### ISSUE TITLE
Way to override Gatsby GraphQL schema for conflicting field types

### ISSUE THREAD

**Issue by njosefbeck** [gatsbyjs/gatsby#10011]
## Summary

First, absolutely love that Gatsby lets me know that there are conflicting field types when it goes to create the GraphQL schema AND tells me what those field types are! Great work there.

I built and maintain a gatsby source plugin for Stripe. The Stripe API has an [Events](https://stripe.com/docs/api/events?lang=node) object that ultimately outputs a list of events related to one's Stripe account. In this event list, you can have a variety of differing Stripe objects. 

For example, when I create a Product, it will log a 'product' event and what shows up in the list is the actual product object. If I create a Sku, it will log a 'sku' event and will output the new sku object in the events list. Thus, ultimately I get something like (simplified):

```
{
  "object": "event",
  "data": {
    "object": "sku",
    "attributes": {
      "name": "My product sku"
    }
},
{
  "object": "event",
  "data": {
    "object": "product",
    "attributes": ['name']
}
```

With the above example of products and skus, both objects in the Stripe API contain an "attributes" key. As can be seen from the example, it's totally OK and understood that for products, "attributes" is an array describing the attributes for the product (i.e. this product contains a name attribute), and then the SKUs for that product have an "attributes" field that is an object, which has the actual attribute values, i.e. `{ name: "My product sku" }`.

So when my source plugin goes to create nodes, all of these nodes are of internal type "StripeEvent", but as described above, some of the data fields are of the same name, but differing types, and thus the 'conflicting field types' warning.

I hesitate to change the attributes key for, say, products, to conform to Gatsby's type checking as this is how the data in the Stripe API is structured. Ideally, there would be a way for me to turn off the type checking, or maybe say, "hey, for this field on this node you can go ahead and accept these types". Maybe this already exists, and I just don't know about it.

Happy to discuss further, and I look forward to everyone's thoughts / suggestions! Thanks for all your hard work :).

**Comment by pieh** [comment]
For now I think easiest way would be create different types of events: i.e. EventSKU, EventProduct - then Gatsby would check for conflicts only inside same type of events.

Other thing to consider - are events something you want to pass to data layer as is?

**Comment by njosefbeck** [comment]
Thanks so much for your response!

I could potentially see making those events into their own types, for GraphQL purposes. I guess that would end up making them into their own nodes as well? I wouldn't want to lose out on the ability to query for all stripe event nodes at once, would be my only concern.

And, my plugin sources all data from Stripe it can, based on what a user specifies they want in gatsby-config. The job of my source plugin is to ensure that the data is as accurate (and as extensive) as possible, so that users can accurately create whatever kind of interface they want.

I'm happy to play around with it a bit more though. I could always rename the fields, so they don't overlap, or something. Would just have to make note of that in my documentation, so that users don't get confused.
