### ISSUE TITLE
[gatsby-source-wordpress]: Using JWT returns 403 Forbidden - Authorization header malformed

### ISSUE THREAD

**Issue by jamie-endeavour** [gatsbyjs/gatsby#10025]
## Description

If I run `gatsby develop` and configure gatsby-source-wordpress to use JWT I am getting the following error:

```
⠈ source and transform nodes
Path: /wp-json
The server response was "403 Forbidden"
Inner exception message: "Authorization header malformed."
error Plugin gatsby-source-wordpress returned an error
```

### Steps to reproduce
- Install the JWT Authentication for WP Rest API Plugin on an instance of WordPress (https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/)

- Update the `gatsby-source-wordpress` options by populating the `jwt_user` and `jwt_pass` values with the user and password required to obtain an access token (I used the admin credentials for my local WordPress build).

### Expected result

When running `gatsby develop` the fetch to the connected WordPress instance should authenticate and should return data.

### Actual result

The following error message is returned for me:

```
⠈ source and transform nodes
Path: /wp-json
The server response was "403 Forbidden"
Inner exception message: "Authorization header malformed."
error Plugin gatsby-source-wordpress returned an error
```

Please note that I attempted to use the WP API outside of Gatsby via Postman and could generate a JWT and call endpoints with the generated JWT token successfully, so this seems to be an issue specific to Gatsby rather than my local WordPress setup.

### Environment

  System:
    OS: macOS 10.14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.1.0 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Firefox: 63.0.1
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.46 => 2.0.46
    gatsby-image: ^2.0.20 => 2.0.20
    gatsby-plugin-manifest: ^2.0.9 => 2.0.9
    gatsby-plugin-offline: ^2.0.13 => 2.0.13
    gatsby-plugin-purgecss: ^2.4.0 => 2.4.0
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1
    gatsby-plugin-sass: ^2.0.4 => 2.0.4
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12
    gatsby-source-filesystem: ^2.0.8 => 2.0.8
    gatsby-source-wordpress: ^3.0.13 => 3.0.13
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8
  npmGlobalPackages:
    gatsby-cli: 2.4.4

**Comment by jamie-endeavour** [comment]
Hey @pieh thanks for the quick response. I've got the output of the console log here:

```
  url: 'http://my-project.local/wp-json',
  auth:
   { username: 'your-htaccess-username',
     password: 'your-htaccess-password' },
  headers:
   { Authorization:
      'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sYXRpbWVyLWhpbmtzLWNtcy5sb2NhbCIsImlhdCI6MTU0MjYzOTk2OCwibmJmIjoxNTQyNjM5OTY4LCJleHAiOjE1NDMyNDQ3NjgsImRhdGEiOnsidXNlciI6eyJpZCI6IjEifX19.pNpq32p5TqM6b4xFY8XCikEn2tPoaZkxVYg_5T9G1ls' } }
```

I hadn't set the htaccess username or htaccess password when I logged the options because I was under the impression that the JWT config wouldn't use them properties. However, I have since tried updating those values to match the `jwt_user` and `jwt_pass` values but I still get the same 403 Authorization header malformed error.

As for Postman, I can create a JWT via postman and query endpoints with the access token in the header as expected, this error only seems to be a problem within the Gatsby plugin.

I did some searching earlier and found of people experiencing a similar issue outside of Gatsby and there was talk about `.htaccess` config, if this helps here is a copy of my .htaccess file:

```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
# END WordPress
```

Thanks again

**Comment by pieh** [comment]
`htaccess_user` / `htaccess_pass` should only be used when you have Basic Auth set on your server

Does token generated by plugin (one you pasted above) works when you fetch with postman? I was testing this few days ago and it did work for me, so I'm not sure what's wrong here

**Comment by jamie-endeavour** [comment]
Okay I've just re-read your last comment and realised that I'm a bit of an idiot 😬
I've commented out the htaccess options in the config and this now seems to be working. 

Thanks again for your help and sorry for wasting your time, I'll close the issue.

**Comment by pieh** [comment]
I didn't realize that using both htaccess and jwt would cause htaccess to "win" and use that. I think this is something that we need to make clearer in docs (and maybe in plugin code to use just JWT if both htaccess and JWT is specified)

**Comment by jamie-endeavour** [comment]
Hey @pieh I would agree yes, that would be useful! Let me know if I can be of any help with that I appreciate you guys will have a lot on!
