### ISSUE TITLE
Use query variables in Graphql on index.js page

### ISSUE THREAD

**Issue by DWebSoft** [gatsbyjs/gatsby#10023]
I am working on tutorial given here https://www.gatsbyjs.org/tutorial/

In it's sixth part (here: https://www.gatsbyjs.org/tutorial/part-six/#create-a-list-of-your-sites-markdown-files-in-srcpagesindexjs), it shows us how to create a list of markdown on index page.

This is the page query it uses to fetch all mark down nodes:
```
export const query = graphql`
  query {
    allMarkdownRemark {
      totalCount
      edges {
        node {
          id
          frontmatter {
            title
            date(formatString: "DD MMMM, YYYY")
          }
          excerpt
        }
      }
    }
  }
`
```

But I want allMarkdownRemark to have limit set on it and it should be passed by a variable as below:

```
export const query = graphql`
  query GetBlogPosts($limit: Int)  {
    allMarkdownRemark (
             limit: $limit
    ){
      totalCount
      edges {
        node {
          id
          frontmatter {
            title
            date(formatString: "DD MMMM, YYYY")
          }
          excerpt
        }
      }
    }
  }
`
```
This code works, but I don't know how to set that $limit variable.

In case of createPages API we use context to send data as GraphQL variables to pages created using createPage() function, but this page (index,js) is not created by that function.

Then how to pass query variable in such pages?

**Comment by LekoArts** [comment]
Why do you need a variable there? You only use this page once, so just use a number for the limit.

**Comment by DWebSoft** [comment]
Thanks, @LekoArts for the quick reply. Above one is given just as an example. 
I'm a WordPress developer and used to set global settings for displaying the number of posts in WordPress. 

The good example here can be: 
I have created multiple pages for categories e.g. food.js, movie.js, tech.js using React components. There I have added some static content same as index.js and want to show the list of posts in that category. 
So instead of hardcoding limit in each page, I thought it would be better if I can have that variable in some kind of global config files. And that should be available as query variables in Page Query.

I know there might be a better way to create the above solution but I am just keen to know if something like can be done or not. 

I just started learning Gatsby and I'm loving it :)
Also, I'm new to GraphQL, so let me know if I'm going a wrong way.

**Comment by DWebSoft** [comment]
Thanks, @LekoArts for the update. I was able to achieve the result with the method you stated above. Thanks again.

**Comment by j127** [comment]
> You create your pages as normal in src/pages and then use the onCreatePage API to first delete those pages and then re-create them with context.

I'm having a similar problem (described [here](https://stackoverflow.com/questions/56448610/graphql-arguments-in-gatsbyjs-from-context-in-gatsby-node-js)). Do the pages always have to be manually deleted before variables defined in `gatsby-node.js`'s `context` are available in graphql queries? Or is that just for editing and resaving pages after they have been created?

```javascript
context: {
    currentDate: currentDate,
    minusFiveDays: minusFiveDays,
},
```
```javascript
export const pageQuery = graphql`
    query($minusFiveDays: Date!) { // this is the key from the file above
        allMarkdownRemark(
            filter: {
                frontmatter: {
                    content_type: { eq: "some_content_type" }
                    start_date: { ne: null, gte: $minusFiveDays }
                }
            }
            sort: { order: ASC, fields: [frontmatter___start_date] }
```

The query can't see the `context`:

```text
'Errors: Variable "$minusFiveDays" of required type "Date!" was not provided.'
```

**Comment by jevenson** [comment]
@j127 I'm seeing the same issue, do you remember finding a solution?

**Comment by j127** [comment]
Sorry, I don't think I solved it. I don't remember what the problem was but that code is commented out in my project so I think I gave up and implement a hack just to get that part of the site online.
