### ISSUE TITLE
gatsby-image fluid queries with maxWidth not displaying large portrait oriented images

### ISSUE THREAD

**Issue by wwrightiv** [gatsbyjs/gatsby#10029]
## Description

I'm using contentful for my data. I have a fluid image query that works fine, but if I set a maxWidth on the query, some of my portrait oriented images do not appear on the UI until the screen is scaled down. This only affects portrait images, and only happens if I set a maxWidth above 1000 or so. I've been pulling my hair out over this for a week or so. **If I don't set a maxWidth on the query, the images display fine**, but they default to a small resolution. Is there something I'm missing here?

Here's the query, which works fine in the graphIQL playground 
![screen shot 2018-11-19 at 11 48 31 am](https://user-images.githubusercontent.com/11726243/48722032-13679000-ebf1-11e8-85f2-12bfa66ca819.png)

Here's where I'm using the gatsby-image Img component
![screen shot 2018-11-19 at 11 53 29 am](https://user-images.githubusercontent.com/11726243/48722345-c89a4800-ebf1-11e8-9966-836f6e0218f8.png)

### Environment

System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Firefox: 63.0.1
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.50 => 2.0.50
    gatsby-cli: ^2.4.5 => 2.4.5
    gatsby-image: ^2.0.20 => 2.0.20
    gatsby-plugin-canonical-urls: ^2.0.5 => 2.0.7
    gatsby-plugin-feed: ^2.0.5 => 2.0.9
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.7
    gatsby-plugin-manifest: ^2.0.2 => 2.0.9
    gatsby-plugin-netlify: ^2.0.0 => 2.0.5
    gatsby-plugin-nprogress: ^2.0.5 => 2.0.6
    gatsby-plugin-offline: ^2.0.5 => 2.0.15
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.2
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.2
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.2
    gatsby-remark-images-contentful: ^2.0.0 => 2.0.3
    gatsby-remark-prismjs: ^3.0.0 => 3.0.3
    gatsby-source-contentful: ^2.0.14 => 2.0.14
    gatsby-source-filesystem: ^2.0.1 => 2.0.8
    gatsby-transformer-remark: ^2.1.3 => 2.1.12
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8
  npmGlobalPackages:
    gatsby-cli: 2.4.5

**Comment by wwrightiv** [comment]
This is the only way I can get **all** of my images to display
![screen shot 2018-11-19 at 1 16 19 pm](https://user-images.githubusercontent.com/11726243/48726438-562f6500-ebfd-11e8-95d0-ec43e510c0a0.png)
![screen shot 2018-11-19 at 1 16 37 pm](https://user-images.githubusercontent.com/11726243/48726447-61829080-ebfd-11e8-96c3-1b973b329e59.png)

**Comment by pieh** [comment]
How does your html output looks like? Can you inspect it and check if urls used in `<img>` tag works? It might be either some limitation in contentful asset API or something on our side that interacts with API wrong

/cc @Khaledgarbaya

**Comment by wwrightiv** [comment]
> How does your html output looks like? Can you inspect it and check if urls used in `<img>` tag works? It might be either some limitation in contentful asset API or something on our side that interacts with API wrong
> 
> /cc @Khaledgarbaya

Here's the url in the ``<img>`` tag:

![screen shot 2018-11-19 at 2 49 51 pm](https://user-images.githubusercontent.com/11726243/48731220-947f5100-ec0a-11e8-8329-66d9ae10e528.png)

**Comment by wwrightiv** [comment]
@pieh I think this has to do with retina screens. I have two monitors - one retina, one standard resolution. On my retina monitor, the images do not appear until the browser window gets below 1385 pixels and on my non retina monitor, they appear at all window widths

**Comment by wwrightiv** [comment]
This definitely has to do with the contentful fluid query and the aspect ratio of the image. I just tested passing the data to a normal ``<img>`` element and the image still doesn't appear above 1385px screen width on retina displays. The aspect ratio is 0.625. However an image with an aspect ratio of .667 displays fine on all sizes.

**Comment by wwrightiv** [comment]
I've done some more testing and now I've come to believe that the issue it a combination of high resolution, portrait images on retina screens and the contentful api. After resizing the image that wouldn't display from 4000w x 6000h to 2000w x 3000h it displayed fine. Closing as this seems like a contentful problem and not gatsby.
