### ISSUE TITLE
[v2] navigate replace `//` by `/`

### ISSUE THREAD

**Issue by thomasMary** [gatsbyjs/gatsby#10028]
## Description

Describe the issue that you're seeing.
Calling gatsby function `navigate` with double '/' in the url will be replace by a single one.
e.g. `example?url=https://github.com` will become `example?url=https:/github.com`

=> This is where the issue is: https://github.com/gatsbyjs/gatsby/blob/3c824f3bf648a137b3e69514c0fa359966680b3c/packages/gatsby-link/src/index.js#L12
Not sure the reason why it's there in the first place, but I would be nice for the query parameters to be left as provided.

### Steps to reproduce

From the documentation: https://www.gatsbyjs.org/docs/gatsby-link/#programmatic-navigation
Change the url to `example?url=https://github.com`
```
import { navigate } from "gatsby"

render () {
  return (
    <div onClick={ () => navigate('example?url=https://github.com')} role="link" tabIndex="0" onKeyUp={this.handleKeyUp}>
      <p>Example</p>
    </div>
  )
}
```

### Expected result

On click, I expect to navigate to: `example?url=https://github.com`

### Actual result

On click, I navigate to `example?url=https:/github.com`
(note the single `/` in the url)

### Environment

  System:
    OS: macOS 10.14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
    Yarn: 1.10.1 - ~/.nvm/versions/node/v10.10.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Firefox: 63.0.1
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.44 => 2.0.44 
    gatsby-image: ^2.0.20 => 2.0.20 
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4 
    gatsby-plugin-manifest: ^2.0.8 => 2.0.8 
    gatsby-plugin-netlify: ^2.0.4 => 2.0.4 
    gatsby-plugin-offline: ^2.0.13 => 2.0.13 
    gatsby-plugin-page-creator: ^2.0.4 => 2.0.4 
    gatsby-plugin-polyfill-io: ^1.0.5 => 1.0.5 
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.1 
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0 
    gatsby-plugin-root-import: ^2.0.4 => 2.0.4 
    gatsby-plugin-sass: ^2.0.4 => 2.0.4 
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12 
    gatsby-plugin-stripe-elements: ^1.0.9 => 1.0.9 
    gatsby-plugin-styled-components: ^3.0.1 => 3.0.1 
    gatsby-source-filesystem: ^2.0.8 => 2.0.8 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8

**Comment by jgierer12** [comment]
Gatsby's `<Link>` and, by extension, the `navigate` function, should [only be used for internal links](https://www.gatsbyjs.org/docs/gatsby-link/#use-link-only-for-internal-links). Since paths containing multiple consecutive slashes are considered bad practice, and can cause inconsistencies in some servers and/or browsers, Gatsby removes consecutive slashes.
