### ISSUE TITLE
gatsby develop is successful but build fails

### ISSUE THREAD

**Issue by khus29** [gatsbyjs/gatsby#10038]
Gatsby build giving following error

`info bootstrap finished - 11.285 s

error Generating JavaScript bundles failed

  Error: ./.cache/data.json
  Module Error (from ./node_modules/stylelint-custom-processor-loader/dist/index.js):

  .cache/data.json
   1:8  ×  Unexpected token, expected ";" (1:8)

   @ ./.cache/async-requires.js 25:9-54
   @ ./.cache/production-app.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! site-generator@1.0.0 build: `npx gatsby build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the site-generator@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

Please help.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
Post `gatsby info --clipboard` and if the work you're doing is not private or otherwise protected a repository url so that the issue can be looked at in more detail if you don't mind

**Comment by kepi** [comment]
Same problem on my system, here is output of `gatsby info`. Unfortunatelly I can't provide repo url.

```
  System:
    OS: Linux 4.18 Debian GNU/Linux buster/sid undefined
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Shell: 5.6.2 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 63.0.3
  npmPackages:
    gatsby: ^2.0.50 => 2.0.67 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12 
    gatsby-plugin-offline: ^2.0.15 => 2.0.19 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.4 
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0 
    gatsby-plugin-sass: ^2.0.4 => 2.0.7 
    gatsby-plugin-styled-components: ^3.0.2 => 3.0.4 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.0.8 => 2.0.12 
    gatsby-transformer-orga: ^0.6.3 => 0.6.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.6
```

**Comment by kepi** [comment]
Ok, I think I found the problem. There is rule in webpack config in `gatsby-node.js`:

```json
        {
          test: /\.jsx?/,
          loader: "stylelint-custom-processor-loader",
          exclude: /node_modules/,
        }
```

Test condition is wrong, as it is checking every file which has `.js` inside, not as extension. Adding `$` for end of string to text regexp should do the work (and it did in my case). Thats what we get when copy pasting ;)

```json
        {
          test: /\.jsx?$/,
          loader: "stylelint-custom-processor-loader",
          exclude: /node_modules/,
        }
```

**Comment by sidharthachatterjee** [comment]
@khus29 Closing this for now since it seems stale but in case you're still seeing this please feel free to reopen and comment with a reproduction. Thanks!
