### ISSUE TITLE
Can a custom component renderer be passed to gatsby-plugin-create-client-paths such as the demo PrivateRoute component?

### ISSUE THREAD

**Issue by tylerssn** [gatsbyjs/gatsby#10032]
I am attempting to use the demo PrivateRoute component to restrict access to the path `/app` using the plugin: `gatsby-plugin-create-client-paths`.

Is it possible to have this plugin render using a custom component?

**Comment by pieh** [comment]
I'm not sure what do you mean? Do you mean this demo - https://github.com/gatsbyjs/gatsby/tree/master/examples/simple-auth ? Also you can modify `app.js` page / template however you like

**Comment by tylerssn** [comment]
I was referring to https://www.gatsbyjs.org/docs/building-a-site-with-authentication/.

I was under the impression that I was meant to "inject" the PrivateRoute component via the `gatsby-config.js` for the plugin. Just my freshmen logic shining through, I suppose.

I don't know how "right" this is, but I ended up settling on:

```jsx
  <PrivateRoute>
    <Layout>
      <h1>NO!</h1>
      <p>Looks like you are authenticated.</p>
      <button onClick={() => logout(() => navigate('/app'))}> Logout</button>
    </Layout>
  </PrivateRoute>
```
