### ISSUE TITLE
Media players and Gatsby #2

### ISSUE THREAD

**Issue by johnelliott** [gatsbyjs/gatsby#10035]
## Summary

My first issue 😄

Add media file regex to plugin-offline workbox [`navigateFallbackBlacklist` list](https://github.com/gatsbyjs/gatsby/blob/7c826a17219053421a85a75038474843f581e026/packages/gatsby-plugin-offline/src/gatsby-node.js).

### Basic example

```javascript
        navigateFallbackBlacklist: [
          /\?(.+&)?no-cache=1$/,
          /\.(mp3|mp4|m4a)(\?.*)?$/
        ]
```
### Motivation

I was experiencing some audio player slowness and saw that the service worker appeared to be intercepting requests for my mp3 files from an HTML5 audio tag. This appeared to be preventing HTTP 1.1 range requests and I saw my file loading all at once. This was in Safari 12.

cURL confirmed that my host (firebase) could handle the range requests and send back HTTP 206 status codes. 

I added ?nocache=1 to my HTML5 audio tag URLs and saw that I was getting successful range requests. This appears to be a way around the service worker issue.

Adjusting the default for common file types could help others and provide a better out-of-the-box experience. Alternate solutions could be adding to documentation or doing nothing.

**Comment by jgierer12** [comment]
Hmm, based on this it should already exclude any URLs with extensions:

https://github.com/gatsbyjs/gatsby/blob/7c826a17219053421a85a75038474843f581e026/packages/gatsby-plugin-offline/src/gatsby-node.js#L83-L92

**Comment by johnelliott** [comment]
Hmm is that for the white list or black list?

**Comment by johnelliott** [comment]
I may be misunderstanding, but using regex101.com I didn't see `.mp3` matching either of the regular expressions that the plugin has for the whitelist or the blacklist. Perhaps I am not trying a proper URL string.

**Comment by johnelliott** [comment]
Thank you. I did see where the options went, I just read the effects backward. I think I will just close this. I’m just glad folks can now search this in closed issues if the question arises for others.

**Comment by jgierer12** [comment]
I'm not sure if this should be closed yet: If the whitelist regex doesn't match your media URLs, then why is the service worker intercepting them? Maybe I am just misunderstanding you, does it work now without `?nocache=1`?
