### ISSUE TITLE
Manual Entry of route doesn't work with Back Button

### ISSUE THREAD

**Issue by a-botermans** [gatsbyjs/gatsby#10046]
## Description

When accessing a route manually and then navigating the back button will skip one step and ignore the manually accessed route.

### Steps to reproduce

Reproduction Repo : https://github.com/a-botermans/test-case-history-bug
Test URL : https://confident-goldstine-20bc0e.netlify.com

1) Click on News Item 2
2) Change URL manually into /blog
3) Click on Blog Item 2
4) Use Browser back button you end up on News Item 2

### Expected result

Back button should send you to /blog

### Actual result

Back button sends you to /news/item-2 skipping one step in your navigation history

### Environment
```
  System:
    OS: macOS 10.14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v9.11.1/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.19 => 2.0.19 
    gatsby-image: ^2.0.15 => 2.0.15 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5 
    gatsby-plugin-offline: ^2.0.11 => 2.0.11 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.7 
    gatsby-source-filesystem: ^2.0.4 => 2.0.4 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

**Comment by jonniebigodes** [comment]
I believe that this is related to #8357 . It has been confirmed and being checked and being addressed.

**Comment by a-botermans** [comment]
Duplicate of #8357
