### ISSUE TITLE
Smart source-plugin bulk fetching remote file assets

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#10049]
(from a conversation with @KyleAMathews )

**Problem**: People are  frustrated by long build times driven by downloading data from Wordpress

**Cause**: Say gatsby-source-wordpress hits a Wordpress site and starts downloading 10,000 images. This creates problems on a number of levels. Often the receiving Wordpress site can’t deal with so many open connections. It overwhelms the Wordpress site, the server starts running out of memory, and the download slows down or fails altogether

**Proposed solution**: This is a two-part solution -- (1) fundamental technical improvement (2) better UX for users.

- We need more robust downloading of files (for createRemoteFileNode). 
	- We need a file throttler / ConnectionHandler  to manage connections to the remote Wordpress server.
	- It would be powered by an algorithm deciding how many connections to open. The algorithm would do this by track bytes / second downloaded, and continuing to add open connections until the bytes/second rate stalls out. 
	- There’s potential other, simpler, options like “don’t have more than X open connections”
	- Download manager would add new files, make sure that remote server isn’t getting overloaded.
	- Exponential backoffs.
- Provide visibility of download process to user
	- Showing file download count // download progress for remote files -- “we’re downloading 250 of 500 files, eta 5:00” -- reduce user frustration

**Similarity to other systems**:

- @KyleAMathews has tweeted out looking at this problem, and looked for packages that handle connections in Wordpress side. So far, this search has come up blank. 
- Similar problem to the what rsync does -- we’re trying to sync files through smart management of server 
- Also similar to the strategy a lot of browsers use -- TCP --  get initial byte, doubling download speed, exponential backoff, fixed max # of simultaneous open connections….

**Comment by TylerBarnes** [comment]
This plugin handles transferring media files from wp site to wp site. 
https://github.com/wp-sync-db/wp-sync-db-media-files
It might be useful for getting some ideas. I've used it and it works well

**Comment by muescha** [comment]
This download manager should also include an cache and some strategies how not redownload media assets when nothing is changed.

**Comment by muescha** [comment]
Is there also a stragegy only to download the used media assets (when maybe more assets are saved in wordpress but only some used in the used articles)?

**Comment by cedricdelpoux** [comment]
Any news about this issue?
