### ISSUE TITLE
Window

### ISSUE THREAD

**Issue by adnxy** [gatsbyjs/gatsby#10044]
## Description

I'm trying to integrate amplitude-js with React and Gatsby. Everything looks good when doing gatsby developer since it's happening inside the browser, but when I try gatsby build I get the following error because Gatsby build is happening on the server where we don't have window object: 

 WebpackError: window is not defined

  - amplitude.js:2428
    ~/amplitude-js/amplitude.js:2428:2

Here is my amplitude module: 

```
import amplitude from 'amplitude-js';

amplitude.getInstance().init('API-KEY', null, {
  // optional configuration options
  saveEvents: true,
  includeUtm: true,
  includeReferrer: true,
});

```
### Steps to reproduce

-gatsby build 

### Expected result

Gatsby build should work

### Actual result

Gatsby build is not working: window is not defined.

If if I'm not using this part anywhere in a project error is pointing to this part:

```
  2426 | if (windowLocalStorageAvailable()) {
  2427 |   localStorage = window.localStorage;
> 2428 | } else if (window.globalStorage) {
       |  ^
  2429 |   // Firefox 2-3 use globalStorage
  2430 |   // See https://developer.mozilla.org/en/dom/storage#globalStorage
  2431 |   try {

```
### Environment

 ```
 System:
    OS: macOS High Sierra 10.13.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Safari: 11.1
  npmPackages:
    gatsby: ^1.9.277 => 1.9.278
    gatsby-link: ^1.6.46 => 1.6.46
    gatsby-plugin-eslint: ^2.0.1 => 2.0.1
    gatsby-plugin-page-transitions: ^1.0.7 => 1.0.7
    gatsby-plugin-postcss-sass: ^1.0.22 => 1.0.22
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11
    gatsby-plugin-sass: ^1.0.26 => 1.0.26
    gatsby-source-shopify: ^1.1.1 => 1.1.1
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

**Comment by jgierer12** [comment]
You can skip the client-side only code during SSR like so:

```js
import amplitude from 'amplitude-js';

if (typeof window !== 'undefined') {
  amplitude.getInstance().init('API-KEY', null, {
    // ...
  });
}
```

**Comment by adnxy** [comment]
It's not helping, still getting the same error from above @jgierer12

**Comment by jgierer12** [comment]
Do you use `amplitude` anywhere else in your project? Or does the library run code when it's imported?

It would be way too ambitious for Gatsby to decide whether or not something should be run during SSR. This should be decided either by yourself, by doing a `typeof window !== 'undefined'` check everywhere it's used, or by the library itself.
