### ISSUE TITLE
Better default for gatsby-remark-copy-linked-files

### ISSUE THREAD

**Issue by lekevicius** [gatsbyjs/gatsby#10048]
## Summary

Default for file URLs should be `hash/filename.ext`, not `filename-hash.ext`

### Basic example

Currently the default is `file.pdf` -> `file-ea0f4f14f1b991e92c681da93172497d.pdf`. 

It is set in [this function](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-copy-linked-files/src/index.js#L21):

```js
const newFileName = linkNode =>
  `${linkNode.name}-${linkNode.internal.contentDigest}.${linkNode.extension}`
```

I suggest to make the default URL be:

```js
const newFileName = linkNode =>
  `${linkNode.internal.contentDigest}/${linkNode.name}.${linkNode.extension}`
```

This would follow the general structure of gatsby-image paths, and make downloaded file name much nicer.

If default is not changed then at least this should be a customizable option, perhaps a function that could be passed.

### Motivation

Currently, for every user downloading the file, filename is very long. In many cases the "hash" part is much longer than the actual file name. Default setting should be nicer.

**Comment by pieh** [comment]
I think that's good idea - we would possibly need to ensure that extra directory exists.

@lekevicius would you be interested in creating PR with this change?

**Comment by KyleAMathews** [comment]
Yeah this would be a good change. We made the same change for image paths.

**Comment by lekevicius** [comment]
The Kyle has spoken.

I'll try to make a PR this week.

**Comment by kimbaudi** [comment]
Hi, I would like to implement this feature. I will submit a PR shortly 🤞

**Comment by kimbaudi** [comment]
Hi, I completed implementing this feature (https://github.com/kimbaudi/gatsby/commit/f7fbd10d2268a4848df7993910d52680516ead5b):
1. change the default destination format from `filename-hash.ext` to `hash/filename.ext`
2. allow customization of the destination format:
    ```js
    destinationDir: f => `${f.hash}/${f.name}`  // f7fbd/myfile.txt
    destinationDir: f => `${f.name}-${f.hash}`  // myfile-f7fbd.txt
    destinationDir: f => `foo${f.hash}---${f.name}bar`  // foof7fbd---myfilebar.txt
    destinationDir: f => `foo${f.hash}/${f.name}bar`  // foof7fbd/myfilebar.txt
    ```

I perform same validation to make sure that the path is a child of `public` folder:

```js
destinationDir: `../`  // error
destinationDir: `../foo`  // error

destinationDir: _ => `../`  // error
destinationDir: _ => `../foo`  // error
destinationDir: f => `../${f.hash}/${f.name}`  // error
```

I even gracefully handle invalid `destinationDir` options:

```js
destinationDir: _ => ``  // f7fbd/myfile.txt
destinationDir: _ => `foobar`  // foobar/f7fbd/myfile.txt
destinationDir: f => `what${f.foo}${f.bar}`  // whatf7fbd/myfile.txt
destinationDir: f => `what/${f.foo}${f.bar}`  // what/f7fbd/myfile.txt
```

I still need to write unit tests, but wanted to share my status :smile:
