### ISSUE TITLE
[gatsby-plugin-sharp] Skip processing images with no ICC input profile

### ISSUE THREAD

**Issue by discovrbookings** [gatsbyjs/gatsby#10040]
I am having an issue with embedded ICC profiles that do not match (e.g. CMYK profile for RGB image) when using [gatsby-plugin-sharp][1]. 

Currently the troublesome images generate the embedded profile incompatible with image error and the processing of all fetched images fails.

Could this be reduced to a warning and ignore the profile to carry on processing the remaining fetched images.

Here is a sandbox of the issue - [https://codesandbox.io/s/jj597mrvmw][3]

The error I receive is 

     error
    The GraphQL query from /sandbox/src/templates/event.js failed.
    
    Errors:
      icc_transform: no input profile
      vips_colourspace: no known route from 'cmyk' to 'srgb'
    
    
      GraphQL request (9:11)
       8:         childImageSharp {
       9:           fluid(maxWidth: 1800) {
                    ^
      10:             ...GatsbyImageSharpFluid
    
    URL path:
      /event/fastlove-:-a-tribute-to-george-michael/
    Context:
      {
        "id": "5f9b3031-ef73-5884-9893-da56317daf3b",
        "slug": "fastlove-:-a-tribute-to-george-michael"
      }
    Plugin:
      none
    Query:
      query sandboxSrcTemplatesEventJs3738613760(
        $slug: String!
      ) {
        allFile(filter: {fields: {slug: {eq: $slug}}}) {
          edges {
            node {
              id
              childImageSharp {
                fluid(maxWidth: 1800) {
                  ...GatsbyImageSharpFluid
                }
              }
              fields {
                name
                slug
              }
            }
          }
        }
      }
    
      fragment GatsbyImageSharpFluid on ImageSharpFluid {
        base64
        aspectRatio
        src
        srcSet
        sizes
      }
    
    
    (sharp:5650): GLib-CRITICAL **: 16:17:47.149: g_hash_table_lookup: assertion 'hash_table != NULL' failed
    
    (sharp:5650): GLib-CRITICAL **: 16:17:47.149: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
    
    (sharp:5650): GLib-CRITICAL **: 16:17:47.149: g_hash_table_lookup: assertion 'hash_table != NULL' failed
    Segmentation fault (core dumped)
    error Command failed with exit code 139.

When running the process during `build` or `develop`

    exports.sourceNodes = async ({ actions, store, cache, createNodeId }) 
    => {
      const { createNode, createNodeField } = actions;
      const { data } = await axios.get(API_URI);
    
      for (const event of data._embedded.events) {
        let fileNode;
        let output = [];
        let filterResults = event.images.filter(e => e.width >= 1900);
        output.push(...filterResults);
        try {
          fileNode = await createRemoteFileNode({
            url: output[0].url,
            cache,
            store,
            createNode,
            createNodeId,
          });
          await createNodeField({
            node: fileNode,
            name: 'EventImage',
            value: 'true'
          });
          await createNodeField({
            node: fileNode,
            name: 'name',
            value: event.name
          });
        } catch (error) {
          console.warn('error creating node', error);
        }
      }
    };

  [1]: https://www.npmjs.com/package/gatsby-plugin-sharp
  [3]: https://codesandbox.io/s/jj597mrvmw

**Comment by pieh** [comment]
I will try to take a look at this tomorrow - defenitely can see same error in code sandbox repro. There are 2 possibilites - either we are doing something really wrong, or just `sharp` or rather vips_colourspace has bug or limitation.

Is this essentially duplicate of https://github.com/gatsbyjs/gatsby/issues/9980 ? If so I will close one of those

**Comment by discovrbookings** [comment]
Thank you @pieh. Yes it is a duplicate - I thought the new question better explained the issue and forgot to close the previous. Sincere apologies. 

I did notice over on the `sharp` repository they had a similar [issue](https://github.com/lovell/sharp/issues/99) but it appears to have been fixed in a later commit.

Thank you again for your time and I look forward to your thoughts.

**Comment by discovrbookings** [comment]
Yes, it does appear to be. 

However because the process fails, it is hard to know whether there may be more images. I believe this image is around 61 - 70 in the API `fetch` and if I reduce the `fetch` limit to `60` there is not an issue. 

Being that the site will be deployed daily and the API `data` will be updated, the issue could appear at anytime for any image.

**Comment by pieh** [comment]
Oh for sure - I'm not saying to get rid of that image - I'm just trying to document as I go, so if needed it's easier to reproduce problem and potentially create minimal reproduction to submit issue to `sharp` repo.

**Comment by discovrbookings** [comment]
Hey @pieh just wanted to follow up and see if you had any more thoughts to this bug. 

I had wondered whether using `GATSBY_JPEG_ENCODER=MOZJPEG` would help the issue but on reading the README [documentation](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/README.md) for Gatsby I found that the the link within 

> To enable MozJPEG set the environment variable:
is not working. Could you please advise the correct `url` as to help with understand how to implement this. Cheers.

**Comment by discovrbookings** [comment]
Thank you @polarathene. This does remove the error `no ICC input profile`. However, now only to be replaced with `error GraphQL Error Unknown field 'childImageSharp' on type 'File'`. Any ideas why?
