### ISSUE TITLE
Expose a Component globally?

### ISSUE THREAD

**Issue by hassanshaikley** [gatsbyjs/gatsby#10068]
How can one expose a component globally so that it's available to the SSR APIs and everything else. 

Just to make it easier for people to use (so they don't have to import).

I tried modifying the global object in the plugin to no avail.

**Comment by hassanshaikley** [comment]
I just don't want to have to import in all the files. I want including a plugin to make components available.

**Comment by jgierer12** [comment]
While I'm not sure whether or not that is possible with Gatsby's current plugin system, I know for sure that I wouldn't want to use a plugin that pollutes my global namespace. What's wrong with importing the component where you need it? Unless there's a good reason to make the component global, it would just take away control from the developers who want to use your plugin.

**Comment by jonniebigodes** [comment]
My thoughts exactly @jgierer12 . Because and if understanding this correctly, in a nutshell you're planning to reinvent the wheel here

**Comment by hassanshaikley** [comment]
Well, I also want to expose some variables globally. : /

I have my reasons d: !

**Comment by jonniebigodes** [comment]
Given that and based on what me and @jreidgreer said, i'm more inclined to believe that the best approach you have is to go the ref way like i said before.

**Comment by hassanshaikley** [comment]
I want to have a component called ButtonX1 and be able to use it without importing it.

So like  what I mean is a plugin creates ButtonX1 and then you're able to use it wherever without importing it.

**Comment by LekoArts** [comment]
As the others said I wouldn’t recommend doing that and I wouldn’t want to use a plugin that just imports things everywhere — that totally defeats the purpose of code-splitting.
I'm closing this as imo such bad practice shouldn’t get into Gatsby’s plugins.
