### ISSUE TITLE
Dynamic Routes via gatsby-plugin-create-client-paths receive NGINX 404

### ISSUE THREAD

**Issue by luskin** [gatsbyjs/gatsby#10070]
## Description

When deployed and served our gatsby app produces NGINX 404 errors when trying to access a dynamic route created by `gatsby-plugin-create-client-paths`. All this works locally when in development but breaks when deployed to Heroku and served via CloudFlare.

### Steps to reproduce

in `gatsby-config.js`:
```
    {
      resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`'/quote/*'] }
    },
```

in our `src/pages` folder we have a quote.js file that reads the * after /quote and displays content accordingly.

### Expected result

The `quote.js` page should be displayed, no 404 error.

### Actual result

*NGINX 404 ERROR*

<img width="381" alt="screen shot 2018-11-21 at 10 27 47 am" src="https://user-images.githubusercontent.com/5702322/48861306-1d67cb00-ed78-11e8-94af-3869b6bbb69a.png">

**Comment by pieh** [comment]
Hey, you need to adjust nginx config to serve `/quotes/index.html` when accessing `/quotes/*` routes. This is not something that gatsby can control as mentioned in https://www.gatsbyjs.org/docs/building-apps-with-gatsby/#client-only-routes--user-authentication

> These routes will exist on the client only and will not correspond to index.html files in an app’s built assets. If you’d like site users to be able to visit client routes directly, you’ll need to set up your server to handle those routes appropriately.

We should expand docs there to add example configuration for popular servers (including `ngingx`)

**Comment by elrumordelaluz** [comment]
As @pieh pointed, something like this works for me:

```vim
location /quotes/ {
  try_files $uri $uri/ /quotes/index.html;
}
```

**Comment by gendronb** [comment]
@pieh 

The fix mentionned in https://stackoverflow.com/questions/52051090/gatsbyjs-client-only-paths-goes-to-404-page-when-the-url-is-directly-accessed-in for Heroku doesn't work.

I tried to deploy the client-only-paths example to Heroku, using https://www.gatsbyjs.org/docs/deploying-to-heroku/ as guidelines, and adding a static.json as mentionned in https://github.com/heroku/heroku-buildpack-static : 
```
{
    "root": "public/",
    "routes": {
        "/static/*": "/static/",
        "/**": "index.html"
    }
  }
```
but loading any client-only route will still fail with 404 status (try https://salty-waters-64986.herokuapp.com/page/3)...

If someone manages to make this work, I will pleased to help writing some documentation regarding this aspect...

**Comment by jufemaiz** [comment]
*follow*

I'm trying to do this with the static site build and am finding it unlikely to work, even with a workaround to route all requests through the "application" page.

I like the idea of gatsby, but particularly for static deployment, it's lacking in a number of areas in providing known solutions and best practices :(

**Comment by jufemaiz** [comment]
No worries. It’s a little hacky but it meets the requirements. 

Still working out what to do for a noscript option though.

**Comment by eknowles** [comment]
@jufemaiz this means the server responds with a 404 status code which messes up logs and analytics. I'm trying to get this working on Azure Verizon CDN which is awful.

**Comment by FredericMartinez** [comment]
FYI, For Apache => https://www.gatsbyjs.org/packages/gatsby-plugin-htaccess/

Like the doc says:
```
npm install gatsby-plugin-htaccess
# or
yarn add gatsby-plugin-htaccess
```

Add to plugins in your `gatsby-config.js`:
```
module.exports = {
  plugins: ['gatsby-plugin-htaccess'],
}
```

I think I have lost 4+ hours on a bad custom `.htaccess`, and I just found this plugin..

And it works like a charm!

**Comment by eknowles** [comment]
For any users with Azure Verizon CDN, my solution was to add a URL rewrite rule.

My rule
<img width="1868" alt="Screenshot 2019-07-28 at 14 08 38" src="https://user-images.githubusercontent.com/817611/62007095-57784080-b141-11e9-8991-fa92a7099a9f.png">

documentation around this syntax is at https://docs.microsoft.com/en-us/azure/cdn/cdn-verizon-premium-rules-engine-reference-features#url-rewrite

**Comment by derakhshanfar** [comment]
@elrumordelaluz 
I'm trying to serve my gatsby in /blog route with Nginx that's why I built gatsby with **_blog_** prefix. I have a dynamic route called /admin which can access it in /blog/admin. and my Nginx config is this:
```
http {    
  server {
    listen 80; 
    server_name localhost; 
    client_max_body_size 10M;      
    
    location /blog {   
      root /usr/share/nginx/html;
      location /blog/admin {
        try_files $uri $uri/blog /blog/admin/index.html;
      }           
    }      
    
    location / {            
      proxy_pass http://web1:8080;         
    }
  }  
}
```
as you can see in / location I used proxy_pass and in /blog location I served gatsby static files but when I visit **/blog/admin/myClientRoute** I can not see **myClientRoute** component and in console, I see this error:
![Screenshot from 2019-08-26 16-47-19](https://user-images.githubusercontent.com/18225394/63690210-4b0b0480-c821-11e9-9567-1c3a05b8a3b3.png)
Actually Requests for page-data.json return 404 in client-side routes.
Do you have any solutions?
Thanks in advance

**Comment by valse** [comment]
Hi @derakhshanfar, I had the same problem: I solved adding the `pathPrefix` in the router client `path`:
```
<Router>
   <Loader
     path={`${pathPrefix}/preview/:guid`}
   />
</Router>
```
I think that it  should be fixed in the `gatsby-plugin-create-client-paths` plugin directly

**Comment by derakhshanfar** [comment]
Hi @valse. Thanks a ton man! It worked! you saved my life :-D

**Comment by valse** [comment]
I found a more elegant solution importing the helper function `withPrefix` from `gatsby`
```
import { withPrefix } from 'gatsby'
<Router>
   <Loader
     path={withPrefix('/preview/:guid')}
   />
</Router>

**Comment by derakhshanfar** [comment]
@valse Great man. Thanks very much!

**Comment by endigo** [comment]
What about in S3 and CloudFront? How to fix this issue?

**Comment by vamshi9** [comment]
@endigo I am facing similar issue in s3 and cloudfront. When I refresh the browser, the page first shows 404 page and then immediately shows the actual page. Please let me know if you've any idea about it.

**Comment by kurtobando** [comment]
Hello, I seen your inputs here, and i understand the idea redirect client side routes to the /app/index.html, for us to get a working dynamic routes, however, could someone share there .htaccess rules, if you have xp in deploying your app in apache.

I find it challenging on where to start with htaccess. Inputs are highly appreciated.

**Comment by kulahin** [comment]
`rewrite ^/products/([0-9]*)$ /products/[id]/index.html;`
or
`rewrite ^/users/confirm/(.*)$ /users/confirm/[code]/index.html;`
etc.

Just go to your production root and look for the correct path to the _index.html_ file for your case.

**Comment by mariovde** [comment]
How can this be fixed when you have no control of your hosting (just bought some cheap hosting...).
Don't think I have access to those config files...

**Comment by dmanaster** [comment]
Like @gendronb I am trying to find a fix for this on Heroku. Has anyone made this work? I do not see a solution anywhere, after hours of searching.

I've opened up a new [StackOverflow question](https://stackoverflow.com/questions/71113925/gatsby-api-route-working-in-dev-environment-but-getting-a-404-on-heroku) for this also to try to give it more visibility.

**Comment by cryptocommerceshop** [comment]
> I found a more elegant solution importing the helper function `withPrefix` from `gatsby`
> 
> ```
> import { withPrefix } from 'gatsby'
> <Router>
>    <Loader
>      path={withPrefix('/preview/:guid')}
>    />
> </Router>
> ```

For anyone who might overlook this like I did, take note if you have a `basepath` on your ```<Router>```, you would need to add it there instead:

```<Router basepath={withPrefix('/a')} className="h-full">```

Otherwise the prefix will get inserted between your base path and loader path.
