### ISSUE TITLE
Bug? on official website

### ISSUE THREAD

**Issue by sidbentifraouine** [gatsbyjs/gatsby#10074]
## Description
Here is a gif:

![nov-21-2018 20-42-26](https://user-images.githubusercontent.com/19405039/48864804-fb009c80-edcd-11e8-8554-1bb88a5f22b8.gif)

### Steps to reproduce
Go to this link `https://www.gatsbyjs.org/starters/gatsby-starter-blog/?gatsby-

### Environment
Chrome on Mac Mojave
Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by jonniebigodes** [comment]
As the url is malformed, you're trying to inject a query param and when gatsby tries to render it will throw what is in the image bellow.
![gatsby_malformed_url](https://user-images.githubusercontent.com/22988955/48865599-fe912500-edc7-11e8-8bcb-3384ab9b6a5e.png)

**Comment by jgierer12** [comment]
I am not able to reproduce this on the same Chrome version on Windows 10. Just wanted to point out that the URL you linked doesn't match the one in your GIF (missing `404` at the end). Is that intentional?

**Comment by jonniebigodes** [comment]
@jgierer12 i just did, the image i posted is a screen grab from windows 10 with chrome.

**Comment by jgierer12** [comment]
Hmm, I still can't reproduce. Tried with `?gatsby-` and `?gatsby-404`, as well as full and empty cache.

**Comment by sidbentifraouine** [comment]
I have the same issue on Firefox 63.0.3 (64-bit), it works on Chrome in Incognito mode, but i blinks 3-4 times before loading correctly.

**Comment by jonniebigodes** [comment]
More on the issue at hand.
After leaving the url opened for a bit this is the my data on the gatsby app.
It starts to grow and with that the chrome process going through the roof.
![gatsby_malformed_url_cache_size](https://user-images.githubusercontent.com/22988955/48869305-aad90880-edd4-11e8-93b0-b76b0de372c5.png)

After clearing the cache and revisiting the url  is what the dev console throws.
![gatsby_malformed_url_after cleared_cache_error](https://user-images.githubusercontent.com/22988955/48869378-e2e04b80-edd4-11e8-9e17-c771e8323cb6.png)

Also it goes from the url provided to gatsby-404 and back. It will loop between the two urls never ending, even in incognito.

**Comment by davidbailey00** [comment]
@tigrankhachikyan Hence why it is still open :) I'm just going to try fixing this now!

**Comment by tigrankhachikyan** [comment]
> @tigrankhachikyan Hence why it is still open :) I'm just going to try fixing this now!

Sorry, I saw `Closed` above, and didn't noticed that it is for a duplicate issue.
Very sorry  :)

**Comment by pushkar8723** [comment]
I ran into this issue and thought to leave a comment in case anyone else is still facing it.

This happened to me when I did a `gatsby build` to figure out some build failure on the server and then switched back to `npm develop`. I figured out that it was because of the service worker and just unregistering it and reloading fixes the issue.
