### ISSUE TITLE
[In Build] Div created in plugin (gatsby-browser.js) loses ID

### ISSUE THREAD

**Issue by hassanshaikley** [gatsbyjs/gatsby#10072]
## Description
It works in dev! But after being built when I inspect it there's no div with id screensaver! ): What could be happening?

gatsby-browser.js

### Steps to reproduce

```
const id='screensaver'
export const wrapRootElement = ({ element, props }, configOptions) => {
  if (configOptions.timeToScreensaver) {
    timeToScreensaver = configOptions.timeToScreensaver * 1000;
  } else {
    timeToScreensaver = defaultTimeToScreensaver
  }

  currentInterval = setTimeout(startScreensaver, timeToScreensaver)

  return (
    <div>
      {element}
      <div
        id={id}
        style={{
          background: 'black',
          position: 'absolute',
          width: '100%',
          height: '100%',
          top: 0,
          opacity: 0.5,
          display: 'none',
        }}
      >
        SCREENSAVER
      </div>
    </div>
  )
}
```

I would try to pore through the source but I find it hard to navigate!

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

I expected the div to have id screensaver, which it only had in dev not build! I tried hard refreshing as well.

What happened.

### Environment

I built it on Mac and tried running it locally in an express server. In an express server is where I saw the issue.

#### Clipboard
```
(node:10445) Warning: a promise was rejected with a non-error: [object Null]

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.19 => 2.0.52
    gatsby-image: ^2.0.15 => 2.0.20
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4
    gatsby-plugin-manifest: ^2.0.5 => 2.0.9
    gatsby-plugin-offline: ^2.0.11 => 2.0.15
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.2
    gatsby-plugin-sharp: ^2.0.7 => 2.0.12
    gatsby-source-filesystem: ^2.0.8 => 2.0.8
    gatsby-transformer-json: ^2.1.5 => 2.1.5
    gatsby-transformer-sharp: ^2.1.4 => 2.1.8
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

**Comment by pieh** [comment]
You probably need to do the same in gatsby-ssr (using same api hook). I would assume it's hydrating issue where html does not match structure of client side react - see https://reactjs.org/docs/react-dom.html#hydrate

> React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them. In development mode, React warns about mismatches during hydration. There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.
