### ISSUE TITLE
Pathprefix cannot be relative

### ISSUE THREAD

**Issue by Yehonal** [gatsbyjs/gatsby#10086]
## Description

Trying to set relative path instead of absolute: `pathPrefix : './'` it's is converted in `/./`

This doesn't allow gatsby to be moved inside subdirectory if you don't recompile it for example.

ReactJS offers this behaviour setting homepage: "./" in package.json for example but Gatsby is not affected by homepage conf and pathPrefix always set that slash at beginning of any internal links.

This feature is also needed for tools such as Electron or Cordova. Actually you can't include a Gatsby project inside such tools because of this behaviour.

### Steps to reproduce

1. set  `pathPrefix : './'` Following [this documentation ](https://www.gatsbyjs.org/docs/path-prefix/)
2. build your project and open public/index.html. At the end of the file all js scripts are included with` /./ `prefix

### Expected result

maybe should exists a condition where pathPrefix is handled that check if we're using a relative path or absolute.

### Actual result

All <script> tags and other internal links are deployed with` /./ `prefix

### Environment

 System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.53 => 2.0.53
    gatsby-image: ^2.0.20 => 2.0.20
    gatsby-plugin-manifest: ^2.0.9 => 2.0.9
    gatsby-plugin-offline: ^2.0.16 => 2.0.16
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12
    gatsby-source-filesystem: ^2.0.8 => 2.0.8
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8

**Comment by pieh** [comment]
> ReactJS offers this behaviour setting homepage: "./" in package.json

I'm not sure what do you mean here, what `react` has to do with this?

I'm not sure if we can actually fully support that: paths to scripts, stylesheets, fonts, images (both when required/using webpack loader and when generated by graphql transformation) would need to be aware at what path we are. This adds a lot of complexity and implementation might be very brittle.

**Comment by Yehonal** [comment]
> > ReactJS offers this behaviour setting homepage: "./" in package.json
> 
> I'm not sure what do you mean here, what `react` has to do with this?
> 
> I'm not sure if we can actually fully support that: paths to scripts, stylesheets, fonts, images (both when required/using webpack loader and when generated by graphql transformation) would need to be aware at what path we are. This adds a lot of complexity and implementation might be very brittle.

It's exactly the case that happens in React:

https://stackoverflow.com/questions/46235798/relative-path-in-index-html-after-build

and you can solve it setting homepage: "./"

The issue is real and Gatsby doesn't allow multiple build configuration currently. So if i want to deploy my gatsby app in multiple environments, for example:

**WEB:**
http://my-web-site.com/

**CORDOVA:**

file://data/user/0/com.adobe.cordova.app/www/

**Electron:**

file://another/subfolder/path

we cannot do it currently with Gatsby, or at least you should have 3 branches just to configure 3 different pathPrefix and build it 3 times (in this case)

**Comment by jgierer12** [comment]
I can't test this right now, but wouldn't setting [`pathPrefix`](https://www.gatsbyjs.org/docs/path-prefix/) to `.` work?

By the way, the `homepage` setting you mentioned is a feature of `create-react-app`, not React itself.

**Comment by Yehonal** [comment]
@jgierer12 i tried it too but doesn't change anything.

**Comment by mattez** [comment]
Related: https://github.com/gatsbyjs/gatsby/issues/2467
