### ISSUE TITLE
Navigating between client-side routes rebuilds children

### ISSUE THREAD

**Issue by RobRuizR** [gatsbyjs/gatsby#10081]
## Description

Gatsby triggers a rebuild on the parent component when navigating through client-side routes. Mostly noticeable when a class component is used as the root for navigation (constructor always runs when route is changed)

### Steps to reproduce

1. Using a client-side routed app, create a class component as the root element.
2. Put a `console.log` on the constructor of the previously created class component.
3. Change your current location, constructor will run every time. Can also be noticed when using `componentDidMount`.

example project: 
https://github.com/RobRuizR/gatsby-client-routing-with-class

running on netlify:
https://gatsby-client-routing-with-class.netlify.com/

### Expected result

Component should be built once.

### Actual result

Component is built every time the route changes.

### Environment

  System:
    OS: Linux 4.10 Ubuntu 17.04 (Zesty Zapus)
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 4.4.7 - /bin/bash
  Binaries:
    Node: 9.7.1 - ~/.nvm/versions/node/v9.7.1/bin/node
    Yarn: 1.3.2 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v9.7.1/bin/npm
  Browsers:
    Chrome: 65.0.3325.146
    Firefox: 55.0.2
  npmPackages:
    gatsby: ^2.0.54 => 2.0.54 
    gatsby-plugin-typography: ^2.2.0 => 2.2.1 
  npmGlobalPackages:
    gatsby-cli: 2.4.5

  EDIT: updated to latest gatsby dependencies
  EDIT 2: Code formatting.

**Comment by jonniebigodes** [comment]
As it should. As you're navigating through the pages your props, states, contexts and data are changing and with that it will trigger updates for the component tree and it will result in that behaviour, if you add `componentDidUpdate(prevProps)` on your  `FadeTransitionRouter` component for instance you'll see what i've mentioned. And with that, this is not a gatsby issue, this is how React is implemented.

**Comment by RobRuizR** [comment]
@jonniebigodes I do understand that the component should be updated on every new page change, and with it, it should be re-rendered. However, the component should not be rebuilt from scratch as it's currently happening since the location should be managed by the router in `FadeTransitionRouter`, not by Gatsby's own router.

In fact, I updated the code as to include your suggestion (it can be seen on the link I previously provided). Putting a `componentDidUpdate(prevProps)` method with a `console.log` on my `FadeTransitionRouter` does not run the logger at all.

**Comment by jonniebigodes** [comment]
From what i've read and tested with the gatsby so far, i've discovered that, as gatsby now uses @reach/router behind the scenes, what is happening is when you click on the link to navigate to another page, gatsby router takes precedence as it's should, over any custom router and does what is supposed to do namely change the history, update contexts and go to the other page.
And there the render process of that component tree wiil be triggered and when it hits your app/router down the line it will build it once again with the new props and your router will follow through and act accordingly. Again this is not a gatsby issue, but the way how it was created.
Possibly one solution for this, would be to avoid you or any other person create another router further down the line when using client routes with or without transitions and have the gatsby router handle this. 
Other possible solution for instance could be to tweak the gatsby browser file to prevent this behaviour and have your client routes be declared there with the transitions.
But as of now, the way it works is how you implemented and it's used on the [examples](https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths).

**Comment by lsirivong** [comment]
To avoid re-creation of some root component in your application you can use `gatsby-plugin-layout`.

Here's a branch where I moved the app code in your example to a layout with the plugin:

https://github.com/RobRuizR/gatsby-client-routing-with-class/compare/master...lsirivong:with-gatsby-plugin-layout

Deployed here:

https://happy-gates-15a7a6.netlify.com/
