### ISSUE TITLE
[gatsby-source-contentful] Can you get field information about content types?

### ISSUE THREAD

**Issue by joealden** [gatsbyjs/gatsby#10099]
For the site I am currently working on, I am using Contentful. I have a custom `Post` type that requires the creator to select a category for the post from a predefined list of categories. The allowed values are defined as validations in Contentful. 

On this site, I want to create a filtering system for the posts. I want to have a dropdown list where the user of the site can select what category of posts they want to browse. To create this list I need to find out what categories are currently defined on the `Post` type. The easiest and most efficient way to do this would be to fetch the list of categories from Contentful at build time through a static GraphQL query.

Is there a way of querying custom type fields in `gatsby-source-contentful`? At the moment I can't see that it is possible. Is this correct? 

From what I can tell, this is what you can query about custom types currently, and this doesn't include any details about the individual fields of the type:

```gql
query {
  contentfulContentType {
    id
    name
    displayField
    description
    internal {
      type
      contentDigest
      owner
    }
  }
}
```

This looks possible to do in the regular REST API that Contentful provides (https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/content-types/content-type/get-a-single-content-type/console/js). If you scroll down to the bottom of that page, you can see the kind of response Contentful returns, including field types and field validations.

A workaround that I could do would be to iterate over all of the posts and build up the list of categories, however, this could be computationally expensive, as the more posts that exist, the more items the code must iterate over. This would also happen at runtime instead of build time, so this iteration technique would happen every time someone visited the site. It is quite wasteful if there is a way to find out what categories there are without having to do this iteration.

If there is already a way to do what I have said in `gatsby-source-contentful`, I'd love to know how! If not, it would be a great feature to have, as I think it is relatively common for developers to want to know the details of their types.

Thanks!

**Comment by pieh** [comment]
What's the type of "category" field in your contentful space? If you are referencing other content type there, then there should be additional query "allContentfulCategory" or something like that?

> A workaround that I could do would be to iterate over all of the posts and build up the list of categories, however, this could be computationally expensive, as the more posts that exist, the more items the code must iterate over. This would also happen at runtime instead of build time, so this iteration technique would happen every time someone visited the site. It is quite wasteful if there is a way to find out what categories there are without having to do this iteration.

This you can do build time, in your gatsby-node and pass it with page context

**Comment by joealden** [comment]
As shown in the screenshot below, the "category" field is just a text field. 

![contentful](https://user-images.githubusercontent.com/10297243/49029954-e80b1500-f19d-11e8-80a8-08650c78fd9f.png)

I am limiting what the post creator can put in that field by only allowing certain values through Contentful validations.

![validation](https://user-images.githubusercontent.com/10297243/49030180-8b5c2a00-f19e-11e8-9181-4f38e521c223.png)

This means that when someone goes to create a post, they are present with a list of radio buttons as shown.

![contentful2](https://user-images.githubusercontent.com/10297243/49030056-328c9180-f19e-11e8-819c-dc1b1b0cd19e.png)

It would be nice is I could somehow access these validation rules from the GraphQL API that `gatsby-plugin-contentful` provides. And as I said in the original message in this thread, it looks as though this is possible through the REST API that `gatsby-plugin-contentful` uses to fetch the data from.

> This you can do build time, in your gatsby-node and pass it with page context

I didn't think of that! For the time being I'll do that then as it won't incur any performance hit for the users of my site, thanks!

Like I said above though, it would be great if you could access these values from the GraphQL query itself. So because it looks as though you can't do that currently, treat this issue as a feature request.

**Comment by joealden** [comment]
@pieh sorry to bother you, but I am trying to implement what you said in `gatsby-node.js` but I am a little stuck. I have the following code:

```js
exports.onCreatePage = ({ page, actions }) => {
  const { createPage, deletePage } = actions;

  return new Promise(resolve => {
    if (page.path === "/") {
      /* Where do I get this 'graphql' function from? */
      const data = graphql`
        query categoriesQuery {
          allContentfulPost {
            edges {
              node {
                category # This is a string
              }
            }
          }
        }
      `;

      const categories = data.allContentfulPost.edges.map(
        edge => edge.node.category
      );

      const newPage = {
        ...page,
        context: {
          categories
        }
      };

      deletePage(page);
      createPage(newPage);
    }

    resolve();
  });
};
```

As it says in the code snippet above, do you know if I can access graphql data from the `onCreatePage` extension point? If so, how would I do that?

From what I've read (https://www.gatsbyjs.org/docs/node-apis/#createPages), the `createPages` extension point receives a `graphql` function in the object it is passed as its argument. As shown in the example on that page I linked, you can use this function to query for data. From what I can tell, this `graphql` function is not passed to `onCreatePage` like it is `createPages`. If this is true, then is it possible to query data from `onCreatePage` at all?

Many thanks.

**Comment by igocode** [comment]
I can confirm that I’m having the exact same issue. Having the validation values provided would enable my filtering system to be far more scalable. Instead I’m having to hardcode the values (🤢) making the project incredibly rigid.
