### ISSUE TITLE
Add (opt-in) support for CSS Module @value variables

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#10094]
## Summary

CSS Modules have a non-widely known feature called ["values variables"](https://github.com/css-modules/css-modules/blob/master/docs/values-variables.md). They can easily be supported using [postcss-modules-values](https://github.com/css-modules/postcss-modules-values).

Please consider adding (plugin-based opt-in) support or more detailed documentation for them!

### Motivation

Currently, the documentation states that [Gatsby works out of the box with CSS Modules](https://github.com/gatsbyjs/gatsby/blob/b1c8c9c8561d5d759fd1b8d4f57dc58e8e5b80c8/docs/docs/css-modules.md). This may be misleading until `@value` variables are not supported.

**Comment by devlato** [comment]
Any news on that?

**Comment by iloveip** [comment]
Hi @kripod!

Have you found a way to import values variables in Gatsby? I'm facing the same problem.

**Comment by kripod** [comment]
Hello @iloveip,

Unfortunately, I haven't. Since then, I've moved to using CSS-in-JS libraries instead.

**Comment by devlato** [comment]
@kripod Why did you do so, Kristóf?

**Comment by kripod** [comment]
@devlato I saw many more optimization opportunities in the land of CSS-in-JS (e.g. extracting critical styles without mistakes).

**Comment by iloveip** [comment]
Hi @kripod,

Thank you for your reply. Is it possible to customize existing components from a third party library with CSS-in-JS?

**Comment by kripod** [comment]
It depends on the CSS-in-JS solution and the customizability of the third-party library in question. I personally had much less problems with CSS-in-JS than prior approaches.
