### ISSUE TITLE
Error: Unable to find plugin (scoped package with npm install) but when moved to the plugins directory it works

### ISSUE THREAD

**Issue by hassanshaikley** [gatsbyjs/gatsby#10097]
## Description

npm installed plugin not recognized. When I move it to the `plugins` directory from `node_modules` it works.

It's a scoped package and I have created another scoped/private package installed the same way that works.

The exact error is: ` Error: Unable to find plugin "@yourhere/return-home". Perhaps you need to install its package?`

[ Private package so it won't work for you ]
```
npm install --save @yourhere/return-home
And then  adjust config:
    {
      resolve: '@yourhere/return-home',
      options: {
        timeToReturnHome: 2,
      },
    },
```

I tried deleting node modules / lock files and installing again to no avail.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.55 => 2.0.55
    gatsby-image: ^2.0.20 => 2.0.20
    gatsby-plugin-manifest: ^2.0.10 => 2.0.10
    gatsby-plugin-offline: ^2.0.17 => 2.0.17
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2
    gatsby-plugin-sharp: ^2.0.13 => 2.0.13
    gatsby-source-filesystem: ^2.0.8 => 2.0.8
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

**Comment by hassanshaikley** [comment]
main was not set to "gatsby-browser.js"

💀

**Comment by hassanshaikley** [comment]
but what does one do when a plugin has a 'gatsby-ssr' file? or another main file? and why doesn't this happen in the plugins folder?

**Comment by hassanshaikley** [comment]
After snooping I have discovered that you need an `index.js` with any contents ie
```
// noop
```

**Comment by loudmouth** [comment]
thanks for sharing your solution!
