### ISSUE TITLE
Open issues on gatsbyjs/gatsby repo via CLI

### ISSUE THREAD

**Issue by jgierer12** [gatsbyjs/gatsby#10095]
## Summary

Add a command to the `gatsby` CLI that allows interactively opening bug reports, feature requests and questions via this repo's issues (as mentioned in #6729). I would love to work on this myself, but wanted to open an issue first to check if no one else is already working on this, and if everyone agrees with my approach.

### Basic example

<details>
<summary>Show example interaction</summary>

```console
$ gatsby issue
? Do you want to open a Bug Report, Feature Request, or Question?
> Bug Report 🐞
  Feature Request 💡
  Question 🤔
```

```console
$ gatsby issue
? Do you want to open a Bug Report, Feature Request, or Question? Bug Report 🐞
? What is the title of your bug report: Example issue
```

```console
$ gatsby issue
? Do you want to open a Bug Report, Feature Request, or Question? Bug Report 🐞
? What is the title of your bug report? Example issue
! We found 3 issues that seem similar to yours:
- Some issue (https://github.com/gatsbyjs/gatsby/issues/1)
- Another issue (https://github.com/gatsbyjs/gatsby/issues/2)
- Third issue (https://github.com/gatsbyjs/gatsby/issues/3)
? Does one of the above match the issue you're seeing? (Y/n) n
```

```console
$ gatsby issue
? Do you want to open a Bug Report, Feature Request, or Question? Bug Report 🐞
? What is the title of your bug report? Example issue
? Describe the issue you're seeing: ...
```

.....

```console
$ gatsby issue
? Do you want to open a Bug Report, Feature Request, or Question? Bug Report 🐞
? What is the title of your bug report? Example issue
? Describe the issue you're seeing
? Clear steps describing how to reproduce the issue
? Link to a demo project
? Actual result: ...
```

```console
$ gatsby issue
✔️ All done! We opened a page in your browser where you can double-check all your
information and submit the issue.

If the page did not open automatically, please open the following URL in your browser:
https://github.com/gatsbyjs/gatsby/issues/new?...
```

</details>

### Motivation

This will allow seamlessly opening an issue as soon as the user discovers it, without switching context away from the development environment. It guides users through the required details step by step, ensuring that they don't forget any important information. Additionally, this can automatically add environment data (`gatsby info`) as well as recent error logs.

### Implementation

The new command will use [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) to create an interactive issue prompt. Depending on the chosen issue type, different questions will be asked. We might also be able to list potential duplicate issues by searching for the specified title via GitHub's API.

In case the user selected the "Bug Report" issue type, we collect environment information (`gatsby info`) as well as recent logs (e.g. `~/.npm/_logs/01234-debug.log`) and add them to the issue body in a `<details>` tag.

Finally, we generate the issue URL with [`new-github-issue-url`](https://github.com/sindresorhus/new-github-issue-url) and try to open it in the user's browser with [`opn`](https://github.com/sindresorhus/opn).

### Challenges

- I have never worked with Inquirer.js yet. The API seems quite friendly though so I think I'll manage it.
- I'm not sure yet how to determine the log files which should be included - any idea would be greatly appreciated!
- Don't know if my idea of finding duplicates via GitHub's API will work out. Perhaps simply searching for the title will not be good enough, or we will get rate limited too quickly.

**Comment by jonniebigodes** [comment]
I just finished reading this and it looks pretty good also.
And @pieh it would be a safer bet to grab the actual output from the console.
Just throwing some thoughts, but couldnt the cached data be checked for injected variables and modify the files to prevent spilling some secrets?

**Comment by jgierer12** [comment]
> Is it possible to purge env vars from the cache

I think that is a good way to get rid of the secrets. A small nitpick is that it will also replace other instances of the string even if they didn't originate from an env var:

```js
if (process.env.NODE_ENV === `production`)
vvv
if (process.env.NODE_ENV === process.env.NODE_ENV)
```

No issue in this particular situation but there may be cases where it becomes problematic. But if it's only for debugging purposes anyways it shouln't be a huge issue.

---

Unfortunately, my laptop broke down yesterday. I hope to have a new one set up by the end of the week so I can start working on this feature 👍

**Comment by pieh** [comment]
I should avoided mentioning .cache thing (it derailed discussion heh). At least for `.cache` dir - we don't store code there, but we have serialized redux state, and in there there will be any api keys or user/pass combos used in `gatsby-config`.

> * Don't know if my idea of finding duplicates via GitHub's API will work out. Perhaps simply searching for the title will not be good enough, or we will get rate limited too quickly.

If we would use `new-github-issue-url` then maybe we don't need to do anything special - this will prefill new issue form (but won't actually submit issue). And from there github should be able to do checks for issue duplication in that form, right?

**Comment by jgierer12** [comment]
The issue is that, by then, the user will have already typed out the whole issue. It also isn't as explicit as deliberately asking if their issue already exists before allowing them to proceed.

I'm not sure how many duplicate issues you get here, if it's not a big problem anyways it's probably enough to rely on GitHub for the duplicate issue detection.

**Comment by jgierer12** [comment]
Ugh. Apparently GitHub doesn't search for duplicates with pre-filled titles. (Try https://github.com/gatsbyjs/gatsby/issues/new?title=Gatsby vs. https://github.com/gatsbyjs/gatsby/issues/new and manually entering "Gatsby").

I'm starting to think it may be better to just ask for type (bug/feature/question), then concatenate the relevant template + env info and send it off to the browser to fill out the details in the GitHub editor like before. Especially since typing longer markdown text in the command line is also kind of clunky.

**Comment by jlengstorf** [comment]
@jgierer12 As a Gatsby-direct option, choosing the type and sending to the browser with envinfo is probably far simpler and will yield pretty solid results.

The app idea you mention sounds great, but I think it's probably overkill for Gatsby. However, it's not necessarily overkill as an OSS project.

<details>
<summary>Quick thoughts on how that might work buried in here.</summary>
If you built this as a CLI tool that directs to a web app, you could create some lifecycle hooks that would allow _any_ project to use this:

1. "pre-run" — where Gatsby would collect env info, etc.
2. "get templates" — where Gatsby would provide the various issue types and the fields we need (could be defined like [Inquirer.js options](https://github.com/SBoudrias/Inquirer.js/blob/b096b4799b13d5323fae3c249457c0a1c04a1e8d/packages/inquirer/examples/pizza.js#L11-L32))
3. "open" — probably nothing to hook into here; would open the web app

If that tool existed, it's feasible that Gatsby could alias it in the CLI (like we do with `envinfo`).
</details>

**Comment by jgierer12** [comment]
I will focus on the info collection aspect for now to ship a `gatsby issue` command featuring that. Perhaps I will build out a complete external CLI tool like you described afterwards :+1:
