### ISSUE TITLE
Installing Radium then requires babel, babel-core, and babel-loader to be installed

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#101]
As reported on Discord by @slightlytyler.

There has to be some sort of misconfiguration in Gatsby's webpack config.

**Comment by KyleAMathews** [comment]
Actually, it seems babel, for whatever reason, just wanted a `.babelrc` file. Adding that to each starter.

**Comment by slightlytyler** [comment]
@KyleAMathews tested this morning and still seeing the same issues, have to install babel and webpack as dev dependencies to get it working.

**Comment by KyleAMathews** [comment]
Did you add a .babelrc? I got a simple radium setup to work by just adding
that.

**Comment by slightlytyler** [comment]
I tested by creating a new gatsby project (with .babelrc included already) and installed radium, hit the same errors as last time.
