### ISSUE TITLE
Last service worker buggy workbox-v3.6.3

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#10100]
i constated some problem with the service worker

i removed the cache of chrome

step1:
started first load of webpage: webpage showed good fully
step2:
second load of webpage webpage showed good fully and on the developper panel i can see service worker is running
step3:
but from third load the webpage is not well load, in panel console i can see that some 404 due to service worker point to past very old file cached before step1 (but removed from chrome cache)

The problem is comping from this line from the "updatingWhitelist"

```
self.addEventListener("message", function (event) { 
  var gatsbyApi = event.data.gatsbyApi; 
  if (gatsbyApi) messageApi[gatsbyApi](event); 
}); 
```

I removed these line and all is working good
Sorry if i cannot give more info about this

**Comment by pieh** [comment]
Hey, did you update `gatsby` as well? New version of offline plugin needs new version of gatsby: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-offline/package.json#L33

**Comment by simonjoom** [comment]
I checked the both my code is correctly updated, i ve new version of the both
