### ISSUE TITLE
Gettings slow Time-To-Interactive 

### ISSUE THREAD

**Issue by deepsyx** [gatsbyjs/gatsby#10104]
Greetings. We're currently optimising our webpage for performance (we just migrated from v1 to v2). Although it feels incredibly fast, all speed insights (google one, chrome audits) are showing really slow Time-To-Interactive times:

Here is a photo of just done performance audit:

https://i.imgur.com/exlbAXg.png

The audits are performed on 4x CPU slowdown. 
I'm not sure what kind of information would be useful to share.
Any tips how to debug that or what can be done to improve it?

**Comment by pieh** [comment]
Check https://www.webpagetest.org/result/181123_M5_7a9ba7bf8e62032f3926dc0405f80a2c/1/details/#waterfall_view_step1 I would say that all the tracking and external scripts is slowing things down

**Comment by LekoArts** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
