### ISSUE TITLE
Material Design Drawer causing Build error

### ISSUE THREAD

**Issue by adrianwix** [gatsbyjs/gatsby#10108]
## Description

Can not build with Material Design React components [https://github.com/material-components/material-components-web-react/tree/master/packages/drawer](url)

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

WebpackError: ReferenceError: Element is not defined

  - index.js:352 Object._
    [lib]/[@material]/react-drawer/dist/index.js:352:305

  - index.js:148 __webpack_require__
    [lib]/[@material]/react-drawer/dist/index.js:148:1

  - index.js:761 Object._
    [lib]/[@material]/react-drawer/dist/index.js:761:483

  - index.js:148 __webpack_require__
    [lib]/[@material]/react-drawer/dist/index.js:148:1

  - index.js:325 Object._
    [lib]/[@material]/react-drawer/dist/index.js:325:576

  - index.js:148 __webpack_require__
    [lib]/[@material]/react-drawer/dist/index.js:148:1

  - index.js:258 Object._
    [lib]/[@material]/react-drawer/dist/index.js:258:1439

  - index.js:148 __webpack_require__
    [lib]/[@material]/react-drawer/dist/index.js:148:1

  - index.js:157 0
    [lib]/[@material]/react-drawer/dist/index.js:157:1

  - index.js:157
    [lib]/[@material]/react-drawer/dist/index.js:157:72

  - index.js:139 webpackUniversalModuleDefinition
    [lib]/[@material]/react-drawer/dist/index.js:139:132

  - index.js:142 Object.<anonymous>
    [lib]/[@material]/react-drawer/dist/index.js:142:275

  - index.js:773 Object._typeof
    [lib]/[@material]/react-drawer/dist/index.js:773:29

  - index.js:30 __webpack_require__
    [lib]/[@material]/react-drawer/dist/index.js:30:1

  - index.js:107 Object._typeof
    [lib]/[@material]/react-drawer/dist/index.js:107:1171

  - index.js:30 __webpack_require__
    [lib]/[@material]/react-drawer/dist/index.js:30:1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-netlify-cms@1.1.3 build: `npm run clean && gatsby build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-starter-netlify-cms@1.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adrian\AppData\Roaming\npm-cache\_logs\2018-11-23T23_04_36_853Z-debug.log

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli` System:
    OS: Windows 8.1
    CPU: x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  Binaries:
    Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    gatsby: ^2.0.0 => 2.0.55
    gatsby-plugin-netlify: ^2.0.0 => 2.0.5
    gatsby-plugin-netlify-cms: ^3.0.0 => 3.0.7
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.2
    gatsby-plugin-sass: ^2.0.1 => 2.0.4
    gatsby-plugin-sharp: ^2.0.5 => 2.0.13
    gatsby-remark-images: ^2.0.1 => 2.0.6
    gatsby-source-filesystem: ^2.0.1 => 2.0.8
    gatsby-transformer-remark: ^2.1.1 => 2.1.12
    gatsby-transformer-sharp: ^2.1.1 => 2.1.8

error The system cannot find the path specified.

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:7778

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:104976

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:123499

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124274

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124289

  - util.js:16 tryCatcher
    [npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

error UNHANDLED REJECTION

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:7778

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:104976

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:123499

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124274

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:124289

  - util.js:16 tryCatcher
    [npm]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

**Comment by jonniebigodes** [comment]
Did you used a starter? If so wich one?
Also provide the `gatsby info --clipboard` here, the gatsby-cli version you have and also if the work you're doing is not private or otherwise protected, a repository url so that the issue can be looked at in more detail if you don't mind.

**Comment by adrianwix** [comment]
Hi, Sorry for not answering before. I used the Netlify CMS starter. Yes it is basically a problem while building the app. Because of the Material Library. 
Is there any way to solve the issue? 
I was thinking about using [material-components-web](https://github.com/material-components/material-components-web) as it only use vanilla css (or sass) and instantiate the component in `componentDidMount`.

**Comment by jonniebigodes** [comment]
@adrianwix i've been at this particular issue for the past 4 days, and no luck in solving it.
I've cloned your repo, and tried to make it work, taking on different approaches at it like for instance:

- Changing the `gatsby-config.js` in order for the scss to be imported correctly.
- Added the babel preset for gatsby and also the babel libraries stated on the documentation.
- Adjusted the `gatsby-node.js` file to reflect the material components documentation, in regards of webpack configuration
- Added a specific wrapper for React, as mentioned for the documentation.

And despite taking several cracks at it. 
Still no luck, same error.
 The issue here and i'm just guessing is that as gatsby works on the server side of the spectrum and the material library you mentioned is on the other side, on the client side. 
When gatsby starts the build process, it will try to gain access to an api that's not accessible to it. And causes that error and prevent the build.
I know that on a development mode like i said on my previous comment  the wrapper i used and the one you're using works, but in development mode gatsby is way more permissive than when you want a final build.
Sorry for not being more of a help.
Could be that someone more knowledgeable could solve this issue and make the library play nice with gatsby.

**Comment by adrianwix** [comment]
https://github.com/material-components/material-components-web/issues/4104. Here is the problem.

**Comment by jonniebigodes** [comment]
Glad you figured out the issue.
