### ISSUE TITLE
Algolia guide

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#10113]
The information on how to use Algolia to search a Gatsby site is quite sparse at the moment. All I could find was the [Adding search guide](https://www.gatsbyjs.org/docs/adding-search/#use-an-api-based-search-engine) initiated in May 2018 and this [blog post](https://www.gatsbyjs.org/blog/2017-12-06-gatsby-plus-contentful-plus-netlify/#solution-algolia--gatsby) from December 2017. Neither goes into any detail and neither even mentions [`gatsby-plugin-algolia`](https://github.com/algolia/gatsby-plugin-algolia). Basically both refer you to Algolia's [Docsearch](https://community.algolia.com/docsearch) which isn't that helpful since most sites aren't documentation sites.

I implemented a custom Algolia search on several sites ([Ocean artUp](https://ocean-artup.eu), [SbS](https://studenten-bilden-schueler.de), [my own](https://janosh.io)) and contributed to `gatsby-plugin-algolia` so I have some experience on the matter by now. I would be happy to contribute a blog post, extend the Adding search guide or write a new guide. Would any of those be welcomed?

**Comment by jonniebigodes** [comment]
For me it either would be perfect. i've been reading on algolia but still very very illiterate on the matter and i would like to see more on the subject and how to make it work with gatsby.

**Comment by janosh** [comment]
@jonniebigodes Thanks for chiming in. Good to know that there's some interest. Still let's wait and see what the maintainers say. In the meantime, [this blog post](https://janosh.io/blog/gatsby-algolia-search) I wrote on the topic might help you out.

**Comment by m-allanson** [comment]
+1 for `gatsby-plugin-algolia`! I've been using it for a recent project and agree it'd be great to see more info on using Algolia with Gatsby. 

I'm a little out of the loop at the moment, cc'ing @gatsbyjs/docs what would be the best approach here? 

Referencing https://www.gatsbyjs.org/docs/templates/ it sounds like this could be  handled as a tutorial?

**Comment by Haroenv** [comment]
Feel free to ask me any questions as well. The plugin should work well up to some more advanced use cases, but isn't that optimised yet for less network usage on the indexing side, which is why  I still left it in "beta" stage for now.

**Comment by m-allanson** [comment]
@janosh sorry for the delay! If you still have the time, there's now a placeholder article for an Algolia guide. See https://www.gatsbyjs.org/docs/adding-search-with-algolia/

**Comment by janosh** [comment]
@m-allanson No worries. Just created a [PR](https://github.com/gatsbyjs/gatsby/pull/11459) with my suggestion for the guide. It's a little long. Let me know if you'd like me to cut it down by maybe removing the part on how to implement the UI. Although to be honest that was the part that took me the longest and something I personally would like to see in such a guide if I came across it.

**Comment by janosh** [comment]
@Haroenv Any reason to keep this open?

**Comment by DSchau** [comment]
@janosh @Haroenv guessing it wasn't clear this is now written!

@Haroenv if you'd like to take another look at the guide or tweak anything--more than welcome to!

For now though, am going to close this, since it has been implemented thanks to @janosh!
