### ISSUE TITLE
WebpackError: TypeError: Cannot read property 'jsonName' of undefined #8936

### ISSUE THREAD

**Issue by cgarvie** [gatsbyjs/gatsby#10111]
## The Problem

I am pretty sure that my problem is very similar to https://github.com/gatsbyjs/gatsby/issues/8936

I apologize but I'm not yet great at JS/node. I could use some help understanding how to solve this.

I can use `gatsby develop` fine but `gatsby build` fails with the following output. I think this issue is very similar to the link above but I do not understand how Promises/resolves fit into the picture.

```
110 |
  111 |   let dataAndContext = {}
> 112 |   if (page.jsonName in dataPaths) {
      |            ^
  113 |     const pathToJsonData = '../public/' + dataPaths[page.jsonName]
  114 |     try {
  115 |       dataAndContext = JSON.parse(

  WebpackError: TypeError: Cannot read property 'jsonName' of undefined

  - static-entry.js:112 Module../.cache/static-entry.js.__webpack_exports__.default
    lib/.cache/static-entry.js:112:12

  - bootstrap:24 Promise
    lib/webpack/bootstrap:24:1

  - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1

  - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1

  - bootstrap:50 MappingPromiseArray._promiseFulfilled
    lib/webpack/bootstrap:50:1

  - api-runner-ssr.js:6 MappingPromiseArray.PromiseArray._iterate
    lib/.cache/api-runner-ssr.js:6:16

  - bootstrap:67 MappingPromiseArray.init
    lib/webpack/bootstrap:67:1

  - bootstrap:19 MappingPromiseArray._asyncInit
    lib/webpack/bootstrap:19:1

  - api-runner-ssr.js:33 _drainQueueStep
    lib/.cache/api-runner-ssr.js:33:6

  - api-runner-ssr.js:36 Async._drainQueues
    lib/.cache/api-runner-ssr.js:36:7

  - static-entry.js:64 processImmediate
    lib/.cache/static-entry.js:64:5
```

and here is the gatsby-node.js to save time:

```
var glob = require("glob");
var fs = require("fs");

require("./src/utils/misc.js")

const path = require("path")

require('events').EventEmitter.prototype._maxListeners = 9999;

exports.createPages = ({ actions: { createPage }, graphql }) => {

  var niches_conditions = [];
  var niches_supplements = [];

  glob("src/data/*.json", function(err, files) { // read the folder or folders if you want: example json/**/*.json
    if(err) {
      console.log("cannot read the folder, something goes wrong with glob", err);
    }
    files.forEach(function(file) {
      fs.readFile(file, 'utf8', function (err, data) { // Read each file
        if(err) {
          console.log("cannot read the file, something goes wrong with the file", err);
        }
        var obj = JSON.parse(data).data;    
        var query = file.split('.')[0].split('/');
        niches_conditions.push(query)
        query = query[query.length-1].replaceAll(' ','-');
        var url = query //query.toLowerCase()
        createPage({
          path: `/supplements/${url}/`,
          component: require.resolve("./src/templates/serp.js"),
          context: { obj, query, files},
        })

      });
    });
    var obj = null
    var query = ""
    createPage({
          path: `/supplements/`,
          matchPath: `/supplements/*`,
          component: require.resolve("./src/templates/serp.js"),
          context: { obj, query, files},
        })
  });

  //
  
  glob("src/data-toplists/*.json", function(err, files) {
    if(err) {
      console.log("cannot read the folder, something goes wrong with glob", err);
    }
    files.forEach(function(file) {
      fs.readFile(file, 'utf8', function (err, data) { // Read each file
        if(err) {
          console.log("cannot read the file, something goes wrong with the file", err);
        }
        var obj = JSON.parse(data);    
        var keyword = file.split('.')[0].split('/');
        niches_conditions.push(keyword)
        keyword = keyword[keyword.length-1].replaceAll(' ','-');
        var url = keyword.toLowerCase()
        createPage({
          path: `/best-${keyword}-supplements/`,
          component: require.resolve("./src/templates/toplistTemplate.js"),
          context: { obj, keyword, files},
        })

      });
    });
  });
  
  //
  
  const blogPostTemplate = path.resolve(`./src/templates/blogTemplate.js`)

  graphql(`
    {
      allMarkdownRemark {
        edges {
          node {
            id
            fileAbsolutePath
            frontmatter {
              title
              path
              date
              _PARENT
            }

          }
        }
      }
    }
  `).then(result => {
    if (result.errors) {
      return Promise.reject(result.errors)
    }
    else {
    result.data.allMarkdownRemark.edges.forEach(({ node }) => {
    if (node.fileAbsolutePath.includes('/markdown/pages/')) {
          createPage({
            path: node.frontmatter.path,
            component: blogPostTemplate,
            context: {}, // additional data can be passed via context
          })
        }
      })
    }
  })
  


}
```

Because it may be asked, I started globbing over files instead of using the JSON importer because the JSON importer was causing problems for me. Attempting to use it with the two json files in ./src/data/ and ./src/data-toplists/ in the linked example repo, for example, will cause `gatsby develop` to fail because `Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "1_2" does not.`. I guess because my JSON's first element starts with a number and not a letter. It's valid JSON though...

### Environment (if relevant)

  System:
    OS: macOS High Sierra 10.13.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.2.0 - ~/.nvm/versions/node/v11.2.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v11.2.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Firefox: 62.0.3
    Safari: 11.0.3
  npmPackages:
    gatsby: ^2.0.49 => 2.0.49
    gatsby-node-helpers: ^0.3.0 => 0.3.0
    gatsby-plugin-create-client-paths: ^2.0.2 => 2.0.2
    gatsby-plugin-nprogress: ^2.0.6 => 2.0.6
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2
    gatsby-plugin-typography: ^2.2.1 => 2.2.1
    gatsby-source-filesystem: ^2.0.8 => 2.0.8
    gatsby-source-google-sheets: ^1.1.1 => 1.1.1
    gatsby-transformer-csv: ^2.0.4 => 2.0.4
    gatsby-transformer-json: ^2.1.5 => 2.1.5
    gatsby-transformer-remark: ^2.1.12 => 2.1.12
  npmGlobalPackages:
    gatsby-cli: 2.4.4

### File contents (if changed)

https://github.com/cgarvie/gatsby-mvp

**Comment by DZuz14** [comment]
I am still learning Gatsby's internals, but from the Node API's docs on [createPages](https://www.gatsbyjs.org/docs/node-apis/#createPages) you need to return a Promise that ultimately resolves, letting Gatsby know your done. 

You are performing other types of asynchronous work here as well via `glob` (according to the docs its an async operation), which leads me to believe the order of execution gets all out of whack.

Hopefully someone more experienced with Gatsby can lend a better explanation, but it seems to me that you need to somehow make sure all of these async operations are done before you resolve the promise that needs to be returned to the invocation of exports.createPages.

**Comment by cgarvie** [comment]
I see, that makes sense. 

__30 minutes later...__

I changed all functions to their synchronous versions and it now builds successfully! Thank you @DZuz14

**Comment by DZuz14** [comment]
No problem man. Glad you got it working.
