### ISSUE TITLE
Gatsby starter blog page causing infinite refresh loop

### ISSUE THREAD

**Issue by cadejscroggins** [gatsbyjs/gatsby#10114]
## Description

My browser (Chrome 70.0.3538.110) seems to loop between:

- https://www.gatsbyjs.org/starters/gatsby-starter-blog/
- https://www.gatsbyjs.org/starters/gatsby-starter-blog/?gatsby-404

### Steps to reproduce

Go to https://www.gatsbyjs.org/starters/gatsby-starter-blog/

**Comment by jonniebigodes** [comment]
Closing this issue, this is same as #10074 .
