### ISSUE TITLE
Graphql debugger not loading

### ISSUE THREAD

**Issue by marvinjude** [gatsbyjs/gatsby#10120]
I am using the `gatsby-starter-default` after adding some plugins and few components the graphql debugger on `http://localhost:8000/___graphql` suddenly stopped working, all i get is:

Loading....

**Is the dev server running**
Yes

**do i have **warnings** in the console**
Yes

**do i have have errors in the console**
No

**Comment by oorestisime** [comment]
Can you please provide some more details?
Did you modify anything? does `gatsby develop` provide any errors?

**Comment by wlockiv** [comment]
Marvin, did you change the port to 8080? The [Gatsby default starter docs](https://github.com/gatsbyjs/gatsby-starter-default) indicates using the 8000 port.

**Comment by marvinjude** [comment]
Sorry i meant 8000
