### ISSUE TITLE
Graphiql Degubber not loading

### ISSUE THREAD

**Issue by marvinjude** [gatsbyjs/gatsby#10129]
I am using the `gatsby-starter-default` after adding some plugins and few components the graphql debugger on `http://localhost:8000/___graphql` suddenly stopped working, all i get is:

Loading....

**Is the dev server running**
Yes

**do i have **warnings** in the console**
Yes

**do i have have errors in the console**
No

**Comment by marvinjude** [comment]
Do i need an internet connection to use _GraphiQL_ ?

**Comment by c0b41** [comment]
@marvinjude yes, graphiql frontend need some external resources to load

**Comment by marvinjude** [comment]
Thanks! I confirmed that.
