### ISSUE TITLE
[gatsby-source-wordpress] TypeError: Cannot read property 'id' of undefined 

### ISSUE THREAD

**Issue by hensmith** [gatsbyjs/gatsby#10138]
## Summary

I'm trying to do a `gatsby build` from a Wordpress blog using `gatsby-source-wordpress`. The build dies with a TypeError. Commenting out the line producing the error results in a seemingly working build. I'm hoping there's some common plugin or config change needed that will be immediately apparent to Gatsby veterans 🤞😇

```
  TypeError: Cannot read property 'id' of undefined

  - normalize.js:256 entities.map.e
    [gatsby-source-wordpress]/normalize.js:256:74
```

## Relevant information

The error means that the `.find()` call in the following block of code from [`normalize.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/normalize.js#L261) is returning `undefined`.

```javascript
// TODO generalize this for all taxonomy types.
exports.mapTagsCategoriesToTaxonomies = entities =>
  entities.map(e => {
    // Where should api_menus stuff link to?
    if (e.taxonomy && e.__type !== `wordpress__wp_api_menus_menus`) {
      // Replace taxonomy with a link to the taxonomy node.
      e.taxonomy___NODE = entities.find(t => t.wordpress_id === e.taxonomy).id
      delete e.taxonomy
    }
    return e
  })
```

Here are some of the relevant plugins present in the Wordpress installation. Because the code near the error mentions the menus API, I've tried a few menu API plugins.

* ACF to REST API
* Advanced Custom Fields PRO
* WP-REST-API V2 Menus (also tried WP REST API Menus, and again with neither installed)
* WPML REST API

### Environment (if relevant)

```
  System:
    OS: macOS 10.14.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.1.0 - ~/.nvm/versions/node/v11.1.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v11.1.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.19 => 2.0.55
    gatsby-source-wordpress: ^3.0.15 => 3.0.15
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

### File contents (if changed)

`gatsby-config.js`

```javascript
module.exports = {
  plugins: [{
    resolve: "gatsby-source-wordpress",
    options: {
      baseUrl: process.env.WP_HOSTNAME,
      protocol: process.env.WP_PROTOCOL,
      auth: {
        htaccess_user: process.env.WP_HTACCESS_USERNAME,
        htaccess_pass: process.env.WP_HTACCESS_PASSWORD
      },
      useACF: true
    }
  }]
}
```

**Comment by pieh** [comment]
Would you be willing to do some debugging?

What's the actualy taxonomy that can't be found?

```
// TODO generalize this for all taxonomy types.
exports.mapTagsCategoriesToTaxonomies = entities =>
  entities.map(e => {
    // Where should api_menus stuff link to?
    if (e.taxonomy && e.__type !== `wordpress__wp_api_menus_menus`) {
      // Replace taxonomy with a link to the taxonomy node.
      const taxonomyNode = entities.find(t => t.wordpress_id === e.taxonomy)
      if (taxonomyNode) {
        e.taxonomy___NODE = taxonomyNode.id
      } else {
        // output some data to see what can't be found
		console.log(`can't find taxonomy ${e.taxonomy}`, e)
      }
      delete e.taxonomy
    }
    return e
  })
```

I think easy way about this is to just apply `if` guard I did above (to not crash process), but it would be great to figure out why we can't find that node

**Comment by hensmith** [comment]
Mmmm 😄 yeah I've been thinking about just sending a quick PR like that, since it seems so harmless to add the check!

It's weird: all the `t.wordpress_id` values are integers and all the `e.taxonomy` values are strings. Don't understand why that's the case, but it seems impossible for this find() call to ever find anything in my dataset.

| console.log message | how many times it appears |
|-|-|
| `can't find taxonomy nav_menu`  | x44 |
| `can't find taxonomy category`  | x1 |
| `can't find taxonomy post_tag`  | x2 |

All the `e` values look roughly the same.

```
{ wordpress_id: 44,
  count: 19,
  description: '',
  link: 'http://example.org/en/tag/consumer/',
  name: 'Hello World',
  slug: 'hello-world',
  taxonomy: 'post_tag',
  meta: [],
  _links:
   { self: [ { href: 'http://example.org/en/wp-json/wp/v2/tags/44/' } ],
     collection: [ { href: 'http://example.org/en/wp-json/wp/v2/tags/' } ],
     about:
      [ { href: 'http://example.org/en/wp-json/wp/v2/taxonomies/post_tag/' } ],
     wp_post_type:
      [ { href: 'http://example.org/en/wp-json/wp/v2/posts/?tags=44' },
        { href: 'http://example.org/en/wp-json/wp/v2/pages/?tags=44' } ],
     curies:
      [ { name: 'wp', href: 'https://api.w.org/{rel}', templated: true } ] },
  __type: 'wordpress__wp_',
  id: 'ace64cd3-baa4-54bf-b242-0dbfe1845b85' }
```

**Comment by pieh** [comment]
Do you perhaps use included / excluded routes option in your `gatsby-source-wordpress` plugin configuration? It seems like http://example.org/en/wp-json/wp/v2/taxonomies/ route is potentially not pulled in?

But yeah, we still want to not crash in those cases :)

**Comment by hensmith** [comment]
funny you should mention that, @pieh, cos ive just been tweaking exactly that bit of configuration!! until now it was empty: i had no includedRoutes or excludedRoutes. there was a bunch of ugly red text 401 errors from the following endpoints during the build:

* /en/wp-json/yoast/v1/reindex_posts/?per_page=100&page=1
* /en/wp-json/yoast/v1/ryte/?per_page=100&page=1
* /en/wp-json/yoast/v1/statistics/?per_page=100&page=1
* /en/wp-json/wpml/tm/v1/ate/jobs/store/?per_page=100&page=1
* /en/wp-json/wpml/tm/v1/ams/register_manager/?per_page=100&page=1
* /en/wp-json/wpml/tm/v1/ams/synchronize/translators/?per_page=100&page=1
* /en/wp-json/wpml/tm/v1/ams/synchronize/managers/?per_page=100&page=1
* /en/wp-json/wpml/tm/v1/ams/status/?per_page=100&page=1
* /en/wp-json/wpml/tm/v1/ate/jobs/?per_page=100&page=1
* /en/wp-json/wpml/tm/v1/jobs/assign/?per_page=100&page=1
* /en/wp-json/wpml/tm/v1/settings/translation_editor/?per_page=100&page=1
* /en/wp-json/wp/v2/users/me/?per_page=100&page=1
* /en/wp-json/wp/v2/settings/?per_page=100&page=1

none of these endpoints look related to taxonomies, but i thought i'd try fixing the errors anyway and see if it helped. so i added the following new config just now:

```json
excludedRoutes: [
    "**/yoast/**",
    "**/wpml/tm/**",
    "**/wp/v2/users/me/**",
    "**/wp/v2/settings/**",
]
```

this has fixed the 401 errors during the build, but the original `Cannot read property 'id' of undefined` error still happens afterwards anyway even though the fetch phase is now error-free. im certain this must be down to some kind of strangeness in this wordpress installation, but haven't been able to isolate whatever it is unfortunately 🥴

glad to see we're moving ahead with the easy if-check fix now! if anyone reading this in the future has the same issue and figures out the cause, i'd appreciate a quick note @ mentioning me with an update! would love to know what this was!!

**Comment by hensmith** [comment]
hmmm i _can_ see the taxonomies endpoint getting hit in the server access logs during the import too

```

[30/Nov/2018:13:00:49 +0000] "GET /en/wp-json/wp/v2/statuses/?per_page=100&page=1 HTTP/1.1" 200 854 "-" "axios/0.18.0"
[30/Nov/2018:13:00:49 +0000] "GET /en/wp-json/wp/v2/taxonomies/?per_page=100&page=1 HTTP/1.1" 200 1252 "-" "axios/0.18.0"
[30/Nov/2018:13:00:49 +0000] "GET /en/wp-json/wp/v2/categories/?per_page=100&page=1 HTTP/1.1" 200 1148 "-" "axios/0.18.0"
[30/Nov/2018:13:00:49 +0000] "GET /en/wp-json/wp/v2/tags/?per_page=100&page=1 HTTP/1.1" 200 1776 "-" "axios/0.18.0"
[30/Nov/2018:13:00:50 +0000] "GET /en/wp-json/wp/v2/users/?per_page=100&page=1 HTTP/1.1" 200 4599 "-" "axios/0.18.0"
[30/Nov/2018:13:00:50 +0000] "GET /en/wp-json/wp/v2/comments/?per_page=100&page=1 HTTP/1.1" 200 533 "-" "axios/0.18.0"
```

so ¯\\\_(ツ)\_/¯ dunno lol 😆

**Comment by pieh** [comment]
You can also try setting `verboseOutput: true` in `gatsby-source-wordpress` configuration which should output more details to console

**Comment by hensmith** [comment]
This is working fine now for me with the latest version of `gatsby-source-wordpress` that has that PR merged in it. I'll close the issue!
