### ISSUE TITLE
Add internal link pointing to license

### ISSUE THREAD

**Issue by open-source-explorer** [gatsbyjs/gatsby#10135]
The license section was recently added within the `README` file.
As per the convention it would be good to have a link within `what's in this document` section pointing to the `LICENSE` section.

**Comment by open-source-explorer** [comment]
@DSchau As per now, the `README` file contains a `What's in this document` section in which each section is listed with the respective link. 
I think it is good idea to have the license included over there as well!

**Comment by DSchau** [comment]
Ah, got it! Yeah, I'm not too concerned about that not being included currently, but sure - if you want to fix this, feel free!
