### ISSUE TITLE
docs: migrate line highlighting to highlight-line, highlight-start, highlight-end

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#10134]
## Summary

Our docs currently use a line highlighting mechanism that is not necessarily ideal. See #9235 for further detail of the general issue. We've since fixed this in #9696, which enables improved functionality that is more maintainable.

### Basic example

Given the following (existing) highlighted code snippet, we can re-factor with the changes in this new release.

Note: the following snippet indicates that line 6 is being highlighted, e.g. the `plugins` array

````markdown
```javascript{6}
module.exports = {
  siteMetadata: {
    title: `Your Name - Blog`,
    author: `Your Name`,
  },
  plugins: ["gatsby-plugin-catch-links", "gatsby-plugin-react-helmet"],
}
```
````

to the following _new_ variant

````markdown
```javascript
module.exports = {
  siteMetadata: {
    title: `Your Name - Blog`,
    author: `Your Name`,
  },
  plugins: ["gatsby-plugin-catch-links", "gatsby-plugin-react-helmet"], // highlight-line
}
```
````

### Motivation

This will be _much_ more maintainable (e.g. resistant to things like prettier messing up line order, code changes, etc.) and a lot easier to use.

Consider using any of the following directives to accomplish this task:

- `highlight-line` - highlights the current line
- `highlight-next-line` - highlights the next line
- `highlight-start` & `highlight-end` - highlight all lines until `highlight-end` is encountered

Additionally things like `highlight-range` are still supported, but I'd recommend using the previously mentioned directives to accomplish this task, as highlight-range does suffer from several of the same issues as the existing functionality.

**Comment by DSchau** [comment]
Note: for some help in identifying the files:

Consider this regular expression
  ````
  ```(\w+)?\{.+}
  ````

this will identify any code fenced blocks with a `{}` block. I've used it in VSCode like so:

<img width="285" alt="screen shot 2018-11-26 at 9 40 38 am" src="https://user-images.githubusercontent.com/3924690/49020826-567cb280-f15f-11e8-9433-2e0d9b9e6ad2.png">

**Comment by nero2009** [comment]
Can I take this

**Comment by DSchau** [comment]
@nero2009 absolutely! I'll mark it as assigned. Looking forward to the PR! Please feel free to reach out to any of us @gatsbyjs/core with any questions!
