### ISSUE TITLE
Activeclassname doesn't work when you have pages with spaces in them

### ISSUE THREAD

**Issue by ivarkallejarv** [gatsbyjs/gatsby#10136]
## Description
When navigating to a page, like "https://my-page.com/my%20page", activeClassName doesn't work on Gatsby's Link component

### Steps to reproduce

1. Create a Gatsby site with a page like "my page.md"
2. Use Gatsby Link component's activeClassName prop 

### Expected result
ActiveClassName should be applied to the page.

### Actual result
ActiveClassName is not applied to the page.

### Environment

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Yarn: 1.10.1 - C:\Users\ivark\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.55 => 2.0.55
    gatsby-cli: ^2.4.5 => 2.4.5
    gatsby-plugin-manifest: ^2.0.10 => 2.0.10
    gatsby-plugin-netlify: ^2.0.4 => 2.0.5
    gatsby-plugin-netlify-cms: ^3.0.7 => 3.0.7
    gatsby-plugin-offline: ^2.0.17 => 2.0.17
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2
    gatsby-plugin-sass: ^2.0.4 => 2.0.4
    gatsby-plugin-typescript: ^2.0.1 => 2.0.1
    gatsby-source-filesystem: ^2.0.8 => 2.0.8
    gatsby-transformer-remark: ^2.1.12 => 2.1.12

After that are a couple of errors =>
error The system cannot find the path specified.
  Error: The system cannot find the path specified.

  doing it manually then:
    "gsap": "^2.0.2",
    "netlify-cms": "^2.2.0",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-helmet": "^5.2.0",
    "sanitize.css": "^8.0.0"

devDependencies:
    "@types/gsap": "^1.20.0",
    "@types/react-helmet": "^5.0.7",
    "gatsby-cli": "^2.4.5",
    "husky": "^1.2.0",
    "immutable": "^3.8.1",
    "node-sass": "^4.10.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.15.2",
    "pretty-quick": "^1.7.0",
    "redux": "^3.7.2",
    "remark-cli": "^6.0.0",
    "remark-preset-lint-recommended": "^3.0.2",
    "standard-version": "^4.4.0",
    "svgo": "^1.1.1",
    "tinypng-cli": "0.0.7",
    "tslint": "^5.11.0",
    "tslint-config-prettier": "^1.16.0",
    "tslint-react": "^3.6.0",
    "typescript": "^3.1.6",
    "uglifyjs-webpack-plugin": "^2.0.1"

**Comment by sidharthachatterjee** [comment]
Gatsby v2 uses [Reach Router](https://reach.tech/router) under the hood which doesn't take an `activeClassName` prop but instead lets you add props based on `isCurrent` or `isPartiallyCurrent` values that it computes. 

I wouldn't usually recommend pages with spaces in their names, but you can make this work with a custom `getProps` function that does the comparison keeping spaces in mind. 

Check out the documentation at https://reach.tech/router/api/Link

**Comment by ivarkallejarv** [comment]
Gotcha, gonna close this then, thanks
