### ISSUE TITLE
Receive TypeError: address.ip is not a function when attempting to run gatsby develop

### ISSUE THREAD

**Issue by Azagoth** [gatsbyjs/gatsby#10144]
## Description

Following the basic tutorial from the docs website.  On the step after cloning and changing directories I attempt to run gatsby develop and receive the error 

TypeError: address.ip is not a function

  - detect-port.js:88 err
    [hello-world]/[detect-port]/lib/detect-port.js:88:32

  - detect-port.js:118 Server.server.listen
    [hello-world]/[detect-port]/lib/detect-port.js:118:12

  - next_tick.js:72 process.internalTickCallback
    internal/process/next_tick.js:72:19

### Steps to reproduce

Follow the tutorial steps exactly (https://www.gatsbyjs.org/tutorial/part-zero/) and then type gatsby develop.

### Expected result

Run and start the gatsby tutorial.

### Actual result

TypeError: address.ip is not a function

  - detect-port.js:88 err
    [hello-world]/[detect-port]/lib/detect-port.js:88:32

  - detect-port.js:118 Server.server.listen
    [hello-world]/[detect-port]/lib/detect-port.js:118:12

  - next_tick.js:72 process.internalTickCallback
    internal/process/next_tick.js:72:19

### Environment

  System:
    OS: macOS 10.14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.2.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.33 => 2.0.55 
  npmGlobalPackages:
    gatsby-cli: 2.4.5

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

**Comment by jonniebigodes** [comment]
Doing a bit of diving in the gatsby code and searching for what you posted leads me to think that something is happening on your end and the address you have on your machine is not being picked up correctly or you have probably some kind of setup that does not play nice with gatsby

**Comment by Azagoth** [comment]
After consulting with my IT department, it was an error with my profile due to a bad installation of mojave.

**Comment by DSchau** [comment]
@Azagoth thanks for letting us know! Going to close this out, then.
