### ISSUE TITLE
[1.0] using-postcss-sass example broken

### ISSUE THREAD

**Issue by craig-mulligan** [gatsbyjs/gatsby#1015]
running the `using-postcss-sass` after a fresh clone && `npm i` gives you a `SyntaxError: Unexpected character '@'` error which suggests the sass-loader wasn't applied to the webpack config. 

I haven't had a chance to really look into it but my first guess is that gatsby isn't seeing the symlink that npm creates when installing a local package with the `file:` mechanism. Because after manually installing `gatsby-plugin-postcss-sass` the example runs as expected.

**Comment by KyleAMathews** [comment]
Huh strange. Good to know. You want to do a quick PR to just change that package to "canary"? I set it to use the file thing originally before I'd published the `gatsby-plugin-postcss-sass` package but now that it's out it should be fine just using "canary".

**Comment by craig-mulligan** [comment]
Done @KyleAMathews, let me know if there are any conventions I missed for PRs, I skim read the contributing guide :)

**Comment by KyleAMathews** [comment]
Eh, not too many conventions. Thanks!
