### ISSUE TITLE
Gatsby plugin offline ios safari bug

### ISSUE THREAD

**Issue by PeterKerins** [gatsbyjs/gatsby#10151]
## Description
Gatsby site returns "Safari cannot open the page. The error was: "FetchEvent.respondWith. received an error: Returned response is null."

### Steps to reproduce
Open site as normally,
close safari or go to another webpage & return to site.

### Expected result

Site should load as normal

### Actual result

Error screen is returned

### Environment

  System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.9.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Firefox: 63.0.3
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.55 => 2.0.55 
    gatsby-image: ^2.0.20 => 2.0.20 
    gatsby-plugin-manifest: ^2.0.10 => 2.0.10 
    gatsby-plugin-offline: ^2.0.17 => 2.0.17 
    gatsby-plugin-react-helmet: ^3.0.1 => 3.0.2 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sharp: ^2.0.13 => 2.0.13 
    gatsby-plugin-styled-components: ^3.0.1 => 3.0.3 
    gatsby-source-filesystem: ^2.0.9 => 2.0.9 
    gatsby-source-prismic: ^2.0.0 => 2.1.0 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.2

**Comment by edykim** [comment]
I've got the same problem. I'm not sure how I stuck in this status.

<img width="868" alt="screen shot 2018-11-30 at 7 27 20 am" src="https://user-images.githubusercontent.com/33057457/49298412-32c4af80-f472-11e8-8410-1f04bf193eb1.png">

  System:
    OS: macOS 10.14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
    Yarn: 1.12.3 - ~/.nvm/versions/node/v10.11.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 60.0.1
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.59 => 2.0.50 
    gatsby-plugin-catch-links: ^2.0.9 => 2.0.8 
    gatsby-plugin-feed: ^2.0.10 => 2.0.7 
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.6 
    gatsby-plugin-manifest: ^2.0.11 => 2.0.9 
    gatsby-plugin-netlify: ^2.0.6 => 2.0.5 
    gatsby-plugin-offline: ^2.0.18 => 2.0.15 
    gatsby-plugin-react-helmet: ^3.0.3 => 3.0.2 
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.1 
    gatsby-plugin-typography: ^2.2.2 => 2.2.0 
    gatsby-remark-prismjs: ^3.1.2 => 3.0.1 
    gatsby-source-filesystem: ^2.0.10 => 2.0.8 
    gatsby-transformer-remark: ^2.1.15 => 2.1.12 
  npmGlobalPackages:
    gatsby-cli: 2.4.6

----

I've found this error from the workbox issue and it looks like a safari bug. https://github.com/GoogleChrome/workbox/issues/1730#issuecomment-432728836

**Comment by dubcanada** [comment]
Also getting this error?

**Comment by rappad** [comment]
i'm facing the same problem.

**Comment by krystiansliwa** [comment]
I also had that problem in iOS 12.1, Today upgraded to iOS 12.1.1 and it works now
