### ISSUE TITLE
Create pullquote styles for .org site

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#10168]
Pulled out of #9847.

Points of consideration:
- multiple styles (quote style, highlight style) -- as you've suggested, @greglobinski 
- implement using [custom components](https://using-remark.gatsbyjs.org/custom-components/)

![pull-quote-v1](https://user-images.githubusercontent.com/3461087/49109205-bfdbee80-f24f-11e8-91b6-55e0c35cefc7.png)

***

![pull-quote-v2](https://user-images.githubusercontent.com/3461087/49109212-c4a0a280-f24f-11e8-9983-7bfe19522614.png)

**Comment by greglobinski** [comment]
New variations of the designs 

1. a quotation mark to indicate it's a quote added

![screenshot from 2018-11-28 23-21-50](https://user-images.githubusercontent.com/32480082/49186278-729d7100-f364-11e8-893e-5f0c3160a149.png)

2. the 'invisible' yellow color removed

![screenshot from 2018-11-28 23-22-04](https://user-images.githubusercontent.com/32480082/49186279-729d7100-f364-11e8-876f-393713598377.png)

@lindaleebumblebee

**Comment by lindaleebumblebee** [comment]
Thank you. Both are great, but now I like the first one the best (with the box and 'stars') :)

**Comment by lindaleebumblebee** [comment]
Love it! Looks great.

**Comment by amberleyromo** [comment]
Closed in #10190
