### ISSUE TITLE
Proper way to use a constant on graphQL queries?

### ISSUE THREAD

**Issue by hanoii** [gatsbyjs/gatsby#10163]
I think I want to do something simple, although I wonder if there's a proper way of doing this?

My backend (drupal) will administer content for several gatsby sites (microsites) and I want to run all queries using that constant, so in my case with a constant value:

```graphql
    allNodeSome (
        filter: {
          relationships: {
            field_site: {
              drupal_internal__tid: {
                eq: 1
              }
            }
          }
        }
      ) {
```

but `eq: 1` should be something that I provide by some mean. It could be an `ENV`. My immediate thought was to use siteMetada for that, but then how do I use that on a query?

I guess I could add it as another config file as well, but again, how do I pass a static variable if string interpolation is not allowed.

You would think I should be able to use variables, but how do I pass a variable to page that's automatically created through the `/pages` dir.

And finally, I also want to be able to use this on static queries that doesn't support variables, so I am stuck with this.

Any help/advise?

**Comment by jgierer12** [comment]
You can add parameters to the `pageQuery` with the `context` object in `cratePages`. You can take a look at the docs for [modifying pages created by Gatsby](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#modifying-pages-created-by-core-or-plugins) and [programatically creating pages](https://www.gatsbyjs.org/docs/programmatically-create-pages-from-data/) to get started.

It's not the most straight-forward solution, so if you have any questions, feel free to ask!

**Comment by LekoArts** [comment]
> but eq: 1 should be something that I provide by some mean.

You only can use variables passed by context.

> You would think I should be able to use variables, but how do I pass a variable to page that's automatically created through the /pages dir.

You delete the page and create it with the new context.
Simplified: https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#removing-trailing-slashes
What I do: https://github.com/LekoArts/portfolio/blob/master/gatsby-node.js#L53-L85 (the `createPage` is important)

> And finally, I also want to be able to use this on static queries that doesn't support variables, so I am stuck with this.

You can't do that.

**Comment by jgierer12** [comment]
> I wonder why string interpolation is not supported?

Because it wasn't implemented (yet) - PRs are always appreciated 😉

**Comment by hanoii** [comment]
@jgierer12 well, string interpolation is out of the box on template literals: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Expression_interpolation.

I wonder why is specifically not allowed, there must be a reason

**Comment by LekoArts** [comment]
> What does it mean it works on gatsby-node.js, how would you use a grapql query on gatsby-node.js?

The two links above show how you can use the `onCreatePage` API in `gatsby-node` to pass context to your pages (in `src/pages`) so that you have it available as variable. And you can set that context as `NODE_ENV` (I believe)

**Comment by jgierer12** [comment]
I'm not an expert on how the query extraction works in Gatsby, but IIRC the queries get extracted directly from the AST, without executing any dynamic code.

**Comment by hanoii** [comment]
@LekoArts thanks for the links, and I see now how I can use `onCreatePage` to achieve something close to what i need, but I am still stuck for StaticQueries, and I was planning on using them quite a bit.
