### ISSUE TITLE
Gatsby develop deletes cache when initializing and with it all downloaded files

### ISSUE THREAD

**Issue by osartun** [gatsbyjs/gatsby#10161]
## Description

This might be related to https://github.com/gatsbyjs/gatsby/issues/4464, but the issue looks like it's resolved so I'm opening this new one.

When running `gatsby develop` it clears almost the entire `.cache` directory. This also removes the `gatsby-source-filesystem` folder that contains downloaded files from source plugins (`gatsby-source-wordpress` in my case) which means that these downloaded files need to be re-downloaded on every start up.

Here a GIF screencast (that I spent way too much time on) that shows how the directory and the `gatsby-source-filesystem` folder are removed when running `gatsby develop`:
![gatsby-deletes-cache-on-startup-4](https://user-images.githubusercontent.com/1381730/49084221-1d237000-f24f-11e8-938c-742090085bfe.gif)

### Expected result

Gatsby uses the cached contents and downloaded files aren't downloaded again

### Actual result

Gatsby clears most of the cache including downloaded files.

### Environment

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.0.0 - /usr/local/Cellar/nvm/0.33.11/versions/node/v11.0.0/bin/node
    Yarn: 1.12.3 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/Cellar/nvm/0.33.11/versions/node/v11.0.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Firefox: 63.0.3
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.0 => 2.0.31
    gatsby-image: ^2.0.13 => 2.0.17
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-resolve-src: 2.0.0-beta.1 => 2.0.0-beta.1
    gatsby-plugin-sass: ^2.0.1 => 2.0.1
    gatsby-plugin-sharp: ^2.0.6 => 2.0.8
    gatsby-source-filesystem: ^2.0.2 => 2.0.5
    gatsby-source-wordpress: ^3.0.15 => 3.0.15
    gatsby-transformer-sharp: ^2.1.3 => 2.1.5
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

**Comment by osartun** [comment]
This issue might be related to this comment: https://github.com/gatsbyjs/gatsby/issues/6654#issuecomment-437908503

**Comment by DSchau** [comment]
@osartun I can't really read some of the text in the terminal, but is there something like

> One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data

We do some diffing of common situations in which you'd _want_ to delete the cache (e.g. hash of package.json, gatsby-config.js, gatsby-node.js, etc, changes), so just want to first confirm that's not the issue.

Next step is to just attempt to upgrade all of your packages. I like to use `yarn upgrade-interactive --latest`--which gives you an interactive prompt where you can just upgrade the gatsby packages.

If the issue still persists, let's try and get a repro put together--if possible!--so that we can attempt to validate this issue ourselves.

Thanks, and sorry for your issue here!

**Comment by osartun** [comment]
@DSchau Thanks for your reply!
I searched my Terminal output for the text you quoted, but couldn't find it there.

> We do some diffing of common situations in which you'd want to delete the cache (e.g. hash of package.json, gatsby-config.js, gatsby-node.js, etc, changes)

That's reasonable. However, the cache was removed between executing `gatsby develop` without changing anything else.

However, my issue might really be related to issues with `gatsby-source-wordpress`, because I also experienced the never ending `source and transform nodes` state that several people have talked about already (https://github.com/gatsbyjs/gatsby/issues/4293, https://github.com/gatsbyjs/gatsby/issues/6385, https://github.com/gatsbyjs/gatsby/issues/4666, https://github.com/gatsbyjs/gatsby/issues/7855, https://github.com/gatsbyjs/gatsby/issues/6654).
I've read through the thread of https://github.com/gatsbyjs/gatsby/issues/6654 and added the `"resolution": { "got": … }` to my `package.json` that somebody suggested (https://github.com/gatsbyjs/gatsby/issues/6654#issuecomment-421922448).

---

While writing these lines I've tried reproducing my issue again. But it seems like it's resolved since resolving `got` to a new version.
So, sorry for prematurely filing this issue.

However, now I'm running into other caching issues:

```
error UNHANDLED REJECTION


  TypeError: Cannot read property 'internal' of null

  - infer-graphql-input-fields.js:346 _.each
    [publizist-frontend-gatsby]/[gatsby]/dist/schema/infer-graphql-input-fields.js:346:38
```
But I think this is also related to problems that are already discussed in https://github.com/gatsbyjs/gatsby/issues/6654 – namely requests silently failing which needs to `null` nodes being created.

---

As the issue at hand seems to be resolved I'm closing this issue now.

**Comment by shendriksza** [comment]
To anyone scouring the internet for a solution to this, a quick and dirty fix is to copy your `.cache/gatsby-source-filesystem` to `node_modules/.cache` after a build and back again before a build.

Naturally, you might have issues where a file change does not reflect, then you just have to manually delete the backup. But at least this allows people like me to run builds without redownloading gigabytes of data from our WordPress server.

Add the following two functions to your `gatsby-node.js` to automate the process:

```
exports.onPostBuild = async ({ reporter }) => {
	await fs.ensureDir("node_modules/.cache/gatsby-source-filesystem")

	if (fs.existsSync(".cache/gatsby-source-filesystem")) {
		console.log(
			"onPostBuild: Copying gatsby-source-filesystem to node_modules"
		)
		await fs.copy(
			".cache/gatsby-source-filesystem",
			"node_modules/.cache/gatsby-source-filesystem"
		)
	}
}

exports.onPreBootstrap = async ({ reporter }) => {
	if (fs.existsSync("node_modules/.cache/gatsby-source-filesystem")) {
		console.log(
			"onPreBootstrap: Copying gatsby-source-filesystem to .cache"
		)
		await fs.copy(
			"node_modules/.cache/gatsby-source-filesystem",
			".cache/gatsby-source-filesystem"
		)
	}
}
```

**Comment by carlaiau** [comment]
@shendriksza you're a life saver! I'm developing with around 20K thumbnails
