### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by GemmaGarcias** [gatsbyjs/gatsby#10164]
I am migrating from React v.15.3 to 15.6 and I have some warnings.
What could I do? Because my goal is migrate to React v.16.
![screen shot 2018-11-27 at 18 01 49](https://user-images.githubusercontent.com/30416900/49098253-c62d9300-f26e-11e8-83e3-43cea4a3545f.png)

**Comment by LekoArts** [comment]
Please follow the issue template in the future as I now ask you the question that the template already asked you:

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

**Comment by LekoArts** [comment]
@GemmaGarcias Hey 👋, I didn't intend to scare you away (if it's what I did). If you found your solution: Great! If not, please feel free to re-open.
