### ISSUE TITLE
Version update to 2.0.55: `SyntaxError: Unexpected token .`

### ISSUE THREAD

**Issue by stefan--** [gatsbyjs/gatsby#10167]
## Description

After updating from version `2.0.50` to `2.0.55` the command `gatsby develop --https` fails due to an uncaught error:

```
.../public/render-page.js:35834
    {}.TEST_PSEUDOMAP = 'true'
      ^
  SyntaxError: Unexpected token .
```
Given I exclude the SSR API usages for wrapping the element in a provider and an error boundary, the above command runs successfully, however, the bundle is broken logging the same error `Uncaught SyntaxError: Unexpected token .`

### Steps to reproduce

I am still trying to figure out a reproducible  setup.

### Expected result

It should be running successfully as it does using gatsby version `2.0.50`

### Actual result

See above

### Environment

```

  System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.12.3 - ~/.config/yarn/global/node_modules/.bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Safari: 12.0.1
  npmPackages:
    gatsby: 2.0.55 => 2.0.55
    gatsby-cli: 2.4.5 => 2.4.5
    gatsby-image: 2.0.20 => 2.0.20
    gatsby-link: 2.0.6 => 2.0.6
    gatsby-plugin-i18n: 0.4.2 => 0.4.2
    gatsby-plugin-manifest: 2.0.9 => 2.0.9
    gatsby-plugin-netlify: 2.0.5 => 2.0.5
    gatsby-plugin-offline: 2.0.16 => 2.0.16
    gatsby-plugin-page-creator: 2.0.4 => 2.0.4
    gatsby-plugin-react-helmet: 3.0.2 => 3.0.2
    gatsby-plugin-sass: 2.0.4 => 2.0.4
    gatsby-plugin-sharp: 2.0.12 => 2.0.12
    gatsby-plugin-svgr: 2.0.1 => 2.0.1
    gatsby-plugin-typescript: 2.0.1 => 2.0.1
    gatsby-react-router-scroll: 2.0.1 => 2.0.1
    gatsby-source-filesystem: 2.0.8 => 2.0.8
    gatsby-transformer-sharp: 2.1.8 => 2.1.8
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

I would appreciate ideas how to narrow down the issue further. Thanks

**Comment by stefan--** [comment]
Another dependency caused the bundle to break.

**Comment by parkerself22** [comment]
@stefan-- running into the same issue, any chance you remember what dependency was causing the issue?

**Comment by dandv** [comment]
Same here, how do you track these errors?

**Comment by dandv** [comment]
[This](https://github.com/isaacs/pseudomap/blob/master/map.js#L3) is the culprit. As @wardpeet explained [here](https://github.com/gatsbyjs/gatsby/issues/12901#issuecomment-477619581), Webpack can't deal with assignments to environment variables. @isaacs, any chance to avoid that statement in [pseudomap](https://www.npmjs.com/package/pseudomap)?
