### ISSUE TITLE
yarn create

### ISSUE THREAD

**Issue by g8tguy** [gatsbyjs/gatsby#1016]
Good news everyone! 
With the latest `yarn` release, we now can use `yarn create gatsby-app some-blog` it will handle the `gatsby` global installation. [yarn create](https://yarnpkg.com/blog/2017/05/12/introducing-yarn/)
The only problem I see, we need to create a package called `create-gatsby-app` in order for it to work

**Comment by KyleAMathews** [comment]
This only works if there's a create-gatsby package.

**Comment by g8tguy** [comment]
yeah,  it's kind of a bummer.

**Comment by neelkarma** [comment]
[well now there is!](https://www.npmjs.com/package/create-gatsby)
