### ISSUE TITLE
Consider make code example more clear in "Adding analytics"

### ISSUE THREAD

**Issue by Rahmon** [gatsbyjs/gatsby#10188]
## Description
In [Adding analytics](https://www.gatsbyjs.org/docs/adding-analytics/#using-gatsby-plugin-google-analytics) page shows how to add Google Analytics in Gatsby. It's necessary install gatsby-plugin-google-analytics and add some configuration in gatsby-config.js. Currently the page show the config below:

```
{
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        // replace "UA-XXXXXXXXX-X" with your own Tracking ID
        trackingId: "UA-XXXXXXXXX-X",
      },
},
```

Although the config works, I think that may be more informative:

```
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        // replace "UA-XXXXXXXXX-X" with your own Tracking ID
        trackingId: "UA-XXXXXXXXX-X",
      }
    }
  ]
};
```

In [gatsby-plugin-google-analytics](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/#how-to-use) the example is like code above.

**Comment by dorukde** [comment]
The link `https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/`
gives 
`This site can’t be reached The web page at https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/ might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED` on my computer.

**Comment by Rahmon** [comment]
Hi @dorukde.

The two links works for me. 

https://www.gatsbyjs.org/docs/adding-analytics/#using-gatsby-plugin-google-analytics
https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/#how-to-use

**Comment by dorukde** [comment]
It was my adblocker for some reason. It is still smth to consider as a detail probably.
