### ISSUE TITLE
Getting "Error: socket hang up" often with gatsby develop

### ISSUE THREAD

**Issue by tchaffee** [gatsbyjs/gatsby#10205]
## Description

When I run `gatsby develop -H 0.0.0.0` I eventually get an "Error: socket hang up" error and have to restart gatsby develop.

### Steps to reproduce

I don't know how to reproduce the issue, but I'm happy to give any information about my dev env that might help.

### Expected result

App shouldn't crash.

### Actual result

App crashes.

### Environment

  System:
    OS: Linux 4.4 Ubuntu 16.04.4 LTS (Xenial Xerus)
    CPU: (2) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm

It might also be relevant that I'm running this in Vagrant and it is running as part of an npm script.

**Comment by tchaffee** [comment]
I also just noticed that this seems to only happen when I am testing in FireFox. Chrome has not crashed the app yet.

**Comment by jonniebigodes** [comment]
I'm not well versed with vagrant but could something like [this](https://stackoverflow.com/questions/33129651/access-web-server-on-virtualbox-vagrant-machine-from-host-browser) help you out?
