### ISSUE TITLE
[gatsby-image] Image with aspectRatio not scaled properly on IE11

### ISSUE THREAD

**Issue by pippo111** [gatsbyjs/gatsby#10200]
## Description

When trying to set aspectRatio property image are not scaled properly on internet explorer 11

**Possible solution, that works for me:**
I noticed, that for e.g. 2.5 aspectRatio, padding-bottom in div below gatsby-image-wrapper is set to 40%. This works for modern browsers, but not for ie11. Setting csses like this works everywhere:

```
.gatsby-image-wrapper {
    & > div {
      padding-bottom: 40%;
    }
    & img {
      top: -40%;
      height: auto;
    }
  }
```

### Steps to reproduce

Try to set aspectRatio on <Img> component, like this:
<Img fluid={{ ...image.childImageSharp.fluid, aspectRatio: 2.5 }} />}

### Expected result

Image should be centered and scaled to proper ratio

![image](https://user-images.githubusercontent.com/22401020/49219157-c0e95900-f3d2-11e8-9cea-d348e35f9e13.png)

What should happen?

### Actual result

Image on IE11 actually looks like this:

![image](https://user-images.githubusercontent.com/22401020/49219187-d9597380-f3d2-11e8-994f-6bbff77eb259.png)

### Environment

```
  System:
    OS: Linux 4.19 Solus 3.9999
    CPU: x64 Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz
    Shell: 2.7.1 - /usr/bin/fish
  Binaries:
    Node: 8.13.0 - /usr/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Firefox: 63.0.3
  npmPackages:
    gatsby: ^2.0.50 => 2.0.50 
    gatsby-cli: ^2.4.3 => 2.4.3 
    gatsby-image: ^2.0.15 => 2.0.15 
    gatsby-paginate: ^1.0.16 => 1.0.16 
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4 
    gatsby-plugin-google-tagmanager: ^2.0.6 => 2.0.6 
    gatsby-plugin-less: ^2.0.5 => 2.0.5 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5 
    gatsby-plugin-polyfill-io: ^1.0.5 => 1.0.5 
    gatsby-plugin-purgecss: ^2.4.0 => 2.4.0 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.7 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.0.5 => 2.0.5 
    gatsby-source-firebase: ^1.0.0 => 1.0.0 
    gatsby-source-firestore: ^1.0.3 => 1.0.3 
    gatsby-source-wordpress: 3.0.4 => 3.0.4 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

**Comment by mik-laj** [comment]
Related to: https://github.com/gatsbyjs/gatsby/issues/4021
