### ISSUE TITLE
Per-format quality settings for Gatsby Image (transformer/sharp)

### ISSUE THREAD

**Issue by coreyward** [gatsbyjs/gatsby#10203]
## Summary

I'd like to see Gatsby Image support different quality settings for each image format available.

### Basic example

Here's what this could look like: 

```graphql
  query Example {
    resource {
      coverImage {
        fluid(maxWidth: 100, webp_quality: 90, jpg_quality: 50, png_quality: 60) {
          ...GatsbyImageSharpFluid_withWebp
        }
      }
    }
  }
```

### Motivation

Quality settings for JPG and PNG roughly align, but quality settings for WebP are _very_ different. Currently there's no way to specify that you'd like 90-quality WebP images and 50-quality JPG images in a Gatsby image query. 

A fallback could be established such that the default quality remains `50`, the `quality` setting overrides, and any undeclared format-specific quality settings fall back to whatever `quality` is set at. Setting `quality: 70, webp_quality: 90` would have the effect of setting the JPG and PNG quality to `70` while WebP quality is `90`.

**Comment by coreyward** [comment]
I did a dive into this around the time I create the issue and found that doing this was a bit convoluted due to the way the code associated with this is structured and the different approach needed for `gatsby-image-contentful`. 

I'm still interested in making this happen, but don't have bandwidth right now.

**Comment by baobabKoodaa** [comment]
I would love to see this happen!

**Comment by Devin-Chaves** [comment]
Me too!

**Comment by isaacschwab** [comment]
Has there been any progress on this issue? I'm having issues where my jpgs look fine with 50%, however, webp is getting too crunched. It would be really helpful to have this enhancement.

**Comment by coreyward** [comment]
@isaacschwab Not as far as I'm aware, no. 

I'm using [Imgix](https://www.imgix.com/) on a number of projects, so I have the benefit of being able to generate multiple sizes and qualities by changing URL parameters. Instead of using the sharp pipeline stuff I've opted to build my own components that will generate a `srcset` for me using those URLs, which sidesteps this need.

**Comment by isaacschwab** [comment]
@coreyward thanks for the response, and creating the initial issue. I have used similar tools to Imgix, they work well. For my current project I'm unable to go that route.  I think your proposed enhancement would be great for the flexibility and functionality of Gatsby, so hopefully this gets some more traction.

**Comment by coreyward** [comment]
@isaacschwab I agree, this should be added to Gatsby. Unfortunately the tight coupling between source plugins and the existing implementation make this more difficult than it should be. I'd be happy to team up with someone later this summer to create an extensible API for source-plugins to tap into and refactor the existing monorepo'ed source plugins to use it.

**Comment by graysonhicks** [comment]
I can attest that this is very important.  For webp browsers, we are able to keep our images at better resolutions and higher quality setting and still keep great image file sizes in the end.  Unfortunately the fallback images at these settings are outrageously large.  For this example, a full screen very heigh quality webp image is 500kb, but the fallback png is 4.1MB. 😔

**Comment by vladar** [comment]
@coreyward Will the approach taken in #18548 fix this for you?

**Comment by coreyward** [comment]
#18548 is a great step forward! These changes also need be applied to the official/monorepo'ed gatsby-source-contentful plugin, and we should get some documentation written up on the new parameters.

**Comment by vladar** [comment]
Mind creating a follow-up issue?
