### ISSUE TITLE
gatsby-plugin-layout is still re-rendering the content

### ISSUE THREAD

**Issue by hassanshaikley** [gatsbyjs/gatsby#10213]
I am not sure why but layout is being re-rendered. 

In the config it's just `'gatsby-plugin-layout',` without any configOptions. 

then there's `src/layouts/index.js` which is properly being used as a layout. It's just getting rerendered.

I expected this plugin to stop re-rendering of the layout component (one of the children of the layout relies on a component did mount to render properly, and takes a second).

```
  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    Shell: 5.3.1 - /usr/bin/zsh
  Binaries:
    Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v8.13.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 60.3.0
  npmPackages:
    gatsby: ^2.0.59 => 2.0.59
    gatsby-image: ^2.0.22 => 2.0.22
    gatsby-plugin-layout: ^1.0.10 => 1.0.10
    gatsby-plugin-manifest: ^2.0.11 => 2.0.11
    gatsby-plugin-offline: ^2.0.18 => 2.0.18
    gatsby-plugin-react-helmet: ^3.0.3 => 3.0.3
    gatsby-plugin-sass: ^2.0.5 => 2.0.5
    gatsby-plugin-sharp: ^2.0.14 => 2.0.14
    gatsby-source-filesystem: ^2.0.10 => 2.0.10
    gatsby-transformer-json: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9
  npmGlobalPackages:
    gatsby: 2.0.59
```

**Comment by jonniebigodes** [comment]
If you can provide a repository for the issue it would be great.

**Comment by hassanshaikley** [comment]
Unfortunately it is proprietary! I just created my own templating plugin but I will take a look at the source for the templating plugin and see what's going on in the future. Thank you1
