### ISSUE TITLE
boundActionCreators warning for non-gatsby code

### ISSUE THREAD

**Issue by richsoni** [gatsbyjs/gatsby#10211]
Hello,

My repo has a folder with javascript that is not part of gatsby.  It is located in `./archives` from the root.

When I build, I get this warning:
```

boundActionCreators is deprecated. Please use actions instead. For migration instructions, see https://gatsby.app/boundActionCreators
Check the following files:

archive/2018-08-04/bundle.js
```

I believe its because this line:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/develop.js#L391

**Comment by jgierer12** [comment]
Can you provide a demo where this issue can be reproduced, or a link to your repo?

**Comment by richsoni** [comment]
Hey @jgierer12, I just added you to my repo https://github.com/richsoni/www-richsoni.com/settings/collaboration

**Comment by richsoni** [comment]
I can also make a demo if thats easier
