### ISSUE TITLE
[babel-preset-gatsby] Should the default babel preset bring Optional Chaining?

### ISSUE THREAD

**Issue by lukewhitehouse** [gatsbyjs/gatsby#10214]
## Summary

Should the default babel preset be bringing in optional chaining? The [readme](https://github.com/gatsbyjs/gatsby/tree/master/packages/babel-preset-gatsby) mentions it does, but the [dependencies](https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby/package.json#L5) don't bring it in.

It'd be good to understand the direction one way or another, I'm happy to patch either scenario to help alleviate confusion.

**Comment by DSchau** [comment]
@lukewhitehouse whoops, yeah!

I don't have a strong preference here. I think we want to offer a safe, optimized preset that others can _extend_ if they desire. I'd say we tweak the README, but I'm open to including the plugin if you think that makes sense.

What do you think?

**Comment by abumalick** [comment]
Now that optional chaining has been shipped in typescript and vscode, I think it would be nice to add optional chaining to gatsby preset.

What do you think ?
https://code.visualstudio.com/updates/v1_40#_building-vs-code-with-typescript-37
