### ISSUE TITLE
Can a plugin require additional plugins?

### ISSUE THREAD

**Issue by pstephan1187** [gatsbyjs/gatsby#10231]
## Summary
I am creating a plugin that relies on other plugins to work. Currently, the user would have to install and configure these other plugins before using the one I am developing. Is there a way to configure my plugin to have gatsby install and configure some additional plugins as needed without having the user manually install them?

## Relevant information

NA

### Environment (if relevant)

NA

### File contents (if changed)

NA

**Comment by jonniebigodes** [comment]
If i'm reading this right, i'll try and and help you a bit if i can.
And with that i'm breaking my answer into two parts.

- Installation
  If your plugin requires other plugins, what you could always do is on your plugin's package.json add those plugins as dependencies and then when the user installs your plugin, the dependencies are picked up and added aswell. The only scenario off the top of my head that might have impact in this situation is that the user had previously added the `gatsby-x-plugin` that you also use and that would generate a bit of extraneous work.

- Configuration
  The configuration is a bit more tricky as for what i know from using gatsby and diving through documentation either in code or github repositories. But the status quo and recomended approach is to have the plugins configuration injected always in the `gatsby-config.js`.
With that, your plugin configuration options would be created there and also whatever plugins you depend on.

Again based on my meager knowledge of gatsby.
I'll leave you with the documentation links for the tutorial of [creating a plugin](https://www.gatsbyjs.org/docs/source-plugin-tutorial/) for gatsby and the 
[plugin authoring](https://www.gatsbyjs.org/docs/plugin-authoring/) part
Hope that could shed some insight on the matter.

**Comment by mitchheddles** [comment]
@pstephan1187 I need to do something similar when creating a conditional gatsby plugin and got it working. The main issue was webpack require messing with dynamic imports.

The plugin config in `gatsby-config.js` looks like this:
```
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-conditional',
      options: {
        exclude: ['embed/*'],
        plugins: [
          {
            resolve: 'gatsby-plugin-intercom',
            options: {
              appId: '123',
            },
          },
        ],
      },
    },
  ],
};

```

Having the `plugins` key will cause gatsby to go over each item in the list, which is fine, but it just changes the output when you _use_ the plugins.

In the plugin `gatsby-ssr.js`:
```
export const onRenderBody = (args, pluginOptions) => {
  const shouldExclude = (pluginOptions.exclude || []).some(patternString => {
    const pattern = new RegExp(patternString);
    return pattern.test(args.pathname);
  });

  if (shouldExclude) {
    return;
  }

  pluginOptions.plugins.forEach(plugin => {
    const requireFunc =
      typeof __webpack_require__ === 'function' ? __non_webpack_require__ : require;
    const { onRenderBody: pluginOnRenderBody } = requireFunc(`${plugin.name}/gatsby-ssr.js`);
    pluginOnRenderBody(args, plugin.pluginOptions);
  });
};
```

Note, it's quite a specific example, but hopefully it helps you.
