### ISSUE TITLE
[Site showcase] Visit site buttons are not mobile responsive

### ISSUE THREAD

**Issue by daydream05** [gatsbyjs/gatsby#10242]
When you visit a site showcase the "visit site" buttons are blocking the "source code" button as seen here.

<img width="374" alt="screen shot 2018-12-02 at 1 43 47 pm" src="https://user-images.githubusercontent.com/11723413/49343513-9567a800-f638-11e8-982a-5885b4579009.png">

Based on this design by @fk this is how it's supposed to look

https://projects.invisionapp.com/share/T9H9LRCG8Z5#/screens/292717378

<img width="362" alt="screen shot 2018-12-02 at 1 47 41 pm" src="https://user-images.githubusercontent.com/11723413/49343523-df508e00-f638-11e8-8e72-977b78fea088.png">

**Comment by daydream05** [comment]
This should be a quick fix. I'll be happy to do a PR

**Comment by daydream05** [comment]
Please no one else fix this. This is probably the only PR i can do 😂

**Comment by wardpeet** [comment]
cleaning up the PR and getting it merged

**Comment by wardpeet** [comment]
@daydream05 thank you for starting on this PR. We finally got it merged!
