### ISSUE TITLE
gatsbyjs.org is giving errors 

### ISSUE THREAD

**Issue by davehallman** [gatsbyjs/gatsby#10246]
All links to the docs lead to an error message

**Comment by pieh** [comment]
What kind of error? I've briefly checked and I'm not getting any errors so more context is needed

**Comment by davehallman** [comment]
Hi,

Sorry for the lack of context but I was on my phone last night but the page wouldn't allow me to  copy/paste the error. Attached is a screen shot. I'm still seeing the same error on my phone but only from Safari. It also loads just fine from my laptop.

Thanks

Dave
![img_2141](https://user-images.githubusercontent.com/718297/49400634-d59b5900-f712-11e8-9a5c-e7f6516690d9.png)

**Comment by AnushPatel** [comment]
Hi Dave,
So this only occurs when you go to the docs? If so - Can you outline the steps you took to get to the error? (I find that I can take a very weird way of getting from point A to B 🤦‍♂️)


Keep me posted,


Anush :-)

**Comment by davehallman** [comment]
Hi Anush,

Sorry for the slow reply - I just tried again today and all is well. I can get to all the pages, so issue can be closed. Thanks.

Dave
