### ISSUE TITLE
[gatsby-transformer-remark] Headings are lowercase in a tag href - links are not working

### ISSUE THREAD

**Issue by alexcroitoru95** [gatsbyjs/gatsby#10253]
## Description

The [tableOfContents](https://www.gatsbyjs.org/packages/gatsby-transformer-remark/#getting-table-of-contents) that **gatsby-transformer-remark** provides is making lowercase of all the Headings from Markdown and so the links are not working (a tag href).

### Steps to reproduce

This is how I make the query:

<img width="684" alt="screenshot 2018-12-03 at 12 12 26" src="https://user-images.githubusercontent.com/22367700/49367717-8135b080-f6f5-11e8-8e9a-5afaf58e9204.png">

This is the Markdown file:

<img width="1180" alt="screenshot 2018-12-03 at 12 14 01" src="https://user-images.githubusercontent.com/22367700/49367740-914d9000-f6f5-11e8-97af-a5193b9c8f7d.png">

This is the HTML (the ID's on the h1 tags are coming from **gatsby-remark-autolink-headers**)

<img width="1358" alt="screenshot 2018-12-03 at 12 17 15" src="https://user-images.githubusercontent.com/22367700/49367963-35cfd200-f6f6-11e8-80dc-8c76bc708ec8.png">

### Expected result

All the links in the href should be like the corresponding Heading from the Markdown File.

### Actual result

This is the result that comes from tableOfContents:

<img width="1679" alt="screenshot 2018-12-03 at 12 13 05" src="https://user-images.githubusercontent.com/22367700/49367760-9f9bac00-f6f5-11e8-8f25-ecdbc14ca82c.png">

### Environment

 ```
System:
    OS: macOS 10.14.1
    CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.1.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.50 => 2.0.59
    gatsby-cli: ^2.4.4 => 2.4.6
    gatsby-image: ^2.0.10 => 2.0.22
    gatsby-link: ^2.0.0-rc.4 => 2.0.7
    gatsby-plugin-catch-links: ^2.0.2-rc.1 => 2.0.9
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4
    gatsby-plugin-google-analytics: ^2.0.7 => 2.0.8
    gatsby-plugin-mailchimp: https://github.com/benjaminhoffman/gatsby-plugin-mailchimp.git#gatsby-v2 => 3.3.0
    gatsby-plugin-manifest: ^2.0.11 => 2.0.11
    gatsby-plugin-netlify: ^2.0.4 => 2.0.6
    gatsby-plugin-offline: ^2.0.18 => 2.0.18
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.3
    gatsby-plugin-sass: ^2.0.0-rc.2 => 2.0.5
    gatsby-plugin-sharp: ^2.0.5 => 2.0.14
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.4
    gatsby-plugin-twitter: ^2.0.7 => 2.0.8
    gatsby-remark-autolink-headers: ^2.0.6 => 2.0.12
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.7
    gatsby-remark-images: ^2.0.3 => 2.0.6
    gatsby-remark-prettier: ^1.0.0-alpha.0 => 1.0.0
    gatsby-remark-prismjs: ^3.0.0-rc.2 => 3.1.2
    gatsby-remark-responsive-iframe: ^2.0.0-rc.5 => 2.0.7
    gatsby-source-filesystem: ^2.0.1-rc.6 => 2.0.10
    gatsby-source-twitter: ^1.3.4 => 1.3.4
    gatsby-transformer-remark: ^2.1.1-rc.5 => 2.1.15
    gatsby-transformer-sharp: ^2.1.2 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.3
```

**Comment by alexcroitoru95** [comment]
The problem was the **maintainCase: true** on gatsby-config.js.

**Comment by Jaikant** [comment]
Thanks this was helpful!
