### ISSUE TITLE
graphql Cannot read property 'node' of undefined but the query works in the graphql interface

### ISSUE THREAD

**Issue by derridHeidegger** [gatsbyjs/gatsby#10256]
## Summary
hey, i am new to gatsby and i play with it, and i am building a blog (multiple language). 
the blog page should paginate the blog posts.
so in my gatsby-node file i use createPage and send a context, according to which on the blog page i do a query:

```js
const testPaginatedBlogPages = ({lang,TotalCount,postsPerPage,createPage,posts}) => {

  const numPages = Math.ceil(TotalCount / postsPerPage);

    
    posts.forEach(({node}, i) => {
      const localizedPath = lang === 'he' ? '' : lang;

      createPage({
        path: i === 0 ? `${localizedPath}/blog` : `${localizedPath}/blog/${i+1}`,
        component: require.resolve('./src/pages/blog.js'),
        context: {
          limit: postsPerPage,
          skip: i * postsPerPage,
          totalPages: numPages,
          currentPage: i + 1,
          locale: lang
        },
      })
    })

}
```

and the query in the blog page:

```js
export const BlogQuery = graphql`
query($locale : String , $limit : Int,$skip : Int ) {
  allMarkdownRemark(
    filter: {frontmatter: {locale: {eq: $locale}}},
    sort: { fields: [frontmatter___date], order: DESC },
    limit: $limit,
    skip: $skip
  ) {
    totalCount
    edges {
        node {
          id
          frontmatter {
            path
            title
            date
            author
            tags
            locale
        }
      }
    }
  }
}
```

now, the pagination works fine i can display the right amount on posts with a prev and next, and it all works!!!
BUT in the command line i get this error several times:
error
The GraphQL query from C:/xampp/htdocs/shtigsite2/src/pages/blog.js failed.

```
Errors:
  Cannot read property 'node' of undefined

  GraphQL request (6:3)
  5: ) {
  6:   allMarkdownRemark(filter: {frontmatter: {locale: {eq: $locale}}}, sort: {fields: [frontmatter___date], order: DESC}, limit: $limit, skip: $skip) {
       ^
  7:     totalCount

URL path:
  /blog/4
Context:
  {
    "limit": 3,
    "skip": 9,
    "totalPages": 1,
    "currentPage": 4,
    "locale": "he"
  }
Plugin:
  none
Query:
  query cXamppHtdocsShtigsite2SrcPagesBlogJs971501053(
    $locale: String
    $limit: Int
    $skip: Int
  ) {
    allMarkdownRemark(filter: {frontmatter: {locale: {eq: $locale}}}, sort: {fields: [frontmatter___date], order: DESC}, limit: $limit, skip: $skip) {
      totalCount
      edges {
        node {
          id
          frontmatter {
            path
            title
            date
            author
            tags
            locale
          }
        }
      }
    }
  }
```

i have tried to put the variables of $locale,$limit and $skip, one by one, and only with the skip this error appears.
by the way, when i test the query in the graphql interface, it does work without any errors.

what am i missing here?

### Environment (if relevant)
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.53 => 2.0.53
    gatsby-image: ^2.0.20 => 2.0.20
    gatsby-plugin-feed: ^2.0.11 => 2.0.11
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8
    gatsby-plugin-manifest: ^2.0.9 => 2.0.9
    gatsby-plugin-offline: ^2.0.16 => 2.0.16
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0
    gatsby-plugin-sharp: ^2.0.14 => 2.0.14
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.0.7
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: ^3.0.1 => 3.0.1
    gatsby-remark-responsive-iframe: ^2.0.7 => 2.0.7
    gatsby-source-filesystem: ^2.0.8 => 2.0.8
    gatsby-transformer-remark: ^2.1.12 => 2.1.12
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by derridHeidegger** [comment]
ok the issue was that instead of looping the posts i needed to loop only the number of pages: now the errors are gone and it is working, that means i can paginate the blog posts by each language.
`  Array.from({length: numPages})
  .forEach((_, i) => {
    createPage({
      path: i === 0 ? `${localizedPath}/blog` : `${localizedPath}/blog/${i+1}`,
      component: require.resolve('./src/pages/blog.js'),
      context: {
        limit: postsPerPage,
        skip: i * postsPerPage,
        totalPages: numPages,
        currentPage: i + 1,
        locale: lang
      },
    })
  })`

**Comment by jonniebigodes** [comment]
Glad you figured it out.
