### ISSUE TITLE
[gatsby-plugin-manifest] internationalization (i18n)

### ISSUE THREAD

**Issue by CanRau** [gatsbyjs/gatsby#10250]
I'm quite new to PWAs, manifests & add-to-homescreen stuff and I'm not 100% sure I get everything. I am not even sure where to discuss my thoughts/questions, a RFC seems to big for this, and I'm not into those chats like spectrum and discord, it's annoying for me to have to check them etc so I'm making this a question for now and see where it goes, hopefully that's okay for everyone else 🙏 

## Summary
Provide a way for pages to specify separate manifests for each language

## Relevant information
That would be one possible solution, maybe a bit verbose/repeating, though you could define your shared base options and then just extend them but it gives a lot of flexibility so people can define different icons, colors etc (proof that icon localization is a thing https://github.com/w3c/manifest/issues/676#issuecomment-442434811)
```
{
  resolve: `gatsby-plugin-manifest`,
  options: [
    {
      name: `Full name`,
      short_name: `Name`,
      start_url: `/en/?utm_source=a2hs`,
      background_color: `#fff`,
      theme_color: `red`,
      display: `standalone`,
      icon: `static/icon.png`,
      pattern: `^/en/.*$`,
    },
    {
      name: `Vollständiger Name`,
      short_name: `Name`,
      start_url: `/de/?utm_source=a2hs`,
      background_color: `#fff`,
      theme_color: `rebeccapurple`,
      display: `standalone`,
      icon: `static/icon_de.png`,
      pattern: `^/de/.*$`,
    },
  ],
},
```
I would suggest still allowing a single object in options to not break anything.

I run on a patched version I just threw in my local packages workspace https://github.com/GaiAma/gaiama.org/commit/ae194c204c8e34c85bec074ba4d6e353ce9eb981#diff-0cee23a635d1c08646f35342b6dee83f which doesn't seem to work properly right now, but it did work…

Another possibility might be to just specify multiple plugin declarations and "just" add a `pattern` property or similar like:
```
{
  resolve: `gatsby-plugin-manifest`,
  options: {
    name: `GaiAma`,
    short_name: `GaiAma`,
    start_url: `/en/?utm_source=a2hs`,
    background_color: `#fff`,
    theme_color: `#287482`,
    display: `standalone`,
    icon: `static/gaiama_pictogram.png`,
    pattern: `^/en/.*$`,
  },
},
{
  resolve: `gatsby-plugin-manifest`,
  options: {
    name: `GaiAma`,
    short_name: `GaiAma`,
    start_url: `/de/?utm_source=a2hs`,
    background_color: `#fff`,
    theme_color: `#287482`,
    display: `standalone`,
    icon: `static/gaiama_pictogram.png`,
    pattern: `^/de/.*$`,
  },
},
```
So the pattern would specify in gatsby-ssr which to run/include

I'm not sure if the manifests should be then save in the respective language directory all called `manifest.webmanifest` or put them all in `/` root and name them differently? 

Another question I have is, what about the manual trigger stuff and listening on `beforeinstallprompt` in chrome https://developers.google.com/web/fundamentals/app-install-banners/#trigger this plugin should probably support it sooner than later right?

Let me know what you think about all this, any suggestions/feedback are really appreciated 🙏 
I think I could implement the i18n stuff properly, if it gets accepted and we settled on an implementation as I don't want to keep my local copy up to date.. I might be able to do the trigger stuff, but that could probably enter another PR

**Comment by pieh** [comment]
The `pattern` would determine where we point `<link rel="manifest">`?

> I'm not sure if the manifests should be then save in the respective language directory all called `manifest.webmanifest` or put them all in `/` root and name them differently?

Easiest to implement is to put them all in `/` and add some suffixes

**Comment by CanRau** [comment]
> The `pattern` would determine where we point `<link rel="manifest">`?

Exactly 👍 I could name it `include` or maybe `pathPattern`/`pathnamePattern` so it's more clear it matches against the pathname?
And in general, is the design okay? Should I prepare a PR? Or should I wait for more comments?

**Comment by CanRau** [comment]
@pieh I understand the amount of issues being a lot of work, just trying to figure out if I should abandon this PR and keep my fork or if it's still interesting..

**Comment by LekoArts** [comment]
Did you see these articles? I'm not sure if your current solution is the best one and there is probably the need for more investigation:

https://developer.chrome.com/webstore/i18n
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization

**Comment by CanRau** [comment]
No I haven't @LekoArts thanks for bringing them up 🙏 
More in https://github.com/gatsbyjs/gatsby/pull/13471

**Comment by CanRau** [comment]
Thanks for reminding me gatsbot, I think this one can be closed as final discussion happens over at the PR https://github.com/gatsbyjs/gatsby/pull/13471
