### ISSUE TITLE
238MB! How can I decrease the size of node_modules?

### ISSUE THREAD

**Issue by FrankFang** [gatsbyjs/gatsby#10269]
```
gatsby new gatsby-site
cd gatsby-site
du -sh
> 238M	.
```

Can I disabled some features to decrease the size?

**Comment by KyleAMathews** [comment]
Not really. There is efforts like yarn pnp which promise to reduce the size of node_modules across projects https://medium.com/@thomasreggi/yarn-plugn-play-1c398bf3e417

**Comment by FrankFang** [comment]
@KyleAMathews  Why does a gatsby project needs so many dependencies? Is is possible to put the dependencies to global node_modules.

**Comment by KyleAMathews** [comment]
To make gatsby more awesome of course ;-)

Gatsby is complex software. There's efforts like pnp but this is a general npm/node problem that we're not working on so won't be working on this in the near future.
