### ISSUE TITLE
[gatsby-source-wordpress] Dynamic Query Doesn't Work After Upgrade

### ISSUE THREAD

**Issue by rotexhawk** [gatsbyjs/gatsby#10262]
I am using `gatsby-source-wordpress` with `createPaginatedPages`. First I am reading all the categories and then in my second query I pass the category id to the post query, to filter posts to that specific category. This used to work perfectly in 2.0 but after the update, the second query (dynamic query) doesn't work. I know I can query the category and pass the id to layout, but then I can't use the `createPaginatedPages plugin`. 

```
graphql(`
    {
        allWordpressCategory {
            edges {
                node {
                    id
               
                }
            }
        }
    }
`).then(result => {
    if (result.errors) {
        console.log(result.errors);
        reject(result.errors);
    }
    _.each(
        result.data.allWordpressCategory.edges,
        edge => {
            graphql(
                `
                    query CatPosts($id: String!) {
                        allWordpressPost(
                            filter: {
                                categories: {
                                    id: { eq: $id }
                                }
                            }
                        ) {
                            edges {
                                node {
                                    id
                                    title
                                    excerpt
                                    slug
                                    status
                                    date(
                                        formatString: "MMMM, DD YYYY"
                                    )
                                    featured_media {
                                        id
                                        source_url
                                        alt_text
                                    }
                                }
                            }
                        }
                    }
                `,
                { id: edge.node.id }
            ).then(posts => {
                if (
                    posts &&
                    posts.data &&
                    posts.data.allWordpressPost
                ) {
                    const pageTemplate = path.resolve(
                        './src/pages/archive.js'
                    );

                    createPaginatedPages({
                        edges:
                            posts.data.allWordpressPost
                                .edges,
                        createPage: createPage,
                        pageTemplate: pageTemplate,
                        pageLength: 10, // This is optional and defaults to 10 if not used
                        pathPrefix: edge.node.slug, // This is optional and defaults to an empty string if not used
                        context: edge.node, // This is optional and defaults to an empty object if not used
                        buildPath: (
                            index,
                            pathPrefix
                        ) =>
                            index > 1
                                ? `/${pathPrefix}/page/${index}/`
                                : pathPrefix,
                    });
                }
            });
        }
    );
```

### Environment

  System:
    OS: OS X El Capitan 10.11.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.0.8 - /bin/zsh
  Binaries:
    Node: 9.8.0 - ~/.nvm/versions/node/v9.8.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v9.8.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 62.0
    Safari: 10.0
  npmPackages:
    gatsby: ^2.0.61 => 2.0.61 
    gatsby-cli: ^2.4.6 => 2.4.6 
    gatsby-image: ^2.0.22 => 2.0.22 
    gatsby-paginate: ^1.0.16 => 1.0.16 
    gatsby-plugin-glamor: ^2.0.7 => 2.0.7 
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8 
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4 
    gatsby-plugin-guess-js: ^1.0.3 => 1.0.3 
    gatsby-plugin-manifest: ^2.0.11 => 2.0.11 
    gatsby-plugin-offline: ^2.0.18 => 2.0.18 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.4 
    gatsby-plugin-root-import: ^2.0.4 => 2.0.4 
    gatsby-plugin-sass: ^2.0.5 => 2.0.5 
    gatsby-plugin-sharp: ^2.0.14 => 2.0.14 
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4 
    gatsby-source-filesystem: ^2.0.10 => 2.0.10 
    gatsby-source-wordpress: ^3.0.17 => 3.0.17 
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9 
  npmGlobalPackages:
    gatsby-cli: 2.4.2

**Comment by rotexhawk** [comment]
After debugging this in __graphql I found out that the type of filter has changed. `categories` no longer accepts `id` but it requires `elemMatch`. Changing it to this fixed it. I am not sure if this is intentional or not?

```
allWordpressPost( filter: {  categories: {   elemMatch: {   id: { eq: $id }   }  }  }) { .....
```

**Comment by jgierer12** [comment]
> This used to work perfectly in 2.0 but after the update, ...

Can you elaborate on which packages you upgraded?

**Comment by rotexhawk** [comment]
I just tested this by updating only gatsby and the site crashed again. The same issue!

![screen shot 2018-12-04 at 11 48 52 am](https://user-images.githubusercontent.com/12015105/49458342-a2140980-f7ba-11e8-92e5-6c121bf8e6b3.png)


  System:
    OS: OS X El Capitan 10.11.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.0.8 - /bin/zsh
  Binaries:
    Node: 9.8.0 - ~/.nvm/versions/node/v9.8.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v9.8.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 62.0
    Safari: 10.0
  npmPackages:
    gatsby: ^2.0.61 => 2.0.61 
    gatsby-cli: ^2.4.3 => 2.4.3 
    gatsby-image: ^2.0.13 => 2.0.13 
    gatsby-paginate: ^1.0.16 => 1.0.16 
    gatsby-plugin-glamor: ^2.0.5 => 2.0.5 
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8 
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4 
    gatsby-plugin-guess-js: ^1.0.2 => 1.0.2 
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-root-import: ^2.0.4 => 2.0.4 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.6 => 2.0.6 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.0 
    gatsby-source-filesystem: ^2.0.5 => 2.0.5 
    gatsby-source-wordpress: ^3.0.1 => 3.0.1 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.2

**Comment by seanngpack** [comment]
@rotexhawk, I have the exact same issue after upgrading to 2.0.61. Replacing all my queries with elemMatch was really painful. Doesn't seem like it was a conscious decision to alter the query structure because now the wordpress-plugin tutorials are incorrect

**Comment by chmac** [comment]
Running `yarn upgrade` on the WordPress starter also hits this same issue. The query structure has changed in a patch release of a Gatsby package. Definitely strikes me as a breaking change which should have caused a major version bump somewhere.

**Comment by jonniebigodes** [comment]
@seanngpack and @chmac sorry for the hassle you both experienced with the upgrade. This was one of those situations that unfortunately slipped through the fingers of the team. You both and the rest of the users should have been notified that some changes were made. And from that expand the documentation accordingly to prevent situations like the ones you've been experiencing. Once again sorry for the inconvenience that it caused.

**Comment by chmac** [comment]
@jonniebigodes Is the current situation final? I was waiting to see if there would be a rollback patch release and then a major version bump or something.

**Comment by jonniebigodes** [comment]
@chmac This is one of those of those situations that i must defer to the development team.

**Comment by chmac** [comment]
I guess at this point we probably need to accept that a breaking change was introduced in a patch release and that's that...
