### ISSUE TITLE
Weird error on build

### ISSUE THREAD

**Issue by ArchieHicklin** [gatsbyjs/gatsby#1027]
Cloned one of the awesome example sites in the Gastby documentation (https://github.com/oliverbenns/oliverbenns.com) and was playing around with editing and transplanting things to learn to use Gatsby for a larger project.

Running `gatsby develop` works fine.

But  `npm run build` throws errors, and when deploying to Netlify the log is really bizarre:

```
3:36:05 PM: Build started
3:36:06 PM: Fetching cached dependencies
3:36:06 PM: Expected build cache - but failed to find it
3:36:06 PM: Failed to extract cache, continuing with build
3:36:06 PM: No cached dependencies found. Cloning fresh repo
3:36:06 PM: git clone git@github.com:ArchieHicklin/Portfolio
3:36:08 PM: git remote rm origin
3:36:08 PM: Preparing Git Reference refs/heads/master
3:36:09 PM: Running build command: gatsby build
3:36:10 PM: Downloading https://nodejs.org/dist/v6.3.0/node-v6.3.0-linux-x64.tar.xz...
3:36:10 PM: # 2.4%
3:36:10 PM: ######################################################################## 100.0%
3:36:10 PM: Computing checksum with sha256sum
3:36:10 PM: Checksums matched!
3:36:12 PM: Using version v6.3.0 of node
3:36:12 PM: Using /opt/buildhome/.rvm/gems/ruby-2.1.2
3:36:12 PM: Installing yarn at version 0.18.1
3:36:13 PM: Installing Yarn!
3:36:13 PM: > Downloading tarball...
3:36:13 PM: 
[1/2]: https://yarnpkg.com/downloads/0.18.1/yarn-v0.18.1.tar.gz --> /tmp/yarn.tar.gz.ojCrpQXhpf
3:36:13 PM: % Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
3:36:13 PM: 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
3:36:13 PM: 100 92 100 92 0 0 602 0 --:--:-- --:--:-- --:--:-- 605
3:36:13 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:01 --:--:-- 0
3:36:14 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:02 --:--:-- 0
3:36:15 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:03 --:--:-- 0
3:36:16 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:04 --:--:-- 0
3:36:17 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:05 --:--:-- 0
3:36:18 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:06 --:--:-- 0
3:36:19 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:06 --:--:-- 0
3:36:19 PM: 0 0 0 595 0 0 88 0 --:--:
3:36:19 PM: -- 0:00:06 --:--:-- 175
3:36:19 PM: 100 3537k 100 3537k 0 0 519k 0 0:00:06 0:00:06 --:--:-- 519k
3:36:19 PM: 
[2/2]: https://yarnpkg.com/downloads/0.1
3:36:19 PM: 8.1/yarn-v0.18.1.tar.gz.asc --> /tmp/yarn.tar.gz.ojCrpQXhpf.asc
3:36:19 PM: 100 96 100 96 0 0 776 0 --:--:-- --:--:-- --:--:-- 776
3:36:20 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:01 --:--:-- 0
3:36:21 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:02 --:--:-- 0
3:36:22 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:03 --:--:-- 0
3:36:23 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:04 --:--:-- 0
3:36:24 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:05 --:--:-- 0
3:36:25 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:06 --:--:-- 0
3:36:26 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:07 --:--:-- 0
3:36:27 PM: 0 0 0 0 0 0 0 0 --:--:-- 0:00:08 --:--:-- 0
3:36:27 PM: 0 0 0 600 0 0 73 0 --:--:-- 0:00:08 --:--:-- 147
3:36:27 PM: 100 832 100 832 0 0 100 0 0:00:08 0:00:08 --:--:-- 100
3:36:27 PM: > Verifying integrity...
3:36:27 PM: gpg: Signature made Sat 17 Dec 2016 12:30:28 PM UTC using RSA key ID FD2497F5
3:36:27 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
3:36:27 PM: gpg: WARNING: This key is not certified with a trusted signature!
gpg: There is no indication that the signature belongs to the owner.
Primary key fingerprint: 72EC F46A 56B4 AD39 C907 BBB7 1646 B01B 86E5 0310
Subkey fingerprint: 6A01 0C51 6600 6599 AA17 F081 46C2 130D FD24 97F5
3:36:27 PM: > GPG signature looks good
3:36:27 PM: > Extracting to ~/.yarn...
3:36:28 PM: > Adding to $PATH...
3:36:28 PM: > We've added the following to your /opt/buildhome/.profile
> If this isn't the profile of your current shell then please add the following to your correct profile:

export PATH="$HOME/.yarn/bin:$PATH"
3:36:28 PM: > Successfully installed Yarn 0.18.1! Please open another terminal where the `yarn` command will now be available.
3:36:28 PM: Installing NPM modules using Yarn version 0.18.1
3:36:29 PM: yarn install v0.18.1
3:36:29 PM: [1/4] Resolving packages...
3:36:30 PM: [2/4] Fetching packages...
3:36:48 PM: warning fsevents@1.0.14: The platform "linux" is incompatible with this module.
3:36:48 PM: info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
3:36:48 PM: [3/4] Linking dependencies...
3:36:48 PM: warning Unmet peer dependency "react@>= 0.14.0".
3:36:48 PM: warning Incorrect peer dependency "eslint-plugin-import@^1.16.0".
3:36:48 PM: warning Incorrect peer dependency "eslint-plugin-import@^1.16.0".
3:37:04 PM: [4/4] Building fresh packages...
3:37:06 PM: Done in 37.02s.
3:37:06 PM: NPM modules installed using Yarn
3:37:07 PM: Generating CSS
3:38:52 PM: Generating Static HTML
3:40:37 PM: Failed at generating HTML
3:40:37 PM: 
/opt/build/repo/node_modules/gatsby/dist/bin/cli.js:52
throw err;
^
```
```
Error: TypeError: Cannot read property 'className' of undefined
at ProjectPage (render-page.js:33170:75)
at ReactCompositeComponentMixin._constructComponentWithoutOwner (render-page.js:13916:15)
at ReactCompositeComponentMixin._constructComponent (render-page.js:13892:20)
at ReactCompositeComponentMixin.mountComponent (render-page.js:13795:22)
at Object.ReactReconciler.mountComponent (render-page.js:6833:36)
at ReactCompositeComponentMixin.performInitialMount (render-page.js:13978:35)
at ReactCompositeComponentMixin.mountComponent (render-page.js:13865:22)
at Object.ReactReconciler.mountComponent (render-page.js:6833:36)
at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (render-page.js:13006:45)
at ReactDOMComponent.Mixin._createContentMarkup (render-page.js:9982:33)
3:40:37 PM: Cached NPM modules
3:40:37 PM: Saved Yarn cache
3:40:38 PM: Build complete: exit code: 1
3:40:38 PM: Cleaning up docker container
3:40:38 PM: Error running command: Build script returned non-zero exit code: 1
3:40:38 PM: An error occurred while building the site, skipping the deploy and cache refresh.
3:40:38 PM: Build script returned non-zero exit code: 1
3:40:40 PM: Finished processing build request in 4m34.065799101s
```

The edited version is public here: https://github.com/ArchieHicklin/Portfolio

I've tried uninstalling and reinstalling gatsby globally but to no avail. Updating or even running npm install seems to break things.

Would appreciate anyone who's run into similar errors or can offer any advice!

🙏

**Comment by KyleAMathews** [comment]
Can you reproduce this locally? If so, open the "render-page.js" file in
the public directory to the line number in the stack trace.

**Comment by ArchieHicklin** [comment]
@KyleAMathews Able to reproduce locally but the errors seem to refer to pretty unrelated lines 😵 I just can't see the relationship of even where to start to tackle this..

Gets rendered in /public so maybe I should exclude in .gitignore?

https://github.com/ArchieHicklin/Portfolio/blob/master/public/render-page.js

**at ProjectPage (render-page.js:33170:75)**

`function isObject(value) {
	  // Avoid a V8 JIT bug in Chrome 19-20.
	  // See https://code.google.com/p/v8/issues/detail?id=2291 for more details.
	  var type = typeof value;
	  return !!value && (type == 'object' || type == 'function');
	}`

**at ReactCompositeComponentMixin._constructComponentWithoutOwner (render-page.js:13916:15)**

`	  ReactInstrumentation.debugTool.onBeginLifeCycleTimer(debugID, timerType);
	  try {
	    return fn();
	  } finally {
	    ReactInstrumentation.debugTool.onEndLifeCycleTimer(debugID, timerType);
	  }
	}`



**at ReactCompositeComponentMixin._constructComponent (render-page.js:13892:20)**

`	function warnIfInvalidElement(Component, element) {
	  if (false) {
	    process.env.NODE_ENV !== 'production' ? warning(element === null || element === false || React.isValidElement(element), '%s(...): A valid React element (or null) must be returned. You may have ' + 'returned undefined, an array or some other invalid object.', Component.displayName || Component.name || 'Component') : void 0;
	    process.env.NODE_ENV !== 'production' ? warning(!Component.childContextTypes, '%s(...): childContextTypes cannot be defined on a functional component.', Component.displayName || Component.name || 'Component') : void 0;
	  }
	}`


**at ReactCompositeComponentMixin.mountComponent (render-page.js:13795:22)**
`	      if (!instance.getHostNode) {
	        instance.getHostNode = instance.getNativeNode;
	      }`


**at Object.ReactReconciler.mountComponent (render-page.js:6833:36)**

`ReactReconciler.performUpdateIfNecessary(component, transaction.reconcileTransaction, updateBatchNumber);`


**at ReactCompositeComponentMixin.performInitialMount (render-page.js:13978:35)**

`this._pendingStateQueue = null;`


**at ReactCompositeComponentMixin.mountComponent (render-page.js:13865:22)**

`	if (false) {
	  var checkReactTypeSpec = require('./checkReactTypeSpec');
	}`

**at Object.ReactReconciler.mountComponent (render-page.js:6833:36)**
`ReactReconciler.performUpdateIfNecessary(component, transaction.reconcileTransaction, updateBatchNumber);`


**at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (render-page.js:13006:45)**

`var _prodInvariant = __webpack_require__(38);`


**at ReactDOMComponent.Mixin._createContentMarkup (render-page.js:9982:33)**

`ReactDOMComponent.displayName = 'ReactDOMComponent';`

**Comment by KyleAMathews** [comment]
You're looking for "className"

**Comment by ArchieHicklin** [comment]
@KyleAMathews could it be linked to this issue do you think?

https://github.com/gatsbyjs/gatsby/issues/499

As I do get this for all css when running in development:

`assets/css/typography.css
undefined [undefined]`

![image](https://cloud.githubusercontent.com/assets/10767740/26369346/5627ab3a-3fec-11e7-9451-8426b3f2cc76.png)

**Comment by KyleAMathews** [comment]
I was never sure what #499 was about. Did you find the code in render-pages.js with "className"?

**Comment by ArchieHicklin** [comment]
@KyleAMathews Bizarre! Thanks so much for your advice so far. 145 instances of className in render.js - none of which correspond with the stack trace or point to errors 😓

Although there is a `null` in most of the rendering associated with className. Not sure if this is normal.

Such frustration 🔥

ex:

`   { className: 'markdown' },
	    _react2.default.createElement(
	      'h1',
	      null,
	      post.title
	    ),
	    _react2.default.createElement('div', { dangerouslySetInnerHTML: { __html: post.body } })
	  );
	};`

**Comment by dileep8014** [comment]
@ArchieHicklin - its very small issue i resolved it its nothing related to gatsby

**Comment by ArchieHicklin** [comment]
@KyleAMathews Issue was completely unrelated to anything above - the wrong slug was defined in a JSON file.
