### ISSUE TITLE
Using the GA/GTM Data Layer with Gatsby

### ISSUE THREAD

**Issue by jeremylynch** [gatsbyjs/gatsby#10271]
What is the best way to use the [GTM Data layer](https://developers.google.com/tag-manager/devguide) in Gatsby?

Importantly, the `Data Layer` needs to be defined (with dynamic variables) BEFORE tracking data is sent to Google Analytics. The standard implementation of GA in Gatsby is by sending tracking data after `onRouteUpdate`:

```js
exports.onRouteUpdate = ({ location }) => {
  // Track pageview with google analytics
  window.ga(`send`, `pageview`)
}
```

How can I define my `Data Layer` with dynamic variables before tracking data is sent to GA?

**Comment by horacioh** [comment]
have you checked [this plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-google-tagmanager/) ?

here you have a config file you can add when boostrapping. also, what type of dynamic variables you need to setup?

also there should be some examples of how other gatsby websites are using this plugin. How I used it in the past i had no use case where I needed to add a dynamic config before sending data to it. 

hope these helps!

**Comment by jeremylynch** [comment]
Each different page has dynamic variables that are unique to that page. Essentially, I need to take those dynamic variables and add them to the Data Layer before the page view data is sent to GA. 

In other systems where the entire page reloads this is easy to achieve, just by changing the Data Layer in a script tag in the head on each different page. Not sure how to achieve this in Gatsby

**Comment by horacioh** [comment]
what you can do is:
- disable the automatic pageView event from the GTM backoffice
- make a pageQuery on everypage to get the dynamic information you need
- when you have that info, fire a custom event to GTM with that information
- then setup a custom trigger in GTM to send the proper pageView to GA from GTM with the data provided to the DataLayer.

let me check if there's documentation from GTM that explains these process with examples :)

**Comment by shansmith01** [comment]
In case it's useful. Adding i eCommerce tracking is pretty straight forward. Let's say you are using stripe payments. When a successful response comes back you would fire something like this:

```
dataLayer.push({
                    event: 'Purchase',
                    ecommerce: {
                      purchase: {
                        actionField: {
                          id: json.charge.id, // Transaction ID. Required for purchases and refunds.
                          revenue: revnueWithNosymbol // Total transaction value (incl. tax and shipping)
                        },
                        products: [
                          {
                            // List of productFieldObjects.
                            name: description, // Name or ID is required.
                            price: revnueWithNosymbol,
                            quantity: 1, // Coule make dynamic
                            coupon: '' // Optional fields may be omitted or set to empty string.
                          }
                        ]
                      }
                    }
```

**Comment by engti** [comment]
@shansmith01 I know its 2 years later, but there is very little documentation on updating the datalayer from Gatsby.

I know it's a tall ask, but would you be able to point me at how to get the above working.  I am new to webdev, and am struggling at making your above code work.

Thanks.
