### ISSUE TITLE
V2 build longer compared to v1

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#10279]
Upgraded our site to Gatsby v2 a few months back and noticed the build time is significantly slower. Went from 
`success run graphql queries — 44.787 s` to `success run graphql queries — 238.530 s — 198/198 0.83 queries/second`

Did not change anything but migrating from v1 to v2 using the guide.

Is this a know issue?

**Comment by sidharthachatterjee** [comment]
Hello @b0gd4n 

> Reduced build times by up to 75%
> Shrunk JavaScript client runtime by 31%
> Upgraded Gatsby’s core dependencies to their latest versions: webpack 4, Babel 7, React 16.5

You should be seeing reduced build times as far as I know. 

Can you share a minimal reproduction of this with me so I can help debug this?
