### ISSUE TITLE
[gatsby-source-drupal] [GraphQL]  Views reference module fields (seen in jsonapi) do not show up in GraphQL

### ISSUE THREAD

**Issue by phonoman** [gatsbyjs/gatsby#10281]
## Description

We're using paragraph page setup on our site. We're also using views reference module and field in order to display view blocks in these pages. The current issue is - we're not able to query the views_reference field as it seems non-existant in GraphQL. We can see the views_reference field with no issue under our _sourceSite/jsonapi/paragraph/view_block_ .
Sidenote: I've messaged M. Piechowiak privately about access to the source data environment. 

### Steps to reproduce

Install paragraphs, views_reference module for Drupal 8
Install views_reference in a paragraph
Create a node that uses a views_reference field and displays a block

### Expected result

We should be seeing the views_reference field and it's information when querying in GraphQL.

### Actual result

views_reference is not seen in GraphQL at all. Only in /jsonapi/paragraph/view_block listing. 

### Environment
  npmPackages:
    gatsby: ^2.0.54 => 2.0.54 
    gatsby-cli: ^2.4.6 => 2.4.6 
    gatsby-image: ^2.0.20 => 2.0.20 
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.10 
    gatsby-plugin-offline: ^2.0.13 => 2.0.17 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2 
    gatsby-plugin-sharp: ^2.0.12 => 2.0.13 
    gatsby-plugin-styled-components: ^3.0.3 => 3.0.3 
    gatsby-plugin-typography: ^2.2.1 => 2.2.1 
    gatsby-source-drupal: ^3.0.9 => 3.0.10 
    gatsby-source-filesystem: ^2.0.8 => 2.0.8 
    gatsby-transformer-remark: ^2.1.11 => 2.1.12 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.6
    gatsby: 2.0.52

**Comment by phonoman** [comment]
Not stale. Ignored.

**Comment by pieh** [comment]
Sorry @phonoman, this totally slipped my mind.

I was doing some checking and `sourceSite/jsonapi/paragraph/view_block` api response has this data:
```
{
  "field_views_reference": {
    "data": {
      "type": "view--view",
      "id": "<some_id>",
      "meta": {
        "display_id": "block_case_studies",
        "data": "a:6:{s:8:\u0022argument\u0022;N;s:5:\u0022limit\u0022;s:0:\u0022\u0022;s:6:\u0022offset\u0022;N;s:5:\u0022pager\u0022;N;s:5:\u0022title\u0022;N;s:14:\u0022hide_more_link\u0022;i:0;}"
      }
    }
  }
}
```
but referenced `view--view` object isn't actually returned by corresponding endpoint - `sourceSite/jsonapi/view/view` returns `data: []` so we are unable to make a link to not existing entity.

There is this extra `meta` object - but I'm not sure what to do with this and if this is data You actually want to have access to? Or the data that is missing from endpoint for some reason

**Comment by phonoman** [comment]
Good to see you back! :) 
Yes, access to the `meta.display_id` would at least give information of which display is supposed to be shown in this paragraph - the actual view could be then guessed/translated from our side at `.onCreateNode()`

**Comment by pieh** [comment]
> Yes, access to the `viewsreferenceModuleField.meta.display_id` would at least give information of which display is supposed to be shown in this paragraph

I would need to take a look at rest api spec - in the data snippet I pasted `meta.data` is php serialized object, but I'm not sure if this is always the case or this is specific to `field_views_reference` or drupal module that provide that. Probably would leave it as-is and don't try to deserialize it

Even with that I'm not sure how this should work - should I create some object with `meta` field, so queries would look like:
```graphql
  allParagraphViewBlock {
    edges {
      node {
        field_paragraph_views {
          meta {
            display_id
            data
          }
        }
      }
    }
  }
}
```

**Comment by phonoman** [comment]
Yeah, `meta.data` isn't as vital as `display_id` and it definitely can stay the same. 
The posted query is totally OK for us as it's same as jsonapi provided structure.

**Comment by pieh** [comment]
A bit related for relationship `meta` - https://github.com/gatsbyjs/gatsby/issues/10339

**Comment by pieh** [comment]
I was reading some drupal jsonapi spec, and approach I was thinking about (create object of linked object doesn't exist) + enrich object with `meta` wouldn't follow the spec - as in those are `meta` fields on relationship and not really on linked object, so those `meta` fields can be different in another relationship linking to same object.

Now I'm thinking if there shouldn't just be extra field - like:
```graphql
{
  allParagraphViewBlock {
    edges {
      node {
        field_paragraph_views {
          some_fields_once_missing_data_in_endpoint_is_figured_out
        }
        field_paragraph_views_meta {
          display_id
          data
        }
      }
    }
  }
}
```

**Comment by phonoman** [comment]
Ahh, yeah, I see that jsonapi for `field_views_reference` is missing the `links` for that specific view, right? 
Because in jsonapi/view--view there is a view with that same id.. It's only not specifically referenced at `field_views_reference` - thus the info for that view is missing for you guys, am I right?

**Comment by pieh** [comment]
@phonoman you are right. We don't currently pull individual endpoints, we try to use listing endpoints (to limit amount of requests).

In this instance it seems like individual endpoint contains just same metadata as `meta` object on relationship tho. So instead of fetching those individual endpoints it seems (at least to me) that adding `meta` from relationship would be cheaper and would solve this issue.

It still seems weird that listing `sourceSite/jsonapi/view/view` returns date being empty array - fixing that would solve the issue without code changes to the gatsby-source-drupoal.

**Comment by pieh** [comment]
ohh, the `/view/view` endpoint has meta with:
```
 "meta": {
    "omitted": {
      "detail": "Some resources have been omitted because of insufficient authorization.",
```
So maybe you could look into this?

**Comment by phonoman** [comment]
Ahh, I totally missed your second response! I dug into it and the only way to share information of `/view/view` is by giving the anon users this
```
Administer views
Warning: Give to trusted roles only; this permission has security implications.
```
While that will allow to look into `/view/view/` AND let `field_views_reference` through - now anons on Drupal will be able to edit views.. 
Also it doesn't give us `field_views_reference.meta` data which had the simplified, essential data (which display is used). 

The only way of getting the used display now (when sharing security implicating permission with anons) would be by adding every single display of all possible views in graphQL (they all have their own key when querying - `field_views_reference.display{displayFromAView, displayFromAnotherView}` and they return either `null` or the displays name as string [so if this paragraph has `field_views_reference` set to show `displayFromAView` from AView - it returns `"displayFromAView"`])

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v4 and updated related packages (gatsby-source-drupal) were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

[reproduction]: https://gatsby.dev/reproduction
