### ISSUE TITLE
Starter library - github stars confusion

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#10285]
## Description

The yellow stars in the starter library confused some users in interviews. They thought they were rating stars (as in Amazon stars) instead of github stars. 

### Steps to reproduce

When people arrive at /starters/, many of them glance at the yellow stars and think they are rating stars when they are actually supposed to represent github stars.

### Expected result

When people arrive on the /starters/ page, they want to be able to choose a high quality starter. We need to make sure the information about each starters helps people know which one they want to try.

### Actual result

When people arrive at /starters/, many of them glance at the yellow stars and think "why do all of these starters only have a one star rating?"

### Environment

Browser window

## Suggested solution
We could make the stars black so they mimic the github look and feel for stars. We could also mimic the design more fully from GitHub:

<img width="154" alt="screen shot 2018-12-04 at 11 18 36 am" src="https://user-images.githubusercontent.com/32467162/49467094-7bec6a80-f7b6-11e8-88f6-1f778a755853.png">

**Comment by LekoArts** [comment]
I'm really surprised that people actually think that. On Amazon you have a scale from 1-5 that immediately can be seen:

![image](https://user-images.githubusercontent.com/16143594/49468731-060fef80-f806-11e8-8f88-b071ab5a82d3.png)

The Gatsby site doesn't have such a scale, and while there are starters with 1 star there are also others with 688. What scale would that be?! 😆 

If changes are necessary, I could quickly incorporate them here: https://github.com/gatsbyjs/gatsby/pull/10258

**Comment by amberleyromo** [comment]
@LekoArts that would be great. I think the easiest thing to do here would be to set it to the same dark gray as the surrounding text. As Shannon suggested, perhaps that will more resemble GitHub, and not being a "yellow star" will take away the rating impression.

**Comment by LekoArts** [comment]
Dark:

![image](https://user-images.githubusercontent.com/16143594/49469643-59833d00-f808-11e8-9753-20dfb85575a3.png)

Same Color:

![image](https://user-images.githubusercontent.com/16143594/49469793-b54dc600-f808-11e8-81cc-2b8b7f6fe910.png)

**Comment by amberleyromo** [comment]
@LekoArts asking for preferences? personally i like it the same color, rather than darker (second screenshot).

**Comment by LekoArts** [comment]
I wasn't sure what you meant exactly so I did both :whynotboth:
I second the second one (duh)

**Comment by shannonbux** [comment]
Yeah, same color looks fine to me!

I think the confusion just comes from the automatic impression people get
from yellow stars, even though once they look at it closer, they realize
the stars are not like Amazon :)

**Comment by amberleyromo** [comment]
Closing with #10258.

**Comment by LekoArts** [comment]
https://github.com/gatsbyjs/gatsby/pull/10258 was merged

**Comment by shannonbux** [comment]
Wohoo! Thanks @lekoarts!
