### ISSUE TITLE
gatsby-plugin-feed ignores custom_namespaces

### ISSUE THREAD

**Issue by vojtechruz** [gatsbyjs/gatsby#10308]
I have the following plugin config, which uses gatsby-plugin-feed:
https://github.com/vojtechruz/vojtechruzicka-blog/blob/master/gatsby-config.js

I am using some custom elements there which gatsby properly recognizes:

```
custom_elements: [
    {"content:encoded": edge.node.html},
    {"webfeeds:logo": site.siteMetadata.siteUrl+"/favicon.svg"},
    {"webfeeds:icon": site.siteMetadata.siteUrl+"/favicon.svg"},
    {"webfeeds:accentColor": "007acc"},
    {"webfeeds:analytics": "UA-76533683-1"},
    {"webfeeds:cover":
        {_attr: {
            image: site.siteMetadata.siteUrl + edge.node.frontmatter.featuredImage.childImageSharp.fluid.originalImg
            }},
        }
],
```

But gatsby does not include custom namespace required by these elements:

```
custom_namespaces: {
    "webfeeds": "http://webfeeds.org/rss/1.0"
},
```

The resulting rss feed can be found here:
https://www.vojtechruzicka.com/feed/

But it does not contain my custom namespace:

```
<rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/"
     xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
```

**Comment by vojtechruz** [comment]
It looks like there is configuration per feed item and per whole RSS instance. namespaces need to be for the whole instance. Cant figure out how to pass these options to the plugin though.

**Comment by bmingles** [comment]
Looking at the plugin source, you should be able to do this via a `setup` function. I copied the default `setup` from here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-feed/src/internals.js and added a `custom_namespaces` property.

    {
        resolve: 'gatsby-plugin-feed',
        options: {
            query: ...,

            // mostly copied from default in gatsby-plugin-feed source code
            // but adding a custom namespace
            setup: ({
                query: {
                    site: { siteMetadata },
                    ...rest
                },
            }) => {
                return {
                    ...siteMetadata,
                    ...rest,
                    custom_namespaces: {
                       "webfeeds": "http://webfeeds.org/rss/1.0"
                    },
                }
            },

            feeds: [
                ...
                ],
        },
    },

**Comment by vojtechruz** [comment]
You are a lifesaver, thanks a lot :)
