### ISSUE TITLE
[gatsby-source-wordpress] How to center content?

### ISSUE THREAD

**Issue by seanngpack** [gatsbyjs/gatsby#10318]
Hi, I have tried looking everywhere for a solution but cannot find one. So I am having trouble in Gatsby centering content pulled from Wordpress. I want to center the images pulled from Wordpress, but they end up left-aligned on my site. On the Wordpress side, I have tried setting the images as right and centered aligned but that makes no difference.

<img width="510" alt="screen shot 2018-12-05 at 10 56 21 pm" src="https://user-images.githubusercontent.com/35155526/49566883-0630ed80-f8e1-11e8-81f7-e04a21ea9277.png">

What can I do to remedy this?

Thanks!
Sean

**Comment by seanngpack** [comment]
I have a temporary fix: From the Wordpress side, set the 'width' and 'height' attributes to 100%. Disadvantage is I have to pre-crop the images to get them to aspect ratio I want. Also the images will take the full width of my container.

**Comment by jonniebigodes** [comment]
@seanngpack based on the information at hand i have to ask, have you looked at [this](https://www.gatsbyjs.org/docs/image-tutorial/) ?
