### ISSUE TITLE
cannot connect to production GraphQL API

### ISSUE THREAD

**Issue by mamartins** [gatsbyjs/gatsby#10327]
## Description

I have a gatsby app hapilly connecting to a Strapi API via gatsby-source-graphql plugin running in development mode. As soon as I change the api to production and I want to generate a `gatsby build` I get this error:
` Error: Response not successful: Received status code 400 `

My suspect here is that the gatsby plugin is trying to build the schema from the API and the API has it turned off, since it's running in production, which makes completely sense... Isn't possible to disable it?

### Expected result

What should happen?
It should be able to build the pages
### Actual result

` Error: Response not successful: Received status code 400 `

### Environment
```   System:
    OS: macOS 10.14.1
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.4.1 - ~/.nvm/versions/node/v10.4.1/bin/node
    Yarn: yarn install v0.24.6
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 8.02s. - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.4.1/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Safari: 12.0.1
  npmPackages:
    gatsby: next => 2.0.0-rc.28
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8
    gatsby-plugin-mailchimp: https://github.com/benjaminhoffman/gatsby-plugin-mailchimp.git#gatsby-v2 => 3.3.0
    gatsby-plugin-manifest: next => 2.0.2-rc.1
    gatsby-plugin-offline: next => 2.0.0-rc.9
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1
    gatsby-plugin-resolve-src: next => 2.0.0-beta.1
    gatsby-plugin-styled-components: next => 3.0.0-rc.5
    gatsby-source-filesystem: next => 2.0.1-rc.6
    gatsby-source-graphql: next => 2.0.0-rc.6
    gatsby-transformer-json: next => 2.1.1-rc.6
  npmGlobalPackages:
    gatsby-cli: 2.4.4

**Comment by jonniebigodes** [comment]
@mamartins try and update gatsby, as i'm seeing here in the output you provided that the dependencies are quite a bit outdated. Also as per the plugin docs, can you try the following [approach](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-graphql#schema-definitions) and see if helps in resolving your issue?

**Comment by mamartins** [comment]
> @mamartins try and update gatsby, as i'm seeing here in the output you provided that the dependencies are quite a bit outdated. Also as per the plugin docs, can you try the following [approach](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-graphql#schema-definitions) and see if helps in resolving your issue?

I'll try to update Gatsby and see. The suggested approach isn't very feasible as I would like to avoid having to update a json on frontend every time I change the API...

**Comment by mamartins** [comment]
Updated Gatsby to latest version, and it's dependencies, and, as I suspected, I still have the same error

**Comment by DSchau** [comment]
@mamartins getting the low hanging fruit out of the way first, then we can debug further.

1. Have you validated that the production API doesn't require (different) authentication?
1. We use [`introspectSchema`](https://www.apollographql.com/docs/graphql-tools/remote-schemas.html) from `graphql-tools` to stitch in the remote schema. Have you validated that introspection is enabled in the remote schema?
  - I've seen this disabled in production using `apollo-server` so that could be the issue

Thanks and sorry for the issue!

**Comment by mamartins** [comment]
> @mamartins getting the low hanging fruit out of the way first, then we can debug further.
> 
> 1. Have you validated that the production API doesn't require (different) authentication?
> 2. We use [`introspectSchema`](https://www.apollographql.com/docs/graphql-tools/remote-schemas.html) from `graphql-tools` to stitch in the remote schema. Have you validated that introspection is enabled in the remote schema?
>    
>    * I've seen this disabled in production--by default--using [`apollo-server`](https://www.apollographql.com/docs/apollo-server/api/apollo-server.html) so that could be the issue
>    * If it's not enabled, you may need to use an approach like @jonniebigodes outlined
> 
> Thanks and sorry for the issue!

Hey @DSchau,
1. Production API do not need any further validation as I can query it 
2. That was what I suspected it was being done, the introspectSchema is disabled when running in Production. I'll see if Strapi was a way to turn it on without having to turn on the playground. What I was trying to to was trying to disable this on Gatsby side, since Gatsby should happily build without having to know the remote schema... :)

**Comment by jonniebigodes** [comment]
@mamartins without further knowledge of the strapi version you're using, but i did some digging and found out this [page](https://strapi.io/documentation/3.x.x/guides/graphql.html#usage), is this something that might help you?

**Comment by mamartins** [comment]
Not really as I cannot pass more options to Apollo than the ones that that doc has. But I've already fixed the problem updating their code and allowing custom parameters on that file. 
It was what @DSchau suspected, `introspectSchema` was turned off by default.

Thank you very much @jonniebigodes and @DSchau

**Comment by DSchau** [comment]
Sounds like an answer to me :)

Thanks for confirming, and thanks for using Gatsby 💜

Please re-open if we can help further!
