### ISSUE TITLE
Is it possible to filter in GrahpQL on multiple fields using $and?

### ISSUE THREAD

**Issue by holyjak** [gatsbyjs/gatsby#10320]
Is it possible to filter on multiple fields in GraphQL? According to [the docs, Gatsby uses Sift](https://www.gatsbyjs.org/docs/graphql-reference/#filter) which [supports the `$and` operator](https://docs.mongodb.com/manual/reference/operator/query/and/#op._S_and) (`{ $and: [ { <expression1> }, { <expression2> } , ... ] }`)

Thank you!

**Comment by holyjak** [comment]
OK, I see it is possible with a comma:

```js
filter: { contentType: { in: ["post", "page"] }, draft: { eq: false } }
```
this should be documented somewhere :)

**Comment by holyjak** [comment]
Opened a PR to improve the docs: #10321

**Comment by pavolhudran** [comment]
Hi, @holyjak but this example is for $in (array value must be $in the given query) not $and (ability to use an array of expressions. All expressions must test true). Do you know how in Gatsby GraphQl use $and. I searched many examples, but none of them is solving this problem. I found same problem, what I try to solve, but without answer:
https://forum.ghost.org/t/gatsby-graphql-filtering-on-multiple-tags-value/6494
