### ISSUE TITLE
[gatsby-plugin-netlify-cms] webpack and global node modules

### ISSUE THREAD

**Issue by buz-zard** [gatsbyjs/gatsby#10326]
## Description

I'm doing some MDX transformations with standalone babel and if imported modules have any references to node global modules, the webpack transpilation fails on CMS build.

Adding to `gastby-node.js` the following:

```js
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    node: { fs: 'empty' },
  });
};
```

Has no effect, as I understand the CMS has separate webpack config, that I can't override.

FYI. With `node: { fs: 'empty' },`  the `import 'babel-plugin-pluck-imports';` does not break normal (non CMS) pages.

### Steps to reproduce

In cms initialization file:

```js
import CMS, { init } from 'netlify-cms';
import 'babel-plugin-pluck-imports';

...
```

### Expected result

The CMS should transpile.

### Actual result

Webpack transpilation fails with error:

```bash
This dependency was not found:

* fs in ./node_modules/convert-source-map/index.js

To install it, you can run: npm install --save fs
```

### Environment

```sh

  System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 62.0.3
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.55 => 2.0.55 
    gatsby-mdx: ^0.2.0 => 0.2.0 
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4 
    gatsby-plugin-netlify-cms: ^3.0.8 => 3.0.8 
    gatsby-plugin-no-sourcemaps: ^2.0.1 => 2.0.1 
    gatsby-plugin-postcss: ^2.0.1 => 2.0.1 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2 
    gatsby-plugin-sitemap: ^2.0.2 => 2.0.2 
    gatsby-source-filesystem: ^2.0.9 => 2.0.9 
    gatsby-transformer-json: ^2.1.6 => 2.1.6 
  npmGlobalPackages:
    gatsby-cli: 2.4.6
```

**Comment by buz-zard** [comment]
Not stale

**Comment by darrelbelvin** [comment]
Adding this to \node_modules\gatsby-plugin-page-creator\gatsby-node.js worked for me.
Solution found at: [stackoverflow issue](https://stackoverflow.com/questions/47033447/gatsbyjs-cannot-find-module-fs-webpack-config-issue/53679959#53679959)

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    node: { fs: 'empty' },
  })
}

**Comment by Knaackee** [comment]
@karolis-sh I have the same issue. Does it work for you now?

**Comment by karolis-sh** [comment]
@Knaackee nope, the issue is still present.

I'm just waiting for mdx runtime update https://github.com/mdx-js/mdx/issues/704 :|

**Comment by Knaackee** [comment]
Thanks @karolis-sh for pointing out that mdx-js/runtime is the problem.

**Comment by hhimanshu** [comment]
Are there any workarounds for this issue?

**Comment by l3aconator** [comment]
@hhimanshu @karolis-sh 
You need to set node: { fs: 'empty' } in gatsby-confg.js. See here: 

https://github.com/mdx-js/mdx/issues/913
https://github.com/webpack-contrib/css-loader/issues/447#issuecomment-285600014

There was a recent version of netlify CMS that allows you to edit the config for the plugin itself. Here was my workaround:

```
{
      resolve: `gatsby-plugin-netlify-cms`,
      options: {
        modulePath: `${__dirname}/src/cms/cms.js`, // for custom preview in the Netlify CMS
        customizeWebpackConfig: (config) => (config.node.fs = 'empty'),
      },
    }
```
