### ISSUE TITLE
gatsby build failed after it was installed globally.

### ISSUE THREAD

**Issue by paul-cheung** [gatsbyjs/gatsby#10323]
i am using gatsby to build my project. Actually, i am trying to replace `gulp build` with `gatsby build`.

after gatsby was installed globally, i run `gatsby build` under my project directory, but error occurs as following which i do not know what actually happened.

![gatsbybuildfailed](https://user-images.githubusercontent.com/4626647/49588693-663b9880-f9a2-11e8-9aec-795b60d293e4.png)

any help?

**Comment by m-allanson** [comment]
Hey @paul-cheung it looks like your project isn't a Gatsby project? While `gulp` can be configured to work however your project is structured, `gatsby build` expects your project to follow a particular structure. 

Does `gatsby build` work with the following commands?

```
gatsby new my-site
cd my-site
gatsby build
```

Check out the _Getting Started_ section of the docs for more info on getting up and running with Gatsby.
