### ISSUE TITLE
Document ENABLE_GATSBY_REFRESH_ENDPOINT

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#10328]
## Summary

Setting an env var `ENABLE_GATSBY_REFRESH_ENDPOINT=true` while running `gatsby develop` will configure the develop server to re-source data when it receives a POST request to `/__refresh`.

This is a really useful feature when working with content while developing your site. The only documentation for this at the moment lives in PR and issue comments. This information should live in the docs of gatsbyjs.org.

### Basic example

Useful info available from:

- https://www.youtube.com/watch?v=8uvnAbMMVhU
- https://github.com/gatsbyjs/gatsby/pull/3054#issuecomment-352858732

Implementation: https://github.com/gatsbyjs/gatsby/blob/2f1b4879b8676e5c4a0d9df791db31bf8a7cb85d/packages/gatsby/src/commands/develop.js#L117-L128

Possibly in other issues / PRs in this repo.

### Motivation

This feature is too useful to remain undocumented 😄

**Comment by RichardBronosky** [comment]
This ticket and https://github.com/gatsbyjs/gatsby/pull/10366/commits and https://github.com/gatsbyjs/gatsby/projects/2 are still the top Google hits. Can we please add links to the real documentation to this ticket and any others discussing it? I still can't find it.

**Comment by drake-smith** [comment]
I understand how this refresh token is working and have tried it out on my local machine, and using localhost. However, I wonder how this can be implemented into a preview system for a non-developer, like a client that needs to preview content before publishing. Especially on Contentful, to set up the POST webhook, I need a non-localhost URL. I could use ngrok, but again, that only works in a limited scope, and wouldn't be a permanent and publicly-accessible URL for others to use.

**Comment by RichardBronosky** [comment]
@drake-smith  You can pass `--host=0.0.0.0` to develop to get it to listen on non-local interfaces.

**Comment by Charlesdoiron** [comment]
Hi @drake-smith i really need the same online preview for my gatsby contentfull website.
Do you find something ?

thanks a lot !
