### ISSUE TITLE
How to pass an environment variable to your build

### ISSUE THREAD

**Issue by 0x80** [gatsbyjs/gatsby#1033]
I would like to pass an environment variable into my build. Normally I would use the `webpack.DefinePlugin` for that. However this plugin is already used of course, and I wonder if I can extend it from my gatsby-node api.

I was reading up on using using multiple instances of DefinePlugin [here](https://github.com/webpack/webpack/issues/1577) but it seems to be unsupported. I wonder if gatsby maybe has a different solution as part of the webpack merging that I am overlooking.

**Comment by 0x80** [comment]
Looking at webpack.config.js, I guess one solution could be to create a dedicated api hook with an action to set environment variables and read them from the redux store when instantiating the DefinePlugin.

**Comment by KyleAMathews** [comment]
Yeah, this needs better support. There's a previous issue [here](https://github.com/gatsbyjs/gatsby/issues/660#issuecomment-280184453) which I'll redirect us to.
