### ISSUE TITLE
gatsby develop (for copied hello-world site) crashes with unhandled exception

### ISSUE THREAD

**Issue by realharry** [gatsbyjs/gatsby#10337]
## Description
I was following the tutorial: https://www.gatsbyjs.org/tutorial/
I created a hello-world site, and ran via `gatsby develop`. I was able to view the page from localhost:8000. Then, I copied the directory and tried to run `gatsby develop` in the copied directory, but couldn't. 

### Steps to reproduce

gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
cd hello-world
gatsby develop
^C
cp -r hello-world ../copied
cd ../copied/hello-world
gatsby develop

### Expected result

`Gatsby develop` should run and serve the page on localhost:8000.

### Actual result

It crashes with unhandled execption.

$:~/gatsby/tutorial-01/hello-world$ gatsby develop
success open and validate gatsby-configs — 0.017 s
success load plugins — 0.293 s
success onPreInit — 0.184 s
success delete html and css files from previous builds — 0.026 s
success initialize cache — 0.019 s
success copy gatsby files — 0.054 s
success onPreBootstrap — 0.031 s
success source and transform nodes — 0.029 s
success building schema — 0.186 s
success createPages — 0.001 s
success createPagesStatefully — 0.064 s
success onPreExtractQueries — 0.001 s
success update schema — 0.102 s
success extract queries from components — 0.038 s
success run graphql queries — 0.017 s — 2/2 140.71 queries/second
success write out page data — 0.009 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.002 s

info bootstrap finished - 4.175 s

 DONE  Compiled successfully in 2764ms                                                                        9:38:08 PM

You can now view gatsby-starter-hello-world in the browser.

  http://localhost:8000/

View GraphiQL, an in-browser IDE, to explore your site's data and schema

  http://localhost:8000/___graphql

Note that the development build is not optimized.
To create a production build, use gatsby build

ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
 WAIT  Compiling...                                                                                           9:38:08 PM

ℹ ｢wdm｣: Compiling...
 DONE  Compiled successfully in 36ms                                                                          9:38:09 PM

ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
error UNHANDLED EXCEPTION

  Error: watch /home/harry/gatsby/tutorial-01/hello-world/static ENOSPC
  
  - nodefs-handler.js:37 createFsWatchInstance
    [hello-world]/[chokidar]/lib/nodefs-handler.js:37:15
  
  - nodefs-handler.js:80 setFsWatchListener
    [hello-world]/[chokidar]/lib/nodefs-handler.js:80:15
  
  - nodefs-handler.js:232 FSWatcher.NodeFsHandler._watchWithNodeFs
    [hello-world]/[chokidar]/lib/nodefs-handler.js:232:14
  
  - nodefs-handler.js:414 FSWatcher.NodeFsHandler._handleDir
    [hello-world]/[chokidar]/lib/nodefs-handler.js:414:19
  
  - nodefs-handler.js:462 FSWatcher.<anonymous>
    [hello-world]/[chokidar]/lib/nodefs-handler.js:462:19
  
  - nodefs-handler.js:467 FSWatcher.<anonymous>
    [hello-world]/[chokidar]/lib/nodefs-handler.js:467:16
  

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.80
    Firefox: 63.0.3
  npmPackages:
    gatsby: ^2.0.33 => 2.0.63 
  npmGlobalPackages:
    gatsby-cli: 2.4.6

**Comment by danielcooke1996** [comment]
Sounds like a caching issue, try deleting `.cache` .
Run `sudo rm -rf node_modules/ && rm -f package-lock.json && npm cache clean -f && npm install`

Then try `gatsby develop` again.

**Comment by DSchau** [comment]
> watch /home/harry/gatsby/tutorial-01/hello-world/static ENOSPC

ENOSPC is actually a filesystem out of memory issue, correct? Do you have space to accommodate any additional files Gatsby will create as part of the develop process?

Additionally, [check out this StackOverflow article](https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve)

**Comment by realharry** [comment]
Thanks both for the answers. As it turned out, the copied .cache dir was causing the issue. Thanks!
