### ISSUE TITLE
Upgrade gatsby-source-filesystem chokidar to version 2

### ISSUE THREAD

**Issue by alexluong** [gatsbyjs/gatsby#10336]
## Summary

Hi. I wonder if we would be interested in upgrading `chokidar` to v2. I ran into some problems with  matching path using glob pattern, which I think version 2 of `chokidar` will support.

### Motivation

```js
  {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "stuff"
        path: "content/stuff/**/index.md",
      },
    },
```

This would result in an error:

```
The path passed to gatsby-source-filesystem does not exist on your file system:

content/stuff/**/index.md

Please pick a path to an existing directory.

See docs here - https://www.gatsbyjs.org/packages/gatsby-source-filesystem/
```

**Comment by KyleAMathews** [comment]
Possibly! What are the differences in the versions?

**Comment by alexluong** [comment]
I don't know. May worth posting an issue asking for migration guide over their repo?

In the mean time, do you know anyway we can perform something similar to glob matching for path in `gatsby-source-filesystem`? Or a negation in ignore would work too (ignore everything but `index.md`). I'm struggling with this problem.

**Comment by KyleAMathews** [comment]
Oh they don't have one or a list of breaking changes?

**Comment by alexluong** [comment]
Oh actually they do have one. They didn't update it in their releases, but there is the `CHANGELOG`.

```
Chokidar 2.0.0 (Dec 29, 2017)

    Breaking: Upgrade globbing dependencies which require globs to be more strict and always use POSIX-style slashes because Windows-style slashes are used as escape sequences
    Update tests to work with upgraded globbing dependencies
    Add ability to log FSEvents require error by setting CHOKIDAR_PRINT_FSEVENTS_REQUIRE_ERROR env
    Fix for handling braces in globs
    Add node 8 & 9 to CI configs
    Allow node 0.10 failures on Windows
```

Seems like the only breaking change is for Windows user, paths like `C:\something\...` would not work anymore.
