### ISSUE TITLE
What are the steps to use Gatsby with no CMS but only REST API as GraphQL ?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#10340]
Hi,

I actually use Gatsby with Prismic and it works great.
I would like to create another project but with no CMS.
I will have a REST API, which probably returns JSON.

I'm wondering **what do I need to use REST API with GraphQL and Gatsby** and is there something else I miss?

Thanks

**Comment by jgierer12** [comment]
You can use [`gatsby-source-apiserver`](https://www.gatsbyjs.org/packages/gatsby-source-apiserver) for REST API sources.

Closing this issue as answered. But if you need any more help feel free to ask :slightly_smiling_face:
