### ISSUE TITLE
remark-images and remark-embed-video wrap everything in <p> tags

### ISSUE THREAD

**Issue by alisonjoseph** [gatsbyjs/gatsby#10341]
`gatsby-remark-embed-video` and `gatsby-remark-images` seem to automatically wrap everything in a p tag. 

Is there a way to customize this, either with having it wrap in a div, or at the very least at a custom class to the `<p>` tag?

I'm using `gatsby-transformer-remark` to add custom html wrappers (grid code) to my p tags and I don't want the same added to all my images and video.

**Comment by dorukde** [comment]
I am using gatsby-transformer-remark on Gatsby v2.
The link renders as "`vimeo: https://www. ...`" and I see only text, which is strange. 

I will be trying to utilise gatsby-remark-responsive-iframe and see if I get any different result.

**Comment by dorukde** [comment]
It worked with gatsby-remark-responsive-iframe, on Gatsby v2.  I will be assigning a name to the iframe and try that.

**Comment by dorukde** [comment]
There's no way I could solve it simply by following what is inside the documentation - not with gatsby-remark-responsive-iframe, either. I could get responsiveness with a container div, but since the plug-in does not work, I get some unwanted padding at the top&bottom.

**Comment by edmundojr** [comment]
You can use the plugin `gatsby-remark-unwrap-images` as a workaround until this is resolved.

See: https://github.com/xuopled/gatsby-remark-unwrap-images

**Comment by snirp** [comment]
Not having luck with `gatsby-remark-unwrap-images`. It only seems to work if the <img> tag is a direct child of the <p> tag, but that is not how `gatsby-remark-image` works. It wraps the image in a <a> tag (which you can disable) and then a <span> tag.

**Comment by KidkArolis** [comment]
Replying to keep this issue open. It's still an issue and the suggested workaround doesn't work.

**Comment by KidkArolis** [comment]
In the meantime, I dropped this into my `plugins/gatsby-remark-unwrap-images/index.js`:

```js
const visit = require(`unist-util-visit`)
const remove = require(`unist-util-remove`)

module.exports = ({ markdownAST }) => {
  visit(markdownAST, `paragraph`, (node, index, parent) => {
    const hasOnlyImagesNodes = node.children.every(child => {
      return child.type === 'html' && child.url && child.alt
    })

    if (!hasOnlyImagesNodes) {
      return
    }

    remove(node, 'text')

    parent.children.splice(index, 1, ...node.children)

    return index
  })
}
```

and configured it like so in `gatsy-config.js`:

```
module.exports = {
    plugins: [
        {
            resolve: "gatsby-transformer-remark",
            options: {
                plugins: ["gatsby-remark-unwrap-images"],
            },
        },
    ],
}
```

**Comment by mirabilio** [comment]
I just released a plugin to solve this issue since I needed to remove the p tags also for another plugin I was working on: https://www.npmjs.com/package/gatsby-remark-remove-root-p-tag 

Lmk if there are any problems with it working for your use case.

**Comment by PilgrimMemoirs** [comment]
Is there a chance of reopening this? I'm having to hack around this issue as well and I don't quite understand the purpose of having them in paragraph tags to begin with. Thanks!
