### ISSUE TITLE
Error following the official quick start quide

### ISSUE THREAD

**Issue by Imaginarydesign** [gatsbyjs/gatsby#10351]
## Description

I am trying to follow the official quick start guide but having some issues/errors that prevent me from continuing.

### Steps to reproduce

1. npm install --global gatsby-cli
2. gatsby new gatsby-site

### Expected result

The project gatsby-site should be set up without errors.

### Actual result

The following errors occurred:

info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git
Cloning into 'gatsby-site'...
remote: Enumerating objects: 1002, done.
remote: Total 1002 (delta 0), reused 0 (delta 0), pack-reused 1002
Receiving objects: 100% (1002/1002), 1.59 MiB | 2.90 MiB/s, done.
Resolving deltas: 100% (568/568), done.
success Created starter directory layout
info Installing packages...
yarn install v1.3.2
(node:85683) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning gatsby > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
warning gatsby-plugin-sharp > imagemin-webp > cwebp-bin > bin-wrapper > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby > @reach/router > create-react-context@0.2.3" has unmet peer dependency "prop-types@^15.0.0".
warning "gatsby > terser-webpack-plugin > schema-utils > ajv-errors@1.0.0" has unmet peer dependency "ajv@>=5.0.0".
[4/4] 📃  Building fresh packages...
[1/5] ⠄ fsevents: https://fsevents-binaries.s3-us-west-2.amazonaws.com/
[2/5] ⠄ sharp
[-/5] ⠄ waiting...
[4/5] ⠄ pngquant-bin
warning Error running install script for optional dependency: "/Users/adam/Code/gatsby-site/node_modules/fsevents: Command failed.\nExit code: 1\nCommand: node install\nArguments: \nDirectory: /Users/adam/Code/gatsby-site/node_modules/fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.10.0\nnode-pre-gyp info using node@11.3.0 | darwin | x64\nnode-pre-gyp info check checked for \"/Users/adam/Code/gatsby-site/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node\" (not found)\nnode-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz\nnode-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz\nnode-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz \nnode-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.3.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) \nnode-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/adam/Code/gatsby-site/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:77:29)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)\nnode-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:421:16)\nnode-pre-gyp ERR! stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)\nnode-pre-gyp ERR! System Darwin 18.2.0\nnode-pre-gyp ERR! command \"/usr/local/Cellar/node/11.3.0_1/bin/node\" \"/Users/adam/Code/gatsby-site/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"\nnode-pre-gyp ERR! cwd /Users/[-/5] ⡀ waiting...
[2/5] ⡀ sharp: WARN install No prebuilt binaries found (target=11.3.0 r
[-/5] ⡀ waiting...
[-/5] ⡀ waiting...
error /Users/adam/Code/gatsby-site/node_modules/sharp: Command failed.
Exit code: 127
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /Users/adam/Code/gatsby-site/node_modules/sharp
Output:
info sharp Using cached /Users/adam/.npm/_libvips/libvips-8.7.0-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=11.3.0 runtime=

error Command failed: yarnpkg

  Error: Command failed: yarnpkg

  - index.js:236 Promise.all.then.arr
    [lib]/[gatsby-cli]/[execa]/index.js:236:11

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - async.js:138 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12

  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14

### Environment

System:
    OS: macOS 10.14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.3.0 - /usr/local/bin/node
    Yarn: 1.3.2 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.80
    Firefox: 63.0.3
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.53 => 2.0.64
    gatsby-image: ^2.0.20 => 2.0.22
    gatsby-plugin-manifest: ^2.0.9 => 2.0.11
    gatsby-plugin-offline: ^2.0.16 => 2.0.19
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.4
    gatsby-plugin-sharp: ^2.0.14 => 2.0.15
    gatsby-source-filesystem: ^2.0.8 => 2.0.11
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.6

**Comment by arturhenryy** [comment]
you might consider runnig "brew doctor" in your terminal and check the issues. this looks like a problem with your development environment rather than with gatsby

**Comment by Imaginarydesign** [comment]
brew doctor returns 'Your system is ready to brew'

**Comment by HarshitChhipa** [comment]
Having the same problem.
I know the issue that "pngquant package is broke" this is not there with the system.
Tried installing standalone.
Tried installing via setup file and everything but nope.
But tried everything to put but not able to resolve it.
Any one who resolved it????

**Comment by rjoseph2** [comment]
Angular 6 install failed please see the log

sudo npm install -g @angular/cli
/usr/local/Cellar/node/11.3.0_1/bin/ng -> /usr/local/Cellar/node/11.3.0_1/lib/node_modules/@angular/cli/bin/ng

fsevents@1.2.4 install /usr/local/Cellar/node/11.3.0_1/lib/node_modules/@angular/cli/node_modules/fsevents
node install

node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.4 and node@11.4.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/Cellar/node/11.3.0_1/lib/node_modules/@angular/cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64'
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/11.3.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /usr/local/Cellar/node/11.3.0_1/lib/node_modules/@angular/cli/node_modules/fsevents
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/11.3.0_1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack at ChildProcess. (/usr/local/Cellar/node/11.3.0_1/lib/node_modules/@angular/cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/11.3.0_1/bin/node" "/usr/local/Cellar/node/11.3.0_1/lib/node_modules/@angular/cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/Cellar/node/11.3.0_1/lib/node_modules/@angular/cli/node_modules/fsevents
node-pre-gyp ERR! node -v v11.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/11.3.0_1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: node install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by HarshitChhipa** [comment]
Sorry Resolved the Issue.....
Man It is working absolutely fine....
It a bit of there fault also...
Documentation is proper...
I have wasted my whole day to just set up a basic app....
I also made a mistake by not reading the whole documentation..
Read this docs......
https://www.gatsbyjs.org/docs/gatsby-on-windows/

So do according to your OS and close this issue....
You missed some step....

> ## Description
> I am trying to follow the official quick start guide but having some issues/errors that prevent me from continuing.
> 
> ### Steps to reproduce
> 1. npm install --global gatsby-cli
> 2. gatsby new gatsby-site
> 
> ### Expected result
> The project gatsby-site should be set up without errors.
> 
> ### Actual result
> The following errors occurred:
> 
> info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git
> Cloning into 'gatsby-site'...
> remote: Enumerating objects: 1002, done.
> remote: Total 1002 (delta 0), reused 0 (delta 0), pack-reused 1002
> Receiving objects: 100% (1002/1002), 1.59 MiB | 2.90 MiB/s, done.
> Resolving deltas: 100% (568/568), done.
> success Created starter directory layout
> info Installing packages...
> yarn install v1.3.2
> (node:85683) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> info No lockfile found.
> [1/4] 🔍 Resolving packages...
> warning gatsby > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
> warning gatsby-plugin-sharp > imagemin-webp > cwebp-bin > bin-wrapper > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
> [2/4] 🚚 Fetching packages...
> [3/4] 🔗 Linking dependencies...
> warning "gatsby > @reach/router > create-react-context@0.2.3" has unmet peer dependency "prop-types@^15.0.0".
> warning "gatsby > terser-webpack-plugin > schema-utils > ajv-errors@1.0.0" has unmet peer dependency "ajv@>=5.0.0".
> [4/4] 📃 Building fresh packages...
> [1/5] ⠄ fsevents: https://fsevents-binaries.s3-us-west-2.amazonaws.com/
> [2/5] ⠄ sharp
> [-/5] ⠄ waiting...
> [4/5] ⠄ pngquant-bin
> warning Error running install script for optional dependency: "/Users/adam/Code/gatsby-site/node_modules/fsevents: Command failed.\nExit code: 1\nCommand: node install\nArguments: \nDirectory: /Users/adam/Code/gatsby-site/node_modules/fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.10.0\nnode-pre-gyp info using node@11.3.0 | darwin | x64\nnode-pre-gyp info check checked for "/Users/adam/Code/gatsby-site/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" (not found)\nnode-pre-gyp http GET [https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz\nnode-pre-gyp](https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz%5Cnnode-pre-gyp) http 404 [https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz\nnode-pre-gyp](https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz%5Cnnode-pre-gyp) WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz \nnode-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.3.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) \nnode-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)\nnode-pre-gyp ERR! stack at ChildProcess. (/Users/adam/Code/gatsby-site/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:77:29)\nnode-pre-gyp ERR! stack at ChildProcess.emit (events.js:182:13)\nnode-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)\nnode-pre-gyp ERR! stack at onErrorNT (internal/child_process.js:421:16)\nnode-pre-gyp ERR! stack at process.internalTickCallback (internal/process/next_tick.js:72:19)\nnode-pre-gyp ERR! System Darwin 18.2.0\nnode-pre-gyp ERR! command "/usr/local/Cellar/node/11.3.0_1/bin/node" "/Users/adam/Code/gatsby-site/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"\nnode-pre-gyp ERR! cwd /Users/[-/5] ⡀ waiting...
> [2/5] ⡀ sharp: WARN install No prebuilt binaries found (target=11.3.0 r
> [-/5] ⡀ waiting...
> [-/5] ⡀ waiting...
> error /Users/adam/Code/gatsby-site/node_modules/sharp: Command failed.
> Exit code: 127
> Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
> Arguments:
> Directory: /Users/adam/Code/gatsby-site/node_modules/sharp
> Output:
> info sharp Using cached /Users/adam/.npm/_libvips/libvips-8.7.0-darwin-x64.tar.gz
> prebuild-install WARN install No prebuilt binaries found (target=11.3.0 runtime=
> 
> error Command failed: yarnpkg
> 
> Error: Command failed: yarnpkg
> 
> * index.js:236 Promise.all.then.arr
>   [lib]/[gatsby-cli]/[execa]/index.js:236:11
> * util.js:16 tryCatcher
>   [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
> * promise.js:512 Promise._settlePromiseFromHandler
>   [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
> * promise.js:569 Promise._settlePromise
>   [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
> * promise.js:614 Promise._settlePromise0
>   [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
> * promise.js:694 Promise._settlePromises
>   [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18
> * promise.js:638 Promise._fulfill
>   [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18
> * promise_array.js:126 PromiseArray._resolve
>   [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19
> * promise_array.js:144 PromiseArray._promiseFulfilled
>   [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14
> * promise.js:574 Promise._settlePromise
>   [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26
> * promise.js:614 Promise._settlePromise0
>   [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
> * promise.js:694 Promise._settlePromises
>   [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18
> * async.js:138 _drainQueueStep
>   [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12
> * async.js:131 _drainQueue
>   [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9
> * async.js:147 Async._drainQueues
>   [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5
> * async.js:17 Immediate.Async.drainQueues [as _onImmediate]
>   [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
> 
> ### Environment
> System:
> OS: macOS 10.14.1
> CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
> Shell: 5.3 - /bin/zsh
> Binaries:
> Node: 11.3.0 - /usr/local/bin/node
> Yarn: 1.3.2 - ~/.yarn/bin/yarn
> npm: 6.4.1 - /usr/local/bin/npm
> Browsers:
> Chrome: 71.0.3578.80
> Firefox: 63.0.3
> Safari: 12.0.1
> npmPackages:
> gatsby: ^2.0.53 => 2.0.64
> gatsby-image: ^2.0.20 => 2.0.22
> gatsby-plugin-manifest: ^2.0.9 => 2.0.11
> gatsby-plugin-offline: ^2.0.16 => 2.0.19
> gatsby-plugin-react-helmet: ^3.0.2 => 3.0.4
> gatsby-plugin-sharp: ^2.0.14 => 2.0.15
> gatsby-source-filesystem: ^2.0.8 => 2.0.11
> gatsby-transformer-sharp: ^2.1.8 => 2.1.9
> npmGlobalPackages:
> gatsby-cli: 2.4.6

**Comment by DSchau** [comment]
@HarshitChhipa nothing to apologize for; we're so glad you figured it out!

I'm going to close this as it seems the issue has been resolved; thanks for using Gatsby, and we hope from here on out you have a better experience 💜 

For posterity and anyone reading this ticket in the future, looks like there were Windows specific issues that can be remedied by reading the support document [Gatsby On Windows](https://www.gatsbyjs.org/docs/gatsby-on-windows/)

**Comment by DSchau** [comment]
@Imaginarydesign if that page above doesn't fix your issue, please feel free to re-open. Thanks!

**Comment by HarshitChhipa** [comment]
sudo apt update && sudo apt -y upgrade && sudo apt install build-essential && sudo apt install git && sudo apt install libpng-dev

Ran this and do a fresh install.
It will solve your problem.
The thing which was causing issue is pngquant-bin or might be packages are not installed correctly due to internet or something....do a fresh install and before that run this command majorly install libpng-dev....
MacOc is also like ubuntu so this should resolve ur problem.

**Comment by alxvallejo** [comment]
>MacOc is also like ubuntu so this should resolve ur problem

apt is a Linux thing. Having this issue on OSX. Anyone resolve this?

**Comment by abhishekmg** [comment]
I am currently in mac os 10.14.3 , I had initially installed gatsby cli without installing Xcode Command line tools and got an access permission denied error . Installing Xcode Command line by xcode-select --install and then installing gatsby cli solved all my issues . 
Please refer https://www.gatsbyjs.org/tutorial/part-zero/ when setting up .
