### ISSUE TITLE
Cannot load JPG file

### ISSUE THREAD

**Issue by TaigaMatsumoto** [gatsbyjs/gatsby#10358]
## Summary
Cannot load JPG format file.

## Description
Hello. I am a beginner of React and Gatsby, and just faced a kinda weird issue. 

I tried to use JPG format image as background image in body element. 
```
body{
  background-image: url("../images/bg_image_one_sunrise.JPG");
  background-repeat: no-repeat;
  background-size: 100% auto;
  background-position: center top;
  background-attachment: fixed;
  margin: 0;
  padding: 0;
}
```

But, I received the error like this.

```
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

 @ ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/lib??postcss-2!./src/components/layout.css 7:112-157
 @ ./src/components/layout.css
 @ ./src/components/layout.js
 @ ./src/pages/404.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false C://Users//matsu//personal_portfolio//website_taigamatsumoto_2018//.cache//app
```

It seems like I need another loader for css. Which loader should I use to implement this? By the way, I replaced JPG file with PNG file and it works fine.

I also tried with gatsby-image API to load JPG file but also failed with same error message.

**Comment by arturhenryy** [comment]
try renaming the file to lower case -> jpg. not sure why that is uppercase. normal convention for this is lowercase. might work just like that

**Comment by aesthytik** [comment]
yeah lower casing should work

**Comment by TaigaMatsumoto** [comment]
Yes! It worked! Thank you so much :)
