### ISSUE TITLE
Gatsby fails build with npm link'ed local npm module

### ISSUE THREAD

**Issue by TeemuKoivisto** [gatsbyjs/gatsby#10364]
## Description

Gatsby will throw errors if developing with a locally linked npm module using `npm link`. Gatsby runs eslint against the local library's source code which, as you can imagine, doesn't follow eslint's best practises.

### Steps to reproduce

Create a local npm library, or just clone some ready-made library. Then build it and link it to your global npm dependencies: `npm link`. Then inside your Gatsby project link it to your dependencies: `npm link <library>`. 

### Expected result

Gatsby shouldn't run eslint against the library's code.

### Actual result

The opposite of the previous statement.

### Environment

My Gatsby is 2.0.22 and I'm using it with TypeScript if that makes any difference.

**Comment by trangcongthanh** [comment]
I'm using typescript and got a ton of errors from default `eslint-loader` too. I found the answer in #5493. You need create a blank `.eslintrc` to disable default `eslint-loader`.

**Comment by TeemuKoivisto** [comment]
> I'm using typescript and got a ton of errors from default `eslint-loader` too. I found the answer in #5493. You need create a blank `.eslintrc` to disable default `eslint-loader`.

Sure enough, that fixed it. Thank you! Probably this could be classified as a borderline bug though?

**Comment by bellindj** [comment]
> I'm using typescript and got a ton of errors from default `eslint-loader` too. I found the answer in #5493. You need create a blank `.eslintrc` to disable default `eslint-loader`.

Thank you this worked for us!
