### ISSUE TITLE
build failure - Generating JavaScript bundles failed

### ISSUE THREAD

**Issue by arturhenryy** [gatsbyjs/gatsby#10363]
## Description

my build fails although everything seems to work fine on run. i have no experience in debugging stuff like that. anybody has a hint what is wrong here?

```
error Generating JavaScript bundles failed


  TypeError: Cannot read property 'resolveId' of undefined

  - index.js:181 Compiler.Plugin
    [si-page]/[lodash-webpack-plugin]/lib/index.js:181:32

  - webpack.js:45 webpack
    [si-page]/[webpack]/lib/webpack.js:45:13

  - build-javascript.js:18 Promise
    [si-page]/[gatsby]/dist/commands/build-javascript.js:18:7

  - debuggability.js:313 Promise._execute
    [si-page]/[bluebird]/js/release/debuggability.js:313:9

  - promise.js:483 Promise._resolveFromExecutor
    [si-page]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [si-page]/[bluebird]/js/release/promise.js:79:10

  - build-javascript.js:17
    [si-page]/[gatsby]/dist/commands/build-javascript.js:17:12

  - Generator.next

  - util.js:16 tryCatcher
    [si-page]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [si-page]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [si-page]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [si-page]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [si-page]/[bluebird]/js/release/promise.js:694:18

  - async.js:138 _drainQueueStep
    [si-page]/[bluebird]/js/release/async.js:138:12


error Command failed with exit code 1.
```

### Environment

  System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.3.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 38.0.5
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.63 => 2.0.64
    gatsby-image: ^2.0.22 => 2.0.22
    gatsby-link: ^2.0.7 => 2.0.7
    gatsby-plugin-catch-links: ^2.0.9 => 2.0.9
    gatsby-plugin-feed: ^2.0.11 => 2.0.11
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8
    gatsby-plugin-manifest: ^2.0.11 => 2.0.11
    gatsby-plugin-nprogress: ^2.0.7 => 2.0.7
    gatsby-plugin-offline: ^2.0.18 => 2.0.19
    gatsby-plugin-page-transitions: ^1.0.7 => 1.0.7
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.4
    gatsby-plugin-sass: ^2.0.7 => 2.0.7
    gatsby-plugin-sharp: ^2.0.14 => 2.0.15
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4
    gatsby-plugin-twitter: ^2.0.8 => 2.0.8
    gatsby-remark-autolink-headers: ^2.0.12 => 2.0.12
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.0.7
    gatsby-remark-images: ^3.0.1 => 3.0.1
    gatsby-remark-prismjs: ^3.1.4 => 3.1.4
    gatsby-remark-responsive-iframe: ^2.0.7 => 2.0.7
    gatsby-source-filesystem: ^2.0.11 => 2.0.11
    gatsby-source-wordpress: ^3.0.19 => 3.0.19
    gatsby-transformer-remark: ^2.1.15 => 2.1.15
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.6

**Comment by heathblandford** [comment]
@arturhenryy were you able to get this fixed? I'm getting same error and am unable to find anything to help

**Comment by arturhenryy** [comment]
@heathblandford hey i fixed it but i dont remember what solution here was. two options:
1. outdated dependcies / check "npm outdated" and update
2. install missing peer dependencies
