### ISSUE TITLE
Link to local PDF asset to download?

### ISSUE THREAD

**Issue by jonathan-chin** [gatsbyjs/gatsby#1036]
I'm trying to add a download link to a static pdf. Something like this:
``` 
<Link to={prefixLink('/assets/pdf/JonChinResume.pdf')}>
    <RaisedButton
            primary={true}
            label='download as PDF' />
</Link>
```

and I have the pdf in the correct spot. However, I think Gatsby's router is not recognizing it as a download option. How could I solve this?

**Comment by craig-mulligan** [comment]
Hey @jonathan-chin why not use an `<a href={prefixLink('/assets/pdf/JonChinResume.pdf')}>` tag?

**Comment by jonathan-chin** [comment]
Perfect! that works!

is Link only used for page components?

**Comment by craig-mulligan** [comment]
Yea, it's to make react-router aware of the of the link, react router handles any client-side routing like switching between page views, but if you want your browser to make a request for an external resource you should use <a>.

**Comment by jonathan-chin** [comment]
Thanks! Gatsby is my first ReactJS project so I'm a little unfamiliar with the components.
