### ISSUE TITLE
Can´t get gatsby to process my scss files

### ISSUE THREAD

**Issue by layoutzweb** [gatsbyjs/gatsby#1037]
I started out with the minimal starter project, than added a couple of .scss files into the css folder, but can´t get gatsby to process those files, if I run develop the styles are not loaded same when I run build.

Can´t find on docs any documentation about how to properly set this up, I tried some webpack configs I found on web but no changes.

**Comment by layoutzweb** [comment]
Ok so I figured this out finally lol, I had to import the .scss file into the page jsx.

`import path/to/my/scss/file.scss `

is there a way to load it as a file in the header?

**Comment by hugmanrique** [comment]
You would need to use the ExtractTextPlugin from webpack to create a CSS bundle containing all your CSS rules. Currently, sass-loaders spits out the CSS into the JS bundle, but if you use that Webpack plugin, you can add a <link> to the compiled CSS bundle

**Comment by KyleAMathews** [comment]
If you're still having trouble, checkout the sass example site in the examples folder
