### ISSUE TITLE
Document stub node "Client data fetching" with relevant information

### ISSUE THREAD

**Issue by tusharjoshi** [gatsbyjs/gatsby#10373]
Provide relevant documentation to change this stub into actual document for the section [Client data fetching](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/client-data-fetching.md)

Located at [Site URL here] (https://www.gatsbyjs.org/docs/client-data-fetching/#client-data-fetching)

Recently there is one [tweet](https://twitter.com/IAmKale/status/1071108771684921344) regarding the state of documentation for this section.

**Comment by tusharjoshi** [comment]
I need information about the context of Client data fetching which should be documented on this page.  Any pointers bout youtube videos, blog posts, code comments or any place where this functionality is discussed will help.  

Is this page title referring to fetching data after the site is built and deployed?  Or this is at the time of building the site.  This node is under section "Use Cases for Gatsby" hence not sure, any information about these from the developers will help me proceed.

**Comment by btk** [comment]
I would say the title is not so clear, If I wanted to write something under that title. I probably wouldn't. The stubs should explain the context of that page with at least one paragraph I think. 

It does not look very inviting to edit or contribute to be honest.

**Comment by tusharjoshi** [comment]
Currently 6 nodes under the section [Use cases with Gatsby](https://www.gatsbyjs.org/docs/building-apps-with-gatsby/) are stubs.  If this title is unclear then we should remove that stub or update it so someone can contribute to make it complete.

I am very new to Gatsby and cannot comment on what shall be the correct title, need help from Gatsby veterans here.

**Comment by amberleyromo** [comment]
Hi @tusharjoshi -- great observation, thank you! We're always trying to expand and cover as much as we can in docs. In this case, we're removing some of these stubs from the sidebar, until we can better define the question we need to answer.

Can you go into more specifics about the problem you were trying to solve, that led you to this doc page?

**Comment by tusharjoshi** [comment]
Hi @amberleyromo Recently there is one [tweet here](https://twitter.com/IAmKale/status/1071108771684921344) regarding the state of documentation for this section.  As I watch @gatsbyjs tweeter feed I came across that tweet and wanted to provide solution by contributing here.

This is [24pullrequest project](https://24pullrequests.com/) month and I keep searching for small contributions which can be done in opensource projects.  Thanks.

**Comment by shannonbux** [comment]
Ok, I searched my slack history and found that when @KyleAMathews suggested this doc, another way to name it could be "runtime data fetching" or "dynamic data fetching", though we concluded to not use "dynamic" since it isn't well-defined.

The two main problem we were trying to solve:
- clarify what Gatsby does at build time and at runtime
- demonstrate and teach how to use Gatsby to build apps

I'm not sure I know enough to make the final call here; does this context help explain this stub article's purpose and whether it's worth creating it?

**Comment by jgierer12** [comment]
Sounds like this has some overlap with the blog post - [Gatsby for Apps](https://www.gatsbyjs.org/blog/2018-11-07-gatsby-for-apps/). @tusharjoshi maybe you'll want to read that to get an idea of what the guide should cover.

**Comment by amberleyromo** [comment]
Closing! This stub was built out in #10516
