### ISSUE TITLE
Allow the use of grid prefixes with autoprefixer

### ISSUE THREAD

**Issue by greatwitenorth** [gatsbyjs/gatsby#10387]
## Summary

I'd like the ability to enable CSS Grid prefixes with autoprefixer. Right now it looks like the only configurable value being passed into autoprefixer is the ```browserslist``` value from package.json:

https://github.com/gatsbyjs/gatsby/blob/fed6d35f991abadca5e4ab335597d0c045d882da/packages/gatsby/src/utils/webpack-utils.js#L204-L225

### Basic example

Following the example of how brwoserslist was implemented we could have a key in package.json called ```grid``` which would allow users to manually specify how they want it handled. 

An alternative solution would be to provide a ```autoprefixer``` key which would allow us to pass in any autoprefixer configurations.

### Motivation

The idea behind this is to enable some basic CSS Grid functionality in IE 11.

**Comment by LekoArts** [comment]
Hi 👋 

You could use autoprefixer comments, couldn't you? (As a temporary solution)
https://css-tricks.com/css-grid-in-ie-duplicate-area-names-now-supported/#article-header-id-11

Do you want to create a PR to include this functionality?

**Comment by greatwitenorth** [comment]
That's great. I didn't even know about autoprefixer comments. At the moment I'm just using Styled Components, so I'm not using a stylesheet. Where would I put the ```/* autoprefixer grid: on */``` comment when using styled components?

**Comment by LekoArts** [comment]
I linked the above article because I assumed you're using gatsby's built-in css support. The code snipped you showed above won't affect your styled-components code.
https://github.com/styled-components/styled-components/issues/1184

That's an issue with styled-components (or Stylis), not with Gatsby 😊

**Comment by LekoArts** [comment]
Closing this issue as answered, please comment if you have further questions.
