### ISSUE TITLE
Add `location` parameter to `onClientEntry`

### ISSUE THREAD

**Issue by johncmunson** [gatsbyjs/gatsby#10392]
## Summary

In regards to the browser api's `onClientEntry` and `onRouteUpdate`, only `onRouteUpdate` receives `location` as a parameter. For analytics purposes, it is necessary to have knowledge of the current location inside of each of these api methods.

### Basic example

Old:
```
exports.onClientEntry = () => {
  console.log("We've started!")
  callAnalyticsAPI()
}
```

New:
```
exports.onClientEntry = ({ location }) => {
  console.log("We've started!")
  callAnalyticsAPI(location.pathname)
}
```

### Motivation

You need to record a pageview with your analytics service as soon as your site initializes. However, your site could initialize at any location, not just the homepage. Therefore, we must have access to the current location inside of `onClientEntry`.

**Comment by johncmunson** [comment]
UPDATE: It appears that I created this issue a little prematurely, since `onRouteUpdate` is also called when the site first initializes. However, it leaves me wondering whether there are any other instances where you would need access to `location` inside of `onClientEntry`?

**Comment by johncmunson** [comment]
.

**Comment by sourabh1031** [comment]
Hello @johncmunson i am new here. i want to contribute to gatsby. i thought of learning while solvng this issue. can you tell me the prerequisites i must have to solve this issue. any guide or reference if provided would be great.

**Comment by johncmunson** [comment]
@sourabh1031 I'm not familiar with Gatsby's internals, only the APIs that it exposes. While tackling this issue may be a good learning exercise, I don't think it would provide much practical benefit to the project. If you are new to Gatsby, I would recommend first getting familiar with using it to build some simple projects. If you like it as a tool, then you may also find it worthwhile to contribute back by working on other issues tagged with `good first issue`. Hope that helps!
