### ISSUE TITLE
Share code between pages and gatsby-*.js files?

### ISSUE THREAD

**Issue by coreyward** [gatsbyjs/gatsby#10391]
I'd like to put logic that maps node types to specific paths for routing in a single file that can be imported/required by both `gatsby-node.js` as well as a React link component. I'm not sure how to accomplish this with Gatsby 2+ due to 1) config files not being run through Babel or Webpack and 2) strict rules against mixing require and import styles. 

Is there a better way than having two copies of the file and all of its dependencies?

**Comment by tdharmon** [comment]
@coreyward did you ever figure out a solution to this? I am also having this issue

**Comment by coreyward** [comment]
@tdharmon Not one I was happy with, no. The best solution I could come up with would be to use Babel to transpile a specific shared folder as a pre-`develop` and pre`build` hook, then use the transpiled files to do `require` on in `gatsby-node.js` and use an `import` for app-code that would get processed by the Babel/Webpack configuration as part of Gatsby's pipeline. I never bothered setting this up since most of what I wanted to share was easy enough to keep two copies of that it wasn't worth the effort.

**Comment by coreyward** [comment]
@LekoArts Care to share why you removed the `not stale` label? This is still very much an issue and nobody from the core team has reviewed or weighed in despite the `inkteam-to-review` label.

**Comment by gillkyle** [comment]
I can't speak for @LekoArts but my guess is it seemed like something that ought to get responded to, but whoever saw the issue just didn't have the context or time when they saw it to respond so I can try and weigh in though I'm not entirely sure I understand what you are trying to accomplish: 

- having a `path` queryable on nodes that's coming from a source that can be imported in `gatsby-node` or a component? (the first thing that comes to mind is how the Gatsby docs use a yaml file that is imported in [`gatsby-node`](https://github.com/gatsbyjs/gatsby/blob/9e9dc3b1475a5d3312483231cea52572b68ec74f/www/gatsby-node.js#L17-L19) and a [component](https://github.com/gatsbyjs/gatsby/blob/master/www/src/utils/sidebar/item-list.js#L1))
- limiting code reuse, like with a fragment you import? seems maybe tangentially related to this question: https://spectrum.chat/gatsby-js/general/possible-to-use-query-fragment-from-a-template-in-createpage~4c8c083d-8299-459b-90fc-8d38f4ac8142

Sorry if copying around code has been a frustration (and I'm really not helping all that much with this response 😬). Maybe @thetrevorharmon can weigh in too?

**Comment by coreyward** [comment]
@gillkyle Thanks for trying to help. The essential problem is the mixed use of `import` and `require`. If Gatsby supported `import` in `gatsby-*.js` files it would solve the issue.

**Comment by thetrevorharmon** [comment]
Yeah, @coreyward does a decent job of explaining what the issue is. I'm doing some weird stuff with mixed types in graphQL, and I have logic that I need to share between some pages and some `gatsby-*.js` files. Ideally I could have some `utilities` folder and be able to get at that from both the `pages` directory and from any `gatsby-*.js` file, but because of the `import` vs `require` issue, I can't share the code.

**Comment by gillkyle** [comment]
I'm not aware of what would technically be required to allow transpiling `gatsby-*.js` files, though I imagine it's not trivial. Those files don't support mixed imports/requires, but could everything be changed to require in the `gatsby-*.js` files and import in the transpiled files? Maybe I'm still misunderstanding why that's not possible though. I bet you've probably already seen this issue (#7810) too, but does that not help?
