### ISSUE TITLE
createPage index?

### ISSUE THREAD

**Issue by braco** [gatsbyjs/gatsby#10394]
Is it not possible to create the main index page via createPage?

I've tried obvious combinations like

createPage({ path: '/' });
createPage({ path: undefined });
createPage({ path: '/index' });

But nothing seems to actually capture the intention. This seems like such a glaring oversight that it must be my fault, but I can't find documentation on this other than creating the file in `pages/index.js`.

**Comment by KyleAMathews** [comment]
Can you share your full code?

**Comment by braco** [comment]
Just got it to work. Not sure what changed, I erased the build folder three times, and on the third time `{ path: '/' }` worked. I'm left with the sense that '/' isn't overwriting older build content like other paths do. Will reopen if I can figure that out.

**Comment by tylermcrobert** [comment]
@braco do you keep your pages/index.js file?

**Comment by kmcaloon** [comment]
I was running into the same problem. Suggestion by @tylermcrobert worked instantly.

**Comment by tfasolino-crak** [comment]
Same problem, I have renamed my index.js to main.js and everything works well

**Comment by OdujokoD** [comment]
@tfasolino-crak, thanks!. After debugging for several hours, this fix worked like charm.

**Comment by usachev-dev** [comment]
@tfasolino-crak you saved me, very arcane problem

**Comment by miguelangeltorresfp** [comment]
Same problem here and @tfasolino-crak trick worked for me. Then I could remove main.js. Maybe it was a problema with the cache.
