### ISSUE TITLE
netlify-cms IE11

### ISSUE THREAD

**Issue by buz-zard** [gatsbyjs/gatsby#10405]
## Description

The netlify-cms build doesn't seem to support IE11. You can't really open the admin url. ~~Also when using [module path init script](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify-cms#modulepath) and using newer syntax I get errors on non admin routes also.~~ (errors in non `/admin/` seem unrelated with CMS plugin)

### Steps to reproduce

In IE11 open - https://gatsby-netlify-cms.netlify.com/admin/

(from the starter repo - https://github.com/netlify-templates/gatsby-starter-netlify-cms)

### Expected result

The CMS login page should be rendered.

### Actual result

Console error is thrown and nothing is rendered.

![image](https://user-images.githubusercontent.com/3521740/49783005-ff5f0c00-fd20-11e8-89a4-6c3ef3f94e24.png)

![image](https://user-images.githubusercontent.com/3521740/49783085-4947f200-fd21-11e8-9392-b043503d56f3.png)

The issue is at template string.

### Environment

from the starter repo:
```
    "gatsby": "^2.0.0",
    "gatsby-image": "^2.0.10",
    "gatsby-plugin-netlify": "^2.0.0",
    "gatsby-plugin-netlify-cms": "^3.0.0",
    "gatsby-plugin-purgecss": "^2.4.0",
    "gatsby-plugin-react-helmet": "^3.0.0",
    "gatsby-remark-copy-linked-files": "^2.0.6",
    "gatsby-plugin-sass": "^2.0.1",
    "gatsby-plugin-sharp": "^2.0.5",
    "gatsby-remark-images": "^3.0.0",
    "gatsby-remark-relative-images": "^0.2.0",
    "gatsby-source-filesystem": "^2.0.1",
    "gatsby-transformer-remark": "^2.1.1",
    "gatsby-transformer-sharp": "^2.1.1",
```

---

~~I think it's relatively fine for CMS itself to not work in IE, but it shouldn't affect the non CMS routes.~~

**Comment by trickydisco78** [comment]
Looks to me like an es6 template literal which IE11 won't understand. Surely it should be transpiling down to es5 for IE11?

**Comment by pieh** [comment]
Does this error show up in non `/admin/` routes?

**Comment by sidharthachatterjee** [comment]
@buz-zard It seems that `netlify-cms` dropped support for IE11 in favour of a smaller bundle size (https://github.com/netlify/netlify-cms/pull/704)

The `gatsby-plugin-netlify-cms` plugin includes `netlify-cms` without any transpilation since it is pre-bundled code. Closing this since the errors are specific to netlify-cms. 

Thanks!
