### ISSUE TITLE
404 for XHR request in IE11

### ISSUE THREAD

**Issue by trickydisco78** [gatsbyjs/gatsby#10408]
## Description

Getting a 404 for a file which doesn't exist in the build in IE11

### Steps to reproduce
Go to https://uob-homepage.netlify.com/ in IE11 and inspect the page
There is a XHR request for Request URL: https://uob-homepage.netlify.com/app-61bfb0215bea3e4434c
Which is strange as it also requests this filename earlier in the cycle
   Request URL: https://uob-homepage.netlify.com/app-61bfb0215bea3e4434c9.js

### Expected result
Should not be producing a 404

### Actual result
![image](https://user-images.githubusercontent.com/3627429/49796603-0b54c900-fd35-11e8-8419-4addc582b8e1.png)

### Environment

System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.785.0
  npmPackages:
    gatsby: ^2.0.64 => 2.0.64
    gatsby-image: ^2.0.22 => 2.0.22
    gatsby-link: ^2.0.1 => 2.0.1
    gatsby-plugin-netlify: ^2.0.6 => 2.0.6
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^2.0.1 => 2.0.1
    gatsby-plugin-sharp: ^2.0.6 => 2.0.6
    gatsby-plugin-typescript: ^2.0.0 => 2.0.0
    gatsby-source-filesystem: ^2.0.1 => 2.0.1
    gatsby-transformer-sharp: ^2.1.3 => 2.1.3

**Comment by sidharthachatterjee** [comment]
Hey @trickydisco78 

Just tested this on IE11 and I can see the request and 404. It appears that it is an HTTP/2 server push that Netlify is doing. 

Can you please post your `gatsby-plugin-netlify` config options?
