### ISSUE TITLE
Can I use multiple Google Tag Manager Ids with gatsby-plugin-google-tagmanager?

### ISSUE THREAD

**Issue by DavidTheSimon** [gatsbyjs/gatsby#10407]
Hi all,

I would like to use multiple Tag Manager ids in my project.
Is there any possible way to achieve this with _gatsby-plugin-google-tagmanager_ plugin?

Many thanks,
David

**Comment by pieh** [comment]
You should be able to put 2 (or more) separate instances of the plugin with different `id` in your `gatsby-config`:

```
// In your gatsby-config.js
plugins: [
  {
    resolve: `gatsby-plugin-google-tagmanager`,
    options: {
      id: "id1",
    },
  },
  {
    resolve: `gatsby-plugin-google-tagmanager`,
    options: {
      id: "id2",
    },
  },
]
```

**Comment by DavidTheSimon** [comment]
Well, that actually worked 👍 Thanks

**Comment by LekoArts** [comment]
Going to close this the. 😊

**Comment by Anurodhyadav** [comment]
How to make sure that one tag manager works for production only and one for development only when using two different google tag manager id?
