### ISSUE TITLE
"CSSSyntaxError" in non-existent file when running gatsby build

### ISSUE THREAD

**Issue by aofolts** [gatsbyjs/gatsby#10401]
## Description

`gatsby develop` works fine, but `gatsby build` fails:

"CssSyntaxError: /Users/aofolts/GitHub/sherpa-gatsby/0.6c8fbe26a8cf4a9a583a.css:106:2  4: Missed semicolon"

This would seemingly be easy to debug, except the file mentioned doesn't exist. I'm assuming it's some temporary file generated during the build process, but I have no clue how to go about figuring out where the issue is in the source files.

I ran a whole slew of regex searches to try to find any lines with missing semicolons, but nothing turned up.

### Steps to reproduce

1. Run `gatsby build`.
2. Error occurs.

https://github.com/aofolts/sherpa-gatsby

### Expected result

The build should run successfully.

### Actual result

Gatsby errors out:

"CssSyntaxError: /Users/aofolts/GitHub/sherpa-gatsby/0.6c8fbe26a8cf4a9a583a.css:106:2  4: Missed semicolon"

### Environment

```
 System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.4.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.80
    Firefox: 63.0.3
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.64 => 2.0.64 
    gatsby-image: ^2.0.22 => 2.0.22 
    gatsby-link: ^2.0.7 => 2.0.7 
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8 
    gatsby-plugin-less: ^2.0.8 => 2.0.8 
    gatsby-plugin-manifest: ^2.0.7 => 2.0.11 
    gatsby-plugin-offline: ^2.0.10 => 2.0.19 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.4 
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0 
    gatsby-plugin-sharp: ^2.0.15 => 2.0.15 
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3 
    gatsby-plugin-svg-sprite: ^2.0.1 => 2.0.1 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-source-contentful: ^2.0.19 => 2.0.19 
    gatsby-source-filesystem: ^2.0.11 => 2.0.11 
    gatsby-transformer-json: ^1.0.20 => 1.0.20 
    gatsby-transformer-remark: ^2.1.15 => 2.1.15 
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9 
  npmGlobalPackages:
    gatsby-cli: 2.4.6
```

**Comment by aofolts** [comment]
This was being caused by some repeated values inside an animation property:

`animation: .2s ease-in-out latterUp .5s ease-in-out;`

I finally managed to debug it by going into...

`[cssnano]/[postcss]/lib/input.js:130:16`

...and logging `JSON.stringify(token)` as the error message, which gave me a text snippet that I then used to locate the problem property.

**Comment by shabith** [comment]
Hi @aofolts,

I'm having a similar issue like this.  Where I can find `[postcss]/lib/input.js:130:16` in the project?

Thanks

**Comment by shabith** [comment]
Nevermind I followed the debugging guide and manage to find the solution. 
https://www.gatsbyjs.org/docs/debugging-the-build-process/
Thanks anyway 😄

**Comment by afleischer** [comment]
Hi @shabith, would you kindly let the world know what the solution was?
