### ISSUE TITLE
Best way to use Apollo in Gatsby 

### ISSUE THREAD

**Issue by Alfrex92** [gatsbyjs/gatsby#10402]
Hi, 

I am learning Gatsby now and it looks pretty cool. 

I noticed that Gatsby is using Redux. What if I want to use Apollo? What would be the best way to manage state in Gatsby? Only Redux or Apollo + Redux? 

Just trying to figure out the best way to use Gatsby.

Thanks :)

**Comment by LekoArts** [comment]
> I noticed that Gatsby is using Redux. What if I want to use Apollo?

Gatsby uses Redux _under_ the hood, but it doesn't get shipped to your dev/production version. If you want to use Redux, you have to add it yourself - same with Apollo.

> What would be the best way to manage state in Gatsby? Only Redux or Apollo + Redux?

Gatsby is not different from any other React app, meaning that it does allow everything from the React ecosystem. You can use anything you want.

> Just trying to figure out the best way to use Gatsby.

If you're a beginner I'd say that you don't need Apollo or Redux, you can use [React Context](https://reactjs.org/docs/context.html) ;)

-----

Here are two links for Redux and Apollo:

- https://github.com/jlengstorf/gatsby-with-apollo
- https://www.gatsbyjs.org/starters?c=Redux&v=2

**Comment by Alfrex92** [comment]
Thanks 👍 

Trying Gatsby now :D

**Comment by LekoArts** [comment]
Great, have fun! 👍
