### ISSUE TITLE
How to get previous path in Gatsby

### ISSUE THREAD

**Issue by jeremylynch** [gatsbyjs/gatsby#10410]
`document.referrer` does not work in single-page-applications. So how can I get the last page/URL that a used has visited in Gatsby?

**Comment by shansmith01** [comment]
Someone may have a more elegant solution that uses reach router, but I have passed the previous pages url via state. [Here is some documentation ](https://www.gatsbyjs.org/docs/gatsby-link/#passing-state-through-link-and-navigate)

**Comment by jeremylynch** [comment]
This is how I solved the problem: 
```
exports.onRouteUpdate = () => {
  window.locations = window.locations || [document.referrer]
  locations.push(window.location.href)
  window.previousPath = locations[locations.length - 2]
}
```

Then `previousPath` can be accessed from anywhere.

**Comment by samajammin** [comment]
Thanks for sharing your solution @jeremylynch!

As an FYI for others, I believe you meant:
```
// gatsby-browser.js
exports.onRouteUpdate = () => {
  window.locations = window.locations || [document.referrer]
  window.locations.push(window.location.href)
  window.previousPath = window.locations[locations.length - 2]
}
```

**Comment by samblackk** [comment]
If you're having issues with duplicates in `window.locations` because of layout re-renders, this helps: 
```js
// gatsby-browser.js
exports.onRouteUpdate = () => {
  window.locations = window.locations || [document.referrer];
  if (window.locations[locations.length - 1] !== window.location.href) {
    window.locations.push(window.location.href);
  }
  window.previousPath = window.locations[locations.length - 2];
}
```

**Comment by SivaGanesh56** [comment]
now gatsby has support for location and prevLocation
`exports.onRouteUpdate = ({location, prevLocation}) => {}`
