### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by jpomykala** [gatsbyjs/gatsby#10413]
```
yarn run v1.12.3
$ gatsby develop
success open and validate gatsby-configs — 0.005 s
success load plugins — 0.145 s
error Plugin gatsby-plugin-manifest returned an error
Error: dlopen(/Users/xxxxxxx/Workspace/xxxxxxx/node_modules/sharp/  build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
    Referenced from: /Users/xxxxxxx/Workspace/xxxxxxx/node_modules/s  harp/build/Release/sharp.node
    Reason: image not found

```

Which image? Where I should start looking for the problem?

**Comment by shansmith01** [comment]
Some more info would be useful. I would consider removing issue and reposting again following the guidelines so people can help you as quickly as possible

**Comment by jpomykala** [comment]
I agree Gatsby should return more info about this error 😉

**Comment by shansmith01** [comment]
No I mean can you provide more info. Maybe you would like to link to your repo and follow the instruction when filling out a ticket....



## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

**Comment by ivorpad** [comment]
Try removing `.cache` with `rm -rf .cache`, also remove `package.json` and run `yarn install` again.

**Comment by 0x80** [comment]
Removing yarn.lock wasn't required for me to solve this. What I did was:

```cli
rm -rf .cache
yarn install --force
gatsby-dev
```

**Comment by jpomykala** [comment]
@shansmith01 
I know, the main problem with this issue is that I cannot fix this on my own because Gatsby is returning very little information about this error. Reason `image not found` is definitely not enough to even try to find the error on my own.
