### ISSUE TITLE
[docs] - reference guide on "Building an e-commerce site"

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#10418]
## Issue Context

This issue's purpose is to fill out highly-requested stub articles in Gatsby docs.

### Motivation

We are doing this because many people have requested docs which have then been turned into stub articles. In order to fill people's needs, we need to complete the stub articles.

### Review the Gatsby docs approach

- [ ] Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
  - Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
  - Docs Templates: https://www.gatsbyjs.org/contributing/docs-templates/
  - Example of a similar article: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-site-with-authentication.md

### Draft the doc

- [ ] Open the stub article with the same title referenced in this issue. The stub article exists in the /docs/ folder here: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-an-e-commerce-site.md
- [ ] Write the doc and follow the format listed in these resources:
  - Docs Templates: https://www.gatsbyjs.org/contributing/docs-templates/
  - Example of a guide to imitate: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-site-with-authentication.md
- [ ] Add the stub to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the "Use cases with Gatsby" section.

### Open a pull request
- [ ] Open a pull request with your work, including the words "closes #[this issue number]" in the pull request description.

**Comment by lannonbr** [comment]
So there is a E-Commerce tutorial in the docs as well as some videos about making an ecommerce site by @jlengstorf on his twitch stream, so is the structure for this page to have a possible condensed format to guide people on what is available for ecommerce and then link to these various resources?

**Comment by lannonbr** [comment]
For reference:

* E-Commerce Tutorial in Docs: https://www.gatsbyjs.org/docs/ecommerce-tutorial/
* YouTube archive of Jason's stream about building a store with Gatsby and Stripe: https://www.youtube.com/watch?v=g4aCBNt5Pcg

**Comment by jlengstorf** [comment]
The tricky part with e-commerce is that there are so many ways to solve this problem and all of them (or at least the vast majority of them) rely on third-party software like Stripe and Shopify.

We’d probably need something more intense here, similar to the [Headless CMS docs](https://www.gatsbyjs.org/docs/headless-cms/), so we can provide a general overview and then list a few options.

**Comment by jlengstorf** [comment]
@sourabh1031 I know we'd love to have the help. 😄 

Did you want to write an overview of e-commerce in Gatsby? That would be a big help.

Thank you!

**Comment by DoctaRay** [comment]
@jlengstorf , is this issue still relevant to work on? I would like to work on it but I don't know what to add. The e-commerce tutorial looks pretty comprehensive already. Would adding some blog references help? 
Also as a side request, would it be possible to work on the starter template itself? I would like to make it look a bit "prettier" if that's ok!

**Comment by jlengstorf** [comment]
@DoctaRay I _think_ this issue might be resolved. @marcysutton can give us a more authoritative answer here.

Regarding styles, we try to keep the starters pretty simple, but we'd love to get a new starter from you and/or a [theme](https://www.gatsbyjs.org/docs/themes/introduction/) that adds more styles.

Thanks!

**Comment by marcysutton** [comment]
The advanced e-commerce tutorial looks limited to Stripe (and will be moved to Tutorials > Advanced soon). To satisfy this issue, we could create a higher-level e-commerce section (potentially) with multiple docs reference guides in it.

Some relevant learning information to consider: tutorials provide step-by-step guidance, while docs reference articles (soon to be called "Reference Guides") are more general in nature. We do need some reference doc material on e-commerce, similar to the Headless CMS docs like @jlengstorf mentioned but outlining the various e-commerce options in Gatsby. Depending on the amount of content, it could either be a single e-commerce reference page or, more likely, a high-level landing page with child pages for each relevant technology or technique. If someone would like to pick that up as part of this issue, I do think it would be useful!

**Comment by marcysutton** [comment]
Something I'm noticing: it would be really great to have a reference guide on setting up Gatsby with Shopify! As a new Shopify Partner I have no idea what I'm doing...and I'm finding it difficult to understand how to set up a brand-new store (does it have to be public? What API key do I use?). The starter and plugin assume you already use Shopify, and this seems like a use case other people would run into as well.

For an e-commerce section of the Gatsby docs, it would be awesome to list a few options and lead to more specific use case guides (to which we could add on as time goes by)...I could see those docs being extremely useful when building sites for clients.

**Comment by jlengstorf** [comment]
This is a good idea, @marcysutton. I can put this on my list after the plugin course if no one beats me to it. 😄

**Comment by kevee** [comment]
Started a shopify doc here: https://github.com/kevee/gatsby/blob/docs/shopify-10418/docs/docs/building-an-ecommerce-site-with-shopify.md

**Comment by marcysutton** [comment]
I just saw your comment, @kevee -- can you open a PR with that Shopify guide? That would be amazing. We want to add a section under [Adding Website Functionality](https://gatsbyjs.org/docs/adding-website-functionality/) for "Building for E-Commerce" or something similar, and this guide could go inside of that.

**Comment by marcysutton** [comment]
We can now close this doc, as the E-commerce section is represented in the docs with a Shopify Guide (thanks again, @kevee!). Additional guides should be added through new issues. Thanks all!
