### ISSUE TITLE
[wordpress-source-plugin] Self Tag is not returning proper URL

### ISSUE THREAD

**Issue by zgriesinger** [gatsbyjs/gatsby#10427]
## Description
I have two apps Using Gatsby JS and the Wordpress-Source-Plugin. One of them is working just fine authenticating and loading the proper WP routes into the GraphQL Schema. This one was created a year or more ago. I also have a newer Wordpress blog that I am using as a data source, however when Authenticating this one I am seeing issues in the Schema. The default route here:
 https://public-api.wordpress.com/wp/v2/sites/[WORDPRESS-BLOG]
Normally returns data like this:
```json
{
  "namespace": "wp\/v2",
  "routes": {
    "\/wp\/v2\/sites\/WORDPRESSBLOG\/posts": {
      "namespace": "wp\/v2",
       ...
      "_links": {
        "self": "https:\/\/public-api.wordpress.com\/wp\/v2\/sites\/WORDPRESSBLOG\/posts"
      }
   ...
}
```

However, in my case, on the newly created Wordpress blog, the default indexing path is returning `https://public-api.wordpress.com/` for EVERY Self property.

This could be a bug on Wordpress's Side, but the fix for me for now was to change the `getRawEntityType` function in `fetch.js` to this:

```javascript
const getRawEntityType = route => route.substring(route.lastIndexOf(`/`) + 1, route.length);
```

While also passing in the path Key to that function on line 615 again in `fetch.js`
```javascript
const entityType = getRawEntityType(key) // Excluding the "technical" API Routes
```
I can provide a PR with this fix if it is valid, but I could just be missing something simple.
### Steps to reproduce
1. Create a new Wordpress Blog, file an API key for it to be able to query things like Media Routes
2. Add the `wpcom_app_clientSecret`, `wpcom_app_clientId`, `wpcom_user`, `wpcom_pass` to `gatsby-config.js` under the Wordpress plugin.
2. Run `gatsby develop` 

### Expected result

The `gatsby-source-wordpress` plugin should pull all data from the routes provided by ` https://public-api.wordpress.com/wp/v2/sites/[WORDPRESS-BLOG]`

### Actual result

Gatsby loads all of the routes from the same URL, if the self key is not correctly representing the key.

### Environment

```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.66 => 2.0.66
    gatsby-image: ^2.0.20 => 2.0.20
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12
    gatsby-plugin-offline: ^2.0.15 => 2.0.19
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12
    gatsby-plugin-typography: ^2.2.1 => 2.2.1
    gatsby-source-filesystem: ^2.0.12 => 2.0.12
    gatsby-source-wordpress: ^3.0.20 => 3.0.20
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8
```

**Comment by lukemorton** [comment]
I can confirm this is happening for me too. The WordPress.com REST API v2 returns a different `self` reference for an older site compared to a newer one.

Old:
```"self": "https://public-api.wordpress.com/wp/v2/sites/$site/users/me"```

New:
```"self": "https://public-api.wordpress.com/"```

**Comment by pieh** [comment]
Please check this comment - https://github.com/gatsbyjs/gatsby/pull/10624#issuecomment-450440832 for update on the issue - there is open PR but it has some problems for non-wp.com + it really does look like bug on wp.com rest endpoints. In the comment there is link to alternative version of the wordpress plugin that works with those weird wp.com responses in case this blocks you currently
