### ISSUE TITLE
Google Analytics Plugin Caching Calls

### ISSUE THREAD

**Issue by GiraffeCoding** [gatsbyjs/gatsby#10423]
## Description

On every page load the Google Analytics calls seem to be getting cached which is adding around 7-10mb worth of unnecessary data to the cache. I've followed the steps in the tutorial on the main docs and cannot seem to figure out this bug. An example of the calls:
<img width="1164" alt="screenshot 2018-12-12 at 00 09 25" src="https://user-images.githubusercontent.com/12425975/49838656-98366b80-fda3-11e8-8ca5-569b1e4a4984.png">

### Steps to reproduce

You can see a live example at https://www.woodnookchippy.co.uk

### Expected result

These calls should not be getting cached.

### Actual result

These calls were cached. 

### Environment

Website is hosted on gh-pages

Here is my package json file:
```
{
  "name": "chippy-site",
  "description": "New Website",
  "version": "1.0.1",
  "author": "Ben McDonough",
  "dependencies": {
    "bootstrap": "^4.1.3",
    "bulma": "^0.7.2",
    "gatsby": "^2.0.57",
    "gatsby-image": "^2.0.5",
    "gatsby-plugin-google-analytics": "^2.0.5",
    "gatsby-plugin-manifest": "^2.0.7",
    "gatsby-plugin-offline": "^2.0.0-rc.9",
    "gatsby-plugin-react-helmet": "^3.0.0-rc.1",
    "gatsby-plugin-sass": "^2.0.0-rc.2",
    "gatsby-source-filesystem": "^2.0.12",
    "gatsby-transformer-remark": "^1.7.44",
    "gatsby-transformer-sharp": "^2.1.9",
    "node-sass": "^4.9.4",
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-helmet": "^5.2.0",
    "react-lazyload": "^2.3.0",
    "reactstrap": "^6.5.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write '**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1",
    "deploy": "gatsby build --prefix-paths && gh-pages -d public"
  },
  "devDependencies": {
    "gh-pages": "^1.2.0",
    "prettier": "^1.14.3",
    "react-mason": "^1.1.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/giraffecoding/"
  }
}

```
and my config file:
```
module.exports = {
  siteMetadata: {
    title: 'Woodnook Chippy',
    description: 'Woodnook Chippy - Fish and Chips'
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'gatsby-starter-default',
        short_name: 'starter',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/gatsby-icon.png', // This path is relative to the root of the site.
      },
    },
    'gatsby-plugin-offline',
    'gatsby-transformer-remark',
    `gatsby-plugin-sass`,
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: `UA-XXXXXXXX-X`,
        head: true,
      },
    },
  ],
}

```

I'm not sure how or why these calls are getting cached but any help with this would be greatly appreciated.

Thank you in advance for your time and efforts

**Comment by sidharthachatterjee** [comment]
Calls to the Google Analytics `/collect` API return a `gif` and are being cached because the default workbox config in `gatsby-plugin-offline` caches `gif` files at runtime 

You can override the default options in `gatsby-config.js`. Look at `urlPattern` under `runtimeCaching`

Check out the docs at 
- https://www.gatsbyjs.org/packages/gatsby-plugin-offline/
- https://developers.google.com/web/tools/workbox/modules/workbox-build

Closing this for now since it has to do with Workbox options but please feel free to reopen if there is anything else

**Comment by GiraffeCoding** [comment]
How is Gatsbyjs.org site excluding these files then? They don't appear to be doing anything other than default setup

**Comment by sidharthachatterjee** [comment]
I just took a look and the only differences are 
- Gatsby site uses a more recent version of the offline plugin
- Your configuration for google analytics plugin includes `head` (don't think this is relevant)

Can you update to the latest version and see if it still occurs? I can't seem to see any calls to GA from the live site you linked to 

Can you post a minimal reproduction repo if possible?

**Comment by GiraffeCoding** [comment]
Oh I removed it for the time being as the cache was causing major issues for the browser. I will update to the latest version tonight and retry. If i get the same error I will produce a repo for you.

Thank you so much for your quick response
