### ISSUE TITLE
Stub articles

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#10449]
## Overview
The purpose of this epic is to help the community finish writing stub articles (stub articles are ideas we have for articles that have not yet been written). The stub article ideas came out of user research, including discussions on Twitter, Discord, this repo, interviews, and usability tests.

I will be adding more issues to this epic as quickly as they get picked up. 

## Where to put stub articles in the sidebar
Each stub article, once finished, needs to be added to [`doc-links`](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml). 
Here is a link to a commit that shows where the stub articles ought to go: https://github.com/gatsbyjs/gatsby/commit/0aade74a1862f7be9875e8f3d84eb049de132c10?diff=unified

**Comment by ashleymavericks** [comment]
I am interested in doing this.

**Comment by shannonbux** [comment]
Apologies @ashleymavericks for not seeing this earlier! I recently put some github filters into my email and was able to uncover a few that I missed. This epic got finished; if you're interested in documentation issues, try filtering for issues labelled "documentation" and "good first issue" if you're new to the Gatsby github repo!
