### ISSUE TITLE
Stub article - "Building an image heavy site"

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#10448]
## Issue Context

This issue's purpose is to fill out highly-requested stub articles in Gatsby docs.

### Motivation

We are doing this because many people have requested docs which have then been turned into stub articles. In order to fill people's needs, we need to complete the stub articles.

### Review the Gatsby docs approach

- [ ] Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
  - Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a similar article: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-site-with-authentication.md

### Draft the doc

- [ ] Open the stub article with the same title referenced in this issue. The stub article exists in the /docs/ folder here: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-an-image-heavy-site.md
- [ ] Write the doc and follow the format listed in these resources:
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a guide to imitate: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-site-with-authentication.md
- [ ] Add the stub to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the "Use cases with Gatsby" section.

### Open a pull request
- [ ] Open a pull request with your work, including the words "closes #[this issue number]" in the pull request description.

**Comment by lannonbr** [comment]
Hey @shannonbux, for this issue, would the content of this document focus around the positive use cases of developing sites that use the gatsby-ecosystem for displaying images (mainly with the Gatsby <Image> component and the sharp library?) Is that likely the focus on this?

If such, I would be interested in tackling this. I develop a blog on VS Code, [vscode.rocks](https://vscode.rocks) which is reasonably image-heavy.

**Comment by shannonbux** [comment]
Hi! The purpose of this doc would be to help people solve the two problems
usually associated with image-heavy sites:
1. Large images make the experience for website visitors less-than-ideal
(because images sometimes load slowly and load in a visually unappealing
way by making items on the page jump around and/or loading in a choppy way)
2. A large site (which can happen for many reasons, though images are an
easy to way to quickly put together a very large site) has a slower build
time, which is a disadvantage for development.

Also, we have a bit of overlap in our image documentation and any amount of
reorganization, cleanup, renaming things or combining docs that you can
think of could also be equally valuable!

Addressing how to solve either or both of these problems would be super
valuable. Forgive me if I explained anything incorrectly; still learning
the vocabulary for some of these things even though I understand them
conceptually!

**Comment by lannonbr** [comment]
Okay. I understand that. Thanks @shannonbux. I will assign myself and will put some work into drafting something up and then I can push a PR up and get some feedback on if it is the right direction for this.

**Comment by DoctaRay** [comment]
Hi there! Is this request still available? I've worked on image-heavy sites before which I think would aid in creating content for this tutorial.

**Comment by yakovleva-tanya** [comment]
Hi, I would like to work on this one, is it still available?

**Comment by bingr001** [comment]
HI I would like to help with this one if available?

**Comment by laurieontech** [comment]
Hey @yakovleva-tanya, we'd love to have you work on this issue! If you're no longer interested or able please let me know as someone else has expressed interest. Thanks so much.
