### ISSUE TITLE
Stub article - "Building a portfolio"

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#10446]
## Issue Context

This issue's purpose is to fill out highly-requested stub articles in Gatsby docs.

### Motivation

We are doing this because many people have requested docs which have then been turned into stub articles. In order to fill people's needs, we need to complete the stub articles.

### Review the Gatsby docs approach

- [ ] Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
  - Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a similar article: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-site-with-authentication.md

### Draft the doc

- [ ] Open the stub article with the same title referenced in this issue. The stub article exists in the /docs/ folder here: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-portfolio.md
- [ ] Write the doc and follow the format listed in these resources:
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a guide to imitate: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-site-with-authentication.md
- [ ] Add the stub to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the "Use cases with Gatsby" section.

### Open a pull request
- [ ] Open a pull request with your work, including the words "closes #[this issue number]" in the pull request description.

**Comment by steoneill** [comment]
@shannonbux  i'll take this if you want to assign it over? :)

**Comment by shannonbux** [comment]
@steoneill! I just saw this; I must have missed it while we were at our company summit; I've since set up my gmail filters so I don't miss any more!

If you're still available to take this, go for it!
