### ISSUE TITLE
CSS acts differently with develop vs build

### ISSUE THREAD

**Issue by indirecthit** [gatsbyjs/gatsby#10442]
I'm currently trying to have different CSS files for each page on my site. When using `gatsby develop` the CSS is loaded globally across all pages. When I use `gatsby build` then serve, it loads the right CSS for that page. 

CSS modules is acting in a similar fashion. Any advice?

**Comment by sidharthachatterjee** [comment]
Hey @indirecthit 

Can you please add a minimal reproduction repo?
