### ISSUE TITLE
Stub article - "Building a site with asynchronous data"

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#10445]
## Issue Context

This issue's purpose is to fill out highly-requested stub articles in Gatsby docs.

### Motivation

We are doing this because many people have requested docs which have then been turned into stub articles. In order to fill people's needs, we need to complete the stub articles.

### Review the Gatsby docs approach

- [ ] Read the Style Guide and follow it in order for your PR to be accepted. Pay special attention to the templates. 
  - Style Guide: https://www.gatsbyjs.org/docs/gatsby-style-guide/
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a similar article: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-site-with-authentication.md

### Draft the doc

- [ ] Open the stub article with the same title referenced in this issue. The stub article exists in the /docs/ folder here: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-site-with-asynchronous-data.md
- [ ] Write the doc and follow the format listed in these resources:
  - Docs Templates: https://www.gatsbyjs.org/docs/templates/
  - Example of a guide to imitate: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-site-with-authentication.md
- [ ] Add the stub to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the "Use cases with Gatsby" section.

### Open a pull request
- [ ] Open a pull request with your work, including the words "closes #[this issue number]" in the pull request description.

**Comment by V1shvesh** [comment]
Hey @shannonbux!,
Can I work upon this issue?

**Comment by shannonbux** [comment]
Hi @V1shvesh! I am so sorry for responding late! I must have missed this during the holidays and I just improved my email system for github notifications and found this. If it's still good timing for you, go ahead and take this issue! And in the future, feel free to just claim an issue and mention the PR number so no one accidentally starts working on the same issue as you :)

**Comment by V1shvesh** [comment]
@shannonbux, great! I'll start working on it

**Comment by V1shvesh** [comment]
https://www.gatsbyjs.org/docs/gatsby-style-guide/#use-you-as-the-pronoun

A very wholesome detail to be considered indeed! :grin:

**Comment by V1shvesh** [comment]
Hey @shannonbux!
So I've read the style guide meant for the article.

I'd like to know more about the topics to be addressed in this article. Should it include one example for just the `createPages` API? Or should we also talk a bit about GraphQL?

**Comment by V1shvesh** [comment]
Hey @shannonbux!
So I've read the style guide meant for the article.

I'd like to know more about the topics to be addressed in this article. Should it include one example for just the `createPages` API? Or should we also talk a bit about GraphQL?

**Comment by shannonbux** [comment]
Hm, I can't remember who requested this issue. Let me loop in @amberleyromo and @marcysutton to see if they can guess what this stub article should be about.

**Comment by marcysutton** [comment]
> I'd like to know more about the topics to be addressed in this article. Should it include one example for just the `createPages` API? Or should we also talk a bit about GraphQL?

It looks like this stub doesn't exist yet in the sidebar, so we could decide where it goes (and what goes on it)? I think having an example with the `createPages` API *and* stuff about GraphQL would be really helpful when building a Gatsby site. I would recommend the "Sourcing content and data" section in the docs, but it could potentially go somewhere else too. 

There's this page in the sourcing section: https://www.gatsbyjs.org/docs/sourcing-from-private-apis/
There is also this page in the GraphQL section: https://www.gatsbyjs.org/docs/programmatically-create-pages-from-data/

**Comment by V1shvesh** [comment]
Yup, saw those pages. I'll create a draft taking all this into account. 

I believe the "Sourcing content and data" section is already pretty much thorough. I'll look around if I can find any other articles/tutorials that can be referred.

What I can't seem to decide upon are the code snippets (not already included in the "Sourcing content and data" section) that can be included in this article.

**Comment by shannonbux** [comment]
Someone requested this doc about a year ago, and unfortunately we didn't
keep a good record of their reason for requesting it. So if it's covered in
another doc, then the question would be whether to pull that information
out and put it in its own doc here, or leave it where it is!

**Comment by V1shvesh** [comment]
Hey @shannonbux! Apologies for not replying sooner.

I was going through the docs and I'd like to clarify a doubt.

Since Gatsby generates static sites, we can't have dynamically sourced content. So I just wanted to make sure that by "async data", do we really mean data sourced from APIs at build time? Or handling frequently changing data at runtime ([first point under Other Considerations](https://www.gatsbyjs.org/docs/sourcing-from-private-apis/#other-considerations))?

**Comment by shannonbux** [comment]
Hello! I will refer you to @marcysutton who is now handling questions about
Gatsby docs!

**Comment by marcysutton** [comment]
@V1shvesh I assume it referred to sourcing data from APIs at build time. That would create a site with server-rendered pages, which is a huge selling point for Gatsby.
