### ISSUE TITLE
Images scale, query and <Img />

### ISSUE THREAD

**Issue by enzoferey** [gatsbyjs/gatsby#10467]
## Summary

I'm currently moving a plain HTML website to Gatsby and I wonder how I should move responsive images that use multiple scales (`@1x`, `@2x`, `@3x`, `@4x`) to use the `<Img />` component.

## Explanation

The images currently look like this:

```html
<img
    src="mySrcFallback"
    srcset="mySrcSetWithTheFourDifferentScales"
    sizes="(min-width: 1200px) 50vw, 30vw"
/>
```

I'm aware of the different query variables such as `width` or `maxWidth` and the `fluid` vs `fixed` types, however should I just serve the `@4x` image and expect Gatsby to do the heavy lifting for me ? Not sure how the `sizes` attribute could be translated neither.

On the [docs](https://www.gatsbyjs.org/packages/gatsby-image/) it states 

> Generate multiple smaller images so smartphones and tablets don’t download desktop-sized images

So I guess only serving the `@4x` image is fine, but what about the `sizes` attribute ? I guess if I set the image type to `fluid` it could handle it ?

Thank you very much !

**Comment by LekoArts** [comment]
> So I guess only serving the @4x image is fine, but what about the sizes attribute ? I guess if I set the image type to fluid it could handle it ?

Exactly. The [sharp documentation](https://www.gatsbyjs.org/packages/gatsby-plugin-sharp#fluid) also explains it a bit.

Take your `@4x` images, query them by GraphQL (with `fluid` and the right `maxWidth` & `quality` setting), pass that to your `<Img fluid={your.query.fluid} />` (gatsby-image) and it handles everything for you.

**Comment by enzoferey** [comment]
Love it ! Such a nice framework 😍 

Thank you and have a nice day 🚀
