### ISSUE TITLE
Catch data access errors from gatsby-node.js (`cannot read property VAR_NAME of undefined`) that are from GraphQL calls and show prettier error with link to try the query in graphiql

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#10463]
When users are trying to create pages in Gatsby by querying graphql data and then using the queried data, they frequently can get stymied by obscure GraphQL-related errors. These are difficult to understand on their own merits and can be especially difficult to fix as the cycle for fixing them is slow as each attempt at fixing errors means restarting the `gatsby develop` process.

An example of this:

![duv6zwjwsaaejq9](https://user-images.githubusercontent.com/71047/49979424-bfa44a00-ff03-11e8-89f8-e2610d2cd011.jpg)

![screen recording 2018-12-14 at 02 16 am](https://user-images.githubusercontent.com/71047/49979426-c337d100-ff03-11e8-99a8-4ea872cc7976.gif)

We should a) catch errors from plugins and detect if they're a GraphQL related error (and re-throw if not) and b) print out a better error which clearly points to their graphql query as the fault (or other possible problems) and generally points them to trying to debug the query in graphiql once the gatsby develop process starts.

**Comment by aamorozov** [comment]
If it's helpful, another example error from [gatsby-source-graphql](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-graphql) plugin 

```

**Comment by KyleAMathews** [comment]
@aamorozov that's definitely something that needs fixed as well /cc @freiksenet

Could you file another issue for it however as it has a different root cause / needed fix than this issue.

**Comment by deammer** [comment]
@KyleAMathews I apologize for reviving this thread but was any work done against this issue before it was moved to "Done"? I'm asking because I'm running into problems with `gatsby-source-wordpress`:

```shell
error Plugin gatsby-source-wordpress returned an error
  TypeError: Cannot read property 'data' of undefined
```

I definitely think this could be handled better in that plugin's code, but I also see value in improving the error handling in gatsby-node, if possible.

**Comment by raydot** [comment]
Agreed!  Similar error, having a pretty tough time debugging.

**Comment by mafrosis** [comment]
The debug experience with Gatsby and graphql errors is terrible! Work on this front would definitely make gatsby more accessible to non-nodejs experts
