### ISSUE TITLE
How to load external js for styling the component which is locally developed

### ISSUE THREAD

**Issue by diana4397** [gatsbyjs/gatsby#10464]
Hello,
I want to style my component and I want to load the js file for it which is locally developed how to load it using gatsby ?
Is there any way

**Comment by diana4397** [comment]
Hi, 
I have custom.js file in my js folder and I want to load that file. 
Custom.js file contains the jquery data and styling components. 
How to call that file in Gatsby?

**Comment by sidharthachatterjee** [comment]
Hi @diana4397 

You should be able to import a JavaScript file the regular way using `import file from path`. If you're trying to load an arbitrary JavaScript file on the client side, you can add it to `html.js` as a custom script tag. 

Take a look at https://www.gatsbyjs.org/docs/custom-html/

In case I'm misunderstanding your question, please let me know. You can also link to the source code if you like so we understand your issue better. 

Thanks!

**Comment by diana4397** [comment]
Hi,
Can you explain the pros and cons of gatsby and angularjs.
I am just curious to know the difference between gatsbyjs and angularjs

**Comment by diana4397** [comment]
Hi, For above solutions,thanks a lot @sidharthachatterjee . It worked for me

**Comment by sidharthachatterjee** [comment]
@diana4397 It would be difficult to compare Gatsby and Angular since Gatsby is a static side generator and Angular is a UI framework. On that note, Gatsby uses React under the hood. 

I'm glad your issue is resolved. May I close this issue?
