### ISSUE TITLE
How to split base-64 images into page specific bundles?

### ISSUE THREAD

**Issue by lbittner-pdftron** [gatsbyjs/gatsby#10479]
Hello!

When I build my Gatsby website, it looks like all the images (less than 10kb) from all my pages are getting inlined and bundled into the main bundle. This means that when _any_ page is loaded, i'm loading the base-64 images for every other page on my site. This also means my main application bundle is very big (2mb).

All my pages basically just consist of a JSON file that determines the page layout. This JSON is passed as a prop to a React Component that renders other components based on the contents of the JSON. 

Here's an example of what most of my pages consist of.

```js
import React from 'react';
import Layout from './layout.json';
import JSONToReact from '../../components/JSONToReact';

export default () => <JSONToReact layout={Layout} />
```

This `JSONToReact` component renders react components based on the contents of the `layout` prop. This means that it needs to dynamically require images, like so:

```js
// JSONToReact.js
...
// render
this.props.layout.images.map(src => {
   return <img src={require(`../../assets/${src}`)} />
})

```

Now, when I build my website and inspect the bundle, I see that all of these images are written in base-64 in the main bundle. 

![image](https://user-images.githubusercontent.com/30271920/50033434-609b0f80-ffad-11e8-9ee4-426488b56e81.png)

My question is, is there a way to split these images out per-page? For example, it would be ideal if my `/customers` page could have its own bundle with only the images required for that page inside it.

**Comment by KyleAMathews** [comment]
So you're not using Gatsby's normal way of creating pages?

If you do that, Gatsby generates bundles for each page automatically for you.

**Comment by lbittner-pdftron** [comment]
I am, yes. Each file in `./src/pages` exports a React component as the docs state. These components just happen to look like 

```js
import React from 'react';
import Layout from './layout.json';
import JSONToReact from '../../components/JSONToReact';

export default () => <JSONToReact layout={Layout} />
```

**Comment by jgierer12** [comment]
Calling [`require()` with an expression](https://webpack.js.org/guides/dependency-management/#require-with-expression) includes all matching files in the main bundle.

You'll want to use the [`import()` syntax](https://webpack.js.org/guides/dependency-management/#require-with-expression) instead, which splits the matching files off into separate bundles. That's not *exactly* what you're asking for (since the images will be separate from the page bundles) but it's the closest thing possible in webpack right now.
