### ISSUE TITLE
CSS broken on some Createpages in Develop only

### ISSUE THREAD

**Issue by shansmith01** [gatsbyjs/gatsby#10472]
When in development mode, a certain bunch on pages created with createpage appear broken. The site when viewed in production looks perfect

All other pages appear fine in dev mode look okay. When navigating to a "hostel page" the site will appear broken. Then clicking a link to a new page or the previous page the next page will then be broken as well Refreshing fixes the working page.

See a gif demo here http://recordit.co/MsmEUwaW2b.gif

Additional info:
- I have run from a clean browser
- tested in browsers other than chrome
- Deleted .cache
- Site uses styled compnents with a Globalstyles.js comonent using createGlobalStyle

### Steps to reproduce

- Install repo here https://github.com/shansmith01/base-test
- run gatsby develop
- Open home page and navigate to http://localhost:8000/hostels/base-backpackers-sydney/
- return to the home page to see it broken as well

### Expected result

The page should look like this 

<img width="1263" alt="screen shot 2018-12-14 at 12 32 25 pm" src="https://user-images.githubusercontent.com/1866452/50020705-748a4580-ff9c-11e8-8b18-55fa5c264816.png">

### Actual result

<img width="1267" alt="screen shot 2018-12-14 at 12 33 48 pm" src="https://user-images.githubusercontent.com/1866452/50020743-8d92f680-ff9c-11e8-93ad-d25c96b8e45a.png">

### Environment

  System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 63.0
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.67 => 2.0.67 
    gatsby-image: ^2.0.25 => 2.0.25 
    gatsby-plugin-canonical-urls: ^2.0.8 => 2.0.8 
    gatsby-plugin-eslint: ^1.0.3 => 1.0.3 
    gatsby-plugin-google-tagmanager: ^2.0.7 => 2.0.7 
    gatsby-plugin-manifest: ^2.0.12 => 2.0.12 
    gatsby-plugin-netlify: ^2.0.6 => 2.0.6 
    gatsby-plugin-offline: ^2.0.19 => 2.0.19 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.4 
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0 
    gatsby-plugin-remove-trailing-slashes: ^2.0.6 => 2.0.6 
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0 
    gatsby-plugin-sentry: ^0.1.0 => 0.1.0 
    gatsby-plugin-sharp: ^2.0.15 => 2.0.15 
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3 
    gatsby-plugin-stripe-checkout: ^1.1.2 => 1.1.2 
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4 
    gatsby-plugin-twitter: ^2.0.8 => 2.0.8 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.3 => 1.0.3 
    gatsby-source-datocms: ^2.0.1 => 2.0.1 
    gatsby-source-filesystem: ^2.0.12 => 2.0.12 
    gatsby-transformer-react-docgen: ^2.1.3 => 2.1.3 
    gatsby-transformer-remark: ^2.1.15 => 2.1.15 
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9 
  npmGlobalPackages:
    gatsby-cli: 2.4.6

**Comment by m-allanson** [comment]
Hey @shansmith01 I just tried to run `gatsby develop` on your repo and am getting a 500 error from DatoCMS:

```
> gatsby develop

success open and validate gatsby-configs — 0.007 s
warning Plugin gatsby-plugin-webpack-bundle-analyzer is not compatible with your gatsby version 2.0.64 - It requires gatsby@next
success load plugins — 0.218 s
success onPreInit — 0.672 s
success delete html and css files from previous builds — 0.042 s
success initialize cache — 0.012 s
success copy gatsby files — 0.032 s
success onPreBootstrap — 0.004 s
error Plugin gatsby-source-datocms returned an error


  ApiException: 500 Internal Server Error

# etc... 
```

Is that something you're seeing on your side too?

**Comment by shansmith01** [comment]
working for me. Maybe Dato was down for a bit

**Comment by shansmith01** [comment]
Issue was related to a bug in a styled component that was not triggering eslint or causing build to fail
