### ISSUE TITLE
[gatsby-link] | Add onMouseLeave prop

### ISSUE THREAD

**Issue by aamorozov** [gatsbyjs/gatsby#10477]
## Summary

Currently, it's possible to pass `onMouseEnter` but not `onMouseLeave`. Would be nice to add this option. I will work on the pr tonight. 
https://github.com/gatsbyjs/gatsby/blob/0514b7d2532c60c09efc42567d9178ef0396ee27/packages/gatsby-link/src/index.js#L116

### Basic example

```

class EnhancedLink extends Component {
    state={active: false}
    handleMouseEnter = () => this.setState({active: true}) 
    handleMouseLeave = () => this.setState({active: false}) 
    render() {
      return (
        // Link here is essentially a wrapper around gatsby link with an identification of external/internal link
        <Link
            href={`${url}`}
            style={{
                 background: this.state.active ? 'green' : 'yellow'
            }}
            onClick={this.handleClick}
            onMouseEnter={this.handleMouseEnter} // currently possible 
            onMouseLeave={this.handleMouseLeave} // not currently possible
     )}
}
```

### Motivation

I think it will be beneficial to the end user to be able to handle both states directly from the props that are being passed to Link component, versus creating additional wrappers around gatsby link.

**Comment by jgierer12** [comment]
As I said in #10489, this should already work - see [this demo](https://condescending-boyd-451435.netlify.com/) ([Source](https://github.com/jgierer12/gatsby-pr-10489-demo)).

Can you share a repo where your issue can be reproduced?

**Comment by aamorozov** [comment]
@jgierer12 
It does, not sure how I missed it's working without providing explicit prop 🤦‍♂️ .
