### ISSUE TITLE
Style gatsby-image <img> tag instead of wrapper using styled-components

### ISSUE THREAD

**Issue by robinmetral** [gatsbyjs/gatsby#10486]
Hi :wave: 

## Description

I'm running into problems trying to horizontally center a `gatsby-image` using `styled-components`.

### Expected result

I'd like to do this:

```javascript
import React from "react"
import { Img } from "gatsby-image"
import styled from "styled-components"

StyledImg = styled(Img)`
  display: block;
  margin: 0 auto;
`
```

And then render a `StyledImg` that would be horizontally centered within my parent container.

### Actual result

The problem is that the styles are being given to a wrapper div, which itself contains the traced SVG image and the `<picture>` tag.

I tried to make this wrapper a flexbox to center-align the children, but it was overridden with a `display: inline-block;`.

### Sources

Here's [the file on robinmetral/eaudepoisson](https://github.com/robinmetral/eaudepoisson/blob/master/src/components/Banner.js)

And [the demo on Netlify](https://eaudepoisson.netlify.com)

### Environment

    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.9.0/bin/npm
    Browsers:
      Chrome: 67.0.3396.87
      Firefox: 63.0.3
    npmPackages:
      gatsby: ^2.0.66 => 2.0.66 
      gatsby-image: ^2.0.23 => 2.0.23 
      gatsby-plugin-feed: ^2.0.11 => 2.0.11 
      gatsby-plugin-manifest: ^2.0.12 => 2.0.12 
      gatsby-plugin-offline: ^2.0.19 => 2.0.19 
      gatsby-plugin-react-helmet: ^3.0.4 => 3.0.4 
      gatsby-plugin-sharp: ^2.0.15 => 2.0.15 
      gatsby-plugin-styled-components: ^3.0.4 => 3.0.4 
      gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.7 
      gatsby-remark-images: ^2.0.4 => 2.0.6 
      gatsby-remark-prismjs: ^3.1.4 => 3.1.4 
      gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.7 
      gatsby-remark-smartypants: ^2.0.5 => 2.0.7 
      gatsby-source-filesystem: ^2.0.12 => 2.0.12 
      gatsby-transformer-remark: ^2.1.6 => 2.1.15 
      gatsby-transformer-sharp: ^2.1.3 => 2.1.9 
      gatsby-transformer-yaml: ^2.1.6 => 2.1.6 
    npmGlobalPackages:
      gatsby-cli: 2.4.6

**Comment by LekoArts** [comment]
Hi 👋 

You need to put an `!important` behind your `display: block`. Then it'll work. Your values get overwritten as gatsby's styles are _inline_

**Comment by jgierer12** [comment]
You can always style the `picture` tag directly by selecting it in your styled-component's CSS:

```javascript
import React from "react"
import { Img } from "gatsby-image"
import styled from "styled-components"

const StyledImg = styled(Img)`
  display: block;
  margin: 0 auto;

  picture {
    // picture styles
  }
`
```

But the better approach in this specific situation would probably be to create an additional wrapper around the `Img`:

```javascript
import React from "react"
import { Img } from "gatsby-image"
import styled from "styled-components"

const StyledImg = styled(Img)`
  display: block;
`

const Wrapper = styled.figure`
  display: flex;
  justify-content: center;
  align-items: center
`
```

**Comment by robinmetral** [comment]
Thanks for your quick replies!

@LekoArts good to know that I can use `!important` if I need to override Gatsby's styles :slightly_smiling_face: 

@jgierer12 I'm going for your second solution as I feel it's the cleanest. I can even omit the styles for the `<Img>` tag, making the container a flexbox was enough. Thought I'd tried that! Thank you :+1:
