### ISSUE TITLE
[Question] Can I ask why you prefer using template strings instead of general quote

### ISSUE THREAD

**Issue by ZYSzys** [gatsbyjs/gatsby#10484]
Just curious, can you please tell me why you prefer using template strings(``) instead of general quote('') in all of the codebase.

It's rare and weird for me to see that `require()` a module using template strings(``), are there some benefits from using template strings ?

## Summary
Just a simple question :)

**Comment by jgierer12** [comment]
Hi! Good question - here's an article on why template strings are always preferable: https://ponyfoo.com/articles/template-literals-strictly-better-strings

**Comment by ZYSzys** [comment]
@jgierer12 Thank you ~

**Comment by ZYSzys** [comment]
@jgierer12 Thanks for your explanation :)
