### ISSUE TITLE
Building fails under incredibly specific circumstances

### ISSUE THREAD

**Issue by dstaley** [gatsbyjs/gatsby#10480]
## Description

When the following conditions are true, Gatsby is unable to build the site, reporting GraphQL validation failures:

1. Use the latest version of `gatsby-remark-images` (`v3.0.1`).
1. Use the `gatsby-paginate` plugin with the suggested template.
1. Include the field `htmlAst` in the `createPages` query.
1. Have a markdown file containing specific content.

### Steps to reproduce

```bash
git clone https://github.com/dstaley/gatsby-starter-blog && cd gatsby-starter-blog
npm i && npm start
```

### Expected result

Gatsby builds the site and begins serving.

### Actual result

```
success open and validate gatsby-configs — 0.008 s
success load plugins — 0.286 s
success onPreInit — 1.662 s
success delete html and css files from previous builds — 0.195 s
success initialize cache — 0.012 s
success copy gatsby files — 0.090 s
success onPreBootstrap — 0.008 s
success source and transform nodes — 0.090 s
success building schema — 0.400 s
success createPages — 0.170 s
success createPagesStatefully — 0.035 s
success onPreExtractQueries — 0.004 s
success update schema — 0.178 s
error Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.


  Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
  Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
  Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

  - query-compiler.js:145
    [gatsby-md]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:14    5:44

  - Generator.next

  - debuggability.js:313 Promise._execute
    [gatsby-md]/[bluebird]/js/release/debuggability.js:313:9

  - promise.js:483 Promise._resolveFromExecutor
    [gatsby-md]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [gatsby-md]/[bluebird]/js/release/promise.js:79:10

  - query-compiler.js:213 Runner.write
    [gatsby-md]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:21    3:7

  - query-compiler.js:89
    [gatsby-md]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:89    :26

  - Generator.next


error UNHANDLED REJECTION


  Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
  Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
  Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.

  - query-compiler.js:145
    [gatsby-md]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:14    5:44

  - Generator.next

  - debuggability.js:313 Promise._execute
    [gatsby-md]/[bluebird]/js/release/debuggability.js:313:9

  - promise.js:483 Promise._resolveFromExecutor
    [gatsby-md]/[bluebird]/js/release/promise.js:483:18

  - promise.js:79 new Promise
    [gatsby-md]/[bluebird]/js/release/promise.js:79:10

  - query-compiler.js:213 Runner.write
    [gatsby-md]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:21    3:7

  - query-compiler.js:89
    [gatsby-md]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:89    :26

  - Generator.next
```

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - /usr/local/opt/node@8/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/opt/node@8/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.19 => 2.0.67
    gatsby-image: ^2.0.22 => 2.0.25
    gatsby-paginate: ^1.0.16 => 1.0.16
    gatsby-plugin-feed: ^2.0.8 => 2.0.11
    gatsby-plugin-google-analytics: ^2.0.5 => 2.0.8
    gatsby-plugin-manifest: ^2.0.5 => 2.0.12
    gatsby-plugin-offline: ^2.0.5 => 2.0.19
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.4
    gatsby-plugin-sharp: ^2.0.6 => 2.0.15
    gatsby-plugin-typography: ^2.2.0 => 2.2.2
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.7
    gatsby-remark-images: ^3.0.1 => 3.0.1
    gatsby-remark-prismjs: ^3.0.0 => 3.1.4
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.7
    gatsby-remark-smartypants: ^2.0.5 => 2.0.7
    gatsby-source-filesystem: ^2.0.2 => 2.0.12
    gatsby-transformer-remark: ^2.1.6 => 2.1.15
    gatsby-transformer-sharp: ^2.1.3 => 2.1.9
```

So, this one is a really tricky one. If any of the above stated conditions are false, the build succeeds. The weirdest aspect to me is that if the image filename is just one character longer (so 30 characters instead of 29), the build succeeds. I realize that this is an incredibly specific set of conditions, but it's the smallest reproduction of this issue that I could get my project down to.

**Comment by sidharthachatterjee** [comment]
Here is what is happening

- Adding `htmlAst` to the query results in it being in the result of course
- The result is passed onto `gatsby-paginate` which sets the `edges` on page context
- When gatsby tries to rebuild schema (after adding pages), the edges are in context (which is in the page payload)
- The AST for some reason includes `"": ""` (as a result of `hast-util-raw` when using gatsby-remark-prismjs or gatsby-remark-images, still not sure why)
- GraphQL requires all fields to have a key with a valid name (empty string is not valid) so this key breaks schema generation and hence the build fails

We've fixed this by making schema generation more defensive—we now ignore all keys which are empty strings (which surprisingly is valid JavaScript) 

Once a new version is published, please update and your issue will be resolved

**Comment by sidharthachatterjee** [comment]
This is now resolved in the latest release 🎉

**Comment by alexeychikk** [comment]
@sidharthachatterjee Just hit the same issue with `"gatsby": "^2.13.13"`

**Comment by alexeychikk** [comment]
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.106
    Firefox: 73.0
  npmPackages:
    gatsby: ^2.13.13 => 2.19.22
    gatsby-image: ^2.2.4 => 2.2.41
    gatsby-plugin-catch-links: ^2.1.0 => 2.1.26
    gatsby-plugin-material-ui: ^2.1.4 => 2.1.6
    gatsby-plugin-netlify: ^2.1.32 => 2.1.33
    gatsby-plugin-netlify-cms: ^4.1.38 => 4.1.40
    gatsby-plugin-nprogress: ^2.1.19 => 2.1.19
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.22
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.3.10 => 2.4.5
    gatsby-plugin-smoothscroll: ^1.0.3 => 1.0.4
    gatsby-plugin-typescript: ^2.1.0 => 2.1.27
    gatsby-remark-copy-linked-files: ^2.1.0 => 2.1.37
    gatsby-remark-images: ^3.1.3 => 3.1.44
    gatsby-remark-prismjs: ^3.3.1 => 3.3.31
    gatsby-remark-relative-images: ^0.2.2 => 0.3.0
    gatsby-remark-responsive-iframe: ^2.2.1 => 2.2.32
    gatsby-remark-smartypants: ^2.1.0 => 2.1.21
    gatsby-source-filesystem: ^2.1.3 => 2.1.48
    gatsby-transformer-json: ^2.2.0 => 2.2.26
    gatsby-transformer-remark: ^2.6.2 => 2.6.53
    gatsby-transformer-sharp: ^2.3.9 => 2.3.14

**Comment by alexeychikk** [comment]
It works when I downgrade from `2.19.22` to `2.13.13`.
