### ISSUE TITLE
[gatsby-transformer-screenshot] Adding an option for a fullpage screenshot

### ISSUE THREAD

**Issue by daydream05** [gatsbyjs/gatsby#10483]
## Summary

Add a config option that would allow users to specify if they would like a full page screenshot of the given website. 

### Basic example
```jsx
// in your gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-transformer-screenshot`,
      options: {
        nodeTypes: [`StartersYaml`, `WhateverType`],
        fullPage: true,
      },
    },
  ],
}
```

### Motivation

Sites such as Dribbble or Behance sometimes include attachments that are full page design of a site. It would be nice to be able to do the same but in reverse, website first then the the design comes next.

Looking at the source code, I think it's as simple as modifying gatsby node and allowing the lambda function to accept fullPage parameters and passing it to puppeeteer
```js
  // inside lambda/index.js
  const screenshot = await page.screenshot({ fullPage: request.fullPage || false })
```

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @daydream05. Just took a look at the source, it is a simple fix indeed. 

We'd love to accept a PR for this. Would you be interested? 🙂

**Comment by apvarun** [comment]
I can sent a PR for this right away!

**Comment by sidharthachatterjee** [comment]
Thank you for adding support for this @apvarun 

@daydream05 Look out for the next release of `gatsby-transformer-screenshot`

**Comment by daydream05** [comment]
Sweet! Amazing stuff @apvarun
