### ISSUE TITLE
Update URL in error message

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#10509]
## Summary

Replace goo.gl shortlinks with gatsby.app shortlinks in Gatsby error messages.

### Basic example

Some of Gatsby's error messages use a goo.gl shortlink to link to the Gatsby documentation. Gatsby now has a dedicated shortlink url, we should use this instead.

Replace https://goo.gl/yL9lND with https://gatsby.app/debug-html

This should be updated in [src/commands/develop.js](https://github.com/gatsbyjs/gatsby/blob/84124da2104781140c43cdf13c5a93746164cefe/packages/gatsby/src/commands/develop.js#L63) and [src/commands/build.js](https://github.com/gatsbyjs/gatsby/blob/84124da2104781140c43cdf13c5a93746164cefe/packages/gatsby/src/commands/build.js#L65).

### Motivation

It's a small detail, but using the same url shortener across all of Gatsby makes for a slightly nicer experience.

**Comment by Dipeshwagle** [comment]
Created a pull request #10521 @m-allanson

**Comment by m-allanson** [comment]
Fixed in #10521, thanks @Dipeshwagle 🎉
