### ISSUE TITLE
Debugging unminified build in gatsby v2

### ISSUE THREAD

**Issue by arturhenryy** [gatsbyjs/gatsby#10501]
## Summary

I get an Error Testing my site under ios 10 mobile safari. The problem is that i cannot debug it because the code is minified and the error message does not give me any hint at all.
Is threre anyway to debug the unminified build?

<img width="654" alt="bildschirmfoto 2018-12-17 um 12 28 59" src="https://user-images.githubusercontent.com/45144968/50084581-c1b62380-01f7-11e9-813e-874cdca368b4.png">

**Comment by LekoArts** [comment]
Hey Artur,

if you want to have an unminified build + sourcemaps you have to visit the site while running `gatsby develop`. You can read here how to do it:
https://github.com/gatsbyjs/gatsby/issues/5801

**Comment by m-allanson** [comment]
There's also the `--no-uglify` flag, `gatsby build --no-uglify` should do a full build and skip the minification step.

See https://www.gatsbyjs.org/docs/gatsby-cli/#options-1

**Comment by arturhenryy** [comment]
@m-allanson  thanks i already discovered and used it. it seems the uglification of gatsby caused error in safari 10. do you know if one can tweek the uglifcation settings like this?

````
    uglify: {
      uglifyOptions: {
        mangle: { safari10: true }
      }
    }
```
