### ISSUE TITLE
Gatsby Build Fails because it cant access sessionStorage at componentDidMount hook

### ISSUE THREAD

**Issue by arturhenryy** [gatsbyjs/gatsby#10511]
## Description

Gatsby fails building evaluating the componentDidMount and componentWillMount because sessionStorage is not defined on build. I know that you should check if window is defined before using sessionStorage but i thought that the component life cycle hooks should not be evaluated on build.
instead i get this error:

```
5:08:21 PM: error Building static HTML for pages failed
5:08:21 PM: See our docs page on debugging HTML builds for help https://goo.gl/yL9lND
5:08:21 PM:   32 |
5:08:21 PM:   33 |   componentWillMount() {
5:08:21 PM: > 34 |     const hideIntro = sessionStorage.getItem("hideIntro");
5:08:21 PM:      |                       ^
5:08:21 PM:   35 |     if (!hideIntro && this.hasSessionStorageSupport) {
5:08:21 PM:   36 |       document.body.classList.add("modal-open", "intro-modal-open");
5:08:21 PM:   37 |     }
5:08:21 PM: 
5:08:21 PM:   WebpackError: ReferenceError: sessionStorage is not defined
5:08:21 PM:   
5:08:21 PM:   - layout.jsx:34 MainLayout.componentWillMount
5:08:21 PM:     lib/src/components/Layout/layout.jsx:34:23
```
### Expected result

Build should succeed because the lifecycle hooks are clearly only evaluated when the component get called.

### Actual result

Build fails

**Comment by DSchau** [comment]
> Gatsby fails building evaluating the componentDidMount and componentWillMount because sessionStorage is not defined on build

It's failing in the `componentWillMount` lifecycle method, not `componentDidMount` (which will not be invoked during the SSR phase).

I'd recommend you re-factor the `componentWillMount` to use `componentDidMount` if you want to access globals on `window`, e.g. `sessionStorage`, `localStorage`, etc.

You could also guard against it, e.g. something like the below:

```jsx
componentWillMount() {
  if (typeof window !== 'undefined') {
    // do your checks; this will be re-invoked on client entry
  }
}
```

> but i thought that the component life cycle hooks should not be evaluated on build

We are just using [`ReactDOMServer`](https://reactjs.org/docs/react-dom-server.html) which invokes `componentWillMount` as this could be a valid use case for computing something and updating state before a render. See [this](https://github.com/DSchau/react-ssr-will-mount-example) for a reproduction.

One final note that `componentWillUnmount` has been [deprecated](https://reactjs.org/docs/react-component.html#mounting) so I'd recommend taking this time to move off of that API if you're able.

Going to close this as answered, but please re-open if we can assist further.

**Comment by arturhenryy** [comment]
@DSchau thanks for the clarification on this matter. one last question. the link you referenced links to
 
These methods are considered legacy and you should avoid them in new code:
UNSAFE_componentWillMount()

so i am confused. are both hooks componentWillMount and componentWillMount getting deprecated?

**Comment by DSchau** [comment]
@arturhenryy [here's some more info](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) re: that question!
