### ISSUE TITLE
Add pullquotes to existing articles on the gatsbyjs.org blog

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#10526]
We recently added pullquotes to the gatsbyjs.org blog, which gives a prettier format than the standard.

New quote display:

![image](https://user-images.githubusercontent.com/4388699/50123137-69414f00-0214-11e9-8704-ac658fc9ff17.png)

Old quote display:

![image](https://user-images.githubusercontent.com/4388699/50123152-76f6d480-0214-11e9-97be-e73b871a29b1.png)

We've identified ten articles that have key quotes that should be transformed to `<pullquote>`s. 

New pullquote syntax: https://github.com/gatsbyjs/gatsby/pull/10474/files#diff-aa36ebb83e4528a3625909e31946ed77R32
 
Have at it!

https://github.com/gatsbyjs/gatsby/tree/master/docs/blog/2018-07-07-graphic-design-class/index.md

https://github.com/gatsbyjs/gatsby/tree/master/docs/blog/2018-09-27-reach-router/index.md

https://github.com/gatsbyjs/gatsby/tree/master/docs/blog/2018-1-24-creative-software-destruction-new-presentation-layer/index.md

https://github.com/gatsbyjs/gatsby/tree/master/docs/blog/2018-10-03-gatsby-perf/index.md

https://github.com/gatsbyjs/gatsby/tree/master/docs/blog/2018-10-16-why-mobile-performance-is-crucial/index.md

https://github.com/gatsbyjs/gatsby/tree/master/docs/blog/2018-11-16-youfit-case-study/index.md

https://github.com/gatsbyjs/gatsby/tree/master/docs/blog/2018-2-3-sites-with-headless-cms/index.md

https://github.com/gatsbyjs/gatsby/tree/master/docs/blog/2017-10-16-making-website-building-fun/index.md

https://github.com/gatsbyjs/gatsby/tree/master/docs/blog/2017-12-20-introducing-the-gatsby-ux-research-program/index.md

**Comment by apvarun** [comment]
I'll handle this. PR coming!

**Comment by apvarun** [comment]
PR: #10530 @calcsam

**Comment by Nelson-Chinedu** [comment]
Hi @calcsam is this issue still open

**Comment by riddla** [comment]
![screenshot 2019-02-11 at 21 23 58](https://user-images.githubusercontent.com/174157/52591114-5d07f580-2e43-11e9-9fbe-2bc4b9f9e89d.png)

@calcsam, this seems to be released and can be closed?

**Comment by calcsam** [comment]
Yep!
