### ISSUE TITLE
Usage of gatsby-plugin-recaptcha without netlify

### ISSUE THREAD

**Issue by khus29** [gatsbyjs/gatsby#10533]
Hi all,

I have to use **gatsby-plugin-recaptcha** in my project forms. We are not using netlify. Please guide me to the usage examples of this plugin.

Thanks,
Khushboo k

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jgierer12** [comment]
Hi! The plugin only imports the reCAPTCHA script for you. So you use it exactly as you would when manually loading it, see the [reCAPTHCHA docs](https://developers.google.com/recaptcha/intro).
