### ISSUE TITLE
When to polyfill URL for Node V8 during build

### ISSUE THREAD

**Issue by darknoon** [gatsbyjs/gatsby#10547]
## Summary

Where do add `URL` to globals?

## Relevant information

I'm trying to migrate a Gatsby website from Zeit Now V1 to Zeit Now V2. One of the issues with Zeit V2 is that you have to build on Node 8.x instead of Node 10.x due to AWS Lambda limitations (I think).

On one of my pages I parse a URL with the `new URL(str)` constructor, then switch on the `host`. I'm not sure how to ensure that `URL` is available in the global scope for that page. I tried inserting code into `gatsby-node.js` and `gatsby-ssr.js` that add it as `global.URL` but neither seem to fix the issue when `gatsby build` actually tries to run.

The only way I've been able to make it work so far is to put this at the top of my file:

```
if (typeof URL === 'undefined') {
  global.URL = require('url').URL
}
```

https://github.com/darknoon/darknoon-web/tree/now-v2

### Environment (if relevant)

Zeit V2 / AWS Lambda

### File contents (if changed)

see github

**Comment by sidharthachatterjee** [comment]
Hey @darknoon 

You can [shim](https://webpack.js.org/guides/shimming/) `URL` using webpack. Read more about adding custom webpack configuration for Gatsby [here](https://www.gatsbyjs.org/docs/add-custom-webpack-config)

In the mean time, I've sent you a pull request (https://github.com/darknoon/darknoon-web/pull/3) with the changes necessary. The Now deployment succeeded so you should be good 🙂

Closing this for now but please feel free to comment if there is anything else

**Comment by darknoon** [comment]
Hi @sidharthachatterjee, I tried the build from your PR and I can't load any other pages than the home page. My browser complains:
<img width="1280" alt="screen shot 2018-12-29 at 18 04 36" src="https://user-images.githubusercontent.com/355540/50542820-3bed8d00-0b94-11e9-9229-75c7d76db56f.png">

I remember hitting that at one point in working out the solution I went for, don't remember how I fixed.
