### ISSUE TITLE
Do I need apollo-client and apollo-server when using Gatsby.js？

### ISSUE THREAD

**Issue by zwl1619** [gatsbyjs/gatsby#10555]
Do I need apollo-client and apollo-server when using Gatsby.js？

**Comment by LekoArts** [comment]
Hi 👋 
You don't need apollo-client, apollo-server or any other GraphQL library to use Gatsby and/or GraphQL in Gatsby. Gatsby comes with these capabilities baked in and will take your GraphQL queries at build time.

You can do the tutorial to get yourself familiar with Gatsby 😊 
https://www.gatsbyjs.org/tutorial/
