### ISSUE TITLE
Add copy-paste functionality on Gatsby docs

### ISSUE THREAD

**Issue by thomlom** [gatsbyjs/gatsby#10554]
## Summary

Add a copy-paste icon on code or comment example of the Gatsby docs.

### Motivation

While I was diving in Gatsby docs, I found it frustrating to have to manually select the code examples and copy them into my local files because:

- By selecting the code example, we select additional text without meaning to do so.
- Copying a long code example involves scrolling, and selecting while scrolling is hard.

Adding a copy-paste icon to the top right of each code example or command would be in my opinion, a small but great addition to the docs.

**Comment by LekoArts** [comment]
Hi 👋 
Thank you for opening the issue! There's already a discussion about that elsewhere, so I'm closing this issue as a duplicate 😊 
https://github.com/gatsbyjs/gatsby/issues/5030
