### ISSUE TITLE
Environment variables are not captured utilizing NODE_ENV in Webpack

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#10563]
## Description

[Environment variables](https://www.gatsbyjs.org/docs/environment-variables/) (captured in `.env.ENVIRONMENT`, e.g. `.env.staging`) do not get exposed correctly to the code that gets bundled with Webpack, e.g. the client-side, non-Node code.

We can see this by walking through the build process:

1. Add a script, `build:staging`

    ```json
    {
      "scripts": {
        "build:staging": "cross-env NODE_ENV=staging npm run build"
      }
    }
    ```

1. `gatsby build` is kicked off via the CLI [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/create-cli.js#L177)
    - This _explicitly_ sets NODE_ENV=production, therefore ignoring any overrides from the user
1. Environment variables are sourced via Webpack [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L40)
    - This will _always_ be production; it's not possible to override this since it's set and overwritten early in the build via the CLI

### Steps to reproduce

1. [Clone this repo](https://github.com/dschau/gatsby-env-vars-example)
1. Run `yarn` or `npm install`
1. Run `yarn build:staging`
1. The environment variable `API_KEY` in `.env.staging` should be present in the built code

### Expected result

The environment variable `API_KEY` from `.env.staging` should be present in `public/index.html`

### Actual result

The environment variable `API_KEY` from `.env.production` is used.

## The Fix

I don't believe we can overwrite `NODE_ENV` as `production` is checked fairly often in various plugins/APIs/etc. Using `process.env.NODE_ENV = process.env.NODE_ENV || 'production'` in `gatsby-cli` seems to break the build.

As such - I think there are two things that we should do here to remediate the issue.

1. Tweak [this code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L40) to check for an environment override _outside_ of `NODE_ENV`
    - Perhaps `ACTIVE_ENV` as we [document here](https://www.gatsbyjs.org/docs/environment-variables/#example-1)
1. Tweak any documentation to make it clear that this new environment variable must be used if you want to use a separate .env file for a "production" build

I don't love the indirection and extra steps here--but not sure I see a better solution off hand. Opinions more than welcome here!

cc @xjamundx

**Comment by KyleAMathews** [comment]
So the problem is how to set environment variables for staging builds?

**Comment by DanielRuf** [comment]
> webpack/babel/terser need it set to production?

Not really as webpack 4.x introduced the `prod/dev` flag.

**Comment by DanielRuf** [comment]
See https://webpack.js.org/guides/production/#specify-the-mode

**Comment by KyleAMathews** [comment]
Ah cool. Yeah setting NODE_ENV seems ideal as it's widely used for this sort of thing.

**Comment by ankesh7** [comment]
Any updates on this? I am running into an issue where I have multiple environments and only one needs to have the Google Tag Manager injected. I am using the gatsby-google-tagmanager plugin and every time i run `ACTIVE_ENV=something yarn gatsby build`, NODE_ENV is always set to production and it skews my analytics.
