### ISSUE TITLE
Cant scroll page after clicking through

### ISSUE THREAD

**Issue by joebentaylor** [gatsbyjs/gatsby#10579]
I am currently working on my portfolio site, however I've came to a quick and abrupt stop as ive got an extremely bizarre error...

So. When i navigate from my portfolio page to my project page through clicking a project on the portfolio page (via Gatsby Link), I cannot scroll the page.

There are no errors.

Nothing CSS wise is causing this from what I've looked into.

However if i reload that page once Im there... I can scroll.

This only happens on mobile devices and not in desktop browsers.

the current version of the site is here:

www.12studio.agency

Im at the point of giving in :'(

Ive disabled components 1 by 1 to make sure either nothing is being carried over, or effecting the page but it happens regardless of whether components or CSS is turned off. It literally will not scroll on navigation to the project page.

**Comment by sidharthachatterjee** [comment]
Really nice site, @joebentaylor

Sorry that you're seeing this. I can confirm that scrolling doesn't work on iOS Safari. It appears that scrolling is handled via JavaScript. Can you post a link to the source code if possible? Do you see any errors in the console when trying to scroll on a mobile device?

**Comment by joebentaylor** [comment]
Thanks @sidharthachatterjee 

No errors in the console on build or develop.

Whats your bitbucket username? Ill share the repo, cant think of another way to share the source code?

**Comment by joebentaylor** [comment]
This wasnt a gatsby issue, i figured out that it was an issue within react-slick

**Comment by sidharthachatterjee** [comment]
Yeah, I was just inspecting the build and everything seemed fine to me. Thank you for closing this, @joebentaylor.

**Comment by fk** [comment]
Glad you could resolve your issue @joebentaylor;
seconding @sidharthachatterjee — this is a beautiful site! 😍 

Please [add it to the showcase](https://www.gatsbyjs.org/showcase) once it's ready!?
