### ISSUE TITLE
gatsby-remark-autolink-headers: Scrolling to anchor not working on page load

### ISSUE THREAD

**Issue by sydneypalumbo** [gatsbyjs/gatsby#10570]
## Description

With `gatsby-remark-autolink-headers`, when refreshing a page or navigating to a different page with an anchor in the URL, scrolling to the anchored header isn't working. The native browser event that handles this seems to be affecting the expected behavior because the script in `gatsby-ssr.js` in `gatsby-remark-autolink-headers` is firing before it should.

More specifically:
 - if you scroll away from an anchor and refresh the page, it initially goes to the right spot, but then returns to your previous location on the page:
![refresh-jumpy-scroll](https://user-images.githubusercontent.com/20714654/50258438-96c4fe80-03b4-11e9-9173-f2308f4cb0d0.gif)

- if you navigate to a page with a URL in the anchor, it jumps to the wrong spot:
![page-load-jump](https://user-images.githubusercontent.com/20714654/50258477-beb46200-03b4-11e9-81f1-dff1ad7a4d34.gif)

As was mentioned in https://github.com/gatsbyjs/gatsby/issues/5314, this can be fixed by editing the script in `gatsby-ssr.js` in `gatsby-remark-autolink-headers` so that it uses the window `load` event rather than the document `DOMContentLoaded` event.

The result of swapping `DOMContentLoaded` for `load` is:
- fixed on page refresh
![fixed-refresh](https://user-images.githubusercontent.com/20714654/50258778-fff94180-03b5-11e9-8185-390da5a833a4.gif)

- fixed on navigating to page with an anchor in the URL 
![new-page-fixed](https://user-images.githubusercontent.com/20714654/50258781-04255f00-03b6-11e9-8d99-d45b1a414a70.gif)

**Comment by KyleAMathews** [comment]
Hmmm not sure why this change would make a difference. Does your site have a lot of images perhaps? `load` waits for all stylesheets/images to finish loading https://stackoverflow.com/questions/2414750/difference-between-domcontentloaded-and-load-events

**Comment by wardpeet** [comment]
@sydneypalumbo we did a scroll fix a week ago, can you test this behaviour again? ^^

**Comment by sydneypalumbo** [comment]
@wardpeet that fixed it! It ends up on the proper place on the page for both of the cases I described above -- thanks so much :+1:
