### ISSUE TITLE
Automatic dependency updates for Gatsby packages

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#10583]
Do we need automatic dependency updates for Gatsby packages?

- [x] Starters
- [x] Packages

### Why we might
- the current climate around attacks in dependencies 
- we've had several issues opened over time around `npm audit` issues with `gatsby` (typically pretty deep into the tree)

### Options
- https://greenkeeper.io
- https://renovatebot.com/

### Challenges
- we don’t run e2e tests on Node 6 (e2e tests are generally problematic with dependency changes currently according to @pieh)

**Comment by sidharthachatterjee** [comment]
Both the options mentioned above have monorepo support, just checked

**Comment by wardpeet** [comment]
I would love renovatebot as it's seems more configurable than greenkeeper. I haven't used any of the 2 so I don't really care but I think it might help us in the long run.

**Comment by sidharthachatterjee** [comment]
We now use Renovate for _all_ packages!
