### ISSUE TITLE
Starter idea: Blog but where each post gets generated with a latex-generated PDF

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#106]
This would be really fun. Auto-convert on build all Markdown files into PDFs using something like Pandoc and a classy Latex template.

**Comment by taras** [comment]
I'd love to see what this looks like. I guess no one picked it up?

**Comment by jonniebigodes** [comment]
@taras to my knowledge and a bit of search, it looks like no one picked up on it. If you're able and willing go for it. Hope to see that starter being added in the future in here 🤞

**Comment by taras** [comment]
I found an article called [Building a PDF Library with Gatsby.js](http://blog.blakesimpson.co.uk/read/96-building-a-pdf-library-with-gatsby-js) and [GitHub repository](https://github.com/BlakeSimpson/gatsby-library) which attempts to do something similar.

The use case that I'm interested in is generating preview images of each page to make more engaging social sharing posts. There is this https://www.gatsbyjs.org/packages/gatsby-remark-social-cards/ but I'd like to make the template for the social image a React component.

With that said, I can also see the need for generating a PDF from a selection of pages.
