### ISSUE TITLE
Autogenerate lock files for starters

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#10607]
Now that starters are in this repo courtesy of @DSchau, @pieh and I were discussing how we ought to autogenerate lock files for them since manually updating dependencies is a chore. 

`package.json` for all starters have all dependencies specified with the `^` selector so it's only the lock files that needs updating.

**Comment by sidharthachatterjee** [comment]
@DSchau just made a great point about how we don't supply a `yarn.lock` and `yarn` users therefore don't get deterministic installs

**Comment by KyleAMathews** [comment]
For context, the only reason we include a lock file at all (we didn't for a while) is the npm has the adorable behavior that if you install dependencies with yarn but then install a package with npm, npm not seeing a package-lock.json file will assume that everything in node_modules isn't needed and then delete those and only install the one new package.

We used to get tons of issues from people complaining that gatsby didn't work after a while when going through the tutorial or trying it out.

So deterministic installs isn't the goal, the goal is helping npm avoid deleting all someone's packages.

What would also help is if we let people choose to use NPM or yarn as then "gatsby new" could choose one or the other and then we could avoid lock files altogether.

**Comment by JacobBlomgren** [comment]
@sidharthachatterjee any updates on this? I was just about to file an issue about `Gatsby new`, where yarn will print 

>  package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

which is related to this. As I see it, there are two solutions to this, either remove the lock file that is not used during `Gatsby new`, or only ship the default starter with package-lock and then do `yarn import` as mentioned above. I’d be happy to help! This has also been reported here: https://github.com/gatsbyjs/gatsby/issues/4514#issuecomment-458729956

**Comment by sidharthachatterjee** [comment]
Sorry for missing this comment @JacobBlomgren 

I've tagged you in https://github.com/gatsbyjs/gatsby/issues/13210 with a potential solution in case you're still interested in taking a stab at this!

**Comment by sidharthachatterjee** [comment]
We now include both `package-lock.json` and `yarn.lock` in official starters (like in https://github.com/gatsbyjs/gatsby-starter-default) and delete the unused one based on the user's selected package manager.
