### ISSUE TITLE
TypeError: queue.off is not a function

### ISSUE THREAD

**Issue by ChenglimEar** [gatsbyjs/gatsby#10615]
## Description

gatsby develop fails after creating a brand new project using `gatsby new my-project`.

### Steps to reproduce

1. npm install --global gatsby-cli
2. gatsby new my-project
3. cd my-project/
4. gatsby develop

### Expected result

No error

### Actual result

Got this error:

success extract queries from components — 0.181 s
error UNHANDLED EXCEPTION

  TypeError: queue.off is not a function

  - page-query-runner.js:162 Queue.onDrain
    [reactstrap]/[gatsby]/dist/internal-plugins/query-runner/page-query-runner.js:162:13

  - queue.js:469 Queue._drained
    [reactstrap]/[better-queue]/lib/queue.js:469:8

  - queue.js:505 Queue._processNextIfAllowed
    [reactstrap]/[better-queue]/lib/queue.js:505:14

  - queue.js:489 Timeout._onTimeout
    [reactstrap]/[better-queue]/lib/queue.js:489:12

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 7.7.4 - /usr/local/bin/node
    npm: 4.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 53.0.3
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.53 => 2.0.74 
    gatsby-image: ^2.0.20 => 2.0.25 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12 
    gatsby-plugin-offline: ^2.0.16 => 2.0.20 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.14 => 2.0.16 
    gatsby-source-filesystem: ^2.0.8 => 2.0.12 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9 
  npmGlobalPackages:
    gatsby-cli: 2.4.7

**Comment by DSchau** [comment]
Hello!

Fix is available in gatsbyjs/gatsby#10613.

Please upgrade to gatsby@2.0.75 in order to get the fix. Thank you!

**Comment by MykalMachon** [comment]
Just a note for others looking to fix this, I had to do the following in conjunction with updating gatsby: 

1. Update Node.js to a version > 10.0.0
2. Re-clone all my Gatsby repositories from GitHub

After doing this, I was able to get up and developing with Gatsby again.
Hope this helped somebody!
