### ISSUE TITLE
Support Parsing of Markdown Within Custom Tags

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#10614]
## Summary

It is currently [trivial](https://using-remark.gatsbyjs.org/custom-components/) to use Rehype to map a custom tag to a React component, as it passing data to that component via the attributes of the custom tag:
```
# Title Here

<custom-component alpha="1" bravo="example"></custom-component>
```

However, any markdown declared within a custom tag is not parsed and will not be converted into an AST.  In the following example, the markdown list will not be converted into a `<ul>`:

```
<custom-component>
  - alpha
  - bravo
  - charlie
</custom-component>
```

If markdown inside a custom tag was parsed, it would become trivial to add sections to a markdown page either for styling purposes or for layout. Assuming you were mapping html elements to Styled Components, you could even wrap them in a different Theme. 

### Basic example

This would be an internal change to how Markdown is parsed. It would need to support a configuration setting to enable / disable to ensure that behaviour didn't change unless the change was wanted. 

### Motivation

This change would add a wealth of possibilities that are currently only possible using MDX, and not only is MDX unsupported in any CMS's (for example Netlify CMS) but it requires programming skills to write and maintain. 

### Current Alternatives

- MDX: No CMS support and requires a programmer to edit and maintain.
- Splitting page into multiple pieces and reassembling them at build time: unwieldy and complex.
- Write page in HML: breaks away from the simplicity and easy-maintenance of Markdown.
- Nested HTML in Markdown: Inconsistent and requires maintainer has knowledge of HTML.

**Comment by robinmetral** [comment]
I believe that Markdown parsing inside [Rehype custom components](https://using-remark.gatsbyjs.org/custom-components/) does works. It's just inconsistent.

For example, in my case, this renders the Markdown as plain text:

```markdown
<post-image columns="2">
![A two-column image](image.jpg)
</post-image>
```

While this renderd the image as expected:

```markdown
<post-image columns="2">![A two-column image](image.jpg)</post-image>
```

The Gatsby community seems to be moving towards using [MDX](https://www.gatsbyjs.org/docs/mdx/) over [Rehype](https://using-remark.gatsbyjs.org/custom-components/) for custom components in Markdown.

So—if you read this, I suggest migrating to MDX, as it will gain support and features in the future. Start with [the MDX docs](https://www.gatsbyjs.org/docs/mdx/).
