### ISSUE TITLE
Cannot start localhost:8000 with "gatsby develop"

### ISSUE THREAD

**Issue by mySuulola** [gatsbyjs/gatsby#10621]
after downloading the starter from gatsby github. Got the error below anytime i run gatsby develop

Error: Unable to find plugin "gatsby-plugin-manifest". Perhaps you need to ins  tall its package?

i've tried running "npm install" and i still got the same problem. Any fix?

**Comment by LekoArts** [comment]
Try deleting `node_modules` and do a `npm install` again. It seems your installation is missing some packages.

**Comment by mySuulola** [comment]
> Try deleting `node_modules` and do a `npm install` again. It seems your installation is missing some packages.

<p>Wow. . .Thanks a lot for this. Worked perfectly well</p>
