### ISSUE TITLE
gatsby-plugin-react-helmet script initially missing

### ISSUE THREAD

**Issue by GlynL** [gatsbyjs/gatsby#10638]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

**Comment by ZYSzys** [comment]
Repeat with #10639 , closing this.
