### ISSUE TITLE
http://localhost:8000/sdf should give me a 404 error page [Tutorial 7]

### ISSUE THREAD

**Issue by omrllm** [gatsbyjs/gatsby#10645]
## Description

Hey guys,

So I'm following your tutorials, and everything works till the [creating pages](https://www.gatsbyjs.org/tutorial/part-seven/#creating-pages) section

### Steps to reproduce

Just follow the [tutorial](https://www.gatsbyjs.org/tutorial/part-seven)

### Expected result

http://localhost:8000/sdf should give a 404 page

### Actual result

I get in `gatsby develop`:

Error: Missing resources for /sdf
ProxyComponent.render
/home/omar/tutorial-part-four/.cache/ensure-resources.js:133
  130 | render() {
  131 |   if (!this.hasResources(this.state.pageResources) && isInitialRender) {
  132 |     // prevent hydrating
> 133 |     throw new Error(`Missing resources for ${this.state.location.pathname}`)
  134 |   }
  135 | 
  136 |   isInitialRender = false
View compiled
▶ 25 stack frames were collapsed.
(anonymous function)
/home/omar/tutorial-part-four/.cache/app.js:56
  53 | const preferDefault = m => (m && m.default) || m
  54 | let Root = preferDefault(require(`./root`))
  55 | domReady(() => {
> 56 |   renderer(<Root />, rootElement, () => {
  57 |     apiRunner(`onInitialClientRender`)
  58 |   })
  59 | })
View compiled
HTMLDocument.listener
node_modules/domready/ready.js:23
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

In production the _sdf_ page gives me:

`Error: ENOENT: no such file or directory, stat '/home/omar/tutorial-part-four/public/404.html'`

### Environment

System:
    OS: Linux 4.19 Fedora 29 (Workstation Edition) 29 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
    Shell: 4.4.23 - /bin/bash
  Binaries:
    Node: 11.3.0 - ~/.nvm/versions/node/v11.3.0/bin/node
    Yarn: 1.12.3 - /var/lib/snapd/snap/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v11.3.0/bin/npm
  Browsers:
    Firefox: 64.0
  npmPackages:
    gatsby: ^2.0.75 => 2.0.75 
    gatsby-plugin-emotion: ^4.0.1 => 4.0.1 
    gatsby-plugin-typography: ^2.2.4 => 2.2.4 
    gatsby-source-filesystem: ^2.0.12 => 2.0.12 
    gatsby-transformer-remark: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.7
    gatsby: 2.0.75

error Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel

  Error: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can inst  all it with: sudo apt install xsel
  
  - envinfo.js:1 i
    [lib]/[gatsby]/[envinfo]/dist/envinfo.js:1:65651
  
  - envinfo.js:1 Object.copySync
    [lib]/[gatsby]/[envinfo]/dist/envinfo.js:1:66177
  
  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [lib]/[gatsby]/[envinfo]/dist/envinfo.js:1:48777
  
  - envinfo.js:1 
    [lib]/[gatsby]/[envinfo]/dist/envinfo.js:1:46934
  
  - envinfo.js:1 Promise.all.then.e
    [lib]/[gatsby]/[envinfo]/dist/envinfo.js:1:46949
  
  - util.js:16 tryCatcher
    [lib]/[gatsby]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:694:18
  
  - promise.js:638 Promise._fulfill
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:638:18
  
  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby]/[bluebird]/js/release/promise_array.js:126:19
  
  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby]/[bluebird]/js/release/promise_array.js:144:14
  
  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:574:26
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:694:18
  

error UNHANDLED REJECTION

  Error: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can inst  all it with: sudo apt install xsel
  
  - envinfo.js:1 i
    [lib]/[gatsby]/[envinfo]/dist/envinfo.js:1:65651
  
  - envinfo.js:1 Object.copySync
    [lib]/[gatsby]/[envinfo]/dist/envinfo.js:1:66177
  
  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [lib]/[gatsby]/[envinfo]/dist/envinfo.js:1:48777
  
  - envinfo.js:1 
    [lib]/[gatsby]/[envinfo]/dist/envinfo.js:1:46934
  
  - envinfo.js:1 Promise.all.then.e
    [lib]/[gatsby]/[envinfo]/dist/envinfo.js:1:46949
  
  - util.js:16 tryCatcher
    [lib]/[gatsby]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:694:18
  
  - promise.js:638 Promise._fulfill
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:638:18
  
  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby]/[bluebird]/js/release/promise_array.js:126:19
  
  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby]/[bluebird]/js/release/promise_array.js:144:14
  
  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:574:26
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby]/[bluebird]/js/release/promise.js:694:18

Is this related to [Uncaught "missing resources" error on 404 page](https://github.com/gatsbyjs/gatsby/issues/10534)?

**Comment by sidharthachatterjee** [comment]
This is related to https://github.com/gatsbyjs/gatsby/issues/10534

https://github.com/gatsbyjs/gatsby/pull/10625 fixes this

In the mean time, can you try running `gatsby` v2.0.66?

**Comment by omrllm** [comment]
> In the mean time, can you try running gatsby v2.0.66?

Yeah, but how can I do that? :satisfied:

**Comment by pieh** [comment]
You should be able to use gatsby@2.0.76 where this should be fixed - you can adjust `package.json` file ("dependencies" section to force that version) and run `npm install` or `yarn` (depending on which package manager you use)
