### ISSUE TITLE
font-feature-settings incorrectly set to have ligatures for code blocks

### ISSUE THREAD

**Issue by qinyiyao** [gatsbyjs/gatsby#10643]
## Description

In documentation, some text in code blocks are rendered with ligatures, making two letters taking up less space.

<img width="925" alt="screen shot 2018-12-24 at 4 51 06 am" src="https://user-images.githubusercontent.com/6311717/50400196-a8eac800-0739-11e9-8636-efce76d10e83.png">

### Steps to reproduce

1. Go to [Transformer plugins | GatsbyJS](https://www.gatsbyjs.org/tutorial/part-six/#transformer-plugins)
2. Search `gatsby-config.js` in page
3. You should see the issue pictured above. If not, change `font-family` fallbacks so that `Menlo` is the first valid font.

### Expected result

Letter `f` and `i` separated and have equal width like others. Visually this is easier to read and aesthetically more pleasing.

### Actual result

Ligature. `font-feature-settings` was set on a global node without special attention for code blocks.

**Comment by sidharthachatterjee** [comment]
@qinyiyao Thank you for opening this

No worries @fk, opened a PR adding them back 🙂

**Comment by fk** [comment]
Thank you @qinyiyao and @sidharthachatterjee! 🙏🤗
