### ISSUE TITLE
gatsby-transformer-remark: support content classes

### ISSUE THREAD

**Issue by robinmetral** [gatsbyjs/gatsby#10647]
## Summary

Remark adds useful features to plain Markdown, and one of them is [content classes](https://github.com/gnab/remark/wiki/Markdown#content-classes). It would be great if the `gatsby-transformer-markdown` plugin supported it!

### Basic example

With content classes, this markdown:

```markdown
.footnote[.red.bold[*] Important footnote]
```

generates this html:

```html
<span class="footnote">
  <span class="red bold">*</span> Important footnote
</span>
```

### Motivation

Users wouldn't need to switch to html in their markdown content as soon as a custom content class is needed.

**Comment by pieh** [comment]
We don't use `remark` you linked to - this seems to be different implementation and for different use cases. We use https://github.com/remarkjs/remark, but I think you could get similiar features from using this additional plugin - https://www.gatsbyjs.org/packages/gatsby-remark-bracketed-spans/ (just not sure if you could nest multiple spans like in your example)

**Comment by robinmetral** [comment]
Thanks for your reply @pieh, sorry I didn't realize this was another Remark :slightly_smiling_face: 

The plugin looks good, I'll give it a try!

**Comment by robinmetral** [comment]
Have to reopen this because the `gatsy-bracketed-spans` plugin isn't working with inner markdown (vadimshvetsov/gatsby-remark-bracketed-spans#1).

Is this something Gatsby could implement in a future version of `gatsby-transformer-remark`?

**Comment by sidharthachatterjee** [comment]
@robinmetral It appears that `gatsy-bracketed-spans` uses `remark-bracketed-spans` under the hood which according to its documentation (at https://github.com/sethvincent/remark-bracketed-spans) only supports span tags

> A remark plugin for adding attributes to span tags in markdown that works even when the span is nested inside other markdown elements.

If the `remark-bracketed-spans` adds support for this, it should just work

**Comment by robinmetral** [comment]
It does seem to use `remark-bracketed-spans` under the hood.

For me the problem isn't so much that it only support `<span>` tags, but that it doesn't accept any inner markdown (no bold text or images in the span, everything is parsed as plain text).

**Comment by sidharthachatterjee** [comment]
Looking at the source for `remark-bracketed-spans` at 
https://github.com/sethvincent/remark-bracketed-spans/blob/1f1e040614c7cc37e2b3578bc65af115e584b651/index.js#L34

It seems to support nested spans but not other elements nested within a span

Closing this for now since its unfortunately beyond Gatsby's control but please feel free to reopen if there is anything else

**Comment by robinmetral** [comment]
@sidharthachatterjee couldn't Gatsby consider adding this feature in `gatsby-transformer-remark` as mentioned in [my comment above](https://github.com/gatsbyjs/gatsby/issues/10647#issuecomment-449939734)?

**Comment by janosh** [comment]
Funny how few upvotes this issue got. Would have thought this is quite a common use case. Common enough even that it could be part of `gatsby-transformer-remark` as @robinmetral suggested.
