### ISSUE TITLE
gatsby-image fluid expects aspectRatio to exist, fails silently(image does not display)

### ISSUE THREAD

**Issue by polarathene** [gatsbyjs/gatsby#10659]
## Description

`gatsby-image` fails to work correctly with fluid image if no `aspectRatio` value is provided due to the calculation expecting it for fluid images and returning NaN instead.

### Steps to reproduce

I have used `gatsby-image` with `gatsby-source-contentful` and a graphql query like the following:

```GraphQL
const QueryPageService = graphql`
  query QueryPageService {
    contentfulPageService {
      services {
          media {
            file { url }
            fluid(maxWidth: 500){
              sizes
              src
              srcSet
              srcWebp
              srcSetWebp
              # Below as an alternative will also retrieve aspectRatio
              #...GatsbyContentfulFluid_withWebp
            }
          }
      }
    }
  }
`
```

The query works fine and provides all data. I referenced the examples from the gatsby/contentful demo: https://using-contentful.netlify.com/image-api/ (also hosted at https://using-contentful.gatsbyjs.org/image-api/ ). The fragment will return the aspectRatio and thus not run into this issue, it was not in the examples I came across and I wasn't aware that it works  even if it does not in `GraphiQL`

**The examples there for fluid do not show the `aspectRatio` field being queried.**(Nor the fragment, tracedSVG has the fragment, but is outdated, despite the repo using v2 of Gatsby in package.json, `...GatsbyContentfulSizes_tracedSVG` is from v1.

When used in my project the images failed to display correctly due to CSS. While I could change the CSS via the `Img` component props to correct this, it turned out that in `gatsby develop` there was a `padding-bottom` CSS property being set on the components wrapper first child div, **but the value was invalid, and thus omitted**. In `gatsby build` this CSS property is included but with a **value of `NaN%`**(Where I noticed breakage with my alternative CSS fix).

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js#L271

```JS
 paddingBottom: `${100 / image.aspectRatio}%`,
```

Additional context if unable to reproduce: My project using this has the image contained a flexbox item parent, and another a carousel component that uses relative positioning. Neither seem to be affected ensuring an aspectRatio value is provided.

### Expected result

This expects `aspectRatio` to exist, a default should be provided or raise a compile error.

The contentful demo repo should also point out it relies on `aspectRatio` to work correctly and/or mention the contentful fluid fragment. The tracedSVG example should also be updated to use the correct v2 fragment.

### Actual result

In `gatsby develop` there was a `padding-bottom` CSS property being set on the components wrapper first child div, **but the value was invalid, and thus omitted**. 

In `gatsby build` this CSS property is included but with a **value of `NaN%`**

### Environment

`gatsby info` has no output, `gatsby -v` returns `2.0.75`. It's running in a custom docker container(Alpine 3.8 base, NodeJS 10).

**Comment by sidharthachatterjee** [comment]
Interestingly, we already do props validation in `gatsby-image`

https://github.com/gatsbyjs/gatsby/blob/4685bcb9a8cd45295280c743de0d964310aaf860/packages/gatsby-image/src/index.js#L453

**Comment by pieh** [comment]
> Interestingly, we already do props validation in `gatsby-image`

Hmm, so this should be caught in `develop` then - just that it would be logged in browser console so it might be easily looked over. We potentially could add `develop` only element that would report missing prop so it's easier to spot

**Comment by polarathene** [comment]
I'll need to confirm again, but when I tried the legacy Sizes version for tracedSVG I remember it failing, I had to use the Fluid version. Not sure if the Contentful variant causes any difference, they seem to define some stuff there.

I could look at doing a PR for the docs if you like, trying to sort out a feature PR for `gatsby-source-contentful` atm :)

Do you need a reproducible project to see the issue with `padding-bottom` if not using a fragment and not passing in aspectRatio?

> just that it would be logged in browser console so it might be easily looked over. 

Yeah, I think my browser console with develop has a lot of warnings that I've sort of not paid attention to atm, so it might have been there. I also get warnings in CLI(again quite a few as it's my first gatsby project and I'm just interested in getting the project built out while I learn, then address warnings after). 

Would it not be considered an error applying a CSS property with a value of NaN%(only in build, in develop the property and value is omitted, both break the visibility of the image however)?

**Comment by aamorozov** [comment]
I've just encountered a similar(might be even the same) issue while using destructured `GatsbyImageSharpFluid` in the fluid query: 

#### doesn't work:
```
childImageSharp {
              fluid(maxWidth: 600) {
                 ...GatsbyImageSharpFluid
```


#### works 
```
        childImageSharp {
              fluid(maxWidth: 600) {
                sizes
                src
                srcSet
                srcWebp
                srcSetWebp
              }
}
```

```
System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 12.0
  npmPackages:
    gatsby: 2.0.85 => 2.0.85
    gatsby-image: 2.0.25 => 2.0.25
    gatsby-plugin-favicon: 3.1.5 => 3.1.5
    gatsby-plugin-flow: 1.0.2 => 1.0.2
    gatsby-plugin-force-trailing-slashes: 1.0.4 => 1.0.4
    gatsby-plugin-jsxstyle: 0.0.4 => 0.0.4
    gatsby-plugin-manifest: 2.0.13 => 2.0.13
    gatsby-plugin-offline: 2.0.20 => 2.0.20
    gatsby-plugin-react-helmet: 3.0.5 => 3.0.5
    gatsby-plugin-sharp: 2.0.17 => 2.0.17
    gatsby-plugin-transition-link: 1.4.5 => 1.4.5
    gatsby-source-filesystem: 2.0.12 => 2.0.12
    gatsby-source-graphql: 2.0.8 => 2.0.8
    gatsby-transformer-json: 2.1.6 => 2.1.6
    gatsby-transformer-sharp: 2.1.10 => 2.1.10
  npmGlobalPackages:
    gatsby-cli: 2.4.6
    gatsby: 2.0.67
```

**Comment by polarathene** [comment]
@aamorozov That sounds like the opposite? I don't believe the term is destructured based on what you showed(that's a spread operator but in GraphQL afaik is called a fragment?), that will return aspectRatio among others. 

Your other snippet doesn't ask for `aspectRatio` and should cause the bug I experienced due to `padding-bottom` being omitted in `gatsby develop` but applied with a value of `NaN%` as without aspectRatio being provided it was an invalid calculation.

I've got a few things to deal with atm, but once they're out of the way I'll be looking back into this to confirm and provide reproduction/fix.

**Comment by aamorozov** [comment]
You're right, I've updated the original comment. The issue that I had was I did not pass the aspectRatio prop, but it worked without any error, and the padding-bottom was added in an opposite direction, i.e opposite aspectRatio @polarathene

**Comment by polarathene** [comment]
I am able to reproduce this with the default starter of `gatsby new` by replacing the GraphQL spread like demonstrated in my initial issue message. 

Building with `gatsby develop` or `gatsby build` throws no warnings/errors in console, viewing the page, no image is displayed, inspecting HTML the mentioned padding is also `NaN%` (on `gatsby build`). Error does show on browsers console(PropType errors don't write to console? I used console.log() in the same file which did output during build):

```
Warning: Failed prop type: The prop `fluid.aspectRatio` is marked as required in `Image`, but its value is `undefined`.
```

Inspecting the `aspectRatio` value from `gatsby-image` is undefined, only the props that were requested from the GraphQL statement are available. `gatsby-transformer-sharp` has the `aspectRatio` node as a `GraphQLFloat` type, `gatsby-plugin-sharp` seems to keep an `aspectRatio` value of 1(which is correct for the image). I assumed that's where the query data was coming from where it returns a fluid object with `aspectRatio`... Perhaps it does provide the GraphQL response data, but since I didn't request the aspectRatio field, it was pruned from the fluid data object passed to Image props?

---

@aamorozov based on my findings, I'm a bit confused how it's working differently for you? Are you able to reproduce your result or my result with a fresh `gatsby new` project? Just edit `src/components/image.js` to swap out the fragment like this:

```
fluid(maxWidth: 300) {
    sizes
    src
    srcSet
}
```

Your results are quite odd, the one you say works for you doesn't use aspectRatio while the fragment will return aspectRatio yet you say doesn't apply a padding-bottom value. I suspect something is wrong or different in your project, if someone else wants to reproduce to confirm either side that'd also be good :)

---

Should I contribute a fix here, and if so what? `sizes` would also be possible to not provide by user error. So assuming what the aspect ratio should be from height/width isn't an option right? Either force/default to 1 and supplement the browser console error with one on the CLI as well, or throw an exception to prevent the build? 

Alternatively... just correcting the documentation(where this problem originally was caused from) and if a developer/user troubleshoots for this issue, they'll resolve it from following the docs properly or perhaps finding this issue thread?

**Comment by san7hos** [comment]
I am beginning with gatsby, but this seems to be failing when using fixed as well. I am using a very simple query:

```
const Image = () => (
  <StaticQuery
    query={graphql`
      query {
        image: file(relativePath: { eq: "logo.jpg" }) {
          childImageSharp {
            fixed(width: 100, height: 100) {
              ...GatsbyImageSharpFixed
            }
          }
        }
      }
    `}
    render={data => <Img fluid={data.image.childImageSharp.fixed} />}
  />
)
```

```

  | __stack_frame_overlay_proxy_console__ | @ | index.js:2177
-- | -- | -- | --
  | printWarning | @ | checkPropTypes.js:19
  | checkPropTypes | @ | checkPropTypes.js:82
  | validatePropTypes | @ | react.development.js:1686
  | createElementWithValidation | @ | react.development.js:1775
  | React$$1.createElement | @ | react-hot-loader.development.js:1710
  | render | @ | heart.js:29
  | (anonymous) | @ | gatsby-browser-entry.js:22
  | updateContextConsumer | @ | react-dom.development.js:15197
  | beginWork | @ | react-dom.development.js:15363
  | performUnitOfWork | @ | react-dom.development.js:18150
  | workLoop | @ | react-dom.development.js:18190
  | renderRoot | @ | react-dom.development.js:18276
  | performWorkOnRoot | @ | react-dom.development.js:19165
  | performWork | @ | react-dom.development.js:19077
  | performSyncWork | @ | react-dom.development.js:19051
  | requestWork | @ | react-dom.development.js:18920
  | scheduleWork | @ | react-dom.development.js:18729
  | scheduleRootUpdate | @ | react-dom.development.js:19397
  | updateContainerAtExpirationTime | @ | react-dom.development.js:19425
  | updateContainer | @ | react-dom.development.js:19482
  | ./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render | @ | react-dom.development.js:19774
  | (anonymous) | @ | react-dom.development.js:19914
  | unbatchedUpdates | @ | react-dom.development.js:19280
  | legacyRenderSubtreeIntoContainer | @ | react-dom.development.js:19910
  | render | @ | react-dom.development.js:19971
  | setTimeout (async) |   |  
  | (anonymous) | @ | ready.js:27
  | Promise.then (async) |   |  
  | __webpack_require__ | @ | bootstrap:723
  | fn | @ | bootstrap:100
  | 0 | @ | layout.scss?429b:45
  | __webpack_require__ | @ | bootstrap:723
  | (anonymous)
```

**Comment by wardpeet** [comment]
@san7hos you need to call fixed instead of fluid :)
`render={data => <Img fixed={data.image.childImageSharp.fixed} />}`

**Comment by san7hos** [comment]
Well, of course. I am officially blind. (That is why you shouldn't code after midnight.) Thanks!

**Comment by wardpeet** [comment]
I like where this thread is going but I think this issue is fixed and would like to suggest to create new issue:

> Fail gatsby build when prop types are throwing warnings.

In develop this can be just a warning but we should stop our build or at least show it in our build process.

WDYT @gatsbyjs/core ?

**Comment by SuperKleber** [comment]
Hello, the warning disappears as follows.

My problem:

I passed the following attribute to a component

`image.childImageSharp.fluid`

and in that component rendered the image.
More or less like this

`
//Father Component
const FatherComponent = ({ pageContext }) => {  
  return (
    <ChildComponent img={pageContext.img.childImageSharp.fluid}/>
  )
}
//Child Component
const ChildComponent = ({ img }) => {  
  return (
    <Image fluid={img}/>
  )
}
`


My solution was that in the Father component DO NOT pass the attribute `img.childImageSharp.fluid`
to the Son component,
instead, I passed the `img` attribute.
In the child component is where I rendered the image with `img.childImageSharp.fluid`

Solution example:

`
//Father Component
const FatherComponent = ({ pageContext }) => {  
  return (
    <ChildComponent img={pageContext.img}/>
  )
}
//Child Component
const ChildComponent = ({ img }) => {  
  return (
    <Image fluid={img.childImageSharp.fluid}/>
  )
}
`


I don't quite understand why this eliminates that annoying Warning, but it worked for me, regards.

**Comment by polarathene** [comment]
@SuperKleber  That has nothing to do with aspectRatio that this issue talks about. You should create a new issue in future instead if there is not a relevant issue. 

You should also share the actual warning received if it was to be of any use to anyone else.
