### ISSUE TITLE
Where is the docs source for gatsby-plugin-cockpit actually located?

### ISSUE THREAD

**Issue by ununseptium** [gatsbyjs/gatsby#10663]
Ahoy and merry Christmas 🎄 🎅 🎅 , 

i searched through the gatsby package docs and found a few errors here and there and wanted to edit https://www.gatsbyjs.org/packages/gatsby-plugin-cockpit/ for example but when i click on 

`edit this page on GitHub` 

it redirects me to the directory where all the packages are in but not to this specific one. In fact i couldn't find it at all in the repo.

Where do the docs really come from is now my question, they have to be somewhere right?
Or am i just not supposed to edit this page?

Thanks in advance for any information about how your docs are build n'stuff. 🙂

**Comment by jgierer12** [comment]
Hi, based on the Readme content it seems like [andrewn/gatsby-plugin-cockpit-temp](https://github.com/andrewn/gatsby-plugin-cockpit-temp) is the source.

Unfortunately, the author didn't set a `homepage` field in their `package.json`, so there's no way of knowing for sure which repo is the source. For all we know, it might not even be on GitHub.

**Comment by sidharthachatterjee** [comment]
Merry Christmas @ununseptium  🎄 

The docs for `gatsby-plugin-cockpit` are coming from `npm`

For packages that are not internal to the Gatsby organisation (and therefore not in this monorepo), docs are retrieved from the package's README on `npm` and in this case https://www.npmjs.com/package/gatsby-plugin-cockpit

Relevant code that does this is at https://github.com/gatsbyjs/gatsby/blob/a13c81295ccb4b605464e80826317749926ef6f4/www/src/templates/template-docs-remote-packages.js#L44 and https://github.com/gatsbyjs/gatsby/blob/a13c81295ccb4b605464e80826317749926ef6f4/www/gatsby-node.js#L395

If the `npm` package has the `url` key set, we link to it or if not, we link to `https://github.com/search?q=${npmPackage.name}`

Hope this clears the confusion!

**Comment by ununseptium** [comment]
Yeah this helps alot, thanks for clearing that up.
