### ISSUE TITLE
gatsby-plugin-raygun

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#10693]
## Summary

There is currently no plugin to use Raygun with Gatsby. I'd like to write one, but before I do I'd like to outline what I propose and see if it makes sense.

Raygun offers [these docs](https://raygun.com/docs/pulse/getting-started) for configuring their tracking scripts. Their setup process involves adding three sets of `<script>` tag

1.  Downloads the Raygun lib
2. Configures the lib with the the api key
3. Configures the lib with user details

I believe that the third is irrelevant, so I think the plugin needs to provide an `id` config param and use Gatsby SSR api to add the first two scripts to the page head using `setHeadComponents`, only when the site is running in production.

Finally, I think the plugin needs to use Gatsby's `onRouteUpdate` Browser API to update Raygun to changes in the url:

```
exports.onRouteUpdate = ({ location }) => {
  // Track pageview with google analytics
  Raygun.trackEvent('pageView', {
      path: $location.pathname
    });
}

``` 

Does this sound like the correct approach?

### Motivation

There is currently no way to use Raygun on a Gatsby site.

**Comment by sidharthachatterjee** [comment]
Yes, that sounds good @Undistraction 

You can call `setHeadComponents` in [onRenderBody](https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody) 

If you're looking for the starting point to log the first pass of analytics, you can do that in `onClientEntry` and the rest `onRouteUpdate`

**Comment by Undistraction** [comment]
Built this, but not had permission from my company to open-source it. I'll try and get it out there soon.
