### ISSUE TITLE
Passing context from gatsby-node to the component

### ISSUE THREAD

**Issue by LpmRaven** [gatsbyjs/gatsby#10698]
Is it possible to pass context from the gatsby-node to the component itself?

I am trying to pass a title to the orderedListTemplate, I have no use for it in my graphql query, but the component (template) is re-usable so I can't declare it in the component itself. This component is used for multiple page all with different sorts. I dont want to duplicate the component simply to change a title.

```javscript 
createPage({
     component: orderedListTemplate,
      path: `${category}/best-${subCategory}-of-2019`,
      context: {
            category,
             subCategory,
             sort: { "fields": ["verdictRating"], "order": "DESC" }
             title: "This is the title for this type of page"
        },
})

createPage({
       component: orderedListTemplate,
       path: `${category}/latest-reviews-for-${subCategory}`,
       context: {
             category,
             subCategory,
             sort: { "fields": ["publishDate"], "order": "DESC" }
             title: "This is a different title with a different sort"
        },
})
```

**Comment by sidharthachatterjee** [comment]
Absolutely @LpmRaven 

You can access the `context` object in `props. pageContext` in your component.

**Comment by LpmRaven** [comment]
Perfect, thanks @sidharthachatterjee. Exactly what I was looking for. I'm not sure if this information is currently anywhere in the docs? I could only find information saying that the context is passed to the page graphql query.

**Comment by sidharthachatterjee** [comment]
For anyone else seeing in the future `pageContext` is documented at https://www.gatsbyjs.org/docs/actions/#createPage

**Comment by Dsingh-wp** [comment]
Hello There,

How I can pass this `pageContext ` to class component

**Comment by woeterman94** [comment]
When I try to access a context parameter in the HTML by using

`  <p>test: {data.pageContext.id}</p>`

I get: TypeError: Cannot read property 'id' of undefined

**Comment by orsi** [comment]
Same as above ^. I am not receiving the context from gatsby-node into the component PageProps as pageContext or in data property.

<img width="376" alt="Screen Shot 2021-09-03 at 12 59 54 PM" src="https://user-images.githubusercontent.com/7156655/132041877-791b867e-24d7-4257-9a9a-c4663b4c2fbe.png">
<img width="405" alt="Screen Shot 2021-09-03 at 1 00 21 PM" src="https://user-images.githubusercontent.com/7156655/132041915-90385a64-c10f-42ae-91d7-15a350251990.png">

No id or node_locale in Page props in any relevant fields:
<img width="416" alt="Screen Shot 2021-09-03 at 1 01 05 PM" src="https://user-images.githubusercontent.com/7156655/132041995-8b4e8492-fead-48e6-8a48-da0d24d87c72.png">
