### ISSUE TITLE
Investigate using/creating CircleCI orbs

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#10697]
## Summary

Orbs are a newer functionality available in CircleCI. In effect, they allow little re-usable blocks of functionality.

## Motivation

I see (minimally) two possible ways we could use and instrument these orbs:

1. Create our own, reusable orbs
    - These can be shared across all gatsbyjs repos, and if generally applicable, can be used by other non-gatsby projects as well
    - This will clean up some of our config, and DRY up some repetitive tasks
1. Use some existing reusable orbs
    - Haven't investigated this a ton, but one particularly interesting one is the [Cypress orb](https://circleci.com/orbs/registry/orb/cypress-io/cypress), particularly the parallelization feature

**Comment by LekoArts** [comment]
> particularly the parallelization feature

This is only available if you use their Dashboard service (didn’t know if we use that).

What orbs that we would create on our own had you in mind?

**Comment by DSchau** [comment]
@LekoArts the e2e test ones are a quick one that comes to mind. All we need is a path to a folder that contains cypress tests (and a `test` script), and we can encapsulate this in a re-usable orb that we can use throughout all Gatsby repos.

The caching is also something that's generally the same for all of our projects, so that could be worth sharing, as well.
