### ISSUE TITLE
SyntaxError: Unexpected token import [Gatsby new]

### ISSUE THREAD

**Issue by chickencoder** [gatsbyjs/gatsby#107]
Just installed gatsby via npm and then ran gatsby new and I am presented with...

```
/usr/local/lib/node_modules/gatsby/lib/utils/init-starter.js:2
import fs from 'fs'
^^^^^^

SyntaxError: Unexpected token import
```
node is at v5.1.0
gatsby is at 0.7.5

Any ideas?

**Comment by KyleAMathews** [comment]
Yes... so in this past release I rewrote the js with Babelscript and on
deploy compile it to a dist directory. That's pretty standard. What I
wasn't able to find a good pattern is for how to instruct the cli to use
the dist version only when it's installed by npm. I settled on looking in
the package.json for a key that NPM adds during packaging and I thought
that was working but perhaps not...

See https://github.com/gatsbyjs/gatsby/blob/master/bin/new.coffee for the
logic.

I won't have time to look at this until later tonight but if you'd like to
get moving trying gatsby, just clone gatsby and then run npm link and that
should work.

**Comment by KyleAMathews** [comment]
Published what I think should fix this in 0.7.6. @chickencoder please install the latest and tell me if things are working correctly. https://github.com/gatsbyjs/gatsby/commit/53c4e42ee49020f24a8153db98679bd0fb068404

**Comment by chickencoder** [comment]
Works a treat! Thanks very much :santa:

**Comment by KyleAMathews** [comment]
great!
