### ISSUE TITLE
Gatsby empties the image directory when building the site

### ISSUE THREAD

**Issue by hilja** [gatsbyjs/gatsby#10703]
## Description

Gatsby removes the contents of my static images directory.

I've got the following dir structure for my static images `static/img/foo`, and `/foo` is a soft link to `~/Dropbox/foo`.

When running `build` or `develop`, Gatsby wipes out the `static/img/foo`, though it leaves empty directories in there. Then errors with:

```
error ENOENT: no such file or directory, lstat '/Users/bob/web/my-gatsby-site/static/img/foo/sadface.jpg'
```

Worth noting that previously Gatsby errored saying that a symlink can't be created because `public/img/foo` exists. I removed that directory. I don't know how it supposed to work, should gatsby copy the `static/img` to `public/img`? Or soft link it?

### Steps to reproduce

Apparently having that `static/img/foo` to be a soft link might cause this. I tried it with a normal dir and that worked. Also worth noting that my `static/img/foo` is about 4 gigs in size and has something like 16 000 files in it.

### Expected result

Not 100% sure, soft link or copy the files from `static/img` to `public/img`.

### Actual result

The contents of `static/img/foo` is removed.

### Environment

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 4.4.23 - /usr/local/bin/bash
  Binaries:
    Node: 8.9.0 - ~/.nvm/versions/node/v8.9.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v8.9.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 57.0.4
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.38 => 2.0.76 
    gatsby-plugin-favicon: ^3.1.4 => 3.1.5 
    gatsby-plugin-google-analytics: ^2.0.7 => 2.0.8 
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4 
    gatsby-plugin-typography: ^2.2.4 => 2.2.4 
    gatsby-remark-responsive-iframe: ^2.0.6 => 2.0.8 
    gatsby-source-filesystem: ^2.0.7 => 2.0.12 
    gatsby-transformer-remark: ^2.1.11 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.3
```

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @hilja 

As far as I know, soft links will not work. Gatsby copies over the contents of `static` to `public` on every build. 

Does it work fine if `static/img` is a normal directory?

**Comment by hilja** [comment]
@sidharthachatterjee Yeah it does works.

Gatsby uses `fs-extra`, right? There's [`dereference`](https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md#copysrc-dest-options-callback) option in the `copy` method (though I'm not sure what that really does).

If that's not doable then maybe throw an error of some sort instead of clearing the directory. Good that I had backups :)

**Comment by hilja** [comment]
Something like this [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/get-static-dir.js#L13):

```
return fs.copySync(staticDir, nodePath.join(process.cwd(), `public`), { dereference: true })
```

**Comment by sidharthachatterjee** [comment]
> If that's not doable then maybe throw an error of some sort instead of clearing the directory. Good that I had backups :)

This is definitely something we should do, thank you for reporting it @hilja 

I'm going to test this and keep this open till we've fixed this behaviour.
