### ISSUE TITLE
Gatsby Build: Conditional Rollback on Failure

### ISSUE THREAD

**Issue by rwieruch** [gatsbyjs/gatsby#10701]
Minor question, because I couldn't find anything about it in the Gatsby documentation: Is there a way to tell Gatsby to fallback to the previous build if the new `gatsby build` fails? 

I am asking, because every time my production build fails, my web server returns a 403. It would be great to just fallback to the old Gatsby build then. I migrated over to Gatsby from Hugo. When I worked with Hugo, this was the default behaviour. That's why I am asking.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @rwieruch

We don't support this out of the box at the moment. Have you considered building your site in a temp directory and only moving assets over if the build succeeds?

**Comment by rwieruch** [comment]
Yes, that would be my solution 😃 Just wanted to make sure if I didn't miss any Gatsby feature related to it. 

In general I think it would be a great feature for transitioning seamlessly from build to build. Another benefit would be to avoid the down time in between builds where a web server sends also a 403. In a perfect world, only if the build succeeds, the new version is copied over. During the build, and in case the build fails, the previous version is kept alive (or linked to) in the public folder.

Anyway, thank you for your reply and for doing a great job with Gatsby.js. Every day I enjoy more using it ❤️

**Comment by rwieruch** [comment]
Any chance to put this on the Gatsby roadmap? I see so many people giving Gatsby a shot this year, would be great to have a seamless build/deployment experience 👍Otherwise we will see lots of 404 pages 😸 Thanks again for building and continuing to improve Gatsby.js! 💯

**Comment by rwieruch** [comment]
For anyone who runs into it, I solved it for my case with the following npm script:

```
"postbuild": "rm -rf production/ && cp -R public/ production/",
```

Now if a build fails, it doesn't copy the files into the *production/* folder. If the build succeeds, it wipes the *production/* folder and copies all content over from the *public/* folder. My webserver points to the *production/* folder now.

Note: There is no way to rename Gatsby's output directory for builds (see https://github.com/gatsbyjs/gatsby/issues/1878).
