### ISSUE TITLE
Make gatsby compatible with graphql-tools last version

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#10709]
I just found an issue when graphql-tools is updated on last version 
gatsby do not compile
Error:
Variable "$_v0_sort" got invalid value for desc -> do you mean DESC ?

graphql-tools need uppercase

to resolve this i changed in dist/schema/create-sort-field.js
 value 'asc' to 'ASC'
and value 'desc' to 'DESC'

now compile good
```
module.exports = function createSortField(typeName, fieldNames) {
....
  return {
....
          name: _.camelCase(`${typeName} sortOrder`),
          defaultValue: `ASC`,
          type: new GraphQLEnumType({
            name: _.camelCase(`${typeName} sortOrderValues`),
            values: {
              ASC: {
                value: `ASC`
              },
              DESC: {
                value: `DESC`
              }
...}
```

**Comment by LekoArts** [comment]
Hi!
How did it come that you updated `graphql-tools` ? It is only used internally and there should be no reason for you to update it.

**Comment by sidharthachatterjee** [comment]
Hey @simonjoom 

Thank you for reporting this! Any specific use case where you had to update `graphql-tools`? 

I'm not sure if the latest version has any other breaking changes but if this is the only change, we would love to accept a PR updating this. 🙂

**Comment by wardpeet** [comment]
@simonjoom can you give us a reproduction as I don't think that part of our code is the issue as it's a simple enum that is used by [lodash orderby](https://lodash.com/docs/4.17.11#orderBy).
