### ISSUE TITLE
Sharp transform non-deterministic for data with optional image fields

### ISSUE THREAD

**Issue by 0x80** [gatsbyjs/gatsby#10704]
## Description

I am using the Sharp transform on the `image` field of some markdown frontmatter, so it is converted in the GQL schema from a `String` type to a `childImageSharp` type. Things seemed to be working fine until I added some more content and the GQL schema broke with this error:

> error GraphQL Error Field "image" must not have a selection since type "String" has no subfields.

This indicates that the conversion of the schema failed and the image field wasn't transformed to a Sharp type.

Trying to figure out what was going on I removed some content and sometimes it worked again and sometimes it didn't. I assumed that something must be corrupt with my data or the images I was using so I tried removing and changing them. It really drove me nuts until I realized that the problem was not with any particular content.

The `image` field in my frontmatter is optional. And depending on the amount of files (and seemingly other factors) things are processed by Gatsby in a certain order. I suspect that the Sharp transform (or any other GQL schema transform) depends on the first data file that gets handled. It is never in a guaranteed order on my system. I might switch back to a commit that was working before to find that it isn't working this time, which makes debugging very confusing.

The schema update occurs after clearing the .cache folder, so if the schema is once successfully transformed you can add whatever content and it will keep working until you clear the cache.

To give an example; say you have 3 markdown files, and two of which have a frontmatter image field pointing to a file. One of the two files with an image is picked up first and the schema is transformed, allowing you to query the childImageSharp object. Then you add another markdown file. This causes the order of files to change and now a markdown file without an image is picked up, and the schema is not transformed resulting in a query error.

The same problem can occur if an image file is not found in which case the path will remain a string as well.

I realize that this problem is maybe not something that can be easily solved, because the GQL schema is inferred from the data it loads. It would need to process all files first in order to figure out which fields are optional, and even then if none of the content contains this optional field it still can't know about it. 

So I think this can only be solved by telling the transform plugin explicitly which nodes to target. For example in my case `childMarkdownRemark > frontmatter > image`.

I am not sure what the correct approach would be, but I do know that the current behavior can be highly confusing and frustrating. So if this is a problem that can't be solved in the near future, I think it deserves a warning in the docs at least.

What are your thoughts? Would it be feasible to add explicit data paths as an option to the transform plugin?

**Comment by 0x80** [comment]
I think my assessment of the problem might be a little off. I just found out that I have another md file in the repo with similar frontmatter pointing to a non-existing image file. This was probably the reason for distorting the schema transformation instead of the field being optional.

Still, a race-condition caused the schema to differ based on what was picked up first.

I'm pulling two types of data from added with Netlify CMS. Both have frontmatter with an image field. And I see now that the `childMarkdownRemark` in GQL is a mixture of the fields of both types of markdown files. 

This is not an issue as long as the fields in those files always have the same type, but this is definitely something to be aware of. You can't be ambiguous about the frontmatter field types, because Gatsby will pick one or the other based on whatever comes first (?)

**Comment by jbolda** [comment]
It seems that #11480 will alleviate this issue (maybe not "child" nodes though in the initial version).

(Thanks @pieh for the heads up.)

**Comment by 0x80** [comment]
@jbolda Yes, I think this can be closed in light of the new schema customization branch. So happy about that major update. Awesome work!
