### ISSUE TITLE
Where to store env variables like api accestokens in Gatsbyjs

### ISSUE THREAD

**Issue by ergunpp** [gatsbyjs/gatsby#10717]
I need to use accesstokens for external apis for my project. Where should I store them and call them when needed?

**Comment by LekoArts** [comment]
Hi!
Did you have a look at our docs regarding that topic?
https://www.gatsbyjs.org/docs/environment-variables/#environment-variables

Do you speak about access tokens for source plugins in `gatsby-config.js` or client-side in one of your components?

**Comment by ergunpp** [comment]
it is a custom aws api gateway access token

**Comment by LekoArts** [comment]
Yeah, but where do you use it? Was the documentation helpful?

**Comment by ergunpp** [comment]
I am using it  with a contact-form where onSubmit an ajax post is made using this token.

**Comment by jonniebigodes** [comment]
@ergunpp  picking up on what @LekoArts said and expanding from there.
With Gatsby and the underlying technology behind it, namely React, you have a multitude of approaches that you can take, this depending on code base you have.
You can access it via injection in `gatsby-config.js` file, as the majority of the plugins do, for instance, the [gatsby-source-wordpress](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/). Also with a .env file like @LekoArts said on his reply. Or If you want it more "close to home" you can store it on a component state like so:

```javascript
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import axios from 'axios' //http request library

class DummyComponent extends Component {
  state = {
    token: '',
    error:false,
  }

  handleWindowSizeChange = () => {
    this.setState({
      width: window.innerWidth,
    })
  }

  onSubmitHandler=e=>{
    e.preventDefault();
  }

  makeAWSDummyRequest=()=>{
    axios.get('http://yoururltoauth.com').then(result=>{
      const {data}= result
      const {authToken}= data
      this.setState({token:authToken})
      
    }).catch(err=>{
      this.setState({error:true})
    })
  }
  render() {
    const { token } = this.state // es6 destructuring of the state for "easier" access to it
    return (
      <div>
        <form onSubmit={this.onSubmitHandler}>
          <label>
            Name:
            <input type="text" name="name"/>
          </label>
          <input type="submit" value="Submit" onClick={this.makeAWSDummyRequest} />
        </form>
      </div>
    )
  }
}
DummyComponent.propTypes = {
  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node,
  ]).isRequired,
  mobile: PropTypes.bool,
}
DefaultLayout.defaultProps = {
  mobile: false,
}
export default DummyComponent

```
And with this you can store as long as the component is "alive".
If you need it to be stored for some time you can expand the code above with something like so:

```javascript

// not the best practice code example, just an ilustration of the case.
// loads the content from the browser storage
componentDidMount(){
    if (typeof window !== 'undefined') {
      const storedAuthtoken = JSON.parse(localStorage.getItem(myawstoken))
      this.setState({token:storedAuthtoken})
    }
  }

makeAWSDummyRequest=()=>{
    axios.get('http://yoururltoauth.com').then(result=>{
      const {data}= result
      const {authToken}= data
      this.setState({token:authToken})

      localStorage.setItem('myawstoken',JSON.stringify(authToken)) // saves it in the browser storage

    }).catch(err=>{
      this.setState({error:true})
    })
  }
```

Hope that @LekoArts and my response can shed some light on the issue at hand, or even resolve it. Feel free to provide some feedback on the issue at hand.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @ergunpp 

Since you need to access these tokens at runtime in the client, you can pass them as env variables. 

From https://www.gatsbyjs.org/docs/environment-variables/#environment-variables

> For Project Env Vars that you want to access in client-side browser JavaScript, you can define an environment config file, .env.development and/or .env.production, in your root folder. Depending on your active environment, the correct one will be found and its values embedded as environment variables in the browser JavaScript.

**Please note that any tokens included in the client side bundle are public and only include tokens with extremely limited privilege**

**Comment by sidharthachatterjee** [comment]
@ergunpp Closing this for now but please feel free to reopen if there is anything else

**Comment by devmithunnath** [comment]
Hey, I'm just a beginner in Gatsby, currently writing a project using Hasura and Auth0 with Gatsby. I just wanted to get an idea of how I can query the data from Hasura using the JWT from auth0. 

I know we store tokens on the .env files and access them at gatsby-config.js (BTW I'm using "gatsby-source-graphql" plugin to connect with Hasura endpoint). But, when it comes to a backend where users can log in and see/update their information, we will need to pass different JWT each time. I'm not sure how we can pass JWT to the "gatsby-source-graphql" plugin in this case! 

Thanks for helping :-)
