### ISSUE TITLE
gatsby-image ref conceals DOM attributes

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#10723]
## Description

Passing a `ref` to `gatsby-image` results in unexpected behavior.

### Steps to reproduce

Usually the following gives me access to the DOM node, in particular to attributes like [`offsetTop`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetTop) and [`getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect).
```jsx
import React, { Component, createRef } from 'react'
import Img from 'gatsby-image'

export default class MyComponent extends Component {
  ref = createRef()

  render() {
    return (
      <>
        <Img ref={this.ref} fluid={this.props.fluid} />
        <p>{JSON.stringify(this.ref.current)}</p>
      </>
    )
  }
}
```
With `gatsby-image`, you instead get a `ProxyComponent` without the above mentioned attributes.
```
this.ref.current : 
ProxyComponent {props: {…}, context: {…}, refs: {…}, updater: {…}, state: {…}, …}
REACT_HOT_LOADER_RENDERED_GENERATION: 5
context: {}
handleImageLoaded: ƒ ()
handleRef: ƒ ()
imageRef: {current: img}
props: {fluid: {…}, critical: false, fadeIn: true, alt: "", Tag: "div", …}
refs: {}
state: {isVisible: true, imgLoaded: true, IOSupported: true, fadeIn: true, hasNoScript: true, …}
updater: {isMounted: ƒ, enqueueSetState: ƒ, enqueueReplaceState: ƒ, enqueueForceUpdate: ƒ}
__reactstandin__isMounted: true
__reactstandin__proxyGeneration: 1
_reactInternalFiber: FiberNode {tag: 1, key: null, elementType: ƒ, type: ƒ, stateNode: ProxyComponent, …}
_reactInternalInstance: {_processChildContext: ƒ}
isMounted: (...)
replaceState: (...)
__proto__: Image
```

It took me a while to notice that the actual DOM node is nonetheless accessible but "hidden" under `this.ref.current.imageRef.current`.

### Issues

There are two problems with this:

1. This should be documented in the [`gatsby-image` readme](https://www.gatsbyjs.org/packages/gatsby-image). If everyone agrees, I'm happy to submit a PR. Before though, I'd like to ask the following question.
2. I'm passing the `ref` to a `styled-component` that uses the [polymorphic `as` prop](https://www.styled-components.com/docs/api#as-polymorphic-prop) to sometimes render as a `gatsby-image`, sometimes as something else, but always requires access to DOM attributes such as `offsetTop`.
I could of course look in both places, i.e. `this.ref.current.offsetTop || (this.ref.current.imageRef && this.ref.current.imageRef.current.offsetTop)` but I'm wondering if it might be possible to lift the DOM attributes from `ref.current.imageRef.current` to `ref.current` instead. This seems cleaner to me and would prevent others from having to scan through the readme to find out how to use `ref`s with `gatsby-image`.

**Comment by janosh** [comment]
cc @pieh

**Comment by rtymchyk** [comment]
Thanks for documenting. Was driving me nuts trying to do some parallax style stuff with the image.

**Comment by janosh** [comment]
@rtymchyk I had the exact same usecase. :)

**Comment by giraffesyo** [comment]
I totally agree on both points, or just forward the ref down to where we would expect it to be.

**Comment by wardpeet** [comment]
I think we made a booboo here. We shouldn't even have give access to the image ref. The problem is `this.handleRef.bind(this)`. We shouldn't have used createRef and forwardRef here.

So I'm not sure if we should document this XD. We can fix this is gatsby V3 but I don't think we can do it now without breaking.

I have a small example that fixes the ref issue.
https://codesandbox.io/s/ly8owlrw97

**Comment by wardpeet** [comment]
We'll have this fixed in gatsby-plugin-image. More info https://github.com/gatsbyjs/gatsby/discussions/27950.

I'll close it in the meantime
