### ISSUE TITLE
[gatsby-source-wordpress] Deploy failed of jetpack_featured_media_url(wpcom) on Netlify

### ISSUE THREAD

**Issue by qrac** [gatsbyjs/gatsby#10733]
I'm acquiring WordPress com (Free Plan) data at gatsby-source-wordpress. By default the Jetpack plugin is replaced by GraphQL `featured_media` by` jetpack_featured_media_url`.

```html
<img src={data.wordpressPost.jetpack_featured_media_url}>
```

There is no problem with local builds, but Netlify gives errors asking for subfields.

```bash
3:01:19 PM: error GraphQL Error Field "jetpack_featured_media_url" of type "wordpress__wp_media" must have a selection of subfields. Did you mean "jetpack_featured_media_url { ... }"?
3:01:19 PM:   file: /opt/build/repo/src/templates/post.js
3:01:19 PM:    7 |       title
3:01:19 PM:    8 |       slug
3:01:19 PM:    9 |       categories {
3:01:19 PM:   10 |         name
3:01:19 PM:   11 |         slug
3:01:19 PM:   12 |       }
3:01:19 PM:   13 |       tags {
3:01:19 PM:   14 |         name
3:01:19 PM:   15 |         slug
3:01:19 PM:   16 |       }
3:01:19 PM: > 17 |       jetpack_featured_media_url
3:01:19 PM:      |       ^
3:01:20 PM:   18 |       content
3:01:20 PM:   19 |       excerpt
3:01:20 PM:   20 |     }
3:01:20 PM:   21 |   }
3:01:20 PM:   22 |
```

Since `jetpack_featured_media_url` does not have subfields, I'd like to avoid this, but is there any way?

- "gatsby": "^2.0.78"
- "gatsby-source-wordpress": "^3.0.21"

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @qrac 

Can you potentially link to a minimal reproduction repo?

> There is no problem with local builds

Do you mean during `develop` or `build`? Is the local build hitting the same instance of WordPress?

**Comment by qrac** [comment]
@sidharthachatterjee Thank you for your reply. Immediately, I created a repository that can reproduce bugs based on starter.

https://github.com/qrac/gatsby-wpcom-test

Local uses the same instance, and `jetpack_featured_media_url` can be used both in develop and build.

In WPcom plugin Jetpack is preinstalled. Nice to meet you.
