### ISSUE TITLE
Gatsby-Source-Filesystem question

### ISSUE THREAD

**Issue by pomegranitedesign** [gatsbyjs/gatsby#10741]
So I have installed the __"gatsby-source-filesystem"__ into my gatsby project.

And everything is getting compiled normally. 
![image](https://user-images.githubusercontent.com/29613240/50565681-3bbdd080-0cff-11e9-93ab-b723511f77f0.png)

__But__, on the __localhost:8000/___graphql__ I am still not able to run the ___"allFile"___ query
![image](https://user-images.githubusercontent.com/29613240/50565695-690a7e80-0cff-11e9-8e5b-d1af2db0ffc9.png)

# My gatsby-config.js
![image](https://user-images.githubusercontent.com/29613240/50565710-850e2000-0cff-11e9-8c5a-0f14629f057d.png)

**Comment by sidharthachatterjee** [comment]
Hey @pomegranitedesign 

Could you please link to a minimal reproduction if possible? That’ll help us in debugging this.

**Comment by jonniebigodes** [comment]
@pomegranitedesign i've picked up on your issue and i was able to reproduce it.
I cloned the starter repo, added the `gatsby-source-filesystem` plugin and created the folder `posts`
Which leads to something like the following:
```
|src
  |--components
  |--images
  |--pages
  |--posts
```
After making the adjustments to the `gatsby-config.js` file and issuing `gatsby develop`, for it to emulate your issue, which results in the following content of the file:
```javascript
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `posts`,
        path: `${__dirname}/src/posts`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.app/offline
    // 'gatsby-plugin-offline',
  ],
}

```
 With a empty folder, you'll not have access to that query.
I moved onto putting some files inside and after that the query is available.

```
|src
  |--components
  |--images
  |--pages
  |--posts
      |--a.md
      |--b.md
```
You'll have access to the query.
I've expanded it even further by creating the following structure.
```
|src
  |--components
  |--images
  |--pages
  |--posts
      |--FolderA
         |--a.md
      |--FolderB
         |--b.md
```
And with this structure the query will also be available to you.
From what knowledge and experience, what is happening ist that plugin will check the path defined in the options and see if it has any contents, if so it will "activate" the query, otherwise no content no need for that query to added and avoid extra work.

**Comment by pomegranitedesign** [comment]
> 
> 
> @pomegranitedesign i've picked up on your issue and i was able to reproduce it.
> I cloned the starter repo, added the `gatsby-source-filesystem` plugin and created the folder `posts`
> Which leads to something like the following:
> 
> ```
> |src
>   |--components
>   |--images
>   |--pages
>   |--posts
> ```
> 
> After making the adjustments to the `gatsby-config.js` file and issuing `gatsby develop`, for it to emulate your issue, which results in the following content of the file:
> 
> ```js
> module.exports = {
>   siteMetadata: {
>     title: `Gatsby Default Starter`,
>     description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
>     author: `@gatsbyjs`,
>   },
>   plugins: [
>     `gatsby-plugin-react-helmet`,
>     {
>       resolve: `gatsby-source-filesystem`,
>       options: {
>         name: `posts`,
>         path: `${__dirname}/src/posts`,
>       },
>     },
>     `gatsby-transformer-sharp`,
>     `gatsby-plugin-sharp`,
>     {
>       resolve: `gatsby-plugin-manifest`,
>       options: {
>         name: `gatsby-starter-default`,
>         short_name: `starter`,
>         start_url: `/`,
>         background_color: `#663399`,
>         theme_color: `#663399`,
>         display: `minimal-ui`,
>         icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
>       },
>     },
>     // this (optional) plugin enables Progressive Web App + Offline functionality
>     // To learn more, visit: https://gatsby.app/offline
>     // 'gatsby-plugin-offline',
>   ],
> }
> ```
> 
> With a empty folder, you'll not have access to that query.
> I moved onto putting some files inside and after that the query is available.
> 
> ```
> |src
>   |--components
>   |--images
>   |--pages
>   |--posts
>       |--a.md
>       |--b.md
> ```
> 
> You'll have access to the query as you can see in the image bellow
> ![allfileavailable](https://user-images.githubusercontent.com/22988955/50606718-99e4e200-0ebe-11e9-9184-0ab323b8a114.png)
> 
> I've expanded it even further by creating the following structure.
> 
> ```
> |src
>   |--components
>   |--images
>   |--pages
>   |--posts
>       |--FolderA
>          |--a.md
>       |--FolderB
>          |--b.md
> ```
> 
> And with this structure the query will also be available to you.
> From what knowledge and experience, what is happening ist that plugin will check the path defined in the options and see if it has any contents, if so it will "activate" the query, otherwise no content no need for that query to added and avoid extra work. Feel free to provide some feedback if my comment helped you out in any way. Or if not provide us with some extra information so that we can move from there.
---
# __This is still not working on my machine at some point...__
![image](https://user-images.githubusercontent.com/29613240/50611227-aad42a00-0ea3-11e9-92a2-a8252bc2f9a7.png)

# posts folder 
![image](https://user-images.githubusercontent.com/29613240/50611255-b6275580-0ea3-11e9-9e38-2dc44b11bd34.png)

# gatsby-config.js
![image](https://user-images.githubusercontent.com/29613240/50611270-c0e1ea80-0ea3-11e9-883a-558ce0555e92.png)

# localhost:8000/___graphql
![image](https://user-images.githubusercontent.com/29613240/50611320-eb33a800-0ea3-11e9-9874-66be3be57227.png)

**Comment by m-czernek** [comment]
The same happened to me. I verified that `rimraf` worked. Thank you for the solution.
