### ISSUE TITLE
Feature Request: Dynamic year in footer

### ISSUE THREAD

**Issue by jacobsowles** [gatsbyjs/gatsby#10756]
## Summary

Currently, the copyright year is hard-coded to 2018 in the footer. Ideally, it would be dynamically generated via JavaScript.

### Motivation

As it stands, every Gatsby user will need to go in and manually update the year in the footer annually. It would be nice to eliminate that need.

**Comment by jacobsowles** [comment]
I can make this change if the feature request is approved.

**Comment by sidharthachatterjee** [comment]
Hey @jacobsowles

We’d love to accept a PR for this. Just FYI, the copyright footer is in both the default and blog starters. 

Thanks!

**Comment by jacobsowles** [comment]
Awesome, I'm on it.
