### ISSUE TITLE
Gatsby build outputs unknown characters instead of HTML (gatsby develop runs fine)

### ISSUE THREAD

**Issue by jacoahmad** [gatsbyjs/gatsby#10750]
## Description
After migrating to Gatsby v2 & Followed all of the instructions from https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/
`gatsby develop` runs fine but after trying to build with `gatsby build` with success output, the page turns into unknown characters (lots of question mark)

`gatsby build` output:
![screen shot 2019-01-01 at 21 58 57](https://user-images.githubusercontent.com/33410950/50573985-fc7fa480-0e10-11e9-884a-b1c7a77200ba.png)

`gatsby serve` on localhost:9000
<img width="1439" alt="screen shot 2019-01-01 at 21 59 26" src="https://user-images.githubusercontent.com/33410950/50573988-086b6680-0e11-11e9-965e-2027bc32e251.png">

Network response
<img width="1435" alt="screen shot 2019-01-01 at 21 59 36" src="https://user-images.githubusercontent.com/33410950/50573991-14572880-0e11-11e9-927a-3313b3e63bda.png">

if anyone ever faced this please let me know.

### Steps to reproduce
Not sure how to reproduce this issue, since the project is a gatsby v1 project, I've changed a lot of configurations, can't share the repo because it's a company private repo.

### Expected result
every pages should returns an html elements

### Actual result
all pages returns unknown characters

### Environment

```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.79 => 2.0.79 
    gatsby-image: ^2.0.25 => 2.0.25 
    gatsby-plugin-catch-links: ^2.0.9 => 2.0.9 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-feed: ^2.0.11 => 2.0.11 
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8 
    gatsby-plugin-manifest: ^2.0.13 => 2.0.13 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-nprogress: ^2.0.7 => 2.0.7 
    gatsby-plugin-offline: ^2.0.20 => 2.0.20 
    gatsby-plugin-postcss-sass: ^1.0.22 => 1.0.22 
    gatsby-plugin-react-helmet: ^3.0.5 => 3.0.5 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-remove-trailing-slashes: ^2.0.6 => 2.0.6 
    gatsby-plugin-sass: ^2.0.7 => 2.0.7 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.17 
    gatsby-plugin-sitemap: ^2.0.4 => 2.0.4 
    gatsby-plugin-twitter: ^2.0.8 => 2.0.8 
    gatsby-plugin-typography: ^2.2.4 => 2.2.4 
    gatsby-remark-autolink-headers: ^2.0.12 => 2.0.12 
    gatsby-remark-copy-linked-files: ^2.0.8 => 2.0.8 
    gatsby-remark-images: ^3.0.1 => 3.0.1 
    gatsby-remark-prismjs: ^3.2.0 => 3.2.0 
    gatsby-remark-responsive-iframe: ^2.0.8 => 2.0.8 
    gatsby-source-filesystem: ^2.0.12 => 2.0.12 
    gatsby-source-medium: ^2.0.2 => 2.0.2 
    gatsby-transformer-remark: ^2.1.18 => 2.1.18 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.10 
```

**Comment by sidharthachatterjee** [comment]
Hey @jacoahmad 

Can you share the repo with me privately or try to make a minimal reproduction of this? This will help us in debugging this.

**Comment by jacoahmad** [comment]
Hi @sidharthachatterjee 

Thanks for responding, sure, I'll send you an invitation to forked repo.

**Comment by jacoahmad** [comment]
Hello @sidharthachatterjee, it turns out to be a gzipped file, sorry for my lack of experience facing gzipped files 😃 Thanks for the support

**Comment by sidharthachatterjee** [comment]
No problem at all, @jacoahmad

I’m glad it got resolved either way 🙂
