### ISSUE TITLE
Make computed Babel configuration accessible in Node API

### ISSUE THREAD

**Issue by silvenon** [gatsbyjs/gatsby#10753]
## Summary

It would be very useful to be able to access Gatsby's computed Babel configuration in the Node API, especially when developing plugins.

### Basic example

To make the final API consistent it would probably have to be a breaking change because `getConfig` in `onCreateWebpackConfig` would need to become `getWebpackConfig`, but a non-breaking version of the API might look like this:

```js
exports.onCreateBabelConfig = ({ actions }) => {
  actions.setBabelPreset({
    name: 'linaria/babel'
  })
}

exports.onCreateWebpackConfig = ({ actions, getConfig, getBabelConfig, stage }) => {
  // returns Babel configuration AFTER applying "linaria/babel" preset
  console.log(getBabelConfig())
}
```

### Motivation

I'm building a plugin which consists of a Babel preset and a webpack loader. The webpack loader is looking for the project's Babel configuration, but instead I want to pass it Gatsby's computed Babel configuration, so that people using my plugin don't have to create a custom Babel configuration on their own to make my Gatsby plugin work.

**Comment by sidharthachatterjee** [comment]
This should be easy to do I think since we already have the applied config in redux. @pieh can confirm this

**Comment by wardpeet** [comment]
@silvenon this is a bit more advanced but have you tried https://www.gatsbyjs.org/docs/add-custom-webpack-config/#modifying-the-babel-loader

I'm unsure what the best practices are here and that we even want to expose babelConfig. maybe @pieh or @DSchau can help.

**Comment by silvenon** [comment]
@wardpeet yes, that's how I was planning to modify the webpack configuration to add another loader after babel-loader, but I need to pass that loader the computed Babel configuration object as options. Did I understand you correctly?

**Comment by sidharthachatterjee** [comment]
@silvenon From the documentation page that @wardpeet linked to 

> // Unless you're replacing Babel with a different transpiler, you probably
>       // want this so that Gatsby will apply its required Babel
>       // presets/plugins.  This will also merge in your configuration from
>       // `babel.config.js`.
>       ...loaders.js(),

This is evaluate down to 
```
{ options: undefined,
  loader:
   'node_modules/gatsby/dist/utils/babel-loader.js' }
```
Adding anything else inside the object where `loaders.js` is spread will let you add _overrides_

If I understand your use case correctly, your plugin should be able to add its overrides here

**Comment by silvenon** [comment]
AFAIK, `node_modules/gatsby/dist/utils/babel-loader.js` is where the Babel config merging logic happens. I want to get that config and pass it to my loader as well. Here's some code (I'm using `rules` instead of `loaders` because it's easier):

```js
exports.onCreateWebpackConfig = ({ actions, rules, getConfig, getBabelConfig }) => {
  const jsRule = rules.js();
  const jsRuleWithMyLoader = {
    ...jsRule,
    use: [
      ...jsRule.use,
      {
        loader: 'my-loader',
        options: {
          babelConfig: getBabelConfig(),
        }
      },
    ],
  };
  // ...merge with the webpack config...
}
```

If I leave this option blank, `my-loader` will only pick up Babel configuration from `babel.config.js`. If I happen to be using gatsby-plugin-flow which modifies Babel config, `my-loader` won't know about it.

Sorry if I'm not getting it, can you show me what I can do to point my plugin to the right direction?

**Comment by wardpeet** [comment]
I've talked this through with @pieh & @DSchau and we agreed that it's a handy feature. Sadly it's not widely requested and only used for a few libraries on the web like linaria. We have other priorities atm so if you want to take a stab at it, that would be awesome! 🙌

**Comment by silvenon** [comment]
That's ok 😄 This is open source, there are no expectations, I'm happy that you're considering it at all. 😉

**Comment by wardpeet** [comment]
We're happy to help you giving pointers on where to get started 😄

**Comment by silvenon** [comment]
If I catch some time and dive into it, I'll ask questions then. 😄

**Comment by silvenon** [comment]
You're right, gatsbot, no need to keep this open. I'll submit a PR when or if I get around to it.
