### ISSUE TITLE
Question: Suggestions on client-side searching?

### ISSUE THREAD

**Issue by rstacruz** [gatsbyjs/gatsby#1075]
What would be a good way to implement client-side site searching? Outside gatsby, I'd do it this way:

- In my build process, use [lunr](https://www.npmjs.com/package/lunr) to build an index into a `search_index.json` file of sorts.
- In the client-side JS, load up this JSON file into Lunr.

It seems like this solution doesn't have an analogue in Gatsby... or does it?

**Comment by jbolda** [comment]
Are you working on the 0.12.X branch? If so, I suspect that you could do it in the html.js and the templates. Similar to how a few of the examples use react-helmet.

I think the 1.0 branch will make this much easier.

**Comment by KyleAMathews** [comment]
Yeah you can totally do it this way — check out the `postBuild` API https://github.com/gatsbyjs/gatsby#perform-additional-post-build-step

Just generate the JSON file there and write it out to the `public` directory.

@jbolda the main difference in v1 is that you have access to the GraphQL schema for querying the processed/structured data. Not sure what you'd use react-helmet for here?

**Comment by jbolda** [comment]
@KyleAMathews not actually using react-helmet, but just structuring it similarly. Hmm, I thought one of the starters had an example, but perhaps not.

Probably easiest to use the `postBuild` api for now rather then get crazy with nested templates.

**Comment by rstacruz** [comment]
> Are you working on the 0.12.X branch? If so, I suspect that you could do it in the html.js and the templates. Similar to how a few of the examples use react-helmet.

Yes I am!

**Comment by kmorf** [comment]
@rstacruz gatsby-plugin-elasticlunr-search is not compatible with Gatsby v2. Is there any workaround or a code snippet where I can generate the search index manually?

**Comment by rstacruz** [comment]
gatsby-plugin-elasticlunr-search (1.0.4) should be fine even with the latest Gatsby (2.0.31), but you may need to change the graphql dependency version. You can do this using package.json's [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) configuration (only available in Yarn, though).
