### ISSUE TITLE
Gatsby build failing with "WebpackError: TypeError: Cannot read property 'site' of undefined"

### ISSUE THREAD

**Issue by johnbuche2000** [gatsbyjs/gatsby#10768]
## Description

When running "gatsby build" I get the following error:

success open and validate gatsby-configs — 0.025 s
success load plugins — 0.378 s
success onPreInit — 2.513 s
success delete html and css files from previous builds — 0.095 s
success initialize cache — 0.011 s
success copy gatsby files — 0.293 s
success onPreBootstrap — 0.090 s
⠂ source and transform nodesStarting to fetch data from Contentful
Fetching default locale
⡀ source and transform nodesdefault locale is : en-US
⠐ source and transform nodescontentTypes fetched 1
Updated entries  0
Deleted entries  0
Updated assets  0
Deleted assets  0
Fetch Contentful data: 309.141ms
success source and transform nodes — 0.423 s
success building schema — 1.154 s
success createPages — 0.001 s
success createPagesStatefully — 0.106 s
success onPreExtractQueries — 0.002 s
success update schema — 0.107 s
warning Using the global `graphql` tag is deprecated, and will not be supported in v3.
Import it instead like:  import { graphql } from 'gatsby' in file:
/Users/uchennaabakporo/Documents/my-default-starter/src/layouts/index.js
warning The GraphQL query in the non-page component "/Users/uchennaabakporo/Documents/my-default-starter/src/layouts/index.js" will not be run.
Exported queries are only executed for Page components. Instead of an exported
query, either co-locate a GraphQL fragment and compose that fragment into the
query (or other fragment) of the top-level page that renders this component, or
use a <StaticQuery> in this component. For more info on fragments and
composition, see http://graphql.org/learn/queries/#fragments and for more
information on <StaticQuery>, see https://gatsbyjs.org/docs/static-query
success extract queries from components — 0.200 s
success run graphql queries — 0.014 s — 4/4 323.75 queries/second
success write out page data — 0.006 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 37.801 s

success Building production JavaScript and CSS bundles — 29.388 s

error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://gatsby.app/debug-html

  10 |       <div>
  11 |         <Helmet
> 12 |           title={data.site.siteMetadata.title}
     |                       ^
  13 |           meta={[
  14 |             { name: 'description', content: data.site.siteMetadata.description },
  15 |             { name: 'keywords', content: data.site.siteMetadata.keywords },

  WebpackError: TypeError: Cannot read property 'site' of undefined

  - index.js:12 Layout
    lib/src/layouts/index.js:12:23

  - bootstrap:25 a.render
    lib/webpack/bootstrap:25:1

  - bootstrap:24 a.read
    lib/webpack/bootstrap:24:1

  - bootstrap:36 renderToString
    lib/webpack/bootstrap:36:1

  - static-entry.js:190 Module.default
    lib/.cache/static-entry.js:190:18

  - bootstrap:24 Promise
    lib/webpack/bootstrap:24:1

  - gatsby-browser-entry.js:33 Promise._resolveFromExecutor
    lib/.cache/gatsby-browser-entry.js:33:9

  - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1

  - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1

  - bootstrap:50 MappingPromiseArray._promiseFulfilled
    lib/webpack/bootstrap:50:1

  - api-runner-ssr.js:8 MappingPromiseArray.PromiseArray._iterate
    lib/.cache/api-runner-ssr.js:8:1

  - bootstrap:67 MappingPromiseArray.init
    lib/webpack/bootstrap:67:1

### Steps to reproduce
run gatsby build

### Expected result

Build should complete without any errors or warnings

### Actual result

Error described above that prevents the build from executing

### Environment

 System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.81 => 2.0.81
    gatsby-image: ^2.0.20 => 2.0.25
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12
    gatsby-plugin-offline: ^2.0.16 => 2.0.20
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5
    gatsby-plugin-sharp: ^2.0.17 => 2.0.17
    gatsby-source-contentful: ^2.0.22 => 2.0.22
    gatsby-source-filesystem: ^2.0.12 => 2.0.12
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.8

**Comment by sidharthachatterjee** [comment]
> The GraphQL query in the non-page component "/Users/uchennaabakporo/Documents/my-default-starter/src/layouts/index.js" will not be run.

@johnbuche2000 Based on this, it appears that the query isn’t being run because it’s in the layout component? Exported queries are only run in page components. You could use a StaticQuery for this. 

In case that doesn’t solve the issue, can you please link to a minimal reproduction repository?
