### ISSUE TITLE
Write guide page on using redirects w/ hosting environment

### ISSUE THREAD

**Issue by shashi127** [gatsbyjs/gatsby#1076]
Can we have multiple URL's to the same html page. 
Below is the one of the URL -
http://sample.domain.com/article/summer-article
And, I wants to have a tiny url as  well which should refer to the same html page. 
http://sample.domain.com/new-article

Is there any way to add route path without creating multiple HTML page. Can I refer two urls to the same page in gatsby?

I tried to add below rewrite rule in netlify but its shows up a blank page.
netlify rewite rule:
/new-article   /article/summer-article   200
after page load it will append below query string and page will disappears.  
/new-article#/?_k=xx4xx7

[gatsby 1.0 alpha13]

**Comment by scottyeck** [comment]
If you don't want to use `exports.createPage` in `gatsby-node.js` to create a new page, you'll have to achieve this on the server-side, which is outside of the scope of _gatsby_.

That said, why don't you want that extra HTML page - it will create a much better experience for your user, as a client-side redirect driven by `react-router` will be the most performant solution.

**Comment by scottyeck** [comment]
FWIW, I'm working on an example that outlines what I just described and will eventually pull it into a plugin. Feel free to take a look: https://github.com/gatsbyjs/gatsby/pull/1068

**Comment by shashi127** [comment]
I wants to avoid duplicate html generation while build time. Since I have HTML page generated already can I use the same for duplicate url's for same page.

**Comment by scottyeck** [comment]
Yeah - sounds like that would be best achieved with some sort of server-side configuration. Please somebody correct me if I'm wrong.

**Comment by KyleAMathews** [comment]
Generally speaking this sounds like a job for HTTP redirects not Gatsby. Gatsby can only produce files so any magic beyond files is up to your hosting environment. And for the job of URL aliases like you're describing, I'd use HTTP redirects. Decide on the canonical URL and then redirect other URLs to it.

The fun thing about Gatsby is this is easy to automate as part of the build process. Store the aliases for a page alongside its canonical URL and then write a query to pull out all the aliases and write those out to a redirects file of some sort (depending on your hosting environment).

**Comment by KyleAMathews** [comment]
This would be a good guide page so leaving it open for that.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
