### ISSUE TITLE
Merge gatsby-source-shopify2 and gatsby-source-shopify

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#10773]
[gatsby-source-shopify2](https://github.com/nikhilag/gatsby-source-shopify) seems to have some fixes to `gatsby-source-shopify`

> Note: This is based on the original plugin along with major fixes for localFile property of images and Gatsby V2.

@nikhilag Would you be interested in opening a pull request with those fixes back into gatsby-source-shopify?

Related issue at https://github.com/gatsbyjs/gatsby/issues/10711

**Comment by jserrao** [comment]
I've been trying to get some movement on the original maintainer of `gatsby-source-shopify` for a months, might be quasi-abandoned at this point.

**Comment by nikhilag** [comment]
@sidharthachatterjee All my fixes have already been pulled into gatsby-source-shopify. See https://github.com/angeloashmore/gatsby-source-shopify/commit/ef0ac1a33673a8324656c7bf804f83475752cb02 .
There were more changes afterwards and then it was moved to gatsby core. Not sure why it's not working as per https://github.com/gatsbyjs/gatsby/issues/10711 given that you already verified the plugin works fine.

**Comment by nikhilag** [comment]
@sidharthachatterjee The new version of gatsby-source-shopify should work properly now. See this change - https://github.com/gatsbyjs/gatsby/pull/10955
I will be deprecating my plugin.

**Comment by sidharthachatterjee** [comment]
Thanks for the clarity, @nikhilag 

Closing this issue now since [gatsby-source-shopify2](https://github.com/nikhilag/gatsby-source-shopify) is now deprecated
