### ISSUE TITLE
Question: replacing highlight.js

### ISSUE THREAD

**Issue by rstacruz** [gatsbyjs/gatsby#1077]
In my experience, highlight.js is pretty weak for JavaScript code. Here's how Highlight.js would process some simple code (dotted outline added to `span.hljs-*` elements):

![image](https://cloud.githubusercontent.com/assets/74385/26675749/ab0b333a-46f7-11e7-93e7-82171e3b1af4.png)

In contrast, here's how it'd be handled by [Prism](http://prismjs.com/):

![image](https://cloud.githubusercontent.com/assets/74385/26675939/50cbd8ce-46f8-11e7-864a-82df7bab2cc0.png)

So some questions:

- Are there any plans to let users easily switch between code highlighters? At the moment they're hard-coded into https://github.com/gatsbyjs/gatsby/blob/master/lib/loaders/markdown-loader/index.js, which can easily be replaced, but it seems excessive to reimplement the entire functionality of it just for that.

- Is Gatsby open to possibly using a different default highlighter like Prism?

**Comment by jquense** [comment]
Good question, I'm not sure t sure if there is a strong reason to use hljs I also tend to prefer prism

**Comment by KyleAMathews** [comment]
I was an ignorant fool when I picked highlight.js over prism back in the day :-) v1 is now using prismjs e.g. https://www.gatsbyjs.org/docs/packages/gatsby-remark-prismjs/

I'm not sure if we want to replace highlight.js as a default though... as that'd mean a breaking change as people would have to switch out the CSS they're using plus it's possible that highlight.js is better than prismjs in some ways that some people prefer etc. I don't want to do any more breaking changes for 0.x as 1.0 is about ready and I'm conserving my limited resources for perfecting that and helping people move over.

This is one of the big downsides to webpack loaders that transformations are difficult to modularize and what Gatsby v1 for the most part corrects. Now it'd be trivial for someone to write a `gatsby-remark-highlightjs` plugin (it'd be like 25 lines of code) and swap it in for the prismjs highlighter.

**Comment by davidtheclark** [comment]
> I was an ignorant fool when I picked highlight.js over prism back in the day

@KyleAMathews @rstacruz I'm really curious to hear more about your strong preference here. Is it just that you prefer the JavaScript syntax in Prism? Or are there other reasons? (Curious because I'm trying to pick between these myself, and having a hard time.)

**Comment by KyleAMathews** [comment]
It's not that strong actually :-) but prismjs does seem to have better support for JavaScript, especially JSX so that makes it a pretty strong choice for Gatsby. That being said, someone could easily make a highlight.js plugin for Gatsby as well.
