### ISSUE TITLE
Is there anyway to ignore unused variables?

### ISSUE THREAD

**Issue by codingphasedotcom** [gatsbyjs/gatsby#10779]
So I'm trying to scrollreveal library but I can't use it by importing the module because its dependencies use the "window" keyword and as you may know we can't use "window" with webpack because it gives us errors on build.

So I tried loading the scrollreveal in a script tag and everything works how it should with "gatsby build". but now when I use "gatsby develop" I keep getting an error
```html
<script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
```
```javascript
componentDidMount(){
  if (typeof window !== 'undefined') {
      window.sr = ScrollReveal()
      const sr = window.sr
      sr.reveal(this.refs.logo, {
        origin: 'left',
        duration: 1000,
        delay: 150,
        distance: '500px',
        scale: 1,
        easing: 'ease',
      })
}
```
```shell
ERROR  Failed to compile with 2 errors                                                2:51:17 PM

 error  in ./src/pages/courses/learn-polymer-3-googles-favorite-framework.js

Module Error (from ./node_modules/eslint-loader/index.js):

/Users/joesantosgarcia/code/cpdotcom/src/pages/courses/learn-polymer-3-googles-favorite-framework.js
  40:19  error  'ScrollReveal' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```
This is extremely frustrating because gatsby develop and gatsby build are not identical... 
what works on develop don't work on build and what works on build don't work on develop.

**Comment by jgierer12** [comment]
Hi, it seems like the module tries to execute browser-only code when it's first imported. To prevent that, you can asynchronously import it in `componentDidMount` like so:

```js
componentDidMount() {
  import('scrollreveal').then(({ default: ScrollReveal }) => {
    const sr = ScrollReveal()
    // ...
  })
}
```

**Comment by jgierer12** [comment]
By the way, you don't need to check for `window` in `componentDidMount` since that lifecycle hook only gets called in the browser.

And if you'd like to just ignore the eslint error, you can use the `global` pragma anywhere in your file (preferably at the very top):

```js
/* global ScrollReveal */

// Rest of your file
```

**Comment by codingphasedotcom** [comment]
> By the way, you don't need to check for `window` in `componentDidMount` since that lifecycle hook only gets called in the browser.
> 
> And if you'd like to just keep using your existing solution, you can use the `global` pragma anywhere in your file (preferably at the very top) to tell eslint that `ScrollReveal` is a global variable:
> 
> ```js
> /* global ScrollReveal */
> 
> // Rest of your file
> ```

Thank you  I know but with gatsby it was giving me errors when it was compiled the only thing that stopped it was to put that if statement as hack till I figure out what was going on. The thing that had me completely confused is why develop and build gave me 2 different results. I usually like to use my own webpack build but heard so much good things about gatsby decided to use it.

**Comment by codingphasedotcom** [comment]
> Hi, it seems like the module tries to execute browser-only code when it's first imported. To prevent that, you can asynchronously import it in `componentDidMount` like so:
> 
> ```js
> componentDidMount() {
>   import('scrollreveal').then(({ default: ScrollReveal }) => {
>     const sr = ScrollReveal()
>     // ...
>   })
> }
> ```

This worked perfectly thank you

**Comment by jgierer12** [comment]
I'm glad you were able to solve your issue!

> The thing that had me completely confused is why develop and build gave me 2 different results

Yes, this is a major pain point right now and we are currently working on making the prod and dev builds more similar to prevent these kind of confusions in the future - see https://github.com/gatsbyjs/gatsby/issues/10706.
