### ISSUE TITLE
https error error in development mode 

### ISSUE THREAD

**Issue by eLeontev** [gatsbyjs/gatsby#10774]
Provided command `gatsby develop --https` mentioned in oficial docs (https://www.gatsbyjs.org/docs/local-https/)  throws the error: 
![image](https://user-images.githubusercontent.com/15786916/50599016-b896a900-0ebd-11e9-8c81-dbd42fa932ee.png)

**More details:** it's the first loading of https, so line `info setting up SSL certificate (may require sudo)` is displayed but without opportunity to set the password.

**OS:** Win10
**CLI:** Command Prompt

**Comment by gurpreet-hanjra** [comment]
It works on Mac. Do you have openssl ( https://www.openssl.org/docs/man1.0.2/apps/openssl.html ) on your machine? Maybe try type `openssl` in cmd to verify.

**Comment by jgierer12** [comment]
This looks like Git Bash, is that correct? Could you try the same command in Windows CMD or PowerShell?

**Comment by eLeontev** [comment]
Command prompt is default CLI for Win. Succefully launched on Git Bush only. Looks strange, but works only in that CLI even after confirmation of certificate.

**Comment by gurpreet-hanjra** [comment]
@eLeontev Hello, just want to check if you still facing issues with https in development.
