### ISSUE TITLE
The page is always refreshed automatically in IE9.

### ISSUE THREAD

**Issue by Dogtiti** [gatsbyjs/gatsby#10789]
```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

Question:
The pages created by `createPage` in `gatsby-node.js` as follow : 
```javascript
const path = require('path')

const makeRequest = (graphql, request) => new Promise((resolve, reject) => {
    resolve(
        graphql(request).then(result => {
            if (result.errors) {
                reject(result.errors)
            }

            return result;
        })
    )
});
  const getDocument = makeRequest(graphql, `
        {
            allStrapiDocument(sort: {order: DESC, fields: strapiId}) {
              edges {
                previous{
                    id
                    title
                }
                next{
                    id
                    title
                }
                node {
                  id
                  title
                  content
                  createdAt
                }
              }
            }
          }
        `).then(result => {
        result.data.allStrapiDocument.edges.forEach((item) => {
            createPage({
                path: `/${item.node.id}`,
                component: path.resolve(`src/template/servers/temDocuments.js`),
                context: {
                    id: item.node.id,
                    next: item.next,
                    previous: item.previous
                }
            })
        })
    });
```
And these is where I use the pages:
```javascript
  <div className="server_documents_content">
                    {newArr.map(item => (
                        <Link to={`${item.node.id}`} key={item.node.id}>
                            <div className="server_documents_content-wrap">
                                <div className="info"><span>{item.node.title}</span></div>
                                <span className="date">{toReadableDate(item.node.createdAt)}</span>
                            </div>
                        </Link>
                    ))}
                </div>
```
These pages are working  properly except `IE9`, in `IE9`,the pages will auto refresh all the time,and it didn't throw any error.

**Comment by gbbns** [comment]
Have you included polyfills? 

[React browser support docs](https://reactjs.org/docs/react-dom.html#browser-support)

**Comment by Dogtiti** [comment]
@gbbns yeah,I have added it

**Comment by sidharthachatterjee** [comment]
Hey @Dogtiti 

Can you please link to a minimal reproduction repo?

**Comment by Dogtiti** [comment]
@sidharthachatterjee  I have to add this to stop refresh the page,although it stoped , but some component became unable to work 
```
                   <Helmet>
                        <script type="text/javascript">
                            {` window.onbeforeunload = function() {
                         return "Dude, are you sure you want to leave? Think of the kittens!";
                            }`}
                        </script>
                    </Helmet>
```
and I found `IE9` thorw an error like this:
![image](https://user-images.githubusercontent.com/38354472/50720002-f4a95400-10df-11e9-82da-1d830d7c95cc.png)
And I guess it maybe wrong in `gatsby-node.js` here:
```
const path = require('path')

const makeRequest = (graphql, request) => new Promise((resolve, reject) => {
    resolve(
        graphql(request).then(result => {
            if (result.errors) {
                reject(result.errors)
            }

            return result;
        })
    )
});
```

**Comment by jonniebigodes** [comment]
@Dogtiti i still have a strapi installation in my pc, since our first "interaction". i'm going to adjust my code to reflect your change and get back to you. Sounds good?

**Comment by Dogtiti** [comment]
@jonniebigodes thanks, and I'll try to provide the repo as soon as possible.

**Comment by Dogtiti** [comment]
@jonniebigodes @sidharthachatterjee here is the repo which reproduces the problem. 
[repo](https://github.com/Dogtiti/gatsby-debug.git)

**Comment by Dogtiti** [comment]
@jonniebigodes thanks 👍

**Comment by Dogtiti** [comment]
@jonniebigodes @sidharthachatterjee Hey,  have any good news?

**Comment by jonniebigodes** [comment]
@Dogtiti sorry for the long wait. But i caught a case of the "bubonic plague"(pardon the bad pun), aka a really bad cold. With that the exposure to computer was limited to a small degree, if you don't mind being a bit more patient, but tomorrow, as where i'm at is still friday, i'll make some more tests on the code i have and provide a answer for your issue. Also a small matter side item, is your issue #10466 resolved ? If so, please notify so that it can be closed if you don't mind. Once again sorry once more for the long wait.

**Comment by Dogtiti** [comment]
@jonniebigodes Thank you very much for providing such a detailed answer. I will try to change the problem you mentioned as soon as possible to see if it works. Also, I wish you a speedy recovery！

**Comment by jonniebigodes** [comment]
@Dogtiti no thanks are in order, you were due a explanation and i was at fault as i've committed to provide you with a answer/solution for your problem. And i should be the one to thank you for your concern and the worst part is over. good old chicken soup always does the trick 😁. Hoping to see if my comment solved your issue. Feel free to provide some feedback when you can.

**Comment by Dogtiti** [comment]
@jonniebigodes 
Thanks again！All things work well! I'll close it!
