### ISSUE TITLE
gatsby-remark-prismjs: How to extend languages?

### ISSUE THREAD

**Issue by atomiks** [gatsbyjs/gatsby#10795]
## Summary

I like to extend Prism with more tokens to allow for more granular highlighting (like VS Code's TextMate grammars). Can this be done with Gatsby?

### Basic example

```js
import Prism from 'prismjs'

Prism.languages.insertBefore('javascript', 'punctuation', {
  definition: {
    pattern: /[a-z]\w*(?=:)/i,
    lookbehind: true,
    alias: 'property',
  },
  access: {
    pattern: /(\.\s*)[a-z_$][\w$]*/i,
    lookbehind: true,
    alias: 'property',
  },
  dom: {
    pattern: /\b(?:window|document|navigator|performance|localStorage)\b/,
    alias: 'variable',
  },
  console: /\bconsole\b/,
  'class-name': {
    pattern: /\b[A-Z][A-Za-z0-9_$]+\b/,
    alias: 'variable',
  },
})
```

**Comment by sidharthachatterjee** [comment]
Hey @atomiks 

If you're using `gatsby-remark-prismjs` then it looks like it doesn't expose access to the internal instance of Prism and therefore this won't be possible with it. 

You could fork from gatsby-remark-prismjs if you're interested and add the code above in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/load-prism-language.js

**Comment by jakallergis** [comment]
@sidharthachatterjee Do you know if there are any plans for exposing access to the internal Instance of Prism? Thanks.

**Comment by david-nossebro** [comment]
I am working on a pull-request.

**Comment by david-nossebro** [comment]
I have made a pull-request #11932. The approach is not to expose the Prism instance, but give the opportunity to configure 'gatsby-remark-prismjs' in the 'gatsby-config.js' file. My pull-request also only let the user add, change or extend the language definition. There is no way of defining input to the 'insertBefore' method, but that could be added if needed.

What is the exact function you try to achieve @atomiks ?

**Comment by atomiks** [comment]
@david-nossebro I want to add more tokens to add more granular syntax highlighting so it's close to my VS Code theme:

I am monkey-patching the file in node_modules for now:

- Gets run before dev: https://github.com/atomiks/tippyjs/blob/59c2cdde16275ef624cccbc4e1246d954b07f0fd/website/src/monkey-patch.js
- The code which gets appended to the end of the prism.js file in node_modules: https://github.com/atomiks/tippyjs/blob/59c2cdde16275ef624cccbc4e1246d954b07f0fd/website/src/prism-extensions.js

**Comment by david-nossebro** [comment]
@atomiks my pull request is now merged. I have included the possibility to define the insertBefore method as well, so it should solve your problem.
