### ISSUE TITLE
React-Toolbox Integration

### ISSUE THREAD

**Issue by Bartekus** [gatsbyjs/gatsby#108]
Do you think it's feasible/worthwhile? Is there anything that might be a problem with integration into gatsby as a starter that I should be aware of?

**Comment by KyleAMathews** [comment]
I can't think of any problems off-hand with integrating with react-toolbox. You will need to add the sass-loader — https://github.com/gatsbyjs/gatsby#how-to-use-your-own-webpack-loaders

Gatsby is a pretty thin wrapper around React + Webpack so if something works with React normally then it should as well with Gatsby.

**Comment by Bartekus** [comment]
Awesome, I'll give it a go. As to sass I just patched my gatsby locally for that but since it's going to be a starter I'll go the proper route and use webpack-configurator to accomplish this. Also, big thank you Kyle for making Gatsby, I really dig the whole undertaking and having found out now that ES6 conversion from coffeescript is planned, I'm even more ecstatic about this project!

**Comment by KyleAMathews** [comment]
:+1: 

And actually most files have already been converted to ES2015 :)

**Comment by KyleAMathews** [comment]
Looking forward to your starter. Feel free to make a PR to add it to the README when you feel it's ready.

**Comment by Bartekus** [comment]
Uhh oh, patching the main webpack.config.js turns out more effective solution for me at the moment as I'm unable to get the webpack-configurator working.
Currently my gatsby.config.js looks like this:

```
var Config = require("webpack-configurator");
var Webpack = require("webpack");

module.exports = function(config, env) {
	config.loader('sass', function(cfg) {
		cfg.test = /\.scss$/;
		cfg.loader = 'style!css!sass?modules';
		return cfg
	});
	return config;
};
```

I'm wondering whether it wouldn't be better to simply include sass-loader into the original webpack.config.js as both .less and .scss can be supported without interfering with one another. 
The module cost would be fairly light too only adding node-sass and sass-loader to the compilation.

Please advice!

**Comment by KyleAMathews** [comment]
I agree that sass-loader should be in core but also @ChristopherBiscardi, any idea why his webpack config override isn't working?

**Comment by ChristopherBiscardi** [comment]
@KyleAMathews @Bartekus 

The config is wrong for sass with css-modules

```javascript
        cfg.loader = 'style!css!sass?modules';
```

should be

```javascript
        cfg.loader = 'style!css?modules!sass';
```

because `modules` is an option passed to `css-loader`, not `sass-loader`

----

I just used the above and it worked for me.

**Comment by Bartekus** [comment]
Oh I get it, thank you @ChristopherBiscardi, I totally missed that one, opss :)

**Comment by KyleAMathews** [comment]
Latest Gatsby release includes out-of-the-box Sass support.

**Comment by KyleAMathews** [comment]
So react-toolbox should just be an install and go experience now.

**Comment by zweicoder** [comment]
@KyleAMathews just installed React-toolbox and it doesn't work out of the box. Not sure what I have to check - any pointers?

**Comment by KyleAMathews** [comment]
@zweicoder did you import the raw or bundled component? https://github.com/react-toolbox/react-toolbox#bundled-component

**Comment by zweicoder** [comment]
@KyleAMathews I imported the bundled one `import { Card, CardMedia, CardTitle, CardText, CardActions } from 'react-toolbox/lib/card';`

**Comment by KyleAMathews** [comment]
Is there any errors in the browser or terminal console?

**Comment by zweicoder** [comment]
@KyleAMathews no, nothing at all =/

**Comment by KyleAMathews** [comment]
What do you get from console.log(Card)?

**Comment by zweicoder** [comment]
@KyleAMathews hmm, it seems like the `theme` attribute is an empty object. From the React Devtools when inspecting `<Card>`: `$r.props
Object {children: "test", theme: Object}`

**Comment by zweicoder** [comment]
There is a `<ThemedCard>` component as well, with these props: `{children: "test", composeTheme: "deeply"}` so it seems the `react-css-themr` is not working?

**Comment by KyleAMathews** [comment]
Could you create a GitHub repo with this so I could play around with it?

**Comment by zweicoder** [comment]
@KyleAMathews [Here](https://github.com/zweicoder/git-gud-scrub) it is, thanks for helping!!!

**Comment by KyleAMathews** [comment]
@zweicoder looks like you've been struck by the dreaded `node_modules` disease. From a fresh install it just worked

<img width="728" alt="screen shot 2016-08-24 at 8 43 42 pm" src="https://cloud.githubusercontent.com/assets/71047/17956091/e670a638-6a3b-11e6-8c78-477f8529f5b2.png">

See if deleting `node_modules` and reinstalling fixes things.

**Comment by zweicoder** [comment]
@KyleAMathews uh... actually for the 'thoughts' section I manually copied the `css` styles to simulate the same styles :sweat_smile:  There's a real `<Card>` component with the words `test` inside. under the `ideas` category. I'll try a fresh install of `node_modules` though regardless

**Comment by zweicoder** [comment]
Didn't work :(

![image](https://cloud.githubusercontent.com/assets/3684550/17958720/703fe77e-6ace-11e6-976d-585cd6cecec3.png)

**Comment by KyleAMathews** [comment]
Figured it out!

Two things. React-Toolbox *does* require some sort of theme to be inserted as a prop. Each component folder has a default `theme.scss` file that you can include. Second hurdle was the module expects you to be using CSS Modules and Gatsby by default only processes files as a css module *if* it's named `*.module.(css|less|sass|scss)`. Since their scss file isn't, it was just being included normally but without the mangled class names to be inserted into the component.

So... either you copy their default theme files into your project and rename them to something.module.scss or I think react-css-thmr takes plain class names as props so you could do that too.

<img width="699" alt="screen shot 2016-08-24 at 11 25 50 pm" src="https://cloud.githubusercontent.com/assets/71047/17958995/470875f0-6a52-11e6-8a96-9225a59addbb.png">

**Comment by zweicoder** [comment]
@KyleAMathews Great job figuring it out! Since I only use CSS Modules I'm gonna try overriding the css loaders to always use `modules` and see if it works :)

**Comment by dbismut** [comment]
For what it's worth, I managed to use react-toolbox using the following config in `gatsby-node.js`. As @zweicoder mentioned, css loaders are overridden to always use modules.

```javascript
import ExtractTextPlugin from 'extract-text-webpack-plugin'

exports.modifyWebpackConfig = function (config, stage) {
  config.removeLoader('css');
  config.removeLoader('sass');
  const cssModulesConf = 'css?modules&minimize&importLoaders=1';
  const cssModulesConfDev = `${cssModulesConf}&sourceMap&localIdentName=[name]---[local]---[hash:base64:5]`;

  if (stage === 'develop') {
    config.loader('css', function (cfg) {
      cfg.test = /\.css$/;
      cfg.loaders = ['style', cssModulesConfDev, 'postcss']
      return cfg
    });

    config.loader('sass', function (cfg) {
      cfg.test = /\.(sass|scss)/;

      cfg.loaders = ['style', cssModulesConfDev, 'sass'];
      return cfg
    });
    return config;
  }
  else {
    config.loader('css', function (cfg) {
      cfg.test = /\.css$/;
      cfg.loader = ExtractTextPlugin.extract('style', [cssModulesConf, 'postcss']);
      return cfg
    });

    config.loader('sass', function (cfg) {
      cfg.test = /\.(sass|scss)/;

      cfg.loader = ExtractTextPlugin.extract('style', [cssModulesConf, 'sass']);
      return cfg
    });
    return config;
  }
};
```

**Comment by obujor** [comment]
Hi, I can't integrate React Toolbox with Gatby.

The error is 
`ERROR in ./~/css-loader!./~/postcss-loader!./~/react-toolbox/lib/button/theme.css
Module build failed: Error: composition is only allowed when selector is single :local class name not in ".raised", ".raised" is weird`

Could someone help me please?

Thanks!

**Comment by KyleAMathews** [comment]
@obujor have you tried @dbismut's solution in https://github.com/gatsbyjs/gatsby/issues/108#issuecomment-263266418?

**Comment by obujor** [comment]
@KyleAMathews yes I've tried but I'm getting another error:

> ERROR in ./\~/css-loader?modules&minimize&importLoaders=1&sourceMap&localIdentName=[name]---[local]---[hash:base64:5]!./\~/postcss-loader!./\~/style-loader!./\~/css-loader?modules&minimize&importLoaders=1&sourceMap&localIdentName=[name]---[local]---[hash:base64:5]!./\~/postcss-loader!./pages/example.module.css
> Module build failed: Unknown word (5:1)
>  3 | // load the styles
>  4 | var content = require("!!./../node_modules/css-loader/index.js?modules&minimize&importLoaders=1&sourceMap&localIdentName=[name]---[local]---[hash:base64:5]!./../node_modules/postcss-loader/index.js!./example.module.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']]; | ^
>  6 | // add the styles to the DOM
>  7 | var update = require("!./../node_modules/style-loader/addStyles.js")(content, {});
> @ ./pages/example.module.css 4:14-433 13:2-17:4 14:20-439

Any idea?

**Comment by KyleAMathews** [comment]
@obujor not sure. Perhaps suggestions in this thread could help? https://github.com/webpack-contrib/css-loader/issues/295

**Comment by obujor** [comment]
@KyleAMathews thanks but those suggestions don't work either, finally I solved by removing from pages all example pages that includes css and sass stylesheets, it's a workaround but it works.

**Comment by KyleAMathews** [comment]
Oh well yes. The change you made to the webpack config made it so that CSS
Modules is enabled for all CSS/sass styles. So the example pages won't work
anymore as they don't use CSS modules.
