### ISSUE TITLE
[Prismjs] global config showLineNumbers: true it not working

### ISSUE THREAD

**Issue by anhchungite** [gatsbyjs/gatsby#10805]
## Description

My config:
```
{
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-prismjs`,
            options: {
              aliases: {
                js: 'javascript'
              },
              showLineNumbers: true
            }
          }
        ]
      }
    }
```
And seem option `showLineNumbers: true` it not working

### Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
  Binaries:
    Yarn: 1.7.0
    npm: 5.6.0 
  npmPackages:
    gatsby: ^2.0.76 => 2.0.79
    gatsby-image: ^2.0.20 => 2.0.25
    gatsby-plugin-manifest: ^2.0.9 => 2.0.13
    gatsby-plugin-offline: ^2.0.16 => 2.0.20
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5
    gatsby-plugin-sharp: ^2.0.14 => 2.0.17
    gatsby-remark-copy-linked-files: ^2.0.8 => 2.0.8
    gatsby-remark-images: ^3.0.1 => 3.0.1
    gatsby-remark-prismjs: ^3.2.0 => 3.2.0
    gatsby-remark-responsive-iframe: ^2.0.8 => 2.0.8
    gatsby-remark-smartypants: ^2.0.7 => 2.0.7
    gatsby-source-filesystem: ^2.0.8 => 2.0.12
    gatsby-transformer-remark: ^2.1.19 => 2.1.19
    gatsby-transformer-sharp: ^2.1.8 => 2.1.10

**Comment by sidharthachatterjee** [comment]
Hey @anhchungite 

Could you please link  to a minimal reproduction repo for this?

**Comment by anhchungite** [comment]
> Hey @anhchungite
> 
> Could you please link to a minimal reproduction repo for this?

Thanks for reply.
I have resolved it. Just restart server and it work.

**Comment by soopdop** [comment]
`gatsby clean` worked for me.
