### ISSUE TITLE
Add missing publishedAt entries to blog posts

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#10800]
## Description

Some blog posts on gatsbyjs.org have a `canonicalLink`, but no `publishedAt` key in their frontmatter. This leads to the blog post header saying _(originally published at )_, instead of _(originally published at example.com)_.

A quick fix would be to update the blog posts that have a `canonicalLink` but no `publishedAt` text to also include `publishedAt`.

A better fix would be to update [`template-blog-post.js`](https://github.com/gatsbyjs/gatsby/blob/2f4ee947a9c4fcc9491819c62ce3ece1caa56c45/www/src/templates/template-blog-post.js#L210-L220) to automatically display a `publishedAt` value if one isn't supplied. As an example, a `canonicalLink` like `https://www.contentful.com/blog/2018/02/28/contentful-gatsby-video-tutorials/` should be displayed as `contentful.com`.

### Steps to reproduce

[Visit this example post](https://www.gatsbyjs.org/blog/2018-11-03-building-an-accessible-lightbox/)
Check the author credit box at the top of the post:

![screenshot 2019-01-03 at 12 56 56](https://user-images.githubusercontent.com/381801/50638861-217e2f80-0f57-11e9-8f41-6e6a31166eb2.png)

[Here's the markdown file for the above url](https://github.com/gatsbyjs/gatsby/blob/2f4ee947a9c4fcc9491819c62ce3ece1caa56c45/docs/blog/2018-11-03-building-an-accessible-lightbox/index.md). Note that there are other posts where this happens too.

### Expected result

It should say something like _(originally published at 416serg.me)_

### Actual result

It says _(originally published at )_

### Environment

gatsbyjs.org

**Comment by Nilomiranda** [comment]
Wouldn't be an easier fix if we check if `publishedAt` returns something, and if not, omit the "originally published at" ?

**Comment by ivorpad** [comment]
I can give this a try and it should be fairly easy to pull off. What about subdomains?:

```
* subdomain.domain.com
* www.domain.com
* ww2.sub.domain.com
```

Should `publishedAt` always be in the form of `example.com`?

**Comment by m-allanson** [comment]
> Wouldn't be an easier fix if we check if publishedAt returns something, and if not, omit the "originally published at" ?

This is what happens if there's no `canonicalLink`. But if there's a `canonicalLink` without a `publishedAt` we can assume that the author wanted to display a link.

> What about subdomains?

Yeah that's a good idea - the logic doesn't need to be complex though. This is just intended to be a 'good enough' fallback in case the `publishedAt` field is missing.

**Comment by ivorpad** [comment]
>Yeah that's a good idea - the logic doesn't need to be complex though.

But if the article came from `blog.example.com` or even `www.blog.example.com` we'd want to show that as `publishedAt` instead of just `example.com`. Sounds good?
