### ISSUE TITLE
opensearch support on www site

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#10812]
Brought up in #9253. This issue is intended to capture discussion around opensearch support on `www`. Would require search params on the global site search. More to understand before any work happens on this.

**Comment by LekoArts** [comment]
Anyone who wonders what OpenSearch actually does:

![19-01-03_48c1m](https://user-images.githubusercontent.com/16143594/50653579-3de78f80-0f8a-11e9-9e77-21fa4b2bba5b.gif)

Type the domain -> <kbd>TAB</kbd> -> Use the site's search
