### ISSUE TITLE
Nice to have: hot reload / restart server when gatsby-node.js updated

### ISSUE THREAD

**Issue by alexgreenland** [gatsbyjs/gatsby#10811]
## Summary

Would be a nice-to-have productivity boost with hot reloading when `gatsby-node.js` is updated.

### Motivation

Gatsby detects a lot of changes and hot reloads, so it would make sense to restart the server when doing common things like adding new node fields.

**Comment by sidharthachatterjee** [comment]
This is actually pretty tricky to do since `gatsby-node.js` does a lot more than creating pages. As a result, it's difficult to localise the hot reloading behaviour to _just_ node fields or adding pages. 

Related discussion at https://github.com/gatsbyjs/gatsby/issues/8163

**Comment by alexgreenland** [comment]
I'd be happy with a complete teardown of the server and restart if state can get corrupted.

**Comment by guilhermedecampo** [comment]
This would be pretty nice indeed. Anyone found a good setup?

**Comment by d4rekanguok** [comment]
Hey folks, I've just put together quickly a plugin to restart Gatsby's process automatically when gatsby-* file changes: https://github.com/d4rekanguok/gatsby-plugin-node-reload

It watches your gatsby-* files (chokidar), spawn a new detached child process on change, kill the previous one while using the same stdout. The caveat is that when you want to end this process you'd have to do it manually (`kill -15 {PID}` on macOS). The plugin will log out the current PID at the beginning of each process.

**Comment by dandv** [comment]
Gatsby now has a feature to [prompt the user to restart, when gatsby-node.js has changed](https://github.com/gatsbyjs/gatsby/pull/22759).
