### ISSUE TITLE
How to use resusable components for another project? 

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#10827]
Hi, 

I actually have a project named X with many components in the directory: 
`/Sites/X/src/components/... `with `/Sites/X/node_modules.`

I have to create another project named Y and I would like to use same components instead of rewriting them.

The project is at `/Sites/Y/src/` with `/Sites/node_modules.`

Is there a way to share these reusable component?

Thanks

**Comment by gurpreet-hanjra** [comment]
Hello,
How about moving those components in a library and deploy them as npm module? Then you can simply `npm install <library>` and use them in any project.

**Comment by Steffi3rd** [comment]
> Hello,
> How about moving those components in a library and deploy them as npm module? Then you can simply `npm install <library>` and use them in any project.

Sounds interesting, but what library? Can you develop please?

**Comment by sidharthachatterjee** [comment]
Hello @Steffi3rd 

Typically the way to do this is to create a new repository called, say _Steffi3rd components_ and publish this to npm. Then in projects _X_ and _Y_ axis, you can import _Steffi3rd components_ and use them as you regularly would. 

Here's a quick walk through that I found on Medium 

https://medium.com/quick-code/publish-your-own-react-component-as-npm-package-under-5-minutes-8a47f0cb92b9

**Comment by cardiv** [comment]
:+1: for Bit that @trickydisco78 mentioned. It's like Github for components with nice goodies.

**Comment by gurpreet-hanjra** [comment]
> > Hello,
> > How about moving those components in a library and deploy them as npm module? Then you can simply `npm install <library>` and use them in any project.
> 
> Sounds interesting, but what library? Can you develop please?

Couldn't described better than @sidharthachatterjee . This is what I meant.

**Comment by Steffi3rd** [comment]
Okay guys, thanks for all those answers.

If we published on npm, anyone can use them, right?

So the component must be contain any "personnal" state/data, right ?

**Comment by cardiv** [comment]
You could use private packages that start at [$7/month on npm](https://www.npmjs.com/pricing) or for free at [Bit](https://bitsrc.io/pricing).

But I think you should use environment variables and/or a headless CMS to store sensible information.

**Comment by sidharthachatterjee** [comment]
Closing this for now @Steffi3rd 

Please feel free to reopen if there is anything else we can help with!
