### ISSUE TITLE
[gatsby-source-wordpress] Missing lead images from posts

### ISSUE THREAD

**Issue by pippo111** [gatsbyjs/gatsby#10828]
## Description

When adding more than 100 media files to wordpress site hosted on wordpress.com some images are missing. Only maximum of 100 images are fetched from api. I cannot set `perPage` parameter greater than 100 because of WP API limitation.

In my opionion it is controlled by `perPage` and somehow the plugin cannot fetch other pages than the first one.

### Steps to reproduce

Add blog post with featured_image and then add another 100 random media files. The oldest images will not be fetched, only latest 100.

### Expected result

All images should be fetched from wordpress site.

### Actual result

The oldest images are not shown or existend in "featured_image" from allWordpressPost

### Environment

```
  System:
    OS: Linux 4.18 Solus 3.9999
    CPU: x64 Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz
    Shell: 2.7.1 - /usr/bin/fish
  Binaries:
    Node: 8.12.0 - /usr/bin/node
    Yarn: 1.12.1 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Firefox: 63.0.1
  npmPackages:
    gatsby: ^2.0.48 => 2.0.48 
    gatsby-cli: ^2.4.3 => 2.4.3 
    gatsby-image: ^2.0.15 => 2.0.15 
    gatsby-paginate: ^1.0.16 => 1.0.16 
    gatsby-plugin-favicon: ^3.1.4 => 3.1.4 
    gatsby-plugin-less: ^2.0.5 => 2.0.5 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.5 
    gatsby-plugin-polyfill-io: ^1.0.5 => 1.0.5 
    gatsby-plugin-purgecss: ^2.4.0 => 2.4.0 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.7 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.0.5 => 2.0.5 
    gatsby-source-firebase: ^1.0.0 => 1.0.0 
    gatsby-source-firestore: ^1.0.3 => 1.0.3 
    gatsby-source-wordpress: ^3.0.21 => 3.0.21 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

**Comment by sidharthachatterjee** [comment]
Hey @pippo111 

Can you please link to a minimal reproduction for this? From what I understand the plugin _does_ indeed get multiple pages of data.

**Comment by jonniebigodes** [comment]
@pippo111 as i said in #11175, i have got the data back correctly.
One post is pulling a gallery with 163 images and one other is pulling all 163 images individually in a post for testing purposes. I have the code in there, It's not deployed because i'm getting the `fetching the JSON data from 0 valid API Routes...` error in netlify when i build the site. Tried it with the approach in [here](https://github.com/gatsbyjs/gatsby/pull/10624#issue-240634235) to no avail. But locally that works and gets the content back
