### ISSUE TITLE
gatsby-remark-component is not wrapping the component into a div, I still have the p

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#10823]
### Environment

    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-component',
          },
          {
            resolve: `gatsby-remark-images`,
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 1200,
              linkImagesToOriginal: false,
              backgroundColor: 'transparent',
              withWebp: true,
            },
          },
        ],
      },
    },

 System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  Binaries:
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 
  npmPackages:
    gatsby: ^2.0.67 => 2.0.67
    gatsby-image: ^2.0.25 => 2.0.25
    gatsby-plugin-catch-links: ^2.0.9 => 2.0.9
    gatsby-plugin-emotion: ^3.0.1 => 3.0.1
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8
    gatsby-plugin-manifest: ^2.0.12 => 2.0.12
    gatsby-plugin-offline: ^2.0.19 => 2.0.19
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.0.15 => 2.0.15
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3
    gatsby-plugin-typescript: ^2.0.3 => 2.0.3
    gatsby-plugin-typography: ^2.2.2 => 2.2.2
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-images: ^3.0.1 => 3.0.1
    gatsby-source-filesystem: ^2.0.12 => 2.0.12
    gatsby-transformer-remark: ^2.1.15 => 2.1.15
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9

**Comment by hackhat** [comment]
If I reverse the order like this it works!

    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 1200,
              linkImagesToOriginal: false,
              backgroundColor: 'transparent',
              withWebp: true,
            },
          },
          {
            resolve: 'gatsby-remark-component',
          },
        ],
      },
    },

**Comment by LekoArts** [comment]
Sorry, I can't follow you. What works / works not? Could you please be more descriptive about the problem you're trying to solve?

The order of remark plugins matter as they change the DOM elements they touch. So if both have overlaps (in elements they should modify) it matters which plugin changes things first.

**Comment by sidharthachatterjee** [comment]
Hello @hackhat 

Like @LekoArts mentioned the order of plugins is important since they're applied serially. If I understand correctly the order in your latter comment works fine?

**Comment by hackhat** [comment]
Cool, thanks. I didn't know the order mattered before.
