### ISSUE TITLE
Arrow functions not converted to functions: gatsby-plugin-typescript

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#10825]
Im using gatsby-plugin-typescript

I just got an exception on IE when building. Not sure why I got a `()=>{}` function in my production build. Only happens in a small section of the generated js file. Like 20 lines have arrow function, while the rest 9000 lines have es5 functions.

File name is 7-f8fb7726d355e3e61d5e.js not sure if it helps.

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  Binaries:
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.67 => 2.0.67
    gatsby-image: ^2.0.25 => 2.0.25
    gatsby-plugin-catch-links: ^2.0.9 => 2.0.9
    gatsby-plugin-emotion: ^3.0.1 => 3.0.1
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8
    gatsby-plugin-manifest: ^2.0.12 => 2.0.12
    gatsby-plugin-offline: ^2.0.19 => 2.0.19
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.0.15 => 2.0.15
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3
    gatsby-plugin-typescript: ^2.0.3 => 2.0.3
    gatsby-plugin-typography: ^2.2.2 => 2.2.2
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-images: ^3.0.1 => 3.0.1
    gatsby-source-filesystem: ^2.0.12 => 2.0.12
    gatsby-transformer-remark: ^2.1.15 => 2.1.15
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9

**Comment by hackhat** [comment]
It's this annoying query-string issue https://github.com/sindresorhus/query-string/pull/148 . Fixed this one but looks like there is another node_module that is not converted properly.

**Comment by DSchau** [comment]
@hackhat thanks for solving your own issues and documenting the fixes!

Re: non-transpiled ES5 making its way into the browser... we've seen it before! We don't transpile node_modules (currently) but it's definitely something we should look into soon.

Thanks for using Gatsby!

**Comment by hackhat** [comment]
@DSchau "non-transpiled ES2015+ making its way into the browser... " That's the worst thing that can happen. How I will ever be able to support other browsers?

I have another module that has arrow functions, but I didn't had the time to find out which one was it.

**Comment by DSchau** [comment]
@hackhat transpile them, e.g.

```js
exports.onCreateWebpackConfig = function onCreateWebpackConfig({ actions, loaders }) {
  actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /\.js$/,
            include: `your-non-transpiled-module`,
            use: [loaders.js()],
          },
        ],
      },
    });
}
```

**Comment by hackhat** [comment]
Thanks I will try it out. I need to find which library is it, do you know how can I find out? I just have the source code minified.
