### ISSUE TITLE
[gatsby-source-medium] How to get post URL? 

### ISSUE THREAD

**Issue by bhavaniravi** [gatsbyjs/gatsby#10826]
## Summary

I am trying to display a preview of my medium blogs as a part of my Gatsby site. I am getting all the information like title, subtitle, image etc., except for the post URL. Is there a key with post URL. None of the following keys seem to have a link and no documentation mentions about getting a link. Is this feature available in `gatsby-source-medium`.

![image](https://user-images.githubusercontent.com/10116000/50679170-5312fb80-1028-11e9-9b16-e7566f02ac92.png)

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`Gatsby-browser.js`: N/A 
`Gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
You looked for the wrong word 😉  With [`uniqueSlug`](https://yq86qyl08z.sse.codesandbox.io/___graphql?query=%7B%0A%20%20allMediumPost%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20uniqueSlug%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) you get your URL. It gets served by [Medium](https://medium.com/kentcdodds/latest?format=json) like that.

**Comment by bhavaniravi** [comment]
Thank you so much.
