### ISSUE TITLE
[gatsby-source-filesystem] Allow publicURL to receive relative directory

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#10832]
## Summary

Currently, `gatsby-source-filesystem` exposes a `publicURL` field on `File`. Querying this field causes the file to be copied to `/static` and the new path to be returned. It would be great if this field accepted an argument to supply a path relative to the site root.

### Basic example

```graphql
{
   example {
      publicURL(path: "./downloads")
   }
}
```

This would copy the file to `/downloads` and return `/downloads/example.pdf`.

### Motivation

This allows a user more control over where files are served from, allowing for cleaner urls.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @Undistraction 

This is pretty simple to do and the code is at https://github.com/gatsbyjs/gatsby/blob/56acfe1674b02740d2c05979be39b1144eacc42f/packages/gatsby-source-filesystem/src/extend-file-node.js#L41

Are there any use cases that you'd like this for besides being able to control directory structure?
