### ISSUE TITLE
[gatsby-transformer-remark] Nested lists inserting rogue paragraphs

### ISSUE THREAD

**Issue by martynhoyer** [gatsbyjs/gatsby#10870]
Seems similar to https://github.com/gatsbyjs/gatsby/issues/4096 which got closed

## Description

Using a markdown nested list seems to produce some slightly awkward/inconsistent markup which is a bit challenging to style. If an `<li>` has a child `<ul>`, that list item's content will be wrapped in a paragraph.

### Steps to reproduce

Project is private on GitLab I'm afraid, but using a markdown page, add the following markdown content: 

```
- List item one
- List item two
- List item three
- List item four
  - Nested list item four point one
  - Nested list item four point two
- List item five
  - Nested list item five point one
- List item six
```

### Expected result

Rendered HTML should be: 

```
<ul>
  <li>List item one</li>
  <li>List item two</li>
  <li>List item three</li>
  <li>
    List item four
    <ul>
      <li>Nested list item four point one</li>
      <li>Nested list item four point two</li>
    </ul>
  </li>
  <li>
    List item five
    <ul>
      <li>Nested list item five point one</li>
    </ul>
  </li>
  <li>List item six</li>
</ul>
```

### Actual result

Rendered HTML is (note the two parent `<li>`s with `<p>`s around their content): 

```
<ul>
  <li>List item one</li>
  <li>List item two</li>
  <li>List item three</li>
  <li>
    <p>List item four</p>
    <ul>
      <li>Nested list item four point one</li>
      <li>Nested list item four point two</li>
    </ul>
  </li>
  <li>
    <p>List item five</p>
    <ul>
      <li>Nested list item five point one</li>
    </ul>
  </li>
  <li>List item six</li>
</ul>
```

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.83 => 2.0.83 
    gatsby-image: ^2.0.25 => 2.0.25 
    gatsby-plugin-catch-links: ^2.0.9 => 2.0.9 
    gatsby-plugin-manifest: ^2.0.13 => 2.0.13 
    gatsby-plugin-netlify: ^2.0.6 => 2.0.6 
    gatsby-plugin-netlify-cms: ^3.0.9 => 3.0.9 
    gatsby-plugin-netlify-cms-paths: ^1.1.0 => 1.1.0 
    gatsby-plugin-offline: ^2.0.20 => 2.0.20 
    gatsby-plugin-react-helmet: ^3.0.5 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.17 
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4 
    gatsby-plugin-svgr: ^2.0.1 => 2.0.1 
    gatsby-remark-images: ^3.0.1 => 3.0.1 
    gatsby-remark-relative-images: ^0.2.1 => 0.2.1 
    gatsby-source-filesystem: ^2.0.12 => 2.0.12 
    gatsby-transformer-remark: ^2.1.19 => 2.1.19 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.10 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @martynhoyer 

I added a resolver for the `markdownAst` to `gatsby-transformer-remark` so inspect what remark returns for the markdown you posted above

Calling `remark.parse(markdownNode.internal.content)` on it returns 
```
              {
                "type": "listItem",
                "loose": false,
                "checked": null,
                "children": [
                  {
                    "type": "paragraph",
                    "children": [
                      {
                        "type": "text",
                        "value": "List item six",
                        "position": {
                          "start": {
                            "line": 27,
                            "column": 3,
                            "offset": 992
                          },
                          "end": {
                            "line": 27,
                            "column": 16,
                            "offset": 1005
                          },
                          "indent": []
                        }
                      }
                    ],
```

Looks like it is an upstream issue with remark 
![screenshot 2019-01-08 21 01 29](https://user-images.githubusercontent.com/7701981/50840448-95ba3800-1388-11e9-8306-4e8b8cc0783b.png)

**Comment by martynhoyer** [comment]
Thanks for looking! I did a bit more research myself and ended up at the remark route too. It's a bit odd though - using this preview tool it seems to work as expected and that uses remark/unified under the hood: 
https://rexxars.github.io/react-markdown/

This one, however has the same issue, but _doesn't_ appear to be using Remark at all...! 🤷‍♂️ 
https://markdownlivepreview.com/
https://github.com/tanabe/markdown-live-preview

**Comment by sidharthachatterjee** [comment]
https://rexxars.github.io/react-markdown doesn't use `mdast-util-to-hast`

It has its own renderers for elements. They do seem to include paragraphs in non tight lists in the last element at https://github.com/rexxars/react-markdown/commit/3bee068ea60069a5ce8a6b964e66ed35f0e4992f

**Comment by martynhoyer** [comment]
I see! In that case, apologies for the noise!

**Comment by sidharthachatterjee** [comment]
No problem at all, @martynhoyer 🙂 

Let's keep this open for now and see what everyone else thinks

**Comment by AryanJ-NYC** [comment]
I have a similar problem to this. How is/was this solved?

**Comment by martynhoyer** [comment]
@AryanJ-NYC It wasn't really... I ended up just hacking around with the CSS to remove the inappropriate margins from the paragraphs inside the list items.

**Comment by slice** [comment]
Just popping in to say that I've been experiencing this issue. Unfortunately I don't have the time on my hands to attempt to PR a fix for this, but I'd just thought I'd let the maintainers know that this is still around.

**Comment by ishan0445** [comment]
> I have a similar problem to this. How is/was this solved?

Just like @martynhoyer suggested, I have removed the extra space from the <p> tag inside <li>.
```css
li > p {
    margin-top: -24px;
}
```

**Comment by max-elia** [comment]
FYI, I also run into this problem and fixed it with the following CSS-rule:
```css
li > p {
    display: inline;
}
```
