### ISSUE TITLE
Sometimes I add a new image and it doesn't appear. I need to delete cache folder and restart.

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#10881]
Sometimes I add a new image to the folder and then reference from my MD.

Interestingly the output of the html is:

![image](https://user-images.githubusercontent.com/11173732/50760869-ed32a800-12a3-11e9-897b-0f592fb27976.png)

Instead of span, picture, source, image tags that normally the image-remark will add.

### Environment

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  Binaries:
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.67 => 2.0.67
    gatsby-image: ^2.0.25 => 2.0.25
    gatsby-plugin-catch-links: ^2.0.9 => 2.0.9
    gatsby-plugin-emotion: ^3.0.1 => 3.0.1
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8
    gatsby-plugin-manifest: ^2.0.12 => 2.0.12
    gatsby-plugin-offline: ^2.0.19 => 2.0.19
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.0.15 => 2.0.15
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3
    gatsby-plugin-typescript: ^2.0.3 => 2.0.3
    gatsby-plugin-typography: ^2.2.2 => 2.2.2
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-images: ^3.0.1 => 3.0.1
    gatsby-source-filesystem: ^2.0.12 => 2.0.12
    gatsby-transformer-remark: ^2.1.15 => 2.1.15
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9

**Comment by sidharthachatterjee** [comment]
Hey @hackhat 

Can you please link to a minimal reproduction for this? Have you seen in occur in some specific instances?

**Comment by hackhat** [comment]
I can't reproduce it all the time but it happens on all projects. I'm quite sure it is not just because of my setup because I'm not doing anything special, just using some plugins and config:

[
      {
        resolve: `@wapps/gatsby-plugin-material-ui`,
        options: {},
      },
      `gatsby-transformer-sharp`,
      `gatsby-plugin-sharp`,
      {
        resolve: `gatsby-plugin-sitemap`,
        options: {
          exclude: [
            '/internal/**',
          ],
        },
      },
      `gatsby-plugin-catch-links`,
      `gatsby-plugin-emotion`,
      `gatsby-plugin-typescript`,
      'gatsby-plugin-react-helmet',
      'gatsby-plugin-offline',
      {
        resolve: `gatsby-source-filesystem`,
        options: {
          path: `${config.rootDir}/src/content/pages`,
          name: 'markdown-pages',
        },
      },
      {
        resolve: `gatsby-source-filesystem`,
        options: {
          path: `${config.rootDir}/src/content/images`,
          name: 'images',
        },
      },
      {
        resolve: `gatsby-transformer-remark`,
        options: {
          plugins: [
            {
              resolve: `gatsby-remark-images`,
              options: {
                // It's important to specify the maxWidth (in pixels) of
                // the content container as this plugin uses this as the
                // base for generating different widths of each image.
                maxWidth: 1200,
                linkImagesToOriginal: false,
                backgroundColor: 'transparent',
                withWebp: true,
              },
            },
            {
              resolve: 'gatsby-remark-component',
            },
          ],
        },
      },
    ]
