### ISSUE TITLE
Why is "../../../static" added to my image paths?

### ISSUE THREAD

**Issue by SachaG** [gatsbyjs/gatsby#10880]
I have the following markdown content:

```
---
templateKey: blog-post
title: 'test post #2'
date: 2018-12-17T00:27:36.051Z
description: Another test post
tags:
  - travel
  - test
thumbnail: /img/masaaki-komori-614762-unsplash.jpg
---
```

Yet when I query for that post, the `thumbnail` field becomes:

``` 
../../../static/img/masaaki-komori-614762-unsplash.jpg
```

Which doesn't work since that path only works in the local file system, not when serving your content. 

Here's my [gatsby-config](https://github.com/zenstokyo/ZensHomeBlog/blob/master/gatsby-config.js) file. I commented out a lot of the plugins bundled by the [NetlifyCMS starter](https://github.com/netlify-templates/gatsby-starter-netlify-cms) to try and debug #10603. 

I would like to get to a point where whatever value I put in that `thumbnail` field just appears as-is when accessed through the GraphQL endpoint, but getting there is proving a lot trickier than I thought…

**Comment by pieh** [comment]
It's this function (imported from 3rd party plugin) in https://github.com/zenstokyo/ZensHomeBlog/blob/master/gatsby-node.mjs#L80 that does this conversion
