### ISSUE TITLE
Postprocess data from graphql response

### ISSUE THREAD

**Issue by schorfES** [gatsbyjs/gatsby#10885]
## Summary

Is there a way to post process the returned data from a graphql query?

## Relevant information

I am searching for a way to post process the data of a qraphql query before it will be used inside a page. In my case the fetched data contains a url. I would like to download the resource from that url into the `public/` folder and update the url value to match the "local" path. Is there any way to achieve this currently? I think the `gatsby-node.js` API should be a place for that functionality but I didn't found any matching behaviour.

Thanks in advance!

**Comment by sidharthachatterjee** [comment]
Thank you for the question @schorfES 

What you describe sounds like a transformer plugin to me. 

Here are the docs for building one! 
https://www.gatsbyjs.org/docs/create-transformer-plugin/

If you don't want to build a plugin for it you can use https://www.gatsbyjs.org/docs/node-apis/#setFieldsOnGraphQLNodeType to add a field

**Comment by schorfES** [comment]
Hi @sidharthachatterjee and thanks a lot for your answer. I will take a look at it!
