### ISSUE TITLE
PDF doesn't show up on google chrome with service worker

### ISSUE THREAD

**Issue by Wolfy64** [gatsbyjs/gatsby#10899]
## Description

The PDF doesn't show up on google chrome (only on build status) using my link.

### Steps to reproduce

```
<a href="../images/file.pdf" target="_blank" rel="noopener noreferrer" >My PDF file</a>
```

The PDF file works fine on localhost with `gatsby develop`. After `gatsby build` I get an empty grey webpage without any error.

If I manually unregister the service worker it works.
Tested on Safari and Firefox: everything is OK.

### Expected result

Show the PDF file.

### Actual result

<a href="https://ibb.co/JkzzZJX"><img src="https://i.ibb.co/JkzzZJX/Screen-Shot.png" alt="Screen-Shot" border="0"></a>

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.85 => 2.0.85 
    gatsby-image: ^2.0.25 => 2.0.25 
    gatsby-plugin-gtag: ^1.0.4 => 1.0.4 
    gatsby-plugin-manifest: ^2.0.13 => 2.0.13 
    gatsby-plugin-netlify-cms: ^3.0.9 => 3.0.9 
    gatsby-plugin-offline: ^2.0.21 => 2.0.21 
    gatsby-plugin-react-helmet: ^3.0.5 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.17 
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4 
    gatsby-plugin-typography: ^2.2.5 => 2.2.5 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-source-filesystem: ^2.0.12 => 2.0.12 
    gatsby-transformer-remark: ^2.1.19 => 2.1.19 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.10 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by sidharthachatterjee** [comment]
Apologies you're seeing this @Wolfy64 
This appears to be a Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=918944

Related workbox issue at https://github.com/GoogleChrome/workbox/issues/1811

Can you try disabling `chrome://flags/#enable-service-worker-servicification` and see if you can still reproduce it?

**Comment by Wolfy64** [comment]
Thanks @sidharthachatterjee you right it's Chrome bug!

If I disabling the service worker it works.
So I close this issue.
