### ISSUE TITLE
gatsby-image: some pngs don't clear blur when in viewport

### ISSUE THREAD

**Issue by rotexhawk** [gatsbyjs/gatsby#10895]
## Description

I am using multiple png (lawyer badges) in the carousel and in the second section lower down the page. As you can see some of the images don't clear the blur effect. The behavior is pretty consistent. It happens with the same images. Particularly the red AV badge. Sometimes the other ones clear but that specific one is always blury. 

https://5c30099e0114ef0007420948--michaelharwin.netlify.com/

### Environment
System:
    OS: OS X El Capitan 10.11.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.0.8 - /bin/zsh
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 62.0
    Safari: 10.0
  npmPackages:
    gatsby: ^2.0.61 => 2.0.61
    gatsby-cli: ^2.4.6 => 2.4.3
    gatsby-image: ^2.0.22 => 2.0.13
    gatsby-paginate: ^1.0.16 => 1.0.16
    gatsby-plugin-glamor: ^2.0.7 => 2.0.5
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4
    gatsby-plugin-guess-js: ^1.0.3 => 1.0.2
    gatsby-plugin-manifest: ^2.0.11 => 2.0.2
    gatsby-plugin-offline: ^2.0.18 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.0
    gatsby-plugin-root-import: ^2.0.4 => 2.0.4
    gatsby-plugin-sass: ^2.0.5 => 2.0.1
    gatsby-plugin-sharp: ^2.0.14 => 2.0.6
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.0
    gatsby-source-filesystem: ^2.0.10 => 2.0.5
    gatsby-source-wordpress: ^3.0.17 => 3.0.1
    gatsby-transformer-sharp: ^2.1.9 => 2.1.3

**Comment by polarathene** [comment]
Is the issue local testing? Try disable the cache in your browser dev tools, if that doesn't help, try remove .cache and public folders in your project and rebuild. 

Still getting a problem? Inspect the problem image in the browser, There should be a <picture> element and above that your blurred image, is it base64(inlined/embedded) or a link to a file? Check the styles of the two image types, setting the picture one to opacity of 1 should reveal the real image if it loaded correctly.

Looks fine on my end via the netlify link(though I have cache disabled in devtools), reloaded it and everything went from blur up to proper image fine. Nice job on the site btw :)

**Comment by sidharthachatterjee** [comment]
Hey @rotexhawk 

I can reproduce this on the url you posted and a few images do appear blurry. It seems that the `opacity` of the base64 encoded image is still `1` even after the full sized image is downloaded. (it should get reset to 0)

Can you please link to a minimal reproduction of this so that we can figure out what's going on?

**Comment by rotexhawk** [comment]
This happens both in prod and locally, even with the cache disabled and in incognito. I will create a minimal repo and post it here.

**Comment by rotexhawk** [comment]
The issue was resolved with the latest updated.
