### ISSUE TITLE
☂️ Umbrella issue for Gatsby CSP

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#10890]
## Summary

By default Gatsby generates a couple of inline `<script>` tags and one (or more?) inline `<style>` tags for each page. 

This is problematic when creating a Content Security Policy (CSP) for your site, as the inline scripts mean `script-src 'unsafe-inline'` needs to be configured for your CSP. This in turn undoes some of the benefits of a CSP.

This issue is tracking improvements to using Gatsby with a CSP.

Useful links:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
- https://bitbucket.org/atlassianlabs/csp-webpack-plugin (possibly useful for reference)

Related issues:

- https://github.com/gatsbyjs/gatsby/issues/3427
- https://github.com/gatsbyjs/gatsby/issues/8025
- https://github.com/gatsbyjs/gatsby/issues/3746
- https://github.com/gatsbyjs/gatsby/issues/3758

### Basic example

Quoting @chuckharmston from issue #3758:

>There are two ways to permit this:
>
>1. By allowing generated assets to be loaded as external assets, so origins can be used to control this.
>2. By using `strict-dynamic` and hashes of the content of each generated file or inline resource. This provides slightly better security, but is also more complex and rigid. Ideally in this case, the generated CSP is inserted as a `<meta>` tag and the same CSP is inserted into `gatsby-plugin-netlify`'s generated `_headers` file.

### Motivation

Adding a Content Security Policy can be a useful safeguard for your site, Gatsby should provide options for people using CSPs.

**Comment by eduards** [comment]
I just started to look into this issue, too. I'd like to use Gatsby for our public web projects but the missing CSP support is a blocker for us. I'm happy to invest some time to look into this but would appreciate if someone could point me into the right direction as I'm new to the codebase 🙈

**Comment by DSchau** [comment]
cc @xjamundx, you'd be interested in this too, correct? With the additional consideration of `nonce` if I recall, correctly?

**Comment by thomkrupa** [comment]
Hey, internally we've been using a custom plugin for this. I decided to open source it, maybe it will help some of you.

https://github.com/bejamas/gatsby-plugin-csp

**Comment by mattburrowsmonzo** [comment]
@thomkrupa looks like we both had the same idea! 😂

I created a repo last night with the same name to do pretty much the same thing -> https://github.com/mattjburrows/gatsby-plugin-csp

**Comment by dsebastien** [comment]
@thomkrupa @mattburrowsmonzo, thanks for sharing!
Your solution does help, but I'm still having issues with gatsby-image that generates inline styles.

When I use `gatsby develop` it works fine (with CSP enabled), but it fails with `gatsby build`

For now I'll have to keep unsafe-inline there :(

**Comment by dsebastien** [comment]
By the way, at the moment I'm using gatsby-plugin-netlify (https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/) to add security-related headers and it would be great to be able copy the CSP generated by your plugin to the "_headers" file generated by gatsby-plugin-netlify.

I'm trying to do it now by parsing the generated "public/index.html", but I'm guessing that there could be an easier solution (e.g., if you plugin wrote the raw CSP content somewhere or made it available somehow for other Gatsby plugins to use :)

**Comment by thomkrupa** [comment]
hey @dsebastien, thanks for your feedback! Feel free to create an issue(s) -> https://github.com/bejamas/gatsby-plugin-csp/issues so we can track the progress on them. 
Gatsby-image issue is something I will definitely look into.

**Comment by dsebastien** [comment]
ping. Don't let this one get forgotten please :)

**Comment by dsebastien** [comment]
Hey everyone.

I'm also facing this issue with the google analytics plugin. Initially, I thought that I could simply add a 'sha256-...' entry to my script-src, but the value changes from page to page. That plugin should allow to pass a nonce so that we can whitelist it through the CSP.

**Comment by m-allanson** [comment]
Question for folks - is this something that should be moved in to core? What should be optional, what should be enabled for everyone? Is this something that always needs to be configured, so people would be better served by using the https://github.com/bejamas/gatsby-plugin-csp plugin?

**Comment by travi** [comment]
i think the community would benefit greatly from some good defaults in this area. gatsby does a great job in other areas of making it easier to do the right thing than the wrong thing, but this is an area that is currently quite difficult to do the right thing.

that said, it may be quite difficult to get to that point that would work out of the box for all configurations, but even warnings to help track conflicts and some guidance to get past issues could go a long way.

**Comment by Addile** [comment]
Was looking to make this work with `gatsby-plugin-netlify` to have proper CSP headers, but that seems hard to do at the moment. `gatsby-plugin-csp` seems like a good start with meta tags, not my preferred choice but it works, but there are still problems and things that could be improved.

**Comment by vcarl** [comment]
Adding another note with an issue I ran into, `gatsby-plugin-mdx` [uses `new Function`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/mdx-renderer.js#L30), which necessitates `'unsafe-eval'` in a CSP. Would be great to be able to remove that, that punches a huge hole in the policy.

**Comment by kaushalyap** [comment]
This an important issue that should be fixed!. Its been a year. Otherwise people will omit gatsby for serious work.

@m-allanson any progress on this?

**Comment by TruthReveller** [comment]
Tried gatsby-plugin-csp but still getting **inline** script and style errors.  Example script tag with  gatsby-chunk-mapping still not covered.

**Comment by hades200082** [comment]
Any solution to this must include nonce or Google Tag Manager will require unsafe-inline :(

https://developers.google.com/tag-manager/web/csp

**Comment by kripod** [comment]
Is it possible to support the [webpack-recommended way](https://webpack.js.org/guides/csp/) of handling nonces out of the box? Each page should have a `__webpack_nonce__ ` defined, which would be great for e.g. CSS-in-JS libraries offering dynamic style injection.

**Comment by hades200082** [comment]
Unfortunately that doesn't solve the issue of the nonce needing to be dynamically generated for each page request... without dynamic generation the nonce becomes meaningless and useless as a security measure.

**Comment by hades200082** [comment]
Ideally these are the criteria that should be met for this...

1. All Gatsby generated inline styles and inline scripts (including those from custom components) should be detected and their hashes added to the relevant CSP section automatically
2. The option in plugin options to configure any/all CSP options for allowed hosts, additional hashes, etc.
3. CSP served as HTTP headers (not meta tag)

https://github.com/bejamas/gatsby-plugin-csp seems to cover #1 and #2 but cannot do #3.

**Comment by JustFly1984** [comment]
@wardpeet please pay attention to this issue.
In our case we have our gatsby.js projects built with github actions and deployed to AWS S3 bucket, and invalidating CloudFront distribution. We have AWS edge lambda attached to each response, generating headers, including CSP header.
We had a plan to generate unique nonce on each response, cos we are setting up analytics and other 3rd party apis, and this is a real bummer to read this issue.

We need to handle private user data on our websites, and A+ security is our goal to bring clients onboard.

Currently I'm following https://eqxtech.com/engineering/our-lambda-dance-gets-more-serious/ idea, and had another idea about substituting some constant nonce in response html with regexp. 

Is it possible to setup dummy CSP nonce to the scripts and styles at build time?

**Comment by viniciuspardini** [comment]
> Ideally these are the criteria that should be met for this...
> 
> 1. All Gatsby generated inline styles and inline scripts (including those from custom components) should be detected and their hashes added to the relevant CSP section automatically
> 2. The option in plugin options to configure any/all CSP options for allowed hosts, additional hashes, etc.
> 3. CSP served as HTTP headers (not meta tag)
> 
> https://github.com/bejamas/gatsby-plugin-csp seems to cover #1 and #2 but cannot do #3.

Maybe for #3 the workaround is to make something similar to what they are doing here: [https://github.com/DeveloPassion/website/commit/c31120ccccefed43c266c8ef862ec696bd36c7a8](url). A process that at build time, get the meta tag from the index.html file, but instead of adding it to a configuration file, add the directive to the web server, or in my case, to the Lambda@Edge function. I didn't test it yet, but I'll work on that.

**Comment by larowlan** [comment]
FYI, for those proposing using a meta element for CSP, it is not supported by Chrome, so if you're using the CSP plugin only, without setting the header - it is likely your CSP rules aren't working in Chrome

https://caniuse.com/mdn-http_headers_csp_content-security-policy_meta-element-support

**Comment by larowlan** [comment]
Actually, I think that Can I use may be incorrect for that, because testing in Chrome is indicating that it works

**Comment by larowlan** [comment]
I opened https://github.com/mdn/browser-compat-data/issues/6998 to discuss updating ^
