### ISSUE TITLE
[tutorial] Rewrite the styles section of the tutorial for clarity, focus on Gatsby functionality

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#10901]
Currently, part 2 of the tutorial focuses on installing and configuring Typography.js more than showing people how to add global and component styles in Gatsby.

To improve this, let's rewrite this section of the tutorial to focus on Gatsby exclusively, and move third-party scripts and plugins to a "further reading" section.

## Proposed Outline

- [x] Introduction
- [ ] Global Styles using a standard `*.css` stylesheet imported into `gatsby-browser.js`
- [ ] Component CSS using CSS Modules
- [ ] A brief intro to CSS-in-JS with links to additional docs/plugins
- [ ] Gatsby style plugins and additional resources (e.g. Typography.js, Sass, Bootstrap)

My thinking is that this follows a "least complex first" approach:

1. If I’m a developer coming across from plain HTML, CSS, and JavaScript dev, I’m used to dropping a `<link rel="stylesheet" href="main.css" />` into the head of my document and adding styles to `main.css` as plain ol' CSS.

    By focusing on Gatsby’s equivalent of a global stylesheet, we don’t introduce too much magic here: we need to explain why we can't just drop a `link` into `Helmet`, but otherwise it's a global stylesheet like any other.

2. If I'm interested in component styling, but not familiar with CSS-in-JS, CSS Modules are a really accessible way to write plain CSS while getting extra benefits.

3. If I read on, I can learn more about taking CSS Modules to the next level with CSS-in-JS.

4. Going further, I can learn about Gatsby plugins for various third-party styling options with links to their docs.

Based on feedback we’ve seen, I think this will help smooth the process of learning how CSS works in Gatsby.

cc: @amberleyromo @shannonbux

**Comment by amberleyromo** [comment]
@jlengstorf Going through old issues -- I think I closed this out with https://github.com/gatsbyjs/gatsby/pull/10929

**Comment by jlengstorf** [comment]
You sure did!
