### ISSUE TITLE
[gatsby-plugin-sharp] Duplicate versions of the same image and size

### ISSUE THREAD

**Issue by wezzle** [gatsbyjs/gatsby#10909]
## Description

When using Gatsby sharp's fluid image the plugin generates multiple versions (depending on variations of max-width/max-height) of the same image with the same size but a different hash. This is because when hashing the arguments ([here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js#L390)), the arguments contain the `maxWidth`, `maxHeight` and/or `sizes` property. These properties are not sent to sharp when running the job and can therefor be left out of the hashed [filteredArguments](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js#L378).

### Steps to reproduce

Use at least two `GatsbyImageSharpFluid` with different arguments. For example:
```
{
  imageSharp {
    fluid(maxWidth: 700) {
      ...GatsbyImageSharpFluid
    }
  }
}
```  
and
```
{
  imageSharp {
    fluid(maxWidth: 600) {
      ...GatsbyImageSharpFluid
    }
  }
}
```  

### Expected result

After the build there should only be 1 version of the image's original resolution present in the static path

### Actual result

There will be two versions (or more, depending on params) of the image's original resolution in separate paths in the static folder.

### Environment

```
System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Shell: 3.0.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.12.0 - ~/.nvm/versions/versions/node/v10.12.0/bin/node
    Yarn: 1.10.1 - ~/.nvm/versions/versions/node/v10.12.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/versions/node/v10.12.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.47 => 2.0.55
    gatsby-image: ^2.0.20 => 2.0.20
    gatsby-paginate: ^1.0.16 => 1.0.16
    gatsby-plugin-catch-links: ^2.0.9 => 2.0.9
    gatsby-plugin-core-js: ^1.0.2 => 1.0.2
    gatsby-plugin-extract-schema: ^0.0.4 => 0.0.4
    gatsby-plugin-google-fonts: ^0.0.4 => 0.0.4
    gatsby-plugin-gtag: ^1.0.4 => 1.0.4
    gatsby-plugin-layout: ^1.0.3 => 1.0.9
    gatsby-plugin-lodash: ^3.0.2 => 3.0.2
    gatsby-plugin-manifest: ^2.0.4 => 2.0.10
    gatsby-plugin-netlify-cache: ^1.0.0 => 1.0.0
    gatsby-plugin-offline: ^2.0.19 => 2.0.20
    gatsby-plugin-page-transitions: ^1.0.7 => 1.0.7
    gatsby-plugin-preact: ^2.0.5 => 2.0.7
    gatsby-plugin-prefetch-google-fonts: ^1.0.11 => 1.0.11
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.2
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.0.6 => 2.0.6
    gatsby-plugin-resolve-src: ^1.1.4 => 1.1.4
    gatsby-plugin-sharp: ^2.0.5 => 2.0.13
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.3
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.3 => 1.0.3
    gatsby-source-filesystem: ^2.0.8 => 2.0.9
    gatsby-source-trustpilot: ^0.0.46 => 0.0.46
    gatsby-source-wordpress: ^3.0.1 => 3.0.15
    gatsby-transformer-sharp: ^2.1.1 => 2.1.8
```

### Suggested fix

Change line [378](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js#L378) into:
```
filteredArgs = _.filter(filteredArgs, arg => ['pathPrefix', 'sizes', 'maxWidth', 'maxHeight'].indexOf(arg[0]) === -1);
```

I'm happy to provide a pull request.

### Extra discussion

Another thing I encountered in the code was this [line](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js#L645):
```
// Add the original image to ensure the largest image possible
// is available for small images. Also so we can link to
// the original image.
filteredSizes.push(fixedDimension === `maxWidth` ? width : height)
```
Is there a reason this is always done? We use really large images because we transform them using this plugin to smaller versions but this causes the original to always be generated by sharp. This sounds like something that could be done with an argument because it might only be needed for smaller images, if at all, and does impact performance quite a bit.

**Comment by ezekielaquino** [comment]
I'm having the same issue. i have page-1/page-2 with identical set of images and an identical graphql queries-- however, the same images with exactly the same params are outputted to two different directories == no cache. Any fix for this yet?

**Comment by wezzle** [comment]
Does the Gatsby inkteam have an update on this? The fix is really simple.

**Comment by Ontopic** [comment]
What's the status on this? We're experiencing the same issue.

**Comment by mdornseif** [comment]
Shouldn't the fix work with a whitelist instead of a blacklist? Currently `['pathPrefix', 'sizes', 'maxWidth', 'maxHeight']` is filtered. In addition I see

* `plugins`
* `showCaptions`
* `linkImagesToOriginal`

which also should not influence the output. Relevant seem to be:

* `backgroundColor`
*  `quality`
* `pngCompressionLevel`
* `pngCompressionSpeed`
* `width`
* `height`?

**Comment by KyleAMathews** [comment]
@wezzle yikes! Sorry for missing this. Looks like no body picked it up. We'd really love a fix for this! Definitely shouldn't be happening.

Also just a general note on how we operate. As long as the fix is simple, feel free to just put up a PR. For more complex PRs, discussing possible fixes first in an issue is definitely helpful.

Sorry again for not responding!
