### ISSUE TITLE
Docs: Explain all operators that can be used in a GraphQL filter, including "glob"

### ISSUE THREAD

**Issue by holyjak** [gatsbyjs/gatsby#10908]
I failed to find anywhere what "glob" in a GraphQL query filter does, could somebody please update the docs? I guess https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/graphql-reference.md should be updated to describe all the operators that are supported in a filter, preferably with examles. Linking to sift is not enough as it doesn't support `glob` but supports many Gatsby doesn't and also its syntax is different (`$in` etc).

Thank you!!!

PS: I am willing to help as much as I can.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @holyjak 

We would love to accept a PR with more examples 🙂

**Comment by RobinCsl** [comment]
I will try and give it a go!

**Comment by holyjak** [comment]
❤️
