### ISSUE TITLE
Extend the gastby-transformer-asciidoc plugin

### ISSUE THREAD

**Issue by jtanguy** [gatsbyjs/gatsby#10914]
## Summary

I would like to enhance the `gastby-transformer-asciidoc` plugin, making it extensible like `gatsby-transformer-remark`.

I would like to add the a `gastby-asciidoc-images` plugin to the asciidoc  transformer, to process images like the remark plugin.

### Basic example

I understand that the basic plugin structure would be the following: 

```js
// In gatsby-config.js
plugins: [
  `gatsby-plugin-sharp`,
  {
    resolve: `gatsby-transformer-asciidoc`,
    options: {
      // asciidoctor.js convert options
      plugins: [
        {
          resolve: `gatsby-asciidoc-images`,
          options: {
             // images options
          },
        },
      ],
    },
  },
]
```

However the `gatsby-remark-images` plugin seems to not work if the image is not hosted locally, so I would like to know if there is any way to search for images relative to the asciidoc parent independently from the source plugin used ?
I would like to add extensions points to allow asciidoctor.js extensions https://asciidoctor-docs.netlify.com/asciidoctor.js/extend/
Are there current best practices for this kind of plugin design ?

### Motivation

I would like to expand the plugin ecosystem around asciidoctor.

**Comment by sidharthachatterjee** [comment]
Hey @jtanguy 

> However the gatsby-remark-images plugin seems to not work if the image is not hosted locally, so I would like to know if there is any way to search for images relative to the asciidoc parent independently from the source plugin used ?

If I understand your question correctly, you want to be able to transform images that are referenced in asciidoc?

Can you elaborate a little more on what issue you're facing?

**Comment by jtanguy** [comment]
I would like to have the images referenced in the asciidoc document known by gatsby and bundled in the output along with the document.

In the spirit of transformer plugins, I would like to not fetch them from the filesystem implicitly

**Comment by sidharthachatterjee** [comment]
@jtanguy Okay, similar to how `gatsby-remark-images` works

> However the gatsby-remark-images plugin seems to not work if the image is not hosted locally, so I would like to know if there is any way to search for images relative to the asciidoc parent independently from the source plugin used ?

So I suppose you would want to download any references images and bundle them?

Take a look at https://github.com/mikegajda/gatsby-transformer-remote-image

It does something similar albeit to Markdown nodes, you could write something similar for asciidoc nodes
