### ISSUE TITLE
Heroku deployment with heroku-buildpack-static using https_only set to true isn't enforcing https

### ISSUE THREAD

**Issue by markhagemann** [gatsbyjs/gatsby#10934]
I've deployed a gatsby site with heroku using https://github.com/heroku/heroku-buildpack-static and my understanding is that if https_only is set to true in the static.json file then it should be forcing http requests to https.

static.json
```
{
  "root": "public/",
  "clean_urls": false,
  "https_only": true,
   ...
   ...
}
```

When logging into heroku and viewing the deployed static.json it is also set to true. 

The site is https://www.ltnetwork.co/

Thanks

**Comment by jgierer12** [comment]
Works fine for me, navigating to `http://ltnetwork.co` in incognito mode redirects to `https://www.ltnetwork.co`.

**Comment by markhagemann** [comment]
It does redirect to https://www.ltnetwork.co but once the page has loaded, if I edit the address in chrome to remove the s from https it will allow me to view http://www.ltnetwork.co  

Example:
https://imgur.com/a/AXZpTzz

Are you able to reproduce that? I'm not sure if the https_only option is meant to work the same way as htaccess or nginx server blocks for forcing port 80 to 443.

**Comment by sidharthachatterjee** [comment]
Hey @markhagemann 

Looks like it enforces `https` for me. Since this has to do with heroku-buildpack-static specifically I'd open an issue at https://github.com/heroku/heroku-buildpack-static 🙂 

Closing this for now but please feel free to reopen if there is something Gatsby related that we can help with!

**Comment by markhagemann** [comment]
Hey @sidharthachatterjee 

I realised that I should have linked the heroku link instead: http://ltnetwork.herokuapp.com

The http://ltnetwork.co redirect is due to an old server with that domain setup to redirect via .htaccess to https://www.ltnetwork.co 

If you visit http://www.ltnetwork.co/ you will also see it isn't working. 

I did create a thread on heroku-buildpack-static but it appears to not be very active at all.
