### ISSUE TITLE
The plugin library sidebar "blinks" when you change links

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#10935]
![kapture 2019-01-08 at 20 13 09](https://user-images.githubusercontent.com/71047/50876478-1cb7e200-1382-11e9-9326-dbf9dbfbb002.gif)

**Comment by LekoArts** [comment]
https://github.com/gatsbyjs/gatsby/pull/10590
😊

**Comment by amberleyromo** [comment]
Closed in #10590
