### ISSUE TITLE
[v2.0.9] useHooks causes webpack error when deployed to Netlify

### ISSUE THREAD

**Issue by daydream05** [gatsbyjs/gatsby#10957]
## Description

In local development, useHook works but when deployed to Netlify, it breaks

### Steps to reproduce

Install the latest GatsbyJS, update to the latest React packages
and useHooks (see what i did there)

Here's the link to the repo https://github.com/daydream05/engravethatshit-website

### Expected result

The site should build and webpack should recognize hooks

### Actual result

What happened.

<img width="751" alt="screen shot 2019-01-09 at 4 07 28 pm" src="https://user-images.githubusercontent.com/11723413/50928455-b8039280-1428-11e9-8bd4-a642f0a0c07c.png">

### Environment

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.0.0 - /usr/local/bin/node
    Yarn: 1.6.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.90 => 2.0.90
    gatsby-image: ^2.0.20 => 2.0.25
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12
    gatsby-plugin-offline: ^2.0.16 => 2.0.20
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5
    gatsby-plugin-sharp: ^2.0.14 => 2.0.16
    gatsby-plugin-snipcart: ^1.0.6 => 1.0.6
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4
    gatsby-plugin-typography: ^2.2.5 => 2.2.5
    gatsby-source-contentful: ^2.0.22 => 2.0.22
    gatsby-source-filesystem: ^2.0.8 => 2.0.12
    gatsby-transformer-remark: ^2.1.19 => 2.1.19
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by DSchau** [comment]
Hey! Fun (or not so much) :)

Checking this out now.

**Comment by daydream05** [comment]
@DSchau Awesome thanks! You're about to kill two birds with one stone! Taught me hooks and possibly fix a bug haha

**Comment by t2ca** [comment]
Have you tried changing react and react-dom to 16.8.0-alpha.0

**Comment by daydream05** [comment]
@t2ca that did the trick!! Thanks! I was at 16.7.2. Closing this now

**Comment by DSchau** [comment]
@daydream05 heh - the alpha you're using should have still worked. Weird!

https://github.com/DSchau/engravethatshit-website/blob/master/package.json#L23

Glad to hear it's solved, thanks @t2ca!

**Comment by t2ca** [comment]
It's possible that Netlify was using 16.7.0 which doesn't support hooks instead of 16.7.0-alpha.2
