### ISSUE TITLE
dead link in e-commerce tutorial

### ISSUE THREAD

**Issue by karenhou** [gatsbyjs/gatsby#10953]
## Description

So I was reading the gatsby/docs/docs/ecommerce-tutorial/index.md for tutorials on how to do a e-commerce with Gatsby, then I found that the link for the following leads to a 404 page. I have no idea what the main tutorial is referring to.
![image](https://user-images.githubusercontent.com/6285935/50922020-6d2d4f00-1417-11e9-8e2c-d1d7643b5105.png)

**Comment by gurpreet-hanjra** [comment]
It's due to relative link `/tutorial/` that works fine when coming from https://www.gatsbyjs.org/docs/ecommerce-tutorial/ but it doesn't relate properly on Github. Maybe have absolute path like other links in md file.
