### ISSUE TITLE
Unique case: Version 2.0.90 not working well with loadable component and unstated.

### ISSUE THREAD

**Issue by cezarcarvalhaes** [gatsbyjs/gatsby#10954]
## Description

Bear with me, this is a bit odd:  

We have a Gatsby project that pulls in a create-react-app as a submodule. The create-react-app component is being async loaded using @loadable/component. The component renders perfectly in Gatsby v2.0.80, but when I updated to v2.0.90, I got an error saying that <Subscribe> components must be wrapped by a <Provider> component from unstated. The create-react-app uses Unstated, and in App.js it's has <Subscribe>. When pulling it into Gatsby, in the render, <App> is wrapped in <Provider>. This works with v2.0.80, but not v2.0.90. 

### Steps to reproduce

```javascript
//create-react-app App.js
import React from 'react';
import { Subscribe } from 'unstated';

class App extends React.Component {

   render() {
      return (
         <Subscribe to={[this.qContainer]}>
            {/* eslint-disable-next-line arrow-body-style */}
            { (container) => {
               return (
                  <div>
                        <Card {...container.state} />,
                  </div>
               );
          }
         </Subscribe>
    );
  }
}

export default App;
```

```javascript
//gatsby/src/pages/index.js

import React from 'react';
import { Provider } from 'unstated';
import loadable from '@loadable/component';

class IndexPage extends React.Component {
  render() {
    let appRoot = null;
    if (typeof document !== 'undefined') appRoot = document.getElementById('react-app');
    return (
                <div>
                     Hello, world!
                     <div id="react-app"><Provider><AW appRoot={appRoot}/></Provider></div>
                </div>
      );
  }

export default IndexPage;

```

### Expected result

React app should render inside the #react-app div. <--works in v2.0.80

### Actual result

Throws error saying Subscribe components need to be wrapped by a <Provider>. <--does not work in v2.0.90

### Environment

  System:
    OS: macOS 10.14.2
    CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 12.0.2
  npmPackages:
    gatsby: 2.0.80 => 2.0.80
    gatsby-image: ^2.0.15 => 2.0.19
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3
    gatsby-plugin-manifest: ^2.0.5 => 2.0.7
    gatsby-plugin-offline: ^2.0.5 => 2.0.11
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.1
    gatsby-plugin-sass: ^2.0.3 => 2.0.3
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12
    gatsby-plugin-styled-components: ^3.0.3 => 3.0.3
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.3 => 1.0.3
    gatsby-source-filesystem: ^2.0.4 => 2.0.7
    gatsby-transformer-remark: ^2.2.0 => 2.2.0
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8
  npmGlobalPackages:
    gatsby-cli: 2.4.4

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @cezarcarvalhaes 

Can you maybe link to a minimal reproduction of this?

**Comment by cezarcarvalhaes** [comment]
Sorry for leaving this out in the ether. I created a minimal reproduction of the scenario, and was unable to reproduce the error, so there's likely something else is going on. I'm going to go ahead and close this as I don't have enough free time currently to fully debug, but will circle back.
