### ISSUE TITLE
Plugin library shows two plugins selected

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#10951]
## Description & steps to reproduce

At https://www.gatsbyjs.org/plugins/
1. I typed in "shopify"
2. I clicked on `gatsby-source-shopify2`
3. I couldn't tell which READme file was getting pulled up on the right, partially because the titles of both `gatsby-source-shopify2` and `gatsby-source-shopify` are the same, and partially because the sidebar looked like both plugins were selected:

<img width="1280" alt="screen shot 2019-01-08 at 8 09 26 pm" src="https://user-images.githubusercontent.com/32467162/50920642-c20e9c80-13fa-11e9-999c-d73edc0480cc.png">

### Expected result

Just one plugin should be able to be selected at a time

### Actual result

Both of the top 2 plugins look selected.

### Environment

Chrome browser

**Comment by tsriram** [comment]
Ah, I seem to have broken this here https://github.com/gatsbyjs/gatsby/blob/d7f8e7712739633902f3e95121fa6c93f172a6a1/www/src/components/plugin-searchbar-body.js#L308

Will try to fix this up later today.
