### ISSUE TITLE
Repeating page graphql query

### ISSUE THREAD

**Issue by jeremylynch** [gatsbyjs/gatsby#10959]
I am making the same graphql query on many pages, only changing the regex query. Is there anyway I can define this query somewhere and pass a variable to change only the regex query? (eg.`"/page-image/"` in this case)

```js
export const pageQuery = graphql`
  query about {
    bannerImage: imageSharp(fluid: {originalName: {regex: "/page-image/" }}) {
      sizes(maxWidth: 1240 ) {
        ...GatsbyImageSharpSizes_withWebp
      }
    }
  }
`
```

**Comment by sidharthachatterjee** [comment]
@jeremylynch Sure, if you're creating the pages manually and if they're all pretty much the same, you could create a template for them, call `createPage` for each in `gatsby-node.js` and pass in the regex as part of context. Values passed in context are available are variables in GraphQL queries so you should be able to get away with changing `regex` to `$regex`

Take a look at the example at https://www.gatsbyjs.org/docs/node-apis/#createPages
