### ISSUE TITLE
Warning: React version not specified in eslint-plugin-react settings.

### ISSUE THREAD

**Issue by antoinerousseau** [gatsbyjs/gatsby#10967]
## Description

I get the warning when running `gatsby develop`

### Steps to reproduce

I'm using the default starter. I run:

    gatsby develop

### Expected result

No warning

### Actual result

    Warning: React version not specified in eslint-plugin-react settings.
    See https://github.com/yannickcr/eslint-plugin-react#configuration

Note that it's nothing critical, it works anyway.

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.76 => 2.0.90
    gatsby-image: ^2.0.20 => 2.0.25
    gatsby-plugin-manifest: ^2.0.9 => 2.0.13
    gatsby-plugin-offline: ^2.0.16 => 2.0.21
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5
    gatsby-plugin-sharp: ^2.0.14 => 2.0.17
    gatsby-source-filesystem: ^2.0.8 => 2.0.13
    gatsby-transformer-sharp: ^2.1.8 => 2.1.10
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @antoinerousseau 

We use `eslint-config-react-app` under the hood and this was fixed in it in https://github.com/facebook/create-react-app/pull/6132

We'll update once they publish a new version 🙂

**Comment by iwfan** [comment]
After I added the `gatsby-browser.js` file, I also encountered the same warning.

**Comment by sidharthachatterjee** [comment]
This is resolved now since `eslint-config-react-app` was published 4 days ago. Updating `gatsby` should get rid of the warning.
