### ISSUE TITLE
Add the ability for plugins to add metadata about inferred types

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#10975]
Currently we infer types for schema generation. `extend-node-type` supports setting new fields on existing nodes (`setFieldsOnGraphQLNodeType`) but doesn't support mutating existing fields

We probably need a new hook for mutating existing fields

Potential use cases for this include
- letting plugins override an incorrect (or imperfect) inference
- letting plugins add _better_ documentation for a field

cc @pieh @freiksenet

**Comment by stefanprobst** [comment]
With schema customization APIs, the behavior of `setFieldsOnGraphQLNodeType` is still to add, not extend, fields -- but the `createTypes` action can be used to e.g. add documentation to fields and types:
```js
// gatsby-node.js
exports.sourceNodes = ({ actions }) => {
  actions.createTypes(`
    """
    A Site node
    """
    type Site implements Node {
      "Site metadata like title and keywords"
      siteMetadata: SiteMetadata
    }

    """
    All the site's metadata
    """
    type SiteMetadata {
      "Describes this site"
      description: String
    }
  `)
}
```
