### ISSUE TITLE
www(showcase): closing modal after navigating items doesn't persist filters

### ISSUE THREAD

**Issue by amberleyromo** [gatsbyjs/gatsby#10971]
#9483 implemented the fix for opening a modal item from the showcase, closing it and then losing applied filters. This works if only one item is browsed.

However, if the site visitor browses multiple showcase items in the modal and then closes, the filter state is lost.

The filters should persist whether one showcase item is viewed, or multiple.

**Comment by danedavid** [comment]
Hi, I would like to start contributing to Gatsby by helping with this issue. Can I work on this?
As I understand, the filter state is lost after viewing more than one showcase item in the showcase page. The filter should preserve state no matter how many items are viewed, right?

**Comment by andrew-anguiano** [comment]
@danedavid go for it! Sounds like you know what to do. Let me know if you need any help.

**Comment by wardpeet** [comment]
@danedavid you probably have missed this section in the Readme.md
https://github.com/gatsbyjs/gatsby/tree/master/www#running-slow-build-screenshots-placeholder

**Comment by danedavid** [comment]
@wardpeet Actually I read that. But it was also written if you're working on showcase, you shouldn't do it.
