### ISSUE TITLE
[gatsby-source-wordpress] error when deleting polylang translated page

### ISSUE THREAD

**Issue by arturhenryy** [gatsbyjs/gatsby#10970]
## Description

I just encountered this error during running gatsby dev

```
error Plugin gatsby-source-wordpress returned an error


  TypeError: Cannot read property 'id' of undefined

  - normalize.js:282 entity.polylang_translations___NODE.entity.polylang_translations.map.tra    nslation
    [si-page]/[gatsby-source-wordpress]/normalize.js:282:184
```

After some searching i found the cause for that error was deleting a translated page in the wordpress backend. i did this because i dont need any translation for this page and ergo no duplicate version of this page.

### Expected result

There should be some kind of check in place for empty values in that normalizing function and it should not break the entire app just because there is no translation for a page available.

### Actual result

app compilation fails

### Environment

```
  System:
    OS: macOS High Sierra 10.13.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 11.0.2
  npmPackages:
    gatsby: ^2.0.63 => 2.0.85
    gatsby-image: ^2.0.22 => 2.0.25
    gatsby-link: ^2.0.7 => 2.0.7
    gatsby-plugin-catch-links: ^2.0.9 => 2.0.9
    gatsby-plugin-feed: ^2.0.11 => 2.0.11
    gatsby-plugin-google-analytics: ^2.0.8 => 2.0.8
    gatsby-plugin-manifest: ^2.0.11 => 2.0.13
    gatsby-plugin-netlify: ^2.0.6 => 2.0.6
    gatsby-plugin-nprogress: ^2.0.7 => 2.0.7
    gatsby-plugin-offline: ^2.0.18 => 2.0.21
    gatsby-plugin-page-transitions: ^1.0.7 => 1.0.7
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.5
    gatsby-plugin-sass: ^2.0.7 => 2.0.7
    gatsby-plugin-sharp: ^2.0.14 => 2.0.17
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.4
    gatsby-plugin-twitter: ^2.0.8 => 2.0.8
    gatsby-remark-autolink-headers: ^2.0.12 => 2.0.12
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.0.8
    gatsby-remark-images: ^3.0.1 => 3.0.1
    gatsby-remark-prismjs: ^3.1.4 => 3.2.0
    gatsby-remark-responsive-iframe: ^2.0.7 => 2.0.8
    gatsby-source-filesystem: ^2.0.11 => 2.0.12
    gatsby-source-wordpress: ^3.0.19 => 3.0.21
    gatsby-transformer-remark: ^2.1.15 => 2.1.19
    gatsby-transformer-sharp: ^2.1.9 => 2.1.10
  npmGlobalPackages:
    gatsby-cli: 2.4.7
```

**Comment by sidharthachatterjee** [comment]
Just looking at the source @arturhenryy and it does seem to check if the `entity` has `polylang_translations` (please correct me if I am wrong)

https://github.com/gatsbyjs/gatsby/blob/2684055ba669737c983769159e6726cc4685acb0/packages/gatsby-source-wordpress/src/normalize.js#L292

Can you link to a minimal reproduction of this?

**Comment by sidharthachatterjee** [comment]
> After some searching i found the cause for that error was deleting a translated page in the wordpress backend

I'm not familiar with this on WordPress but maybe along with deleting the translation, you need to delete the relationship in the entity as well?

**Comment by cardiv** [comment]
Hey @arturhenryy,

testing some alternatives to WPML? :smile:

Did you found a way to fetch the translated posts with Polylang? According to [wp-rest-polylang](https://github.com/maru3l/wp-rest-polylang), the plugin does the same as `wpml-rest-api`: Populating only the current language and the translated locale + id. As I can see, it does not allow to even switch the language on WP REST API (e.g. `?lang=en`), right?

**Comment by arturhenryy** [comment]
@cardiv hey mate, 
first of all thanks for your pr and your work. yeah i switched to polylang for now. i have a pretty tight deadline for the multilanguage implementation so i had to find a quick solution for this. 
considering your question, yes as far as i know that is not possible, but i do not need that at all. if you want to have language specific data you can just filter your graphql query with the lang parameter.
and yes all in all i am quite happy with polylang so far. it seems not so overbloated and unecessary complex as wpml on the backend side and it fits my requirements.

**Comment by arturhenryy** [comment]
@sidharthachatterjee sorry unfortunately i just have the full repo which is private. so you mean that although deleting the page it is still referenced as a translation in the original page? and probably need to be fixed in the database because in the backend i see no option for removing that.

**Comment by cardiv** [comment]
> filter your graphql query with the lang parameter

Interesting. Have I misunderstood what you want to do? I thought you want to create full pages of translated GraphQL nodes. Based on that I wonder how do you filter the query for the lang parameter when no lang parameter has been queried (so no translations were fetched from WordPress)?

> but i do not need that at all

Could you explain your use case a bit more, please?

**Comment by arturhenryy** [comment]
@cardiv 
ok so for example with the query for all the pages in the gatsby-node.js i query the lang field provided by polylang. on create page i provide that lang value in the context so this value is available in my page template. so now if i need language specific content like only the posts in german i can use $lang in my posts query like that to filter my posts. 

```
allWordpressPost(filter: { lang: { eq: $lang } })
```

**Comment by cardiv** [comment]
I had a look into the docs of [gatsby-source-wordpress](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/) and it seems that all fields are available inside `polylang_translations` as in, for example, `allWordpressPost`. WPML populates only a few.

And to understand your filter correctly: GraphQL searches for `polylang_current_lang` (since this includes `lang` and compares that to the current `$lang` value, right? I didn't work with filters so far. As a conclusion, a similar filter for WPML would be `locale` – but that does not contain as much field nodes as Polylang?

In that case, Polylang seems much simpler and elegant, too. They do not need a language switch like `?lang=en` on the REST API because all fields are available out of the box, if my assumption is right.

Comparing available nodes:

**WPML**

```graphql
{
  allWordpressPost {
    edges {
      node {
        # All field nodes as usual.
        id
        slug
        title
        content
        excerpt
        date
        modified
        author
        featured_media
        template
        categories
        tags
        wpml_current_locale
        wpml_translations {
          # Very few nodes available.
          locale
          wordpress_id
          post_title
          href
        }
      }
    }
  }
}
```

**Polylang**

```graphql
{
  allWordpressPost {
    edges {
      node {
        # All field nodes as usual.
        id
        slug
        title
        content
        excerpt
        date
        modified
        author
        featured_media
        template
        categories
        tags
        polylang_current_lang
        polylang_translations {
          # All field nodes available as in the parent.
          id
          slug
          title
          content
          excerpt
          date
          modified
          author
          featured_media
          template
          categories
          tags
          polylang_current_lang
        }
      }
    }
  }
}
```

**Comment by cardiv** [comment]
@arturhenryy 

And to your issue: I can confirm that the deleted translation is still _connected_ to the page in WordPress. Build is crashing.

To unlink the translation, edit the original and click on the edit button for that translation. This will remove the translation title. After that the build works for me.

<img width="290" alt="unlink-translation" src="https://user-images.githubusercontent.com/43521823/51078260-cebd1a00-16b2-11e9-9917-fd83ff592dfb.png">

**Comment by arturhenryy** [comment]
@cardiv yeah so basically this is a bug of the polylang plugin and has nothing really to do with the way the source plugin handles the response. i will close this ticket then. thanks for the response
