### ISSUE TITLE
[1.0] ValidationError: "pathPrefix" is not allowed

### ISSUE THREAD

**Issue by kevinfoerster** [gatsbyjs/gatsby#1098]
i am getting an error when using `pathPrefix`

```
The site's gatsby-config.js failed validation
ValidationError: "pathPrefix" is not allowed
```

and using `gatsby build --prefix-links="/path"` is not working either

**Comment by craig-mulligan** [comment]
@kevinfoerster change `pathPrefix -> linkPrefix` in your `gatsby-config.js`

**Comment by kevinfoerster** [comment]
nope… does add any paths prefix for my javascript? is there anything else i have to do, except providing the path?

**Comment by craig-mulligan** [comment]
@kevinfoerster, Prefix-link is a boolean flag so you just need to pass it like `gatsby build --prefix-link` and make sure the link value is added to your `gatsby-config.js` as `linkPrefix`.

**Comment by kevinfoerster** [comment]
ok, that was not directly clear to me…

just for future reference, this means setting `linkPrefix` in gatsby-config.js

```
{
linkPrefix: 'some/path'
}
```
and run this, to use the linkPrefix:

`gatsby build --prefix-link`

works like a charm… thank you
