### ISSUE TITLE
gatsby-source-wordpress to support jwt authentication requests (drafted content types)

### ISSUE THREAD

**Issue by sarahannnicholson** [gatsbyjs/gatsby#10982]
## Summary

Now that we can successfully get a bearer token from WordPress [PR 9509](https://github.com/gatsbyjs/gatsby/pull/9509) 
It would be awesome for gatsby-source-wordpress to support JWT requests to WordPress to get drafted content types. 

### Basic example

Enable a status flag for getting posts from WordPress that allows the user to get draft posts
[A more detailed description](https://github.com/gatsbyjs/gatsby/pull/9509#issuecomment-434901137)

Or exposing more endpoints to query with GraphQL??  

### Motivation
We use the [jwt-authentication-for-wp-rest-api plugin](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) for a project. We also use wordpress as a headless CMS. So the preview of drafted content in WordPress doesn't mean much for content creators. 
It would be nice to be able to query drafted posts, so that content creators can preview their content inside the website).

**Comment by cardiv** [comment]
Hey @sarahannnicholson,

I am interested in use cases for REST API authentication. Would you mind explaining more about your use of JWT authentication in `gatbsy-source-wordpress`?

To the topic: I plan to build a preview for drafts in Gatsby, but from the browser side (proxying API requests to WordPress, authenticate with a token from env and fetch a draft for that a preview has been requested). This way, the editor does not have to wait on the build and the draft pages are not publicly available.

My PR #10942 adds the ability for custom routes including query parameters like `?lang=en` for WPML translations. Something similar mentioned @pieh in the comment you linked.

**Comment by sarahannnicholson** [comment]
Oh neat, I didn't come across your PR in my searching yesterday. 

> To the topic: I plan to build a preview for drafts in Gatsby, but from the browser side (proxying API requests to WordPress, authenticate with a token from env and fetch a draft for that a preview has been requested). This way, the editor does not have to wait on the build and the draft pages are not publicly available.

Also, this could work? but we were planning to go about this a different way.
We were hoping to deploy to a separate environment with an env flag to denote a preview environment, if in the preview env we could make authenticated requests to WP's JWT, then we could show drafted content. The preview environment would be password protected. Which is why I thought making authenticated jwt requests would be a nice feature to add. But honestly, we haven't fully thought through how we would get drafted content, so I'm open to ideas that don't require modifying Gatsby. 

> This way, the editor does not have to wait on the build and the draft pages are not publicly available.

Hmmm, I'd like to try to get this to work, but I am wondering how making fetch requests instead would hide drafted pages from the public? Currently we restrict public access by deploying to servers that are password protected and access is only given to certain people within the organization. 
And what about previewing a page that has never been published and only exists as a draft? I'd expect to go to {my-domain}/my-draft-page-slug to access that page, I assume this would go in the 'exports.createPages' method, which would then need to be built.

I was looking at your PR, nice work btw! I had some questions though. 
You mention the query parameter on the `/pages` endpoint `?lang=en` a lot, would your code also work for `?status=any` or`status=draft`? 

What about query parameters on the `/posts` endpoint?
eg)

```
// Add to plugin options.
allRoutes: [
  { // Example with WPML.
    namespace: `wp/v2`,
    endpoint: `/posts/?status=draft`,
    endpoint: `/pages/?status=draft`,
  },
],
includedRoutes: [
  // ... other whitelisted routes ...
  `/*/*/posts/?status=*`,
  `/*/*/pages/?status=*`,
],
```

**Comment by cardiv** [comment]
Ah, I understand. A preview environment would help to keep previews private. Although waiting on the build to preview pages could take a long time at the moment – if you build them like published pages – the team is working on faster, incremental builds – so only changed pages will be build and not the whole site every time.

Currently, I need to figure out the details of a browser side preview. Since every WordPress post type is based on a template in Gatsby, I could imagine building a preview version of that template which could fetch the draft.

To do that, the preview button in WordPress could send some query params like the id and a one-time authentication token – that is based on the current users permissions. The Gatsby preview page will send this params to WordPress, fetch the draft data and hydrate all React components.

But this are only early considerations. I have not started building this at the moment.

To the PR: Thank you! Yes, you could add any number of query params to the route. Gatsby adds `per_page` and `page` params by default. With this PR, these two get appended to your param chain.

The config is a bit different, though. You need to add each route in a new object:

```js
allRoutes: [
  { // Example with WPML.
    namespace: `wp/v2`,
    endpoint: `/posts/?status=draft`,
  },
  {
    namespace: `wp/v2`,
    endpoint: `/pages/?status=draft`,
  },
],
```

Your example of `includedRoutes` is correct.

It may be some work to add multiple custom routes one by one, but it is flexible.

**Comment by sarahannnicholson** [comment]
I managed to get around this by using client only routes.
1. Using client only routes I dedicated the route /drafts (and all sub routes) to wordpress content
2. In the index page for the client only routes (index.js in my /pages/drafts) I use fetch to query wordpress and get my bearer token
3. in the body of the index page, I select which component to render (post or page) based on the route
eg) 
{domain}/drafts/posts/:id => goes to the posts component, which makes a request to wordpress with the id in the url to get the post
{domain}/drafts/:id => goes to the pages component, which makes a request to wordpress with the id in the url to get the page
{domain}/drafts => goes to the draftList component, which then makes a few more requests to wordpress to get all draft pages and posts. It renders them as links


It's not very fast, but as soon as you create a new draft of a page/post you can immediately see your changes in the {domain}/drafts area of the site. 

Closing the ticket, I don't believe this feature request is necessary given that there is a solid implementation with client only routes. Hopefully this is helpful for others trying to accomplish something similar.
