### ISSUE TITLE
Page source content doesn't appear with gatsby-plugin-offline

### ISSUE THREAD

**Issue by likush** [gatsbyjs/gatsby#10998]
I want to use gatsby-plugin-offline in my project, but if it's connected, source page content disappear (I tried to see it in "View page source")
<img width="2555" alt="google chrome_2019-01-11 14-45-34 2x" src="https://user-images.githubusercontent.com/31741926/51032952-d2697780-15b2-11e9-97b0-8cb29a3461e0.png">
Without gatsby-plugin-offline and unregister service workers everything is ok.
<img width="2556" alt="google chrome_2019-01-11 14-43-45 2x" src="https://user-images.githubusercontent.com/31741926/51033040-1e1c2100-15b3-11e9-8091-9de25c26b176.png">

I used this [starter](https://github.com/netlify-templates/gatsby-starter-netlify-cms) as base, this is my [repo](https://github.com/likush/gatsby-starter-netlify-cms) (I've added gatsby-plugin-offline).
[gatsby-node.js](https://github.com/likush/gatsby-starter-netlify-cms/blob/master/gatsby-node.js)
[package-json](https://github.com/likush/gatsby-starter-netlify-cms/blob/master/package.json)

**Comment by LekoArts** [comment]
Hi!
You're not the first person to ask this question, that's why we added a _Notes_ section on the README:
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-offline#notes

I'll close this issue but if you need further explanation than the README, please let me know 👍

**Comment by likush** [comment]
@LekoArts Thanks. Also, I have another one problem: I tried to make page sharing, and there are no actual information in sharing preview. Meta tags values exist in <head> tag (in Inspect -> Elements). It may be because there are no content in page source?
