### ISSUE TITLE
[GraphQL] Querying with Sift on any array node field

### ISSUE THREAD

**Issue by sondrele** [gatsbyjs/gatsby#10990]
## Summary

The node query API of Gatsby is really powerful, it's a joy to use, and it helps us move some of the complexity from the view/js down to the node sourcing build step instead.

However, sometimes I wish I could express even more in a query, especially when it comes to filtering/sorting (Sifting) array fields of a node. This is not possible today, although it could easily be expressed in js. **Even so, the more we can express in gql-query, the cleaner and less complex our UI-code comes out.**

### Basic example

Consider the below data:

```json
[
  {
    "name": "My hardware shop",
    "products": [
      { "name": "Nail", "weight": 15 },
      { "name": "Gear", "weight": 80 },
      { "name": "Hotstopper", "weight": 10 }
    ]
  },
  {
    "name": "Jon's hardware shop",
    "products": [
      { "name": "hammer", "weight": 550 }
    ]
  }
]
```

By generating nodes for my companies, I would be able to query them like this:

```gql
{
  allCompany {
    edges {
      node {
        name
        products {
          name
        }
      }
    }
  }
}
# result:
# [
#   {
#     "name": "My hardware shop",
#     "products": [
#       { "name": "Nail" },
#       { "name": "Gear" },
#       { "name": "Hotstopper" }
#     ]
#   },
#   {
#     "name": "Jon's hardware shop",
#     "products": [
#       { "name": "hammer" }
#     ]
#   }
# ]
```

Now consider the case where I want to display all companies with a list of their products *that weigh more than a certain threshold*, like this:
```gql
{
  allCompany {
    edges {
      node {
        name
        products(filter: { weight: { gt: 10 }}) {
          name
        }
      }
    }
  }
}
# wanted result:
# [
#   {
#     "name": "My hardware shop",
#     "products": [
#       { "name": "Nail" },
#       { "name": "Gear" }
#     ]
#   },
#   {
#     "name": "Jon's hardware shop",
#     "products": [
#       { "name": "hammer" }
#     ]
#   }
# ]
```

This is not possible to query on the schemas that gets generated by default today. It could be solved by manually implementing `setFieldsOnGraphQLNodeType`, but this would require me to do it for every node array field.

### Motivation

This feature will improve the default generated query API, which gives us more control of what data we can query. Any UI code will get the benefit of being able to express more in its query, and thus resort to doing less in the UI layer of a Gatsby site.

To me, it seams like this is a functionality that "should have been part of Gatsby", but there might be a good reason for it not to be present. I don't know how complex it is to implement something like this, or whether it will degregate performance, or other parts of the build process.

What do you think, is this a feature that you have discussed or would consider implementing/supporting in the future?

**Comment by sidharthachatterjee** [comment]
This is not too difficult to implement (since we already use sift to help query connections) but I think the complexity lies in knowing when to create connections out of an Array

cc @pieh @freiksenet

**Comment by sondrele** [comment]
Thanks for your answer @sidharthachatterjee !

> This is not too difficult to implement (since we already use sift to help query connections)

This was my thought about this as well! :)

> but I think the complexity lies in knowing when to create connections out of an Array

How so? Wouldn't it be possible to somehow make all arrays "siftable", no matter how the nodes are connected? Note that I have no insight in how the schemas are actually generated, so I don't know where exactly the complexity lies.

**Comment by sondrele** [comment]
@pieh Is this something you have looked into and would like to support natively in Gatsby?
If so, I might have some extra time to implement

**Comment by jschuler** [comment]
I am also looking for this feature so that i can filter on a nested array of objects and get just the items back that fulfill my criteria

**Comment by sondrele** [comment]
@sidharthachatterjee Has this issue been ignored due to gatsbot, or is it still being considered?

**Comment by stefanprobst** [comment]
@sondrele We currently don't have any plans to add query arguments to fields other than root query fields. However, we have recently added [new APIs for schema customization](https://www.gatsbyjs.org/blog/2019-03-18-releasing-new-schema-customization/) that (hopefully) make building something like this on your own quite straightforward. There are different approaches you could take (also depending on how generic a solution this should be), but you could simply add a query argument to the `products` field to specify a minimum weight:
```js
exports.createResolvers = ({ createResolvers }) => {
  createResolvers({
    CompanyJson: {
      products: {
        args: {
          minWeight: `Int`,
        },
        resolve(source, args) {
          const { products } = source
          const { minWeight } = args

          return minWeight == null
            ? products
            : products.filter(product => product.weight >= minWeight)
        },
      },
    },
  })
}
```
You could also define a more generic query type and use that on the `products` field. It is even possible to do this as an inline SDL string. For example:
```js
exports.createResolvers = ({ createResolvers }) => {
  createResolvers({
    CompanyJson: {
      products: {
        args: {
          weight: `input ProductWeight { gt: Int, lt: Int }`,
        },
        resolve(source, args) {
          const { products } = source
          const { weight } = args

          if (!weight) return products

          const { gt, lt } = weight
          return gt != null
            ? products.filter(product => product.weight > gt)
            : products.filter(product => product.weight < lt)
        },
      },
    },
  })
}
```
