### ISSUE TITLE
[site-showcase] category filters shouldn't jump up

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#11001]
## Description
It's part of #9048 where we want to scroll down when people visit the page with ?filters in their url.

Sadly we scroll up on each time we select a new category.

### Steps to reproduce

1) go to https://www.gatsbyjs.org/showcase/
2) click on a category filter
3) site jumps back up

### Expected result

It should not scroll up, maybe it should scroll back to the top of the showcase but not to the top of the page
![image](https://user-images.githubusercontent.com/1120926/51036465-81a35000-15ad-11e9-9ceb-8f825a0bf897.png)

### Actual result

![scroll showcase](https://user-images.githubusercontent.com/1120926/51036383-38530080-15ad-11e9-8cdc-39b1ffdd875b.gif)

**Comment by marcysutton** [comment]
I wonder if that's focus management happening with Reach Router, where focus is being set to the top of the page when the view changes? Might be worth looking into. Perhaps focus could go to the lower part of the view if that makes more sense from an interaction standpoint ("N Sites (filtered)" in your animated GIF").
