### ISSUE TITLE
Adding itemProp="image"

### ISSUE THREAD

**Issue by patrickcameron** [gatsbyjs/gatsby#11005]
## Summary

It seems as though adding the `itemProp="image"` attribute to a Gatsby Image component doesn't work - it just gets stripped out when the page is compiled.

### Basic example

`<Img itemProp="image" fluid={image.fluid} key={i} />` - itemProp does not show up on the rendered image container or any of its children.

### Motivation

Having this ability would be useful for adding schema.org data to pages.

Apologies if I'm just missing something or this has already been addressed - I tried searching for this issue but couldn't find anything.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @patrickcameron 

Should be simple to add a prop and pass it down to the image element in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js

We would love to accept a PR adding support for this!

**Comment by patrickcameron** [comment]
> We would love to accept a PR adding support for this! Would you be interested?

I will give it a try! Should have a PR ready to submit today or tomorrow.

**Comment by sidharthachatterjee** [comment]
Great! Thank you @patrickcameron

**Comment by rafaelgfx** [comment]
@patrickcameron how is the progress of this task?

**Comment by patrickcameron** [comment]
> @patrickcameron how is the progress of this task?

I just submitted a PR. Please let me know if there's anything I need to fix. This is my first time submitting to a big open source repo.
