### ISSUE TITLE
[gatsby-transformer-remark] move toc and excerpt to remark-plugins

### ISSUE THREAD

**Issue by benjaminabel** [gatsbyjs/gatsby#11004]
Hi, as the title says, I think it would be preferable to move the toc, excerpt and other remark extra features to respective `gatsby-remark-toc`, `gatsby-remark-excerpt` in order to keep the separation of concern of each plugin.

**Comment by sidharthachatterjee** [comment]
Just want to mention that this will be a breaking change for existing users of `gatsby-transformer-remark`

**Comment by DSchau** [comment]
@benjaminabel could you provide some more detail as to why this would be beneficial? I can see your point, but co-locating this common functionality into the one plugin has some additional benefits, e.g. you can make changes to related functionality in _one_ spot rather than in several.

**Comment by benjaminabel** [comment]
@sidharthachatterjee I know that this implies breaking changes, however this could be covered smoothly adding the new plugins as dependencies wirh a warning message until a further release.

**Comment by benjaminabel** [comment]
@DSchau first of all I think toc,  metadata, excerpt, are out of the scope of the transformer plugin, they are really handy but could be provided by plugins.
These changes could allow to extend the API that the transformer provide to plugins for exemple to allow them to work on the hast tree as it is done when creating the toc, maybe we could also allow plugins to handle the html code.

**Comment by benjaminabel** [comment]
@DSchau I can investigate in the creation of `gatsby-remark-toc`. Is it worth trying or there's no way to get this merged, or is this unnecessary.
