### ISSUE TITLE
Browser navigation does not work with gatsbygram

### ISSUE THREAD

**Issue by sedubois** [gatsbyjs/gatsby#1101]
- visit https://gatsbygram.gatsbyjs.org
- click on a picture
- hit F5 -> image displays in standalone instead of overlay, OK
- hit the back button -> URL changes back to https://gatsbygram.gatsbyjs.org but page doesn't change

<img width="1132" alt="screen shot 2017-06-04 at 10 58 52" src="https://cloud.githubusercontent.com/assets/4217871/26760286/d80dd5c6-4914-11e7-8fd0-5adbaa81c002.png">

**Comment by 0x80** [comment]
Might be related #1102

**Comment by KyleAMathews** [comment]
It's a different problem. We're not waiting for the page component to load when clicking the back button so it errors (check the console). Try following steps above but then clicking on "Gatsbygram". That works.

I'll be doing a refactor of of our runtime later this week and will make sure this gets handled.

Thanks for the very clear bug report!

**Comment by KyleAMathews** [comment]
This is fixed now. Thanks for reporting! Hadn't noticed this tricky but fairly common edge case.
