### ISSUE TITLE
gatsby-plugin-google-tagmanager and Google Search Console Verification

### ISSUE THREAD

**Issue by stmcallister** [gatsbyjs/gatsby#11014]
Has anyone had issues getting Google Search Console to verify ownership of your site with Google Tag Manager using `gatsby-plugin-google-tagmanager`? 

We're using the plugin, and our analytics are flowing wonderfully. But, I'm being told by the person who is trying to add our site in Google Search Console that GTM is not verifying. The only difference between the gatsby plugin code and the code they want me to use is this:  `'https://www.googletagmanager.com/gtm.js?id='+i+dl+''` and `'https://www.googletagmanager.com/gtm.js?id='+i+dl`. The first one as an extra `+''` at the end...which isn't functionally different. 

So, has anyone else using the plugin had issues verifying their sites?

**Comment by cardiv** [comment]
Hey @stmcallister,

thank you for raising this issue.

Does the requested changes to GTM code work adding the site to Search Console?

If so, would you mind creating a PR for that?

**Comment by maxlapides** [comment]
I tested the idea of removing the `+''` and it unfortunately didn't resolve the issue for me.

**Comment by stmcallister** [comment]
Do you get any kind of error message?

**Comment by maxlapides** [comment]
"We could not find any Google Tag Manager container ID on the index page of your site.”

**Comment by sidharthachatterjee** [comment]
@stmcallister @maxlapides 

`gatsby-plugin-google-tagmanager` adds the script recommended in https://developers.google.com/tag-manager/quickstart at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-tagmanager/src/gatsby-ssr.js

Can you please link to a minimal reproduction of this if possible?

**Comment by stmcallister** [comment]
Turns out the culprit is the `iframe` code snippet just inside `<body>`.  The plugin is generating line breaks to make the `iframe` code more readable, like so:

`<iframe
  src="https://www.googletagmanager.com/ns.html?id=GTM-xxxxxx"
  height="0"
  width="0"
  style="display: none; visibility: hidden"
></iframe>`

This does not allow Google Search Console to verify ownership of the site. However, if you remove the line breaks, and make the `iframe` code look like the code below GSC is happy and verifies site ownership.

`<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-xxxxxx" height="0" width="0" style="display: none; visibility: hidden"></iframe>`

My pull request above removes the line breaks in the iframe code.

**Comment by wardpeet** [comment]
Looks like this is fixed! Sweet thank you for your PR! @stmcallister 
We really appreciate it!
