### ISSUE TITLE
createPages context must be nullable in graphql?

### ISSUE THREAD

**Issue by marcos-rios** [gatsbyjs/gatsby#11015]
## Summary
When generating pages from markdown files and passing the slug to the component context it's not working on graphql as intended in the documentation/guides.

## Relevant information
```
import React from 'react'
import { graphql, StaticQuery } from 'gatsby'
import Layout from '../components/layout/layout'
import { Header } from 'semantic-ui-react'

const Post = () => (
  <StaticQuery
    query={graphql`
      query($slug: String!) {
        markdownRemark(fields: { slug: { eq: $slug } }) {
          html
          frontmatter {
            title
          }
        }
      }
    `}
    render={data =>
      <Layout>
        <Header size={'huge'} content={data.markdownRemark.frontmatter.title} />
        <div dangerouslySetInnerHTML={{ __html: data.markdownRemark.html }}/>
      </Layout>
    }
  />
)

export default Post
```

`gatsby-config.js`: N/A
`package.json`: N/A 
`gatsby-node.js`:
```
exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions
  const blogPostTemplate = path.resolve(`src/templates/blog-post.js`)

  return graphql(`
    {
      allMarkdownRemark {
        edges {
          node {
            fields {
              slug
            }
          }
        }
      }
    }
  `
  ).then(result => {
    if (result.errors) {
      throw result.errors
    }
    result.data.allMarkdownRemark.edges.forEach(({ node }) => {
      console.log('\n\n=== adding ' + node.fields.slug + ' to ' + blogPostTemplate + '===\n\n')
      createPage({
        path: node.fields.slug,
        component: blogPostTemplate,
        context: {
          // Data passed to context is available
          // in page queries as GraphQL variables.
          slug: node.fields.slug,
        },
      })
    })
  })
}

```
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 

I had a hard time debugging and figuring out what was wrong with this code. The problem was the non nullable variable in the graphql query. If I remove the `!` sign from `String!`, the page is generated correctly. Otherwise, I get the following error:
```
Errors:
  Variable "$slug" of required type "String!" was not provided.
```

Is that the intended behaviour? I guess it isn't since when querying for the slug in GraphiQL the values is returned as expected and when removing the `!` the query matches correctly and the page content is also displayed correctly.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @marcos-rios 

The reason the above isn't working is because StaticQuery does not accept variables as documented in https://www.gatsbyjs.org/docs/static-query/#how-staticquery-differs-from-page-query

You need to export a page query from the Post component file and then the context passed to it will be available in the GraphQL query. 

> The problem was the non nullable variable in the graphql query. If I remove the ! sign from String!, the page is generated correctly.

This is a red herring and works because by removing the `!` makes `slug` nullable and therefore `null` (which is what get passed in because context isn't accessible) a valid value
