### ISSUE TITLE
When i create a wildcard path, a folder named * is created

### ISSUE THREAD

**Issue by Pitchlab** [gatsbyjs/gatsby#11024]
## Wildcard path creates folder named * - which I can't upload
I created a path like this: 
```
 createPage({
      path: "/s/*",
      component: SomeTemplate,
      context: {}, 
    });
```

When using `gatsby develop` this works fine locally on MacOSX. But after running `gatsby build` and trying to upload to a generic Linux server, I got some errors. Investigating showed me that a folder named '*' is present in the public folder. Linux apparently doesn't like that. 

```
public
-- s
---- *
------ index.html 
...
```

What should I do to resolve this? I want to match paths such as this: 
```
https://mysite.com/s/<some GUID>
```
And I don't want to use a querystring. 

```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.8.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 63.0.1
    Safari: 12.0
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
You need to pass in `<some GUID>` in the `createPage` function instead of the `*`. The `path` doesn't accept "wildcards", it creates pages on the respective paths.
