### ISSUE TITLE
Filter out medium post based on tags

### ISSUE THREAD

**Issue by bhavaniravi** [gatsbyjs/gatsby#11022]
I am trying to bring in all my medium blogs and display them on my Gatsby site.

I am trying to write a GraphQL query which will eliminate posts with certain tags. How do I go about doing it

My current query filters out just the post leaving the Series
```
query {
        allMediumPost(limit:10, filter: {type:{eq:"Post"}}, 
                                  sort: { fields: [latestPublishedAt], order: DESC }) {
          edges {
            node{
              id
              uniqueSlug
              title
              latestPublishedAt
              virtuals {
                totalClapCount
                subtitle
                readingTime
                responsesCreatedCount
                previewImage {
                        imageId
                }
                tags {
                    name
                }
              }
              author {
                id
                name
              }
              
            }
          }
        }
      }
```

**Comment by LekoArts** [comment]
Do you have your repository available? You should have a look at the GraphQL docs on `filter`: https://www.gatsbyjs.org/docs/graphql-reference/#filter

**Comment by sidharthachatterjee** [comment]
Hey @bhavaniravi 

Took a look at the response from Medium and the schema. I don't see tags for `allMediumPost` whereas I do see them in `allMediumCollection`

Can you elaborate a little more on your use case?

**Comment by bhavaniravi** [comment]
@sidharthachatterjee It does have `tags` in `allMediumPost` under `virtuals->tags->name`.
@LekoArts 

```
filter: {type:{eq:"Post"},virtuals:{tags:{name:{in:["Programming"]}}}}
```

Here is the filter I am trying to write but it says `name field is unknown`

![image](https://user-images.githubusercontent.com/10116000/51119769-b3304b80-1839-11e9-8891-e51834f14b39.png)

**Comment by sidharthachatterjee** [comment]
@bhavaniravi Here you go 

```
{
  allMediumPost(filter: {
    virtuals: {
      tags: {
        elemMatch: {
          slug: {
            in: "bitcoin"
          }
        }
      }
    }
  }) {
    totalCount
    edges {
      node {
        id
        title
        virtuals {
          tags {
            slug
            name
            postCount
            type
          }
        }
      }
    }
  }
}
```

**Comment by sidharthachatterjee** [comment]
Closing this issue for now but please feel free to reopen if there is anything else @bhavaniravi 

Thanks!
