### ISSUE TITLE
How to port an existing html/bootstrap scss website with some custom js code to gatsby?

### ISSUE THREAD

**Issue by ergunpp** [gatsbyjs/gatsby#11036]
Hi,
I have just finished my first website with Gatsbyjs showcasing around 15 products with product data coming from contentful.

Now I have another website running at chefschoice.com.tr that I want to port to gatsby. I have played around with directly adding existing scss to gatsby (which failed at module.exports even after adding node-sass plugin) and also with reactstrap. Reactstrap seemed to require a complete rewrite of the code.
Is there a quick and easy way or maybe a comprehensive documentation for this kind of migration?
I can not move forward, as with every little step there comes a problem that I have to spend hours to solve.

**Comment by ergunpp** [comment]
Yes I can confirm Version 2 and gatsby-plugin-sass

**Comment by sidharthachatterjee** [comment]
@ergunpp Can you link to a reproduction repo for the issue you're facing with [gatsby-plugin-sass](https://www.gatsbyjs.org/packages/gatsby-plugin-sass/)?
