### ISSUE TITLE
[Regression] createRemoteFileNode is not able to guess filename from temporary urls

### ISSUE THREAD

**Issue by oorestisime** [gatsbyjs/gatsby#11037]
(Sorry for not respecting the template)

So #9777 introduced a regression when the It tries to guess the remote file name on urls that do not contain the filename. Such urls are temporary download urls. I guess this is acceptable

**But** when those urls are somewhat long (>255 characters) then it will try to save the file under that name and fail since it exceeds the maximum characters allowed in a filename (255 on ext4).

**Proposal:** same thing with the extension, the `createRemoteFileNode` could take an optional parameter that enforces the name of the file.

If this is ok I am willing to make the necessary changes here.

(How i came here https://github.com/oorestisime/gatsby-source-dropbox/issues/2)

**Comment by hbish** [comment]
I think it makes sense to have an override as there are lots of different use case of this utility method and there is no way to cater for each and every use case. Thanks for proposing this @oorestisime
