### ISSUE TITLE
Plugin gatsby-transformer-remark is not compatible with your gatsby

### ISSUE THREAD

**Issue by ocian** [gatsbyjs/gatsby#11049]
## Summary
I use `gatsby-cli@2.4.8` when create my project, and add the `gatsby-transformer-remark` followed by the document. But I notice this warn:
> `warning Plugin gatsby-transformer-remark is not compatible with your gatsby version 2.0.76 - It requires gatsby@^2.0.88`

And, it takes no effect.
## Relevant information
node: v10.15.0
npm: 6.4.1
Operate System: Debian buster

### Environment (if relevant)
Here lists all I has done:
```sh
gatsby new .
npm install --save gatsby-transformer-remark
npm start
```

### File contents (if changed)

`gatsby-config.js`: 
```js
plugins: [
    `gatsby-transformer-remark`,
]
```
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Update your `gatsby` package in your project. When you use `new` the [starter](https://github.com/gatsbyjs/gatsby-starter-default) gets cloned. Its yarn.lock is currently at 2.0.76 that's why you see this message. It should be updated soon but in the meantime just update the gatsby package(s).

**Comment by mhenrixon** [comment]
Hi @LekoArts, how about this one: 

> warn Plugin gatsby-remark-reading-time is not compatible with your gatsby version 2.9.0 - It requires gatsby@next

Is the plugin not compatible with v2.1 and onwards?
