### ISSUE TITLE
Enable advanced redirects

### ISSUE THREAD

**Issue by osartun** [gatsbyjs/gatsby#11056]
## Motivation

We're in the process of migrating a big Wordpress instance to Gatsby which uses plugins to configure many redirects. These redirects also include wildcards and pattern matching. We were able to convert these redirects into [the redirect format that Netlify uses](https://www.netlify.com/docs/redirects/).
However, this only supports the redirects on the server side. At some point we want to use Gatsby's `Link` and `navigate` everywhere which means that if a redirecting URL is linked on a page it should work on the client side as well. But the way Gatsby supports redirects is unfortunately very limited.
https://github.com/gatsbyjs/gatsby/blob/8d3af3f9d880f4c94d46823371257037dac4dd28/packages/gatsby/cache-dir/navigation.js#L10-L18
The way it's currently determining whether a path should be redirected is if it matches _exactly_ the `fromPath` specified with the [`createRedirect`](https://www.gatsbyjs.org/docs/actions/#createRedirect) action.
That means that even a trailing slash could hinder the redirect from matching.

## Summary

What I'm suggesting is not for Gatsby to support complex / dynamic redirects because I read [the argument that this needs to work on all hosting platforms as well](https://github.com/gatsbyjs/gatsby/issues/10424#issuecomment-447008565) and I understand that using Regex might not work everywhere.
What I'd like to see is some way to hook into this redirect functionality, so that it works the other way round: So that a plugin like `gatsby-plugin-netlify` is able to support `/foobar/*` and `/:year/:month/:date/:slug` paths also on the client side. And can make sure that a trailing slash wouldn't break the redirect (just as Netlify does on the server side).

So, I'd really appreciate it if you add a way – probably in the Browsers API – that enables overriding the default `maybeRedirect` functionality.

**Comment by KyleAMathews** [comment]
Why do you need complex redirect support in the browser? Generally you just want to load the site with the present URLs — people should then navigate within that structure. Redirects are just for old links which then gets redirected on the server to their new URL.

**Comment by emaildano** [comment]
@osaturn did you ever solve this? I’m working on a plugin that does exactly this for the platform I work on, getshifter.io.

Using the Redirection plugin, WP REST API and a bit of JS, regex style redirects are possible on our static sites. I think the same idea could apply to GatsbyJS.

**Comment by osartun** [comment]
@emaildano @KyleAMathews Yes, sorry, I never replied here.
So, we actually solved the issue by changing the content. I wrote an internal Gatsby plugin that runs `onPostBuild` and goes through all relevant pages and checks if the in-site and relative links on these pages point to existing Gatsby pages. If not it reports it as a broken link in the build output. This is how we were able to find all redirects (and other actually broken links!) and change them in a way that they would refer to a page directly.

This is a different way than supporting complex redirects, but for us it was good approach.

**Comment by insaurabh** [comment]
We can use client-side routing   with `getServerData` to have SSR

URL like : site-url.co.uk/flats-for-sale-in-dorking

```
export async function getServerData(context) {
  try {
    const param = context.params[`*`];
    const regexPattern = /(\w+)-for-(\w+)-in-(\w+)/;
    const match = param.match(regexPattern);
    if (match) {
      const type = match[1];
      const tenure = match[2];
      const location = match[3];

      const params = {
        // prepare
      };
      const queryString = new URLSearchParams(params).toString();
      //...

      if (!response.ok) {
        throw new Error(`Response failed`);
      }

      // return data as need
    } else {
      // When match fail
      // redirect to serach page or 404
    }
  } catch (error) {
    return {
      status: 500,
      headers: {},
      props: [],
    };
  }
}```
