### ISSUE TITLE
GraphiQL not working

### ISSUE THREAD

**Issue by b0gd4n** [gatsbyjs/gatsby#11053]
The GraphiQL interface (http://localhost:8000/___graphql) open just fine, however it does not work.

We've started building the project with Gatsby v1 and we've been using GraphiQL just fine. However, since updated to v2, it stopped working.
A few seconds after opening the ui, I get this error `TypeError: Failed to fetch` in the interface and this trace in terminal:

<--- Last few GCs --->

[80995:0x104000000]  3433624 ms: Mark-sweep 1381.8 (1428.4) -> 1381.5 (1428.9) MB, 1471.7 / 0.0 ms  (average mu = 0.065, current mu = 0.003) allocation failure scavenge might not succeed
[80995:0x104000000]  3434727 ms: Mark-sweep 1382.4 (1428.9) -> 1382.0 (1429.4) MB, 1098.9 / 0.0 ms  (average mu = 0.040, current mu = 0.004) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x099d2009d9f1 <JSObject>
    0: builtin exit frame: stringify(this=0x099d200909c1 <Object map = 0x99d42283e21>,0x099d185025b1 <undefined>,0x099d185025b1 <undefined>,0x099d85f02201 <Object map = 0x99deeb32f91>,0x099d200909c1 <Object map = 0x99d42283e21>)

    1: arguments adaptor frame: 1->3
    2: stringify(aka stringify) [0x99d968bec61] [/Users/bogdan/Dev/kaizen/kaizen-2018/node_modules/express/lib/response.js:1119] [b...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1000623a3 node::Abort() [/usr/local/bin/node]
 2: 0x100062c0a node::FatalTryCatch::~FatalTryCatch() [/usr/local/bin/node]
 3: 0x1001a2227 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x1001a21c4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1005a68a2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x1005a8dd3 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 7: 0x1005a5308 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x1005a34c5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1005afd6c v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x1005afdef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x100581c74 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
12: 0x1008bc54b v8::internal::IncrementalStringBuilder::Extend() [/usr/local/bin/node]
13: 0x10068a257 v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [/usr/local/bin/node]
14: 0x10068e46d v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
15: 0x10068b328 v8::internal::JsonStringifier::SerializeJSReceiverSlow(v8::internal::Handle<v8::internal::JSReceiver>) [/usr/local/bin/node]
16: 0x10068bc63 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
17: 0x10068eec3 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
18: 0x10068b328 v8::internal::JsonStringifier::SerializeJSReceiverSlow(v8::internal::Handle<v8::internal::JSReceiver>) [/usr/local/bin/node]
19: 0x10068bc63 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
20: 0x10068eec3 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
21: 0x10068b328 v8::internal::JsonStringifier::SerializeJSReceiverSlow(v8::internal::Handle<v8::internal::JSReceiver>) [/usr/local/bin/node]
22: 0x10068def4 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
23: 0x10068b328 v8::internal::JsonStringifier::SerializeJSReceiverSlow(v8::internal::Handle<v8::internal::JSReceiver>) [/usr/local/bin/node]
24: 0x10068def4 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
25: 0x10068ce16 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
26: 0x1006889ae v8::internal::JsonStringify(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
27: 0x10025a9f9 v8::internal::Builtin_JsonStringify(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
28: 0xe377644fcdd 
29: 0xe37764076a6 
30: 0xe377640e458 
31: 0xe377640e458 
Abort trap: 6

**Comment by devrchancay** [comment]
Hello @b0gd4n 

I happened something similar in another project is something from the memory of nodejs.

try
```bash
NODE_OPTIONS=--max_old_space_size=4096 npm run develop
```

**Comment by b0gd4n** [comment]
hey @devrchancay - I tried making a `.npmrc` file with `NODE_OPTIONS=--max_old_space_size=4096` inside, as well as changed the develop script to
`"develop": "node --max_old_space_size=4096 node_modules/gatsby-cli develop",`

Both resulted with the same errors

**Comment by b0gd4n** [comment]
also tried using this module https://www.npmjs.com/package/increase-memory-limit - but same result

**Comment by devrchancay** [comment]
How rare is it that the maximum ever increase was `8192`

**Comment by devrchancay** [comment]
hello @KyleAMathews , why is this error

**Comment by sidharthachatterjee** [comment]
Hey @b0gd4n 

Can you please link to a minimal reproduction of this?

**Comment by b0gd4n** [comment]
@sidharthachatterjee here's a stripped down repo of our webite https://github.com/kaizenagency/public-kaizen-dummy - it happens on it as well

**Comment by sidharthachatterjee** [comment]
Looks like this might be potentially related to https://github.com/webpack/webpack/issues/6929

**Comment by cyrfer** [comment]
I cannot get the graphiql interface to load in the browser, even for new gatsby projects.

```
$ nvm use 11
Now using node v11.8.0 (npm v6.5.0)
$ npm list -g --depth 0
/Users/jkgrant/.nvm/versions/node/v11.8.0/lib
├── firebase-tools@6.3.0
└── npm@6.5.0
$ node -v
v11.8.0
$ npx gatsby new site3
...
info Create initial git commit in site3
$ cd site3
$ npm start
...
You can now view gatsby-starter-default in the browser.

  http://localhost:8000/

View GraphiQL, an in-browser IDE, to explore your site's data and schema

  http://localhost:8000/___graphql

Note that the development build is not optimized.
To create a production build, use npm run build

ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
```

When I click the link to `___graphql`, the browser never loads the page.

**Comment by jonniebigodes** [comment]
@cyrfer manually opening a new browser window to `localhost:8000/___graphql` shows GraphiQL? If not with the window opened, open the devtools post errors if they exist

**Comment by cyrfer** [comment]
@jonniebigodes Thanks, that fixed my new site folder. I'm seeing the same problem after porting the code in my old site folder over to the new site. Both the app and graphiql will not appear. The client shows the request never gets a response, but there is no warning in the cli.

I don't want to pollute this thread with my troubles since they are a different problem. I'll write a new issue ticket if I can find a way to explain what is happening.

**Comment by b0gd4n** [comment]
I am still getting this issue - just updated all packages, nothing changed.

**Comment by b0gd4n** [comment]
We've update the site packages - no other changes and this is now working perfectly fine.
