### ISSUE TITLE
[1.0] gatsby.config.js validation - child "sources" fails

### ISSUE THREAD

**Issue by Shaid** [gatsbyjs/gatsby#1105]
Hi,

I'm in the process of updating gatsby from 1.0.0alpha12 to 1.0.0alpha19 (I know, I left it a while). 

I'm getting an issue with my gatsby-config validation:

```
gatsby.config.js failed validation
ValidationError: child "sources" fails because ["sources" is required]
```

I can't see "sources" mentioned anywhere in the [joi schema](gatsbyjs/gatsby/blob/v1.0.0-alpha19/packages/gatsby/src/joi-schemas/joi.js). 

My config is current a copy of the one from the 0.x to 1.0 [migration document](https://www.gatsbyjs.org/docs/migrating-from-v0-to-v1/#add-markdown-plugins):
```
module.exports = {
  siteMetadata: {
    title: `My Sweet Gatsby Site!`,
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages/`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-responsive-image`,
            options: {
              maxWidth: 690,
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
          },
          `gatsby-remark-prismjs`,
          `gatsby-remark-copy-linked-files`,
          `gatsby-remark-smartypants`,
        ],
      },
    },
    `gatsby-plugin-sharp`,
  ],
}
```

It is, of course, possible I missed a migration step somewhere.

Thanks in advance! 1.0 is looking very exciting.

**Comment by KyleAMathews** [comment]
Run `cat node_modules/gatsby/package.json | grep version`

I'm guessing you somehow didn't upgrade quite yet.

**Comment by vishalniit** [comment]
Hi Kyle,

We also face same issue here is package.json output
`{
  "_args": [
    [
      {
        "raw": "gatsby@^1.0.0-alpha13",
        "scope": null,
        "escapedName": "gatsby",
        "name": "gatsby",
        "rawSpec": "^1.0.0-alpha13",
        "spec": ">=1.0.0-alpha13 <2.0.0",
        "type": "range"
      },
      "C:\\StaticGenerators\\Gatsby\\Project\\Develop\\lightweight-cms"
    ]
  ],
  "_from": "gatsby@>=1.0.0-alpha13 <2.0.0",
  "_id": "gatsby@1.0.0-alpha9-test1",
  "_inCache": true,
  "_location": "/gatsby",
  "_nodeVersion": "6.9.0",
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/gatsby-1.0.0-alpha9-test1.tgz_1478279177355_0.19959248742088675"
  },
  "_npmUser": {
    "name": "kylemathews",
    "email": "mathews.kyle@gmail.com"
  },
  "_npmVersion": "3.10.8",
  "_phantomChildren": {
    "argparse": "1.0.9",
    "entities": "1.1.1",
    "linkify-it": "2.0.3",
    "mdurl": "1.0.1",
    "uc.micro": "1.0.3"
  },
  "_requested": {
    "raw": "gatsby@^1.0.0-alpha13",
    "scope": null,
    "escapedName": "gatsby",
    "name": "gatsby",
    "rawSpec": "^1.0.0-alpha13",
    "spec": ">=1.0.0-alpha13 <2.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/gatsby/-/gatsby-1.0.0-alpha9-test1.tgz",
  "_shasum": "b269b94512c04102d5fd1d85863194cb68bdda2d",
  "_shrinkwrap": null,
  "_spec": "gatsby@^1.0.0-alpha13",
  "_where": "C:\\StaticGenerators\\Gatsby\\Project\\Develop\\lightweight-cms",
  "author": {
    "name": "Kyle Mathews",
    "email": "mathews.kyle@gmail.com"
  },
  "ava": {
    "require": [
      "babel-register"
    ],
    "babel": "inherit"
  },
  "bin": {
    "gatsby": "./bin/gatsby.js"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  },
  "dependencies": {
    "async": "^2.1.2",
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.7",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-transform-async-to-generator": "^6.8.0",
    "babel-plugin-transform-object-assign": "^6.8.0",
    "babel-plugin-transform-react-jsx-source": "^6.9.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-runtime": "^6.18.0",
    "babel-traverse": "^6.18.0",
    "babylon": "^6.13.1",
    "bluebird": "^3.4.6",
    "boom": "^2.7.2",
    "bundle-loader": "^0.5.4",
    "chalk": "^1.1.3",
    "chokidar": "^1.6.1",
    "chunk-manifest-webpack-plugin": "^0.1.0",
    "cjsx-loader": "^3.0.0",
    "coffee-loader": "^0.7.2",
    "coffee-script": "^1.9.3",
    "commander": "^2.9.0",
    "css-loader": "^0.25.0",
    "debug": "^2.2.0",
    "detect-port": "^1.0.5",
    "dist-exiftool": "^10.25.0",
    "eslint-plugin-react": "^6.5.0",
    "excerpt-html": "^1.1.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "front-matter": "^2.1.0",
    "fs-extra": "^0.30.0",
    "glob": "^7.1.0",
    "graphql": "^0.7.2",
    "graphql-relay": "^0.4.3",
    "hapi": "^8.5.1",
    "hapi-graphql": "^1.0.1",
    "highlight.js": "^9.6.0",
    "history": "^2.1.2",
    "invariant": "^2.2.1",
    "joi": "^9.1.1",
    "json-loader": "^0.5.2",
    "json5": "^0.5.0",
    "loader-utils": "^0.2.16",
    "lodash": "^4.16.5",
    "markdown-it": "^7.0.1",
    "md5-file": "^3.1.1",
    "mkdirp": "^0.5.1",
    "moment": "^2.15.2",
    "negotiator": "^0.6.1",
    "node-cjsx": "^2.0.0",
    "node-exiftool": "^2.0.0",
    "node-libs-browser": "^1.0.0",
    "null-loader": "^0.1.1",
    "object-assign": "^4.1.0",
    "observable": "^2.1.4",
    "offline-plugin": "^3.4.2",
    "opn": "^4.0.2",
    "parse-filepath": "^1.0.1",
    "path-exists": "^3.0.0",
    "postcss-browser-reporter": "^0.5.0",
    "postcss-cssnext": "^2.8.0",
    "postcss-import": "^8.1.2",
    "postcss-loader": "^0.13.0",
    "postcss-reporter": "^1.4.1",
    "raw-loader": "^0.5.1",
    "react": "^15.3.2",
    "react-document-title": "^2.0.1",
    "react-dom": "^15.3.2",
    "react-hot-loader": "^3.0.0-beta.6",
    "react-router": "^2.8.1",
    "react-router-scroll": "^0.3.3",
    "remark": "^6.2.0",
    "remark-html": "^5.0.1",
    "remark-parse": "^2.2.0",
    "sanitize-html": "^1.13.0",
    "slash": "^1.0.0",
    "static-site-generator-webpack-plugin": "^3.1.0",
    "style-loader": "^0.13.0",
    "tcomb": "^3.2.13",
    "toml": "^2.2.2",
    "tracer": "^0.8.7",
    "unist-util-select": "^1.5.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.3",
    "webpack-configurator": "^0.3.0",
    "webpack-dev-server": "^1.16.1",
    "webpack-md5-hash": "0.0.5",
    "webpack-require": "0.0.16",
    "webpack-stats-plugin": "^0.1.4",
    "webpack-validator": "^2.2.7",
    "yaml-js": "^0.1.4"
  },
  "description": "React.js Static Site Generator",
  "devDependencies": {
    "ava": "^0.16.0",
    "ava-http": "^0.2.1",
    "babel-cli": "^6.18.0",
    "babel-eslint": "^7.1.0",
    "babel-plugin-lodash": "^3.2.9",
    "babel-plugin-transform-flow-strip-types": "^6.18.0",
    "babel-register": "^6.18.0",
    "cheerio": "^0.22.0",
    "eslint": "^3.9.1",
    "eslint-config-airbnb": "^12.0.0",
    "eslint-plugin-flow-vars": "^0.5.0",
    "eslint-plugin-flowtype": "^2.25.0",
    "eslint-plugin-import": "^1.16.0",
    "eslint-plugin-jsx-a11y": "^2.2.2",
    "eslint-plugin-react": "^6.3.0",
    "flow-bin": "^0.34.0",
    "iflow-debug": "^1.0.15",
    "iflow-lodash": "^1.1.24",
    "iflow-react-router": "^1.1.17",
    "nyc": "^7.0.0"
  },
  "directories": {},
  "dist": {
    "shasum": "b269b94512c04102d5fd1d85863194cb68bdda2d",
    "tarball": "https://registry.npmjs.org/gatsby/-/gatsby-1.0.0-alpha9-test1.tgz"
  },
  "engines": {
    "node": ">4.0.0"
  },
  "gitHead": "86567dec11038c390ffc19eafbd02a0fd9d1f13b",
  "homepage": "https://github.com/gatsbyjs/gatsby#readme",
  "keywords": [
    "blog",
    "generator",
    "jekyll",
    "markdown",
    "react",
    "ssg",
    "website"
  ],
  "license": "MIT",
  "main": "index.js",
  "maintainers": [
    {
      "name": "kylemathews",
      "email": "mathews.kyle@gmail.com"
    }
  ],
  "name": "gatsby",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gatsbyjs/gatsby.git"
  },
  "scripts": {
    "build": "rm -r dist/; babel lib --out-dir dist/",
    "clean-test-bundles": "find test/ -type f -name bundle.js* -exec rm -rf {} +",
    "lint": "eslint --ext .js,.jsx --ignore-path .gitignore .",
    "lint:flow": "babel-node scripts/flow-check.js",
    "test": "npm run lint && npm run test-node && npm run test-integration",
    "test-coverage": "nyc --reporter=lcov --reporter=text npm test",
    "test-integration": "ava test/integration",
    "test-node": "ava test/utils",
    "watch": "rm -r dist/; babel -w lib --out-dir dist/"
  },
  "version": "1.0.0-alpha9-test1"
}
`

**Comment by KyleAMathews** [comment]
@vishalniit try upgrading to alpha 19 of Gatsby. There's been a number of breaking changes since alpha 13.

**Comment by Shaid** [comment]
@KyleAMathews I've worked out what's happening. 

`npm i gatsby@next --save` will install gatsby-alpha19, and write `"gatsby": "^1.0.0-alpha19"` to package.json. The ValidationError no longer occurs.

Subsequently nuking the contents of node_modules and then running `npm i` will install `gatsby-alpha9-test1` to satisfy `^1.0.0-alpha19`. 

So, now the question: what should I be using in package.json to install alpha19?

**Comment by KyleAMathews** [comment]
@Shaid use an exact version so delete the `^` from the version string.

**Comment by Shaid** [comment]
Thanks for you help, @KyleAMathews. All working now. 

Having used gatsby from pre1.0 days, a final 1.0 release is looking very exciting. Thank you to everyone involved for their work!
