### ISSUE TITLE
Adding guide to Docz integration

### ISSUE THREAD

**Issue by graysonhicks** [gatsbyjs/gatsby#11062]
## Summary

Add a guide for [Docz](https://www.docz.site/) integration to a Gatsby project.  Both projects emphasize the use of `.mdx` files but after spending a weekend, I can't get them working together and can't find any resource that points me in the right direction.

### Basic example

The [Storybook](https://www.gatsbyjs.org/docs/visual-testing-with-storybook/#visual-testing-with-storybook) section in the docs is a great example of what a Docz section could look like.

### Motivation

At first glance, these two projects (Gatsby and Docz) seem well matched for each other by their encouragement of `.mdx`.  Unfortunately there seems to be some webpack and/or babel changes that need to take place to get them working.  A guide similar to the Storybook one would improve the Gatsby user experience by adding another component documentation to as a possibility.

If someone has already gotten Docz working with Gatsby and would care to share their code or insights here in the meantime, that would be great.

Thanks!

**Comment by RobinCsl** [comment]
@graysonhicks I just pushed the following repo https://github.com/RobinCsl/docz-with-gatsby and I managed to get Gatsby and Docz work together. Let me know if this was what your are asking about or if I misunderstood your question.

Ah, maybe what I missed was that you also want Gatsby to deal with the `mdx` files, not just Docz. Is that it?

**Comment by benjamingrobertson** [comment]
@RobinCsl Were you able to successfully import a component from your Gatsby source into an .mdx file? Based on the errors I was getting last week, I would think you need to customize the docz webpack config to work with Gatsby.

**Comment by graysonhicks** [comment]
Thanks @RobinCsl .  What I am trying to do is import a component from the Gatsby `src` directory.  In this case, try and import the `header` component from the Gatsby `src` dir and document it with Docz.

**Comment by RobinCsl** [comment]
Oh right. 😊 
I encounter the same problem as you then:
```
Failed to compile.

./node_modules/gatsby/cache-dir/gatsby-browser-entry.js 16:2
Module parse failed: Unexpected token (16:2)
You may need an appropriate loader to handle this file type.
|
| const StaticQuery = props => (
>   <StaticQueryContext.Consumer>
|     {staticQueryData => {
|       if (
```

**Comment by graysonhicks** [comment]
Yep thats the same error.  The Storybook link I posted above shows how to fix this issue for Storybook.  Looking for the same information, but for Docz.  Thanks for looking at it.

**Comment by RobinCsl** [comment]
I’d like to give that a try, I’ve been playing a bit with Docz recently.
But of course, anyone else is welcome to look at it too!

**Comment by RobinCsl** [comment]
@graysonhicks Hopefully, this helps you :slightly_smiling_face:

**Comment by RobinCsl** [comment]
Exactly, the workaround being that you split the UI layer and the data layer into two components, and use the UI layer one in your `mdx` files.
I tried in the Storybook example and the same issue happened: using `StaticQuery` or `graphql` would prevent the build. So I assume a lot more work would be needed for that to work.

**Comment by graysonhicks** [comment]
Okay, got it.  Great stuff!
