### ISSUE TITLE
[1.0] building with prefix-link creates runtime err

### ISSUE THREAD

**Issue by craig-mulligan** [gatsbyjs/gatsby#1106]
Pretty strange, when building with the prefix flag this [runtime error](https://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=boolean&args[]=%20Check%20the%20render%20method%20of%20%60t%60)

Running in dev mode or without the prefix flag I don't see it. Wondering if anyone else has encountered this or has ideas on the root cause?

**Comment by craig-mulligan** [comment]
gatsby version : "1.0.0-alpha19-alpha.62172e76"

**Comment by nicholaswyoung** [comment]
`prefixLink` is [no more in 1.0](https://www.gatsbyjs.org/docs/migrating-from-v0-to-v1/). In 1.0, use the `gatsby-link` component instead and everything should just work.

**Comment by craig-mulligan** [comment]
Hey @nicholaswyoung, yea I'm using the `gatsby-link` the interesting thing is that it's generating the link prefix (my scripts don't 404), it just creates the ^ side effect error. 

I have two custom transformer plugins, but not sure that they are to blame cause everything works without prefix. 

```
{
  "name": "landr",
  "version": "0.0.0",
  "description": "Experimental Static site generator",
  "homepage": "https://github.com/resin-io/landr",
  "repository": {
    "type": "git",
    "url": "git@github.com:resin-io/landr.git"
  },
  "scripts": {
    "start": "gatsby develop",
    "build": "gatsby build",
    "build:prefix": "gatsby build --prefix-links",
    "deploy": "npm run build:prefix && gh-pages -d public"
  },
  "dependencies": {
    "bootstrap": "4.0.0-alpha.6",
    "gatsby": "canary",
    "gatsby-link": "canary",
    "gatsby-plugin-postcss-sass": "canary",
    "gatsby-source-filesystem": "canary",
    "gatsby-transformer-readme": "0.0.0",
    "gatsby-transformer-changelog": "0.0.0",
    "react-addons-css-transition-group": "^15.5.2",
    "react-addons-transition-group": "^15.5.2",
    "react-transition-group": "^1.1.3",
    "reactstrap": "^4.6.2"
  },
  "devDependencies": {
    "gh-pages": "1.0.0"
  }
}
```

**Comment by KyleAMathews** [comment]
Do you know what component `t` is? Perhaps disable uglify in the webpack config so you can more easily identify it.

**Comment by craig-mulligan** [comment]
Here's the un uglified error. 
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: boolean. Check the render method of `Route`
```

**Comment by KyleAMathews** [comment]
Thanks, testing this.

**Comment by KyleAMathews** [comment]
I added a linkPrefix to the gatsby-starter-blog and built it with `gatsby build --prefix-links` and it built just fine. Could you create a simple reproduction of the problem you're seeing?

Do you have a `Route` component in your project?I added a linkPrefix to the gatsby-starter-blog and built it with `gatsby build --prefix-links` and it built just fine. Could you create a simple reproduction of the problem you're seeing?

Do you have a `Route` component in your project?

**Comment by craig-mulligan** [comment]
Hey @KyleAMathews thanks for testing this, but it's not a build error, it's a browser runtime err which I think must have to do with when gatsby is building the routes. (I don't have any Route component in my app)

I've reproduced with `gatsby-starter-blog` see here: https://craig-mulligan.github.io/gatsby-starter-blog/, all I changed was the prefix link: https://github.com/gatsbyjs/gatsby-starter-blog/pull/32

**Comment by KyleAMathews** [comment]
Hmm ok see it now. Going to work today on how we're loading code into the browser anyways so will tackle this as part of that.

**Comment by KyleAMathews** [comment]
Just added an example site + some fixes for path prefixing in https://github.com/gatsbyjs/gatsby/pull/1155

Will merge and release soon.

**Comment by craig-mulligan** [comment]
Thanks that fixed this 👍
