### ISSUE TITLE
Conditional injection of gtag through gdpr cookie layer

### ISSUE THREAD

**Issue by Siregar** [gatsbyjs/gatsby#11075]
👋
I am trying to implement a gdpr cookie layer in a **Gatsby V1** project, which should inject the gtag script when the user clicks accept. My first attempt was to manipulate the `html.js` and sync the cookie with the files state. This isn't working, no script in the DOM.

Any hints what's the right place for that implementation?

Thanks for your help!

**Comment by sidharthachatterjee** [comment]
Hey @Siregar 

You could add the script in an event handler in a component, I suppose
```
import React, { Component } from 'react'

class App extends Component {
  addGoogleAnalytics() {
    const googleAnalytics = document.createElement('script')
    googleAnalytics.setAttribute('src', 'https://google.com')
    document.body.appendChild(googleAnalytics)
  }
  render() {
    return (
      <div className="App">
        <p onClick={this.addGoogleAnalytics}>Take My Data</p>
      </div>
    )
  }
}

export default App

```

**Comment by Siregar** [comment]
@sidharthachatterjee Thanks for your help. This was the right hint. :)

**Comment by sidharthachatterjee** [comment]
Glad it worked for you, @Siregar 🙂 

Closing this issue for now but please feel free to reopen or comment if you need anything else related to this
