### ISSUE TITLE
`gatsby build` vs `gatsby develop` - conditional props behave unexpectedly

### ISSUE THREAD

**Issue by polarathene** [gatsbyjs/gatsby#11099]
## Summary

Query string / URL parameters for conditionally styling placeholder in `gatsby-image` component, works in development(`gatsby develop` but not always production(`gatsby build`)?

## Relevant information

```JSX
const Placeholder = ({data , location }) => {
  const params = qs.parse(location.search, { ignoreQueryPrefix: true });
  const base42_data = {
    galleryTall: data.galleryTall,
    galleryWide: data.galleryWide,
    galleryBig: data.galleryBig,
    galleryNormal: data.galleryNormal
  }

  const base42webp_data =  {
    galleryTall: data.galleryTall_base64webp,
    galleryWide: data.galleryWide_base64webp,
    galleryBig: data.galleryBig_base64webp,
    galleryNormal: data.galleryNormal_base64webp
  }

  return (
  <Layout>
      <Gallery
        data={params.base64webp ? base42webp_data : base42_data}
        blur={params.blur}
        bg={params.bg}
      />
  </Layout>
)}
```

Gallery component contains a list of GridCell components(styled `gatsby-image` components):

```JSX
const Gallery = (props) => {
  const image_nodes = getAndSort(props.data)

  return (
  <>
      {image_nodes.map((image, i) =>
        <GridCell key={i}
          type={image.image_type}
          fluid={image.fluid}
          placeholderStyle={props.blur && {
            filter: `blur(8px)`,
            transform: `scale(1.04)`,
          }}
          backgroundColor={props.bg && "#333"}
        />
      )}
  </>
)}
```

Data contains two different qraphql queries on image data to filter based on querystring, main difference is the base64 format for placeholder thumbnails, this data exists in the published .json file that gatsby stores the query data in. The querystring parameter also works in production, but it's effect does not work in production.

Likewise, the blur prop if true, does not apply/update the html style to have the placeholder blur style applied, style appears to be baked into the index.html file(iirc in prior projects, this is direct access to the file vs navigating to another page once the website has rehydrated into a react app.

The bg prop however, will affect if the backgroundColor div exists or not, even in production... That confuses me, adding/removing elements is ok in production, but not modifying an elements attributes(base64 image data or inline style)?? Is this expected, or should there not be this functional disparity between gatsby develop and build outputs?

Reproduction repo can be provided upon request, I'm not sure if this is my own fault/error for not handling it correctly, or if it is a bug. 

### Environment (if relevant)

Alpine Linux (Docker), Node 10

### File contents (if changed)

`gatsby-config.js`: 

```js
module.exports = {
  plugins: [
    `gatsby-plugin-styled-components`,
    `gatsby-plugin-netlify`,
    `gatsby-transformer-sharp`,
    //`gatsby-plugin-no-sourcemaps`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `content`,
        path: `${__dirname}/content`,
      },
    },
    `gatsby-transformer-yaml`,
    {
      resolve: `gatsby-source-remote-images`,
      options: {
        filter: node => node.internal.type === `UnsplashImagesYaml`,
      },
    },
    {
      resolve: `gatsby-plugin-sharp`,
      options: {
        forceBase64Format: `jpeg`,
        useMozJpeg: false,
        stripMetadata: true,
      },
    },
  ],
}
```

`package.json`:

```json
 "dependencies": {
    "gatsby": "^2.0.53",
    "gatsby-image": "git+https://github.com/polarathene/forked_packages#placeholder-gatsby-image",
    "styled-components": "^4.1.3",
    "styled-modern-normalize": "^0.2.0",
    "babel-plugin-styled-components": "^1.10.0",
    "gatsby-plugin-styled-components": "^3.0.4",
    "gatsby-plugin-netlify": "^2.0.3",
    "gatsby-plugin-no-sourcemaps": "^2.0.1",
    "gatsby-plugin-sharp": "git+https://github.com/polarathene/forked_packages#placeholder-gatsby-plugin-sharp",
    "gatsby-source-filesystem": "^2.0.16",
    "gatsby-transformer-sharp": "git+https://github.com/polarathene/forked_packages#placeholder-gatsby-transformer-sharp",
    "gatsby-transformer-yaml": "^2.1.4",
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "qs": "^6.6.0"
  },
```

`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by polarathene** [comment]
Probably related to: #10706

Is there a docs page about this behaviour, some sort of tips/best practices to avoid such situations? Linked issue does describe that rehydration into a React app does appear to prevent any changes to attributes like styles and img src's(base64 placeholder thumbs) from being changed, but for elements it's alright? 

And of course navigation to other pages is client-side rather than loading up a different pages `index.html` so navigating back to the same page should display/work as intended... so... why not force some full DOM rebuild during rehydration?

**Comment by sidharthachatterjee** [comment]
@polarathene Definitely seems like a hydration issue but do link to a minimal reproduction is possible. I'd like to take a look at this!

**Comment by polarathene** [comment]
@sidharthachatterjee [Here you go](https://github.com/polarathene/gatsby-develop-build-issue). I have a similar(not quite same code) hosted on netlify presently [here](https://gifted-brattain-4080d7.netlify.com/)(it'll accept bg and blur params, [this one](https://gifted-brattain-4080d7.netlify.com/placeholder) will accept blur and base64webp params), not that it's particularly useful :)

Do note, the project sources around 140MB or so of image data from unsplash and my attempt to add local caching for the remote content didn't seem to work out.

**Comment by polarathene** [comment]
@sidharthachatterjee @gatsbybot will close(lock?) this issue at some point. Notifying you as I'm not able to add the "not stale" label, so if you think it's relevant to keep open, please do add the label.

I guess it's ok to close, although docs should perhaps point this behaviour difference between `build` and `develop` out, perhaps for troubleshooting/FAQ. I had assumed I could do this with query string params I think because of gatsbygram doing something similar.

**Comment by davidbasalla** [comment]
@polarathene did you ever find a fix/workaround for this issue? I think I've run into a similar problem with using URL query params to populate the value of a select input - works fine with `yarn develop` but not with `yarn build`...

**Comment by Natansab** [comment]
Hey @davidbasalla, I am experiencing the same issue.
What did you add to `componentDidMount` to fix this?
I have added `this.forceUpdate()` but it does not work (everything works fine using `gatsby develop`)
Thanks!

**Comment by davidbasalla** [comment]
@Natansab hmm yeah that's exactly what I did (I do add an eventListener for `popstate` in `componentDidMount` as well but that shouldn't matter) and it sorted out my particular issue. I guess alternatively you could reset state to force a render?

**Comment by wardpeet** [comment]
When rendering html files using `gatsby-build` it doesn't know about query parameters in a route. So we always render the none query parameter route. On rehydration, we should detect it and use the correct path. Note that this might cause flickering.

The problem with gatsby-image in particular and base64 is that we inline the placeholder image which is the one without a query string. Than we swap it with the original image on rehydration which might nog be the same image due the query string. We recommend creating separate pages for it or move to a client only path.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by Natansab** [comment]
Hey @wardpeet thank you for your feedback.
Actually, I still get an issue and using @davidbasalla `forceUpdate()` didn't work.

I want to set `blue-style` class to my main `div` when a user enters my website with `?blue=true` param.

```
class Example extends Component {
  // Added this but it didn't work
  // componentDidMount() {
  //   this.forceUpdate()
  // }

  render() {
    const params = new URLSearchParams(this.props.location.search)
    const displayBlue = params.get('blue')

    return (
      <div className={displayBlue === 'true' ? 'blue-style' : ''}>
        Hello
      </div>
    )
  }
}
```

On first load class is always empty `<div class>` element is created. When I change page and hit the return button then the class is set correctly.

Do you have any idea on how to fix this?

**Comment by jonniebigodes** [comment]
@Natansab you can do something like the following to get it working:
```jsx
import React, { Component } from "react"
import '../assets/css/main.css'
class SecondPage extends Component {
  state = {
    isblue: false,
  }

  componentDidMount() {
    const { location } = this.props
    const { search } = location
    const siteParams = new URLSearchParams(search)
    if (siteParams.has("blue")) {
      this.setState({ isblue: true })
    }
  }
  render() {
    const { isblue } = this.state
    return (
      <div className={isblue ? "blue-style" : "normal-style"}>Hello</div>
    )
  }
}

export default SecondPage
```
The css is the following:
```css
.blue-style{
    background-color: blue;
    color: white;
}
.normal-style{
    background-color: tomato;
    color: darkolivegreen;
}
```
Issuing `gatsby dev` and opening up `http://localhost:8000/page2` i'm presented with:

![natansab_1_dev](https://user-images.githubusercontent.com/22988955/64650064-2a909c00-d416-11e9-8362-68158531ac4f.png)

Opening a new browser window to `localhost:8000/page2?blue=true` it yelds the following:

![natansab_2_dev](https://user-images.githubusercontent.com/22988955/64650112-514ed280-d416-11e9-8308-5f6a8eb0b138.png)

Clearing the cache with `gatsby clean` and issuing a production build and serving it with `gatsby build && gatsby serve` and opening up `http://localhost:9000/page2` yelds the following:

![natansab_3_build](https://user-images.githubusercontent.com/22988955/64650197-89561580-d416-11e9-8ffb-cf8878916734.png)

And `http://localhost:9000/page2?blue=true` yelds the following:

![natansab_4_build](https://user-images.githubusercontent.com/22988955/64650255-a8ed3e00-d416-11e9-99f5-b1a4fe3c989f.png)

I would avoid using the structure you're using in the render method. As it could lead to this sort of rendering issues. More specifically in the ssr(server side rendering) "world" like in gatsby.

**Comment by Natansab** [comment]
@jonniebigodes this worked for me! It is still unclear why some stuff work with gatsby develop and not with gatsby build do to SSR rendering. Thank you though!

**Comment by jonniebigodes** [comment]
@Natansab no need to thank. Glad that i was able to solve your issue. Gatsby in development mode enables a environment that is a bit more permissive and lets you go through with some packages and some other situations that normally wouldn't work in a full production mode.

**Comment by macojaune** [comment]
Hi @Natansab, could you provide an alternative way to do this kind of thing a more "SSR friendly" way ?

**Comment by AllanPooley** [comment]
This is quite an old thread, but I was experiencing the same issue and resolved it by moving the variable that was driving the conditional rendering into a piece of state.

For example:

```jsx
import React, { useState, useEffect } from 'react';

const ConditionalComponent = (props) => {
  const [success, setSuccess] = useState(false);

  useEffect(() => {
    const queryParams = queryString.parse(location.search);
    const subscriptionSuccess = queryParams.success === 'true';
    setSuccess(subscriptionSuccess);
  }, []);

  return (
    <section className="my-component">
      {subscriptionSuccess ? (
        <ThankYouMessage />
      ) : (
        <DoSomethingModal />
      )}
    </section>
  );
}
```
