### ISSUE TITLE
bash: gatsby: command not found on running "gatsby new gatsby-site" 

### ISSUE THREAD

**Issue by adityakmr7** [gatsbyjs/gatsby#11096]
## Description

Describe the issue that you're seeing.
after running  `npm install --global gatsby-cli `

I get something like this

```
$ npm i -g gatsby-cli
C:\Users\adity\AppData\Roaming\npm\gatsby -> C:\Users\adity\AppData\Roaming\npm\node_modules\gatsby-cli\lib\index.js
+ gatsby-cli@2.4.8
updated 1 package in 21.909s

```

but while trying to to `run gatsby new gatsby-site` 

it gives

### Actual result

bash: gatsby: command not found.

### Environment
    operating system  :   windows 10
     $ node --version
        v10.12.0
      $ npm --version
        6.4.1

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

**Comment by polarathene** [comment]
Is any actual gatsby command working for you? Did you open a new terminal/console window to try the command? 

At `C:\Users\adity\AppData\Roaming\npm` You should have a bin folder I think for global modules, and there should be a gatsby file there, go to that location and try the gatsby command again, it should work then, if that's the case then you need this bin directory in your PATH variable, which would be an issue with the way you installed Node/NPM rather than gatsby.

**Comment by adityakmr7** [comment]
> Is any actual gatsby command working for you? Did you open a new terminal/console window to try the command?
> 
> At `C:\Users\adity\AppData\Roaming\npm` You should have a bin folder I think for global modules, and there should be a gatsby file there, go to that location and try the gatsby command again, it should work then, if that's the case then you need this bin directory in your PATH variable, which would be an issue with the way you installed Node/NPM rather than gatsby.

I have only two foders "bin" and "node_modules". there is no "bin" folder

**Comment by adityakmr7** [comment]
Yes I you are right problem is with nodejs installation I guess. I reinstalled my nodejs and know gatsby is working fine. Thank you.

**Comment by wardpeet** [comment]
That's awesome to hear! Have fun with gatsby!

**Comment by polarathene** [comment]
I am so confused..

> I have only two foders "bin" and "node_modules". there is no "bin" folder

@adityakmr7 you just said one of the two folders is "bin", then you say that there isn't a "bin" folder.. what?

> That's awesome to hear! Have fun with gatsby!

@wardpeet ...what? Was there more context to this earlier that's been deleted? OP hasn't confirmed they've solved the issue have they? What's awesome to hear?

**Comment by db10101** [comment]
Shouldn't be closed. Currently getting the same issue on Mac with a fresh install.

**Comment by wardpeet** [comment]
I probably was on a different issue and probably just messed up while commenting. Sorry about this.

@adityakmr7 
> I have only two foders "bin" and "node_modules". there is no "bin" folder

seems like you have a bin folder? could you echo out your `$PATH` variable. Run `echo $PATH`.
