### ISSUE TITLE
Querying reference fields from Contentful 

### ISSUE THREAD

**Issue by LpmRaven** [gatsbyjs/gatsby#11094]
I'm am using contentful to hold re-usable feature information for products. I have a content model where I have products and I have features. The products each have a reference field where you can select multiple features (which is returned as an array of strings). How do I use GraphQL to query additional information about the features that my product has? features is a reference field so I was expecting a relationship in GraphQL.

### Content model
<img width="739" alt="screen shot 2019-01-16 at 6 06 27 pm" src="https://user-images.githubusercontent.com/6523593/51232020-a20e4880-19b9-11e9-81b8-a823d3b56d6d.png">

### Product content model with features field
<img width="605" alt="screen shot 2019-01-16 at 6 08 08 pm" src="https://user-images.githubusercontent.com/6523593/51232047-b4888200-19b9-11e9-8335-690aefba67de.png">

### Product page query for products
``` javascript
query ($category: String!, $subCategory: String!, $product: String!, $rrp: Float!, $verdictRating: Int!) {
          product: allContentfulProduct(
    filter: {
          categories: {slug: {eq: $category}},
          subCategories: {slug: {eq: $subCategory}},
          slug: {eq: $product}
    }) {
    edges {
      node {
        productId
        brand {
          name
          slug
        }
        name
        slug
        categories {
          slug
        }
        subCategories {
          slug
        }
        features
        color
      }
    }
  }
```

**Comment by sidharthachatterjee** [comment]
cc @Khaledgarbaya

**Comment by Khaledgarbaya** [comment]
👋 
your query can be something like this

```
query ($category: String!, $subCategory: String!, $product: String!, $rrp: Float!, $verdictRating: Int!) {
          product: allContentfulProduct(
    filter: {
          categories: {slug: {eq: $category}},
          subCategories: {slug: {eq: $subCategory}},
          slug: {eq: $product}
    }) {
    edges {
      node {
        productId
        brand {
          name
          slug
        }
        name
        slug
        categories {
          slug
        }
        subCategories {
          slug
        }
        features {
          ...on FeatureType { 
            name
            etc...
          }
        }
        color
      }
    }
  }
```

**Comment by LpmRaven** [comment]
Thank you @Khaledgarbaya!
