### ISSUE TITLE
gatsby-plugin-remove-trailing-slashes not working when using `gatsby develop`

### ISSUE THREAD

**Issue by itmayziii** [gatsbyjs/gatsby#11105]
# Description

gatsby-plugin-remove-trailing-slashes seems to work when running `gatsby serve` but not when running `gatsby develop`

### Steps to reproduce
I created a demo project from the CLI to demonstrate the behaviour. 
https://github.com/itmayziii/gatsby-trailing-slahes-demo
<img width="1675" alt="screen shot 2019-01-16 at 11 09 28 am" src="https://user-images.githubusercontent.com/13625506/51262104-a9b0fb80-197f-11e9-8daa-b6931f775c83.png">

### Expected result

Gatsby plugins should work the same in develop as when building the project.

### Actual result

`gatsby develop` is not removing trailing slashes.

What happened.

### Environment
  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0.2
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.76 => 2.0.76
    gatsby-image: ^2.0.20 => 2.0.25
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12
    gatsby-plugin-offline: ^2.0.16 => 2.0.20
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5
    gatsby-plugin-remove-trailing-slashes: ^2.0.6 => 2.0.6
    gatsby-plugin-sharp: ^2.0.14 => 2.0.16
    gatsby-source-filesystem: ^2.0.8 => 2.0.12
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9

**Comment by sidharthachatterjee** [comment]
Sorry about the confusion @itmayziii 

Just cloned this and tested it out. The plugin seems to be working fine but I suppose the confusion is based on the fact that the Link in https://github.com/itmayziii/gatsby-trailing-slahes-demo/blob/cfe4de7d85be0be5ec22d608fb52974e8cd96405/src/pages/index.js#L17 actually links to /page-2/


From the documentation at https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/
> This plugin is intended to remove trailing slashes from paths generated by Gatsby itself.
> 
> This however does not prevent the resolution of pages that have trailing slashes, due to the way browsers are built to interpret URLs as paths.
> 
> This means that a user will need to take the extra step of ensuring that all router links direct towards paths that do not end in a slash.
> 
> For example, <Link to="/about/"> will render the view related to /about but will display as /about/ in the browsers address bar.

**Comment by itmayziii** [comment]
My mistake @sidharthachatterjee, you are right that changing the link to /page-2 fixes the issue. 

Actually I encountered this issue in a little more complicated setup and am still experiencing the issue, even when going directly to the url, but it is a private repository for work. I'm trying to figure out the best way to share the example with you.

Below is the network request to localhost:8000/pricing/roll-off-dumpster-prices but it responded with a 301 to the version with the trailing slash.
<img width="863" alt="screen shot 2019-01-16 at 11 59 55 am" src="https://user-images.githubusercontent.com/13625506/51265208-45456a80-1986-11e9-92e2-63a11d5e9b65.png">

What information can I give you that would be helpful?

**Comment by sidharthachatterjee** [comment]
@itmayziii Do you have any redirects specifically configured? That 301 looks strange 

This is when running `gatsby develop`, correct?

**Comment by itmayziii** [comment]
@sidharthachatterjee this was running `gatsby develop`. I just double checked gatsby serve again though and it appears to be the same problem 

<img width="1676" alt="screen shot 2019-01-16 at 12 40 19 pm" src="https://user-images.githubusercontent.com/13625506/51267537-f8649280-198b-11e9-8c4e-0f3868b87214.png">

**Comment by sidharthachatterjee** [comment]
I just realised that the 301 is default behaviour for most servers (and express in this instance). Chrome does not append the trailing slash in the status bar though. 

The plugin is only intended to remove trailing slashes from paths generated by Gatsby itself. Just to clear up confusion, can you please elaborate on expected behaviour versus actual?

**Comment by abohannon** [comment]
I also have this concern. We recently switched a lot of properties to Gatsby, but using the same urls because we have marketing campaigns using these urls. However, the 301/302 redirect is deleting the url params.

e.g. 

`mysite.com/page?utm_source=google`

becomes 

`mysite.com/page/`

and the tracking does not register.

Any insight into this would be very helpful.

**Comment by igorpupkinable** [comment]
I am experiencing `301 Moved Permanently` redirect to `/reviews/` when hitting `/reviews` page in development and build/serve mode.
Reviews page is located in `/src/pages/reviews.js`.
I am using gatsby@2.0.50, gatsby-plugin-remove-trailing-slashes@2.0.7, Node.js v10.15.0 x64, Windows 10 Pro x64.

**Comment by itmayziii** [comment]
Just in case anyone else comes across this issue, I'm solving the problem with a combination of Nginx configuration and the [Gatsby remove trailing slashes plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-remove-trailing-slashes). 

On the Nginx side I'm redirecting all trailing slash versions to the non trailing slash version
This goes in my server block configuration
```
rewrite ^/(.*)/$ /$1 permanent;
```

You need the Gatsby plugin also because even though the server is redirecting all traffic to the non trailing slash version, the Gatsby javascript seems to be adding the trailing slash to the URL bar. If you use the plugin it will stop doing that.
To clarify

**Comment by igorpupkinable** [comment]
not stale

**Comment by feychenie** [comment]
I had a similar issue, a 301 redirect from non-slash to slash while removing trailing slashes with the plugin.

@itmayziii, are you creating pages in gatsby-node? 

I noticed that for one (and only one) type of pages, I was calling createPage({ path: ... }) passing a `path` with a trailing slash (_ooops_), but as it was removed later by the plugin, the mistake wasn't visible when listing all the available paths after build.

The fact that it added the 301 redirects on completely unrelated pages didn't help to pinpoint the issue, and making sure that manually created pages had clean paths fixed the issue for ALL paths.

Also, if you are using `createFilePath` from `gatsby-source-filesystem`, make sure to set the `trailingSlash` option to `false`:

`const nodePath = createFilePath({ node, getNode, trailingSlash: false });`

**Comment by feychenie** [comment]
Actually, all is said in this phrase (by @sidharthachatterjee)

> The plugin is only intended to remove trailing slashes from paths generated by Gatsby itself.

So yeah, double check the paths you create programmatically :)

**Comment by itmayziii** [comment]
@feychenie 

Thanks for the tip and we are creating pages using gatsby-node, but we definitely do not have trailing slashes in our data. The issue for me specifically was that the gatsby javascript was putting the trailing slash back in the URL after the page had loaded so that if a user were to refresh there page they would get a 301 which is not ideal.

**Comment by feychenie** [comment]
> The issue for me specifically was that the gatsby javascript was putting the trailing slash back in the URL after the page had loaded so that if a user were to refresh there page they would get a 301 which is not ideal.

Yes that's exactly what I am talking about

**Comment by moroshko** [comment]
I'm using `gatsby-plugin-remove-trailing-slashes`, but it doesn't do much.
Visiting `/contact-us` redirects (301) to `/contact-us/`.
Is there a way to get rid of the redirect and the trailing slash without involving server configuration?

**Comment by jamesncampbell** [comment]
I'm experiencing the same issue. We intend not to have a server setup for this so an nginx configuration wouldn't work in our case.

**Comment by mshick** [comment]
Problem here as well. This is an issue if you're trying to align your develop URLs with production URLs.

Seems it would need to be handled in this file with some simple middleware and a config switch: 

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/develop.js

**Comment by toobulkeh** [comment]
I fixed this issue by removing the plugin `remove-trailing-slashes`. It doesn't align develop and production, but it works for hosting on netlify without trailing slashes:

(localhost on left, netlify production on right):
<img width="1672" alt="Screen Shot 2019-11-10 at 5 11 11 PM" src="https://user-images.githubusercontent.com/1342064/68551698-97f08700-03dd-11ea-8634-62e21f97fe65.png">

**Comment by aleclarson** [comment]
bump, please reopen. i'm seeing this with and w/o `gatsby-plugin-remove-trailing-slash` enabled.
