### ISSUE TITLE
Proxy isn't working with the graphql prefix

### ISSUE THREAD

**Issue by jgoux** [gatsbyjs/gatsby#11104]
Hello,

## Description

During development, I want to be able to proxy my GraphQL queries to my own GraphQL server at http://localhost:3000/graphql

I configured Gatsby like this : 
```js
module.exports = {
  proxy: {
    prefix: '/graphql',
    url: 'http://localhost:3000'
  }
}
```

Gatsby's development server is running at http://localhost:8000

My queries aren't proxied, they fired on http://localhost:8000/graphql and I got the empty `index.html` content as a response : 

`<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><script src="/socket.io/socket.io.js"></script></head><body><noscript id="gatsby-noscript">This app works best with JavaScript enabled.</noscript><div id="___gatsby"></div><script src="/commons.js"></script></body></html>`

If I set the full uri for my apollo-client configuration, it's working as expected : 
```js
{
      resolve: 'gatsby-plugin-react-apollo-hooks',
      options: {
        uri: 'http://localhost:3000/graphql'
      }
    }
```

This looks a lot like : https://github.com/gatsbyjs/gatsby/issues/10985#issuecomment-453601591

But in my case I don't have any traffic monitor. 😅 

### Environment
  System:
    OS: Linux 4.4 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.15.0 - /usr/bin/node
    Yarn: 1.13.0 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  npmPackages:
    gatsby: ^2.0.76 => 2.0.91 
    gatsby-plugin-emotion: ^4.0.1 => 4.0.1 
    gatsby-plugin-layout: ^1.0.11 => 1.0.11 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5 

Also, I'm using WSL (Windows Subsystem for Linux). So my servers are all running in Linux, but I access the application from Chrome on Windows. (I never have any issue with it)

**Comment by jonniebigodes** [comment]
@jgoux you're correct, i've tested it and let's call it the basic approach for proxying the requests when you're working with localhost does not redirect to the correct path, i've grabbed this [example](https://github.com/jlengstorf/gatsby-with-apollo), created a simple graphql server with express, adjusted it all to port 3000, issued `gatsby develop` and the proxy was always targetting the port 8000, it wasn't changing it which in turn led to a 404. Expanded the server and client to check if a http request would behave in a similar fashion, and yes it does. 
Adjusting the `gatsby-config.js` file to the advanced version of proxying does the trick, it proxies the request to the specified port.
I have a dummy example for the server and client in [here](https://github.com/jonniebigodes/test_gatsby_graphql_proxy). In this case, and after reading this specific documentation, a small adjustment could be made to mention this case.

**Comment by jgoux** [comment]
@jonniebigodes Wow thanks **a lot** for this!

Indeed, using the `developMiddleware` approach is working.

```js
import proxy from 'http-proxy-middleware'

export let developMiddleware = app => {
  app.use(
    '/graphql',
    proxy({
      target: 'http://localhost:3000'
    })
  )
}
```

Shouldn't the `proxy` version be a simple shortcut to the `developMiddleware` notation?

**Comment by amperand** [comment]
@jonniebigodes thanks! How would I implement this with gatsby-source-graphql? It's failing there as I'm working locally and it's a self-signed and issued cert.

**Comment by jonniebigodes** [comment]
@jgoux sorry for the late response i was otherwise engaged and regarding your comment, to the best of my knowledge yes it should be. But my reasoning on this is that the shortcut will proxy/redirect to a external fully qualified url. By using this notation you're overriding the default behaviour for cases like this one. 

@amperand based on what you've described, i think almost out of the box you should be able to. Going trough the steps in [here](https://www.gatsbyjs.org/docs/local-https/) and configuring it like it describes [here](https://www.gatsbyjs.org/packages/gatsby-source-graphql/) you should be able to get it up and running.

Hope i've answered your question.
Feel free to provide feedback so that we can close this issue.

**Comment by lexaurin** [comment]
This bug is very annoying. Spent hours figuring out why simple proxy configuration works on external graphql server but not on local one. Can we please reopen this @jgoux ?
