### ISSUE TITLE
[1.0] Allow pages to set a custom loader

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1110]
@jquense and I were discussing on Discord how to create pages from markdown files w/ embedded React components. One idea that came out of the discussion was that there could be a custom webpack loader which processed the markdown file into a react component using data from GraphQL.

This could be done by importing the markdown file using the custom loader into a normal JSX page e.g.

```jsx
import Component from '!custom-loader./the-markdown-file-with-components.md'
```

But that'd be inconvenient. Much better to automatically apply the loader to each markdown/react file.

If when creating pages you could set a custom loader for loading the page then we could just add that loader when generating the routes module https://github.com/gatsbyjs/gatsby/blob/fc65bf2c347d4c16a3e2651e2737d0c59ba78324/packages/gatsby/src/internal-plugins/query-runner/pages-writer.js#L110

**Comment by jquense** [comment]
working on this one :)

**Comment by KyleAMathews** [comment]
💯

**Comment by 0x80** [comment]
I would like to do something similar, but from markdown formatted text inside a json field. When pulling content from a CMS for example. Could I do the same using a transformer that catches certain nodes maybe?

**Comment by KyleAMathews** [comment]
@0x80 for that, just create new nodes for the markdown fields and set their `mediaType` to `text/x-markdown`. @jquense's react-docgen transformer does that here: https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby-transformer-react-docgen/src/on-node-create.js#L13

Then the markdown is transformed to html like normal with Gatsby's transformers and you can write queries like:

```graphql
{
  allContentFromCMS {
    product {
      description { // This is a link to separate node
        childMarkdownRemark {
          html
        }
      }
    }
  }
}
```

I also used this same technique for the documentationjs transformer which extracts jsdocs and then transforms all the documentation to markdown nodes. https://github.com/gatsbyjs/gatsby/blob/1.0/www/src/pages/docs/node-apis.js and 

https://github.com/gatsbyjs/gatsby/blob/1.0/www/src/components/function-list.js#L108

This loader technique is only used when you need to programmatically create a JavaScript module. If you're transforming data, use Gatsby's layer. If you're transforming data into code, use this loader "trick".

**Comment by KyleAMathews** [comment]
Closing this as it seems our most viable path forward for react in markdown is https://github.com/gatsbyjs/gatsby/issues/312#issuecomment-336681894
