### ISSUE TITLE
Can modules imported into cms.js for netlify-cms be resolved relative to one specified directory?

### ISSUE THREAD

**Issue by vai0** [gatsbyjs/gatsby#11119]
It seems like imports and the imported module's dependencies in the cms.js module must be all be relative. Is there a workaround to allowing absolute imports, something similar along the lines of webpack config's [resolve](https://webpack.js.org/configuration/resolve/)?

The reason I ask is because I'm importing a React component that is resolving it's own imports relative to `src`.

Essentially, it seems like the `cms.js` isn't respecting my modified webpack config which added a `resolve.modules`.

```
// cms.js
import CMS from "netlify-cms";

import StandardLandingPagePreview from "./components/preview-templates/StandardLandingPagePreview";

CMS.registerPreviewTemplate('lp-standard', StandardLandingPagePreview)
```

```
// StandardLandingPagePreview.js
import React from "react";

import BaseLayout from "components/layouts/BaseLayout";
import StandardLandingPage from "components/StandardLandingPage";

export default class StandardLandingPagePreview extends React.Component {
    render() {
        ...
        );
    }
}

```

This will throw error:
```
 ERROR  Failed to compile with 2 errors                                                                                14:06:49

These dependencies were not found:

* components/StandardLandingPage in ./src/components/preview-templates/StandardLandingPagePreview.js
* components/layouts/BaseLayout in ./src/components/preview-templates/StandardLandingPagePreview.js

To install them, you can run: npm install --save components/StandardLandingPage components/layouts/BaseLayout
```
Here is my gatsby-node.js file:
```
// gatsby-node.js
exports.onCreateWebpackConfig = ({ stage, actions, plugins, loaders }) => {
    let config = {
        resolve: {
            modules: [path.resolve(__dirname, "src"), "node_modules"],
        },
        ...
    };

    actions.setWebpackConfig(config);
};
```

**Applicable Versions:**
 - Netlify CMS version: 2.3.3
 - Git provider: Gitlab
 - OS: Mac OS 10.14

**Additional context**
I am running netlify-cms with GatsbyJS via [gatsby-plugin-netlify-cms](https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cms/?=gatsby-plugin-netlify)

**Comment by sidharthachatterjee** [comment]
@vai0 The Netlify CMS plugin runs a separate instance of webpack it does spread the gatsby webpack config  but this is probably being run before your code) so that would explain why your code in `gatsby-node.js` isn't working 

Here is the webpack config for it 
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify-cms/src/gatsby-node.js

Would you like to open a PR with your fix? 🙂

**Comment by vai0** [comment]
@sidharthachatterjee Would love to :)

Before I submit the PR - do you happen to know what the reason is for running a separate instance of webpack rather than relying on gatsby's?

Would you prefer the fix to simply be adding a resolve to the config, or switching `webpack(config).run()` to `actions.setWebpackConfig`?

**Comment by vai0** [comment]
Actually `actions.setWebpackConfig` probably wont work
