### ISSUE TITLE
Hosting Static HTML without path awareness

### ISSUE THREAD

**Issue by singlemind** [gatsbyjs/gatsby#11110]
## Relevant information

We are in the process of building out a new site and moving away from Wordpress. The issue is that in the immediate, we need to be able to just launch a couple of new pages.

We can do this with static HTML by creating empty theme templates in Wordpress, and creating a page pointing at that template. We've chosen that route because we're replacing the home page, but aren't ready to replace all of the pages yet.

In short, when we add the static HTML of the 'Index.html' for the home page to a template, and go to the path for the 'home' page, the page redirects to the path to the file "/wp-content/themes/Avada/smcgatsby/" where 'Avada' is the name of the theme.  We need the static HTML to NOT redirect the page path, and simply render at the path it's set at.

If these means just doing a find/replace on some paths in the index.html, that's fine...we just need to know what/how to do that.

### Environment (if relevant)

Wordpress hosted on Pantheon

**Comment by barrymcgee** [comment]
This seems to be a question about Wordpress and not a question specific to Gatsby?

**Comment by singlemind** [comment]
> This seems to be a question about Wordpress and not a question specific to Gatsby?

No. This is a question about how to place index.html files at an arbitrary path and view them at that path without the URL being redirected.

Wordpress is a red herring. 

I just want the index.html file to RENDER. Not redirect me to point at the file(s) directory location.

**Comment by barrymcgee** [comment]
@singlemind Are you placing the index.html file in a Wordpress codebase or a Gatsby codebase?

Gatsby is a static site generator which uses React, a Javascript library. If you just drop a HTML file into a Gatsby site root, it will not render.

The following link will help you understand how to create a basic index page in Gatsby: https://www.gatsbyjs.org/tutorial/part-one/#familiarizing-with-gatsby-pages

**Comment by singlemind** [comment]
> @singlemind Are you placing the index.html file in a Wordpress codebase or a Gatsby codebase?
> 
> Gatsby is a static site generator which uses React, a Javascript library. If you just drop a HTML file into a Gatsby site root, it will not render.
> 
> The following link will help you understand how to create a basic index page in Gatsby: https://www.gatsbyjs.org/tutorial/part-one/#familiarizing-with-gatsby-pages

I appreciate the fact that you've responded to me and have offered feedback and suggestions.

I don't feel that you understand the nature of the issue.

I'm doing server side routing. I want to manage the routing to pages using standard server side routing. I want to take the static HTML file produced by 'gatsby build' in the public directory, and drop it into directory and have it just render. At that path.

What it does right now, is the route will load as expected, but once the JS loads it redirects the path in the URL to point at the literal file path.

I would vastly prefer that it not do that. Frankly, I'm confused why that would be the behavior.

**Comment by barrymcgee** [comment]
> when we add the static HTML of the 'Index.html' for the home page to a template, and go to the path for the 'home' page, the page redirects to the path to the file "/wp-content/themes/Avada/smcgatsby/" where 'Avada' is the name of the theme.

Leaving the Gatsby generated index file aside for one moment - if you just add `<h1>Hello world</h1>` to that template, does it still redirect?

**Comment by sidharthachatterjee** [comment]
From what I understand, you're seeing this because of 
https://github.com/gatsbyjs/gatsby/blob/a11f79abcfe7f0390dedc5b10c7d0b79848595c2/packages/gatsby/cache-dir/production-app.js#L65

Have you tried setting a path prefix solve this?

On a side note: I understand your use case and would recommend routing to the static assets Gatsby generates on nginx, Apache or whatever as opposed to creating a WordPress theme

**Comment by moonmeister** [comment]
We figure a way around this, thanks ya'll.

**Comment by brianbento** [comment]
@moonmeister I'm running into a similar situation. Can you post what you did? Would be really appreciated!

**Comment by moonmeister** [comment]
@brianbento Hey, my boss(the original poster) mostly figured this one out. I know we're copying the gatsby files in to the root of the WP site and not using any wp "templates" but I think there was also some .htaccess magic done. One of the issues we had with assets was their relative nature. There is a feature in the work for gatsby (that's maybe been merged) to allow assets being hosted on a different domain. This would help resolve this issue as well. If you have more specific questions maybe open your own issue or reach out on Discord.
