### ISSUE TITLE
[1.0] Transliterate all GraphQL names to avoid invalid name errors

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1111]
GraphQL is unlikely to ever allow for names other than `/(a-zA-Z0-9_)/` so we need to work within that.

[This comment](https://github.com/facebook/graphql/issues/256#issuecomment-273301618) suggested using this package https://github.com/andyhu/transliteration

/cc @jquense

**Comment by jquense** [comment]
It seems reasonable to me, but i'm not really familar with whether that's a viable strategy here. My limited experience with transliteration tho would lead me to think it would cause confusion or ambiguity. Depending on the language there really isn't always "one way" to transliterate something so it may be unclear to a consumer what their fields were turned into. It doesn't help with the non semantic characters either unfortunately :/

**Comment by KyleAMathews** [comment]
Ok let's leave this open for now until someone working in a non-english language has trouble and we can work out with them a good solution to this.

Yeah the tradeoff is a) transliterate and risk confusing people on why their field names changed or b) don't transliterate and force people to rename their fields causing potential confusion + possibly not being able to easily use Gatsby if it's not possible or easy to change/transform field names in their data pipeline.
