### ISSUE TITLE
Gatsby data filter on page

### ISSUE THREAD

**Issue by khus29** [gatsbyjs/gatsby#11121]
Hi folks, I am working on a scenario where we are dynamically generating pages at build time depending on data. Per page can have max 10 data so there is limited data query per page. Now there is one more feature required from client, to implement select based filter on page. I am not sure if we can apply filter after pages are generated? Please help.

**Comment by sidharthachatterjee** [comment]
Closing this in the mean time, @khus29 but please feel free to reopen or comment on this if we missed answering your question! Thanks!
