### ISSUE TITLE
[feature]: Avoid duplicating processing effort in sharp

### ISSUE THREAD

**Issue by polarathene** [gatsbyjs/gatsby#11122]
## Summary

If the same source image has been processed by sharp before, it should not need to be processed again.

### Basic example

I have two similar pages using the exact same graphql query and using `gatsby-plugin-sharp` to process the images. During a build, CLI output doubles the number of images to process. Another page with a custom feature that allows requesting a different size for the base64 placeholder thumbnail also processes all the same inputs again for the same outputs that aren't different(only the base64 is).

### Motivation

Is it possible to cache those in some way during the build to skip processing the same input for the same output? Or could that be detected upfront before processing and filtering through what is to be processed to skip/remove image processing tasks that would be redundant?

**Comment by sidharthachatterjee** [comment]
Just dug into the code and found 
https://github.com/gatsbyjs/gatsby/blob/a11f79abcfe7f0390dedc5b10c7d0b79848595c2/packages/gatsby-plugin-sharp/src/index.js#L330

@polarathene Can you please link to a minimal reproduction of this not working?

**Comment by polarathene** [comment]
@sidharthachatterjee Sure, it could be a misunderstanding on my part. In the CLI output, I know that the same queries(or similar in the case of only changing the base64 width) was showing a larger total count of images to process/output with `Generating Thumbnails..`, for about 24 images I recall about 330-ish were being generated, using the same graphql query in another page doubled that, and my other page which adjusts base64 width in the graphql param pushed it over 1000.

Maybe some of the images were being skipped, and the number of images to generate was misleading? I'll take a look and provide a reproduction repo if the images aren't being skipped.

**Comment by polarathene** [comment]
@sidharthachatterjee 

- 24 image folders in static, 108MB, 1,008 files, each folder has 42 images. Images are all using fluid queries with max-width or max-height with JPG and WEBP outputs. Still seems a bit high image count wise.
- 2nd build, remote images are downloaded again. I had additional folders added with 42 images, but some were skipped, this appears to be due to some remote files having failed to download correctly/fully either in 1st or 2nd build and thus being "different" images I imagine. Only 847 were generated this time, possibly due to skipping or some images failing to successfully download(happens sometimes causing null for childImageSharp on a component expecting it).

I removed the two other pages besides index, the single query produced 336 files each image dir of JPG/WEBP outputs was 14 files in size, a third of the 42. So it'd seem the page with the same query + duplicate query that only changes the base64 thumbnail, the caching works fine and only produces 14 images per image like the other two pages... but whatever is going on, it doesn't seem to avoid the duplicate queries(which might be my fault if I'm meant to keep them separate from the page and import from a single source/query definition?)

I can put together a reproduction repo, but afaik it should just be having a duplicate of a page with the same qraphql query on it(as a new graphql query instance). Is it likely something to do with the hash generation, such as tying the page component or graphql query instance to it?

**Comment by polarathene** [comment]
Potential fix: https://github.com/gatsbyjs/gatsby/pull/12129
