### ISSUE TITLE
[www] plugins page on small screen does not show plugin details

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#11127]
On a mobile screen, selecting a plugin on [www.gatsbyjs.org/plugins](https://www.gatsbyjs.org/plugins/) should show the plugin's details, but does nothing.

**Comment by danedavid** [comment]
I'll take this up 👍 
Is any sort of design required? We'll just render the markdown content in mobile too, like we do for desktop, right?

**Comment by sidharthachatterjee** [comment]
cc @fk

**Comment by danedavid** [comment]
Any updates on this?

**Comment by fk** [comment]
Argh, missed this.
I'm so sorry @danedavid (and @sidharthachatterjee)! 🙏 

> Is any sort of design required? We'll just render the markdown content in mobile too, like we do for desktop, right?

This was working already, so no additional design is required.
I don't know what broke — for small screens, we showed just the sidebar for https://www.gatsbyjs.org/plugins/, and selecting a plugin from the list brought up the markdown content.

… Just did a little digging, and also tested on my phone — looks like @amberleyromo already fixed that in #11212.
