### ISSUE TITLE
Replace double slashes at the start of a page's path

### ISSUE THREAD

**Issue by hcavalieri** [gatsbyjs/gatsby#11125]
## Summary

Pages with paths that begin with double (or more) slashes (such as `//design`) get redirected to a non-existing url upon mounting, if loaded straight from the address bar. If they happen to show up through a router link (such as visiting the homepage and clicking on `/design`), then all is fine. Double slashes in the middle of the path don't make a difference, either, although they end-up showing in the address bar.

You can check this behavior live [here](https://5c3faf2fdf9ecb000831572b--henrique-codes.netlify.com/design/react-for-designers) and see the _desired_ behavior [here](https://henrique.codes/design/react-for-designers)

I suggest **running a regex** to remove double slashes at the start of pages' paths, baked into the `createPage` API.

### Basic example

I had a typo in my `gatsby-node.js` when creating paths for articles, which generated the problem:

```js
const path = `/${
      category ? `/${slugifyString(category)}` : ''
    }/${slugifyString(slug)}`;
```

As you can see, I check if there's a category to the post before adding it to the URL, but I was then adding two slashes, rendering paths like `"//design/react-for-designers"`. To fix this, a simple `/\/{2,}/g` regex would do the trick tied to a `path.replace` function. Not sure where this would fit, but I can gladly put a PR forward if you think this is valid ;)

### Motivation

This is a very specific scenario, but **could send a beginner into an hour-long journey** (or more) **of debugging** before they realize what had happened, and this builds tons of frustration. Also, I don't see why we should maintain a double slash - is there any use case for that?

I was lucky enough to open a built `.html` file, run a search for the redirected URL and find the following:

```html
<script id="gatsby-script-loader">
  /*<![CDATA[*/ window.page = {
    componentChunkName:
      "component---src-templates-article-article-template-tsx",
    jsonName: "design-react-for-designers-ee9",
    path: "//design/react-for-designers"
  };
  // ...
</script>
```

By seeing the weird path, I figured that could be causing the error, and _voilà_! Not sure this is trivial troubleshooting, tho.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @hcavalieri 

I _do_ see this is a potentially tricky scenario for a beginner but I'm not sure if we want to add more defensive code around this

Maybe we need to add a quick tip in documentation _encouraging_ a user to use `path.join()` when creating a path out of several parts? 

We could add that in https://www.gatsbyjs.org/docs/actions/#createPage

**Comment by hcavalieri** [comment]
Super sorry for the long wait, @sidharthachatterjee , I honestly forgot about this issue after I archived the notification 😅

I agree with your decision of avoiding extra overhead to defend against this scenario, but I'm unsure `path.join()` is an easy solution for beginners... Maybe a simple annotation on the `createPage`'s example like this could do the trick:

```
createPage({
  path: `/my-sweet-new-page/`,
  component: path.resolve(`./src/templates/my-sweet-new-page.js`),
  // The context is passed as props to the component as well
  // as into the component's GraphQL query.
  context: {
    id: `123456`,
  },
})
```
