### ISSUE TITLE
Demonstrate use of directly importing data (json & yaml) for simple data in tutorial plus recipee

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#11130]
People sometimes think you need to use graphql for everything including simple cases like using data from a json file.

We should emphasize that hard-coded data can be directly imported and that graphql is only necessary when you want db-like functionality e.g. filtering, sorting, pulling bits of data from connected data, and transforming data (images, markdown, dates, etc.).

Add this to the tutorial and recipes page. Perhaps a standalone page too.

@gatsbyjs/docs

**Comment by jonniebigodes** [comment]
@KyleAMathews if you don't mind i can whip up something and have the @gatsbyjs/docs go over it and fine tune the details. Sounds good?

**Comment by krismorf** [comment]
Can this also be a part of a tutorial about the use case of manually creating a search index JSON file in `gatsby-node.js` and then using onClientEntry in `gatsby-browser.js` to load the index to `window`?

**Comment by m-allanson** [comment]
@KyleAMathews do you see this as a case of adding more pointers to existing docs or adding a new docs section somewhere?

We have the following docs on using Gatsby without GraphQL:

- In the _Recipes_ section: https://www.gatsbyjs.org/docs/recipes/#using-gatsby-without-graphql
- In the _Sourcing content and data_ section: https://www.gatsbyjs.org/docs/using-gatsby-without-graphql/
  - Which also links out to this example repo: https://github.com/jlengstorf/gatsby-with-unstructured-data
- In the blog: https://www.gatsbyjs.org/blog/2018-10-25-using-gatsby-without-graphql/

Maybe the only TODO here is to reference some of these docs from within the tutorial?

**Comment by KyleAMathews** [comment]
This is a bit different than those pages. Those pages are about adding data to a page via `pageContext`. We're not telling people that they can also just do `const data = require(`../data/cool-data.json`). Which is sometimes all people want.

I haven't through through though how or where this should go though. Recipes would be a good place. I was thinking the tutorial but I'd have to look through that closely.

/cc @marcysutton

**Comment by jonniebigodes** [comment]
it's being rebased and reworked

**Comment by LekoArts** [comment]
Fixed by #12634
