### ISSUE TITLE
gatsby-plugin-netlify-cms errors when components dependent on gatsby modules are imported in cms.js

### ISSUE THREAD

**Issue by vai0** [gatsbyjs/gatsby#11137]
## Summary
I am attempting to register a preview template in `cms.js` with the component I'm also using in Gatsby. However, gatsby-plugin-netlify-cms throws the error below when Gatsby is built. I've narrowed it down to the reason being that gatsby-plugin-netlify-cms' webpack instance cannot process the Link component from the "gatsby" module.

```js
// cms.js
import CMS from "netlify-cms";

import Test from "components/Test";
```

```js
// Test.js
import React from "react";

import { Link } from "gatsby";

export class Test extends React.Component {
    render() {
        return <div><Link to="/hello">Hello</Link></div>;
    }
}
```

Error
```bash
error  in ./node_modules/gatsby/cache-dir/gatsby-browser-entry.js

Module parse failed: Unexpected token (16:2)
You may need an appropriate loader to handle this file type.
|
| const StaticQuery = props => (
>   <StaticQueryContext.Consumer>
|     {staticQueryData => {
|       if (

 @ ./src/components/Link.js 61:6-22
 @ ./src/components/Test.js
 @ ./src/cms/cms.js
 @ multi ./plugins/gatsby-plugin-netlify-cms/cms.js ./src/cms/cms.js
```

Is there an obvious workaround for this? 

**Gatsby version:** 2.0.90
**gatsby-plugin-netlify-cms version:** 3.0.9

**Comment by sidharthachatterjee** [comment]
Interestingly, I'm not able to reproduce this 

https://github.com/sidharthachatterjee/netlify-cms-test seems to build fine 

I do remember fixing this for Storybook though so could you please try the repository I've linked to and reproduce this issue there?

**Comment by vai0** [comment]
@sidharthachatterjee I was able to reproduce it by adding the following into your test repo's `gatsby-plugin-netlify-cms`'s `gatsby-node.js` webpack config variable:

```
var config = (0, _extends2.default)({}, gatsbyConfig, {
  ...
  resolve: {
    modules: [_path.default.resolve(__dirname, "../../src"), "node_modules"]
  },
  ...
});
```

Error:
```
ERROR  Failed to compile with 1 errors                                                        17:35:33

 error  in ./node_modules/gatsby/cache-dir/gatsby-browser-entry.js

Module parse failed: Unexpected token (16:2)
You may need an appropriate loader to handle this file type.
|
| const StaticQuery = props => (
>   <StaticQueryContext.Consumer>
|     {staticQueryData => {
|       if (

 @ ./src/cms/preview-templates/AboutPagePreview.js 8:0-30 15:29-33
 @ ./src/cms/cms.js
 @ multi ./node_modules/gatsby-plugin-netlify-cms/cms.js ./src/cms/cms.js ./node_modules/gatsby-plugin-netlify-cms/cms-identity.js
```

Your test repo works perfectly without the resolve key in the webpack config - so this is more or less related to the other thread: https://github.com/gatsbyjs/gatsby/issues/11119. 

I'm not exactly sure why it does this - it seems to start resolving things that it shouldn't once resolve is added?

**Comment by kluplau** [comment]
@vai0 Did you happen to fix this yourself? I'm struggling with the exact same issue, because my plugin uses Link (from Gatsby).

**Comment by vai0** [comment]
@kluplau I have a PR going which I'm using currently in my own project, although it isn't passing tests atm. Been a bit busy recently, so feel free to take over that PR :)

https://github.com/gatsbyjs/gatsby/pull/11947

**Comment by wardpeet** [comment]
The latest version of [gatsby-plugin-netlify-cms](https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cms/?=gatsby-plugin-netlify-cms) fixes this one
