### ISSUE TITLE
[www] Plugins feedback button is not working 

### ISSUE THREAD

**Issue by oorestisime** [gatsbyjs/gatsby#11143]
## Description

When i click on the mail icon in the plugins page i get

![screenshot_2019-01-18 gatsby-source-instagram](https://user-images.githubusercontent.com/3874836/51382507-3e9a2d00-1b17-11e9-8c07-8068be65e103.png)

### Expected result
Not sure :D

**Comment by gurpreet-hanjra** [comment]
Hello, in initial investigation it seems like unbird component is not getting the public key here https://github.com/gatsbyjs/gatsby/blob/b8422553a6cc2b0b1195ba1c788eea4727ec13ca/www/src/pages/plugins.js#L71
could someone help in debugging the publickey? @sidharthachatterjee

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @oorestisime and thank you for the help in debugging this @gurpreet-hanjra 

We'll need to check but my best guess is that we will need to prefix this with `GATSBY_`

**Comment by gurpreet-hanjra** [comment]
Thank you @sidharthachatterjee I will submit a PR with adding prefix to the public key. I hope it's fine.

**Comment by sidharthachatterjee** [comment]
@gurpreet-hanjra Just saw your comment now after pushing and opening a PR. 

I'm so sorry! Didn't mean to ignore your comment. Would love to receive more PRs in the future! Thank you again 🙂
