### ISSUE TITLE
[question][gatsby-plugin-offline] Any plans to add support for push notifications in the future?

### ISSUE THREAD

**Issue by rtm619** [gatsbyjs/gatsby#11140]
## Summary

The current offline plugin provides a sw with caching options using workbox's generateSW plugin.
While this is enough, I think that the plugin could be expanded to support push notifications using firebase and APNS (for ios compatibility).

What do you guys think?

**Comment by Robert-H-Leonard** [comment]
Don't want to re-open this issue but I found this blog post that built on top of the gatsby offline plugin: https://www.dshomoye.dev/gatsby-web-push-notifications/
