### ISSUE TITLE
[gatsby-plugin-google-gtag] respectDNT has the wrong documented path

### ISSUE THREAD

**Issue by JacobBlomgren** [gatsbyjs/gatsby#11159]
## Description

The `respectDNT` option is erroneously documented to be provided as `pluginOptions.pluginConfig.respectDNT` when the code in fact only listens to `pluginOptions.respectDNT`, as can clearly be seen [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-gtag/src/gatsby-ssr.js#L47).

### Steps to reproduce

This config will not result in the expected result:
```javascript
{
  resolve: `gatsby-plugin-google-gtag`,
  options: {
    pluginConfig: {
      respectDNT: true,
    }
  },
}
```

But this will:
```javascript
{
  resolve: `gatsby-plugin-google-gtag`,
  options: {
    respectDNT: true,
  },
},
```

### Actual result

The plugin doesn't respect DNT as it should.

**Comment by JacobBlomgren** [comment]
> On second thought, I think keeping it in `pluginConfig` and updating the code is a better idea

Yes, I thought so too! But will that be a breaking change then? Even though it's not documented, that's how it has worked for the existence of this plugin.

**Comment by sidharthachatterjee** [comment]
> But will that be a breaking change then? Even though it's not documented, that's how it has worked for the existence of this plugin.

It will! I think we ought to just update docs for now and maybe clean this up in a future breaking release 

@JacobBlomgren What do you think?

**Comment by JacobBlomgren** [comment]
@sidharthachatterjee Since it actually makes the most sense in `pluginConfig`, maybe the code can be updated, while still allowing it to be defined in root for now (with a printed deprecation warning)?

**Comment by sidharthachatterjee** [comment]
@JacobBlomgren That's a better idea! 

Would you like to take a stab at this? 🙂

**Comment by JacobBlomgren** [comment]
@sidharthachatterjee Gladly 😊
