### ISSUE TITLE
Source and target nodes of a mapping relationship don't update under develop/build

### ISSUE THREAD

**Issue by pauleveritt** [gatsbyjs/gatsby#11151]
## Summary

When doing relationships with a `mapping` in `gatsby-config.js` as described in the docs, nodes don't update, either in `develop` or `build`. You have to remove the develop/build caches.

As commented below by @pieh this is related to a reported bug where a dependency should be added.

## Relevant information

[Reproducible repo, writeup, and video illustrating the problem](https://github.com/pauleveritt/sourceNodes-bug-11151)

This is in relation to [the docs](https://www.gatsbyjs.org/docs/create-source-plugin/#foreign-key-relationships) regarding forward and backwards references.

Imagine you have a system with `Post` entries in markdown. Each has one `Author` and zero or more `Topic` references. Those references are also in markdown, as they are pages in the site. When you render a post, you want to also show information about the author (name, headshot) and topics, plus links to each. When rendering the author or a topic, you want to link back to any matching posts.

Following the docs, it all works well with using `sourceNodes` to add a `field` with the `id` of each reference (in either direction), then using `mapping` to inject a node for that `id`.

However, when content authors use `gatsby develop` and start adding content once it has started, `sourceNodes` isn't run as changes happen on the filesystem. Even worse, in some cases, you have to `rm -rf .cache/*` to get all the targets updated.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @pauleveritt 

> sourceNodes isn't run as changes happen on the filesystem

Can you please link to a simplified reproduction of this if possible?

**Comment by pauleveritt** [comment]
I made the [smallest possible example](https://github.com/pauleveritt/sourceNodes-bug-11151) with a README that says what I did, how to reproduce the two problems, and further diagnosis.

I didn't yet illustrate the full `sourceNodes` issue which I'm facing because:

- It isn't clear to me if `mapping` is favored now over the documented way to do forwards/reverse relationships by maintaining a custom field with the id values

- I was surprised to see that `mapping` could handle reverse relationships, albeit only 1:1, not 1:N.

If you'd prefer, I could change this to the `sourceNodes` but it obviously will fail. `sourceNodes` never runs after startup, so it can't be used to maintain relationships. Plus, I think some kinds of changes require `rm -rf .cache/*` before the author can see their changes.

**Comment by pauleveritt** [comment]
Whether using `mapping` or `sourceNodes`, authors need to either make small changes to all content or blow away their caches, either under `gatsby build` or `gatsby develop`.

Here's a [2m15s video narrating the issue in play](https://www.youtube.com/watch?v=bP_yur3I5Po).

Conclusion: Don't do relationships as described in the docs. Instead of lifecycle APIs, manually recreate the universe inside each pageQuery.

**Comment by KyleAMathews** [comment]
A few points.

Gatsby doesn't watch the file system. Plugins that wish to do this must do it themselves e.g. like gatsby-source-filesystem does.

Most people arrange their content on the fs so mappings between data can be done there.

**Comment by pauleveritt** [comment]
@KyleAMathews Thanks for the fast response. On the second point "Most people arrange their content on the fs so mappings between data can be done there" I think I'm following the example from the docs correctly.

**Comment by pauleveritt** [comment]
Thanks Kyle for the response. Feel free to say "You're painting outside the lines." I'm halfway to moving everything back to page queries, so I'm ok with closing this ticket. Though I'd really like to create and share a plugin with a rich relationship and content type system.

I'm able to get most of that in a plugin now but it is tied to sourceNodes, which doesn't fire after startup. I could switch to createNode which fires on changes, but was advised by @gatsbyjs on Twitter not to use it to update other nodes (the other side of the relationships.)

Should I use `createNode` to maintain some mapping of all relationships, way up the node hierarchy, that's available in all queries?

If so, next question is reloading the browser. I'm looking a post that points to an author. I change info on the author. How do I rebuild the post? (This is true for `gatsby build` as well, which needs to know how to rebuild the other end of a relationship.)

**Comment by KyleAMathews** [comment]
Have you seen `createNodeField`? You can use that to create relationships between nodes https://www.gatsbyjs.org/docs/node-creation/#foreign-key-reference-___node

Another method is "mapping" https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types

**Comment by pauleveritt** [comment]
@KyleAMathews The sample repo uses `mapping`. It sort of works...reverse relationships don't work for 1:N. But the bigger problem: if you change data on one end, you have to blow away the cache to get the other end to use it.

My existing application uses `createNodeField`. But since that's called in `sourceNodes`, it doesn't update after startup (and also suffers from "blow away the cache".)

I probably have to take your advice and go much lower: (a) write my own source plugin that watches all file changes, (b) manage the mapping myself, and (c) learn how to find-then-rebuild source/target nodes on changes.

For now, I'm moving everything out of lifecycle APIs and having every page re-assemble all the authors/topics/categories, then filter out in JS which ones match that post's metadata.

**Comment by KyleAMathews** [comment]
When exactly do you have to clear away the cache? The mapping happens when running queries so there shouldn't be anything cached.

`createNodeField` should generally be used in `onCreateNode` — then it'll get called again whenever data changes.

**Comment by pauleveritt** [comment]
I think I'll take the advice from @KyleAMathews and implement my own source plugin which watches for frontmatter changes, finds each end of each relationship, and calls utils/source-nodes.sourceNodes, similar to how the the /__refresh API works: https://github.com/gatsbyjs/gatsby/blob/45a8f09554b20a02f9c83e57272b7fb1721500b7/packages/gatsby/src/commands/develop.js#L129

It means learning Chokidar, which I'm not looking forward to.

In the meantime, please put a warning at https://www.gatsbyjs.org/docs/create-source-plugin/#foreign-key-relationships saying "This will likely require clearing the cache when one end changes." I demonstrated that in the video, so I don't think that's a question.

**Comment by pieh** [comment]
> All good and `Author.jsx` can have a page query which gets the `frontmatter.title` off the Author node and display it. But if the Author's`frontmatter.title` changes, the Post doesn't reflect the change. Ever. You have to edit every Post to get the Author's new title. Or, clear the cache.

This is a bug in gatsby. We don't add dependency here - https://github.com/gatsbyjs/gatsby/blob/94a80b798d50f03f60e560946cec57ff9e1bc3d4/packages/gatsby/src/schema/infer-graphql-type.js#L179

**Comment by pauleveritt** [comment]
@pieh Thanks for the pointer. Should I change this ticket to be specific to dependencies and mappings? Then perhaps make a new ticket about reverse relationships not doing 1:N?

**Comment by pieh** [comment]
Yeah, we would need separate issues for:
 - dependency thing (which cause queries not to rerun on author frontmatter changes) 
 - back references from mapped fields
Really up to you how you want to split this issue

**Comment by pauleveritt** [comment]
@pieh Thanks, I narrowed this ticket and made a new one for the reverse 1:N.

**Comment by pauleveritt** [comment]
Still an open issue.

**Comment by pauleveritt** [comment]
@pieh How do I prevent the bot from trying to close this? I commented 11 days ago. I don't have permission to put the "not stale" label nor re-open.

I put a lot of work into this ticket.

**Comment by DSchau** [comment]
@pauleveritt I've done it for you. Thanks for making us aware!

**Comment by pauleveritt** [comment]
@DSchau I realize this ticket is architecturally significant and is likely low on priority (though hopefully the bug @pieh mentions gets worked on.)

In the meantime, I highly suggest you un-document (or at least add a warning) the mapping feature.

**Comment by pauleveritt** [comment]
Would the new `@link` resolver extension in the schema customizations stuff also suffer from what @pieh mentioned in February? ("We do need to wrap that resolver in pageDependencyResolver helper")

I'm having trouble putting Gatsby in the hands of authors, as they have to blow the cache quite frequently.

**Comment by wardpeet** [comment]
I think the cache issue still persist even with @link extension.

@freiksenet or @pieh might know more

**Comment by freiksenet** [comment]
@pauleveritt This might have been fixed in latest gatsby, because mapping now use `@link` too. Could you check if latest Gatsby solved this for you?

**Comment by freiksenet** [comment]
Otherwise, `@link` definitely tracks dependencies.

**Comment by pauleveritt** [comment]
Yep, it works, thanks @freiksenet for checking back. Closing.

I was surprised, even delete works.
