### ISSUE TITLE
Babel errors shouldn't let the site run

### ISSUE THREAD

**Issue by gaearon** [gatsbyjs/gatsby#11165]
I'm in a hurry, feel free to close if I'm not following the template.

I have some Babel errors:

<img width="727" alt="screen shot 2019-01-19 at 9 48 26 pm" src="https://user-images.githubusercontent.com/810438/51432715-1a803e00-1c34-11e9-8ad5-100edf7ad734.png">

But the site still loads in DEV. I guess it just serves the previous version.

This is very wrong and can lead to nightmare-ish debugging sessions. If there is a Babel error, refresh should show that error immediately. Not serve the previous version.

**Comment by sidharthachatterjee** [comment]
Thank you for reporting this @gaearon 

Posting reproduction steps here for future reference
- Clone https://github.com/sidharthachatterjee/gatsby-babel-test
- gatsby develop
- Uncomment line 33 in src/components/image.js
- Develop logs Babel error and error component is rendered in browser
- Hit refresh 

Error component is not rendered and previous build is served instead

**Comment by gagandeepp** [comment]
@sidharthachatterjee can i look into this?

**Comment by sidharthachatterjee** [comment]
@gagandeepp Sure! Please comment if you need any help 🙂

**Comment by theajr** [comment]
@sidharthachatterjee  @LekoArts 

So far, I found that we are not enforcing webpack rules on js/jsx file. 
We can do that in `packages/gatsby-plugin-preact/src/gatsby-node.js` file by adding below rule under `module.rules`
```javascript
{
  test: /\.jsx?$/,
  enforce: "pre",
  loader: "babel-loader"
}
```

Or is there any other generic place to add such enforcing rules? Please let me know your thoughts.

I would like to work on this. Can you please assign it me?

**Comment by krvajal** [comment]
@theajr are you still working on this, otherwise I would like to give it a try to make a fix. I am having this issue and it is quite annoying.

**Comment by bilogic** [comment]
> adding below rule under `module.rules`
> 
> ```js
> {
>   test: /\.jsx?$/,
>   enforce: "pre",
>   loader: "babel-loader"
> }
> ```

@theajr what about react? I tried the above in my project's ```gatsby-node.js``` and it doesn't make any difference, the previous version continues to load.

**Comment by LekoArts** [comment]
This is still up for grabs if someone wants to contribute to Gatsby.

**Comment by blainekasten** [comment]
I just tested this. If a babel syntax error happens, we show the error on the screen immediately. We are not rendering the previous version of the page. I'm going to close this because I believe the original issue is fixed.
