### ISSUE TITLE
`deletePage` action is unexpectedly asynchronous 

### ISSUE THREAD

**Issue by ChristopherBiscardi** [gatsbyjs/gatsby#11173]
## Description

The issue seems to be that calling `deletePage` in two different `onCreatePage` hooks is unexpectedly asynchronous, causing the [DELETE_NODE reducer](https://github.com/gatsbyjs/gatsby/blob/fc2ff3503ac1ed32a4b7677b12edf4c4ea4fd050/packages/gatsby/src/redux/reducers/nodes.js#L16) to receive 

```js
{ type: 'DELETE_NODE', plugin: undefined, payload: undefined }
```

This causes

![image](https://user-images.githubusercontent.com/551247/51437023-b5851200-1c4c-11e9-8434-8f263d228478.png)

### Steps to reproduce

Here's a full description with a repro repo: https://github.com/ChristopherBiscardi/gatsby-mdx/issues/159

I could probably get this example even smaller if it needs to be, but [gatsby-mdx's onCreatePage](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/b1657ae41bd04db4beea814a09cfb0cf23c1b774/packages/gatsby-mdx/gatsby/on-create-page.js) uses `deletePage` and so does the user's own `gatsby-node.js`.

### Expected result

* Async code should not overflow into createPagesStatefully lifecycle
* Using `deletePage` should not cause other hooks to fail

### Actual result

```
TypeError: Can not read property 'id' of undefined
```

---

##### More info

It seems like changing 

```js
emitter.on(`DELETE_PAGE`, action => {
  const nodeId = createPageId(action.payload.path)
  const node = getNode(nodeId)
  boundActionCreators.deleteNode({ node })
})
```

to use await

```js
emitter.on(`DELETE_PAGE`, async action => {
  const nodeId = await createPageId(action.payload.path)
  const node = await getNode(nodeId)
  boundActionCreators.deleteNode({ node })
})
```

fixes this issue [in the data bridge's gatsby-node](https://github.com/gatsbyjs/gatsby/blob/fc2ff3503ac1ed32a4b7677b12edf4c4ea4fd050/packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js#L154-L159). I don't know why as I'm not familiar enough with the internal data bridge.

**Comment by sidharthachatterjee** [comment]
cc @pieh

**Comment by lannonbr** [comment]
Any updates on this?

**Comment by pieh** [comment]
One thing to note is that all our node APIs are `async` https://github.com/gatsbyjs/gatsby/blob/2032147f23d40fe8d986fd33996a8c5362e6c75d/packages/gatsby/src/utils/api-runner-node.js#L232-L244

Let's see what the flow would be if we have 2 `onCreatePage` hooks that delete pages - let's call them `onCreatePageA` and `onCreatePageB`:

 - createPage(X) (either from 'src/pages' automatic or programmatic createPage in gatsby-node - it shouldn't matter)
 - `onCreatePageA` for X is called which:
   - calls `deletePage` triggering data bridge's `DELETE_PAGE` handler and deleting the node
   - calls `createPage(Y)` with change path field
 - `onCreatePageB` for X is called (this was scheduled before `onCreatePageA` was executed) and we are deleting same page object:
   - we call `deletePage` again, but node was already deleted

So maybe what we would need to do is make sanity checks - either in `deletePage` action to make it no-op if page was already deleted (and thus skipping internal data bridge handling) or in internal data bridge add sanity check to see if `node` exist before we call `deleteNode`?

**Comment by pieh** [comment]
I've been thinking more on this and maybe better way of fixing this than trying to add sanity checks is to stop calling queued `onCreatePage` API calls once if/when of those did delete the page - this would require more work, but it feels to me like it's better solution (because once we delete page, next `onCreatePage` calls for that page are really a "lie")

**Comment by KyleAMathews** [comment]
Yeah I like that. There's no guarantee you'll get to see every page that's created. So if it disappears, stop making calls. We could do the same thing for onCreateNode.

**Comment by pieh** [comment]
`gatsby@2.1.12` was published with fix

**Comment by secondary-school55** [comment]
Still have issue (gatsby@2.1.22) when using gatsby-mdx:

**Plugin gatsby-mdx returned an error
TypeError: Cannot read property id of undefined**

I use deletePage and createPage to pass context for page.

**Comment by YordanLV** [comment]
Same issue here.. Anyone with a fix?

**Comment by pgooch** [comment]
I ran across this recently and while I know it old I found a work-around that might help others in the future. When I did was rename the file, `products.js` in the pages directory to `products.nopage.js` then used the following in `gatsbyh-node.esm.js` to automatically remove those pages.

```
// Add a file to the pages directory and have not* create a page by using this one weird trick.
// The trick is to rename it *.nopage.js, and this will delete it for you.
exports.onCreatePage = async ({ page, actions: { createPage, deletePage } }) => {
    if (page.path.match(/\.nopage\/$/g)) {
        deletePage(page)
    }
}
```
