### ISSUE TITLE
Gatsby crashes on Chrome v 43.0.2357.81

### ISSUE THREAD

**Issue by magnusarinell** [gatsbyjs/gatsby#11176]
## Description

When browsing with Chrome v 43.0.2357.81, site crashes with error:
Uncaught TypeError: Cannot read property 'split' of undefined.

### Steps to reproduce

Visit https://reactjs.org/docs/hello-world.html with Chrome  v 43.0.2357.81.

### Expected result

Site should render.

### Actual result

Site crashes on hydration.

**Comment by koreyboone** [comment]
Why are you using chrome 43? I doubt that old of a version of chrome is compatible

**Comment by DanielRuf** [comment]
Please provide the line which throws the split error.
So far this issue is not a bug in Gatsby but a missing polyfill for your Chrome version.

Please check the browserslist config.
