### ISSUE TITLE
Issues loading wordpress featured images

### ISSUE THREAD

**Issue by VilleKoivukangas** [gatsbyjs/gatsby#11175]
## Description

Loading wordpress posts seems to work randomly. Posts get loaded always as expected but there is problems to get featured images with them. Wordpress version that i am working with is **5.0.3**

### Steps to reproduce

1. Set up wordpress site and make couple posts and add featured images to them
2. Clone gatsby project "git clone https://github.com/VilleKoivukangas/wordpress-blog-gatsby.git"
3. Edit gatsby-config.js to match with your wordpress installation
3. Run "gatsby develop"

### Expected result

Should load wordpress featured images while using gatsby-source-wordpress

### Actual result

Sometimes loading works as expected and some times i have to delete images from wordpress and set them again. Some times it's enough to edit images name. It's hard to tell what really happens there because as i said sometimes these steps will "fix" the issue and sometimes i just rebuild and edit images until it works again and some times it works fine but eventually it will break again.

**Comment by jonniebigodes** [comment]
@VilleKoivukangas this looks similar to this #10828 issue. i have a wordpress local wordpress installation running on wsl, and a post created to match what is now both behaviours. i'm going to do some testing and see if i can come up with a solution. Sounds good?

**Comment by jonniebigodes** [comment]
@VilleKoivukangas sorry for the late response, but i ran into some issues while addressing the other issue i mentioned in my previous comment.
Going to break my comment in parts for a better understanding:
- Like i mentioned before, i have a wordpress running on wsl. With that i created some more posts in there, some with featured images and others without, imported over 100 images into there from a old wallpapers folder i had laying around, just to test both issues.
- Created a new Gatsby website with the default template and added the gatsby-source-wordpress plugin. 
- Changed my `gatsby-config.js` for the following:
```javascript
module.exports = {
  ......
    {
      resolve:`gatsby-source-wordpress`,
      options:{
        baseUrl: `localhost/wordpress/`,
        hostingWPCOM: false,
        protocol:`http`,
        useACF:false,
        auth:{},
        verboseOutput: false,
        includedRoutes: [
          "/*/*/posts",
          "/*/*/media",
        ],
      }
    },
    ......
}
```
- Moved into modifying the `gatsby-node.js` to the following:
```javascript
const path= require('path')
const { createFilePath } = require('gatsby-source-filesystem')

exports.createPages=({actions,graphql})=>{
    const {createPage}= actions
    return graphql(`
        {
            allWordpressPost(sort:{fields:[date], order:DESC}) {
                edges {
                    node {
                        id
                        date( formatString: "/YYYY/MM/DD/" )
                        featured_media {
                            localFile{
                                childImageSharp {
                                    id
                                } 
                            }
                        }
                        slug
                    }
                }
            }
        }
    `).then(result=>{
        if (result.errors){
            result.errors.forEach(e => console.error(e.toString()))
            return Promise.reject(result.errors)
        }
        const AllPostsTemplate= path.resolve('./src/templates/AllPosts.js')
        const postTemplate = path.resolve(`./src/templates/post.js`)
        createPage({
            path:'/blog',
            component:AllPostsTemplate,
            context:{
                allData:result.data.allWordpressPost.edges
            }
        })
        
        const allPosts = result.data.allWordpressPost.edges

        allPosts.forEach(element=>{
            createPage({
                path:`/blog/${element.node.slug}`,
                component:postTemplate,
                context:{
                    id:element.node.id
                }
            })
        })
    })
}

 exports.onCreateNode = ({ node, actions, getNode }) => {
    const { createNodeField } = actions
  
    if (node.internal.type === `MarkdownRemark`) {
      const value = createFilePath({ node, getNode })
      createNodeField({
        name: `slug`,
        node,
        value,
      })
    }
  }
```
- Created two template files, one for a listing of the posts, other for the post itself:
  - `AllPosts.js` file to list the posts has the following content:
```javascript
....
const AllPosts =props=>{
    const {pageContext} = props
    const {allData}= pageContext

    return (
        <Layout>
            {
                allData.map(item=>{
                    return(
                        <div key={`container_${item.node.slug}`}>
                            <Link to={`/blog/${item.node.slug}`}>Go to {item.node.slug}</Link>
                        </div>
                    )
                })
            }
        </Layout>
        
    )
}
export default AllPosts
```
- `post.js` responsible for showing the actual content for single post:
```javascript
....
const BlogPost = ({ data }) => {
  const {wordpressPost}= data
  return (
    <div>
      <div>
        <h1>{wordpressPost.title}</h1>
      </div>
      <div>
        
        {
          wordpressPost.featured_media===null?<h1>No featured media</h1>:<Img fluid={wordpressPost.featured_media.localFile.childImageSharp.fluid}/>
        }
        Content:
        <br/>
        <div>
          <div dangerouslySetInnerHTML={{ __html: wordpressPost.content }} />
        </div>
        <div>
          <Link to="/blog">Go back</Link>
        </div>
      </div>
    </div>
  )
}
export default BlogPost

export const pageQuery = graphql`
  query BlogPostByID($id: String!) {
    wordpressPost(id: { eq: $id }) {
      id
      title
      slug
      content
      date(formatString: "/YYYY/MM/DD/")
      featured_media {
        localFile {
          childImageSharp {
            fluid(maxWidth: 5000) {
              ...GatsbyImageSharpFluid_withWebp
            }
          }
        }
      }
    }
  }
`
```
- Issuing `gatsby build && gatsby serve` shows me the following: 
  - Importing the content:
    ![ville_pippo_build_info](https://user-images.githubusercontent.com/22988955/52000228-7b213d80-24b4-11e9-856d-1c77ff3ffd26.png)

  - Browser in incognito mode showing the list of posts:
     ![ville_pippo_list_posts](https://user-images.githubusercontent.com/22988955/52000298-a6a42800-24b4-11e9-9b86-895502b8b3be.png)

  - A post without a featured image looks like so:
    ![ville_no_featured_post](https://user-images.githubusercontent.com/22988955/52000348-cb989b00-24b4-11e9-8777-a788b0ae97d4.png)

  - A featured image
     ![ville_featured_media](https://user-images.githubusercontent.com/22988955/52000567-642f1b00-24b5-11e9-9855-f22ecc1c0924.png)
  - Post with featured image
     ![villle_featured_media_with_content](https://user-images.githubusercontent.com/22988955/52000614-7f018f80-24b5-11e9-88ac-7427bc6a8a0e.png)


As you can see for this really long post, it's showing the content with a featured image coming from wordpress. The whole code is [here](https://github.com/jonniebigodes/gatsy_wp_featured_image). In the meantime i'm going to clone your repository and adjust it to get my content and see this issue is resolved

**Comment by marcphilippebeaujean-abertay** [comment]
Sorry to reopen this again, but for me, I cannot seem to find the featured_media option for my wordpress posts. I added it to the wordpress theme in PHP and it shows up in my admin, however I cannot seem to query it in GraphQL - anyone able to identify the problem?
