### ISSUE TITLE
How to construct createSchema for .js file (gatsby-source-graphql)

### ISSUE THREAD

**Issue by carendivinagracia22** [gatsbyjs/gatsby#11189]
## Summary

 I have with me my gatsby-config.js for gatsby-source-graphql:

![image](https://user-images.githubusercontent.com/28243205/51461332-c2168100-1d98-11e9-95e5-ced250ff5336.png)

And a `resolver.js` which contains a schema:

![image](https://user-images.githubusercontent.com/28243205/51461387-e4a89a00-1d98-11e9-9a89-59e5ed7c93e9.png)

And I just don't know on how to import this `resolver.js` into my `createSchema`.  Thanks for the help. 
I'm really new to gatsby.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
Hey @carendivinagracia22 

You don't necessarily _need_ to construct schema and pass into createSchema

If the GraphQL endpoint you'd like to consume is already live on a url, you could just set its url (like you have in the screenshot) and the schema will be introspected from the url

> When createSchema callback is used, schema isn’t cached. 

In case the above is your use case and why you'd like to pass in a constructed schema to the plugin, you need to read the schema definition file and pass it in like the example in https://www.gatsbyjs.org/packages/gatsby-source-graphql/

The resolvers are separate from the schema definition and the schema is likely not in resolver.js

**Comment by sidharthachatterjee** [comment]
That's alright @carendivinagracia22 

From what I understand, you can import the schema. The resolvers don't need to be imported since they are presumably running on an instance somewhere (which is the url that you set)
