### ISSUE TITLE
CSS overriding

### ISSUE THREAD

**Issue by helmerdavila** [gatsbyjs/gatsby#11181]
## Description

SCSS modules got loaded before global styles. Breaking my customized CSS modules 

### Steps to reproduce

1. Using gatsby SCSS
2. Installed a CSS framework (Bulma)
3. Added bulma import into SCSS in `gatsby-browser.js`
4. Created a component `mycomponent.jsx` add connect it with a SCSS module `mycomponent.module.scss`. Added my own CSS, worked as expected on develop. i.e, overriding bulma `.footer` background color.
5. Created a build using `gatsby build`. Then I saw in the code the CSS module code is on the top of the styles. Then, bulma CSS.

### Expected result

First, build global styles, then my own CSS / SCSS modules code

### Actual result

`gatsby build` is moving the global CSS code to the bottom of all styles, causing my override CSS doesn't work

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.76 => 2.0.76 
    gatsby-image: ^2.0.20 => 2.0.25 
    gatsby-plugin-google-analytics: ^2.0.9 => 2.0.9 
    gatsby-plugin-google-fonts: ^0.0.4 => 0.0.4 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12 
    gatsby-plugin-offline: ^2.0.16 => 2.0.20 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5 
    gatsby-plugin-sass: ^2.0.7 => 2.0.7 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.17 
    gatsby-source-filesystem: ^2.0.8 => 2.0.12 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.10 
```

**Comment by sidharthachatterjee** [comment]
@helmerdavila Consider using https://www.gatsbyjs.org/packages/gatsby-plugin-sass/ and importing the scss file in one of your top level components?

Adding it in `gatsby-browser.js` will always result it in being added in last because it is only added in the client side and not during the build

**Comment by helmerdavila** [comment]
> @helmerdavila Consider using https://www.gatsbyjs.org/packages/gatsby-plugin-sass/ and importing the scss file in one of your top level components?
> 
> Adding it in `gatsby-browser.js` will always result it in being added in last because it is only added in the client side and not during the build

I tried adding my scss in layout file and it doesn't work. Bulma still overriding my modules SCSS

**Comment by sidharthachatterjee** [comment]
@helmerdavila Where are you importing Bulma?

**Comment by helmerdavila** [comment]
Right now in my `gatsby-browser.js` file, I did it on layout.js default file but Bulma styles were overriding too my custom styles (in development I never tested creating a build version). So, adding to `gatsby-browser` solves development styling but not for `build` command

**Comment by helmerdavila** [comment]
not stale.

**Comment by FlaviooLima** [comment]
@helmerdavila  The @sidharthachatterjee comment make it worked on my project.
Maybe some update fixes it or there is another issue with your code?

**Comment by helmerdavila** [comment]
![lol](https://dsc.cloud/helmer/Screen-Shot-2019-03-05-at-7.02.04-PM.png)

I've tried moving SCSS file (no module) at the top of my layout.js file. Which is my top-level component

I have the same issue.

**Comment by helmerdavila** [comment]
<img width="100%" alt="screen shot 2019-03-05 at 7 06 44 pm" src="https://user-images.githubusercontent.com/11061182/53846151-df369600-3f79-11e9-9af8-7cb9fbc00ef1.png">
And this is my code in the module

**Comment by DSchau** [comment]
@helmerdavila thanks!

Could you provide a [reproduction](https://gatsby.dev/reproduction) so we can take a look at this?

Generally - these issues are a little hard to track down without some real code to look at!

**Comment by helmerdavila** [comment]
Hey @DSchau, my online portfolio could work as demo case? This is the project where I have the issue. Right now I need to use !important. Please check it out the following link: [https://github.com/helmerdavila/portfolio-v3](PORTFOLIO)

**Comment by arjyobala** [comment]
I was having issues with inconsistent styling when using React Bootstrap with Gatsby between develop and build.

1. Navbar Links had reverted to default Bootstrap style and gone out of alignment on every alternate link.
2.  Gatsby's default link underline was persisting.

For the first one, I missed out on adding a nav-item component inside each nav-link. That solved the alignment issues, specifically for Bootstrap.
```
<NavLink>
      <NavItem>
             ......
       </NavItem>
</NavLink>
```
 Maybe you are missing a component that Bulma also requires?

For the underlines and colour, I targeted the element and added `text-decoration : none !important`  . The `!important` tag is a  fix to override default styles from CSS frameworks if it's just a few elements. Using it a lot will create more issues than needed.

 I'd rather use that for now than get crazy over how Gatsby is prioritizing style classes.

**Comment by code-mattclaffey** [comment]
Having a similar issue with our own component library where we would want to extend the class name of the component but the styles that come from our plugin are being applied after the styles that are set. So for example:

```jsx
import React from 'react'
import { Text } from 'some-library'
import styles from './comp.module.scss'
import classNames from 'classnames'

export const Comp = () => <Text className={styles.compText}>My Text</Text>
```

then in my comp I would have

```scss
.compText {
    font-size: 12px;
    font-weight: 400;
    line-height: 1.3;
}
```

and then when I run ONLY gatsby build what happens is I get ...

![Screenshot 2020-08-10 at 12 52 00](https://user-images.githubusercontent.com/10598938/89779924-5295ed00-db08-11ea-9a21-d3e7dbf50f3d.png)

What is happening here is I think gatsby build extracts the styles from the css modules that are local but they are not extracting the css from the package that lives in the node_modules directory which means when your application runs the css modules from the node_modules directory gets pushed in a style tag which then overrides the styles that live in the stylesheet. 

I am using gatsby-plugin-postcss.

**Comment by Alicia489** [comment]
Any update? I'm facing this same issue. The global styles take precedence over module scss styles after page refresh. 
This is happening in Gatsby v4.
