### ISSUE TITLE
gatsby-starter-blog blog-post.js fails hot reload due to graphql query failure

### ISSUE THREAD

**Issue by bjj** [gatsbyjs/gatsby#11183]
## Description

There seems to be a well-known issue that saving markdown files sometimes causes an error on hot reload where this.props.data.markdownRemark is null.  I have seen this attributed to a "race".  I have no idea what the mechanism is.

### Steps to reproduce

Create a project based on gatsby-starter-blog.  Load one of the blog pages in a browser (in my case, firefox).  Make any change to the index.md for that page and save. 
### Expected result

Page should update to reflect index.md changes.

### Actual result

Sometimes (always, in my case, but others report it depends on page length or other factors), this will result in a traceback in the browser because "post is null" (aka this.props.data.markdownRemark).

If you introspect this.props.data, you can see that the siteMetadata part of the query has succeeded.  I assume that the actual node with the matching slug has been destroyed (temporarily?) during this query.

As a side-issue, a large amount of the area of the traceback webpage is clickable, and clicking it launches $EDITOR in the background of the gatsby develop context.  This basically renders the terminal unusable until you can kill off the editor and gatsby develop.

### Workaround

I have added this at the top of BlogPostTemplate:

    if (!post) return (<div>graphql query failed :(</div>)

This avoids the traceback, and another hot-reload event usually happens a fraction of a second later and succeeds (whereas going to the traceback was a dead end).

### Environment

  System:
    OS: Linux 4.4 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
    Shell: 5.1.1 - /bin/zsh
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    npm: 6.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  npmPackages:
    gatsby: ^2.0.76 => 2.0.76
    gatsby-image: ^2.0.22 => 2.0.25
    gatsby-plugin-emotion: ^4.0.1 => 4.0.1
    gatsby-plugin-feed: ^2.0.8 => 2.0.11
    gatsby-plugin-google-analytics: ^2.0.5 => 2.0.8
    gatsby-plugin-manifest: ^2.0.5 => 2.0.12
    gatsby-plugin-offline: ^2.0.5 => 2.0.20
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.5
    gatsby-plugin-sharp: ^2.0.6 => 2.0.16
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.8
    gatsby-remark-images: ^2.0.4 => 2.0.6
    gatsby-remark-prismjs: ^3.0.0 => 3.1.4
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.8
    gatsby-remark-smartypants: ^2.0.5 => 2.0.7
    gatsby-source-filesystem: ^2.0.2 => 2.0.12
    gatsby-transformer-remark: ^2.1.6 => 2.1.17
    gatsby-transformer-sharp: ^2.1.3 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.8

**Comment by sidharthachatterjee** [comment]
@bjj Can you please link to a simplified reproduction of this?

**Comment by bjj** [comment]
You can reproduce it with gatsby-starter-blog

**Comment by jonniebigodes** [comment]
@bjj i've been doing some work with a repository in which the code uses version 1.7.39 of the plugin, the reason behind the use of that particular version being used in that repository is beyond the scope of this issue. What i've noticed is that doing small changes and those far apart in terms of time interval, won't trigger the error. But "hammering" the .md file constantly will lead to it. What i strongly suspect is that behind the scenes when the contents is being transformed and gatsby is coping with the changes will trigger the error. My first approach to this, was writing the post first and checking if everything was alright and if not make the changes, trigger a build and see the results. Also as this is time consuming, i went with a similar approach as you've stated.

**Comment by bjj** [comment]
It may be that the race is easier to hit when things like gatsby-transformer-sharp and gatsby-remark-copy-linked-files are kicking in and making the update take longer.
