### ISSUE TITLE
Should Boolean input filter fields have $in and $nin operators?

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#11197]
Currently, boolean input filter fields [allow querying with `$in` and `$nin`](https://github.com/gatsbyjs/gatsby/blob/d71b3107ba05c92b6cbb70f05092d197c372e5d1/packages/gatsby/src/schema/infer-graphql-input-fields.js#L38). Should we remove those, since it doesn't make much sense to search `in: [true, false]`?

**Comment by KyleAMathews** [comment]
Query all that are true?

**Comment by stefanprobst** [comment]
Do you mean `eq: true`?

**Comment by KyleAMathews** [comment]
eq: true is just for single values. in is for arrays.

**Comment by stefanprobst** [comment]
Hmm, this is what I get:
```
> sift({ $eq: true }, [true, false, true] )
[ true, true ]
> sift({ $eq: true }, [[true], [false], [true]] )
[ [ true ], [ true ] ]
> sift({ $eq: true }, [[true, false], [false, false], [true, false]] )
[ [ true, false ], [ true, false ] ]
```

**Comment by stefanprobst** [comment]
Not that I think this is super important, but for my own sanity: with Sift, is there any difference between these:

|  |  |
|  ---  |  ---  |
|  in: [ true ]  |  eq: true  |
|  in: [ false ]  |  eq: false  |
|  in: [ null ]  |  eq: null  |
|  in: [ true, false ]  |  ne: null  |
|  in: [ true, null ]  |  ne: false  |
|  in: [ false, null ]  |  ne: true  |
|  in: [ true, false, null ]  |  no filter needed  |
