### ISSUE TITLE
Loading chunk failed

### ISSUE THREAD

**Issue by jaredsilver** [gatsbyjs/gatsby#11194]
## Description

In production, we're seeing a small but significant number of errors that `Loading chunk 5 failed`.

### Steps to reproduce

I have yet to figure out how to reproduce this. The application can be found [here](https://marketing-app.new.datacamp.com), chunk 5 can be found [here](https://marketing-app.new.datacamp.com/marketingasset-5-41bb936337cbeeeb432d.js), and the error on Sentry can be found [here](https://sentry.io/share/issue/d31402354d2f410f99cbb07c8ff3a7ff/). Note that these are reverse proxied from a different domain in production. I cannot determine any pattern among the browsers, etc. of the users for whom this error occurred.

### Expected result

This error should not occur.

### Actual result

This error occurs.

### Environment

Hosted on a CDN, served via reverse-proxy.

Local output from `gatsby info`:

```
  System:
    OS: macOS High Sierra 10.13.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.0.0 - ~/.nvm/versions/node/v11.0.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v11.0.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 59.0.2
    Safari: 11.0.3
  npmPackages:
    gatsby: ^2.0.27 => 2.0.27 
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-purgecss: ^2.4.0 => 2.4.0 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-source-apiserver: ^2.0.0 => 2.0.0 
    gatsby-source-filesystem: ^2.0.7 => 2.0.7 
    gatsby-transformer-yaml: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    gatsby-cli: 2.4.7
```

**Comment by sidharthachatterjee** [comment]
This looks tricky to reproduce. Maybe chunk 5 is sometimes inaccessible from S3? Not sure. 

Don't think this is relevant to Gatsby though, keeping this open nonetheless till we learn more about this!

**Comment by jaredsilver** [comment]
Yeah, almost definitely not Gatsby-specific. When I look around on Google, I notice some other similar errors for other frameworks like Next.js. I’ll look into this a bit more and see if I can find anything useful. In the meantime, if anyone else sees a similar error, it would be great to pool our efforts!

**Comment by sidharthachatterjee** [comment]
Absolutely agree! Thanks @jaredsilver

**Comment by jaredsilver** [comment]
One thing to note is that if this were operating under normal conditions, chunk 5 would be lazily loaded. So my guess is that we're simply seeing slow connections resulting in the chunk not loading fast enough.

**Comment by sidharthachatterjee** [comment]
That _could_ be it!

**Comment by jperasmus** [comment]
We've seen similar issues on a non-Gatsby app before when using the `skipWaiting` option for service workers. With `skipWaiting` the new service worker installs and become active straight away, which clears out old asset caches. If the already loaded page references one of these assets that are now deleted, it will error. Afaik, the Gatsby offline plugin uses `skipWaiting` by default.
