### ISSUE TITLE
Task: Investigate ways to reduce size of the NPM package

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#112]
http://glebbahmutov.com/blog/smaller-published-NPM-modules/ has lots of good tips.

**Comment by lpgeiger** [comment]
@KyleAMathews  I'm just getting started. I may be doing something wrong. I've installed gatsby and created a new project, and it took roughly 1.5GB. Is that really possible?

Can you confirm these directory sizes:
gatsby global install:
/usr/local/lib/node_modules/gatsby: 736M
/code/blog: 770M

Possibly related: each new project seems to download the dependencies every time. Shouldn't there be caching?

**Comment by KyleAMathews** [comment]
@lpgeiger I'm seeing ~210mb for Gatsby v1. But possibly it's larger for 0.x if that's what you're on.

>each new project seems to download the dependencies every time. Shouldn't there be caching?

I believe NPM does. You can research their docs for how the client works.
