### ISSUE TITLE
Why use /static when /src/images already available in gatsby-starter-default?

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#11206]
## Summary

I noticed that a couple of starters and projects use a separate /static folder rather than /src/images for their image assets. Some even had both of them together.

I'm confused which one do I go for and what is the difference in the build process between the two. It seems that /src/images is handled by gatsby-source-filesystem and gatsby-sharp plugins while /static images are directly imported. 

About my case, as image assets I have pictures as pngs/jpgs, illustrations as svg, couple social media icons as svg, favicons, logos. Any docs or insights into this would be appreciated.

**Comment by ajayns** [comment]
Thank you so much for your quick response! Much appreciated.

I was aware about the processing part but didn't know that the `static` directory is directly copied into `public`, is this there in the docs somewhere cause I feel it definitely should be mentioned. 

I am using gatsby-sharp-plugin and yes it works great for png and jpegs but does it help for SVGs? Out of the box does Gatsby do any optimisations to reduce SVG size? Else should I just put those in the static folder?

**Comment by sidharthachatterjee** [comment]
Here are the docs for the static folder
https://www.gatsbyjs.org/docs/adding-images-fonts-files/#using-the-static-folder

gatsby-plugin-sharp doesn't do anything with SVGs

You could put them in the static folder or `import` them in your JavaScript like
```
import yourSVG from './logo_large.svg'

const Home = () => <><img src={yourSVG} /></>

```

**Comment by ajayns** [comment]
Makes sense, thank you for sharing the doc and for clearing the doubts.

Closing the issue.
