### ISSUE TITLE
Improving code examples

### ISSUE THREAD

**Issue by chrisanderss0n** [gatsbyjs/gatsby#11200]
## Relevant information

Several times when following the Gatsby documentation I have been tripped up when following the code examples. The same pattern has tripped me up several times where the line highlighting of the code example has not been enough for me to understand the difference between the previous code, and the new code.

I would like to help improve the line highlighting by including an additional highlight _within the line of code_ that was modified.

Here is an example from: https://www.gatsbyjs.org/tutorial/part-seven/#creating-slugs-for-pages

<img width="685" alt="screen shot 2019-01-21 at 7 37 04 pm" src="https://user-images.githubusercontent.com/6155115/51505372-1ed36500-1db4-11e9-98ce-72b82df31311.png">

Looking at the above code sample, it took me a while to figure out where `getNode` was coming from when I looked at the changed sample below

<img width="685" alt="screen shot 2019-01-21 at 7 39 46 pm" src="https://user-images.githubusercontent.com/6155115/51505426-593d0200-1db4-11e9-8a92-b27ac4767a3d.png">

Ideally, for me, the `getNode` parameter would have been highlighted with its own color to help me identify what had changed on that line.

Personally, I think this would make the documentation much easier to follow.

What would be the path for moving this idea forward?

**Comment by chrisanderss0n** [comment]
I would be happy to design and make the changes to the docs as well.

**Comment by marcysutton** [comment]
Hi there @chrisanderss0n! It took me a second to even understand what changed myself, so I agree with you that it would be a helpful change. Could you introduce bolding of text to provide another callout? That might have helped with the `getNode` reference. 

Whatever we end up doing, I want to ensure it has enough contrast to stand out..currently the blue and pink text colors fail color contrast requirements on both the highlighted and regular background colors. Perhaps we could strengthen those colors at the same time? 

Here's a screenshot from the Chrome color picker, which shows when a color's contrast ratio falls below the requirements at that font size (in this case, 4.5:1):

![pink text open in Chrome color picker](https://user-images.githubusercontent.com/1045233/53132445-8f40e380-3524-11e9-90ca-55cfd6700c5b.png)
Note: you can enable this tool in DevTools settings.

We definitely welcome your contributions, so let me know if you have any questions or want to pair on this!

**Comment by chrisanderss0n** [comment]
You got it, I'll take care of it!

**Comment by marcysutton** [comment]
Hey @chrisanderss0n, what's the status of this issue? are you still interested in working on it?

**Comment by chrisanderss0n** [comment]
Yes! I will prioritize this evening and / or this week-end.

**Comment by marcysutton** [comment]
@chrisanderss0n how's it going with this one?

**Comment by rehat101** [comment]
Here's what I propose:

Highlighting the parameter and the actual callout with same color and font weight can help identify the change.

![image](https://user-images.githubusercontent.com/8665427/63952599-7dc13100-ca9d-11e9-8948-a8324a769005.png)

It also passes the color ratio with `4.77`

Let me know what you guys think. If it's ok, Can I open a PR for this issue?

**Comment by marcysutton** [comment]
Hey @nullhook, I just saw this–that would be fantastic. We would love a PR if you're up for it, and if you can pull it off in the month of October you could get credit for Hacktoberfest as well!
