### ISSUE TITLE
Gatsby production build fails on Netlify with "Unknown kernel" error 

### ISSUE THREAD

**Issue by aidandunlop** [gatsbyjs/gatsby#11208]
## Description

Gatsby build fails when deploying to Netlify. I get an `Unknown kernel` error:

![image](https://user-images.githubusercontent.com/30293030/51542460-37df2300-1e53-11e9-9951-d8a1a21a2cfa.png)

Works fine locally when using `gatsby develop` or `gatsby build && gatsby serve`

I'm using the Gatsby default starter.
I've tried update gatsby and netlify, but still seeing the same issue.

### Environment

`gatsby info --clipboard`:
```
  System:
    OS: macOS High Sierra 10.13.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.6.0 - ~/.nvm/versions/node/v10.6.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.6.0/bin/npm
  Languages:
    Python: 3.6.4 - /Users/adu27/.pyenv/shims/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 62.0.3
    Safari: 11.0.3
  npmPackages:
    gatsby: ^2.0.91 => 2.0.91
    gatsby-image: ^2.0.19 => 2.0.19
    gatsby-plugin-eslint: ^2.0.1 => 2.0.1
    gatsby-plugin-manifest: ^2.0.2 => 2.0.2
    gatsby-plugin-netlify-cms: ^3.0.3 => 3.0.3
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: 2.0.1 => 2.0.1
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12
    gatsby-plugin-twitter: ^2.0.6 => 2.0.6
    gatsby-plugin-typography: ^2.2.0 => 2.2.0
    gatsby-source-filesystem: ^2.0.2 => 2.0.2
    gatsby-source-unsplash: ^1.1.0 => 1.1.0
    gatsby-transformer-remark: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by sidharthachatterjee** [comment]
@aidandunlop Could you please link to a reproduction repo?

**Comment by aidandunlop** [comment]
@sidharthachatterjee yeah sure: https://github.com/aidandunlop/aidan_dunlop

**Comment by sidharthachatterjee** [comment]
Updating gatsby-plugin-manifest seems to have fixed this

https://github.com/aidandunlop/aidan_dunlop/pull/10

Successful deploy at https://app.netlify.com/sites/fervent-leavitt-e8226a/deploys/5c4737577a17730007a02ffe

**Comment by aidandunlop** [comment]
Ah perfect, thank you! 👏👏👏

**Comment by sidharthachatterjee** [comment]
You're welcome, @aidandunlop 

Closing this for now but feel free to reopen if you see this again
