### ISSUE TITLE
Pass in components for <Body /> <HeadComponents /> and <PostBodyComponents />

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1121]
@iiroj suggested this to me and I really like it.

That'd make things in `html.js` more "react-y" and more foolproof as it'd make these things opaque data containers as generally they should be.

I think we could leave the existing props `headComponents`, `postBodyComponents`, and `body` for backwards compatability + people might want to manipulate their data before rendering.

**Comment by 0x80** [comment]
I am not sure what you mean by this. Care to explain a little further maybe?

**Comment by KyleAMathews** [comment]
Right now an html.js looks like (greatly simplified)

```
<html>
  <head>
    {this.props.headComponents}
  </head>
  <body>
    <div
       id="___gatsby"
       dangerouslySetInnerHTML={{ __html: this.props.body }}
     />
    {this.props.postBodyComponents}
  </body>
</html>
```

Instead it could be:

```
<html>
  <head>
    <HeadComponents />
  </head>
  <body>
    <PageBody />
    <PostBodyComponents />
  </body>
</html>
```

Much simpler.

**Comment by 0x80** [comment]
I was actually thinking more along the lines of if they're not passed in as props, where do they come from? But I am guessing they would simply be imported and themselves get the content from the store.

It's def much cleaner to look at :)

**Comment by KyleAMathews** [comment]
Oh they would be passed in as props. Sorry for not making that clear.

**Comment by KyleAMathews** [comment]
This got done a long time ago :-)

**Comment by arminnaimi** [comment]
@KyleAMathews I am little puzzled on how I would pass values to `{this.props.headComponents}`.
