### ISSUE TITLE
SVGs not rendering on iOS with "gatsby develop"

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#11219]
## Description

When running gatsby in development mode and exposing it to the local network with `-H 0.0.0.0` and opening a site that has SVGs, the image doesn't appear and if it has alt-text, the alt text appears.

That said, when built and served, the SVG does render on iOS.

### Steps to reproduce

Here's a reproducible build repo: https://github.com/lannonbr/gatsby-svg-bug

As said in the readme there, run `gatsby develop -H 0.0.0.0` and see the bug and then build the site and serve it and see that the image appears on iOS.

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.12.3 - ~/.yarn/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0.2
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.76 => 2.0.76 
    gatsby-image: ^2.0.20 => 2.0.25 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12 
    gatsby-plugin-offline: ^2.0.16 => 2.0.20 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.14 => 2.0.16 
    gatsby-source-filesystem: ^2.0.8 => 2.0.12 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9 
  npmGlobalPackages:
    gatsby-cli: 2.4.6
```

As well, I am testing this on an iPhone and iPad on iOS 12.1.2

**Comment by sidharthachatterjee** [comment]
This is happening because the url for the SVG is set to `http://0.0.0.0/<path>` which won't resolve correctly on any other device on the network. This should happen on any device other than the machine serving `gatsby develop`

![screenshot 2019-01-23 19 04 21](https://user-images.githubusercontent.com/7701981/51610057-c3cf7880-1f41-11e9-8a68-ad26c526652a.png)

**Comment by sidharthachatterjee** [comment]
On build, it seems to set a relative url for this

We should probably set relative urls for `develop` as well

**Comment by lannonbr** [comment]
Ah gotcha. Tested it with using the IP of my machine and that worked. And yeah I think having the relative URL would be nice in development mode.
