### ISSUE TITLE
Valuable Inventory: No content - Adsense

### ISSUE THREAD

**Issue by omrllm** [gatsbyjs/gatsby#11216]
I have written this issue here and not on Stackoverflow, because if this is really happening because there isn't a specific tag or something like that, this is gonna be related to Gatsby in a way.

## I'm getting refused by Google Adsense 
with this given reason: Valuable Inventory: No content.

From what I've read online this could happen if you don't have the text tag inside the compiled html, so for the "Google bots" the website even if with content, it's not considered like that, you could have one article or one thousand article that doesn't really matter.

**Is anyone else having this issue?**

### Steps to reproduce

Project to reproduce the problem: https://github.com/anabcrypto/abcrypto.

I'm using the default blog starter and I didn't change that much.

The script code was inserted inside the html.js file.

### Expected result

Google Adsense should finally work.

### Actual result

Valuable Inventory: No content -> That's what I get from Google Adsense.

### Environment

```
System:
    OS: Linux 4.19 Fedora 29 (Workstation Edition) 29 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
    Shell: 4.4.23 - /bin/bash
  Binaries:
    Node: 11.3.0 - ~/.nvm/versions/node/v11.3.0/bin/node
    Yarn: 1.12.3 - /var/lib/snapd/snap/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v11.3.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Firefox: 64.0.2
  npmPackages:
    gatsby: ^2.0.91 => 2.0.91 
    gatsby-cli: ^2.4.8 => 2.4.8 
    gatsby-image: ^2.0.26 => 2.0.26 
    gatsby-plugin-feed: ^2.0.8 => 2.0.11 
    gatsby-plugin-google-analytics: ^2.0.9 => 2.0.9 
    gatsby-plugin-manifest: ^2.0.13 => 2.0.13 
    gatsby-plugin-offline: ^2.0.21 => 2.0.21 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.17 
    gatsby-plugin-typography: ^2.2.5 => 2.2.5 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.8 
    gatsby-remark-images: ^2.0.4 => 2.0.6 
    gatsby-remark-prismjs: ^3.2.0 => 3.2.0 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.8 
    gatsby-remark-smartypants: ^2.0.5 => 2.0.7 
    gatsby-source-filesystem: ^2.0.16 => 2.0.16 
    gatsby-transformer-remark: ^2.2.0 => 2.2.0 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.10 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
    gatsby: 2.0.85

```

### P.S.

I had the same problem with a website built with Hugo; I don't know if this is relevant, but yeah.

**Comment by omrllm** [comment]
I did that and when I submitted the changes, I still didn't get a response from Google Adsense. 

Now I've got the same **"Valuable Inventory: No content"** message, again.

**Comment by omrllm** [comment]
I got refused again, but I've read on their forum from an "expert" that in order to get approved you should have a website which is at least six months old and with more than 50 articles.

That is not my case, so I can't say that this is related to Gatsby itself.

**Comment by tonystaark** [comment]
@omrllm so did u able to get it work in the end? I am not able to get Google Adsense on my newly created blog. Need help.
