### ISSUE TITLE
[1.0] Suggestion: make plugin generated node names more terse

### ISSUE THREAD

**Issue by 0x80** [gatsbyjs/gatsby#1122]
Plugins create nodes names like `childMarkdownRemark` and `childImageSharp`. 

So the node is named after child + type + plugin. That seems overly verbose to me. I would think `markdownRemark` and `imageSharp` is already clear enough.

Also the type seems unnecessary since the user will already know what remark or sharp does, and the type of content they work with. I get that you want to avoid naming collisions, but then I would suggest picking a clear standardized prefix like `ext`.

So nodes could be named `extRemark` and `extSharp`.

What do you think?

**Comment by KyleAMathews** [comment]
Imagine a scenario where you come into a site that you didn't build — either it's from a starter/theme or someone else built it — and you're trying to understand how it works. If you have no idea what Remark is and there's 50 different plugins, it'd be quite helpful to see `childMarkdownRemark` as a) you know it's a link to another node type and b) that node type is a transformed child that has something to do with Markdown.

That seems really useful to me.

**Comment by 0x80** [comment]
Alright. I see your point 😄

**Comment by KyleAMathews** [comment]
Something that'd be amazing would be to get auto-complete setup for GraphQL queries in popular text editors. That'd help with the verbosity a lot.
