### ISSUE TITLE
Time to interactive really slow (tracking disabled for google)

### ISSUE THREAD

**Issue by ginovski** [gatsbyjs/gatsby#11223]
## Summary
Hello there I'm running one of our pages in PageSpeed Insights and we get a really low score on mobile

## Relevant information

<img width="898" alt="screenshot 2019-01-23 at 13 36 45" src="https://user-images.githubusercontent.com/6017552/51603953-f3678c00-1f13-11e9-9949-2838f2fdf43a.png">

The page is https://enhancv.com/resume-examples/. Can you give me some suggestions on how I can reduce that loading time?

### Environment (if relevant)
npmPackages:
    gatsby: ^2.0.50 => 2.0.55 
    gatsby-image: ^2.0.0-rc.4 => 2.0.20 
    gatsby-image-sitemap: ^1.0.1 => 1.0.1 
    gatsby-link: ^2.0.0-rc.4 => 2.0.6 
    gatsby-plugin-canonical-urls: ^2.0.0-rc.2 => 2.0.7 
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5 
    gatsby-plugin-offline: ^2.0.17 => 2.0.17 
    gatsby-plugin-postcss: ^2.0.0-rc.5 => 2.0.1 
    gatsby-plugin-postcss-sass: ^1.0.0-beta.6 => 1.0.22 
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.2 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-root-import: ^2.0.4 => 2.0.4 
    gatsby-plugin-sass: ^2.0.4 => 2.0.4 
    gatsby-plugin-sharp: ^2.0.0-rc.7 => 2.0.13 
    gatsby-plugin-sitemap: ^2.0.0-rc.2 => 2.0.2 
    gatsby-source-filesystem: ^2.0.1-rc.6 => 2.0.9 
    gatsby-transformer-json: ^2.1.1-rc.6 => 2.1.5 
    gatsby-transformer-sharp: ^2.1.1-rc.3 => 2.1.8

**Comment by dellwatson** [comment]
@ginovski hello, may i know how u solve it ?
