### ISSUE TITLE
gatsby-plugin-catch-links conflicting with Netlify redirects

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#11238]
## Description

This may be somewhat related to https://github.com/gatsbyjs/gatsby/issues/6686 but since this is dealing with a generic redirect, wanted to raise the issue.

We have created redirects within Netlify that go from paths like `/test/` an external site, like `http://www.google.com`. When clicking on them directly from content, it brings up a 404 page; as the page doesn't actually exist. But, when refreshing that page (and not going through the routing system), it correctly redirects where it's supposed to go. What would be the best way to mitigate this issue for (in our case) 301 redirects? We use them for a variety of reasons, and it's tripping us up at the moment for what we should be doing here. 

I'm thinking the catch-links plugin that is causing the issue.

### Steps to reproduce

☝️ 

### Expected result

Gatsby should not catch that link.

### Actual result

Attempts to go to the page; which does not actually exist.

### Environment

```
 System:
    OS: macOS 10.14.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.0.0 - /usr/local/bin/fish
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.12.1 - ~/.yarn/bin/yarn
    npm: 6.5.0 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 63.0.3
    Safari: 12.0.2
  npmPackages:
    gatsby: 2.0.91 => 2.0.91
    gatsby-image: 2.0.26 => 2.0.26
    gatsby-plugin-canonical-urls: 2.0.8 => 2.0.8
    gatsby-plugin-catch-links: 2.0.9 => 2.0.9
    gatsby-plugin-feed: 2.0.11 => 2.0.11
    gatsby-plugin-google-tagmanager: 2.0.7 => 2.0.7
    gatsby-plugin-manifest: 2.0.13 => 2.0.13
    gatsby-plugin-netlify: 2.0.6 => 2.0.6
    gatsby-plugin-netlify-cms: 3.0.9 => 3.0.9
    gatsby-plugin-node-fields: 1.0.0 => 1.0.0
    gatsby-plugin-react-helmet: 3.0.5 => 3.0.5
    gatsby-plugin-sass: 2.0.7 => 2.0.7
    gatsby-plugin-sharp: 2.0.17 => 2.0.17
    gatsby-plugin-sitemap: 2.0.4 => 2.0.4
    gatsby-plugin-twitter: 2.0.8 => 2.0.8
    gatsby-remark-autolink-headers: 2.0.12 => 2.0.12
    gatsby-remark-copy-linked-files: 2.0.8 => 2.0.8
    gatsby-remark-custom-blocks: 2.0.3 => 2.0.3
    gatsby-remark-embed-video: 1.7.0 => 1.7.0
    gatsby-remark-images: 3.0.1 => 3.0.1
    gatsby-remark-prismjs: 3.2.0 => 3.2.0
    gatsby-remark-relative-images-v2: 0.1.5 => 0.1.5
    gatsby-remark-relative-links: 0.0.3 => 0.0.3
    gatsby-remark-responsive-iframe: 2.0.8 => 2.0.8
    gatsby-source-filesystem: 2.0.16 => 2.0.16
    gatsby-transformer-remark: 2.2.0 => 2.2.0
    gatsby-transformer-sharp: 2.1.10 => 2.1.10
    gatsby-transformer-yaml: 2.1.7 => 2.1.7
  npmGlobalPackages:
    gatsby-cli: 2.4.6
```

**Comment by sidharthachatterjee** [comment]
From the documentation at https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/

> Intercepts local links from markdown and other non-react pages and does a client-side pushState to avoid the browser having to refresh the page.
> 
> For instance, in a markdown file with relative links (transformed to a tags by gatsby-transformer-remark), this plugin replaces the default link behaviour with that of gatsby-link’s navigate, preserving the SPA-like page change without reload.

It indeed is `gatsby-plugin-catch-links` catching any relative links as it _ought_ to

You could remove `gatsby-plugin-catch-links` or another simple fix is to set absolute urls for externals!

**Comment by zslabs** [comment]
Ah interesting! I am using https://github.com/zslabs/remark-relative-links (I'm the author) that makes links on the same domain relative so I can use https://github.com/remarkjs/remark-external-links/releases more reliably, so maybe I can create some filters to keep these as their full domain counter-parts. Will give this a shot and check back.

**Comment by zslabs** [comment]
Yep, was just able to mess around with my regex to ignore a few specific patterns.
