### ISSUE TITLE
Filter single custom post type acf

### ISSUE THREAD

**Issue by frivolta** [gatsbyjs/gatsby#11231]
Hello,
I am a gatsby and graphql newbie, I am moving my website from WP to WP/gatsby.
Actually I have a custom post type called 'portfolio' made of acf custom fields.
I managed to query all the post types of 'portfolio' using this query:
`query {
    allWordpressAcfPortfolio {
      edges {
        node {
          id
          acf {
            slug
            project_title
            featured_image {
              id
              source_url
              localFile {
                id
                publicURL
              }
            }
          }
        }
      }
    }
  }
`
I also managed to make single post pages from a template in gatsby-node using:

`graphql(
          {
            allWordpressAcfPortfolio {
              edges {
                node {
                  id
                  acf {
                    slug
                  }
                }
              }
            }
          }
        ).then(result => {
          if (result.errors) {
            console.log(result.errors)
            reject(result.errors)
          }
          const postTemplate = path.resolve("./src/templates/portfolio.js")
          // We want to create a detailed page for each
          // post node. We'll just use the WordPress Slug for the slug.
          // The Post ID is prefixed with 'POST_'
          _.each(result.data.allWordpressAcfPortfolio.edges, edge => {
            createPage({
              path: 'portfolio/${edge.node.acf.slug}/',
              component: slash(postTemplate),
              context: {
                id: edge.node.id,
                slug: edge.node.acf.slug
              },
            })
          })
          resolve()
        })`

Now I am stucked as I don't know how to get single custom post type data inside the template page.
For the blog section I used this query:
`
query currentPostQuery($id: String!) {
    wordpressPost(id: { eq: $id }) {
      title
      content
    }
  }
`
But I am struggling for this custom post, plus I am not finding a similar example online.
What is the best method to achieve my purpose? Do you have any idea... it would help me a lot understanding gatsby and migrating from wp.
Thanks!

**Comment by frivolta** [comment]
Ok sorry, I was using a bad query I solved using this query:
`query portfolioQuery($id: String!) {
    wordpressAcfPortfolio(id: { eq: $id }) {
      id
      acf {
        slug
        project_title
        featured_image {
          id
          source_url
          localFile {
            id
            publicURL
          }
        }
    }
    }
  }`

**Comment by gurpreet-hanjra** [comment]
Hello, since you solved the issue, I hope it's fine to close this issue :) . Please feel free to reopen this, if needed.
