### ISSUE TITLE
want to set up a certain file structure and routing configuration for mdx documents...

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#11247]
I have this file structure fore my content:

<img width="201" alt="screenshot 2019-01-23 15 41 36" src="https://user-images.githubusercontent.com/7884263/51645337-ae018980-1f28-11e9-9ca8-d9194f98eac2.png">

where each article is in it's own folder with it's own assets folders. In this case I only have an images folder, but more will come in the future.

I then want the routing to look like this:

```
www.company.com/articles/article
```

where each articles route is preceded by all the articles and finally the main url.

currently my Gatsby-source-filesystem is set up like so:

```
{
  resolve: `gatsby-source-filesystem`,
  options: {
    name: `content`,
    path: `${__dirname}/src/content`
  },
},
```

and here is my entire Gatsby-node file:

```
const path = require(`path`)
const { createFilePath } = require(`gatsby-source-filesystem`)

exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions
  if (node.internal.type === `Mdx`) {
    const slug = createFilePath({ node, getNode, basePath: `pages` })
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }
}

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions
  
    const result = await graphql(`
      {
        posts: allFile(filter: {relativePath: {glob: "*.mdx"}}, sort: {fields: relativePath, order: DESC}) {
          edges {
            node {
              childMdx {
                fields {
                  slug
                }
              }
            }
          }
        }
      }
    `).then(res => res.data )

    // console.log(result)

    result.posts.edges.forEach(({ node }) => {
      createPage({
        path: node.childMdx.fields.slug,
        component: path.resolve(`./src/templates/article.js`),
        context: {
          slug: node.childMdx.fields.slug,
          // id: node.id
        },
      })
    })
}

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, 'src'), 'node_modules'],
    },
  })
}
```

trying to figure out how to explain this a bit better, but I'm not sure what I'm trying to do to get what I want...

**Comment by sidharthachatterjee** [comment]
Hey @rchrdnsh 

From what I understand, you want deeper paths to be set for each page that you create. 

You're setting path for a page as `node.childMdx.fields.slug`. You can set it here as anything you want. Maybe get the relative path from GraphQL and use that to create a path?

**Comment by rchrdnsh** [comment]
hmmmmm...not sure how to do that @sidharthachatterjee. It seems like maybe mdx does not support relative paths in queries...it has a place for `fileAbsolutePath` but I'm not seeing fileRelativePath in the docs for mdx or in the docs in GraphiQL...

**Comment by lsirivong** [comment]
So you have a file structure you're happy with (folders under `content/`), but you want the URLs in your site to be `domain.com/articles/{slug}`. Is that correct?

What sidharthachatterjee was saying is you could achieve this in your `gatsby-node.js` code:

```diff
...
    result.posts.edges.forEach(({ node }) => {
      createPage({
-        path: node.childMdx.fields.slug,
+        path: `/articles${node.childMdx.fields.slug},
        component: path.resolve(`./src/templates/article.js`),
        context: {
          slug: node.childMdx.fields.slug,
          // id: node.id
        },
      })
    })
...
```

I recently set up something similar in my site, where it uses the subdirectory under `content` as the path in the URL.

eg. `content/blog/my-post.mdx` => `domain.com/blog/my-post/`

You can see how I set that up here:
https://github.com/lsirivong/lenny-s.com/blob/master/gatsby-node.js#L49

Hope that helps!

**Comment by rchrdnsh** [comment]
hmmmm...not quite able to make this work, as each piece of content is actually in it's own folder, which is the preferred folder structure, like so...

```
content [folder]
    article one [folder]
        article-one.md
        images [folder]
            image-1.jpg
            image-2.jpg
     article two [folder]
        article-two.md
        images [folder]
            image-1.jpg
            image-2.jpg
```

so all of the content is in a 'content' folder, then each article is in it's own folder named after itself with sub-folders with article specific assets.

Try to figure out how to make that particular folder structure work, but getting lost...

**Comment by lsirivong** [comment]
What in particular is not working for you? Are you having build issues with this set up?

I believe the only difference between your example and my blog is:

```diff
 content [folder]
-    article one [folder]
-        article-one.md
+    article-one [folder]
+        index.md
         images [folder]
             image-1.jpg
             image-2.jpg
-     article two [folder]
-        article-two.md
+     article-two [folder]
+        index.md
         images [folder]
             image-1.jpg
             image-2.jpg
```

**Comment by rchrdnsh** [comment]
I'm not sure now, to be honest...need to try and go through the whole setup to figure out what's going wrong...without an explicit router I find it a bit challenging to do the kind of routing I want to do, but I'm also pretty new to Gatsby as well, and trying to use bleeding edge stuff like MDX, so there's that.

**Comment by rchrdnsh** [comment]
When clicking on the link to the article in question it should go to:

```
http://localhost:8000/words/practice/
```

but instead tries to go to:

```
http://localhost:8000/practice/practice/
```

and then gives me this error page:

<img width="940" alt="screenshot 2019-02-13 16 21 46" src="https://user-images.githubusercontent.com/7884263/52753528-d589c600-2fab-11e9-9778-805dd9577b31.png">

I really don't understand why it's trying to do that, and without knowing how to explicitly set routes, I just don't know where to look to fix it...

**Comment by DSchau** [comment]
Hi Richard!

It's extremely challenging to work backwards to figure out what's going wrong here. Generally, it looks like the slug that's being created is not creating the exact path that you want--but that's OK and expected. You're in control of what gets created!

Given:

```
content/
  /practice
    index.md
```

gatsby-source-filesystem's `createFilePath` will create a slug like `/practice` (relative to `/content`). If you want to prepend `/words` to the generated URL, you can do that when you create the slug, like so:

```js
const path = require(`path`)
const { createFilePath } = require(`gatsby-source-filesystem`)

exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions
  if (node.internal.type === `Mdx`) {
    const slug = createFilePath({ node, getNode, basePath: `pages` })
    createNodeField({
      node,
      name: `slug`,
      value: `/words${slug}`, // /words/practice/
    })
  }
}
```

This will create the field like you'd expect, and then when you query for pages and create pages (which is currently querying this field) it will create the expected route.

A [reproduction](https://gatsby.dev/reproduction) would be helpful here, as well.

Thanks!

**Comment by muescha** [comment]
@DSchau the reproduction link is broken

**Comment by DSchau** [comment]
@muescha no it's not?

Does https://gatsby.dev/reproduction not work for you?

**Comment by muescha** [comment]
no

**Comment by muescha** [comment]
maybe i miss something magic for development - but in the doc don't i found nothing about the gaysby.dev ... and google search only show me 2x this line: `Learn about environment variables: https://gatsby.dev/env-vars`

**Comment by DSchau** [comment]
Sorry - would you mind opening a separate issue here? It's a bit tangential to the issue at hand.

Thanks!

**Comment by muescha** [comment]
ok - sorry -> #12385
