### ISSUE TITLE
Child component of template not being parsed by Gatsby

### ISSUE THREAD

**Issue by snirp** [gatsbyjs/gatsby#11250]
## Description

I have a Post template that can display a Gatsby Image. I tried moving the image to a separate React component (ImageHeader), but that doesn't work as expected. It seems like the ImageHeader has no access to the `data` (although that is explicitly passed to the component and shows up correctly in a `console.log`). The image will also not display. I even tried passing the `sizes` directly to the ImageHeader, but that does not get parsed by Gatsby (only showing [Object object]).

### Steps to reproduce

See also this codesandbox: https://codesandbox.io/s/github/snirp/royprins.com

`Post`
```
import React from 'react';
import { graphql } from 'gatsby';
import Img from 'gatsby-image';

import ImageHeader from '../components/ImageHeader';


export default ({ data }) => {
  return (
    <div>
      {/* This works */}
      <Img sizes={data.markdownRemark.fields.coverFile.childImageSharp.sizes} />

      {/* This doesn't work */}
      <ImageHeader data={data} />
      
      <h1>{data.markdownRemark.frontmatter.title}</h1>
      <div dangerouslySetInnerHTML={{ __html: data.markdownRemark.html }} />
    </div>
  );
};

export const query = graphql`
  query($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      html
      frontmatter {
        title
      }
      fields {
        coverFile {
          childImageSharp {
            sizes(maxWidth: 1400) {
              ...GatsbyImageSharpSizes_tracedSVG
            }
          }
        }
      }
    }
  }
`;
```

`ImageHeader`
```
import React from 'react';
import Img from 'gatsby-image';

export default data => (
  <div>
    {console.log(data)}
    <Img sizes={data.markdownRemark.post.fields.coverFile.childImageSharp.sizes} />
  </div>
);
```

### Expected result

The ImageHeader should have access to `data` and render the Gatsby Image correctly with sizes.

### Actual result

What happened.

`TypeError: Cannot read property 'post' of undefined`

### Environment

  System:
    OS: macOS 10.14.2
    CPU: x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0.2
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.91 => 2.0.91 
    gatsby-cli: ^2.4.8 => 2.4.8 
    gatsby-image: ^2.0.26 => 2.0.26 
    gatsby-plugin-emotion: ^4.0.1 => 4.0.1 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.17 
    gatsby-remark-copy-linked-files: ^2.0.8 => 2.0.8 
    gatsby-remark-images: ^3.0.1 => 3.0.1 
    gatsby-remark-prismjs: ^3.2.0 => 3.2.0 
    gatsby-remark-smartypants: ^2.0.7 => 2.0.7 
    gatsby-source-filesystem: ^2.0.16 => 2.0.16 
    gatsby-transformer-remark: ^2.2.0 => 2.2.0 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.10 
    gatsby-transformer-yaml: ^2.1.7 => 2.1.7 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by sidharthachatterjee** [comment]
Just took a look at this @snirp 

Changing ImageHeader.jsx to the following fixes it:
```
export default ({ data }) => {
  return (
    <div>
      <Img sizes={data.markdownRemark.fields.coverFile.childImageSharp.sizes} />
    </div>
  )
}

```

Basically, 
- data needed to be destructured since the parameter to the function is `props`
- you were accessing `data.markdownRemark.post.fields` which needed to be `data.markdownRemark.fields`

Closing this but please feel free to reopen if this doesn't fix your issue!
