### ISSUE TITLE
Avoid confusion when reading transformers plugin doc

### ISSUE THREAD

**Issue by enzoferey** [gatsbyjs/gatsby#11251]
Hi !

So I was reading through [custom transformers plugin docs](https://www.gatsbyjs.org/docs/create-transformer-plugin/). It tells that the common to use them is to do this:

`exports.setFieldsOnGraphQLNodeType = require("./extend-node-type")`

And then just underneath it provides a link to the [API docs](https://www.gatsbyjs.org/docs/node-apis/#setFieldsOnGraphQLNodeType). So if you go to that page and you copy paste the example:

```js
import { GraphQLString } from "gatsby/graphql"

exports.setFieldsOnGraphQLNodeType = ({ type }) => {
  if (type.name === `File`) {
    return {
      newField: {
        type: GraphQLString,
        args: {
          myArgument: {
            type: GraphQLString,
          }
        },
        resolve: (source, fieldArgs) => {
          return `Id of this node is ${source.id}.
                  Field was called with argument: ${fieldArgs.myArgument}`
        }
      }
    }
  }

  // by default return empty object
  return {}
}
```

You will get a nice and hard to debug error `TypeError: gatsbyNode[api] is not a function`.

Searching for a bit I found https://github.com/gatsbyjs/gatsby/issues/6313 and the problem comes from the fact that we are importing the default export in `gatsby-node.js` but only exposing the function as a named export in `extend-node-type.js`.

I think it makes sense to adjust one or the other to have a working solution by just copy pasting across steps in the doc.

In this case, I think what makes more sense is to adjust the example of `extend-node-type.js` to export the function as the default import.

What do you think ? I can open a PR if you want 👍

**Comment by sidharthachatterjee** [comment]
Good catch, @enzoferey! We'd love to receive a PR fixing the example.

**Comment by imcodingideas** [comment]
@enzoferey yes, I am going it.

**Comment by enzoferey** [comment]
I can pick it up if needed !
