### ISSUE TITLE
Custom Webpack Config not Accepting `output` path option

### ISSUE THREAD

**Issue by mattfwood** [gatsbyjs/gatsby#11262]
## Description

I'm trying to dynamically build a large number of Gatsby sites at once with different configs. But since they all build to the `public` directory by default, I'm forced to build them one at a time which presents significant scaling issues.

However, when I try to specify a custom output path in `gatsby-node.js` with `onCreateWebpackConfig`, it seems to ignore this change and still output to `public`.

I've looked into the source code [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L105) and I see where the default output path is being set, but looking through it, it seems like the webpack config should still be able to override that?

I've been digging through the Gatsby source for a good amount of time and can't seem to see where I might be able to make this work. I would be more than willing to work on this bug myself, but I've hit a wall so any direction would be greatly appreciated.

### Steps to reproduce

`gatsby-node.js`
```javascript
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    output: {
      path: `sites/${process.env.GATSBY_SITE_NAME}`,
    },
  });
};
```

Even if I use a fixed path (not a template string like shown above) it still just builds to the public directory.

### Expected result

Gatsby should build to the new output path provided to `setWebpackConfig`

### Actual result

Gatsby still builds to the `public` directory.

### Environment

  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.76 => 2.0.76 
    gatsby-image: ^2.0.20 => 2.0.25 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12 
    gatsby-plugin-offline: ^2.0.16 => 2.0.20 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.14 => 2.0.16 
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4 
    gatsby-source-filesystem: ^2.0.8 => 2.0.12 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9 
    gatsby-transformer-yaml: ^2.1.7 => 2.1.7

**Comment by sidharthachatterjee** [comment]
Based on https://www.gatsbyjs.org/docs/actions/#setWebpackConfig

> Specifically, any change to entry, output, target, or resolveLoaders will be ignored.
For full control over the webpack config, use replaceWebpackConfig().

However, I tried this out and this is tricky because a lot of the Gatsby source has `public` hardcoded in several places and many plugins depend on it as well 

This was attempted at https://github.com/gatsbyjs/gatsby/pull/4756 but reverted because it broke a bunch of things
