### ISSUE TITLE
Amplify starter PR merged but not showing up on the main website

### ISSUE THREAD

**Issue by swaminator** [gatsbyjs/gatsby#11260]
Hi, 

The PR: https://github.com/gatsbyjs/gatsby/pull/11235 was recently merged. However, when I goto https://www.gatsbyjs.org/starters/ and search for 'amplify' or 'aws', it doesn't show up. Is there anything else I should do?

**Comment by LekoArts** [comment]
The build just had a hiccup and it's now live ;)
