### ISSUE TITLE
Unit Testing tutorial yields failing test after following steps

### ISSUE THREAD

**Issue by renschler** [gatsbyjs/gatsby#11267]
## Description

I've attempted to follow the steps in the [Unit testing guide](https://www.gatsbyjs.org/docs/unit-testing/), as well as the [Testing components with GraphQL guide](https://www.gatsbyjs.org/docs/testing-components-with-graphql/), but the simple index.js test is still failing. I think the tutorial needs to be updated.

### Steps to reproduce

```
# install starter blog
npx gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-blog

# start with the unit testing guide: https://www.gatsbyjs.org/docs/unit-testing/
# install dependencies while in the starter blog project
npm install --save-dev jest babel-jest react-test-renderer identity-obj-proxy babel-core@^7.0.0-bridge.0 @babel/core babel-preset-gatsby

# create jest.config.js as described
# create jest-preprocess.js as described
# create __mocks__/fileMock.js as described
# create loadershim.js as described
# create __mocks__/gatsby.js as described
# update test script in package.json to call jest
# create src/__tests__/index.js using provided code with location const
# try running npm run test, this fails (as expected) bc no GraphQL data being passed to component 
```
![screen shot 2019-01-24 at 3 31 26 pm](https://user-images.githubusercontent.com/3973468/51709935-642ea700-1fed-11e9-9ce2-e7b5071849af.png)

```
# So now move to GraphQL guide: https://www.gatsbyjs.org/docs/testing-components-with-graphql/
# update src/__tests__/index.js with provided code. This code contains data const
# which was obtained from GraphiQL IDE
npm run test
```
Resulting Error: Invariant Violation: mockConstructor(...)
![screen shot 2019-01-24 at 3 36 29 pm](https://user-images.githubusercontent.com/3973468/51710568-2f235400-1fef-11e9-8f8b-2c1ca92a3df8.png)

### Expected result

After providing mocked data within the index.js test, I expected the test to pass and for there to be a snapshot in the snapshot dir as described:
![screen shot 2019-01-24 at 3 46 44 pm](https://user-images.githubusercontent.com/3973468/51710624-50844000-1fef-11e9-89bf-136b0d0d23cc.png)

### Actual result

The test fails, see above screenshot for error message.

### Environment

 ```
 System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.76 => 2.0.76
    gatsby-image: ^2.0.22 => 2.0.25
    gatsby-plugin-feed: ^2.0.8 => 2.0.11
    gatsby-plugin-google-analytics: ^2.0.5 => 2.0.8
    gatsby-plugin-manifest: ^2.0.5 => 2.0.12
    gatsby-plugin-offline: ^2.0.5 => 2.0.20
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.5
    gatsby-plugin-sharp: ^2.0.6 => 2.0.16
    gatsby-plugin-typography: ^2.2.0 => 2.2.3
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.8
    gatsby-remark-images: ^2.0.4 => 2.0.6
    gatsby-remark-prismjs: ^3.0.0 => 3.1.4
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.8
    gatsby-remark-smartypants: ^2.0.5 => 2.0.7
    gatsby-source-filesystem: ^2.0.2 => 2.0.12
    gatsby-transformer-remark: ^2.1.6 => 2.1.17
    gatsby-transformer-sharp: ^2.1.3 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

**Comment by renschler** [comment]
Update: I noticed in __mocks__/gatsby.js we were calling jest.fn().mockImplementation() I changed this to jest.fn(--Inserted mock implementation here--) because that's what the most recent Jest documentation says to do. But this didn't change my output.

**Comment by DSchau** [comment]
My guess is that this changed with the introduction of the SEO component. For now - I think you'll want to mock the result of StaticQuery with something like:

```jsx
import { StaticQuery } from 'gatsby' // this will be mocked

// later

describe(`BlogIndex`, () => {
  it(`renders correctly`, () => {
    StaticQuery.mockReturnValueOnce(({ render }) => render({
      data: {
        site: {
          siteMetadata: {
            title: `Hello World`
          }
        }
      }
    }))

    // the rest of your test
  })
})
```

want to give that a shot and let me know if it works? If it does, I'd propose we make a few changes to that guide, specifically:

1. Use the default starter instead of the blog starter (simpler!)
1. Mock out the SEO component in a little bit nicer way

**Comment by renschler** [comment]
thanks for the help, I tried your recommendation and I got a very similar error message. The main error is the same but the warning text at the bottom is slightly different.

![screen shot 2019-01-24 at 4 53 43 pm](https://user-images.githubusercontent.com/3973468/51713799-c640d980-1ff8-11e9-90d6-e013272771f8.png)

**Comment by DSchau** [comment]
@renschler guessing this repo is in a state where it could be shared. Could you share the link please?

**Comment by renschler** [comment]
@DSchau I uploaded it here: [https://github.com/renschler/my-blog-starter](https://github.com/renschler/my-blog-starter)

**Comment by renschler** [comment]
I commented out the SEO and the Bio component and things worked. So I think you are right, just need to mock the StaticQuery for both of those components and things should pass.

That said, I'm new to jest/gatsby and I didn't follow most of the guide. So I agree starting with something simpler might be better.

**Comment by DSchau** [comment]
@renschler thanks for letting us know about this! I updated the tutorial in #11293 to reflect some of these idiosyncrasies. I'll close this out when it's merged, but wanted to let you know!
