### ISSUE TITLE
Graphql Errors for unused templates

### ISSUE THREAD

**Issue by pgegenfurtner** [gatsbyjs/gatsby#11278]
## Description
Using the new theme functionality, I have a core theme from which I generate multiple different projects, which consume this theme. 
In the core theme I have different page templates. Some may not be used by theme consumers. But data which these unused templates want to query may not be available in a theme consumer, so I get a graphql error and the site cannot be build.
Is there some way around this?

**Comment by ChristopherBiscardi** [comment]
silly gatsbot. keep this open while we work on the data abstractions.

**Comment by pgegenfurtner** [comment]
Is there a solution for this yet?

**Comment by pieh** [comment]
We released support for "schema customization" API ( https://www.gatsbyjs.org/blog/2019-03-18-releasing-new-schema-customization/ ) that allow you to define types, so schema is consistent even without having any data.

Can you provide more information what kind of sources are you using, as examples of this might be different depending on what you are using.

**Comment by pgegenfurtner** [comment]
@pieh That sounds like a solution, but I don't unterstand how I would implement this. 
I will try to give an example.. 

I have projects A and B, both using my theme. In the theme I have a query fragment for a component `newsletter`. The fragment looks like this: 

```
export const newsletter = graphql`
    fragment Newsletter on DirectusProject {
        newsletter {
            endpoint
            mail
        }
    }
`;
```

Project A does have a newsletter configuration. Project B does not (and does not use the newsletter component). So in the graphql schema the `newsletter` node under `directusProject` is not present. 
I believe what I would need is to create this node with just null values.

**Comment by pieh** [comment]
Idea is that you would use something like this:
```js
exports.sourceNodes = ({ actions }) => {
  actions.createTypes(`
    type Newsletter {
      endpoint: String
      mail: String
    }

    type DirectusProject implements Node {
      newsletter: Newsletter
    }
  `)
}
so even if newsletter field is never used - it will be created in schema correctly and queries don't break.

Ultimately it would be ideal if Directus plugin would create those types automatically (if it knows the type structure), so users don't have to do that manually. But this is new feature and we are stillworking on it, so it will take some time for ecosystem to catch up.

**Comment by pieh** [comment]
Sorry, random click - I didn't mean to close it.

**Comment by pgegenfurtner** [comment]
This solves my problem, thank you!

**Comment by lannonbr** [comment]
So are we good to close this issue now @pgegenfurtner ?

**Comment by pgegenfurtner** [comment]
Yes

**Comment by pgegenfurtner** [comment]
Sorry, I have to reopen this.

In the project where the newsletter field is present, the createTypes function seems to override it with null values. What am I doing wrong here? I implemented the function in my theme.

**Comment by freiksenet** [comment]
@pgegenfurtner Hm, that shouldn't happen. What is value that's present in the newsletter? I wonder if it'd be possible for you to share a reproduction project with us.

**Comment by freiksenet** [comment]
Ping @pgegenfurtner

**Comment by pgegenfurtner** [comment]
The value is just null. 
I will try to publish a reproduction repo.
But basically I implemented this like @pieh suggested:

```

exports.sourceNodes = ({ actions }) => {
  actions.createTypes(`
    type Newsletter {
      endpoint: String
      mail: String
    }

    type DirectusProject implements Node {
      newsletter: Newsletter
    }
  `)
}
```

**Comment by freiksenet** [comment]
@pgegenfurtner That looks like it should work. Could you also include data that's inside DirectusProject type?

**Comment by sidharthachatterjee** [comment]
Closing this because the problem described in here is solved by defining a schema using the schema customisation API. 

With respect to not warning for unused templates, let's track that in https://github.com/gatsbyjs/gatsby/issues/20413

Thanks!
