### ISSUE TITLE
How does google know what pages to crawl when using GatsbyJS

### ISSUE THREAD

**Issue by jephjohnson** [gatsbyjs/gatsby#11274]
Pardon my lack of knowledge here, I am still new to using GatsbyJS.

When building out locally if I hit a 404 page I get a list of available pages. (see attached)

Just wondering if google indexes all these pages?
<img width="906" alt="screen shot 2019-01-24 at 3 37 57 pm" src="https://user-images.githubusercontent.com/1817084/51717504-f044cc80-1ff5-11e9-9380-b009f62603f5.png">

**Comment by sidharthachatterjee** [comment]
@jephjohnson That page is development only and doesn't get into the production bundle

Most search engines crawl pages by following links from one page to another. You _can_ make this easier for them by building a sitemap. 

Check out the documentation at https://www.gatsbyjs.org/docs/creating-a-sitemap/

Closing this for the moment but please feel free to reopen or comment if I haven't answered your question completely!

**Comment by jephjohnson** [comment]
> @jephjohnson That page is development only and doesn't get into the production bundle
> 
> Most search engines crawl pages by following links from one page to another. You _can_ make this easier for them by building a sitemap.
> 
> Check out the documentation at https://www.gatsbyjs.org/docs/creating-a-sitemap/
> 
> Closing this for the moment but please feel free to reopen or comment if I haven't answered your question completely!

Thanks @sidharthachatterjee
