### ISSUE TITLE
Demo with Graphcool

### ISSUE THREAD

**Issue by sedubois** [gatsbyjs/gatsby#1127]
As the Gatsby documentation mentioned how it can integrate with external CMSes, and considering its evolution towards a GraphQL data layer, I think it would be awesome to have a Gatsby + [Graphcool](https://www.graph.cool/) demo 😄 

cc @sorenbs

**Comment by jbolda** [comment]
@sedubois are you volunteering to make a plugin for it? 😁

There is one in process for contentful, but it would be awesome to see graphcool in the mix.

**Comment by kbrandwijk** [comment]
Would that be a source plugin like gatsby-source-drupal or something? Where can I find the contentful plugin source?

**Comment by KyleAMathews** [comment]
Yeah, it'd be a source plugin (need to write up docs on writing source plugins soon). You can find the source at https://github.com/gatsbyjs/gatsby/tree/1.0/packages

**Comment by kbrandwijk** [comment]
Cool, I'll try that... Thanks!

**Comment by nickeblewis** [comment]
@kbrandwijk @KyleAMathews this is something I am interested in using at least, as I have an account on GraphCool and data I'd like to pull into a project of ours

**Comment by KyleAMathews** [comment]
@nickeblewis nice! Would love a graphcool plugin added. BTW, did get the source plugin docs up https://www.gatsbyjs.org/docs/create-source-plugin/

**Comment by spherop** [comment]
Would love to see this in Gatsby. Seems like the perfect combo.

**Comment by spherop** [comment]
@KyleAMathews - just getting acquainted with Gatsby - is there any reason that one cannot simply interact with graphcool from react components in Gatsby - is a plugin necessary given the Gatsby architecture?

**Comment by KyleAMathews** [comment]
To be able to query graphcool using gatsby's data layer and include as part  of server rendering yes. But to use in client like normal no.

**Comment by spherop** [comment]
Thanks Kyle.

**Comment by KyleAMathews** [comment]
Planning on doing GraphQL stitching in the future https://github.com/gatsbyjs/gatsby/pull/2423#issuecomment-352535452

**Comment by DanielRSnell** [comment]
Check out the GraphCMS plugin, it looks like it's most like just a graphql-requests wrapper. When I use a Graphcool endpoint with it creates the nodes in ___graphql but prompts a duplicate graphql instance warning. I was thinking about using this as a starting point, if anyone else has something better, let me know!
