### ISSUE TITLE
TypeError: Cannot read property 'spaceId' of undefined

### ISSUE THREAD

**Issue by jonasman** [gatsbyjs/gatsby#11282]
## Description

Installing contenful starting guide

### Steps to reproduce
Just follow the intro tuturial:

Copy the following commands into your terminal:
`git clone https://github.com/contentful/starter-gatsby-blog.git`
`cd starter-gatsby-blog`
`npm install`
`npm run setup -- --spaceId XXXX --deliveryToken XXX --managementToken CFPAT-XXXx`
See the blog in action:
`npm run dev` --> Fails here

### Expected result

The tutorial should show me a blog or something

### Actual result
```
success delete html and css files from previous builds — 0.008 s
error We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.


  TypeError: Cannot read property 'spaceId' of undefined
  
  - gatsby-config.js:10 Object.<anonymous>
    /Users/jnunes/DEV/starter-gatsby-blog/gatsby-config.js:10:64
  
  - v8-compile-cache.js:178 Module._compile
    [starter-gatsby-blog]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - v8-compile-cache.js:159 require
    [starter-gatsby-blog]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - get-config-file.js:36 _callee$
    [starter-gatsby-blog]/[gatsby]/dist/bootstrap/get-config-file.js:36:28

```
### Environment

 System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.8.0 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277 
    gatsby-image: ^1.0.55 => 1.0.55 
    gatsby-link: ^1.6.46 => 1.6.46 
    gatsby-plugin-react-helmet: ^1.0.8 => 1.0.8 
    gatsby-plugin-sharp: ^1.6.46 => 1.6.48 
    gatsby-source-contentful: ^1.3.54 => 1.3.54 
    gatsby-transformer-remark: ^1.7.44 => 1.7.44 
  npmGlobalPackages:
    gatsby-cli: 2.4.8

**Comment by karenhou** [comment]
Did you apply all the fields it required? All three of the fields need to be provided. For the managementToken you can obtained via Setting/APIs/content management tokens

**Comment by marcusps11** [comment]
I am also having this problem?  Any ideas how to fix
