### ISSUE TITLE
[docs] Broken anchor link in Adding Images, Fonts, and Files

### ISSUE THREAD

**Issue by tatchi** [gatsbyjs/gatsby#11297]
## Description

There's a broken link in the "Adding Images, Fonts, and Files" section of the documentation.

At the bottom of the page (within the "When to Use the static Folder"), the "stylesheets" link does not seem to work.

see: https://www.gatsbyjs.org/docs/adding-images-fonts-files/#when-to-use-the-static-folder

It tries to redirect to a position elsewhere in the page, but I couldn't find a spot in the page where we talk about importing stylesheet. Therefore, I don't really know what to replace this link with.

Maybe redirect to the top of the page (and use the same link than the "images, and fonts" text just next to the "stylesheets" one)? 

What do you think?

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @tatchi 

The link is broken and while we can change it to /#adding-images-fonts-files, that section doesn't mention anything about stylesheets and could be confusing. 

I'd probably lean _towards_ removing the `stylesheets` word from that sentence entirely but I think @shannonbux should have a better idea here.

**Comment by shannonbux** [comment]
For now, just removing the hyperlink but leaving the word there might work best. I don't have the technical expertise to know what we could link to, but at least this would get rid of the broken link. 

Thanks!

PS I did some digging to figure out what this was supposed to link to, and no luck. This is the issue that led to the creation of this doc in the first place, though the link was broken in the first draft of this doc too: https://github.com/gatsbyjs/gatsby/issues/9222

**Comment by tatchi** [comment]
Thanks for your suggestions 👍

Here's the PR:  #11499
