### ISSUE TITLE
requestAnimationFrame and Gatsby?

### ISSUE THREAD

**Issue by artemartemov** [gatsbyjs/gatsby#11300]
hey there, I was wondering if utilizing `requestAnimationFrame` is possible in gatsby

I have a simple background slider and was implementing rAF but realized that the build fails on prod builds. This is the code snippet in question:
```js
const requestTimeout = (fn, delay) => {
  if (typeof window !== `undefined`) {
    if (!window.requestAnimationFrame) return setTimeout(fn, delay);
  }

  const start = new Date().getTime();
  const handle = {};
  const loop = () => {
    const current = new Date().getTime();
    const delta = current - start;

    delta >= delay ? fn.call() : (handle.value = requestAnimationFrame(loop));
  };

  handle.value = requestAnimationFrame(loop);
  return handle;
};
```

and during prod build I get `WebpackError: ReferenceError: requestAnimationFrame is not defined`

I haven't been able to find any sorts of discussions or talk about this anywhere, so if this was already asked before I do apologize.

**Comment by yeskunall** [comment]
@artemartemov you’re getting a `ReferenceError`. In your code snippet, I don’t see you defining `requestAnimationFrame` anywhere. I think if you just use `window.requestAnimationFrame` everywhere, at least your webpack compile errors _should_ disappear.

I use [raf](https://www.npmjs.com/package/raf) as it also has a polyfill for browsers that don’t support the API.

**Comment by artemartemov** [comment]
@yeskunall wow yeah 🤦‍♂️ I am a dummy. defining window helps!

**Comment by yeskunall** [comment]
I’m glad I could help @artemartemov! 😁

I am, however, a little curious. How did webpack only complain during a production build? It should have complained about this during any sort of compilation process, really.

If you’re too busy, I’ll let you move on, but I would appreciate it if you could let me know. I’m just wondering 😅

**Comment by artemartemov** [comment]
@yeskunall so I am not quite sure _why_ it only decided to fail on the production build end. But it could be due to the fact I am using [lerna](https://github.com/lerna/lerna) on my parent folder to run commands in the `/cms/` and the `/gatsby/` child directories, but all it was running was a `gatsby develop` and a startup script for the cms to spin up locally on another port.

this was code that is part of a background image slider/fader, but I have no clue on the exact why. 

more than happy to share my code with you if you're really curious!
