### ISSUE TITLE
[plugin-manifest] Add option to opt-out of generating favicon (vs. pwa icon)

### ISSUE THREAD

**Issue by seaneking** [gatsbyjs/gatsby#11308]
## Summary

Currently `gatsby-plugin-manifest` automatically generates and links to a favicon as well as PWA style icons when in automatic or hybrid mode, and there's no way to opt-out of this behaviour without going full manual mode. 

The plugin should expose an opt-out flag for this, as it already does for other problematic on-by-default features (eg: theme-color tags). Especially since a) favicons are arguably out of scope for a PWA manifest-style featureset anyway, and b) it's trivial for users to include their own single favicon asset.

### Basic example

Easiest way to accomplish this is to add another optional config parameter to the plugin 

```js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `GatsbyJS`,
	...
        icon: `src/images/icon.png`,
	include_favicon: true // Defaults to true to be non-breaking
      }
    }
  ]
}
```

### Motivation

It's very common to want very different assets for a favicon and PWA icon — eg: a small transparent icon for the favicon, and a more intricate icon with a background for the PWA manifest. While you can achieve this using 'manual' mode, that's a frustrating workaround for a fairly large use-case.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @seaneking 

We would love to accept a PR adding this! Would you be interested?

**Comment by gurpreet-hanjra** [comment]
Hello, can I take this task?

**Comment by pieh** [comment]
`gatsby-plugin-manifest@2.0.16` was released which added support for `include_favicon` config option.

Thanks @gurpreet-hanjra for adding support for it.
