### ISSUE TITLE
Reducing or removing gatsby-source-mongodb lodash dependency

### ISSUE THREAD

**Issue by raulrpearson** [gatsbyjs/gatsby#11307]
gatsby-source-monbodb requires lodash and uses it twice in `mapping.js` and once in `gatsby-node.js`.

- I'd recommend substituting [`_.isArray(collection)`](https://github.com/gatsbyjs/gatsby/blob/026d2a956296cb01936bcf45d2be1066dd844d00/packages/gatsby-source-mongodb/src/gatsby-node.js#L32) with `Array.isArray(collection)` since `_.isArray` is [deprecated](https://www.npmjs.com/package/lodash.isarray). This way, `gatsby-node.js` can also stop depending on lodash.

- [`_.isString(text)`](https://github.com/gatsbyjs/gatsby/blob/026d2a956296cb01936bcf45d2be1066dd844d00/packages/gatsby-source-mongodb/src/mapping.js#L5) could be implemented with `typeof text === 'string'` or maybe not, since lodash seems to be doing [something extra](https://github.com/lodash/lodash/blob/6248f8a65861b506f2c106defe28619be5f45723/isString.js#L20) that I don't fully understand and might be important (relevant discussion in [this SO answer](https://stackoverflow.com/a/4059166)):

```javascript
function isString(value) {
  const type = typeof value
  return type == 'string' || (type == 'object' && value != null && !Array.isArray(value) && getTag(value) == '[object String]')
}
```

- [`_.camelCase(...)`](https://github.com/gatsbyjs/gatsby/blob/026d2a956296cb01936bcf45d2be1066dd844d00/packages/gatsby-source-mongodb/src/mapping.js#L13) doesn't seem worth [implementing](https://github.com/lodash/lodash/blob/6248f8a65861b506f2c106defe28619be5f45723/camelCase.js#L23):

```javascript
const camelCase = (string) => (
  words(`${string}`.replace(/['\u2019]/g, '')).reduce((result, word, index) => {
    word = word.toLowerCase()
    return result + (index ? upperFirst(word) : word)
  }, '')
)
```

If `_.isString()` and `_.camelCase()` are kept, they could at least be required in their [modularized versions](https://www.npmjs.com/search?q=keywords:lodash-modularized).

**Comment by raulrpearson** [comment]
Absolutely, I'll try to get it done tomorrow. I'll change the `isArray` use in `gatsby-node.js` and use modularized imports in `mapping.js`.

**Comment by sidharthachatterjee** [comment]
Thank you, @raulrpearson!
