### ISSUE TITLE
[1.0] [RFC] Frontmatter Conventions

### ISSUE THREAD

**Issue by nicholaswyoung** [gatsbyjs/gatsby#1131]
Gatsby ingests and processes more markdown sources than anything else. At least a [couple](https://github.com/gatsbyjs/gatsby/tree/1.0/packages/gatsby-plugin-feed) [plugins](https://github.com/gatsbyjs/gatsby/tree/1.0/packages/gatsby-plugin-sitemap) from core already assume a default structure for YAML or JSON frontmatter, for example, each markdown file might have the following attributes:

```yaml
---
draft: true
---
```

As the plugin ecosystem expands, default frontmatter fields allow authors to build on a standard API. To begin, I propose the above.

**Comment by millette** [comment]
I noticed draft field was required when I use the feed plugin. Is there a way to specify a default value (true for draft, for example).
