### ISSUE TITLE
gatsby-remark-katex macros 

### ISSUE THREAD

**Issue by pantelis** [gatsbyjs/gatsby#11320]
I wonder if the inclusion of katex macros is supported in the current version of the plugin or if you can comment on the copied portion of the gatsby-config.js file where I tried to experiment with macros. I couldnt find any information in the Katex site other than the this [doc](https://github.com/KaTeX/KaTeX/blob/master/docs/options.md) that points to a [macros.js
 ](https://github.com/KaTeX/KaTeX/blob/master/src/macros.js). Non macro katex is rendered correctly including the macros defined in the standard Katex. But for my usage (university course site) I need to define new macros. 

### Environment (if relevant)

  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.88 => 2.0.88 
    gatsby-image: ^2.0.5 => 2.0.25 
    gatsby-plugin-canonical-urls: ^2.0.5 => 2.0.8 
    gatsby-plugin-catch-links: ^2.0.2 => 2.0.9 
    gatsby-plugin-emotion: ^2.0.5 => 2.0.7 
    gatsby-plugin-feed: ^2.0.5 => 2.0.11 
    gatsby-plugin-google-analytics: ^2.0.5 => 2.0.8 
    gatsby-plugin-google-tagmanager: ^2.0.5 => 2.0.7 
    gatsby-plugin-guess-js: ^1.0.0 => 1.0.3 
    gatsby-plugin-layout: ^1.0.11 => 1.0.11 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.3 
    gatsby-plugin-mailchimp: ^2.2.3 => 2.2.3 
    gatsby-plugin-manifest: ^2.0.2 => 2.0.13 
    gatsby-plugin-netlify: ^2.0.0 => 2.0.6 
    gatsby-plugin-netlify-cache: ^0.1.0 => 0.1.0 
    gatsby-plugin-nprogress: ^2.0.5 => 2.0.7 
    gatsby-plugin-offline: ^2.0.19 => 2.0.21 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.17 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.4 
    gatsby-plugin-subfont: ^1.0.1 => 1.0.3 
    gatsby-plugin-twitter: ^2.0.5 => 2.0.8 
    gatsby-plugin-typography: ^2.2.0 => 2.2.5 
    gatsby-remark-autolink-headers: ^2.0.10 => 2.0.12 
    gatsby-remark-code-titles: ^1.0.2 => 1.0.2 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.8 
    gatsby-remark-draw: ^1.0.15 => 1.0.15 
    gatsby-remark-graphviz: ^1.0.0 => 1.0.5 
    gatsby-remark-images: ^2.0.1 => 2.0.6 
    gatsby-remark-katex: ^3.0.1 => 3.0.1 
    gatsby-remark-normalize-paths: ^1.0.0 => 1.0.0 
    gatsby-remark-prismjs: ^3.0.2 => 3.2.0 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.8 
    gatsby-remark-smartypants: ^2.0.5 => 2.0.7 
    gatsby-source-filesystem: ^2.0.1 => 2.0.12 
    gatsby-source-npm-package-search: ^2.0.0 => 2.0.2 
    gatsby-transformer-csv: ^2.0.0 => 2.0.5 
    gatsby-transformer-documentationjs: ^2.0.0 => 2.0.2 
    gatsby-transformer-remark: ^2.2.0 => 2.2.0 
    gatsby-transformer-screenshot: ^2.0.4 => 2.0.10 
    gatsby-transformer-sharp: ^2.1.1 => 2.1.10 
    gatsby-transformer-yaml: ^2.1.1 => 2.1.6 
  npmGlobalPackages:
    gatsby-cli: 2.4.8

### File contents - gatsby-config.js (relevant to the issue).

resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-katex`,
            options: {
              macros: '\def\rvepsilon{{\mathbf{\epsilon}}}'
            },
          },

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @pantelis 

`gatsby-remark-katex` currently does _not_ support macros but this should be a simple fix. We just need to accept options in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-katex/src/index.js and pass it on to the katex instance

Would you be interested in doing this? We would love to accept a PR adding this!

**Comment by pantelis** [comment]
Thank you @sidharthachatterjee for the timely response. Unfortunately I have no prior coding experience in Javascript. I use Gatsby without having to go down to Javascript level.

**Comment by sidharthachatterjee** [comment]
No worries, @pantelis 

I've added support for this in a new PR. We'll let you know once merged and released so you can upgrade and start using macros!
