### ISSUE TITLE
Corrupt Content Error on Gatsby Website

### ISSUE THREAD

**Issue by SeaDude** [gatsbyjs/gatsby#11347]
## Description

A number of links on the Featured Site gallery are returning with "Corrupted Content" errors. The thumbnails are white in the gallery, error appears upon clicking.

### Steps to reproduce

Go to Gatsby website. Click Featured Sites. Choose Education filter. Click Load More
![image](https://user-images.githubusercontent.com/8636973/51819661-0a95d900-2288-11e9-9cda-bc110fcfcaba.png)

**Comment by AnushPatel** [comment]
Hi @SeaDude,
I just tried to reproduce this with no avail? Can you try again and see if it still occurs? I will try out Chrome and Firefox to see if maybe that's the cause...

Anush :-)

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @SeaDude 

Can't reproduce this on either Chrome 71.0.3578.98 or Firefox 65.0b7

Could you please post more details about the environment and maybe add a screenshot of the console if you're still able to reproduce this?

**Comment by SeaDude** [comment]
Hello,
The thumbnails are now showing on the Gatsby Showcase page and the error is no longer occurring. 
I'm on Firefox for Ubuntu 1.0. 
Thank you

**Comment by SeaDude** [comment]
Looks like it was the Firefox Privacy Badger extension causing the issue. https://forum.vuejs.org/t/corrupted-content-error/55807/2

**Comment by ghostwords** [comment]
You are probably running into a Firefox WebExtensions bug having to do with Service Worker requests: https://github.com/EFForg/privacybadger/issues/1144#issuecomment-436444285
