### ISSUE TITLE
[docs] Map stubs to existing issues on GitHub

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#11342]
## Summary

Throughout the docs, we have a links in the sidebar that are greyed out noting an article that doesn't exist yet but would be useful to have. When you visit one, it currently has a notice saying 

### Basic example

For instance, the [How to run a Gatsby workshop](https://www.gatsbyjs.org/docs/how-to-run-a-gatsby-workshop/) page is a current stub, but we also have a issue open for such: #8847.

We could possibly add a field to the frontmatter in the stub file to link the github issue and then render it out somehow when generated.

```markdown
---
title: How to run a Gatsby workshop
issue: https://github.com/gatsbyjs/gatsby/issues/8847
---
```

Then, when a user visits the stub, we could guide them to the GitHub issue for said stub.

### Motivation

I believe adding links to the specific issues would possibly increase the experience for helping draw contributors. With this, they would know how to flesh out the page based upon the style guide as well as some specific guidance about the topic from the community / Gatsby team.

Not all stubs have matching issues, but for the ones that do, this could make the flow of seeing a stub to wanting to help flesh out the stub smoother.

**Comment by sidharthachatterjee** [comment]
This is a great idea, @lannonbr! It _might_ be extra effort to keep track of issues and stubs though

Let's see what @m-allanson and @shannonbux have to say!

**Comment by isaac-martin** [comment]
I can take this on if we want to go ahead? How is the grey styling applied in the sidebar? Could use the same logic to show / hide the link to the issue?

**Comment by shannonbux** [comment]
I think this is worth doing. Whatever makes it easiest for people to fill out/contribute to the stub article gets an up vote from me!

**Comment by isaac-martin** [comment]
Cool - i'll have a look now and open a PR.

**Comment by isaac-martin** [comment]
Doing this now. 
Not sure on best design decision to be made?
Small in footer next to the edit in the same style? Or up in the main body?

![image](https://user-images.githubusercontent.com/8649366/52154025-35967900-264a-11e9-8ca0-f2399a07fe0b.png)
