### ISSUE TITLE
Creating pages with invalid path silently errors

### ISSUE THREAD

**Issue by Ehesp** [gatsbyjs/gatsby#11348]
## Description

While creating pages programatically using the `createPage` action, one of my `path`s has the following characters...

### Steps to reproduce
```
    createPage({
      path: '/reference/mono-v6.x.x'
      component,
    });
```
### Expected result

If the characters are not allowed, I'd hope for a warning or error telling me so.

### Actual result

Strangely, the page is created, however the results are unexpected.

- While on the dev 404 page, I can see my page in the list. If I click it, the page/component loads correctly.
- If I directly navigate to the page in my browser, I get the error: `Cannot GET /reference/mono-v6.x.x`

There is nothing in logs about this, or in the browser console.

### Environment

```
  System:
    OS: macOS 10.14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.7.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 43.0.4
    Safari: 12.0.1
  npmGlobalPackages:
    gatsby-cli: 2.4.6

```

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @Ehesp 

The path is fine (as far as I know) and both `gatsby develop` and `gatsby build` build it correctly. It is in the right directory — public/reference/mono-v6.x.x/index.html

gatsby serve works correctly, looks like a minor issue with the webpack dev server setup during develop

**Comment by sidharthachatterjee** [comment]
So this isn't an issue with webpack-dev-middleware as the tests at https://github.com/webpack/webpack-dev-middleware/pull/365 assert

The issue is that in `packages/gatsby/src/commands/develop.js`, we only serve index.html if 
```
      parsedPath.extname === `` ||
      parsedPath.extname.startsWith(`.html`) ||
      parsedPath.path.endsWith(`/`)
```
I'll fix that since it is unnecessary as everything _should_ be caught that low in the pipeline
