### ISSUE TITLE
[docs] Add "emotion" to Styling section

### ISSUE THREAD

**Issue by LekoArts** [gatsbyjs/gatsby#11350]
We also want to have [emotion](https://emotion.sh/) in the styling section of the docs: https://www.gatsbyjs.org/docs/styling/

The title should be `Using CSS-in-JS library emotion` and also be added to the sidebar under the Glamor entry. Furthermore the Glamor entry should get a note at the beginning, saying that the maintainer recommends using emotion as it's actively maintained (Glamor isn't).

The doc itself should be similar to the styled-component one but also showcase the `css` prop. Examples of emotion are https://github.com/gatsbyjs/gatsby/tree/master/examples/using-emotion or https://github.com/LekoArts/gatsby-starter-prismic

**Comment by gurpreet-hanjra** [comment]
Hello, I would love to start with it. Although, I'm more into styled-components but documenting styling with emotion would be interesting.

**Comment by gurpreet-hanjra** [comment]
Hello @LekoArts I have raised a PR here for review. Please let me know if something is missing. https://github.com/gatsbyjs/gatsby/pull/11356

**Comment by LekoArts** [comment]
https://github.com/gatsbyjs/gatsby/pull/11356
