### ISSUE TITLE
Warning issued on Gatsby v2 Link and Styled Components/React props

### ISSUE THREAD

**Issue by aprather51** [gatsbyjs/gatsby#11362]
## Description
Getting browser console error:
*Warning: React does not recognize the `bgColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `bgcolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.*

### Steps to reproduce
Link.js
```
import React from 'react';
import PropTypes from 'prop-types';
import { Link } from 'gatsby';
import styled from 'styled-components';
import { darken } from 'polished';

const LinkTo = ({ children, to, bgColor, color }) => {
	return (
		<SetLink
			to={to}
			bgColor={bgColor}
			color={color}
		>
			{children}
		</SetLink>
	);
};

LinkTo.propTypes = {
	bgColor: PropTypes.string,
	color: PropTypes.string,
};

export default LinkTo;

/*Styles*/
const SetLink = styled(Link)`
	background: ${({ bgColor }) => bgColor || ''};
	color: ${({ color }) => color || ''};
  font-size: 1.5rem;
	padding: .5rem 1rem;
	border: ${({ border }) => border || 'none'};
	cursor: pointer;
	:hover {
		background: ${({ bgColor }) => bgColor && darken(0.1, bgColor)} || ${({
	bgColor
}) => bgColor};
    color: ${({ color }) => (color && darken(0.2, color)) || ''};
	}
`;

```

### Expected result
Function does work, Expected to remove warning from browser console. 

### Environment
System: Custom Build
OS: Win10 Pro
CPU: AMD FX-8320 Eight-Core Processors
Shell: zsh 5.1.1 
Binaries:
Node: 10.12.0 
yarn: 1.12.3
Browsers:
Chrome: 71.0.3578.98
Firefox: 66.0b2

npmPackages:
        "babel-plugin-styled-components": "^1.10.0",
        "gatsby": "^2.0.76",
        "gatsby-image": "^2.0.20",
        "gatsby-plugin-manifest": "^2.0.9",
        "gatsby-plugin-offline": "^2.0.16",
        "gatsby-plugin-react-helmet": "^3.0.2",
        "gatsby-plugin-resolve-src": "^2.0.0-beta.1",
        "gatsby-plugin-sharp": "^2.0.14",
        "gatsby-plugin-styled-components": "^3.0.4",
        "gatsby-remark-images": "^3.0.1",
        "gatsby-remark-relative-images": "^0.2.1",
        "gatsby-source-filesystem": "^2.0.8",
        "gatsby-transformer-remark": "^2.2.0",
        "gatsby-transformer-sharp": "^2.1.8",
        "polished": "^2.3.3",
        "prop-types": "^15.6.2",
        "react": "^16.6.3",
        "react-dom": "^16.6.3",
        "react-helmet": "^5.2.0",
        "react-pose": "^4.0.4",
        "rimraf": "^2.6.2",
        "styled-components": "^4.1.4-alpha.5"

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @aprather51 

@reach/router's Link
We pass down all props to

**Comment by homearanya** [comment]
This is an issue that is [currently being addressed](https://medium.com/@probablyup/introducing-transient-props-f35fd5203e0c) by the SC guys. It seems like they're about to introduce the concept of "transient" props to prevent this from passing down from the uppermost component layer.

**Comment by aprather51** [comment]
Only wonder about the progress -- how does it go? Did issues resolve? Should this I close this comments?

**Comment by wardpeet** [comment]
Thanks so much for opening this issue! As stated, this is slightly tangential to Gatsby, and it seems like we sadly have no control of this one.
https://github.com/styled-components/styled-components/issues/439

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪
