### ISSUE TITLE
How do I know if its working?

### ISSUE THREAD

**Issue by Cobwebster** [gatsbyjs/gatsby#11367]
I didn't see any explanation about how it works or what exactly it does.

Does it generate a url I can send to google to index the sitemap.xml? How can do I test to see if it worked.

Sorry for the basic questions, I didn't see any explantation. Just how to install.

**Comment by danoc** [comment]
Hi, are you referring to the Gatsby sitemap plugin?

If so, `gatsby build` should generate a `sitemap.xml` file at the root of the `public` folder that it generates. If you do `gatsby build && gatsby serve`, you should also be able to see the sitemap at `localhost:9000/sitemap.xml`.

**Comment by Cobwebster** [comment]
> Hi, are you referring to the Gatsby sitemap plugin?
> 
> If so, `gatsby build` should generate a `sitemap.xml` file at the root of the `public` folder that it generates. If you do `gatsby build && gatsby serve`, you should also be able to see the sitemap at `localhost:9000/sitemap.xml`.

Ah thanks, didn't see it until running gatsby build
