### ISSUE TITLE
implementing `onPreInit` API hook makes `cache` instance unusable

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#11369]
We create instances of `cache` on the first API that plugin implements ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/api-runner-node.js#L95 ). Initialization of `cache` also takes care of ensuring that dedicated cache directory exists ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/cache.js#L20 ).

When there is no `.cache` directory / or no saved redux state we wipe `.cache` directory ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/index.js#L179-L190 - `oldPluginsHash` is empty)

This happens after `onPreInit` API hook, so if plugin implement that API, it's possible that dedicated cache directory get's deleted and not recreated (even if plugin isn't `cache` in that API hook). This make subsequent usage of `cache` unusable - it doesn't error out, and just silently doesn't persist anything.

Potential fixes:
 1. Don't try to instantiate `cache`s for `onPreInit` hook (potentially pass dummy `cache` object that throws with meaningful error to not use `cache` functions in that hook as this is before we fully initialize `.cache` directory)
 2. Force re-create `cache`s after `.cache` directory initialization - it might be confusing if user would use `cache` in `onPreInit` as all data would just disappear.

**Comment by vladar** [comment]
A quick repro:

Create a site with this `gatsby-node.js`: https://gist.github.com/vladar/f7c5dca0f3c7a0c472c3f86c19f71656
1. Run `gatsby clean`
2. Run `gatsby-develop`, break
3. Run `gatsby-develop` (second time)

Expected result: the output of the second run contains:

```
info Testing cache
info someValue
info Setting cache
info Checking if set succesfully
info someValue
```

Actual result:

```
info Testing cache
info 
info Setting cache
info Checking if set succesfully
info someValue
```

Only the third run contains the correct output.

Also, if we remove `exports.onPreInit = (gatsbyApi, pluginOptions) => {}` from the gist above - we get the expected result.
