### ISSUE TITLE
[1.0] Question: blog post images

### ISSUE THREAD

**Issue by rstacruz** [gatsbyjs/gatsby#1138]
Hey, sorry to be bombarding you with questions, but I see that the `1.0` branch has files like:

```
docs/
  blog/ 
    gatsbygram-case-study/
      index.md
      ui-and-code.png
      template-page-screenshot.png
```

How do you make those `.png`'s show up in the final built site?

**Comment by rstacruz** [comment]
Ah, it seems to be handled by `gatsby-remark-responsive-image`.

However, this doesn't seem to work:

```html
<span class='preview'>
<img src='image.png' />
</span>
```

But this does, since gatsby-remark-responsive-image tries to look for the image markdown AST nodes:

```md
![](image.png)
```

**Comment by rstacruz** [comment]
Also, it seems to add:

```html
<div class="gatsby-resp-image-wrapper" style="z-index: -1">
```

where in typical pages, `z-index: -1` will make it invisible :P

**Comment by nicholaswyoung** [comment]
Try installing `gatsby-remark-copy-linked-files` and add it to your `gatsby-transformer-remark` plugin configuration, just under the responsive image plugin.

**Comment by rstacruz** [comment]
hmm, i got copy-linked-files in my config

**Comment by rstacruz** [comment]
## Digging deeper

- `gatsby-remark-copy-linked-files` only works for links, (eg, `[Download](reference.pdf)`) and non-gif images. It ignores images that are NOT .gif.

- `gatsby-remark-responsive-image` is the plugin that takes care of putting image files into the store (?).

I'd really like to use responsive-image, but I got a few considerations...

- It can't properly handle images inside links, eg: `[![](image.png)](http://google.com)`. This is since responsive-image adds its own link, and you can't have a link-in-a-link.

- It doesn't handle `<img>` tags (when used as HTML in your Markdown).

**Comment by KyleAMathews** [comment]
PRs accepted :-) both seem solvable?

And yeah, the two plugins are designed to be used together. Perhaps we
could add option to the copy link plugin to also copy images. Perhaps
automatically if it sees that the responsive image plugin isn't installed.

**Comment by KyleAMathews** [comment]
Also I have a TODO in the responsive image plugin about making the link
optional so yeah, doesn't need to be there in the image inside link case.

**Comment by rstacruz** [comment]
> Perhaps we could add option to the copy link plugin to also copy images. Perhaps automatically if it sees that the responsive image plugin isn't installed.

I'd suggest to avoid interactions between plugins, if possible, so they're more deterministically composable (you'll know what it would do, regardless of whether there are other plugins or not). May I suggest something like this?

```js
{ 
  resolve: 'gatsby-remark-copy-linked-files',
  options: {
    imagesPath: '!*.gif', /* only handle images that match these - (via minimatch/anymatch) */
    linksPath: '*'
  }
}
```

**Comment by iM-Durant7** [comment]
I cant get any images to load outside of the default .jpg. I don't see my webpack file to add dependencies for different file types. Where should I be adding those?

**Comment by KyleAMathews** [comment]
>I'd suggest to avoid interactions between plugins, if possible, so they're more deterministically composable

great point

On options — perhaps it should be `imagePaths` and `filePaths`?

**Comment by chiedo** [comment]
I attempted to get html `img` tags working with no success. Out of thoughts but if anyone has any ideas and wants to continue off of the work I started (if worth continuing), feel free:

**What did I try?**

- I added `cheerio` to the [package.json](https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby-remark-responsive-image/package.json)
- I updated [this file](https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby-remark-responsive-image/src/index.js) with the following:

**Before:**

```
var imageNodes = select(markdownAST, "image");
```

**After:**

```
  var $ = require('cheerio');
  var imageNodes = select(markdownAST, "image");
  var rawHtmlImageNodes = select(markdownAST, "html").filter((node) => {
    return node.value.startsWith("<img");
  });

  for(var node of rawHtmlImageNodes) {
    var formattedImgTag = $.parseHTML(node.value)[0].attribs;
    formattedImgTag.url = formattedImgTag.src;
    formattedImgTag.type = 'image';
    formattedImgTag.position =  node.position;

    imageNodes.push(formattedImgTag);
  }
```

**Comment by KyleAMathews** [comment]
@chiedo did you add `gatsby-remark-responsive-images` to your site's gatsby-config.js?

**Comment by chiedo** [comment]
@KyleAMathews yep. Works perfectly with this

```
![](image.png)
```

Doesn't work with this

```
<img src='image.png' />
```

**Comment by KyleAMathews** [comment]
Oh right :-) 

You're on the right path.

The algorithm for supporting image tags in addition to markdown images would be something like:

1. select for img html tags (you're doing this)
2. find the linked File node
3. if there's a linked File node, create a responsive version of the image (can reuse the code for doing this with markdown images).
4. replace the original image element with our new responsive version. Again can use the same HTML code as for markdown images.

**Comment by chiedo** [comment]
Awesome thanks @KyleAMathews 

I'll try to implement the rest of it.

I'm going to revisit on a fresh mind. I just hit that point where I'm doing things that don't make sense anymore haha

**Comment by chiedo** [comment]
So the reason I hit a massive roadblock yesterday is because the plugin doesn't accept gifs. I was working with a gif file for my testing haha.

What's the reasoning behind not treating gif files as images?

**Comment by chiedo** [comment]
Woohoo, got the `<img>` tags working. Needed to use Object.assign to update my object in place. I was creating a new object which is why my changes weren't applying. Will pull request shortly.

**Comment by chiedo** [comment]
Pull request created

https://github.com/gatsbyjs/gatsby/pull/1283

**Comment by chiedo** [comment]
Also applied the same fix to the copy-links plugin https://github.com/gatsbyjs/gatsby/pull/1285

**Comment by Antoine007** [comment]
Could `gatsby-transformer-sharp` accept `.gif` at some point?! It's almost 2018 guys 😂

**Comment by nicholaswyoung** [comment]
@Antoine007 [`libvips`](https://github.com/jcupitt/libvips/issues/235) doesn't support `gif images.

Perhaps you could write a plugin with imagemagick to do roughly the same thing. (The [code is relatively easy to understand,](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-sharp/src) and the Gatsby team is generally friendly and helpful.)

**Comment by KyleAMathews** [comment]
@Antoine007 yeah, would love another transformer added that can convert gifs!

Closing this issue as it's old and served its purpose
