### ISSUE TITLE
Cannot get sass loader working

### ISSUE THREAD

**Issue by ericterpstra** [gatsbyjs/gatsby#114]
I cannot figure out how to get sass-loader working with Gatsby.  All I get are tons of errors (client side).

My environment:
* OS X El Capitan
* Node 0.5.4
* NPM 3.3.12
* Gatsby 0.7.7 (master)

Here is my gatsby.config.js

```
module.exports = function(config, env) {

    config.removeLoader('css');

    config.loader('sass', function(cfg) {
        cfg.test = /\.scss$/;
        cfg.loader = 'style!css!scss';
        return cfg;
    });

    return config;
}
```

I installed `sass-loader` and it complained about missing peer dependencies (node-sass and webpack) so I did `npm install node-sass webpack`.  Then it complained about a missing scss module, so I installed `scss` from npm as well.

I created a folder in my root called 'scss' and have 'scss/style.scss'.  In `pages/_template.jsx` I have `require (../scss/style.scss);`

When starting `gatsby develop` it starts OK.  Navigating to 0.0.0.0:8000 creates a huge pile of errors in the browser console...

https://gist.github.com/ericterpstra/9a51e28a7c976be316a1

I'm new to webpack, so not sure if it's a gatsby/webpack issue, or something I'm doing wrong.

Any help is appreciated. Thanks

**Comment by KyleAMathews** [comment]
@ericterpstra hey sorry about the lousy experience. Sass is such a common requirement that I added it to Gatsby proper so it should just work now in the latest release (0.8)
