### ISSUE TITLE
[site-showcase] Blank page when visiting and navigating back

### ISSUE THREAD

**Issue by krismorf** [gatsbyjs/gatsby#11405]
## Description

In Gatsby Showcase when the user clicks on 'Visit site' and navigates back, a wild blank page appears. 

### Steps to reproduce

1. https://www.gatsbyjs.org/showcase
2. Click any site
3. Click 'Visit site'

### Expected result

When clicking back user should return to the showcase, although it would be a better if the page opened in a new window.

### Environment

All browsers

**Comment by sidharthachatterjee** [comment]
Thank you for reporting this @krismorf 

This is a known issue and documented at https://github.com/gatsbyjs/gatsby/issues/10727

I'm closing this for now since it is a duplicate but please feel free to follow along there!
