### ISSUE TITLE
[gatsby-source-filesystem & gatsby-source-wordpress] Wordpress Media with UTF-8 URL skipped without error

### ISSUE THREAD

**Issue by wezzle** [gatsbyjs/gatsby#11429]
## Description

The Wordpress REST API does not URL encode UTF-8 characters. As a result the gatsby-source-filesystem plugin does not download the file because of this check:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L345
```javascript
...
  if (!url || isWebUri(url) === undefined) {
    // should we resolve here, or reject?
    // Technically, it's invalid input
    return Promise.resolve()
  }
...
```

I'm not sure where the problem should be fixed. The following options could result in a solution:
- Tell the Wordpress team to URL encode Media filenames (not likely)
- Have gatsby-source-wordpress URL encode Media URLs (only the filename, not the entire URL, so with regex?)
- Replace the valid-url package in gatsby-source-filesystem to something that does validate UTF-8 URLs (could cause other issues?)

### Steps to reproduce

Upload an image to Wordpress with a UTF-8 character in it. For example: `random-filename™.jpg` (notice the Trademark). Run the gatsby build step and check the `.cache/gatsby-source-filesystem` folder for an image with the md5 hash of the full Media URL. 

Or if you use gatsby-plugin-sharp query in GraphQL for:
```
...
some_image_field {
  file: localFile {
    sharp: childImageSharp {
      fluid(maxWidth: 600, quality: 60) {
        ...GatsbyImageSharpFluid_withWebp
      }
    }
  }
}
...
```
and have `some_image_field.file.sharp` throw an error because `.sharp` is missing.

### Expected result

File should be there or at least the build process should error telling you the image could not be downloaded.

### Actual result

No image, only an error in the front-end if you try to access the image.

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Shell: 3.0.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.12.0 - ~/.nvm/versions/versions/node/v10.12.0/bin/node
    Yarn: 1.10.1 - ~/.nvm/versions/versions/node/v10.12.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/versions/node/v10.12.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0.2
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.47 => 2.0.55 
    gatsby-image: ^2.0.20 => 2.0.20 
    gatsby-paginate: ^1.0.16 => 1.0.16 
    gatsby-plugin-catch-links: ^2.0.9 => 2.0.9 
    gatsby-plugin-core-js: ^1.0.2 => 1.0.2 
    gatsby-plugin-extract-schema: ^0.0.4 => 0.0.4 
    gatsby-plugin-force-trailing-slashes: ^1.0.4 => 1.0.4 
    gatsby-plugin-google-fonts: ^0.0.4 => 0.0.4 
    gatsby-plugin-gtag: ^1.0.4 => 1.0.4 
    gatsby-plugin-layout: ^1.0.3 => 1.0.9 
    gatsby-plugin-lodash: ^3.0.2 => 3.0.2 
    gatsby-plugin-manifest: ^2.0.4 => 2.0.10 
    gatsby-plugin-netlify-cache: ^1.0.0 => 1.0.0 
    gatsby-plugin-offline: ^2.0.19 => 2.0.20 
    gatsby-plugin-page-transitions: ^1.0.7 => 1.0.7 
    gatsby-plugin-preact: ^2.0.5 => 2.0.7 
    gatsby-plugin-prefetch-google-fonts: ^1.0.11 => 1.0.11 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.2 
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-remove-trailing-slashes: ^2.0.6 => 2.0.6 
    gatsby-plugin-resolve-src: ^1.1.4 => 1.1.4 
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.3 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.3 => 1.0.3 
    gatsby-source-filesystem: ^2.0.8 => 2.0.9 
    gatsby-source-trustpilot: ^0.0.46 => 0.0.46 
    gatsby-source-wordpress: ^3.0.1 => 3.0.15 
    gatsby-transformer-sharp: ^2.1.1 => 2.1.8 
```

**Comment by wezzle** [comment]
For those looking for a quick fix, add the following to your theme or plugin in Wordpress:

```php
add_filter('wp_get_attachment_url', 'encode_attachment_url');
function encode_attachment_url($url) {
    $filename = basename($url);
    $encoded = urlencode($filename);
    return str_replace($filename, $encoded, $url);
}
```

**Comment by Ontopic** [comment]
What's the status on this? We're experiencing the same issue.

**Comment by luukdv** [comment]
Doesn't seem to be stale.
