### ISSUE TITLE
Azure Pipelines failing for new PRs

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#11421]
## Description

Windows CI builds are failing for new PRs since yesterday. See https://github.com/gatsbyjs/gatsby/pulls, or a specific example at https://github.com/gatsbyjs/gatsby/pull/11409/checks?check_run_id=56525556

### Steps to reproduce

Create a new PR to the Gatsby repo.

### Expected result

Windows CI tests should run, and pass or fail appropriately.

### Actual result

Windows CI tests fail to run with an error about parsing [azure-pipelines.yml](https://github.com/gatsbyjs/gatsby/blob/master/azure-pipelines.yml), however this file hasn't changed since November.

Reported error is:

```
/azure-pipelines.yml (Line: 26, Col: 21): Unrecognized value: 'parameters'. Located at position 39 within expression: format('TestRun {0} $(node_version)', parameters.name). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996
```

Possibly related issue: https://github.com/MicrosoftDocs/azure-docs/issues/13871

### Environment

N/A

**Comment by m-allanson** [comment]
@vagisha-nidhi as you very kindly helped us out with the config before, I was wondering if you had any insights on how we could investigate this issue?

**Comment by pieh** [comment]
Here's test PR https://github.com/gatsbyjs/gatsby/pull/11420 that just removed `testRunTitle` optional field that references `parameters` and everything seems to work with this change

**Comment by sidharthachatterjee** [comment]
Maybe related — https://github.com/MicrosoftDocs/azure-docs/issues/13871
