### ISSUE TITLE
[1.0] Question: why can you use graphql in templates?

### ISSUE THREAD

**Issue by rstacruz** [gatsbyjs/gatsby#1143]
The 1.0 boilerplate has this in template pages:

```js
export const pageQuery = graphql`
  query MyQuery($slug: String!) {
    ..
  }
`
```

But linters will complain here:

```
'graphql' is not defined.
```

True enough, when you try to do see what `graphql` is, it's not defined:

```js
console.log(graphql)
// => undefined
```

How does this sorcery work?

**Comment by 0x80** [comment]
The sources are processed with Babylon in [file-parser.js](https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby/src/internal-plugins/query-runner/file-parser.js) and the queries are extracted from the AST in [query-compiler.js](https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby/src/internal-plugins/query-runner/query-compiler.js)

**Comment by jquense** [comment]
yeah the down and dirty reason it works is that the queries are _removed_ from the source code before they are run.

**Comment by KyleAMathews** [comment]
Several people have asked about this — perhaps we just need to make sure this is covered in the tutorial + GraphQL docs so people aren't confused? I remember being confused for similar reasons back in the day when I first used Relay :-)

**Comment by bradennapier** [comment]
Seems like what you really need is an eslint plugin so people aren't having to make a bunch of comments or remove their linting to support Gatsby without a bunch of errors everywhere.

**Comment by jlengstorf** [comment]
I just ran into this question while setting up ESLint, so I took a crack at expanding the tutorial to explain why this doesn't explode in #2965. Someone who understands this better should probably review pretty closely, though, because I only _sorta_ get how this works. 😅

**Comment by KyleAMathews** [comment]
Closing this as there's another issue about including a custom gatsby eslint plugin https://github.com/gatsbyjs/gatsby/issues/2446#issuecomment-336491690
