### ISSUE TITLE
gatsby-plugin-manifest doesn't show home screen icon in latest version

### ISSUE THREAD

**Issue by alisonjoseph** [gatsbyjs/gatsby#11458]
I was pulling out my hair trying to get `gatsby-plugin-manifest` to show my "add to home screen" icon on my phone with version `2.0.11` and it wasn't working. Changed to `2.0.2` (which the gatsby site is using) and it works fine.

**Comment by sidharthachatterjee** [comment]
Hey @alisonjoseph 

This could be related to a regression in `2.0.9` (https://github.com/gatsbyjs/gatsby/issues/10770) which was fixed in https://github.com/gatsbyjs/gatsby/pull/11203 and published in `2.0.14`

Can you update to gatsby-plugin-manifest 2.0.14 (or the latest) and give it a go?

**Comment by alisonjoseph** [comment]
Yep its working! thanks as always for the super quick response. 🥳
