### ISSUE TITLE
[1.0] Responsive images: ignore SVG's

### ISSUE THREAD

**Issue by rstacruz** [gatsbyjs/gatsby#1145]
I think SVG's should be ignored from the responsive images pipeline. They should be responsive by it's default nature, shouldn't they? :)

```md
![](example.svg)
```

**Comment by KyleAMathews** [comment]
True! :-) Could you make a PR to exclude it like gifs? And make the copy-link plugin copy over svgs.

**Comment by fk** [comment]
I got some time tonight and can give that a go in an hour or so! 👋

**Comment by fk** [comment]
@KyleAMathews This can be closed, sorry for not doing so in the commit message.
