### ISSUE TITLE
[gatsby-transformer-remark] TOC depth?

### ISSUE THREAD

**Issue by andrewcroce** [gatsbyjs/gatsby#11452]
## Summary
Is it possible to set the table of contents depth with gatsby-transformer-remark?

### Environment (if relevant)

  System:
    OS: macOS 10.14.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.10.1 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.81
    Firefox: 61.0.2
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.76 => 2.0.99 
    gatsby-image: ^2.0.20 => 2.0.28 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.14 
    gatsby-plugin-offline: ^2.0.16 => 2.0.21 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5 
    gatsby-plugin-sass: ^2.0.7 => 2.0.7 
    gatsby-plugin-sharp: ^2.0.14 => 2.0.18 
    gatsby-remark-autolink-headers: ^2.0.12 => 2.0.12 
    gatsby-remark-toc: ^1.2.0 => 1.2.0 
    gatsby-source-filesystem: ^2.0.17 => 2.0.18 
    gatsby-transformer-remark: ^2.2.0 => 2.2.1 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.12 
  npmGlobalPackages:
    gatsby-cli: 2.4.8

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @andrewcroce 

Currently, this isn't possible but should be pretty easy to implement. `gatsby-transformer-remark` uses `mdast-util-toc` under the hood to create the table of contents and this takes a [maxDepth](https://github.com/syntax-tree/mdast-util-toc#optionsmaxdepth) parameter

It should be pretty easy to add a new option called `maxDepth` in `gatsby-transformer-remark` that is forwarded to `mdast-util-toc` in https://github.com/gatsbyjs/gatsby/blob/9b447a67bd7991d09e82933af49624e326a35b88/packages/gatsby-transformer-remark/src/extend-node-type.js#L280

Would you like to add this? We would love to accept a PR adding support for this!

**Comment by pieh** [comment]
Hey, there is open PR for it - https://github.com/gatsbyjs/gatsby/pull/9814 - we could get some help in reviewing and testing it
