### ISSUE TITLE
[plugin-react-css-modules] React CSS modules don't work in production

### ISSUE THREAD

**Issue by seaneking** [gatsbyjs/gatsby#11463]
## Description

When building for production with `gatsby-plugin-react-css-modules` styles are't correctly applied. Guessing the hash that react-css-modules defaults to and the hash that Gatsby's internal CSS module setup use don't match. The extended hash used in dev works fine. 

### Steps to reproduce

1. Setup plugin-react-css-modules
2. Build site for production

### Expected result

Classes from css modules should be applied

### Actual result

Classes are generated, but styles not applied.

**Comment by seaneking** [comment]
Based on https://github.com/gatsbyjs/gatsby/blob/97c98e9cf9229369892f5fee04458c9018cd2c07/packages/gatsby/src/utils/webpack-utils.js#L201 guessing it should be `[name]--[local]--[hash:base64:5]` when in production, rather than just the hash like it currently is.

**Comment by sidharthachatterjee** [comment]
Thank you for reporting this and for the detailed info @seaneking 

New version with fix is on the way
