### ISSUE TITLE
[bug]: StaticQuery fails when `export` is used to export query

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#11477]
## Description

When a component with a `StaticQuery` exports its query, e.g.

```jsx
import React from 'react'
import { StaticQuery, graphql } from 'gatsby'

export default function Header() {
  return (
    <StaticQuery
      query={titleQuery}
      render={data => (
        <header><h1>{data.site.siteMetadata.title}</h1></header>
      )}
    />
  )
}

export const titleQuery = graphql`
  {
    site {
      siteMetadata {
        title
      }
    }
  }
`

```

Building this code will lead to the query data _not_ being injected into the component and will lead to a display of `Loading (StaticQuery)`

### Steps to reproduce

- Use the above code, _or_ check out [this repo](https://github.com/marcysutton/gatsby-site/commit/7ae73eb46dbd008494b7610d7ae98ca6116ee014#diff-76a7ceef21a0a9f68cb5ca6205d6ac57R86)

### Expected result

Query should be injected and data should be available

### Actual result

Query is not stripped, data is not available

### Fix

Not sure what the _exact_ fix is, but it almost certainly some type of AST parsing issue in [this file](https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-plugin-remove-graphql-queries/src/index.js)

**Comment by sidharthachatterjee** [comment]
_Looks_ like we need to check in https://github.com/gatsbyjs/gatsby/blob/fbb77daa7eac39c1593f808bd837d0e470f63595/packages/babel-plugin-remove-graphql-queries/src/index.js#L254 if the same tag is used in a static query before removing it
