### ISSUE TITLE
Image Names after build

### ISSUE THREAD

**Issue by frivolta** [gatsbyjs/gatsby#11479]
Hello,
I was wandering why image names after the production build changes from like "image.jpg" to `image-${id}.jpg` . Isn't a bad practice in terms of SEO? is there any way I can keep the image name?
Thanks,F.

**Comment by sidharthachatterjee** [comment]
We do to make cache busting simple

> is there any way I can keep the image name?
You can actually override this by [adding custom webpack config](https://www.gatsbyjs.org/docs/add-custom-webpack-config/) 

You could do something like this
```
exports.onCreateWebpackConfig = ({
  stage,
  rules,
  loaders,
  plugins,
  actions,
}) => {
  actions.setWebpackConfig({
    module: {
      rules: [
        {
          test: /\.(ico|svg|jpg|jpeg|png|gif|webp)(\?.*)?$/,
          use: [
            loaders.url({
              name: `${assetRelativeRoot}[name].[ext]?[hash:5]`
            })
          ],
        },
      ],
    }
  })
}

```
That'll keep the original name and _also_ add a hash for cache busting

**Comment by sidharthachatterjee** [comment]
Not sure but the above might be a good default too actually according to https://support.google.com/webmasters/answer/114016?hl=en

thoughts @pieh @DSchau?

**Comment by frivolta** [comment]
Looks great since the performance of gatsby are awesome, having a good image name / title is still a best practice. Is there any functionality reason why id (i guess is a unique id) is append to the images?
Btw thanks for the support

**Comment by sidharthachatterjee** [comment]
> Looks great since the performance of gatsby are awesome, having a good image name / title is still a best practice. Is there any functionality reason why id (i guess is a unique id) is append to the images?
> Btw thanks for the support

No functional reason per se other than having urls that can be cache busted per build

**Comment by LekoArts** [comment]
Where do you see this behavior? Gatsby doesn’t modify the filenames on local images as the hashes are stored in the folder names

**Comment by frivolta** [comment]
Sorry for the answer delay,
Actually I mean, when I deploy, those strings are appended to all images and then they are deployed in the static folder. If you inspect any image in my website for example: [www.filipporivolta.it/en](url)
the slider image is: /static/hero_1-58abed5adb2d83d3df6790e6ef4ff936.jpg, is real name is hero_1.jpg
