### ISSUE TITLE
docs(gatsby-plugin-catch-links): Make it more clear that not only markdown links are affected

### ISSUE THREAD

**Issue by cardiv** [gatsbyjs/gatsby#11485]
In the readme, only markdown is mentioned. But does this plugin work with every link inserted through `dangerouslySetInnerHtml` or equivalent?

Example: I fetch a WYSIWYG text with internal links from WordPress and that is inserted as HTML.

If not, how could I replace HTML links with the `gatsby-link` component?

**Comment by sidharthachatterjee** [comment]
@cardiv `gatsby-plugin-catch-links` adds an event listener to `window` so this should work for links from anywhere
