### ISSUE TITLE
gatsby-source-wordpress: add jwt_base_path option

### ISSUE THREAD

**Issue by rotexhawk** [gatsbyjs/gatsby#11488]
Currently gatsby-source-wordpress hardcodes the jwt token endpoint `/jwt-auth/v1/token`.  I am using https://github.com/jonathan-dejong/simple-jwt-authentication/wiki/Documentation which uses `/simple-jwt-authentication/v1/token` endpoint instead. It would be great to pass the basepath in jwt options so we can support this plugin and future plugins that use different namespace.

**Comment by wardpeet** [comment]
I'm referencing https://github.com/gatsbyjs/rfcs/pull/23 as this might be valuable for the RFC.
