### ISSUE TITLE
Publish gatsby packages as scoped package

### ISSUE THREAD

**Issue by PoiScript** [gatsbyjs/gatsby#1148]
Look like there are a lot of sub-packages (plugin/component) in gatsby 1.0: https://github.com/gatsbyjs/gatsby/tree/1.0/packages

Maybe you can publish them as [scoped package](https://docs.npmjs.com/misc/scope), like `@gatsby/gatsby` `@gatsby/link`. This looks methodical.

Angular is using this approach: https://github.com/angular/angular/tree/master/packages, as well as material components: https://github.com/material-components/material-components-web/tree/master/packages

**Comment by KyleAMathews** [comment]
I think this is an interesting approach but not necessary to do before 1.0. We can reconsider this before releasing a 2.0.

**Comment by PoiScript** [comment]
Ok, I will close this issue because it just makes a suggestion. Gatsby 1.0 is already on the way to go and not necessary for such changes.
