### ISSUE TITLE
Observing weird strings inside of generated `app.js` of a minimal project

### ISSUE THREAD

**Issue by zubko** [gatsbyjs/gatsby#1149]
For example `"/Users/zubko/bugtest/node_modules/babel-plugin-transform-object-assign/lib/index.js"`

Steps to reproduce:

```
mkdir bugtest && cd bugtest
npm init --yes
yarn add gatsby@next
mkdir -p src/pages
echo "import React from 'react'; export default ()=><p>Hello</p>" > src/pages/index.js
gatsby build
cat public/app*.js

```

I'm including the files from my test run in case if the sequence won't reproduce the issue.

[bugtest.zip](https://github.com/gatsbyjs/gatsby/files/1067218/bugtest.zip)

Gatsby version: 
```
gatsby@next:
  resolved "https://registry.yarnpkg.com/gatsby/-/gatsby-1.0.0-alpha.22.tgz#af661798320126c24ceb48ed1aac9bd698e5cb2a"
```

Gatsby CLI: `1.0.0-alpha.22`

Node.js version: `v7.10.0`

OS version: `10.11.6 (15G1510)`

**Comment by KyleAMathews** [comment]
Yes, I've seen these too. Won't have time in near future to find the cause but thanks for bringing it up. If anyone else wants to investigate and PR a fix, please do.
