### ISSUE TITLE
Sort tagged blog post by date + add author avatar/name

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#11491]
E.g. on pages like https://www.gatsbyjs.org/blog/tags/themes

<img width="715" alt="screenshot 2019-02-01 14 56 15" src="https://user-images.githubusercontent.com/71047/52154166-a1201c80-2631-11e9-84f1-2abc5806edf1.png">

https://github.com/gatsbyjs/gatsby/blob/master/www/src/templates/tags.js

**Comment by Saifadin** [comment]
Would like to take this ✋🏽

**Comment by jlengstorf** [comment]
Thanks @Saifadin!

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by Saifadin** [comment]
Is this how you imagined it @KyleAMathews?

<img width="1010" alt="screenshot 2019-02-02 at 10 39 49" src="https://user-images.githubusercontent.com/1507057/52162598-f2361c00-26d6-11e9-9af4-5b169f8afa7b.png">
