### ISSUE TITLE
Hot module replacement not working in IE

### ISSUE THREAD

**Issue by saranshkataria** [gatsbyjs/gatsby#11495]
## Description

I get a console error: webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools

### Steps to reproduce

1. Create new project
2. Run gatsby develop
3. open IE
4. (warning shows in console)

### Expected result

HMR should work in IE

### Actual result

HMR is not working

**Comment by saranshkataria** [comment]
Seems like event-source-polyfill needs to be added to the project and then an entry needs to be made in the webpack config for importing it before importing webpack-hot-middleware/client. If I am on the right track, would like to create a PR for it

**Comment by sidharthachatterjee** [comment]
So isn't supported on IE or Edge according to https://caniuse.com/#feat=eventsource

@saranshkataria Thank you for the debugging on this. We'd love to receive a PR!

**Comment by JodiWarren** [comment]
This seems to have regressed at some point. In IE11, I get the same message as in the original post: `webpack-hot-middleware's client requires EventSource to work`. I haven't yet worked out whether this is an issue upstream or in Gatsby's implementation.

**Comment by sidharthachatterjee** [comment]
@JodiWarren Interesting. Let me reopen this if that's the case. 

> I haven't yet worked out whether this is an issue upstream or in Gatsby's implementation.

Do let us know if you manage to work this out!

**Comment by chandlervdw** [comment]
> This seems to have regressed at some point.
 
+1 this polyfill no longer works
