### ISSUE TITLE
gatsby info --clipboard gives errors on Windows 10

### ISSUE THREAD

**Issue by saranshkataria** [gatsbyjs/gatsby#11496]
## Description

I ran the gatsby info --clipboard command on command line for an issue I was reporting and got a bunch of errors stating " The system cannot find the path specified."

### Steps to reproduce

Create project, cd into directory, run gatsby info --clipboard

### Expected result

No errors should be present in output

### Actual result

`  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.107 => 2.0.107

error The system cannot find the path specified.

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [v8.15.0]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:4970

  - envinfo.js:1 Object.copySync
    [v8.15.0]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:66948

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [v8.15.0]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:48777

  - envinfo.js:1
    [v8.15.0]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46934

  - envinfo.js:1 Promise.all.then.e
    [v8.15.0]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46949

  - util.js:16 tryCatcher
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

error UNHANDLED REJECTION

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [v8.15.0]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:4970

  - envinfo.js:1 Object.copySync
    [v8.15.0]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:66948

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [v8.15.0]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:48777

  - envinfo.js:1
    [v8.15.0]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46934

  - envinfo.js:1 Promise.all.then.e
    [v8.15.0]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46949

  - util.js:16 tryCatcher
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [v8.15.0]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18
`

### Environment

Error in this section itself

**Comment by gobeli** [comment]
It seems like the maintainers of [envinfo](https://github.com/tabrindle/envinfo) [removed the clipboard functionality](https://github.com/tabrindle/envinfo/issues/83) because it was too hard to maintain and failed on windows and other systems. maybe it would be a good idea to remove the --clipboard flag from gatsby-cli as well...

**Comment by sidharthachatterjee** [comment]
Thank you for reporting this @saranshkataria 

@gobeli Removing it would be a breaking change for us as well 😞 

Are there any alternatives to `envinfo` that work well on all platforms?

**Comment by saranshkataria** [comment]
still waiting for a possible solution

**Comment by saranshkataria** [comment]
@sidharthachatterjee does [envinfo](https://github.com/tabrindle/envinfo) look like a good alternative?

**Comment by DSchau** [comment]
@saranshkataria that's actually what we use.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/create-cli.js#L5

A fix here would be to disallow the `--clipboard` flag when the OS is windows perhaps? Is it true that this seems to happen on all Windows machines?

**Comment by saranshkataria** [comment]
From what I see, they have decided to remove --clipboard altogether and recommend using clipboard-cli or clipboardy instead

**Comment by sidharthachatterjee** [comment]
@saranshkataria Moved it over to `clipboardy` in https://github.com/gatsbyjs/gatsby/pull/13212

While this shouldn't fix the issue automatically (envinfo was using clipboardy internally before they dropped support in v6) it should enable us to diagnose the potential issue in clipboardy and open an issue/contribute a fix upstream

Can you test this with `npm i gatsby-cli@clipboardy` and post a log and open an issue in https://github.com/sindresorhus/clipboardy?
