### ISSUE TITLE
Odd rendering issue in IE11, Safari, and Firefox - extra component

### ISSUE THREAD

**Issue by mikeriley131** [gatsbyjs/gatsby#11504]
## Description

In IE11, Firefox, and Safari I sometimes get a component that does not exist in my code. It's always a duplicate of the first component inside of `<main>` but it gets the class from a component further down the page (in this case, `class='ad'`, which contains a `video` element. In IE11 I sometimes get it on initial load, but almost always get it on refresh. In Safari and FF, it takes a bunch of refreshing before I get it.

### Steps to reproduce

1. Open https://pointsforpies.dominos.com/ in IE11. Refresh once or twice if you don't see an incorrectly styled duplicate of the first component after the header.

### Expected result

There should be no extra duplicate of the first component after the header with the wrong class name. See the same page in Chrome for the site without the error.

### Actual result

A duplicate of the first component inside of `<main>` but it gets the class from a component further down the page (in this case, `class='ad'`, which contains a `video` element.

### Environment

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v9.11.1/bin/npm
  Browsers:
    Chrome: 72.0.3626.81
    Firefox: 65.0
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.62 => 2.0.67
    gatsby-image: ^2.0.22 => 2.0.25
    gatsby-plugin-accessibilityjs: ^1.0.3 => 1.0.3
    gatsby-plugin-google-tagmanager: ^2.0.7 => 2.0.7
    gatsby-plugin-manifest: ^2.0.11 => 2.0.12
    gatsby-plugin-offline: ^2.0.18 => 2.0.19
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.4
    gatsby-plugin-remove-trailing-slashes: ^2.0.6 => 2.0.6
    gatsby-plugin-sass: ^2.0.7 => 2.0.7
    gatsby-plugin-sharp: ^2.0.14 => 2.0.15
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3
    gatsby-source-filesystem: ^2.0.10 => 2.0.12
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.3
```

**Comment by sidharthachatterjee** [comment]
So I can definitely see this happening on Safari

**Comment by mikeriley131** [comment]
Hi @Kevin-Hamilton and @sidharthachatterjee. Thanks for the insights and suggestions.

Unfortunately adding keys to the components did not have any effect. The content should be identical on both the server and the client. There is nothing be added on the client that doesn't already exist on the server. All of the components and pages are stateless functional components.

Any chance you have any other ideas or suggestions?
