### ISSUE TITLE
Please update express-graphql@0.6.12 and graphql-tools@3.1.1 eslint-plugin-graphql@2.1.1 warns about peer dependency graphql

### ISSUE THREAD

**Issue by JustFly1984** [gatsbyjs/gatsby#11507]
If I'm `npm i` my app with `graphql@0.13.2` I have this dependency issues with gatsby sub-dependencies:
```
npm WARN eslint-plugin-graphql@2.1.1 requires a peer of graphql@^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-remove-graphql-queries@2.5.4 requiresa peer of graphql@^14.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-skip-limit@2.0.5 requires a peer of graphql@^14.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN relay-compiler@2.0.0 requires a peer of graphql@^14.1.0 but none is installed. You must install peer dependencies yourself.
```

if I'm `npm i` my app with `graphql@14.1.1` I have next sub-dependency issues
```
npm WARN express-graphql@0.6.12 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-graphql@2.1.1 requires a peer of graphql@^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@3.1.1 requires a peer of graphql@^0.13.0 but none is installed. You must install peer dependencies yourself.
```
current versions of this dependencies: 
express-graphql@0.7.1 - safe to update
graphql-tools@4.0.4  - safe to update
eslint-plugin-graphql@3.0.3 - need to be tested

**Comment by Timothy-Guyon** [comment]
I am having similar issues
```
npm install --save gatsby-plugin-typography
npm WARN eslint-plugin-graphql@2.1.1 requires a peer of graphql@^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN express-graphql@0.6.12 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-plugin-emotion@4.0.3 requires a peer of @emotion/core@^10.0.5 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@3.1.1 requires a peer of graphql@^0.13.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by pxlla** [comment]
I'm chiming in too...

`npm WARN eslint-plugin-graphql@2.1.1 requires a peer of graphql@^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN express-graphql@0.6.12 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN graphql-tools@3.1.1 requires a peer of graphql@^0.13.0 but none is installed. You must install peer dependencies yourself.`

**Comment by sirojinadias** [comment]
Similar problem :
`npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN eslint-plugin-graphql@2.1.1 requires a peer of graphql@^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN express-graphql@0.6.12 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@3.1.1 requires a peer of graphql@^0.13.0 but none is installed. You must install peer dependencies yourself.
`

**Comment by DewiEJ** [comment]
Similar problem

```
npm install --save node-sass gatsby-plugin-sass
npm WARN eslint-plugin-graphql@2.1.1 requires a peer of graphql@^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN express-graphql@0.6.12 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@3.1.1 requires a peer of graphql@^0.13.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by millette** [comment]
We all see the same warnings, no need to keep repeating here, thanks.

**Comment by lakerphan4life** [comment]
Any solution found? I keep running into these issues when trying to create a gatsby project

**Comment by millette** [comment]
Progressing in (either) #11512 and #11568

**Comment by thomasryu** [comment]
Any progress on this issue? `babel-plugin-remove-graphql-queries` not working properly breaks both my project's Jest tests and Storybook stories :(

**Comment by DSchau** [comment]
@thomasryu could you explain how this breaks functionality? This is a warning--it shouldn't impact underlying functionality.

**Comment by thomasryu** [comment]
@DSchau sorry for the delay. I've recently updated Gatsby in order to use `useStaticQuery`.

**Before** the update, I was already using the standard `StaticQuery` to load images into my components, and my jest tests (simple render tests) and Storybook stories were working fine.

**After** the update, it seems Gatsby is unable to remove GraphQL queries inside components after the update, the complain received is the following: 
```
It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away,. Unfortunately, something went wrong and the query was left in the compiled code.
```

I am assuming this is a problem with `babel-plugin-remove-graphql-queries`.

**Comment by ramusbucket** [comment]
@JustFly1984  @Timothy-Guyon  @pxlla,  I'm on ` Gatsby v2.4.8` and still facing issues. Linked issue above by @millette; does not seem to solve my problems. Thank you guys for your hard work on this awesome project.

**Comment by ramusbucket** [comment]
Here are the steps I followed - 
`gatsby new hello-world`
`npm install`
`npm i gatsby-source-pg` 
added config for `gatsby-source-pg` in gatsby-config.js
`gatsby develop`

when I try to execute graphql query in playgroud (http://localhost:8000/___graphql), I get following errors - 

```
"message": "Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules directory. If different versions of "graphql" are the dependencies of other relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different versions may have different capabilities and behavior. The data from one version used in the function from another could produce confusing and spurious results.",
```
