### ISSUE TITLE
[1.0] gatsby-remark-responsive-images causes invariant violations in HTML structure

### ISSUE THREAD

**Issue by rstacruz** [gatsbyjs/gatsby#1150]
> tl;dr: use `span` instead of `div`

## The issue

gatsby-remark-responsive-images generates an HTML snippet that would cause HTML validations to fail. Browsers can interpret this differently; indeed, Firefox and Chrome have different behavior in parsing the HTML output that the plugin generates.

In certain cases, it can lead to production builds being stuck with a fatal JavaScript error that stops React from working in Chrome (see "Will it break anything?" below).

## Details

The plugin generates HTML like this:

```html
<a class="gatsby-resp-image-link">
  <div class="gatsby-resp-image-wrapper">
    <div class="gatsby-resp-image-background-image">
      ...
```

However, since this Markdown snippet:

```md
![](image.png)
```

Generates this HTML:

```html
<p><img src='' /></p>
```

The `img` (inside `p`) is subsequently replaced by `a.gatsby-resp-image-link`, which leads to a `div` being nested inside `p`.

## Why is this an issue?

`div`s can't appear inside `p`, as per HTML spec.

## Will it break anything?

In usual cases, no. Most starter sites suggest you do this:

```jsx
<div dangerouslySetInnerHTML={{__html: html}} />
```

However, I'm using [html-to-react](https://www.npmjs.com/package/html-to-react) to convert my Markdown HTML into React nodes. Which leads to this React warning:

```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>. See LessonBody > p > ... > div.
```

This setup now has a problem with production builds. Gatsby pre-renders your HTML in production. When browsers now parse this pre-rendered HTML, it will be mangled because of the invalid nesting. This will cause production sites to fail, as documented in this issue:

- https://github.com/facebook/react/issues/7093
- https://github.com/facebook/react/issues/7093#issuecomment-267178520

## Suggestion

Use `span` instead of `div`.

**Comment by rstacruz** [comment]
Also I can't seem to solve this simply by changing `div` to `span`. It seems there's another `div` being added and I don't know why that is :(

![image](https://user-images.githubusercontent.com/74385/27023794-a4e4673c-4f86-11e7-8df2-94457b24122e.png)

**Comment by KyleAMathews** [comment]
This was fixed 👍
