### ISSUE TITLE
`pathPrefix` worked, but `window.___chunkMapping` has no affected paths at index.html

### ISSUE THREAD

**Issue by denisx** [gatsbyjs/gatsby#11515]
at last gatsbyjs with standard config, and with pathPrefix

**Comment by sidharthachatterjee** [comment]
Thank you for reporting this, @denisx 

Could you please link to a minimal reproduction and add expected and actual behaviour? It typically helps to follow the issue template so that there is enough context for someone to reproduce and fix

**Comment by denisx** [comment]
wake up, need to fix
