### ISSUE TITLE
docs(blog): blog post about adding react hooks

### ISSUE THREAD

**Issue by dslemay** [gatsbyjs/gatsby#11513]
## Description

I recently converted my Gatsby Portfolio site to use React Hooks in advance of the stable release on February 4th, 2019. Blog post to include pragmatic take aways from converting to React Hooks as well as implementation within a Gatsby site. I ran into a few gotchas which are included in the draft post.

**Comment by sidharthachatterjee** [comment]
Thank you so much for opening this and for the associated blog post, @dslemay! Someone from the team will review your post soon.

**Comment by marcysutton** [comment]
Looks like this was merged, yay!  🎉
