### ISSUE TITLE
UNHANDLED REJECTION SyntaxError:  "...nodes" while json object creation

### ISSUE THREAD

**Issue by spatrame** [gatsbyjs/gatsby#1152]
I am trying to create a json object in sourceNode api in gatsby-node.js. code looks similar to below one. 
data = {
  id:123,
  **...nodes[0]**
}
But getting an error saying "UNHANDLED REJECTION SyntaxError: D:/RJS/using-drupal/gatsby-node.js: Unexpected token (103:2)" in **...nodes[0]** point. 

When I tried same code inside src folder and it working fine. Could you please let me know how can I solve it in gatsby-node.js file?

**Comment by KyleAMathews** [comment]
Gatsby doesn't run `gatsby-node.js` at the root of your file through babel. There's talk of fixing this but for now, if you want to use new JavaScript syntax, you'll need to update the version of node.js you're using. I believe node 8 supports object spread now.

**Comment by spatrame** [comment]
I have installed NodeJs v8.1.0, but still shows SyntaxError: Unexpected token ...
