### ISSUE TITLE
Styling images in a blog post with markdown remark.

### ISSUE THREAD

**Issue by orshick** [gatsbyjs/gatsby#11529]
I am in the process of converting an old site with hand-coded articles. That means there are all sorts of unique styles for images in the blog (floated left and right, containing captions, etc).

Having converted the text portions of the articles to markdown in Gatsby I ran into a wall with styling the images. Was curious if it possible to do this, or if it would it be more fruitful to abandon the markdown idea and simply make each post as a regular page.

Thanks for reading, and hints for what to look into or example repos much appreciated!

**Comment by sidharthachatterjee** [comment]
Hey @orshick 

Like @artbycrunk mentioned, if all the posts are fundamentally different in styling, you might want to _treat_ the differently styled sections as components and maybe use MDX then

On the other hand, if you can organise the different _hand styled_ pages into a couple of unique templates, then you can continue using Markdown and create pages for each template as shown in https://www.gatsbyjs.org/tutorial/part-seven/

**Comment by orshick** [comment]
Thanks guys, I will look into using MDX for the posts. It isn't terribly complicated what was 'handcoded', simply some images would be floated left or right, and some would be in the middle, things of that nature. Thing is I wanted these posts to be editable via Netlify CMS as well, so hopefully I will be able to integrate the two.
