### ISSUE TITLE
ValidationError: child "contentDigest" fails while createNode

### ISSUE THREAD

**Issue by spatrame** [gatsbyjs/gatsby#1153]
I am trying to add node to SourceNode in gatsby-node.js. Below is the code snippet. But facing below error: 

**ERROR:**
> The new node didn't pass validation
> ValidationError: child "contentDigest" fails because ["contentDigest" is required]

**Code:**
let node = { nid: 'abc', name: 'testing' }
  const assetNode = {
    id: '123',
    parent: `__SOURCE__`,
    children: [],
    internal: {
      type: 'CoolServiceMarkdownField',
      content: JSON.stringify(node),
      mediaType: `application/json`,
      contentDigest: crypto
        .createHash(`md5`)
        .update(JSON.stringify(node))
        .digest(`hex`)
    }
  }
  createNode(assetNode)

**Comment by KyleAMathews** [comment]
What does the node look like that's created?

**Comment by spatrame** [comment]
node is a json object fetching from an api or a file. For sample i just hardcoded as below
node = { nid: 'abc', name: 'testing' }

**Comment by KyleAMathews** [comment]
No sorry what is the final node that you pass to `createNode`?

**Comment by spatrame** [comment]
I took an example from below link and created above sample code(initial post). I am passing assetNode object. Let me know if i am doing something wrong here.
createNode(assetNode)

https://www.gatsbyjs.org/docs/bound-action creators/#createNode

  // Data for the node.
  ...fieldData,
  id: `a-node-id`,
  parent: `the-id-of-the-parent-node`,
  children: [],
  internal: {
    mediaType: `text/x-markdown`,
    type: `CoolServiceMarkdownField`,
    content: JSON.stringify(fieldData),
    contentDigest: crypto
      .createHash(`md5`)
      .update(JSON.stringify(fieldData))
      .digest(`hex`),
  }
}

**Comment by spatrame** [comment]
Createnode is called inside

  exports.sourceNodes = ({ boundActionCreators }) => {
// Create nodes here.
const { createNode } = boundActionCreators
}

Ref: https://www.gatsbyjs.org/docs/node-apis/#sourceNodes

**Comment by KyleAMathews** [comment]
Yes... what is `assetNode`. Please add a `console.log(assetNode)` and copy/paste what is outputted from that here.

**Comment by spatrame** [comment]
Please find the console log below,

copy gatsby files: 91.922ms
calling api handler in D:/RJS/using-drupal for api sourceNodes
{ id: '123',
  parent: '__SOURCE__',
  children: [],
  internal:
   { type: 'CoolServiceMarkdownField',
     content: '{"nid":"abc","name":"testing"}',
     mediaType: 'application/json',
     contentDigest: '4ea677a894a9b641faf30871512ff8a1' } }
**The new node didn't pass validation
ValidationError: child "contentDigest" fails because ["contentDigest" is required]**
{ id: '123',
  parent: '__SOURCE__',
  children: [],
  internal:
   { type: 'CoolServiceMarkdownField',
     content: '{"nid":"abc","name":"testing"}',
     mediaType: 'application/json',
     contentDigest: '4ea677a894a9b641faf30871512ff8a1' },
  pluginName: 'defaultSitePlugin' }
sourcing and parsing nodes: 604.204ms
building schema: 54.314ms

**Comment by KyleAMathews** [comment]
btw, if you put the code inside a code block, it's easier to read. 

https://help.github.com/articles/creating-and-highlighting-code-blocks/

Hmmm the only think I could guess is you have an old version of Gatsby installed. The node structure was changed several alphas back. Make sure you're on the latest alpha by running `npm install --save gatsby@next`.

**Comment by KyleAMathews** [comment]
Also I just put up a docs page on creating source plugins which might be helpful as well https://www.gatsbyjs.org/docs/create-source-plugin/
