### ISSUE TITLE
gatsby: Don't use fork of relay-compiler

### ISSUE THREAD

**Issue by freiksenet** [gatsbyjs/gatsby#11536]
## Description

When having literal enums that have non-string values (eg ImageCropFocus), Relay fails to print the query. 

### Expected result

Should print normally.

### Actual result

Fails with exception.

Reported upstream in https://github.com/facebook/relay/issues/2633.

We should consider downgrading back to relay-compiler 1.

**Comment by freiksenet** [comment]
Fixed in latest relay, should be tested and used.

**Comment by freiksenet** [comment]
Not fixed in Relay, we are still using Relay fork. Modifying the issue to be about that.

**Comment by m-allanson** [comment]
Should this switch from: 

`"@gatsbyjs/relay-compiler": "2.0.0-printer-fix.2",`

to: 

`"relay-compiler": "5.0.0,`

or a different version?

See [here for a similar PR](https://github.com/gatsbyjs/gatsby/pull/11759/files) if anyone would like to take this on.

**Comment by freiksenet** [comment]
Last time we patched this, it broke our builds because Relay regressed. I'll assign myself and try it again when I have time.

**Comment by TheBear44** [comment]
Currently, it shows security alert with `mem < 4.0.0`

**Comment by freiksenet** [comment]
So far this is impossible, because relay-compiler has completely broken compatibility with Gatsby, eg by not supporting complex input types. We will keep using forked relay-compiler. https://github.com/facebook/relay/blob/master/packages/relay-compiler/core/RelayParser.js#L1392 

I'll release an update to forked compiler with this library fixed.

Closing this issue because we will keep using fork in near future.

**Comment by sibelius** [comment]
now it does support complex input types

https://github.com/facebook/relay/commit/5da3be070283c6dcd42774ba33c1590db65fe3c7

**Comment by josephsavona** [comment]
@freiksenet Any interest in re-evaluating? I'm not sure exactly when you forked, but we've continually worked to improve Relay Compiler performance (especially in the last 6 months) that could potentially benefit Gatsby users.
