### ISSUE TITLE
[gatsby-dev-cli]: don't check for local package.json when configuring path to monorepo

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#11535]
When setting path to monorepo with `gatsby-dev-cli` (`gatsby-dev --set-path-to-repo /path/to/my/cloned/version/gatsby`) we shouldn't check for local `package.json`. This is confusing when doing initial setup and for that step it's also not needed to check it because we don't use it.

Here's related code - https://github.com/gatsbyjs/gatsby/blob/ad14073eac153930cb7c81451b7f9536b33baa0e/packages/gatsby-dev-cli/src/index.js#L41-L44

It should be moved after `pathToRepo` handling

**Comment by amad-person** [comment]
Would like to take this issue up!
