### ISSUE TITLE
Documentation code background

### ISSUE THREAD

**Issue by tsvetlin** [gatsbyjs/gatsby#11537]
## Summary

When reading the docks, I saw that the code sections inline with other text have a different font and background. The background color is '#fdfaf6', it's close to white, thus hardly visible. I have trouble isolating it from the text. 

### Basic example

https://www.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-repo
At this link, the shell commands should be copied from the page. These code snippets are on the same line as the text, but since the code blocks background is barely visible, it's easy to miss a command.

Current background:
![screenshot 2019-02-04 at 14 22 06](https://user-images.githubusercontent.com/15650896/52210824-6237d400-2888-11e9-9b79-a16bf4300b89.png)

Darker background:
![screenshot 2019-02-04 at 14 22 38](https://user-images.githubusercontent.com/15650896/52210834-66fc8800-2888-11e9-8054-c9ad91da12b0.png)

I think the background should be darker, so it would be more readable. for example '#ccc'

### Motivation

For me it's really hard to see which part of the text is code.  Maybe other people out there have also trouble with that. I'd happily change the css.
The background property should be changed of the code css class.

**Comment by fk** [comment]
Hey @tsvetlin! 👋
Thanks for pointing out this issue to me — I wasn't aware of it (and neither the problem itself 😞), @pieh made me aware of the problem in a direct message today.

Thank you for creating this detailed description, and glad to hear that #11538 solves the issue. 🙏 🤗
