### ISSUE TITLE
[docs]: move to async/await when appropriate

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#11548]
## Description

Now that the [Node 8 RFC has been merged](https://github.com/gatsbyjs/rfcs/pull/24) we can perform some changes to our documentation with functionality available in Node 8 and NPM 5.

Specifically, one of these is **using async/await in our documentation.**

## What should happen

All documentation examples, blog posts, tutorials, etc. should be migrated to using `async` and `await` **with a focus on simplifying and removing explicit use of a returned `Promise`**. For example, the following example is an excellent illustration of a code example that is not incredibly clear and is error-prone. Migrating to async/await drastically simplifies this

```js
exports.createPages = function createPages({ graphql }) {
  return new Promise((resolve, reject) => {
    graphql(`{
      site {
        siteMetadata {
          titel
        }
      }
    }`)
      .then(result => {
        if (result.errors) {
          return reject(result.errors)
        }

        // do something with result.data
        resolve()
      })
  })
}
```

with a fixed example like:

```js
exports.createPages = async function createPages({ graphql }) {
  const result = await graphql(`
    {
      site {
        siteMetadata {
          titel
        }
      }
    }
  `)
    .then(response => {
      if (response.errors) {
        throw new Error(response.errors)
      }
      return response
    })

  // do something with result | result.data
 
}
```

## What should _not_ happen

Migrating Promise based code in existing examples (e.g. a component with a componentDidMount lifecycle method) that is not substantially improved with async await should _not_ be added to this fix.

```jsx
import React, { Component } from 'react'

export default class IndexPage extends Component {
  componentDidMount() {
    fetch(`${process.env.API_URL}/comments`)
      .then(res => res.json())
      .then(comments => {
        this.setState({
          comments
        })
      })
  }
}
```

### Why?

We want to keep the barrier to entry low. Adding the `async` keyword does not improve comprehension in _every_ scenario. Particularly, sometimes it can be advantage to make it clear that something is _using_ a Promise in our documentation, and `async` and `await` could obfuscate this in certain scenarios.

## Examples

The [`adding-pagination`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/adding-pagination.md#example) docs example is a great illustration of using this anti-pattern that can be cleaned up with `async` and `await`.

```diff
diff --git a/bad.js b/good.js
index 1238f0c..f1e931f 100644
--- a/bad.js
+++ b/good.js
@@ -1,53 +1,51 @@
 const path = require('path');
 const { createFilePath } = require('gatsby-source-filesystem');
 
-exports.createPages = ({ graphql, actions }) => {
+exports.createPages = async ({ graphql, actions }) => {
   const { createPage } = actions;
 
-  return new Promise((resolve, reject) => {
-    resolve(
-      graphql(
-        `
-          {
-            allMarkdownRemark(
-              sort: { fields: [frontmatter___date], order: DESC }
-              limit: 1000
-            ) {
-              edges {
-                node {
-                  fields {
-                    slug
-                  }
-                }
+  const result = await graphql(
+    `
+      {
+        allMarkdownRemark(
+          sort: { fields: [frontmatter___date], order: DESC }
+          limit: 1000
+        ) {
+          edges {
+            node {
+              fields {
+                slug
               }
             }
           }
-        `
-      ).then(result => {
-        if (result.errors) {
-          reject(result.errors);
         }
+      }
+    `
+  ).then(response => {
+    if (response.errors) {
+      throw new Error(response.errors);
+    }
 
-        // ...
+    return response;
+  });
 
-        // Create blog-list pages
-        // highlight-start
-        const posts = result.data.allMarkdownRemark.edges;
-        const postsPerPage = 6;
-        const numPages = Math.ceil(posts.length / postsPerPage);
+  // ...
 
-        Array.from({ length: numPages }).forEach((_, i) => {
-          createPage({
-            path: i === 0 ? `/blog` : `/blog/${i + 1}`,
-            component: path.resolve('./src/templates/blog-list-template.js'),
-            context: {
-              limit: postsPerPage,
-              skip: i * postsPerPage
-            }
-          });
-        });
-        // highlight-end
-      })
-    );
+  // Create blog-list pages
+  // highlight-start
+  const posts = result.data.allMarkdownRemark.edges;
+  const postsPerPage = 6;
+  const numPages = Math.ceil(posts.length / postsPerPage);
+
+  Array.from({ length: numPages }).forEach((_, i) => {
+    createPage({
+      path: i === 0 ? `/blog` : `/blog/${i + 1}`,
+      component: path.resolve('./src/templates/blog-list-template.js'),
+      context: {
+        limit: postsPerPage,
+        skip: i * postsPerPage
+      }
+    });
   });
-};
+  // highlight-end
+}

```

**Comment by joshdcuneo** [comment]
@DSchau I'm happy to work on this one if you like?

Could the fixed example be further simplified by handling errors like this? Certainly .then() is less confusing than reject() but handling them syncronously might be even clearer.

```javascript
exports.createPages = async function createPages({ graphql }) {
  const response = await graphql(`
    {
      site {
        siteMetadata {
          title
        }
      }
    }
  `);

  // handle errors
  if (response.errors) throw new Error(response.errors);

  // do something with response | response.data
};
```

**Comment by KyleAMathews** [comment]
We shouldn't suggest people use async/await in browser code btw. The transform Babel does is pretty heavy.

**Comment by m-allanson** [comment]
@Dschau @joshdcuneo agreed that looks better 👍 

> We shouldn't suggest people use async/await in browser code btw. The transform Babel does is pretty heavy.

This would possibly be ok once #2114 is done? Depending on someone's individual use case

**Comment by joshdcuneo** [comment]
Heavy indeed. Just tried generating two new projects and added a function returning an old school promise to one and the same code with async await to the other and the async / await bundle was 4kb bigger.

Let me know if you would like a PR to move the gatsby-node.js API examples over to async await. Seems like the rest needs to wait?

**Comment by KyleAMathews** [comment]
Yeah, modern builds would help though what'd be really nice is a Babel plugin which compiles async/await to promises.

**Comment by amberleyromo** [comment]
Ready to close per @gatsbyjs/core
