### ISSUE TITLE
[docs]: move off of global installs and use package scripts

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#11547]
## Description

Now that the [Node 8 RFC has been merged](https://github.com/gatsbyjs/rfcs/pull/24) we can perform some changes to our documentation with functionality available in Node 8 and NPM 5.

Specifically, one of these is **moving off of global installs and migrating to `npx`.**

## What should happen

All instances of `npm install -g gatsby-cli` followed up by `gatsby <some-command>` should be replaced and unified with `npx gatsby <some-command>`.

Coupled with this issue is that any commands that are "bare" (e.g. `gatsby <some-command>`) should use the script name in `package.json`. For instance, given `gatsby develop`, that should be changed to `npm run develop`.

Both of these will isolate us from some issues re: CLI version and project version _and_ simplify set-up instructions.

This should be done in a single PR, if possible, but if multiple PRs are necessary--that's OK too!

## Examples

For instance, given the document [`docs/docs/authentication-tutorial.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/authentication-tutorial.md#building-your-gatsby-app), we should upgrade like so:

```diff
- gatsby new gatsby-auth gatsbyjs/gatsby-starter-hello-world
- cd gatsby-auth
+ npx gatsby new gatsby-auth gatsbyjs/gatsby-starter-hello-world
```

This type of change should be done to any articles, tutorials, and even blog posts in the top-level `docs` directory.

**Comment by isaac-martin** [comment]
@DSchau I'll start doing some of these tomorrow. Keep a look out for a PR, may not have time to get a PR for all of them

**Comment by joshdcuneo** [comment]
@isaac-martin @DSchau sorry, should have mentioned I have been working on this. Admittedly it will be my first PR so no guarantees. 

Submitting the PR now, I think I got all the references except in the translations. There were a few places where explanations needed to change as well as the code and that was a bit beyond me in another language.

**Comment by isaac-martin** [comment]
Thanks for the contribution @joshdcuneo
