### ISSUE TITLE
Blog handle & Shopify static page nodes

### ISSUE THREAD

**Issue by PHironaka** [gatsbyjs/gatsby#11550]
## Summary

Two suggestions for the Gatsby Source Shopify plugin:

1. For articles, would it be possible to include a handle node just like there's one for products? That way we can create detail pages for blog posts.
2. Is there a way to access static page nodes from a shop?

**Comment by isaac-martin** [comment]
I don't think pages are exposed from Shopify API.

**Comment by PHironaka** [comment]
@isaac-martin There is a pages object in the Storefront api: https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/object/page
