### ISSUE TITLE
Gatsby .env variables with Heroku

### ISSUE THREAD

**Issue by souhailmerroun** [gatsbyjs/gatsby#11559]
## Description

I want to use .env variables to configure some plugins on my Gatsby website. I've added into my gatsby-config.js file: 
```
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`
});
```

Locally, process.env contains my .env.development variables when I run gatsby develop. I also tested with gatsby build and .env.production works well. When I deploy to Heroku though, I get undefined. 

I have set up the variables on the Heroku dashboard. 

### Steps to reproduce

- Add dotenv config into gatsby-config.js
- Create variables into the Heroku Dashboard
- Deploy & test if values are working

### Expected result

I should get my .env variables available in the gatsby-config.js file.

### Actual result

I get undefined values. 

### Environment

```
Step 9/10 : RUN gatsby info --clipboard
 ---> Running in 4b4d6acea84f
  System:
    OS: Linux 4.14 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: ^2.0.114 => 2.0.114 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-google-analytics: ^2.0.13 => 2.0.13 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-source-filesystem: ^2.0.18 => 2.0.20 
    gatsby-transformer-remark: ^2.2.4 => 2.2.4 
  npmGlobalPackages:
    gatsby-cli: 2.4.9
```

**Comment by sidharthachatterjee** [comment]
Sorry for the confusion here, @souhailmerroun 

Environment variables from a `.env.development` file (your local setup) and set in the environment itself (Heroku in your example) behave slightly differently. 

You need to prefix the latter with GATSBY_ if you'd like to access them in client side JavaScript as documented in https://www.gatsbyjs.org/docs/environment-variables/

Please note that _all_ variables prefixed with GATSBY_ will be added to the client side JavaScript bundle and one must ensure that sensitive values aren't leaked in

**Comment by souhailmerroun** [comment]
Thanks for the quick reply.

Okay, so here what I did:
- Rename my variable on Heroku to GATSBY_GOOGLE_ANALYTICS_TRACKING_ID
- I have a .env file on my project that looks like [this](https://github.com/idea-to-mvp-framework/documentation/blob/master/.env.development.example)
- I've updated my [gatsby-config.js](https://github.com/idea-to-mvp-framework/documentation/blob/master/gatsby-config.js) as well

When I deploy to Heroku, I still get undefined. What am I doing wrong?

**Comment by sidharthachatterjee** [comment]
Is the .env file committed to the project? You might not need that since you're setting the env variables in the Heroku dashboard itself. 

Also, you don't need `dotenv`. Gatsby reads .env.development and .env.production automatically

**Comment by souhailmerroun** [comment]
No, I didn't commit the .env file. 

I also removed the dotenv from my [gatsby-config.js](https://github.com/idea-to-mvp-framework/documentation/commit/d236c9ff24feb2dd4276a79d528b73097f23e833)

It still not working. Locally I don't have access to variables anymore. I get undefined. On production, it not working as well. Heroku logs still show undefined.

**Comment by sidharthachatterjee** [comment]
@souhailmerroun Can you link to the logs and maybe the repo if its public? Or try to make a minimal reproduction of this that you can share?

**Comment by souhailmerroun** [comment]
Here is the repo: https://github.com/idea-to-mvp-framework/documentation

The readme.md includes how to run it locally. 

I can provide a readme.md to run on Heroku as well if needed. 

Here is the logs of the deploy on Heroku: https://gist.github.com/souhailmerroun/2cd98b8a71aeb3622d441e770f503e09

**Comment by jonniebigodes** [comment]
@souhailmerroun looks like there's a bit of confusion in here. 

In order for `gatsby-config.js` to read the environment variables. You'll need the `dotenv` package added to your project and if the .env file is in the root of the project's folder, namely:
```
|-project
  |-src
  |-data
  gatsby.config.js
  .env
```
You don't need the configuration like you were declaring it.
You only need it like so:
```javascript
 const dotenv= require('dotenv').config()
```
As you can see [here](https://github.com/jonniebigodes/gatsy_wp_featured_image/blob/remote_wp/gatsby-config.js).
Otherwise you'll need to adjust the path as mentioned in the package's npm page.
To get this to work in docker and heroku i'll refer you to this documentation [here](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml) and [here](https://devcenter.heroku.com/articles/buildpack-builds-heroku-yml) .

**Comment by souhailmerroun** [comment]
I've taken into consideration what you said @dimitrisnl & @jonniebigodes. I've updated my [gatsby-config.js](https://github.com/idea-to-mvp-framework/documentation/blob/master/gatsby-config.js). It works fine for the development environment. 

Since I'm using Docker to deploy on Heroku, I think the variables defined in Heroku Dashboard at the "Config Vars" section are not loaded or something similar. It not a GatsbyJS issue anymore I think, It how to make variables loads from Heroku using Docker deployment.  Would you happen to have any thoughts about this? 

Thanks.

**Comment by jonniebigodes** [comment]
@souhailmerroun based on the information i've provided in my previous comment, to get the variables working on a heroku docker deploy, you'll need to adjust heroku.yml to the [following](https://devcenter.heroku.com/articles/buildpack-builds-heroku-yml#setting-config-vars), otherwise it looks no matter what environment variables declared on the dashboard, the docker instance will never pick them up.

**Comment by souhailmerroun** [comment]
I tried to follow the documentation on Heroku but I still can't make it work. 
I have updated the [heroku.yml](https://github.com/idea-to-mvp-framework/documentation-website/blob/master/heroku.yml) to add some variables. I also updated the [gatsby-config.js](https://github.com/idea-to-mvp-framework/documentation-website/blob/master/gatsby-config.js) to only load .env on dev environment. 

Can you help me out?

**Comment by souhailmerroun** [comment]
I'm closing the issue since It is not a Gatsby issue but a Docker thing now. Thanks to everyone for your help.

**Comment by jonniebigodes** [comment]
@souhailmerroun sorry for not being more helpfull in this. Hope you can solve it.
