### ISSUE TITLE
Unused json and js files after gatsby build (Google pagespeed) 

### ISSUE THREAD

**Issue by Jornve** [gatsbyjs/gatsby#11563]
Hi guys!

When validating our new Gatsby website with PageSpeed Insights our score dropped significantly due to unused json and js files. Anyone had this issue before and/or know how to solve this? 

![Screenshot](https://duaw26jehqd4r.cloudfront.net/items/0G3y1C0K2I2S2f3U1L2y/Screenshot%202019-02-05%20at%2008.55.30.png?v=900aebdb)

**Comment by sidharthachatterjee** [comment]
@Jornve These warnings are displayed when some assets that are preloaded in the browser are _not_ eventually used. 

Gatsby preloads assets for pages that are linked to in the viewport — so the page loads practically instantly when the user clicks on the link. In this case, the PageSpeed Insights test is likely not navigating through to multiple pages and therefore this warning is being thrown. 

I would say that it's okay to _ignore_ these warnings but keeping this open to hear what others have to say on this issue.

**Comment by pgilad** [comment]
According to @addyosmani answer here (https://github.com/GoogleChromeLabs/preload-webpack-plugin/issues/8#issuecomment-277105884) it seems the correct method of loading assets from another page is `prefetch` and not `preload`

**Comment by KyleAMathews** [comment]
What site is this? Gatsby adds preload links to SSRed HTML for the initial critical resources. We do use prefetch for prefetching subsequent resources. 

I haven't seen this error before. How much JS are you loading initially?

**Comment by Jornve** [comment]
@KyleAMathews Here is a preview link: https://5c6a83cd7cf4c1000bf91a3f--amazing-pare-38b4d5.netlify.com/

I do have to mention that we don't have a score drop when testing with Lighthouse. For some reason these tools are not fully in sync.

**Comment by rshackleton** [comment]
Seeing the same preload warnings on PSI for my own website: https://rshackleton.co.uk/

![image](https://user-images.githubusercontent.com/13448395/53767851-ec4a7b00-3ece-11e9-94b4-afad65c9f318.png)

**Comment by jackyef** [comment]
Bump! Seeing this issue as well on my site powered by gatsby.

**Comment by ghassanmas** [comment]
+1 for having this issue as well

**Comment by lnikell** [comment]
Same for me
