### ISSUE TITLE
Weird error "SecurityError: Failed to read the 'rules' property from 'CSSStyleSheet'"

### ISSUE THREAD

**Issue by AaronBentley** [gatsbyjs/gatsby#11571]
## Description

Hey everybody 👋

I've been having a blast with Gatsby.js, however I'm now getting a weird error, namely:

**"SecurityError: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules"** 

... when using  [gatsby-background-image](https://github.com/timhagn/gbitest) and [Typography.js](https://kyleamathews.github.io/typography.js/) in all browsers **except Safari (both mobile & desktop)**.

![screenshot 2019-02-05 at 15 57 52](https://user-images.githubusercontent.com/3936200/52287024-45230400-2961-11e9-9b2b-5febda65ad05.png)

Upon initial investigation I'm guessing it's some kinda conflict with gatsby-background-image and Typography.js, but I'm not 100% sure exactly what the cause is or how best to tackle it.

### Steps to reproduce

I've created a small repo (with only the relevant components) to help reproduce/demonstrate the issue:
- Clone https://github.com/AaronBentley/gatsby-debug.git
- npm/yarn install
- run gatsby develop
- Visit http://localhost:8000 with Chrome, Firefox, Opera etc... to see the error (no error thrown in Safari).

### Expected result

I was hoping to see my glorious background image, laden with beautiful typography.

### Actual result

Site looks fine in Safari, **not fine** in any other browser that I've tested.

### Environment

**System:**
OS: macOS 10.14.2
CPU: (8) x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
Shell: 3.2.57 - /bin/bash
**Binaries:**
Node: 10.10.0 - /usr/local/bin/node
Yarn: 1.13.0 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
**Languages:**
Python: 2.7.10 - /usr/bin/python
**Browsers:**
Chrome: 71.0.3578.98
Firefox: 65.0
Safari: 12.0.2
**npmPackages:**
gatsby: ^2.0.112 => 2.0.112
gatsby-background-image: ^0.2.2 => 0.2.2
gatsby-image: ^2.0.29 => 2.0.29
gatsby-plugin-manifest: ^2.0.17 => 2.0.17
gatsby-plugin-offline: ^2.0.22 => 2.0.22
gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
gatsby-plugin-sharp: ^2.0.20 => 2.0.20
gatsby-plugin-typography: ^2.2.7 => 2.2.7
gatsby-source-filesystem: ^2.0.20 => 2.0.20
gatsby-transformer-sharp: ^2.1.13 => 2.1.13
**npmGlobalPackages:**
gatsby-cli: 2.4.8

Here's hoping someone can shed light on this issue or point me in the right direction,
Thanks in advance,
Aaron 😀

**Comment by sidharthachatterjee** [comment]
Sorry you're seeing this @AaronBentley and thank you for the detailed issue

I can reproduce this locally but removing `gatsby-background-image` seems to solve the issue. Maybe opening an issue in https://github.com/timhagn/gatsby-background-image is a good idea?

I haven't dug deep, but on first inspection it appears that the plugin tries to access `styleSheets. cssRules` and there is some kind of security violation which occurs as a result of the fix for https://bugs.chromium.org/p/chromium/issues/detail?id=775525

https://github.com/timhagn/gatsby-background-image/blob/cdb1000190eb2d63d16212a330ee9950d56b236a/src/BackgroundUtils.js#L9-L14

**Comment by AaronBentley** [comment]
Thank you for taking a look at this @sidharthachatterjee 👍

I've been researching the CORS fix you've described too and was about to open an issue over at `gatsby-background-image` when I found this [open issue already present](https://github.com/timhagn/gatsby-background-image/issues/6) which identifies the issue as a result of some Chrome extensions attempting to load CSS.

The issue appears to have been fixed (very quickly too I might add) in the latest release of `gatsby-background-image` at version 0.2.3.

Thanks again for taking the time to look at my code, will close the issue and have a good day 😎
