### ISSUE TITLE
How to deal with Gatsby site using 100k pages all editable ?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#11585]
Hi, 

I want to run a build which creates 100k pages of companies. These companies page should be editable. 
So the build should run for each modification _(Netlify hook already working)_

What happen if several users do modification at same time ? What Gatsby would build ?
Is this a good idea?

The other solution I think, We could be create these companies pages as "client page" (so not static). But we will lose the SEO feature here...

What should I do please?

@KyleAMathews @jlengstorf anyone ? 

Thanks

**Comment by andersonsantos** [comment]
Are this 100k pages of companies hosted as different websites (supporting custom domains names, etc) or they are something like LinkedIn profiles, all hosted on the same "main" website (like www.example.com/companyX/)?

**Comment by araphiel** [comment]
What will your clients use to edit data?

My thoughts on options:
- Fetch company data on the client.
- Run the site on a node server, use `gatsby serve` + [`ENABLE_GATSBY_REFRESH_ENDPOINT`](https://www.gatsbyjs.org/docs/environment-variables/#reserved-environment-variables) (not sure about the memory usage on this though)

I think the incremental build feature is still being worked on but I'm still not certain that would help your situation.


My thoughts - 
- Run the site on a node server

That sounds like a tough one.

The sheer quantity and possible access patterns make this a bit scary.
My first thought, run the site in `gatsby serve` mode with the r
My first though would be running the site via `gatsby serve` and using

The access patterns on that 
That sounds like a tough one.



First though, it using gatsby server in refresh mode
Using gatsby serve Running incremental builds over

**Comment by sidharthachatterjee** [comment]
Hey @Steffi3rd 

When you say _modification_, what is the source of the data that is consumed to create these pages? Depending on how you use that source and trigger new builds, several builds triggered at the same will run one after another.
