### ISSUE TITLE
[gatsby-plugin-remove-trailing-slashes] doesn't work with slugs

### ISSUE THREAD

**Issue by denkristoffer** [gatsbyjs/gatsby#11598]
## Description

I'm using `gatsby-plugin-remove-trailing-slashes` with https://github.com/gatsbyjs/gatsby-starter-blog — the problem is that blog post slugs still have trailing slashes which gets used in the post links. The `path` field for pages DOES have the slashes removed though.

### Steps to reproduce

Run the following query in GraphiQL

```graphql
{
  allMarkdownRemark {
    edges {
      node {
        fields {
          slug
        }
      }
    }
  }
}
```

### Expected result

```json
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "fields": {
              "slug": "/hello-word"
            }
          }
        }
      ]
    }
  }
}
```

### Actual result

```json
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "fields": {
              "slug": "/hello-word/"
            }
          }
        }
      ]
    }
  }
}
```

Notice the trailing slash

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 5.6.2 - /usr/local/bin/zsh
  Binaries:
    Node: 10.15.1 - /var/folders/sz/lcm4z71d11b6tx4dqmwvbklh0000gn/T/yarn--1549471491051-0.32397696393743036/node
    Yarn: 1.13.0 - /var/folders/sz/lcm4z71d11b6tx4dqmwvbklh0000gn/T/yarn--1549471491051-0.32397696393743036/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 65.0
    Safari: 12.0.3

**Comment by DSchau** [comment]
I think this is on the creator of the slug field to implement!

This function here -> https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/gatsby-node.js#L57

has an option `trailingSlash` that can be disabled!

**Comment by denkristoffer** [comment]
Thank you @DSchau, that's fair and works perfectly for me 🙂 I think it'd be nice DX if that option was inferred from the plugin, but I'm not well versed in Gatsby's code to implement such an idea.
