### ISSUE TITLE
fix(www): fix spacing between tags list and 'View All Tags' button on blog posts

### ISSUE THREAD

**Issue by LMulvey** [gatsbyjs/gatsby#11591]
## Description

A visual regression was introduced in #10936. There is no space between the tags and the 'View All Tags' button.

<img width="969" alt="screenshot 2019-02-05 10 04 49" src="https://user-images.githubusercontent.com/71047/52294198-7d105400-292d-11e9-9a12-394b0172bb41.png">

_Originally posted by @KyleAMathews in https://github.com/gatsbyjs/gatsby/pull/10936#issuecomment-460741722_

**Comment by sidharthachatterjee** [comment]
Thanks for this @LMulvey!

**Comment by LMulvey** [comment]
No problem! #11594 addresses and fixes this issue. Made this for consistency 😄
