### ISSUE TITLE
Netlify Deploy Fail Since new Gatsby CLI update

### ISSUE THREAD

**Issue by joebentaylor** [gatsbyjs/gatsby#11609]
Hi, today i upgraded gatsby to the latest version, and ever since then ive had major issues...

Ive had to stop using NPM as the site wont build locally anymore and had to use yarn to fix this.

But, the biggest issue now is when i run the build inside of Netlify i get this build fail:

```
10:35:15 PM:   Error: ./src/scss/app.scss
10:35:15 PM:   Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.j  s):
10:35:15 PM:   ModuleBuildError: Module build failed (from ./node_modules/css-loader/index.js  ):
10:35:15 PM:   Error: Cannot find module 'lodash.camelcase'
10:35:15 PM:       at Function.Module._resolveFilename (module.js:548:15)
10:35:15 PM:       at Function.Module._load (module.js:475:25)
10:35:15 PM:       at Module.require (module.js:597:17)
10:35:15 PM:       at require (/opt/build/repo/node_modules/v8-compile-cache/v8-compile-cache  .js:159:20)
10:35:15 PM:       at Object.<anonymous> (/opt/build/repo/node_modules/css-loader/lib/compile  -exports.js:1:79)
10:35:15 PM:       at Module._compile (/opt/build/repo/node_modules/v8-compile-cache/v8-compi  le-cache.js:178:30)
10:35:15 PM:       at Object.Module._extensions..js (module.js:664:10)
10:35:15 PM:       at Module.load (module.js:566:32)
10:35:15 PM:       at tryModuleLoad (module.js:506:12)
10:35:15 PM:       at Function.Module._load (module.js:498:3)
10:35:15 PM:       at Module.require (module.js:597:17)
10:35:15 PM:       at require (/opt/build/repo/node_modules/v8-compile-cache/v8-compile-cache  .js:159:20)
10:35:15 PM:       at Object.<anonymous> (/opt/build/repo/node_modules/css-loader/lib/loader.  js:8:22)
10:35:15 PM:       at Module._compile (/opt/build/repo/node_modules/v8-compile-cache/v8-compi  le-cache.js:178:30)
10:35:15 PM:       at Object.Module._extensions..js (module.js:664:10)
10:35:15 PM:       at Module.load (module.js:566:32)
10:35:15 PM:       at runLoaders (/opt/build/repo/node_modules/webpack/lib/NormalModule.js:30  1:20)
10:35:15 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
10:35:15 PM:       at /opt/build/repo/node_modules/loader-runner/lib/LoaderRunner.js:367:11
10:35:15 PM:       at /opt/build/repo/node_modules/loader-runner/lib/LoaderRunner.js:172:11
10:35:15 PM:       at loadLoader (/opt/build/repo/node_modules/loader-runner/lib/loadLoader.j  s:32:11)
10:35:15 PM: Shutting down logging, 35 messages pending
```

I have no clue where to start. Someone help!!! :(

**Comment by DSchau** [comment]
Does your code depend on a dependency (`lodash.camelcase`) that isn't installed?

Are you able to build this code locally i.e. outside of Netlify?

**Comment by joebentaylor** [comment]
Not that i know of. And can build it totally fine no problems outside of netlify

**Comment by joebentaylor** [comment]
Its literally only since updating the Gatsby CLI that this has become an issue

**Comment by JustFly1984** [comment]
@joebentaylor can you run `npm ls lodash.camelcase` or `yarn list lodash.camelcase` ? it will tell you which dependency is it. Also it could help if you remove `^` from all semver of your dependencies and devDependencies, remove `package-lock.json`, `yarn.lock` and `node_modules`, run `npm i` or `yarn` again, and build locally. Possible that you have some dependencies in devDependencies, and you need to move them. Netlify could skip devDependencies installation on NODE_ENV=production.

**Comment by DSchau** [comment]
Also linking to the build history (e.g. the Netlify build logs) would be helpful, as well as providing a reproduction, e.g. a copy of the repo on Github or elsewhere where we can try to reproduce.
