### ISSUE TITLE
Uncaught Error: _registerComponent(...): Target container is not a DOM element

### ISSUE THREAD

**Issue by spatrame** [gatsbyjs/gatsby#1160]
I installed gatsby@canary.[gatsby 1.0.0-alpha.22-alpha.2d2aa0ef] 

After gatsby develop pages are not loading. It showing above error. 

Could you please let us know how do I configure target container.

**Comment by spatrame** [comment]
This got fixed by adding below div.
<div  id="___gatsby"   dangerouslySetInnerHTML={{ __html: this.props.body }}  />

**Comment by KyleAMathews** [comment]
👍
