### ISSUE TITLE
Consider integrating graphiql-explorer

### ISSUE THREAD

**Issue by kolya-ay** [gatsbyjs/gatsby#11602]
[It looks](https://github.com/OneGraph/graphiql-explorer) very useful for exploring Gatsby internals.

**Comment by sidharthachatterjee** [comment]
Hey @kolya-ay 

`graphiql-explorer` does indeed look very useful and we've discussed the possibility of adding it. I'm not sure about adding it to core but one could definitely create a plugin for this. 

Would you be interested? 🙂

**Comment by sudarshang** [comment]
I was interested in this, but after some digging around looks like when this 

https://github.com/prisma/graphql-playground/pull/943

is fixed, gatsby will have the graphiql-explorer

**Comment by m-allanson** [comment]
This would be a big DX improvement, re-opening. 

Sort-of related issue at https://github.com/gatsbyjs/gatsby/issues/14212

**Comment by DSchau** [comment]
Looks like OneGraph is working on some improvements, as well -> https://www.youtube.com/watch?v=yWjCAjpHRt0

**Comment by pieh** [comment]
PR adding graphiql-explorer support is open - https://github.com/gatsbyjs/gatsby/pull/14280

**Comment by pieh** [comment]
`gatsby@2.7.3` was published which includes graphiql-explorer
