### ISSUE TITLE
Pagination and filtering on nested properties

### ISSUE THREAD

**Issue by matthewlawson** [gatsbyjs/gatsby#11607]
## Summary

I recently built an ecommerce style site with gatsby and I had a few issues with the build times as I was inadvertently over-fetching data. I have a simple Many to Many, Category <-> Product schema setup using [foreign keys](https://www.gatsbyjs.org/docs/node-creation/#foreign-key-reference-___node). I would like to be able to paginate on the nested properties the same way I can on the top level connection

For example when creating a product page it would be nice to render some related products by querying for other products in the same category.

#### Existing query
I can currently do this with the following query. I commented where the overfetching happens.
```
{
  product(fields:{slug:{eq: $slug}}) {
    id
    category { # <- This can overfetch categories and can't be ordered if I am only interested in rendering two related categories (for example)
      name
      products { # <- This could potentially return hundreds of products
        name
      }
    }
  }
}
```
#### Proposed query
A Proposed solution is to bring the filtering / ordering / limit / skip functionality to these nested properties so a query like this could be written...
```
{
  product(fields:{slug:{eq: $slug}}) {
    id
    category(limit: 2) { 
      name
      products(limit: 12) { 
        name
      }
    }
  }
}
```

### Motivation

* Less overfetching
* A nicer way to traverse the data than writing additional queries to filter based on the foreign key eg `allProduct(limit:12, filter:{category:{name:{eq: $categoryName }}})`

Apologies if this has been mentioned before or is currently being worked on - I couldn't find anything in the issues.

**Comment by sidharthachatterjee** [comment]
cc @freiksenet

**Comment by cryic** [comment]
I'd like to reopen this issue and continue the discussion, as this is something I've run to as well.

Being able to `limit` a nested field would be a great help.

This would be done by making any collection a `Connection` type?

Is there any best-practice or query convention that would make the OP's 'Proposed Query' _not_ a good idea to pursue?

**Comment by cryic** [comment]
I ended up changing my project a little, so I only ended up need child data a single layer deep.

Instead of requesting the nested relationship, I ended up breaking out the nested data into separate, aliased queries. I could then filter/limit those queries.

So originally, my query was something like:
```
{
  query ($id: String!) {
    topic(id: {eq: $id}) {
      id
      slug
      name
      blog_posts { //really only need the first 5
        slug
        title
      }
    }
  }
}
```

I pulled out the nested `blog_posts` to:
```
{
  query ($id: String!) {
    currentTopic: topic(id: {eq: $id}) {
      id
      slug
      name
    }

    relatedBlogPosts: blogPosts(
      filter: {
        topic: {id: {eq: $id}}
      },
      limit: 4
    ) {
      slug
      title
    }
  }
}
```

That said, it would be great to have a single, top-down query that's could help OP's more deeply nested data.

**Comment by matthewlawson** [comment]
> @cryic @matthewlawson Have you found any work arounds for this?

I'm not actively developing anything with Gatsby currently so I'm not familiar with any new query features, but the best I could do at the time was basically what I mentioned in my original issue and what @cryic has done above. Adding an additional query and filtering on the foreign key there:

`allProduct(limit:12, filter:{category:{name:{eq: $categoryName }}})`

**Comment by me4502** [comment]
Doing it that way involves creating extra complexity and links in the data. 

Also, it doesn't work very well when you're querying for multiple of the parent items and then filtering the inner item.

I've had a bit of a look into how to implement this, however, I don't completely understand the Gatsby GraphQL type creation process.

**Comment by zce** [comment]
Four months have passed. Are there any updates?
