### ISSUE TITLE
Can't get my images from markdown frontmatter to display - "Cannot read property 'src' of undefined

### ISSUE THREAD

**Issue by danboyle8637** [gatsbyjs/gatsby#11623]
Here is my query and how I'm rendering a card component... Using images because my preview did not show indenting and made it super hard to read.

![screen shot 2019-02-07 at 10 37 41 am](https://user-images.githubusercontent.com/26289514/52422650-7a943280-2ac4-11e9-8a78-b59edece1156.png)

When I console log pic I I get the correct image object... but when I pass it as a prop and try to display it, I get the error TypeError: Cannot read property 'src' of undefined.

![screen shot 2019-02-07 at 10 35 46 am](https://user-images.githubusercontent.com/26289514/52422559-43be1c80-2ac4-11e9-8778-ebe0d5992fba.png)

Here is my card component that is displaying this data...

![screen shot 2019-02-07 at 10 38 40 am](https://user-images.githubusercontent.com/26289514/52422689-8f70c600-2ac4-11e9-8273-2a05fa7982ab.png)

PictureWrapper is a styled Gatsby Image using styled components so I can give it a border radius and the exact width I want.

When I take the picture out of the component, everything displays correctly. So I'm not sure why the image is not. 

Gatsby version: 2.0.76

**Comment by t2ca** [comment]
Try

`const PictureWrapper = styled(Img)`

**Comment by danboyle8637** [comment]
@t2ca  Thanks. I imported Image from 'gatsby-image' 

I thought you can name default exports whatever you wanted. I guess I was wrong.

But then why do my images work on all my other pages where I'm just querying the image?

**Comment by sidharthachatterjee** [comment]
@danboyle8637 It _is_ a default export and you should be able to name it anything you like. I'm not sure what the issue here is but I can't seem to reproduce it. 

Can you link to a minimal reproduction if possible?
