### ISSUE TITLE
update  cheerio 1.0.0-rc.2 to 0.22.0 

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#11649]
**Need to change cheerio 1.0.0-rc.2 to 0.22.0 in gatsby deps**

## Description
see:
https://github.com/cheeriojs/cheerio/commit/e2f8436170e56190beb0dbbd284065624ca4d329

### Steps to reproduce

When i use cheerio 1.0.0-rc.2 my gatsby not running correctly with rehype-react (who use hast parsing)

I found that update to the last version cheerio@0.22.0 fix my compilation

### Environment
last gatsby

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @simonjoom 

`cheerio` isn't a gatsby dependency but looks like several gatsby  remark plugins use it. Can you post some more details of the issue and a minimal reproduction if possible? 

I see that in https://github.com/cheeriojs/cheerio/commit/e2f8436170e56190beb0dbbd284065624ca4d329 that they've reverted `1.0.0` and are back to `0.22.0` but I'm not sure if there were breaking changes between these that our plugins now depend on

**Comment by simonjoom** [comment]
i m working with cheerio 0.22.0 and it's fully supported with gatsby remark plugins .
i use all these plugin with no problem  :
     `gatsby-plugin-sharp`, 
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-lodash",
    "gatsby-plugin-sass",
     "gatsby-source-filesystem",
"gatsby-transformer-remark",
"gatsby-remark-images", 
"gatsby-remark-responsive-iframe",
  "gatsby-remark-copy-linked-files" 
"gatsby-plugin-google-analytics", 
    "gatsby-transformer-sharp",
    "gatsby-plugin-catch-links",
    "gatsby-plugin-twitter", 
      resolve: "gatsby-plugin-sitemap",
      resolve: "gatsby-plugin-manifest",
      resolve: "gatsby-plugin-feed",

In fact like described in the last commit cheerio v1.0.0 is not stable and outdated. 

About reproduction it's hard as i use a gatsby configured with inferno.

I found an issue with my gatsby repo who use inferno in development .
 Inferno use a normalisation in development mode and the component's keys produced with cheerio v1.0.0 return this error:
Encountered two children with the same key, `[object Object]`1

I spent one night to figure out (changed all deps and refreshed everything),
 with cheerio v 0.22.0 it's working without problem.

So maybe you can keep cheerio v1.0.0 for gatsby but i think from my experience it's not stable and outdated.

Regards
Simon

**Comment by DSchau** [comment]
@simonjoom circling back to this--this doesn't seem like an issue that's a problem with gatsby core.

If you'd like to resolve _one_ version of cheerio for your project you can use [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) for this use case.

In your scenario, you'd add a key to your **package.json** like so:

```json
{
  "resolutions": {
    "cheerio": "0.22.0"
  }
}
```

As far as this issue in Gatsby core, if 0.22.0 is the new "1.0.0" for cheerio, we'll make that change and "upgrade" plugins that use cheerio to accomodate this newer version, as needed.

As we've provided a remediation for your use case here, I'm going to close this out. If you'd like to discuss further, please reply and we can re-open and continue the discussion. Thanks!
