### ISSUE TITLE
[gatsby-transformer-react-docgen] - TypeScript generated docs missing properties from interface

### ISSUE THREAD

**Issue by dgutride** [gatsbyjs/gatsby#11650]
## Summary
When generating documentation from a component written in typescript, it works much better since the 3.0.3 release, but props from the interface are missing and only props set as default props are referenced.  Is there an issue to track the ongoing work to update to the latest react-docgen?

In the example below, only className and src show up in the allComponentMetadata props object (and type is missing, too).

const defaultProps = {
  className: '',
  src: ''
}
export interface MyComponentProps
  /** Additional classes added to the comp. */
  className?: string;
  /** Attribute that specifies the URL of the image. */
  src?: string;
  /** Attribute that specifies the alt text of the image */
  alt: string;
}

MyComponent.defaultProps = defaultProps;
export default MyComponent;

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
Just tried this out locally. It does seem that `gatsby-transformer-react-docgen` doesn't take props declared as interfaces into account.

**Comment by sidharthachatterjee** [comment]
On deeper inspection, it seems that react-docgen doesn't support TypeScript at the moment. The relevant issue is at https://github.com/reactjs/react-docgen/issues/325

**Comment by dgutride** [comment]
Replying to keep this open

**Comment by ColeTownsend** [comment]
Not stale
