### ISSUE TITLE
Gatsby build process is changing the JavaScript i add in the page head 

### ISSUE THREAD

**Issue by dhoulker** [gatsbyjs/gatsby#11664]
## Description

When adding JavaScript to the head of the page, i see the Gatsby Build process change the JavaScript.

### Steps to reproduce

I've copied the `html.js` file, as documented [on this page in the docs](https://www.gatsbyjs.org/docs/custom-html/).
```shell
cp .cache/default-html.js src/html.js
```

I've then added the below to the `html.js`, below my last meta tag:

```javascript
<script
  type="text/javascript"
  dangerouslySetInnerHTML={{
    __html: `
    var example = /Version\/(\S+)\s+Safari/;
    console.log(example)
    `,
  }}
/>
```

Please note the code above is an extract from a third party library, the New Relic Browser Agent, i've stripped it down to 2 lines for clarity.

For what its worth i've tested the Regex and it seems to be valid. 

### Expected result

In the rendered page i should see this:
```javascript
<script type="text/javascript">
  var example = /Version\/(\S+)\s+Safari/;
  console.log(example)
</script>
```

### Actual result
Instead i see the below, note the three missing `\`
```javascript
<script type="text/javascript">
  var example = /Version/(S+)s+Safari/;
  console.log(example)
</script>
```
This causes a JavaScript error on the page.

### Environment

  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 63.0
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.91 => 2.0.91 
    gatsby-image: ^2.0.26 => 2.0.26 
    gatsby-plugin-google-analytics: ^2.0.13 => 2.0.13 
    gatsby-plugin-manifest: ^2.0.13 => 2.0.13 
    gatsby-plugin-node-fields: ^2.0.1 => 2.0.1 
    gatsby-plugin-offline: ^2.0.21 => 2.0.21 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.17 
    gatsby-plugin-sitemap: ^2.0.5 => 2.0.5 
    gatsby-plugin-typescript: ^2.0.3 => 2.0.3 
    gatsby-source-filesystem: ^2.0.19 => 2.0.19 
    gatsby-source-wordpress: ^3.0.30 => 3.0.30 
    gatsby-transformer-remark: ^2.2.0 => 2.2.0 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.10 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
    gatsby: 2.0.0-rc.28

**Comment by harryparkdotio** [comment]
you'll need to escape the slashes, ie.

```js
`\s` // -> 's'
`\\s` // -> '\s'
```

so to get the correct js you're looking for;

```diff
+ var example = /Version\\/(\\S+)\\s+Safari/;
- var example = /Version\/(\S+)\s+Safari/;
```
