### ISSUE TITLE
request: add warnings when remark prism language not found

### ISSUE THREAD

**Issue by cdaringe** [gatsbyjs/gatsby#11667]
# problem

- typescript was not syntax highlighting, even though supported via prism.
- no errors or warnings are presented even when a failure is occurring

# reproduction

- #1917 explains the failure mode in depth, where i reached the failure by using `ts` after the triple backtick, vs typescript

# request

in the `gatsby-remark-prism`, add helpful logging rather than silently bailing:

```js
  if (!Prism.languages[language]) {
    try {
      console.log(`loading language: ${language}`)
      loadPrismLanguage(language);
    } catch (e) {
      // Language wasn't loaded so let's bail.
      // ^^ REQUEST, don't bail so fast!  log.warn(`unable to find language ${language} for highlighting. applying generic code block`)
      if (language === `none`) {
        return code; // Don't escape if set to none.
      } else {
        return _.escape(code);
      }
    }
  }
```

**Comment by pieh** [comment]
For reference - this is location of code referenced by @cdaringe - https://github.com/gatsbyjs/gatsby/blob/9fdf931f62e1e9e0ea2bebc536cdf780afee2c58/packages/gatsby-remark-prismjs/src/highlight-code.js#L9-L20

I think it makes sense to only warn if can't load language and is different than `none` (as then user opts in to not add highlighting).

This feature has potential of being very spammy so we might want to track if warning was already displayed for `language` before showing it.

**Comment by connollyf** [comment]
Hi, I'd like to try to tackle this issue. Is there a style guide for printing error messages?

**Comment by cdaringe** [comment]
hush hush @gatsbot, the issue is alive and valid

**Comment by arturfsousa** [comment]
Hey guys, I've sent a PR to add the warning #12565. Let me know if you need any changes.

Thank you 😀
