### ISSUE TITLE
Submitted and accepted Gatsby starter is not showing description on https://www.gatsbyjs.org/

### ISSUE THREAD

**Issue by bluepeter** [gatsbyjs/gatsby#11668]
See screenshot:

![screenshot-www gatsbyjs org-2019 02 09-11-53-10](https://user-images.githubusercontent.com/2158187/52525636-70f40180-2c61-11e9-916c-28daf6294cf9.png)

I recently submitted this, and it was merged. However, the description is not showing up, despite seemingly correct YAML: https://github.com/gatsbyjs/gatsby/blob/5adb2a3beb10ff9ca9fd58b351d8e6bbb0dd05a1/docs/starters.yml#L1733-L1744

What needs to be done to get the description showing? As it is, without a description, it doesn't show up for relevant searches, either.

**Comment by LekoArts** [comment]
The description for these previews is grabbed from the description field in the package.json

**Comment by bluepeter** [comment]
Thanks @LekoArts ! Will PR a close to this issue shortly.
