### ISSUE TITLE
Npm gatsby develop keeps freezing on windows

### ISSUE THREAD

**Issue by dharric** [gatsbyjs/gatsby#11665]
## Description
I just installed the default template, gatsby-starter-default, using the gatsby-cli. It gives me gatsby 2.0.118 and react 16.8. This is on windows. I am using the vs code (1.31.0) terminal, but the freezing issue also happens on the command prompt. After installation I run npm start. The web site comes up fine and gatsby at first compiles code changes without issue. After a few minutes it stops compiling and I am not able to exit the terminal using ctrl+c. It is unresponsive. Trying to reload the site, it just hangs.

### Steps to reproduce

install using gatsby new <my app name>
go to app folder with vs code and run npm start
see app compile and start as normal
access web site without issues
create new folder inside of pages folder. compiles fine
create new js file inside the new folder. compiles fine
make some edits inside new js file. compiles up to a point and then freezes the terminal, which becomes unresponsive.

### Expected result

I should be a be able to keep going without having to constantly restart the terminal

### Actual result

Keeps freezing and i have to restart vs code.

### Environment

There must be something wrong with this install since I get the errors below. But I did not do anything special, other than run the cli as shown above.

  [4mSystem:[0m
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  [4mBinaries:[0m
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  [4mLanguages:[0m
    Python: 2.7.15 - C:\Users\dharr\.windows-build-tools\python27\python.EXE
  [4mBrowsers:[0m
    Edge: 42.17134.1.0
  [4mnpmPackages:[0m
    gatsby: ^2.0.118 => 2.0.118 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17 
    gatsby-plugin-offline: ^2.0.23 => 2.0.23 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20 
    gatsby-source-filesystem: ^2.0.20 => 2.0.20 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13 

[0m
[0m  [0m[97m[41mError[0m[37m[41m:[0m[37m[41m [0m[97m[41mThe system cannot find the path specified.[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93menvinfo.js[0m[90m:[0m[93m1[0m[37m [0m[37mFunction.e.exports.sync[0m
[0m  [0m  [0m[90m[gatsby-garb]/[envinfo]/dist/envinfo.js:1:4970[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93menvinfo.js[0m[90m:[0m[93m1[0m[37m [0m[37mObject.copySync[0m
[0m  [0m  [0m[90m[gatsby-garb]/[envinfo]/dist/envinfo.js:1:66948[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93menvinfo.js[0m[90m:[0m[93m1[0m[37m [0m[37mObject.t.writeSync.e [as writeSync][0m
[0m  [0m  [0m[90m[gatsby-garb]/[envinfo]/dist/envinfo.js:1:48777[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93menvinfo.js[0m[90m:[0m[93m1[0m[37m [0m
[0m  [0m  [0m[90m[gatsby-garb]/[envinfo]/dist/envinfo.js:1:46934[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93menvinfo.js[0m[90m:[0m[93m1[0m[37m [0m[37mPromise.all.then.e[0m
[0m  [0m  [0m[90m[gatsby-garb]/[envinfo]/dist/envinfo.js:1:46949[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mutil.js[0m[90m:[0m[93m16[0m[37m [0m[37mtryCatcher[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/util.js:16:23[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m512[0m[37m [0m[37mPromise._settlePromiseFromHandler[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:512:31[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m569[0m[37m [0m[37mPromise._settlePromise[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:569:18[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m614[0m[37m [0m[37mPromise._settlePromise0[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:614:10[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m694[0m[37m [0m[37mPromise._settlePromises[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:694:18[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m638[0m[37m [0m[37mPromise._fulfill[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:638:18[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise_array.js[0m[90m:[0m[93m126[0m[37m [0m[37mPromiseArray._resolve[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise_array.js:126:19[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise_array.js[0m[90m:[0m[93m144[0m[37m [0m[37mPromiseArray._promiseFulfilled[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise_array.js:144:14[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m574[0m[37m [0m[37mPromise._settlePromise[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:574:26[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m614[0m[37m [0m[37mPromise._settlePromise0[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:614:10[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m694[0m[37m [0m[37mPromise._settlePromises[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:694:18[0m
[0m  [0m
[0m

[0m
[0m  [0m[97m[41mError[0m[37m[41m:[0m[37m[41m [0m[97m[41mThe system cannot find the path specified.[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93menvinfo.js[0m[90m:[0m[93m1[0m[37m [0m[37mFunction.e.exports.sync[0m
[0m  [0m  [0m[90m[gatsby-garb]/[envinfo]/dist/envinfo.js:1:4970[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93menvinfo.js[0m[90m:[0m[93m1[0m[37m [0m[37mObject.copySync[0m
[0m  [0m  [0m[90m[gatsby-garb]/[envinfo]/dist/envinfo.js:1:66948[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93menvinfo.js[0m[90m:[0m[93m1[0m[37m [0m[37mObject.t.writeSync.e [as writeSync][0m
[0m  [0m  [0m[90m[gatsby-garb]/[envinfo]/dist/envinfo.js:1:48777[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93menvinfo.js[0m[90m:[0m[93m1[0m[37m [0m
[0m  [0m  [0m[90m[gatsby-garb]/[envinfo]/dist/envinfo.js:1:46934[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93menvinfo.js[0m[90m:[0m[93m1[0m[37m [0m[37mPromise.all.then.e[0m
[0m  [0m  [0m[90m[gatsby-garb]/[envinfo]/dist/envinfo.js:1:46949[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mutil.js[0m[90m:[0m[93m16[0m[37m [0m[37mtryCatcher[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/util.js:16:23[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m512[0m[37m [0m[37mPromise._settlePromiseFromHandler[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:512:31[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m569[0m[37m [0m[37mPromise._settlePromise[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:569:18[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m614[0m[37m [0m[37mPromise._settlePromise0[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:614:10[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m694[0m[37m [0m[37mPromise._settlePromises[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:694:18[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m638[0m[37m [0m[37mPromise._fulfill[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:638:18[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise_array.js[0m[90m:[0m[93m126[0m[37m [0m[37mPromiseArray._resolve[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise_array.js:126:19[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise_array.js[0m[90m:[0m[93m144[0m[37m [0m[37mPromiseArray._promiseFulfilled[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise_array.js:144:14[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m574[0m[37m [0m[37mPromise._settlePromise[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:574:26[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m614[0m[37m [0m[37mPromise._settlePromise0[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:614:10[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mpromise.js[0m[90m:[0m[93m694[0m[37m [0m[37mPromise._settlePromises[0m
[0m  [0m  [0m[90m[gatsby-garb]/[bluebird]/js/release/promise.js:694:18[0m
[0m  [0m
[0m

**Comment by pieh** [comment]
@dharric How often does the freeze happen? Did you also try on non-windows OS (just trying to verify this is windows specific issue and not gatsby in general)?

**Comment by dharric** [comment]
The freeze happens after making code changes. It seems to occur when code changes are either wrong and fail the build or I'm making a longer code change that takes several steps (the build tries to run even though I've not saved the file yet and have not completed my changes yet). But it takes a few failures before the freeze happens. I end up killing my vs code terminal and opening a new one. This works but of course is annoying and a time suck. On mac this issue does not occur (I have a macbook also). Is there another log somewhere that I can send you? Not sure that a screenshot would help since its not error specific.

**Comment by pieh** [comment]
I don't think any logs or screenshot will help here (we don't have enough details for problems like that in our logs). I need to try to reproduce this problem - I do have windows machine around, so will just boot it up and will try to cause freeze.

**Comment by dharric** [comment]
Cool I'll keep going and write again if I see anything new.

**Comment by jonniebigodes** [comment]
@dharric speaking from experience, the only time i've experienced a behaviour like yours was under three situations:

- The harddrive was dying on me, soon after this behaviour started i was presented with the infamous "click of death"
- The system is under a lot of stress. And by stress i mean let's say a big bunch of chrome tabs opened, 3 to 4 instances of vscode, slack and email and also a wsl ubuntu machine running a project that i was revising and then then the antivirus kicked in and basically....the system locked down.
- With the "abuse" mentioned above out of the picture,to be avoided as much as possible, the same happened, but it was due to a markdown heavy gatsby site. I was updating the markdown and trying to see the outcome of the edits and my system started locking down.

**Comment by pieh** [comment]
So this is very long shot - buy maybe you could try using `CHOKIDAR_USEPOLLING` environment variable - for example in your project `package.json` have a `develop` script like this:

```
{
  "name": "name-of-project",
  ...rest of fields,
  "scripts": {
    "develop": "CHOKIDAR_USEPOLLING=1 gatsby develop"
    ...rest of scripts
  }
}
```
and see if that helps?

**Comment by dharric** [comment]
@jonniebigodes thanks but site is still being developed and very small. Also this is the only app that is exhibiting this behavior. Appreciate your feedback though.

**Comment by dharric** [comment]
@pieh thanks but could you explain what that would do. Also on a side note if I kill the build I see polling happening back to my server for socket.io and webpack_hmr. The webpack must be for hotmodule reloading, but do you know what the socket connection is for?

**Comment by pieh** [comment]
Web socket is primarily for emitting graphql query data (we don't use webpack for data as it doesn't scale very well when there are thousands of pages)

**Comment by dharric** [comment]
When I tried adding the entry into package.json I got error 'CHOKIDAR_USEPOLLING' is not recognized as an internal or external command. Other than that issue still occurs. I even tried updating all of my npm packages. No luck.

**Comment by lannonbr** [comment]
@dharric Are you still running into this issue?

**Comment by bogdan-calapod** [comment]
I'm also running into this issue. Windows 10 1809 with Ubuntu WSL and Gatsby 2.0.91 installed.

**Comment by lannonbr** [comment]
@bogdan-calapod can you try updating to Gatsby 2.2.0 or later and try again to check that this hasn’t been resolved

**Comment by bogdan-calapod** [comment]
Just upgraded all packages to the latest version (gatsby is at 2.2.5) and it still locks up. The weird thing is that the port somehow remains blocked, as killing the terminal and restarting gatsby doesn't restore connection.

Restarting LxssManager from `services.msc` and then restarting `gatsby` fixes the problem after a while. 

Let me know if I can be of help in tracking this bug down.

**Comment by lannonbr** [comment]
Okay. I'll mark it as not stale as the issue is still persisting

**Comment by dharric** [comment]
I also updated and it still happens. I also develop node and plain react apps but have never run into this issue there

**Comment by skyzadev** [comment]
I am experiencing the same issue.  

Currently busy with the gatsby tutorials using VS CODE on Windows. Running gatsby and starting a develop server works great until I edit a file with a change which breaks the build. It seems that once you make a breaking change while the site is running it freezes. I also cannot kill the server using ctrl + c in the terminal, I have to physically kill the terminal instance for it to quit.

**Comment by jarrodmedrano** [comment]
I am also having this problem. And the kicker is killall node wont' even stop gatsby develop from running.

**Comment by sdevil7th** [comment]
Same issue for me as well! A new change in jsx or scss module file would freeze the app for atleast 1minute.

**Comment by wardpeet** [comment]
Could you try running the following:
`setx CHOKIDAR_USEPOLLING 1; npm run dev`?

**Comment by koga73** [comment]
I'm experiencing this as well. gatsby develop completely locks up the console. Can't control+c. Web server is unresponsive. I tried ```setx CHOKIDAR_USEPOLLING 1;``` which made no difference. Also tried restarting LxssManager and deleting my .cache and public directories. Nothing works please help!

**Comment by ahukkanen** [comment]
Having the same issue with Ubuntu 18.04, so seems it's not only Windows specific.

**Comment by rpedroni** [comment]
Having the same problem running on Mac/Mojave and Node 11. I'll try to update to Node 12 to see if it solves the problem.

**Comment by wardpeet** [comment]
Node 11 has overall problems and is not on the LTS track. Please use node 10 or 12.

**Comment by hashimwarren** [comment]
> Node 11 has overall problems and is not on the LTS track. Please use node 10 or 12.

I had the same problem this week with my terminal freezing after running gatsby develop.

I upgraded Node from 10 to 12.

Problem resolved. My terminal no longer freezes after running gatsby develop
