### ISSUE TITLE
withPrefix not working in 2.0.118

### ISSUE THREAD

**Issue by morleytatro** [gatsbyjs/gatsby#11669]
## Description

Files inserted in the static folder and referenced using withPrefix are not found in development.

### Steps to reproduce

Start a new Gatsby project with 2.0.118 and use the withPrefix to load an assets

### Expected result

The asset should be successfully called in development.

### Actual result

It instead rendered a 404 page. I confirmed that this was not the case in version 2.0.114.

### Environment

System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 62.0
    Safari: 12.0.3
  npmPackages:
    gatsby: 2.0.118 => 2.0.118 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-plugin-google-analytics: ^2.0.13 => 2.0.13 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-remove-trailing-slashes: ^2.0.7 => 2.0.7 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20 
    gatsby-plugin-typescript: ^2.0.7 => 2.0.7 
    gatsby-react-router-scroll: ^2.0.4 => 2.0.4 
    gatsby-source-contentful: ^2.0.29 => 2.0.29 
    gatsby-source-filesystem: ^2.0.20 => 2.0.20 
    gatsby-transformer-remark: ^2.2.4 => 2.2.4 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13 
  npmGlobalPackages:
    gatsby: 2.0.117

**Comment by pieh** [comment]
Can you provide reproduction sample for this?

I tried reproducing locally but it **seems** to work for me using `gatsby@2.0.118` (I used `/blog` as pathPrefix):
![screenshot 2019-02-11 at 11 59 19](https://user-images.githubusercontent.com/419821/52559114-a9781480-2df4-11e9-8070-f53d90accc0e.png)

Did you build using `gatsby build --prefix-paths`?

**Comment by morleytatro** [comment]
Strange, it actually wasn't during the build that I noticed it; it was in development. However, upon starting a brand-new repo with 2.0.118, the issue isn't happening. I have a pathPrefix of '/'. Unfortunately, I can't share the code, so I'll close this for now until I determine what the pertinent difference is.
