### ISSUE TITLE
How I can debug code in source of gatsby-source-filesystem plugin 

### ISSUE THREAD

**Issue by iFlameing** [gatsbyjs/gatsby#11675]
I am adding a custom header to create-remote-file-node which is able to pass the authentication token so that private things all fetch from the cms. can anybody help me regarding this issue? please!. You can see my changes by going to this link https://github.com/iFlameing/gatsby/pull/1

**Comment by pieh** [comment]
Hey, do You need more help? I've seen you created PR for this ( https://github.com/gatsbyjs/gatsby/pull/11682 )

**Comment by iFlameing** [comment]
@pieh  now the problem is resolved can you review my pr.

just one simple question how I can log some  return ouput in source code
of createRemoteFileNode.

**Comment by DanielRuf** [comment]
You can always insert a `debugger;` statement and step through the code and inspect the values. It is better than a `console.log` as you can use it with the debugger and output the current states.

**Comment by iFlameing** [comment]
@DanielRuf thanks
