### ISSUE TITLE
False positive deprecation warning

### ISSUE THREAD

**Issue by JacobBlomgren** [gatsbyjs/gatsby#11679]
## Description

When developing on the gatsby website (www), I get this in dev mode:
```
boundActionCreators is deprecated. Please use actions instead. For migration instructions, see https://gatsby.app/boundActionCreators

Check the following files:

src/pages/docs/actions.js
```

The only mention of boundActionCreators in that file is [l32](https://github.com/gatsbyjs/gatsby/blob/master/www/src/pages/docs/actions.js#L32), clearly a false positive. This is caused by `gatsby/src/commands/develop` at [l383-l407](https://github.com/gatsbyjs/gatsby/blob/45a8f09554b20a02f9c83e57272b7fb1721500b7/packages/gatsby/src/commands/develop.js#L383) where every file in a gatsby project is simply scanned for the keywords `boundActionCreators` and `pathContext`.

This has been reported in at least one other (stale) issue as well: https://github.com/gatsbyjs/gatsby/issues/10211

Now, I don't know if there's any obvious good solution to this that wouldn't be over-engineering, except for maybe clarifying the print. But perhaps even that would only confuse. I imagine the vast majority of scenarios are not false positives after all. But I at least wanted to bring this up.

### Steps to reproduce

Run the gatsby site in `develop` mode.

**Comment by pieh** [comment]
Perhaps we could limit warnings for this only to `gatsby-node.js` files, but this might silence warnings if users would split their gatsby-node into multiple modules (something that we actually do in some plugins - for example in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/gatsby-node.js)

**Comment by pieh** [comment]
another idea:
we could use Getter for `boundActionCreators` instead of scanning files - something like this: https://runkit.com/pieh/5c61658c2da4920012e3a826

**Comment by JacobBlomgren** [comment]
@pieh Really nice idea! Shouldn't we be able to do the same with `pathContext` then? If I understand it  correctly, it's provided here https://github.com/gatsbyjs/gatsby/blob/b750400e4ad4ebb9d3bf7b4b1437232e5d7331e4/packages/gatsby/cache-dir/static-entry.js , and then we should be able to do something similar, e.g.:
```js
const props = {
  ...this.props,
  ...dataAndContext,
  get pathContext() {
    console.log('deprecated')
    return dataAndContext.pageContext
  },
}
```

**Comment by pieh** [comment]
Yeah, if we go that route we should use it for all deprecated things (if possible)

One thing that we are losing with this is showing in which files those are used. And also if any plugin uses `boundActionCreators` users would see those warning and wonder where they come from.

**Comment by JacobBlomgren** [comment]
@pieh the last point is a really valid one. I can find that at least gatsby-plugin-sharp [uses](https://github.com/gatsbyjs/gatsby/blob/b789689717b7be16e213fe8ac0e5ceb3ab38e4e8/packages/gatsby-plugin-sharp/src/index.js#L39) `boundActionCreators` and likewise the internal plugins [query-watcher](https://github.com/gatsbyjs/gatsby/blob/5f16e651ff2f5ebb6a5bf73f0f706a96f22e9458/packages/gatsby/src/internal-plugins/query-runner/query-watcher.js#L17) and [internal-data-bridge](https://github.com/gatsbyjs/gatsby/blob/ac2a54ae6795636d9088a06ac8c26bd1519e3728/packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js#L7). On top of that it's used in [page-hot-reloader](https://github.com/gatsbyjs/gatsby/blob/5c2e5cb62f3f95ee784b578c2a317c6be171157d/packages/gatsby/src/bootstrap/page-hot-reloader.js#L5) also internally. 

So it's safe to say that a lot of consumers would be affected by this and wonder where the warnings came from. So maybe this issue should just be closed.
