### ISSUE TITLE
Error: custom keyword definition is invalid: data.errors should be boolean

### ISSUE THREAD

**Issue by ndejesus1227** [gatsbyjs/gatsby#11678]
## Description

Trying to build a restaurant menu theme, I kept getting this error:

Error: custom keyword definition is invalid: data.errors should be boolean

I went into `node_modules/ajv/lib/keyword.js` (where the error pointed me to) and manually did this:

```
  if (definition) {
    definition.errors = false
...
```

The original value was a string when it was expecting a boolean. The theme seems to work just fine now. I just wanted to bring this to someone's attention.

### Steps to reproduce

Pretty sure if you just clone my repo and try running:

`yarn workspace site develop`

You'll see the error

https://github.com/ndejesus1227/gatsby-theme-restaurant-website

### Expected result
I should just be able to see the server start and the initial page which would say "Waddup, yo"

### Actual result

Get this error:

Error: custom keyword definition is invalid: data.errors should be boolean

For some reason data.errors has a string "full".

What happened.

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
    Yarn: 1.10.1 - ~/.nvm/versions/node/v10.5.0/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v10.5.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmGlobalPackages:
    gatsby-cli: 2.4.9
```

Hopefully this is helpful.

**Comment by pieh** [comment]
Hey, there was upstream bug:
 - https://github.com/webpack/webpack/issues/8768
 - https://github.com/epoberezkin/ajv/issues/941
You would need to update `ajv` package (but it's not straight forward because it's not our direct dependency) - it's probably simplest to nuke `yarn.lock` and let it be recreated with next `yarn` install. Alternative solution is to add `resolutions` to root package.json (and install deps again):
```
{
  "private": true,
  "name": "gatsby-theme-restaurant",
  "version": "0.1.0",
  "workspaces": [
    "site",
    "packages/*"
  ],
  "resolutions": {
    "ajv": "^6.9.1"
  }
}
```

**Comment by ndejesus1227** [comment]
@pieh That fixed it! I used your resolutions method, removed node_modules and ran yarn install. Thank you!
