### ISSUE TITLE
Gatsby image quality original

### ISSUE THREAD

**Issue by frederikhors** [gatsbyjs/gatsby#11672]
I'm new to Gatsby.

I'm just wondering why I can't use my original quality for "fixed" images?

If I have a 500 KB jpg image (already high optimized I don't want to change quality, how to?

Now gatsby is making 200 KB with `quality: 50` (default) and a 1.28 MB with `quality: 100` (manually).

**Comment by pieh** [comment]
This is tricky to do automatically (to use original image if size of original file is lower than size of generated image). When we provide `src` and `srcSet` information, those files potentially don't exist yet (we queue image processing).

So any solution would need to be explicitly opted in by user (like adding "reuseOriginalImage" argument to sharp transformation / query).

**Comment by pieh** [comment]
For now I guess best way is to experiment with `quality` setting. `quality: 100` will cause images to be very large in size with potentially not very noticeable differences with `quality: 90` - as you increase quality there are diminishing returns for actual image quality, but file size keep growing.

**Comment by frederikhors** [comment]
Can I have for now (until we understand how to) just the functioning of traced SVG (or blur) and my original size (with not at all resized images)?

**Comment by frederikhors** [comment]
Please, bot, do not stale.

**Comment by qnguyen12** [comment]
I don't know if this is the cause of the big size of images after building?
For example, file on Github is 138KB https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/master/static/img/home-jumbotron.jpg
but it's 437KB on https://gatsby-netlify-cms.netlify.com/
Both files have the same dimensions, resolution and bit depth.

**Comment by frederikhors** [comment]
Gatsbot, please.

**Comment by jserrao** [comment]
I'm enjoying the bot conversation....

**Comment by frederikhors** [comment]
@gastbot please reopen.

**Comment by leandigital** [comment]
This is a pretty serious issue. I want to use images that I optimize myself, as they alway look better and weigh less than what Gatsby produces. However, if I use gatsby-image with quality anything other than 85, the result is terrible, but  80 and over - the file size goes through the roof. Not sure what compression mechanism is used but it's obviously not good.
