### ISSUE TITLE
Gatsby develop running but not updating page after npm install

### ISSUE THREAD

**Issue by nzwnabdulwahid** [gatsbyjs/gatsby#11674]
## Description

Installed `gatsby-plugin-create-client-paths` via `npm install --save gatsby-plugin-create-client-paths` and run successfully. After that saving the changes on code doesn't update the page anymore

### Steps to reproduce

I use `gatsby-firebase-authentication` starter and before this npm any package working just fine expect for `gatsby-plugin-create-client-paths`

### Environment

  System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 5.2 - /bin/zsh
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 15.41s. - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Firefox: 62.0.3
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.12 => 2.0.82 
    gatsby-plugin-antd: ^2.0.2 => 2.0.2 
    gatsby-plugin-create-client-paths: ^2.0.4 => 2.0.4 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.5

**Comment by pieh** [comment]
Do you see any errors in browser console? I just tried setting up project with firebase and same starter, installing `gatsby-plugin-create-client-paths` and it did work.

Is your project hosted on github? Can you share a link to it? Either publicly here or via DM on twitter ( https://twitter.com/mipiechowiak )

**Comment by pieh** [comment]
One thing I noticed - in your `Environment` info there is something weird going on with `yarn` (instead of showing version, it install packages with yarn). I don't know if this might cause some issues - but just as sanity check, please try deleting node_modules and reinstalling deps (`npm install`)

**Comment by nzwnabdulwahid** [comment]
Hi @pieh , now its working after I delete the node_modules and reinstalling it. Not really sure what happens but thank you !
