### ISSUE TITLE
Disable javascript

### ISSUE THREAD

**Issue by yepes** [gatsbyjs/gatsby#11680]
Hi everyone

I have created a single page webpage that doesn't provide any user interaction. 
I have all the content in markdown files, and I use gatsby to generate a static, just one page website.
All I need is the html content and the images. Everything is working, but gatsby is adding some javascript files that i wont never use.

How can I avoid that?

**Comment by mherchel** [comment]
Gatsby is a static site generator based on React. One of it's purposes is to prefetch additional pages. 

I honestly think that a one-page non-JS site is outside of Gatsby's use-case. For a one-pager, why not use static HTML?

**Comment by yepes** [comment]
Yep, maybe that's right. I just discovered gatsby the other day and had to do something simple and test it. Just wondering if that would be possible. 

I know about other "older" static sites generator, I just wanted to try something new

**Comment by pieh** [comment]
We don't support this out of the box, but if you feel advanteruous I think this would doable using [`onPreRenderHTML`](https://www.gatsbyjs.org/docs/ssr-apis/#onPreRenderHTML) hook in `gatsby-ssr.js` - especially for js bundles you would want to use `getHeadComponents` and filter out `js` ones (or just all script tags, and use `replaceHeadComponents` with filtered list of components. Might need to check "pre-body components" and "post-body components"

**Comment by KyleAMathews** [comment]
People build tons of 1 pager sites with Gatsby. Just like larger sites, it's far more productive to use Gatsby with ready-designed development environment and plugins, and optimized production builds vs doing it by hand. Also one page sites rarely stay one page. Also it's rare too for sites to not eventually need JavaScript.

Back to the subject of removing the js script tags. It'd be nice if there was a plugin which followed the algorithm @pieh described. It could work for all pages or just specified pages.

**Comment by LekoArts** [comment]
> I honestly think that a one-page non-JS site is outside of Gatsby's use-case. For a one-pager, why not use static HTML?

One-Pager are a perfect usecase. I saw so many websites with 30MB of images loading... You get that optimizations for free then

**Comment by yepes** [comment]
@pieh thanks, i will take a look at it and try to do something this week.

@KyleAMathews yeah, that would be awesome. But i'm getting a grasp of React and this is my first project using gatsby, so I don't think I can do that yet

**Comment by itmayziii** [comment]
I wrote a Gatsby plugin that removes Gatsby generated javascript for those that find this issue in the future

https://www.npmjs.com/package/gatsby-plugin-no-javascript
