### ISSUE TITLE
Attempting to replace header icon, but icon is formatted as text not an image

### ISSUE THREAD

**Issue by farverio** [gatsbyjs/gatsby#11681]
## Description
I am working to replace the diamond icon on the main page, but it appears it is hard-coded as a font awesome text. I believe many users would have a use case wherein they would like to more easily replace the icon with a logo, but the current CSS makes it challenging. Given additional guidance, I would be glad to help fix to improve this template and enable even more users to try out this great design!

### Steps to reproduce

In the Header.js file, import a logo picture into the component. Remove the `fa-diamond` class to the span and add the image with the source between the span. It looks okay if sized correctly on a full-page but is not mobile friendly and does not resize even after adjusting the `_header.scss` to edit the height/width of the `.logo > .icon` at various breakpoints. Feel free to PM for an actual link.

### Expected result

The image should resize according to the breakpoints sent and stay within the created circle of the webpage.

### Actual result

The image remains the same size as the circle size decreases, thus making the site look very unprofessional.

### Environment

```System:
    OS: Linux 4.15 KDE neon 5.14
    CPU: (4) x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    npm: 3.5.2 - /usr/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Firefox: 65.0
  npmPackages:
    gatsby: ^2.0.76 => 2.0.118 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.17 
    gatsby-plugin-offline: ^2.0.16 => 2.0.23 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.6 
    gatsby-plugin-sass: ^2.0.7 => 2.0.10 
  npmGlobalPackages:
    gatsby-cli: 2.4.9```

**Comment by mherchel** [comment]
To make images resize according to the width of the viewport, you'll want to add a `max-width: 100%` rule within CSS. I typically do this globally to all `img` elements.

```css
img {
  max-width: 100%;
}
```
