### ISSUE TITLE
process image with sharp and provide path onCreateNode

### ISSUE THREAD

**Issue by marcos-rios** [gatsbyjs/gatsby#11695]
## Summary
I'm trying to process images on create node using image-sharp.
The idea is to implement search functionality and be able to show images using the [elastic-lunr plugin](https://www.gatsbyjs.org/packages/@gatsby-contrib/gatsby-plugin-elasticlunr-search/?=elastic-lunr) and [semantic-ui-react](https://react.semantic-ui.com/modules/search/) search component.

## Relevant information

When searching the elastic-lunr index, I want to be able to show an image in the search results.
My idea was to add a field to the markdown node which would contain the final path of the image after being processed by image-sharp. Is there a way to do that?

frontmatter:
```
title: "fancy title"
description: "fancy description"
cover: "./cover.jpg"
```

### File contents (if changed)

`gatsby-config.js`: 
```
{
  resolve: `@gatsby-contrib/gatsby-plugin-elasticlunr-search`,
  options: {
    // Fields to index
    fields: ['title', 'description'],
    // How to resolve each field`s value for a supported node type
    resolvers: {
      // For any node of type MarkdownRemark, list how to resolve the fields` values
      MarkdownRemark: {
        title: node => node.frontmatter.title,
        description: node => node.frontmatter.description,
        thumbnail: node => node.fields.thumbnail,
      },
    },
  },
}
```

`package.json`: N/A 
`gatsby-node.js`: 
```
exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions
  if (node.internal.type === `MarkdownRemark`) {
    const slug = createFilePath({ node, getNode, basePath: `data/posts`, trailingSlash: false })
    const thumbnailPath = path.join(
      path.dirname(node.fileAbsolutePath),
      node.frontmatter.cover
    )

    // console.log(
    //   sharp(thumbnailPath)
    //     .resize({ width: 64 })
    //     .toFile('output.png')
    // )
    
    createNodeField({
      node,
      name: 'slug',
      value: slug,
    })
    createNodeField({
      node,
      name: 'thumbnail',
      value: thumbnailPath,
    })
  }
}
```

`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by krismorf** [comment]
This plugin only scans markdown properties. But you can build your own lunr index in your `gatsby-node.js` by modifying your existing createPages export and your graphql query.

See [here](https://github.com/humanseelabs/gatsby-plugin-lunr/issues/8#issuecomment-447301250)

**Comment by marcos-rios** [comment]
It works! Thanks!!
