### ISSUE TITLE
Google search console

### ISSUE THREAD

**Issue by razvan-soare** [gatsbyjs/gatsby#11692]
Hello i have a little problem maybe someone can help a bit.
In the next screenshot i have some errors from google search console that says it cannot load lots of files on my website.

But if i take one of these urls and open it in a new tab i can see the files there. This image for example.
https://bryant.dental/static/689f06a3e92b7ef707773e8cb9a869bd/133f4/gallery-6.jpg

![screen shot 2019-02-11 at 14 15 50](https://user-images.githubusercontent.com/39434481/52564540-23b49300-2e0d-11e9-9557-320f21e53d94.png)

At first i thought it might be because i rebuilt the project and pushed the new files on production and since at every build gatsby is generating another hash for files, google wont be able to find these files or smth.. But since i can access them i have no idea why would the resources fail loading.

**Comment by DanielRuf** [comment]
These are sometimes false positives / bugs of the Google crawler. Did you try to run the crawler again?

**Comment by DanielRuf** [comment]
Or is it blocked by the robots.txt rules?

**Comment by razvan-soare** [comment]
Yes i did bunch of recrawls and im getting the same result. 

And the robots look like this
```
User-agent: *
Disallow:
Sitemap: https://bryant.dental/sitemap.xml
```

**Comment by gdomorski** [comment]
I agree this seems more like an issue with false positives / bugs of the Google crawler.

**Comment by wardpeet** [comment]
Hearing from your comments it looks like we can't resolve this on our end or did I miss anything?
