### ISSUE TITLE
gatsby-transformer-yaml sourceNodes node availability

### ISSUE THREAD

**Issue by nicib83** [gatsbyjs/gatsby#11705]
## Description

When I include a yml file via gatsby-transformer-yaml ought these needs be available within exports.sourceNodes in gatsby-node.js ?

### Steps to reproduce

gatsby-transformer-yaml
add yml file
exports.sourceNodes in gatsby-node.js

### Expected result

I can see the yml nodes

### Actual result

They are not there, only file references.
But they are available in exports.createPages later on

### Environment

 System:
    OS: Linux 4.9 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: (2) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 4.3.30 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^2.0.19 => 2.0.44
    gatsby-image: ^2.0.15 => 2.0.20
    gatsby-plugin-emotion: ^3.0.1 => 3.0.1
    gatsby-plugin-eslint: ^2.0.1 => 2.0.1
    gatsby-plugin-manifest: ^2.0.5 => 2.0.8
    gatsby-plugin-offline: ^2.0.5 => 2.0.13
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.1
    gatsby-plugin-sharp: ^2.0.7 => 2.0.12
    gatsby-source-filesystem: ^2.0.20 => 2.0.20
    gatsby-source-google-sheets: ^1.1.1 => 1.1.1
    gatsby-transformer-sharp: ^2.1.4 => 2.1.8
    gatsby-transformer-yaml: ^2.1.8 => 2.1.8
  npmGlobalPackages:
    gatsby-cli: 2.4.8

**Comment by pieh** [comment]
> When I include a yml file via gatsby-transformer-yaml ought these needs be available within exports.sourceNodes in gatsby-node.js ?

It's not guaranteed that they will be created before `sourceNodes` is called. What are you trying to do? Maybe there is different approach to achieve that

**Comment by nicib83** [comment]
i am trying to create nodes based on a number of plugins, these need to be consumed by createPages.

i thought sourceNodes is the recommended early entry point for this

**Comment by nicib83** [comment]
I thought this was reflected by:

https://www.gatsbyjs.org/docs/node-apis/#sourceNodes

> If you define this hook in gatsby-node.js it will be called exactly once after all of your source plugins have finished creating nodes.

**Comment by pieh** [comment]
It's true for source plugins, but not for transformers. We call `onCreateNode` and this can be async operations, so your `gatsby-node` sourceNodes might be called before transformers handle `onCreateNode`

**Comment by nicib83** [comment]
thanks this is fine for me

**Comment by pieh** [comment]
I'm just thinking if we should expose something that `sourceNodes` could wait for all already scheduled `onCreateNode` to finish

for example:
exports.sourceNodes = async ({ actions, waitForTransformers }) => {
  await waitForTransformers()
  // now all transformed nodes are available
}

**Comment by nicib83** [comment]
since plugins perform tasks that are delegated and you usually wait for this could be an option, or a new exports.sourceNodesWithTransforms

**Comment by nicib83** [comment]
onCreateNode works for entity level follow up operations, but not for tasks which require batch or aggregated results
