### ISSUE TITLE
feat(gatsby-plugin-google-analytics]: DNS prefetch google analytics domain in head

### ISSUE THREAD

**Issue by asistapl** [gatsbyjs/gatsby#11714]
## Summary

I saw that gatsby website is doing this:
https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-ssr.js#L10
And I'm wondering if it's a good idea to do it by default in gatsby-plugin-google-analytics.

### Motivation

Maybe things will go a little faster with that approach.

**Comment by pieh** [comment]
@m-allanson do you remember if there was reason we added this just for gatsbyjs.org and not to google analytics plugin directly?

**Comment by m-allanson** [comment]
I have no idea why I did it like that 😅 

It seems like a good idea to add it to the google analytics plugin though. It's something that gets highlighted during a [Lighthouse](https://developers.google.com/web/tools/lighthouse/) audit. Looking at the audit for gatsbyjs.org:

![screenshot 2019-02-12 at 15 37 03](https://user-images.githubusercontent.com/381801/52647284-537e9c00-2edc-11e9-984d-99d49c3e6ecd.png)

Does google analytics (GA) always connect to google.com too? That could be worth investigating, and adding if it's a domain that GA always connects to.

**Comment by asistapl** [comment]
I found all these in source:

- //www.google-analytics.com
- //www.google.com
- //stats.g.doubleclick.net
- //ampcid.google.com

but only `//www.google-analytics.com` and  `//www.google.com` appears to be used often when I look at request while browsing some sites.

I can create PR for that and add these two domains. I would use relative protocol `//` since analytics.js would use `http://` if site is served with that.

It's also worth looking into this aspect in `gatsby-plugin-google-tagmanager` plugin.

**Comment by ayu15** [comment]
Keep open

**Comment by dougwithseismic** [comment]
Anyone working on this? I'll pick it up if not.

**Comment by wardpeet** [comment]
@dougwithseismic Thank you for wanting to contribute, sadly we already have support for it and it was added in https://github.com/gatsbyjs/gatsby/pull/12826.

I'll be closing this one for that reason.
