### ISSUE TITLE
Passing variables through route

### ISSUE THREAD

**Issue by jonathan-chin** [gatsbyjs/gatsby#1171]
hi all,

pardon me if this is a silly question. how can I pull variables from the route / url? for example:

www.example.com/blog/this-is-the-title

can I pull the title into a variable?

**Comment by craig-mulligan** [comment]
Hey @jonathan-chin, I haven't actually used Gatsby much yet, but it uses react-router under the hood, so it should be passing the location to the the route component in this case your page component. I'm take a look at this https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/location.md.

**Comment by jonathan-chin** [comment]
Thanks but part of what I'm struggling with is configuring the routes to
components. Gatsby does so much of it magically that I'm not sure where to
customize them.

**Comment by jonathan-chin** [comment]
@craig-mulligan it looks like I want to do something like this:

```
<Route path="/user/:username" component={User}/>

const User = ({ match }) => {
  return <h1>Hello {match.params.username}!</h1>
}
```

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md#Route-props

Any ideas where I would make the additions in Gatsby?

**Comment by MarcCoet** [comment]
@jonathan-chin hopefully you can find your answer there: https://github.com/gatsbyjs/gatsby/blob/1.0/examples/client-only-paths/src/pages/index.js

**Comment by KyleAMathews** [comment]
Add a `console.log(this.props)` to your render method. The location data from react-router should be there.

**Comment by jonathan-chin** [comment]
@MarcCoet this looks almost exactly like what I need. let me try to incorporate it into my code. Thanks!

**Comment by nikhilag** [comment]
The updated link for the answer given by @MarcCoet  is https://github.com/gatsbyjs/gatsby/blob/master/examples/client-only-paths/src/pages/index.js

**Comment by lucasjohnston** [comment]
This isn't working for me - I even copied and pasted the code from @jonathan-chin's answer, and it keeps redirecting me to the Gatsby 404 page 😞

**Comment by lucasjohnston** [comment]
Never mind! I was missing this in my `gatsby-node.js`:

```// Implement the Gatsby API “onCreatePage”. This is
// called after every page is created.
exports.onCreatePage = ({ page, actions }) => {
  const { createPage } = actions
  // Make the front page match everything client side.
  // Normally your paths should be a bit more judicious.
  if (page.path === `/`) {
    page.matchPath = `/*`
    createPage(page)
  }
}```
