### ISSUE TITLE
[gatsby-source-graphql] InputFields (using a scalar type) are invalidated by relay-compiler

### ISSUE THREAD

**Issue by inlet** [gatsbyjs/gatsby#11710]
## Description

It seems that scalar types are not supported? I've tried to build the schema via an introspection file as well and it still throws the same error.

### Steps to reproduce

1. Open this simple [graphql server](https://v01op94yp5.sse.codesandbox.io/) and make sure it's running. See JSON scalar type in [edit view](https://codesandbox.io/s/v01op94yp5). Running queries via `graphiql` gives you the correct response.

try:

```graphql
{
  Search {
    asc: by(filter: { sort: "DESC" }) {
      result
    }
    desc: by(filter: { sort: "ASC" }) {
      result
    }
  }
}
```

2. Open this [gatsby project](https://codesandbox.io/s/431j121929), which points to the graphql server (step 1) and go to `Server Control Panel` tab and hit the `Restart Sandbox` button.

3. See error in `Terminal` tab:

`error GraphQLIRPrinter: Need an InputObject type to print objects.`

### Tip

If you change `page/index.js` with this query (leave out the input args):

```graphql
export const query = graphql`
  {
    searchapi {
      Search {
        by {
          result
        }
      }
    }
  }
`
```

the build succeeds.. it seems like `relay-compiler` doesn't like the custom scalar type. I've tried it with an older version of Gatsby and the error was something like:

`GraphQL Error Expected a value matching type 'Search_JSON' but got an object value`

### Expected result

The build should succeed. 

### Actual result

Error:

`error GraphQLIRPrinter: Need an InputObject type to print objects.`

### Environment

See codesandbox

### Using Gatsby's GraphiQL

Query it with the builtin Gatsby GraphiQL at `http://localhost:8000/___graphql` works as expected

Thanks so much for creating this awesome project! Keep up the good work.

**Comment by freiksenet** [comment]
It's a bug upstream. I'll make a fix and send it to relay-compiler.

**Comment by freiksenet** [comment]
Right, this is actually fixed in https://github.com/facebook/relay/pull/2638. I'll push additional regression test for it.

**Comment by inlet** [comment]
> Right, this is actually already fixed by me in [facebook/relay#2638](https://github.com/facebook/relay/pull/2638).

Perhaps Gatsby using an older relay?

> I'll push additional regression test for it there just to make sure.

Awesome! Would love to see this working

**Comment by freiksenet** [comment]
> Perhaps Gatsby using an older relay?

It's not merged yet, that's why it still occurs.

**Comment by inlet** [comment]
That makes sense! Hopefully they merge it soon. Thanks man

**Comment by freiksenet** [comment]
Should be fixed in 2.1.1

**Comment by inlet** [comment]
Now it throws a different error:

```
The GraphQL query from /sandbox/src/pages/index.js failed.

Errors:
  Syntax Error: Expected Name, found String "sort"
```

See terminal tab: https://codesandbox.io/s/431j121929

**Comment by inlet** [comment]
Any pointers why this happens?

**Comment by simoneb** [comment]
try removing the double quotes

**Comment by inlet** [comment]
See [gatsby project](https://codesandbox.io/s/431j121929 ), I'm not adding double quotes at all.

**Comment by simoneb** [comment]
"DESC" -> DESC

**Comment by inlet** [comment]
As you can see if I remove the double quotes it gets reconstructed with double quotes internally.

![image](https://user-images.githubusercontent.com/232559/52953118-d5604080-3386-11e9-92af-b4847ce334a9.png)

Can you make the codesandbox example to work?

**Comment by simoneb** [comment]
I couldn't, but when I opened it the quotes were still there. In any case, this issue doesn't seem to be fixed and it's affecting me too, with or without quotes.

**Comment by inlet** [comment]
@freiksenet Do you have any idea what's causing the issue? Thanks!

**Comment by simoneb** [comment]
To add more details to this, the same query in my case works perfectly fine in the GraphiQL tool running along with the gatsby development server. It suggests it's an issue with the way the query is parsed before being submitted to the server, or a wrong formatting when it is sent to the server.

**Comment by inlet** [comment]
> To add more details to this, the same query in my case works perfectly fine in the GraphiQL tool running along with the gatsby development server.

Exactly, I pointed this out in the issue description as well.

> It suggests it's an issue with the way the query is parsed before being submitted to the server, or a wrong formatting when it is sent to the server.

👍 

It looks like the graphql validator (relay-compiler?) validates a serialized query.

**Comment by inlet** [comment]
@freiksenet any updates on this issue?

**Comment by karthikvt26** [comment]
Folks I am still facing this issue with my Hasura GraphQL engine server.

Here are my package.json and yarn.lock screenshots.

![screenshot 755](https://user-images.githubusercontent.com/25095884/54030905-1c499500-41d3-11e9-9499-ab4d936b95f0.jpg)
![screenshot 754](https://user-images.githubusercontent.com/25095884/54030907-1ce22b80-41d3-11e9-83ac-be9fe5b32a12.jpg)

Here is the error

![screenshot 756](https://user-images.githubusercontent.com/25095884/54030913-24a1d000-41d3-11e9-8605-218f306e0edf.jpg)

Am I doing anything wrong here?

Any help is greatly appreciated :)

**Comment by Overdozed** [comment]
Error with your hasura coming from using single query values where arrays are expected.
Probably you copied your query from their playground, but the playground set single objects per default also where array is expected. It doesn't cause errors on playground itself.
