### ISSUE TITLE
Why is graphql returning a number?

### ISSUE THREAD

**Issue by tylermcrobert** [gatsbyjs/gatsby#11717]
For some reason, a query in GraphiQL that returns a block of JSON data simply returns a 9-digit number.

```
const query = graphql`
  query allPrismicCaseStudy {
     edges {
       node {
         uid
       }
     }
   }
`;
```
returns `348885080`

```
const query = graphql`
  query{
    site{
      port
    }
  }
`;
```

returns `3416814672`

I am using the hello world starter. Whitespace seems to impact the number's output

**Comment by pieh** [comment]
Can you paste entire file snippet? Do you by any chance try to use `query` variable directly? This won't contain data, but hash of the query content (used internally by gatsby)

**Comment by tylermcrobert** [comment]
That appears to be the issue.

**Comment by AlbertZawadzki** [comment]
I've same issue, I'm not using query variable directly, my code:
`export const query= graphql`
  query nameQuery{
    file(base: { eq: "data.json" }) {
      children {
        ... on DataJson {
          id
          name
          link
        }
      }
    }
  }
``

**Comment by AlbertZawadzki** [comment]
Hi, 
Can you explain me why (and how to fix it) this query is returning hashing?

query:

`
export const query = graphql'
  query nameQuery {
    file(base: { eq: "data.json" }) {
      children {
        ... on DataJson {
          id
          name
          link
        }
      }
    }
  }
'`

data.json:
`
[
  { "id": "menu-01", "name": "name1", "link": "/link1" },
  { "id": "menu-02", "name": "name2", "link": "/link2" },
  { "id": "menu-03", "name": "name3", "link": "/link3" }
]`

**Comment by onderbakirtas** [comment]
I'm experiencing same issue. Pretty much same query returns 9-digit number. Is there any update on this?

**Comment by PieterT2000** [comment]
Same issue here!

**Comment by MaxVynohradov** [comment]
@PieterT2000 , @onderbakirtas , just faced with the same issue.
But fixed this, it was mistake in my code!
From docs: https://www.gatsbyjs.com/docs/page-query/ 

> Below the HomePage component declaration, export a new constant called query. The name of the constant isn’t important, as Gatsby looks for an exported graphql string from the file rather than a specific variable. Note that you can only have one page query per file.

Hope, this will be useful.

**Comment by onderbakirtas** [comment]
> @PieterT2000 , @onderbakirtas , just faced with the same issue.
> But fixed this, it was mistake in my code!
> From docs: https://www.gatsbyjs.com/docs/page-query/
> 
> > Below the HomePage component declaration, export a new constant called query. The name of the constant isn’t important, as Gatsby looks for an exported graphql string from the file rather than a specific variable. Note that you can only have one page query per file.
> 
> Hope, this will be useful.

Thanks for taking time to answer it. I have solved it just like you. Mistakes here to be made.

**Comment by delasign** [comment]
@onderbakirtas  @MaxVynohradov What exactly did you do?

I cannot seem to resolve this issue.
