### ISSUE TITLE
Why can't query exports be listed at the end of the module?

### ISSUE THREAD

**Issue by matchatype** [gatsbyjs/gatsby#11726]
## Description

I have the following working template:

```javascript
import React from 'react'
import { graphql } from 'gatsby'

import Layout from '../components/layout'

export const query = graphql`
  query($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      html
      frontmatter {
        title
      }
    }
  }
`

const SinglePostTemplate = props => {
  const { frontmatter, html } = props.data.markdownRemark
  return (
    <Layout>
      <div>
        <h1>{frontmatter.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: html }} />
      </div>
    </Layout>
  )
}

export { SinglePostTemplate as default }
```

However, if I try to list everything I want to export at the end of the module, the query does not work, and the component's `data` prop is never populated.

### Steps to reproduce

Rewrite exports as follows:

```javascript
import React from 'react'
import { graphql } from 'gatsby'

import Layout from '../components/layout'

const query = graphql`
  query($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      html
      frontmatter {
        title
      }
    }
  }
`

const SinglePostTemplate = props => {
  const { frontmatter, html } = props.data.markdownRemark
  return (
    <Layout>
      <div>
        <h1>{frontmatter.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: html }} />
      </div>
    </Layout>
  )
}

export { query, SinglePostTemplate as default }
```
### Expected result

The component should be passed a `data` prop.

### Actual result

No prop is passed down to the component.

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.15.1 - ~/.asdf/shims/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.asdf/shims/npm
  Languages:
    Python: 2.7.14 - /Users/andrea/.asdf/shims/python
  Browsers:
    Chrome: 72.0.3626.96
    Firefox: 65.0
    Safari: 12.1
  npmPackages:
    gatsby: ^2.0.119 => 2.0.119 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17 
    gatsby-plugin-offline: ^2.0.23 => 2.0.23 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20 
    gatsby-source-filesystem: ^2.0.20 => 2.0.20 
    gatsby-transformer-remark: 2.2.5 => 2.2.5 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13

**Comment by pieh** [comment]
We do static analisys of source files to extract queries and run them during the build.

Here's our code handling this currently - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/query-runner/file-parser.js#L187-L213 - this is just limitation of current implementation (just handling code in your first example) and it's definitely possible to implement support for your second example.
