### ISSUE TITLE
VSCode goto Definition navigation not working

### ISSUE THREAD

**Issue by chatzipan** [gatsbyjs/gatsby#11722]
## Summary
I have created 3 different projects with Gatsby, and i used VSCode as an editor, and in all of them I cannot get "go to Definition" feature working. 

That means for example hovering over a js import and doing Ctrl + click does not navigate to the imported file, something that slows down my development. 

Anyone else facing the same issue?

**Comment by pieh** [comment]
Seems to work here:
![kapture 2019-02-12 at 21 55 40](https://user-images.githubusercontent.com/419821/52667412-08cb4700-2f11-11e9-845a-ac2983c466f0.gif)
I'm no expert in vs code tho, so I don't know why it doesn't work for You :(

**Comment by chatzipan** [comment]
Hmm.. its really weird, I use VScode as my standard editor, and its just my Gatsby projects where this doesn't work.. i guess i need to search it more

**Comment by wardpeet** [comment]
I don't have any issues either 😛 Does peek definition work?

**Comment by christian-schulze** [comment]
I'm also seeing this issue, though it works for installed modules located in `node_modules` folder, but no user created files...

One possible cause, could be using import aliases, which I have configured using the `gatsby-plugin-root-import` plugin:

_gatsby-config.js_
```
{
  plugins: [
      resolve: "gatsby-plugin-root-import",
      options: {
        components: path.join(__dirname, "src/components"),
        hooks: path.join(__dirname, "src/hooks"),
        images: path.join(__dirname, "src/images"),
        utils: path.join(__dirname, "src/utils"),
      },
    },
  ]
```

**Comment by christian-schulze** [comment]
I've got a solution...specify a `jsconfig.json`:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "*": ["src/*"]
    },
    "jsx": "react"
  }
}
```

@wardpeet @pieh @chatzipan

**Comment by dmandreev** [comment]
> jsconfig.json

Doesn't work. After 1-5 seconds with loaded gatsby project, "Go to definition", path suggestions on import. and other Intellisence stuff of VSCode  stopped working.  Very annoying. 

"Typescritp Restart TS Server" from command palette can help temporarily.
