### ISSUE TITLE
Bring back preview sites when creating a pull request

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#11731]
## Description
We used to have demo sites added to PRs so we can view our changes and make sure they didn't break.

![image](https://user-images.githubusercontent.com/1120926/52702899-71e8a400-2f7d-11e9-9f6c-3a47bab92286.png)

I find it super valuable for www when changes are done to docs or parts of core that we can visualize it without building www yourself https://github.com/gatsbyjs/gatsby/issues/10815 and https://github.com/gatsbyjs/gatsby/issues/7348 will help too.

Besides www we could link plugins to examples and tell gatsbybot about these deploys so we don't have to clutter the comments with 100 deploys.

I've noticed that builds are running on netlify but just have to bring the bot back.

### Steps to reproduce

Go to pull requests, pick one from the last month and you'll see no deploy comments :'(

### Expected result

What should happen?

![image](https://user-images.githubusercontent.com/1120926/52702899-71e8a400-2f7d-11e9-9f6c-3a47bab92286.png)

**Comment by gurpreet-hanjra** [comment]
Hello @wardpeet this issue seems interesting. Would you mind giving some pointers to fix this? Thank you.

**Comment by pieh** [comment]
We removed `Netlify` github app from repo because it was too spammy and also netlify check in PR status check was confusing because example sites were overriding this check.

Deploys can still be manually checked when visiting f.e. https://app.netlify.com/sites/using-remark/deploys (this should visible to everyone).

Ideally we would have have single "example sites" check that would create detailed view in "Checks" tab on PRs that would list status for each example, but this require some custom coding.

**Comment by m-allanson** [comment]
Thanks @gurpreet-hanjra! Unfortunately this needs to be done by a Gatsby team member, as it requires access to Gatsby's Netlify account. 

@pieh Is the new Netlify GitHub App considerate with notifications? Or is the problem that we were pushing notifications from multiple sites to this one repo? https://www.netlify.com/blog/2018/12/03/richer-github-integrations-come-to-netlify-thanks-to-github-apps/

I think it'd at least be worth re-adding netlify build notifications for gatsbyjs.org, even if we don't add all the example. site notifications back.

> Ideally we would have have single "example sites" check that would create detailed view in "Checks" tab on PRs that would list status for each example, but this require some custom coding.

👍

**Comment by wardpeet** [comment]
@pieh so making a mini dashboard where all builds are shown?

I can imagine the spammyness when using a bot when it builds on each push. If multiple netlify apps are possible this would fix it too? (like circle-ci)

**Comment by pieh** [comment]
> @pieh Is the new Netlify GitHub App considerate with notifications? Or is the problem that we were pushing notifications from multiple sites to this one repo? [netlify.com/blog/2018/12/03/richer-github-integrations-come-to-netlify-thanks-to-github-apps](https://www.netlify.com/blog/2018/12/03/richer-github-integrations-come-to-netlify-thanks-to-github-apps/)

So this is what we've seen when I re-enabled netlify app for a moment
![screenshot 2019-02-13 at 14 06 43](https://user-images.githubusercontent.com/419821/52713862-bcc3e500-2f98-11e9-9d48-0334e60e9897.png)

There were multiple extra checks added by netlify (comming from "richer github integration") - this can be disabled per site on netlify settings, but I don't have access to all of them and it wasn't priority task to do.

I mean all of this (comments, checks) should be configurable, but we still won't really get nice list of results for each example in single unified manner.
