### ISSUE TITLE
"Variable "$slug" got invalid value null; Expected non-nullable type String! not to be null."

### ISSUE THREAD

**Issue by imshuffling** [gatsbyjs/gatsby#11732]
Getting a weird error when running `gatsby develop` this morning.

![screenshot 2019-02-13 at 10 09 39](https://user-images.githubusercontent.com/739061/52704018-8e81dd80-2f77-11e9-9d33-b87bad092535.png)

Getting alot of 404s in the console and the index.js page does not want to load.

![screenshot 2019-02-13 at 10 12 17](https://user-images.githubusercontent.com/739061/52704202-e91b3980-2f77-11e9-8a20-d6b9e18e000c.png)

Repo here - https://github.com/imshuffling/davidrich.es

I haven't touched anything in the code just updated node_modules recently so I'm wondering if a package has been updated or I need to update my code.

### Environment

  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.96
    Firefox: 65.0
    Safari: 12.0.2
  npmPackages:
    gatsby: next => 2.0.0-rc.28 
    gatsby-image: next => 2.0.0-rc.4 
    gatsby-plugin-catch-links: next => 2.0.2-rc.1 
    gatsby-plugin-manifest: next => 2.0.2-rc.1 
    gatsby-plugin-netlify: next => 2.0.0-rc.6 
    gatsby-plugin-nprogress: next => 2.0.0-rc.1 
    gatsby-plugin-offline: next => 2.0.0-rc.9 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1 
    gatsby-plugin-sass: next => 2.0.0-rc.2 
    gatsby-plugin-sharp: next => 2.0.0-rc.7 
    gatsby-plugin-sitemap: ^2.0.2 => 2.0.5 
    gatsby-plugin-sri: ^1.0.3 => 1.0.5 
    gatsby-source-contentful: next => 2.0.1-rc.9 
    gatsby-transformer-remark: next => 2.1.1-rc.5 
    gatsby-transformer-sharp: next => 2.1.1-rc.3

**Comment by imshuffling** [comment]
![screenshot 2019-02-13 at 13 48 00](https://user-images.githubusercontent.com/739061/52716130-065f0080-2f96-11e9-9401-7fb32a8a68d6.png)

Seeing this coming back from contentful, looks like its something to do with this.

**Comment by DSchau** [comment]
@imshuffling to remediate, you could just filter on the `null`, e.g. something like:

```graphql
{
  allContentfulPortfolio(filter: { slug: { ne: null } }) {
    # the rest
  }
}
```

Generally you'll want to just fix the content issue though--is the slug something added to that content type (manually) or something you're generating automatically?

**Comment by imshuffling** [comment]
OK thanks, Yeah the slug its added to content type.

I've contacted Contentful to see if they can shed any light on this,  it's a strange one because the posts have content.

**Comment by pieh** [comment]
Do you use localisation in contentful? If so try adding `locale` or `node_locale` (don't remember exact name of the field) to your graphiql query. It might shed some light on this

**Comment by imshuffling** [comment]
Yeah tried that, I've raised it with Contentful - see what they come back with.

![screenshot 2019-02-13 at 16 31 49](https://user-images.githubusercontent.com/739061/52727353-eedf4200-2fac-11e9-8eb9-216d2420e326.png)

Thanks.

**Comment by imshuffling** [comment]
Update.

![screenshot 2019-02-13 at 17 04 54](https://user-images.githubusercontent.com/739061/52729695-92caec80-2fb1-11e9-9fb2-c81d583a896e.png)

**Comment by DSchau** [comment]
@imshuffling thanks for digging in!

Let's get this closed out as it doesn't really seem to be a Gatsby issue. Thanks for opening and sharing the (upcoming!) fix for others, as well!

**Comment by h-sargsyan** [comment]
checkFilters() {
      this.queryResult = this.adminProperties
      console.log(this.queryResult)

      this.$apollo.query({
        query: gql` query{
          propertiesPublishedFilters(input: {price_filters: {min: 123, max: 123, deal_type: "sale"}, id: $id}) {
            id
            address
            property_deals {
              deal_type {
                name
              }
              price
            }
          }
        }`,
      }).then((e) => {
        console.log(e)
      }).catch((e) => {
        console.log('false', e)
      })
    }

this is my experience.
