### ISSUE TITLE
[gatsby-plugin-offline & gatsby-plugin-layout] Link activeStyle problem

### ISSUE THREAD

**Issue by universse** [gatsbyjs/gatsby#11738]
## Description
I'm using gatsby-plugin-offline and gatsby-plugin-layout on my site. Prop activeStyle on Link component rendered in gatsby-plugin-layout layouts/index.js component (footer) isn't properly applied on subsequent access to the site after service worker is installed. 
Link rendered in the gatsby v2 layout component (header) works as expected.

### Steps to reproduce
With gatsby-plugin-offline, after service worker is installed, on subsequent access, activeStyle={{color: 'black'}} isn't applied to the Link in footer. The interesting thing is in react devtools, activestyle is present (https://i.imgur.com/bp713B3.png)
https://with-offline.netlify.com/

Everything works as expected without gatsby-plugin-offline.
https://without-offline.netlify.com/

Source code is available here https://codesandbox.io/s/w28k3n0kpk

### Expected result
"Gatsby" in footer for https://with-offline.netlify.com/ should be black.

### Actual result
"Gatsby" in footer for https://with-offline.netlify.com/ is white.

Also, a big thank-you for all the amazing works you guys have done.

**Comment by pieh** [comment]
This is mixed problem of react hydration and our app shell used by offline plugin (which does use layout, but shouldn't).

The problem is that when offline plugin is used we serve (what should be) blank page. But because it actually includes layout (with link in footer that has inactive styling) when we hydrate (mount react application over existing html), react doesn't handle updating mismatched attributes.

React documentation mention this:

> React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them. In development mode, React warns about mismatches during hydration. There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.
( https://reactjs.org/docs/react-dom.html#hydrate )

**Comment by pieh** [comment]
I don't think there are reasonable workarounds for this and we need to fix that in gatsby code.

**Comment by tudor-ghiorghiu** [comment]
I am having a similar issue with this, but with CSS modules `className={styles.nameOfMyClass}`. Even after disabling all modules and leaving only `gatsby-plugin-sass` it still acts up.
This is the first load of the landing page:
<img width="1440" alt="screenshot 2019-02-14 at 08 35 09" src="https://user-images.githubusercontent.com/4012479/52767609-b2a2f480-3033-11e9-9cac-11a121c9f5e4.png">

This is the landing page after I navigate away from it and then back again:
<img width="1439" alt="screenshot 2019-02-14 at 08 35 12" src="https://user-images.githubusercontent.com/4012479/52767686-ebdb6480-3033-11e9-9dd0-b27ffe4a0859.png">

If I don't use modules, everything is fine, but that's now what I am after for.

**Comment by pieh** [comment]
@tudor-ghiorghiu I think this is also hydration problem, but given that you removed all of the plugins (so no `gatsby-plugin-offline`) it's unrelated to this issue. Can you create separate issue (ideally with reproduction - link to repository that will allow us to reproduce and give you answer more specific to your case)

**Comment by universse** [comment]
Seems like the issue is fixed now. Thanks!

**Comment by universse** [comment]
Hi sorry for the miscommunication. I am reopening because I encountered this issue again.

**Comment by universse** [comment]
anyway i found a workaround in case anyone faces the same problem
layouts/index.js
```javascript
export default function Layout ({ location }) {
  if (location.pathname=== '/offline-plugin-app-shell-fallback') return null
  
  // rest of code
}
```
