### ISSUE TITLE
Providing function as option to babel plugin does not work

### ISSUE THREAD

**Issue by psantini** [gatsbyjs/gatsby#11746]
## Description

When trying to implement functionality to minify classnames (as described here [https://medium.freecodecamp.org/reducing-css-bundle-size-70-by-cutting-the-class-names-and-using-scope-isolation-625440de600b](https://medium.freecodecamp.org/reducing-css-bundle-size-70-by-cutting-the-class-names-and-using-scope-isolation-625440de600b)) I came across an issue with the `addBabelPlugin` functionality.  When trying to provide a function to the `generateScopedName` parameter for `babel-plugin-react-css-modules`, the system would ignore that functionality, reverting back to the default value as defined here: [requireCssModule.js](https://github.com/gajus/babel-plugin-react-css-modules/blob/master/src/requireCssModule.js#L105).  After investigating further, it seems to be that because the options for the babel plugins are being put into the redux store here: [babelrc.js](https://github.com/gatsbyjs/gatsby/blob/9c45441da456b41f010a86b0ba5fa7e1a81fa5bf/packages/gatsby/src/redux/reducers/babelrc.js#L43), serialized out here: [gatsby-node](https://github.com/gatsbyjs/gatsby/blob/0f0feac9c7ebb1b18208bbbc584f3cddc5f31a72/packages/gatsby/src/internal-plugins/load-babel-config/gatsby-node.js#L25), and then read back in here: [babel-loader-helpers](https://github.com/gatsbyjs/gatsby/blob/0f0feac9c7ebb1b18208bbbc584f3cddc5f31a72/packages/gatsby/src/utils/babel-loader-helpers.js#L11), the function gets removed (functions return `undefined` when passed to `JSON.stringify`) 

### Steps to reproduce

Attempt to set the generateScopedName parameter in `onCreateBabelConfig` in `gatsby-node.js` as follows:
```
exports.onCreateBabelConfig = ({ actions }) => {
  actions.setBabelPlugin({
    name    : 'babel-plugin-react-css-modules',
    options : {
      generateScopedName : function(localName, resourcePath) {
        return 'bob';
       },
      webpackHotModuleReloading : process.env.NODE_ENV !== 'production',
      attributeNames            : { styleClasses : 'classes' }
    }
  });
};
```

### Expected result

All of the generated HTML would have `bob` as its class (tried to make this as obvious as possible).

### Actual result

All of the generated classnames match the default interpolation string `'[path]___[name]__[local]___[hash:base64:5]'`

### Environment

  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.15.0 - ~/.nodenv/versions/8.15.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nodenv/versions/8.15.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.117 => 2.0.117 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-link: ^2.0.9 => 2.0.10 
    gatsby-paginate: ^1.0.17 => 1.0.17 
    gatsby-plugin-canonical-urls: ^2.0.10 => 2.0.10 
    gatsby-plugin-catch-links: ^2.0.10 => 2.0.10 
    gatsby-plugin-feed: ^2.0.13 => 2.0.13 
    gatsby-plugin-google-tagmanager: ^2.0.9 => 2.0.9 
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17 
    gatsby-plugin-offline: ^2.0.22 => 2.0.22 
    gatsby-plugin-postcss: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-sharp: ^2.0.19 => 2.0.20 
    gatsby-plugin-sitemap: ^2.0.5 => 2.0.5 
    gatsby-source-contentful: ^2.0.29 => 2.0.29 
    gatsby-transformer-remark: ^2.2.4 => 2.2.4

**Comment by pieh** [comment]
To be honest I'm not sure why we serialize/deserialize babel config. I will be following code and reading babel docs. 

This was added in https://github.com/gatsbyjs/gatsby/pull/6801 changeset that was resolving https://github.com/gatsbyjs/gatsby/issues/4689 ticket.

**Comment by psantini** [comment]
@pieh Just wanted to check if there was any further thought on a way to get around the issue we're having.  Thanks so much!

**Comment by psantini** [comment]
Hello again.  Wanted to see if there was any thought on a resolution to this issue as it is does end up bloating our html and css files larger than we'd prefer.
