### ISSUE TITLE
Fetch contentful preview data on load for instant feedback

### ISSUE THREAD

**Issue by marcuslindfeldt** [gatsbyjs/gatsby#11755]
## Summary
Ability to fetch contentful data on load instead of build for preview purposes in `gatsby-source-contentful`.

### Basic example
`CONTENTFUL_HOST=https://preview.contentful.com CONTENTFUL_FETCH_ON_LOAD=true gatsby build`

### Motivation

To be a real contender to giants like wordpress, static site generators needs to shorten the feedback loop for content writers. Waiting up to five minutes for the site to build every time you make a new draft of a blog post is not a great experience.

**Comment by pieh** [comment]
This is currently possible - see https://github.com/gatsbyjs/gatsby/issues/10328 and linked resources from there (youtube video is almost one year old, and issues that author of that vid shown should be fixed).

You would need to have development server running and publicly accessible with refresh hook enabled and confiugre your contentful space to trigger gatsby webhook on data changes.

**Comment by marcuslindfeldt** [comment]
Cool! Thank you for this! I had no idea this existed.
