### ISSUE TITLE
TypeError: Cannot read property 'split' of null at createErrorFromString, or for v1 building HTML fails without throwing an error on the console

### ISSUE THREAD

**Issue by festiveox** [gatsbyjs/gatsby#11799]
## Summary

I didn't know where to write this so I will just do it here in case someone runs into the same issue.

I have been fighting Gatsby (1.9) for the last 2 days because it would build the CSS, and JS, but when it got to the HTML it would stop after a couple of seconds, skip, don't log any issue/error, and finish the build process without the HTML. 

So this is when my journey started, I looked, and looked, tried upgrading to the latest Gatsby, which gave me some insight with superior error logging, either way that didn't work.

I went back to v1.9 and started uninstalling node modules that I had just installed until I found 4 modules that are interdependent that were causing the build to fail. These are internal modules that my company uses so I couldn't just get rid of them or find replacements. 

What I ended up doing is checking them one by one and fixing any browser globals that I found. This didn't work. However, on this effort I found a component that was trying to style an Error constructor using styled components. It seems that by this component was triggering an exit on the Gatsby build, by sending a silent error without any message. 

To fix this I downgraded to a version of the library without the Error component.

Moral of the story, we need better logging for Gatsby, and be careful with Error constructors if your HTML build is not building and is not throwing any errors.

edit: Upon further investigation the error was triggered due to the Error not being declared (with const, let, etc) so declaring it should solve the issue.

## Relevant information

this is the culprit:
```js

Error = styled.p`
  font-family: ${fontFamily};
  color: ${colors.error};
  font-weight: ${fontWeight.light};
  ${fontSize("bodySmall")};
  line-height: 1;
  bottom: 0;
  position: ${props => props.position ? props.position : 'absolute'};
  margin: ${props => props.margin ? props.margin : "4px 0 8px"};
  padding: ${props => props.padding ? props.padding : "0"};
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
`

export { Error as default }
```

### Environment (if relevant)

Gatsby v1.9

**Comment by pieh** [comment]
Do you have code causing this error in build publicly available so we could use it for reproduction + fix testing?

**Comment by pieh** [comment]
Ok, I see - it should be enough to copy `Error` component example (that misses variable declaration)

**Comment by festiveox** [comment]
Yup! If you call that component in your code as a component <Error>Text</Error> Gatsby will fail to build. It is using styled-components.
