### ISSUE TITLE
PageRenderer missing from typings

### ISSUE THREAD

**Issue by jariz** [gatsbyjs/gatsby#11796]
## Description

The PageRenderer component is missing from the TS typings.

### Steps to reproduce

```js
import { PageRenderer } from 'gatsby'; // 🚨 TS2305: Module has no exported member 'PageRenderer'.
```
### Expected result

N/A

### Actual result

N/A

### Environment

N/A

**Comment by pieh** [comment]
Would you be interested and adding those in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/index.d.ts

For reference this is the component

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/public-page-renderer-prod.js

So it only have `location` prop

**Comment by jariz** [comment]
Thanks. I'll file a PR shortly.

**Comment by pieh** [comment]
`location` should have normal `Location` shape (https://developer.mozilla.org/en-US/docs/Web/API/Location). We mark just `pathname` as required, but there is bunch of other optional fields that can be passed (and used by the referenced page template component), so if there is ready to use `Location` typing - this is what we should use.

**Comment by jariz** [comment]
reach-router exports a `WindowLocation` type which differs slightly from the default location object because it has a couple of historyjs-specific keys added to it (like 'state'), so I was figuring I'd use that - if that's OK.

**Comment by pieh** [comment]
Sure! This is very good catch. Even if it's unlikely that users would use @reach/router specific fields this is more future proof.
