### ISSUE TITLE
I got this error when Gatsby Build breaks. Anyone has any idea?

### ISSUE THREAD

**Issue by jerus1403** [gatsbyjs/gatsby#11802]
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://gatsby.app/debug-html

   8 |  else
   9 |          root["lib"] = factory(root["@reach/router"], root["core-js/library/fn/array/from"], root["core-js/library/fn/array/is-array"], root["core-js/library/fn/is-iterable"], root["core-js/library/fn/json/stringify"], root["core-js/library/fn/map"], root["core-js/library/fn/object/assign"], root["core-js/library/fn/object/create"], root["core-js/library/fn/object/define-property"], root["core-js/library/fn/object/get-own-property-descriptor"], root["core-js/library/fn/object/get-own-property-symbols"], root["core-js/library/fn/object/get-prototype-of"], root["core-js/library/fn/object/keys"], root["core-js/library/fn/object/set-prototype-of"], root["core-js/library/fn/promise"], root["core-js/library/fn/symbol"], root["core-js/library/fn/symbol/iterator"], root["core-js/modules/es6.array.find-index"], root["core-js/modules/es6.array.iterator"], root["core-js/modules/es6.array.sort"], root["core-js/modules/es6.function.name"], root["core-js/modules/es6.map"], root["core-js/modules/es6.object.assign"], root["core-js/modules/es6.object.keys"], root["core-js/modules/es6.promise"], root["core-js/modules/es6.regexp.constructor"], root["core-js/modules/es6.regexp.match"], root["core-js/modules/es6.regexp.replace"], root["core-js/modules/es6.regexp.search"], root["core-js/modules/es6.regexp.split"], root["core-js/modules/es6.regexp.to-string"], root["core-js/modules/es6.string.ends-with"], root["core-js/modules/es6.string.includes"], root["core-js/modules/es6.string.iterator"], root["core-js/modules/es6.string.link"], root["core-js/modules/es7.array.includes"], root["core-js/modules/web.dom.iterable"], root["fs"], root["lodash"], root["path"], root["react"], root["react-dom/server"], root["react-helmet"]);
> 10 | })(this, function(__WEBPACK_EXTERNAL_MODULE__reach_router__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_array_from__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_array_is_array__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_is_iterable__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_json_stringify__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_map__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_object_assign__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_object_create__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_object_define_property__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_object_get_own_property_descriptor__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_object_get_own_property_symbols__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_object_get_prototype_of__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_object_keys__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_object_set_prototype_of__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_promise__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_symbol__, __WEBPACK_EXTERNAL_MODULE_core_js_library_fn_symbol_iterator__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_array_find_index__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_array_iterator__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_array_sort__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_function_name__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_map__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_object_assign__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_object_keys__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_promise__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_regexp_constructor__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_regexp_match__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_regexp_replace__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_regexp_search__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_regexp_split__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_regexp_to_string__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_string_ends_with__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_string_includes__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_string_iterator__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_string_link__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_es7_array_includes__, __WEBPACK_EXTERNAL_MODULE_core_js_modules_web_dom_iterable__, __WEBPACK_EXTERNAL_MODULE_fs__, __WEBPACK_EXTERNAL_MODULE_lodash__, __WEBPACK_EXTERNAL_MODULE_path__, __WEBPACK_EXTERNAL_MODULE_react__, __WEBPACK_EXTERNAL_MODULE_react_dom_server__, __WEBPACK_EXTERNAL_MODULE_react_helmet__) {
     |  ^
  11 | return

  WebpackError: Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified de  v environment for full errors and additional helpful warnings.

  - universalModuleDefinition:10 ba
    lib/webpack/universalModuleDefinition:10:2

  - bootstrap:24 a.read
    lib/webpack/bootstrap:24:1

  - bootstrap:36 renderToString
    lib/webpack/bootstrap:36:1

  - static-entry.js:190 Module../.cache/static-entry.js.__webpack_exports__.default
    lib/.cache/static-entry.js:190:18

  - bootstrap:24 Promise
    lib/webpack/bootstrap:24:1

  - gatsby-browser-entry.js:1 Promise._resolveFromExecutor
    lib/.cache/gatsby-browser-entry.js:1:1

  - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1

  - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1

  - bootstrap:50 MappingPromiseArray._promiseFulfilled
    lib/webpack/bootstrap:50:1

  - api-runner-ssr.js:6 MappingPromiseArray.PromiseArray._iterate
    lib/.cache/api-runner-ssr.js:6:27

  - bootstrap:67 MappingPromiseArray.init
    lib/webpack/bootstrap:67:1

  - bootstrap:19 MappingPromiseArray._asyncInit
    lib/webpack/bootstrap:19:1

**Comment by pieh** [comment]
Can you try updating `gatsby` to latest? It probably won't fix the build but should at least point to a page path that cause the error so it's easier to find components potentially responsible

**Comment by jerus1403** [comment]
> Can you try updating `gatsby` to latest? It probably won't fix the build but should at least point to a page path that cause the error so it's easier to find components potentially responsible

Thanks Pieh. I did and it's spitting out where the problem is for me. Now I'm working on solving the problem.

**Comment by JustFly1984** [comment]
We had same issue today, hope it will help:

we had refactoring and basicaly had a typo in functional component declaration:

instead of proper:
```
const MyComponent = () => (<JSX />)
``

we had:

```
const MyComponent = (<JSX />)
```

**Comment by jerus1403** [comment]
Yes we have multiple issues that break the Gatsby Build process. Thank you for sharing with us. 👍

**Comment by DSchau** [comment]
Great! Sounds like this is mostly answered, so going to close it out.

@jerus1403 would you be able to make a comment confirming what your issue(s) were so that anyone else who lands here will be able to track your solution too?

Thanks so much, and thanks for using Gatsby! 💪

**Comment by jerus1403** [comment]
The issues were most from the graphql query the unknown properties after I changed some post types from the CMS (Wordpress). We use Wordpress as a headless CMS for our project.
