### ISSUE TITLE
Wordpress example installation is down?

### ISSUE THREAD

**Issue by riddla** [gatsbyjs/gatsby#11806]
## Description

The WordPress site used in the `using-worpress` example seems to be down.

### Steps to reproduce

```bash
curl -I dev-gatbsyjswp.pantheonsite.io
curl: (6) Could not resolve host: dev-gatbsyjswp.pantheonsite.io
```

**Comment by DSchau** [comment]
Oh - whoops. I presumed this fixed it, but this site is probably still down?

**Comment by riddla** [comment]
Yeah, just wanted to mention that.

**Comment by DSchau** [comment]
I should've probably _not_ merged the PR then 🙃 

Oh well - figuring this out now, hopefully the URL stays the same 😅

**Comment by riddla** [comment]
At least its the same in all places now. But the one on wordpress.com seemed abandoned from what I could tell from the referenced commit in the PR. 
There was a change to the pantheon one in the code and I saw the site running a few weeks ago ...

**Comment by KyleAMathews** [comment]
I "unfroze" the site on Pantheon. I just have to do this periodically. Not idea but it's free at least.

**Comment by KyleAMathews** [comment]
Thanks for the heads up!

**Comment by riddla** [comment]
@KyleAMathews, I found the following on https://pantheon.io/docs/platform-considerations/:

> **Inactive Site Freezing**
> Sandbox sites that are over four months old that have not had code commits or other Git activity for three months are "frozen". All requests to a frozen site will return a 530 Site Frozen error code, and the site's Dashboard will be unavailable.

Which probably means, that this will happen again?
