### ISSUE TITLE
Gatsby  Error: no parsers registered for: "\"

### ISSUE THREAD

**Issue by samuelbouye** [gatsbyjs/gatsby#11807]
npm run develop

> gatsby-starter-hello-world@0.1.0 develop C:\Users\Samuel Bouyé\Documents\WorkSpace\Projects\other\hello-world
> gatsby develop

success open and validate gatsby-configs — 0.038 s
success load plugins — 1.133 s
success onPreInit — 0.625 s
success delete html and css files from previous builds — 0.161 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success initialize cache — 0.317 s
success copy gatsby files — 2.008 s
success onPreBootstrap — 0.083 s
success source and transform nodes — 0.157 s
success building schema — 1.239 s
success createPages — 0.002 s
success createPagesStatefully — 0.953 s
success onPreExtractQueries — 0.002 s
success update schema — 1.060 s
success extract queries from components — 0.146 s
success run graphql queries — 0.058 s — 3/3 53.79 queries/second
success write out page data — 0.055 s
success write out redirect data — 0.009 s
success onPostBootstrap — 0.002 s

info bootstrap finished - 31.008 s

error UNHANDLED EXCEPTION

  Error: no parsers registered for: "\"

  - parser.js:473 parse
    [hello-world]/[snapdragon]/lib/parser.js:473:15

  - parser.js:477 Parser.parse
    [hello-world]/[snapdragon]/lib/parser.js:477:24

  - index.js:122 Snapdragon.parse
    [hello-world]/[snapdragon]/index.js:122:28

  - braces.js:40 Snapdragon.<anonymous>
    [hello-world]/[braces]/lib/braces.js:40:45

  - braces.js:66 Braces.parse
    [hello-world]/[braces]/lib/braces.js:66:26

  - braces.js:87 Braces.expand
    [hello-world]/[braces]/lib/braces.js:87:18

  - index.js:142 create
    [hello-world]/[braces]/index.js:142:15

  - index.js:298 memoize
    [hello-world]/[braces]/index.js:298:13

  - index.js:165 Function.braces.create
    [hello-world]/[braces]/index.js:165:10

  - index.js:81 Function.braces.expand
    [hello-world]/[braces]/index.js:81:17

  - index.js:435 getDirParts
    [hello-world]/[chokidar]/index.js:435:31

  - index.js:442 FSWatcher._getWatchHelpers
    [hello-world]/[chokidar]/index.js:442:18

  - nodefs-handler.js:460 FSWatcher.NodeFsHandler._addToNodeFs
    [hello-world]/[chokidar]/lib/nodefs-handler.js:460:17

  - index.js:648 FSWatcher.<anonymous>
    [hello-world]/[chokidar]/index.js:648:12

  - index.js:16
    [hello-world]/[async-each]/index.js:16:7

  - Array.forEach

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-hello-world@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-starter-hello-world@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Samuel Bouyé\AppData\Roaming\npm-cache\_logs\2019-02-15T22_01_37_236Z-debug.log

**Comment by wardpeet** [comment]
Could you give us some more steps on how to reproduce this?

It looks like you're using windows and a package called snapdragon
