### ISSUE TITLE
Docs: Gatsby Governance Model

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#11805]
In the new contributing docs, it would be good to document Gatsby's Governance Model. From [oss-watch](http://oss-watch.ac.uk/resources/governancemodels):

> A governance model describes the roles that project participants can take on and the process for decision making within the project. In addition, it describes the ground rules for participation in the project and the processes for communicating and sharing within the project team and community. In other words it is the governance model that prevents an open source project from descending into chaos.

We have an [RFC process](https://www.gatsbyjs.org/docs/rfc-process/), and this document could sit alongside it to communicate more about the Gatsby process to contributors.

Here is the Vue.js version: https://github.com/vuejs/vue/wiki/Governance-Document

To close this issue, we need to write a governance model for Gatsby and include the content in the contributing section.

**Comment by marcysutton** [comment]
Hey @calcsam, any interest in helping us work on this governance model doc? Your work on the Gatsby Philosophy doc was so appreciated! 

On a related note, it's worth looking to the Wordpress community for examples of why we need governance outlined and followed. Here's a thread for some food for thought: https://twitter.com/mor10/status/1113223629804699648

**Comment by mujeex** [comment]
@marcysutton Hey! I'd like to try working on this issue if it's still up for grabs. With adequate provision of guidance from you, I'm sure I can make it work. Thanks.

**Comment by caitlinthefirst** [comment]
Hey, @mujeex ! I have a draft that's been "in progress" for a while that I'd love another set of eyes on. If you email me at caitlin@gatsbyjs.com, I can share the doc with you. Thanks!
