### ISSUE TITLE
docs: add a workshop/presentation template?

### ISSUE THREAD

**Issue by riddla** [gatsbyjs/gatsby#11803]
## Summary

The Gatsby documentation could contain material for presentations and/or workshops.

### Motivation

Ever since I stumbled upon it, I was very impressed by Cypress.io's documentation. In particular that they are providing [material for a full workshop](https://gatsby.app/discord) on using their product.
I was wondering if Gatsby could provide something similar?

There are probably a lot of developers that are exited about Gatsby (like me). And there are probably also a lot of them that don't have the time, the creativity or some other reason putting together decent presentation, live coding session or workshop material. Nevertheless they would be willing to spread the word to their web dev friends or colleagues. Why not give them a head start?

Maybe by reusing presentations that were already given by Gatsby team members? And/or reusing existing marketing material? Videos ... you name it.

**Comment by riddla** [comment]
(Having written this, I found https://github.com/gatsbyjs/gatsby/issues/8847. So maybe my take on it is obsolete.)

**Comment by marcysutton** [comment]
I'm working on this page right now, so this is super timely! Thanks for opening an issue. When I get my PR submitted I'll link to this so we can track it.
