### ISSUE TITLE
URL with and without trailing slash behaves differently in production

### ISSUE THREAD

**Issue by williamkhshea** [gatsbyjs/gatsby#11814]
## Description

For URL with a trailing slash, the page seems to be server-side rendered first (not sure about this) where windows.innerWidth property doesn't exist.

I have a carousel component which needs the screen size for correctly rendering itself. 

DOM downloaded is empty for URL without trailing slash
<img width="1216" alt="screenshot 2019-02-16 at 11 35 05 am" src="https://user-images.githubusercontent.com/4775489/52894085-056cdf80-31df-11e9-8562-3ea2d5dda026.png">

DOM is ready for URL with a trailing slash
<img width="1429" alt="screenshot 2019-02-16 at 11 38 14 am" src="https://user-images.githubusercontent.com/4775489/52894102-60063b80-31df-11e9-93b8-1818d29b68bd.png">

This happends only for production.

### Steps to reproduce

Go to https://www.mralife.com/grenson-fred-brogue-boot-review and https://www.mralife.com/grenson-fred-brogue-boot-review/

You will see the carousel render for https://www.mralife.com/grenson-fred-brogue-boot-review but not for https://www.mralife.com/grenson-fred-brogue-boot-review/.

### Expected result

Both URL should behave the same and render the carousel correctly.

### Actual result

The URL with a trailing slash doesn't render the carousel.

### Environment

  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5675R CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.109
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.1.4 => 2.1.4 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-plugin-canonical-urls: ^2.0.10 => 2.0.10 
    gatsby-plugin-catch-links: ^2.0.11 => 2.0.11 
    gatsby-plugin-favicon: ^3.1.4 => 3.1.5 
    gatsby-plugin-feed: 2.0.12 => 2.0.12 
    gatsby-plugin-google-analytics: 2.0.14 => 2.0.14 
    gatsby-plugin-lodash: ^3.0.4 => 3.0.4 
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17 
    gatsby-plugin-offline: ^2.0.23 => 2.0.23 
    gatsby-plugin-react-helmet: 3.0.6 => 3.0.6 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-sharp: 2.0.20 => 2.0.20 
    gatsby-plugin-sitemap: 2.0.5 => 2.0.5 
    gatsby-remark-autolink-headers: 2.0.12 => 2.0.12 
    gatsby-remark-external-links: ^0.0.4 => 0.0.4 
    gatsby-remark-images-contentful: ^2.0.8 => 2.0.8 
    gatsby-source-contentful: ^2.0.29 => 2.0.29 
    gatsby-transformer-remark: 2.2.5 => 2.2.5 
  npmGlobalPackages:
    gatsby-cli: 2.4.6

**Comment by wardpeet** [comment]
I'm not seeing a carousel 🙈 when visiting `https://www.mralife.com/grenson-fred-brogue-boot-review/` I get redirected to `https://www.mralife.com/grenson-fred-brogue-boot-review`.

Could you add some extra info to put me in the right direction ^^
