### ISSUE TITLE
Docs: Triaging Github Issues

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#11810]
As per the discussion in [rfcs/29](https://github.com/gatsbyjs/rfcs/pull/29#discussion_r257195791), there will soon be a page on Triaging Github Issues in the Gatsby contributing docs. This issue acts as a reminder to fill in the content! 

@sidharthachatterjee can you help us out with this?

![Empty page for Triaging Github Issues](https://user-images.githubusercontent.com/1045233/52888824-11e72e80-3132-11e9-87f3-6459b22e736a.png)

**Comment by marcysutton** [comment]
This one shouldn't be closed! There is work being done in https://github.com/gatsbyjs/gatsby/pull/12406

**Comment by thecodingaviator** [comment]
Hi, @marcysutton I see that there has been very less progress on the PR relating to this issue. Is this up for takes?

cc: @sidharthachatterjee

**Comment by marcysutton** [comment]
Closed with https://github.com/gatsbyjs/gatsby/pull/12406.
