### ISSUE TITLE
Access to unmodified Original Images is not available

### ISSUE THREAD

**Issue by mdornseif** [gatsbyjs/gatsby#11829]
## Description

For my application I have to serve bit-Identical versions of Images - preferable from static paths. 

https://github.com/gatsbyjs/gatsby/issues/10909 shows that an images path changes on configuration changes, even if the (bitstream) content of an Image stays the same. ([Cool URIs don't change](https://www.w3.org/Provider/Style/URI))

https://github.com/gatsbyjs/gatsby/issues/11672 is a little unclear to me but would be solved with access to an `originalImg`. But currently the `originalImg` does not provide access to the unmodified (bitstream) of the Source image but to an processed Version. 

### Steps to reproduce

    git clone git@github.com:mdornseif/gatsby-original-image-issue.git
    cd gatsby-original-image-issue ; yarn ; gatsby build
    # Find image in original size
    find public/ -name salty_egg.jpg | xargs file | grep 2048x1536
    public/static/8058f3f26913fea3b6a89a73344fe94a/105fb/salty_egg.jpg: JPEG image data, progressive, precision 8, 2048x1536, frames 3

### Expected result

`./content/blog/hello-world/salty_egg.jpg` and `./public/static/8058f3f26913fea3b6a89a73344fe94a/105fb/salty_egg.jpg` should be identical because the "original image" was requested.

### Actual result

Images are same size but wildly different. The image used by `gatsby-plugin-sharp.originalImg`  and `gatsby-remark-images.linkImagesToOriginal` is the same size as the source image but optimised and processed by sharp.

    $ ls -l content/blog/hello-world/salty_egg.jpg public//static/8058f3f26913fea3b6a89a73344fe94a/105fb/salty_egg.jpg
    -rw-r--r--  1 md  staff  684322 Feb 16 20:05 content/blog/hello-world/salty_egg.jpg
    -rw-r--r--  1 md  staff  234323 Feb 16 20:09 public//static/8058f3f26913fea3b6a89a73344fe94a/105fb/salty_egg.jpg

    $ file content/blog/hello-world/salty_egg.jpg  public//static/8058f3f26913fea3b6a89a73344fe94a/105fb/salty_egg.jpg
    content/blog/hello-world/salty_egg.jpg:                              JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=8, manufacturer=Nokia], baseline, precision 8, 2048x1536, frames 3
    public//static/8058f3f26913fea3b6a89a73344fe94a/105fb/salty_egg.jpg: JPEG image data, progressive, precision 8, 2048x1536, frames 3

### Suggested changes

Changing  `originalImg` to provide a reference to an unmodified version of the original image file probably would break assumptions in existing code. Adding something like `unprocessedImage` might minimise changes but increases API surface.

### Environment

```
$ npx gatsby info --clipboard

  System:
    OS: macOS High Sierra 10.13.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 65.0.3325.162
    Safari: 11.1
  npmPackages:
    gatsby: ^2.0.118 => 2.0.118 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-plugin-emotion: ^4.0.3 => 4.0.3 
    gatsby-plugin-feed: ^2.0.13 => 2.0.13 
    gatsby-plugin-google-analytics: ^2.0.13 => 2.0.13 
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17 
    gatsby-plugin-netlify: ^2.0.10 => 2.0.10 
    gatsby-plugin-offline: ^2.0.23 => 2.0.23 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20 
    gatsby-remark-copy-linked-files: ^2.0.9 => 2.0.9 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-remark-prismjs: ^3.2.4 => 3.2.4 
    gatsby-remark-responsive-iframe: ^2.0.9 => 2.0.9 
    gatsby-remark-smartypants: ^2.0.8 => 2.0.8 
    gatsby-source-filesystem: ^2.0.20 => 2.0.20 
    gatsby-source-ghost: ^3.3.0 => 3.3.0 
    gatsby-transformer-remark: ^2.2.4 => 2.2.4 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13 
  npmGlobalPackages:
    gatsby-cli: 2.4.10
```

**Comment by wardpeet** [comment]
I will be checking this out tomorrow.

**Comment by frantic1048** [comment]
Hi there, any update on this issue ?
