### ISSUE TITLE
Starter search should be case insensitive

### ISSUE THREAD

**Issue by NeverMendel** [gatsbyjs/gatsby#11820]
I think that the starter search should be case insensitive. I believe it is better also because on mobile devices the first letter is capitalized by default.

I can fix it!

Search with first letter capitalized: ![image](https://user-images.githubusercontent.com/28535750/52900745-1bd46480-31fa-11e9-8f95-4f7589b82c02.png)

Search with first letter non capitalized: ![image](https://user-images.githubusercontent.com/28535750/52900879-39a2c900-31fc-11e9-8363-84f85d5718bc.png)

**Comment by wardpeet** [comment]
I think this is a good idea

@gatsbyjs/ecosystem wdyt?
