### ISSUE TITLE
Gatsby Remarkable integration

### ISSUE THREAD

**Issue by DxCx** [gatsbyjs/gatsby#11827]
Hey!

Ive made a pretty nice integration between gatsby and remarkable, including rehype of React components.

An example live editor can be found here:
https://discretize.eu/editor

While this whole website is running gatsby, you can browse to see the full results.

Is there any interest in such integration? (I was thinking of open source it back to the community now that it works well for long enough)

Or am i alone in here? Hehe

**Comment by wardpeet** [comment]
I'm unsure what you're asking 🙄. Do you mean you want to create a React Component for it? Sorry for misunderstanding 🤦‍♂️

**Comment by DxCx** [comment]
No

The website is running different engine (remarkable not remark). Which is an integration layer ive written with React components support (there is a file to map tag name (<Table>/<Row>)

I was asking if any more people wants to use this integration because if so ill work on opensource it

**Comment by yogeshkotadiya** [comment]
As I see that it adds more functionality to markdown just like MDX.
He's asking the community to try this as an alternative markdown renderer. 
If so you can create a plugin and publish to Gatsby Plugins, you can find more info on [Create Gatsby Plugin](https://www.gatsbyjs.org/docs/plugin-authoring/) page.

**Comment by DxCx** [comment]
Yeah, there is basic md parse + components from react. (With a help of webpack plugin ive written to build used components assets as well)

And Also framework to add plugins both for client and server or only server side.
(For example i got sharp, just like remark one has, also, we cache api requests during build time so we will have faster load times)

The thing is that i am very flooded on my personal life, i want to do the work to export it and make it a plug-in but i want to see if people are interested first.
I thought this was the best place to ask..

(P.S i also wrote alot of code for apollo graphql server so i know graphql internals pretty good, this is the reason i choose gatsby to start with)

**Comment by calpa** [comment]
You can create a plugin such as gatsby-plugin-remarkable to enable remarkable.js in gatsby.

I had used remarkable.js in previous version of my blog system.
