### ISSUE TITLE
TypeError: Cannot read property 'buildError' of undefined

### ISSUE THREAD

**Issue by antoinerousseau** [gatsbyjs/gatsby#11826]
## Description

JS errors in `gatsby-node.js#onPostBuild` (and maybe in other places too) are obscure.

### Steps to reproduce

* run `gatsby new gatsby-test` 
* add this to `gatsby-node.js`:
```js
exports.onPostBuild = async () => {
    const arr = []
    const arr = []
}
```
* run `gatsby build`

### Expected result

    SyntaxError: Identifier 'arr' has already been declared

### Actual result

    TypeError: Cannot read property 'buildError' of undefined

### Environment

```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.4 => 2.1.4
    gatsby-image: ^2.0.29 => 2.0.29
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17
    gatsby-plugin-offline: ^2.0.23 => 2.0.23
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20
    gatsby-source-filesystem: ^2.0.20 => 2.0.20
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13
  npmGlobalPackages:
    gatsby-cli: 2.4.10
```

**Comment by wardpeet** [comment]
You're completely right. Sadly it's an upstream bug on [babel's side #8617](https://github.com/babel/babel/issues/8617). I've just subscribed to it and I'll try to help pinpoint the issue here.
