### ISSUE TITLE
Add option to get date in local or specified time zone

### ISSUE THREAD

**Issue by mono0x** [gatsbyjs/gatsby#11832]
## Summary

Add option to get `date` in local or specified time zone.

### Basic example

Add option to `date` type.

```
  query blogListQuery($skip: Int!, $limit: Int!) {
    ...
    allMarkdownRemark(...) {
      edges {
        node {
          ...
          frontmatter {
            date(formatString: "MMMM DD, YYYY", local: true) <-- use local time zone
            date(formatString: "MMMM DD, YYYY", tz: "Asia/Tokyo") <-- use specified time zone
          }
        }
      }
    }
  }
```

and/or add option to `gatsby-config.js`.

### Motivation

Display date in an easy-to-understand way for main readers of the website.

**Comment by wardpeet** [comment]
Why do you want to do this inside the query and not inside the page or component itself?

**Comment by mono0x** [comment]
Thank you for your comment. I didn't know I can get raw string of the `date` if `formatString` is not specified. 

https://github.com/gatsbyjs/gatsby/blob/445f5ff7508ab613967e18b32490e3feffd7730c/packages/gatsby/src/schema/types/type-date.js#L120

I could display date in local time zone using following query and page.

```
  query blogListQuery($skip: Int!, $limit: Int!) {
    ...
    allMarkdownRemark(...) {
      edges {
        node {
          ...
          frontmatter {
            date
          }
        }
      }
    }
  }
```

```js
import moment from 'moment'

<small>{moment(node.frontmatter.date).local().format(`MMMM DD, YYYY`)}</small>
```

Therefore, I think that applying time zone in query is not absolutely necessary. However, if Gatsby supports `formatString`, it is more natural to be able to specify time zone of formatted time.

**Comment by KyleAMathews** [comment]
Re-opening this as it's a valid use case as if you're displaying dates e.g. for an event, you often know what time zone you want to display and it'd be nice to generate that at build-time vs having to load a library for it.
