### ISSUE TITLE
Mappings don't support 1:N on reverse relationships

### ISSUE THREAD

**Issue by pauleveritt** [gatsbyjs/gatsby#11838]
## Description

When using a `mapping` in `gatsby-config.js`, reverse relationships work as described in the docs but only for a 1:1 relationship. A 1:N relationship doesn't return an array, it just returns a single value.

This was discussed also in #11151

### Steps to reproduce

Here is a [reproducible repo](https://github.com/pauleveritt/sourceNodes-bug-11151) that illustrates the bug as well has links to a video illustrating it.

### Expected result

When expanding the node in a page query, I should get an array of items. Meaning, it should work the same as a forward relationship for 1:N.

### Actual result

I only get a single value.

**Comment by wardpeet** [comment]
@pieh it seems like you have most context about this

**Comment by pauleveritt** [comment]
Not stale.

**Comment by freiksenet** [comment]
@pauleveritt This might have been fixed in latest gatsby, I wonder if you could see if it works for you.

**Comment by pauleveritt** [comment]
@freiksenet I just tried (albeit with `@link`) and it worked. Closing. Thanks for checking back!
