### ISSUE TITLE
gastby-plugin-sharp: constantly regenerating same images on subsequent query runs in dev mode

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#11837]
## Description

We use `fs-exists-cached` (memoized `fs.lstat(sync)`) in `gatsby-plugin-sharp` to check if processed file already exists to skip processing. This works in production, but in development cause problem:

If file doesn't exist on initial check, it will cache this -> sharp plugin will generate image. On next query run that would cause sharp plugin processing we use cached check and regenerate same image.

Ideally we would invalidate that cached value for the file, but `fs-exists-cached` doesn't support that currently. We could fork it (it's pretty low weight - https://github.com/isaacs/fs-exists-cached/blob/master/index.js ) and add invalidation mechanism and use that once images are generated.

**Comment by DSchau** [comment]
@pieh this is a reasonably straight-forward fix. Would you be opposed to just swapping to fs.existsSync here, or do you think the performance benefit is worth the cost of forking/maintaining an fs-exists-cached with an invalidation mechanism?

**Comment by pieh** [comment]
Let's just switch. @oorestisime already kind of did that in https://github.com/gatsbyjs/gatsby/pull/12129 when he was working on another `gatsby-plugin-sharp` issue

**Comment by oorestisime** [comment]
FYI I am planning on rebasing my PRs for sharp plugin on current master today or tomorrow. This should be taken care of in on of my PRs.

**Comment by wardpeet** [comment]
@pieh I guess this is fixed?

**Comment by pieh** [comment]
Yes, it should be fixed. Would be good to verify before closing, so let me do that

**Comment by wardpeet** [comment]
Going to close this :)
