### ISSUE TITLE
is there a way to query markdown files in sub-folders ?

### ISSUE THREAD

**Issue by engmagdy87** [gatsbyjs/gatsby#11835]
## Summary
in normal case, if i have this structure 

pages
&nbsp;&nbsp;|_ markdown
&nbsp;&nbsp;&nbsp;&nbsp;|_  1.md
&nbsp;&nbsp;&nbsp;&nbsp;|_  2.md 
&nbsp;&nbsp;&nbsp;&nbsp;|_  3.md

this query in ```gatsby-node.js```will read all md files
`
{
            allMarkdownRemark {
              edges {
                node {
                  frontmatter {
                    path
                  }
                }
              }
            }
          }
`

BUT if the structure is
pages
&nbsp;&nbsp;|_ markdown
&nbsp;&nbsp;&nbsp;&nbsp;|_  category_1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|_  1.md
&nbsp;&nbsp;&nbsp;&nbsp;|_  category_2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|_  1.md
&nbsp;&nbsp;&nbsp;&nbsp;|_  category_3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|_  1.md

the query didn't recognize the md files

**Comment by loremipson** [comment]
I haven't had any issues with recursive files in gatsby. What does your `gatsby-config.js` look like?

**Comment by engmagdy87** [comment]
const config = require('./config/site')

module.exports = {
  siteMetadata: {
    ...config,
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/static/images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages/`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          // gatsby-remark-relative-images must
          // go before gatsby-remark-images
          {
            resolve: `gatsby-remark-relative-images`,
          },
          {
            resolve: `gatsby-remark-images`,
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 700,
              backgroundColor: 'transparent',
            },
          },
        ],
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    // 'gatsby-plugin-offline',
    'gatsby-plugin-sitemap',
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'Mai Magdy Portfolio',
        short_name: 'Mai Magdy Portfolio',
        start_url: '/',
        background_color: '#daa501',
        theme_color: '#daa501',
        display: 'minimal-ui',
        icon: 'static/images/assets/manifest-logo.png', // This path is relative to the root of the site.
      },
    },
    {
      resolve: 'gatsby-plugin-typography',
      options: {
        pathToConfigModule: 'config/typography.js',
      },
    },

    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.app/offline
    // 'gatsby-plugin-offline',
  ],
}

**Comment by yogeshkotadiya** [comment]
Try adding another `gatsby-source-filesystem` in your config file.
```js
{
resolve: `gatsby-source-filesystem`,
options: {
name: `markdown`,
path: `${__dirname}/src/pages/markdown`,
},
```

See if this solves your issue.
