### ISSUE TITLE
Render just what is visible in viewport

### ISSUE THREAD

**Issue by frederikhors** [gatsbyjs/gatsby#11843]
I'm newbie in Gatsby and I'm wondering how to render just what is visible in the viewport in a long home page.

Not just for performance reasons, also for animation ones.

Let's say I have texts and images with https://daneden.github.io/animate.css styles and I want to animate them just when I scroll to them in viewport.

Something like:
- https://github.com/matthieua/WOW or
- https://github.com/twobin/react-lazyload

**Comment by yogeshkotadiya** [comment]
You can use [react-visibilty-sensor](https://github.com/joshwnj/react-visibility-sensor) to trigger your animations when they become visible in Viewport.

**Comment by wardpeet** [comment]
It all depends on what you want to do but it's not Gatsby specific. You could use something like https://github.com/brigade/react-waypoint to trigger specific classnames or whatever you want to do.

**Comment by wardpeet** [comment]
Thanks so much for opening this issue! As stated, this is slightly tangential to Gatsby, and it seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby :muscle:
