### ISSUE TITLE
gatsny build fails at: Building static HTML for pages failed with 

### ISSUE THREAD

**Issue by zilahir** [gatsbyjs/gatsby#11841]
## Description
I have been struggling with this for weeks now.

`gatsby develop` works as expected, all the data getting processed, all the pages rendered correctly, but `gatsby build` fails with the following issue: 

`error Building static HTML for pages failed`

```
SyntaxError: Unexpected end of JSON input

  - JSON.parse
```

### Steps to reproduce

get any api endpoint which returns json like as string, then use: 

`let demo = JSON.parse(sometJson)`,

then try to map it through: 

`demo.map((e, i) => (`

In `dev`, works like charm, as it should. The issues occurs when i am trying to build. 

### Expected result

Not throwing `unexpected end of json input`

### Actual result

See image attachment. 
<img width="770" alt="screen shot 2019-02-17 at 23 23 04" src="https://user-images.githubusercontent.com/6687149/52919482-993bca00-330b-11e9-8faa-fa23879215f6.png">

### Environment

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 65.0
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.76 => 2.0.76
    gatsby-image: ^2.0.20 => 2.0.25
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12
    gatsby-plugin-offline: ^2.0.16 => 2.0.20
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5
    gatsby-plugin-sass: ^2.0.7 => 2.0.7
    gatsby-plugin-sharp: ^2.0.14 => 2.0.16
    gatsby-source-filesystem: ^2.0.8 => 2.0.12
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.7
```

I have found an other issue which may be related, but that one was already closed, even if the issue seems super similar. 

https://github.com/gatsbyjs/gatsby/issues/3094

I hace created a gist and put my entire json which probably causing the issue

**Comment by gurpreet-hanjra** [comment]
hello @zilahir could you provide a minimal reproduction of the issue, maybe a github repo?

**Comment by zilahir** [comment]
hello @gurpreet-hanjra , thank for your reply. well i can give u a github repo, but then i'd need to provide you my API credentials, since you won't be able to test it without those. I will figure out something soonish! 

Thank you!

**Comment by gurpreet-hanjra** [comment]
Great, thank you.

**Comment by wardpeet** [comment]
@zilahir you could also mock the API with a JSON file as I'm pretty sure it's not really Gatsby related but more on the data part of it. So if you could reproduce it with maybe soemthing like below that would be enough :)

```
const demo = JSON.parse(`your response`);

return demo.map((e, i) => (`

```
