### ISSUE TITLE
gatsby-plugin-page-creator found 1 low severity vulnerability

### ISSUE THREAD

**Issue by doahuang** [gatsbyjs/gatsby#11847]
Low | Regular Expression Denial of Service     
--- | ---
Package | braces
Patched in | >=2.3.1
Dependency of | gatsby
Path | gatsby > gatsby-plugin-page-creator > chokidar > anymatch > micromatch > braces
More info | https://npmjs.com/advisories/786  

```
└─┬ gatsby@2.1.4
  ├─┬ chokidar@2.1.1
  │ └── braces@2.3.2 
  └─┬ gatsby-plugin-page-creator@2.0.6
    ├─┬ chokidar@1.7.0
    │ └─┬ anymatch@1.3.2
    │   └─┬ micromatch@2.3.11
    │     └── braces@1.8.5 
    └─┬ micromatch@3.1.10
      └── braces@2.3.2  deduped
```
This is caused by dependent chokidar@1.7.0

**Comment by wardpeet** [comment]
@pieh or @DSchau were any of you looking at this one?

**Comment by maxwell-k** [comment]
I'm facing the same, but with both `gatsby-plugin-page-creator` and `gatsby-source-filesystem`. Is this issue specific to `gatsby-plugin-page-creator`?  Should I open a separate issue for `gatsby-source-filesystem`?  

The only related issue I can find is https://github.com/gatsbyjs/gatsby/issues/10336 but it was closed for inactivity, and doesn't mention security.

```
✂
├─┬ gatsby-source-filesystem@2.0.20
│ ├── @babel/runtime@7.3.1 deduped
│ ├── better-queue@3.8.10 deduped
│ ├── bluebird@3.5.3 deduped
│ ├─┬ chokidar@1.7.0
│ │ ├─┬ anymatch@1.3.2
│ │ │ ├─┬ micromatch@2.3.11
│ │ │ │ ├─┬ arr-diff@2.0.0
│ │ │ │ │ └── arr-flatten@1.1.0 deduped
│ │ │ │ ├── array-unique@0.2.1
│ │ │ │ ├─┬ braces@1.8.5
✂
```

**Comment by yogeshkotadiya** [comment]
Fix is already merged #11862

**Comment by maxwell-k** [comment]
@yogeshkotadiya I don't think the PR you pointed to upgrades chokidar? Are you sure it fixes this issue? 

I think that PR just fixes a test and doesn't address the low severity vulnerabilities with `gatsby-plugin-page-creator` or `gatsby-source-filesystem`

**Comment by gh0stwrit3r** [comment]
How is the update doing? 
This vulnerability breaks CI for us... :/

Greetings
