### ISSUE TITLE
Empty `<div id="___gatsby"><div style="outline:none" tabindex="-1" role="group"></div></div>` in production

### ISSUE THREAD

**Issue by JustFly1984** [gatsbyjs/gatsby#11846]
If I'm opening `view-source:https://www.agrariansupply.com/` - I see incomplete static rendering with empty, but if I navigate to `view-source:https://www.agrariansupply.com/index.html` static rendering is complete.

Same thing happens on every statically build page.

for example:
view-source:https://www.agrariansupply.com/product/lm-6-high-porosity-mix-ca/
view-source:https://www.agrariansupply.com/product/lm-6-high-porosity-mix-ca/index.html

I'm hosting on netlify.com

Is there any way to fix this behavior in gatsby's config, or should I ask netlify support?

**Comment by wardpeet** [comment]
What do you mean by an incomplete static rendering?

I believe you are having the following issue:
https://www.gatsbyjs.org/packages/gatsby-plugin-offline/#notes

By using gatsby-plugin-offline we optimize the ssr served paged so we don't ship to much data each time to our users. For search engines this doesn't make a difference, they just get the original SSR page.

**Comment by JustFly1984** [comment]
@wardpeet Thank you for explanation, I've missed this part of docs!
