### ISSUE TITLE
Allow cancellation or interruption of route updates

### ISSUE THREAD

**Issue by kamranayub** [gatsbyjs/gatsby#11852]
## Summary

The `onPreRouteUpdate` hook should allow the user to cancel the route update asynchronously.

### Basic example

I'm thinking something as simple as:

```js
export const onPreRouteUpdate = ({ location, prevLocation }) => {

    // return a callback to indicate an async router update
	return ({ resolve, reject ) => { 
	  // trigger a modal/dialog to prompt user
      showModal({ onSuccess: resolve, onDismiss: reject })
      
      // or something async
      determineIfCancel().then(areWeCool => areWeCool ? resolve() : reject());
    }
}
```

### Motivation

In order to build app-like experiences with Gatsby where users are entering information or making changes, it's typical to want to warn the user when they're leaving a page. We can hook into `onbeforeunload` but internal Reach Router updates are not subject to that so they are bypassed. Reach Router also doesn't provide an internal mechanism to hook into that could interrupt a route transition either so the Gatsby `onPreRouteUpdate` is the closest we have.

There are probably multiple ways to handle this but when I reviewed the Gatsby documentation, I went to the `onPreRouteUpdate` method because I expected to be able to do something there since that's a pattern I'm used to seeing in `onPre*` methods.

**Comment by wardpeet** [comment]
Hey! Thanks for submitting this feature request. This is probably going to need some discussions. I'm not sure this is something we should fix in onPreRouteUpdate but rather in our React application itself.

This is just something from the top of my head so take this with a grain of salt. You could write your own [gatsby-link](https://www.gatsbyjs.org/docs/gatsby-link/) component or just enhance ours.

The caveat with `gatby-link` is that it does not take care of pop state (back buttons).

**Comment by kamranayub** [comment]
Right, yes, I did think of that but like you said since this will primarily
be used within a mobile context the popState is kind of a must-have.

However, that said, in my specific case I believe I can just rethink how I
do my data input to replace with a different flow that avoids needing to
warn the user.

I still think this is probably a good use case to solve with Gatsby,
whether that means a new hook or an enhancement to Reach Router. React
Router v4 has the Prompt component that addresses this.

**Comment by viggin543** [comment]
Any updates on this issue?
Im having a similar problem.
