### ISSUE TITLE
Circular Json not handled in gatsby-source-contentful plugin

### ISSUE THREAD

**Issue by spatrame** [gatsbyjs/gatsby#1186]
I have content which is referencing to the same content in contentful.

ex: A has reference of B,  B has reference of C, and C has reference of A.

A -> B -> C -> A

If I have such data in contentful the gatsby source contentful plugin will not work. 

Could you please let me know how can we fix it? Will graphql handles circularjson ?

**Comment by KyleAMathews** [comment]
Let me look into this today.

**Comment by KyleAMathews** [comment]
The circular JSON problem needed fixed in both core and in the plugin. Working on a PR with fixes for this and some other tweaks to the contentful plugin.

**Comment by KyleAMathews** [comment]
https://github.com/gatsbyjs/gatsby/pull/1202 fixes this and a few other issues I found with the contentful source plugin.

**Comment by KyleAMathews** [comment]
#1202 is merged now. I published a canary release with the fix and will be publishing another beta early next week.
