### ISSUE TITLE
Running 'gatsby build' results in different html structure to that of 'gatsby develop'

### ISSUE THREAD

**Issue by jonathanpuc** [gatsbyjs/gatsby#11860]
## Description

When running 'gatsby build' command and then viewing the website with 'gatsby serve', the website html is different to the actual markup written. At surface level, I first thought there was an issue with the sass/css as I've noticed there have been quite a few issues, but having observed DOM elements closer - I noticed they were muddled up.

However, when refreshing the page, for a split second everything looks normal but then goes back to the incorrect structure.

CORRECT (gatsby develop):
<img width="490" alt="screen shot 2019-02-18 at 10 03 49 pm" src="https://user-images.githubusercontent.com/26730919/52947511-10846300-33cb-11e9-8d22-6ec042166b07.png">

INCORRECT (gatsby build and serve):
<img width="486" alt="screen shot 2019-02-18 at 10 02 49 pm" src="https://user-images.githubusercontent.com/26730919/52947493-fc406600-33ca-11e9-86ed-c10e40b6b2dc.png">

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

Running build and serve should result in the same website output as running develop

### Actual result

Website looks totally different due to weird build/bundling behaviour

### Environment

 System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /anaconda/bin/python
  Browsers:
    Chrome: 72.0.3626.109
    Safari: 12.0
  npmPackages:
    gatsby: ^2.1.4 => 2.1.4
    gatsby-image: ^2.0.29 => 2.0.29
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17
    gatsby-plugin-offline: ^2.0.23 => 2.0.23
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-sass: ^2.0.10 => 2.0.10
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20
    gatsby-source-filesystem: ^2.0.20 => 2.0.20
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13
  npmGlobalPackages:
    gatsby: 2.1.4

**Comment by wardpeet** [comment]
Do you have any repo for reproduction? I haven't seen this bug yet so it might be a configuration problem.

**Comment by jonathanpuc** [comment]
@wardpeet a fresh gatsby install seemed to fix it on this particular machine (I was previously using a [bulma starter](https://www.gatsbyjs.org/starters/amandeepmittal/gatsby-bulma-quickstart/). But last night at home, a fresh install didn't help (see first comment above for env).

System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.2 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.109
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.4 => 2.1.4
    gatsby-image: ^2.0.29 => 2.0.29
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17
    gatsby-plugin-offline: ^2.0.23 => 2.0.23
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-sass: ^2.0.10 => 2.0.10
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20
    gatsby-source-filesystem: ^2.0.20 => 2.0.20
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13
  npmGlobalPackages:
    gatsby-cli: 2.4.8


You can perhaps try to recreate it with this [repo](https://github.com/jonathanpuc/gatsby-dummy-bug), is it possible that something the way I'm importing trying to import a global scss file while also using css modules is creating inconsistent behaviour?

**Comment by jonathanpuc** [comment]
Problems resolved. Created root component file which imports main.scss and is then imported into gatsby-browser.js and gatsby-ssr.js as the root element.
