### ISSUE TITLE
[gatsby-transformer-remark] null heading when in backticks

### ISSUE THREAD

**Issue by diegohaz** [gatsbyjs/gatsby#11879]
## Description

It's related to #5436. Opening a new issue per @KyleAMathews' [comment](https://github.com/gatsbyjs/gatsby/issues/5436#issuecomment-419614254).

When headings are in backticks (e.g. <code># \`foo\`</code>), the `headings` array from `markdownRemark` have `null` value.

### Steps to reproduce

This is the minimum possible reproduction I could come with. Hope it's enough.
https://codesandbox.io/s/502pwvro94

### Expected result

`headings` should be:
```json
[
  {
    "value": "Normal title",
    "depth": 1
  },
  {
    "value": "Code title", <--------
    "depth": 1
  }
]
```

### Actual result

```json
[
  {
    "value": "Normal title",
    "depth": 1
  },
  {
    "value": null, <--------
    "depth": 1
  }
]
```

### Environment

```
  System:
    OS: Linux 4.17 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (8) x64 Intel Xeon Processor (Skylake, IBRS)
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 8.14.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: ^2.1.4 => 2.1.4
    gatsby-image: ^2.0.29 => 2.0.29
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17
    gatsby-plugin-offline: ^2.0.23 => 2.0.23
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20
    gatsby-source-filesystem: ^2.0.20 => 2.0.20
    gatsby-transformer-remark: 2.2.5 => 2.2.5
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13
```

**Comment by stefanprobst** [comment]
Thanks for the reproduction! The issue is that we only use `text` nodes, and ignore `inlineCode` nodes [here](https://github.com/gatsbyjs/gatsby/blob/e9345cd2fc299a3fd61de7cb5b640baf659180d4/packages/gatsby-transformer-remark/src/extend-node-type.js#L271).

**Comment by stefanprobst** [comment]
@diegohaz Could you try if #11888 works for you? Thanks

**Comment by stefanprobst** [comment]
Oh sorry, don't know why I missed your #11881
