### ISSUE TITLE
1200 people in the Gatsby GitHub org?

### ISSUE THREAD

**Issue by corysimmons** [gatsbyjs/gatsby#11876]
I just got invited to this org for some reason.

I thought maybe I was cool but then I saw 1200 other people in the org and now I feel like I'm part of some contributor marketing scheme.

In comparison "Facebook" has 180 people in their org.

@KyleAMathews ? ? ?

**Comment by jlengstorf** [comment]
@corysimmons hey Cory!

Gatsby’s policy is that anyone who contributes to the project will be invited to the org. The best part of Gatsby is its community, so we want to make it as easy as possible to join and participate in the community.

We put up regular updates for maintainers in the org's discussion area, but those can be opted out of if you don't want to see them.

So there's no marketing scheme or other strings attached — we just wanted to say thanks for being part of our community.

Let me know if you have any other questions! I’m going to close this issue, but definitely feel free to follow up here.

Thanks again!

**Comment by corysimmons** [comment]
Okay no problem. I was just curious how it worked since I'd never seen it before. Gonna dip to avoid 100+ GH Notifications every time I login. =)
