### ISSUE TITLE
Font loading fails without giving any errors

### ISSUE THREAD

**Issue by baobabKoodaa** [gatsbyjs/gatsby#11875]
## Summary

Can someone please explain how to load fonts in Gatsby? Edit: I resolved my issue in a different way, but I would still like to understand how to load fonts properly.

## Relevant information

I'm working on [this Gatsby starter](https://gatsby-starter-hero-blog.greglobinski.com/). If you scroll down and refresh the main page, you will notice that text jumps around during page load. I'm trying to fix that. Currently the browser renders "fallback font settings" first and then some JavaScript is executed which loads the real font and changes font-weight. This causes the jumpyness.

I don't have much experience with web fonts, React, Webpack or Gatsby. So I've been reading a lot and trying to figure out how font loading is supposed to be done. According to [this StackOverflow post](https://stackoverflow.com/a/22152625/4490400), I should be able to create several font-families in CSS and then try to load these in order. This way I could have a fallback font without any client side JS execution, and all my font-families could have custom font-weight settings etc. According to [this GatsbyJS doc](https://www.gatsbyjs.org/docs/adding-images-fonts-files/) I should be able to import a local font file with Webpack. The doc doesn't provide a complete example. So I tried to to refactor the code to pack the local font file with Webpack, then create font-families in CSS and then load them in order. For some reason it's failing without giving me any errors that I could debug. My browser is simply rendering the page with some default font. When I inspect the page I can see that it's trying to use the correct font-family. I also see that the font-family's url points to the correct woff2 file and the path created by Webpack resolves correctly. So why is my browser not rendering the font?

[Here is the diff from my refactor](https://github.com/baobabKoodaa/blog/commit/191d3a8a9bcb34d66d99a1b7015592c3d26cacc6).

What am I doing wrong? Can someone provide a complete working example of using fonts in GatsbyJS?

**Comment by t2ca** [comment]
I believe this is a good and easy way to import fonts in gatsby:
https://github.com/KyleAMathews/typefaces

`npm install --save typeface-open-sans`

In my layout.js file

`import 'typeface-open-sans/index.css'`

**Comment by baobabKoodaa** [comment]
Thanks, this worked quite nicely for me! (Although I still can't seem to get custom font-families working, but oh well)

**Comment by thundernixon** [comment]
@baobabKoodaa does this workflow help you, perhaps?

https://spectrum.chat/gatsby-js/general/self-hosting-fonts-on-gatbsy-v2~971fa5bd-6a95-4ac6-bf92-aedc59ed1bab?m=MTU0NTg4ODgzMjQ1NQ==

**Comment by baobabKoodaa** [comment]
@thundernixon Hmmh, so compared to my attempt:

`
import openSans from "...static/..."
src: url($openSans)
`

...you are instead doing:

`
src: url("...fonts/...")
`

If that indeed works, then it sounds like my issue has something to do with webpack. If I understand correctly, with your way of doing it the font doesn't get a hash in its filename, so we won't be able to cache it as efficiently (minor quibble, I know).

**Comment by thundernixon** [comment]
Ohh hmm, I don't know webpack that well, so I haven't realized that could be a problem. Yeah, I just have a very small global CSS for that calls the fonts, and I load that in the main layout components.

**Comment by baobabKoodaa** [comment]
> I believe this is a good and easy way to import fonts in gatsby:
> https://github.com/KyleAMathews/typefaces
> 
> `npm install --save typeface-open-sans`
> 
> In my layout.js file
> 
> `import 'typeface-open-sans/index.css'`

I can't get this to work on gatsby-default-starter. Here is a demo:

https://github.com/baobabKoodaa/font-problem-demo/commit/0b6e7c6bac41225ac0bc1612155f9fe5975b5de2

**Comment by t2ca** [comment]
Try the following without dash

`font-family: Open Sans;`

**Comment by baobabKoodaa** [comment]
Ah, of course! Thank you!
