### ISSUE TITLE
npm install --save gatsby-plugin-netlify

### ISSUE THREAD

**Issue by tommy3531** [gatsbyjs/gatsby#11872]
When I run npm install --save gatsby-plugin-netlify, I get the following error:
![error](https://user-images.githubusercontent.com/4014163/52968069-b905d900-3371-11e9-8347-2bb08ab831ab.png)

I ran npm audit fix, tried installing the peer dependency and still received the above error.

Expected Outcome:
When I ran npm install --save gatsby-plugin-netlify, it would install and create a netlify.toml file so I can redirect my netlify subdomain to my primary domain.

**Comment by yogeshkotadiya** [comment]
Not an error just warnings, that should not have any problems with netlify.
There is a PR [#11568](https://github.com/gatsbyjs/gatsby/pull/11568) landed to fix this warning.
But you can go ahead and deploy your site.
