### ISSUE TITLE
Feature request: ability to load critical resources first, non-critical resources after that

### ISSUE THREAD

**Issue by baobabKoodaa** [gatsbyjs/gatsby#11878]
## Summary

At this time images can either be lazy loaded (after the user has scrolled to position) _or_ loaded immediately as critical resources. It would be nice to have an option between these two extremes.

### Motivation

Imagine a use case like a typical blog: a lot of text, a few images. When a page is loaded, it would be nice to first fetch critical resources needed for first meaningful paint, and as soon as we're able, fetch the rest of the resources needed on this page. I was surprised I was not able to do this with Gatsby.

It seems my options are:
1. Mark all images as critical, unnecessarily slowing down first meaningful paint
2. Lazy load images, unnecessarily showing "loading artifacts" to the user (e.g. blur-up placeholder)

It would be nice if I could disable lazy loading _and_ still load critical images before other images on the page. Or a different approach could be to tweak _when_ lazy loading happens, so that I could perhaps start loading an image when the user is scrolling towards an image (rather than after they have scrolled to it).

I've put a [100 bounty on SO](https://stackoverflow.com/questions/54448386/gatsbyjs-optimize-when-to-fetch-images) in case someone knows how to achieve this goal with current version of Gatsby.

**Comment by wardpeet** [comment]
There are a few possibilities. You don't have to use gatsby-image, you can write your own image component that doesn't use Intersection Observer but things like requestIdleCallback or a simple setTimeout. The reason why we only use intersection observer is the benefit of reducing data usage, especially for mobile, where a lot of users can have poor connectivity and limited data plans.

We probably should expose some mechanism to manually trigger image loading. We could implement a mechanism that evaluates the critical prop so you can change it on the fly.

example
```
// state.shouldLoad = false
<Img fluid={myfluiddata} critical={state.shouldLoad}/>

// some time passes (setTimeout or whatever)
// state.shouldLoad = true
<Img fluid={myfluiddata} critical={state.shouldLoad} />
```

/cc @gatsbyjs/core
