### ISSUE TITLE
[feat]: add validation or normalization for pathPrefix, siteUrl, etc.

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#11871]
## Summary

We should validate siteMetadata.siteUrl (as a url) and pathPrefix (as a string starting with a forward slash and not ending with one) and warn or normalize when a trailing slash is detected.

### Basic example

See #11869 for an example of this causing issues. In effect:

- Certain keys can not contain a trailing slash
- We should warn when these values _do_ contain a trailing slash, rather than documenting this behavior with something like an inline comment like [`// Note: it must *not* have a trailing slash.`](https://www.gatsbyjs.org/docs/path-prefix/#production-build)

We'll want to update our [schema validation](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/joi-schemas/joi.js#L3-L15) with either a warning or outright normalization of the expected structure. See [this example](https://runkit.com/dschau/5c6ae2aff8150400120f142c) for a way we could normalize--but note that there could be a cleaner way to do this.

### Motivation

We should warn early (or normalize if we _know_ a structure should be a certain way), rather than relying on the user to investigate underlying functionality and read comments.

**Comment by tterb** [comment]
I'm interested in working on this if no one else is.

**Comment by DSchau** [comment]
@tterb all yours!

**Comment by tterb** [comment]
@DSchau While working on the normalizations, I noticed there seems to be a discrepancy in the documentation for the proxy url.  
More specifically, the [Gatsby Config](https://www.gatsbyjs.org/docs/gatsby-config/#proxy) page features a url with a trailing slash, whereas the [Proxying API Requests in Develop](https://www.gatsbyjs.org/docs/api-proxy/) page shows a url without a trailing slash.  

After looking further into the code, it looks like the example on the Gatsby Config page may be a mistake, but I wanted to check that I wasn't misunderstanding something and that the intention was for the normalizations to also be applied to these proxy values.
