### ISSUE TITLE
images didn't show when in gatsby build but when i run in gatsby develop images show correctly

### ISSUE THREAD

**Issue by anuar-fullstack** [gatsbyjs/gatsby#11887]
## Description

whenever i run gatsby build and run the production. images didn't shows. only svg files appear in may page. though. when i run gatsby build there is no error. and whenver i run it in gatsby develop. the images shows as expected.
### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

http://psdwizard.net/preview/limeproxiesV2/blog
http://psdwizard.net/preview/limeproxiesV2/blogposts/
http://psdwizard.net/preview/limeproxiesV2/about/

### Expected result

should show the images correctly.

### Environment

 System:
    OS: Linux 4.15 elementary OS 0.4.1 Loki
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
    Yarn: 1.10.1 - /usr/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Chrome: 69.0.3497.81
  npmPackages:
    gatsby: ^2.0.19 => 2.1.4
    gatsby-image: ^2.0.15 => 2.0.29
    gatsby-plugin-manifest: ^2.0.5 => 2.0.17
    gatsby-plugin-offline: ^2.0.11 => 2.0.23
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-sass: ^2.0.10 => 2.0.10
    gatsby-plugin-sharp: ^2.0.7 => 2.0.20
    gatsby-source-filesystem: ^2.0.20 => 2.0.20
    gatsby-source-storyblok: ^0.1.4 => 0.1.4
    gatsby-transformer-sharp: ^2.1.4 => 2.1.13
  npmGlobalPackages:
    gatsby-cli: 2.4.9

MY REPO
https://github.com/eyyyyyyy/gatsby.git

**Comment by yogeshkotadiya** [comment]
Need more info, Is it possible to share the repo or some code?

**Comment by eyyyyyyy** [comment]
> Need more info, Is it possible to share the repo or some code?

hello this is my repo https://github.com/eyyyyyyy/gatsby.git

**Comment by yogeshkotadiya** [comment]
OK, so the problem is you are not importing images correctly.
You can not use a relative path in `src` attribute in Gatsby you have to import Images first.
Check docs for more info [Adding Images, Fonts, and Files](https://www.gatsbyjs.org/docs/adding-images-fonts-files/)

**Comment by eyyyyyyy** [comment]
> OK, so the problem is you are not importing images correctly.
> You can not use a relative path in `src` attribute in Gatsby you have to import Images first.
> Check docs for more info [Adding Images, Fonts, and Files](https://www.gatsbyjs.org/docs/adding-images-fonts-files/)

still. images didn't show. even in background image. how can i set backgound images in css

**Comment by eyyyyyyy** [comment]
https://eyyyyyyy.github.io/purple-rain/public/blog-posts/ this is my new page some images didn;t show.

**Comment by yogeshkotadiya** [comment]
As I said before you have to import your images first in your javascript file for Webpack to bundle them in production.

```js
import React, { Component } from "react"
import Logo from "img/logo.svg" // See here you have to import your image first.

export default class Header extends Component {
  render() {
    return (
		<div className="header_wrap__logo">
			<a href="/">
				<img src={Logo} alt="Logo" /> // This is how you use them in img tag.
			</a>
		</div>
		)
	}	
}
```

If you want to use images in CSS you can directly specify the path in url.

```css
div{
	background-image: url('./img/logo.svg');
}
```

**Comment by eyyyyyyy** [comment]
> As I said before you have to import your images first in your javascript file for Webpack to bundle them in production.
> 
> ```js
> import React, { Component } from "react"
> import Logo from "img/logo.svg" // See here you have to import your image first.
> 
> export default class Header extends Component {
>   render() {
>     return (
> 		<div className="header_wrap__logo">
> 			<a href="/">
> 				<img src={Logo} alt="Logo" /> // This is how you use them in img tag.
> 			</a>
> 		</div>
> 		)
> 	}	
> }
> ```
> 
> If you want to use images in CSS you can directly specify the path in url.
> 
> ```css
> div{
> 	background-image: url('./img/logo.svg');
> }
> ```

i already did that. but bigger images didn't show. only small images

**Comment by jonniebigodes** [comment]
@eyyyyyyy see if my explanation in this [issue](https://github.com/gatsbyjs/gatsby/issues/11794#issuecomment-464938352) helps you out in any shape or form.

**Comment by oumaymaSghayer** [comment]
I had this issue when building a gatsby project: images stay blurred on first load and sharpens after interaction. I fixed it by setting loading="eager".

**Comment by roNn23** [comment]
> I had this issue when building a gatsby project: images stay blurred on first load and sharpens after interaction. I fixed it by setting loading="eager".

That was working for me, too. Thanks @oumaymaSghayer
