### ISSUE TITLE
[gatsby-link] Typescript definitions should extend @reach/router's type definitions

### ISSUE THREAD

**Issue by leomeloxp** [gatsbyjs/gatsby#11889]
## Description

When using Gatsby `Link` with Typescript I get an error when trying to use `getProps` prop:

> Type '({ isCurrent }: LinkGetProps) => void' is not assignable to type '(props: LinkGetProps) => {}'.
> Type 'void' is not assignable to type '{}'.

**EDIT**: Not an issue. It was my own mistake, function expects `{}` as a return type as I was returning `void`. Fixed it on my own code.

**Comment by wardpeet** [comment]
@leomeloxp I guess we can close this one? If not please add a few more details. We don't 100% have typescript typing coverage.

**Comment by leomeloxp** [comment]
Yes, you're more than welcome to close this. 

Although the type definition for that method is incorrect (should be `void`), that is something that has to be fixed at Reach router's end. Thanks for the prompt reply 😄
