### ISSUE TITLE
Writing on your Gatsby blog leads to JavaScript bloat

### ISSUE THREAD

**Issue by jab** [gatsbyjs/gatsby#11886]
https://matthewphillips.info/programming/gatsby-pages-manifest.html
Didn’t see this referenced in any existing issues so opening this in case it’s worth addressing here.

**Comment by wardpeet** [comment]
Thanks for creating this issue. We are aware of this problem and already have an issue for it https://github.com/gatsbyjs/gatsby/issues/4746. We have a WIP PR up which should be updated https://github.com/gatsbyjs/gatsby/pull/6651

I'll be closing this one in favour of https://github.com/gatsbyjs/gatsby/issues/4746.
