### ISSUE TITLE
Does gatsby support multiple 404 page?

### ISSUE THREAD

**Issue by zhouxiang19910319** [gatsbyjs/gatsby#11890]
Does Gatsby support multiple 404 pages?

I want my 404 page to behave like this: 

each time a user got a 404 page, it is one of the pages I set up. And each page has a random funny quote just to light up the mood. 

It's like a random quote machine that is built in 404 page.

**Comment by yogeshkotadiya** [comment]
You can't have multiple 404 pages, but you can create Component that renders random quote either from state or external API.

**Comment by zhouxiang19910319** [comment]
I see. So basically I just make a random quote machine on the 404 page? Just like all the examples online?

**Comment by jonniebigodes** [comment]
@zhouxiang19910319 to answer your questions yes you can apply it.
Under the `pages` folder you can create a file called `404.js`. And for instance you can have the following code:

```javascript
import React, { Component } from 'react'
import Axios from 'axios'

class NotFound extends Component {
    state = {
        randomQuote:'',
        isError:false
    }

    async componentDidMount() {
        try {
            const remoterequest= await Axios.get('http://your_api_for_quotes.com')
            const {data}=remoterequest
            this.setState({randomQuote:data.quote})
            
        } catch (error) {
            console.log('====================================');
            console.log(`error on 404:${error}`);
            console.log('====================================');
            this.setState({isError:true})
        }
    }
    
    render() {
        const { isError, randomQuote } = this.state
        if (isError){
            return (<div>upsy daisy</div>)
        }
        return(
          <div>
              <h1>{randomQuote}</h1>
          </div>
        )
    }
    
}
export default NotFound
```
And you should have a random quote machine all set up. More on 404 pages and Gatsby [here](https://www.gatsbyjs.org/docs/add-404-page/).

Feel free to close this if the answers provided helped solve your issue. Thanks for using Gatsby 👍

**Comment by zhouxiang19910319** [comment]
Thank you for the in depth explanation! Welp, you actually just gave me the code I needed. I will close this for now and study more about React as well as Gatsby!
