### ISSUE TITLE
Gatsby not GDPR compliant?

### ISSUE THREAD

**Issue by crstnio** [gatsbyjs/gatsby#11891]
I noticed that Gatsby's websites (gatsbyjs.org and gatsbyjs.com) save cookies without user consent – like `GA`.

There is no cookie banner to allow user consent and I see no privacy policy.

The component [react-cookie-consent](https://www.npmjs.com/package/react-cookie-consent) could help with that. But as I can see, it has no way for a user to revoke consent later except for deleting the consent cookie manually or wait till the expiration time.

I think Gatsby could need documentation and best practices about this topic. Maybe an official component or plugin that handles GDPR.

**Comment by LekoArts** [comment]
That depends on how you use GA. If you don’t collect personal data then you don’t need the consent
