### ISSUE TITLE
Provide site configuration to root HTML component in develop mode

### ISSUE THREAD

**Issue by scottnonnenberg** [gatsbyjs/gatsby#119]
First, many thanks for this great little tool. I love using React, what I'm used to for apps these days, for blog functionality!

I notice that the data passed into the `HTML` top-level react component in `develop` is very different from `build`. Please consider supplying the `config` object to `HTML` in `develop` mode.

`develop` mode render of `HTML`: https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/develop.js#L96
`build` mode render of `HTML`: https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/static-entry.jsx#L70

My specific scenario is around URLs like usage tracking and CDN. I'd like to have that in my central site configuration, and that does work well for the static build. But it doesn't work for my development scenarios.

**Comment by KyleAMathews** [comment]
Oh thanks! Yeah, this is definitely how things should work. All modes should be as similar as possible.

I fixed things a bit differently than your PR as I didn't think it made sense to return the `siteConfig` from `globPages` (not sure now why it was loaded there at all). See ca5ae21
