### ISSUE TITLE
Non-ASCII path problems in gatsby-source-filesystem

### ISSUE THREAD

**Issue by overthebytes** [gatsbyjs/gatsby#11903]
`gatsby-source-filesystem` depends on [slash](https://github.com/sindresorhus/slash) to normalize the path.

but, [slash](https://github.com/sindresorhus/slash) does not do anything if there are non-ascii characters in the path.

This causes problems with other plugins that refer to `node.absolutePath` such as ` gatsby-transformer-sharp` or `gatsby-remark-copy-linked-files`.

**Comment by wardpeet** [comment]
mind sharing a simple reproduction that we can have a look at.

We are always happy to receive Pull Requests.

**Comment by raae** [comment]
I have no opinion on whether this should be fixed or not, but I have created a sample repo to highlight the issue. 

* Repo: https://github.com/raae/gatsby-triage-non-ascii-filepaths
* Deployed version: https://non-ascii-filepaths.netlify.com/

Results:
* Non-ASCII characters in file name ok.
* Non-ASCII characters in folder name NOT ok.
