### ISSUE TITLE
Better configurability for Gatsby starters with the CLI

### ISSUE THREAD

**Issue by snics** [gatsbyjs/gatsby#11908]
## Summary
Actually, the start is just a git clone on the Starter Git repository. It would be nice if you could make certain settings or create a config file that creates the project.

### Basic example
I could imagine a setting like helm chart. So you can do with a YAML config file all settings with a CLI commando.

### Motivation
Such a function just makes bootstrapping faster and there could be complex starter kits (e.g. e-commerce frontends) to make setup easier. I would be willing to work with you because I love GatsbyJS

**Comment by wardpeet** [comment]
I'm unsure what you're talking about. Do you want to create a [Helm chart](https://docs.helm.sh/)? I don't think we want this atm. You can always create a wrapper or something completely new on your own GitHub.

This is just my own opinion so unsure what the community thinks of it :joy:
