### ISSUE TITLE
[Gatsby-link] navigate cannot add hash link nor query parameters to the URL

### ISSUE THREAD

**Issue by Minivera** [gatsbyjs/gatsby#11910]
Discussed in this PR: https://github.com/gatsbyjs/gatsby/pull/11625

## Description

When using gatsby's `navigate` helper or the `<Link>` component, the `withPrefix` function will always be called, adding a prefix to navigations to hash-link or query parameters. While this can be circumvented with an anchor tag, you may want to navigate programmatically and the only fix there is to use `@reach/router`'s `navigate` function directly or `window.___navigate`, which is unintuitive to developers starting out.

I think gatsby should support all use cases of the `navigate` function without having to load any other package and this would require some change in the `withPrefix` function to not add a slash if detecting a hash-link or a query param.

The contributor in the above PR which fixed the issue in a very ugly way suggested I instead add this limitation to the docs and open an issue to discuss this problem and possible solutions.

### Steps to reproduce

```jsx
import { navigate } from 'gatsby';

navigate('#some-id', { replace: true });
```

### Expected result

I should see the url change to `http://somewhere.com/path/to/location#some-id`

### Actual result

`withPrefix` adds a trailing slash which instead redirects to  `http://somewhere.com/#some-id`

**Comment by wardpeet** [comment]
Thanks for creating this issue! Feel free to create a PR for it! We would love that!

**Comment by Minivera** [comment]
I created one - though my fix what somewhat ugly - here: https://github.com/gatsbyjs/gatsby/pull/11625. I'd be happy to revisit the issue if it's decided that the feature is necessary.
