### ISSUE TITLE
How to customize Markdown transformation

### ISSUE THREAD

**Issue by baobabKoodaa** [gatsbyjs/gatsby#11913]
## Summary

How can I customize the way Markdown content is transformed into pages?

## Relevant information

I've been trying to do this on/off for [3 weeks now](https://stackoverflow.com/questions/54470505/gatsbyjs-customize-markdown-transformer). I would really appreciate it if someone could help me out. Basically, I'm trying to implement the tracedSVG placeholders from ["Using gatsby-image" demosite](https://using-gatsby-image.gatsbyjs.org/).

### Approach 1: standard plugins

The typical way of transforming Markdown content into pages is with `gatsby-transformer-remark` plugin. The plugin itself has a plugin called `gatsby-remark-images` for images, but it doesn't support tracedSVG placeholders. There is [a pull request](https://github.com/gatsbyjs/gatsby/pull/9490) which implements this feature, but it's been hanging there for 2 months without approval. I could of course fork Gatsby just to merge this feature for myself, but I don't really want to do that.

### Approach 2: alternative plugin

I found another plugin called `gatsby-remark-rehype-images`, which gives more control over my image transformations. It is supposed to let me "specify any arguments to pass on to plugin sharp", but it turns out [there isn't a way to pass the "tracedSVG" argument](https://github.com/oorestisime/gatsby-remark-rehype-images/issues/2).

### Approach 3: custom Components

I used rehype-react to [enable embedding custom React Components in Markdown](https://using-remark.gatsbyjs.org/custom-components/). Then I created a Component which displays the image like I want it to. You can see the Component [here](https://github.com/baobabKoodaa/blog/blob/master/src/components/Article/ReImage.js). I was so happy to finally see it working, but then I realized it's wasting horrible amounts of bandwidth. Because this is a Component file instead of a Page, I had to use a StaticQuery to get the images. I'm [unable to use variables in a StaticQuery](https://spectrum.chat/gatsby-js/general/using-variables-in-a-staticquery~abee4d1d-6bc4-4202-afb2-38326d91bd05) so I have to fetch _all_ images in the StaticQuery and then filter down to the one I want. This would be fine if the filtering was done at _build time only_. But I can see in console that a client can access a massive JS object which contains the metadata and base64 for all images. After I saw this I thought this page must not work without JS anymore. But boy oh boy, somehow it does! So now **I'm also confused regarding which JS is executed at build time and which is executed at runtime by the client**.

Surely there must be a way to render customized pages from Markdown with Gatsby, without sacrificing performance? I would prefer to solve this with a custom Component because I also want to do other customizations. Here's some random thoughts about how to solve this issue:

- Maybe I could use _only build time JS_ to filter the results of the StaticQuery? I was expecting this to be possible, because Gatsby is a static site generator, and I'm just trying to generate a static page from Markdown. It looks like this is not possible.
- I initiate creation of pages from Markdown in `gatsby-node.js`, where I pass the content of my Markdown file to the things which render it. Perhaps I could pass these contents all the way down to my custom Component? This would be in line with React's custom of passing variables down the tree as props. I was surprised this doesn't seem to be possible either.
- Should I try to create my own plugin for `gatsby-transformer-remark`?

Edit: Looks like the performance hit from my custom Component is not that bad after all. Yes it downloads metadata for all images, but it can reuse this data for subsequent page loads. Furthermore, Gatsby seems to optimize the initial page load pretty well. When I simulate a slow 3G network in devtools, I can see a fully functional, rendered page (with image placeholders) after only **20kb** of data. So the initial page load is really fast and subsequent page loads are fast. The only thing that takes a hit is the time to see actual images on the initial page load. Metadata and tracedSVG placeholders for 25 images appears to take  ~70kb gzipped.

**Comment by oorestisime** [comment]
FYI approach 2 should work with the upcoming release of gatsby-plugin-sharp (suspecting it will be 2.0.22 and should be available in the day)

**Comment by baobabKoodaa** [comment]
Confirmed
