### ISSUE TITLE
Force page refresh when three.js code changes

### ISSUE THREAD

**Issue by bravokiloecho** [gatsbyjs/gatsby#11928]
I'm building a site that uses three.js. I would like the page to refresh whenever I make changes to the JS that controls the three.js scene.

At the moment, when I make changes, Gatsby rebuilds everything fine, but the page doesn't refresh and so the new code that controls the three.js scene does not get used. If I manually refresh the page it takes effect.

Is there a way to force the page to refresh when the code gets changed?

The details of the implementation are included below...

This is the log that I guest in the web inspector when the three.js code changes:

```
[HMR] Checking for updates on the server...
process-update.js:114 [HMR] Updated modules:
process-update.js:116 [HMR]  - ./src/components/threeEntryPoint.js
process-update.js:116 [HMR]  - ./src/components/SceneComponent.jsx
process-update.js:116 [HMR]  - ./src/pages/index.js
process-update.js:116 [HMR]  - ./.cache/sync-requires.js
process-update.js:121 [HMR] App is up to date.
client.js?path=/__webpack_hmr&reload=true&overlay=false:234 [HMR] bundle rebuilding
client.js?path=/__webpack_hmr&reload=true&overlay=false:242 [HMR] bundle rebuilt in 276ms
```

To implement the canvas that three.js uses I'm using this component:

```
import React from "react";
import threeEntryPoint from './threeEntryPoint';

export default class SceneComponent extends React.Component {
  componentDidMount() {
    threeEntryPoint(this.threeRootElement, this.props.images);
  }
  render() {
    return (
      <div ref={element => this.threeRootElement = element} />
    );
  }
}
```

This imports a file called `threeEntryPoint.js` which looks like this:

```
import SceneManager from './SceneManager';

export default containerElement => {
  const canvas = createCanvas(document, containerElement);
  const sceneManager = new SceneManager(canvas);

  bindEventListeners();
  render();
  function createCanvas(document, containerElement) {
    const canvas = document.createElement('canvas');
    containerElement.appendChild(canvas);
    return canvas;
  }
  function bindEventListeners() {
    window.onresize = resizeCanvas;
    resizeCanvas();
  }
  function resizeCanvas() {
    canvas.style.width = '100%';
    canvas.style.height = '100%';
    canvas.width = canvas.offsetWidth;
    canvas.height = canvas.offsetHeight;
    sceneManager.onWindowResize();
  }
  function render(time) {
    requestAnimationFrame(render);
    sceneManager.update();
  }
}
```

And finally, the `SceneManger.js` file looks like this:

```
import * as THREE from 'three';
export default canvas => {
  const scene = buildScene(); 
  const renderer = buildRender(screenDimensions);
  const camera = buildCamera(screenDimensions); 
  const sceneSubjects = createSceneSubjects(scene);
  function buildScene() { ... }
  function buildRender({ width, height }) { ... }
  function buildCamera({ width, height }) { ... }
  function createSceneSubjects(scene) { ... }
  function update() { ... }
  function onWindowResize() { ... }
  return {
    update,
    onWindowResize
  }
}
```

### Environment (if relevant)

System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.4.1 - ~/.nvm/versions/node/v10.4.1/bin/node
    npm: 6.6.0 - ~/.nvm/versions/node/v10.4.1/bin/npm
  Languages:
    Python: 2.7.13 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 64.0.2
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.76 => 2.0.109
    gatsby-image: ^2.0.20 => 2.0.29
    gatsby-plugin-manifest: ^2.0.9 => 2.0.16
    gatsby-plugin-offline: ^2.0.16 => 2.0.22
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5
    gatsby-plugin-sass: ^2.0.9 => 2.0.9
    gatsby-plugin-sharp: ^2.0.14 => 2.0.19
    gatsby-source-filesystem: ^2.0.8 => 2.0.19
    gatsby-transformer-sharp: ^2.1.8 => 2.1.13
    gatsby-transformer-yaml: ^2.1.7 => 2.1.7
  npmGlobalPackages:
    gatsby-cli: 2.4.8

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`:
```
{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "babel-preset-stage-1": "^6.24.1",
    "current-device": "^0.8.0",
    "gatsby": "^2.0.76",
    "gatsby-image": "^2.0.20",
    "gatsby-plugin-manifest": "^2.0.9",
    "gatsby-plugin-offline": "^2.0.16",
    "gatsby-plugin-react-helmet": "^3.0.2",
    "gatsby-plugin-sass": "^2.0.9",
    "gatsby-plugin-sharp": "^2.0.14",
    "gatsby-source-filesystem": "^2.0.8",
    "gatsby-transformer-sharp": "^2.1.8",
    "gatsby-transformer-yaml": "^2.1.7",
    "gsap": "^2.0.2",
    "lodash": "^4.17.11",
    "mousetrap": "^1.6.2",
    "node-sass": "^4.11.0",
    "prop-types": "^15.6.2",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-helmet": "^5.2.0",
    "react-sizes": "^1.0.4",
    "react-transition-group": "^2.5.3",
    "three": "^0.101.1"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "start": "gatsby develop -H $HOSTNAME -p 8000",
    "format": "prettier --write \"src/**/*.js\"",
    "test": "echo \"Write tests! -> https://gatsby.app/unit-testing\"",
    "os": "open https://dev--trusting-yonath-bbb52f.netlify.com",
    "ol": "open https://collages.elwyn.co"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "eslint": "^5.12.1",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-babel": "^5.3.0",
    "prettier": "^1.15.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
```
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wardpeet** [comment]
We don't expose any watch tasks of webpack.

This is just a guess, I'm not 100% sure it will work but worth giving it a go. HMR of webpack exposes an api in your files:
https://webpack.js.org/guides/hot-module-replacement/#enabling-hmr

you can probably do something like the following in your main file:
```
if (module.hot) {
   module.hot.accept('./pathtothreejsimplementation.js', function() {
     window.location.reload();
   })
 }
```

**Comment by bravokiloecho** [comment]
Thanks for the suggestion @wardpeet!

I put this code in the `pages/index.js` (home page) of the gatsby site where the three.js scene is happening. At first I got the path wrong and it complained. So it's doing something! But when I fixed the path there were no errors but the page doesn't refresh.

Is there anything else I can try? Or some way of debugging this?

**Comment by wardpeet** [comment]
mind creating a super small reproduction so I can fiddle with it?

**Comment by bravokiloecho** [comment]
Hello! Sorry for the long delay.

I've put together a repo here: https://github.com/bravokiloecho/gatsby-three-js

The files where it would be good to have forced page refreshing are `./src/scene/SceneBasic.js` as well as `./components/SceneComponent.jsx`

I really appreciate your help with this, thank you!

**Comment by bravokiloecho** [comment]
I'm still waiting for a reply, hope that's ok

**Comment by DSchau** [comment]
@bravokiloecho of course that's OK! I'll remove the label and see if we can figure this out!

**Comment by DSchau** [comment]
What's happening here is that you're relying on componentDidMount to create the scene renderer. Because hot reloading (rightfully!) doesn't cause that method to be re-invoked, you're not invoking the `createSphere` method again with the changes.

You can test this with logging in componentDidMount, e.g.

```js
import React, { Component } from 'react';
import LoadingOverlay from './LoadingOverlay';
import { CreateSphere } from "../scene/SceneBasic";


let activeEnv = process.env.ACTIVE_ENV || process.env.NODE_ENV || "development";

export default class SceneComponent extends Component {
  constructor(props) {
    super(props);
    this.scrollTop = 0;
    this.state = {
      loaded: false
    };
    // this.clock = new THREE.Clock()
  }

  componentDidMount = () => {
    console.log('I will mount and initialize')
    this.loadThree()
      .then(() => {
        this.setupRenderer();
        this.setupScene();
        this.setupCamera();
        this.setupLights();
        this.buildScene()
          .then(() => {
            this.animate();
            this.setState({
              loaded: true
            });
          });
      });
  }

  loadThree = () => {
    const loadjs = require('loadjs');
    const threePath = '/three.101.min.js';
    return new Promise(function(resolve, reject) {
      loadjs([threePath], 'three');
      loadjs.ready('three', {
        success: resolve,
        error: reject
      });
    });
  }

  setupCamera = () => {
    let { innerWidth: width, innerHeight: height } = window;
    this.camera = new THREE.PerspectiveCamera(45, width / height, 10, 1000);
    this.camera.position.set(0, 0, 20);
  }

  setupRenderer = () => {
    let { innerWidth: width, innerHeight: height } = window;
    
    this.renderer = new THREE.WebGLRenderer({
      canvas: this.canvas,
      antialias: true,
      preserveDrawingBuffer: false
    });

    const pixelRatio = Math.max(2, window.devicePixelRatio);
    this.renderer.setPixelRatio(pixelRatio);
    this.renderer.setSize(width, height);
    // Setup resize events
    window.addEventListener('resize', () => this._resize());
    window.addEventListener('orientationchange', () => this._resize());
  }

  setupScene = () => {
    this.scene = new THREE.Scene();
    this.scene.background = new THREE.Color(0xffffff);
  }

  buildScene = () => {
    return new Promise((resolve) => {
      const sphere = CreateSphere();
      this.scene.add( sphere );
      resolve();
    });
  }

  setupLights = () => {
    
  }

  animate = () => {
    // Start loop again
    requestAnimationFrame(this.animate);
    this.renderer.render(this.scene, this.camera);
  }

  render() {
    return (
      <div className="three-container" ref={element => this.containerElement = element}>
        <LoadingOverlay loaded={this.state.loaded} />
        <div className="three-scroller" ref={element => this.scrollElement = element} />
        <canvas id="three-canvas" ref={element => this.canvas = element} />
      </div>
    )
  }

  _resize() {
    let { innerWidth: width, innerHeight: height } = window;
    this.renderer.setSize(width, height);
    this.camera.updateProjectionMatrix();
  }
}

```

This will only log on the _first_ mount, and because you're sorta short-circuiting the React rendering process here there's no way for React to know that he needs to re-invoke that method and re-render.

The typical way to do this is to make the component stateful or otherwise re-invoke the rendering process. What you could use here is `componentDidUpdate` here to update something within the graph, rather than relying on `componentDidMount` and effectively setting and forgetting that updates could occur.

So, what you would want to do here:

- Expose a way to re-draw the ThreeJS scene with an update (e.g. .redraw())
- Tie into [componentDidUpdate](https://reactjs.org/docs/react-component.html#componentdidupdate) and invoke this method with the possibly changed scene

Hope this helps! This is a little bit outside of a Gatsby issue (more a React and re-rendering/hot-reloading issue) so I'm going to close this out--but please do let us know if we can help any further!

**Comment by bravokiloecho** [comment]
Thanks @DSchau! I really appreciate your help and advice here.

I think I understand your suggestion but I wonder if there's another approach possible. Sometimes I'll want the THREE.js scene to update on every `requestAnimationFrame` so I'd rather not add the computational load of having to update the React component in addition. Especially when this is only for the sake of getting hot-reloading to work while developing.

I feel like a more ideal solution here would be to follow the path suggested by @wardpeet above where I hook into Gatsby's webpack implementation and force a `window.location.reload()` on changes to a given file.

It would be super helpful to get some advice on if/how this would be possible. I feel there would be other use cases for this beyond the scenario I'm describing here. Thanks again!
