### ISSUE TITLE
Graphql caching mechanism preventing double fetching?

### ISSUE THREAD

**Issue by axhamre** [gatsbyjs/gatsby#11924]
Is there any caching mechanism in Gatsby that prevents the same object queried in different parts of the application to be fetched multiple times? Something similar to how apollo-client works.

If so, what's the prerequisites for this to work? E.g. always include ID etc.

**Comment by KyleAMathews** [comment]
Hey, sorry we missed your question.

To answer it, there isn't right now but it's something we'd like to add. React Static does something along these lines where it identifies common data between queries and moves those into "shared" data chunks and only loads those once. We should be able to do something like this fairly cheaply with GraphQL. /cc @freiksenet @stefanprobst

**Comment by freiksenet** [comment]
Fetching node in Gatsby is already made through a cache, there isn't really a need to do additional cache on top of that on GraphQL level. Do you have any use case where this is important @axhamre?

**Comment by freiksenet** [comment]
Ah right, this is about using common chunks on client side. Disregard my comment above.
