### ISSUE TITLE
[docs] add page in contributing section on building reproducible builds

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#11933]
## Summary

A notice when filing a bug report here is to create a demo project to show off the bug. I think it would be useful to either enhance the "How to file an issue" page or create a new page describing how to create a reproducible build and the benefits of it.

### Motivation

It would be good to have a page describing further how to make a demo project for such.

**Comment by lannonbr** [comment]
Would someone on the @gatsbyjs/docs team be interested in a pair session to tackle this with me?

**Comment by marcysutton** [comment]
Hey @lannonbr, I like that idea. There is some new stuff in the [Code Contributions](https://www.gatsbyjs.org/contributing/code-contributions/) page on setting up Wordpress with Docker that I figured would get expanded for other setups...so my question is, would this content be a good fit there (with a link from "how to file an issue"), or on a separate page?

**Comment by krismorf** [comment]
FWIW people can launch a demo project in codesandbox but this is not documented on the docs.

**Comment by marcysutton** [comment]
> FWIW people can launch a demo project in [codesandbox ](https://codesandbox.io/s/)but this is not documented on the docs.

That would be a great addition too!

**Comment by lannonbr** [comment]
> Hey @lannonbr, I like that idea. There is some new stuff in the [Code Contributions](https://www.gatsbyjs.org/contributing/code-contributions/) page on setting up Wordpress with Docker that I figured would get expanded for other setups...so my question is, would this content be a good fit there (with a link from "how to file an issue"), or on a separate page?

So what I was thinking was more the idea to focus on more of what is a reproducible build is and how it is helpful for developers to debug down to figure out a possible solution so there is as little surface area to debug, but yeah I think this would be a good page to link from the "how to file an issue" and have a page describing reproducible builds

**Comment by marcysutton** [comment]
That sounds good to me @lannonbr. I'd say if you're up for writing it, go for it! And thanks for the suggestion!
