### ISSUE TITLE
Error references obsolete domain gatsby.app

### ISSUE THREAD

**Issue by docwhat** [gatsbyjs/gatsby#11944]
[This code](https://github.com/gatsbyjs/gatsby/blob/f32c0167605baf156108bdd600b9f0cd19bab6ce/packages/gatsby/src/utils/api-runner-node.js#L121-L122) emits an error pointing to the domain gatsby.app which seems to no longer exist:

```
warning Action createPage was called outside of its expected asynchronous lifecycle createPages in default-site-plugin.
Ensure that you return a Promise from createPages and are awaiting any asynchronous method invocations (like graphql or http requests).
For more info and debugging tips: see https://gatsby.app/sync-actions
```

**Comment by DSchau** [comment]
@docwhat whoops - thanks so much for letting us know.

I've added the shortlink.

https://gatsby.app/sync-actions
