### ISSUE TITLE
Plugin Library: Can't click on google analytics plugin

### ISSUE THREAD

**Issue by giraffesyo** [gatsbyjs/gatsby#11949]
When I go to the gatsbyjs.org site and click on the Google Analytics plugin from the plugin library it directs me to: https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/?= which is an "ERR_FAILED" page

**Comment by wardpeet** [comment]
I'm not able to reproduce this one, even if I go to this page directly it works. Could you try running it in incognito so no interference of extensions can happen

**Comment by giraffesyo** [comment]
You're right, it works in incognito. I disabled and re-enabled uBlock origin and it seems like it fixed it in regular browsing. I guess it's a problem with their filters? It's crazy.
