### ISSUE TITLE
[Docs] confusing gatsby-config.js

### ISSUE THREAD

**Issue by CHEWX** [gatsbyjs/gatsby#11957]
Hi, 

New to Gatsby and I've noticed that there is no clear link back to `gatsby-config.js`.

For example if you were to setup a new site and then complete the quick tutorial. You'd then like to finish off with adding Google Analytics.

You search gatsby analytics and get taken to this page — https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/adding-analytics.md

It's not obvious what `gatsby-config.js` is? Should there be a link back to the docs on this?

Also, the example of Google Analytics. Most people would just copy and paste that into their `gatsby-config.js` file, however, shouldn't it display like this:

```
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-google-analytics',
      options: {
        // replace "UA-XXXXXXXXX-X" with your own Tracking ID
        trackingId: "UA-XXXXXXXXX-X",
      },
    },
  ],
};
```
This gives a little context.

Might be overly simplifying, just initial feedback.

**Comment by wardpeet** [comment]
Not sure how we do it for other README.md but that's a great idea!

I would recommend something like
```
module.exports = {
  // ...gatsby config
  plugins: [
    // ...other gatsby plugins
    {
      resolve: 'gatsby-plugin-google-analytics',
      options: {
        // replace "UA-XXXXXXXXX-X" with your own Tracking ID
        trackingId: "UA-XXXXXXXXX-X",
      },
    },
  ],
};
```

@CHEWX mind opening a PR for this? That would help us a lot!

@gatsbyjs/docs do any of you have a better solution?

**Comment by marcysutton** [comment]
Ah yes, I could see how that would be confusing. To clarify your steps, did you search on Google for "adding analytics" and land on the Github page? The page on the Gatsby docs shows the file title (`gatsby-config.js`), but the Github version does not: https://www.gatsbyjs.org/docs/adding-analytics/#using-gatsby-plugin-google-analytics

I agree that showing a more complete `gatsby-config.js` structure like what you have here would help in both cases. You could also add a link to this page: https://www.gatsbyjs.org/docs/gatsby-config/#gatsby-config
