### ISSUE TITLE
GATSBY_DB_NODES=loki gatsby build

### ISSUE THREAD

**Issue by krismorf** [gatsbyjs/gatsby#11958]
I used to run my project using `GATSBY_DB_NODES=loki gatsby build`

This stopped working since Gatsby 2.0.10.  Was this functionality removed recently? 

```bash
'GATSBY_DB_NODES' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by pieh** [comment]
`GATSBY_DB_NODES=loki` is setting environment variable. I think you are running this on Windows and it requires a little different syntax - check https://stackoverflow.com/questions/1420719/powershell-setting-an-environment-variable-for-a-single-command-only

**Comment by pieh** [comment]
And we didn't remove it for sure.

**Comment by krismorf** [comment]
Thanks, It's because I switched to Windows yesterday.
