### ISSUE TITLE
Proper way to import a gif or a video in gatsby after the building process?

### ISSUE THREAD

**Issue by leworking** [gatsbyjs/gatsby#11950]
I have a .mp4 file that I want to use in a Gatsby component. Being outside `gatsby-image`, this is just a matter of importing it

    import video from '../images/myvideo.mp4'

Now what I want to do is to randomly import one video from a pool of let's say 50 videos. I could import all 50 videos and then select one of them and add it in a `src` property.

**But importing 50 videos is likely not the recommended way**

How to do it? Once I have the final url (from the pool, I select one of the 50 urls), how can I insert in my component? This doesn't work

    <img  src={require(`${mySelectedUrl}`)} />

Is the only way to add the videos in a static folder so that I can simply type the address?

**Comment by leworking** [comment]
I have been able to do it like this (from [here](https://github.com/gatsbyjs/gatsby/issues/3663))

      let media = 'my_video.mp4' // name selected from the pool of names
      letreq = require.context('../videos', false, /.*\.mp4$/)
      let [video] = req.keys().filter(key => key === media)
      elem.src = req(video) // elem is a document.getElementById('myId')

I would close it, but in case there's something wrong with this solution I keep it open.
*Also, since require is not ES6, is there any alternative for ES6?

**Comment by wardpeet** [comment]
@leworking it's not entirely gatsby issue.

The solution is the non gatsby solution and works in every web app where you use [WebPack](https://webpack.js.org/)

```
  let media = 'my_video.mp4' // name selected from the pool of names
  let req = require.context('../videos', false, /.*\.mp4$/)
  let [video] = req.keys().filter(key => key === media)
  elem.src = req(video) // elem is a document.getElementById('myId')
```

If we look at gatsby we would probably want to move to GraphQL and the [gatsby-source-filesystem](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/).
Here is an [article that covers it for PDFs](https://www.gatsbyjs.org/docs/adding-images-fonts-files/#query-for-file-in-graphql-queries-using-gatsby-source-filesystem)

```
{
  allFile(filter: { extension: { eq: "mp4" } }) {
    edges {
      node {
        publicURL
      }
    }
  }
}
```

I hope I've put you in the right direction. Thanks for using Gatsby 💪 .

**Comment by leworking** [comment]
Yes, somehow since I couldn't use `gatsby-image` (like in the `.gif` cases) I assumed I could not use `graphql` for this, but you are completely right, I can gather the directory content through `graphql` (as I am doing with `.jpg` images)

Thanks
