### ISSUE TITLE
HELP with createPage - hosting - content creation

### ISSUE THREAD

**Issue by aikodeio** [gatsbyjs/gatsby#11967]
Hello nice to meet you! My name is Roberto. I do not speak English very well, but I will try to express my question as best I can.

GatsbyJs is great, I have implemented it in several places and everything works perfectly. But now I have a bigger challenge and I want to know if it is possible to do it with Gatsby.

(My site will be implemented in Firebase Hosting).

Requirements:

1) That registered users, through a form, create different types of publications, for example:
- User 1: publish a car to sell through the site.
The url should be: www.misitio.cl/autos/auto-usuario-1
- User 2: publishes a house to sell through the site.
The url should be: www.misitio.cl/casas/casa-2

I know that the createPage API exists. Is it possible to run it on any hosting?

I need that each time a publication is created, a html page of each one is created and it is immediately visible.

Thanks in advance for any help or you can guide me :smiley:

![gatsbyjstest](https://user-images.githubusercontent.com/47112604/53187036-fa4ff000-35e0-11e9-91c7-d0d15e2f4475.jpg)

**Comment by 17cupsofcoffee** [comment]
If you wanted to use the createPage API, you'd need to regenerate/redeploy the site every time someone creates a new item. One way of doing this would be to fire a webhook whenever data gets submitted (potentially via [Firebase triggers](https://firebase.google.com/docs/functions/database-events)?) to kick off a CI build and deployment.

That said, regenerating the site takes a little bit of time, so the listings will not appear immediately - this may or may not be an issue for you! If it is, you might want to investigate using ['client-only routes'](https://www.gatsbyjs.org/docs/building-apps-with-gatsby/#client-only-routes--user-authentication) and pulling the data down from Firebase dynamically on the client side.

**Comment by aikodeio** [comment]
@17cupsofcoffee  Thank you for the time in responding and guiding me in a solution. I will investigate what you told me.

**Comment by aikodeio** [comment]
@17cupsofcoffee A question:
If there are 100 users creating a publication at the same time,
Will the site be built 100 times and implemented 100 times?
Does it affect traffic?

I am a little confused.

**Comment by 17cupsofcoffee** [comment]
It depends on how you have things set up. Most CI systems I've used have an 'auto-cancellation' option (e.g. on [Travis CI](https://docs.travis-ci.com/user/customizing-the-build/#Building-only-the-latest-commit) or [Circle CI](https://circleci.com/docs/2.0/skip-build/#auto-cancelling-a-redundant-build)), which will cancel any queued builds if another build is started. In that case, 100 builds would get queued, but only the last one would get run.

That said, if you anticipate your website regularly having 100 people push content simultaniously, I don't know if the 'rebuild on every content change' approach would be the best fit for your site.

**Comment by aikodeio** [comment]
@17cupsofcoffee 

I understand, maybe I should rebuild the site once a day with the new publications, be it 50 or 100.

It just bothers me a bit that users can not share their publication immediately with other users.

I will apply the routes on the client side and Firebase Cloud Functions.

Thank you!
