### ISSUE TITLE
Bad content loaded from markdown when files have similar names (substings)

### ISSUE THREAD

**Issue by nschainapp** [gatsbyjs/gatsby#11963]
Bad content loaded when markdown files have similar names
  Useful Links:
  - [Repo
](https://github.com/nschainapp/testlink
) 
- [Example url 
](https://epic-swirles-74611d.netlify.com/)

## Description

Click on links load content from file with longer name on server
On MacOS or Windows Parialy work, on some builds links work as expected, in some cases links load content of longer named file.

### Steps to reproduce

Just clisk on link pairs and You will see difference between your local build and live site

### Expected result

Show 4 different markdown file contents.

### Actual result

Showing just content from files that have longer name.

### Environment

Run `npm start dev` or `gatsby build gatsby serve` same results

**Comment by nschainapp** [comment]
This looks like some greedy regex on file name but I don't know where to look for it :(

**Comment by wardpeet** [comment]
Thanks for submitting this bug! I haven't found the time to dig deep into this bug. It probably has something to do with our match part inside @reach/router.

**Comment by igor-velickovic** [comment]
+1 on this issue. Any news?

**Comment by ashley** [comment]
Hey, can I work on this? 😄

**Comment by wardpeet** [comment]
@ashley yes! please 😄
