### ISSUE TITLE
How are plugins supposed to use the cache?

### ISSUE THREAD

**Issue by riddla** [gatsbyjs/gatsby#11977]
I'm trying to get my head around why the directories in `.cache/caches/` are cleared every time I (re-)start the development server.

I am successfully caching something with `cache.set` within a source plugin, but I can't retrieve it because the directories are whipped out. 

Has this something to do with the `touching` of nodes? Can a plugin only cache nodes? Or do I need to use the `getCache` method that was lately introduced?

(I double checked that my plugins hash has not changed at this point, so the [general cache directory deletion](https://github.com/gatsbyjs/gatsby/blob/c2fa762de1cdaf2d24cf0903963983f304577b9a/packages/gatsby/src/bootstrap/index.js#L180) is not invoked.)

**Comment by DSchau** [comment]
@riddla anything you could reproduce or share?

**Comment by riddla** [comment]
@DSchau, I will try to isolate the (possible) issue tonight. It’s currently happening in a private repo and within something I wanted to try in the wordpress source plugin.

**Comment by riddla** [comment]
@DSchau, you can use https://github.com/riddla/julia-wickelt.de, I added a basic reproduction with the commit https://github.com/riddla/julia-wickelt.de/commit/526df705cf61bd28bb92e554894a8318391203db.

Just invoke `npm run develop` twice.
