### ISSUE TITLE
How does Gatsby count number of plugin downloads

### ISSUE THREAD

**Issue by Simply007** [gatsbyjs/gatsby#11989]
## Summary

I am wondering, how does Gatsby counts the number of download of the plugins (ketico source plugin in my case).

On the npm I can see around 3k downloads, but in the docs, there is just 661.

![image](https://user-images.githubusercontent.com/9218736/53232257-02fd0080-368b-11e9-9dc3-b16419e33112.png)

Does the number describe total downloads or number of downloads in some time period?

## Relevant information

I looked to npm stats (https://npm-stat.com/charts.html?package=gatsby-source-kentico-cloud) and 661 downloads were performed between October and November 2018

**Comment by wardpeet** [comment]
We use https://github.com/algolia/npm-search but it seems to be out of date all the time...

https://github.com/gatsbyjs/gatsby/issues/11129

I'm pretty sure we should create our own or work together with the algolia team to get this fixed.

**Comment by Simply007** [comment]
Great thanks!

**Comment by wardpeet** [comment]
@Simply007 If I answered your question correctly, mind closing as we already have the #11129 open for it.

**Comment by Simply007** [comment]
Sure @wardpeet!

**Comment by KyleAMathews** [comment]
The number there is the count for the last month of  downloads. So not the total.

**Comment by Simply007** [comment]
Thanks for clarification @KyleAMathews.
