### ISSUE TITLE
[1.0] Question: have you looked at alternatives to gatsby-dev-cli?

### ISSUE THREAD

**Issue by rstacruz** [gatsbyjs/gatsby#1198]
Hey, totally off-topic, but...

I'd love to use lerna to manage monorepos. `gatsby-dev-cli` is great, but only works for Gatsby. As I understand it, its reason for living is to be a glorified [npm-link](http://devdocs.io/npm/cli/link) that works for multiple packages.

Have you tried looking for a more general-purpose tool?

**Comment by KyleAMathews** [comment]
This is (I'm pretty sure) my dream setup https://github.com/yarnpkg/yarn/issues/3294

Also might replace Lerna in time.

I would have loved to use a more general purpose tool but nothing else existed and gatsby-dev-cli was the easiest kludge I could think of until workspaces is ready. `npm link` flat out doesn't work for Gatsby (several reasons...) so we really needed something like gatsby-dev-cli and making it specific for Gatsby was the cheapest way to do it.

**Comment by rstacruz** [comment]
Thanks for the reply!

Why is `npm link` not working for gatsby? I imagine it would be simple:

```sh
# export your working copies of the packages
cd ~/gatsby-1.0
for f in packages/*; do (cd $f && npm link); done

# link it in new project
cd ~/my-project
npm link gatsby gatsby-link gatsby-plugin-google-analytics gatsby-plugin-manifest ...
# or
(for f in node_modules/gatsby*; do echo $(basename $f); done) | xargs npm link
```

May have to disable hoisting in lerna though.

**Comment by KyleAMathews** [comment]
The main thing that tripped me up is `npm link` means dependencies don't get deduped necessarily which can be fine but in our case graphql really dislikes because it expects global singletons and compares objects against each other so if both code paths A & B load separate GraphQL, GraphQL will then throw errors when doing internal validation.

**Comment by rstacruz** [comment]
ouch, i see.
