### ISSUE TITLE
Allow loaders.postcss() to accept Autoprefixer options

### ISSUE THREAD

**Issue by khades** [gatsbyjs/gatsby#11984]
I have seen may issues that autoprefixer is not processing stylesheets as intended, when people add it as postcss plugins in gatsby-source-sass. The issue is that loader.postcss() has set in options (except browsers, which is picked from package.json), so webpack uses that configuration. 

Example: no matter if you add autoprefixer with grid settings as postcss plugin, autoprefixer doesn't prefix\autoplace grids.

I want loaders.postcss() to accept autoprefixer configuration.

**Comment by wardpeet** [comment]
Is it possible to actually post some configurations you already have? 

We support changing configurations as you can do in any app that uses postcss.
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-postcss#postcss-plugins

**Comment by khades** [comment]
``` 
   {
      resolve: 'gatsby-plugin-sass',
      options: {
        postCssPlugins: [
          autoprefixer({
            grid: true,
            browsers: ['last 2 version'],
          }),
        ],
      },
    },
```

I got to autoprefixer package and checked its options, it runs with that options only on configuration definition, while building app it uses predefined settings in loaders.postcss()

**Comment by wardpeet** [comment]
oh you're right we should merge those 2, unsure if we can but it's definitly a good idea!

For now you could go for `/* autoprefixer grid: no-autoplace */` in your code. Could you perhaps create a small repro for this? Or do you have your code public somewhere?

**Comment by khades** [comment]
the problem is that without grid: true there's no -ms prefixes, so if you placed element by hand, no placement styles are generated.

**Comment by khades** [comment]
i think its not hard to do.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack-utils.js

original code
```
 postcss: (options = {}) => {
      let { plugins, browsers = supportedBrowsers, ...postcssOpts } = options

      return {
        loader: require.resolve(`postcss-loader`),
        options: {
          ident: `postcss-${++ident}`,
          sourceMap: !PRODUCTION,
          plugins: loader => {
            plugins =
              (typeof plugins === `function` ? plugins(loader) : plugins) || []

            return [
              flexbugs,
              autoprefixer({ browsers, flexbox: `no-2009` }),
              ...plugins,
            ]
          },
          ...postcssOpts,
        },
      }
    },
```

My proposal
```
 postcss: (options = {}) => {
      let { plugins, autoprefixerOptions, browsers = supportedBrowsers, ...postcssOpts } = options
      const autoprefixerOpts =Object.assign({}, autoprefixerOptions, { browsers, flexbox: `no-2009` })
      return {
        loader: require.resolve(`postcss-loader`),
        options: {
          ident: `postcss-${++ident}`,
          sourceMap: !PRODUCTION,
          plugins: loader => {
            plugins =
              (typeof plugins === `function` ? plugins(loader) : plugins) || []

            return [
              flexbugs,
              autoprefixer(autoprefixerOpts),
              ...plugins,
            ]
          },
          ...postcssOpts,
        },
      }
    },
```

Sorry, i can't do proper pull request right now.
