### ISSUE TITLE
Using Webcomponents (e.g. lit-element) instead of react

### ISSUE THREAD

**Issue by raptoni** [gatsbyjs/gatsby#11987]
Would it be possible to use gatsby with webcomponents (lit-element) instead of react ?

**Comment by wardpeet** [comment]
you won't be able to entirely remove React as we use parts of it to do routing and other optimisations.

You can use gatsby and webcomponents together. React supports it so we do too 😄 
https://reactjs.org/docs/web-components.html

There are probably better articles on the web

**Comment by raptoni** [comment]
I did not expect to just remove react and substitute it with lit-element. The question was if that is something worth considering as a future feature. I am fairly new to this but as far as I understand using a native standard would be a great fit for gatsby even if react is a the "standard" nowadays. I am sure routing is something you could do without react-router.

**Comment by neilhem** [comment]
You can use React as Container components and for routing combined with your ui components based in web components

**Comment by ZaradarDFDS** [comment]
You can use lit-element and React together as long as you have support for CustomElements. Essentially you just use the CustomElement in your react application/plugin and lit-element will take care of the rest. there are some issues with synthetic events you need to be aware of and if you want to keep react in sync with lit-elements you will probably need to look at the React Hooks API
