### ISSUE TITLE
Improve reliability of gatsby-plugin-sharp by moving Sharp image transformations into child process

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#11996]
An idea occurred to me yesterday about how we could improve the reliability of Sharp — as many people have their builds fail due to it segfaulting. One solution would be just to move it out of the main process so that when it fails, we can recover. We’re already using jest-worker for doing HTML builds and it’d be perfect for this as it automatically respawns child processes that crash https://www.npmjs.com/package/jest-worker

**Comment by KyleAMathews** [comment]
We could also use this to detect which files are causing trouble (assuming it is a particular file and not something randomly glitchy inside sharp). We could detect which job Sharp was working on when it crashed and if the same job crashes multiple times in a row (2? 3?) then exit Gatsby altogether and point to the file that's causing trouble for the user to fix.

**Comment by m-allanson** [comment]
cc @jamo are you able to find out what percentage of build failures are related to sharp?

**Comment by jamo** [comment]
Sorry for the delay -- based on a quick analysis it seems that extremely small amount (less than 0.1% of errors reported in the build phase has to do with sharp.
