### ISSUE TITLE
Webpack externals break gatsby build

### ISSUE THREAD

**Issue by rapzo** [gatsbyjs/gatsby#11990]
## Description

When defining externals in a custom webpack config, and having a custom html.js with a script tag importing the external file's path, `gatsby build` fails.

### Steps to reproduce

In `gatsby-node.js`:
```
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    externals: ['xxx']
  })
}
```

And `src/html.js`:
```
import React from "react"
import PropTypes from "prop-types"

export default class HTML extends React.Component {
  render() {
    return (
      <html {...this.props.htmlAttributes}>
        <head>
          <meta charSet="utf-8" />
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          <script src="/xxx.js" />
          {this.props.headComponents}
        </head>
        <body {...this.props.bodyAttributes}>
          {this.props.preBodyComponents}
          <div
            key="body"
            id="___gatsby"
            // eslint-disable-next-line
            dangerouslySetInnerHTML={{ __html: this.props.body }}
          />
          {this.props.postBodyComponents}
        </body>
      </html>
    )
  }
}

HTML.propTypes = {
  htmlAttributes: PropTypes.object,
  // eslint-disable-next-line
  headComponents: PropTypes.array,
  bodyAttributes: PropTypes.object,
  // eslint-disable-next-line
  preBodyComponents: PropTypes.array,
  body: PropTypes.string,
  // eslint-disable-next-line
  postBodyComponents: PropTypes.array,
}

HTML.defaultProps = {
  htmlAttributes: null,
  headComponents: null,
  bodyAttributes: null,
  preBodyComponents: null,
  body: null,
  postBodyComponents: null,
}
```

And anywhere in the site's code:
```
import XXX from 'xxx';
```

### Expected result

The build should complete and the module `xxx` shouldn't be in the bundle

### Actual result

Build unsuccessful.

### Environment

```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    npm: 6.8.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 65.0
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.76 => 2.1.14
    gatsby-image: ^2.0.20 => 2.0.29
    gatsby-plugin-google-analytics: ^2.0.13 => 2.0.14
    gatsby-plugin-manifest: ^2.0.9 => 2.0.18
    gatsby-plugin-offline: ^2.0.16 => 2.0.24
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.6
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0
    gatsby-plugin-sharp: ^2.0.14 => 2.0.21
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.6
    gatsby-remark-images: ^3.0.1 => 3.0.4
    gatsby-source-contentful: ^2.0.28 => 2.0.30
    gatsby-source-filesystem: ^2.0.8 => 2.0.21
    gatsby-transformer-json: ^2.1.7 => 2.1.8
    gatsby-transformer-remark: ^2.1.19 => 2.2.5
    gatsby-transformer-sharp: ^2.1.8 => 2.1.14
```

**Comment by rapzo** [comment]
If the victim module is not available in node_modules then i get: `WebpackError: Cannot find module 'xxx'` despite the form of externals object (array or object).

**Comment by rapzo** [comment]
Probably related with #11761 ?

**Comment by airtonix** [comment]
Also experienced this yesterday. will update with details this evening.

**Comment by danrha** [comment]
I'm getting the same issue in a similar case.

**Comment by ryancat** [comment]
I also run into this issue today. 
Dig a little bit and found the starter I use (gatsby-gitbook-starter) is using a function for externals. I tried to add my config to the externals array like https://webpack.js.org/configuration/externals/#combining-syntaxes, but I still get my module not found issue. Not sure how to debug further...


 System:
    OS: macOS 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.70
    Safari: 13.0.2
  npmGlobalPackages:
    gatsby: 2.16.3

**Comment by ryancat** [comment]
More details on how this works in gatsby: https://github.com/gatsbyjs/gatsby/pull/14208/files

I don't understand why the mixed externals array is not working :(. Any idea?
