### ISSUE TITLE
Generating a sitemap

### ISSUE THREAD

**Issue by johnbrett** [gatsbyjs/gatsby#12]
Any advice on where to start on generating sitemap either during gatsby serve or build ?

Thinking of using gatsby for my blog: https://johnbrett.me/

**Comment by KyleAMathews** [comment]
If you add a `post-build` file in the root of your site, you can do custom stuff like generate a sitemap and rss/atom feed.

https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/build.coffee#L30

See my personal blog where I generate an Atom feed https://github.com/KyleAMathews/blog/blob/master/post-build.coffee

You're in node.js context here so you can write files to disk etc.

**Comment by johnbrett** [comment]
Worked perfectly. Cheers for the responsiveness.

**Comment by ivanoats** [comment]
JSYK I have a gist here with how to make a sitemap: https://gist.github.com/ivanoats/8d01d9e934fdc17bae9090147f1e799b

**Comment by ivanoats** [comment]
Nice. FWIW I wasn't using babel, just node 6 😎

**Comment by chiedo** [comment]
Ahhh, that's makes sense @ivanoats  :)
