### ISSUE TITLE
After updating node gatsby plugins started to throw errors

### ISSUE THREAD

**Issue by ergunpp** [gatsbyjs/gatsby#12000]
I have updated node version to make a plugin work using nvm, gatsby stopped working.
Re-installed gatsby. Run gatsby build for my existing project, started throwing errors for every plugin listed in the gatsby-config.js, reinstalled them all. Run npm audit fix. reinstalled packages.
Now when I run the gatsby build command, it throws the error:

> success open and validate gatsby-configs — 0.007 s
> warning Plugin gatsby-plugin-offline is not compatible with your gatsby version 2.0.76 - It requires gatsby@^2.0.100
> error 
> Your plugins must export known APIs from their gatsby-browser.js.
> The following exports aren't APIs. Perhaps you made a typo or your plugin is outdated?
> 
> See https://www.gatsbyjs.org/docs/browser-apis/ for the list of Gatsby Browser APIs
> 
> - Your site's gatsby-browser.js is exporting a variable named "onServiceWorkerUpdateReady" which isn't an API.
> 
> Perhaps you meant to export "onServiceWorkerUpdateFound"?

Help pls.

**Comment by ergunpp** [comment]
Changing the * onServiceWorkerUpdateReady to onServiceWorkerUpdateFound in gatsby-browser.js solved my issue.

**Comment by dlindahl** [comment]
While your change may have worked around your issue, the semantics between these two methods seems important enough that I'd argue that this is still a "bug". The documentation lists [`onServiceWorkerUpdateReady`](https://www.gatsbyjs.org/docs/browser-apis/#onServiceWorkerUpdateReady) as a configuration option. So either there is a bug in the plugin somewhere, or the documentation needs to be updated to reflect this API change.
