### ISSUE TITLE
using local dependecies with "npm link" does not work with node v10 anymore

### ISSUE THREAD

**Issue by oschade** [gatsbyjs/gatsby#12002]
## Description

I use local dependencies which depends on `react`. I used `npm link` to use the modules locally.  `gatsby develop` fails when I using the modules as a plugin. It workded with node 6 (I think), after updating node to v10 it stopped working. I know, you can place local plugins in a plugin-directory inside the gatsby-folder, but the plugin using other local modules linked with "npm link", with throws the same error messages. And: it worked fine before updating node.js.

### Steps to reproduce

Create a folder `test` and inside a file `gatsby-browser.js` with the following content:

`
// eslint-disable-next-line
import React from 'react'
`

run `npm link` in the plugin-directory. Then run `npm link test` in your gatsby-folder and include the plugin in your gatsby-config.js.

### Expected result

Gatsby loads the plugin without any errors.

### Actual result

Gatsby throws the following error:

`
info bootstrap finished - 11.105 s

 ERROR  Failed to compile with 1 errors                                                               18:31:19
This dependency was not found:

* react in ../test/gatsby-browser.js

To install it, you can run: npm install --save react
× ｢wdm｣:
ERROR in ../test/gatsby-browser.js
Module not found: Error: Can't resolve 'react' in '[...]\www\test'
 @ ../test/gatsby-browser.js 2:0-26
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false [...]//test-blog//.cache//app
i ｢wdm｣: Failed to compile.
`

### Environment

  System:
    OS: Windows 10
  Binaries:
    npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.9 - C:\lang\Python27\python.EXE
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.1.11 => 2.1.11
    gatsby-image: ^2.0.29 => 2.0.29
    gatsby-plugin-manifest: ^2.0.18 => 2.0.18
    gatsby-plugin-offline: ^2.0.24 => 2.0.24
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-sharp: ^2.0.21 => 2.0.21
    gatsby-source-filesystem: ^2.0.21 => 2.0.21
    gatsby-transformer-sharp: ^2.1.14 => 2.1.14

Node-Version: 10.15.1

**Comment by freiksenet** [comment]
Can you try adding `react` as a dependency of your plugin? It fixed this issue when I was reproducing this problem.

**Comment by oschade** [comment]
Of course, this fix this. But then the plugin using its own version of react and I think, this could become a problem. I was hoping for a better solution. Normaly, gatsby-plugins don't have to include its own "react". But for locally development, this might be ok...

**Comment by MaximeCheramy** [comment]
Try with npm 6.7.0 instead.

**Comment by DSchau** [comment]
@oschade we generally solve this by installing our peerDependencies (which most plugins specify React as a peerDep if they rely on it) as devDependencies.

Then it would be installed and available.

I'm not sure this is actually an issue with Gatsby though--this seems like rather an issue with npm and module resolution when linking?

**Comment by oschade** [comment]
> 
> 
> Try with npm 6.7.0 instead. I have a problem with npm 6.8.0 that doesn't install the dependency of my local dependencies, this could be the same issue.

This does not work for me.
