### ISSUE TITLE
[www/showcase] Filter and scroll issues

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#12003]
Clicking any "Category" label on a "Showcase site card" does update the URL, but does not actually set and filter by the clicked category:

* open https://www.gatsbyjs.org/showcase
* scroll down past "Featured Sites" to the list of all Showcase sites (418)
* click "Featured" on the reactjs.org card <img src="https://user-images.githubusercontent.com/21834/53264833-ea1d3b00-36dc-11e9-9b70-07dd3714f52e.png" width="300px" />
* URL updates to https://www.gatsbyjs.org/showcase?filters%5B0%5D=Featured, but
  * category is not set as filter in sidebar
  * list is unfiltered, still showing all 418 Showcase sites

---

Another fun 🙉🙈one:

* click the "View all" link next to "Featured Sites" 
![image](https://user-images.githubusercontent.com/21834/53265041-792a5300-36dd-11e9-9f3d-1586d9d65c14.png)
* watch the viewport being scrolled down to `#showcase`, the URL being updated to https://www.gatsbyjs.org/showcase?filters%5B0%5D=Featured, and then …
* the scroll position is being reset to `0`
* filters are not set (just like described above)

**Comment by rohintangirala** [comment]
Just to clarify, the first issue applies to all the filter categories, not just Featured.

**Comment by freiksenet** [comment]
Thank you for the report! Would you like to make a PR to fix this issue?

**Comment by rohintangirala** [comment]
I'll check it out.

**Comment by wardpeet** [comment]
@rohintangirala I'm actually fixing this one already #11001

**Comment by wardpeet** [comment]
@fk i'm closing this one in favour of #11001 so we don't have 2 people working on the same issue.

**Comment by rohintangirala** [comment]
@fk Alright sounds good. I didn't really get to it anyway.

**Comment by wardpeet** [comment]
Sorry about this. If I knew earlier I would have gave you a few pointers instead
