### ISSUE TITLE
Bug? Browser always loads the largest possible image

### ISSUE THREAD

**Issue by baobabKoodaa** [gatsbyjs/gatsby#12009]
## Description

I noticed that my browser is always loading the largest possible images, regardless of viewport width and the fact that smaller images would be available in `srcset`. I believe there is a bug in the code which is generating `sizes` (which is supposed to tell the browser how to use the `srcset`). Or am I using gatsby-image somehow incorrectly? I couldn't find any documentation related to issues with `srcset` or `sizes`.

### Steps to reproduce

I created a website to demo the problem: https://gatsby-bug-reports.netlify.com/buggy-srcset/

It also has a more detailed explanation. Source for the demo is here: https://github.com/baobabKoodaa/blog/tree/imageBugsDemo

### Expected result

When Gatsby generates multiple sizes of an image, we expect the browser to choose to load the appropriate image. For example, if the user has a tiny screen, we expect the browser to load a tiny image. Or if a user has a large screen, we expect the browser to load a large image. In this instance I specifically set the "maxWidth" to 800, so I would expect the browser to never load an image larger than 800 pixels.

### Actual result

The browser always loads the largest possible image, regardless of viewport size or "maxWidth" parameter.

**Comment by KyleAMathews** [comment]
What image exactly is downloaded? Also, what type of device are you viewing it with?

**Comment by baobabKoodaa** [comment]
In the example web site this image shows up in the network tab: https://gatsby-bug-reports.netlify.com/static/be21c7dd0d11c74c18530fc39aefa922/bf242/mailboxes2.webp

I'm using Chrome on an Ubuntu laptop and I've tried resizing the browser to be very small, but no effect.

**Comment by baobabKoodaa** [comment]
Are you seeing different behavior on the same site?

**Comment by yogeshkotadiya** [comment]
It's working fine for me.
The site downloads a correct image size for current viewport or maybe am I missing something?

![screenshot_20190223_110020](https://user-images.githubusercontent.com/9676379/53282222-b8e35000-375a-11e9-8d01-e53b2f713491.png)

**Comment by baobabKoodaa** [comment]
Huh, that's weird. May I please ask you to double check that you aren't always getting the same sized image? I ask because I did some more experiments now, and:

- Chrome on Ubuntu always loads the largest image
- Chrome on Windows always loads the 800px the image (the one in your screenshot)

**Comment by baobabKoodaa** [comment]
Here is a screenshot from Chrome on Ubuntu: 

![screenshot](https://imgur.com/a/KrwmPO8)

**Comment by handreistoicescu** [comment]
I'm having the same problem with Chrome on MacOS Mojave. The widths specified in the srcset attribute of the <source> tag are not leading to the expected image being loaded.

**Comment by handreistoicescu** [comment]
I found the solution for my case. I should have used the maxWidth parameter for the GraphQL query:

`{
    allImageSharp {
      edges {
        node {
          id
          fluid(maxWidth: 360, quality: 80) {
            ...GatsbyImageSharpFluid_noBase64
          }
        }
      }
    }
  }`

If the maxWidth parameter is not set, the default image that is set in the <img> tag will have a default of 800px.

**Comment by baobabKoodaa** [comment]
In my case there already is a maxWidth parameter, and it's not working for me on 2 different devices.

**Comment by LekoArts** [comment]
> Also, what type of device are you viewing it with?

What Kyle meant: What monitor are you using? Because if it's High DPI ("Retina") it'll load other images

**Comment by baobabKoodaa** [comment]
Oh, I didn't realize that makes a difference.

Ubuntu laptop with High DPI screen: always loads the largest possible image
Windows desktop with normal DPI monitor: always loads the 800px image

**Comment by LekoArts** [comment]
Then you have the solution to your problem. In order to serve sharp images on "Retina" devices Gatsby will choose the image double/triple the size, so that you see it sharp.

The `fixed` query also does exactly that.

**Comment by baobabKoodaa** [comment]
So it works after all!

As @LekoArts said, I was seeing the higher resolution image on Ubuntu due to the high DPI screen.

On Windows I was seeing the 800px image all the time because I didn't have  "disable cache" checked there. (I saw other assets listed as "from memory cache", and this one wasn't listed like that, so I assumed it wasn't coming from cache. But it was, because the behavior changed after I checked the "disable cache" box).

**Comment by handreistoicescu** [comment]
> Then you have the solution to your problem. In order to serve sharp images on "Retina" devices Gatsby will choose the image double/triple the size, so that you see it sharp.
> 
> The `fixed` query also does exactly that.

It's not so much Gatsby that does that, but the inner workings of how the browser interprets the <picture> tag.

**Comment by dbx834** [comment]
I just stumbled across this post.

I was struggling with the same thing. I just started playing with `gatsby-image` and observed that Google Chrome was always getting the largest image. For quite some time I thought that it was a bug. But, it turns out that it's not a bug. 

BTW -- you can validate that different images are being fetched by [emulating](https://developers.google.com/web/tools/chrome-devtools/device-mode/?utm_source=dcc&utm_medium=redirect&utm_campaign=2016q3#enable-emulation-panel) mobile devices in Chrome (select a mid-range phone, iPhone or Nexus...), open the network panel and then do a hard-refresh... You'll see a different image being fetched...

---

Some articles that increased my understanding:

["How the browser selects the needed image size... We can't tell..."](https://www.liip.ch/en/blog/things-you-should-know-about-responsive-images)

"In general with `srcset` you can't predict the chosen candidate" - [Read more](https://stackoverflow.com/questions/28683635/is-there-something-wrong-with-my-srcset-definition-or-is-current-browser-suppor)

I think it's something to do with browser behaviour, screen specs. (retina), etc (?)...
