### ISSUE TITLE
get children data from directory using allFile

### ISSUE THREAD

**Issue by ndejesus1227** [gatsbyjs/gatsby#12006]
I have 46 CSV files, all with the same exact formatting/structure.I can successfully query one file at a time and get the data I need in JSON format. I would love to be able to query ALL of them at the same time. From what I can tell, this is not possible.

Using this query: 

<img width="1032" alt="screen shot 2019-02-22 at 7 04 24 pm" src="https://user-images.githubusercontent.com/1852675/53278013-d7066d00-36d4-11e9-972b-26d9512da8ec.png">

I'm able to get the name of each file, which is great. It'd be great if I can get the actual data from each file as well.

I think a similar issue to this is here:

#https://github.com/gatsbyjs/gatsby/issues/3727

I see that Kyle is asking the reporter to make a PR to handle this. If what I'm trying to do is actually not possible I would love to work on the PR for it, but would definitely need help/direction.

**Comment by KyleAMathews** [comment]
Do all the files have the same type of data? I.e. same columns?

**Comment by ndejesus1227** [comment]
@KyleAMathews Yes, all files have the same columns in the same order and everything. Just different data

**Comment by freiksenet** [comment]
This would be a new feature, likely a flag or config option in `gatsby-transformer-csv`/`gatsby-transformer-json` and their like, something like a `merge` flag that you can pass. Do you want to try tackling this? It's probably not a very small feature. As a workaround, you could concatenate files into one big CSV file for now.

**Comment by freiksenet** [comment]
You could also write a local source plugin, reusing code from transformer-csv, to do this loading locally.

**Comment by ndejesus1227** [comment]
@freiksenet hey!

I would love to take a shot at working on this. I personally need something done sooner than later so I might look into your workaround solution for now, but I would love to try and add this feature. I'd definitely need some help with approaching this if you'd be so kind to guide me

**Comment by ndejesus1227** [comment]
I just want to add one thing to make sure it's clear what I'm trying to do:

```
export const CharacterDataQuery = graphql`
  query {
    allAkumaMovesCsv {
      edges {
        node {
          MOVE_NAME,
          COMMAND,
          HIT_LEVEL,
          RANGE,
          GAP,
          TRACKING,
          CRUSH,
          JAIL,
          ENVIRONMENTAL,
          CANCELLABLE,
          METER_GAIN,
          DAMAGE,
          START_UP,
          ON_BLOCK,
          ON_HIT,
          ON_CH,
          IN_AIR,
          ON_WHIFF,
          ACTIVE
        }
      }
    }
  }
`;
```

See where it says "allAkumaMovesCsv"? I'd love for there to be a way to have like, "allFile" or something there that would look at every single file and get each value from the columns that exist.
