### ISSUE TITLE
A "styles.js" file is being loaded (that shouldn't exist)

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#12018]
Almost certainly related to https://github.com/gatsbyjs/gatsby/pull/11800

**Comment by KyleAMathews** [comment]
<img width="574" alt="screenshot 2019-02-23 07 26 08" src="https://user-images.githubusercontent.com/71047/53288419-68f59080-373c-11e9-89ee-e8c862452e09.png">

**Comment by luukdv** [comment]
This doesn't seem to be stale. How can I add the label?

**Comment by DSchau** [comment]
This seems to create a mostly empty .js file--investigate what this is doing and whether this is needed (probably not!).

**Comment by JesseFarebro** [comment]
Seems to be this caused by this: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/151. Upstream there is an open issue @webpack here: https://github.com/webpack/webpack/issues/7300

**Comment by DSchau** [comment]
@JesseFarebro thanks for surfacing that! Definitely seems to be the issue here!

**Comment by LekoArts** [comment]
Will be fixed with v5: https://github.com/webpack/webpack/issues/7300#issuecomment-498092637

**Comment by LekoArts** [comment]
This has been fixed in current `master` / `@next` tag
