### ISSUE TITLE
Error when installing packages gatsby@2.1.17 and gatsby-source-kentico-cloud@3.0.0

### ISSUE THREAD

**Issue by rshackleton** [gatsbyjs/gatsby#12019]
## Description

Error when installing packages via yarn.

`gatsby@2.1.17`
`gatsby-source-kentico-cloud@3.0.0`

```
error An unexpected error occurred: "could not find a copy of gatsby to link in C:\\Projects\\Personal\\rshackleton.co.uk\\node_modules\\gatsby-source-kentico-cloud\\node_modules".
```

The error seems to happen from `gatsby@2.1.5` onwards.

### Steps to reproduce

The issue happens with this version of the repository:

https://github.com/rshackleton/rshackleton.co.uk/tree/4570cfda95b2f25b746983bca9f4f2331ab00a3e

### Expected result

Packages should be installed successfully.

### Actual result

```
error An unexpected error occurred: "could not find a copy of gatsby to link in C:\\Projects\\Personal\\rshackleton.co.uk\\node_modules\\gatsby-source-kentico-cloud\\node_modules".
```

### Environment

```
  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
  Binaries:
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: 2.1.5 => 2.1.5
    gatsby-plugin-alias-imports: 1.0.5 => 1.0.5
    gatsby-plugin-emotion: 4.0.4 => 4.0.4
    gatsby-plugin-google-analytics: 2.0.14 => 2.0.14
    gatsby-plugin-manifest: 2.0.19 => 2.0.19
    gatsby-plugin-netlify: 2.0.11 => 2.0.11
    gatsby-plugin-offline: 2.0.24 => 2.0.24
    gatsby-plugin-react-helmet: 3.0.6 => 3.0.6
    gatsby-plugin-typography: 2.2.7 => 2.2.7
    gatsby-plugin-web-font-loader: 1.0.4 => 1.0.4
    gatsby-source-kentico-cloud: 3.0.0 => 3.0.0
```

**Comment by rshackleton** [comment]
Also reported here:

https://github.com/Kentico/gatsby-source-kentico-cloud/issues/48
https://github.com/yarnpkg/yarn/issues/7061

**Comment by KyleAMathews** [comment]
Can you try deleting node_modules and reinstalling?

**Comment by rshackleton** [comment]
@KyleAMathews have tried a fresh install, the error would keep happening.

https://github.com/Kentico/gatsby-source-kentico-cloud/issues/48#issuecomment-466669643

Based on the update above I think the issue lies with the source plugin.
