### ISSUE TITLE
[www/tutorial/part-four] Plugin Library link behavior

### ISSUE THREAD

**Issue by sdolber** [gatsbyjs/gatsby#12029]
### Description

Clicking on the Plugin Library link in the Part Four Tutorial page, in the section "When do I use unstructured data vs GraphQL?" takes you to a page not found.

### Steps to reproduce

1. Open [https://www.gatsbyjs.org/tutorial/part-four/#data-in-gatsby](https://www.gatsbyjs.org/tutorial/part-four/#data-in-gatsby)
2. Click on the Plugin Library link in the "When do I use unstructured data vs GraphQL?" section
<img width="936" alt="screen shot 2019-02-23 at 11 04 27 pm" src="https://user-images.githubusercontent.com/374992/53295005-959ebc00-37bf-11e9-99ff-6e1c97a94d5a.png">

### Expected result

Should redirect to [https://www.gatsbyjs.org/plugins/](https://www.gatsbyjs.org/plugins/)

### Actual result

Displays a Page not found
<img width="923" alt="screen shot 2019-02-23 at 11 07 28 pm" src="https://user-images.githubusercontent.com/374992/53295019-e8787380-37bf-11e9-8b6e-0b208fa7294c.png">

### Environment

Reproduced in Mac OS 10.14.3 using Firefox 65.0 and Chrome 72.0.3626.96.

**Comment by jonniebigodes** [comment]
@sdolber i can confirm it. it should point there. the url should be `https://www.gatsbyjs.org/plugins/` not `https://www.gatsbyjs.org/packages/`. If you're willing, read the [docs](https://www.gatsbyjs.org/contributing/)  for contributing, fork the repo, make the adjustment to the documentation and submit a pull request and don't forget to mention this issue. Sounds good?

**Comment by sdolber** [comment]
Thanks! Sounds good, I'll check it out.
