### ISSUE TITLE
[gatsby-source-contentful] Fields like contentful_id should not be nullable

### ISSUE THREAD

**Issue by IanVS** [gatsbyjs/gatsby#12028]
## Description

It seems like many more fields in the contentful graphql schema should be marked as always present (non-nullable) than currently are.  I noticed this when exploring contentful data in graphiql, and it's particularly noticeable/painful when generating typescript definitions from the graphql schema.  For example, the edges in a connection type come across as:

```
edges: [ContentfulSchoolDayEdge]
```

Which means that there could be `null` or `undefined` values in the array of edges, which to my knowledge isn't possible.

Then, digging deeper, the node of the edge is not required, nor is even the `contentful_id` nor `node_locale`.  And ideally, if a field is marked as required in the contentful schema, it would also come across as non-optional in graphql.

This causes problems because it means that when using typescript, I have to include null checks at tons of levels, which is kind of a pain.  

I don't know if this is something that gatsby has _any_ control over whatsoever.  If not, maybe it's worth working with contentful to refine their api a bit.  I poked around a little, but I can't figure out how the graphql schema is being generated for the contentful api.

### Steps to reproduce

Set up a contentful space with some content types and content, and explore them using graphiql.

### Expected result

I _think_ that many more types should have the `!` after them than they do.  I don't have a complete list, but if it's something that's even possible to change, I could try to create one.

### Actual result

A lot of types are indicated as optional.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.6.2 - /usr/local/bin/zsh
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 64.0.2
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.4 => 2.1.4 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-plugin-emotion: ^4.0.3 => 4.0.3 
    gatsby-plugin-manifest: ^2.0.2 => 2.0.17 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.6 
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20 
    gatsby-plugin-typescript: ^2.0.0 => 2.0.7 
    gatsby-source-contentful: ^2.0.1 => 2.0.29 
    gatsby-source-filesystem: ^2.0.20 => 2.0.20 
    gatsby-transformer-remark: ^2.1.5 => 2.2.4 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13 
```

**Comment by freiksenet** [comment]
We had tests around doing typescript generation internally and that was a big pain point. We are getting better tools to do that with #11480 and we'll make sure to make more stuff non-nullable, at least for derived fields like edges, pageinfo etc.
