### ISSUE TITLE
Source contetful returns  `Cannot read property 'localized' of undefined` error

### ISSUE THREAD

**Issue by d-ivashchuk** [gatsbyjs/gatsby#12037]
I have changed some data in contentful and without changing anything in my gatsby project or config I am now getting this error on `develop` or `build`:
```
error Plugin gatsby-source-contentful returned an error
TypeError: Cannot read property 'localized' of undefined
```
Can't find anything useful anywhere, and it seems like some chache issues to me, as I don't even have content types in contentful which have localizations that I know to be accountable for such errors.

# Solution:
 > Seems  like I solved this one by regenerating contentful access token and using it in config

**Comment by overlordofmu** [comment]
@d-ivashchuk, just letting you know this was useful troubleshooting a similar issue today. Even though you resolved it yourself, sharing the issue and solution helped someone else today. Thank you for sharing what you learned!

**Comment by tobiasfrei** [comment]
Solution is to delete the **.cache** folder
