### ISSUE TITLE
RHL / HMR does not reload  

### ISSUE THREAD

**Issue by pungggi** [gatsbyjs/gatsby#12034]
I am not sure where to start explaining my issue maybe its here may be its react hot loader..
maybe its [linaria](https://github.com/silvenon/gatsby-plugin-linaria).

I am using gatsby with [react easy state](https://github.com/solkimicreb/react-easy-state).
gatsby 2.0.69 introduced a new version of react-hot -loader 4.6

As of this version Props passed to a  styled` component are not hot updated  **if they are wrapped with view from react easy state**..

For example:

Box.js
```js
import { styled } from "linaria/react"

const Box = styled.div`
  color: ${(props) => (props.color ? props.color : "red")};

export default Box
```

then i consume

index.js

```js
import { view } from 'react-easy-state'

export default view(() => {
  const classColor = css`
    color: green;
  `
  return (
     <Box padding={[30, 2, 10, 20]}>
       <div className={classColor}>
         <h1>About</h1>
       </div>
     </Box>
  )
})
```
If I change the classColor it updates.
But changing the value of the `padding` prop does not trigger a reload. This was working with gatsby 2.0.68 that uses react hot loader 4.5.

**Comment by freiksenet** [comment]
Thank you for your report! I think that should be an issue with react-hot-loader, I wonder if you can create a bug report there.

**Comment by pungggi** [comment]
You are probably right.
