### ISSUE TITLE
Don't silently process.exit

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#12042]
[Calling `process.exit` without an error message](https://github.com/gatsbyjs/gatsby/blob/0df55f61587fe7f86e48bba5599d3fdc5d59b19b/packages/gatsby/src/internal-plugins/query-runner/gatsby-node.js#L11) is really hard to debug.

**Comment by KyleAMathews** [comment]
Hmm I have no idea why that's there. And yeah, it doesn't make any sense.

Luckily my almost ready to go PR just removed that file.

https://github.com/gatsbyjs/gatsby/pull/11897

**Comment by freiksenet** [comment]
`process.exit` also fails very annoyingly in jest tests (hanging jest infinitely). Should we fix that too?

**Comment by wardpeet** [comment]
We should move to process.exitCode instead. I think it's a good idea to handle this inside https://github.com/gatsbyjs/rfcs/pull/31

**Comment by KyleAMathews** [comment]
Oh this is fixed now.

**Comment by KyleAMathews** [comment]
The linked file doesn't exist anymore
