### ISSUE TITLE
Make GraphQL queryable from a child component of Layout

### ISSUE THREAD

**Issue by sebastienfi** [gatsbyjs/gatsby#1206]
Let's say a header component that's not a page, and that's a child of Layout.
Should this component be able to query graphQL ?

> Right now there's a limitation where only page components (and components that are children of pages) can query for graphql data...
> So a header component right now, you just need to hard code data somewhere else like a yaml file and import that

Workaround : use a static file (that could be writen from a source plugin : yaml, json, ...).
Example in consuming a yaml file (for the docs sidebar) : https://github.com/gatsbyjs/gatsby/blob/1.0/www/src/pages/docs/doc-links.yaml

**Comment by whmountains** [comment]
IMHO it would be very useful.

In my case I have a global footer that needs a responsive image but I can't load it in the usual way via GraphQL.  The only workaround would be to use `responsive-loader` directly, but that has caching issues and really slows down the build.
