### ISSUE TITLE
Why I can't use dash character "-" in path?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#12063]
I would like to use this `<Home path="/page-test" />` it doesn't work. 
Without the dash like this:  `<Home path="/pagetest" />`, it works.

Here is the error when I use dash in path

<img width="1043" alt="capture d ecran 2019-02-25 a 10 27 03" src="https://user-images.githubusercontent.com/814410/53327358-ed384700-38e7-11e9-9272-65be0e8230f1.png">

```
 exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions;
  if (page.path.match(/^\/page-test/)) {
    page.matchPath = `/page-test/*`;
    createPage(page);
  }
};
```

**Comment by freiksenet** [comment]
Thank you for the report! Could you please provide a bigger reproduction case, eg a simple gatsby project with a reproduction?

**Comment by thejamespower** [comment]
We are having the a similar issue in our project. We are dynamically creating pages using the createPage API, using people's names as part of the path ('Joe Bloggs' -> http://oursite.com/joe-blogs-123). Double-barrelled surnames ('Joe Bloggs-Smith' -> http://oursite.com/joe-blogs-smith-123) do not work. Gatsby throws a 404 for the page-data.json file in both develop and build, even though it can be clearly seen in the public output directory.

**Comment by mgray88** [comment]
This seems to be affecting me. To repro, I'm simply following the tutorial: 

https://www.gatsbyjs.org/tutorial/part-five/#build-a-page-with-a-graphql-query

This is where I'm at and it crashes when the file is named `my-files.js`, but works fine when it's named `myfiles.js`

Environment:
OS: MacOS 10.15.3
Gatsby: 
```
Gatsby CLI version: 2.11.7
Gatsby version: 2.20.12
```
npm: 6.14.4
