### ISSUE TITLE
Allow path whitelisting for gatsby-plugin-fullstory

### ISSUE THREAD

**Issue by dimitrisnl** [gatsbyjs/gatsby#12067]
## Summary

`Gatsby-plugin-fullstory` adds the [fullstory](https://www.fullstory.com) tracking code in each page. It would be great to provide an array of pathnames where this script will not be present.

### Basic example

```
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-fullstory`,
      options: {
        fs_org: YOUR_ORG_ID,
		fs_paths_to_exclude: ['/this-landing-page/', '/thank-you/']
      },
    },
  ],
}
```

**Comment by freiksenet** [comment]
Thank you for the report! Do you want to make a PR to add this? Thanks!

**Comment by dimitrisnl** [comment]
I would love to @francesmx

**Comment by dimitrisnl** [comment]
@freiksenet 	I did an implementation, that can be found [here](https://github.com/dimitrisnl/gatsby/commit/dc5b489f8479d96dc499f27ebd3ea256bc490652)

There is a caveat that I didn't think about. If I visit the whitelisted page then I don't include the script in the <head>, which is good. 

But if I navigate to another page that I want to track, the script won't be present since the routing was done client-side. So there will be no tracking activity at all.

Likewise, if I visit a page that allows tracking, the script will be present, and will persist when navigating to the whitelisted pages.

What do you think? Should this be left to the user, implemented on a Layout wrapper component instead?
