### ISSUE TITLE
Do I can use use Gatsby with soap API ?

### ISSUE THREAD

**Issue by faycelbouamoud** [gatsbyjs/gatsby#12064]
Hello, 
As I mentioned in the title, Do I can use Gatsby JS with a SOAP api ?
Thanks.

**Comment by oorestisime** [comment]
Do you mean to create a source plugin taking in data from a SOAP api?

Generally as long as you are able to do this in JS then you shouldn't feel in any way limited in gatsby. It is a JS and React app in any case.
