### ISSUE TITLE
Cant get npx gatsby new project to work

### ISSUE THREAD

**Issue by brendonco** [gatsbyjs/gatsby#12075]
Hi,

I am getting below errors:

```
Could not locate the bindings file. Tried

\node_modules\sharp\build\sharp.node

  error  Cannot query field "childImageSharp" on type "File"  graphql/template-strings

node_modules\sharp\lib\binding\node-v57-win32-x64\sharp.no
```

I am using node version: 8.10.0

**Comment by freiksenet** [comment]
It's likely to be the same issue as https://github.com/gatsbyjs/gatsby/issues/10620. What's your version of Python?

**Comment by loconluis** [comment]
Same issue. Im using Python 2.7.15

**Comment by DSchau** [comment]
Looks like you're on Windows, which requires some set-up steps to get up and running with Sharp, in particular.

I'd encourage you to check out the [Gatsby and Windows](https://www.gatsbyjs.org/docs/gatsby-on-windows/) documentation, which may help you resolve this issue.

Please check that out, and then if you're still running into an issue, please reply back here and we'll help further in debugging!

Thanks!
