### ISSUE TITLE
gatsby-plugin-feed requires creating slugs for pages

### ISSUE THREAD

**Issue by johnreynoldsventure** [gatsbyjs/gatsby#12079]
This is probably obvious to many, but while adding gatsby-plugin-feed to my site I discovered that you must add slugs to your MarkdownReact nodes.

The documentation for how to do this is very clear: https://www.gatsbyjs.org/docs/creating-slugs-for-pages/

What wasn't clear (to me) was that this was a dependency for gatsby-plugin-feed.

I hope this helps others...

**Comment by KyleAMathews** [comment]
The plugin shouldn't work this way. You should pass into the configuration which field to use does the slug. Would you be interested in working on a PR for this?

**Comment by johnreynoldsventure** [comment]
I'd love to help more Kyle, but I fear I don't know enough - I'm just getting started with gatsby.
I started with the gatsby tutorial, and have been added functionality as I need it.  Likely my problems are due to me missing a step or two along the way rather than anything fundamental.

**Comment by tomoyukikashiro** [comment]
@johnreynoldsventure 

> What wasn't clear (to me) was that this was a dependency for gatsby-plugin-feed.

Your are right. :)  `gatsby-plugin-feed` require `slug` by default. 
=> [here is the code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-feed/src/gatsby-node.js#L16-L17) where plugin use `slug` to define each page url.

But you can costomize it by passing option into `gatsby-config.js`.

In my example I try to change default site url from `https://example.com/${slug}` to `https://example.com/posts/${slug}` in feed.
=> [here is the code](https://github.com/tomoyukikashiro/gatsby-starter-blog-amp-to-pwa/commit/f69c56666a28bf6dead474b76e095e247998a795).

**Comment by laurosilvacom** [comment]
I'll like to work on a PR @KyleAMathews. Can you point me on the write direction?

**Comment by VGoose** [comment]
I think this should be fixed by updating the docs stating that the default serializer requires a slug field, rather than any change to the plugin.

**Comment by DSchau** [comment]
@VGoose we actually did that recently -> https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-feed#how-to-use

(We don't note what you need to do to use the internal serialize, just that we recommend you write your own!)

**Comment by VGoose** [comment]
@DSchau any reason to not be explicit about the requirements of the default serializer? The issue was opened because it wasn't clear.
