### ISSUE TITLE
gatsby-image lazy loading  not working in MacOS Safari

### ISSUE THREAD

**Issue by handreistoicescu** [gatsbyjs/gatsby#12074]
## Description

In MacOS Safari, all images are downloaded at once, regardless of the expected lazy loading. In all the other browsers I tested in (i.e. Chrome, Firefox), lazy loading works just fine.

### Steps to reproduce

Open a website built in Gatsby that contains as many fluid gatsby-image Img components as the browser will start displaying the scroll bar, so a few images won't be in the viewport yet. 

### Expected result

Only displayed images are downloaded.

### Actual result

As the Network tab of the Developer Tools shows, all images are loaded on page load, even those that are not scrolled to yet.

### Environment

System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 2.7.14 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 64.0
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.104 => 2.0.104 
    gatsby-image: ^2.0.30 => 2.0.30 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20 
    gatsby-source-filesystem: ^2.0.20 => 2.0.20 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13

**Comment by yogeshkotadiya** [comment]
That's because Safari 12 doesn't support `IntersectionObserver` yet. But the support is now coming soon as it's already available in Sarafi 12.1 Technical Preview.

**Comment by handreistoicescu** [comment]
All clear now. Didn't know `IntersectionObserver` even existed, so thank you for the enlightenment.

P.S. Amazing work you're doing here, people. I'm fascinated by what Gatsby has under the hood.

**Comment by arturhenryy** [comment]
@handreistoicescu 
here is how to fix this.

add a gatsby-browser.js to your root

insert following code
```
export const onClientEntry = async () => {
  if (typeof IntersectionObserver === "undefined") {
    await import("intersection-observer");
    console.log("IntersectionObserver polyfilled ;)");
  }
};
```

this will polyfill intersectionObserver for Safari until it will be supported native.

**Comment by handreistoicescu** [comment]
Where do I import `"intersection-oberver"` from? If I do only as you said, I get a reference error (`Module not found: Error: Can't resolve 'intersection-observer'`)

**Comment by arturhenryy** [comment]
@handreistoicescu i just noticed that is missed that part. i edited it. if you use npm just switch 
yarn add intersection-observer 
with 
npm install intersection-observer --save

**Comment by handreistoicescu** [comment]
Thank you. Worked like a charm!

**Comment by yogeshkotadiya** [comment]
@handreistoicescu Please close the issue if resolved.

**Comment by rzubrycki** [comment]
Hell guys, i got the same problem, but now safari has support for intersection observer api...
Any ideas?

**Comment by jonathon-alcindor** [comment]
This is happening to me as well, using Safari 13.1. I'm also polyfilling for the intersection-observer as mentioned above.
