### ISSUE TITLE
Issue when fetching Contentful data with GraphQL - "URL scheme must be "http" or "https" for CORS request"

### ISSUE THREAD

**Issue by MaralS** [gatsbyjs/gatsby#12071]
Hi everyone

## Description
I'm trying to build my blog with Contentful. I already installed Contentful plugins. But I have some issues to display the data in my blog post template. I really don't know what's wrong because I followed tutorials on gatsby official docs.

### Steps to reproduce

clone my repo and run `yarn develop` on the dev branch - [link to the repo](https://bitbucket.org/maralsabbagh/maralsabbagh/src/dev/)

### Expected result

Display the data in my component

### Actual result

Nothing in the browser and this error in my console.
`"URL scheme must be "http" or "https" for CORS request"`

### Environment

```
System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
  Binaries:
    Yarn: 1.3.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: latest => 2.0.54
    gatsby-cli: ^2.4.5 => 2.4.5
    gatsby-image: latest => 2.0.20
    gatsby-link: latest => 2.0.6
    gatsby-plugin-canonical-urls: latest => 2.0.7
    gatsby-plugin-catch-links: latest => 2.0.8
    gatsby-plugin-google-tagmanager: latest => 2.0.6
    gatsby-plugin-manifest: latest => 2.0.9
    gatsby-plugin-offline: latest => 2.0.16
    gatsby-plugin-react-helmet: latest => 3.0.2
    gatsby-plugin-sass: ^2.0.4 => 2.0.4
    gatsby-plugin-sharp: latest => 2.0.13
    gatsby-plugin-sitemap: latest => 2.0.2
    gatsby-remark-images: ^3.0.0 => 3.0.0
    gatsby-source-contentful: ^2.0.32 => 2.0.32
    gatsby-source-filesystem: latest => 2.0.8
    gatsby-transformer-json: latest => 2.1.5
    gatsby-transformer-remark: latest => 2.1.12
    gatsby-transformer-sharp: latest => 2.1.8
```

thanks in advance for your help

**Comment by freiksenet** [comment]
Hi! Thanks for the report. I can't reproduce, I can get your site to display with dev branch (though there is some style issue and they don't load like they do for master). Could you try reinstalling node_modules and maybe deleting `.cache` directory on your site?

**Comment by MaralS** [comment]
@freiksenet Hi,
Thanks for your reactivity. It's normal the dev version is completely different from master branch. I'm working on the different pages :)
If you go the URL [http://localhost:8000/blog/create-a-blog-using-gatsby-js-and-contentful/](http://localhost:8000/blog/create-a-blog-using-gatsby-js-and-contentful/), do you have the same error ?

**Comment by freiksenet** [comment]
I get the following error:

![2019-02-25-15 26 23](https://user-images.githubusercontent.com/172936/53340497-d0b10480-3911-11e9-98fc-16ce0fe6bc60.png)

**Comment by freiksenet** [comment]
However it could also cause I don't have your contentful API key and maybe it doesn't return the same data as for you.

**Comment by freiksenet** [comment]
Ok, actually I could make it run by removing some of the undefined variables (metaDesc, scale, rhytm).

**Comment by MaralS** [comment]
The api key is in the .env file
You can test the graphql query 
```
{
  allContentfulPost {
    edges {
      node {
        createdAt
        updatedAt
        postTitle
        slug
        metaDesc
        metaTitle
        content {
          childContentfulRichText {
            html
          }
        }
        postThumbnail {
          fluid {
            src
          }
        }
      }
    }
  }
}

```
I replaced 
metaDesc by post.metaDesc 
metaTitle by post.metaTitle
I do not have the error related to the metaDesc variable but I always have the error 
![capture](https://user-images.githubusercontent.com/19915917/53340862-516c0280-390a-11e9-9cee-e61b8b9e14e1.PNG)

**Comment by freiksenet** [comment]
@MaralS could you push those changes to the dev branch?

**Comment by MaralS** [comment]
@freiksenet it's done

**Comment by freiksenet** [comment]
It runs for me :disappointed: 

![2019-02-25-15 43 38](https://user-images.githubusercontent.com/172936/53341410-28506f80-3914-11e9-95fb-88b72510ce0c.png)

Can you try fixing the import for `DefaultLayout` in the component? It should be `import { DefaultLayout }`. That's the only change that I do to make it run, but I don't get the above errors even in that case. But it could be difference of behaviour while running windows and linux.

**Comment by MaralS** [comment]
@freiksenet It runs for me too now but i don't see the content metaDesc and metaTitle in the code.
