### ISSUE TITLE
Page scrolling not smooth

### ISSUE THREAD

**Issue by ergunpp** [gatsbyjs/gatsby#12082]
Hi,
I have almost finished a web project and built it and am now serving a test version at: http://chefs-test.s3-website.eu-central-1.amazonaws.com

But I have now realised on mobile, the touch page scroll is not working or just very jumpy and not smooth.
Is there a way to solve this?

Thanks,

**Comment by kbrgl** [comment]
Hi!

Are you using any libraries that modify scroll behavior (smooth-scrolling anchors, Remark autolink, etc.)?

Can you reproduce this / let me know what plugins you have installed?

**Comment by ergunpp** [comment]
No I am not using any library. Which one do you recommend?

**Comment by Kosai106** [comment]
You can try adding `-webkit-overflow-scrolling: touch;` to your containing divs, but ultimately it's a hack and the issue lies somewhere else.

**Comment by kbrgl** [comment]
Sorry, I should have been more clear. Are you currently using any libraries that make changes to scroll behavior?

(I think it's more likely that this is an issue with the website layout as opposed to an issue with Gatsby 😄)

**Comment by ergunpp** [comment]
No i am not using any libraries. Can you give me hint what issues may cause
this? You can also check the demo site with the link above.
I aporeciate your help.

**Comment by kbrgl** [comment]
May or may not be related to your bug, but somewhere in your code you have a where a div has a `classname` attribute as opposed to a `className` attribute. (Note the uppercase 'n'.)

**Comment by kbrgl** [comment]
Could you create a small repo to reproduce this issue and link it here? I spent some time trying to track down the bug (using devtools) and couldn't figure it out.

**Comment by KyleAMathews** [comment]
It seems to scroll just fine for me. Perhaps what you're seeing is a bit of glitchness when images load? Is scrolling smoother when you scroll back up?

**Comment by ergunpp** [comment]
What i mean is on other websites when you pull your finger down once it
keeps scrolling down freely and than comes slowly to halt. But for this one
it just scrolls down as much as you pull. You have to make multiple
pulldown or up movements to navigate

**Comment by KyleAMathews** [comment]
What device are you on?

**Comment by dkrasniy** [comment]
It’s a CSS issue. Try adding the following css to your body/html 

overflow-y: scroll;
  -webkit-overflow-scrolling: touch;

**Comment by ergunpp** [comment]
I am on iphone xs max

**Comment by KyleAMathews** [comment]
Can you see the same issue on any other Gatsby sites?

**Comment by ergunpp** [comment]
@KyleAMathews no I have another gatsby website which scrolls just fine.

**Comment by ergunpp** [comment]
> It’s a CSS issue. Try adding the following css to your body/html
> 
> overflow-y: scroll;
> -webkit-overflow-scrolling: touch;
> 
> https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

This solved the problem! Thank you so much!

**Comment by ergunpp** [comment]
No. The weird thing is i did another site with gatsby and the same issue is
not happening there. I just need help how to solve that problem.

**Comment by baptisteArnaud** [comment]
Hey guys ! I'm pretty sure this bug exists. I recorded a video :

[Gatsby scroll bug on mobile devices](https://www.youtube.com/watch?v=OPzprTx-5TA)

I think the problem comes from the gatsby divs wrapping the body tag. I tried applying a `overflow-y : hidden` but it seems not to solve the problem
