### ISSUE TITLE
WebWorker support

### ISSUE THREAD

**Issue by universse** [gatsbyjs/gatsby#12095]
Hi. Is it possible to use web workers with Gatsbyjs? I can't seem to find any resource related to this. If I wanted to use something like https://github.com/developit/workerize-loader, I would need to create custom webpack config?

**Comment by freiksenet** [comment]
Hi! What do you want to do with workers? We use workers in [gatsby-plugin-offline](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/), for example.

**Comment by universse** [comment]
Hi. There are a few use cases I have in mind. I have a big list of items and I want to display it as a feed. The users can manipulate the list through sorting and filtering. I was testing on throttled cpu on chrome and the UI just froze. So I was thinking maybe could offload that to another thread via web worker instead. I understand that we could query presorted and prefiltered data but that means transferring a lot of data to the client, so I didn't go for that option.

Another use case is regarding firebase. Basically, firebase size is huge (https://github.com/firebase/firebase-js-sdk/issues/332) and it affects the initial page load. I guess the parsing and processing of firebase bundles can be offloaded to web workers instead to improve performance.

I have been exploring https://github.com/developit/workerize and https://github.com/GoogleChromeLabs/comlink. I'm just not sure if there is anything to take note of regarding configuration since both projects come with their own webpack loader. And my knowledge with webpack and babel configs in general is quite limited.

**Comment by wardpeet** [comment]
Sure you can! By default we do not support it but we use webpack under the hood which means all available plugins are available.

https://www.gatsbyjs.org/docs/add-custom-webpack-config/#add-custom-webpack-config

you can add your specific workerize code using https://www.gatsbyjs.org/docs/browser-apis/. If you need any help, just let us know!

**Comment by universse** [comment]
Ok got it. Thanks a lot!

**Comment by wdevon99** [comment]
@universse Did you find a solution to your problem, i am trying to do the exact thing!

**Comment by universse** [comment]
@wdevon99  Yes. I ended up using https://github.com/developit/workerize-loader
gatsby-node.js
```javascript
exports.onCreateWebpackConfig = ({ actions: { replaceWebpackConfig }, getConfig, stage }) => {
  const config = getConfig()

  config.module.rules.push({
    test: /\.worker\.js$/,
    use: { loader: 'workerize-loader' }
  })

  config.output.globalObject = 'this'

  config.resolve.modules = [resolve('./src'), 'node_modules']

  replaceWebpackConfig(config)
}
```
Then suffix your worker file with .worker e.g search.worker.js
Hope it helps!

**Comment by fayez-nazzal** [comment]
Any solution other than using workerize-loader ? 

As of now, workerize-loader doesn't support webpack 5 and you end up having an error in gatsby 3...

**Comment by barbalex** [comment]
Does this work for webpack5? https://webpack.js.org/guides/web-workers/

**Comment by zuspan** [comment]
@barbalex - I've tried setting this up as per webpack 5 out-of-the-box usage as described in that link. It compiles, but the message posting doesn't seem to work. I have also tried deploying it, and gatsby errors with:

`WebpackError: ReferenceError: Worker is not defined`

gatsby: 4.21.1
webpack: 5.74.0

test.worker.js:
```
/* eslint-disable-next-line no-restricted-globals */
self.onmessage = ({ data: { question } }) => {
  console.log('hi from web worker');
  /* eslint-disable-next-line no-restricted-globals */
  self.postMessage({
    answer: 42,
  });
};
```

code from the component that loads the worker:
```
const worker = new Worker(new URL('./tes.worker.js', import.meta.url));
worker.postMessage({
  question:
    'The Answer to the Ultimate Question of Life, The Universe, and Everything.',
});
worker.onmessage = ({ data: { answer } }) => {
  console.log(answer);
};
```

I know the issue has been closed for a bit, but let me know if anyone has any leads on how to solve this...
