### ISSUE TITLE
feat: gatsby-plugin-feed and i18n

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#12093]
> Just as an idea: What about i18n and RSS feeds?

To capture @LekoArts' suggestion in https://github.com/gatsbyjs/gatsby/pull/11941, RSS feeds should also support internationalization. There is a prerequisite for better i18n support in general, but this issue is specifically for generating internationalized RSS feeds. 

@DSchau's work in https://github.com/gatsbyjs/gatsby/pull/12085 is also a good prerequisite, as he's fixing issues with multiple feeds.

Related to https://github.com/gatsbyjs/gatsby/issues/3853

**Comment by CanRau** [comment]
Yay, I've a need for this, too 🎉 👍 

I was already looking into this, not sure what the best API would be though..
Maybe I could look into it and prepare a PR for it if we agree on something and no one else is already on it..

I would love to have it kind of automated, so not like manually providing multiple feeds with a `language` prop but rather everything driven by the `query` and `serialize`
One idea I had was using [GraphQL's group](https://www.gatsbyjs.org/docs/graphql-reference/#group) feature to "split" the results based on language
then `title` and `output` could accept a function (as alternative to string) to customize the value based on `query` & `serialize`

Any ideas, suggestions, wishes?

**Comment by marcysutton** [comment]
This is delayed, but a PR would be pretty fantastic as no one has yet picked this up. @LekoArts any input on @CanRau's questions?
