### ISSUE TITLE
docs: Managing pull requests

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#12094]
## Description

It would be really helpful to have a doc on Managing PRs in the contributing section. It was in my original [contributing IA RFC](https://github.com/gatsbyjs/rfcs/pull/29) but we didn't write that page for launch. So this issue is an attempt to make that happen!

Specifically, we need a page that describes what contributors and maintainers should know about changing the Gatsby codebase via pull requests: things like linting commands while working, how to run tests, and the requirements to merge, including some info about Codeowners.

If there is a need to write two separate pages for contributors and maintainers we can do that, but I think that line is pretty blurry with our large membership...so one page makes sense to me right now. It could go under Triaging Github Issues in the [How to Contribute](https://www.gatsbyjs.org/contributing/how-to-contribute/) section.

**Comment by lauragift21** [comment]
I could take a stab at this if it's still open.

**Comment by marcysutton** [comment]
@lauragift21 this stuff should probably come from the core team, since they have insider knowledge of conventions that aren't yet documented. But I'll definitely keep you in mind for this as we move forward and reach out if/when we need help!

Something that would be good to include: naming conventions for PRs, a la [this comment](
https://github.com/gatsbyjs/gatsby/pull/12310#issuecomment-469606727): 

> I notice you changed the title. Are there any guidelines published anywhere for naming conventions so I can stick to them?

**Comment by lauragift21** [comment]
Right totally understand that. Thanks @marcysutton
