### ISSUE TITLE
The plugin "gatsby-plugin-typescript-css-modules@1.0.4" is exporting a variable named "modifyWebpackConfig" which isn't an API warning at `yarn start`

### ISSUE THREAD

**Issue by JustFly1984** [gatsbyjs/gatsby#12091]
Is there a way to update this package for v2 support?

**Comment by freiksenet** [comment]
Hi! This plugin isn't maintaned by Gatsby, I wonder if you could report the issue in [their repo](https://github.com/jcreamer898/gatsby-plugin-typescript-css-modules).

**Comment by JustFly1984** [comment]
@freiksenet Thank you, it seems that plugin is unmaintained. It could be useful to have official version supported by v2

**Comment by DSchau** [comment]
@JustFly1984 as @freiksenet mentioned, this is an issue outside of Gatsby.

We are working on quality metrics and "official Gatsby plugins" to our plugins search, so hopefully implementing both of those will help you avoid this issue in the future.

Thanks for using Gatsby 💜
