### ISSUE TITLE
allImageSharp query sort 

### ISSUE THREAD

**Issue by handreistoicescu** [gatsbyjs/gatsby#12109]
## Summary

I'm using GraphiQL to test an allImageSharp query with a sort parameter, but the sorting doesn't happen at all.

## Relevant information

I have a folder with images named 01.jpg, 02.jpg to xx.jpg. I want my query to return the results ordered by originalName.

The query looks like this in GraphiQL:

```javascript
{
  allImageSharp(sort: { fields: [fluid___originalName], order: ASC }) {
    edges {
      node {
        fluid {
          originalName
        }
      }
    }
  }
}
````

Here are the query results:

```javascript
{
  "data": {
    "allImageSharp": {
      "edges": [
        {
          "node": {
            "fluid": {
              "originalName": "03.jpg"
            }
          }
        },
        {
          "node": {
            "fluid": {
              "originalName": "02.jpg"
            }
          }
        },
        {
          "node": {
            "fluid": {
              "originalName": "01.jpg"
            }
          }
        },
        {
          "node": {
            "fluid": {
              "originalName": "04.jpg"
            }
          }
        },
        {
          "node": {
            "fluid": {
              "originalName": "05.jpg"
            }
          }
        }
      ]
    }
  }
}
````

What I expected was that the items from the edges array were ordered by the originalName property. Isn't this how it should have worked?

I should mention that I'm fairly new to GraphQL, so maybe it's something obvious that I'm missing.

**Comment by stefanprobst** [comment]
This is actually a bug in Gatsby, see #11368. Currently we cannot sort on fields that are added with the `setFieldsOnGraphQLNodeType` API (which the sharp plugin uses).

**Comment by stefanprobst** [comment]
You could try work around this by using something similar to this:
```graphql
{
  allFile(sort: { fields: [base] }) {
    edges {
      node {
        base
        childImageSharp {
          fluid {
            src
          }
        }
      }
    }
  }
}
```

**Comment by handreistoicescu** [comment]
Thanks for the info, and for the amazing work on GraphQL. Should I close this issue now?

**Comment by stefanprobst** [comment]
Closed. Thanks for using Gatsby!
