### ISSUE TITLE
gatsbyjs.org build assumes native dependency `libvips-dev`

### ISSUE THREAD

**Issue by jamo** [gatsbyjs/gatsby#12101]
## Description

`yarn run develop` for gatsbyjs.org (`www/`) fails with following errors on a fresh ubuntu 18.04 setup:
```
error Failed to process image /path/to/gatsby/www/.cache/gatsby-source-filesystem/31986f7e77b390d77efe1d58936176a0/db0d7d37f2039e29db5e4611a2a19392.png
  Error: vipspng: libpng read error
  vipspng: libpng read error
  vips2png: unable to write to buffer
```

Installing `libvips-dev`  fixed the issue; maybe we should note the native dependency in the readme? 
Although it's fairly easy to figure it out.

**Comment by chiamakaikeanyi** [comment]
Can I make a PR to address this?

**Comment by freiksenet** [comment]
@chiamakaikeanyi Of course, we'd really appreciate that :)

**Comment by LekoArts** [comment]
This should already be covered with the install of `build-essential`
https://www.gatsbyjs.org/docs/gatsby-on-linux/

**Comment by freiksenet** [comment]
Not everyone uses Ubuntu/Debian. It would be nice to have a list of packages required.

**Comment by chiamakaikeanyi** [comment]
@freiksenet, can you help review [the PR](https://github.com/gatsbyjs/gatsby/pull/12183)
