### ISSUE TITLE
Current state of i18n?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#12121]
Just a few general questions about building an i18n site with Gatsby?

What are the best possible solutions for creating an i18n site with Gatsby?

Is the core team working on something in this regard?

Are there any current tutorials that people in the community recommend?

I have been googling a bunch but I'm just getting more and more lost. Any curated guides and/or assistance on the matter would be most appreciated.

XD

**Comment by kbrgl** [comment]
You might find [this post on the Gatsby blog](https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/) useful.

**Comment by rchrdnsh** [comment]
hmmmm...reading through it...
is it still considered relevant, considering the posts age?
Do these concepts work well with V2?
