### ISSUE TITLE
Make github docs more user friendly

### ISSUE THREAD

**Issue by alexandrtovmach** [gatsbyjs/gatsby#12125]
## Summary

Currently we have a known issue with representation docs in normal GitHub markdown, because they are adopted to be parsed with a list of plugins for a website. And the most important thing, from my point of view is hidden names of files in codesnippets. That's really confusing everyone.

### Basic example

For example, please take a look on the markdown first:
https://github.com/gatsbyjs/gatsby/blame/master/docs/docs/adding-analytics.md#L39
![image](https://user-images.githubusercontent.com/28801003/53443909-6e412c80-3a15-11e9-8e9d-994364acd1fa.png)

Then here is an example how it looks on website (make attention to codesnippet title):
https://www.gatsbyjs.org/docs/adding-analytics/#using-gatsby-plugin-google-analytics
![image](https://user-images.githubusercontent.com/28801003/53443921-78fbc180-3a15-11e9-9d82-57963fa07c4d.png)

And the last one is how it looks on GitHub:
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/adding-analytics.md#using-gatsby-plugin-google-analytics
![image](https://user-images.githubusercontent.com/28801003/53443937-844eed00-3a15-11e9-8564-69b56c098972.png)

### Solution

After small research :male_detective:  I have an idea how we can solve that.

**We can use meta information blocks for filenames!** :fireworks: 

```
  ---
  gatsby-config.js
  ---

  ```js:title=gatsby-config.js
  module.exports = { ....
```

All happy:
- website markdown continue working in the same way
- GitHub show filenames for each codesnippet
- not hard to implement

In addition good to change configuration for `gatsby-transformer-remark` by adding custom options for [gray-matter-options](https://www.gatsbyjs.org/packages/gatsby-transformer-remark/#gray-matter-options), to parser use some [special delimiters](https://github.com/jonschlinkert/gray-matter#optionsdelimiters) for meta info. By default it use `---`:
```
---
gatsby-config.js
---
```
and on GitHub it looks like this:
![image](https://user-images.githubusercontent.com/28801003/53444713-8d40be00-3a17-11e9-9560-09f455f1f99f.png)

Not ideal, so we can change delimiter to `===` (actually I'm open to discuss about optimal delimiter):

```
===
gatsby-config.js
===
```
aaaand it looks like:
![image](https://user-images.githubusercontent.com/28801003/53444808-ca0cb500-3a17-11e9-9e1d-a26e55b43204.png)

### Motivation

Sure the most of users prefer using website documentation instead to looking for some file on GitHub.... but, it's still the case. Also I think that is having well structured documentation on GitHub it's "must have" in modern development (Am I wrong?) and we can start from small steps and then complete with that. From my point of view: _"If I can see formatted docs in free access anywhere, it should looks correct, and all things like missed filename seems like a bug for me"_

I'm ready to work on it, and as result create PR with config for parser and updated docs.

Thanks

**Comment by KyleAMathews** [comment]
We optimize the reading experience for the website. Markdown on GitHub simply can't express everything we'd like so we try to warn people away from reading there. Thanks for your thoughts!

https://github.com/gatsbyjs/gatsby/blob/master/docs/README.md

**Comment by alexandrtovmach** [comment]
@KyleAMathews Okay, thanks
