### ISSUE TITLE
The site is empty after going back

### ISSUE THREAD

**Issue by whs-dot-hk** [gatsbyjs/gatsby#12138]
## Description

Describe the issue that you're seeing.

I see nothing, the page is blank.

### Steps to reproduce
1) Visit https://www.gatsbyjs.org/showcase
2) Click on ReactJS
2) Click the purple visit site button
3) Go back

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

See the original page.

### Actual result

What happened.

Blank

### Environment

Run `npx gatsby info --clipboard` in your project directory and paste the output here.

**Comment by JacobBlomgren** [comment]
Interesting. I can reproduce on my machine. The console shows `TypeError: Cannot read property 'json' of undefined` and this https://github.com/gatsbyjs/gatsby/blob/3971ed4d6cc788b2fdc44d3b197bfe3fe68037ab/packages/gatsby/cache-dir/public-page-renderer-prod.js#L12 seems to be the line that breaks.

**Comment by whs-dot-hk** [comment]
Hi, my error is like this

![screenshot from 2019-02-27 23-07-37](https://user-images.githubusercontent.com/35202375/53500055-92b80a00-3ae4-11e9-8c63-46ecf36e75b0.png)

**Comment by t2ca** [comment]
Im getting the same error and the blank page.

```
TypeError: Cannot read property 'json' of undefined
    at c (public-page-renderer-prod.js:12)
```

**Comment by whs-dot-hk** [comment]
Looks like the findpage function is null

https://github.com/gatsbyjs/gatsby/blob/3971ed4d6cc788b2fdc44d3b197bfe3fe68037ab/packages/gatsby/cache-dir/loader.js#L163

but I can't fire a debugger to confirm

How to debug a built gatsbyjs site?

**Comment by yogeshkotadiya** [comment]
Not just `reactjs.org` site but all the sites.

* Go to [showcase](https://gatsbyjs.org/showcase) Page
* Click on the site title.
* Press Reload button.

**Comment by JacobBlomgren** [comment]
@whs-dot-hk Do you want to take a stab at this? Otherwise I can try.

**Comment by LaRuaNa** [comment]
@JacobBlomgren  I'd also like to give that one a try if you are not already on it :]

**Comment by whs-dot-hk** [comment]
@JacobBlomgren You can

**Comment by JacobBlomgren** [comment]
I think I know what causes this. The location state here https://github.com/gatsbyjs/gatsby/blob/master/www/src/templates/template-showcase-details.js#L78 says that it should be a modal, but since the page is refreshed, it doesn't have the data to render the /showcase background page here https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/layout.js#L71, which causes the crash described above. One solution would be show it without a modal, as it is when server side rendered, but I don't know how to detect the special case where the user has gone back/refreshed. It's kinda tricky. Don't know if it's worth solving @gatsbyjs/website ?

**Comment by whs-dot-hk** [comment]
Someone fixed it!

**Comment by wardpeet** [comment]
Can't seem to reproduce it anymore in chrome & firefox. I'm closing this, feel free to re-open if I'm wrong on this one.

**Comment by whs-dot-hk** [comment]
@wardpeet The bug is still here

**Comment by wardpeet** [comment]
@whs-dot-hk could you give me your browser info as it did work for me

**Comment by whs-dot-hk** [comment]
@wardpeet My chrome version is 73.0.3683.86.

**Comment by whs-dot-hk** [comment]
@wardpeet I have just post a PR.
