### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by GlynL** [gatsbyjs/gatsby#12135]
## Description
When running `npm install --save gatsby-plugin-styled-components` an npm error is received. This is on a brand new project installed used npx gatsby new 'project'

npm ERR! path C:\Users\glyn_\Documents\Coding\Projects\gatsby-portfolio\node_modules\@types\events\npm-shrinkwrap.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open
npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\glyn_\Documents\Coding\Projects\gatsby-portfolio\node_modules\@types\events\npm-shrinkwrap.json'npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Users\glyn_\Documents\Coding\Projects\gatsby-portfolio\node_modules\@types\events\npm-shrinkwrap.json']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, open 'C:\Users\glyn_\Documents\Coding\Projects\gatsby-portfolio\node_modules\@types\events\npm-shrinkwrap.json'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'open',
npm ERR!      path:
npm ERR!       'C:\\Users\\glyn_\\Documents\\Coding\\Projects\\gatsby-portfolio\\node_modules\\@types\\events\\npm-shrinkwrap.json' },
npm ERR!   isOperational: true,
npm ERR!   stack:
npm ERR!    "Error: EPERM: operation not permitted, open 'C:\\Users\\glyn_\\Documents\\Coding\\Projects\\gatsby-portfolio\\node_modules\\@types\\events\\npm-shrinkwrap.json'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path:
npm ERR!    'C:\\Users\\glyn_\\Documents\\Coding\\Projects\\gatsby-portfolio\\node_modules\\@types\\events\\npm-shrinkwrap.json',
npm ERR!   parent: '@types/glob' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\glyn_\AppData\Roaming\npm-cache\_logs\2019-02-27T07_06_14_170Z-debug.log

### Steps to reproduce

`npx gatsby new 'site'`
`npm install --save gatsby-plugin-styled-components`
or
`npm install --save gatsby-plugin-styled-components styled-components babel-plugin-styled-components`

### Expected result

package should install

### Actual result

npm error received.

### Environment

 System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Yarn: 1.10.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.0 - /c/Users/glyn_/AppData/Local/Programs/Python/Python37-32/python
  Browsers:
    Edge: 42.17134.1.0

error The system cannot find the path specified.

**Comment by JABedford** [comment]
This may be really basic of me, but you are changing into the right directory after creating the new project aren't you? 

`npx gatsby new 'site'`
`cd site`

I notice you have a project folder set up so I expect you have unless you have run the command within the folder and now have an extra subfolder? I only ask because I have made this mistake accidentally before and whilst I am on Mac a fairly similar error message is displayed.

**Comment by GlynL** [comment]
haha yes, that fixed it... now I feel silly. And here I was thinking I'd found the bug in my other repo. Back to the drawing board... thanks!

**Comment by JABedford** [comment]
Happens to us all buddy! Glad I could help.
