### ISSUE TITLE
Remove broken avatar image on gatsbygram example

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#12147]
## Description

The post detail page on https://gatsbygram.gatsbyjs.org is missing the avatar image. This should be updated to fix the image, or if that's not possible, remove the image completely.

### Getting started

The [Gatsbygram code can be found in the example directory of this repo](https://github.com/gatsbyjs/gatsby/tree/master/examples/gatsbygram). 

The avatar is rendered in [post-detail.js](https://github.com/gatsbyjs/gatsby/blob/master/examples/gatsbygram/src/components/post-detail.js#L30-L41) and the browser tests are in [home-page-spec.js](https://github.com/gatsbyjs/gatsby/blob/master/examples/gatsbygram/cypress/integration/home-page-spec.js). Run the browser tests (built with cypress.io) with `yarn run cy:run`.

For reference there's [a recent PR that fixes this for the gatsbygram homepage](https://github.com/gatsbyjs/gatsby/pull/12133).

### Steps to reproduce

- Visit https://gatsbygram.gatsbyjs.org
- Click on one of the posts
- See question mark next to the username

![screenshot 2019-02-27 at 13 47 27](https://user-images.githubusercontent.com/381801/53494783-6d9caa80-3a96-11e9-9e34-332cd920929a.png)

### Expected result

Either the correct image, or if that's not possible then remove the image.

### Actual result

It's trying to show an image that's not available.

### Environment

n/a

**Comment by DylanTackoor** [comment]
I'll take a stab at fixing this today 😄

**Comment by FrederikBolding** [comment]
As it didn't seem to have been looked at yet, and I was mocking about with example anyway, I fixed it in #12371
