### ISSUE TITLE
Grouping query results by "null"

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#12148]
When grouping query results with the `group` field, we internally use `lodash`'s `groupBy` which apparently treats `null` and `"null"` (the string) the same. This is unexpected.

```js
_.groupBy([{ field: null }, { field: "null" }], "field")
// { null: [ { field: null }, { field: 'null' } ] }
```

**Comment by freiksenet** [comment]
Amazing.
