### ISSUE TITLE
Gatsby Image types not consistent with nullable graphql types

### ISSUE THREAD

**Issue by deltaskelta** [gatsbyjs/gatsby#12149]
## Description

I believe that the types listed in gatsby-image [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/index.d.ts#L14) are not consistent with the schema, which is a nullable field. I am using the gatsby graphql schema to automatically generate types for all my queries and the required fields in gatsby image are in fact nullable. 

### Steps to reproduce

1. use a gatsby image fragment in a query
2. auto generate the type definitions with [apollo](https://github.com/apollographql/apollo-tooling)
3. try to use the generated type in a component with `<Img>` tag
4. see that the generated type gives an error because things like `aspectRatio` are `number | null`

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

I would expect the type definition reflected from the schema to be the same as the provided type defs

I can make the PR, but I'm not sure if changing the types here is the right approach, or maybe the schema needs to be changed?

**Comment by DSchau** [comment]
I'm not super-familiar with autogenerated types, but the interface for prpos that `GatsbyImage` accepts do seem valid. If you pass a null `fluid` prop, that is indeed invalid and we wouldn't be able to handle that.

What would you propose changes here?

**Comment by humphreybc** [comment]
Also stuck with this one. Here's my relevant code. You can see that the generated types have things like `aspectRatio: number | null` and `srcSet: string | null` but GatsbyImage expects simply `aspectRatio: number` and doesn't handle the null case. The workaround is to map over the generated FluidObject and handle all the null cases, but that's not so great.

## Page query

```
export const pageQuery = graphql`
  query IndexImageQuery {
    fileName: file(relativePath: { eq: "./images/project-data.png" }) {
      childImageSharp {
        fluid(maxWidth: 960, maxHeight: 600) {
          ...GatsbyImageSharpFluid
        }
      }
    }
  }
`;
```

## Generated types

```
export interface IndexImageQuery_fileName_childImageSharp_fluid {
  __typename: "ImageSharpFluid";
  base64: string | null;
  aspectRatio: number | null;
  src: string | null;
  srcSet: string | null;
  sizes: string | null;
}

export interface IndexImageQuery_fileName_childImageSharp {
  __typename: "ImageSharp";
  fluid: IndexImageQuery_fileName_childImageSharp_fluid | null;
}

export interface IndexImageQuery_fileName {
  __typename: "File";
  /**
   * The child of this node of type imageSharp
   */
  childImageSharp: IndexImageQuery_fileName_childImageSharp | null;
}

export interface IndexImageQuery {
  fileName: IndexImageQuery_fileName | null;
}
```

## GatbsyImage types

```
import * as React from "react"

interface FixedObject {
  width: number
  height: number
  src: string
  srcSet: string
  base64?: string
  tracedSVG?: string
  srcWebp?: string
  srcSetWebp?: string
}

interface FluidObject {
  aspectRatio: number
  src: string
  srcSet: string
  sizes: string
  base64?: string
  tracedSVG?: string
  srcWebp?: string
  srcSetWebp?: string
}

interface GatsbyImageProps {
  resolutions?: FixedObject
  sizes?: FluidObject
  fixed?: FixedObject
  fluid?: FluidObject
  fadeIn?: boolean
  title?: string
  alt?: string
  className?: string | object
  critical?: boolean
  style?: object
  imgStyle?: object
  placeholderStyle?: object
  backgroundColor?: string | boolean
  onLoad?: () => void
  onStartLoad?: (param: { wasCached: boolean }) => void
  onError?: (event: any) => void
  Tag?: string
}

export default class GatsbyImage extends React.Component<
  GatsbyImageProps,
  any
> {}
```

**Comment by deltaskelta** [comment]
@DSchau I would expect that whatever Gatsby returns from the query to be a valid object for Img. If Gatsby can possibly return null for the image query `fluid` prop then there will be uncaught build error when it does, regardless of using Typescript or not. Is that correct?

If that is the case, and it is also the case that `Img` fails without the `fluid` prop then I would think Gatsby should return a non nullable type for the non nullable parts of the query, and return an error otherwise.

**Comment by humphreybc** [comment]
FYI if it's helpful for anyone, here's my temporary workaround:

```tsx
import GatsbyImage from "gatsby-image";
import React from "react";

export interface FluidImage {
  __typename: "ImageSharpFluid";
  aspectRatio: number | null;
  base64: string | null;
  sizes: string | null;
  src: string | null;
  srcSet: string | null;
}

interface Props {
  className?: string;
  fluid?: FluidImage | null;
}

export const GatsbyImageWrapper: React.FC<Props> = ({ className, fluid: f }) =>
  f != null ? (
    <GatsbyImage
      className={className}
      fluid={{
        aspectRatio: f.aspectRatio !== null ? f.aspectRatio : 1,
        base64: f.base64 !== null ? f.base64 : "",
        sizes: f.sizes !== null ? f.sizes : "",
        src: f.src !== null ? f.src : "",
        srcSet: f.srcSet !== null ? f.srcSet : ""
      }}
    />
  ) : null;
```

**Comment by KyleAMathews** [comment]
Gatsby's types are nullable as we can't guarantee that data will be available when queries are run. gatsby-image doesn't have the same contract so isn't nullable.
