### ISSUE TITLE
gatsby-plugin-offline & gatsby-plugin-styled-components css is not injected

### ISSUE THREAD

**Issue by tcerdaITBA** [gatsbyjs/gatsby#12145]
## Description

CSS class is missing in some components when including `gatsby-plugin-offline` during deployment. During development it works as expected.

The missing CSS corresponds to the `Tab` styled component in  `src/components/Header.jsx`. The `div` tag renders but without the corresponding class. On the first load it may render fine, but on refresh the header CSS styles are missing. Navigating to another section of the page makes the header CSS reappear.

See https://survivalrecipes-pja8azdht.now.sh/en/ for an example.

### Steps to reproduce

1. Clone https://github.com/tcerdaITBA/SurvivalRecipes

2. Include `gatsby-plugin-offline` in `gatsby-config.js`

3. Deploy. Can be done by running `now`

4. Navigate to deployment website.

5. Refresh page

### Expected result

All CSS classes should be included on deployment.

### Actual result

The header CSS class is missing on deployment.

### Environment

```
  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.5.0 - ~/.nvm/versions/node/v11.5.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.5.0/bin/npm
  Languages:
    Python: 3.6.4 - /usr/local/bin/python
  Browsers:
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.18 => 2.1.18 
    gatsby-image: ^2.0.20 => 2.0.25 
    gatsby-plugin-favicon: ^3.1.5 => 3.1.5 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12 
    gatsby-plugin-offline: ^2.0.24 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.7 => 3.0.7 
    gatsby-plugin-sharp: ^2.0.22 => 2.0.22 
    gatsby-plugin-styled-components: ^3.0.6 => 3.0.6 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-transformer-remark: ^2.2.0 => 2.2.0 
    gatsby-transformer-sharp: ^2.1.14 => 2.1.14 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

### Additional Infomation
Same issue occurred deploying with Netlify as well, so it should not be a Zeit Now issue.

**Comment by wardpeet** [comment]
It seems like an issue with `gatsby-plugin-styled-components`. If I comment it out everything works as expected. I'll check the plugin how they do SSR & rehydration as I have some experience with styled-components.

**Comment by polarathene** [comment]
Try this in `gatsby-node.js`:

```JS
exports.onCreateBabelConfig = ({ stage, actions }, pluginOptions) => {
  const ssr = stage === `build-html` || stage === `build-javascript`

  actions.setBabelPlugin({
    name: `babel-plugin-styled-components`,
    stage,
    options: { ...pluginOptions, ssr },
  })
}
```

I don't recall the source of it(I think it's from a prior Github issue in this repo), it fixed an issue I had with styled-components, but I also recall something about this snippet (should) no longer being required

**Comment by tcerdaITBA** [comment]
Thanks @polarathene; unfortunately the bug persists.

**Comment by nickreese** [comment]
Having this exact issue as well. @tcerdaITBA did you find a solution?

**Comment by tcerdaITBA** [comment]
No, unfortunately I have not been able to come up with a solution. I was thinking of maybe migrating to emotion as a workaround.

**Comment by nickreese** [comment]
@tcerdaltba — Mine was caused by another plugin competing for the gastby-ssr replace header tags/node... Or some name like that. (I don't have it in front of me)

Look in that file and try disabling other plugins until gatsby build gives you css in the head.

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v3 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

[reproduction]: https://gatsby.dev/reproduction
