### ISSUE TITLE
Upgrading to Gatsby 2.1 breaks multiple stylesheet output (via custom webpack config)

### ISSUE THREAD

**Issue by gswirrl** [gatsbyjs/gatsby#12151]
I have code in `gatsby-node.js` that patches the WebPack config to output multiple css files - 

```
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

exports.onCreateWebpackConfig = ({
  actions,
  stage,
  getConfig
}) => {
  actions.setWebpackConfig({
    plugins: [new MiniCssExtractPlugin({ })],
  })
  if (stage.includes('javascript')) {
    let config = getConfig()
    config.entry["theme-a"] = './src/css/entry-points/theme-a.css'
    config.entry["theme-b"] = './src/css/entry-points/theme-b.css'
    actions.replaceWebpackConfig(config)
  }
}
```

Under gatsby `2.0.17` this builds two css files in `/public`, `theme-a.css` and `theme-b.css`. 
Under gatsby `2.1.n` this builds one file, `styles.css`.

If I just log out the config to the console, it's the same in each...

Is this expected? If so, any ideas how I could get the old behaviour back? Any help where I could start looking for what's changed?

**Comment by krismorf** [comment]
Hi @gswirrl see here the related PR #11800 and issue #12018

**Comment by gswirrl** [comment]
Hi @krismorf ah - understood. Is there a way I can work around it?

**Comment by gswirrl** [comment]
Minimal demo of the issue: https://github.com/gswirrl/gatsby-multiple-stylesheet

**Comment by gswirrl** [comment]
FIXED?

Problem is the new
 https://github.com/gatsbyjs/gatsby/blob/0a3705f5a0e0d2ac417cd2db012e92c66c16f8c3/packages/gatsby/src/utils/webpack.config.js#L399

My hacky solution (in `gatsby-node.js`) is to just stomp `config.optimization.splitChunks.cacheGroups.styles`

```
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

exports.onCreateWebpackConfig = ({
  actions,
  stage,
  getConfig
}) => {
  actions.setWebpackConfig({
    plugins: [new MiniCssExtractPlugin({

    })],
  })
  if (stage.includes('javascript')) {
    let config = getConfig()
    config.entry["theme-a"] = './src/css/theme-a.css'
    config.entry["theme-b"] = './src/css/theme-b.css'

    // override default output to styles.css
    config.optimization.splitChunks.cacheGroups.styles = {}

    actions.replaceWebpackConfig(config)
  }
}
```

Seems to work? May have unintended drawbacks! :-)

**Comment by gswirrl** [comment]
I think this is still fresh! Sorry.
