### ISSUE TITLE
Support custom GraphQL fragments inside gatsby-node.js

### ISSUE THREAD

**Issue by baobabKoodaa** [gatsbyjs/gatsby#12155]
How can I use custom GraphQL fragments inside gatsby-node? [Here](https://github.com/gatsbyjs/gatsby/issues/12092) is more information on what I've tried so far, but it would perhaps be better if someone just provided a working example. [The example in the docs](https://www.gatsbyjs.org/docs/using-fragments/) doesn't work when applied to gatsby-node (or I'm doing something wrong).

**Comment by LekoArts** [comment]
You can use normal string interpolation:
https://github.com/LekoArts/portfolio/blob/master/gatsby-node.js#L108

**Comment by baobabKoodaa** [comment]
The problem with string interpolation is that it can't be used inside page queries or static queries. I thought fragments were supposed to solve the issue of repetition (and dependencies) inside GraphQL queries?

**Comment by wardpeet** [comment]
Is it possible to give us some more information what you tried and create a reproduction so we can easily test this out.

**Comment by baobabKoodaa** [comment]
@wardpeet Here is more information about various things I tried: https://github.com/gatsbyjs/gatsby/issues/12092

**Comment by realgt** [comment]
i  just ran into the same issue trying to refactor my growing gatsby-node query into fragments stored elsewhere. hope theres a fix for this

**Comment by baobabKoodaa** [comment]
@realgt If you only need those fragments inside a gatsby-node query, then string interpolation is not a bad solution. I actually ran into this issue again yesterday, but I need to use the fragments in static queries as well, which means I can't use string interpolation and now I have duplicated code :(

**Comment by realgt** [comment]
@baobabKoodaa string interpolation just seems like a dirty solution, the graphql equivalent of sql injection

**Comment by seidtgeist** [comment]
Chiming in here to report that I expected my GraphQL fragments to be available in `gatsby-node.js`.

**Comment by KyleAMathews** [comment]
It would make sense to support your fragments inside gatsby-node.js as well. This would require some refactoring as we don't collect all the fragments until we run page/static queries later in bootstrap. But we should be able to move that earlier and use the Relay Compiler to "expand" queries with fragments into the full query when they're passed into the graphql function.

/cc @freiksenet

**Comment by sibelius** [comment]
check this https://github.com/n1ru4l/relay-compiler-repl to understand how relay compiler transforms graphql queries and fragments

**Comment by Barsonax** [comment]
Any news on this?

**Comment by pilniczek** [comment]
I would appreciate more info as well. Thanks! :)

**Comment by addisonschultz** [comment]
Here to also say this would be awesome! I use the same query in `gatsby-node` as in other parts of my app, which can be long and I'd rather not repeat them 😬

**Comment by JonasJuss** [comment]
I would love this functionality as well!

**Comment by digital-flowers** [comment]
Here you go, how to write cross env fragments  ;)

```javascript
import { promisify } from "util";
import GatsbyParser from "gatsby/dist/query/file-parser";
import fs from "fs";
import path from "path";

/**
 * Collect all graphql queries from a directory
 * @param dirname
 * @returns {Promise<*>}
 */
export const collectGQLQueries = async dirname => {
  const parser = new GatsbyParser();
  const files = await promisify(fs.readdir)(dirname);
  const result = await parser.parseFiles(
    files.map(file => path.join(dirname, file))
  );
  return result
    .filter(item => item.doc && item.doc.kind === "Document")
    .map(doc => doc.text)
    .join("\n");
};
```

**How to use:**
1- add all your Fragments as queries inside the same directory:

![image](https://user-images.githubusercontent.com/5216291/80109661-52e99700-85b0-11ea-80df-e601ac106ad5.png)

2- make sure you use graphql to query them 

![image](https://user-images.githubusercontent.com/5216291/80109954-ba074b80-85b0-11ea-9e59-a2ade2f9e2ef.png)

3- Use the `collectGQLQueries` util to collect all fragments and just inject them inside `gatsby-node`

```javascript
 // fragments
  const fragments = await collectGQLQueries(
     path.resolve(__dirname, "fragments")
  );
  // data
  const { data, errors } = await graphql(`
    ${fragments}
    {
      allContentfulPage {
        nodes {
          id
          contentful_id
          // ...
        }
     }
   }`);
```

**Comment by LpmRaven** [comment]
Any news on this?

**Comment by hasparus** [comment]
I had to change @digital-flowers' function a bit to pick fragments by name, since an unused fragment fails a query.

[Here's the gist](https://gist.github.com/hasparus/8a65896f4ca98aa6bd54c44ebdf5d9e5).

```tsx
  const fragments = await collectGraphQLFragments(
    resolve(__dirname, "src/features"),
    ["TweetDiscussEditLinksDataOnMdx"]
  );
```
