### ISSUE TITLE
WordPress Source - Flexible Content layouts ignored by graphql when not used

### ISSUE THREAD

**Issue by HurricaneInteractive** [gatsbyjs/gatsby#12164]
## Summary
I've setup ~15 different layouts in WordPress using the Flexible Content feature in ACF. Because there are so many it means that some are not used by the content author. When gatsby pulls in the content and generates the graphql data structure, it will create the structure based on the layouts that have been used. When I set up my queries to pull in all the layouts I get an error because some layouts are queried that aren't present in the graphql structure (because they are not being used by the author). Here is an example of the query.

```
acf {
    content_layouts_page {
        __typename
        ... on WordPressAcf_pullout_lead_with_list {
             ...plwlFragment
        }
        ... on WordPressAcf_client_list {
            ...clFragment
        }
        ... on WordPressAcf_titled_list_with_item_description {
             ...tlwidFragment
        }
        ...more layouts defined
    }
}
```

### Question
How can I set up my graphql queries that it will be "future proof " for when the author decides to use an unused layout.

## Potential solution

This is a solution that I have thought of but I am not sure if it is possible. If I can just query the `__typename`, which will return an array. Then dynamically construct the graphql query based on the present layouts.

```
// __typename array = ['WordPressAcf_pullout_lead_with_list', 'on WordPressAcf_client_list']
let queryString = ''
__typename.forEach(layout => {
    switch (layout) {
        case 'WordPressAcf_pullout_lead_with_list':
            queryString += '...on WordPressAcf_pullout_lead_with_list { ...plwlFragment }'
            break;
        ....
    }
})

// Use queryString in graphql query
```

Again, not sure if this is possible, but it would solve a lot of problems for sure.

**Comment by pieh** [comment]
Hey, it's limitation of current graphql schema construction.

Right now what you can is to create "dummy" posts that have all possible layouts:
![screenshot 2019-02-28 at 14 07 50](https://user-images.githubusercontent.com/419821/53568452-588d4d80-3b62-11e9-813e-2d5514bdca7e.png)

And when you query for data, use filter to remove "dummy" posts from results:
![screenshot 2019-02-28 at 14 08 16](https://user-images.githubusercontent.com/419821/53568490-6e9b0e00-3b62-11e9-8ca4-75bc28517968.png)

In this example you can see that query doesn't error when using `WordPressAcf_textarea` even if no "real" post is using that (dummy post is using that, but it's filtered out)

**Comment by HurricaneInteractive** [comment]
@pieh So I'll just need to filter out the dummy pages in `gatsby-node.js` to make sure that I don't create a publically available page but the graphql queries will still have a reference to those layouts?

**Comment by pieh** [comment]
@HurricaneInteractive Yeah, in `gatsby-node` is one place, but also if you have any  queries for `allWordpress(Page|Post)` in any page component query or static query

**Comment by HurricaneInteractive** [comment]
Thanks you @pieh got it working now so 👍
