### ISSUE TITLE
Persist state with useReducer hook

### ISSUE THREAD

**Issue by Hypothesis-github** [gatsbyjs/gatsby#12188]
As we know the new hooks are officially out and everyone is trying to figure out the future of React.
I come from a Mobx background myself and I want to switch the new useReducer and useContext hooks to take care of my state. However, I cannot carry the state through the route, There are some ways which I found in the documents that Redux state and Mobx state can be carried out, but the new hooks are missing. Can someone suggest me a way to pass my state through the route in gatsby ?

**Comment by universse** [comment]
You can investigate using gatsby-plugin-layout (https://www.gatsbyjs.org/packages/gatsby-plugin-layout/) to persist state across route.

**Comment by universse** [comment]
For example
```
const SomeContext = createContext()

export default function Layout ({ children }) {
  const [someState, dispatch] = useReducer(someReducer, someInitialValue)

  return (
    <SomeContext.Provider value={someState}>
        {children}
    </SomeContext.Provider>
  )
}
```

Then in your component 
```
  const someState = useContext(SomeContext)
```

**Comment by Hypothesis-github** [comment]
> For example
> 
> src/layouts/index.js (default)
> 
> ```
> export const SomeContext = createContext()
> 
> export default function Layout ({ children }) {
>   const [someState, dispatch] = useReducer(someReducer, someInitialValue)
> 
>   return (
>     <SomeContext.Provider value={someState}>
>         {children}
>     </SomeContext.Provider>
>   )
> }
> ```
> Then in your component
> 
> ```
>   const someState = useContext(SomeContext)
> ```

You are a life saver, mad props.

**Comment by makhnovskiy** [comment]
@Hypothesis-github How would one useContext within a class component? Getting Invalid Hook Call error.

**Comment by universse** [comment]
@makhnovskiy React hooks can only be used with functional components. For class components, you can use either [contextType](https://reactjs.org/docs/context.html#classcontexttype) or [Context.Consumer](https://reactjs.org/docs/context.html#contextconsumer).
