### ISSUE TITLE
[1.0] GraphQL debugging help

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1218]
* Detect "$variable not found" graphql errors and print out more description about what this means as well as printing out the actual context that was received as well as which plugin created the page.
* Always push people to Graph*i*QL — say basically, go to this URL and paste in the above query and debug things there.

**Comment by 0x80** [comment]
In my experience, when my graphql queries have mistakes, the GraphiQL server doesn't start because the process exists early. It would be super helpful if Gatsby caught any errors related to user queries, and allows the graphiql interface to run for debugging.

**Comment by KyleAMathews** [comment]
Yes, this should be the first fix, make GraphQL problems warnings not errors. If a query can't run, it's not that big of deal. Yeah, lemme get this (small) change in today and do another beta release.

**Comment by KyleAMathews** [comment]
Not tested and probably will break with other errors but all I have time for right now and a good foundation for further improvements.

In any case, doesn't error out now :-)

<img width="1047" alt="screen shot 2017-06-21 at 10 13 04 am" src="https://user-images.githubusercontent.com/71047/27397229-77696506-566a-11e7-9368-a4ea72473eba.png">

**Comment by craig-coles** [comment]
my graphql starts fine, but i can't get anything back from my query,
`import React from 'react';
import * as PropTypes from "prop-types";
import Header from '../components/Header/Header';
import Footer from '../components/Footer/Footer';

const propTypes = {
  data: PropTypes.object.isRequired,
}
const main = ({ node }) =>{
    console.log(node);

    return (
        <div>
            <Header />
            <div>This is a page</div>
            <Footer />
        </div>
    )
}

export default main;

export const pageQuery = graphql`
  query PageQuery {
    allContentfulRecipe {
      edges {
        node {
          title
        }
      }
    }
  }
``

**Comment by KyleAMathews** [comment]
A lot of progress has been made. More to go but let's close this as it's out-dated.
