### ISSUE TITLE
[gatsby-plugin-feed] Api for creating multiple dynamic feeds based off of a query

### ISSUE THREAD

**Issue by jsanchez034** [gatsbyjs/gatsby#12184]
## Summary

When creating rss feeds with `gatsby-plugin-feed` it would be great to have the ability to create multiple feeds from dynamic data coming from a single GraphQL query. In other words to create numerous feeds at build time where you wouldn't know up front ( without GraphQL query data ) how many you need.

### Basic example
Bellow I'm proposing adding a new config property to a feed object called `mapToFeedFiles`. From it the user would return an array of feed objects that would support all current feed properties minus `serialize` and instead support a property called `serializedItems` which basically would be similar to what `serialize` property function normally would return.

```
{
  resolve : 'gatsby-plugin-feed',
  options : {
    query : `
      {
        site {
          siteMetadata {
            title
            description
            site_url
          }
        }
      }
    `,
    feeds : [
      {
        query : `{
          allBlogCategory {
            edges {
              node {
                name
                fields {
                  categorySlug
                }
                blog___post {
                  title
                  publishedOn
                  author {
                    name
                  }
                  body {
                    html
                  }
                  fields {
                    postSlug
                  }
                }
              }
            }
          }
        }`,
        mapToFeedFiles : ({ query: { site, allContentfulBlogCategory } }) => {
          return allContentfulBlogCategory.edges.map(({ node }) => {
            const { name, fields, blog___post : categoryBlogPosts } = node;
            return {
              title             : name,
              output            : `/category/${fields.categorySlug}/rss.xml`,
              serializedItems   : categoryBlogPosts.map(() => mapPostToRSSFeedItem(node))
            };
          });
        }
      }
    ]
  }
}
```

### Motivation

The motivation behind this is say you have a blog with posts that each have a main category assigned to them. Furthermore the categories are created by content creators in your headless CMS system such a Contentful. Each category has its own page on your blog site listing the posts under that category and you want each page to have a rss feed. The above api addition would allow for creating a rss feed per category.

If given the ok with the above api from the maintainers of the plugin, I can implement the new feature as well. I just wanted some feedback on the proposal before creating a PR. Thanks for the consideration!

**Comment by jsanchez034** [comment]
Hello @mikefowler and @secretfader I see you guys have contributed to `gatsby-plugin-feed`. I also see there was a similar proposal earlier in issue https://github.com/gatsbyjs/gatsby/issues/3489. I would love to get some feedback on this new proposal.

**Comment by secretfader** [comment]
While I love seeing people take an interest in RSS (and syndication feeds in general), I've largely stepped away from Gatsby development and no longer have a controlling interest in `gatsby-plugin-feed`. That said, while cases like yours (@jsanchez034) are something I always wanted support for, but proved difficult to execute against.

@DSchau has proposed a few changes to how options are parsed and validated in #12085, which may open the door to supporting new methods for ingesting configuration and creating feeds. Still, the general trend (at least among plugins in the core repo) seems to be bending towards the most common use cases, expanding functionality carefully if needed.

It's probably worth considering what it would take to write this feature once the PR covering option validation lands. But it could also be better addressed by a plugin you write to handle a specific use case.

**Comment by DSchau** [comment]
@secretfader couldn't have said it better myself.

The work I'm doing in that PR does make it slightly easier to add new features (in a way that the user is at least aware if they're being used incorrectly, wrong options passed).

@jsanchez034 However - this seems like it could lead to some fairly significant bloat in a plugin that is already _sorta_ confusing to use.

I don't ever want to discourage someone from contributing, because I completely understand the use case for the plugin you describe, but maybe this makes most sense as a fork or something that is maintained outside of the Gatsby repo?

In some sense, maintaining a repository is about making sure you're focusing on the right things and balancing the right trade offs. Introducing features that may not be generally applicable (but valuable!) introduce a maintenance burden on maintainers.

What do you think @jsanchez034? Want to make it clear that this is a discussion not a decision. Happy to be persuaded!

**Comment by jsanchez034** [comment]
Thanks for the feedback @DSchau and @secretfader! Yeah I think the use case might be too specific like you guys described. I will create a separate plugin for my use case.

**Comment by DSchau** [comment]
@jsanchez034 awesome - would you mind keeping us in the loop as to when you publish? We're also happy to provide any feedback along the way!

**Comment by jsanchez034** [comment]
Awesome will do 👍  Thanks for the support!

**Comment by cedricdelpoux** [comment]
@jsanchez034 Did you publish your plugin? I can't find it

**Comment by jsanchez034** [comment]
> @jsanchez034 Did you publish your plugin? I can't find it

Hi! Never got around to making the plugin. I ended up not needing the multi feed feature

**Comment by cedricdelpoux** [comment]
Ok thank you for your feedback.

**Comment by codefull** [comment]
> > @jsanchez034 Did you publish your plugin? I can't find it
> 
> Hi! Never got around to making the plugin. I ended up not needing the multi feed feature

Hi! Did you just dropped multifeed feature or did you just workaround  a solution. Please could you let me know, I'm in the same scenario.

**Comment by jsanchez034** [comment]
Yeah ended dropping the multi-feed feature
