### ISSUE TITLE
Revert instructing people to use npx and npm scripts

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#12195]
We recently started suggesting people use `npx` and `npm scripts` more which I think was a mistake.

There are some cli commands that we use constantly — `git`, `npm`, `ls`, `cd`, etc. These are all global commands that we want accessible at all times.

People often suggest using npm scripts for a few reasons:

- it ensures that you're using the locally installed version (perhaps you want to use a different version than a globally installed version)
- the perception that installing more globals clutters things

Neither apply to Gatsby. The Gatsby CLI version doesn't matter — when you run `gatsby develop` or `gatsby build` or any of the other site commands, it just looks for the locally installed gatsby package (and fails if it can't find one) and runs the command for you.

`npx` is an interesting idea for simplifying using seldomly run global commands as it skips the installation step for using a global + ensures that the global is always up to date.

But Gatsby is _not_ a seldomly used command — people use Gatsby all day long and it's very reasonable to expect that they'll install the gatsby-cli package once.

Also because people do type Gatsby commands so often, it's not very pleasant to need to type 4 extra characters every time. Imagine if you had to type `npx npm` or `npx git` or `npx ls`, etc.

Things to revert:

- [ ] GitHub issue templates
- [ ] getting started doc
- [ ] recipes
- [ ] tutorial
- [x] other random places in the docs where things where switched over

**Comment by DSchau** [comment]
For extra context, and a handy diff of what changed, #11556 contains most of the changes that will be necessary here to revert.

**Comment by JABedford** [comment]
I'm happy to sweep the tutorial if anyone hasn't started already.

**Comment by ryancharris** [comment]
@JABedford Did you jump on this already? Was going to make this my first contribution, but don't want to duplicate work 🙏

**Comment by DSchau** [comment]
@JABedford @ryancharris thanks to both of you!

If it makes sense--perhaps @JABedford could focus on the tutorial, and then @ryancharris perhaps you could focus on the other changes that #11556 introduced?

That way you won't double up on work.

**Comment by ryancharris** [comment]
@JABedford @DSchau Works for me!

**Comment by JABedford** [comment]
Yes that sounds good to me too @DSchau and @ryancharris 👍

**Comment by KyleAMathews** [comment]
Something else I noticed is that @jlengstorf needs to reshoot his video on https://www.gatsbyjs.org/docs/quick-start

**Comment by DSchau** [comment]
Let's keep this open until #12273 lands.

**Comment by muescha** [comment]
@KyleAMathews 
here https://www.gatsbyjs.org/docs/quick-start
are still the `npm xxx` commands ...

**Comment by DSchau** [comment]
@muescha thanks!

Would you want to PR this change? File is [here](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/quick-start.md)

**Comment by muescha** [comment]
done 

PS:
but there much more places when i run a [search for npm run](https://github.com/gatsbyjs/gatsby/search?p=2&q=npm+run&unscoped_q=npm+run) over the full repo

**Comment by TheBear44** [comment]
This docs https://www.gatsbyjs.org/docs/gatsby-cli/#note-on-globally-installed-executables stills encourage to use `npm run develop`
