### ISSUE TITLE
Docs: add guide on how to enable comments

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#12209]
[Gatsby offers a number of great guides](https://www.gatsbyjs.org/docs/adding-website-functionality) on how to add various kinds of functionality such as search, analytics, forms, etc. One feature that is extremely common for blogs but not yet covered is how to enable comments.

There's a [discussion on this topic](https://spectrum.chat/gatsby-js/general/whats-the-best-way-to-make-commenting-system~0c7e3f0f-8737-4948-9c52-0d20dfe37a05?m=MTUxNjM2MjE1NTY1MA==) in a 2017 Spectrum chat that lists several options:
- [Disqus](https://disqus.com) [[mention](https://spectrum.chat/gatsby-js/general/whats-the-best-way-to-make-commenting-system~0c7e3f0f-8737-4948-9c52-0d20dfe37a05?m=MTUxMTIzMDE0NjY2MQ==)]
- [Staticman](https://staticman.net) [[mention](https://spectrum.chat/gatsby-js/general/whats-the-best-way-to-make-commenting-system~0c7e3f0f-8737-4948-9c52-0d20dfe37a05?m=MTUzNDkxODUxMDk4OA==)]
- [Facebook comments](https://www.npmjs.com/package/react-facebook) [[mention](https://spectrum.chat/gatsby-js/general/whats-the-best-way-to-make-commenting-system~0c7e3f0f-8737-4948-9c52-0d20dfe37a05?m=MTU0MTEwNTQyNDI1MA==)]
- [JustComments](https://just-comments.com) [[mention](https://spectrum.chat/gatsby-js/general/whats-the-best-way-to-make-commenting-system~0c7e3f0f-8737-4948-9c52-0d20dfe37a05?m=MTU0MTQ0MzcxMTgxMQ==)]
- [TalkYard](https://www.talkyard.io) [[mention](https://spectrum.chat/gatsby-js/general/whats-the-best-way-to-make-commenting-system~0c7e3f0f-8737-4948-9c52-0d20dfe37a05?m=MTUxNjMzMzM5MTU5NA==)]

It would be great if Gatsby could provide an official and more up-to-date guide on the pros and cons of each service (and perhaps others I'm unaware of) as well as how to implement some of them.

**Comment by sidharthachatterjee** [comment]
@janosh This seems like a great idea! Thank you for the detailed issue.

**Comment by m-allanson** [comment]
I agree, this sounds like a good idea 👍 

This could start out as an _Adding Comments_ page in [the section you pointed out](https://www.gatsbyjs.org/docs/adding-website-functionality).

**Comment by calpa** [comment]
Just for more information, [Gitalk](https://github.com/gitalk/gitalk) is another useful tools for comment.

**Comment by janosh** [comment]
@sidharthachatterjee @m-allanson Just submitted a PR for the guide on how to implement Disqus.

**Comment by ryaholm** [comment]
I implemented Github Issues as comments on my gatsby blog. Here's the javascript file:
https://github.com/HolmSchool/holm-school-site/blob/master/src/js/github-comments.js
Then on my blogpost template I add at the bottom:
```html
<div id="gh-comments">
          <h6>COMMENTS</h6>
          <div id="gh-comments-list"></div>
          <div style={{textAlign: 'center'}}><button className={css`border-radius: 3px;border: 1px solid purple;color: purple;font-family:"Courier New", Courier;vertical-align: middle;`} onClick={() => ghc.DoGithubComments(post.frontmatter.ghissue, ++page)} id="gh-load-comments">Load more comments</button></div>
        </div>
```
as found here: https://github.com/HolmSchool/holm-school-site/blob/master/src/templates/blog-post.js

Example comments on a live Gatsby page:
https://holm.school/bootstrap-your-computer-science-career/

Let me know if I need to explain anything, or possibly write a blog post or something like that.

**Comment by janosh** [comment]
@ryaholm That's cool. You might want to submit a PR that extends the docs to cover your method once the initial guide at #12458 has been merged.
