### ISSUE TITLE
Add LivingDocs magazine example to starter library

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#12205]
There's a great new magazine code example -- we should add this to the starter library!

Code:
https://github.com/livingdocsIO/gatsby-magazine-example

Site:
https://magazine-example.livingdocs.io/politics-4942

**Comment by LaRuaNa** [comment]
On it :]

**Comment by plhnk** [comment]
PR submitted #12267

**Comment by plhnk** [comment]
ah shoot...I opened this last night and didn't refresh the tab before submitting the PR 😭

**Comment by LaRuaNa** [comment]
Ehm.. Ok

**Comment by sidharthachatterjee** [comment]
Sorry about that @LaRuaNa 

Would love to see more contributions from you in the future!
