### ISSUE TITLE
[gatsby-image] Image resolution too low if image overflows page

### ISSUE THREAD

**Issue by erikhoj** [gatsbyjs/gatsby#12217]
## Summary
If a gatsby-image overflows the page, firefox will pick a src with a lower resolution. Like so:

![Illustration of the issue in Firefox](https://i.imgur.com/a7RyQGX.png)

Does anyone know how to solve this issue?

## Relevant information
It seems to only happen in Firefox. In Chrome, it picks the following size:

![What happens in Chrome](https://i.imgur.com/8hqyiP2.png)

### Environment (if relevant)

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.0 - C:\Users\Mindfox-Erik\AppData\Local\Programs\Python\Python37-32\python.EXE
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.119 => 2.0.119
    gatsby-image: ^2.0.30 => 2.0.30
    gatsby-plugin-material-ui: ^1.2.4 => 1.2.4
    gatsby-plugin-netlify-cms: ^3.0.12 => 3.0.12
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-sass: ^2.0.10 => 2.0.10
    gatsby-plugin-sharp: ^2.0.12 => 2.0.12
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-images: ^3.0.1 => 3.0.1
    gatsby-remark-relative-images: ^0.2.1 => 0.2.1
    gatsby-source-filesystem: ^2.0.8 => 2.0.8
    gatsby-transformer-remark: ^2.1.12 => 2.1.12
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8

### File contents (if changed)

`gatsby-config.js`: https://pastebin.com/4kAjtgc9
`package.json`: https://pastebin.com/zUDYvE1i
`gatsby-node.js`: https://pastebin.com/tUVvC2r7
`gatsby-browser.js`: https://pastebin.com/gA2c8gid
`gatsby-ssr.js`: https://pastebin.com/EjRhmcSQ

**Comment by DSchau** [comment]
@erikhoj thanks for reporting this!

This sounds like an issue that we won't really be _able_ to fix. We can only do so much as far as normalizing behavior for browsers, and using standards like `srcset` generally help us a ton here. So _if_ and when Firefox fixes this apparent bug, merely by using gatsby-image you'll get this nice functionality for free.

As far as the underlying bug--I'm not really sure what we could do here. This seems like something that is fairly out of our control.

Do you feel differently? Happy to discuss this further!

Also a [reproduction](https://gatsby.dev/reproduction) would be very helpful, as well, just to validate the underlying bug!
