### ISSUE TITLE
Dev server started before all nodes are created

### ISSUE THREAD

**Issue by cbetta** [gatsbyjs/gatsby#12210]
## Description

I am fetching some remote files and then parsing their content. I am fetching the remote files using `sourceNodes` and  `createRemoteFileNode` from `gatsby-source-filesystem`. All of this works fine.

Where things go wrong is where I then listen to `onCreateNode` to extract content from these fetched files. It seems that the development server starts before all `createNode` calls are finished! As a result, when I go to GraphiQL none of the nodes seem to be available.

### Steps to reproduce

Assuming you have some `File` nodes with large HTML content in them, the following code runs fine but fails to make the new nodes available to GraphiQL.

```js
let id = 0

exports.onCreateNode = async ({
  node,
  createNodeId,
  createContentDigest,
  loadNodeContent,
  actions
}) => {
  let { createNode } = actions

  if (node.internal.type === 'File') {
    let content = await loadNodeContent(node)
    let items = content.split(/\>/, 20)

    items.forEach(sample => {
      let nodeId = createNodeId(`test-${id}`)
  
      let data = { id, sample }
  
      let newNode = Object.assign({}, data, {
        id: nodeId,
        parent: node.id,
        children: [],
        internal: {
          type: `Test`,
          content: JSON.stringify(data),
          contentDigest: createContentDigest(data),
        }
      })
    
      createNode(newNode)
      id++
    })
  }  
}
```

For me, this sometimes works with an empty cache, but break when the dev server is restarted with a cache in place.

### Expected result

Start the dev server: `npm run develop`

I'd then expect this query

```
{
  allTest {
    totalCount
  }
}
```

to result in something like this

```json
{
  "data": {
    "allTest": {
      "totalCount": 370
    }
  }
}
```

### Actual result

Instead I get

```json
{
  "errors": [
    {
      "message": "Cannot query field \"allTest\" on type \"Query\".",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

### Temporary workaround

For now I have had to insert a timeout at the end of `onCreateNode` to wait for all nodes to load before the dev server continues to boot.

```js
      ... ....

      createNode(newNode)
      id++
    })
  }  

  return new Promise((resolve) => {
    setTimeout(resolve, 1000)
  })

```

### Environment

```

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.7.0 - /usr/local/bin/node
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 3.7.0 - /Users/cbetta/.pyenv/shims/python
  Browsers:
    Chrome: 72.0.3626.119
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.119 => 2.1.17 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-plugin-force-trailing-slashes: ^1.0.4 => 1.0.4 
    gatsby-plugin-manifest: ^2.0.17 => 2.0.19 
    gatsby-plugin-netlify: ^2.0.10 => 2.0.11 
    gatsby-plugin-netlify-cache: ^1.0.0 => 1.0.0 
    gatsby-plugin-offline: ^2.0.23 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-sharp: ^2.0.20 => 2.0.22 
    gatsby-plugin-subfont: ^1.0.3 => 1.0.3 
    gatsby-plugin-typography: ^2.2.7 => 2.2.7 
    gatsby-source-apiserver: ^2.1.1 => 2.1.1 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-source-json: ^1.0.0 => 1.0.0 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.14 
  npmGlobalPackages: {}
```

**Comment by jonniebigodes** [comment]
@cbetta looking at your code it looks like you're missing something. You should return something, namely a promise. More on that [here](https://www.gatsbyjs.org/docs/node-apis/)

**Comment by cbetta** [comment]
@jonniebigodes not quite, the async is just there because otherwise the `await` won't work.

I figured out the real issue though: I wasn't waiting for `createRemoteFileNode` to complete. I wrapped those into a nice await and returned a promise and now it all works fine. Closing this issue.
