### ISSUE TITLE
GraphQL queries are executed even if not using GraphQL

### ISSUE THREAD

**Issue by asilgag** [gatsbyjs/gatsby#12216]
## Description

I am creating 10k pages from a set of 10k json files, and I'm doing it without using GraphQL at any moment. I just read their contents from the filesystem and call `createPage` passing the JSON data in the context.

I'm not using any GraphQL query in my project, but when I run `gatsby build`, I see the following line in the logs:

`success run graphql queries — 5.223 s — 10000/10000 1914.57 queries/second`

For each page I create, there is a graphql query that gets executed, even if I'm not using graphql at all.

Just to be sure that it wasn't my fault, I tested this repo (https://github.com/jlengstorf/gatsby-with-unstructured-data) which is referenced in Gatsby documentation as an example of how to work without GraphQL. The same happens on that repo: one GraphQL query is executed for each page.

### More info

Trying to find the root cause, I think that the problem is with `runQueriesForPathnames`. A query is created for each `pathname`, and an object is pushed to the `queue` (it looks like this step is needed to pass the context to each page):

```
pageQueries.forEach(id => {
    const page = pages.get(id);
    if (page) {
      didNotQueueItems = false;
      queue.push({
        id: page.path,
        jsonName: page.jsonName,
        query: store.getState().components.get(page.componentPath).query, <--- THIS IS EMPTY
        isPage: true,
        componentPath: page.componentPath,
        context: Object.assign({}, page, page.context) <--- THIS IS THE CONTEXT
      });
    }
  });
```
Even if I comment the query property, queries are executed. And if I don't push the object to the queue, page creation doesn't work because no context is passed to the page.

### Steps to reproduce
```
git clone https://github.com/jlengstorf/gatsby-with-unstructured-data.git
cd gatsby-with-unstructured-data/
npm install
gatsby build
```
### Expected result

Not executing any GraphQL query.

### Actual result

GraphQL queries are executed, one per page:

```
...
success run graphql queries — 0.057 s — 10/10 180.74 queries/second
...
```

### Environment
  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 11.9.0 - ~/.nvm/versions/node/v11.9.0/bin/node
    Yarn: 1.13.0 - /usr/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v11.9.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: 65.0.1
  npmPackages:
    gatsby: ^2.0.0 => 2.1.19 
  npmGlobalPackages:
    gatsby-cli: 2.4.12

**Comment by LekoArts** [comment]
cc @gatsbyjs/core

**Comment by KyleAMathews** [comment]
It's not actually running any queries. It's a bit confusing but every page is handled the same way whether it had a query or not as we need to write out its data file. The assumption is that most pages do have a query. We could make the label more verbose to be clear it's also just writing out pageContext on some pages.

**Comment by asilgag** [comment]
Ok, thats fine, no problem if it's just a naming issue... thanks @KyleAMathews

**Comment by DSchau** [comment]
Let's close this out. Sorry for the confusion here--but that seems to have been alleviated!

If we can help further--please feel free to reply and we'll re-open and continue the discussion. Thanks for using Gatsby 💜
