### ISSUE TITLE
AWS Amplify build fails

### ISSUE THREAD

**Issue by samscarsella** [gatsbyjs/gatsby#12222]
## Description

Similar to the issues here involving Netlify, attempting to build on AWS Amplify throws similar errors and build fails.

### Steps to reproduce

Build started with https://github.com/gatsbyjs/gatsby-starter-default
AWS setup follows this tutorial https://www.gatsbyjs.org/blog/2018-08-24-gatsby-aws-hosting/.

**gatsby-config.js**: https://pastebin.com/t6C8L1S9
**AWS logs**: https://pastebin.com/HbNTcfiB

Based off of other issues I've seen, I've already ensured that all imports and filename cases match, removed yarn.lock from the repo and upgrading gatsby-related packages to their latest versions.

### Expected result

Build should succeed.

### Actual result

Build fails.

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.7.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: 64.0
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.0-rc.28 => 2.1.19 
    gatsby-image: ^2.0.0-rc.4 => 2.0.30 
    gatsby-plugin-manifest: ^2.0.2-rc.1 => 2.0.20 
    gatsby-plugin-offline: ^2.0.0-rc.9 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.7 
    gatsby-plugin-s3: ^0.2.4 => 0.2.4 
    gatsby-plugin-sass: ^2.0.0-rc.2 => 2.0.10 
    gatsby-plugin-sharp: ^2.0.0-rc.7 => 2.0.23 
    gatsby-source-filesystem: ^2.0.1-rc.6 => 2.0.23 
    gatsby-transformer-sharp: ^2.1.1-rc.3 => 2.1.15

**Comment by DSchau** [comment]
@samscarsella could you provide a [reproduction](https://gatsby.dev/reproduction)?

This generally looks like an issue with (as you note) casing. I've seen `git` be incredibly confusing and finicky with changing the case on files. Generally I've had to do `git mv <options>` (e.g. [this StackOverflow post](https://stackoverflow.com/a/24979063)).

It _could_ also just be a relative path issue, but if it builds locally, I'm more inclined to think it's casing!
