### ISSUE TITLE
gatsby develop can only serve 5 pages at a time

### ISSUE THREAD

**Issue by jeffrafter** [gatsbyjs/gatsby#12225]
## Description

When running `gatsby develop` everything works perfectly and fast for the first 5 pages I open (in multiple tabs). Subsequent pages opened in new tabs hang indefinitely. When I close one of the previously opened tabs the last pages load immediately. I've tried to see if this is related to similar issues including (https://github.com/gatsbyjs/gatsby/issues/12143, https://github.com/gatsbyjs/gatsby/issues/11747 https://github.com/gatsbyjs/gatsby/pull/10257 and https://github.com/gatsbyjs/gatsby/issues/11727) but it seems different. 

![gatsby-closing-tabs](https://user-images.githubusercontent.com/4064/53659141-9c8a5c00-3c0f-11e9-8ce9-f58779694a0b.gif)

### Steps to reproduce

Start `gatsby develop`, open a bunch of tabs simultaneously.

### Expected result

All of them load, HMR is ready.

### Actual result

Only the first four load, the others hang.

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.3 - ~/.nvm/versions/node/v10.13.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: 65.0.1
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.85 => 2.1.17 
    gatsby-image: ^2.0.30 => 2.0.30 
    gatsby-plugin-canonical-urls: ^2.0.5 => 2.0.10 
    gatsby-plugin-feed: ^2.0.13 => 2.0.13 
    gatsby-plugin-google-analytics: ^2.0.14 => 2.0.14 
    gatsby-plugin-manifest: ^2.0.19 => 2.0.19 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.6 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.22 
    gatsby-plugin-styled-components: ^3.0.5 => 3.0.6 
    gatsby-plugin-typescript: ^2.0.0 => 2.0.9 
    gatsby-remark-autolink-headers: ^2.0.14 => 2.0.14 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.9 
    gatsby-remark-images: ^2.0.1 => 2.0.6 
    gatsby-remark-prismjs: ^3.0.0 => 3.2.4 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.9 
    gatsby-remark-smartypants: ^2.0.5 => 2.0.8 
    gatsby-source-filesystem: ^2.0.1 => 2.0.22 
    gatsby-transformer-json: ^2.1.1 => 2.1.8 
    gatsby-transformer-remark: ^2.1.3 => 2.2.6 
    gatsby-transformer-sharp: ^2.1.1 => 2.1.14 
  npmGlobalPackages:
    gatsby: 2.1.4
```

**Comment by adamclifford** [comment]
@jeffrafter This is a limitation of the browser you are using.

When you are developing with GatsbyJS there is a connection to the GraphQL endpoint open and all of the pages queries are then rendered based on the live queries, this is how getting live data to the pages you are editing works in the back ground.

However, each browser has a limited set of connections that it uses to connect to the same end point. In chrome, this limit is 5, when you exceed that limit, chrome restricts the connection until one has been freed up and can connect.

I hope this helps.

**Comment by DSchau** [comment]
@adamclifford whoa! Today I learned!

Could you provide a source on that? Would be helpful to document for posterity.

In any case--this doesn't seem like an issue we can resolve within Gatsby, and we're not doing anything outside the ordinary (apart from opening up a web socket) that would cause any weirdness here!

Going to close as answered--but please reply if we missed something or if the above is off-base.

Thanks for using Gatsby! 💜

**Comment by adamclifford** [comment]
@DSchau the HTTL/1.1 specification stipulates 2 connections as a limit, as can be read [here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.1.4).
Most modern browsers now allow more than that, as the official limit has hindered the effectiveness of said browsers, an [RF7230](https://tools.ietf.org/html/rfc7230#section-6.4) replaced the previous limit, and told browser vendors to not be greedy.

This is a form  of protection against DDoS attacks.

I cant find an official list of available limits, but [Pushtechnology](https://docs.pushtechnology.com/cloud/latest/manual/html/designguide/solution/support/connection_limitations.html) has a list of the current ones.

**Comment by jeffrafter** [comment]
@adamclifford thanks for those links, this is super helpful; I never realized that limit was _per browser_ not _per tab_! 

> When you are developing with GatsbyJS there is a connection to the GraphQL endpoint open and all of the pages queries are then rendered based on the live queries, this is how getting live data to the pages you are editing works in the back ground.

Is this just for HMR? Do you know if there is a config/fallback strategy for polling instead of open connections?

**Comment by DSchau** [comment]
> Is this just for HMR

Yep! We build out the data from the local GraphQL schema, so there isn't a trace of that in the production code.

> Do you know if there is a config/fallback strategy for polling instead of open connections?

Not really. Generally - is this something you do often? 5 open tabs with the same content seems to be a little overkill, but maybe there's a use case we're missing here with our current strategy!

**Comment by jeffrafter** [comment]
@DSchau it isn't a great use case... I just keep a lot of tabs open and forget some on a desktop here or there. Then I open a new tab and it is empty and I wait and then 10-15 seconds later realize "Oh, I must have 5 other tabs open somewhere" and go hunt them down through my mess of desktops and tabs and disorganization. Often it is different pages with different styling and I want to see the impact of a new header or something across them. So I have to open/close open/close.

My understanding is that this is not a problem in HTTP/2 because of multiplexing. I wonder if there is a way to move to HTTP/2 or some other connection mechanism that is more forgiving of disorganized people like myself 🤹‍♂️

**Comment by KyleAMathews** [comment]
Huh, this is an unfortunate bug. We could change from websockets to long-polling to solve this. It shouldn't have much effect on performance.

**Comment by jeffrafter** [comment]
Actually, I spent some time digging into this... if we upgrade the development experience to `SPDY` instead of `HTTP` the problem is resolved. Unfortunately, doing this (effectively) requires running the local development environment behind TLS.  

I changed [this line](https://github.com/gatsbyjs/gatsby/blob/66ebe958bb004d99e859b664b295d510d8999678/packages/gatsby/src/commands/develop.js#L199) to: 

```
let server = require(`spdy`).createServer(
      {
        key: program.ssl.key,
        cert: program.ssl.cert,
      },
      app,
    )
```

And commented out the subsequent SSL block. Then I ran `gatsby develop --https` and everything worked perfectly. It works and you can simultaneously open as many pages as you want.

Note, I tried to run SPDY in non-TLS (this does not work):

```javascript
 let server = require(`spdy`).createServer(
      {
        spdy: {
          plain: true,
          ssl: false,
        },
      },
      app,
    )
```

Running in plain mode with no SSL correctly serves pages with no `https` but in this mode Chrome falls back to normal HTTP/1 rules and the concurrent connection limit kicks in.

**Comment by jeffrafter** [comment]
@DSchau would you consider re-opening this, considering #12302

**Comment by DSchau** [comment]
Of course! Consider it done!

**Comment by jlengstorf** [comment]
This [showed up in Sizzy](https://twitter.com/thekitze/status/1144328801603768322). cc @kitze

**Comment by kitze** [comment]
Yup. It'd be cool if at least I can change something in Sizzy so it works.

**Comment by jlengstorf** [comment]
It looks like there's a workaround in Electron (`--ignore-connections-limit`) that's been [implemented for Sizzy](https://twitter.com/thekitze/status/1154763673832964096) — are we able to do that by default in Gatsby so the workaround isn't required?

**Comment by kitze** [comment]
@jlengstorf I think this has to be implemented on the browser side. Firefox has this setting in `about:config`, but Chrome only supports it via flag. Unless Gatsby changes from SSE to WebSockets I'm afraid this won't be possible.

https://tools.ietf.org/html/rfc6202#section-5.1

**Comment by coreyward** [comment]
Could Gatsby listen at multiple ports or hostnames (is the limit per-port or per-hostname)? 

If so, we could potentially monitor the total number of connections per browser (doesn't have to be perfect: a user-agent heuristic probably works fine) and automatically add another port/hostname to the pool when we get close to the limit.

Alternately, there are approaches to allow for sharing data across tabs which would limit the need for multiple websocket connections, but this is enough of an edge case that I don't know that it would merit the complications that such an approach would bring.

**Comment by tu4mo** [comment]
Many component libraries show examples in iframes, so they work in isolation of the documentation page. I guess there isn't any workaround to enable opening multiple Gatsby pages in iframes inside one page?

**Comment by varma59** [comment]
opening in an updated browser

**Comment by varma59** [comment]
Chnging ssl and hosting provider

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!

**Comment by limichange** [comment]
I'm using the latest version of GATSBY (4.15.2) and the problem still exists, this issue needs to be reopened.

**Comment by FMCorz** [comment]
In Firefox, increasing the config value `network.http.max-persistent-connections-per-server` (from about:config) seems to help.
