### ISSUE TITLE
[RFC] gatsby-plugin-manifest query for site data

### ISSUE THREAD

**Issue by ijones16** [gatsbyjs/gatsby#12227]
## Summary

Add a `query` option for the plugin to query `site.metaData` instead of passing `options`.

Then, `onPostBootstrap`, where can, if a query is present, query site data and set the manifest up that way.

I think [`gatsby-plugin-feed`](https://github.com/gatsbyjs/gatsby/tree/51be9e633d247e5948681073cb290d7192b7e66a/packages/gatsby-plugin-feed) is a good example of this. 

### Basic example

```js
{
      resolve: 'gatsby-plugin-manifest',
      options: {
        query: `
          {
            site {
              siteMetadata {
                title: name
                description
                // etc...
              }
            }
          }
        `,
      },
    },
```

### Motivation

This would allow theme creators to add `gatsby-plugin-manifest` to their theme. Having to pass static `options` to this plugin restricts this plugin to consumer gatsby projects.

**Comment by DSchau** [comment]
We don't really need an RFC for this, but appreciate you labeling it as such!

This is a feature request, and how you've designed it makes a fair amount of sense. onPostBootstrap should have access to the `graphql` function, so you could query (if supplied!), grab the data, and then inject it however you'd like.

However - I wonder what the benefit of doing this at the theme level is compared to just having this live in user land (where it can be configured very cleanly and obviously with the established plugin options)?

Plugin use cases are still being hardened and established, but this _seems_ like something that should be left to the consuming "parent" package that implements the theme at first glance.

What do you think?

**Comment by ijones16** [comment]
Hey @DSchau! I think those are fair points. It does seem to make a lot of sense to keep this plugin in userland. I can't think of any other real benefits maybe besides consistency that querying site data would provide.

**Comment by ChristopherBiscardi** [comment]
themes accept a function gatsby-config, which can accept options to pass into any plugin's options. As such I don't think we need theme-specific support for this to work, as it would already work if the theme-author set it up to.

```js
module.exports = ({ manifestOptions }) => ({
  plugins: [{ resolve: `gatsby-plugin-manifest`, options: manifestOptions }]
});
```

**Comment by ijones16** [comment]
Oh, I didn't realize that. Thanks @ChristopherBiscardi!
