### ISSUE TITLE
Potential Node Mismatch: Any reason why Dockerfile is using node v8.x.x, whereas package.json is node v6.11.5?

### ISSUE THREAD

**Issue by anthonytranDev** [gatsbyjs/gatsby#12229]
## Summary
Came across the 2 versions here, wanted to know the reason for using mismatched versions of node.

### package.json
![screenshot 2019-03-01 at 20 33 58](https://user-images.githubusercontent.com/26009168/53664848-ac329080-3c61-11e9-97bc-ff83201ef238.png)

### Dockerfile
![screenshot 2019-03-01 at 20 35 19](https://user-images.githubusercontent.com/26009168/53664916-e6039700-3c61-11e9-87b6-f9a81fdc3448.png)

## Relevant information
**My Guesses as to why:**
- **Perfomances Boost** - https://hackernoon.com/upgrading-from-node-6-to-node-8-a-real-world-performance-comparison-3dfe1fbc92a3
- **Additional Features and Improved Security** - https://blog.risingstack.com/important-features-fixes-node-js-version-8/

**Comment by KyleAMathews** [comment]
Node 6 is just the minimum version we support. We actually suggest using node 10 now (the latest stable release) so the Dockerfile could be updated now.

**Comment by KyleAMathews** [comment]
And yeah, newer versions of node are faster, have more features, have fewer bugs, etc

**Comment by anthonytranDev** [comment]
Thanks @KyleAMathews I assumed that would the case
