### ISSUE TITLE
gatsbyjs.org documentation Discord link is broken

### ISSUE THREAD

**Issue by spacenate** [gatsbyjs/gatsby#12234]
## Description

The Discord link in the gatsbyjs.org tutorial header navigation is broken.

### Steps to reproduce

Go to gatsbyjs.org, click Docs, then click the Discord icon in the header.

### Expected result

The link should work.

### Actual result

The link did not work (unable to connect to server at gatsby.dev)

### Environment

The Internet.

**Comment by lannonbr** [comment]
@spacenate can you possibly try again? The link is https://gatsby.dev/discord for me and it resolves to the invite link for the discord.

**Comment by ryancharris** [comment]
@spacenate @lannonbr Just tried myself and the link seems to work properly. Link goes to `https://gatsby.dev/discord` as expected.

**Comment by sidharthachatterjee** [comment]
https://gatsby.dev/discord works for me as well 

Closing this for now but please feel free to reopen if you're still seeing this @spacenate

**Comment by spacenate** [comment]
Oh, how embarrassing! I was able to access that domain from other devices as well (the issue only existed on my laptop). 

Clearing my DNS cache resolved the problem for me (on Mac OS: `sudo killall -HUP mDNSResponder`). Sorry about that 🙈

**Comment by DSchau** [comment]
For anyone else coming here, it's possible you also have some custom hosts mapping or resolvers. See [this issue](https://github.com/gatsbyjs/gatsby/issues/12385) for more info!

**Comment by harobed** [comment]
@sidharthachatterjee https://gatsby.dev/discord is down for me
