### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/canvas in node_modules/canvas/lib

### ISSUE THREAD

**Issue by danielbh** [gatsbyjs/gatsby#1223]
Hello, are you able to please help me with this gatsby build issue? Thanks in advance!

When I import and build [trianglify](https://www.npmjs.com/package/trianglify) I get the error output below. The site still runs in "gatsby develop" mode. If you would like to repeat the issue on your machine do the following...

1) git clone git@github.com:danielbh/danielhollcraft.com.git
2) cd danielhollcraft.com
3) cd ui/src
4) yarn install / npm install
5) gatsby build 

Please see below for diagnostic information.

**Gatsby version**: 0.12.39
**Node version**: v6.11.0
**OS**: MAC OS 10.12.5

**gatsby-node.js**: not used

[package.json](https://github.com/danielbh/danielhollcraft.com/blob/master/ui/src/package.json)

**gatsby-browser.js**

```import ReactGA from 'react-ga';
import { config } from 'config'; // eslint-disable-line

if (process.env.NODE_ENV === 'production') {
  ReactGA.initialize(config.googleAnalyticsId);

  exports.onRouteUpdate = (state, page, pages) => { // eslint-disable-line
    ReactGA.set({page: state.pathname});
    ReactGA.pageview(state.pathname);
  };
}
```

**Error Output**
```
Generating CSS
Generating Static HTML
Failed at generating HTML

/src/node_modules/gatsby/dist/bin/cli.js:42
      throw err;
      ^
Error: ./~/canvas/lib/bindings.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/canvas in /src/node_modules/canvas/lib
resolve file
  node_modules/canvas/build/Release/canvas doesn't exist
  node_modules/canvas/build/Release/canvas.js doesn't exist
  node_modules/canvas/build/Release/canvas.jsx doesn't exist
  node_modules/canvas/build/Release/canvas.cjsx doesn't exist
  node_modules/canvas/build/Release/canvas.coffee doesn't exist
  node_modules/canvas/build/Release/canvas.ts doesn't exist
  node_modules/canvas/build/Release/canvas.tsx doesn't exist
  node_modules/canvas/build/Release/canvas.json doesn't exist
  node_modules/canvas/build/Release/canvas.less doesn't exist
  node_modules/canvas/build/Release/canvas.css doesn't exist
  node_modules/canvas/build/Release/canvas.scss doesn't exist
  node_modules/canvas/build/Release/canvas.sass doesn't exist
  node_modules/canvas/build/Release/canvas.toml doesn't exist
  node_modules/canvas/build/Release/canvas.yml doesn't exist
  node_modules/canvas/build/Release/canvas.yaml doesn't exist
resolve directory
 node_modules/canvas/build/Release/canvas doesn't exist (directory default file)
 node_modules/canvas/build/Release/canvas/package.json doesn't exist (directory description file)
[node_modules/canvas/build/Release/canvas]
[node_modules/canvas/build/Release/canvas.js]
[node_modules/canvas/build/Release/canvas.jsx]
[node_modules/canvas/build/Release/canvas.cjsx]
[node_modules/canvas/build/Release/canvas.coffee]
[node_modules/canvas/build/Release/canvas.ts]
[node_modules/canvas/build/Release/canvas.tsx]
[node_modules/canvas/build/Release/canvas.json]
[node_modules/canvas/build/Release/canvas.less]
[node_modules/canvas/build/Release/canvas.css]
[node_modules/canvas/build/Release/canvas.scss]
[node_modules/canvas/build/Release/canvas.sass]
[node_modules/canvas/build/Release/canvas.toml]
[node_modules/canvas/build/Release/canvas.yml]
[node_modules/canvas/build/Release/canvas.yaml]
 @ ./~/canvas/lib/bindings.js 3:17-51
```

Thanks again for any help you could offer!

Daniel

**Comment by KyleAMathews** [comment]
First thing to check is if there's a file at `/src/node_modules/canvas/build/Release/canvas`

**Comment by KyleAMathews** [comment]
Second is to google around for people trying to use this library with webpack as it might have some trickery necessary to get it working.

**Comment by danielbh** [comment]
So you don't think this is gatbsy related then?

**Comment by KyleAMathews** [comment]
Highly unlikely. It's perhaps related to Gatsby webpack config but our
config is for the most part pretty vanilla.

**Comment by danielbh** [comment]
Ok thanks. I'll investigate further.

**Comment by danielbh** [comment]
I think it's a webpack issue like you said. I'm going to close this for now. Thanks.

**Comment by danielbh** [comment]
I could be wrong, but I think I need to exclude the canvas module using https://webpack.js.org/configuration/externals/ How would I do that with Gatsby? I've been trying to do it in the gatsby-nod.js file unsuccessfully...

```javascript
exports.modifyWebpackConfig = function(config, stage) {
    // edit loaders here
  if(stage === 'build-html') {
    config.externals = ['canvas'];
  }
  return config
};
```

Thanks!!

**Comment by danielbh** [comment]
By the way here is a fellow that fixed the issue doing this with a fabric.js https://github.com/kangax/fabric.js/issues/3115

**Comment by danielbh** [comment]
On inspection of the webpack config object I discovered I was modifying the wrong property. Unfortunately it looks like I shouldn't be modifying it as it is a private variable. I'll use it as a workaround unless you have a better suggestion. Thanks!

```javascript
exports.modifyWebpackConfig = function(config, stage) {

  if(stage === "build-html") {
    config._config.externals ='canvas';
  }

  return config
};
```
