### ISSUE TITLE
[docs] Reorganize plugins section

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#12230]
## Summary

I want to split the current "plugins" category in the docs into two categories and rename a number of docs as well as create some new docs. Thought of this idea through interviewing plugin authors and also while working on #12228, which implements a very small number of these proposed changes.

### Basic example

Here are what the current plugin docs look like:
<img width="270" alt="screen shot 2019-03-01 at 1 23 54 pm" src="https://user-images.githubusercontent.com/32467162/53667263-5d670580-3c25-11e9-9848-845127cd6eda.png">

I'm proposing to break these docs down into tinier chunks, one task or question each, like so:

Using plugins (overview) (involves renaming current overview doc)
What is a Plugin? (involves creating a new doc, repurposing content for it)
How do Plugins Work? (involves renaming Plugin Authoring doc and editing it)
Finding a Gatsby Plugin (don't need this doc yet, might someday)
Using Plugins FAQ (involves creating a new doc)

Creating plugins (overview) (involves creating a new overview doc)
Creating a Source Plugin (involves merging this PR, which renames a doc)
Creating a Transformer Plugin (involves merging this PR, which renames a doc)
Publishing a Plugin to npm (involves creating a very short doc that pulls info from other docs)
Submitting to Gatsby Plugin Library (already exists in Contributing and we could link to it from docs also)
Authoring a Plugin FAQ (involves creating a new doc)

### Motivation

It's been tricky for some plugin authors to find answers to their questions, and breaking existing docs into smaller chunks so the doc titles and URLs are discoverable could help with finding things while browsing the site. We're trying to surface answers to common questions and can link to them whenever people have the questions on Twitter, Github, Spectrum, Discord, etc.

Questions:
- Is this way of splitting one category into two categories helpful? It seems like these docs could belong in both categories:
> What is a Plugin? (involves creating a new doc, repurposing content for it)
> How do Plugins Work? (involves renaming Plugin Authoring doc and editing it)

- does this belong in an RFC?
- Who would be willing to help write the FAQ docs?

Disclaimer: I don't think these docs will necessarily solve all plugin authoring problems; I think they will mostly help the core team have a more complete reference so they can send people links with answers to their questions more quickly.

**Comment by marcysutton** [comment]
Hey @shannonbux, this all sounds great to me! What's next on the list to do?

**Comment by shannonbux** [comment]
Hi @marcysutton! I think it would probably involve two phases:

#1 renaming current docs and creating a few new ones:
- Using plugins (overview) (involves renaming current overview doc)
- What is a Plugin? (involves creating a new doc, repurposing content for it)
- How do Plugins Work? (involves renaming Plugin Authoring doc and editing it)
- Finding a Gatsby Plugin (don't need this doc yet, might someday)
- Using Plugins FAQ (involves creating a new doc)

#2 creating new section under Contributing part of the nav
- Creating plugins (overview) (involves creating a new overview doc)
- Creating a Source Plugin (involves merging this PR, which renames a doc)
- Creating a Transformer Plugin (involves merging this PR, which renames a doc)
- Publishing a Plugin to npm (involves creating a very short doc that pulls info from other docs)
- Submitting to Gatsby Plugin Library (already exists in Contributing and we could link to it from docs also)
- Authoring a Plugin FAQ (involves creating a new doc)
