### ISSUE TITLE
gatsby plugin sass stopped compiling 

### ISSUE THREAD

**Issue by Angel-SG** [gatsbyjs/gatsby#12248]
## Description

I'm building a site with Gatsby and I originally used the hello-world starter pack. Everything worked perfect until without apparent reason the plugins sass stopped working. If I'm not importing the global.scss to my index.js then everything works as expected. Anyone can help please?

### Steps to reproduce

This is the error on my terminal: 

error  in ./src/styles/global.scss

Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import 'home';
| @import 'fontawesome';
| @import 'skills';

 @ ./src/pages/index.js 17:0-31
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

✖ ｢wdm｣:
ERROR in ./src/styles/global.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import 'home';
| @import 'fontawesome';
| @import 'skills';
 @ ./src/pages/index.js 17:0-31
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi event-source-polyfill ./node_modules/webpack-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.

### Expected result

What should happen?

### Actual result

What happened.

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-3330S CPU @ 2.70GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 11.10.0 - /usr/local/bin/node
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.119
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.19 => 2.1.19 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-typography: ^2.2.7 => 2.2.7

**Comment by Flavien-Pensato** [comment]
I encounter the same bug. Can you explain, how did you solved it ?

**Comment by Angel-SG** [comment]
check your CSS files, it might be a syntax error in there that's stoping the compiler.

**Comment by Flavien-Pensato** [comment]
It was a forgotten ; ^^
