### ISSUE TITLE
New lines disappear from code-blocks using gatsby-remark-prismjs

### ISSUE THREAD

**Issue by phenax** [gatsbyjs/gatsby#12255]
## Description
I am using gatsby-mdx with gatsby-remark-prismjs. The syntax highlighting works this way but for some reason, the entire code appears in one line. Im not entirely sure if this issue should be a part of this repo or the gatsby-mdx repo.

What I wrote
![screenshot from 2019-03-03 12-56-23](https://user-images.githubusercontent.com/11407672/53692357-56bac880-3db4-11e9-87b1-2d9ac0b4a507.png)

What I got
![screenshot from 2019-03-03 12-55-57](https://user-images.githubusercontent.com/11407672/53692360-6508e480-3db4-11e9-9f2f-84549593168e.png)

### Steps to reproduce
My config for mdx and remark looks something like this.
```js
  {
      resolve: 'gatsby-mdx',
      options: {
        extensions: ['.mdx', '.md'],
        frontmatter: true,
        defaultLayout: require.resolve('./src/blog-layout.tsx'),
        gatsbyRemarkPlugins: [
          {
            resolve: 'gatsby-remark-prismjs',
            options: {
              inlineCodeMarker: '=>',
              showLineNumbers: true,
            },
          },
        ],
      },
    },
```

Here's the project I'm facing this issue in -> https://github.com/phenax/phenax.github.io

### Expected result
Expected the newlines to be maintained as coded in the codeblock

### Actual result
Everything gets rendered in a single line

### Environment
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 65.0.1
  npmPackages:
    gatsby: ^2.1.16 => 2.1.16 
    gatsby-mdx: ^0.4.0 => 0.4.0 
    gatsby-plugin-copy: ^0.0.1 => 0.0.1 
    gatsby-plugin-google-analytics: ^2.0.15 => 2.0.15 
    gatsby-plugin-prefetch-google-fonts: ^1.4.0 => 1.4.0 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-sharp: ^2.0.22 => 2.0.22 
    gatsby-plugin-typescript: ^2.0.9 => 2.0.9 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-remark-prismjs: ^3.2.4 => 3.2.4 
    gatsby-source-filesystem: ^2.0.22 => 2.0.22 
    gatsby-transformer-json: ^2.1.8 => 2.1.8 
    gatsby-transformer-sharp: ^2.1.14 => 2.1.14 
```

**Comment by DSchau** [comment]
@phenax looks like you solved this with [this commit](https://github.com/phenax/phenax.github.io/commit/64775eaaa506ce3086c52ab1b82394be1d587c07)?

If this is not the case, please feel free to reply and we'll re-open this promptly.

Thanks!
