### ISSUE TITLE
Babel Plugin Styled Components must be a dev dependency?

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#12271]
When you visit https://www.gatsbyjs.org/packages/gatsby-plugin-styled-components/, I think `babel-plugin-styled-components` must be a dev dependency, not sure tho?

Right now it's

```sh
npm install --save gatsby-plugin-styled-components styled-components babel-plugin-styled-components
```

I think it must be changed to

```sh
npm install --save gatsby-plugin-styled-components styled-components
npm install --save-dev babel-plugin-styled-components
```

Correct?

**Comment by KyleAMathews** [comment]
Some dependencies that other tools consider dev should be normal dependencies with Gatsby as e.g. on a CI server, often dev dependencies won't be installed which will break your gatsby build.

**Comment by deadcoder0904** [comment]
Gotcha!

This is a naive example but suppose if many such dependencies are installed then won't it increase the build size?

Which dependencies are supposed to be normal vs dev? How would I differentiate?
