### ISSUE TITLE
Scoping folder structure in GraphQL Queries

### ISSUE THREAD

**Issue by nextlevelshit** [gatsbyjs/gatsby#12278]
## Summary

The plan is to enrich all nodes with a certain parameter, namely its parent folder. For better understanding, I've implemented all important parts of my code so far. At the end I will explain my main problem in more detail.

**Folder structure:**

    work
    ├── drawing
    │   ├── drawing-1
    │   │   ├── image.1.jpg
    │   │   ├── image.2.jpg
    │   │   ├── image.3.jpg
    │   │   ├── image.jpg
    │   │   └── index.md
    │   └── index.md
    ├── sculpture
    │   ├── gaehnschreier
    │   │   ├── image.1.JPG
    │   │   ├── image.2.jpg
    │   │   ├── image.3.JPEG
    │   │   ├── image.4.png
    │   │   ├── image.PNG
    │   │   └── index.md
    │   └── index.md
    └── watercolor
        ├── index.md
        ├── portrait-1
        │   ├── image.jpg
        │   └── index.md
        └── portrait-2
            ├── image.jpg
            └── index.md

*This is a simple hierarchy of a portfolio. `work` is the root folder and has different categories e.g. `drawing`. Inside you'll find folders, which represent a specific piece. Each piece has a `index.md` with detailed information about that piece and multiple images (jpeg, png etc.).* 

---

**gatsby-config.js:**

    // ...
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'work',
        path: `${__dirname}/work/`,
      },
    },
    // ...

*For resolving the files, I use the `gatsby-source-filesystem` plugin. So, I can query that folder by `sourceInstanceName: { eq: "work" }`.*

---

**gatsby-node.js:**

    exports.onCreateNode = ({ node, getNode, actions }) => {
    
      const { createNodeField } = actions
    
      if (node.internal.type === `Directory`) {
    
        if (node.sourceInstanceName === `work`) {
    
          if (!node.relativeDirectory) {
            createNodeField({
              node,   
              name: `workCategory`,
              value: true,  
            })
          }
        }
      }
    }

*This code helps me to flag the categories for later purpose, e.g. displaying a list of categories on a overview page.*

---
**Example Queries:**

    {
      allDirectory(
        filter: {
          sourceInstanceName: { eq: "work" }
          relativeDirectory: { eq: "" }
        }
      ) {
        edges {
          node {
            dir
            name
            extension
            relativeDirectory
            relativePath
          }
        }
      }
    }

*Querying all categories.*

---

    {
      allDirectory(
        filter: {
          sourceInstanceName: { eq: "work" }
          relativeDirectory: { eq: "drawing" }
        }
      ) {
        edges {
          node {
            dir
            name
            extension
            relativeDirectory
            relativePath
          }
        }
      }
    }

*Querying all pieces of the category `drawing`.* 

---

    {
      allFile(
        filter: {
          sourceInstanceName: { eq: "work" }
          extension: { in: ["jpg", "jpeg", "png"] }
        	relativeDirectory: { eq: "drawing/drawing-1" }
        }
      ) {
        edges {
          node {
            dir
            name
            extension
            relativeDirectory
            relativePath
          }
        }
      }
    }

*Querying all pictures of the piece `drawing-1` inside category `drawing`.*

---

**The problem:**

In the best case I'd like to iterate through each category and display the work pieces with its pictures and descriptions from the `index.md`. But how can I extract the categories seprately to query for the pieces? Is my concept missleading? If you're having any good suggestion, what I should think of to achieve my goal, I'll be very happy with it.

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.0.0 - /usr/local/bin/node
    Yarn: 1.12.3 - ~/.yarn/bin/yarn
    npm: 3.5.2 - /usr/bin/npm
  Browsers:
    Chrome: 67.0.3396.87
    Firefox: 65.0
  npmPackages:
    gatsby: ^2.0.25 => 2.0.119 
    gatsby-plugin-catch-links: ^2.0.5 => 2.0.10 
    gatsby-plugin-google-tagmanager: ^2.0.5 => 2.0.9 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.4 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.17 
    gatsby-plugin-offline: ^2.0.7 => 2.0.23 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.6 
    gatsby-plugin-sass: ^2.0.1 => 2.0.10 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.5 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.5 
    gatsby-plugin-typescript: ^2.0.0 => 2.0.7 
    gatsby-plugin-typography: ^2.2.0 => 2.2.7 
    gatsby-remark-autolink-headers: ^2.0.7 => 2.0.14 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-prismjs: ^3.0.2 => 3.2.4 
    gatsby-source-filesystem: ^2.0.4 => 2.0.20 
    gatsby-transformer-remark: ^2.1.7 => 2.2.4 
  npmGlobalPackages:
    gatsby-cli: 2.4.5

**Comment by DSchau** [comment]
Hello! Sorry for the delay on this!

To be honest with you--I'm not 100% sure what you're asking.

It _seems_ like you want a way to query for images for a particular category, which you have mostly implemented?

> But how can I extract the categories seprately to query for the pieces? Is my concept missleading

Could you use `context` and send the category when you're creating the page? Then you can query for e.g. a glob pattern, or something that matches the category when you're using allFile?

Generally - a [reproduction](https://gatsby.dev/reproduction) would be very helpful for me to understand exactly what you're trying to do, and whether there's a better recommendation from us.

Thanks!
