### ISSUE TITLE
ValidationError when exporting a function from gatsby-config.js

### ISSUE THREAD

**Issue by sondrele** [gatsbyjs/gatsby#12286]
## Description

I'm testing out `themes` with gatsby, and from [gatsby-theme-examples](https://github.com/ChristopherBiscardi/gatsby-theme-examples/blob/master/themes/gatsby-theme-blog/gatsby-config.js#L3) I can see that it's also possible to export a function from `gatsby-config.js`, in order to configure a theme dependency.

This works when the theme is plugged in as a dependency to a project, but this does not seem to be supported by gatsby if I try to run `gatsby build` or `gatsby develop` directly in my theme project.
If I try to run one of the build commands, Gatsby ends up throwing an error:

```
$ yarn build                                                                                                                    [n: 11.9.0]
yarn run v1.13.0
$ gatsby build
⠁ The site's gatsby-config.js failed validation
ValidationError: "value" must be an object
error The site's gatsby-config.js failed validation

```

Since Gatsby supports resolving themes that exports a function (that returns a config) from it's `gatsby-config`, it should also be supported in a general gatsby function. 
**This would make it easier to independently develop and maintain themes.** 

### Steps to reproduce

1. Clone this repo: https://github.com/ChristopherBiscardi/gatsby-theme-examples
2. Install dependencies: `$ cd gatsby-theme-examples && yarn install`
3. Attempt to only build [gatsby-theme-blog](https://github.com/ChristopherBiscardi/gatsby-theme-examples/tree/master/themes/gatsby-theme-blog): `cd themes/gatsby-theme-blog && yarn build`

### Expected result

The build should succeed, and not result in an error.

### Actual result

An error was thrown:

```
⠁ The site's gatsby-config.js failed validation
ValidationError: "value" must be an object
error The site's gatsby-config.js failed validation


  Error: The site's gatsby-config.js failed validation
  
  - config.js:29 module.exports
    [gatsby-theme-examples]/[gatsby]/dist/redux/reducers/config.js:29:17
  
  - redux.js:451 combination
    [gatsby-theme-examples]/[redux]/lib/redux.js:451:29
  
  - redux.js:211 dispatch
    [gatsby-theme-examples]/[redux]/lib/redux.js:211:22
  
  - index.js:89 Object.action [as dispatch]
    [gatsby-theme-examples]/[gatsby]/dist/redux/index.js:89:91
  
  - index.js:117 
    [gatsby-theme-examples]/[gatsby]/dist/bootstrap/index.js:117:11
  
  - Generator.next
  
  - util.js:16 tryCatcher
    [gatsby-theme-examples]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [gatsby-theme-examples]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [gatsby-theme-examples]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:606 Promise._settlePromiseCtx
    [gatsby-theme-examples]/[bluebird]/js/release/promise.js:606:10
  
  - async.js:142 _drainQueueStep
    [gatsby-theme-examples]/[bluebird]/js/release/async.js:142:12
  
  - async.js:131 _drainQueue
    [gatsby-theme-examples]/[bluebird]/js/release/async.js:131:9
  
  - async.js:147 Async._drainQueues
    [gatsby-theme-examples]/[bluebird]/js/release/async.js:147:5
  
  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [gatsby-theme-examples]/[bluebird]/js/release/async.js:17:14
  
```

### Environment
```
  System:
    OS: Linux 4.15 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.5.1 - /usr/bin/zsh
  Binaries:
    Node: 11.9.0 - ~/.nvm/versions/node/v11.9.0/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v11.9.0/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v11.9.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 66.0
  npmPackages:
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20 
    gatsby-remark-images: ^3.0.3 => 3.0.3 
    gatsby-transformer-remark: ^2.2.3 => 2.2.3 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13 

```

**Comment by DSchau** [comment]
I'm not sure it's (currently) possible to run themes locally for development, rather I think the intended use case would be to `link` (`yarn link` or `npm link`) the theme in a "parent" project that uses the theme.

If we were to tweak the validation, it may give a false sense of security that a function can be used, when in fact, functions are currently exclusive to themes.

Themes are still in their relative infancy, but we'll want to document developing locally with themes, which will entail documenting things like linking, using a theme in a project, etc.

For your edification, the process would look something like:

```
cd theme-example
yarn
yarn link

# later
cd your-project-that-uses-this-theme
yarn link gatsby-theme-example # or whatever the name is
yarn build or yarn develop
```

Going to close this as answered, but please feel free to continue the discussion further and we can re-open or revisit.

Thanks so much!

**Comment by sondrele** [comment]
I understand that this example repository is there for demonstrative purposes, and that the project relies on yarn and its workspaces to properly link the themes and the dependent packages.
I'm also aware that themes are in early stages.

However, I still think it would be beneficial to be able to build and develop a theme package in isolation as if it was a simple gatsby site.
I actually had the impression that (simply put) a gatsby theme was just a plugin that also provided additional configuration, and it should therefore be possible to run it independently (in addition to the `link`-suggestion provided over) - but maybe that's just wishful thinking? :)

**Comment by DSchau** [comment]
@sondrele most non-trivial themes would need some type of content injection that only a "parent app" could provide (e.g. content as Markdown, MDX, posts sourced from wordpress, etc.), so it seems like sort of an anti-pattern to develop locally with a theme for any reason other than testing and ease-of-use.

That being said--I do think the ease-of-use argument is a fair one. Something we've tossed around internally is a top-level themes folder (just like with plugins) but I'm not necessarily convinced this is any easier to use than simply linking the theme with your local project.

We'd be happy to be convinced otherwise, we do want to keep the barrier to entry low with these, but we also don't want to encourage folks to use things in a way that w wouldn't strongly encourage.

**Comment by sondrele** [comment]
> Something we've tossed around internally is a top-level themes folder (just like with plugins) but I'm not necessarily convinced this is any easier to use than simply linking the theme with your local project.

I agree. In general I think it's better/easier to rely on the tooling and best practices that already exists in the ecosystem, than re-inventing new ways of connecting and building Gatsby apps. It just increases the amount of domain knowledge required to develop a gatsby project, that is not transferable to other js-projects.

> We'd be happy to be convinced otherwise, we do want to keep the barrier to entry low with these, but we also don't want to encourage folks to use things in a way that we wouldn't strongly encourage or that make a barrier to entry in other areas (e.g. publishing) more challenging.

Fair points, and I also fully agree on being restrictive on features/alternative ways of doing things in order to have a low barrier to entry.

I still think it can be a little confusing to people that the `gatsby-config` can be defined in two different ways, while only the object-type configuration can be built, but as long as we have this in mind when themes are being integrated (and well documented) in Gatsby, it should be good enough :)
