### ISSUE TITLE
Styled Components Problem

### ISSUE THREAD

**Issue by JhonathaNunes** [gatsbyjs/gatsby#12283]
## Description

I have an issue while using styled-components with gatsby. I already use the styled-components plugin. It works, but if I reload the page the style stops working. When in develop it works normal, when built this happens, maybe it is some problem with path.

### Steps to reproduce

Use styled component with gatsby, install the plugin and in a different page from index reload the page

### Expected result

The page should be like in localhost
<img width="1280" alt="screen shot 2019-03-04 at 11 07 53" src="https://user-images.githubusercontent.com/33481861/53738424-ecfef500-3e6d-11e9-8f29-fbcca0fcc4bd.png">

### Actual result

The style breaks

<img width="1277" alt="screen shot 2019-03-04 at 11 08 12" src="https://user-images.githubusercontent.com/33481861/53738425-ecfef500-3e6d-11e9-91b6-f8c93f113301.png">

### Environment

Run `npx gatsby build` and `npx gatsby serve`, or deploy the project

 in your project directory and paste the output here.

**Comment by lannonbr** [comment]
@JhonathaNunes Is there a possibility that you could link the code for this or possibly create a reproducible test case to resolve this. Here's the docs on such: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

**Comment by jeffrafter** [comment]
@JhonathaNunes just checking but are you using styled components 4 and `createGlobalStyle`? If you are using `injectGlobal` then there is a known problem with hot module reloading (which is why it is deprecated)

**Comment by JhonathaNunes** [comment]
The problem solved when I updated gatsby.
