### ISSUE TITLE
Gatsby config validation should suggest related keys

### ISSUE THREAD

**Issue by ChristopherBiscardi** [gatsbyjs/gatsby#12291]
## Summary

When running a gatsby site the gatsby-config is validated. The error message is quite long due to multiple instances of the failed validation error that appear after the initial `ValidationError`. The error also doesn't suggest any possible mis-spellings, so a user new to Gatsby can become frustrated fairly easily, not knowing that `plugin` should be `plugins`. 

<details>
 <summary>full error log</summary>

```
➜ yarn workspace scotchy-site develop
yarn workspace v1.13.0
yarn run v1.13.0
$ gatsby develop
⠁ The site's gatsby-config.js failed validation
ValidationError: "plugin" is not allowed
error The site's gatsby-config.js failed validation


  Error: The site's gatsby-config.js failed validation

  - config.js:29 module.exports
    [Scotch-gastby-theme-demo]/[gatsby]/dist/redux/reducers/config.js:29:17

  - redux.js:451 combination
    [Scotch-gastby-theme-demo]/[redux]/lib/redux.js:451:29

  - redux.js:211 dispatch
    [Scotch-gastby-theme-demo]/[redux]/lib/redux.js:211:22

  - index.js:89 Object.action [as dispatch]
    [Scotch-gastby-theme-demo]/[gatsby]/dist/redux/index.js:89:91

  - index.js:117
    [Scotch-gastby-theme-demo]/[gatsby]/dist/bootstrap/index.js:117:11

  - Generator.next

  - util.js:16 tryCatcher
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:638:18

  - promise.js:432 Promise._resolveCallback
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:432:57

  - promise.js:524 Promise._settlePromiseFromHandler
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:524:17


error UNHANDLED REJECTION


  Error: The site's gatsby-config.js failed validation

  - config.js:29 module.exports
    [Scotch-gastby-theme-demo]/[gatsby]/dist/redux/reducers/config.js:29:17

  - redux.js:451 combination
    [Scotch-gastby-theme-demo]/[redux]/lib/redux.js:451:29

  - redux.js:211 dispatch
    [Scotch-gastby-theme-demo]/[redux]/lib/redux.js:211:22

  - index.js:89 Object.action [as dispatch]
    [Scotch-gastby-theme-demo]/[gatsby]/dist/redux/index.js:89:91

  - index.js:117
    [Scotch-gastby-theme-demo]/[gatsby]/dist/bootstrap/index.js:117:11

  - Generator.next

  - util.js:16 tryCatcher
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:638:18

  - promise.js:432 Promise._resolveCallback
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:432:57

  - promise.js:524 Promise._settlePromiseFromHandler
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:524:17


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/chris/.nvm/versions/node/v10.6.0/bin/node
Arguments: /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js develop
Directory: /Users/chris/tmp/Scotch-gastby-theme-demo/site
Output:
```

</details>

### Basic example

I'd like to see the output truncated to exclude the duplicate errors and also add a suggested option based on Levenshtein distance to possible valid keys.

```
➜ yarn workspace scotchy-site develop
yarn workspace v1.13.0
yarn run v1.13.0
$ gatsby develop
⠁ The site's gatsby-config.js failed validation
ValidationError: the key "plugin" is not allowed, did you mean "plugins"?

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/chris/.nvm/versions/node/v10.6.0/bin/node
Arguments: /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js develop
Directory: /Users/chris/tmp/Scotch-gastby-theme-demo/site
Output:
```

### Motivation

> Why are we doing this? What use cases does it support? What is the expected outcome?

This change supports people new to Gatsby and new to reading error messages in general by showing less "noise" and providing helpful suggestions, making Gatsby an even friendlier tool for newcomers.

**Comment by ryancharris** [comment]
@ChristopherBiscardi @DSchau I can take a whack at this one, if that's cool with you gents.

**Comment by DSchau** [comment]
@ryancharris of course! Let us know if @gatsbyjs/core can help out further!

**Comment by ryancharris** [comment]
@DSchau Sweet! I'm sure I'll have some questions as I get more familiar with the codebase 👍

**Comment by jonlow** [comment]
Related to this issue, plugins added in gatsby-config will silently fail if there are typos in the plugin options. Simply misspelling 'options' in any plugin won't show any errors, but the plugin will not load. This can be a headache for anybody to debug (not just Gatsby newcomers) 

Quick twitter convo with @DSchau @jlengstorf regarding this https://twitter.com/jonlowforever/status/1102820897398767617

**Comment by ryancharris** [comment]
@ChristopherBiscardi To clarify, do you not want to see the stack trace in the logs? I was doing some testing last night and only saw a single stack trace, not duplicates like you have above.

Or were you referring to these as duplicates?
```
⠁ The site's gatsby-config.js failed validation
ValidationError: "plugin" is not allowed
error The site's gatsby-config.js failed validation
```

**Comment by ChristopherBiscardi** [comment]
@ryancharris I'd be happy with listing all invalid top-level keys so that people don't have to re-run the process to find each spelling issue if they have multiple to fix. Really any suggestions is better than today's behavior (no suggestions) though.

If you're not seeing duplicates then don't worry about the stack trace stuff

**Comment by ryancharris** [comment]
@ChristopherBiscardi Sounds good to me. I have the top level keys stuff pretty much working. Just gotta take care of the suggestions.

**Comment by jlengstorf** [comment]
Hey, @ryancharris! How's it going with this feature? Anything we can do to help?

**Comment by sharat9211** [comment]
Hi,
Found this issue while going through good first issues. Have done some preliminary research on how this was implemented in other CLIs. Wordpress CLI has this feature. The discussion is on the following two threads: 
https://github.com/wp-cli/wp-cli/issues/3861
https://github.com/wp-cli/wp-cli/issues/4379

They basically have  a two pronged approach to solving this problem:
1. They find out the distance between the user entered key and allowed keys and suggest based on that
2. They have a prebuilt dictionary of suggestions. 

 The first approach is taken from git which also does this when you type "git stati" it suggests "git status". The git implementation of the same can be found in https://github.com/git/git/blob/e0aaa1b6532cfce93d87af9bc813fb2e7a7ce9d7/help.c#L302

I can start working on this, if nobody else is.

**Comment by jlengstorf** [comment]
@sharat9211 we'd love to have your help! Thanks so much for digging into prior art!

**Comment by sharat9211** [comment]
@jlengstorf Cool will start working on it. Where should I start looking at in the codebase?

**Comment by jlengstorf** [comment]
It looks like we've started some of this work here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/did-you-mean.js

So that's probably the best place to start. Thanks!

**Comment by jeremyscatigna** [comment]
Hey! 👋Is there any way I could help?

**Comment by DZuz14** [comment]
How is everything going on this? I know @ryancharris was working on this, so I wanted to see if he's still around with some of the validation code that he was working on.

To help, I came up with a list of all of the errors I could produce when it comes to misconfiguring the `gatsby-config.js` file.  You can check them all out via this [gist](https://gist.github.com/DZuz14/5cd84aa5f5fb720f0edb0458feaf7592).

I wanted to create this list of errors because I receive different errors than Ryan originally posted about. I do not receive any output whatsoever that Gatsby even attempted to validate the config file.

If we don't hear back from Ryan, I'd be glad to start working on this. I will definitely need some help.

**Comment by alexbarkin** [comment]
@DSchau @danabrit  Hey, I just came across this issue. I've been looking to get into open source work for a bit, and thought this could be a good first issue. Would it be cool if I took a crack at it and opened a PR?

**Comment by DZuz14** [comment]
You should prob just go ahead and work on it and submit something. No one is responding clearly lol.

**Comment by DSchau** [comment]
@DZuz14 we're listening and seeing :) How can we help?

If @ryancharris is no longer working on this -- would be a great opportunity to take some prior work/art and continue with the work!

**Comment by DZuz14** [comment]
@DSchau Im going to work on this. I've been doing some snooping around and is this where we should be doing the check?

Perhaps test the flattened array for the typos before it goes any further and tries to load any of the plugins via the load.js file?
