### ISSUE TITLE
404 link on Gatsby home page

### ISSUE THREAD

**Issue by jumpalottahigh** [gatsbyjs/gatsby#12306]
## Description

Clicking the "Creating Plugins" button on the https://www.gatsbyjs.org/ home page in the plugins section (see image) leads to a 404.

![image](https://user-images.githubusercontent.com/4155121/53785962-cb137a00-3f22-11e9-824d-8f0724f9045b.png)

Refreshing the page after that triggers the correct(?) redirect.

Additionally, there is at least one more broken link on this page:
https://www.gatsbyjs.org/docs/plugins/
and there could be other cases so maybe global search for the slug to search and replace is a good idea.

### Steps to reproduce

1. Go to live site home page (incognito or not)
2. Scroll down to the plugins section
3. Click the "Creating Plugins" button

### Expected result

We should see the relevant page or be redirected correctly.

### Actual result

We see a 404.

### Environment

N/A

**Comment by Fazyyy** [comment]
Could this be something specific to your machine? I'm not able to replicate the issue and the link works as expected for me in both Firefix and Chrome on Windows 10, also fine on my Pixel 2 in Chrome.

**Comment by jumpalottahigh** [comment]
Hm, don't think it's just me, or then could it be some CDN edge caching issue?

I get consistent 404 when clicking the button on my mac, any browser, incognito or not; also tested on my Pixel 3 chrome incognito and not, either way always 404 on that link (also tested on 4G and WiFi, just to change networks). Would be nice if more people could test.

**Comment by Fazyyy** [comment]
Apologies, I think I was mislead by the "Using plugins" being white in your screenshot and was testing that instead, updated with my original post as I do in fact experience the same issue as you when clicking "Create Plugin"

**Comment by JABedford** [comment]
I can recreate and have found several more cases of this relatively quickly.

Seems as though the `/docs/plugin-authoring/` page does not exist. A refresh redirects to `/docs/how-plugins-work/`.

Are you taking this one @jumpalottahigh? Else I will put a PR in for it.

**Comment by jumpalottahigh** [comment]
@JABedford , please, go for it! I'd absolutely love to help, but I have one too many things on my table at the moment :(. Very happy you are jumping in though! Thank you.

**Comment by JABedford** [comment]
I know that feeling!

**Comment by JABedford** [comment]
I guess for now I will just redirect them to the "How Plugins Work" page. Probably better than a broken link?

**Comment by jumpalottahigh** [comment]
This has been quiet for a while and I had some time to put together #12736 , hope you don't mind @JABedford .

**Comment by JABedford** [comment]
No, absolutely not. I just never had the time to look into it properly.
