### ISSUE TITLE
gatsby-plugin-sharp 2.0.24 requires gatsby@2.1.20 but specifies peer dependency of gatsby@^2.0.0

### ISSUE THREAD

**Issue by matt-assemble** [gatsbyjs/gatsby#12307]
## Description

gatsby-plugin-sharp 2.0.24 requires gatsby@2.1.20 but specifies peer dependency of gatsby@^2.0.0

https://github.com/gatsbyjs/gatsby/pull/10257
https://github.com/gatsbyjs/gatsby/blob/8e1661806931b0af42b744b9b5c8cf2909ae1201/packages/gatsby-plugin-sharp/package.json#L43

### Steps to reproduce

Use the right combination of plugins and configs to actuate gatsby-plugin-sharp and then at build time:

```
error Plugin gatsby-plugin-sharp returned an error


  Error: Cannot find module 'gatsby/dist/utils/cpu-core-count'
  
  - v8-compile-cache.js:159 require
    [code]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - index.js:88 Object.<anonymous>
    [code]/[gatsby-plugin-sharp]/index.js:88:22
  
  - v8-compile-cache.js:178 Module._compile
    [code]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - v8-compile-cache.js:159 require
    [code]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - gatsby-node.js:3 Object.<anonymous>
    [code]/[gatsby-plugin-sharp]/gatsby-node.js:3:18
  
  - v8-compile-cache.js:178 Module._compile
    [code]/[v8-compile-cache]/v8-compile-cache.js:178:30
```

### Expected result

Minor version updates to not break the install.

### Actual result

Breakage.

**Comment by LekoArts** [comment]
![85ecf14e-8a45-460f-89b9-d8492caff761](https://user-images.githubusercontent.com/16143594/53787369-f005ee00-3f1e-11e9-992f-42c2ad8bbb6c.png)

Yeah, this user had the same experience :/

**Comment by pieh** [comment]
```
 - gatsby-plugin-manifest@2.0.22
 - gatsby-plugin-sharp@2.0.25
```
was published with the fix. We don't need updated gatsby version, just added code to gracefully fallback to previous behaviour if gatsby is a bit older
