### ISSUE TITLE
[1.0] Should we add friendly errors for webpack?

### ISSUE THREAD

**Issue by craig-mulligan** [gatsbyjs/gatsby#1231]
I see a lot of webpack based projects use this [package](https://www.npmjs.com/package/friendly-errors-webpack-plugin), it cleans up the webpack output quite nicely.. any objections to adding it? or are there other plans for stdout?

**Comment by KyleAMathews** [comment]
Woah, looks really nice!

We should add this and eslint-loader — been meaning to get to the latter for a while. Want to create a PR?

**Comment by KyleAMathews** [comment]
Fixed in #1240
