### ISSUE TITLE
Cannot render the "Rich Text" field from Contentful 

### ISSUE THREAD

**Issue by MaralS** [gatsbyjs/gatsby#12313]
Hello everyone,

## Description

I have some issues rendering the rich text field from Contentful. I tried to use the gatsby plugin, but there are bugs for the rendering of assets and entries inside the rich text field (#9821 - #10592)
So I installed the package from Contentful.
But when I want to parse the JSON to HTML nothing renders.

Here is the code from my blog template 

```
import React from "react"
import { Link, graphql } from "gatsby"
import Img from "gatsby-image"
import {DefaultLayout} from "../components/DefaultLayout"
import {
  BLOCKS,
  MARKS,
  INLINES
} from '@contentful/rich-text-types';
import { documentToHtmlString} from '@contentful/rich-text-html-renderer'
const document = {
  nodeType: 'document',
};

const options = {
  renderNode: {
      [INLINES.ASSET_HYPERLINK]: node => {
        return `<img class='custom-asset' src="${
                node.data.target.fields.file['fr-FR'].url
              }"/>`
      },
      [INLINES.EMBEDDED_ENTRY]: node => {
        return `<div class='custom-entry' />${
                node.data.target.fields.name['fr-FR']
              }</div>`
      },
    },
    renderMark: {
      [MARKS.BOLD]: text => `<custom-bold>${text}<custom-bold>`,
    },
  }


class BlogPostContentfulTemplate extends React.Component {
  render() {
    const post = this.props.data.contentfulPost
    const { previous, next } = this.props.pageContext
    return (
      <DefaultLayout location={this.props.location} siteDescription={post.metaDesc} siteTitle={post.metaTitle}>
        <h1>{post.postTitle}</h1>
        <ul>
          <li>Article par {post.author}</li>
        </ul>

        <Img fluid={post.postThumbnail.fluid} />
        <div className="article-content">{post.content.content}</div>
        {
          console.log("Result :" + documentToHtmlString(post.content.content, options))
          /// Console output
          // Result :
        }
        <ul>
          <li>
            {previous && (
              <Link to={`/blog/${previous.slug}`} rel="prev">← {previous.postTitle}</Link>
            )}
          </li>
          <li>
            {next && (
              <Link to={`/blog/${next.slug}/`} rel="next">{next.postTitle} →</Link>
            )}
          </li>
        </ul>
      </DefaultLayout>
    )
  }
}

export default BlogPostContentfulTemplate

export const pageQuery = graphql`
query ContentfulBlogPostBySlug($slug: String!) {
    contentfulPost( slug: { eq: $slug } ) {
        slug
        postTitle
        author
        metaTitle
        metaDesc
        content{
          nodeType
          content
        }
        postThumbnail {
            fluid{
              ...GatsbyContentfulFluid
            }
         }
      }
    }
`
```
### Steps to reproduce

- Clone the dev branch from my repository

- Switch to the dev branch

- Do `yarn develop`

- Then go [blog post used for the test](http://localhost:8000/blog/create-a-blog-using-gatsby-js-and-contentful/) and check the console. Nothing happens.

### Expected result

The HTML rendered completely, with assets and entries.

### Actual result

Nothing rendered

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```
 gatsby info --clipboard
module.js:549
    throw err;
    ^

Error: Cannot find module 'regenerator-runtime/runtime'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Maral Sabbagh\AppData\Roaming\npm\node_modules\gatsby-cli\lib\index.js:88:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by phacks** [comment]
In your `graphql` query, try to use the following snippet to fetch the Rich Text content : 

```
content {
  childContentfulRichText {
    html
  }
}
```

You can see an example for an [live website](https://jamstack.paris) built with Gatsby & Contentful [here](https://github.com/JAMstack-paris/JAMstack.paris/blob/a60ec51fe1b414aaeab223bcef4ead417ac573e3/src/pages/index.js#L81-L84) (for the graphql query) and [here](https://github.com/JAMstack-paris/JAMstack.paris/blob/a60ec51fe1b414aaeab223bcef4ead417ac573e3/src/components/TextBlock/TextBlock.component.js#L13-L15) (for the actual display of the `RichText`):

**Comment by MaralS** [comment]
> In your `graphql` query, try to use the following snippet to fetch the Rich Text content :
> 
> ```
> content {
>   childContentfulRichText {
>     html
>   }
> }
> ```
> You can see an example for a [live website](https://jamstack.paris) built with Gatsby & Contentful [here](https://github.com/JAMstack-paris/JAMstack.paris/blob/a60ec51fe1b414aaeab223bcef4ead417ac573e3/src/pages/index.js#L81-L84) (for the graphql query) and [here](https://github.com/JAMstack-paris/JAMstack.paris/blob/a60ec51fe1b414aaeab223bcef4ead417ac573e3/src/components/TextBlock/TextBlock.component.js#L13-L15) (for the actual display of the `RichText`):

Hi,
I already tried to use the plugin as I said before. The reason why I don't use it anymore is that the assets and the entries  inside the rich text fied are not rendered.

**Comment by phacks** [comment]
Oh, sorry! Read your issue in a hurry, and had trouble setting up Contentful’s RichText myself, so I went ahead with what I assumed was the same problem. My mistake 😅

**Comment by MaralS** [comment]
> Oh, sorry! Read your issue in a hurry, and had trouble setting up Contentful’s RichText myself, so I went ahead with what I assumed was the same problem. My mistake 😅

No no that's ok. Don't worry.
I reinstalled the gatsby transformer plugin for Contentful but I still have the same issue assets and entries  are not rendered
.

**Comment by DSchau** [comment]
@MaralS we can't actually follow your reproduction steps because you haven't provided a repository/reproduction we can take a look at!

Would you be able to [check this document out](https://gatsby.dev/reproduction) and then post that repository here?

Additionally - since there are API keys involved here, it may be necessary to send me some details so that I can authenticate with Contentful via Gatsby, which is non-ideal.

Alternately, a [pairing session](https://gatsby.dev/pairing) could be helpful here.

**Comment by MaralS** [comment]
> @MaralS we can't actually follow your reproduction steps because you haven't provided a repository/reproduction we can take a look at!
> 
> Would you be able to [check this document out](https://gatsby.dev/reproduction) and then post that repository here?
> 
> Additionally - since there are API keys involved here, it may be necessary to send me some details so that I can authenticate with Contentful via Gatsby, which is non-ideal.
> 
> Alternately, a [pairing session](https://gatsby.dev/pairing) could be helpful here.

Hi @DSchau 
I will do isolate the bug in a specific repository. I made my repo private because i don't want to make all my data public with the api key.
How can  I do ?
Thanks

**Comment by DSchau** [comment]
@MaralS I'd recommend _not_ committing the API key to a Github repo (even private) if you can ever avoid it.

Generally, I'd read this [using environment variables](https://www.gatsbyjs.org/docs/environment-variables/). Would strongly recommend using a tool like [dotenv](https://www.npmjs.com/package/dotenv), and then not committing your secrets to the repo!

**Comment by polarathene** [comment]
I don't have any experience personally with this issue, but I am aware of it. This should probably be discussed in an issue in the relevant repo: https://github.com/contentful/rich-text

See the existing issues on the topic(there are some closed ones as well). I believe someone made some progress and they might have solved it, but I'm not sure if it's been solved correctly yet (since I haven't been following the discussions).

**Comment by rmcsharry** [comment]
I think this might be because the Gatsby GraphQL engine is not able to see the `MARKS` property, which is required in order to convert Rich Text to Html when using the render plugin

See https://github.com/contentful/rich-text/issues/111

**Comment by Roshif** [comment]
you can try :

content {
            json
         }

**Comment by rmcsharry** [comment]
@Roshif Yes, using the json node works, thank you so much!
