### ISSUE TITLE
Help debugging vague error

### ISSUE THREAD

**Issue by Fazyyy** [gatsbyjs/gatsby#12312]
## Description

Site deploys to netlify and builds fine but if I try to run it locally with npm run build or gatsby develop-
it's 'compiles' fine but then if you navigate to localhost:8000 it will 'load' for several minutes while displaying nothing and then the server will crash.

### Steps to reproduce

Repo:
https://github.com/Fazyyy/Trago2Wheels

Simply run a local development and navigate to localhost then watch the console for the build to crash and display the error.

### Expected result

Site compiles and runs locally without issue

### Actual result

`
i ｢wdm｣: Compiling...
error UNHANDLED EXCEPTION

  Error: UNKNOWN: unknown error, watch

  - watchers.js:123 FSEvent.FSWatcher._handle.onchange
    internal/fs/watchers.js:123:28
`

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

`
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/user/.windows-build-tools/python27/python
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.1.14 => 2.1.14
    gatsby-image: ^2.0.29 => 2.0.29
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-sharp: ^2.0.21 => 2.0.21
    gatsby-remark-copy-linked-files: ^2.0.9 => 2.0.9
    gatsby-remark-images: ^3.0.4 => 3.0.4
    gatsby-source-filesystem: ^2.0.23 => 2.0.23
    gatsby-transformer-remark: ^2.2.5 => 2.2.5
    gatsby-transformer-sharp: ^2.1.14 => 2.1.14

error The system cannot find the path specified.

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby]/[envinfo]/dist/envinfo.js:1:4970

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby]/[envinfo]/dist/envinfo.js:1:66948

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby]/[envinfo]/dist/envinfo.js:1:48777

  - envinfo.js:1
    [npm]/[gatsby]/[envinfo]/dist/envinfo.js:1:46934

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby]/[envinfo]/dist/envinfo.js:1:46949

  - util.js:16 tryCatcher
    [npm]/[gatsby]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:694:18

error UNHANDLED REJECTION

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby]/[envinfo]/dist/envinfo.js:1:4970

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby]/[envinfo]/dist/envinfo.js:1:66948

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby]/[envinfo]/dist/envinfo.js:1:48777

  - envinfo.js:1
    [npm]/[gatsby]/[envinfo]/dist/envinfo.js:1:46934

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby]/[envinfo]/dist/envinfo.js:1:46949

  - util.js:16 tryCatcher
    [npm]/[gatsby]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [npm]/[gatsby]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [npm]/[gatsby]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [npm]/[gatsby]/[bluebird]/js/release/promise.js:694:18
`

**Comment by Fazyyy** [comment]
Seems to have resolved itself.
Not sure how, perhaps just by running npm install?

**Comment by Fazyyy** [comment]
Issue has returned, once again unsure of cause.

Console says site compiled successfully.
Go to localhost:8000
Page loads for 5 minutes+ without actually displaying anything
Then gatsby develop stops running with the error:

```
error UNHANDLED EXCEPTION


  Error: UNKNOWN: unknown error, watch

  - watchers.js:123 FSEvent.FSWatcher._handle.onchange
    internal/fs/watchers.js:123:28
```

**Comment by eballeste** [comment]
Error: The system cannot find the path specified.

**Comment by josefaidt** [comment]
Have you tried reinstalling node_modules and clearing Gatsby's `/.cache/` directory?

**Comment by josefaidt** [comment]
@Fazyyy I just downloaded your repo and installed deps, and ran the site without issue. I would start by deleting the `/node_modules/` and `/.cache` directories locally. Also, I'd suggest removing one of the lockfiles to mitigate any further issues (ex: if you use `npm` then remove `yarn.lock` and vice-versa).

**Comment by Fazyyy** [comment]
@eballeste 
I'm not exactly sure how to find out what path without more to go on.

@josefaidt 
The 'yarn.lock' was just from me fiddling with a few things in order to try and troubleshoot a few things. I'll definitely be deleting that. I will try your suggestion with deleting the other directories and report back shortly.

**Comment by Fazyyy** [comment]
So I deleted the yarn.lock, .cache and node-modules folders but when I run npm install I get...

```
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

'\\TRMFP\users$\user\My Documents\GitHub\Trago2Wheels\node_modules\sharp'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'C:\Windows\install\libvips'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

C:\Windows>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: EPERM: operation not permitted, mkdir 'C:\Windows\build'
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN rollback Rolling back string-width@1.0.2 failed (this is probably harmless): EPERM: operation not permitted, lstat '\\TRMFP\users$\user\My Documents\GitHub\Trago2Wheels\node_modules\gauge\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: idb-connector@1.1.8 (node_modules\idb-connector):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for idb-connector@1.1.8: wanted {"os":"aix","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.21.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-03-06T10_16_06_594Z-debug.log
```

I've installed Python, Visual Studio 2017, completely deleted the local repo and pulled it from github again but error persists, any ideas?

**Comment by wardpeet** [comment]
Did you follow https://www.gatsbyjs.org/docs/gatsby-on-windows/ ?

**Comment by sthielen** [comment]
For anyone else who might be troubleshooting this, we just encountered it on a Windows build where the user was using a Net Use alias to access the Gatsby project. Using the true path on the filesystem resolved the issue - seems like there was an issue initializing the file watcher for aliased paths. My Windows knowledge is limited, so I'm not sure how to debug any more deeply, but hopefully this helps anyone encountering the same issue.

**Comment by treechime** [comment]
@sthielen Lifesaver 🙏 Just had this exact same thing and moved the project to the local drive and it worked perfectly.
