### ISSUE TITLE
Gatsby Theme not building the pages but works in develop

### ISSUE THREAD

**Issue by wcastand** [gatsbyjs/gatsby#12322]
## Description

I'm using the gatsby theme feature for a project, in `develop` it works perfectly but when i try to build it, i get no error but only the index page is built, but not the other pages.

### Steps to reproduce
I made the project's repo public so you can take a look.
[repo](https://github.com/teamplanes/dashbored)

you can see the theme in `packages/gatsby-theme-dashbored`
and the demo gatsby website using it in `packages/dash`

I use createPage to dynamically create pages in the theme.

### Expected result

It should build the website with all the pages

### Actual result

Only building the index page
(right now i think, the render is glitching because my styled-component has a bad init and does the rendering on the fly)
### Environment

```
  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.0.0 - /usr/local/bin/fish
  Binaries:
    Node: 11.9.0 - /var/folders/k1/f1hwwnjx793cq6jdbs31hv9r0000gn/T/yarn--1551798254187-0.24223292950237574/node
    Yarn: 1.13.0 - /var/folders/k1/f1hwwnjx793cq6jdbs31hv9r0000gn/T/yarn--1551798254187-0.24223292950237574/yarn
    npm: 6.5.0 - ~/.fnm/node-versions/latest/installation/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: 64.0
    Safari: 12.0.3
```

**Comment by DSchau** [comment]
It's a bit hard to untangle exactly what's going on here. I don't fully understand all of the flowRight/lodash stuff that you're doing here.

That being said, I don't think this is correctly being awaited:

```
flowRight(
    createPP,
    map(fetchQueries),
  )(queries)
```

seems to return undefined, rather than a Promise like you'd expect.

If you attempt to build this out locally you get a helpful here, e.g.

```
warning Action createPage was called outside of its expected asynchronous lifecycle createPages in gatsby-theme-dashbored.
Ensure that you return a Promise from createPages and are awaiting any asynchronous method invocations (like graphql or http requests).
For more info and debugging tips: see https://gatsby.dev/sync-actions

File /Users/dschau/Code/Work/gatsby/test/dashbored/packages/gatsby-theme-dashbored/gatsby-node.js:52:9
  50 |       const uri = page.default ? '/' : `/${page.title.toLowerCase().replace(/\s/gim, '-')}`
  51 |       Promise.all(queries).then(result => {
> 52 |         createPage({
     |         ^
  53 |           path: uri,
  54 |           component: require.resolve(path.resolve(__dirname, `./src/templates/dash.js`)),
  55 |           context: { ...page, uri, result },
```

If you fix this error, are you able to successfully build out the pages like you'd expect?

**Comment by wcastand** [comment]
Nice, it's working i returned a promise and it worked.
I still get a warning but not sure if i can fix that because i'm sending different data every time.
<img width="457" alt="screenshot 2019-03-05 at 23 11 42" src="https://user-images.githubusercontent.com/2178244/53843960-161da380-3f9c-11e9-9e28-9e0112a85c7c.png">
