### ISSUE TITLE
Site Showcase entry doesn't include category fields

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#12320]
## Description

Josef Aidt's site in the site showcase does not have any category fields.

@josefaidt Would it be possible to update your entry so this warning doesn't appear

![image](https://user-images.githubusercontent.com/3685876/53813278-411bdf00-3f2b-11e9-9a32-d94e7c2f590f.png)

Here's the docs for the page for reference on site showcase submissions: https://www.gatsbyjs.org/contributing/site-showcase-submissions/

**Comment by josefaidt** [comment]
@lannonbr just added the categories. Apologies for missing that 🙂
