### ISSUE TITLE
gatsby-remark-code-repls do not support scoped dependencies (started by @ character)

### ISSUE THREAD

**Issue by krzysztofpniak** [gatsbyjs/gatsby#12327]
## Description

At the moment `gatsby-remark-code-repls` plugin do not support scoped npm packages (started by @ character). It expects only one @ character for name - version separation.

### Steps to reproduce
1. git clone https://github.com/reactjs/reactjs.org.git
2. cd reactjs.org
3. run `yarn`
4. go to file: `gatsby-config.js`
5. find `dependencies` array and add `@material-ui/core` to that array
6. go to file: `content/docs/hello-world.md`
7. replace `[](codepen://hello-world)` by `[](codesandbox://hello-world)`
8. run project by: `npm run dev`
9. go to your browser: http://localhost:8000/docs/hello-world.html and click link `Try it on CodePen`

### Expected result

code on the Code Sandbox should have @material-ui/core correctly attached (`"@material-ui/core": "latest"`)

### Actual result

if you one package.json you'll see "": "material-ui/core" in dependencies.

I have patched it on my locak copy. I can prepare pull request with the patch.

### Environment

 System:
    OS: macOS 10.14.2
    CPU: x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: 64.0
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.0 => 2.0.21 
    gatsby-plugin-catch-links: ^2.0.0 => 2.0.4 
    gatsby-plugin-feed: ^2.0.0 => 2.0.8 
    gatsby-plugin-glamor: ^2.0.0 => 2.0.5 
    gatsby-plugin-google-analytics: ^2.0.0 => 2.0.6 
    gatsby-plugin-manifest: ^2.0.0 => 2.0.5 
    gatsby-plugin-netlify: ^2.0.0 => 2.0.1 
    gatsby-plugin-nprogress: ^2.0.0 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.0.0 => 2.0.6 
    gatsby-plugin-twitter: ^2.0.0 => 2.0.6 
    gatsby-remark-code-repls: ^2.0.0 => 2.0.0 
    gatsby-remark-copy-linked-files: ^2.0.0 => 2.0.5 
    gatsby-remark-embed-snippet: ^3.0.0 => 3.0.0 
    gatsby-remark-images: ^2.0.0 => 2.0.4 
    gatsby-remark-prismjs: ^3.0.2 => 3.0.2 
    gatsby-remark-responsive-iframe: ^2.0.0 => 2.0.5 
    gatsby-remark-smartypants: ^2.0.0 => 2.0.5 
    gatsby-source-filesystem: ^2.0.0 => 2.0.3 
    gatsby-transformer-remark: ^2.0.0 => 2.1.7 
    gatsby-transformer-sharp: ^2.0.0 => 2.1.3

**Comment by DSchau** [comment]
Thanks for the detailed write up!

Looks like [these lines](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-code-repls/src/index.js#L137-L142) will need to be modified to support scoped packages.

Any interest in adding/fixing this functionality?

**Comment by krzysztofpniak** [comment]
I already fixed it locally, I can submit pr tomorrow.
