### ISSUE TITLE
localhost:8000 not refreshing on windows build

### ISSUE THREAD

**Issue by nickeblewis** [gatsbyjs/gatsby#1233]
We have a windows machine that runs gatsby fine, the site loads ok but when making changes, the sync doesn't work. We then need to stop gatbsy develop from running, re-run it and the changes are then visible. What sort of things should we check for?

**Comment by craig-mulligan** [comment]
@nickeblewis, hmm.. try check the browser console request for a `/__webpack_hmr` request, I assume it'll be a failed request but that err may give you a hint. Otherwise check the webpack output for anything weird.
