### ISSUE TITLE
Creating Pagination with Headless CMS... a little confused.

### ISSUE THREAD

**Issue by danboyle8637** [gatsbyjs/gatsby#12330]
I am using GraphCMS as my headless cms at the moment. I can pull all my data in... but now I'm working on pagination for my blog page.

I deleted my original blog.js page under the pages folder since now these blog pages should be build dynamically in my gatsby-node.js file. 

Here is what I have in my gatsby-node file:

```javascript

const path = require(`path`)

// This creates blog pages based on the number of total blog posts.
// Currently I have 6 blog posts showing up per page.
exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions

  return new Promise((resolve, reject) => {
    const blogPage = path.resolve(
      `${__dirname}/src/components/Blog/BlogList.js`
    )
    graphql(
      `
        {
          gcms {
            blogPosts(orderBy: published_DESC) {
              id
              slug
            }
          }
        }
      `
    ).then(result => {
      if (result.errors) {
        reject(result.errors)
      }

      //Create pages based on posts per page.
      const posts = result.data.gcms.blogPosts
      const postsPerPage = 6
      const numberOfPages = Math.ceil(posts.length / postsPerPage)
      Array.from({ length: numberOfPages }).forEach((_, i) => {
        createPage({
          path: i === 0 ? `/blog` : `/blog/${i + 1}`,
          component: blogPage,
          context: {
            limit: postsPerPage,
            skip: i * postsPerPage,
          },
        })
      })
      resolve()
    })
  })
}

exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions

  if (node.internal.type === 'gcms') {
    const value = createFilePath({ node, getNode })
    createNodeField({
      name: `slug`,
      node,
      value,
    })
  }
}

```

I followed the docs and understand everything up until the exports.onCreateNode block.

What is this supposed to be doing?

And the node.internal.type?

In the docs it checks if it's equal to 'MarkdownRemark'

But since I'm pulling in from GraphCMS... I don't know what to check for.

My site compiles but none of my blog pages get created. I should have two blog list pages because I have 10 total posts for this site.

I also have another entire block of exports.createPages for each individual blog post itself. I'm assuming that's correct.

**Comment by jonniebigodes** [comment]
@danboyle8637 a little insight on the `onCreateNode ` api call [here](https://www.gatsbyjs.org/docs/node-apis/#onCreateNode) and the `createFilePath` explanation [here](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createfilepath).
>And the node.internal.type?

In a nutshell almost every single piece of data that is pulled into Gatsby will be have a type associated with. Taking the example of markdown. When the plugin is fetching the files and transforming them, it will generate a graphql schema structure to allow the data to be queried and manipulated in this case by you, the developer. As your using GraphCMS as a source and configured it with what i expect is [gatsby-source-graphql](https://www.gatsbyjs.org/packages/gatsby-source-graphql/), a way i know to check what is the node type is issue `gatsby develop` open a browser window to `http://localhost:8000/___graphql` and on the right side there should be a `docs` link, clicking that will expand the documentation available to every node available and it's type, with that your node type should be also included in there aswell.

**Comment by danboyle8637** [comment]
@jonniebigodes Thanks! When you said to check graphiql it was not a head slap moment. 

I will give this a try and see if I can get my code to work. 

Thanks again!
