### ISSUE TITLE
Why is the callback from static-entry.js called with NULL value?

### ISSUE THREAD

**Issue by TomFreudenberg** [gatsbyjs/gatsby#12341]
## Summary

I try to overload entry in webpack event `onCreateWebpackConfig` to proceed with some actions on rendered `html`.

But the callback() from argument is always called with NULL value

```
callback(null, html)
```

I would expect it should include the pagePath

```
callback(pagePath, html)
```

Is this a bug or intented?

## Relevant information

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/static-entry.js#L394

**Comment by DSchau** [comment]
This is a common Node.js convention. A callback is invoked with an error as the first parameter (if an error occurred), otherwise the first argument is null and the second argument(s)--or rather non-first arguments, are the requested data.

Sorta weird in that we're not ever calling back with an error, but it is a standard convention we're following here.

We'd be happy to accept PRs here--but we'd have to be wary of a breaking change here, which modifying this behavior would certainly be.

As this is--going to close as answered, but please reply further if we can help or if you disagree!

Thanks for using Gatsby 💜

**Comment by TomFreudenberg** [comment]
Hi Dustin @DSchau 

thanks for your feedback. If it does not break the system, could you imagine to accept a PR for a new gatsby-node.js event like `onPostRenderedHTML`?

Thanks for your feedback
Tom

**Comment by DSchau** [comment]
@TomFreudenberg what are you trying to do, exactly?

We do have [extension points](https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody) that do something similar.

**Comment by TomFreudenberg** [comment]
First of all, I am new to Gatsby for about 3 days by now - so maybe I have not yet get every aspect of the framework. Sorry in that case for silly questions.

What I like to do is following:

I have a `doc1.js` which I likely to have as doc1.pdf.

So after rendering the `doc1.js` into a static html file, I have to run a puppeteer system call, to convert that html into pdf. After that I would like to add the pdf as resource by js file. That should all be run during `npm run build`

Do you understand my requirements?

I have not yet found a suitable event for that.

**Comment by DSchau** [comment]
@TomFreudenberg never apologize! We're glad to have you here, any question is a good question.

So you want to parse /doc1 (which will be HTML) into a PDF, and then make that PDF available _in_ /doc1? My main question concerns this comment:

> After that I would like to add the pdf as resource by js file

I'm not really sure what this means. Do you want to link to the PDF file? That seems strange since a PDF of the page you're on seems not super useful?

**Comment by TomFreudenberg** [comment]
@DSchau 

Lets say I have a calendar app. There are a number of entries I may browse by the app. In addition I would like to have also a Monthly View to print. So I create a page `monthView.js` with special print styles like "DIN A4", "portrait" etc. 

After this page is rendered into static html file, I can use puppeteer to convert that into `monthView.pdf`

I want to add that pdf file into the app by `Link` or whatever. Best fit is, that the pdf file is also offline available on client. 

I do not need to have the link `/monthView` as html (webpage) anymore after the puppeteer process has converted it - just added as pdf would be fine.

**Comment by TomFreudenberg** [comment]
Hi Dustin @DSchau 

maybe its easier to understand when I explain the build workflow step by step. If I don't run that all in one build process, it works:

```
gatsby new pdf-documents
gatsby new my-app
```

In `pdf-documents` I create `src/pages/month.js`.

``` js
import React from "react"
import styles from "../styles/sass.module.scss"

export default () =>

    <div id="pdf">
      <div id="page1" className={`${styles.page} ${styles.landscape}`}>
        <h1>Month view</h1>
        <p>Hello world</p>
        <div id={styles.pdfLogo}>
           <img src="/img/pdf-logo.svg" alt="pdf-logo" />
        </div>
      </div>
    </div>
```

### Step 1: build pdf documents html

```
cd pdf-documents
npm run build
```

### Step 2: take static html from public and convert by puppeteer.
This output file will be written to `../my-app/src/pages/month.pdf`

```
puppeteer-to-pdf ./public/month/index.html ../my-app/src/pages/month.pdf
```

### Step 3: include the pdf into app

Inside `my-app` I create `src/pages/documents.js` like

``` js
import React from "react"
import { Link } from "gatsby"
import month from "./month.pdf"

function Documents() {
  return <Link to={month}>Monthly PDF</Link>
}

export default Documents
```

### Step 4: build the app

```
cd my-app
npm run build
npm run serve
```

Now Webpack has made my app and also packed the pdf into static folder with id.

When I surfe to `http://localhost:9000/documents` I see the link to the Month pdf and when I click, the pdf will be opened.


### Question:

Is it possible to solve such a workflow in one gatsby project and one build process?

Thanks for help
Tom

**Comment by TomFreudenberg** [comment]
@DSchau, I moved my question to a new descriptive thread and deleted the off-topics here.

Maybe you do this too

Thanks, Tom
