### ISSUE TITLE
Gatsby CLI commands not working

### ISSUE THREAD

**Issue by MaralS** [gatsbyjs/gatsby#12352]
## Description

I try to run gatsby command, and i have the following error 
```
Maral Sabbagh@HP-MARAL MINGW64 /d/Maral Sabbagh/Documents/Sites/maralsabbagh (dev)
$ gatsby develop
module.js:549
    throw err;
    ^

Error: Cannot find module 'regenerator-runtime/runtime'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Maral Sabbagh\AppData\Roaming\npm\node_modules\gatsby-cli\lib\index.js:88:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
It's really frustrating because when I'm doing `yarn develop` i don't have the problem.
I tried to update `gatsby-cli` but nothing happens.
I tried to install the package `regenerator-runtime`, it changes nothing either.

**Comment by DSchau** [comment]
Could you run the command `gatsby --version` and let me know what that outputs?

If you haven't already, I'd try wiping and re-installing, like so:

```shell
npm uninstall -g gatsby-cli
npm install -g gatsby-cli
```

Alternately, you don't _have_ to use the global (i.e. you can use package scripts) but for stuff we'll be working on soon we do recommend using the global, so it'd be nice to figure this out!

**Comment by MaralS** [comment]
> Could you run the command `gatsby --version` and let me know what that outputs?
> 
> If you haven't already, I'd try wiping and re-installing, like so:
> 
> ```shell
> npm uninstall -g gatsby-cli
> npm install -g gatsby-cli
> ```
> 
> Alternately, you don't _have_ to use the global (i.e. you can use package scripts) but for stuff we'll be working on soon we do recommend using the global, so it'd be nice to figure this out!

Hello @DSchau 
I was trying to delete the module with yarn. Maybe it's not a good idea. I used npm  and i do not have the error ! 
Thanks
