### ISSUE TITLE
Improve createNode documentation for parent field 

### ISSUE THREAD

**Issue by andru** [gatsbyjs/gatsby#12363]
## Summary

When creating a new node using `createNode` within an `onCreateNode` lifecycle hook, not setting the parent id may lead to the graphql schema generation inferring types incorrectly.

In my particular case, I was using an `onCreateNode` hook to generate new nodes based on nodes created by `gatsby-transformer-json`. 
When the `parent` field is set to null, none of the field values are [checked to see if they look like filepaths](https://github.com/gatsbyjs/gatsby/blob/23b84338f50ed372e41440fdba538c583e0b203d/packages/gatsby/src/schema/types/type-file.js#L28-L35), leading to the "cannot make a subselection of a String type" error which is usually associated with missing files.
When `parent` is set to the `id` of the parent `gatsby-transformer-json` node, filenames in field values are correctly detected and assigned an appropriate mime-type for later transform plugins to operate on. 

It would be helpful if the documentation regarding the `parent` field of a new node placed emphasis on the importance this.

The current documentation reads:

> The ID of the parent’s node. If the node is derived from another node, set that node as the parent. Otherwise it can just be null.

Unless this is actually a bug rather than a lack of documentation, I'll happily provide a PR, though some suggestions on a better way to word it would help!

### Basic example

I'm not great at documentation, but a line like 

> The ID of the parent’s node. If the node is derived from another node, you should set that node as the parent to ensure proper schema type inference. It should only be null where nodes are not derived from another node.

 ... or something similar

### Motivation

To reduce confusion. The current documentation makes it seem that the `parent` field is only to maintain relationships for the benefit of later convenience when writing graphql queries.

**Comment by stefanprobst** [comment]
I think this is because we only allow linking to File nodes on nodes that themselves have a root File node:
https://github.com/gatsbyjs/gatsby/blob/9bef10ac6b5dfb10ec5ffbe873b8720a397bcb19/packages/gatsby/src/schema/types/type-file.js#L102-L106

Not 100% sure why we do this though.

**Comment by KyleAMathews** [comment]
There's several other reasons you need to set the parent. I agree it'd be helpful to explain why parent is needed.

**Comment by KyleAMathews** [comment]
Another reason it's needed is that we delete nodes that aren't recreated during bootstrap unless they come from a parent node that is still alive. Without the parent node set, the child gets deleted which leads to people needing to clear the cache all the time to force recreating all nodes

**Comment by KyleAMathews** [comment]
@stefanprobst the reasoning is that we only allow relative paths between files. So without the origin node being derived from a file, we can't calculate the link.

**Comment by stefanprobst** [comment]
@KyleAMathews Maybe I'm misunderstanding, but linking to a File by something other than `relativePath` *is* allowed. For example, this works in a default starter:
```js
// gatsby-node.js
exports.sourceNodes = ({ actions }) => {
  actions.createNode({
    id: `test1`,
    parent: null,
    children: [],
    internal: {
      type: `Test`,
      contentDigest: `test1`,
    },
    link___NODE___base: `gatsby-astronaut.png`,
  })
}
```
