### ISSUE TITLE
npx gatsby --help

### ISSUE THREAD

**Issue by FeruzOripov** [gatsbyjs/gatsby#12368]
## Description

When I run `npx gatsby --help` I'm getting this error

### Result

npm ERR! Unexpected end of input at 1:1034920
npm ERR! -url":"^2.0.0","joi":"^9.1.1","json-loader":"^0.5.2","json-stringify-
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/feruz/.npm/_logs/2019-03-07T04_16_16_693Z-debug.log
Install for gatsby@latest failed with code 1

**Comment by aravindballa** [comment]
Can you provide some info on which machine you are on and `npm` version you use?
Looks like `gatsby-cli` is not installed properly. You can try re-installing it.

**Comment by FeruzOripov** [comment]
I found solution. I've just cleaned cache and helped me. `npm cache clean --force`

**Comment by FeruzOripov** [comment]
It was Ubuntu 18.04 LTS.
