### ISSUE TITLE
Output files with .html extension create unnecessary folder

### ISSUE THREAD

**Issue by 0505gonzalez** [gatsbyjs/gatsby#12364]
## Description
When deploying to GithubPages, I experience multiple redirects. This affects my page's SEO score.

For example, I have the page `/src/pages/en/test.html.js`. I then visit `https://mysite.com/en.test.html` which github redirects to `https://mysite.com/en.test.html/` (a trailing slash is added).

The cause of the issue is the way that the static HTML files are built. Github pages adds a trailing slash to directories. My gatsby page above, when converted to a static page is converted from `/src/pages/en/test.html.js` to `/public/en/test.html/index.html`. Instead, it should be `/public/en/test.html`.

### Steps to reproduce

1. Create a page `/src/pages/test.html.js`. Add any content.
2. Run `gatsby build`
3. Deploy to github pages

### Expected result
Visiting `https://mypage.com/test.html` should work without any redirects.

### Actual result
Visiting `https://mypage.com/test.html` redirects to  `https://mypage.com/test.html/ (trailing slash at the end`

### Environment
```
  System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.7.0 - ~/.nvm/versions/node/v8.11.1/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Languages:
    Python: 3.7.0 - /Users/gonzalez/anaconda3/bin/python
  Browsers:
    Firefox: 42.0
    Safari: 12.0
  npmPackages:
    gatsby: ^2.1.19 => 2.1.19 
    gatsby-image: ^2.0.30 => 2.0.30 
    gatsby-plugin-manifest: ^2.0.20 => 2.0.20 
    gatsby-plugin-offline: ^2.0.24 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.7 => 3.0.7 
    gatsby-plugin-remove-trailing-slashes: ^2.0.9 => 2.0.9 
    gatsby-plugin-sharp: ^2.0.23 => 2.0.23 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-transformer-sharp: ^2.1.15 => 2.1.15 
  npmGlobalPackages:
    gatsby: 2.1.19
```

**Comment by 0505gonzalez** [comment]
I have a proposed fix for this. I can create a PR for it shortly.

**Comment by DSchau** [comment]
Is there a reason that you are suffixing your pages with `.html.js`?

We create html files for you, so given `test.js` we will create `test/index.html`

**Comment by 0505gonzalez** [comment]
This is a port from an existing static site which has plain html files. We wanted to keep the links the same

**Comment by 0505gonzalez** [comment]
I think this case was supposed to be handled ([see this line](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/worker.js#L9), but the page creator interferes with this if statement. The filename the page creator generates is `/pages/test.html/` with a trailing slash

**Comment by 0505gonzalez** [comment]
Or is there a reason that a page `src/pages/test.js` is generated as `/public/test/index.html` instead of `/public/test.html`?

**Comment by DSchau** [comment]
If you strip the .html suffix from URLs (e.g. at the server level) wouldn't the URLs be the same?

You referenced Netlify, and they specifically [call that behavior out](https://www.netlify.com/docs/redirects/#trailing-slash)

e.g. given `/test.html`, the user could type `/test` and that would refer to `/test/` which would still work like you'd expect?

> Or is there a reason that a page src/pages/test.js is generated as /public/test/index.html instead of /public/test.html?

Yeah - I'd think the basis was that we support creating nested paths, e.g.

```
src/pages/test/
  index.js // test/index.html
  something // test/something.html
```

**Comment by 0505gonzalez** [comment]
> e.g. given /test.html, the user could type /test or /test.html and that would refer to /test/ which would still work like you'd expect?

The problem is the other way around. The old static pages had the `.html` extension. So in order for the links to still work, the `html` extension is necessary. E.g. old url looked like this: `/test.html`. In order to do this with gatsby, I'd have to create the page `test.html.js` since `test.js` would create the html file `test/index.html` and the `/test.html` url would not work (only either `/test/` or `/test/index.html`

**Comment by DSchau** [comment]
I think that's exactly what I mentioned! Netlify's documentation states:

> Rewrite link URLs: /about.html -> /about, /about/index.html -> /about

Given a user accessing a URL `/test.html` that would be rewritten (with the pretty URL setting in Netlify) to `/test` which will map to `/test/index.html` which is what Gatsby produces. In your scenario, the user would follow a link to `https://your-site.com/test.html` which would automatically be re-written to `https://your-site.com/test`.

For example, here's a link to a proposals site I built with Gatsby: https://proposals.dustinschau.com/index.html

If you visit that page, you'll be re-directed to https://proposals.dustinschau.com/

Also just to clarify here--are you using Netlify? I'd imagine you can do something similar with re-write rules in other platforms, however!

**Comment by 0505gonzalez** [comment]
I'm using Github pages

**Comment by dja** [comment]
@DSchau Hey! I saw on your proposals site that you don't have trailing slashes at all - Was there something custom that you did to do that? Are you on Netlify?

**Comment by DSchau** [comment]
@dja nothing custom--all Netlify!

Source code is [here](https://github.com/dschau/cfps), although it's all based on a theme [here](https://github.com/DSchau/gatsby-themes/tree/master/themes/blog)

**Comment by Nowaker** [comment]
Can this ticket be reopened? I'm interested to have `custom.html` files as an output. Just like I can have PDFs and other static content served as such without renaming, asking for the same with HTMLs isn't a huge ask, I think.

We're rebuilding our Jekyll site in Gatsby, and we don not want to change the underlying infrastructure like rewrites. The file structure of the generated site (so, paths and file names) should remain the same for making the Gatsby transition as painless as possible. 

CC @DSchau

**Comment by DSchau** [comment]
Would something like what the React team did suffice?

All of their pages include the .html suffix when they're creating the page (actions.createPage), and Gatsby should respect that when you create pages.

An example: https://github.com/reactjs/reactjs.org/blob/main/gatsby/onCreateNode.js#L50

https://reactjs.org/docs/getting-started.html

**Comment by Nowaker** [comment]
@DSchau This ticket gave my team an impression outputting `.html` files is not possible at all. However, once we looked into the code, we came up with this:

```javascript
exports.createPages = async ({ actions: { createPage }, graphql }) => {
  const jekyllPageTemplate = path.resolve(
    './plugins/gatsby-plugin-transformer-jekyll/src/templates/jekyll-page.js'
  )
  const JekyllPages = await graphql(`
    {
      # graphql structure here
    }
  `).then((results) => {
    results.data.allJekyllHtml.edges.forEach((node) => {
      createPage({
        path: `/${node.node.relativeDirectory}/${
          node.node.name !== 'index' ? node.node.name + '.html' : ''
        }`,
```

And it seems to work just fine. Yours uses `onCreateNode`, ours uses `createPages`. I'm not very familiar with React and Gatsby, so I consider it a hackery, but one that works... Is your solution more preferable than what we did?

**Comment by DSchau** [comment]
If it works -- it works! 

Your solution is just fine -- the React team did it that way so that when Markdown nodes are created, they automatically add a slug field to the node at node generation time. You do it at page generation time -- both work!
