### ISSUE TITLE
[bug]: Brave browser blocks chunks with analytics/google-analytics in their name

### ISSUE THREAD

**Issue by drobinhood** [gatsbyjs/gatsby#12361]
## Description

When going to https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/ in Brave browser, the page fails to load and opens a blank browser page with "data:text/plain," in the url bar.

The only information I could find referencing this issue seems to be an IE issue with data URIs. This shouldn't be an issue in the Brave browser as it is running chromium. The other weird thing is that seems to be the only page that fails to load, for me anyways.

### Steps to reproduce

Open Brave browser and browse to https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/. 

or

Navigate to the gatsby plugin page and search for google analytics plugin and click on the google analytics plugin.

### Expected result

It should pull up the plugin page.

### Actual result

It opens an empty tab with "data:text/plain," in the url bar.

### Environment

NA

**Comment by DSchau** [comment]
Well this is extremely strange! Thanks for opening this issue.

I am fairly sure that this is an issue with over-aggressively blocking content. Specifically, we have a "chunk" that is loaded with this page that is named

`https://www.gatsbyjs.org/static/d/576/path---packages-gatsby-plugin-google-analytics-aac-98e-fxfP6ZZk9SZ4lij1lrssolXc.json`

Brave aggressively blocks this call, so the fetch from the service worker fails and the page fails to render.

To get around, you can disable the "guard" for gatsbyjs.org, but it'd be nice if special-cased this chunk naming so we can avoid the blocking in the first place.

**Comment by drobinhood** [comment]
Not really worried about getting around, just pulled up the github page for the plugin I needed.

It's just rather weird that with all of the plugin pages the only ones that fail to load are the ones related to google analytics. It does the below for pretty much any plugin referrencing google analytics.

Fetch API cannot load https://www.gatsbyjs.org/static/d/576/path---packages-gatsby-plugin-google-analytics-aac-98e-fxfP6ZZk9SZ4lij1lrssolXc.json. Redirects to data: URL are allowed only when mode is "no-cors".

It's just weird that the plugin page is not adding any additional trackers yet Brave refuses to load it because of the reference to google analytics in the content being loaded. Perhaps this is an issue I should open with Brave then? Seems like there should be some kind of fallback for this kind of behavior. Just my two cents.

**Comment by DSchau** [comment]
@drobinhood it's because Brave (and other content blockers) are following kind of a naive algorithm here (presumably--it at least seems that way).

They're blocking any network requests that match a pattern, e.g. `google-analytics`. So any plugin that has that google-analytics in its title will be blocked, because the page resources will fail to fetch.
