### ISSUE TITLE
Start dev server with custom path 

### ISSUE THREAD

**Issue by rubeonline** [gatsbyjs/gatsby#12379]
When i start development with `gatsby develop` the dev server starts with:
http://localhost:8000/

I want to open the dev-server with a **specific route** like this:
http://localhost:8000/de/

I don´t have a index.html in the root. I have this structure:
/public
___/de/index.html
___/en/index.html
*.css
*.js

On my production environment i redirect via .htaccess. The dev server always start with error because he don´t find the index.html in root. So i don´t want to prefix at all. Just want to start my dev server with specific route.

Is this possible?

**Comment by JABedford** [comment]
https://www.gatsbyjs.org/docs/path-prefix/
I believe that this should help?

In summary:

```javascript
module.exports = {
  // Note: it must *not* have a trailing slash.
  pathPrefix: `/de`,
}
```
and then run
```shell
gatsby build --prefix-paths
```

**Comment by DSchau** [comment]
This is not currently possible.

We allow an option `pathPrefix` which gives you the ability to deploy your application to a route, but the general approach is that you use the development server as if you weren't behind a prefix.

Could you walk me through your setup a bit? I'm not sure exactly how you'd create a structure with gatsby develop like you describe in public, unless you're doing that manually?

A [reproduction](https://gatsby.dev/reproduction) would also be very much appreciated! Thanks!

**Comment by rubeonline** [comment]
Thanks for your response. So we use contentful where our pages are created. The content there is multilingual. We create the pages with `createsPages` in gatsby-node.js. In the `onCreatePage` method we modify the path with the locale:

```
const locales = {
  "de": {
    path: 'de'
  },
  "en-US": {
    path: 'en'
  }
}

exports.onCreatePage = ({ page, actions }) => {
  const { createPage, deletePage } = actions

  return new Promise(resolve => {
    deletePage(page)

    Object.keys(locales).map(lang => {
      const localizedPath = locales[lang].path + page.path

      return createPage({
        ...page,
        path: localizedPath,
        context: {
          locale: lang,
        },
      })
    })

    resolve()
  })
};
```

So we getting all our pages in this way:
/de/about/index
/en/about/index

and so on. And gatsby develop starts at **localhost:8000**. Its not a really big issue. I can type in the browser **localhost:8000/en/** but when somebody clones the website und runs gatsby develop he get this:

![image](https://user-images.githubusercontent.com/5664460/54018683-a3721b00-4189-11e9-9c83-6a6286864ad1.png)


It would be great do have something like your prefixPath for only starting the webserver from my custom route.

like this: 
````
module.exports = {
  devUrl: "/en/",
}
````

`gatsby develop --use-dev-url`

browser opens:

**localhost:8000/en/**

**Comment by wardpeet** [comment]
Isn't it possible to create a redirect on develop?
```js
// in gatsby-node.js
exports.createPages = ({ actions, graphql }) => {
  const { createRedirect } = actions

  if (process.env.NODE_ENV === "development") {
    createRedirect({
      fromPath: `/`,
      isPermanent: true,
      redirectInBrowser: true,
      toPath: `/en/`,
    })
  }
}

```

**Comment by rubeonline** [comment]
Hi thanks for your answer. It is 100% what I need but I just testet is and i´m getting first a 404 before the redirect starts. So it does not render my page. Looks like this issue: #5329

**Comment by rubeonline** [comment]
Closed by mistake so reopend again.

**Comment by wardpeet** [comment]
@rubeonline would it be ok to close this one as your issue got resolved but now you're hitting #5329?

**Comment by rubeonline** [comment]
@wardpeet Yes for sure. Thanks.

**Comment by HipsterZipster** [comment]
Why is this issue closed? This seems like a very valid request?
