### ISSUE TITLE
Can't `yarn run bootstrap` from repo install instruction

### ISSUE THREAD

**Issue by hedgehog34** [gatsbyjs/gatsby#12388]
I stuck on bullet point 5: "Set up repo and install dependencies: `yarn run bootstrap`" on my Windows machine.
Getting an error:
`$ yarn run bootstrap
yarn run v1.13.0
error Command "bootstrap" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by DSchau** [comment]
Are you in the correct directory? `bootstrap` is a script we expose in our root-level package.json [here](https://github.com/gatsbyjs/gatsby/blob/master/package.json#L66)

**Comment by hedgehog34** [comment]
Probably nope, my package.json's script part looks:
```
"scripts": {
    "build": "babel lib --out-dir dist/",
    "clean-test-bundles": "find test/ -type f -name bundle.js* -exec rm -rf {} +",
    "lint": "eslint --ext .js,.jsx --ignore-path .gitignore .",
    "lint:flow": "babel-node scripts/flow-check.js",
    "test": "npm run lint && npm run test-node && npm run test-integration",
    "test-coverage": "node_modules/.bin/nyc --reporter=lcov --reporter=text npm test",
    "test-integration": "node_modules/.bin/ava test/integration",
    "test-node": "node_modules/.bin/ava test/utils",
    "watch": "babel -w lib --out-dir dist/"
  }
```

I followed the repo instruction though. Is there a step I missed?

**Comment by DSchau** [comment]
Right - yep that's `packages/gatsby`!

You'll want to be up _two_ directories, e.g. `cd ../../`. Your directory structure should have `packages`, `docs`, etc. in the top-level directory.

**Comment by DSchau** [comment]
Going to close this as answered--but please feel free to continue the discussion if any of us can help further.

Thanks for using Gatsby 💜

**Comment by hedgehog34** [comment]
Apologies for reopening, but just want to add that running `git clone --depth=1 https://github.com/<your-username>/gatsby.git` from point 4 cloned the repo with the aforementioned package.json. There is no `cd ../../` from here as I'm at the top level of my cloned version of repo. I'm bit confused...

**Comment by hedgehog34** [comment]
Ah. I got it. I presumably forked wrong version. Feel free to close this up. I'll give it a go with correct repo.
