### ISSUE TITLE
[gatsby-source-shopify] Fallback to cache with warning if API not reachable when developing

### ISSUE THREAD

**Issue by andru** [gatsbyjs/gatsby#12382]
## Summary

Currently, source-shopify will cause `gatsby develop` to fail if the shopify API is not reachable, with the message:

`FetchError: request to https://[api-url]/api/graphql failed, reason: getaddrinfo ENOTFOUND`

### Basic example

I'm not totally familiar with the structure of source plugins, but it would be great if data fetched from the API is cached and used as a fallback during `gatsby develop` bootstrap if the shopify API is unreachable.

Even better would be if this could be passed as an option to `gatsby develop` or added to the config to actively avoid hitting up the live API. 

At least personally I find that most of the time during development, having the most up-to-date data from Shopify is not important, and the time it takes to hit the APIs would shave a good 10s from the gatsby dev bootstrap.

Having read some similar issues related to `source-wordpress`, this might be an issue of `gatsby develop` overly aggressively clearing cache and not something that source plugins have any control over, but - a bit ignorant as I am of the internals - I'm hopeful that's not the case.

### Motivation

Working on trains, planes, etc, or anywhere where network access may be unavailable or flaky. At present `gatsby-source-shopify` makes it impossible, unless there's an undocumented API or something I'm missing

**Comment by DSchau** [comment]
Agreed!

We could follow a similar approach to how we've implemented it in [gatsby-source-contentful](https://www.gatsbyjs.org/packages/gatsby-source-contentful/#offline) which would be a nice feature addition to this plugin.

Happy to take PRs here, or offer any guidance!

**Comment by andru** [comment]
I'd like to keep this open. It's a feature I'd be interested to contribute a PR to when I've got some time for it.
