### ISSUE TITLE
[gatsby-transformer-remark] Extra space when link is in excerpt

### ISSUE THREAD

**Issue by kylejrp** [gatsbyjs/gatsby#12398]
## Description

When a markdown file includes a link that would be shown in the plaintext excerpt, an extra space is added after the link.

### Steps to reproduce

1. Clone https://github.com/gatsbyjs/gatsby-starter-blog
2. Modify `content/blog/hello-world/index.md` so that the first paragraph has a link:
  `This is my first post on my new [fake blog](http://example.com)! How exciting!`
3. Start the site with `gatsby develop` and read the excerpt on the Hello World blog post

### Expected result

The excerpt on the page should say:
> This is my first post on my new fake blog!

### Actual result

The excerpt on the page includes a space before the exclamation point:
> This is my first post on my new fake blog !

### Environment
`gatsby info --clipboard` threw an error when I tried to run it, but here's what it spit out:

```
   System:
     OS: Windows 10
     CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
   Binaries:
     npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
   Browsers:
     Edge: 44.17763.1.0
   npmPackages:
     gatsby: ^2.1.24 => 2.1.24
     gatsby-image: ^2.0.31 => 2.0.31
     gatsby-plugin-feed: ^2.0.14 => 2.0.14
     gatsby-plugin-google-analytics: ^2.0.16 => 2.0.16
     gatsby-plugin-manifest: ^2.0.22 => 2.0.22
     gatsby-plugin-offline: ^2.0.24 => 2.0.24
     gatsby-plugin-react-helmet: ^3.0.8 => 3.0.8
     gatsby-plugin-sharp: ^2.0.25 => 2.0.25
     gatsby-plugin-typography: ^2.2.8 => 2.2.8
     gatsby-remark-copy-linked-files: ^2.0.9 => 2.0.9
     gatsby-remark-images: ^2.0.6 => 2.0.6
     gatsby-remark-prismjs: ^3.2.4 => 3.2.4
     gatsby-remark-responsive-iframe: ^2.0.9 => 2.0.9
     gatsby-remark-smartypants: ^2.0.8 => 2.0.8
     gatsby-source-filesystem: ^2.0.23 => 2.0.23
     gatsby-transformer-remark: ^2.3.1 => 2.3.1
     gatsby-transformer-sharp: ^2.1.15 => 2.1.15

```

**Comment by sidharthachatterjee** [comment]
@kylejrp Can't seem to reproduce this

![Screenshot 2019-03-11 13 53 36](https://user-images.githubusercontent.com/7701981/54109607-1d620880-4405-11e9-91ef-1e414959151b.png)

**Comment by kylejrp** [comment]
My reproduction steps should have been more specific, sorry!

This is referring to the excerpts on the front page, not on the blog post page. I've highlighted it in red here:
![image](https://user-images.githubusercontent.com/6742479/54226260-adae5500-44ba-11e9-97f1-9e31ca4eb5d3.png)

**Comment by kylejrp** [comment]
You can also see this from GraphQL with the following query:

```
{
  allMarkdownRemark{
    edges{
      node{
        excerpt
      }
    }
  }
}
```

It produces this output:
```
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        ...
        {
          "node": {
            "excerpt": "This is my first post on my new  fake blog ! How exciting! I’m sure I’ll write a lot more interesting things in the future. Oh, and here’s a…"
          }
        }
      ]
    }
  }
}
```

Interestingly, the GraphQL query shows an extra space before and after the link. I think that this because HTML shows multiple spaces as one.
```
new  fake blog!
```

**Comment by kylejrp** [comment]
@sidharthachatterjee Should this issue still be marked as `status: needs reproduction`? Is there any other information I can include to help reproduce this error?

**Comment by macklinu** [comment]
I can also reproduce this issue with my Gatsby-powered blog. Will look into contributing a reproduction repo or a failing test today.

**Comment by macklinu** [comment]
Opened up https://github.com/gatsbyjs/gatsby/pull/12878, which is a failing test case to reproduce this issue.

**Comment by wardpeet** [comment]
thanks a lot @macklinu

**Comment by macklinu** [comment]
Opened up #12878 - not sure how to resolve the issue, but this is still a valid bug.

**Comment by iChenLei** [comment]
Looks like this issue has been fixed by this `MR` https://github.com/gatsbyjs/gatsby/pull/12878 ?

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
