### ISSUE TITLE
Improve Contentful source plugin

### ISSUE THREAD

**Issue by Khaledgarbaya** [gatsbyjs/gatsby#1239]
I would like to improve more the plugin, to use the real sync endpoint and for that, I want some feedback on that.

When using Contentful sync we need to save the sync token that holds the timestamp of the last time we performed the sync. Where would be the perfect place to save that token. is there already a `tmp` or `cache` folder created by Gatsby?

Also we need to store the sync data in json format

Best,
Khaled

**Comment by KyleAMathews** [comment]
Hey!

Left a comment over on your PR on the last sync. On storing synced data, Gatsby's data layer handles persisting data for you (as you've probably figured out already).

Glad you're helping out! It'll be awesome having sync support.

**Comment by Khaledgarbaya** [comment]
Hi @KyleAMathews I think we can close this issue.
Still, have a problem when building the example project, I tried to `npm link` tha latest deps but still got errors, any recommendations ?

**Comment by Khaledgarbaya** [comment]
All good, sorry for the spam, I had to go through the ci configs to find out how you develop against gatsby, gatsby-dev for the win

**Comment by KyleAMathews** [comment]
No worries, it's not obvious :-)

The hope is that releases happen enough that the state of example sites don't stay weird very long (if ever) but it's tough right now with all the rapid changes.

Working on a new beta which will make the example site just work again.
