### ISSUE TITLE
[docs] Include semantic versioning for every function/method in www.gatsbyjs.org/docs/

### ISSUE THREAD

**Issue by anthonytranDev** [gatsbyjs/gatsby#12395]
## Summary

When reading through the Gatsby docs, the user can see when a specific semantic versioning of the methods or functions they use from Gatsby and it subsidiary packages

### Example
For instance Node enables versioning of each function, for each specific class. Notice the `Added in:  v0.1.26` and `Added in: 10.0.0`

![screenshot 2019-03-03 at 14 58 11](https://user-images.githubusercontent.com/26009168/53697041-ecf6ea80-3dc4-11e9-9507-cf618e68627d.png)
![screenshot 2019-03-03 at 14 58 46](https://user-images.githubusercontent.com/26009168/53697045-f5e7bc00-3dc4-11e9-876a-d37357d65752.png)

### Motivation
One day, whilst using the `gatsby-cli`. I tried typing in `gatsby clean`, it then suggested that I use the commands available - in short this meant that my CLI wasn't the most recent one.

However in my case, the CLI's `clean` command was only available if bumped up to version `2.4.11` - my current version was `2.4.8` at the time of writing this

#### Advantages of this feature

- **Highlight New Features** - the versioning helps with highlighting additional features they are missing or ones to be taken advantage of. From the current gatsby version they have right now.
- **Check for Breaking Features** - rather than sifting through the CHANGELOG, users can check for breaking changes made to a specific feature. Before deciding to update to the latest versions

#### Disadvantages of this feature

- **High Maintainence Cost** - basically even after this feature has been implemented, it will require the community and core gatsby team to label the version of every new function when it comes out and updates made to current ones

**Comment by KyleAMathews** [comment]
This would be 💯 — I've always liked that from node. We could add it as a jsdoc annotation perhaps (@pieh?) and then pull it into different APIs.

It'd require a fair bit of initial work to sort through git logs to figure out the version things were added but this would be great.

**Comment by anthonytranDev** [comment]
I've pair-programmed with @pieh before, would it alright if I can contribute to this, as well?

**Comment by pieh** [comment]
The `gatsby-cli` commands referenced in issue are sourced from markdown file ( https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-cli.md ), but having a way to support annotations like that both in .md and in jsdoc (not sure if there is jsdoc convention for that) would be great!

This is how node handles this in markdown :
![screenshot 2019-03-08 at 03 31 23](https://user-images.githubusercontent.com/419821/54003607-08f6e500-4153-11e9-85eb-f6d065c03e2b.png)
( https://raw.githubusercontent.com/nodejs/node/master/doc/api/util.md / https://github.com/nodejs/node/blob/master/doc/api/util.md / https://nodejs.org/docs/latest-v11.x/api/util.html )

I think both Gatsby APIs and plugin documentation would benefit from adding metadata like that (when was new option added).

And yeah, it would not only be alright - it would be great if You either want to pair with me (or anyone else) on this!

**Comment by anthonytranDev** [comment]
@pieh Cool that sounds great!! We can pair again. It's a lot of work, present and future; I believe finding a way to easily maintainable and usable is top priority.

[I've already set a date for the pair programming session. I'll see what solutions out there are available.]

**Comment by anthonytranDev** [comment]
Closing Issue
---
No Simple Solution Found - problem is very complex

Approach Discussed
---
Plan was to find a way to extract listed version bumps, focusing on new `feat` include and ignoring `fix`,  and changes from the CHANGELOG, to create a **Standardised Versioning Description Markdown** doc for Gatsby namespace - similar to the one seen above.

Reason why the issue was resolved
---
Currently can't find a feasible, one solution fits all approach to automate the semver on ALL namespaces; extract their Feature change metadata and automatically include them in /docs markdown files.

Complex aspects of the problem
--- 
- All of gatsby package APIs have been documented differently, with a mixture of automated documentation created and manually written ones
- The scope of work is large, to search back on specific namespaces from their inception to now is a large tasks. Coupled with the fact that conventional commits wasn't used at very start of the Gatsby project - https://www.conventionalcommits.org/en/v1.0.0-beta.2/
- Accurate description of Feature addition/change/removal can't be summarised just in the commit message within CHANGELOG

Reopen Premise
---
When a holistic automated solution that is found
