### ISSUE TITLE
Translate docs

### ISSUE THREAD

**Issue by calpa** [gatsbyjs/gatsby#12396]
## Summary

GatsbyJS has brings me a lot of awesome function to build modern website, and I initiated the idea of translating the docs into Chinese version in order to promote it.

Should I copy the docs and start a doc project, or other?

**Comment by lannonbr** [comment]
This sounds like a great idea. So @jlengstorf actually had a livestream about building sites that had internationalization support with GraphCMS ([Livestream VOD](https://www.youtube.com/watch?v=JLwxNeuYcBE) for reference). That said, the website doesn't part

The docs has a huge amount of content, and I think it would be a good step to start building it out in other languages such as Chinese.

@gatsbyjs/docs @gatsbyjs/website, Is there anything on the roadmap yet for i18n support? It would be a large undertaking but could greatly bring a large amount of developers to the community who may not be native english speakers or extremely fluent with the language.

**Comment by calpa** [comment]
reactjs.org has build different repo for different language, maybe we can consider this approach

For simplified Chinese, they build this one:
https://github.com/reactjs/zh-hans.reactjs.org/
https://zh-hans.reactjs.org/

My team and I can contribute to this

**Comment by LekoArts** [comment]
We closed such issues in the past as our stance on that topic currently is that we don’t want to have translated docs (yet). @marcysutton can make a call on this but I doubt that the situation has changed.

**Comment by m-allanson** [comment]
I think having translated docs is a _great_ idea! 

In the past we've not had a good way to publicise translations or keep them up to date. This resulted in occasional docs getting translated but the translated files were tucked away in a folder in the repo, there was no way for people to find them from gatsbyjs.org. This resulted in very few people knowing they existed, which led us to the decision that no translations are probably better than outdated/incomplete and hard-to-find translations.

 The React team's approach seems pretty sensible and scalable: https://reactjs.org/blog/2019/02/23/is-react-translated-yet.html

This will need some set up from the Gatsby team, so it'd be a case of working out if and when we can make the time for that initial setup work.

**Comment by laozhu** [comment]
Great idea, let's make gatsby docs easier for lots of Chinese developers.

**Comment by calpa** [comment]
@m-allanson @lannonbr Any update?

**Comment by KyleAMathews** [comment]
We definitely want to do this but no updates yet.

**Comment by prestonso** [comment]
Happy to say that we're beginning work on an official docs i18n process now!

Right now we're deciding whether it will need to be scoped to the full site or just the docs, but any suggestions about recommended approaches and whether folks find the routes taken by e.g. [React](https://github.com/reactjs/reactjs.org-translation) and [Vue](https://github.com/vuejs/vuejs.org) would also be very welcome!

**Comment by jlengstorf** [comment]
@prestonso this seems like it's probably a good candidate for an RFC — we'll have a lot of different things to iron out and get feedback on before we can start work. Maybe you and I can set some time aside to run through ideas and get the initial RFC written up?

**Comment by alexandrtovmach** [comment]
Is any progress with that? What about [CrowdIn](https://crowdin.com/)?

**Comment by alexandrtovmach** [comment]
I started working on Russian and Ukrainian translations of Tutorials. If we going to have a plan to make global process I'd be in! Let me know how can I help.

**Comment by alexandrtovmach** [comment]
@prestonso Hey! Any progress with that?

**Comment by alexandrtovmach** [comment]
@m-allanson @KyleAMathews @prestonso ping

**Comment by m-allanson** [comment]
The excellent @tesseralis is going to be working on this 🎉 Please [head over to the RFC]( https://github.com/gatsbyjs/rfcs/pull/42) to add your ideas and comments.

**Comment by marcysutton** [comment]
With the translation project and the new Translation Guide, I think we can close this issue now! There are multiple translation repos that are open for contributing, and we are working towards a system to show translated docs on the site. https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/
