### ISSUE TITLE
Possible to meld this build workflow with Gatsby?

### ISSUE THREAD

**Issue by TomFreudenberg** [gatsbyjs/gatsby#12412]
Some days earlier I tried already to ask @DSchau while being in another thread. Hopefully someone could give me some feedback if this might be solveable with gatsby.

The (short) requirements for the app are: Generate some pre-rendered PDF documents for some pages and include that generated PDFs into the app by webpack or offline-data.

I hope that it is easier to understand when I explain the actual (testing framework) build workflow step by step. It works until I try to run that all in one project and one build process:

```
gatsby new pdf-documents
gatsby new my-app
```

In `pdf-documents` I create `src/pages/month.js`.

``` js
import React from "react"
import styles from "../styles/sass.module.scss"

export default () =>

    <div id="pdf">
      <div id="page1" className={`${styles.page} ${styles.landscape}`}>
        <h1>Month view</h1>
        <p>Hello world</p>
        <div id={styles.pdfLogo}>
           <img src="/img/pdf-logo.svg" alt="pdf-logo" />
        </div>
      </div>
    </div>
```

### Step 1: build pdf documents html

```
cd pdf-documents
npm run build
```

### Step 2: take static html from public and convert by puppeteer.
This output file will be written to `../my-app/src/pages/month.pdf`

```
puppeteer-to-pdf ./public/month/index.html ../my-app/src/pages/month.pdf
```

### Step 3: include the pdf into app

Inside `my-app` I create `src/pages/documents.js` like

``` js
import React from "react"
import { Link } from "gatsby"
import month from "./month.pdf"

function Documents() {
  return <Link to={month}>Monthly PDF</Link>
}

export default Documents
```

### Step 4: build the app

```
cd my-app
npm run build
npm run serve
```

Now Webpack has made my app and also packed the pdf into static folder with id.

When I surfe to `http://localhost:9000/documents` I see the link to the Month pdf and when I click, the pdf will be opened.

### Question:

Is it possible to solve such a workflow in one gatsby project and one build process?

Thanks for help
Tom

**Comment by DSchau** [comment]
Hey Tom!

Sorry - I received your e-mail, and wasn't sure how to best reply, so glad you opened an issue!

It would be helpful if you could supply a [reproduction](https://gatsby.dev/reproduction) for this!

More broadly speaking, I don't necessarily think we need to provide anything here to get this working.

If we first augment package.json to have something like:

```json
{
  "scripts": {
    "build": "gatsby build",
    "postbuild": "puppeteer-to-pdf ./public/month/index.html public/month/month.pdf"
  }
}
```

this will run your puppeteer script, and output the month.pdf file deterministically to `public/month/month.pdf`. This will then let us use a relative link (outside of Webpack--which isn't needed here) to your month.pdf view, like so:

```
import React from "react"

// this will not work in local development server, is that OK?
function Documents() {
  return (
    <React.Fragment>
      <a href="./month.pdf">View Monthly PDF</a>
    </React.Fragment>
  )
}

export default Documents
```

I believe this will accommodate your use-case as you wish. Could you try this out and get back to us as to whether this solves your issue?

**Comment by TomFreudenberg** [comment]
Hi Dustin @DSchau 

thanks for feedback - I will check and come back then.

**Comment by TomFreudenberg** [comment]
Hi Dustin @DSchau 

I have prepared 2 Repositories to reproduce my question and issue. The README of each repository will describe how to run. Be aware, the second is not working as expected / wished - this is what I am asking for.

1.) https://github.com/TomFreudenberg/gatsby-build-demo-splitted

I have divided the sample app into 2 projects. One is just to build the pdf documents and the second is to include and serve them.

It is not a good approach because I have to double resources, css etc.


2.) https://github.com/TomFreudenberg/gatsby-build-demo-melted

I have included all the pieces from the above 2 projects into one but the default build process won't create what I need (it has to be exactly what the pdf_app from 1.) is about)

I have written down my current question like:

#### How to meld all in one project and one build process?

The build process must combine the 4 steps

1. run build (but only pdf_*.js pages)
2. run puppeteer-to-pdf.js for all pdf_*/index.html and store the PDF into src path
3. remove public completely
4. run build (but this time without pdf_*.js)

or there must be some "on-the-fly" converting from the pdf_*.js files into pdf_*.pdf resources.

_

Looking forward to your help.

Thanks 
Tom

**Comment by TomFreudenberg** [comment]
HI Dustin @DSchau had you already the option to take a look at the reproductions?

Thanks for a note
Tom

**Comment by DSchau** [comment]
Tom, I haven't, you posted this on a Saturday, so just getting back to it for the week! Thanks for your patience.

I'm trying to unwind this, and to be honest with you--I can't really make sense of what you're trying to do here.

I _think_ I may have gotten what you wanted working in TomFreudenberg/gatsby-build-demo-melted#1, which is mostly what I mentioned in [this comment](https://github.com/gatsbyjs/gatsby/issues/12412#issuecomment-470984936).

<img width="1679" alt="a" src="https://user-images.githubusercontent.com/3924690/54151379-b3e3f900-4408-11e9-8abb-921e7a496e58.png">

<img width="1679" alt="b" src="https://user-images.githubusercontent.com/3924690/54151385-b5adbc80-4408-11e9-8d70-b35fd7d62936.png">

Perhaps I don't understand your use case, but I think this does what you want.

I'm going to close as answered, but I'm going to recommend a [pairing session](https://gatsby.dev/pairing) if you'd like more assistance with this.

Thank you!

**Comment by TomFreudenberg** [comment]
Hi Dustin @DSchau thanks for your feedback - I tested your PR

1. I hadn't recognized that 'postbuild' will automatically run after 'build' - thats fine so far
2. The result has on dismatch to my requirements but hopefully you have one more tip

The path 

* http://localhost:9000/pdf_documents/pdf_sample/

is now available also in the final app BUT SHOULD NOT

The app just should know the routes

http://localhost:9000/
http://localhost:9000/pdf_documents/pdf_sample.pdf

but not the page 

http://localhost:9000/pdf_documents/pdf_sample/

This should only be available for puppeteer process.

Thats why I ran in two loops

Any tipp on this?

Thanks for your help in advance 
Tom

**Comment by TomFreudenberg** [comment]
Hi Dustin @DSchau 

I have seen so far that I may use a "prebuild" and a "postbuild" script to build my app and use some simple check in OnCreateNode event like

"prebuild": "gatsby build --with_pdf_html; find ... -exec puppeteer.sh ...; gatsby clean"

and in gatsby-node.sh something like

``` js
const args = process.argv;
...
exports.onCreatePage = ({ page, actions }) => {
  const { deletePage } = actions
  if (!args.with_pdf_html && (page.path.indexOf('pdf') >= 0)) {
    deletePage(page);
  }
}
```

Is that a valid approach in your mind?

**Comment by DSchau** [comment]
Hi Tom -

You were on the right path!

I PR'd it here TomFreudenberg/gatsby-build-demo-melted#2.

Closing as answered, thanks!

**Comment by TomFreudenberg** [comment]
Hi Dustin @DSchau thanks a lot for the PR - That helps me a lot and made my day.

I would like to spend you some coffee or bucks if you like - just give me a note please

In any way - Thank you very much !!!

Tom

**Comment by DSchau** [comment]
No worries, at all :)

We're happy to help - thanks for using Gatsby and for the nice note 💜

**Comment by TomFreudenberg** [comment]
Hi Dustin @DSchau 

I have prepared a second branch on https://github.com/TomFreudenberg/gatsby-build-demo-melted/blob/feature-source-filesystem/pdf_melted_app

Therefor I have used gatsby-source-filesystem plugin and add the pdf pages during `onCreateNode` event instead dropping them in `onCreatePage` event.

If you had to choose for _better style_ or _preferred approach_ what would you prefer.

Thanks for your additional feedback
Tom

P.S. After all of that I will write a short blog note about adding puppeteer process into gatsby - maybe its interesting for some others too.
