### ISSUE TITLE
[gatsby-source-wordpress] ACF Post Object should map taxonomies as it does Posts?

### ISSUE THREAD

**Issue by joperron** [gatsbyjs/gatsby#12420]
## Summary

First of all, normalizing the data acf-to-rest-api returns so it matches regular WP Post output can be done using the function found [here](https://github.com/airesvsg/acf-to-rest-api/issues/153#issuecomment-371788518).

As of right now when using a [Post Object in an ACF](https://www.advancedcustomfields.com/resources/post-object/), it only returns the category IDs. It should [expand them as it does for posts](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/normalize.js#L233)

### Example query

Query
```
{
  allWordpressPage(filter: {title: {eq: "Home"}}) {
    edges {
      node {
        acf {
          featured_post {
            categories
          }
        }
      }
    }
  }
}
```
Result
```
{
  "data": {
    "allWordpressPage": {
      "edges": [
        {
          "node": {
            "acf": {
              "featured_post": {
                "categories": [
                  29,
                  26,
                  35
                ]
              }
            }
          }
        }
      ]
    }
  }
}
```
### Motivation

![ef5134a366271c930a5634608f7abde1f803759aec2f3bf9802c8140dbf47560](https://user-images.githubusercontent.com/1000260/54050514-6750b180-41ad-11e9-90b3-cb35738880ea.jpg)

PS: I'm willing to take this on but wanted to make sure I filed an issue before anything. Cheers

**Comment by DSchau** [comment]
Seems reasonable.

@pieh does this make sense to you?

**Comment by joperron** [comment]
Happy Monday guys, I can do this this week if you want, @pieh how would you go about doing it?
