### ISSUE TITLE
WebpackError: ReferenceError: window is not defined - Using Stateful functional component with hooks

### ISSUE THREAD

**Issue by PatrickLambert1101** [gatsbyjs/gatsby#12427]
I am trying to use a hook to determine the size of my window and am getting a build error when deploying to netlify

`  const toggle = () => setToggle(!isToggledOn);
   var windowSize = 900;
   if (window) {
     windowSize = useWindowSize();
   }
   return (
WebpackError: ReferenceError: window is not defined`

Here is my code

`import React, { useState, useEffect } from 'react';
import HeadLogo from './HeadLogo';
import useWindowSize from '@rehooks/window-size';
import TransitionLink from 'gatsby-plugin-transition-link';
import NavbarBrand from './styles/NavbarBrand';
import NavLinks from './styles/NavLinks';
import HamburgerMenu from './HamburgerMenu';
import isEntryExit from './isEntryExit';
import InnerDrop from './InnerDrop';

export default function Navbar() {
  const [isToggledOn, setToggle] = useState(false);
  const toggle = () => setToggle(!isToggledOn);
  var windowSize = 900;
  windowSize = useWindowSize();

  return (
    <nav onClick={toggle}>
      <NavbarBrand>
        <TransitionLink {...isEntryExit} to="/" className="navbar-item">
          <HeadLogo alt="Eat Play Love Logo" />
        </TransitionLink>
        <HamburgerMenu
          isToggle={
            (isToggledOn && windowSize.innerWidth < 800) ||
            windowSize.innerWidth > 800
          }
        />
      </NavbarBrand>
      <NavLinks
        className={
          (isToggledOn && windowSize.innerWidth < 800) ||
          windowSize.innerWidth > 800
            ? 'toggle-open'
            : 'toggle-closed'
        }
      >
        <TransitionLink {...isEntryExit} to="/">
          <div>HOME</div>
        </TransitionLink>
        <InnerDrop />
        <TransitionLink {...isEntryExit} to="/retreats">
          <div> RETREATS</div>
        </TransitionLink>
        <TransitionLink {...isEntryExit} to="/about">
          <div>ABOUT US</div>
        </TransitionLink>
        <TransitionLink {...isEntryExit} to="/contact">
          <div>CONTACT</div>
        </TransitionLink>
      </NavLinks>
    </nav>
  );
}
`

I have seen in other [issues](https://github.com/gatsbyjs/gatsby/issues/309) that set the function in a componentDidMount would solve the issue but that is not possible with hooks. Does anyone have any suggestions?

Thanks so much.

P.S this is my first post to GitHub :) So if I've left anything out of this question please let me know.

**Comment by DanielRuf** [comment]
Did you already try `typeof window !== 'undefined'`?

**Comment by joperron** [comment]
Try this

```
let windowsize = 900
if (typeof window !== 'undefined') {
 windowsize =  useWindowSize();
}
```

**Comment by joperron** [comment]
you probably want to define something closer to the actual object you want to use like:

`let windowsize = { innerWidth: '900' }`

**Comment by universse** [comment]
can you please share your useWindowSize code also?

**Comment by universse** [comment]
based on what you are trying to do, I think it should be something like this
```
function useWindowSize () {
  const [windowSize, setWindowSize] = useState({ innerWidth: 900 })

  useEffect(() => {
    setWindowSize({ innerWidth: window.innerWidth })
  }, [])

  return windowSize
}
```

then in your component
```
const windowSize = useWindowSize()
```

**Comment by sidharthachatterjee** [comment]
Hey @PatrickLambert1101 

The ReferenceError error is occurring because `window` is not available during server side rendering (when `gatsby build` is run)

To fix this, you need to run this code only on the client side. You can do this by calling the hook inside an effect. Depending on your use case, you can use [useEffect](https://reactjs.org/docs/hooks-reference.html#useeffect) or [useLayoutEffect](https://reactjs.org/docs/hooks-reference.html#uselayouteffect)

**Comment by Powell-v2** [comment]
Guys, just a note: 

> You can do this by calling the hook inside an effect

In a (function-based) component, hooks should be called only at the top level. [Doc ref](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level)

**Comment by Powell-v2** [comment]
@PatrickLambert1101 you'd need to adjust the hook itself. Defining default values in the outside scope and using them as default state should do the trick:
```js
let defaultHeight
let defaultWidth

if (typeof window !== `undefined`) {
  defaultHeight = window.innerHeight
  defaultWidth = window.innerWidth
}

const useWindowSize = () => {
  const [dimensions, setDimensions] = useState({
    windowHeight: defaultHeight,
    windowWidth: defaultWidth,
  })

  useEffect(() => {
    const handler = () => setDimensions({
      windowHeight: window.innerHeight,
      windowWidth: window.innerWidth,
    })

    window.addEventListener(`resize`, handler)
    return () => window.removeEventListener(`resize`, handler)
  }, [])

  return dimensions
}
```

**Comment by Siregar** [comment]
> @PatrickLambert1101 you'd need to adjust the hook itself. Defining default values in the outside scope and using them as default state should do the trick:
> 
> ```js
> let defaultHeight
> let defaultWidth
> 
> if (typeof window !== `undefined`) {
>   defaultHeight = window.innerHeight
>   defaultWidth = window.innerWidth
> }
> 
> const useWindowSize = () => {
>   const [dimensions, setDimensions] = useState({
>     windowHeight: defaultHeight,
>     windowWidth: defaultWidth,
>   })
> 
>   useEffect(() => {
>     const handler = () => setDimensions({
>       windowHeight: window.innerHeight,
>       windowWidth: window.innerWidth,
>     })
> 
>     window.addEventListener(`resize`, handler)
>     return () => window.removeEventListener(`resize`, handler)
>   }, [])
> 
>   return dimensions
> }
> ```

This solved my problem.

**Comment by ramadan26** [comment]
@Siregar 
Where should I put this code ?
