### ISSUE TITLE
Is there a way to remove first "/" from resources url?

### ISSUE THREAD

**Issue by alqamabinsadiq** [gatsbyjs/gatsby#12429]
I am trying to generate static webpages from Gatsby and I want to change resource urls in `index.html`.

I want to serve multiple websites from a single CloudFront distribution that's why I want to remove all the prefix `/` from resource url.

I just want to change links in `index.html`  from `/static/js/main.2a85c832.js` to `static/js/main.2a85c832.js` and `/styles.ff6acd2cf49d657974c9.css` to `styles.ff6acd2cf49d657974c9.css`?

Could anyone help? Thanks.

I know we can change configuration in webpack by creating a `gatsby-node.js` file. But it's not working for me.

**Comment by markatli** [comment]
Same question here. Thoughts welcome!

**Comment by sidharthachatterjee** [comment]
Does setting a path prefix solve your issue? 
https://www.gatsbyjs.org/docs/path-prefix/

Separate sites could have different path prefixes and be served from the same CloudFront distribution

**Comment by alqamabinsadiq** [comment]
Yeah, I figured it out using path-prefix. Thanks
