### ISSUE TITLE
Issues with development links

### ISSUE THREAD

**Issue by mattcotter** [gatsbyjs/gatsby#1243]
Hi, 

I'm currently running Gatsby v0.12.48 on a project. I've inititally installed several themes from the docs but all seem to have the same issue. I've read the docs thoroughly and can't seem to locate where the issue is.

Each theme has pages pre-made. Whenever I change the directory name and other details in the .md files (say from 'profile' to 'about'), the links in navigation all of a sudden stop working even though I've changed them in the seemingly appropriate areas. But instead of redirecting them to the newly modified or created directories, I just get a 404 page. I've updated both the markdown files and navigation areas.

It's also worth noting when I build the site, pages seem to work fine. It's only when I have a development server running that I seem to have this issue and was wondering if there was a way to alleviate it.

Can anyone tell me what I'm missing?

**Comment by KyleAMathews** [comment]
Hmmm have you tried stopping and starting again the dev server? There might be state that's not hot reloading.

**Comment by mattcotter** [comment]
Yeah, multiple times. I've even gone as far as to delete my local repo and re-download it from Github, same results on 3 separate machines. My repo is public; it's based off of Gatstrap. 

https://github.com/mattcotter/gatstrap

**Comment by KyleAMathews** [comment]
I only see a link to your home page (`/`) — https://github.com/mattcotter/gatstrap/search?utf8=%E2%9C%93&q=Link&type=

Am I missing something?

**Comment by mattcotter** [comment]
That's maybe my issue, I only have one linkPrefix set up in the 'config.toml' file? I tried setting up individual prefixes and updating in the SiteNavi directory (where the menu is setup) but it renders an error.

This may be a rookie issue, I should have stated that I'm somewhat new to React.

**Comment by KyleAMathews** [comment]
The prefix is only necessary if you're deploying to something like GitHub
pages where all your paths need a prefix. In the Link component, you need
to pass to the "to" prop the path you're linking to just like you would a
href in an A element.

**Comment by mattcotter** [comment]
Yeah and I've done just that. When using gatstrap, /profile is a valid path, but when I change that exact directory's name and update the markdown files for both the SiteNavi and the page its self with the appropriate path, it no longer works. It's as if there's something cached inside the theme's installation but when I clear the cache (browser & npm) I still get the same results. It only accepts the original path from the theme and nothing else, including the modified path or newly created paths. 

This is also the case with other themes, including the default theme & multiple other themes.

**Comment by KyleAMathews** [comment]
Can you visit the page via its new path?

**Comment by mattcotter** [comment]
Aha! I fixed it; in the SiteNavi component, I had changed the className to something different than what was previously in there by mistake. It's working now. Sorry for the confusion. :)
