### ISSUE TITLE
[gatsby-transformer-remark]: support gray-matter sections

### ISSUE THREAD

**Issue by kevindavi5** [gatsbyjs/gatsby#12432]
## Summary

I think it would benefit the gatsby community if gatsby-transformer-remark, (GTR), made use of [gray-matter](https://github.com/jonschlinkert/gray-matter)'s, (GM), `sections` option to create nodes for sections added in markdown. Currently you are allowed to pass any options that GM accepts to GTR, one of them being section?s, `sections` being a boolean and `section` being a function. When `sections: true` GM uses [section-matter](https://github.com/jonschlinkert/section-matter) to parse its section syntax noted here https://github.com/jonschlinkert/section-matter#example. The benefit of this would allow multiple nodes to be queried by file with the ability of passing in unique frontmatter for each section. The problem is that GTR doesn't currently support sections.

### Basic example

The markdown for an About page may look something like this:

```md
---
title: About
---

---1
component: HeroText
link: ipsum dolor
href: http://example.com
---

# About. Lorem Ipsum is simply dummy text of the printing and typesetting industry.

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry.

---2
component: FullHeading
---

## Lorem Ipsum is simply dummy text of the printing and typesetting industry.

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry.

---3
component: FullTwoColumn
link: lorem ipsum
href: http://example.com
spacing: m
---

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry.

Lorem Ipsum is simply dummy text of the printing and typesetting industry.
Lorem Ipsum is simply dummy text of the printing and typesetting industry.
Lorem Ipsum is simply dummy text of the printing and typesetting industry.
```

### Motivation

The motivation for this allows me have a single file with multiple nodes that are consumed independently of each other. In my use case this gives me the ability to target a component, pass in additional frontmatter unique to that component, as well as the htmlAst so that it can be parsed by rehype-react to be styled with components that are created with emotion. 

### Proposed solution

In GTR's [on-node-create.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/on-node-create.js) we first put a wrapper around `markdownNode` to let it create nodes as `createMarkdownNode`, look for sections, parse the data object with yaml, and create the nodes.

```js
...
const createMarkdownNode = data => {
   let markdownNode = {
     id: createNodeId(
       `${data.key ? node.id + data.key : node.id} >>> MarkdownRemark`
     ),
     children: [],
     parent: node.id,
     internal: {
       content: data.content,
       type: `MarkdownRemark`,
     },
   }
  ...
}
const markdownNode = createMarkdownNode(data)

if (data.sections && Object.keys(data.sections).length) {
  data.sections.map(section => {
    if (section.data) {
      section.data = yaml.safeLoad(section.data)
    }
    return section
  })

  data.sections.forEach(section => {
    createMarkdownNode(section)
  })
}

return markdownNode
...
```

My concern is the return of a single markdown node as it is today. If this is creating multiple nodes, should we be returning an array of nodes? is there even a way to return an array of nodes? 

Please let me know your thoughts. This solution has helped me in my use case and I would love for it to help others. With my proposed solution, I'm just not sure if there are any pitfalls.

Thanks for reading 🙏

**Comment by pieh** [comment]
What if GTR would create `MarkdownRemarkSection` nodes that are children of `MarkdownRemark`?

So queries could look like:
```gql
query {
  markdownRemark(frontmatter: { title: { eq: "hello-world" } }) {
    frontmatter {
      title
      date
    }
    sections: childrenMarkdownRemarkSection {
      data {
        component
        link
        href
      }
      htmlAst
    }
  }
}
```

**Comment by kevindavi5** [comment]
@pieh, I'm not opposed to that. I agree with your point that `data` should be `frontmatter`.
