### ISSUE TITLE
gatbsy themes in plugin directory

### ISSUE THREAD

**Issue by oschade** [gatsbyjs/gatsby#12455]
## Summary

I want to place my themes in a local "theme" folder while development like the "plugins"-directory for custom plugins. I tried to place my theme in the plugin-folder, but this does not work.

**Comment by sidharthachatterjee** [comment]
Not sure if this is supported 

cc @ChristopherBiscardi

**Comment by ChristopherBiscardi** [comment]
This is not currently supported.

**Comment by oschade** [comment]
For me, a local theme would be nice for development. Linked packages with "npm link" have some strange behaviour (see: https://github.com/gatsbyjs/gatsby/issues/12002).
But there could be some benefits in the future, too. For example, if you sell a gatsby-theme, you probaby don't want to publish it over npm. How would you bind it to gatsby in a safe way?

**Comment by pieh** [comment]
For theme development you can use `yarn workspaces` - see https://github.com/jlengstorf/livestream-gatsby-themes for example on set this up (in linked youtube video in first few minutes Jason and John go through setting this up initially).

This allows you to develop locally and also let themes actually have their own dependencies. For distribution if you want to sell theme/not publish it to public npm registry then you could use `npm pack`/`yarn pack` to create tarball that users can download and install in their projects.

**Comment by ChristopherBiscardi** [comment]
While we aren't supporting local themes right now, it doesn't mean we never will. The current suggested approach is to use yarn workspaces because other approaches such as `npm link` can have hard to diagnose issues.

**Comment by oschade** [comment]
I did start using gatsby with `yarn workspaces` and it works fine. Thank you for this advice! But for simplicity, a theme-folder would be nice. Thank you for keeping that in mind!
