### ISSUE TITLE
Scroll position not reset when navigating to new page 

### ISSUE THREAD

**Issue by ergunpp** [gatsbyjs/gatsby#12453]
I have taken my site live and the only problem I need to solve is, when scrolling down on a page and navigate to a new page, the newly loaded page is not scrolled to top.
My site is live at chefschoice.com.tr.
Need help! Thank you.

**Comment by sidharthachatterjee** [comment]
Hey @ergunpp 

I can reproduce this on chefschoice.com.tr but not sure what's happening. Can you try to create a minimal reproduction of this? Happy to help!

In the mean time, if you want to _always_ scroll to the top on page change (without remembering scroll position from last view) you can do this in `gatsby-browser.js`:

```
exports.onRouteUpdate = () => {
  window.scrollTo(0, 0)
}
```

**Comment by ergunpp** [comment]
@sidharthachatterjee Hi, the repo is: ergunpp/chefschoice

**Comment by sidharthachatterjee** [comment]
The issue is in https://github.com/ergunpp/chefschoice/blob/d3189752e1e756c54b14a37e8357204a0c5a7ef7/gatsby-browser.js#L20

It's setting __navigatingToLink to false in `onRouteUpdate` and then the condition in `shouldUpdateScroll` always evaluates to false

Side note: I'd highly recommend not to depend on internal values like __navigatingToLink. We might remove it at any point without a semver breaking version since it's an internal API.

**Comment by ergunpp** [comment]
@sidharthachatterjee so, how should I do it? Completely remove it or?

**Comment by pieh** [comment]
I would remove:
```
exports.onRouteUpdate = () => {
  window.__navigatingToLink = false;
};
```
part - not sure what's the purpose of this? But it definitely can cause this problem

**Comment by ergunpp** [comment]
This was part of a script I copied from the forums but it didint work I probably forgot and left it there. But when I remove this it will scroll up to top of the screen even when clicking the back button. Is there a quick and easy way to make it scroll to top when navigating to a new page and scroll it to the last scroll position when navigating back?

**Comment by ergunpp** [comment]
@pieh I completely removed exports.onRouteUpdate and tested, the problem persists.
