### ISSUE TITLE
Keywords meta tag

### ISSUE THREAD

**Issue by mattcdowning** [gatsbyjs/gatsby#12454]
Curious why Gatsby's default starter includes code for the [keywords meta tag](https://github.com/gatsbyjs/gatsby/blob/master/starters/default/src/components/seo.js#L87)? It's presumably included for SEO, but [Google hasn't used the keywords meta tag since 2009](https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html). And [Bing dubbed the keyword tag "dead" in 2014](https://blogs.bing.com/webmaster/2014/10/03/blame-the-meta-keyword-tag). Happy to submit a PR to remove 😀

**Comment by sidharthachatterjee** [comment]
Thank you, @mattcdowning 

I'm definitely no SEO expert so let's keep this open and hear what others have to say about this. On some preliminary searching, it does appear to _not_ be used by Google, Yahoo and Bing.

**Comment by DanielRuf** [comment]
Afaik it is not used by search engines anymore. Only content matters.

**Comment by mattcdowning** [comment]
Anyone else want to chime in here?

**Comment by KyleAMathews** [comment]
Yeah, please remove it. Thanks for noticing!
