### ISSUE TITLE
Grommet Layer component Error

### ISSUE THREAD

**Issue by Ganevru** [gatsbyjs/gatsby#12467]
I have a starter: [gatsby-starter-blog-grommet](https://github.com/Ganevru/gatsby-starter-blog-grommet) based on [grommet](https://github.com/grommet/grommet) - it has an error described here: [gatsby-starter-blog-grommet/issues/4](https://github.com/Ganevru/gatsby-starter-blog-grommet/issues/4)

`Layer` code and what it does: [https://github.com/grommet/grommet/tree/master/src/js/components/Layer](https://github.com/grommet/grommet/tree/master/src/js/components/Layer)

### How to reproduce?

Add <Layer /> (with or without children/props) anywhere in the code, ie:

    <Grommet theme={THEMES[themeByThemeType(themeType)]}>

      <Grommet theme={siteTheme}>

        <Layer />

        <GlobalStyle />

        <Box direction="column" align="center">

        ...

The build will fail with

    error Building static HTML failed for path "/blog/as-you/"

    See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

    24 |     _this = _Component.call.apply(_Component, [this].concat(args)) || this;

    25 | 

    > 26 |     _defineProperty(_assertThisInitialized(_assertThisInitialized(_this)), "originalFocusedElement", document.activeElement);

     | ^

    27 | 

    28 |     _defineProperty(_assertThisInitialized(_assertThisInitialized(_this)), "layerContainer", getNewContainer());
    29 | 

    WebpackError: ReferenceError: document is not defined

    - Layer.js:26 new Layer
    [lib]/[grommet]/es6/components/Layer/Layer.js:26:1

    - bootstrap:22 c
    lib/webpack/bootstrap:22:1

    - bootstrap:25 Sa
    lib/webpack/bootstrap:25:1

    - bootstrap:30 a.render
    lib/webpack/bootstrap:30:1

    - bootstrap:30 a.read
    lib/webpack/bootstrap:30:1

    - bootstrap:42 renderToString
    lib/webpack/bootstrap:42:1

    - static-entry.js:194 Module.default
    lib/.cache/static-entry.js:194:18

    - bootstrap:24 Promise
    lib/webpack/bootstrap:24:1

    - gatsby-browser-entry.js:11 Promise._resolveFromExecutor
    lib/.cache/gatsby-browser-entry.js:11:1

    - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1

    - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1

    - bootstrap:50 MappingPromiseArray._promiseFulfilled
    lib/webpack/bootstrap:50:1

    - api-runner-ssr.js:6 MappingPromiseArray.PromiseArray._iterate
    lib/.cache/api-runner-ssr.js:6:16

    - bootstrap:67 MappingPromiseArray.init
    lib/webpack/bootstrap:67:1

    error Command failed with exit code 1.

On `gatsby develop` everything works as it should, the `<Layer>` component is displayed and works, the problem only occurs when generating the `gatsby build` site.

**Comment by sidharthachatterjee** [comment]
@Ganevru Looks like the `Layer` component is trying to access `document`. 

It is breaking during `build` because document is not available in a non browser environment and therefore server side rendering is failing. `gatsby develop` works because we don't do SSR during develop currently. 

I'd recommend opening an issue in https://github.com/grommet/grommet 

Closing this for now since it isn't related to gatsby but please feel free to comment if we can help with more 🙂
