### ISSUE TITLE
[gatsby-plugin-emotion] old 3.x files published in 4.0.5 build

### ISSUE THREAD

**Issue by wKovacs64** [gatsbyjs/gatsby#12489]
#11482 has struck again.

## Description

`gatsby-plugin-emotion` 4.0.5 is breaking builds where 4.0.4 succeeded. Some old files from 3.x (`gatsby-browser.js`, `gatsby-ssr.js`, and `wrap-element.js`) made it into the published package. These files were originally deleted in #10500.

Compare 4.0.4 to 4.0.5 on unpkg:

https://unpkg.com/gatsby-plugin-emotion@4.0.4/ (correct)
https://unpkg.com/gatsby-plugin-emotion@4.0.5/ (incorrect)

### Steps to reproduce

N/A

### Expected result

I would expect only the current files to be in the corresponding published package.

### Actual result

Additional files (not in the current source tree) are being included in the published package.

### Environment

N/A

**Comment by pieh** [comment]
ugh :/ will re-publish

**Comment by pieh** [comment]
4.0.6 was republished with clean files ( https://unpkg.com/gatsby-plugin-emotion@4.0.6/ )

**Comment by wKovacs64** [comment]
Thanks @pieh!
