### ISSUE TITLE
onPreRouteUpdate and onRouteUpdate when location.search changed

### ISSUE THREAD

**Issue by DevSide** [gatsbyjs/gatsby#12484]
## Description

When the query string changed (location.search), _onPreRouteUpdate_ and _onRouteUpdate_ don't trigger because everything is based on the pathname.

### Actual result
The props location changed in the layout but no _onPreRouteUpdate_/_onRouteUpdate_ happens

### Expected result

Would it make sense to trigger them because prevLocation and location have actually changed ?

### Environment

```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    Yarn: 1.9.4 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 63.0.3
    Safari: 12.0.3
  npmPackages:
    gatsby: 2.1.29 => 2.1.29 
    gatsby-image: 2.0.31 => 2.0.31 
    gatsby-plugin-html-attributes: 1.0.5 => 1.0.5 
    gatsby-plugin-manifest: 2.0.22 => 2.0.22 
    gatsby-plugin-react-helmet: 3.0.8 => 3.0.8 
    gatsby-plugin-remove-trailing-slashes: 2.0.9 => 2.0.9 
    gatsby-plugin-robots-txt: 1.4.0 => 1.4.0 
    gatsby-plugin-sharp: 2.0.25 => 2.0.25 
    gatsby-plugin-sitemap: 2.0.6 => 2.0.6 
    gatsby-plugin-styled-components: 3.0.6 => 3.0.6 
    gatsby-source-filesystem: 2.0.23 => 2.0.23 
    gatsby-transformer-sharp: 2.1.15 => 2.1.15 
```

**Comment by pieh** [comment]
Those are mostly for page changes. `location.search` won't trigger page change or page component re-mounting. But I could see current behaviour being problematic for analytics (not sending url changes after `location.search` changes).

What's Your usecase?

**Comment by DevSide** [comment]
My use case is for functional testing. We implement `onInitialClientRender` to be sure the first render occurred and `onRouteUpdate` to check if the navigation occurred internally to continue safely. We had some trouble where the location address bar was ok but not the transition.

**Comment by pieh** [comment]
Here's the check we use currently (just comparing `window.pathname`) https://github.com/gatsbyjs/gatsby/blob/da4dda45acd9c0c2a42ea91411b477c20c133d0a/packages/gatsby/cache-dir/navigation.js#L146-L153

I think checking `location.search` do make sense there, but it might change some behaviour that people rely on right now - would need to investigate on how impactful change like that would be.

**Comment by DevSide** [comment]
Would you consider a custom option until the next major version ? Or maybe having different hooks like onLocationChange / onPreLocationUpdate ?

**Comment by BPScott** [comment]
Heya folks, Throwing my two cents in here too.

This is throwing off my analytics as page views aren't registered when I navigate to the same path with a different querystring, as @pieh pointed out earlier.

**Comment by pieh** [comment]
> Would you consider a custom option until the next major version ? Or maybe having different hooks like onLocationChange / onPreLocationUpdate ?

You can listen to `@reach/router` history (for example in gatsby-browser.js):
```js
import { globalHistory } from "@reach/router"

globalHistory.listen(({ location }) => {
  console.log("location changed", location)
})
```

**Comment by BPScott** [comment]
@pieh,

Given that `onRouteUpdate` does not change when the only the location changes and modifying this is scary, should `gatsby-plugin-google-analytics` and `gatsby-plugin-google-gtag` both be updated to listen to react-router's globalHistory changing instead of registering an onRouteUpdate handler?

Currently loading `page?foo=1` then navigating to `page?bar=1` does not trigger an analytics event
