### ISSUE TITLE
When using linkImagesToOriginal, images do not render

### ISSUE THREAD

**Issue by wwwhatley** [gatsbyjs/gatsby#12488]
## Description

When adding linkImagesToOriginal to options for gatsby-remark-images, images no longer render.

### Steps to reproduce

- Add linkImagesToOriginal, and set to false in options

### Expected result

Images should appear

### Actual result

Images do not appear

### Environment

  System:
    OS: macOS 10.14.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.121
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.119 => 2.0.119 
    gatsby-background-image: ^0.2.4 => 0.2.4 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-plugin-drift: ^1.0.0 => 1.0.0 
    gatsby-plugin-favicon: ^3.1.5 => 3.1.5 
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17 
    gatsby-plugin-offline: ^2.0.23 => 2.0.23 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20 
    gatsby-plugin-styled-components: ^3.0.5 => 3.0.5 
    gatsby-plugin-typography: ^2.2.7 => 2.2.7 
    gatsby-remark-images: ^3.0.5 => 3.0.5 
    gatsby-source-filesystem: ^2.0.20 => 2.0.20 
    gatsby-transformer-javascript-frontmatter: ^2.0.8 => 2.0.8 
    gatsby-transformer-json: ^2.1.8 => 2.1.8 
    gatsby-transformer-remark: ^2.2.5 => 2.2.5 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13 
  npmGlobalPackages:
    gatsby-cli: 2.4.9

**Comment by pieh** [comment]
I could not reproduce it. Some [reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) is needed I think here - this might be some combination of things.

**Comment by wwwhatley** [comment]
@pieh Here is the repo: 

https://github.com/Catatek/bookhipstr

**Comment by pieh** [comment]
This styling is somehow causing problems - https://github.com/Catatek/bookhipstr/blob/development/src/templates/package.js#L25-L31

If you remove `display: flex` from there, then image shows. Otherwise images have size of 0x0, which is pretty weird
