### ISSUE TITLE
[gatsby-plugin-google-tagmanager] script failed to load with 404

### ISSUE THREAD

**Issue by tmpduarte** [gatsbyjs/gatsby#12492]
## Description

When I add the `gatsby-plugin-google-tagmanager` to my project it tries to load the file with the following url: `https://www.googletagmanager.com/gtm.js?id=AW-XYZCODE `, but the status of the request is 404.
When I compared with the script added by the plugin and the one provided by Google I noticed that the url should be the following: `https://www.googletagmanager.com/gtag/js?id=AW-XYZCODE`. Notice the `/gtm.js?id=` vs `/gtag/js?id=`

### Steps to reproduce

1. Add the `gatsby-plugin-google-tagmanager` 
2. Add the following snippet to your `gastby-config.js` file
```
{
      resolve: 'gatsby-plugin-google-tagmanager',
      options: {
        id: 'AW-861462059'
      }
}
```
3. Run the project in production mode
4. Observe that the request to get the google tag manager script fails with 404:
![Screenshot 2019-03-11 at 15 12 39](https://user-images.githubusercontent.com/1597565/54134619-3623eb80-4410-11e9-82b9-f6f565991712.png)

### Expected result

Google tag manager script is loaded.

### Actual result

![Screenshot 2019-03-11 at 15 12 39](https://user-images.githubusercontent.com/1597565/54134619-3623eb80-4410-11e9-82b9-f6f565991712.png)

### Environment

```
System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.121
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.0 => 2.1.14
    gatsby-image: ^2.0.29 => 2.0.29
    gatsby-link: ^2.0.11 => 2.0.11
    gatsby-plugin-crisp-chat: ^2.1.0 => 2.1.0
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3
    gatsby-plugin-favicon: ^3.1.5 => 3.1.5
    gatsby-plugin-google-analytics: ^2.0.14 => 2.0.14
    gatsby-plugin-google-tagmanager: ^2.0.9 => 2.0.9
    gatsby-plugin-nprogress: ^2.0.8 => 2.0.8
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-robots-txt: ^1.4.0 => 1.4.0
    gatsby-plugin-sharp: ^2.0.21 => 2.0.21
    gatsby-plugin-sitemap: ^2.0.5 => 2.0.5
    gatsby-plugin-styled-components: ^3.0.6 => 3.0.6
    gatsby-source-filesystem: ^2.0.21 => 2.0.21
    gatsby-transformer-sharp: ^2.1.14 => 2.1.14
    gatsby-transformer-yaml: ^2.1.8 => 2.1.8
  npmGlobalPackages:
    gatsby-cli: 2.4.9
```

**Comment by pieh** [comment]
Pretty weird - we are using (for the most part) snippet from https://developers.google.com/tag-manager/quickstart :

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-tagmanager/src/gatsby-ssr.js#L26-L30

which uses `/gtm.js?id=` variant. If this is broken then Google's docs are broken as well?

**Comment by tmpduarte** [comment]
I have been doing some research and seems that google has tag manager and gtag.js (https://support.google.com/tagmanager/answer/7582054?hl=en) and for some reason in my case google suggested I use gtag instead

**Comment by pieh** [comment]
It seems we also have `gtag` plugin that uses this second url ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-gtag/src/gatsby-ssr.js#L71-L75 )

To be honest I'm completely lost what is actual difference between those 2

**Comment by tmpduarte** [comment]
😄 Thank you for the help, I am going to close this issue.

**Comment by birksy89** [comment]
For me, this issue was caused by having an unpublished container:

> "Every time you set up a new Google Tag Manager container, publish it (even though it’s totally empty), otherwise, the response from Google will return 404 not found error."

https://www.analyticsmania.com/post/google-tag-manager-404-error-gtm-js/
