### ISSUE TITLE
Steps to make the existing gatsbyjs site multilingual

### ISSUE THREAD

**Issue by ergunpp** [gatsbyjs/gatsby#12493]
Hi,
I have just finished and taken live 2 sites with gatsbyjs. Both of them are for different petfood brands showcasing a range of products (fetched from contentful via graphql) and have a little static text.
Now I need to make them multilingual (they are in turkish, I need to add english versions). The product data coming from contentful is localized and has already the english translations. I am using aws s3 and cloudfront to serve them.
I hope to be able to automatically serve the english version when the site is called outside of Turkey from a browser with no turkish localization.
How would you recommend to move ahead with the second language?
The project repos are: ergunpp/bestpet and ergunpp/chefschoice.
Thanks for suggestions.

**Comment by ergunpp** [comment]
I am still witing for an input from our great community

**Comment by robinmetral** [comment]
@ergunpp I understand your content is already localized and fetched from Contentful.

Are you looking for information on how to build your site in both English and Turkish, based on your content?

Or did you already manage to do this, and are simply looking for a way to route your users based on their browser settings?

**Comment by ergunpp** [comment]
No my site is only in turkish. I need to add english language

**Comment by robinmetral** [comment]
> arrow_right In this case, a good place to start is the [localization and internationalization docs page](https://www.gatsbyjs.org/docs/localization-i18n/). It goes over different approaches to i18n, from a Gatsby plugin to React libraries, and also links to further resources.

Did these docs help at all? Check out the linked resources at the bottom too :slightly_smiling_face:

**Comment by ergunpp** [comment]
Actually I read it all, what I was looking was a more specific strategy
suggestion.

**Comment by robinmetral** [comment]
If you're after a step-by-step guide to transform the Gatsby default starter into a multilingual site, I don't think we have any, yet.

Looking at the code for the [`gatsby-starter-default-i18n`](https://github.com/angeloocana/gatsby-plugin-i18n/tree/master/packages/gatsby-starter-default-i18n) ([demo](https://gatsby-starter-default-i18n.netlify.com/)) (built with [`gatsby-plugin-i18n`](https://github.com/angeloocana/gatsby-plugin-i18n)) could help!
