### ISSUE TITLE
[fix]: run git clean before publishing

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#12491]
## Description

To avoid issues like #12489, we should bake in support for running `git clean -xfd` before publishing.

This will clean all gitignored files and give a clean slate so we don't have to worry about issues like these popping up again.

## Implementation

We should edit [the `bootstrap` script](https://github.com/gatsbyjs/gatsby/blob/master/package.json#L67) to run `git clean -xfd` before bootstrapping, so that you are always given a clean slate. The publish workflow is currently:

- `yarn bootstrap`
- `yarn run publish`

So baking it into the bootstrap step makes sense. It should be done in the `prebootstrap` script, so that it can be done before actual bootstrap tasks.

Longer term - it'd be nice to move to a CI publish workflow, but we're not quite there yet!

### Steps to reproduce

Publish with an unclean package (e.g. gatsby-plugin-emotion with extraneous files)

### Expected result

Files that should be gitignore'd should be ignored

### Actual result

Files are not gitignored, and misc. files can make their way into a publish

**Comment by pieh** [comment]
I must say that I don't run full `bootstrap` on each publish (just `yarn` to install any packages that changed). This saves a bit of time, because packages are built anyway during publishing.

I would like for this to run automatically before each package `prepare`, but not sure if we can do this nicely:
 - `git clean -xfd` will remove `node_modules` and that's not what we want.
 - and to not repeat this in each package scripts (as that is error-prone) - I'll check if having this centralized in lerna config is somehow possible

**Comment by DSchau** [comment]
@pieh I don't either--but that's technically how we've documented publishing thus far.

I'd happily consider a separate workflow that does the same thing (e.g. just cleaning for _that_ package or something before building would be ideal).

**Comment by pieh** [comment]
Just looking at https://github.com/lerna/lerna/blob/a7ad9b60d27b390fde21fd2837f2d97320c4603e/commands/publish/index.js#L583-L589

We could have `prepublish` script in root package.json that would do cleaning (would "just" need to figure out to not clear `node_modules` at that point).

Other solution - have actual separate script to clean directory in each package, but have script to verify that each package has that script before publishing (and have simple `--fix` option to auto add it if it's not there) - ie:

```
"scripts": {
  "build": "[...]",
  "watch": "[...]"
  "prepare": "[...]",
  "prepublish": "../../scripts/clean-dist-files.sh"
}
```
and clean-dist-files could check `.gitignore` and remove everything that is not node_modules?
