### ISSUE TITLE
Docs: reconfigure search on docs site for contributing, plugins, and starters

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#12503]
## Summary

Some commonly-searched terms come up empty even when there is content for them in a plugin. For example, when searching Google for "Gatsby createFilePath" or "Gatsby robots.txt", one can find plugins for those things ([gatsby-source-filesystem](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createfilepath) and [gatsby-plugin-robots-txt](https://www.gatsbyjs.org/packages/gatsby-plugin-robots-txt/), respectively), but not when searching on Gatsbyjs.org itself. 

It might be helpful to index packages so that Gatsby search results will include things like `createFilePath` and `robots.txt`. This has been asked before: https://github.com/gatsbyjs/gatsby/issues/4028

From talking to the core team, it looks like packages were excluded on purpose; it would be good to understand the reasoning for this, as we determine the best way forward. An alternative would be to add more docs for things like `createFilePath`, but the question then would become "where should plugin-related docs live?"

**Comment by KyleAMathews** [comment]
Were they always excluded? I remember being able to search for packages in the past.

**Comment by marcysutton** [comment]
Looks like it was removed in September 2018, but I'm not sure why: https://github.com/algolia/docsearch-configs/commit/01178d485d238968151d4dddd95d85621737afad

**Comment by marcysutton** [comment]
Something else I just noticed: the new Contributing section isn't indexed either. Do we need to add something to the Algolia search config @DSchau ?

**Comment by jlengstorf** [comment]
I have a call with Algolia later this week — I will figure out how to actually make this fix possible.

**Comment by jackbravo** [comment]
@jlengstorf how did the call with algolia go?

**Comment by jlengstorf** [comment]
@jackbravo that discussion never ended up happening. I'm not sure where this stands; I'll defer to the Gatsby team on what next steps are.

**Comment by LekoArts** [comment]
Since `www` isn't public anymore I've noted this internally as a ticket.
