### ISSUE TITLE
Docs: Restructure tutorial examples to allow automated testing

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#12502]
## Summary

The Gatsby tutorial is a huge part of onboarding and learning experience. To make it more robust, we could find a way to automate testing of the examples. That would hopefully prevent situations like this:

> @jlengstorf: I think we have a bug in the tutorial? 
> https://twitter.com/shinytoyrobots/status/1104639898110300161?s=19
> https://twitter.com/shinytoyrobots/status/1104640202008653824?s=19

There are some potential tools that could help:
- https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-embed-snippet
- https://www.gatsbyjs.org/packages/gatsby-remark-code-repls/
- https://github.com/FormidableLabs/react-live

Ideally, we could refer to an example in our repo for the actual tutorial content. Then, we could author e2e-tests against the tutorial, swapping between the files as needed to assert things.

Also from @jlengstorf:

> If the code was in distinct files, we could at least test that each individual step worked, but that wouldn’t solve the problem of a later step changing and not being reflected in the previous steps.
> But it would be cool if we could do:
```<Example path="/examples/tutorial-name/step-1/gatsby-config.js" />```
> And tests could be written against the `/examples` folder.

### Motivation

It would be super cool if we could write automated tests for the tutorial examples, so that if something stops working due to outdated code or some other change, we'll know about it.

The exact solution is TBD obviously, but it would be awesome to have something more robust in place to ensure a bug in the Tutorial doesn't unexpectedly trip people up.

**Comment by jlengstorf** [comment]
@ChristopherBiscardi’s work in #12514 will likely have a huge impact on our ability to solve this well. It might make sense to table this until we have MDX working, then revisit?

**Comment by LekoArts** [comment]
Since `www` isn't public anymore I've noted this internally as a ticket.

**Comment by karlhorky** [comment]
Ah, too bad, was looking forward to hearing what solution you ended up on!

Would it be possible to get a short post here detailing the solution (redacted for any private information, of course) once the internal ticket has been completed?
