### ISSUE TITLE
[gatsby-plugin-manifest] Don't regenerate unchanged/cached assets

### ISSUE THREAD

**Issue by missmatsuko** [gatsbyjs/gatsby#12506]
## Summary
Create and check a cached hash file. Don't regenerate assets (icons, manifest) unless the hashes actually changed.

### Basic example
On another (non-Gatsby) project, I'm using [app-manifest-webpack-plugin](https://www.npmjs.com/package/app-manifest-webpack-plugin#all-properties) to generate app icons and the app manifest file. It uses a cache file so that files don't get regenerated until the source image and/or data actually changes.

### Motivation
In general, app icons and manifests probably aren't changing that frequently. This plugin adds several minutes to build time on every build when I added it to my Netlify-hosted gatsby site that is based on [gatsby-starter-netlify-cms](https://github.com/netlify-templates/gatsby-starter-netlify-cms).

**Comment by pieh** [comment]
> This plugin adds several minutes to build time on every build

This is super weird. It definitely shouldn't take that long. Are you sure that's this plugin that cause this? I would suspect that this is not manifest plugin, but rather image processing from `gatsby-plugin-sharp`.

Also on netlify `.cache` or `public` directories is not cached between builds. You need https://www.npmjs.com/package/gatsby-plugin-netlify-cache for it.

**Comment by missmatsuko** [comment]
I didn't know about the `gatsby-plugin-netlify-cache` plugin. I'm not sure why, but that `gatsby-starter-netlify-cms` starter deletes public and cache on every build. 

I tried adding the plugin and updating the build script so it doesn't clear out public and cache. Then I tried deploying on Netlify a few times, and it took about 10 minutes each build.

From the deploy details, it looks like the manifest icons are still generated each time, and it takes about 9 minutes:
```
9:48:25 AM: info bootstrap finished - 22.247 s
9:57:08 AM: done generating icons for manifest
```

When I remove `gatsby-plugin-manifest`, the build time was reduced to 52 seconds!

**Comment by missmatsuko** [comment]
Sure, this is my project: https://github.com/missmatsuko/matsuko-ca

It doesn't take so long locally, I was told here that it was because we only have 1 CPU on Netlify: https://github.com/netlify-templates/gatsby-starter-netlify-cms/issues/191#issuecomment-470425337

I could try reducing the size of the source SVG, I'm not sure if that would help. I made it have a large viewbox because very blurry images were produced when a had a small viewbox, even though it's a vector/SVG.

**Comment by moonmeister** [comment]
@missmatsuko I've never seen this plugin run for more that a couple seconds (usually <1s). Doesn't mean it's not causing you troubles, but this is definitely not typical. 

Your troubles aside, this is an excellent suggestion and future i18n support from #13471 makes this more important. We're happy to take a PR to support this from you or anyone who would like to contribute.

**Comment by moonmeister** [comment]
Update: #13471 Implemented some rudimentary caching. This implementation does not work across builds but only in a single build. With the implementation of internationalization it was possible we would be regenerating a single image multiple of time. This caching creates a record of every image it builds and doesn't rebuild if it has already been created during that build cycle. 

For anyone wanting to contribute this we're looking to implement caching across builds. meaning these images wouldn't be recreated every build. only if the src image changed, or the output is changed would we need to regenerate the images.

**Comment by moonmeister** [comment]
@lekoarts is there a reason not stale got removed?
