### ISSUE TITLE
How to directly access YAML/JSON data

### ISSUE THREAD

**Issue by mavam** [gatsbyjs/gatsby#12539]
I am trying to figure out a dead-simple way to reference data in my components. I'm building a simple static site for which GraphQL is a bit overkill. I have my data in `src/data`, in the form of YAML files. What I am looking for is a way to reference this data without `StaticQuery`. Say I have a file `src/data/features.yaml`, I was hoping to be able to do something like this:

```jsx
const Foo = () => (
<Bar>
{
   /* Work with the parsed YAML natively in JS. */
   features.map(...) => (...)
}
</Bar>
```

This fails because `features` is not in global scope. I hope you understand where I'm trying to do, though. All I want is to access the YAML data directly, without going through a long GraphQL expression.

In my `gatsby-config.js`, I have the YAML plugin already configured:

```js
  plugins: [
    'gatsby-transformer-yaml',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: './src/data/',
      },
    },
  ],
```

Apologies if this has been covered in past issues, but I don't know what I'm supposed to look for ( quite yet).

**Comment by krismorf** [comment]
Hi @mavam. There is a section in the docs referring to [using Gatsby without GraphQL](https://www.gatsbyjs.org/docs/using-gatsby-without-graphql/). I suspect this is what you need.

Thanks for using Gatsby 💜

**Comment by mavam** [comment]
Thanks, I actually found this one as well, but couldn't quite get my use case mapped to it. Maybe you can help me fill in the missing pieces. What confused me in this is example is that I don't want to create pages but only make the data available for use in components.

Okay, but let me try to map the Pokemon example to my use case. The function `getPokemonData` will be the one that has side-effects. That is, it will be the one that should load my YAML data. Let's say I figure out how to do this. Then how do I make available the `allPokemon` variable globally? I tried adding something like

```js
const allPokemon = [1, 2, 3];
```

into `gatsby-node.js` and then tried referencing it a component, but the variable name is not known at that point. Would exporting the variable be the missing piece? How do I do that? I looked also at the [Node APIs](https://www.gatsbyjs.org/docs/node-apis/) but couldn't find anything that sounds like what I'm looking for.

I'm coming from the world of static website generators (I used Hugo, Jekyll, Nanoc in the past) where the framework makes it possible to interpolate data variables. I'm sure this is also possible with Gatsby, but it requires a lot more deep understanding of all the pieces to get up and running.

**Comment by jonniebigodes** [comment]
@mavam i have a addition to the documentation that will target that case especifically. It needed some work done. and i put it hold as another pull request i made was simmering and waiting for review and go through. As it was not touched in any shape or form, i'll make the final adjustments till the end of the week and submit it. Do you mind waiting a little longer?

**Comment by pieh** [comment]
> I'm coming from the world of static website generators (I used Hugo, Jekyll, Nanoc in the past) where the framework makes it possible to interpolate data variables. I'm sure this is also possible with Gatsby, but it requires a lot more deep understanding of all the pieces to get up and running.

In gatsby we do that via GraphQL, but if you don't want to use that, you should be able to do `import data from "../file.yaml"` - we do have webpack loader for yaml files

**Comment by pieh** [comment]
As example of it - we use importing yaml in gatsby website - https://github.com/gatsbyjs/gatsby/blob/95155e0338bf8f6ba3bdc6e50d03ef267d4d39c7/www/src/utils/sidebar/item-list.js#L1-L4

**Comment by mavam** [comment]
@pieh. This was exactly what I need. Thanks!
@jonniebigodes I appreciate your offer, but my issue has been solved.

To make my above example work, the only missing piece was adding a single line:

```jsx
import features from '../data/features.yaml'
```
I knew there was a simple way!
