### ISSUE TITLE
Gatsby Image Align Fluid Images Like Background Position

### ISSUE THREAD

**Issue by jonathancary** [gatsbyjs/gatsby#12534]
Basically what I'm trying to do it mimic the effect of background-position for Gatsby Image. On a website I'm building, I'm using fluid for my hero image. The style is to be height: 500px for desktop, however the images are about 800px tall. 

The problem is, some of the images I would like to be position bottom, others centered like normal and some position top. Is there a way to make this possible, I would just crop the photo but the aspect ratio changes on mobile so would really like to figure out a way to make this functionality work. 

I tried messing around with object-fit and object-position, but wasn't able to get it to work. However, I may have been using it wrong.

Thanks for the help!

**Comment by pieh** [comment]
Try something like this:
```
<Img imgStyle={{height: 300, objectPosition: 'bottom'}} fluid={f} />
```
It seems to work here. Just note that IE11 doesn't support `object-position` so this will not work there, but seems to work at least on chrome

**Comment by jonathancary** [comment]
Perfect, thanks!
