### ISSUE TITLE
[gatsby-plugin-offline] Initial load with SW installed causes blank page to appear

### ISSUE THREAD

**Issue by jariz** [gatsbyjs/gatsby#12536]
## Description

If app is loaded from serviceworker, only my layout gets rendered.
After a few seconds of waiting, the page appears.

This happens consistently throughout reloads on all pages.  

This experience is far less superior than the 'normal' non-SW workflow, which immediately shows a page.

See [screen recording here](https://streamable.com/44reh)

I would like to make a minimal reproduction repo, but I have no idea what part of my setup is causing this. A live example is available, however.
If more details are required, I'm on the discord as jari#1337

### Steps to reproduce

- Open `accept[.]oerol[.]nl` (remove brackets around dots, don't want it to get indexed)
- Wait for serviceworker to install
- Refresh
- Just the header and the footer will show up, no page visible for the first few seconds

------

- Hard refresh (cmd+shift+R) / unregister the serviceworker (Chrome DevTools > Application > Serviceworkers)
- Page is visible during initial load.

### Environment

```
  System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.5.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0.1
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.53 => 2.0.67 
    gatsby-plugin-offline: ^2.0.19 => 2.0.19 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.4 
    gatsby-plugin-s3: ^0.2.4 => 0.2.4 
    gatsby-plugin-sitemap: ^2.0.3 => 2.0.3 
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4 
    gatsby-plugin-typescript: ^2.0.3 => 2.0.3 
    gatsby-source-filesystem: ^2.0.12 => 2.0.12 
    gatsby-source-graphql: ^2.0.7 => 2.0.7 
  npmGlobalPackages:
    gatsby-cli: 2.4.6
    gatsby-plugin-graphql-preview: 0.0.0-development
    gatsby-plugin-s3: 0.2.5
    gatsby-starter-default: 1.0.0
```

**Comment by pieh** [comment]
There are couple of things to unpack here:
Current implementation of offline plugin was supposed to serve blank app shell (essentially white page) until js which is cache by service worker is processed/compiled and actually mount react application. The `gatsby-plugin-layout` or directly using `wrapPageElement` (or `wrapRootElement`) is causing this blank page to be wrapped by layout, which cause problems like you described. This should be fixed but problem is, right now we would need to hardcode this `app-shell` page path which is defined in `offline` plugin in either gatsby core or in `gatsby-plugin-layout` to skip wrapping for that page.

There is open pull request to change offline plugin to not serve app shell, but serve actual html ( https://github.com/gatsbyjs/gatsby/pull/11965 ). This requires caution given how much problems we already had with offline plugin.

**Comment by jariz** [comment]
Alright, thanks for the explanation, I sorta understand what's happening now.
I'll close this in favour of #11006, and I'll remove the stale label from there.
