### ISSUE TITLE
Getting Facebook Messenger into site

### ISSUE THREAD

**Issue by danboyle8637** [gatsbyjs/gatsby#12542]
I am thinking about how to get the Facebook Messenger div into my site. 

Here's what it looks like:

```
<div class="fb-customerchat"
  attribution=setup_tool
  page_id="##############"
  theme_color="#21dbec"
  logged_in_greeting="Hi! If you have questions... I'm here"
  logged_out_greeting="Hi! If you have questions... I'm here">
</div>
```

I just hashed out my page id btw.

Initially I was thinking of using setPostBodyComponents in my gatsby-ssr file... 

But the attribution=setup_tool is messing things up because the compiler is looking for setup_tool and it's not found.

I am using Google Tagmanager currently to inject the Facebook SDK script. And that works properly because I am getting my pixel to load on my pages. 

But I don't know of a way to inject a div using Tagmanager. 

Any ideas?

**Comment by pieh** [comment]
You can try something like this:
```
setPostBodyComponents([<div dangerouslySetInnerHTML={{__html: `
<div class="fb-customerchat"
  attribution=setup_tool
  page_id="##############"
  theme_color="#21dbec"
  logged_in_greeting="Hi! If you have questions... I'm here"
  logged_out_greeting="Hi! If you have questions... I'm here">
</div>
`}}>])
```
which will inject html string as is and react should not meddle with it. Downside there is extra wrapping div (`dangerouslySetInnerHTML` need this, last time I checked it didn't work with `React.Fragment`)

**Comment by rzubrycki** [comment]
hey @pieh could you elaborate a little bit more how to implement this code into gatsby?
