### ISSUE TITLE
[www]: Implement testing for www site

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#12545]
## Summary

After discussion during today's Community Meeting, we discussed that it would be good to start working on adding some forms of testing whether it be with Jest or Cypress to test parts of the site as well as the business logic for some pages. This is going to be an open issue to discuss what would be best to implement for the .org site

### Resources

* @DSchau had a example reference that we could use as a base for beginning to add tests to the site: https://github.com/DSchau/gatsby/pull/8
* Kent C Dodds and @jlengstorf did a livestream recently on testing Gatsby Sites: https://www.youtube.com/watch?v=BzRAYt7BHRw

**Comment by marcysutton** [comment]
Love this idea. I would love to see tests added with PRs for bigger site changes, and having a foundation to build on would make that more feasible.

I think a combination of Jest and Cypress tests would be useful; business logic and individual components in Jest as you could test things in isolation, and Cypress for integrating components together and testing overall pages. I would be happy contribute some tests, especially for accessibility in Cypress (focus management, auditing with accessibility test APIs, etc.).

**Comment by lannonbr** [comment]
So @DSchau and I just finished up a pair session on tackling the framework for this.

Some remaining tasks left include the following:

- [ ] add a task to Circle CI to run the www tests
- [ ] create an issue on GitHub to reach out to the community to build unit tests for various components in `www/`

We should have a PR later this week to add this.

As well, it may be useful to have a docs page to possibly describe the toolchain we use for testing and how people can get started adding tests for various components for `www/`

**Comment by lannonbr** [comment]
So the first PR is going to push unit testing with Jest. We haven't started looking to integrate Cypress yet, but I think it is a good idea and likely should belong in a separate PR given they are kinda tackling two fronts

**Comment by ollelauribostrom** [comment]
Nice job, seems like a good approach. I'm definitely up for adding some component tests once this is all set up 🎉
