### ISSUE TITLE
[gatsby-source-shopify] product image localFile is null

### ISSUE THREAD

**Issue by kristojorg** [gatsbyjs/gatsby#12559]
## Description

I have a shopify store with approximately 100 products and associated images. When running `npm run build` I am not seeing any errors, though the request is taking a while. However, when I explore my data in GraphiQL, some of the `localFile` nodes are `null`. These images do exist however, and have valid `originalSrc` urls. 

### Steps to reproduce

1. Store with many products and images
2. Try to query them all

### Expected result

no `null` localFiles

### Actual result

`localFile` was `null`.

### Environment

  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v11.10.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 64.0.2
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.106 => 2.0.106 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-plugin-layout: ^1.0.12 => 1.0.12 
    gatsby-plugin-manifest: ^2.0.15 => 2.0.15 
    gatsby-plugin-offline: ^2.0.22 => 2.0.22 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.19 => 2.0.19 
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4 
    gatsby-source-filesystem: ^2.0.18 => 2.0.18 
    gatsby-source-shopify: ^2.0.11 => 2.0.11 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13 
  npmGlobalPackages:
    gatsby-cli: 2.4.13

**Comment by kristojorg** [comment]
I am investigating if this is an API rate limit on Shopify, or if it is a timeout while downloading files. Either way, the plugin should fail more gracefully and hopefully I'll have a PR for this.

**Comment by kristojorg** [comment]
This appears to have been an issue with ungraceful handling of timeout errors. I'll try to make a PR soon

**Comment by PHironaka** [comment]
@kristojorg  I'm experiencing the same issue with my images.

**Comment by hesselberg** [comment]
Seems to be related here as well? https://github.com/gatsbyjs/gatsby/issues/10347

**Comment by kristojorg** [comment]
I believe it's related. I can work on a fix this weekend or next week. For now I am querying the `originalSrc` in my graphql query and then displaying a standard `img` tag if the `localFile` is `null`.

**Comment by kristojorg** [comment]
See the issue @hesselberg linked for my description of how to fix in source-shopify if you want to make a PR before I get to it

**Comment by PHironaka** [comment]
Anyone able to solve the issue yet? My localfile nodes are still returning null.

**Comment by kristojorg** [comment]
Sorry, I got busy with other work. The issue stems from request timeouts, so the best way I found to solve it temporarily was to develop somewhere with better internet. I also put a block in my code to catch cases where localFile was null, and then I just ignored it bc it only happened when developing and for me it was fine developing with 50% of my images. Hope that helps!
