### ISSUE TITLE
Docs: Storybook - Webpack override documentation

### ISSUE THREAD

**Issue by colbyfayock** [gatsbyjs/gatsby#12550]
## Description

Looks like the webpack override documentation may be out of date, possibly due to it's new release? Running through the steps, the custom webpack configuration example now doesn't properly work.

https://www.gatsbyjs.org/docs/visual-testing-with-storybook/

Simply changing the wrapping method and object definitions as described in Storybook documentation worked: https://storybook.js.org/docs/configurations/custom-webpack-config/#full-control-mode

While at it, might we update that documentation to install storybook to the project locally rather than globally? 🤔

### Steps to reproduce

Assuming Gatsby is installed...
- Run through documentation for adding Storybook "as is": https://www.gatsbyjs.org/docs/visual-testing-with-storybook/
- Running storybook fails

### Expected result

Storybook to compile and load a local server

### Actual result

Fails:
```
info => Loading custom webpack config (full-control mode).

WARN Broken build, fix the error below.
WARN You may need to refresh the browser.

ERR! TypeError: Cannot read property 'module' of undefined
ERR!     at module.exports (/Users/cfayock/Code/dashboard-components/.storybook/webpack.config.js:4:17)
ERR!     at Object.webpack (/Users/cfayock/Code/dashboard-components/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:43:12)
ERR!     at <anonymous>
ERR!     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR!  { TypeError: Cannot read property 'module' of undefined
ERR!     at module.exports (/Users/cfayock/Code/dashboard-components/.storybook/webpack.config.js:4:17)
ERR!     at Object.webpack (/Users/cfayock/Code/dashboard-components/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:43:12)
ERR!     at <anonymous>
ERR!     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR!   stack: 'TypeError: Cannot read property \'module\' of undefined\n    at module.exports (/Users/cfayock/Code/dashboard-components/.storybook/webpack.config.js:4:17)\n    at Object.webpack (/Users/cfayock/Code/dashboard-components/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:43:12)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }
```

### Environment
```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.75
    Firefox: 64.0.2
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.19 => 2.1.19 
    gatsby-image: ^2.0.30 => 2.0.30 
    gatsby-plugin-manifest: ^2.0.20 => 2.0.20 
    gatsby-plugin-offline: ^2.0.24 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.7 => 3.0.7 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-sharp: ^2.0.23 => 2.0.23 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-transformer-sharp: ^2.1.14 => 2.1.14 
```

**Comment by DSchau** [comment]
> Looks like the webpack override documentation may be out of date, possibly due to its new release

Correct - yeah. Looks like you're probably using Storybook@5, and the docs haven't been updated beyond Storybook@4.

Would you be able to take a look at gatsbyjs/gatsby#12350 and validate whether those instructions work for you?

If so - we can get that merged so everyone gets the benefit 🎉 

Thanks for opening this issue!

**Comment by colbyfayock** [comment]
yup, thats exactly what i have 👍 thanks
