### ISSUE TITLE
[gatsby] headComponents can be empty (null or empty array) values

### ISSUE THREAD

**Issue by danielkov** [gatsbyjs/gatsby#12553]
## Description

This is related to #12549 and as discussed in the comments, sanitizing `headComponents` would ensure that plugins that do similar transformations as the one in that issue can assume that all elements are actual components.

### Steps to reproduce

As of now it is possible to call `setHeadComponents` or `replaceHeadComponents` with any values and there are no sanity checks in place.

### Expected result

Empty values (null, empty array) should be filtered out.

### Actual result

Everything gets added.

### Environment

Not environment specific.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this and the pull request @danielkov 👍
