### ISSUE TITLE
Add David Eads' blogpost to blog

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#12563]
David Eads has given us permission to cross-post his blog post on The Ticket Trap on our blog!

We need to:

* Add the blog post text, found at https://www.propublica.org/nerds/the-ticket-trap-news-app-front-to-back-david-eads-propublica-illinois
* Add images. Tweets can be embedded just by pasting the link to the tweet
* Add an analytics tracking pixel _only_ to that one page. First create a ProPublicaTracking component using rehype on [this page](https://github.com/gatsbyjs/gatsby/blob/02d84a366ec86758acfc873cead7380bb58a8506/www/src/templates/template-blog-post.js) and then add <pro-publica-tracking> to the component
* Add his name and [image](https://avatars2.githubusercontent.com/u/634572?s=460&v=4) to authors.yaml
* use `canonicalLink` in the frontmatter
* Use March 18 or later as the date.

Here's an example! https://www.gatsbyjs.org/contributing/blog-and-website-contributions/#contributing-to-the-blog

**Comment by RikoSmith** [comment]
Hello, is it possible to accept this as an issue for Pair Programming? I'm a newcomer to the community and I think it would be good first issue and excellent choice for Pair Programming session

**Comment by calcsam** [comment]
David now suggested it would be easier to have a Q&A session with him, so I'll be doing that!
