### ISSUE TITLE
Generate fully qualified URLs when building

### ISSUE THREAD

**Issue by rhysforyou** [gatsbyjs/gatsby#12567]
## Summary

When building my site, I want the URLs used in things like `Link` components, meta tags, and so on to be fully qualified. That means rather than `/posts/` I'd want `http://example.com/posts/`. This could be achieved by allowing a base URL to be specified in `gatsby-config.js` or with a command line flag.

### Basic example

Given the following component:

```tsx
export default function OpenGraphURLTag() {
  return (
    <Location>
      {({ location }) => (
        <Helmet htmlAttributes>
          <meta property="og:url" content={location.href} />
        </Helmet>
      )}
    </Location>
  )
}
```

I'd want `gatsby build` to generate the following tag in the header:

```html
<meta property="og:url" content="https://example.com/whatever/" />
```

### Motivation

Certain meta tags, like those used for Open Graph metadata and Twitter Cards, require any included URLs to be fully qualified. Right now I'm not sure it's possible to correctly implement these in a Gatsby site.

**Comment by pieh** [comment]
You can do `<meta property="og:url" content={`${domain}${location.href}`} />` and you can specify `domain` however you want - be it in gatsby-config or even hard code

**Comment by rhysforyou** [comment]
This approach worked great for me, thanks!
