### ISSUE TITLE
[help] how do you configure expressJS to visit client-only routes directly?

### ISSUE THREAD

**Issue by nodox** [gatsbyjs/gatsby#12576]
## Summary

I'm trying to setup my gatsby site to handle direct links to [client-only](https://www.gatsbyjs.org/docs/building-apps-with-gatsby/#client-only-routes--user-authentication) routes as mentioned here in the docs. 

> These routes will exist on the client only and will not correspond to index.html files in an app’s built assets. If you’d like site users to be able to visit client routes directly, you’ll need to set up your server to handle those routes appropriately.

While its useful to know that I will need to talk to my server to handle the case of accessing links directly, how exactly would one go about setting this up with an express/node server? How would you tell "gatsby don't handle this, instead forward it to the server"?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
We have this implemented in `gatsby serve` - see https://github.com/gatsbyjs/gatsby/blob/3b3153d410800890c87af25df192136e2a4af97b/packages/gatsby/src/commands/serve.js#L13-L41 (and how it's called with `express`/`router` below that

**Comment by nodox** [comment]
This is helpful! @pieh 

Though am I correct to notice that this assumes the site is served from the express backend? I'm not sure how this would work if my gatsby site is hosted on netlify while talking to an express backend.

**Comment by pieh** [comment]
Oh, I probably didn't understood the use case correctly then. Can you elaborate on how you serve (or want to serve) your application? (I just extracted `express` from it and thought question was how to configure express server)

**Comment by rafcontreras** [comment]
I use gatsby-plugin-express and do not set express router

**Comment by nodox** [comment]
Hey there I was able to get this working using Netlify redirects! Therefore I am going to close this issue @pieh thank you!

**Comment by Bulletninja** [comment]
@nodox would be great if you could share some references to the solution, if you have any.
