### ISSUE TITLE
Add New Post 

### ISSUE THREAD

**Issue by tanvirraj** [gatsbyjs/gatsby#1257]
hey Thanks for great project . 
i am new to static site g. ecosystem . 
want to know how can i add new post

**Comment by KyleAMathews** [comment]
Gatsby doesn't have a specific way to add new posts since it aims to be a fairly generic tool. I'd suggest looking at some of the blog starters to see how they work.

https://github.com/gatsbyjs/gatsby#gatsby-starters

**Comment by haakym** [comment]
Updated link for anyone passing through

https://github.com/gatsbyjs/gatsby/blob/master/v0-README.md#gatsby-starters

Blog example here: https://github.com/gatsbyjs/gatsby-starter-blog/tree/master/src

**Comment by sagakom** [comment]
> hey Thanks for great project .
> i am new to static site g. ecosystem .
> want to know how can i add new post

use contentful you can edit gatbsy starter
