### ISSUE TITLE
Change source url of gatsby-plugin-i18next 

### ISSUE THREAD

**Issue by hesamkaveh** [gatsbyjs/gatsby#12571]
Source url in [this post](https://www.gatsbyjs.org/packages/gatsby-plugin-i18next/#gatsby-starter-i18next) must replace with this:
https://github.com/ikhudo/gatsby-i18n-plugin/blob/HEAD/starters/gatsby-starter-i18next

**Comment by pieh** [comment]
Hey, we use https://github.com/algolia/npm-search to get npm packages with `gatsby-plugin` keyword and get readme from it

It seems like readme in that index is outdated for some reason:
![Screenshot 2019-03-14 at 13 27 37](https://user-images.githubusercontent.com/419821/54356977-39f87d80-465d-11e9-984c-7850fd7a44bf.png)

**Comment by pieh** [comment]
Ohhh - actually, it's not outdated - it just uses relative path and we don't transform it to be relative to your github. Not sure how to solve this easily - but you could change Source url to be absolute, which should workaround this problem
