### ISSUE TITLE
[gatsby-react-router-scroll] Console warnings in production version

### ISSUE THREAD

**Issue by aengl** [gatsbyjs/gatsby#12577]
## Description

When accessing the deployed website with cookies disabled, the console is spammed with the following error when scrolling:

```
app-afd7b45928374abe3ffb.js:1 [gatsby-react-router-scroll] Unable to save state in sessionStorage; sessionStorage is not available.
```

Relevant code lines: https://github.com/gatsbyjs/gatsby/blob/421ec9dba71f8048d5351d6a499b2d0b3df7cbaf/packages/gatsby-react-router-scroll/src/StateStorage.js#L42-L44

### Steps to reproduce

• Go to https://www.gatsbyjs.org/
• Disable cookies and refresh the site
• Open the browser console and scroll

### Expected result

The production website shouldn't be leaking internals and spam the console with warnings. The warnings should only be visible when developing with `gatsby develop`.

### Actual result

Production website shows warnings when scrolling.

### Environment

```
  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 11.11.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.75
    Firefox: 64.0
    Safari: 12.0.3
  npmPackages:
    gatsby: 2.1.30 => 2.1.30 
    gatsby-plugin-google-analytics: 2.0.17 => 2.0.17 
    gatsby-plugin-no-sourcemaps: 2.0.2 => 2.0.2 
    gatsby-plugin-sitemap: 2.0.8 => 2.0.8 
    gatsby-plugin-styled-components: 3.0.7 => 3.0.7 
    gatsby-source-filesystem: 2.0.24 => 2.0.24 
    gatsby-transformer-remark: 2.3.2 => 2.3.2 
```

**Comment by pieh** [comment]
@aengl I'm not sure I totally agree about leaking internals, but I don't oppose to make that conditional and wrap this `console.warn` in `if (process.env.NODE_ENV !== `production`)` - would you be interested in creating Pull Request with that change?

**Comment by aengl** [comment]
@pieh Sure, will do.

**Comment by aengl** [comment]
Let me know if you want the commit or PR name changed, there seem to be some loosely followed naming conventions but I didn't want to make too many assumptions.

**Comment by pieh** [comment]
The PR names itself don't matter much - we only change those to follow conventional commits, so merge commit is later on using them as this is helpful to generate automatic changelog entries. But yours is fine
