### ISSUE TITLE
gatsby-browser onRoutChange in layout?

### ISSUE THREAD

**Issue by dumblole** [gatsbyjs/gatsby#12589]
## Summary
I understand how onRouteChange works for gatsby-browser and I use it to log whenever a user changed page. The problem is is that I want to load in a loading page while the new route is loading like videos or something. I use a layout currently to add footer and header functionality to all my pages and I'm planning on adding my loading page to the layout component. Is there a way to import the onRouteChange to my layout? Are there any better solutions to my problem?  I know onLoad exists for some images but how can I replicate similar functionality with divs?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
We do have `gatsby-plugin-nprogress` plugin that does show loading indicator if page didn't load fast. Reason for not showing this progress immediately is that, this actually decrease "perceived" performance.

But before diving into that - are your pages loading so long that showing videos seems like needed "distraction"? To me long page loading seems like true problem here?

**Comment by dumblole** [comment]
I understand what you are trying to say. Thanks for showing the plugin. The pages aren't loading very long its just that one of my images doesn't use the lazy loading that gatsby-image utilizes and wish that the user sees the whole image instead of it loading layer by layer.

**Comment by sidharthachatterjee** [comment]
@dumblole It isn't possible to use the `gatsby-browser` hooks including onRouteUpdate and onRouteUpdateDelayed in your components and I suppose this is a pretty specific use case. 

You could manipulate the DOM yourself in `gatsby-browser` like the gatsby-plugin-nprogress plugin does in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-nprogress/src/gatsby-browser.js

Closing this for the moment but please feel free to comment or reopen if we can help further. Thank you for using Gatsby!
