### ISSUE TITLE
Bug when access directly to client-only page. Works using navigate()

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#12587]
Hello
Guys, you have to save me please.

I have client-only pages in my app. 
I have this in my `gatsby-node.js` :

```
  if (page.path.match(/^\/page-account/)) {
    page.matchPath = `/account/*`;
    createPage(page);
  }
```

When I navigate using `<Link to="/account">` or `navigate("/account")`, my page `account` is loaded fine 👍 

But when I tried to access directly by typing in the address bar `/account` —  it's redirects me to "/", so I never reached this page. It's like page doesn't exist...

Why ? How to solve that please?

```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.0 => 2.0.118 
    gatsby-cli: ^2.4.6 => 2.4.9 
    gatsby-image: ^2.0.26 => 2.0.29 
    gatsby-plugin-emotion: ^4.0.1 => 4.0.3 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.6 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.20 
    gatsby-source-filesystem: ^2.0.12 => 2.0.20 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.13 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by pieh** [comment]
You need server side rewrites (because your hosting isn't aware of `/account/` path. This is mentioned in https://www.gatsbyjs.org/docs/building-apps-with-gatsby/#client-only-routes--user-authentication

> These routes will exist on the client only and will not correspond to index.html files in an app’s built assets. If you’d like site users to be able to visit client routes directly, you’ll need to set up your server to handle those routes appropriately.

What are you using for hosting?

**Comment by Steffi3rd** [comment]
But does I need client-only route.

What I only trying do to is is : 
- Nested url like `/account/settings`, `/projects/:projectName`
- And the content of these pages are generated (or filled) using `fetch(...)` `setState...`
- And one of these pages requires `token` doesn't exist redirect to `/login` 

It's seems weird we can do that with gatsby, even with React it works.

I'm using free Netilfy

**Comment by Steffi3rd** [comment]
The things is on `yarn develop`, everything works! Even on refresh.
But on `yarn serve`, it fails when access directly or reload a client-only route.

**Comment by pieh** [comment]
Please add `gatsby-plugin-netlify` to your config - this should fix accessing client only paths directly on netlify

**Comment by Steffi3rd** [comment]
:O !!!! OMG let me try this...

**Comment by Steffi3rd** [comment]
@pieh I added but not yet deploy on Netlify. I tried before using `yarn serve` and it's doesn't, is it normal?

**Comment by sidharthachatterjee** [comment]
> Automatically generates a _headers file and a _redirects file at the root of the public folder to configure HTTP headers and redirects on Netlify.

@Steffi3rd Yes, as mentioned in the documentation, `gatsby-plugin-netlify` will create redirects and headers files for you. These will let Netlify set up the appropriate redirects so that you reach the client side routes correctly. 

They won't have any effect locally using `yarn serve`

Marking this as answered and closing for now but please feel free to comment or reopen if you still see this.

**Comment by pieh** [comment]
For `yarn serve` you would need to update `gatsby` version. We adjusted `gatsby serve` in `gatsby@2.1.7` to handle client only paths

**Comment by Steffi3rd** [comment]
Thanks!!! @pieh @sidharthachatterjee

**Comment by Steffi3rd** [comment]
Hello, 

Works well on desktop but On smartphone I still have the problem for client only route.

When I tried to access it to client only route from smartphone (Safari or Chrome), I have a white screen.

Why?
