### ISSUE TITLE
[1.0] Fail gracefully if window.sessionStorage is unavailable

### ISSUE THREAD

**Issue by scottyeck** [gatsbyjs/gatsby#1258]
Currently using `1.0.0-beta.5`

Via browser settings, if you block sites from setting any data, disable cookies, etc., `window.sessionStorage` is unavailable. The following error is thrown:

![fabric_-_life_insurance_and_new_issue_ _gatsbyjs_gatsby](https://user-images.githubusercontent.com/3766777/27547917-5dab275e-5a65-11e7-8ce5-4cb998f82572.jpg)

Verified in both Chrome 58.0.3029.110 and Safari 10.0.3.

The error is coming from _react-router-scroll_ but is apparently linked to _history_ where it's been fixed in `3.x`. Relevant:

- https://github.com/ReactTraining/history/issues/397
- https://github.com/taion/react-router-scroll/issues/60

**Comment by KyleAMathews** [comment]
Hmmm we use history 4.x where it should be fixed?

**Comment by scottyeck** [comment]
Oops you're right - was looking at `package.json` from _master_ rather than _1.0_.

Hmm interesting... Will do some thinkin on this one to try to diagnose. FWIW, `window.serviceWorker.register` is also unavailable and the `'serviceWorker' in navigator` check passes since the browser supports it. Food for thought if nothing else.

**Comment by KyleAMathews** [comment]
@scottyeck lemme know if this is still a problem but it seems outdated now.
