### ISSUE TITLE
Exclude .gitkeep from gatsby-source-filesystem scan

### ISSUE THREAD

**Issue by DevSide** [gatsbyjs/gatsby#12580]
## Description

Exclude .gitkeep from gatsby-source-filesystem scan

### Expected result
No File node for .gitkeep files

### Actual result
A File node is created for each .gitkeep

**Comment by pieh** [comment]
`.gitkeep` is convention but is not really a formal standard, so I don't really want to put this in global ignore list.

But you can add this yourself:

```
{
  resolve: `gatsby-source-filesystem`,
  options: {
    path: `${__dirname}/some-path/`,
    ignore: [`**/.gitkeep`], // ignore .gitkeep files
  }
}
```

**Comment by sidharthachatterjee** [comment]
@DevSide Marking this as answered and closing for now but please feel free to comment or reopen if there is anything else we can help with
