### ISSUE TITLE
Cannot query field "localFile" with prismic.io

### ISSUE THREAD

**Issue by immbudden** [gatsbyjs/gatsby#12594]
## Description

I am very new to react and have been working on my first gatsby site for a client. Having previously used `gatsby-image` to compress and serve images uploaded in prismic.io CMS - I had a version working using 2.0.0-alpha.5 of `gatsby-source-prismic`. I am using prismic.io as the CMS for the news section of the site. 

Project has been on hold for a month and after making a few changes and adding a fresh deploy today it is throwing errors where my graphql `localFile` query was previously working. 

Three things that could have caused the issue (from what I can see) are;

- `gatsby-source-filesystem` was updated from `2.0.1-rc.6` to `2.0.25`
- `gatsby-source-prismic` was updated from `2.0.0-alpha.5` to `2.2.0`
- Gatsby was upgraded (can't see what version but vaguely remember)

### Steps to reproduce

run `gatsby-develop` on latest deployment

You can see the project at : https://github.com/immbudden/Lanyon 

### Expected result

Site should generate all images using `childImageSharp` and static site should be rendered

### Actual result

Following errors are thrown:

- `348:33  error    Cannot query field "localFile" on type "featuredImage_2"  graphql/template-strings`
- `311:21  error    Cannot query field "localFile" on type "headlineImage_2"  graphql/template-strings`

### Environment

System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash

  Binaries:
    Node: 8.6.0 - ~/.nvm/versions/node/v8.6.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.6.0/bin/npm

  Languages:
    Python: 2.7.10 - /usr/bin/python

  Browsers:
    Chrome: 72.0.3626.121
    Safari: 12.0.3

  npmPackages:
    gatsby: ^2.0.33 => 2.1.34
    gatsby-image: ^2.0.0-rc.4 => 2.0.34
    gatsby-paginate: ^1.0.17 => 1.0.17
    gatsby-plugin-emotion: ^3.0.1 => 3.0.1
    gatsby-plugin-favicon: ^3.1.5 => 3.1.5
    gatsby-plugin-google-analytics: ^2.0.17 => 2.0.17
    gatsby-plugin-react-helmet: ^3.0.5 => 3.0.9
    gatsby-plugin-sharp: ^2.0.16 => 2.0.29
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.7
    gatsby-plugin-typography: ^2.2.2 => 2.2.10
    gatsby-remark-embed-video: ^1.7.0 => 1.7.1
    gatsby-remark-responsive-iframe: ^2.0.8 => 2.1.1
    gatsby-source-filesystem: ^2.0.1-rc.6 => 2.0.27
    gatsby-source-prismic: ^2.0.0-alpha.5 => 2.2.0
    gatsby-transformer-remark: ^2.1.15 => 2.3.4
    gatsby-transformer-sharp: ^2.1.9 => 2.1.17
  npmGlobalPackages:
    gatsby-cli: 2.4.12

Not sure whether this is a gatsby issue or package issue but thought this would be the best place to ask!

**Comment by pieh** [comment]
In your `gatsby-config.js` in `gatsby-source-prismic` you have this section:
https://github.com/immbudden/Lanyon/blob/master/gatsby-config.js#L113-L121

and because you never do `return true` there - it means that images are never downloaded and therefore `localFile` is not available. Just putting `return true` should fix this

**Comment by immbudden** [comment]
@pieh - you're a star, that's worked a treat!

Thank you!
