### ISSUE TITLE
[1.0] using-remark example: link to PDF only opens correctly when reloading the updated URL

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#1259]
On https://using-remark.gatsbyjs.org/copy-linked-files-intercepting-local-links/#copying-linked-files, when clicking on the "Creative Commons Informational Flyer.pdf" link, the URL gets updated but the PDF is only displayed when reloading.

If I recall correctly, this is the same that once happened with the link to the original image for the images generated by `gatsby-remark-responsive-image`, but I can't track down the fix. :(

**Comment by KyleAMathews** [comment]
Fixed by https://github.com/gatsbyjs/gatsby/pull/1260

**Comment by KyleAMathews** [comment]
Thanks for the bug report! Example sites are awesome for surfacing stuff like this.
