### ISSUE TITLE
Gatsby-plugin-sitemap should remove the trailing slash of siteUrl

### ISSUE THREAD

**Issue by rnitta** [gatsbyjs/gatsby#12590]
## Summary

If you have such config file as:

```js
module.exports = {
  siteMetadata: {
    siteUrl: `https://exmaple.com/`,

```

then, the generated sitemap will be like:

```js
...
<url> <loc>https://example.com//path</loc> <changefreq>daily</changefreq> <priority>0.7</priority> </url>
<url> <loc>https://example.com//</loc> <changefreq>daily</changefreq> <priority>0.7</priority> </url>
...
```

So the plugin should do something avoid generating double-slashed url.

### Motivation

https://github.com/gatsbyjs/gatsby/blob/9298fa374736aa9a88941b3de5b5dfd916bbfd3c/packages/gatsby-plugin-sitemap/src/internals.js#L28

As you can see here, the all paths has a prefixed slash.
But it is not so obvious for users, so the plugin should remove the siteUrl's trailing slash for users' convenience, so as not to their sitemaps have double slash path like `https://example.com//path`

**Comment by pieh** [comment]
This does make sense. I think that adjusting query result handler - https://github.com/gatsbyjs/gatsby/blob/9298fa374736aa9a88941b3de5b5dfd916bbfd3c/packages/gatsby-plugin-sitemap/src/internals.js#L13-L32

and adding:
```js
r.data.site.siteMetadata.siteUrl = withoutTrailingSlash (r.data.site.siteMetadata.siteUrl)
```

does make sense - would you be interested in opening Pull Request with that change?
