### ISSUE TITLE
pages-manifest[chunk].js should be cacheable / renamed, otherwise every single page' html get's changed on every build. Causing huge deploy upload times on netlify for example.

### ISSUE THREAD

**Issue by supermoos** [gatsbyjs/gatsby#12591]
## Summary

pages-manifest[chunk].js get's generated on each build, so if I add a single page, then the chunk name changes, and because every single page*.html file has an inline reference to this page-manifest[chunk].js file, then every single page*.html file get's a new checksum / content, even though nothing changed in those files besides the file reference. This causes netlify to re-upload all those files, in our current site (3200 pages) this takes 20 minutes sometimes for netlify to process.

I also can't find documentation on what pages-manifest.js is even used for? Seems like it could become a huge overhead to lazyload a file referencing every single page for big sites, what if we had 20000 pages? 

### Motivation

Drastically improve subsequent builds where only a single page may have changed.

**Comment by pieh** [comment]
See https://github.com/gatsbyjs/gatsby/issues/11982 for more details - we are aware of it (and that it doesn't scale very well)

**Comment by sidharthachatterjee** [comment]
Thank you for opening this and the detailed summary, @supermoos 

As @pieh mentioned, this is being discussed in https://github.com/gatsbyjs/gatsby/issues/11982

Marking this as a duplicate and closing this issue but please feel free to follow along in the linked issue!
