### ISSUE TITLE
linkPrefix option not working?

### ISSUE THREAD

**Issue by arnoldstoba** [gatsbyjs/gatsby#126]
When I run gatsby build with an "linkPrefix" option set in the config.toml file, the generated html files do not contain any link prefix at all. I tried it with the gatsby-starter-blog repo and it did not work there either.
Any information on this?
[Image link](https://i.gyazo.com/02297de855a887eb911b1d3ab5ae5495.png)

**Comment by GU5TAF** [comment]
Did you run your build with the prefix links option like this `gatsby build --prefix-links` as shown [here](https://github.com/gatsbyjs/gatsby#deploying-to-github-pages-and-other-hosts-where-your-sites-links-need-prefixes)?

**Comment by arnoldstoba** [comment]
Thank you @GU5TAF. I did not know that option existed. Solved my problem.

**Comment by GU5TAF** [comment]
Glad to hear it @arnoldstoba!
I myself was stumped by this for quite some time, feels counterintuitive that it isn't applied automatically when it's specified in the config.
