### ISSUE TITLE
[gatsby-source-wordpress] Multi-site config looses data 

### ISSUE THREAD

**Issue by sarahannnicholson** [gatsbyjs/gatsby#12608]
## Summary

I am running into an issue where `gatsby-source-wordpress` is merging content from both of my WordPress configs. This is resulting in a loss of content. So I was wondering, **is there a way, in a multi site WordPress config, to specify which site you are querying?**
By 'multi-site WordPress config' I mean, two gatsby-source-wordpress definitions in the `gatsby-config.js` where each WP config goes to a different baseUrl (or WP site)

## Relevant information

I have two WordPress sites (lets call them, wpSite1 and wpSite2). I am attempting to get menus from both sites. So my `gatsby-config.js` has something like this in it:
<pre>        
{
            resolve: `gatsby-source-wordpress`,
            options: {
                baseUrl: wpSite1,
                protocol: `http`,
                hostingWPCOM: false,
                useACF: true,
                includedRoutes: [
                     "**/pages",
                     "**/posts",
                     "**/menus",
                     "**/media"
                ],
                verboseOutput: true
            },
        },
        {
            
            resolve: `gatsby-source-wordpress`,
            options: {
                baseUrl: wpSite2,
                protocol: `http`,
                hostingWPCOM: false,
                useACF: true,
                includedRoutes: [
                    "**/posts",
                    "**/tags",
                    "**/menus",
                    "**/media"
                ],
                verboseOutput: true
            },
        },
</pre>

So I went ahead and created some menus in my WP. The rest responses are as follows:
Full response form wpSite1
**https://{wpSite1}/wp-json/wp-api-menus/v2/menus**
<pre>
[
{
	"term_id": 81,
	"name": "menu2",
	"slug": "menu2",
	"term_group": 0,
	"term_taxonomy_id": 81,
	"taxonomy": "nav_menu",
	"description": "",
	"parent": 0,
	"count": 3,
	"filter": "raw",
	"ID": 81,
	"meta": {...}
},
{
	"term_id": 84,
	"name": "menu3",
	"slug": "menu3",
	"term_group": 0,
	"term_taxonomy_id": 84,
	"taxonomy": "nav_menu",
	"description": "",
	"parent": 0,
	"count": 1,
	"filter": "raw",
	"ID": 84,
	"meta": {...}
}
]
</pre>

response sample from wpSite2
**https://{wpSite2}/wp-json/wp-api-menus/v2/menus** 
<pre>
[
...
{
	"term_id": 81,
	"name": "menu1 - Portuguese (Brazil)",
	"slug": "menu1-portuguese-brazil",
	"term_group": 0,
	"term_taxonomy_id": 81,
	"taxonomy": "nav_menu",
	"description": "",
	"parent": 0,
	"count": 0,
	"filter": "raw",
	"ID": 81,
	"meta": {...}
},
{
	"term_id": 82,
	"name": "menu1 - Russian",
	"slug": "menu1-russian",
	"term_group": 0,
	"term_taxonomy_id": 82,
	"taxonomy": "nav_menu",
	"description": "",
	"parent": 0,
	"count": 0,
	"filter": "raw",
	"ID": 82,
	"meta": {...}
},
{
	"term_id": 83,
	"name": "menu1 - Spanish",
	"slug": "menu1-spanish",
	"term_group": 0,
	"term_taxonomy_id": 83,
	"taxonomy": "nav_menu",
	"description": "",
	"parent": 0,
	"count": 0,
	"filter": "raw",
	"ID": 83,
	"meta": {...}
},
{
	"term_id": 84,
	"name": "menu1 - Spanish, Mexico",
	"slug": "menu1-spanish-mexico",
	"term_group": 0,
	"term_taxonomy_id": 84,
	"taxonomy": "nav_menu",
	"description": "",
	"parent": 0,
	"count": 0,
	"filter": "raw",
	"ID": 84,
	"meta": {...}
}
...
]
</pre>

Then when building Gatsby, we first initialize wpSite1 
<pre>
=== [ Fetching wordpress__wp_api_menus_menus ] === {wpSite1}/wp-json/wp-api-menus/v2/menus
source and transform nodes=== [ Fetching wordpress__wp_api_menus_menus_items ] === {wpSite1}/wp-json/wp-api-menus/v2/menus/81
source and transform nodes -> wordpress__wp_api_menus_menus_items fetched : 1
Fetching the wordpress__wp_api_menus_menus_items took: Xms
=== [ Fetching wordpress__wp_api_menus_menus_items ] === {wpSite1}/wp-json/wp-api-menus/v2/menus/84
source and transform nodes -> wordpress__wp_api_menus_menus_items fetched : 1
Fetching the wordpress__wp_api_menus_menus_items took: Yms
 -> wordpress__wp_api_menus_menus fetched : 2
</pre>

then wpSite2
<pre>
=== [ Fetching wordpress__wp_api_menus_menus ] === {wpSite2}/wp-json/wp-api-menus/v2/menus
...
Fetching the wordpress__wp_api_menus_menus_items took: Tms
=== [ Fetching wordpress__wp_api_menus_menus_items ] === {wpSite2}/wp-json/wp-api-menus/v2/menus/81
source and transform nodes -> wordpress__wp_api_menus_menus_items fetched : 1
Fetching the wordpress__wp_api_menus_menus_items took: Ums
=== [ Fetching wordpress__wp_api_menus_menus_items ] === {wpSite2}/wp-json/wp-api-menus/v2/menus/82
source and transform nodes -> wordpress__wp_api_menus_menus_items fetched : 1
Fetching the wordpress__wp_api_menus_menus_items took: Vms
=== [ Fetching wordpress__wp_api_menus_menus_items ] === {wpSite2}/wp-json/wp-api-menus/v2/menus/83
source and transform nodes -> wordpress__wp_api_menus_menus_items fetched : 1
Fetching the wordpress__wp_api_menus_menus_items took: Wms
=== [ Fetching wordpress__wp_api_menus_menus_items ] === {wpSite2}/wp-json/wp-api-menus/v2/menus/84
source and transform nodes -> wordpress__wp_api_menus_menus_items fetched : 1
Fetching the wordpress__wp_api_menus_menus_items took: Xms

...
</pre>

The build succeeds. Then I open `http://localhost:8000/___graphql` and try to query for my menus in wpSite2

<pre>
  allWordpressWpApiMenusMenus{
     edges{
       node{
         name
         wordpress_id
       }
     }
   }
</pre>

Only my menus from wpSite2 are there. 
If I query for any of my woSite1 menus by ID (eg allWordpressWpApiMenusMenus (filter: { wordpress_id: {eq: 81}}){  ) I see the menu from wpSite2
<pre>
{
  "data": {
    "allWordpressWpApiMenusMenus": {
      "edges": [
        {
          "node": {
            "name": "menu1 - Portuguese (Brazil)",
            "wordpress_id": 81
          }
        }
      ]
    }
  }
}
</pre>

This behavior makes sense from my experience and readings. If two objects have the same id (and likely other logic) only one is returned cause gatsby-source-wordpress is using the wordpress id to make the node id. 

### Questions
1. Is this the intended way to setup a multi-site config for WordPress in Gatsby?
2. Is there a way to split things by site? (nodes or queries or something) so that the id's being the same isn't an issue for the system 
3. Could I do something with [node creation](https://www.gatsbyjs.org/docs/node-creation/) or [onCreateNode](https://www.gatsbyjs.org/docs/node-apis/#onCreateNode) to try to solve this?

To me, this is a pretty major problem. My problem is just menus, but I'm sure the situation is the same for any post type in WP.

### File contents (if changed)

`gatsby-config.js`: Relevant information above
`package.json`:
<pre>
{
  "name": "myapp",
  "description": "A website",
  "author": "me",
  "version": "0.1.0",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.app/unit-testing\""
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.15",
    "@fortawesome/free-brands-svg-icons": "^5.7.2",
    "@fortawesome/free-regular-svg-icons": "^5.7.2",
    "@fortawesome/free-solid-svg-icons": "^5.7.2",
    "@fortawesome/react-fontawesome": "^0.1.4",
    "bootstrap": "^4.3.1",
    "dotenv": "^7.0.0",
    "gatsby": "^2.1.34",
    "gatsby-image": "^2.0.33",
    "gatsby-plugin-create-client-paths": "^2.0.5",
    "gatsby-plugin-manifest": "^2.0.24",
    "gatsby-plugin-offline": "^2.0.25",
    "gatsby-plugin-react-helmet": "^3.0.9",
    "gatsby-plugin-robots-txt": "^1.4.0",
    "gatsby-plugin-sass": "^2.0.11",
    "gatsby-plugin-sharp": "^2.0.28",
    "gatsby-plugin-sri": "^1.0.6",
    "gatsby-source-filesystem": "^2.0.26",
    "gatsby-source-wordpress": "^3.0.46",
    "gatsby-transformer-sharp": "^2.1.17",
    "jquery": "^3.3.1",
    "node-sass": "^4.11.0",
    "popper.js": "^1.14.7",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-helmet": "^5.2.0",
    "react-responsive": "^6.1.1"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "devDependencies": {
    "autoprefixer": "^9.5.0",
    "gatsby-plugin-postcss": "^2.0.6"
  }
}
</pre>
`gatsby-node.js`: Choosing to omit, could supply if requested 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
Probably `gatsby-source-wordpress` is just not ready to support more than single site at a time. Most likely there is `id` collision (one site overriding data from the other site).

Most likely this could be done in here:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/normalize.js#L179-L190

We would need to use some identifier of site when producing new `id`s. Probably site url on top of `type` and `wordpress_id`.
