### ISSUE TITLE
Page not found with gatsby-plugin-remove-trailing-slashes installed

### ISSUE THREAD

**Issue by CodeAndWeb** [gatsbyjs/gatsby#12627]
## Description

First rendering with `gatsby develop` is ok and all pages work. After changing a page I get a warning about `A page wasn't found for "/studio"` and an error `TypeError: undefined is not an object (evaluating 'dev404Page.componentChunkName')` in root.js

The only thing that helps is restart gatsby develop.

The issue seems to be somehow related to `gatsby-plugin-remove-trailing-slashes` - without it everything is fine.

I tried to reproduce the issue in a clean project but was not yet able to... so I am somehow lost where to start to look for a solution. Any ideas?

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v11.6.0/bin/yarn
    npm: 5.10.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.0 => 2.1.37
    gatsby-image: ^2.0.5 => 2.0.34
    gatsby-link: ^2.0.1 => 2.0.16
    gatsby-plugin-canonical-urls: ^2.0.12 => 2.0.12
    gatsby-plugin-emotion: ^4.0.3 => 4.0.6
    gatsby-plugin-htaccess: ^1.1.1 => 1.1.1
    gatsby-plugin-manifest: ^2.0.2 => 2.0.24
    gatsby-plugin-matomo: ^0.5.1 => 0.5.1
    gatsby-plugin-offline: ^2.0.5 => 2.0.25
    gatsby-plugin-postcss: ^2.0.5 => 2.0.7
    gatsby-plugin-purgecss: ^3.1.0 => 3.1.0
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.10
    gatsby-plugin-react-svg: ^2.0.0 => 2.1.0
    gatsby-plugin-remove-trailing-slashes: ^2.0.10 => 2.0.10
    gatsby-plugin-sass: ^2.0.1 => 2.0.11
    gatsby-plugin-sharp: ^2.0.5 => 2.0.29
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.10
    gatsby-remark-component: git+https://git@github.com/CodeAndWeb/gatsby-remark-component.git#b6249395f0979f1667db1da9934532f4c96eb23b => 1.1.3
    gatsby-source-filesystem: ^2.0.1 => 2.0.27
    gatsby-transformer-remark: ^2.2.5 => 2.3.4
    gatsby-transformer-sharp: ^2.1.1 => 2.1.17
  npmGlobalPackages:
    gatsby-cli: 2.4.16

The `gatsby-remark-component` is my own version which has some console.log() output disabled compared to the official 1.1.3

**Comment by Undistraction** [comment]
@CodeAndWeb FWIW We found `gatsby-plugin-remove-trailing-slashes ` to be really problematic, especially in production and had to remove it. Depending on your server, it may or may not treat urls with no trailing slash as directories which can cause issues.

**Comment by CodeAndWeb** [comment]
Ok - found the issue...

The problem was that I mixed markdown pages and .js pages in the same `pages` folder.

        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: "markdown-pages",
                path: `${__dirname}/src/pages`,
            },
        },

I don't know what exactly is happening but after moving the .md files to pages-md and using this as a source everything now works as expected.
