### ISSUE TITLE
React-animate-on-scroll

### ISSUE THREAD

**Issue by mouhsnimohamed** [gatsbyjs/gatsby#12623]
I'm using react-animate-on-scroll package for animating blocks on scroll, it woks great on develop env but not on production env! I don't know why? Is there someone who can help me to fix this problem pls.
https://github.com/dbramwell/react-animate-on-scroll/issues/52

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @mouhsnimohamed 

Could you link to the repository or make a minimal reproduction? That will help in debugging this!

**Comment by mouhsnimohamed** [comment]
Hi,

Its actually when i'm using **pathPrefix**(gatsby build --prefix-paths)  and in my gatsby-config.js I have **pathPrefix: "/next"**

If I just do gatsby build it works great as in **DEVELOP** ENV
