### ISSUE TITLE
Scope to become a maintainer 

### ISSUE THREAD

**Issue by strongSoda** [gatsbyjs/gatsby#12637]
Is there a well defined path by following which a contributor will be added as a maintainer for this project?

**Comment by gurpreet-hanjra** [comment]
I think when you start contributing and first PR is merged, you will be added as maintainer.

**Comment by sidharthachatterjee** [comment]
@strongSoda You will be invited as a member automatically once your first PR is merged! In case you're not sure where to start, we have documentation on how to get started at https://www.gatsbyjs.org/contributing/where-to-participate

Closing this for now but would love to have you as a Gatsby contributor and we'll look forward to your first contribution!
