### ISSUE TITLE
Babel Preset Env Doesn't Work Correctly When Using 'entry'

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#12640]
## Description

As discussed in https://github.com/gatsbyjs/gatsby/issues/12399, Gatsby uses `babel-preset-env` with `useBuiltins` set to `usage`. This means it adds polyfill imports for the chosen browser range when required. However, it doesn't do this for any node_modules that are used, so if a node module needs a polyfill that hasn't been added via 'usage', the polyfill will be missing at runtime.

One potential way of dealing with this is to tell Gatsby to use 'entry' instead. This should mean that an `import @babel/polyfill` will be replaced by all polyfills for the required browser range. This at least would mean any node_modules would be guaranteed to be polyfilled.

However it appears that at present Gatsby doesn't support usage of `useBuiltIns: 'entry'`. When overriding Gatsby's babel-config to enable this (and setting `debug` to `true`), the polyfill is only intermittently replaced by imports. Much of the time it appears this process doesn't happen at all. Leading to the whole of `@babel/polyfill` being included.

### Steps to reproduce

Pull https://github.com/Undistraction/babel-issues (based on Gatsby's default starter)
Run either `gatsby develop` or `gatsby build`. Note this might run the first time or first few times, but will not work consistently.

### Expected result

You should see console output of babel listing the replaced polyfills.

### Actual result

This only happens intermittently, even when using `gatsby clean` to ensure there are no build artifacts from previous builds.

Using `source-map-explorer` you can see all the polyfills are added after build:

<img width="769" alt="Screenshot 2019-03-18 at 10 49 41" src="https://user-images.githubusercontent.com/161489/54525210-97e1d980-496b-11e9-94d0-4d1099cb1c18.png">

### Workaround

Because this doesn't work consistently, there is an implicit workaround of the whole of `@babel/polyfill` being included.

### Environment

```
  System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.8.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.31 => 2.1.31 
    gatsby-image: ^2.0.33 => 2.0.33 
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.9 => 3.0.9 
    gatsby-plugin-sharp: ^2.0.28 => 2.0.28 
    gatsby-source-filesystem: ^2.0.24 => 2.0.24 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.15
```

**Comment by DSchau** [comment]
@Undistraction sorry that this has gotten a little stale--this seems to still be an issue.

I am not super familiar with the `useBuiltIns` option, but it doesn't seem like this would necessarily solve the issue you're trying to solve, which is conditionally loading polyfills for code that babel doesn't know about (`node_modules`).

> This option enables a new plugin that replaces the statement import "@babel/polyfill" or require("@babel/polyfill") with individual requires for @babel/polyfill based on environment

The confusing part here is _based on environment_. I'm presuming it respects browserslistrc files, but it's a little unclear exactly how that works. This feature working as I'd expect would be able to conditionally load additional polyfills based on a browserlist file (e.g. if targeting IE9, more polyfills should be loaded than if targeting >0.25%).

Also:

> However it appears that at present Gatsby doesn't support usage of useBuiltIns: 'entry'. When overriding Gatsby's babel-config to enable this (and setting debug to true), the polyfill is only intermittently replaced by imports

We're just using tools here (e.g. babel, webpack, etc.). I think it's unlikely this is a Gatsby problem **however** I do think it is a problem that we don't enable this option with our babel-preset. My guess here is the random behavior is due to caching, e.g. babel caches its config and other content in `node_modules/.cache/babel-loader` if I remember correctly.

**Comment by Undistraction** [comment]
@DSchau Sorry for the delayed reply. You were right on the money - it appeared that babel was failing to replace the imports, but it had already done so in a previous build and cached the result.

This means that using `entry` does work correctly with Gatsby!

This means that #12409 is valid, and I think it would be useful.

> In terms of improving things I think it would be great if babel-preset-gatsby exposed:
> 
> useBuiltIns so that a developer can opt to use entry instead of usage.
> debug so that a developer can clearly see what polyfills and transforms are being applied.
> I'd be happy to put a PR together adding these two config params.

**Comment by wardpeet** [comment]
@Undistraction this one seems fixed right?

**Comment by Undistraction** [comment]
@wardpeet unfortunately not. Gatsby doesn't provide a hook that is early enough to add the import so that it is expanded prior to all plugins. Using `gatsby-browser.js` is no good as it can load the Polyfills after plugins' own `gatsby-browser.js` files were loaded. One example of where this is problematic is with React and React DOM which can end up with problens relating to the symbol polyfill. The only way using entry could work reliably is if Gatsby provided a place to define the import before the `gatby-browser.js` files of all plugins were loaded.

**Comment by wardpeet** [comment]
What about using https://www.gatsbyjs.org/packages/gatsby-plugin-compile-es6-packages/ would this work for you in the meantime?

**Comment by Undistraction** [comment]
@wardpeet Thanks for the suggestion. That is a viable approach if you know which packages need to be transpiled, but I don't think it's very scalable, especially when it comes to nested dependencies.

I've ended up adding all the polyfills that would have been added by using `entry` to a local plugin's `gatsby-browser.js` which I include first of all the plugins in `gatsby-config.js`. That way I can be sure they are loaded before any other plugins. It's a dirty solution and means my Polyfills are no longer added dynamically based on my browser list, but it is the only solid solution I've found

**Comment by wardpeet** [comment]
@Undistraction it's on our list to experiment with babel compiling node_modules. We just want to make sure it doesn't slow down perf.

**Comment by Undistraction** [comment]
Not stale ol' Gatsby. Still not possible to reliably use `entry`, and the workaround of specifying individual packages to transpile is a poor one.

**Comment by JustFly1984** [comment]
not stale gatsbot
@blainekasten can you please elaborate?

currently every build time I see the same warning: 
```
warn
  When setting `useBuiltIns: 'usage'`, polyfills are automatically imported when
needed.
```
<img width="428" alt="Screenshot 2020-04-08 21 33 55" src="https://user-images.githubusercontent.com/2255993/78796570-b4bad600-79e0-11ea-95eb-01966099ecb6.png">
