### ISSUE TITLE
[www]: GuessJS not preloading expected routes

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#12651]
## Description

Recently, GuessJS support was added to gatsbyjs.org (see: #12351).

This seems to have worked, but doesn't seem like the preloading is working as we'd expect.

### Steps to reproduce

1. Go to [gatsbyjs.org](https://gatsbyjs.org)
1. Open up the console
1. Inspect errors as you click around, e.g.
    > A page wasn't found for "/grafeno/bem-vindo/"
    > A page wasn't found for "/docs/configurando-ambiente/"

### Expected result

Pages that are pre-fetched are _actual_ pages.

### Actual result

It appears that the pages that are pre-fetched are not being sourced correctly from Google Analytics.

## Further Details

In looking at the implementation in the PR, not really clear where this went wrong. The correct env vars were exposed to the container, so perhaps it's an issue in the plugin?

cc @wardpeet

**Comment by sidharthachatterjee** [comment]
Looks like this was fixed by @wardpeet in https://github.com/gatsbyjs/gatsby/pull/12658
