### ISSUE TITLE
need demo to combine with mdx and gatsby-transformer-remark

### ISSUE THREAD

**Issue by wulucxy** [gatsbyjs/gatsby#12656]
## Summary

my first blog just use `gatsby-transformer-remark` to convert `markdown` files，and now i want to add some interactivity，so I think `gatsby-mdx` is a good choice。actually `gatsby-transformer-remark` does't have some plugins to support mdx。so how can I use both 
`gatsby-transformer-remark` and `gatsby-mdx`?

### Environment (if relevant)

gatsby-v2

### File contents (if changed)

`gatsby-config.js`: N/A 

```
module.exports = {
  plugins: [
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          `gatsby-remark-katex`,
          {
            resolve: `gatsby-remark-autolink-headers`,
            options: {
              className: 'post-toc-anchor',
            },
          },
          {
            resolve: `gatsby-remark-images`,
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 320,
            },
          },
          'gatsby-remark-use-jsx',
          {
            resolve: 'gatsby-remark-prismjs',
            options: {
              classPrefix: 'gatsby-code-',
            },
          },
        ],
      },
    },
  ],
}
```

`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
@wulucxy Can you elaborate on why you would like to use both `gatsby-transformer-remark` and `gatsby-mdx` at the same time? If you need to use gatsby-remark plugins with mdx you can do so as documented in https://gatsby-mdx.netlify.com/api-reference/options/gatsby-remark-plugins/

Here is an example config to get you started:
```
{
  resolve: `gatsby-mdx`,
  options: {
    gatsbyRemarkPlugins: [
      {
        resolve: `gatsby-remark-images`,
        options: {
          // It's important to specify the maxWidth (in pixels) of
          // the content container as this plugin uses this as the
          // base for generating different widths of each image.
          maxWidth: 590,
        },
      },
    ],
  },
},
```

**Comment by erikdstock** [comment]
@wulucxy I agree that it isn't necessary to combine these but I have some tutorial PRs doing just that linked here: https://github.com/erikdstock/gatsby-starter-ts-mdx
