### ISSUE TITLE
Bug when access directly to client-only route : BLANK PAGE (on smartphone ONLY)

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#12661]
Hello guys

You helped to solve client route only not accessible on build. I needed `gatsby-plugin-netlify`.

It works on desktop, but on mobile/smartphone when I tried to access my website, is turns as a blank page few seconds after loading. Some page is blank page by default.

Why? How to solve that please?
 
```
   System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.0 => 2.0.118 
    gatsby-cli: ^2.4.16 => 2.4.16 
    gatsby-image: ^2.0.26 => 2.0.29 
    gatsby-plugin-emotion: ^4.0.1 => 4.0.3 
    gatsby-plugin-netlify: ^2.0.12 => 2.0.12 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.6 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.20 
    gatsby-source-filesystem: ^2.0.12 => 2.0.20 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.13 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by sidharthachatterjee** [comment]
@Steffi3rd Could you link to a minimal reproduction of this? Just tried it out and it seems to work fine for me. Did you check the console for any thrown error or warning?

**Comment by Steffi3rd** [comment]
https://v2.edgebase.com

You can check the bug here.

**Comment by jonniebigodes** [comment]
@Steffi3rd just opened the url in a old iphone 4s using wireless and nothing wrong there, tried it once more with 3g, same result. Grabbed another phone this case a galaxy s9. Same tests, same results. All loads instantly. Nothing blank there.

**Comment by Steffi3rd** [comment]
Thanks @jonniebigodes, really weird... I’ll try to upload videos to show you

**Comment by Steffi3rd** [comment]
Here, when we click on item after typing in the search input (yeah responsive not done yet)


https://imgur.com/a/WIj9Dda

**Comment by sidharthachatterjee** [comment]
@Steffi3rd Can you inspect the console on the mobile device and see if it throws anything?

**Comment by Steffi3rd** [comment]
I don’t know how to see console log on iPhone X

Homepage works fine because it on client route only. 

But company pages are client only like this one are blank : https://v2.edgebase.com/company/social-cloud

**Comment by sidharthachatterjee** [comment]
@Steffi3rd https://v2.edgebase.com/company/social-cloud is blank on desktop for me as well

**Comment by jonniebigodes** [comment]
@Steffi3rd i'm thinking that the problem is not actually with gatsby. The problem stems from a whole diferent place.
I'm getting a 500 error in there, could be the source of it.
This is the errror:
![stepphierderror](https://user-images.githubusercontent.com/22988955/54832688-8e7ea700-4cb4-11e9-9030-b74dda161b1f.png)

**Comment by Steffi3rd** [comment]
SORRY guys, wrong example they delete the company...

On this : https://v2.edgebase.com/company/teads

**Comment by DSchau** [comment]
@Steffi3rd just tried to reproduce and was unable.

I am guessing one of your dependencies (e.g. in node_modules) may have some code that's not transpiled that is crashing the browser. It would seem to be specific to the company page?

If you have an iOS device (and a Mac) you should be able to [attach a debugger](https://appletoolbox.com/2014/05/use-web-inspector-debug-mobile-safari/) which will let you inspect the console to see what the error is.
