### ISSUE TITLE
[gatsby-image] Images rendered with `gatsby-image` "blink" in and out of the page

### ISSUE THREAD

**Issue by SammyIsra** [gatsbyjs/gatsby#12676]
## Description

Images that are rendered with `gatsby-image` seem to not always be present on the page. In Chrome v72, the images seem sometimes loading in and out of the page, while maintaining their position. The images also are not placed where they are supposed to, as seen in the same page rendered in other browsers.

The issue does not happen if no `gatsby-image` is used, and instead a plain old `<img /> tag is used instead: https://www.sammyis.me/photographer 

The images that blink in and out seem to change if you reduce the horizontal space of the page.

### Platform

- This seem to happen only in Chrome Version 72.0.
- Using Windows 10, but can't verify if it happens anywhere else.

### Steps to reproduce

The image links are loaded from a personal endpoint and then downloaded using `gatsby-plugin-remote-images`, which then go thru `gatsby-plugin-sharp` and `gatsby-transformer-sharp` (all normal steps as described in here: https://www.gatsbyjs.org/packages/gatsby-image/)

When the images are loaded to the page, they seem to 'blink' in and out.

### Expected result

Images should first load a low resolution image and then fully render the final image when it is loaded.

### Actual result

Images blink in place, sometimes never rendering the full image. The images that blink in and out seem to not be placed where they are supposed to, if you compare them to how the page renders in other browsers. 

### Environment

`gatsby info --clipboard` seems to not work, so I just copied the results of running the command without `--clipboard`:
```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
Binaries:
    Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - ~\AppData\Roaming\npm\npm.CMD
Browsers:
    Edge: 42.17134.1.0
npmPackages:
    gatsby: ^2.1.23 => 2.1.23
    gatsby-image: ^2.0.34 => 2.0.34
    gatsby-plugin-react-helmet: ^3.0.8 => 3.0.8
    gatsby-plugin-remote-images: 1.0.1 => 1.0.1
    gatsby-plugin-sharp: ^2.0.29 => 2.0.29
    gatsby-plugin-styled-components: ^3.0.6 => 3.0.6
    gatsby-plugin-typography: ^2.2.8 => 2.2.8
    gatsby-source-filesystem: 2.0.23 => 2.0.23
    gatsby-transformer-remark: ^2.3.1 => 2.3.1
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17
```

Additionally: 
- Node v11.10.0
- Chrome v72

### Example

https://deploy-preview-10--optimistic-goodall-a71eb1.netlify.com/photographer/ (scroll down to the first row of images)

### Relevant files

Commit where it is happening: https://github.com/SammyIsra/SammyPortfoliov2/tree/3dff3785b3037c73c2e61d9966dcad85c1c5d7d5

- `gatsby-config.js`: https://github.com/SammyIsra/SammyPortfoliov2/blob/3dff3785b3037c73c2e61d9966dcad85c1c5d7d5/gatsby-config.js 
- `gatsby-node.js`: https://github.com/SammyIsra/SammyPortfoliov2/blob/3dff3785b3037c73c2e61d9966dcad85c1c5d7d5/gatsby-node.js
- File where the images are loaded: 
  - GraphQL query: https://github.com/SammyIsra/SammyPortfoliov2/blob/3dff3785b3037c73c2e61d9966dcad85c1c5d7d5/src/pages/photographer.js#L95
  - Using `gatsby-image`: https://github.com/SammyIsra/SammyPortfoliov2/blob/3dff3785b3037c73c2e61d9966dcad85c1c5d7d5/src/pages/photographer.js#L90

**Comment by coreyward** [comment]
I can confirm the effect is present in the provided Netlify demo using Chrome 72.0.3626.121 on Mac OS.

Video demonstrating: https://media.giphy.com/media/1msHufSJWODw1g5jfM/giphy.mp4

**Comment by coreyward** [comment]
After looking a little closer, this is almost certainly not related to Gatsby image. The reason it's appearing on the top images in the second and third column is because you're using `column-count` (i.e. text column wrapping) and your images are relatively sized. The flashing is happening when the image gets shifted back into the prior column before it overflows and gets redrawn at the top of the column you're expecting it in, where the cycle begins again as a result of your mouse cursor remaining over the image.

If you'd like this style of layout, check out [React Masonry Component](https://github.com/eiriklv/react-masonry-component) or a similar [masonry](https://masonry.desandro.com/) layout library.

**Comment by SammyIsra** [comment]
@coreyward thank you! Your answer clued me into using a `fixed` query instead of a `fluid` one. That mostly solved my issue, but not I am facing a new one where the images are zoomed in the container. However, I don't think that may be in the scope of this issue anymore, thank you very much!
