### ISSUE TITLE
createRemoteFileNode can't deal with special characters

### ISSUE THREAD

**Issue by gu-stav** [gatsbyjs/gatsby#12684]
## Description

In some cases `localFile` was null, when pulling media from wordpress.

### Steps to reproduce

I ran into the issue, while working with gatsby-source-wordpress:

```js
export const fragment = graphql`
  fragment imageTextCombination on WordPressAcf_imageTextCombination {
    image {
      localFile {
        childImageSharp {
          fluid(maxWidth: 500) {
            src
            srcSet
          }
        }
      }
    }
  }
`;
```

In some cases `image.localFile` was `null` which made me wonder. After some time I found out, that the difference in the files appeared to be an `ä` (a german Umlaut), which is currently not normalized by default in wordpress.

Installing a plugin to normalize fileNames on upload fixed the issue.

I think the root of the issues comes from here:

https://github.com/gatsbyjs/gatsby/blob/1257a225de0bb3be8314ecc5684d1c6635d3ee05/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L344-L348

I've checked `valid-url` and added a test:

```js
t.ok(is_uri('http://localhost/ä'), 'http://localhost/ä');
```

which would fail.

### Expected result

`image.localFile` should contain the file and not care about the fileName at all. I'm not sure whether I'm right on this, that's why I opened an issue instead of an PR. What do you think?

### Actual result

`image.localFile` is null.

### Environment

```
  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 11.11.0 - /usr/local/bin/node
    Yarn: yarn install v0.21.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 47.06s. - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    gatsby: ^2.2.1 => 2.2.1
    gatsby-image: ^2.0.34 => 2.0.34
    gatsby-link: ^2.0.16 => 2.0.16
    gatsby-plugin-react-helmet: ^3.0.10 => 3.0.10
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1
    gatsby-plugin-sharp: ^2.0.29 => 2.0.29
    gatsby-plugin-styled-jsx: ^3.0.5 => 3.0.5
    gatsby-source-filesystem: ^2.0.27 => 2.0.27
    gatsby-source-wordpress: ^3.0.47 => 3.0.47
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

**Comment by coreyward** [comment]
@tsimons wrote this code, perhaps he can shed some light.

**Comment by sidharthachatterjee** [comment]
Thank you for pointing this out @gustavpursche 

Just took a look at the code for the `valid-url` package that we use. The regular expression here seems to be the issue 
https://github.com/ogt/valid-url/blob/8d1fc52b21ceab99b68f415838035859b7237949/index.js#L62

A great next step would be to open an issue in that repository and maybe a failing test. We can then hear what the author has to say and get it resolved. Would you like to an open an issue in https://github.com/ogt/valid-url/issues?

**Comment by gustavpursche** [comment]
@sidharthachatterjee I think you are right. After reading a bit about the difference of IRI and URI today, I also think the regex shouldn't be part of the authors `is_iri` function.

However - the author hasn't replied to any issues since 2015 or commited anything since then. Similar issues are open already, so maybe the only thing that could convince him is, that Gatsby is so popular. I'll try :)

**Comment by gustavpursche** [comment]
@gatsbyjs-read-only-user Not stale.

**Comment by gustavpursche** [comment]
Hi there again. Thanks to the bot reminder: the author of the lib didn't respond (since 2015). I think the whole module could be small enough to inline the code. What do you think?

The other solution could be to fork the project and rework the code based on the actual specs and to publish it as a new npm module.

**Comment by domemvs** [comment]
@gustavpursche could you tell me what plugin you used to normalize the filenames? Thanks a lot!

**Comment by gustavpursche** [comment]
@domemvs Sure! It's called "[Clean Image Filenames](https://wordpress.org/plugins/clean-image-filenames/)".

**Comment by domemvs** [comment]
Thank you, that was quick!

**Comment by daniloef** [comment]
Hi! Do you know a plugin that "clean" the filenames of uploaded images?

**Comment by KyleAMathews** [comment]
https://www.npmjs.com/package/sanitize-filename looks like a good one

**Comment by gabrielloeb** [comment]
Begging for mercy since I don't understand the fullness of what's happening inside gatsby-source-filesystem, but can the change made in #15835 be applied directly to that plugin? I'm experiencing the same issue with gatsby-source-prismic, and I presume other source plugins are falling (or will fall) victim to this issue. Is there any reason not to attempt to sanitize urls before abandoning them with a message to the console?

```
wrong url: https://images.prismic.io/redacted/b56f83c2-73e9-4be7-bb53-0792209c74df_CarréTopHandleMini_.jpg?auto=compress,format
```

**Comment by yann-yinn** [comment]
I've got this "wrong url" error a lot of times, i have a source containing some filenames with accents (èéàù...). What would be the best work around to not break the whole build because of those filenames ?

**Comment by yann-yinn** [comment]
I had the same issues with filenames from a S3 bucket with accented characters:

example of a problematic filename `téléphonefixe.jpg`
error message : 

```sh
here was an error in your GraphQL query:

Unexpected error value: "url passed to createRemoteFileNode is either missing or not a proper web uri: (...)-téléphonefixe.jpg" 
```

I tried to use encodeURI 

```js
          return createRemoteFileNode({
            url: encodeURI(source.image.url),
            store,
            cache,
            createNode,
            createNodeId,
            reporter
          });
```

but then got another error because resulting filename seems to be rightly encode (double encoded ?):

`t%25C3%25A9l%25C3%25A9phonefixe.jpg`

It supposed to be `t%C3%A9l%C3%A9phonefixe.jpg` ...

**Comment by uded** [comment]
I am not sure if it is related, but I do have a problem importing MediaItems into Gatsby:

```
 ERROR

UNHANDLED REJECTION Unexpected token W in JSON at position 6664



  SyntaxError: Unexpected token W in JSON at position 6664

  - JSON.parse

  - process-node.js:915 processNode
    [gatsby-source-wordpress-npm-5.1.0-43be09dcc8-39192b6008.zip]/[gatsby-source-wordpress]/src/steps/source-nodes/create-nodes/process-node.js:915:17

  - create-nodes.js:42
    [gatsby-source-wordpress-npm-5.1.0-43be09dcc8-39192b6008.zip]/[gatsby-source-wordpress]/src/steps/source-nodes/create-nodes/create-nodes.js:42:12

  - index.js:163 run
    [p-queue-npm-6.6.2-b173c5bfa8-e95a48f421.zip]/[p-queue]/dist/index.js:163:29


not finished source and transform nodes - 5510.440s
not finished  gatsby-source-wordpress  fetching nodes - 5510.380s - 42043 total
not finished  gatsby-source-wordpress  creating nodes - 2470.510s
not finished  gatsby-source-wordpress  MediaItem - 2470.512s - fetched 6628
not finished Downloading remote files - 1994.564s
```

I googled and checked multiple solutions I've found, but I still can't get it to work. On top of that this one is rather hard to debug and find the root cause as I have ~45.000 images to import...

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
