### ISSUE TITLE
gatsby-plugin-canonical-urls query params and hash

### ISSUE THREAD

**Issue by MarkSalabutin** [gatsbyjs/gatsby#12709]
Could you let me know why you added `location.hash` and `location.search` to canonical url? I faced with a problem that search engines treat pages `example.com/page` and `example.com/page?search=query` as different, but in practice, they are the same.

**Comment by sidharthachatterjee** [comment]
From what I understand `location.hash` is ignored by most search engines and `location.search` should be included because its values often represent unique pages.

**Comment by MarkSalabutin** [comment]
But what about cases when `location.search` don't represent unique page? For example, `fbclid` which facebook add to every external link. If canonical URL includes that parameter search engine will treat this URL as a different page.

**Comment by sidharthachatterjee** [comment]
@MarkSalabutin That’s a fair. We could add options to configure this, I suppose. Would you like to pick this up?

**Comment by Ehesp** [comment]
@MarkSalabutin @sidharthachatterjee just submitted a PR for this as I also ran into this issue. Would be good to get feedback.

**Comment by LekoArts** [comment]
fixed by https://github.com/gatsbyjs/gatsby/pull/13339
