### ISSUE TITLE
Error Building static HTML failed for path "/home/"

### ISSUE THREAD

**Issue by antonioc57** [gatsbyjs/gatsby#12706]
Hello, I have the error when I run the build, error has failed for the path, I have no idea where this error occurs.

```
error Building static HTML failed for path "/home/"

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

   7 | 
   8 |   if (isProduction) {
>  9 |     throw new Error(prefix);
     | ^
  10 |   } else {
  11 |     throw new Error(prefix + ": " + (message || ''));
  12 |   }

  WebpackError: Invariant failed
  
  - tiny-invariant.esm.js:9 invariant
    [lib]/[tiny-invariant]/dist/tiny-invariant.esm.js:9:1
  
  - history.js:250 createBrowserHistory
    [lib]/[history]/esm/history.js:250:115
  
  - react-router-dom.js:29 new BrowserRouter
    [lib]/[react-router-dom]/esm/react-router-dom.js:29:41
  
  - bootstrap:22 c
    lib/webpack/bootstrap:22:1
  
  - bootstrap:25 Sa
    lib/webpack/bootstrap:25:1
  
  - bootstrap:30 a.render
    lib/webpack/bootstrap:30:1
  
  - bootstrap:30 a.read
    lib/webpack/bootstrap:30:1
  
  - bootstrap:42 renderToString
    lib/webpack/bootstrap:42:1
  
  - static-entry.js:194 Module../.cache/static-entry.js.__webpack_exports__.default
    lib/.cache/static-entry.js:194:18
  
  - bootstrap:24 Promise
    lib/webpack/bootstrap:24:1
 
  - gatsby-browser-entry.js:19 Promise._resolveFromExecutor
    lib/.cache/gatsby-browser-entry.js:19:9
  
  - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1
  
  - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1
  
  - bootstrap:50 MappingPromiseArray._promiseFulfilled
    lib/webpack/bootstrap:50:1`
```

**Comment by frank3stein** [comment]
I get a similar error for the path "/404/", which I have not modified. This happened after running npm update and only in npm run build.

<pre><font color="#CC0000">error</font> Building static HTML failed for path &quot;<b>/404/</b>&quot;

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

 <font color="#555753">  8 | </font>	<font color="#06989A">else</font>
 <font color="#555753">  9 | </font>		root[<font color="#4E9A06">&quot;lib&quot;</font>] <font color="#C4A000">=</font> factory(root[<font color="#4E9A06">&quot;@reach/router&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;core-js/modules/es6.array.iterator&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;core-js/modules/es6.array.sort&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;core-js/modules/es6.function.name&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;core-js/modules/es6.map&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;core-js/modules/es6.object.assign&quot;</font>]<font color="#C4A000">,</font> root[&quot;<font color="#4E9A06">core-js/modules/es6.object.to-string&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;core-js/modules/es6.regexp.constructor&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;core-js/modules/es6.regexp.split&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;core-js/modules/es6.regexp.to-string&quot;</font>]<font color="#C4A000">,</font><font color="#C4A000"> root</font>[<font color="#4E9A06">&quot;core-js/modules/es6.string.ends-with&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;core-js/modules/es6.string.iterator&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;core-js/modules/web.dom.iterable&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;crypto&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;fs&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;lodash&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;path&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;react&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;react-dom/server&quot;</font>]<font color="#C4A000">,</font> root[<font color="#4E9A06">&quot;react-helmet&quot;</font>])<font color="#C4A000">;</font>
<font color="#EF2929"><b>&gt;</b></font><font color="#555753"> 10 | </font>})(<font color="#06989A">this</font><font color="#C4A000">,</font> <font color="#06989A">function</font>(__WEBPACK_EXTERNAL_MODULE__reach_router__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_array_iterator__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_array_sort__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_function_name__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_map__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_object_assign__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_object_to_string__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_regexp_constructor__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_regexp_split__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_regexp_to_string__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_string_ends_with__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_es6_string_iterator__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_core_js_modules_web_dom_iterable__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_crypto__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_fs__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_lodash__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_path__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_react__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_react_dom_server__<font color="#C4A000">,</font> __WEBPACK_EXTERNAL_MODULE_react_helmet__) {
 <font color="#555753">    | </font> <font color="#EF2929"><b>^</b></font>
 <font color="#555753"> 11 | </font><font color="#06989A">return</font> 


  <span style="background-color:#CC0000"><font color="#EEEEEC">WebpackError</font></span><span style="background-color:#CC0000"><font color="#D3D7CF">: </font></span><span style="background-color:#CC0000"><font color="#EEEEEC">Invariant Violation: Minified React error #130; visit https://reactjs.org/</font></span>  <span style="background-color:#CC0000"><font color="#EEEEEC">docs/error-decoder.html?invariant=130&amp;args[]=object&amp;args[]= for the full message or use </font></span>  <span style="background-color:#CC0000"><font color="#EEEEEC">the non-minified dev environment for full errors and additional helpful warnings.</font></span>
  
  <font color="#555753">-</font> <font color="#FCE94F">universalModuleDefinition</font><font color="#555753">:</font><font color="#FCE94F">10</font><font color="#D3D7CF"> ba</font>
    <font color="#555753">lib/webpack/universalModuleDefinition:10:2</font>
  
  
  <font color="#555753">-</font> <font color="#FCE94F">bootstrap</font><font color="#555753">:</font><font color="#FCE94F">33</font><font color="#D3D7CF"> a.render</font>
    <font color="#555753">lib/webpack/bootstrap:33:1</font>
  
  <font color="#555753">-</font> <font color="#FCE94F">bootstrap</font><font color="#555753">:</font><font color="#FCE94F">30</font><font color="#D3D7CF"> a.read</font>
    <font color="#555753">lib/webpack/bootstrap:30:1</font>
  
  <font color="#555753">-</font> <font color="#FCE94F">bootstrap</font><font color="#555753">:</font><font color="#FCE94F">42</font><font color="#D3D7CF"> renderToString</font>
    <font color="#555753">lib/webpack/bootstrap:42:1</font>
  
  <font color="#555753">-</font> <font color="#FCE94F">static-entry.js</font><font color="#555753">:</font><font color="#FCE94F">206</font><font color="#D3D7CF"> Module.default</font>
    <font color="#555753">lib/.cache/static-entry.js:206:18</font>
  
  <font color="#555753">-</font> <font color="#FCE94F">bootstrap</font><font color="#555753">:</font><font color="#FCE94F">24</font><font color="#D3D7CF"> Promise</font>
    <font color="#555753">lib/webpack/bootstrap:24:1</font>
  
  
  <font color="#555753">-</font> <font color="#FCE94F">gatsby-browser-entry.js</font><font color="#555753">:</font><font color="#FCE94F">44</font><font color="#D3D7CF"> Promise._resolveFromExecutor</font>
    <font color="#555753">lib/.cache/gatsby-browser-entry.js:44:19</font>
  
  <font color="#555753">-</font> <font color="#FCE94F">bootstrap</font><font color="#555753">:</font><font color="#FCE94F">68</font><font color="#D3D7CF"> new Promise</font>
    <font color="#555753">lib/webpack/bootstrap:68:1</font>
  
  
  <font color="#555753">-</font> <font color="#FCE94F">bootstrap</font><font color="#555753">:</font><font color="#FCE94F">5</font><font color="#D3D7CF"> tryCatcher</font>
    <font color="#555753">lib/webpack/bootstrap:5:1</font>
  
  <font color="#555753">-</font> <font color="#FCE94F">bootstrap</font><font color="#555753">:</font><font color="#FCE94F">50</font><font color="#D3D7CF"> MappingPromiseArray._promiseFulfilled</font>
    <font color="#555753">lib/webpack/bootstrap:50:1</font>
  
  <font color="#555753">-</font> <font color="#FCE94F">api-runner-ssr.js</font><font color="#555753">:</font><font color="#FCE94F">6</font><font color="#D3D7CF"> MappingPromiseArray.PromiseArray._iterate</font>
    <font color="#555753">lib/.cache/api-runner-ssr.js:6:16</font>
  
  <font color="#555753">-</font> <font color="#FCE94F">bootstrap</font><font color="#555753">:</font><font color="#FCE94F">67</font><font color="#D3D7CF"> MappingPromiseArray.init</font>
    <font color="#555753">lib/webpack/bootstrap:67:1</font>
  
  <font color="#555753">-</font> <font color="#FCE94F">bootstrap</font><font color="#555753">:</font><font color="#FCE94F">19</font><font color="#D3D7CF"> MappingPromiseArray._asyncInit</font>
    <font color="#555753">lib/webpack/bootstrap:19:1</font></pre>

**Comment by sidharthachatterjee** [comment]
@antonioc57 This typically occurs when there is an error during server side rendering in `gatsby build`

Based on your stack trace, it looks like it is coming from `react-router-dom`. Gatsby v2 includes reach router for routing so you shouldn't need to include react-router-dom.

**Comment by aposudevsky** [comment]
@antonioc57 ,
I had the same problem. It was connected to history package. I see you are using it as well. 
`!canUseDOM ? process.env.NODE_ENV !== "production" ? invariant(false, 'Browser history needs a DOM') : invariant(false) : void 0;`
This code from history.js shows that it needs DOM which is unavailable during production build process. 
The workaround I did is: 
`const history = typeof window !== 'undefined' ? createBrowserHistory() : null;`
You can do the same trick with other functionalities of that library you might be using.
Hope this helps.

**Comment by danny-0805** [comment]
Got same error:
```
Building static HTML failed for path "/404/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  Error: Minified React error #294; visit https://reactjs.org/docs/error-decoder.html?invariant=294 for the full message or use the non-minified dev environment f  or full errors and additional helpful warnings.

  - react-dom-server.node.production.min.js:46 a.b.render
    [myproject]/[react-dom]/cjs/react-dom-server.node.production.min.js:46:17

  - react-dom-server.node.production.min.js:44 a.b.read
    [myproject]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:18

  - react-dom-server.node.production.min.js:54 renderToString
    [myproject]/[react-dom]/cjs/react-dom-server.node.production.min.js:54:364

  - render-page.js:612 Module../.cache/static-entry.js.__webpack_exports__.default
    E:/myproject/public/render-page.js:612:28

  - render-html.js:28 
    [myproject]/[gatsby]/dist/utils/worker/render-html.js:28:36

  - debuggability.js:384 Promise._execute
    [myproject]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [myproject]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [myproject]/[bluebird]/js/release/promise.js:103:10

  - render-html.js:24 
    [myproject]/[gatsby]/dist/utils/worker/render-html.js:24:47

  - util.js:16 tryCatcher
    [myproject]/[bluebird]/js/release/util.js:16:23

  - map.js:68 MappingPromiseArray._promiseFulfilled
    [myproject]/[bluebird]/js/release/map.js:68:38

  - promise_array.js:115 MappingPromiseArray.PromiseArray._iterate
    [myproject]/[bluebird]/js/release/promise_array.js:115:31

  - promise_array.js:79 MappingPromiseArray.init
    [myproject]/[bluebird]/js/release/promise_array.js:79:10

  - map.js:37 MappingPromiseArray._asyncInit
    [myproject]/[bluebird]/js/release/map.js:37:10

  - async.js:97 _drainQueueStep
    [myproject]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [myproject]/[bluebird]/js/release/async.js:86:9


not finished Generating image thumbnails - 228.649s
```

**Comment by apsrcreatix** [comment]
> Got same error:
> 
> ```
> Building static HTML failed for path "/404/"
> 
> See our docs page for more info on this error: https://gatsby.dev/debug-html
> 
> 
>   Error: Minified React error #294; visit https://reactjs.org/docs/error-decoder.html?invariant=294 for the full message or use the non-minified dev environment f  or full errors and additional helpful warnings.
> 
>   - react-dom-server.node.production.min.js:46 a.b.render
>     [myproject]/[react-dom]/cjs/react-dom-server.node.production.min.js:46:17
> 
>   - react-dom-server.node.production.min.js:44 a.b.read
>     [myproject]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:18
> 
>   - react-dom-server.node.production.min.js:54 renderToString
>     [myproject]/[react-dom]/cjs/react-dom-server.node.production.min.js:54:364
> 
>   - render-page.js:612 Module../.cache/static-entry.js.__webpack_exports__.default
>     E:/myproject/public/render-page.js:612:28
> 
>   - render-html.js:28 
>     [myproject]/[gatsby]/dist/utils/worker/render-html.js:28:36
> 
>   - debuggability.js:384 Promise._execute
>     [myproject]/[bluebird]/js/release/debuggability.js:384:9
> 
>   - promise.js:518 Promise._resolveFromExecutor
>     [myproject]/[bluebird]/js/release/promise.js:518:18
> 
>   - promise.js:103 new Promise
>     [myproject]/[bluebird]/js/release/promise.js:103:10
> 
>   - render-html.js:24 
>     [myproject]/[gatsby]/dist/utils/worker/render-html.js:24:47
> 
>   - util.js:16 tryCatcher
>     [myproject]/[bluebird]/js/release/util.js:16:23
> 
>   - map.js:68 MappingPromiseArray._promiseFulfilled
>     [myproject]/[bluebird]/js/release/map.js:68:38
> 
>   - promise_array.js:115 MappingPromiseArray.PromiseArray._iterate
>     [myproject]/[bluebird]/js/release/promise_array.js:115:31
> 
>   - promise_array.js:79 MappingPromiseArray.init
>     [myproject]/[bluebird]/js/release/promise_array.js:79:10
> 
>   - map.js:37 MappingPromiseArray._asyncInit
>     [myproject]/[bluebird]/js/release/map.js:37:10
> 
>   - async.js:97 _drainQueueStep
>     [myproject]/[bluebird]/js/release/async.js:97:12
> 
>   - async.js:86 _drainQueue
>     [myproject]/[bluebird]/js/release/async.js:86:9
> 
> 
> not finished Generating image thumbnails - 228.649s
> ```
> 
> dependencies I am using:
> 
> ```
> "dependencies": {
>     "axios": "^0.19.2",
>     "browser-lang": "^0.0.1",
>     "checkout-js-library": "^1.1.7",
>     "core-js": "^3.6.4",
>     "currency.js": "^1.2.2",
>     "gatsby": "^2.19.19",
>     "gatsby-cli": "^2.10.6",
>     "gatsby-image": "^2.2.39",
>     "gatsby-link": "^2.2.28",
>     "gatsby-paginate": "^1.1.1",
>     "gatsby-plugin-algolia": "^0.5.0",
>     "gatsby-plugin-alias-imports": "^1.0.5",
>     "gatsby-plugin-analytics": "^0.2.0",
>     "gatsby-plugin-catch-links": "^2.0.2",
>     "gatsby-plugin-dark-mode": "^1.1.0",
>     "gatsby-plugin-facebook-analytics": "^2.2.20",
>     "gatsby-plugin-facebook-pixel": "^1.0.3",
>     "gatsby-plugin-feed": "^2.0.5",
>     "gatsby-plugin-firebase": "^0.1.8",
>     "gatsby-plugin-google-analytics": "^2.1.34",
>     "gatsby-plugin-google-fonts": "^1.0.1",
>     "gatsby-plugin-guess-js": "^1.1.31",
>     "gatsby-plugin-i18n": "^1.0.1",
>     "gatsby-plugin-intercom-spa": "^0.2.0",
>     "gatsby-plugin-intl": "^0.3.3",
>     "gatsby-plugin-layout": "^1.0.2",
>     "gatsby-plugin-lint-queries": "^0.0.3",
>     "gatsby-plugin-mailchimp": "^5.1.2",
>     "gatsby-plugin-manifest": "^2.2.40",
>     "gatsby-plugin-netlify": "^2.0.0",
>     "gatsby-plugin-nprogress": "^2.1.18",
>     "gatsby-plugin-offline": "^3.0.33",
>     "gatsby-plugin-prefetch-google-fonts": "^1.4.3",
>     "gatsby-plugin-provide-react": "^1.0.0",
>     "gatsby-plugin-react-helmet": "^3.1.21",
>     "gatsby-plugin-react-redux": "^1.1.0-0",
>     "gatsby-plugin-react-svg": "^3.0.0",
>     "gatsby-plugin-remove-trailing-slashes": "^2.1.22",
>     "gatsby-plugin-robots-txt": "^1.5.0",
>     "gatsby-plugin-sentry": "^1.0.1",
>     "gatsby-plugin-sharp": "^2.4.4",
>     "gatsby-plugin-sitemap": "^2.2.26",
>     "gatsby-plugin-styled-components": "^3.1.18",
>     "gatsby-plugin-styled-jsx": "^3.0.1",
>     "gatsby-plugin-web-font-loader": "^1.0.4",
>     "gatsby-remark-copy-linked-files": "^2.0.5",
>     "gatsby-remark-emojis": "^0.2.3",
>     "gatsby-remark-external-links": "^0.0.4",
>     "gatsby-remark-images": "^3.1.43",
>     "gatsby-remark-prismjs": "^3.3.30",
>     "gatsby-source-filesystem": "^2.1.47",
>     "gatsby-source-googlemaps-geocoding": "^1.0.0",
>     "gatsby-source-instagram": "^0.7.0",
>     "gatsby-source-magento": "file:plugins/gatsby-source-magento",
>     "gatsby-source-wordpress": "file:plugins/gatsby-source-wordpress",
>     "gatsby-transformer-json": "^2.2.25",
>     "gatsby-transformer-remark": "^2.6.49",
>     "gatsby-transformer-sharp": "^2.3.13",
>     "moment": "^2.24.0",
>     "postscribe": "^2.0.8",
>     "prismjs": "^1.15.0",
>     "prop-types": "^15.7.2",
>     "react": "^16.12.0",
>     "react-dom": "^16.12.0",
>     "react-helmet": "^5.2.1",
>     "react-icons": "^3.9.0",
>     "react-intl": "^2.8.0",
>     "react-redux": "^7.1.3",
>     "recompose": "^0.30.0",
>     "redux": "^4.0.5",
>     "redux-thunk": "^2.3.0",
>   },
> ```

Hey folks,

I was getting the same issue then I removed the code of Suspense and Lazy load from my file. It worked!

I hope it may work for you as well until they add the support for these.

Happy Coding!

**Comment by David-orovs** [comment]
i dont get, what code of suspense and lazy??

**Comment by apsrcreatix** [comment]
> i dont get, what code of suspense and lazy??

[Suspense & Lazy in React](https://reactjs.org/docs/concurrent-mode-suspense.html)

**Comment by umer2001** [comment]
I got the same errror when I ran "**gatsby build**" , but it was working fine in development.
in my gatsby project i was handling global state using contextApi & Reducer so i had to make changes to gatsby-ssr & gatsby-browser to import provider and wrap it to root element.
I had exported Provideras default in contextfile.
**the problem was I was importing provider as below in browser-ssr.js**
`const GlobalProvider = require("./src/context/GlobalState")`

**I just changed it and added .default** in the end like below & it started working fine.
`const GlobalProvider = require("./src/context/GlobalState").default;` 

now I am adding my error detailso you can relate to it.

> failed Building static HTML for pages - 4.252s
> 5:07:47 PM: error Building static HTML failed for path "/blog"
> 5:07:48 PM: 
> 5:07:48 PM: 
> 5:07:48 PM:   Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder  .html?invariant=130&args[]=object&args[]= for the full message or use the non-  minified dev environment for full errors and additional helpful warnings.
> 5:07:48 PM:   
> 5:07:48 PM:   - react-dom-server.node.production.min.js:48 a.b.render
> 5:07:48 PM:     [repo]/[react-dom]/cjs/react-dom-server.node.production.min.js:48:37
> 5:07:48 PM:   
> 5:07:48 PM:   - react-dom-server.node.production.min.js:44 a.b.read
> 5:07:48 PM:     [repo]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:18
> 5:07:48 PM:   
> 5:07:48 PM:   - react-dom-server.node.production.min.js:54 renderToString
> 5:07:48 PM:     [repo]/[react-dom]/cjs/react-dom-server.node.production.min.js:54:364
> 5:07:48 PM:   
> 5:07:48 PM:   - render-page.js:654 Module../.cache/static-entry.js.__webpack_exports__.defau    lt
> 5:07:48 PM:     /opt/build/repo/public/render-page.js:654:28
> 5:07:48 PM:   
> 5:07:48 PM:   - render-html.js:28 
> 5:07:48 PM:     [repo]/[gatsby]/dist/utils/worker/render-html.js:28:36
> 5:07:48 PM:   
> 5:07:48 PM:   - debuggability.js:384 Promise._execute
> 5:07:48 PM:     [repo]/[bluebird]/js/release/debuggability.js:384:9
> 5:07:48 PM:   
> 5:07:48 PM:   - promise.js:518 Promise._resolveFromExecutor
> 5:07:48 PM:     [repo]/[bluebird]/js/release/promise.js:518:18
> 5:07:48 PM:   
> 5:07:48 PM:   - promise.js:103 new Promise
> 5:07:48 PM:     [repo]/[bluebird]/js/release/promise.js:103:10
> 5:07:48 PM:   
> 5:07:48 PM:   - render-html.js:24 
> 5:07:48 PM:     [repo]/[gatsby]/dist/utils/worker/render-html.js:24:47
> 5:07:48 PM:   
> 5:07:48 PM:   - util.js:16 tryCatcher
> 5:07:48 PM:     [repo]/[bluebird]/js/release/util.js:16:23
> 5:07:48 PM:   
> 5:07:48 PM:   - map.js:68 MappingPromiseArray._promiseFulfilled
> 5:07:48 PM:     [repo]/[bluebird]/js/release/map.js:68:38
> 5:07:48 PM:   
> 5:07:48 PM:   - promise_array.js:115 MappingPromiseArray.PromiseArray._iterate
> 5:07:48 PM:     [repo]/[bluebird]/js/release/promise_array.js:115:31
> 5:07:48 PM:   
> 5:07:48 PM:   - promise_array.js:79 MappingPromiseArray.init
> 5:07:48 PM:     [repo]/[bluebird]/js/release/promise_array.js:79:10
> 5:07:48 PM:   
> 5:07:48 PM:   - map.js:37 MappingPromiseArray._asyncInit
> 5:07:48 PM:     [repo]/[bluebird]/js/release/map.js:37:10
> 5:07:48 PM:   
> 5:07:48 PM:   - async.js:97 _drainQueueStep
> 5:07:48 PM:     [repo]/[bluebird]/js/release/async.js:97:12
> 5:07:48 PM:   
> 5:07:48 PM:   - async.js:86 _drainQueue
> 5:07:48 PM:     [repo]/[bluebird]/js/release/async.js:86:9
>

**Comment by TyeCampbell** [comment]
> **the problem was I was importing provider as below in browser-ssr.js**
> `const GlobalProvider = require("./src/context/GlobalState")`
> 
> **I just changed it and added .default** in the end like below & it started working fine.
> `const GlobalProvider = require("./src/context/GlobalState").default;`

This is exactly what I was doing as well and this fixed the issue. Thank you!
