### ISSUE TITLE
Add new gatsby lifecycle

### ISSUE THREAD

**Issue by secondary-school55** [gatsbyjs/gatsby#12710]
## Summary

In Gatsby there are sourceNodes api and it works fine for most cases. But it not works very good with transformers plugins. For example gatsby-transformer-yaml. When sourceNodes is called there are no gatsby-transformer-yaml nodes created yet. I suggest lifecycle api similar for sourceNodes: transformNodes. It will be called when all source and transform plugins done their work.

**Comment by sidharthachatterjee** [comment]
@secondary-school55 Can you elaborate on your use-case? Sounds like this might be rendered void by schema customization

**Comment by KyleAMathews** [comment]
Transformer plugins should use https://www.gatsbyjs.org/docs/node-apis/#onCreateNode

Which is in fact what gatsby-transformer-yaml uses ;-) https://github.com/gatsbyjs/gatsby/blob/546c3d2d79ef09be2bb583b0944cc5d1446562e6/packages/gatsby-transformer-yaml/src/gatsby-node.js#L5

Nodes can be added at any time and in any order so there's no lifecycle hook that could be called for when "sourcing" nodes are created as nodes are never "done". Additionally there's no difference between a source plugin creating a node and a transformer plugin creating a node. Transformers can transform nodes created by other transformers.

Let us know if there's something unique you want to do that's not covered by `onCreateNode`!
