### ISSUE TITLE
[1.0] gatsby-plugin-feed does not work

### ISSUE THREAD

**Issue by chiedo** [gatsbyjs/gatsby#1272]
When running the build with this plugin, Gatsby doesn't actually create an rss.xml file. It fails silently.

This is with the gatsby-starter-blog after adding the plugin exactly as shown in the documentation.

**Comment by KyleAMathews** [comment]
@chiedo you might need a custom query https://www.gatsbyjs.org/docs/packages/gatsby-plugin-feed/#how-to-use

It's hard to know what's going on in your site from here. Could you add some console.logs to the plugin code? This is a new plugin so probably has some bugs still.

/cc @nicholaswyoung

**Comment by chiedo** [comment]
Hey @KyleAMathews 

There are no logs. It's failing silently. The console appears as if everything succeeded but it just doesn't do anything.

I was using the gatsby-starter-blog though with no modifications other than the default set up described at https://www.gatsbyjs.org/docs/packages/gatsby-plugin-feed/#how-to-use

Does it work for you (or @nicholaswyoung does it work for you if you're the one who built it)?

Thanks!

**Comment by KyleAMathews** [comment]
@chiedo I meant could you please dig into the plugin code and add some console.logs to try to understand where it's failing :-)

**Comment by chiedo** [comment]
Oh hahahaha my mistake.

I'm going to need to revisit on a fresh mind @KyleAMathews 

I'm probably getting tunnel vision. A console.log in the first line of onPostBuild doesn't do anything...

It may just be me though...

**Comment by chiedo** [comment]
Figured it out @KyleAMathews haha.

The last npm version `gatsby-plugin-feed@1.0.0-beta.1` was published without the files being built.

That's why none of my console.log was working.

When you get a chance, can you push gatsby-plugin-feed with the build? :)

**Comment by chiedo** [comment]
@nicholaswyoung I actually just saw that you're the author of this plugin. Could you build those files and republish? Thanks!

**Comment by KyleAMathews** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/1298

Will be making new beta release soonish.
