### ISSUE TITLE
TypeError: Cannot read property 'componentChunkName' of undefined

### ISSUE THREAD

**Issue by AAverin** [gatsbyjs/gatsby#12725]
## Description

After implementing some generated pages (blog posts) often dev version of Gatsby breaks with `TypeError: Cannot read property 'componentChunkName' of undefined`

<img width="1084" alt="Screen Shot 2019-03-21 at 14 45 10" src="https://user-images.githubusercontent.com/1481332/54756185-f7e4b400-4be7-11e9-95f8-99bbd9143dd2.png">

Only restarting `gatsby develop` solves the problem

### Steps to reproduce

Not sure what was the cause and how to cleanly reproduce it. I assume that generating pages using `createPages`, `onCreateNode` and `onCreatePages` might be the cause of the problem.

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Safari: 11.1.2
  npmGlobalPackages:
    gatsby-cli: 2.4.4

**Comment by AAverin** [comment]
After starting `gatsby develop` everything works for a while, but then randomly breaks and page no longer opens

**Comment by dbrookes** [comment]
I have the same issue on hot reload, any chance you're using `gatsby-plugin-remove-trailing-slashes`?

Removing `gatsby-plugin-remove-trailing-slashes` from `gataby-config.js` brings back hot reloading in dev for me

**Comment by AAverin** [comment]
I have this, maybe some of the plugins use `remove-trailing-slashes` internally?
```
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
  },
  plugins: [
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        // Setting this parameter is optional
        anonymize: true,
      },
    },
    {
      resolve: `gatsby-plugin-react-helmet`
    },
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-images',
            options: {
              maxWidth: 970,
            },
          },
          {
            resolve: "markdown-embed-youtube"
          }
        ],
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages/blog/posts`,
        name: "pages",
      },
    },
    {
      resolve: `gatsby-plugin-facebook-pixel`,
      options: {

      },
    },
    `gatsby-remark-copy-linked-files`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-remark-images`,
      options: {
        maxWidth: 1080,
      },
    }
  ],
}

```

**Comment by sarahannnicholson** [comment]
I am seeing this as well, I haven't tried installing `remove-trailing-slashes` yet. 

But I have a question for everyone. When you do `gatsby build` then `gatsby serve` and go to http://localhost:9000 do you get the same error? Just wondering if what I am seeing with `gatsby serve` is related to this

**Comment by AAverin** [comment]
I am still struggling to build, get some error inside error message prettifier similar to #6668
Will post a message when I build the project
Also, maybe look to #4360. Once I applied a fix from there I think I stopped getting the componentChunkName  message

**Comment by khades** [comment]
that issue was fixed in recent 2.2.4 gatsby build, try to update gatsby itself, not cli

**Comment by sidharthachatterjee** [comment]
@sarahannnicholson This shouldn't occur when running `gatsby build` then `gatsby serve` since the error looks like it's coming from the Dev 404 code, which isn't included in the production build 

@AAverin Can you link to a minimal reproduction of this if possible?

**Comment by khades** [comment]
https://github.com/gatsbyjs/gatsby/pull/12671 this pull fixes pages deletion (even 404) in development mode, its live in version 2.2.4

**Comment by sidharthachatterjee** [comment]
Thank you @khades 

@AAverin Can you confirm if updating to 2.2.4 fixes your issue?

**Comment by AAverin** [comment]
I'll update and keep testing, thanks
