### ISSUE TITLE
Featured media in elasticlunr search index

### ISSUE THREAD

**Issue by mahhan** [gatsbyjs/gatsby#12728]
Having implemented the plugin 'gatsby-plugin-elasticlunr-search' I have managed to create a fully working site index search. However, is there any way to add a post types featured media in the search to show the product being searched for.

I have the current setup in `gatsby-config.js`:
```js
...
{
  resolve: `@gatsby-contrib/gatsby-plugin-elasticlunr-search`,
    options: {
      fields: [`title`],
      resolvers: {
        wordpress__wp_artist: {
          title: node => node.title,
          path: node => node.path,
          featuredImage: node => node.featured_media.localFile.childImageSharp.fixed.src
        }
      },
    },
  },
...
```

This search input field component `SearchInput.js`
```js
import React, { Component } from 'react'
import { useStaticQuery, graphql } from 'gatsby'
import Search from './Search'

const SearchInput = () => {
  const { siteSearchIndex } = useStaticQuery(
    graphql`
      query {
        siteSearchIndex {
          index
        }
      }
    `
  )

  return (
    <Search searchIndex={siteSearchIndex.index} />
  )
}

export default SearchInput
```

And this search component, which handles the search ```Search.js```
```js
import React, { Component } from 'react'
import { Index } from 'elasticlunr'
import Link from 'gatsby-link'

// Search component
export default class Search extends Component {
  constructor (props) {
    super(props)
    this.state = {
      query: ``,
      results: [],
    }
  }

  render () {
    return (
      <div>
        <input type="text" value={this.state.query} onChange={this.search} />
        <ul className="u__absolute">
          {this.state.results.map(page => (
            <li key={page.id}>
              <Link to={'/' + page.path}>{page.title}</Link>
              <img src={page.featuredImage} />
            </li>
          ))}
        </ul>
      </div>
    )
  }
  getOrCreateIndex = () =>
    this.index
      ? this.index
      : Index.load(this.props.searchIndex)

  search = evt => {
    const query = evt.target.value
    this.index = this.getOrCreateIndex()
    this.setState({
      query,
      // Query the index with search string to get an [] of IDs
      results: this.index
        .search(query, { expand: true })
        // Map over each ID and return the full document
        .map(({ ref }) => this.index.documentStore.getDoc(ref)),
    })
  }
}
```

Am I missing something? The 'featuredImage' prop in the img `src` tag isn't working and it responds with this error on build time:

```js
error
The GraphQL query from /mnt/c/dev/djb/frontend/src/components/Menu/SearchInput.js failed.

Errors:
  Cannot read property 'localFile' of undefined

  GraphQL request (3:5)
  2:   siteSearchIndex {
  3:     index
         ^
  4:   }

Plugin:
  none
Query:
  query mntCDevDjbFrontendSrcComponentsMenuSearchInputJs3428966955 {
    siteSearchIndex {
      index
    }
  }
```

**Comment by pieh** [comment]
Hey @mahhan 

I'm not sure if this is solvable (at least with current implementation of `@gatsby-contrib/gatsby-plugin-elasticlunr-search`). The raw node data doesn't actually look like one you have in your `resolvers` config option.

`node.featured_media.localFile.childImageSharp.fixed.src` is not really there in *raw* node data - the graphql layer does normalize those things to make and creates object that you can navigate like that.

In raw data this really is something like this:

- wordprest artist node: `node.featured_media___NODE = <id_of_media_node>`
- media node `node.localFile = <id_of_file_node>`
- file node looks for `ImageSharp` child nodes
- `ImageSharp` doesn't really have any data - it just is interface to run image processing

**Comment by mahhan** [comment]
@pieh Thanks for getting back to me.

Okay, well that's a bummer. What would any other gatsby solution be, which can provide the feature of showing images in search results?
