### ISSUE TITLE
Support for Tabbed Content

### ISSUE THREAD

**Issue by WriteCodeEveryday** [gatsbyjs/gatsby#12745]
## Summary

I'd like support for tabbed content or some documentation on how to do tabbed-like behaviour.

### Basic example

DocFX has extension for tabbed content here (https://github.com/dotnet/docfx/issues/1659) that could be some limited use.

### Motivation

When generating developer documentation using Gatsby, it would be amazing to nest a whole bunch of examples kinda like these [twilio ones](https://www.twilio.com/docs/sms/twiml/message) on the left side of 
 screen allowing someone to select a target language and get a fancy PrismJS code highlighted example. 

This is a [well known](https://medium.com/@aryamurali/embed-code-in-medium-e95b839cfdda) [missing use case](https://medium.com/@egonelbre/dealing-with-code-on-medium-c40016e8b1f3) in a competitor.

I am perfectly fine with a drop-in example that shows how to simulate this on the existing, or having this be linked back to an existing proposal and closed.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @WriteCodeEveryday 

Could you elaborate a little on what you mean? If I understand correctly, you’re requesting for support for tabs in Markdown in gatsby-transformer-remark?

**Comment by DSchau** [comment]
Also just to clarify--I wouldn't really call what you're asking for _tabs_!

You're asking for a navigable sidebar, right? [Gatsby themes](https://www.gatsbyjs.org/docs/themes/) are going to be a great fit for this--particularly with themes already available like [docz](https://twitter.com/pedronauck/status/1108763903411007488) which support similar use-cases.

That being said--you could also build this in yourself You would just need to use headers (e.g. `## Something`), and then the [`tableOfContents` field](https://www.gatsbyjs.org/packages/gatsby-transformer-remark/#getting-table-of-contents) on the `MarkdownRemark` node, and then you could build out the sidebar based upon that query (or queries!).

Hopefully this helps! Let us know if we can help further!

**Comment by WriteCodeEveryday** [comment]
> Also just to clarify--I wouldn't really call what you're asking for _tabs_!
> That being said--you could also build this in yourself You would just need to use headers (e.g. `## Something`), and then the [`tableOfContents` field](https://www.gatsbyjs.org/packages/gatsby-transformer-remark/#getting-table-of-contents) on the `MarkdownRemark` node, and then you could build out the sidebar based upon that query (or queries!).


You're correct, I was just looking for tabbed content being nested that could be tabbed through. 

The twilio example is probably the best: you can choose different languages and get relevant code snippets.
