### ISSUE TITLE
How to strip of the lazy loading scripts from the output html to get the amp version?

### ISSUE THREAD

**Issue by amanrathore10** [gatsbyjs/gatsby#12753]
The gatsby amp plugins are not too useful and are failed by the ampvalidator tools.

**Comment by sidharthachatterjee** [comment]
@amanrathore10 Can you elaborate on what’s failing? If you’re referring to 
https://github.com/jafaircl/gatsby-plugin-amp then I’d recommend ole Ingram issue there? 🙂
