### ISSUE TITLE
fail fast/eslint plugin that checks for `window`

### ISSUE THREAD

**Issue by kentcdodds** [gatsbyjs/gatsby#12769]
## Summary

I wish I could say I never make this mistake, but I make it pretty often. The error message I get when building is:

```
error Building static HTML failed for path "/workshops/asynchronous-java-script"
See our docs page on debugging HTML builds for help https://gatsby.app/debug-html
  11 |   const {event, discount} = props
  12 |   const [titoWidgetReady, setWidgetReady] = React.useState(
> 13 |     window.hasOwnProperty('TitoWidget'),
     |     ^
  14 |   )
  15 |
  16 |   React.useEffect(() => {

  WebpackError: ReferenceError: window is not defined
```

The problem is I'm referencing `window` in the render method. This works fine in `dev`, but it doesn't work when running `gatsby build`.

### Motivation

I know that it's my problem. But it'd be cool if `gatsby develop` would give me a warning if it detected something that wont work for the `build`. There could be other situations, but I know that at least referencing browser-only globals in the `render` method doesn't work during the `build` but works during `develop` and I don't realize something's wrong until it breaks in CI.

So I'd really appreciate some sort of gatsby eslint plugin (like suggested in #7687) or (even better) an error in `develop` for anything that would fail in `build`.

**Comment by DSchau** [comment]
@kentcdodds this would be super slick, and agreed, I've seen people suffer through a broken build while they iron out usages of globals in SSR environment.

Giving actionable feedback _prior_ to failing in build is key here. I've never written an eslint plugin, but this certainly seems like something that could be doable--so we'll take a look and prioritize appropriately!

Thanks for the idea!

**Comment by sidharthachatterjee** [comment]
Watching https://github.com/yannickcr/eslint-plugin-react/issues/2057 closely

**Comment by LekoArts** [comment]
We have solved this with SSR in Development now: https://github.com/gatsbyjs/gatsby/discussions/28138
