### ISSUE TITLE
gatsby-source-filesystem sourceInstanceName query filter sensitive to plugin declaration order

### ISSUE THREAD

**Issue by Wolfsun** [gatsbyjs/gatsby#12762]
## Description

It is possible to query the filesystem using a filter defining sourceInstanceName. However, if two or more directories are defined within the plugins section of gatsby-config.js, where the directories are nested within each other, the query only works as expected if the deepest directory is defined first.

### Steps to reproduce

Using the standard gatsby starter, within the images directory create a sub directory e.g. photos. Configure the photos directory in gatsby-config.js, place the deeper photos declaration directly below the images declaration like so:

```
{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `photos`,
        path: `${__dirname}/src/images/photos`,
      },
    },
```

The sourceInstanceName filter on images works and returns all results (including those within photos), but the same search filter on photos returns no results.

If you reverse the declarations like below and restart the development server the photos query returns results as expected. The images query returns all results excluding the photos directory, not sure if this is the expected result or if it should still include photos? 

```
{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `photos`,
        path: `${__dirname}/src/images/photos`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
```

### Expected result

See above. 

### Actual result

See above. This may not be a bug but just a documentation issue????

### Environment

  System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 11.0.0 - ~/.nvm/versions/node/v11.0.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v11.0.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.75
    Firefox: 65.0.1
  npmPackages:
    gatsby: ^2.2.6 => 2.2.6 
    gatsby-image: ^2.0.34 => 2.0.34 
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6 
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.10 => 3.0.10 
    gatsby-plugin-sharp: ^2.0.29 => 2.0.29 
    gatsby-source-filesystem: ^2.0.27 => 2.0.27 
    gatsby-transformer-json: ^2.1.11 => 2.1.11 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.17

**Comment by wardpeet** [comment]
This is not a bug, it's intentional. When adding gatsby-source-filesystem we traverse the directories to find any files. Whenever we hit a file we mark it as created so if another gatsby-source-filesystem plugin is loaded the files will be ignored as they are already known to gatsby.

you have multiple options, the one you described by making photos be loaded first. Secondary you can use the [ignore option](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#options) to ignore `photos` in the images filesystem.

For you this might be:
```
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
        ignore: ['/photos/**/*']
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `photos`,
        path: `${__dirname}/src/images/photos`,
      },
    },
```

**Comment by idomusha** [comment]
For me, it's a bug.
Lets says we have 2 images in both folders.

```
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
        ignore: [`photos/**/*`],
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `photos`,
        path: `${__dirname}/src/images/photos`,
      },
    },
```
returns
`getPhotos:allFile(filter: { sourceInstanceName: { eq: "images" } }).totalCount: 4`
`getPhotos:allFile(filter: { sourceInstanceName: { eq: "photos" } }).totalCount: 0`

while

```
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `photos`,
        path: `${__dirname}/src/images/photos`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
        ignore: [`photos/**/*`],
      },
    },
```
returns
`getPhotos:allFile(filter: { sourceInstanceName: { eq: "images" } }).totalCount: 2`
`getPhotos:allFile(filter: { sourceInstanceName: { eq: "photos" } }).totalCount: 2`

**Comment by idomusha** [comment]
Still happening.
