### ISSUE TITLE
Using imports and gatsby-plugin-sass after building

### ISSUE THREAD

**Issue by jeffpamer** [gatsbyjs/gatsby#1277]
I'm hoping to get some clarity on the expected way to import scss styles with gatsby-plugin-sass to work in both development and after building. Say you have an extremely basic `layouts/index.js` file:

```javascript
import React from 'react';
import '../stylesheets/main.scss';

export default class Index extends React.Component {
  render() {
    return this.props.children();
  }
}
```

In development the styles imported in `main.scss` work fine. During the build the stylesheet is correctly compiled/extracted/etc, but the dynamic React component still attempts to import `stylesheets/main.scss` (which doesn't exist in public). Should I update this to import only when in development? Or am I missing the intended way to use this plugin?

**Comment by danielfarrell** [comment]
I(the sass plugin author) am actually running into this same thing with the normal css handling as well when it imports from an npm package, but didn't totally understand what was going on until just now. Thanks for that.  I'll try to figure out a solution for that and share here.

**Comment by danielfarrell** [comment]
@KyleAMathews might have some thoughts here, because I think the build-javascript stage used to have a null loader for css, but switched for the offline plugin.

**Comment by KyleAMathews** [comment]
Won't have time to look into this in the very near future. If one of you
want to look into this and make a PR to fix it plus add a simple using-sass
example site that'd be 💯 This is the examples directory
https://github.com/gatsbyjs/gatsby/tree/1.0/examples

**Comment by KyleAMathews** [comment]
@jeffpamer could you try reproducing your issue in the using-sass example site @danielfarrell added?

**Comment by jeffpamer** [comment]
@KyleAMathews I'll try to take a look today, tomorrow at the latest.

**Comment by jeffpamer** [comment]
@KyleAMathews @danielfarrell I can't reproduce this anymore after the latest changes so I'll go ahead and close this. Thanks! But one additional question/comment: When I was first investigating this I thought the compiled styles.css file was being pulled into index.html, but maybe I'm mistaken because it looks like all CSS is inlined while using the sass plugin. I know there was some discussion in the 1.0 roadmap around critical CSS, but just trying to confirm if it's intentional at the moment that _all_ sass styles are inlined?

**Comment by KyleAMathews** [comment]
Inlining everything is the default cause it's easiest. If someone wanted to create a critical-styles plugin that'd be 🔥

**Comment by jeffpamer** [comment]
Ok got it, thanks for confirming. The project I most want to use Gatsby on will probably end up around 150kb of minified CSS, so I'm hesitant to rely _only_ on inlining. Let me try to figure out if I have some time to look into putting together a critical-styles example.

**Comment by jarodtaylor** [comment]
I'm having this same exact issue just using regualr postcss imports. 

src/assets/stylesheets/main.css
```css
@import '_normalize';
@import '_font-family';
@import '_breakpoints';
@import '_container';
@import '_parallax-layout';
@import '_main-header';
```

src/layouts/index.js
![image](https://user-images.githubusercontent.com/362248/36063727-11c2a908-0e46-11e8-988f-1e371ea9d55a.png)

**Comment by m-allanson** [comment]
@jarodtaylor This should work if you're importing only local CSS files. 

In your `main.css`, what happens if you use relative paths and include the `.css` file extension? e.g. `@import './_normalize.css';`

If that doesn't work can you open a new issue? Ideally with an example repo that reproduces the problem.

**Comment by jarodtaylor** [comment]
@m-allanson what's interesting is if I import the normalize.css, it's fine. It's when I import any css file that uses postcss-cssnext things like variables, etc. 

I'll try and set up another repo demonstrating this. I decided to just roll with styled-components with this particular use case.

**Comment by jeffpamer** [comment]
@jarodtaylor Just to make sure there's no confusion: This issue is referencing `gatsby-plugin-sass` which doesn't provide any postcss support. For those features you would need `gatsby-plugin-postcss-sass`.

**Comment by jarodtaylor** [comment]
@jeffpamer yeah, sorry to hijack this particular issue. I was just having the same exact issue you were having, only this was with just using postcss. I haven't used Sass in years. Sorry for any confusion. 

My presumption was the postcss/postcss-cssnext was ready to work right out of the box with Gatsby.
