### ISSUE TITLE
Gatsby custom schema API fails with Contentful multi reference

### ISSUE THREAD

**Issue by sami616** [gatsbyjs/gatsby#12787]
## Description

The new Gatsby customize schema API returns null on multi reference fields when used with ```gatsby-source-contentful``` even when the field is populated

In this case specifically the ```sections``` field:

```
    type ContentfulPage implements Node {
      title: String
      slug: String
      sections: [ContentfulSection] <-- null
    }
```

### Steps to reproduce

1. clone: git clone https://github.com/sami616/gatsby-contentful-custom-schema-bug.git
2. yarn install
2. yarn start

### Expected result

A list of data should render under the page title

### Actual result

Nothing renders because the field sections is ```null``` despite data being available in Contentful.

### Environment

System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
    Yarn: 1.10.1 - ~/.nvm/versions/node/v10.10.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.10.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    gatsby: ^2.2.8 => 2.2.8
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-source-contentful: ^2.0.42 => 2.0.42
    gatsby-transformer-remark: ^2.1.7 => 2.1.7
  npmGlobalPackages:
    gatsby-cli: 2.4.3

**Comment by stefanprobst** [comment]
@sami616 Thanks for reporting! Would you be able to test if #12806 fixes the issue for you?

**Comment by sami616** [comment]
Thanks @stefanprobst, whats the best way for me to test? can i install this specific PR?

**Comment by wardpeet** [comment]
it's available in the latest gatsby version (2.2.10) :)

**Comment by sami616** [comment]
@stefanprobst @wardpeet  i have discovered the same problem seems to be affecting unions, when a field is referencing an array of multiple types i'm always getting ```null```

Should i report another bug?

**Comment by stefanprobst** [comment]
@sami616 The PR you linked to is not merged yet, so the issue must lie somewhere else. Would you be able to open a new bug report (and if possible adjust the reproduction repo)? That would be very helpful thanks!

**Comment by sami616** [comment]
no prob @stefanprobst #12832 

same repo, hopefully that makes sense - shout if not!
