### ISSUE TITLE
Plugin option to access renamed dataLayer for gatsby-plugin-google-tagmanager

### ISSUE THREAD

**Issue by spwisner** [gatsbyjs/gatsby#12782]
## Summary

Google Tag Manager allows users to rename the dataLayer in GTM (https://developers.google.com/tag-manager/devguide#renaming).  The current configuration of gatsby-plugin-google-tagmanager does not accommodate a renamed dataLayer and data pushed to a renamed dataLayer is inaccessible.  The proposed feature would include a plugin option (which would be optional) in gatsby-config.js to include the name of a renamed dataLayer, thereby making this data available to GTM.  

### Basic example

I will provide a real life example of why this feature is needed.  I used Gatsby to build landing pages that included an embedded interactive form.  This form has a GTM container configured to push events to a renamed dataLayer (named "bzDataLayer").  My employer renamed the dataLayer to "bzDataLayer" for the embedded application because it is hosted on numerous partner websites and there was concern that failure to do so could cause events from our form to be pushed to the dataLayer of a partner's GTM container and create conflicts.

The landing pages, which was configured in Gatsby to use a different GTM container, cannot access the custom events pushed to the form's "bzDataLayer."  As a result, I had to modify gatsby-plugin-google-tagmanager to make the renamed dataLayer accessible (see associated pull request for details).

### Motivation

Being unable to access custom events in a renamed dataLayer was a blocker for releasing the landing pages.  Although it may be relatively uncommon for developers to rename dataLayer, it is included as an option in the GTM documentation (https://developers.google.com/tag-manager/devguide#renaming).  As a result, it should be accounted for in Gatsby plugin.  Moreover, because of the prevalence and importance of GTM  (it was a blocker for our release), every effort should be made to ensure that gatsby-plugin-google-tagmanager can be configured to address all the needs of users.

**Comment by sidharthachatterjee** [comment]
Published in gatsby-plugin-google-tagmanager@2.0.11

Thank you @spwisner 🎉
