### ISSUE TITLE
Support disabling gatsby core to turns React components in src/pages into pages automatically

### ISSUE THREAD

**Issue by Terry-Su** [gatsbyjs/gatsby#12784]
## Description
For some reason, I'd like to use `createPage` api in `createPages` to create a home page with some custom data,like:
```js
createPage: {
  path: "/",
  component: path.resolve( __dirname, '...src/pages/index.tsx' ).
  context: {
    customData: 'customData'
  }
}
```
However, when visiting "/", it turns out the context hasn't been injected, that is, the home page is still the page create automatically by gatsby core as [docs demonstrates](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/).
> **Gatsby core automatically** turns React components in` src/pages` into pages

So I tried to look for a config to disable that feature, but with no luck.

### Steps to reproduce

As shown above

### Expected result

Can disable that gatsby turns React components in `src/pages` into pages automatically

### Actual result

Cannot

**Comment by universse** [comment]
You can use the gatsby-node onCreatePage API to inject context into automatically created page.
Something like this
```
exports.onCreatePage = ({ page, actions }) => {
  const { createPage, deletePage } = actions

  if (page.path === '/') {
    deletePage(page)

    createPage({
      ...page,
      context: {
        customData: 'customData'
      }
    })
  }
}
```

For more info, visit https://www.gatsbyjs.org/docs/creating-and-modifying-pages/

**Comment by Terry-Su** [comment]
@universse Thankful to your solution! Yes, it's one of solutions. However, it would be better if we can create "/"  page under `createPages`,  because it's more sensible and it's more convenient if there're some reused data under `createPages`.  Otherwise, we would  contract the reused data to outside for both `createPages` and `onCreatePage` apis.

**Comment by Terry-Su** [comment]
Btw, for people who encountered similar problem, I solved that by changing the target component's path:
```js
createPage: {
  path: "/",
  component: path.resolve( __dirname, '...src/pages/Home.tsx' ).
  context: {
    customData: 'customData'
  }
}
```

**Comment by universse** [comment]
> 
> 
> Btw, for people who encountered similar problem, I solved that by changing the target component's path:
> 
> ```js
> createPage: {
>   path: "/",
>   component: path.resolve( __dirname, '...src/pages/Home.tsx' ).
>   context: {
>     customData: 'customData'
>   }
> }
> ```
If I'm not wrong, with that approach you would create an extra /home path since it is automatically created.

**Comment by Terry-Su** [comment]
@universse  Yep. It's not the best solution, so I hope there should be a "switch" in gatsby to toggle the feature: "turns React components in src/pages into pages automatically" so that we needn't create extra /home route.

**Comment by wardpeet** [comment]
We want to keep gatsby as simple as possible so we won't change our convention at this time. We suggest going for https://www.gatsbyjs.org/docs/creating-and-modifying-pages/ as stated above.

It seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪
