### ISSUE TITLE
Markdown rich link to other md file

### ISSUE THREAD

**Issue by vojtechruz** [gatsbyjs/gatsby#12792]
I would kindly like to ask for guidance with a plugin I would like to write.

I have a Gatsby blog with markdown posts. In the middle of a blog post, I want to reference another post with a rich link. Something like this:

![link](https://user-images.githubusercontent.com/7038612/54868247-d1ab4980-4d8a-11e9-81cb-e14a7e795d7a.png)

You can see, it is not a simple text link, but it contains a whole lot of information from frontmatter of the linked post such as:
- title
- excerpts
- tags
- date
- featured image

Another limitation is that you do that in the middle of the blog post not something like related articles after the end of your post.

So far I was able to implement this manually - [that is including HTML in my markdown](https://raw.githubusercontent.com/vojtechruz/vojtechruzicka-blog/master/src/posts/spring-boot-actuator/index.md). That has, of course, many disadvantages such as:
- No support for gatsby image handling
- Does not reflect changes in frontmatter of the linked post
- does pollute MD files with a lot of HTML
- if you want to change HTML structure, you need to do it at many places.

My idea was to create a plugin for gatsby-transformer-remark. I would then use custom element in markdown such as

![linked-post][post-id]

The plugin would translate this into HTML while using graphql query to load all the metadata about the linked post.

Is this achievable or is it the best approach? I am not sure you can even access graphql and other posts when processing markdown.

Another approach which I thought about was combining markdown and react components and I discovered there is MDX. Is it a better approach?

Thank you for advice.

**Comment by LekoArts** [comment]
I can't answer you of the top of my head if this would be achievable with remark but you could try to use MDX with e.g. these:

- https://github.com/microlinkhq/sdk
- https://github.com/winhtaikaung/react-tiny-link

Would be interesting to see how that would work with `gatsby-link` specifically so that you still have the SPA feel for internal links 🤔

**Comment by vojtechruz** [comment]
Thanks for the reply. I wonder, if it is not possible to use graphql in remark transformer plugins could it still be a viable option to pass in all the frontmatter data directly as an input and just use existing plugins to do the work - eg. remark image for the thumbnail, something for the links etc.?
