### ISSUE TITLE
[gatsby-starter-default] Multiple text-shadows in the header with typography.js

### ISSUE THREAD

**Issue by RikoSmith** [gatsbyjs/gatsby#12796]
## Description

Header title has several text-shadows after adding to [gatsby-starter-default](https://github.com/gatsbyjs/gatsby-starter-default) according to [tutorial-3](https://www.gatsbyjs.org/tutorial/part-three/#using-plugins). Although there is not any `text-shadow` in _[layout.css](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/src/components/layout.css)_ and `textShadow` in other [components](https://github.com/gatsbyjs/gatsby-starter-default/tree/master/src/components) and [pages](https://github.com/gatsbyjs/gatsby-starter-default/tree/master/src/pages), header acquires `text-shadow` according to web inspection tool (image 2). Seems to appear with the `Elk Glen` theme too (did not test with other themes).

### Steps to reproduce

1. `gatsby new my-default-starter https://github.com/gatsbyjs/gatsby-starter-default`
2. `cd my-default-starter/`
3. `npm install --save gatsby-plugin-typography react-typography typography typography-theme-fairy-gates`
4. Add this to `gatsby-config.js` along with other plugins: 
```javascript
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`,
      },
    },
  ],
}
```
5. Create `src/utils/typography.js` and insert: 
```javascript
import Typography from "typography"
import fairyGateTheme from "typography-theme-fairy-gates"

const typography = new Typography(fairyGateTheme)

export const { scale, rhythm, options } = typography
export default typography
```
6. Save and run `gatsby develop`
7. Observe error at `http://localhost:8000/`
### Expected result

Text style without shadows as pictured in [Typography demo](https://kyleamathews.github.io/typography.js/)

### Actual result

Image 1:
![image](https://user-images.githubusercontent.com/24265041/54869962-43ef4e80-4dca-11e9-8833-c27288771a3a.png)

Image 2:
![image](https://user-images.githubusercontent.com/24265041/54870103-67b39400-4dcc-11e9-9768-dc63e6da1f30.png)

### Environment
Node: v8.11.2
Gatsby: v2.4.17

Contents of `gatsby-config.js`: 
```javascript
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`,
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // 'gatsby-plugin-offline',
  ],
}
```

Contents of `package.json`:
```javascript
{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^2.2.5",
    "gatsby-image": "^2.0.34",
    "gatsby-plugin-manifest": "^2.0.24",
    "gatsby-plugin-offline": "^2.0.25",
    "gatsby-plugin-react-helmet": "^3.0.10",
    "gatsby-plugin-sharp": "^2.0.30",
    "gatsby-plugin-typography": "^2.2.10",
    "gatsby-source-filesystem": "^2.0.27",
    "gatsby-transformer-sharp": "^2.1.17",
    "prop-types": "^15.7.2",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-helmet": "^5.2.0",
    "react-typography": "^0.16.19",
    "typography": "^0.16.19",
    "typography-theme-fairy-gates": "^0.16.19"
  },
  "devDependencies": {
    "prettier": "^1.16.4"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write src/**/*.{js,jsx}",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\""
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
```

Output of  `gatsby info --clipboard` : 
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.2.5 => 2.2.5
    gatsby-image: ^2.0.34 => 2.0.34
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.10 => 3.0.10
    gatsby-plugin-sharp: ^2.0.30 => 2.0.30
    gatsby-plugin-typography: ^2.2.10 => 2.2.10
    gatsby-source-filesystem: ^2.0.27 => 2.0.27
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17

error UNHANDLED REJECTION

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:4970

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:66948

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:48777

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46934

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46949

Contents of `gatsby-ssr.js`, `gatsby-node.js` and `gatsby-browser.js` are the same as in the [gatsby-starter-default](https://github.com/gatsbyjs/gatsby-starter-default) (i.e. empty)

**Comment by RikoSmith** [comment]
Oh, I figured out that was a feature, not a bug. It can be disabled by disabling textShadow in the header.js.

**Comment by baerrach** [comment]
To fix this using Typorgraphy, see https://github.com/KyleAMathews/typography.js/issues/155#issuecomment-490715480

```
fairyGateTheme.overrideThemeStyles = () => ({
  a: {
    textShadow: `none`,
    backgroundImage: `none`,
  },
});

const typography = new Typography(fairyGateTheme);
```
