### ISSUE TITLE
Render a text from query??

### ISSUE THREAD

**Issue by aprather51** [gatsbyjs/gatsby#12798]
**Objective:** fetch, parse, and render array of data in string. 

**Create:**
created json _asset/data/_**link.json**
```js
[{
        "url": "https://www.google.com/"
    },
    {
        "url": "https://github.com/"
    },
     {
        "url": "https://twitter.com/"
    },
  {
        "url": "https://codesandbox.io/"
    }

]
```

installed `gatsby-transformer-json` package, setting up `gatsby-source-filesystem` **gatsby-config.js**...

**gatsby-config.js**
```js
	`gatsby-transformer-json`,
		{
		/* Data */
		resolve: `gatsby-source-filesystem`,
		   options: {
			name: `url`,
			   path: `${__dirname}/src/assets/data`
			}
		},
```

set up query using useStaticQuery method

_hooks_/**useUrls.js**
```js
import { useStaticQuery, graphql } from 'gatsby';

export const useUrls = () => {
	const { urls } = useStaticQuery(
		graphql`
			query {
				urls: allLinkJson {
					edges {
						node {
							url
						}
					}
				}
			}
		`
	);

	return { urls };
};

```

Components to fetch query and render text in array.
_components_/**UrlList.js**
```js
import React from 'react';
import { useUrls } from '../hooks/useUrls';

export const UrlList = () => {
	const { urls } = useUrls();
	return (
             <ul>
		   {urls.edges.map(({ node }, i) => (
		     <li>
		          <p>url: {urls.url}</p>
		     </li>
		   ))} 
	</ul>
	);
};

```

**Problem:** Unable to render Text String from array....
![render_result](https://user-images.githubusercontent.com/10257247/54871367-d965f080-4d80-11e9-9086-6ed413516632.jpg)

**Diagnosis** The, confirmed data is fetched. 

**Preforming Test**
Results from browser console
![image](https://user-images.githubusercontent.com/10257247/54871443-c43d9180-4d81-11e9-9ae6-d5f0a6abd3c6.png)

![image](https://user-images.githubusercontent.com/10257247/54871413-88a2c780-4d81-11e9-97bc-418f19eee3a6.png)

Result from GraphiQL
![image](https://user-images.githubusercontent.com/10257247/54871474-3ca45280-4d82-11e9-873e-acb3d6e68596.png)

Couldn't be able to figure out why Text isn't rendering... Please help.

**Comment by muescha** [comment]
`urls.url` -> `node.url`

**Comment by aprather51** [comment]
`node.url`!  feeling sick. Thank you @muescha

**Comment by muescha** [comment]
But anyhow. You can turn your issue into a doc/tutorial?

It shows how to query a json file with hooks and the new useStaticQuery :)

What you mean: @core/docs ?

**Comment by aprather51** [comment]
This docs i was referring to...
useStaticQuery -> https://www.gatsbyjs.org/blog/2019-02-20-introducing-use-static-query/
gatsby-transformer-json - https://www.gatsbyjs.org/packages/gatsby-transformer-json/
