### ISSUE TITLE
Upgrade to lodash 4.0

### ISSUE THREAD

**Issue by rossPatton** [gatsbyjs/gatsby#128]
Currently if you update the local `package.json` to use lodash 4.x, gatsby breaks.

![screen shot 2016-02-18 at 11 21 58 am](https://cloud.githubusercontent.com/assets/2379901/13155290/de6f4988-d631-11e5-827a-6600d8391533.jpg)

**Comment by KyleAMathews** [comment]
Already done :) https://github.com/gatsbyjs/gatsby/commit/e08ca39c901f234e5da8ab60d23167d6ee00607d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34

New release coming later today!
