### ISSUE TITLE
css order incorrect

### ISSUE THREAD

**Issue by ademilter** [gatsbyjs/gatsby#12804]
## Summary
global style comes under the header when it should be at the top

## Relevant information
layout.js
<img width="360" alt="Screen Shot 2019-03-24 at 16 09 22" src="https://user-images.githubusercontent.com/187922/54880013-2a451a00-4e51-11e9-811a-85fd4264c6a6.png">

source-code
<img width="483" alt="Screen Shot 2019-03-24 at 16 09 09" src="https://user-images.githubusercontent.com/187922/54880015-34671880-4e51-11e9-935c-753e2f175a1a.png">

**Comment by wardpeet** [comment]
Could you create a reproduction for us so we don't have to do the heavy lifting to test and create a fix.

**Comment by ademilter** [comment]
@wardpeet https://github.com/ademilter/is-this-error-gatsby

**Comment by kmcaloon** [comment]
Is no one else seeing this?  Looks like OP was using style components, but I am getting this same problem using gastby-plugin-sass and including my global styles within a shared layout.
