### ISSUE TITLE
[1.0] Scan for graphl queries in locations other than src. 

### ISSUE THREAD

**Issue by hobochild** [gatsbyjs/gatsby#1280]
Carried over from discussion here: https://github.com/resin-io/landr/issues/25

**Comment by craig-mulligan** [comment]
The problem: 

Right now the relay compiler scans for grapqhl queries and fragments for all js files in "src" as well as any page component, unfortunately if a plugin is exposing it's own components or the user is putting components in another directory they are never compiled and added to graphql.

**Comment by craig-mulligan** [comment]
I'd prefer to make the graphql compiler programatically accept paths via the bound actions api, in the same way you'd `createPages()` you could `setgraphqlCompileComponent` or something with a better name :)

**Comment by KyleAMathews** [comment]
>I'd prefer to make the graphql compiler programatically accept paths via the bound actions api, in the same way you'd createPages() you could setgraphqlCompileComponent or something with a better name :)

This would be great too I think — the problem is it doesn't solve the use case of someone wanting to install a Gatsby-specific component that has an included GraphQL fragment. Unless we treat these components as plugins basically and make people add them to their gatsby-config.js

**Comment by KyleAMathews** [comment]
This PR added support for plugins including fragments https://github.com/gatsbyjs/gatsby/pull/2320#issuecomment-334908799
