### ISSUE TITLE
Don't allow non-serializable types in node store

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#12819]
Currently we allow non-serializable types like functions on nodes. Mostly this seems to be the case when plugin options in `gatsby-config` allow functions, and the plugin configuration is included in `SitePlugin` nodes. This leads to the same node being different when loaded from cache.

Although we recreate plugins on every run, the nodes will still be different depending on if they have been serialized before (i.e. loaded from `.cache`) or not. This is because when plugin nodes are created, `createNode` will check `contentDigest` if the node has changed. Because `createContentDigest` itself calls `JSON.stringify`, functions will be treated there as `null` values, so to the `createNode` action it looks like the plugin node loaded from cache has not changed (even though it does not include the functions) and therefore only calls `touchNode`.

An example for this behavior is e.g. the repo provided [here](https://github.com/gatsbyjs/gatsby/issues/12770#issuecomment-475788446), where `gatsby-plugin-sass` allows specifying `postCssPlugins` as functions.

The bigger motivation behind this is also that swapping the serializer to `v8.serialize` would be easier because `v8` throws when it encounters a function.

**Comment by vladar** [comment]
Oh, turns out this was done in Materialization PR #16091
