### ISSUE TITLE
warning  'use strict' is unnecessary inside of modules  strict

### ISSUE THREAD

**Issue by oschade** [gatsbyjs/gatsby#12812]
## Description

I set up a repository with yarn workspaces like this one:

https://github.com/jlengstorf/gatsby-theme-style

I added a plugin in the packages-folder with a `gatsby-browser.js` file using jsx-syntax. This have to be compiled with babel. The compilation added a "use strict" add the top when using the preset "babel-preset-gatsby-package".

This causes the warning "warning  'use strict' is unnecessary inside of modules  strict"

### Steps to reproduce

Download the repository:
https://github.com/jlengstorf/gatsby-theme-style.git
Add a "gatsby-plugin-test" folder with an index file and a "gatsby-browser.js" file with the following content:

`"use strict";`

And run `yarn workspace site develop`

### Expected result

No warnings.

### Actual result

warning  'use strict' is unnecessary inside of modules  strict

### Environment

  System:
    OS: Windows 10
  Binaries:
    Yarn: 1.13.0

**Comment by yogeshkotadiya** [comment]
That's because in ES6 modules are strict by default so you don't have to use `"use strict";`.
[https://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code](https://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code)

**Comment by oschade** [comment]
> 
> 
> That's because in ES6 modules are strict by default so you don't have to use `"use strict";`.
> https://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code

But how to avoid this warning? There are a lot of plugins using this setup, for example the gatsby-plugin-glamor:

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-glamor

If I install it in the setup mentioned above, the error do not show up, even though the (compiled) gatsby-browser.js starts with `"use strict";` How could this be possible?

**Comment by wardpeet** [comment]
@oschade is it possible to upload the git repo with your changes so we can easily reproduce it?

**Comment by oschade** [comment]
I solved the problem by placing an .eslintrc-file into the "site" directory. I had one in the root-directory, but this seems to have no effects. Thank you for your advices!
