### ISSUE TITLE
[gatsby-source-wordpress] Disable image download via route blacklist?

### ISSUE THREAD

**Issue by lucassilvagc** [gatsbyjs/gatsby#12827]
At this point, I'm stuck to what's happening on issue #6654 (I'm also reporting my problems there, by the way) - and I'm thinking if it's possible to skip the image files via route blacklist (or just by leaving images off the whitelist) without creating major problems on my execution. If the answer is yes, then I'd be able to compile and check for errors in the code, while leaving the images (according to the issue) for later. 

Is this right or letting images out of the equation would be too dangerous?

**Comment by davidmann4** [comment]
see https://github.com/gatsbyjs/gatsby/issues/15560 for possible solutions
