### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by roslaneshellanoo** [gatsbyjs/gatsby#1282]
im getting this warning:
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by jeffpamer** [comment]
From expanding the warning details it appears to be generated by the react-router-scroll package
![image](https://user-images.githubusercontent.com/888818/27664686-cb718012-5c1d-11e7-81b7-7fdd59446efe.png)

It looks like Gatsby is using a [fork](https://github.com/ytase/react-router-scroll) of this library that does not have issues enabled.

**Comment by joeycrypto420** [comment]
what doesthis mean? popup.js:69428 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
printWarning @ popup.js:69428

**Comment by ahfarmer** [comment]
@joeycrypto420 it means you are supposed to install the `prop-types` package and import it separately from React with `import PropTypes from 'prop-types'`. The problem in this case is that the `react-router-scroll` package is generating the warning. So the issue either has to be fixed there, or Gatsby needs to stop using that package.

**Comment by KyleAMathews** [comment]
We're not using react-router-scroll anymore (we forked it) so closing this issue.
