### ISSUE TITLE
npm install -g gatsby-cli error <rollbackFailedOptional>

### ISSUE THREAD

**Issue by unixph** [gatsbyjs/gatsby#12820]
Hi,

I am getting this erro when trying to install gatsby-cli. Can you please help???

-sh-4.2$ node --version
v10.15.3

-sh-4.2$ npm --version
6.4.1

-sh-4.2$ git --version
git version 1.8.3.1

-sh-4.2$ npm install -g gatsby-cli
[..................] / rollbackFailedOptional: verb npm-session 10dbb2ad593c8b68

I've tried these, but still doesn't work.
-sh-4.2$ npm config rm https-proxy
-sh-4.2$ npm install -g gatsby-cli

**Comment by wardpeet** [comment]
this is weird, I don't have any issue with installing gatsby on node 10.15.3. Does any other packages have the same issue?

Maybe reinstall node & npm and try again?

**Comment by unixph** [comment]
> this is weird, I don't have any issue with installing gatsby on node 10.15.3. Does any other packages have the same issue?
> 
> Maybe reinstall node & npm and try again?

Oh, found out that I'm not able to connect to npm registry as my server is not able to connect the internet. Is there an offline npm repo that I can use and install this?

**Comment by wardpeet** [comment]
Sadly it's really hard to have an offline npm mirror if you're never able to connect to the the internet. An options is to do your gatsby build on your local machine and ftp the public folder into your machine so no npm is needed on the server.

As stated, this is slightly tangential to Gatsby, and it seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪
