### ISSUE TITLE
gatsby image fadeIn duration

### ISSUE THREAD

**Issue by speexy** [gatsbyjs/gatsby#12836]
## Summary

Gatsby Image property fadeIn takes a numeric value instead of boolean and sets the duration of the transition to that value.

### Motivation

I am using traced svgs as placeholders. They are very pretty in themselves and are perfect if loading time is actually slow. However, when the actual images load fast, the placeholder is more irritating then helpful. The placeholder is visually so different that it needs to be seen a bit longer to appreciate the effect. I'd love to increase the transition duration via passing a property so that the effect visually works on both slow and fast connections.

**Comment by frinyvonnick** [comment]
I made a PR for it 😄
