### ISSUE TITLE
Clarification on Babel Polyfill Documentation

### ISSUE THREAD

**Issue by liamfd** [gatsbyjs/gatsby#12833]
## Summary
The language in the 1 -> 2 migration guide around the babel-polyfill is somewhat confusing, so I'd like to get some clarification if possible!

I originally asked this in another thread (https://github.com/gatsbyjs/gatsby/issues/7064#issuecomment-474875862), but I think it makes more sense as a standalone question.

## Relevant information
> ### Remove explicit polyfills
>
> If your Gatsby v1 site included any polyfills, you can remove them. Gatsby v2 ships with babel 7 and is configured to automatically include polyfills for your code. See Gatsby’s babel docs for more details.
>
> > Note: This works for your own code, but is not yet implemented for code imported from node_modules. Track progress of this feature at [bullet 5 of this issue](https://github.com/gatsbyjs/gatsby/issues/3870).

I'm confused by this because my understanding is that `babel-polyfill` makes its changes globally (as opposed to injecting things into the scope of each module). That seems to match what [its docs](https://babeljs.io/docs/en/babel-polyfill#docsNav) say:

>The polyfill adds to the global scope as well as native prototypes like String in order to do this.

If that's the case, what does the migration guide mean when it says that this is "not yet implemented for code imported from node_modules"? I would think that the node_modules code would have access to the polyfills if they're in the global scope.

Is the issue that, because Gatsby uses `useBuiltIns: 'usage'`, and because out of the box Gatsby does not transpile `node_modules`, babel may not inject the polyfills required by those `node_modules` because babel never sees their code? Meaning, if some of the transpiled code did require the same polyfills, they would be available to the code from node_modules, but if not, the polyfill would never get injected.

Finally (and maybe most importantly), since React [requires `Map` and `Set`](https://reactjs.org/docs/javascript-environment-requirements.html), does this caveat mean that Gatsby 2 may not work out of the box for older browsers, because there's no guarantee that they would get polyfilled?

I'm happy to contribute back to the docs on this if applicable.

### Environment (if relevant)
N/a

### File contents (if changed)
N/a

**Comment by benjaminhoffman** [comment]
+1 . @liamfd did you find a fix for this?

for v1, this worked for me for production builds:
```
current.entry.app = ['babel-polyfill', current.entry.app];
```

**Comment by Undistraction** [comment]
@liamfd Gatsby will only polyfill code within your project. If you are using third party modules that need polyfills that _have not been needed within your project code_, the polyfills will be missing at runtime and cause hard-to-debug errors.
