### ISSUE TITLE
Webpack's dead code elimination cuts off global css imports in production builds

### ISSUE THREAD

**Issue by pristas-peter** [gatsbyjs/gatsby#12831]
## Description

Webpack's dead code elimination cuts off global css imports in production builds.

Create react app has a solution of setting field `sideEffects: true` to css loader like this:

```
              test: cssRegex,
              exclude: cssModuleRegex,
              use: getStyleLoaders({
                importLoaders: 1,
                sourceMap: isEnvProduction && shouldUseSourceMap,
              }),
              // Don't consider CSS imports dead code even if the
              // containing package claims to have no side effects.
              // Remove this when webpack adds a warning or an error for this.
              // See https://github.com/webpack/webpack/issues/6571
              sideEffects: true,
```

### Steps to reproduce
Create started project. Add global css imports with no side effects, for example:
```
import '@material/typography/dist/mdc.typography.css';
```
When you use require, everything works as expected:
```
require('@material/typography/dist/mdc.typography.css');
```

**Comment by wardpeet** [comment]
could you publish a small reproduction so we can test this? We might need to upgrade our loaders to accept a sideEffect property.
