### ISSUE TITLE
Bring tutorial into alignment with style guide section regarding reducing hyperlinks

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#12845]
## Summary

Bring tutorial into alignment with style guide section regarding reducing hyperlinks: https://www.gatsbyjs.org/contributing/gatsby-style-guide/#dont-make-users-think-more-than-is-necessary

All hyperlinks that aren't strictly necessary for beginners to complete the steps of the tutorial should be removed and/or moved to the bottom of the page in an "additional resources" section.

### Basic example

For example, this section has a link to 404 pages and to API docs, neither of which are necessary for beginners to complete the tasks of the tutorial. https://www.gatsbyjs.org/tutorial/part-one/#-using-the-link--component

### Motivation

We are doing this to make sure beginners don't get side-tracked more than is necessary. We want this tutorial to be as powerful as possible. It isn't easy to do this, and will likely require this kind of maintenance to bring it back into alignment with the style guide on a regular basis.

**Comment by amad-person** [comment]
I tried compiling a list of links that could potentially be shifted in the (awesome!) tutorial. Not sure about all of them, but included for the sake of discussion 😅

### 0. Set Up Your Development Environment
(This section describes prerequisites for the rest of the tutorial, so not sure if we should remove / shift the links)

#### [Overview of core technologies](https://www.gatsbyjs.org/tutorial/part-zero/#overview-of-core-technologies): 
- Links to HTML, CSS, JavaScript Codeacademy tutorials, and React and GraphQL tutorials
   > (Optional!) For a comprehensive introduction…

#### [Familiarize yourself with the command line](https://www.gatsbyjs.org/tutorial/part-zero/#familiarize-yourself-with-the-command-line):
- Codeacademy’s Command Line tutorial

#### [Familiarize yourself with npm](https://www.gatsbyjs.org/tutorial/part-zero/#familiarize-yourself-with-npm):
- ‘What is npm’

#### [Install Git](https://www.gatsbyjs.org/tutorial/part-zero/#install-git)
- ‘Git Handbook’

### 1. Get to know Gatsby building blocks

#### [Using Gatsby starters](https://www.gatsbyjs.org/tutorial/part-one/#using-gatsby-starters):
- List of existing and official community starters

#### [Building with components](https://www.gatsbyjs.org/tutorial/part-one/#building-with-components): 
- Building with Components docs page

#### [Linking between pages](https://www.gatsbyjs.org/tutorial/part-one/#linking-between-pages):
- 404 pages docs
- API docs for routing 

### 2. Introduction to styling in Gatsby

#### [Creating global styles with standard CSS files](https://www.gatsbyjs.org/tutorial/part-two/#creating-global-styles-with-standard-css-files):
- Link to gatsby-browser.js docs
- Link to docs for adding global styles with a shared layout component

### 3. Nested Layout Components

#### [Using Gatsby plugins](https://www.gatsbyjs.org/tutorial/part-two/#creating-global-styles-with-standard-css-files):
- Link to Plugin Library
- Link to gatsby-config.js docs

### 4. Data in Gatsby

#### [Recap of the first half of the tutorial](https://www.gatsbyjs.org/tutorial/part-four/#recap-of-first-half-of-the-tutorial):
- Link to in-depth tutorial on GraphQL

#### [Your first GraphQL query](https://www.gatsbyjs.org/tutorial/part-four/#your-first-graphql-query):
- Link to part 5 of tutorial 
- Link to part 7 of tutoral 

### 8. Preparing a site to go live

#### [Audit with Lighthouse](https://www.gatsbyjs.org/tutorial/part-eight/#audit-with-lighthouse):
- Link to part 1 for explaining what a production build is

Some of the links above are at the end of each subsection, would these need to be shifted to the bottom of the page?
