### ISSUE TITLE
No js document or window in Gatsby

### ISSUE THREAD

**Issue by donaldboulton** [gatsbyjs/gatsby#12849]
I am learning Gatsby but most of the react components I try to build with npm modules that have anything about document or window create build errors.  Like prism.js common for anyone to use gives me the following error
`error Building static HTML failed

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

  175 | 
  176 |         highlightAll: function(async, callback) {
> 177 |                 _.highlightAllUnder(document, async, callback);
      | ^
  178 |         },
  179 | 
  180 |         highlightAllUnder: function(container, async, callback) {

  WebpackError: ReferenceError: document is not defined`

react-comments and many many more.
I have learned how to get around this in gatsby-browsers.js or html.js, with my old non $ jquery scripts, but how do you fix this for npm modules???

**Comment by coreyward** [comment]
See: https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-window-is-defined

**Comment by donaldboulton** [comment]
Nice thanks for the reply, I will try that and get back to this.
Thanks
DOnald Boulton

**Comment by donaldboulton** [comment]
Example with the below worked
`if (typeof window !== `undefined`) {
  const module = require('prismjs')
}`

Adding to gatsby-node.js as [Gatsby]https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-window-is-defined) gave me the following error
` exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
> 101 |   if (stage === "build-html" {
      |                             ^
  102 |     actions.setWebpackConfig({
  103 |       module: {
  104 |         rules: [
error Command failed with exit code 1.`

Thanks for the info but I would still like to be able to tell webpack to overlook window and document errors in modules because some of the npm modules having document as a error being undefined.

**Comment by rajjeet** [comment]
Had the same issue. I had to add `if (typeof document !== undefined) ` or`if (typeof window !== undefined)` before using those browser objects in my client side JS. If you need to operate on those objects (i.e. `window.onscroll = your function`) then move the code into `componentDidMount()`
