### ISSUE TITLE
[Doc] Little warning about <Link />

### ISSUE THREAD

**Issue by Videl** [gatsbyjs/gatsby#12846]
Hello!

I started coding with Gatsby recently,I just set up CI/CD on my project and I didn't understand why my path prefixes were not working. I eventually found out I imported the wrong ``Link``,  React's instead of Gatsby. 

Would you guys be open to adding a little warning when Link is first introduced in the tutorial here?

https://www.gatsbyjs.org/tutorial/part-one/#linking-between-pages

Something like: 

> 💡 Heads up! Be sure to import Link from Gatsby and not @reach/router, ours handles url prefixes site-wide.

I think adding the warning about path prefixes can warn people it's important.

**Comment by coreyward** [comment]
The docs pretty clearly show `Link` being imported from Gatsby. Did you have previous experience with Reach Router that led you to believe the `Link` component was coming from there, or did something on the page lead you to that conclusion?

**Comment by Videl** [comment]
Just let Visual Studio Code import the first Link it could find. 
As I didn't know that React had a Link also defined, I didn't notice that I had imported the wrong one.
That's where I was coming from as a beginner in React and Gatsby.

**Comment by coreyward** [comment]
It doesn't sound like the VSCode recommendation was very helpful here, but I worry that mentioning Reach Router on the Link documentation will serve to confuse others who may not be using prefixes. Gatsby's `Link` does use Reach Router's, but that's an implementation detail and could change (it has in the past).

**Comment by Videl** [comment]
Fair enough. Must have been a beginner's mistake then
