### ISSUE TITLE
<link rel="prefetch"> _can_ interfere with loading higher priority resources so we should delay adding them

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#12850]
From @yoavweiss in https://github.com/gatsbyjs/gatsby/issues/12800#issuecomment-475979360

>I'd caution against heavily relying on prefetch's prioritization downgrade too much, as it [doesn't always prevent contention](https://bugs.chromium.org/p/chromium/issues/detail?id=651160) with resources for the current page, especially if their discovery is delayed. It might be better to inject those prefetches only after you know that the current page is fully rendered and interactive.

We add prefetch elements here https://github.com/gatsbyjs/gatsby/blob/c2b322af07ca7fbf312e8b5e3fee8e8c4090fff5/packages/gatsby/cache-dir/static-entry.js#L279

We should instead insert a JSON blob into the HTML with these hrefs and add them as link elements once the page is rendered/interactive.

**Comment by danielimmke** [comment]
I'd like to take this on.

**Comment by thall1961** [comment]
Do you still need help with this issue?
