### ISSUE TITLE
Testing Gatsby with Cypress fails when HTTPS is on

### ISSUE THREAD

**Issue by flaviolivolsi** [gatsbyjs/gatsby#12862]
Hi,

I followed [this guide](https://www.gatsbyjs.org/docs/end-to-end-testing/) which works fine, but not when I try to enable the HTTPS.

I normally work with the HTTPS enabled also in my local environment, because my app is heavily depending on the Facebook APIs which now require HTTPS also locally. 

The following works:

```
  "scripts": {
    "develop": "gatsby develop",
    "start": "npm run develop",
    "cypress:run": "cypress run",
    "test:cypress": "start-server-and-test start http://localhost:8000 cypress:run"
  },
```

whereas this doesn't:

```
  "scripts": {
    "develop": "gatsby develop --https",
    "start": "npm run develop",
    "cypress:run": "cypress run",
    "test:cypress": "start-server-and-test start https://localhost:8000 cypress:run"
  },
```

There is no error, when I run `yarn test:cypress` it just stops at the message `ℹ ｢wdm｣: Compiled successfully.`. Cypress doesn't run. Any ideas?

---

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.6.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.1.30 => 2.1.30 
    gatsby-image: ^2.0.20 => 2.0.20 
    gatsby-plugin-create-client-paths: ^2.0.2 => 2.0.5 
    gatsby-plugin-google-tagmanager: ^2.0.6 => 2.0.10 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.23 
    gatsby-plugin-netlify: ^2.0.4 => 2.0.12 
    gatsby-plugin-offline: ^2.0.11 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.9 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sass: ^2.0.4 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.12 => 2.0.27 
    gatsby-source-filesystem: ^2.0.4 => 2.0.24 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.16 
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

**Comment by flaviolivolsi** [comment]
I solved. The issue is referenced also [here](https://github.com/bahmutov/start-server-and-test/issues/152#issuecomment-474918461) and setting the variable `START_SERVER_AND_TEST_INSECURE=1` solved it.

**Comment by luichooy** [comment]
> I solved. The issue is referenced also [here](https://github.com/bahmutov/start-server-and-test/issues/152#issuecomment-474918461) and setting the variable `START_SERVER_AND_TEST_INSECURE=1` solved it.

would you teach me how to set variable `START_SERVER_AND_TEST_INSECURE=1` ?

I set it as beblow but no effect
```
"e2e": "START_SERVER_AND_TEST_INSECURE=1&& start-test dev-daily https://localhost:9000 cypress-open"
```
