### ISSUE TITLE
[1.0] Potential renaming of remark-responsive-image plugin

### ISSUE THREAD

**Issue by chiedo** [gatsbyjs/gatsby#1286]
I'm wondering if a better name for gatsby-remark-responsive-image would be gatsby-remark-build-images

My thinking is that the current name is a little misleading and the intent isn't clear. If I don't want images to be responsive, I may ignore that package all together not realizing that it's necessary to get my images from my markdown files so that they work in my build.

If we did change the name, then the default could be to just copy the default version of the image without creating all the responsive versions and we could have a responsive option that when set to true would do what it does now.

Just a thought. If it isn't helpful, feel free to ignore. :)

**Comment by KyleAMathews** [comment]
Hmmm that is a better name. You want to submit a PR? I can then deprecate the old package on NPM.

Keep the functionality the same though. Creating responsive versions should always be the default. If someone really cares enough to make an option for just copying images over then we could take a PR for that or they could make their own plugin.

**Comment by chiedo** [comment]
Deal!

I will submit the PR.

Thanks for being cool with new ideas.

**Comment by chiedo** [comment]
PR submitted! https://github.com/gatsbyjs/gatsby/pull/1288

**Comment by KyleAMathews** [comment]
Fixed in #1288
