### ISSUE TITLE
Line breaks ignored with remark-prismjs

### ISSUE THREAD

**Issue by alanshortis** [gatsbyjs/gatsby#12868]
## Summary

When using the remark prismjs plugin, I am having an issue with line breaks being ignored not being rendered. This doesn't happen with every line break though, just a few.

I have published the built page here: https://gatsby-whitespace.netlify.com/

## Relevant information

You'll see that the last closing bracket on the second code block is on the same line despite there being a line break in the source.

Things tried:

- Develop build vs production build.
- Disable prettier.
- Use tabs instead of spaces.
- Including a CSS theme.
- Pacing around.
- Swearing out loud at no one in particular.

Here is the full markdown file used to build this example: 

```
---
title: 'Testing'
date: '2019-03-26'
slug: '/test'
---

Without defining language:

    ```
    something: {
      somethingElse: 'thing'
    }
    ```

Defining language:

    ```javascript
    something: {
      somethingElse: 'thing'
    }
    ```
```

### Environment (if relevant)

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v11.6.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 65.0.2
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.31 => 2.1.37 
    gatsby-cli: ^2.4.16 => 2.4.16 
    gatsby-image: ^2.0.33 => 2.0.34 
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.9 => 3.0.10 
    gatsby-plugin-sharp: ^2.0.28 => 2.0.29 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-remark-prismjs: ^3.2.5 => 3.2.5 
    gatsby-source-filesystem: ^2.0.24 => 2.0.27 
    gatsby-transformer-remark: ^2.3.4 => 2.3.4 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.17
```

### File contents (if changed)

gatsby-config.js

```
module.exports = {
  siteMetadata: {
    title: 'title',
    description: 'desc,
    author: 'Alan Shortis',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-styled-components',
    '@danbruegge/gatsby-plugin-stylelint',
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-prismjs',
          },
        ],
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/posts`,
        name: 'posts',
      },
    },
  ],
};
```

gatsby-node.js

```
const path = require('path');

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions;
  return new Promise(resolve => {
    graphql(`
      {
        allMarkdownRemark {
          edges {
            node {
              frontmatter {
                slug
              }
            }
          }
        }
      }
    `).then(results => {
      results.data.allMarkdownRemark.edges.forEach(({ node }) => {
        createPage({
          path: node.frontmatter.slug,
          component: path.resolve('./src/components/Post.js'),
          context: {
            slug: node.frontmatter.slug,
          },
        });
      });
    });
    resolve();
  });
};
```
package.json

```
{
  "name": "short.is",
  "private": true,
  "description": "Alan Shortis is a web developer",
  "version": "2.0.0",
  "author": "Alan Shortis",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "lint:js": "eslint 'src/**/*.js'",
    "lint:style": "stylelint 'src/**/*.js'"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/alanshortis/short.is"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.js": [
      "npm run lint:js",
      "npm run lint:style"
    ]
  },
  "dependencies": {
    "babel-plugin-styled-components": "^1.10.0",
    "gatsby": "^2.1.31",
    "gatsby-cli": "^2.4.16",
    "gatsby-image": "^2.0.33",
    "gatsby-plugin-manifest": "^2.0.24",
    "gatsby-plugin-offline": "^2.0.25",
    "gatsby-plugin-react-helmet": "^3.0.9",
    "gatsby-plugin-sharp": "^2.0.28",
    "gatsby-plugin-styled-components": "^3.0.7",
    "gatsby-remark-prismjs": "^3.2.5",
    "gatsby-source-filesystem": "^2.0.24",
    "gatsby-transformer-remark": "^2.3.4",
    "gatsby-transformer-sharp": "^2.1.17",
    "prismjs": "^1.15.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-helmet": "^5.2.0",
    "react-html-parser": "^2.0.2",
    "styled-components": "^4.1.3"
  },
  "devDependencies": {
    "@danbruegge/gatsby-plugin-stylelint": "^3.4.0",
    "eslint": "^5.3.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.12.4",
    "husky": "^1.3.1",
    "lint-staged": "^8.1.5",
    "prettier": "^1.16.4",
    "stylelint": "^9.10.1",
    "stylelint-config-recommended": "^2.1.0",
    "stylelint-config-styled-components": "^0.1.1",
    "stylelint-processor-styled-components": "^1.5.2"
  }
}

```

**Comment by wardpeet** [comment]
Thanks for adding the reproduction steps! it would be handier if you publish a git repo we can use to validate that. Would that be possible?

**Comment by tenphi** [comment]
The same here.

@alanshortis  Did you manage to fix this?

**Comment by alanshortis** [comment]
> The same here.
> 
> @alanshortis Did you manage to fix this?

Unfortunately not. I actually switched to Next.js not long after, which I've been really enjoying.

**Comment by dgarcia360** [comment]
The same problem here.

@tenphi, did you manage to solve it?
