### ISSUE TITLE
-develop not connecting to localhost because "TypeError: receiver.on is not a function" 

### ISSUE THREAD

**Issue by celinepark94** [gatsbyjs/gatsby#12874]
## Summary
`gatbsy develop` is not connecting to my localhost:8000
LocalHost says "site can't be reached, localhost refused to connect" or shows a blank page

Why is it doing this? I am new to gatsby and react in general. I'm not sure if my computer is acting up somehow or if there's an issue with gatsby or if I've just done something wrong...

Does anyone know? Thank you so much for the help :)

## Relevant information
It seems like it suddenly stopped working. It was fine last night, I didn't run any updates since then.

here's what the terminal throws when i try to run develop

```
ℹ ｢wdm｣: Compiled with warnings.
error UNHANDLED EXCEPTION


  TypeError: receiver.on is not a function
  
  - websocket.js:141 WebSocket.setSocket
    [Portfolio]/[ws]/lib/websocket.js:141:14
  
  - websocket-server.js:305 WebSocketServer.completeUpgrade
    [Portfolio]/[ws]/lib/websocket-server.js:305:8
  
  - websocket-server.js:236 WebSocketServer.handleUpgrade
    [Portfolio]/[ws]/lib/websocket-server.js:236:10
  
  - server.js:361 
    [Portfolio]/[engine.io]/lib/server.js:361:13
  
  - server.js:171 Server.verify
    [Portfolio]/[engine.io]/lib/server.js:171:3
  
  - server.js:351 Server.handleUpgrade
    [Portfolio]/[engine.io]/lib/server.js:351:8
  
  - server.js:478 Server.<anonymous>
    [Portfolio]/[engine.io]/lib/server.js:478:14
```

Before that it seems like it's compiling everything with some warnings that I imported a component but it was never used.

here is a screenshot of the errors on the console
![image](https://user-images.githubusercontent.com/4051426/55023788-f21a1480-4fd3-11e9-841b-8847c1458865.png)

### Environment (if relevant)
I'm not sure what is relevant but I use a Macbook. 
I'm using the gatsby starter pack
The gatsby version is 2.2.12

```
Celines-MBP:Portfolio celine$ gatsby info --clipboard

  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.1.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.2.12 => 2.2.12 
    gatsby-cli: ^2.4.7 => 2.4.7 
    gatsby-image: ^2.0.20 => 2.0.20 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.9 
    gatsby-plugin-offline: ^2.0.16 => 2.0.16 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2 
    gatsby-plugin-sharp: ^2.0.14 => 2.0.14 
    gatsby-source-filesystem: ^2.0.8 => 2.0.8 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.5
    gatsby: 2.2.12
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by celinepark94** [comment]
just tried deploying it on netlify and it works fine...

**Comment by wardpeet** [comment]
this is a bit weird. Do you have an edited host file or some weird firewall rules on?

you could try `gatsby develop -p 4000` to run it on another port.

**Comment by celinepark94** [comment]
ended up deleting cache and npm and reinstalling everything and it seems like its working now
