### ISSUE TITLE
docs: add new Gatsby Cheat Sheet

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#12881]
## Summary

We have a beautiful new Gatsby Cheat Sheet that needs to be added to the docs! I think it could live under Quick Start and Recipes, as those are the most related introductory areas of the docs.

This involves:
- Creating a new page and linking it in the docs sidebar
- Embedding the two cheat sheet pages as graphics
- Providing adequate alt text: likely some visually hidden lists / tables with the cheat sheet content (this does run the risk of becoming outdated...but it's better than forcing users with accessibility needs to download / use a PDF)
- [Tagging the PDF](https://helpx.adobe.com/acrobat/using/create-verify-pdf-accessibility.html) so that headings and content are properly exposed. @fk how was the document created? E.g. there is a checkbox in Adobe Illustrator that could help.
- Adding a link to download the PDF

I can take this on, I don't anticipate it being a huge amount of work but I wanted to capture it in an issue here.

**Comment by fk** [comment]
> how was the document created? E.g. there is a checkbox in Adobe Illustrator that could help.

**Comment by marcysutton** [comment]
re: InDesign: that is what I meant, so perfect! I'm happy to help with that, or you can find some docs here: https://helpx.adobe.com/indesign/using/structuring-pdfs.html
