### ISSUE TITLE
New plugin: gatsby-remark-lint

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#12882]
## Summary

In discussing a potential improvement to the .org site (adding a [remark lint plugin for link text](https://github.com/mapbox/remark-lint-link-text)), @pieh suggested creating a new plugin: `gatsby-remark-lint`. This would make it much easier to use [remark-lint](https://github.com/remarkjs/remark-lint) with Gatsby, including the aforementioned plugin.

This is open for member(s) of the community to take on, if we don't get around to it first!

**Comment by tsriram** [comment]
I'll give this a go :pray:

**Comment by tsriram** [comment]
Okay, I started with this but not sure if I'm doing it right. Should `gatsby-remark-lint` only install `remark-lint` as a dependency and users can install other presets & plugins for `remark-lint` that can be passed as options to this plugin? 

So once user has installed `gatsby-remark-lint`, installed any of its plugins they can add it as a plugin to `gatsby-transformer-remark` which should take care of running the lint plugin against all markdown files. Does this make sense? Would appreciate any input.

**Comment by marcysutton** [comment]
That makes sense, @tsriram! Perhaps you could start by posting an API example with a snippet of a `gatsby-config.js` file, showing how the plugin could be used. We could discuss before it's committed to code, if that helps!

**Comment by zslabs** [comment]
This would be a great addition! Was looking into this myself, but running into some roadblocks.

**Comment by alexluong** [comment]
Hey @tsriram do you have any updates on this? I'd love to jump in and help if you're running into some issues or are too busy.

**Comment by dskvr** [comment]
Is this dead?
