### ISSUE TITLE
Missing dependency for babel-plugin-remove-graphql-queries

### ISSUE THREAD

**Issue by arizonatribe** [gatsbyjs/gatsby#12890]
I'm sure `babel-plugin-remove-graphql-queries` is just intended as an internal package, but I was interested in it using it nonetheless. But when I pulled it into the Babel plugins list for my non-Gatsby project, it threw this error that seems unintended.

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'gatsby/graphql'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/projects/some-non-gatsby-project/node_modules/babel-plugin-remove-graphql-queries/index.js:8:17)
```

It's [pulling in the `gatsby/graphql` package](https://github.com/gatsbyjs/gatsby/blob/0f0feac9c7ebb1b18208bbbc584f3cddc5f31a72/packages/babel-plugin-remove-graphql-queries/src/index.js#L2), which is failing for me because `gatsby` isn't listed among the dependencies for `babel-plugin-remove-graphql-queries`.

I'm guessing this doesn't happen when developing Gatsby because it's part of a multi-package repo where symlinking is happening via `lerna` or some custom module resolver, so I'm not sure if there's an unintended side-effect of declaring a direct dependency on `gatsby`. Hopefully not, but If there is could it perhaps be made a peer dependency?

**Comment by wardpeet** [comment]
Yeah, `gatsby` is available because of lerna yes. We aren't opposed to making it a peerDependency & adding it to devDependencies to be up to date with a valid package.json. You still need to have gatsby or alias the package as we're using it inside the babel transform

**Comment by ashley** [comment]
Hey, I was wondering if I can take this issue up as my first `good first issue`? 😃

**Comment by arizonatribe** [comment]
Actually nevermind. It looks like [someone fixed it](https://github.com/arizonatribe/gatsby/commit/5a4c60c30ea7e0e35fae6eb9eab142062bbf0618) already and it got merged in several minutes ago.

**Comment by arizonatribe** [comment]
Was 8+ minutes to clone Gatsby, so had some time to kill and found it, lol.

**Comment by wardpeet** [comment]
you should clone with --depth=1 than it shouldn't take so long 👍

**Comment by arizonatribe** [comment]
Oh, thanks for the tip!
