### ISSUE TITLE
Hot reloading breaks when adding new packages

### ISSUE THREAD

**Issue by Param-Harrison** [gatsbyjs/gatsby#12892]
## Description

When adding new packages in the new terminal, the `gatsby develop` window throw errors and don't recover back even after the package finished getting installed. Have to restart again everytime

### Steps to reproduce

- Run `yarn start`
- open new terminal and add new package - `yarn add <package>`
- the dev terminal break into error and won't recover back

### Expected result

- develop process should run and restart automatically

### Actual result

- Not restarted after error

### Environment

 System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.6.2 - /usr/local/bin/zsh
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 65.0
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.2.13 => 2.2.13 
    gatsby-image: ^2.0.33 => 2.0.34 
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6 
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-prefetch-google-fonts: ^1.4.0 => 1.4.0 
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.11 
    gatsby-plugin-sharp: ^2.0.31 => 2.0.31 
    gatsby-plugin-typography: ^2.2.10 => 2.2.10 
    gatsby-source-filesystem: ^2.0.28 => 2.0.28 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.11

**Comment by wardpeet** [comment]
@Param-Harrison could you explain what error you get?

**Comment by Param-Harrison** [comment]
@wardpeet Here you go, this is the error. Its related to cache for typography.js
```
 ERROR  Failed to compile with 1 errors               08:16:36

 error  in ./node_modules/gatsby-plugin-typography/.cache/typography.js

Module build failed: Error: ENOENT: no such file or directory, open '/Users/Param/Jobbatical/homepage/node_modules/gatsby-plugin-typography/.cache/typography.js'

 @ ./node_modules/gatsby-plugin-typography/gatsby-browser.js 14:25-58
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

✖ ｢wdm｣: 
ERROR in ./node_modules/gatsby-plugin-typography/.cache/typography.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/Param/Jobbatical/homepage/node_modules/gatsby-plugin-typography/.cache/typography.js'
 @ ./node_modules/gatsby-plugin-typography/gatsby-browser.js 14:25-58
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.
```

**Comment by wardpeet** [comment]
That probably has to do with typography creating some files when bootstrapping. Unsure how easy it is to fix.

**Comment by Param-Harrison** [comment]
No problem @wardpeet. I will also check what might be wrong in my typo setup and ping the solution if I find anything useful
