### ISSUE TITLE
Assigning to process.env results in "Uncaught SyntaxError: Unexpected token ." 

### ISSUE THREAD

**Issue by tobiasandersen** [gatsbyjs/gatsby#12901]
## Description
If I do this (anywhere):

```
process.env.MY_VARIABLE = 'test'
```

It gets compiled to:

```
{}.MY_VARIABLE = 'test';
```

Which isn't legal, so it throws the following error:

```
Uncaught SyntaxError: Unexpected token .
```

Note: this is not how I'm actually using it (it's a [dependency](https://github.com/isaacs/pseudomap/blob/master/map.js) that's doing it), so I'm not looking for alternative solutions.

### Steps to reproduce

Start a clean Gatsby project, and add a line where you assign something to `process.env`, e.g. `process.env.MY_VARIABLE = 'test'`. [Here's a project](https://github.com/tobiasandersen/gatsby-site) where I did:

1. `gatsby new gatsby-site`
2. Added `process.env.MY_VARIABLE = 'test'` to `src/pages/index.js`
 
### Expected result
It shouldn't mess with `process.env`

### Actual result
It replaces `process.env` with `{}`, and thus breaks the site.

### Environment
```
  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 63.0.3
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.2.13 => 2.2.13 
    gatsby-image: ^2.0.34 => 2.0.34 
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.11 
    gatsby-plugin-sharp: ^2.0.31 => 2.0.31 
    gatsby-source-filesystem: ^2.0.28 => 2.0.28 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.14
```

**Comment by wardpeet** [comment]
For more information on process.env vars in gatsby can be found at https://www.gatsbyjs.org/docs/environment-variables/#client-side-javascript. To make this work for you you'll have to prefix it with `GATSBY_` so `process.env.GATSBY_MY_VARIABLE = 'test'`

**Comment by tobiasandersen** [comment]
I'm not the one assigning to `process.env` — it's a dependency deep down the tree. I'm not even dependant on the variable being set, but since it gets transpiled to illegal code I can't use it.

**Comment by wardpeet** [comment]
Sadly there is nothing we can do about it as it's bad practice to edit process.env variables inside a web applications. The problem isn't gatsby related but it's Webpack's DefinePlugin so sadly I'm not able to help you any further but to look for another npm package.

**Comment by tobiasandersen** [comment]
Alright thanks, no problem! I've already replaced the package in question, was mostly curious why it behaved like this. I'll close it out, thanks for your answers!
