### ISSUE TITLE
Docs: new page on Working With Video

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#12903]
## Summary

As part of improving the docs for common Gatsby workflows, one gap I noticed in the [Images and Files](https://www.gatsbyjs.org/docs/images-and-files/) documentation is around working with video (and audio?).

There is a new stub file coming that will include a few video suggestions, however, it should be filled out more with additional tips on video best practices in Gatsby sites (especially if there are any new plugins or techniques that do things "The Gatsby Way", which there aren't right now).

Things a video doc should include:

- How to source hosted video files: copying embeds from Youtube, Vimeo, etc.
    - Including a `title` attribute on the iframe for accessibility
- Hosting your own video files
    - A bit on codecs and formats
    - Streaming advice?
- Sourcing video files with GraphQL
- Techniques for embedding video in Gatsby/React sites
    - Creating a reusable video player component
    - Controls and options with the HTML5 video tag
    - Encouraging use of captions and subtitles
- Recommended video players for React
    - Paypal: https://github.com/paypal/accessible-html5-video-player#react-version

**Comment by janosh** [comment]
Definitely mention [gatsby-remark-embed-video](https://www.gatsbyjs.org/packages/gatsby-remark-embed-video/?=gatsby-remark-embed-video).

**Comment by marcysutton** [comment]
Closed with #12906.

**Comment by Paddy888** [comment]
I have tried following this tutorial but it is not working for me. 

I created compontents/video.js and pasted

`const Video = ({ videoSrcURL, videoTitle, ...props }) => (
  <div className="video">
    <iframe
      src={videoSrcURL}
      title={videoTitle}
      allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
      frameBorder="0"
      webkitallowfullscreen="true"
      mozallowfullscreen="true"
      allowFullScreen
    />
  </div>
)`

Then 404.js:

`mport React from "react"

import Layout from "../components/layout"
import Video from "../components/video"

const NotFoundPage = () => (
  <Layout>
    
    <section>
      <h1>NOT FOUND</h1>
      <p>You just hit a page that doesn't exist... the sadness.</p>
      <p>May I suggest a video instead?</p>
      <Video
        videoSrcURL="https://www.youtube.com/embed/dQw4w9WgXcQ"
        videoTitle="Official Music Video on YouTube"
      />
    </section>
  </Layout>
)

export default NotFoundPage`

Error:

3:7  warning  'Video' is assigned a value but never used  no-unused-vars

✖ 1 problem (0 errors, 1 warning)


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 warning  in ./src/pages/404.js

"export 'default' (imported as 'Video') was not found in '../components/video'
