### ISSUE TITLE
Some css classes missing from build output

### ISSUE THREAD

**Issue by alfredvaa** [gatsbyjs/gatsby#12908]
## Description

I noticed that the css differs between the `gatsby develop` and `gatsby build`. Almost everything is similar on both but some css classes are missing from the build css. It seems that if a class is only used in an unusual way it is not included when building gatsby.

Classes that are missing from the build output are those referenced like this:

```
<div className={`col-${i === 0 ? "7" : "5"}`}></div>
```

and also the `styles` in CSSTransition (using `react-transition-group` and css modules) are missing.

```
<CSSTransition
          in={this.state.show}
          timeout={1000}
          classNames={styles}
        >
          <div className={s.children}>{children}</div>
        </CSSTransition>
```

What works as it should is references like (using css modules):

```
<div className={s.container}></div>
```

and (using global bootstrap):

```
<div className="col-6"></div>
``` 

### Steps to reproduce

1. Add this to a gatsby project (with `react-transition-group` and `bootstrap` installed) and run `gatsby build`:

```
import "bootstrap/dist/css/bootstrap.css";
```

```
<div className={`col-${i === 0 ? "7" : "5"}`}></div>
<CSSTransition
  in={this.state.show}
  timeout={1000}
  classNames={styles}
>
    <div className={s.children}>{children}</div>
</CSSTransition>
```

2. Run a find command in the `/public` folder for `col-5`.

### Expected result

Css classes should be included in the build output.

### Actual result

Css classes was not included in the build output.

### Environment

  System:
    OS: macOS 10.14.1
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.6.0 - ~/.nvm/versions/node/v10.6.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.6.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 65.0.1
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.0 => 2.0.7 
    gatsby-awesome-pagination: ^0.3.3 => 0.3.3 
    gatsby-image: ^2.0.31 => 2.0.31 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.1 
    gatsby-plugin-netlify: ^2.0.0 => 2.0.0 
    gatsby-plugin-purgecss: ^2.4.0 => 2.4.0 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5 
    gatsby-plugin-typescript: ^2.0.9 => 2.0.9 
    gatsby-remark-images: ^2.0.1 => 2.0.1 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-source-wordpress: ^3.0.1 => 3.0.1 
    gatsby-transformer-remark: ^2.1.1 => 2.1.3 
    gatsby-transformer-sharp: ^2.1.1 => 2.1.1

**Comment by alfredvaa** [comment]
A hotfix I found for now is to add a div below the `CSSTransition` which has all the classes of the `styles`-variable.

```
<CSSTransition
  in={this.state.show}
  timeout={1000}
  classNames={styles}
>
    <div className={s.children}>{children}</div>
</CSSTransition>
<div className={`${styles.enter} ${styles.enterActive}`} />
```

this will include all transition classes in the build output which will make the CSSTransition work in the production build.

**Comment by anantoghosh** [comment]
This looks like an issue caused by [`gatsby-plugin-purgecss`](https://github.com/anantoghosh/gatsby-plugin-purgecss).
There are various ways documented on how to deal with this in the readme or if you do not need the plugin, just remove it.
