### ISSUE TITLE
Is it possible to modify the frontmatter field in onCreateNode for a certain purpose?

### ISSUE THREAD

**Issue by mostearly** [gatsbyjs/gatsby#12913]
I tried to modify the `frontmatter` field obtained in `onCreateNode` in the `gatsby-node.js` code. The code was correctly output to graphql and it reached my expected result.

I don't know what the downside of this behavior is. What kind of harm will this lead to?

**Comment by DSchau** [comment]
@mostearly sorry we missed this!

Generally, we recommend using `createNodeField` for this, which will then make a `fields` _field_ with your extended data.

For example:

```js
exports.onCreateNode = function onCreateNode({ actions, node }) {
  if (node.internal.type === 'MarkdownRemark') {
    actions.createNodeField({
      name: `slug`,
      value: `/whatever/based/on/node`,
      node
    })
  }
}
```

then you can query with GraphQL like:

```graphql
{
  markdownRemark(fields: { slug: { eq: "/whatever" }}) {
    id
    html
  }
}
```

Closing as answered! Thanks for the question, please reply or re-open if we can help further!

**Comment by janosh** [comment]
@DSchau `createNodeField` does have the disadvantage of splitting relevant data for page creation into two objects. Instead of everything being nicely contained in `frontmatter`, it's now partly in `frontmatter` and partly in `fields`. I read repeatedly that `createNodeField` is recommended over in-place modification but I was wondering what exactly could go wrong here. Could you elaborate? Could it interfere with plugins or cache?

**Comment by janosh** [comment]
@DSchau ☝️

**Comment by rori4** [comment]
why is this closed?

**Comment by CalamarBicefalo** [comment]
Would be good to understand this indeed :)

**Comment by bytrangle** [comment]
I'd like to know more about the downsides of in-place modification of frontmatter fields. `gatsby-transformer-remark` and `gatsby-plugin-mdx` both take the latter approach to modify a field that references an image file and turns it into Sharp's responsive image data.

So, what could possibly go wrong if third-party plugins try to do the same? :)

**Comment by natapg** [comment]
I'm doing some in-place modifications, but now in gatsby v4 is not working anymore (just in build, not in development), it's taking the original field values, not the modified ones...

**Comment by verystack** [comment]
Bump. This has vanished in Gatsby v4 in production only. Very annoying.

**Comment by walpoletim** [comment]
Same issue - production Nodes updated in place are lost - works in development t
