### ISSUE TITLE
gatsby-plugin-sitemap NoURLProtocolError: Protocol is required

### ISSUE THREAD

**Issue by pawelotto** [gatsbyjs/gatsby#12912]
While building the site with gatsby-plugin-sitemap I get the 
```NoURLProtocolError: Protocol is required```
error.

Why?

**Comment by wardpeet** [comment]
Could you give us some more information about your configuration and maybe just push your code online so we can have a look at it?

Please look at https://github.com/gatsbyjs/gatsby/blob/master/.github/ISSUE_TEMPLATE/bug_report.md to tell us more about this issue.

**Comment by pawelotto** [comment]
I've discovered that this error only occurs when I use a custom query and when I have no `siteUrl` defined in the `siteMetadata`. I've been using `siteRoot` instead of `siteUrl` and when I add the `siteUrl` everything works OK.

**Comment by wardpeet** [comment]
Oh yeah siteUrl is mandatory. It's probably a good idea to throw an error when this happens instead of showing a weird error.

**Comment by ryandrew14** [comment]
I will go dig into this over the weekend!

**Comment by sidharthachatterjee** [comment]
Fix for this was published in `gatsby-plugin-sitemap@2.0.12` courtesy of @sbardian 🎉
