### ISSUE TITLE
Expose API to programmatically set plugin configuration options at runtime

### ISSUE THREAD

**Issue by thebigredgeek** [gatsbyjs/gatsby#12919]
## Summary

In Gatsby Cloud Preview, users currently have to modify their Contentful Source Plugin configuration in order to complete onboarding.  This adds a massive hurdle for our users to jump over in order to complete onboarding.  If there was a way for Cloud code to call a set of methods and set configuration values for plugins at run time, we could extract the above values from Contentful's Management APIs ourselves and plug in the values.  This would provide a magically feeling experience for our end users, as well as reduce the amount of time necessary for time-to-value.  This would also open the door to some potentially interesting patterns for our OSS power users!

### Basic example

We should nail down implementation details before throwing out a strawman

### Motivation

Exposing an API like this will allow plugins to be dynamically augmented, which can be useful from a variety of perspectives.

**Comment by thebigredgeek** [comment]
Whoever ends up tackling this will want to talk to @rase- and @abhiaiyer91 about this to nail down a contract before implementing

**Comment by moonmeister** [comment]
@thebigredgeek Sounds interesting. We've chatted about a plugin configuration API for the CLI. See: https://github.com/gatsbyjs/rfcs/blob/master/text/0007-gatsby-plugin-cli.md and #12822. I'm not on the gatsby cloud preview but...is this basically what you're talking about, but for the cloud? Maybe the final implementation of this API could be made to be compatible with the cloud and called from there as well?

**Comment by DSchau** [comment]
Talked to @KyleAMathews about this. We like the idea, but in this particular case, I think we can implement this pretty cleanly with an intuitive option passing syntax. For example:

If we'd like to pass a custom contentful host, we could do so with (in any phase/build/develop/etc.)

```
gatsby develop --gatsby-source-contentful.host=preview.contentful.com
```

These environment variables would be _automatically_ applied for plugin options, and would take precedence over the user passed tokens.

For example, given the following `gatsby-config.js`

```js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-contentful`,
      options: {
        host: `api.contentful.com`
      }
    }
  ]
}
```

and the command `gatsby develop --gatsby-source-contentful.host=preview.contentful.com`

the plugin would have a host argument of `preview.contentful.com`.

This seems to be cleaner, in that environment variables don't have to be passed, and accommodates the same general idea, e.g. a way to augment a plugin's options at runtime with custom values, independent of the user-supplied config.

**Comment by thebigredgeek** [comment]
Love this approach!  A lot cleaner than what I was thinking

**Comment by DSchau** [comment]
The idea I proposed above (☝️) will suffer from the same issue noted [here](https://github.com/gatsbyjs/gatsby/issues/13050#issuecomment-479141305), namely multiple plugins complicate this.

Will need to think on the best approach for this.

**Comment by DSchau** [comment]
Going to close this out, for a few reasons:

1. Environment variables tend to be cleaner and more easily understood
1. We can instead build out improved plugin option validation to fail _quickly_ and obviously, which seems to be an improved user experience

From the Gatsby Preview side of things, this will be solved with using an OAuth flow to provide necessary environment variables as editable values in the UI, itself. If the user needs to augment their gatsby-config.js file to consume these values (or to change the enviroment variable name) that's OK--but it's a manual, clear process rather than something automated that could be confusing.

Reducing friction in this approach is certainly something we'll want to solve, but for now... I think we can close this. Thanks all!
