### ISSUE TITLE
[gatsby-transformer-json] Images into array from source json

### ISSUE THREAD

**Issue by nephlin7** [gatsbyjs/gatsby#12916]
## Summary
I get data from json file with "gatsby-transformer-json" plugin, my problem is with relative path images into array like this:

``` json
{
"image": "images/placeholder.png",
"gallery": [
            { "image": "images/placeholder.png" }, 
            { "image": "images/placeholder.png"}
          ]
}
```

Graphql Query result:

``` Json
"data": {
    "allBienesAdjudicadosJson": {
      "edges": [
        {
          "node": {
            "gallery": [
              {
                "image": "images/placeholder.png"
              },
              {
                "image": "images/placeholder.png"
              }
            ],
            "image": {
              "childImageSharp": {
                "id": "88de8d91-e1fb-5cc1-9781-cd6b9b9a216a"
              }
            }
          }
        }
      ]
    }
  }

```

Images into array not process like file field

how can i get  relative path images?

### File contents (if changed)

`gatsby-config.js`: 

``` javascript
 `gatsby-transformer-json`,
  {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: path.join(__dirname, `data`),
      },
    },
```
 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@nephlin7 i've picked up on your issue and i think i have a solution for you.
Based on the information you provided, i'm going to break it into 2 approaches that you can use for your case.
- Created a new Gatsby website based on the hello world started to keep it simple.
- Added the necessary dependencies, namely `gatsby-image`, `gatsby-plugin-sharp`, `gatsby-source-filesystem`, `gatsby-transformer-json` `gatsby-transformer-sharp`
- Modified `gatsby-config.js` to "activate" the plugins, transformin it into the following:
```
module.exports = {
    plugins: [
      `gatsby-transformer-json`,
      {
          resolve:`gatsby-source-filesystem`,
          options: {
            path:`${__dirname}/data/`
          },
      }
    ],
  }
```

Now that the basic configuration is out of the way. Going to elaborate on both approaches.
The first approach i took was based on the contents of the json file.
So with that in mind 
- i've created a file called `Images.json` inside `data` folder with the following contents:
```json
[
    {
        "image": "images/starwarsri.jpg",
        "gallery": [
            { "image": "images/wallpaper-1386.jpg" }, 
            { "image": "images/wallpaper-134268.jpg"}
        ]
    },
    {
        "image":"images/wallpaper-249766.jpg",
        "gallery":[
            {
                "image": "images/wallpaper-364251.jpg"
            },
            {
                "image": "images/wallpaper-420962.jpg"
            },
            {
                "image":"images/wallpaper-421882.jpg"
            },
            {
                "image":"images/wallpaper-441444.jpg"
            },
            {
                "image":"images/wallpaper-444742.jpg"
            },
            {
                "image":"images/wallpaper-458162.jpg"
            },
            {
                "image":"images/wallpaper-463698.jpg"
            },
            {
                "image":"images/wallpaper-466410.jpg"
            }
        ]
    }
]
```
All of the images are some images i had laying around from an old wallpaper folder.

- Grabbed those images and created a new folder called `images` inside the `static` folder, for more information on how the static folder works see [this](https://www.gatsbyjs.org/docs/static-folder/)
- Created a component called `ComponentA` with the following contents:
```javascript
import React from "react"
import { StaticQuery, graphql } from "gatsby"

const ComponentA = () => (
  <StaticQuery
    query={graphql`
      {
        allImagesJson {
          edges {
            node {
              image
              gallery {
                image
              }
            }
          }
        }
      }
    `}
    render={data => (
      <div>
        {data.allImagesJson.edges.map(item => {
          return (
            <div>
              <img
                src={item.node.image}
                alt={`image_${item.node.image}`}
                style={{ width: "800px", height: "600px" }}
              />
              <hr />
              <p style={{ fontSize: "20px", fontWeight: "bolder" }}>
                gallery items for {item.node.image}
              </p>
              {item.node.gallery.map(galleryItem => {
                return (
                  <img
                    src={galleryItem.image}
                    alt={`gallery_item_${galleryItem.image}`}
                    style={{ width: "800px", height: "600px" }}
                  />
                )
              })}
              <hr />
            </div>
          )
        })}
      </div>
    )}
  />
)
export default ComponentA

```
- Added the component to `pages/index.js`.
- Issued `gatsby develop`, opened `http://localhost:8000` and i'm presented with the following:
The image

![neflin7_first_approach_image](https://user-images.githubusercontent.com/22988955/55205102-6538ac00-51c9-11e9-9192-3d61a7f2f3b2.png)

The gallery

![neflin7_first_approach_gallery](https://user-images.githubusercontent.com/22988955/55205074-42a69300-51c9-11e9-8b3f-15e7ece72186.png)

Key thing to take from this. By using this approach you have at your disposal the images out of the box, as they will be copied over when you issue `gatsby develop` for instance. The image files will be copied over and you only need to use one grapql to fetch the data from the json file and transverse the results returning a image for them.

Now for the second approach, once again based on the information you provided, it looked like you wanted the images to be fluid/responsive, and you are probably using `gatsby-image` for that.
So with that in mind:

- Created a new folder called `gatsby-images` inside `src` folder, copied over the images i had before inside.
- Modified `gatsby config.js` to the following
```javascript
module.exports = {
    plugins: [
      
      {
        resolve: `gatsby-source-filesystem`,
        options: {
          name: `content`,
          path: `${__dirname}/src/gatsby-images`,
        },
      },
      `gatsby-transformer-json`,
      {
          resolve:`gatsby-source-filesystem`,
          options: {
            path:`${__dirname}/data/`
          },
      },
      'gatsby-transformer-sharp',
      'gatsby-plugin-sharp',
    ],
  }
```
- Created a new file under `data` folder called `NewImages.json` with the following contents:
```json
[
    {
        "image": "starwarsri.jpg",
        "gallery": [
            { "image": "wallpaper-1386.jpg" }, 
            { "image": "wallpaper-134268.jpg"}
        ]
    },
    {
        "image":"wallpaper-249766.jpg",
        "gallery":[
            {
                "image": "wallpaper-364251.jpg"
            },
            {
                "image": "wallpaper-420962.jpg"
            },
            {
                "image":"wallpaper-421882.jpg"
            },
            {
                "image":"wallpaper-441444.jpg"
            },
            {
                "image":"wallpaper-444742.jpg"
            },
            {
                "image":"wallpaper-458162.jpg"
            },
            {
                "image":"wallpaper-463698.jpg"
            },
            {
                "image":"wallpaper-466410.jpg"
            }
        ]
    }
]
```
The difference here is just the removal of the images folder and you'll see why shortly.
- Created a new component called `ComponentB.js` with the following content:
```javascript
import React from "react"
import { StaticQuery, graphql } from "gatsby"
import Img from "gatsby-image"

const ComponentB = () => (
  <StaticQuery
    query={graphql`
      query AllImagesAndJSON {
        images: allFile(filter: {sourceInstanceName: {eq: "content"}}){
          edges {
            node {
              name
              childImageSharp {
                fluid(maxWidth: 2000) {
                  ...GatsbyImageSharpFluid
                }
              }
            }
          }
        }
        datafromjson: allNewImagesJson {
          edges {
            node {
              image
              gallery {
                image
              }
            }
          }
        }
      }
    `}
    render={data => {
      const { images, datafromjson } = data
      
      return (
        <div>
          {datafromjson.edges.map(jsonItem => {

            const imageIndex = images.edges.findIndex(
              x => x.node.name === jsonItem.node.image.split('.').slice(0, -1).join('.')
            )
            return (
              
              <div>
                <Img fluid={images.edges[imageIndex].node.childImageSharp.fluid} style={{ width: "800px", height: "600px" }}/>
                <hr />
                <p style={{ fontSize: "20px", fontWeight: "bolder" }}>
                  gallery items for {jsonItem.node.image}
                </p>
                {jsonItem.node.gallery.map(galleritem => {
                  const galleritemIndex = images.edges.findIndex(
                    y => y.node.name === galleritem.image.split('.').slice(0, -1).join('.')
                  )

                  return (
                    <Img
                      fluid={images.edges[galleritemIndex].node.childImageSharp.fluid} style={{ width: "800px", height: "600px" }}
                    />
                  )
                })}
              </div>
            )
          })}
        </div>
      )
    }}
  />
)
export default ComponentB

```
Breaking down the code into smaller pieces:

I have a `StaticQuery` with 2 queries inside, one for fetching all the items based on the `sourceInstanceName` which i defined above in the `gatsby-config.js` update, the other for fetching items inside the new json file created.

As the images query value `name` does not provide the extension and i have a extension inside the json file, i'm removing it when i lookup the position of the array for the specific image.

The results obtained from graphql for json content are iterated over and i fetch the corresponding image and return it and the same for each item of the gallery.

- Finally created a new file inside `pages` with the following name `page-b.js` and inside imported `ComponentB.js`

Re-issuing `gatsby develop` and opening a browser window  to `http://localhost:8000/page-b` will yeld the same results i illustrated earlier.

With this approach you have at your disposal the images as before but this time you're making use of `gatsby-image` to transform them into responsive. 

Probably there could have been other way to achieve the same result, but this was based on the information at hand and tried to simplify it as much as possible.

Feel free to provide feedback so that we can close this issue, or provide additional information so that we can continue to try and resolve this.

**Comment by nephlin7** [comment]
Wow, thanks a lot for your time @jonniebigodes .

I resolve problem with ur first example.

I put item images gallery inside root **/static** folder to access them and works fine.

### Component file

```javascript
        const { image, gallery } = this.props.data.dataJson

      <Slider>
             <div>
                    <Img className="each-slide" alt={name} fluid={image.childImageSharp.fluid}/>
              </div>
               {gallery.map((i, index) => (
                       <img  key={index} 
                                  alt={`${name}-${index}`}  
                                  style={{width: `100%` }}  
                                  id={index}  
                                  src={`${withPrefix(i.image)}`}/>
                 ))}
     </Slider>
```

### Graphql Query

```javascript
 dataJson(id: { eq: $id }) {
      id
      image {
        childImageSharp {
          fluid(maxWidth: 640) {
            ...GatsbyImageSharpFluid
          }
        }
      }
      gallery {
        image
      }
    }

```

I will treat your second example when I make an improvement of the site and I will tell you how it was.

Thanks again.

**Comment by jonniebigodes** [comment]
@nephlin7 no need to thank, it was no trouble at all. Glad i could be of assistance. And glad you worked it out. I'm going to close this. Should any other issues arise, feel free to open a new one.

**Comment by nephlin7** [comment]
> @nephlin7 no need to thank, it was no trouble at all. Glad i could be of assistance. And glad you worked it out. I'm going to close this. Should any other issues arise, feel free to open a new one.

Hi @jonniebigodes, I found another simple solution for this, with the  [New Schema Customization API ](https://www.gatsbyjs.org/blog/2019-03-18-releasing-new-schema-customization/) it was easy to tell the desired type of data:

### gatsby-node.js
```javascript

exports.sourceNodes = ({actions}) => {
    const {createTypes} = actions
    const typeDefs = `

        type GalleryImages implements Node {
            image: File!
        }
  
        type BienesEnVentaJson implements Node {
            Fecha: Date,
            gallery: [GalleryImages]
      }
    `
    createTypes(typeDefs)
}
```
Thanks again for ur helps.

regards

**Comment by jonniebigodes** [comment]
@nephlin7 once again, no need to thank, even more glad that you found another solution for your issue 👍

**Comment by devpgcs** [comment]
> @nephlin7 i've picked up on your issue and i think i have a solution for you.
> Based on the information you provided, i'm going to break it into 2 approaches that you can use for your case.
> 
> * Created a new Gatsby website based on the hello world started to keep it simple.
> * Added the necessary dependencies, namely `gatsby-image`, `gatsby-plugin-sharp`, `gatsby-source-filesystem`, `gatsby-transformer-json` `gatsby-transformer-sharp`
> * Modified `gatsby-config.js` to "activate" the plugins, transformin it into the following:
> 
> ```
> module.exports = {
>     plugins: [
>       `gatsby-transformer-json`,
>       {
>           resolve:`gatsby-source-filesystem`,
>           options: {
>             path:`${__dirname}/data/`
>           },
>       }
>     ],
>   }
> ```
> 
> Now that the basic configuration is out of the way. Going to elaborate on both approaches.
> The first approach i took was based on the contents of the json file.
> So with that in mind
> 
> * i've created a file called `Images.json` inside `data` folder with the following contents:
> 
> ```json
> [
>     {
>         "image": "images/starwarsri.jpg",
>         "gallery": [
>             { "image": "images/wallpaper-1386.jpg" }, 
>             { "image": "images/wallpaper-134268.jpg"}
>         ]
>     },
>     {
>         "image":"images/wallpaper-249766.jpg",
>         "gallery":[
>             {
>                 "image": "images/wallpaper-364251.jpg"
>             },
>             {
>                 "image": "images/wallpaper-420962.jpg"
>             },
>             {
>                 "image":"images/wallpaper-421882.jpg"
>             },
>             {
>                 "image":"images/wallpaper-441444.jpg"
>             },
>             {
>                 "image":"images/wallpaper-444742.jpg"
>             },
>             {
>                 "image":"images/wallpaper-458162.jpg"
>             },
>             {
>                 "image":"images/wallpaper-463698.jpg"
>             },
>             {
>                 "image":"images/wallpaper-466410.jpg"
>             }
>         ]
>     }
> ]
> ```
> 
> All of the images are some images i had laying around from an old wallpaper folder.
> 
> * Grabbed those images and created a new folder called `images` inside the `static` folder, for more information on how the static folder works see [this](https://www.gatsbyjs.org/docs/static-folder/)
> * Created a component called `ComponentA` with the following contents:
> 
> ```js
> import React from "react"
> import { StaticQuery, graphql } from "gatsby"
> 
> const ComponentA = () => (
>   <StaticQuery
>     query={graphql`
>       {
>         allImagesJson {
>           edges {
>             node {
>               image
>               gallery {
>                 image
>               }
>             }
>           }
>         }
>       }
>     `}
>     render={data => (
>       <div>
>         {data.allImagesJson.edges.map(item => {
>           return (
>             <div>
>               <img
>                 src={item.node.image}
>                 alt={`image_${item.node.image}`}
>                 style={{ width: "800px", height: "600px" }}
>               />
>               <hr />
>               <p style={{ fontSize: "20px", fontWeight: "bolder" }}>
>                 gallery items for {item.node.image}
>               </p>
>               {item.node.gallery.map(galleryItem => {
>                 return (
>                   <img
>                     src={galleryItem.image}
>                     alt={`gallery_item_${galleryItem.image}`}
>                     style={{ width: "800px", height: "600px" }}
>                   />
>                 )
>               })}
>               <hr />
>             </div>
>           )
>         })}
>       </div>
>     )}
>   />
> )
> export default ComponentA
> ```
> 
> * Added the component to `pages/index.js`.
> * Issued `gatsby develop`, opened `http://localhost:8000` and i'm presented with the following:
>   The image
> 
> ![neflin7_first_approach_image](https://user-images.githubusercontent.com/22988955/55205102-6538ac00-51c9-11e9-9192-3d61a7f2f3b2.png)
> 
> The gallery
> 
> ![neflin7_first_approach_gallery](https://user-images.githubusercontent.com/22988955/55205074-42a69300-51c9-11e9-8b3f-15e7ece72186.png)
> 
> Key thing to take from this. By using this approach you have at your disposal the images out of the box, as they will be copied over when you issue `gatsby develop` for instance. And you only need to use one grapql to fetch the data from the json file and transverse the results returning a image for them.
> 
> Now for the second approach, once again based on the information you provided, it looked like you wanted the images to be fluid/responsive, and you are probably using `gatsby-image` for that.
> So with that in mind:
> 
> * Created a new folder called `gatsby-images` inside `src` folder, copied over the images i had before inside.
> * Modified `gatsby config.js` to the following
> 
> ```js
> module.exports = {
>     plugins: [
>       
>       {
>         resolve: `gatsby-source-filesystem`,
>         options: {
>           name: `content`,
>           path: `${__dirname}/src/gatsby-images`,
>         },
>       },
>       `gatsby-transformer-json`,
>       {
>           resolve:`gatsby-source-filesystem`,
>           options: {
>             path:`${__dirname}/data/`
>           },
>       },
>       'gatsby-transformer-sharp',
>       'gatsby-plugin-sharp',
>     ],
>   }
> ```
> 
> * Created a new file under `data` folder called `NewImages.json` with the following contents:
> 
> ```json
> [
>     {
>         "image": "starwarsri.jpg",
>         "gallery": [
>             { "image": "wallpaper-1386.jpg" }, 
>             { "image": "wallpaper-134268.jpg"}
>         ]
>     },
>     {
>         "image":"wallpaper-249766.jpg",
>         "gallery":[
>             {
>                 "image": "wallpaper-364251.jpg"
>             },
>             {
>                 "image": "wallpaper-420962.jpg"
>             },
>             {
>                 "image":"wallpaper-421882.jpg"
>             },
>             {
>                 "image":"wallpaper-441444.jpg"
>             },
>             {
>                 "image":"wallpaper-444742.jpg"
>             },
>             {
>                 "image":"wallpaper-458162.jpg"
>             },
>             {
>                 "image":"wallpaper-463698.jpg"
>             },
>             {
>                 "image":"wallpaper-466410.jpg"
>             }
>         ]
>     }
> ]
> ```
> 
> The difference here is just the removal of the images folder and you'll see why shortly.
> 
> * Created a new component called `ComponentB.js` with the following content:
> 
> ```js
> import React from "react"
> import { StaticQuery, graphql } from "gatsby"
> import Img from "gatsby-image"
> 
> const ComponentB = () => (
>   <StaticQuery
>     query={graphql`
>       query AllImagesAndJSON {
>         images: allFile(filter: {sourceInstanceName: {eq: "content"}}){
>           edges {
>             node {
>               name
>               childImageSharp {
>                 fluid(maxWidth: 2000) {
>                   ...GatsbyImageSharpFluid
>                 }
>               }
>             }
>           }
>         }
>         datafromjson: allNewImagesJson {
>           edges {
>             node {
>               image
>               gallery {
>                 image
>               }
>             }
>           }
>         }
>       }
>     `}
>     render={data => {
>       const { images, datafromjson } = data
>       
>       return (
>         <div>
>           {datafromjson.edges.map(jsonItem => {
> 
>             const imageIndex = images.edges.findIndex(
>               x => x.node.name === jsonItem.node.image.split('.').slice(0, -1).join('.')
>             )
>             return (
>               
>               <div>
>                 <Img fluid={images.edges[imageIndex].node.childImageSharp.fluid} style={{ width: "800px", height: "600px" }}/>
>                 <hr />
>                 <p style={{ fontSize: "20px", fontWeight: "bolder" }}>
>                   gallery items for {jsonItem.node.image}
>                 </p>
>                 {jsonItem.node.gallery.map(galleritem => {
>                   const galleritemIndex = images.edges.findIndex(
>                     y => y.node.name === galleritem.image.split('.').slice(0, -1).join('.')
>                   )
> 
>                   return (
>                     <Img
>                       fluid={images.edges[galleritemIndex].node.childImageSharp.fluid} style={{ width: "800px", height: "600px" }}
>                     />
>                   )
>                 })}
>               </div>
>             )
>           })}
>         </div>
>       )
>     }}
>   />
> )
> export default ComponentB
> ```
> 
> Breaking down the code into smaller pieces:
> 
> I have a `StaticQuery` with 2 queries inside, one for fetching all the items based on the `sourceInstanceName` which i defined above in the `gatsby-config.js` update, the other for fetching items inside the new json file created.
> 
> As the images query value `name` does not provide the extension and i have a extension inside the json file, i'm removing it when i lookup the position of the array for the specific image.
> 
> The results obtained from graphql for json content are iterated over and i fetch the corresponding image and return it and the same for each item of the gallery.
> 
> * Finally created a new file inside `pages` with the following name `page-b.js` and inside imported `ComponentB.js`
> 
> Re-issuing `gatsby develop` and opening a browser window to `http://localhost:8000/page-b` will yeld the same results i illustrated earlier.
> 
> With this approach you have at your disposal the images as before but this time you're making use of `gatsby-image` to transform them into responsive.
> 
> Probably there could have been other way to achieve the same result, but this was based on the information at hand and tried to simplify it as much as possible.
> 
> Feel free to provide feedback so that we can close this issue, or provide additional information so that we can continue to try and resolve this.

Thanks man! I was stuck in this about 2 hours seriously. I'm starting in this so... jajajajaja. Static folder works for me. Thanks again!

**Comment by jonniebigodes** [comment]
@devpgcs no problem. Glad that the explanation helped you out aswell

**Comment by Mouzayan** [comment]
> @jonniebigodes Hi, 
I am new to Gatsby and I'm still trying to get a full handle of the querying process.
I created a custom node which contains both image and non image data. I have this data in a Json file, and I'm trying to query it into a component.
I am having a super hard time figuring this out.
I  do see my Json data in the GraphiQL. Yet I'm not able to pull this data to map it in a component.

Do you have any idea about how this can be done?

Any advice or direction would be hugely appreciated.
Thank you so much!
