### ISSUE TITLE
gatsby-plugin-google-tagmanager misspelled default 'dataLayer'

### ISSUE THREAD

**Issue by alexjsdev** [gatsbyjs/gatsby#12921]
## Description

For the gatsby-plugin-google-tagmanager this PR/release: #12783, has introduced a bug where by default the 'dataLayer' was being set as 'datalayer' (all lower case). Which means that by default this will not work with GTM. This PR just updates to use the correct form dataLayer.

### Steps to reproduce

Install the latest gatsby-plugin-google-tagmanager package and in your code try to push to "dataLayer" (ie `window.dataLayer.push({event: 'poop'})` all google docs suggest for interacting with GTM, you will errors in the console about trying to call push on undefined.

**Comment by spwisner** [comment]
Closing because issued has been resolved and pull request has been merged.
