### ISSUE TITLE
[feat]: make analytics notice more obvious

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#12923]
## Description

Surfaced in #12922, it seems apparent that the telemetry notice--while helpful--can easily be overlooked as a wall of text from other logging draws more attention.

To remediate, I propose we make the telemetry notice more obvious so that users are aware of the opt-out nature and that we are beginning to track on telemetry data.

_Note: curious about this telemetry data? Check out https://gatsby.dev/telemetry for more info_

## Ideas

I have a few ideas for how to make the notice more apparent:

- Usage of color
    - e.g. chalk.blue, chalk.bold, etc. could be used to separate the notice from other logging
- Usage of padding and/or a tool like [boxen](https://github.com/sindresorhus/boxen)
- Moving the notice to a different phase in Gatsby core, e.g. in Gatsby bootstrap

**Comment by KyleAMathews** [comment]
Just came here to suggest boxen too :-)

**Comment by DSchau** [comment]
@KyleAMathews when we roll out the Ink functionality (cc @wardpeet) there's even an [Ink component, too](https://github.com/sindresorhus/ink-box).
