### ISSUE TITLE
Issues getting client/dynamic routes working

### ISSUE THREAD

**Issue by shansmith01** [gatsbyjs/gatsby#12932]
I am having some fun trying to get a react app (todo app) that uses firebase auth and real time DB to work inside gatsby. But I am running into an issue trying to get dynamic/client only routes to work.

My client only routes are 404ing

My workflow is this: When a user logs in they should be redirected to a client only path which is /app/:appId (where appID is the firebase user ID. For example it may be http://localhost:8000/app/qKXZO8yOD1MFvRtOykBpMW7UR603

I am using the create client paths plugin like below

```
 {
      resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`/app/*`] },
    },
```

and I have a app.js file that looks like this

```
import React from "react"
import { Router } from "@reach/router"
import Layout from "../components/Layout"
import AppWrapper from "../components/AppWrapper"

const App = () => (
  <Layout>
    <Router>
      <AppWrapper path="/app/" />
      <AppWrapper path="/app/:appId" />
    </Router>
  </Layout>
)

export default App
```

But still no luck. I have read the few tutorials out there but now I am a bit lost. Can anyone shed some light on this?

Full repo here https://github.com/shansmith01/todoapp

**Comment by wardpeet** [comment]
Hey there seems nothing wrong on the gatsby side. I've did a quick peek in your source code and it seems like your not using the property `appId` from router anywhere.

I looked into https://github.com/shansmith01/todoapp/blob/master/src/components/AppWrapper.js but `this.props.appId` isn't used here so even if you visit `http://localhost:8000/app/qKXZO8yOD1MFvRtOykBpMW7UR603` nothing different is done than going to `http://localhost:8000/app/`
