### ISSUE TITLE
Accessing directly to a client-only route redirects wrong.  

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#12935]
## 🐛 Bug Report
Hello guys, 

I created some client-only routes like this one : https://v2.edgebase.com/account/settings 

I have this code in `gatsby-node.js`

```
  if (page.path.match(/^\/page-account/)) {
    page.matchPath = `/account/*`;
    createPage(page);
  }
```

and this code in `page-account.js`

``` 
    <Router>
      <PrivateRoute path="/account/" component={Home} />
      <PrivateRoute path="/account/settings" component={Settings} />
    </Router>
```

**This code works perfectly on `localhost`**

**But on production**, when I access to https://v2.edgebase.com/account/settings 
via a : `navigate(/account/settings)`  or `<Link to="/account/settings">`, it's work, I see my page Settings.

### The problem is when I access directly to 

```
https://v2.edgebase.com/account/settings 
``` 

It redirects me to this URL (which is a blank page)

```
https://v2.edgebase.com/account/Settings/ 
```

## To Reproduce

1 / Go to https://v2.edgebase.com/account/settings
2 / Should see https://v2.edgebase.com/account/settings be finally see https://v2.edgebase.com/account/Settings/ _(I think it's the name of my component...)_

## Expected Behavior

No redirection. Maintain exact URL tapped in the address bar.

## Code Example

https://v2.edgebase.com/account/settings

## Environment

```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.0 => 2.0.118 
    gatsby-cli: ^2.4.16 => 2.4.16 
    gatsby-image: ^2.0.26 => 2.0.29 
    gatsby-plugin-emotion: ^4.0.1 => 4.0.3 
    gatsby-plugin-netlify: ^2.0.12 => 2.0.12 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.6 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.20 
    gatsby-source-filesystem: ^2.0.12 => 2.0.20 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.13 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by sidharthachatterjee** [comment]
Hey @Steffi3rd 

I can reproduce what you describe on https://v2.edgebase.com/account/settings

I'd typically suggest that this has something to do with your hosting provider and potentially an incorrect redirect setup there (in this case Netlify)

However, looking at the network tab, there doesn't appear to be a redirect to `/account/Settings` and this stops happening when JavaScript is disabled. 

That suggests that this likely has to do with an incorrect call to navigate or maybe a bug. Could you isolate this and link to a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) of it so we can investigate further?

**Comment by Steffi3rd** [comment]
Hello guys

**This is real bug here.**

We cannot use the same naming for the component and the route. 
And I think it's not about Netlify because I just reproduced with `yarn serve`

```
<PrivateRoute path="/cmt/dashboard" component={Dashboard} />
```

Redirects me on production to `/cmt/Dashboard` instead of `/cmt/dashboard`.
