### ISSUE TITLE
BackgroundImage strange behaviour. Same template, black image.

### ISSUE THREAD

**Issue by Jsalvat** [gatsbyjs/gatsby#12943]
## Description

Strange behavior in BackgroundImage when pass new data to the same template
### Steps to reproduce

Template for 2 pages. First load it loads fine, but after we click on button to load new data on same template, BackgroundImage loads the image for 0.5 sec and then goes to black.

### Expected result

It should load all data and change the BackgroundImage for the new one.

### Actual result

Loads new data and then the BackgroundImage goes fine for 0.5sec and then goes to black.
### Environment

System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Safari: 12.1
  npmPackages:
    gatsby: ^2.1.18 => 2.1.19
    gatsby-background-image: ^0.2.73 => 0.2.73
    gatsby-image: ^2.0.33 => 2.0.33
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24
    gatsby-plugin-material-ui: ^1.2.4 => 1.2.4
    gatsby-plugin-offline: ^2.0.24 => 2.0.24
    gatsby-plugin-react-helmet: ^3.0.7 => 3.0.7
    gatsby-plugin-remote-images: ^1.0.1 => 1.0.1
    gatsby-plugin-sass: ^2.0.10 => 2.0.10
    gatsby-plugin-sharp: ^2.0.22 => 2.0.23
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.0.23 => 2.0.23
    gatsby-transformer-sharp: ^2.1.14 => 2.1.14
  npmGlobalPackages:
    gatsby-cli: 2.4.16

**Comment by Jsalvat** [comment]
Still having this issue, anyone experienced something like this?

**Comment by Jsalvat** [comment]
Fixed with the new version of background-images-plugin

**Comment by pieh** [comment]
`gatsby-background-image` is not maintained here btw, so we wouldn't be able to help
