### ISSUE TITLE
docs(gatsby-source-contentful) : Update rendering RichText

### ISSUE THREAD

**Issue by isaac-martin** [gatsbyjs/gatsby#12944]
[This is the documentation in reference](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/README.md)

I am parsing some Rich Text from contentful. 
Using `gatsby-source-contentful` and `@contentful/rich-text-react-renderer`

However I don't think the docs are correct. 
I have had to do the below, which works as I would expect. From what I see there is no way to access the full `document` from the GraphQL query, which is what the `@contentful/rich-text-react-renderer` is expecting. I will update Docs if we think this is the right approach? 

@sbezludny and @pieh  it looks like you authored the docs on these a little while ago, so some input if possible would be nice before I open up a PR.

```jsx
import { BLOCKS, MARKS } from "@contentful/rich-text-types"
import { documentToReactComponents } from "@contentful/rich-text-react-renderer"

const Bold = ({ children }) => <span className="bold">{children}</span>
const Text = ({ children }) => <p className="align-center">{children}</p>

const options = {
  renderMark: {
    [MARKS.BOLD]: text => <Bold>{text}</Bold>,
  },
  renderNode: {
    [BLOCKS.PARAGRAPH]: (node, children) => <Text>{children}</Text>,
  },
}

const document = {
    nodeType: 'document',
    content: [...node.bodyRichText.json]
  }

 documentToReactComponents(document, options)

```

**Comment by sbezludny** [comment]
Hi @isaac-martin, 
`json` field returns the full rich text document. I've tried to reproduce the described behaviour but it works for me https://codesandbox.io/s/5x2ym34k7n

Could you provide the exact versions of `gatsby` and `gatsby-source-contentful` you're using.

Please let me know if I am missing something.

**Comment by isaac-martin** [comment]
Yeah - looks like i had made a mistake in my function, was only passing down the content. Apologies!
