### ISSUE TITLE
Using Gatsby Image site uses Lorem Ipsum placeholder text

### ISSUE THREAD

**Issue by robphoenix** [gatsbyjs/gatsby#12947]
## Summary

I noticed the site at https://using-gatsby-image.gatsbyjs.org/ currently uses Lorem Ipsum placeholder text, is there plans to update this to explanations of the different features of gatsby image? If so, is there any direction for what would make a useful PR to replace the current text?

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @robphoenix 

The home page at https://using-gatsby-image.gatsbyjs.org/ seems to have some documentation and links to https://www.gatsbyjs.org/packages/gatsby-image/ but the rest is placeholder text. 

Updating the placeholder text to some explanation of the features used in context will be helpful and I can definitely see the value in it!

Would you like to open a PR? The relevant files are in https://github.com/gatsbyjs/gatsby/tree/master/examples/using-gatsby-image/ and the lorem text is coming from https://github.com/gatsbyjs/gatsby/blob/master/examples/using-gatsby-image/src/components/lorem.js

CC @marcysutton
