### ISSUE TITLE
How do I add headers to individual requests (Authenticate) to a graphql endpoint.

### ISSUE THREAD

**Issue by trufa** [gatsbyjs/gatsby#12958]
I have made my own graphql server/endpoint using prisma and prisma client.

I have used the [source graphql plugin](https://www.gatsbyjs.org/packages/gatsby-source-graphql/) and managed to successfully query the server with this configuration:

```
    {
      resolve: 'gatsby-source-graphql',
      options: {
        ....
        headers: {
          Authorization: 'Bearer __THE_TOKEN___',
        },
      },
    },
```

This allows me to successfully execute queries like:

```
{
  companyFieldName {
  	me {
      name
    }
  }
}
```

But this is a per api header, and I need it to be per user.

The graphql api I built accepts jwt tokens to authenticate individual users and gives back individual data.

I would like to send headers with each individual requests to send the authorization token of each respective user after login.

I have two questions:

1) Can I send headers per query with the token?

2) Is this the right approach? Or is there a more gatsby friendly approach to this?

Thanks in advance!

**Comment by pieh** [comment]
`gatsby-source-graphql` run queries during build time - so you can't "prebuild" those query results for individual users. For that you would need client side querying - i.e. with `apollo-boost`/`react-apollo`

**Comment by trufa** [comment]
@pieh thanks! makes sense. Will go that route.
