### ISSUE TITLE
How to build a source of data from multiple GraphQL queries

### ISSUE THREAD

**Issue by erichgoldman** [gatsbyjs/gatsby#12956]
## Summary

I would like to pull data from the GitHub GraphQL. I need to issue multiple similar queries, but then would like to combine them into one data source. The list of queries should also be dynamic. 

For example the simple query would be:

```graphql
{
 github{
    nasa: organization(login:"nasa"){
      id
    	url
    }
  }
}
```
However, both the alias name and value for `login:` would be variable.

```graphql
{
 github{
    {ORG}: organization(login:"{ORG}"){
      id
    	url
    }
  }
}
```

In terms of creating the list I would ideally like to just have a CSV file loaded (would just put one org per line). But to keep it simple, right now I am just using a variable defined in gatsby-config.js like this

```jsx
module.exports = {
  siteMetadata: {
    title: `Info on Orgs`,
    githubOrgs: [ "nasa", "github", "microsoft" ]
  },
...
```
The approach would either then be to loop or map the array against a graphql query with variables or to create one large query ahead of time (preferred):

```graphql
{
 githubOrgs: github{
    nasa: organization(login:"nasa"){
      ...orgFragments
    }
    github: organization(login:"github"){
      ...orgFragments
    }
  }
}

fragment orgFragments on GitHub_Organization{
  id
  url
}
```

## Relevant information

I am a bit lost on where and how to script this. When reading [Querying data in pages with GraphQL](https://www.gatsbyjs.org/docs/page-query/) it notes that queries are run at build time and that

> This means that the graphql tag isn’t executed the way that you might expect. For example, you cannot use expression interpolation with Gatsby’s graphql tag.

So I can't just create a page and loop/map in a page, which would have been my initial thought.

From going through the tutorial, it looks like you can create/add data in `gatsby-node.js`, but I am stuck on how to pull this all together and when where I can use variables or interpolation.

It would seem I should be able to somehow create this data structure and then I could create individual pages or query it on individual pages. I noted that `pageContext` can provide variables, but I couldn't find an example of iterating over something like I am looking to do here.

### Environment (if relevant)

```
  System:
    OS: Linux 4.4 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 11.12.0 - /usr/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.7.0 - /usr/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: ^2.3.3 => 2.3.3
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6
    gatsby-plugin-typography: ^2.2.10 => 2.2.10
    gatsby-source-filesystem: ^2.0.28 => 2.0.28
    gatsby-source-graphql: ^2.0.15 => 2.0.15
    gatsby-transformer-remark: ^2.3.8 => 2.3.8
  npmGlobalPackages:
    gatsby-cli: 2.4.17
    gatsby-source-graphql: 2.0.15
    gatsby: 2.2.8
```

### File contents (if changed)

`gatsby-config.js`: 

```jsx
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
})

module.exports = {
  siteMetadata: {
    title: `Info on Orgs`,
    githubOrgs: [ "nasa", "github", "microsoft" ]
  },
  plugins: [
    {
      resolve: "gatsby-source-graphql",
      options: {
        typeName: "GitHub",
        fieldName: "github",
        // Url to query from
        url: "https://api.github.com/graphql",
        // HTTP headers
        headers: {
          // Learn about environment variables: https://gatsby.dev/env-vars
          Authorization: `bearer ${process.env.GITHUB_TOKEN}`,
        },
        // Additional options to pass to node-fetch
        fetchOptions: {},
      },
    },
  ],
}
```

`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
Hey @erichgoldman 

> The list of queries should also be dynamic.
GraphQL queries in Gatsby are run at build time (and not runtime). Therefore a dynamically generated query string won't work as a page query (this doesn't mean that you can't use variables in queries, only that the query _structure_ itself needs to be static and not dynamically generated)

> So I can't just create a page and loop/map in a page, which would have been my initial thought.
> 
> From going through the tutorial, it looks like you can create/add data in gatsby-node.js, but I am stuck on how to pull this all together and when where I can use variables or interpolation.

The only place where this is possible is `gatsby-node.js`. I've gone ahead and created an example for you to use in https://gist.github.com/sidharthachatterjee/a3f21834a67185a370427e37ef4d245f

Hope this helps!

**Comment by erichgoldman** [comment]
Thanks @sidharthachatterjee . I tested this and generally understand the flow. Could you expand the gist to show how to actually make the pages from this result? I've been trying some things, but I'm not getting much closer.

How could I take this data set and make it generally available instead of creating pages. e.g., I want this data to loop over to make an index page with cards for each org.

The other related issue I am trying to understand is how to make multiple unrelated queries in `exports.createPages`. I will have a few queries like this where I want to build complex queries to be used on pages. Do I abstract this all out into a plugin or organize this some other way?
