### ISSUE TITLE
Queries work on refresh but break when navigating via Link

### ISSUE THREAD

**Issue by OllieJT** [gatsbyjs/gatsby#12959]
## Description

I'm not sure if this is a bug or my limited knowledge so I'm posting this as a question first. createPages & Queries work on page load, but not when navigating to them from Links.

I'm not sure if my queries are supposed to be static, but as I understand, I can't pass the context into them.

**Example**: 
 - Load homepage with no issues.
 - Navigate to detail view and receive a query error "TypeError: Cannot read property 'edges' of undefined". 
 - Refreshing this page correctly loads everything without errors. 
 - Navigating back to the homepage errors "TypeError: Cannot read property 'edges' of undefined"

### Expected result
 - Load Homepage
 - Click on Link
 - Navigates to the detail page

### Actual result
 - Load Homepage
 - Click on Link
 - Navigates to the detail page with a query error "TypeError: Cannot read property 'edges' of undefined"

### Environment
System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.3.4 => 2.3.4 
    gatsby-image: ^2.0.35 => 2.0.35 
    gatsby-plugin-manifest: ^2.0.26 => 2.0.26 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-prefetch-google-fonts: ^1.4.1 => 1.4.1 
    gatsby-plugin-prismic-preview: ^2.0.0 => 2.0.0 
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.11 
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-remark-prettier: ^1.0.0 => 1.0.0 
    gatsby-source-custom-api: ^0.1.1 => 0.1.1 **(Using Shopify)**
    gatsby-source-filesystem: ^2.0.28 => 2.0.28 
    gatsby-source-prismic-rich-text-fields: ^1.0.0 => 1.0.0 
    gatsby-transformer-remark: ^2.3.8 => 2.3.8 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.14

**Comment by OllieJT** [comment]
Refactoring my gatsby-node.js file seems to have fixed it. I'm still not entirely sure how or why.

**Comment by TinasheKeith** [comment]
> Refactoring my gatsby-node.js file seems to have fixed it. I'm still not entirely sure how or why.

Hi Ollie, what changes did you make to your gatsby-node file? I'm having the same issue
