### ISSUE TITLE
Collect & analyze examples of CLI apps

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#12951]
Particularly for software that's similar to Gatsby.

For each, try out installing and creating a project and write up what the experience is like and take screenshots of different workflows.

- [x] [Vue CLI](https://cli.vuejs.org/)
- [x] [Create React App](https://github.com/facebook/create-react-app)
- [x] react-static
- [x] Next.js
- [x] Expo
- [x] Parcel
- [x] Ruby on Rails
- [x] [Phoenix Framework](https://phoenixframework.org/)
- [x] Django
- [x] [create-next-app](https://github.com/segmentio/create-next-app)
- [x] [gridsome](https://gridsome.org)
- [x] [hugo](https://gohugo.io/getting-started/quick-start/)
- [x] middleman
- [x] eleventy

## Next phase 
(look at these after implementing quick wins gained from list above)
- [ ] vuepress
- [ ] docusaurus
Ideas from Twitter: https://twitter.com/kylemathews/status/1113623329875709952
- [x] https://cli.angular.io/
- [ ] nuxt.js
- [ ] https://wp-cli.org/
For example, if you have the WPGraphQL plugin active on your site you can use WP CLI to generate a schema.graphql file of your sites Schema using WP-CLI
wp graphql generate-schema
- [ ] https://pantheon.io/docs/terminus/
- [ ] https://github.com/FormidableLabs/webpack-dashboard/
- [ ] @goserverless
- [ ] speed-test
- [ ] archey
- [ ] yarn
- [ ] cargo
- [ ] rocket
- [ ] huge great cli
- [ ] create-new-app
- [ ] nethack
- [ ] ghost
- [ ] curl
- [ ] heroku
- [ ] pgcli (https://www.pgcli.com)
- [ ] HTTPie (@clihttp)
- [ ] @goserverless

**Comment by shannonbux** [comment]
Vue CLI
Things I noticed that seem nice:
- When a process is done, the command line interface anchors its position at the relevant info. For example, when localhost:8000 was ready, the text saying "Done!" + the link got anchored at the top.
- The default vs. manually selecting options was easy to use
- Lots of people say they love the `vue ui` idea - it's a graphical interface

Cons:
- Repeated typescript warning many times when I ran `npm run build` to warn me that my version of typescript is above their currently supported versions
- the UI doesn't help you find the project's files--it's possible, just hard to find

**Comment by KyleAMathews** [comment]
## Phoenix Framework

Based on Elixir which is based on Erlang

### Installation
Has a bunch of dependencies to install — Elixir & Postgres — homebrew handled these easily

<img width="938" alt="Screenshot 2019-03-29 14 38 07" src="https://user-images.githubusercontent.com/71047/55265511-e463c980-5235-11e9-89eb-b4aa83984e2c.png">

Then had to install `hex` which is a Elixir or Phoenix package manager

<img width="905" alt="Screenshot 2019-03-29 14 40 56" src="https://user-images.githubusercontent.com/71047/55265527-f47ba900-5235-11e9-8eef-89e9d88aebc8.png">
<img width="765" alt="Screenshot 2019-03-29 14 41 11" src="https://user-images.githubusercontent.com/71047/55265534-f9d8f380-5235-11e9-9d18-2c223fd0103b.png">

### Create new project

<img width="560" alt="Screenshot 2019-03-29 14 42 15" src="https://user-images.githubusercontent.com/71047/55265549-0cebc380-5236-11e9-9b6d-fb7211a674f2.png">

### Postinstall
<img width="849" alt="Screenshot 2019-03-29 14 43 04" src="https://user-images.githubusercontent.com/71047/55265603-445a7000-5236-11e9-948b-cc40edfefb91.png">

### Help command
<img width="708" alt="Screenshot 2019-03-29 15 20 09" src="https://user-images.githubusercontent.com/71047/55265581-2d1b8280-5236-11e9-86f3-77f7ef59b093.png">

### Develop
Interesting mix of Phoenix + webpack — ok organized, no color

<img width="904" alt="Screenshot 2019-03-29 15 07 40" src="https://user-images.githubusercontent.com/71047/55265610-4cb2ab00-5236-11e9-982d-96950ae02b6a.png">

### Error handling

Browser

<img width="568" alt="Screenshot 2019-03-29 15 11 14" src="https://user-images.githubusercontent.com/71047/55265626-60f6a800-5236-11e9-9730-7033d592b60d.png">

Terminal

<img width="1056" alt="Screenshot 2019-03-29 15 11 24" src="https://user-images.githubusercontent.com/71047/55265629-6522c580-5236-11e9-9483-729fe0b27306.png">

**Comment by KyleAMathews** [comment]
## Ruby on Rails

Played with the hosted RoR on repl.it for 5 minutes https://repl.it/languages/rails

## Develop
Really verbose output for each handled request

<img width="565" alt="Screenshot 2019-03-29 15 25 30" src="https://user-images.githubusercontent.com/71047/55265878-630d3680-5237-11e9-99b6-8cea33180a02.png">

Fun initial screen

<img width="772" alt="Screenshot 2019-03-29 15 24 42" src="https://user-images.githubusercontent.com/71047/55265888-6f918f00-5237-11e9-9c70-787434831aca.png">

Couldn't figure out how to edit the page so couldn't trigger an error to see how that was handled.

**Comment by KyleAMathews** [comment]
## Django

https://repl.it/languages/django

### Develop

#### output
<img width="565" alt="Screenshot 2019-03-29 15 25 30" src="https://user-images.githubusercontent.com/71047/55265988-eaf34080-5237-11e9-9bb3-34fa6598b2ba.png">
<img width="525" alt="Screenshot 2019-03-29 15 32 40" src="https://user-images.githubusercontent.com/71047/55265990-ecbd0400-5237-11e9-9ebc-233a87b584e4.png">

- Doesn't hot reload styles
- Hot reloads python which is fun (handled by repl.it though?)

### Error handling

Prints very long error trace w/ no colors and has error message nestled in middle — so kinda confusing

<img width="568" alt="Screenshot 2019-03-29 15 35 04" src="https://user-images.githubusercontent.com/71047/55266055-4cb3aa80-5238-11e9-9682-9d62e024e459.png">

**Comment by KyleAMathews** [comment]
## Parcel

### Install global cli
<details>
<summary>Pretty good except for noise from NPM from installing binaries</summary>
<img width="1440" alt="Screenshot 2019-03-29 15 56 48" src="https://user-images.githubusercontent.com/71047/55266948-c77ec480-523c-11e9-81cb-dbd2696175f9.png">
</details>

### Development

Use html as entry point. No fancy way to start projects. Has a basic html file in README (which points to an index.js which it doesn't say to add).

### Errors

<details>
<summary>Well written errors in both browser overlay & terminal</summary>
<img width="753" alt="Screenshot 2019-03-29 16 02 36" src="https://user-images.githubusercontent.com/71047/55266982-e8dfb080-523c-11e9-87fd-62c9bd46a77a.png">
<img width="874" alt="Screenshot 2019-03-29 16 02 44" src="https://user-images.githubusercontent.com/71047/55266985-eb420a80-523c-11e9-9b3f-4a071a131808.png">
</details>

### Build
<img width="399" alt="Screenshot 2019-03-29 16 03 25" src="https://user-images.githubusercontent.com/71047/55266991-f5fc9f80-523c-11e9-9006-849180c419d7.png">

**Comment by shannonbux** [comment]
# Create-react-app

## Install
<details>
  <summary>Click here to expand!</summary>
- Installation was really fast = 27.63 seconds
- Not sure why I need to see a readout of the entire list of dependencies. Was super long (screenshot doesn't show them all)
<img width="1275" alt="Screen Shot 2019-03-29 at 4 14 42 PM" src="https://user-images.githubusercontent.com/32467162/55267202-19741a00-523e-11e9-8714-f1284e5c10dd.png">

</details>

## CLI help
<details>
  <summary>Click here to expand!</summary>
- appeared after I installed, which was nice
<img width="565" alt="Screen Shot 2019-03-29 at 4 13 58 PM" src="https://user-images.githubusercontent.com/32467162/55267215-298bf980-523e-11e9-9be2-1667fb4c403e.png">

</details>

**Comment by KyleAMathews** [comment]
## Next.js

### Install
<details>
<summary>
Oddly they assume that you've already setup a node project (but don't tell you this) as they're first instruction is to install next/react/react-dom — wonder how often that bites people.

No postinstall message
</summary>
<img width="1116" alt="Screenshot 2019-03-29 16 20 39" src="https://user-images.githubusercontent.com/71047/55267310-aa4af580-523e-11e9-96aa-0b79386816ad.png">
</details>

### Develop

<details>
<summary>Clear the screen and show nice success message</summary>
<img width="656" alt="Screenshot 2019-03-29 16 23 03" src="https://user-images.githubusercontent.com/71047/55267380-0150ca80-523f-11e9-9f7a-c6c91c08a486.png">
</details>

### Errors

<details>
<summary>Show nice & similar errors in both terminal and browser. Returns to success message in terminal + regular stuff in browser upon fixing error</summary>
<img width="637" alt="Screenshot 2019-03-29 16 24 42" src="https://user-images.githubusercontent.com/71047/55267420-3eb55800-523f-11e9-9c31-134fedd7334b.png">
<img width="761" alt="Screenshot 2019-03-29 16 24 52" src="https://user-images.githubusercontent.com/71047/55267422-407f1b80-523f-11e9-8e6b-9ce1ad220190.png">
</details>

### Production

<details>
<summary>With next.js you build the assets and then start the server. Spartan output that gets the job done but nothing more</summary>
<img width="397" alt="Screenshot 2019-03-29 16 27 59" src="https://user-images.githubusercontent.com/71047/55267553-06fae000-5240-11e9-848d-d3c3a45dfa3e.png">
<img width="416" alt="Screenshot 2019-03-29 16 29 27" src="https://user-images.githubusercontent.com/71047/55267554-08c4a380-5240-11e9-9540-00119ff68f0a.png">
</details>

**Comment by shannonbux** [comment]
# React-static

## Install
<details>
  <summary>Nothing noteworthy here</summary>
<img width="573" alt="Screen Shot 2019-03-29 at 5 06 54 PM" src="https://user-images.githubusercontent.com/32467162/55268356-344a8c80-5246-11e9-976d-9a90b3e3028c.png">
</details>

## CLI Help
<details>
  <summary>Seemed fairly standard, came up at end of installation process</summary>



</details>

## Create new project
<details>
  <summary>Suggested name for the project, prompted me to `cd my-project-name` and told me what to do next. Very nice! </summary>
<img width="447" alt="Screen Shot 2019-03-29 at 5 08 11 PM" src="https://user-images.githubusercontent.com/32467162/55268374-56440f00-5246-11e9-9d80-553d1a36eff4.png">
</details>

## Develop
<details>
  <summary>Hot reloading required me to refresh the page on Chrome. The CLI did a nice job converting my `npm start` command to what it needed me to run instead. I guess it could have prompted me to change my behavior too. Finally, I had to look a while for the link to the localhost:3000 </summary>
<img width="1238" alt="Screen Shot 2019-03-29 at 5 10 37 PM" src="https://user-images.githubusercontent.com/32467162/55268378-63f99480-5246-11e9-9748-947a81f7ddd7.png">

- The CLI did a nice job converting my `npm start` command to what it needed me to run instead.

- Finally, I had to look a while for the link to the localhost:3000 

</details>

## Build
<details>
  <summary>Click here to expand!</summary>


</details>

## Error & recovery
<details>
  <summary>Click here to expand!</summary>


</details>

**Comment by KyleAMathews** [comment]
## Hugo

### Install
<details>
<summary>Easy with homebrew</summary>
<img width="704" alt="Screenshot 2019-03-29 21 56 03" src="https://user-images.githubusercontent.com/71047/55520866-28d6d700-5633-11e9-864a-01110ee11448.png">
</details>

### Develop

<details>
<summary>Fast and simple</summary>
<img width="734" alt="Screenshot 2019-03-29 21 57 55" src="https://user-images.githubusercontent.com/71047/55520889-3d1ad400-5633-11e9-8c95-a36bb691f804.png">

</details>

### Handling errors

<details>
<summary>showed error in browser & terminal and cleared both once the error was fixed</summary>

<img width="1440" alt="Screenshot 2019-03-29 21 59 55" src="https://user-images.githubusercontent.com/71047/55520915-5885df00-5633-11e9-82b5-63a0ecf9922a.png">
<img width="1299" alt="Screenshot 2019-03-29 22 00 11" src="https://user-images.githubusercontent.com/71047/55520917-5b80cf80-5633-11e9-8ca5-cdab43aaf73c.png">
</details>

**Comment by KyleAMathews** [comment]
## create-next-app
<details>
<summary>Simple helper for quickly setting up new Next.js apps. Creates directory, installs dependencies, displays success message and help with commands people can run</summary>
<img width="485" alt="Screenshot 2019-04-03 17 14 15" src="https://user-images.githubusercontent.com/71047/55521086-10b38780-5634-11e9-833a-80445da05fc6.png">

</details>

**Comment by KyleAMathews** [comment]
#  Middleman

Ruby-based SSG

## Install
<details
<summary>New project creation is easy from CLI. Clones repo and installs gems</summary>

<img width="804" alt="Screenshot 2019-04-03 17 19 20" src="https://user-images.githubusercontent.com/71047/55521263-e8785880-5634-11e9-8ff2-92ee01e45e0d.png">
</details>

## Error handling

<details>
<summary>There's no hot reloading so you have to refresh to see errors. I was only able to trigger their error screen by calling a non-existent ruby function in the erb file. JS/frontmatter errors were ignored. The build failed with this error as well but it didn't show it — you needed to re-run the build with a `--verbose` flag</summary>

<img width="1440" alt="Screenshot 2019-04-03 17 25 01" src="https://user-images.githubusercontent.com/71047/55521430-908e2180-5635-11e9-9a93-3671bb4b1bfa.png">
</details>

**Comment by KyleAMathews** [comment]
# @11ty/eleventy

## Install

Standard NPM install

## New project

Docs instruct you to echo a string into a file to create your first file :-)  Everything is run out of the global so there's nothing to install in the project

## Error handling

<details>
<summary>I created a JS page and triggered an error. The CLI showed the error and the browser didn't. When I fixed the error, the CLI showed the build running again successfully</summary>

<img width="788" alt="Screenshot 2019-04-03 17 48 35" src="https://user-images.githubusercontent.com/71047/55522292-2bd4c600-5639-11e9-99ef-b0fc08949a72.png">

</details>

**Comment by KyleAMathews** [comment]
# Gridsome

## Install
Standard NPM global install

## New project
<details>
<summary>Did something pretty clever where they hid output cloning / installing packages (presumably _unless_ there's an error). Ended up being very clean</summary>
<img width="642" alt="Screenshot 2019-04-03 17 54 03" src="https://user-images.githubusercontent.com/71047/55524414-26c84480-5642-11e9-86aa-30048397430c.png">
</details>

## Develop
Shows log during bootstrap and then clears the screen to show the normal webpack successful compilation output

## Error and recovery
<details>
<summary>Shows error in browser & terminal and clears them on fixing</summary>

<img width="626" alt="Screenshot 2019-04-03 17 56 33" src="https://user-images.githubusercontent.com/71047/55524546-9d654200-5642-11e9-84ed-221ca4284ade.png">
<img width="1046" alt="Screenshot 2019-04-03 17 56 42" src="https://user-images.githubusercontent.com/71047/55524548-9f2f0580-5642-11e9-9977-370dcab1be37.png">
</details>

**Comment by shannonbux** [comment]
# Angular CLI

## [Angular Console](https://angularconsole.com/).
<details>
  <summary>A desktop app that allows you to run commands in a graphical interface.</summary> 
Features: 
- nav bar = recent, create, import. Also has icons to open project in finder, code editor, or terminal
- run schematics, see options and descriptions for each option, toggle & set options with toggle button and text input fields
- serve, test, build buttons
- works w/ any schematics you have set up

Pros: 
- way simpler than Vue's graphical UI

Cons:
- not sure what the audience is--how hard is it to look up schematic options and find out what they mean in a regular CLI?
</details>

## Install & create project
<details>
  <summary></summary>
- Installation was really fast = 27.63 seconds
- Not sure why I need to see a readout of the entire list of dependencies. Was super long (screenshot doesn't show them all)
<img width="1275" alt="Screen Shot 2019-03-29 at 4 14 42 PM" src="https://user-images.githubusercontent.com/32467162/55267202-19741a00-523e-11e9-8714-f1284e5c10dd.png">
- Creating a project was included in installation `npx create-react-app my-app` which was nice although it confused me since it's one less step than I'm used to
</details>

## CLI help
<details>
  <summary>appeared after I installed w/o needing additional command, which was nice</summary>
- appeared after I installed, which was nice
<img width="565" alt="Screen Shot 2019-03-29 at 4 13 58 PM" src="https://user-images.githubusercontent.com/32467162/55267215-298bf980-523e-11e9-9be2-1667fb4c403e.png">
</details>

## Develop
<details>
  <summary>localhost:3000 opened automatically after developing which was nice</summary>
- localhost:3000 opened automatically once I ran `npm start` in the project, which was nice, although the terminal said I would need to open it myself, so that was confusing bc I was about to type it in and then it just opened by itself
<img width="1280" alt="Screen Shot 2019-03-29 at 4 20 03 PM" src="https://user-images.githubusercontent.com/32467162/55267342-d1092c00-523e-11e9-85c6-dd7b15420d5f.png">
- hot reloading worked great
</details>

## Test
<details>
  <summary>Hadn't seen `npm test` options before this, seems useful</summary>
- `npm test` gave me some options for testing
<img width="396" alt="Screen Shot 2019-03-29 at 4 28 27 PM" src="https://user-images.githubusercontent.com/32467162/55267555-09f5d080-5240-11e9-9c95-fced18519703.png">
</details>

## Build
<details>
  <summary>`npm run build` comes up with some options that don't seem common enough to be front and center</summary>
- `npm run build` comes up with some options that don't seem common enough to be front and center
<img width="525" alt="Screen Shot 2019-03-29 at 4 32 10 PM" src="https://user-images.githubusercontent.com/32467162/55267583-390c4200-5240-11e9-830f-e8d8d4311c82.png">
</details>

## Errors and recovery
<details>
  <summary>Click here to expand!</summary>
- Command line and browser show same error when I entered 1/0 into a .js file
<img width="745" alt="Screen Shot 2019-03-29 at 4 33 29 PM" src="https://user-images.githubusercontent.com/32467162/55267607-796bc000-5240-11e9-95ce-3f1e5800d364.png">
<img width="662" alt="Screen Shot 2019-03-29 at 4 33 15 PM" src="https://user-images.githubusercontent.com/32467162/55267608-796bc000-5240-11e9-94c9-503e4ed85898.png">

</details>
