### ISSUE TITLE
react router v4

### ISSUE THREAD

**Issue by whmountains** [gatsbyjs/gatsby#1295]
Any chance you'll start using React-Router v4 in Gatsby?  It has a much cleaner API and I miss it from other projects.

**Comment by KyleAMathews** [comment]
@whmountains try out Gatsby v1! We're using RR v4 there

https://www.gatsbyjs.org/docs/

**Comment by KyleAMathews** [comment]
Gatsby v1 in in beta but getting pretty close to its first stable release. Feel free to jump in and start using it.
