### ISSUE TITLE
gatsby serve 出现端口被占用问题，能不能改gatsby serve 的端口号呀

### ISSUE THREAD

**Issue by tgy3300** [gatsbyjs/gatsby#12961]
F:\gatsby-site>gatsby serve
error UNHANDLED EXCEPTION
  Error: listen EADDRINUSE 127.0.0.1:9000

**Comment by anastasialanz** [comment]
I am also seeing this issue.

**Comment by sidharthachatterjee** [comment]
Like @anastasialanz correctly mentioned, `EADDRINUSE` is thrown when the port is already in use. This is a great opportunity to auto detect and let the user pick a port like we have for develop so I've gone ahead and added that in. 

Thank you for opening this @tgy3300 and for your response @anastasialanz!

**Comment by sidharthachatterjee** [comment]
Published in gatsby@2.3.5
