### ISSUE TITLE
Unable to remove gatsby v1 on mac

### ISSUE THREAD

**Issue by vermontdevil** [gatsbyjs/gatsby#12979]
This is weird. I have Gatsby V1.1.4 installed somewhere on my mac. I've ran the NPM install for gatsby-cli and NPM list -g is showing the latest gatsby-cli.

but when i ran gatsby -V, its showing 1.1.4  I thought the latest version is 2.x 

Found the old gatsby on /users/myname/.npm-packages and there's some old stuff here.

Can't uninstall gatsby here as NPM keeps pointing to the latest version elsewhere.

I'm unable to install any gatsby projects because of this. Any ideas? 

I'm using the latest Mac OSX version etc and it's a Macbook Pro.

**Comment by gurpreet-hanjra** [comment]
Maybe try `which gatsby` and it will show current location of gatsby and then you can remove it by going that location, something like `cd /usr/local/bin`
