### ISSUE TITLE
在 gatsby 中，如何请求api数据呢？

### ISSUE THREAD

**Issue by tgy3300** [gatsbyjs/gatsby#12983]
在 gatsby 中，如何请求api数据呢？非要使用GraphQL吗？

**Comment by gurpreet-hanjra** [comment]
https://www.gatsbyjs.org/docs/client-data-fetching/ you can fetch data with/without GraphQL

**Comment by LekoArts** [comment]
Hello, thank you for opening this issue!

We would really like to help you with your problem/question but we don't understand your language and therefore kindly ask you to write in the English language. Google Translate can only help a bit and in the end it would be a frustrating guessing game for both parties.

Please feel free to open a new issue (in English) and we'd be happy to help you then 💜

Thank you for using Gatsby!
