### ISSUE TITLE
Creating mappings automatically within a plugin

### ISSUE THREAD

**Issue by namuol** [gatsbyjs/gatsby#12982]
I'm building a custom plugin that works with a CMS that supports relational data (specifically, one-to-one and one-to-many relationships).

Is there a good way to implement these relations within the generated schema such that they feel as if they were created with [`gatsby-config`'s `mapping` option](https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types), but entirely within the plugin itself?

More concretely, suppose our plugin's user has two collections in their CMS, `BlogPost` and `Author`:

```js
{
  type: 'BlogPost',
  id: 'blog-post-42',
  // Each `BlogPost` can have 0 or more `Authors`
  authors: ['author-123', 'author-456'],
  ...
}
```

```js
{
  type: 'Author',
  id: 'author-123',
  ...
}
```

If they were to _manually_ configure the mapping between `BlogPost -> Author` it would look like this:

```js
module.exports = {
  plugins: [...],
  mapping: {
    'BlogPost.authors': `Author`
  }
}
```

To automate this behavior within the plugin, I imagine I could make use of [`createTypes`](https://www.gatsbyjs.org/docs/node-apis/#createTypes) and/or [`createResolvers`](https://www.gatsbyjs.org/docs/node-apis/#createResolvers), but given how ergonomic it is to use `mapping`, I was hoping plugin authors could somehow harness that interface.

- Are there any plans to support something like this, or is it already possible?
- Are there any existing DB/CMS plugins that support automatic relation mapping in this fashion?
  - I've discovered that `gatsby-source-pg` does support relation mapping, but it implements this by using [Postgraphile](https://www.graphile.org/postgraphile/) combined with `gatsby-source-graphql` - Clever!

Thank you 🙇 

## Relevant Links

- [StackOverflow:  How to make a one to many connection between Netlify CMS and Gatsby](https://stackoverflow.com/questions/49456106/how-to-make-a-one-to-many-connection-between-netlify-cms-and-gatsby)
- [Gatsby Docs: Mapping node types](https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types)
- [GH Issue: gatsby-source-mongodb doesn't support relationships](https://github.com/gatsbyjs/gatsby/issues/11587)

**Comment by pieh** [comment]
For mapping in plugin you'd need to use [`Foreign Key reference`](https://www.gatsbyjs.org/docs/schema-gql-type#foreign-key-reference-___node) in your data. In your example it would be:

```diff
{
  type: 'BlogPost',
  id: 'blog-post-42',
  // Each `BlogPost` can have 0 or more `Authors`
- authors: ['author-123', 'author-456'],
+ // ___NODE suffix instruct gatsby to create node link field
+ authors___NODE: ['author-123', 'author-456'],
  ...
}
```

```js
{
  type: 'Author',
  id: 'author-123',
  ...
}
```

`___NODE` suffix can be used for single "foreign node" id or array of ids (like in this example)

**Comment by namuol** [comment]
Thank you @pieh! 🙇 I read that section but incorrectly assumed it only worked for single IDs (e.g. `author: 'abc123'`), but it _should_ work in this case.

My next question is (anticipating edge cases 😅): When does `inferFromFieldName` (or GQL type inference in general) occur?

In the above example, I imagine inference would fail if the name of the field were something other than `authors` and there weren't any `Author` nodes created yet, but this _wouldn't_ be a problem if inference occurs _after_ every `createNode` call as there _would_ be some `Author` nodes to infer against.

**Comment by namuol** [comment]
Fantastic - thank you for the detailed explanation @pieh! I suppose this means Gatsby waits until after all `createNode` calls before the schema is resolved - makes a lot of sense :+1:
