### ISSUE TITLE
Correct custom eslint instructions

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#12980]
If people customize their eslint setup, we should recommend they start from our default setup https://www.npmjs.com/package/eslint-config-react-app and go from there.

Our current docs recommend something entirely different:
https://www.gatsbyjs.org/docs/eslint/#configuring-eslint

**Comment by KyleAMathews** [comment]
This is the file that defines our setup https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/eslint-config.js

**Comment by KyleAMathews** [comment]
@kkemple looked into writing out the schema so then a custom eslint config could use it. @freiksenet @stefanprobst — it'd be great to do that https://github.com/gatsbyjs/gatsby/issues/6167

**Comment by stefanprobst** [comment]
@KyleAMathews this is on the [roadmap](https://github.com/gatsbyjs/gatsby/issues/12510). In the meantime there is [this plugin](https://github.com/NickyMeuleman/gatsby-plugin-extract-schema).

**Comment by KyleAMathews** [comment]
Ok, no worries @stefanprobst 

So for now we should just recommend people use:

```js
{
      globals: {
        graphql: true,
        __PATH_PREFIX__: true,
      },
      extends: `react-app`,
}
```

**Comment by DSchau** [comment]
Would love for someone to pick this up--right now we're displaying a document that is a little bit less focused than we'd like.

## Description

- Update [this document](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/eslint.md) with the above instructions per @KyleAMathews 
    - Why?
        - This document is doing a bit too many things, e.g. adding prettier
        - We should advocate _simple_ set ups that work out of the box and scale as needed
- (Longer term!) we should expose something like `gatsby-config-eslint` which will be an opinionated set of defaults that are currently [internalized here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/eslint-config.js)
    - This requires changes to dumping our schema, so a quicker win is to first update the documentation and longer term externalize our config so it can be used by anyone

**Comment by DSchau** [comment]
@lukebrobbs not a dumb question, at all!

Yep, exactly. You'll want to edit [this file](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/eslint.md) and instructions to be a little simpler, and just install the necessary dependencies, e.g. `eslint-config-react-app`

Feel free to reach out if we can help with anything else!

**Comment by lukebrobbs** [comment]
Great, thanks! The npm page for `eslint-config-react-app` recommends installing the following for projects not build with Create React App: 

`npm install --save-dev eslint-config-react-app babel-eslint@9.x eslint@5.x eslint-plugin-flowtype@2.x eslint-plugin-import@2.x eslint-plugin-jsx-a11y@6.x eslint-plugin-react@7.x
` 

Will all of this need to be installed with Gatsby?
