### ISSUE TITLE
Gatsby项目中，页面基础模板如何指定

### ISSUE THREAD

**Issue by tgy3300** [gatsbyjs/gatsby#12984]
页面的

<!DOCTYPE html><html lang="en">
<head>
...
</head>
<body>
...
</body>
</html>

这个模板在哪里，能设置指定吗?

**Comment by gurpreet-hanjra** [comment]
You can use layout components as templates https://www.gatsbyjs.org/docs/layout-components/

**Comment by nihgwu** [comment]
https://www.gatsbyjs.org/blog/2018-06-08-life-after-layouts/
