### ISSUE TITLE
SourceMaps in Windows do not display correctly

### ISSUE THREAD

**Issue by andyfinch333** [gatsbyjs/gatsby#12986]
## Description

SCSS SourceMaps in any of the downloadable starter kits or in a fresh build of Gatsby, do not correctly show SCSS SourceMap references in the Web Inspector. In Firefox on Windows you see a Blob reference (Screenshot attached), In Chrome, you see an absolute path that repeats several times (screenshot attached), which while better as I can work out what file the code references, does not look great. I feel like a lot of people must have this issue as all the starter kits i've downloaded have this problem. This issue is present in Gatsby v1 and v2, it is not present in similar Static Generators such as Next.js, so I feel it's not an issue with Webpack.

The same build, when run on Linux, shows source map references correctly which leads me to believe this issue seems to be limited to Windows.

### Steps to reproduce

1. Clone repository - https://github.com/ueno-llc/ueno-gatsby-starter
2. Follow instructions to install, launch gatsby develop.
3. Use web inspector to view sourcemap location

Works with any repository from Starter Library or fresh build of Gatsby.

### Expected result

Ideally, you will see scss source maps are compiled correctly and display correctly in All Browsers pointing only to a file with extension.

### Actual result

You see scss source maps are compiled but in Firefox inspector you see a Blob Reference.
You see scss source maps are compiled but in Chrome inspector you see an absolute path 3x.
You see scss source maps are compiled correctly and display correctly in Chrome on Linux.

### Environment
Gatsby 2.1.23
Windows 10

Run `gatsby info --clipboard` in your project directory and paste the output here.

Command not recognized.

### Screenshots
![gatsby-sm-firefox](https://user-images.githubusercontent.com/37833451/55321478-a94dda00-5471-11e9-8a12-4f72cbfe8551.png)
![gatsby-sm-chrome](https://user-images.githubusercontent.com/37833451/55321477-a8b54380-5471-11e9-80ba-51229065ab8a.png)

**Comment by pieh** [comment]
I did reproduce it locally, will investigate

**Comment by pieh** [comment]
This issue doesn't seem sass/scss specific - it also happen with vanilla css, so I this seems either css-loader or style-loader (or our configuration for them)

**Comment by pieh** [comment]
Seems like this is exactly this problem - https://github.com/postcss/postcss-loader/issues/390

**Comment by andyfinch333** [comment]
Yeah I think you are right, Seems this issue has not been fixed yet, is the best way to remove postcss loader? However, I'm not finding it easy to see what the default Webpack config for Gatsby is to modify it.

**Comment by wardpeet** [comment]
It's not easy to remove it and it might break your site but you can find more info on how to replace your webpack config
https://www.gatsbyjs.org/docs/add-custom-webpack-config/

**Comment by pieh** [comment]
@andyfinch333 The problem is ... that `css-loader` is calling `postcss` in its internals ( https://github.com/webpack-contrib/css-loader/blob/v1.0.1/lib/processCss.js#L182-L192 ) this is exact spot where source maps are getting mangled - before that they are correct - but output of the `postcss` pipeline contains borked paths. So removing `postcss` won't solve this as `css-loader` on itself is doing that.

That being said - we are on `css-loader@1` and there is version `2` released, just not sure if this is fixed and if there are any breaking changes that would cause troubles to existing sites.
