### ISSUE TITLE
Gatsby hosting

### ISSUE THREAD

**Issue by lpluispacheco** [gatsbyjs/gatsby#12993]
Hi, what's the hosting cheapest option where I can use Gatsby with netilifycms?

I want to give my services of web design but I really don't know very well the hosting that I can use that work with gatsby and netlifycms I want to know the prices of servers, what hosting can work with gatsby and netlifycms together.

Thanks!

**Comment by DSchau** [comment]
Gatsby produces static content which can be hosted on _any_ static content host. Big ones are AWS Amplify, S3 + Cloudfront, Netlify, etc.

We have [guides for deploying to a variety of providers](https://www.gatsbyjs.org/docs/deploying-and-hosting/), so I'd encourage you to check them out and find one that suits your particular use case. Off hand, you can't beat free--and Netlify is effectively free depending upon what features you need, exactly.

Closing as answered, but please feel free to continue the discussion if one of us can help further. Thanks!

**Comment by lpluispacheco** [comment]
> Gatsby produces static content which can be hosted on _any_ static content host. Big ones are AWS Amplify, S3 + Cloudfront, Netlify, etc.
> 
> We have [guides for deploying to a variety of providers](https://www.gatsbyjs.org/docs/deploying-and-hosting/), so I'd encourage you to check them out and find one that suits your particular use case. Off hand, you can't beat free--and Netlify is effectively free depending upon what features you need, exactly.
> 
> Closing as answered, but please feel free to continue the discussion if one of us can help further. Thanks!

Hi **DSchau**, thanks for your answer.

There's only one thing left, I have made this website for an hostel:

https://inspiring-bell-9fbb73.netlify.com/

It's almost done, when it's get done in your point of view what gonna be ideal hosting? Because it has netlify-cms, I don't know 100% if uploading just the static files the CMS will work? That's my doubt left, if you know any guide that I can read or something I'll really appreciate it.

Thanks **DSchau**!

**Comment by DSchau** [comment]
> It's almost done, when it's get done in your point of view what gonna be ideal hosting? Because it has netlify-cms, I don't know 100% if uploading just the static files the CMS will work? That's my doubt left, if you know any guide that I can read or something I'll really appreciate it.

I wouldn't say there's a Gatsby-official "ideal hosting." I would say if that works for you and your project--then that's as ideal as it can be!

> Because it has netlify-cms, I don't know 100% if uploading just the static files the CMS will work

I'd urge you to work with the client/customer/etc. to see if it meets their needs. If it doesn't for whatever reason, you could consider using any number of the other CMSes Gatsby supports, e.g. Wordpress, Drupal, Contentful, etc.

**Comment by lpluispacheco** [comment]
> > It's almost done, when it's get done in your point of view what gonna be ideal hosting? Because it has netlify-cms, I don't know 100% if uploading just the static files the CMS will work? That's my doubt left, if you know any guide that I can read or something I'll really appreciate it.
> 
> I wouldn't say there's a Gatsby-official "ideal hosting." I would say if that works for you and your project--then that's as ideal as it can be!
> 
> > Because it has netlify-cms, I don't know 100% if uploading just the static files the CMS will work
> 
> I'd urge you to work with the client/customer/etc. to see if it meets their needs. If it doesn't for whatever reason, you could consider using any number of the other CMSes Gatsby supports, e.g. Wordpress, Drupal, Contentful, etc.

Perfect, thanks for your help!
