### ISSUE TITLE
gatsby-remark-images-contentful for referenced images

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#12999]
## Description

`gatsby-remark-images-contentful` seems to not apply to images whose source is referenced at the bottom of the file.

<img width="856" alt="contentful-markdown" src="https://user-images.githubusercontent.com/30958850/55356119-5d7b4f00-54ca-11e9-90ff-377d5a7089c9.png">

### Steps to reproduce

I would expect this markdown to be parsed the same

```md
![alt][1]

[1]: //images.ctfassets.net/gi9muc70s4ub/1Q7vDiIeUs8KYaG6E2aiYy/117d037ae49ad0ad626491962db5544d/image.jpg
```

as this

```md
![alt](//images.ctfassets.net/gi9muc70s4ub/1Q7vDiIeUs8KYaG6E2aiYy/117d037ae49ad0ad626491962db5544d/image.jpg)
```

### Actual result

<img width="454" alt="html" src="https://user-images.githubusercontent.com/30958850/55356296-b945d800-54ca-11e9-8717-836143fb36e2.png">

### Expected result

<img width="456" alt="html-expected" src="https://user-images.githubusercontent.com/30958850/55356490-1fcaf600-54cb-11e9-90fc-ca1b58579d63.png">

**Comment by pieh** [comment]
`gatsby-remark-images` does support that, so this is missing feature. If anyone is interested in adding support for this in `gatsby-remark-images-contentful` please note how this is implemented in `gatsby-remark-images`:

make sure you handle image reference AST nodes:
https://github.com/gatsbyjs/gatsby/blob/87c1f2884a81b6221523e0210012db7db33ef4bf/packages/gatsby-remark-images/src/index.js#L62-L70

make sure alt tag for image ref is maintained:
https://github.com/gatsbyjs/gatsby/blob/87c1f2884a81b6221523e0210012db7db33ef4bf/packages/gatsby-remark-images/src/index.js#L295-L309
