### ISSUE TITLE
Figure out ways to share code with Antwar?

### ISSUE THREAD

**Issue by bebraw** [gatsbyjs/gatsby#13]
Just a quick FYI, we've been working on a similar tool known as [Antwar](https://antwarjs.github.io/) for a few months. Interestingly there's a huge amount of overlap in terms of functionality and goals.

Perhaps we could find some way to collaborate or share code even? That might be beneficial to both projects.

**Comment by KyleAMathews** [comment]
That'd be great! I'm a solo technical startup founder so I really don't have time to be working on a big open source project like this :) so would love to join forces with like-minded folks.

I'm not super familiar with Antwar. Where do you see areas where we can collaborate?

**Comment by bebraw** [comment]
Well, we have a fairly extensive plugin system in Antwar. The plugins themselves are quite simple. A couple of examples: [https://github.com/antwarjs/rss-plugin](rss-plugin), [prevnext-plugin](https://github.com/antwarjs/prevnext-plugin). They can attach themselves to various processing hooks. You could reuse our work by implementing some sort of adapter or matching the design.

Antwar is structurally more flexible. It accepts literally anything. It's up to you to configure it. I've done something fairly complicated at [SurviveJS site](https://github.com/survivejs/site/blob/master/antwar.config.js). And from my perspective that's great! I can map [GitBook](https://github.com/GitbookIO/gitbook) content to my site while using Leanpub definitions (Book.txt, custom syntax) with no problems. This leads me to think that we might be able to adapt Antwar to run gatsby sites.

If we share enough common goals one option would be to merge the projects. We can for instance adapt Antwar APIs closer to gatsby. I would love to ditch mixins and go through props. A merge comes with its issues but it's more sustainable than to "compete". After all both of us want a solid site generator.

**Comment by KyleAMathews** [comment]
So Gatsby seems much more of a convention over configuration software than Antwar. For example files are translated directly into pages e.g. `/docs/help/index.md` becomes `/docs/help/index.html`.

https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/glob-pages.coffee reads files off the fs and https://github.com/gatsbyjs/gatsby/blob/master/lib/isomorphic/create-routes.coffee turns the file structure into a React Router configuration. File information + file metadata (e.g. compiled Markdown body + frontmatter) get passed down to templates and page renderers.

With this Gatsby gets zero-reload page transitions etc. It's basically an auto-generated SPA with each page having its own pre-rendered static entrypoint. Everything is designed around making this really easy.

I want to formalize extension points for Gatsby so syncing plugins with Antwar makes sense but we'd need to agree on a common file object format to do that.

**Comment by bebraw** [comment]
> So Gatsby seems much more of a convention over configuration software than Antwar. For example files are translated directly into pages e.g. /docs/help/index.md becomes /docs/help/index.html.

Exactly. Antwar is the exact opposite on this regard. Configuration over convention. It's like webpack but for static sites. We wanted specifically something that provides a lot of programmability. :)

> With this Gatsby gets zero-reload page transitions etc. It's basically an auto-generated SPA with each page having its own pre-rendered static entrypoint. Everything is designed around making this really easy.

This is probably where I can learn from you. We generate the site through React Router as well. The eventual idea is that it should be possible to hit between static/dynamic loading. I mean the first hit will always be static loading but after that React Router can kick in and start loading dynamic content bundles -> no refresh. Webpack can deal with the heavy lifting here and generate those for us. If JavaScript is disabled it will revert to static behavior.

It is possible you might have something like this already. I didn't look that closely. :+1:

For me that static/dynamic thing would be awesome as it might allow more interesting transitions between pages and most importantly scroll based user interfaces. New content would appear as you scroll getting you a little nicer ux. This is handy especially for blog indices and such. And all of this is possible through a static site generator without having to drop a backend into the mix.

> I want to formalize extension points for Gatsby so syncing plugins with Antwar makes sense but we'd need to agree on a common file object format to do that.

There are probably two bigger things to resolve: theming and plugins. Especially when it comes to theming Antwar is a little weak. We provide starting points but quite soon you'll have to start overriding layouts. It's possible we're approaching it wrong. Composition might be a better way here.

Given we're both operating with React we can perhaps find a lot of common especially here. Our current system relies on custom mixins but I would love to move to use props instead as that's Antwar agnostic way to deal with it.

Antwar provides a large amount of hooks for plugins. For instance [ga-plugin](https://github.com/antwarjs/ga-plugin/blob/master/index.js) injects to body. Same goes for [prevnext-plugin](https://github.com/antwarjs/prevnext-plugin/blob/master/index.js). `prevnext-plugin` also shapes page data (adds prev/next info). This additional data can be used to render actual elements. [highlight-plugin](https://github.com/antwarjs/highlight-plugin/blob/master/index.js) is more complex as it performs some postprocessing.

I've described the basic interface at [plugin-boilerplate](https://github.com/antwarjs/plugin-boilerplate/blob/master/index.js). That gives you the hooks we're using. You may want to grep Antwar source to see where they are used exactly and how.

I expect the current plugin format is quite close to something that could work for both projects. They are just React components that have been wrapped in a function after all so there isn't anything in particular that ties them specifically to Antwar apart from `prevnext-plugin` as that operates on Antwar page structure.

@eldh Feel free to comment on this thread.

**Comment by eldh** [comment]
Would be awesome if there are ways to share code. I think you have covered the entry points.

I'd also love to see Antwar implement the SPA generation. Should look into using Gatsby code for that :)

**Comment by KyleAMathews** [comment]
On theming, I really like what I came up with. It mirrors the React Router api so you can very easily nested UI templates. I've found this system very intuitive for both normal SPA as well as the Gatsby sites I've built/am building.

For example in the docs example site, [this is the top-level template which sets up the site header + grid container](https://github.com/gatsbyjs/gatsby-starter-documentation/blob/master/pages/_template.cjsx).

Then [this is the template for individual (markdown) pages](https://github.com/gatsbyjs/gatsby-starter-documentation/blob/master/pages/docs/_template.cjsx). Because of the nesting UI from React Router, the templates have all been entirely decoupled.

**Comment by gesposito** [comment]
These are my current top 2 project for React static sites, I follow both of them waiting for more.
I'd love you guys joining forces, I love the React Router based (isomorphic) theming and the plugins system.

**Comment by KyleAMathews** [comment]
Cleaning up issues and closing this as the discussion's petered off. Happy to collaborate still if we come across more joint issues.
