### ISSUE TITLE
can I've collections?

### ISSUE THREAD

**Issue by sandrodz** [gatsbyjs/gatsby#130]
My site structure is complicated. I need to have several different collections. Is this possible?

**Comment by KyleAMathews** [comment]
Every page has access to all other pages. So wherever you want a collection, just add a React.js component there e.g. to create a photo gallery, `/photos.js`.

In Gatsby 0.8+ page data is at `this.props.route.pages`. For a photo gallery, you write a filter function which pulls out all the photo pages.
