### ISSUE TITLE
gatsby build build hangs indefinitely when there are 0 pages/queries

### ISSUE THREAD

**Issue by cdaringe** [gatsbyjs/gatsby#13019]
## Description

in circleci, my build hangs in machine and docker builds.  in either case, it's a linux os:

```
+ DEBUG='gats*,cow*'
+ yarn build --verbose
yarn run v1.13.0
$ gatsby build --verbose
verbose 0.401 set gatsby_log_level: "verbose"
verbose 0.403 set gatsby_executing_command: "build"
verbose 0.404 loading local command from: /home/circleci/project/node_modules/gatsby/dist/commands/build.js
verbose 1.73 running command: build
success open and validate gatsby-configs — 0.005 s
success load plugins — 0.086 s
success onPreInit — 0.022 s
success delete html and css files from previous builds — 0.005 s
success initialize cache — 0.008 s
success copy gatsby files — 0.017 s
success onPreBootstrap — 0.009 s
success source and transform nodes — 0.023 s
success building schema — 0.089 s
success createPages — 0.000 s
success createPagesStatefully — 0.017 s
success onPreExtractQueries — 0.000 s
success update schema — 0.008 s
success extract queries from components — 0.008 s 
# and nothing else.  hangs.
```

### Steps to reproduce

- clone https://github.com/cdaringe/cowtown
- `yarn && yarn bootstrap`
- `cd packages/docs`
- `DEBUG=gats*,cow* yarn build --verbose`
 
### Expected result

`success Building static HTML for pages`

### Actual result

hangs.  works on osx!

### Environment

```
+ npx gatsby info

  System:
    OS: Linux 4.4 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
```

**Comment by pieh** [comment]
It looks like it's hanging in `running graphql queries` step. Not quite sure what could cause this, will try to reproduce on linux

**Comment by pieh** [comment]
I definitely can reproduce with your repo in ubuntu VM - will investigate.

One note, is that this doesn't happen with starters, so there has to be something specific in your site (or some dependencies in your site)

**Comment by pieh** [comment]
And also I can reproduce this on OSX as well - so doesn't seem linux specific. It most likely are some dependency changes - you don't have lock file checked in your repo, so those will use newest packages possible, but locally you probably have lock file that pins it to some version where it works

**Comment by pieh** [comment]
hmmmm you have 0 pages in your site. This is definitely bug in gatsby and should hang when there is 0 pages. But after adding single page to it - it works.

**Comment by JacobDFrank** [comment]
> Hiya!
> 
> This issue has gone quiet. Spooky quiet. 👻
> 
> We get a lot of issues, so we currently close issues after 30 days of inactivity. It’s been at least 20 days since the last update here.
> 
> If we missed this issue or if you want to keep it open, please reply here. You can also add the label "not stale" to keep this issue open!
> 
> Thanks for being a part of the Gatsby community! 💪💜

Just got this issue on my netlify build.

**Comment by cdaringe** [comment]
oh @gatsbot you little eager closing troll ;) still an issue.

**Comment by eadistar** [comment]
@cdaringe  Remove .cache folder and try again. It will work.

**Comment by cdaringe** [comment]
@eadistar, since last time I suffered the issue, purging the cache did not work

**Comment by bensink** [comment]
clearing cache worked for me! thanks

**Comment by RCopeland** [comment]
i have this issue when our mono-repo's other project folders contain node_modules. If i delete them, it builds the pages and continues normally. I've tried using gatsby-plugin-exclude to ignore the files, but it doesn't help.
