### ISSUE TITLE
gatsby-transformer-remark and copied markdown files

### ISSUE THREAD

**Issue by secondary-school55** [gatsbyjs/gatsby#13023]
## Summary
It that by design, gatsby-transformer-remark is copying markdown files to public when build production build? Can it be disabled?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
It should not copy markdown files? Are you sure it's `gatsby-transformer-remark` doing it? Can you share reproduction?

**Comment by secondary-school55** [comment]
@pieh 
Repository for reproduction: [link](https://github.com/secondary-school55/site)

After build there are large amount index-{content_digest}.md in public/static/
Maybe it gatsby-source-filesystem is copying that files

**Comment by secondary-school55** [comment]
Found source of problem:
``
await graphql(`
    {
      allFile {
        edges {
          node {
            publicURL
          }
        }
      }
    }
  `);
``
It copying all files via publicURL resolver.
