### ISSUE TITLE
Improve error messaging for sharp

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#13026]
`sharp` is a really important dependency for us since we use it in `gatsby-plugin-sharp`, `gatsby-transformer-sharp` and `gatsby-plugin-manifest`

We've seen several instances where something has failed in one of the plugins above but has been difficult to debug. These issues tend to fit in one of the following three categories:

1. Errors due to broken native dependencies or install time issues
2. Errors due to invalid images
3. Errors due to potential race conditions (https://github.com/gatsbyjs/gatsby/pull/12927)

While some of the above can be fixed (like 3), the others would benefit from better error messaging. 

Todo
- [x] Bail early in sharp if bindings are broken (https://github.com/lovell/sharp/pull/1638)
- [x] Remove warning from gatsby-plugin-sharp
- [ ] Improve messaging in sharp if image format is invalid

Related issues: https://github.com/gatsbyjs/gatsby/issues/10841

**Comment by m-allanson** [comment]
First parts of this are done, closing! 

@sidharthachatterjee to create a separate issue tracking the last point.
