### ISSUE TITLE
[1.0] Documentation Pages Broken

### ISSUE THREAD

**Issue by jeffpamer** [gatsbyjs/gatsby#1304]
I know they are still in development. But at the moment all of the pages in the docs except "Getting Started" are empty.

![image](https://user-images.githubusercontent.com/888818/27716825-eaf77710-5cf5-11e7-802f-bb37ae8f40e0.png)

**Comment by KyleAMathews** [comment]
Yeah there was a bug with an earlier deploy which I fixed a bit ago. Thanks
for the report!
