### ISSUE TITLE
Dynamic page content with custom APIs

### ISSUE THREAD

**Issue by renanpupin** [gatsbyjs/gatsby#13043]
Hi,
this issue is a question about how gatsby can be integrated with a server content (an express nodejs API for exemple).

Is there a way that Gatsby could query data from backend and just return the page after get the content? If I use axios requests, before it gets the result data, the gatsby page already got returned, so when I inspect my code from crawlers or OpenGraph API linter, it does not have the content, and the SEO is wrong.

So my question is, gatsby provides a way to handle this return in server side and only load the site when the template is hydrated?

**Comment by pieh** [comment]
How often that date in your backend changes? Ideally you could make request during build time and embed that data statically (and rebuild site when the data changes).

If this is not feasible or if data just changes very often (like every 30 seconds), then this is pretty challenging. We could add APIs that allow you to delay initial app mount or page transitions (we don't have those right now), but I don't think it would solve the issue with crawlers as they potentially would use just static content and not wait for react application to mount.
