### ISSUE TITLE
Gatsby query like insert

### ISSUE THREAD

**Issue by lpluispacheco** [gatsbyjs/gatsby#13044]
Hi, I have a doubt about the query's. 

Is possible make a query to insert data in x.MD files? Using any CMS, By example:

Room.md
---
available: 1
---

Later on when a user clicks a button set the available to 0? Any trick or function to make it works?

Thanks!

**Comment by pieh** [comment]
You mean like actually change markdown file? Or just change what is displayed on the page? If this is just changing what is displayed on the page you can make stateful react component and adjust the component state.

Can you clarify?

**Comment by lpluispacheco** [comment]
Change the markdown file directly, without get in the x CMS that it's connected with gatsby

**Comment by jonniebigodes** [comment]
@lpluispacheco if i'm reading this correctly you want to change the contents of the .md file when some action is triggered, for instance if you click a button and the contents is updated, am i right? If that is the case, then you cannot do it out of the box as most plugins that exist in the gatsby ecosystem are "a one way street" (pardon the bad pun), or in other words, they only consume data, they don't mutate it. 

In this case for instance as you want to mutate the file, you would have to open the file in question, search for the specific item to change either in the form of a keyword or some other marker to identify what needs to be change and apply it. 

That would lead to problems further down the line, contents inconsistencies or issues when building as the file in question could be still be "locked" and it was needed and some more situations that could lead to alot of headaches for the developer(you) and the gatsby team to handle. If you need to mutate the contents of some data, it's best to choose another approach, use a cms like wordpress, drupal, graphcms, or even a more simpler approach, a simple rest server with a database connection.
