### ISSUE TITLE
Reverse routing and typesafe linking

### ISSUE THREAD

**Issue by slorber** [gatsbyjs/gatsby#13069]
## Summary

Some frameworks permit to do some kind of "reverse routing". The purpose is to be able to generate a typesafe way to link to existing pages (including potential page parameters)

Here is an example with Play/Scala: https://www.playframework.com/documentation/2.7.x/ScalaRouting#Reverse-routing

### Basic example

Don't have an example of how this should be implemented. This can be different for TS/Flow users and for JS users.

For JS, just emitting a list of constants for all possible paths at build time could be useful.

For TS/flow it could be to generate a union type of acceptable props for the link comp:

`type LinkProps = {to: "page1", params: {x: string} | {to: "page2", params: {y: string}`

### Motivation

Ensure typesafety for Link to prop, to avoid typos in strings.

Follow up of this tweet conversation  https://twitter.com/gatsbyjs/status/1113151235169771521

**Comment by pieh** [comment]
TS/flow typing would have some flaws the type/union for acceptable paths need to be generated during build / develop - so those union can be outdated if user creates new pages (as union won't be updated until user run `gatsby build/develop`). So this can generate some false negatives/positives.

But adding built time check does make a lot of sense

**Comment by slorber** [comment]
Actually some tools like Apollo codegen allow to generate types live and it works great. It can be a cli command with a - -watch option so that it's more explicit that things can be out of date if the cli is not run.
