### ISSUE TITLE
No matching version found for babel-plugin-remove-graphql-queries@^2.6.3

### ISSUE THREAD

**Issue by Blumed** [gatsbyjs/gatsby#13065]
## Description

Updating gatsby from 2.0.75 to 2.3.7 and I get the following error in my `npm i` `No matching version found for babel-plugin-remove-graphql-queries@^2.6.3` So I downloaded the dependency alone and the version printed 2.6.2 in my package.json. Did gatsby jump the gun with this package version?

I got curious and brought my old lock file back and ran `npm i` and of course, the install worked again. Found the nexus url in my lock file and changed the version of the babel dep to the one gatsby2.3.7 is requesting it downloads, so it exists. Opened downloaded asset and peek inside the package.json and 2.6.3 version at the top. I don't understand why this happening. Gatsby's version numbers look like they are correct but my npm installs are just getting hung up.

Here is the full message:

```
bash-4.4# npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for babel-plugin-remove-graphql-queries@^2.6.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'gatsby'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-03T06_44_14_064Z-debug.log
```

### Steps to reproduce

- Download gatsby default starter version 0.1.0
- package.json change gatsby version to latest

### Expected result

npm install would complete successfully

### Actual result

npm install was unsuccessfull

### Environment

``` 
 System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 65.0.1
    Safari: 12.1
  npmGlobalPackages:
    gatsby: 2.0.107
```

**Comment by pieh** [comment]
Super weird - the package is on npm with `2.6.3` version. https://www.npmjs.com/package/babel-plugin-remove-graphql-queries?activeTab=versions

I also just tried installing latest thing with both `yarn` and `npm` and it worked. Do you maybe use some npm repository mirror?

**Comment by Blumed** [comment]
I just double checked with my devops person who setup our docker flow which gatsby is being installed into and he said we are not using any npm repository mirror.

**Comment by Blumed** [comment]
I ended up using yarn instead of npm and the issue went away.
