### ISSUE TITLE
[gatsby-transformer-json] parsing HTML in template: server render OK, React app not so much

### ISSUE THREAD

**Issue by endymion1818** [gatsbyjs/gatsby#13068]
## Description

I'm bringing in the contents of a JSON file with gatsby-source-filesystem and transforming it using gatsby-transformer-json. I'm not doing any schema transforms, everything else is default.

One field in this JSON content is HTML, they contain <a> tags predominantly.

I'm using `dangerouslySetInnerHTML` to populate my template, and when I turn JavaScript OFF in my built application, I can see it's rendering fine. However, some of the nodes in the React app don't seem to be able to render this content. I can see the element I'm rendering to, but there's nothing in there.

It's only happening with a subset of nodes, and only occurs in the built application, so it's really hard to debug.

I'm going to work on a demo of this to evidence what's happening.

### Steps to reproduce

- Load the plugins gatsby-source-filesystem & gatsby-transformer-json
- Have one field of HTML content
- Query using graphql
- Loop over nodes into a template
- Use `dangerouslySetInnerHTML` to render HTML field

### Expected result

Content should render as HTML

### Actual result

Content renders as HTML _on the server_, the React app often misses, leaving an empty HTML tag when viewed in FireFox, and when the page is refreshed in Chrome.

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 62.0
    Safari: 12.1
  npmPackages:
    gatsby: ^2.1.20 => 2.1.22 
    gatsby-cli: ^2.4.5 => 2.4.12 
    gatsby-image: ^2.0.26 => 2.0.30 
    gatsby-link: ^2.0.12 => 2.0.13 
    gatsby-plugin-canonical-urls: ^2.0.8 => 2.0.10 
    gatsby-plugin-google-tagmanager: ^2.0.6 => 2.0.9 
    gatsby-plugin-manifest: ^2.0.4 => 2.0.20 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.7 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-remove-trailing-slashes: ^2.0.9 => 2.0.9 
    gatsby-plugin-robots-txt: ^1.3.0 => 1.4.0 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.23 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.6 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.6 
    gatsby-plugin-typescript: ^2.0.3 => 2.0.9 
    gatsby-source-apiserver: ^2.0.0 => 2.1.1 
    gatsby-source-filesystem: ^2.0.1 => 2.0.23 
    gatsby-source-lever: ^2.0.4 => 2.0.5 
    gatsby-source-wordpress: ^3.0.0 => 3.0.41 
    gatsby-transformer-csv: ^2.0.4 => 2.0.7 
    gatsby-transformer-javascript-frontmatter: ^2.0.0 => 2.0.8 
    gatsby-transformer-json: ^2.1.2 => 2.1.8 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.14 
  npmGlobalPackages:
    gatsby-cli: 2.5.2

**Comment by pieh** [comment]
This is super weird. We use same component for "server side rendering" (building static html file) and runtime rendering, so this looks like there is some difference between `react-dom.render` and `reach-dom/server.renderToString` (or our handling of those). Reproduction will really be needed to figure this out, because we didn't see this issue yet

**Comment by endymion1818** [comment]
Actually I can share the url since it's public: https://shopfront.uat1.dev.zopa.com/about/awards#2017

Note it'll probably look OK on first render, but refresh or open in Firefox and it'll show up.

**Comment by pieh** [comment]
I can't really cause it to do something weird :/ It seems to work fine here? Can you maybe show recording of what is happening, because I also not quite understand what is exacty wrong - do you get blank pages?

**Comment by endymion1818** [comment]
I've been a bit slow & deliberate with this video, so there are some pauses, but you should see the paragraph of text disappear when I hit the refresh button:

![13068](https://user-images.githubusercontent.com/2216344/55539719-3e8edf80-56b9-11e9-92c3-ae90f36ecd6e.gif)
