### ISSUE TITLE
[gatsby-source-filesystem] createRemoteFileNode Authorization and custom headers

### ISSUE THREAD

**Issue by DevSide** [gatsbyjs/gatsby#13075]
## Summary

This request is about passing an Authorization header to the createRemoteFileNode function.
Eventually any kind of custom headers could be passed.

### Motivation

My use case is to fetch files using a JWT token like `Authorization: Bearer MY_TOKEN` header.

**Comment by pieh** [comment]
There is open pull request for it https://github.com/gatsbyjs/gatsby/pull/11682

**Comment by sidharthachatterjee** [comment]
This was added by @iFlameing in https://github.com/gatsbyjs/gatsby/pull/11682 and published in `gatsby-source-filesystem@2.0.29` 🎉
