### ISSUE TITLE
exports.onCreatePage -> I get the same mdx file twice

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#13071]
In `gatsby-node.esm.js`, if I have the code

```js
exports.onCreatePage = ({ page, actions }) => {
  const { createPage, deletePage } = actions
  console.log('____________________________________________')
  console.log(page)
}
```

I see the same page twice, which is a `.mdx` file that exists only as one file, as checked in the explorer and in `http://localhost:8000/___graphql`

The difference between the 2 received files is the `page.updatedAt` string, and that one doesn't have `frontmatter`. If I add a second `.mdx` file in the folder, then I receive also this one twice, one with formatter, the other without.

```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  Binaries:
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - C:\Python27\python.EXE
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.1.4 => 2.1.4
    gatsby-plugin-compile-es6-packages: ^1.1.0 => 1.1.0
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-page-creator: ^2.0.12 => 2.0.12
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.11
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7
    gatsby-source-filesystem: ^2.0.28 => 2.0.28
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17
```

**Comment by kuworking** [comment]
I see now that the cause of the error is that I receive the same `page` twice, and the second time there is a name collision or something (I assume).

Curious, they are the same file (referring to a `.mdx` file) that however one corresponds to the current version and the other to a past version (from few minutes ago). Why am I receiving this page, if I'm deleting `.cache` and `public` folders before `gatsby develop`? It doesn't exist (!?)

**Comment by pieh** [comment]
That's because of how `gatsby-mdx` work. It uses `onCreatePage` listener on it's own and add frontmatter to page ( https://github.com/ChristopherBiscardi/gatsby-mdx/blob/master/packages/gatsby-mdx/gatsby/on-create-page.js ).

This is not a bug

**Comment by kuworking** [comment]
Ok, then if I am filtering not to process those files without frontmatter (just checking that there is no frontmatter there) it is already what I should be doing, right? If that's the case, let's close the ticket :)

**Comment by wardpeet** [comment]
Could you share a repro? You shouldn't do anything special, just enable mdx plugin. I might not understand the problem.

**Comment by kuworking** [comment]
If I am understood it well, by enabling the mdx plugin, if I use `onCreatePage` I will receive two instances of the same `mdx` file, but this a consequence of the mdx plugin and not a problem to be solved.

In other words, if I use `onCreatePage` to remove things from the url, as documented [here](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#removing-trailing-slashes), and I also use the `mdx` plugin, then I will receive the same "page" twice in `onCreatePage` as a consequence of using the `mdx` plugin. In my eyes, if this is well documented then it is not really a problem since one can filter between the two "same" pages.

In detail, I am filtering out the instance of the file that I don't want to touch (the one that __does not have__ frontmatter) with 

```js
  if (page.path !== oldPage.path 
    && (type !== '.mdx' || (type === '.mdx' && page.context.frontmatter))) {
    deletePage(oldPage)
    createPage(page)
  }
```

What's your opinion? I'm ok with closing the issue

**Comment by wardpeet** [comment]
Oh yeah I see what you get at, sadly there is nothing to do about it. Your solution is 👌
