### ISSUE TITLE
[gatsby-plugin-advanced-sitemap] is exporting a variable named "__esModule" which isn't an API.

### ISSUE THREAD

**Issue by sethxd** [gatsbyjs/gatsby#13082]
## Description

I'm seeing this error when I run gatsby build or gatsby develop locally, and also when I try to deploy to netlify. It doesn't stop the site from loading locally, but it does cause the netlify build to fail.

### Steps to reproduce

Here's the setup for the plugin in my gatsby-config:

{
            resolve: `gatsby-plugin-advanced-sitemap`,
            options: {
                query: `
                {
                    allGhostPost {
                        edges {
                            node {
                                id
                                slug
                                updated_at
                                created_at
                                feature_image
                            }
                        }
                    }
                    allGhostPage {
                        edges {
                            node {
                                id
                                slug
                                updated_at
                                created_at
                                feature_image
                            }
                        }
                    }
                    allGhostTag {
                        edges {
                            node {
                                id
                                slug
                                feature_image
                            }
                        }
                    }
                    allGhostAuthor {
                        edges {
                            node {
                                id
                                slug
                                profile_image
                            }
                        }
                    }
                }`,
                mapping: {
                    allGhostPost: {
                        sitemap: `posts`,
                    },
                    allGhostTag: {
                        sitemap: `tags`,
                    },
                    allGhostAuthor: {
                        sitemap: `authors`,
                    },
                    allGhostPage: {
                        sitemap: `pages`,
                    },
                },
                exclude: [
                    `/dev-404-page`,
                    `/404`,
                    `/404.html`,
                    `/offline-plugin-app-shell-fallback`,
                ],
                createLinkInHead: true,
            },
        },

And the plugin in yarn.lock:

gatsby-plugin-advanced-sitemap@1.0.3:
  version "1.0.3"
  resolved "https://registry.yarnpkg.com/gatsby-plugin-advanced-sitemap/-/gatsby-plugin-advanced-sitemap-1.0.3.tgz#a4ad58684516d988be0c69780ebe66b3d8388fb2"
  dependencies:
    "@babel/runtime" "^7.0.0"
    fs-extra "^7.0.1"
    lodash "^4.17.11"
    moment "^2.24.0"
    xml "^1.0.1"

### Expected result

Site should deploy successfully to netlify without errors.

### Actual result

Deploy fails.

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.13.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.2
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.3.9 => 2.3.9 
    gatsby-awesome-pagination: 0.3.4 => 0.3.4 
    gatsby-cli: ^2.5.4 => 2.5.4 
    gatsby-image: 2.0.32 => 2.0.32 
    gatsby-plugin-advanced-sitemap: 1.0.3 => 1.0.3 
    gatsby-plugin-feed: 2.0.15 => 2.0.15 
    gatsby-plugin-force-trailing-slashes: 1.0.4 => 1.0.4 
    gatsby-plugin-manifest: 2.0.23 => 2.0.23 
    gatsby-plugin-offline: 2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: 3.0.9 => 3.0.9 
    gatsby-plugin-sharp: 2.0.27 => 2.0.27 
    gatsby-source-filesystem: 2.0.24 => 2.0.24 
    gatsby-source-ghost: 3.3.0 => 3.3.0 
    gatsby-transformer-sharp: 2.1.16 => 2.1.16 
  npmGlobalPackages:
    gatsby-cli: 2.4.13

**Comment by pieh** [comment]
Hey, this is same error as in https://github.com/gatsbyjs/gatsby/issues/13079, so I'll close this one as duplicate

**Comment by pieh** [comment]
`gatsby@2.3.10` was published with fix

**Comment by sethxd** [comment]
Thanks, this fixed it.
