### ISSUE TITLE
[docs] Document Location prop

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13083]
## Summary

After a discussion in the Maintainers Meeting this week, it was brought up that the `location` prop available on all gatsby pages is not well documented. It likely should be documented in the [routing](https://www.gatsbyjs.org/docs/routing/) section of the docs.

With this, we can reference how people can use the location prop to create conditional workflows in their gatsby pages.

**Comment by pieh** [comment]
Maybe we should have general documentation on what props Page/Template component receive?

So list them and add description:
 - `location`
 - `data` (query resutls)
 - `pageContext` (anything passed to `createPage` context)

I'm not sure of the place for it, but it seems we don't clearly document this anywhere (other than by usage in some examples)

**Comment by hassan3095** [comment]
Hi, can anyone please explain to me the details in more detail because I would love to contribute to this and I am new to this project. I do have the local project environment setup :)

**Comment by paschalidi** [comment]
@lannonbr and @pieh I would also like to get involved here if there is need for it. Please let me know !

**Comment by marcysutton** [comment]
There was a request on the gatsbyjs.org feedback widget that sounds related, this was reported on https://www.gatsbyjs.org/docs/gatsby-link/

> how to use location prop in class based component passed via <Link />

@paschalidi @hassan3095 we could definitely still use your help!

**Comment by dandv** [comment]
Good to see this documented, because the lack of documentation has led to all sorts of [overengineered](https://medium.com/@chrisfitkin/how-to-get-query-string-parameter-values-in-gatsby-f714161104f) [solutions](https://dev.to/5t3ph/how-to-use-url-query-string-parameters-in-gatsby-a71).
