### ISSUE TITLE
Change footnotes rendering from Markdown

### ISSUE THREAD

**Issue by markvital** [gatsbyjs/gatsby#13092]
I'm using footnotes in Markdown ```[^1]```, ```[^2]``` etc..

I would like to change back arrow style for each individual footnote from ↩to ^, and postition so it displays at the beginning of the line (example 2), just like on Wikipedia:
<img width="676" alt="Screen Shot 2019-04-03 at 8 23 35 PM" src="https://user-images.githubusercontent.com/742796/55503609-4d40ac80-564f-11e9-87af-6b38b6d49a05.png">
Currently gatsby-transformer-remark produces the following HTML:
```HTML
<li id="fn-1">
  <p><a href="http://hint.fm/papers/pivotgraph.pdf">Lorem ipsum dolor sit amet</a></p>
  <a href="#fnref-1" class="footnote-backref">↩</a>
</li>
```
Is there a way to change this HTML, so **.footnote-backref** is positioned in the beginning of the paragraph?

**Comment by pieh** [comment]
It seems like we are not doing this directly in gatsby code - it's hardcoded in one of dependency of remark transformer - https://github.com/syntax-tree/mdast-util-to-hast/blob/master/lib/footer.js#L27-L32

You probably can adjust this with css (pretty hacky) to hide auto generated one and prepend `^` with `:before` pseudo element. But if you would prefer nicer/cleaner solution - you could create `remark` plugin to modify markdown AST yourself before linked package handle this

**Comment by markvital** [comment]
@pieh thank you.
I've managed to position it at the end of the paragraph with CSS and will use your pseudo element solution for now.

It would be great to have footnotes setting in base Gatsby configuration.

**Comment by jamessimone** [comment]
@markvital I saw this issue a while back and got interested in creating a fix. At this point I'm fairly satisfied with the functionality.  Let me know what you think!

**Comment by stevanpopo** [comment]
Just the solution I was after. Thanks @jamessimone.

**Comment by jamessimone** [comment]
@stevanpopo no problem!

**Comment by markvital** [comment]
@jamessimone sorry, somehow I missed this message.
Thank you, the fix is very handy! It saved me a lot of time.

One thing would be great to have is to be able to change position where generated footnotes appear. Right now it can only appear at the bottom of the article and this could be very annoying if you have complex footnotes structure like wikipedia. Let me give you an example:

My footnote section has two sub-sections, like in Wikipedia, linked footnotes and further reading.  I want Further Reader to appear below Footnotes. Right now this is not possible. 
Here is a screenshot which illustrates what I am talking about:


<img width="1019" alt="Screen Shot 2019-09-09 at 6 40 18 PM" src="https://user-images.githubusercontent.com/742796/64545831-2ab76b80-d332-11e9-8b5b-d0a5b8541031.png">

**Comment by jamessimone** [comment]
@markvital excellent, thank you for the detailed explanation and response. Let me think a little bit about how to arrange the plugin options so as to best meet your use case. I will get back to you in the coming days!

**Comment by markvital** [comment]
> @markvital excellent, thank you for the detailed explanation and response. Let me think a little bit about how to arrange the plugin options so as to best meet your use case. I will get back to you in the coming days!

@jamessimone Is there any update on this?

**Comment by jamessimone** [comment]
@markvital I don't have an update for you, unfortunately. I have been bogged down by other work and the issue is larger than I had originally anticipated because of the way the AST tree is produced for markdown - each node has a column/line reference for where it should be rendered in relation to the nodes both before and after it. I was unable to gracefully figure out a way to move the footnote markdown below another section. I still have a branch open for it in my plugin, but have been bogged down with contracting work the past few months. It may be that I have time later this month to re-open this issue. I would ask that you paste the contents of your remark from September 9th in a bug on my repo so that I can continue to track this.

**Comment by markvital** [comment]
> @markvital I don't have an update for you, unfortunately. I have been bogged down by other work and the issue is larger than I had originally anticipated because of the way the AST tree is produced for markdown - each node has a column/line reference for where it should be rendered in relation to the nodes both before and after it. I was unable to gracefully figure out a way to move the footnote markdown below another section. I still have a branch open for it in my plugin, but have been bogged down with contracting work the past few months. It may be that I have time later this month to re-open this issue. I would ask that you paste the contents of your remark from September 9th in a bug on my repo so that I can continue to track this.

OK, pasted [here](https://github.com/jamessimone/gatsby-remark-footnotes/issues/4)
