### ISSUE TITLE
Polyfill issue in the development mode and prefix issue in production mode on IE10

### ISSUE THREAD

**Issue by takeakiyamasaki** [gatsbyjs/gatsby#13091]
When you run a [starter project](https://github.com/gatsbyjs/gatsby-starter-default) without any modification in the development mode, it does not polyfill for IE10, which causes the whole app not to load at all even when browserslist is correctly set in package.json.

This is how I set browserslist in package.json

```
{
  ...,
  "browserslist": [
      "last 4 versions",
      "not ie < 10"
   ],
  ...
}
```

And the following is the error I get in the IE10 console.

![Screen Shot 2019-04-03 at 2 04 30 PM](https://user-images.githubusercontent.com/47050080/55501914-75151d80-5619-11e9-9524-0c3bf5d10700.png)

After reading relevant issues, I figured this is due to the newer version of React using Set and  Map object which are not compatible with some of older browsers.

I tried adding following imports in gatsby-browser file to polyfill them (as mentioned in issue [#9348](https://github.com/gatsbyjs/gatsby/issues/9348#issuecomment-470548844) and [React documentation](https://reactjs.org/docs/javascript-environment-requirements.html)) but it did not solve the problem.

```
import 'core-js/modules/es6.set'; 
import 'core-js/modules/es6.map';
import 'raf/polyfill';
```

Also, though it builds without polyfilling issue in the production mode in IE10, it seems it is not prefixing CSS properties (e.g. flexbox).

Is this something your team is currently working on, or is there some work around to fix this issue?

**Comment by pieh** [comment]
We don't really support IE10 in development - there is bunch of technical problems (needed for Hot Module Replacement), so this isn't something we will try to fix.

The flexbox issue for sure is something to look into - do you have any site you can share to demonstrate the issue?

**Comment by wangyi7099** [comment]
I have same issue... 
After looking into the souce code at devtool.. I found polyfill code loaded hebind the `Set` is used, so the error will still show.
