### ISSUE TITLE
I don't think gatsby-plugin-lunr-search exists anymore?

### ISSUE THREAD

**Issue by interglobalmedia** [gatsbyjs/gatsby#13100]
## Relevant information

Gatsby documentation - (https://www.gatsbyjs.org/packages/gatsby-plugin-lunr-search/)

Link to repo: [https://github.com/Mrtenz/gatsby-plugin-lunr-index](url)

Please either update this page or remove it.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
Plugin library is constructed from npm registry and it still exist there - https://www.npmjs.com/package/gatsby-plugin-lunr-search

We use same field that npm site is using to show link to repository (one that is defined in `repository` field in https://unpkg.com/gatsby-plugin-lunr-search@1.0.1/package.json )
