### ISSUE TITLE
Default aliases are not used by gatsby-remark-prismjs

### ISSUE THREAD

**Issue by ojeytonwilliams** [gatsbyjs/gatsby#13119]
## Description

Prismjs language aliases like `shell` for `bash` are not being accepted.

### Steps to reproduce

I put together a [demo project](https://github.com/ojeytonwilliams/gatsby-remark-prismjs-bug).  In that project there's a markdown file with a code block

> \```shell
>   git pull origin master
> \```

which should produce a page, `/shell/`, in which the word 'git' is highlighted

### Expected result

Code blocks labelled with aliases should be highlighted

### Actual result

Those code blocks only receive the default style.  Changing the label to `bash` results in the correct highlighting.

It is possible to create aliases via options passed to the plugin, but I think the existing ones should be picked up by default.

I'm happy to put together a PR for this (I'm 90% sure I know how to solve it), but I figured I'd best put this issue up first.

### Environment

  System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 11.7.0 - ~/.nvm/versions/node/v11.7.0/bin/node
    Yarn: 1.13.0 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v11.7.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.2
  npmPackages:
    gatsby: ^2.3.11 => 2.3.11 
    gatsby-remark-prismjs: ^3.2.6 => 3.2.6 
    gatsby-source-filesystem: ^2.0.28 => 2.0.28 
    gatsby-transformer-remark: ^2.3.8 => 2.3.8 
  npmGlobalPackages:
    gatsby-cli: 2.5.4

**Comment by pieh** [comment]
Does prismjs has list of those aliases we could use to set default ones?

**Comment by ojeytonwilliams** [comment]
There's a list of all their languages on their [site](https://prismjs.com/#supported-languages) and you can find them in [components.js](https://github.com/PrismJS/prism/blob/master/components.js).  I've not been able to find anything like `{shell: "bash", py: "python"...}`, unfortunately.

**Comment by sidharthachatterjee** [comment]
Thank you for pointing this out @ojeytonwilliams 

I've added support for this in a PR linked above and will comment here once it's published!
