### ISSUE TITLE
[gatsby-plugin-google-analytics] Allow adding linker parameters

### ISSUE THREAD

**Issue by dimitrisnl** [gatsbyjs/gatsby#13117]
### Current state

The [plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/) allows setting [the following option](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/#create-only-fields)

```js
options: {
  allowLinker: true,
},
```

which translates to `ga('create', 'UA-XXXXX-Y', 'auto', {allowLinker: true});`

This means that the Gatsby application expects to check for a client ID in the URL. This is all part of having cross-domain tracking.

### Proposed feature

It would great to use the very same plugin for bi-directional cross domain tracking.

The only thing needed is to (conditionaly) add these extra lines in `gatsby-ssr`
```js
ga('require', 'linker');
ga('linker:autoLink', ['destination1.com', 'destination2.com']);
```

The links that target any of the given domains will have the client ID appended.

For more details, here's the GA documentation: https://developers.google.com/analytics/devguides/collection/analyticsjs/linker

**Comment by pieh** [comment]
I know this is not ideal, but you could put that code snippet in your `gatsby-ssr.js`:

```js
exports.onRenderBody = ({ setPostBodyComponents }) => {
  const attachCode = `
if (ga) {
  ga('require', 'linker');
  ga('linker:autoLink', ['destination1.com', 'destination2.com']);
}`

  setPostBodyComponents([<script dangerouslySetInnerHTML={{
    __html: attachCode
  }}/>])
}
```

I'm pretty weary of adding too much options in plugin that can be solved in user code

**Comment by dimitrisnl** [comment]
Makes sense @pieh , I'll happily close it.

For my case, I placed the snippet in `gatsby-browser` instead, as I wasn't sure of the order that these BodyComponents appear. Thanks for the suggestion!

**Comment by byeokim** [comment]
@dimitrisnl mind sharing your snippet?
