### ISSUE TITLE
allMarkdownRemark filter on sourceInstanceName tries to read fields of filtered-out sourceInstance

### ISSUE THREAD

**Issue by webbrewjake** [gatsbyjs/gatsby#13111]
I have two folders at the root of our src folder. One called services and one called work. I use gatsby-source-filesystem like this:

```
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'services',
        path: '${__dirname}/src/services',
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'work',
        path: '${__dirname}/src/work',
      },
    },
```

I then have this graphql query:

```
query WorkListing {
    allMarkdownRemark(filter: { fields: { sourceInstanceName: { eq: "work" } } }) {
      edges {
        node {
          frontmatter {
            image {
              childImageSharp {
                fluid(maxHeight: 600) {
                  ...GatsbyImageSharpFluid
                }
              }
            }
          }
        }
      }
    }
  }
```

As it was, both 'services' and 'work' had an image field in the frontmatter. 'work' is a relative image file, and 'services' is a string. I was at the time getting this error:

> error GraphQL Error Field "image" must not have a selection since type "String" has no subfields.

I finally figured out that it was reading them from both files (both as strings) and thus my query above would not work. When I remove the image field from the 'services' frontmatter - it works!

Can someone please let me know if this behaviour is intended, or if I'm going about this the wrong way?

**Comment by pieh** [comment]
This is how gatsby type inference and graphql type system work - we have single `MarkdownRemark` type shared for both instances - so the `frontmatter.image` field will always share the same type for both source instances (so either `File` link - that allow you to do `sharp` transformations, or "just" as string).

If you need to have different behaviours for those 2 instances, then you also need to use different frontmatter field names for those.

**Comment by webbrewjake** [comment]
Thanks for the response Pieh. So even though I apply the filter:

`filter: { fields: { sourceInstanceName: { eq: "work" } } }`

That's somewhat ignored? By somewhat, I mean that when the image field is removed or changed in the 'services' markdown it only pulls back the 'work' markdown, but with it in there it obviously still tries to retrieve it.
