### ISSUE TITLE
class/id styling not working on 0.12.36

### ISSUE THREAD

**Issue by horak** [gatsbyjs/gatsby#13124]
## Summary
Inline styles and general tag selectors (`img`, `div`, etc.) function within my `css/index.module.css`. However, adding a class tag does not work: the styles made with that selector are not applied. Very odd. I've talked to someone in discord and they haven't been able to discern what's going wrong either.

## Relevant information
I'm on an old version: 0.12.36. Very old, but stock, I haven't changed very much. 

## Breakdown
Here is what my component looks like using `className='yo2'`:
```js
          <div className='yo2' style={{
            transform: 'rotate(-90deg)',
            font: 'bold 10px Sans-Serif',
            letterSpacing: '1.7px',
            textTransform: 'uppercase',
            background: this.state.color,
            color: '#fff',
            padding: '0 5px',
            margin: '39px -54px 0px',
            lineHeight: '24px',
            float: 'left'
          }}>
            presently 
```
And here is the full component code, [in context](https://paste.ee/p/3tkct) on line 94.

And here is the relevant part of my `index.module.css`:
```css
@media (max-width: 480px) {
 button {
    width: 100% !important;
  }
  .yo2 {
    background-color: red !important;
  }
```

Now, once I `gatsby develop`, I'm seeing the following in my chrome console:
![image](https://user-images.githubusercontent.com/1111424/55567326-6ab35c00-56cb-11e9-98c1-79a919e9e11b.png).
You can see that the class `yo` is being added to that element. Yet, if you look at the media query code, nothing has been added. (It's important to add that I've also tried this outside of and within the media query selector.)

...

I've also tried using the css module approach by:
```js
import styles from '../css/page.module.css';
...
<div className={styles.yo2}>
```
But that prevents even the class name from being added to that html element!

I'm very lost.

**Comment by pieh** [comment]
I don't think I can provide much support here. This is pretty old version that I have absolutely no context on. I do think this approach should be the one to use:

```
import styles from '../css/page.module.css';
...
<div className={styles.yo2}>
```

can you try `console.logging` `styles` to see what it looks like?

Other than that I only can try to recommend updating gatsby version (as then I could recommend checking https://github.com/gatsbyjs/gatsby/tree/master/examples/using-css-modules example - but it's using gatsby v2)

**Comment by coderkind** [comment]
Experiencing similar going through a basic GatsbyJS tutorial this evening; element selectors work (styling a h1, etc) but bespoke styles aren’t attached or applied. Empty styles object when I console.log it out as well.
