### ISSUE TITLE
gatsby-plugin-cockpit returned an error: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by 8ctopotamus** [gatsbyjs/gatsby#13121]
I have set up a cockpit installation, installed `gatsby-plugin-cockpit`, created an API key, and followed the instruction on https://www.gatsbyjs.org/packages/gatsby-plugin-cockpit/ to add it to my gastby-config.js file. 

I have also created a few collections inside of cockpit.

When I run `npm run develop`, I get the following error:

```
error Plugin gatsby-plugin-cockpit returned an error
  TypeError: Cannot read property 'map' of undefined
  - extend-node-type.js:14 Object.module.exports [as setFieldsOnGraphQLNodeType]
```
How can I fix this?

**Comment by pieh** [comment]
`gatsby-plugin-cockpit` is not maintained in this repository.

Check https://github.com/mpartipilo/gatsby-source-cockpit - it seems like it's not being actively maintained :(

**Comment by 8ctopotamus** [comment]
I will try it out, thanks!

And that's unfortunate. Cockpit seems like a really cool open-source CMS solution! Are there any others you'd recommend?

**Comment by Hypothesis-github** [comment]
There is Fika plugin you can use for cockpit js but even that fails on images and gallery as far I tried. This is as you mentioned quite a pity that a great cms like cockpit cannot work properly with gatsby and graphql.
