### ISSUE TITLE
Random FAILED DOWNLOAD

### ISSUE THREAD

**Issue by Jsalvat** [gatsbyjs/gatsby#13125]
## Description

Random Failed Downloads when we're doing gatsby develop and build
### Steps to reproduce

rm -rf gatsby develop or build. Sometimes works, sometimes It didnt. Throw download Failed and we've to start again

### Expected result

It should work correctly

### Actual result

Random Failed Downloads 
### Environment

System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Safari: 12.1
  npmPackages:
    gatsby: ^2.1.18 => 2.3.7
    gatsby-background-image: ^0.2.8-beta => 0.2.8-beta
    gatsby-image: ^2.0.33 => 2.0.37
    gatsby-plugin-manifest: ^2.0.24 => 2.0.26
    gatsby-plugin-material-ui: ^1.2.4 => 1.2.4
    gatsby-plugin-offline: ^2.0.24 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.7 => 3.0.11
    gatsby-plugin-remote-images: ^1.0.1 => 1.0.1
    gatsby-plugin-sass: ^2.0.10 => 2.0.11
    gatsby-plugin-sharp: ^2.0.22 => 2.0.32
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.0.23 => 2.0.28
    gatsby-transformer-sharp: ^2.1.14 => 2.1.17
  npmGlobalPackages:
    gatsby-cli: 2.4.16

**Comment by Jsalvat** [comment]
There's some way to say gatsby that if he failed with some download ... retry again?

**Comment by Jsalvat** [comment]
bump

**Comment by wardpeet** [comment]
at the moment we don't have a solution for this. Could you let us know which one fails? Could you share some code?
