### ISSUE TITLE
Loading external script file works sometimes but not every time.

### ISSUE THREAD

**Issue by bobbymart1n** [gatsbyjs/gatsby#13136]
## Summary
So I'm trying to load an external JS file thats in my project on componentDidMount. I've tried React Helmet to only get the same result. After building the project and deploying it, the script gets inserted, but only works sometimes. I thought this might be an issue of the script loading after everything else, but I've appended the script also using the async tag which also didn't fix the problem. I'd appreciate any insight on the issue. I've seen a few other people have a similar situation, and tried their solutions without any success.

## Relevant information
Here is my componentDidMount
```
componentDidMount() {
    const homepageScripts = document.createElement("script")
    homepageScripts.id = "homepageScripts"
    homepageScripts.src = withPrefix("/scripts/homepage.js")
    homepageScripts.async = true
    document.body.appendChild(homepageScripts)
  }
```

### Environment (if relevant)

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 64.0.2
    Safari: 12.1
  npmPackages:
    gatsby: ^2.1.18 => 2.1.18 
    gatsby-image: ^2.0.30 => 2.0.30 
    gatsby-plugin-manifest: ^2.0.19 => 2.0.19 
    gatsby-plugin-offline: ^2.0.24 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.7 => 3.0.7 
    gatsby-plugin-react-svg: ^2.1.0 => 2.1.0 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-sharp: ^2.0.22 => 2.0.22 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-source-graphql: ^2.0.10 => 2.0.11 
    gatsby-transformer-sharp: ^2.1.14 => 2.1.14 
  npmGlobalPackages:
    gatsby-cli: 2.4.16

### File contents (if changed)

`gatsby-config.js`: 
```
module.exports = {
  siteMetadata: {
    title: 'Title',
    description: '',
  },
  pathPrefix: '/static',
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sass',
    {
      resolve: 'gatsby-source-graphql',
      options: {
        typeName: 'Craft',
        fieldName: 'craft',
        url: 'http://example.com', 
        headers: {
          Authorization: '',
        },
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'images',
        path: '${__dirname}/src/images',
      },
    },
    {
      resolve: 'gatsby-plugin-react-svg`',
      options: {
        rule: {
          include: /images/,
        },
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.app/offline
    // 'gatsby-plugin-offline',
  ],
}
```
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
What is your script doing? It will be evaluated just single time (first time you insert it). So after navigation it will not run more than once (we don't reload entire page on navigation)

**Comment by jonniebigodes** [comment]
@bobbymart1n see if my response [here](https://github.com/gatsbyjs/gatsby/issues/10713#issuecomment-451276923) helps you out. In a nutshell try using a [ref](https://reactjs.org/docs/refs-and-the-dom.html) instead of your approach. Feel free to provide feedback.

**Comment by bobbymart1n** [comment]
@jonniebigodes So I've implemented your solution from the link, looks like the dev before me had a similar solution to this problem, but failed to mention it. So the issue I'm having now is that, if I navigate to another page, then navigate back to the page where I'm loading the script on `componentDidMount` via the sites navigation, not using the back button, the script is appended properly, but none of the JavaScript is applied. I'm a little unsure as to why.

**Comment by jonniebigodes** [comment]
@bobbymart1n and what happens if you refresh the page? if it triggers the execution, then the issue is what  pieh said, to make the page loading more agile.

Been thinking about this and this is a really long shot and i haven't tested it out, nor i know what's inside your external js file, even if it's triggered by a function or event, but you could do something like this:

```javascript
import React, { Component } from 'react'
class xpto extends Component {
componentDidMount(){
    const script=document.createElement('script')
    script.src="your_external_script"
    script.async=true; // probably would have to remove this to prevent issues
    this.instance.appendChild(script)
    if (typeof window !== 'undefined') {
      let something= window.nameofyourstarterfunction // gets the function reference
      something() // calls the function
   }
  }
........
}
```

Reasoning behind this.

If i'm thinking correctly, the script will be added as global and with that it should let you call whatever functions you have defined in there. The "sanity" check is just for good measure, to prevent issues when building the site, as technically all of the work is done a priori in "server" side with node and you don't have access to certain apis, which in turn when you visit the endpoint, the page/component will be rehydrated back to you(client) and should trigger the execution. This is a very reduced description of how Gatsby works.

Once again, this is not tested in any shape or form, just something i came up while having a sip of coffee..... Feel free to provide some feedback

**Comment by bobbymart1n** [comment]
@jonniebigodes Alright so I've tied my load function to the window object, and its definitely being invoked when navigating back to my landing page from another page using the solution you provided. I now need to figure out why it isn't attaching certain things like event listeners once its being invoked. My assumption is that the JS is loading before the elements get rendered to the virtual DOM.

**Comment by jonniebigodes** [comment]
@bobbymart1n once again without any further knowledge of what is your external js is doing, but regarding your comment i thought of something, don't know if it will work but worth a try.
In your component where you're loading the js, make the following change to see if it will trigger the event.

```javascript
import React, { Component } from 'react'
class xpto extends Component {
componentDidMount(){
    const script=document.createElement('script')
    script.src="your_external_script"
    script.async=true; // probably would have to remove this to prevent issues
    this.instance.appendChild(script)
    if (typeof window !== 'undefined') {
      window.addEventListener('some_event', this.eventHandler)
      let something= window.nameofyourstarterfunction // gets the function reference
      something() // calls the function

   }
  }
eventHandler=()=>{
    console.log('event was triggered')
}
// removes the handler as it's no longer needed.
componentWillUnmount() {
    if (typeof window !== 'undefined') {
      window.removeEventListener('some_event', this.eventHandler)
    }
}
........
}
````

**Comment by wardpeet** [comment]
Injecting scripts is a bit tricky but best way to make sure everything in place to execute your function is probably a setTimeout

try putting this in componentDidMount
```
setTimeout(window.nameofyourstarterfunction, 100)

**Comment by bobbymart1n** [comment]
@jonniebigodes I figured it out. I had variables that were being referenced in the in the function were outside the scope of the function. I brought those variables into the function itself and all was good. Thank you all so much for the help, I really appreciate it.

**Comment by jonniebigodes** [comment]
@bobbymart1n no need to thank, glad i could help even if it was a little bit and that you got your issue solved.

**Comment by bobbymart1n** [comment]
@jonniebigodes So I'm having a separate issue now and it involves Safari. Everything works fine in Chrome and Firefox. The only thing that seems to be working through Safari is if I use a setTimeout on running the function. Heres my code.

```
const [loaded, setLoaded] = useState(false)
const scriptEl = useRef(null)
  //Only add the script when component mounts
  useEffect(() => {
    const homepageScripts = document.createElement("script")
    homepageScripts.id = "homepageScripts"
    homepageScripts.src = withPrefix("/scripts/homepage.js")
    scriptEl.current.appendChild(homepageScripts)
    setLoaded(true)
  }, [])
  useEffect(() => {
    if (typeof window !== "undefined" && loaded) {
      // Reference the function stored in the window object from index.js
      let loadWindow = window.loadWindow
      loadWindow()
    }
  }, [])
```
Any insight is much appreciated.

**Comment by bobbymart1n** [comment]
So I think I actually figured it out this time. My event listener originally looked like this
```
window.addEventListener("load", loadWindow, false)
```
I changed it to this 
```
window.addEventListener("load", loadWindow(), false)
```
And now it works every time. 

I guess I misunderstood invoking the function in addEventListener
