### ISSUE TITLE
Styled Components Delayed Loading Issue in Gatsby

### ISSUE THREAD

**Issue by laurosilvacom** [gatsbyjs/gatsby#13133]
## Description

When developing with Gatsby locally (gatsby develop), everything seems to be okay. On the other hand, when I tested the built site locally (gatsby build and gatsby serve), the CSS seems to be loaded after the content. 

This issue also occurred when I pushed my built site to Netlify. After reading documentation I noticed that I need to add the gatsby-plugin-styled-components  to my gatsby-config.js file. So I did that, and I deployed to netlify and it worked. 

But now the style components are not loading in development. The issue now lays in the development environment. The style components are not loading in the development environment. 

### Environment

```
System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU@ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.3.3 => 2.3.3
    gatsby-image: ^2.0.35 => 2.0.35
    gatsby-plugin-manifest: ^2.0.25 => 2.0.25
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.11
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7
    gatsby-remark-prismjs: ^3.2.6 => 3.2.6
    gatsby-source-filesystem: ^2.0.28 => 2.0.28
    gatsby-transformer-remark: ^2.3.8 => 2.3.8
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17

```

**Comment by pieh** [comment]
I just tried running our example ( https://github.com/gatsbyjs/gatsby/tree/master/examples/using-styled-components ) and it doesn't have delayed style loading, and style also load in development mode.

Can you share your site code so we could have look at it?

**Comment by laurosilvacom** [comment]
It seems to be running fine in production. But when running in development, components are only compiled when commenting `gatsby-plugin-styled-components`. I'm puzzled. What can I share to help reproduce the error @pieh?

https://laurosilva.com

**Comment by pieh** [comment]
Can you share github repository for it?

**Comment by laurosilvacom** [comment]
https://github.com/laurosilvacom/laurosilvacom

**Comment by laurosilvacom** [comment]
Any thoughts @pieh?

**Comment by pieh** [comment]
I think I did reproduce it with your site for now - prime example would be those tutorial cards on home page? I didn't yet figure out why

**Comment by pieh** [comment]
Hmmm, it seems you have malformatted css in your styles: https://github.com/laurosilvacom/laurosilvacom/blob/master/src/components/card.js#L15-L23

I noticed some components do have styles, but some do not. It seems like there is some weirdness with develop not handlings this (why pluing) but build handling this

**Comment by laurosilvacom** [comment]
Not only is the Card components is not loading, but also the the Section component. I also have other components in the blog post. But this seems to be an error happening on the initial page.

**Comment by pieh** [comment]
```csss
  &:hover {
    transform: scale(1.1, 1.1);
    box-shadow: 0 30px 60px rgba(0, 0, 0, 0.5);
  }
   {
    &:hover img {
      transform: translateY(-20px);
    }
  }
```
In your card you have this - this is not valid it should be 
```diff
  &:hover {
    transform: scale(1.1, 1.1);
    box-shadow: 0 30px 60px rgba(0, 0, 0, 0.5);
  }
-  {
    &:hover img {
      transform: translateY(-20px);
    }
- }
```

After that change it fixed most of the things for me

**Comment by laurosilvacom** [comment]
Wow! It was that simple. How did I not catch that? Thanks for help @pieh 😁
