### ISSUE TITLE
Docs: add more information on finding a source plugin

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#13131]
## Summary

Finding a source plugin is a key workflow in Gatsby. There are a number of docs on source plugins already (which is awesome), but one thing I noticed is the Sourcing intro doc has a list of pages and no introductory text. This would be a good place to add more information on finding a source plugin! I also found the Source Plugin Tutorial could use an edit, which makes sense to do as part of this work.

Pages to edit: 
- https://www.gatsbyjs.org/docs/content-and-data/
- https://www.gatsbyjs.org/docs/source-plugin-tutorial/ (it references and links to itself, which seems like an artifact of moving from elsewhere)

Related page:
- https://www.gatsbyjs.org/docs/headless-cms/

**Comment by andrewfairlie** [comment]
I would like to have a go at this one if you don't mind @marcysutton? I've been learning Source Plugins recently and came across the same thing so it's fresh in my mind.

**Comment by marcysutton** [comment]
That sounds great @andrewfairlie! We're going through an effort to improve key workflows, and this is one of them. The first step in this work would be to evaluate the "finding a source plugin"  workflow to identify potential improvements: there's a new meta issue with a grading rubric for you to use: https://github.com/gatsbyjs/gatsby/issues/13708 

After establishing a baseline, improvements could be made. Let me know if you want to set up a time to discuss how this would work. I'll be traveling for the next two weeks but we could figure something out.

**Comment by gillkyle** [comment]
Have you had any time to look over the meta issue (#13708) @andrewfairlie? 

There are a couple examples of evaluations linked from that issue of what it would take to make improvements to the docs for finding and explaining source plugins.

**Comment by gillkyle** [comment]
Addressed by issue: #14796 and merged changes with PR: #14846
