### ISSUE TITLE
Gatsby-image fails in build in this repo, solved when removing a specific styled component

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#13146]
If you clone this [repo](https://github.com/kuworking/theme_u_workspace) and do

1. yarn
2. yarn workspace site develop

everything works as expected, but if you

3. yarn workspace site build
4. yarn workspace site serve

you should notice that the images of the 2 posts in `localhost/9000` are not shown. If you inspect it, the `<picture>` tag is missing.

The problem is located [here](https://github.com/kuworking/theme_u_workspace/blob/master/packages/gatsby-theme-u/src/gatsby-theme-inici/components/hook-post.js#L20-L26) and [here](https://github.com/kuworking/theme_u_workspace/blob/master/packages/gatsby-theme-u/src/gatsby-theme-inici/components/hook-post.js#L55)

Somehow, gatsby doesn't like if you style `GIcon` here (which itself is styling a span). It is weird (because it seems completely unrelated). If you change [this](https://github.com/kuworking/theme_u_workspace/blob/master/packages/gatsby-theme-u/src/gatsby-theme-inici/components/hook-post.js#L20-L26)

with 

```
const Icon = ({ g_building }) => <GIcon g_building={g_building} />

const Icon2 = styled(GIcon)`
  font-size: 5em;
  display: flex;
  & svg {
    color: #c89999c9;
  }
`
```

it doesn't make any change, but if you delete `Icon2` and just add this

```
const Icon = ({ g_building }) => <GIcon g_building={g_building} />

/*
const Icon2 = styled(GIcon)`
  font-size: 5em;
  display: flex;
  & svg {
    color: #c89999c9;
  }
`
*/
```

then the build (after deleting `public` and `cache`, just in case) works as expected.

I say this is a bug but I have no idea. However, it looks like a bug to me, this shouldn't happen IMHO

**Comment by pieh** [comment]
Hey, I tried reproducing and what I got when building and serving is runtime error:
```
Uncaught Error: An error occurred. See https://github.com/styled-components/styled-components/blob/master/src/utils/errors.md#1 for more information. Additional arguments: undefined
```
Investigating why this is happening

And definitely can confirm that omitting extra styling of `GIcon` "fixes" it in production. Will investigate

**Comment by pieh** [comment]
This is very weird ... it seems like there is something weird that webpack is doing in production mode

When I add:
```diff
import { GIcon } from 'gatsby-theme-inici'
+import * as ThemeExports from 'gatsby-theme-inici'
+console.log(ThemeExports)
```

It reports empty module in production mode (but only if `GIcon` is being styled):
![Screenshot 2019-04-05 at 12 16 29](https://user-images.githubusercontent.com/419821/55621155-03fe7300-579d-11e9-9ac1-40a8a1bb9366.png)

And this is output is either `GIcon` is not being styled or if I set webpack mode to `development`:
![Screenshot 2019-04-05 at 12 15 46](https://user-images.githubusercontent.com/419821/55621200-22fd0500-579d-11e9-9260-131a2a13b9f0.png)

**Comment by kuworking** [comment]
I'm not in front of a computer now, but with yarn workspace gatsby-theme-u build it works so it may be related to gatsby themes?

**Comment by pieh** [comment]
That's possible it's related in some way - but I have no idea why it wouldn't happen when you comment out that extra styling on `GIcon`?

**Comment by kuworking** [comment]
Yes, your screenshots are the same as mine, and yes, it is weird because this is styling a `GIcon` in a page that is rendered when `gatsby-images` is not acting, or the contrary, when `gatsby-image` fails, the styling of GIcon is not occurring since `type != 'mdx'` but `== grid` (seen [here](https://github.com/kuworking/theme_u_workspace/blob/master/packages/gatsby-theme-u/src/gatsby-theme-inici/components/structure-global.js#L325)).

They are really unrelated. And the fact that this interference is not occurring when the structure is `core-child` but occurring with `core-child-child` (even though the problem is always occurring in the first child) suggests that `gatsby-themes` is involved, but maybe not.

If I'm not wrong, this is the only place where `GIcon` gets styled, so maybe there's something wrong with [GIcon](https://github.com/kuworking/theme_u_workspace/blob/master/packages/gatsby-theme-inici/src/gitems/gicon.js)? Gonna experiment a little bit here

**Comment by kuworking** [comment]
Definitively is weird, because replacing `GIcon`'s content with a simple

```
import React from 'react'
export const GIcon = props => 'hey'
```

doesn't make any difference, so it's not about `GIcon`, it's about styling an element of the core from the child, .... but, the site has several stylings like this, so what's happening? And, why is this happening when a 2nd child comes into play? Because here the 2nd child is not doing anything here, it's not participating here.

Maybe it is about having in the 2nd child 
```
    {
      resolve: `gatsby-plugin-page-creator`,
      options: {
        path: path.resolve(__dirname, `posts`),
      },
    },
```
that somehow interferes with the subfolders? I've been playing with this in all possible variations (and also with the images) but nothing has made any difference in the behaviour. I'm afraind I'm running out of ideas 🤒

**Comment by amicidellaschola** [comment]
Hi, I am struggling against this problem too. On `develop` all images show up correctly, while on `build` the `<picture>...` HTML element is not printed,  
This shoulbe the correct usual output
![image](https://user-images.githubusercontent.com/49395015/68768646-39b4e580-0623-11ea-8622-dda5baa1febe.png)
instead I get this
![image](https://user-images.githubusercontent.com/49395015/68768702-52bd9680-0623-11ea-81f6-1a8a38f81c4f.png)

I have no clue about what is causing it. I am trying to figure out what change I made could have caused it but it's hard to isolate the problem as it is quite a complex gatsby project. I am writing here in case anybody stumble upon this problem and I'll post, hopefully, the solution that will work for me

**Comment by tomhanlon** [comment]
@amicidellaschola Hi, I am encountering the same issue -- did you find a solution?

**Comment by pascaloliv** [comment]
@amicidellaschola @tomhanlon  I'm experiencing the same issue at the moment on my 404 page on when using `gatsby develop` the image is displaying properly (`<picture>` and `<noscript>` elements).

But when I'm building the app, there is no `<picture>` element.

Did you find any cause or solution?
Thx

**Comment by tomhanlon** [comment]
@pascaloliv The project I was working on was hosted on Netlify. I found once I cleared the cache and re-deployed the images rendered properly. Can you try that?
