### ISSUE TITLE
Gatsby 有没有针对视频的插件，就像Gatsby-image一样

### ISSUE THREAD

**Issue by tgy3300** [gatsbyjs/gatsby#13149]
如题，Gatsby 有没有针对网页放视频的插件，就像Gatsby-image一样，推荐一个

**Comment by LekoArts** [comment]
Hello, thank you for opening this issue!

We would really like to help you with your problem/question but we don't understand your language and therefore kindly ask you to write in the English language. Google Translate can only help a bit and in the end it would be a frustrating guessing game for both parties.

Please feel free to open a new issue (in English) and we'd be happy to help you then 💜

Thank you for using Gatsby!
