### ISSUE TITLE
[1.0] Detect when a user is trying to change something that can't be hot reloaded and tell them they need to restart the dev server to see an effect

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1315]
E.g. someone was asking me why a change to their html.js wasn't taking effect.

Once most things hot reload, you expect everything to. Which isn't sometimes possible or is harder than it's worth. But to avoid confusion, we should tell people what they need to do to see their change which generally is restarting the dev server.

Things to detect:

* Edit gatsby-config.js (other than metadata since that's already hot reloaded).
* Upgrade node_modules
* Edit html.js

Anything else?

**Comment by sebastienfi** [comment]
If we can detect these changes, perhaps we can autorestart the server ?

**Comment by KyleAMathews** [comment]
Only if we were very confident that's what the user wanted. It's pretty expensive to restart the server so it's probably safer to just tell them to do it.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
