### ISSUE TITLE
Validate starterPath url such that only valid templates are being cloned

### ISSUE THREAD

**Issue by open-source-explorer** [gatsbyjs/gatsby#13154]
## Description

`gatsby new <new-project> any_valid_github_repo_path` clones the respective repository which doesn't make any sense :thinking: 

### Steps to reproduce

Fire in `gatsby new project gatsbyjs/gatsby`

### Expected result

As in the context above we had provided the core `gatsby` repo which is not a valid starter template. There should be suitable warnings :warning: 

### Actual result

It goes ahead and clones the respective repository.

### Environment

System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (4) x64 Intel(R) Core(TM) i3-7200U CPU @ 2.50GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0
    Firefox: 66.0
  npmGlobalPackages:
    gatsby-cli: 2.5.5

**Comment by open-source-explorer** [comment]
@pieh What are your thoughts :thinking:

**Comment by pieh** [comment]
We don't know if something is valid starter until it's cloned. We could have specific checks against github repositories potentially (check package.json and examine dependencies) before cloning, but you can use any git provider (or even use your customly hosted git repos) and then we don't have a way to validate that

**Comment by open-source-explorer** [comment]
@pieh Are we gonna consider this somehow? Anyways accepting any sort of random `url` doesn't make any sense at all :confused:

**Comment by pieh** [comment]
How would you see this working?

**Comment by open-source-explorer** [comment]
I'm not sure regarding the implementation :thinking: How would you go forward with this?

**Comment by pieh** [comment]
I wouldn't really exactly because we can't reliably validate if something is starter or not, before cloning it ...
