### ISSUE TITLE
Creating Blog Site with Gatsby (USING HTML)

### ISSUE THREAD

**Issue by zsubzwary** [gatsbyjs/gatsby#13151]
## Summary
I just recently discovered this project and quite liked it!! 😇

Now my question is that I am going to be building a static blog site, How should I do it ??? 
I followed the [Starter Blog](https://github.com/gatsbyjs/gatsby-starter-blog) but I didn’t liked the idea of writing my blog content in markdown file, I want a full control over my content with HTML tags !!

How can I go about that ?

I thought of creating a simple HELLO WORLD project and then creating `.js` file for every new post that I make, how about that? _(but how am I going to handle the pagination in that case ?)_

**Comment by imrankhokhar** [comment]
I was going to ask same question but you got it first, Now lets wait for someone to respond.

**Comment by LekoArts** [comment]
> I just recently discovered this project and quite liked it!! 

Cool, glad to hear that!

> I didn’t liked the idea of writing my blog content in markdown file, I want a full control over my content with HTML tags !!

What do you mean with full control? The markdown syntax is pretty straight forward and corresponds to certain HTML tags in the end, so e.g. `#` will always be a `<h1>` tag. You can also write HTML in markdown if you want.

With MDX you can also modify the native HTML tags with your React components/customizations: https://www.gatsbyjs.org/docs/mdx/customizing-components/

IMO there really shouldn't be a need to write your blogposts in plain JS but I'm happy to hear your concerns :) MD/MDX will give you a much better authoring experience

**Comment by zsubzwary** [comment]
> there really shouldn't be a need to write your blogposts in plain JS
What if I want to inject some JS in only one blog post?? _(how is that possible with markdown?)_

**Comment by janosh** [comment]
@zsubzwary That's exactly what `mdx` is for. Take a look:
- [mdx](https://mdxjs.com) ([how to use it with Gatsby](https://mdxjs.com/getting-started/gatsby))
- [gatsby-mdx](https://gatsby-mdx.netlify.com)

**Comment by zsubzwary** [comment]
@janosh Thank you very much this MDX looks promising !!
I will look into it soon !
