### ISSUE TITLE
Validate directory name <rootPath> provided with gatsby new

### ISSUE THREAD

**Issue by jamesgeorge007** [gatsbyjs/gatsby#13153]
## Description

`rootPath` name provided with `gatsby new` should be validated inorder to keep up with npm naming conventions. 
> There is actually an npm package inorder to perform the validation => `validate-npm-package-name`

### Steps to reproduce

Fire in `gatsby new *^#`

### Expected result

A suitable warning such as that the naming is not as per convention.

### Actual result

A directory is being created `<rootPath>` named as `*^#`

### Environment
```
System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.75
    Firefox: 66.0.2
  npmGlobalPackages:
    gatsby-cli: 2.5.5
```

**Comment by jamesgeorge007** [comment]
@pieh Your thoughts :thinking:

**Comment by pieh** [comment]
It does make sense. I'm not sure if `validate-npm-package-name` is one to use - npm package names might have additional restrictions that directory names might not have. What about https://www.npmjs.com/package/is-valid-path ?
