### ISSUE TITLE
[gatsby-source-wordpress] Styling post content

### ISSUE THREAD

**Issue by kostimarko** [gatsbyjs/gatsby#13167]
How do I style post content?

I'm currently setting 
` <div dangerouslySetInnerHTML={{ __html: props.pageContext.content }}/>`

to dump my conent onto a page. However I'd like to add classes and style the specific pieces of content.

I couldn't find anything in the guidelines.

**Comment by pieh** [comment]
Hey @kostimarko!

Right now we don't have builtin methods for manipulating html content/strings (to add classnames). You can style your content using something like:

`<div className="someClassName" dangerouslySetInnerHTML={{ __html: props.pageContext.content }}/>`

and target elements with appropiate selectors - i.e.:

```css
.someClassName p {
}
```
etc

**Comment by kostimarko** [comment]
Thanks!
