### ISSUE TITLE
Live PR Code Reviews

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13172]
## Summary

Having an opportunity to have a face to face conversation to code review a PR would be a very unique thing but more an extension of the Pair Programming sessions that already exist with the Gatsby Core team. Compared to the elongated back and forth that PRs usually have in open source, the conversation can be trimmed down given things can be suggested and edited in real time.

### Basic example

Say I am creating a new page in the docs. I go write it up and then push a PR to the Gatsby repo. I then in the PR could possibly ask for a live review. Then someone like @marcysutton or someone who works frequently in the docs could hop on a zoom call with the author and do code review in a synchronous manner compared to the async review structure on GitHub.

### Motivation

Having the opportunity to have conversations directly between the Gatsby team and contributors can really push high quality changes to the codebase or docs.

This wouldn't be applicable to all PRs (i.e. Site Showcase submissions would likely not need this), but having a conversation about the changes made or the way things were constructed directly rather than through text can allow for clarity between both parties.

### Things to think about / Concerns

What is the best way to get the PR author and the reviewer in contact? Given the default Gatsby calendly link sometimes is booked for multiple weeks into the future, having someone wait a few weeks to get on a call feels too long.

Hopping into a DM on Twitter or Discord and having the reviewer give the PR author a personal calendly link can solve this, but not everyone may be on Twitter or Discord, and scheduling a time to do such inside the PR itself can be a bit privacy encroaching given someone may not want to give personal details like an email address.

**Comment by mtheoryx** [comment]
As a Gatsby consumer, and fellow developer on a team, I really think this is a great idea. I think the discussion around what "contact" platform to use could even be a separate track after the group backs the intent of live reviews.

I'm not diminishing the concerns around privacy around the actual calls, just saying, let's see if we can get some backing for the motivation, then we can figure out the tools :) Great work and ideas!

**Comment by sidharthachatterjee** [comment]
Thank you for opening this and the detailed explanation @lannonbr 

While I think this is a great idea and we'd love to support the community as much as possible in contributing to Gatsby, doing PR reviews synchronously over calls is tricky. 

As a distributed community and team, we want to encourage shared context and keep information in public as much as possible. The true value of async PR review over text is the record of decisions and the context that led to them. Doing PR reviews over a call might cause a lot of that context to be communicated over the call and not recorded here. 

> Having the opportunity to have conversations directly between the Gatsby team and contributors can really push high quality changes to the codebase or docs.

However, I understand the motivation here and we've gone ahead and created a #contributing channel on Discord (https://gatsby.dev/discord) to enable these conversations directly with the team. 

I want to point out that we understand that there are still the kind of PRs that warrant jumping on a call and walking through from time and time, and we're happy to start conversations on #contributing and hop on when required and possible. 

Hope this makes sense! Thank you again for all the great work and for starting this discussion 💜
