### ISSUE TITLE
[gatsby-cli] lib/reporter hard exits on panic

### ISSUE THREAD

**Issue by amclin** [gatsbyjs/gatsby#13179]
## Summary

When encountering an error, the Gatsby CLI reporter forces a hard-exit using `process.exit()`

This is explicitly [discouraged by NodeJS](https://nodejs.org/api/process.html#process_process_exit_code) because it prevents other asynchronous tasks from completing.

> In most situations, it is not actually necessary to call process.exit() explicitly. The Node.js process will exit on its own if there is no additional work pending in the event loop. The process.exitCode property can be set to tell the process which exit code to use when the process exits gracefully.
> ...
> The reason this is problematic is because writes to process.stdout in Node.js are sometimes asynchronous and may occur over multiple ticks of the Node.js event loop. Calling process.exit(), however, forces the process to exit before those additional writes to stdout can be performed.

### Basic example

* https://github.com/gatsbyjs/gatsby/blob/34e4add901738e2b15fd1b5875ccb76871ce57a3/packages/gatsby-cli/src/reporter/index.js#L52
* https://github.com/gatsbyjs/gatsby/blob/34e4add901738e2b15fd1b5875ccb76871ce57a3/packages/gatsby-cli/src/reporter/index.js#L59

replace with:
```
process.exitCode = 1
```

### Motivation
A real use case I'm trying to solve: I'm capturing log events in order to post to a remote monitoring service. But the most important events to capture are errors, and I cannot capture them because the entire Node process exits.

**Comment by sidharthachatterjee** [comment]
This is interesting. 

> In most situations, it is not actually necessary to call process.exit() explicitly. The Node.js process will exit on its own if there is no additional work pending in the event loop.

I've seen instances when a panic logs multiple times in an endless loop (don't remember where) so I'm not sure if `process.exitCode = 1` will suffice in situations where we would want to hard exit. 

From the linked documentation
> If it is necessary to terminate the Node.js process due to an error condition, throwing an uncaught error and allowing the process to terminate accordingly is safer than calling process.exit().

This does seem like a cleaner way to do this. @pieh thoughts in case I'm missing something here?
