### ISSUE TITLE
"The dependency "sharp" does not seem to have been built or installed correctly." (possible Node 11 issue?)

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#13177]
## Description

on a brand new gatsby project, i can't run it right without deleting node_modules and reinstalling. it complains about node version, and i happen to run node 11 - do you think that is the problem here?

### Steps to reproduce

1. `gatsby new myapp`
2. `yarn start`

### Expected result

it runs a gatsby instance

### Actual result

```
      The dependency "sharp" does not seem to have been built or installed correctly.

      - Try to reinstall packages and look for errors during installation
      - Consult "sharp" installation page at http://sharp.pixelplumbing.com/en/stable/install/
      
      If neither of the above work, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    

Error: The module '/Users/swyx/Netlify/NetlifyDevGatsbyThemeFaunaDemo/node_modules/sharp/build/Release/sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:736:18)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (/Users/swyx/Netlify/NetlifyDevGatsbyThemeFaunaDemo/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at bindings (/Users/swyx/Netlify/NetlifyDevGatsbyThemeFaunaDemo/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/swyx/Netlify/NetlifyDevGatsbyThemeFaunaDemo/node_modules/sharp/lib/constructor.js:10:34)
    at Module._compile (/Users/swyx/Netlify/NetlifyDevGatsbyThemeFaunaDemo/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (/Users/swyx/Netlify/NetlifyDevGatsbyThemeFaunaDemo/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/swyx/Netlify/NetlifyDevGatsbyThemeFaunaDemo/node_modules/sharp/lib/index.js:3:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

```

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.0.0 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.14 => 2.3.14 
    gatsby-theme-elevator-pitch: ^0.0.36 => 0.0.36 
  npmGlobalPackages:
    gatsby-cli: 2.5.4
```

**Comment by jackkoppa** [comment]
I was getting a somewhat similar issue, on my Travis CI build of Gatsby. In that I was getting the same error report about `sharp`:

```shell
success open and validate gatsby-configs — 0.015 s
success load plugins — 0.293 s
      The dependency "sharp" does not seem to have been built or installed correctly.
      - Try to reinstall packages and look for errors during installation
      - Consult "sharp" installation page at http://sharp.pixelplumbing.com/en/stable/install/
      
      If neither of the above work, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    
{ Error: Could not locate the bindings file. Tried:
 → /home/travis/build/jackkoppa/gatsby-portfolio/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/sharp.node
 → /home/travis/build/jackkoppa/gatsby-portfolio/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/Debug/sharp.node
 → /home/travis/build/jackkoppa/gatsby-portfolio/node_modules/gatsby-plugin-sharp/node_modules/sharp/build/Release/sharp.node

# etc.
```

I mention it here because that let me to #10677, **where early throwing was added if `sharp` was not properly bound for an environment**. So perhaps this issue would have existed previously for your environment, and is just being thrown now.

For those interested, in my case, it was the `yarn` version that needed changing. Travis uses yarn `1.3.2`, which is why it wasn't failing for me locally. Upgrading to the latest yarn for Travis (`v1.15.2`) resolved my CI error above (looks like that's not at all the case for this issue)

**Comment by sw-yx** [comment]
correct, my issue is local dev related, not Travis

**Comment by DSchau** [comment]
@sw-yx this seems like a good thing that it's erroring out?

It's hard to pin down what exactly happened here--did you change terminals? This error should only be thrown if the version of Node.js used in local project folder changed between install time (e.g. `gatsby new` which runs `yarn`) and run time (e.g. `cd project && yarn start`).

The error should be able to be remediated with:

```shell
rm -rf node_modules
yarn
```

but would still appreciate any more info you can provide re: how it got to that state. Not a great user experience to start with project broken--sorry about that!

**Comment by DSchau** [comment]
Also @sw-yx, re:

> on a brand new gatsby project, i can't run it right without deleting node_modules and reinstalling. it complains about node version, and i happen to run node 11 - do you think that is the problem here?

Does this happen every time? Could you check `node --version` before running the command and after? I've never seen that change before.

Re: Node 11, I use Node 11, so it shouldn't matter!

**Comment by sw-yx** [comment]
@DSchau no, no change of terminal, it happens every time i `gatsby new` and then `yarn start` right after so something is definitely up. i should probably screenshare or something. nuking node_modules does fix it, but ofc im reporting this just in case this is an experience shared by others. if i'm the only one with this then its less interesting :)

**Comment by DSchau** [comment]
I doubt you're the only one :) I'm at a conference this week--but maybe we set something up for next week?

**Comment by sw-yx** [comment]
this is helpful!!! i just realized something - when i run `nvm ls`, i get this:

```js
nvm ls
        v8.14.0
->     v10.13.0
         system
default -> 10.13.0 (-> v10.13.0)
node -> stable (-> v10.13.0) (default)
stable -> 10.13 (-> v10.13.0) (default)
iojs -> N/A (default)
lts/* -> lts/dubnium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.15.1 (-> N/A)
lts/carbon -> v8.14.0
lts/dubnium -> v10.14.1 (-> N/A)
```

which -says- i'm on node 10. i run `node -v` and get `v10.13.0`.

BUT when i run `gatsby info --clipboard` i get:

`Node: 11.0.0 - /usr/local/bin/node` (as in original issue). what the hell?!?

**Comment by DanielRuf** [comment]
Did you use `nodenv local`? Check for a `.node-version` file or similar in your project which sets the Node.js version - or some nvm config file there.

**Comment by DanielRuf** [comment]
In the project it is probably `system`. How does your `PATH` look like?

**Comment by sw-yx** [comment]
thanks for the tips!

i dont think i use `nodenv` at all, and i do not have a `.node-version` file anywhere.

my PATH:

```
 echo $PATH
/Users/swyx/.netlify/helper/bin:/Users/swyx/bin:/usr/local/bin:/Users/swyx/Library/Python/2.7/bin:/Users/swyx/ANT_HOME/bin:/Users/swyx/jython2.7.0/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/swyx/.netlify/helper/bin:/Users/swyx/bin:/Users/swyx/Library/Python/2.7/bin:/Users/swyx/ANT_HOME/bin:/Users/swyx/jython2.7.0/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin
```

i cant see anything immediately wrong - do i just have a bad PATH somewhere?

**Comment by DSchau** [comment]
Just a quick clarification question: what is "IN MY TERMINAL" vs "IN MY PROJECT?"

It sounds like your system version of Node is using nvm (as it should) but your project is using a non-nvm version? I would start with just removing the non-nvm version of Node--unless that's being used for something?

**Comment by sw-yx** [comment]
i mean like this.. i'm sorry i must be dumb or something - 
![image](https://user-images.githubusercontent.com/6764957/55835776-b9f1f600-5aea-11e9-816a-e3725c1a1368.png)

removing the non nvm version of node sounds like a good idea. i will do that. sorry this must sound so nooby and not really have to do with gatsby. ugh.

**Comment by DSchau** [comment]
> sorry this must sound so nooby and not really have to do with gatsby. ugh.

Not even a little bit! Happy to help.

Re: the underlying question. Is there an .nvmrc in the project?

Otherwise I _maybe_ know what's happening. I don't think VSCode knows about nvm, so it will use the system path (the /usr/local/bin/node executable).

Does running `nvm alias default 11` (or 10!) resolve the issue?

**Comment by sw-yx** [comment]
i did not need to get there - i [uninstalled node like you said](https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x) and now it works!

its worth noting that VSCode seesm to have a bunch of options that also override node versions for no particular reason: https://stackoverflow.com/questions/44700432/visual-studio-code-to-use-node-version-specified-by-nvm none of the solutions here worked at all. but deleting the node v11.0 worked. i should just go all-in on `nvm`. i forget, sometimes.

thank you everyone!!!!!!!!!

**Comment by atilafassina** [comment]
fyi, I had this issue after making 12 my `default`, so this fixed for me ❤️

> Does running `nvm alias default 11` (or 10!) resolve the issue?

**Comment by DanielRuf** [comment]
`npm rebuild sharp` or `npm rebuild` should work in most cases when your environemnt has changed.
