### ISSUE TITLE
gatsby develop error 

### ISSUE THREAD

**Issue by Mohammed-Alama** [gatsbyjs/gatsby#13187]
## Description

Hi everyone i have problem when i run gatsby develop in my terminal 
i have install it correctly 

### Expected result

it should run gatsby server on localhost

### Actual result

Nothing happend 
and give me that error

error UNHANDLED EXCEPTION
  Error: listen EADDRNOTAVAIL: address not available 218.93.250.18:8000

### Environment

  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.3.5 => 2.3.5 
    gatsby-image: ^2.0.37 => 2.0.37 
    gatsby-plugin-manifest: ^2.0.26 => 2.0.26 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.11 
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32 
    gatsby-source-filesystem: ^2.0.28 => 2.0.28 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.5.5

**Comment by andrewfairlie** [comment]
Hi @MohankumarAmbati 

It looks like your `gatsby develop` is trying to run on an external IP address (`218.93.250.18`) rather than your local machine. Is this something you have purposefully done, or has it just happened automatically?

You could try forcing it to use localhost (`127.0.0.1`) by running  this command

```
gatsby develop -H 127.0.0.1
```

**Comment by DSchau** [comment]
Seems like a reasonable assessment, thanks @andrewfairlie!

One additional note is that if you are passing anything custom there, you can also just remove it, e.g.

```
"scripts": {
  "develop": "gatsby develop"
}
```

and running `npm run develop` will open up a development server at `http://localhost:8000`

Going to close this as answered-- @Mohammed-Alama feel free to re-open or reply further if we can help with this or if this doesn't seem to fix the issue.

**Comment by Mohammed-Alama** [comment]
Thanks man @andrewfairlie your solution by forcing to use localhost is working well ,and it just happened automatically ,another questions how to make it run by typing `gatsby develop` instead of
`gatsby develop -H 127.0.0.1`

**Comment by DSchau** [comment]
@Mohammed-Alama what setup are you working with here? Is this running in a VM by chance?

You should be able to use `gatsby develop -H 0.0.0.0` as well, and that will make it routable from the outside world.

It's possible this could be a bug in gatsby--but can't validate that until I know more about how this is working currently in your setup!

**Comment by Mohammed-Alama** [comment]
it's working on my local machine and i have try `gatsby develop -H 0.0.0.0` and it also working will
but can't using `gatsby develop` ever
