### ISSUE TITLE
React Lottie not working with Gatsby

### ISSUE THREAD

**Issue by spences10** [gatsbyjs/gatsby#13192]
## Description

Copy example component from : https://github.com/chenqingspring/react-lottie

Pasta example component into React default starter on codesandbox: works

Open Gatsby default starter on codesandbox, pasta example component into there: doesn't work

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

React example: https://codesandbox.io/s/zrrn187393

Gatsby example: https://codesandbox.io/s/1yk8r2r2y3

### Expected result

Gatsby should render the same component as the react example.

### Actual result

It does not

### Environment

See steps to reproduce...

**Comment by andrewfairlie** [comment]
@spences10 Gatsby uses Webpack 4. Looking on the Lottie repo I found that others are reporting this bug, along with a potential workaround, for when using Webpack 4.

https://github.com/chenqingspring/react-lottie/issues/24

**Comment by DSchau** [comment]
Hi @spences10!

Thanks for reporting this--but this doesn't seem to be specific to Gatsby. If there is something we can do to better support this use-case, we'd happily take PRs or tweaks to documentation to account for this.

However--in this case, it seems like a fairly known issue with react-lottie that has some documented workarounds worth considering.

As such--going to close this out. Thanks for opening, and please let us know if we can help further!
