### ISSUE TITLE
gatsby-source-wordpress fails to build

### ISSUE THREAD

**Issue by josh-meredith** [gatsbyjs/gatsby#13195]
## Description

I'm using gatsby-source-wordpress, and whenever I try to run a fresh build it will either fail on the first run or just hang on "source and transform nodes" and never complete. If I run it again straight after, it usually completes successfully. If it does error and provide a message, it always seems to be related to images. All seems very intermittent.

I can deal with this if I'm working locally as it will eventually build, although when I try to deploy and have build scripts run, it will fail every time. This could be due to the public folder and cache having to be re-created. It's a very small site with around 20 pages, and not a huge amount of images (approximately 300). Any help would be much appreciated. This is the first project I've used Gatsby for and have been loving everything so far. Hoping I can get past this issue.

### Steps to reproduce

I've created a repo which should demonstrate the issue.

https://github.com/josh-meredith/gatsby-demo

### Expected result

Build completes successfully.

### Actual result

Build will either get stuck on "source and transform nodes" or fail and provide an error related to media files.

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.7.0 - ~/.nvm/versions/node/v11.7.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v11.7.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.3.14 => 2.3.14
    gatsby-image: ^2.0.37 => 2.0.37
    gatsby-plugin-manifest: ^2.0.17 => 2.0.26
    gatsby-plugin-offline: ^2.0.22 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.8 => 3.0.12
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32
    gatsby-plugin-styled-components: ^3.0.6 => 3.0.7
    gatsby-source-filesystem: ^2.0.28 => 2.0.28
    gatsby-source-wordpress: ^3.0.52 => 3.0.52
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17
  npmGlobalPackages:
    gatsby-cli: 2.4.17

**Comment by violy** [comment]
Seeing assets download failures on your local dev, with `gatsby-source-wordpress`, maybe my issue #13073 could help you ? — and PR #13110 — seems similar and should help you.

**Comment by josh-meredith** [comment]
Another error which I just received, again - seems to be related to images.

--------
success write out redirect data — 0.002 s
Generating image thumbnails [========----------------------] 446/1780 37.3 secs 25%
(sharp:66192): GLib-GObject-WARNING **: 11:13:27.948: gtype.c:4265: type id '0' is invalid

(sharp:66192): GLib-GObject-WARNING **: 11:13:27.949: can't peek value table for type '<invalid>' which is not currently referenced

(sharp:66192): GLib-GObject-WARNING **: 11:13:27.949: gvalue.c:184: cannot initialize GValue with type '(null)', this type has no GTypeValueTable implementation
error Command failed with signal "SIGSEGV".

**Comment by josh-meredith** [comment]
@violy after spending some more time debugging this issue and fixing up some of my code, it seems your suggested change in #13110 does actually fix my issue. Dropping the concurrent value down to 10, my site successfully builds every time. Hopefully your PR will get merged soon. Thanks 👍
