### ISSUE TITLE
Why Gatsby 2.3.11 and above started adding render-page.js and render-page.js.map to ./public

### ISSUE THREAD

**Issue by LubomirGeorgiev** [gatsbyjs/gatsby#13202]
## Summary

I noticed that after Gatsby@2.3.11 two new files get added to the ./public folder on build. The 2 new files are `render-page.js` and `render-page.js.map`.
Is there any particular reason they are added there because I think that they are not used by the application after it's been built?

I digged up a little bit and I think 1534fe52 causes this to happen.

Can these 2 new files be safely removed from ./public?

**Comment by LubomirGeorgiev** [comment]
It's going to be fixed when #13208 gets merged.

**Comment by sidharthachatterjee** [comment]
Thank you for all your work in investigating this and opening the PR @LubomirGeorgiev 

I'm sorry that I didn't see your PR before opening another one and apologies for not merging yours (we prefer async where possible). 

I'd like to mention once again how much we value your work on this and look forward to more contributions from you in the future 💪

**Comment by sidharthachatterjee** [comment]
Fixed and published in `gatsby@2.3.15`

**Comment by LubomirGeorgiev** [comment]
@sidharthachatterjee Thanks 😄
