### ISSUE TITLE
Limit number of results on dev 404 page and add search

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#13204]
It can get expensive (and useless) to render all site pages on the dev 404 page. Instead we should show a subset of pages (once past e.g. 100 pages) and add a simple search

See discussion @ https://github.com/gatsbyjs/gatsby/pull/13186#issuecomment-480569159

**Comment by me4502** [comment]
@bennetthardwick and I have discussed this issue a fair bit, as the site we are working on is at 60k pages at the moment. 

One thing we've thought of is having a tree-like structure that you can expand and contract. Eg, if you had a page structure such as /animals/cats, /animals/cats/ragdoll, /animals/dogs, /animals/birds, and then /foods/cat-food, you could expand the animals section to show cats, dogs, and birds, then expand cats to show ragdoll.

I do agree a glob based search could be very useful as well.

**Comment by KyleAMathews** [comment]
Tree structure would be fun too! Feel free to out up a PR. This is a very simple page right now and obviously broken for large sites so let's do something at least incrementally better.
