### ISSUE TITLE
Remove one of package-lock.json and yarn.lock on gatsby new 

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#13210]
Our starters currently include both `package-lock.json` and `yarn.lock` 

This typically leads to some confusion due to yarn's warning (https://github.com/gatsbyjs/gatsby/issues/4514#issuecomment-458729956)

> package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

And in worst case, inconsistencies between the two, leading to issues like https://github.com/gatsbyjs/gatsby/issues/13194

### Potential solution

It'd be nice to remove both lock files altogether but we can't because of https://github.com/gatsbyjs/gatsby/issues/10607#issuecomment-450290701

We could remove `yarn.lock` from the starter repositories and run `yarn import` if `yarn` is detected (this solves inconsistencies in the starter itself as well as inconsistencies _after_ the project is created if both files are still present like in https://github.com/gatsbyjs/gatsby/issues/13194)

What do you think @DSchau @KyleAMathews?

**Comment by sidharthachatterjee** [comment]
@JacobBlomgren Want to take a stab at this?

**Comment by sidharthachatterjee** [comment]
Just remembered that we added @renovate[bot] and it'll handle updates to both `package-lock.json` and `yarn.lock`. And we only track `package-lock.json` in git, `yarn.lock` is created via `yarn import` in CI thanks to @DSchau 

So all we really need to do is, during `gatsby new`
- Check if `yarn` is installed
- If it is, remove `package-lock.json`
- If it is not, remove `yarn.lock`

We could also prompt, but since we internally use yarn currently if it is available (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/init-starter.js#L16-L28), we should just consistently do that for now

**Comment by pieh** [comment]
> * Check if `yarn` is installed
> * If it is, remove `package-lock.json`
> * If it is not, remove `yarn.lock`

Just to clarify: the check should be "if should use yarn" ( `shouldUseYarn` function that was linked by @sidharthachatterjee in previous comment) and not direct check if `yarn` is installed.

**Comment by KyleAMathews** [comment]
The real long-term solution here is to ask people which client they use on their first `gatsby new` and then use that in the future.

**Comment by frinyvonnick** [comment]
Regarding of your discussion I made a first implementation that seems to solve this issue. I used [prompts](https://github.com/terkelg/prompts) to ask user which package manager he wants to use.

**Comment by frinyvonnick** [comment]
Should I close this ?

**Comment by lannonbr** [comment]
Yeah this has been resolved so I'll close it.

**Comment by idyWilliams** [comment]
**'npm install'** creates **package-lock.json** and **'yarn install'** generates **yarn.lock** . Normally you stick to either one of the package managers in your project instead of having both..

**Comment by suhrob008** [comment]
![image](https://github.com/gatsbyjs/gatsby/assets/118727649/60a1b28a-dbd4-487e-aa84-e3efc66773d4)

what does it say
