### ISSUE TITLE
Advanced Tutorial: Manipulating the Remark AST with gatsby-transformer-remark plugins

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13222]
## Summary

I think it would be a good reference to create a page in the docs on a tutorial on how to create a gatsby-transformer-remark plugin so you can add additional functionality / manipulate the markdown Abstract Syntax Tree (AST).

### Motivation

There are a variety of plugins that modify the AST when using remark to add embed codes or other things when using Gatsby with Remark. Having a tutorial to reference would be a good resource to show how to do this generally.

### Things to reference

- [gatsby-transformer-remark docs](https://www.gatsbyjs.org/packages/gatsby-transformer-remark/)
- [unist-util-visit](https://github.com/syntax-tree/unist-util-visit): A library to walk the AST for particular node types

**Comment by DSchau** [comment]
Excellent idea (as noted in Discord!).

We love contributions geared towards _all_ skill levels, so documentation geared towards more advanced use cases like this would be _so so_ appreciated.

Thanks for raising this!

**Comment by lannonbr** [comment]
And opened a Draft PR to begin the progress on this. Hope to get the initial draft done this week and then it can be reviewed and cleaned up before being merged and pushed to the site
