### ISSUE TITLE
[gatsby-plugin-amplitude-analytics & gatsby-plugin-offline] 

### ISSUE THREAD

**Issue by universse** [gatsbyjs/gatsby#13232]
Hi. gatsby-plugin-amplitude-analytics doesn't seem to play well with gatsby-plugin-offline. Only got a blank page on subsequent page load after service worker is installed. I had to resort to using plugin gatsby-plugin-remove-serviceworker and the site works as normal again. Do you have any suggestion or workaround for this?

**Comment by sidharthachatterjee** [comment]
Hey @universse 

Could you provide a minimal reproduction for this if possible? Honestly, I'm not familiar with `gatsby-plugin-amplitude-analytics`. 

Considering `gatsby-plugin-remove-serviceworker` fixed the issue, I'd conclude that the plugin doesn't work with service workers in general?

I noticed you opened the issue at https://github.com/ryanashcraft/gatsby-plugin-amplitude-analytics/issues/7 as well so let's track this there and close this out for now!
