### ISSUE TITLE
onCreateNode is not consistently firing from the createNode in gatsby-transformer-yaml 

### ISSUE THREAD

**Issue by vai0** [gatsbyjs/gatsby#13231]
## Description

I am importing many yml files, and want to act on the contents of that yml file in the `onCreateNode` hook in `gatsby-node.js`. Problem is nearly half the time the build is run, it does not seem to detect any of the nodes created by `gatsby-transformer-yaml`

gatsby-node.js
```
exports.onCreateNode = ({ node, actions }) => {
    // ...
    const { path } = node;
    const forms = [];

    if (path && node.internal.type === "PagesYaml") {
        console.log("PATH EXISTS");
    }

    // ...
};
```

gatsby-config.yml
```
// ...
module.exports = {
    // ...
    "gatsby-transformer-yaml",
    {
        resolve: "gatsby-source-filesystem",
        options: {
            name: "pages",
            path: `${__dirname}/src/content/pages`,
        },
    },
    //...
}
// ...
```

One of the roughly 50ish `.yml` files in /src/content/pages/
```
path: /careers/engineering/
pageTitle: lorem ipsum
metaDescription: >-
    lorem ipsum
metaKeywords: ""
```

### Expected result

On every build, the nodes created by gatsby-transformer-yaml should be available every single time in `onCreateNode`

### Actual result

Only half the time are the nodes ever available in `onCreateNode`

### Environment

```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 4.4.23 - /nix/store/9fzc7vpqqq0bsxlpm3npgi4z00q9s61z-bash-interactive-4.4-p23/bin/bash
  Binaries:
    Node: 10.15.3 - /nix/store/v2bbzr3wxasxnq9mf7sryl362ahcbsfb-bifrost-env/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /nix/store/v2bbzr3wxasxnq9mf7sryl362ahcbsfb-bifrost-env/bin/npm
  Languages:
    Python: 3.6.6 - /Users/admin/Projects/bifrost/backend/venv/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 65.0.1
    Safari: 12.0
```

**Comment by DSchau** [comment]
@vai0 could you provide a [reproduction](https://gatsby.dev/reproduction)?

This could be a caching "bug" where if the file isn't changing, onCreateNode won't be called for a clean node.

**Comment by vai0** [comment]
@DSchau  Seems like you're totally right. To clarify - I'm running `gatsby develop`. After killing, then rerunning it immediately again without changes, the nodes are never avail in `onCreateNode`. However, if I `rm -rf .cache` then rerun `gatsby develop`, those nodes then exist. And I can reproduce this over and over locally.

I'll try creating a reproduction in a sec.

I'm guessing this is an expected behavior for gatsby? Is there a "proper" way of working around this annoyance? I'm thinking to simply execute `rm -rf .cache` prior to every `gatsby develop` run

**Comment by DSchau** [comment]
@vai0 ah - so a few more questions! Generally, cache will be invalidated when one of:

- package.json
- gatsby-config.js
- gatsby-node.js

change (even by a single character). Otherwise--we assume you _want_ to keep things cached and not re-run methods like onCreateNode on nodes that have't changed.

What exactly are you trying to do in onCreateNode?

Re: "proper" sorta, yeah. I'd strongly encourage us to figure out what you're trying to do here first, but this will work, as well.

```json
{
  "scripts": {
    "predevelop": "gatsby clean"
    "develop": "gatsby develop"
  "
}
```

**Comment by vai0** [comment]
In our `onCreateNode`, we're importing a couple functions, so...
````
```

**Comment by vai0** [comment]
That makes perfect sense. In `onCreateNode`, we're running a couple functions, so...

gatsby-node.js
```
import { runValidityChecks } from "src/utils/resources";

// ...

exports.onCreateNode = {
    // ...
    const { resourcesData } = node;
    runValidityChecks(resourcesData);
    // ...
}
```

We were making changes in the `src/utils/resources` file, but not touching `gatsby-node.js`, which perfectly explains why the cache wasn't updating.

**Comment by DSchau** [comment]
@vai0 slick (or rather--not slick!). That's kinda what I thought.

I have an extremely [WIP PR](https://github.com/DSchau/gatsby/pull/9) that resolves this use case for the most part by parsing gatsby-node.js into an AST, and then tracing the imports to check if they changed too. Can totally see how this is kind of a problem point for some though, so we may want to improve our documentation re: cache invalidation!

**Comment by vai0** [comment]
@DSchau That idea sounds great :) BTW - appreciate the help and the quick responses! For now as a workaround to prevent others on our team from scratching their heads in the future, we'll prepend `gatsby clean` to `gatsby develop` in our `npm start` script.

**Comment by DSchau** [comment]
Sounds good!

Thanks for using Gatsby 💜

**Comment by suziwen** [comment]
There is one more bug, if I create new node  in onCreateNode function, just like `gatsby-transformer-remark`

``` javascript
createNode(markdownNode)
createParentChildLink({ parent: node, child: markdownNode })
```

first build is ok, but next time build  which use cache, this will not trigger the onCreateNode function, and allMarkdownRemark will always be empty;
