### ISSUE TITLE
[gatsby-source-graphql]: refetchInterval cause "error UNHANDLED EXCEPTION"

### ISSUE THREAD

**Issue by Flintlozk** [gatsbyjs/gatsby#13239]
i have set refetchInterval for 60 sec and after i got this log after 60 sec
i work prefectly before i upgrade (was 2.0.15) to latest version (2.0.17)
.
.
.
error UNHANDLED EXCEPTION
  TypeError: createContentDigest is not a function

  - gatsby-node.js:146 createSchemaNode
    [itp_ecommerce]/[gatsby-source-graphql]/gatsby-node.js:146:29

  - gatsby-node.js:121 Timeout.refetcher [as _onTimeout]
    [itp_ecommerce]/[gatsby-source-graphql]/gatsby-node.js:121:22

**Comment by DSchau** [comment]
Ah - yep.

If you're interested in making the fix, the error is [here](https://github.com/gatsbyjs/gatsby/blob/e65aca7edebbed7a595643186fca0c41653e39fd/packages/gatsby-source-graphql/src/gatsby-node.js#L112).

`createContentDigest` is not passed to the helper like it should be. So we fixed part of the error in #13214, but not the rest of it!

Thanks for opening this!

**Comment by pieh** [comment]
`gatsby-source-graphql@2.0.18` was published
