### ISSUE TITLE
[docs] Inconsistent module format in gatsby-browser & gatsby-ssr docs

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13248]
## Description

In the docs for gatsby-browser.js and gatsby-ssr.js, the last two APIs on each page, `wrapPageElement` and `wrapRootElement` are both using the ES6 module syntax in the documentation while the remainder of the page is using the older require syntax. I think sticking to one syntax across the entire page may be better and easier to comprehend.

**Comment by lannonbr** [comment]
So @pieh notified that you can use either commonjs or es6 module syntax but you have to stick with a single module syntax in these files. So it may be good to mention on these documents maybe on the top that you can use either syntax for these APIs, but for the docs it would likely best to compress down to a single module syntax so it is more unified

**Comment by KyleAMathews** [comment]
yeah, 💯 to keeping to the same format in the docs.

**Comment by wardpeet** [comment]
I'm all for same format, i'm slightly more in favor of going for es6 export, import as it's what most people know when working with react but I don't have a strong feeling. I mostly use commonjs in node and es6 in browser context 🤷‍♂️

**Comment by lannonbr** [comment]
After discussion in the maintainers meeting, we decided that for now we will switch everything to CommonJS require syntax and in the future we can switch to the ES Modules syntax if that becomes the standard way to do so later. I'll open a PR for this later today

**Comment by interglobalmedia** [comment]
I just experienced the exact same issue on one of my Gatsby projects. One is fine, and the styling in the other one just broke. I use the defaulter starter. And am on Gatbsy 2. Just happened out of the blue.

**Comment by rchrdnsh** [comment]
Can I use es module syntax instead? I didn’t even know what commonjs was before reading this issue, and it seems very odd to use two different syntaxes for the same thing, no?
