### ISSUE TITLE
Infinite recursion calls with circular nodes

### ISSUE THREAD

**Issue by xiaoxinghu** [gatsbyjs/gatsby#13259]
## Description

After upgrade to gatsby 2.3.15, causing issue xiaoxinghu/orgajs#24.
Get errors like `RangeError: Maximum call stack size exceeded` when building with plugin [gatsby-tranformer-orga](https://github.com/xiaoxinghu/orgajs)

**Comment by stefanprobst** [comment]
Thanks for reporting this issue! Could you provide a small reproduction repo -- this would be very helpful!
