### ISSUE TITLE
Gatsby client side routes with locale support

### ISSUE THREAD

**Issue by seand52** [gatsbyjs/gatsby#13266]
## Relevant information

Hi, 

My app is multilingual and I'm using a pretty standard setup with React Intl. When creating pages in Gatsby node I pass the locale to each page, which generates two different versions (one for each language). 

The app has standard Gatbsy pages and client side routes. I'm using the gatsby-plugin-create-client-paths plugin to generate client side paths.

The problem I'm facing is that I need these client routes to be aware of the locale they are in.  When I access a client side route it always shows the same language because the locale isn't sent to these client side routes as they are not created at build time. Is there a way to set a local for these routes? 

Thanks
### Environment 

  System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Safari: 12.0
  npmPackages:
    gatsby: ^2.1.27 => 2.1.27 
    gatsby-image: ^2.0.31 => 2.0.31 
    gatsby-plugin-client-side-redirect: ^0.0.2 => 0.0.2 
    gatsby-plugin-create-client-paths: ^2.0.4 => 2.0.4 
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.0.22 => 2.0.22 
    gatsby-plugin-offline: ^2.0.24 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.8 => 3.0.8 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.25 => 2.0.25 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-transformer-sharp: ^2.1.15 => 2.1.15 
  npmGlobalPackages:
    gatsby-cli: 2.5.4

**Comment by sidharthachatterjee** [comment]
> When I access a client side route it always shows the same language because the locale isn't sent to these client side routes as they are not created at build time. 

Perhaps your URL has the locale in it and you could use that?

**Comment by wardpeet** [comment]
Hi seand52!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜
