### ISSUE TITLE
Have issue with upload image on netlify CMS. It was fixed or not?

### ISSUE THREAD

**Issue by VasilHamulyak** [gatsbyjs/gatsby#13268]
## Description
![Screenshot from 2019-04-10 16-19-57](https://user-images.githubusercontent.com/30534198/55882519-58469000-5bad-11e9-9c29-a5c638a28969.png)

### Steps to reproduce

I just go to admin page and click on some entry. Image path look like '../../images.background.jpg'.

### Expected result

Image should be displayed in entry.

### Actual result

Image didn't display in entry.

### Environment

 System:
    OS: Linux 4.15 Linux Mint 19.1 (Tessa)
  Binaries:
    Node: 11.9.0
    npm: 6.5.0
  Browsers:
    Chrome: 72.0.3626.96
    Firefox: 65.0
  npmPackages:
    gatsby: ^2.0.118 => 2.0.118 
    gatsby-image: ^2.0.29 => 2.0.29 
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17 
    gatsby-plugin-netlify-cms: ^3.0.17 => 3.0.17 
    gatsby-plugin-offline: ^2.0.23 => 2.0.23 
    gatsby-plugin-postcss: ^2.0.6 => 2.0.6 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20 
    gatsby-remark-images: ^3.0.10 => 3.0.10 
    gatsby-remark-relative-images: ^0.2.2 => 0.2.2 
    gatsby-source-filesystem: ^2.0.20 => 2.0.20 
    gatsby-transformer-remark: ^2.3.4 => 2.3.4 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13 
  npmGlobalPackages:
    gatsby-cli: 2.4.9e.

**Comment by sidharthachatterjee** [comment]
@VasilHamulyak The `/admin` page is rendered entirely by https://github.com/netlify/netlify-cms

On that note, are you using a custom preview template like https://github.com/netlify-templates/gatsby-starter-netlify-cms/tree/master/src/cms/preview-templates?

**Comment by VasilHamulyak** [comment]
I don't use templates. It will help to solve this problem?

**Comment by wardpeet** [comment]
could this be a duplicate of https://github.com/gatsbyjs/gatsby/issues/13291? a new version should've been published in 3.0.18.
