### ISSUE TITLE
Keying off GATSBY_ACTIVE_ENV breaks non production env builds 

### ISSUE THREAD

**Issue by jakegibson** [gatsbyjs/gatsby#13273]
## Description

We have been utilizing GATSBY_ACTIVE_ENV for setting different staging/test environments.  PR [10565](https://github.com/gatsbyjs/gatsby/pull/10565) broke none productions builds for us due to Gatsby using it internally to determine whether to fetch data in .cache/loader.  

This was an easy fix for us as we simply use another variable for determining which environments we point our site too.  
### Steps to reproduce
[Example Repo](https://github.com/jakegibson/gatsbyActiveEnvBug)
With gatsby-plugin-offline installed. 
GATSBY_ACTIVE_ENV=staging gatsby build
gatsby serve

### Expected result
Should see rendered page

### Actual result
Can not read component-bundlename-index.js of undefined in .cache/loader.js  line 379

### Environment
gatsby >= 2.1.33

### Potential solution 
In multiple places .cache/loader splits off process.env.NODE_ENV !== `production`.  Seems like process.env.NODE_ENV !== `development` would make more sense as when we are testing in staging or test it is best practice to have a build that mirrors production.

**Comment by jakegibson** [comment]
https://github.com/gatsbyjs/gatsby/issues/10573 looks relevant

**Comment by jakegibson** [comment]
#10573

**Comment by sidharthachatterjee** [comment]
cc @DSchau

**Comment by wardpeet** [comment]
I created a PR to fix this. It's indeed a bug that got introduced

**Comment by jakegibson** [comment]
Thanks!
