### ISSUE TITLE
[gatsby-source-wordpress] `excludedRoutes` as a function

### ISSUE THREAD

**Issue by kyuumeitai** [gatsbyjs/gatsby#13270]
Hi there. I was wondering if it's possible to have `excludedRoutes` as a function, for instance, to filter certain media files from all posts with certain tag.

I have several gatsby instances with one WordPress, and every time that I build one of the gatsby projects, it includes all media files.

Thank you.

**Comment by sidharthachatterjee** [comment]
@kyuumeitai If I understand correctly, this would help in use cases where a glob isn't sufficient because some context is required on a certain route (in this case, a tag)?

> I have several gatsby instances with one WordPress

We could certainly support this but just wondering if this is a popular use case.

**Comment by kyuumeitai** [comment]
Indeed, this could help if you have several clients with one wordpress installation.

Another case would be if you need to publish a lean gatsby wordpress site with only the images that are being actually used, i.e., you have 100 photos in media but you have 3 posts with one `featured_media`, the `build` process would grab the 100 photos even if you use only 3.

**Comment by frinyvonnick** [comment]
Do you have some examples of usage for this function ?
