### ISSUE TITLE
Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by eballeste** [gatsbyjs/gatsby#13276]
## Description

Did not see this error during the whole development / qa process until the site was finally launched. Occasionally, certain sections will not load on inital page load and then subsequently load fine once the page is refreshed. I'm seeing a related ticket #6947 but that ticket was closed stating an issue with the code itself. Wondering what that issue might be? I am not hosting on netflify. 

### Steps to reproduce

Happens on initial page load.

### Expected result

Full page load.

### Actual result

Getting partial page loads:
`Refused to execute script from '<url>/component---src-pages-index-js-5728fe7c6c0828459796.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
(index):1 `

`Refused to execute script from '<url>/webpack-runtime-86c9c3e802ef670deb8e.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

`The resource <url>/static/d/173/path---index-6a9-NZuapzHg3X9TaN1iIixfv1W23E.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

### Environment

```
System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.2
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.1.18 => 2.1.19 
    gatsby-image: ^2.0.30 => 2.0.30 
    gatsby-plugin-google-tagmanager: ^2.0.9 => 2.0.9 
    gatsby-plugin-react-helmet: ^3.0.7 => 3.0.7 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-sharp: ^2.0.22 => 2.0.23 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-transformer-json: ^2.1.8 => 2.1.8 
    gatsby-transformer-sharp: ^2.1.14 => 2.1.15 
  npmGlobalPackages:
    gatsby-cli: 2.4.11
```

**Comment by sidharthachatterjee** [comment]
Hey @eballeste 

> Refused to execute script from '<url>/component---src-pages-index-js-5728fe7c6c0828459796.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled. (index):1

Based on this, I'd look at how the assets are being hosted in production. It seems that `component---src-pages-index-js-5728fe7c6c0828459796.js` is being returned with an incorrect MIME type (text/html whereas it should be application/javascript)

**Comment by eballeste** [comment]
@sidharthachatterjee thanks for responding, quick question, would you know why this seems to happen only happen to some of our users and why it would go away on page refresh?
