### ISSUE TITLE
Is it possible to put content from a GraphQL query in a SASS file?

### ISSUE THREAD

**Issue by zachfeldman** [gatsbyjs/gatsby#13275]
Just a general question here, wondering if anyone has ever done this. 

Example case is that we have different assets for a hero image for desktop and mobile. We tried using `react-media` to set the different assets within the component, but because Gatsby pre-renders everything, it's not reading the viewport and other information to render correctly on initial load, only on page return.

My thought was to maybe use media queries to set the image, but the problem is that the image URL is being pulled in from a GraphQL query. I know I could set it with inline styles, but then I can't indicate the media query (at least I don't think?) within those inline, component level styles. 

That being said, has anyone tried dropping a GraphQL query in a sass file, or am I way overthinking this?

**Comment by sidharthachatterjee** [comment]
@zachfeldman A GraphQL query in sass file won't work since we only _process_ queries passed to `useStaticQuery`, `StaticQuery` or exported from pages 

> but then I can't indicate the media query (at least I don't think?) within those inline, component level styles.

You should be able to use media queries in a styled component perhaps as documented in https://www.styled-components.com/docs/advanced#media-templates

**Comment by zachfeldman** [comment]
Thanks @sidharthachatterjee , this actually worked perfectly! I am thrilled. Have a great day and thanks so much for your help.
