### ISSUE TITLE
Image paths in nested markdown frontmatter list not correctly inferred 

### ISSUE THREAD

**Issue by sbugert** [gatsbyjs/gatsby#13272]
## Description

When using nested lists in markdown frontmatter (corresponding to arrays in arrays), path strings resolving to images are not transformed to file nodes. Instead their types remain "String".

It seems like [this](https://github.com/gatsbyjs/gatsby/issues/2687) issue is related.

### Steps to reproduce
Example frontmatter:
```
---
data:
- - src: ../images/gatsby-astronaut.png
  - src: ../images/gatsby-icon.png
- - src: ../images/gatsby-astronaut.png
  - src: ../images/gatsby-icon.png
---
```

This query fails:
```
    allMarkdownRemark {
      edges {
        node {
          frontmatter {
            data {
              src {
                absolutePath
              }
            }
          }
        }
      }
    }
  }
```

[Demo repo](https://github.com/Juliajuliah/gatsby-remark-frontmatter-issue)
The demo repo was generated via `gatsby new …`, [these](https://github.com/Juliajuliah/gatsby-remark-frontmatter-issue/commit/ea14dcbaf321d5d21d40c03fd5b6a726fa66ef77) are the only changes made.

### Expected result
All image paths should be extended to be graphql files.

### Actual result

The build fails with this error: `GraphQL Error Field "src" must not have a selection since type "String" has no subfields.`

### Environment

```
  System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.3.0 - /usr/local/bin/node
    npm: 6.1.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.3.16 => 2.3.16 
    gatsby-image: ^2.0.37 => 2.0.37 
    gatsby-plugin-manifest: ^2.0.28 => 2.0.28 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32 
    gatsby-source-filesystem: ^2.0.29 => 2.0.29 
    gatsby-transformer-remark: ^2.3.8 => 2.3.8 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.13
```

**Comment by jonniebigodes** [comment]
@sbugert going to describe what is happening and try and offer you a solution for your issue.
The issue you're having is that when Gatsby and the appropriate plugins are working in generating the contents from markdown and transforming the yaml frontmatter, if the image is not a sibling, is not in the same folder as the markdown, the node associated will be a String as the plugin as no way of knowing where the image file is actually located and it will resolve it to a String node and let you make the necessary adjustments to your queries. On the other hand if they are siblings, then it will resolve them to a File node. And you can use `childImagesharp` to apply some modifications to it.

What i sugested to another person on a completely different issue was the following:
- Mutate the frontmatter name to the following
```yaml
#image: ../../images/proj.jpg
# name changed and adjusted to prevent issues with image loading with gatsby image and transformations.
featuredImage: "proj.jpg"
````

- In `gatsby-node.js` make the following adjustment:
```javascript
return graphql(`
    {
      allMarkdownRemark {
        edges {
          node {
            frontmatter {
              author
              featuredImage #<=just want the name of the file
            }
            fields {
              slug
            }
          }
        }
      }
    }
  `).then(res => {
    if(res.errors){
      throw res.errors
    }

    const posts = res.data.allMarkdownRemark.edges;

    
    posts.forEach(({ node }) => {
      createPage({
        path: node.fields.slug,
        component: singlePostTemplate,
        context: {
          // Passing slug for template to use to get post
          slug: node.fields.slug,
          imageInfo:node.frontmatter.featuredImage
        }
      })
    })
  })
```
- in the template file it was changed to the following:

```javascript
import React from "react"
import { graphql, StaticQuery, Link } from "gatsby"
import Img from "gatsby-image"

const xpto = () => (
    <div>
      <StaticQuery
            query={xptoquery}
            render={data => {
              const { allPageInfo, allImages } = data
              return (
                <div>
                  {allPageInfo.edges.map(({ node }) => (
                    <div key={node.id}>
                      <Link to={node.fields.slug}>
                        <Img
                          fluid={allImages.edges.filter(
                            x =>
                              x.node.fluid.originalName ===
                              node.frontmatter.featuredImage
                          )}
                        />
                      </Link>
                    </div>
                  ))}
                </div>
              )
            }}
          />
    </div>
  )
  const xptoquery = graphql`
  query sidebarQuery {
    allPageInfo: allMarkdownRemark(
      sort: { fields: [frontmatter___date], order: DESC }
      limit: 3
    ) {
      edges {
        node {
          id
          frontmatter {
            title
            featuredImage
          }
          fields {
            slug
          }
        }
      }
    }
    allImages: allImageSharp {
      edges {
        node {
          fluid(maxWidth: 300) {
            originalName
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
  }
`
  export default xpto
```
 On your case you would adjust it to inject the image array into the page(only the filenames) though context,  and in your component you would map over the array of image paths provided and based on the result of the query you would filter it and return it.

Feel free to provide feedback.

**Comment by sbugert** [comment]
Thank you for your answer @jonniebigodes.

> if the image is not a sibling, is not in the same folder as the markdown, the node associated will be a String as the plugin as no way of knowing where the image file is actually located and it will resolve it to a String node and let you make the necessary adjustments to your queries. On the other hand if they are siblings, then it will resolve them to a File node. And you can use childImagesharp to apply some modifications to it.

I'm not sure if this is true because in the repo I linked I have [this markdown file](https://github.com/Juliajuliah/gatsby-remark-frontmatter-issue/blob/master/src/pages/content.md):

```
---
one:
  items:
    - src: ../images/gatsby-astronaut.png
    - src: ../images/gatsby-icon.png
two:
- - src: ../images/gatsby-astronaut.png
  - src: ../images/gatsby-icon.png
- - src: ../images/gatsby-astronaut.png
  - src: ../images/gatsby-icon.png
---

```

and in [pages/index.js](https://github.com/Juliajuliah/gatsby-remark-frontmatter-issue/blob/master/src/pages/index.js) this query:
```
  query IndexQuery {
    allMarkdownRemark {
      edges {
        node {
          frontmatter {
            one {
              items {
                src {
                  absolutePath
                }
              }
            }
            two {
              src {
                absolutePath
              }
            }
          }
        }
      }
    }
  }
```

which only fails for the second item. The images in the first part of the frontmatter get resolved as expected.

I understand your workaround, but in my case it would add a lot of complexity because the markdown files are generated and I cannot change the image locations . I would have to traverse all of the frontmatter to find the paths and add them to another level.

If this is unexpected behaviror/a bug I would be happy to contribute and try to fix it if given some general directions, .

**Comment by jonniebigodes** [comment]
@sbugert my comment is based from experience dealing with similar issues in here. if you open `http://localhost:8000/___graphql` and check the documentation, you'll see what i mean in my comment. And with that i'll leave to the capable hands of @stefanprobst for a solution

**Comment by stefanprobst** [comment]
@sbugert Thanks for the report and the repo! This is (very probably) a known issue ([we don't handle linking array of arrays](https://github.com/gatsbyjs/gatsby/blob/8caa1f26d99150b1624c7104f5f969436e1c6dd1/packages/gatsby/src/schema/resolvers.js#L111)), I'll hopefully have a fix soon(TM).

**Comment by stevanpopo** [comment]
Hey @jonniebigodes (or anyone else) - I have a similar issue and would love some help. 

## Code
My frontmatter
```
---
title: "How To Choose The Right Coding Bootcamp"
featuredImage: ./codebootcamps.jpg
---
```
Note - This frontmatter exists in a an index.md file which is a sibling to the image.
post_folder
--> index.md
--> codebootcamps.jpg

My query
```
export const pageQuery = graphql`
  query BlogPostBySlug($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      id
      excerpt(pruneLength: 160)
      html
      frontmatter {
        date(formatString: "MMMM DD, YYYY")
        title
        featuredImage {
          childImageSharp {
            sizes(maxWidth: 630) {
              ...GatsbyImageSharpSizes
            }
          }
        }
      }
    }
  }
`
```

## Expected result
All image paths to be available in blog post on render.

## Actual result
The build fails with this error: GraphQL Error Field "featuredImage" must not have a selection since type "String" has no subfields.

This result is confirmed when I view in GraphiQL.

## Additional
I have both `gatsby-transformer-sharp` and `gatsby-plugin-sharp` installed.
```
{
  "name": "codewithbootcamps.com",
  "private": true,
  "description": "A website to find and compare best coding bootcamps.",
  "version": "0.1.0",
  "author": "Stevan Popovic <stevanpopovic5@gmail.com>",
  "dependencies": {
    "gatsby": "^2.13.50",
    "gatsby-image": "^2.2.8",
    "gatsby-plugin-feed": "^2.3.6",
    "gatsby-plugin-force-trailing-slashes": "^1.0.4",
    "gatsby-plugin-google-analytics": "^2.1.6",
    "gatsby-plugin-manifest": "^2.2.4",
    "gatsby-plugin-offline": "^2.2.4",
    "gatsby-plugin-react-helmet": "^3.1.3",
    "gatsby-plugin-sass": "^2.1.15",
    "gatsby-plugin-sharp": "^2.2.9",
    "gatsby-plugin-sitemap": "^2.2.16",
    "gatsby-plugin-twitter": "^2.1.9",
    "gatsby-plugin-typography": "^2.3.2",
    "gatsby-remark-copy-linked-files": "^2.1.4",
    "gatsby-remark-images": "^3.1.7",
    "gatsby-remark-prismjs": "^3.3.4",
    "gatsby-remark-responsive-iframe": "^2.2.4",
    "gatsby-remark-smartypants": "^2.1.2",
    "gatsby-source-filesystem": "^2.1.8",
    "gatsby-transformer-remark": "^2.6.10",
    "gatsby-transformer-sharp": "^2.2.5",
    "node-sass": "^4.12.0",
    "prismjs": "^1.17.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1",
    "react-icons": "^3.7.0",
    "react-typography": "^0.16.19",
    "typeface-merriweather": "0.0.72",
    "typeface-montserrat": "0.0.75",
    "typography": "^0.16.19",
    "typography-theme-wordpress-2016": "^0.16.19"
  },
  "devDependencies": {
    "prettier": "^1.18.2"
  },
  "homepage": "https://github.com/gatsbyjs/gatsby-starter-blog#readme",
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gatsbyjs/gatsby-starter-blog.git"
  },
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write src/**/*.{js,jsx}",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\""
  }
}

```
