### ISSUE TITLE
Rollback DANGEROUSLY_DISABLE_OOM when V8.serialize is merged

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#13284]
## Summary
A quick fix to enable gatsby users to disable redux state caching was introduced by #13066 as it caused out of memory issues for large websites. #10732 fixes this issue correctly by moving away from `json-stringify` into `v8.serialize`.

#10732 still keeps the redux state on disk which gives us the same speed benefits as we had before. With the temporary fix, we didn't have any cache which means our site takes more time to load.

**Comment by lannonbr** [comment]
As the `v8.serialize` PR was merged, I believe this can be tackled now

**Comment by abhijithvijayan** [comment]
@wardpeet @lannonbr  I can take a shot at this. All I have to do is rollback https://github.com/gatsbyjs/gatsby/pull/13066/files right?
