### ISSUE TITLE
[gatsby] createParentChildLink fails to create children nodes in createPages

### ISSUE THREAD

**Issue by Ehesp** [gatsbyjs/gatsby#13285]
## Description

In version 2.1.18 of gatsby, I'm able to successfully create a parent/child link from within the `createPages` node API. When the link is made, I'm able to query the child nodes with their data.

Upgrading to the latest Gatsby version (2.3.16),. this functionality breaks. I'm only able to query `children`, which returns an array of Node IDs.

### Steps to reproduce

https://github.com/Ehesp/gatsby-bug

In the ` gatsby-node` file I create 3 custom nodes to replicate my own setup. 1 parent and 2 children.

If I link the children to the parent within `sourceNodes` I'm able to then query the children like so (commented the code out on line 48):

```
{
  allDocumentationPage {
    edges {
      node {
        childrenDocumentationPage {
          name
        }
      }
    }
  }
}
```

In my actual project, I only know whether the nodes have a parent/child once they've been sourced. So I then create the link within my `createPages` function, as exampled in the repro, on line 78.

Now when I do the query above, I get the error: Cannot query field "childrenDocumentationPage" on type "DocumentationPage".

### Expected result

^^

### Actual result

^^

### Environment

System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
  Binaries:
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/Elliot/.windows-build-tools/python27/python
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.3.16 => 2.3.16
    gatsby-image: ^2.0.37 => 2.0.37
    gatsby-plugin-manifest: ^2.0.28 => 2.0.28
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32
    gatsby-source-filesystem: ^2.0.29 => 2.0.29
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17

**Comment by pieh** [comment]
This is unfortunate bug / side effect of schema refactor that schema is updating only `SitePage` and nothing else. As a workaround you should be able to change your query to:

```
{
  allDocumentationPage {
    edges {
      node {
        children {
          ... on DocumentaionPage {
            name
          }
        }
      }
    }
  }
}
```
at least for temporary workaround. We will look into this and see if we can figure out nice way of fixing this without adding performance regression
