### ISSUE TITLE
Static folder documentation isn't correct

### ISSUE THREAD

**Issue by maxlapides** [gatsbyjs/gatsby#13297]
Following the instructions on this page https://www.gatsbyjs.org/docs/static-folder/:
1. I added a file named logo.png to `/static`
2. I added `pathPrefix: '/img'` to `gatsby-config.js`
3. I put `<img src={withPrefix('/img/logo.png')} alt="Logo" />` in a component

It did not work.

This does work:
1. I added a file named logo.png to `/static`
2. I put `<img src='/logo.png' alt="Logo" />` in a component

That worked fine.

I'm probably misunderstanding something here.

**Comment by marcysutton** [comment]
Thanks for reporting! There's a [draft PR](https://github.com/gatsbyjs/gatsby/pull/13170) open for that doc, I can take a look...or if you feel like opening a PR that would be welcome!
