### ISSUE TITLE
[gatsby-plugin-netlify-cms]: Localhost only works with default "/admin" URL

### ISSUE THREAD

**Issue by petrpacas** [gatsbyjs/gatsby#13291]
## Description

https://github.com/gatsbyjs/gatsby/pull/12474 solved an issue with NetlifyCMS not running on `localhost`, but unfortunately it only lets you use `/admin` URL to access the admin-page.

Hard-coded stuff here:
https://github.com/gatsbyjs/gatsby/pull/12474/files#diff-4d1c9d2c489d6b95920275f753551be8

[The plugin itself has `publicPath` variable](https://www.npmjs.com/package/gatsby-plugin-netlify-cms#publicpath) that lets you set the URL to be different than `/admin`. The fix mentioned above doesn't play nice with this feature.

### Expected result

`gatsby-plugin-netlify-cms` should let you access the admin-page on whatever address specified in the `publicPath` variable.

### Actual result

The admin-page address is hard-coded to `/admin`, so anybody wanting to use any other address is out of luck.

**Comment by pieh** [comment]
You are totally right, would you be interested in applying necessary fixes?

**Comment by petrpacas** [comment]
I tried to give it a shot, but I'm not a NodeJS programmer myself unfortunately...

**Comment by petrpacas** [comment]
I struggled with pulling the `publicPath` option in a reasonable manner, and after much fiddling it turned out I could do it the same way it's done elsewhere in the file (as a second destructured argument)
