### ISSUE TITLE
Trying to embed the code from Disqus into my blog site

### ISSUE THREAD

**Issue by Oppenheimer1** [gatsbyjs/gatsby#133]
I was trying to embed the comment code from Disqus into my blog site, the code below and tried embedding it in multiple ways locally in wrappers/md.js but I haven't been able to get it to work. Any help would be much appreciated.

var React = require('react');
var ReactDisqusThread = require('react-disqus-thread');

var App = createClass({

    handleNewComment: function(comment) {
        console.log(comment.text);
    }

    render: function () {
        return (
            <ReactDisqusThread
                shortname="example"
                identifier="something-unique-12345"
                title="Example Thread"
                url="http://localhost:8000/first-post/"
                category_id="123456"
                onNewComment={this.handleNewComment}/>
        );
    }
});

React.render(<App/>, document.getElementById('container'));

**Comment by KyleAMathews** [comment]
See how I do it on my blog here: https://github.com/KyleAMathews/blog/blob/master/wrappers/md.cjsx#L51-L54

You shouldn't be calling React.render in a wrapper. Gatsby handles that for you. Just export a component.

**Comment by KyleAMathews** [comment]
Let me know if you need any more help.

**Comment by dougajmcdonald** [comment]
I did this and it blew up setting `url` for some reason, removing that worked ok

**Comment by hexrcs** [comment]
@dougajmcdonald Mine blew up as well with custom `url` or `identifier` - it turned out that I was using the `location` prop as a string! Changing `this.props.location` to `this.props.location.pathname` fixed the problem.
