### ISSUE TITLE
Setting up gatsby-plugin-layout / redux / connected layout / material ui in a clean way. Max call stack error

### ISSUE THREAD

**Issue by adberard** [gatsbyjs/gatsby#13307]
## Description

I am trying to migrate a site to gatsby but so far the experience have been very painfull and Im kinda stuck so close to the end.
Here is the setup
typecript
material ui
gatsby-plugin-material-ui (as material ui need special ssr care)
gatsby-plugin-layout (I dont want to the layout to rerender each time I change route)
redux (to connect the layout)

So what is not working:
- the routes when I move to one page to another in develop mode, do it a bit with the drawer and term of use and it will break into a Maximum call stack size.
I think the break come from the fact that there is some spagetti wrapper thing going on between Layouts, Redux Provider and Material ui theme providers.
I use a wrapWithReducer function in gatsby-browser and gatsby-ssr but because my layout is connected I need to wrap another provider around it. It seem suboptimal. Also when I check the nodes rendered there seem to have too much of wrappers.

- eslint trigger twice and is SUPER slow and it seems that its eating a lot of cpu with develop

- It seem to have been solved but using helmet used to break hot reloading with Maximum call stack size 

- When I load the page with hash /#item3 it doesnt go to the id. It only work when I come from another page or when the page is already loaded

- Im not sure the ways I handle ssr things are correct

### Steps to reproduce
Here I did set up a minimal buggued project that im willing to use as basis.
`git clone https://github.com/adberard/gatsby-boilerplate`

### Expected result

Working fine both in prod and develop mode

### Environment

  System:
    OS: Linux 4.14 Manjaro Linux undefined
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.13.0 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.config/yarn/global/node_modules/.bin/npm
  Languages:
    Python: 3.7.2 - /usr/bin/python
  Browsers:
    Firefox: 66.0.1
    Chrome
  npmPackages:
    gatsby: ^2.3.16 => 2.3.19 
    gatsby-plugin-alias-imports: 1.0.5 => 1.0.5 
    gatsby-plugin-eslint: 2.0.4 => 2.0.4 
    gatsby-plugin-layout: ^1.0.14 => 1.0.14 
    gatsby-plugin-manifest: 2.0.28 => 2.0.28 
    gatsby-plugin-material-ui: ^1.2.4 => 1.2.4 
    gatsby-plugin-offline: 2.0.25 => 2.0.25 
    gatsby-plugin-prefetch-google-fonts: ^1.4.2 => 1.4.2 
    gatsby-plugin-react-helmet: 3.0.12 => 3.0.12 
    gatsby-plugin-root-import: 2.0.5 => 2.0.5 
    gatsby-plugin-styled-components: 3.0.7 => 3.0.7 
    gatsby-plugin-typescript: 2.0.12 => 2.0.12 
    gatsby-plugin-typescript-checker: 1.0.3 => 1.0.3 
    gatsby-react-router-scroll: ^2.0.7 => 2.0.7 
    gatsby-source-graphql: 2.0.17 => 2.0.17

**Comment by DSchau** [comment]
> It seem to have been solved but using helmet used to break hot reloading with Maximum call stack size

This seems like [these instructions](https://www.gatsbyjs.org/packages/gatsby-plugin-react-helmet/#compatibility-with-react-168-useeffect-hook) will help you here.

In the other areas you identified, there's a lot to unwind. Could you provide specific files/info on each problem area you identified above?

Generally, we recommend providing a [simplified reproduction](https://gatsby.dev/reproduction) for _each_ case here, as it's fairly challenging to dive into an app and identify issues and these don't necessarily seem like Gatsby issues but rather application-level issues.

**Comment by adberard** [comment]
Thank you that was exactly my problem as I just integrated react hooks ! 
I indeed only provided one simplified version of the app instead of each case. I really needed to make all this work together and most of my bugs happen when im in the process or connecting simples working cases.

**Comment by wardpeet** [comment]
Thanks so much for opening this issue! It seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪

**Comment by daledesilva** [comment]
@adelin-b , I have the same issue as you here:

> When I load the page with hash /#item3 it doesnt go to the id. It only work when I come from another page or when the page is already loaded

Did you find out what was causing it?
I don't have any programmatically created pages, but I I am using a layout component with react-plugin-layout.
The layout component works fine and the page reloading works fine locally, but when deployed to amazon reloading a page and going directly to a URL reroutes back to the landing page.
