### ISSUE TITLE
Warning: The GraphQL query in the non-page component will not be run

### ISSUE THREAD

**Issue by kalms** [gatsbyjs/gatsby#13303]
## Description

Running both `gatsby build` and `gatsby develop` causes the following message to appear during build phase:

> warning The GraphQL query in the non-page component "/Users/user/Development/repo/src/templates/overrides/page--pagename.js" will not be run.

It's a page and not a component. I'm quite stumped and have been debugging for hours, even diving into the gatsby itself — but I'm none the wiser.

**Some info:**

We're using a forked version of `gatsby-source-ghost` with added image and static file downloads, enabling us to use `gatsby-transformer-sharp` and `gatsby-images`.

You can find that here: [https://github.com/kalms/gatsby-source-ghost](https://github.com/kalms/gatsby-source-ghost) (Branch: `feature/gatsby-image-support`)

The build script for pages and the offending templates can be found in this repo: [https://github.com/kalms/gatsby-issue-temp](https://github.com/kalms/gatsby-issue-temp)

### Steps to reproduce

Run `gatsby build` OR `gatsby develop`.

It's a little intermittent but mostly a stable error on one or two specific templates and pages from Ghost. It's preventing the pages to be published to our Netlify instance.

### Expected result

/<pagename> being viewable and GraphQL query being executed.

### Actual result

GraphQL query warning is logged

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 57.0.1
    Safari: 12.0.3
  npmGlobalPackages:
    gatsby-cli: 2.5.6

**Comment by pieh** [comment]
This error should have not much to do with your source plugin. What it usually means that if there is page query in component that wasn't use as template for any page:

There are 2 scenarios here to consider:
 - there is truly no pages that use that template
 - there are some pages, but they were created after `createPages` call was completed - this can happen if you have async code and don't return promises properly.

What version of gatsby are you using in your site?

**Comment by kalms** [comment]
`"gatsby": "2.3.17"`

Pretty sure everything is as it should be if you see the source files in here: [https://github.com/kalms/gatsby-issue-temp](https://github.com/kalms/gatsby-issue-temp)

**Comment by kalms** [comment]
A little additional information: If we change something in say the context, like:

`                return createPage({
                    path: node.url,
                    component: templateHook(`page`, node.slug),
                    context: {
                        // Data passed to context is available
                        // in page queries as GraphQL variables.
                        slug: node.slug,
                        title: node.title,
                    },
                })`

... it works on first run and then fails subsequent builds.

If we save after the first build has run (with `gatsby develop`) it works. So it's luckily not preventing us from developing it, but it's preventing us from deploying it.

**Comment by kalms** [comment]
Found the issue and it was in `gatsby-source-ghost`. The `Array.map()` was used incorrectly and added as two arrays instead of one.

*Before:*
```
    return await Promise.all([fetchPosts, fetchPages, fetchTags, fetchAuthors, fetchSettings])
        .then(async () => {
            await Promise.all(
                posts.map(async (post) => {
                    if (post.feature_image) {
                        post.image = await downloadImageAndCreateFileNode(post, { createNode, createNodeId, store, cache });
            
                        post.localFile___NODE = post.image.id;
                    }
            
                    return createNode(PostNode(post));
                }),
                pages.map(async (page) => {
                    if (page.feature_image) {
                        page.image = await downloadImageAndCreateFileNode(page, { createNode, createNodeId, store, cache });

                        page.localFile___NODE = page.image.id;
                    }
            
                    return createNode(PageNode(page));
                })
            );
        });
```

*After:*
 ```
   return await Promise.all([fetchPosts, fetchPages, fetchTags, fetchAuthors, fetchSettings])
        .then(async () => {
            await Promise.all([
                ...posts.map(async (post) => {
                    if (post.feature_image) {
                        post.image = await downloadImageAndCreateFileNode(post, { createNode, createNodeId, store, cache });
            
                        post.localFile___NODE = post.image.id;
                    }
            
                    return createNode(PostNode(post));
                }),
                ...pages.map(async (page) => {
                    if (page.feature_image) {
                        page.image = await downloadImageAndCreateFileNode(page, { createNode, createNodeId, store, cache });

                        page.localFile___NODE = page.image.id;
                    }
            
                    return createNode(PageNode(page));
                })
            ])
        });
```

Keeping the issue here if it should help anyone else. Also, our version of `gatsby-source-ghost` might be beneficial for others :-)

**Comment by trkohler** [comment]
@kalms how to start using your version of `gatsby-source-ghost` ?
