### ISSUE TITLE
Add screenshots to Ritual blog post

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#13306]
The Ritual blog post we published recently is a great case study -- does someone want to add screenshots to make it even more alive?

https://www.gatsbyjs.org/blog/2019-04-05-health-brand-chooses-gatsby-to-level-up-its-modern-stack/

Two screenshots are fine: one of the homepage, and one of a product page. Their site is ritual.com.

https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2019-04-05-health-brand-chooses-gatsby-to-level-up-its-modern-stack/index.md

**Comment by HarisSpahija** [comment]
I would like to solve this issue
