### ISSUE TITLE
we shall clean the commented out code

### ISSUE THREAD

**Issue by prashant-andani** [gatsbyjs/gatsby#13312]
Hey Folks !!!
I see that some of the code blocks are **commented out**, in the CSS, JS, HTML.

were they mean't to be kept? IMHO We must clean them up, to clear out that they are not required. And avoid **accidentally uncommenting** them and get it applied. 

Let me know your opinions....

**Comment by DSchau** [comment]
@prashant-andani not really sure what you're referring to--could you provide an example of the commented code? Do you mean in the default starter?

**Comment by prashant-andani** [comment]
@DSchau The code has been commented mostly in the `www` folder
some of them are 
i.e `www/src/components/sidebar/accordion.js`, `evalution-table.js`

**Comment by polarathene** [comment]
Ok, not comments for related code, but actual parts of code that aren't in use but have been kept as **commented out**.

[accordion.js#L128](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/sidebar/accordion.js#L128), `git blame` to [spring clean ep 5 PR](https://github.com/gatsbyjs/gatsby/pull/12603)
[evaluation-table.js#L28](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/evaluation-table.js#L28), `git blame` to [spring clean ep 2 PR](https://github.com/gatsbyjs/gatsby/pull/12464)

I imagine any of the other ones you've seen also have a good chance of `git blame` pointing to related PRs. 

Perhaps @fk can clarify what's going on there and if they're safe to remove or kept around for a reason like that intentionally :)

**Comment by wardpeet** [comment]
feel free to cleanup, it's just how @fk works ;)

**Comment by fk** [comment]
👋 Yep, I'm a total mess! :D

@prashant-andani + @polarathene I once learned that no dead code — commented or not — should be commited in any case. Irt the sidebar accordions it somewhat made sense because that was kind of a moving target, but in general we (and esp. I 😬) should stick to the rule I just mentioned.
So as @wardpeet already said — feel free to clean up, any help is appreciated! Happy to review any PRs doing so, please just ping me! 🙏

**Comment by prashant-andani** [comment]
> Ok, not comments for related code, but actual parts of code that aren't in use but have been kept as **commented out** code.
> 
> [accordion.js#L128](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/sidebar/accordion.js#L128), `git blame` to [spring clean ep 5 PR](https://github.com/gatsbyjs/gatsby/pull/12603)
> [evaluation-table.js#L28](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/evaluation-table.js#L28), `git blame` to [spring clean ep 2 PR](https://github.com/gatsbyjs/gatsby/pull/12464)
> 
> I imagine any of the other ones you've seen also have a good chance of `git blame` pointing to related PRs.
> 
> Perhaps @fk can clarify what's going on there and if they're safe to remove or kept around for a reason like that intentionally :)

Thanks for correcting me out there .... "Commented out code" not "Commented Code"

**Comment by prashant-andani** [comment]
Cleaned up the commented out code... Hence closing this issue..
