### ISSUE TITLE
How do Gatsby pages call style classes of CSS files in className

### ISSUE THREAD

**Issue by tgy3300** [gatsbyjs/gatsby#13313]
For example

**Comment by DSchau** [comment]
@tgy3300 I'm not exactly sure what you mean here.

Could you provide an example snippet that you find confusing and then one of us could explain how it's working?

Thank you!

**Comment by tgy3300** [comment]
The style.css file code is as follows
`.aa{
background:#ff0000
}`

How to call in the page file index.js
The index.js code is as follows
`
import React from "react"
import Layout from "../components/layout"
import SEO from "../components/seo"
import style from "./style.css"

const IndexPage = () => (
  <Layout>
    <SEO title="Page" />
    <p className={style.aa}>Welcome to page</p>
  </Layout>
)

export default IndexPage
`

I tried to call <p className={style.aa}>Welcome to page</p> in the index.js file, it didn't take effect, but an error occurred.

**Comment by DSchau** [comment]
@tgy3300 you're looking for CSS Modules.

Rename `style.css` -> `style.module.css`

Change the import from `import style from './style.css'` to `import style from './style.module.css'` and you should be good to go.

Closing as answered, but please re-open if we can help further.
