### ISSUE TITLE
[docs] Update "Writing documentation with Docz" to use gatsby-theme-docz

### ISSUE THREAD

**Issue by LekoArts** [gatsbyjs/gatsby#13315]
# Summary

Replace the current instructions on [Writing documentation with Docz](https://www.gatsbyjs.org/docs/writing-documentation-with-docz/) with instructions on how to use `gatsby-theme-docz`

## Motivation

The page [Writing documentation with Docz](https://www.gatsbyjs.org/docs/writing-documentation-with-docz/) is quite complex and the overall setup is complicated. Moreover some of the dependencies are outdated. However, this was more or less the only way to get Docz working with Gatsby _in the past_.

Docz recently published its own Gatsby theme [`gatsby-theme-docz`][docz-doc]

## What needs to be done

- Keep the general introduction but remove the paragraph about the starter as it's not the recommended way of doing things anymore ("If you’re starting your Gatsby project from scratch and would like to have great [...]")
- Keep the setup of a new gatsby site
- Follow the "How to use" instructions
- Follow the "Configuration" instructions and maybe expand on them a bit
- Keep the "Writing documentation" part (but update it if necessary)
- Keep the "Other resources" part but also link to [`gatsby-theme-docz`][docz-doc]

### Further information

You can read our [Contributing Guide](https://www.gatsbyjs.org/contributing/) to learn how to tackle this issue.

[docz-doc]: https://www.docz.site/docs/gatsby-theme

**Comment by polishedwp** [comment]
@LekoArts I am relatively new to GatsbyJS and am not familiar with Docz, but can help put together a beginning draft to help out if you need me to work on this.

**Comment by LekoArts** [comment]
Hey,

thank you for taking the time to read this issue and volunteering to tackle this one! Sadly this issue requires at least intermediate level of context/knowledge (both Gatsby and Docz) -- hence I didn't mark this as a "good first issue".

Speaking of that: We absolutely want to have you as a contributor, so please take a look at [our open issues][open-issues] for ideas, especially at those marked with "good first issue". If you have questions feel free to ask them in the respective issue. Thanks!

[open-issues]: https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22

**Comment by polishedwp** [comment]
@LekoArts Thank, I generally and reading the "good first issues" daily. I currently have one issue open #12519 
Love the community.
