### ISSUE TITLE
Update blog post to include the correct link for Gatsby source plug-ins page 

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/gatsby#13325]
The "Integrating and Partnering with Gatsby (for Vendors" blog post lists the incorrect link for creating a source plugin.

This is the blog post link: https://www.gatsbyjs.org/docs/gatsby-vendor-partnership/#step-four-integrating-with-gatsby-preview-and-co-selling

* We need to update the `developer documentation` link in this section:

<img width="671" alt="Screenshot 2019-04-12 12 23 00" src="https://user-images.githubusercontent.com/13393126/56061283-dde94d80-5d1d-11e9-8cf8-f45037f83b9a.png">

Here is the correct link: https://www.gatsbyjs.org/docs/creating-a-source-plugin/

**Comment by DSchau** [comment]
If anyone wants to implement this (would very much appreciate it!), need to edit [this file](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-vendor-partnership.md) with the correct link that @marisamorby specified.
