### ISSUE TITLE
Gatsby: Integration with Contentful - struggling to add data in the component

### ISSUE THREAD

**Issue by theofromthelabo** [gatsbyjs/gatsby#13366]
Dear ! 

HELP ! trying to integration Contentful with my Gatsby. I think I'm almost there, just the final touch that I'm missing ;) 

I try it first on the tagline of my homepage: "Solve problem with digital solution(s)"

in Contentful - 
Content Model: Homepage - text | ID: homepageText
Field: tagline

I would like to integrate this data from contentful to the h1 tag that is part of the Banner.js component. 

Can you please guide me to integrate this data from Contenful ?

Here is my repo: https://github.com/theofromthelabo/thelabo

Thxxxxx. so much! 

Cheers

**Comment by wardpeet** [comment]
Hey, without an env variable it would be hard to test this but I see that you use a pagequery inside the [banner.js component](https://github.com/theofromthelabo/thelabo/blob/master/src/components/Banner.js).

inside components you should use a static query which is described here:
https://www.gatsbyjs.org/docs/static-query/

**Comment by theofromthelabo** [comment]
@wardpeet ! thx you a lot ! it works! the learning curve takes some time! 

`
error gatsby-node.js returned an error
  TypeError: homepageText.forEach is not a function
  - gatsby-node.js:35 graphql.then.result
    /Users/tcourtial/thelabo/gatsby-node.js:35:22
`

Also I'm getting this error from gatsby-node.js => https://github.com/theofromthelabo/thelabo/blob/master/gatsby-node.js 

do you have any idea to resolve it ? 

thank you !

**Comment by jonniebigodes** [comment]
@theofromthelabo if you don't mind waiting i'm going to take a closer look when i get home and see what i can come up with...in the meantime take a look at #13288 and [repo](https://github.com/jonniebigodes/test_repoman_contenfull_tags) for some context. I'm perfectly aware that they might be unrelated issues, but at least it will give you some context when working and pulling data from contentful to Gatsby. Sounds good?

**Comment by jonniebigodes** [comment]
@theofromthelabo that error usually happens when you try to iterate something that is not iterable. but looking at you said and what you have in your `gatsby-node.js` in the repository you mentioned there's no reference to `homepageText.forEach`. Also is that error happening on deploy or locally? Also a quick tip for you, it seems that when you commited and pushed the code, you didn't have a `.gitignore` file and the folders `.cache` `public` and `node_modules` were commited, in the future avoid commiting those, as they should be only be available locally when the individual that clones the repo issues `npm install` for instance. As the presence of these folders might lead to some problems

**Comment by theofromthelabo** [comment]
@jonniebigodes 

regarding the error I got - it has been fixed with the following code in the gatsby-node.js: 
i was getting this error locally.

```
        const homepages = result.data.allContentfulHomepageText.edges
        
        homepages.forEach((index) => {
            createPage({
                path: `/${index.node.id}/` , 
                component: homepageTemplate, 
                context: {
                    id: index.node.id,
                },
            })
        })
```

Folders .cache public and node_modules: I pushed them to the repo before adding .gitignore - can I delete these folders from my Github directly (https://github.com/theofromthelabo/thelabo)? 

Also I have another question regarding the rich text editor of Contenfu. How can we create/manage different colour of text? 
Maybe this question should be asked to https://github.com/contentful direectly. 

cheers and thx again !

**Comment by jonniebigodes** [comment]
@theofromthelabo Sorry for the late response and yes, the `.cache` `public` and `node_modules` should only exist on your end, on your local machine for the reason i stated above. Also i've been tinkering with contentful model trying to get something like you asked in your comment above, To no luck. The only way is to do it the "old fashioned way" (pardon the bad pun) with the css or inline styles. but in my defense i'm no expert in contentful in any way shape or form and there might be some other more edgier approach to it that i was not able to achieve. Probably in there you might have a better luck in the contentful issues.
