### ISSUE TITLE
Multiple microsites from single project?

### ISSUE THREAD

**Issue by natezerk** [gatsbyjs/gatsby#13365]
What would be the best way to have a single Gatsby project with multiple microsites?

Ideally, this would pull in data from a single source (e.g. Netlify CMS). Let's say this gives us a list of places.

Then the build would need to create different output (public) folders for each one?

Is this possible? I am not even sure where to start with this.

**Comment by wardpeet** [comment]
We don't allow writing to multiple folders but we have something called themes.

Themes give you the possibility to put all your logic in a base gatsby site which other projects can extend from. For your use case you could put in the data fetching inside the base theme and make x subsites based on that theme. With themes you can still overwrite anything from the base theme if it needs to so you have 100% flexibility.

More information about themese can be found here:
https://www.gatsbyjs.org/blog/2018-11-11-introducing-gatsby-themes/
https://www.gatsbyjs.org/blog/tags/themes

**Comment by natezerk** [comment]
Okay great, thanks, will have a look at them.
