### ISSUE TITLE
[gatsby-source-wordpress] How to query only for stickied posts?

### ISSUE THREAD

**Issue by ferni** [gatsbyjs/gatsby#13378]
How do you get only stickied posts from wordpress (sticky=true)? Ideally I would want the plugin to not fetch at all the other posts, but if you can only filter them after the fact that could work too.

In the API I would do this: /wp-json/wp/v2/posts?sticky=true&per_page=3 , how to do the same with the plugin? Thanks.

**Comment by orshick** [comment]
@ferni I believe a query like this should do the trick

```
allWordpressPost( filter: {sticky: { eq: false }}) {
    edges {
      node {
        title
        sticky
      }
    }
  }
```

**Comment by ferni** [comment]
Yeah that did work. So there's no way to prevent fetching all the posts? Is it only possible to filter them after getting all of them?

**Comment by orshick** [comment]
You mean under the hood? I'm not sure how graphql works on that level, but unless wordpress keeps a separate list of sticky pages for this plugin to query, there's no way to check which pages are sticky and which are not without checking them all.

**Comment by ferni** [comment]
You can filter the posts in the API by adding sticky=true to the query string, for instance /wp-json/wp/v2/posts?sticky=true , so if you could just add arbitrary query parameters as an option to the plugin, that would do it.

**Comment by wardpeet** [comment]
At the moment we don't have an option to add querystrings to the urls we query. So sadly you'll have to fetch all your posts at this time.

**Comment by ferni** [comment]
Okay, thanks a lot for your help.
