### ISSUE TITLE
Invite Gatsby users to learn more about plugin authoring via CLI

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#13377]
## Summary

The CLI could invite users who seem to be authoring a plugin to learn more about a few resources that they might find useful.

### Basic example

The CLI could say:

```
Watsons-MacBook-Pro:~ watsondog$ gatsby develop
Are you interested in learning how to write your own Gatsby plugin [y/n] Y

To learn more about creating a Gatsby source plugin, use these resources:

Walk through the tutorial (https://www.stuff.com)
etc.

Run `gatsby start source-plugin` anytime you'd like to see this help center again. Thank you!
```

We could expand this pattern in the future as we learn to anticipate plugin authors' needs.

### Motivation

People say the plugin authoring docs are useful but hardly anyone looks at them. This could increase views of docs and decrease the amount of time it takes to create a plugin. The trick then would be for people to find out about the new command `gatsby start source-plugin`. 

Related Issue #13376

**Comment by assuncaocharles** [comment]
Hey, 

Can I try to handle this one?

**Comment by shannonbux** [comment]
Going to modify this because I don't think it's helpful to invite everyone to learn about plugin authoring. Is it possible to detect if the user is doing specific plugin authoring type activities, and *then* invite them to learn more about plugin authoring?
