### ISSUE TITLE
How to access context from page created statefully?

### ISSUE THREAD

**Issue by natezerk** [gatsbyjs/gatsby#13382]
Hello,

I have a project with a default `index.js`. I am trying to pass a context variable into the query on it, so that I can do something like this: 

```
export const pageQuery = graphql`
  query HomeQuery($key: !String) {
    site {
      siteMetadata {
        title
      }
    }
    allContentfulProperty(filter: { slug: { eq: $key } }) {
      edges {
        node {
          id
          title
          slug
          dateCreated
        }
      }
    }
  }
`
```

The example given here says to add an `onCreatePage` hook that adds the context to the page: https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#pass-context-to-pages.

So I have done this in `gatsby-node`:

```
exports.onCreatePage = ({ page, actions }) => {
  const { createPage, deletePage } = actions
  console.log('page ' . page)
  deletePage(page)
  createPage({
    ...page,
    context: {
      key: 'test'
    }
  })
}
```

However, this function does not seem to be called when generating my default index page (not done programmatically, just by having an `index.js` file in `pages/`) and hence this throws errors saying it doesn't have access to $key? Maybe because it is created by default and not through `config-node`?

Any idea on how I can pass this context variable into the query on this page?

**Comment by garretteklof** [comment]
What was the resolution here? I am experiencing a similar issue.

**Comment by natezerk** [comment]
This was one of those funny ones where restarting the project seemed to work. The method should be being called and was after a restart.

I think this only works for page queries though and not static queries if that's what you're trying to do.

**Comment by garretteklof** [comment]
Thanks for the quick reply! I actually restarted (plenty lol), the issue was even more ridiculous. I started a new Gatsby project via the CLI, and it asked me whether I wanted yarn or npm as my package manager. I chose yarn, and it set me up that way, however the script `yarn run start` was still alias for the script `npm run develop`. Something with my binaries with node were wonky? I switched the script to `yarn run develop`, and voilée. That is an hour I will never get back 😝

**Comment by garretteklof** [comment]
Idk if I should post this anywhere. If there's some bug with the CLI, or if my build was just a lemon and that sneaky script snuck in anywhere but on the off chance anyone's listening: `The node binary used for scripts is /var/folders/py/qr45p7jx12q94v6hj7l599940000gn/T/yarn--1555630565690-0.4286459916050005/node but npm is using /usr/local/Cellar/node/11.2.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.`
