### ISSUE TITLE
[plugin-preact] Update to use Preact X (preact/compat)

### ISSUE THREAD

**Issue by seaneking** [gatsbyjs/gatsby#13380]
## Description

Preact 8.x is incompatible with reach router and errors out on Gatsby v2 (see #8545). Preact X includes compat for contexts and other React 16 features needed by Gatsby, and has moved the `compat` module to core. This plugin should use that, even though it's currently in alpha, since the current implementation is broken.

Just a matter of updating alias refs from `preact-compat` to `preact/compat` and requiring a peer dep of preact `^10.0.0`.

### Steps to reproduce

Use `gatsby-plugin-preact` with Preact 10 alpha

### Expected result

It should work

### Actual result

It doesn't

**Comment by wardpeet** [comment]
@seaneking as a preact core member, it's on my list to update the plugin and make sure Gatsby works. I'm a bit swamped with other priorities right now but feel free to pick this up.

**Comment by seaneking** [comment]
@wardpeet great to hear! I tried using Preact X locally, but seems there's still incompatibilities with react router and contexts. So guess we'll have to wait for more bugs to be ironed out during the alpha

**Comment by seaneking** [comment]
I think this should be kept open until Preact X is compatible with Reach router (and therefore Gatsby) and can be used again with this plugin. The beta rewrite may have fixed the issues I saw last time I tried, will try again when I get a chance.
