### ISSUE TITLE
Structured microdata

### ISSUE THREAD

**Issue by donaldboulton** [gatsbyjs/gatsby#13383]
A real website has blogs, pages, adds, reviews comments ect...
And there are many things that Gatsby has decided we do not need, like the real ability to have our content found by search engines - spiders.

If you all are building for Googlers then you might think about, "in code structured micro-data", = no sudo json LD.
Pages, comments, posts, adds, reviews, products ect... need to have a correct structure for search engines.. Unless the  Googlers could find our site's and page's what good is Googling for non-indexed content. Gatsby need's to have some kind of usable structured microdata for Google search and other spiders, by adding it to any real website site, so the Google spiders and other spiders can index there content

Now this is not true for Gatsbyjs as you all have 0 microdata in any of your sites and that's ok because of all the people searching for Gatsby stuff. So you are positioned by search hits, but the regular user with a web site need's to have all the help he can get to have his content found so the Googlers will even know his site and pages are there.

**Comment by wardpeet** [comment]
We use meta tags instead of structured microdata. Although structured data might improve SEO, it mostly improves how it shows up on google.

We heavily use the [SEO Component](https://www.gatsbyjs.org/docs/add-seo-component/). Nothing stops you to create a component that adds structured data.

**Comment by donaldboulton** [comment]
No way to inject the variables need for the proper structure, been tried by the MVC Community and the Jekyll community, no one ever got it working so it had the proper format which Schema.org constantly refines.
Here is Googles Products sample below, which is not totally correct but the basic idea.

`<div itemscope itemtype="https://schema.org/Product">
  <span itemprop="brand">ACME</span> <span itemprop="name">Executive Anvil</span>
  <img itemprop="image" src="anvil_executive.jpg" />
  <span itemprop="aggregateRating" itemscope itemtype="https://schema.org/AggregateRating">
    Average rating: <span itemprop="ratingValue">4.4</span>, based on
    <span itemprop="ratingCount">89</span> reviews
  </span>
  <span itemprop="offers" itemscope itemtype="https://schema.org/AggregateOffer">
    from $<span itemprop="lowPrice">119.99</span> to
    $<span itemprop="highPrice">199.99</span>
    <meta itemprop="priceCurrency" content="USD" />
  </span>
</div>`
If you are trying to sell something then it is important to have your product found in the first Search engine page or you most likely will not be found.

Spent years doing page emulation for internet positioning companies. If you cannot be in the top 10 on the first search page for Google **or any internet spider**. then most likely you do not sell anything.

Is Gatsby a Website framework or a toy?

Most of the community uses Gatsby for a look at me thing and most of the posts about or on Gatsby are straight plagerizms on Gatsby.com or Gatsbyjs.org code samples and some others without the credits.

I am not quite sure what Gatsby is trying to achieve? A fully functional Web Framework or a superfast toy.

**Comment by me4502** [comment]
It’s perfectly possible to use Microdata with Gatsby as is. Just apply it where you need it. I’ve set it up on multiple sites by just adding the tags and it works fine.

**Comment by donaldboulton** [comment]
Have you used some testing tool for results and on what website links. I would like to see it.

**Comment by LekoArts** [comment]
I honestly don't understand what point you're trying to make 😅 As the others said you can just implement the schema.org stuff yourself -- Gatsby's standard SEO doesn't ship it by default.

You can use Google's own tool:
https://search.google.com/structured-data/testing-tool

---

My site:
https://www.lekoarts.de/en/blog/tips-and-tricks-for-gatsby

Result:
https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.lekoarts.de%2Fen%2Fblog%2Ftips-and-tricks-for-gatsby

Source Code:
https://github.com/LekoArts/portfolio/blob/40f8fc5f93a50556a83dd1539ed34983643814d7/src/components/SEO.jsx

**Comment by donaldboulton** [comment]
Ya nice site wish I could have found your [Tips & Tricks for Gatsby](https://www.lekoarts.de/en/blog/tips-and-tricks-for-gatsby) previously in my many searches for Gatsby related anything.
Your post on static queries is really helpful and wish I would have found it before. I have had issues with needing static queries in templates in the latest Gatsby.
But one reason I never found what I was looking for related to static queries is you have 0 structured data that gives internet spiders the ability to know what is in your site and pages content. 
Perfect microdata on Breadcrumbs and you even got last pub date on articles very nice but this should be within a website and then within a web page = structured.

This is as web page within a web site that has whatever content with maybe even structured in site comments, not a externally proved, "Disqus", does not work for this. Comments and better yet reviews tell Google or any spider that people are looking at and using you site. 
Structured by post, time, date, author, or whatever. The reviews of your content position you much higher in search hits so if anyone search's  for, "Gatsby Static Query or useStaticQuery" everyone could find your right on point to the lastest of what's up with Gatsby.
That's my point.

**Comment by donaldboulton** [comment]
No one cares and do not know the difference

**Comment by eeyorr** [comment]
FWIW, Google prefers JSON-LD over microdata and they have for years. 

> Cannot use meta-tags or json LD to achieve proper microdata structure for Web Page, comments, products or reviews.

I don't understand that. JSON-LD conveys the same properties as microdata and I think it's easier in most cases to build a JSON object on the fly than to inject microdata tags into content.

**Comment by kingluddite** [comment]
Here is a nice site showing you how to add JSON-LD - https://khalilstemmler.com/articles/how-to-optimize-your-gatsby-blog-for-seo/
