### ISSUE TITLE
[examples]: update dependencies for styleguide example

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#13399]
## Description

Our example `styleguide` is using a slightly outdated version of some packages. Our examples should serve as best practices, which means that they should _also_ be up-to-date with the latest and greatest versions of our excellent plugin infrastructure.

## Technical Detail

1. You will need to fork the repo and follow the set-up process [outlined in this document](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/)
1. The changes will be isolated to the [`examples/styleguide`](https://github.com/gatsbyjs/gatsby/tree/master/examples/styleguide) directory
1. Update the version of `gatsby-transformer-react-docgen` to `^4.0.0` and make any necessary fixes
    - Check out the [CHANGELOG for gatsby-transformer-react-docgen](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-react-docgen/CHANGELOG.md) particularly checking for any breaking changes
1. The end result should be viewable, and should work with both `gatsby develop` and `gatsby build`

**Comment by steoneill** [comment]
I’ll take this :)

**Comment by DSchau** [comment]
Wonderful! Thanks for assigning yourself and taking it on!

**Comment by steoneill** [comment]
@DSchau OK so everything seems to be working as it is before the update :) 

I seem to be getting hot update errors though, before & after updating. Is this to be expected?

**Comment by steoneill** [comment]
@gatsbyjs/core any updates on what I can do here? :)

**Comment by polishedwp** [comment]
@steoneill @DSchau What is the status of this Issue? Do you need any help?

**Comment by steoneill** [comment]
@polishedwp hi!

I've updated them locally but before & after changes it's showing issues with hot reloading. 

Do you know if this is to be expected?

**Comment by wardpeet** [comment]
@steoneill mind sharing your work in a PR? We could review and give feedback on the issue.

**Comment by polishedwp** [comment]
I agree ... Share the PR and we can help.

**Comment by dorshinar** [comment]
Hi! I see this issue has not been touched since may, I'd love to give it a go. 

@eclectic-coding

**Comment by eclectic-coding** [comment]
@dorshinar I see no problem with that. I was waiting for @steoneill to submit a PR but haven't heard from him in months.

**Comment by steoneill** [comment]
Sorry guys, life 100% got in the way! Feel free (and sorry!)

**Comment by dorshinar** [comment]
Great! I've submitted a pull request fixing this issue. 

@eclectic-coding
