### ISSUE TITLE
[examples]: update using-emotion dependencies in example project

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#13401]
## Description

Our example `using-emotion` is using a slightly outdated version of some packages. Our examples should serve as best practices, which means that they should _also_ be up-to-date with the latest and greatest versions of our excellent plugin infrastructure.

## Technical Detail

1. You will need to fork the repo and follow the set-up process [outlined in this document](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/)
1. The changes will be isolated to the [`examples/using-emotion`](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-emotion) directory
1. Update the version of `gatsby-plugin-emotion` to `^4.0.6` and make any necessary fixes
    - Check out the [CHANGELOG for gatsby-plugin-emotion](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-emotion/CHANGELOG.md) particularly checking for any breaking changes
1. The end result should be viewable, and should work with both `gatsby develop` and `gatsby build`

**Comment by taran-gill** [comment]
Hey, mind if I look into this?

**Comment by polishedwp** [comment]
@taran-gill are you working on this one?

**Comment by taran-gill** [comment]
@polishedwp I was expecting to be assigned the issue before I started it, so I haven't had the opportunity to look into it (although I was hoping to knock this out tomorrow and Saturday). I've never contributed to Gatsby before, so if the ticket's high priority, then feel free to work on this :)

**Comment by polishedwp** [comment]
@taran-gill I say go for it. If you need any help let me know.

**Comment by paschalidi** [comment]
@KyleAMathews hey, I might be wrong but it looks like this issue needs to be closed.
