### ISSUE TITLE
[examples]: update using-remark dependencies in example project

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#13404]
## Description

Our example `using-remark` is using a slightly outdated version of some packages. Our examples should serve as best practices, which means that they should _also_ be up-to-date with the latest and greatest versions of our excellent plugin infrastructure.

## Technical Detail

1. You will need to fork the repo and follow the set-up process [outlined in this document](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/)
1. The changes will be isolated to the [`examples/using-remark`](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-remark) directory
1. Update the version of `gatsby-remark-images` to `^3.0.10` and `gatsby-remark-katex` to `^3.0.4` and make any necessary fixes
    - [Check out the CHANGELOG for gatsby-remark-images](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/CHANGELOG.md) and [the CHANGELOG for gatsby-remark-katex](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-katex/CHANGELOG.md) particularly focusing on any breaking changes
1. The end result should be viewable, and should work with both `gatsby develop` and `gatsby build`

**Comment by nephlin7** [comment]
@DSchau 
can you assign me this?

**Comment by nephlin7** [comment]
hi @DSchau , I did the pull request, but I do not know why it became like a child of another pull request that I did previously. 😓

How do I fix it?
