### ISSUE TITLE
[examples]: update using-gatsby-image dependencies in example project

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#13403]
## Description

Our example `using-gatsby-image` is using a slightly outdated version of some packages. Our examples should serve as best practices, which means that they should _also_ be up-to-date with the latest and greatest versions of our excellent plugin infrastructure.

## Technical Detail

1. You will need to fork the repo and follow the set-up process [outlined in this document](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/)
1. The changes will be isolated to the [`examples/using-gatsby-image`](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-gatsby-image) directory
1. Update the version of `gatsby-plugin-emotion` to `^4.0.6` and make any necessary fixes
    - Check out the [CHANGELOG for gatsby-plugin-emotion](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-emotion/CHANGELOG.md) particularly checking for any breaking changes
1. The end result should be viewable, and should work with both `gatsby develop` and `gatsby build`

**Comment by samovertonjr** [comment]
@DSchau Can I grab this?

**Comment by DSchau** [comment]
✅ Done! Thank you!

**Comment by pieh** [comment]
PR with update was merged, thanks @samovertonjr!
