### ISSUE TITLE
[examples]: update using-emotion-prismjs dependencies in example project

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#13402]
## Description

Our example `using-emotion-prismjs` is using a slightly outdated version of some packages. Our examples should serve as best practices, which means that they should _also_ be up-to-date with the latest and greatest versions of our excellent plugin infrastructure.

## Technical Detail

1. You will need to fork the repo and follow the set-up process [outlined in this document](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/)
1. The changes will be isolated to the [`examples/using-emotion-prismjs`](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-emotion-prismjs) directory
1. Update the version of `gatsby-plugin-emotion` to `^4.0.6` and make any necessary fixes
    - Check out the [CHANGELOG for gatsby-plugin-emotion](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-emotion/CHANGELOG.md) particularly checking for any breaking changes
1. The end result should be viewable, and should work with both `gatsby develop` and `gatsby build`

**Comment by polishedwp** [comment]
I will work on this in the morning.

**Comment by lannonbr** [comment]
And this is done. Closing
