### ISSUE TITLE
[examples]: update dependencies for using-cxs

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#13400]
## Description

Our example `using-cxs` is using a slightly outdated version of some packages. Our examples should serve as best practices, which means that they should _also_ be up-to-date with the latest and greatest versions of our excellent plugin infrastructure.

## Technical Detail

1. You will need to fork the repo and follow the set-up process [outlined in this document](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/)
1. The changes will be isolated to the [`examples/using-cxs`](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-cxs) directory
1. Update the version of `gatsby-plugin-cxs` to `^2.0.8` and make any necessary fixes
    - Check out the [CHANGELOG for gatsby-plugin-cxs](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-cxs/CHANGELOG.md) particularly checking for any breaking changes
1. The end result should be viewable, and should work with both `gatsby develop` and `gatsby build`

**Comment by rajatrao777** [comment]
Hi @DSchau,
If no one else is taking up and if this is not urgent, can i look into it.
This will be my first contribution.

**Comment by KirankumarAmbati** [comment]
May I know if this issue is addressed ?

**Comment by DSchau** [comment]
It has! Thanks for the reminder!
