### ISSUE TITLE
[examples]: update using-remark-copy-linked-files dependencies in example project

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#13405]
## Description

Our example `using-remark-copy-linked-files` is using a slightly outdated version of some packages. Our examples should serve as best practices, which means that they should _also_ be up-to-date with the latest and greatest versions of our excellent plugin infrastructure.

## Technical Detail

1. You will need to fork the repo and follow the set-up process [outlined in this document](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/)
1. The changes will be isolated to the [`examples/using-remark-copy-linked-files`](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-remark-copy-linked-files) directory
1. Update the version of `gatsby-remark-images` to `^3.0.10` and make any necessary fixes
    - [Check out the CHANGELOG](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/CHANGELOG.md) particularly focusing on any breaking changes
1. The end result should be viewable, and should work with both `gatsby develop` and `gatsby build`

**Comment by polishedwp** [comment]
Hey @DSchau ,
I will work on this one this evening, unless someone else picks it up first.

**Comment by DSchau** [comment]
I'll assign it--it's all yours.

Thank you!

**Comment by lannonbr** [comment]
This seems to be resolved
