### ISSUE TITLE
How to Automatically Cache All Routes with Offline Plugin

### ISSUE THREAD

**Issue by adueck** [gatsbyjs/gatsby#13417]
I am using `gatsby-plugin-offline` with the default configuration.

I have noticed that it only caches routes that the user visits. If the user doesn't visit a route while online, they can't open that route/page when offline.  

**I would like to be able to automatically cache all routes/pages, so that once a user installs the PWA they can get any route offline.**  And I'm a little nervous about overriding the options because [as the documentation says](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/): 

> Warning: you can break the offline support by changing these options, so tread carefully.

In my case, I have something similar to a blog with [programmatically generated pages like this](https://www.gatsbyjs.org/tutorial/part-seven/).  How can I have all these generated pages cached automatically for offline use?  

Thank you so much for this fantastic product.

**Comment by adueck** [comment]
Any thoughts/ideas anybody? For me this is kind of a deal-breaker, so if this isn't possible I think I will switch my site over to a regular single page app bootstrapped from [create-react-app](https://github.com/facebook/create-react-app)

**Comment by adueck** [comment]
No, please don't close this... Anybody?

**Comment by KyleAMathews** [comment]
This isn't something we'll directly support in core as it's a niche use case as most casual visitors to your site don't want to download code & data for dozens or hundreds of pages.

This _would_ be a cool plugin though. What the plugin code do is create a manifest file that lists every page and what code/data is required for those pages. Then once the site is loaded, fetch all the files which the SW will cache.
