### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by tweetzal** [gatsbyjs/gatsby#13423]
Hi there,
I followed instructions to install.
All worked fine.
However, I suggest the following install command if you want to have no issues: 

npm install --save-dev babel-jest react-test-renderer babel-preset-gatsby identity-obj-proxy jest-cli jest-dom

I basically added jest-cli and jest-dom and removed jest

Thats it !

Otherwise you will get errors on a clean gatsby install

**Comment by DSchau** [comment]
@tweetzal hello!

I'm not really sure what you mean here? Is there an error? What are you trying to do?

**Comment by tweetzal** [comment]
I resolved the issue by using the suggested fix.

Just wanted to let you know, so can update the pagw as it assumes you have
jest cli installed

Best
Mo

**Comment by KartSriv** [comment]
Thanks, @tweetzal for your information! I'll close this issue now.
