### ISSUE TITLE
Tracking page visits (splunk)

### ISSUE THREAD

**Issue by gurpreet-hanjra** [gatsbyjs/gatsby#13420]
Hello everyone,

The project I'm working upon needs to track page visits like which page was visited how many time. No user tracking, so can't use Google of other 3rd party tracking tools. There is one tool, Splunk, which looks at network requests and logs page visits.

Since Gatsby is SPA and when I look into Network panel, there are bunch of network requests due to resource pre-fetching. So Splunk doesn't help there.

Any suggestion for tools or method to track page visits?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by DSchau** [comment]
Gatsby provides you all the hooks you'd need to implement this yourself utilizing whatever technology you prefer.

I would recommend using `gatsby-browser.js`, specifically the [`onRouteUpdate`](https://www.gatsbyjs.org/docs/browser-apis/#onRouteUpdate) API which will work well for this use case. Specifically - you can see in the example that we show implementing Google Analytics, but you could swap to whatever library you prefer (e.g. Splunk).

How it would look for you, the implementer:

1. If Splunk provides a library/global (it almost certainly does), look at injecting it with gatsby-ssr.js or a dynamic import as to not impact the initial load
1. Use gatsby-browser.js to call the APIs that Splunk (or whatever) provide

Hope this helps! Going to close as answered--thanks for the question!
