### ISSUE TITLE
Gatsby breaks in path with non-ascii characters

### ISSUE THREAD

**Issue by buthig** [gatsbyjs/gatsby#13429]
## Description

I'm completely newbie to Gatsby and was following the introduction tutorial of hello-world starter project but every time I ran `gatsby develop / build` it was breaking around the createPages phase.

It took me a while to understand what was happening but after finding where the error was actually being raised and preventing the undefined string to be called on, I suspected that the problem came because my full path (PWD) contains the spanish word _código_ and this o with an graphical accent breaks gatsby build process.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

1. in a test directory run `mkdir código`
2. `cd código`
3. `gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`
4. `gatsby develop`

### Expected result

Gatsby should go over the project and come back with a dev server running on localhost:8000

### Actual result

The develop build process breaks with following output

success open and validate gatsby-configs — 0.013 s
success load plugins — 0.062 s
success onPreInit — 0.007 s
success delete html and css files from previous builds — 0.012 s
success initialize cache — 0.038 s
success copy gatsby files — 0.203 s
success onPreBootstrap — 0.021 s
success source and transform nodes — 0.032 s
success building schema — 0.243 s
success createPages — 0.000 s
error UNHANDLED REJECTION

  TypeError: Cannot read property 'replace' of undefined
  
  - index.js:10 module.exports
    [hello-world]/[slash]/index.js:10:13
  
  - actions.js:201 actions.createPage
    [hello-world]/[gatsby]/dist/redux/actions.js:201:35
  
  - redux.js:468 
    [hello-world]/[redux]/lib/redux.js:468:35
  
  - api-runner-node.js:63 doubleBoundActionCreators.(anonymous function).args
    [hello-world]/[gatsby]/dist/utils/api-runner-node.js:63:13
  
  - gatsby-node.js:141 _createPage
    [hello-world]/[gatsby-plugin-page-creator]/gatsby-node.js:141:3
  
  - gatsby-node.js:76 
    [hello-world]/[gatsby-plugin-page-creator]/gatsby-node.js:76:22
  
  - Array.forEach
  
  - gatsby-node.js:75 Object._callee$
    [hello-world]/[gatsby-plugin-page-creator]/gatsby-node.js:75:19

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 66.0.2
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.16 => 2.3.16 
  npmGlobalPackages:
    gatsby-cli: 2.5.9

**Comment by jonniebigodes** [comment]
@buthig spanish..or portuguese words for instance that use the language's accents like `à` or `á` or `ã` or even more specifically special characters like the portuguese `ç` tend to break it. From my testing, when i got started with Gatsby back in version 1.5. And then when i tested it with version 2.x.x same issue happened. For now, if you don't mind, try and avoid using the accents or like in your language specific case for instance the `ñ` as it will result in issues.

**Comment by buthig** [comment]
I can agree this may be a low priority issue but I created this bug report because of two reasons.

Firstly, I was unable to find a solution to this issue when googling for it, and taking into account that it happens when trying to run the very first tutorial for Gatsby I believe that it would be useful for other newcomers to find an easy workaround for it before they get frustrated about this project.

Secondly, I believe that the workaround is not trivial nor elegant (e.g. it breaks all _recent projects_ in any IDE) but even it might be not possible to rename the path if the special character is part of the username in a work environment. Specially because the issue arises even with special characters outside the project directories, and this outside path _should be ignored_ when creating the build.

If I find time once I understand better how Gatsby works, I could send a PR to fix it. 

Currently, I see there are three solutions:

1. The *good* one: some error message is shown on the console so that users understand what is breaking the pipeline and are able to act upon it.
2. The *better* one: the tooling is able to process projects with special characters that lie outside the project directories, i.e. upper in the path chain.
3. The *best* one: special characters may occur even in the project directories and they are substituted for normal ones in the output from the build process in a similar way to what happens when _locale comparison_ functions take _a_, _à_, _á_, _ä_, etc as the same character in the sorting.

**Comment by AVert** [comment]
Hey non latin chars must be suppotred!
