### ISSUE TITLE
apple-app-site-association

### ISSUE THREAD

**Issue by jeffchuber** [gatsbyjs/gatsby#13437]
I'm interested in strategies to add `apple-app-site-association` to a Gatsby site. [more here](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html)

Apple requires that it be at `https://domain.com/.well-known/apple-app-site-association` and return flat `json`. (no html!) 

In m production website, I'm using `Cloudfront` in front of `s3`, so linking directly to it does not work. The Gatsby router picks up the route and gives me a 404. 

Thank you!

**Comment by DSchau** [comment]
@jeffchuber wouldn't you need to add this to the static folder? https://www.gatsbyjs.org/docs/static-folder/

This will be copied as-is to the public folder, which can then be deployed to e.g. S3 very easily.

Also: this seems like this could be a good idea for a plugin to create this automatically!

Going to close as answered, but please feel free to re-open/reply if we can help further!

**Comment by jeffchuber** [comment]
@DSchau thanks for the quick reply! 

The issue is not getting a file into the static folder, the issue is accessing that file by the route/url apple demands `https://domain.com/.well-known/apple-app-site-association`. 

Desired scenario:
1. Apple's crawler visits `http://localhost:8000/.well-known/apple-app-site-association`
2. It is presented with raw json. eg:
```json
{
  "webcredentials": {
    "apps": [
      "KAW43335BG.com.companyName.App1",
      "KAW43335BG.com.companyName.App2"
    ]
  }
}
```

**Comment by jeffchuber** [comment]
Looks like this is not an uncommon issue: https://github.com/gatsbyjs/gatsby/issues/4144

**Comment by DSchau** [comment]
@jeffchuber you need to set up a redirect for your provider. For example, with S3: https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

I've set up an example with Netlify [with this repo](https://github.com/DSchau/apple-app-site-association), and you can see it working:

https://gatsby-apple-app-site-association.netlify.com/.well-known/apple-app-site-association

**Comment by jeffchuber** [comment]
@DSchau I really appreciate the reply! I do think this is something a lot of devs will encounter or I wouldn't spend the time. 

Unfortunately it needs to be solved at the routing level because Apple rejects redirects:
<img width="898" alt="Screen Shot 2019-04-19 at 11 11 09 AM" src="https://user-images.githubusercontent.com/891664/56437380-003a1880-6294-11e9-925a-0253dd930d9c.png">
https://developer.apple.com/documentation/security/password_autofill/setting_up_an_app_s_associated_domains

My understanding is that enabling a dev to add a route to `gatsby-node.js` that can point directly at a file (instead of a React component) would be ideal. Something like this perhaps. 
```js
createPage({
  path: '/.well-known/apple-app-site-association',
  file: path.resolve('./public/.well-known/apple-app-site-association.json'),
})
```

**Comment by DSchau** [comment]
Ah! Come on Apple, not making it easy on us!

Let's re-open this and find a more robust solution.

**Comment by jeffchuber** [comment]
@DSchau what do you think about the idea above of setting up a route to serve a static file?

**Comment by rafcontreras** [comment]
Hi @jeffchuber,

Why do you need to route to the `apple-app-site-association` file? Safari looks if the file exists on your server for credential sharing.

It may be that your server is restricting access to dotfiles which are hidden to some OSs.

I use express to serve the gatsby files and express.static to allow access to the `.well-known` folder.

```js
app.use(
  express.static(serverSettings.root, {
    dotfiles: "allow"
  })
);
```

<img width="277" alt="Screen Shot 2019-04-26 at 6 03 22 AM" src="https://user-images.githubusercontent.com/670423/56757729-032f8e80-67e9-11e9-895c-aaa39e3cc52d.png">

**Comment by jeffchuber** [comment]
@rafcontreras thanks for the idea! 

currently im using Cloudfront -> S3 -> gatsby static site. 

I found a workaround which is hosting on a subdomain, so I'm going to close this for now out of respect for the community.

**Comment by adberard** [comment]
> Hi @jeffchuber,
> 
> Why do you need to route to the `apple-app-site-association` file? Safari and your iOS app look for if the file exists on your server for credential sharing.
> 
> It may be that your server is restricting access to dotfiles which are hidden to some OSs.
> 
> I use express to serve the gatsby files and express.static to allow access to the `.well-known` folder.
> 
> ```js
> app.use(
>   express.static(serverSettings.root, {
>     dotfiles: "allow"
>   })
> );
> 
> app.get("/.well-known/change-password", (req, res) => {
>   res.redirect(301, "/change-password");
> });
> ```
> 
> <img alt="Screen Shot 2019-04-26 at 6 03 22 AM" width="277" src="https://user-images.githubusercontent.com/670423/56757729-032f8e80-67e9-11e9-895c-aaa39e3cc52d.png">

Where do you use express exactly ?

**Comment by rafcontreras** [comment]
Hey @adberard 

I used Gatsby to create a hybrid app, so I need a server in between the user and the different APIs as some have dumb CORS settings.

I'm using expressJS to proxy API requests and I'm hosting it in Azure.

Here's my very small express server:

```javascript
const url = require("url");
const express = require("express");
const gatsyExpress = require("gatsby-plugin-express");
const proxy = require("express-http-proxy");
const bugsnagExpress = require("@bugsnag/plugin-express");
const bodyParser = require("body-parser");
const expressStaticGzip = require("express-static-gzip");

// NodeJS Express server
const app = express();

// In case the server is behind a proxy
app.enable("trust proxy");
// Removes the X-Powered-By header to make it slightly harder for attackers to see what potentially-vulnerable technology powers your site
app.disable("x-powered-by");

// Parse rest queries
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// Redirect .well-known requests .well-known/change-password
app.get("/.well-known/change-password", (request, response) => {
  response.redirect(301, "/change-password");
});

// Proxy API
app.use(
  "/api",
  proxy("https://api.domain.tld", {
    https: true,
    proxyReqPathResolver(request) {
      const reqPath = url.parse(request.url).path;
      return [api, reqPath].join("/");
    },
    proxyErrorHandler(error, next) {
      console.log(error)
      next(error);
    }
  })
);

// Send pre-compressed static files
app.use(
  "/",
  expressStaticGzip("/public", {
    enableBrotli: true,
    orderPreference: ["br", "gz"]
  })
);

// Routes
app.use(
  gatsyExpress("gatsby-express.json", {
    publicDir: "/public",
    template: "public/404/index.html",
    redirectSlashes: true
  })
);

// Allow dotfiles
app.use(
  express.static(serverSettings.root, {
    dotfiles: "allow"
  })
);

// Serve 404 page on 404
app.use((req, res, next) => {
  const err = new Error("Not Found");
  err.status = 404;
  next(err);
});

app.use((err, req, res, next) => {
  res.status(err.status || 500);
  res.sendFile("404/index.html", {
    root: "/public"
  });
});

// HTTP server
app
  .listen(3000, () => {})
  .on("error", e => {
    console.log(e);
  });
```

**Comment by maximedegreve** [comment]
Another simple strategy is placing it directly in /public.
Even though public is in .gitignore, you can `git add -f ./public/apple-app-site-association` and commit it. It shouldn't get deleted or overwritten when you build.

**Comment by PolGuixe** [comment]
Has anyone found a solid approach for this? 

Is creating the file on `postBuild` a good solution?

**Comment by Svarto** [comment]
I also need a solution to this... @jeffchuber how did you host it on a subdomain? Does your links then all have to be written as `subdomain.example.com` or is it possible to still have the universal link applicable to `example.com`?

@PolGuixe did you find a good solution?

**Comment by whitedogg13** [comment]
Hi all, I have successfully linked my app with a gatsby-js powered website recently. It's not complex, and you don't actually need to use any server-rendered route, just some little gotchas.

My website is hosted on `Netlify`, but I believe the same idea applies to all hosting platforms. 

Here're the steps.

1. Put your `apple-app-site-association` in `static` folder, as mentioned by @DSchau 
```
{"applinks":{"apps":[],"details":[{"appID":"HE7MCCDHL4.com.revteltech.nfcopenrewriter","paths":["*"]}]}}
```
> Please notice the `apps` prop should be an empty array. (Apple has some updates regarding this format, but the above snippet works correctly for me)

> By Apple's doc, you can serve it under `/` or `/.well-known`, we use the former one here.

2. serve this file with correct `content-type`, it should be `application/json`. More info check [official Apple doc](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html). For `netlify` users, you can put a `_headers` file in your `static` directory, with following content:
```
/apple-app-site-association
  Content-Type: application/json
```

> By default `netlify` serve it as `plain/text`, and I guess that's the reason why some people cannot make it work

3. Verify it.

You can use [official tool](https://search.developer.apple.com/appsearch-validation-tool). After you run the program, check the `Link to Application` field. 

The following screenshot means your association file is **NOT** recognized by Apple, you should check the format or content-type mentioned above:

![image](https://user-images.githubusercontent.com/10307875/124379065-65e51480-dce7-11eb-909d-56f220af4338.png)

On the other hand, the following screenshot means the `association` file is correctly served. Apple might need some time to process the link between your app and website. If there's still an issue, then it should be in your iOS app rather than your website. (in my case, the validator still show the same kind of messages but the `universal link` already works correctly):

![image](https://user-images.githubusercontent.com/10307875/124379006-26b6c380-dce7-11eb-9583-dd5379d2be03.png)

Finally, open your website in iOS safari browser, see if it hints you about your app on the **top** area:

![image](https://user-images.githubusercontent.com/10307875/124379465-d55c0380-dce9-11eb-81d9-bac6a21a8aa4.png)

Hope that helps!

**Comment by AristideNestor** [comment]
@whitedogg13  Could you provide Repo ? any final solution for this ?
