### ISSUE TITLE
gatsby-remark-images not show captions in md file

### ISSUE THREAD

**Issue by XHMM** [gatsbyjs/gatsby#13448]
When i write image like this `![my image](../img.jpg)`  in markdown file ,  
 `gatsby-remark-images` not show captions (because source code only detect img.title), 

(PS: I have enabled showCaptions in gatsby-config.js file)

so I have to write like `<img src="../img.jpg"  title="my image"></img>` instead. 
But when I switched to use `gatsby-mdx` later, 
`<img src="../img.jpg"  title="my image"></img>`   not worked (I watched output, src not replaced by processed images under static files, maybe a bug?) ,
 
so I have to write back `![my image](../img.jpg)` again,
but captions not showed in this way, 

so can you change `const showCaptions = options.showCaptions && node.title` ([source code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/index.js#L244) ) to `const showCaptions = options.showCaptions && (node.title || node.alt)`  or add something else to detect if image is written in `![my image](../img.jpg)` style and add captions to it?

**Comment by DSchau** [comment]
This seems reasonable! We'd happily take a PR.

**Comment by jamessimone** [comment]
@DSchau saw your comment on this yesterday and submitted a PR for the issue this morning. Let me know what you think! 

Thanks,
James
