### ISSUE TITLE
gatsby-source-shopify Pulling in Product Barcode?

### ISSUE THREAD

**Issue by waywardm** [gatsbyjs/gatsby#13441]
Is there any way to pull in the Product Variant Barcode?

I cannot see it available on the shopify api either which seems a bit strange.

**Comment by DSchau** [comment]
@waywardm if it's not available in the Shopify API, it won't be available in our source plugin!

I'd recommend opening an issue or reaching out for support to Shopify to see if they can add this capability, and then we can add it into our source plugin.

Thanks!
