### ISSUE TITLE
Gatsby-cypress is not present plugin library

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13457]
## Summary

If you search for `gatsby-cypress` it doesn't show up in the plugin library.

As well, the page for it does not show the sidebar and header:

https://www.gatsbyjs.org/packages/gatsby-cypress/

![Screenshot_2019-04-18 gatsby-cypress](https://user-images.githubusercontent.com/3685876/56378181-416df200-61da-11e9-8202-6129dc6eca89.png)

**Comment by DSchau** [comment]
Thanks @lannonbr!

For a plugin to show up in the sidebar, it needs to have the keyword `gatsby-plugin`, which it currently doesn't have.

That being said--I do think this is worth documenting, but I'm not really convinced this is a plugin. Plugins _are_ currently a little vague, e.g. gatsby-image is not a plugin but shows in the plugin search, so there is some precedent here.

However - the second issue you note (no sidebar/header) definitely seems to be an issue.

What do you think?

**Comment by lannonbr** [comment]
As well there was some other broken things too. making a PR right now for this

**Comment by wardpeet** [comment]
Should we keep this open @lannonbr, I think @DSchau explained why this isn't in the list. If this refers to some other issue, perhaps close this one and create a new one as this one is created for cypress.

**Comment by lannonbr** [comment]
Yeah I understand that reasoning that it is not technically a "plugin" persay, but more so do we want to keep the page around and if so what should we do for these "non-plugins"

**Comment by wardpeet** [comment]
It seems like the page for gatsby-cypress is gone. People can look it up and we could have a e2e blog post or tutorial where we talk about gatsby-cypress instead.

I'm marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
