### ISSUE TITLE
Modify Gatsbot wording for gatsby swag offer

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13453]
## Summary

Just a thought about the message gatsbot posts after someone get's their first PR merged. In terms of the swag offer, it may be a good idea to edit the phrasing to say what kind of stuff you can get given we have more products in the store now and not all are available under the first tier. As well, maybe have another comment for when people hit 5 PRs for the tier 2 threshold to tell people they now can get a free tier 2 swag item

This is currently how the phrasing is:

> We’d like to send you some Gatsby swag. As a token of our appreciation, you can go to the [Gatsby Swag Store](https://store.gatsbyjs.org/) and log in with your GitHub account to get a coupon code good for one free piece of swag. (Currently we’ve got a couple t-shirts available, plus some socks that are really razzing our berries right now.)

**Comment by DSchau** [comment]
If someone is interested in picking this up, the source of this message is the repo gatsbyjs/peril-gatsbyjs. We have a number of rules and automation in that repo currently invoked/powered by Peril.

Specifically, [this file](https://github.com/gatsbyjs/peril-gatsbyjs/blob/master/rules/invite-collaborator.ts) is where the changes will need to be made.

**Comment by lannonbr** [comment]
Let's keep this unpinned. The pinned issues usually should belong to issues that are relevant for all gatsby users / issues that we want to have large discussions on that are picked out by the Gatsby Core Team

**Comment by DSchau** [comment]
@polishedwp just for our context, did you accidentally pin? Feels like that's been happening a fair amount recently, so just trying to understand further!

**Comment by polishedwp** [comment]
No, I pinned to watch. If it is still open after the weekend, I will come back and pick it up.

**Comment by DSchau** [comment]
Ah - so pinning is more for _everyone_. You can just use the watch feature in Github to actually watch an issue!

**Comment by polishedwp** [comment]
Sorry, if this is the wrong way.

**Comment by DSchau** [comment]
@polishedwp nothing to apologize for! Thanks for letting us know _and_ for being willing to help!

**Comment by JDeLay-JR** [comment]
I would love to take this issue if no one has claimed it yet!

**Comment by lannonbr** [comment]
Go ahead @JDeLay-JR

**Comment by JDeLay-JR** [comment]
Awesome; thank you! Super excited; this will be my first contribution to an open source project!

**Comment by JDeLay-JR** [comment]
Hi guys, is there an official list of swag items and the tiers they belong to? I checked out the Gatsby Store and saw some items for $2, $10, and $26. Is it safe to assume that these prices correspond to Tiers 1, 2, & 3?

**Comment by lannonbr** [comment]
So the $2 and $10 items are under the first tier while the $26 items are under the 2nd tier

**Comment by JDeLay-JR** [comment]
Awesome sounds good; thank you for the quick reply!

**Comment by JDeLay-JR** [comment]
First PR was closed because it was accidentally created using my old GitHub account
