### ISSUE TITLE
gatsby-source-contentful not working

### ISSUE THREAD

**Issue by craig-coles** [gatsbyjs/gatsby#1345]
Not sure that this plugin is working. When I run $ gatsby develop I continually get 
GraphQLError: Cannot query field "Recipe" on type "RootQueryType" (where Recipe is my custom content type)

i've poked around in the code, and it seems that the gatsby-source-contentful plugin is never actually loaded (which logically seems like that's the problem), I've looked in  node_modules and added some console.log statements and can't see them tracing out.

Though when looking in node_modules/gatsby/dist/bootstrap/load-plugins.js a few basic console traces there seem to suggest it is getting to the plugin in the correct way from gatsby-config.js.

Tracing out console.log(plugin.resolve + "/gatsby-node") (line 214)  in node_modules/gatsby/dist/bootstrap/load-plugins.js 

shows:
`/my/project/path/node_modules/gatsby/dist/internal-plugins/component-page-creator/gatsby-node
/my/project/path/node_modules/gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node
/my/project/path/node_modules/gatsby/dist/internal-plugins/dev-404-page/gatsby-node
/my/project/path/node_modules/gatsby/dist/internal-plugins/query-runner/gatsby-node
/my/project/path/node_modules/gatsby-source-contentful/gatsby-node
/my/project/path//gatsby-node`

I've noticed that-> /my/project/path/node_modules/gatsby-source-contentful/gatsby-node doesn't actually exist (can't see a symlink here either)

but that -> /my/project/path/node_modules/gatsby-source-contentful/src/gatsby-node.js does exist

Any ideas here? I really like the project just wish I could get contentful working with it!

**Comment by KyleAMathews** [comment]
Have you checked out the example site for contentful? See if you can
replicate the problem there.

**Comment by craig-coles** [comment]
ok so that worked! thanks! the other version of gataby i was using was on master, does contentful only work in branch 1.0?

**Comment by jbolda** [comment]
@craig-coles, you are correct. Technically 1.0 was launched and that is on the master branch now. Glad you got it figured out!
