### ISSUE TITLE
[docs] Document that you can use just the username and repo in `gatsby new`

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13455]
## Summary

@jlengstorf and @marcysutton brought up in Jason's stream today that you can use a shorthand to choose the starter when running `gatsby new`

so rather than this:

```
gatsby new test https://github.com/gatsbyjs/gatsby-starter-hello-world
```

you can write just the user / org and the repo name

```
gatsby new test gatsbyjs/gatsby-starter-hello-world
```

This should be documented

**Comment by polishedwp** [comment]
So, to what extent is this documented? 
[Get Up and Running in 5 Minutes](https://github.com/gatsbyjs/gatsby/blob/master/README.md)
[Quick Start](https://www.gatsbyjs.org/docs/quick-start)
[Get to know Gatsby building blocks](https://www.gatsbyjs.org/tutorial/part-one/)

The command `gatsby new ...`, from my experience as a new user, is documented in a lot of locations.

**Comment by lannonbr** [comment]
I think a good place to look to document this would be possibly be the [Starters Docs page](https://www.gatsbyjs.org/docs/starters/) as this is just a shorthand when choosing a speciifc starter
