### ISSUE TITLE
Warn if creating a page with same path but trailing slash

### ISSUE THREAD

**Issue by Moocar** [gatsbyjs/gatsby#13464]
Say you have a site with two pages `/page` and `/page/` (second has a trailing slash). Reach Router will match `/page` or `/page/` pathname against either of them, since it doesn't care about trailing slashes. So the order they appear in `data.json` influences which page will get matched first. And that result is cached.

Further complicating matters, say we navigate the browser to `/page`. That results in `findPage` being initialized with an array of 1 page (`/page`), which is pulled from the `window.page` object. Therefore, if we call findPage for `/page/` immediately (e.g as a result of a `Link` mounting), before the `data.json` arrives in the browser, then it will match against `/page` as well. I.e, it won't even have a chance to match against the other pages in the pages-manifest.

Since the behavior is non-deterministic depending on browser/network speed, I think at the very least, we should warn the user if they are creating a page which has the same path as an existing page, except with(out) a trailing slash.

## Related Issues

- https://github.com/gatsbyjs/gatsby/issues/11871

**Comment by feychenie** [comment]
Actually, during development when a rebuild is a trigger by a file save, this triggers a warning for every path that gets it's trailing slash removed by this documented tip (and the related plugin):
https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#removing-trailing-slashes

![Screenshot 2019-04-24 at 14 48 59](https://user-images.githubusercontent.com/277455/56660635-374b6800-66a0-11e9-9035-a580ea917760.png)
