### ISSUE TITLE
Very unstable work https://www.gatsbyjs.org/

### ISSUE THREAD

**Issue by agvo1kov** [gatsbyjs/gatsby#13466]
Hello Gatsby-Team!
I can't use the site of the project for learning Gatsby because often it's not available. I just began learning. I tried to open the site a few times on week, but every time my learning was interrupted because of infinite next page loading.

Hope, you will solve the problem soon. Thank you,

**Comment by DSchau** [comment]
Hello!

@agvolkov5 I'm not really sure what you're referring to--could you provide more detail? We don't really have "infinite loading" on gatsbyjs.org.

**Comment by agvolkov5** [comment]
I am seeing the following picture: [https://www.youtube.com/watch?v=YqPmeod0Rkw](https://www.youtube.com/watch?v=YqPmeod0Rkw)
Even the main page maybe not opening.

**Comment by DSchau** [comment]
This is super strange! It appears that the pre-loading is timing out.

Could you perhaps have any network issues? Very slow network? (e.g. try fast.com and let us know what your dl/up speed is!)

**Comment by agvolkov5** [comment]
Now my dl is 5.1 Mbps and up is 530 Kbps.
But I tried to connect to another network (about 30 Mbps dl and up), but it didn't influence the stability of the site's work.
From time to time the site works wonderfully, but usually, it does not last long.

**Comment by thecodingaviator** [comment]
I believe this might be due to some restriction that the ISP or your network if you're on a work network or such has enforced. Besides, I think that cloning the repo is ~400 or so MB so the request may time out sometimes

**Comment by agvo1kov** [comment]
I began to use a VPN and it solved the problem. And my network is not a work network. I tried to use different networks.

**Comment by thecodingaviator** [comment]
In that case, I believe it is a problem on the client side browser application rather than something we can fix. Thanks for opening this issue, I’m closing this, if you want it to be reopened, please add further clarification. Happy coding!
