### ISSUE TITLE
Landing Page duplicate category on Showcase

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#13479]
Someone made 2 categories in Showcase - [Landing page](https://www.gatsbyjs.org/showcase/?filters%5B0%5D=Landing%20page) & [Landing Page](https://www.gatsbyjs.org/showcase/?filters%5B0%5D=Landing%20Page).

Also, there's a little jankiness when I unselect one & select another category :)

**Comment by danielbayerlein** [comment]
@deadcoder0904 I'll check it out.
