### ISSUE TITLE
Further document End to End Testing page

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13473]
## Summary

The [End To End Testing page](https://www.gatsbyjs.org/docs/end-to-end-testing/) has some content about setting up Cypress with Gatsby, but I think it would also be useful to describe writing E2E tests explicitly and write some examples for it. As well maybe add some stuff for accessibility as was done in the stream today with Jason and Marcy.

cc: @marcysutton

**Comment by marcysutton** [comment]
love that idea! We incorporated [cypress-axe](https://github.com/avanslaars/cypress-axe) and wrote a keyboard test for a clickable span. If you or someone wants to take this on, that would be fantastic! @jlengstorf do you have the files from today's livestream (and the Youtube link, whenever you upload it)?

**Comment by KartSriv** [comment]
@marcysutton I'll take this ASAP after @jlengstorf provides us with the Livestream files.

**Comment by lannonbr** [comment]
Feel free to go ahead and assign yourself to this issue @KartSriv. For issues I want to tackle I assign myself but if you are interested in working on this I am all for it 👍

**Comment by jlengstorf** [comment]
@KartSriv files are at https://github.com/jlengstorf/a11y-testing

Thanks!

**Comment by KartSriv** [comment]
Sorry, @jlengstorf! Missed your response in the cluttered notifications. I'll take this issue but give me some time cause I am AFK for the next couple of days. I think @marcysutton is referring to this live stream: https://www.youtube.com/watch?v=IADSsClWVtA I'll just see it and add more stuff to the E2E doc. Thanks - Karthik Srivijay 

PS: Sorry for the delay for both following up this issue and fixing these issues later

**Comment by jlengstorf** [comment]
Hey, @KartSriv! I can see you're still busy, according to GitHub, so I'm going to label this one as available for someone to pick up. If you find free time and it's still unclaimed, we'd love to have your help!

**Comment by bendtherules** [comment]
Hi,
I would like to work on this documentation.

**Comment by MarkosKon** [comment]
I can work on this.

**Comment by phacks** [comment]
This issue seems resolved as far as I can tell, can we close it?

**Comment by marcysutton** [comment]
Yep, thanks @phacks!
