### ISSUE TITLE
Wrong link to Accessibility in Gatsby Themes

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#13480]
Go to https://www.gatsbyjs.org/docs/themes/introduction/.

Under https://www.gatsbyjs.org/docs/themes/introduction/#why-does-this-matter, click on the accessibility link, it redirects to 404.

It should link to https://www.gatsbyjs.org/docs/themes/building-themes/#make-it-accessible-by-default

**Comment by KartSriv** [comment]
Thanks, @deadcoder0904! I just fixed it. Please wait for the reviewers to accept the proposed change.
