### ISSUE TITLE
[1.0] Static assets are timing out

### ISSUE THREAD

**Issue by levibuzolic** [gatsbyjs/gatsby#1348]
Noticed the latest beta (6) seems to have broken static assets in development mode.

I've created a super basic example site here: https://github.com/levibuzolic/gatsby-test-site/tree/broken-static-assets

Seems like assets in the public directory aren't resolving anymore and just time out after ~2mins. However assets that are part of the bundle and are copied into `public/static` by gatsby seem to be working.

You can see the endlessly loading image in this screenshot:

![image](https://user-images.githubusercontent.com/721323/27778637-d911ac70-5fff-11e7-8aaa-85d6c11342c5.png)

**Comment by levibuzolic** [comment]
Tried digging around recent commits and the only potentially related change I've managed to spot is: #1332

**Comment by KyleAMathews** [comment]
Oh drat, I think it was this commit actually — https://github.com/gatsbyjs/gatsby/pull/1324/files

I think I forgot to call next(). Could you test that and if is the fix, add a PR?

**Comment by KyleAMathews** [comment]
(and thanks for the nice clean reproduction site! That's super helpful)

**Comment by levibuzolic** [comment]
@KyleAMathews ah thanks I'll give that a go.

**Comment by levibuzolic** [comment]
That was exactly it, thanks @KyleAMathews -- PR is up.

**Comment by levibuzolic** [comment]
Fixed in #1349
