### ISSUE TITLE
[docs] Adding Free Swag information in the README

### ISSUE THREAD

**Issue by KartSriv** [gatsbyjs/gatsby#13495]
### Adding Free Swag information in the README

Giving a gist about the free Gatsby Swag can encourage the open source community to contribute. I think we can just include a few lines from https://www.gatsbyjs.org/contributing/contributor-swag/.

**Comment by KartSriv** [comment]
**There you go https://github.com/gatsbyjs/gatsby/pull/13496**

**Comment by DSchau** [comment]
Hello @KartSriv!

We've closed the accompanying pull request (#13496) in the interest of keeping our README focused and pertinent, so we'll do the same here.

Thanks for opening this issue and for working on a contribution towards the Gatsby ecosystem!
