### ISSUE TITLE
Make a custom directory accessible to GatsbyJS for development and build

### ISSUE THREAD

**Issue by insmac** [gatsbyjs/gatsby#13503]
I have GatsbyJS set up within a large monorepo with two different builds using a shared components set. The structure is as following:

```
src/
    /assets
        /images
    /gatsby-site
    /other-site
    /shared
gatsby-{config,node,etc.js}
package.json
...
```
The issue is this: I can access the `shared` components directory to import and use React components and logic in both GatsbyJS site and other site (native React) just fine, only that they contain images with src using a regular `src=/assets/images/...` tag, not ES6 imports.  Obviously, they won't work in both development or built version in the Gatsby site. 

What's the easiest solution to 1) make the `assets` directory visible to Gatsby and 2) copy these files (preferably only the used ones...) to `static` folder in the built version?

Best,
Maciek

**Comment by pieh** [comment]
Not ideal, but we copy files from `<project-root>/static` to public directory, so it would be worth checking setup when symlink is created:
`<project-root>/static/assets -> <project-root>/src/assets`, so those would be automatically copied.

Other option is to copy files there as part of build step - either in npm script or in `gatsby-node` - i.e.:
```
const fs = require(`fs`)
const path = require(`path`)

exports.onPostBootstrap = () => {
  fs.copySync(path.join(process.cwd(), "src", "assets", path.join(process.cwd(), `public`, "assets"))
}
```
(it won't watch for files and copy new one during `gatsby develop` tho)
