### ISSUE TITLE
NetlifyCMS admin page 404's instead of displaying

### ISSUE THREAD

**Issue by leeandher** [gatsbyjs/gatsby#13501]
## Description

For some reason, my local NetlifyCMS instance isn't showing up on the `/admin/` page.
I recently updated from Gatsby `v2.2.8` to `v2.3.25` and I'm not sure if that has something to do with it.

This also may be a NetlifyCMS issue, but that entirely depends on the `config.yml` file, and will throw an error if it has any errors in it, it seems to work fine in the printout below.

### Steps to reproduce

Run `gatsby develop` on my [project](https://github.com/leeandher/leander.xyz/tree/dev)
<details>
<summary>The printout</summary>
<pre><code>&gt; gatsby develop

success open and validate gatsby-configs — 0.010 s
success load plugins — 0.880 s
success onPreInit — 0.004 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success initialize cache — 0.041 s
success copy gatsby files — 0.140 s
success onPreBootstrap — 0.012 s
success source and transform nodes — 0.263 s
success building schema — 0.227 s
success createPages — 0.094 s
success createPagesStatefully — 0.097 s
success onPreExtractQueries — 0.000 s
success update schema — 0.021 s
success extract queries from components — 0.151 s
success run static queries — 0.001 s
⠁ code block language not specified in markdown. applying generic code block
⠄ run page queries — 4/65 42.56 queries/secondunable to find prism language 'env' for highlighting. applying generic code block
⠄ run page queries — 37/65 59.93 queries/secondunable to find prism language 'txt' for highlighting. applying generic code block
success run page queries — 0.865 s — 65/65 75.17 queries/second
success write out page data — 0.009 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.110 s

info bootstrap finished - 6.34 s

 DONE  Compiled successfully in 2588ms                                                                                                      11:35:20 AM

You can now view leander.xyz in the browser.

  http://localhost:8000/

View GraphiQL, an in-browser IDE, to explore your site's data and schema

  http://localhost:8000/___graphql

Note that the development build is not optimized.
To create a production build, use npm run build

i ｢wdm｣:
i ｢wdm｣: Compiled successfully.
 DONE  Compiled successfully in 5859ms                                                                                                      11:35:24 AM

 DONE  Compiled successfully in 5859ms                                                                                                      11:35:24 AM

 I  Netlify CMS is running at http://localhost:8000/admin/
</code>
</pre>
</details>

### Expected result

The `/admin/` page should show my local NetlifyCMS confg

### Actual result

The `/admin/` page 404's instead

### Environment

```
System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - ~\AppData\Roaming\npm\npm.CMD
  Languages:
    Python: 3.6.2 - /c/Users/leand/AppData/Local/Programs/Python/Python36/python
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: 2.3.25 => 2.3.25
    gatsby-plugin-manifest: 2.0.24 => 2.0.24
    gatsby-plugin-netlify-cms: 3.0.9 => 3.0.9
    gatsby-plugin-nprogress: 2.0.10 => 2.0.10
    gatsby-plugin-offline: 2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: 3.0.8 => 3.0.8
    gatsby-plugin-sitemap: 2.0.12 => 2.0.12
    gatsby-plugin-styled-components: 3.0.4 => 3.0.4
    gatsby-remark-prismjs: 3.2.8 => 3.2.8
    gatsby-source-filesystem: 2.0.26 => 2.0.26
    gatsby-transformer-remark: 2.1.17 => 2.1.17
```

**Comment by pieh** [comment]
Please bump `gatsby-plugin-netlify-cms`. It was fixed in `gatsby-plugin-netlify-cms@3.0.18`
