### ISSUE TITLE
SW registration fails when custom pathPrefix is used

### ISSUE THREAD

**Issue by dennismorello** [gatsbyjs/gatsby#13506]
## Description

When `pathPrefix` is set in `gatsby-config.js`, the service worker fails to be registered.

### Steps to reproduce

- Set the `pathPrefix` in `gatsby-config.js` to a non-empty string (let's say `"xyz"`)
- Generate the static site with `gatsby build --prefix-paths`
- Upload the generated content to your server and access it from `yourdomain.com/xyz`

The service worker registration fails because `sw.js` is not found.

### Expected result

The script tries to register the service worker located at `/xyz/sw.js`.

### Actual result

The script tries to register the service worker located at `/xyz/sw.js/sw.js` because `__PATH_PREFIX__` variable has a value of `"/xyz/cw.js"` instead of just `"/xyz"`.

### Environment

```
System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 66.0.3
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.16 => 2.3.25 
    gatsby-image: ^2.0.37 => 2.0.39 
    gatsby-plugin-manifest: ^2.0.28 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.32 => 2.0.35 
    gatsby-source-filesystem: ^2.0.29 => 2.0.29 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.18 
  npmGlobalPackages:
    gatsby-cli: 2.4.16
```

**Comment by pieh** [comment]
I just tried this and it does work here. I think we need more information on this

**Comment by pieh** [comment]
Can you provide [Reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)?

**Comment by dennismorello** [comment]
Hi Michal,

I think the issue is related to my web server configuration and not to Gatsby, but I need to do further investigations.

We can close this issue for now.



Thank you.
