### ISSUE TITLE
How to localize content using gatsby-source-drupal

### ISSUE THREAD

**Issue by violabg** [gatsbyjs/gatsby#13517]
I need to build a site that supports both English and Italian content, using gatsby-source-drupal, I’m having problems since filtering by languageCode doesn’t work.

**Comment by pieh** [comment]
Hey @violabg - could you expand on this? Ideally create minimal reproduction case ( https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/ ) so we could take a look at that.

**Comment by violabg** [comment]
it looks like Drupal jsonapi can't be filtered by setting languageCode on querys, but you need separate entry points, one for each language, that you want to localize.

https://github.com/gatsbyjs/gatsby/issues/10020

I'm not sure how to implement that

**Comment by pieh** [comment]
Thanks for bringing related issue. I'm pretty sure it wasn't fixed and issue was closed due to being "stale". So same things apply what was mentioned there

> One other problem that I see, is how would you retrieve Drupal available languages?

I'm not sure how to approach that - we are mostly consumers of Drupal APIs and if there is no API that we could use to fetch available languages, users would need to specify them manually :(

**Comment by back-2-95** [comment]
Hello, looking into these issues with multilingual Drupal (for reference almost all our Drupal projects are multilingual).

In #10020 there was proposed solution: https://github.com/gatsbyjs/gatsby/issues/10020#issuecomment-440484969

But how to do that? Can I somehow "patch" gatsby-source-drupal ?

Or can I modify jsonapi output for creating language-aware-id for gatsby-source-drupal?

**Comment by back-2-95** [comment]
@pieh I could arrange public API exposed for testing this...

**Comment by back-2-95** [comment]
Linking also a related comment from Drupal.org issue https://www.drupal.org/project/jsonapi/issues/2794431#comment-12928528
