### ISSUE TITLE
Error adding Redux Store to Gatsby

### ISSUE THREAD

**Issue by Frost0x** [gatsbyjs/gatsby#13518]
Using this [article ](https://medium.freecodecamp.org/how-to-get-started-with-gatsby-2-and-redux-ae1c543571ca), I created the Redux Store, from myself I connected redux-dev-tools, but for some reason, this design does not work. 

I read other questions and found that this is a common problem, but I did not find a working solution.

Could you tell me, please, whether it is possible to solve this problem?
If the problem cannot be solved, what can be used as a replacement for Redux (preferably other than React State)?

[Project](https://github.com/Frost0x/WQ-Gatsby)

[Img 1](https://ibb.co/4YSWktX)
[Img 2](https://ibb.co/WPkNw52)

`
Project:
- gatsby-browser.js
- gatsby-ssr.js
   - src
      - store
         - App.js
         - RootReducers.js
         - ReduxWrapper.js
`

`
// App.js
const initialState = { isDarkMode : false }

export default function App(state = initialState, action) {
    if (action.type === 'TOGGLE_DARKMODE') {
        return {
            ...state,
            isDarkMode: action.payload
        }
    }
    return state
}`

`
// RootReducers.js
import { combineReducers } from 'redux'
import App from './App'

export default () => combineReducers({
    App
})`

`
// ReduxWrapper.js
import React from 'react';
import { Provider } from 'react-redux';
import { createStore, compose } from 'redux';
import rootReducer from './RootReducers';

const composeEnhancers = typeof window === 'object' && window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : compose;

const store = preloadedState => createStore(rootReducer, preloadedState, composeEnhancers)

export default ({element}) => <Provider store={store}>{element}</Provider>`

`
// gatsby-browser.js & gatsby-ssr.js

export { default as wrapRootElement } from './src/state/ReduxWrapper';
`

**Comment by universse** [comment]
seems like for RootReducers.js, you need to
```javascript
export default combineReducers({
  App
})
```
instead of exporting the function

**Comment by Frost0x** [comment]
> seems like for RootReducers.js, you need to
> 
> ```js
> export default combineReducers({
>   App
> })
> ```
> 
> instead of exporting the function

I changed the Reducer, unfortunately, it did not help.
I created a repository with this project: [WQ-Gatsby](https://github.com/Frost0x/WQ-Gatsby)

**Comment by universse** [comment]
Oh, also for ReduxWrapper
```javascript
const store = preloadedState => createStore(rootReducer, preloadedState, composeEnhancers)
```
This is a function.
You should do something like this instead.
```javascript
const createReduxStore = (preloadedState = {}) => createStore(rootReducer, preloadedState, composeEnhancers)
const store = createReduxStore()
// rest of code
```

**Comment by Frost0x** [comment]
Your decision helped me.
Thank You very much for your help!
