### ISSUE TITLE
Welcome message in the Gatsby CLI

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#13511]
## Summary
We've seen some CLI's do this, and it could be nice!

## Details

```shell
npm install -g gatsby-cli
Success!
Welcome to the Gatsby CLI! Please visit https://www.gatsbyjs.org/docs/gatsby-cli/ for more information.

Usage: gatsby <command> [options]

Commands:
  gatsby develop                   Start development server. Watches files,
                                   rebuilds, and hot reloads if something
                                   changes
  gatsby build                     Build a Gatsby project.
  gatsby serve                     Serve previously built Gatsby site.
  gatsby info                      Get environment information for debugging and
                                   issue reporting
  gatsby clean                     Wipe the local gatsby environment including
                                   built assets and cache
  gatsby repl                      Get a node repl with context of Gatsby
                                   environment, see (add docs link here)
  gatsby new [rootPath] [starter]  Create new Gatsby project.
  gatsby telemetry                 Enable or disable Gatsby anonymous analytics
                                   collection.

Options:
  --verbose                Turn on verbose output     [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output
                                                      [boolean] [default: false]
  -h, --help               Show help                                   [boolean]
  -v, --version            Show version number                         [boolean]
```

## Motivation
Some other docs have really great CLI documentation, and we could use a welcome message to both communicate success to Gatsby users and point them to the documentation about the CLI. #12951. Thanks and fyi @DSchau @jamo @KyleAMathews @sidharthachatterjee

**Comment by deepakchethan** [comment]
Hello, If this is issue is still not taken I would like to work on this.

**Comment by anamritraj** [comment]
I am currently working on this and would create a PR soon. 
Will update the thread with PR#.

**Comment by wardpeet** [comment]
Regular npm install on a project doesn't show anything which is 👌
<details>
<summary>npm install gatsby@cli-postinstall</summary>

![image](https://user-images.githubusercontent.com/1120926/65496728-4a659c80-deb9-11e9-9a0c-a57bdffb9f2a.png)
</details>

<details>
<summary>npm install -g gatsby-cli@cli-postinstall</summary>

![image](https://user-images.githubusercontent.com/1120926/65496881-96184600-deb9-11e9-8783-522700e60782.png)
</details>

<details>
<summary>yarn add gatsby@cli-postinstall</summary>

![image](https://user-images.githubusercontent.com/1120926/65497170-0de67080-deba-11e9-9840-bb5cfd61b288.png)
</details>

<details>
<summary>yarn global add gatsby-cli@cli-postinstall</summary>

![image](https://user-images.githubusercontent.com/1120926/65497373-6f0e4400-deba-11e9-822e-fb0bedf6b286.png)

</details>

<details>
<summary>npx gatsby-cli@cli-postinstall</summary>

![image](https://user-images.githubusercontent.com/1120926/65497940-59e5e500-debb-11e9-8478-367741c9b50d.png)
</details>
