### ISSUE TITLE
How to remove the line 'This app works best with JavaScript enabled.'

### ISSUE THREAD

**Issue by huynhminhtufu** [gatsbyjs/gatsby#13514]
## Summary

When I disable Javascript on the browser, the Gatsby site display the line 'This app works best with JavaScript enabled.', everything else are working fine. How can I remove this line from gatsby?

```
<noscript id="gatsby-noscript">This app works best with JavaScript enabled.</noscript>
```

## Relevant information

None

### Environment (if relevant)
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /Users/tuhuynh/.pyenv/shims/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 65.0.1
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.25 => 2.3.25 
    gatsby-image: ^2.0.39 => 2.0.39 
    gatsby-plugin-feed: ^2.1.1 => 2.1.1 
    gatsby-plugin-google-analytics: ^2.0.18 => 2.0.18 
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-remark-copy-linked-files: ^2.0.11 => 2.0.11 
    gatsby-remark-emojis: ^0.3.2 => 0.3.2 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-remark-prismjs: ^3.2.8 => 3.2.8 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.29 => 2.0.29 
    gatsby-transformer-remark: ^2.3.8 => 2.3.8 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18 
  npmGlobalPackages:
    gatsby-cli: 2.5.9

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by c0b41** [comment]
@huynhminhtufu follow up [Customizing html.js](https://www.gatsbyjs.org/docs/custom-html/)

**Comment by LekoArts** [comment]
You can use CSS with `display: none` on the `#gatsby-noscript`. That’s why the id is there :)

Closing this issue as answered 👍🏻
