### ISSUE TITLE
warnings from old version of workbox

### ISSUE THREAD

**Issue by dsvensson** [gatsbyjs/gatsby#13525]
Using the offline plugin:

`warning gatsby-plugin-offline > workbox-build > joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).`

offline plugin package.json:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-offline/package.json#L9-L15

The latest version is 4.3:

https://github.com/GoogleChrome/workbox/releases/tag/v4.3.0

**Comment by pieh** [comment]
Deprecated packages don't stop working. Ideally we use newer dependencies, but using older (but working) ones is OK too.
