### ISSUE TITLE
CLI Design Discussion

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/gatsby#13537]
## Summary

There has been lots of discussion lately around improvements to be made to the CLI. More specifically in adding and modifying commands. These are great additions that will benefit developers of Gatsby, but I'm concerned without some high level guidance and CLI design thought that the CLI might quickly become confusing and not maintainable. Ultimately this might require a major version bump and rewrite (i.e. major CLI API changes). I think if we can address these design issues now we might get away with a much simpler major version bump(i.e. minimal breaking CLI API changes) or avoid one all together (i.e. no breaking CLI API changes).

I'm thinking if we can layout a grand design for the CLI then we can make sure these PRs and issues have specific commands they should be linked to. @shannonbux Do you already have something like this? Do we have anything record of all the commands that we'd _like_ to add that we can use to do this? If not, maybe we can start with compiling that list.

Note: I

## Relevant information

#13450 & #10294 are both in contention for the same CLI command and will conflict.

#13376
#13450
#11500
#10385

*Any CLI Issues or PRs:*
https://github.com/gatsbyjs/gatsby/issues/13511
https://github.com/gatsbyjs/gatsby/issues/13512
https://github.com/gatsbyjs/gatsby/issues/13377
https://github.com/gatsbyjs/gatsby/pull/12822

CC: @gatsbyjs/core

**Comment by pieh** [comment]
Thanks Alex for putting this "epic" issue together.

Shannon is doing series of interviews with users this week, so we don't work on design part yet as first we need to get as much information as we can to inform design process.

**Comment by shannonbux** [comment]
Hi @moonmeister and thanks for surfacing these valid concerns! I'm putting together an RFC as we speak and will include this information you've gathered. Will ping you when that RFC is ready

**Comment by moonmeister** [comment]
@shannonbux I should have known you would be on top of things! I was talking with @sidharthachatterjee yesterday about getting #10294 merged soon. Should we hold off for the RFC process to be complete?

**Comment by shannonbux** [comment]
Hi @moonmeister, thanks for your patience! I think #10294 is fine to merge
- it matches up nicely with plans for the CLI! So it's up to the core team,
from my perspective!
