### ISSUE TITLE
Alias `--with-prefix` to `--prefix-paths`

### ISSUE THREAD

**Issue by jaredsilver** [gatsbyjs/gatsby#13549]
I don't know about everyone else, but I make this mistake all the time. `--with-prefix` feels like a more natural way to say this.

**Comment by frinyvonnick** [comment]
I made a PR for this 😄

**Comment by wardpeet** [comment]
It's how you would read this 😛 . --prefix-paths actually tells we add prefix to paths, with-prefix does not.

It's probably better to make sure we show you a message like --prefix-paths not found, you probably mean --with-prefix. We have a https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/did-you-mean.js but I'm unsure how it actually works

**Comment by jaredsilver** [comment]
It’s not necessarily just paths that are being prefixed now though. It could also be assets.

**Comment by sidharthachatterjee** [comment]
> It’s not necessarily just paths that are being prefixed now though. It could also be assets.

@jaredsilver While I understand that this can be confusing, I don't think this is a valuable addition because:
- This could be solved by better documentation
- Added aliases will need to be maintained till the next breaking version (and best to avoid API surface bloat)

What do you think?

**Comment by jaredsilver** [comment]
Sorry, I should clarify that the way that I read this is "gatsby build with prefix" which makes sense as an English sentence whereas "gatsby build asset prefix" does not. If others don't have this same issue, then it's not really a problem. I'll close the issue.
