### ISSUE TITLE
Strongly typed GraphQL queries

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#13546]
## Summary

Currently, the only option available to check for invalid GraphQL queries is through [eslint-plugin-graphql](https://github.com/apollographql/eslint-plugin-graphql) by using [gatsby-plugin-extract-schema](https://www.gatsbyjs.org/packages/gatsby-plugin-extract-schema/).

It would be nicer if static types could be generated with [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator) during builds (even in development), extending a pre-defined interface (inside `node_modules`) through a file inside the `.cache` folder with [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) instead of [using `any`](https://github.com/gatsbyjs/gatsby/blob/fa6e327eaa619b663f97ff220cd9bb84e4259354/packages/gatsby/index.d.ts#L24) in the type definitions of query-related methods.

### Motivation

Static typing is gaining traction amongst frontend developers. A previous issue (#2374) has a partial solution for typed GraphQL queries, but proper support has yet to be built into the core of Gatsby.

**Comment by orta** [comment]
The [under-the-hood](https://github.com/gatsbyjs/gatsby/blob/5078f03027c868554111f48fbd5d685c403a9fdd/packages/gatsby/src/query/query-compiler.js#L7-L9) relay-compiler should have enough knowledge to generate for them for you (similar to how we build React apps ([query](https://github.com/artsy/emission/blob/1183c139191b9557724e386dfae7caada1cc55e1/src/lib/Scenes/Settings/MyProfile.tsx#L127-L134) - [types](https://github.com/artsy/emission/blob/1183c139191b9557724e386dfae7caada1cc55e1/src/__generated__/MyProfile_me.graphql.ts#L3-L10) with Relay )

**Comment by orta** [comment]
Also, @damassi explored this idea in https://github.com/damassi/gatsby-plugin-emit-graphql-types/

It's a [pretty simple concept](https://github.com/damassi/gatsby-plugin-emit-graphql-types/blob/master/gatsby-node.js#L31-L71) - but would need to know what are the extra fragments that particular plugins are adding to queries to reflect the types accurately.

**Comment by LekoArts** [comment]
I'll close this in favor of https://github.com/gatsbyjs/gatsby/issues/18983
