### ISSUE TITLE
How can I use different set of gatsby.config.js plugins for dev, staging and production environments?

### ISSUE THREAD

**Issue by JustFly1984** [gatsbyjs/gatsby#13551]
For all of our gatsby.js projects, we are using at least 3 environments, and the typescript.

Is there a way to use unique set of plugins, or even different gatsby.config/node/ssr js depending on ENV variable?

**Comment by KyleAMathews** [comment]
You can add/remove plugins and node/SSR code depending on the environment as it's all JavaScript.

**Comment by KyleAMathews** [comment]
You can access env variables at `process.env.MYVAR`

**Comment by wardpeet** [comment]
@JustFly1984 we have an env variable just for that called `GATSBY_ACTIVE_ENV` (more info: https://www.gatsbyjs.org/docs/environment-variables/#additional-environments-staging-test-etc). It will still put NODE_ENV=production when running gatsby build so your site is minfied and everything but it will read different .env files from disk. You can also use it directly in code as @KyleAMathews described.

does this make sense?

**Comment by cekujin** [comment]
In addition to the question of the author, is it also possible to run a build version using a staging environment?
