### ISSUE TITLE
useStaticContext custom hook with contentful throws error

### ISSUE THREAD

**Issue by adamwade2384** [gatsbyjs/gatsby#13573]
# Code

```
import { useStaticQuery, graphql } from "gatsby"

export const useNavigationData = () => {
  const { allContentfulNavigation } = useStaticQuery(
    graphql`
      query {
        allContentfulNavigation{
          edges{
            node{
              title
              links{
                title
              }
            }
          }
        }
      }
    `
  )
  return allContentfulNavigation
}
```

## Description

"Error: The result of this StaticQuery could not be fetched."

### Steps to reproduce

1.) Create a contentful account
2.) Connect Gatsby to the contentful source
3.) Write a custom hook using useStaticQuery that connects to contentful data
5.) Log the result from the hook in any component or page

### Expected result

The data should be fetched.

### Actual result

The data was not fetched.

### Environment

System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.3.25 => 2.3.25 
    gatsby-image: ^2.0.39 => 2.0.39 
    gatsby-plugin-google-analytics: ^2.0.18 => 2.0.18 
    gatsby-plugin-i18n: ^0.4.2 => 0.4.2 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
    gatsby-source-contentful: ^2.0.50 => 2.0.50 
    gatsby-transformer-remark: ^2.3.8 => 2.3.8 
  npmGlobalPackages:
    gatsby-cli: 2.5.9

**Comment by pieh** [comment]
Where in your project do you make this query? Gatsby will not extract queries outside of `<project-root>/src` directory.

**Comment by adamwade2384** [comment]
Thanks for the quick response @pieh! I placed my 'hooks' folder at the same level as src by mistake. I'm no longer receiving the error. Cheers!
