### ISSUE TITLE
Image blur-up on every page load

### ISSUE THREAD

**Issue by pawelotto** [gatsbyjs/gatsby#13575]
After checking the docs I don't see any solution to my problem where the logo on [travelem.com](https://travelem.com/en-us) gets blurred-up on every page load. 
Any suggestion how to fix this?

**Comment by nephlin7** [comment]
Hi @pawelotto, have you checked this link? https://www.gatsbyjs.org/packages/gatsby-image/
<img width="770" alt="Captura de pantalla 2019-04-23 a la(s) 2 28 15 p  m" src="https://user-images.githubusercontent.com/22168189/56613569-26cdbb80-65d4-11e9-8f0c-487da3657760.png">
