### ISSUE TITLE
[Sharp] Nodejs 12 API makes gatsby broken

### ISSUE THREAD

**Issue by ThomasT404** [gatsbyjs/gatsby#13588]
## Description

Since I have updated nodejs 11 to nodejs 12 some packages don't build anymore surely because of the new native APIs.

Examples :
> \node_modules\sharp\src\pipeline.cc(417): error C3861: 'RemoveExifOrientation'
> \node_modules\sharp\src\pipeline.cc(436): error C3861: 'ApplyAlpha'

etc...

### Steps to reproduce

-Install Nodejs12
-gatsby new nodejstest

And wait for it

### Expected result

A normal installation

### Actual result

A bug caused by the incompatibility with the new API

### Environment

> System:
>     OS: Windows 10
>     CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor         
>   Binaries:
>     Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>     npm: 6.9.0 - C:\Users\Thomas\AppData\Roaming\npm\npm.CMD
>   Languages:
>     Python: 3.7.3
>   Browsers:
>     Edge: 44.17763.1.0
>

**Comment by pieh** [comment]
See https://github.com/lovell/sharp/issues/1668 - this is 2 part issue:
 1. upstream - sharp maintainer mentioned this will be fixed in `sharp@0.22.1` (which is not yet released)
 2. in here we will need to update sharp dependencies in few packages
