### ISSUE TITLE
Using createPage where GraphQL API (DatoCMS) sets a limit on records returned

### ISSUE THREAD

**Issue by jonlay** [gatsbyjs/gatsby#13589]
## Summary

I'm trying to build a medium-sized blog (about 150 posts), where all content is hosted within DatoCMS.

DatoCMS's GraphQL content API enforces a limit of 100 records per response, meaning that I need to use their [pagination parameters](https://www.datocms.com/docs/content-delivery-api/pagination) to access the second group of 50 posts which are not returned in the first query.

I'm unsure of how to modify the (working) code below to successfully build pages for the remaining posts - i.e. how I can combine multiple GraphQL queries before I run the `forEach` loop to build the pages.

## Relevant information

I'm on the latest version of Gatsby, so this is more of a procedural question.

### File contents (if changed)

Here's my current `gatsby-node.js`:

````
const path = require(`path`)

exports.createPages = async ({ actions, graphql }) => {
  const { data } = await graphql(`
    query {
      dato {
        allBlogs(orderBy: [publishDate_DESC], first: 100) {
          slug
        }
      }
    }
  `)

  data.dato.allBlogs.forEach(blog => {
    actions.createPage({
      path: `blog/${blog.slug}`,
      component: path.resolve(`./src/components/templates/blog-single.js`),
      context: {
        slug: blog.slug
      }
    })
  })
}
````

**Comment by pieh** [comment]
You can continue to query `allBlogs` increasing `skip` parameter until it returns less than 100 items (meaning that there is no more items after that):

```js
const path = require(`path`)

exports.createPages = async ({ actions, graphql }) => {
  // start from 0
  let skip = 0

  const limit = 100

  // toggle to see when we should break the loop
  let keepQuerying = true

  // we will accumulate blog posts in this array
  let blogPosts = []

  while (keepQuerying) {
    const { data } = await graphql(`
      query {
        dato {
          allBlogs(orderBy: [publishDate_DESC], first: ${limit}, skip: ${skip}) {
            slug
          }
        }
      }
    `)

    // aggregate results
    blogPosts = blogPosts.concat(data.dato.allBlogs)

    // adjust "cursor" to grab next batch
    skip += limit

    // see if we need to make another query
    if (data.dato.allBlogs.length < limit) {
      // if we got less items than we asked for
      // it means we reached the end
      keepQuerying = false
    }
  }


  blogPosts.forEach(blog => {
    actions.createPage({
      path: `blog/${blog.slug}`,
      component: path.resolve(`./src/components/templates/blog-single.js`),
      context: {
        slug: blog.slug
      }
    })
  })
}
```

**Comment by jonlay** [comment]
Thanks @pieh - that's exactly what I wanted, and makes total sense. Really appreciate the pointer!
