### ISSUE TITLE
Update Style Guide to prefer shorter names for documents

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13583]
## Summary

While working on #13475, A topic came up that if we have breadcrumbs where the document titles are all long, the breadcrumbs component could become very long on a screen. A thing that could reduce this could be two things:

1) Update the Gatsby Style Guide to suggest that shorter titles are better
2) Add a new field for a short version of the title that will be used when put in the breadcrumbs.

cc: @marcysutton @shannonbux

**Comment by marcysutton** [comment]
Thanks for filing this issue, I think it all sounds very doable! Both items would be useful solutions moving forward: shorter titles would work well in both the sidebar and breadcrumbs, and the flexibility to specify a short title for the breadcrumb specifically would ease the burden on everyone.

**Comment by muescha** [comment]
i vote for 2 - short name for breadcrumbs and TOC on left side

**Comment by shannonbux** [comment]
I think doing both is a good idea, because even with infinite space, you'd still want the shortest title possible that does the job of a title - communicating the topic of the article so someone knows if they want to read it or not.

**Comment by cdtinney** [comment]
I'd be happy to pick up both solutions if possible.

**Comment by muescha** [comment]
If wenn add a short Name: in the same step Wenn can add a short teaser.

Usage: 

- as tooltip over a Link (like the preview here in at GitHub when I hover over a issue number)
- in search results
- tooltip if I hover over the left TOC

**Comment by marcysutton** [comment]
@muescha I think this issue should remain focused on supporting breadcrumbs. Tooltips are entirely different patterns that we aren't addressing here, so we should keep the scope limited if possible.

**Comment by muescha** [comment]
@marcysutton 

Just when we touch all files for a short name then we can add also the teaser in the same step. 

When a short name has a teaser then it is more easy to find a short name. that's the idea

**Comment by marcysutton** [comment]
Now that we have the breadcrumb component, the contributing docs should mention how to use a `breadcrumbTitle` to add shorter names to docs.

**Comment by marcysutton** [comment]
Closed with #16438
