### ISSUE TITLE
Removing trailing slashes like documented triggers warnings since #13470

### ISSUE THREAD

**Issue by feychenie** [gatsbyjs/gatsby#13594]
## Description

Since https://github.com/gatsbyjs/gatsby/pull/13470, removing trailing slashes as documented here https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#removing-trailing-slashes triggers warnings when pages are rebuilt after a file save.

### Steps to reproduce

- add [gatsby-plugin-remove-trailing-slashes](https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/) plugin to a project containing regular pages
- start dev mode (no warnings are triggered)
- trigger re-build by saving any file

### Expected result

No warnings should be displayed for pages that get their trailing slash removed

### Actual result

Warnings that were added in https://github.com/gatsbyjs/gatsby/pull/13470 are displayed for every page of the project

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 63.0.3
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.26 => 2.3.26 
    gatsby-image: ^2.0.30 => 2.0.39 
    gatsby-mdx: ^0.6.2 => 0.6.2 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-layout: ^1.0.12 => 1.0.14 
    gatsby-plugin-manifest: ^2.0.20 => 2.0.29 
    gatsby-plugin-offline: ^2.0.24 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.7 => 3.0.12 
    gatsby-plugin-remove-trailing-slashes: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.23 => 2.0.35 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-svg-sprite: ^2.0.1 => 2.0.1 
    gatsby-source-filesystem: ^2.0.29 => 2.0.29 
    gatsby-transformer-react-docgen: ^4.0.1 => 4.0.1 
    gatsby-transformer-sharp: ^2.1.15 => 2.1.18 

## Related

Issue #13464 and related PR #13470

**Comment by feychenie** [comment]
#13464

**Comment by Moocar** [comment]
@feychenie Thanks for reporting this. I've tried a few different sites with the latest version of gatsby and the `remove-trailing-slashes` plugin, but have been unable to reproduce this. Any chance you'd be able to create a standalone repo that reproduces the problem?

**Comment by feychenie** [comment]
@Moocar, my bad, this was actually happening on pages created programmatically in gatsby-node, where some paths used with `createPage` had trailing slashes, that wasn't visible when listing all available path to debug because this list was already processed by the plugin before printing it out (_duh_).

I also couldn't notice a difference in behavior with regular files in `pages/`, because we are using only code-generated pages. Again, my bad.

Sorry for this, I'm closing the issue and will add a warning "double check your createPage" in the plugin's doc.

**Comment by DSchau** [comment]
@feychenie please don't apologize! Thanks for opening the issue, remedying the issue, and wrapping up what the issue actually was for others! We appreciate it!! 💜

**Comment by neb-b** [comment]
I wasn't sure which issue to comment on but I'm currently seeing this too. Link with repro:
https://github.com/gatsbyjs/gatsby/issues/17373#issuecomment-866270784
