### ISSUE TITLE
How can I get custom entities in gatsby-source-drupal?

### ISSUE THREAD

**Issue by bgbohling** [gatsbyjs/gatsby#13595]
I've got Gatsby up and running and getting data from a Drupal site where I have quite a few custom (non-Node) content entities.  When I go to Explorer, it looks like I can only query on default Drupal entities like nodes, taxonomies, users, etc.  I don't see anything for my custom entities.  I've checked JSON API configuration and there's nothing there to tell JSON API to work on specific entity types.  Looking at the gatsby-source-drupal code, I see lots of returns if an item isn't a Content Type.

Is there a way to get my custom entities into Gatsby with gatsby-source-drupal?  Gatsby looks like it could be really useful, but almost everything we do with Drupal involves our own entities, not nodes.

**Comment by pieh** [comment]
I have no insight into Drupal, so can't comment on non-node entities much on Drupal side, but if JSON API would support those we definitely would look at implementing support for them in `gatsby-source-drupal`.

Is there any public Drupal instance with JSON API enabled / easy way to spin out preconfigured instance that use those so we could investigate?

**Comment by bgbohling** [comment]
I don't know of any public instances.  I could possibly try to send you some custom entity definitions, if that would help.

**Comment by bgbohling** [comment]
Not stale.  I wouldn't mind trying to help out but I need more understanding how `gatsby-source-drupal` decides what items to include.  `allData` has all the entity types, but I don't see where those are being filtered down to just nodes.  I haven't had time to look at the code in awhile, though.

**Comment by paulsheldrake** [comment]
Just wanted to follow up on this issue.  Custom entities will show but they need to be made viewable to anonymous users.
