### ISSUE TITLE
[docs] Stub list not collecting all stubs

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13590]
## Description

#13510 from @fk:

> I noticed we don't currently catch https://www.gatsbyjs.org/docs/best-practices-for-orgs/ (which is a stub, too) — I don't have the time to figure out why this happens, and I'm not sure if there are others we are missing

I believe this is due to some mishap in the findStubs method in the [stub-list.js](https://github.com/gatsbyjs/gatsby/blob/master/www/src/pages/contributing/stub-list.js) file.

**Comment by jgalat** [comment]
Hi @lannonbr! Can I take this?

**Comment by lannonbr** [comment]
Sure @jgalat. If you need any help I am here given I wrote the majority of that file, but I'm always welcome for contributors taking issues that I open up if I don't directly assign them to myself.
