### ISSUE TITLE
Globally installed Gatsby 0.8 not running

### ISSUE THREAD

**Issue by cutemachine** [gatsbyjs/gatsby#136]
I just upgraded Gatsby to the latest version. Unfortunately it is not running anymore. So, I did a fresh install, but with the same result.

This is what I get when I try to run `gatsby --version`. When I change bin/index.js from import to require I get the version number (0.8).

I am on a Mac with node.js 5.6.0.

```
/usr/local/lib/node_modules/gatsby/bin/index.js:1
(function (exports, require, module, __filename, __dirname) { import program from 'commander'
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/gatsby/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby/bin/cli.js:4:1)
    at Module._compile (module.js:434:26)
```

PS: Many thanks for your great work. I love Gatsby.

**Comment by gesposito** [comment]
Can confirm this on my machine (Node 4.3.1).
I was able to get Gatsby 0.8 working (`link`ed) by adding `webpack-hot-middleware`.

**Comment by KyleAMathews** [comment]
These are two separate problems. @gesposito I merged your missing dependency and I just added a commit (https://github.com/gatsbyjs/gatsby/commit/f8edc05670fdddb052d457eb562c2165dc478784) to restore the `/bin` code to not use the import syntax.

Gah, got to get integration tests running on Travis (PRs accepted :D)

**Comment by KyleAMathews** [comment]
Just published 0.8.1. If you two could verify this version works and report back here that'd be great!

**Comment by gesposito** [comment]
Cool, 0.8.1 works globally installed.

**Comment by KyleAMathews** [comment]
Ok, try again.

**Comment by KyleAMathews** [comment]
(and thanks for the quick testing)

**Comment by gesposito** [comment]
0.8.2: `Error: Cannot find module 'cssnano'`
it also happened on 0.8.0 but I didn't push the dependency cause it looked fixed after `webpack-hot-middleware`

**Comment by KyleAMathews** [comment]
Ok, just added it and am publishing 0.8.3. Good thing versions are cheap :dancers:

**Comment by gesposito** [comment]
Cool, 0.8.3 is good to go! (for me) :smile:

**Comment by KyleAMathews** [comment]
Yeah! :fireworks: Now nap then prepare my talk on Gatsby for tomorrow's ReactConf

**Comment by gesposito** [comment]
Looking forward to hear your lightning talk! Good luck :)
