### ISSUE TITLE
[docs] Current page not always in view in sidebar when navigating around docs

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13602]
just a side note: when i jump to a doc then in the doc hierarchy is bolded. 

but i miss here that the bolded selected doc is also moved to be visible area. i always need to scroll down to find the bolded text

_Originally posted by @muescha in https://github.com/gatsbyjs/gatsby/issues/13475#issuecomment-486307738_

**Comment by lannonbr** [comment]
I agree with @muescha that it can be stressful when a page that is not immediately visible in the sidebar when you navigate to it from another page. Is there a way we can scroll the sidebar down so the page is in view?

**Comment by marcysutton** [comment]
I also agree! Fixing the scrolling and expanding of the sidebar would improve things a lot.

**Comment by cdtinney** [comment]
I'd be happy to pick this up if possible.

**Comment by kevee** [comment]
I'd like some feedback on #17447, should we scroll just on initial page load, or every time the user navigates within the docs site?

**Comment by muescha** [comment]
Ich would expected always. 

For example if i click on a link to a different section I like to see other topics of this subtopic then if would be fine if I see this in the Sidebar

Also I would expect to see the next 1(or2) items in the Sidebar. Best way if the current selected is in the middle
