### ISSUE TITLE
Extract logic for watching a directory from gatsby-page-creator so can reuse for custom page creation

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#13606]
[This PR](https://github.com/gatsbyjs/gatsby/pull/10960) suggested adding custom validation and path manipulation to gastby-plugin-page-creator. In general we don't want to complicate plugin interfaces much. It's a better pattern to extract out logic into libraries that can be reused in multiple plugins or in a site's gatsby-node.js.

So this PR is around creating a separate library (it would be a package here in this repo) that extracts out the various bits of logic from gatsby-plugin-page-creator in a way that makes them reusable & overridable.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-page-creator/src/gatsby-node.js

E.g. the library could export a few functions for:
- watching a directory
- validating paths
- creating the page object

Then someone that wants to create pages for a site but use their own custom logic could use the library to do so.

**Comment by frinyvonnick** [comment]
I would like to work on this issue 😄

**Comment by frinyvonnick** [comment]
I named the package `gatsyb-page-helper`. Sounds good to you @KyleAMathews ?

**Comment by wardpeet** [comment]
`gatsby-page-utilities` maybe?

Let me drag in @gatsbyjs/ecosystem & @gatsbyjs/core into this bikeshed 😄

**Comment by KyleAMathews** [comment]
`gatsby-page-utils` sounds nice! :-D

Thanks for jumping on this @frinyvonnick !
