### ISSUE TITLE
Video does not work on Safari with gatsby-plugin-offline

### ISSUE THREAD

**Issue by vanwalj** [gatsbyjs/gatsby#13615]
## Description

Caching video with gatsby-plugin-offline works almost everywhere, except on Safari

After digging a bit, it seems that Safari do some pretty weird stuff when loading video, I found [this blog post interesting](https://philna.sh/blog/2018/10/23/service-workers-beware-safaris-range-request/)

A quick fix would probably be to exclude video files from the `gatsby-plugin-offline` cache, but I can't find a way to do so.

### Steps to reproduce

You can check out the project I'm currently working on https://staging.ouaille-note-festival.fr

- Visit the home page with Safari iOS or macOS
- A video should start playing
- Reload the page and the video is not loading anymore

If you reproduce those steps with Google Chrome it works well

### Expected result

The video should play on every latest browser

### Actual result

It doesn't load once cached Safari

### Environment

Latest stable Safari version on iOS and macOS

**Comment by JDeLay-JR** [comment]
I can start taking a look at this one

**Comment by vanwalj** [comment]
This seems to be the root issue https://github.com/GoogleChrome/workbox/issues/1663
Unfortunately it doesn't seems straightforward to fix 😨

**Comment by jamesvclements** [comment]
🤕 Any solutions for this?

**Comment by vanwalj** [comment]
@jamesvclements didn't find a proper way to solve this, I has to remove gatsby-plugin-offline 😟

**Comment by cwgw** [comment]
I also decided to drop offline support because of this issue.

I'd like to keep this open in the hopes that some brave person takes it on. Here's the strategy that the Workbox team currently suggests:

https://developers.google.com/web/tools/workbox/guides/advanced-recipes#cached-av

**Comment by LekoArts** [comment]
I'll close this as it's an upstream issue.
