### ISSUE TITLE
No generated HTML in production build

### ISSUE THREAD

**Issue by sebastienh** [gatsbyjs/gatsby#13611]
## Description

My issue looks like the #10322... The `gatsby serve` command outputs pages in js without HTML content, like in development mode. I need this HTML for SEO purpose but also because I want to use Netlify form which require generated HTML to parse and detect `form` tag elements. I made my GitHub repo public for solving this issue.  

### Steps to reproduce

Run the following commands using the repo: https://github.com/sebastienh/textually.net:

```  
$gatsby build
$gatsby serve
```

### Expected result

When doing `curl localhost:9000`, I should see the page HTML source. 

### Actual result

The only thing I can see in the `body` is 
``` html 
<noscript id="gatsby-noscript">This app works best with JavaScript enabled.</noscript><div id="___gatsby"><div style="outline:none" tabindex="-1" role="group"></div></div>
```

plus some `script` tags linking to javascript source files. No HTML. 

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.5.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Firefox: 62.0.3
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.29 => 2.3.29 
    gatsby-cli: ^2.5.11 => 2.5.11 
    gatsby-image: ^2.0.40 => 2.0.40 
    gatsby-plugin-catch-links: ^2.0.13 => 2.0.13 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-feed: ^2.1.1 => 2.1.1 
    gatsby-plugin-google-analytics: ^2.0.18 => 2.0.18 
    gatsby-plugin-layout: ^1.0.15 => 1.0.15 
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
    gatsby-remark-component: ^1.1.3 => 1.1.3 
    gatsby-remark-copy-linked-files: ^2.0.12 => 2.0.12 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-remark-prismjs: ^3.2.8 => 3.2.8 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.32 => 2.0.32 
    gatsby-transformer-remark: ^2.3.11 => 2.3.11 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18 
  npmGlobalPackages:
    gatsby-cli: 2.5.11

**Comment by pieh** [comment]
Linked repo either doesn't exist or is private :(

**Comment by sebastienh** [comment]
The repo is now public, sorry!

**Comment by sebastienh** [comment]
After some tests, it seems the problem is related to the use of MediaQuery from 'react-responsive' npm module. Without it the HTML content is generated correctly...

**Comment by sebastienh** [comment]
We can close this as I found a replacement that does the same thing and which doesn't interfere with HTML content generation. For others stumbling on the same problem use 'react-media' instead of 'react-responsive'.
