### ISSUE TITLE
Can you remove the <style id="typography.js">...</style> part of the page?

### ISSUE THREAD

**Issue by tgy3300** [gatsbyjs/gatsby#13622]
Create a gatsby blog project using the `gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-blog` command. After the `gatsby develop` test, the page was found to have `<style id="typography.js">. ..</style>`, can you remove this?

**Comment by DSchau** [comment]
Hello!

You'll want to remove `gatsby-plugin-typography` from `gatsby-config.js`, as well as the associated `typography.js` file in `src/utils`.

However--note that you'll lose the nice, optimized typography that you may have wanted.

Thanks!
