### ISSUE TITLE
[gatsby-transformer-remark] I want to build code code with webpack

### ISSUE THREAD

**Issue by chenshuai2144** [gatsbyjs/gatsby#13626]
hi guys
I want to migrate the code of ant.desgin to gatsby, which is a great product. I have migrated [ant design pro](https://pro.ant.design/). [repo](https://github.com/ant-design/ant-design-pro-site)
But I encountered a very difficult problem in antd, the code in md in antd will be compiled by webpack, so he can directly display his demo. I can't do it in gatsby, I hope I can have a good solution.

**Comment by pieh** [comment]
This is possible to do with `mdx` (using `gatsby-mdx` as alternative to `gatsby-transformer-remark`)

When using that, you can actually import and use react components inside your .md(x) files:

```mdx
---
name: Button
menu: Components
---

import { Button } from './Button'

# This is mdx file

## `Button` component

this is description of `<Button>` - here's how it looks like without any props:

<Button>lorem</Button>

Here's alternative using some props

<Button size="large">ipsum</Button>
```

For documentation pages, you can also use `docz` which automates a lot of things for this usecase + provide nice utilities:
 - `<Props of={SomeComponent} />` component that will list available props
 - `<Playground>` wrapper (for easy clipboard copy, live editing etc)

See https://gatsby-docz.netlify.com/docs/docs-button for demo (and https://github.com/pedronauck/gatsby-starter-docz/blob/master/docs/Button.mdx for source of it).

Here's just demo of interactive playground:
![Kapture 2019-04-25 at 13 56 11](https://user-images.githubusercontent.com/419821/56733983-f582f600-6761-11e9-8f08-dbcd15d5c2b3.gif)

**Comment by chenshuai2144** [comment]
i konw this. 
We have quite a lot of stock md documentation. If you need to rewrite it with this. It is very difficult to change it.
My ideal api is to convert the code in` http://pro.ant.design/static/d/140/path---index-6a9-0SUcWyAf8ecbYDsMhQkEfPzV8.json ` to webpack

**Comment by pieh** [comment]
Ah, ok.

Given that switching to mdx is not feasible for this use case, there is still some value in it - because mdx does something like that under the hood.

Just to clarify, so we talking about more concrete examples - are we talking about handling (for example) this https://github.com/ant-design/ant-design/blob/master/components/button/demo/basic.md (and rest of demos) as input
to achieve something like this https://ant.design/components/button/ as output?

**Comment by chenshuai2144** [comment]
yep. 
I used babel to compile, but I can't handle third-party dependency reports.
