### ISSUE TITLE
Question about the "Adding Page Transitions with gatsby-plugin-page-transitions" stub

### ISSUE THREAD

**Issue by polishedwp** [gatsbyjs/gatsby#13620]
## Summary
I have a question about the newly structured [Stubs List](https://www.gatsbyjs.org/contributing/stub-list/). I understand the general idea about the stub-list and from an organizational perceptive it is a great idea. 

My question is concerning  the Stub for [Adding Page Transitions with gatsby-plugin-page-transitions](https://www.gatsbyjs.org/docs/adding-page-transitions-with-plugin-page-transitions/). It appears this page is already done, as the [README](https://www.gatsbyjs.org/packages/gatsby-plugin-page-transitions/) is an incredible piece of documentation, and I am not sure it could be improved upon.

Are you looking for additional information or a different presentation for the Stub Page?

**Comment by pieh** [comment]
https://www.npmjs.com/package/gatsby-plugin-page-transitions is excellent plugin that abstracts lot of setup needed for page transitions, but it also is a bit opinionated (using `react-transition-group`). I think for the most part complete page would look something like this mention available packages for this:
 - so already mentioned https://www.npmjs.com/package/gatsby-plugin-page-transitions
 - alternative package: https://www.npmjs.com/package/gatsby-plugin-transition-link which potentially give you more control over individual page transitions

And after that there could be advanced section - dive into how to setup custom page transition - for example like in this starter https://emilia.lekoarts.de/ / https://github.com/LekoArts/gatsby-starter-portfolio-emilia where transition was hand coded giving users most control over it (and not being limited by APIs provided by ready made packages)
