### ISSUE TITLE
Using gatsbyjs as a blog site, is it necessary to use gatsby build once for each post?

### ISSUE THREAD

**Issue by tgy3300** [gatsbyjs/gatsby#13621]
Using gatsbyjs as a blog site, is it necessary to use the gatsby build command to repack each time an article is published, otherwise how to generate a new article page?

**Comment by cdtinney** [comment]
Yes, that is correct.

You can use automated CI (e.g. Travis CI) to do this for you as you commit/merge PRs to a specific branch (e.g. `master`).

**Comment by tgy3300** [comment]
However, my program has not changed, but the data has changed. This also needs to be re-gatsby build. There is no other way.

**Comment by DSchau** [comment]
I think you're asking for a feature we're terming "Incremental builds." The idea will be that you don't have to re-build the _entire_ site, but rather can do so in a more performant matter by understanding the internal data layer and knowing which pages to re-build.

This isn't currently possible--so the recommended approach will be to re-build the entire site on a change, e.g. with a CI build as @cdtinney noted!

Thanks!
