### ISSUE TITLE
Plugin library not rendering some images

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#13632]
## Description

I've seen this issue before, and thought we fixed it months ago. The plugin library doesn't seem to render some kinds of images from READme files.

### Steps to reproduce

Go to these links and notice the images at the top of the READme files. The first one doesn't render correctly, the second one does.
https://www.gatsbyjs.org/packages/gatsby-mdx/?=gatsby-mdx
https://www.gatsbyjs.org/packages/gatsby-plugin-transition-link/?=transition

### Expected result

Both images should render correctly.

### Actual result

Only the second one does.

### Environment

Latest Chrome browser.

@ChristopherBiscardi

**Comment by KyleAMathews** [comment]
The image in gatsby-mdx has a relative path pointing to @ChristopherBiscardi's github repo. That could be changed to an absolute link. We could also while building the pages try to download images with relative paths and use that.

**Comment by ChristopherBiscardi** [comment]
gatsby-mdx is being PR'd to the monorepo anyway soon. After #12514 lands.

This is definitely a gatsby-mdx relative image in readme issue and not a .org issue.
