### ISSUE TITLE
[www] remove plugin and starter feedback widget

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#13633]
On https://www.gatsbyjs.org/plugins/, there is a feedback collection widget for the Plugin Library. When I tried logging into Unbird (where the data is going), I found that Gatsby doesn't have a current subscription. The widget is also inaccessible, and uses a non-interactive SVG icon instead of a button element. Given this has gone unnoticed for a while and the plugin library data hasn't been reviewed, we should remove the widget.

![plugin library widget](https://user-images.githubusercontent.com/1045233/56770470-e9e6fd80-6768-11e9-9b1e-40f925f99018.png)

There is a separate effort to add a [feedback widget to the docs](#13550) that we will entirely control and thus won't require paying for a subscription. We could incorporate that into the Plugin Library section if we decide we want to solicit feedback.

**Comment by polishedwp** [comment]
It looks like the component `<Unbird />` in on line `116` of the `plugin.js` file located @ `www/src/pages/plugins.js`. Is this all the changes you need made? Or do you need `www/src/components/unbird.js` removed as well? I will be glad to work on this one.
