### ISSUE TITLE
[docs-contributing] Generate Developer Preview Branches with Netlify

### ISSUE THREAD

**Issue by hydrosquall** [gatsbyjs/gatsby#13642]
## Summary

Connect Netlify to the Gatsby repo, so that changes to the `docs/` folder triggers a build of the docs folder. This way, people can share changes that they've made to the site without requiring reviewers to build the site locally. The link to the preview site shows up in the "Checks" area of the pull request, similar to the existing tests that are run.

Documentation about the Netlify Developer Preview feature is [here](https://www.netlify.com/docs/continuous-deployment/).

I don't know if there's a way to add logic to the Netlify configuration so that only changes to the doc site will generate previews, as opposed to changes to the repository in general.

### Motivation

- Developer experience while shipping #13640 , it was hard to test how the changes would look due to a local build issue.
- It looks like Netlify is already a partner of the Gatsby, this change increases awareness of one of my favorite Netlify free features.

**Comment by DSchau** [comment]
Very much agreed! This is complicated, however, because Netlify only allows builds 15 minutes to complete, and gatsbyjs.org takes a little bit longer than that.

One thing I have tossed around is a very much simplified version of gatsbyjs.org (e.g. without screenshots, sites, showcase items, etc.) that would build out much quicker.

We'd love any assistance with this!

**Comment by paschalidi** [comment]
hey @hydrosquall and @DSchau have you thought of using another service that `netify`? I have seen implementations of PR-preview that dont use build in netify feature and the result is the same. 

Thoughts on that? 
I am also willing to help here :)

**Comment by hydrosquall** [comment]
Hi @paschalidi, I'm not familiar with other services that do branch previews, but would be interested to consider others.

@DSchau , do you know if there are any dashboards or services (circleCI maybe) which collect metrics about how long the gatsby docs site takes to build over time? It would be useful to see how far we have to go to get under the 15 minute mark, as well as keep track at how this number has changed over time.

**Comment by paschalidi** [comment]
@hydrosquall hey good Monday morning! 🌸 Hm there are not services that provide this out of the box but its not so difficult to build ourselves! 

Imagine a process like this once a PR is open
1. project is being build.
2. the static files are now being deployed in a url like `gatsby.pr-xxx.dev` 

And a process like this when you close a PR.
1. deletes url that has been deployed. 

I have done this couple of times already maintaining is not a great effort and you can use tools like `now` or `surge` to deploy in urls like i explained above. 
I personally have used surge but `now` can do the job as well!  

https://surge.sh/
https://zeit.co/now

Let me know your thoughts @hydrosquall and @DSchau and I am happy to open a PR with this :)

**Comment by wardpeet** [comment]
I don't think surge fits the need here. With surge we'll need to add a new step in circle-ci which will take a lot of resources. Now.sh might have the same issue though, that it needs to be built on circle-ci.

We probably want to lower the amount of starters/showcases as @DSchau mentioned. Of course we are open for other ideas. If you can get it up on now.sh we're happy to try!

**Comment by paschalidi** [comment]
Hey @wardpeet I am happy to open an experimental PR to see if `now` can work for this. 
I dont understand how now is different than surge, can you maybe explain, becuase as far as i understand what will happen with now is that we will like to add a job on the circle ci and deploy on `now` the built app. 

What you think it should be happening with `now`?

**Comment by hydrosquall** [comment]
It sounds to me like a middle term step is to build a “lite” version of the
docs site on each deploy which omits the showcase and uses simpler
placeholder images.

The limitation with now and surge is that they host built assets, but don’t
actually build the assets for you, and we can’t afford to build whole docs
site for every push to every PR branch in CircleCI.

With Netlify we could build deploy sites for every PR branch, but only if
we got the site build time to be consistently under 15 minutes.

I guess with now and surge, we could ask developers to deploy their
proposed changes that were built on their device to a URL that is included
on their PR- but we’d have no guarantee that the PR code is the same as
what got deployed.

**Comment by KyleAMathews** [comment]
Going to close this as we're close to an mvp for the Gatsby Cloud build service I announced in NYC recently. We'll be building preview versions for PRs here.

Thanks for everyone's interest! It's definitely been a bummer not having them and excited to get them back.

Video of my talk for reference https://youtu.be/bCclhXnYsTk
