### ISSUE TITLE
Complete documentation for `createPages`

### ISSUE THREAD

**Issue by loxaxs** [gatsbyjs/gatsby#13644]
I'm looking for the documentation for `exports.createPages` in `gatsby-node.js`, but all I found is this: https://www.gatsbyjs.org/docs/node-apis/#createPages, which is purely example.

Is there some doc I'm missing? If not, what's the list of arguments passed to `createPages`?

**Comment by jonniebigodes** [comment]
@loxaxs the page you've linked has the de facto arguments that are mostly used with the `createPages` api.
For some more context on what the arguments used see [here](https://www.gatsbyjs.org/docs/actions/#createPage). It complements the one you mentioned.

**Comment by KartSriv** [comment]
**@loxaxs I think [this](https://www.gatsbyjs.org/blog/2017-11-06-migrate-hugo-gatsby/#programmatic-page-creation) is the doc you're looking for.**

**Comment by loxaxs** [comment]
> @loxaxs I think [this](https://www.gatsbyjs.org/blog/2017-11-06-migrate-hugo-gatsby/#programmatic-page-creation) is the doc you're looking for.

I guess one more example can still be useful.
