### ISSUE TITLE
more links between the pages in section 'community'

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#13649]
i miss some crosslinks in section community at the pages. i think in the overview there should also some links to the subpages of this section. what are your opinions?

**where i miss some crosslinks:**

on [community](https://www.gatsbyjs.org/contributing/community/):

- Why Contribute to Gatsby.js?
- Gatsby Community Events
- Where to Participate in the Community
- Organize a Gatsby Event
- How to Run a Gatsby Workshop
- How to Pitch Gatsby

on [community events](https://www.gatsbyjs.org/contributing/events/)

- Organize a Gatsby Event
- How to Run a Gatsby Workshop
- How to Pitch Gatsby

on [organize-a-gatsby-event](https://www.gatsbyjs.org/contributing/organize-a-gatsby-event/)

- community events

**Comment by DSchau** [comment]
@muescha if cross-linking is indeed valuable on some of these pages (which seems reasonable) we'd happily take PRs adding some extra detail where it makes sense.

Thanks!

**Comment by hassan3095** [comment]
Hi, can I be assigned to this issue? I have already made some changes!

**Comment by muescha** [comment]
yes - you are welcome to contribute - just make an Pull Request with the issue number in the text
