### ISSUE TITLE
missing Links on community events page

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#13648]
## Description

i miss some links at [community events](https://www.gatsbyjs.org/contributing/events/):

GatsbyGatsby Days NY — May 6, 2019
-> can not find any link 

Total Newbie Introduction to Gatsby — June 6, 2019 
https://www.colabroanoke.com/public-events

JAMStack Conference — April 9, 2019 (NYC)
https://jamstackconf.com/

**Comment by marcysutton** [comment]
Here's a link for Gatsby Days: https://www.gatsbyjs.com/resources/gatsby-days/

PRs welcome!

**Comment by muescha** [comment]
since i can not make pull request to the airtable, the maintainer of this airtable need to make the update... 

BTW: is there any public database sytem with an "Pull Request"-Feature?

**Comment by freiksenet** [comment]
@muescha I don't have airtable access too, forwarded this to our marketing. Thank you!

**Comment by lindaleebumblebee** [comment]
I've made the updates to the airtable doc that will populate in the webpage. Thank you!

**Comment by muescha** [comment]
PS: Just now the events list is empty

**Comment by lannonbr** [comment]
@muescha what do you mean the events list is empty? I loaded the community events page and see a decent amount of events

**Comment by muescha** [comment]
https://www.gatsbyjs.org/contributing/events/
![327D68C4-0EF5-428B-ACC4-D4695F926AB0](https://user-images.githubusercontent.com/184316/57090618-854b1600-6d07-11e9-944b-92063ec31893.png)

**Comment by muescha** [comment]
It is interesting: it shows for a second the events and then they are away.

**Comment by lannonbr** [comment]
Can you open up devtools and see if there are any errors popping up in the console?

**Comment by muescha** [comment]
![4D7E1E6B-576E-4D59-8183-EFE80AA3CF40](https://user-images.githubusercontent.com/184316/57091518-b88ea480-6d09-11e9-9e3f-d4e1fea1d5b2.gif)

I am now on iPhone only - tomorrow I can try to use remote debugging

**Comment by muescha** [comment]
I will open a new bug report tomorrow.

**Comment by muescha** [comment]
links added to events page. thanks @lindaleebumblebee  for adding

**Comment by muescha** [comment]
@lannonbr  i opened #13844
