### ISSUE TITLE
Issue with integrating with reactstrap/bootstrap

### ISSUE THREAD

**Issue by kenlu89** [gatsbyjs/gatsby#13655]
We're facing a problem when import the reactstrap into our Gatsby site. When we do a build on Gatsby the bootstrap or reactstrap, the CSS code embed into all the public static html page. This causing our site from to change folder size from 400MB all the way to 4.6GB and may eventually be more. 

Is there a way to include reactstrap also our own CSS rule to not embed into the html pages?

**Comment by DSchau** [comment]
@kenlu89 could you provide a [reproduction](https://gatsby.dev/reproduction) so we could take a further look?

In particular, I don't think it's extremely likely that including a dependency makes your site weigh *4.6Gb* but I would honestly love to be shown otherwise, here!

**Comment by kenlu89** [comment]
@DSchau  we figure out the issue from 400MB to 4.6GB is that instead using import bootstrap inside the layout component we would use CDN method in the html.js . This shrink from 4.6 to 1.1GB. The site still in production but the problem is solved.
