### ISSUE TITLE
How to fix "unknown argument slug" 

### ISSUE THREAD

**Issue by mujeex** [gatsbyjs/gatsby#13669]
<!--
I am currently trying to create a blog site using gatsbyjs, and would like my blog posts to have their pages created for them programmatically.

I followed the steps in the tutorials section of the official documentation, but instead of creating the pages from a markdown file, I am pulling data from the contentful CMS. I keep on hitting this block whenever I run my code.
 
##gatsby-node.js file

`const path= require('path')

exports.createPages=({graphql,actions})=>{
const {createPage}=actions

const blogPost= path.resolve('./src/components/blogComponents/blog-post.js')
return new Promise((resolve,reject)=>{
    graphql(`
    {
        allContentfulBlog{
            edges{
              node{
                slug
              }
            }
          }
    }
`).then(results=>{
    // console.log(results)
    if(results.error){
        reject(results.error)
    }
      // create blog post pages
const posts=results.data.allContentfulBlog.edges

posts.forEach((post,index)=>{
    console.log(`showing slugs: ${post.node.slug}`)

   createPage({
        path:post.node.slug,
        component:blogPost ,
        context:{

            slug:post.node.slug,

        } 
    })

    })
}).then(resolve)
}) 
}`

##blog-post.js file

`   import React from 'react'
   import { graphql} from 'gatsby'

  const blogPost=({data})=>{
return (
    <div>
        new page created
    </div>
)
 }

 export default blogPost
 export const pageQuery= graphql`
  query ($slug: String!){
     allContentfulBlog (slug:{eq: $slug }) {
      edges{
      node{
       content{
           content
       }
      }
    }
  }
 }
 `
 `
I expected the blog-post.js file to receive all appropriate variables, but instead, it kept on throwing the "unknown argument 'slug' " error while making reference to the blog-post.js file.

**Comment by mujeex** [comment]
##Description
I am currently trying to create a blog site and would like my blog posts to have their pages created for them programmatically.

I followed the steps in the tutorials section of the official documentation, but instead of creating the pages from a markdown file, I am pulling data from the contentful CMS. I keep on hitting this block whenever I run my code.

##gatsby-node.js
`const path= require('path')

exports.createPages=({graphql,actions})=>{
    const {createPage}=actions

    const blogPost= path.resolve('./src/components/blogComponents/blog-post.js')
    return new Promise((resolve,reject)=>{
        graphql(`
        {
            allContentfulBlog{
                edges{
                  node{
                    slug
                  }
                }
              }
        }
    `).then(results=>{
        // console.log(results)
        if(results.error){
            reject(results.error)
        }
          // create blog post pages
    const posts=results.data.allContentfulBlog.edges
    // console.log(post)

    posts.forEach((post,index)=>{
        console.log(`showing slugs: ${post.node.slug}`)
        // const previous= index === posts.length-1?null: posts[index+1].node
        // const next= index === 0?null: posts[index-1].node

       createPage({
            path:`${post.node.slug}`,
            component:blogPost ,
            context:{
                slug:post.node.slug,
                // previous,
                // next
            } 
        })

        })
    }).then(resolve)
    }) 
}`

blog-post.js

` import React from 'react'
   import { graphql} from 'gatsby'


  const blogPost=({data})=>{
return (
    <div>
        new page created
    </div>
)
 }

 export default blogPost
 export const pageQuery= graphql`
  query ($slug: String!){
     allContentfulBlog (slug:{eq: $slug }) {
      edges{
      node{
       content{
           content
       }
      }
    }
  }
 }
 ``
I expected the blog-post.js file to receive all appropriate variables, but instead, it kept on throwing the "unknown argument 'slug' " error while making reference to the blog-post.js file.

**Comment by nephlin7** [comment]
Hi @mujeex,
Error is in the blog-post.js query,  should be for a single entry like this:

### blog-post.js
```javascript
export const pageQuery = graphql `
query ($slug: String!){
    contentfulBlog  (slug:{eq: $slug }) {
        content{
           content
       }
    }
}
`

```

**Comment by mujeex** [comment]
Thanks a lot, nephlin7 but I found out that if querying for entries with "all" prefixed, we are to first use the **filter** argument before the query.

**Comment by mujeex** [comment]
So the correct query goes like this

`
export const pageQuery= graphql`
query ($slug: String!){
    allContentfulBlog (filter:{slug:{eq: $slug }}) {
        edges{ 
          node{
              slug
              author
           content{
               content
           }
          }
        }
      }
}
``

**Comment by nephlin7** [comment]
> Thanks a lot, nephlin7 but I found out that if querying for entries with "all" prefixed, we are to first use the **filter** argument before the query.

ur welcome,

I recommend get item with "contentfulBlog" because is more ease destructuring data in template like this:

### template-blog.js

```javascript

const blogPost = (props) => {
    const {author, slug} = props.data.contentfulBlogPost
    return (
        <div>
            <h1>{ title }</h1>
            <span>{ slug }</span>
        </div>
    )
}

export blogPost

export const pageQuery = graphql `
query ($slug: String!){
    contentfulBlog  (slug:{eq: $slug }) {
           slug
           author
            content{
                content
             }
    }
}
`
```
If u use `allContentfulBlog ` you will have to iterate in the node to get the data.
