### ISSUE TITLE
Can't find react-router/lib/link when migrating to gatsby 2.0

### ISSUE THREAD

**Issue by whmountains** [gatsbyjs/gatsby#1366]
```
 ERROR  Failed to compile with 1 errors                                                                                                                                    6:29:29 PM

This dependency was not found:

* react-router/lib/Link in ./~/gatsby-link/index.js

To install it, you can run: npm install --save react-router/lib/Link
```
This goes away if I manually install react-router v3, but it seems like that should be automatic.

Also, I thought Gatsby v1 used react-router v4.  Very confusing...

**Comment by whmountains** [comment]
Update: installing react-router v3 clears the warning, but I get another message in the error overlay that says that the history object is incompatible.

**Comment by KyleAMathews** [comment]
https://www.gatsbyjs.org/docs/migrating-from-v0-to-v1/#replace-react-routers-link-component-with-gatsby-link
