### ISSUE TITLE
Trying to add mapping for authors in blog

### ISSUE THREAD

**Issue by derricktsmith** [gatsbyjs/gatsby#13660]
## Description

I am trying to add author information to my blog posts. However, it is not working and I am getting the following error message. 

`Error: MarkdownRemarkFrontmatter.author cannot convert to OutputType the following string: 'AuthorYaml'`

I looked at the [mapping in the Gatsby docs](https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types).

I also saw, and copied, how Gatsby put `author.yaml` in the `blog/` directory. The docs linked above don't share where to put the `author.yaml` file.

Where author file is in Gatsby blog: https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/author.yaml

### Steps to reproduce

- pull down my repo: https://github.com/derricktsmith/gatsby-blog-author
- $ `yarn`
- $ `yarn develop`

### Expected result
- Expected `yarn develop` to build the dev site.
- Expected to see author information inside the GraphQL query.

### Actual result

Received this error message and was not able to run `yarn develop` locally:
![Screen Shot 2019-04-26 at 4 05 52 PM](https://user-images.githubusercontent.com/47364320/56837001-83ccaa00-683e-11e9-81e7-5d327e7246e8.png)

### Environment

```
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.31 => 2.3.31 
    gatsby-image: ^2.0.40 => 2.0.40 
    gatsby-plugin-feed: ^2.1.1 => 2.1.1 
    gatsby-plugin-google-analytics: ^2.0.18 => 2.0.18 
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
    gatsby-remark-copy-linked-files: ^2.0.12 => 2.0.12 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-remark-prismjs: ^3.2.8 => 3.2.8 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.32 => 2.0.32 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18 
  npmGlobalPackages:
    gatsby: 2.3.27
```

**Comment by polishedwp** [comment]
Sorry... Looking at repo on my phone but It does not look like you modifed the GRAPHQL query like the example in the docs.

Need to add the yaml fields to the query.

**Comment by polishedwp** [comment]
Responded to the repo https://github.com/derricktsmith/gatsby-blog-author/pulls

**Comment by derricktsmith** [comment]
@polishedwp Anyway we can get something added to the Gatsby docs?
