### ISSUE TITLE
Remove Legacy Context API

### ISSUE THREAD

**Issue by pungggi** [gatsbyjs/gatsby#13676]
## Summary
Running my App in React.StrictMode brings the following

```
Warning: Legacy context API has been detected within a strict-mode tree: 
    in StrictMode (at gatsby-browser.js:10)
    in _default

Please update the following components: ScrollContext

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

### Basic example

https://github.com/gatsbyjs/gatsby/blob/3cbaadeea397d7ee871149e117f4e0eaea23b7d2/packages/gatsby-react-router-scroll/src/ScrollBehaviorContext.js#L103

### Motivation
Use the new Context API all over to try out Concurrent Mode now and to be prepared for React 17.
https://reactjs.org/docs/legacy-context.html

**Comment by DSchau** [comment]
@pungggi you've done a great job debugging where this issue occurs.

Would you be interested in making this change? Context was introduced in React 16.3, and our minimum supported version of React is 16.4.2, so we can make this change.

We'd love a PR! Thank you!

**Comment by paschalidi** [comment]
@DSchau and @pungggi 👋! 

This looks like a nice issue ! Can I please take over and start working on it? Asking since if @pungggi who reported want to work on this that is absolutely understandable. 

Thanks for reporting @pungggi and thanks for taking good care of this @DSchau!

**Comment by DSchau** [comment]
@paschalidi that'd be great! A unit test validating the fix to go along with it would be 👌 as well.

Let us know if we can help at all!

**Comment by paschalidi** [comment]
@DSchau cool! Thanks for the quick response! Will open a PR the soonest! 👍

**Comment by paschalidi** [comment]
@pungggi hey 👋, thanks from my side as well for reporting this. 
I am looking a little bit onto this, could you maybe help me by explaining how to reproduce it?

What I have done is that I created a completely new `gatsby` app 
with `gatsby new my-blazing-fast-site`
and then run `gatsby develop` from the root folder of the project.
Also have wrapped the whole app with the `React.StrictMode`. 

This however will not give me the warning you are getting. 
Explaining what you have done to get the warning will help a lot!

Thanks! 🙇

**Comment by pungggi** [comment]
hi @paschalidi  you might need to import from reach-router 
for example
`import { navigate } from "@reach/router"`
or a Link I guess
`import { Link } from "gatsby"`

**Comment by pungggi** [comment]
I`ve wrapped with
![grafik](https://user-images.githubusercontent.com/5635709/57106285-79b61a00-6d1c-11e9-812a-6f871bb53f2e.png)

but I think it is the same effect as React.StrictMode ..

**Comment by paschalidi** [comment]
Thanks!

**Comment by paschalidi** [comment]
Hey @pungggi and @DSchau 👋 hope you both are doing fine and that you also having a good time!

Hmmm, it looks to me that I still cant reproduce the `warning`. To clear this out, I would very kindly ask you to check this repo https://github.com/paschalidi/gatsby-issue-13676. 

Can please one of you clone it and run it locally and see if you can reproduce the same `warning`?
That would be amazing!! 🕊

**Comment by pungggi** [comment]
@paschalidi 
Just add this code to gatsby-browser.js
```js
import React from "react"

export const wrapRootElement = ({ element }) => {
  return (
    <React.unstable_ConcurrentMode>{element}</React.unstable_ConcurrentMode>
  )
}
```

**Comment by paschalidi** [comment]
little bit busy the last days will work on that in the weekend. soz

**Comment by ericmasiello** [comment]
Can we reopen this?

**Comment by DSchau** [comment]
@ericmasiello sure -- would you like to tackle the work required? It seems reasonably well scoped out!

**Comment by simnalamburt** [comment]
For those who reached here to enable strict mode in Gatsby, discussion of gatsby-react-router-scroll is being continued at #21231, and a PR regarding this issue has been opened! #21626
