### ISSUE TITLE
Extend BrowserApi for React Concurrent Mode

### ISSUE THREAD

**Issue by pungggi** [gatsbyjs/gatsby#13675]
## Summary

Allow to tweak how the React App is rendered, but not only by wrapping the root element.

### Basic example

Standard React:

```js
ReactDOM.render(<App />, document.getElementById('root'));
```

Concurrent React:

```js
ReactDOM.createRoot(document.getElementById('root')).render(<App />);
```

### Motivation

Allow Gatsby to be used with the future of React Concurrent Mode.
https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement does not seem to do it, as it wraps the root element only.

**Comment by thiskevinwang** [comment]
👇 😄 
### https://reactjs.org/docs/concurrent-mode-reference.html#concurrent-mode

**Comment by thiskevinwang** [comment]
wait, it looks like you can use https://www.gatsbyjs.org/docs/browser-apis/#replaceHydrateFunction ...?
