### ISSUE TITLE
Minimal usage for ImageSharp?

### ISSUE THREAD

**Issue by whmountains** [gatsbyjs/gatsby#1368]
Could you point me in the right direction for a minimal example of how to write a GraphQL query that resizes an image with ImageSharp?

I've given it my best shot looking at both the GatsbyGram example and the ImageSharp source but I can't crack it.  Here's what I have so far:

```graphql
{
  testImg: childImageSharp {
    small: responsiveSizes(maxWidth: 292, maxHeight: 292) {
      src
      srcSet
    }
  }
}
```
But I don't know how to specify the the path to the image.

Thanks a lot!

**Comment by KyleAMathews** [comment]
Check out the image processing example site
https://image-processing.gatsbyjs.org

**Comment by KyleAMathews** [comment]
You also should become friends with graphiql as it let's you explore what data is available and how different nodes relate to each other.

**Comment by whmountains** [comment]
Thank you so much!  That was what I needed.  Turns out I was missing the source plugin to read files from the filesystem.
