### ISSUE TITLE
Update React InstantSearch to v5

### ISSUE THREAD

**Issue by paschalidi** [gatsbyjs/gatsby#13686]
Hello you all, first things first, I cant really put into words how much I have been amazed by the way you have this project running! 🏆 wow.

## Update React InstantSearch to v5

I am wondering if it makes any sense for you to have the `react-instantsearch` from `algolia` to be updated into the latest version `v5`. I dont think that this is a duplicated issue although I might be wrong.. 

### Motivation

Looks to me that we can have the website loading faster since the package itself in the v5 is **16.3%** smaller [in some cases](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/?language=javascript#package-imports-since-520).

**Comment by KyleAMathews** [comment]
Oh yes please! 🙏

The components are massive right now.

**Comment by paschalidi** [comment]
Cool! I will open a PR soon @KyleAMathews. Any special requests?

**Comment by KyleAMathews** [comment]
A straight upgrade seems fine 👍

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by Kosai106** [comment]
Good call! Please let us (Algolia) know if you need any help. 😄

**Comment by paschalidi** [comment]
@KyleAMathews @Kosai106 rad! Will be working on that then :) Thanks 🙏 for making this possible!
