### ISSUE TITLE
[docs] Plugin search input encoding

### ISSUE THREAD

**Issue by colbyfayock** [gatsbyjs/gatsby#13696]
## Description
When visiting the docs plugin search directly with a pre-existing query in the URL, the search input displays the encoded characters, such as `%20`, instead of in this example, a space ` `.

![image](https://user-images.githubusercontent.com/1045274/56872287-42322f80-69f5-11e9-860b-59d55310b3b5.png)

**Note:** this does not appear to impact functionality, just aesthetics.

### Steps to reproduce
* Go to https://www.gatsbyjs.org/plugins/
* Search for `marketing platform` or really any multi-word phrase
* Simply hit refresh or copy the URL with the query and open a new tab with https://www.gatsbyjs.org/plugins/?=marketing%20platform
* See the plugins search input on the left

### Expected result
Would expect the input to show `marketing platform` instead of `marketing%20platform`.

### Actual result
It shows `marketing%20platform`.

### Environment
OSX 10.14.4 (18E226)
Chrome Version 76.0.3778.0 (Official Build) canary (64-bit)

**Comment by jgalat** [comment]
Hi @colbyfayock! I'm taking this. I'll publish a PR in a moment
