### ISSUE TITLE
Cannot query field for Wordpress

### ISSUE THREAD

**Issue by Mohammed-Alama** [gatsbyjs/gatsby#13695]
## Description
Hay there I'am trying to fetch some data from wordpress API but it field 
### Steps to reproduce
**1- Trying to execute this query**
{
  allWordpressPost {
             edges {
                   node {
                          id
                          slug
                          title
                          content
                          excerpt
                          date
                         modified
      }
    }
  }
}

**This is my repo**
https://github.com/Mohammed-Alama/wp-gatsby
### Expected result

give me the pages from my wordpress installation

### Actual result

`{
  "errors": [
    {
      "message": "Cannot query field \"allWordpressPost\" on type \"Query\".",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "stack": [
        "GraphQLError: Cannot query field \"allWordpressPost\" on type \"Query\".",
        "    at Object.Field (/Users/mohammedalama/WebstormProjects/Wordpress Gatsby/wp-gatsby/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:64:31)",
        "    at Object.enter (/Users/mohammedalama/WebstormProjects/Wordpress Gatsby/wp-gatsby/node_modules/graphql/language/visitor.js:334:29)",
        "    at Object.enter (/Users/mohammedalama/WebstormProjects/Wordpress Gatsby/wp-gatsby/node_modules/graphql/language/visitor.js:385:25)",
        "    at visit (/Users/mohammedalama/WebstormProjects/Wordpress Gatsby/wp-gatsby/node_modules/graphql/language/visitor.js:252:26)",
        "    at validate (/Users/mohammedalama/WebstormProjects/Wordpress Gatsby/wp-gatsby/node_modules/graphql/validation/validate.js:63:22)",
        "    at /Users/mohammedalama/WebstormProjects/Wordpress Gatsby/wp-gatsby/node_modules/express-graphql/dist/index.js:154:52",
        "    at processTicksAndRejections (internal/process/next_tick.js:81:5)"
      ]
    }
  ]
}`

### Environment

 System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.3.32 => 2.3.32 
    gatsby-image: ^2.0.40 => 2.0.40 
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-source-filesystem: ^2.0.32 => 2.0.32 
    gatsby-source-wordpress: ^3.0.57 => 3.0.57 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18 
  npmGlobalPackages:
    gatsby-cli: 2.5.12

**Comment by luchoster** [comment]
what's your WP url?
Also, I don't see your WP info in your `gatsby-config.js` form your repo

**Comment by DSchau** [comment]
As @luchoster noted, it doesn't look like you've installed/configured gatsby-source-wordpress which you will need to do to query Wordpress nodes.

Please try that--and then re-open/reply if we can help further. Thanks!

**Comment by Mohammed-Alama** [comment]
sorry for that guys i have forget to push changes to repo I have updated now

**Comment by luchoster** [comment]
Hey @Mohammed-Alama sorry, I just saw this again.
You have your configuration wrong for wordpress:
`baseUrl: "gatsby-wordpress.local/wp-json"`
it should be:
`baseUrl: "gatsby-wordpress.local"`

check that again and let me know if you different results.

**Comment by vipulcssoftsolutions** [comment]
I have the same issue, it does not show the Wordpress query in Grpahql interface. I installed the gatsby-source-wordpress and also added my website in config file.

Please help./
