### ISSUE TITLE
Extremely long (25+ min) build time happening randomly

### ISSUE THREAD

**Issue by gc** [gatsbyjs/gatsby#13698]
I have a gatsby website which uses gatsby-source-wordpress (with ACF), and build times are usually 5 minutes with netlify-cache plugin, and randomly (possibly with dependency version changes?) its started taking 25 minutes which causes it to not deploy because it takes way too long. I'm not sure exactly what is taking so long.

This log seems to be longest one (nothing comes after this log for 10-15 mins)
```
10:56:00 AM: success write out redirect data — 0.001 s
```

I can share the repo/code in private if it helps debug.

### Environment
System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
  Binaries:
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.1.0 => 2.3.31
    gatsby-image: ^2.0.20 => 2.0.40
    gatsby-plugin-manifest: ^2.0.9 => 2.0.29
    gatsby-plugin-netlify: ^2.0.13 => 2.0.15
    gatsby-plugin-netlify-cache: ^1.1.0 => 1.1.0
    gatsby-plugin-offline: ^2.0.16 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.12
    gatsby-plugin-react-svg: ^2.0.0 => 2.1.1
    gatsby-plugin-sharp: ^2.0.14 => 2.0.35
    gatsby-plugin-sitemap: ^2.0.11 => 2.0.12
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.7
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.0.8 => 2.0.32
    gatsby-source-wordpress: ^3.0.25 => 3.0.57
    gatsby-transformer-sharp: ^2.1.8 => 2.1.18

**Comment by gc** [comment]
Here are my deps:

```
    "babel-plugin-styled-components": "^1.10.0",
    "gatsby": "^2.1.0",
    "gatsby-image": "^2.0.20",
    "gatsby-plugin-manifest": "^2.0.9",
    "gatsby-plugin-netlify": "^2.0.13",
    "gatsby-plugin-netlify-cache": "^1.1.0",
    "gatsby-plugin-offline": "^2.0.16",
    "gatsby-plugin-react-helmet": "^3.0.2",
    "gatsby-plugin-react-svg": "^2.0.0",
    "gatsby-plugin-sharp": "^2.0.14",
    "gatsby-plugin-sitemap": "^2.0.11",
    "gatsby-plugin-styled-components": "^3.0.4",
    "gatsby-plugin-webpack-bundle-analyzer": "^1.0.4",
    "gatsby-source-filesystem": "^2.0.8",
    "gatsby-source-wordpress": "^3.0.25",
    "gatsby-transformer-sharp": "^2.1.8",
    "he": "^1.2.0",
    "moment": "^2.24.0",
    "prop-types": "^15.6.2",
    "react": "^16.8.0",
    "react-accessible-accordion": "^2.4.5",
    "react-animations": "^1.0.0",
    "react-dom": "^16.8.0",
    "react-flip-move": "^3.0.3",
    "react-helmet": "^5.2.0",
    "react-icons": "^3.3.0",
    "react-inlinesvg": "^0.8.4",
    "react-modal": "^3.8.1",
    "react-scrolllock": "^4.0.1",
    "react-slick": "^0.23.2",
    "react-structured-data": "^0.0.13",
    "react-waypoint": "^9.0.0",
    "slick-carousel": "^1.8.1",
    "slugify": "^1.3.4",
    "styled-components": "^4.1.3"
```

**Comment by gc** [comment]
After some investigation, the thing which is taking a long time is the image generation, it takes longer 15+ mins without the images being already cached on Netlify

Most likely a duplicate of #8056 , where the only workaround is to check in the cache (in my case, probably over 1GB) to git :(

**Comment by freiksenet** [comment]
Could you include a reproduction case? This way we could see why it's generating so many images.

**Comment by thundernixon** [comment]
I'm also having (what seems to be) the same issue.

I'm creating a site that will be 11 pages of design project images (including process). It's a group site, because the projects are thesis projects from a design program I was recently in. So, each person is adding about 15–25 images, and these are generating a pretty big cache.

I've found a (hopefully temporary) workaround: using `gatsby build && netlify deploy --prod` locally, so that my computer does the processing work, then uploads the results. However, this only works as a replacement technique; it doesn't update the cache so that subsequent push updates work, as I had hoped might be the case.

If anyone finds a better solution, I'd be happy to learn about it!

**Comment by thundernixon** [comment]
EDIT: Actually, my build isn't *randomly* long; it's taking too long, every time. 

However, the similar aspect is that it tends to fail on the same line:

```
success write out redirect data — 0.001 s
```

**Comment by gc** [comment]
@freiksenet I can let you see the repo privately, perhaps if you have an email I can send details to.
@thundernixon I fixed it by checking my cache into git (a very very messy and bad thing to do, but worked nonetheless). I'm not sure how Gatsby can fix it on their end, besides perhaps making image generation faster, or producing less images.


On producing less images, it surely must be possible, last I checked, Gatsby was producing over 9000 for our site, when we have only a few hundred. I'm assuming this is for the Gatsby-Image *fluid* images which have a range of different sizes, perhaps we can limit the amount of sizes gatsby will create for our fluid images. As another workaround, we can perhaps switch some of our images to be fixed.

Lastly, your build is stopping on `success write out redirect data — 0.001 s` as thats where the image generation happens after, Netlify just doesn't show those logs on their console for some reason.

**Comment by freiksenet** [comment]
@gc Sorry for dropping the ball on it. You can send me the access through `freiksenet@gatsbyjs.com`.

**Comment by philohelp** [comment]
Same problem here :( Netlify builds are taking a huge time.

**Comment by arrowtype** [comment]
@gc, thanks so much for the advice! I ended up using the netlify cache plugin, and checking in my cache to GitHub. It was pretty messy, and meant I submitted a lot of commits that felt sort of worthless. But, it made things work!

**Comment by philohelp** [comment]
I solved the issue with adding this to a gatsby-node.js file at the root of my project.  Still haven't found precisely what unterminated process was the cause of the problem but... somehow it solved it.

```
const ChildProcess = require('child_process');
exports.onPostBuild = () => {
  ChildProcess.execSync(
    "ps aux | grep jest | grep -v grep | awk '{print $2}' | xargs kill",
  );
};
```

**Comment by jmaroa** [comment]
> I solved the issue by adding these lines to a gatsby-node.js file at the root of my project. Still haven't found precisely what unterminated process was the cause of the problem but... somehow it solved it.
> 
> ```
> const ChildProcess = require('child_process');
> exports.onPostBuild = () => {
>   ChildProcess.execSync(
>     "ps aux | grep jest | grep -v grep | awk '{print $2}' | xargs kill",
>   );
> };
> ```

How did get into this solution?
