### ISSUE TITLE
how can I deploy the sites to a CDN?

### ISSUE THREAD

**Issue by magicly** [gatsbyjs/gatsby#1369]
hi, I want to deploy all files(including pics/js/css/font) except index.html to my CDN, e.g. http://cdn.example.com, but deploy index.html to my main site: http://www.example.com.  Is it possible? I work around for several hours, including set 
```js
pathPrefix: 'http://cdn.example.com'
```
in gatsby-config.js. 
or modify webpack config in gatsby-node.js
```js
exports.modifyWebpackConfig = ({config, stage}) => {
  config.merge({
    output: {
      publicPath: 'http://localhost:50000000000/',
    }
  })

  return config;
}
```

In create-react-app, I just need to set PUBLIC_URL and in webpack I just need to set publicPath in output. 

Is there sth I missing? Any help is welcome. Thanks~
I use https://github.com/gatsbyjs/gatsby-starter-blog/tree/1.0 as a starter, so the package.json file is the same.

**Comment by KyleAMathews** [comment]
With a static site you really want to deploy everything to a CDN. You're
site is significantly faster this way as html can be loaded from the CDN as
well as assets and you don't have to do multiple SSL negotiations. Perhaps
we can add support for this style of deployment but in the meantime,
there's plenty of static hosts that'll put everything for you on a CDN.

**Comment by whmountains** [comment]
[Netlify](https://netlify.com) is a nice static host has a free plan.  They also have an auto-deploy feature that knows how to build Gatsby sites so you don't have to set up CI.

**Comment by prateek3255** [comment]
For anyone else who wanders on this issue, this can now be achieved using the `assetPrefix` option introduced with this PR - https://github.com/gatsbyjs/gatsby/pull/12128
