### ISSUE TITLE
gatsby-plugin-google-tagmanager without jquery

### ISSUE THREAD

**Issue by Jsalvat** [gatsbyjs/gatsby#13701]
## Summary

gatsby-plugin-google-tagmanager throws an error of jquery not defined. We're not using jQuery on our project and we want to know if it's possible to use this plugin without jQuery

## Relevant information

Use gatsby-plugin-google-tagmanager without jQuery for projects without this module
### Environment (if relevant)
    System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Safari: 12.1
  npmPackages:
    gatsby: ^2.1.18 => 2.3.4
    gatsby-background-image: ^0.2.8-beta => 0.2.8-beta
    gatsby-image: ^2.0.33 => 2.0.35
    gatsby-plugin-canonical-urls: ^2.0.12 => 2.0.12
    gatsby-plugin-google-tagmanager: ^2.0.13 => 2.0.13
    gatsby-plugin-manifest: ^2.0.24 => 2.0.26
    gatsby-plugin-material-ui: ^1.2.4 => 1.2.4
    gatsby-plugin-offline: ^2.0.24 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.7 => 3.0.11
    gatsby-plugin-react-helmet-canonical-urls: ^1.2.0 => 1.2.0
    gatsby-plugin-remote-images: ^1.0.1 => 1.0.1
    gatsby-plugin-remove-trailing-slashes: ^2.0.10 => 2.0.10
    gatsby-plugin-sass: ^2.0.10 => 2.0.11
    gatsby-plugin-sharp: ^2.0.22 => 2.0.32
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.0.23 => 2.0.28
    gatsby-transformer-sharp: ^2.1.14 => 2.1.17
  npmGlobalPackages:
    gatsby-cli: 2.4.16

**Comment by mikaelkristiansson** [comment]
I dont think `gatsby-plugin-google-tagmanager` is using jquery, so there must be something else throwing the error. If you look here:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-tagmanager/package.json

Could you post the error here so we can see what might be causing it?

**Comment by jonniebigodes** [comment]
@Jsalvat upon checking the plugin it isn't using any jquery, i haven't checked all the packages you're using but so far none of them is using it. Probably the issue is stemming from another package you have installed that is requiring jquery.

**Comment by Jsalvat** [comment]
It seems that GTM add some script with jquery. I'll have to look into it. Thanks guys. I'll close this issue now

**Comment by JackEdwardLyons** [comment]
Any news on a workaround for this?
