### ISSUE TITLE
GraphQLError: Schema is not configured for mutations

### ISSUE THREAD

**Issue by Mountains-and-rivers** [gatsbyjs/gatsby#13704]
i type ```{
  allStrapiDianzan {
    edges {
      node {
        id
        dianzan
      }
    }
  }
}```  in ___graphql,then i get blow:
```
{
  "data": {
    "allStrapiDianzan": {
      "edges": [
        {
          "node": {
            "id": "Dianzan_5cc6b9f816723f694d45efff",
            "dianzan": 155
          }
        }
      ]
    }
  }
}
```

now i want to update "dianzan" to 300 , i type like this:

```
mutation {
  update(id:"Dianzan_5cc6b9f816723f694d45efff", dianzan: 300) {
    id
    dianzan
  }
}
```

got error:

```
{
  "errors": [
    {
      "message": "Schema is not configured for mutations.",
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ],
      "stack": [
        "GraphQLError: Schema is not configured for mutations.",
        "    at getOperationRootType (/Users/wangguilin/aliyunGit/gatsby-site/node_modules/graphql/utilities/getOperationRootType.js:37:15)",
        "    at executeOperation (/Users/wangguilin/aliyunGit/gatsby-site/node_modules/graphql/execution/execute.js:229:61)",
        "    at executeImpl (/Users/wangguilin/aliyunGit/gatsby-site/node_modules/graphql/execution/execute.js:85:14)",
        "    at execute (/Users/wangguilin/aliyunGit/gatsby-site/node_modules/graphql/execution/execute.js:62:256)",
        "    at /Users/wangguilin/aliyunGit/gatsby-site/node_modules/express-graphql/dist/index.js:180:37",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
      ]
    }
  ]
}
```
i got data from strapi by adding gatsby-config.js like this:
```
 {
      resolve: `gatsby-source-strapi`,

      options: {
        apiURL: `http://localhost:1337`,
        contentTypes: [
          `dianzan`
        ],
        queryLimit: 1000,
      },
    },
```

I can't find the reason for the mistake. i selected "update" and "find" in strapi  Permissions

**Comment by jonniebigodes** [comment]
@Mountains-and-rivers if i'm reading this right you're using the plugin right? the `gatsby-source-strapi` plugin right? If that's the case i'm sorry to inform you that like some  of the plugins available to gatsby, they are a "one way street" (pardon the bad pun), which in other words means you can only get the data, not modify or create. For that case you'll have to make another arrangements, you'll have to change your  site and add apollo for instance in order to manipulate the data.

**Comment by DSchau** [comment]
@jonniebigodes correct, yeah!

Gatsby source plugins are currently enabled only to query data, not provide mutations. The reason for that is that a mutation would typically be done client-side, and would require shipping a GraphQL client library alongside our runtime, which is not something we're currently doing.

Thanks for noting this! If you'd like to set up a mutation-aware GraphQL version of your application, you should be able to use the [Strapi API](https://strapi.io/documentation/3.x.x/guides/graphql.html) and then use something like [Gatsby with Apollo](https://github.com/jlengstorf/gatsby-with-apollo) to enable the client-side GraphQL library.

Closing as answered--but please re-open/reply if we can help further. Thanks!

**Comment by Mountains-and-rivers** [comment]
OK thank you ! i find this: https://www.apollographql.com

**Comment by jonniebigodes** [comment]
@Mountains-and-rivers good to know, also take a look at [this](https://github.com/jlengstorf/gatsby-with-apollo) for a example on how to connect apollo and Gatsby

**Comment by fullstackwebdev** [comment]
How do disable this? I want to "configure Schema for mutations"

I am using Apollo and Gatsby to stitch my backend schema -- which runs on Apollo Server and has a database. I guess I could by pass the schema stitching, why would this be disabled for people who know what to do? I guess I don't understand how this is a useful feature. 

Any help disabling welcomed.

**Comment by Kasilucky** [comment]
when i'm trying to write mutations in gatsby graphql console it shows
{
  "errors": [
    {
      "message": "Schema is not configured for mutations.",
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ],
      "stack": [
        "GraphQLError: Schema is not configured for mutations.",]

How to configure mutations and subscriptions
