### ISSUE TITLE
Investigate adding thread-loader & cache-loader — should be easy speedup of JS compilation

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#13719]
We'd planned to do this for v2 but somehow it didn't happen :-( Should be easy to get in.

**Comment by pieh** [comment]
Something worth checking - CRA added `thread-loader` and removed it later on because of some problems ( https://github.com/facebook/create-react-app/pull/5170 ).

**Comment by m-allanson** [comment]
Based on conversations with @KyleAMathews and @pieh it seems like this isn't a big enough win for now. web pack v5 will have it by default? Let's wait for that.
