### ISSUE TITLE
gatsby-plugin-emotion breaks onRenderBody

### ISSUE THREAD

**Issue by kennedyrose** [gatsbyjs/gatsby#13717]
## Description

Including gatsby-plugin-emotion in the gatsby-config.js file makes the onRenderBody API unusable.

### Steps to reproduce

1. Clone repo: https://github.com/escaladesports/emotion-bug (which is just the Gatsby blog starter with emotion)
2. Run `gatsby develop`

### Expected result

Both "GATSBY SSR" and "ONRENDERBODY" should be logged to the console. These are logged in the gatsby-ssr.js file.

### Actual result

Only "GATSBY SSR" is logged since onRenderBody never executes.

However, if the emotion plugin is removed from the console, the onRenderBody function executes and logs to the console as expected.

### Environment
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0-next.0 - ~/.nvm/versions/node/v11.6.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.108
    Firefox: 55.0.3
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.3.32 => 2.3.32 
    gatsby-image: ^2.0.40 => 2.0.40 
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6 
    gatsby-plugin-feed: ^2.1.1 => 2.1.1 
    gatsby-plugin-google-analytics: ^2.0.18 => 2.0.18 
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
    gatsby-remark-copy-linked-files: ^2.0.12 => 2.0.12 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-remark-prismjs: ^3.2.8 => 3.2.8 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.32 => 2.0.32 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18 
  npmGlobalPackages:
    gatsby-cli: 2.4.17
```

**Comment by DSchau** [comment]
@kennedyrose am I missing something?

I did the following:

1. Cloned the repo
1. Ran `yarn`
1. Ran `yarn dev`

And I see the following in the console:

```
success onPostBootstrap — 0.092 s

info bootstrap finished - 2.653 s




GATSBY SSR






ONRENDERBODY



 DONE  Compiled successfully in 3552ms     
```

Could you provide some more detail?

**Comment by kennedyrose** [comment]
Super weird. We tested this with 2 members of the team and it wasn't working. Closing for now, I'll try to get more info about what might be happening.

**Comment by pyramation** [comment]
reproduced on my machine just today.
