### ISSUE TITLE
Groups of groups

### ISSUE THREAD

**Issue by FraserThompson** [gatsbyjs/gatsby#13725]
## Summary

I want to be able to nest groups in GraphQL queries.

### Basic example

```
allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC  } ) {
    group(field: fields___year) {
        fieldValue
        group(field: fields___month) {
            fieldValue
            edges {
                node
            }
        }
    } 
}
```

And what comes out would look like

```
group {
    [
        {
            fieldValue: 2019
            group: [
                {fieldValue: April, edges []},
                {fieldValue: March, edges []},
                {fieldValue: February, edges []}
            ]
        },
        {
            fieldValue: 2018
            group: [
                {fieldValue: December, edges []},
                {fieldValue: November, edges []},
                {fieldValue: October, edges []}
            ]
        },
    ]
}
```

### Motivation

For my site I'm grouping posts in elements by year and month so I can display them on a big page with a scrollspying sidebar. Like this:

![image](https://user-images.githubusercontent.com/6093858/56927893-68f18280-6b29-11e9-9b02-4478eb6a28ba.png)

Currently to achieve this I have a custom `yearAndMonth` field and a big reduce in the component to sort the posts into groups like `[{year: 2019, months: [{month: april, posts: []}, {month: march, posts: []}]}]`. It would be much more convenient and way better for clientside performance if this were already sorted once it got to the component.

**Comment by DSchau** [comment]
@FraserThompson since Gatsby renders that .reduce at _build time_ the client-side performance isn't suffering! That loop will run in the Node.js process--and so the end result will be sweet, sweet performant HTML (with a React runtime once it hits the client-side).

However - to best check this out to see if it is possible, could you supply a [reproduction](https://gatsby.dev/reproduction) so we could investigate?

**Comment by FraserThompson** [comment]
@DSchau Hold on, have I completely misunderstood a fundamental part of how gatsby works? 😯 I was under the impression only code in gatsby-node.js was run at build time and the React code in my page and other components was run in the clients browser like a normal React app... Is this not the case? If so then Gatsby is even more magical than I thought 🌠

I've made a bit of a reproduction here using the blog starter. Basically has posts grouped by year using the GraphQL query, then grouped by month using a reduce. Hopefully you can see how being able to group the contents of that group by another field would result in nicer code: 
https://github.com/FraserThompson/gatsby-groups-of-groups

**Comment by DSchau** [comment]
> Hold on, have I completely misunderstood a fundamental part of how gatsby works? 😯 I was under the impression only code in gatsby-node.js was run at build time and the React code in my page and other components was run in the clients browser like a normal React app... Is this not the case? If so then Gatsby is even more magical than I thought

It is run like a normal React app--but the build process _produces_ static HTML that is then hydrated with the "normal React app" functionality! So you get the best of both worlds!

Also just for clarity--a reduce/loop is generally O(n) time if you're just iterating, so the performance is actually _great_ ;)

I'll take a look at that starter in a minute and see if we can figure out a solution--thanks!
