### ISSUE TITLE
[1.0] gatsby-plugin-google-analytics causing `ga is not defined`

### ISSUE THREAD

**Issue by qkevinto** [gatsbyjs/gatsby#1372]
Hey everyone! Fantastic work on Gatsby, was able to move my personal site from `hexo` to `gatsby@next` in a breeze!

Though I think I've hit a bit of a snag:
`gatsby-plugin-google-analytics` includes 
```
ga("set", "page", (location || {}).pathname);
ga("send", "pageview");
```
in `gatsby-browser.js`, which then gets bundled into the `app-<hash>.js`, which then gets added to the `<head>`.

However, in `gatsby-ssr.js` the ga script that adds the `ga` function to the `window` gets rendered into the `<body>`. So it seems as though when `ga("set", "page", (location || {}).pathname);` gets called from within `app-<hash>.js`, the `ga` function does not yet exist and thus throwing `ga is not defined`.

---
Gatsby `v1.0.0-beta.6`
Node `v6.9.2`
macOS `v10.12.6`

**Comment by Vagr9K** [comment]
This is already fixed in https://github.com/gatsbyjs/gatsby/commit/b0ff97d5f12f6c2d6180500783e648e6702fa4c2.

Just wait for the canary release of `gatsby-plugin-google-analytics`.

**Comment by qkevinto** [comment]
Ahh completely missed that. Cheers @Vagr9K! Closing issue.
