### ISSUE TITLE
Gatsby build (prod) doesn't generate static HTML and head meta tags

### ISSUE THREAD

**Issue by zuyetawarmatik** [gatsbyjs/gatsby#13737]
My Github repo at https://github.com/zuyetawarmatik/zuyetawarmatrip

How: If you try to clone and run `gatsby build`, checking .html files in public folder, such as in public/trips/2015-may-meteora-greece/en/index.html.

Expected: the generated HTML should have static content. (We can curl localhost:9000/<page path> to see: it's not static content)

Reality: The static content is empty. Head meta tags is empty. Instead it seems that it only has linkings to JSON file for service worker to fetch the content.

This seems to mess my site SEO feature (crawler can't see the content?) and Facebook sharing debugger quite a lot.

**Comment by anonimoconiglio** [comment]
I see from your config file that you're using `gatsby-plugin-manifest` along with `gatsby-plugin-offline`.  

I think the behavior you see it's normal since with this two plugins the head meta tags are now on the service worker:

> "View source doesn’t represent the actual HTML data since gatsby-plugin-offline registers and loads a service worker that will cache and handle this differently. Your site is loaded from the service worker, not from its actual source (check your Network tab in the DevTools for that)."
>  from [gatsby-plugin-offline notes](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/#notes)

**Comment by zuyetawarmatik** [comment]
My site is based on `https://github.com/gatsbyjs/gatsby-starter-blog`, which configures the `gatsby-plugin-manifest` and `gatsby-plugin-offline` the same way. Building starter blog outputs HTML with raw contents. The thing is just half a month ago everything was still going OK for my site.

> I see from your config file that you're using `gatsby-plugin-manifest` along with `gatsby-plugin-offline`.
> 
> I think the behavior you see it's normal since with this two plugins the head meta tags are now on the service worker:
> 
> > "View source doesn’t represent the actual HTML data since gatsby-plugin-offline registers and loads a service worker that will cache and handle this differently. Your site is loaded from the service worker, not from its actual source (check your Network tab in the DevTools for that)."
> > from [gatsby-plugin-offline notes](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/#notes)

**Comment by anonimoconiglio** [comment]
You're right. 
I don't know if it could work but I guess that maybe it's because you have `gatsby-plugin-offline` before `gatsby-plugin-react-helmet` and other plugins. Did you try to load offline plugin at the end? (Or at least before netlify one)

**Comment by zuyetawarmatik** [comment]
@anonimoconiglio I've figured out the problem, it's because I used `withWidth` function of material-ui, which will break SSR generation when building (but service working is still working, so everything outside looks still fine, but not correctly inside). The SSR generation doesn't know about media query so it can't build the HTML perfectly, but it's too silent to figure out the bug.

**Comment by jperasmus** [comment]
For anyone seeing this in the future: We had a similar issue where the meta tags were properly set for the client-side runtime, but that the meta tags were not part of the statically generated HTML.

In the end, it came down to us using the documented `meta` property of `Helmet` like this:

```jsx
<Helmet
  title={title}
  meta={[{ name: 'description', content: 'Some description' }]}
/>
```

Changing it to child components fixed it for us:

```jsx
<Helmet
  title={title}
>
  {metaTags.map((metaTag, index) => (
    <meta key={index} {...metaTag} />
  )}
</Helmet>
```
