### ISSUE TITLE
preload fonts using Typeface from NPM

### ISSUE THREAD

**Issue by danboyle8637** [gatsbyjs/gatsby#13746]
I'm using Kyle's Typeface project to get in the two fonts I'm using on my websites. 

In my gatsby-browser.js file, I have...

```
require('typeface-montserrat')
require('typeface-quicksand')
```

But I don't know how to make sure they's a rel='preload' tag on the link tags. 

I've seen some ways of doing this but they weren't using the Typeface fonts from npm.

Thanks!

**Comment by polishedwp** [comment]
It is documented in the [Starter Blog](https://github.com/gatsbyjs/gatsby/tree/master/starters/blog):

The npm packages are loaded in the [package.json](https://github.com/gatsbyjs/gatsby/tree/master/starters/blog) file. 

Take a look at the [layout.js](https://github.com/gatsbyjs/gatsby/blob/118e0d0628e8adc3b471c1bf7f3dda1f39655b97/starters/blog/src/components/layout.js#L37) file.

**Comment by danboyle8637** [comment]
@polishedwp Awesome thank you!

**Comment by KyleAMathews** [comment]
You might be interested in my proposal here: https://github.com/gatsbyjs/gatsby/issues/14281
