### ISSUE TITLE
How much memory is too much? vps build

### ISSUE THREAD

**Issue by decimoseptimo** [gatsbyjs/gatsby#13760]
## Summary
I'm still experiencing https://github.com/gatsbyjs/gatsby/issues/5321

After `gatsby build` i get 
```
success Building production JavaScript and CSS bundles — 6.716 s
⡀ Building static HTML for pagesKilled
```

We are talking about 5 pages.

I can confirm with `htop` that it is due to memory issues. My VPS goes from [478M/992M] to [9XXM/992M] then throws the error.

### Environment (if relevant)

It doesn't happen during development (win10)
It happens in my staging server (vagrant ubuntu/bionic64 image)
It happens in production server (1GB VPS ubuntu 16.04)

**Comment by DSchau** [comment]
@decimoseptimo this seems something to be a little out of our control, and rather seems to be some issue with how your CI environment is configured.

Are you able to build other Node.js projects, e.g. something build with create-react-app? A site of 5 pages should absolutely be able to be built even in a CI environment, so I'm left with a few options:

1. Server needs optimization to build out Node.js projects like Gatsby
1. Some utility we use (e.g. jest-worker) that spins up workers is getting killed prematurely
