### ISSUE TITLE
Hot reload not working using VM 

### ISSUE THREAD

**Issue by ammarjabakji** [gatsbyjs/gatsby#13778]
Hello,

Hot reload is not working using Virtual Machine.
I am using VSCode "the server version" and I am running `gatsby develop -H 0.0.0.0` to listen to the Server's IP address. I could know what cause this problem.

**Comment by DSchau** [comment]
Hi!

We'll need a lot more info for this problem to begin to address. We use web sockets to handle the hot module reloading--are these supported with whatever VM/container you are using?

This seems largely out of our control for two reasons:

1. We are using technologies that are supported in local environments that _should_ translate just fine to e.g. a VM
1. It's difficult to diagnose an issue that we can't reproduce

**Comment by polishedwp** [comment]
For what its worth, I just tested in a Mac/ Parallels Vm of Ubuntu 18.10 and Node v.12 and the hot reloading works fine.

**Comment by ammarjabakji** [comment]
> Hi!
> 
> We'll need a lot more info for this problem to begin to address. We use web sockets to handle the hot module reloading--are these supported with whatever VM/container you are using?
> 
> This seems largely out of our control for two reasons:
> 
> 1. We are using technologies that are supported in local environments that _should_ translate just fine to e.g. a VM
> 2. It's difficult to diagnose an issue that we can't reproduce

**Comment by ammarjabakji** [comment]
Hi @Dschau,
Thank you for your reply.
I think web sockets are supported but I am not sure.
I have a WordPress Certified by Bitnami VM instance, please see the details below;

> Runs on
Google Compute Engine
Type
Virtual machines
Single VM
Last updated
5/6/19, 8:57 AM
Category
Blog & CMS
Version
5.1.1-1
Operating system
Debian 9
Package contents
Apache 2.4.39
ImageMagick 6.9.8
lego 2.4.0
MySQL 8.0.15
OpenSSL 1.0.2r
PHP 7.2.16
phpMyAdmin 4.8.5
SQLite 3.27.2
Varnish 4.1.0
WordPress 5.1.1
WP-CLI 2.1.0

**Comment by ammarjabakji** [comment]
Hi @Dschau,
Thank you for your reply.
I think web sockets are supported but I am not sure.
I have a WordPress Certified by Bitnami VM instance, please see the details below;

> Runs on
Google Compute Engine
Type
Virtual machines
Single VM
Last updated
5/6/19, 8:57 AM
Category
Blog & CMS
Version
5.1.1-1
Operating system
Debian 9
Package contents
Apache 2.4.39
ImageMagick 6.9.8
lego 2.4.0
MySQL 8.0.15
OpenSSL 1.0.2r
PHP 7.2.16
phpMyAdmin 4.8.5
SQLite 3.27.2
Varnish 4.1.0
WordPress 5.1.1
WP-CLI 2.1.0
