### ISSUE TITLE
[docs] Further describe where gatsby-* files should belong in a gatsby plugin

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13782]
## Description

When @robert197 was creating a Gatsby plugin, he got caught up on where to place the `gatsby-node.js` file and it wasn't working for him. I helped debug his issue and it was that he didn't compile the code with babel from the `src/` directory up to the root directory of his plugin.

The only place I found this noted to do this is in the last paragraph here: https://www.gatsbyjs.org/docs/creating-a-local-plugin/

It would be good to further document what files should belong in a plugin structure as well as expand upon transpiling the code with babel as many Gatsby plugins are done.

**Comment by marcysutton** [comment]
This file exists now (the information was already there, just buried in another doc): https://www.gatsbyjs.org/docs/files-gatsby-looks-for-in-a-plugin/

The main action item I see here is to document transpiling of plugin code–but there are two things to note with that:

1. the [transpilation plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-compile-es6-packages/) doesn't talk about how to operate on source code, only packages
2. Gatsby should probably just do that for you. @gatsbyjs/core any input on timing for when Gatsby will handle transpilation of packages automatically?

**Comment by sidharthachatterjee** [comment]
We _do_ transpile all code in plugin packages since https://github.com/gatsbyjs/gatsby/pull/15284

@robert197 Could you link to a reproduction because this sounds like a potential bug

**Comment by marcysutton** [comment]
This was opened before the transpilation of packages by default, so it might be a non-issue now!

**Comment by marcysutton** [comment]
I'm to close this issue as I believe it's resolved, but feel free to open if needed. Thank you!
