### ISSUE TITLE
[1.0] process.env.__PATH_PREFIX__ is undefined

### ISSUE THREAD

**Issue by chiedo** [gatsbyjs/gatsby#1378]
Following the instructions [here](https://www.gatsbyjs.org/docs/adding-images-fonts-files/#using-the-static-folder) yields undefined

I have image URLs being delivered dynamically from a json file so I'm assuming the static folder is the only option.

**Comment by whmountains** [comment]
I can reproduce this.

```js
console.log('path prefix', process.env.__PATH_PREFIX__)
```

Returns `undefined` for me as well, at least in development.

**Comment by KyleAMathews** [comment]
Oh oops, it should be `window.__PATH_PREFIX__` — can one of you double check that and PR a fix to the docs?

**Comment by chiedo** [comment]
That isn't working either. :(

Once the appropriate fix is clear, I can submit the PR. Got everything queued up

**Comment by chiedo** [comment]
Using window also causes the build to fail

**Comment by chiedo** [comment]
Figured it out. It should just be `__PATH_PREFIX__` and pathPrefix needs to be defined in gatsby-config.js.

PR coming shortly

**Comment by chiedo** [comment]
https://github.com/gatsbyjs/gatsby/pull/1406
