### ISSUE TITLE
how to make apollo-cache-persist to work with gatsby ? 

### ISSUE THREAD

**Issue by mrtornado** [gatsbyjs/gatsby#13785]
Hello guys can somebody help me with apollo-cache-persist ? 
 
 I have tried 
```
persistCache({
	cache,
	storage: typeof window !== 'undefined' && window.localStorage
});
```

 but doing this gives me an Apollo error throw new Error('In order to persist your Apollo Cache, you need to pass in an underlying storage provider. '

 Anyway to use local storage for the cache with gatsby ?

**Comment by DSchau** [comment]
@mrtornado few things!

1. It looks like [apollo-cache-persist isn't really maintained](https://github.com/apollographql/apollo-cache-persist/issues/86)
1. You'll want to provide some type of fallback for storage in Node.js environment, e.g. right now that is currently setting `storage: false` in Node.js environment, which of course, won't work like you'd expect!

If you provide a [reproduction](https://gatsby.dev/reproduction) one of us could take a look to see how to implement 2.

**Comment by mrtornado** [comment]
thanks for the quick answer I removed it if it's not maintained anymore, guess I'll have to optimize my queries better to make the quicker since I'm dealing with some deep nested queries.
