### ISSUE TITLE
Failing check on open PRs with title: `ci/circleci: unit_tests_node12`

### ISSUE THREAD

**Issue by paschalidi** [gatsbyjs/gatsby#13789]
👋 to y'all! Thanks once again for maintaining such a high quality oss project, and thanks for giving us the opportunity to help you with this! 

## Description

When opening a PR several checks are being made to ensure codebase quality. 
At the moment you can see that many PRs are failing on the 
**`ci/circleci: unit_tests_node12`** check. 

This might give the impression to people who are not familiar with the codebase and therefore not familiar with the historical reasons of this failure, that something went wrong, however one can see that PRs are being merged even tho this check would fail. (a random merged PR https://github.com/gatsbyjs/gatsby/pull/13749) 

A list of random PRs that this issue is preset 
https://github.com/gatsbyjs/gatsby/pull/13766 
https://github.com/gatsbyjs/gatsby/pull/13771  
https://github.com/gatsbyjs/gatsby/pull/13762 
https://github.com/gatsbyjs/gatsby/pull/13747 
https://github.com/gatsbyjs/gatsby/pull/13743

### Steps to reproduce

1. fork [gatsby](https://github.com/gatsbyjs/gatsby)
2. open a PR. 
3. let the checks run after opening the PR. 

### Expected result

All checks are green.

### Actual result

Check `ci/circleci: unit_tests_node12` would fail on job with title `Install node modules`
while running the `yarn --frozen-lockfile` command.

**Comment by DSchau** [comment]
Hello!

This was actually fixed [here](https://github.com/gatsbyjs/gatsby/pull/13748).

So, it’s a matter of merging master in, which while non-ideal, is a fair thing to do.

As such, going to close this out. Thanks to opening!

**Comment by paschalidi** [comment]
@DSchau hey thanks for closing this, I could find the issue, sorry!
