### ISSUE TITLE
emotion is not working as expected without using Jsx pragma

### ISSUE THREAD

**Issue by aditya81070** [gatsbyjs/gatsby#13803]
## Description
Use of emotion library to style the component in [part 4 of tutorial](https://www.gatsbyjs.org/tutorial/part-four/) is not working properly. In the `layout.js` component, there is no use of `Jsx pragma` as mentioned in the [emotion documentation](https://emotion.sh/docs/css-prop#jsx-pragma) and it is causing the styles applied to be failed.
I used the `JSX pragma` at the top of my `layout.js` file and then I got the expected result. 

### Steps to reproduce

1. Follow the steps that are mentioned in the [part 4 of tutorial](https://www.gatsbyjs.org/tutorial/part-four/) to create the initial web pages.
2. run `gatsby develop`

### Expected result
The page should look like the following image:-
![](https://www.gatsbyjs.org/static/9a136a7536d2f4b315d446f6a1a83725/f911f/start.png)

### Actual result

Actual results are normal page without any effect of applied styles:-
![Screenshot from 2019-05-02 17-43-30](https://user-images.githubusercontent.com/30300772/57074568-e66feb00-6d01-11e9-9755-b5bd2827f90b.png)

### Environment

System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Languages:
    Python: 3.7.0 - /home/neo/anaconda3/bin/python
  Browsers:
    Chrome: 74.0.3729.108
    Firefox: 67.0b2
  npmPackages:
    gatsby: ^2.3.34 => 2.3.34 
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
  npmGlobalPackages:
    gatsby-cli: 2.5.12

**Comment by universse** [comment]
did you add gatsby-plugin-emotion to gatsby-config.js?

**Comment by aditya81070** [comment]
@universse  I have not added this plugin. It was not mentioned in the tutorial.

**Comment by universse** [comment]
They did though.
![image](https://user-images.githubusercontent.com/15166715/57076675-cc8fd180-6d1c-11e9-9f1b-bf3364e5d4c5.png)

**Comment by aditya81070** [comment]
@universse Sorry, I don't know how I missed that line.  Things are working smoothly now.

**Comment by universse** [comment]
No worry. I agree the tutorial could be clearer.

**Comment by aditya81070** [comment]
yeah, it should mention that you have to use `gatsby-emotion-plugin` otherwise `emotion` library will not work.
