### ISSUE TITLE
How to deploy to github pages

### ISSUE THREAD

**Issue by bpmottathai** [gatsbyjs/gatsby#13809]
I tried to deploy gatsby-starter-default available in your repo according to documentation at 

https://github.com/bpmottathai/gatsby-default-starter

https://bpmottathai.github.io/gatsby-default-starter/

I added gh-pages dependancy and added script in package.json and add pathprefix. But it not deployed. What step I am missing?

**Comment by freiksenet** [comment]
Hello @bpmottathai! Check out [this guide](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/).

**Comment by bpmottathai** [comment]
Thanks for the support, fixed with `npm run deploy`.
