### ISSUE TITLE
[docs] [workflows] Deploying to Netlify

### ISSUE THREAD

**Issue by aravindballa** [gatsbyjs/gatsby#13804]
Part of the **Top 25 Learning Workflows initiative**. See #13708 for the meta issue that this issue falls under.

# User story

As a new Gatsby user, I want to deploy my Gatsby project to Netlify.

# Evaluation

| Search | Discover | Complete | Linked | Tone | Style | Overall |
| --- | --- | --- | --- | --- | --- | --- |
| 😁 | 😐 | 😐 | 😁 | 😁 | 😐 | 😐 |

# Steps taken to implement

**1. Search**
  - Searched `gatsby deploy netlify` on Google; clicked first [result](https://www.gatsbyjs.org/docs/hosting-on-netlify/)

**2. Discover**
  - Searched `deploy netlify` on .org; First result is [Hosting on Netlify](https://www.gatsbyjs.org/docs/hosting-on-netlify/) and the others are docs with different sources.
  - Searched `gatsby deploy netlify` on .org; Results include blog articles to start with. The documentation result is not Hosting. It is [sourcing from Netlify CMS](https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/#deploying-to-netlify).
  **[rec]** Can we correct the algolia indexes?
  - Clickpath on .org:
    - Clicked _Docs_
    - Clicked _Recipies > Deploying (Does not find Netlify) > Other deployment topics > Hosting on Netlify (found)_ - **5 clicks**
  - Other Clickpath on .org:
    - Clicked _Docs_
    - Clicked _Guides > Deploying and Hosting > Hosting on Netlify (found)_ - **4 clicks**

**3. Complete**
  Followed steps in [Hosting on Netlify](https://www.gatsbyjs.org/docs/hosting-on-netlify/)
  **[rec]** Link to Quickstart is wrong
  - Created a new project from the [Quickstart](https://www.gatsbyjs.org/docs/quick-start/) guide.
  - First Method
    - Ran `gatsby build` to build the project
    - Signed up for Netlify
    - Dragged the `public` folder to Netlify
  - Second Method
    - Clicked on 'New Site from Git'
	- Authenticated to Github
	- Selected the repo
	- Deploy site
	**[rec]** We could mention how to use environment variables in Netlify. Will be helpful when working with CMS.

**4. Linked**
  - Contains useful examples/blog posts related to this topic

**5. Tone**
  - Explains what Netlify is
  - The overall tone is friendly

# Recommendations

- [x] Link to Quickstart is wrong in [Hosting on Netlify](https://www.gatsbyjs.org/docs/hosting-on-netlify/)
- [x] We could mention how to use environment variables in Netlify. Will be helpful when working with CMS.
- [ ] Can we correct Algolia indexes for `gatsby deploy netlify`?
		![image](https://user-images.githubusercontent.com/8036315/57120606-1796fc80-6d90-11e9-8e6b-a5b04490c20a.png)

**Comment by marcysutton** [comment]
As for this question, "Can we correct Algolia indexes for `gatsby deploy` netlify"? The best ways to do that are with on-page content. One recommendation would be to add the command `gatsby deploy` to the page somewhere. Alternatively, you could change the title of the page to "Deploy your Gatsby Site with Netlify Hosting" or something similar to get the important search terms in there.

**Comment by marcysutton** [comment]
Here are two more items from the feedback widget on gatsbyjs.org that might help with this workflow:

re: https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/

> "Netlify CMS allows you to have multiple fields containing markdown. I believe this example is just showing a single \"html\" catch-all markdown field."

> "Hi you are missing instructions to add ClientID and Client Secret to Access Control which I guess should be part of the Authenticating with GitHub section?"

**Comment by amberleyromo** [comment]
Note: Related to improving overall site search #16367 and #12503.

**Comment by gillkyle** [comment]
The changes on #16501 wrap up the updates to this workflow so I'm going to close this. The searching issues are being tracked at #16367 and #12503 like are posted in the comment above.
