### ISSUE TITLE
Programmatic navigate does not load page resources when used in useEffect

### ISSUE THREAD

**Issue by universse** [gatsbyjs/gatsby#13802]
Hi. I am using useEffect to check if a page exists. If it does, navigate there. However, it seems the resources for the page isn't loaded. When I refresh the page, everything is fine.

Here i'm using the same template for static and client-only routes. Take note of matchPath
gatsby-node.js
```javascript
const { resolve } = require('path')

module.exports.createPages = async ({ graphql, actions: { createPage } }) => {
  const db = await graphql(
    `
      {
        allProductsJson {
          edges {
            node {
              id
              value
            }
          }
        }
      }
    `
  )

  createPage({
    path: '/product',
    component: resolve('./src/template/product.js'),
    matchPath: '/product/*',
    context: {
      id: 'fallback'
    }
  })

  db.data.allProductsJson.edges.forEach(({ node: { id, value } }) =>
    createPage({
      path: `/product/${value}-${id}`,
      component: resolve('./src/template/product.js'),
      matchPath: undefined,
      context: {
        id
      }
    })
  )
}
```

Here i normalized data so that later I can check if route exists using id
layouts/index.js
```javascript
import React, { createContext, useState, useEffect, useMemo } from 'react'
import PropTypes from 'prop-types'
import { graphql, useStaticQuery } from 'gatsby'

export const NormalizedContext = createContext()

export default function Layout ({ children }) {
  const data = useStaticQuery(graphql`
    query {
      allProductsJson {
        edges {
          node {
            id
            value
          }
        }
      }
    }
  `)
  const [normalized, setNormalized] = useState()

  useEffect(
    () => {
      const normalized = {}
      data.allProductsJson.edges.forEach(({ node: { id, value } }) => {
        normalized[id] = { id, value }
      })
      setNormalized(normalized)
    },
    [data.allProductsJson.edges]
  )

  return (
    <NormalizedContext.Provider value={normalized}>
      {children}
    </NormalizedContext.Provider>
  )
}
```

Here i check if route exists and redirect.
template/product.js
```javascript
import React, { useContext, useEffect, useState } from 'react'
import { graphql, navigate } from 'gatsby'

import { NormalizedContext } from '../layouts'

export default function ProductTemplate ({
  data: { productsJson },
  location,
  pageContext
}) {
  const normalized = useContext(NormalizedContext)
  const [product, setProduct] = useState(() => productsJson)

  // here i get id from location.pathname and check if id exists in normalized data
  useEffect(
    () => {
      if (!normalized) return

      const pathname = location.pathname.endsWith('/')
        ? location.pathname.slice(0, -1)
        : location.pathname
      const id = pathname.split('/').pop()

      if (normalized[id]) {
        const { value } = normalized[id]
        navigate(`/product/${value}-${id}`)
      }
    },
    [location.pathname, normalized]
  )

  return product ? JSON.stringify(product) : 'client product route'
}

export const pageQuery = graphql`
  query($id: String!) {
    productsJson(id: { eq: $id }) {
      id
      value
    }
  }
`
```

_redirects
```
/product/*  /product  200
```

repo https://github.com/universse/navigate-bug
site https://relaxed-banach-32e4ce.netlify.com/

expected: when i navigate to https://relaxed-banach-32e4ce.netlify.com/product/1, it navigates to https://relaxed-banach-32e4ce.netlify.com/product/a-1. Here it's supposed to load data but does not. Things are fine when refresh page or access directly.

**Comment by sidharthachatterjee** [comment]
If I understand correctly, it looks like we're navigating to `/product/${value}-${id}` when refreshing but `/product/*` on `navigate` and therefore showing data in one case and not in the other (page queries don't work in client side routes)

@pieh Thoughts?

**Comment by wardpeet** [comment]
It's not really an issue with useEffect. It's more or less how we use reach router but it's also a bit weird what you do.

We're not capable of setting pages & a catchall on the same route. A workaround you can do is remove the catch-all route and just implement it in your 404.

For example put this in your 404:
```
import React from 'react';
import { navigate } from 'gatsby'
import { NormalizedContext } from '../layouts'

const NotFoundPage = () => {
  const normalized = React.useContext(NormalizedContext)

  React.useEffect(() => {
    if (!normalized) return

    const pathname = location.pathname.endsWith('/')
      ? location.pathname.slice(0, -1)
      : location.pathname
    const id = pathname.split('/').pop()

    if (normalized[id]) {
      const { value } = normalized[id]
      navigate(`/product/${value}-${id}`)
    }
  })

  if (location.pathname.startsWith('/product/')) {
    return null;
  }

  return <React.Fragment>Not found</React.Fragment>;
}

export default NotFoundPage;
```

**Comment by universse** [comment]
Thanks for the reply. Here's how I decided on this on solution.

The site I'm working on have user-generated contents. What I'm trying to do is to redirect if route with id already exists. If not, fetch using api to handle time between builds when routes for newly user-generated content haven't been created yet.

I considered using createRedirect. Yet, quite some time back while researching some other issue, I read somewhere that having a huge redirect file isn't recommended. I can't really find the original source so I might be mistaken here.

I also didn't go with the 404 solution. As mentioned above, when routes doesn't exist, the site will fetch data from database. And the renderings here will be the same as the /product route, as such causing duplicated rendering logic. It is also not optimal in the sense that I have other routes with similar logic for handling user-generated contents. As such, 404 page would need to handle different cases for different routes, which I think is not ideal.

Would be interested in futher hearing your thoughts on this.

**Comment by antoinerousseau** [comment]
I am having a similar issue where a `navigate()` does not trigger the destination's `useEffect`.

**Comment by universse** [comment]
Do you mind sharing the useEffect code? I think your use case is different from mine.

**Comment by AdamZaczek** [comment]
Interestingly, for me navigate does not work at all from useEffect level. I'm using it in wrapRootElement but I also tried wrapPageElement as well :/

**Comment by Jaikant** [comment]
Just so it could help someone else - I was seeing a similar issue where after a login and a subsequent programmatic `navigate` my query value was null. It turned out the graphql query was picking it's data from the cache, I had to do a refetch. This is using apollo client.

**Comment by LekoArts** [comment]
The original question was answered so I'll close this one.

**Comment by ReactMad** [comment]
@universse I think your case is exactly the same as my issue.
I navigate to the page when specific data I need has arrived but there is 404 page.
After refresh all is fine. Could you kindly let me know what is the solution?
