### ISSUE TITLE
[gatsby-image] Add rootMargin option

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13815]
## Summary

Add a option to modify the [rootMargin](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Creating_an_intersection_observer) property of the IntersectionObserver of gatsby-image. To start, we are thinking of passing a prop for the <Image/> component so we can set the rootMargin on individual images.

### Basic example

We could do something like this:

```jsx
<Img rootMargin='20px' />
```

This image then would have the rootMargin set to `20px` the current setting is `200px` so we could possibly use this as the default when a user doesn't add this prop.

This file will be need to be modified to add this: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js

### Motivation

It would be useful to allow users to customize the rootMargin so if they wish to load the images earlier while scrolling down, they can change the bounding box for when the IntersectionObserver would be triggered.

**Comment by grantglidewell** [comment]
I'm happy to take a stab at this, ill have a PR shortly

**Comment by grantglidewell** [comment]
https://github.com/gatsbyjs/gatsby/pull/13816
a first pass

**Comment by Oliweer** [comment]
The default 200px isn't responsive, this causes big monitors which most likely have wifi access to have the least amount of scroll percentage wise until next images compared to mobile. Wouldn't it be advisable to change the default 200px to something like 20vh?

**Comment by DSchau** [comment]
Closing due to the reasons [@KyleAMathews specified in #13816](https://github.com/gatsbyjs/gatsby/pull/13816#issuecomment-488831605)

Thanks all!
