### ISSUE TITLE
[docs] Possible page on incrementally migrating non-react site to Gatsby

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13813]
## Summary

In certain contexts, a developer may have an existing website and they wish to start using Gatsby, but do not have the capabilities to do a rewrite of the entire site in Gatsby and rather wish to incrementally update routes over time from the legacy codebase to Gatsby.

With this, there would be points where Gatsby and the legacy codebase would exist on the same domain. Is this something that can be done with Gatsby as of Today, and if so, what does that entail? If not, is this something that should be built into Gatsby so this is possible?

**Comment by sidharthachatterjee** [comment]
As far as I understand, this should be possible as of today. One can build individual pages with Gatsby and serve them on URLs independent of the root URL. 

`pathPrefix` makes this possible. 

Also now that `assetPrefix` is here, thanks to @DSchau, we can _also_ support scenarios where HTML and assets need to be served separately — by serving Gatsby's built HTML pages in the (legacy) existing setup and assets separately on a CDN.

**Comment by grantmoran** [comment]
I'd like to take this on.

I'm currently working on an incremental migration and feel comfortable writing about the general workflow and challenges/considerations that should be factored into the decision to migrate incrementally. The latter mostly helping novice users steer clear of common mistakes & repercussions during site migrations in general.

If no one is on this already, feel free to assign me. I have time over the next two weeks I can set aside to carve out something for review.

**Comment by marcysutton** [comment]
Are you still interested, @grantmoran? That would be awesome!

**Comment by Jeddf** [comment]
Could I snap this one up?

As well as the use case laid out for pathPrefix and assetPrefix, it looks like an interesting entry point for less js familiar users. Lots of opportunities for pointing out incremental next steps into Gatsby/React/CMS beyond the initial basic, static migration.

Would definitely get a draft PR going on it early!

**Comment by marcysutton** [comment]
Sounds great @jeddf, go for it!
