### ISSUE TITLE
[docs] Add page on migrating Create React App site to Gatsby

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#13812]
## Summary

It may be good to research and dive into seeing if having a page on migrating from CRA (Create React App) to Gatsby would be beneficial to the community.

### Motivation

Some people may already have a React site but wish to use Gatsby's tools to better structure their data or use it for it's SSR capabilities, so it would be good to have a workflow to describe the migration progress

**Comment by lannonbr** [comment]
@pieh found that a community member has already written an article on their blog on a CRA -> Gatsby guide: https://khaledgarbaya.net/articles/moving-from-create-react-app-to-gatsby-js

**Comment by marcysutton** [comment]
@gillkyle have been discussing a blog post on this, I think a doc could be useful as well (in a new section of [Releases & Migration](https://www.gatsbyjs.org/docs/releases-and-migration/) maybe?). In general here's how I'm thinking of content strategy:

- Blog posts are primarily made for storytelling and case studies
- Docs are more persistent reference guides that go beyond any one case study or situation

I could see a benefit in having both–a blog post could introduce some project-specific or time sensitive bits, while pointing to a more canonical reference doc. Here's a Google doc where we started collaborating on ideas: https://docs.google.com/document/d/1APy4q-oaDhYNHyycZ0Um8EPdDRtQqdSABII2ImByFm0/edit#

**Comment by marcysutton** [comment]
As there is a [blog post](https://www.gatsbyjs.org/blog/2018-06-18-moving-from-create-react-app-to-gatsby-js/) on this already, we should focus our efforts on creating a reference doc instead! Good find, @gillkyle. If you have any bandwidth to take this on, a doc would be a great thing to work on. I'll assign it to you if that's ok!

**Comment by gillkyle** [comment]
Yeah I can take this on! I'll get to it as soon as I can 👍

**Comment by gillkyle** [comment]
Merged in #14626
