### ISSUE TITLE
GraphQL 'non string' Context

### ISSUE THREAD

**Issue by OllieJT** [gatsbyjs/gatsby#13822]
## Summary
I've been going round in circles as to how I can transform a string into a custom type. I am trying to pass a _sortKey_ into a Shopify query. For example;
- CREATED_AT
- UPDATED_AT
- TITLE
- PRODUCT_TYPE
- VENDOR
- BEST_SELLING
- PRICE
- ID
- RELEVANCE
The issue is that **none of these should be strings**. When I pass them as context in gatsby-node.js it spits out the error _ReferenceError: CREATED_AT is not defined_, It thinks they are undefined variables. However, when I pass them as strings GraphQL thinks they are invalid.

#### Context
Arguements: ![Arguements](https://cdn.discordapp.com/attachments/537691356487876624/573588393783722050/SPOILER_Screenshot_2019-05-02_at_21.14.57.png "Query Arguements")

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`:

```javascript
...
const allStores = await graphql(`
    {
      allPrismicStore {
        totalCount
        edges {
          node {
            uid
            data {
              query
              sortkey
              reverse
            }
          }
        }
      }
    }
  `);

  allStores &&
    allStores.data.allPrismicStore.edges.forEach(edge => {
      createPage({
        path: storeUrl(edge.node.uid),
        component: path.resolve('./src/templates/store.js'),
        context: {
          uid: edge.node.uid,
          query: edge.node.data.query,
          sortkey: edge.node.data.sortkey // This is "CREATED_AT" but I need it to NOT be a string
          reverse: Boolean(edge.node.data.reverse),
        },
      });
    });
...
```
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 
`page query`:
```javascript
export const query = graphql`
  query StorePageQuery(
    $uid: String!
    $query: String = "available_for_sale:true AND NOT product_type:Custom Graphics"
    $sortkey: Shopify_ProductSortKeys!
    $reverse: Boolean!
  ) {
    shopify {
      shop {
        products(
          first: 50
          reverse: $reverse
          sortKey: $sortkey
          query: $query
        ) {
          edges {
            ...shopifyProductCard
          }
        }
      }
    }
  }
`;
```

**Comment by freiksenet** [comment]
Thank you for the issue!

I don't quite understand the problem yet :(. You are storing the values inside prismic as strings, so they are passed through the context as strings. Do you mean that shopify encodes enums as non strings? Could you send the error that you get when you pass sortKey as string? Ideally, I wonder if you could create a small reproduction case so I could see what is wrong.

**Comment by muescha** [comment]
Maybe you need also to add the schema definition for `Shopify_ProductSortKeys` or change this definition to just string?

**Comment by muescha** [comment]
It works if you write `sortKey: CREATED_AT` or `sortKey: createdAt`?
