### ISSUE TITLE
UseStaticQuery resulting in undefined

### ISSUE THREAD

**Issue by imrandyk** [gatsbyjs/gatsby#13821]
So I have a query that works in graphql and if I change the query to use the same one that.s in the seo component it works just fine. I'm sure it's something simple but any help would be appreciated.

```
import { useStaticQuery, graphql } from "gatsby"

const results = ({ filter, targetId }) => {
  const { filters } = useStaticQuery(
    graphql`
      query {
        allFile(filter: { sourceInstanceName: { eq: "filters" } }) {
          edges {
            node {
              relativeDirectory
            }
          }
        }
      }
    `
  )
...


  console.log({ filters }) // always undefined
  return (
    <>
...
    </>
  )
}

export default results
```

Here is the revelavent portion of my `gatsby-config.js`

```
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/components/playground/filters`,
        ignore: [`**/index*`, `**/base*`],
        name: `filters`,
      },
    },
```

**Comment by DSchau** [comment]
@imrandyk we'll need a lot more info to begin triaging this!

Could you provide a [reproduction](https://gatsby.dev/reproduction) and any other detail as to how this bug was encountered?

Thanks!

**Comment by imrandyk** [comment]
> @imrandyk we'll need a lot more info to begin triaging this!
> 
> Could you provide a [reproduction](https://gatsby.dev/reproduction) and any other detail as to how this bug was encountered?
> 
> Thanks!

Sorry, I hit enter by mistake and it saved the default issue. I have corrected it.

**Comment by DSchau** [comment]
@imrandyk you're pulling the wrong field from the data.

The query returns a shape (as JSON) like:

```json
{
  "allFile": {
    "edges": []
  }
}
```

so you'll want to change your destructuring to:

```js
import { useStaticQuery, graphql } from "gatsby"

const results = ({ filter, targetId }) => {
  const { allFile } = useStaticQuery(
    graphql`
      query {
        allFile(filter: { sourceInstanceName: { eq: "filters" } }) {
          edges {
            node {
              relativeDirectory
            }
          }
        }
      }
    `
  )
...


  console.log({ allFile })
```

**Comment by imrandyk** [comment]
@DSchau Took me a few but I get it, thanks!

**Comment by muescha** [comment]
I was not able to find the difference - but the diff tool done it:

```diff
-const { filters } = useStaticQuery(
+const { allFile } = useStaticQuery(
```
