### ISSUE TITLE
gatsby-link does not work with target="_blank"

### ISSUE THREAD

**Issue by unyo** [gatsbyjs/gatsby#13825]
## Description

```<Link to={slug} target="_blank">hello</Link>``` does not open a new tab in the browser.

### Steps to reproduce

Create new gatsby project, add:
    ```<Link to='/some-path' target="_blank">wut</Link>```
And click on it

### Expected result

New tab is opened

### Actual result

Link opens in existing tab

### Environment
```

  [4mSystem:[0m
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Shell: 3.2.57 - /bin/bash
  [4mBinaries:[0m
    Node: 11.11.0 - /usr/local/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.npm-global/bin/npm
  [4mBrowsers:[0m
    Chrome: 73.0.3683.103
    Firefox: 66.0.1
    Safari: 12.1
  [4mnpmPackages:[0m
    gatsby: ^2.1.0 => 2.1.32 
    gatsby-image: ^2.0.29 => 2.0.33 
    gatsby-plugin-favicon: ^3.1.5 => 3.1.5 
    gatsby-plugin-google-analytics: ^2.0.14 => 2.0.17 
    gatsby-plugin-netlify: ^2.0.10 => 2.0.12 
    gatsby-plugin-netlify-cms: ^3.0.12 => 3.0.14 
    gatsby-plugin-purgecss: ^3.1.0 => 3.1.0 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.9 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-sass: ^2.0.10 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.20 => 2.0.28 
    gatsby-plugin-styled-components: ^3.0.5 => 3.0.7 
    gatsby-remark-copy-linked-files: ^2.0.9 => 2.0.10 
    gatsby-remark-images: ^3.0.3 => 3.0.9 
    gatsby-remark-relative-images: ^0.2.1 => 0.2.2 
    gatsby-source-filesystem: ^2.0.20 => 2.0.25 
    gatsby-transformer-remark: ^2.2.5 => 2.3.3 
    gatsby-transformer-sharp: ^2.1.13 => 2.1.17 


```

**Comment by nnnkit** [comment]
Gatsby uses @reach/router and the `Link` component has `onClick` handler that overrides any default functionality of the anchor element.
https://github.com/reach/router/blob/master/src/index.js#L391

**For external links instead of `Link` component just use an `<a>`**

**Comment by imkrunal** [comment]
Gatsby Link is used for internal routing you can use that for external routing. Opening a new window is equal to external routing so you have to use anchor tag for that.
```html
<a href="/some-path" target="_blank" >some text</a>
```

**Comment by sidharthachatterjee** [comment]
^ What @nnnkit and @imkrunal said

Marking this as answered and closing. Thank you everyone!

**Comment by muescha** [comment]
But when the path is an "internal" link to an other datsbyjs page  I use the path prefix?

Then the `a` tag has not included the prefix?

**Comment by kuworking** [comment]
Then I assume there's no way to open an internal link within a new window/tab while using `Link`, so that we lose the advantages of `Link` for this use cases

**Comment by cmarabate** [comment]
But why? There are absolutely times when I want to open an internal link in a new tab. It is a shame that Link does not let us add a target because the pages load so much faster when using Link. It should not matter if I want to open it in a new tab or not, I should be able to use Link to do either.

**Comment by bilguunabi** [comment]
Any updates on this one? 
When I use <Link> it works perfectly. But I need to create new tab.
When I use <a> it gives me 404 error (Maybe it's related to azure deployment). 
<a> tag works locally but when I publish it, it doesn't work.

**Comment by tayrotayro** [comment]
As of now, you need to switch out the Link tag and just use an "a" tag and make target="_blank". This worked fine for me. @bilguunabi

**Comment by bilguunabi** [comment]
@tayrotayro  Yeah man I tried. But the strangest thing is that the "new tab" is not working.
It gives me a 404 error. I copied the whole link and pasted it elsewhere, it still not working. 
I'm just so irritated with this issue.

**Comment by tyirvine** [comment]
Thank you to the Gatsby team for adding this in! For anyone viewing this thread in the future, it can now be used like so → `<Link target='_blank'/>` I believe `rel` is now supported as well.

**Comment by GregorTr** [comment]
Is this working for everybody?
Its not working for me (Gatsby V5). The rendered anchor element has the `target="_blank"` attribute, but still opens in the same tab!
