### ISSUE TITLE
how to display a custom notification of prograssive webapp with gatsby

### ISSUE THREAD

**Issue by bpmottathai** [gatsbyjs/gatsby#13831]
I deployed a gatsby website with manifest and offline plugin. I want to display a custom notification for pwa in chrome and ios safari. I found a link [here](https://gist.github.com/jsanta/9745813617f78bc6a21ce5a24fb0039e). Where to put it in gatsby?

**Comment by sidharthachatterjee** [comment]
@bpmottathai Looking at the linked gist, since it's arbitrary JavaScript, you should be able to put it in your root React component's `componentDidMount`

**Comment by bpmottathai** [comment]
Please tell me the exact file or give updated file code. Newbie here

**Comment by muescha** [comment]
Did you see this links?

It is just a guess. But maybe this meet your requirements:

https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/

https://medium.com/@mjadav/build-pwa-with-gatsby-9cbaa3ee93cc

**Comment by bpmottathai** [comment]
No. That is not I am asking. I need info about custom alert for pwa if a user accidentally close add to home screen notification
