### ISSUE TITLE
Events Page: Missing content after loading on iPhone

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#13844]
## Description

Events Page: Missing content after full page load complete on iPhone

### Steps to reproduce

i open the gatsby [community events](https://www.gatsbyjs.org/contributing/events/) page on iPhone 6S+ (iOS 12.1.3) 
i tested it in Safari app and Chrome app

### Expected result

- i see the full events list

### Actual result

- while loading i see the full events list
- after loading complete the events are empty

**Comment by muescha** [comment]
Screenshot:

![327D68C4-0EF5-428B-ACC4-D4695F926AB0](https://user-images.githubusercontent.com/184316/57090618-854b1600-6d07-11e9-944b-92063ec31893.png)

**Comment by muescha** [comment]
Screencast:

![4D7E1E6B-576E-4D59-8183-EFE80AA3CF40](https://user-images.githubusercontent.com/184316/57091518-b88ea480-6d09-11e9-9e3f-d4e1fea1d5b2.gif)

Note: I manually the page while loading to see the events section

**Comment by muescha** [comment]
remote debug console on mac connected to iphone:

![Bildschirmfoto 2019-05-03 um 19 18 20](https://user-images.githubusercontent.com/184316/57154485-47b6bd80-6dd9-11e9-988f-38d446d9917f.png)


the content of the .js file:

```json
{"pageContext":{"isCreatedByStatefulCreatePages":true}}
```

**Comment by DSchau** [comment]
Yeah - I can confirm this. This seems to be specific to Safari (has nothing to do with mobile or desktop).

Will take a look!

**Comment by muescha** [comment]
yes i can canfirm on safari on mac is the same problem
