### ISSUE TITLE
Gatsby v1 vs v2 Client-side Environment Variable Behavior - `GATSBY_MY_CLIENT_CONFIGS` No Longer Available...

### ISSUE THREAD

**Issue by busticated** [gatsbyjs/gatsby#13846]
hey all :wave: - i'm trying to upgrade from v1 to v2 and i'm hitting an issue w/ how env vars how handled under v2

## Description

i have a private npm module that exposes some pre-processed env vars server-side like so:

```
ENV_VARS.forEach(key => process.env[key] = JSON.stringify(publicSettings));
```

where `ENV_VARS` are keys that look like `MY_CLIENT_CONFIGS` and `GATSBY_MY_CLIENT_CONFIGS`

the implementation is swapped out when compiling the client using a webpack alias:

```
resolve: {
    alias: {
        '@myorg/config': '@myorg/config/dist/client/index.js'
    }
},
```

when that module is loaded client-side, it then looks-up the env var keys like so:

```
function getExportedSettings(){
    const env = process ? (process.env || {}) : {};
    let index = -1;
    let json;

    while (++index < ENV_VARS.length){
        const key = ENV_VARS[index];

        if (env[key]){
            json = env[key];
            break;
        }
    }

    if (!json){
        throw new Error('unable to load client config settings');
    }
    return JSON.parse(json);
}
```

under gatsby v1 (`v1.9.279` specifically) this all worked fine. since `GATSBY_MY_CLIENT_CONFIGS` used the special prefix it, was exposes as expected to the client app.

under gatsby v2 i now get: `WebpackError: unable to load client config settings`

`console.log`'ing all the things, i see that `process.env['GATSBY_MY_CLIENT_CONFIGS']` is actually available but `process.env` is just a plain object so `process.env[key]` (or equivalent) does not work.

anyone aware of a work-around? i tried setting the webpack config directly:

```
actions.setWebpackConfig({
    plugins: [
        plugins.define({
            'process.env': {
                MY_CLIENT_CONFIGS: JSON.stringify(process.env.MY_CLIENT_CONFIGS)
            }
        })
    ]
});
```

but that doesn't help :frowning:

i'm also aware of https://github.com/gatsbyjs/gatsby/pull/10030 (https://github.com/gatsbyjs/gatsby/pull/10030#issuecomment-443053497 specifically) but theoretically my webpack define customization _should_ side-step that (as it does it my other non-gatsby apps). 

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.15.1 - /usr/local/bin/node
    npm: 5.10.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Safari: 12.1
  npmPackages:
    gatsby: ^2.1.19 => 2.1.19 
    gatsby-cli: ^2.4.12 => 2.4.12 
    gatsby-image: ^2.0.30 => 2.0.30 
    gatsby-plugin-netlify: ^2.0.11 => 2.0.11 
    gatsby-plugin-react-helmet: ^3.0.7 => 3.0.7 
    gatsby-plugin-sharp: ^2.0.23 => 2.0.23 
    gatsby-plugin-sitemap: ^2.0.6 => 2.0.6 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-source-contentful: ^2.0.33 => 2.0.33 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-transformer-sharp: ^2.1.15 => 2.1.15 
    gatsby-transformer-yaml: ^2.1.8 => 2.1.8 
```

**Comment by jonniebigodes** [comment]
@busticated see if the [documentation](https://www.gatsbyjs.org/docs/environment-variables/) helps you in any way, shape or form, or if [gatsby-plugin-env-variables](https://www.gatsbyjs.org/packages/gatsby-plugin-env-variables/) plugin could shed some insight, see if the code helps you out at least to get you started in fixing the issue.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by busticated** [comment]
@LekoArts here ya go:

https://github.com/busticated/gatsby-env-vars

pull that down, run `npm i`, then run `npm run start:prod` and you'll see the `WebpackError: unable to load client config settings` error.

thanks for taking a look :pray::+1:

**Comment by busticated** [comment]
@LekoArts 

here's the crux of it i think:

in v2, my env var related client-side bits are transformed into:

```js
var ENV_VARS = ['MY_CLIENT_CONFIGS', 'GATSBY_MY_CLIENT_CONFIGS'];

function getExportedSettings() {
  var env = process ? {} || {} : {};
  var index = -1;
  var json;

  while (++index < ENV_VARS.length) {
    var key = ENV_VARS[index];

    if (env[key]) {
      json = env[key];
      break;
    }
  }

  if (!json) {
    console.log('FOUND:', "{\"foo\":1,\"bar\":false,\"baz\":{\"qux\":[1,2,3]}}");
    throw new Error('unable to load client config settings');
  }

  return JSON.parse(json);
}
```

note that `const env = process ? (process.env || {}) : {};` is transformed into `var env = process ? {} || {} : {};`

whereas in v1, my client-side bits are transformed into:

```js
var ENV_VARS = ['MY_CLIENT_CONFIGS', 'GATSBY_MY_CLIENT_CONFIGS'];

function getExportedSettings() {
  var env = process ? {
    NODE_ENV: "production",
    PUBLIC_DIR: "/opt/build/repo/public",
    MY_CLIENT_CONFIGS: "{\"foo\":1,\"bar\":false,\"baz\":{\"qux\":[1,2,3]}}"
  } || {} : {};
  var index = -1;
  var json;

  while (++index < ENV_VARS.length) {
    var key = ENV_VARS[index];

    if (env[key]) {
      json = env[key];
      break;
    }
  }

  if (!json) {
    console.log('FOUND:', "{\"foo\":1,\"bar\":false,\"baz\":{\"qux\":[1,2,3]}}");
    throw new Error('unable to load client config settings');
  }

  return JSON.parse(json);
}
```

note that in this scenario `const env = process ? (process.env || {}) : {};` includes both mine and gatsby's env vars after transformation.
