### ISSUE TITLE
Update starters / gatsbyjs after creating site

### ISSUE THREAD

**Issue by mrkd** [gatsbyjs/gatsby#13855]
## Relevant information

I have created a new site using this starter:

`https://github.com/alxshelepenok/gatsby-starter-lumen`

Since I have created my site there have been a number of commits.

Is there an official way to update starters from the source?

### Environment (if relevant)

```
$ gatsby info

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Shell: 4.4.12 - /usr/local/bin/bash
  Binaries:
    Node: 11.11.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 3.7.3 - /Users/mark/anaconda3/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Safari: 12.1
  npmGlobalPackages:
    gatsby-cli: 2.5.12
    gatsby: 1.5.0
```

**Comment by LekoArts** [comment]
You can add the source repo as an upstream origin and pull new changes. But you'll have to deal with merge conflicts then.

The much better approach are [Gatsby Themes](https://www.gatsbyjs.com/gatsby-themes). When they're more widely used you'll be able to update a package :)

Closing this issue as answered, thanks for the question!
