### ISSUE TITLE
Should my module's JavaScript files be causing errors during the Webpack HTML building phase?

### ISSUE THREAD

**Issue by ryandrew14** [gatsbyjs/gatsby#13863]
## Summary
When I try to build my site with `gatsby build`, the `amplitude-js` node module won't build and throws an error during the build-html phase. Any help/Webpack enlightenment would be greatly appreciated! Trying to turn this into a learning experience.
## Relevant information
I was able to solve this using the ever-helpful docs ([this page](https://gatsby.dev/debug-html)) by excluding the module from the HTML build, but I still would like to get more information about how this could potentially be fixed in _their_ codebase, and about the root cause of the error.

Here's the error it throws:
```
success Building production JavaScript and CSS bundles — 15.044 s

error Building static HTML failed

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

  773 |     if (windowLocalStorageAvailable()) {
  774 |       localStorage = window.localStorage;
> 775 |     } else if (window.globalStorage) {
      |      ^
  776 |       // Firefox 2-3 use globalStorage
  777 |       // See https://developer.mozilla.org/en/dom/storage#globalStorage
  778 |       try {


  WebpackError: ReferenceError: window is not defined
```
I'm relatively new to Webpack -- should the html build phase even be touching `.js` files like this? I've read that Webpack is usually smart enough to know that `window` is global but this doesn't seem to be working correctly here (I'm guessing the loader you guys use here isn't the one that knows about `window`).

### Environment (if relevant)
Here's a [link to the site it was failing on](https://github.com/sandboxneu/sandboxneu.com/tree/add-analytics), and here's the [link to the file](https://github.com/amplitude/Amplitude-JavaScript/blob/master/src/localstorage.js) in the package that wasn't building right.

```
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.3
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.32 => 2.4.2 
    gatsby-background-image: ^0.3.4 => 0.3.6 
    gatsby-image: ^2.0.37 => 2.0.41 
    gatsby-plugin-manifest: ^2.0.28 => 2.1.1 
    gatsby-plugin-offline: ^2.0.25 => 2.1.0 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.32 => 2.0.36 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-source-filesystem: ^2.0.29 => 2.0.33 
    gatsby-transformer-json: ^2.1.11 => 2.1.11 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.19 
  npmGlobalPackages:
    gatsby-cli: 2.5.12
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: 
```javascript
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /amplitude-js/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
```
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
> how this could potentially be fixed in their codebase

When referencing browser globals like e.g. `window` they would need to add a check if the current file is in a SSR context (without the `window` being available) and skip that part until it runs in the browser.

> should the html build phase even be touching .js files like this?

It takes all the code you use, so also the packages you use.

> Webpack is usually smart enough to know that window is global but this doesn't seem to be working correctly here

The `window` object isn't available at build-time (in Node). Remember, Webpack doesn't run this code in the browser but on your machine with Node.

> I'm guessing the loader you guys use here isn't the one that knows about window

We use "normal" Webpack :)

Closing this issue as answered then! Thanks for opening the issue.
