### ISSUE TITLE
Add linting when using gatsby-plugin-emotion

### ISSUE THREAD

**Issue by docwhat** [gatsbyjs/gatsby#13861]
As a developer, I write CSS in my React components using Emotion 10 (via the `gatsby-plugin-emotion`).

However, I discover a whole chunk of my CSS was broken and I couldn't tell.

The closest I got to being able to detect these problems was using Firefox with its (unreliable but useful) css console warnings.

Since emotion, etc. all expand my written CSS to include vendor extensions and other tricks, it seems like the best time to lint my CSS would be before emotion expands everything.

**Comment by universse** [comment]
Hey you can check out https://www.styled-components.com/docs/tooling#stylelint
It's fully compatible with emotion-js

**Comment by LekoArts** [comment]
I'd also recommend using stylelint then! Closing this as answered :)

**Comment by docwhat** [comment]
I got it working but it isn’t as smooth as everything else is. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
