### ISSUE TITLE
Allow unicode file path for gatsby-config

### ISSUE THREAD

**Issue by Ta2Rim** [gatsbyjs/gatsby#13865]
## Description
![image](https://user-images.githubusercontent.com/41318449/57191994-95acfc00-6f66-11e9-9a11-ef6c9c6fb568.png)

when I run `gatsby devlop` causes error like above.

I've named my PC named '신태림' is my Korean name)
and I'd like to use gatsby on desktop directory.
but Windows make desktop directory located in the directory named PC name. (in this case, \신태림 exists on path)

I think it has to be solved for non-english speaking country

### Steps to reproduce

locate gatsby directory in some directory named with Unicode 
copy this --> 신태림

https://github.com/Ta2Rim/taesdevblog

### Expected result

Compiled successfully
( When I located my gatsby project in C drive, it works )

### Actual result
![image](https://user-images.githubusercontent.com/41318449/57191994-95acfc00-6f66-11e9-9a11-ef6c9c6fb568.png)

![image](https://user-images.githubusercontent.com/41318449/57192144-27693900-6f68-11e9-8079-c19b09056f18.png)

error occurs

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.13.0 - C:\Users\신태림\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.14
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.3.34 => 2.4.2
    gatsby-image: ^2.0.41 => 2.0.41
    gatsby-plugin-manifest: ^2.0.29 => 2.1.1
    gatsby-plugin-offline: ^2.0.25 => 2.1.0
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.0.35 => 2.0.36
    gatsby-source-filesystem: ^2.0.33 => 2.0.33
    gatsby-transformer-remark: ^2.3.12 => 2.3.12
    gatsby-transformer-sharp: ^2.1.18 => 2.1.19

**Comment by LekoArts** [comment]
Seems related to: https://github.com/gatsbyjs/gatsby/pull/13882

**Comment by Ta2Rim** [comment]
related to #14126
