### ISSUE TITLE
Build issues when using aframe-react with Gatsby

### ISSUE THREAD

**Issue by andrewrutter** [gatsbyjs/gatsby#13870]
I am working on a prototype web application which will be using aframe to render some 3d scenes with static content being liked in. I am using Gatsby to pull this all together but running into an issue when running a build: 
```
  WebpackError: ReferenceError: window is not defined

  - aframe-master.js:75415 Object.148.../package
    [lib]/[aframe]/dist/aframe-master.js:75415:1
```
Is there any reasonable workaround for this? Essentially AFrame/React are going to have to run on certain pages to handle the internal canvas/webgl state - we have a number of flat HTML pages that would handle exposing the site structure for crawlability along with actual flat content pages, the 3d spaces are for an extra layer of navigation.

Thanks

**Comment by LekoArts** [comment]
Please have a look at [Debugging HTML Builds](https://www.gatsbyjs.org/docs/debugging-html-builds/) to see how to solve your (common) `window is not defined` error :)

Closing this issue as answered, please let us know when you need further help. Thanks!
