### ISSUE TITLE
[gatsby-source-contentful] Content sourced from Contentful appears in other query types

### ISSUE THREAD

**Issue by vcarl** [gatsbyjs/gatsby#13873]
## Description

Also described in #10254. Queries for `allMarkdownRemark` and `allMdx` contain all entries that I can otherwise find from `allContentfulBlogPost`. These redundant entries are missing several fields that are found on the `Contentful` queries that make them unusable—`title`, `slug`, `node_locale`, to name 3. As #10254 concludes, I'm working around this by filtering them out, which is easy enough as they have no `absoluteFilePath`.

This isn't mentioned in the [`gatsby-source-contentful`](https://www.gatsbyjs.org/packages/gatsby-source-contentful/) plugin page, and the data returned is unhelpful enough that I'm not sure it's intentional.

I can put together a repro, but as it relies on a Contentful account it's a little awkward to set up. [I made a Gist](https://gist.github.com/vcarl/15a387a62047aafcc5e0169bc7ecbc27) of the markdown + Contentful query results.

### Steps to reproduce

* Set up a Gatsby site with:
  * `gatsby-source-filesystem`
  * `gatsby-source-contentful`
    * set up Contentful example site, which includes sample posts
  * `gatsby-mdx`
  * `gatsby-transformer-remark`
* Add `.md` and `.mdx` files in your file source location
* Query `allMarkdownRemark` and `allMdx`.

### Expected result

Only the `.md` or `.mdx` files are returned

### Actual result

All Contentful posts are interleaved with the files sourced from content.

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 2.5.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.3
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.4.2 => 2.4.2 
    gatsby-image: ^2.0.41 => 2.0.41 
    gatsby-mdx: ^0.6.3 => 0.6.3 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
    gatsby-remark-copy-linked-files: ^2.0.12 => 2.0.12 
    gatsby-remark-prismjs: ^3.2.9 => 3.2.9 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-contentful: ^2.0.55 => 2.0.55 
    gatsby-source-filesystem: ^2.0.33 => 2.0.33 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
  npmGlobalPackages:
    gatsby-cli: 2.5.12
```

**Comment by rongpenl** [comment]
Same issue here.

**Comment by LekoArts** [comment]
@freiksenet 	@pieh any clues on that?

**Comment by elmariachi111** [comment]
same here (and I think this is related: https://github.com/gatsbyjs/gatsby/issues/10254) . For SEO / google: since the createPagesApi relies on a "path" field (that I got in my MD files but not on ALL the content in Contentful, the page build stage might fail saying `Your site's "gatsby-node.js" must set the page path when creating a page` . The origin of this problem seems to be that the Markdown nodes are created by gatsby-transformer-remark and he simply doesn't care if the source is a local md file or a contenful item ;) . To hack a solution you can tell your Gql query that's supposed to read local md files to be filtered like 

```graqhl
 {
   allMarkdownRemark(
      filter: {fileAbsolutePath: {ne: null} },
    ) {
      edges {
        node {
          frontmatter {
            title
            path
            order
            radius
          }
        }
      }
    }
```
since there is no `fileAbsolutePath` on Contentful nodes ;)

**Comment by freiksenet** [comment]
We only create one MarkdownRemark type (same for Mdx) and when plugins use that to process their data, those kind of issues happen. I'll think about the ways to fix this. Thank you for the report! :purple_heart:

**Comment by freiksenet** [comment]
In the meantime, @elmariachi111 solution would work to solve your issue @vcarl.

**Comment by vcarl** [comment]
Yep! I mentioned in the original ticket that I'm using that method to work around it for the time being.

**Comment by vcarl** [comment]
I can't add a label but This isn't stale!

**Comment by takapiro99** [comment]
I've finally found my way here. I'm having trouble with this too. 

Has any solution been found?

**Comment by cmosgh** [comment]
I noticed that gatsby created a better graphql schema when there was a published content per content type, maybe this is a clue as per why is this incomplete schema generation happening for Contentful

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
