### ISSUE TITLE
Improve Gatsbyjs.org without browser JavaScript

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#13885]
## Description

In reviewing Gatsbyjs.org with JavaScript disabled, most of it works! There are two main improvements I'd like to propose (and if anyone finds other low-hanging fruit, feel free to add details here!).

- Improve layout with "This app works best with JavaScript enabled" notice and scrolling of the page
- The plugins page shows up completely blank

It's reasonable that some functionality would not work, particularly things that rely on client-side scripting like calling external APIs. However, the site chrome should still render on all pages with client-side scripting disabled.

### Steps to reproduce

Turn JavaScript off in your browser and navigate the site

### Expected result

All pages should render and have a decent layout / scrolling experience.

### Actual result

The site header looks buggy and the plugins page is blank.

![gatsbyjs. org header](https://user-images.githubusercontent.com/1045233/57232105-ef0a3f00-6fe9-11e9-9f3b-590d345d9624.png)
![gatsbyjs.org plugins page](https://user-images.githubusercontent.com/1045233/57232119-f4678980-6fe9-11e9-8ad0-3bcc0b5a9f35.png)

**Comment by wardpeet** [comment]
is it worth the effort when we're thinking of a complete redesign? We might just want to make sure we do this in our redesign?

**Comment by marcysutton** [comment]
For the site chrome issue, that does make sense to do in the scope of the redesign. The plugins page thing seems worth investigating anyway to know why it's happening.

**Comment by DSchau** [comment]
Just to provide some context on this:

> Improve layout with "This app works best with JavaScript enabled" notice and scrolling of the page

Definitely worth doing (not sure if it needs to be scoped as part of the redesign). We can style this quite easily with CSS (there's an id on the noscript element), so we can/should do so.

> The plugins page shows up completely blank

This seems like an issue. It definitely wouldn't work to begin with (e.g. plugins sidebar requires a client-side data call), but we should at least show the layout component in the absence of JavaScript!

**Comment by LekoArts** [comment]
The JS notice was removed in the meantime and the /plugins page shows a skeleton when having JS disabled. So I'll close this one.
