### ISSUE TITLE
[gatsby-plugin-google-analytics] Example's comment for `head: false` is contradicting with the option's value

### ISSUE THREAD

**Issue by saple** [gatsbyjs/gatsby#13888]
## Description

Documentation for gatsby-plugin-google-analytics has contradiction in the example. Comment above the `head: false` line says tracking script is put into head instead of body but the value `head: false` suggests the opposite.

### Steps to reproduce

See *How to use* section in [gatsby-plugin-google-analytics documentation](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-analytics)

### Expected result

Comment above `head: false` says `// Puts tracking script in the body instead of the head`

### Actual result

Comment above `head: false` says `// Puts tracking script in the head instead of the head`

**Comment by LekoArts** [comment]
Hi, thank you for opening the issue!

The comment on the README is correct as it refers to the `head` option itself. It is common practice to display all the options with the default options (e.g. in this case `head: false`) with their comments so that when people copy/paste the code they are not surprised by things that are turned on/off just for the sake of showing the option.

Hope this clears things up for you :) Thanks for using Gatsby, have a nice day!
(Closing this issue as solved/answered)

**Comment by muescha** [comment]
Since it is the second PR about it:

I think it's a design issue and should somehow fixed because everyone expect the opposite of the property

**Comment by muescha** [comment]
Please just check out again this lines:

https://github.com/gatsbyjs/gatsby/blob/064010415e2bf4736d2525f97b66b80e815e778c/packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js#L50-L52

Here I can see if it is true then setHeadCompontents is used

Here you see the ApiRunner:

https://github.com/gatsbyjs/gatsby/blob/077a9c8e8657575a800ddf74994f80b2fcc6f62c/packages/gatsby/cache-dir/develop-static-entry.js#L80-L88

**Comment by LekoArts** [comment]
Hi Michael,

those two PRs were created at roughly the same time, I don't think that it indicates something specific.

> The comment on the README is correct as it refers to the head option itself. It is common practice to display all the options with the default options (e.g. in this case head: false) with their comments so that when people copy/paste the code they are not surprised by things that are turned on/off just for the sake of showing the option.

This pretty much explains it and hence I don't see the need to change something here. That's why I'm closing this again.

**Comment by muescha** [comment]
Oh. I fall into the same trap. 

You are right: The comment should describes the parameter, not the value. 

I think about a better wording to avoid confusion (include `true` and `false` into the comment)

**Comment by muescha** [comment]
@LekoArts i will give it a try with: #13950
