### ISSUE TITLE
How to completely remove trailing slashes

### ISSUE THREAD

**Issue by pawelotto** [gatsbyjs/gatsby#13897]
I desperately need to NOT generate any trailing slashes for Gatsby pages.

I'm currently using `gatsby-plugin-remove-trailing-slashes` but the plugin seems to give me more problems than it solves:

- it doesn't work when JS is disabled (my site works great also with JS disabled and I don't want any trailing slashes for the SSRendered pages when JS is disabled - good for crawler bots!)
- the plugin adds ugly 301 redirects instead of sanitizing urls and I'm getting enormous amounts of warnings in Google Webmaster Tools about the redirects. Something I want to avoid at all cost.

Anyone could tell me how to force Gatsby to NOT generate any trailing slashes while generating pages?
Thanks

**Comment by rstacruz** [comment]
(Disclaimer: I'm still investigating this too!)

I've found one way to prevent this from happening is to use `createPage` with a `.html` extension. This prevents Gatsby from making a folder with an `index.html` for that page. https://www.gatsbyjs.org/docs/actions/#createPage

```js
// Creates /my-sweet-new-page/index.html
createPage({ path: '/my-sweet-new-page/' })

// Creates /my-sweet-new-page.html
createPage({ path: '/my-sweet-new-page.html' })
```

**Comment by pawelotto** [comment]
Nice workaround, however, trailing .html is something I want to avoid also. Any other ideas?

**Comment by himynameistimli** [comment]
There's a discussion about this issue going on here: https://github.com/gatsbyjs/gatsby/issues/9207

For my side, I just stopped trying to solving it within Gatsby, we handle it on Lambda@Edge instead. If that's something you can do, you can see my comment in the above issue https://github.com/gatsbyjs/gatsby/issues/9207#issuecomment-479359403
