### ISSUE TITLE
[gatsby-plugin-netlify]: Caching headers missing for many immutable assets.

### ISSUE THREAD

**Issue by cameron-martin** [gatsbyjs/gatsby#13902]
## Description

The root of the build directory contains many js files that have a hash of the file contents in their name and therefore can be cached indefinitely. However, the `_headers` file generated by `gatsby-plugin-netlify` does not include caching headers for these.

### Steps to reproduce

1) Clone any gatsby starter.
2) Add `gatsby-plugin-netlify`.
3) Run `gatsby build`.

### Expected result

The `_headers` file in the build output directory should contain rules to make all files that have a hash of the file contents in their name to cache indefinitely, e.g.

```
/0-12e710fd4a5212f32b8b.js:
  Cache-Control: public, max-age=31536000, immutable
```

### Actual result

No headers are specified in `_headers` for these files.

### Environment

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.14.1 - /tmp/yarn--1557231755699-0.6394244563261118/node
    Yarn: 1.15.2 - /tmp/yarn--1557231755699-0.6394244563261118/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.3
  npmPackages:
    gatsby: ^2.0.83 => 2.2.0 
    gatsby-cli: ^2.4.4 => 2.4.16 
    gatsby-plugin-eslint: ^2.0.1 => 2.0.4 
    gatsby-plugin-google-tagmanager: ^2.0.7 => 2.0.10 
    gatsby-plugin-manifest: ^2.0.10 => 2.0.24 
    gatsby-plugin-netlify: ^2.0.5 => 2.0.13 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.10 
    gatsby-plugin-root-import: ^2.0.4 => 2.0.5 
    gatsby-plugin-styled-components: ^3.0.3 => 3.0.7 
    gatsby-plugin-svgr: 2.0.1 => 2.0.1 
    gatsby-source-contentful: ^2.0.15 => 2.0.40 
    gatsby-transformer-remark: ^2.1.12 => 2.3.6 
```

**Comment by wardpeet** [comment]
This looks awesome! This is great for our netlify users, it will increase speed for many regular visitors.

I'm checking to make sure it all works 👌

**Comment by borisirota** [comment]
Hi, I thought of opening new issue but then I found this :)

It will be great to add caching headers for async chunks (dynamic import) as well.
