### ISSUE TITLE
How to disable split chunk in build

### ISSUE THREAD

**Issue by nsisodiya** [gatsbyjs/gatsby#13906]
How to disable code splitting. I tried but unable to find suitable settings.

**Comment by nsisodiya** [comment]
I tried this one.

gatsby-node.js

```js 
const webpack = require(`webpack`);

exports.onCreateWebpackConfig = ({ stage, actions }, options) => {
  console.log('==== Disabling Chunk ====');
  if ((process.env.NODE_ENV === 'production' && stage === 'build-javascript') || options.development) {
    actions.setWebpackConfig({
      plugins: [
        new webpack.optimize.LimitChunkCountPlugin({
          maxChunks: 1
        })
      ]
    });
  }
};```

**Comment by trevorlitsey** [comment]
hi @nsisodiya, would this work for your needs?

```
exports.onCreateWebpackConfig = () => {
  actions.setWebpackConfig({
    optimization: {
      splitChunks: false,
    },
  });
};
```

**Comment by nsisodiya** [comment]
Thanks

**Comment by nsisodiya** [comment]
@trevorlitsey - I tried, but it didn't worked.

**Comment by LekoArts** [comment]
As mentioned in your [other issue](https://github.com/gatsbyjs/gatsby/issues/13901) we don't recommend changing this behavior of Gatsby. We work hard on making Gatsby as fast as possible and this would decrease your speed. Hence I'm closing this, thanks for the issue!

**Comment by slorber** [comment]
@LekoArts what about actually "enhancing" the gatsby config? Is this not recommended when gatsby config does not totally suit us?

For example see this https://github.com/gatsbyjs/gatsby/issues/10965#issuecomment-453456324
