### ISSUE TITLE
sitemap options: page rules for priority and frequency ?

### ISSUE THREAD

**Issue by myriamgoude** [gatsbyjs/gatsby#13900]
## Summary

In order to help Google to crawl and index correctly websites, we need to adapt frequency and priority levels for some pages on the generated sitemap.xml. It would be nice to overwrite the standard option for specific urls.

### File contents

Quick proposal: 
`gatsby-config.js`: 

```
options: {
      output: `/some-other-sitemap.xml`,
      ...,
      pageRules: {
       '/': {
          frequency: daily,
          priority: 1 
       },
       'foo-1/': {
           frequency: monthly,
           priority: 0.5
       }
       
      }
}

```

**Comment by myriamgoude** [comment]
Keep it open

Le mar. 28 mai 2019 à 19:28, gatsbot[bot] <notifications@github.com> a
écrit :

**Comment by JoaquinScript** [comment]
This is a great idea, currently both frequency and priority are hardcoded but I guess the `serialize` function can be overridden and a object like the one on the issue can be used

**Comment by wardpeet** [comment]
I believe you're able to do this with the serialize option:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sitemap/README.md#options

You have full control of the output you're providing

I'm marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
