### ISSUE TITLE
Unable to get 100/100 score

### ISSUE THREAD

**Issue by nsisodiya** [gatsbyjs/gatsby#13901]
I want to get 100/100 score and few things it is showing.

* Combine multple JS reqests into one.
* 
![image](https://user-images.githubusercontent.com/333455/57295596-7d64ea80-70e8-11e9-82ca-f562144e6fa2.png)

**Comment by nsisodiya** [comment]
Also, a few files which are generated are very very small. It should be okey to inline them

![image](https://user-images.githubusercontent.com/333455/57297000-09c4dc80-70ec-11e9-8b32-e81ce7ef8a8f.png)

**Comment by me4502** [comment]
If you're using HTTP2, using multiple smaller scripts can actually be better for performance

**Comment by nsisodiya** [comment]
@me4502 Yes, we are using http2. But Yslow is still not giving 100/100. I am looking for 100/100 on these sites. 
Only last option that, I need to write a plugin which will combine all js into one js file.
![image](https://user-images.githubusercontent.com/333455/57297451-4218ea80-70ed-11e9-800d-0b0b1133b9ac.png)

**Comment by LekoArts** [comment]
As @me4502 said I wouldn't worry about Yslow in this case. We're smarter than Yslow and hence know that you can ignore this message. You shouldn't try to do something different if you definitely know better.

**Comment by nsisodiya** [comment]
@LekoArts @me4502 
I am 100% agree. However, I tried with MaxChunk Number is 1 and now I have 100/100 score.

![image](https://user-images.githubusercontent.com/333455/57305147-3550c280-70fe-11e9-99de-26fa4ceddf87.png)


**gatsby-node.js**
```js
const webpack = require(`webpack`);

exports.onCreateWebpackConfig = ({ stage, actions }, options) => {
  console.log('==== Disabling Chunk ====');
  if ((process.env.NODE_ENV === 'production' && stage === 'build-javascript') || options.development) {
    actions.setWebpackConfig({
      plugins: [
        new webpack.optimize.LimitChunkCountPlugin({
          maxChunks: 1
        })
      ]
    });
  }
};
```
I noticed that the load time also increased.

**Comment by KyleAMathews** [comment]
As @me4502 mentioned, this is advice from pre http/2 days. We recommend using lighthouse scores for performance advice as it is kept up to date and yslow isn't.
