### ISSUE TITLE
Is it possible to run scripts defined in a theme in an app? 

### ISSUE THREAD

**Issue by maecapozzi** [gatsbyjs/gatsby#13915]
## Summary

I tried making a typescript theme: https://github.com/maecapozzi/gatsby-theme-typescript

I was exploring whether I could run some of the scripts I've written in the theme in another Gatsby app. Is this possible and I'm just missing something, or is it not possible?

## Relevant information

I thought that it may be possible to write scripts in my theme, and have them be executable from an application's environment. 

So if I wrote a script called `typecheck` in `gatsby-theme-typescript`, and I included `gatsby-theme-typescript` in `project-a`, I though I'd be able to run `yarn run typescript` from `project-a`.

### Environment (if relevant)

  System:
    OS: macOS 10.14.4
    CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v10.9.0/bin/yarn
    npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.3
    Safari: 12.1
  npmGlobalPackages:
    gatsby-cli: 2.4.2

### File contents (if changed)

`gatsby-config.js`: 

```js
const path = require("path");

module.exports = {
  plugins: [
    {
      resolve: "gatsby-plugin-page-creator",
      options: {
        path: path.join(__dirname, "src", "pages")
      }
    },
    {
      resolve: "gatsby-plugin-compile-es6-packages",
      options: {
        modules: ["gatsby-theme-typescript"]
      }
    },
    {
      resolve: `gatsby-plugin-typescript`
    }
  ]
};

```

`package.json`: 

```json
{
  "name": "gatsby-theme-typescript",
  "version": "0.0.4",
  "main": "index.js",
  "author": "Mae Capozzi",
  "license": "MIT",
  "keywords": [
    "gatsby-theme"
  ],
  "scripts": {
    "develop": "gatsby develop",
    "typecheck": "tsc --noEmit",
    "typecheck:watch": "tsc --noEmit --watch"
  },
  "devDependencies": {
    "gatsby": "^2.3.31",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "peerDependencies": {
    "gatsby": "^2.3.31",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "typescript": "^3.4.5"
  },
  "dependencies": {
    "gatsby-plugin-compile-es6-packages": "^1.1.0",
    "gatsby-plugin-page-creator": "^2.0.12",
    "gatsby-plugin-typescript": "^2.0.13",
    "typescript": "^3.4.5"
  }
}

```
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by maecapozzi** [comment]
Not stale! I still don't think this is quite clear.

**Comment by ChristopherBiscardi** [comment]
I don't personally know of any way to call scripts defined in npm packages as if they were scripts defined in the root package.json. I think if you declared them as `bin`s in the theme's package.json you would be able to then run `yarn my-bin`, but that wouldn't show them in the root package.json and such.

**Comment by wardpeet** [comment]
As @ChristopherBiscardi described you'll need to do something along the lines of https://blog.npmjs.org/post/118810260230/building-a-simple-command-line-tool-with-npm. Create a custom cli and add it to `bin` in `package.json`.
