### ISSUE TITLE
gatsby-plugin-netlify-cms adding widgets

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#13928]
## Summary

The new version of https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify-cms depends on netlify-cms-app which does not include the Cloudinary widget. Are there any docs for how to add this with that version?

**Comment by zslabs** [comment]
```js
import CMS from 'netlify-cms-app';
import cloudinary from 'netlify-cms-media-library-cloudinary';

CMS.registerMediaLibrary(cloudinary);

CMS.init();
```

Using

```js
{
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
        modulePath: `${__dirname}/src/cms/index.js`,
        options: {
          manualInit: true,
        },
      },
    },
```

Appears to be the way I'd go doing this, but just want to make sure I won't miss out on anything the base plugin is providing in the init of the CMS.

**Comment by sidharthachatterjee** [comment]
@zslabs Looks good to me 

We only run `CMS.init()` anyway so you should be fine!
https://github.com/gatsbyjs/gatsby/blob/0e2db0430b093f8bb13553075572d58d142efea6/packages/gatsby-plugin-netlify-cms/src/cms.js#L7

**Comment by zslabs** [comment]
Ok awesome, thanks for confirming!
