### ISSUE TITLE
gatsby-remark-autolink-headers: add slug for markdown headings to GraphQL

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#13925]
Would be great if [`gatsby-remark-autolink-headers`](https://gatsbyjs.org/packages/gatsby-remark-autolink-headers) made the slugs it generates to markdown headings available through GraphQL, i.e. as an additional attribute to the `headings` array generated by [`gatsby-transformer-remark`](https://gatsbyjs.org/packages/gatsby-transformer-remark).

### Basic example

```graphql
{
  allMarkdownRemark {
    edges {
      node {
        headings {
          depth
          value
          slug  // new
        }
      }
    }
  }
}
```

### Motivation

Would make building custom tables of contents [as discussed here](https://github.com/gatsbyjs/gatsby/issues/6896) much easier.

**Comment by donaldboulton** [comment]
Wish someone could fix this or show us how to build a toc that is not in the markdown page but in a static query with a component, Its not possible.
And yes I have tried to use [sticky-active-smooth-responsive-toc](https://janosh.io/blog/[sticky-active-smooth-responsive-toc)
And I cannot get it to work in a non MDX site, and there are 0 post on how to do this from the Gatsby Community except or MDX usage. Do not want MDX and I you are not using it I have already seen any and all response's on issues non-MDX are somewhat disregarded now days.

**Comment by janosh** [comment]
@donaldboulton Actually, [the ToC I built](https://janosh.io/blog/sticky-active-smooth-responsive-toc) doesn't depend on MDX. If you like we can try to solve whatever issue you encountered following that blog post. It should work both with and without MDX.

**Comment by robertsoniv** [comment]
I think this should be reopened - or there should be a gatsby utility to generate the slug based on the header.value
