### ISSUE TITLE
Redux failing my build - works in development mode

### ISSUE THREAD

**Issue by Cobwebster** [gatsbyjs/gatsby#13934]
## Description

Here is my repo which shows my basic redux setup, should give a better idea of my setup.  https://github.com/Cobwebster/CraftMC

I added some redux functionanility to my website, it works in development mode but when I attempt to build it throws this error,

`  WebpackError: Invariant Violation: Could not find "store" in the context of "Connect(Layout)". Either wrap the ro  ot component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React c  ontext consumer to Connect(Layout) in connect options.`

I've seen this error around in other issues but all solutions didn't seem to work for me, whenever I attempt to give a page/component props via connect 

`export default connect(
  mapStateToProps,
  mapDispatchToProps
)(SeedSubmit);
`

it fails a build with the error above, any pointers/help is appreciated, i've been debugging this for a while and am lost.

> Binaries:
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.4.2 => 2.4.2
    gatsby-image: ^2.0.41 => 2.0.41
    gatsby-pagination: ^1.2.0 => 1.2.0
    gatsby-plugin-google-analytics: ^2.0.19 => 2.0.19
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.0 => 2.1.0
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-robots-txt: ^1.4.0 => 1.4.0
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.0.36 => 2.0.36
    gatsby-plugin-sitemap: ^2.1.0 => 2.1.0
    gatsby-source-filesystem: ^2.0.33 => 2.0.33
    gatsby-source-firestore: ^1.0.3 => 1.0.3
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19

I copy this example - https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redux

When I use 

import wrapWithProvider from "./wrap-with-provider"
export const wrapRootElement = wrapWithProvider

in both browser.js or ssr.js - this error occurs, i'm not sure if thats progress or if this error is just firing before the next,

  TypeError: Cannot read property 'split' of null

(Code in ./wrap-with-provider)
`export default ({ element }) => {
  const store = createStore()
  return <Provider store={store}>{element}</Provider>
}`

any information is appreciated.  From what I gather when I build (SSR) redux doesn't correctly do its thing and I need some special setup for it to work in SSR, however I can't seem to find that setup and when I do something that other error appears. I don't know if thats progress or a setback.

**Comment by kazuma1989** [comment]
Came from https://github.com/gatsbyjs/gatsby/issues/6362#issuecomment-490665270

Sorry but my examples are in private repos.
My `gatsby-ssr.js` and `gatsby-browser.js` are essentially same as ones in [the official example](https://github.com/gatsbyjs/gatsby/tree/ec8deb2d757524316a06ae3cefe26d7626549ad6/examples/using-redux), so your repo for reproduction seem to work fine.
