### ISSUE TITLE
[Help] I somehow managed to butcher my site's performance

### ISSUE THREAD

**Issue by daydream05** [gatsbyjs/gatsby#13949]
## Summary
When accessed through normal means, the site is blazing fast. However, when tested using lighthouse, the performance score is terrible.
## Relevant information
[Webpage Test Results](https://www.webpagetest.org/result/190509_P0_0cf4def8e160e63ef1078984a613b641/)

[Lighthouse Results](https://www.webpagetest.org/lighthouse.php?test=190509_P0_0cf4def8e160e63ef1078984a613b641&run=3)

I believe the image sizes are fixable but I'm not sure how to optimize for the rest. Especially this part where I need to minimize main-thread work:

<img width="940" alt="Screen Shot 2019-05-09 at 12 40 12 PM" src="https://user-images.githubusercontent.com/11723413/57470778-a35ccd00-7257-11e9-8be2-bbe53c9e4636.png">

I'm not sure where to start and what to look for. I tried viewing the trace, but I have no clue what's going on and what's causing this. If someone can help or even point me to the right direction, that would be helpful!
 

### Environment (if relevant)
```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.0.0 - /usr/local/bin/node
    Yarn: 1.6.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.3
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.23 => 2.3.23 
    gatsby-image: ^2.0.35 => 2.0.35 
    gatsby-plugin-canonical-urls: ^2.0.12 => 2.0.12 
    gatsby-plugin-feed: 2.1.0 => 2.1.0 
    gatsby-plugin-google-analytics: 2.0.18 => 2.0.18 
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5 
    gatsby-plugin-manifest: ^2.0.19 => 2.0.19 
    gatsby-plugin-netlify: 2.0.13 => 2.0.13 
    gatsby-plugin-nprogress: 2.0.10 => 2.0.10 
    gatsby-plugin-offline: ^2.0.24 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.8 => 3.0.8 
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0 
    gatsby-plugin-sitemap: 2.0.10 => 2.0.10 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-typography: 2.2.10 => 2.2.10 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-prismjs: 3.2.6 => 3.2.6 
    gatsby-source-contentful: ^2.0.44 => 2.0.44 
    gatsby-source-filesystem: ^2.0.28 => 2.0.28 
    gatsby-transformer-remark: 2.3.8 => 2.3.8 
    gatsby-transformer-sharp: 2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.5.12
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by Kevin-Hamilton** [comment]
A couple things I noticed when taking a quick look at this is
1) Your not serving a Server-side Rendered static HTML version of your pages.  So react needs to hydrate before your page can render
2) I noticed a couple of really large SVGs on your homepage.  The SVG above "We Collaborate" is 90KB where an equivalent PNG would be under 20KB.  Plus the SVG is directly embedded, so that is 180+ nodes that React is going to render.

**Comment by daydream05** [comment]
Thanks! Regarding your answers:
1. Wouldn't Gatsby automatically create these static pages for me?  If i'm not mistaken, isn't rehydration an expected Gatsby behavior?

Or do you mean something else?

2. You're definitely right! I ended up just passing them as images since they have so many nodes.

**Comment by Kevin-Hamilton** [comment]
Regarding number 1 - it looks like I was mistaken.  I didn't realize that view-source behaves differently with Service Worker, but apparently that is the case.  It is mentioned at the bottom of https://www.gatsbyjs.org/packages/gatsby-plugin-offline/ that you should test with curl, which I just did, and your site is returning full HTML in that case.

**Comment by daydream05** [comment]
Ahh gotcha. Didn’t know that’s how service workers work! I’m still investigating what causes this really bad performance. It might be my animations(pop motion) along with react waypoint since i’m noticing a lot of layout reflow.

**Comment by daydream05** [comment]
I'm getting closer to a respectable speed.

Things I've done so far. I might be wrong on some of these assumptions.

- Reduced all my image sizes
- Stopped using base64 on the images
- Removed the video

Biggest difference maker:
- Stopped bundling my js and css on Netlify. My assumption is that bundling lowers the number of times your sites make a request, but it increases the size & complexity of your js. This takes the browser a lot more time to process and evaluate. So removing bundling helped **reduce javaScript execution time**.

**Comment by DSchau** [comment]
@daydream05 hey Vince! 👋 

Not quite sure what's going on here, exactly, but I think your initial suspicion was correct. My _guess_ is that JS animations were blocking the rendering of static HTML, so there was a delay before the JS thread picked up and _eventually_ produced the DOM structure you expect.

Few things I'd recommend:

1. Think hard about whether the entry animation is necessary for the end-user experience (it seems to delay some important metrics, e.g. first paint)
1. Some resources (e.g. Typekit, images (served from Contentful?), etc.) are quite large and numerous, and again, may not be necessary for the end-user experience
    - In particular, it seems like _all_ the images for the hero section are loading even if they're not necessary _yet_? (e.g. they could be preloaded in the background until they're necessary)

However - looks like you've made some impactful changes, as I'm seeing pretty good scores on my end.

![Screen Shot 2019-05-13 at 11 10 49 AM](https://user-images.githubusercontent.com/3924690/57637153-4cfdd000-7570-11e9-8607-755076d1f937.png)

**Comment by daydream05** [comment]
@DSchau Hey Dustin! It was great meeting you at Gatsby Days!

I followed your recommendations and I've seen massive improvements! Thanks again for saving the day!

Here's what I did:

- I removed all of my scrolling animations which def lowered the js execution time.
- I use [react-slick](https://react-slick.neostack.com/) for the Hero, and I added the `lazyLoad` prop to do the trick. I think it did.
- Also, stopped using [react-media](https://github.com/ReactTraining/react-media) and just used plain 'ol `display: none` for the Hero media queries. I noticed there's a brief moment where the mobile version shows up on the desktop.
- For images, it's a tough battle. On one hand, the client wants to show their images since this is one of their competitive advantage. I can't disagree because some of our clients inquire from seeing the work on Instagram. And at the same time, they use very large monitors so an image less than 2k resolutions look terrible on them. I guess I need to find a better way to relay this tradeoff between speed and quality. I think I was banking on the magic of gatsby-image to do all of the heavy-lifting when it comes to perceived site speed.

- For typekit, I removed the oblique version of the fonts. But the biggest difference is the use of [WebFont Loader](https://www.gatsbyjs.org/packages/gatsby-plugin-web-font-loader/) instead of using the link that Typekit gave. This pushed my score from 85 to 98

- The the weird thing about lighthouse is it's different results every time. When you posted that screenshot, my last score was around 65. Also, it's a lot worse if I use webpagetest.org

My question right now is this [js blob](https://prtwd.com/0-81f450fe3d70e0022541.js) inside my head tag. It's has the highest evaluation time according to my audit. It looks like my css-in-js but I'm not sure what to make of it.

**Comment by DSchau** [comment]
@daydream05 it seems good for me--but I noticed that some resources (small ones, even) take quite a while to load.

How are you hosting this? Do you have a CDN edge layer in front of the host?

For what it's worth, my Webpagetest results were pretty solid -> https://www.webpagetest.org/result/190514_DZ_3124029672236e3bb7de795b85b1d002/

**Comment by daydream05** [comment]
@DSchau I use Netlify and its Asset Optimization feature. I'm minifying the JS and the CSS. Everything else is through Contentful.

**Comment by daydream05** [comment]
Closing this. Thank you for all the help @DSchau

**Comment by DSchau** [comment]
It was all you @daydream05! Glad to help!

**Comment by pmarxbraun** [comment]
Hey @DSchau @daydream05 

My Gatsby [site](https://fehrgroup.com) has a performance score of 35 on Lighthouse... which is really not what I expected. 
Here's the [report](https://googlechrome.github.io/lighthouse/viewer/?gist=be1f9ada331f56b3bb3c4e0411ccbdd8)

I reckon Tawk.to script is not doing any good but it seems that other improvements should me made. But I can't quite figure out what to do ... 

Take first warning for instance : *Ensure text remains visible during webfont load*
I load my Google Font font via @import and declare them using *"Lato", sans-serif* which is best practice. 

Any help here would be appreciated :-)
Thanks

**Comment by daydream05** [comment]
@pmarxbraun I'm still struggling with this myself but there are some quick wins you can do. 
I see you've [improved](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ffehrgroup.com%2F&tab=mobile) it already.

Here's some things you can do: 

- SVG tracing takes a toll on CPU which increases js execution time. Maybe consider using just regular webp with no base64? (It might )
- Make the [cache](https://www.gatsbyjs.org/docs/caching/#static-files) for your static assets forever.
