### ISSUE TITLE
[gatsby-plugin-netlify]: add statusCode to matchPath rewrites

### ISSUE THREAD

**Issue by CanRau** [gatsbyjs/gatsby#13946]
## Summary

I think, if I'm not doing anything wrong, `gatsby-plugin-netlify` is not yet setting the proper `statusCode` on matchPath redirects like for custom 404 pages. 🤔 

### Basic example

I think it should happen [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify/src/gatsby-node.js#L41) so I assume it's not yet implemented..

I'm setting `page.matchPath = `/${lang}/*` on error pages as mentioned in the [docs](https://www.gatsbyjs.org/docs/creating-prefixed-404-pages-for-different-languages/) for handling localized 404 pages.
I just noticed, that those pages are still being served with a status code `200` instead of `404`

Maybe 
```
createPage({
    ...page,
    path: slug,
    matchPath: `/${lang}/*`,
    statusCode: 404,
  })
}
```
and then `gatsby-plugin-netlify` would merge it in the redirect [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify/src/gatsby-node.js#L41)

what do you think? Or am I missing anything?

`transformHeaders` might offer a workaround, yet I think it shouldn't be necessary..

I could prepare a PR, once I know how the right implementation might look like 😉

**Comment by superfunkminister** [comment]
Also having this problem!

**Comment by LekoArts** [comment]
Please post a [minimal reproduction][reproduction]. The Netlify plugin should handle this case already: https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/#configuring-and-handling-client-only-routes-on-a-server

[reproduction]: https://gatsby.dev/reproduction

**Comment by CanRau** [comment]
Didn't notice you comment @LekoArts 🙏 
I'll have to check 👍

**Comment by wardpeet** [comment]
Seems like a bug, i'll post some more info later :)

**Comment by freiksenet** [comment]
Ping @wardpeet.

**Comment by episode17** [comment]
Yeah, those rewrites will [always end up 200](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify/src/create-redirects.js#L54).

**Comment by wardpeet** [comment]
Closing as we don't longer own gatsby-plugin-netlify
