### ISSUE TITLE
[docs] [workflows] Installing and using Contentful

### ISSUE THREAD

**Issue by jasonellington** [gatsbyjs/gatsby#13945]
Part of the **Top 25 Learning Workflows initiative**. See #13708 for the meta issue that this issue falls under.

# User story

As a new Gatsby user, I want to create a blog/site that pulls content and images from Contentful and allows me to query it.

# Evaluation

| Search | Discover | Complete | Linked | Tone | Style | Overall |
| --- | --- | --- | --- | --- | --- | --- |
| 😄 | 😐 | 😐 | 😞 | 😐 | 😄  | 😐 |

# Steps taken to implement

1. Searchability
   1. Searched `gatsby contentful` on Google. clicked [second link](https://www.gatsbyjs.org/packages/gatsby-source-contentful/).
   1. First link was to Contentful site
1. Discoverability
   1. Searchbar:
      1. Searched `gatsby contentful` in search bar; only blog articles show up.
      1. Searched`contentful`; [Sourcing from Contentful](https://www.gatsbyjs.org/docs/sourcing-from-contentful/) pops up.
      **[rec]** searching for `gatsby contentful` should bring up [Sourcing from Contentful](https://www.gatsbyjs.org/docs/sourcing-from-contentful/) as well
      1. Some blogs do not mention [Sourcing from Contentful](https://www.gatsbyjs.org/docs/sourcing-from-contentful/)
   1. Clickpath on .org:
      1. Clicked _docs_
      1. Clicked _Guides > Sourcing Content and Data > Sourcing from (Headless) CMSs > Sourcing from Contentful_
      1. Discoverable
1. Completeness
   1. Followed steps in [Sourcing from Contentful](https://www.gatsbyjs.org/docs/sourcing-from-contentful/)
   1. Clicked on Link [Quick Start guide](https://www.gatsbyjs.org/docs/) which actually links to `Gatsby.js Documentation`. 
  **[rec]** actually link to [Quick Start](https://www.gatsbyjs.org/docs/quick-start), the link above goes to docs.
   1. Followed steps in [Quick Start](https://www.gatsbyjs.org/docs/quick-start).
   1. Jumped back to [Sourcing from Contentful](https://www.gatsbyjs.org/docs/sourcing-from-contentful/)
      1. Followed `prerequisites`
      **[rec]** include prerequisite of contentful site and give an option for [Getting started with Contentful](https://itnext.io/jamstack-basics-how-to-create-a-gatsby-starter-with-contentful-and-deploy-to-netlify-846354cc74bc), steps in this blog are pretty clear and helpful.
      1. The `Pulling data in and pushing data out` section does not really fit here at all.
      **[rec]** remove `Pulling data in and pushing data out`
      1. Followed `install` and `how to use`
   1. I was able to get the plugin running with ```sh gatsby develop```, but no more information provided after that.
      **[rec]** Add another section for how to actually use the data, or at least a general query in GraphQL
1. Linkedness
   1. The links could be much better.
   **[rec]** There should be links to help get a better understanding in general. i.e. GraphQL at build time, GraphQL schema, etc.
   **[rec]** Link the user to getting started content with Contentful
   **[rec]** Provide a `Learn More` with more indepth articles on using Contentful with Gatsby
1. Tone
   1. Overall easy to read, but I would suggest rearranging parts of the content and buffing up the wording in areas.
1. Style
   1. Nothing obviously wrong

# Recommendations

- [ ] searching for `gatsby contentful` should bring up [Sourcing from Contentful](https://www.gatsbyjs.org/docs/sourcing-from-contentful/) as well
- [ ] include prerequisite of contentful site and give an option for [Getting started with Contentful](https://itnext.io/jamstack-basics-how-to-create-a-gatsby-starter-with-contentful-and-deploy-to-netlify-846354cc74bc), steps in this blog are pretty clear and helpful.
- [ ] remove `Pulling data in and pushing data out`
- [ ] Add another section for how to actually use the data, or at least a general query in GraphQL
- [ ] There should be links to help get a better understanding in general. i.e. GraphQL at build time, GraphQL schema, etc.
- [ ] Link the user to getting started content with Contentful
- [ ] Provide a `Learn More` with more indepth articles on using Contentful with Gatsby

**Comment by alexluong** [comment]
Hey @freiksenet, I'd love to help with this. I have some experiences building sites with Gatsby and Contentful.

Within those recommendations by @jasonellington, how should I go about tackling them?

**Comment by jonniebigodes** [comment]
@alexluong if you want see my reproduction for this [issue](https://github.com/gatsbyjs/gatsby/issues/13288#issuecomment-483017863) and take it from there.

**Comment by alexluong** [comment]
@jonniebigodes That's a great starting point. I'd take that into consideration for the documentation page.

**Comment by jasonellington** [comment]
@prestonso is this still a priority?
