### ISSUE TITLE
low routing performance

### ISSUE THREAD

**Issue by onopko81** [gatsbyjs/gatsby#13944]
Hi, I'm realizing my portfolio with gatsby, I use threejs and gsap for the part of 3d and animations. The performances of animations and 3D renderings are reduced at each page change using "Link". I analyzed fps of my background component (made in webgl) goes from 60fps and is reduced to 10 at each page change. What can it depend on?

**Comment by sidharthachatterjee** [comment]
The `Link` component is a wrapper on top of https://reach.tech/router/api/Link

It does a bunch of things including prefetching assets on hover etc but not sure if the reduced fps is relevant here. Perhaps try using Link from reach directly to see it if has to do with page navigation in general or anything specific to Gatsby?

**Comment by onopko81** [comment]
I try this solution. I am also trying to use removeListeners in the project.

**Comment by onopko81** [comment]
The problem concerns the navigation of the pages, with each click the performances are reduced more and more drastically.

**Comment by KyleAMathews** [comment]
Perhaps you're not cleaning up old animations? Gatsby doesn't do anything special when a link is changes. Just renders the new page.

**Comment by onopko81** [comment]
I solved, I removed the hover and mouse events, I also used cancelAnimationFrame and removeChild for the 3d render. Performance now is ok.

**Comment by KyleAMathews** [comment]
Great! Closing now.
