### ISSUE TITLE
createPages async issue

### ISSUE THREAD

**Issue by jeremylynch** [gatsbyjs/gatsby#13967]
I am getting the following error: 
```
warning Action createPage was called outside of its expected asynchronous lifecycle createPages in gatsby-source-algolia.
Ensure that you return a Promise from createPages and are awaiting any asynchronous method invocations (like graphql or http requests).
For more info and debugging tips: see https://gatsby.dev/sync-actions
```
In gatsby-source-algolia [see full code here](https://github.com/jeremylynch/gatsby-source-algolia/blob/master/gatsby-node.js)

Also see code here: 

```js
return new Promise((resolve, reject) => {
  const templatePath = path.resolve(template);
  pages.map((page) => {
    let searchParams = Object.assign({}, search_params[0], {params: {
      hitsPerPage: hitsPerPage,
      facets: facets,
      ...page.search_params
    }})
    resolve(
      client.search([searchParams]).then(response => {
        createPageWithResults(page, response, state, templatePath)
      })
    )
  })
})
```

What am I doing wrong?

**Comment by coreyward** [comment]
You probably want to do `client.search(...).then(response => { ... }).then(resolve)` instead of trying to pass the result of the `client.search().then()` in as an argument to `resolve`.

**Comment by jeremylynch** [comment]
I tried that approach and I am still getting the error

**Comment by jeremylynch** [comment]
I also get the following error at build: 
```
TypeError: Cannot read property 'includes' of null
```

**Comment by DSchau** [comment]
Array.prototype.map is a sync function that you are using as if it was async. You'll want to re-write to use Promise.all.

[Here's a re-write on Github Gist](https://gist.github.com/DSchau/8809383e2be900d1d18c516a03de7b08)

Let me know if we can help further, but for now, closing as answered. Thanks!
