### ISSUE TITLE
Style in production not same as development using Rebass

### ISSUE THREAD

**Issue by wiput1999** [gatsbyjs/gatsby#13966]
## Description
I'm using Rebass for UI with styled-component I'm facing style in development and production not the same as screen short I attach below in the left is a development which has correct style but on the right gatsby seem put class that has margin-top on the wrong element that's make navbar has margin-top

Categories Page
![CleanShot 2019-05-10 at 22 05 49](https://user-images.githubusercontent.com/8299278/57537251-18232a80-7370-11e9-94ac-b7e9b76b1c05.png)

Home Page
![CleanShot 2019-05-10 at 22 05 33](https://user-images.githubusercontent.com/8299278/57537252-18232a80-7370-11e9-812c-54af925a302e.png)

### Steps to reproduce

I'm using Netlify to deploy for this site just normal build and this happens nothing special in build command.

### Expected result

Navbar not have margin in categories page and on home page "Featured Articles" Should have margin-top

### Actual result

As screenshots above

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 3.7.2 - /Users/wiput/.pyenv/versions/3.7.2/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 64.0.2
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.16 => 2.4.2 
    gatsby-image: ^2.0.37 => 2.0.41 
    gatsby-plugin-feed: ^2.1.0 => 2.2.0 
    gatsby-plugin-google-analytics: ^2.0.18 => 2.0.19 
    gatsby-plugin-google-fonts: ^0.0.4 => 0.0.4 
    gatsby-plugin-manifest: ^2.0.28 => 2.1.1 
    gatsby-plugin-netlify: ^2.0.16 => 2.0.16 
    gatsby-plugin-netlify-cache: ^1.1.0 => 1.1.0 
    gatsby-plugin-offline: ^2.0.25 => 2.1.0 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.36 => 2.0.36 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-tslint: ^0.0.2 => 0.0.2 
    gatsby-plugin-typescript: ^2.0.12 => 2.0.13 
    gatsby-plugin-typography: ^2.2.12 => 2.2.13 
    gatsby-remark-copy-linked-files: ^2.0.11 => 2.0.12 
    gatsby-remark-images: ^3.0.11 => 3.0.11 
    gatsby-remark-prismjs: ^3.2.8 => 3.2.9 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.29 => 2.0.33 
    gatsby-transformer-remark: ^2.3.8 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.19

**Comment by wiput1999** [comment]
Solved it's seem like issue from Rebass.js

**Comment by iammatthias** [comment]
@wiput1999 what was the solution? I'm having a similar issue.

**Comment by wiput1999** [comment]
@iammatthias Which UI Library are you using?

**Comment by iammatthias** [comment]
I'm using Rebass.js. Experience a similar render issue. 

### Expected 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5431737/57544144-563a3300-730b-11e9-856d-01a84e5b7011.png">


### Result
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5431737/57544136-4f132500-730b-11e9-92f4-9ff923eb5e60.png">

**Comment by wiput1999** [comment]
@iammatthias Same here... We will wait for someone know about this to answer 😄

**Comment by rayriffy** [comment]
I just created an issue on Rebass hope we will get an answer.
https://github.com/rebassjs/rebass/issues/587

**Comment by coreyward** [comment]
This can occur when global styles are used and/or when styles are expected to load in a specific order. Since `develop` mode uses hot reloading and does not do server-side-rendering, insertion order is sometimes different than in production.

**Comment by iammatthias** [comment]
@coreyward Interesting. I recently split my CSS reset out into it's own global style file, in addition to my main globals.js. I'll take a closer look at my CSS tonight.

**Comment by wiput1999** [comment]
@coreyward Any method to solve this problem?

**Comment by coreyward** [comment]
@wiput1999 I've never used Rebass, alas. When I'm using Emotion I've found that the default webpack import (e.g. `import "some.css"`) will cause it to be appended to the `<head>` after the Emotion `<style>` tags when navigating, so I instead use the `Global` component provided by Emotion: 

```js
import { Global } from "@emotion/core"
import baseStyles from "whatever"

export default () => 
  <>
    <Global styles={baseStyles} />
    <p>Hello, world</p>
  </>
```

**Comment by iammatthias** [comment]
Figured out what the issue was for me: 

This snippet: 
```js
import Layout from './src/components/general/Layout'

export const wrapPageElement = ({ element, props }) => {
  return <Layout {...props}>{element}</Layout>
}
```

Got removed from [gatsby-browser](https://github.com/iammatthias/.com/blob/master/gatsby-browser.js) and [gatsby-ssr](https://github.com/iammatthias/.com/blob/master/gatsby-ssr.js). Added the above snippet, and all is well.

**Comment by rayriffy** [comment]
For mine it make UI more glitchy. So, I gave up wrapping element inside `gatsby-browser` and `gatsby-ssr` then everything rendered as I expected!

So, it's not Rebass fault then.

**Comment by rayriffy** [comment]
Here's all the preview I tried

-   `gatsby-ssr` alone [Link](https://5cd6930a976d3300074c6d7f--thaiwithcodes-staging.netlify.com/)
-   `gatsby-broswer` alone [Link](https://5cd694566996f10007acfa7f--thaiwithcodes-staging.netlify.com/)
-   `gatsby-ssr` and `gatsby-browser` [Link](https://5cd5eb1dc1a0910008fc4f28--thaiwithcodes-staging.netlify.com/)
-   Nothing just directly add Layouts into each page [Link](https://5cd694ce0355e7000b4f3ecd--thaiwithcodes-staging.netlify.com/)

**Comment by iammatthias** [comment]
When adding the Layout direct to each page, it's possible to end up duplicating your content: https://github.com/gatsbyjs/gatsby/issues/7466

**Comment by wiput1999** [comment]
It seems stable right now, Thanks you, everyone, for help.
