### ISSUE TITLE
External link with dynamically constructed string results in "/undefined" in URL

### ISSUE THREAD

**Issue by zvinless** [gatsbyjs/gatsby#13961]
## Description

When dynamically constructing an external link starting with my site's origin, `/undefined` is inserted into the link, rendering it invalid.

Here is a test deployment: https://eloquent-bassi-2f286c.netlify.com/
and corresponding test repo: https://github.com/zvinless/link-test

in src/pages/index.js the line:
```jsx
<a href={`${origin}/somewhere`}>Go Somewhere (Undefined)</a>
```
where `origin` is `location.origin` passed into the React component, creates the following link:
```
https://eloquent-bassi-2f286c.netlify.com/undefined/somewhere
```
(note the `/undefined` part). Hardcoding the link works correctly, though. I have *not* been able to reproduce this using the dev server.

### Steps to reproduce

1. Go to the test deployment: https://eloquent-bassi-2f286c.netlify.com/
2. Mouse over the first link, Go Somewhere
3. Observe that it links to https://eloquent-bassi-2f286c.netlify.com/somewhere
4. Mouse over the second link, Go Somewhere (Undefined)
5. Observe that it links to https://eloquent-bassi-2f286c.netlify.com/undefined/somewhere which is an invalid link
6. Reference the source code to see that the links should be identical: https://github.com/zvinless/link-test/blob/master/src/pages/index.js
7. Observe the printout of the `origin` variable to be extra sure that the links should be identical

### Expected result

The link should be valid and not contain the extra `/undefined`segment

### Actual result

It had the `/undefined` segment :(

### Environment
```
  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/opt/node@10/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 65.0.1
    Safari: 12.1
  npmPackages:
    gatsby: ^2.4.2 => 2.4.2 
    gatsby-image: ^2.0.41 => 2.0.41 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.0 => 2.1.0 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.36 => 2.0.36 
    gatsby-source-filesystem: ^2.0.33 => 2.0.33 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 
```

**Comment by coreyward** [comment]
I don't believe `location.origin` is available server-side; that information is typically parsed from the HTTP request or browser location API, but neither exist when rendering in advance server-side.

**Comment by zvinless** [comment]
That makes sense--I'm not familiar with Gatsby's SSR internals; does it check out that the value prints properly via `console.log()` but doesn't work correctly when passed into the `<a>` tag? The reason I ask is that the URL is actually correct aside from the _additional_ `/undefined` part.

Also, I have this same issue on a larger site, and if I navigate to a different page on my site using Gatsby's link component, that corrects the target URL.

**Comment by coreyward** [comment]
> Does [Gatsby] check out that the value prints properly via console.log() but doesn't work correctly when passed into the <a> tag? 

I don't follow what you mean.

> …if I first navigate to a different page on my site using Gatsby's link component, that corrects the target URL.

This isn't all that surprising since subsequent navigations don't actually load the pre-rendered HTML from the server, they load the components and data and render via React, so that code is executed client side.

**Comment by zvinless** [comment]
I was just noticing that logging the value prints the correct URL, but as that's executing client-side it makes sense.

My overall question is, despite `location.origin` being unavailable server-side, why does it still produce the correct value for the URL, just with the addition of `/undefined`? And is there a workaround for that?

**Comment by zvinless** [comment]
Oh wait, it's just appending to an otherwise relative URL. Never mind and thanks for the help!
