### ISSUE TITLE
Failed to render about page in tutorial step 1: building with components

### ISSUE THREAD

**Issue by chfw** [gatsbyjs/gatsby#13978]
## Summary

Failed to render src/pages/about.js

<img width="1044" alt="Screenshot 2019-05-12 at 00 17 13" src="https://user-images.githubusercontent.com/4280312/57575882-55101f80-744b-11e9-83bd-65c5683b1112.png">

<img width="870" alt="Screenshot 2019-05-12 at 00 17 59" src="https://user-images.githubusercontent.com/4280312/57575894-84269100-744b-11e9-9271-f82e1263fd1f.png">

## Relevant information

I was following the tutorial till: https://www.gatsbyjs.org/tutorial/part-one/#-using-page-components

### Environment (if relevant)

 System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Safari: 12.1
  npmPackages:
    gatsby: ^2.4.3 => 2.4.3 
  npmGlobalPackages:
    gatsby-cli: 2.5.13

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@chfw seeing the screenshot you posted one thing comes to mind, that the file is not saved, save the file and see if it helps? Also to make sure refresh the page

**Comment by chfw** [comment]
@jonniebigodes , it does help indeed! VScode does not do auto-save as I uses WebStorm normally, and WS does auto-save.

You have sharp eyes!! Thanks a lot!

I would be able to proceed with the rest of the tutorial.

**Comment by chfw** [comment]
Just want to share the learning so that next person, who followed the same path, would know what else to enhance.

by default, vscode turns of auto-save: https://code.visualstudio.com/docs/editor/codebasics but can have it turned on like the following:

<img width="857" alt="Screenshot 2019-05-12 at 10 10 50" src="https://user-images.githubusercontent.com/4280312/57580203-9d0c6200-749e-11e9-9840-c59eb4e5d994.png">

**Comment by jonniebigodes** [comment]
@chfw just glad i was able to help and good one one the tip. 👍! Thanks for using Gatsby

**Comment by chfw** [comment]
I have gone through the tutorial today!

What surprised me that it is awesome to use graphiql and what surpised me more is: the end site is a static site, without graphiql, which means a lot to me: no extra cost except a good CDN site of choice!

Next topics I would be explore if you don'd mind type a few words:

1. CMS editor, which allow dummy user to record what they have so that I would be able harvest their data and feed into the static site. 
2. I18N.  Provide multi-language support, like [aurelia-i18n](https://aurelia.io/docs/plugins/i18n/)

**Comment by jonniebigodes** [comment]
@chfw i don't mind at all trying to answer to your follow up questions.

Regarding the first one, what you intented on achieving i'm not familiar with a cms that would allow to do what you intented to do. I do know that there are some like [sanity](https://www.sanity.io/) that allow self host and you might get some metrics with that, probably for instance [drupal](https://www.drupal.org/) might let you achieve the same result. I'll leave it to more knowledgeable people to expand on this.

Regarding the second one i'll leave [this](https://www.gatsbyjs.org/docs/localization-i18n/) piece of documentation for you to go over. 

Sorry that i wasn't much help in your follow up questions.
