### ISSUE TITLE
Importing CSS with print media query doesn't work in development mode

### ISSUE THREAD

**Issue by drakang4** [gatsbyjs/gatsby#13984]
## Description

Importing CSS with print media query doesn't work in development mode. Styles described in CSS ignore the media query and apply by default, not only print mode.
However, this works correctly as expected in production mode.

### Steps to reproduce

I tried
```
@media query {
  @import 'styles.css';
}
```

and

```
@import 'styles.css' print;
```

### Expected result

styles.css is applied in print mode only.

### Actual result

Both applies styles even in screen mode.

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Safari: 12.1
  npmPackages:
    gatsby: 2.4.3 => 2.4.3 
    gatsby-image: 2.0.41 => 2.0.41 
    gatsby-plugin-google-analytics: 2.0.19 => 2.0.19 
    gatsby-plugin-manifest: 2.1.1 => 2.1.1 
    gatsby-plugin-netlify-cms: 4.0.1 => 4.0.1 
    gatsby-plugin-offline: 2.1.0 => 2.1.0 
    gatsby-plugin-react-helmet: 3.0.12 => 3.0.12 
    gatsby-plugin-sharp: 2.0.37 => 2.0.37 
    gatsby-plugin-sitemap: 2.1.0 => 2.1.0 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-typescript: 2.0.13 => 2.0.13 
    gatsby-remark-autolink-headers: 2.0.16 => 2.0.16 
    gatsby-remark-copy-linked-files: 2.0.12 => 2.0.12 
    gatsby-remark-images: 3.0.11 => 3.0.11 
    gatsby-remark-prismjs: 3.2.9 => 3.2.9 
    gatsby-remark-relative-images: 0.2.2 => 0.2.2 
    gatsby-remark-responsive-iframe: 2.1.1 => 2.1.1 
    gatsby-source-filesystem: 2.0.33 => 2.0.33 
    gatsby-transformer-remark: 2.3.12 => 2.3.12 
    gatsby-transformer-sharp: 2.1.19 => 2.1.19 
  npmGlobalPackages:
    gatsby-cli: 2.4.8

**Comment by chris2fr** [comment]
Let's reopen. Gatsby seems to have print.css problems.
