### ISSUE TITLE
Non-deterministic build errors with no apparent cause

### ISSUE THREAD

**Issue by chrisjpatty** [gatsbyjs/gatsby#13986]
## Description

I'm currently in the process of converting a Wordpress site to Gatsby + Netlify CMS. I started with the Netlify starter project, converted the HTML posts to Markdown, and started copying them into my new Gatsby project. Running `yarn develop` to start the project fails non-deterministically. It seems that sometimes the command will succeed, and sometimes it will fail, with no changes to the project or environment. 

### Steps to reproduce

The Github repo I'm working out of [can be found here](https://github.com/chrisjpatty/igobyari-gatsby).
All I do is run `yarn develop`.

### Expected result

It should startup the project, and at the `/blog` url, it should render a lists of posts. 

### Actual result

The command fails with the following error(s):

```bash
error GraphQL Error Encountered 6 error(s):
- Unknown field 'title' on type 'MarkdownRemarkFrontmatter'. Source: document `BlogRollQuery` file: `GraphQL request`
  
  GraphQL request (15:17)
  14:               frontmatter {
  15:                 title
                      ^
  16:                 templateKey
  
- Unknown field 'title' on type 'MarkdownRemarkFrontmatter'. Source: document `AboutPage` file: `GraphQL request`
  
  GraphQL request (6:9)
  5:       frontmatter {
  6:         title
             ^
  7:       }
  
- Unknown field 'title' on type 'MarkdownRemarkFrontmatter'. Source: document `BlogPostByID` file: `GraphQL request`
  
  GraphQL request (8:9)
  7:         date(formatString: "MMMM DD, YYYY")
  8:         title
             ^
  9:         description
  
- Unknown field 'title' on type 'MarkdownRemarkFrontmatter'. Source: document `IndexPageTemplate` file: `GraphQL request`
  
  GraphQL request (5:9)
  4:       frontmatter {
  5:         title
             ^
  6:         image {
  
- Unknown field 'title' on type 'MarkdownRemarkFrontmatter'. Source: document `ProductPage` file: `GraphQL request`
  
  GraphQL request (5:9)
  4:       frontmatter {
  5:         title
             ^
  6:         image {
  
- Unknown field 'title' on type 'MarkdownRemarkFrontmatter'. 

      file: /Users/chrisjpatty/projects/igobyari-gatsby/src/templates/tags.js



error Command failed with exit code 1.
```

### Environment

```bash
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 60.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.34 => 2.3.12 
    gatsby-image: ^2.0.23 => 2.0.37 
    gatsby-plugin-netlify: ^2.0.6 => 2.0.13 
    gatsby-plugin-netlify-cms: ^4.0.0 => 4.0.0 
    gatsby-plugin-purgecss: ^3.1.0 => 3.1.1 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.11 
    gatsby-plugin-sass: ^2.0.7 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.15 => 2.0.32 
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.0.11 
    gatsby-remark-images: ^3.0.1 => 3.0.10 
    gatsby-remark-relative-images: ^0.2.1 => 0.2.2 
    gatsby-source-filesystem: ^2.0.26 => 2.0.28 
    gatsby-transformer-remark: ^2.3.4 => 2.3.8 
    gatsby-transformer-sharp: ^2.1.9 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

Thanks in advance for the help! I've had great experiences with Gatsby in the past, and I'm looking forward to working with it in the future. Thanks for all the hard work from everyone working on this project.

**Comment by jonniebigodes** [comment]
@chrisjpatty i've skimmed through the repository's code and based on your description, one thing caught my eye.

In `gatsby-node.js` you have:
```javascript
.....
 posts.forEach(edge => {
      const id = edge.node.id
      createPage({
        path: edge.node.fields.slug,
        tags: edge.node.frontmatter.tags,
        component: path.resolve(
          `src/templates/${String(edge.node.frontmatter.templateKey)}.js`
        ),
        // additional data can be passed via context
        context: {
          id,
        },
      })
    })
.....
 tags.forEach(tag => {
      const tagPath = `/tags/${_.kebabCase(tag)}/`

      createPage({
        path: tagPath,
        component: path.resolve(`src/templates/tags.js`),
        context: {
          tag,
        },
      })
    })
  })
```
Try changing the code to:
```javascript
posts.forEach(edge => {
      createPage({
        path: edge.node.fields.slug,
        tags: edge.node.frontmatter.tags,
        component: path.resolve(
          `src/templates/${String(edge.node.frontmatter.templateKey)}.js`
        ),
        // additional data can be passed via context
        context: {
          id:edge.node.id
        },
      })
    })
.....
 tags.forEach(tag => {
      const tagPath = `/tags/${_.kebabCase(tag)}/`

      createPage({
        path: tagPath,
        component: path.resolve(`src/templates/tags.js`),
        context: {
          tag,:tag
        },
      })
    })
  })
```

That's how you should pass data through Gatsby's special prop `context`, some issues have popped here,  with code similar to what you have. More on that [here](https://www.gatsbyjs.org/tutorial/part-seven/) and [here](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#pass-context-to-pages).  

Issue `gatsby clean` or your command to clean both `.cache` and `public` folders, Issue `gatsby develop` and see if the issue surfaces once more.

Feel free to provide feedback so that we can close this issue or continue to work on it till we find a solution.

**Comment by KyleAMathews** [comment]
Passing other top-level fields to createPage should create warnings in the terminal as well.

**Comment by chrisjpatty** [comment]
Thanks for help! The code in that repo comes directly from the netlify CMS starter. I did upgrade Gatsby up a couple of minor versions and it seemed to improve the error message I was receiving.  It turns out there was a problem with some of the blog post titles being numbers instead of strings. So the title field was being dropped. It's still strange that the build seemed to succeed occasionally, but after upgrading Gatsby the build at least was failing consistently. I'll close this issue as resolve. Thanks again for the help!

**Comment by jonniebigodes** [comment]
@chrisjpatty no need to thank, glad you managed to solve it. 👍

**Comment by sidharthachatterjee** [comment]
@godmar Remove the comma

**Comment by godmar** [comment]
Thanks @sidharthachatterjee , that's what I thought. 
It didn't make a difference (my issue was in the docz v1 starter); I realized that that's dead code so I abandoned it and am using v2 instead. Very arduous as well, btw.
