### ISSUE TITLE
How to import SVGs files that are processed?

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#13999]
## Summary

As per what I've seen images that require processing by gatsby-image or so are generally placed in `src/image/` and the ones that don't require processing and are just directly imported (generally SVG files) are placed in `static/`and imported.

I was a bit confused as to where I should place SVG files that are processed by a plugin such as gatsby-plugin-svgr or gatsby-plugin-react-svg which is generally used to inline the SVG data. What would be the best approach for this?

**Comment by DSchau** [comment]
@ajayns wouldn't SVG files used by those plugins be processed? e.g. gatsby-plugin-react-svg will process an SVG file and turn it into a React component.

In that case, it makes the most sense to use the `src` directory and co-locate the SVG files wherever they're being used (e.g. if used in src/components, then src/components/whatever.svg or src/components/images/whatever.svg), using whatever directory structure you like.

The idea of the static folder is that it is expressly and only to be used for assets that do not require any processing and that you want to have the _same_ path as in the built site (e.g. if you need /something.png, create static/something.png and it will be copied over _exactly as is_ to the public folder).

Hope this makes sense, and please let us know if we can provide any more clarity. Thanks!

**Comment by ajayns** [comment]
Thank you so much for the quick response. This clarifies most of my doubts.
