### ISSUE TITLE
Init new apps similar to Vue CLI

### ISSUE THREAD

**Issue by grantglidewell** [gatsbyjs/gatsby#13996]
## Summary

Vue CLI has an excellent feature selection interface for initializing a new project. For Gatsby this could mean selecting plugins, sources, and eventually themes. This can be used to initiate new projects that once a user has gone through the init process will have a hands free bespoke app with whatever themes plugins and related information ready to go. 

### Basic example

this is how VUE CLI behaves: https://cli.vuejs.org/guide/creating-a-project.html#vue-create
we could use functionality similar to [emma](https://github.com/maticzav/emma-cli) to find plugins/sources/themes.

Ideally usage would prompt the user for which configuration options they would like to have control over and then iterate through those options until an entire gatsby-config.js is completed.

additionally developers writing plugins could add prompts (or the cli would use typedefs to identify required options) so that the plugins are fully configured. 

This could also work in existing projects with a `gatsby add plugin x-y-z` command that will walk through setting up the options through the cli and users wont have to touch the gatsby-config at all. 

```shell
gatsby init ...
do you want to use a theme? y/n? Y

search for themes: blog...

are these the themes youre looking for?

[ ] gatsby-theme-bloga
[X] gatsby-theme-blogb << selected
[ ] gatsby-theme-blogc
```

### Motivation

If Gatsby goal is to be zero config (or best config out of the box), this gets a lot closer than having people `yarn add` and then edit their gatsby-config.js with options.

**Comment by wardpeet** [comment]
cc @shannonbux

**Comment by KyleAMathews** [comment]
Nice! @shannonbux added a similar issue @ https://github.com/gatsbyjs/gatsby/issues/14085

@gillkyle is working on a PR exploring this direction https://github.com/gatsbyjs/gatsby/issues/14085

I agree that we should move towards something like vue-cli — more research and thinking definitely needed. I think a step-by-step approach is good. There's a long list of things we want to improve on our CLI.

**Comment by shannonbux** [comment]
Yes, I'll spearhead testing the #14085 implementation and if it goes well, then try expanding it to include more! I'm glad we're exploring this now before themes become more mainstream

**Comment by shannonbux** [comment]
I think we'll definitely revisit this once themes are ready!
