### ISSUE TITLE
Gatsby does not generate pages defined as arrow functions

### ISSUE THREAD

**Issue by Ethan-Arrowood** [gatsbyjs/gatsby#13995]
## Description

I've created a new page in my gatsby site called `about.js` in the `src/pages` directory. It has the following content:
```js
import React from 'react'

const About = () => {
  return (
    <div>
      <h2>About Page</h2>
    </div>
  )
}

export default About
```

When I run `npm run develop`, Gatsby does not generate a page at the `/about` url. 

Changing the `About` function declaration to `function About() { ... }` fixes the problem.

**Why does Gatsby not generate a page when it is an arrow function?**

The `index.js` page is defined as:
```js
import React from 'react'

const Layout = () => {
  return (
    <div>
      <h1>My Site</h1>
    </div>
  )
}

export default Layout
``` 
And Gatsby handles generating the root route just fine.

If this is intended (which i imagine it is). Then I believe a section should be added to the documentation in any of the following spots so this is clarified better.
- https://www.gatsbyjs.org/docs/building-with-components/#page-components
- https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#creating-pages-in-gatsby-nodejs

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.3
    Safari: 12.1
  npmPackages:
    gatsby: ^2.4.3 => 2.4.3 
    gatsby-image: ^2.0.41 => 2.0.41 
    gatsby-plugin-sharp: ^2.0.37 => 2.0.37 
    gatsby-remark-images: ^3.0.11 => 3.0.11 
    gatsby-source-filesystem: ^2.0.33 => 2.0.33 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 
  npmGlobalPackages:
    gatsby: 2.4.3

**Comment by polishedwp** [comment]
@Ethan-Arrowood can you post a repo for testing. I was able to create an About page with your arrow function code about without any problems in the default starter.

**Comment by jonniebigodes** [comment]
@Ethan-Arrowood while working on another unrelated issue and using the hello world starter i adapted the code and created following your description and issued `gatsby develop` and `gatsby build && gatsby serve`, both ways show the page in question.

**Comment by Ethan-Arrowood** [comment]
🙃 well now not even I can reproduce it. Hmmf maybe something else was off with my set up. 🐞 gotta love it. Closing
