### ISSUE TITLE
Some pages are missing on build/serve

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#13998]
## Description
 
I have a page which is not appear to the build. 
That page works well on local. I can access it normally.

I found the bug in production (using Netlify) which said : "Missing ressource for /profile/activation"

So I run `build` or `serve` before production  I saw these pages:

```
{ pathname: '/login/', search: '', hash: '' }
{ pathname: '/OI/CreateOI/', search: '', hash: '' }
{ pathname: '/OI/HomepageOI/', search: '', hash: '' } '' },
{ pathname: '/OI/ListOI/', search: '', hash: '' }
{ pathname: '/signup/', search: '', hash: '' }
{ pathname: '/404.html', search: '', hash: '' }
```

One of them is missing : 
```
{ pathname: '/profile/activation', search: '', hash: '' }
```

In `gatsby-node` I have this, and it works perfectly for `page-OI` but not for `page-profile`.

```
 if (page.path.match(/^\/page-profile/)) {
    page.matchPath = `/profile/*`;
    createPage(page);
  }

  if (page.path.match(/^\/page-OI/)) {
    page.matchPath = `/OI/*`;
    createPage(page);
  }
```

I have this 2 files : page-OI.js and page-profile.js

In page-profile.js

```
const Index = props => (
    <Router>
      <ProfileActivation path="/profile/activation" />
    </Router>
);
export default Index;
```

In page-profile.js
```
const Index = props => (
    <Router>
      <PrivateRoute path="/OI/create" component={CreateOI} />
      <ListOI path="/OI/initiatives" />
      <HomepageOI path="/OI" />
    </Router>
);
export default Index;
```

### Steps to reproduce

`yarn serve`

### Expected result

Should build ALL pages define in `gatsby-node`

### Actual result

Some pages missing for build.

When I trying to access the page : 
— on local > It redirects to homepage (index.js)
— on production > Blank page "Error: Missing ressource for `/profile/activation`

### Environment

gatsby-config.js : 
```
module.exports = {
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-plugin-emotion`,
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/static/images/`,
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    'gatsby-plugin-netlify'
  ],
};
```

gatsby info : 
```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.0 => 2.0.118 
    gatsby-cli: ^2.4.16 => 2.4.16 
    gatsby-image: ^2.0.26 => 2.0.29 
    gatsby-plugin-emotion: ^4.0.1 => 4.0.3 
    gatsby-plugin-netlify: ^2.0.12 => 2.0.12 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.6 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.20 
    gatsby-source-filesystem: ^2.0.12 => 2.0.20 
    gatsby-transformer-sharp: ^2.1.10 => 2.1.13 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by Steffi3rd** [comment]
<img width="740" alt="Capture d’écran 2019-05-13 à 11 57 50" src="https://user-images.githubusercontent.com/814410/57613158-791c4f80-7576-11e9-9048-4425d2ada086.png">

**Comment by Steffi3rd** [comment]
URL : https://edgebase-v2.netlify.com/profile/activation

**Comment by DSchau** [comment]
I _think_ the problem you're trying to solve here is a dynamic route, e.g. /profile will be a wildcard?

It's pretty challenging to debug this in the absence of a [reproduction](https://gatsby.dev/reproduction) so I'd request you provide one here so we can solve this most effectively.

Thanks!

**Comment by Steffi3rd** [comment]
Ohhh... I think I understand what you mean.

I don't have no route `/profile` but I have `/profile/activation`

That's the problem?

**Comment by DSchau** [comment]
I don't honestly know what the problem is until we get that reproduction--but that's my guess, yeah!

**Comment by Steffi3rd** [comment]
Found one thing very interesting.

I add a page `ProfileIndex` to match with `/profile`.

First I did this, and it didn't work 
```
const ProfileIndex = props => "ProfileIndex";
export default ProfileIndex;
```

Finally I did this, and it worked
```
const ProfileIndex = props => {
  console.log('ProfileIndex', props);
  return 'ProfileIndex';
};
```

I saw my page in the building list... when I add a `return` and a `console.log(...)`

Do you have an explanation for this?
