### ISSUE TITLE
View counter 

### ISSUE THREAD

**Issue by Hypothesis-github** [gatsbyjs/gatsby#13994]
I wonder if there is a way or plugin in which I can show the number of views on a certain gatsby page or each page individually.

**Comment by jonniebigodes** [comment]
@Hypothesis-github have you looked at [this](https://www.gatsbyjs.org/docs/adding-analytics/)? And see if it suits your needs?

**Comment by Hypothesis-github** [comment]
> @Hypothesis-github have you looked at [this](https://www.gatsbyjs.org/docs/adding-analytics/)? And see if it suits your needs?

Nothing like old school showing this page has had 100 views ? can I do it with this one ?

**Comment by DSchau** [comment]
This isn't necessarily a Gatsby question, but happy to provide some assistance here.

The idea here is that you will need:

1. An endpoint to register a visit (e.g. a tracking gif/image would work just fine here)
1. An endpoint to return page visits for a particular path
1. A plugin (or functionality) to embed the tracking visit and (optionally) a component to display this with a client-side request

I quite liked [this article](https://benhoyt.com/writings/replacing-google-analytics/) to show how you could implement steps 1 and 2. Step 3 would be just exposing functionality to surface that analytics and return a count, e.g. a React component like this would do the trick just fine:

```jsx
import { useState, useEffect } from 'react'

export default function useVisits(pathname) {
  const [visits, setVisits] = useState(0)
  useEffect(() => {
    // may need to polyfill fetch, depending on browser
    fetch(`https://whatever-tracking-url.com/${pathname}`)
      .then(response => response.text())
      .then(numVisits => setVisits(numVisits))
  }, [pathname])

  return visits
}

// later
function Counter({ pathname }) {
  const visits = useVisits(pathname)
  return <h1>{visits}</h1>
}
```

Hope this helps! Going to close as answered, but let us know if we can help further.

**Comment by leerob** [comment]
For anyone who stumbled on this: I went with a similar solution as mentioned above when adding a view counter to my blog.

- A microservice that increments view counts in a Firebase Realtime Database
- A React component to subscribe to view updates and highlight the count

https://leerob.io/blog/real-time-post-views/

**Comment by olegKusov** [comment]
> For anyone who stumbles onto this: I went with a similar solution as mentioned above when adding a view counter to my blog.
> 
> * A microservice that increments view counts in a Firebase Realtime Database
> * A React component to subscribe to view updates and highlight the count
> 
> Cheers! 🎉
> 
> https://leerob.io/blog/real-time-post-views/

i don't undertand how you use backend code in GatsbyJS

**Comment by leerob** [comment]
@olegKusov Hey! You use backend code with Gatsby through any API call. In my example above, the code to track view counts is all managed through communication with an API.

I've actually found an even better solution for those who don't want to mess with backend code. 

https://docs.views.show/

**Comment by olegKusov** [comment]
> @olegKusov Hey! You use backend code with Gatsby through any API call. In my example above, the code to track view counts is all managed through communication with an API.
> 
> I've actually found an even better solution for those who don't want to mess with backend code.
> 
> https://docs.views.show/

Now it is clear. Thanks

**Comment by philodotshop** [comment]
> @olegKusov Hey! You use backend code with Gatsby through any API call. In my example above, the code to track view counts is all managed through communication with an API.
> 
> I've actually found an even better solution for those who don't want to mess with backend code.
> 
> https://docs.views.show/

Hi @leerob, thanks for the tutorial. I have cloned the repo, set up the firebase & service-account.json, and substituted the values. It's running perfectly on localhost:3000 tracking views count. RTDB in firebase does sync with it as well. But I don't understand how to integrate it with gatsby.  Does it only work through vercel.json and Next ? please help

**Comment by mshams999** [comment]
Hi @leerob, thanks for the tutorial.

i can't really add it to my gatsbby blog. can you make a blog post about how to add it.

**Comment by leerob** [comment]
> Hi @leerob, thanks for the tutorial. I have cloned the repo, set up the firebase & service-account.json, and substituted the values. It's running perfectly on localhost:3000 tracking views count. RTDB in firebase does sync with it as well. But I don't understand how to integrate it with gatsby. Does it only work through vercel.json and Next ? please help

Previously, I was using a completely separate microservice for logging views. I've since switched to an API route in Next.js since it's part of the framework. For Gatsby, you could:

- Deploy with Vercel and create an `/api` folder in your project. 
- Deploy with Netlify and use their serverless functions

Or create your own Express microservice and deploy/host it wherever you want! Heroku, etc.

**Comment by iloveip** [comment]
Hi @leerob,
Is it possible to add view counter to Gatsby site with Google Analytics?

**Comment by leerob** [comment]
@iloveip Yes, it is! You can follow [my tutorial](https://leerob.io/blog/google-analytics-api-nextjs) for integrating with Google Analytics and then deploy a serverless function using Vercel.

**Comment by iloveip** [comment]
@leerob Thank you very much! 🙏
