### ISSUE TITLE
non-index pages are created as name-of-file.html/index.html

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#14]

**Comment by phlogisticfugu** [comment]
Just found gatsby, which looks pretty much what I'd wanted in a static site generator.

Looks like this issue is still occurring.  To confirm, if there's a file:

pages/about.md

then should it build to:

public/about/index.html
or
public/about.html
?

or should that maybe be configurable?

**Comment by KyleAMathews** [comment]
Glad to hear!

And yes... this bug needs fixed still. It shouldn't be too hard to fix just haven't taken the time yet.

I think it'd be nice to default to building index files (`about.md` becomes `/about/index.html`) as aesthetically I prefer urls without `.html` at the end but definitely make it configurable.

A PR to fix this would be great!

**Comment by phlogisticfugu** [comment]
made a PR.

found that the usage of `about/index.html` came from the static-site-generator-webpack-plugin so that was not easily configurable.

**Comment by KyleAMathews** [comment]
Oh interesting... that should be fixed. I'll open an issue on the static-site-generator plugin then.
