### ISSUE TITLE
onCreatePage Api 

### ISSUE THREAD

**Issue by harshalpatel91** [gatsbyjs/gatsby#14008]
Hi,

Do onCreatePage Api have graphql as args like we have in createPages Api. I wanted to use graphlql inside onCreatePage method.

**Comment by harshalpatel91** [comment]
We were trying Gatsby for our use case where we want to change the route of a page which is generated from inside pages folder. We are using onCreatePage method for it. But since we wanted to run the graphql query and get data for URL and set it on page.path so that we can control routes from our CMS. I'm finding that currently, we don't get graphql as args as we have in createPages method. Do you have any recommendation for the above use case.

**Comment by freiksenet** [comment]
You can use graphql in createPages, check out [this guide](https://www.gatsbyjs.org/docs/programmatically-create-pages-from-data/).

**Comment by harshalpatel91** [comment]
@freiksenet, thanks for looking into it.

I have tried createPages api, but in above case I wanted to change the routes/path of the pages which are generate by gatsby core and wanted to create dynamic routes by running graphql query inside onCreatePage api.

**Comment by wardpeet** [comment]
Is it possible to give use a code snippet of what you're trying to do? You should be able to add extra information to internal pages with the creagePages API.

checkout https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#pass-context-to-pages

**Comment by harshalpatel91** [comment]
@wardpeet, thanks for giving your time in looking this. 

In my case I wanted to change the routes/path of the pages which are generate by gatsby core (i.e inside pages folder and not the pages created by createPages API).

**Comment by pieh** [comment]
@harshalpatel91 What about this - instead of using `src/pages` put your page components in `src/templates` (for example - just so Gatsby doesn't automatically create pages for them). And then use `createPages` API to create pages for them (using results of `graphql` to get path for them)

**Comment by harshalpatel91** [comment]
@pieh, that option we have but when we think of maintaining the code & pagequery, the src/pages are quite simple and easy to handle in comparing with createPages API for static pages

**Comment by freiksenet** [comment]
@harshalpatel91 Sorry, we won't support changing URLs in `src/pages`, the point of that API is to be simple and we feel it will unnecessary complicate things. We recommend that you use `createPages` api in cases where you need custom URLs.

I'm closing this issue, feel free to open it if you have further questions. :purple_heart: :muscle:

**Comment by harshalpatel91** [comment]
@freiksenet, no worries will consider createPages api.

**Comment by jessjohnstonuk** [comment]
In my case, I'm trying to use `onCreatePage` to pass data into my 404 page for my navigation component.
Is it possible to use `onCreatePage` with the `async / await` api in order to pass in the data?
