### ISSUE TITLE
Failed to compile with 16 errors when upgrading from v0 to v1 

### ISSUE THREAD

**Issue by julianomoreira** [gatsbyjs/gatsby#1400]
I'm upgrading from v0.12.45 to v1.0.5 and I'm getting this error. I followed the guide, [migrating from v0 to v1](https://www.gatsbyjs.org/docs/migrating-from-v0-to-v1/) but I didn't work. The migration guide feels incomplete to me since there's a lot more that needs to be done to upgrade successfully. 

```ERROR  Failed to compile with 16 errors                                                                                                         11:25:06 AM

These dependencies were not found:

* fs in ./~/config/lib/config.js, ./~/coffee-script/lib/coffee-script/coffee-script.js and 4 others
* hjson in ./~/config/lib/config.js
* cson in ./~/config/lib/config.js
* properties in ./~/config/lib/config.js
* x2js in ./~/config/lib/config.js
* module in ./~/coffee-script/lib/coffee-script/coffee-script.js, ./~/coffee-script/lib/coffee-script/register.js
* child_process in ./~/coffee-script/lib/coffee-script/register.js, ./~/coffee-script/lib/coffee-script/command.js
* jison in ./~/coffee-script/lib/coffee-script/grammar.js
* repl in ./~/coffee-script/lib/coffee-script/repl.js

To install them, you can run: npm install --save fs hjson cson properties x2js module child_process jison repl```

**Comment by jquense** [comment]
this sounds like you have stale or outdated depedencies. I'd nuke your `node_modules` and install from scratch. The deps above wouldn't be something you'd install manually

**Comment by julianomoreira** [comment]
I tried that but it didn't work. Any other options?

**Comment by whmountains** [comment]
Try nuking `package-lock.json` and/or `yarn.lock`.

**Comment by julianomoreira** [comment]
Here it is what I've tried so far with no success:

- removed node_modules from dir
- removed yarn.lock file
- removed gatsby globally and reinstalled with `yarn global add gatsby`
- reinstalled modules with `yarn install` in the dir

Nothing seems to work.

**Comment by KyleAMathews** [comment]
Can you push your code somewhere so we can take a look at it?

**Comment by julianomoreira** [comment]
@KyleAMathews Yes. I pushed it to a repo on Github [here](https://github.com/julianomoreira/gatsby-site)

**Comment by KyleAMathews** [comment]
* This isn't JS code https://github.com/julianomoreira/gatsby-site/blob/master/gatsby-config.js
* .cache should be ignored
* we're not using markdown-loaders anymore
* Looks like you haven't followed this step yet https://www.gatsbyjs.org/docs/migrating-from-v0-to-v1/#migrate-wrapper-components-to-template-components

**Comment by julianomoreira** [comment]
Fixed all these above. I'm still getting errs. Can you take a look again? Thanks!

**Comment by KyleAMathews** [comment]
@julianomoreira try playing around with some example sites and compare them with your site.

**Comment by julianomoreira** [comment]
@KyleAMathews I'm actually thinking about starting from scratch. Are the example sites up-to-date as well? Thanks!

**Comment by KyleAMathews** [comment]
Once I merge https://github.com/gatsbyjs/gatsby/pull/1404 they will be :-)

You can also try the default starter as well by running `gatsby new site-name`

**Comment by julianomoreira** [comment]
@KyleAMathews I'm playing with the default starter right now. Thanks!
