### ISSUE TITLE
Shadow component logging

### ISSUE THREAD

**Issue by maecapozzi** [gatsbyjs/gatsby#14006]
Issue moved from https://github.com/ChristopherBiscardi/gatsby-theme-examples/ at the request of @ChristopherBiscardi.

## Summary

When shadowing components, it can easily become pretty confusing to know where in this folder structure the shadowing is actually happening, especially when it is several levels deep. It would be nice if Gatsby, when themes are used, could show when/where it happens.

Perhaps just showing something in the terminal logs, could visually display the shadowing chain? Not really sure the best way to go about this, but thinking of something like this:

```
ComponentX originated in gatsby-theme-core
ComponentX was shadowed by gatsby-theme-blog-a
ComponentX was shadowed by gastby-theme-blog-b
```

### Basic example

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

**Comment by maecapozzi** [comment]
Hey @LekoArts, Chris asked me to assign him to these issues.

**Comment by ChristopherBiscardi** [comment]
Started working on this in Italy last week as a separate CLI tool. I want to move some of the shadow group logic to separate functions that can be imported and shared by not only this CLI tool, but also the hot-reload logic.

**Comment by johnletey** [comment]
@ChristopherBiscardi What is the update on this? I can take over with your current code if you'd like

**Comment by LekoArts** [comment]
This will be solved with https://github.com/gatsbyjs/gatsby/pull/22713
