### ISSUE TITLE
Copy static folder for each theme develop-time

### ISSUE THREAD

**Issue by maecapozzi** [gatsbyjs/gatsby#14003]
Issue moved from https://github.com/ChristopherBiscardi/gatsby-theme-examples/ at the request of @ChristopherBiscardi.

The static folder in each theme should be copied into the final static dir. Right not only the user's is.

**Comment by pieh** [comment]
I think some clarification is needed here. On builds it seems that `static` directories are being copied already ( https://github.com/gatsbyjs/gatsby/blob/d4b60f2b900a59b70dd2d97cf14125c77c1de4df/packages/gatsby/src/utils/get-static-dir.js#L6-L30 ). For development it's not happening, so [`syncStaticDir`](https://github.com/gatsbyjs/gatsby/blob/d4b60f2b900a59b70dd2d97cf14125c77c1de4df/packages/gatsby/src/utils/get-static-dir.js#L32-L49) is function that need to be updated to handle themes static directories

**Comment by ChristopherBiscardi** [comment]
[this PR](https://github.com/gatsbyjs/gatsby/commit/edd6cb1f28ba550b74987a77a9f1eb25dd5138f8) handled themes directories for builds. As you've said, we need to update `syncStaticDir` for development.

**Comment by gillkyle** [comment]
So it sounds like these lines basically just need to appear again inside of the `syncStaticDir` folder as well to be keeping files in the `public` directory up to date with what's happening during `gatsby develop`? 

https://github.com/gatsbyjs/gatsby/blob/d4b60f2b900a59b70dd2d97cf14125c77c1de4df/packages/gatsby/src/utils/get-static-dir.js#L13-L25

**Comment by ChristopherBiscardi** [comment]
@gillkyle basically, yes. We also need to make sure the order of copying over is preserved though. So if a file changes and a later package in the theme order has a file named the same in the same location, the last file wins.

**Comment by ehannes** [comment]
Any news on this?

**Comment by sarahbethfederman** [comment]
I'm experiencing this issue with trying to provide a webfont in my theme's static folder

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
