### ISSUE TITLE
Best way to trigger a site init function in GatsbyJS?

### ISSUE THREAD

**Issue by Sondro** [gatsbyjs/gatsby#14012]
Hi, I need to be able to init a page based off cookie settings.

So back in the day you could just do a ```<body onload="func()" />```

I've seen different ways to do this in React with props and querying the virtual DOM, but what is the best way to do this in GatsbyJS in particular?

Right now I just have a quick hack with ```<body onLoad={myFunc()} />``` and then I set a bool to return every time a link is clicked.

**Comment by pieh** [comment]
Depending on when exactly you want to get your callback called you can use one of those Gatsby browser APIs:
 - [`onClientEntry`](https://www.gatsbyjs.org/docs/browser-apis/#onClientEntry) - this will be first thing that runs (before mounting react application)
 - [`onInitialClientRender`](https://www.gatsbyjs.org/docs/browser-apis/#onInitialClientRender) - this will run after react application has mounted

I'm not sure what you want to do there, so if those won't work for you, please add more information so we talk about specific use case.

**Comment by Sondro** [comment]
Thanks a lot this should be useful. Haven't had time to try it, but seems like it should work.
