### ISSUE TITLE
Update Plugin repos that aren't appearing in Plugin library

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#14013]
There are a lot of plugins floating around on repositories that aren't included in the plugin library. Issue #5211 was created to address this, and a lot of progress was made on [a script that will find plugins](https://github.com/gatsbyjs/gatsby/tree/master/scripts/gatsby-plugin-checker) that mention `gatsby-source`, `gatsby-plugin`, or `gatsby-transformer` and don't match the list from Gatsby's keyword search for plugins to include in the library. However, that issue didn't track fixes to repositories that needed to be updated and the script hasn't been completed to post issues in GitHub repositories.

## Steps

These packages just need the `gatsby` and `gatsby-plugin` keywords included in their `package.json` ([docs for reference](https://www.gatsbyjs.org/contributing/submit-to-plugin-library/)). For each plugin:

1. Find the plugin's source code from npm
2. Submit a PR (or an issue, maybe they don't want their plugin showing up in the library? 🤷‍♂ ) that makes sure both `gatsby` and `gatsby-plugin` are included in the keywords section of the `package.json`
3. Mark that plugin as done in this issue

## Plugins to Update

Running the script lists these packages from npm that should be updated:

(Check marks are added when an issue or PR has been created, they are crossed out when keywords have been merged)

(_Update_: all repos have had an issue or PR filed, thanks everyone!)

- [X] [gatsby-plugin-zygote](https://www.npmjs.com/package/gatsby-plugin-zygote)
- [X] [gatsby-plugin-escalade-stock](https://www.npmjs.com/package/gatsby-plugin-escalade-stock)
- [X] [gatsby-plugin-product-markdown-pages](https://www.npmjs.com/package/gatsby-plugin-product-markdown-pages)
- [X] [gatsby-plugin-source-john-deere](https://www.npmjs.com/package/gatsby-plugin-source-john-deere)
- [X] ~[gatsby-plugin-production](https://www.npmjs.com/package/gatsby-plugin-production)~
- [X] [gatsby-source-product-markdown](https://www.npmjs.com/package/gatsby-source-product-markdown)
- [X] ~[gatsby-plugin-purify-css](https://www.npmjs.com/package/gatsby-plugin-purify-css)~
- [X] ~[gatsby-plugin-stripe-elements](https://www.npmjs.com/package/gatsby-plugin-stripe-elements)~
- [x] ~[gatsby-plugin-indieweb](https://www.npmjs.com/package/gatsby-plugin-indieweb)~
- [X] ~[gatsby-plugin-i18n-extension](https://www.npmjs.com/package/gatsby-plugin-i18n-extension)~
- [X] ~[gatsby-plugin-favicons](https://www.npmjs.com/package/gatsby-plugin-favicons)~
- [X] ~[gatsby-source-jsonapi](https://www.npmjs.com/package/gatsby-source-jsonapi)~
- [X] ~[gatsby-source-twitter-users](https://www.npmjs.com/package/gatsby-source-twitter-users)~
- [X] [gatsby-source-medium-posts](https://www.npmjs.com/package/gatsby-source-medium-posts)
- [X] [gatsby-source-itchio](https://www.npmjs.com/package/gatsby-source-itchio)
- [x] ~[gatsby-transformer-geojson](https://www.npmjs.com/package/gatsby-transformer-geojson)~
- [X] [gatsby-source-gdrive-tree](https://www.npmjs.com/package/gatsby-source-gdrive-tree)
- [X] ~[gatsby-plugin-polyfill-cdn](https://www.npmjs.com/package/gatsby-plugin-polyfill-cdn)~
- [X] [gatsby-plugin-channel](https://www.npmjs.com/package/gatsby-plugin-channel)
- [X] ~[gatsby-source-stripe-products](https://www.npmjs.com/package/gatsby-source-stripe-products)~
- [X] [gatsby-transformer-exif](https://www.npmjs.com/package/gatsby-transformer-exif)
- [X] ~[gatsby-plugin-snowplow](https://www.npmjs.com/package/gatsby-plugin-snowplow)~
- [X] ~[gatsby-plugin-protoculture](https://www.npmjs.com/package/gatsby-plugin-protoculture)~
- [X] [gatsby-source-sapcc](https://www.npmjs.com/package/gatsby-source-sapcc)
- [X] ~[gatsby-plugin-landr](https://www.npmjs.com/package/gatsby-plugin-landr)~
- [X] ~[gatsby-plugin-ngrok-tunneling](https://www.npmjs.com/package/gatsby-plugin-ngrok-tunneling)~
- [X] ~[gatsby-source-newsapi](https://www.npmjs.com/package/gatsby-source-newsapi)~
- [X] [gatsby-plugin-mui](https://www.npmjs.com/package/gatsby-plugin-mui)
- [X] ~[gatsby-plugin-drip](https://www.npmjs.com/package/gatsby-plugin-drip)~
- [X] [gatsby-source-google-calendar](https://www.npmjs.com/package/gatsby-source-google-calendar)
- [x] [gatsby-source-google-sheet](https://www.npmjs.com/package/gatsby-source-google-sheet)
- [X] ~[gatsby-source-anilist](https://www.npmjs.com/package/gatsby-source-anilist)~
- [x] ~[gatsby-source-github-api](https://www.npmjs.com/package/gatsby-source-github-api)~
- [x] [gatsby-plugin-github-pages](https://www.npmjs.com/package/gatsby-plugin-github-pages)
- [X] [gatsby-plugin-facebook-sdk](https://www.npmjs.com/package/gatsby-plugin-facebook-sdk)
- [X] ~[gatsby-source-nba](https://www.npmjs.com/package/gatsby-source-nba)~
- [x] ~[gatsby-source-steam](https://www.npmjs.com/package/gatsby-source-steam)~
- [X] [gatsby-source-gcloud-object](https://www.npmjs.com/package/gatsby-source-gcloud-object)
- [X] [gatsby-plugin-sass-bulk-import](https://www.npmjs.com/package/gatsby-plugin-sass-bulk-import)
- [X] [gatsby-plugin-iamport](https://www.npmjs.com/package/gatsby-plugin-iamport)
- [X] [gatsby-plugin-graphql](https://www.npmjs.com/package/gatsby-plugin-graphql)
- [x] ~[gatsby-plugin-netlify-lambda](https://www.npmjs.com/package/gatsby-plugin-netlify-lambda)~
- [X] ~[gatsby-plugin-core-js](https://www.npmjs.com/package/gatsby-plugin-core-js)~
- [X] ~[gatsby-source-github-projects](https://www.npmjs.com/package/gatsby-source-github-projects)~
- [X] ~[gatsby-plugin-google-fonts](https://www.npmjs.com/package/gatsby-plugin-google-fonts)~
- [x] ~[gatsby-source-utopian](https://www.npmjs.com/package/gatsby-source-utopian)~
- [X] ~[gatsby-transformer-ipynb](https://www.npmjs.com/package/gatsby-transformer-ipynb)~
- [x] [gatsby-plugin-react-webfont-loader](https://www.npmjs.com/package/gatsby-plugin-react-webfont-loader)
- [X] ~[gatsby-plugin-module-local-ident-name](https://www.npmjs.com/package/gatsby-plugin-module-local-ident-name)~
- [X] ~[gatsby-plugin-copy-files](https://www.npmjs.com/package/gatsby-plugin-copy-files)~
- [X] [gatsby-plugin-size-analyzer](https://www.npmjs.com/package/gatsby-plugin-size-analyzer)
- [X] ~[gatsby-plugin-favicon-mperkh](https://www.npmjs.com/package/gatsby-plugin-favicon-mperkh)~
- [X] [gatsby-source-jira](https://www.npmjs.com/package/gatsby-source-jira)
- [X] ~[gatsby-source-published-google-sheets](https://www.npmjs.com/package/gatsby-source-published-google-sheets)~
- [X] ~[gatsby-source-airtable-linked](https://www.npmjs.com/package/gatsby-source-airtable-linked)~
- [X] ~[gatsby-source-soundcloud](https://www.npmjs.com/package/gatsby-source-soundcloud)~
- [X] ~[gatsby-source-twitch](https://www.npmjs.com/package/gatsby-source-twitch)~
- [X] [gatsby-source-mongo](https://www.npmjs.com/package/gatsby-source-mongo)
- [X] ~[gatsby-source-wordpress-bcgdv](https://www.npmjs.com/package/gatsby-source-wordpress-bcgdv)~
- [X] ~[gatsby-transformer-nimbl](https://www.npmjs.com/package/gatsby-transformer-nimbl)~
- [X] ~[gatsby-transformer-whoa](https://www.npmjs.com/package/gatsby-transformer-whoa)~

If someone is feeling ambitious, development of the script discussed in #5211 could be continued in that issue for the future when more plugins leave off these keywords, but it'd be helpful to simply make a PR to existing repositories from the list above including the keywords and get these plugins included in the library.

Once a plugin has had keywords merged into it's repo, feel free to edit this issue to check it off the list 🙂

**Comment by wardpeet** [comment]
Awesome @gillkyle, you're the best!

**Comment by marcysutton** [comment]
Related to https://github.com/gatsbyjs/gatsby/issues/12503

**Comment by ashley** [comment]
Hi! Here are the plugins I have made PRs to (they include some that already included the keywords).

- [X]  gatsby-plugin-escalade-stock
- [X]   gatsby-plugin-product-markdown-pages
- [x]   gatsby-plugin-source-john-deere
- [x]   gatsby-plugin-production
- [x] gatsby-source-product-markdown
- [x]   gatsby-plugin-purify-css
- [x]   gatsby-plugin-stripe-elements
- [x]   gatsby-plugin-indieweb
- [x]   gatsby-plugin-i18n-extension
- [x]   gatsby-plugin-favicons
- [x]   gatsby-source-jsonapi
- [x] gatsby-source-twitter-users
- [x]   gatsby-source-medium-posts
- [x]   gatsby-source-itchio
- [x]   gatsby-transformer-geojson
- [x]   gatsby-source-gdrive-tree
- [x]   gatsby-plugin-polyfill-cdn
- [x]   gatsby-plugin-channel
- [ ]   gatsby-source-stripe-products (archived repo)
- [x]   gatsby-transformer-exif
- [x]   gatsby-plugin-snowplow

**Comment by dmarkiewicz** [comment]
Hi! I've just made my first open source pull request in gatsby-plugin-graphql. I will try to hunt another plugins as soon as I get home.

- [ ] gatsby-plugin-graphql

**Comment by wardpeet** [comment]
we probably want to update our script somehow to check if a repo is archived or not. If anyone wants to update https://github.com/gatsbyjs/gatsby/blob/master/scripts/gatsby-plugin-checker/index.js we would be grateful.

**Comment by dmarkiewicz** [comment]
I would like to take care of it. Should I just create a pull request or are there any other steps I need to take?

**Comment by gillkyle** [comment]
Thanks for the help @ashley and @dmarkiewicz! 

---

@dmarkiewicz I would reference the guidelines mentioned in [Issue 5211](https://github.com/gatsbyjs/gatsby/issues/5211) as well, but then making a pull request that at least checks if the repo is archived like @wardpeet mentioned would be fantastic 🙂

**Comment by dmarkiewicz** [comment]
@gillkyle I think that checking if repositories are archived require a Github App Token because there is a limit of 60 requests per hour. To check if repository is archived I need to call API for each of them and that might exceed the limit. Is there a possibility to create such token?

**Comment by RobinCsl** [comment]
Issue Created:
- [ ] [gatsby-source-twitch](https://www.npmjs.com/package/gatsby-source-twitch) 
- [ ] [gatsby-source-soundcloud](https://www.npmjs.com/package/gatsby-source-soundcloud)

PR:
- [ ] [gatsby-source-google-calendar](https://www.npmjs.com/package/gatsby-source-google-calendar)

**Comment by gillkyle** [comment]
Thanks for adding your help on so many of these @RobinCsl! 

I guess that Netlify lambda plugin must be in a private repo or something. If that's the case they may not want to include it as a plugin in the library but good we've at least made them aware how they can!

**Comment by poyea** [comment]
I've opened two PRs for now:

- [ ] [gatsby-transformer-nimbl](https://github.com/NimblNotes/gatsby-transformer-nimbl/pull/2)
- [ ] [gatsby-plugin-core-js](https://github.com/lloydh/gatsby-plugin-core-js/pull/1)

**Comment by PriyaBhatt13** [comment]
PRs Created:

- [ ] gatsby-source-newsapi

- [ ] gatsby-source-nba

- [ ] gatsby-source-gcloud-object

- [ ] gatsby-plugin-drip

**Comment by wardpeet** [comment]
@dmarkiewicz let's just not do it then, api tokens are to much hassle when running it. Another way would be to do a get request to the repo and search for the string but that's just to messy so we'll just deal with it 😎 

Thanks for looking into it!

**Comment by gillkyle** [comment]
Thanks for finishing up the last packages @PriyaBhatt13!

We've now got PRs and issues filed in all the repos listed, thanks for all the help 🥇 I'll be monitoring the issues here to watch as things (hopefully) get merged in.

**Comment by gillkyle** [comment]
I sent emails to the package authors that haven't been updated yet, encouraging them to merge PR's, several have responded already.

**Comment by gillkyle** [comment]
Closing as we've done what we can on our end, many of the remaining plugins aren't being maintained or updated and pull requests have been made that package maintainers have the option of merging. 

According to the initial list 37 plugins were added to the plugin library so thanks everyone! 👏
