### ISSUE TITLE
Hosting Gatsby Blog within Express Application

### ISSUE THREAD

**Issue by daningamells** [gatsbyjs/gatsby#14021]
Hey all,

This may be a stupid question and if so apologies. I have my website hosted on Heroku (Express application). I also have a blog I have created with Gatsby, I want to host Gatsby @ www.mysite.com/blog, can I host my Gatsby app from within my Express app and if so how do I call Gatsby from my Express routes.

Thanks

Daniel Ingamells

**Comment by pieh** [comment]
There are few things here:
 - first, if you want to host Gatsby not in the root of domain (`/blog`), you will need to use [path prefix](https://www.gatsbyjs.org/docs/path-prefix/) when building your site
 - then in your express application you could use:
   ```js
   const app = express()
   const router = express.Router()
   router.use(compression())
   router.use(express.static(`public`))
   // this would be needed if you use client routes/`matchPath` (see https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/serve.js for implementation of `clientOnlyPathsRouter`)
   router.use(clientOnlyPathsRouter(pages, { root }))
   // serve 404 if nothing found
   router.use((req, res, next) => {
     if (req.accepts(`html`)) {
       return res.status(404).sendFile(`404.html`, { root })
     }
     return next()
   })
   app.use(function(req, res, next) {
     res.header(`Access-Control-Allow-Origin`, `http://${host}:${port}`)
     res.header(`Access-Control-Allow-Credentials`, true)
     res.header(
       `Access-Control-Allow-Headers`,
       `Origin, X-Requested-With, Content-Type, Accept`
     )
     next()
   })
   // use same pathPrefix as one you build site with
   app.use(pathPrefix, router)
   ```

**Comment by daningamells** [comment]
Hey, 

Thanks for the reply, struggling to get my head round this, would you happen to have a working example I could use for reference?

Thanks
