### ISSUE TITLE
Youtube Embeds don't work on Google Chrome iOS Mobile

### ISSUE THREAD

**Issue by tylermcrobert** [gatsbyjs/gatsby#14032]
## Description

Youtube embeds on Mobile Chrome do not play. 

### Steps to reproduce

Using justdoit.nike.com as an example as it's the first site on the gatsbyjs.org showcase that I found had YouTube embeds.

1. Navigate to justdoit.nike.com
2. Select a video
3. Press play on YouTube embed
4. Note the issue

### Expected result

Video should play.

### Actual result

Video shows loading spinner then does not play

**Comment by pieh** [comment]
This is pretty difficult to diagnose without seeing how those are actually embedded. I'm also not sure if this is Gatsby issue or issue in react components used to embed Youtube video?

**Comment by tylermcrobert** [comment]
https://codesandbox.io/s/lprmr2xjml?fontsize=14 Here is an example. In this case, just using default embed code and no video component

**Comment by pieh** [comment]
Hmm, I don't have iOS device, but checked on browserstack and both reproduction and nike site have no problems for me :(

**Comment by tylermcrobert** [comment]
Interesting. I had a few colleagues test and a few were having the problem, but most were not. Pretty tough to debug
