### ISSUE TITLE
gatsby-source-graphql creating slug for pages 

### ISSUE THREAD

**Issue by violabg** [gatsbyjs/gatsby#14030]
I'm sourcing data from drupal, can't use the gatsby-source-drupal plugin, because I need to localise the content, and it seams it is not supported. 
So I installed drupal GraphQL module and sourcing data with gatsby-source-graphql.
I'm able to query data, but can't find a way to create a slug onCreateNode.

with gatsby-source-drupal I was able to generate it like this:

```js
exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions
  if (node.internal.type === `node__work`) {
    const title = changeCase.paramCase(node.title)
    const slug = `/works/${title}/`
    console.log("/n slug ", slug)
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }
}
```

but with gatsby-source-graphql I don't have any relative information on the onCreateNode method.

**Comment by pieh** [comment]
Node aren't created when `gatsby-source-graphql` is being used, so `onCreateNode` method won't really work here.

You could add `slug` field to data from drupal graphql using something like this in your `gatsby-node` file:

```js
exports.createResolvers = ({ createResolvers }) => {
  createResolvers({
    TypeNameInGraphql: {
      slug: {
        type: `string`,
        resolve: object => {
          const title = changeCase.paramCase(object.title)
          return `/works/${title}`
        }
      },
    },
  })
}
```

Type will probably be something like `Drupal_Work` (depends on how you setup `gatsby-source-graphql` + what's the base type name in Drupal graphql schema). You can get actual name from `___graphql` if you click through Docs section.

**Comment by violabg** [comment]
Thanks it works!

If I query all nodes ora node by Id I get my node with the "slug" field, but I can't filter by slug

```js
{
  media {
    nodeQuery(filter: {conditions: [
    {operator: EQUAL, field: "type", value: ["work"]},
    {operator: EQUAL, field: "slug", value: ["/works/work-title"]}
  ]}) {
      entities {
        ... on MEDIA_NodeWork {
          nid
          title
          slug
        }
      }
    }
  }
}
```

**Comment by wardpeet** [comment]
Anything else works, fine? just slug?

**Comment by freiksenet** [comment]
Unfortunately you can't filter by fields created with `createResolvers`, as they are created last in schema generation step, so those filters won't work for them. If using gatsby-source-graphql, the only way to fix this atm is to have slug inside your Drupal schema.

**Comment by violabg** [comment]
> Anything else works, fine? just slug?

Yes I can filter by all other field

**Comment by violabg** [comment]
I was looking at https://www.gatsbyjs.org/docs/node-apis/#createResolvers

```js
exports.createResolvers = ({ createResolvers }) => {
  const resolvers = {
    Author: {
      fullName: {
        resolve: (source, args, context, info) => {
          return source.firstName + source.lastName
        }
      },
    },
    Query: {
      allRecentPosts: {
        type: [`BlogPost`],
        resolve: (source, args, context, info) => {
          const posts = context.nodeModel.getAllNodes({ type: `BlogPost` })
          const recentPosts = posts.filter(
            post => post.publishedAt > Date.UTC(2018, 0, 1)
          )
          return recentPosts
        }
      }
    }
  }
  createResolvers(resolvers)
}
```

but I guess it doesn't work on fields created with createResolvers
