### ISSUE TITLE
Wrapping Root Component fails

### ISSUE THREAD

**Issue by wharri220** [gatsbyjs/gatsby#1403]
Hi,

I am new to gatsby and was attempting to add redux to a Gatsby site. According to this https://github.com/gatsbyjs/gatsby/releases/tag/v0.12.34

The syntax is as follows in gatsby-browser.js
```
exports.wrapRootComponent = Root => {
  return () => (
    <Provider store={store}>
      <Root />
    </Provider>
  );
};
```

However, this gives me an error: 
![image](https://user-images.githubusercontent.com/9452756/27974415-f0d81a18-632b-11e7-8d9c-871f3e5e8aa3.png)

After looking at the objects, I found that this worked:
```
exports.wrapRootComponent = Root => {
  return () => (
    <Provider store={store}>
      <Root.Root />
    </Provider>
  );
};
```

Is this a bug? Or do the given examples need to be updated?

**Comment by KyleAMathews** [comment]
The examples? Did you check out https://github.com/gatsbyjs/gatsby/tree/master/examples/redux?

**Comment by wharri220** [comment]
By examples I mean your comment on the commit that introduced the wrapRootComonent lifecycle method.

The redux example in the samples show the use of the replaceRouterComponent method. 

Is the wrapRootComponent method no longer considered a valid way of introducing redux?

**Comment by KyleAMathews** [comment]
Which version of gatsby are you using? We released a new major version yesterday so yes, if you're trying to use v0 example code with gatsby v1 (the new version) it'll fail. That's why I pointed you to the redux example site for v1.

**Comment by wharri220** [comment]
Yea, it looks like I'm using 1.0.0-beta.7. So I will upgrade and refactor. Thanks for the info!

**Comment by adekbadek** [comment]
in case sbd stumbled here as I did, the current link to the redux example is: https://github.com/gatsbyjs/gatsby/blob/master/examples/using-redux/gatsby-browser.js

**Comment by SaulNML** [comment]
https://github.com/gatsbyjs/gatsby/blob/master/examples/using-redux/gatsby-browser.js

This is great, but how do I do a lazy load of the store here?

**Comment by SaulNML** [comment]
I need to make something like this work: https://github.com/rt2zz/redux-persist/issues/126

**Comment by SaulNML** [comment]
I need to make something like this work: https://github.com/rt2zz/redux-persist/issues/126#issuecomment-320503234
