### ISSUE TITLE
[Help] Is there a way to have a buffer zone for lazy loading Images?

### ISSUE THREAD

**Issue by oriooctopus** [gatsbyjs/gatsby#14033]
In [google's guide](https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/) to lazy loading using the intersection observer, they say that you can establish a buffer zone that allows images to start loading well before you've actually scrolled to them\

```
let lazyImageObserver = new IntersectionObserver(function(entries, observer) {
  // Lazy loading image code goes here
}, {
  rootMargin: "0px 0px 256px 0px"
});
```

Since I know Gatsby uses the Intersection Observer API for their lazy loading of images, is there a way to do this with gatsby-image?

**Comment by pieh** [comment]
We currently are using hard-coded 200px margin zone in all directions ( https://github.com/gatsbyjs/gatsby/blob/1fe6f9d73d2bb531dbce72988d3cdf652f551c63/packages/gatsby-image/src/index.js#L65 ).

If this default doesn't work for You, you can always fork `gatsby-image` component (it's 1 file - https://github.com/gatsbyjs/gatsby/blob/1fe6f9d73d2bb531dbce72988d3cdf652f551c63/packages/gatsby-image/src/index.js#L65) and adjust rootMargin

**Comment by KyleAMathews** [comment]
If the 200px isn't enough, we could change it too. It was picked in a rather arbitrary way.

**Comment by oriooctopus** [comment]
@KyleAMathews @pieh Mind if I take a swing and put up a PR for this?

**Comment by KyleAMathews** [comment]
@oriooctopus what would you like to do?

**Comment by oriooctopus** [comment]
@KyleAMathews add an optional variable for rootMargin that defaults to 200px

**Comment by KyleAMathews** [comment]
We already rejected a PR doing that :-) https://github.com/gatsbyjs/gatsby/pull/13816#issuecomment-488831605

You can see that PR comments for context but we won't accept a PR like this. We would however appreciate some research showing what could be a more ideal setting.
