### ISSUE TITLE
Understanding Gatsby's error messages when proxying API requests

### ISSUE THREAD

**Issue by esharri2** [gatsbyjs/gatsby#14044]
## Summary

What exactly does it mean when Gatsby shows the following error in the shell:

```
error Error when trying to proxy request "/api/auth/signup" to "http://localhost:3001/api/auth/signup"
```

Is this just a basic error telling me that my server returned an error? Or is this the Gatsby proxy feature somehow failing? More details below!

## Relevant information

I have an Express API set up as a proxy on my Gatsby project. I am sending a POST request and expecting to get 422 status and Mongoose's validation error message when there is a data validation issue on the server. My API works as expected via Postman. 

However, when I make the same request via my Gatsby site, I am getting this message in the shell:

```
error Error when trying to proxy request "/api/auth/signup" to "http://localhost:3001/api/auth/signup"


  HTTPError: Response code 422 (Unprocessable Entity  )

  - index.js:423 EventEmitter.ee.on.res
    [client]/[gatsby]/[got]/index.js:423:24

  - index.js:189 Immediate.setImmediate [as _onImmed    iate]
    [client]/[gatsby]/[got]/index.js:189:8
```

And my client just gets a 500 Internal Server Error and no validation error message. **I need to get the 422 status and error message so I can properly handle the error on the client.**

### Environment (if relevant)

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Python27/python
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.4.3 => 2.4.3
    gatsby-cli: ^2.5.13 => 2.5.13
    gatsby-image: ^2.0.33 => 2.0.33
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.9 => 3.0.9
    gatsby-plugin-sharp: ^2.0.36 => 2.0.36
    gatsby-source-filesystem: ^2.0.24 => 2.0.24
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17

### File contents (if changed)

`gatsby-config.js`: 

```
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`
  },
  proxy: {
    prefix: "/api",
    url: "http://localhost:3001"
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`
      }
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png` // This path is relative to the root of the site.
      }
    }
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // 'gatsby-plugin-offline',
  ]
};

```

`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@esharri2 see if [this](https://www.gatsbyjs.org/docs/api-proxy/) helps solving your issue.

**Comment by esharri2** [comment]
Thanks @jonniebigodes. I didn't see anything there that addresses my issues. I have the basic setup working; I can make successful requests to my API. The issue I'm having is particular to how errors are coming back from the API.

**Comment by jonniebigodes** [comment]
@esharri2 can you share a [reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be looked at?

**Comment by Kevin-Hamilton** [comment]
Looks to me like the gatsby proxy is a pretty basic / naive implementation.  It doesn't know anything about handling or passing through errors.  I'm sure a pull request with better handling would be welcomed.

See:
https://github.com/gatsbyjs/gatsby/blob/842d9ce5a57d4154251001b4e47eb5053bc77642/packages/gatsby/src/commands/develop.js#L214-L221
and
https://www.npmjs.com/package/got#onerror-error-body-response

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @esharri2 and for the details @Kevin-Hamilton 

We'd love to accept a PR with improved error handling in this case!

**Comment by esharri2** [comment]
Thanks @Kevin-Hamilton. So you're read on this is that any time my server returns an error of any kind, I'll just get that blanket 500 error?

**Comment by esharri2** [comment]
Still looking for time to work on this more, but just wanted to note the PR + issue that introduced this approach to handling errors: https://github.com/gatsbyjs/gatsby/pull/9839
