### ISSUE TITLE
[docs] add articles on winning over stakeholders 

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14040]
## Summary

There are a few stubs in the docs section on [Using Gatsby Professionally](https://www.gatsbyjs.org/docs/using-gatsby-professionally/) > [Winning Over Different Stakeholders](https://www.gatsbyjs.org/docs/winning-over-stakeholders/) that have some content on them, but need to be filled out further. This issue exists as a place to discuss ideas and collect information that could go on those pages. It can be closed when all the pages have been filled in enough to no longer be listed as stubs. Contributions are welcome!

 - [x] [Winning over Developers](https://www.gatsbyjs.org/docs/winning-over-developers/)
 - [x] [Winning over Engineering Leaders](https://www.gatsbyjs.org/docs/winning-over-engineering-leaders/)
 - [x] [Winning over Executives](https://www.gatsbyjs.org/docs/winning-over-executives/)

## Content ideas
- There may be some gems in Jim Ettig's blog post on sales and talking to developers, either in this section on Executives or in the Developers section: https://www.gatsbyjs.org/blog/2019-04-12-linear-or-declining-sales-talk-to-developers/
- There are also probably some ideas in Linda Watkins' post on talking to clients: https://www.gatsbyjs.org/blog/2019-03-07-sell-gatsby-to-clients/

You can also refer to the up-to-date stub list for ideas on how to help with docs: https://www.gatsbyjs.org/contributing/stub-list/

**Comment by GregBorrelly** [comment]
I can help with this.

**Comment by prestonso** [comment]
Also see #14061 for upcoming content about championing Gatsby in the enterprise (e.g. marketing executives, engineering executives, enterprise architects).

**Comment by GregBorrelly** [comment]
thank you @prestonso, I'll start writing

**Comment by caitlinthefirst** [comment]
Assuming this still needs addressing, I can draft content to replace these stubs. At this point there's more than enough blog/video content that I can pull from; but if there are any other particular pieces anyone wants to suggest for reference material, let me know

**Comment by marcysutton** [comment]
@caitlinthefirst that would be amazing! How's it going with writing @GregBorrelly, do you need any help?

**Comment by chawdamrunal** [comment]
I can pull from; but if there are any other particular pieces anyone wants to suggest for reference material, let me know

**Comment by caitlinthefirst** [comment]
Just a heads up, @chawdamrunal – I've almost finished my draft of the page on engineering leaders, and was planning to post the executive page by Monday. You're welcome take a crack at it yourself, of course.

**Comment by marcysutton** [comment]
To reduce confusion, I've assigned this issue to you @caitlinthefirst, since you seem to have this one covered! Thanks again for your work on it. We really appreciate it!

**Comment by connorlindsey** [comment]
Hi, I noticed this is still a stub and was wondering if the team would like help with it? I was planning on writing a bit about how Gatsby can benefit businesses and other clients and felt like that could be helpful here.
