### ISSUE TITLE
Plugins don't inject their scripts in the page if I'm overriding html.js

### ISSUE THREAD

**Issue by linuz90** [gatsbyjs/gatsby#14048]
## Summary

Hello. I'm building a website and I'm overriding html.js, which looks like this:

```javascript
import React from "react";
import PropTypes from "prop-types";

export default function HTML(props) {
  return (
    <html {...props.htmlAttributes}>
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <script src="https://cdn.paddle.com/paddle/paddle.js" />
        {props.headComponents}
      </head>
      <body {...props.bodyAttributes}>
        {props.preBodyComponents}
        <noscript key="noscript" id="gatsby-noscript">
          This app works best with JavaScript enabled.
        </noscript>
        <div
          key={`body`}
          id="___gatsby"
          dangerouslySetInnerHTML={{ __html: props.body }}
        />
        {props.postBodyComponents}
      </body>
    </html>
  );
}

HTML.propTypes = {
  htmlAttributes: PropTypes.object,
  headComponents: PropTypes.array,
  bodyAttributes: PropTypes.object,
  preBodyComponents: PropTypes.array,
  body: PropTypes.string,
  postBodyComponents: PropTypes.array
};
```

Now the problem is that plugins like **gatsby-plugin-facebook-pixel** and **gatsby-plugin-google-analytics**, even if set up correctly in `gatsby-config.js`, are not injecting their scripts in the page. They're nowhere to be found.

Any idea how to fix this?

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.157
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.16 => 2.3.16 
    gatsby-image: ^2.0.37 => 2.0.37 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-feed: ^2.1.1 => 2.1.1 
    gatsby-plugin-manifest: ^2.0.28 => 2.0.28 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-remark-copy-linked-files: ^2.0.11 => 2.0.11 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-images: ^3.0.10 => 3.0.10 
    gatsby-source-filesystem: ^2.0.29 => 2.0.29 
    gatsby-transformer-remark: ^2.3.8 => 2.3.8 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.5.9

### File contents (if changed)

`gatsby-config.js`:

```javascript
...
{
  resolve: "gatsby-plugin-facebook-pixel",
  options: {
    pixelId: "..."
  }
},
{
  resolve: "gatsby-plugin-google-analytics",
  options: {
    trackingId: "UA-...."
  }
}
...
```

**Comment by freiksenet** [comment]
Are you testing this in production? Those scripts don't inject anything in development. Try checking if they are there with `gatsby build`
