### ISSUE TITLE
How to Test Javascript Disabled?

### ISSUE THREAD

**Issue by cameronmcefee** [gatsbyjs/gatsby#14058]
How can I test how Gatsby performs with Javascript disabled, in local development? In [this comment](https://github.com/gatsbyjs/gatsby/issues/9626#issuecomment-435605109), the suggestion is to disable the Javascript preference to ensure service workers are also disabled. This works in production, but does not work when running gatsby in dev mode.

Thanks for your help.

**Comment by lannonbr** [comment]
So this is all dependent on your web browser you are using.

## Chrome

On Google's Web Fundamentals site, they have a page describing how to [Turn off JS in Chrome's Dev Tools](https://developers.google.com/web/tools/chrome-devtools/javascript/disable)

## Firefox

There's a Firefox extension convienently called [Disable JavaScript](https://addons.mozilla.org/en-US/firefox/addon/disable-javascript/)

## Safari

If you open the preferences menu, go to Security and you can uncheck the `Enable JavaScript` checkbox.

![Screen Shot 2019-05-15 at 10 33 41 PM](https://user-images.githubusercontent.com/3685876/57822456-98c39b80-7761-11e9-8327-b5a08680792b.png)

Hope this solved your question

**Comment by cameronmcefee** [comment]
Unfortunately, no. I understand how to disable Javascript, and that works when our site is deployed. However, if I'm running the site locally and do this, this is all I see:

<img width="777" alt="Screen Shot 2019-05-15 at 8 17 12 PM" src="https://user-images.githubusercontent.com/72919/57824043-90159a00-774e-11e9-9fbc-93038da6448c.png">

The markup is just a noscript tag.

**Comment by DSchau** [comment]
@cameronmcefee SSR is a build-time optimization, not a develop-time optimization.

In other words, we don't statically render to HTML at _develop time_ because it's extra overhead and a slower experience that a user wouldn't generally need. If you want to test the non-JS experience, you can use:

```shell
gatsby build
gatsby serve
```

and open up localhost:9000.

Hope this helps, going to close as answered; thanks!

**Comment by cameronmcefee** [comment]
Ah, that makes sense. I appreciate the explanation.

**Comment by BryanBarrera** [comment]
@DSchau - Your response was extremely helpful

`gatsby build`
`gatsby serve`

Worked for me.
