### ISSUE TITLE
Gatsby SSR Not working (Redux and @react/router)

### ISSUE THREAD

**Issue by NavaneethaKrishnanP** [gatsbyjs/gatsby#14054]
Tried with Gatsby SSR using Redux and @reach/router, in a project which contains many pages that are displayed with the data got from backend apis. The data is displayed fine in gatsby development mode, but the data is not populating with the html tags when doing view page source of the page from browser (after gatsby build ) - related to server side rendering.

 routes defined using  @reach/router

Defined Routes -- Root.js
```js
import { Router, Link } from "@reach/router"

const Root = ({ store }) => (  
 `<Router>
        <Home path="/" history={history} /> 
        <AuthenticatePage path="authenticate/:toUrl" />
        <ProductPage path='/:productName/:seoUrl'/>
        <CartPage path="cart"/>
   </Router>` 
)


export default Root;
```

Wrapped the Routes inside Provider of react-redux

gatsby-ssr.js

```js
import React from 'react';
import { JssProvider } from 'react-jss';
import { SheetsRegistry } from 'jss';
import getPageContext from './src/getPageContext';
import configureStore,{history} from './src/store';

//import Layout from './src/layout';
import Root from './src/Root';
import {Provider} from 'react-redux';
//const store = configureStore()
import store from './src/store';
import Home from './src/pages/home';

let sheets = new SheetsRegistry();

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <style
      type="text/css"
      id="server-side-jss"
      key="server-side-jss"
      dangerouslySetInnerHTML={{ __html: sheets.toString() }}
    />,
  ]);

  // Re-instantiate sheets, so that it isn't reused:
  sheets = new SheetsRegistry();
}

// eslint-disable-next-line react/prop-types
export function wrapRootElement({ element }) {
  // Get the context of the page to collected side effects.
  //const muiPageContext = getPageContext();

  // The standard class name generator.
  //const generateClassName = createGenerateClassName();

  return (
    `<Provider store={store}>
        <Root/>
      </Provider>`
  );
}
```

**Comment by freiksenet** [comment]
Thank you for the report, I've fixed the formatting so it's easier to read.

Are backticks around Root component Router intentional or just an accident from formatting?

**Comment by m-allanson** [comment]
Hey @NavaneethaKrishnanP could you create a reproduction for this? https://gatsby.dev/reproduction 

Alternatively check out the docs on creating pages in Gatsby, typically for SSR you'll need to use Gatsby's createPages API rather than using Reach Router directly. Check out [the docs on routing](https://www.gatsbyjs.org/docs/routing/) and this guide to [programatically creating pages from data](https://www.gatsbyjs.org/docs/programmatically-create-pages-from-data/)
