### ISSUE TITLE
CLI argument passthrough

### ISSUE THREAD

**Issue by lexaurin** [gatsbyjs/gatsby#14050]
## Summary
[Feature Request]

It would be nice to support CLI argument passthrough to be able to customize build by argument switches.

### Basic example

```
# gatsby.config.js
const argv = require("minimist")(process.argv.slice(2));

module.exports = {
  proxy: {
    prefix: "/graphql",
    url: argv.mock ? MOCK_SERVER_URL : SERVER_URL,
  },
```

```
yarn start -- --mock
```

Related #9935

**Comment by wardpeet** [comment]
I don't see much value over environment values. I also don't know if yargs support it, it's the cli helper we use.

If more people need this we might consider it but I don't think at this point we will
