### ISSUE TITLE
Can not get wp user information of my live site

### ISSUE THREAD

**Issue by anamwp** [gatsbyjs/gatsby#14055]
While I made this query of my live site it give me error. 
I am using `gatsby-source-wordpress` plugin to pull wordpress data
```
{
  allWordpressPost {
    edges {
      node {
        id
        slug
        title
        content
        excerpt
        date
        modified
        author {
          id
          name
          description
        }
      }
    }
  }
}
```
Its says "message": "Field \"author\" must not have a selection since type \"Int\" has no subfields."
But when I try to fetch local data then it works fine.  
Any help appreciated. 
Thanks.

**Comment by pieh** [comment]
can you use `verboseOutput: true` in wordpress plugin configuration and see if there are any errors when fetching data? It's possible that wordpress won't return list of users/authors if unauthorized requests are being made

**Comment by anamwp** [comment]
Yes. I use .  When I run `gatsby develop` then it build properly. But it graphql it display only user Id . Nothing else.

**Comment by anamwp** [comment]
One more thing is when I run `gatsby develop`
I got 
`Path: /wp-json/wp/v2/users?per_page=100&page=1
The server response was "403 Forbidden"
Fetching the wordpress__wp_users took: 7288.589ms`
this message inside build log. 
But I manually get single user information through browser like `/wp-json/wp/v2/users/40` 
This message does not show while I fetch data from my local wordpress site. 
It shows in live site only. 
Any solution ?

**Comment by orshick** [comment]
Is your site hosted on wordpress.com? Sounds like you're having the same issue as  #13983

**Comment by anamwp** [comment]
Nope. I got the issue. It was my server issue. 
My server does not let me fetch the  users data while wp source plugin try to fetch. 
I update my server security issue and now it fixed. 
Thanks.
