### ISSUE TITLE
Add typing support for gatsby-source-drupal

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#14063]
Drupal and Gatsby are commonly used together.

One problem (as faced by other source plugins) is that due to the GraphQL schema being inferred, sometimes fields that are defined in content types on Drupal, don't get created on Gatsby's side as there might not be any Drupal entities with data for that content.

Ideally we would leverage the new schema tooling recently added to Gatsby to directly set types.

One approach suggested by @mrjmd is for people to add https://www.drupal.org/project/openapi which provides a JSON description of Drupal's types. This would be an optional addon (though strongly encouraged) so the source plugin could check if it can download the file and use it if it's found.

**Comment by e0ipso** [comment]
@KyleAMathews I think that is a great idea. However bear in mind that the modules that power that feature are not :100: stable.

The heart of the schema generation is the Schemata module, which generates the JSON Schema for the JSON:API responses. The other part is the OpenAPI module, which leverages the _data model schema_ and produces an Open API document.

I recommend you to apply the same patches we have in Contenta CMS for the Open API module. https://github.com/contentacms/contenta_jsonapi/blob/8.x-3.x/composer.json#L38-L43

**Comment by e0ipso** [comment]
I also had this issue when working with ContentaJS (a node.js proxy for Contenta CMS/Drupal). This was the solution: https://git.drupalcode.org/project/contentajs/blob/8.x-1.x/src/Plugin/jsonrpc/Method/JsonApiMetadata.php
