### ISSUE TITLE
Links to static remain unprefixed even with --prefix-paths flag enabled - clone of #8479

### ISSUE THREAD

**Issue by jonnybot0** [gatsbyjs/gatsby#14067]
## Description

Discovered this one the hard way tonight - it looks like pathPrefix is not honored for links to files in the static directory as of v2.0.6.

NOTE (this is a clone of https://github.com/gatsbyjs/gatsby/issues/8479, which was closed as "could not reproduce" some time ago, but can be reproduced now)

### Steps to reproduce

Follow the steps in the README.md file at https://github.com/jonnybot0/gatsby-static-image-bug-demo

The package.json scripts assume an OSX/Linux/Unix shell of some kind, but you can probably reverse engineer what needs to happen for them to work on Windows.

### Expected result

Images served from the static folder should be prefixed.

### Actual result

Images served from the static folder are not prefixed, and thus appear broken if your site is deployed to a subpath.

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 4.4.23 - /usr/local/bin/bash
  Binaries:
    Node: 8.11.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.27
    Firefox: 66.0.5
    Safari: 12.1.1

**Comment by m-allanson** [comment]
Thanks for the repro @jonnybot0, I can confirm I'm seeing the same issue. Updating to the l latest dependencies doesn't fix it. I haven't had a chance to dig further yet, but I wonder if this is specific to `gatsby-mdx`? If you get the chance could you try replicating the problem using plain markdown? 

There's a [`using-remark` example site](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-remark) that might make a good starting point.

**Comment by jonnybot0** [comment]
I'll be honest, I'm not really using Gatsby now. I'd like to try to repro with the other example site, but I'm not gonna get it done in the next 10 days. Best of luck!

**Comment by rochabianca** [comment]
Hi, I'm using normal md on my website, but still facing the same problem

gatsby version: 2.13.82
