### ISSUE TITLE
[BUG]: gatsby-image cache key is not reliable if viewport resizes

### ISSUE THREAD

**Issue by polarathene** [gatsbyjs/gatsby#14073]
## Description

`gatsby-image` has a run-time cache that is separate from the browsers own image cache. This cache tracks what images are loaded by assigning their `src` value in the fluid/fixed metadata as their cache key for lookup. 

This key is always the same despite multiple `src` values an image can represent(sizes and formats, and in future - [variants](https://github.com/gatsbyjs/gatsby/pull/13395)). This is a non-issue provided the viewport is not resized (browser window, or on mobile when splitting the display area to accomodate another app, or an orientation change).

Presently, at least with Chrome, resizing the viewport only changes the image source when the viewport grows and a better source is available for a given size(`w` in srcSet in combination with the `sizes` attribute). This updates the `src`, if you were to copy the image address, but retains the current image loaded in until the new one is ready to replace. 

However, if you have since navigated to a different page which unmounted the image, resize the viewport and visit that page again, the image is freshly mounted but it's cache key now returns `true`, thus lazy loading and any transition effect is disabled.

When `gatsby-image` supports image variants via the Art Direction PR, this bug will be further impacted when a viewport shrinks if it triggers a media condition for a source variant.

### Steps to reproduce

Load a page with a small viewport, navigate to another page on the site and grow the viewport to a size that would select a different image file source for the same image, visit that page again.

The image cache key will be the same. The image will download regardless of distance from viewport, there will be no transition effect despite no browser image cache hit.

### Expected result

An image should still retain it's ability to lazy-load and use it's transition style if it's source has changed due to a viewport resize.

### Actual result

The image's cache key is unique to it's resource but does not take the selected source into account. This triggers queries for the cache key used by logic such as `seenBefore`, `wasCached` and `imgLoaded` to behave incorrectly when the viewport is resized.

### Details

`inImageCache` method with the current PR would assign the first variant supplied as the run-time/instance cache key(different from actual browser image cache). This should generally be ok, but would be invalid if the image changes due to a browser resize.

`seenBefore` takes that value when adding an image to the page. When true, lazy-load will be skipped, as will any fade transition. This is unaffected by a screen resize, but I believe the run-time cache persists across navigation? In which case, if the viewport was later resized to trigger a different source, and the resource is mounted again, this could cause undesirable UX, more so if there were multiple instances of that image(less likely with art directed images?. Another scenario would be dynamically adding the image to the same page after the initial load.

`inImageCache` also impacts logic in `componentDidMount()` and `handleRef(ref)`, a load event method is triggered in both that provides info if the asset was cached. It's not used by the actual component, but as a hook for a developer to utilize.

`handleImageLoaded()` is where the actual key is created. This may apply to the existing `gatsby-image` code too, but I don't think the browser will switch source unless a media query/attribute is present? Thus the image currently only changes when mounted again which would also run into this issue.

### Resolution

There's not much that can be done here? The key will be queried before the browser has been able to assign an appropriate source.

The default `srcset` does provide `w`/`x` values that could be potentially parsed and matched by JS querying the viewport/window, although for `w` sources, this would also need to take `sizes` attribute into account? Further complicated when `media` is also part of source selection for art direction. Image format is a non-issue as that shouldn't change and we don't need the URL just an appropriate key to distinguish a different source.

Browsers may behave differently with source selection afaik, I have read that they can select a more appropriate source based on conditions such as network type/quality in use.

With `gatsby-image` now having a proper browser image cache in place, where is this run-time cache useful? `seenBefore` appears to opt out of lazy-loading (how much of a benefit is that?) and disable fadeIn, which the browser cache support covers too iirc. That leaves `wasCached` for those using it with an `onStartLoad` event.

**Comment by polarathene** [comment]
Disable cache when attempting to reproduce. If the higher resolution image is available in the image cache, and you shrink the viewport to refresh where a smaller image would be retrieved, that higher quality image is used instead(by Chrome at least).

**Comment by KyleAMathews** [comment]
This seems like a really small edge case? Very few people resize their browser and the only thing bad that happens is that people see a normal image load instead of our nice placeholder and fade in.

We'd have to add extra code to handle this.

It'd be nice if browsers gave you an api to parse srcset like they do.

**Comment by polarathene** [comment]
> Very few people resize their browser

On a desktop most common would be maximize or snap resizing to half/quarter of screen.

On mobile, orientation change or adding/removing a separate app to share the screen space. 
Orientation wouldn't be too uncommon when viewing certain media like video content.

> the only thing bad that happens is that people see a normal image load instead of our nice placeholder and fade in.

If that's not a problem, then the issue can be closed. I just noticed this behaviour when reviewing the Art Direction PR, which is more likely to encounter it, no idea how that works for offline PWA experience when image variants are involved.

> We'd have to add extra code to handle this.

Yep? Just like we did for avoiding transition when the image was in the browser cache to avoid the minor issue of a transition appearing.

This bug isn't breaking anything, it's not that important to fix without others chiming in that it's a problem for them.

---

Do you want to close this issue then? Or just leave it open as low priority? It's not likely something you'd see handled outside of Gatsby often either I imagine. If browser has native lazy-load support, then the image should still be lazy-loaded

**Comment by KyleAMathews** [comment]
yeah, I don't think this is something we need to worry about. It's very niche and not something that's easy to solve without loading a library that can parse image's srcsets and do something about that. Though tbh, we might [want to do that eventually for other reasons](https://github.com/gatsbyjs/rfcs/pull/35) in which case we could possibly revisit this.

If issues are so low priority that we're not planning to do anything, we prefer to close them. So I'll do that :-D

Thank you for your writeup and all your help on the art direction PR!
