### ISSUE TITLE
[Gatsby-source-shopify] - Product in collections are limited to 250

### ISSUE THREAD

**Issue by federicobadini** [gatsbyjs/gatsby#14079]
## Description

Gatsby-source-shopify - Products in collections gets truncated at 250

### Steps to reproduce

Try to fetch a shopify collection with more than 250 products 

### Expected result

I have inspected the library code and I agree on almost every default that has been set. It's really uncommon to have for instance more than 250 photos for a product. 
However it is very common to have much more than 250 products in a collection. As a consequence I expected this lib to iterate in order to fetch all products in each collection.

Without this feature you do not have any possibility to retrieve the product of a collection sorted by best selling for instance. 

### Actual result

Products get truncated at 250

### Environment

  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 66.0.3
    Safari: 12.0.2
  npmPackages:
    gatsby: 2.4.2 => 2.4.2 
    gatsby-image: 2.0.30 => 2.0.30 
    gatsby-plugin-layout: 1.0.15 => 1.0.15 
    gatsby-plugin-manifest: 2.0.20 => 2.0.20 
    gatsby-plugin-offline: 2.1.0 => 2.1.0 
    gatsby-plugin-react-helmet: 3.0.7 => 3.0.7 
    gatsby-plugin-remove-console: 0.0.2 => 0.0.2 
    gatsby-plugin-sharp: 2.0.23 => 2.0.23 
    gatsby-plugin-sitemap: 2.1.0 => 2.1.0 
    gatsby-plugin-styled-components: 3.0.6 => 3.0.6 
    gatsby-plugin-typescript: 2.0.10 => 2.0.10 
    gatsby-plugin-web-font-loader: 1.0.4 => 1.0.4 
    gatsby-source-datocms: 2.1.4 => 2.1.4 
    gatsby-source-graphql: 2.0.18 => 2.0.18 
    gatsby-source-shopify: 2.0.28 => 2.0.28 
    gatsby-transformer-remark: 2.3.12 => 2.3.12 
    gatsby-transformer-sharp: 2.1.18 => 2.1.18

**Comment by m-allanson** [comment]
This sounds like a pretty reasonable feature request! I've labelled it up as help wanted. Would you have the chance to open a PR?
