### ISSUE TITLE
Transformer plugin option for limiting transforms to specific nodes

### ISSUE THREAD

**Issue by sbardian** [gatsbyjs/gatsby#14081]
## Summary

See closed PR #11940 for the discussion on this issue.  

This started as a PR to add the plugin option to the `gatsby-transformer-json` plugin, but should probably be a global/gatsby core plugin option for all transformer plugins. 

### Basic example 
NOTE: `this example is from the PR when it was being applied to just the gatsby-transformer-json plugin.  I'm not sure what a global/gatsby core plugin option API would look like. `

#### Usage
```javascript
module.exports = {
  plugins: [
    {
      resolve: `gatsby-transformer-json`,
      options: {
        plugins: [`gatsby-source-filesystem`],
      },
    },
  ],
}
```

#### Implementation
```
  const { plugins } = pluginOptions

  if (plugins && plugins.length > 0 && !plugins.includes(node.internal.owner)) {
    return
  }
```

### Motivation

Transformer plugins sometimes run on nodes that don't need to be transformed.  This would be a performance improvement and limit the amount of unused types and queries polluting your schema when using transformer plugins.

**Comment by m-allanson** [comment]
@pieh or @wardpeet do you have any thoughts on how the API for this might look?

**Comment by sbardian** [comment]
I have been digging around to see if I could find where we might catch this as a global API/pluginOption.  If we keep the same plugin option mentioned above, couldn't we add a check here (https://github.com/gatsbyjs/gatsby/blob/bf042a04d95b33ee0d2e4675181587f890b72240/packages/gatsby/src/db/nodes.js#L43) pulling out the `plugin.pluginOptions.plugins` as above from the `const plugin` on line 34, and check it against the `node.internal.owner` after the `!loadNodeContent` check?  Might be totally off point here, but thought I would throw it out.  May try some tests on this later tonight.  Figured I would get your thoughts.
