### ISSUE TITLE
accept multiple url variants for graphiql IDE

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#14084]
## Summary

In usability tests, we discovered that when people type the wrong thing in the browser (e.g. “localhost:8000/_ _ graphiql), we could either redirect to "correct" one or just support multiple different cases. This will help them spend less time looking for the right link.

### Basic example
I'm not sure what the best practice is here. Here are some ideas:

Support various number of underscores before graphiql e.g. _graphiql (1 underscore), __graphiql (2 underscores), ___graphiql (3 underscores), ____graphiql (4 underscores)
Support "graphql" and "graphiql"
Other ideas?

### Motivation

We observed that many users (including ourselves!) say "how many  underscores is this again? I can never remember" and "I always misspell Graphiql. How do you even say Graphiql??" haha.

**Comment by pieh** [comment]
Some tips on how to implement this:
We need to update https://github.com/gatsbyjs/gatsby/blob/0b565765a8291f1525e86f17e1d8bedc774a7782/packages/gatsby/src/commands/develop.js#L126-L153

to handle variants mentioned by Shannon in basic example.

To do this we can update paths that our endpoint handle. Express server allow to use path patterns or regular expressions ( https://expressjs.com/en/api.html#path-examples ) and I think those will work here very nicely.

It would be very nice (but not strictly needed) if there were also cypress tests for this in https://github.com/gatsbyjs/gatsby/tree/master/e2e-tests/development-runtime/cypress/integration to make sure that visiting those paths result in viewing graphiql interface

**Comment by thomascorthouts** [comment]
@pieh Can I pick this one?

**Comment by thomascorthouts** [comment]
@pieh I have a small question regarding code structuring. I changed the endpoints so they use the express patterns to match everything with at least 1 underscore and match both on `graphql` and `graphiql`. So the pattern you get is `/_+graphi{0,1}ql` 

But now I would be interested in creating cypress tests for this as well, where I test whether the patterns give the graphqlIDE for both the basic develop runtime as well as the runtime with `GATSBY_GRAPHQL_IDE=playground`, but I don't really see where the best spot would be to put these tests. Should this be a file like `cypress/integration/functionality/graphql-endpoint.js` or what would be the best place to put this?

**Comment by pieh** [comment]
Ah, sorry I didn't reply, but I see you managed. The place for e2e tests is not clear, but one you picked seems very reasonable here
