### ISSUE TITLE
Gatsby is serving js instead of html

### ISSUE THREAD

**Issue by jrusso1020** [gatsbyjs/gatsby#14098]
## Description

I'm not seeing my page's html when I view the source code of my website in development or after building the static files and serving it locally. I can see the `.html` files in the public directory and in there they look fine. But when I actually visit the pages it doesn't look like it's using those `.html` files.

I've seen posts https://github.com/gatsbyjs/gatsby/issues/13611 and https://github.com/gatsbyjs/gatsby/issues/10322 and when I curl my page it looks fine, but does anyone know why when I try to view the source it's not viewable?

### Steps to reproduce

https://github.com/jrusso1020/anakin here is a link to my repo

Run `gatsby develop` or `gatsby build && gatsby serve` and view the page source

### Expected result
I should see my pages source code in the html when I view it in the browser.

It should look something like this on the homepage
```
<body><noscript id="gatsby-noscript">This app works best with JavaScript enabled.</noscript><div id="___gatsby"><div style="outline:none" tabindex="-1" role="group"><div><div class="navbar__Container-sc-1q8ki5q-0 coDZPa"><div class="sidebar__Container-sc-46ilx5-0 vUVwu"><div class="bio__Container-s89brg-0 jdBHc"><div class="bio__ImageContainer-s89brg-1 jSPVxc"><div class="bio__StyledImage-s89brg-2 kWEZcb gatsby-image-wrapper" style="position:relative;overflow:hidden;display:inline-block;width:100px;height:100px">
...
```
### Actual result

I do not see anything in the html that looks like the current page.

```
body><noscript id="gatsby-noscript">This app works best with JavaScript enabled.</noscript><div id="___gatsby"><div style="outline:none" tabindex="-1" role="group"></div></div>```

### Environment

 System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 3.5.2 - /Users/james/anaconda3/bin/python
  Browsers:
    Chrome: 74.0.3729.157
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.31 => 2.1.31 
    gatsby-image: ^2.0.33 => 2.0.33 
    gatsby-plugin-catch-links: ^2.0.13 => 2.0.13 
    gatsby-plugin-feed: ^2.0.15 => 2.0.15 
    gatsby-plugin-google-analytics: ^2.0.17 => 2.0.17 
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.9 => 3.0.9 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-s3: ^0.2.5 => 0.2.5 
    gatsby-plugin-sharp: ^2.0.28 => 2.0.28 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-typography: ^2.2.9 => 2.2.9 
    gatsby-remark-copy-linked-files: ^2.0.10 => 2.0.10 
    gatsby-remark-embed-gist: ^1.1.7 => 1.1.7 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-remark-prismjs: ^3.2.5 => 3.2.5 
    gatsby-remark-responsive-iframe: ^2.0.10 => 2.0.10 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.24 => 2.0.24 
    gatsby-transformer-remark: ^2.3.2 => 2.3.2 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby: 2.5.0

**Comment by LekoArts** [comment]
Hi, thanks for opening the issue!

> my website in development

The development build is not optimized and hence you won't see HTML there.

#10322 already mentioned why you're seeing this behavior and it was since then also added to the README 👍 
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-offline#empty-view-source-and-seo

Closing as answered :)
