### ISSUE TITLE
[themes] Write a happy path for first-time developers: use themes to set up a blog with MDX

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#14094]
As part of getting themes to a stable launch, we need to write a tutorial showing how to use Gatsby with themes.

## Proposed table of contents

- [ ] Create a new blog with the Gatsby CLI
- [ ] Install `gatsby-theme-blog` (blocked on finishing @amberleyromo’s darklight theme)
- [ ] Write a blog post
- [ ] Use component shadowing to override design tokens
- [ ] Create a custom component and use it in a blog post

Tagging @ChristopherBiscardi @johno @jxnblk @marcysutton for feedback on the ToC.

**Comment by ChristopherBiscardi** [comment]
Can we add the notes theme in here too to show composition? or is that too much.

**Comment by jlengstorf** [comment]
@ChristopherBiscardi I think composition would be perfect for a "part 2" of this tutorial — @marcysutton's work in #14071 lays a solid foundation for making the happy path part of the "fundamentals", with composition being an intermediate tutorial.

If you feel like composition is fundamental, we can definitely pull it back into part one, though.

**Comment by amberleyromo** [comment]
Closed with [using a theme docs guide](https://www.gatsbyjs.org/docs/themes/using-a-gatsby-theme) and [using a theme tutorial](https://www.gatsbyjs.org/tutorial/using-a-theme).
