### ISSUE TITLE
[bug] [www] gatsbyjs.org links do not have correct destination on LinkedIn social share

### ISSUE THREAD

**Issue by prestonso** [gatsbyjs/gatsby#14093]
This is a bug that impacts all gatsbyjs.org links that are shared on the LinkedIn social network.

## Description

When gatsbyjs.org links are posted on LinkedIn for sharing, only "How Gatsby works" — the title of the home page — appears, and when a miniature preview is clicked on a published LinkedIn post, it leads to the gatsbyjs.org home page.

### Steps to reproduce

1. Share any gatsbyjs.org URL that is not the home page to a post on LinkedIn.
2. Note that the miniature preview points to "How Gatsby works" — the home page — and not the desired link.
3. Note that after the post is published, the link still points to the home page.

### Expected result

The link should work correctly on LinkedIn social share and not lead to the gatsbyjs.org homepage.

### Actual result

<img width="553" alt="Screen Shot 2019-05-16 at 4 58 29 PM" src="https://user-images.githubusercontent.com/484252/57886946-5733fe80-77fc-11e9-89a3-f1abcb8ea020.png">

The link instead points to the gatsbyjs.org home page.

### Environment

Not relevant.

**Comment by KyleAMathews** [comment]
https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fwww.gatsbyjs.org%2Fblog%2F2019-05-15-enterprise-gatsby-how-to-reduce-your-digital-total-cost-of-ownership-with-gatsby%2F

**Comment by KyleAMathews** [comment]
It looks like it's reading the Canonical URL wrong which is odd as it's set correctly in the HTML
<img width="518" alt="Screenshot 2019-05-16 18 54 14" src="https://user-images.githubusercontent.com/71047/57898085-5f943580-780c-11e9-9ce3-f031746b8fd3.png">

**Comment by m-allanson** [comment]
Weird... I tried with a few other Gatsby sites and LinkedIn picks them up ok. Just gatsbyjs.org it doesn't like.

**Comment by prestonso** [comment]
Thanks @Jared-Dev!
