### ISSUE TITLE
[docs] Define custom MDX components needed for the docs

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#14095]
As soon as gatsbyjs/gatsby#14071 is merged, we’ll be able to add custom MDX shortcodes to improve the docs authoring experience and the readability of the docs.

@marcysutton is collecting requirements for what we need to create — this issue tracks that work and will eventually evolve into an umbrella issue tracking progress on the shortcodes.

**Comment by marcysutton** [comment]
The components were spec'd out in a separate doc: https://docs.google.com/document/d/1XYzToB-cNJ6Ot0ujdg5WaO5jmKH7moJ8305VwwwA2UY/edit#heading=h.nt3t0p9y6kx5

We need this project to be prioritized to move onto the next stage. Some of the components will be addressed with issues like #13475 and #6896, which I'll follow-up on, but as for the spec'ing part, I believe it is done and the issue can be closed.
