### ISSUE TITLE
Add ability to adjust gatsby-image lazy loading threshold

### ISSUE THREAD

**Issue by FraserThompson** [gatsbyjs/gatsby#14103]
## Summary

I would like to be able to change the "threshold" before an image is loaded. So instead of loading the image as soon as it enters the viewport, I'd like this to be configurable so more images are loaded.

### Motivation

I use gatsby-image in an image gallery which can have up to 60 or so photos, displayed in a single column on mobile.

Lazy loading is obviously essential to ensure all 60 aren't downloaded at once, but scrolling through the images isn't a nice experience when you have to wait a second or so for each image to load as soon as it enters the viewport. If we could configure the threshold to load more images before the user gets to them it would improve the experience for users.

**Comment by m-allanson** [comment]
Thanks for opening this @FraserThompson! There's been a few bits of discussion around this in the past. Check out the comments on this PR https://github.com/gatsbyjs/gatsby/pull/13816#issuecomment-488831605

To summarise the discussion there - we're moving towards letting the browser handle this natively and currently we don't want to add an option that makes the threshold configurable. However we _would_ be interested in seeing research that identifies a better default value - the current value is `200px`.

Do you have a link to your gallery? That might be a good example case where the existing threshold doesn't work well.

**Comment by FraserThompson** [comment]
Oh sorry, I did do a search but somehow missed that PR...

Here's the gallery I'm talking about: https://dunedinsound.com/gigs/primitive-man---dunedin/

It works okay on desktop but for a user scrolling through relatively quickly on mobile to get a good look at all the images the loading lags behind at some points.

**Comment by KyleAMathews** [comment]
Could you try upgrading the distance to e.g. 350px see how big of difference that makes?

**Comment by polarathene** [comment]
There are plans to [refactor `gatsby-image` functionality to be more composable](https://github.com/gatsbyjs/gatsby/issues/13353) for v3 of Gatsby. That will allow you to use the default, or alter/swap certain behaviour more easily for more niche needs. 

Presently, you could consider something like [react-waypoint](https://github.com/civiccc/react-waypoint), having it trigger `critical` / `loading="eager"` props to opt-out of lazy-load for n images?

> but for a user scrolling through relatively quickly on mobile to get a good look at all the images the loading lags behind at some points.

I don't think much can be done about that regarding scrolling quickly. All images prior will be still queued up to download, the browser may lower the priority to focus on those in/near the viewport though. You could consider a virtualized list component, that would remove the images further away from the view which should cancel the browser downloading them, allowing for the images in the users view and near it to be prioritized.
