### ISSUE TITLE
gatsby theme docs out of date

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#14107]
## Description

https://www.gatsbyjs.org/docs/themes/getting-started/ references https://github.com/gatsbyjs/gatsby-starter-blog-theme

this repo doesnt exist. i'm not sure what the correct one is.

**Comment by m-allanson** [comment]
Thanks @sw-yx! I think this should be pointing to the theme here: https://github.com/gatsbyjs/gatsby/tree/master/themes/gatsby-theme-blog

However the Gatsby cli needs a path to a repo, not a directory within a repo. For the official starters we automatically mirror them [from the gatsby monorepo](https://github.com/gatsbyjs/gatsby/tree/master/starters) to [their own repos](https://github.com/gatsbyjs) using [this script](https://github.com/gatsbyjs/gatsby/blob/master/scripts/clone-and-validate.sh). I guess we should do the same for themes.

cc @ChristopherBiscardi does that sound right to you? Happy to help with getting this going for themes if so.

**Comment by sw-yx** [comment]
i'll leave y'all to it. i know chris said y'all have some bigger rearchitecture of the theme docs coming or something. just wannted to address possible pain if it takes like 3 seconds to fix

**Comment by ChristopherBiscardi** [comment]
Yeah, the theme docs are not linked in the sidebar for a reason and it's that they are sorta beta-y state like this. We're working towards stable soon and that mostly means productionizing docs and supporting code like having the official themes up and running with a starter in the gatsby repo (like the current starters are).

> However the Gatsby cli needs a path to a repo, not a directory within a repo. 

We have an issue #14007 to change that, although for the official starters we won't use that functionality and we'll mirror out to a github repo instead, like you said @m-allanson. When we merge in the new official blog theme, we'll also set up the starter for that theme. I also need to hand `gastby-theme-blog` and `gatsby-theme-blog-core` over to the gatsby maintainership so they can be published out of the gatsby repo.
