### ISSUE TITLE
[docs] [workflows] Set up Gatsby Preview with Contentful

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#14100]
TODO: add the full workflow evaluation per #13708

**Comment by gillkyle** [comment]
Part of the **Top 25 Learning Workflows initiative**.

# User story

As a new Gatsby user, I want to learn how to integrate Gatsby Preview with Contentful.

# Evaluation

| Search | Discover | Complete | Linked | Tone | Style | Overall |
| --- | --- | --- | --- | --- | --- | --- |
| 😐 | 😄 | 😄 | 😄 | 😄 | 😄 | 😄 |

# Steps taken to implement

1. Searchability
	1. Searched `gatsby preview with contentful` on Google; clicked on first video [result](https://www.youtube.com/watch?v=RrQi6W_8SVQ); watched demo on using the two together
	2. Searched `gatsby preview with contentful` on Google; clicked on first site [result](https://www.gatsbyjs.org/blog/2019-03-22-introducing-gatsby-preview-beta/) [**rec**] Include a link to docs for integrating directly in this blog post and improve the page score/SEO of [the doc](https://www.gatsbyjs.com/docs/preview/getting-started-with-gatsby-preview-and-contentful/) at .com
2. Discoverability
	1. Searched `gatsby preview` in search bar; directed to [same blog post](https://www.gatsbyjs.org/blog/2019-03-22-introducing-gatsby-preview-beta/) as above
	2. Clickpath on .com (**3 clicks**):
		- clicked on profile dropdown
		- clicked on *Documentation*
		- clicked on *See how to get started with Gatsby Preview and Contentful*
3. Completeness
Followed steps in [docs](https://www.gatsbyjs.com/docs/preview/getting-started-with-gatsby-preview-and-contentful/)
	- Overall really thorough
    - ENV variables section was confusing with text not matching images and then compounded by a message about the section potentially being confusing
	- [**rec**] update image for ENV vars where text and image conflict, explain naming of env variables like `GATSBY_PREVIEW_ACCESS_TOKEN` and clarify what needs to be in each place
4. Linkedness
	- Contains many links to other useful docs (especially Contentful related ones)
5. Tone
	- 👍 
6. Style
    - 👍 

# Recommendations

- [ ] Include a link to docs for integrating directly in the Gatsby Preview announcement blog post
- [ ] Improve the page score/SEO of [the doc](https://www.gatsbyjs.com/docs/preview/getting-started-with-gatsby-preview-and-contentful/) at .com
- [ ] update image for ENV vars where text and image conflict, explain naming of env variables like `GATSBY_PREVIEW_ACCESS_TOKEN` and clarify what needs to be in each place
