### ISSUE TITLE
CSS/SCSS

### ISSUE THREAD

**Issue by lsguillory** [gatsbyjs/gatsby#14101]
## Description
Doing a Gatsby tutorial by Andrew Mead. After creating the index.css file, just showing how to style with Gatsby, the program through an error : Invalid CSS after "{": expected 1 selector or at-rule, was "{"
The other info above:
./src/styles/index.scss (./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/lib??postcss-3!./node_modules/sass-loader/lib/loader.js??ref--13-oneOf-1-3!./src/styles/index.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
{

I have searched and searched but as a Newbie, I found nothing that really speaks to this error. The SCSS file does the same thing as this was the next step in the tutorial. This is basic and at the beginning and the first time a css file didn't work in any tutorial, so I am a bit frustrated and lost. 

![image](https://user-images.githubusercontent.com/19393274/57899751-d25cdb00-7823-11e9-8369-8ae49d60afa2.png)

I'd appreciate any help. 
### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by Jared-Dev** [comment]
If that file is a screenshot of your actual file then it appears that you are missing an identifier that the rule should apply to. I.e.

```css
* { color: red; }
// or
span { color: red; }
// or
.red-the-thing { color: red; }
```

**Comment by lsguillory** [comment]
Thanks, I just saw the asterisk. You're great for not making me feel totally incompetent. I appreciate. it.

**Comment by Jared-Dev** [comment]
@lsguillory no worries, little stuff like that is easy to miss!
