### ISSUE TITLE
tutorial errors w/ "missing gatsby-config"

### ISSUE THREAD

**Issue by jaredly** [gatsbyjs/gatsby#1412]
I'm following https://www.gatsbyjs.org/tutorial/part-one/#creating-a-gatsby-site-from-scratch, but when I get to `./node_modules/.bin/gatsby develop`, it errors saying it tried to require `./gatsby-config` and it wasn't there.
Seems like we're missing a step.

**Comment by KyleAMathews** [comment]
Almost certainly is because it had you install the old "next" version instead of our shiny new stable-er release

https://github.com/gatsbyjs/gatsby/pull/1413

**Comment by KyleAMathews** [comment]
Could you install the latest version to confirm that fixes things?

**Comment by jaredly** [comment]
yeah that looks good!

**Comment by je553** [comment]
I was stuck on this for a while, too, but then I ran `yarn run gatsby develop` (based on how my other projects work) and it finally worked.

Maybe updating the tutorial to to say `npm run gatsby develop` might be a good idea?
