### ISSUE TITLE
Component shadowing isn't working with scoped packages

### ISSUE THREAD

**Issue by bkegley** [gatsbyjs/gatsby#14134]
## Description

Gatsby doesn't seem to allow component shadowing in scopes packages - i.e. (`@bkegley/scoped-theme`).

### Steps to reproduce

```
git clone https://github.com/bkegley/gatsby-scoped-theme-issue.git
cd gatsby-scoped-theme-issue
npx lerna bootstrap
yarn workspace gatsby-starter-default run develop
```

In `gatsby-config.js` toggle the `__experimentalThemes` config as well as the import statement in `pages/index.js` to test the shadow components in each theme.

There are two themes in `packages` - one scoped and one not - both export a button with a green background. The main site shadows both of these themes (scoped and non) with an red and orange background respectively. However, only the non-scoped theme is overridden.

### Expected result

Both scoped and non-scoped themes should allow component shadowing in the site.

### Actual result

Only non-scoped themes are able to be overridden.

### Environment

  System:
    OS: macOS Sierra 10.12.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.157
    Safari: 10.0.2
  npmGlobalPackages:
    gatsby-cli: 2.5.13

**Comment by ChristopherBiscardi** [comment]
The issue here is that your package directory on the filesystem (`scoped-theme`) doesn't match the package name (`@bkegley/scoped-theme`).

I've prototyped a solution that I think will remove this requirement.

**Comment by bkegley** [comment]
That was blazing fast 😆 Thanks!

**Comment by TidyIQ** [comment]
This still isn't working for me. 

I have a scoped theme `@tidyiq/gatsby-theme-tidyiq` and am attempting to overwrite a file located at `packages/@tidyiq/gatsby-theme-tidyiq/dist/theme.js`. I have tried creating a shadow component at `site/src/@tidyiq/gatsby-theme-tidyiq/dist/theme.js` yet it's not doing anything.

**Comment by bkegley** [comment]
Component shadowing works with the `src` directory in a theme. You'd shadow `packages/@tidyiq/gatsby-theme-tidyiq/src/theme.js` with `site/src/@tidyiq/gatsby-theme-tidyiq/theme.js` (notice omitting the `src` directory in the shadow component).

**Comment by TidyIQ** [comment]
Ah ok, I'll give that a try. That's very peculiar though that the theme distribution files are meant to go in a `src` folder instead of a `dist` folder. I developed my theme using typescript so I put the source .ts and .tsx files in the src folder, then I output the .js and .jsx to dist. 

I guess I'll just use a `realsrc` folder then rename `dist` to `src` to get it to work.

**Comment by TidyIQ** [comment]
Yep it works now. Thanks!
