### ISSUE TITLE
docs: Add explanation about `setup` field at gatsby-plugin-feed README

### ISSUE THREAD

**Issue by heejongahn** [gatsbyjs/gatsby#14136]
## Summary

Add explanation about `setup` field (or, the more appropriate way of setting the top-level fields of feed filed) at `gatsby-plugin-feed` README

### Basic example

N/A

### Motivation

Yesterday, I had a journey as below.

1. Found out my feed file's top-level `link` field was unintentionally set as `https://github.com/dylang/node-rss` ([configuration](https://github.com/heejongahn/blog/blob/8d4c5a8f22196c3dbe4c0b86a9dd165a4b625306/gatsby-config.js#L11-L64))
2. Couldn't find how to set it on both [the package README](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-feed) and [the official doc](https://www.gatsbyjs.org/docs/adding-an-rss-feed/)
3. The plugin README mentions `node-rss`, so after reading its README I found out `site_url` and `feed_url`.
4. Tried [this commit](https://github.com/heejongahn/blog/commit/089decb516c99a323305ae4405fce5306445106b). Still no luck.
5. So I opened the plugin source code, found [this line](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-feed/src/gatsby-node.js#L87), and finally made it work. ([commit](https://github.com/heejongahn/blog/commit/d6518d08f1d5986bd23e2472c4d27d4c1b333426))

I think setting the top-level fields for the feed is quite a common needs, and it would be nice if it is documented. I'm also willing to contribute, so if the team agrees that this documentation might help, please let me know.

**Comment by freiksenet** [comment]
Thank you for this suggestion! Would you like to open a PR with that fix?

**Comment by heejongahn** [comment]
Sure, I’ll come up with a draft in few days.

**Comment by marcysutton** [comment]
Can you describe the problem a bit more–what is the top-level link field? I looked through the commits and links in your description but I still couldn't tell how that came about.

That said, we want to keep READMEs and docs as straight-forward as possible for a wide range of situations. What I'd like to determine is how common this use-case is, and potentially include some "advanced setup" instructions to limit the cognitive overhead & required understanding when getting started.

**Comment by heejongahn** [comment]
@marcysutton when you generate feed with [the configuration of list item #1 on the original issue](https://github.com/heejongahn/blog/blob/8d4c5a8f22196c3dbe4c0b86a9dd165a4b625306/gatsby-config.js#L11-L64), you get:

```
<rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title>
      <![CDATA[ ahn.heejong ]]>
    </title>
    <description>
      <![CDATA[ 한국에 살며 웹사이트를 만드는 안희종입니다. ]]>
    </description>
    <link>http://github.com/dylang/node-rss</link>
    <generator>RSS for Node</generator>
    <lastBuildDate>Fri, 24 May 2019 17:18:53 GMT</lastBuildDate>
    (..and bunch of `<item>` tags here, one per each post)
  </channel>
</rss>
```

what bugged me was that my feed isn't the feed of `http://github.com/dylang/node-rss`; it's the RSS feed for my blog. (see line #9 of the code snippet above – `<link>http://github.com/dylang/node-rss</link>`).

By ‘top-level fields’, I meant direct children of `<channel>`, e.g. `<link>`, `<generator>`, `<atom:link>` and such. (I'm not very familiar with the precise terminologies, so please excuse me if I caused any confusions)

**Comment by heejongahn** [comment]
I think this issue can also be closed, in favor of proposed change in https://github.com/gatsbyjs/gatsby/pull/14237#issuecomment-497815056.
