### ISSUE TITLE
RSS/Atom Feeds should use absolute URLs to be standards-compliant

### ISSUE THREAD

**Issue by agentofuser** [gatsbyjs/gatsby#14133]
## Description

* By [default](https://github.com/gatsbyjs/gatsby/blob/626cab461640bd6598806f3ec5b98e196f83dc9a/packages/gatsby-plugin-feed/src/gatsby-node.js#L27), `gatsby-plugin-feed` uses the `markdownRemark` node's **html** field as the contents of RSS entries. 
* That html field has internal links and asset references as [root-relative](https://mor10.com/html-basics-hyperlink-syntax-absolute-relative-and-root-relative/) paths.
* The [W3C feed validator](https://validator.w3.org/feed/) complains that the feed [should not contain relative URL references](https://www.feedvalidator.org/docs/warning/ContainsRelRef.html).
* The `gatsby-plugin-feed` README also [uses](https://github.com/gatsbyjs/gatsby/blame/97b8ed61983ae9d4607ad058c0c3b74c3bd63f7d/packages/gatsby-plugin-feed/README.md#L39) the html field unaltered.
* Gatsby docs on [customizing the RSS](https://github.com/gatsbyjs/gatsby/blame/8a3d46431b20be989c0177a3102468dec44ff6c2/docs/docs/adding-an-rss-feed.md#L95) feed also use the html field with root-relative URLs.

I found a ("hacky", as he himself describes it) workaround on Dan Abramov's blog:

https://github.com/gaearon/overreacted.io/issues/65

The workaround is based on string replacement though, which would replace false-positives such as matches within code blocks. I'm also not sure whether `href` and `src` cover every use of urls in the html spec.

### Steps to reproduce

* Go to https://gatsby-starter-blog-demo.netlify.com/rss.xml
* Search for `salty_egg`

### Expected result

* `href="https://gatsby-starter-blog-demo.netlify.com/static/8058f3f26913fea3b6a89a73344fe94a/2b40c/salty_egg.jpg"`
* `src="https://gatsby-starter-blog-demo.netlify.com/static/8058f3f26913fea3b6a89a73344fe94a/c739e/salty_egg.jpg"` 

### Actual result

* `href="/static/8058f3f26913fea3b6a89a73344fe94a/2b40c/salty_egg.jpg"`
* `src="/static/8058f3f26913fea3b6a89a73344fe94a/c739e/salty_egg.jpg"`

**Comment by freiksenet** [comment]
Hi!

Thanks a lot for filing this issue! I wonder if you would like to make a PR to `gatsby-plugin-feed` to fix that?

Thank you! :purple_heart:

**Comment by agentofuser** [comment]
@freiksenet you're welcome :) I'd love to help, yes. I will probably have time to write that PR in a week or two if waiting that long is ok.

**Comment by humphreybc** [comment]
Ran into this one today. @agentofuser how did you get on with the PR?

**Comment by atuttle** [comment]
I'd be happy to take a crack at it, but I don't understand the code well enough. Can anyone lend a bit of insight to help get me started?

**Comment by eubanksmd** [comment]
Found a great blog article that describes how to replace the relative URL with absolute URL in the RSS feed while this issue gets sorted out: 
https://markshust.com/2020/06/25/fixing-images-in-gatsby-rss-feeds/

**Comment by bytrangle** [comment]
Hello Gatsby team, 
Do you still need this issue to be solved? If so, can I take on this?
