### ISSUE TITLE
Contentful with gatsby-source-contentful and apollo

### ISSUE THREAD

**Issue by LpmRaven** [gatsbyjs/gatsby#14138]
## Summary
I am querying data from Contentful using `gatsby-source-contentful` at build time to get the products for [WaterproofJack.com](https://waterproofjack.com). I am now building a filter for the product listing pages, to filter by brand, waterproof rating, breathability rating etc (many more). To do this I use Apollo at runtime to get product data when the filter is changed. I chose to do it this way (rather than at build time) due to the number of variations of product filters that could be selected. Unfortunately Contentful gives me this error. How does `gatsby-source-contentful` get around this? Alternatively, does anyone have a clever way of generating a large number of product filter variation pages?

```javascript
{
  errors: [
    {
      message: "GraphQL is not available for your plan",
      extensions: {
        contentful: {
          code: "UPGRADE_PLAN_REQUIRED",
          requestId: "0389b838-994f-46e4-b54a-317f63a9d24b"
        }
      }
    }
  ]
}
```

**Comment by pieh** [comment]
`gatsby-source-contentful` doesn't use Contentful graphql endpoint. It uses [Contentful Sync API](https://www.contentful.com/developers/docs/concepts/sync/). Sync API won't be good fit for client data fetching, but you can use [Contentful Content Delivery API](https://www.contentful.com/developers/docs/references/content-delivery-api/) if GraphQL isn't available in your Contentful plan

**Comment by LpmRaven** [comment]
Thanks @pieh. It seems really strange to me that Contentful has decided to restrict their GraphQL API to only larger plans when the technology to retrieve data has a limited impact on their bottom line; it's a disappointment. I'll try using the CCD API, thank again!

**Comment by LpmRaven** [comment]
@pieh, I noticed this issue that seems to completely match what I need. Is there any chance you have information about if the work is being continued on it? [Issue 10230](https://github.com/gatsbyjs/gatsby/issues/10230)
