### ISSUE TITLE
Rename "Behind the Scenes" docs to "Gatsby Internals"

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#14148]
Our recent Gatsby survey revealed that many people want documentation on how Gatsby internals work. 

**The good news is that these docs already exist:**

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/behind-the-scenes.md

**The bad news is that people are having problems finding them.**

In order to resolve this, we should:

(1) rename the behind-the-scenes doc page to `Gatsby internals`:
(a) change the URL, 
(b) change the title
(c) add a redirect

(2) Do the same for the terminology page:
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/behind-the-scenes-terminology.md

(3) Change the link title and URL on https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml

This is a great issue for first time contributors!

**Comment by tanayv** [comment]
Hello! Aiming to be a first time contributor here! I was working on this so I wanted to make sure I understood the steps correctly: For 1(a), changing the URL would just involve renaming the markdown file right?

**Comment by horacioh** [comment]
@tanayv yes!, changing the URL means changing the URL and the title :)

I recommend you test it locally first and also build the site locally and test it too. if you follow the steps aboe you should be ok!

**Comment by tanayv** [comment]
Got it, thanks!

**Comment by Jared-Dev** [comment]
Should there be a redirect added as well just in case someone has them bookmarked?

**Comment by tanayv** [comment]
Hi @calcsam, 

There's also another page for queries which uses behind-the-scenes in its URL:
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/query-behind-the-scenes.md

Should I rename this to `query-gatsby-internals` and also create a redirect for this?

**Comment by lannonbr** [comment]
Closing as @tanayv's PR which resolved this has been merged
