### ISSUE TITLE
[develop] requesting a path that doesn't end in .html gives a blank 404 response

### ISSUE THREAD

**Issue by jaredly** [gatsbyjs/gatsby#1414]
Gatsby should probably check for the `accepts: html` header & return the fancy 404 page in that case as well.

e.g going to `http://localhost:8000/awesome.md` gives me this:
![image](https://user-images.githubusercontent.com/112170/27982783-d216965c-6369-11e7-804a-b77b1b2a0483.png)

**Comment by KyleAMathews** [comment]
Hmmm there was some reason we stopped doing that before. Something about how it's tricky to differentiate between html request and request for images, etc.

This is the code if you or anyone else wants to poke at it https://github.com/gatsbyjs/gatsby/blob/660e5c41fd69ece5264f1f6b579d6556495205fe/packages/gatsby/src/utils/develop.js#L88
