### ISSUE TITLE
Node type mapping messes up order of lists

### ISSUE THREAD

**Issue by diondiondion** [gatsbyjs/gatsby#14162]
## Description

When using node type mapping, queries for fields that are affected by it don't return items in the order that they were originally defined in.

### Steps to reproduce

- Set up a node type mapping [as described in the docs](https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types) for a field that contains a list of items (for example a playlist in markdown frontmatter):
   ```
   // playlist.md
   ---
   title: Test playlist
   tracks:
     - One (1)
     - Deux (2)
     - Tres (3)
     - Vier (4)
   ---
   ```
   ```
   // track-one.yml
   ---
   title: One (1)
   artist: Nielson
   ---
   ```
- Query the list in your frontend code or graphiql and observe that the list is not ordered correctly anymore :( 
  ![image](https://user-images.githubusercontent.com/5636050/57986667-cbc2a380-7a6f-11e9-8adb-d10b1a13b3c1.png)

Not using a mapping and directly querying the track name as defined in the playlist's markdown file preserves the order of tracks, so it would be great if using a mapping did so, too.

**[Reproduction on Codesandbox](https://codesandbox.io/s/gatsbystarterdefault-k3div)**

### Expected result

The order of items should remain the same after using a node type mapping.

### Actual result

The order of items changes in mysterious ways that I'm not able to comprehend.

**Comment by freiksenet** [comment]
Thank you, fix here https://github.com/gatsbyjs/gatsby/pull/14176

**Comment by diondiondion** [comment]
Thanks a lot for the quick fix!

**Comment by wardpeet** [comment]
```
Successfully published:
 - gatsby@2.5.6
```
