### ISSUE TITLE
[gatsby-plugin-netlify-cms] how to import 3rd-party css into custom widgets?

### ISSUE THREAD

**Issue by d4rekanguok** [gatsbyjs/gatsby#14169]
## Summary

What is the right way to include css for netlify-cms custom widget?

Hi folks! I'm building a custom upload widget with [uppy](https://uppy.io/docs/react/dashboard/). The package comes with a few css files:
```js
import '@uppy/core/dist/style.css'
import '@uppy/dashboard/dist/style.css'
```

When I navigate to the generated `public` directory, I can see uppy's css being extracted & bundled into `cms.css` (`public/admin/cms.css`). However, they're missing from the generated `index.html`.

I thought I must have missed a setting somewhere, so I looked at the source code for `gatsby-plugin-netlify-cms` and found this [line](https://github.com/gatsbyjs/gatsby/blob/d23174e79c976d659c512ee1c4fc9ed23986bd8a/packages/gatsby-plugin-netlify-cms/src/gatsby-node.js#L139), followed by this comment:

>       /**
>        * Auto generate CMS index.html page.
>        */
>       new HtmlWebpackPlugin({
>         title: htmlTitle,
>         chunks: [`cms`],
>         excludeAssets: [/cms.css/],
>       }),
> 
>       /**
>        * Exclude CSS from index.html, as any imported styles are assumed to be
>        * targeting the editor preview pane. Uses `excludeAssets` option from
>        * `HtmlWebpackPlugin` config.
>        */
>       new HtmlWebpackExcludeAssetsPlugin(),

It looks like `cms.css` is intentionally excluded from `index.html`. What is then the right way to import 3rd party css into custom component?

Also, thanks for all the works that gone into `netlifyCMS` & `gatsby-pligin-netlify-cms`! It's the only CMS I use & recommend.

Pinging @talves 

## Relevant information

These are the netlify packages I'm using:

    "gatsby-plugin-netlify": "^2.0.16",
    "gatsby-plugin-netlify-cms": "^4.0.1",
    "netlify-cms-app": "^2.9.1",

### File contents (if changed)

`gatsby-plugin-netlify-cms` config:

```js
    {
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
        modulePath: `${__dirname}/src/cms/cms.js`,
      },
    },
```

**Comment by freiksenet** [comment]
CC @erquhart

**Comment by erquhart** [comment]
`cms.css` is included in the preview pane of the editor, which is an iframe, as it could mess with global cms styles if included in the page itself.

I was noodling over the issue of universal custom styles for widgets and implemented an experimental approach, along with the similarly undocumented API update for `registerWidget`. If you check the CMS repo you'll notice all of the internal widgets now pass only an object (returned by a function, generally) to that registration method. [Here's an example.](https://github.com/netlify/netlify-cms/blob/ccef446d72f96fa8d8db9bf2d0be5633eff79979/packages/netlify-cms-core/src/lib/registry.js#L81)

The approach being trialed right now for custom widget styles is to get the styles into a string, and then pass them in with key `globalStyles` at registration time:

```javascript
CMS.registerWidget({
  name: 'uppy',
  controlComponent: UppyControl,
  previewComponent: UppyPreview,
  globalStyles: 'css string',
})
```

I've used the `css-to-string` loader with webpack in the past to import dependency CSS as a string. Again, keep in mind, this isn't even in beta, we're still figuring it out. Please open an issue on the [CMS repo](https://github.com/netlify/netlify-cms) or chat with us in [Gitter](https://gitter.im/netlify/netlifycms) with any questions on that.

**Comment by talves** [comment]
I did not realize `globalStyles` was included in the API update. Thanks @erquhart for pointing it out.

**Comment by d4rekanguok** [comment]
Thanks @erquhart, I didn't realize `cms.css` was meant for preview iframe, that makes sense. I will try out `globalStyles` & keep an eye out for updates.
