### ISSUE TITLE
Caching with layout.css and <Layout>?

### ISSUE THREAD

**Issue by montylounge** [gatsbyjs/gatsby#14163]
## Description

I'm seeing layout.css referenced after starting a new site with gatsby when using `gatsby develop` but I'm not referencing this stylesheet in my project.

### Steps to reproduce

> gatsby new test-site
> cd test-site
> gatsby develop

[Screenshot](https://cl.ly/4d17f07715d7)

Then, stop dev server.

Replace ./pages/index.js with the below...

    import React from "react"

    const IndexPage = () => (
    <>
        <h1>Hi people</h1>
        <p>Welcome to your new Gatsby site.</p>
        <p>Now go build something great.</p>
    </>
    )

    export default IndexPage

Then run the dev server `> gatsby develop`

View site in browser.

[Screenshot](https://cl.ly/81b5327142d7)

Note the H1 is using the `-apple-system` font-family but no page styles have been provided.

Open up the developer tools to check things out...

[Screenshot](https://cl.ly/1e4808497459)

Not sure why the reference to layout.css style exists. With the update to index.js I removed the <Layout> component which is the source of the reference to `import "./layout.css"`

I thought, maybe caching, so I opened up incognito and no luck.

Then I tried up Safari (was using Chrome prior)... but the same result.

Next, stop dev server and then...

> gatsby clean
> gatsby develop

Viewed the site again, but the issue still exists.

Next, stop dev server.

Let's try something else... let's build the static site and view the results versus using `gatsby develop`.

> gatsby build
> gatsby serve

[Screenshot](https://cl.ly/3def0952dc16)

With the `build` command the result is as expected.

### Expected result

My assumption is when I remove the <Layout> component from the index.js file that the result would remove the reference to layout.css which it does do correctly in `gatsby build` but just no `gatsby develop`

### Actual result

It appears layout.css is cached.

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.10.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.157
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.5.5 => 2.5.5 
    gatsby-image: ^2.1.0 => 2.1.0 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.1 => 2.1.1 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.37 => 2.0.37 
    gatsby-source-filesystem: ^2.0.36 => 2.0.36 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 
  npmGlobalPackages:
    gatsby-cli: 2.5.15

**Comment by wardpeet** [comment]
what happens if you remove `node_modules/.cache` as this could be a babel cache issue. If it's the case we can look into this further.

**Comment by montylounge** [comment]
Issue still exists @wardpeet after `rm -rf node_modules/.cache` and then running `gatsby develop` to view the site again. Figured I'd share in case anyone else is running into the same issue. Thank you.

**Comment by wardpeet** [comment]
so removing `node_modules/.cache` is a quickfix?

**Comment by montylounge** [comment]
No, the issue still exists.

**Comment by wardpeet** [comment]
Hi {montylounge}!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by TarjeiB** [comment]
I have the same issue on chrome and cant get rid of the old styles. Tried clearing all caches etc. 
On firefox i do not have the same problem.

**Comment by montylounge** [comment]
Let me run my manual tests again on Firefox and Safari as well to confirm the behavior.

**Comment by KyleAMathews** [comment]
The file is imported in layout.js which is also used in the second page. Try deleting the second-page.js and layout.js?

**Comment by montylounge** [comment]
I'll try that next @KyleAMathews and get back to you - thank you.

**Comment by montylounge** [comment]
If I remove the <Layout> component from *all* page JS files (404, index, page-2) then the issue is resolved. Not sure if this should stay open or not but I created the ticket as I thought someone else may run into this and wanted to share. This isn't a roadblock for me, but possibly a confusion for someone getting started with gatsby?

**Comment by moroshko** [comment]
This unexpected behavior just tripped me as well. 

[Layout docs](https://www.gatsbyjs.org/docs/layout-components/#gatsbys-approach-to-layouts) state:
> Gatsby does not, by default, automatically apply layouts to pages...

@KyleAMathews Is this really the expected behavior that CSS included on page 1 will be included on page 2? This means that the site during `gatsby develop` looks different from how it looks after `gatsby build`.

Feels like a bug to me 🤔
