### ISSUE TITLE
Integrating Gatsby into my existing Godaddy site for only blogging

### ISSUE THREAD

**Issue by jnsrikanth** [gatsbyjs/gatsby#14172]
## Summary
I am having an existing HTML/CSS/PHP website hosted on GoDaddy using a cPanel. Now Everything works 100% fine there. I just need to add Blogging functionality locally into this site by creating a separate folder but want to serve up such blog post content using GatsbyJS.

Has anyone tried this before? If not, how can this be achieved? It would be good to know. 

My plan is to eventually move the rest of my website into GatsbyJS once I figure the appropriate architecture for that to serve up the same content that I have on my website right now.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wardpeet** [comment]
Sure you can! If you want a gatsby site to live in example.com/blog that's possible with [path-prefix](https://www.gatsbyjs.org/docs/path-prefix).

To get started, please check out https://www.gatsbyjs.org/tutorial/
