### ISSUE TITLE
A nice collection of often useful examples done in Gatsby

### ISSUE THREAD

**Issue by heshanfu** [gatsbyjs/gatsby#14170]
A nice collection of often useful examples done in Gatsby.
https://gatsbyawesome.com/

**Comment by wardpeet** [comment]
Hey thanks for sharing this website with us. We have https://www.gatsbyjs.org/showcase/ that does the same. It would be cool if we could add gatsbyawesome.com to our showcase but sadly it's not a gatsby site :cry:
