### ISSUE TITLE
fetch data from wordpress, Failed to process remote content.

### ISSUE THREAD

**Issue by xuweiwei117526** [gatsbyjs/gatsby#14173]
during our Gatsby build,fetch data from wordpress, we will see images which say Failed to process remote content.

Any assistance would be appreciated!

.source and transform nodes
.source and transform nodesFailed to process remote content http://site-url/sites/default/files/Name%20of%20file_2018_1.jpg
Failed to process remote content http://site-url/sites/default/files/Name%20of%20file_2018_1.jpg
Failed to process remote content http://site-url/sites/default/files/NameOfFile.gif

**Comment by josh-meredith** [comment]
I have experienced this same issue, and it seems the only fix for now is to manually reduce the limit of concurrent downloads within the `gatsby-source-filesystem` plugin. The problem is most likely due to server/network overload.

Please see #13073 for the fix I'm referring to. Unfortunately it doesn't look like there has been much progress with the PR.

**Comment by bakeruk** [comment]
@wardpeet This looks like the same issue as the recent `gatsby-source-drupal` that was merged into master (#13943).

All to do with unresolved promises overloading the callstack using with using `Promise.all` in the code

```
// Downloads media files and removes "sizes" data as useless in Gatsby context.
exports.downloadMediaFiles = async ({
  entities,
  store,
  cache,
  createNode,
  createNodeId,
  touchNode,
  getNode,
  _auth,
}) =>
  Promise.all(
    entities.map(async e => {
      let fileNodeID
      if (e.__type === `wordpress__wp_media`) {
        const mediaDataCacheKey = `wordpress-media-${e.wordpress_id}`
        const cacheMediaData = await cache.get(mediaDataCacheKey)

        // If we have cached media data and it wasn't modified, reuse
        // previously created file node to not try to redownload
        if (cacheMediaData && e.modified === cacheMediaData.modified) {
          const fileNode = getNode(cacheMediaData.fileNodeID)

          // check if node still exists in cache
          // it could be removed if image was made private
          if (fileNode) {
            fileNodeID = cacheMediaData.fileNodeID
            touchNode({
              nodeId: fileNodeID,
            })
          }
        }

        // If we don't have cached data, download the file
        if (!fileNodeID) {
          try {
            const fileNode = await createRemoteFileNode({
              url: e.source_url,
              store,
              cache,
              createNode,
              createNodeId,
              parentNodeId: e.id,
              auth: _auth,
            })
...
```

I don't have the time to fix this currently, nor do I have a project to test once the change has been made. However, we could definitely get set **labels** against this 😊👍🏼

**Comment by wardpeet** [comment]
Yes, indeed, lets fix this asap.

**Comment by xuweiwei117526** [comment]
Excuse me, please ask the code with the ellipsis above is not the final one.How to change this question specifically, I still don’t quite know.This problem has plagued me for a long time.If you can specifically write how to change this problem, I must be very grateful.

**Comment by xuweiwei117526** [comment]
Please keep it open,thank you!

**Comment by jacobsilver2** [comment]
Yes, please keep this open!

**Comment by josh-meredith** [comment]
FYI - The `gatsby-source-filesystem` plugin has been updated which now accepts the `GATSBY_CONCURRENT_DOWNLOAD` environment variable. Try setting this value to 10 and you should hopefully have some luck.

You can reference the [docs](https://www.gatsbyjs.org/docs/environment-variables/#server-side-nodejs) if you're not sure how to set the environment variable.

**Comment by Kevin-Hamilton** [comment]
@wardpeet can we get this labeled "not stale", please?

**Comment by Kevin-Hamilton** [comment]
@wardpeet - just another gentle reminder ... I believe this should be "not stale".  See your comment here: https://github.com/gatsbyjs/gatsby/issues/14173#issuecomment-493937401

**Comment by wardpeet** [comment]
I was on vacation, so thanks @m-allanson to get this one re-opened.

**Comment by sidharthachatterjee** [comment]
Closing this in favour of https://github.com/gatsbyjs/gatsby/issues/10049
