### ISSUE TITLE
Automatic TypeScript Definitions Generation

### ISSUE THREAD

**Issue by Siyfion** [gatsbyjs/gatsby#14185]
## Summary

This feature request stems from a conversation on the Gatsby discord server that I had with @DSchau in which I asked:

> Is there any way to generate TypeScript definitions for the results of each `graphql''` query? This would allow us to ensure that all cases are covered, with regards to nullables, etc.

> I did think that I might be able to use something like: `npx apollo@2.11.1 client:codegen --endpoint=http://localhost:8000/___graphql --target=typescript` however, we use gatsby-image and it complains mightily about `Unknown fragment "GatsbyContentfulFluid_withWebp"` etc...

> It just seems that this is something that Gatsby has the potential to do entirely for you on initial build, and then on each file change... Something to consider?

> dschau: @StarvingDragon we've talked about generating the SDL (e.g. a snapshot of the current schema as apollo-like types) but hadn't considered Typescript definitions! Could you perhaps share some more info and/or open an issue with more detail for what you'd like?

### Basic example & Motivation

> So the benefit of this (auto-generated types) would be that if you're developing in TS, you could type all data passed into the pages/component as props mega simply! And you could also guarantee that after each rebuild, if the types changed, you'd know and have failing TS errors...

> eg. imagine changing a field (say "author") in Contentful from required to optional. The next time that Gatsby would start up, it would know that field is now optional and update the TS definition such that `author: Author | null`. Leading anywhere that you're not handling a null value to throw TS errors.

### Progress so far

I have managed to get the `apollo:codegen` tool to recognise the queries Gatsby uses by changing imports to `import { graphql as gql } from 'gatsby'`, as I believe it's looking for `gql` tags. However, as stated above, it struggles with the Gatsby Image fragments, as it doesn't know what they are!

**Comment by lannonbr** [comment]
CC: @pieh I recall you having something similar to this if I am not mistaken

**Comment by pieh** [comment]
@Siyfion I'm not sure if this still works - but you can try checking https://github.com/pieh/gatsby-query-result-type-gen

**Comment by pieh** [comment]
Yep, it doesn't work anymore after some refactoring done in gatsby (as I was importing some gatsby internals there), but it probably can be updated to work again.

The fragment blocker you mentioned - please check my code - I was importing "queries" directly from gatsby redux store (and not parsing your project directly). This ensures that any fragments that were used will be attached to queries (i.e. gatsby-image` fragments)

**Comment by Siyfion** [comment]
Ah nice @pieh! Is this something that the Gatsby team would consider incorporating as an official tool in future? I really think it'd be hugely useful!

**Comment by Siyfion** [comment]
I believe that the major breaking change seems to be this refactor: https://github.com/gatsbyjs/gatsby/commit/bbb8c36f78af806f6e79310bca9b3c99df107436

**Comment by pieh** [comment]
> Ah nice @pieh! Is this something that the Gatsby team would consider incorporating as an official tool in future? I really think it'd be hugely useful!

This was one of my "weekend projects", and I don't think we really talked about it yet.

Now I start to remember more when I was working on this (why I didn't make it a plugin and made "standalone" tool). apollo-codegen used different version of `graphql` package and this was causing issues (when you have multiple versions of graphql package in node_modules it can cause weird issues ( for example errors like https://github.com/graphile/postgraphile/issues/677 ) - which also make it hard to incorporate this nicely

**Comment by Siyfion** [comment]
> apollo-codegen used different version of `graphql` package and this was causing issues (when you have multiple versions of graphql package in node_modules it can cause weird issues

Yup, I've been on the receiving end of lots of those issues at various points over the last few months! I does seem to be a constant issue with the Apollo CLI unfortunately. Still, if Gatsby did support this tool as an official way to generate TypeScript Definitions, I'm sure there would be a fair amount of support for it ;)

**Comment by andykenward** [comment]
You should try using [`graphQL-codegen`](https://graphql-code-generator.com) . They have [documentation](https://graphql-code-generator.com/docs/integrations/gatsby) on using it with Gatsby.

```
npm i @graphql-codegen/cli @graphql-codegen/typescript @graphql-codegen/typescript-operations --save-dev
```

There is currently an [issue](https://github.com/dotansimha/graphql-code-generator/issues/642#issuecomment-495919863) with their suggested config  so use the below config.
```
schema: http://localhost:8000/___graphql
documents:
  - ./src/**/*.{ts,tsx}
  - ./node_modules/gatsby-*/**/*.js
config:
  namingConvention:
    enumValues: keep
generates:
  ./src/graphqlTypes.ts:
    plugins:
      - typescript
      - typescript-operations
```

**Comment by pieh** [comment]
Ooooh, that's interesting!

**Comment by cameron-martin** [comment]
Related: https://github.com/gatsbyjs/gatsby/issues/2374

**Comment by Siyfion** [comment]
Wow, that's really cool @andykenward, though it still seems to struggle with the image fragments, eg:

```
$ graphql-codegen
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./src/graphqlTypes.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        →         at ./node_modules/gatsby-transformer-sharp/src/fragments.js:200:53


 Found 1 error

  ✖ ./src/graphqlTypes.ts
    AggregateError:
        GraphQLDocumentError: Unknown type "ImageSharpFixed".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:1:35
```

Perhaps using their programmatic API we could add these "known" fragments in @pieh?

**Comment by andykenward** [comment]
@Siyfion is works with `GatsbyImageSharpFixed` fragment.

I've made a Gatsby Starter you can try it out ["Gatsby's default starter - TypeScript"](https://github.com/andykenward/gatsby-starter-default-typescript) with `graphql-code-generator` setup.

**Comment by Siyfion** [comment]
@andykenward we're using `GatsbyContentfulFluid_withWebp` and `GatsbyContentfulFixed_withWebp` throughout our code, so I can only assume that the issue relates to their usage as, like you say, your repo with images seems to work fine!

**Comment by andykenward** [comment]
@Siyfion I think that's to do with not being able to query the Contentful GraphQL endpoint to generate their fragments. Adding the Gatsby Plugin `gatsby-source-contentful` and having valid api keys setup. When I try to generate the typings I get an error on  any fragment referring to their fragments `ContentfulFixed`. 

```
at ./node_modules/gatsby-source-contentful/src/fragments.js
 AggregateError:
        GraphQLDocumentError: Unknown type "ContentfulFixed".
            at ./node_modules/gatsby-source-contentful/src/fragments.js:1:35
        GraphQLDocumentError: Unknown type "ContentfulFixed".
            at ./node_modules/gatsby-source-contentful/src/fragments.js:9:45
```

**Comment by Siyfion** [comment]
Yeah, it's weird because they are all there in that `./node_modules/gatsby-source-contentful/src/fragments.js` file... Not really sure what's going on 😕

**Comment by andykenward** [comment]
@Siyfion Setting up [`Gatsby-source-graphql`](https://www.gatsbyjs.org/packages/gatsby-source-graphql/) and configuring GraphCMS and GitHub GraphQL Endpoints lets me generate their schemas typings just using `http://localhost:8000/___graphql` as the one endpoint for "GraphQL code generator".

Perhaps using `gatsby-source-graphql` and configuring a Contentful GraphQL endpoint will solve it?

**Comment by Siyfion** [comment]
@andykenward but the thing is, I don't _think_ that the `gatsby-source-contentful` plugin is actually using Contentful's GraphQL API, as it's currently reserved for specific high-throughput/perf. spaces.

So the GraphQL fragments, types, etc. must _all_ be coming from the Gatsby plugin!?

**Comment by Siyfion** [comment]
I've been having a lot of success with `graphql-codegen` in many other projects, but unfortunately the moment I use a fluid/fixed image the whole thing comes crumbling down with a Gatsby project. Which is a shame! Why aren't the fragments exposed in the introspection query I wonder? @KyleAMathews

**Comment by KyleAMathews** [comment]
@Siyfion it's tricky as graphiql and other tools don't support it. @pieh has some initial work in that direction so hopefully we'll get there.

**Comment by gemcave** [comment]
same problem:

**Comment by d4rekanguok** [comment]
hey folks, run into this issue by chance -- I recently wrote a [typescript plugin that does codegen automatically](https://www.gatsbyjs.org/packages/gatsby-plugin-ts/), using `graphql-codegen` api like pieh mentioned above. I've been using it for awhile, so far so good.

The codegen part can be its own plugin really -- I wanted to spin it out but haven't got the chance to do so yet. Give it a try if you're interested!

**Comment by orta** [comment]
The new GraphiQL 1.0 re-design work should allow plugins which I think would support adding the extra fragments

**Comment by RIP21** [comment]
@Siyfion about Fragments, I just copy-pasted them into the project from the plugin itself and got everything generated.
Just copy-paste this file.
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/fragments.js
And you're good to go with `graphql-codegen`

If anyone wondering what is my config. Here it is.
```yaml
overwrite: true
schema: "${SCHEMA:schema.graphql}"
pluckConfig:
  globalIdentifier: "graphql"
documents:
  - "./{src,gatsby-scripts}/**/*.graphql"
  - "./{src,gatsby-scripts}/**/*!(.generated).{ts,tsx}"
generates:
  src/types.generated.ts:
    plugins:
      - "typescript"
    config:
      namingConvention:
        enumValues: keep
  src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: ./types.generated.ts
    plugins:
      - typescript-operations
  ./schema.graphql:
    plugins:
      - "schema-ast"
```

Although I must admit strictness of types that are generated needs to be fixed because typings that are getting generated are way too "nullable" causing millions of `null` checks for no reason..
Please, continue the discussion about it here https://github.com/gatsbyjs/gatsby/issues/16310  anyone who is interested.

**Comment by slorber** [comment]
hey, has anybody encountered incompatible types between the gatsby image fluid fragments and the gatsby-image fluid prop? => https://github.com/gatsbyjs/gatsby/issues/17003

**Comment by daugsbi** [comment]
Hey,
I've created a plugin for handling TypeScript/Flow generation with apollo-codegen and configure the vscode apollographql plugin for autocomplete.

```shell
npm install --save gatsby-plugin-codegen
```

I would love to hear your feedback.

**Comment by bsgreenb** [comment]
Best approach I've found for temporarily dealing with this is [Type Assertions]
(https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions):

```import Img, {GatsbyImageProps} from "gatsby-image";

<Img fluid={(featuredImage.fluid as GatsbyImageProps['fluid'])} />```

**Comment by bsgreenb** [comment]
The problem with any of the recommendations here is that you can get a [working Gatsby setup](https://graphql-code-generator.com/docs/integrations/gatsby), you can get a [working Contentful setup](https://github.com/intercom/contentful-typescript-codegen).

However when you try to use Gatsby+Contentful there is no proper tool.  Everything (Required or not) has `| null` after it, and none of the generated interfaces match the expected props.  This is primarily because Contentful does not set `non_null` for Required fields, as explained here:

![image](https://user-images.githubusercontent.com/980217/67989748-028d1000-fbf1-11e9-9059-ac1f163d747d.png)

I am seeing if I can hack in Required fields, basically stuck

**Comment by TeoTN** [comment]
So what is the status of that and what is the state of the art way to integrate gatsby, graphQL, fragments and typescript?
I currently have `ts-graphql-plugin` in my `tsconfig.json`,  `gatsby-plugin-typegen` to generate types and schema, GraphQL plugin for webstorm and `gatsby-plugin-typescript`, and it fails on the fragment. Is there a simple way to have it all running together?

**Comment by LekoArts** [comment]
Let's track this in the meta issue: https://github.com/gatsbyjs/gatsby/issues/17934
Please add your comments there, thanks!

**Comment by LekoArts** [comment]
This is soon a built-in feature to Gatsby: [RFC: GraphQL TypeScript Generation](https://github.com/gatsbyjs/gatsby/discussions/35420)
