### ISSUE TITLE
[gatsby-plugin-sitemap] Incorrect http header content-type: "text/html; charset=UTF-8" (expected: "application/xml")

### ISSUE THREAD

**Issue by jakeherp** [gatsbyjs/gatsby#14181]
## Description

The header content type for the sitemap.xml generated by `gatsby-plugin-sitemap` has an incorrect header type (text/html), but will need the header type `application/xml` to be parsed by Google correctly.

### Steps to reproduce

Basic set up of the plugin in a fresh Gatsby installation

### Expected result

`sitemap.xml` should send the header content-type: "application/xml"

### Actual result

Header content-type: "text/html; charset=UTF-8"

### Environment

Local environment: 
```
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.2.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.1-next.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 65.0
    Safari: 12.1
  npmPackages:
    gatsby: ^2.5.5 => 2.5.5 
    gatsby-image: ^2.1.0 => 2.1.0 
    gatsby-plugin-google-tagmanager: ^2.0.13 => 2.0.13 
    gatsby-plugin-lunr: ^1.5.0 => 1.5.0 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-netlify: ^2.0.17 => 2.0.17 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-nprogress: ^2.0.10 => 2.0.10 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-robots-txt: ^1.4.0 => 1.4.0 
    gatsby-plugin-sharp: ^2.0.37 => 2.0.37 
    gatsby-plugin-sitemap: ^2.1.0 => 2.1.0 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-transition-link: ^1.12.4 => 1.12.4 
    gatsby-source-filesystem: ^2.0.36 => 2.0.36 
    gatsby-source-wordpress: ^3.0.61 => 3.0.61 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 
    gatsby-v2-plugin-page-transitions: ^1.0.0 => 1.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.5.15
```

Remote environment: 
  Netlify

**Comment by wardpeet** [comment]
This seems like a hosting issue. What provider do you use to host your website?

**Comment by jakeherp** [comment]
The site is hosted with Netlify

**Comment by jakeherp** [comment]
Sorry, disregard what I just said - while the site is hosted on Netlify, it is accessed through a Pantheon server with a rewrite and a redirect. The sitemap.xml works on Netlify directly, but not under the final domain. 
Will have to investigate on Pantheon.

**Comment by savage-hack** [comment]
I am having same error incorrect http header. My site is hosted on github
