### ISSUE TITLE
Blurred image never shown

### ISSUE THREAD

**Issue by hyperknot** [gatsbyjs/gatsby#14186]
## Description

In the default configuration of gatsby-starter-blog, the blurred image from markdown visible in `/hello-world` (salty_egg.jpg 684 KB), is never shown.

### Steps to reproduce
gatsby new test https://github.com/gatsbyjs/gatsby-starter-blog
cd test
yarn build
yarn serve
put Chrome network panel to disable cache + slow 3G (+ clear site data for worker cache if needed)
load http://localhost:9000/hello-world/

### Expected result
The blurred image, present in the HTML with `.gatsby-resp-image-background-image` should be shown during loading.

### Actual result
White space is show, until image is loaded, top to bottom.

### Environment

```

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.15.1 - ~/n/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/n/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 66.0.5
    Safari: 12.1
  npmPackages:
    gatsby: ^2.5.5 => 2.5.5 
    gatsby-image: ^2.1.0 => 2.1.0 
    gatsby-plugin-feed: ^2.2.0 => 2.2.0 
    gatsby-plugin-google-analytics: ^2.0.20 => 2.0.20 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.1 => 2.1.1 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.37 => 2.0.37 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
    gatsby-remark-copy-linked-files: ^2.0.12 => 2.0.12 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-remark-prismjs: ^3.2.9 => 3.2.9 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.36 => 2.0.36 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 
  npmGlobalPackages:
    gatsby-cli: 2.5.15
```

**Comment by hyperknot** [comment]
I see, this is simply because the starter is still using 2.x of gatsby-remark-images.

**Comment by DSchau** [comment]
Interesting - would you like to PR this fix to update the version?

**Comment by harshil1712** [comment]
Hey, is anyone working on this? I would like to take this

**Comment by harshil1712** [comment]
@FrederikBolding awesome!

**Comment by FrederikBolding** [comment]
@harshil1712 Here we go: #14217

**Comment by JoshuaWalsh** [comment]
I've updated to 3.0.12

```
PS D:\git\personal-blog> npm list gatsby-remark-images
personal-blog@0.1.0 D:\git\personal-blog
`-- gatsby-remark-images@3.0.12
```

But blur-up still isn't working properly for me. It appears for a very short amount of time, but then disappears:

![blurUp](https://user-images.githubusercontent.com/2290576/58370621-033bbf00-7f4c-11e9-97bd-728eb8e2923c.gif)

Any ideas?
