### ISSUE TITLE
Consider removing the GitHub bot from discord 

### ISSUE THREAD

**Issue by marcustisater** [gatsbyjs/gatsby#1418]
Howdy 👋 I am loving the project so far. I am walking through the docs atm, found some broken links so I will try submit PR within next few days if that's cool.

I have a suggestion 😉 Remove the GitHub bot that posts to the discord chat whenever there is activity  on the project, it's kinda annoying and message goes by.

Btw what do you think about opening up a chat on [gitter.im](http://gitter.im/)? I personally love it as it's very easy to sign up for.

Cheers,
Keep up the good work!

**Comment by jquense** [comment]
or debounces maybe :P that 1.0 bump has really increased the volume of messages :P

**Comment by KyleAMathews** [comment]
Yeah, normally it's not so noisy around here :-) I rather like seeing the stars normally as it's motivating in the sense that "oh, people really are paying attention and using Gatsby".

Right now we're using a bot that discord wrote for the github integrations but if our starring volume continues to be high (here's hoping), then yeah, a custom bot which groups stars would be sweet. I'm already planning on adding more custom bots so this would straightforward.

And thanks for your docs PR! Keep them coming!

**Comment by marcustisater** [comment]
Thanks for the answer, I agree with you.

I will tidy up that PR 😉
