### ISSUE TITLE
Broken Examples

### ISSUE THREAD

**Issue by derekperkins** [gatsbyjs/gatsby#1419]
**Sitemap** 
https://sitemap.gatsbyjs.org has no DNS entry
From https://github.com/gatsbyjs/gatsby/tree/master/examples/sitemap

**HN**
The link is copied from gatsbygram, and I'm not sure what the right demo destination is (or I'd submit a PR)
From https://github.com/gatsbyjs/gatsby/tree/master/examples/hn

**Comment by jamesdbruner** [comment]
At a glance.. feed, redux, no-plugins, sitemap and page-loading-indicator all don't resolve for me with the error message:

> This site can’t be reached
> 
> _example_.gatsbyjs.org’s server DNS address could not be found.

contentful is broken in a different way and it looks like WordPress doesn't have a readme.

**Comment by KyleAMathews** [comment]
Yeah, planning on doing a cleanup sweep of the example sites next week.

How is contentful broken?

@sebastienfi when you get back from vacation, could you add a README to the wordpress example site? I'll get it building online.

**Comment by jamesdbruner** [comment]
Ah sorry, I should have been more specific. The link in the using-contentful example readme is broken. [(this link)](https://gatsby-using-contentful.netlify.com/). It just says "Not Found"

**Comment by KyleAMathews** [comment]
@jamesdbruner ah :-) yeah, that is wrong — fixed in https://github.com/gatsbyjs/gatsby/pull/1436

**Comment by sebastienfi** [comment]
@KyleAMathews The API is hosted on Wordpress.com so basically it's free tier. Where should I host the live Gatsby's Wordpress example site ?

**Comment by KyleAMathews** [comment]
@sebastienfi I'll handle setting up the hosting for the example site. All Gatsby example sites are hosted on Netlify so we can build them on every PR as integration tests.

**Comment by sebastienfi** [comment]
@KyleAMathews any news on ⬆️ ?

**Comment by KyleAMathews** [comment]
We're going to automatically host example sites w/ https://github.com/gatsbyjs/gatsby/pull/3242
