### ISSUE TITLE
ERROR Sharp images

### ISSUE THREAD

**Issue by lsguillory** [gatsbyjs/gatsby#14203]
## Description

Having problems installing sharp plugins. I'm a newbie so am pretty much at a loss and have gone as far I can. 

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

I'm going through a Gatsby tutorial and the author is not having any problems, simply runs
npm install gatsby-plugin-sharp@2.0.32 gatsby-remark-images@3.0.10 gatsby-remark-relative-images@0.2.2

Haven't had any problems installing other plugins
### Actual result

What happened.

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lsggu\Desktop\tutorials\gatsby-newBootcamp\node_modules\sharp
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.21.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lsggu\AppData\Roaming\npm-cache\_logs\2019-05-21T05_50_01_252Z-debug.log

### Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    npm: 6.9.0 
  Languages:
    Python: 2.7.15  
  Browsers:
    Version 74.0.3729.157 (Official Build) (64-bit)
  npmPackages:
    gatsby: ^2.5.5 => 2.5.5
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-source-filesystem: ^2.0.28 => 2.0.28
    gatsby-transformer-remark: ^2.3.8 => 2.3.8

### Steps I took

Did some research and found that it could be a windows build issue
https://github.com/gatsbyjs/gatsby/issues/6976
https://www.gatsbyjs.org/docs/gatsby-on-windows/
 I followed the instructions, installed and ran again, and got the same result. 

More googling did not provide further help and didn't want to make the issue worse. 

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by wardpeet** [comment]
@lsguillory could you remove node_modules and install again?

**Comment by lsguillory** [comment]
### Success

Thank you so much as the uninstall worked to load the packages. 
I uninstalled and reinstalled and I was able to load the packages with success. I was elated then deflated as It seems now it is an error in failing to process image. To make sure I hadn't made a mistake in coding I downloaded the source file for setting up the config file for the images section. 

Here is the code: 
'gatsby-plugin-sharp',
        {
            resolve: 'gatsby-transformer-remark',
            options: {
                plugins: [
                    'gatsby-remark-relative-images',
                    {
                        resolve: 'gatsby-remark-images',
                        options: {
                            maxWidth: 750,
                            linkImagesToOriginal: false
                        }
                    }
                ]
            }
        }
    ]
}

### System
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/lsggu/.windows-build-tools/python27/python
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.5.5 => 2.5.5
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32
    gatsby-remark-images: ^3.0.10 => 3.0.10
    gatsby-remark-relative-images: ^0.2.2 => 0.2.2
    gatsby-source-filesystem: ^2.0.28 => 2.0.28
    gatsby-transformer-remark: ^2.3.8 => 2.3.8

### Results after installation of sharp images package
> gatsby-starter-hello-world@0.1.0 develop C:\Users\lsggu\Desktop\tutorials\gatsby-newBootcamp
> gatsby develop

success open and validate gatsby-configs — 0.004 s
success load plugins — 0.651 s
success onPreInit — 0.005 s
success initialize cache — 0.023 s
success copy gatsby files — 0.156 s
success onPreBootstrap — 0.018 s
success source and transform nodes — 0.168 s
success building schema — 0.502 s
success createPages — 0.029 s
success createPagesStatefully — 0.046 s
success onPreExtractQueries — 0.000 s
success update schema — 0.040 s
success extract queries from components — 0.129 s
success run static queries — 0.018 s — 4/4 239.61 queries/second
error UNHANDLED REJECTION


  Error: Failed to process image C:/Users/lsggu/Desktop/tutorials/gatsby-newBootcamp/src/posts/grass.png

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-hello-world@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-starter-hello-world@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jonniebigodes** [comment]
@lsguillory can you create a reproduction, following [this](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be looked at? If you don't mind include the image that is causing trouble

**Comment by lsguillory** [comment]
Thanks. I've created a repository https://github.com/lsguillory/gatsbybootcamp . That was easier for me. I hope that's not a problem. 

I ran it again and got a new error --Unable to find plugin "gatsby-remark-relative-images,".  It shows in the system so my mind is boggled. 

Any help would be appreciated.

The other question I have are there other images plugins that can be used? As I'm asking the question, I realize it could be the setup so that wouldn' help.


### System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/lsggu/.windows-build-tools/python27/python
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.5.5 => 2.5.5
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32
    gatsby-remark-images: ^3.0.10 => 3.0.10
    gatsby-remark-relative-images: ^0.2.2 => 0.2.2
    gatsby-source-filesystem: ^2.0.28 => 2.0.28
    gatsby-transformer-remark: ^2.3.8 => 2.3.8


### ERROR
> gatsby-starter-hello-world@0.1.0 develop C:\Users\lsggu\Desktop\tutorials\gatsby-newBootcamp
> gatsby develop

success open and validate gatsby-configs — 0.010 s
error UNHANDLED REJECTION


  Error: Unable to find plugin "gatsby-remark-relative-images,". Perhaps you need to install its package?

  - load.js:107 resolvePlugin
    [gatsby-newBootcamp]/[gatsby]/dist/bootstrap/load-plugins/load.js:107:11

  - load.js:119 processPlugin
    [gatsby-newBootcamp]/[gatsby]/dist/bootstrap/load-plugins/load.js:119:20

  - load.js:132 plugin.options.plugins.forEach.p
    [gatsby-newBootcamp]/[gatsby]/dist/bootstrap/load-plugins/load.js:132:27

  - Array.forEach

  - load.js:131 processPlugin
    [gatsby-newBootcamp]/[gatsby]/dist/bootstrap/load-plugins/load.js:131:32

  - load.js:169 config.plugins.forEach.plugin
    [gatsby-newBootcamp]/[gatsby]/dist/bootstrap/load-plugins/load.js:169:20

  - Array.forEach

  - load.js:168 module.exports
    [gatsby-newBootcamp]/[gatsby]/dist/bootstrap/load-plugins/load.js:168:20

  - index.js:56
    [gatsby-newBootcamp]/[gatsby]/dist/bootstrap/load-plugins/index.js:56:21

  - Generator.next

  - new Promise

  - index.js:85
    [gatsby-newBootcamp]/[gatsby]/dist/bootstrap/load-plugins/index.js:85:17


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-hello-world@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-starter-hello-world@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jonniebigodes** [comment]
@lsguillory i'll look it over  and i'll post a detailed explanation of your issue and possibly how to solve it. Do you mind waiting a bit while i look into your code?

**Comment by lsguillory** [comment]
No, not at all, take your time. I need to pour some motivation into me to keep going.

**Comment by jonniebigodes** [comment]
@lsguillory sorry for the wait. I'm going to detail the steps taken to solve your issue and some considerations for you, if you don't mind.

- Cloned the repository you provided.
- Installed the dependencies
- Issued `gatsby develop` and the error you mentioned last was present. The problem in there was a extra comma present in your `gatsby-config.js` you have the following:

```javascript
module.exports = {
.....
plugins:[
....
{
        resolve: 'gatsby-transformer-remark',

        options: {
            plugins: [
                'gatsby-remark-relative-images,', // <-extra comma 
                {
                  resolve: 'gatsby-remark-images', 
                  options: {
                      maxWidth: 750,
                      linkImagesToOriginal: false
                  }
                }
            ]
        }
      }
]
}
```
And it should be:
```javascript
{
        resolve: 'gatsby-transformer-remark',

        options: {
            plugins: [
                'gatsby-remark-relative-images',
                {
                  resolve: 'gatsby-remark-images', 
                  options: {
                      maxWidth: 750,
                      linkImagesToOriginal: false
                  }
                }
            ]
        }
      }
```

- Re issued `gatsby develop` and it was almost good, the error was not popping up, but it brought me to the attention of a couple of things which if you don't mind i'll go over next.

- Starting from your `gatsby-config.js` file, you should only reference the folders you actually need, instead of using a base one and go from there, as it might lead to more bad than good and probably more code t obe implemented. More exactly in this case:
```javascript
module.exports = {
...
plugins:[
{
          resolve: 'gatsby-source-filesystem',
          options: {
              name: 'src',
              path: `${__dirname}/src/`,
          }
      },
]
}
```
You need the posts, make Gatsby look for the posts only, instead of having ` path: `${__dirname}/src/`,` you have `path: `${__dirname}/src/posts`,`.

- On your `gatsby-node.js`, you have the following:
```javascript
module.exports.onCreateNode = ({ node, actions }) => {
    const { createNodeField } = actions
    // Transform the new node here and create a new node or
    // create a new node field.

    //console.log(node)

    if (node.internal.type === 'MarkdownRemark') {  //target specific nodes 2 articles
        const slug = path.basename(node.fileAbsolutePath, '.md')

        createNodeField({
            node,
            name: 'slug',
            value: slug
        })
    }    
  }
```
Looking over at it, you can optimize it and generate the "physical" path and also the necessary field so that the graphql queries can use it a priori. Transforming it into the following:

```javascript
const { createFilePath } = require(`gatsby-source-filesystem`)
exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions

  // checks for type of node
  if (node.internal.type === `MarkdownRemark`) {
    // creates the "physical" path where the page sourced from markdown will live
    // more on the item here https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createfilepath
    const value = createFilePath({ node, getNode })
    // 
    // generates necessary graphql field that will be consumed when querying for the markdown pages
    createNodeField({
      name: `slug`,
      node,
      value,
    })
    //
  }
}
```

Saw in your description that you're a bit of a newcomer to Gatsby, so i left some comments on the code so that you understand what is happening at every stage.

Moving on.

On your `createPages` API call i saw that you're using the async version of it, which is a good thing to use , not to create a "bottleneck" when the build process is running.

Now, one thing that you should be aware, is that you should have some sort of exception treatment, you cannot assume the principal that all of the code will work nicelly and you'll get a build, more even based on the fact that some exceptions might be a bit cryptic.
A simple way to implement this would be to implement it like so, in this case you have a rudimentary way of handling exceptions that might happen. Once more i left some comments on the code so that you can understand what is happening at every step.

```javascript
exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions
  const blogTemplate = path.resolve("./src/templates/blog.js")
  // equivalent to the approach provided as each of them would return the same (a promise)
  // but with this you have error checking.
  // with your approach it would be wise to add exception treatment.
  return graphql(
    `
      {
        allMarkdownRemark {
          edges {
            node {
              fields {
                slug
              }
            }
          }
        }
      }
    `
  ).then(result => {
    // checks for errors in graphql and throws them
    if (result.errors) {
      throw result.errors
    }
    //

    // destructures the data needed, namely gets only the data needed and works on it
    // avoids using dot notation to oblivion
    const { data } = result
    const { allMarkdownRemark } = data
    const { edges } = allMarkdownRemark
    //
    // iterates the array with the markdown retrieved from the graphql query and creates a page
    // for each item and passes in the slug(created below inside the onCreateNode api call )
    edges.forEach(edge => {
      createPage({
        path: `/blog${edge.node.fields.slug}`, // as the slug already is in the form of /slug/ only needs to adjust the endpoint like so
        component: blogTemplate,
        context: {
          slug: edge.node.fields.slug,
        },
      })
    })
  })
}
```
- Looked over your template in `./src/templates/blog.js` and only did a small adjustment to it. Once more i left some comments in the code.

```javascript
import React from "react"
import { graphql } from "gatsby"
import Layout from "../components/layout"
const Blog = props => {
  // destructuring like in gatsby-node.js to avoid dot notation to oblivion
  // as it might lead to some errors being thrown as some property is undefined.
  const { data } = props
  const { markdownRemark } = data

  return (
    <Layout>
      {/* <h1>{props.data.markdownRemark.frontmatter.title}</h1>
      <h1>{props.data.markdownRemark.frontmatter.date}</h1> */}
      <h1>{markdownRemark.frontmatter.title}</h1>
      <h1>{props.data.markdownRemark.frontmatter.date}</h1>
      {/* <div
        dangerouslySetInnerHTML={{ __html: props.data.markdownRemark.html }}
      /> */}
      <div dangerouslySetInnerHTML={{ __html: markdownRemark.html }} />
    </Layout>
  )
}

export const query = graphql`
  query($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      frontmatter {
        title
        date
      }
      html
    }
  }
`
export default Blog
```
A couple of items to finish if you don't mind.
- After all of this i was able to get a development build, but with one issue, more specifically a warning in `./src/components/footer.js`, so i adjusted it to the following:

```javascript
import React from "react"
import { graphql, StaticQuery } from "gatsby"

const Footer = () => {
  return (
    <StaticQuery
      query={graphql`
        {
          site {
            siteMetadata {
              author
            }
          }
        }
      `}
      render={data => {
        const { site } = data
        const { siteMetadata } = site
        return (
          <footer>
            <p>Created by {siteMetadata.author} aka Dr. Nana, &copy; 2019 </p>
          </footer>
        )
      }}
    />
  )
}
export default Footer
```
It's pretty much what you have but no warnings will be thrown, mentioning that the query could not be run or it is not cached.

- Finally and based on the item above. I saw that you're using `StaticQueries`, with the hook functional approach, which is really good, as it's one of the things i really like alot about Gatsby, as technically you can manipulate almost of the datum( images, content and so on) inside your site easily, you just create a string reflecting a object structure querying the data you want and you get it back and manipulate it as you see fit. But as all things, it comes with a cost, this case, your repository it's a small test case scenario and your approach is actually fine. But as projects tend to grow in a heartbeat the overuse of said queries might lead to some long build times and possibly to some issues with Gatsby further down the line. So a approach you could consider would be "Do i really need a graphql query here to fetch  the same information that is being fetched on a already defined component? Or could i move the query somewhere else and supply it via React props?". 

Sorry for the long comment, feel free to provide feedback so that we can close this issue or continue to work on it till we find a solution. Thanks for using Gastby 👍

**Comment by lsguillory** [comment]
Thanks for the tremendous effort you put into the feedback. I'm sorry so much trouble was caused by a comma. I reviewed those document I know 20 times and can't believe I missed it. I'm going to work on the other feedback you gave as I appreciate that also. I have a ways to go as, Yes, I am a newbie to gatsby but I'll keep trying to learn. Again, thanks and I will close this issue.
