### ISSUE TITLE
Gatsby source contentful / schema customization schema generation.

### ISSUE THREAD

**Issue by sami616** [gatsbyjs/gatsby#14206]
Hi, looking at the recent improvements made to the schema customization api: https://www.gatsbyjs.org/blog/2019-05-17-improvements-to-schema-customization/

It looks like a lot of the problems of using contentful with missing fields / references can be avoided by manually defining your schema. 

However, this seems like a lot of work for large and complex data models, is it possible for source plugins (contentful specifically ) to make use of this new api and perform this schema generation automatically for you behind the scenes? if so are there any plans in the works to make this possible?

**Comment by m-allanson** [comment]
Hey @sami616, there's a work-in-progress PR that should do this - check out:  https://github.com/gatsbyjs/gatsby/pull/12816

The work so far has been published to a temporary npm tag, install `gatsby-source-contentful@schema-types`. If you get a chance to try it out, please leave feedback on the PR!

**Comment by sami616** [comment]
@m-allanson amazing! thanks for the heads up!
