### ISSUE TITLE
Ignore merge commits in the PRs bot

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#14205]
## Summary

The PR bot at https://github.com/gatsbyjs/gatsby/tree/master/.github/actions/high-priority-prs is great for highlighting PRs that need attention. However sometimes there are false positives.

In the `PRs with new commits awaiting review` list, any pr that has merge commits will be incorrectly highlighted. Merge commits should be ignored by the bot. This could be done by ignoring commits with messages like:

- ignore `merge branch 'master'`
- ignore `merge remote-tracking branch`

### Motivation

False positives are annoying and make the bot less useful, let's get rid of them.

**Comment by sharat9211** [comment]
Hi, 
If nobody else is working, I am interested in taking up this issue.

**Comment by pieh** [comment]
Hey @sharat9211! It seems like @mkan0141 already opened PR that tackles this issue

**Comment by pieh** [comment]
#14352 was merged
