### ISSUE TITLE
Unable to use html.js present in theme package from example site

### ISSUE THREAD

**Issue by sonapraneeth-a** [gatsbyjs/gatsby#14221]
## Description

I've created a custom html.js in gatsby-theme-minimal package and am trying to see it's effect on the example site created. When running `yarn workspace gatsby-theme-minimal develop` for theme workspace, custom html.js seems to loaded, but when running the `yarn workspace example develop` command from example workspace, custom html.js is not getting used.

### Steps to reproduce

```
$ git clone https://github.com/sonapraneeth-a/gatsby-theme-bug
$ cd gatsby-theme-bug
<root-dir>$ yarn install
<root-dir>$ yarn workspace gatsby-theme-minimal develop
(Custom html.js loaded)
<root-dir>$ yarn workspace example develop
(Custom html.js not loaded)
```

### Expected result

(Please look at the developer console for expected result)
[See the attached screenshot](https://drive.google.com/file/d/1gOv3Ncb63zVYnSmn5oQxhK2uEoOV1ssF/view?usp=sharing)

### Actual result

(Please look at the developer console for actual result)
[See the attached screenshot](https://drive.google.com/file/d/1VWeAY1u8Suwz3DlUFIl0YeluUYd6PT9a/view?usp=sharing)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
>gatsby info --clipboard

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Softwares\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\Softwares\nodejs\npm.CMD
  Languages:
    Python: 3.7.1
  Browsers:
    Edge: 42.17134.1.0
```

**Comment by wardpeet** [comment]
This might be a bug, or at least a feature we haven't added yet.

Let me get some people involved who actually know more about this.

cc @ChristopherBiscardi, @jxnblk, @johno

**Comment by ChristopherBiscardi** [comment]
Would be feature we haven't added yet. (For the record, the handling for html.js is in the static entry: https://github.com/gatsbyjs/gatsby/blob/f338dfea534b21724b7d19dece8ee9f63a854f0f/packages/gatsby/cache-dir/static-entry.js#L35)

Given that no one has asked for it and it wouldn't be composable with other themes (ex: two themes have a custom html.js, what should happen?) I'd want to hear a good use case for it first that isn't covered by the lifecycle APIs before adding support.

**Comment by sonapraneeth-a** [comment]
Actually I was trying to implement a theme switcher and I wanted some styling attributes based on theme selected to be applied to `<body>` tag. But the `<body>` was present in html.js and was hence was using custom html.js file.

Is there any good idea with the current architecture on applying style attributes / class names to `<body>` based on theme selected?

**Comment by DSchau** [comment]
@sonapraneeth-a wouldn't [onRenderBody](https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody) work here? I'd need to know more about your specific use case to guarantee that's the best solution, but it seems like that would work just fine.

**Comment by sonapraneeth-a** [comment]
My current case is I want to switch themes (using emotion theming and react context apis) based on a checkbox input. I'm passing the theme props from root div to necessary child components. But I'm unable to pass an style props / classes to body (I want to mainly change the background color and foreground color of body based on theme selected) as it is present in html.js. I'm not sure if such a thing is possible using `onRenderBody`.

Do you have any other idea / workaround as a solution to my problem @DSchau ?

**Comment by jxnblk** [comment]
@sonapraneeth-a I've been using the `wrapRootElement` API to provide Emotion's theming context, then using the `<Global />` component to change the body's foreground and background colors. Would that potentially work for your use-case?

**Comment by sonapraneeth-a** [comment]
I'm trying the following but it is not working @jxnblk . I'm unable to use the theme set in ThemeProvider of emotion in Global styles. Any idea on how can it be done?

```
<ThemeProvider theme={computedTheme}>
<Global styles={css`
                body: {
                  background: ${props => props.theme.body.bg},
                  color: ${props => props.theme.body.fg}
                }
              `} />
</ThemeProvider>
```

**Comment by jxnblk** [comment]
@sonapraneeth-a I'm not 100% sure on the Emotion syntax you have, but I've done something like the following: 
```jsx
<Global
  styles={theme => ({
    body: {
      color: theme.colors.text,
      backgroundColor: theme.colors.background,
    }
  })}
/>
```

**Comment by sonapraneeth-a** [comment]
1. From the website(https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement …), I cannot understand if we can add React components in `wrapRootElement`. I want `ThemeProvider theme={}>` to have value based on checkbox selection.

 2. Do we have access to localStorage from `wrapRootElement`? @jxnblk

**Comment by DSchau** [comment]
@sonapraneeth-a gatsby-browser is run in the browser, so yes!

**Comment by sonapraneeth-a** [comment]
Hi @DSchau, @jxnblk  ,

It looks like I cannot use `useState()` or `this.state` in `wrapRootElement`. Is it true?

I'm doing something like the following but it is not working:

```
export const wrapRootElement = ({ element }) => {
  const [isDarkTheme, setIsDarkTheme] = useState(options.defaultTheme === 'dark');
  const computedTheme = (isDarkTheme === true)
      ? theme('dark')
      : theme('light');
  return (
    <ThemeProvider theme={computedTheme}>
      {element}
    <ThemeProvider>
    );
};
```

**Comment by wardpeet** [comment]
Technically this shouldn't be a problem but the problem is options.defaultTheme if not mistaken.

I believe you should add the default theme as a env variable. Could you try
```
process.env.GATSBY_DEFAULT_THEME = options.defaultTheme
```

**Comment by sonapraneeth-a** [comment]
Hi @wardpeet ,

Currently, I was using options from a js file with variables exported like

options.js
``` 
module.exports = {
  defaultTheme: 'dark'
}
```

However, I wanted options to come from ```__experimentalThemes``` which I do not know how to use. I could not find documentation on how to use options from 

```
module.exports = {
  __experimentalThemes: [
    {
      resolve: "gatsby-theme-blog",
      options: {},  <---
    },
  ],
}
```

So, can I use `useState()` or `this.state` in `wrapRootElement` as per the setting I've mentioned in this comment?

**Comment by jxnblk** [comment]
@sonapraneeth-a If I'm not mistaken, I think to use hooks you'll need to put them in a separate component that you can use in `wrapRootElement`. With your example above, it could look like this:

```jsx
const Root = props => {
  const [isDarkTheme, setIsDarkTheme] = useState(options.defaultTheme === 'dark');
  const computedTheme = (isDarkTheme === true)
      ? theme('dark')
      : theme('light');
  return (
    <ThemeProvider theme={computedTheme}>
      {element}
    <ThemeProvider>
  );
};

export const wrapRootElement = ({ element }) => {
  return (
    <Root>
      {element}
    </Root>
  );
};
```

**Comment by sonapraneeth-a** [comment]
Hi, 

Finally things are working as expected with your suggestion.  Closing the issue. I'll re-open if any related issue arises in future.

Thanks for your time and help.
