### ISSUE TITLE
Send structured errors through telemetry

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#14224]
Currently gatsby-telemetry sends a JSON string for errors.

This makes it difficult to identify what are reoccurring errors that Gatsby users are seeing.

To fix this, we should analyze errors and structure them before sending them off.

We can also enhance errors with more information e.g. at what point in the Gatsby lifecycle did the error happen? What plugin (if any) throw the error, etc.

This will be a good first step towards implementing structured error reporting https://github.com/gatsbyjs/rfcs/pull/37

**Comment by jamo** [comment]
I believe this has been implemented already
