### ISSUE TITLE
Tutorial Part 2?

### ISSUE THREAD

**Issue by awitherow** [gatsbyjs/gatsby#1422]
Is there a second part of the tutorial? I can only see Part one on the site...

<img width="1280" alt="screen shot 2017-07-08 at 18 04 57" src="https://user-images.githubusercontent.com/1827147/27987041-0493a3c4-6408-11e7-9dab-5c9a692e42fc.png">

**Comment by KyleAMathews** [comment]
Not yet, see the introduction. The other parts are coming soonish.
