### ISSUE TITLE
Hot reload fails when developer tools open in Chrome

### ISSUE THREAD

**Issue by martinpsz** [gatsbyjs/gatsby#14223]
I have noticed what appears to be a bug when developing in Gatsby and using the Chrome developer tools.

When I have the Chrome developer tools open (I am using Chrome 74), it appears that hot reloading stops working when the browser is refreshed. This is irrespective of whether there is an error thrown in the code or if the code was compiled successfully. What I see, when I refresh the browser, is a blank screen. Sometimes I am not refreshing the browser when the blank screen pops up during development with the developer tools open. I am able to clear the error, by closing the Chrome dev tools and refreshing the browser. 

I tried to recreate this same issue on Firefox but I don't see the same problem there. So it may be a Chrome specific setting or something. But I wanted to make you all aware in case it is a Gatsby issue.

**Comment by DSchau** [comment]
@martinpsz it's possible this is an extension issue.

Could you try in Incognito mode? Also--if you can reliably reproduce this, we'd love a video or some other means to see what's going on exactly here. I can't reproduce this locally!

**Comment by martinpsz** [comment]
I will record and post a video next time it happens. It might be a plug-in I have enabled in Chrome.

**Comment by DSchau** [comment]
Great!

In the absence of that--let's get this closed out. When you reply with that info, let's re-open and we'll help ya figure this out!

**Comment by martinpsz** [comment]
Here is what I am seeing in the console. Not sure if it is related. 

![Screen Shot 2019-05-22 at 6 56 15 PM](https://user-images.githubusercontent.com/8620006/58214395-8a2a3680-7cc3-11e9-9a16-0acee5d010cc.jpg)

Thanks for the help. I'll seek to reopen with video evidence if problem continues
