### ISSUE TITLE
Wrong className assegnation on build project

### ISSUE THREAD

**Issue by marcosilvestroni** [gatsbyjs/gatsby#14232]
## Description
During checking the media query with `react-responsive` when I build the project gatsby assigned to a div a wrong className , taked form the div above the wrong one. 

that's from the index.js
```
[...]
<div className="home-last">
            <h3 className="title-separator">{"Gli ultimi Annunci"}</h3>
            <UltimiAnnunci />
            <div className="scopritutti">
              <Link to={"/ricerca"}>
                <button className="control button">{`Scopri tutti gli annunci`}</button>
              </Link>
            </div>
          </div>
[...]
```

from UltimiAnnunci.js
```
import React from "react";
import { StaticQuery, graphql } from "gatsby";
import GridCarousel from "./gridCarousel";

const UltimiAnnunci = () => {
  return (
    <StaticQuery
      query={graphql`
        query {
          //retrieve data
      `}
      render={data => {
        return <GridCarousel data={data} node="ultimiAnnunci" />;
      }}
    />
  );
};

export default UltimiAnnunci;
```

from GridCarousel.js

```
import React from "react";
import PropTypes from "prop-types";
import { GridResults } from "./GridResults";
import MediaQuery from "react-responsive";
import { Carousel } from "react-responsive-carousel";
import Card from "./card";
import { settingsCarouselCards as settings } from "./_utility";

const GridCarousel = ({ data, node }) => {
  return (
    <MediaQuery
      minDeviceWidth={300}
      values={{ deviceWidth: 300 }}
      type="screen"
    >
      <MediaQuery maxWidth={450}>
        <Carousel {...settings} className="card-carousel">
          {data[node].edges.map((item, index) => {
            return <Card key={index} item={item.node} />;
          })}
        </Carousel>
      </MediaQuery>
      <MediaQuery minWidth={451}>
        <GridResults items={data[node].edges} className="search-results" />
      </MediaQuery>
    </MediaQuery>
  );
};

GridCarousel.propTypes = {
  data: PropTypes.object.isRequired,
  node: PropTypes.string.isRequired,
};

export default GridCarousel;
```

screenShot from develop
![Screenshot from 2019-05-22 12-10-16](https://user-images.githubusercontent.com/16466555/58166697-b1b0dd00-7c8a-11e9-9570-3e780b7ab0ae.png)

screenShot from build and gatsby serve
![Screenshot from 2019-05-22 12-09-02](https://user-images.githubusercontent.com/16466555/58166989-4ca9b700-7c8b-11e9-891a-56d50b15d93a.png)

**As you can see the className 'scopritutti' was assigned , but not from me!**

### Steps to reproduce

I cannot publish the repo now but I will create a repo test soon if requested

### Expected result

The html-tree shuold be the same in develop and build

### Actual result

The  html-tree shuold differs from develop to build

### Environment
```System:
    OS: Linux 4.15 Pop!_OS 18.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.13.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Firefox: 67.0
  npmPackages:
    gatsby: ^2.3.3 => 2.3.24 
    gatsby-image: ^2.0.35 => 2.0.39 
    gatsby-plugin-manifest: ^2.0.25 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.12 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-robots-txt: ^1.4.0 => 1.4.0 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.32 => 2.0.35 
    gatsby-plugin-sitemap: ^2.1.0 => 2.1.0 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.0.28 => 2.0.29 
    gatsby-source-mysql: ^1.0.0 => 1.0.0 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.18 
  npmGlobalPackages:
    gatsby: 2.3.23
```

**Comment by marcosilvestroni** [comment]
The strange thing is that if I remove 
```
<div className="scopritutti">
              <Link to={"/ricerca"}>
                <button className="control button">{`Scopri tutti gli annunci`}</button>
              </Link>
            </div>
```
everything works fine in develop and build

**Comment by DSchau** [comment]
Hello!

A [reproduction](https://gatsby.dev/reproduction) would indeed be helpful!

My _guess_ is that the MediaQuery component isn't SSR friendly, and so because `gatsby develop` is effectively a client-side app, and `gatsby build` is a statically rendered app that hydrates client-side, that that would explain the idiosyncrasy.

Thanks!

**Comment by marcosilvestroni** [comment]
> The strange thing is that if I remove
> 
> ```
> <div className="scopritutti">
>               <Link to={"/ricerca"}>
>                 <button className="control button">{`Scopri tutti gli annunci`}</button>
>               </Link>
>             </div>
> ```
> 
> everything works fine in develop and build


Also moving the link inside the "UltimiAnnunci" components solves the issue but it's the the best solution for other use cases

**Comment by mbwatson** [comment]
Unfortunately, this is also happening for me. I've been keeping an eye on #8560 and  #9911, but I think this is the real issue.

**Comment by marcosilvestroni** [comment]
Hi, everyone, I'm still here with the same problem, I changed the library but the issue remains so I created a repo to reproduce the problem.

here the repo https://github.com/marcosilvestroni/testMedia

to check the problem build the project and via the inspector have a look at the classnames of the divs when you change the device. If you reload the page the switch won't work properly, the problem is the same with react-media and also with react-media-match (that should support better SSR) or others. 

give me feedback please as soon as possible, thks

**Comment by marcosilvestroni** [comment]
@DSchau can you update the label tag?

**Comment by holmberd** [comment]
@marcosilvestroni this problem exist with `react-media`, as well as using media queries with `react-jss`, and will sometimes result in undesired `className` behaviour between development and production builds. This is not a new problem.

**Comment by SuperKleber** [comment]
I have the same problem, I only know that the person in charge is gatsby.browser.js and gatsby-ssr.js, if you don't use them everything is resolved

**Comment by rlaPHOENiX** [comment]
For anyone else having this issue, which I am, It seems to be in relation with the use of `<></>` as the root "element" of the component. If I change these to `div`'s it started to work again.

**Comment by gittestfor** [comment]
Still having the same problem and I dont use Fragments in Layout

**Comment by alexkurowski** [comment]
Just had this bug. One of my pages contained a context provider, and a class name of the last child leaked into a different page (wild). Wrapping all children of the provider in a div fixed it.

This issue shouldn't be closed.

**Comment by mcfadyeni** [comment]
I also just had this issue. I was wrapping my main index.js page in a fragment (<></>) and using gatsby-browser.js to add my Header.js and Footer.js. Changing the fragment to a <div> fixed it.
