### ISSUE TITLE
Allow React production build control

### ISSUE THREAD

**Issue by monsieurnebo** [gatsbyjs/gatsby#14230]
Hello,

We're working on multiple environments (local, dev, test, prod, sandbox), with specific configurations for each of them.

Using a custom `FOO_ENV` variable allow us to manage these configurations, except for one thing: the [React production build](https://reactjs.org/docs/optimizing-performance.html) setting. 

This setting is set in Webpack via:

```js
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify('production')
}),
```

In production mode, React will hide any errors... But we need to see them in some of our environments (e.g. `development`).  However, Gatsby is always setting `NODE_ENV` to `production` during a build.

**=> Is there any way of having a control over this setting, allowing us to set React in `development` mode for some environments?** 🤔

**Comment by wardpeet** [comment]
I don't think you can, you might be able to by using [replaceWebpackConfig](https://www.gatsbyjs.org/docs/add-custom-webpack-config/).

You can use webpack alias to replace react or react-dom to the development version or replace definePlugin with your own implementation. This is just speculation so it might not be possible at all.

**Comment by monsieurnebo** [comment]
We already used `replaceWebpackConfig`, but that's really not a durable solution (any major change from Gatsby original config could break the project).

Not sure about the Webpack alias thing 🤔 

I just give it a try to the third idea, but our `NODE_ENV` has already been overwritten by the Gatsby's one, and I have to idea of which one it should be at this moment.

**Comment by wardpeet** [comment]
We set the NODE_ENV inside gatsby-cli so not using it might easily fix your issue.
https://github.com/gatsbyjs/gatsby/blob/67ff2b993a564dc339b7bfc09e8a582e6876e970/packages/gatsby-cli/src/create-cli.js#L196

preInit should works too if you know what env you are in. You could create a diff env var that you use to overwrite NODE_ENV
