### ISSUE TITLE
Adding .md files to starter kit does not work

### ISSUE THREAD

**Issue by timurc** [gatsbyjs/gatsby#1423]
Hey, first thanks for all the hard work put into this. After several projects with 0.x, I finally took the time to check out 1.0.

The getting startet states in point 4 "Try editing markdown and javascript files. Saved changes will live reload in the browser.". Markdown files wont work though, because the starter kit does not have a template and a `gatsby-node.js`. I figured out how to get it working, but I guess this guide should either not mention markdown, or the starter kit should have this working. 

If needed, I could create a pull request for the starter kit to add this, but I was not sure if it might be deliberately left out in the starter kit to keep it simple.

**Comment by KyleAMathews** [comment]
Oh yeah, that's outdated. Ooops. Removed in https://github.com/gatsbyjs/gatsby/commit/c27f6aeb7235418df737438c9b335779ea8ae075

There is a starter blog with markdown support https://github.com/gatsbyjs/gatsby-starter-blog

**Comment by KyleAMathews** [comment]
I assume you saw the upgrade guide! Looking forward to your 1.0 sites :-D

**Comment by timurc** [comment]
Yep, saw the migration guide! Will open more issues when i stumble upon them :)
