### ISSUE TITLE
gatsby-source-wordpress should decode HTML entities on import

### ISSUE THREAD

**Issue by g-elwell** [gatsbyjs/gatsby#14239]
## Summary

The WordPress REST API encodes HTML entities (eg `’` as `&#8217;`) and the `gatsby-source-wordpress` plugin pulls these into Gatsby.

The result is that if your WordPress content contains any HTML entities, you will need to either use `dangerouslySetInnerHTML`, or decode strings before using them within your Gatsby components.

### Motivation

If HTML entities are decoded by the `gatsby-source-wordpress` plugin at import time, your content will display as expected when you come to use it within Gatsby.

### Proposed solution

I looked to the source of `gatsby-source-wordpress` for inspiration and wrote a custom normalizer similar to `searchReplaceContentUrls` which converts entities to strings and uses the [he](https://github.com/mathiasbynens/he) library to decode them.

```
const he = require('he');
const _ = require('lodash');

function decodeHtml({ entities }) {

  const _blacklist = [`_links`, `__type`];

  const blacklistProperties = function(obj = {}, blacklist = []) {
    for (var i = 0; i < blacklist.length; i++) {
      delete obj[blacklist[i]];
    }
    return obj;
  };

  return entities.map(function(entity) {
    const original = Object.assign({}, entity);
    try {
      var whiteList = blacklistProperties(entity, _blacklist);
      var replaceable = JSON.stringify(whiteList);
      var replaced = he.decode(replaceable);
      var parsed = JSON.parse(replaced);
    } catch (e) {
      console.log(e.message);
      return original;
    }
    return _.defaultsDeep(parsed, original);
  });

}

module.exports = decodeHtml;

```

This issue had me stumped for a while and I couldn't find any discussion on it. I'm not sure if that means I'm doing something wrong or the problem is niche and confusing enough to not be reported yet.

In any case I thought I'd let you know as it may be something to consider building into the plugin.

**Comment by pieh** [comment]
Does this happen just on output from WYSIWYG editor fields (like `content`) or on different fields as well? For content (etc) it would be expected to use `dangerouslySetInnerHTML` as it would contain html tags (like `<p>`) which wouldn't render correctly without it.

**Comment by g-elwell** [comment]
It's on non WYSIWYG fields too. I first noticed it on a `title` that was using an apostrophe, as I'm using `dangerouslySetInnerHTML` for `content` myself.

**Comment by lightstrike** [comment]
@g-elwell I've hit this issue with `title` as well. I've just ended up using `dangerouslySetInnerHTML`, it would be good to fix this though :smile:

**Comment by bogdancss** [comment]
I am using `html-react-parser` for title as well  -  would be nice to get this decoded

**Comment by PierreMouchan** [comment]
> ## Summary
> The WordPress REST API encodes HTML entities (eg `’` as `&#8217;`) and the `gatsby-source-wordpress` plugin pulls these into Gatsby.
> 
> The result is that if your WordPress content contains any HTML entities, you will need to either use `dangerouslySetInnerHTML`, or decode strings before using them within your Gatsby components.
> 
> ### Motivation
> If HTML entities are decoded by the `gatsby-source-wordpress` plugin at import time, your content will display as expected when you come to use it within Gatsby.
> 
> ### Proposed solution
> I looked to the source of `gatsby-source-wordpress` for inspiration and wrote a custom normalizer similar to `searchReplaceContentUrls` which converts entities to strings and uses the [he](https://github.com/mathiasbynens/he) library to decode them.
> 
> 
> ```
> const he = require('he');
> const _ = require('lodash');
> 
> function decodeHtml({ entities }) {
> 
>   const _blacklist = [`_links`, `__type`];
> 
>   const blacklistProperties = function(obj = {}, blacklist = []) {
>     for (var i = 0; i < blacklist.length; i++) {
>       delete obj[blacklist[i]];
>     }
>     return obj;
>   };
> 
>   return entities.map(function(entity) {
>     const original = Object.assign({}, entity);
>     try {
>       var whiteList = blacklistProperties(entity, _blacklist);
>       var replaceable = JSON.stringify(whiteList);
>       var replaced = he.decode(replaceable);
>       var parsed = JSON.parse(replaced);
>     } catch (e) {
>       console.log(e.message);
>       return original;
>     }
>     return _.defaultsDeep(parsed, original);
>   });
> 
> }
> 
> module.exports = decodeHtml;
> ```
> 
> This issue had me stumped for a while and I couldn't find any discussion on it. I'm not sure if that means I'm doing something wrong or the problem is niche and confusing enough to not be reported yet.
> 
> In any case I thought I'd let you know as it may be something to consider building into the plugin.

I was wondering if someone has any solution to that, i still encounter the problem of html entities and i don't understand how to use 'your solution' @g-elwell :) thanks.

**Comment by g-elwell** [comment]
Hey @PierreMouchan 

The code I included above will handle decoding the html, to get `gatsby-source-wordpress` to run this on build, you need to add it as a normalizer in the plugin options.

The normalizer option will essentially run all of your data through a function and return the output.

So save that function somewhere, then require it in your `gatsby-config.js` and add it to the plugin config:

```
const { decodeHtml } = require('./gatsby/utils');

module.exports = {
...existing config
{
      resolve: 'gatsby-source-wordpress',
      options: {
        ...existing settings
        normalizer: decodeHtml,
      }
    }
```

**Comment by PierreMouchan** [comment]
> Hey @PierreMouchan
> 
> The code I included above will handle decoding the html, to get `gatsby-source-wordpress` to run this on build, you need to add it as a normalizer in the plugin options.
> 
> The normalizer option will essentially run all of your data through a function and return the output.
> 
> So save that function somewhere, then require it in your `gatsby-config.js` and add it to the plugin config:
> 
> 
> ```
> const { decodeHtml } = require('./gatsby/utils');
> 
> module.exports = {
> ...existing config
> {
>       resolve: 'gatsby-source-wordpress',
>       options: {
>         ...existing settings
>         normalizer: decodeHtml,
>       }
>     }
> ```

Thank for the reply ! 

I tried many times your solution and it still doesn't work ? 😕
```json
          "slug": "agence",
          "title": "L&rsquo;Agence"
```
still got the html entities in the response, i'm sorry !

**Comment by g-elwell** [comment]
Did you restart Gatsby? You need to do this to rebuild the data

**Comment by PierreMouchan** [comment]
> Did you restart Gatsby? You need to do this to rebuild the data

Yeah i restarted gatsby, i also tried normalizers (array of normalizer) instead of normalizer, html entities remains inside my graphql queries. 

EDIT: i tried to directly use it as a anonymous function and it works ! thank you again for your time !
```javascript
normalizer: ({ entities }) => {
      const _blacklist = [`_links`, `__type`]

      const blacklistProperties = function (obj = {}, blacklist = []) {
        for (var i = 0; i < blacklist.length; i++) {
          delete obj[blacklist[i]]
        }
        return obj
      }

      return entities.map(function (entity) {
        const original = Object.assign({}, entity)
        try {
          var whiteList = blacklistProperties(entity, _blacklist)
          var replaceable = JSON.stringify(whiteList)
          var replaced = he.decode(replaceable)
          var parsed = JSON.parse(replaced)
        } catch (e) {
          console.log(e.message)
          return original
        }
        return _.defaultsDeep(parsed, original)
      })
    },
```

**Comment by PierreMouchan** [comment]
> > Did you restart Gatsby? You need to do this to rebuild the data
> 
> Yeah i restarted gatsby, i also tried normalizers (array of normalizer) instead of normalizer, html entities remains inside my graphql queries.
> 
> EDIT: i tried to directly use it as a anonymous function and it works ! thank you again for your time !
> 
> 
> normalizer: ({ entities }) => {
>       const _blacklist = [`_links`, `__type`]
> 
>       const blacklistProperties = function (obj = {}, blacklist = []) {
>         for (var i = 0; i < blacklist.length; i++) {
>           delete obj[blacklist[i]]
>         }
>         return obj
>       }
> 
>       return entities.map(function (entity) {
>         const original = Object.assign({}, entity)
>         try {
>           var whiteList = blacklistProperties(entity, _blacklist)
>           var replaceable = JSON.stringify(whiteList)
>           var replaced = he.decode(replaceable)
>           var parsed = JSON.parse(replaced)
>         } catch (e) {
>           console.log(e.message)
>           return original
>         }
>         return _.defaultsDeep(parsed, original)
>       })
>     },
> I will look around to see what's the problem but your answer is working ! good job ! 💪

Edit: This add like 400 kb to the final bundle of your app because it import the whole he and lodash library ! I try to find a work-around to these libraries.

**Comment by nathanpate** [comment]
# Solution
Under the guidance of [this gist](https://gist.github.com/esamattis/54abd801b078056f9e646d63d47ccc4c?permalink_comment_id=3630080#gistcomment-3630080),
and according to [this dev doc of WP Graphql plugin's official site](https://www.wpgraphql.com/filters/graphql_html_entity_decoding_enabled/),
add this line to `functions.php`:
```php
add_filter( 'graphql_html_entity_decoding_enabled', '__return_true' );
```
would decode any HTML Entity.

# My Case
### Before:
```graphql
{
  "data": {
    "allWpPost": {
      "nodes": [
        {
          "id": "cG9zdDoxOQ==",
          "title": "This Is How Twitter Edit Button Can Actually Work",
          "excerpt": "<p>&#8230;The ability to edit tweets is coming but it&#8217;s full of risks and this is how to do it right&#8230;</p>\n"
        },
      },
   },
}
```
### After
```graphql
{
  "data": {
    "allWpPost": {
      "nodes": [
        {
          "id": "cG9zdDoxOQ==",
          "title": "This Is How Twitter Edit Button Can Actually Work",
          "excerpt": "<p>…The ability to edit tweets is coming but it’s full of risks and this is how to do it right…</p>\n"
        },
      },
   },
}
```
