### ISSUE TITLE
NPM Gatsby Cli install error

### ISSUE THREAD

**Issue by donaldboulton** [gatsbyjs/gatsby#14242]
Npm install instructions for Gatsby cli is `npm i gatsby` = will not install in Windows 10 and had to reinstall npm after this mess up.
Should it not be `npm i -g gatsby`?

**Comment by DSchau** [comment]
@donaldboulton could you provide more detail for this statement?

> Npm install instructions for Gatsby cli is npm i gatsby

Where did you see this?

**Comment by donaldboulton** [comment]
At [NPM](https://www.npmjs.com/package/gatsby)

**Comment by DSchau** [comment]
@donaldboulton got it--sorry for the confusion!

There's not a ton we can do there--that's the baked in UI for npmjs.org. If you have ideas for how we could improve these--we'd love a PR!

In general, we recommend starting with our [tutorial](https://www.gatsbyjs.org/tutorial/), particularly the ["Setup your Development Environment" section](https://www.gatsbyjs.org/tutorial/part-zero/) for getting up and running quickly with Gatsby.

Thanks, and again sorry for the confusion!
