### ISSUE TITLE
Page and animations become junky after browsing a few pages

### ISSUE THREAD

**Issue by dragonflypl** [gatsbyjs/gatsby#14247]
## Summary

I've created Gatsby portfolio site: https://2m2.dragonflypl.now.sh/ (this is test version, still work in progress).

I'm testing it and I've already realized that on mobile it very quickly becomes junky. Initially, animations/transitions are smooth (e.g. menu) but after browsing pages in the portfolio section, when I toggle menu (with icon) animation is dreadfully slow.

Are there any techniques to speed it up in Gatsby? I assume that things pile up in the memory (images etc) and browser process just slows down.

gatsby

**Comment by DSchau** [comment]
@dragonflypl could you provide a set of steps you take to reproduce the slowness? e.g. start here, open the menu, click this link, etc.

**Comment by dragonflypl** [comment]
1. Goto main page
2. Open menu -> Goto portfolio
3. Click on first project (image) and go to details
4. Scroll down and click "Następny Projekt" to go to next project, and do the same until all projects are browser
5. Now open menu once again - animation is junky

**Comment by DSchau** [comment]
I'm not really sure--I just tried that on my iPhone and couldn't replicate.

That being said, running a Lighthouse test surfaces some useful findings, specifically:

> Does not use passive listeners to improve scrolling performance

Are you perhaps registering event listeners (e.g. scroll, mousewheel, etc.) and then not deregistering them? Or perhaps registering for _lots_ of events or something?

> Includes front-end JavaScript libraries with known security vulnerabilities

Looks like you're using jQuery 2.2.0 for something (and Modernizer, which is quite a heavy dep)? Generally - would recommend avoiding additional libraries if you can avoid them. jQuery usually isn't needed as often as it used to be--but not knocking it if you find it useful!

Generally - it's not really possible for us to debug this in the absence of a [reproduction](https://gatsby.dev/reproduction) so if you can supply that we could take a look. In general -- this does not seem to be a Gatsby bug, but is rather an issue with loading too much JavaScript and/or something like a non-performant event listener or set of event listeners.

**Comment by dragonflypl** [comment]
Ok, thanks. Yeap, this is adoption of some themeforest template which is quite old. I'll update stuff soon.
Thank you for looking into it.

Btw... I have also issue with preloading. E.g. I'm using Link component but it seems that Gatsby does not preload anything (e.g. when I hover over Portfolio link on Desktop). Is it normal behavior i.e. Gatsby can decide not to preload?

**Comment by DSchau** [comment]
@dragonflypl no. The Gatsby Link component preloads content when it's in the browses viewport, and then fetches that content when it's hovered (e.g. on desktop).

You can check your head tags to see what's happening there:

<img width="737" alt="Screen Shot 2019-05-22 at 3 38 27 PM" src="https://user-images.githubusercontent.com/3924690/58207132-af10b080-7ca7-11e9-8d54-392e056377a5.png">

Going to close as answered--thanks! Please reply if we can help further.
