### ISSUE TITLE
How to apply --prefix-paths to links generated from Frontmatter.

### ISSUE THREAD

**Issue by oldmannseamus** [gatsbyjs/gatsby#14248]
I'm using frontmatter properties to store data for conversion into fields at build time. I've successfully used Remark on these fields in order to handle formatting and links, but any links processed from these fields do not receive prefixes when the `--prefix-paths` flag is used.

I've gotten around this for the time being by hardcoding the absolute paths of these links, but I'd prefer to find a way to pass prefixes to Remark. Here's the relevant block in my gatsby-node.js file:
```
// Create fields for Ability Actions from Frontmatter.
const actions = node.frontmatter.actions
Object.keys(actions).forEach((key) => {
  // Process using Remark.
  Remark().use(html).process(actions[key]).then(result => {
    // Create field.
    createNodeField({
      node,
      name: key,
      value: result.contents
    })
  })
})
```

Any thoughts on how to get path prefixing to operate on links included in frontmatter?

Couple of details that may or may not be relevant:
- I have `gatsby-plugin-catch-links` running successfully.
- The Remark() invocation above is imported from the `remark` package directly rather than the `gatsby-transformer-remark` plugin, as the latter produced a typeerror when called. I'd prefer to use the gatsby transformer instead, if that's possible.

**Comment by DSchau** [comment]
@oldmannseamus could you provide a little more detail as to what you're doing in gatsby-node.js? Does `result.contents` contain links that aren't prefixed?

We expose `pathPrefix` and `basePath` (which is actually what pathPrefix is now that we've created the [assetPrefix functionality](https://www.gatsbyjs.org/docs/asset-prefix/) to our plugin APIs, e.g.

```jsx
exports.onCreateNode = function onCreateNode({ pathPrefix, basePath = pathPrefix }) {
 // use basePath to replace links as you wish
 // e.g. you would visit each a tag, and replace the href with basePath + href
}
```

If you could supply a [reproduction](https://gatsby.dev/reproduction) one of us could probably help more with the separate question re: gatsby-transformer-remark (which should have links prefixed as you'd expect).

**Comment by oldmannseamus** [comment]
Thanks, @DSchau.

`result.contents` contains a string that may or may not include markdown formatting, including links. These links are not prefixed when the process completes.

I'm pulling together a repro now and will link it when it's complete. The operative issue appears to be user error: `gatsby-transformer-remark` doesn't export anything, so I'm likely not using it the way it's meant to be.

**Comment by oldmannseamus** [comment]
I'm actually going to close this; I've made some discoveries while making the repro.

1. @DSchau's suggestion above re: `pathPrefix` being exposed allowed me to operate on links inside of `result.contents` during the `onCreateNode` process, fixing the problem.
2. The purpose of my using Frontmatter in this way was to emulate the use of "fields" in my content, allowing me to populate a template with specific portions of my content. In reading the documentation on creating a reproduction, I was made aware of [the MDX plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/), which is specifically designed to provide this featureset and does so in a much more coherent way. I'll be converting my application to use this instead.

Thank you!
