### ISSUE TITLE
Material-UI Plugin page preview is blank

### ISSUE THREAD

**Issue by webdevpchoi** [gatsbyjs/gatsby#14249]
When searching for Material UI in the plugins, upon clicking on the result, nothing shows up in the preview pane like the other plugins. I'm currently working around this by going directly to the github link, but I just thought I'd let you know!

Using Chrome Version 74.0.3729.169

![image](https://user-images.githubusercontent.com/21182531/58200543-d9eb0c80-7c87-11e9-9ccd-7f0edd871661.png)

**Comment by DSchau** [comment]
Ugh, that's unfortunate!

We rely on Algolia (and specifically docsearch) for that functionality, and there's occasionally some intermittent misses when the READMEs for those packages are parsed from their end.

If you're curious, the code for how we generate those pages is encapsulated in [`gatsby-source-npm-package-search`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-npm-package-search)

Going to be a little hand-wave-y here and close this as it's a little out of our control, but that being said--we appreciate you opening this issue and letting us know. Hopefully this will be resolved the next time the [Algolia index](https://github.com/algolia/npm-search) is updated, which is hopefully soon.

**Comment by webdevpchoi** [comment]
Awesome, thank you for your input Dustin!
