### ISSUE TITLE
[bug]: Avoiding "plugin has generated no Gatsby nodes. Do you need it?"

### ISSUE THREAD

**Issue by kwiechmann** [gatsbyjs/gatsby#14255]
## Description

Have run across more than a few Gatsby examples working with remote images and needing to apply the blur up effect (e.g., https://www.wildsmithstudio.com/blog/remote-images-with-gatsby/ by Matthew Smith). The examples typically hook into `exports.sourceNodes` but this results in a "no Gatsby nodes generated" warning message appearing in the Gatsby startup information. Since multiple examples fail to mention it in their posts, believe that the warning message was added since examples were written.

Found that warning message to be misleading. This warning occurs unless the `exports.sourceNodes` includes at least one `createNode()` call. Being new to Gatsby, I am not sure if remote file nodes are considered a sub class of Gatsby nodes. I found that any calls to `createRemoteFileNode()` do not suppress the warning message either. Must be at least one call to `createNode()`.

An aside, I did look at `gatsby-plugin-remote-images`. This plugin assumes that the remote images to blur up can be found in a string field of another node. I can see valid user stories to associate images with specific content but this seems wasteful. This is not a good match for pages that are custom/less structured (landing page) versus a more structured product page.

### Steps to reproduce

1. Begin with your favorte standard Gatsby starter.
2. Follow instructions through updating `gatsby-config.js` to build a plugin like `instafeed.js`: https://www.wildsmithstudio.com/blog/remote-images-with-gatsby/
3. Execute `gatsby develop`
4. Review log output on screen.

### Expected result

For plugins that do not need to create any nodes, the warning message leads to confusion. Ideally, the messages should be automatically suppressed or be suppressible without taking the counter measures. 

### Actual result

```
...
warn The gatsby-source-pixabay plugin has generated no Gatsby nodes. Do you need it?
...
```

### Workarounds

1. Ignore. Maybe one just needs to know. This however does not fit with Gatsby mantra to make things easy. *
2. Add a way to suppress the warning by developers when appropriate. **
3. Add a fake node using createNode() and then immediately removing the fake node using deleteNode(), Gatsby will not include the error message in the output. 10+ lines of code should need either just work or be replaced with a one liner of code. **
4. Switch hooks from `sourceNodes` to `onPreBootstrap`. While this worked for me, everyone's "individual mileage may vary" as there may be other applications unable to hook switch. ***

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.0.2 - /usr/local/bin/bash
  Binaries:
    Node: 10.15.2 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.6.0 => 2.6.0 
    gatsby-image: ^2.0.41 => 2.0.41 
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6 
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3 
    gatsby-plugin-offline: ^2.1.0 => 2.1.0 
    gatsby-plugin-remote-images: ^1.0.1 => 1.0.1 
    gatsby-plugin-remove-trailing-slashes: ^2.0.11 => 2.0.11 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.37 => 2.0.37 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
    gatsby-remark-images: ^3.0.11 => 3.0.11 
    gatsby-source-filesystem: ^2.0.34 => 2.0.34 
    gatsby-transformer-json: ^2.1.11 => 2.1.11 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
    gatsby-transformer-remote-image: ^2.0.1 => 2.0.1 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 
  npmGlobalPackages:
    gatsby-cli: 2.6.0

CC: @prestonso

**Comment by DSchau** [comment]
Hello!

Thanks for this question.

The `sourceNodes` API should be used (as its name would indicate) to create nodes. A remote file node is a special type of node in Gatsby, which does not trigger the create node hook/check as you noted.

In this example, it seems like that blog post is giving slightly misleading information. What I would rather recommend here (instead of overloading node fields) is to _actually_ create Instagram nodes, and then associate the remote file node with that created node.

This is sort of pseudo code (can't really test it easily!), but it hopefully illustrates the recommended practice of sourceNodes, which is to create nodes. You'll likely want to tinker with this to get it working perfectly, but the general idea is that we should:

1. Create nodes of type `InstagramImage` (rather than using createNodeField)
1. Create an image reference on the created `InstagramImage` node

It looks something like (in gatsby-node.js):

```js
const {createRemoteFileNode} = require(`gatsby-source-filesystem`);
const axios = require('axios');
const _ = require(`lodash`)

// Replace ACCESS_TOKEN with your Instagram token
const API_URI =
  'https://api.instagram.com/v1/users/self/media/recent/?access_token=ACCESS_TOKEN';


exports.sourceNodes = async ({ actions, createNodeId, createContentDigest }) => {
  const { createNode } = actions

  const {data} = await axios.get(API_URI);

  for (const image of data.data) {
    try {
      const instagramNode = _.omit(node, ['images']) // these aren't really useful and aren't optimized; let's remove them

      const node = Object.assign({
        id: createNodeId(`instagram-source-${instagramNode.key}`), // note: some unique identifier here, I'm not familiar with the data source
        parent: null,
        children: [],
        internal: {
          type: `InstagramImage`,
          contentDigest: createContentDigest(instagramNode)
        }
      }, instagramNode) // now we can query for any of the data on the API response for an image

      createNode(node)

      const imageNode = await createRemoteFileNode({
        url: image.images.standard_resolution.url,
        cache,
        store,
        createNode,
        parentNodeId: node.id,
        ext: '.jpg',
      });

      node[`image___NODE`] = imageNode.id
    } catch (error) {
      console.warn('error creating node', error);
    }
  }
}
```

Now we can query for e.g. `allInstagramImage` and additionally get the optimized images we love and expect when using Gatsby.

I hope this helps, please reply or re-open if we can help further.

Thanks!
