### ISSUE TITLE
Couldn't find preset "es2015"

### ISSUE THREAD

**Issue by jaubut** [gatsbyjs/gatsby#1425]
I got this error everytimes I try to run gatsby develop.. I try to run a local npm install.. Nothing..

**Comment by bencodezen** [comment]
@jaubut what happens when you run `./node_modules/.bin/gatsby develop`? i found that trying to run `gatsby develop` through the global package didn't quite work as expected.

**Comment by jaubut** [comment]
I had a .babelrc file and had `{"presets": ["react", "es2015", "stage-0"]}` and it solve the problem :)

**Comment by bencodezen** [comment]
@jaubut glad to hear!

**Comment by ozymandias547** [comment]
Why isn't this part of the install...
