### ISSUE TITLE
[ WIP ] gatsby-starter-i18n-bulma (starter in development)

### ISSUE THREAD

**Issue by kalwalt** [gatsbyjs/gatsby#14250]
Hi, i am Walter, I am an italian :it:  self-made developer. I want to show my starter [gatsby-starter-i18n-bulma](https://github.com/kalwalt/gatsby-starter-i18n-bulma) i developed for my new personal website, but  i would share with you. Time ago I searched a multilingual starter, but i didn't find what i was looking for. Most of them don't let much freedom when you switch from one language to another.

 I used the [gatsby-plugin-i18n](https://github.com/angeloocana/gatsby-plugin-i18n) but i developed a system to switch between pages assigning a id number to every pair page and storing the list in a Json file. 
  ```json
  {
      "id": "03",
      "en": "about",
      "it": "presentazione"
    },
```
 https://github.com/kalwalt/gatsby-starter-i18n-bulma/blob/60ba308f6c0de27816ce2a0c57cbf901938def1b/src/data/articles/articles.json#L13-L17

in this way you can assign different names to the pages:

`/en/about/`   is linked to   `/it/presentazione/`

I love :heart:  the [Bulma](https://bulma.io) :1st_place_medal:  project and was funny  to play with this amazing CSS library. I have to learn still a lot, but i hope to improve it. 
Anyway my reference was the [gatsby-starter-netlify-cms](https://github.com/netlify-templates/gatsby-starter-netlify-cms), without this starter i think nothing would happens!
I want to know if this could be added in a future :robot:  in the Gatsby starter collection, and if you have suggestions, comments, criticisms or improvements that can be made to the code, I would be happy :smile:  to receive.
Thanks for your attention,
Walter

**Comment by DSchau** [comment]
Hello Walter!

We're so glad to have you here, and we love that you put together a starter.

We'd love to accept your submission to our Starter Library. You can read more about doing so [with this documentation for adding to the Starter Library](https://www.gatsbyjs.org/contributing/submit-to-starter-library/).

We look forward to your pull request!

Thanks!

**Comment by kalwalt** [comment]
Thank you @DSchau I will think about it!
