### ISSUE TITLE
[v1 -> v2] Problems with module imports after migration.

### ISSUE THREAD

**Issue by chvas-navi** [gatsbyjs/gatsby#14268]
## Description

*SHORT*: After migration from v1 to v2, for some imported modules, contents is differ to what was before migration.

*DETAILS* (for now, only related to problem):
1. There is some project that use **Gatsby**, **React**, **Typescript** and other packages (**firebase**, **match-sorter**, **qs**, **moment**, other) (all yarn (npm) packages).
2. To it, were applied migration from here https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/ .
3. After this, such error occured: `WebpackError: TypeError: Cannot read property 'GoogleAuthProvider' of undefined`, in the line `= new firebase.auth.GoogleAuthProvider()`.
4. After some investigation I collected this related data:
    1. This occurred, for file where firebase imported like this - `import * as firebase from "firebase/app"`.
    2. If before migration `firebase` contains `X`, then after it contains `{default: X}`. Also after migration there no `INTERNAL: node: {}` property in firebase.
    3. This also occurred for **match-sorter**. But **not** for **React**, **qs** and **moment** (all of them imported in this same way).
    4. From all changes that happened during migration, I think, source of problem must be in "version changes" in: `gatsby (1.9.259 -> 2.4.3)` and/or `gatsby-plugin-typescript ( 1.4.18 -> 2.0.13)`. With them there a lot what installed as dependencies (`babel-loader` (6.4.1 -> 8.0.6), `babel-core` (6.26.0) -> `@babel/core` (7.4.4), other).
5. So first of all, I want to ask the question: what can cause such behavior? Where can be *root of the problem*, what package do this?
6. People tried to solve this problem, also searching "in the internet" (:-)), but for now unsuccessfully.
7. What can be done, is maybe manually get from imported module `X`, by referring the **default**, but is there any other solution.

### Steps to reproduce

In near future I will add here project to reproduce the problem. But before, I want to look maybe description is enough.

### Expected result

Project must run (`develop`, `build`).

### Actual result

Error, because of changed content of  imported module.

### Environment

Will be putted later, when there is `test project`.

**Comment by DSchau** [comment]
Hello!

This will be a bit more difficult to trace down in the absence of a [reproduction](https://gatsby.dev/reproduction) so in the interest of allowing us to help you most effectively, I'd strongly suggest you provide one if you're able!

That being said, I have a few questions:

1. Did you also upgrade Firebase? Perhaps it changed how it was distributed/packaged?
1. Have you checked out [this Firebase starter](https://github.com/the-road-to-react-with-firebase/react-gatsby-firebase-authentication)? It may help you get on the right track re: the correct imports and instantiation of various Firebase classes

Thanks!

**Comment by chvas-navi** [comment]
Hi @DSchau . Thanks for reply.

**My answers:**
1. For now I can't give reproduction. But maybe in near future.
2. `Did you also upgrade Firebase?` - please see **Addition-1** higher.
3. I tried to use `babel-plugin-add-module-exports`, didn't work and broke other import.
4. `Have you checked out this Firebase starter?` - thanks, but for now, I am searching such solution, that not need changing of firebase version.

**Some questions:**
I understood that hard to help without reproduction. This is clear to me. But for now, wanted to ask:
1. Is there possibility to force **Webpack** do next. If must be used for resolution file like this -`x.esm.js`, then force to check is there file like `x.cjs.js` in same folder, and only on absence use first.
2. Or maybe force to check first for files `*.cjs.js`, and after on other default pathes (tried to use `resolve: extensions: ["*.cjs.js", "*"]` and didn't work).
3. Maybe here is bad place for sucn **Webpack** questions. I see.

**Comment by chvas-navi** [comment]
Hi @DSchau . Thank you for fast response, and sorry for my late answer.
Such happened that for now, people will work on the problem by themselves. And there no need to bothering your team. It seems like, I hurried up with this issue, I am sorry.

Answers, that not actual now:

0) About reproduction I understood. Ok.
1) `Did you also upgrade Firebase?` - Nope. During migration version of this packages has been not changed: **firebase**, **match-sorter**, **qs**, **moment**.
2) `Have you checked out this Firebase starter?` - Thanks for resource. But for now is searched for solution that not cause changes in code that use firebase.

I close the issue for now. Later, if help will be needed, I'll reopen it. And again, thank you.
