### ISSUE TITLE
Use jQuery plugins 

### ISSUE THREAD

**Issue by akzhy** [gatsbyjs/gatsby#14265]
## Summary

I am in a situation where I need to use a couple of jQuery plugins like owl carousel.
But I can't just import them as I get the error
`TypeError: Cannot read property 'fn' of undefined`

## Relevant information

I tried importing them as follows

`import $ from "jquery"`

and 

`import owlCarousel from "owl.carousel"`

What is the proper way to import jQuery so that other plugins can be used ?

**Comment by DSchau** [comment]
@akzhy would you be able to supply a [reproduction](https://gatsby.dev) for what you've tried thus far? Even in a broken state--it would be a helpful basis for us to get started with.

In general, I think you'll want to do something like this in *gatsby-node.js* to inform Webpack of the jQuery global.

```js
exports.onCreateWebpackConfig = ({
  actions,
}) => {
  const { setWebpackConfig } = actions;
  setWebpackConfig({
    externals: {
      jquery: 'jQuery', // important: 'Q' capitalized
    }
  })
}
```

**Comment by akzhy** [comment]
Thank you, but that didn't work.
Anyway I ended up using vanilla js alternatives.
