### ISSUE TITLE
Add prefetch for linked component modules to page HTML

### ISSUE THREAD

**Issue by Moocar** [gatsbyjs/gatsby#14262]
## Background

The new [per-page-manifest](https://github.com/gatsbyjs/gatsby/tree/per-page-manifest) feature replaces the global `pages-manifest` with a `page-data.json` for each page. The pages-manifest meant that the browser had all the component and dataPath information it needed, and could therefore prefetch component and query results in parallel. Since we no longer have the global list of all page metadata, we now have to first request the `page-data.json` for the page, retrieve the component name, and then request the component. So we now have to wait for 2 prefetch requests to execute serially before we have all the information required to quickly navigate to a page. This performance impact will only be felt by users on slow connections, but it's still a regression.

## Proposed Change

During html rendering, detect all pages that are linked to by the page currently being rendered, and for each linked page, find its component, and add a prefetch link. Basically, we want the same functionality as [Gatsby.Link.componentDidMount](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-link/src/index.js#L76), but during html generation.

## Implementation Ideas

- Use [react-side-effect](https://github.com/gaearon/react-side-effect). This would involve creating an alternate `Gatsby Link` that worked on the server. On `componentDidMount`, it would write the `to` URL to a Set, which we could use to figure out which pages/components need prefetching

## Related Issues

- https://github.com/gatsbyjs/gatsby/pull/13004
- https://github.com/gatsbyjs/gatsby/issues/11982#issuecomment-468950038

**Comment by dja** [comment]
Just an added thought here that a proposed solution should support adding the appropriate links to headers for hosting plugins like `gatsby-plugin-netlify`.
