### ISSUE TITLE
Need help with conditional rendering of component on site load depending on conditions in the browser

### ISSUE THREAD

**Issue by jacksaunders** [gatsbyjs/gatsby#14275]
## Summary
I have a split test component that conditionally renders components however because the calculations need to be done in the browser based on a cookie that is set by nginx im getting a flash of the wrong component on load. 

## Relevant information

I have written a custom A/B testing component for testing individual components in react. it works pretty similar to https://www.npmjs.com/package/react-split-testing but with one difference in that, the split test branch is determined by a cookie set via nginx. 

I have it set to show the first child branch if no config is detected which is needed for SSR in order to have the correct content for crawlers to properly index. 

However, when i serve the built version of the site I'm getting that default branch shown for a split second and then if the user is in the other branch it loads that one up so it looks pretty awful. 

i assume this is because SSR is building the site with no config and showing the default branch, then my conditional logic runs on page load and inputs the other component if needed. 

So i am wondering if there is a way to do the calculation after the initial request for the html (which is when the cookie is set via nginx) but before the page is shown and then display the correct branch without seeing the default one first.

Thanks in advance

**Comment by pieh** [comment]
Just to be clear - branch here doesn't mean git branch - it's A/B variant?

In any case - we would need to build 2 variants of the site or page ahead of time and we could let nginx determine which html to serve for first-paint based on the cookie, so there is no flash of wrong component - details on how to do this will depend on your exact setup, so I hope to hear more

**Comment by jacksaunders** [comment]
Yes sorry i mean variant. 

The setup is fairly straight forward the build is uploaded to an S3 bucket, what would you need to know from an nginx point of view to determine this?

**Comment by pieh** [comment]
Are all your request going through nginx? If so, we could create 2 separate pages for your 2 variants:

in `gatsby-node`:
```
const variants = [`variant-A`, `variant-B`]
variants.forEach((variant, index) => {
  actions.createPage({
    path:  index === 0 ? `some-path` : `some-path_${variant}`,
    component: _path_to_template_
    context: {
      variant
    }
  })
})
```

In your page you can get `variant` by using `pageContext.variant` prop in your template to determine which one to use for SSR (so you probably should check cookie first and fallback to that prop if not available)

And in nginx, serve when someone requests `some-path/index.html` serve either that or `some-path_variant-B/index.html` depending on cookie

Would this work for you?

**Comment by pieh** [comment]
(it's pretty hacky, because we didn't do much research on canonical example for A/B testing)

**Comment by jacksaunders** [comment]
Thanks, this is very useful thanks, i will see what i can put together, my only real reservation for this is if i have numerous split tests going on there could potentially be quite a lot of variations being generated as someone could be in split test variant_a for one split test and variant_b for another
