### ISSUE TITLE
[question] combine theme & starters?

### ISSUE THREAD

**Issue by maxpou** [gatsbyjs/gatsby#14274]
Hey,

6 months ago, I completely rewrote my blog using Gatsby.js. But, I wanted to share my work to the community. So, I created a starter and I based my blog on this starter.
I have:
* Starter: https://github.com/maxpou/gatsby-starter-morning-dew
* Website: https://github.com/maxpou/maxpou.fr (using starter)

Every-time I wanted to fix a bug/add functionality, I have to do it twice. One per repo.
Then, a few months ago, Gatsby launch themes (beta). I checked @jlengstorf 's blog and I decided to do something similar. 
* the theme repo will contain the components&co
* the website repo will only contain content data (blog posts, etc.).

After a few commits, I'm very close to merge the "convert to theme PR" (https://github.com/maxpou/gatsby-starter-morning-dew/pull/55). I checked, the "starter repo" can now be used as a starter, but also as a theme.

My question is: 
What is the best way to combine theme and starter in the same repo?
Because if I switch my repo to a theme (~ repo renaming), I will probably loose the "theme users". What do you think about?

In advance, thanks for your help :purple_heart:

**Comment by DSchau** [comment]
Hello!

In general, we're big fans of monorepos at Gatsby. A pattern we like is a top-level folder called `themes`, wherein the themes are developed. You could then use another folder, e.g. `starter` that would then _use_ these exposed themes.

However, you may note an issue here, specifically that as a user _using_ your theme they wouldn't be able to use `gatsby new <your-repo-url>` here very cleanly. As such, we'll soon enable a sub-path functionality to `gatsby-new`. Until then, a pattern we like is to build out a read-only clone of a subdirectory, e.g. gatsbyjs/gatsby-starter-default is built from the [starters/default](https://github.com/gatsbyjs/gatsby/tree/master/starters/default) folder in our monorepo with [this script](https://github.com/gatsbyjs/gatsby/blob/master/scripts/clone-and-validate.sh).

So the recommended approach here for now would be something like:

1. Continue to keep your `gatsby-starter-morning-dew` repo
1. Consider creating `gatsby-morning-dew` repo (or whatever you name it!)
1. Use a CI or Github Actions tool to clone our the `gatsby-morning-dew/starter` folder to the separate repo
    - I know @johno has experimented a bit with the Action approach

We're aware there's a little friction here, so rest assured--we're working on this! Thanks for being an early adopter and hanging with us 💪

**Comment by maxpou** [comment]
Thank you so much @DSchau for your very detailed response!
