### ISSUE TITLE
Update dashboard github apps info [slightly unrelated]

### ISSUE THREAD

**Issue by halkeye** [gatsbyjs/gatsby#14277]
## Description

When I goto the gatsby dashboard github page, it says the url is localhost:8000

### Steps to reproduce

goto https://github.com/settings/connections/applications/e0358f043a6c3048612d

### Expected result

Should have the actual url

### Actual result

localhost:8000

I know this isn't gatsby code related, but I couldn't find a related repo to put this in. I'm trying to clean up my oauth'd apps like I do regularly, and right now since I can't access the site I'm probably going to revoke.

**Comment by DSchau** [comment]
Hello!

We use that application to associate your Github account for rewards, e.g. the [GatsbyJS Swag Store](https://store.gatsbyjs.org). The URL is for the _project_ not necessarily for the end user.

It's associated with your account when you purchase something from the GatsbyJS store, so we hope you'll keep it around. Specifically, some more helpful info:

**Name**

> Gatsby Collaborator Dashboard

**Description**

> Manage your Gatsby contributor rewards, such as discount codes for swag and contributor-only announcements.

Nothing malicious here, we just need a way to request your Github profile and some info to associate with the Swag Store.

Going to close as answered--thanks for the question!

**Comment by halkeye** [comment]
@DSchau can you still update the oauth info it uses to be a real url? like https://store.gatsbyjs.org/
