### ISSUE TITLE
[blog] Blog suggestion: Integrating Bug Monitoring software tools into Gatsby

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#14278]
## Summary

Throughout the past few years, many tools like [Sentry](https://sentry.io), [Rollbar](https://rollbar.com) and others offer experiences that if a user runs into a bug, rather than having a user submit a bug report with the bug and their environment settings, the software will do it automatically.

I think it would be neat for someone who has a Gatsby workflow with one of these platforms to write a blog post for the Gatsby Blog describing their workflow and how it's improved their development cycle.

**Comment by RedHoodJT1988** [comment]
I would love to work on this. I am currently developing a site now with Gatsby that will have a blog attached to it. Would it be ok to take this on @lannonbr?

**Comment by DSchau** [comment]
@RedHoodJT1988 it's all yours 👍

**Comment by RedHoodJT1988** [comment]
Awesome. Just to clarify, you want me to write a blog about using Gatsby with Sentry, Rollbar or any one of the other similar bug reporting libraries correct based on my own use of the libraries right?

**Comment by lannonbr** [comment]
@RedHoodJT1988 The idea is more on creating a blog post for the [Official Gatsby Blog](https://www.gatsbyjs.org/blog/) on how to integrate those kinds of bug reporting software with a Gatsby site and insights about the experience.

**Comment by RedHoodJT1988** [comment]
Ok awesome. That works even better. Thank you for the clarification. I will get started on that right now.

**Comment by RedHoodJT1988** [comment]
Hello, I am still working on this issue. It's taking me a bit of time
because I am juggling work and the issue. I am still doing it though. Sorry.

**Comment by RedHoodJT1988** [comment]
Almost finished with this blog post. Sorry it has taken so long.

**Comment by RedHoodJT1988** [comment]
Hello, just wanted to reach out and let you know that I was finally able to submit my PR for this. I am hoping that it is what you were looking for but if not please let me know and I will adjust or add anything needed to fix it. Thanks.
