### ISSUE TITLE
Preload fonts used on pages

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#14281]
Fonts don't start downloading until the browser knows they're needed. Which means that the browser has to download/parse the HTML & CSS and start rendering a section of the page before it knows to start downloading the font.

This can cause significant delays in loading fonts.

A common suggestion is to add a `<link preload>` to the page for each font that's used on the page so the browser knows to start downloading the font files immediately.

But that raises the question of how would you know which files are used. Generally right now people manually note which fonts are used on specific pages and manually add preloads for each one.

This sort of manual bookkeeping is against everything Gatsby stands for! So how do we automate this? We can't (cheaply) know at build time which fonts are used on every page.

One idea I just prototyped is that we could use Puppeter to visit each page of the site and write out a file listing for each page, what font files are downloaded. Then at build-time, a plugin could add the `<link preload>` for these files.

The plugin would include a script to build/serve/visit all the pages and write out a file with the font file data. This file would need checked in and the script would need periodically re-run (or automate it e.g. nightly in a CI).

Someone want to write this :-D? This would be a great core plugin to add.

The puppeter script would work roughly like this:

```js
const puppeteer = require("puppeteer")
const path = require(`path`)

puppeteer.launch().then(async browser => {
  const page = await browser.newPage()
  page.on(`requestfinished`, e => {
    if (e._method === `GET` && path.parse(e._url).ext === `.woff2`) {
      console.log(e._url)
    }
  })
  await page.goto("https://www.gatsbyjs.org")
  await browser.close()
})
```

/cc @brimtown

**Comment by Munter** [comment]
@papandreou of we can add an opt-out of the subsetting functionality of subfont, we basically already have what's required here

**Comment by papandreou** [comment]
You want to take the sub out of subfont? :laughing:

But yeah, that ought to work!

**Comment by superhawk610** [comment]
I can take this ✌️

**Comment by KyleAMathews** [comment]
Thanks!
