### ISSUE TITLE
Make requests not send credentials

### ISSUE THREAD

**Issue by cameron-martin** [gatsbyjs/gatsby#14293]
## Summary

Make gatsby not send credentials when making requests - currently in the following 2 places:

https://github.com/gatsbyjs/gatsby/blob/eaa08cfd7d9bf3e34209eec58a488585f25726e2/packages/gatsby/cache-dir/loader.js#L87

https://github.com/gatsbyjs/gatsby/blob/eaa08cfd7d9bf3e34209eec58a488585f25726e2/packages/gatsby/cache-dir/static-entry.js#L300

### Motivation

We have a slightly weird setup where our assets are on a CDN (enabled by the new `assetPrefix` option), which is a different domain from where the pages are served. This means we have to serve the assets with CORS headers. Moreover, we need them accessible from multiple origins and the headers must be static so we have to set `Access-Control-Allow-Origin` to `*`. Having this header set this way means that browsers error when doing XHRs with credentials.

My initial thought was that credentials can be removed for everyone without causing issues, but some people may have their static sites behind an authentication proxy which means credentials will need to be sent in some cases.

**Comment by pieh** [comment]
This is weird case - reason for using this in first place is that `<link rel="preload">` tag we add to <head> and then fetching it sometimes would create duplicated requests (that's why XHR is used there and not fetch ... and that's why there is bunch of weird attributes) - see https://github.com/gatsbyjs/gatsby/pull/4555/commits/9008479b10fbefdf426c1f9c8b1e27477d502f0b for change that was made that added this

**Comment by pieh** [comment]
I'm not sure if anyone actually is using credentials, so if we can replicate behaviour of not duplicated requests. Tt was some time ago since I tested it, and might be it was fixed - if it was chrome bug then (it might be just security reasons, didn't find much information on this topic).

In general I would very much love to avoid adding options like that and adjust what currently is there if possible

**Comment by cameron-martin** [comment]
> This is weird case - reason for using this in first place is that <link rel="preload"> tag we add to and then fetching it sometimes would create duplicated requests (that's why XHR is used there and not fetch ... and that's why there is bunch of weird attributes)

So is it setting `withCredentials` that fixes this bug, or the switch from `fetch` -> `XHR` or a combination of both? Do you have any more details on this bug?

> I'm not sure if anyone actually is using credentials

I'm not sure either, but a valid use-case for this would be a static site sitting behind an authentication proxy. But I'm not sure if anyone is doing this, or whether this actually works (since every request would have to be done with credentials enabled for this to work).

> In general I would very much love to avoid adding options like that and adjust what currently is there if possible

Yeah it does seem silly to add such a specific option - I probably should have opened this as a bug report instead.

It doesn't seem to be just the posted place that's causing problems, this also does:

https://github.com/gatsbyjs/gatsby/blob/eaa08cfd7d9bf3e34209eec58a488585f25726e2/packages/gatsby/cache-dir/static-entry.js#L300

However, I can't seem to find the original commit that introduced it - I can only find the merge commit. Possibly somebody with better git skills could find it.

**Comment by pieh** [comment]
over 1 year ago I used https://github.com/pieh/link-preload-fetch as barebone example of issue - I don't remember specifics but I think that not using `withCredentials` was resulting in double requests (I'm not quite sure if this is bug or intended behaviour, as I mentioned I couldn't find much information back then)

**Comment by cameron-martin** [comment]
I just ran that demo and:
* In chrome, everything except "base" only results in 1 request to `data.json`.
* In firefox, they all result in only 1 request.
* In edge, the top 2 result in 2 requests, and the bottom 2 result in only 1 request.

Possibly we could use `crossorigin="anonymous" / xhr` now then?

**Comment by cameron-martin** [comment]
Not stale

**Comment by xavivars** [comment]
We're also facing this problem: multiple hosts (xxxxxx.com, xxxxxx.fr, xxxxx.ie,...) need to access same CDN where assets live.

**Comment by id0Sch** [comment]
I'm facing this issue when trying to host the assets on the google-cloud-storage.
i'm using assetsPrefix, and have no way of adding the `Access-Control-Allow-Credentials` header.
AFAIK - there's no way of using gatsby with google-cloud-storage.
(found a relevant thread here: https://issuetracker.google.com/issues/123376293)

**Comment by xavivars** [comment]
I'd love to help to fix this issue...
