### ISSUE TITLE
[www] Icons breaking outside of container

### ISSUE THREAD

**Issue by ashygee** [gatsbyjs/gatsby#14303]
## Description

The icons in the sections header for Ecosystem and Blog seem to be collapsing out of alignment when resizing the browser under 1000px

### Steps to reproduce
Reproduced by resizing the window.

![gatsbyicons](https://user-images.githubusercontent.com/10384315/58348036-4d218980-7e14-11e9-846a-72ec9da29417.gif)

### Expected result

They should stay in alignment as seen in the screenshot below.
<img width="308" alt="Screenshot 2019-05-24 11 12 47" src="https://user-images.githubusercontent.com/10384315/58348237-f0729e80-7e14-11e9-830c-7dd694302699.png">

### Possible solution

When inspecting I noticed that the containing `h3` had a `margin-left: calc(-2.4rem);` but when at the smallest breakpoint <750px changes to `margin: 0px 0px 0.5em calc(-0.4rem);` which seems to fix the alignment at the breakpoint where the icons are shifting.

**Comment by lannonbr** [comment]
Confirmed this is happening between the mobile media query (<750px) and under 1000px.

cc: @fk is this supposed to happen or a bug / regression of the alignment of the styling across `www` over the past few months.

**Comment by dakebl** [comment]
Had a play with this locally and it looks like the wrong media query was being used, with `md` being used instead of `lg`.

I've created PR #14337 to update it.

**Comment by fk** [comment]
Not supposed to happen! :/ 🤦‍♂ 
Thank you both! <3 🙏
