### ISSUE TITLE
Error: Cannot query field "allImageSharp" on type "Query" when there's no images in the folder

### ISSUE THREAD

**Issue by javidhsueh** [gatsbyjs/gatsby#14304]
## Summary
I'm getting error when querying allImageSharp when there's no image in the static folder
<img width="1677" alt="Screen Shot 2019-05-24 at 12 49 54 PM" src="https://user-images.githubusercontent.com/3599601/58353139-92e54e80-7e22-11e9-837f-9677cdd6e06b.png">

```
Error: Cannot query field "allImageSharp" on type "Query".

GraphQL request (15:7)
14:       }
15:       allImageSharp {
          ^
16:         edges {
```
The query will pass if I have one or more images in the corresponding static folder.

## Relevant information

I have a folder /static/images in my website folder. I've setup the `gatsby-source-filesystem` plugin to get all the images. But there's no images in the folder by default.

Is there anyway to handle the query error above or do I need to have a dummy image in the folder?

### Environment (if relevant)

```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
  Languages:
    Python: 2.7.13 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 61.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby-cli: ^2.5.7 => 2.6.2 
    gatsby-image: ^2.0.38 => 2.1.0 
    gatsby-plugin-catch-links: ^2.0.13 => 2.0.15 
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1 
    gatsby-plugin-feed: ^2.1.0 => 2.2.1 
    gatsby-plugin-google-analytics: ^2.0.18 => 2.0.20 
    gatsby-plugin-google-fonts: ^0.0.4 => 0.0.4 
    gatsby-plugin-layout: ^1.0.11 => 1.0.15 
    gatsby-plugin-lodash: ^3.0.5 => 3.0.5 
    gatsby-plugin-manifest: ^2.0.29 => 2.1.1 
    gatsby-plugin-nprogress: ^2.0.10 => 2.0.10 
    gatsby-plugin-offline: ^2.0.25 => 2.1.1 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sass: ^2.0.7 => 2.0.11 
    gatsby-plugin-sharp: ^2.1.0 => 2.1.0 
    gatsby-plugin-sitemap: ^2.0.12 => 2.1.0 
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.7 
    gatsby-remark-autolink-headers: ^2.0.16 => 2.0.16 
    gatsby-remark-copy-linked-files: ^2.0.11 => 2.0.12 
    gatsby-remark-frontmatter-defaults: ^0.0.2 => 0.0.2 
    gatsby-remark-images: ^3.0.12 => 3.0.12 
    gatsby-remark-prismjs: ^3.2.8 => 3.2.9 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-source-filesystem: ^2.0.29 => 2.0.37 
    gatsby-source-instance-name-for-remark: ^0.1.1 => 0.1.1 
    gatsby-transformer-json: ^2.1.6 => 2.1.11 
    gatsby-transformer-remark: ^2.3.8 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 
```

### File contents (if changed)
gatsby-congif.js
```
plugins: [
      // ...
      'gatsby-plugin-sharp',
      'gatsby-transformer-sharp',
      {
          resolve: 'gatsby-source-filesystem',
          options: {
          name: 'images',
          path: `${myConfig.DIR_NAME}/static/images`,
      }
    }
]
```

**Comment by jonniebigodes** [comment]
@javidhsueh take a look at [this](https://www.gatsbyjs.org/docs/static-folder/) for usage of the `static` folder and also [this](https://www.gatsbyjs.org/docs/importing-assets-into-files/) and also like you said if there's nothing, Gatsby will overlook the folder as there's no need to apply any image transformation during the build time and with that the graphql error in the query. If there's a suitable image in there then Gatsby will then manipulate it.

**Comment by javidhsueh** [comment]
> @javidhsueh take a look at [this](https://www.gatsbyjs.org/docs/static-folder/) for usage of the `static` folder and also [this](https://www.gatsbyjs.org/docs/importing-assets-into-files/) and also like you said if there's nothing, Gatsby will overlook the folder as there's no need to apply any image transformation during the build time and with that the graphql error in the query. If there's a suitable image in there then Gatsby will then manipulate it.

Yes, I understand these. My question is how to bypass the query error when three's no images in the static folder. It's a bit annoying to see the error in the build time.

**Comment by jonniebigodes** [comment]
@javidhsueh put a image in the folder, either a stock image or something like the `gatsby-icon.png` or `gatsby-astronaut.png` used in the default starter. That will probably fix that error.

**Comment by javidhsueh** [comment]
> @javidhsueh put a image in the folder, either a stock image or something like the `gatsby-icon.png` or `gatsby-astronaut.png` used in the default starter. That will probably fix that error.

Yes, it will fix the error as I described above. Having at least one image in the static folder will solve it. I just wonder if there's a cleaner solution for the query error.

**Comment by jonniebigodes** [comment]
@javidhsueh here's the thing. During the build process Gatsby checks the plugins that will be used and sees that you have references to `gatsby-image` and it's dependencies. It continues the process and takes a peek at the folder in question, if it has something that is referenced by `gatsby-source-filesystem`, it will delegate the job of manipulating the images otherwise it will continue it's process. Now when it reaches the stage where it parses the graphql queries, it will try to run them. Which in this case will result in that error. Basically you're telling Gatsby to manipulate something that doesn't exist, so that's why you experience that error.

**Comment by javidhsueh** [comment]
Can't we use `resolvers` to deal with this situation gracefully?
https://www.gatsbyjs.org/blog/2019-03-04-new-schema-customization/

**Comment by stefanprobst** [comment]
@javidhsueh one thing you could do is enforce that a `ImageSharp` type exists in the schema:
```js
// gatsby-node.js
exports.sourceNodes = ({ actions }) => {
  actions.createTypes(`type ImageSharp implements Node { id: ID! }`)
}
```

**Comment by javidhsueh** [comment]
> @javidhsueh one thing you could do is enforce that a `ImageSharp` type exists in the schema:
> 
> ```js
> // gatsby-node.js
> exports.sourceNodes = ({ actions }) => {
>   actions.createTypes(`type ImageSharp implements Node { id: ID! }`)
> }
> ```

Thanks @stefanprobst this solves my problem!
