### ISSUE TITLE
Reducing # of output files?

### ISSUE THREAD

**Issue by v-kistai** [gatsbyjs/gatsby#14313]
Question!
My current development environment is a bit Web 1.0, it's a ready made CMS that only accepts copy/pasted HTML and manually uploaded files (think 10 clicks to upload each file).  I won't go into why it's my only option, but truly it is for internal/company reasons.  

I would really ease my path to make use of more modern technologies like React to speed along development, while still generating the static content that my platform requires.  It's a small site I'm working on, and I'm less concerned about the performance benefits of code-splitting and whatever all of these JSON files in the /public/static folder are for (I'm new!) and REALLY concerned about the level of work that manual deployments will take given the number of output files I'm seeing that Gatsby generates.  I created a few pages and a few components in Gatsby, turned on Webpack's LimitChunkCountPlugin = 1 (which really helped) but there are still 27 files that I would need to painstakingly upload with all the clicking with just this very limited amount of pages/components.  I expect this number would end up being x20 with my actual site's content in Gatsby.  The site will be changing frequently, which is nightmarish to think about deploying.

Do you know of a way to switch off some of Gatsby's features to limit the number of output files that I would need to deploy?

Ideally the /public folder would have..
html pages
1 css file
1 js file
maybe a json file

I definitely realize this is not what Gatsby is intended for, but it would really help me out to be able to use it without all the deployment headaches/deal-breakers of hundreds of files to deploy manually over and over. 

Fingers crossed
Thank you kindly

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by DSchau** [comment]
@v-kistai is there any way whatsoever to automate the task?

A brute force solution would be to script the process you do manually with something like [Puppeteer](https://github.com/GoogleChrome/puppeteer) so you could script the manual actions with an automated solution.

I don't think this is going to be something we'll support in core, mostly because it's an extremely niche use case unfortunately!

**Comment by v-kistai** [comment]
Totally understandable. Puppeteer might be really handy if my CMS were web-based (it's a Windows app), but thanks much for offering the suggestion.  No one happens to know of a SSG that might be more appropriate given my use case would they?

**Comment by superhawk610** [comment]
@v-kistai if you want to produce the smallest number of files possible, I don't believe you'll have much luck with any existing SSGs, but you may like [Parcel](https://parceljs.org/). Here's a super minimal example I threw together - you could even drop the sourcemap and only have to upload 2 files per deployment.

<img width="519" alt="Screenshot_20190605_021111" src="https://user-images.githubusercontent.com/18172185/58934076-63461880-8737-11e9-9e97-794e76b088a3.png">

Parcel also supports just about everything out of the box with no config, so it sounds like it may work well for your situation. Best of luck!
