### ISSUE TITLE
[gatsby-plugin-emotion] duplicate CSS declarations

### ISSUE THREAD

**Issue by FlorianMoser** [gatsbyjs/gatsby#14321]
## Description

Not sure if this is working as expected or if it is even an issue with Emotion: when adding styled components into a non-styled node, the compiler produces duplicate CSS class declarations.

### Steps to reproduce

1. Insert the following code into index.js of a new Gatsby project
```JSX
import React from "react"
import styled from "@emotion/styled"

const TitleStyle = styled.h1`color: #bad101;`
const Title = ({ children }) => <TitleStyle>{children}</TitleStyle>

export default () => (
  <div>
    <Title>Hello World</Title>
    <Title>Bonjour World</Title>
    <Title>Ciao World</Title>
  </div>
)
```
2. Build the project using `gatsby build`
3. Inspect the generated source code

### Expected result

The generated HTML source code should only contain one single declaration of the class that is being applied to the Title components.

### Actual result

In this example, the CSS class `css-qnh44z`is declared for every instance of the H1.

```HTML
<div>
  <style data-emotion-css="qnh44z">.css-qnh44z{color:#bad101;}</style>
  <h1 class="css-qnh44z en8bjfu0">Hello World</h1>
  <style data-emotion-css="qnh44z">.css-qnh44z{color:#bad101;}</style>
  <h1 class="css-qnh44z en8bjfu0">Bonjour World</h1>
  <style data-emotion-css="qnh44z">.css-qnh44z{color:#bad101;}</style>
  <h1 class="css-qnh44z en8bjfu0">Ciao World</h1>
</div>
```

### Remedy
Simply styling the outer node fixes the problem:

```JSX
import React from "react"
import styled from "@emotion/styled"

const TitleStyle = styled.h1`color: #bad101;`
const Title = ({ children }) => <TitleStyle>{children}</TitleStyle>
const NowStyled = styled.div``

export default () => (
  <NowStyled>
    <Title>Hello World</Title>
    <Title>Bonjour World</Title>
    <Title>Ciao World</Title>
  </NowStyled>
)
```

### Environment

  npmPackages:
    gatsby: ^2.3.25 => 2.7.1
    gatsby-image: ^2.0.39 => 2.1.0
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6
    gatsby-plugin-manifest: ^2.0.29 => 2.1.1
    gatsby-plugin-offline: ^2.0.25 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.0.35 => 2.1.0
    gatsby-plugin-sitemap: ^2.0.12 => 2.1.0
    gatsby-source-filesystem: ^2.0.29 => 2.0.37
    gatsby-transformer-remark: ^2.3.10 => 2.3.12
    gatsby-transformer-sharp: ^2.1.18 => 2.1.19

**Comment by freiksenet** [comment]
This looks like an issue with emotion, I don't think Gatsby does anything special there. I wonder if you could create an issue in [their repository](https://github.com/emotion-js/emotion)? Thank you!

**Comment by FlorianMoser** [comment]
Thanks for the response. I just searched deeper in the Emotion issues and I found this issue [Styles are output multiple times during SSR](https://github.com/emotion-js/emotion/issues/1061), which is probably the same problem.
