### ISSUE TITLE
[1.0] Webpack Validation Errors for custom top-level config keys

### ISSUE THREAD

**Issue by iansinnott** [gatsbyjs/gatsby#1432]
Hello, I'm running in to this issue while trying to build a transform plugin for stylus, _but_ this looks like a larger issue that will affect any webpack loader or plugin which uses a top-level key for custom configuration.

`gatsby-node.js` looks like:

```js
// gatsby-node.js
exports.modifyWebpackConfig = ({ config, stage }, options = {}) => {

  if (Array.isArray(options.use)) {
    config.merge(current => {
      current.stylus = { // <-- The problem line
        use: options.use,
      };
      return current;
    });
  }

  // ... more stuff, but not relevant to this issue

}
```

The issue here is that webpack-validator does not allow `current.stylus = ...` because it's a non-standard top-level key. But this isn't just an issue for stylus, it's an issue for any webpack library that wants to use a top-level config key. 

The resulting message in the console is:

```
stylus
object.allowUnknown , "stylus" is not allowed
```

Source code in question: [webpack-modify-validate.js#L22](https://github.com/gatsbyjs/gatsby/blob/524ff171cd890b79ce9535d6dc10550c70365d33/packages/gatsby/src/utils/webpack-modify-validate.js#L22)

Is there any way around this? Am I missing something? 

---

One way around this would be an upgrade to webpack 2 since all loaders provide their own options in a standard way, but that is likely not priority right now since webpack 1.x is working just fine.

Gatsby: **1.0.6**
Node: **6.10.2**
OSX: **10.11**

**Comment by KyleAMathews** [comment]
Hmmm interesting.

The plan is to move to webpack 3 sooner than later but in the meantime... perhaps you could add an exception for stylus somehow?

Also, interested in making a `gatsby-plugin-stylus`? It's just the code you're writing but in its own package :-)

**Comment by iansinnott** [comment]
Yeah, definitely :) I've got all the code running on my own site which I just ported to gatsby. The only downside currently is this precise issue. Adding stylus plugins is pretty common _but_ in the meantime the plugin will work fine for authoring your own stylus.

Will PR. 

But it will be great to either get on WP3 or have another solution for any loaders/plugins that use top-level keys.

**Comment by KyleAMathews** [comment]
Great! Looking forward to the PR.

What we can do now is just look at the error from the webpack validator and if it complains about something we do allow e.g. stylus then ignore the error.
