### ISSUE TITLE
[gatsby-remark-images] Wrong image ratio for portrait image

### ISSUE THREAD

**Issue by MicroBenz** [gatsbyjs/gatsby#14331]
## Description

I've using gatsby-remark-images to enable importing the image into markdown, everything works fine except If I'm using an image with portrait ratio (height is longer than width) its result showing the wrong image ratio.

### Steps to reproduce

Link the image inside markdown

```markdown
![](./01.jpg)
```

### Expected result

The image should show the correct image's ratio.

Here is the original's image

![image](https://user-images.githubusercontent.com/9103800/58382326-3776b480-800c-11e9-8a49-3e933ad4017d.png)

### Actual result

Image shows but the aspect ratio are incorrect.

![image](https://user-images.githubusercontent.com/9103800/58382301-072f1600-800c-11e9-8e68-e159d7b600d8.png)

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.10.1 - ~/.nvm/versions/node/v8.12.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Safari: 12.1
  npmPackages:
    gatsby: ^2.0.19 => 2.0.70 
    gatsby-image: ^2.0.22 => 2.0.25 
    gatsby-plugin-feed: ^2.0.8 => 2.0.11 
    gatsby-plugin-google-analytics: ^2.0.5 => 2.0.8 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.12 
    gatsby-plugin-offline: ^2.0.5 => 2.0.20 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.4 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sass: ^2.0.7 => 2.0.7 
    gatsby-plugin-sharp: ^2.0.6 => 2.0.15 
    gatsby-plugin-sitemap: ^2.0.5 => 2.0.5 
    gatsby-plugin-slug: ^1.0.1 => 1.0.1 
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4 
    gatsby-remark-external-links: ^0.0.4 => 0.0.4 
    gatsby-remark-images: ^3.0.11 => 2.0.6 
    gatsby-remark-prismjs: ^3.0.0 => 3.1.4 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.7 
    gatsby-remark-smartypants: ^2.0.5 => 2.0.7 
    gatsby-source-filesystem: ^2.0.2 => 2.0.12 
    gatsby-transformer-remark: ^2.1.6 => 2.1.17 
    gatsby-transformer-sharp: ^2.1.3 => 2.1.9 

My plugins

```
plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/blog`,
        name: 'blog',
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/assets`,
        name: 'assets',
      },
    },
    {
      resolve: `gatsby-plugin-styled-components`,
      options: {
        ssr: true,
      },
    },
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              withWebp: true,
              quality: 70,
              showCaptions: false,
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          'gatsby-remark-prismjs',
          // 'gatsby-remark-copy-linked-files',
          'gatsby-remark-smartypants',
          {
            resolve: 'gatsby-remark-external-links',
            options: {
              target: '_blank',
              rel: 'noopener noreferrer',
            },
          },
        ],
      },
    },
    `gatsby-transformer-sharp`,
    'gatsby-plugin-sitemap',
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: env === 'development' ? '' : ``,
      },
    },
    `gatsby-plugin-feed`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `เบนซ์เขียนบล็อกนะจ๊ะ`,
        short_name: `MicroBenz`,
        start_url: `/`,
        background_color: `#ffffff`,
        theme_color: `#3B76BF`,
        display: `minimal-ui`,
        icon: `content/assets/favicon.png`,
      },
    },
    `gatsby-plugin-remove-serviceworker`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-sass`,
  ],
```

**Comment by Ronva** [comment]
Created a codesandbox with the remark-images plugin and it seems to be working as expected:
https://codesandbox.io/embed/gatsbystartermarkdown-ql50o

**Comment by MicroBenz** [comment]
@Ronva If I used an image from the network it's fine. But if I use image locally (like my example I've used a relative path to the image). The bug still happens.

**Comment by freiksenet** [comment]
Hi @MicroBenz!

I've recreated it with local image and it still doesn't work (I've used your image, but compressed it a bit so it fits into code sandbox). https://codesandbox.io/s/gatsbystartermarkdown-cr6f3

**Comment by MicroBenz** [comment]
I just find out that my image isn't really in the portrait ratio. I re-rotate it 360 degrees. And it's work...

So I'm closing this issue. Thanks

**Comment by karlhorky** [comment]
I had a variation of this today where the images were replaced (under the same names) and Gatsby didn't update the cache for the sizes for the images (even after a restart of the dev server), which caused the aspect ratios to be improperly calculated.
