### ISSUE TITLE
Footnotes aren't rendering in Markdown

### ISSUE THREAD

**Issue by benmccormick** [gatsbyjs/gatsby#1434]
It looks like gatsby is intending to render footnotes when parsing Markdown, based on the [plugin code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/extend-node-type.js#L43).  Unfortunately this isn't happening in practice.

I'm seeing this behavior on my site.  [This post](https://benmccormick.org/2017/05/29/atom-tips/) for example is based on [this source](https://github.com/benmccormick/benmccormickorg/blob/master/src/pages/posts/2017/atom-tips.md).  You can scroll down and see that the footnote isn't being formatted.  

I was able to verify the behavior outside of my environment by cloning https://github.com/KyleAMathews/blog and adding a footnote to a post.  It also didn't format.  I also disabled all of the remark-plugins my blog was using, and didn't see any difference.  I'm going to try to look into this, but would appreciate help if this is simple for someone else, since I've never done anything with remark and don't have a lot of context.  

Minimal test case I'd expect to work, but isn't:

```
Test [^1].

[^1]: Testing
```

should be formatted to footnote html that links the references.

**Comment by KyleAMathews** [comment]
Hmm I'm not sure why that doesn't work... things to check are what the markdown AST looks like for a very simple post and if in the html conversion process if footnotes need to be enabled there as well.

**Comment by KyleAMathews** [comment]
Possibly one of the gatsby remark plugins is interfering with the conversion as well so you could try disabling them.

**Comment by fk** [comment]
Damn, had testing and documenting footnotes on my list when setting up https://using-remark.gatsbyjs.org/ … and then forgot about it! Thanks for bringing this up @benmccormick!

**Comment by benmccormick** [comment]
@fk @kyleamathews Turns out that remark changed the way they load options recently.  Updating to the new style fixes the issue. https://github.com/gatsbyjs/gatsby/pull/1441
