### ISSUE TITLE
How to use prismjs plugins custom-class with gatsby-remark-prismjs?

### ISSUE THREAD

**Issue by vikasaditya** [gatsbyjs/gatsby#14342]
hi, 
I have some global CSS classes that clash with prism styles which can be solved by https://prismjs.com/plugins/custom-class/ 

Any pointer on how to use this?

Thanks

**Comment by freiksenet** [comment]
Hi!

How are you using prism in gatsby? Is it `gatsby-plugin-mdx-prismjs` or `gatsby-plugin-remark-prismjs`? If latter, would using `classPrefix` option solve your problem?

**Comment by vikasaditya** [comment]
hi, 
I am using https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/  and no classPrefix only adds prefix to `<pre>` and `<code>` whereas I need it at the level of `<span class="pr-token pr-punctuation">;</span>`

**Comment by donaldboulton** [comment]
Try a utils file with prism.js to declare your extensions and variables. Mine is at [prism.js](https://github.com/donaldboulton/publiuslogic/blob/master/client/src/utils/prism.js)
Hope that helps.
Don
