### ISSUE TITLE
False warning of “unable to find declaration of variable” with useStaticQuery + TypeScript

### ISSUE THREAD

**Issue by ryanditjia** [gatsbyjs/gatsby#14345]
## Description

Gatsby is giving me this false positive warning:

> We were unable to find the declaration of variable "HomepageQuery", which you passed as the "query" prop into the useStaticQuery declaration in
"~/gatsby-project/src/pages/index.tsx".

![image](https://user-images.githubusercontent.com/16177372/58411848-70139e00-809f-11e9-8e6e-2e562c7a6c88.png)

Gatsby code that I assume is reporting this warning: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/query/file-parser.js#L213-L259

Current workaround is changing this:

```jsx
  const data = useStaticQuery<HomepageQuery>(query)
```

to
```jsx
  const data: HomepageQuery = useStaticQuery(query)
```

### Steps to reproduce

I made a minimal reproduction case in this repo:

```sh
git clone https://github.com/ryanditjia/gatsby-issue-typescript-usestaticquery.git
```

```sh
npm install
```

```sh
npm start
```

The types were generated using Apollo CLI. If you wish to re-run the code generation:

```sh
npm run clean-generate
```

Note that I have tried inlining the types inside the component, but the warning is still there.

### Expected result

There should be no warning.

### Actual result

Develop and build work just fine, but the warning is an annoyance.

### Environment

System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 60.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.7.1 => 2.7.1
    gatsby-plugin-typescript: ^2.0.15 => 2.0.15

**Comment by freiksenet** [comment]
Thank you for a great report! It looks like that AST lint function doesn't support type casts properly. Would you like to make a PR to fix that?

**Comment by ryanditjia** [comment]
I haven’t the slightest idea where to begin with that 😅

**Comment by cameron-martin** [comment]
I can take a look at this.
