### ISSUE TITLE
Updating (migrating?) Data

### ISSUE THREAD

**Issue by nkov** [gatsbyjs/gatsby#1435]
I know this is a "static" site generator but with all of the GraphQL business and pulling from external sources, I wonder if something like the following is possible:

To have source JSON files like this:

```
{
  name: "Item1",
  quantity: 15
}
```
Then we can query this and display it on the page. All fine so far. Now a user goes through, places an order, receives a positive result from the API, now I would like to update this JSON file to -1 quantity. Then the site would need to recompile I guess, making this impossible.

Is this the right way to go about this? Should I pull quantity/product information from the API instead? Is this not a "Gatsby problem", or if it is, what's the Gatsby way to solve it? Am I supposed to make a custom source plugin or just throw `fetch` at it?

New to this ecosystem, any insight is helpful :)

**Comment by KyleAMathews** [comment]
You'd probably just want to reconcile the API updates with the data from Gatsby in the component.

So the user would immediately see an update after the API returns and then others would see the update as soon as the site finishes rebuilding.
