### ISSUE TITLE
Missing resources for /packages/gatsby-plugin-google-analytics/

### ISSUE THREAD

**Issue by ng-hai** [gatsbyjs/gatsby#14354]
## Description

The URL for [Gatsby Plugin Google Analytics](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/) is missing

### Steps to reproduce

From the Plugins page, search for `google analytics`, choose the result item.

### Expected result

It should show the content

### Actual result

Blank page and the console prints out `Missing resources for /packages/gatsby-plugin-google-analytics/`

### Environment

Gatsby website on production

**Comment by polishedwp** [comment]
Haven't been able to confirm from my system using Chrome, or from my Android phone. Can you supply more details? Which browser can you report this issue?

**Comment by LekoArts** [comment]
Please disable your Ad-Blocker and try again.

**Comment by ng-hai** [comment]
Hmm, turn off Ad-Blocker and it works

I use Firefox Developer Edition browser, with Ad-Blocker (uBlock Origin) turned on, I can still access to other plugins like `gatsby-plugin-hotjar` or `gatsby-plugin-google-gtag`. I don't understand why Ad-Blocker play a role on site resources fetching, is this problem related to how Gatsby process the resources? I've never seen this problem through other sites built with Gatsby.

**Comment by wardpeet** [comment]
Ad blockers block requests based on url. It seems like ublock block google-analytics keyword so that's why it breaks.
