### ISSUE TITLE
`gatsby serve` returns incorrect Content-Type header for wasm file

### ISSUE THREAD

**Issue by stefan2718** [gatsbyjs/gatsby#14374]
## Description

`gatsby serve` is returning the incorrect header `Content-Type: application/octet-stream` for my wasm module when it should be returning `application/wasm`. Running `gatsby develop` correctly returns the `wasm` header.

The `octet-stream` header means that I get this error in the console when I try to asynchronously load my module:
```
Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
  Promise.then (async)   
  componentDidMount   @ Clusterer.js:7
```

### Steps to reproduce

1. You can pull my repo [here. I've tagged it so it won't change.](https://github.com/stefan2718/personal-website/tree/v1.0.1) 
2. Run `npm install && gatsby develop` and go to `localhost:8000/lab`
3. Click the button "This button calls a function in a Wasm module." and you should see an alert pop-up (this is the successful test of loading the wasm module)
4. Kill the `gatsby develop` server and run `gatsby build && gatsby serve`
5. Go to `localhost:9000/lab` and you should see the console error I've printed above. Clicking the button will throw a `null` error, as the module has not been loaded.

You can also download my pre-built `public` folder from running `gatsby build` [here, labelled build.tar.gz](https://github.com/stefan2718/personal-website/releases/tag/v1.0.1)

You can also go to [https://stefanbattiston.com/lab](https://stefanbattiston.com/lab) and confirm that Cloudfront returns the correct header and therefore loading the module works.

### Expected result

The network request for http://localhost:9000/8e2923d2c8661eb4c930.module.wasm should have `Content-Type: application/wasm`

### Actual result

The network request for http://localhost:9000/8e2923d2c8661eb4c930.module.wasm has `Content-Type: application/octet-stream`

### Environment

Gatsby config files can be found here: https://github.com/stefan2718/personal-website/tree/v1.0.1
```
  System:
    OS: macOS Sierra 10.12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.9.2 - ~/.nvm/versions/node/v8.11.1/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Languages:
    Python: 3.7.0 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 60.0.1
    Safari: 10.0.3
  npmPackages:
    gatsby: ^2.2.9 => 2.3.27 
    gatsby-plugin-canonical-urls: ^2.0.13 => 2.0.13 
    gatsby-plugin-catch-links: ^2.0.13 => 2.0.13 
    gatsby-plugin-manifest: ^2.0.24 => 2.0.29 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^3.0.10 => 3.0.12 
    gatsby-plugin-s3: ^0.2.5 => 0.2.5 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.37 => 2.0.37 
    gatsby-remark-autolink-headers: ^2.0.16 => 2.0.16 
    gatsby-remark-images: ^3.0.11 => 3.0.11 
    gatsby-remark-prismjs: ^3.2.9 => 3.2.9 
    gatsby-source-filesystem: ^2.0.32 => 2.0.32 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
    gatsby: 2.7.3
```

**Comment by pieh** [comment]
I updated gatsby to latest and this seems to fix it for me

**Comment by stefan2718** [comment]
Upgrading all the libraries worked to fix this for me, thanks. I had initially only upgraded the global `gatsby` package, but upgrading `gatsby-cli` and the local `gatsby` seems to have done the trick.

New package versions:
```
  System:
    OS: macOS Sierra 10.12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.9.2 - ~/.nvm/versions/node/v8.11.1/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Languages:
    Python: 3.7.0 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 60.0.1
    Safari: 10.0.3
  npmPackages:
    gatsby: ^2.7.9 => 2.8.2
    gatsby-plugin-canonical-urls: ^2.0.13 => 2.0.13
    gatsby-plugin-catch-links: ^2.0.15 => 2.0.15
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^3.0.10 => 3.0.12
    gatsby-plugin-s3: ^0.2.5 => 0.2.5
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-remark-autolink-headers: ^2.0.16 => 2.0.16
    gatsby-remark-images: ^3.0.14 => 3.0.14
    gatsby-remark-prismjs: ^3.2.9 => 3.2.9
    gatsby-source-filesystem: ^2.0.38 => 2.0.38
    gatsby-transformer-remark: ^2.3.12 => 2.3.12
  npmGlobalPackages:
    gatsby-cli: 2.6.4
    gatsby: 2.8.2
```
