### ISSUE TITLE
Copy SWF files in gatsby-remark-copy-linked-files

### ISSUE THREAD

**Issue by jbeuckm** [gatsbyjs/gatsby#14380]
## Summary

Gatsby could copy flash _.swf files and replace the URLs in generated markup.

### Basic example

Proposed tag style to support:
```
<object type="application/x-shockwave-flash">
  <param name="movie" value="myContent.swf" />
</object>
```

### Motivation

I am migrating an old blog with some macromedia flash content.

**Comment by pieh** [comment]
`gatsby-remark-copy-linked-files@2.0.13` was published
