### ISSUE TITLE
Typography.js in starter example

### ISSUE THREAD

**Issue by SachaG** [gatsbyjs/gatsby#1438]
I'm not sure if it's a good idea to have typography.js included by default? I like what it does, but at the same time I think we should try to have the starter example be as simple as possible, to make it easier to understand. Someone unfamiliar with typography.js might not know what it does, or think it's required to run Gatsby, or try to remove it and break something in the process…

**Comment by KyleAMathews** [comment]
Yeah agree — I'll export the Typography.js CSS to a `typography.css` file. I'll be building a simple plugin for using Typography.js with Gatsby soon + in part 2 of the tutorial exploring different styling methods.

**Comment by KyleAMathews** [comment]
Removed in https://github.com/gatsbyjs/gatsby-starter-default/commit/c630e4597c3be7ec2a3655b13c42f77afda3c8a6
