### ISSUE TITLE
Globally Available Configurations or Data Objects

### ISSUE THREAD

**Issue by jhoffmcd** [gatsbyjs/gatsby#14398]
## Summary

Development teams who work on fairly large scale applications or practicing trunk-based development with feature/release flags may want to be able to build in a system of configuration based on these feature/release flags. You could do this by programmatically creating the config based on env vars during build time and pass that "global" configuration to the client code for further use.

### Basic example

The idea would be that during build time you would be able to create the configuration object, which could later be accessed by the runtime code bundles. Some advanced use cases of this would be using the configuration object to make a Feature Toggle component that you can use in your application to control flow.

Teams might namespace these flags as `FEATURE_` or `RELEASE_` flags, the idea being that feature flags are permanent fixtures while release flags are for temporary code gating on large in progress additions to the code base.

Component Toggle Example:

```javascript
import React from 'react';
import PropTypes from 'prop-types';

export default contextType => {
  class Toggle extends React.Component {
    render() {
      const { children, fallback, name } = this.props;
      const { [name]: feature } = this.context;
      const isFeatureEnabled = Boolean(feature);

      if (fallback) {
        return name in this.context && !isFeatureEnabled ? children : null;
      }

      return isFeatureEnabled ? children : null;
    }
  }

  Toggle.contextType = contextType;

  Toggle.propTypes = {
    children: PropTypes.node,
    fallback: PropTypes.bool,
    name: PropTypes.string.isRequired,
  };

  Toggle.defaultProps = {
    children: null,
    fallback: false,
  };

  return Toggle;
};
```

This component has feature context provided to it by a Provider:

```javascript
<FeatureToggleProvider value={featureFlags}>
```

And the `featureFlags` object is created by iterating through `process.env` and looking for the prefix `FEATURE_`.

### Motivation

For a large team working in a quick iteration cycle, it's important to be able to utilize the flagging concept in a dynamic, scalable way. This is also useful for developer who might be building whitelabel, multi-tenant, or i18n applications, where certain app features need on/off switches. In general, I think this would be an important concern for teams that are looking to scale Gatsby apps.

@DSchau

**Comment by jhoffmcd** [comment]
I guess bottom line is I really just need the mechanism to pass an object I create at build time over to the client side code. Does't have to be for feature flags, that's just for this example, however I would think most people would use it to pass configuration type things.

**Comment by KyleAMathews** [comment]
I like this. There's a variety of ways you can do this right now but none of them are _easy_. We could easily create e.g. a action that you can call from gatsby-node.js (`createGlobalContext` 🤔) that when called, writes out the data and then we add this to a context provider in both SSR and the browser.

**Comment by jhoffmcd** [comment]
@KyleAMathews any chance you can share an example of the hard ways? I would love to help contribute but I don't really know where a good starting place is.

I've worked on teams who have used this flagging approach to great effect in some other frameworks, I would love to see it easy to implement in Gatsby!

**Comment by jhoffmcd** [comment]
Would love to see any example of how this could be done 😜

**Comment by ervasive** [comment]
> Would love to see any example of how this could be done

This is how I currently do this kind of stuff.

First I add the required data to the page context with [`onCreatePage`](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#pass-context-to-pages) hook (btw it would be neat to have access to `graphql` in this hook).

This makes it possible to access this data in another hook [`wrapPageElement`](https://www.gatsbyjs.org/docs/browser-apis/#wrapPageElement), it is not completely clear from the docs, but we have access to the provided `pageContext` value in `props` argument there. Then we can wrap the `page element` with custom `context` and make it available to React components both in the browser and SSR envs.

**Comment by jhoffmcd** [comment]
@ervasive interesting approach! I will try it out. Thank you 🎸
