### ISSUE TITLE
Props not being passed in using Contentful example

### ISSUE THREAD

**Issue by bin4ryio** [gatsbyjs/gatsby#1439]
Hello @KyleAMathews. First, thanks for such amazing framework.

I am using latest 1.0 Contentful example with my own space API, however it seems like there is no `data` object being passed into `/pages/index.js`. I have checked everywhere, tried with/without localisation.

![2017-07-09_19 43 13_valkyrie_ss](https://user-images.githubusercontent.com/21124691/27993516-166f57fa-64df-11e7-8ada-2c08f6b4af5d.jpg)

**Comment by KyleAMathews** [comment]
Hi, have you tried the contentful example site?

**Comment by bin4ryio** [comment]
Yes I used the official example as starter. Only changed all `product` to `post` in everywhere (`gastby-node.js`, `product.js > post.js`, etc) for my own Contentful space. GraphQL queries return fine.

 I comparatively diffed with gatsby master and everything is similar. Wonder why `this.props.data` is undefined.

Also, for official examples it requires a manual install of `npm install --save-dev babel-plugin-transform-runtime` as well as a `.babelrc` that does the followings:
```{
  "plugins": ["transform-runtime"]
}
```

**Comment by bin4ryio** [comment]
Weird. Suddenly and it's working now.

**Comment by KyleAMathews** [comment]
Weird... if you can reliably reproduce the problem, would love to see a reproduction site.

**Comment by delta98** [comment]
@KyleAMathews not sure if related but receiving a data is null error here:

```
import React from "react"
import PropTypes from "prop-types"
import Link from "gatsby-link"
import Helmet from "react-helmet"

export default class Template extends React.Component {
  static propTypes = {
    data: PropTypes.object.isRequired,
    edges: PropTypes.array,
  }
  
  render() {
    return (
      <div>
        <Helmet
          title="Channel Frame"
          meta={[
            { name: "description", content: "Sample" },
            { name: "keywords", content: "sample, something" },
          ]}
        />
      </div>
    )
  }
}

export const pageQuery = graphql`
  query layoutQuery {
    site {
      siteMetadata {
        title
        description
      }
    }
  }
`
```
