### ISSUE TITLE
Backtick for prismjs and markdown video embed error

### ISSUE THREAD

**Issue by donaldboulton** [gatsbyjs/gatsby#14396]
I am using prism js for syntax highlighting and backticks in markdown indicate a code block so it overrides any other plugin using backticks and makes it a code block.
Plugins I have tried that get highlighted; "not linked", in markdown
Any and all that use backticks, like= `video: https://www.youtube.com/embed/2Xc9gXyf2G4`

**Comment by pieh** [comment]
I think you might need to re-order your remark plugins to put `gatsby-remark-video` (if this is the plugin you are using) before `gatsby-remark-prismjs`. If this doesn't help, then more details are needed here - ideally [reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)

**Comment by donaldboulton** [comment]
Moved  gatsby-remark-video before gatsby-remark-prismjs and it works.
Thank You
Don
