### ISSUE TITLE
gatsby build failing

### ISSUE THREAD

**Issue by santoshgistto** [gatsbyjs/gatsby#14405]
`gatsby build`

Error:
` WebpackError: ReferenceError: window is not defined
  
  - main.js:1 
    [lib]/[react-json-view]/dist/main.js:1:152093
  
  - main.js:1 
    [lib]/[react-json-view]/dist/main.js:1:152031
  
  - main.js:1 e.exports
    [lib]/[react-json-view]/dist/main.js:1:152530
  
  - main.js:1 Object.<anonymous>
    [lib]/[react-json-view]/dist/main.js:1:147630
  
  - main.js:1 t
    [lib]/[react-json-view]/dist/main.js:1:395
  
  - main.js:1 Object.defineProperty.value
    [lib]/[react-json-view]/dist/main.js:1:55264
  
  - main.js:1 t
    [lib]/[react-json-view]/dist/main.js:1:395
  
  - main.js:1 Object.defineProperty.value
    [lib]/[react-json-view]/dist/main.js:1:54028
  
  - main.js:1 t
    [lib]/[react-json-view]/dist/main.js:1:395
  
  - main.js:1 t.exports
    [lib]/[react-json-view]/dist/main.js:1:756
  
  - main.js:1 
    [lib]/[react-json-view]/dist/main.js:1:774
  
  - main.js:1 ./node_modules/react-json-view/dist/main.js.n
    [lib]/[react-json-view]/dist/main.js:1:65
  
  - main.js:1 Object../node_modules/react-json-view/dist/main.js
    [lib]/[react-json-view]/dist/main.js:1:253
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
  
  
  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
`
Using : https://github.com/mac-s-g/react-json-view

**Comment by DSchau** [comment]
You'll want to add react-json-view to the ignore list with Webpack. It's not server side rendering friendly (as you can see--it's using `window` which won't be available in a Node.js environment).

See [fixing third party modules](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules)

Going to close--thanks for providing the stack trace. Please reply or re-open if we can help further!
