### ISSUE TITLE
Prompt on cli subset of active users to take survey

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#14403]
Only survey people who've used Gatsby sufficiently enough to have an opinion.

Only ask a tiny subset of users.

Don't ask the same person more than once every quarter.

/cc @m-allanson @shannonbux

**Comment by shannonbux** [comment]
Probably making these expectations clear in the survey would help people
feel special and . "This survey is getting sent out to a subset of active
Gatsby users and will only be sent, at most, once per quarter. If you'd
like to opt out from future surveys, say no here." or something like that?

I saw an example today of people doing an opt in thing in the CLI with the
command called `feedback` and the results get sent to a google form
