### ISSUE TITLE
Why does my code run while Gatsby is building?

### ISSUE THREAD

**Issue by Jeff-Mott-OR** [gatsbyjs/gatsby#14415]
Regarding https://www.gatsbyjs.org/docs/debugging-html-builds/

> To fix this, find the offending code and either a) check before calling the code if window is defined **so the code doesn’t run while Gatsby is building**

My question is, why does my code run _at all_ when Gatsby is building?

Side question: Should I use onInitialClientRender instead?

**Comment by cameron-martin** [comment]
For doing [server side rendering](https://reactjs.org/docs/react-dom-server.html).

**Comment by lannonbr** [comment]
@Jeff-Mott-OR is there any updates on this issue? Would you like more information other than what @cameron-martin mentioned?
