### ISSUE TITLE
Gatsby develop not working inside a folder with accented latin letters

### ISSUE THREAD

**Issue by lborgav** [gatsbyjs/gatsby#14412]
## Description

When running **gatsby develop** inside a folder with accented latin letter, raises lots of error.
For example: inside a folder named **Ação**.
(When the folder is name **Acao**, it works fine)

### Steps to reproduce

```
cd /tmp
mkdir Ação && cd Ação
gatsby new gatsby-site && cd gatsby-site
gatsby develop
```
### Expected result

It should work correctly

### Actual result

```
success open and validate gatsby-configs - 0.016 s
success load plugins - 0.586 s
success onPreInit - 0.004 s
success initialize cache - 0.011 s
success copy gatsby files - 0.042 s
success onPreBootstrap - 0.010 s
success source and transform nodes - 0.046 s
success building schema - 0.166 s
success createPages - 0.002 s
⠋ createPagesStatefully
error UNHANDLED REJECTION


  TypeError: Cannot read property 'replace' of undefined

  - index.js:10 module.exports
    [gatsby-site]/[slash]/index.js:10:13

  - actions.js:203 actions.createPage
    [gatsby-site]/[gatsby]/dist/redux/actions.js:203:35

  - redux.js:468
    [gatsby-site]/[redux]/lib/redux.js:468:35

  - api-runner-node.js:65 doubleBoundActionCreators.(anonymous function).args
    [gatsby-site]/[gatsby]/dist/utils/api-runner-node.js:65:20

  - gatsby-node.js:31 Object.<anonymous>
    [gatsby-site]/[gatsby]/dist/internal-plugins/dev-404-page/gatsby-node.js:31:7

  - Generator.next
```

### Environment

System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.7.5 => 2.7.5
    gatsby-image: ^2.1.2 => 2.1.2
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.1.2 => 2.1.2
    gatsby-source-filesystem: ^2.0.37 => 2.0.37
    gatsby-transformer-sharp: ^2.1.20 => 2.1.20

**Comment by jonniebigodes** [comment]
@lborgav this is a issue that's been created a couple of times, as mentioned in #14126, for now avoid using those characters if you don't mind, i know that it might be a little cumbersome for a portuguese native speaking person, where you implicitely go for portuguese words. But until this issue is solved use this workaround, let's call it that. 

Feel free to provide feedback so that we can close this issue in favor of the one mentioned above. And sorry for the trouble you're experiencing.

**Comment by lborgav** [comment]
@jonniebigodes Thanks for the answer.
I gonna use the workaround you mentioned
