### ISSUE TITLE
Work with Jarmo to get top error messages listed

### ISSUE THREAD

**Issue by prestonso** [gatsbyjs/gatsby#14428]

**Comment by prestonso** [comment]
This replaces gatsby-inc/mansion#3420.

**Comment by jamo** [comment]
We do have https://modeanalytics.com/gatsby/reports/db549027a0d8 
But I'm planning to extend it to look at two parts. what's the first error, and what's the last error users experienced

**Comment by shannonbux** [comment]
Just saw this. Thanks @jamo, for the update! Maybe it makes sense to close this issue, since the original task is finished, and then open a new one with the new idea you have. What do you think @prestonso?

**Comment by jamo** [comment]
That's a great idea
