### ISSUE TITLE
Losing links to css & js after reload static page without cleaning cache of browser

### ISSUE THREAD

**Issue by FoxyGirl** [gatsbyjs/gatsby#14429]
# Description

We are using Gatsby for our site and we have caught a problem with pages created by gatsby-ssr.js. 

We can see correct html files in folder **/public/** with added links to css & js into `<head>`, but after build we can see them in <head> only after updating with cleaning browser cache _(Shift/Cmd/R)_.

Even using _Cmd/R_ for reload page doesn't help. 
https://tilda-api.netlify.com/en/factory-promo/

We get some links & scripts from external source by axios and write them in files in gatsby-node.js 
After we use next code  in gatsby-ssr.js

```
export const onPreRenderHTML = ({ pathname, getHeadComponents, replaceHeadComponents }) => {

  if (tildaFactoryPromoPages.includes(pathname)) {
    const headComponents = getHeadComponents()
    let cssTilda = fs.readdirSync('./public/static/tilda/factory/css/')
    let jsTilda = fs.readdirSync('./public/static/tilda/factory/js/')

    cssTilda = cssTilda.map((item) => (
      <link type="text/css" rel="stylesheet" href={`/static/tilda/factory/css/${item}`} />
    ))

    jsTilda = jsTilda.map((item) => <script src={`/static/tilda/factory/js/${item}`} />)
    replaceHeadComponents([...cssTilda, ...jsTilda, ...headComponents])
  }
}
```

We have to add some custom external link before the main links to styles.

### Files gatsby-browser.js, gatsby-config.js, gatsby-node.js, gatsby-ssr.js
https://codesandbox.io/s/gatsbystarterdefault-1n15w

What can be a problem?

**Comment by pieh** [comment]
This is quirk of `gatsby-plugin-offline` that it replaces served html with it's own app shell (that will miss those extra head components.

Would it be possible to import those js and css files in about page component instead of adding those head links? Then webpack could properly bundle the code.

**Comment by FoxyGirl** [comment]
@pieh Thank you for your answer!
