### ISSUE TITLE
Gatsby does not detect/render changes to html.js

### ISSUE THREAD

**Issue by felixjung** [gatsbyjs/gatsby#1442]
When running Gatsby in develop mode, i"m having trouble getting it to detect and render changes to `html.js`. I always have to restart the develop task.

This is happening in a brand new project created with the `gatsby new` command.

Am I missing something and this is expected behavior?

Files below. I have not created any of the `.js` files for interacting with the gatsby node, ssr, browser APIs, yet.

**gatsby.config.js**
```javascript
module.exports = {
  siteMetadata: {
    title: 'my cool title'
  },
  plugins: [
    'gatsby-plugin-catch-links',
    'gatsby-plugin-glamor',
    'gatsby-plugin-preact'
  ]
}
```

**package.json**
```json
{
  "name": "",
  "description": "",
  "version": "1.0.0",
  "author": "",
  "dependencies": {
    "gatsby": "^1.0.1",
    "gatsby-link": "^1.0.1",
    "gatsby-plugin-catch-links": "^1.0.1",
    "gatsby-plugin-glamor": "^1.0.6",
    "gatsby-plugin-preact": "^1.0.1",
    "gatsby-plugin-react-helmet": "^1.0.1",
    "glamor": "^3.0.0-2",
    "glamorous": "^3.23.5",
    "lodash": "^4.17.4",
    "preact": "^8.1.0"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^4.2.0",
    "eslint-config-prettier": "^2.3.0",
    "eslint-config-xo": "^0.18.2",
    "eslint-formatter-pretty": "^1.1.0",
    "eslint-import-resolver-webpack": "^0.8.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-prettier": "^2.1.2",
    "eslint-plugin-react": "^7.1.0",
    "husky": "^0.14.3",
    "lint-staged": "^4.0.1"
  },
  "keywords": [
    "blog",
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "start": "gatsby develop",
    "test": "echo \"Error: no test specified\" && exit 1",
    "precommit": "lint-staged",
    "test:lint": "eslint --cache src/**/*.js",
    "fix:prettier": "prettier --no-semi --single-quote true --write src/**/*.js",
    "fix:eslint": "eslint --fix --quiet src/**/*.js",
    "fix": "npm run fix:prettier && npm run fix:eslint"
  },
  "lint-staged": {
    "src/**/*.js": [
      "prettier --no-semi --single-quote true --write",
      "eslint --fix",
      "git add"
    ]
  }
}
```

**Comment by KyleAMathews** [comment]
What is home.js?

**Comment by felixjung** [comment]
Sorry @KyleAMathews. Obviously shouldn't have pressed the send button just, yet. Added some more details and fixed the file name. Of course I meant `html.js`.

**Comment by KyleAMathews** [comment]
Ah :-) no this is the expected behavior ATM. It'd be possible to make changes to the html.js file hot reload just hasn't happened yet. Interested in taking it on?

**Comment by felixjung** [comment]
Sure, can you point me in the right direction?

**Comment by KyleAMathews** [comment]
great!

So the magic all happens in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/develop.js and https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/develop-html.js

Basically the changes you'd need to make are

1. watch the html file & any gatsby-ssr.js files (as those can affect the finished rendered html file) in the site
2. on a change, re-build the development index.html page
3. trigger the client to reload to get the latest changes.

On the last point, I've been thinking for a while it'd be convenient to have a way for the dev server and dev client runtime to have a way to communicate over websockets as then plugins and core could expose ways for people to configure their site in the browser and have that persisted to gatsby-config.js for example or elsewhere. This could be a first exploration of that idea.

To setup the websocket (or whatever way you think best for the client/server communication), you'll want to add that to develop.js and https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/cache-dir/root.js

**Comment by patricksimpson** [comment]
Interesting. I am having a similar issue, but not sure it's related or not. I am quite new to gatsby. So,  I am not getting any changes to `html.js`, no matter if stop and re-run the develop script. 

I am running gatsby version 1.0.11, I was mostly following the tutorial and taking examples from the gatsby-sass example. 

My files are currently:

├── components
│   └── navigation
│       └── index.js
├── favicon.ico
├── html.js
├── layouts
│   └── index.js
├── pages
│   ├── about.js
│   └── index.js
└── styles
    └── main.scss

Doesn't gatsby automatically look for and use the `html.js` file?

**Comment by felixjung** [comment]
From my end this can be closed. #1473 addressed this for me.

**Comment by Madgeniusblink** [comment]
Does anyone know how to have the DOM render a contact form when it's coming from a portal? in the main render/ load of HTML my portal div appears empty. but when I toggle the button then it renders the content. The reason why I ask is that it seems to be affecting Netlify Form. meaning that Netlify form bot can not find my form there for it's not working.
