### ISSUE TITLE
Work with Jarmo to set up funnel for OSS usage

### ISSUE THREAD

**Issue by prestonso** [gatsbyjs/gatsby#14430]
Instead of a traditional funnel, let's just measure how long it takes for people to get from 
1. When telemetry starts tracking them
2. They see hot reloading for the first time

And perhaps, if possible, what they do in between those two steps.

We're trying to make sure people see hot reloading as fast as possible, because it's the first big WOW moment, so we need to know how long it takes now so we can tell if we're making it faster.

@jamo ^ edit from the future!

**Comment by prestonso** [comment]
This replaces gatsby-inc/mansion#3421.

**Comment by jamo** [comment]
Added a chart to the internal gatsbyjs dasbhoard.
