### ISSUE TITLE
Change Helmet.rewind to Helmet.renderStatic

### ISSUE THREAD

**Issue by ricardocosta89** [gatsbyjs/gatsby#1443]
According to [Helmet's release notes](https://github.com/nfl/react-helmet/blob/07851a670f2342161c128558f8e17cbffbd61dfd/CHANGELOG.md#500-2017-03-21), `Helmet.rewind()` will be deprecated in the future and the recommendation is now `Helmet.renderStatic()`.

I've looked at the several available starters and `rewind` seems to be used throughout, hence opening the issue in the top project. Is there a generator for the several starters or does it require a manual change in each of them?

Thanks. 🙂

**Comment by KyleAMathews** [comment]
Actually been replacing server rendering of React Helmet in v1 starters with https://www.gatsbyjs.org/docs/packages/gatsby-plugin-react-helmet/ (where we are using renderStatic). Feel free to PR fixes to starters to use gatsby-plugin-react-helmet!

**Comment by ricardocosta89** [comment]
From what I've seen, the starters are already using the plugin. However, all of them have a call to `Helmet.rewind()` in `html.js` that should be changed to `Helmet.renderStatic()`.
I can PR that change, I was just wandering if they are generated from a single source or if multiple PRs are needed, one for each starter.

**Comment by KyleAMathews** [comment]
Removed old unused code for react-helmet in the default/blog starter + this one example site (wordpress) that had some helmet code in html.js.

Anywhere else that needs cleaned up?

**Comment by ricardocosta89** [comment]
Thanks, @KyleAMathews! 👍 

I think the only one missing is `gatsby-starter-kitchen-sink`, but I'm not sure if that's up to date.

**Comment by KyleAMathews** [comment]
Oh right, yeah that one hasn't been updated yet to Gatsby v1 (and might not be as it was meant to be a comprehensive demo of what Gatsby can do and Gatsby can way way more things now (and constantly expanding to as people add more plugins)).

Feel free to update that one as well!

**Comment by ricardocosta89** [comment]
Well, if it is "deprecated" maybe it is not worth to update. But I'd put something in the README so people don't follow it on new projects. 😄
