### ISSUE TITLE
Cannot add as Composer type following value: Date.

### ISSUE THREAD

**Issue by lukedohner** [gatsbyjs/gatsby#14439]
## Description

On Gatsby Develop I get this error:
Lukes-MacBook-Pro-5% gatsby develop
success open and validate gatsby-configs — 0.017 s
success load plugins — 1.997 s
success onPreInit — 0.092 s
success initialize cache — 0.023 s
success copy gatsby files — 0.432 s
success onPreBootstrap — 0.022 s
success source and transform nodes — 0.298 s
⠁ error UNHANDLED REJECTION

  Error: Cannot add as Composer type following value: Date.
  
  - SchemaComposer.js:391 SchemaComposer.addAsComposer
    [gatsby-site]/[graphql-compose]/lib/SchemaComposer.js:391:11
  
  - schema-composer.js:21 createSchemaComposer
    [gatsby-site]/[gatsby]/dist/schema/schema-composer.js:21:18
  
  - index.js:42 Object.<anonymous>
    [gatsby-site]/[gatsby]/dist/schema/index.js:42:28
  
  - Generator.next
  
  - new Promise
  
  - index.js:65 Object.build
    [gatsby-site]/[gatsby]/dist/schema/index.js:65:17
  
  - index.js:340 
    [gatsby-site]/[gatsby]/dist/bootstrap/index.js:340:32
  
  - Generator.next

### Steps to reproduce

The error first started when I installed react-muuri.
Seems to be an issue with GraphQL. 

I installed the latest GraphQL.

thanks for any ideas!
Luke

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.4.2 => 2.4.2 
    gatsby-image: ^2.0.20 => 2.0.25 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12 
    gatsby-plugin-offline: ^2.0.16 => 2.0.20 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-source-filesystem: ^2.0.33 => 2.0.33 
    gatsby-source-google-docs: ^1.6.0 => 1.6.0 
    gatsby-source-google-sheets: ^1.1.1 => 1.1.1 
    gatsby-source-graphql: ^2.0.18 => 2.0.18 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9 
  npmGlobalPackages:
    gatsby-cli: 2.6.3

//

**Comment by lukedohner** [comment]
Not sure what the gatsbot wants me to do. The body of this issue is not blank. (?)

**Comment by stefanprobst** [comment]
@lukedohner yes the error message indicates that there are probably conflicting `graphql` packages (the message is just the first possible error thrown by the `graphql-compose` package we use).

what does `yarn list graphql` show?

**Comment by lukedohner** [comment]
I used npm list graphql ...
```
npm list graphql
gatsby-starter-default@2.6.3 /luke_projects_all/Luke-site-calypsoBootstrap/calypso/gatsby-ld/gatsby-site
└─┬ gatsby@2.4.2
  └── graphql@14.3.1 
```

Does that mean there are two versions of graphql? How do I delete the older version? 
thanks!

**Comment by m-allanson** [comment]
Here's a related issue, maybe the steps in there are useful? https://github.com/gatsbyjs/gatsby/issues/14411

**Comment by stefanprobst** [comment]
@lukedohner would you be able to provide a small repo to reproduce the error so we could look into this? Thanks!

**Comment by lukedohner** [comment]
I solved the issue by using the Gatsby Debug starter.  Added each import, page and component testing develop and build along the way.
I did not get anymore react-muuri or graphQL errors. I am not sure what is different but it worked.
