### ISSUE TITLE
Users should experience hot reloading as soon as possible

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/gatsby#14432]
## Description
Users should experience hot reloading as soon as possible because it is a crucial taste of the important value that Gatsby provides--fast in every way that matters. A faster editing/development cycle is a huge part of why people like Gatsby, but we don't yet know *how* fast the cycle is and whether we could make it faster.

Measure how long it takes from the time people install Gatsby CLI until they visit localhost:8000 (after running `gatsby develop`). We want to know how long it takes before people get their first rewarding "wow" moment so we have a baseline to measure against as we try to reduce that amount of time.

## Actionable steps
@jamo to figure out how to measure this

## After this issue is done
After we have a baseline measurement, we can figure out if we can/should help people experience hot reloading even faster than they do now and we can decide the steps to reach that goal. 

Note:
This is replacing issue https://github.com/gatsby-inc/mansion/issues/3422 (Set up goals for OSS funnel and alerts when we don't meet the goals).

**Comment by sidharthachatterjee** [comment]
Closing this for now since:

- we measure much of this in telemetry
- this issue mentions _what_ but doesn't illustrate _how_ which I think is crucial in this particular instance
