### ISSUE TITLE
Questions regarding createResolvers

### ISSUE THREAD

**Issue by alexluong** [gatsbyjs/gatsby#14436]
# Thoughts

After learning more about the new Schema Customization API, I have a few questions regarding `createResolvers`.

Based on what I'm understanding, `createResolvers` is a Gatsby Node API which will be called at the last step before the schema is generated.

Inside this event, there is a parameter called `createResolvers`, which actually performs the task of creating GraphQL resolvers.

I understand the original idea of this API is for people to, well, create resolvers. However, I can see there are more use cases for this beyond just that.

# Example

For example, I can clone or change a Node type:

```js
exports.createResolvers = function ({ getNodesByType, actions: { createNode, deleteNode } }) {
  const markdownNodes = getNodesByType("MarkdownRemark")
  markdownNodes.forEach(node => {
    createNode(...someData, { type: "BlogPost", ...someOtherData })
    deleteNode({ node })
  })
}
```

This is a use case that I've wanted for a while but was not able to perform. With this new `createResolvers` API, I can finally do it. Besides, having access to the entire finished node system is quite powerful for users.

# Summary

Therefore, I'm wondering if `createResolvers` is the best name for the API. Would something like `onPreSchemaGeneration` makes more sense?

Just a thought while I'm learning more about Schema Customization. And lastly, amazing work everybody on this topic. It really opens the door to many cool things people can do with Gatsby!

**Comment by pieh** [comment]
I'm not sure if manipulating nodes is safe there. We might move API around in the future that it will break this accidental feature

/cc @freiksenet @stefanprobst

**Comment by alexluong** [comment]
@pieh That makes sense. If that's the case, maybe there needs to be some sort of rules/warning against manipulating nodes in that event?

In the mean time, do you know if it's impossible to manipulate nodes after `setFieldsOnNodeType`?

**Comment by freiksenet** [comment]
Most probably, we'll remove ability to manipulate nodes in node API steps after `sourceNodes`. See [this PR](https://github.com/gatsbyjs/gatsby/pull/14283).

**Comment by alexluong** [comment]
This makes sense. Although it's quite frustrating when I try to manipulate nodes and don't get the full data because `setFieldsOnGraphQLNodeType`'s generated fields are not accessible. Not sure if there's any way around it though.

**Comment by freiksenet** [comment]
We are working on improving the way it works, so that you can ask to "materialize" the node using the resolvers on it's type. This won't work with `setFieldsOnGraphQLNodeType` (and we are likely to mark that API deprecated in v3), but it will work with `createTypes`, which is a preferred API now.

**Comment by alexluong** [comment]
Sounds great. That's the feature I'm looking for. Looking forward to v3 then.

**Comment by Jaikant** [comment]
> I'm not sure if manipulating nodes is safe there. We might move API around in the future that it will break this accidental feature
> 
> /cc @freiksenet @stefanprobst

@pieh @freiksenet This example in the docs does a createRemoteNode in the createResolvers. Is this alright? https://www.gatsbyjs.org/docs/schema-customization/#feeding-remote-images-into-gatsby-image. I am using the gatsby-graphql-plugin and need to create a node in the resolver, so I can get the benefits of the sift.js library while querying.
