### ISSUE TITLE
Google complaining about redirects and curling any page returns homepage

### ISSUE THREAD

**Issue by jrusso1020** [gatsbyjs/gatsby#14441]
## Description
My google search console is complaining all of my pages besides my homepage are either redirects or Duplicate without user-selected canonical. As you can imagine this is causing SEO problems for me because no pages besides my homepage can be listed and I'm getting dinged for having duplicates/redirects.

Also whenever I curl any page on my website I only ever get my homepage, regardless of path. However the response code is always a 200.

This post looks similar https://github.com/gatsbyjs/gatsby/issues/9207 but I don't think it's quite the same problem

Also my repo of my website is public and available to see here https://github.com/jrusso1020/anakin

### Steps to reproduce
website: https://boredhacking.com 

Curl any page on my website `curl https://boredhacking.com`, `curl https://boredhacking.com/about`, `curl https://boredhacking.com/segment-event-pipeline/`, etc... They all seemingly return the same html for the homepage.

I'm not sure how to recreate the search console results...

### Expected result
My website should be crawlable and indexable, and curl each page on my website should return the html for that page

### Actual result
Curling any page returns the html for the homepage

### Environment
  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 3.5.2 - /Users/james/anaconda3/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.5.3 => 2.5.3 
    gatsby-image: ^2.0.33 => 2.0.33 
    gatsby-plugin-catch-links: ^2.0.13 => 2.0.13 
    gatsby-plugin-feed: ^2.0.15 => 2.0.15 
    gatsby-plugin-google-analytics: ^2.0.17 => 2.0.17 
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.9 => 3.0.9 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-s3: ^0.2.5 => 0.2.5 
    gatsby-plugin-sharp: ^2.0.28 => 2.0.28 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-typography: ^2.2.9 => 2.2.9 
    gatsby-remark-copy-linked-files: ^2.0.10 => 2.0.10 
    gatsby-remark-embed-gist: ^1.1.7 => 1.1.7 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-remark-prismjs: ^3.2.5 => 3.2.5 
    gatsby-remark-responsive-iframe: ^2.0.10 => 2.0.10 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.24 => 2.0.24 
    gatsby-transformer-remark: ^2.3.2 => 2.3.2 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby: 2.5.0

**Comment by cameron-martin** [comment]
It appears not much is getting server-side rendered:

```
<div id="___gatsby"><div style="outline:none" tabindex="-1" role="group"></div></div>
```

But why? :thinking:

**Comment by DSchau** [comment]
@cameron-martin that's unrelated (and not an issue!) related to [gatsby-plugin-offline and a Chrome bug](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/#empty-view-source-and-seo)

@jrusso1020 I can definitely confirm the issue, but it seems to be something with how the site is deployed or something else. That's based on the fact that:

1. `yarn build`
1. `yarn serve`
1. `curl http://localhost:9000/about/ | grep about`

works like you'd expect.

How are you deploying this? Are you using Netlify?

**Comment by jrusso1020** [comment]
@DSchau I’ve deployed my site to an S3 bucket with cloudfront in front of it as a CDN

**Comment by DSchau** [comment]
You have the S3 bucket configured for Static Website Hosting right?

![Screen Shot 2019-05-30 at 4 47 52 PM](https://user-images.githubusercontent.com/3924690/58667086-b3b61400-82fa-11e9-8f8c-ea8d848783f1.png)

**Comment by jrusso1020** [comment]
@DSchau This is how I have s3 configured
<img width="544" alt="Screen Shot 2019-05-30 at 6 56 16 PM" src="https://user-images.githubusercontent.com/7664106/58670349-b91c5a00-830c-11e9-8e01-03baa008548d.png">

**Comment by jrusso1020** [comment]
I think I was able to fix it by using the endpoint url of the s3 bucket when creating the origin in cloudfront. I found that bit of information here https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront/#setting-up-cloudfront but now I have the problem described in #9207 where if you forget the trailing slash then you get a redirect
