### ISSUE TITLE
gatsby-remark-images & netlify-cms - Cannot query field "childImageSharp" on type "File".

### ISSUE THREAD

**Issue by aldomonteiro** [gatsbyjs/gatsby#14446]
I am using netlify-cms to create my markdown files. They have a field called `cover` that is an image path.

I found that `onCreateNode` on `gatsby-node.js` could convert this string into a `gatsby-image`, but it is only converting it to a File.

Below the onCreateNode code:

```javascript
exports.onCreateNode = ({ node, actions }) => {
  const { createNodeField } = actions;

  const { frontmatter } = node;
  if (frontmatter) {
    const { cover } = frontmatter
    if (cover) {
      const coverPath = path.relative(
        path.dirname(node.fileAbsolutePath),
        path.join(__dirname, '/static/', cover)
      )
      createNodeField({
        node,
        name: 'coverImg',
        value: coverPath
      });
    }
  }
};
```
It is almost working. It is converting the image string to a File, as I can see in the graphql:

```graphql
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "frontmatter": {
              "title": "Hello Gatsby",
              "path": "/blog/hello-gatsby",
              "cover": "/assets/gatsby-logo.jpeg"
            },
            "fields": {
              "coverImg": {
                "id": "35707c9b-8ba7-5a5f-bfe9-57266f2d5d83",
                "absolutePath": "/Users/aldo/DEV/Gatsby/netlify_blog/static/assets/gatsby-logo.jpeg"
              }
            }
          }
        },
```
When I try to query childImageSharp field as below:

```graphql
           ....
           fields {
              coverImg {
                id
                childImageSharp {
                  fluid(maxWidth: 590, maxHeight: 265) {
                    src
                  }
```

It raises an error:

**GraphQLError: Cannot query field "childImageSharp" on type "File".**

Here the links to: [gatsby-node.js](https://github.com/aldomonteiro/blog/blob/master/gatsby-node.js), [gatsby-config.js](https://github.com/aldomonteiro/blog/blob/master/gatsby-config.js) and [package.json](https://github.com/aldomonteiro/blog/blob/master/package.json).

What is missing?

**Comment by jonniebigodes** [comment]
@aldomonteiro take a look at [this](https://github.com/jonniebigodes/test_gatsby_netlify_cms) for a way to   have netlify cms and gatsby "playing nice" and being able to fetch the content and more specifically the cover/featured images and a detailed explanation for the code in [here](https://github.com/gatsbyjs/gatsby/issues/12610#issuecomment-475992459)

**Comment by aldomonteiro** [comment]
@jonniebigodes I compared my code with yours and made the changes to be the very same and it worked fine! Thank you so much.
