### ISSUE TITLE
[gatsby-plugin-sharp] imagemin-pngquant fails to process images larger than 10 MB

### ISSUE THREAD

**Issue by TitanNano** [gatsbyjs/gatsby#14453]
`imagemin-pngquant` had an unintended limit of 10 MB for some of it's buffers. This causes the library to fail a processing images larger than 10 MB. This was fixed in version 6.0.1 and higher, it would be great if `gatsby-plugin-sharp` could update to at least `imagemin-pngquant@6.0.1`

**Comment by pieh** [comment]
We use caret version selector in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/package.json#L16
so 6.0.1 should be installed (and I verified that this is happening with both npm and yarn)

Can you check what version is being used for you?
```
npm list imagemin-pngquant

or

yarn why imagemin-pngquant
```

**Comment by pieh** [comment]
It would also be helpful to provide [reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) for this issue - as there might be more than `imagemin-pngquant` that cause problems here

**Comment by TitanNano** [comment]
@pieh you are right, this was a mistake on my end. Updating the dependencies of `gatsby-plugin-sharp` fixed the issues.
