### ISSUE TITLE
[www/showcase] Twitter cards not working for individual "Showcase" entries

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#14468]
Happened to all three URLs I tested:

![image](https://user-images.githubusercontent.com/21834/58722475-cc482c00-83d7-11e9-829e-52e7c2b99688.png)

**Comment by rlynn523** [comment]
I would like to pick this up if possible

**Comment by fk** [comment]
Hey @rlynn523, that'd be great! 🙏

**Comment by rlynn523** [comment]
@fk is there a dev or test env I can deploy to? I can only really validate the twitter cards when the code is deployed. I tried to use ngrok, but it didn't seem to work with the Twitter Card Validator. I could also just push my forked repo to gh-pages or something...what do you recommend?

**Comment by fk** [comment]
> I can only really validate the twitter cards when the code is deployed. I tried to use ngrok, but it didn't seem to work with the Twitter Card Validator.

💯 Yeah … hmm, ngrok _should_ work — I used it before to test with the Twitter Card Validator. Did you try it with `develop` or `build`? I think I was successful with the latter. Want to give it another chance?

Alternatively, you could build `www` with `GATSBY_SCREENSHOT_PLACEHOLDER=true` in `.env.production` (see https://github.com/gatsbyjs/gatsby/tree/master/www#running-slow-build-screenshots-placeholder — `GATSBY_SCREENSHOT_PLACEHOLDER=true` also works for prod), and upload to Netlify. But that means uploading 1,5 GB if I remember correctly. :(

**Comment by rlynn523** [comment]
I only tried it with `develop` but will see if using `build` works. Thanks!

**Comment by fk** [comment]
Sure! You're welcome! Crossing fingers! 🤞
Thanks for looking into this!

**Comment by rlynn523** [comment]
<img width="458" alt="twitter-card" src="https://user-images.githubusercontent.com/18073651/59139043-95858f00-895e-11e9-955c-856f502a9ff5.png">

It worked! I ended up creating a `SocialMetaTags` component that will create `og` and `twitter` meta tags. I did have one question, if a site in the showcase does not have a description, is there any copy you would like to use as a fallback? Something with the title maybe? Let me know if this is what you were expecting! I did see that there was a ticket in to fix which image is used in the cards...I can update that here or it can be resolved later and passed as props to the new component.

**Comment by rlynn523** [comment]
Also, by updating the `SiteMetadata` component, you can pass in more props to the `Layout` component which will make cards available across the site. Is that something you would want?
<img width="497" alt="Screen Shot 2019-06-08 at 10 38 38 AM" src="https://user-images.githubusercontent.com/18073651/59148671-e1294e80-89d9-11e9-9b51-913a5f8f0c04.png">

**Comment by fk** [comment]
> It worked!

Yay, happy to hear that!!

> I did have one question, if a site in the showcase does not have a description, is there any copy you would like to use as a fallback? Something with the title maybe?

Yes, good call! Maybe even with the URL of the showcased site? Might be easier to write copy for that than for the site title?

> Let me know if this is what you were expecting!

🙏👌Looks like the Twitter cards are working, so yes, absolutely! 

> I did see that there was a ticket in to fix which image is used in the cards...I can update that here or it can be resolved later.

That's #14469; about to merge the PR that fixes that.
Do you want to open a PR with your work, and continue the discussion there?

> Also, by updating the `SiteMetadata` component, you can pass in more props to the `Layout` component which will make cards available across the site. Is that something you would want?

Hmm, maybe open a new issue for that?

**Comment by fk** [comment]
Hey again @rlynn523!

So I just fixed and merged https://github.com/gatsbyjs/gatsby/pull/14560.
To do that, I—unfortunately, because I'd hate it if you got the feeling that your work isn't valued and appreciated!! 🙏—needed to fix `og:title`, which rudimentarily solves this issue, too. I did not add descriptions however—would you still be up for that? 🙏 🤞

**Comment by rlynn523** [comment]
Yes I can update that. My fix involved updating the `SiteMetaData` component that's pulled into the `Layout` component, and then just passing in the necessary props. It will generate both `og` and `twitter` tags. If you are ok with this fix, you can then add Twitter tags to other parts of the site. This should hopefully fix this issue for the future.

**Comment by rlynn523** [comment]
I can also just include the description in `showcase-details` and create an issue like you mentioned, and say that I have a solution for implementing global twitter cards?

**Comment by jjcav84** [comment]
I am new here and everything but I say fix and PR.

**Comment by fk** [comment]
☝️ 💯Hey @jjcav84! 👋 — @rlynn523 Do you want to open a ([draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/)) PR with your work?

**Comment by jjcav84** [comment]
> ☝️ 💯Hey @jjcav84! 👋 — @rlynn523 Do you want to open a ([draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/)) PR with your work?

Hmm I hadn't thought about that until now. I am built a mock employee directory using the character data from the Rick and Morty GraphQL API using the first page (20 characters) and I would like to add all of them about 500 characters and paginate it as well as a way to have a form that you can create update and delete characters from the directory but I got a bit stuck there. I'm sure someone could help out with that and it will give them the opportunity for an initial contribution.  Hmmmm.

**Comment by rlynn523** [comment]
> ☝️ 💯Hey @jjcav84! 👋 — @rlynn523 Do you want to open a ([draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/)) PR with your work?

Sounds great, I'll push that tonight!

**Comment by rlynn523** [comment]
@fk here is a link to the PR for just adding the description to the Twitter cards: https://github.com/gatsbyjs/gatsby/pull/14721

I will open a draft PR with the changes to `SiteMetaData` to allow for the configuration of Twitter tags on any page that pulls in `Layout`. I'll add the link when it's in. There are no tests for the changes, but if it is something that you think would be useful, I'll update and add tests.

**Comment by rlynn523** [comment]
@fk there they are! I did notice that when I navigated from one page to a showcase site, that the meta data in the head did not change (and remained the default values), but hitting that page directly updated the meta data. When using the twitter card validator, there were no issues, most likely due to it grabbing the page directly. If this is a problem, I can probably extract out the logic I have in `SiteMetaData` and create a component like  `SocialMetaTags` that can be pulled into pages to render the title, description, etc. by just passing props.

**Comment by fk** [comment]
Hey y'all, going to close this as the issue described here was fixed in #14560 and #14721.

@rlynn523 Thanks again for all your work here! As I'm trying to catch up on things, do I understand correctly that you opened #14725 to address the issues you mentioned in https://github.com/gatsbyjs/gatsby/issues/14468#issuecomment-501093683?

**Comment by rlynn523** [comment]
@fk yes that is correct!
