### ISSUE TITLE
Field "image" must not have a selection since type "String" has no subfields.

### ISSUE THREAD

**Issue by scotNZ** [gatsbyjs/gatsby#14460]
## Description

As described in various other issues, this error is sometimes thrown when an gatsby-image field is referenced in a GraphQL query. :

 "Field image must not have a selection since type String has no subfields" 

### Steps to reproduce

I first encountered this error when referencing a specific image file that should have been selected by my query but happened to be missing from my images folder.  However, the error is sensitive to the position of the missing image in the selection generated by the query.

If the first image selected by the query happens not to be in the folder, the error is thrown. If the first image is present and other images are missing, the error is not thrown.

In the case where the first image is missing, as soon as I lodge the file back in the folder (after cleaning the cache) the error disappears.

### Expected result

I guess I expect the query to be more robust and to generate an informative error message.

The fact that it appears to be sensitive to position in the list of images in the query set may explain the reports from others that the error comes and goes (no doubt compounded by the need to clear the cache and restart).

### Actual result

Error is seen in terminal and can also be seen in Graphiql:

"Field "image" must not have a selection since type "String" has no subfields."

Error disappeared when file was placed back in folder. Error did not appear at all if the missing file was not first in the list of selected images.

### Environment
System:
    OS: Windows 8.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.13
  npmPackages:
    gatsby: ^2.7.1 => 2.7.1
    gatsby-image: ^2.1.0 => 2.1.0
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.1.0 => 2.1.0
    gatsby-source-filesystem: ^2.0.37 => 2.0.37
    gatsby-transformer-json: ^2.1.11 => 2.1.11
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19

**Comment by pieh** [comment]
You can harden generated schema using:
```
exports.sourceNodes = ({ actions }) => {
  const { createTypes } = actions
  const typeDefs = `
    type MarkdownRemark implements Node @infer {
      frontmatter: Frontmatter!
    }

    type Frontmatter @infer {
      image: File @fileByRelativePath
    }
```

And yes, we do agree that error message is not conveying much, but this error will happen for multiple different reasons and it's hard to figure out if this error happens because of shape of the schema or actual user error

**Comment by scotNZ** [comment]
Hi

Yeh, I understand.

Just think the apparent inconsistency of what I was seeing was worth recording for others.

For anyone following along, this may help you based on my experience:

If you are referring to image elements contained in an array, make sure the first image file in the array is being referred to correctly and it is present in the target folder. In my case a missing image not at the first position in the selection did not lead to the error.

In my case the array was nested in a non-shallow json construct which may have contributed but I don't know.

Just another thing to check ...

Closing.

**Comment by scotNZ** [comment]
There appear to be many issues with inferred schemas. Anyone with complex data constructs causing trouble might be better served through a custom schema: [https://www.gatsbyjs.org/docs/schema-customization/](url)

**Comment by mikheevm** [comment]
The solution here solved issue in my case.
