### ISSUE TITLE
Google Analytics plugin page broken

### ISSUE THREAD

**Issue by Chalarangelo** [gatsbyjs/gatsby#14466]
## Description

Blank page for the [Google Analytics plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/) documentation.

### Steps to reproduce

Visit https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/

### Expected result

Documentation for the plugin.

### Actual result

Blank page.

### Environment

Documentation page for the plugin, Firefox 68 on Windows 10.

**Comment by DSchau** [comment]
Unfortunately, this is a known issue with ad blockers (and the hashes that we create).

If you open the page in Incognito (or Firefox's equivalent, e.g. Private Browsing), it should display just fine.

We are tracking on the ad blocker hash issue in #8307 

Thanks for opening! Please reply or re-open if we can help further.
