### ISSUE TITLE
[themes] How do you reference theme components in your consuming application?

### ISSUE THREAD

**Issue by maecapozzi** [gatsbyjs/gatsby#14462]
## Summary

It's not clear to me from the documentation how to resolve a component from my theme in my actual application. So if I have a theme called `gatsby-theme-a` with a `Layout` component in it, when I'm in `my-app`, how do I actually import that `Layout` component. Is this possible?

**Comment by DSchau** [comment]
Should be!

Just import it by its path on your filesystem, for instance in this case it'd be:

```js
import React from 'react'

import Layout from 'gatsby-theme-a/src/components/layout'

export default () => (
  <Layout>
    <h1>I am wrapped by a custom layout component</h1>
  </Layout>
)
```

(also we'd love any documentation tweaks to clarify this!)

**Comment by maecapozzi** [comment]
Hey @DSchau, thanks so much! Nailed it! You'll see a PR from me to try to make this even clearer in the docs soon :)
