### ISSUE TITLE
Local gatsby development builds hang after "success extract queries from components"

### ISSUE THREAD

**Issue by bbaker6225** [gatsbyjs/gatsby#14467]
## Description
When running a gatsby development build, after we source our nodes and build our schema, the build gets to the line `success extract queries from components — 1.340 s` and then hangs for several minutes before continuing

### Steps to reproduce
This issue occurs when running `make develop` locally for the gatsby project in https://github.com/edx/prospectus

### Expected result

The build should not hang with no indication of progress for several minutes.

### Actual result

The build does hang for several minutes with no indication of progress.

### Environment

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.2 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 65.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.2.0 => 2.4.2 
    gatsby-cli: ^2.4.15 => 2.5.12 
    gatsby-image: ^2.0.33 => 2.0.41 
    gatsby-link: ^2.0.16 => 2.1.1 
    gatsby-node-helpers: ^0.3.0 => 0.3.0 
    gatsby-plugin-intl: ^0.1.7 => 0.1.7 
    gatsby-plugin-netlify: ^2.0.12 => 2.0.16 
    gatsby-plugin-netlify-cms: ^3.0.14 => 3.0.18 
    gatsby-plugin-react-helmet: ^3.0.9 => 3.0.12 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-segment-js: ^3.0.1 => 3.0.1 
    gatsby-plugin-sharp: ^2.0.28 => 2.0.36 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.0.25 => 2.0.33 
    gatsby-transformer-json: ^2.1.10 => 2.1.11 
    gatsby-transformer-remark: ^2.3.3 => 2.3.12 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

Thanks for the help

**Comment by jonniebigodes** [comment]
@bbaker6225 could you provide a reproduction following these [steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) or adjust the link you supplied, because is leading to a non existing page

**Comment by bbaker6225** [comment]
Ah sorry, the repo is a private repo that I unfortunately don't have the ability to grant access to, and I've been unable to recreate the issue with a small gatsby starter project thus far
