### ISSUE TITLE
[www/showcase] "Showcase" entry uses square image as meta `twitter:image`

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#14469]
E.g. for https://www.gatsbyjs.org/showcase/airbnb.io/ we are setting

<img src="https://www.gatsbyjs.org/static/cbaf442ed29638ce3775856ede4ac483/ef52a/8990f01f5a6d31fce109c16ab078b499.jpg" />

as `twitter:image`.
Let's share the uncropped image instead:

<img src="https://www.gatsbyjs.org/static/cbaf442ed29638ce3775856ede4ac483/54c56/8990f01f5a6d31fce109c16ab078b499.png" />

**Comment by odm275** [comment]
Hey! I'd like to give this a shot if possible.

**Comment by odm275** [comment]
Been trying to get started on this but I'm not exactly sure now. This is my first issue! If you could provide me with some extra context please.

**Comment by superhawk610** [comment]
@fk looks like your link is broken, would you mind reuploading?

**Comment by superhawk610** [comment]
@odm275 the React component responsible for rendering the showcase details view can be found in `www/src/components/showcase-details` [here](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/showcase-details.js#L253). The meta tags responsible for setting `og:image` and `twitter:image` are set by `react-helmet` via the `<Helmet />` component. You should be able to get it from there :smiley:

**Comment by abhijithvijayan** [comment]
@superhawk610 How can I run this on dev mode, I tried running `gatsby develop` under `www` dir, but that kept on reaching watcher file count limit.

**Comment by wardpeet** [comment]
Watcher issues can be resolved by https://github.com/gatsbyjs/gatsby/issues/11406#issuecomment-458769756.

as @superhawk610 mentioned the code is https://github.com/gatsbyjs/gatsby/blob/542cdb29d12601c0e4a2afde4012059e107e4e11/www/src/components/showcase-details.js#L255-L268

And I believe we want to change `data.sitesYaml.childScreenshot.screenshotFile.childImageSharp.resize.src` into `data.sitesYaml.childScreenshot.screenshotFile.publicURL`

which also means you'll need to add publicURL to https://github.com/gatsbyjs/gatsby/blob/a82a9adc4599f89daa7a44ec849d7e4009be878e/www/src/components/showcase-details.js#L125-L131

**Comment by abhijithvijayan** [comment]
@wardpeet I can take this.

**Comment by odm275** [comment]
@superhawk610 Thanks for the clarification! I think I got this.

**Comment by fk** [comment]
Sorry for only being able to follow up here today! Thanks for helping out everybody!
