### ISSUE TITLE
Question on wrapPageElement

### ISSUE THREAD

**Issue by kajchang** [gatsbyjs/gatsby#14479]
## Description

For my project, I have recently moved my `MUIThemeProvider` to `wrapPageElement` in `gatsby-browser.js`.
```js
export const wrapPageElement = ({ element }) => (
    <MuiThemeProvider theme={ theme }>
        { element }
    </MuiThemeProvider>
);
```
When I build, the styles are incorrect.
I was wondering if it's a problem with `wrapPageElement` getting called after the SSR for `gatsby-plugin-material-ui` has finished, somehow messing up the styles, and if I shouldn't be using `wrapPageElement` for this.

### Steps to reproduce

I can mock up an example if this is unintended behavior.

### Expected result

The styles should be correct.

### Actual result

The styles are incorrect.

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.4.3 => 2.7.1 
    gatsby-image: ^2.1.2 => 2.1.2 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-google-analytics: ^2.0.20 => 2.0.20 
    gatsby-plugin-material-ui: ^1.2.5 => 1.2.5 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-remove-trailing-slashes: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3 
    gatsby-source-filesystem: ^2.0.38 => 2.0.38 
    gatsby-source-mongodb: ^2.0.18 => 2.0.18 
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21 

Thanks in advance!

**Comment by MarkosKon** [comment]
You may have to do the same for `gatsby-ssr.js`. [See this](https://github.com/gatsbyjs/gatsby/issues/11494#issuecomment-460058623).

**Comment by kajchang** [comment]
Ok, thanks!
