### ISSUE TITLE
[gatsby-remark-images] When using `showCaption`, parse the caption as markdown

### ISSUE THREAD

**Issue by mathieudutour** [gatsbyjs/gatsby#14474]
## Summary

When using `showCaptions: true` as an option for the `gatsby-remark-images`, it inserts the title of the image as raw html.
How about considering the caption as markdown and parsing it before inserting it?

### Motivation

https://github.com/mathieudutour/medium-to-own-blog/issues/5

Happy to work on it if that's something that you find interesting

**Comment by freiksenet** [comment]
It's a good idea. Could you make a PR with that change? I think it should be a new parameter, like `markdownCaptions: true`, so we preserve backwards compatability.

**Comment by mathieudutour** [comment]
Sounds good, will do

**Comment by johnletey** [comment]
@mathieudutour If you are busy, I can give this a shot!
