### ISSUE TITLE
GraphQL - sort - works locally, breaks in production

### ISSUE THREAD

**Issue by bryndyment** [gatsbyjs/gatsby#14478]
## Description

https://github.com/bryndyment/hoologic/blob/master/src/layouts/index.js#L26-L29

When including sort in my GraphQL query, the sort order works locally, but breaks in production.

Removing the sort resolves the issue in production.

Line 26 in the above URL contains the problematic sort.

Line 29 in the above URL contains the query without said sort.

### Steps to reproduce

See above for repo.  Note that the text under the images is in the correct sort order.  The images and the links are incorrect, though.

If you watch, on initial load, the text under the images initially matches the associated image, but is then overridden by different text.

### Expected result

Sort order of posts should match the sort specified in the query, and should also be consistent between `develop` and `build`.

### Actual result

Incorrect sort order in `build`.

### Environment
```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.7.5 => 2.8.0
    gatsby-plugin-google-analytics: ^2.0.20 => 2.0.20
    gatsby-plugin-layout: ^1.0.15 => 1.0.15
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-source-filesystem: ^2.0.37 => 2.0.37
    gatsby-transformer-remark: ^2.3.12 => 2.3.12
  npmGlobalPackages:
    gatsby-cli: 2.6.2
```

**Comment by muescha** [comment]
@Bryndyment

How did you resolved your issue!

**Comment by bryndyment** [comment]
It was a dumb coding mistake on my end, unrelated to GraphQL. 😄
