### ISSUE TITLE
Add Tags and Categories to Blog Posts

### ISSUE THREAD

**Issue by eclectic-coding** [gatsbyjs/gatsby#14473]
I have a question about the clarity of one of the Doc's. 

On the [Docs Page](https://www.gatsbyjs.org/docs/), there is a Link in the sidebar called: `Adding Tags and Categories to Blog Posts`, with a Page URL(https://www.gatsbyjs.org/docs/adding-tags-and-categories-to-blog-posts/) which again is entitled ` ... /adding-tags-and-categories-to-blog-posts/`. 

The problem, for clarity, is that the actual page does not mention `Categories`, only `Tags`. So the question is actually three:
- Do we need to create a Stub page with an overview of the process and design of adding Tags and Categories, pointing to two separate articles? 
- Add categories to the existing article?
- Or remove the references to Categories?

**Comment by Aswinpookkatt** [comment]
This issue is fixed now. Maintainers  plz check.
