### ISSUE TITLE
How do I make a multilingual MD/MDX Blog?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#14477]
Hi everybody,

I recently implemented some basic i18n/localization/multi-language goodness in an app I'm developing using `gatsby-plugin-intl`.

It's working pretty well, except that this plugin doesn't seem to support an  i18n/localization/multi-language blog. So I was curious if anybody has any experience doing this and could point me in the right direction. I reached out to the developer but I think they are pretty busy.

I have googled this a few times but cannot seem to find anything related to a blog specifically, only basic i18n.

So any help in the matter would be greatly appreciated. 

Thank you XD

**Comment by lannonbr** [comment]
@LekoArts has developed a example i18n blog site with Gatsby here: https://github.com/gatsbyjs/gatsby/tree/master/examples/using-i18n

**Comment by maxpou** [comment]
Hey @rchrdnsh , 
for the i18n part, you can checkout Dan Abramov's blog: https://github.com/gaearon/overreacted.io

**Comment by lannonbr** [comment]
@rchrdnsh Any update on this issue. Have you figured out how to do this?

**Comment by rchrdnsh** [comment]
I actually haven't had a chance to come back to this, but I would still like to :-)

**Comment by rchrdnsh** [comment]
hmmmm...I checked out the above example for LekoArts, but the implementation seems to be a bit broken, as clicking on a different language in a blog post switches languages, but then routes back to the home page, instead of staying in that blog post. Any thoughts @lannonbr?

**Comment by zasuh** [comment]
Has anyone found a solution to this?

**Comment by bolonio** [comment]
https://github.com/angeloocana/gatsby-plugin-i18n/pull/93
