### ISSUE TITLE
[gatsby-source-contentful] support the Preview API

### ISSUE THREAD

**Issue by ajeeshadressary** [gatsbyjs/gatsby#1448]
How can we pull data from 'preview.contentful.com' using gatsby-source-contnetful plugin?

Can we specify the hostname in the configuration(inside options{})

**Comment by KyleAMathews** [comment]
@Khaledgarbaya how would you suggest supporting the preview API? We can't use the sync API right so we'd need to support fetching solely with your pager.

Perhaps just in the options expose a `preview` which takes a true or false value. This would work well with the cache as changing the value would invalidate the cache anyways so there' wouldn't be stale data messing up things.

**Comment by Khaledgarbaya** [comment]
👋  if you change the host when creating the contentful [client](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/fetch.js#L12)  
the plugin config could look like this.

```
plugins: [
  {
    resolve: `gatsby-source-contentful`,
    options: {
      spaceId: `your_space_id`,
      accessToken: `your_acces_token`,
      host: 'preview.contentful.com'
    },
  },
]
```
One limitation though, you are only able to do an initial sync with the preview API, meaning, always get all the data and the syncToken is useless. But I think that is ok.
I'll be happy to open a PR. What do you think @KyleAMathews , @ajeeshadressary

**Comment by Khaledgarbaya** [comment]
[PR](https://github.com/gatsbyjs/gatsby/pull/1464) is ready, any feedback is welcome

**Comment by Smiter** [comment]
I just upgraded to latest Gatsby and updated my `gatsby-config` with host: `preview.contentful.com` and preview specific `accessToken` and now getting an error in my terminal:

`spaceId/accessToken source and transform nodesAccessing your Contentful space failed. Perhaps you're offline or the spaceId/accessToken is incorrect.`

help.. :)

**Comment by Khaledgarbaya** [comment]
I think the new changes were not published yet, try to clone the gatsby rep, cd to `packages/gatsby-source-contentful`, run `npm link, go back to  your projec, run `npm link gatsby-source-contentful` and build again

**Comment by Smiter** [comment]
Fixed an issue here https://github.com/gatsbyjs/gatsby/pull/1487 :)

**Comment by Khaledgarbaya** [comment]
it's already handled [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/gatsby-node.js#L35)

**Comment by KyleAMathews** [comment]
This is fixed now so closing.
