### ISSUE TITLE
Broken output of `gatsby build`

### ISSUE THREAD

**Issue by mohoff** [gatsbyjs/gatsby#14486]
Hi,

I'm having weird results when building my gatsby project, which is based on `gatsby-image`.

When i run `gatsby develop` all looks good:

<img width="932" alt="Screenshot 2019-06-01 at 21 54 12" src="https://user-images.githubusercontent.com/6060612/58752995-7c8d6180-84b8-11e9-9040-94ff91478351.png">

However, when i run `gatsby build` (no errors) followed by `gatsby serve` (or serve `/public` via Caddy), I get:

<img width="971" alt="Screenshot 2019-06-01 at 21 55 59" src="https://user-images.githubusercontent.com/6060612/58753005-9d55b700-84b8-11e9-99cc-d840dec5e531.png">

This happens as well when i delete `/public` and `.cache` before running both commands.

It seems that assets (images, css) are not available or not properly linked. However, the image data is included in `/public` as the folder size shows (roughly matches the total size of all images).

My gatsby-related dependencies are:

```
"gatsby": "^2.3.32",
"gatsby-image": "^2.0.40",
"gatsby-plugin-manifest": "^2.0.29",
"gatsby-plugin-sharp": "^2.0.35",
"gatsby-source-filesystem": "^2.0.32",
"gatsby-transformer-remark": "^2.3.12",
"gatsby-transformer-sharp": "^2.1.18",
```

Do you guys have an idea what is going wrong here? Any help or hints are much appreciated, thanks!

**Comment by mohoff** [comment]
Just upgraded all the dependencies to their newest versions, and `gatsby build && gatsby serve` now results in:

<img width="848" alt="Screenshot 2019-06-01 at 22 22 37" src="https://user-images.githubusercontent.com/6060612/58753184-ece9b200-84bb-11e9-85b5-3fe15c42eac1.png">

Looks like the CSS part of the page works now, while the images are still missing.

The new dependency versions are:

```
"gatsby": "^2.8.2",
"gatsby-image": "^2.1.2",
"gatsby-plugin-manifest": "^2.1.1",
"gatsby-plugin-sharp": "^2.1.3",
"gatsby-source-filesystem": "^2.0.38",
"gatsby-transformer-remark": "^2.3.12",
"gatsby-transformer-sharp": "^2.1.21",
```

**Comment by KyleAMathews** [comment]
Can you try running "gatsby clean" and rebuilding?

--
Kyle Mathews

Blog: http://bricolage.io
Twitter: http://twitter.com/kylemathews

**Comment by mohoff** [comment]
Thanks for your reply @KyleAMathews 

Same result after `gatsby clean` on updated dependencies

**Comment by KyleAMathews** [comment]
Perhaps check the browser console for errors?

Can you share your code? This isn't the normal behavior so I suggest that you keep looking around. Another good debugging technique is to delete bits of your code until it starts working.

**Comment by mohoff** [comment]
There are no errors or warnings in the console output. While loading/refreshing the page, I see the blurred previews of the images. So the base64 representation of the images seems to work.

It's working perfectly with `gatsby develop`, so I assume it's a problem with `gatsby build`. Without any errors shown in the build step, the console, or starting the server, it's hard to dig deeper. I ended up using `gatsby develop` only for now.

The code is here: https://github.com/mohoff/photo-blog/tree/73504690952a8222e929b8d1605b89c4a2188529

**Comment by KyleAMathews** [comment]
You can't have both page and static queries in the same component like here
https://github.com/mohoff/photo-blog/blob/master/src/pages/index.js

That shouldn't work in development but apparently is but that's why the
build is failing.

**Comment by mohoff** [comment]
Thanks for the tip! I converted the query to a page query now:

```js
const App = ({ data }) => (
  <Layout>
    <div>
      <Blog data={data} />
    </div>
  </Layout>
)

const Blog = ({ data }) =>
  data.posts.edges.map(edge => (
    <Image
      data={edge.node.frontmatter}
      key={edge.node.frontmatter.image.childImageSharp.id}
    />
  ))

export const allImages = graphql`
  query ImagesQuery {
    posts: allMarkdownRemark(
      filter: { frontmatter: { publish: { eq: true } } }
      sort: { fields: [frontmatter___takenAt], order: DESC }
    ) {
      edges {
        node {
          frontmatter {
            takenAt(formatString: "MMM YYYY")
            country
            place
            title
            image {
              childImageSharp {
                id
                fluid {
                  ...GatsbyImageSharpFluid_withWebp
                }
              }
            }
          }
        }
      }
    }
  }
`

export default App
```

and ran `gatsby clean && gatsby build && gatsby serve` again. Unfortunately the issue persists.

**Comment by KyleAMathews** [comment]
Do you have a live example of this we could look at?

**Comment by mohoff** [comment]
Yes, I just deployed it to https://blog.mohoff.de/ . The images seem to work now, however the CSS is still an issue. Specifically, the custom styles that are applied with `withStyles()` are ignored while the styles coming from material-ui are included.

I have to investigate why the images are working out of a sudden, maybe it's related to the specific steps in the `Dockerfile`.

The source code of that deployment is at https://github.com/mohoff/photo-blog/tree/d5cb43193cca4699be4fbdbb0ae12bda16da18e4

**Comment by superhawk610** [comment]
@mohoff I believe the issue is caused by inconsistent class naming in between the SSR build and the hydrated result, hence the issue showing up in prod builds but staying absent when using `gatsby develop`.

There's a plugin for `material-ui` SSR + Gatsby you can check out [here](https://github.com/hupe1980/gatsby-plugin-material-ui). If that still doesn't solve it, here's a nice [discussion thread](https://github.com/gatsbyjs/gatsby/issues/8237#issuecomment-465337532) on some of the potential problems you may be running into :smiley:

**Comment by mohoff** [comment]
Oh beautiful! Thank you so much for these links! Adding this plugin fixed it already.
