### ISSUE TITLE
Schema delegation using delegateToSchema

### ISSUE THREAD

**Issue by gburgett** [gatsbyjs/gatsby#14517]
## Summary

Apollo's graphql-tools package provides an example for delegating to a remote schema within a resolver - https://www.apollographql.com/docs/graphql-tools/schema-delegation/
This appears to use the `mergeInfo` field on the `info` object, which unfortunately is not present inside of a gatsby resolver even if the third-party schema has been added using `gatsby-source-graphql`.

__Feature request__: add some analogue of `delegateToSchema` in the resolver info object when a third-party schema has been added.

### Basic example

```js
const setFieldsOnGraphQLNodeType = async ({ type }) => {
  let remoteAuthorsSchema = makeRemoteExecutableSchema({
    schema: await introspectSchema(link),
    link,
  })
  const person = remoteAuthorsSchema.getType('Person')

  switch (type.name) {
    case 'BlogPost':
      return {
        author: {
          type: person,
          args: {},
          resolve: async (source, fieldArgs, context, info) => {
            if (!source.authorId) {
              return null
            }
            return info.mergeInfo.delegateToSchema({
              schema: remoteAuthorsSchema,
              operation: 'query',
              fieldName: 'Person',
              args: { id: source.authorId },
              context,
              info
            });
```

### Motivation

My blog posts coming from Contentful have a foreign-key into a separate system for looking up author information (photos, short bio, etc.).  This system exposes a graphql interface, so I had hoped to use schema delegation to essentially link blog posts to authors "for free".

For now, as a workaround, I am copying the data over via `actions.createParentChildLink` inside of `onCreateNode`.  But, for various reasons (one being that author information is queried conditionally, author info changes more often than blog posts, not wanting to cache all that author info, can provide more detail if asked),  I'd much rather execute the remote query on demand.

**Comment by freiksenet** [comment]
You can import `delegateToSchema` directly from `graphql-tools`, it doesn't have to come from info. However, you can't add type to the schema this way, because Person type won't exist on Gatsby graphql schema. 

Consider using [gatsby-source-graphq](https://www.gatsbyjs.org/packages/gatsby-source-graphql/) and connecting schemas using [createResolvers](https://www.gatsbyjs.org/docs/node-apis/#createResolvers).

**Comment by gburgett** [comment]
Thanks for the tip!  I didn't realize it was in there.  I was able to get it working, for posterity here's my code.  I load up my blog posts from `gatsby-source-contentful`, and the `author` field on the blog post is an ID of type string referencing another system which exposes a graphql interface.

```ts
const setFieldsOnGraphQLNodeType: SetFieldsOnGraphQLNodeType = async ({ type }) => {
  let remoteAuthorsSchema = makeRemoteExecutableSchema({
    schema: await introspectSchema(link),
    link,
  })
  const person = remoteAuthorsSchema.getType('Person') as GraphQLObjectType

  switch (type.name) {
    case 'ContentfulBlogPost':
      return {
        authorId: {
          type: GraphQLString,
          resolve: (source: ContentfulBlogPost) => source.author
        },
        author: {
          type: person,
          args: {},
          resolve: async (source: ContentfulBlogPost, fieldArgs, context, info) => {
            if (!source.author) {
              return null
            }

            return delegateToSchema({
              schema: remoteAuthorsSchema,
              operation: 'query',
              fieldName: 'Person',
              args: { id: source.author },
              context,
              info
            });
          },
        },
      }
  }
}
```

Then I can run the following graphQL query:
![image](https://user-images.githubusercontent.com/430257/58897385-ceeb9f80-86bd-11e9-9063-aacdb3465cd1.png)

which fires off this query to my other service:
```json
{
  "operationName": "BlogPostByUrl",
  "variables": { "_v0_id": "5CvSQIAE1n65tJFZmr2uyD" },
  "query": "query BlogPostByUrl($_v0_id: ID) {\n  Person(id: $_v0_id) {\n    firstName\n    lastName\n    bio {\n      body\n    }\n  }\n}\n"
}
```
and returns the appropriate author information!
