### ISSUE TITLE
Can I control which routes scroll to the top of the page or not?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#14524]
General or specific Gatsby question, not sure:

I am using a specific plugin using the browser API to make scrollToTop false for every route, but I don't necessarily want to do that all the time. Can I use the scrollToTop thing to only work or not work on some routes, and not all of them?

And in general would this be the place to go for doing something like this or are there other ways to do so?

**Comment by DSchau** [comment]
@rchrdnsh which plugin are you using?

If you're using the `shouldUpdateScroll` API you could pass an array of routes that it _should_ be updated, and then compare that array with the current pathname.

**Comment by rchrdnsh** [comment]
I'm using `gatsby-plugin-transitions` and in the `gatsby-browser.js` file i'm doing this, per the instructions for the plugin:

```js
exports.shouldUpdateScroll = () => {
  return false;
};
```

sooooooo, yeah...I think I'm just a little hazy at to how to pass in routes that I want to scroll to top, rather than not scroll to top.

I'm looking at the example in the Gatsby docs, but I don't really understand it, unfortunately :-(

**Comment by rchrdnsh** [comment]
hmmmm...the more I'm exploring the site the more it seems to be broken. No page seems to reset to the top of the page when it should, and using the forward and back buttons in the browser don't take me to the last position I was on on the previous page, like they should. I have no idea what I'm doing with controlling navigation and position the way that I want to and it feels like Gatsby might not be doing a good job at these things. Then again, it might be one or a few of the plugins as well. 😶

**Comment by rchrdnsh** [comment]
I'm also using `gatsby-plugin-intl` for i18n, and that replaces the gatsby `<Link>` with its own link component so that might be messing things up as well. I just feel lost right now controlling gatsby and making it behave how i think it should, i guess.

**Comment by rchrdnsh** [comment]
closing this nor now as I made a new issue which is more exact in my needs.
