### ISSUE TITLE
Saving Buffer as file to utilize image processing

### ISSUE THREAD

**Issue by malcolm-kee** [gatsbyjs/gatsby#14538]
## Summary
How to save an image `Buffer` as file in order to utilize gatsby image processing?

If currently such use case is not available, which part of the code (core/plugin) that I can contribute to make it possible?

## Relevant information

- This use case arises from `gatsby-source-mysql`, whereby images could be retrived from database as `Buffer` object.
- It seems like `gatsby-source-filesystem` exports a `createRemoteFileNode` helper for file in remote. However, I could not find something like `createBufferFileNode`.

**Comment by superhawk610** [comment]
You should be able to make use of [gatsby-transformer-sharp](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-sharp) to transform your Buffer nodes into `ImageSharp` nodes, which will in turn support image processing operations via GraphQL.

All you need to do to support `gatsby-transformer-sharp` is to make sure the nodes you create have a supported `extension`, one of the following:

```
const supportedExtensions = {
  jpeg: true,
  jpg: true,
  png: true,
  webp: true,
  tif: true,
  tiff: true,
}
```

You can read more on the transformer source [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/on-node-create.js).

**Comment by malcolm-kee** [comment]
Hi @superhawk610 thanks for your response.
AFAIK `gatsby-source-filesystem` doesn't exports `createFileNode`, therefore I need to make a pull request to export that?

**Comment by superhawk610** [comment]
If you look at the source for `createFileNode` it really just takes a file path and returns an object with a lot of information about that path. I don't think `gatsby-source-filesystem` wants to export that since it's only useful to other source plugins, so you may have to just write a similar file yourself.

**Comment by wardpeet** [comment]
This sounds awesome :smile:

We're happy to accept a PR that adds a `createFileNodeFromBuffer` that does the same thing as a remote url. We probably want to split up the processRemoteNode function one that fetches the file and one that has the logic of saving to disk.

**Comment by superhawk610** [comment]
@malcom-kee unless you want to take this one, I'd like to work on the API that @wardpeet suggested. We should be able to get that merged into `gatsby-source-filesystem` within a week or so, then you can just pull from that in `gatsby-source-mysql`?

**Comment by malcolm-kee** [comment]
@superhawk610 you can proceed. Thanks!

**Comment by wardpeet** [comment]
Sounds awesome @superhawk610! Thanks for picking this up!
