### ISSUE TITLE
Autoprefixer "browsers" option is deprecated in v9, produces warnings

### ISSUE THREAD

**Issue by fedriz** [gatsbyjs/gatsby#14530]
## Description

I'm getting a series of warnings related to the `browserslist` package.
I can't override the settings following the warning instructions because I can't find
where the wrong properties are written.

### Steps to reproduce

- `yarn develop`

### Expected result

There should be no warnings.

### Actual result

```
warn
  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist
```

`DONE  Compiled successfully in 9137ms`                                                                                                                                 

### Environment

```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.2.1 => 2.8.2
    gatsby-image: ^2.0.34 => 2.1.2
    gatsby-plugin-feed: ^2.0.15 => 2.2.2
    gatsby-plugin-google-analytics: ^2.0.17 => 2.0.20
    gatsby-plugin-google-tagmanager: ^2.0.13 => 2.0.15
    gatsby-plugin-manifest: ^2.0.24 => 2.1.1
    gatsby-plugin-offline: ^2.0.25 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.10 => 3.0.12
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.0.29 => 2.1.3
    gatsby-plugin-sitemap: ^2.1.0 => 2.1.0
    gatsby-remark-copy-linked-files: ^2.0.11 => 2.0.13
    gatsby-remark-images: ^3.0.10 => 3.0.14
    gatsby-remark-prismjs: ^3.2.6 => 3.2.9
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9
    gatsby-source-contentful: ^2.0.47 => 2.0.67
    gatsby-source-filesystem: ^2.0.27 => 2.0.38
    gatsby-transformer-remark: ^2.3.7 => 2.3.12
    gatsby-transformer-sharp: ^2.1.17 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.6.3
    gatsby: 2.7.5
```

**Comment by robertcoopercode** [comment]
Seems to be caused by `autoprefixer`'s [latest commit](https://github.com/postcss/autoprefixer/commit/7980d0ac3ebb0d1adbbe6a75d248ca3702b2d5f3).

**Comment by wardpeet** [comment]
Yeah seems like it autoprefixers latest release. We would love to get this fixed.

1. Upgrade autoprefixer in gatsby to 9.6.0
2. Rename browsers to overrideBrowserslist inside https://github.com/gatsbyjs/gatsby/blob/6070279f68aab0c82f2d244f54088f8ad4a74503/packages/gatsby/src/utils/webpack-utils.js#L222

**Comment by robertcoopercode** [comment]
I'll do it ✌🏻

**Comment by wardpeet** [comment]
That was fast! awesome @robertcoopercode

**Comment by zefviktor** [comment]
Hi, I have the same error only in the Gulp system
`  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist`

`{
  "name": "zefviktor",
  "version": "1.0.0",
  "description": "",
  "main": "gulpfile.js",
  "devDependencies": {
    "browser-sync": "^2.26.3",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^6.1.0",
    "gulp-clean": "^0.4.0",
    "gulp-clean-css": "^4.0.0",
    "gulp-cli": "^2.0.1",
    "gulp-concat-css": "^3.1.0",
    "gulp-file": "^0.4.0",
    "gulp-footer": "^2.0.2",
    "gulp-header": "^2.0.7",
    "gulp-install": "^1.1.0",
    "gulp-modify-css-urls": "^2.0.0",
    "gulp-rename": "^1.4.0",
    "gulp-sass": "^4.0.2",
    "gulp-sass-glob": "^1.0.9",
    "gulp-sourcemaps": "^2.6.5",
    "gulp-tap": "^1.0.1",
    "gulp-uglify": "^3.0.2",
    "node-sass": "^4.10.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "zefviktor",
  "license": "MIT",
  "dependencies": {
    "bootstrap": "^4.3.1",
    "masonry-layout": "^4.2.2"
  }
}
`

**Comment by lucasjohnson** [comment]
Do get rid of error with Gulp do the following:

Add browserslist options array to package.json
```
"browserslist": [
    "last 2 version",
    "> 2%"
  ],
  "scripts": {},
```
Then remove the options from gulpfile.js, leaving the autoprefixer callback empty.
```
const postCssOptions = [
  assets({ loadPaths: ['images/'] }),
  autoprefixer(),
  postcssNormalize({
    browsers: 'last 2 versions',
    forceImport: true
  })
];
```

**Comment by rmolinamir** [comment]
@lucasjohnson 
Thanks! I assume it should be the same with webpack.

I also assume `autoprefixer` will fallback to the `package.json` settings, right?

**Comment by jwangyangls** [comment]
I found the following link helpful to me and solved my problem.

https://github.com/ng-packagr/ng-packagr/pull/1311/files

**Comment by lucasjohnson** [comment]
> @lucasjohnson
> Thanks! I assume it should be the same with webpack.
> 
> I also assume `autoprefixer` will fallback to the `package.json` settings, right?

Correct

**Comment by Kol-Cyber** [comment]
Thank you very much for this solutions! Saved me!

**Comment by doliglwt** [comment]
I am stuck with the same issue in Grunt, autoprefixer is a line in my Grunt package.json, in dependencies

dependencies: {
  "autoprefixer": "^6.5.4", 
  etc...}

and in the package-lock.json it is configured like this
`"autoprefixer": {
      "version": "6.7.7",
      "resolved": "https://registry.npmjs.org/autoprefixer/-/autoprefixer-6.7.7.tgz",
      "integrity": "sha1-Hb0cg1ZY41zj+ZhAmdsAWFx4IBQ=",
      "requires": {
        "browserslist": "^1.7.6",
        "caniuse-db": "^1.0.30000634",
        "normalize-range": "^0.1.2",
        "num2fraction": "^1.2.2",
        "postcss": "^5.2.16",
        "postcss-value-parser": "^3.2.3"
      }
    },

"browserslist": {
      "version": "1.7.7",
      "resolved": "https://registry.npmjs.org/browserslist/-/browserslist-1.7.7.tgz",
      "integrity": "sha1-C9dnBCWL6CmyOYu1Dkti0aFmsLk=",
      "requires": {
        "caniuse-db": "^1.0.30000639",
        "electron-to-chromium": "^1.2.7"
      }
    },
`

**Comment by lucasjohnson** [comment]
You can see the full working example here: https://github.com/lucasjohnson/gulp-templating/blob/master/package.json
