### ISSUE TITLE
Why is there not a @types/gatsby package?

### ISSUE THREAD

**Issue by alexluong** [gatsbyjs/gatsby#14535]
Hi,

I'm trying out TypeScript with Gatsby for the first time and quite surprised that there is no `@types/gatsby` package. I think it would be helpful, especially if someone want to implement the Node/Browser/SSR in TypeScript.

Some example code:

```ts
export function sourceNodes({ actions, createNodeId }: SourceNodesParam) {}
```

**Comment by DSchau** [comment]
Types are available, and are distributed alongside the library.

https://unpkg.com/gatsby@2.8.2/index.d.ts

Hope this helps -- thanks!

**Comment by alexluong** [comment]
Thanks for the response. This is exactly what I'm looking for.

**Comment by alexluong** [comment]
@DSchau Sorry for bothering, but using types from Gatsby create a false error for me:

```ts
    createNode({
      ...obj,
      id: createNodeId(`Obj-${post.id}`),
      parent: "",
      children: [],
      internal: {
        type: "Obj",
        content: nodeContent,
        contentDigest: crypto
          .createHash("md5")
          .update(nodeContent)
          .digest("hex"),
      },
    })
```

It complains:

```
Type '{ type: string; content: string; contentDigest: string; }' is missing the following properties from type '{ type: string; mediaType: string; content: string; contentDigest: string; owner: string; description?: string | undefined; }': mediaType, owner
```

What I think is happening is here:

```
export interface Actions {
  ...

  createNode(node: Node, plugin?: ActionPlugin, options?: ActionOptions): void
}
```

It expect a Node as an argument where `mediaType` is not optional and `owner` field exists within `internal`.

Maybe there should be a `NodeInput` where `mediaType` is optional and there is no `owner` field?

**Comment by DSchau** [comment]
@alexluong we'd love a PR making those types a little more flexible!

**Comment by alexluong** [comment]
@DSchau Created a PR with a follow-up question. We can discuss over there! Thanks for the support.

**Comment by muescha** [comment]
FYI: 
- https://www.gatsbyjs.org/plugins/?=typescript
