### ISSUE TITLE
Heads up: @reach/router EOL

### ISSUE THREAD

**Issue by blenoski** [gatsbyjs/gatsby#14534]
## Summary
Looks like reach-router and react-router and going to be merged into a new hooks based react-router release at which point @reach/router will be EOL (but still maintained for some time).

See: https://reacttraining.com/blog/reach-react-router-future/

**Comment by lannonbr** [comment]
This is something that has been brought up. From a tweet on Gatsby's twitter account here: https://twitter.com/gatsbyjs/status/1129804373700300800

> As the article explains, the new react-router is very close to the API of @reach/router — so we'll continue to use @reach/router for Gatsby v2 and switch to react-router v5 for Gatsby v3. For most people, it shouldn't be a breaking change.

So this will be tackled when we release Gatsby v3

**Comment by KyleAMathews** [comment]
Yeah thanks @lannonbr and @blenoski! This is something we'll switch at v3 as @lannonbr mentioned. @reach/router will be supported in the meantime and it should be an easy switch over for both core and users. For most users (if they don't have an client-only routes), it won't be a breaking change.

**Comment by blainekasten** [comment]
I'm going to close this issue. I now have ownership of the reach/router repo, so the repo will remain maintained. In addition we will still be changing to react-router@6 in gatsby@3.
