### ISSUE TITLE
Styles within iframe component applied to parent window

### ISSUE THREAD

**Issue by kmcaloon** [gatsbyjs/gatsby#14558]
So this isn't so much a "bug" as it is an incompatibility with a specific use case mixed with a sort of feature request.

Here is the situation.  I have a gatsby-based cms and am current working on a page builder that includes an interactive preview of what the content would look like on the frontend.  The cms imports the necessary frontend components/styles in order to achieve the preview. The problem is that this results in 2 sets of global styles and other class names that conflict (not using css modules). 

One workaround I am trying to implement is to load the page builder within a Frame component as seen here https://github.com/ryanseddon/react-frame-component/. 

Here are some snippets of what we're looking at:

**Everything within `<Frame />` is rendered within an iframe**
```
<Frame>
   <ComposerPreview />
</Frame>
```

**ComposerPreview.js**
```
import classnames from 'classnames';
import React from 'react';

import 'demo.scss';

/**
 * Composer Preview Screen.
 */
const propTypes = {};
const ComposerPreview = props => {

  const className = classnames(
    'Composer__preview',
    props.className
  );

  return(

    <div className={ className }>
      <h1>Heyyyy</h1>
    </div>

  )

};
ComposerPreview.propTypes = propTypes;

export default ComposerPreview;
```

**Here is the result**
<img width="330" alt="Screen Shot 2019-06-05 at 10 09 16 AM" src="https://user-images.githubusercontent.com/10777353/58962834-ff910f00-8779-11e9-8d4f-6cecc2d8220e.png">

As you can see, `demo.scss` is being imported by the component which is rendered within the iframe, however Gatsby is moving the styles to the head of the parent window instead of the iframe's, which I guess is sort of to be expected.

This gets to the crux of it and leads into a sort of feature request: Is there no way to get the scope of the current component and inline the styles directly above its location in the DOM instead of having everything embedded within `<head />`?  Would this not also improve page load as only critical styles would be rendered at the beginning of the DOM?

I will be experimenting with this but just wanted to get the community's thoughts and if I am missing a simpler solution here.  Obviously one solution would be to pull up an actual Gatsby page within the iframe and hide all elements and styles that I don't need for the preview, but as of right now looking for something a little smoother. 

Thanks

**Comment by DSchau** [comment]
OK!

So what's happening here is that css is _global_, and embedding a component in an iframe does not strip the (now unused by the main app) CSS from _that specific_ component from the main application.

Gatsby's build process is something like this (in the case of CSS):

1. Use webpack to load all assets
1. If an asset is requested (e.g. a page imports a component), load the assets for that component
1. In the case of SCSS/CSS/etc. load the styles for _that_ component for the entire application

In this case, we don't really have any way of knowing that the component that's being imported isn't actually _used_ by the parent application, but is rather going to be embedded in an iframe.

There are a few ways you could restrict style code to only loading within the iframe. Probably the easiest here is to use... inline styles, depending upon how complex the CSS is for the composer component.

Will that work for your use case?

**Comment by kmcaloon** [comment]
Thanks @DSchau.  Originally I was going to try exploring inline styles, however the problem is that the Composer component would then import components from my actual gatsby-based frontend app with their own styles -- so I would basically have to refactor everything to use inline styles or styled components.

For these and other reasons, for this use case I just had to implement an iframe and am using postmessages to communicate updates to state.

That being said, I could imagine other scenarios where it might be helpful to control where the stylesheets are actually embedded within the DOM instead of defaulting everything to `<head/>`. Not sure what exactly this would entail with regards to Gatsby's build pipelines.
