### ISSUE TITLE
Add DuoTone options to cache key

### ISSUE THREAD

**Issue by nickwild-999** [gatsbyjs/gatsby#14551]
## Description

On the gatsby-starter (and others) when I set a duotone on an image query...

````
<StaticQuery
    query={graphql`
      query {
        placeholderImage: file(relativePath: { eq: "gatsby-astronaut.png" }) {
          childImageSharp {
            fluid(
              maxWidth: 200
              duotone: { shadow: "#10c5f8", highlight: "#32CD32" }
            ) {
              ...GatsbyImageSharpFluid
            }
          }
        }
      }
    `}

````

 all works well. However when I change the highlight and shadow colours it still renders the old colour choices.

I have emptied all caches etc to no avail

### Steps to reproduce

Change highlight and shadow colours and rebuild

### Expected result

New colourset should render

### Actual result

Old duotone colurs render

### Environment

System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.3
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.8.3 => 2.8.3
    gatsby-image: ^2.1.2 => 2.1.2
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7
    gatsby-source-filesystem: ^2.0.38 => 2.0.38
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.5.12

**Comment by wardpeet** [comment]
Thanks for reporting! It seems like a bug with our caching mechanism with duotone in sharp. A quickfix is to run `gatsby clean` which cleans our cache.

The problem is occuring because of:
https://github.com/gatsbyjs/gatsby/blob/a20afb1f3c8c09804572a7b17ab92050764f60f4/packages/gatsby-plugin-sharp/src/process-file.js#L244

if we run `console.log(JSON.stringify(filtered, Object.keys(filtered).sort()))` we'll get
```json
{
   "background":"rgba(0,0,0,1)",
   "cropFocus":17,
   "duotone":{},
   "fit":"cover",
   "pngCompressionLevel":9,
   "quality":50,
   "toFormat":"png",
   "width":800
}
```
In fact we want
```json
{
   "background":"rgba(0,0,0,1)",
   "cropFocus":17,
   "duotone":{
      "highlight":"#32CD32",
      "shadow":"#10c5f8"
   },
   "fit":"cover",
   "pngCompressionLevel":9,
   "quality":50,
   "toFormat":"png",
   "width":800
}
```
we need to replace `Object.keys(filtered).sort()` with a recursive ObjectKeys & sort so we add "highlight" & "shadow" as whitelisted

**Comment by nickwild-999** [comment]
Thanks for identifying a temp fix @wardpeet

**Comment by adarshlilha** [comment]
Can I take this @wardpeet @nickwild-999 ?

**Comment by nickwild-999** [comment]
You can for me! :-)


On 6 June 2019 at 22:20:06, Adarsh Lilha (notifications@github.com) wrote:

Can I take this @wardpeet <https://github.com/wardpeet> @nickwild-999
<https://github.com/nickwild-999> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gatsbyjs/gatsby/issues/14551?email_source=notifications&email_token=AELGDNUA6576KLOIII3SXZTPZF5QLA5CNFSM4HTQUUC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXEGFTQ#issuecomment-499671758>,
or mute the thread

**Comment by adarshlilha** [comment]
Sorry for jumping right in, all yours @nickwild-999, I will take up another one

**Comment by nickwild-999** [comment]
Sorry no I meant that you are fine to take it as far as I am concerned but
I am not an admin on here

-- 
Nick Wild

**Comment by adarshlilha** [comment]
@nickwild-999 go for it, all yours

**Comment by wardpeet** [comment]
@adarshlilha feel free to take this one on it seems like @nickwild-999 is fine that you take it so :)

**Comment by pieh** [comment]
Published `gatsby-plugin-sharp@2.2.3`. Thanks @Annnnnieee for submitting fix!

**Comment by ehannes** [comment]
@pieh we still have this problem with `gatsby-plugin-sharp@2.6.10`. Are you sure this was actually resolved?

**Comment by JamesMAWalker** [comment]
Just had this problem on `gatsby-plugin-sharp@2.11.1`. The gatsby clean workaround does solve the immediate issue, but it's still not a great developer experience having to both run the cache clean and restart the server.

**Comment by agusterodin** [comment]
I think this issue is still present!
