### ISSUE TITLE
gatsby-cli does not output path of deleted file

### ISSUE THREAD

**Issue by arpitbatra123** [gatsbyjs/gatsby#14561]
## Description

I just created a new project using the gatsby-cli. I ran gatsby-develop in the terminal and opened the project in VSCode and deleted a file from there. Upon Deleting the file the output of the gastby develop command ran earlier is shown in the below screenshot.

![image](https://user-images.githubusercontent.com/21967563/58972441-377c6e80-87db-11e9-82fc-a95e7fda641e.png)

As we can see above, gatsby outputs that a file was deleted saying `file deleted at` but does not output the path of the file, which it should as why else the `at` would be there at the end of that sentence. 

### Steps to reproduce

Create a new project using gatsby, Run gatsby-develop, delete a file from your project.

### Expected result

gatsby should output a message that a file was deleted, along with the path of the file.

### Actual result

gatsby does not output path of deleted file(s).

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.1.0 -
/var/folders/nj/rypkd2js2sbb2y8dl1l8vxqc0000gn/T/fnm-shell-3450044/bin/node
    npm: 6.9.0 -
/var/folders/nj/rypkd2js2sbb2y8dl1l8vxqc0000gn/T/fnm-shell-3450044/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0
    Safari: 12.1
  npmPackages:
    gatsby: ^2.8.3 => 2.8.3
    gatsby-image: ^2.1.2 => 2.1.2
    gatsby-plugin-feed: ^2.2.2 => 2.2.2
    gatsby-plugin-google-analytics: ^2.0.20 => 2.0.20
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-plugin-typography: ^2.2.13 => 2.2.13
    gatsby-remark-copy-linked-files: ^2.0.13 => 2.0.13
    gatsby-remark-images: ^3.0.14 => 3.0.14
    gatsby-remark-prismjs: ^3.2.9 => 3.2.9
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9
    gatsby-source-filesystem: ^2.0.38 => 2.0.38
    gatsby-transformer-remark: ^2.3.12 => 2.3.12
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
  npmGlobalPackages:

**Comment by freiksenet** [comment]
Hello @arpitbatra123!

Unfortunately I couldn't reproduce this.

![2019-06-11-10:39:05](https://user-images.githubusercontent.com/172936/59252669-3c0ab200-8c35-11e9-8258-cf8297214fc5.png)

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.


Thanks for using Gatsby!  :purple_heart:

**Comment by arpitbatra123** [comment]
Hey @freiksenet. 

Thanks for looking into this.
Steps to reproduce this issue:
1. Run `gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog`
2. cd my-blog && gatsby develop
3. Delete a file from the project. For reference I deleted images from the content/assets folder.

On doing the above, You Should be able to reproduce this issue.

**Comment by freiksenet** [comment]
I still can't reproduce :( I'll ask my colleagues to see if they can.

![2019-06-17-10:11:04](https://user-images.githubusercontent.com/172936/59585040-42db6e00-90e8-11e9-98fe-c01cadf19ecd.png)

**Comment by pieh** [comment]
I can't reproduce either. 

Are there perhaps any special characters or space in your path?

**Comment by sidharthachatterjee** [comment]
Can't reproduce this either on `gatsby 2.9.4`

![Screenshot 2019-06-17 17 53 20](https://user-images.githubusercontent.com/7701981/59604097-c87f0e00-9128-11e9-9437-3bbc7912ce37.png)

Works for directories and files with spaces in their names as well. Can you update to gatsby 2.9.4 and try this out (in case it was a bug in previous versions)?

**Comment by arpitbatra123** [comment]
Hi, 

Thanks for taking the time for looking into this. I just upgraded my gatsby version to `2.9.4` and can no longer reproduce this issue. Turns out that earlier I was on an older verison of gatsby namely `2.6.7`
