### ISSUE TITLE
[docs] new reference guide on contact forms in Gatsby

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14564]
## Summary

A [common question](https://github.com/gatsbyjs/gatsby/issues/12022) in Gatsby is how to build a functioning contact form (it is also a [key workflow](https://github.com/gatsbyjs/gatsby/issues/13708)). Without a server runtime environment, it isn't exactly intuitive how to hook up a form action to submit data. 

The first step to improving that workflow would be to create a [reference guide](https://www.gatsbyjs.org/docs/guides/) in the docs; reference guides are technical documentation outlining the various ways to build things in Gatsby (as opposed to tutorials, which are step-by-step instructions). Check out the [docs templates](https://www.gatsbyjs.org/contributing/docs-templates/) and [Gatsby Style Guide[(https://www.gatsbyjs.org/contributing/gatsby-style-guide/) for more information.

Here are some of the potential points to include in such a guide:

- Link to the [Adding Forms](https://www.gatsbyjs.org/docs/adding-forms/) doc
- Briefly mention [creating accessible forms](https://webaim.org/techniques/forms/) because it's a common barrier on the web, and we should take every opportunity to educate
- Use cloud/serverless functions for form action, like [Netlify](https://www.netlify.com/docs/form-handling/), [AWS Lambda](https://aws.amazon.com/blogs/architecture/create-dynamic-contact-forms-for-s3-static-websites-using-aws-lambda-amazon-api-gateway-and-amazon-ses/) or Azure
    - This could also mention Netlify's honeypot feature for spam prevention
- Stand up your own API server, i.e. with Express or similar
- Try services like FormSpree (be sure to test to make sure it works for submissions!)

This could be added to the docs sidebar under "Adding Website Functionality", under Adding Forms. The title of this one should differentiate that it is about hooking up the contact form, more than building out the markup; something like "Building a Contact Form" perhaps?

This is up for grabs if anyone wants to take it on!

**Comment by dyyyl** [comment]
I can try taking this one up!

**Comment by marcysutton** [comment]
@dyyyl awesome. Let us know if you have any questions!

**Comment by dyyyl** [comment]
Hey @marcysutton! I'm getting close to PR time, but I'm struggling to add the new article to the sidenav. Can you please point me in the direction on how that's managed in the repo? Thanks!

**Comment by dyyyl** [comment]
> Hey @marcysutton! I'm getting close to PR time, but I'm struggling to add the new article to the sidenav. Can you please point me in the direction on how that's managed in the repo? Thanks!

Actually, scratch that! Managed to figure it out, PR is out! Really enjoyed working on this one 😄

**Comment by gillkyle** [comment]
Merged in #14768
