### ISSUE TITLE
Change prop name "pathContext" to "pageContext"

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1456]
This when creating pages you can add a `context` key. All data passed there is passed into pages as `pathContext`. I think `pageContext` is a more intuitive name as its context for the "page" which is the main object not "path", an attribute of the page.

Since we're at 1.0, we can just pass in both and then remove `pathContext` at the next major release.

Any thoughts?

**Comment by Vagr9K** [comment]
`pageContext` is less confusing IMO.

Maybe gatsby can throw warnings when building with deprecated `pathContext`?
Then, it wouldn't be a surprise in 2.0.

**Comment by monsieurnebo** [comment]
Totally agree, `pathContext` is confusing and `pageContext` will fit better!

**Comment by calcsam** [comment]
Merged into v2 branch. Going to close this.
