### ISSUE TITLE
Discussion: JSON streaming solution(s)

### ISSUE THREAD

**Issue by DanielRuf** [gatsbyjs/gatsby#14579]
## Summary
We could use some streaming solutions for streaming big chunks of JSON and big JSON documents.

## Relevant information
I was speaking with @LekoArts at a React meetup after his Gatsby talks and we were discussing about JSON streaming. Some of the following solutions could be helpful or maybe used. He might be able to give some more context about the current needs, requirements, use cases and some insight about the current status around such solutions in Gatsby.

oboe.js is a project which is probably still well known

http://oboejs.com/ 
http://oboejs.com/why 

It is baed on the concepts and code of clarinet which can be used for such stream parsers:
https://github.com/dscape/clarinet 

Which is a fork of Isaac Schlueters sax-js:
https://github.com/isaacs/sax-js 

There are some more which are actively maintained but I did not yet evaluate them:
https://www.npmjs.com/package/JSONStream
https://www.npmjs.com/package/bfj
https://www.npmjs.com/package/stream-json

**Comment by pieh** [comment]
I'm not quite sure where exactly this could be used - can you expand a bit on that?
