### ISSUE TITLE
Google analytics does not trigger on querystring changes

### ISSUE THREAD

**Issue by BPScott** [gatsbyjs/gatsby#14571]
## Description

gatsby-plugin-google-gtag and gatsby-plugin-google-analytics both get triggered on `onRouteUpdate`. However `onRouteUpdate` [does not trigger when only the querystring changes](https://github.com/gatsbyjs/gatsby/issues/12484) e.g. you navigate from `example.com/index.html?page=1` to  `example.com/index.html?page=2`.

This means that these navigations are not counted by google analytics and therefore my stats are incorrect.

In #12484 @pieh suggested listening to `@reach/router`'s globalHistory which would trigger when just the querystring changes. Should these two plugins be updated to use that mechanism of checking for url updates instead of `onRouteUpdate`?

### Expected result

Navigating from `example.com/index.html?page=1` to  `example.com/index.html?page=2` should trigger a google analytics page view event in the same way that navigating from `example.com/page1` to  `example.com/page2` does.

### Actual result

No google analytics page view event is triggered

**Comment by freiksenet** [comment]
Hello @BPScott!

@pieh described a possible workraround here https://github.com/gatsbyjs/gatsby/issues/12484#issuecomment-473488628. I don't think it's always a desired behaviour to trigger on query string change, however I definitely think it would be a great option for the plugins. Would you like to make a PR to those plugins to add that option?

Thanks a lot! :purple_heart: :muscle:

**Comment by abhijithvijayan** [comment]
@freiksenet What is the required change needed to fix this?
