### ISSUE TITLE
HTML comment give SyntaxError

### ISSUE THREAD

**Issue by fancydev18** [gatsbyjs/gatsby#14587]
Couldn't find this in first 2 pages of "comment" issues, nor google.

Trying to add this HTML comment in gatsby starter site:

```
<!-- header -->
  <header 
...
```

This gives a SyntaxError on the comment. Aren't HTML comments supported?

**Comment by DSchau** [comment]
@fancydev18 when you're writing React code (JSX), you're writing an XML syntax that _mostly_ looks like HTML. However, there are some gotchas, notably what you're hitting right now re: comments. I recommend also reading [this documentation on ReactJS.org](https://reactjs.org/docs/jsx-in-depth.html) for more info--although comments aren't specifically called out.

To comment something in JSX, you'll want to do something like this

```jsx
function Header() {
  return (
    <header>
      {/* This is a header */}
    </header>
  )
}
```

thanks for the question! Please re-open or reply if we can be of further assistance.
