### ISSUE TITLE
Serving gatsby with NodeJS express server

### ISSUE THREAD

**Issue by nxz91** [gatsbyjs/gatsby#14585]
I would like to host gatsby via a NodeJS express server. I have used Netlify in the past but it is not a feasible option for the current project.

I did `gatsby build` but then was not sure which files to copy over to my express application. I was expecting that I could just use express.static to serve the site. But I cannot even find an `index.html`

Any ideas? 🤔

Thank you!

**Comment by m-allanson** [comment]
Hey @nxz91 - the built site will be available from the `/public` directory. There's a little more info on this page: https://www.gatsbyjs.org/docs/gatsby-project-structure/

**Comment by nxz91** [comment]
Thank you!!! I was almost sure I had tried this before, but now it worked xD

**Comment by lannonbr** [comment]
Closing this as it seems @nxz91 seems to have solved their problem

**Comment by nxz91** [comment]
Sorry, yes! Thank you :)
