### ISSUE TITLE
My typographies are no longer importing since updating to newest version of Gatsby

### ISSUE THREAD

**Issue by raph90** [gatsbyjs/gatsby#14581]
## Description

I've been working on a Gatsby site for a few months, and recently I started using NVM. I'm using Node 10.16.0, and my repo is working fine when uploaded to Netlify. The issue is locally, where typography.js doesn't seem to be applied to my project. I think this is a version/dependency issue but it might also be to do with the latest version of Gatsby. 

### Steps to reproduce

Here is my package.json:

```
{
  
    "dependencies": {
        "@fortawesome/fontawesome-svg-core": "^1.2.19",
        "@fortawesome/free-brands-svg-icons": "^5.9.0",
        "@fortawesome/free-solid-svg-icons": "^5.9.0",
        "@fortawesome/react-fontawesome": "^0.1.4",
        "@glidejs/glide": "^3.3.0",
        "babel-plugin-styled-components": "^1.10.0",
        "bootstrap": "^4.3.1",
        "express": "^4.17.1",
        "gatsby": "^2.8.5",
        "gatsby-background-image": "^0.7.0",
        "gatsby-image": "^2.1.2",
        "gatsby-plugin-express": "^1.1.6",
        "gatsby-plugin-manifest": "^2.1.1",
        "gatsby-plugin-offline": "^2.1.1",
        "gatsby-plugin-react-helmet": "^3.0.12",
        "gatsby-plugin-sharp": "^2.1.3",
        "gatsby-plugin-styled-components": "^3.0.7",
        "gatsby-plugin-typography": "^2.2.13",
        "gatsby-remark-copy-linked-files": "^2.0.13",
        "gatsby-remark-images": "^3.0.14",
        "gatsby-remark-prismjs": "^3.2.10",
        "gatsby-source-contentful": "^2.0.67",
        "gatsby-source-filesystem": "^2.0.38",
        "gatsby-transformer-remark": "^2.3.12",
        "gatsby-transformer-sharp": "^2.1.21",
        "prismjs": "^1.16.0",
        "prop-types": "^15.7.2",
        "react": "^16.8.6",
        "react-bootstrap": "^1.0.0-beta.9",
        "react-dom": "^16.8.6",
        "react-glider": "^1.1.2",
        "react-helmet": "^5.2.1",
        "react-pure-lifecycle": "^3.0.0",
        "react-scroll": "^1.7.11",
        "react-typography": "^0.16.19",
        "sharp": "^0.22.1",
        "styled-components": "^4.3.0",
        "typography": "^0.16.19",
        "typography-theme-lawton": "^0.16.19"
    },
    "devDependencies": {
        "gatsby-plugin-remove-trailing-slashes": "^2.0.11",
        "nodemon": "^1.19.1",
        "prettier": "^1.17.1"
    },
    "keywords": [
        "gatsby"
    ],
    "license": "MIT",
    "scripts": {
        "build": "gatsby build",
        "develop": "gatsby develop",
        "format": "prettier --write src/**/*.{js,jsx}",
        "start": "npm run develop",
        "serve": "gatsby serve",
        "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\""
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/gatsbyjs/gatsby-starter-default"
    },
    "bugs": {
        "url": "https://github.com/gatsbyjs/gatsby/issues"
    }
}
```
Likewise, here's my gatsby config:

```
module.exports = {
  siteMetadata: {
    title: `Raphael Hetherington`,
    description: `Web Development and Design`,
    author: `Raphael Hetherington`,
  },
  plugins: [
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utilities/typography`,
      },
    },
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    {
      resolve: `gatsby-remark-images`,
      options: {
        maxWidth: 1440,
      },
    },
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-styled-components`,

    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [`gatsby-remark-prismjs`],
      },
    },
    `gatsby-remark-copy-linked-files`,
    `gatsby-plugin-remove-trailing-slashes`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/md/`,
        name: "markdown-pages",
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/images/`,
        name: "images",
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-remark-prismjs`,
      options: {
        // Class prefix for <pre> tags containing syntax highlighting;
        // defaults to 'language-' (eg <pre class="language-js">).
        // If your site loads Prism into the browser at runtime,
        // (eg for use with libraries like react-live),
        // you may use this to prevent Prism from re-processing syntax.
        // This is an uncommon use-case though;
        // If you're unsure, it's best to use the default value.
        classPrefix: "language-",
        // This is used to allow setting a language for inline code
        // (i.e. single backticks) by creating a separator.
        // This separator is a string and will do no white-space
        // stripping.
        // A suggested value for English speakers is the non-ascii
        // character '›'.
        inlineCodeMarker: null,
        // This lets you set up language aliases.  For example,
        // setting this to '{ sh: "bash" }' will let you use
        // the language "sh" which will highlight using the
        // bash highlighter.
        aliases: {},
        // This toggles the display of line numbers globally alongside the code.
        // To use it, add the following line in src/layouts/index.js
        // right after importing the prism color scheme:
        //  `require("prismjs/plugins/line-numbers/prism-line-numbers.css");`
        // Defaults to false.
        // If you wish to only show line numbers on certain code blocks,
        // leave false and use the {numberLines: true} syntax below
        showLineNumbers: false,
        // If setting this to true, the parser won't handle and highlight inline
        // code used in markdown i.e. single backtick code like `this`.
        noInlineHighlight: false,
      },
    },
  ],
}

```

Finally, my typography.js file:
```

import Typography from "typography"
// import lawtonTheme from "typography-theme-lawton"

// const configuration = ({...lawtonTheme}) => ({
  
// })

const sizes = {
  tiny: 300,
  phone: 600,
  tab_port: 900,
  tab_land: 1200,
  big_desktop: 1800
}

const configuration = ({
    baseFontSize: '10px',
    scaleRatio: 2,
    googleFonts: [
        {
          name: 'Alegreya Sans',
          styles: [
            '300',
            '400',
            '700'
          ],
        }
      ],
      headerColor: 'rgba(0,0,0,.459)',
      headerFontFamily: ["Alegreya Sans", 'sans-serif'],
      bodyFontFamily: ["Alegreya Sans", 'sans-serif'],
      blockMarginBottom: 0,
      includeNormalize: true,
      headerWeight: 300,
      overrideStyles: ({ rhythm }, options, styles) => ({
        h1: {
          textTransform: 'uppercase',
          letterSpacing: '3px',
          fontSize: '4rem',
          textDecoration: 'bold',
          margin: '1rem 0'
        },
        h2: {
          fontSize: '2rem',
          fontWeight: 400,
          paddingTop: '1rem'
        },
        a: {
          textDecoration: 'none',
          color: 'rgba(0,0,0,.459)',
          textTransform: 'uppercase',
          letterSpacing: '.3rem'
        },
        p: {
          fontSize: '1.8rem',
          color: 'rgba(0,0,0,.459)',
          margin: '1rem 0 2rem 0',
          fontWeight: 300
        },
        ul: {
          margin: "0 0 2rem 2rem"
        },
        li: {
          fontSize: '1.8rem',
          color: 'rgba(122, 61, 179, 0.952)',
          margin: '1rem 0',
          fontWeight: 300
        },
        // 
        "@media screen and (max-width: 600px)": {
          h1: {
            fontSize: '3rem'
          },
          p: {
              fontSize: '1.6rem'
          },
          li: {
              fontSize: '1.6rem'
          }
        },
        span: {
          color: "rgba(0,0,0,.459)"
        }
      })
})

const typography = new Typography(configuration)

export default typography
```

### Expected result

As I mentioned above, everything was working until around two days ago, (and indeed it was working after I started using NVM). This makes me think there's some dependency issue. I expect to import in the font-family and for the styles to be loaded.

### Actual result

My font colours are not correct and my font-family is not being loaded, so I think the typography library isn't working. 

### Environment

System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 3.7.1 - /Users/raph/anaconda3/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 63.0.3
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.8.5 => 2.8.5
    gatsby-background-image: ^0.7.0 => 0.7.0
    gatsby-image: ^2.1.2 => 2.1.2
    gatsby-plugin-express: ^1.1.6 => 1.1.6
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-remove-trailing-slashes: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7
    gatsby-plugin-typography: ^2.2.13 => 2.2.13
    gatsby-remark-copy-linked-files: ^2.0.13 => 2.0.13
    gatsby-remark-images: ^3.0.14 => 3.0.14
    gatsby-remark-prismjs: ^3.2.10 => 3.2.10
    gatsby-source-contentful: ^2.0.67 => 2.0.67
    gatsby-source-filesystem: ^2.0.38 => 2.0.38
    gatsby-transformer-remark: ^2.3.12 => 2.3.12
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21

**Comment by pieh** [comment]
Hey, can you share [example project](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) with this issue? We are using typography for gatsbyjs.org and it seems to work correctly

**Comment by raph90** [comment]
Hi, sure, is it enough to post the link to a repo that you can clone?

**Comment by raph90** [comment]
Here it is, I hope this is ok: https://github.com/raph90/portfolio_gatsby_rebuild

**Comment by raph90** [comment]
I think this issue is to do with my local machine, since it's uploading to Netlify just fine

**Comment by pieh** [comment]
Yeah, it seems to work ok for me too locally. At least `Alegreya Sans` font seems to be used. Just in case - this is what I see:
![Screenshot 2019-06-06 at 12 53 41](https://user-images.githubusercontent.com/419821/59027753-27f03a80-885a-11e9-8b9d-a7187bba2ca9.png).

**Comment by raph90** [comment]
Hi yes, so the problem is with the header, footer, home page, and contact. The only page that works properly is the blog. The fonts at the top in the header and colours aren't correct. It should look like this:
 https://elegant-ramanujan-e30989.netlify.com/

**Comment by raph90** [comment]
I've clearly got some sort of import issue somewhere, but I can't work out what it is, and it's all the more baffling since it's ok when Netlify builds it

**Comment by pieh** [comment]
ok I just did more checks - gatsby develop produces a bit different output than gatsby build - some css order is different - that's why menu is blue in gatsby develop but gray in builds (also some font sizing is affected)

**Comment by raph90** [comment]
Ah ok - is that to do with the build process? As in the module bundling (I'm assuming webpack under the hood). It's strange because I haven't changed any of the files and everything was working...

**Comment by raph90** [comment]
I've noticed that Netlify is cleaning the yarn cache on its builds so I'm trying that...

**Comment by pieh** [comment]
This seems what kind of cause missmatches https://github.com/raph90/portfolio_gatsby_rebuild/blob/master/src/html.js#L17-L22
it's being inserted in different order in develop and builds. Seems like this is global style clashes - what's the order of global styles you would want to apply?

Bootstrap => Typography => Your styles?

**Comment by raph90** [comment]
yes exactly - how should I re-order?

**Comment by polishedwp** [comment]
I can reproduce the error on my local computer. I can't see where the font-family is actually specified. You might want to add to your `global.css`. 

Also, if you are going to use `React-bootstrap` and want to customize the CSS, you might want to specify, bootstrap CSS: `bootstrap/dist/css/bootstrap.min.css`.

**Comment by raph90** [comment]
Hi @polishedwp, the font-family is specified in the typography.js file (in utilities). There's been no problem with the development build up to now, and I haven't changed any of the imports... it's a bit confusing. 

Thanks for the tip about React-bootstrap, 
R

**Comment by raph90** [comment]
@polishedwp Adding the font-family to global.css has worked, thanks, but I still have the issue with the font colours. So the problem remains prioritising the typography.js import.

**Comment by polishedwp** [comment]
Since you are using `styled-components` you could use `GlobalStyles`. It may give you more control over what appears to be CSS style clashes.

**Comment by raph90** [comment]
@polishedwp Thanks, I'll give it a try

**Comment by raph90** [comment]
The issue is definitely that Bootstrap is overriding my styles. Do you guys know how I could prioritise typography.js over Bootstrap? I've tried importing bootstrap but no dice so far

**Comment by polishedwp** [comment]
Not entirely sure. My setup, I'm using bootstrap as my primary and I have `styled-components` available as needed but so far have not used it. I am not using `typography.js` at all. I am using SASS to override bootstrap. See [here](https://github.com/polishedwp/my-ec.mdx/blob/master/src/styles/custom.scsshttps://github.com/polishedwp/my-ec.mdx/blob/master/src/styles/custom.scss). 

I import `reactstrap` and `./src/styles/custom.scss`.

**Comment by raph90** [comment]
Yeah I might need to change approach. The issue is Gatsby is injecting the typography.js styles at the very top of the HTML head, which is completely infuriating and counterproductive. I'm sure there's a way around it but I don't know how...
