### ISSUE TITLE
Just a question about Gatsby's output HTML structure

### ISSUE THREAD

**Issue by danboyle8637** [gatsbyjs/gatsby#14588]
With every site I build, I'm trying to get more detail 'installed' in my brain.

I'm setting up the containers for my site and I noticed the first element inside the root gatsby div ... <div id="___gatsby" />

... There is another div with a tab index and a role of group.

What is this div?

**Comment by m-allanson** [comment]
Hey @danboyle8637 - this is an accessibility feature of `@reach/router`. This is the router that Gatsby uses to handle page navigation. Read more about the feature here: https://reach.tech/router/accessibility

Note that Gatsby's implementation of the router means this feature isn't working as intended right now. There's a fix in progress at https://github.com/gatsbyjs/gatsby/pull/13197

**Comment by danboyle8637** [comment]
@m-allanson Thanks Mike! I appreciate the answer and link.
