### ISSUE TITLE
[gatsby-source-shopify] Allow querying shop currency

### ISSUE THREAD

**Issue by ukch** [gatsbyjs/gatsby#14591]
## Summary

As far as I can tell, there is no way to tell what is the default currency for a shop using this library. However, it should be possible to query this data using [PaymentSettings](https://help.shopify.com/en/api/storefront-api/reference/object/paymentsettings).

### Motivation

If a developer wants to build a reusable code base for multiple Shopify stores, it would be very helpful if they don't need to already know that store's currency.

**Comment by Asjas** [comment]
I'd like to give this a shot to add this if no-one has picked it up yet :+1:

**Comment by ukch** [comment]
Shut up gatsbot

**Comment by paveli** [comment]
Hi are there any updates on this issue? Will currency be added?

**Comment by ukch** [comment]
@paveli Unfortunately I can't reopen this issue or mark it as not stale. That's just how things work around here I'm afraid.
