### ISSUE TITLE
Make each starter repository a template

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#14595]
## Summary

As [GitHub repository templates](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/) came out, there is an opportunity to set up new projects without relying on the `gatsby new` command.

### Motivation

Developers could take a quicker path when creating a new repository and avoid having to follow several instructions about setting up new Gatsby projects. Also, it would be nice to encourage the authors of existing and upcoming starters to do the same, at least by a mention inside the documentation.

**Comment by harshitjuneja** [comment]
Good suggestion @kripod!

I see this setting change is applicable to the following gatsbyjs repositories (ignoring the ones that are already archived/un-maintained). 

1. gatsby-starter-hello-world
2. gatsby-starter-default
3. gatsby-starter-blog

I would be happy to pick up the README change, once a maintainer enables repository templates.

**Comment by NickyMeuleman** [comment]
Was about to post the same suggestion and found this!
This is the documentation page I came across https://help.github.com/en/articles/creating-a-template-repository

For example this would be an ideal candidate: https://github.com/jlengstorf/gatsby-theme-jam-example

How would this work with the monorepo structure? (some?) starters also have their own repository.

For example: https://github.com/gatsbyjs/gatsby/tree/master/starters/hello-world would not work, while https://github.com/gatsbyjs/gatsby-starter-hello-world would.

**Comment by LekoArts** [comment]
I made these three starter repos a template:
https://github.com/gatsbyjs/gatsby-starter-hello-world
https://github.com/gatsbyjs/gatsby-starter-default
https://github.com/gatsbyjs/gatsby-starter-blog

Thanks for suggesting that!
