### ISSUE TITLE
How do I make the `react-div-100vh` React component work for my Gatsby app?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#14590]
Hi everybody,

I'm trying to use a react component called:

https://github.com/mvasin/react-div-100vh

In my project to fix the iOS Safari/Chrome bug where both browsers hijack the vh unit so that 100vh is not actually 100vh, which is INSANE!!!!! but they think it's good, for some reason...many threads on da internet about it, including this one:

https://medium.com/@susiekim9/how-to-compensate-for-the-ios-viewport-unit-bug-46e78d54af0d

Anyhooo, I want to try and wrap my entire app all the time with `react-div-100vh` to fix this 'feature', but I don't know how to go about doing that. I have a feeling it might be the whole browser API thing, but I don't know how to use that, or if that's even the best way to handle it.

If I can get this to work then I can actually use 100vh for layouts, which is the most awesome thing to have ever existed! or something along those lines 🤗

Anyway, any help would be absolutely great :-)

**Comment by DSchau** [comment]
Hi Richard! :wave:

You'll want to use `wrapPageElement` in [`gatsby-browser.js`](https://www.gatsbyjs.org/docs/browser-apis/#wrapPageElement). This will allow you to wrap all pages in a component (in this case the react-div-100vh component) in the _browser_.

This should do the trick, but please reply or re-open if we can help further. Thanks!

**Comment by rchrdnsh** [comment]
Hi @DSchau , I'm doing this:

```
const React = require('react')
const Div100vh = require('react-div-100vh')

exports.wrapPageElement = ({ element }) => {
  return <Div100vh>{element}</Div100vh>
}
```

but it's giving me the following error:

<img width="1041" alt="Screenshot 2019-06-06 10 12 52" src="https://user-images.githubusercontent.com/7884263/59052316-a9889e00-8843-11e9-836f-83b4eefad66d.png">

the syntax is new to me here as well...does the regular import statement not work here?

**Comment by DSchau** [comment]
I'm not exactly sure, but you should definitely use ES Modules for gatsby-browser.js.

```js
import React from 'react'
import Div100vh from 'react-div-100vh'

export const wrapPageElement = ({ element }) => {
  return <Div100vh>{element}</Div100vh>
}
```

**Comment by rchrdnsh** [comment]
should we update that in the docs? Currently the docs look like this:

<img width="723" alt="Screen Shot 2019-06-06 at 10 17 41 AM" src="https://user-images.githubusercontent.com/7884263/59052627-54995780-8844-11e9-8447-b8be2761076f.png">

but changing it to what you showed me ended up working and the error went away.

**Comment by rchrdnsh** [comment]
ugh...the component is totally not working...the screen is now just blank on mobile devices...

can i do something like this in gatsby-browser?

```
window.onresize = function() {
    document.body.height = window.innerHeight;
}
window.onresize(); // called to initially set the height.
```

This was another solution proposed in one of the articles I have read about the subject.

**Comment by ptb** [comment]
I've put together a component which may work for those who are running into this issue.

https://gist.github.com/ptb/9ace4534d67393683bf7191370a16089

It uses `window.visualViewport` to resize a div to the dimensions of the currently available viewport which takes into account the keyboard.

Reference: https://tkte.ch/2019/09/23/iOS-VisualViewport.html

I'm thinking it would primarily be used for `position: fixed` modals which have a child with `overflow-y: auto`, but it could be used for anything. I figured I'd put it out there.

**Comment by Vini98br** [comment]
@rchrdnsh I was with the same problem as you and fix with this: 

#### gatsby-browser.js
```js
import React from 'react';
import Div100vh from 'react-div-100vh';

export { wrapRootElement } from "./gatsby/wrapRootElement"; // i dont know if this can help with some, but its just a theme provider from `styled-components`

export const wrapPageElement = ({ element }) => {
  return <Div100vh style={{minHeight: '100rvh'}}>{element}</Div100vh>
}
```
In the `react-div-100vh` docs, i saw this rvh ( real viewport height ), and i think this can solve your problem too.

**Comment by a-barbieri** [comment]
I don't see here a pure CSS tricks I have been using in the past, so I list them for future reference.

### Position absolute (or fixed)

```scss
.wrapper {
  position: absolute; // works also with position: fixed
  top: 0;
  bottom: 0;
  height: 100%;
}
```

In case you are nesting many elements and you want them to have `height: 100%` as well have a look at this thread. https://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent
