### ISSUE TITLE
[docs] how to upgrade Gatsby and dependencies for minor/patch releases

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14598]
## Summary

We should add a doc on how to upgrade Gatsby after you've created a site. For many developers, the steps to do that are not obvious and there's likely some fear that typing in random commands could break things. 

In the [Releases & Migration](https://www.gatsbyjs.org/docs/releases-and-migration/) section of the docs, we could list out both the reasons and steps for how to upgrade. Ultimately when paired with prompts in the CLI (cc @KyleAMathews), I suspect users will upgrade more regularly.

A doc on Gatsby upgrades should mention any gotchas related to semver/breaking changes, what to do if an upgrade goes wrong, and all necessary steps to updating relevant dependencies.

**Comment by johnletey** [comment]
@marcysutton I can give this a go!

**Comment by jjcav84** [comment]
@marcysutton for clarification is this upgrading from version 1 to version 2 or does this include minor versions?

**Comment by marcysutton** [comment]
@jjcav84 that doc already exists: https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/

Sorry, I should have clarified! This is for minor/patch upgrades; people tend to install Gatsby and then rarely update it again.

Thanks for taking it on! Let me know if you have any other questions.

**Comment by darrell24015** [comment]
Need any additional help with this? I've had a couple of time where I've been prompted to update and worried it might break something in the build. Also, is there some documentation that addresses moving the local build from one PC/Laptop to another? I have three different laptops that I do dev work on (depending where I'm working at the moment).

**Comment by marcysutton** [comment]
> is there some documentation that addresses moving the local build from one PC/Laptop to another?

I would recommend using Git for that!

**Comment by furai** [comment]
I could really use such docs or general guidelines about now. I'm searching the net for some best practices but can't find any. Is there any rough write up about how to upgrade minor/patch versions?
Is just doing "yarn upgrade" on default starter repo good enough?

**Comment by wardpeet** [comment]
When using yarn I use `yarn add gatsby` to get the latest. Npm is probably the same `npm install gatsby` I'm not sure for npm

**Comment by m-allanson** [comment]
yarn also has `yarn upgrade-interactive` which lets you pick and choose which packages to update:

<img width="1039" alt="Screenshot 2019-07-16 at 10 05 14" src="https://user-images.githubusercontent.com/381801/61281270-46c6e280-a7b1-11e9-82f2-1025f2113959.png">

**Comment by furai** [comment]
Another thing that might be worth looking into is fixing inconsistency across documentation with usage of NPM and YARN and actually sticking to one or covering both in each document. I've run into few instances where one tutorial/manual was mentioning usage of one and next one the other.

**Comment by wardpeet** [comment]
We could also introduce a gatsby upgrade method which upgrades gatsby to the latest version. Gatsby upgrade might become beneficial if we do a major upgrade. We could run codemods to get you upgraded.

> Another thing that might be worth looking into is fixing inconsistency across documentation with usage of NPM and YARN and actually sticking to one or covering both in each document. I've run into few instances where one tutorial/manual was mentioning usage of one and next one the other.

Oh that's a great point. Could you point us to some links? We try to advocate NPM as it comes natively with nodejs. The only documentation I'm aware of themes where we use `yarn workspaces` as NPM doesn't have a baked-in solution for this.

**Comment by furai** [comment]
I would actually advocate for yarn usage everywhere. I've run into many issues with NPM during setting up many deployments for different technologies/frameworks. While yarn usually worked as expected.

Searching docs for "yarn add" with `grep -rn ./docs/ -e "yarn add"` shows a few different .MD files where package was added with yarn.

Probably those are mostly pages for plug-ins, not sure though, so the tutorial seems fine. But when you follow the tutorial closely, you're lead to other pages which use yarn. That's why I've noticed inconsistency. 

To be honest the best would be to include both instructions for yarn and for npm so people can make up their minds what they want to use.

Right now it's all a bit confusing because of that discrepancy. 

Maybe it's also because of the default starter theme?

**Comment by darrell24015** [comment]
> Another thing that might be worth looking into is fixing inconsistency across documentation with usage of NPM and YARN and actually sticking to one or covering both in each document.

Wait - what is YARN?  Every course on node.js I've ever taken only talks about NPM. Sorry, that's slightly off-topic. We've identified at least three related items that could use more documentation.

**Comment by wardpeet** [comment]
@furai we use yarn in those files as npm doesn't support "workspaces" out of the box and we thought it's easier to specify yarn than telling people to [setup lernajs](https://lerna.js.org/). 

We might want to add a disclaimer at the top and maybe write a doc about how to set up workspaces with NPM & lernajs.

@darrell24015 It's an NPM alternative. It's 90% compatible with NPM and adds some extra caching/features to NPM. Checkout https://yarnpkg.com/lang/en/.
