### ISSUE TITLE
Gatsby CLI Commands not working for a GitHub Repo

### ISSUE THREAD

**Issue by NaziaHasanPoT** [gatsbyjs/gatsby#14613]
## Description

I am trying to clone a webservice built with gatsby and run it locally in my laptop.
But typing any gatsby command gives the following alert on command prompt:
`-bash: gatsby: command not found`

I tried uninstall and reinstall gatsby manually without working on the GitHub Repository. But it still did not work out.

<img width="934" alt="Screenshot 2019-06-07 at 15 13 33" src="https://user-images.githubusercontent.com/51476428/59093933-dff31580-8936-11e9-9481-029b991df5b9.png">

I am suspecting something  might be missing inthe .npm-global or Path variables, but I might be wrong. 
Please help.

### Steps to reproduce

1. Go to the ReadMe section of [this GitHub Repo](https://github.com/PlatformOfTrust/pot-websites#frontends-with-gatsbygraphql-react) to get instructions
2. Open terminal in Mac and navigate inside the GitHub folder
3. run `git clone git@github.com:PlatformOfTrust/pot-websites.git`
4. run `cd pot-website/developer-site`
5. run `npm install`
6. run `npm install --global gatsby-cli`
7. run `gatsby develop -o -p 8000`
`

### Expected result

The Site should open in browser localhost:8000

### Actual result

On running `gatsby develop -o -p 8000` terminal shows the following: **-bash: gatsby: command not found**

site can't be run on localhost:8000

Here is the screenshot of all the execute commands:
<img width="1339" alt="Screenshot 2019-06-07 at 15 32 51" src="https://user-images.githubusercontent.com/51476428/59095226-c30c1180-8939-11e9-899b-e1e07998d0af.png">

### Environment

As no gatsby commands work at all, I am providing here information on my Operating System.
OS: macOS Mojave (version 10.14.4)
npm version: 6.4.1

**Comment by DSchau** [comment]
I believe you'll need to set up your path to account for global NPM packages.

We recommend using [Homebrew to install](https://www.gatsbyjs.org/tutorial/part-zero/#install-homebrew-for-nodejs) but you can also go without with a guide like [this](https://coolestguidesontheplanet.com/installing-node-js-on-macos/)

I'm going to close this out, but please re-open or reply if we can help further!
