### ISSUE TITLE
Examples sites (e.g. using-contentful) return “Not Found”

### ISSUE THREAD

**Issue by phacks** [gatsbyjs/gatsby#14614]
## Description

Hi! I was checking something on the `gatsby-source-contentful` docs and I noticed that the example site (https://using-contentful.gatsbyjs.org/) returns a 404 “Not Found” served by Netlify.

![image](https://user-images.githubusercontent.com/2587348/59095557-1f126e00-8919-11e9-8a25-5b9bbb8cb708.png)

The 404 is handled by Netlify directly, not on an applicative level:

![image](https://user-images.githubusercontent.com/2587348/59095598-35202e80-8919-11e9-8b7a-0178b9d572e7.png)

I found that this problem appears on the following “example” sites (100% of the ones I tested, so I’m assuming that none of them work):

- https://using-contentful.gatsbyjs.org (404)
- https://using-emotion.gatsbyjs.org (404)
- https://using-asciidoc.gatsbyjs.org (Different error here, seems to be related to DNS: `DNS_PROBE_FINISHED_NXDOMAIN`)
- https://using-css-modules.gatsbyjs.org/ (404)
- https://using-drupal.gatsbyjs.org/ (404)
- https://using-gatsby-image.gatsbyjs.org/ (404)

### Steps to reproduce

Click on one of the links above

### Expected result

The actual example sites should be available.

### Actual result

A 404 (or a DNS-related error) was returned by Netlify and the website is not available.

### Environment

N/A

**Comment by DSchau** [comment]
Great catch!

Not really sure how -- but it appears that some of our Netlify deploys have mysteriously disappeared.

Adding them back now--and will try to get this ironed out. Thanks!

**Comment by phacks** [comment]
@DSchau Thanks for the quick reply and the fix!

It looks that previous 404 errors are fixed, however one error remains on the domain https://using-asciidoc.gatsbyjs.org (the error was `DNS_PROBE_FINISHED_NXDOMAIN`).

So on the 6 URLs I tested in this issue, 5 are fixed and one remains unreachable.

I can close this issue and open a specific one if you prefer?

**Comment by phacks** [comment]
@gatsbybot The `DNS_PROBE_FINISHED_NXDOMAIN` error on the https://using-asciidoc.gatsbyjs.org example site is still there, so the issue is not entirely resolved.
@DSchau do you think you can have a look in the Netlify config regarding this particular URL?

**Comment by hirokihokari** [comment]
Still down by the way.
