### ISSUE TITLE
Theming: Page query in template is not shadowed

### ISSUE THREAD

**Issue by pgegenfurtner** [gatsbyjs/gatsby#14611]
I have a core data theme and a multiple ui themes that depend on the core. I have some templates in `core-theme/src/templates/page.js` and would like to override the page query in my theme like `src/core-theme/templates/page.js`. The component itself gets shadowed and overriden, but the page query stays the old one from ore.

Gatsby version: 2.8.5

**Comment by DSchau** [comment]
As far as I understand it, pages or templates aren't necessarily _intended_ to be shadowed, but rather the underlying components that make up a theme and are _consumed_ by pages or templates.

In other words, we may have a file named `src/pages/whatver.js` and it could look something like:

```jsx
import React from 'react'
import { graphql } from 'gatsby'

import Whatever from '../components/whatever' // this can be shadowed

export default function WhateverPage({ data }) {
  return (
    <Whatever {...data.markdownRemark} />
  )
}

export const pageQuery = graphql`
  query WhateverQueryBySlugOrSomething($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug }}) {
      html
      frontmatter {
        title
      }
    }
  }
`

```

This means you can (should?) shadow the component with data, not necessarily the page that injects with data.

@ChristopherBiscardi is this a reasonable interpretation, or is this something we'll want to fix in themes?

**Comment by pgegenfurtner** [comment]
I understand why it is not necessarily intended to be shadowed.
In my specific use case, I would like to query images differently (other query attributes for fluid sizes for example) for each theme, because the UI output is different. 
Maybe there is a better way to do this.

**Comment by ChristopherBiscardi** [comment]
> pages or templates aren't necessarily intended to be shadowed,

Templates should be shadowable as they participate in webpack via the component path in a createPage call. Pages are shadowable via gatsby-plugin-page-creator being applied to all themes.

> but rather the underlying components that make up a theme and are consumed by pages or templates.

This is a pattern we've been using so that people less familiar with GraphQL can shadow rendering components and get the graphql data via props. (ie: a `src/templates/blog-post.js` with the query that imports and uses a `src/components/blog-post.js` that handles rendering the data). It is not a hard requirement though.

>  The component itself gets shadowed and overriden, but the page query stays the old one from ore.

Can you provide a reproduction for this? Are you having the issue while the develop process is running or after a full `rm` of `.cache`?

**Comment by laurenskling** [comment]
I'm experiencing the same; 

```
createPage({
      path:  ...
      component: require.resolve('./src/templates/car.js'),
    })
```
The page query is run in the original file, the React component of the shadow is being rendered

**Comment by laurenskling** [comment]
It makes sense with this warning:
```
warn The GraphQL query in the non-page component "/Users/laurens/sites/test/yarn-carsite/packages/gatsby-theme-cars/src/gatsby-theme-cars-core/templates/car.js" will not be run.
```

**Comment by laurenskling** [comment]
Could the stale label be removed?

**Comment by ChristopherBiscardi** [comment]
@laurenskling Follow #17681  instead
