### ISSUE TITLE
Create URLs in cyrillic

### ISSUE THREAD

**Issue by pantaley** [gatsbyjs/gatsby#14629]
Hello, I'm trying to create a website with Cyrillic urls. I created a file ./src/pages/проекти.js in Cyrillic. Then I can navigate successfully to this page with <Link to={'/' + encodeURIComponent('проекти')} >

The problem I can't solve is with GraphQL query. Every time I try to run 'gatsby develop' I got the error:

```
error
The GraphQL query from C:/Work/src/pages/проекти.js failed.
Errors:
  Syntax Error: Cannot parse the unexpected character "\u041F".
GraphQL request (1:36)
  1: query cWorkSrcPagesПроектиJs2829808107 {
```
Can you suggest how to set GraphQL to work with non Latin chars or workaround?

PS: I've tried also and with StaticQuery and with the new useStaticQuery.

**Comment by DSchau** [comment]
@pantaley could you paste a sample page, and better yet a [reproduction](https://gatsby.dev/reproduction) that we can test with?

**Comment by pantaley** [comment]
@DSchau I found the issue. When you create new app with `gatsby new` and rename page-2 to something that is not with Latin chars you must add a name to you query.

For example when I want to get site meta from `gatsby-config.js` it needs to be:
`query name { site { siteMetadata ....`
and not just:
`query { site { siteMetadata ....`

Here are the full queries:
```
export const query = graphql`
  query {
    site {
      siteMetadata {
        description
      }
    }
  }
`
```

If you add for example data as name everything works:
```
export const query = graphql`
  query data {
    site {
      siteMetadata {
        description
      }
    }
  }
`
```

Here is the example repo https://github.com/pantaley/cyrillic-app

**Comment by pantaley** [comment]
I stumble to another issue related to GraphQL and non latin symbols.

Here https://github.com/pantaley/cyrillic-app/ I try to create posts with slugs like in https://www.gatsbyjs.org/docs/creating-slugs-for-pages/

The catch is that I need my URLs to be in Cyrillic so my folders are in Cyrillic as well. You can see it in here: https://github.com/pantaley/cyrillic-app/tree/master/src/projects/%D1%82%D0%B5%D1%81%D1%82

If I change the folder name from Cyrillic to Latin, for example from 'тест' to 'test' the page will be created and I can access it from http://localhost:8000/src/projects/test/, but if it's in Cyrillic when you access: http://localhost:8000/src/projects/%D1%82%D0%B5%D1%81%D1%82/ there will be 404 error.

**Comment by pantaley** [comment]
Closing the issue, seems that somewhere between Gatsby v.2.8.5 and the latest 2.10.5 everything is working.
