### ISSUE TITLE
WordPress Pods support

### ISSUE THREAD

**Issue by cr101** [gatsbyjs/gatsby#1463]
@KyleAMathews Does `gatsby-source-wordpress` support the [Pods Framework](https://wordpress.org/plugins/pods/)?

**Comment by KyleAMathews** [comment]
@sebastienfi has been the main one working on this.

Feel free to check out the README and source code https://www.gatsbyjs.org/docs/packages/gatsby-source-wordpress/

**Comment by sebastienfi** [comment]
Yes it is already supported.
