### ISSUE TITLE
gatsby-remark-images do not work when parent node has dash in name

### ISSUE THREAD

**Issue by pitkes22** [gatsbyjs/gatsby#14644]
## Description

gatsby-remark-images do not converts image path string node to file node when it is under the node with a dash('-') in the name. Instead, it changes the path of the image to some weird invalid path with lot of `../`.

My markdown file looks like this
```
logo-Branding:
    other_projects:
        thumbnail: /assets/hp_project_letenky.png
```
So name of the `logo-Branding` node is automatically renamed to `logo_Branding`.
![screen](https://i.imgur.com/AAsPL0p.png)

But then string node is not converted to file node but instead path is changed from `/assets/hp_project_letenky.png` (Output when gatsby-remark-images plugin is disabled) to `../../../../assets/hp_project_letenky.png`.

### Steps to reproduce

Use gatsby-remark-images on the markdown file that use dashes in the name of key in the frontmatter.

### Expected result

Plugin should work normally and convert string node to File node or throw an error.

### Actual result

Path is changed to invalid one and a node is not converted to File node.

### Environment
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.6.2 - C:\Users\pitkes22\AppData\Local\Programs\Python\Python36-32\python.EXE
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.29 => 2.2.8
    gatsby-image: ^2.1.2 => 2.1.2
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-layout: ^1.0.15 => 1.0.15
    gatsby-plugin-manifest: ^2.0.2 => 2.0.24
    gatsby-plugin-netlify-cms: ^3.0.4 => 3.0.16
    gatsby-plugin-offline: ^2.0.5 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.10
    gatsby-plugin-sass: ^2.0.1 => 2.0.11
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-remark-images: ^3.0.14 => 3.0.14
    gatsby-remark-relative-images: ^0.2.2 => 0.2.2
    gatsby-source-filesystem: ^2.0.5 => 2.0.28
    gatsby-transformer-remark: ^2.1.9 => 2.3.8
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
```

**Comment by freiksenet** [comment]
Hi @pitkes22!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! :purple_heart:
