### ISSUE TITLE
CLI text seems to be cut off with Ink

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#14658]
I’m not sure if the switch to Ink is the culprit, but I’ve started seeing messages in the CLI get cut off since about the time Ink rolled out.

For example, the rest of this `info` notice is missing from the output:

<img width="791" alt="Screen Shot 2019-06-08 at 5 52 43 PM" src="https://user-images.githubusercontent.com/163561/59153738-8d892600-8a16-11e9-8132-8c7bea00ce76.png">

I’ve seen this a few times — I can’t remember exactly where, but I _think_ it was error messages.

**Comment by wardpeet** [comment]
I'll look into this, might be wrong text wrapping.

**Comment by janosh** [comment]
Also experiencing this.

**Comment by wardpeet** [comment]
PR is building to fix this :smile:

**Comment by sidharthachatterjee** [comment]
Fix published in `gatsby-cli@2.7.17` and `gatsby@2.13.31`
