### ISSUE TITLE
gatsby new fails if initialized with a path that has a space in it

### ISSUE THREAD

**Issue by trevorlitsey** [gatsbyjs/gatsby#14651]
## Description

When I make a new empty directory that contains a space in the folder new and type `gatsby new` a git error is thrown:

```
Error: Command failed: git clone https://github.com/gatsbyjs/gatsby-starter-default.git   /Users/trevorlitsey/Documents/code/3 notes/netlify --single-branch
```

### Steps to reproduce

```(bash)
mkdir 'some where' && cd 'some where'
gastby new
```

### Expected result

Gatsby should init a new project

### Actual result

A git error is throw because the path is split into two arguments

### Potential fix

The path should be wrapped in 'quotes'

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0
    Safari: 12.0.2
  npmGlobalPackages:
    gatsby-cli: 2.4.8
    gatsby: 2.8.6
```

**Comment by DSchau** [comment]
Ah, interesting! Would you like to tackle this functionality?

You'll be working in the gatsby-cli package, and will just tweak what gets passed to the `gatsby new` command. We'd love this fix if you're able to do so!

**Comment by trevorlitsey** [comment]
Absolutely! Thanks for confirming the right solution. Will take a crack at it 🔨
