### ISSUE TITLE
[idea] linter to warn against using Suspense in SSR

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#14678]
## Description

build-only bug when using Suspense in gatsby. i used it, got no warning, waited for build, then got this in my netlify logs: https://reactjs.org/docs/error-decoder.html/?invariant=294

### Steps to reproduce

https://github.com/sw-yx/plsdelete-netlify-identity-loop-bug/tree/a487389a2c5f289b2759058394e41dd54d375d82

### Expected result

just warn me in some sort of lint rule that suspense is not allowed in Gatsby pages? i'm sure someone's already written this?

**Comment by wardpeet** [comment]
Do you favor a build error or rather a warning and a patch for suspense. I believe we can polyfill Suspense with React.Fragment on SSR and show a warning during build and develop. We'll rehydrate and use CSR Suspense. I'm not 100% sure this is doable 😛

**Comment by sw-yx** [comment]
eh. i mean i think just using a linter is a good first step. can do the fancy stuff later :)

**Comment by sw-yx** [comment]
please!

**Comment by sw-yx** [comment]
i dont like you gatsbot

**Comment by sw-yx** [comment]
i like you allansonbot

**Comment by samovertonjr** [comment]
I created a draft with my proposed fix. I still have to test it properly.

**Comment by LekoArts** [comment]
Closing this due to https://github.com/gatsbyjs/gatsby/pull/21262#issuecomment-585024394
