### ISSUE TITLE
GraphQL Error: RelayParser: Encountered duplicate defintitions for one or more documents

### ISSUE THREAD

**Issue by bmccaw** [gatsbyjs/gatsby#14676]
## Summary

I've been struggling with this particular issue for several days and have been unable to find a solution. I had built a single page scrolling site with Gatsby using gatsby-image and gatsby-background-image to serve up my image files. The error mentions duplicate query names but I can't seem to find the duplicate.

## Relevant information

```
GraphQL Error There was an error while compiling your site's GraphQL queries.
  Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
- IndexQuery
```

## Steps to Reproduce

https://github.com/bmccaw/diamond-opticians

- Run NPM install for node packages
- Run gatsby develop.
- Visit localhost/8000

An error should appear like the one above. 

## Expected Behavior

- Page should load without errors
- User should see a header with clickable links and a header image
- Clicking the links should navigate down the page with each image loading as they are scrolled past

### Environment (if relevant)

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.8.6 => 2.8.6 
    gatsby-background-image: ^0.6.2 => 0.6.2 
    gatsby-image: ^2.0.37 => 2.0.37 
    gatsby-plugin-manifest: ^2.0.27 => 2.0.27 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-source-filesystem: ^2.0.29 => 2.0.29 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17 

### File contents (if changed)

`gatsby-config.js`: 
```
module.exports = {
  siteMetadata: {
    title: `Diamond Opticians`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `Brendan McCaughey`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`, // This path is relative to the root of the site.
      },
    },
    `gatsby-plugin-styled-components`
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ]
}
```

`package.json`:
```
{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "babel-plugin-styled-components": "^1.10.0",
    "gatsby": "^2.8.6",
    "gatsby-background-image": "^0.6.2",
    "gatsby-image": "^2.0.37",
    "gatsby-plugin-manifest": "^2.0.27",
    "gatsby-plugin-offline": "^2.0.25",
    "gatsby-plugin-react-helmet": "^3.0.12",
    "gatsby-plugin-sharp": "^2.0.32",
    "gatsby-plugin-styled-components": "^3.0.7",
    "gatsby-source-filesystem": "^2.0.29",
    "gatsby-transformer-sharp": "^2.1.17",
    "google-map-react": "^1.1.4",
    "intersection-observer": "^0.7.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.0",
    "smooth-scroll": "^16.0.3",
    "styled-components": "^4.2.0"
  },
  "devDependencies": {
    "prettier": "^1.16.4"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write src/**/*.{js,jsx}",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\""
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
```

`gatsby-node.js`: N/A 
`gatsby-browser.js`:
```
/**
 * Implement Gatsby's Browser APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/browser-apis/
 */
export const onClientEntry = () => {  
	// IntersectionObserver polyfill for gatsby-background-image (Safari, IE)
	if (typeof window.IntersectionObserver === `undefined`) {
	  import(`intersection-observer`)
	  console.log(`# IntersectionObserver is polyfilled!`)
	}
  }
// You can delete this file if you're not using it
```
 
`gatsby-ssr.js`: N/A

**Comment by freiksenet** [comment]
Hello @bmccaw!

Sorry to hear that you are having issues :( Unfortunately I couldn't reproduce this error with the example repository you have provided. Maybe you didn't add some code there? I'll be glad to take another look again after that.

Thank you for using Gatsby! :purple_heart:

**Comment by bmccaw** [comment]
Thanks for taking a look! Does the site display as normal or are you getting a different error?

**Comment by bmccaw** [comment]
Just to update: I decided to do a `git fetch --all
` and `git reset --hard origin/master` to get rid of any local changes that may be causing the error but I'm still getting the error.  I'm going to delete my local folder and do a `git clone` to see if that does the trick.

**Comment by bmccaw** [comment]
That did the trick. Not sure what the actual issue was but I'm guessing there was some sort of conflict on my local machine that was causing the issue.

**Comment by marcinsydor** [comment]
Just updated gatsby to `2.13.3` version and I'm getting the same error now. I had two themes and the main project. I'm on Mac which might important. I also moved themes declarations from `__experimentalThemes` to `plugins` but it did not help.
