### ISSUE TITLE
gatsbyjs contentful blog-pages link to wrong content

### ISSUE THREAD

**Issue by jjazzymane** [gatsbyjs/gatsby#14672]
## Description

Clicking on the link to an individual blog page displays slug in URL properly _but not the content that is related to that slug_. Instead, each blog page _is rendering the same content_ from the most recent post.  In the templates/blog.js file, the query is set up to pull contentful data as specified by the equivalence (eq:) of the slug variable ($slug). 

### Steps to reproduce

Create the following **js** files in your **hello-world gatsby project.**

**_src/templates/blog.js_**
In the templates/blog.js file, the query is set up to pull contentful data as specified by the equivalence (eq:) of the slug variable ($slug). 
     

        import React from 'react'
        import Layout from "../components/layout"
        import Profile from "../components/page-title/black-title"
        import { graphql } from 'gatsby';
        import { documentToReactComponents } from '@contentful/rich-text-react-renderer'

        export const pageQuery = graphql`
            query ContentfulBlogPostBySlug($slug: String! ) { 
        
                contentfulBlogPost( slug: { eq: $slug}) {
                    title 
                    publishDate(formatString:"MMMM Do, YYYY")
                    body { 
                        json
                    }
                } 

            }
        `

        const BlogPage = ({data}) => { 

            const post = data.contentfulBlogPost
            const options = { 
                // override specific node types
                renderNode: { 
                    "embedded-asset-block": ({data}) => { 
                        const alt = data.target.fields.title['en-US']
                        const url = data.target.fields.file['en-US'].url
                        return <img alt={alt} src={url}/>
                    }
                }
            }
            return ( 
                <Layout> 
                    <Profile>
                        <h1>{post.title}</h1>
                        <p>{post.publishDate}</p>
                        {documentToReactComponents(post.body.json, options)}

                    </Profile>
                </Layout>
            )
        }

        export default BlogPage

**_gatsby-node.js_**

        const path = require('path')

        module.exports.createPages = async({ graphql, actions }) => { 
            const { createPage } = actions
            const blogTemplate = path.resolve('./src/templates/blog.js')
            const res = await graphql(`
                { 
                   allContentfulBlogPost { 
                       edges { 
                           node{ 
                               slug

                           }
                       }
                   } 
                }
            `)
            const posts = res.data.allContentfulBlogPost.edges
            posts.forEach(({ node }) => { 
                createPage( { 
                    component: blogTemplate,
                    path: `/blog/${node.slug}`,
                    context: { 
                        slug: node.slug
                    }
                })
            })
        }

**_/src/pages/index.js_**

        import React from "react"
        import { Link, graphql, useStaticQuery } from 'gatsby'
        import Layout from '../components/layout'
        import { BlackTitle, WelcomeHeader, FeatureImage, CallToActionButtons, ServicesMenue2, NewSection, Subheader} from '../components/page-title/black-title'

        const Home = () => { 

          const data = useStaticQuery(graphql`
          {
            allContentfulBlogPost(sort: {fields: publishDate, order: DESC}) {
              edges {
                node {
                  title
                  slug
                  publishDate(formatString: "MMMM Do, YYYY")
                }
              }
            }
          }
          `)
            return ( 
                <Layout>
                    <BlackTitle>
                        <WelcomeHeader>
                            Get coached. <br></br>
                            Be heard. <br></br>
                            Expect progress. 
                        </WelcomeHeader>

                        <FeatureImage/>
        
                        <CallToActionButtons/>
        
                        <ServicesMenue2/>
        
                        <NewSection>
                    
                            <Subheader>Latest from Coach</Subheader>
                            <ol>
                              {data.allContentfulBlogPost.edges.map((edge) => {
                                return ( 
                                  <li>
                                      
                                    <Link to={`/blog/${edge.node.slug}`}>
                                        <h2>{edge.node.title}</h2>
                                        <p>{edge.node.publishDate}</p>
                                    </Link>
                              
                              
                                  </li>
                                )
                              })}
                    
                            </ol>
                    
                        </NewSection>
                    </BlackTitle>
                </Layout>
            )
        }

        export default Home

### Expected result

The content for each blog post page should render its specific page content (that is present in graphiql) because it is queried through its slug on the template.

### Actual result

The content rendered to that page is from the post associated with the most recent blog post. 

### Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.5.0-next.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.3
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.7.3 => 2.7.3
    gatsby-plugin-create-client-paths: ^2.0.5 => 2.0.5
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-remark-images: ^3.0.14 => 3.0.14
    gatsby-remark-relative-images: ^0.2.2 => 0.2.2
    gatsby-source-contentful: ^2.0.67 => 2.0.67

error UNHANDLED REJECTION

  Error: The system cannot find the path specified.

  - envinfo.js:1 Function.e.exports.sync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:4970

  - envinfo.js:1 Object.copySync
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:66948

  - envinfo.js:1 Object.t.writeSync.e [as writeSync]
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:48777

  - envinfo.js:1
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46934

  - envinfo.js:1 Promise.all.then.e
    [npm]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:46949

  - next_tick.js:77 process.internalTickCallback
    internal/process/next_tick.js:77:7

**Comment by jjazzymane** [comment]
<img width="683" alt="indexpage" src="https://user-images.githubusercontent.com/50809709/59162567-21afc780-8ac1-11e9-8de3-47f87b66c5f5.PNG">
**correct**
Has correct slug and content
<img width="683" alt="dddPage" src="https://user-images.githubusercontent.com/50809709/59162573-30967a00-8ac1-11e9-8651-a52f41e248f1.PNG">
**wrong**
has correct slug but wrong content
<img width="683" alt="where-to-start-business-in-indy-Page" src="https://user-images.githubusercontent.com/50809709/59162576-3ee49600-8ac1-11e9-902c-f3195f5bf053.PNG">
<img width="683" alt="okbutarewereallygettingahangofthisPage" src="https://user-images.githubusercontent.com/50809709/59162630-3b9dda00-8ac2-11e9-88ed-bdd62aed700e.PNG">


proof query is has nodes with correct values
<img width="683" alt="query displaying different values for each node" src="https://user-images.githubusercontent.com/50809709/59162579-5754b080-8ac1-11e9-9089-9e4fa3a3c897.PNG">
<img width="683" alt="query displaying different values for each node2" src="https://user-images.githubusercontent.com/50809709/59162606-b5819380-8ac1-11e9-9f87-c03cce81eff8.PNG">

**Comment by jjazzymane** [comment]
It’s still an issue for me, please keep open ;)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tapudp** [comment]
how do I solve this????

**Comment by jjazzymane** [comment]
Have you tried “Handling Path Resolution” in the gatsby docs: https://www.gatsbyjs.org/docs/themes/converting-a-starter/ ?

The change is made in the gatsby-node.js file, where path.resolve becomes require.resolve

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tapudp** [comment]
umm not sure of that right now it is just giving me error in the gatsby-node.js file saying it can't `allContentfulBlogPost` Query in the GraphQL query this is the code, I have pulled in directly from my friend's repo and he has this from the video tutorial he followed and setup : https://www.youtube.com/watch?v=8t0vNu2fCCM&t=7464s

the code : 
```
const path = require('path')

module.exports.createPages = async ({ graphql, actions }) => {
    const { createPage } = actions
    const blogTemplate = path.resolve('./src/templates/blog.js')
    const res = await graphql(`
        query {
            allContentfulBlogPost {
                edges {
                    node {
                        slug
                    }
                }
            }
        }
    `)

    res.data.allContentfulBlogPost.edges.forEach((edge) => {
        createPage({
            component: blogTemplate,
            path: `/blog/${edge.node.slug}`,
            context: {
                slug: edge.node.slug
            }
        })
    })
}
```

**Comment by jjazzymane** [comment]
I started my gatsby-node.js and the template/blog.js file over, using this tutorial instead. https://www.gatsbyjs.org/tutorial/part-seven/

**Comment by wardpeet** [comment]
Did you had a look at https://github.com/contentful-userland/gatsby-contentful-starter ?

**Comment by jjazzymane** [comment]
Thanks Wardpeet. Yes, I can put up a minimal reproduction (from the gatsby-contentful-starter above) in a couple of hours. I originally used the gatsby-starter-hello-world and was unable to generate associated for each dynamically generated page.

**Comment by Tapudp** [comment]
okay so for me, I don't know what happened but after removing everything i.e., node_modules and installing it with `npm install gatsby-source-contentful` it worked.

**Comment by jjazzymane** [comment]
The gatsby-contentful-starter worked for me as well. When I click on the link content, the associated data those pages shows up correctly.
