### ISSUE TITLE
Running several gatsby-cli commands synchron [not solveable for several reasons]

### ISSUE THREAD

**Issue by TomFreudenberg** [gatsbyjs/gatsby#14687]
Hi,

I like to run several gatsby commands one after another without invoking them from external by new processes via npm.

I tried following simple builder:

``` javascript
"use strict";

function cli_gatsby(...params) {
  let cli = require("gatsby/node_modules/gatsby-cli/lib/create-cli");
  cli(["", "" ].concat(params))
}

cli_gatsby("clean")
console.log("STEP 1 END")


process.env.BUILD_TARGET = "pdfs"
cli_gatsby("build")
console.log("STEP 2 END")


process.env.BUILD_TARGET = "app"
cli_gatsby("build")
console.log("STEP 2 END")
```

At least this works but in case that the commands run by Promises, those will run nested instead serialized.

Do you have an idea how to get that working in serial?

Thanks for feedback in advance
Tom

**Comment by freiksenet** [comment]
Hello @TomFreudenberg!

You could try wrapping everything into an async function and use `await` inside.

```js
async function run() {
  await cli_gatsby("clean")
  console.log("STEP 1 END")


  process.env.BUILD_TARGET = "pdfs"
  await cli_gatsby("build")
  console.log("STEP 2 END")

  process.env.BUILD_TARGET = "app"
  await cli_gatsby("build")
  console.log("STEP 2 END")
}

run().then(() => {
  console.log('Done!')
})
```

Note that this isn't a very supported way of running Gatsby and you might run into more problems.

**Comment by TomFreudenberg** [comment]
Hi Mikhail @freiksenet 

thanks for your feedback - I have tried those already before and that didn't worked either.

There is also some part in [create-cli.js#L15-L20](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/create-cli.js#L15-L20) which makes it non-working: `process.exit(0)`

So, for now there seems to be no option to run several cli commands in a series.

Thanks for help
Tom
