### ISSUE TITLE
gatsby-source-graphql and strapi, can't use filters in GraphQL query

### ISSUE THREAD

**Issue by violabg** [gatsbyjs/gatsby#14680]
## Description

I'm using gatsby-source-graphql with Strapi content, I have a query like this:

```graphql
{
   regions(sort: "sortId:asc", where: { shops: { published: true } }) {
        id
        name
        shops(sort: "sortId:asc", where: { published: true }) {
          id
          published
        }
      }
}
```

it works fine in both strapi/graphql explorer and gatsby http://localhost:8000/___graphql? one.
but when I compile I'm getting this error

```
Syntax Error: Expected Name, found String "shops"

  GraphQL request (7:41)
  6:     }
  7:     regions(sort: "sortId:asc", where: {"shops":{"published":true}}) {
```

just want to point out, that the query in my code is like the one above, and not like the error one that has shops in double quotes,

### Environment

System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.8.5 => 2.8.5
    gatsby-image: ^2.1.2 => 2.1.2
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-source-filesystem: ^2.0.38 => 2.0.38
    gatsby-source-graphql: ^2.0.18 => 2.0.18
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.6.4

**Comment by freiksenet** [comment]
Hello @violabg!

Could you paste your code where you use this query? It sounds like either variables or the query is passed somehow wrong and it runs with quotes in it.

Thank you! :purple_heart:

**Comment by violabg** [comment]
Hi thanks, 
I'm not passing any variables, this is the code.

```graphql
export const query = graphql`
  query {
    ge {
      tags(sort: "sortId:asc") {
        id
        value
      }
      regions(sort: "sortId:asc", where: { shops: { published: true } }) {
        id
        name
        bgImage {
          url
          imageFile {
            ...bgImage
          }
        }
        shops(sort: "sortId:asc", where: { published: true }) {
          id
          published
          name
          country
          lat
          long
          flag {
            url
            imageFile {
              ...flagImage
            }
          }
          tags {
            value
          }
        }
      }
    }
  }
`;
```

**Comment by abv** [comment]
I'm running into this too. It seems like when the graphql compiles, it forces the where value to string, instead of JSON, or something like that.

**Comment by Ayo91** [comment]
Same issue... I cant use a where filter inside the gatsby code because the query doesn't work. Any solution?
`houses(sort: "created_at:DESC", limit: 4, where: {id: 1})`

**Comment by abv** [comment]
I have found a workaround for this issue. Perhaps this will be of help to others.

**The following fails:** 
`blah(where: {id : $blah_id})` in the query, with `{ "blah_id" : "5" }` passed to context in createPage`

**The following works:** 
`blah(where: $blah_id_json)` in the query, with `{ "blah_id_json" : { "blah_id" : "5" }}` passed to context in createPage`

**Comment by Ayo91** [comment]
Your proposal is not valid for me. I'm running an static query: 
![image](https://user-images.githubusercontent.com/2479896/60659316-04b2ae00-9e4d-11e9-9a35-9351abbbd948.png)

It shows me this error:
Syntax Error: Expected Name, found String "direct_sale"
![image](https://user-images.githubusercontent.com/2479896/60659377-21e77c80-9e4d-11e9-8280-b7492c196c21.png)

If I run this query in the graphql editor, everything works fine.... Any idea?

**Comment by manuelnas** [comment]
I'm having this issue as well. Is there any sort of fix for this?

**Comment by manuelnas** [comment]
@abv 's suggestion works, but is not really something I want to be doing if at all possible. I'd like to get this working as it should, anyone that can help with this?

**Comment by stefanprobst** [comment]
If possible, could you provide a link to a repo to reproduce this error? Thanks!
