### ISSUE TITLE
Unable to deploy on Netlify

### ISSUE THREAD

**Issue by michelecocuccio** [gatsbyjs/gatsby#14683]
I am unable to deploy on Netlify! I have tried in any way... I have read in another thread that it was an issue using npm. I was using yarn already so there is no package.lock.json file and it's ignored anyway in my .gitignore.

When I try to build I get this error

11:16:38 AM: Executing user command: npm run build
11:16:39 AM: npm ERR! path /opt/build/repo/package.json
11:16:39 AM: npm
11:16:39 AM: ERR!
11:16:39 AM: code
11:16:39 AM:  ENOENT
11:16:39 AM: npm
11:16:39 AM: ERR! errno -2
11:16:39 AM: npm
11:16:39 AM:  ERR!
11:16:39 AM:  syscall
11:16:39 AM:  open
11:16:39 AM: npm
11:16:39 AM:  ERR! enoent ENOENT: no such file or directory, open '/opt/build/repo/package.json'
11:16:39 AM: npm ERR! enoent This is related to npm not being able to find a file.
11:16:39 AM: npm ERR! enoent
11:16:39 AM: npm

What am I doing wrong...? 
Please help!

**Comment by jjcav84** [comment]
How are you setting setup? I'm attaching a screenshot of one of my sites so you can adjust yours if necessary. This is assuming you have your file structure setup in a standard fashion.
![Screen Shot 2019-06-10 at 6 26 35 AM](https://user-images.githubusercontent.com/20393409/59192676-df31cd80-8b48-11e9-9181-ae5eb8d330cd.png)

**Comment by michelecocuccio** [comment]
Ok I am so stupid. Please close and delete this! My git folder had a sub folder with the Gatsby website in it. The file needs to be in the main folder of the repo... not in a subfolder. I am deeply sorry If opened a thread for this. Thanks.

**Comment by hafbau** [comment]
Actually thanks @michelecocuccio for this (probably SO type issh)! You just saved me some frustration. I had a new github repo that I haven't pushed the rest of my code to!
