### ISSUE TITLE
Higher turnaround in featured showcase

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#14686]
I just checked the [Gatsby showcase](https://www.gatsbyjs.org/showcase) for the first time in several months and noticed that the featured sites are exactly the same as the last time I visited.

I think the showcase would be more useful and more interesting if the featured sites changed frequently. It might be worth writing an algorithm that selects sites to be featured at random but biased towards sites with more stars on GitHub (or something like that) once a day or every time [gatsbyjs.org](https://gatsbyjs.org) is rebuilt.

**Comment by m-allanson** [comment]
👍 This has been sitting on the list of things we'd love to do but haven't found time for :( An intermediate step might be to manually pick out a few more sites to add to the showcase. 

If you or anyone else has the time to put some suggestions in here, we could follow up with a PR. 

Any suggestions should match at least two of:

- high-production values
- unique functionality
- well known brand

note that the final decision is down to the Gatsby team, suggesting a showcase site here doesn't guarantee that it'll make it to the showcase!

**Comment by interglobalmedia** [comment]
Hi, I  want to add my biz site that I developed myself (I'm a Full Stack JS Developer) to the GatsbyJS showcase. I am also working on a client site using Gatsby and will be in future with other clients. I was a bit confused however, by the steps in https://www.gatsbyjs.org/contributing/site-showcase-submissions/. Should I be forking the Gatsby repo and then creating a pull request in order to submit my site to the yaml file? Thanks!

**Comment by janosh** [comment]
Correct you need to submit a PR against [`sites.yml`](https://github.com/gatsbyjs/gatsby/blob/master/docs/sites.yml). However, you don't have to pull the repo to your local machine. You can edit the file directly on GitHub which will create a fork automatically from which you can submit the PR.

![Screen Shot 2019-06-12 at 15 47 39](https://user-images.githubusercontent.com/30958850/59361399-b0bf1880-8d29-11e9-912c-0cec425e48cc.png)
