### ISSUE TITLE
Keep build-only state in Node API?

### ISSUE THREAD

**Issue by mxxk** [gatsbyjs/gatsby#14696]
## Summary

Is it possible (or even recommended) to keep and reference build-only state when using the Gatsby Node API? Something like the [Cache API](https://www.gatsbyjs.org/docs/build-caching/), except whose state does not persist between builds.

## Relevant information

In `gatsby-node.js`, when linking transformer-created nodes (e.g. `MarkdownRemark`), not all nodes are available at the time `sourceNodes` is called (#11033). The recommended solution in the issue is to instead use `onCreateNode` to perform this logic. But because the order of `onCreateNode` calls is not known a priori, is there a better solution for "build-only state" than something like a global variable? Furthermore, is there any foreseeable issue with this approach?

```js
const globalState = {};

exports.onCreateNode = async ({ node, actions }) => {
  const { createNode, createNodeField } = actions;

  if (node.internal.type === 'MarkdownRemark') {
    if (/* check globalState to see if other MarkdownRemark node was already created */) {
      // If so, perform some custom logic here.
    }
    globalState[node.id] = true;
  }
};
```

Since Gatsby uses Redux to manage internal state at build-time, I would think it exposes some way (carves out a Redux namespace, perhaps?) to allow plugin site authors to keep build-time state. At the time of this writing, the [Data Storage (Redux)](https://www.gatsbyjs.org/docs/data-storage-redux/) docs page is a stub.

Thanks in advance for clarifying!

### Environment

```
$ gatsby info --clipboard

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.8.5 => 2.8.5
    gatsby-plugin-typography: ^2.2.13 => 2.2.13
    gatsby-source-filesystem: ^2.0.38 => 2.0.38
    gatsby-transformer-remark: ^2.3.12 => 2.3.12
  npmGlobalPackages:
    gatsby-cli: 2.6.4
```

**Comment by KyleAMathews** [comment]
It's not recommended — the transformer API is designed to be stateless so we can easily parallelize it across nodes which obviously won't share module-level state & we don't want to be syncing transitory state between nodes.

For your particular example, why would it matter if you recreated the same markdown node?

**Comment by mxxk** [comment]
Thanks for the prompt reply @KyleAMathews. 🙏 Since posting the issue I see an example of using a global variable in `gatsby-transformer-screenshot`. What makes it okay here?

https://github.com/gatsbyjs/gatsby/blob/5a3c1fc3171362ebc9ae4727be122db5448a71b9/packages/gatsby-transformer-screenshot/src/gatsby-node.js#L9

In my use case, I've defined a new GraphQL node type `PostTag` and am creating one per tag across all `MarkdownRemark` nodes: https://github.com/gatsbyjs/gatsby/issues/4614#issuecomment-500628839.

# Cache Problems

On further testing the solution in https://github.com/gatsbyjs/gatsby/issues/4614#issuecomment-500628839, I see that these newly-created `PostTag` nodes disappearing on subsequent builds. This is similar to the behavior described in #8629, though the proposed solution there is to set an appropriate node parent. In terms of caching, only if a particular tag is removed from _all_ posts, should that tag node's be deleted on a rebuild. But not sure how to implement that relationship in Gatsby's Node API...

**Comment by KyleAMathews** [comment]
That's a rather obscure plugin we'd don't put forward as a best practice :-)

It was built by a contractor and we don't recommend following that pattern. In that case, the state should have been stored in the remote service not in the local plugin.

It sounds like you want to do is directly define the `PostTag` type and filter `MarkdownRemark` nodes when the query is called https://www.gatsbyjs.org/docs/schema-customization/

**Comment by mxxk** [comment]
> That's a rather obscure plugin we'd don't put forward as a best practice :-)

Got it; thank you for clarifying.

> It sounds like you want to do is directly define the PostTag type and filter MarkdownRemark nodes when the query is called https://www.gatsbyjs.org/docs/schema-customization/

So far I've been able to arrive at the intended GraphQL schema and querying behavior with the wonderfully flexible [Node Type Mappings](https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types), but what has got me tripped up is the lifecycle of the nodes themselves post-creation.

Correct me if I'm wrong, but per the docs on schema customization, custom resolvers and the Gatsby `@link` directive would only affect the schema itself and not solve the problem of nodes disappearing on rebuilds.

I'll close out this issue as the original question is addressed (many thanks!), and open a new one on the subject of many-to-one node transformations and caching.

**Comment by KyleAMathews** [comment]
Are you setting the `parent` field for your transformed nodes? If you don't set that, Gatsby assumes the node is orphaned and deletes it.

**Comment by KyleAMathews** [comment]
Guess we can chat more in a new issue :-)

**Comment by mxxk** [comment]
> Guess we can chat more in a new issue :-)

#14766. See you there! 😄
