### ISSUE TITLE
TypeError: Cannot read property 'site' of undefined

### ISSUE THREAD

**Issue by magdalena-dering** [gatsbyjs/gatsby#14708]
## Description

Hi, 
I have created component in gatsby.js project. The component is build with three separate files - component, data and index.js. I have build similar component to one below with fetching title and is working fine. This one throw an error even if I restart gatsby, remove node_modules or clear cache (that helped me before).
Query in http://localhost:8000/___graphql is working fine:

```
{
  "data": {
    "site": {
      "siteMetadata": {
        "linkedin": "www.example.com",
        "github": "www.example.com"
        
      }
    }
  }
}
```
 

**Structure of the code:**

**Component:** 
```
import React from "react";
import { IconsContainer } from "../styles";
import { linkedin, github } from "../../../assets/icons";

const SocialIcons = ({ data }) => (
  <>
    <IconsContainer>
      <a href={data.site.siteMetadata.linkedin}>        
      </a>
      <a href={data.site.siteMetadata.github}>        
      </a>
    </IconsContainer>
  </>
);

export default SocialIcons;
```

**Data:** 
```
import React from "react";
import { graphql, StaticQuery } from "gatsby";

import SocialIcons from "./SocialIcons";

const SocialIconsData = () => (
  <StaticQuery
    query={graphql`
      query {
        site {
          siteMetadata {
            linkedin
            github 
          }
        }
      }
    `}
    render={data => <SocialIcons data={data} />}
  />
);

export default SocialIconsData;
```

**index.js**
`export { default } from "./components/ScoialIconsData";`

**gatsby-config.js**

```
module.exports = {
  siteMetadata: {  
    linkedin: 'www.example.com',
    github: 'www.example.com',
  },
```
### Steps to reproduce
yarn develop

### Expected result
clear console

What should happen?

### Actual result
"TypeError: Cannot read property 'site' of undefined"

What happened.

### Environment

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.0.33 => 2.9.0
    gatsby-cli: ^2.6.5 => 2.6.5
    gatsby-image: ^2.1.2 => 2.1.3
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.12
    gatsby-plugin-sass: ^2.0.7 => 2.0.11
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7
    gatsby-remark-prismjs: ^3.2.9 => 3.2.11
    gatsby-source-filesystem: ^2.0.38 => 2.0.39
    gatsby-transformer-json: ^2.1.6 => 2.1.11
    gatsby-transformer-remark: ^2.3.12 => 2.3.12
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21

**Comment by iFlameing** [comment]
@magdalena-dering I tried your code and It works fine for me. Just one problem might be in this line

> export { default } from "./components/ScoialIconsData";

For me it is export { default } from "../components/SocialIconsData";
can you provide your repo link. So that I can debug it :)

**Comment by magdalena-dering** [comment]
Yes, thank you in advance :)
https://github.com/magdalena-dering/folio.git

**Comment by iFlameing** [comment]
@magdalena-dering You are not importing SocialIconsData into Layout.js once you substitute the socialIcons with SocialData component your problem is solved :

**Comment by magdalena-dering** [comment]
Ohhh grrrr ;D 

Thank you :)
