### ISSUE TITLE
Error: `Unable to find element with ID ##`

### ISSUE THREAD

**Issue by couturecraigj** [gatsbyjs/gatsby#1470]
Thought I would post this for others benefit.

Spent plenty of time trying to debug this issue.  If you are using a hosted service make sure that they are not minifying your html (was using cloudflare).  This eliminates comments that signify `data-reactids` when the client grabs hold e.g. `<!-- react-text: 28 -->`.  This is a react specific thing and you need to make sure it is not being eliminated when doing static sites.  SSR does not seem to demonstrate this issue because it is not an html file but a generated string so this should probably be noted in the documentation.  Do you want a pull request for this @KyleAMathews?

**Comment by KyleAMathews** [comment]
Yes! We need to start a deployment page in general so this would be a good start. Perhaps deploying-gatsby.md and make a debugging section near the end addressing common problems like this.

**Comment by couturecraigj** [comment]
So, I wrote something out last night and submitted a pull request this morning.  If you want to take a look #1480 .

**Comment by KyleAMathews** [comment]
Fixed in #1480
