### ISSUE TITLE
gatsby-plugin-google-tagmanager verification for Google Search Console

### ISSUE THREAD

**Issue by kalongthewires** [gatsbyjs/gatsby#14712]
## Description

The Google Tag Manager (GTM) plugin for Gatsby does not seem to guarantee that the GTM snippet is inserted immediately after the `body` tag, which is a requirement for Google Search Console Verification.

### Steps to reproduce

Include both gatsby-plugin-google-tagmanager and gatsby-plugin-svg-sprite in your project (package.json and gatsby-config.js) and include a SVG somewhere on the page.

In gatsby-config.js:
![image](https://user-images.githubusercontent.com/2043335/59300775-01693f80-8c5e-11e9-828c-ba19972f173c.png)

When the html is outputted, the `svg` tag is inserted before the `noscript` from GTM under the `body` tag. 

![image](https://user-images.githubusercontent.com/2043335/59301276-37f38a00-8c5f-11e9-9212-201372f1ac66.png)

As a result, the Google Search Console verification does not work.

### Expected result

Both GTM snippets should be placed in the html document in the correct places per [Google's instructions](https://developers.google.com/tag-manager/quickstart) so that I can verify my site for Google Search Console. This means that the `noscript` snippet must be placed "immediately after the opening `<body>` tag".

Google's instructions:
![image](https://user-images.githubusercontent.com/2043335/59301026-a421be00-8c5e-11e9-9f75-bce89d21a65b.png)

### Actual result

The site cannot be verified and the following message is displayed on verification attempt: 
"Verification failed ... using the Google Tag Manager method ...  . The Google Tag Manager snippet on your site is in the wrong location"

### Environment
```
 System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v11.10.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.3
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.1.35 => 2.1.35
    gatsby-image: ^2.0.34 => 2.0.34
    gatsby-plugin-favicon: ^3.1.5 => 3.1.5
    gatsby-plugin-google-tagmanager: ^2.0.10 => 2.0.10
    gatsby-plugin-intercom: ^0.1.4 => 0.1.4
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24
    gatsby-plugin-prefetch-google-fonts: ^1.4.1 => 1.4.1
    gatsby-plugin-react-helmet: ^3.0.9 => 3.0.9
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.0.10 => 2.0.10
    gatsby-plugin-sharp: ^2.0.29 => 2.0.29
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7
    gatsby-plugin-svg-sprite: ^2.0.1 => 2.0.1
    gatsby-plugin-zopfli: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.0.27 => 2.0.27
    gatsby-transformer-json: ^2.1.11 => 2.1.11
    gatsby-transformer-remark: ^2.3.4 => 2.3.4
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17
  npmGlobalPackages:
    gatsby-cli: 2.6.5
```

**Comment by wardpeet** [comment]
it's going to be hard to enforce this. It probably depends on the order of your plugins. Could you create a small github project so we can test this properly?

Thanks!
