### ISSUE TITLE
Add a node field

### ISSUE THREAD

**Issue by ahmedelgabri** [gatsbyjs/gatsby#1471]
I'm trying to add a `slug` node field, had a look at [`https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-node.js`](https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-node.js#L70-L121) & [`https://github.com/gatsbyjs/gatsby/blob/master/www/src/templates/template-blog-post.js`](https://github.com/gatsbyjs/gatsby/blob/master/www/src/templates/template-blog-post.js#L176-L178)

And here is my `onCreateNode` function

```js
// Create slugs for files.
exports.onCreateNode = ({ node, boundActionCreators }) => {
  const { createNodeField } = boundActionCreators
  if (node.internal.type === 'File') {
    createNodeField({
      node,
      name: 'slug',
      value: path.basename(node.relativePath, '.md'),
    })
  }
}
```
and the query

```js
export const postQuery = graphql`
  query BlogPostBySlug($slug: String!) {
    site {
      siteMetadata {
        title
        author
      }
    }
    markdownRemark(fields: { slug: { eq: $slug } }) {
      id
      html
      fields {
        slug
      }
      frontmatter {
        title
        date
      }
    }
  }
`
```

But when I try to run this I get `GraphQLError: Cannot query field "fields" on type "MarkdownRemark"` any idea what am I doing wrong here?

**Comment by KyleAMathews** [comment]
Have you tried running the query in graphiql?

**Comment by ahmedelgabri** [comment]
Yes, I get the same error

**Comment by KyleAMathews** [comment]
Can you verify your `onCreateNode` function is being called? By adding a console.log there?

**Comment by ahmedelgabri** [comment]
It's getting called & returning an object with type `ADD_FIELD_TO_NODE` & the `payload` object inside it contains `field` object with a `slug` property inside of it.

**Comment by KyleAMathews** [comment]
Oh there is is. Your code has an if statement filtering nodes to only those of type "File". If you try querying File you'll see your field. You need to add the slug to nodes of type MarkdownRemark. Check out my blog for this pattern github.com/kyleamathews/blog

**Comment by ahmedelgabri** [comment]
Thanks @KyleAMathews

**Comment by morattoo** [comment]
I had the same problem doing the tutorial the programmatically create page.  @KyleAMathews can you explain what was your solution. I don't understand the pattern github.com/kyleamathews/blog.
Thanks!

**Comment by ahmedelgabri** [comment]
@morattoo You need something like this for example in Kyle's blog he is adding this field on [`MarkdownRemark`](https://github.com/KyleAMathews/blog/blob/c646f0ceb91b925ac9bd24c2164ec91a62636e68/gatsby-node.js#L83-L86) in my case I'm adding it [`Mdx` field](https://github.com/ahmedelgabri/gabri.me/blob/80627d950fdc5c91b5f015368772aa7e0e1cc40f/gatsby-node.js#L8) so you need to know which field you want to modify. 

```js
exports.onCreateNode = ({node, actions}) => {
  const {createNodeField} = actions

  switch (node.internal.type) {
    case '<FIELD TYPE YOU WANT TO CHANGE>': { // <-- Change this to match your usage.
      const {
        fileAbsolutePath,
      } = node

      createNodeField({
        node,
        name: 'slug',
        value: `/blog/${path.basename(fileAbsolutePath, '.md')}`,
      })
    }
  }
}
```

**Comment by iDVB** [comment]
Also having no luck getting a custom field to stick to a node.

```javascript
exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions;

  if (!isLeverNode(node)) return;
  createNodeField({
    node,
    name: 'slug',
    value: `${node.lever_id}_dvb`,
  });

  console.log('onCreateNode', node);
};
```

That console.log shows the `node.fields.slug` being added... but then when I try to access it from graphql, or from graphiQL its not there.

**Comment by vexilar** [comment]
What ended up happening with this?  Shouldn't the solution ultimately be to fix the code samples here: https://www.gatsbyjs.com/tutorial/part-seven/ ?  Is there really that few people walking through the tutorial?

**Comment by vexilar** [comment]
Root cause for me was I had put gatsby-node.js in the src folder instead of the root of the site as the tutorial directs -- my bad.  Hopefully this helps someone else.
