### ISSUE TITLE
[www] Use styled-system.com/css/

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#14722]
I've been chatting with @jxnblk about this today: With #14360 incoming, how about switching `www` to use https://styled-system.com/css/?
Stating the obvious DX benefits:

- no need to import design tokens anymore, e.g. https://github.com/gatsbyjs/gatsby/blob/29e2de43ddc97eb9065d5981f3a4a13745c2b86c/www/src/components/avatar.js#L4
- no need for the syntactic overhead of https://emotion.sh/docs/theming brings along, e.g.  
  ```jsx
   <div css={theme => ({ color: theme.colors.primary })}>
      some other text
    </div>
  ```
- in line with ~https://theme-ui.now.sh/~ https://theme-ui.com/

Drawbacks, AFAIU:

- no more treeshaking for design tokens
- more magic ✨

**Comment by jxnblk** [comment]
Happy to address any questions/concerns about this. Small note, the docs are now being deployed to https://theme-ui.com and the ones linked above may be outdated

> no more treeshaking for design tokens

There are probably other tradeoffs between any treeshaking that using modules might provide and using React context for design tokens – I'd guess that it's probably not a huge concern and that it's probably best to rely on real-world performance metrics to determine what performs better.

> more magic ✨

It definitely is. I'll add that we'd looking into making sure the API for these sorts of utilities are explicit and don't cause unexpected results. The main idea is to make it easier to use theme-based values by default, but also obvious to apply raw values when needed. That said, the `@styled-system/css` library is newer than the core `styled-system` (props-based API), and that it's a little less battle-tested

**Comment by fk** [comment]
Closing in favor of `theme-ui`.
