### ISSUE TITLE
feat(site-showcase-validator): Output daily results to Discord

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#14744]
## Summary

As discussed in the OSS Maintainers meeting this week, I brought up the idea to take the output of the Site Showcase Validator and output into the Gatsby Discord. The outputs of the current action found at [.github/actions/gatsby-site-showcase-validator](https://github.com/gatsbyjs/gatsby/tree/master/.github/actions/gatsby-site-showcase-validator) could be saved to a file and then read into another action that passes a string using Discord's API

### Motivation

By putting these results in a more public place, we can more easily be notified about issues and clean up the showcase frequently.

**Comment by leanmiguel** [comment]
Can I help with this?

**Comment by lannonbr** [comment]
@leanmiguel Do you have access to GitHub Actions? If not, I would be open as well to pair program on this as I do have access to Actions and have a good knowledge-base around the validator. I have a private discord for testing so we could test things out there and then move the code into here.

**Comment by leanmiguel** [comment]
I do not have access to GitHub Actions. As this would be my first open source contribution, I would be very open to the pair programming session. I'm currently just trying to get the output from the validator.

**Comment by lannonbr** [comment]
Alright. Feel free to send an email (you can find it on my profile page) to me and we can set up a time to pair program.

Looking forward to it!

**Comment by lannonbr** [comment]
As an update, Lean and I had a pair programming session today to tackle this and we made some good progress.

What we still need to do is as follows:
1. Update the validator action to save the results to a file on a filesystem. Then this can be loaded in the discord bot action.
2. Create some local tests to run the entire workflow with actual data.
3. Make a PR against Gatsby to push the new action as well as the changes to the validator action.

**Comment by lannonbr** [comment]
Further as a notice, I discussed this on the Maintainers meeting this week and @DSchau brought up that this would be a stepping stone that may not be the best solution. With that, he brought up the idea for instead looking into possibly making an action to create PRs to remove sites that the validator finds are no longer Gatsby sites.

With this, I am going to close this issue.
