### ISSUE TITLE
No compile errors for html.js JSX

### ISSUE THREAD

**Issue by patricksimpson** [gatsbyjs/gatsby#1475]
## Issue

No compile errors for `html.js`JSX.  File is ignored until errors are fixed.

## Description

Made changes to the `html.js` file and noticed that compile errors (errors in the JSX) are not being caught (or reported).

Using the example from https://www.gatsbyjs.org/docs/building-with-components/#html-component `html.js` file, adding an erroneous JSX object `<link href={customLink}>` **note** lack of trailing `/`. No error is reported and the `html.js`file is then ignored and not used even when the server is stopped and restarted. (note the changes to the `html.js` file are not being picked up unless server is stopped and restarted regardless due to issue #1442). 

## Reqs

`node -v && npm -v && gatsby -V`
                                                                                                                                 
v6.10.3
4.0.3
1.0.11

`cat gatsby-config.js`:
```

module.exports = {
  plugins: [
    `gatsby-plugin-sass`,
    `gatsby-plugin-react-helmet`
  ],
}
```

**Comment by KyleAMathews** [comment]
Are there no errors displayed in both development and production builds?

**Comment by patricksimpson** [comment]
@KyleAMathews No errors in either production or development.

**Comment by imjared** [comment]
I'm not sure this issue is restricted to `html.js`. I'm having the same problem after editing my `layouts/index.js`.

**Comment by imjared** [comment]
Trying to track this issue down and so far it's to no avail.

@KyleAMathews I know you're a busy dude so are there any areas of the repo you'd recommend for me to investigate? I have a hunch you might be a bit more familiar than I with what's going here. I'd love to send a PR your way if I can but could use a jump start :)

**Comment by KyleAMathews** [comment]
This is where the development HTML file is generated: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/develop-html.js

This is the entry file for that https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/develop-static-entry.js

this is the script setting up the development server https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/develop.js

**Comment by KyleAMathews** [comment]
Pretty sure this was fixed — lemme know if there's still problems.
