### ISSUE TITLE
Got GraphQL Syntax Error in Visual Studio Code

### ISSUE THREAD

**Issue by WildDagger** [gatsbyjs/gatsby#14759]
I installed Gatsby and want to use StaticQuery.
However, I got a syntax error in Visual Studio Code.
I don't know why my Code can not detect GraphQL Code rightly.

[Here is error what happened](https://i.stack.imgur.com/Huhms.png)

I copied StaticQuery code from [this page](https://www.gatsbyjs.org/docs/static-query/)

Can someone tell me how to solve this problem?

P.S. I have already updated to the latest version, and I install GraphQL and Babel Javascript Extension, not use.

**Comment by josefaidt** [comment]
You need to surround the query with backticks. 

```js
...
<StaticQuery
  query={graphql`
    query HeadingQuery {
        # your query
     }
  `}
  render={...}
>
`
```

**Comment by WildDagger** [comment]
> 
> 
> You need to surround the query with backticks.
> 
> ```js
> ...
> <StaticQuery
>   query={graphql`
>     query HeadingQuery {
>         # your query
>      }
>   `}
>   render={...}
> >
> `
> ```

I got it. Thanks a lot.
