### ISSUE TITLE
[docs] add info about working with multiple images 

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14753]
## Summary

As part of the [image workflow evaluation](https://github.com/gatsbyjs/gatsby/issues/14529), one use case that would be good to document is how to work with multiple images, like with an image gallery or something. Currently options are somewhat limited and the GraphQL workflow is awkward, but hopefully that will be improved in the future with https://github.com/gatsbyjs/gatsby/issues/10482. 

In order to keep the overarching image workflow evaluation issue from depending on this one item, I've created this new issue to track the need for docs on working with multiple images.

Here's an example of how they are referenced in the current docs for [Working With Images](https://www.gatsbyjs.org/docs/working-with-images/), in the section on fragments:

```
export const query = graphql`
  query {
    image1: file(relativePath: { eq: "images/image1.jpg" }) {
      ...squareImage
    }

    image2: file(relativePath: { eq: "images/image2.jpg" }) {
      ...squareImage
    }

    image3: file(relativePath: { eq: "images/image3.jpg" }) {
      ...squareImage
    }
  }
```
This is very repetitive...and for anything more than a handful of images it's quite awkward. We're open to any ideas for making this more dynamic, while keeping in mind that https://github.com/gatsbyjs/gatsby/issues/10482 is likely the ultimate direction.

**Comment by lstar19** [comment]
Aliases is one use case, but when I've done this in the past I've stored paths to the images in yaml(or markdown) and queried them together. The only hiccup is this assumes you're going to loop through your results for display OR you can consistently assume an index for each image you want.

**Comment by marcysutton** [comment]
I think any and all solutions would be helpful for the time being!

**Comment by marcysutton** [comment]
One other potential solution I thought of was using `allFile` to query a folder of images–I haven't actually tried it to know if it works, but the thought crossed my mind. One limitation of this approach would be matching images to alt text, a use case that we should remind developers of every chance we get. So using YAML or JSON may still be the way to go.

To satisfy this issue, we should add details to the [Working with Images](https://www.gatsbyjs.org/docs/working-with-images/) doc (before "Additional Resources") to make recommendations for working with multiple images. We could also link to this new information towards the end of [Using Gatsby Image](https://www.gatsbyjs.org/docs/using-gatsby-image/ ).

**Comment by lstar19** [comment]
When I'm done with the image tutorial I might be able to leverage some of that for the yaml use case we discussed above.
