### ISSUE TITLE
gatbsy-source-medium: Provide GraphQL Types

### ISSUE THREAD

**Issue by AniaMakes** [gatsbyjs/gatsby#14765]
## Description

As far as I can tell, gatsby-source-medium fetches a JSON of Medium data. At some point this becomes a GQL schema. The schema's types are somehow inferred based on the content.
Unfortunately, Medium - in some cases - has two different content types for one key. 

This results in the following warning

```warn There are conflicting field types in your data.

If you have explicitly defined a type for those fields, you can safely ignore this warning message.
Otherwise, Gatsby will omit those fields from the GraphQL schema.

If you know all field types in advance, the best strategy is to explicitly define them with the `createTypes` action, and skip inference
with the `@dontInfer` directive.
MediumUser.mediumMemberAt:
 - type: date
   value: '2017-09-28'
 - type: number
   value: 0
MediumPost.importedPublishedAt:
 - type: date
   value: '2017-12-07'
 - type: number
   value: 0
MediumPost.curationEligibleAt:
 - type: date
   value: '2019-06-11'
 - type: number
   value: 0
```
I'm going to guess that Medium uses `0` as equivalent of `null`, but unfortunately when building a schema this gets interpreted as a number. Due to the confusion, I don't think the affected key ever makes it into the GQL schema. 

### Steps to reproduce

Use any large Medium blog (ours is https://medium.com/yld-engineering-blog/latest?format=json) to feed into Gatsby-source-medium. `yarn develop` will boot up the project and the errors will show. 

### Expected result

Unsure, actually. The relevant key should make it into the schema, but I can tell it would be tricky to get the typing right, both at Gatsby end and the User making type assumptions...

Maybe check with Medium to see what fields are affected by the duality and make it so that the type inferring function assigns the correct type and replaces the 0 with `null`?

### Actual result

Console error and the key doesn't make it into the schema

### Environment

```
  System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.5.0-next.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.80
  npmPackages:
    gatsby: ^2.8.3 => 2.8.3 
    gatsby-image: 2.0.20 => 2.0.20 
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1 
    gatsby-plugin-favicon: 3.1.4 => 3.1.4 
    gatsby-plugin-google-analytics: 2.0.7 => 2.0.7 
    gatsby-plugin-google-tagmanager: ^2.0.6 => 2.0.15 
    gatsby-plugin-modal-routing: ^1.0.0 => 1.0.0 
    gatsby-plugin-react-helmet: 3.0.2 => 3.0.2 
    gatsby-plugin-sharp: ^2.0.13 => 2.1.3 
    gatsby-plugin-sitemap: 2.0.2 => 2.0.2 
    gatsby-plugin-styled-components: 3.0.3 => 3.0.3 
    gatsby-source-contentful: 2.0.15 => 2.0.15 
    gatsby-source-filesystem: ^2.0.8 => 2.0.37 
    gatsby-source-lever: 2.0.1 => 2.0.1 
    gatsby-source-medium: 2.0.8 => 2.0.8 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.21 

```

**Comment by sidharthachatterjee** [comment]
> Maybe check with Medium to see what fields are affected by the duality and make it so that the type inferring function assigns the correct type and replaces the 0 with null?

This is a little tricky to do. 

I think the best solution here would be to set types yourself as mentioned in the error. We would have to update `gatsby-source-medium` and set a schema based on known types. 

> If you know all field types in advance, the best strategy is to explicitly define them with the `createTypes` action, and skip inference
> with the `@dontInfer` directive.

cc @freiksenet

**Comment by AniaMakes** [comment]
Something that I didn't realise when I was writing the bug report, but is important - when this issue was first raised in my team on the 20th of May, the warnings read

```
warning There are conflicting field types in your data. 
GraphQL schema will omit those fields

MediumUser.mediumMemberAt:
 - type: number
   value: 0
 - type: string
   value: '2017-09-28'

MediumPost.importedPublishedAt:
 - type: number
   value: 0
 - type: string
   value: '2017-12-07'

MediumPost.curationEligibleAt:
 - type: number
   value: 0
 - type: string
   value: '2019-02-25'
```

It's the same keys, but the types were string rather than dates... I don't know if this why that was, but I think it's worth adding here.

**Comment by stefanprobst** [comment]
@AniaMakes As a workaround, you can explicitly define those fields as Dates:
```js
// gatsby-node.js
exports.sourceNodes = ({ actions }) => {
  actions.createTypes(`
    type MediumUser implements Node {
      mediumMemberAt: Date
    }

    type MediumPost implements Node {
      importedPublishedAt: Date
      curationEligibleAt: Date
    }
  `)
}
```

**Comment by freiksenet** [comment]
As a long term solution to this, `gatsby-source-medium` should define all types in `createTypes`.

**Comment by vladar** [comment]
This was fixed via https://github.com/gatsbyjs/gatsby/pull/22377
