### ISSUE TITLE
GraphQL Node with Multiple Upstream Dependencies

### ISSUE THREAD

**Issue by mxxk** [gatsbyjs/gatsby#14766]
## Summary

How does one model transformed GraphQL nodes in Gatsby which depend on more than one source node? 🤔

Gatsby uses parent/child relationships between nodes to:

1. Know which cached nodes are stale and should be deleted for subsequent builds.
2. Implement live updates in `gatsby develop`.

Thus, if the parent of a created node is not set properly, this node may not update correctly on rebuilds or disappear altogether (#8216). However, because each child node has exactly one parent, it is not possible to let Gatsby know that a node's existence and data relies on more than one upstream node and should be re-created in response to any of them changing.

The purpose of this issue is to start a discussion of how something like this may be accomplished with Gatsby in the future.

## Relevant information

An example of a transformed node which depends on multiple source nodes is `PostTag` in the example project https://github.com/mxxk/test-gatsby-multi-parent-node. One `PostTag` node is created per tag across _all posts_ (i.e. `MarkdownRemark` nodes) on the site.

| Post   | Tags            |
| ------ | --------------- |
| Post 1 | Gatsby, Awesome |
| Post 2 | Gatsby, Super   |
| Post 3 | Gatsby, Super   |

From the above posts and tags, three `PostTag` nodes are produced: "Gatsby", "Awesome", "Super".

The problem is that the initial `gatsby build` / `gatsby develop` succeeds, but subsequent re-runs generate erroneous output unless preceded with `gatsby clean`. This is because all `PostTag` nodes are created with `parent: null`, and are not touched with `touchNode` on a rebuild. (What parent would even make sense in this case, if no single post is responsible for creating a shared tag?)

### Many-to-Many Dependency

Conceptually, every created `PostTag` node depends on every post which is tagged with it, because the removal a tag from its last post should result in deletion of the newly-orphaned `PostTag`.

### Partial Workaround

A workaround (available in the [workaround branch](https://github.com/mxxk/test-gatsby-multi-parent-node/tree/workaround)) uses extra logic in `sourceNodes` to identify existing `PostTag` nodes which should still be valid based on existing `MarkdownRemark` nodes and touches them with `touchNode`. This solves the issue of disappearing nodes in re-runs of `gatsby build` and `gatsby develop`.

```js
exports.sourceNodes = ({ actions, getNodesByType, createNodeId }) => {
  const { touchNode } = actions

  getNodesByType(`MarkdownRemark`).forEach(node =>
    node.frontmatter.tags.forEach(tag =>
      touchNode({
        nodeId: createNodeId(`PostTag-${tag}`)
      })
    )
  )
}
```

### Full Workaround

The partial workaround above is so named because it has one problem. With `gatsby develop` running, if the tag "Awesome" is renamed to "Awesome2", the old tag will remain and appear in the [All Tags](https://mxxk.github.io/test-gatsby-multi-parent-node/tags/) page along with "Awesome2" even though it has no more posts and should be deleted. (When `gatsby develop` is restared, and `sourceNodes` runs, the previously described partial workaround will remove the stale `PostTag`.)

To delete old nodes without having to restart the development server, a solution is to explicitly scan for and delete stale `PostTag` nodes in `createPages`:

```js
  // Remove old `PostTag` nodes.
  const allTags = new Set(
    getNodesByType(`MarkdownRemark`).flatMap(node => node.frontmatter.tags),
  )
  getNodesByType(`PostTag`).forEach(node => {
    if (!allTags.has(node.tag)) {
      deleteNode(node)
    }
  })
```

While the full workaround (available in the [workaround-deletenode branch](https://github.com/mxxk/test-gatsby-multi-parent-node/tree/workaround-deletenode)) accomplishes its goal, it does so at a price of performance, since now `createPages` has to re-examine _all posts_ when any single post changes. :anguished:

### A New Hope for a Better Solution

Gatsby's use of GraphQL node parent/child relationships to track inter-node dependencies seems to be a very clean design, as it re-uses an existing feature of GraphQL for build caching and live reload. It is difficult to imagine an equally clean proposal which would maintain both the existing simplicity plus something to solve the multi-parent dependency problem.

If such a solution were to exist, it would enable faster live reload than any of the workarounds, as only those nodes whose upstream dependencies changed would get re-created. (In the workarounds, _all_ nodes were inspected in the ad-hoc ways to achieve desired state). In my experimentation, it does not seem that Gatsby supports multiple calls to `createParentChildLink` with different parent nodes for the same child node, as it surfaces an obscure error during the build.

One important requirement for a multi-parent dependency solution of any sort is the ability to modify inter-node dependencies _after_ initial creation. (I'm not sure if node _reparenting_ is possible in today's implementation, but that would be the closest equivalent of the ask expressed in terms of the single-parent model.) In the `PostTag`, example, this would mean that each `PostTag` "depends" on each `MarkdownRemark` node which has its tag, and these dependencies would get updated as tags are added and removed in `gatsby develop` mode to keep the live site up-to-date.

All right, that's all for this blog post-length issue! :nerd_face:

**Comment by sidharthachatterjee** [comment]
cc @KyleAMathews

**Comment by freiksenet** [comment]
I wouldn't change the parent/child model. I think it's clean that there is only one parent with node.

Instead, how I would solve this is to add a `SomethingTags` chlid. This child would be a container for tags for a particular node, created by a particular transformer plugin. Let's consider your example.

Post nodes will have `PostTags` child. Here is the type definition for it:

```graphql
type PostTags implements Node {
  tags: [Tag]
}
```

`Tag` would be the actual Tag type.

```graphql
type Tag implements Node {
  name: String!
  posts: [PostTags]
}
```

This way both types would be created inside your transformer plugin, meaning they both own it. Here is how you would query it:

```graphql
post(id: 1) {
  childPostTag {
     tags {
        name
      }
  }
}

tag(name: "Awesome") {
  posts {
    parent {
      name
    }
  }
}
```

This is all achievable currently in Gatsby. Hope it helps!

**Comment by freiksenet** [comment]
Ping @mxxk.

**Comment by mxxk** [comment]
Thanks @freiksenet, that seems like a nifty suggestion and I want to give it a try soon. From the perspective of GraphQL connections, it makes perfect sense. From the perspective of GraphQL parent/child relationships, hopefully these two follow-up questions will help clear it up! 💭

1. It sounds like the middleman type `PostTags` solves the problem of type ownership, right? That way the plugin owns `PostTags` and does not have to mess with the type of the actual `Post`.

2. Each `Post` has a `PostTags` child (1:1 relationship), that part is clear. But when it comes to having `PostTags` connect to a list of `Tag` nodes, which node is the parent for a given `Tag`?

    To reuse the example above with three posts and three tags,

    | Post   | Tags            |
    | ------ | --------------- |
    | Post 1 | Gatsby, Awesome |
    | Post 2 | Gatsby, Super   |
    | Post 3 | Gatsby, Super   |

    say the plugin is creating a `Tag` node for "Super" which exists in Post 2 and Post 3. If there is only one `Tag` per unique tag string across all posts, then which parent node would this `Tag` be attached to?

    ```
    Post 1  -----  PostTags 1  -+----  Tag "Awesome"
                                 \
                                  \
    Post 2  -----  PostTags 2  -+--+-  Tag "Gatsby"
                                 \/
                                 /\
    Post 3  -----  PostTags 3  -+--+-  Tag "Super"


Thank you for clarifying!

**Comment by freiksenet** [comment]
@mxxk In this case, you wouldn't use parent->child relationships, but instead like them through either `___NODE` convention or through `@link` directive in GraphQL definition. It really depends on how exactly you'll store the tags.
