### ISSUE TITLE
Blog archive from JSON, Gatsby Image returns 'TypeError: node.photo is null'

### ISSUE THREAD

**Issue by bpsmpls** [gatsbyjs/gatsby#14778]
## A little background

Long term, I'm trying to build a site that utilizes a JSON file as the primary data source. This project is a stepping stone as a means of learning Gatsby and determining its viability for that project. I'm sure I could use Markdown for some of this, but I'm really trying to utilize JSON as a means of building knowledge for my next project.

## Description

I'm creating a blog archive of an old Tumblr from a few years ago and supplying the complete, unchanging posts via JSON. I've been able to follow tutorials well enough to get Gatsby to output loops containing most of that data: post slug, text content, video IDs, etc. 

However, I've hit a hard wall with rendering out images using Gatsby Image. Images are stored in the same directory as the JSON file and are recognized properly in GraphQL queries, but when rendering out in my templates, I get a notification in-browser: 'TypeError: node.photo is null' with the offending line highlighted. 

![Screenshot of error](https://i.imgur.com/8kxBECP.png)
[Screenshot of error](https://imgur.com/a/EJwq6me)

When I inspect the results in the console, the photo object is populated alongside all my requested data. 

When I output simply ```{node.photo}``` in blog-post.js with a simple ```<img src={props.photo} />``` in post-media.js, the page renders with ```<img src="[object Object]">``` as expected, indicating there is an object to parse there. 

```gatsby develop``` results in a successful compile and images appear to be outputting to /public without issue.

I've also tried using node v12.4.0, but saw the same result.

### Steps to reproduce

My working repository:
https://github.com/bpsmpls/bpsopposketch.com

You should be able to pull down and do a simple build to reproduce the issue. 

### Expected result

I expect the ```<img>``` will display as an optimized image on the index.js page for each blog post on the site (further deferred post-loading optimization to come later on my end).

So far, Gatsby's tutorials have been amazing in introducing me to JSX, React, and Gatsby as a whole, but I have found difficulty in troubleshooting this issue using the tutorials, [Gatsby Image docs](https://www.gatsbyjs.org/packages/gatsby-image/), and internet searches thus far.

### Actual result

Error preventing page display: 'TypeError: node.photo is null' when GraphQL query shows successful acquisition of data.

### Environment
```
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.14.0/bin/npm
    Languages:
      Python: 2.7.10 - /usr/bin/python
    Browsers:
      Chrome: 74.0.3729.169
      Firefox: 67.0
      Safari: 12.1.1
    npmPackages:
      gatsby: ^2.8.3 => 2.8.5 
      gatsby-image: ^2.1.2 => 2.1.2 
      gatsby-plugin-emotion: ^4.0.7 => 4.0.7 
      gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
      gatsby-plugin-offline: ^2.1.1 => 2.1.1 
      gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
      gatsby-plugin-sharp: ^2.1.3 => 2.1.3 
      gatsby-plugin-typography: ^2.2.13 => 2.2.13 
      gatsby-source-filesystem: ^2.0.38 => 2.0.38 
      gatsby-transformer-json: ^2.1.11 => 2.1.11 
      gatsby-transformer-sharp: ^2.1.21 => 2.1.21 
    npmGlobalPackages:
      gatsby-cli: 2.6.7
```

**Comment by stefanprobst** [comment]
In your `posts.json`, not every entry has a `photo` field (e.g. the one with id 154247942990 has not). so `node.photo` would be `null` here.

**Comment by bpsmpls** [comment]
Oh I forgot to mention that in the original post, but removal of the singular video post still produced the same result in my testing. I would love to know how to handle that better with conditional logic.

**Comment by stefanprobst** [comment]
* you have one other empty `node.photo` field because of a typo [here](https://github.com/bpsmpls/bpsopposketch.com/blob/6d0e9d742b17af09be91487219f4c752bf822a95/src/data/posts.json#L210) -- this path doesn't exist
* also make sure to lowercase the `fluid` attribute on `<Img />` [here](https://github.com/bpsmpls/bpsopposketch.com/blob/6d0e9d742b17af09be91487219f4c752bf822a95/src/components/post-media.js#L14)

**Comment by bpsmpls** [comment]
Eagle eyes! Using lowercase ```fluid``` on the ```<Img />``` and addressing the two issues in my JSON mentioned in this thread — fixing the typo for one photo post and adding a placeholder photo for the video post — did the trick. I was going crazy with this! That popsicle typo was the variable I hadn't seen. 

Thank you for your patient sleuthing, stefanprobst!

**Comment by stefanprobst** [comment]
Great to hear!

As a tip, you can use the [Graphiql explorer](https://www.gatsbyjs.org/docs/introducing-graphiql/) to easily find `null` query results, e.g. with:
```graphql
{
  allPostsJson(filter: {photo: {id: {eq: null}}}) {
    edges {
      node {
        _id
        slug
      }
    }
  }
}
```
