### ISSUE TITLE
Guide for creating plugins should explain when the plugin code is executed

### ISSUE THREAD

**Issue by eyalroth** [gatsbyjs/gatsby#14773]
Nowhere in the [guide for creating plugins](https://www.gatsbyjs.org/docs/creating-plugins/) it is mentioned that the exported code of the plugin will only run upon changing relevant files - either `gatsby-config.js` or perhaps some Markdown files.

As a beginner to Gatsby (and node / js in general), I didn't realize that `gatsby develop` isn't enough to guarantee my plugin's code will run, and that I have to either change a file or delete the cache (`.cache` folder).

**Comment by mokimo** [comment]
I'd suggest opening a PR for the documentation. That's a good suggestion because I remember having issues when writing a plugin myself a few months back

**Comment by eyalroth** [comment]
@mokimo Thing is I'm quite a newbie to this entire ecosystem, so I fear I'm not the right person for this job.

**Comment by mokimo** [comment]
Oh, it's a good first issue, a good way to make your first step into an open source contribution! 

IMO this file would do:
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/creating-a-local-plugin.md

You could either fork the repo and make a PR or edit the file via the GitHub UI (That's like cheating tho :P)

**Comment by eyalroth** [comment]
@mokimo I don't really have the knowledge required to explain what's going on behind the scenes in regards to this case. I'm not familiar with the lifecycle of gatsby.
