### ISSUE TITLE
Serve Gatsby blog site in sub directory with Netlify

### ISSUE THREAD

**Issue by medyun** [gatsbyjs/gatsby#14771]
Hello there. I'm new to gatsby and netlify and I'm having a problem.

I have a domain called example.com. It has an index.html file, which is a static html file. I want to create a subfolder named blog here and put the blog I created with gastby into it.

> example.com -> run index.html
> example.com/blog -> run gatsby blog inside blog folder

When I do this and try to build in netlify, I get an error. The error message is: "**failed during stage 'building site': Build script returned non-zero exit code: 127**".

I tried to set up Netlify deploy as follows:
`
Base directory: Not set
Build command: cd blog && gatsby build
Publish directory: public/
`

How can I solve this problem?

**Comment by devrchancay** [comment]
I think you should specify the base directory instead of using `cd blog`

![321C0BFA-2CEB-4503-9A67-AB1F2FB679AF](https://user-images.githubusercontent.com/4138285/59546984-bc166d80-8efc-11e9-81cb-5a371a3eb656.png)

**Comment by universse** [comment]
Or you can set publish directory to blog/public

**Comment by medyun** [comment]
Thanks @devrchancay. The error has changed now. My netlify.toml file looks like this:
`
[build]
  base    = ""
  publish = "public"
  command = "cd blog && rm -rf .cache/ public/ node_modules/ && gatsby build --prefix-paths && cd public && mkdir blog | mv * blog"
`

and I get an error like this:
`/usr/local/bin/build: line 34: gatsby: command not found`

I don't understand what's wrong :/

**Comment by sidharthachatterjee** [comment]
> and I get an error like this:
> /usr/local/bin/build: line 34: gatsby: command not found
> 
> I don't understand what's wrong :/

@medyun You're seeing this since `gatsby` isn't installed globally and hence not available in the Netlify environment. A quick fix would be to:

1. add `"build": "gatsby build"` under `scripts` in `package.json`
2. On Netlify, set the Build command to `npm build`

Closing this for now. Please feel free to re open this in case you're still seeing this!

**Comment by medyun** [comment]
I installed gatsby globally. Now, gastby running on subfolder but not running index.html inside root ("/").

`example.com -> run index.html (NOT RUNNING)
example.com/blog -> run gatsby blog inside blog folder (RUNNING)
`

My netlify.toml:
`[build]
  base    = "blog"
  publish = "public"
  command = "npm run build"
`

My build command:
`npm install && gatsby build --prefix-paths && cd public && mkdir blog && mv * blog`

**Comment by wouter-dev** [comment]
Is this solved yet? Wondering the same?

**Comment by israteneda** [comment]
I hope this post helps:
https://community.netlify.com/t/common-issue-can-i-deploy-multiple-repositories-in-a-single-site/179
