### ISSUE TITLE
Problem Firebase Messaging (Push notification)

### ISSUE THREAD

**Issue by aikodeio** [gatsbyjs/gatsby#14780]
Hi, I hope you can guide me or help me if possible. I am trying to integrate Firebase Messaging (Push notifications), using the Firebase guide on YouTube (https://www.youtube.com/watch?v=BsCBCudx58g&t) 
together with Gatsby. 

In localhost: 8000 I get this error:

**The script has an unsupported MIME type ('text/html').
index.js:2177 FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html'). (messaging/failed-serviceworker-registration).**

With the command "gatsby build" I receive this error:

**error Building static HTML failed

See our docs page on debugging HTML builds for help

  2122 | registerMessaging(firebase);
  2123 | function isSupported() {
> 2124 |     if (self && 'ServiceWorkerGlobalScope' in self) {
       | ^
  2125 |         // Running in ServiceWorker context
  2126 |         return isSWControllerSupported();
  2127 |     }

  WebpackError: ReferenceError: self is not defined

  - index.esm.js:2124 isSupported
    [lib]/[@firebase]/messaging/dist/index.esm.js:2124:1**

THANKS!!!

**Comment by sidharthachatterjee** [comment]
Based on the error above, it looks like the library you're using is not SSR friendly and is breaking builds because of that 

Read more about this at https://www.gatsbyjs.org/docs/debugging-html-builds/

**Comment by klutchdev** [comment]
Hey, I have the solution for this if you still need it.

**Comment by AlexanderChiclana** [comment]
> Hey, I have the solution for this if you still need it.

I need a solution for this if you happen to still remember
