### ISSUE TITLE
Rewrite path

### ISSUE THREAD

**Issue by TibiTotoro** [gatsbyjs/gatsby#14788]
For some pages, i want to to change the URL path in the router to not map directly to the path on the filesystem. 
These pages will be placed on subdomains, all such pages are building to a folder /test/, we get /test/subdomain1/index.html,  /test/subdomain2/index.html, /test/subdomain3/index.html etc.

Redirection is configured by Nginx, but gatsby take path from gatsby-script-loader and a page subdomain.domain.com redirected to subdomain.domain.com/test/subdomain1/index.html

I saw that a similar question about path rewriting was raised in [#3113](https://github.com/gatsbyjs/gatsby/issues/3113) and  [#383](https://github.com/gatsbyjs/gatsby/issues/383) but there is no solution to these questions.

Is there any solution to this problem? Thanks!

**Comment by sidharthachatterjee** [comment]
You should be able to do this using path prefixes. 

Read more about this at https://www.gatsbyjs.org/docs/path-prefix/

**Comment by TibiTotoro** [comment]
Wow, how quickly closed the question) 
I found a solution to this problem in [4337,](https://github.com/gatsbyjs/gatsby/issues/4337) the plugin https://github.com/wardpeet/gatsby-plugin-static-site helps to remove unnecessary redirects. 
Вut I'm not sure this is the best solution.
@sidharthachatterjee, сould you describe in more detail how path-prefix can help me? I need to build pages for the main domain in one project, as well as pages for all subdomains in the same project, in the folders demo/subdimain1, demo/subdimain2, demo/subdimain3. There are many subdomains and they are of the same type. All redirect will will be made Nginx. 
This task is more like building several app in one project, but in several similar questions I did not find simple solution to this problem.

**Comment by sidharthachatterjee** [comment]
@TibiTotoro Sorry for closing this too soon! 

Let me elaborate. Path prefixes let you host at something other than at the the root (/) of the domain.

For example in your case, you could build the sites for each sub domain independently and put in folders demo/subdimain1, demo/subdimain2, demo/subdimain3. For this, you would set the path prefix as /subdimain1, /subdimain2 and /subdimain3 respectively.

**Comment by TibiTotoro** [comment]
I understand correctly that you propose to run build several times, each time with your own path-prefix and put the files into different folders? Is there any way to automate this (there are many subdomains)? Is there any way to avoid duplication of static content such as images and documents that are the same for subdomains? If I duplicate static content 30-40 times, the output project will be terribly large. 
In this moment i build project once, create pages for subdomains by createPages in gatsby-node.js, disable gatsby routing and set up redirects by nginx, вut i think, this may lead to problems.

**Comment by xavivars** [comment]
@sidharthachatterjee: path-prefix allows to host at something other than /, but it doesn't allow you to host at something other than / while, at the same time, _serving_ at a different URL where it's in the filesystem, because first thing gatsby app does is a "canonical check": 

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/production-app.js#L69

in #4337 there was a proposal to introduce a config variable to disable such redirect, but was closed in favor of a workaround that doesn't work anymore.

**Comment by digitaldiy** [comment]
Wouldn't this approach work?
https://nextjs.org/docs/api-reference/next.config.js/rewrites
