### ISSUE TITLE
Excerpts are not displayed on the main page

### ISSUE THREAD

**Issue by romach** [gatsbyjs/gatsby#14791]
## Description

Excerpts are not displayed on the main page

### Steps to reproduce

1. Create new project using `gatsby-starter-blog` starter

    ```bash
    gatsby new new-blog https://github.com/gatsbyjs/gatsby-starter-blog
    ```

2. [Add HTML excerpt to blog post](https://github.com/romach/gatsby-example/commit/4e647d5b7ce1581257a2d91c173f7da64fff89f5)

3. Build and serve site

    ```bash
    gatsby build
    gatsby serve
    ```

4. Open url `http://localhost:9000/`

5. Excerpts in second and third blog posts dissappered

6. After page reloading excerpts appears

7. Bug can be reproduced again after clear page cache (Cmd+Shift + R in Google Chrome) or after opening page in incognito tab

**Demo:** [Netlify](https://quizzical-curran-ed32a5.netlify.com/)

**Source code:** [Github](https://github.com/romach/gatsby-example)

### Expected result

Excerpts should be displayed

### Actual result

Excerpts in second and third blog posts dissappered

**Video**
![gatsby](https://user-images.githubusercontent.com/2506484/59515455-ccf8bc00-8ec7-11e9-9af6-ae190369331b.gif)

### Environment

`gatsby info --clipboard`

```
System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 8.16.0 - /usr/bin/node
    npm: 6.4.1 - /usr/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.5
  npmPackages:
    gatsby: ^2.9.4 => 2.9.4
    gatsby-image: ^2.1.4 => 2.1.4
    gatsby-plugin-feed: ^2.2.3 => 2.2.3
    gatsby-plugin-google-analytics: ^2.0.21 => 2.0.21
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.3 => 2.1.3
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.1.5 => 2.1.5
    gatsby-plugin-typography: ^2.2.13 => 2.2.13
    gatsby-remark-copy-linked-files: ^2.0.13 => 2.0.13
    gatsby-remark-images: ^3.0.16 => 3.0.16
    gatsby-remark-prismjs: ^3.2.11 => 3.2.11
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9
    gatsby-source-filesystem: ^2.0.39 => 2.0.39
    gatsby-transformer-remark: ^2.3.12 => 2.3.12
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.6.5
```

**Comment by Ronva** [comment]
I have reproduced this locally. 
```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.9.4 => 2.9.4 
    gatsby-image: ^2.1.4 => 2.1.4 
    gatsby-plugin-feed: ^2.2.3 => 2.2.3 
    gatsby-plugin-google-analytics: ^2.0.21 => 2.0.21 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.3 => 2.1.3 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.1.5 => 2.1.5 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
    gatsby-remark-copy-linked-files: ^2.0.13 => 2.0.13 
    gatsby-remark-images: ^3.0.16 => 3.0.16 
    gatsby-remark-prismjs: ^3.2.11 => 3.2.11 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.39 => 2.0.39 
    gatsby-transformer-remark: ^2.3.12 => 2.4.0 
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21 
```

**Comment by sidharthachatterjee** [comment]
I can reproduce this. Seems like a hydration issue at first glance. The built HTML seems to have the excerpt correctly and it is removed from the DOM on hydration 🤔 

(Disabling JavaScript will show you the excerpts)

**Comment by romach** [comment]
Issue is reproduced

**Comment by alisalahio** [comment]
Issue still exists

**Comment by alisalahio** [comment]
The excerpt is rendered in a `p` tag. So it's a `p` inside a `p`, which is what causes the issue I think.
It can be solved by rendering the excerpt inside `div` tag instead of a `p`

Replace
`<p dangerouslySetInnerHTML={{ __html: node.excerpt }} />`

With
`<div dangerouslySetInnerHTML={{ __html: node.excerpt }} />`
