### ISSUE TITLE
Print information of exceptions thrown in plugins

### ISSUE THREAD

**Issue by eyalroth** [gatsbyjs/gatsby#14790]
I'm writing my own local gatsby plugin, but since I'm new to node and javascript, I'm getting quite a lot of exceptions. The problem is that gatsby only prints "error" and doesn't print any further information about thrown exceptions, not even with `--verbose`. Well, at least it doesn't do so on `gatsby develop`.

There is obviously a simple workaround to this which is to wrap the code with `try`-`catch` and re-throw the exception, but it would be very helpful if gatsby did print the entire exception in the first place.

**Comment by sidharthachatterjee** [comment]
Sounds good to me. Would love to see a PR adding this! 💜

**Comment by ertrzyiks** [comment]
I would be happy to help with this issue.

@eyalroth is there any public repo when I could reproduce the issue? I tried it with my own project and got the error reported nicely:
<img width="772" alt="Screenshot 2019-06-18 at 21 44 22" src="https://user-images.githubusercontent.com/2437969/59714668-77e3df80-9212-11e9-9f46-176ec5d549ec.png">

**Comment by eyalroth** [comment]
@ertrzyiks I see now that it is a more specific case of `gatsby-transformer-remark`.

Clone the [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog) repository, create a new plugin with the following `index.js`:
```js
module.exports = ({ markdownAST }, pluginOptions) => {
    visit(markdownAST, "heading", node => {
        throw "i am an error, behold!"
      })
    return markdownAST
}
```

and add it to the `gatsby-transformer-remark` list of plugins in `gatsby-config.js`.

**Comment by ertrzyiks** [comment]
@eyalroth Thanks for providing extra information. I reproduced the issue following your steps and got:

```
error
The GraphQL query from /Users/mateuszderks/workspace/gatsby-starter-blog/src/templates/blog-post.js failed.

Errors:
  Unexpected error value: "i am an error, behold!"

 GraphQL request (13:5)
  12:     excerpt(pruneLength: 160)
  13:     html

```

The stacktrace is missing indeed.

**Comment by ertrzyiks** [comment]
function exported in remark plugin is called here: https://github.com/gatsbyjs/gatsby/blob/4f72687ce9b2c9edcf1358c9ece3a5aad3d003f3/packages/gatsby-transformer-remark/src/extend-node-type.js#L242

but it becomes an instance of GraphqlError and is presented to console in a special way:
https://github.com/graphql/graphql-js/blob/v14.3.1/src/error/printError.js#L18-L40

The stack trace is completely ignored, we only see the message and locations in the Graphql query. This information is irrelevant though because the problem is not with the query itself, but with the underlying code.

**Comment by ertrzyiks** [comment]
@sidharthachatterjee what do you think about adding stack trace to errors reported here: https://github.com/gatsbyjs/gatsby/blob/49fd769f695ccfa6e990e3eaae7c886f073db19b/packages/gatsby/src/query/query-runner.js#L51

Errors reported there contain only a query trace now.

We could get stack trace from the original errors which are not wrapped by [GraphQLError](https://github.com/graphql/graphql-js/blob/v14.3.1/src/error/GraphQLError.js)

or alternatively add another value like
```
errorDetails.set(`Original Errors`, (result.errors || []).map(error => error.originalError));
```
