### ISSUE TITLE
yarn start will throw error `TypeError: Cannot read property "minimizer" of undefined`

### ISSUE THREAD

**Issue by jcppman** [gatsbyjs/gatsby#14794]
## Description

with the latest `gatsby-plugin-netlify-cms` package (https://github.com/gatsbyjs/gatsby/releases/tag/gatsby-plugin-netlify-cms%404.0.2), `yarn start` will throw error `TypeError: Cannot read property "minimizer" of undefined`.

This is caused by https://github.com/gatsbyjs/gatsby/pull/14783. Because in dev mode `optimization` is indeed undefined.

### Steps to reproduce

- clone the starter https://github.com/netlify-templates/gatsby-starter-netlify-cms/
- `yarn`
- update `gatsby-plugin-netlify-cms` to 4.0.2
- `yarn start`

### Expected result

No error is thrown.

### Actual result

An error will be thrown. TypeError: Cannot read property "minimizer" of undefined

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 2.6.0 - /usr/local/bin/fish
  Binaries:
    Node: 8.11.2 - ~/.config/fnm/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.5.0 - ~/.config/fnm/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 64.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.1.34 => 2.9.4 
    gatsby-image: ^2.0.23 => 2.1.4 
    gatsby-plugin-netlify: ^2.0.6 => 2.0.17 
    gatsby-plugin-netlify-cms: ^4.0.0 => 4.0.2 
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.12 
    gatsby-plugin-sass: ^2.0.7 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.15 => 2.1.5 
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.0.13 
    gatsby-remark-images: ^3.0.1 => 3.0.16 
    gatsby-remark-relative-images: ^0.2.1 => 0.2.2 
    gatsby-source-filesystem: ^2.0.26 => 2.0.39 
    gatsby-transformer-remark: ^2.3.4 => 2.4.0 
    gatsby-transformer-sharp: ^2.1.9 => 2.1.21

**Comment by sidharthachatterjee** [comment]
Fixed and published in `gatsby-plugin-netlify-cms@4.0.3`
