### ISSUE TITLE
FEATURE: font loader

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#148]

**Comment by gesposito** [comment]
I used these, if it helps
https://github.com/gesposito/gatsby-starter-blog-bulma/blob/master/gatsby.config.js#L2

**Comment by KyleAMathews** [comment]
Those look great! I haven't used these loaders so if you want to create a
PR that'd be appreciated. Also a bit less code that you need to maintain ;-)

**Comment by KyleAMathews** [comment]
Also nice looking starter there :-)

**Comment by gesposito** [comment]
WIP :smile:
