### ISSUE TITLE
[gatsby-source-wordpress] Issue with WPCOM authentication

### ISSUE THREAD

**Issue by himynameistimli** [gatsbyjs/gatsby#14802]
## Description

Hi All,

I'm having a problem where I'm unable to get WPCOM (Wordpress.com) authentication to work properly. I've added the required fields for wpcom:
```javascript
        auth: {
          wpcom_app_clientSecret: xxxx,
          wpcom_app_clientId: xxxx,
          wpcom_user: xxx,
          wpcom_pass: xxx,
        },
```

But I still get errors when trying to pull media from the api:

```

The server response was "401 Unauthorized"
Inner exception message: "That API call requires authentication against the 

```

So I went digging thru the code to see where my issue is and I'm at the `getWPCOMAccessToken` function. https://github.com/gatsbyjs/gatsby/blob/e806c660dc5ba853a47b51b6fbec472f8c6df237/packages/gatsby-source-wordpress/src/fetch.js#L187 Copied here for reference:

```javascript
async function getWPCOMAccessToken(_auth) {
  let result
  const oauthUrl = `https://public-api.wordpress.com/oauth2/token`
  try {
    let options = {
      url: oauthUrl,
      method: `post`,
      data: querystring.stringify({
        client_secret: _auth.wpcom_app_clientSecret,
        client_id: _auth.wpcom_app_clientId,
        username: _auth.wpcom_user,
        password: _auth.wpcom_pass,
        grant_type: `password`,
      }),
    }
    result = await axios(options)
    result = result.data.access_token
  } catch (e) {
    httpExceptionHandler(e)
  }

  return result
}
```

When I copy the body / url into Postman, I get:

```
{
    "error": "unsupported_grant_type",
    "error_description": "Client cannot use \"password\" grant_type"
}
```
And when I modify `grant_type` to test other things:
```
{
    "error": "unsupported_grant_type",
    "error_description": "WordPress.com only supports the \"authorization_code\" grant_type"
}
```

I will continue to dig into this, but it seems like the `password` grant type is not longer accepted (if it was previously), or I am using the wrong method here. I will continue to test this issue out, but I'm just wondering if I'm the only one with this situation or if it's a mistake in my implementation. 

Here's my system info for reference.
```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.4.1 - /usr/local/bin/zsh
  Binaries:
    Node: 10.6.0 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 63.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.7.1 => 2.7.1 
    gatsby-image: 2.0.34 => 2.0.34 
    gatsby-plugin-canonical-urls: ^2.0.12 => 2.0.12 
    gatsby-plugin-catch-links: 2.0.13 => 2.0.13 
    gatsby-plugin-create-client-paths: ^2.0.5 => 2.0.5 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-feed: ^2.1.2 => 2.1.2 
    gatsby-plugin-google-analytics: 2.0.17 => 2.0.17 
    gatsby-plugin-manifest: 2.0.24 => 2.0.24 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-mixpanel: ^2.2.1 => 2.2.1 
    gatsby-plugin-nprogress: 2.0.10 => 2.0.10 
    gatsby-plugin-offline: 2.0.25 => 2.0.25 
    gatsby-plugin-postcss-sass: ^1.0.22 => 1.0.22 
    gatsby-plugin-react-helmet: 3.0.10 => 3.0.10 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-remove-trailing-slashes: ^2.0.10 => 2.0.10 
    gatsby-plugin-sass: 2.0.11 => 2.0.11 
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1 
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32 
    gatsby-plugin-sitemap: 2.0.10 => 2.0.10 
    gatsby-plugin-twitter: 2.0.13 => 2.0.13 
    gatsby-plugin-typography: 2.2.10 => 2.2.10 
    gatsby-remark-autolink-headers: ^2.0.12 => 2.0.16 
    gatsby-remark-copy-linked-files: ^2.0.8 => 2.0.11 
    gatsby-remark-images: ^3.0.1 => 3.0.10 
    gatsby-remark-prismjs: ^3.2.0 => 3.2.6 
    gatsby-remark-responsive-iframe: 2.1.1 => 2.1.1 
    gatsby-source-apiserver: ^2.1.1 => 2.1.1 
    gatsby-source-filesystem: 2.0.27 => 2.0.27 
    gatsby-source-wordpress: ^3.0.65 => 3.0.58 
    gatsby-transformer-json: 2.1.11 => 2.1.11 
    gatsby-transformer-remark: 2.3.8 => 2.3.8 
    gatsby-transformer-sharp: 2.1.17 => 2.1.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.16
    gatsby: 1.9.100
```

**Comment by himynameistimli** [comment]
Okay it seems it's my poor implementation.

In any case, I got it to work when I did the following:

1) Ensure that I used my own account. Prior, I had created a second admin account for the gatsby. I had given this user admin access to the developer application, but it didn't matter. I think the client_id/client_secret only works with the original user (?).

2) Add 2FA, and create an Application Password. This worked with my account but not with the second admin account I created. I never did the regular password because I did social sign-in, which is maybe why it was a bit messed up (And why I thought it would be better to create a specific second admin account).

**Comment by bosslee** [comment]
hi there may I check with you if you had to input redirect URL?
![image](https://user-images.githubusercontent.com/993948/71431898-5f4c0900-2710-11ea-9871-d94788933bb7.png)

if yes, is it the hostedsite/callback 
or did you leave it blank?

**Comment by louisrli** [comment]
+1 I think it only works with the original user. I tried to add an admin user for a colleague but it doesn't work.
