### ISSUE TITLE
Graphql query error

### ISSUE THREAD

**Issue by jamieholliday** [gatsbyjs/gatsby#1481]
I'm having an issue with a graphql query running in gatsby-starter-blog when trying to order the blog posts by date. This could be quite possibly an error on my part however. 

If I run this query in graphiql everything works as expected:

```
{
  allMarkdownRemark(sort:{fields: frontmatter___date, order: DESC}){
    edges{
      node{
        frontmatter{
          path,
          date,
          title
        }
      }
    }
  }
}
```
If however I run the same query in the app the error is this:

```
GraphQL request: Argument "sort" has invalid value {fields: "frontmatter___date", order: ASC}.
```

I'm struggling to see why there would be differences if its using the same schema

**Comment by KyleAMathews** [comment]
I'm not 100% sure either but the fields has to be an array so put your
field within []

I think graphiql is less strict than relay compiler so let's the diff pass.

**Comment by jamieholliday** [comment]
Oh what a rookie mistake! Having field within square brackets solves the issue.
Thanks for your help. 

Here is the working code incase anyone else has the same issue:

```
allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC }) {
      edges {
        node {
          frontmatter {
            path
            date
            title
          }
        }
      }
    }
```
