### ISSUE TITLE
Add babel-plugin-transform-react-remove-prop-types

### ISSUE THREAD

**Issue by neo** [gatsbyjs/gatsby#14814]
## Summary

I am not 100% sure, but it seems like `babel-plugin-transform-react-remove-prop-types` isn't being used when gatsby is building for production.

In my opinion, this is a very useful and practical thing to add.

### Basic example

N/A

### Motivation

To achieve smaller production build bundle.

**Comment by sidharthachatterjee** [comment]
Sounds useful but I'm not _entirely_ sure if we should add it in our default config (which is super lightweight by design). 

Let's keep this open and hear what everyone else has to say. 

In the mean time, you could add this in a [custom .babelrc file](https://www.gatsbyjs.org/docs/babel/)

**Comment by sidharthachatterjee** [comment]
Just spoke with @DSchau about this and we both agree that this is useful indeed! 

We would love to accept a PR with this. 💪

**Comment by luisFilipePT** [comment]
Hi,
Can I try to tackle this one?

Cheers

**Comment by sidharthachatterjee** [comment]
@luisFilipePT Sure! Thank you for picking it up 🙌

**Comment by wardpeet** [comment]
@luisFilipePT You should be able to add it to [babel-preset-gatsby/src/index.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby/src/index.js)

**Comment by luisFilipePT** [comment]
@wardpeet thanks for the tip 👍 

I started to check it out last night, just not sure yet you to test it, this is what I have tried (so far)

1 - Added the npm package in `packages/babel-preset-react`
2 - Added the config to `.babelrc` in the same folder (so maybe this will go in `index.js` 🤔 )
3 - Built everything
4 - Build the default project in `starters`
5 - Go to `public` and search for `propTypes` in that folder
6 - Compare with the original build (before the change)

Am I on the right path? 😄

PS - The goal here, for now, is just to remove propTypes on Gatsby prod but not on the plugins, right?

Thanks guys

**Comment by luisFilipePT** [comment]
kind of struggling here, this are my current changes:

I'm missing something 😕 

![image](https://user-images.githubusercontent.com/9373787/59847400-47a75880-935a-11e9-854e-d7f87e4a06c6.png)

**Comment by 0tho** [comment]
@luisFilipePT how is this going? I might be able to help you out

**Comment by luisFilipePT** [comment]
> @luisFilipePT how is this going? I might be able to help you out

I think it's done. You can check the PR and see if theres anything that could be improved.
But for now I am just waiting for feedback or for the PR to be merged 😄

**Comment by pieh** [comment]
Plan is to merge this today (we are doing bunch of babel preset related changes)
