### ISSUE TITLE
how can I achieve a trimmed version of the gatsby

### ISSUE THREAD

**Issue by jackyq2015** [gatsbyjs/gatsby#14826]
Need some help to setup a simple web site to allow users to publish 1 page of company information such as website, description, etc. It is like a yellow page but self published by users.
 
Gatsby is powerful but I am wondering is there way that I can provide the user a template that user can fill in without overwhelming the end user? If Gatsby is overkill, is there any recommendation to archive this? Thanks

**Comment by DSchau** [comment]
@jackyq2015 could you explain what exactly you want "trimmed?" Gatsby's runtime is around ~50Kb gzipped, and most of that is React and ReactDOM. Can't get a whole heck of a lot smaller!

More detail would be great--thanks!

**Comment by jackyq2015** [comment]
@DSchau I mean from the function aspect, not the size. Basically, the use case is:
 

- Each user will only have one page based on a template. He will fill in and update by himself. 
- It should be able to plug into existing web site written in React

Thanks!

**Comment by Ronva** [comment]
It sounds like you want to create a form(s) using serverless functions. Here's a good starting point: https://github.com/snipcart/gatsby-netlify-serverless

Once your user submits the form you can call whatever webhook/endpoint/etc. You need to notify your main website. Good luck 😄
