### ISSUE TITLE
Cannot install gatsby on windows

### ISSUE THREAD

**Issue by besrabasant** [gatsbyjs/gatsby#1482]
I get this error when i run `npm install -g gatsby`
```
npm ERR! Unexpected end of input at 1:104456
npm ERR! 4.16"},"directories":{},"dist":{"shasum":"3c9350470ca8a27fdebe1a38aaa
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PROGRAMMER'S EDGE\AppData\Roaming\npm-cache\_logs\2017-07-12T19_24_43_705Z-debug.log
```

**Comment by KyleAMathews** [comment]
It's just a random npm error. We see similar errors all the time building the example sites. Try again?

**Comment by besrabasant** [comment]
Okay

**Comment by sebastienfi** [comment]
Here you will find the how-to get it to build on Windows. https://www.gatsbyjs.org/docs/gatsby-on-windows/

**Comment by besrabasant** [comment]
@KyleAMathews Still no luck

**Comment by besrabasant** [comment]
@KyleAMathews @sebastienfi Solved the issue... after updating `npm` to the latest version.

**Comment by KyleAMathews** [comment]
Oh weird... which version where you on in case other people are running into the same issue?

**Comment by besrabasant** [comment]
I updated from npm  `5.0.2` to the latest npm `5.2.0`. @KyleAMathews

**Comment by KyleAMathews** [comment]
Ok good to know. Yeah I've heard other reports that < 5.1 or so is broken
