### ISSUE TITLE
gatsby-plugin-offline does not update website after new deploy on Safari or Safari installed pwa

### ISSUE THREAD

**Issue by MassivDash** [gatsbyjs/gatsby#14821]
## Description
Gatsby website using gatsby-offline-plugin does not update website after new deploy, on iOS Safari Mobile. Chrome on same iOS phone does updates the site. 

Cleaning browser history for safari, makes safari and pwa installed though safari update.

It looks like its only related to safari and how it handles pwa. Is there somekind of special setting to include to avoid this behavior. 

### Steps to reproduce

install gatsby-offiline-plugin

### Expected result

Website should upadte

### Actual result

Website does not update

### Environment

iphone 6 
iOS: 12.3.1

**Comment by sidharthachatterjee** [comment]
@MassivDash The closest issue I can relate this to is https://github.com/GoogleChrome/workbox/issues/1744

> Although that bug is marked as Fixed, there are a number of folks who have reported that the issue persists.
> 
> As you say, it's tied to Safari's implementation, and I'm not sure that there's much Workbox can do to remediate the issue—I've been keeping these bugs here open for visibility, at least.

Closing this for the moment because this looks like an issue on iOS Safari but following along the conversation on the linked issue might be valuable!
