### ISSUE TITLE
Gatsby Build not completing

### ISSUE THREAD

**Issue by danielmonk** [gatsbyjs/gatsby#14833]
## Description

Running gatsby build gives the following error:

error Building static HTML failed

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

  67 |          __webpack_require__.n = function(module) {
  68 |                  var getter = module && module.__esModule ?
> 69 |                          function getDefault() { return module['default']; } :
     | ^
  70 |                          function getModuleExports() { return module; };
  71 |                  __webpack_require__.d(getter, 'a', getter);
  72 |                  return getter;

  WebpackError: /Users/danielmonk/Sites/danielmonk-react/danielmonk/public/render-page.js:4877
  
  - bootstrap:69 new Script
    lib/webpack/bootstrap:69:1
  
  
  - static-entry.js:75 Object.Module._extensions..js
    lib/.cache/static-entry.js:75:5
  
  
  - gatsby-browser-entry.js:70 tryModuleLoad
    lib/.cache/gatsby-browser-entry.js:70:10
  
  - gatsby-browser-entry.js:58 Function.Module._load
    lib/.cache/gatsby-browser-entry.js:58:5
  
  - static-entry.js:6 Module.require
    lib/.cache/static-entry.js:6:51
  
  - bootstrap:11 require
    lib/webpack/bootstrap:11:1
  
  - bootstrap:21 Promise
    lib/webpack/bootstrap:21:1
  
  
  - gatsby-browser-entry.js:1 Promise._resolveFromExecutor
    lib/.cache/gatsby-browser-entry.js:1:1
  
  - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1
  
  
  - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1

have followed others recommendations to use yarn instead of npm but still no use.

### Steps to reproduce

Simply running gatsby build within project folder. Gatsby develop works fine.

### Expected result

Gatsby should build correctly.

### Actual result

Following error message:

error Building static HTML failed

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

  67 |          __webpack_require__.n = function(module) {
  68 |                  var getter = module && module.__esModule ?
> 69 |                          function getDefault() { return module['default']; } :
     | ^
  70 |                          function getModuleExports() { return module; };
  71 |                  __webpack_require__.d(getter, 'a', getter);
  72 |                  return getter;

  WebpackError: /Users/danielmonk/Sites/danielmonk-react/danielmonk/public/render-page.js:4877
  
  - bootstrap:69 new Script
    lib/webpack/bootstrap:69:1
  
  
  
  
  - static-entry.js:75 Object.Module._extensions..js
    lib/.cache/static-entry.js:75:5
  
  
  - gatsby-browser-entry.js:70 tryModuleLoad
    lib/.cache/gatsby-browser-entry.js:70:10
  
  - gatsby-browser-entry.js:58 Function.Module._load
    lib/.cache/gatsby-browser-entry.js:58:5
  
  - static-entry.js:6 Module.require
    lib/.cache/static-entry.js:6:51
  
  - bootstrap:11 require
    lib/webpack/bootstrap:11:1
  
  - bootstrap:21 Promise
    lib/webpack/bootstrap:21:1
  
  
  - gatsby-browser-entry.js:1 Promise._resolveFromExecutor
    lib/.cache/gatsby-browser-entry.js:1:1
  
  - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1
  
  
  - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
  npmPackages:
    gatsby: ^2.5.2 => 2.9.4 
    gatsby-image: ^2.1.0 => 2.1.4 
    gatsby-plugin-ffmpeg: ^0.3.0 => 0.3.0 
    gatsby-plugin-google-analytics: ^2.0.20 => 2.0.21 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.0 => 2.1.3 
    gatsby-plugin-page-load-delay: ^0.1.2 => 0.1.2 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.37 => 2.1.5 
    gatsby-remark-videos: ^0.3.0 => 0.3.0 
    gatsby-sharp: ^1.0.0-alpha11-alpha.00fcfe90 => 1.0.0-alpha11-alpha.00fcfe90 
    gatsby-source-filesystem: ^2.0.36 => 2.0.39 
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21 
  npmGlobalPackages:
    gatsby-cli: 2.5.14

**Comment by danielmonk** [comment]
Here is the github link for the project: https://github.com/danielmonk/danielmonk

**Comment by sidharthachatterjee** [comment]
Looks like the import to `react-youtube` is causing SSR to fail? Removing the import seems to fix the build. 

Not sure what the error is exactly pointing to yet since `react-youtube` seems to handle SSR correctly (does everything after component mounts)

**Comment by sidharthachatterjee** [comment]
@wardpeet just pointed out that this could be a CommonJS interoperability issue

**Comment by wardpeet** [comment]
It seems like a `youtube-player` (a dependency of `react-youtube`) is using `debug` npm package which doesn't play well with webpack.

You can fix it by replacing onCreateWebpackConfig in gatsby-node.
```js
exports.onCreateWebpackConfig = ({
  actions,
  stage
}) => {
  const { setWebpackConfig } = actions;

  if (stage === 'build-html') {
    setWebpackConfig({
      resolve: {
        alias: {
          'debug': require.resolve('debug').replace('index.js', 'browser.js'),
        }
      }
    })
  }

  setWebpackConfig({
    externals: {
      jquery: 'jQuery', // important: 'Q' capitalized
    }
  })
} 
```
