### ISSUE TITLE
[gatsby-remark-images] Add feature for medium-zoom feature

### ISSUE THREAD

**Issue by JaeYeopHan** [gatsbyjs/gatsby#14831]
> Hi, 🙋🏻‍♂️ I'm Front-End engineer in Korea!

## Summary

Add feature for zoom image like 'medium zoom'.

ref: https://github.com/francoischalifour/medium-zoom

### Basic example

```js
plugins: [
  {
    resolve: `gatsby-remark-images`,
    options: {
      // other options
      useMediumZoom: {
        margin: 24,
        background: 24,
        scrollOffset: 0,
      }, // If this option is empty, not apply medium zoom feature.
    },
  },
]
```

### Motivation

When user click image to enlarge the image and see more detail, opening it with a new tab causes the user to be extremely inconvenient. If the image is larged on in the window user was viewing and user can easily close it with scrolling or toggling, the user experience is expected to be very high.

#### Why not use an [existing plugin](https://github.com/premieroctet/gatsby-remark-images-zoom)?

[This code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/gatsby-browser.js#L21
) is blocking `transition` of medium-zoom library. So medium-zoom library is not working. I think it would be better to support this feature in this library.

#### Expected

![medium-zoom-gif](https://user-images.githubusercontent.com/17924127/59593535-15fd7a00-912d-11e9-9def-630febbea456.gif)

#### Plan

like this in `gatsby-browser.js`:

```js
// in `onRouteUpdate` function

// something...
function onImageLoad() {
  // something...
  imageElement.style.transition =
    'opacity 0.5s, transform .3s cubic-bezier(.2,0,.2,1)'
  // something...
}
// something...
const { mediumZoomOptions } = pluginOptions

if (mediumZoomOptions) {
  const defaultOptions = {
    margin: 36,
    background: "#fff",
    scrollOffset: 0,
  }

  let options

  if (typeof mediumZoomOptions === "object") {
    options = { ...defaultOptions, ...mediumZoomOptions }
  } else {
    options = defaultOptions
  }

  mediumZoom(`.gatsby-resp-image-image`, options)
}
```

> If you like this issue, I will enroll pull request soon! Thanks. :)

**Comment by SoYoung210** [comment]
I think It's good issue. It would be nice if you implemented it and PR.

**Comment by sidharthachatterjee** [comment]
I think this ought to be a separate plugin as opposed to being added to `gatsby-remark-images`

Maybe `gatsby-remark-images-zoom` 🙂 

Closing this issue but would love to see this as a plugin published by you! Thank you for the great work 💪 💜
