### ISSUE TITLE
gatsby-plugin-catch-links - allow opt-outs

### ISSUE THREAD

**Issue by gethinw** [gatsbyjs/gatsby#14835]
## Summary

It would be great to have some options to configure this plugin, to ignore certain paths. In my case, anything under /examples/ is served as separate static files outside of Gatsby, so I would like to only convert links that don't start /examples/

### Basic example

```
{
      resolve: 'gatsby-plugin-catch-links',
      options: {
        excludePattern: /^\/examples\//
      }
}
```
### Motivation

To support sites with different types of routing setups than a very basic one. Although https://github.com/gatsbyjs/gatsby/issues/11238 was resolved in a different way, this could also have solved that.

**Comment by sidharthachatterjee** [comment]
This sounds pretty useful! We’d love to accept a PR adding support for this 🙌🏼

**Comment by fboechats** [comment]
Can I work on this feature??

**Comment by sidharthachatterjee** [comment]
@fboechats Sure! Thank you for picking it up 🙌

**Comment by i-bsd** [comment]
What about using multiple exclude patterns?

This seems to only allow one single exclude regex.

**Comment by AnansiOmega** [comment]
Hey, first time working on open source is this feature still being worked on? If not I'd love take this on, with hopefully some guidance?

**Comment by himanshu211raj** [comment]
I wanted to work on this issue but as i am a beginner so i need guidance regarding how i start contributing to open source?
