### ISSUE TITLE
[docs] h6 headers are very hard to read

### ISSUE THREAD

**Issue by dimitrisnl** [gatsbyjs/gatsby#14836]
## Description

The `h6` headers in the [website](https://www.gatsbyjs.org/docs/ssr-apis/) are `9px`. The `code` tags insde them are `6.70251px`

## File history

https://github.com/gatsbyjs/gatsby/blame/e806c660dc5ba853a47b51b6fbec472f8c6df237/www/src/utils/typography.js#L47

## Screens

<img width="644" alt="Screenshot 2019-06-18 at 00 12 39" src="https://user-images.githubusercontent.com/4951004/59637183-df8c2300-915d-11e9-902a-5e944f53d244.png">

**Comment by sidharthachatterjee** [comment]
cc @fk

**Comment by fk** [comment]
👍 That shouldn't be; thank you @dimitrisnl! 🙏 
Will PR later today!
