### ISSUE TITLE
chore: Move console overrides to reporter.log

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#14834]
We currently override `console.log`, `console.warn`, `console.info` and `console.error` in https://github.com/gatsbyjs/gatsby/blob/e034605e1c3ea47882dbf670c2eb1fb3ce3572fa/packages/gatsby-cli/src/reporter/index.js#L109

<details>
<summary>This can get a little messy sometimes</summary>

![Screenshot 2019-06-17 18 30 07](https://user-images.githubusercontent.com/7701981/59606692-6a095e00-912f-11e9-89e3-f0966f1e0982.png)

In this case, the log from `update-notifier` shows up as an error. `update-notifier` correctly calls console.error (because they want to log to stderr) but this isn't really an error for us and shouldn't show up as one (and potentially confuse some users)

https://github.com/yeoman/update-notifier/commit/c3b1df66fee922cae1af7c3ca898240c2df35884#diff-168726dbe96b3ce427e7fedce31bb0bc

</details>

We want to move our console overrides to reporter.log. Console messages will still show pretty in ink but won't have a prefix (success, error, warn, info). We want to move towards a future where all gatsby stuff uses the reported directly.

**Comment by sidharthachatterjee** [comment]
This is currently blocked till all usage of `console` is removed from gatsby and (official) plugins

**Comment by wardpeet** [comment]
I removed the comment about this being blocked. I updated the issue so it's not blocking anymore.

**Comment by wardpeet** [comment]
I'm going to use this one in my pairing session with someone. Sorry, it's taken ^^

**Comment by sidharthachatterjee** [comment]
This is back for the taking since the pairing session was a no show 😱

**Comment by leonlafa** [comment]
I'm happy to go through and refactor if it's still up for grabs?

**Comment by wardpeet** [comment]
yes! All yours!

**Comment by leonlafa** [comment]
Just to clarify, you want all of the console logs throughout the application to be refactored as ...reporter.log(util.format(...args))?

**Comment by sidharthachatterjee** [comment]
@leonlafa 

> Just to clarify, you want all of the console logs in the file above to be refactored as ...reporter.log(util.format(...args))?

Yeah, all of them (console.log, console.warn, console.info and console.error) should call reporter.log(util.format(...args))

**Comment by leonlafa** [comment]
@sidharthachatterjee thanks, I'll start work on this tonight.

**Comment by leonlafa** [comment]
Anyone about to quickly review my PR? @wardpeet @sidharthachatterjee

**Comment by kushthedude** [comment]
@sidharthachatterjee Can I work on this, I see there are still `console.log` present in directory?

**Comment by sidharthachatterjee** [comment]
This was done in https://github.com/gatsbyjs/gatsby/pull/14956 by @leonlafa

**Comment by kushthedude** [comment]
@sidharthachatterjee is there something remaining in the issue?
