### ISSUE TITLE
How to debug the use of GuessJS?

### ISSUE THREAD

**Issue by PolGuixe** [gatsbyjs/gatsby#14841]
## Summary
Setting up the plugin is easy and great! 

How can it be debugged and check that is doing something?

**Comment by wardpeet** [comment]
Sorry for keeping you waiting. What I usually do is write the following in console and see if I get something back.
```js
__GUESS__.guess()
```

I can't show you a demo right now on gatbyjs.org as we have disabled it to fix a bug. I'll come back with a small gif when we fixed the bug.

**Comment by wardpeet** [comment]
When using `gatsby-plugin-guess-js` you should see prefetches that are related to a page.

for example when you're on gatsbyjs.org and type `__GUESS__.guess()` it returns paths to prefetch. You should see prefetches for this route inside the DOM when checking it with devtools.

![image](https://user-images.githubusercontent.com/1120926/62132466-6ac01300-b2dd-11e9-92f8-dc4046904f9e.png)

On gatsbyjs.org, guess is telling us to prefetch /docs/ so we load the docs page javascript and all assets.

Please install gatsby@2.13.44 & gatsby-plugin-guess-js@1.1.4 to make guess work again.

I'm marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by PolGuixe** [comment]
@wardpeet many thanks for the help! ;)
