### ISSUE TITLE
Reverse querying a list of the usage (or non-usage) of image nodes

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/gatsby#14844]
I have a feeling there isn't a way to do this but hopefully there is!
I have a project with a ton of images and I'm sure 50% of those images aren't being used but I don't know which images those are. 
Is there a way to find image nodes that aren't being linked to by other nodes?
It would be cool to be able to use GraphQL to query for a list of those unused images.

**Comment by sidharthachatterjee** [comment]
> Is there a way to find image nodes that aren't being linked to by other nodes?

Not currently 😞

**Comment by TylerBarnes** [comment]
No worries, I can write a script to find them. Thanks for the response!
