### ISSUE TITLE
If there are so many posts in Wordpress so how to fetch only new added post on every build time?

### ISSUE THREAD

**Issue by hirenramoliya** [gatsbyjs/gatsby#14861]
Hello, I am using Gatsby with WordPress so, on every build time gatsby fetching all posts from the Wordpress JSON API then how can I fetch only recently added posts from API.

**Comment by sidharthachatterjee** [comment]
Unfortunately, this isn’t possible currently because Wordpress doesn’t give us a diff of what’s changed. We are actively looking at ways to improve this though!

**Comment by hirenramoliya** [comment]
@sidharthachatterjee Thanks for the reply.
