### ISSUE TITLE
Bug for gatsby-starter-blog

### ISSUE THREAD

**Issue by ZolderonGitHub** [gatsbyjs/gatsby#14878]
I have a bug when i run gatsby develop  [in the gatsby-blog-project](https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-blog/)
>GraphQL Error There was an error while compiling your site's GraphQL queries.
  Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
>- cUsersGuimo000DesktopDevReactZolderBlogSrcPages404Js1097489062
>- BlogPostBySlug
>- cUsersGuimo000DesktopDevReactZolderBlogSrcPagesIndexJs2785444898

I don't make any change, and i think that come from query.
I run on windows 10.

**Comment by freiksenet** [comment]
Hi @ZolderonGitHub !

Sorry to hear you're running into an issue. I've tried to reproduce it, but I can't. Could you send all the steps you take before running `gatsby develop` (so how you started the project, what did you install with). In addition, please include result of `gatsby info` in the project.

**Comment by ZolderonGitHub** [comment]
@freiksenet i just install the project on my computer with git and i try to use it with gatsby develop

**Comment by wardpeet** [comment]
Can you tell us the exact steps you did to clone this repo?
We advise doing `gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-blog`
