### ISSUE TITLE
Local plugin behaves differently then direct configuration (SSR)

### ISSUE THREAD

**Issue by bengry** [gatsbyjs/gatsby#14879]
## Description
Code written as a local plugin behaves differently then if it were written directly in `gatsby-ssr.js`/`gatsby-browser.js`.

I started with [this example](https://github.com/mui-org/material-ui/tree/master/examples/gatsby) from the Material-UI repo, after seeing that their `<CssBaseline />` ([docs](https://github.com/mui-org/material-ui/blob/89687f38cae750650555772ba4d821c9084d8dfc/pages/api/css-baseline.md), [code](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/CssBaseline/CssBaseline.js)) behaves differently in our app then in that example.

I reduced the issue down to [a minimal reproduction](https://github.com/bengry/gatsby-mui-local-plugin-repro), based on the above repo. There are 3 commits there, the last (`77251e6`) of which causes a FOUC, while the previous commit (`5022cb6`) works fine.
The only difference between them is that the local plugin was removed in favor of having it as part of the app's `gatsby-ssr.js` and `gatsby-browser.js`.

Describe the issue that you're seeing.

### Steps to reproduce
1. `git clone https://github.com/bengry/gatsby-mui-local-plugin-repro`
2. `yarn install`
3. `yarn build`
4. `npx http-server ./public` (or any other simple HTTP server that serves `./public`)

You should see a FOUC. Going back to the previous commit should **not** have it (`git checkout 5022cb6`).

### Expected result
Local code written in the app's `gatsby-ssr.js` and `gatsby-browser.js` (as well as `gatsby-node.js`) should behave the same as the one written in local plugins.

### Actual result

They don't behave the same

### Environment
  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.3 - /var/folders/5n/8fcbq7cn2mb0m8nn2jpd3zyh0000gn/T/yarn--1560881617782-0.8801172608473162/node
    Yarn: 1.16.0 - /var/folders/5n/8fcbq7cn2mb0m8nn2jpd3zyh0000gn/T/yarn--1560881617782-0.8801172608473162/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    gatsby: latest => 2.9.6 
    gatsby-plugin-material-ui: latest => 2.0.1 
    gatsby-plugin-react-helmet: latest => 3.0.12 

I'll also add that `@material-ui/core` and `@material-ui/styles` are both at version `4.1.1`. Any further dependencies can be seen in the `yarn.lock` file in the repo linked above.

**Comment by freiksenet** [comment]
Thank you for the great reproduction! We'll take a look at it.

**Comment by bengry** [comment]
@freiksenet @sidharthachatterjee should the bot close this issue as stale, or is fixing this in the backlog?

**Comment by freiksenet** [comment]
@bengry Certainly not stale. CC @sidharthachatterjee

**Comment by LekoArts** [comment]
Closing as stale. If you still see this behavior in the latest Gatsby v3 please open a new issue.
