### ISSUE TITLE
[docs][recipes] Styling: Using Emotion

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14895]
## Summary

To improve key learning workflows in the Recipes section of the docs, the "Styling" recipe should be broken up into smaller, more actionable parts. This issue is about the fourth item, **Using Emotion**, coming after the Styled Components recipe requested in https://github.com/gatsbyjs/gatsby/issues/14894. 

The current recipe has this text (it will be replaced by Styling recipes inline): 

> There are so many ways to add styles to your website; Gatsby supports almost every possible option, through official and community plugins.
> - Walk through adding global styles to an example site in tutorial part two
>    - More on global styles with standard CSS files
>    - More on global styles with CSS-in-JS
>    - More on global styles with CSS files and no layout component
> - Use the CSS-in-JS library Glamor
> - Use the CSS-in-JS library Styled Components
> - Use CSS Modules

Note: Glamor is no longer being actively maintained and [we don't recommend using it](https://www.gatsbyjs.org/docs/glamor/) anymore.

The actionable version of this Emotion recipe should show how to work with it _inline_ as concisely as possible. It should explain how to install Emotion and show how to use it; we could consider listing installation as a prerequisite to keep the example short, but we can play around with it. The [Emotion docs page](https://www.gatsbyjs.org/docs/emotion/) can be used as a reference.

Recipes now follow this format:

- Requirements or prerequisites 
- Step-by-step instructions
- Relevant links to any relevant information
    - More on using Emotion https://www.gatsbyjs.org/docs/emotion/
    - Link to a live example (@jlengstorf is there an Egghead video like for Styled Components?)

This recipe will go into the "Styling" section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md), replacing the existing text. There is a template in the contributing docs: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by jlengstorf** [comment]
@ChristopherBiscardi has a playlist on using Emotion with Gatsby! https://egghead.io/playlists/using-emotion-with-gatsby-c167ea3d

**Comment by marcysutton** [comment]
Nice! thanks, @jlengstorf !
