### ISSUE TITLE
[docs][recipes] Styling: Using Styled Components

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14894]
## Summary

To improve key learning workflows in the Recipes section of the docs, the "Styling" recipe should be broken up into smaller, more actionable parts. This issue is about the third item, **Using Styled Components**, coming after the standard CSS file recipes requested in https://github.com/gatsbyjs/gatsby/issues/14892 and https://github.com/gatsbyjs/gatsby/issues/14893. 

The current recipe has this text (it will be replaced by Styling recipes inline): 

> There are so many ways to add styles to your website; Gatsby supports almost every possible option, through official and community plugins.
> - Walk through adding global styles to an example site in tutorial part two
>    - More on global styles with standard CSS files
>    - More on global styles with CSS-in-JS
>    - More on global styles with CSS files and no layout component
> - Use the CSS-in-JS library Glamor
> - Use the CSS-in-JS library Styled Components
> - Use CSS Modules

Note: Glamor is no longer being actively maintained and [we don't recommend using it](https://www.gatsbyjs.org/docs/glamor/) anymore.

The actionable version of this Styled Components recipe should show how to work with it _inline_ as concisely as possible. It should explain how to install Styled Components and show how to use it; we could consider listing installation as a prerequisite to keep the example short, but we can play around with it.

Recipes now follow this format:

- Requirements or prerequisites 
- Step-by-step instructions
- Relevant links to any relevant information
    - More on using Styled Components https://www.gatsbyjs.org/docs/styled-components/
    - Link to the Egghead lesson: https://egghead.io/lessons/gatsby-style-gatsby-sites-with-styled-components

This recipe should go into the "Styling"  section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md), replacing the existing text. There is a template in the contributing docs: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by harshil1712** [comment]
I would like to work on this

**Comment by marcysutton** [comment]
Sounds good @harshil1712! The change will go in `docs/docs/recipes.md`. There is already a heading for Styling, so this recipe would go into that section.

**Comment by harshil1712** [comment]
Okay thank you! I will send a PR in a few days

**Comment by harshil1712** [comment]
Hey, so this will go under Styling section, with the recipe name, there's no need to make a separate file. I hope I understood right

**Comment by marcysutton** [comment]
@harshil1712 that is correct! These styling recipes will replace the existing text.

**Comment by harshil1712** [comment]
Okay! PR coming your way

**Comment by amberleyromo** [comment]
Closed in #15093
