### ISSUE TITLE
[docs][recipes] Styling: Using CSS modules

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14896]
## Summary

To improve key learning workflows in the Recipes section of the docs, the "Styling" recipe should be broken up into smaller, more actionable parts. This issue is about the item **Using CSS modules**, coming after the Emotion recipe requested in https://github.com/gatsbyjs/gatsby/issues/14895. 

The current recipe has this text (it will be replaced by Styling recipes inline): 

> There are so many ways to add styles to your website; Gatsby supports almost every possible option, through official and community plugins.
> - Walk through adding global styles to an example site in tutorial part two
>    - More on global styles with standard CSS files
>    - More on global styles with CSS-in-JS
>    - More on global styles with CSS files and no layout component
> - Use the CSS-in-JS library Glamor
> - Use the CSS-in-JS library Styled Components
> - Use CSS Modules

The actionable version of this CSS module recipe should show how to work with them _inline_ as concisely as possible. It should include code examples showing what makes a CSS module and how to import one in a component. The CSS modules docs page can be used as a reference: https://www.gatsbyjs.org/docs/css-modules/

Recipes now follow this format:

- Requirements or prerequisites 
- Step-by-step instructions
- Relevant links to any relevant information
    - More on using CSS Modules https://www.gatsbyjs.org/docs/css-modules/
    - Link to a live example 

This recipe should go into the "Styling" section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md), replacing the existing text. There is a template in the contributing docs: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by mehtavishwa30** [comment]
Hey @marcysutton! Does this still need help? I'd love to work on it. Lemme know!

**Comment by marcysutton** [comment]
@mehtavishwa30 yes, absolutely! We'd love to have help!

**Comment by mehtavishwa30** [comment]
Hey @marcysutton!
Sorry for the delay. Have opened a PR for the Recipe requested in the issue. Please have a look!
:)
