### ISSUE TITLE
pathPrefix not working after building and serving Gatsby site

### ISSUE THREAD

**Issue by jfarris587** [gatsbyjs/gatsby#14898]
## Description

**Problem when using `pathPrefix` option in `gatsby-config` when serving the build.**

The goal is to have a gatsby app, that builds, and the build is then served from an (express) app. You would have the main express app serving a static page, called `page-2` (the gatsby page) at `www.myapp.com/banana/page-2`.

Due to `banana` there is a `pathPrefix` of "/banana" added to the config. The build then uses `gatsby build --prefix-paths` to utilize this.

### Steps to reproduce

Demo Repo: https://github.com/jfarris587/gatsby-demo

**A):**

- Clone the repo
- run `yarn build` and then `yarn serve`
- Go to `localhost:9000`
- Attempt to navigate
- Attempt to go to `localhost:9000/page-2`
- Try and click the text to trigger alert

**B):**

- Change build script to normal `yarn gatsby build`
- Remove pathPrefix from gatsby-config file
- Repeat steps above

### Expected result

I should be able to go to the home page, navigate to the other page and click the text to see the javascript working.

### Actual result

Trying (A): You will notice that going to the home page works, but clicking the link takes you to unknown page. However, if you go to `/page-2` directory with no "banana" prefix, then it takes you to the page.... But the javascript doesn't work. When clicking the `h3` an onClick fires to alert you...

Trying (B): You will get the expected behavior, but it doesn't utilize a prefix, which is needed for serving `page-2` from an express app

Notice that yarn Dev in Chrome does work. (IE seems to have seperate polyfill issue in development mode). However, serving the build gives above problems

**Comment by wardpeet** [comment]
Jawza, you're running old gatsby dependencies
![image](https://user-images.githubusercontent.com/1120926/59770819-eecbb780-92a8-11e9-98fa-5c3f9d32dc6e.png)

You probably want to consider `yarn upgrade` or `npm update` depending on which package manager you like. Doing 2 builds and gatsby serve wouldn't work as `path-prefix` doesn't create any folders for you in public. The idea is that you deploy public to the correct directory on the server. To mimic this behaviour you can try the following.

**A):**

- Clone the repo
- run `yarn build`
- move public to a temporary folder `banana` (`mv public/ banana/`)

**B):**

- Change build script to normal `yarn gatsby build`
- Remove pathPrefix from gatsby-config file
- run `yarn build`
- move your temporary folder into public under the banana namespace (`mv banana/ public/banana/`
- run `yarn serve`
- Go to `localhost:9000`
- Attempt to navigate
- Try and click the text to trigger alert

**Comment by spam-n-eggs** [comment]
Also expericing this issue hosting on GitHub static pages.

**Comment by spam-n-eggs** [comment]
I tested this again with my reproduction site, and it appears to now be working.  I will slowly start adding components until this issue is again reproducible.

**Comment by wardpeet** [comment]
Thank you for opening this, @jfarris587 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by yugandhar-pathi** [comment]
If anyone coming here like me ..after building your application with `--prefix-paths` serve your site also with `--prefix-paths` !
Modify your scripts in package.json as 
`   "serve": "gatsby serve --prefix-paths -o", `

**Comment by ramrock93** [comment]
> If anyone coming here like me ..after building your application with `--prefix-paths` serve your site also with `--prefix-paths` !
> Modify your scripts in package.json as
> ` "serve": "gatsby serve --prefix-paths -o",`

Thanks man! Solved my problem. It's not specified in the [docs](https://www.gatsbyjs.org/docs/path-prefix/)

**Comment by daxiongFED** [comment]
I fixed this wrong.It happen because of gatsby-plugin-osano，turn if off and fixed.

**Comment by joewang704** [comment]
> If anyone coming here like me ..after building your application with `--prefix-paths` serve your site also with `--prefix-paths` ! Modify your scripts in package.json as ` "serve": "gatsby serve --prefix-paths -o",`

This shouldn't be a necessity to use a prefix path, especially if it's just appending a string onto links. I'm using gatsby w/ github pages and this makes default GH page sites unusable.

**Comment by daxiongFED** [comment]
我已经收到你的来信，会尽快处理，辛苦了！                                                             曾志雄
