### ISSUE TITLE
[docs][workflows] Centralizing MDX docs on Gatsbyjs.org

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#14890]
Part of the Top 25 Learning Workflows initiative. See #13708 for the meta issue that this issue falls under.

## Description:

In an effort to centralize docs for MDX under the Gatsbyjs.org docs, all guides should be moved from [the gatsby-mdx docs](https://gatsby-mdx.netlify.com/) to .org. We should add `createRedirects` on the gatsby-mdx page as well to point users to Gatsby's docs where documentation will continue for what is now `gatsby-plugin-mdx`.

~The name of the reference guides on MDX has been a question, should "Adding Components to Content with MDX" be changed to something that instead mentions adding JavaScript?~

- [x] add new page in Gatsby API section of the docs sidebar for MDX
- [x] move docs from gatsby-mdx.netlify.com to .org
- [x] create redirects from gatsby-mdx.netlify.com to corresponding pages on .org
- [x] update references to https://gatsby-mdx.netlify.com/ to new docs on .org
- [x] update references to gatsby-mdx to official plugin gatsby-plugin-mdx
- [x] clarify docs on using frontmatter and imports in the same file

## Related:

#14258

**Comment by marcysutton** [comment]
Here's a relevant comment from the feedback widget on gatsbyjs.org:

> I had a problem using MDXProvider with MDXRenderer. The issue was, the gatsby-mdx docs say to import MDXRenderer from '@mdx-js/tag', which silently fails. [This doc](https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/) imports '@mdx-js/react', which works as expected.

**Comment by gillkyle** [comment]
Thanks, this is actually something I noticed too and have updated the example from the referred guide already 👍

**Comment by robinmetral** [comment]
Quick aside: it took me a while to understand there were two ways of doing custom components, MDX and [Rehype](https://using-remark.gatsbyjs.org/custom-components/). Since we're trying to encourage MDX, shouldn't we recommend it over Rehype in [gatsby-example-using-remark](https://using-remark.gatsbyjs.org/)?

**Comment by gillkyle** [comment]
Yeah that's a good point @robinmetral, I know MDX uses rehype and remark internally (see [here](https://mdxjs.com/advanced/plugins/)) so trying to push people towards MDX seems like a good idea there, though I think it's great to have that documentation still the same.

**Comment by lannonbr** [comment]
As gatsby-mdx.netlify.com now tells people to use gatsby-plugin-mdx instead, is there any remaining tasks for this issue?

**Comment by marcysutton** [comment]
There may be–we want to make sure the APIs are fully documented. @amberleyromo is taking that on

**Comment by jackbravo** [comment]
Seems like this effort is now finished, right? There is this new section: https://www.gatsbyjs.org/docs/mdx/ Should this issue be closed?

**Comment by marcysutton** [comment]
I checked in with Amberley and Kyle Gill, and it sounds like this one is indeed done now. Any remaining improvements can be handled in new issues and PRs. Thanks so much!
