### ISSUE TITLE
[docs][recipes] Styling: Add Global CSS files

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14892]
## Summary

To improve key learning workflows in the Recipes section of the docs, the "Styling" recipe should be broken up into smaller, more actionable parts. This issue is about the first item, **standard global CSS files** [without a layout component](https://www.gatsbyjs.org/docs/global-css/#adding-global-styles-without-a-layout-component).

The current recipe has this text (it will be replaced by Styling recipes inline): 

> There are so many ways to add styles to your website; Gatsby supports almost every possible option, through official and community plugins.
> - Walk through adding global styles to an example site in tutorial part two
>    - More on global styles with standard CSS files
>    - More on global styles with CSS-in-JS
>    - More on global styles with CSS files and no layout component
> - Use the CSS-in-JS library Glamor
> - Use the CSS-in-JS library Styled Components
> - Use CSS Modules

The actionable version of this **global CSS recipe** should show how to work with a vanilla CSS file _inline_ as concisely as possible. It should include code snippets showing a short CSS file and how it can be imported into `gatsby-browser.js` (like on https://www.gatsbyjs.org/docs/global-css/#adding-global-styles-without-a-layout-component).

Recipes now follow this format:

- Requirements or prerequisites 
- Step-by-step instructions
- Relevant links to any relevant information
    - Link to a live example
    - More on using standard global CSS files https://www.gatsbyjs.org/docs/global-css/

This recipe will go into the "Styling" section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md), replacing the existing text. There is a template in the contributing docs: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by mehtavishwa30** [comment]
Hi @marcysutton! I'd like to start working on this issue.
