### ISSUE TITLE
[docs][recipes] Styling: Adding a local font

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14897]
## Summary

To improve key learning workflows in the Recipes section of the docs, the "Styling" recipe should be broken up into smaller, more actionable parts. This issue is about how to **Add a local font**, coming after the CSS Modules recipe requested in https://github.com/gatsbyjs/gatsby/issues/14896. 

This recipe should show how to work with local fonts _inline_ as concisely as possible. Many of the learning paths recommend using Typography.js, but not everyone wants to use that. This recipe should show how to import a local font for self-hosting with code snippets.

Recipes now follow this format:

- Requirements or prerequisites 
- Step-by-step instructions
- Relevant links to any relevant information
    - More on importing files: https://www.gatsbyjs.org/docs/importing-assets-into-files/ 
    - Using Typography.js for Google fonts: https://www.gatsbyjs.org/docs/typography-js/ 
    - Link to a live example

This recipe should go into the "Styling" section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md), replacing the existing text. There is a template in the contributing docs: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by kkaramch** [comment]
@marcysutton I'd like to help with this issue. It's my first contribution.

**Comment by kkaramch** [comment]
I submitted a PR. #15257

**Comment by watadarkstar** [comment]
Hi @marcysutton I'll be assisting @kkaramch with his PR - he's my mentee over the summer 😄 I'll be keeping an eye out for your comments on his PR (if any) and helping him work through them.
