### ISSUE TITLE
Create marketing/docs site

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#149]
If anyone is interested in a doc writing party in SF/online let me know :)
## Stuff (beyond the normal) to document
- Default webpack config (which loaders/plugins are added + why) + how to modify it + common modifications
- Deployment
- Project philosophy. What it isn't and isn't. Constraints you should be aware + their advantages/disadvantages.
- List starters #56 
- document how to accomplish common patterns in Gatsby/React.js e.g. [Disqus](https://github.com/gatsbyjs/gatsby/issues/133), generating Atom/RSS feeds & site maps, etc.
- Pointers to learning React to React newbies.

Other things that should be there? E.g. what did you find confusing when playing with Gatsby?

Let's continue to flesh out the list of topics to cover and then start writing docs (in markdown) and land them as PRs against the [1.0 branch](https://github.com/gatsbyjs/gatsby/tree/1.0) in a `/docs` directory.

**Comment by tychota** [comment]
in common pattern , generating an atom/rss feed could be added ! I manage to do it, using the `post-build` from your blog but I wasn't an easy road.

**Comment by KyleAMathews** [comment]
@tychota absolutely, I'll add that to the list.

**Comment by kaihendry** [comment]
Keen for some pointers how to generate an RSS feed from the starter blog template. Cheers!

**Comment by KyleAMathews** [comment]
@kaihendry check out what I did for my personal blog (need to convert this to JS) https://github.com/KyleAMathews/blog/blob/master/post-build.coffee

**Comment by KyleAMathews** [comment]
Hey folks — been working on design + components for Gatsby powered documentation sites. As a test case I've been working on a PR to convert the new Webpack website to use Gatsby. Would love feedback on the design, etc. as whatever that ends up being will be what we will use here (or very similar).

https://github.com/webpack/webpack.js.org/pull/202

**Comment by kaihendry** [comment]
Looks good @KyleAMathews. My only niggle is that View Source is FUGLY. 
view-source:https://webpack-gatsby.netlify.com/concepts/targets/

I know one is supposed to use Chrome Dev tools to explore the markup in 2016, but I prefer to have readable markup. It's the way I learnt the Web and as a result, any site that has fugly markup gets minus points from me.

Oh btw CONFIGURATION is line breaked? http://s.natalian.org/2016-10-05/1475643336_2558x1404.png

**Comment by KyleAMathews** [comment]
@kaihendry ahhh I see you're an old-timey web developer who likes the fine patina developed on hand-crafted, hand-polished HTML ;-)

You'll love the new plugin system with Gatsby 1.0 as you could create a plugin to pretty-print Gatsby's output :-)

Hmmm... yeah, it looks like that line breaks at 872 pixels wide on my mac chrome. I'll shrink it down or set a min-width on that column in the morning.

**Comment by MoOx** [comment]
@KyleAMathews I think the current visible css is very redundant. Is this something that can be improved?

**Comment by KyleAMathews** [comment]
@MoOx not sure I understand what you mean? Which css? Redundant to what?

**Comment by MoOx** [comment]
view-source:https://webpack-gatsby.netlify.com/concepts/targets/

![image](https://cloud.githubusercontent.com/assets/157534/19121966/bd4b5042-8b28-11e6-8fdc-774345951257.png)

**Comment by KyleAMathews** [comment]
@MoOx oh gotcha... hmmm you're right, there is a lot of duplicates there. That's the output from extracting styles from [Glamor](https://github.com/threepointone/glamor/) — I'll file an issue there about deduping rules when server rendering. In the meantime though, all hail the magic of gzip :-)

**Comment by kaihendry** [comment]
Btw the hero graphic doesn't look good http://s.natalian.org/2016-10-06/iphone7+.PNG

Actually I'm pretty confused by https://webpack-gatsby.netlify.com/93881a5096732dfdf25532ff4596690a.png

I thought the "idea" with Webpack is that you can put js,css,png,jpg(as data uris) etc etc all in one payload, the bundle.js! https://www.youtube.com/watch?v=WQue1AN93YU

**Comment by KyleAMathews** [comment]
Interesting write-up on doc sites' sidebar navigation http://idratherbewriting.com/2016/10/23/coding-sidebar-navigation-for-documentation-websites/

**Comment by KyleAMathews** [comment]
Very early preview of new site is up — https://gatsbyjs.netlify.com/

Going to be working on a sketch soon for a proposal for the information architecture.

**Comment by KyleAMathews** [comment]
Something that'd be fun/useful to explore for mobile is a bottom navigation bar. Perhaps with links to home, docs, news, and a hamburger menu with an extended navigation menu.

Links:

* https://material.google.com/components/bottom-navigation.html
* https://www.smashingmagazine.com/2016/11/the-golden-rules-of-mobile-navigation-design/

Quartz is a web site that showcases this nicely http://qz.com/

**Comment by KyleAMathews** [comment]
StackOverflow's documentation project is really interesting — http://meta.stackoverflow.com/questions/339974/the-dawn-of-documentation-a-solstice-update?cb=1

This bit is suggestive of some things we could add to Gatsby's docs:

>Wikipedia offered low transaction costs to participation, and it de-emphasized the social ownership of content. Editing Wikipedia is easy, and instant, and virtually commitment-free. “You can come along and do a drive-by edit and never make a contribution again,” Hill pointed out. And the fact that it’s difficult to tell who wrote an article, or who edited it — rather than discouraging contribution, as you might assume — actually encouraged contributions, Hill found. “Low textual ownership resulted in more collaboration,” he put it.

It might be helpful to let people edit the Gatsby docs site directly on the site so you click a button on a page and up pops a model.

**Comment by erlend-sh** [comment]
> It might be helpful to let people edit the Gatsby docs site directly on the site so you click a button on a page and up pops a model.

I [pitched such a thing for Jekyll](http://talk.jekyllrb.com/t/an-idea-for-front-end-editing-in-jekyll-via-the-github-api-and-web-based-markdown-editors/737), and @mushishi78 actually rolled with it and developed a working prototype:

https://github.com/wiki-hub
https://jekyll-anon.surge.sh/gods/2015/02/18/vesta.html (live demo)

![wikihub-piclite-gif-crop](https://cloud.githubusercontent.com/assets/583842/9761287/1bf37096-56fc-11e5-9081-93268ec386c6.gif)

It needs to be running persistently on a service like Heroku though. As far as I know there's no way around that.

**Comment by KyleAMathews** [comment]
@erlend-sh nifty! Yeah, that's exactly what I was thinking of. User clicks edit, auths against github, makes change w/ commit message, and a PR is created.

**Comment by MarcCoet** [comment]
Maybe using [Netlify CMS](https://github.com/netlify/netlify-cms). Though I don't know if you can even access the Editing UI if you are not a collaborator on the repo...

**Comment by mchandleraz** [comment]
I'm trying to get Disqus integrated to a new Gatsby project and I'm not having much success so far. I saw #133, but the link from @KyleAMathews 404s now and I wasn't able to find anything disqus related in that repo.

I'd be happy to write the docs, if someone can point me in the direction of some more info or a reference implementation.

Thanks!

**Comment by KyleAMathews** [comment]
@mchandleraz this is the react component that I was using https://github.com/mzabriskie/react-disqus-thread
