### ISSUE TITLE
In Gatsby 2.9, filesystem data changes are lost on browser reload

### ISSUE THREAD

**Issue by wodenx** [gatsbyjs/gatsby#14903]
## Description

Since Gatsby 2.9, using gatsby-source-filesystem, when running gatsby develop, changes to file data are correctly propagated to the browser, but then disappear when the page is reloaded (except on the homepage).  This behavior is not reproducible in 2.8.8.  I have published a test case illustrating the problem at https://github.com/wodenx/gatsby-fs-reload-bug.

### Steps to reproduce

1. Clone [this repo](https://github.com/wodenx/gatsby-fs-reload-bug).
2. Run `npm i`
3. Run `gatsby develop`
4. open both the homepage and `/page-2` in separate browser tabs.
4. Manually edit data in `/src/data/pages/page.txt`
5. Verify that the changes are reflected in the browser (should see changes in both `size` and `changeTime` fields.
6. Reload both pages

### Expected result

The changes are reflected on both pages after reload.

### Actual result

The changes are reflected on the homepage after reload.
On /page-2 the original data (prior to modification from step 4)
is displayed.

### Environment
```
  System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.90
    Firefox: 67.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.9.6 => 2.9.9
    gatsby-cli: ^2.6.9 => 2.6.12
    gatsby-image: ^2.1.4 => 2.1.4
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.3 => 2.1.3
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.1.6 => 2.1.9
    gatsby-source-filesystem: ^2.0.41-reporter-npm.9 => 2.0.43
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.6.9
```

**Comment by KyleAMathews** [comment]
Just reproduced the bug — that's an odd one. Thanks for the reproduction! Lemme think about why this is happening.

**Comment by KyleAMathews** [comment]
Identified the problem. In 2.9 we started normalizing pathnames in the client but didn't on the server so we're not updating the server query result cache correctly. I'll pr a fix a bit later.
