### ISSUE TITLE
gatsby-plugin-sass styles loaded as global css not as variable

### ISSUE THREAD

**Issue by derit** [gatsbyjs/gatsby#14919]
here for reproduce
i'm using plugin **gatsby-plugin-sass**

create a file with name mystyles.scss 
the code
import styles from './mystyles.scss'

console.log(styles)

result 

`{ }`

case two
in mystyles.scss create a styles 
```
.mybutton{
backgroud:red
}
```
the code

```
import styles from './mystyles.scss'

<button className="mybutton" />

```
i think this a bug

 mystyles.scss is loaded as global styles, background color of button with class mybutton is red,
 
expect no backgroud because styles as variable no imported as global like ` import './mystyles.scss'
`

 here an example styles as variable

```
import styles from './mystyles.scss'

<button className={styles.mybutton} />

```

**Comment by freiksenet** [comment]
Hello @derrit!

Unfortunately I can't reproduce this issue. If you look at https://www.gatsbyjs.org/starters/colbyfayock/gatsby-starter-sass/, it seems to import styles globally when you do the import. I wonder if you can make a minimal reproduction with that issue?

Thank you! :purple_heart: :muscle:

**Comment by lannonbr** [comment]
@derit are you still running into this issue? If so, would you be able to make a reproduction as Mikhail commented so we can try debugging this?

**Comment by derit** [comment]
@lannonbr was solved

**Comment by xBau** [comment]
@derit how did you solve the problem?

I'm having the same issue

**Comment by derit** [comment]
@xBau follow this document
[https://www.gatsbyjs.org/packages/gatsby-plugin-sass/](url)
and follow this [https://www.gatsbyjs.org/packages/gatsby-plugin-sass/#with-css-modules](url)
