### ISSUE TITLE
gatsby-cli 2.6.13 error on `gatsby new`: cwebp: error while loading shared libraries: libXi.so.6

### ISSUE THREAD

**Issue by eyalroth** [gatsbyjs/gatsby#14913]
## Description
Upon `gatsby new` (global installation) I get the error:
```txt
> cwebp-bin@5.1.0 postinstall /mnt/c/Users/eyal/repos/gatsby-starter-blog/node_modules/cwebp-bin
> node lib/install.js

  ⚠ Command failed: /mnt/c/Users/eyal/repos/gatsby-starter-blog/node_modules/cwebp-bin/vendor/cwebp -version
/mnt/c/Users/eyal/repos/gatsby-starter-blog/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libXi.so.6: cannot open shared object file: No such file or directory


  ⚠ cwebp pre-build test failed
  ℹ compiling from source
```

The `gatsby new` process will complete eventually, but it takes far more time and eventually there are additional errors with this CLI version as described in #14911.  I'm not sure if it's only since version `2.6.13` or a bit sooner, but I update regularly so I suspect it's quite a recent bug.

Describe the issue that you're seeing.

### Steps to reproduce
1. `npm i -g gatsby-cli`
2. `gatsby new gatsby-starter-blog https://github.com/gatsbyjs/gatsby-starter-blog`

### Environment
```
eyal@eyal-indeni:/mnt/c/Users/eyal/repos$ gatsby info --clipboard
  System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/n/bin/node
    npm: 6.9.0 - ~/n/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  npmGlobalPackages:
    gatsby-cli: 2.13.0
```
**Note** that this is a WSL installation on Windows 10.0.17134.799.

**Comment by wardpeet** [comment]
🤔 We have bumped sharp in the past but still it shouldn't break.

Seems like an issue with WSL rather than gatsby but have you tried googling `error while loading shared libraries: libXi.so.6:` ?

**Comment by eyalroth** [comment]
@wardpeet I googled and tried installing `libxtst6`, but that wasn't enough. Seems like `sudo updatedb` suggested in the blog you linked did the job. Thanks!

**Comment by inseokr** [comment]
I tried to install concurrently in the target environment, but failed.
