### ISSUE TITLE
few react/gatsby beginner questions

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#14914]
1. 
if everything works as it should, let's assume that we have a shop with 10k products.
very estimating how long "gatsby develop" and "gatsby build" should last for 10 k products and 100 categories.

2. 
i'm using now gatsby-source-custom-api, my question if i provide graphql API instead, will this significantly affect the build speed?

3. 
i have issue 6654 my question is this problem occour only with plugins like gatsby-source-custom-api and problem dissapear if i provide  graphql API ? 

4. 
is there any possibility to use lazy load images for remote images (not downloaded)? 

For example, I will download additional photos from the API that were not downloaded by grapthql during build. 

5. 
In gatsby-source-custom-api config schema if i use:  

product_id: Int 

And then make query 
{
  product(product_id: {eq: 123})
}

i allways get null result, when i use 

product_id: String!

{
  product(product_id: {eq: "123"})
}
 
everything work correctly. 

Why this do not work with Int definitions? Using string in sql queries slow down queries?

**Comment by marcysutton** [comment]
Hi there, I think Discord would be a good place to ask questions in this format! https://www.gatsbyjs.org/contributing/community/#discord
