### ISSUE TITLE
Possible issue with Fragments containing Unions?

### ISSUE THREAD

**Issue by grantglidewell** [gatsbyjs/gatsby#14921]
## Description

An exported fragment containing a union throws errors on develop, however only in a component, not in a page component. 

### Steps to reproduce

---pages/index.js
```javascript
export const ExportedFragment = graphql`
  fragment ExportedFragment on type {
    id
    created(formatString: "MMMM DD YYYY")
    path {
      alias
    }
      field_components {
        ... on text {
          information
        }
        ... on image {
          informaiton
        }
      }
    }
  }
`;
```

--- pages/anotherPage
```
  const data = useStaticQuery(graphql`
    {
      allType {
        nodes {
          ...ExportedFragment
        }
      }
    }
  `);
```
no error

--- components/ComponentWhoFails/ComponentWhoFails.js
```
  const data = useStaticQuery(graphql`
    {
      allType {
        nodes {
          ...ExportedFragment
        }
      }
    }
  `);
```
throws an error in the build process. the build process does however complete.

### Expected result

The query should run with no errors thrown, as happens in the same application with another query being used the same way, but does not have Unions.

### Actual result

```
Error loading a result for the StaticQuery in "/ComponentWhoFails.js". Query was not run and no cached result was found.
```

### Environment
```
  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.2 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.3.16 => 2.3.31
    gatsby-image: ^2.0.37 => 2.0.40
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6
    gatsby-plugin-manifest: ^2.0.28 => 2.0.29
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.0.32 => 2.0.35
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2
    gatsby-source-drupal-preview: ^0.2.0 => 0.2.0
    gatsby-source-filesystem: ^2.0.29 => 2.0.32
    gatsby-transformer-sharp: ^2.1.17 => 2.1.18
  npmGlobalPackages:
    gatsby-cli: 2.5.12
    gatsby: 2.1.22
```

**Comment by freiksenet** [comment]
It's not yet possible to use fragments with `useStaticQuery`. We are working on the fix for this, so that fragments can be used there, but there is no ETA for this. I recommend that you use regular page  queries if you want to use fragments.

I'm closing this issue, feel free to open it if you have any more question.

**Comment by grantglidewell** [comment]
interesting, I have working fragments in useStaticQuery. The data resolves for all of the queries as I mentioned, it just throws the error. It's only a query with a union that behaves this way. 

Is it maybe Unions that arent supported in useStaticQuery (even though it works, just errors)?
