### ISSUE TITLE
App works fine locally, deploys to Heroku, but doesn't load, has error "App boot timeout"

### ISSUE THREAD

**Issue by sophyphreak** [gatsbyjs/gatsby#14927]
## Description

I'm using gatsby 2.0.76, deploying through heroku-cli. The app seems to deploy just fine, getting this message in the command line:
```
remote: Verifying deploy... done.
```
But then it doesn't load, and I get the heroku application error page:

[![!\[Heroku Application Error Page][1]][1] I get this error when I run `heroku logs --tail` in the command line:

```
2019-06-19T17:46:15.443142+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/" host=sheltered-journey-44127.herokuapp.com request_id=93bfbe03-0fdc-48dd-a5f5-6dea99d03ba4 fwd="73.155.178.206" dyno= connect= service= status=503 bytes= protocol=https
2019-06-19T17:46:28.338200+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2019-06-19T17:46:28.338200+00:00 heroku[web.1]: Stopping process with SIGKILL
2019-06-19T17:46:28.459853+00:00 heroku[web.1]: State changed from starting to crashed
2019-06-19T17:46:28.430750+00:00 heroku[web.1]: Process exited with status 137
```
### Steps to reproduce

1. Clone [my github repo][2].
2. Run `heroku create` and push it to heroku. Run `git push heroku master`.
3. See Application Error screen on `heroku open`.
4. See error messages on `heroku logs --tail`.

[This is a current demo of the broken app on heroku](https://sheltered-journey-44127.herokuapp.com/).

### Expected result

The app should be there and not broken.

### Actual result

Application Error page.

### Environment

  System:
    OS: Linux 4.15 elementary OS 0.4.1 Loki
    CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 11.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.3
  npmPackages:
    gatsby: ^2.0.76 => 2.9.0 
    gatsby-image: ^2.0.28 => 2.1.3 
    gatsby-plugin-manifest: ^2.0.9 => 2.1.1 
    gatsby-plugin-offline: ^2.0.16 => 2.1.1 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.12 
    gatsby-plugin-sass: ^2.0.7 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.14 => 2.1.3 
    gatsby-source-filesystem: ^2.0.17 => 2.0.39 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.21 
  npmGlobalPackages:
    gatsby-cli: 2.6.7

  [1]: https://i.stack.imgur.com/EBm9p.png
  [2]: https://github.com/sophyphreak/my-portfolio

**Comment by freiksenet** [comment]
Looks like the Heroku buildpack that is used is not the Heroku static one. Have you checked our [guide to deploying on Heroku](https://www.gatsbyjs.org/docs/deploying-to-heroku/)?

**Comment by sophyphreak** [comment]
Hi @freiksenet, thanks for replying! :)

I have checked your guide to deploying on Heroku. I believe I followed it to the letter. I ran
```
$ heroku buildpacks:set heroku/nodejs
$ heroku buildpacks:add https://github.com/heroku/heroku-buildpack-static.git
```
in the command line. The project has an `app.json` file that looks like this:
```
{
  "buildpacks": [
    {
      "url": "heroku/nodejs"
    },
    {
      "url": "https://github.com/heroku/heroku-buildpack-static"
    }
  ]
}
```
It also has a scripts in `package.json` that looks like this:
```
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "start": "npm run develop",
    "format": "prettier --write \"src/**/*.js\"",
    "test": "echo \"Write tests! -> https://gatsby.app/unit-testing\"",
    "heroku-postbuild": "gatsby build"
  },
```
And lastly, it has a `static.json` that looks like this:
```
{
  "root": "public/",
  "headers": {
    "/**.js": {
      "Cache-Control": "public, max-age=0, must-revalidate"
    }
  }
}
```
I believe I had previously checked all the boxes here, and yet it's still not working.

**Comment by wardpeet** [comment]
This is weird, we just updated the docs page with some updated information.
It looks like the same issue as https://github.com/gatsbyjs/gatsby/issues/14546. Could you try if that resolves your issue?

**Comment by sophyphreak** [comment]
Thanks @wardpeet it works! Thank you!!!!

**Comment by wardpeet** [comment]
Can you tell us what the issue was? Should we add something to the docs pages?

**Comment by sophyphreak** [comment]
I think it was just the same as the other guy. Remove the Procfile and change the static.json. I'm not sure anything needs to be added to the docs page.

**Comment by dimitrisnl** [comment]
@sophyphreak 	Which was the change in static.json?

**Comment by wardpeet** [comment]
@dimitrisnl please have a look at https://www.gatsbyjs.org/docs/deploying-to-heroku/. Make sure to remove the Procfile.

You probably have to remove `"start": "npm run develop"`
