### ISSUE TITLE
[docs] improve messaging on "Client Data Fetching"

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14938]
## Summary

Feedback from gatsbyjs.org shows the doc on Client Data Fetching could be improved, particularly for beginners: https://www.gatsbyjs.org/docs/client-data-fetching/

> "This may seem obvious to some people but probably not for newbies. How about mentioning when it's appropriate to use build time vs. run time? It seems like build time is good for when we want to fetch data that either doesn't change or it's not important to our app if it does change. Run time seems appropriate for constantly changing data like an email client."

This page assumes quite a bit of knowledge with terminology. Some improvements would be to link to the glossary for [hydration](https://www.gatsbyjs.org/docs/glossary/#hydration) and explain the concepts more fully. 

The page on Life and Times of a Gatsby build would be helpful as well, I filed a separate issue for it here: https://github.com/gatsbyjs/gatsby/issues/14937

**Comment by eduarmreyes** [comment]
Hi @marcysutton, I would very much like to help on this issue, let me know if I can. Plus, I would like to confirm if links to the glossary are sufficient to fix this one.

![image](https://user-images.githubusercontent.com/3196685/59810883-4849db80-92d5-11e9-81ad-367e8dfc4d55.png)

**Comment by marcysutton** [comment]
Hi @eduarmreyes, thanks for your offer to help! The glossary link is one to-do item (I also opened https://github.com/gatsbyjs/gatsby/pull/14939/ to update some terminology on that page), but the bulk of this issue is around explaining concepts on the docs page itself. New learners don't always know when client-data fetching is appropriate, so a brief explanation of build-time vs. client run-time and some examples/recommendations would help. See the blockquote in the issue description for more.

**Comment by eduarmreyes** [comment]
Hello, @marcysutton I opened a new PR, let me know your thoughts.

https://github.com/gatsbyjs/gatsby/pull/15020/files

**Comment by eduarmreyes** [comment]
This should be closed because the PR https://github.com/gatsbyjs/gatsby/pull/15020/ is successfully merged thanks to @marcysutton.

**Comment by marcysutton** [comment]
Good call. Thanks, @eduarmreyes!
