### ISSUE TITLE
[docs] improve "Adding search with Algolia" guide

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14936]
## Summary

Feedback from gatsbyjs.org shows this page could be improved with an explanation about where to get environment variables from Algolia: https://www.gatsbyjs.org/docs/adding-search-with-algolia/

> where do i get the GATSBY_ALGOLIA_APP_ID? where do i get the GATSBY_ALGOLIA_SEARCH_KEY??? Is this generated or I can set it to anything? This should either be obvious / intuitive OR steps should be mentioned on how to retrieve this.

Also, it jumps right into the _how_ without much of the _why_. What's the motivation to do this work?
> Whoa. This is WAY too much work for just search functionality!

Action items:
- [ ] Explain in plain language where to find the `GATSBY_ALGOLIA_APP_ID` and `GATSBY_ALGOLIA_SEARCH_KEY`
- [ ] Show screenshots if possible (with alt text)
- [ ] Add a brief explanation of why this coding approach is useful and necessary when implementing search

**Comment by tom-raley** [comment]
I can take a stab at this!
