### ISSUE TITLE
[bug]: ☂️ umbrella issue for Drupal + Gatsby Preview issues

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#14933]
## Description

In this umbrella issue, we'd like to provide a means for others to share any issues encountered regarding the work-in-progress functionality with Drupal + Gatsby Preview. The changes in the source plugin are being worked on in #14630, but it is most helpful to provide a unified forum to best track upon and prioritize any issues that arise.

## Template

Please use the following template to report an issue so that we can most effectively debug the underlying issue.

Note: it is *extremely important* that you provide as much information as possible for the reproduction step. The more info and clearer the reproduction, the better we will be able to debug and ship fixes to these issues!

```markdown
## Description

<!-- What seems to be the issue? Please describe in as much detail as possible. -->

## Reproduction

<!-- Please, please provide detailed steps to reproduce. Ideally a Github repository where we can reproduce the issue(s) ourselves, as well. -->
```

**Comment by sidharthachatterjee** [comment]
Gatsby Preview and Drupal have been working fine for a while and we now accept reports of issues via support@gatsbyjs.com so I think it's time to close this issue. 

Thank you!
