### ISSUE TITLE
Production Build Fully Reloading On Page Change

### ISSUE THREAD

**Issue by mattoni** [gatsbyjs/gatsby#14930]
## Description

In my development build, everything works as expected, and navigating to different pages does not trigger a full navigation and full page reload. In production, this is not the case and every page change results in the browser doing a full navigation.

### Steps to reproduce

I honestly have no idea, this was working before but something in my latest build is causing this. Maybe a clue is the URL flashes back and forth before finally navigating, so I'm wondering if there is an issue there?

See https://docs.cycle.io for the deployed live version

### Expected result

Navigation should be smooth and act as a single page

### Actual result

Site is doing a full reload/navigation on every page

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (12) x64 AMD Ryzen 5 1600X Six-Core Processor
    Shell: 5.1.1 - /usr/bin/zsh
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  npmPackages:
    gatsby: ^2.4.6 => 2.4.6
    gatsby-plugin-canonical-urls: ^2.0.5 => 2.0.6
    gatsby-plugin-layout: ^1.0.3 => 1.0.3
    gatsby-plugin-linaria: ^1.2.0 => 1.2.0
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-root-import: ^2.0.4 => 2.0.4
    gatsby-plugin-typescript: ^2.0.0 => 2.0.0
    gatsby-source-filesystem: ^2.0.1 => 2.0.3
    gatsby-transformer-json: ^2.1.1 => 2.1.4

**Comment by mattoni** [comment]
I did a bunch more testing and found the culprit. The issue was happening only when I built the gatsby build into a container, which made me suspect a dependency issue. I upgraded gatsby to the latest locally (v2.9.11) and the issue occurred outside the container. Reverted back to 2.4.6 and poof, no issue.

Looks like there may be a bug in the new version?

**Comment by JonathanLehner** [comment]
? did it get solved?

**Comment by choyan** [comment]
Save problem facing here.

**Comment by codeshifu** [comment]
Does anyone have a fix for this issue?

**Comment by vineckb** [comment]
@mattoni I see you fix this on your link(https://docs.cycle.io/).

Can you tell me how to solve this problem?

**Comment by fafrd** [comment]
I had this problem- remember to use Gastby's `<Link>` tag for internal page navigation, not the normal `<a href=...>`. 

`<Link>` will intelligently refresh only the parts of the page that need to be refreshed.

for example:
```jsx
import React from "react"
import { Link } from "gatsby"
const Page = () => (
  <div>
    <p>
      Check out my <Link to="/blog">blog</Link>!
    </p>
    <p>
      {/* Note that external links still use `a` tags. */}
      Follow me on <a href="https://twitter.com/gatsbyjs">Twitter</a>!
    </p>
  </div>
)
```

docs: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/
