### ISSUE TITLE
[docs] Improve messaging on "Add a 404 page"

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14935]
## Summary

We got some feedback on the Add a 404 docs page, and the suggestions seem like they would help everyone. https://www.gatsbyjs.org/docs/add-404-page/

Current text: "When developing, Gatsby adds a default 404 page that overrides your custom 404 page. But you can still preview your 404 page by clicking “Preview custom 404 page” to verify that it’s working as expected."

>  _Don't understand this at all. If it overrides, should I make my own or not? Where am I supposed to click to see the preview is also not clear._

> _The 404 doc could use a bit clearer explanation of how the 404.html is created. How is this configured in the gatsby-node.js?_

Action items:
- [ ] Add a screenshot of the development 404 page (with alt text)
- [ ]  Add more details about how the 404.html is created - explain the magic happening here and that you don't need `gatsby-node.js` for it

**Comment by tom-raley** [comment]
I can take this on.

**Comment by prestonso** [comment]
Merged in #15036. Closing!

**Comment by marcysutton** [comment]
Thanks for your work on this, @tom-raley! it was a great addition in response to user feedback on gatsbyjs.org. ✅
