### ISSUE TITLE
[docs][recipes] Install a starter with the Gatsby CLI

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14943]
## Summary

To improve key learning workflows in the Recipes section of the docs, there should be a more actionable recipe on installing a Gatsby starter that comes after the Styling recipes (the last of which is #14897). Here's the current starter recipe: https://www.gatsbyjs.org/docs/recipes/#using-a-starter

This text should be changed to show how to work with the CLI _inline_ as concisely as possible, with code examples inline for the commands. It should use the most common syntax of [installing from a Git repo by its URL](https://www.gatsbyjs.org/docs/starters/#using-git-repo-urls).

Recipes now follow this format:

- Requirements or prerequisites 
    - Installing Node, npm and the Gatsby CLI: https://www.gatsbyjs.org/docs/preparing-your-environment/
    - Picking a starter repo URL: https://www.gatsbyjs.org/starters/?v=2
- Step-by-step instructions
- Relevant links to any relevant information
    - More on Gatsby Starters: https://www.gatsbyjs.org/docs/starters/ 
    - Link to a live example

This recipe should go into the "Using a starter" section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md), replacing the existing text. There is a template in the contributing docs: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by marisamorby** [comment]
This issue overlaps and should be done at a similar time as issue #14944.

**Comment by amberleyromo** [comment]
Closed in #16231
