### ISSUE TITLE
[docs][recipes] Sourcing Markdown pages from the filesystem

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14946]
## Summary

To improve key learning workflows in the Recipes section of the docs, there should be an actionable recipe on sourcing Markdown pages from the filesystem that comes after the starter and theme installation recipes captured in #14943 and #14944.

This recipe should show how to install `gatsby-source-filesystem` in `gatsby-config.js` to source Markdown _pages_ in a Gatsby site (as opposed to a list of blog posts). It should briefly mention the [Gatsby data layer](https://www.gatsbyjs.org/docs/using-gatsby-without-graphql/#the-tradeoffs-of-foregoing-gatsbys-data-layer) and show how to inspect the content in GraphiQL, preferably with an embedded example like on https://www.gatsbyjs.org/docs/graphql-reference/

Recipes now follow this format:

- Requirements or prerequisites 
- Step-by-step instructions
- Relevant links to any relevant information
    - Adding Markdown pages: https://www.gatsbyjs.org/docs/adding-markdown-pages/
    - More on Sourcing from the filesystem: https://www.gatsbyjs.org/docs/sourcing-from-the-filesystem/
    - Link to a live example if not already embedded

This recipe should go into a new  section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md) titled "Sourcing Content" (if it hasn't already been created). There is a recipe template in the contributing docs, including tips on adding a new section: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by marcysutton** [comment]
The goal for this issue is to add a recipe in the Sourcing Data section with the content that's currently in Pages and Layouts > Creating pages with createPage. To minimize overlap, that recipe on createPage should be simplified to use a `const` object with data instead of integrating Markdown (to limit the scope and make that more intuitive to learners). A good title for the Pages and Layouts recipe then would be something like "Create pages programmatically with createPage"

**Comment by gillkyle** [comment]
This was done with #17009

**Comment by mehtavishwa30** [comment]
Hi @marcysutton! I'd like to start working on this issue if it still needs help.
