### ISSUE TITLE
[docs][recipes] Sourcing from Contentful

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14949]
## Summary

To improve key learning workflows in the Recipes section of the docs, there should be an actionable recipe on sourcing from Contentful that comes after the recipes on [sourcing Markdown pages](https://github.com/gatsbyjs/gatsby/issues/14946) and [blog posts](https://github.com/gatsbyjs/gatsby/issues/14947) and [sourcing from Wordpress](https://github.com/gatsbyjs/gatsby/issues/14948). This is also related to the Contentful workflow evaluation in https://github.com/gatsbyjs/gatsby/issues/13945.

This recipe should show how to use the `gatsby-source-contentful` plugin to source content from Contentful _inline_ as concisely as possible. Showing how the data layer can be inspected with GraphiQL would help understanding. The docs page on Sourcing from Contentful can be used as a starting point: https://www.gatsbyjs.org/docs/sourcing-from-contentful/

Recipes now follow this format:

- Requirements or prerequisites 
    - This would include setting up a Contentful site, to keep the scope of the recipe limited to Gatsby-related tasks
- Step-by-step instructions
- Relevant links to any relevant information
    - Building a Site with React and Contentful: https://www.gatsbyjs.org/blog/2018-1-25-building-a-site-with-react-and-contentful/
    - More on Sourcing from Contentful: https://www.gatsbyjs.org/docs/sourcing-from-contentful/
    - Link to a live example

This recipe should go into a new section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md) titled "Sourcing Content" (if it hasn't already been created). There is a recipe template in the contributing docs, including tips on adding a new section: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by mehtavishwa30** [comment]
Hey @marcysutton! 
If this still needs help, can I work on it?

**Comment by kevee** [comment]
Sorry, @mehtavishwa30, just saw your comment after I did the PR.
