### ISSUE TITLE
[docs][recipes] install a theme

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14944]
## Summary

To improve key learning workflows in the Recipes section of the docs, there should be an actionable recipe on installing a Gatsby theme that comes after the starter recipe (see #14943).

I've assigned this to you, @amberleyromo, as you're working on the theme docs, but I'll let you decide whether to reassign. I've intentionally included both "install a starter" and "install a theme" as recipes to show the unique aspects of each, but I'm happy to discuss the content breakdown further!

Recipes now follow this format:

- Requirements or prerequisites 
- Step-by-step instructions
- Relevant links to any relevant information
    - Gatsby theme docs
    - Link to a live example, video, etc. - @jlengstorf is working on this!

This recipe should go into a new section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md) titled "Themes" (coming after "Using a starter". There is a recipe template in the contributing docs, including tips on adding a new section: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by amberleyromo** [comment]
Closed in #16231
