### ISSUE TITLE
Preserve scroll in sidebar on page change without layout plugin?

### ISSUE THREAD

**Issue by mattoni** [gatsbyjs/gatsby#14940]
## Summary

Is it possible to preserve the scrollbar in a nav menu between page changes, without setting up a layout plugin?

## Relevant information

I'm building a documentation site that has two primary layouts interchanged depending on what "kind" of docs you're looking at (regular vs api). Both of these menus can be long, and changing pages always jumps the sidebar up to the top, which is a bad experience for the user.

I don't want to use a layout plugin because not every page is going to have the same layout, and adding extra complexity to decide which layout to show just to preserve a scrollbar is tedious, difficult to follow and more prone to error. Ideally I'd like to find a solution to preserve the scrollbar in the side menu without wrapping it in a layout plugin.

Thanks!

**Comment by freiksenet** [comment]
Pages are always unmounted when they change. You can use [`wrapPageElement`](https://www.gatsbyjs.org/docs/browser-apis/#wrapPageElement) API to provide a component that renders your sidebar.

**Comment by lannonbr** [comment]
@mattoni Have you looked into using Mikhail's suggestion of trying `wrapPageElement`?

**Comment by mattoni** [comment]
@lannonbr  I think that's what I'm going to have to do to make it work unfortunately. Thanks for the assistance.
