### ISSUE TITLE
[docs][recipes] Sourcing from Wordpress

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14948]
## Summary

To improve key learning workflows in the Recipes section of the docs, there should be an actionable recipe on sourcing from Wordpress that comes after the recipes on [sourcing Markdown pages](https://github.com/gatsbyjs/gatsby/issues/14946) and [blog posts](https://github.com/gatsbyjs/gatsby/issues/14947). This is also related to the Wordpress workflow evaluation in #13876.

This recipe should show how to use the `gatsby-source-wordpress` plugin to source content from Wordpress _inline_ as concisely as possible. Showing how the data layer can be inspected with GraphiQL would also help understanding. The docs page on Sourcing from Wordpress can be used as a starting point: https://www.gatsbyjs.org/docs/sourcing-from-wordpress/

Recipes now follow this format:

- Requirements or prerequisites 
    - This would include setting up a Wordpress site, to keep the scope of the recipe limited to Gatsby-related tasks ([Docker/Wordpress installation instructions might come in handy?](https://www.gatsbyjs.org/contributing/code-contributions/#docker-wordpress-and-gatsby))
- Step-by-step instructions
- Relevant links to any relevant information
    - Getting Started with Wordpress and Gatsby: https://www.gatsbyjs.org/blog/2018-01-22-getting-started-gatsby-and-wordpress/
    - How to Build a Blog with Wordpress and Gatsby: https://www.gatsbyjs.org/blog/2019-04-26-how-to-build-a-blog-with-wordpress-and-gatsby-part-1/
    - More on Sourcing from Wordpress: https://www.gatsbyjs.org/docs/sourcing-from-wordpress/
    - Link to a live example

This recipe should go into a new section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md) titled "Sourcing Content" (if it hasn't already been created). There is a recipe template in the contributing docs, including tips on adding a new section: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by mehtavishwa30** [comment]
Hello! I'd like to submit a PR to this issue if no one else is working on it. Thanks!

**Comment by marcysutton** [comment]
Sounds great, @mehtavishwa30! Go for it!
