### ISSUE TITLE
[docs][recipes] Sourcing from Drupal

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14950]
## Summary

To improve key learning workflows in the Recipes section of the docs, there should be an actionable recipe on sourcing from Drupal that comes after the recipes on [sourcing Markdown pages](#14946) and [blog posts](https://github.com/gatsbyjs/gatsby/issues/14947), [sourcing from Wordpress](https://github.com/gatsbyjs/gatsby/issues/14948) and [sourcing from Contentful](https://github.com/gatsbyjs/gatsby/issues/14949).

This recipe should show how to use the `gatsby-source-drupal` plugin to source content from Drupal _inline_ as concisely as possible. Showing how the data layer can be inspected with GraphiQL would help understanding. The docs page on Sourcing from Drupal can be used as a starting point: https://www.gatsbyjs.org/docs/sourcing-from-drupal/

Recipes now follow this format:

- Requirements or prerequisites 
    - This would include setting up a Drupal site, to keep the scope of the recipe limited to Gatsby-related tasks
- Step-by-step instructions
- Relevant links to any relevant information
    - Using Decoupled Drupal with Gatsby: https://www.gatsbyjs.org/blog/2018-08-13-using-decoupled-drupal-with-gatsby/
    - More on Sourcing from Drupal: https://www.gatsbyjs.org/docs/sourcing-from-drupal/
    - Link to a live example

This recipe should go into a new section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md) titled "Sourcing Content" (if it hasn't already been created). There is a recipe template in the contributing docs, including tips on adding a new section: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by svict4** [comment]
For reference: Lullabot has written some great guides for Drupal+Gatsby integration
https://gatsbyguides.com/

**Comment by JohnAlbin** [comment]
Also note that the `examples/using-drupal` files don't work with the latest Drupal 8.7.0 (or later) version. See https://github.com/gatsbyjs/gatsby/issues/15693
