### ISSUE TITLE
JS Bundle size increased significantly since upgrade to 2.9.4 (~25k page site)

### ISSUE THREAD

**Issue by ConorLindsay94** [gatsbyjs/gatsby#14954]
## Summary
We have recently upgraded Gatsby from v2.3.4 to v2.9.4. We have since noticed a dramatic increase in the app[content-hash].js file size, it has gone from ~650kb to 3.1mb. After close inspection it is due to a massive array containing objects of `matchPath` data:

```
{
   path: "/path/example",
   matchPath: "/path/example/*"
}
```

Is there a reason why this data is now built to the bundle app.js file now? On the previous version we don't get anything like this in the bundled js.

## Relevant information
- Our site contains ~25k pages, each with a matchPath set for dynamic routing.
- We have static sub-router entry points for a large majority of these pages, as in our Router sits in the template passed to `createPage`.

**Comment by pieh** [comment]
@ConorLindsay94 Previously it was in separate file (`pages-manifest`), but still was loaded eagerly.

This is not easy thing to solve. Can you provide some details on why you want to create 25k pages with `matchPath` instead of single one?

**Comment by sidharthachatterjee** [comment]
This one is tricky to fix because for loader to work, we still put all matchPath metadata into a single file. 

We could potentially solve this by doing multiple checks. For instance if a user navigates to `/foo/bar/baz/5432`, we could check `/*`, `/foo/*`, `/foo/bar/*` and then `foo/bar/baz/*`

**Comment by ConorLindsay94** [comment]
> @ConorLindsay94 Previously it was in separate file (`pages-manifest`), but still was loaded eagerly.
> 
> This is not easy thing to solve. Can you provide some details on why you want to create 25k pages with `matchPath` instead of single one?

Before upgrading, we changed these pages to now include a tabbing system, so we needed to implement sub routes. These routes were to be client-only, but we also needed to ensure that the default route for the page was static, as it contains a lot of SEO related data.

We previously did have one `matchPath` defined afterwards in the `onCreatePage` step, but we ran into issues with full page re-renders when navigating between tabs, when it should only be the sub routes rendering. This was because we had a 'dynamic' page set up in `/pages` which the `matchPath` mapped to, so it was essentially rendering two separate components when switching between the default tab and the other ones.

We needed to prevent this behaviour, so we moved the router into the template, and removed the 'dynamic' page. We then also moved the `matchPath` definition into the `createPage` method options. This means that now we have a `matchPath` set against each individual page which was fine for us pre upgrade, its just now that it is in the JS bundle that we can't move forward with our current approach.

Are we correct in our approach? Or is there something we can do better to prevent this from happening?

Thanks!

**Comment by pbrickles** [comment]
@pieh,  @sidharthachatterjee , @ConorLindsay94  - any further progress on this?

**Comment by wardpeet** [comment]
@ConorLindsay94 is it possible to share a snippet or video what the reason is why matchPath is needed for those pages?

We advocate to use only a few matchPaths and not per page.

**Comment by ConorLindsay94** [comment]
@pieh @sidharthachatterjee @wardpeet 

So after further investigation, and some changes to our approach, I think we have got it working how it should now.

The challenge for us was the fact we needed a page created statically through `createPage`, but also a component in `/pages` for the client-only routes. Some of the content we needed to be static was on the default sub-route, so we needed a router in the template component. This means we have two components, containing the same or very similar routers in, for two different purposes.

The behaviour we were initially getting was that the template component was being mounted for the default route, but then the client-only component was being mounted for the other routes when switching between tabs. How we got around it at the time was adding these `matchPath` values in `createPage`, meaning that **only** the static template component mounted, and we removed the components in `/pages`.

However, because of not being able to upgrade, we explored other approaches to see if we can get it working in the way we originally expected, which is that the template should only be used for static HTML generation, and the page component should mount when accessing these pages in the browser. We now have the desired behaviour, and I think that how we did it was by using reach router's nested routing structure in both routers, as previously we didn't have it this way. Now the page component mounts when accessing the routes in the browser, but we still get the static HTML for each page which is great.

Template used for `createPage`
```
<Router>
  <ContainerComponent
     path={urlFromGraphQL}
  >
    <DefaultRoute
      default
    />
    <SecondTabRoute
      path="second-tab-route"
    />
    <ThirdTabRoute
      path="third-tab-route"
    />
  </ContainerComponent>
</Router>
```

Client only component in `/pages`
```
<Router>
  <ContainerComponent
     path="/some-route/:slug/:id"
  >
    <DefaultRoute
      default
    />
    <SecondTabRoute
      path="second-tab-route"
    />
    <ThirdTabRoute
      path="third-tab-route"
    />
  </ContainerComponent>
</Router>
```

One more thing though - in your minds could this be a common issue that people may come across when trying to implement similar routing systems in a hybrid app? Or do you think there is something we have just missed along the way in our own implementation? We couldn't find much in the documentation or in online discussions about what we were trying to achieve, and are still confused about why the template component was mounting at all when hitting those routes in the browser.

**Comment by ConorLindsay94** [comment]
Closing this as initial approach was incorrect with `matchPath` assignment.
