### ISSUE TITLE
Cannot use gatsby-starter-default - pngquant error

### ISSUE THREAD

**Issue by darrenparkinson** [gatsbyjs/gatsby#14959]
## Description

When trying to run through the quick start and using the gatsby-starter-default, it fails with an error:

```
error /.../my-default-starter/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /.../my-default-starter/node_modules/pngquant-bin
Output:
⚠ unable to get local issuer certificate
  ⚠ pngquant pre-build test failed
  ℹ compiling from source

error Command failed: yarnpkg

  Error: Command failed: yarnpkg

  - index.js:236 Promise.all.then.arr
    [lib]/[gatsby-cli]/[execa]/index.js:236:11

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

### Steps to reproduce

* Install gatsby-cli (`npm install -g gatsby-cli`)
* Run `gatsby new gatsby-site`

Essentially just follow the [quick start](https://www.gatsbyjs.org/docs/quick-start/) or the instructions on the [gatsby-starter-default page](https://github.com/gatsbyjs/gatsby-starter-default)

Tried with both yarn and npm.

Using the gatsby-starter-hello-world template works fine.

### Expected result

I should be able to follow the tutorial without error.

### Actual result

It failed.  The site I desperately needed was built with hugo instead.

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.npm-packages/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmGlobalPackages:
    gatsby-cli: 2.6.13

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @darrenparkinson 

I can't reproduce this on my machine. The error messages suggests that this has something to do with `pngquant` not building correctly. 

https://github.com/imagemin/pngquant-bin/issues/77 might be relevant. Could you please open an issue in their repository?
