### ISSUE TITLE
Images are broken in build version and console has errors like 'Missing resources for /'

### ISSUE THREAD

**Issue by ivanshinkarenko** [gatsbyjs/gatsby#14953]
On http://localhost:8000/ everything works properly but after deploy build version all images just displays with blur effect and blur doesn't disappear at all
<img width="467" alt="blur" src="https://user-images.githubusercontent.com/43337798/59836260-d5cc1080-9353-11e9-9753-eee9d4e03b44.png">

Also console has these errors('Missing resources'):
<img width="295" alt="errors" src="https://user-images.githubusercontent.com/43337798/59836354-08760900-9354-11e9-8fdf-20a6babf821f.png">

### Environment (if relevant)

 System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1
  npmPackages:
    gatsby: ^2.9.9 => 2.9.11
    gatsby-background-image: ^0.7.2 => 0.7.2
    gatsby-image: ^2.1.4 => 2.1.4
    gatsby-plugin-compile-es6-packages: ^1.1.0 => 1.1.0
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.3 => 2.1.3
    gatsby-plugin-prefetch-google-fonts: ^1.4.2 => 1.4.2
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.1.5 => 2.1.5
    gatsby-plugin-typography: ^2.2.13 => 2.2.13
    gatsby-remark-images: ^3.0.16 => 3.0.16
    gatsby-remark-relative-images: ^0.2.2 => 0.2.2
    gatsby-source-filesystem: ^2.0.39 => 2.0.39
    gatsby-transformer-json: ^2.1.11 => 2.1.11
    gatsby-transformer-remark: ^2.4.0 => 2.4.0
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.6.5

### File contents (if changed)

`gatsby-config.js`: 

 ```
plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: "gatsby-source-filesystem",
      options: {
        path: `${__dirname}/src/images`,
        name: "images",
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content`,
        name: `markdown`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: "gatsby-remark-relative-images",
          },
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 590,
            },
          },
        ],
      },
    },

    `gatsby-plugin-sass`,
    `gatsby-transformer-json`,
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `${__dirname}/src/utils/typography`,
      },
    },
    {
      resolve: `gatsby-plugin-compile-es6-packages`,
      options: {
        modules: [`gatsby-background-image`],
      },
    },
```
`package.json`: 

```
{
  "dependencies": {
    "babel-eslint": "^8.2.6",
    "eslint-config-prettier": "^5.0.0",
    "eslint-plugin-graphql": "^3.0.3",
    "gatsby": "^2.9.9",
    "gatsby-background-image": "^0.7.2",
    "gatsby-image": "^2.1.4",
    "gatsby-plugin-compile-es6-packages": "^1.1.0",
    "gatsby-plugin-manifest": "^2.1.1",
    "gatsby-plugin-offline": "^2.1.3",
    "gatsby-plugin-prefetch-google-fonts": "^1.4.2",
    "gatsby-plugin-react-helmet": "^3.0.12",
    "gatsby-plugin-sass": "^2.0.11",
    "gatsby-plugin-sharp": "^2.1.5",
    "gatsby-plugin-typography": "^2.2.13",
    "gatsby-remark-images": "^3.0.16",
    "gatsby-remark-relative-images": "^0.2.2",
    "gatsby-source-filesystem": "^2.0.39",
    "gatsby-transformer-json": "^2.1.11",
    "gatsby-transformer-remark": "^2.4.0",
    "gatsby-transformer-sharp": "^2.1.21",
    "intersection-observer": "^0.7.0",
    "node-sass": "^4.12.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1",
    "react-typography": "^0.16.19",
    "typography": "^0.16.19"
  },
  "devDependencies": {
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.13.0",
    "prettier": "^1.18.2"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write src/**/*.{js,jsx}",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\""
  },
  
}
```

`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by subpopular** [comment]
Running into the same issue right now with latest Gatsby when deploying to Netlify.

**Comment by ThermalIDTechnologies** [comment]
I am also experiencing this. As well as blank pages on page refreshes :(

**Comment by juddey** [comment]
This is an issue for me also, but running straight from build dir with local webserver (whihch I understand you can do)
 Heres a shot of my deps:
```
  "dependencies": {
    "gatsby": "^2.9.4",
    "gatsby-background-image": "^0.7.2",
    "gatsby-image": "^2.1.4",
    "gatsby-plugin-manifest": "^2.1.1",
    "gatsby-plugin-offline": "^2.1.3",
    "gatsby-plugin-react-helmet": "^3.0.12",
    "gatsby-plugin-sharp": "^2.1.5",
    "gatsby-source-filesystem": "^2.0.39",
    "gatsby-transformer-sharp": "^2.1.21",
    "intersection-observer": "^0.7.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1",
    "styled-components": "^4.3.1",
    "typeface-nunito": "^0.0.72"
  },
```

**Comment by dontdomilk** [comment]
Also running into this issue. It works in my local environment, sourcing from the same CMS, but for some reason my deploys on Netlify are missing about half of my images (returning 404). I'm not using base64 so they just look like blank spaces.

For what it's worth, here are my dependencies (from gatsby info): 

npmPackages:
    gatsby: ^2.10.5 => 2.12.0 
    gatsby-image: ^2.0.34 => 2.2.3 
    gatsby-plugin-google-gtag: ^1.0.17 => 1.1.0 
    gatsby-plugin-manifest: ^2.0.24 => 2.2.0 
    gatsby-plugin-netlify: ^2.0.17 => 2.1.0 
    gatsby-plugin-offline: ^2.0.25 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.0.11 => 3.1.0 
    gatsby-plugin-remote-images: ^1.0.1 => 1.0.3 
    gatsby-plugin-sass: ^2.0.11 => 2.1.0 
    gatsby-plugin-sharp: ^2.0.31 => 2.2.1 
    gatsby-plugin-sitemap: ^2.1.0 => 2.2.1 
    gatsby-source-filesystem: ^2.0.28 => 2.1.1 
    gatsby-source-marketo: ^1.0.2 => 1.0.2 
    gatsby-source-wordpress: ^3.0.49 => 3.1.2 
    gatsby-transformer-sharp: ^2.1.17 => 2.2.0 
  npmGlobalPackages:
    gatsby-cli: 2.5.0

**Comment by juddey** [comment]
I eventually wound up rolling back to 2.8.8, seems to work with that version. ymmv.

**Comment by jschlechte** [comment]
@juddey -- Thanks for the tip! Rolling back to 2.8.8 also resolved this issue for me. I was seeing it on Amazon S3 for every single page prior to the rollback!

I hope this gets a fix soon!

**Comment by MaximeHeckel** [comment]
I'm having the same exact issue on https://maximeheckel.com I'd like to know if there's a fix for the latest versions of gatsby
Note I'm getting the following during the build time:
```
(sharp:1578): GLib-CRITICAL **: 01:49:14.787: g_hash_table_lookup: assertion 'hash_table != NULL' failed
6:49:16 PM: (sharp:1578): GLib-CRITICAL **: 01:49:16.138: g_hash_table_lookup: assertion 'hash_table != NULL' failed
6:49:18 PM: (sharp:1578): GLib-CRITICAL **: 01:49:18.403: g_hash_table_lookup: assertion 'hash_table != NULL' failed
```

And if you load my site you can see that I actually have 3 images not loading so I guess it's linked (?). Netlify builds have been a bit flaky for me recently

**Comment by MaximeHeckel** [comment]
I updated `gastby-plugin-sharp` to `^2.2.10` and it fixed the issue I had with Netlify not loading my "gatsby-images" 🎉 
Let me know if this helps
