### ISSUE TITLE
Gatsby Issue with Google Web cache

### ISSUE THREAD

**Issue by ramsunvtech** [gatsbyjs/gatsby#14964]
## Description

Gatsby pointing to 404 page when Google Web cache tried to open.

### Steps to reproduce

http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fwww.loanabull.com%2F&rlz=1C1CHBF_enIN768IN768&oq=cache%3Ahttps%3A%2F%2Fwww.loanabull.com%2F&aqs=chrome..69i57j69i58j69i60l3j69i59.2078j0j4&sourceid=chrome&ie=UTF-8

### Expected result

Gatsby should route to the right page.

### Actual result

What happened.
![image](https://user-images.githubusercontent.com/1652629/59855112-e5287980-93a6-11e9-959f-f542a0242783.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

gatsby info --clipboard

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz
  Binaries:
    Yarn: 1.12.3 - C:\Program Files\nodejs\yarn.CMD
    npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.14 - /c/Python27/python
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277
    gatsby-link: ^1.6.46 => 1.6.46
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6
    gatsby-plugin-layout: ^1.0.15 => 1.0.15
    gatsby-plugin-material-ui: ^2.0.1 => 2.0.1
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11

I see this issue every gatsby site - http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fsharemeals.org%2F&rlz=1C1CHBF_enIN768IN768&oq=cache%3Ahttps%3A%2F%2Fsharemeals.org%2F&aqs=chrome..69i57j69i58j69i59j69i60l2.4943j0j4&sourceid=chrome&ie=UTF-8

**Comment by marcysutton** [comment]
i can reproduce that as well when I look at my own site on the Web Archive...it even takes over old versions.

**Comment by ramsunvtech** [comment]
Team, Any update on this issue in SEO

**Comment by marcysutton** [comment]
@sidharthachatterjee you self-assigned, can you take a look?

**Comment by ramsunvtech** [comment]
can u anyone have solution for this known issue ??? @marcysutton / @sidharthachatterjee

**Comment by LekoArts** [comment]
Closing as stale
