### ISSUE TITLE
Expand PR bot to identify PRs for the Learning team

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#14968]
## Summary

Update the [high priority PRs action]( https://github.com/gatsbyjs/gatsby/tree/master/.github/actions/high-priority-prs) to identify documentation and blog post PRs that need reviewing, then post them to the #docs-issues channel in Slack.

### Motivation

Help team members identify which PRs need attention first.

**Comment by gillkyle** [comment]
Closed by #15194
