### ISSUE TITLE
gatsby-remark-copy-files plugin?

### ISSUE THREAD

**Issue by chiedo** [gatsbyjs/gatsby#1497]
Currently the gatsby-remark-images plugin is awesome on small sites.

**Problems i ran into:**

When I tried it on a site with 200 markdown pages I ran into issues:
- it would take longer than I would like it to.
- the plugin would ruin the way pages displayed due to the extra markup it added and by requiring every image it processes to be the size of the `maxWidth` variable.

I wanted a plugin to stay out of the way, have limited opinions and just make sure my images work without any changes.

**My solution**

I wrote a plugin that only does the following (I use [this approach](https://labs.chiedo.com/blog/automatically-optimizing-images-with-each-git-commit/) to optimize images only when they're committed so it doesn't have to happen over and over again):
- Copies the images from the source to the static folder with the name being the unique hash.

**My question**

Is this a plugin you'd want pull requested as it's own plugin or as part of the gatsby-remark-images plugin. If as part of the gatsby-remark-images plugin, I could just add an option for `simpleMode` or something.

Currently I am using it as a local plugin.

**Comment by KyleAMathews** [comment]
It sounds like you just want https://www.gatsbyjs.org/docs/packages/gatsby-remark-copy-linked-files/ but that copies images too?

**Comment by chiedo** [comment]
Hey @KyleAMathews 

Yep!

To stay true to the name, I think `gatsby-copy-linked-files` should only copy linked files via a tags and markdown links.

Then a plugin called gatsby-remark-copy-images should be it's own plugin that copies all images. It should have an option for `ignoreFileTypes` that you could use to make it ignore png and jpegs if you're using it alongside the `gatsby-remark-images` plugin.

Thoughts?

**Comment by chiedo** [comment]
Thinking about this further, 

I ran into a situation where I had a `<video>` loading `video.mp4` that wouldn't work for obvious reasons.

I'm assuming that people with Markdown would want a plugin called `gatsby-remark-copy-files` that copied all local files referenced in markdown and replaced the reference with a hash. This would support `img`, `a` and `video` tags by default. And other tag types could be added to the "to support" list.

The plugin would have a `ignoreFileTypes` or `onlyFileTypes` option which would allow it to be used hand in hand with the `gatsby-remark-images` plugin.

When I first started working with 1.0, my thought was just that I wanted my markdown references to work. I'm imagining others would have the same thought process without thinking about side effects etc.

If this sounds like a good idea to you, let me know and I'll work on it.

**Comment by KyleAMathews** [comment]
Yeah, adding support for an option called `ignoreFileExtensions` which takes an array of file extensions w/o dots should work. And by default it's setup to work with gatsby-remark-images so ignores all the image types support by Sharp.

**Comment by chiedo** [comment]
Awesome @KyleAMathews so just to be clear, you're good with me creating a new plugin or do you want me to add to gatsby-remark-copy-linked-files?

**Comment by KyleAMathews** [comment]
>do you want me to add to gatsby-remark-copy-linked-files?

Yes this, it'd be confusing otherwise as the two plugins would be doing basically the same thing.

**Comment by chiedo** [comment]
Deal
