### ISSUE TITLE
Hot reloading kills gatsby process

### ISSUE THREAD

**Issue by ybv** [gatsbyjs/gatsby#14971]
## Description

As a part of regular housekeeping for [this](https://github.com/WeOpenly/localgov.fyi) I've updated `gatsby` from `2.1.18` to `2.9.11` along with other libraries. Hot reloading seems to kill the `gatsby` process upon changes to the source.

### Steps to reproduce
```
git clone --single-branch --branch  new-v-updates https://github.com/WeOpenly/localgov.fyi.git
npm install
gatsby develop
```
change any file and save

### Expected result

Hot reloading happens without any "side effects"

### Actual result

`gatsby` process is killed with 

```
2655 pages                                                   localgov-fyi-gatsby
error UNHANDLED REJECTION


  FetchError: request to http://localhost:8000/___graphql failed, reason: connec
  t ECONNRESET 127.0.0.1:8000

  - index.js:1455 ClientRequest.<anonymous>
    [localgov.fyi_frontend]/[gatsby]/[node-fetch]/lib/index.js:1455:11

  - destroy.js:64 emitErrorNT
    internal/streams/destroy.js:64:8

  - next_tick.js:138 _combinedTickCallback
    internal/process/next_tick.js:138:11

  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9
```

### Environment

```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.5.1 - ~/.yarn/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.14 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.0
  npmPackages:
    gatsby: ^2.9.11 => 2.10.0
    gatsby-image: ^2.1.4 => 2.2.0
    gatsby-link: ^2.1.1 => 2.2.0
    gatsby-plugin-brotli: ^1.1.2 => 1.1.2
    gatsby-plugin-create-client-paths: ^2.0.5 => 2.1.0
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6
    gatsby-plugin-layout: ^1.0.15 => 1.1.0
    gatsby-plugin-manifest: ^2.1.1 => 2.2.0
    gatsby-plugin-material-ui: ^2.0.1 => 2.0.1
    gatsby-plugin-netlify: ^2.0.17 => 2.1.0
    gatsby-plugin-nprogress: ^2.0.10 => 2.1.0
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.4.0 => 1.4.0
    gatsby-plugin-sharp: ^2.1.9 => 2.2.0
    gatsby-plugin-sitemap: ^2.1.0 => 2.2.0
    gatsby-source-filesystem: ^2.0.43 => 2.1.0
    gatsby-transformer-json: ^2.1.11 => 2.2.0
    gatsby-transformer-remark: ^2.4.0 => 2.5.0
    gatsby-transformer-sharp: ^2.1.21 => 2.2.0
  npmGlobalPackages:
    gatsby-cli: 2.7.0
    gatsby: 2.0.25
```

**Comment by ybv** [comment]
May be related to 13918?

**Comment by ybv** [comment]
@sidharthachatterjee @pieh 
Sorry about the ping, just wanted to be sure I'm not doing something obviously stupid before ditching upgrade plans.

**Comment by sidharthachatterjee** [comment]
@ybv Thank you for opening this! The repo you linked to seems to miss the `/data/orgs` folder that isn't letting me run gatsby. 

Could you please link to a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)? Thanks!

**Comment by ybv** [comment]
@sidharthachatterjee Ah, sorry about that. Let me check in that folder.

**Comment by ybv** [comment]
@sidharthachatterjee I was able to run without issues after I downgraded to`Material-UI v3`, Looks like this is not a Gatsby issue. Sorry about the false ping, thanks for looking into this!

**Comment by mduecker** [comment]
I have the same problem: gatsby develop crashes every time I make a change to my project during hot reloading with the following error:

> UNHANDLED REJECTION request to https://localhost:8000/___graphql failed, reason: getaddrinfo ENOTFOUND localhost localhost:8000

>  FetchError: request to https://localhost:8000/___graphql failed, reason: getaddrinfo ENOTFOUND localhost localhost:8000

I already tried removing the node_modules folder, reinstalling packages, switching to a different node version, ...
If this is a problem with one of my packages, I don't know how to identify the one that's causing it.

**Comment by sidharthachatterjee** [comment]
@mduecker Is your repository public? Or you do have a minimal reproductive?
