### ISSUE TITLE
[docs][recipes] using StaticQuery in components

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14979]
## Summary

To improve key learning workflows in the Recipes section of the docs, there should be a short, actionable recipe on using StaticQuery for data in components with GraphQL, with a slight learning team preference for the `useStaticQuery` hook for readability. See also: #14977 for a page query recipe.

This recipe should show how to write a staticQuery and provide the returned data to a component _inline_ as concisely as possible. It should briefly describe when someone would need a static query vs other kinds of queries and include code snippets.

Recipes now follow this format:

- Requirements or prerequisites 
- Step-by-step instructions
- Relevant links to any relevant information
    - More on Static Query for querying data in components: https://www.gatsbyjs.org/docs/static-query/
    - The difference between a static query and a page query https://www.gatsbyjs.org/docs/static-query/#how-staticquery-differs-from-page-query
    - More on the useStaticQuery hook https://www.gatsbyjs.org/docs/use-static-query/
    - Link to a live example

This recipe should go into the "Querying data" section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md), replacing the existing text. There is a recipe template in the contributing docs: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by juhosa** [comment]
Hey @marcysutton, I can tackle this issue 👍🏽

**Comment by marcysutton** [comment]
Closed with #15079. Thank you @juhosa!!
