### ISSUE TITLE
[docs][recipes] Sourcing Content: directly importing data (json & yaml)

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14976]
## Summary

To improve key learning workflows in the Recipes section of the docs, there should be an actionable recipe on directly importing simple JSON and YAML data without GraphQL. 

From @KyleAMathews in https://github.com/gatsbyjs/gatsby/issues/11130: "We should emphasize that hard-coded data can be directly imported and that graphql is only necessary when you want db-like functionality e.g. filtering, sorting, pulling bits of data from connected data, and transforming data (images, markdown, dates, etc.)."

This recipe should show how to import JSON and/or YAML data and use it in a component as concisely as possible. There would be a code snippet like `const data = require('../data/cool-data.json')` and an example of how to consume it.

Recipes now follow this format:

- Requirements or prerequisites 
- Step-by-step instructions
- Relevant links to any relevant information
    - Using Gatsby without GraphQL https://www.gatsbyjs.org/docs/using-gatsby-without-graphql/
    - Link to a live example if not already embedded

This recipe should go into a new section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md) titled "Sourcing Content" (if it hasn't already been created). There is a recipe template in the contributing docs, including tips on adding a new section: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by jonniebigodes** [comment]
@marcysutton sorry for the radio silence. But if you don't mind as most of the work is already done for this workflow in #12634 , more specifically in the file `sourcing-content-from-json-or-yaml.md`. Probably the only thing needed is to make some adjustments in the example and wording and this will good to be merged. 

Feel free to provide feedback

**Comment by marcysutton** [comment]
@jonniebigodes this format is slightly different than a tutorial–it would need to be trimmed down to meet the parameters outlined above. But your work is definitely a good starting point!

**Comment by marcysutton** [comment]
Closed with #15812.
