### ISSUE TITLE
[gatsby-plugin-styled-components] Styled components delayed css loading in build

### ISSUE THREAD

**Issue by alexanderwe** [gatsbyjs/gatsby#14978]
## Description

Currently I am facing an issue with styled-components in a production Gatsby site. It is similar to the following issue: https://github.com/gatsbyjs/gatsby/issues/9902 and others. Unfortunately none of those issues contained information that helped me to fix the issue.

I am developing a Gatsby theme with styled-components which then is used by my personal blog site. Both projects (theme and site) are located in the same directory and linked via yarn workspaces. When I develop with `gatsby develop` everything is working fine, but when I run `gatsby build && gatsby serve` I experience the weird behaviour of my styles being loaded shortly after site has loaded. Something around the 100ms to 300ms mark. What I read in similar issues is that it has something to do with css styles not being injected into the generated HTML. Unfortunately adding `gatsby-plugin-styled-components` to the theme project did not solve the problem for me. The issue still persists. Are there any hints what could be wrong ? 

### Steps to reproduce

I created a demo project at https://github.com/alexanderwe/gatsby-styled-components-test which is a trimmed down version of my real project. 

- Clone the project
- Run `yarn install`
- Run `yarn workspace site serve` (will built and serve the site)

### Expected result

Page should load with css injected into HTML without being loaded shortly after the page has loaded.

### Actual result

Labels are moving to the correct position on the page shortly after the page has loaded indicating the delayed loading of the css. Sometimes multiple reloads are needed to see the effect since it is very fast. 

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /var/folders/8g/thhx4y056s92_s9xqfytf6ww0000gn/T/yarn--1561055300499-0.2759144333476431/node
    Yarn: 1.17.0 - /var/folders/8g/thhx4y056s92_s9xqfytf6ww0000gn/T/yarn--1561055300499-0.2759144333476431/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 67.0.3
    Safari: 12.1.1
```

**Comment by alexanderwe** [comment]
**Small update:** It seems that only components are affected which are not "pages". For example using styled components inside a `layout.js` causing the styles to be loaded delayed. But using styled-components inside `./src/pages/index.js` everything is working fine

**Comment by alexanderwe** [comment]
I recently resolved the issue - It seems that I had an error inside my `wrapPageElement.js` inside the theme directory. After switching to https://www.gatsbyjs.org/packages/gatsby-plugin-layout/ the issue was resolved. Since the plugin is just mimicking the `wrapPageElement` I assume the error is in my implementation.

**Comment by hayyaun** [comment]
In my case, `gatsby-plugin-minify` was making this problem, which led the production build to reload all styles after a page was loaded completely in the production build.
