### ISSUE TITLE
[docs][recipes] Images: querying with GraphQL and gatsby-image

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14989]
## Summary

To improve key learning workflows in the Recipes section of the docs, there should be a short, actionable recipe on querying for images with gatsby-image. This should come after #14985 and #14986.

This recipe should briefly mention the benefits of Gatsby's data layer and show how to query for an image with GraphQL _inline_ as concisely as possible. It should include code snippets and potentially an embedded example. The [Gatsby Image doc](https://www.gatsbyjs.org/docs/gatsby-image/) and other [image docs](https://www.gatsbyjs.org/docs/using-gatsby-image/) can be used for reference.

Because the various methods we want to show for images are such small tweaks (and would carry a lot of boilerplate if all broken out individually), this issue covers multiple variations that can be slotted into the "Step-by-step instructions" part of the recipe.

Recipes now follow this format:

- Requirements or prerequisites 
- Step-by-step instructions
- Relevant links to any relevant information
    - Gatsby Image API https://www.gatsbyjs.org/docs/gatsby-image/
    - Using Gatsby Image https://www.gatsbyjs.org/docs/using-gatsby-image/
    - More on working with images in Gatsby https://www.gatsbyjs.org/docs/working-with-images/
    - Link to a live example

Techniques this issue should cover: 
- [ ] Querying by relativePath
- [ ] from a directory
- [ ] from post frontmatter
- [ ] fixed width and height
- [ ] fixed maxWidth
- [ ] fluid maxWidth and quality
- [ ] fluid but limited by height
- [ ] with inline styles applied
- [ ] with a fragment like `GatsbyImageSharpFixed`
- [ ] preserving an aspectRatio

These recipes should go into a new section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md) titled "Images"  (if it isn't already created). There is a recipe template in the contributing docs, including tips on adding a new section: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by gillkyle** [comment]
On our info in the [Gatsby Image API](https://www.gatsbyjs.org/docs/gatsby-image/#fixed-image-query-parameters), there isn't an option to pass in a `maxWidth` with a `fixed` image, does that mean that example should show how you can constrain a `gatsby-image` by passing a style prop or something? Or maybe it should be an example for fluid images?

**Comment by marcysutton** [comment]
That could easily be changed to a fluid image example - whatever works! I think my original intent was to show how to constrain a fixed image so it wouldn't scale up with its container element and thus appear blurry. But if that situation doesn't apply, don't worry about it! (I'd have to dig back into gatsby-image to know)
