### ISSUE TITLE
Waste of time

### ISSUE THREAD

**Issue by jhabdas** [gatsbyjs/gatsby#1498]
JS will never be fast. End the hype. Go Hugo

**Comment by jquense** [comment]
Speaking of a waste of time...

**Comment by KyleAMathews** [comment]
Congratulations, you win the dubious honor of being the first person to be blocked from the gatsbyjs org.

**Comment by jhabdas** [comment]
Sorry all for my transgressions. I was outside of myself when I opened this issue. And I want to thank Kyle for personally taking the time to hear me out.

I believe Gatsby to be the likely front-runner next to Hugo within the next year, each with their own strengths and weaknesses. And I look forward to porting my namesake blog https://habd.as to Gatsby in the near future and writing a tutorial similar to one of the following:

https://habd.as/zero-to-http-2-aws-hugo/
https://habd.as/pagespeed-100-with-jekyll-s3-and-cloudfront/
https://habd.as/simple-websites-jekyll-docker/

Cheer and thank you Kyle for keeping an open mind.
