### ISSUE TITLE
[docs][recipes] transform Markdown with gatsby-transformer-remark 

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#14992]
## Summary

To improve key learning workflows in the Recipes section of the docs, there should be a short, actionable recipe on transforming Markdown with `gatsby-transformer-remark`. This should be slightly different than the Sourcing from Markdown recipes in #14946 and #14947 to show transforming of data, specifically.  From [tutorial part six](https://www.gatsbyjs.org/tutorial/part-six/#transformer-plugins): 

> Source plugins bring data into Gatsby’s data system and transformer plugins transform raw content brought by source plugins.

This recipe briefly explain why you might want to transform data and should show how to do it _inline_ as concisely as possible. It should include code snippets and most likely, an embedded [GraphiQL interface](https://www.gatsbyjs.org/docs/graphql-reference/#basic-query) to play around with.

Recipes now follow this format:

- Requirements or prerequisites 
- Step-by-step instructions
- Relevant links to any relevant information
    - Tutorial part six: transformer plugins https://www.gatsbyjs.org/tutorial/part-six/#transformer-plugins
    - GraphQL reference guide https://www.gatsbyjs.org/docs/graphql-reference/
    - README for `gatsby-transformer-remark` https://www.gatsbyjs.org/packages/gatsby-transformer-remark/
    - Link to a live example if not already embedded

This recipe should go into the "Transforming data" section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md), replacing the existing text. There is a recipe template in the contributing docs: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by mehtavishwa30** [comment]
Hey @marcysutton!
Is this issue open for contributors? I went through the Recipes and would like to work on this particular page for transforming Markdown with `gatsby-transformer-remark`.

**Comment by marcysutton** [comment]
@mehtavishwa30 yes it is! We would love to have your contribution.

**Comment by mehtavishwa30** [comment]
Ahh, sweet! Looking forward to submitting a PR soon. 
Thanks!
