### ISSUE TITLE
Copy button to copy code from the documentation

### ISSUE THREAD

**Issue by bcye** [gatsbyjs/gatsby#14998]
## Summary

A lot of documentation sites have the ability to copy the shown code with a button. (Instead of needing to highlight the code and then press Ctrl+C)

### Basic example

N/A

### Motivation

* Make it easier to learn Gatsby
* Code has the correct formatting (when highlighting code and copying it, sometimes the code doesn't get formatted right by the text editor)

**Comment by lannonbr** [comment]
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/5030. Closing
