### ISSUE TITLE
FEATURE: minify HTML when building site

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#150]
Using https://www.npmjs.com/package/html-minifier

Saves some kilobytes. Test how much extra time it adds to builds.

Add it `static-entry.js`

**Comment by KyleAMathews** [comment]
Hmmm... this might not save us much. Running a ~30kb html file through this then comparing the gzipped minified/non-minified version showed a difference of 160 bytes...

A byte is a byte though... and minifying is really fast. I'll leave this open for a while. If anyone else experiments with this, please report in on your findings.

**Comment by KyleAMathews** [comment]
Not a big deal especially since React renders minified HTML output on the server already. Someone could implement this as a plugin in the future though.

**Comment by brianjd** [comment]
@KyleAMathews How would this be implemented as a plugin?  Wouldn't html-minifier have to wrap renderToStaticMarkup [here](https://github.com/gatsbyjs/gatsby/blob/e1f1a9864f9b88ca33710f7b5fa837f5153a786d/packages/gatsby/cache-dir/static-entry.js#L371)?

**Comment by nsisodiya** [comment]
@KyleAMathews I built a plugin for HTML minification. https://github.com/nsisodiya/gatsby-plugin-html-minifier. https://gtmetrix.com reports are better now.

**Comment by KyleAMathews** [comment]
Nice!
