### ISSUE TITLE
SCSS modules in Gatsby Themes

### ISSUE THREAD

**Issue by gvocale** [gatsbyjs/gatsby#15007]
I have created a Gatsby Theme out of a project and I have imported it into a new blank Gatsby project. On gatsby develop I am running into the error 
`WebpackError: ./node_modules/gatsby-theme-name/src/components/ComponentName/styles.module.scss`.

Do I need to change the import path of each scss, similar to how I needed to change paths into `require.resolve...`?

I am currently importing scss in each react component in my theme via
`import * as styles from "./styles.module.scss"` .

Thanks

**Comment by MassivDash** [comment]
You need to have sass and css modules plugins installed on your gatsby project. 

According to official docs, you should import your files: 
import containerStyles from "./container.module.css"

<div className={containerStyles.container}></div>

**Comment by gvocale** [comment]
Seems that Gatsby works with CSS Modules by default, I didn't have to install a plugin for it in my Gatsby site. 
My theme includes in its dependencies:
```
"node-sass": "^4.12.0",
"gatsby-plugin-sass": "^2.0.11",
```
I have tried to add the same dependencies manually in the gatsby site that is consuming that theme, but now luck. I still get `WebpackError: ./node_modules/gatsby-theme-memoriestoriche/src/components/CustomHits/styles.module.scss`

**Comment by gvocale** [comment]
I have also tried cloning these gatsby theme examples https://github.com/ChristopherBiscardi/gatsby-theme-examples to see how they handle CSS, but none of them uses css files, or sass or css modules. They all seem to use inlined css.

**Comment by polishedwp** [comment]
You need the following packages I believe:
`npm install --save node-sass gatsby-plugin-sass`

Refer to [gatsby-plugin-sass](https://www.gatsbyjs.org/packages/gatsby-plugin-sass/?=sass#gatsby-plugin-sass)

**Comment by gvocale** [comment]
Yep, I have both installed, but still the issue persists.

**Comment by gvocale** [comment]
Sorry, my bad. I just found out css modules is not the issue. I was creating a reproducible test case Gatsby theme with just one component using CSS modules, and it actually worked correctly out of the box. My issue then is somewhere else within the larger original site.

**Comment by gvocale** [comment]
In case anyone else runs in a similar problem, I believe the issue is I was importing some global css from `component.module.scss` via
`@import './src/styles/breakpoints/index';`

Instead I needed to import it with
`@import '../../styles/breakpoints/index';`
