### ISSUE TITLE
Support the ability to use local node_modules

### ISSUE THREAD

**Issue by lourd** [gatsbyjs/gatsby#15006]
## Summary

As inspired by [Rich Harris's tweet](https://twitter.com/Rich_Harris/status/1139908960520220677), it should be possible to use a local `node_modules` directory in `src` for simpler importing without having to use a custom plugin.

### Basic example

See https://github.com/lourd/gatsby-local-node_modules-bug for a simple reproduction. The first error to pop up when running the example is:

```
error ✖ ｢wdm｣:
ERROR in ./src/node_modules/components/world.js 4:11
Module parse failed: Unexpected token (4:11)
You may need an appropriate loader to handle this file type.
|
| export default function World() {
>     return <h1>World!</h1>
| }
|
```

### Motivation

Less bespoke configuration and IDE integration for Gatsby to worry about.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @lourd 

It seems like this is a pretty niche use case. Gatsby has a reasonably opinionated config and I'm not sure if supporting this is worth the change. 

Can you elaborate on why you think this would be useful? 

Related to https://github.com/gatsbyjs/gatsby/issues/12342

**Comment by lourd** [comment]
Hey @sidharthachatterjee. Pleasure to meet you.

The main objective for seeing this supported is needing less configuration for importing local modules. Having it would eliminate the need for the gatsby-plugin-root-import plugin, as well the additional configuration for IDEs and linters to support importing modules from a root path. That plugin has about 7,000 weekly installs, with roughly 30% month-over-month growth, so it seems like this is a challenge that many Gatsby users are facing, and a feature that many users would appreciate.

**Comment by wardpeet** [comment]
@lourd we have support for inner node_modules. It's not a gatsby feature but a nodejs feature. One thing we don't have support for is node_modules transpilation. You can fix that by using `https://www.gatsbyjs.org/docs/node-apis/#onCreateWebpackConfig`. You'll still have editor support.


This works without transpilation:

```
import React from 'react';

export default () => {
  return React.createElement('h1', {}, 'world'}
}
```

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
