### ISSUE TITLE
Update graphiql to fix "failed to advance stream" bug

### ISSUE THREAD

**Issue by robinmetral** [gatsbyjs/gatsby#15021]
## Summary

A long-time [graphiql bug](https://github.com/graphql/graphiql/issues/735) is causing the [`gatsby-graphiql-explorer`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-graphiql-explorer) to freeze for some users when accidentally typing option-space instead of ctrl-space.

This was fixed by graphiql in version 0.13.1 and published to npm in version 0.13.2.

Currently `gatsby-graphiql-explorer` uses version 0.13.0:
https://github.com/gatsbyjs/gatsby/blob/8df6f299db04fd875cf6d7d8193899ac53be6815/packages/gatsby-graphiql-explorer/package.json#L43

Should we update the dependency manually? Or will the renovate bot take care of it? I'm eager to see this fixed in the `gatsby-graphiql-explorer` :slightly_smiling_face: 

## Relevant information

Issue regarding the bug on the graphiql repo: https://github.com/graphql/graphiql/issues/735

**Comment by sidharthachatterjee** [comment]
> Should we update the dependency manually? Or will the renovate bot take care of it?

Renovate currently only updates packages for our starters. Do you want to open a PR updating this? 

Thank you for pointing this out, @robinmetral 💪 💜

**Comment by robinmetral** [comment]
I'd love to @sidharthachatterjee! I'll upgrade locally, test it on my end and open a PR if it looks good :slightly_smiling_face:

**Comment by robinmetral** [comment]
Unfortunately I think the issue wasn't fixed with the new `graphiql@0.13.2` version: I'm still getting the bug.

Could anybody see if you can replicate?

**Steps:**
1. `gatsby new super-cool-site`
2. `cd super-cool-site`
3. `gatsby develop`
4. visit http://localhost:8000/___graphql
5. deliberately type `option+space` (or `alt+space`) instead of `cmd+space`
6. does GraphiQL freeze?

**Comment by kindavishal** [comment]
Hi, I would like to help out here (if needed), if someone would be up to mentor me through this.

**Comment by robinmetral** [comment]
Update: `graphiql@0.14.0`, released today, fixed the issue :tada: ([thread](https://github.com/graphql/graphiql/issues/735#issuecomment-522428215))

@kindavishal this is a very simple fix, we have to upgrade our `graphiql` dependency to the latest (0.14.2) and make sure it works.

Can you reproduce the issue in your environment? If you can, feel free to pick it up. I can help you with it if needed. Otherwise I'll do it, because we need to be able to reproduce the issue in the first place to make sure we're actually fixing it.

**Comment by kindavishal** [comment]
On it @robinmetral!

**Comment by kindavishal** [comment]
Hey! I tried to reproduce this locally, I don't find any issue in GraphiQl, tried with:

  | Ubuntu/Firefox | 
-- | -- |
Command + Space | Does nothing  | 
Control + Space | Ubuntu shortcut (Launches Synapse) |  
Alt/Option Right + Space | Ubuntu shortcut (window menu)  |  
Alt/Option Left + Space | Ubuntu shortcut (window menu) | 

Version details:
Firefox: 68.0.2
OS: Ubuntu (LXDE)
Gatsby CLI version: 2.7.34
Gatsby version: 2.13.73

I don't know how to check the version of GraphiQl, you think that could be the issue?

**Comment by robinmetral** [comment]
@kindavishal can you reproduce the bug with [this query](http://localhost:8000/___graphql?query=%7B%0A%20%20allFilms%20%7B%0A%20%20%20%20title%C2%A0%0A%20%20%7D%0A%7D)? (the blank page is expected, check your console for the error message)

**Comment by kindavishal** [comment]
Okay! That did give a blank page with ```Error: "Mode graphql failed to advance stream."```
Are we talking about GraphQL Playground or GraphiQL?
I get the error in Playground and not in GraphiQL

**Comment by robinmetral** [comment]
@kindavishal the IDE you see when you visit `http://localhost:8000/___graphql` on a Gatsby site in development is GraphiQL, does this answer your question?

**Comment by kindavishal** [comment]
Image 1: GraphQL Playground (Gives error)
![image](https://user-images.githubusercontent.com/35860774/63453421-42ec4700-c466-11e9-9ce7-972d4532f11a.png)


Image 2: GraphiQL, the default one (doesn't give error)
![image](https://user-images.githubusercontent.com/35860774/63453457-55668080-c466-11e9-90b8-ddceda64fef4.png)

**Comment by robinmetral** [comment]
Oh, I didn't know that you could choose to [use Prisma's GraphQL Playground](https://www.gatsbyjs.org/docs/using-graphql-playground/) over GraphiQL!

Since GraphQL Playground uses GraphiQL in the background, the issue would need to be fixed [over there](https://github.com/prisma/graphql-playground/tree/master/packages/graphql-playground-react) (they're still using `0.11.x`).

And there's no bug in Gatsby's GraphiQL because... the package was upgraded by the renovate bot yesterday :tada: 

https://github.com/gatsbyjs/gatsby/blob/ca40de73b2c3326558a57093f79d5e3d38f381a4/packages/gatsby-graphiql-explorer/package.json#L44

Closing the issue, thanks for offering your help @kindavishal
