### ISSUE TITLE
Is there a way to rename the filenames of Gatsby-generated JavaScript?

### ISSUE THREAD

**Issue by maxcountryman** [gatsbyjs/gatsby#15023]
In particular I'm interested in filtering specific words that occur as part of component names in some of the generated JavaScript files.

Is there a way to do this with Gatsby?

**Comment by sidharthachatterjee** [comment]
Hey @maxcountryman 

> Is there a way to rename the filenames of Gatsby-generated JavaScript?

Currently, there isn't. Gatsby _owns_ these files during the build process and ideally, we shouldn't have to be concerned about them 🙂

> In particular I'm interested in filtering specific words that occur as part of component names in some of the generated JavaScript files.

Can you elaborate on why you'd like to do this in case I'm missing out on something? Thanks!

**Comment by maxcountryman** [comment]
> Currently, there isn't. Gatsby owns these files during the build process and ideally, we shouldn't have to be concerned about them

I agree that's the ideal case, nonetheless it would be nice to have some configurable control over how these files are named, even if it's just basic obfuscation.

> Can you elaborate on why you'd like to do this in case I'm missing out on something? Thanks!

I'm sure there are any number of reasons, but among the most important in our particular case are compliance and regulatory considerations. I could also see not wanting to leak implementation details as another reason you might want to hide or obscure filenames.

**Comment by sidharthachatterjee** [comment]
@maxcountryman Firstly, my apologies for not responding to this earlier. 

> I'm sure there are any number of reasons, but among the most important in our particular case are compliance and regulatory considerations. I could also see not wanting to leak implementation details as another reason you might want to hide or obscure filenames.

While I disagree that this should be necessary, I can empathise and understand the use case. I've put up a sample repository on how you could do this at https://github.com/sidharthachatterjee/gatsby-custom-filenames

The trick is to use `replaceWebpackConfig` to setup a custom webpack config with `filename` keys. 

In https://github.com/sidharthachatterjee/gatsby-custom-filenames/blob/master/gatsby-node.js I have set it to `[id].js` and `[contenthash].js` (default value is `[name]-[contenthash].js`) in an effort to _obfuscate_ the file names as you described. 

Hope this helps!

**Comment by marshalhayes** [comment]
I was able to get this working quite easily, so thanks for that example repo - and for still keeping it up almost two years later! 

Here's what I did, even though it's essentially identical to your example (in production):

```js
// gatsby-node.js
const { merge } = require('webpack-merge');

exports.onCreateWebpackConfig = ({
  stage,
  getConfig,
  actions,
}) => {
  if (stage === 'build-javascript') {
    actions.replaceWebpackConfig(
      merge(getConfig(), {
        output: {
          filename: '[contenthash].js',
          chunkFilename: '[contenthash].js',
        },
      }),
    );
  }
};

```

Out of curiosity, should this also rename gatsby's `page-data.json` files' `componentChunkName` properties? After making the above change, the network request to one `page-data.json` shows:

```json
{
  "componentChunkName": "component---src-pages-login-tsx",
  "path": "/login/",
  "result": {
    "pageContext": {}
  },
  "staticQueryHashes": []
}
```

While this doesn't matter to me as much as the filenames themselves, I'm just wondering if the chunk names should match. Here's what I expected this `page-data.json` to become:

```json
{
  "componentChunkName": "component--5e43c0de24a1049b0158-js", 
  "path": "/login/",
  "result": {
    "pageContext": {}
  },
  "staticQueryHashes": []
}
```

Any ideas on how to accomplish this?
