### ISSUE TITLE
AWS S3, Cloudfront and custom filename + extension

### ISSUE THREAD

**Issue by ves-fyayc** [gatsbyjs/gatsby#15024]
Our Gatsby rendered pages will be stored in S3. 

S3 can be configured as “Web Hosting” and would do subdirectory root resolution (so request /product/SAPPHIRE would resolve in /product/SAPPHIRE/index.html.)

But when delivering the site via CloudFront  with a restricted S3 bucket this is not possible.

My question: Is it possible, using createPages or any other API, to generate a custom path + filename + extension.

**Comment by bradleyayers** [comment]
I'm also interested in this, though my motivation is to avoid the redirect that occurs from `/product/SAPPHIRE` to `/product/SAPPHIRE/index.html` for performance. I'd like to generate `public/product/SAPPHIRE.html` instead of `public/product/SAPPHIRE/index.html`.

**Comment by sidharthachatterjee** [comment]
> My question: Is it possible, using createPages or any other API, to generate a custom path + filename + extension.

> I'd like to generate public/product/SAPPHIRE.html instead of public/product/SAPPHIRE/index.html.

Unfortunately, we don't currently support this. File name and extensions are set to `index.html` (scoped within a folder for the path) and there isn't any way to customise it.

**Comment by elliotdickison** [comment]
@sidharthachatterjee I'm trying to do something similar. If index.html is fixed, is there at least a way to keep Gatsby from stripping that off URLs when loaded? For example right now if I load `<cloudfront domain>/my-page/index.html` then it works, but Gatsby replaces the URL with just `<cloudfront domain>/my-page/` after JS loads which will not work if the user refreshes.
