### ISSUE TITLE
if I have found vulnerabilities in a gatsby plugin or gatsby itself whom should I tell about it?

### ISSUE THREAD

**Issue by interglobalmedia** [gatsbyjs/gatsby#15037]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by eknowles** [comment]
normally it would be https://github.com/gatsbyjs/gatsby/security/policy but it hasn't been setup yet... awaiting author response

**Comment by sidharthachatterjee** [comment]
@interglobalmedia Can you please send an email on kyle@gatsbyjs.com? 

@eknowles We've set that up in https://github.com/gatsbyjs/gatsby/pull/15162

Thank you!
