### ISSUE TITLE
Gatsby page query execution during build appears to be impacted by network conditions

### ISSUE THREAD

**Issue by vcarl** [gatsbyjs/gatsby#15032]
## Description

The `run page queries` step of the Gatsby build appears to be significantly affected by poor network conditions. I've now encountered this in Netlify (Recently there were network issues with their cloud hosting) and to a lesser extent locally when my wifi was dropping packets.

The only source plugins I'm using are  `gatsby-source-filesystem`, `gatsby-source-contentful`, and `gatsby-source-rss-feed`, all of which frontload data before queries are run, to my knowledge.

Build logs during our extra slow Netlify build:

```
3:40:33 PM: contentTypes fetched 6
3:40:33 PM: Updated entries  68
3:40:33 PM: Deleted entries  0
3:40:33 PM: Updated assets  52
3:40:33 PM: Deleted assets  0
3:40:33 PM: Fetch Contentful data: 2764.054ms
3:41:09 PM: warning Failed to process remote content http://images.ctfassets.net/<snip>.png
3:41:09 PM: warning Failed to process remote content http://images.ctfassets.net/<snip>.png
3:41:09 PM: success source and transform nodes — 38.807 s
3:41:09 PM: success building schema — 0.564 s
3:41:10 PM: success createPages — 0.325 s
3:41:10 PM: success createPagesStatefully — 0.038 s
3:41:10 PM: success onPreExtractQueries — 0.007 s
3:41:10 PM: success update schema — 0.237 s
3:41:10 PM: success extract queries from components — 0.291 s
3:41:10 PM: success run static queries — 0.001 s
3:52:07 PM: success run page queries — 656.861 s — 117/117 0.18 queries/second
3:52:07 PM: success write out page data — 0.006 s
3:52:07 PM: success write out redirect data — 0.001 s
3:52:07 PM: success onPostBootstrap — 0.001 s
3:52:07 PM: info bootstrap finished - 700.606 s
3:52:42 PM: success Building production JavaScript and CSS bundles — 34.950 s
3:52:49 PM: success Building static HTML for pages — 6.710 s — 117/117 25.71 pages/second
3:52:49 PM: info Done building in 742.417 sec
3:52:49 PM: Done in 743.36s.
```

Specifically, `run page queries — 656.861 s — 117/117 0.18 queries/second` is nearly 2 orders of magnitude slower than in good conditions. It also looks like some images failed to load, indicative of how severe network issues were.

For some random further evidence, here are some logs and the network latency reported by `ping 8.8.8.8`:

```
round-trip min/avg/max/stddev = 3.790/4.103/4.678/0.296 ms
run page queries — 2.076 s — 128/128 61.69 queries/second
```
```
round-trip min/avg/max/stddev = 25.998/97.079/277.198/64.029 ms
run page queries — 8.454 s — 128/128 15.14 queries/second
```

These are run on the same machine.

### Steps to reproduce

I'm near a deadline at work and can't dive deep into making a reproduction (and since it appears to be from network conditions, that seems hard to recreate), but I can try and create something in a few weeks.

### Expected result

Builds should not be affected by network conditions after data is loaded

### Actual result

Poor network = super slow page query execution.

### Environment

In a gist: https://gist.github.com/vcarl/ba0ed05d1c66968d3f19629f770165ba.

**Comment by sidharthachatterjee** [comment]
@vcarl Thank you for opening this!

Resolvers can indeed connect to the network. For instance, `gatsby-source-contentful` will grab images (from Contentful) to generate base64 versions for blur-up. 

> Builds should not be affected by network conditions after data is loaded

Since the loading of the data and running queries are both steps in the same command (build), we would typically expect network connectivity through the build process.

**Comment by vcarl** [comment]
Hm, it doesn't fetch all content in one go, then query that when it needs to work with image further? I assumed the `Fetch Contentful data` was retrieving all the necessary data for future use.

From my first post, 

```
// From wifi
round-trip min/avg/max/stddev = 3.790/4.103/4.678/0.296 ms
run page queries — 2.076 s — 128/128 61.69 queries/second

// From phone tether
round-trip min/avg/max/stddev = 25.998/97.079/277.198/64.029 ms
run page queries — 8.454 s — 128/128 15.14 queries/second
```

A 4x slowdown on moderate latency seems pretty unusual, the latency numbers there aren't too extreme. This is a blog with pretty moderate image use (most of them are raw URLs, so Contentful isn't even aware they're images).

I'm not familiar with how it works, but this inconsistency in performance has hit me a number of times. I can dig into the code later to see how much work it would take to change, but I would notice if this were improved.

**Comment by KyleAMathews** [comment]
The extra latency comes probably from us limiting the number of concurrent GraphQL queries (to 4) — so high latency HTTP calls cause a lot of trouble. We should make the # of concurrent queries vary depending on CPU load in the process so that we could have more ongoing network calls.

**Comment by KyleAMathews** [comment]
@vcarl want to try changing this number? https://github.com/gatsbyjs/gatsby/blob/9a1f5e26b194ab852235a8a8af1d8f130cab58c0/packages/gatsby/src/query/queue.js#L8

**Comment by vcarl** [comment]
I did a couple builds while tether to my phone. I ran `rm -rf .cache; yarn build`, started `ping 8.8.8.8` in a different terminal, and kill both once bootstrap finished. 

```
concurrent: 4

round-trip min/avg/max/stddev = 28.053/96.187/268.060/74.427 ms
run page queries — 2.742 s — 83/83 30.28 queries/second

round-trip min/avg/max/stddev = 30.032/56.345/145.745/24.032 ms
run page queries — 4.954 s — 83/83 16.76 queries/second

round-trip min/avg/max/stddev = 28.344/58.574/241.359/31.610 ms
run page queries — 10.476 s — 83/83 7.92 queries/second

concurrent: 8

round-trip min/avg/max/stddev = 20.328/51.765/163.524/27.917 ms
run page queries — 4.361 s — 85/85 19.50 queries/second

round-trip min/avg/max/stddev = 21.797/64.608/471.720/68.892 ms
run page queries — 4.404 s — 83/83 18.85 queries/second

round-trip min/avg/max/stddev = 26.635/52.615/129.712/22.871 ms
run page queries — 4.351 s — 83/83 19.08 queries/second
```

There's a ton of variability here. I'm not sure if bumping up concurrent helped or those builds just didn't get unlucky.  Worth mentioning that the last `concurrent: 4` build, the slowest, hung on 82/83 for a few seconds.

**Comment by vcarl** [comment]
I guess whether this is stale or not depends on whether it's okay for 100ms in latency to slow down this stage of the build by 4x, and more to have a correspondingly larger slowdown.

This has bitten me in the form of builds failing due to timeout during a latency spike. The behavior was surprising to me since it seems the data could be front-loaded, eliminating the need for fetching it when building the requests.
