### ISSUE TITLE
Styled Component props not updating in dom

### ISSUE THREAD

**Issue by BraveLilToaster** [gatsbyjs/gatsby#15033]
## Description

I have been experiencing some unexpected behavior when trying to use styled-components in a Gatsby build that only seems to happen in production builds. I have a hook that changes the value of props being passed to a styled component. When the page is loaded in the browser it appears as though the styles are correct in react dev tools, but the DOM does not reflect these changes.

It works as intended with `gatsby develop` , but not with `gatsby build`.

Link to issue in syted-components: https://github.com/styled-components/styled-components/issues/2629

### Steps to reproduce

1. `npm run build`
2. `npm run serve`
3. Visit localhost:9000

Example Repo: https://github.com/BraveLilToaster/styled-components-issue-2629
Example CodeSandbox: https://codesandbox.io/s/styled-components-issue-2629-js89j

### Expected result

Screen size is detected to be over 900px wide. Value of props passed down to the styled components change. Classes/styles update in the DOM.
![image](https://user-images.githubusercontent.com/8815195/59778999-799abb00-9285-11e9-99b8-ebc70cb96a83.png)

### Actual result

Screen size is detected to be over 900px wide. Value of props passed down to the styled components. Classes/styles update in react dev tools, but the DOM maintains the same classes/styles from the initial load.
![image](https://user-images.githubusercontent.com/8815195/59778936-612aa080-9285-11e9-9509-91f9355d2a76.png)

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.12.1 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 67.0.1
  npmPackages:
    gatsby: ^2.9.4 => 2.9.4 
    gatsby-image: ^2.1.4 => 2.1.4 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.3 => 2.1.3 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.1.5 => 2.1.5 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-source-filesystem: ^2.0.39 => 2.0.39 
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21

**Comment by sidharthachatterjee** [comment]
Thank you for the detailed issue @BraveLilToaster 

I've seen issues like these before and they are typically a result your app not being hydrated correctly. 

From https://reactjs.org/docs/react-dom.html

> React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them. In development mode, React warns about mismatches during hydration. There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.

I'm not sure how to fix this but I would investigate the component that this is occurring in and maybe open an issue in https://github.com/styled-components/styled-components
