### ISSUE TITLE
How might I get this component to work in a gatsby site?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#15049]
I'm trying to get this component to work in my gatsby app:
 
https://github.com/mvasin/react-div-100vh

...but I'm not sure how to implement it so that it will actually work. I tried importing it into my `layout.js` component, but it did not do the job it's supposed to do.

I'm wondering if I need to wrap my app with it inside the `gatsby-browser.js` file, and if so, how would I go about doing that.

For instance, should this work in the `gatsby-browser.js` file?

```js
import React from 'react'
import Div100vh from 'react-div-100vh'

export const wrapRootElement = ({ element }) => {
  return (
    <Div100vh>{element}</Div100vh>
  )
}
```

Gonna test this, but any thoughts would be appreciated.

Thank you XD

**Comment by rchrdnsh** [comment]
ok, I tried that and I just got a white screen and no error messages that I could make any sense of...

**Comment by robinmetral** [comment]
I took a look at [`mvasin/react-div-100vh`](https://github.com/mvasin/react-div-100vh) and it looks like it expects `window` to be defined ([check the `getWindowHeight` function](https://github.com/mvasin/react-div-100vh/blob/b764b11408a78e6ba2ef76c4efea03a0bb7ad26d/src/lib/getWindowHeight.js#L2-L4)).

Gatsby is rendered server-side, and when it builds, `window` is undefined. This would cause your Gatsby site to crash on build.

From the [docs](https://www.gatsbyjs.org/docs/debugging-html-builds/):
> If this is your problem you should see an error above like “window is not defined”. To fix this, find the offending code and either a) check before calling the code if window is defined so the code doesn’t run while Gatsby is building (see code sample below) or b) if the code is in the render function of a React.js component, move that code into componentDidMount which ensures the code doesn’t run unless it’s in the browser.

Is this the error you're running into?

**If it is**: since the error comes from an npm dependency, a solution is to ignore `react-div-100vh` on build through a webpack setting. Refer to [Fixing third-party modules](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules) for details :slightly_smiling_face: 

**If it isn't**: can you provide error messages or a repo to test?

**Comment by rchrdnsh** [comment]
hmmmmmm...now I don't get any error in the console at all, but the build that has been pushed to Netlify and served to my phone is still completely blank.

Check out this site and see if you can spot anything on your phone, as it seems to work on the laptop:

www.alma.vacations

The routing broken as I am waiting on the fix that will be coming from Gatsby in the next few days.

Anyway, here is the repo as well:

https://github.com/arrowgtp/alma

**Comment by robinmetral** [comment]
I reproduced this on desktop with a hard reload of www.alma.vacations:

- hard reload: blank page
- reload: the site appears

Not sure what's going on there. Even when the site is blank, the markup seems to be rendered:

| screenshot from FF devtools |
| --- |
| ![screenshot](https://user-images.githubusercontent.com/35560568/59994639-e4b50a80-9654-11e9-90d9-bad043da2cee.png) |

In the built site, it seems like your Layout has `opacity: 0;`, which hides all children components.

Are you sure that [`mvasin/react-div-100vh`](https://github.com/mvasin/react-div-100vh) is causing the error?

**Comment by rchrdnsh** [comment]
well, i've pushed a new build, and the only thing i changed was commenting out the code for the plugin and it works fine again, minus the routes being broken, so........i don't know...

I'm really just trying to solve a problem, and I thought this react component would be the easiest way to solve it, but if that's not the case...

Here is a quick little article describing the issue quickly, with a few solutions.

https://medium.com/@susiekim9/how-to-compensate-for-the-ios-viewport-unit-bug-46e78d54af0d

The react component was the authors choice, but even her second example might do the trick as well:

```js
window.onresize = function() {
    document.body.height = window.innerHeight;
}
window.onresize(); // called to initially set the height.
```

I just don't know where this would go or how to make it work in a Gatsby app.

I just really wanna solve the issue at the end of the day, that's all really.

**Comment by wardpeet** [comment]
you have to do:

```
import React, { useEffect } from 'react'
import Div100vh from 'react-div-100vh'

export const wrapRootElement = ({ element }) => {
  useEffect(() => {
    window.onresize = function() {
      document.body.height = window.innerHeight;
    }

    window.onresize(); // called to initially set the height.
  }, []);

  return (
    <Div100vh>{element}</Div100vh>
  )
}
```

**Comment by rchrdnsh** [comment]
hmmmm...I threw that code in my app and got this error message in the browser:

<img width="1053" alt="Screenshot 2019-06-25 09 50 20" src="https://user-images.githubusercontent.com/7884263/60117313-b3a90880-972e-11e9-9bce-aaa50db5442e.png">

...which is odd, since you are doing the exact right thing in the code...🤷‍♂️

**Comment by wardpeet** [comment]
what about?
```js
const WrapperComponent = (props) => {
  useEffect(() => {
    window.onresize = function() {
      document.body.height = window.innerHeight;
    }

    window.onresize(); // called to initially set the height.
  }, []);

  return props.children;
})

export const wrapRootElement = ({ element }) => {
  
  return (<WrapperComponent>
    <Div100vh>{element}</Div100vh>
  </WrapperComponent>)
}
```

**Comment by rchrdnsh** [comment]
so the app wasn't broken, but it was still just blank screen on deploy...All I really want to do is make 100vh work in mobile Safari and Chrome, so maybe I don't need that component, just to resize the window to the visual viewport...is that possible?

Just to use this?

```js
window.onresize = function() {
  document.body.height = window.innerHeight;
}
```

and if so, how could i use it in Gatsby to change the height to the visual viewport and have THAT number equal 100vh?

**Comment by rchrdnsh** [comment]
I'm just trying to fix the behavior of a few key browsers and the way they handle vh units in css.

This image illustrates the issue:

![iOS-100vh-bug-compressor](https://user-images.githubusercontent.com/7884263/60413940-807dd380-9b8b-11e9-91f1-f4eadf69c299.png)

...where iOS safari and chrome calculate 100vh to include the browser ui, as they will disappear upon scroll. I have disabled the browser UI from minimzing on scroll, so i would like to essentially make 100vh turn into whatever the inner height of the visual viewport is in every browser. The 100vh react component supposedly does this, but if I can do it without that component i would be fine with that. Just don't know how I would go about that in gatsby.
