### ISSUE TITLE
Links with slow loading using version 2.10

### ISSUE THREAD

**Issue by aikodeio** [gatsbyjs/gatsby#15041]
## Description

I am experiencing a strange loading process with my website in mobile browsers since the Gatsby update.

Using an excellent Internet connection, every time I browse the site, mobile browsers (chrome, firefox) show me a progress bar in loading the website ("loading" or "nprogress" style).
But only with this site created with version 2.10 of Gatsby.

I have another site with the version of Gatsby 2.0.53 and I do not have that experience. The navigation feels fast and at no time shows the loading progress bar.

What surprises me is that this new website has NOTHING of content, compared to my other website.
However, it offers an experience totally contrary to the experience with my other website that uses a previous version.
It feels slow.

I'm supposed to have the same experience on both websites, that is, every time I browse between pages, I should enjoy an excellent sense of speed and not show me a load progress bar.

Both have integrated the nprogress plugin.

### Steps to reproduce

From your cell phone (hopefully Android, since I do not have IOS to try):

Enter to: https://academia-milanomodels.firebaseapp.com
Browse between the pages.

Enter to: https://raul-mujica.firebaseapp.com
Browse between the pages.

### Expected result

On both sites the browsing experience should feel fast.

### Actual result

On the https://academia-milanomodels.firebaseapp.com website. 
The navigation feels a bit slower, since mobile browsers show a loading progress bar every time I browse a page.

### Environment

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.10.0 => 2.10.0
    gatsby-image: ^2.2.1 => 2.2.1
    gatsby-plugin-advanced-sitemap: ^1.1.1 => 1.1.1
    gatsby-plugin-canonical-urls: ^2.1.0 => 2.1.0
    gatsby-plugin-gtag: ^1.0.11 => 1.0.11
    gatsby-plugin-manifest: ^2.2.0 => 2.2.0
    gatsby-plugin-nprogress: ^2.1.0 => 2.1.0
    gatsby-plugin-offline: ^2.2.0 => 2.2.0
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0
    gatsby-plugin-remove-trailing-slashes: ^2.1.0 => 2.1.0
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1
    gatsby-source-filesystem: ^2.1.0 => 2.1.0
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @aikodeio 

I did take a look at both sites (on desktop but with network throttled to Slow 3G) and I can't point to anything specifically slow on the latter. 

Can you elaborate on what you mean when you say that the second site feels slower? It does seem to navigate to the page quickly enough. Images are taking a while to load but I don't think that is what you were referring to?

**Comment by aikodeio** [comment]
@sidharthachatterjee Thank you for your response and for having performed the tests on my question. I'm going to record a video to show what happens.
