### ISSUE TITLE
Custom markdown components with Rehype are wrapped in paragraphs

### ISSUE THREAD

**Issue by robinmetral** [gatsbyjs/gatsby#15057]
_Note: I'm aware that the current [recommended way](https://www.gatsbyjs.org/docs/mdx/) of adding custom components in Markdown is MDX, instead of the Rehype plugin. Therefore I'm not sure whether this should be fixed or not._

## Description

Custom components in Markdown, created following [this guide](https://using-remark.gatsbyjs.org/custom-components/), are nested in a paragraph element when rendered to the DOM.

### Expected result

The custom component shouldn't be wrapped in a `p`.

**Why?**  if the custom component's root element is a div (for example, if the component is an image gallery), there will be a `div` inside a `p`, which will cause a semantic error:

```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>. 
```

**Comment by freiksenet** [comment]
Hello @robinmetral!

While we indeed recommend MDX, I don't think that means that using custom components shouldn't work. Would you like to make a PR to gatsby-plugin-remark to fix that, so that custom components aren't wrapped in <p>?

Thank you! :purple_heart: :muscle:

**Comment by robinmetral** [comment]
Unfortunately I don't think I'm not sure I can manage it by myself, I can't even seem to figure out where the relevant code is in the `gatsby-transformer-remark` plugin :stuck_out_tongue:  Can you give me a hint?

**Comment by moroshko** [comment]
Hitting this issue as well.

@freiksenet Could you provide some guidance for where the issue might be?

**Comment by pinkiebala** [comment]
I'd follow this [doc](https://www.gatsbyjs.org/packages/gatsby-remark-component/)，install "gatsby-remark-component" solved the problem.

**Comment by muuvmuuv** [comment]
Having the same with `gatsby-remark-images`:

```
index.js:2177 Warning: validateDOMNesting(...): <figcaption> cannot appear as a descendant of <p>.
    in figcaption (created by MDXCreateElement)
    in MDXCreateElement (at credits.mdx:163)
    in figure (created by MDXCreateElement)
    in MDXCreateElement (at credits.mdx:100)
    in p (at Paragraph.jsx:3)
    in Paragraph (created by MDXCreateElement)
    in MDXCreateElement (at credits.mdx:100)
    in article (at Article.jsx:99)
    in Article (at PageSingle.jsx:40)
    in Page (at PageSingle.jsx:48)
    in ForwardRef (created by MDXCreateElement)
    in MDXCreateElement (at credits.mdx:42)
    in MDXContent (created by HotExportedMDXContent)
    in AppContainer (created by HotExportedMDXContent)
    in HotExportedMDXContent (created by PageRenderer)
    in main (at layouts/index.jsx:19)
    in MDXProvider (at layouts/index.jsx:18)
......
```

**Comment by dinhanhthi** [comment]
> Having the same with `gatsby-remark-images`:
> 
> ```
> index.js:2177 Warning: validateDOMNesting(...): <figcaption> cannot appear as a descendant of <p>.
>     in figcaption (created by MDXCreateElement)
>     in MDXCreateElement (at credits.mdx:163)
>     in figure (created by MDXCreateElement)
>     in MDXCreateElement (at credits.mdx:100)
>     in p (at Paragraph.jsx:3)
>     in Paragraph (created by MDXCreateElement)
>     in MDXCreateElement (at credits.mdx:100)
>     in article (at Article.jsx:99)
>     in Article (at PageSingle.jsx:40)
>     in Page (at PageSingle.jsx:48)
>     in ForwardRef (created by MDXCreateElement)
>     in MDXCreateElement (at credits.mdx:42)
>     in MDXContent (created by HotExportedMDXContent)
>     in AppContainer (created by HotExportedMDXContent)
>     in HotExportedMDXContent (created by PageRenderer)
>     in main (at layouts/index.jsx:19)
>     in MDXProvider (at layouts/index.jsx:18)
> ......
> ```

Same issue in Gatbsy 4.12.1
