### ISSUE TITLE
gatsby-source-wordpress flexible content query structure problem

### ISSUE THREAD

**Issue by arturhenryy** [gatsbyjs/gatsby#15069]
## Summary

So i have custom post type called projects which has a acf flexible content field. somehow i am failing to structure the query right.

this would be the recommended way of the documentation:
```
{
  allWordpressWpProjects {
    edges {
      node {
        title
        acf {
          project_single {
            project_content_projects {
              __typename
            }
          }
        }
      }
    } 
  }
}
```

but this throws an error in graphiQl and recommends me to use the actual field name of the flexible content like project_content. so like this i can query it. but if i query the typenames like so:

```
{
  allWordpressWpProjects {
    edges {
      node {
        title
        acf {
          project_single {
            project_content {
              __typename
            }
          }
        }
      }
    } 
  }
}
```

so in the project single custom field group i have 4 flexible content modules all named like text_module, slider_module and the displayed project has everyone one of them assigned twice but the returning typenames are all the same and look wrong

```
{
  "data": {
    "allWordpressWpProjects": {
      "edges": [
        {
          "node": {
            "acf": {
              "project_single": {
                "project_content": [
                  {
                    "__typename": "wordpress__wp_projectsAcfProject_singleProject_content"
                  },
                  {
                    "__typename": "wordpress__wp_projectsAcfProject_singleProject_content"
                  },
                  {
                    "__typename": "wordpress__wp_projectsAcfProject_singleProject_content"
                  },
                  {
                    "__typename": "wordpress__wp_projectsAcfProject_singleProject_content"
                  },
                  {
                    "__typename": "wordpress__wp_projectsAcfProject_singleProject_content"
                  },
                  {
                    "__typename": "wordpress__wp_projectsAcfProject_singleProject_content"
                  },
                  {
                    "__typename": "wordpress__wp_projectsAcfProject_singleProject_content"
                  },
                  {
                    "__typename": "wordpress__wp_projectsAcfProject_singleProject_content"
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
```

would be great if someone could give a hint what i am missing here :)

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by arturhenryy** [comment]
ok so i found the solution to this problem. the project content field which is the flexible content acf was inside a acf group field which somehow prevented that i could query project_content_projects like described in the documentation. so i removed the acf group and it worked.

**Comment by pieh** [comment]
Can you post screenshot of your ACF fields definitions (before you removed it from group)? I'd like to take a look at this and that way I think I could reproduce this in easiest way

**Comment by arturhenryy** [comment]
@pieh yes i rebuilt it for you
![Edit Field Group ‹ MD-Relaunch-2019-WP-Backend — WordPress](https://user-images.githubusercontent.com/45144968/60104691-4020ee80-9762-11e9-8ace-129e84c72ed2.png)

**Comment by arturhenryy** [comment]
@pieh did you fix this? otherwise this shouldnt be closed.
