### ISSUE TITLE
Which plugin for mdx support?

### ISSUE THREAD

**Issue by benabel** [gatsbyjs/gatsby#15068]
## Summary

Its is not really clear if we should use `gatsby-plugin-mdx` or `gatsby-mdx` to process mdx files. The [docs](https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/) sometimes use one or another.

## Relevant information

This doc [page](https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/) uses `gatsby-mdx`, but this [one](https://www.gatsbyjs.org/docs/mdx/getting-started/) require install of `gatsby-plugin-mdx`. Also the README of both packages have no information of which one to use.

**Comment by benabel** [comment]
In fact it seems that `gatsby-plugin-mdx` has been archived in github. So docs should be updated. to only use `gatsby-mdx`. Do you want that I oopen a PR for this.

**Comment by benabel** [comment]
It seems that the gatsbyjs.org site use `gatsby-plugin-mdx`, see [package.json](https://github.com/gatsbyjs/gatsby/blob/460b2db675f811d417f4f15569a1bc5375c0d680/www/package.json#L36).

**Comment by wardpeet** [comment]
We're moving gatsby into the monorepo, that's the reason why it's archived. Please use `gatsby-plugin-mdx` we'll deprecate `gatsby-mdx` in the future.

**Comment by benabel** [comment]
Thanks, I created a PR to use `gatsby-plugin-mdx` on docs.
