### ISSUE TITLE
Theme Boilerplate

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#15066]
## Summary

A theme boilerplate which sets up a basic scaffold for themes as the process requires a lot of time (~5-15 mins on understanding level) so theme boilerplate can simplify that.

### Basic example

It should be included within Gatsby CLI.

A simple example can be like:

```bash
$ gatsby new personal-site --theme gatsby-theme-workspace --example example
```

Then for a complex example which includes Child Theme & all, you get a bunch of questions about adding child themes & all. But the complex version can come later. The simple one is much needed.

### Motivation

I was reading the new blog https://www.gatsbyjs.org/blog/2019-05-22-setting-up-yarn-workspaces-for-theme-development/

I used Themes when it first came out. It was complex at that time.

This blog is well written (includes why you should add peer deeps & all which wasn't added at that time) but still it has a learning curve.

Every time I want to start from scratch I'd have to refer to this blog. It'd be better if I can just get started in 2 secs rather than wasting so much time. The biggest gripe Gatsby has is getting started is complex. Earlier Gatsby itself faced it which themes solved but now themes are facing it.

I also know about the starter blog for gastby-theme but an official one would be much better :)

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @deadcoder0904 

Seems like an interesting idea to add support for scaffolding this out. What do you think @ChristopherBiscardi?

**Comment by ChristopherBiscardi** [comment]
We have starters for the official themes (blog, notes, blog+notes) coming as we look to go stable soon, and I'm also planning on donating the [theme authoring starter](https://github.com/ChristopherBiscardi/gatsby-starter-theme) which would set up the full workspaces setup.

Would this command do something substantially different than a starter?

**Comment by deadcoder0904** [comment]
Yes, I think.

The starter you have is minimal so this command would look something like `expo-cli` in React Native.

For a quick video about `expo-cli`, see https://youtu.be/bef12Fa9bhM?t=271

It's generally faster to use & easier to remember -> `$ gatsby new personal-site --theme gatsby-theme-workspace --example example` rather than typing `$ git clone <your-repo>`

`expo-cli` has 2 templates like `blank` & `tabs`. `blank` is like our `minimal`. `tabs` for gatsby can be like `child-themes` so everything gets set up using `gatsby-cli`.

Not sure if you wanna include `child-themes` & all but base version would be much better for now :)
