### ISSUE TITLE
RFC: tweak slogan

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1507]
I was talking to a friend and he suggested an alternative slogan for Gatsby:

"Blazing-fast static site generator for the modern web"

The logic being that for many people adopting Gatsby, "React" isn't necessarily what they care about. They just want a framework that builds really fast websites for today's web with modern tools. React may or may not be part of the attraction.

I'm seeing evidence of this on Twitter as many people commenting on Gatsby say paraphrasing "Gatsby is awesome! Haven't used React before but guess I can learn it to use Gatsby".

Thoughts?

**Comment by jbolda** [comment]
👍  especially once a plugin is setup to emulate 0.12.X where you bring the markdown and most of react is abstracted away.

**Comment by KyleAMathews** [comment]
This is live!
