### ISSUE TITLE
Bug: Image links broken in the WordPress Images Tutorial

### ISSUE THREAD

**Issue by n8finch** [gatsbyjs/gatsby#15087]
## Description

In the Adding Images to a WordPress Site tutorial, the image links are broken: https://cl.ly/8f94b00cea7d . It looks like they are relative links.

### Steps to reproduce

In the [Adding Images to a WordPress Site]https://www.gatsbyjs.org/tutorial/image-tutorial/) at the end of the article, there are three broken images.

### Expected result

The images should be displayed (on gif, two images).

### Actual result

Currently, the images are broken.

### Environment

This is on the website here: https://www.gatsbyjs.org/tutorial/image-tutorial/

### Proposed Solution

I'm opening a PR with a modified links, based on the Contributing guidelines [here](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#format-code-blocks-inline-code-and-images).

**Comment by tom-raley** [comment]
I'd be happy to work on this. It seems that the images are missing entirely from the code base. If someone can point me in the direction of where to find these images I'd be happy to upload and update the code.
