### ISSUE TITLE
No instruction to import header to index.js

### ISSUE THREAD

**Issue by alexdkaminski** [gatsbyjs/gatsby#15098]
## Description

In [Part One](https://www.gatsbyjs.org/tutorial/part-one/#-using-the-link--component) (Section "Using the <Link /> component") of the Gatsby tutorial, there is no instruction to add `import Header from "../components/header` to `index.js`. This line just appears in the code block of `index.js`. 

In a previous step, the user is instructed to add this line to `about.js`. The user should be instructed to also add this line to `index.js` to ensure their code matches that of the tutorial.

### Steps to reproduce

Follow Part one of the Gatsby tutorial

### Expected result

User should be instructed to add `import Header from "../components/header` to `index.js`.

### Actual result

The line just appears in the code block of `index.js` without any instruction given to the user.

### Environment

[Part One](https://www.gatsbyjs.org/tutorial/part-one/#-using-the-link--component) (Section "Using the <Link /> component") of the Gatsby tutorial

**Comment by freiksenet** [comment]
Thank you very much for your report!

Would you like to make a PR to our documentation to fix this? We would really appreciate that. :purple_heart: :muscle:

**Comment by LaunchingDream** [comment]
Hi. Can I work on this issue?

**Comment by mehtavishwa30** [comment]
Hey!
I'd like to open a PR on this issue if no one else is working on it.

**Comment by Aswinpookkatt** [comment]
why is this issue still open?
