### ISSUE TITLE
events.js:177       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Torara1998** [gatsbyjs/gatsby#15100]
Help me plz ! I'm newbie in react native android learner. When i try to build my app this is what i got: 
Error: EPERM: operation not permitted, lstat 'F:\react\templatephoto\android\
app\build\generated\not_namespaced_r_class_sources\devKernelDebug\processDevKernelDebugResources\r\android\arch\core\R.java'
Emitted 'error' event at:
    at NodeWatcher.<anonymous> (F:\react\templatephoto\node_modules\sane\src\node_watcher.js:306:14)
    at F:\react\templatephoto\node_modules\graceful-fs\polyfills.js:282:31
    at FSReqCallback.oncomplete (fs.js:165:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'F:\\react\\templatephoto\\android\\app\\build\\generated\\not_namespaced_r_class_sources\\devKernelDebug\\processDevKernelDebugResources\\r\\android\\arch\\core\\R.java'
}

There are steps to build this app in to emulator device: 
-   npm install
-   npm start
-   Open xcode or android studio build native project
How can i fix it ?

**Comment by freiksenet** [comment]
I'm sorry @Torara1998, but this isn't an Android repository, this is a repository for a Gatsby web framework. I wonder if you can open an issue with them.

Thank you! :purple_heart:
