### ISSUE TITLE
Success source and transform nodes - 1188.045 s

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#15103]
Success source and transform nodes **1188.045 s** 

## Description

`gatsby develop` too long... I have less than 20 articles.

### Steps to reproduce

`gatsby clean && gatsby develop`

### Expected result

The project should start faster at this point. 

### Actual result

<img width="1900" alt="Capture d’écran 2019-06-25 à 10 38 33" src="https://user-images.githubusercontent.com/814410/60083288-c246ee00-9735-11e9-98c6-0dc2c288d082.png">

### Environment

```
$ gatsby info --clipboard

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.24 => 2.10.4 
    gatsby-cli: ^2.4.5 => 2.7.2 
    gatsby-image: ^2.0.15 => 2.0.29 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.3 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.14 
    gatsby-plugin-offline: ^2.0.6 => 2.0.22 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.5 
    gatsby-plugin-sharp: ^2.0.13 => 2.0.18 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.4 
    gatsby-plugin-styled-components: ^3.0.1 => 3.0.4 
    gatsby-source-prismic: ^2.0.0 => 2.2.0 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.12 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by freiksenet** [comment]
Hi @Steffi3rd!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Steffi3rd** [comment]
@freiksenet Hello, sorry I can't. Content is not shareable online at this time.

My posts have images, I see "Downloading..." when I run `gatsby develop`
But I don't understand why I take too long on "local"

**Comment by sidharthachatterjee** [comment]
> My posts have images, I see "Downloading..." when I run gatsby develop
> But I don't understand why it takes too long on "local"

Where are these images coming from? Are they being downloaded from a CMS?

**Comment by Steffi3rd** [comment]
@sidharthachatterjee Yes! It comes from Prismic CMS

**Comment by Steffi3rd** [comment]
Guys! I think I found a "fix"...
I just updated React and ReactDOM to the latest. And it works.

Before : 
gatsby develop : 1188s
gatsby clean && gatsby develop : 1188s

After 
**gatsby develop : 1.2s**
gatsby clean && gatsby develop : 1188s
