### ISSUE TITLE
Error: Cannot find module 'gatsby/utils' after fresh install

### ISSUE THREAD

**Issue by dontdomilk** [gatsbyjs/gatsby#15106]
## Description

Build is failing with an error on plugin gatsby-source-wordpress, though I'm not sure it is related specifically to that plugin. I tried a few versions and it still fails, though everything worked well, both locally and on Netlify, yesterday.

### Steps to reproduce

Either run a fresh build on Netlify or remove node_modules, run npm install, and run gatsby build

### Expected result

Build should run successfully

### Actual result

Build fails
### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.\

The following is the output on my local environment, though again it is occurring on Netlify as well.

System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.14.1 - /usr/local/opt/node@8/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0
    Safari: 12.0
  npmPackages:
    gatsby: ^2.2.13 => 2.2.13 
    gatsby-image: ^2.0.34 => 2.2.3 
    gatsby-plugin-google-gtag: ^1.0.17 => 1.1.0 
    gatsby-plugin-manifest: ^2.0.24 => 2.2.0 
    gatsby-plugin-netlify: ^2.0.17 => 2.1.0 
    gatsby-plugin-offline: ^2.0.25 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.0.11 => 3.1.0 
    gatsby-plugin-remote-images: ^1.0.1 => 1.0.3 
    gatsby-plugin-sass: ^2.0.11 => 2.1.0 
    gatsby-plugin-sharp: ^2.0.31 => 2.2.1 
    gatsby-plugin-sitemap: ^2.1.0 => 2.2.0 
    gatsby-source-filesystem: ^2.0.28 => 2.1.1 
    gatsby-source-marketo: ^1.0.2 => 1.0.2 
    gatsby-source-wordpress: ^3.0.49 => 3.0.49 
    gatsby-transformer-sharp: ^2.1.17 => 2.2.0 
  npmGlobalPackages:
    gatsby-cli: 2.5.0

**Comment by freiksenet** [comment]
Hello @dontdomilk!

Sorry to hear you're running into an issue. You seem to be running a pretty old version of Gatsby and that might be what is causing the problem. I wonder if you could try updating it.

If that doesn't help, I wonder if you could provide us with a [minimal reproduction](https://gatsby.dev/reproduction), so that we could debug the issue.

Thank you for using Gatsby! :purple_heart: :muscle:

**Comment by dontdomilk** [comment]
@freiksenet Thanks for the quick reply. That was the issue, I'm not sure why the ^ on the version number wasn't working as expected, but I've updated my package json. Thanks!
