### ISSUE TITLE
[themejam] Design initial launch state for Theme Jam website

### ISSUE THREAD

**Issue by prestonso** [gatsbyjs/gatsby#15117]
We need to design the initial launch state for the Theme Jam website so that creation of the Gatsby theme can proceed.

### Specification

Taken from @jlengstorf's document:

For the initial launch, let’s timebox design to 2 days maximum. For the pages in this phase, I think it’d be wise to go for a fairly straightforward content template. The home page would probably benefit from having a hero box on top of the standard content layout. Simple/minimal is going to be critical for hitting our launch deadline.

* Home page
  * Illustration from Maggie (see this Slack message for rough sketches)
  * Headline: “Announcing Gatsby Theme Jam! Build a Gatsby theme and win exclusive swag and prizes”
  * Lede: To celebrate the launch of Gatsby themes, we’re holding a theme building contest! Remix our blog theme and enter the Theme Jam contest to get exclusive swag designed by Maggie Appleton. The top two entries will win an all-expenses-paid trip to Gatsby Days!
  * Get started
    * This section might just be links to things, or it could be a code snippet showing the CLI install steps.
    * Links:
      * Contest rules
      * Themes docs/course
      * Official blog theme on GitHub
* Contest Rules
  * Maddie and Linda are working on the copy for this page.
  * Judging criteria (most of these are subjective and will be at the sole discretion of the Gatsby Inkteam):
    * Code quality
    * Accessibility (Lighthouse/manual audit)
    * Performance (Lighthouse/Webpagetest.org score)
    * Creativity
    * Live demo available (e.g. on Netlify)
    * Tagged appropriately to show up in the showcase
    * Documentation for using the theme in the README
* Submit your theme
  * Embedded Airtable form
    * First Name
    * Last Name
    * Email
    * GitHub repo
    * Swag choice
      * Mug
      * T-shirt size
    * Optional comments (e.g. motivation for the theme)
  * Airtable base needs to have a manual approval step (i.e. “approved for listing in contest showcase” checkbox)
* Terms and Conditions/Disclaimer
  * GDPR/privacy disclosures (e.g. how will we use the information we’re collecting? Marketing? Other purposes?)
  * This is more legal stuff than contest rules

**Comment by fk** [comment]
Done; Figma source: https://www.figma.com/file/D9FPTlFlysj8ZqzDXFAvq4CZ/themejam.gatsbyjs.org?node-id=0%3A1
