### ISSUE TITLE
gatsby-source-wordpress acf repeater query does not work when wrapped in group

### ISSUE THREAD

**Issue by arturhenryy** [gatsbyjs/gatsby#15112]
### Description

As described in further detail in https://github.com/gatsbyjs/gatsby/issues/15069
the query logic for repeaters as described in the documentation like [repeater_field_name]_[post_type] does not work when the repeater is wrapped inside a acf group. i have not tried if this also applies if the wrapping element is something other than a group as well. At this point i am not sure if this is a bug that can or should be fixed but this should definitely be mentioned in the documentation if not so.

### Steps to reproduce

1. In the wordpress backend add a acf group to a post or page.
2. Then put the acf flexible content field below
3. Fill in demo content on the page or post
4. Try the query as described in the documentation of gatsby-source-wordpress (https://www.gatsbyjs.org/packages/@angeloashmore/gatsby-source-wordpress/#query-with-acf-flexible-content)

### Expected result

Should just work as if flexible content would be at top level

### Actual result

[repeater_field_name]_[post_type] will throw an error in graphiQL 

### Environment

  System:
    OS: macOS High Sierra 10.13.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 66.0.4
    Safari: 11.0.2
  npmPackages:
    gatsby: ^2.6.0 => 2.6.0 
    gatsby-image: ^2.1.0 => 2.1.0 
    gatsby-link: ^2.1.1 => 2.1.1 
    gatsby-plugin-catch-links: ^2.0.14 => 2.0.14 
    gatsby-plugin-eslint: ^2.0.5 => 2.0.5 
    gatsby-plugin-feed: ^2.2.0 => 2.2.0 
    gatsby-plugin-google-analytics: ^2.0.20 => 2.0.20 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-netlify: ^2.0.17 => 2.0.17 
    gatsby-plugin-nprogress: ^2.0.10 => 2.0.10 
    gatsby-plugin-offline: ^2.1.1 => 2.1.1 
    gatsby-plugin-page-transitions: ^1.0.8 => 1.0.8 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3 
    gatsby-plugin-sitemap: ^2.1.0 => 2.1.0 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-plugin-twitter: ^2.0.13 => 2.0.13 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.0.37 => 2.0.37 
    gatsby-source-wordpress: ^3.0.62 => 3.0.62 
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21 
  npmGlobalPackages:
    gatsby-cli: 2.4.7

**Comment by LekoArts** [comment]
With v4 of `gatsby-source-wordpress` now being powered by WPGraphQL and not the REST API anymore we'll close outdated issues that we won't fix anymore. Please use the new version and check if your issue is fixed. Thanks!
