### ISSUE TITLE
Update eslint-config-react-app to ^4.0.0

### ISSUE THREAD

**Issue by ThewBear** [gatsbyjs/gatsby#15114]
For typescript-eslint supports.
Also, this Webpack rule needs to be changed to include `.ts`/`.tsx`

https://github.com/gatsbyjs/gatsby/blob/9fb78f8634d42e0f5547e320aafed9ae5b489223/packages/gatsby/src/utils/webpack-utils.js#L327-L334

**Comment by TheBear44** [comment]
Keep it open

**Comment by ashr81** [comment]
@wardpeet  raised a pull request by adding ts/tsx , into the regex rule. please check

**Comment by TheBear44** [comment]
Any plan to move eslint-config-react-app to `^4.0.0`?
It has React hooks support.

**Comment by wardpeet** [comment]
sorry missed this issue, i'll be merging eslint upgrade soonish

**Comment by sidharthachatterjee** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/16168 thanks to @ThewBear 🎉
