### ISSUE TITLE
Linking to html in /static shows 404 on click, but works on reload

### ISSUE THREAD

**Issue by isaacs** [gatsbyjs/gatsby#15120]
## Description

Linking to an HTML doc in the /static folder results in a 404.  But, it shows the HTML when rendered

### Steps to reproduce

The page at http://localhost:9000/docs/getting-started/ has a link to an HTML example of coverage output, here: https://node-tap.org/my-awesome-module/coverage-1/lcov-report/index.html

The static coverage output HTML lives in the /static folder here: https://github.com/tapjs/node-tap/blob/master/docs/static/my-awesome-module/coverage-1/index.html

As you can see, all the pages exist and are getting shipped to the appropriate locations.  However, if you click the link on the getting started page (Cmd-F for "pretty" and you'll find it), you get a 404 page.  Reloading the 404 page shows the intended results.

### Expected result

It should serve the static HTML document on click, instead of a 404 page.

### Actual result

A 404 was shown.

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 4.4.23 - /usr/local/bin/bash
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 64.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.8.2 => 2.8.2 
    gatsby-plugin-catch-links: ^2.0.15 => 2.0.15 
    gatsby-plugin-eslint: ^2.0.5 => 2.0.5 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-prefetch-google-fonts: ^1.4.2 => 1.4.2 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-redirect-from: ^0.2.1 => 0.2.1 
    gatsby-remark-autolink-headers: ^2.0.18 => 2.0.18 
    gatsby-remark-prismjs: ^3.2.9 => 3.2.9 
    gatsby-source-filesystem: ^2.0.38 => 2.0.38 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
```

**Comment by isaacs** [comment]
Note: for the time being, I added a `target` property on the link to open in a new tab to work around this issue.  I'll whip up a standalone reproduction case this afternoon.

**Comment by m-allanson** [comment]
Are you using [gatsby-link](https://www.gatsbyjs.org/docs/gatsby-link/) to link to that document? If so, replacing it with a plain `a` tag should fix the problem.

There's a bit more info here: https://www.gatsbyjs.org/docs/gatsby-link/#reminder-use-link-only-for-internal-links

**Comment by isaacs** [comment]
It's a link from within a markdown page, so no.  Using a `<a>` tag  instead of `[foo](/bar)` has the same behavior.

Oddly, I _don't_ see this behavior when using the markdown starter, so it must be something in my setup.

**Comment by isaacs** [comment]
Aha!  [`gatsby-plugin-catch-links`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-catch-links) is the culprit.

Probably worth it to keep using that plugin, since I have a lot of cross-linking between markdown docs on the site, but at least the mystery is solved.  I'll keep using the `target` attribute for now.

Hopefully this issue is helpful for someone in the future :)
