### ISSUE TITLE
[meta] Introduce policy for volunteers to pick up work and assign themselves

### ISSUE THREAD

**Issue by prestonso** [gatsbyjs/gatsby#15123]
Introduce a policy for external contributors where we can assign volunteers and give folks a series of steps.

Automate this with Gatsbot so that we can reduce ambiguity where we can distinguish between issues where we are willing for the community to pick up and issues where we are willing for the community to pick up *and* are working on the issue.

**Comment by amberleyromo** [comment]
Capturing the thoughts that prompted this (originally a DM to @marcysutton)

> Wondering what you think about brainstorming what more we can do to leverage automation to help us manage when the community has offered to pick up an issue. Like maybe have a specific label when someone in the community has volunteered to take up an issue (and therefore marked as not available for others to work on, to get rid of the “oh, but i’ve been working on that too” problem). Then perhaps have a bot to check in a certain amount of time after that label has been added (if the issue is still open), where it pings the contributor. Then, if still no response, remove the label and mark it as available for others to pick up again.

**Comment by lannonbr** [comment]
Just as a notice, GitHub announced this today: https://github.blog/changelog/2019-06-25-assign-issues-to-issue-commenters/

So this allows us to assign non-org members to issues and then we can have some other automation around it to keep in check how the progress is for an issue.

**Comment by danabrit** [comment]
Closing, as this is not a clear priority given the Contribution guidelines are available.
