### ISSUE TITLE
[docs][guides] Accessibility testing checklist reference guide / manual

### ISSUE THREAD

**Issue by prestonso** [gatsbyjs/gatsby#15121]
Discuss manual vs. automated testing and common process for ensuring accessibility.

First step is to create a Google doc and solicit feedback on it.

This will be important for having text about accessibility for Theme Jam participants.

* Working with Fable
* Building in Cypress for theme development
* Document building in that Cypress testing into the themes documentation.

**Comment by marcysutton** [comment]
Brainstorming doc: https://docs.google.com/document/d/1Hyp2oKW5IfpGRXT8lJEKvsVQs7_Agobap4R6_yMdB8k/
