### ISSUE TITLE
Not setting pathPrefix returns undefined

### ISSUE THREAD

**Issue by dardub** [gatsbyjs/gatsby#1512]
### Environment

Gatsby: 1.0.11
Node: 7.3.0

### Issue

When running a build with:
```
gatsby build --prefix-paths
```

If pathPrefix is not defined in gatsby-config.js, asset paths return as /**undefined**/path.ext

### Expected

If pathPrefix is not defined it should return a warning or error.

I think it would be nice if it just returned a warning and returned '/' rather than undefined. What do you think?

**Comment by KyleAMathews** [comment]
Fixed by https://github.com/gatsbyjs/gatsby/pull/1551

**Comment by KyleAMathews** [comment]
Thanks for the bug report!
