### ISSUE TITLE
Iframe injection inside gatsby project

### ISSUE THREAD

**Issue by MateuszKuba** [gatsbyjs/gatsby#15129]
What is an iframe that gatsby injects inside the code ???

![Screenshot_1](https://user-images.githubusercontent.com/26925370/60127912-aa9d5300-9791-11e9-8b44-a13c030cb4b5.png)

**Comment by sidharthachatterjee** [comment]
@MateuszKuba That iframe isn't added by Gatsby. Perhaps it's added by some other JS  that is being loaded?

**Comment by MateuszKuba** [comment]
It is added by gatsby, check the website reactjs.org - it has the same iframe inside its code and many others, the most basic gatsby app has it as well, something is wrong here and i don't like that nobody informs about it inside a documentation

**Comment by MateuszKuba** [comment]
Yes, srry for trouble, it was another js library
