### ISSUE TITLE
Error: Unknown field 'jsonName' on type 'SitePage!'...

### ISSUE THREAD

**Issue by busticated** [gatsbyjs/gatsby#15132]
here's a weird one: i'm in the middle of upgrading to gatsby v2 and seeing an error when building:

```
error GraphQL Error Encountered 1 error(s):
- Unknown field 'jsonName' on type 'SitePage!'.
```

which has me stumped b/c afaict it's an internal, built-in field: https://www.gatsbyjs.org/docs/internal-data-bridge/

the file in question is a "page" (lives in `src/pages/my-page/index.jsx`)

i can repro the error over in GraphiQL using this query:

```
{
    allSitePage {
        edges {
            node {
                jsonName
            }
        }
    }
}
```

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.0 - /usr/local/bin/node
    npm: 5.10.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.9.4 => 2.9.4 
    gatsby-cli: ^2.6.7 => 2.6.7 
    gatsby-image: ^2.1.4 => 2.1.4 
    gatsby-plugin-netlify: ^2.0.17 => 2.0.17 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.1.5 => 2.1.5 
    gatsby-plugin-sitemap: ^2.1.0 => 2.1.0 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-source-contentful: ^2.0.71 => 2.0.71 
    gatsby-source-filesystem: ^2.0.39 => 2.0.39 
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21 
    gatsby-transformer-yaml: ^2.1.12 => 2.1.12

**Comment by stefanprobst** [comment]
@busticated The `jsonName` field on `SitePage` is no longer available in Gatsby v2.9 and above because of #14359.
Could you provide more details on why you're querying for `SitePage.jsonName`? Thanks!

**Comment by busticated** [comment]
hi @stefanprobst - thanks for taking a look :pray:

i'm using `jsonName` to create a series of links to pages within a given namespace:

```js
export const pageQuery = graphql`
	query examplePagesQuery {
		allSitePage(
			filter: {
				path: {
					regex: "^\/examples\/"
				}
			}
		){
			edges {
				node {
					path
					jsonName
				}
			}
		}
	}
`;
```

```jsx
renderNav(){
    const { edges: pages } = this.props.data.allSitePage;

    return (
        <_nav>
            {
                pages.map(({ node }, i) => {
                    return (
                        <_navItem key={i}>
                            <_link to={node.path}>{this.getPageName(node.jsonName)}</_link>
                        </_navItem>
                    );
                })
            }
        </_nav>
    );
},
getPageName(jsonName){
    return jsonName
    .replace('examples-', '')
    .replace('-', ' ')
    .replace('.json', '');
}
```

looking at the new `SitePage` data, i don't see an obvious replacement for this

**Comment by stefanprobst** [comment]
@busticated it looks like `jsonName` was derived from `path`, which is still on `SitePage`:

https://github.com/gatsbyjs/gatsby/blob/b66eca15c0b6f93e9ed3b33b9796b25c6a576b56/packages/gatsby/src/redux/actions/public.js#L269-L277

**Comment by busticated** [comment]
ok. was there a specific reason to remove `jsonName`? more practically, if i simply re-implement the original logic will i run into issues?

**Comment by stefanprobst** [comment]
sorry for the late reply -- yes that should work without issues -- you could even re-add the `jsonName` field to the `SitePage` type if you want:
```js
// gatsby-node.js
const kebabHash = require('kebab-hash')

exports.sourceNodes = ({ actions, schema }) => {
  actions.createTypes(
    schema.buildObjectType({
      name: 'SitePage',
      interfaces: ['Node'],
      fields: {
        jsonName: {
          type: 'String',
          resolve(source) {
            return source.path === '/'
              ? 'index'
              : kebabHash(source.path)
          }
        }
      }
    })
  )
}
```
