### ISSUE TITLE
Storybook docs example broken since storybook v5.1.4

### ISSUE THREAD

**Issue by svict4** [gatsbyjs/gatsby#15136]
## Description

The example for [Visual Testing with Storybook](https://www.gatsbyjs.org/docs/visual-testing-with-storybook/) will break for any new repo (and has been broken since [@storybook v5.1.4](https://github.com/storybookjs/storybook/releases/tag/v5.1.4))
This is because of a minor change to their [implementation of `core-js`](https://github.com/storybookjs/storybook/pull/7051)
An edit will be required to [the docs](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/visual-testing-with-storybook.md)

### Steps to reproduce

Follow the steps at [Visual Testing with Storybook](https://www.gatsbyjs.org/docs/visual-testing-with-storybook/)

1. Create a new repo
2. sb init in said repo
3. copy over `config.js` and `webpack.config.js` as in the docs
4. `yarn storybook` then cry

### Expected result

No errors, storybook should load and open

### Actual result

Errors regarding `core-js` modules not being found

### Environment

  System:
    OS: Windows 10
  Binaries:
    Node: 10.15.3
    Yarn: 1.16.0
    npm: 6.4.1
  npmPackages:
    gatsby: ^2.10.0 => 2.10.4 
    gatsby-image: ^2.2.1 => 2.2.3 
    gatsby-plugin-manifest: ^2.2.0 => 2.2.0 
    gatsby-plugin-offline: ^2.2.0 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0 
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1 
    gatsby-source-filesystem: ^2.1.0 => 2.1.0 
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0 

<details><summary>package.json</summary>
<p>

```
{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "core-js": "^3.1.4",
    "gatsby": "^2.10.0",
    "gatsby-image": "^2.2.1",
    "gatsby-plugin-manifest": "^2.2.0",
    "gatsby-plugin-offline": "^2.2.0",
    "gatsby-plugin-react-helmet": "^3.1.0",
    "gatsby-plugin-sharp": "^2.2.1",
    "gatsby-source-filesystem": "^2.1.0",
    "gatsby-transformer-sharp": "^2.2.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@babel/polyfill": "^7.4.4",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-react": "^7.0.0",
    "@storybook/addon-actions": "5.1.4",
    "@storybook/addon-links": "5.1.4",
    "@storybook/addons": "5.1.4",
    "@storybook/react": "5.1.4",
    "babel-loader": "^8.0.6",
    "babel-plugin-remove-graphql-queries": "^2.7.0",
    "prettier": "^1.18.2"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write src/**/*.{js,jsx}",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\"",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}

```

Note that I've specified storybook 5.1.4 exactly
</p>
</details>

### Notes

Not a webpack expert at all 🙅
Just edited the webpack config to *not* exclude gatsby folder in node_modules and called it a day

Naturally works if you downgrade to storybook v5.1.3

**Comment by cynosurecreative** [comment]
can confirm i follow the above exactly and receive a slew of errors all referencing corejs related data

**Comment by philippe-lavoie** [comment]
In my case, removing the reference breaks storybook. However, when I use my ubuntu shell instead of my windows command prompt, then storybook works. Under windows command prompt, I do have a slew of core-js errors too. The workaround for me is to use Linux inside windows.
