### ISSUE TITLE
Access location from any child of layout component

### ISSUE THREAD

**Issue by kalinchernev** [gatsbyjs/gatsby#15143]
## Summary

Using `gatsby-plugin-layout`, the component under `/src/components/Layout.jsx` has the following signature:

```js
const Layout = ({ children, location }) => {}
```

I'm wondering how would be the best way to pass the `location` to each component used within the layout.

## Relevant information

The layout returns the following:

```js
  return (
    <>
      <TopMessage location={location} />
      <Header
        languages={languages}
        currentLanguage={currentLanguage}
        location={location}
        contentTranslations={contentTranslations}
      />
      <Menu location={location} />
      {children}
      <Footer location={location} />
    </>
  );
```
I want to avoid passing `location` repeatedly.

I believe it's a question of React-specific way of thinking approach, welcoming ideas.

PS I'm not sure it's a good idea to use Context API here. Repo could be seen [here](https://github.com/ec-inno/digit-eci-reference/tree/master/gatsby).

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by arturhenryy** [comment]
hey, so you would obviously need some global state provider logic or a global variable. you could try use this https://www.npmjs.com/package/reactn. 
it´s a simple global state tool build around hooks with not much boilerplate

**Comment by kalinchernev** [comment]
Hi @arturhenryy thanks for the suggestion. I'm not sure it's about state management. I have a relatively decent [state management](https://github.com/ec-inno/digit-eci-reference/blob/master/gatsby/src/Context.js). However, I feel it's more about some cool functional programming concept around props, as the layout component would mount once (i think) and even when i set state from it, components don't quite get the value from the store. I'm also adding the question in gatsby's queue, as I might be unaware of a specific of some sort related to the location object.

**Comment by arturhenryy** [comment]
ok so i cant really follow you here but if you want to use the location objects in components below layout you either can pass them as props or use a global state. their is no other option for that.

**Comment by arturhenryy** [comment]
also if you change routes say from home to about the layout will get of course re-rendered because the location prop changes.

**Comment by kalinchernev** [comment]
Thanks @arturhenryy i'll try with global state again, probably i've done something wrong there.
