### ISSUE TITLE
Access data from gatsby-node.js API in pages/components

### ISSUE THREAD

**Issue by bartold3ak** [gatsbyjs/gatsby#15140]
Hi! I set up third party API that returns array of information in `gatsby-node.js`. How can I access that array in _normal_ code (like pages and components in /src/ directory)

`gatsby-node.js`
```js
exports.onPreBuild = () => {
  ...
  return apiData // [ ["data", "data"], ["data", "data"] ]
}
```

**Comment by paustint** [comment]
I am not an expert, but I think you need to do the following:
Make your api call in `exports.sourceNodes` within `gatsby-node.js`.  Then call `actions.createNode()` which will add the data to graphql.

You might have to play around with it using graphiql explorer - but you can look at other plugins to see how other folks do it.

```javascript
exports.sourceNodes = (
  { actions, getNode, createNodeId, hasNodeChanged, reporter, emitter },
  pluginOptions
) => {
  const { createNode, deleteNode } = actions
...
```
https://www.gatsbyjs.org/docs/node-apis/#sourceNodes
https://www.gatsbyjs.org/docs/actions/#createNode

**Comment by bartold3ak** [comment]
@paustint Thanks, this is pretty much what I did!
