### ISSUE TITLE
Cannot display some images of md file

### ISSUE THREAD

**Issue by MorphyMeri** [gatsbyjs/gatsby#15152]
## Description
It is not able to create a dynamic folder for image...
like If I inspect the image the path is not inside static folder...

### Steps to reproduce

This is a personal project.Cannot reproduce using this project.
This is the link to my project
https://github.com/MorphyMeri/dynamic-blog-new
The images of "how-to-install-jenkins blog has this issue"
if the image is not enclosed in any div and is written in html format,it displays without error
but in markdown format,there is an issue

### Expected result
Image should be correctly displayed

### Actual result

Images in md file in format !{}(imagepath) are not displaying
There is no problem with the image because if I include it in another blog/folder with the same path
It displays correctly

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.10.5 => 2.10.5
    gatsby-image: ^2.0.34 => 2.0.34
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.10 => 3.0.10
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7
    gatsby-remark-images: ^3.0.10 => 3.0.11
    gatsby-source-filesystem: ^2.0.32 => 2.0.32
    gatsby-transformer-remark: ^2.3.8 => 2.3.12
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0

**Comment by prestonso** [comment]
Hi @MorphyMeri!

Thank you for reporting this issue! I spent some time with your codebase to understand what was going on. Thank you for providing us with a repository!

I noticed that you're wrapping your `<img>` tags in `<a>` tags that lack `href` attributes. This is invalid HTML and can lead to parsing issues. We recommend that you use [Markdown syntax](https://www.markdownguide.org/) for handling links and images. Some HTML may render correctly, but other elements will not.

I've forked your repository and [pushed two commits](https://github.com/MorphyMeri/dynamic-blog-new/compare/master...prestonso:master) that show two examples:

1. A test image without the surrounding invalid `<a>` tag
2. A test image linked to your application root using Markdown syntax:

```
[![Linked image test](./how-to-install-jenkins-5.jpg)](/)
```

Thanks for using Gatsby! 💪 💜

**Comment by MorphyMeri** [comment]
@prestonso , i have changed it to a tag just to test it wether it was displaying in that, i know for a fact that the a tag is invalid , but of you enclose the image tag within a div the images dont appear. Can you try enclosing the img tag in a div and check again?
