### ISSUE TITLE
[docs] Finish Static vs Normal Queries page

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#15157]
## Summary

The page on Static vs Normal (Page) Queries exists but seems to not be fully fleshed out.

https://www.gatsbyjs.org/docs/static-vs-normal-queries/

I think it would be good to clean this page up as it is a question that frequently comes up of the differences between the two.

**Comment by lannonbr** [comment]
As well, this is in the Gatsby Internals section of the docs which usually talks about the implementation details, so would it be discussing the technical details about the two types of queries.

With that, do we have a page for the more higher-level differences between the two?

**Comment by sidharthachatterjee** [comment]
I suppose this could be moved out of Gatsby internals and this page could focus on high level differences and limitations that are listed in https://www.gatsbyjs.org/docs/static-query/#how-staticquery-differs-from-page-query

**Comment by lannonbr** [comment]
I actually would be interested in helping out working on this. let me assign myself

**Comment by m-allanson** [comment]
[This PR was merged recently](https://github.com/gatsbyjs/gatsby/pull/15186/files) which adds more context to the [how static query differs from page query doc](https://www.gatsbyjs.org/docs/static-query/#how-staticquery-differs-from-page-query). Which I think leaves it ok to talk about more technical implementation details in this doc. 

cc @gatsbyjs/learning to confirm that sounds right?

**Comment by lannonbr** [comment]
So @Aswinpookkatt's PR did add some stuff to this page, but I believe there is still some work to be done.

With such, I think a good idea would be to split this page into two:

1) High level concepts between the two types of queries. This could be moved out of this section
2) Flesh out this page to discuss more of the internals

**Comment by marcysutton** [comment]
> I think leaves it ok to talk about more technical implementation details in this doc.

That is correct. We should keep the page where it is, but clean up the TODOs. Are you still willing to work on this, @lannonbr?
