### ISSUE TITLE
Built site fails when deployed to Amazon S3 in 2.9.0 and later

### ISSUE THREAD

**Issue by gswirrl** [gatsbyjs/gatsby#15151]
###  Description

Site builds and serves successfully with `gatsby build && gatsby serve`, but when I copy the built files to an AWS S3 web bucket, the site generates 'resource missing' errors.

(the same AWS bucket has served gatsby sites successfully in the past)

UPDATE: I believe rolling back in same project to

```
  "dependencies": {
    "gatsby": "2.8.8",
    ...
```

fixes the issue. 2.9.0 and later all have the problem)

### Steps to reproduce

(1)
```
gatsby new demo
cd demo
gatsby build
```

(2)
upload files to AWS S3 website-bucket

### Expected result

Website should appear as it does from `gatsby serve`

### Actual result

The js does not run. Console shows errors:

<img width="1277" alt="Screenshot 2019-06-26 at 13 44 07" src="https://user-images.githubusercontent.com/17145418/60180755-a5371b80-9818-11e9-82ad-7c5c382644f6.png">

According to the 'Network' tab of my browser, all files loaded successfully.

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
  npmPackages:
    gatsby: ^2.10.4 => 2.10.4 
    gatsby-image: ^2.2.3 => 2.2.3 
    gatsby-plugin-manifest: ^2.2.0 => 2.2.0 
    gatsby-plugin-offline: ^2.2.0 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0 
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1 
    gatsby-source-filesystem: ^2.1.0 => 2.1.0 
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0 
  npmGlobalPackages:
    gatsby-cli: 2.7.2

**Comment by gswirrl** [comment]
Still fails in 2.11.0

**Comment by gswirrl** [comment]
Still fails in 2.11.5, but with a different error

<img width="808" alt="Screenshot 2019-06-29 at 21 13 03" src="https://user-images.githubusercontent.com/17145418/60389058-cd41ab80-9ab2-11e9-872b-f8bb20c2dc6d.png">

(There IS a 404 page)

**Comment by KyleAMathews** [comment]
Can you investigate more what's happening? gatsbyjs.org is working fine e.g. https://www.gatsbyjs.org/rhhdjd

**Comment by gswirrl** [comment]
Happy to help, but Im kind of stumped tbh! If I run it locally - it works fine. What can i try?

This is what I get if i do `gatsby new foo` => http://swirrl-scratch.s3-website-eu-west-1.amazonaws.com/

Note that the js bombs out before loading the image even.

**Comment by gswirrl** [comment]
The error says the 404 page cant be found, but that's right there at http://swirrl-scratch.s3-website-eu-west-1.amazonaws.com/404/ ???

**Comment by gswirrl** [comment]
One this that I do notice is that this error is in the same function as the previous one, `loadPage`...

**Comment by gswirrl** [comment]
update: yes this indeed seems to be the issue. 

manually setting the content type on everything in `/page-data/*/*.json` to `application/json` fixes it. it's quite a drag to work through all the json files but it works i think. 

im still confused why this has only now started to be an issue however.

you might want to add this fix to the S3 section of the notes?

**Comment by hussainakram** [comment]
@KyleAMathews I'm having the exact same issue on production and it seems on Amazon S3 its not receiving of my *page-data.json* with `content-type: text/plain` whereas locally its `xhr`:

---
<img width="1644" alt="prod-error" src="https://user-images.githubusercontent.com/20062423/60509917-88528a80-9ce7-11e9-8577-49dcb8aa613b.png">

Any idea what might be the cause?

**Comment by silviopaganini** [comment]
also having this problem, anyone found a fix?

**Comment by gswirrl** [comment]
@silviopaganini  the fix is in the thread. change the MIME type of each `page-data.json` to `text/json` (or if your s3 client lets you, set it during upload). it's annoying im afraid, if you have a large site. good luck

**Comment by gswirrl** [comment]
@KyleAMathews could this be problem be avoided by changing

`const isJson = contentType && contentType.startsWith(`application/json`) ` to just check the file extension instead?

**Comment by silviopaganini** [comment]
@gswirrl that's happening locally when you build and serve the files with `gatsby serve`

**Comment by hussainakram** [comment]
To fix this issue I had to: 

- Change my `Makefile` script to have  `--no-mime-magic`:
```
deploy\:production :
	s3cmd sync --no-mime-magic ./public/ s3://samplesite.com
```

- Also added this line at the start of one svg file to fix deploy `content-type`
```xml
<?xml version="1.0" encoding="UTF-8"?>
```

**Comment by silviopaganini** [comment]
OMG

**Comment by colbyfayock** [comment]
development environment fixes aside, is Gatsby's position that this is an environment issue or will there be thought putting into a gatsby solution? i think this kind of problem creates a higher barrier of entry for newcomers

**Comment by KyleAMathews** [comment]
>is Gatsby's position that this is an environment issue or will there be thought putting into a gatsby solution

The expectation is currently that people’s servers would set the mime type to `application/json` but yeah — that’s probably too strict given how many variants there is out there (see e.g. https://stackoverflow.com/questions/477816/what-is-the-correct-json-content-type)

Checking the extension in addition to the mime type seems reasonable — would someone like to PR that in?

**Comment by wardpeet** [comment]
I just created a PR that doesn't look at content type but tries to parse the json.

**Comment by gswirrl** [comment]
@wardpeet woah. thats a much better idea than mine. thank you. 🙏

**Comment by pieh** [comment]
Hey, we just published `gatsby@2.13.6` that _should_ fix this. Please give it a go and let us know if it solved the issue

**Comment by gswirrl** [comment]
@pieh confirmed fixed for me! 🎉 thank you! 👍

**Comment by Rajarml** [comment]
Our PWA is hosted in Azure websites and we can't upgrade Gatsby higher than 2.9.2 (since the page-data.json change). The issue occurs only after an app deployment (locally everything is fine).
Testing the version 2.13.12 fix the problem :)

**Comment by wardpeet** [comment]
Seems like we fixed this bug 🎉 let's close 😄
