### ISSUE TITLE
run Gatsby through WSL2

### ISSUE THREAD

**Issue by NickyMeuleman** [gatsbyjs/gatsby#15163]
Had trouble running `gatsby develop` through WSL2 (Windows subsystem for Linux v2)

### context
WSL2 is available, it is still in the early stages.
https://devblogs.microsoft.com/commandline/wsl-2-is-now-available-in-windows-insiders/
https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes

### Steps to reproduce

Run `gatsby develop` from WSL2.

### Actual result

Browser reports `connection refused`

### (Temporary) solution

1. Get the correct ip address by running
```sh
ip addr | grep eth0
```
and copying the ip after `inet`

2. Start the Gatsby development server with
```sh
gatsby develop -H 0.0.0.0
```
3. Open browser on the ip from step 1 at the port reported by `gatsby develop` (8000)

Thanks to @lannonbr on the Gatsby discord for the solution!

The WSL2 team will probably change how connecting to localhost works in the future, so this solution should be temporary.

**Comment by lannonbr** [comment]
So for now my suggestion was to expose it out to the network with `-H 0.0.0.0`. It works, but I am not sure if this is the perfect solution. This may be good to add to the docs under the [Gatsby on Windows](https://www.gatsbyjs.org/docs/gatsby-on-windows/) page.

**Comment by wardpeet** [comment]
I'm marking this stale. If people aren't running into this too often, this isn't a pressing issue. We can deal with it again when it pops up a bit more or when wsl2 becomes mainstream.

**Comment by lannonbr** [comment]
I think this has been updated in a newer insiders release of WSL 2 as discussed here: https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-insiders-preview-build-18945/

@NickyMeuleman, can you possibly download this new version and verify that this issue has been resolved?

**Comment by NickyMeuleman** [comment]
Ooh, that sounds very exciting!
![image](https://user-images.githubusercontent.com/30179461/61975426-61872b80-afe9-11e9-8787-ba644129e038.png)
will report back :) thanks for the heads up.

**Comment by wardpeet** [comment]
I'm unsure this is something we can address as of now. WSL 2 is still in beta and might be a windows issue rather than a gatsby issue.

**Comment by lannonbr** [comment]
Alright yeah that's fine. Thanks anyway for the testing @NickyMeuleman

**Comment by lannonbr** [comment]
I will close this now and keep it on file so if this issue persists when WSL2 is stable this fall, then we can look into it.

**Comment by lannonbr** [comment]
Alright, reopening the issue

**Comment by jnmsl** [comment]
Working with gatsby on WSL 2 is in general extremely slow. The workaround doesn't even work for me.

**Comment by alago1** [comment]
I'm having trouble running `gatsby develop -H 0.0.0.0 --https` on WSL2

This is purely a guess but from what I've read of the [documentation on the topic](https://www.gatsbyjs.com/docs/local-https/), devcert is adding the certificate on the wsl side of things which means that when opening the site through a browser (on the windows side) the server is just refusing to connect.
