### ISSUE TITLE
Example of using gatsby-image in stateful components

### ISSUE THREAD

**Issue by SilencerWeb** [gatsbyjs/gatsby#15175]
It would be cool to have an example of using `gatsby-image` in stateful components since `useStaticQuery` won't work in them because `useStaticQuery` uses hooks.

**Comment by lannonbr** [comment]
So you can use the plain StaticQuery as described in the docs here: https://www.gatsbyjs.org/docs/static-query/

This is in a functional component here, but nothing is blocking you from using it in a class component. With that, what are you trying to do with this in particular?

**Comment by SilencerWeb** [comment]
@lannonbr, the problem is that somebody who is using `gatsby` and `gatsby-image` can even not know about existing of `StaticQuery` and it would be hard to find a solution for using `gatsby-image` in stateful components. I didn't check any `gatsby` tutorials, I jumped right into working on a real project for a customer and I had a struggle with this and decided to share it with the community in case you'll find it useful. Feel free to close the issue :)

**Comment by lannonbr** [comment]
Could you try to rephrase that? I'm unsure what you are trying to convey.

**Comment by prestonso** [comment]
Hi @SilencerWeb,

Thank you so much for opening this issue! As @lannonbr mentions, this functionality is available through `StaticQuery`. You have impeccable timing, as our Learning team is currently working on a more discoverable recipe for `StaticQuery`. This is being tracked in #14979 if you have any thoughts on how we can make our documentation about `StaticQuery` even better.

Thanks for your support of the Gatsby community! 💪 💜
