### ISSUE TITLE
How do I run createPage after a promise? Trying to pass cloudinary image URLs to createPage

### ISSUE THREAD

**Issue by ArthurHwang** [gatsbyjs/gatsby#15176]
## Summary
I get a `createPage was called outside of its expected asynchronous lifecycle` error when I try to use createPages in a `then` promise block.

Also a webpack error : ` WebpackError: Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-d  ecoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev
  environment for full errors and additional helpful warnings.`

## Relevant information

What I am trying to do is use cloudinary npm package to upload each image to cloudinary  that comes back from the node creation process when querying from my wordpress blog,  then pass the cloudinary URL it gives back from the response to `createPage`

The reason for doing so is I am hosting my site on netlify.  I cannot access image URLs from the static folder from netlify.  I want to do this for SEO purposes with blog posts being able to dynamically feed in facebook and twitter card images.

The promise image upload portion of my code works, just not createPages after the promise.

### File contents (if changed)

`gatsby-node.js`:  
```
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`
})

const path = require("path")
const createPaginatedPages = require("gatsby-paginate")
const cloudinary = require("cloudinary").v2

cloudinary.config({
  cloud_name: `${process.env.CLOUDINARY_NAME}`,
  api_key: `${process.env.CLOUDINARY_API_KEY}`,
  api_secret: `${process.env.CLOUDINARY_SECRET}`
})

// Implement the Gatsby API “onCreatePage”. This is
// called after every page is created.
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions

  // page.matchPath is a special key that's used for matching pages
  // only on the client.
  if (page.path.match(/^\/app/)) {
    page.matchPath = "/admin/*"

    // Update the page.
    createPage(page)
  }
}

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions

  await graphql(
    `
        {
          allWordpressPost(limit: ${process.env.BLOG_LIMIT}) {
            edges {
              node {
                id
                slug
                title
                content
                excerpt
                date
                modified
                categories {
                  name
                }
                author {
                  name
                }
                featured_media {
                  localFile {
                    childImageSharp {
                      fluid {
                        src
                        srcSet
                        sizes
                        aspectRatio
                      }
                    }
                  }
                }
              }
            }
          }
        }
      `
  ).then(result => {
    if (result.errors) {
      console.log(result.errors)
      reject(result.errors)
    }

    createPaginatedPages({
      edges: result.data.allWordpressPost.edges,
      createPage: createPage,
      pageTemplate: "./src/components/elements/blog/PostsTemplate.tsx",
      pageLength: 5,
      pathPrefix: "/blog"
    })

    result.data.allWordpressPost.edges.forEach(({ node }) => {
      const cloudinaryPromise = new Promise((resolve, reject) => {
        return cloudinary.uploader.upload(
          `./public${node.featured_media.localFile.childImageSharp.fluid.src}`,
          (error, result) => {
            if (result) {
              resolve(result)
            }
            if (error) {
              reject(new Error("ERROR WITH CLOUDINARY UPLOAD"))
            }
          }
        )
      })

      cloudinaryPromise.then(data => {
        createPage({
          path: "blog/" + node.slug,
          component: path.resolve(
            "./src/components/elements/blog/PostTemplate.tsx"
          ),
          context: {
            slug: node.slug,
            imageSharp: node.featured_media,
            title: node.title,
            author: node.author.name,
            categories: node.categories,
            modified: node.modified,
            content: node.content,
            excerpt: node.excerpt,
            cloudinaryURL: data.url
          }
        })
      })
    })
  })
}

```

**Comment by DSchau** [comment]
Hello @ArthurHwang!

Thanks for the question. This looks to be an issue with not `await`ing at the right moment, specifically the graphql invocation is awaited, but the _result_ of iterating over your pages is not awaited.

Hard to _ensure_ this is the fix without a [reproduction](https://gatsby.dev/reproduction) but I’m pretty confident this should do the trick!

Please check out [this Gist](https://gist.github.com/DSchau/f0db8c7fce24913063cdf6330c228e63) to see the completed code.

I’m going to close this as answered, but please re-open if I or a member of @gatsbyjs/core can help further.

Thanks!

**Comment by DSchau** [comment]
Also re: your second error (sorry I missed that!):

> WebpackError: Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

The actual error is:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

which typically indicates you’re importing the wrong thing. This is typically for a few reasons, but most commonly:

- Using a destructured form of a default export
- Not exporting in a file

In other words — usually it’s an indication that you’re importing something that may not be named as you expect, or it may not be exported at all.

Thanks!
