### ISSUE TITLE
ERR! code 128 - fatal: reference is not a tree

### ISSUE THREAD

**Issue by i-bsd** [gatsbyjs/gatsby#15174]
## Description

After git cloning any of my Gatsby projects (which have always worked fine), I'm now getting:

```
npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git checkout b7d54921d849e6108f968581bf31e41929fd992f
npm ERR! fatal: reference is not a tree: b7d54921d849e6108f968581bf31e41929fd992f
npm ERR!
```
This is a sudden change. Log file doesn't provide any information.

### Steps to reproduce

git clone *repo*
cd *dir*
*npm i*

### Expected result

Should install node modules as it usually does.

### Actual result

```
npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git checkout b7d54921d849e6108f968581bf31e41929fd992f
npm ERR! fatal: reference is not a tree: b7d54921d849e6108f968581bf31e41929fd992f
npm ERR!
```

### Environment

```System:
    OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  npmPackages:
    gatsby: ^2.10.5 => 2.10.5
  npmGlobalPackages:
    gatsby-cli: 2.7.2

```
Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by i-bsd** [comment]
Actually, just found this toward the top of the log file:

```
8033 silly fetchPackageMetaData error for first-mate-select-grammar@git+https://github.com/atom/first-mate-select-grammar.git#b7d54921d849e6108f968581bf31e41929fd992f Command failed: /usr/bin/git checkout b7d54921d849e6108f968581bf31e41929fd992f
8033 silly fetchPackageMetaData fatal: reference is not a tree: b7d54921d849e6108f968581bf31e41929fd992f
```

Does that mean there's an issue with `first-mate-select-grammar`?

**Comment by prestonso** [comment]
Hi @i-bsd,

Thanks so much for opening this issue! As stated, this is slightly tangential to Gatsby, and after cloning a few of my own Gatsby codebases, I couldn't reproduce this issue or find `first-mate-select-grammar` among any of the dependencies.

It looks like this may be an issue with Atom's git integration, and I see you opened an issue in the `first-mate-select-grammar` repository.

If this is not the case, or if we can help further—please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪 💜
