### ISSUE TITLE
[gatsby-image] Art direction feature does not support different aspect ratios

### ISSUE THREAD

**Issue by brimtown** [gatsbyjs/gatsby#15189]
## Description

When using the new art direction feature introduced in #13395 with `fluid` images that have different aspect ratios, the padding height generated by `gatsby-image` only uses the aspect ratio of the first image passed to `fluid`.

### Steps to reproduce

1. Create a `sources` array with two `fluid` images with different aspect ratios, and pass this to `fluid`.

```js
const mobileImage = {
  aspectRatio: 0.75,
  src: "https://via.placeholder.com/1440x1920",
  srcSet:
    "https://via.placeholder.com/300x400 300w, https://via.placeholder.com/600x800 600w, https://via.placeholder.com/900x1200 900w, https://via.placeholder.com/1440x1920 1440w",
  sizes: "(max-width: 1440px) 100vw, 1440px",
};

const desktopImage = {
  aspectRatio: 1.7777777778,
  src: "https://via.placeholder.com/1600x900",
  srcSet:
    "https://via.placeholder.com/300x169 300w, https://via.placeholder.com/600x338 600w, https://via.placeholder.com/1200x675 1200w, https://via.placeholder.com/1600x900 1600w",
  sizes: "(max-width: 1600px) 100vw, 1600px",
};

const sources = [
  {
    ...mobileImage,
    media: `(max-width: 767px)`,
  },
  {
    ...desktopImage,
    media: `(min-width: 768px)`,
  },
];

// Initialize image as <Image fluid={sources} />
```

Example site:
https://inspiring-gates-f6a434.netlify.com/fluid

### Expected result

When viewing the art-directed image at a breakpoint corresponding to `desktopImage`, the padding in `gatsby-image` should use `desktopImage`'s aspect ratio instead of `mobileImage`'s.

### Actual result
`gatsby-image` just uses the aspect ratio of the first image (`mobileImage`) for all subsequent images in `sources`.

### Environment

Introduced in `gatsby-image@2.2.1`

cc @polarathene @wardpeet @antoinegrelard

Discussed at https://github.com/gatsbyjs/gatsby/pull/13395#issuecomment-493640397
Fixes https://github.com/gatsbyjs/gatsby/pull/13395#issuecomment-505870830

**Comment by polarathene** [comment]
I should have time in the next week or two to tackle this. 

Although I don't think we can fix the pre-rendered placeholders(baked into the markup delivered on page request) until React kicks in and can run the appropriate JS to update. Maybe if some media query style was injected into a style tag in the header?(wouldn't work with inline styles on the component afaik) I'm not sure how to go about that with Gatsby.

My plan to fix this within the component is the JS method [`matchMedia()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia), which should allow for detecting when to swap the default `image` for a variant and update those related props accordingly. If anyone wants to tackle that before I have the time to, you're welcome to :)

**Comment by brimtown** [comment]
Awesome! I think @KyleAMathews had an idea to use https://github.com/gaearon/react-side-effect somehow to inject those style rules at build time? Not sure if I remember the specifics, but maybe he could chime in as well.

Keeping the pre-rendered images seems fairly important (at least for our use-cases), and considering that apps can work around this limitation by [writing their own styles](https://github.com/gatsbyjs/gatsby/pull/13395#issuecomment-506402173), it would be a bummer to lose the pre-rendering entirely for art directed images.

**Comment by KyleAMathews** [comment]
>Awesome! I think @KyleAMathews had an idea to use https://github.com/gaearon/react-side-effect somehow to inject those style rules at build time? Not sure if I remember the specifics, but maybe he could chime in as well.

Yeah :-)

We should be able to catch during SSR when an art direction image is rendered and inject in the head the appropriate css.

That's the same technique we can use for preloading/prefetchinig images https://github.com/gatsbyjs/rfcs/blob/prefetch-images/text/0000-support-prefetching-images.md

**Comment by polarathene** [comment]
@ehannes  I don't think there is. I've not had time to allocate to working on this unfortunately due to other events. It's likely still a month away until I can work on this.

**Comment by jgoslow** [comment]
+1 on this - definitely a broken feature until this is resolved. In my experience, "art direction" usally requires a change in aspect ratio to be useful.

**Comment by polarathene** [comment]
As long as nothing else comes up on my end, I should be able to allocate time to this in November.

**Comment by danboyle8637** [comment]
I just posted a question about this and I am having this issue where different aspect ratios are not supported... or least it seems to be the case. 

https://github.com/gatsbyjs/gatsby/issues/19702

**Comment by polarathene** [comment]
@danboyle8637 As much as I'd love to resolve the issue and submit a PR with the feature/fix, I don't have a personal need for it which makes it difficult to justify allocating time towards for me. 

I was hoping by now to be employed, but for the entire year I am rarely considered for interviews, employers seem to care very little about my contributions/experience when I lack the "professional"(employed) experience and the growing gap since my last role isn't helping.

This remains on my backlog but it's low priority, I will get to it eventually but I would encourage anyone else to take a shot if they have the time spare, or to setup a bounty, if you're earning money from dev work and would like someone else to sort this out, considering how long it's been open, it's probably the best way to go and support the feature financially a little. It'd definitely help raise the priority in my case, so that I can pay bills :)

If you want to tackle it, I'm pretty sure using JS with `matchMedia()` call is the way to go(as mentioned/linked above).

**Comment by danboyle8637** [comment]
I am rushing this morning and didn't get to look long enough or test but I did find this which is interesting. It looks like it's using the aspect ratio for only the first image element in the array of sources... and not iterating over each one to recalculate the padding bottoms... These are my messy notes on the code... what do you think?

![IMG_0151](https://user-images.githubusercontent.com/26289514/69427798-e6672500-0cfd-11ea-9a72-0fa63a8d6cf5.jpeg)

**Comment by jgoslow** [comment]
@danboyle8637 that's correct.  You'll need to add a listener for screen resize and set the padding accordingly.  Or since it's set dynamically with javascript anyway, you could just set the height.

**Comment by polarathene** [comment]
@danboyle8637 yes I pointed that out in your [linked issue](https://github.com/gatsbyjs/gatsby/issues/19702#issuecomment-557359083). As has been discussed earlier, you want to use `matchMedia()` with JS to handle this correctly, the current code has no way of knowing what image will be used so defaults to the first image.

Related issues to this with `fixed` images as well are pointed out [here](https://github.com/gatsbyjs/gatsby/pull/13395#issuecomment-493640397).

**Comment by jarkkosyrjala** [comment]
This seems to be working correctly with gatsby-image 2.3.2.
Fixed in  #19887 and/or #21431 I guess.

Thanks 👍

**Comment by andrezimpel** [comment]
> #21431

Really? I'm using 2.3.4 and it is unfortunately not working. :/

**Comment by judewang** [comment]
This has not be fixed, the bug is still happening in production. https://github.com/gatsbyjs/gatsby/pull/21431#issuecomment-618961354

**Comment by IanLunn** [comment]
I am also finding it hasn't been fixed. Any update on this or pointers on how to work around it please?

**Comment by polarathene** [comment]
Please sub to [this issue](https://github.com/gatsbyjs/gatsby/issues/24748) to be notified of a fix, continue discussion there.
