### ISSUE TITLE
Modifying postcss plugins

### ISSUE THREAD

**Issue by imjared** [gatsbyjs/gatsby#1518]
It seems like the plugins (import, cssnext, etc)  get [merged into config](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L400-L410)  in the base webpack config and there's not really a way to override. We've been using postcss-import with the `path` option specified but:

1. it needs to run before all postcss plugins
1. it doesn't seem like we can actually override the postcss settings since they're getting merged in and there's not an option like `config.removeLoader` since the postcss plugins don't technically sit in a config.

Any ideas how we could bypass this? I like that postcss works out of the box but the options seem a little opinionated. That said, I seem to appreciate your opinions since this whole project is pretty 💯

**Comment by jbolda** [comment]
@imjared I believe you are looking for: https://www.gatsbyjs.org/docs/add-custom-webpack-config/

**Comment by imjared** [comment]
Hey @jbolda, I had taken a look at that previously and I'm not quite sure it addresses the issue I'm having. The custom webpack config seems to only allow us to add/remove loaders and add additional settings to config. We don't seem to have the ability to remove settings from `config` since [they're merged in here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L400-L410).

Regardless, I did some digging and as a workaround used a postcss.config.js and it worked. I'd prefer to handle the configuration programmatically but in the interest of moving on to the next issue, this works for now.

**Comment by jbolda** [comment]
You can override the plugins themselves in the same manner. I guess that first link I have didn't specifically go into that. The postcss-sass plugin serves as a decent example to override/change the plugins.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-postcss-sass/src/gatsby-node.js

**Comment by dlindahl** [comment]
I need to set a config option in `cssnext`, but the [default configuration references `program.browsersList`](https://github.com/gatsbyjs/gatsby/blob/c3408ab321e9d16c0186a7264b9b7be33dbaedf5/packages/gatsby/src/utils/webpack.config.js#L423). `gatsby-node.js` does not get passed a reference to `program`, so I am unable to copy/paste that particular setup into my custom override.

@imjared Can you provide any details about how you got `postcss.config.js` to work? PostCSS never pulled in my attempt at that workaround

**Comment by imjared** [comment]
hey derek- i'm traveling this weekend but will take a look early next week

**Comment by KyleAMathews** [comment]
@dlindahl btw, `program` is passed in the first argument.

**Comment by dlindahl** [comment]
@KyleAMathews to `modifyWebpackConfig`? In `gatsby-node.js`?

I only see:

```js
[ 'config',
  'stage',
  'pathPrefix',
  'boundActionCreators',
  'loadNodeContent',
  'store',
  'getNodes',
  'getNode',
  'hasNodeChanged',
  'reporter',
  'getNodeAndSavePathDependency',
  'cache' ]
```

Am I looking in the right place?

**Comment by KyleAMathews** [comment]
Oh sorry — forgot program is in the store. So `store.getState().program`
