### ISSUE TITLE
[v2] A node's custom string field with a file name is replaced with an object of the File type

### ISSUE THREAD

**Issue by zubko** [gatsbyjs/gatsby#15200]
## Description

Creating a string field with a value === filename for example ("2019-03-01-hello-world.md") will replace that string with the object of a File type

This is may be advanced but very unexpected behavior and it can backfire very hard.

### Steps to reproduce

<img width="471" alt="Screen Shot 2019-06-28 at 9 58 19 AM" src="https://user-images.githubusercontent.com/16039/60324769-5612f700-998e-11e9-8fda-bf1ce51dd575.png">

Checkout this repo and this commit:

https://github.com/zubko/tmp-gatsby-issue-reproduce-my-blog-starter/commit/e96180a4fd4efebfb570dcc5c90a658ce09b87dc

run `yarn install` `yarn develop`

Inspect the data in GraphiQL

### Expected result

The field should be of a string type with a given value.

### Actual result

The field is of an object type with lots of info in it.

<img width="1392" alt="Screen Shot 2019-06-28 at 10 18 19 AM" src="https://user-images.githubusercontent.com/16039/60324730-3a0f5580-998e-11e9-808f-3f788a058543.png">

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.1
  npmPackages:
    gatsby: ^2.11.0 => 2.11.0 
    gatsby-image: ^2.2.3 => 2.2.3 
    gatsby-plugin-feed: ^2.3.1 => 2.3.1 
    gatsby-plugin-google-analytics: ^2.1.1 => 2.1.1 
    gatsby-plugin-manifest: ^2.2.0 => 2.2.0 
    gatsby-plugin-offline: ^2.2.0 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0 
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1 
    gatsby-plugin-typography: ^2.3.0 => 2.3.0 
    gatsby-remark-copy-linked-files: ^2.1.0 => 2.1.0 
    gatsby-remark-images: ^3.1.0 => 3.1.0 
    gatsby-remark-prismjs: ^3.3.0 => 3.3.0 
    gatsby-remark-responsive-iframe: ^2.2.1 => 2.2.1 
    gatsby-remark-smartypants: ^2.1.0 => 2.1.0 
    gatsby-source-filesystem: ^2.1.1 => 2.1.1 
    gatsby-transformer-remark: ^2.5.0 => 2.5.0 
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0 
  npmGlobalPackages:
    gatsby-cli: 2.7.3

**Comment by pieh** [comment]
Gatsby was doing this by default since v1 (so users can link to files and access file transformations - i.e. image transformation with `sharp`), but you can force this field to be just String by adding:

```
exports.sourceNodes = ({ actions }) => {
  actions.createTypes(`
    type MarkdownRemark implements Node {
      fields: MarkdownRemarkFields
    }
    type MarkdownRemarkFields {
      path: String
    }
  `)
}
```
to your `gatsby-node.js` file

**Comment by zubko** [comment]
Yay! Thanks. 

`createTypes` helped to keep filenames as values.

Do you think it will be good to add a note about type inference & `createTypes` to `createNodeField` API docs? I could make a PR

**Comment by zubko** [comment]
I also think if `createNoteField` could have an optional param `type` it would be more informative than just adding a notice about type inference. Then in the description of the `type` param it would be good to say that the type of the value is inferred and it's possible to force it by using this param.
