### ISSUE TITLE
YouTube push notifications

### ISSUE THREAD

**Issue by sujoys10** [gatsbyjs/gatsby#15206]
I want to get push notifications when a YouTuber uploads a video in his/her channel. 
I have to make pubsubhub server which will listen to this feed and then trigger a build through netlify. 
My question is how to implement this in gatsby? Where to write this server code? Do I have to go with the plug-in way ie. Write the code in gatsby-node js file.. But I think this will not work as gatsby-node.js file run only at build time.

**Comment by prestonso** [comment]
Hi @sujoys10,

Thank you for opening this issue! This unfortunately functionality that is native to Gatsby, and as you mentioned, `gatsby-node.js` runs only at build time.

Whereas there are [documented solutions](https://matienzo.org/2018/websub-static/) for sending WebSub notifications from a static site through [Netlify functions](https://www.netlify.com/docs/functions/), this is only in response to Netlify events and doesn't achieve your goal of triggering them.

Luckily, Netlify has [incoming webhooks](https://www.netlify.com/docs/webhooks/#incoming-webhooks), and you can trigger a Netlify build by issuing a `POST` request as follows from your WebSub service, e.g. in cURL:

```
curl -X POST -d '{}' https://api.netlify.com/build_hooks/XXXXXXXXXXXXXXX
```

Hope this starts you down the right path! Thanks for using Gatsby! 💪 💜

**Comment by sujoys10** [comment]
What will be the callback url to call the netlify function from a websub
service?
"https://hopeful-kepler-23eefa.netlify.com/<func name>" or anything like
that?
