### ISSUE TITLE
[gatsby-source-contentful] gatsby develop script build hangs with high CPU using plugin 

### ISSUE THREAD

**Issue by rudolphfunk** [gatsbyjs/gatsby#15210]
## Description
This issue seems to be related to the gatsby-source-contentful plugin. When running the development server `$ gatsby develop`. `$ gatsby build` builds successfully and `$ gatsby serve` works as expected.

In some cases the build does finish and you can open the site in the browser, but then after the first page load. The site becomes unresponsive and no subsequent page loads work. This is the case for both http://localhost:8000/ and http://localhost:8000/___graphql

### Steps to reproduce

1. Install gatsby-source-contentful plugin:

```
$ npm i -S gatsby-source-contentful@2.1.3
```
2. Setup project as documented [here](https://www.gatsbyjs.org/packages/gatsby-source-contentful)

3. Run develop script
```
$ node node_modules/.bin/gatsby develop
```
**Please note**: The content type being retrieved from contentful is [RichText](https://www.contentful.com/developers/docs/tutorials/general/getting-started-with-rich-text-field-type/), which is being rendered with the `@contentful/rich-text-react-renderer` package although this does not seem to be related.

I can reproduce the issue in a fresh gatsby site hooked up to the same contentful space and therefore does not seem to be related to any proprietary code. My guess is that it is the content being pulled in from contentful that is causing the issue, but I can't pinpoint why. Any help with debugging would be appreciated.

### Expected result

The script should complete. CPU should remain stable. The site should load on host: http://localhost:8000. 

### Actual result

The script fails to complete and hangs after run page queries. A node process starts eating CPU (>90%). Opening up http://localhost:8000/ in browser results in loading tab with no content. 

Output from command line:
```
> gatsby develop

success open and validate gatsby-configs - 0.030 s
success load plugins - 0.460 s
success onPreInit - 0.011 s
success initialize cache - 0.010 s
success copy gatsby files - 0.121 s
success onPreBootstrap - 0.009 s
Starting to fetch data from Contentful
Fetching default locale
default locale is : en
contentTypes fetched 5
Updated entries  0
Deleted entries  0
Updated assets  0
Deleted assets  0
Fetch Contentful data: 426.566ms
success source and transform nodes - 0.602 s
success building schema - 0.415 s
success createPages - 0.072 s
success createPagesStatefully - 0.060 s
success onPreExtractQueries - 0.013 s
success update schema - 0.033 s
success extract queries from components - 0.206 s
success write out requires - 0.019 s
success write out redirect data - 0.006 s
success Build manifest and related icons - 0.089 s
success onPostBootstrap - 0.105 s
⠀
info bootstrap finished - 4.736 s
⠀
success run static queries - 0.034 s — 3/3 118.90 queries/second
success run page queries - 0.050 s — 3/3 91.09 queries/second
...
```

### Environment
```
  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 11.0.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 47.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.11.0 => 2.11.0 
    gatsby-image: ^2.0.34 => 2.2.3 
    gatsby-plugin-manifest: ^2.0.24 => 2.2.0 
    gatsby-plugin-offline: ^2.0.25 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.0.11 => 3.1.0 
    gatsby-plugin-sharp: ^2.0.31 => 2.2.1 
    gatsby-source-contentful: ^2.1.3 => 2.1.3 
    gatsby-source-filesystem: ^2.0.28 => 2.1.1 
    gatsby-transformer-sharp: ^2.1.17 => 2.2.0 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

**Comment by rudolphfunk** [comment]
Attached is a CPU profile recorded while the issue was observed.
[CPU-20190716T110559.cpuprofile.zip](https://github.com/gatsbyjs/gatsby/files/3396240/CPU-20190716T110559.cpuprofile.zip)

**Comment by wardpeet** [comment]
Could it be processing images? Downloading and optimizing them?

Thank you for the cpuprofile, I'll have a look.

**Comment by rudolphfunk** [comment]
After some initial tests it seems that Node: 11.0.0 is the issue:

> It seems the error was being caused by the node version I was using. I was using v11 for newer projects which appears to be incompatible with gatsby-source-contentful. Reverting back to stable (10.16) works for both projects.
https://github.com/gatsbyjs/gatsby/issues/15784#issuecomment-512165544

After switching to Node: v10.15.3 and rebuilding packages the issue seems to be resolved.

**Comment by rudolphfunk** [comment]
> Could it be processing images? Downloading and optimizing them?
@wardpeet - it seems unrelated. I have tried with and without images.

**Comment by freiksenet** [comment]
Closing as a duplicate.

**Comment by freiksenet** [comment]
Sorry closed wrong issue :)

**Comment by freiksenet** [comment]
Closing as this seems resolved.

**Comment by victsant** [comment]
I am seeing this issue using `gatsby develop`. 

## Plugin:
`"gatsby-source-contentful": "^2.1.20"`

## Tried the following node versions:
`node v10.16.0` and `node v10.15.3`

##  Results: Hangs at 95-97%
`Starting to fetch data from Contentful
Fetching default locale
default locale is : en-US
contentTypes fetched 3
Updated entries  58
Deleted entries  0
Updated assets  488
Deleted assets  0
Fetch Contentful data: 2090.733ms
⠙ source and transform nodes
[==========================  ]   63.036 s 464/488 95% Downloading remote files`

It runs successfully with my build in AWS that uses `node v10.16.0`.

Any help with this will be greatly appreciated!
