### ISSUE TITLE
Making babel node_modules transpilation better

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#15213]
## Summary
Improve how we handle node_modules with babel.

We have a few options to explore.
1) Use a smaller babelrc file for node_modules
We currently use our babel-preset-gatsby which does lots of things which are probably not needed on node_modules. We probably want to run babel-preset-env to make bundles compatible.
2) only run babel on build-javascript stage. Currently, we run it also in node land, which is probably something we don't need. We want our web bundle to be working with IE11, ... 
3) allow disable of node_modules with a plugin, `gatsby-plugin-babel-no-nodemodules`. This plugin will remove our node_modules runner from gatsby.

### Motivation
It seems like people are having issues with our latest Gatsby change. Transpiling node_modules with babel. It may cause slow builds or memory issues.

- https://github.com/gatsbyjs/gatsby/issues/15190
- https://github.com/gatsbyjs/gatsby/issues/15207
- https://github.com/gatsbyjs/gatsby/issues/15183
- https://github.com/gatsbyjs/gatsby/pull/14111#issuecomment-506747028

**Comment by angeloashmore** [comment]
Any progress on this? Transpiling `node_modules` makes sense to perform by default, but having a way to opt out completely would be helpful. Something like Option 3 seems like the best option.

As evident in other issues, build times have more than doubled as a result of this change (~5 minutes to ~12 minutes our case). In addition to higher costs for those paying by the second, we're actually seeing builds time out on Netlify occasionally.

**Comment by jasonsoden** [comment]
I'd also like an update on this. We're stuck on gatsby v2.10.5 because 2.11 "enabled babel-loader for all dependencies" which completely killed our build time. We're literally blocked because of the 2.11 change and can't upgrade due to build timeouts.  Using `--max_old_space_size=4096` does nothing. Gatsby used to build so fast. How do we opt-out of the new ~~bug~~ feature? If there's no fix we're going to have to drop Gatsby altogether.

**Comment by thomasMary** [comment]
Any update or workaround? We're too stuck on Gatsby v2.10.5

**Comment by manekinekko** [comment]
@thomasMary this seems to be a workaround: https://github.com/gatsbyjs/gatsby/issues/15190#issuecomment-506489552

**Comment by wardpeet** [comment]
I've created `gatsby-plugin-remove-dependency-transpilation` so you can disable the step. Note that we made the step a little bit better from 2.24.0 but if you want to omit it as a whole you can use my plugin. Note this could break your node_modules if they aren't transpiled correctly

````
# gatsby-plugin-remove-dependency-transpilation

Removes the dependency transpilation step from Gatsby.

## Install

```shell
npm install gatsby-plugin-remove-dependency-transpilation
```

## Configure

```javascript
// In your gatsby-config.js
plugins: [`gatsby-plugin-remove-dependency-transpilation`];
```
````
