### ISSUE TITLE
[docs] Blog & Website Contributions page missing "Excerpt" info

### ISSUE THREAD

**Issue by caitlinthefirst** [gatsbyjs/gatsby#15226]
I noticed several blog post files include an "excerpt" field in their frontmatter, but the documentation instructions and template for contributing to the blog don't include this field or info on what to write. 

I can make a PR for this, but I wanted to check that it wasn't omitted on purpose.

**Comment by lannonbr** [comment]
@caitlinthefirst I don't believe there's any particular reasoning that it isn't there, but I think this is a great issue and we'd love a PR for this! Feel free to assign yourself to this issue

**Comment by marcysutton** [comment]
Closed with #15335. Thanks for your contributions @caitlinthefirst!
