### ISSUE TITLE
[docs][guides] improve publishing to Github Pages doc

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#15229]
## Summary

In feedback from gatsbyjs.org, the [Deploying to GitHub Pages](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/) guide could use an update. Specifically:

"What about if I wanted to use the doc/ folder option instead of a dedicated gh-pages branch?"

That process is described here: https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

It would be good to add a section to the GitHub Pages deployment guide to provide that information inline, so people don't have to go hunting for it. If anyone else has encountered gotchas with GitHub pages, we could also include them as part of this effort.

The page needing an update: https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/

**Comment by arshadkazmi42** [comment]
I can work on this, if its still available for grab. I think we can have a redirect url to that page from gatsby page.

**Comment by lannonbr** [comment]
Sorry @arshadkazmi42 but @Aswinpookkatt already has a PR up to resolve this.

**Comment by arshadkazmi42** [comment]
@lannonbr Thank  you for the quick response. Will explore other issues.
