### ISSUE TITLE
Module Import / Export Conventions

### ISSUE THREAD

**Issue by atrauzzi** [gatsbyjs/gatsby#1522]
_Realizing that the JS ecosystem is varied with lots of different niches_, some of the export syntax mixing used by gatsby may risk causing headaches.  It might be worthwhile to centralize around one.

Examples:

```
import Link from "gatsby-link"
import { Helmet } from "react-helmet"
```
For the snippet above, gatsby seems to be exporting `default`, while one of its dependencies - helmet - doesn't.

```
module.exports = class HTML extends React.Component<any, any> {
```
In this example, I'm forced to use the `module.exports` syntax so that gatsby can bootstrap `html.tsx`.

Obviously because I use TypeScript, I'm a bit biased, but they have at least [gone so far as to document their rationale](https://basarat.gitbooks.io/typescript/content/docs/tips/defaultIsBad.html).
I would love to see gatsby adopt either only using named exports, or ensure that any code that people have to author as part of a gatsby project experience is consistently one type.  Again, the TS book docs make a pretty decent case for named exports and this ensures that you retain the maximum of flexibility while also making life easier on users consuming your code.

✏️

**Comment by KyleAMathews** [comment]
So it using es6 exports doesn't work with the HTML component right now? Definitely want to make the examples as good as possible since a lot of people will base their projects off them.

**Comment by KyleAMathews** [comment]
@fabien0102 thoughts?

**Comment by atrauzzi** [comment]
Well, I don't know if it's necessarily stale...

**Comment by fabien0102** [comment]
https://github.com/fabien0102/gatsby-starter/blob/master/src/html.tsx#L23

If you talk about that, I'm agree with you (even if I don't saw this issue before ^^)
