### ISSUE TITLE
[docs][guides] improvements to Why Gatsby Uses GraphQL

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#15235]
## Summary

In feedback from gatsbyjs.org, some questions surfaced that would be nice improvements to the [Why Gatsby Uses GraphQL Page](https://www.gatsbyjs.org/docs/why-gatsby-uses-graphql/). Specifically:

> "What causes allProductsJson to appear in the graphql results? What/where is it defined? Is this example on github? A link to the working example would be helpful."

For folks following along, the introduction of `allProductsJson` isn't explained clearly enough. It would help to explain where that key comes from, in explicit detail!

@jlengstorf is there also a live example we can link to?

This issue is open for anyone to pick up, once we answer where the live example lives (if there isn't one, we should create one).

**Comment by raleytom** [comment]
I'd be happy to try and work on this, although I myself am a bit confused as to where the allProductsJson key comes from. If someone could clarify that, I can try and tackle this.

**Comment by tom-raley** [comment]
I'd be happy to try and work on this, although I myself am a bit confused as to where the allProductsJson key comes from. If someone could clarify that, I can try and tackle this.

**Comment by jlengstorf** [comment]
Oh whoops, I missed this the first time around. I did not create a live example.

@tom-raley the `allProductsJson` key is created by `gatsby-transformer-json`. You can see how the names are generated if you play with filenames and plugin settings — I can't remember off the top of my head exactly how it works.

Good luck!

**Comment by tom-raley** [comment]
Apologies, really haven't had time to work on this lately and probably won't for awhile. Someone else is welcome to give it a go!
