### ISSUE TITLE
[docs][guides] add details about user stylesheets with Styled Components

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#15232]
## Summary

In feedback from gatsbyjs.org, the [Styled Components](https://www.gatsbyjs.org/docs/styled-components/) styling doc could use a little more information around user stylesheets. Specifically:

> in the last part where would a user write their CSS for the line "A site user could then write their own CSS styles matching HTML elements with a class name of .container, and it wouldn’t be affected if the CSS-in-JS output changed."

It could be that the term "user" is what's confusing here, since this section is referring to end-users creating their own stylesheets for accessibility and other purposes. I have three recommendations:

- Refer to users in this scenario as "end-users" to differentiate from "Gatsby users" (developers)
- Include a short CSS snippet that references the `.container` class, and give it a file title like `css:title=user-stylesheet.css`.
- Add a link to more information on writing and including user stylesheets. Here's a recent-ish-looking post we could link to by Chris Coyier: https://mediatemple.net/blog/tips/bend-websites-css-will-stylish-stylebot/

**Comment by luizcieslak** [comment]
Hi Marcy, I'd like to take this one if it's not taken

**Comment by marcysutton** [comment]
Absolutely @luizcieslak, we'd love to have your contributions! Let me know if you have any questions.

**Comment by kushthedude** [comment]
@marcysutton Up for claims ?

**Comment by marcysutton** [comment]
@kushthedude yes, go for it!
