### ISSUE TITLE
[docs][guides] new doc on Working with Images in Blog Posts

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#15234]
## Summary

In feedback from gatsbyjs.org and an ongoing part of improving the [images](#14529) and [MDX workflows](#14258), it would help to include a new reference guide on working with images in blog posts. Specifically, there was this question:

> "I don't understand how I specify the filename of the image(s) used for each blog post (for example)? It seems like this only handles a fixed image name?" 

The page referenced was [Using Gatsby Image](https://www.gatsbyjs.org/docs/using-gatsby-image/ ), which is in the context of components and queries where you know filenames already. Recommended improvements to that page and [Working With Images in Gatsby](https://www.gatsbyjs.org/docs/working-with-images/) can be found in #14753. 

This "Images in Blog Posts" page, on the other-hand, would include new information specific to working with images in Markdown and MDX. I recommend placing it in the [Images, Files, and Video](https://www.gatsbyjs.org/docs/images-and-files/) section and linking from the [Writing Pages in MDX](https://www.gatsbyjs.org/docs/mdx/writing-pages/) doc. It could include:

- querying featured images from post frontmatter when [creating dynamic pages](https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/) with `gatsby-node.js`, for social sharing or embedding in the page ([example](https://github.com/marcysutton/gatsby-site/blob/master/src/templates/post.js#L62))
- using [`gatsby-remark-images`](https://gatsby-mdx.netlify.com/guides/using-gatsby-remark-images/) (maybe this links to another new doc as part of #14890?)
- Other techniques for leveraging MDX to load images, if any. This likely depends on https://github.com/gatsbyjs/gatsby/issues/10482.

This issue is open if anyone wants to pick it up!  Please refer to the [Gatsby Style Guide](https://www.gatsbyjs.org/contributing/gatsby-style-guide/) and [docs templates](https://www.gatsbyjs.org/contributing/docs-templates/) for more information on the required format.

See other [image related GitHub issues](https://github.com/gatsbyjs/gatsby/labels/topic%3A%20images%2Fmedia).

**Comment by lannonbr** [comment]
Hey Marcy, I'd be interested in working on this issue. I was actually just helping someone with this (specifically the first bullet), and I think this will be very useful for those who wish to add images to pages written in markdown.

**Comment by lannonbr** [comment]
Hope to get a draft PR up in a day or two
