### ISSUE TITLE
Requiring a local project file from gatsby plugin results in strange warning

### ISSUE THREAD

**Issue by NathHorrigan** [gatsbyjs/gatsby#15248]
## Description

When requiring a local project file from a file in the Gatsby plugin (doesn’t matter what type of JS file) you get the following error for multiple non-js file types:

```
 warning  in ./public/index.html
⠀
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <!DOCTYPE html><html><head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><title

 @ . sync ^\.\/.*$
 @ ./node_modules/gatsby-source-wagtail/preview-template.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
⠀
 warning  in ./LICENSE
⠀
Module parse failed: Unexpected token (1:4)
You may need an appropriate loader to handle this file type.
> The MIT License (MIT)
|
| Copyright (c) 2015 gatsbyjs

 @ . sync ^\.\/.*$
 @ ./node_modules/gatsby-source-wagtail/preview-template.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
⠀
 warning  in ./public/manifest.webmanifest
⠀
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
> {"name":"gatsby-starter-default","short_name":"starter","start_url":"/","background_color":"#663399","theme_color":"#663399","display":"minimal-ui","icons":[{"src":"icons/icon-48x48.png?v=008654519ce705ac7bc44303a9014606","size

 @ . sync ^\.\/.*$
 @ ./node_modules/gatsby-source-wagtail/preview-template.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
```

### Steps to reproduce

`require(‘…’)` a file from main project
 from `gatsby-node.js` file of a plugin.

### Expected result

Warning free build

### Actual result

Warnings from Gatsby compiler

### Environment

System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.11.0 => 2.11.0
    gatsby-image: ^2.2.3 => 2.2.3
    gatsby-plugin-compile-es6-packages: ^1.1.0 => 1.1.0
    gatsby-plugin-manifest: ^2.2.0 => 2.2.0
    gatsby-plugin-offline: ^2.2.0 => 2.2.0
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1
    gatsby-source-filesystem: ^2.1.1 => 2.1.1
    gatsby-source-wagtail: github:NathHorrigan/gatsby-source-wagtail-grapple => 0.0.1
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0
  npmGlobalPackages:
    gatsby-cli: 2.7.3
    gatsby: 2.11.0

**Comment by KyleAMathews** [comment]
Which file in your plugin is the js file being required from?

**Comment by NathHorrigan** [comment]
Hi @KyleAMathews,

The require happens on both line 23 and 54 of this file: https://github.com/NathHorrigan/gatsby-source-wagtail-grapple/blob/master/src/preview-template.js#L23

The code is fully functional beyond these warnings 😕
