### ISSUE TITLE
Maintain Scroll Position with Layz load images

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#15245]
I use 
https://www.npmjs.com/package/react-lazy-load-image-component
For images because for i can't use gatsby Img - i load images from external server. 

The problem is that when i go to previous page scroll do not point to prev state becouse images upside do not loaded thanks to react-lazy-load. 
How to solve it or can you recomend other layzy loade image plugin which work good with gatsby?  
 
I pass pram "scrollPosition" to LazyLoadImage.

**Comment by pieh** [comment]
Can you provide some sample code? I never used that package, so not sure how it works / behave.

**Comment by bjatwork** [comment]
it's simple, when i use in components 

```
 <LazyLoadImage
                                key={product.product_id}
                                alt={product.product_name}                        
                                scrollPosition={this.props.scrollPosition}
                                src={ this.state.mainImage }/>  
```

insead of 

```
<img
                                key={product.product_id}
                                alt={product.product_name}                        
                        
                                src={ this.state.mainImage }/> 
```

problem occur

My gatsby-browser.js is empty. I tried also manually save and pass scroll position to gatsby-browser.js and manually scroll, but the same effect.
