### ISSUE TITLE
error when trying to add  redux-devtools

### ISSUE THREAD

**Issue by creotip** [gatsbyjs/gatsby#1525]
I'm using the redux example in gatsby repository.
Added devtools to createStore.js

```
const createStore = () => reduxCreateStore(
    reducer, initialState,
    window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
)
```

in dev working fine, but  when i'm using build command im getting this error:

```
Error: ReferenceError: window is not defined
```

**Comment by viatsko** [comment]
build command builds a server-side-rendered (SSR) version of application and window object is not available there (and redux devtools as well are not available in server side rendering mode)

What you can do to solve a problem is to introduce a check for `window` to exist or check for a `process.browser` (webpack polyfills it and process.browser will be `undefined` for a server build`)

**Comment by KyleAMathews** [comment]
Is this still an issue?

**Comment by KyleAMathews** [comment]
If it is, please reopen!

**Comment by adnanfajlur** [comment]
may be, you can check the windows is exist
`
import { createStore, applyMiddleware, compose } from 'redux';
const windowExist = typeof window === 'object';

  windowExist && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
    ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
    : compose;
`

**Comment by leomotta121** [comment]
Can anyone provide example?

**Comment by MutableLoss** [comment]
If the conditional value assignment bothers you, it can be omitted:

```
const composeEnhancers = (typeof window === 'object') ?
 window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__() : compose;
```
