### ISSUE TITLE
Wrong favicon showing up in macOS Safari....

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#15259]
The gatsby favicon is showing up in macOS safari, even though it's been changed quite a while ago. The correct favicon works properly in chrome and firefox. Even the gatsby favicon has been removed for quite some time from the project images folder.

Do I need to do something in safari to make it show up?

**Comment by pieh** [comment]
Might be just stale Safari cache, please try checking https://blog.madjid.net/force-refresh-favicon-safari

**Comment by rchrdnsh** [comment]
hmmm...just tried that, but it does not seem to have worked...I got the gatsby favicon again, instead of mine. Will google around and see if I can find anything as well.
