### ISSUE TITLE
Measure key performance numbers in CI (and via telemetry when makes sense)

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#15272]
Gatsby stakes its reputation on being fast.

We should measure closely key performance numbers so we don't introduce accidental regressions (and so we can know when various improvements are working).

We should measure these in CI and fail builds that slow things down. We should also track bootstrap numbers in telemetry so we can see how things look in the wild.

- develop & build bootstrap up to the first API invocation to measure our startup time
- individual activity timing during build for hello-world starter
- how big is the JS bundles for the front page of the hello world starter

**Comment by jamo** [comment]
Uuh, we've captured the two first points a while back. I should look more into the last one.
Thanks @gatsbybot 😉
