### ISSUE TITLE
[feat]: expose API to validate pluginOptions

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#15281]
## Summary

Passing options to plugins is a key construct in Gatsby, and the plugin ecosystem is key to the power and reusability of any Gatsby application.

However — currently we’re encouraging plugins to implement their own plugin validation API, or worse yet, to not validate options whatsoever. This leads to failing much later than needed, and we should fail early with a nice, helpful error message when an invalid plugin option shape is detected.

### Basic example

Let’s consider Contentful, as an example, specifically gatsby-source-contentful. It accepts `accessToken`, `spaceId`, `host`, etc. to connect to the Contentful instance. These environment variables are oftentimes environment variables (secrets!), which makes this even harder to debug. As a user using this functionality, it may look something like:

```js
require('dotenv').config({
  path: `.env.${process.env.NODE_ENV}`
})

module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: process.env.CONTENTFUL_SPACE_ID,
        accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
        host: process.env.CONTENTFUL_HOST
      }
    }
  ]
}
```

However — if any of those environment variables are undefined, the source plugin will not fail early with a helpful error message, but will rather fail with something like:

> [Gatsby] error Accessing your Contentful space failed.

### Code and Approaches

I see (minimally) two ways we could do this.

1. Overload a lifecycle method (e.g. onPreInit) and pass in a helper/helpers to validate plugin optionsn
1. Create a new lifecycle method (e.g. `validatePluginOptions`)
    - Note: this should be async (Joi.validate is async) and in case e.g. you could do deep validation, e.g. check the accessToken and spaceId are not only provided but valid

I think 2. is preferable, because it will just be a “no-op” in older versions of Gatsby, whereas 1. would potentially break if the helper wasn’t passed as expected.

### Code example

Again, I think there are two approaches here:

1. We use Joi (or equivalent?) and pass it as an option to `validatePluginOptions`
1. We use GraphQL to validate the shape of a plugin’s options, e.g. with an SDL-like approach like the below

```js
exports.validatePluginOptions = ({ validateOptions }) => {
  return validateOptions(`
    # note: not the final API, nor even the best API
    # strawman to begin the discussion
    type SourceContentfulPluginOptions implements PluginOptions {
      accessToken: String!
      host: String # note, could use an enum or scalar here for even richer errors
      spaceId: String!
      environment: String
      downloadLocal: Boolean
    }
  `)
}
```

I prefer 1, but I can see the argument for 2.

### Motivation

Failing fast with a helpful message is _crucial_ to new users of Gatsby, and delivering this functionality will vastly improve the plugin (and theme!) ecosystem in that it enforces consistency.

**Comment by KyleAMathews** [comment]
New life cycle hook makes a lot of sense to me & I think we strongly encourage Joi but given we'd want to push people to use structured errors from the get-go — it might not actually matter too much what they use. They just just do simple checks right on the option object too if they wanted.

**Comment by DSchau** [comment]
Note: per @KyleAMathews as part of this work migrate over the ad-hoc plugin validation that may exist at the plugin level for some plugins already.

Will be a good validation of the approach--and ensuring it accommodates a wide swath of use cases.

**Comment by pieh** [comment]
> 2\. Create a new lifecycle method (e.g. `validatePluginOptions`)
>     
>     * Note: this should be async (Joi.validate is async) and in case e.g. you could do deep validation, e.g. check the accessToken and spaceId are not only provided but valid
> 
> I think 2. is preferable, because it will just be a “no-op” in older versions of Gatsby, whereas 1. would potentially break if the helper wasn’t passed as expected.

Older versions of gatsby will panic saying `validatePluginOptions` is not known API ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/load-plugins/validate.js#L24-L89 )

**Comment by DSchau** [comment]
@pieh I don't really have a solution to that problem, do you? We could:

1. Bump the peerDependency to the version of Gatsby that contains this API (this will be _OK_
1. Use some other method (e.g. onPreInit) and pass a validator, but this seems non-idea

**Comment by moonmeister** [comment]
@mxstbr this can probably be closed...
