### ISSUE TITLE
chore(gatsby-source-filesystem): Deprecate multiple different versions of birth time on File 

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#15287]
@pieh and I noticed that we have three different versions of birth time in File 

- birthTime
- birthtime
- birthtimeMs

Probably want to clean this up at some point 😂

**Comment by spences10** [comment]
What's the work involved in this @sidharthachatterjee?

**Comment by KyleAMathews** [comment]
No one noticed before @pieh went and added that explorer sidebar!!! 😅

**Comment by sidharthachatterjee** [comment]
@spences10 We'll probably want to 

- mark two of them (birthtime and birthtimeMs likely) as deprecated in GraphQL and show a warning when they are used
- update usage across this repo to `birthTime`

**Comment by Simonpedro** [comment]
Hey there! I took a look at this and I decided to follow what @sidharthachatterjee mentioned.
I searched for usages of `birthtime` and `birthtimeMs` in the codebase but I only found them in types declarations files, so I've updated them too.

**Comment by henricazottes** [comment]
We still have those on version `2.1.0`
