### ISSUE TITLE
React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by oste** [gatsbyjs/gatsby#15299]
## Description
Using material-components-web-react Textfield(https://github.com/material-components/material-components-web-react/tree/master/packages/text-field) causes the below stack trace

```
React.Children.only expected to receive a single React element child.
▶ 28 stack frames were collapsed.
(anonymous function)
/.../.cache/app.js:65
  62 | const preferDefault = m => (m && m.default) || m
  63 | let Root = preferDefault(require(`./root`))
  64 | domReady(() => {
> 65 |   renderer(<Root />, rootElement, () => {
  66 |     apiRunner(`onInitialClientRender`)
  67 |   })
  68 | })
```

### Steps to reproduce

1) install "@material/react-text-field": "^0.14.1",
2) add `import TextField, { HelperText, Input } from '@material/react-text-field';` and then `<TextField></TextField>` to pages/index.js

### Expected result

The input should render

### Actual result

Seeing error: `React.Children.only expected to receive a single React element child.`

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.11.7 => 2.11.7
    gatsby-image: ^2.2.3 => 2.2.3
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.3 => 2.2.0
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1
    gatsby-plugin-sass: ^2.0.13 => 2.1.0
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1
    gatsby-source-filesystem: ^2.1.1 => 2.1.1
    gatsby-source-graphql: ^2.0.19 => 2.1.0
    gatsby-transformer-sharp: ^2.1.21 => 2.2.0
  npmGlobalPackages:
    gatsby-cli: 2.7.7
    gatsby: 2.7.3

**Comment by wardpeet** [comment]
Hey @oste!

This doesn't seem like a gatsby core issue. Could you post a snippet of your component/page where you use `TextField`?

> Seeing error: React.Children.only expected to receive a single React element child.

Looks like you can't add `<TextField></TextField>`. You'll need to add 1 children inside of the component. Does the following snippet work for you?
```js
<TextField><Input value="hello" /></TextField>
```

Make sure to change your import into `import TextField, {Input} from '@material/react-text-field';`

Thanks for using gatsby!

**Comment by jonniebigodes** [comment]
@oste i've been fiddling with the package in question and here's a simple implementation on how to use the one that's giving you issues.
I've created a simple component called `contact.js` ,inside `src/components` with the following code:
```javascript
import React, { useState } from "react"
import TextField, { HelperText, Input } from "@material/react-text-field"
import { Cell, Grid, Row } from "@material/react-layout-grid"
import "@material/react-text-field/dist/text-field.css"
import "@material/react-layout-grid/dist/layout-grid.css"
const Contact = () => {
  const [username, setUserName] = useState("")
  const [password, setPassword] = useState("")

  const handleSubmit = event => {
    event.preventDefault()
  }
  return (
    <Grid>
      <Row>
        <Cell columns={12}>
          <h1>Contact Form</h1>
        </Cell>
      </Row>
      <Row>
        <Cell columns={12}>
          <form onSubmit={handleSubmit}>
            <TextField
              label="Username"
              helperText={<HelperText>Add username</HelperText>}
            >
              <Input
                value={username}
                onChange={e => setUserName(e.target.value)}
              />
            </TextField>
            <TextField label="Password" helperText={<HelperText>Add a password</HelperText>}>
                <Input value={password} onChange={e=>setPassword(e.target.value)}/>
            </TextField>
          </form>
        </Cell>
      </Row>
    </Grid>
  )
}
export default Contact

```
Added it in the `index.js` and issuing `gatsby develop` and opening up a new browser window to `http://localhost:8000` shows me the following:
![oste1](https://user-images.githubusercontent.com/22988955/60526035-6e18ac80-9ce7-11e9-9ef3-90769d2cae29.png)

Feel free to provide feedback so that the issue can be closed or continue to work on it till we find a solution.

**Comment by oste** [comment]
doh, yep looking at the docs closer it does seem like the `TextField` does need an `Input` child. I was thrown off a bit b/c I was using the `textarea` prop and didn't think that would have `<input>`

Thanks @wardpeet and @jonniebigodes for the effort looking at this one.
