### ISSUE TITLE
Getting trackbacks/pingbacks from wordpress

### ISSUE THREAD

**Issue by tmo207** [gatsbyjs/gatsby#15291]
## Summary

I'm migrating a wordpress blog to Gatsby with the help of `gatsby-source-wordpress`. Now I want to get the pingback comments over GraphQl, but the allWordpressWpComments query doesn't return them. I wasn't able to find the pingback comments while digging through the Wordpress REST API of my website as well, so no wonder they don't exist on the query. How am I able to get them though?

## Relevant information

I initialised the project via `gatsby-starter-wordpress`.

**Comment by wardpeet** [comment]
It seems like a wordpress rest api issue. Like you mentioned there is no support yet for this in the api. You could add your own solution with https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/.

As stated, this is slightly tangential to Gatsby, and it seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪
