### ISSUE TITLE
feat(gatsby/schema): Allow defining child relationships through metadata

### ISSUE THREAD

**Issue by freiksenet** [gatsbyjs/gatsby#15305]
## Summary

Schema customization allows defining all kind of types and fields, except for the fields created through child/parent relationships. Defining child convenience fields isn't a good thing to do on parent level, therefore it needs to be done from a child point of view and we currently don't have any backreference mechanism in place. This issue defines API that transformers can use to specify child/parent relationships on type level, rather than node level.

### Basic example

```
// Generic parent children relationship
type SomeParent implements Node @infer {
  id
}

type SomeChild implements Node @infer @childOf(types: ['SomeParent']) {
  id
}

// Mime type based relationships

// File has all mimeTypes
type File implements Node @infer @mimeTypes {
  id
}

type SomeMarkdownType implements Node @infer @mimeTypes(types: ['text/markdown']) {
  id
}

type MarkdownRemark implements Node @infer @childOf(mimeTypes: ['text/markdown']) {
  id
}

type ImageSharp implements Node @infer @childOf(mimeTypes: ['image/jpeg']) {
  id
}
```

### Detailed explanation

Add `mimeTypes` extensions to types, that define possible mime types for that type.

Add `childOf` extension, that allows specifying that a type can be a child of either some type or a type with a particular mimeType. This allows for extensible parent/child relationship that aren't bound to `File`. We special case `File` to have all mimeTypes.

When we create child convenient fields, we add them not only based on nodes, but also based on the above system. @infer/@dontInfer start affecting this, with @dontInfer only adding explicit children.

**Comment by pauleveritt** [comment]
Should this work with deletion of the parent?

I have a parent-child transformer working using:

```javascript
        createParentChildLink({
            parent: node,
            child: resourceNode
        });
```

When I comment out that line, and add `@childOf(types: ["Mdx"])` on my type, my queries fail to grab the parent (and don't delete the child.)
