### ISSUE TITLE
[Discussion] gatsby-source-contentful requires at least one instance for schema

### ISSUE THREAD

**Issue by marcuslindfeldt** [gatsbyjs/gatsby#15304]
[gatsby-source-contentful](https://www.npmjs.com/package/gatsby-source-contentful#notes-on-contentful-content-models) has a requirement that:

> fields that do not have at least one populated instance will not be created in the GraphQL schema.

This obviously makes it hard to create empty states where there are no published content models. For example a job listing with no current open positions or a blog with no published posts yet. Currently I get the following build errors:

```
Cannot query field "allContentfulBlogPost" on type "Query". Did you mean "allContentfulPerson", "allContentfulTag", "allContentfulContentType", "contentfulPerson", or "contentfulTag"?
```

How do you normally handle these situations?

Would it not be possible to download the structure of the content models from contentful api and create empty graphql models so the build does not break?

E.g. an empty query for all blog posts could look like.
```
{
  data: {
    allContentfulBlogPost {
      edges: []
    }
  }
}
```

**Comment by sidharthachatterjee** [comment]
Thank you for the detailed and well written issue, @marcuslindfeldt 🙌 

The schema customisation feature we added in Gatsby 2.2.0 makes it possible to solve this by the defining known schema shapes ahead of time (and not depending no inference and therefore content). 

We currently have a work in progress PR for a rewrite of `gatsby-source-contentful` with support for this in https://github.com/gatsbyjs/gatsby/pull/12816

> fields that do not have at least one populated instance will not be created in the GraphQL schema.

We will no longer have this limitation once https://github.com/gatsbyjs/gatsby/pull/12816 is merged and published 💪

**Comment by kiliw** [comment]
Please reopen this. Urgent topic and there is an endless discussion about minor things in the PR so will take a while to get merged. Please advise with a workaround for the time being.

**Comment by LukasMachetanz** [comment]
Any update or a possible workaround?

**Comment by Fewwy** [comment]
Got stuck in this issue for several days straight. The gatsby documentation doesn't provide the proper guide to solve this issue with a schema. This is my StackOverflow post covering the issue and code I had.
https://stackoverflow.com/questions/64455525/cannot-query-field-x-on-type-y/64456887?noredirect=1#comment114086798_64456887

**Comment by jung-youjin** [comment]
I managed to solve this a few months ago and this bug started showing up again for no reason when I didn't give any changes to my code :( This has to be fixed and I'm stuck as well.

**Comment by jromme** [comment]
I'm currently using a dummy-post with all the fields needed and hiding that particular post manually. That case there will always be an instance that has all the data needed to create the instance and not break the code. 

Not a pretty solution as it will show an awkward post of which the client needs to know that they cannot delete the post. Clunky, but it works.
