### ISSUE TITLE
[docs][recipes] Prepare for deployment

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#15319]
## Summary

To improve key learning workflows in the Recipes section of the docs, there should be a short, actionable recipe on preparing a site for deployment. This would include generating your site with `gatsby build` and adding an optional path prefix (with a quick note about why you would even need/want that option).

Recipes now follow this format:

- Requirements or prerequisites 
    - Gatsby CLI
    - A Gatsby site
- Step-by-step instructions
- Relevant links to any relevant information
    - More on [preparing a site for deployment](https://www.gatsbyjs.org/docs/preparing-for-deployment/)

This recipe should go into the "Deploying" section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md), replacing the existing text. Docs URLs to gatsbyjs.org should be relative. There is a recipe template in the contributing docs: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by tom-raley** [comment]
I’d like to take this on if no one else has started yet!

**Comment by marcysutton** [comment]
Go for it, @tom-raley! Thanks for offering!

**Comment by marcysutton** [comment]
Closed with #15605
