### ISSUE TITLE
[1.0] Automatically open browser when running gatsby develop (like create-react-app)

### ISSUE THREAD

**Issue by prayasht** [gatsbyjs/gatsby#1531]
Is it possible to implement this feature? I find it very handy when starting up the dev server.

Looking through create-react-app `scripts/start.js`, it seems that they use an external `openBrowser` package like so: 
```javascript
const openBrowser = require('react-dev-utils/openBrowser')

// then open the dev server url with the package
openBrowser(urls.localUrlForBrowser);
```

If it's a trivial change, I'd love to take a stab at it!

**Comment by oscar-b** [comment]
Try `gatsby develop --open`

```
  Usage: develop [options]

  Start development server. Watches files and rebuilds and hot reloads if something changes

  Options:

    -h, --help         output usage information
    -H, --host <url>   Set host. Defaults to localhost
    -p, --port <port>  Set port. Defaults to 8000
    -o, --open         Open the site in your browser for you.
```

**Comment by prayasht** [comment]
Ahh! Should've looked that up before posting this. Sorry about that and thanks for the quick response!

**Comment by KyleAMathews** [comment]
Opening the site by default is an interesting default. @prayasht do you really like this? We could change the default. I haven't used CRA much or other systems which open pages by default. Is there other tools that do this?

The only downside I see is it grabs the focus of your OS which can be annoying.

**Comment by oscar-b** [comment]
I don't like th default of CRA (you can change it with config though), it's quite annoying and you end up with a lot of tabs. As long as it's possible to configure, I think either default is fine.

**Comment by prayasht** [comment]
@oscar-b On my machine (macOS + Chrome), if an instance is already open in a tab, it simply refreshes it. I've never had it open new instances every time I run the dev server. 

Honestly, I like it and I just changed my npm script to `gatsby develop --open` so that's easy enough for me. Not sure about others though!

**Comment by KyleAMathews** [comment]
Let's leave this open for a while to see if anyone else has strong feelings about it

**Comment by VerteDinde** [comment]
Just chiming in as a create-react-app user to say that I really like the app to open as a default; `gatsby develop --open` works fine for me as well, though.

**Comment by nicholaswyoung** [comment]
`--open` should *not* be the default. 

I share the same dislike for Gatsby taking control of my OS windows, even just to launch a browser.  I changed the default behavior in CRA the moment I installed it.

This can be easily scripted. Most sites already wrap `gatsby build` as `npm run build` &mdash; my two cents? `--open` can be just as easily included there, in your `package.json`, on a project-by-project basis.

**Comment by rongierlach** [comment]
Going to chime in and say that `--open` should _not_ be a default.

**Comment by sebastienfi** [comment]
I too agree, `-o` shouldn't be default.

**Comment by KyleAMathews** [comment]
Leaving it not as the default :-)
