### ISSUE TITLE
Gatsby develop unable to create local host

### ISSUE THREAD

**Issue by arps18** [gatsbyjs/gatsby#15320]
## Description

`gatsby develop ` is showing error i.e error
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'

also `yarn install ` shows the error.

### Steps to reproduce

`yarn install`
`gatsby develop` 

### Expected result
It should be able to run `localhost`

### Actual result
`gatsby develop` **error**

success open and validate gatsby-configs - 0.008 s
error
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

⠋ load plugins

`yarn install` **error**

ERR! sharp Windows x86 (32-bit) node.exe is not supported
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies

C:\Users\arpan\Documents\MozGujarat\mozguj\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | win32 | ia32
gyp info spawn C:\Users\arpan\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\arpan\\Documents\\MozGujarat\\mozguj\\node_modules\\sharp\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\arpan\\.node-gyp\\10.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\arpan\\.node-gyp\\10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\arpan\\.node-gyp\\10.16.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\arpan\\Documents\\MozGujarat\\mozguj\\node_modules\\sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\arpan\\Documents\\MozGujarat\\mozguj\\node_modules\\sharp\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
c:\users\arpan\documents\mozgujarat\mozguj\node_modules\sharp\src\libvips\cplusplus\verror.cpp(33): fatal error C1083: Cannot open include file: 'vips/intl.h': No such file or directory [C:\Users\arpan\Documents\MozGujarat\mozguj\node_modules\sharp\build\libvips-cpp.vcxproj]
c:\users\arpan\documents\mozgujarat\mozguj\node_modules\sharp\src\libvips\cplusplus\vinterpolate.cpp(34): fatal error C1083: Cannot open include file: 'vips/intl.h': No such file or directory [C:\Users\arpan\Documents\MozGujarat\mozguj\node_modules\sharp\build\libvips-cpp.vcxproj]
c:\users\arpan\documents\mozgujarat\mozguj\node_modules\sharp\src\libvips\cplusplus\vimage.cpp(41): fatal error C1083: Cannot open include file: 'vips/intl.h': No such file or directory [C:\Users\arpan\Documents\MozGujarat\mozguj\node_modules\sharp\build\libvips-cpp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\arpan\Documents\MozGujarat\mozguj\node_modules\sharp

### Environment

 System:
    OS: Windows 10
    CPU: (4) ia32 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.2 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.9.6 => 2.9.6
    gatsby-image: ^2.1.4 => 2.1.4
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.3 => 2.1.3
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.1.6 => 2.1.6
    gatsby-source-filesystem: ^2.0.40 => 2.0.40
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21

**Comment by m-allanson** [comment]
Hey @arps18 - it looks like you have a 32 bit version of Windows installed. Unfortunately the `sharp` image processing library used by Gatsby only supports 64 bit versions of Windows.  

You might be able to manually install an older version of sharp's dependencies with these instructions: https://github.com/lovell/sharp/issues/379

Or possibly use yarn aliases to install an older version of sharp itself, e.g. `yarn add sharp@npm:sharp@0.11.4`

**Comment by arps18** [comment]
> Hey @arps18 - it looks like you have a 32 bit version of Windows installed. Unfortunately the `sharp` image processing library used by Gatsby only supports 64 bit versions of Windows.
> 
> You might be able to manually install an older version of sharp's dependencies with these instructions: [lovell/sharp#379](https://github.com/lovell/sharp/issues/379)
> 
> Or possibly use yarn aliases to install an older version of sharp itself, e.g. `yarn add sharp@npm:sharp@0.11.4`

Hey @m-allanson , it is to inform you that i have a 64 bit version o f Windows.So maybe another issue might be there!
![Capture](https://user-images.githubusercontent.com/47818179/60587414-fd8a9200-9db1-11e9-83d9-67af9523e30a.PNG)

**Comment by m-allanson** [comment]
Hmm how strange. Maybe the version of node you're using is 32 bit instead of 64? It looks like Node is installed in `C:\Program Files (x86)\` which I think is reserved for 32 bit applications? Does using a [64 bit version of Node JS](https://nodejs.org/en/download/) work?

**Comment by arps18** [comment]
> Hmm how strange. Maybe the version of node you're using is 32 bit instead of 64? It looks like Node is installed in `C:\Program Files (x86)\` which I think is reserved for 32 bit applications? Does using a [64 bit version of Node JS](https://nodejs.org/en/download/) work?

No i tried that too and now when i installed node again in `C:\Program Files \ ` it showes that node hasn't been detected. Enviornment variable is updated too!

**Comment by mehrad77** [comment]
What was the problem? Im getting the same in ubuntu

**Comment by mdhiabouthuri** [comment]
same on windows 64bit

**Comment by arps18** [comment]
> What was the problem? Im getting the same in ubuntu

What is System Type of Your machine 32 or 64 bits?

**Comment by arps18** [comment]
> same on windows 64bit

Try installing node in Program Files rather than Program files (x86) folder!

**Comment by mehrad77** [comment]
> > What was the problem? Im getting the same in ubuntu
> 
> What is System Type of Your machine 32 or 64 bits?

it was 64, It solved after reinstalling packages.
