### ISSUE TITLE
navigateTo() from gatsby-link doesn't apply pathPrefix

### ISSUE THREAD

**Issue by DaleWebb** [gatsbyjs/gatsby#1533]
When using programmatic routing via the `navigateTo` function from `gatsby-link` - the route doesn't contain the `pathPrefix` in a production build.

In my case, I have `cp-website` repo to deploy for `gh-pages` which will be hosted at dalewebb.github.io/cp-website, and so my `pathPrefix` is `cp-website`.

The `<Link>` component will navigate correctly however.

---

Using Gatsby 1.2.0, Gatsby-Link 1.0.9

**Comment by KyleAMathews** [comment]
Fixed in #1550

**Comment by KyleAMathews** [comment]
Thanks for reporting the bug!
