### ISSUE TITLE
[gatsby-source-wordpress] Differences in WPCOM API results in pagination errors

### ISSUE THREAD

**Issue by himynameistimli** [gatsbyjs/gatsby#15347]
## Description

WPCOM's REST API differs slightly from the typical WP REST API, so using the header to determine number of items and number of pages does not work properly.

For instance, if you have over 100 tags, the endpoint will not pull more than 100, and then posts that link to those tags will result in:

```
TypeError: Cannot read property 'id' of undefined
```

If you're in a bind, you can remove some tags, and the build will proceed normally.

I'm talking to a WP support admin to determine what the proper path forward is. I'll update this post as I learn more.

When I get a chance, I'll make a PR to fix this issue, but I wanted to put up this issue in case others are using Wordpress.com instead of the self-hosted version.

**Comment by freiksenet** [comment]
@himynameistimli Is it possible to page the endpoint to request rest of the tags? In that case it would be possible to update wordpress plugin to do that.

CC @jasonbahl

**Comment by freiksenet** [comment]
Thank you for your patch!
