### ISSUE TITLE
built gatsby completely different from development, especially styling. 

### ISSUE THREAD

**Issue by zfc9d3f** [gatsbyjs/gatsby#15356]
## Description

I'm using styled components and it seems what i built looking at `gatsby develop` happens to be immensely different to what is produced with `gatsby build`

[you can see my problem here](https://i.imgur.com/rXfJCwK.gif)

### Steps to reproduce

[here is my deployed project on netlify](https://ecstatic-einstein-2f00b4.netlify.com/)

[here is my project](https://github.com/zfc9d3f/minerva-health)

### Expected result

- fonts should be loaded (i'm using the Helmet component to add link href to the google fonts needed)
- svg should be responsive, but it's one width throughout
- background color when using `createGlobalStyle` should be applied, but is not.

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 11.15.0 - /usr/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.7.0 - /usr/bin/npm
  Languages:
    Python: 3.6.8 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.90
    Firefox: 67.0.4
  npmPackages:
    gatsby: ^2.10.4 => 2.10.4 
    gatsby-image: ^2.2.3 => 2.2.3 
    gatsby-plugin-manifest: ^2.2.0 => 2.2.0 
    gatsby-plugin-offline: ^2.2.0 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0 
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1 
    gatsby-plugin-styled-components: ^3.1.0 => 3.1.0 
    gatsby-source-filesystem: ^2.1.0 => 2.1.0 
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0 
  npmGlobalPackages:
    gatsby-cli: 2.6.5

**Comment by zfc9d3f** [comment]
SSL problems with netlify btw, open with chrome

**Comment by zfc9d3f** [comment]
it seems like the styling issues were coming from my end, although i'm still unsure how to load fonts in gatsby.
Using CRA has made it clear for me where the issue was, whereas gatsby production build is vastly different from development causing a lot of headaches. since this is just a toy project, i'll be reverting to CRA

**Comment by broskoski** [comment]
@zfc9d3f did you end up getting this fixed? experiencing the same issue.

**Comment by k8martian** [comment]
i have the same issue but all happen on images..... all my images become 20x20

**Comment by Jennykuma** [comment]
@zfc9d3f Hey did you find a solution for this? Same issue here.

**Comment by zfc9d3f** [comment]
@Jennykuma I think i ended up going to CRA for one of the projects because SEO wasn't really something necessary. For the other, i ended up styling just through css.
