### ISSUE TITLE
Can not make react component work correctly

### ISSUE THREAD

**Issue by afucher** [gatsbyjs/gatsby#1536]
I'm trying for the first time gatsby, I started the example site and try to add a menu component. But the component is not working, the build result not even have the component method that I've created.

Here is the repo: https://github.com/astroregulus/regulus-site

**Comment by besrabasant** [comment]
Add `MenuComponent` in `layouts/index.js` instead of `html.js`

**Comment by afucher** [comment]
@besrabasant it works!! But I didn't understand why :/ Can you explain for me?

**Comment by DaleWebb** [comment]
Gatsby renders content within the `#___gatsby` `<div>`, but you had it outside of that element.

**Comment by afucher** [comment]
Thks!!
