### ISSUE TITLE
Declare slash as a dependency of gatsby-plugin-offline

### ISSUE THREAD

**Issue by seangenabe** [gatsbyjs/gatsby#15372]
## Description

`slash` is being required by the `gatsby-node` script of `gatsby-plugin-offline`, however, it is not declared as a dependency in `package.json`.

### Steps to reproduce

* Use pnpm to install gatsby and gatsby-plugin-offline
* Include gatsby-plugin-offline as a plugin

### Expected result

No errors

### Actual result

`gatsby develop` fails to run with

`Error: Cannot find module 'slash'`

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by freiksenet** [comment]
Thank you!

Would you be interested in making a PR to fix that?

**Comment by abhijithvijayan** [comment]
I can take a peek at this

**Comment by freiksenet** [comment]
Cheers!
