### ISSUE TITLE
Pathprefix breaking sw.js include

### ISSUE THREAD

**Issue by gregsqueeb** [gatsbyjs/gatsby#1539]
When trying to use the pathprefix with the gatsby-starter-blog it is including the pathprefix on the sw.js include incorrectly: https://gregsqueeb.github.io/gregdmathews.com/ Instead of /gregdmathews.com/sw.js it is trying to include /gregdmathews.comsw.js which 404s.

Here is the repo that builds to that gh-pages as well. The only thing I have changed is adding the PathPrefix to the gatsbyconfig.
https://github.com/gregsqueeb/gregdmathews.com/tree/master

Going to look into how to fix this now with a PR, but if you know where the issue is off the top of your head let me know and it could speed up me hunting down the problem :)

**Comment by KyleAMathews** [comment]
Oy, thanks for the fix!

And hello fellow correctly spelled Mathews :-D

**Comment by gregsqueeb** [comment]
Haha :p Don't run into too many of us who correctly spell our last names!
