### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#154]
Tests are good.
### Modules to unit test
- [x] `glob-pages.js` (which should be split into two modules, one for globbing and one for processing the files).
- [ ] `create-routes.js`
- [ ] `gatsby-helpers.js`
### Integration tests
- [ ] Can build starters (check for bundle.js, styles.css, html files?)
- [ ] Running develop listens on port and correctly returns html/js

**Comment by KyleAMathews** [comment]
Let's use https://github.com/sindresorhus/ava

**Comment by benstepp** [comment]
Any preference on other testing utilities? I wrote a [single integration test](https://github.com/benstepp/gatsby/blob/bs-build/test/integration/build-starter-default.js) with no real assertions, and came to the realization that we're probably going to need more stuff to get some really good coverage.

* supertest? for http requests to development server
* jsdom? to ensure pages are rendered with bundle/styles/other selectors
* bluebird? promisify to reduce Promise boilerplate for async/await

I'm pretty new to JS testing land, so I'm not really sure what's the best/hottest to use.

**Comment by KyleAMathews** [comment]
No strong preferences. Those are very common utilities so are great choices.

**Comment by KyleAMathews** [comment]
Closing as old and not very useful anymore.
