### ISSUE TITLE
Urgent help, need to remove service worker ( special case)

### ISSUE THREAD

**Issue by duongthienlee** [gatsbyjs/gatsby#15402]
What I mean by special case  is that I need to remove the old service worker when I was using create-react-app.
I should have removed it when using cra before switching the whole website to use gatsby.
With gatsby I know I can remove service worker like this
     
     //'gatsby-plugin-offline',
    'gatsby-plugin-remove-serviceworker'

But on the user's browser, they visited my website a long time ago when my website was using CRA with service worker installed on their device. And then my stupidity, I didn't remove CRA's service worker before moving to gatsby.
So right now, my website is using gatsby which I have configured to remove service worker like the code above. But it doesn't remove CRA's service worker.
On gatsby-browser.js I tried this code, but it doesn't work. 

    export const onClientEntry = async () => {
        if ('serviceWorker' in navigator) {
    
            navigator.serviceWorker.getRegistrations().then(function(registrations) {
        
            for(let registration of registrations) {
                console.log('Service Worker registration removed: ');
                    registration.unregister()
        
            }}).catch(function(err) {
        
                console.log('Service Worker registration failed: ', err);
        
            });
        }
    } 

Related information :
My CRA's website used to hosted on AWS, and delivered by cloudfront.
Then my website using gatbsy is currently hosted on Netlify and DNS is managed by AWS.
I need to host the website on netlify since i'm using netlify cms.

**Comment by wardpeet** [comment]
That's how you should do it. Could you send your website URL?

**Comment by duongthienlee** [comment]
@wardpeet  sure, https://senzolive.com
You will obviously see the latest version.
But if users visited my website before I switched to use gatsby. They will see the CRA website which serve old content. Here my website used to use ButterCMS, but with Gatsby I use netlify-cms now.
<img width="1440" alt="Screenshot 2019-07-04 at 14 32 43" src="https://user-images.githubusercontent.com/26104402/60663714-a7c4f100-9e68-11e9-9491-745fe7536b51.png">

**Comment by duongthienlee** [comment]
I have found the solution for it.
The CRA's service worker won't be unregister because there is no service-worker.js file.
So by adding a service-worker.js file in static folder, and it will work.

    if ('serviceWorker' in navigator) {
        navigator.serviceWorker.ready.then(registration => {
          registration.unregister();
        });
      }

**Comment by vikas26294** [comment]
Above solution worked for me but I had to create `service-worker.js` in `public` folder.
