### ISSUE TITLE
[gatsby-plugin-feed] JSON Feed support

### ISSUE THREAD

**Issue by brandonweiss** [gatsbyjs/gatsby#15420]
## Summary

I’d like to add [JSON Feed](https://jsonfeed.org) support to `gatsby-plugin-feed`.

If it were a simple change I would have just opened a PR, but there are some potential changes to design, so I wanted to get feedback first.

### Basic example

My philosophy when adding new features is always to maintain simplicity and use convention over configuration. Ideally it would be possible to transparently add JSON Feed in a way that requires no configuration changes, and everyone would automatically get a JSON Feed in addition to their RSS feed for “free”. Although given the current configuration, that may or may not be possible.

Here are a few options:

#### Keep the config the same, infer the JSON feed path from `output`

When generating the feed, we could generate an additional feed in JSON, take the output path, lop off the extension, replace it with `.json` and write out the file.

This would require no changes to anyone’s configuration, which probably makes it the most simple. However, it’s pretty unintuitive and probably violates the principle of least surprise. If I saw one feed in the `feeds` array and it had an `output` property of `/feed.xml` I would _not_ expect there to also be a matching JSON feed generated.

#### Change the config, add a `json` boolean

This builds on the previous option. We could add a `json` boolean, either to the individual feed config or the root config of the whole plugin.

This is better in that it makes it clear that a JSON feed is being generated. But it’s worse in that it’s unclear that it’s additive. Someone might think this would output a JSON feed instead of an XML feed.

Also if we default it the JSON feed option to on so everyone that is generating XML feeds would also get JSON feeds automatically when they update, then we’re right back to the problem of people not expecting a JSON feed to be generated given the current configuration they have.

We could change the property to maybe take a string value of `"xml"`, `"json"`, or `"both"`, which makes what’s happening clearer. Although the `output` property would still have an XML extension in it, which is confusing.

#### Change the config, add another feed with JSON extension

The only thing that really indicates that a given feed is XML is the extension. So we could enable JSON feed support by having people add another feed in the array with an `output` property that has a `.json` extension.

The upside is this is nice and simple. The downside is it’s not particularly obvious. It relies heavily on documentation to explain how JSON feed support is possible. Also, duplicating the entire feed and all its options only to change one property feels kludgey.

#### Change the config, change the `output` property

Lastly, we could change the `output` property. The fact that it contains the extension is what’s causing a lot of the difficulty here.

If we get rid of the extension, assuming we want each feed to generate both an XML and JSON feed automatically, we’re left with configuring the path and the name of the feed.

We could call it `path` or `outputPath`, although nothing about that is clear that it should include the feed’s path and name but _not_ the extension.

Or we could call it `name`. That seems relatively clear that it shouldn’t have an extension, but it’s not clear that it could include the path.

We could also have an option for `path` and an option for `name`, which solves the previous two problems but could create other problems when joining the two options together.

I think in this scenario, no matter what we name it, it will require leaning on documentation a bit to show how to use it correctly.

The upside here is that it’s probably the clearest as to what is happening and the least kludgey. The downside is that it would be a breaking change. 

I suppose we could support both `output` for the old behavior and `path`/`name` for the new behavior and warn people when building, which would create a nice migration path.

### Motivation

In a relatively short amount of time [JSON Feed](https://jsonfeed.org) has become a very popular standard—most RSS readers seem to support it. Maybe JSON Feed will never entirely supplant RSS, but given it’s a small amount of effort I think it’s worth supporting both standards.

**Comment by brandonweiss** [comment]
It would be great to get some feedback on this!

**Comment by ryanfiller** [comment]
I came across this googling, I would love if this existed.
