### ISSUE TITLE
Blog Theme error message

### ISSUE THREAD

**Issue by eclectic-coding** [gatsbyjs/gatsby#15436]
## Description
Created a site with `gatsby-starter-blog-theme`, and there is a `unique key` error message in the Gatsby Develop terminal.

### Steps to reproduce
I created a test site for trying out Gatsby Themes with the following command:
`gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme`

Then started:
`gatsby develop`

_***I did not create a demo project for testing since it was a baseline site. I can if need be.***_

### Expected result

It is expected that the new site starts with no error messages. Even though this error message displays, the site loads normally. 

### Actual result
Error message:
```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
    in EmotionCssPropInternal
```
I did look through the site source and the NPM theme package but cannot seem to find the error. 

### Environment
```
gatsby info --clipboard

  System:
    OS: Linux 5.0 Pop!_OS 19.04
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.5.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
  npmPackages:
    gatsby: ^2.13.3 => 2.13.3
    gatsby-theme-blog: ^1.0.0 => 1.0.0
```

**Comment by sw-yx** [comment]
still a problem.

**Comment by eclectic-coding** [comment]
@sw-yx I agree. I haven't been able to find a list which is missing a `key prop` in the theme itself. 
However, this error is not present in the regular starters, which probably means, the error is generated somewhere in the theme infra-structure, but not necessarily the theme itself.

**Comment by johno** [comment]
Thanks for opening up this issue!

This was fixed in a couple different PRs in [Theme UI](https://github.com/system-ui/theme-ui). I'm going to close now as a fresh `gatsby new` or dependency update will no longer result in an error.

![image](https://user-images.githubusercontent.com/1424573/62500396-63987980-b7a3-11e9-98c2-45ac81e2d111.png)

**Comment by smerth** [comment]
I am running into what looks to be the same error.  I have updated all packages and I am running gatsby-plugin-theme-ui not gatsby-theme-ui

This is the error I am getting.

```bash
Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
    in InitializeColorMode
```

**Comment by smerth** [comment]
sorry missed part of the error:
```bash
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
    in InitializeColorMode
```

**Comment by sw-yx** [comment]
@smerth are you trying from `gatsby new`? maybe youre caching something you arent aware of

**Comment by smerth** [comment]
@sw-yx  I ran `gatsby clean` and deleted yarn lock file and re-installed packages and have the same error.  It doesn't break the build and as far as I can see the theme is working properly.  
The site I am working from is built from Lengsdorf's tutorial on Egghead.io.  He does starts the site build from scratch.
I will publish the theme and see how it works in a new site and let you know.

**Comment by sw-yx** [comment]
sorry man. i got nothing.
