### ISSUE TITLE
[docs] Queries example URL contains wrong line number

### ISSUE THREAD

**Issue by JayKid** [gatsbyjs/gatsby#15434]
## Description

The line number referenced in https://www.gatsbyjs.org/docs/query-behind-the-scenes/ as an example is wrong (pointing to an old revision of the file).

### Steps to reproduce

Navigate to https://www.gatsbyjs.org/docs/query-behind-the-scenes/ and click on the link.

### Expected result

The link should contain the appropriate line number to point new gatsby devs in the appropriate direction.

### Actual result

The link opens in Github but the focus is at the top of the file.

### Environment

-

**Comment by lannonbr** [comment]
Fixed in #15435. Closing
