### ISSUE TITLE
How to use jQuery?

### ISSUE THREAD

**Issue by afucher** [gatsbyjs/gatsby#1544]
I'm using the foundation framework, and it needs the global jQuery. I try to import jQuery, but I still getting the error 'jQuery is not defined'.  

So what is the correct way to use it?

**Comment by akadop** [comment]
you shouldn't be using jquery with react.

react is entirely virtual DOM, while jquery manipulates the real DOM.

**Comment by akadop** [comment]
if you want to use foundation in react, use this

https://github.com/digiaonline/react-foundation

**Comment by KyleAMathews** [comment]
Try this https://stackoverflow.com/questions/29080148/expose-jquery-to-real-window-object-with-webpack
