### ISSUE TITLE
Starter download analytics

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1546]
It'd be nice to be able to count when starters are installed. There's a few ways of doing that. I think sorting by install count would be a natural way to display starters on the website.

**Comment by hgmeza** [comment]
Hi, I would like to contribute on this one. Can you clarify for me "display starters on websites" ? You just want the count of how many starters have been installed, and that number to be displayed on the website?

**Comment by KyleAMathews** [comment]
This would be great to get going — we need first to get community buy-in however on tracking when a starter is installed.

What I think would make sense is we only track installs of known starters — e.g. starters listed on https://www.gatsbyjs.org/docs/gatsby-starters/

That way if someone installs a test starter or a private one, it's not recorded.

**Comment by hgmeza** [comment]
Excellent! So I found the code where the CLI here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/init-starter.js

I assume I would need to modify something here. Is there a gatsby server or some other common state where I could keep the number of installations it has been made?

**Comment by KyleAMathews** [comment]
@hgmeza that's another problem — we don't have a place yet for storing this data :-(

**Comment by hgmeza** [comment]
Dang! Alright, so one of the things we can do is to have a server that Gatsby can read. I've found two services that have free tiers:

-MondoDB Atlas 
-Amazon S3

The benefit of including either of them is that we wouldn't have to worry about the maintenance of the server. Also, the usage would be very light weight.

We could store objects that describe each starter including the github link and demo link and the count of installs then automatically generate the list based on that instead of hard coding on markdown

**Comment by KyleAMathews** [comment]
Yeah, perhaps an s3 bucket — store each install as a separate event (a JSON file w/ the metadata). Then can periodically loop over the files and create counts from that.

**Comment by lassiter** [comment]
Could you do an api request for google analytics based on event tracker clicks?

**Comment by hgmeza** [comment]
Hey, still working on this. One thing that I just realized is that after setting up the S3 (where I am almost done), how are we going to get the data if there is no s3 gatsby source plug-in?

**Comment by tanvibhakta** [comment]
Hi, I looked into what @lassiter said and it looks like you can get the number from [Google Analytic's Real Time Reporting API](https://developers.google.com/analytics/devguides/reporting/realtime/v3/devguide) but the API is in developer beta, and to request access in the form [here](https://docs.google.com/forms/d/e/1FAIpQLSc9OpoDGB3tBD7oy1OG9fyum8KBIxs-2ihPCsHp13WTnM-SSQ/viewform) you need to give them the GA project ID which only the people who host the site will have. 

Hope this helps!

**Comment by LuisPaGarcia** [comment]
Hi! Can i work in this issue?

**Comment by lassiter** [comment]
@hgmeza are you still working on this? If not, I'd be interested in taking a crack at it. What are we counting as a download now with the current layout of the site? On [gatsby-starter-blog](https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-blog/) there are really three main links: preview, deploy to netlify, and starter source code. Are all of those clicks considered a download? Or, is this feature not a priority anymore?

As @tanvibhakta discovered the Google Analytics Real-Time Reporting API was and still is in preview beta. So, I'm not sure that's an option yet. @KyleAMathews could we set up a simple lambda with Netlify and have a database somewhere? Or, are we going for something more static. One potentially bad option, which would be much more complicated is seeing if we could use Github webhooks to store the data in each starter or the gatsbyjs/gatsby repo.
