### ISSUE TITLE
[Themes] Build error when adding `gatsby-theme-blog` to existing site

### ISSUE THREAD

**Issue by Polcius** [gatsbyjs/gatsby#15462]
## Description

Adding `gatsby-theme-blog` to an existing site doesn't work.

### Steps to reproduce

1. Start a new Gatsby site
2. Add `gatsby-theme-blog` as a plugin
3. Fill with an example blog post following the template
4. Set `basePath` to `/blog` in `gatsby-config`.

### Expected result

The site builds and I should have a blog with one post in my `/blog` path.

### Actual result

I got an error:
```
There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html ReferenceError: Tag is not defined


> 1 | /** @jsx jsx */
    | ^
  2 | import { jsx, ThemeProvider, ColorMode } from 'theme-ui'
  3 | import React from 'react'
  4 | import theme from './index'


  WebpackError: ReferenceError: Tag is not defined

  - provider.js:1 Module../node_modules/gatsby-plugin-theme-ui/src/provider.js
    node_modules/gatsby-plugin-theme-ui/src/provider.js:1:1

  - gatsby-ssr.js:1 Module../node_modules/gatsby-plugin-theme-ui/gatsby-ssr.js
    node_modules/gatsby-plugin-theme-ui/gatsby-ssr.js:1:1
```

### Environment

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.13.1 => 2.13.4 
    gatsby-image: ^2.2.4 => 2.2.4 
    gatsby-plugin-manifest: ^2.2.1 => 2.2.1 
    gatsby-plugin-netlify: ^2.1.0 => 2.1.0 
    gatsby-plugin-offline: ^2.2.0 => 2.2.1 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-sharp: ^2.2.2 => 2.2.2 
    gatsby-plugin-styled-components: ^3.1.0 => 3.1.0 
    gatsby-source-filesystem: ^2.1.2 => 2.1.2 
    gatsby-theme-blog: ^1.0.0 => 1.0.0 
    gatsby-transformer-sharp: ^2.2.1 => 2.2.1

**Comment by amberleyromo** [comment]
Hi! Can you share the repo where the error is happening? I tried to reproduce this by creating a new site from the default Gatsby starter and adding the blog theme, but wasn't able to repro.

**Comment by Polcius** [comment]
I am trying to add it to this site => https://github.com/Polcius/portfolio

I am thinking it may have something to do with the fact I already have `styled-components` and a `<Theme />` component, but IMO it should work.

**Comment by stefthoen** [comment]
I just started a new project with the gatsby-default-starter and have added `gatsby-plugin-styled-components` to `gatsby-config.js` and I get the same error. Commenting out that line makes the build succesfully compile.

**Comment by 454de6e** [comment]
I can confirm the observation made by @stefthoen .

**Comment by datakurre** [comment]
Unfortunately, "dropping" gatsby-plugin-styled-components from gatsby-config also removes ssr-rendering of styled components.

As a fix, I followed https://emotion.sh/docs/styled, removed both styled-components and gatsby-plugin-styled-components, added emotion/styled, theme-ui, gatsby-plugin-theme-ui and added gatsby-plugin-theme-ui into gatsby-config. This restored ssr for my styled components with gatsby-theme-blog.

**Comment by AlmogRnD** [comment]
Has then been fixed I'm getting the same error/issue and can't add gatsby-theme-blog to my site

**Comment by di-sukharev** [comment]
gatsby-plugin-styled-components breaks the SSR, fix please =-)
<img width="1484" alt="Screenshot 2021-03-03 at 09 48 54" src="https://user-images.githubusercontent.com/57486732/109765272-ab90b400-7c05-11eb-8fef-1dd21652b5da.png">
