### ISSUE TITLE
CLI output clipping pushed into new line

### ISSUE THREAD

**Issue by herecydev** [gatsbyjs/gatsby#15466]
## Description

Running `gatsby develop` outputs the total pages created as the final output, this text is supposed to span the entire width of the command line however it is pushing onto another line

![image](https://user-images.githubusercontent.com/11328618/60755580-a40ca800-9fe9-11e9-8cad-4bb48c6f6f04.png)

### Steps to reproduce
With dependencies:

 "dependencies": {
    "gatsby": "^2.13.4"
  },

Run `gatsby develop` in a command prompt on command prompt or powershell

### Environment

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: 44.18362.1.0
  npmPackages:
    gatsby: ^2.13.4 => 2.13.4

**Comment by herecydev** [comment]
For what it's worth, it's fine on mac pro.

 System:
    OS: macOS 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.1
  npmPackages:
    gatsby: ^2.13.10 => 2.13.10 
  npmGlobalPackages:
    gatsby-cli: 2.5.4

**Comment by herecydev** [comment]
Any pointers on this? I'm more than happy to try and get a fix together.

**Comment by wardpeet** [comment]
Thanks for creating this issue. It's an issue only affecting windows. I believe it's not a gatsby issue but an issue with [ink](https://github.com/vadimdemedes/ink). Ink is the terminal renderer we use to output messages to the screen.

I've created an issue upstream https://github.com/vadimdemedes/ink/issues/218

**Comment by herecydev** [comment]
not stale

**Comment by herecydev** [comment]
This is fixed upstream, running `yarn ugrade` for yarn or `npm update` for npm should resolve this.
