### ISSUE TITLE
Conflicting version requirements for babel-preset-gatsby-package in CI

### ISSUE THREAD

**Issue by superhawk610** [gatsbyjs/gatsby#15475]
## Description

While developing a new plugin (#14608), I get the following error messages:

`unit_tests_windows` [Azure DevOps](https://dev.azure.com/gatsbyjs/gatsby/_build/results?buildId=17391) 

```
gatsby-plugin-preload-fonts: 
  Depends on "babel-preset-gatsby-package@^0.1.4" 
  instead of "babel-preset-gatsby-package@0.2.0". 
```

`ci/circleci: bootstrap` [CircleCI](https://circleci.com/gh/gatsbyjs/gatsby/164646?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

```
gatsby-plugin-preload-fonts: 
  Depends on "babel-preset-gatsby-package@0.2.0" 
  instead of "babel-preset-gatsby-package@0.1.4". 
```

### Steps to reproduce

View failing CI error logs for the following commits on #14608:

- `store cache file in project root`
- `bump babel-preset-gatsby-package version`

### Expected result

Either `babel-preset-gatsby-package@0.1.4` or `babel-preset-gatsby-package@0.2.0` should be standard across all CI.

### Actual result

They are not.

### Environment

n/a

**Comment by wardpeet** [comment]
Oh I fixed this in your PR :) Seems like I missed this.
