### ISSUE TITLE
Issue with setting up Gatsby, VS code, and ubuntu 

### ISSUE THREAD

**Issue by Will-McKnight-604** [gatsbyjs/gatsby#15473]
## Summary

Hello Everyone,

I followed the setup recommended by the tutorials on gatsbyjs website, and I downloaded Ubunto as my Linux subsystem and VS code for the editor. My problem is that VS code cannot access my Gatsby server directory when I use Ubuntu to create a website from a "Starter".

I found out that through the Ubuntu cmd line you can access the Windows C and D drive, but coming from the Windows side you cannot access the Ubuntu directories.

I followed the instructions on the gatsby website, so I am not sure where I went wrong? Or am I just not using these two apps as you're supposed to?

Please let me know if more information is needed.

Cheers,
Will

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by lannonbr** [comment]
So this is not particularly a Gatsby issue, but Microsoft has a VS Code extension to use VS Code inside WSL: https://code.visualstudio.com/docs/remote/wsl

**Comment by Will-McKnight-604** [comment]
Thanks Iannobr for the hyperlink, but you could argue it is a Gatsby issue.

I find it strange that within the tutorial they don't mention this, as they just go from installing VS code to showing how VS code has direct access to the gatsby server directories.

Anywho, thank you for responding!

**Comment by lannonbr** [comment]
Alright, we can look into updating the docs to include this
