### ISSUE TITLE
[Bug] "originalImg" doesn't return original image

### ISSUE THREAD

**Issue by baobabKoodaa** [gatsbyjs/gatsby#15474]
## Description

It seems like there is currently no GraphQL query available which could be used to fetch an image file without compressing it.

### Steps to reproduce

Use a GraphQL query like this:

```
{
            localImages: allFile(
                filter: {
                    extension: {regex: "/(jpeg|jpg|png)/"},
                    sourceInstanceName: {eq: "images"}
                }
            ) {
                edges {
                    node {
                        childImageSharp {
                            fluid {
                                originalImg
                            }
                        }
                    }
                }
            }
        }
```

### Expected result

When I query for "originalImg", I'm expecting to get the original image file.

### Actual result

Gatsby compresses the image for me using some kind of default compression settings. Quality of the image is reduced.

### Workaround

I did some experiments with `fluid(quality: 90)`. If the quality of the raw image files is uniform, then this can be used as a workaround to get the images to roughly the desired quality level. However, even this command doesn't seem to work as expected. For example, when I used "quality: 100", Gatsby would take my 1MB image file and make it a 2MB image file.

**Comment by LekoArts** [comment]
You can grab the original image like this:

```graphql
query MyQuery {
  allFile {
    nodes {
      publicURL
      childImageSharp {
        original {
          src
        }
      }
    }
  }
}
```

[Codesanbox example](https://mzeo7.sse.codesandbox.io/___graphql?query=query%20MyQuery%20%7B%0A%20%20allFile%20%7B%0A%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20publicURL%0A%20%20%20%20%20%20childImageSharp%20%7B%0A%20%20%20%20%20%20%20%20original%20%7B%0A%20%20%20%20%20%20%20%20%20%20src%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)
