### ISSUE TITLE
Netlify - Update gatsby monorepo continually failing

### ISSUE THREAD

**Issue by spences10** [gatsbyjs/gatsby#15481]
## Description

Netlify - Update gatsby monorepo continually failing:

```bash
[BABEL] Note: The code generator has deoptimised the styling of
```

:point_up: Message is truncated so don't know what the rest of the message is...

![image](https://user-images.githubusercontent.com/234708/60765523-7a0fc000-a093-11e9-86df-312c5a0c5d1a.png)

### Steps to reproduce

I use renovate, after trying to get the builds working a close the PR, then another PR is made by the bot when the monorepo updates.

### Expected result

Successful build

### Actual result

Failed builds:

https://app.netlify.com/sites/scottspence/deploys/5d20b394e530540008cca831

https://app.netlify.com/sites/font-sample-component/deploys/5d212d6ce05e910008829d06

https://app.netlify.com/sites/scott-gatsby-netlify-cms/deploys/5d20b363267365000d2db204

### Environment

<details><summary>scottspence.me</summary>

```bash
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.10.0 - /tmp/yarn--1562485191592-0.8964086359504344/node
    Yarn: 1.16.0 - /tmp/yarn--1562485191592-0.8964086359504344/yarn
    npm: 6.4.1 - ~/n/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 67.0.4
  npmPackages:
    gatsby: 2.12.0 => 2.11.3 
    gatsby-plugin-catch-links: ^2.0.9 => 2.1.0 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-google-analytics: 2.1.1 => 2.1.1 
    gatsby-plugin-manifest: 2.2.0 => 2.2.0 
    gatsby-plugin-netlify: ^2.0.6 => 2.1.0 
    gatsby-plugin-netlify-cms: 4.1.1 => 4.1.0 
    gatsby-plugin-offline: 2.2.0 => 2.2.0 
    gatsby-plugin-react-helmet: 3.1.0 => 3.1.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-robots-txt: 1.3.0 => 1.3.0 
    gatsby-plugin-sharp: 2.2.1 => 2.2.1 
    gatsby-plugin-sitemap: 2.2.1 => 2.2.0 
    gatsby-plugin-styled-components: 3.1.0 => 3.1.0 
    gatsby-remark-autolink-headers: 2.1.0 => 2.1.0 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-smartypants: ^2.0.9 => 2.1.0 
    gatsby-source-filesystem: 2.1.1 => 2.1.1 
    gatsby-source-graphql: 2.1.0 => 2.1.0 
    gatsby-transformer-remark: 2.5.0 => 2.5.0 
    gatsby-transformer-sharp: 2.2.0 => 2.2.0 
```

</details>

<details><summary>font-sample-component</summary>

```bash
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.10.0 - /tmp/yarn--1562485566589-0.4356436197932765/node
    Yarn: 1.16.0 - /tmp/yarn--1562485566589-0.4356436197932765/yarn
    npm: 6.4.1 - ~/n/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 67.0.4
  npmPackages:
    gatsby: 2.11.7 => 2.11.7 
    gatsby-image: 2.2.3 => 2.2.3 
    gatsby-mdx: 0.6.3 => 0.6.3 
    gatsby-node-helpers: 0.3.0 => 0.3.0 
    gatsby-plugin-manifest: 2.2.0 => 2.2.0 
    gatsby-plugin-offline: 2.2.0 => 2.2.0 
    gatsby-plugin-react-helmet: 3.1.0 => 3.1.0 
    gatsby-plugin-sharp: 2.2.1 => 2.2.1 
    gatsby-plugin-styled-components: 3.1.0 => 3.1.0 
    gatsby-source-filesystem: 2.1.1 => 2.1.1 
    gatsby-transformer-sharp: 2.2.0 => 2.2.0 
```

</details>

<details><summary>gatsby-netlify-cms</summary>

```bash
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.10.0 - /tmp/yarn--1562485590690-0.6250043845771542/node
    Yarn: 1.16.0 - /tmp/yarn--1562485590690-0.6250043845771542/yarn
    npm: 6.4.1 - ~/n/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 67.0.4
  npmPackages:
    gatsby: 2.11.6 => 2.11.3 
    gatsby-plugin-netlify-cms: 4.1.0 => 4.1.0 
    gatsby-plugin-react-helmet: 3.1.0 => 3.1.0 
    gatsby-source-filesystem: 2.1.2 => 2.1.1 
    gatsby-transformer-remark: 2.5.0 => 2.5.0 
```

</details>

**Comment by wardpeet** [comment]
Do you still have this issue with latest gatsby and latest netlify-cms-plugin?

**Comment by spences10** [comment]
I'm still having similar issues @wardpeet yes 

![image](https://user-images.githubusercontent.com/234708/61168333-a8cee000-a544-11e9-9bfb-bcc4eab1db9e.png)

For the MDX monorepo I need to switch to `gatsby-plugin-mdx` from `gatsby-mdx` so will see if that fixes the MDX ones, but as you can see there's still failing gatsby monorepo's too

**Comment by spences10** [comment]
So this still persists @wardpeet should I try updating packages one by one to find the one which breaks the build?

Logs for this: https://app.netlify.com/sites/font-sample-component/deploys/5d2cb7b308d3d40007f5d849

![image](https://user-images.githubusercontent.com/234708/61241889-607a1280-a73c-11e9-871c-cc7a59f8fcaf.png)

**Comment by spences10** [comment]
So, for the [font sample component] It's either Gatsby@2.11+ or the gatsby source filesystem but seeing as for [scottspence.me] I reverted to an earlier version of Gatsby@2.12.0 I think it may be the gatsby versions.

[font sample component]: https://github.com/spences10/font-sample-component
[scottspence.me]: https://github.com/spences10/scottspence.me

**Comment by spences10** [comment]
Should I close this @wardpeet? It seems to be varying on the three differing repos and means the issue is fragmented/not specific enough.

So, although I have given you as much information as I could I sense this isn't very high up on the priority list right now as it only seems to be me that is experiencing the issue.

I can just keep the Gatsby version pinned on the repos where this is happening so that the Netlify CI/CD isn't continually breaking. Thanks.

**Comment by wardpeet** [comment]
It seems like some npm modules can cause this when they don't have proper polyfilling. You can install regenerator-runtime and just add import "regenerator-runtime/runtime"; to your page which should fix it.

**Comment by spences10** [comment]
> You can install regenerator-runtime and just add import "regenerator-runtime/runtime"; to your page which should fix it.

Yeap! That did it for the `font-sample-component` repo thanks @wardpeet :pray: 

For `scottspence.me` I didn't have `gatsby-transformer-sharp` or `gatsby-plugin-sharp` in my `transformer-remark` plugins :man_facepalming: see comment here: https://github.com/gatsbyjs/gatsby/issues/15625#issuecomment-511978323
