### ISSUE TITLE
Gatsby Auth example not found the /app/login and /app/profile pages

### ISSUE THREAD

**Issue by ipatate** [gatsbyjs/gatsby#15484]
I tried this example : https://www.gatsbyjs.org/tutorial/authentication-tutorial/ and i have tried the example in repo github and for the both, @reach/router not found the page login and profile.
The route /app/login got to app page but the router not display the component login.

I have searched but i haven't found. Have you idea of the bug ?

![Capture d’écran 2019-07-07 à 17 03 09](https://user-images.githubusercontent.com/46760/60770237-258f3380-a0d9-11e9-961f-12a4d97a3451.png)

**Comment by chrismullins** [comment]
I am also seeing this, haven't had much time to investigate but here are other links calling attention to this issue [1] [2] if I'm not mistaken. No workarounds posted at this time that I've found.

[1] https://spectrum.chat/gatsby-js/general/gatsby-reach-router-url-params-ex-path-id~6a181e7c-68c9-4ee9-91c7-bc4b0a828ddf

[2] https://spectrum.chat/gatsby-js/general/nested-router-inside-of-gatsby~79743a61-00cb-460b-b267-eb675388d586

**Comment by chrismullins** [comment]
Also related to #15401 maybe, which has some workarounds listed.

**Comment by ipatate** [comment]
now, the path is without "/app/"

```jsx
<Layout>
      <Router>
        <PrivateRoute path="/profile" component={Profile} />
        <Login path="/login" />
      </Router>
    </Layout>
```

**Comment by ipatate** [comment]
Correction on documentation #15532
