### ISSUE TITLE
Navigating back should remember scroll position

### ISSUE THREAD

**Issue by KidkArolis** [gatsbyjs/gatsby#15499]
1. Scroll down a Gatsby page.
2. Click a link.
3. Hit browser's back button.

Expected: you're in the same scroll position as it was before you've clicked the link.
Actual: you're back at the top of the page.

**Comment by cdaein** [comment]
In my case, it does remember scroll position when I click browser back button. (I am using Gatsby's `<Link>` API)

On a related note, I wonder how i can simulate the same behavior with a button I create.
