### ISSUE TITLE
Different queries on the same page template

### ISSUE THREAD

**Issue by rgllm** [gatsbyjs/gatsby#15497]
## Summary

Hello.

I'm using `gatsby-source-wordpress` and ACF. In my WordPress installation, I have multiple page templates and each different page templates has different ACF fields.

How can I have different graphql queries for different WordPress page templates? Map each page on Gatsby for different Gatsby templates?

**Comment by lannonbr** [comment]
Sorry for the delay @rgllm but yeah I would say creating a gatsby template for each of the WP page templates would be a reasonable solution
