### ISSUE TITLE
[gatsby] CJK characters in pathname stop working since 2.13.2

### ISSUE THREAD

**Issue by d4rekanguok** [gatsbyjs/gatsby#15500]
## Description

Hi folks, since `gatsby@2.13.2`, paths with CJK (Chinese, Japanese, Korean) characters no longer works( i.e`/안녕/`). 

On Firefox, Gatsby renders an absolutely empty page, with no error displayed.
On Chrome, the correct page flashes up, but then becomes empty like in firefox.
This previously works with `gatsby@2.13.1`.

This happens on both `gatsby develop` & `gatsby build`. I've included a reproduction repo below.

### Steps to reproduce

Use CJK characters in a pathname. For a quick reproduction, clone gatsby blog starter & rename one of the markdown folder to include CJK characters. 

### Expected result

- [Working repo](https://github.com/d4rekanguok/gatsby-pathname-bug-repro/tree/bug/path-working)

- [Working path (deployed to netlify)](https://5d22b36339d71a0009ab8f77--nifty-thompson-08ab7e.netlify.com/%EC%95%88%EB%85%95/)

### Actual result

- [Repro repo](https://github.com/d4rekanguok/gatsby-pathname-bug-repro/tree/bug/path-not-working)

- [Not working path (deployed to netlify)](https://nifty-thompson-08ab7e.netlify.com/%EC%95%88%EB%85%95/)

**Comment by d4rekanguok** [comment]
After trying out a bunch of different Gatsby version, it looks like #13197 might contains the cause.

cc @pieh

**Comment by pieh** [comment]
Thanks for reproduction. Taking a look

**Comment by pieh** [comment]
Ok, this is related to https://github.com/reach/router/issues/206

Seems like workaround proposed in https://github.com/reach/router/issues/206#issuecomment-441284842 fix the issue - so I will add that to gatsby router

**Comment by pieh** [comment]
Opened pull request with fix - https://github.com/gatsbyjs/gatsby/pull/15552

**Comment by pieh** [comment]
Published `gatsby@2.13.11` - it fixed issue in reproduction in my tests, but please let us know if that's not actually the case.

**Comment by d4rekanguok** [comment]
Thanks @pieh for the quick fix, it now works on all of my paths!
