### ISSUE TITLE
Image issues in blog

### ISSUE THREAD

**Issue by FrugalTest** [gatsbyjs/gatsby#15506]
## Description

I am unable to load images inside a blog

### Steps to reproduce
I am providing a link - https://quirky-babbage-cc3053.netlify.com/blog/2019/06/10/how-to-install-jenkins-guide

Where you can see i am not able to render the images. If i inspect the images the dynamic link has not been generated.

when i run gatsby develop and check in localhost the images are appearing fine but when i push to github the images are not rendering

### Expected result

Images should appear

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.10.5 => 2.10.5
    gatsby-image: ^2.0.34 => 2.0.34
    gatsby-plugin-manifest: ^2.0.24 => 2.0.24
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.10 => 3.0.10
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7
    gatsby-remark-copy-linked-files: ^2.1.0 => 2.1.0
    gatsby-remark-images: ^3.0.10 => 3.0.11
    gatsby-source-filesystem: ^2.0.32 => 2.0.32
    gatsby-transformer-remark: ^2.3.8 => 2.3.12
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0

**Comment by MorphyMeri** [comment]
also in the same given link when i go into a blog of any page and click back it goes directly to the first page of the blog. For example if I click a blog in page 5 and click back button it goes to blog page 1. But these issue doesnt occur in local host

**Comment by FrugalTest** [comment]
also in the same given link when i go into a blog of any page and click back it goes directly to the first page of the blog. For example if I click a blog in page 5 and click back button it goes to blog page 1. But these issue doesnt occur in local host

**Comment by josefaidt** [comment]
In your `gatsby-config.js` file, have you added the `gatsby-remark-images` plugin as a plugin to the remark plugin like:

```js
// In your gatsby-config.js
plugins: [
  `gatsby-plugin-sharp`,
  {
    resolve: `gatsby-transformer-remark`,
    options: {
      plugins: [
        {
          resolve: `gatsby-remark-images`,
          options: {
            // It's important to specify the maxWidth (in pixels) of
            // the content container as this plugin uses this as the
            // base for generating different widths of each image.
            maxWidth: 590,
          },
        },
      ],
    },
  },
]
```

https://www.gatsbyjs.org/packages/gatsby-remark-images/

**Comment by FrugalTest** [comment]
I have used this but no luck. I have change the code from html format to md format. Now most of the images are loading other than two images. Can you recheck? 
Link - https://quirky-babbage-cc3053.netlify.com/blog/2019/06/10/how-to-install-jenkins-guide

**Comment by wardpeet** [comment]
Are you 100% sure the images are availalbe? Perhaps we don't process `PNG` extensions but only `.png`

**Comment by FrugalTest** [comment]
yes the images are available! and the images below are with PNG extension they are loading fine only two images are giving me issues. Cant share the repo as it is private. Anyways i will try changing the format and try

**Comment by lannonbr** [comment]
Would it be possible for you to instead of sharing this codebase make a reproduction so we can clone down and be able to reproduce your bug? https://gatsby.dev/reproduction

**Comment by FrugalTest** [comment]
There were some runtime errors after fixing those the images are working fine. closing the issue
