### ISSUE TITLE
gatsby-theme-blog generate invalid URL for post slug

### ISSUE THREAD

**Issue by malcolm-kee** [gatsbyjs/gatsby#15507]
## Description

The slug for post in `gatsby-theme-blog` are invalid URL when using windows.

This is due to the code that use `path.join` to create slug at https://github.com/gatsbyjs/gatsby/blob/master/themes/gatsby-theme-blog/gatsby-node.js#L171, which is fine in unix but problematic in windows because `path.join` returns backslash in windows.

### Steps to reproduce

In windows machine, run:

```bash
gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme
```

Then 

```bash
npm start
```

Then you should be able to see the links on the home page is incorrect.

### Expected result

The slug for post should be valid URL.

### Actual result

![image](https://user-images.githubusercontent.com/24528512/60789379-8ed27d80-a191-11e9-8fb9-caaf19e4c95e.png)

![image](https://user-images.githubusercontent.com/24528512/60789443-b75a7780-a191-11e9-8103-2186e2c4609c.png)

### Environment

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.13.6 => 2.13.6 
    gatsby-theme-blog: ^1.0.0 => 1.0.0

**Comment by malcolm-kee** [comment]
I can work on the fix once someone can confirm this is valid bug (not due to my misunderstanding 😅)

**Comment by LekoArts** [comment]
Ward is working on a fix 👍🏻
https://github.com/gatsbyjs/gatsby/pull/15370

**Comment by LekoArts** [comment]
Should be fixed now with https://github.com/gatsbyjs/gatsby/pull/15370

**Comment by bravo-kernel** [comment]
I just created a fresh gatsby-starter-blog-theme on Windows but am having the same problem. Should I do something to pull in the changes?
