### ISSUE TITLE
Hot module replacing is not not working

### ISSUE THREAD

**Issue by sidletsky** [gatsbyjs/gatsby#15516]
## Description

After upgrading from 2.13.1 gatsby doesn't send any file

### Steps to reproduce

Have in `package.json` dependency `gatsby": "2.13.2"`, make `yarn install`, then `yarn start`

### Expected result

Pages like usual

### Actual result

Blank page. In console error `The connection to http://0.0.0.0:8000/__webpack_hmr was interrupted while the page was loading.`

### Environment

`
  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    gatsby: 2.13.2 => 2.13.2
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
    gatsby-plugin-google-tagmanager: ^2.1.1 => 2.1.1
    gatsby-plugin-manifest: ^2.2.1 => 2.2.1
    gatsby-plugin-no-sourcemaps: ^2.1.0 => 2.1.0
    gatsby-plugin-offline: ^2.2.0 => 2.2.1
    gatsby-plugin-prefetch-google-fonts: ^1.4.2 => 1.4.2
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1
    gatsby-plugin-remove-trailing-slashes: ^2.1.0 => 2.1.0
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1
    gatsby-plugin-styled-components: ^3.1.0 => 3.1.0
    gatsby-plugin-typescript: ^2.1.0 => 2.1.0

`

**Comment by rroslaniec** [comment]
Blank page is here because of https://github.com/gatsbyjs/gatsby/issues/15429, but still there is hmr error.
