### ISSUE TITLE
Unhandled rejection eacces: permission denied, scandir '/' on server

### ISSUE THREAD

**Issue by bobobob22** [gatsbyjs/gatsby#15512]
## Description 

Hi, i met a problem when I tried to build gatsby project on server.
It returns an error "Unhandled rejection eacces: permission denied, scandir '/' "
I have an access to read root directory disabled on the server.

The problem occurs from 2.1.18 version.
Pull request: https://github.com/gatsbyjs/gatsby/pull/12005

It tries to find a correct path here:
https://github.com/Profiscience/true-case-path/blob/a1623002cf442ba7b8bb91c6a981cc46c887b85b/index.js#L29

### Steps to reproduce

Just try to install the newest version of gatsby and run build without root permissions.

### Expected result

Enable to build project.

### Actual result

It is impossible to build project without root permissions.

### Environment

Run gatsby-build

"dependencies": {
    "gatsby": "2.1.18",
}

**Comment by bobobob22** [comment]
> ## Description
> Hi, i met a problem when I tried to build gatsby on server.
> It returns an error "Unhandled rejection eacces: permission denied, scandir '/' "
> It is obvious that root shouldn't be permitted.
> 
> The problem occurs from 2.1.18 version (#12005 - normalize component path casing).
> 
> It tries to find a correct path here:
> https://github.com/Profiscience/true-case-path/blob/a1623002cf442ba7b8bb91c6a981cc46c887b85b/index.js#L29
> 
> ### Steps to reproduce
> Just try to install the newest version of gatsby and run build without root permissions.
> 
> ### Expected result
> Enable to build project.
> 
> ### Actual result
> It is impossible to build project without root permissions.
> 
> ### Environment
> Run gatsby-build

**Comment by lannonbr** [comment]
Hey @bobobob22 So I think this is extremely related to #14962 so I am going to close this issue. There's a PR up that issue.
