### ISSUE TITLE
Query data in gatsby-ssr.js

### ISSUE THREAD

**Issue by klase** [gatsbyjs/gatsby#15519]
Is it possible to use something like static query inside any of the Server Rendering API functions in gatsby-ssr.js?

**Comment by jonniebigodes** [comment]
@klase  `StaticQuery` and the hook counterpart `useStaticQuery` are considered part of the page and with that each graphql query used will be evaluated and run on a specific step during the build pipeline. Using a `StaticQuery` with a graphql query like the following one in `gatsby-browser.js` or `gatsby-ssr`:

```javascript
const React = require("react")

const { StaticQuery, graphql } = require("gatsby")
//const Layout = require("./src/components/layout").default
exports.wrapPageElement = ({ element, props }) => {
  // props provide same data to Layout as Page element will get
  // including location, data, etc - you don't need to pass it

  return (
    <StaticQuery
    query={graphql`
      query HeadingQuery {
        site {
          siteMetadata {
            title
          }
        }
      }
    `}
    render={data => (
      <div>
        <h1>{data.site.siteMetadata.title}</h1>
        {element}
      </div>
    )}/>
  )
  
}
```

Will yeld the following when you issue `gatsby develop`:

![ssr1](https://user-images.githubusercontent.com/22988955/60925361-5b7c1580-a29b-11e9-81c9-ac5b7ef0d828.png)

Feel free to provide feedback.

**Comment by tqureshi-uog** [comment]
As I described in https://github.com/gatsbyjs/gatsby/discussions/27838 I'm having this exact same problem. So is this a bug, or a built-in limitation of gatsby-ssr in that it (or any component it calls) is completely incapable of pulling any data via staticquery?

**Comment by crazydev901** [comment]
@gatsbybot  "not stale" Same problem here. 
Error message:
`Generating SSR bundle failed

Can't resolve 'public/page-data/sq/d/2150987292.json' in '/home/david/0Project/ask-p2/gatsby-emulsify'

If you're trying to use a package make sure that 'public/page-data/sq/d/2150987292.json' is installed. If you're trying to use a local file make sure that the path is correct.
`
@tqureshi-uog @klase @jonniebigodes  Could you help me to fix this issue?
