### ISSUE TITLE
Can't verify email for gatsby-plugin-netlify-cms/netlify-cms-app and so can't login to netlify cms

### ISSUE THREAD

**Issue by interglobalmedia** [gatsbyjs/gatsby#15528]
## Description 
When I sign up myself to netlify-cms and subsequently try to login, I am given the message that my email has not been verified. And when I click on the link in the email to accept the invitation, I am simply directed to my site's home page. I think that is why my email is not verified. I am at level 0 as I should be since I am the site administrator.

Describe the issue that you're seeing. This is the link I am taken to when clicking on the accept invite in the email I am sent to accept my invite from Netlify Identity to use Netlify CMS on my site: https://www.interglobalmedianetwork.com/#invite_token=whateverthetokenis
As you can see, admin does not exist in this link. Big problem.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result That my email invite would be verified.

What should happen? That I should be able to login to netlify-cms via my gatsby site.

### Actual result My email is not verified. I am taken to the home page of my site. That is because in the default email template for level 0, the link does NOT include /admin.

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

 ```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
    npm: 6.7.0 - ~/.nvm/versions/node/v11.14.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.100
  npmPackages:
    gatsby: ^2.10.0 => 2.10.0
    gatsby-image: ^2.1.4 => 2.2.3
    gatsby-plugin-feed: ^2.3.1 => 2.3.1
    gatsby-plugin-google-analytics: ^2.0.21 => 2.1.1
    gatsby-plugin-gtag: ^1.0.11 => 1.0.11
    gatsby-plugin-manifest: ^2.1.1 => 2.2.0
    gatsby-plugin-netlify-cms: ^4.1.1 => 4.1.1
    gatsby-plugin-offline: ^2.1.3 => 2.2.0
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.0
    gatsby-plugin-sass: ^2.0.11 => 2.1.0
    gatsby-plugin-sharp: ^2.1.5 => 2.2.1
    gatsby-plugin-sitemap: ^2.1.0 => 2.2.1
    gatsby-plugin-styled-components: ^3.0.7 => 3.1.0
    gatsby-plugin-twitter: ^2.0.13 => 2.1.0
    gatsby-plugin-typography: ^2.2.13 => 2.3.0
    gatsby-remark-copy-linked-files: ^2.0.13 => 2.1.0
    gatsby-remark-images: ^3.0.16 => 3.1.2
    gatsby-remark-prismjs: ^3.2.11 => 3.3.0
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.2.1
    gatsby-remark-smartypants: ^2.0.9 => 2.1.0
    gatsby-source-filesystem: ^2.0.39 => 2.1.1
    gatsby-transformer-remark: ^2.4.0 => 2.5.0
    gatsby-transformer-sharp: ^2.1.21 => 2.2.0
```

**Comment by interglobalmedia** [comment]
So I decided to go the github route for the backend along with the repo name, and that WOULD work, but using gatsby-plugin-netlify-cms breaks my  build, specifically because of sourcemaps. So until that issue is fixed, I will have to bag the whole idea and can't use it for clients. This is definitely a gatsby/gatsby plugin issue.

**Comment by wardpeet** [comment]
Did you install both `netlify-cms-app` and `gatsby-plugin-netlify-cms`? Do you get a out of memory issue?

**Comment by interglobalmedia** [comment]
Hi @wardpeet! Yes, I did. After much testing etc and research, I found that it is a terser issue. I however, do not use yarn. I use npm. And the only "resolution" for the source-maps issue on build (it breaks it) caused by a bug with terser:

[New installs of Gatsby fail on builds with source-map error](https://github.com/gatsbyjs/gatsby/issues/15249)

So I did the npm version of the temporary yarn fix with npm-force-resolutions:

[npm-force-resolutions Github repo](https://github.com/rogeriochaves/npm-force-resolutions)

However, I still have to test this remotely in staging on Netlfiy to make sure the build passes there as well.

**Comment by interglobalmedia** [comment]
oh, and I ended up removing git-gateway and just using Github and the repo in the config.yml. There just was not enough documentation on how to get git-gateway to work properly. I don't know if the alternative will be any better, but I will soon find out!

**Comment by interglobalmedia** [comment]
Hi @wardpeet Everything has been resolved. Am using git-gateway and am using Netlify CMS. Working beautifully. Required some workarounds to make everything happen, but the site was deployed to remote on Netlify successfully. Sorry for not responding sooner. Thanks!

**Comment by aaronearl** [comment]
What is the git repo, so we the community can use it as reference for other netlify CMS issues?

**Comment by interglobalmedia** [comment]
Sure. Repo: https://github.com/interglobalmedia/interglobalmedia Posts/podcasts regarding the issue(s): https://www.interglobalmedianetwork.com/blog/gatsby-terser-sourcemaps/ https://www.interglobalmedianetwork.com/blog/2019-07-10-gatsby-gatsby-image-and-netlify-cms/

**Comment by wardpeet** [comment]
Glad that everything is working. Sorry for dropping the ball here.
