### ISSUE TITLE
Build error in Netlify - Failed to validate error {ValidationError: child "error" fails because ["error" must be an object]

### ISSUE THREAD

**Issue by aldomonteiro** [gatsbyjs/gatsby#15538]
## Description

My site is running and I can build it locally fine with `gatsby build`, however, when I try to build it in Netlify it breaks. The deploy error shows messages related to `babel-preset-react`, however this dependency is not listed in my package.json, so, I guess it is some internal incompability with some package I am using. Below the deploy error messages:

```
Failed to validate error { ValidationError: child "error" fails because ["error" must be an object]
at Object.exports.process (/opt/build/repo/node_modules/@hapi/joi/lib/errors.js:202:19)
at internals.Object._validateWithOptions (/opt/build/repo/node_modules/@hapi/joi/lib/types/any/index.js:764:31)
at module.exports.internals.Any.root.validate (/opt/build/repo/node_modules/@hapi/joi/lib/index.js:145:23)
at constructError (/opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/structured-errors/construct-error.js:28:29)
at Object.error (/opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/index.js:100:29)
at Object.panic (/opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/index.js:58:24)
at reportFailure (/opt/build/repo/node_modules/gatsby/dist/commands/build.js:47:10)
at buildProductionBundle.catch.err (/opt/build/repo/node_modules/gatsby/dist/commands/build.js:102:5)
at <anonymous>
isJoi: true,
name: 'ValidationError',
details:
[ { message: '"error" must be an object',
path: [Array],
type: 'object.base',
context: [Object] } ],
_object:
{ error:
[ './.cache/production-app.js\nModule build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):\nError: Cannot find module \'babel-preset-react\' from \'/opt/build/repo\'\n- If you want to resolve "react", use "module:react"\n- Did you mean "@babel/react"?\n
```
[Here is the full deploy log in netlify](https://app.netlify.com/sites/confident-joliot-67d9fa/deploys/5d23aa6181f53500076532fe)

Today I updated every package to the latest version (see my [package.json](https://github.com/aldomonteiro/alinemarius3/blob/master/package.json)).

### Steps to reproduce

The repository is public, it is possible to deploy it on Netlify, [here is the github](https://github.com/aldomonteiro/alinemarius3).

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.0
  npmPackages:
    gatsby: ^2.13.9 => 2.13.9 
    gatsby-image: ^2.2.4 => 2.2.4 
    gatsby-plugin-google-analytics: ^2.1.1 => 2.1.1 
    gatsby-plugin-google-gtag: ^1.1.1 => 1.1.1 
    gatsby-plugin-manifest: ^2.2.1 => 2.2.1 
    gatsby-plugin-offline: ^2.2.1 => 2.2.1 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0 
    gatsby-plugin-sass: ^2.1.0 => 2.1.0 
    gatsby-plugin-sharp: ^2.2.3 => 2.2.3 
    gatsby-remark-copy-linked-files: ^2.1.0 => 2.1.0 
    gatsby-remark-images: ^3.1.3 => 3.1.3 
    gatsby-source-filesystem: ^2.1.2 => 2.1.2 
    gatsby-transformer-remark: ^2.6.1 => 2.6.1 
    gatsby-transformer-sharp: ^2.2.1 => 2.2.1

**Comment by bsh314** [comment]
I'm having the same issue after recent npm update.

**Comment by davidkartuzinski** [comment]
This seems to be the same issue as https://github.com/gatsbyjs/gatsby/issues/15242

**Comment by onokje** [comment]
I am having the same issue after a recent update of various packages

**Comment by wardpeet** [comment]
Closing because of duplication. Please move your comments to that thread. I'm currently working to get this resolved
