### ISSUE TITLE
[docs][contributing] blog content ideas page

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#15531]
## Summary

We get a lot of questions from folks who want to write for the Gatsby blog. This [process is mentioned in the contributing docs](https://www.gatsbyjs.org/contributing/blog-and-website-contributions/) as a way to ensure blog content will be approved. However, this adds some overhead for the Gatsby team to respond, so to make responses faster and easier it would help to have a blog ideas page to point to (along with a mention of what makes a blog post vs. a docs guide).

This page could live under [Blog and Website Contributions](https://www.gatsbyjs.org/contributing/blog-and-website-contributions/) in the sidebar, similar to how the [Docs Contributions](https://www.gatsbyjs.org/contributing/docs-contributions/) page has sub-pages.

### Evergreen (forever-relevant) content themes to list on this page
- E-commerce
- Content for "the Marketer"
- Web Performance
- Enterprise/Large sites
- PWAs
- Working with IT/Security
- Creating blogs
- Headless Wordpress
- Decoupled Drupal
- Accessible UIs

When the Gatsby team has chosen a specific quarterly theme to focus on, we can add it to the page.

We shouldn't list every _possible_ topic here, but instead focus on the most common content themes with a bit of strategy thrown into the mix (recurring Gatsby team updates will touch on this).

In the long term, it would be cool to link to existing blog posts that fit a given theme on the this page to encourage unique content (this could align well with blog tags/keywords and be aggregated as such). Here are the rest of the blog tags for inspiration: https://www.gatsbyjs.org/blog/tags

### Motivation

To provide more insight into what blog post topics would be the most beneficial for the Gatsby blog. It can also point to the [docs-templates](https://www.gatsbyjs.org/contributing/docs-templates/) page to clarify what makes a good blog post vs. going in the docs. The expected outcome would be to alleviate the burden on the Gatsby team when suggesting blog post topics as we get that question a lot.

**Comment by RedHoodJT1988** [comment]
So would this need to be an actual page that is created? I wouldn't mind giving it a go. I might have some more questions as I go along but would love to try to tackle this. I think I have a good idea on how it will look.

**Comment by marcysutton** [comment]
Yes–this would be a page in the contributing docs, with a few headings, paragraphs and unordered lists. Thanks for offering to work on it! Let me know if you have any questions.

**Comment by RedHoodJT1988** [comment]
Alright sounds good. I will get started on this ASAP. Hoping to have it
finished by next week at the latest.

**Comment by RedHoodJT1988** [comment]
I am still working on this. I have another open issue that I am tackling as
well so I am bouncing back and forth. Sorry for the delay.

**Comment by laurieontech** [comment]
@marcysutton Do we think this is still necessary given the added clarity in #19153 ?

**Comment by RedHoodJT1988** [comment]
Seems like the new instructions cover this pretty well.

**Comment by marcysutton** [comment]
Sure, that is certainly better than when I opened the issue. Thanks for following up here!
