### ISSUE TITLE
[docs][recipes] deploy to Netlify

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#15535]
## Summary

As part of the recipes initiative and the [Deploying to Netlify workflow](#13804), there should be a recipe on Deploying to Netlify. Recipes have a new [actionable format](https://www.gatsbyjs.org/contributing/docs-templates/#recipes) where the steps are included inline. Because a lot of this workflow happens outside of Gatsby itself, this recipe may take some experimentation to find the right amount of content. This recipe should leverage Prerequisites to list the required setup steps without having to show them all inline, and focus on the Gatsby-specific parts.

Recipes now follow this format:

- Requirements or prerequisites 
    - Gatsby CLI
    - A Gatsby site
- Step-by-step instructions
- Relevant links to any relevant information
    - More on [preparing a site for deployment](https://www.gatsbyjs.org/docs/preparing-for-deployment/)

This recipe should go into the "Deploying" section of [`docs/docs/recipes.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md) after the [Preparing for deployment recipe](#15319), and replacing the existing text. Docs URLs to gatsbyjs.org should be relative. There is a recipe template in the contributing docs: https://www.gatsbyjs.org/contributing/docs-templates/#recipes

For reference, the new recipe collection is also listed in a spreadsheet: https://docs.google.com/spreadsheets/d/1yNUQi_-3TsuDtE98hCIJQvLZ6X1YHlDmC-EJwOGxiHk/edit#gid=1252007048

**Comment by luizcieslak** [comment]
Hello Marcy! I got proactive and created #15673 in order to address this issue. I thought about a recipe using [netlify-cli](https://www.netlify.com/docs/cli/) because of [Hosting on Netlify](https://www.gatsbyjs.org/docs/hosting-on-netlify/) page which addresses the deploy using the Netlify website. Let me know if it is the right way.
