### ISSUE TITLE
gatsby-remark-images@3.1.3 height

### ISSUE THREAD

**Issue by spences10** [gatsbyjs/gatsby#15541]
## Description

Visual representation of 3.1.3 against 3.1.2

![image](https://user-images.githubusercontent.com/234708/60861726-4360b380-a213-11e9-9dfc-259cba7c9bb7.png)

![image](https://user-images.githubusercontent.com/234708/60861747-4eb3df00-a213-11e9-948c-83bd873fcefe.png)

I went back to 3.1.2, unfortunately I don't have time to investigate the issue further.

### Steps to reproduce

Netlify preview deploy of 3.1.3: https://deploy-preview-1542--blog-scottspence-me.netlify.com/convert-gatsby-default-blog-to-use-mdx

Preview version with 3.1.2: https://5d2427437af85500078c41c7--blog-scottspence-me.netlify.com/convert-gatsby-default-blog-to-use-mdx

Production version with 3.1.2: https://blog.scottspence.me/convert-gatsby-default-blog-to-use-mdx

**Comment by wardpeet** [comment]
I can't seem to reproduce it on https://deploy-preview-1542--blog-scottspence-me.netlify.com/convert-gatsby-default-blog-to-use-mdx.

Did this magically got fixed?

**Comment by vpicone** [comment]
I believe this is a duplicate of https://github.com/gatsbyjs/gatsby/issues/15486

**Comment by spences10** [comment]
Agreed @vpicone closing this in favour of #15486

I use `gatsby-mdx` and run all my remark plugins though `gatsbyRemarkPlugins` and don't use Gatsby remark in favour or Gatsby MDX.

https://github.com/spences10/blog.scottspence.me/blob/99495eddf935b7b2ea42cbd1247c5896bb1399eb/gatsby-config.js#L59-L87
