### ISSUE TITLE
Allow themes to modify existing GraphQL types

### ISSUE THREAD

**Issue by wangyi7099** [gatsbyjs/gatsby#15544]
I have a graphQL query like this:
```js
export const pageQuery = graphql`
  query TemplateDocsMarkdown($slug: String!) {
    allMdx(
      sort: { fields: fields___slug, order: DESC }
      filter: { fields: { slug: { glob: "/docs/*" } } }
    ) {
      edges {
        node { 
          frontmatter {
            title
            type
            order
          }
        }
      }
    }
  }
`;
```

But if my `md` file doesn't have a frontmatter `type` . then gatsby will show the error: 
`Unknown field 'type' on type 'MdxFrontmatter'.`

Can I get around this? Because I want  to make this field **optional**  in the frontmatter of each file.

**Comment by freiksenet** [comment]
Hi!

Take a look at [schema customization docs](https://www.gatsbyjs.org/docs/schema-customization/#explicitly-defining-data-types).

For your use case, you would need something like the following:

```
createTypes(`
  type MdxFrontmatter @infer {
    type: String
  }

  type Mdx implements Node @infer {
    frontmatter: MdxFrontmatter
  }
`)
```

**Comment by wangyi7099** [comment]
Hi I followed the docs and use the `createSchemaCustomization`  api in `gatsby-node.js`  which doesn't work. And gatsby show the errors:
`The following exports aren't APIs. Perhaps you made a typo or your plugin is outdated?`

This is my code, and I use it in a custom theme plugin:  
```js
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions;
  const typeDefs = `
  type MdxFrontmatter @infer {
    type: String
  }

  type Mdx implements Node @infer {
    frontmatter: MdxFrontmatter
  }
  `;
  createTypes(typeDefs);
};
```

**Comment by stefanprobst** [comment]
@wangyi7099 The `createSchemaCustomization` API is only available in Gatsby v2.12 and above. If you are using a different version, you can use `sourceNodes` instead of `createSchemaCustomization`.

**Comment by wangyi7099** [comment]
Thanks!
@freiksenet @stefanprobst I have updated to the lastest version and works properly!

**Comment by wangyi7099** [comment]
Hi. I have another problem just now..  
When I change the plugin from `gatsby-mdx` to `gatsby-plugin-mdx`..  The code below still don't work.
```js
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions;
  const typeDefs = `
  type MdxFrontmatter @infer {
    type: String
  }

  type Mdx implements Node @infer {
    frontmatter: MdxFrontmatter
  }
  `;
  createTypes(typeDefs);
};
```
And console still warns `Unknown field 'subtitle' on type 'MdxFrontmatter'`.  

I have a look at both codes and noted the difference between `gatsby-mdx` and `gatsby-plugin-mdx` .
#### gatsby-mdx 
Create type defination at [sourceNodes](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/gatsby/source-nodes.js)  hook.

#### gatsby-plugin-mdx

Create type defination at `onCreateNode`  hook.

Is this caused by creating type at different hooks?  Could you please give me some help? Thanks..

**Comment by stefanprobst** [comment]
* looks like you haven't provided a def for the `subtitle` frontmatter field?
* it is recommended to call `createTypes` from either the `sourcesNodes` API, or if you are using Gatsby 2.12+ the `createSchemaCustomization` API. The `onCreateNode` API is not a good place to do this because this would mean creating type defniitions every time a new node is added to the data layer.

**Comment by wangyi7099** [comment]
Hi! Sorry .. My code provided seems not complete, I just copy the above code, and the complete code is below:
`createSchemaCustomization.js`
```js
module.exports = ({ actions }) => {
  const { createTypes } = actions;
  const typeDefs = `
    type MdxFrontmatter @infer {
      type: String
      title: String
      subtitle: String
      disabled: Boolean
      link: String
      important: Boolean
    }

    type Avatar {
      href: String
      text: String
      src: String
    }

    type MdxFields @infer {
      avatarList: [Avatar]
    }
  
    type Mdx implements Node @infer {
      frontmatter: MdxFrontmatter
      fields: MdxFields
    }

    type SitePage implements Node @infer {
      context: SitePageContext
    }

    type SitePageContext @dontInfer  {
      webConfig: Json
    }
    `;
  createTypes(typeDefs);
};

```

**Comment by stefanprobst** [comment]
Is the repo public somewhere? I could take a closer look

**Comment by wangyi7099** [comment]
I have created a repo for this issue: [link](https://github.com/wangyi7099/gatsby-issue-15544)
Perhaps I use a theme?

**Comment by stefanprobst** [comment]
@wangyi7099 Thanks for the repo!

This is indeed an issue with themes. When running the project in the repo, you will see two warning messages printed:
```sh
warn Plugin `gatsby-issue-15544-theme` tried to define the GraphQL type `MdxFrontmatter`, which has already been defined by the plugin `gatsby-plugin-mdx`.
warn Plugin `gatsby-issue-15544-theme` tried to define the GraphQL type `Mdx`, which has already been defined by the plugin `gatsby-plugin-mdx`.
```

This means that the `createTypes` call in `theme/gatsby-config` does not actually modify the types.

This is because we don't allow just anyone to modify a type that already exists in the schema -- only plugins that own that type, or a user's `gatsby-config` are allowed to do that. What is missing is a way to also allow this for a theme's `gatsby-config`. I'll look into this.

**Comment by csr632** [comment]
I ran into this too
