### ISSUE TITLE
Add option to extend gatsby-config.js

### ISSUE THREAD

**Issue by TidyIQ** [gatsbyjs/gatsby#15549]
## Summary

Add the ability to extend an existing `gatsby-config.js`. Any additional options added will overwrite the extended config options. Basically, the same implementation as  `"extends"` in `tsconfig.json`.

### Basic example

```
// gatsby-config.js

module.exports = {
  extends: "path/to/different/gatsby-config.js",
  ...overwrites
}
```

### Motivation

I am creating an npm package that is essentially a template for Gatsby projects. Since it involves many plugins, `gatsby-config.js` needs to be modified for each project that uses the package. Currently the only options are to:

1. Force users to copy-paste the gatsby-config.js contents themselves
2. Clone from a repo

These are poor options as any time the npm package is updated and requires a change in `gatsby-config.js` (e.g. new plugins are added, settings are changed, plugins removed, etc.), the user has to manually apply the changes themselves to their own `gatsby-config.js` file. 

With this proposed change, users would simply need to run `npm update [package_name]` and they would immediately receive the new up-to-date configuration file.

This works extremely well for packages such as Typescript and ESLint and it would be fantastic to have this feature in Gatsby.

**Comment by lannonbr** [comment]
Would Gatsby Themes possibly help with this? You can put a base config in the theme and then when you use a theme, the site's gatsby-config is merged with any gatsby-configs from other themes. As well, as you upgrade a theme, the gatsby-config in the theme updates with it so a consumer of the theme doesn't need to touch it.

Here's the docs for Themes: https://www.gatsbyjs.org/docs/themes/what-are-gatsby-themes

**Comment by TidyIQ** [comment]
Oh nice, that sounds perfect. I didn't know that was a thing. I'll look into it more, thanks!

**Comment by lannonbr** [comment]
Alright. I'm going to close this for now as this seems to be resolved

**Comment by AryanJ-NYC** [comment]
@lannonbr Any idea what I'm doing wrong here? I'm hoping to extend `@narative/gatsby-theme-novela`'s use of `gatsby-transformer-remark`: https://github.com/AryanJ-NYC/webdev-coach-blog/blob/move-to-narrative/gatsby-config.js#L32.

The links still do not open as expected.

**Comment by lannonbr** [comment]
Let me open a new issue about this
