### ISSUE TITLE
User-defined project structure

### ISSUE THREAD

**Issue by rm-rf-etc** [gatsbyjs/gatsby#15543]
## Summary

Users should be able to define a gatsby project structure which is different from the default. This means telling gatsby where to look for `pages/`, which directories to exclude from query scanning, and probably more.

### Basic Example

This is my use case. I want to use one project to share `common/` components between various target builds.
```
root
   |- { package.json and gatsby config files live here }
   |- common
      |- { shared components live here }
   |- projects
      |- homepage
         |- { gatsby project pages and component files live here }
      |- desktop
         |- { electron project entry point and component files live here }
      |- web
         |- { CRA project entry point(s) and component files live here }
```

Forgive me if this is already possible. I've not been able to find a solution anywhere. I have a project which follows this structure and it runs successfully, but I can't prevent gatsby from scanning folders that I want to exclude.

It also seems to be the case that it's not possible to stop gatsby from expecting page components to be found in `src/pages/`, even when setting an alternate location with `gatsby-plugin-page-creator`.

## Motivation

I want to maintain a single repo with my shared components, and be able to build for different targets. I don't want to change directories to run various commands, or keep multiple `node_modules/` folders and multiple package.json files. Both Electron and CRA can cohabitate, I see no reason why gatsby could not do the same.

**Comment by wardpeet** [comment]
Homepage should be your gatsby root. So you'll have gatsby-config and a package.json. We always read from `src/pages/`, that's a convention we're having and cannot be turned of.

You're free to include components from common or any other directory. We have something called [gatsby themes](https://www.gatsbyjs.org/blog/2019-07-03-announcing-stable-release-gatsby-themes/) which might improve your use case when sharing gatsby config from site to site.

On another note, we also support client-side only routes, just as cra does. So no need to use CRA.

Does this help you?

**Comment by rm-rf-etc** [comment]
Hi Ward. Thanks for the quick response. Allow me to clarify.

> Homepage should be your gatsby root. So you'll have gatsby-config and a package.json. We always read from `src/pages/`, that's a convention we're having and cannot be turned of.

I'm not asking anyone to get rid of or change Gatsby conventions. They are very good conventions, they make a lot of sense, and it's a very intuitive structure. But what is the harm in allowing someone to override a Gatsby default convention with configuration options?

> You're free to include components from common or any other directory. We have something called [gatsby themes](https://www.gatsbyjs.org/blog/2019-07-03-announcing-stable-release-gatsby-themes/) which might improve your use case when sharing Gatsby config from site to site.

That really doesn't sound like my use case. I have an Electron and a Cordova app which I want to build using some of the same components I use in Gatsby. Cordova produces files which have certain keywords like `boundActionCreators` and `PagesQuery`, Gatsby then finds these when it scans all the directories and complains about it, and there's no way to tell Gatsby it can ignore these directories.

All of my other projects can be run and built from the project root, because they are configurable. Why can't Gatsby be configurable as well?

> On another note, we also support client-side only routes, just as cra does. So no need to use CRA.

Maybe, but given the lack of configurability, I'd be really hesitant to make that switch.

Does this clarify? Thanks again for all your work. I've been really happy and really impressed with Gatsby, just wish I could easily add Gatsby to my project.

**Comment by wardpeet** [comment]
I might have been a bit short in my description. We have tried making these directories configurable but it broke a few workflows. So we are a bit hesitant to look at it again for a v2 release. We might change this behaviour in v3.

> That really doesn't sound like my use case. I have an Electron and a Cordova app which I want to build using some of the same components I use in Gatsby. Cordova produces files which have certain keywords like boundActionCreators and PagesQuery, Gatsby then finds these when it scans all the directories and complains about it, and there's no way to tell Gatsby it can ignore these directories.

Could you elaborate a bit on this? Why would Gatsby complain about this? Could you maybe give an example?

I'm happy to show you the Gatsby way 😄

**Comment by rm-rf-etc** [comment]
I was able to get my project working. But let's start where I last left off.

## What Wasn't Working

I didn't mention `projects/mobile/`, but you can see it here. I've been using a framework called Evothings, which is set of tools with Cordova bundled.

<img width="1275" alt="Screenshot 2019-07-09 18 32 40" src="https://user-images.githubusercontent.com/5067463/60933712-535eae80-a278-11e9-9bba-fa7c0147ca9e.png">

I don't know why there is a build directory inside of the build directory, but you can see that the output uses `boundActionCreators`, and this causes gatsby to give the following warning:
```
 DONE  Compiled successfully in 3189ms                                                                                                                                           6:27:24 PM
⠀
You can now view homepage in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use npm run build
⠀
boundActionCreators is deprecated. Please use actions instead. For migration instructions, see https://gatsby.dev/boundActionCreators
Check the following files:
⠀
projects/mobile/build/build/main.chunk.js
projects/mobile/build/main.chunk.js
⠀
ℹ ｢wdm｣:
ℹ ｢wdm｣: Compiled successfully.
```

What bothers me is that gatsby is taking the time to read these files. I wish I could simply exclude everything under `projects/mobile/`.

## What Worked

I reevaluated my approach and decided to move the gatsby root files back to `projects/homepage/`, like you were saying. What I chose to do is keep `node_modules/` and `package.json` in the root of the project, and set my command for `yarn start-homepage` to `(cd projects/homepage && gatsby develop)`.

Everything works now! I even verified that I can successfully import files from `common/`. Thanks for considering my request. I still think Gatsby would benefit from added configurability and the option to exclude directories from parsing, but I realize it may not be feasible near-term. I'm just glad I got it working.
