### ISSUE TITLE
Build fail on Netlify but not locally: JavaScript heap out of memory

### ISSUE THREAD

**Issue by isif-ostewg** [gatsbyjs/gatsby#15540]
# Description

I am able to build the website locally but the build is not successful on Netlify.

### Steps to reproduce

https://github.com/isif-ostewg/isif-ostewg.org

### Expected result

Build should be successful.

E.g.

MacBook-Pro:isif-ostewg.org User$ gatsby build
success open and validate gatsby-configs - 0.085 s
success load plugins - 1.365 s
success onPreInit - 0.004 s
success delete html and css files from previous builds - 0.045 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success initialize cache - 0.028 s
success copy gatsby files - 0.085 s
success onPreBootstrap - 0.020 s
warn The gatsby-transformer-sharp plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 0.246 s
success building schema - 0.701 s
success createPages - 0.264 s
success createPagesStatefully - 0.049 s
success onPreExtractQueries - 0.002 s
success update schema - 0.068 s
success extract queries from components - 0.494 s
success write out requires - 0.007 s
success write out redirect data - 0.003 s
success Build manifest and related icons - 0.005 s
success onPostBootstrap - 0.019 s
⠀
info bootstrap finished - 7.245 s
⠀
success run static queries - 0.021 s — 1/1 61.95 queries/second

gatsby-plugin-purgecss: Only processing
success Building production JavaScript and CSS bundles - 53.446 s
success Rewriting compilation hashes - 0.005 s
success run page queries - 0.203 s — 19/19 96.35 queries/second

gatsby-plugin-purgecss:
 Previous CSS Size: 222.73 KB
 New CSS Size: 22.93 KB (-89.70%)
 Removed ~199.80 KB of CSS

success Building static HTML for pages - 1.906 s — 19/19 33.62 pages/second
Generated public/sw.js, which will precache 11 files, totaling 348963 bytes.
info Done building in 63.233 sec

### Actual result

2:07:12 AM: Build ready to start
2:07:14 AM: build-image version: 8e315e54bc4032a32e73290be556cde4f8348c12
2:07:14 AM: build-image tag: v2.8.2
2:07:14 AM: buildbot version: b925d11411cabfe7b120501027bd0e96dbc28dde
2:07:14 AM: Fetching cached dependencies
2:07:14 AM: Starting to download cache of 329.2MB
2:07:16 AM: Finished downloading cache in 2.267497057s
2:07:16 AM: Starting to extract cache
2:07:31 AM: Finished extracting cache in 14.283686256s
2:07:31 AM: Finished fetching cache in 16.687886282s
2:07:31 AM: Starting to prepare the repo for build
2:07:31 AM: Preparing Git Reference refs/heads/master
2:07:32 AM: Found netlify.toml. Overriding site configuration
2:07:32 AM: Starting build script
2:07:32 AM: Installing dependencies
2:07:33 AM: Started restoring cached node version
2:07:35 AM: Finished restoring cached node version
2:07:35 AM: v8.16.0 is already installed.
2:07:36 AM: Now using node v8.16.0 (npm v6.4.1)
2:07:36 AM: Attempting ruby version 2.3.6, read from environment
2:07:38 AM: Using ruby version 2.3.6
2:07:38 AM: Using PHP version 5.6
2:07:38 AM: Started restoring cached node modules
2:07:38 AM: Finished restoring cached node modules
2:07:38 AM: Started restoring cached yarn cache
2:07:38 AM: Finished restoring cached yarn cache
2:07:39 AM: Installing NPM modules using Yarn version 1.15.0
2:07:39 AM: yarn install v1.15.0
2:07:39 AM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
2:07:39 AM: [1/4] Resolving packages...
2:07:41 AM: [2/4] Fetching packages...
2:08:24 AM: info fsevents@1.2.9: The platform "linux" is incompatible with this module.
2:08:24 AM: info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
2:08:24 AM: [3/4] Linking dependencies...
2:08:24 AM: warning "gatsby-plugin-netlify > webpack-assets-manifest@3.1.1" has unmet peer dependency "webpack@>=4.4.0".
2:08:24 AM: warning " > gatsby-plugin-netlify-cms@4.1.1" has unmet peer dependency "netlify-cms-app@^2.9.0".
2:08:24 AM: warning "gatsby-plugin-sass > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
2:08:24 AM: warning " > lodash-webpack-plugin@0.11.5" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
2:08:24 AM: warning "netlify-cms > netlify-cms-media-library-cloudinary@1.3.2" has unmet peer dependency "netlify-cms-lib-util@^2.1.3-beta.0".
2:08:24 AM: warning "netlify-cms > netlify-cms-app > netlify-cms-widget-markdown > slate-edit-list@0.11.3" has incorrect peer dependency "slate@^0.32.0".
2:08:24 AM: warning " > slate-edit-table@0.15.2" has unmet peer dependency "slate-schema-violations@^0.1.7".
2:08:24 AM: warning " > uglifyjs-webpack-plugin@2.1.3" has unmet peer dependency "webpack@^4.0.0".
2:08:45 AM: [4/4] Building fresh packages...
2:08:51 AM: success Saved lockfile.
2:08:51 AM: Done in 71.75s.
2:08:51 AM: NPM modules installed using Yarn
2:08:51 AM: Started restoring cached go cache
2:08:52 AM: Finished restoring cached go cache
2:08:52 AM: Installing Go version 1.10
2:08:53 AM: unset GOOS;
2:08:53 AM: unset GOARCH;
2:08:53 AM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64';
2:08:53 AM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64/bin:${PATH}";
2:08:53 AM: go version >&2;
2:08:53 AM: export GIMME_ENV='/opt/buildhome/.gimme_cache/env/go1.10.linux.amd64.env';
2:08:53 AM: go version go1.10 linux/amd64
2:08:53 AM: Installing missing commands
2:08:53 AM: Verify run directory
2:08:53 AM: Executing user command: gatsby build
2:08:55 AM: success open and validate gatsby-configs — 0.074
2:08:56 AM: success load plugins — 1.321
2:08:56 AM: success onPreInit — 0.125
2:08:56 AM: success delete html and css files from previous builds — 0.005
2:08:56 AM: success initialize cache — 0.007
2:08:56 AM: success copy gatsby files — 0.023
2:08:56 AM: success onPreBootstrap — 0.014
2:08:57 AM: warning The gatsby-transformer-sharp plugin has generated no Gatsby nodes. Do you need it?
2:08:57 AM: success source and transform nodes — 0.207
2:08:57 AM: success building schema — 0.485
2:08:57 AM: success createPages — 0.230
2:08:57 AM: success createPagesStatefully — 0.035
2:08:57 AM: success onPreExtractQueries — 0.001
2:08:57 AM: success update schema — 0.067
2:08:58 AM: success extract queries from components — 0.469
2:08:58 AM: success write out requires — 0.004
2:08:58 AM: success write out redirect data — 0.001
2:08:58 AM: success Build manifest and related icons — 0.001
2:08:58 AM: success onPostBootstrap — 0.002
2:08:58 AM: info bootstrap finished - 5.268 s
2:08:58 AM: success run static queries — 0.019 — 1/1 57.27 queries/second
2:11:38 AM: <--- Last few GCs --->
2:11:38 AM: [1376:0x22844f0]   157258 ms: Mark-sweep 1391.5 (1537.5) -> 1391.5 (1539.5) MB, 3606.6 / 0.0 ms  allocation failure GC in old space requested
2:11:38 AM: [1376:0x22844f0]   161061 ms: Mark-sweep 1391.5 (1539.5) -> 1391.3 (1501.5) MB, 3802.3 / 0.0 ms  last resort GC in old space requested
2:11:38 AM: [1376:0x22844f0]   165051 ms: Mark-sweep 1391.3 (1501.5) -> 1391.3 (1497.0) MB, 3990.0 / 0.0 ms  last resort GC in old space requested
2:11:38 AM: <--- JS stacktrace --->
2:11:38 AM: ==== JS stack trace =========================================
2:11:38 AM: Security context: 0x1876ce25891 <JSObject>
2:11:38 AM:     1: ReferencedIdentifier [/opt/build/repo/node_modules/@babel/traverse/lib/scope/index.js:~128] [pc=0x18132a749031](this=0x189619e02831 <Object map = 0x2cef68e9de21>,path=0x1d99e021e949 <NodePath map = 0x2cef68e9e241>,state=0x189619e02831 <Object map = 0x2cef68e9de21>)
2:11:38 AM:     2: newFn [/opt/build/repo/node_modules/@babel/traverse/lib/visitors.js:~228] [pc=0x18132a617fb0](this=0x189619e02831 <Obje...
2:11:38 AM: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
2:11:38 AM:  1:
2:11:38 AM: node::Abort() [node]
2:11:38 AM:  2:
2:11:38 AM: 0x8cd14c [node]
2:11:38 AM:  3:
2:11:38 AM: v8::Utils::ReportOOMFailure(char const*, bool) [node]
2:11:38 AM:  4:
2:11:38 AM: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
2:11:38 AM:  5:
2:11:38 AM: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
2:11:38 AM:  6:
2:11:38 AM: 0xd83553 [node]
2:11:38 AM:  7:
2:11:38 AM: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
2:11:38 AM:  8: 0x181329e042fd
2:11:45 AM: /usr/local/bin/build: line 34:  1376 Aborted                 (core dumped) gatsby build
2:11:45 AM: Skipping functions preparation step: no functions directory set
2:11:45 AM: Caching artifacts
2:11:45 AM: Started saving node modules
2:11:45 AM: Finished saving node modules
2:11:45 AM: Started saving yarn cache
2:11:45 AM: Finished saving yarn cache
2:11:45 AM: Started saving pip cache
2:11:45 AM: Finished saving pip cache
2:11:45 AM: Started saving emacs cask dependencies
2:11:45 AM: Finished saving emacs cask dependencies
2:11:45 AM: Started saving maven dependencies
2:11:45 AM: Finished saving maven dependencies
2:11:45 AM: Started saving boot dependencies
2:11:45 AM: Finished saving boot dependencies
2:11:45 AM: Started saving go dependencies
2:11:48 AM: Finished saving go dependencies
2:11:48 AM: Error running command: Build script returned non-zero exit code: 134
2:11:48 AM: Failing build: Failed to build site
2:11:48 AM: failed during stage 'building site': Build script returned non-zero exit code: 134
2:11:48 AM: Finished processing build request in 4m33.846329411s

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.3.0 - ~/.nvm/versions/node/v11.3.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v11.3.0/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /Users/User/anaconda/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 66.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.11.7 => 2.13.9
    gatsby-paginate: ^1.1.0 => 1.1.0
    gatsby-plugin-catch-links: ^2.1.0 => 2.1.0
    gatsby-plugin-feed: ^2.3.1 => 2.3.2
    gatsby-plugin-force-trailing-slashes: ^1.0.4 => 1.0.4
    gatsby-plugin-google-analytics: ^2.1.1 => 2.1.1
    gatsby-plugin-google-tagmanager: ^2.1.0 => 2.1.1
    gatsby-plugin-manifest: ^2.2.0 => 2.2.1
    gatsby-plugin-netlify: ^2.1.0 => 2.1.0
    gatsby-plugin-netlify-cms: ^4.1.1 => 4.1.1
    gatsby-plugin-nprogress: ^2.1.0 => 2.1.0
    gatsby-plugin-offline: ^2.2.0 => 2.2.1
    gatsby-plugin-purgecss: ^3.1.1 => 3.1.1
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0
    gatsby-plugin-sass: ^2.1.0 => 2.1.0
    gatsby-plugin-sharp: ^2.2.1 => 2.2.3
    gatsby-plugin-sitemap: ^2.2.1 => 2.2.1
    gatsby-plugin-styled-components: ^3.1.0 => 3.1.0
    gatsby-remark-autolink-headers: ^2.1.0 => 2.1.0
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: ^3.1.2 => 3.1.3
    gatsby-remark-relative-images: ^0.2.2 => 0.2.2
    gatsby-remark-responsive-iframe: ^2.2.1 => 2.2.1
    gatsby-remark-smartypants: ^2.1.0 => 2.1.0
    gatsby-source-filesystem: ^2.1.1 => 2.1.2
    gatsby-transformer-remark: ^2.5.0 => 2.6.1
    gatsby-transformer-sharp: ^2.2.0 => 2.2.1

**Comment by TK05** [comment]
same errors for me trying to deploy a few different starters. same hang after `success run static queries`. same `JavaScript heap out of memory` error. same 134 exit code.

**Comment by wardpeet** [comment]
Seems like a duplication of https://github.com/gatsbyjs/gatsby/issues/15190. Closing
