### ISSUE TITLE
How to show images?

### ISSUE THREAD

**Issue by zwl1619** [gatsbyjs/gatsby#15548]
How to show images? 
![Snipaste_2019-07-09_18-24-05](https://user-images.githubusercontent.com/13177997/60881854-2e1e7000-a279-11e9-9077-7a7fb1bfdfcc.png)
It can not be shown correctly above.

**Comment by dantehemerson** [comment]
I think you need import, try this:
```
import logo from '../images/logo.png'

...

<img src={logo} />
```
Reference: https://www.gatsbyjs.org/docs/importing-assets-into-files/
