### ISSUE TITLE
How can I add my personal gatsby plugin to official docs?

### ISSUE THREAD

**Issue by JaeYeopHan** [gatsbyjs/gatsby#15550]
## Summary

How can I add my personal gatsby plugin to official docs?

## Relevant information

https://github.com/JaeYeopHan/gatsby-remark-images-medium-zoom

**Comment by m-allanson** [comment]
Hey @JaeYeopHan it looks like you've already [followed the steps in the docs](https://www.gatsbyjs.org/contributing/submit-to-plugin-library/), and your plugin can be found in Gatsby's plugin library: https://www.gatsbyjs.org/packages/gatsby-remark-images-medium-zoom/?=gatsby-remark-images-medium-zoom

Does that help?

**Comment by JaeYeopHan** [comment]
oh thanks! i didn’t know that! 🤦‍♂️
