### ISSUE TITLE
Hosting gatsby on Shared Hosting

### ISSUE THREAD

**Issue by afnizarnur** [gatsbyjs/gatsby#1555]
Hi, is it possible to host gatsbyjs on shared hosting? If yes, any tutorial to do that?

Thanks! :)

**Comment by nicholaswyoung** [comment]
Absolutely! Gatsby doesn't run server-side, so all you need is the ability to host static HTML. In that regard, any shared host should be capable.

All site assets (HTML, CSS, pre-processed images, etc.) are all stored in the `public/` folder after your build completes. Take that folder and upload it to your web root.

**Comment by afnizarnur** [comment]
Great to hear that! 
Thanks for you explanation :) @nicholaswyoung

**Comment by swacmade** [comment]
> Absolutely! Gatsby doesn't run server-side, so all you need is the ability to host static HTML. In that regard, any shared host should be capable.
> 
> All site assets (HTML, CSS, pre-processed images, etc.) are all stored in the `public/` folder after your build completes. Take that folder and upload it to your web root.

Hello,

I attempted doing this, I grabbed my public folder and placed it in my web root after running (npm run setup, npm run build) and my blog isn't actually updating with live posts i make from Contentful. Is it really as simple as grabbing the public folder and just placing it in the web root?

**Comment by DavidBarnes761** [comment]
@swacmade you have to first run "gatsby build"
