### ISSUE TITLE
Querying graphql when using commonjs style

### ISSUE THREAD

**Issue by pcr910303** [gatsbyjs/gatsby#15561]
#  Summary
I, as a node developer, use CommonJS style even in frontend code as that makes the codebase (backend & frontend) more coherent.
I would like to use CommonJS style-require & exports in Gatsby pages, but I could not get graphql queries to work.
I expect CommonJS style available since Gatsby seems to have existed before the ES6 import-style became commonplace.
How do I have to export my data to execute my query?

## Relevant information
I have done
1. ```module.exports = Component; module.exports.query = graphql``;

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@pcr910303 going to close this one in favor of #15562 as this one is a duplicate.
