### ISSUE TITLE
[gatsby-source-wordpress] Prevent media from downloading

### ISSUE THREAD

**Issue by geeknabe** [gatsbyjs/gatsby#15560]
Hello, 

Is it possible to stop the plugin from downloading media? For a website with a ton of photos, including the images would just bloat up the public folder.

**Comment by jonniebigodes** [comment]
@geeknabe yes it is. In your `gatsby-config.js` you can omit the `"**/media"` route and all of the images will be sourced directly from the wordpress instance. But don't forget that as all of the images in the pages or posts will be sourced directly from the wordpress installation, they are not available and need to be downloaded when the page is shown/rendered. That's why the route mentioned above in conjunction with the plugin is a better way, so that you have all of the images at build time and you can transform them as needed.

Feel free to provide feedback so that we can close this issue or continue to work on it till we find a suitable solution for your issue.

**Comment by geeknabe** [comment]
Alright, thanks for the info!

**Comment by brisa-pedronetto** [comment]
Still on this issue, sometimes you will want to use a media url but i I omit the "media" route I can't access, for example, the "featured_media" property in a post node. Is there a way I could get only the URL but not download the media?

**Comment by laurent-le-graverend** [comment]
Sorry if it sounds obvious – how to omit the "**/media" in gatsby-config.js?

**Comment by plong0** [comment]
I also couldn't find how to omit the "**/media" route, but found a workaround by setting the [`type.MediaItem.localFile.maxFileSizeBytes`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#typemediaitemlocalfilemaxfilesizebytes) option to 1 (0 seemed to still download the files, assuming it detects as empty and reverts to the default option value.)  This prevents downloading image files while still allowing a content node's `featuredImage.url` to be available.

```
          MediaItem: {
            localFile: {
              maxFileSizeBytes: 1,
            },
          },
```

**Comment by robmarshall** [comment]
@laurent-le-graverend To exclude a type, do the following in the config:

```{
  resolve: `gatsby-source-wordpress`,
  options: {
    type: {
      MediaItem: {
        exclude: true,
      },
    },
  },
}```

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#type__allexclude

**Comment by davidmann4** [comment]
You can disable the download by adjusting your settings, with the following settings it will source the images directly from your wordpress site:


```js
{
  resolve: `gatsby-source-wordpress`,
  options: {
    html: {
      useGatsbyImage: false,
      createStaticFiles: false,
    },
  },
}

```

via https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#htmlusegatsbyimage

### html.useGatsbyImage

Causes the source plugin to find/replace images in html with Gatsby images.

**Field type**: `Boolean`

**Default value**: `true`

```js
{
  resolve: `gatsby-source-wordpress`,
  options: {
    html: {
      useGatsbyImage: true,
    },
  },
}

```

### html.createStaticFiles

When this is true, any url's which are wrapped in "", '', or () and which contain /wp-content/uploads will be transformed into static files and the url's will be rewritten. This adds support for video, audio, and anchor tags which point at WP media item uploads as well as inline-html css like background-image: url().

**Field type**: `Boolean`

**Default value**: `true`

```js
{
  resolve: `gatsby-source-wordpress`,
  options: {
    html: {
      createStaticFiles: true,
    },
  },
}

```

**Comment by insaurabh** [comment]
> https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/plugin-options.md#htmlusegatsbyimage

If i do this then started getting error for featured_image or `opengraphImage`

 ```
opengraphImage {
          altText
          sourceUrl
          srcSet
        }
       
```

In Wordpress when I import properties from API they have lots of images, I am using image URL directly so no need to download those images when running build gatsby detects all those media changes which increase the total build time.

Any suggestion to get the URL but skip them in build process.
