### ISSUE TITLE
Try adding support for https://blurha.sh/

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#15563]
I ran across https://blurha.sh/ recently (via @jamo) which looks like an excellent blur-up — better than our existing method of relying on the browser to upscale a 20px image.

Would be interesting to try adding support for this to gatsby-plugin-sharp/gatsby-transformer-sharp/gatsby-image.

This would be an extra field on the image type that does the pre-processing. The library also includes a JS client library ([1.6kb](https://bundlephobia.com/result?p=blurhash@1.1.0)) that we'd include with gatsby-image — probably as an optional export e.g. `import Img from "gatsby-image/with-blurha"` or we could document how to pre-process the generated string to convert it back to an image.

Would someone like to try putting together a prototype so we can see how this works for real? Perhaps add this as another tab to https://using-gatsby-image.gatsbyjs.org/

**Comment by Darking360** [comment]
Hey! @KyleAMathews I'd love to try it out :rocket: Do you have like a getting started guide on how to contribute? :thinking: 

Let me know and I can start it tonight maybe (Venezuela time - GMT-4) :pray:

**Comment by KyleAMathews** [comment]
@Darking360 thanks for jumping in! We do have a contributing guide here https://www.gatsbyjs.org/contributing/how-to-contribute/

**Comment by Darking360** [comment]
Perfect @KyleAMathews  :writing_hand: I'll fork the project and setup everything to start a draft on this, I'll let you know any advances, thank you! :raised_hands:

**Comment by Darking360** [comment]
Greetings @KyleAMathews how are you? I'm really sorry for the delay 😓 

I just got time to finish the prototype for `blurhash`, I already create a PR [here](https://github.com/gatsbyjs/gatsby/pull/16419) to test it and check that.

It's pretty "prototype" so I didn't know how fancy to get it done so hehe let me know how do you see it, I think it's really cool, the string generated even for components with `X` and `Y` with 9 and 9 which are the highest are pretty small so it's nice 🚀 

Thanks a lot, I look forward for any feedback 💯 🙏

**Comment by m5r** [comment]
I took the opportunity to build a gatsby transformer for blurhash, let me know what you think about it

https://github.com/m5r/gatsby-transformer-blurhash
