### ISSUE TITLE
Odd routing behavior

### ISSUE THREAD

**Issue by emaddoma** [gatsbyjs/gatsby#15570]
## Summary
Site routing works as expected when developing locally. When deployed to Amplify the browser first changes routes and then performs a GET to server with trailing slash and then settles to route without trailing slash.  When built and run locally, behavior is at first like Amplify but then works fine after the initial hiccup.

## Relevant information
Here are logs from Chrome.  "Navigated to.." is Chrome generated.  "onRouteUpdate..." is from gatsby-browser.js.  User behavior in each environment is 1) load root 2) click link to /products 3) click link to /how-to 4) click link to /products

LOCAL DEVELOP

Navigated to http://localhost:8000/
onRouteUpdate  -> http://localhost:8000/
onRouteUpdate http://localhost:8000/ -> http://localhost:8000/products
onRouteUpdate http://localhost:8000/products -> http://localhost:8000/how-to
onRouteUpdate http://localhost:8000/how-to -> http://localhost:8000/products

STAGING (AWS Amplify)

Navigated to https://staging.myapp.amplifyapp.com/
onRouteUpdate  -> https://staging.myapp.amplifyapp.com/
onRouteUpdate https://staging.myapp.amplifyapp.com/ -> https://staging.myapp.amplifyapp.com/products
Navigated to https://staging.myapp.amplifyapp.com/products/
onRouteUpdate  -> https://staging.myapp.amplifyapp.com/products
onRouteUpdate https://staging.myapp.amplifyapp.com/products -> https://staging.myapp.amplifyapp.com/how-to
Navigated to https://staging.myapp.amplifyapp.com/how-to/
onRouteUpdate  -> https://staging.myapp.amplifyapp.com/how-to
onRouteUpdate https://staging.myapp.amplifyapp.com/how-to -> https://staging.myapp.amplifyapp.com/products
Navigated to https://staging.myapp.amplifyapp.com/products/
onRouteUpdate  -> https://staging.myapp.amplifyapp.com/products

LOCAL SERVE

Navigated to http://localhost:9000/
onRouteUpdate  -> http://localhost:9000/
onRouteUpdate http://localhost:9000/ -> http://localhost:9000/products
Navigated to http://localhost:9000/products/
onRouteUpdate  -> http://localhost:9000/products
onRouteUpdate http://localhost:9000/products -> http://localhost:9000/how-to
onRouteUpdate http://localhost:9000/how-to -> http://localhost:9000/products 

### Environment (if relevant)

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 61.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.9.0 => 2.9.2 
    gatsby-image: ^2.0.35 => 2.1.4 
    gatsby-plugin-google-tagmanager: ^2.1.1 => 2.1.1 
    gatsby-plugin-lodash: ^3.0.5 => 3.0.5 
    gatsby-plugin-manifest: ^2.0.25 => 2.1.1 
    gatsby-plugin-offline: ^2.0.25 => 2.1.3 
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.12 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.32 => 2.1.5 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-source-datocms: ^2.0.2 => 2.1.7 
    gatsby-source-filesystem: ^2.0.28 => 2.0.39 
    gatsby-source-graphql: ^2.0.15 => 2.0.19 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.21 
  npmGlobalPackages:
    gatsby-cli: 2.4.13

### File contents (if changed)

`gatsby-config.js`: N/A
`package.json`: N/A
`gatsby-node.js`: Far too extensive to put here.  Mainly graphql queries that create pages
`gatsby-browser.js`: Just some logging
`gatsby-ssr.js`: N/A

**Comment by cseebach-tpc** [comment]
If you are comfortable removing trailing slashes, you might try running with https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/ to see whether it helps make things more consistent. We use this in production in combination with a Lambda@Edge function to prevent the kind of behavior you're describing, where a page's location specified within Gatsby may not match the exact location it's being served from.

**Comment by emaddoma** [comment]
@cseebach-tpc We were using and prefer routes without the trailing slashes but I did eventually realize that Amplify didn't seem to be compatible out-of-the-box with them.  Deploying to Netlify as a sanity check proved my theory.  I didn't Lambda@Edge even existed until now.  Any chance you could share your function?

**Comment by cseebach-tpc** [comment]
@emaddoma unfortunately, it's probably protected company information that I can't share. What I can say is that you can use an OriginRequest Lambda@Edge function to map an incoming URL to any file in an S3 bucket that you want, by rewriting the CloudFront request URI to something of your choice. The best part is that CloudFront will cache your rewrite so your Lambda function gets invoked only once per file.

**Comment by RobinHerzog** [comment]
> @emaddoma unfortunately, it's probably protected company information that I can't share. What I can say is that you can use an OriginRequest Lambda@Edge function to map an incoming URL to any file in an S3 bucket that you want, by rewriting the CloudFront request URI to something of your choice. The best part is that CloudFront will cache your rewrite so your Lambda function gets invoked only once per file.

Do you force / with Lamdba or not?

**Comment by RobinHerzog** [comment]
I found this link https://www.ximedes.com/2018-04-23/deploying-gatsby-on-s3-and-cloudfront/ that is helpful

**Comment by RobinHerzog** [comment]
> @cseebach-tpc We were using and prefer routes without the trailing slashes but I did eventually realize that Amplify didn't seem to be compatible out-of-the-box with them. Deploying to Netlify as a sanity check proved my theory. I didn't Lambda@Edge even existed until now. Any chance you could share your function?

Did you solved your issue?
