### ISSUE TITLE
Cyrillic urls doesn't work after gatsby v2.13.1

### ISSUE THREAD

**Issue by pantaley** [gatsbyjs/gatsby#15571]
## Description
When updated to Gatsby 2.13.2 or newer Cyrillic routes doesn't work.

### Steps to reproduce
I've just forked [gatsby blog starter and changed hello-world folder](https://github.com/pantaley/gatsby-starter-blog) to random Cyrillic name and when open the page in develop the page is blank. You can see the change in the last commit [here](https://github.com/pantaley/gatsby-starter-blog/commit/8b90b2c49a97fd3262c532e54bb49f16be8d1f6a). Make sure you are on Gatsby version 2.13.2 or newer (included 2.13.10).

I can **confirm that on 2.13.1** everything is working.

There was [an issue before with terser v4.0.1](https://github.com/terser-js/terser/issues/380) it might be related.

Tested and it doesn't work on Firefox, Chrome and Edge.

### Expected result
Should show the hello-world blog post page.

### Actual result
 When inspected the DOM I only see this:
```html
<body>
    <noscript id="gatsby-noscript">This app works best with JavaScript enabled.</noscript>
    <div id="___gatsby"></div>
    <script src="/commons.js"></script>
</body>
```

No errors are shown in the browser console or in the terminal.

### Environment
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
  Binaries:
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.1.0
  npmPackages:
    gatsby: ^2.13.9 => 2.13.9
    gatsby-image: ^2.2.4 => 2.2.4
    gatsby-plugin-feed: ^2.3.2 => 2.3.2
    gatsby-plugin-google-analytics: ^2.1.1 => 2.1.1
    gatsby-plugin-manifest: ^2.2.1 => 2.2.1
    gatsby-plugin-offline: ^2.2.1 => 2.2.1
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0
    gatsby-plugin-sharp: ^2.2.3 => 2.2.3
    gatsby-plugin-typography: ^2.3.0 => 2.3.0
    gatsby-remark-copy-linked-files: ^2.1.0 => 2.1.0
    gatsby-remark-images: ^3.1.3 => 3.1.3
    gatsby-remark-prismjs: ^3.3.1 => 3.3.1
    gatsby-remark-responsive-iframe: ^2.2.1 => 2.2.1
    gatsby-remark-smartypants: ^2.1.0 => 2.1.0
    gatsby-source-filesystem: ^2.1.2 => 2.1.2
    gatsby-transformer-remark: ^2.6.1 => 2.6.1
    gatsby-transformer-sharp: ^2.2.1 => 2.2.1

**Comment by wardpeet** [comment]
This got fixed in gatsby@2.13.11. Please upgrade your gatsby version.
![image](https://user-images.githubusercontent.com/1120926/60960511-6f129500-a30a-11e9-8990-2b4db4a48c18.png)
