### ISSUE TITLE
gatsby build on Netlify broken with gatsby-mdx

### ISSUE THREAD

**Issue by cameron-yee** [gatsbyjs/gatsby#15581]
## Description
My Gatsby site is working fine in development, but breaking during build.  When I try to deploy to Netlify, I'm getting this error (see full log below):

![Screen Shot 2019-07-09 at 5 43 50 PM](https://user-images.githubusercontent.com/28813403/60930093-438f9c00-a271-11e9-8b89-c02983b92706.png)

I've poked around for about half a day and can't find anything related to this.

I'm querying allMdx in gatsby-node.js to create pages based off of a template for each markdown file.  I'm also querying allMdx on the "/about/leadership" page of the demo repo and displaying each node as a card.

### Steps to reproduce

1. Clone demo repo
2. Push to GitHub account associated with Netlify.
3. Create and deploy new site on Netlify.

Demo Repo:
https://github.com/cameron-yee/mdxfaildemo

### Expected result

Gatsby build should build and deploy on Netlify.

### Actual result

Gatsby build fails.

### Environment
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.1 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.11.1 => 2.11.1 
    gatsby-background-image: ^0.7.3 => 0.7.3 
    gatsby-image: ^2.2.3 => 2.2.3 
    gatsby-plugin-google-analytics: ^2.1.1 => 2.1.1 
    gatsby-plugin-manifest: ^2.2.0 => 2.2.0 
    gatsby-plugin-mdx: ^1.0.9 => 1.0.9 
    gatsby-plugin-netlify: ^2.1.0 => 2.1.0 
    gatsby-plugin-netlify-cms: ^4.1.0 => 4.1.0 
    gatsby-plugin-offline: ^2.2.0 => 2.2.0 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0 
    gatsby-plugin-robots-txt: ^1.4.0 => 1.4.0 
    gatsby-plugin-sass: ^2.1.0 => 2.1.0 
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1 
    gatsby-plugin-sitemap: ^2.2.0 => 2.2.0 
    gatsby-source-filesystem: ^2.1.1 => 2.1.1 
    gatsby-transformer-json: ^2.2.0 => 2.2.0 
    gatsby-transformer-remark: ^2.5.0 => 2.5.0 
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0 
  npmGlobalPackages:
    gatsby-cli: 2.4.16

## Netlify Build Log
9:44:19 AM: Build ready to start
9:44:25 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
9:44:25 AM: build-image tag: v3.3.2
9:44:25 AM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
9:44:25 AM: Fetching cached dependencies
9:44:25 AM: Starting to download cache of 255.1KB
9:44:25 AM: Finished downloading cache in 86.522297ms
9:44:25 AM: Starting to extract cache
9:44:25 AM: Failed to fetch cache, continuing with build
9:44:25 AM: Starting to prepare the repo for build
9:44:26 AM: No cached dependencies found. Cloning fresh repo
9:44:26 AM: git clone https://github.com/cameron-yee/mdxfaildemo
9:44:28 AM: Preparing Git Reference refs/heads/master
9:44:28 AM: Found netlify.toml. Overriding site configuration
9:44:28 AM: Starting build script
9:44:28 AM: Installing dependencies
9:44:29 AM: Downloading and installing node v8.11.1...
9:44:30 AM: Downloading https://nodejs.org/dist/v8.11.1/node-v8.11.1-linux-x64.tar.xz...
9:44:30 AM: 
######
9:44:30 AM:         9.0%
9:44:30 AM: 
###########################################################
9:44:30 AM: ############# 100.0%
9:44:30 AM: Computing checksum with sha256sum
9:44:30 AM: Checksums matched!
9:44:32 AM: Now using node v8.11.1 (npm v5.6.0)
9:44:33 AM: Attempting ruby version 2.6.2, read from environment
9:44:34 AM: Using ruby version 2.6.2
9:44:34 AM: Using PHP version 5.6
9:44:34 AM: Started restoring cached node modules
9:44:34 AM: Finished restoring cached node modules
9:44:34 AM: Started restoring cached yarn cache
9:44:34 AM: Finished restoring cached yarn cache
9:44:34 AM: Installing yarn at version 1.13.0
9:44:34 AM: Installing Yarn!
9:44:34 AM: > Downloading tarball...
9:44:34 AM: [1/2]: https://yarnpkg.com/downloads/1.13.0/yarn-v1.13.0.tar.gz --> /tmp/yarn.
9:44:34 AM: tar.gz.Sx5bWlJv2l
9:44:34 AM:   % Total    % Received % Xferd  Average Speed
9:44:34 AM:   Time    Time     Time  Current
9:44:34 AM:                                  Dload  Upload   Total   Spent    Left  Spee
9:44:34 AM: d
9:44:34 AM: 
  0     0    0     0    0     0      0      0 -
9:44:34 AM: -:--:-- --:--:-- --:--:--     0
9:44:34 AM: 
100    93  100    93    0     0
9:44:34 AM: 454      0 --:--:-- --:--:-- --:--:--   455
9:44:35 AM: 
100   609    0   609    0     0   1052      0 --:--:-- --:--
9:44:35 AM: :-- --:--:--  1052
9:44:35 AM:   0     0    0     0
9:44:35 AM:   0     0      0      0 --:--:-- --:--:-- --:--:--     0
9:44:35 AM: 
100 1142k  100 1142k    0     0  1137k      0  0:00:01  0:00
9:44:35 AM: :01 --:--:-- 5827k
9:44:35 AM: [2/2]: https://yarnpkg.com/downloads/1
9:44:35 AM: .13.0/yarn-v1.13.0.tar.gz.asc --> /tmp/yarn.tar.gz.Sx5bWlJv2l.asc
9:44:35 AM: 
100    97  100    97    0     0   2438      0 --:--:--
9:44:35 AM: --:--:-- --:--:--  2438
9:44:35 AM: 
100   613    0   613    0     0   3782      0 --:--:-- --:--
9:44:35 AM: :-- --:--:--  3782
9:44:35 AM: 
100   832  100   832    0     0   4075      0 --:--:--
9:44:35 AM:  --:--:-- --:--:--  4075
9:44:36 AM: > Verifying integrity...
9:44:36 AM: gpg: Signature made Tue 18 Dec 2018 04:04:55 PM UTC using RSA key ID B6FF4DE3
9:44:36 AM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
9:44:36 AM: gpg: Note: This key has expired!
9:44:36 AM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
9:44:36 AM:      Subkey fingerprint:
9:44:36 AM:  E219 30C4 D0A4 AA46 1858  1F7A E074 D16E B6FF 4DE3
9:44:36 AM: > GPG signature looks good
9:44:36 AM: > Extracting to ~/.yarn...
9:44:36 AM: > Adding to $PATH...
9:44:36 AM: > We've added the following to your /opt/buildhome/.profile
9:44:36 AM: > If this isn't the profile of your current shell then please add the following to your correct profile:
9:44:36 AM: export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
9:44:36 AM: 
9:44:36 AM: > Successfully installed Yarn 1.13.0! Please open another terminal where the `yarn` command will now be available.
9:44:37 AM: Installing NPM modules using Yarn version 1.13.0
9:44:37 AM: yarn install v1.13.0
9:44:37 AM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
9:44:37 AM: [1/4] Resolving packages...
9:44:43 AM: warning netlify-cms > netlify-cms-app > netlify-cms-core > react-router-redux@5.0.0-alpha.9: This project is no longer maintained.
9:44:45 AM: [2/4] Fetching packages...
9:45:15 AM: info fsevents@1.2.4: The platform "linux" is incompatible with this module.
9:45:15 AM: info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
9:45:15 AM: info fsevents@1.2.9: The platform "linux" is incompatible with this module.
9:45:15 AM: info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
9:45:16 AM: [3/4] Linking dependencies...
9:45:16 AM: warning "@mdx-js/mdx > @babel/plugin-syntax-jsx@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
9:45:16 AM: warning "@mdx-js/mdx > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
9:45:16 AM: warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
9:45:16 AM: warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
9:45:16 AM: warning "gatsby-plugin-netlify > webpack-assets-manifest@3.1.1" has unmet peer dependency "webpack@>=4.4.0".
9:45:16 AM: warning " > gatsby-plugin-netlify-cms@4.1.1" has unmet peer dependency "netlify-cms-app@^2.9.0".
9:45:16 AM: warning "gatsby-plugin-sass > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
9:45:16 AM: warning "netlify-cms > netlify-cms-media-library-cloudinary@1.3.2" has unmet peer dependency "netlify-cms-lib-util@^2.1.3-beta.0".
9:45:16 AM: warning "netlify-cms > netlify-cms-app > netlify-cms-core > redux-notifications > react-redux@4.4.10" has incorrect peer dependency "redux@^2.0.0 || ^3.0.0".
9:45:16 AM: warning "netlify-cms > netlify-cms-app > netlify-cms-widget-markdown > slate-edit-list@0.11.3" has incorrect peer dependency "slate@^0.32.0".
9:45:16 AM: warning "netlify-cms > netlify-cms-app > netlify-cms-widget-markdown > slate-edit-table@0.15.2" has incorrect peer dependency "slate@^0.33.3".
9:45:16 AM: warning "netlify-cms > netlify-cms-app > netlify-cms-widget-markdown > slate-edit-table@0.15.2" has unmet peer dependency "slate-schema-violations@^0.1.7".
9:45:59 AM: [4/4] Building fresh packages...
9:46:15 AM: success Saved lockfile.
9:46:15 AM: Done in 97.67s.
9:46:15 AM: NPM modules installed using Yarn
9:46:15 AM: Started restoring cached go cache
9:46:15 AM: Finished restoring cached go cache
9:46:15 AM: unset GOOS;
9:46:15 AM: unset GOARCH;
9:46:15 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
9:46:15 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
9:46:15 AM: go version >&2;
9:46:15 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
9:46:15 AM: go version go1.12 linux/amd64
9:46:15 AM: Installing missing commands
9:46:15 AM: Verify run directory
9:46:15 AM: Executing user command: gatsby build
9:46:18 AM: success open and validate gatsby-configs — 0.050
9:46:20 AM: success load plugins — 1.874
9:46:20 AM: success onPreInit — 0.002
9:46:20 AM: success delete html and css files from previous builds — 0.005
9:46:20 AM: success initialize cache — 0.007
9:46:20 AM: success copy gatsby files — 0.018
9:46:20 AM: success onPreBootstrap — 0.012
9:46:22 AM: success source and transform nodes — 2.012
9:46:22 AM: success building schema — 0.308
9:46:22 AM: success createPages — 0.046
9:46:22 AM: success createPagesStatefully — 0.038
9:46:22 AM: success onPreExtractQueries — 0.002
9:46:22 AM: success update schema — 0.023
9:46:23 AM: success extract queries from components — 0.516
9:46:23 AM: success write out requires — 0.003
9:46:23 AM: success write out redirect data — 0.001
9:46:23 AM: success Build manifest and related icons — 0.555
9:46:23 AM: success onPostBootstrap — 0.557
9:46:23 AM: info bootstrap finished - 8.086 s
9:46:23 AM: success run static queries — 0.011 — 1/1 102.79 queries/second
9:48:41 AM: Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
9:48:54 AM: success Building production JavaScript and CSS bundles — 150.219
9:48:54 AM: success Rewriting compilation hashes — 0.001
9:48:55 AM: success run page queries — 0.371 — 7/7 18.89 queries/second
9:48:57 AM: error #95313 ReferenceError: _objectSpread is not defined
9:48:57 AM: Building static HTML failed for path "/offline-plugin-app-shell-fallback/"
9:48:57 AM: See our docs page for more info on this error: https://gatsby.dev/debug-html
9:48:57 AM:   61 |   ({ components: componentsFromContext, children }) => (
9:48:57 AM:   62 |     <MDXScopeProvider __mdxScope={scopeContexts}>
9:48:57 AM: > 63 |       <MDXProvider components={{ ...componentsFromContext, ...components }}>
9:48:57 AM:      |       ^
9:48:57 AM:   64 |         {children}
9:48:57 AM:   65 |       </MDXProvider>
9:48:57 AM:   66 |     </MDXScopeProvider>
9:48:57 AM: 
9:48:57 AM:   WebpackError: ReferenceError: _objectSpread is not defined
9:48:57 AM:   
9:48:57 AM:   - wrap-root-element.js:63 
9:48:57 AM:     node_modules/gatsby-plugin-mdx/wrap-root-element.js:63:7
9:48:57 AM:   
9:48:57 AM: 
9:48:57 AM: Skipping functions preparation step: no functions directory set
9:48:57 AM: Caching artifacts
9:48:57 AM: Started saving node modules
9:48:57 AM: Finished saving node modules
9:48:57 AM: Started saving yarn cache
9:48:57 AM: Finished saving yarn cache
9:49:00 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
9:48:57 AM: Started saving pip cache
9:48:58 AM: Finished saving pip cache
9:48:58 AM: Started saving emacs cask dependencies
9:48:58 AM: Finished saving emacs cask dependencies
9:48:58 AM: Started saving maven dependencies
9:48:58 AM: Finished saving maven dependencies
9:48:58 AM: Started saving boot dependencies
9:48:58 AM: Finished saving boot dependencies
9:48:58 AM: Started saving go dependencies
9:48:58 AM: Finished saving go dependencies
9:49:00 AM: Error running command: Build script returned non-zero exit code: 1
9:49:00 AM: Failing build: Failed to build site
9:49:00 AM: Finished processing build request in 4m35.21082015s

**Comment by moonmeister** [comment]
Can you provide a full build log from netlify? Thanks.

**Comment by moonmeister** [comment]
FYI: I don't think this is related to the MDX plugin. Looks like the build just doesn't recognize the object rest spread syntax. Maybe make sure netlify is using the correct version of node.

**Comment by wardpeet** [comment]
@cameron-yee, it seems like you're using gatsby-mdx, we've deprecated gatsby-mdx in favour of `gatsby-plugin-mdx`

We're still fixing these docs pages https://github.com/gatsbyjs/gatsby/pull/15559 to be up to date with gatsby-plugin-mdx.

While updating you'll also have to update your mdx query in `leadership-template.js` to
```
export const query = graphql`
  query($nodeId: String!) {
    mdx(id: {eq: $nodeId}) {
      body
      frontmatter {
        date(formatString: "MMMM DD, YYYY"),
        seoCanonicalUrl,
        seoDescription,
        seoLang,
        additionalTags,
        fullName
        type,
        alt,
        image,
        template,
        title,
      }
    }
  }
`
```

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪

**Comment by cameron-yee** [comment]
@wardpeet I've migrated from gatsby-mdx to gatsby-plugin-mdx.  The README on the plugin page is out of date on the plugin page: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx.  @moonmeister I've also set NODE_VERSION on Netlify to match my local Node version (8.11.1).  Neither of these are causing the issue though.  My builds are still failing.  I've updated the description with my updated environment info and added a full Netlify build log as well.

**Comment by cameron-yee** [comment]
Turns out it was an issue with Babel: https://github.com/babel/babel/issues/10179.  I fixed this by adding @babel/core: ^7.5.4 to both devDependencies and resolutions in package.json.  It builds fine after this.

**Comment by bscs-dev-team** [comment]
We have this resolved for Gatsby on Netlify by adding `plugin-proposal-object-rest-spread` to Gatsby.

package.json:
"devDependencies": {
    "@babel/core": "^7.5.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.5.4",
    "babel-preset-gatsby": "^0.2.1"
},
"resolutions": {
    "@babel/core": "^7.5.4"
}

.babelrc in root:
{
  "presets": ["babel-preset-gatsby"],
  "plugins": ["@babel/plugin-proposal-object-rest-spread"]
}

**Comment by ehowey** [comment]
I can confirm this worked for me as well - I was getting an identical error.  I wonder if this needs to be fixed somewhere more permanent that does not need this workaround.  Thanks for your work in problem solving this!  Saved me a ton of headache!
