### ISSUE TITLE
question about graphql File type

### ISSUE THREAD

**Issue by peonmodel** [gatsbyjs/gatsby#1558]
i am trying to create a json file of metadata for my folder of images, ie the captions and descriptions
i have a folder structure of
```
- folder1
-- metadata.json
-- image 1
-- image 2...
```

in my metadata.json i have 
```json
[{
	"subfolder": "folder1",
	"description": "",
	"category": "",
	"titleImage": "image1.jpg",
	"photos": [
		{ "filename": "image1.jpg", "alt": "", "caption": "" },
		{ "filename": "image2.jpg", "alt": "", "caption": "" },
	]
}]
```
and the result of the query
```js
[{
    "id": `${dir}/metadata.json absPath of file`
	"subfolder": "folder1",
	"description": "",
	"category": "",
	"titleImage": { id: `${dir}/image1.jpg absPath of file` },  // somehow titleImage is automatically converted to File-compatible
	"photos": [
		{ "filename": "image1.jpg", "alt": "", "caption": "" },  // however my array is not
		{ "filename": "image2.jpg", "alt": "", "caption": "" },
	]
}]
```
i like how my titleImage is automatically converted, but i also would need my array of photos to be converted too

how may i do so?

**Comment by KyleAMathews** [comment]
This is possibly a bug. Not sure why they're not getting converted to links to the file nodes.

I won't have time to look into this for the next week or so but if you want to try fixing it yourself, the graphql schema creation happens in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-type.js

This page has documentation on setting up a Gatsby dev environment https://www.gatsbyjs.org/docs/how-to-contribute/#contributing

**Comment by peonmodel** [comment]
ya, its definitely a bug, but i have great difficulty hunting whats wrong due to some weird caching

```json
// somehow when there is more than 1 item in the array defined in json, none of them get converted
[{"titleImage": "image1.jpg"}, {"titleImage": "image2.jpg"}]  // both titleImage does NOT become File-compatible and remains just a string
```
is there a command to clear cache? i tried deleting .cache folder and purge my browser cache and re-ran gatsby develop, yet sometimes changes to my json file is not reflected
i am wondering if it is a async issue? that the json file have not been read?

**Comment by KyleAMathews** [comment]
There's been a number of PRs improving this so odds are this is fixed now. Please reopen if you discover otherwise!
