### ISSUE TITLE
`Gatsby Build` command failure at `loading command`

### ISSUE THREAD

**Issue by CPLepage** [gatsbyjs/gatsby#15599]
`gatsby build` command not working properly anymore.

Output : 

```
verbose set gatsby_log_level: "verbose"
verbose set gatsby_executing_command: "build"
verbose loading local command from: .../node_modules/gatsby/dist/commands/build.js

There was a problem loading the local build command. Gatsby may not be installed. Perhaps you need to run "npm install"? Cannot find module '../src/utils'

Error: Cannot find module '../src/utils'
  
  - loader.js:581 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:581:15
  
  - loader.js:507 Function.Module._load
    internal/modules/cjs/loader.js:507:25
  
  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17
  
  - v8-compile-cache.js:159 require
    [Landing]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - stateUtils.js:13 Object.<anonymous>
    [Landing]/[xstate]/lib/stateUtils.js:13:15
  
  - v8-compile-cache.js:178 Module._compile
    [Landing]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - loader.js:700 Object.Module._extensions..js
    internal/modules/cjs/loader.js:700:10
  
  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32
  
  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12
  
  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3
  
  - loader.js:637 Module.require
    internal/modules/cjs/loader.js:637:17
  
  - v8-compile-cache.js:159 require
    [Landing]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - StateNode.js:62 Object.<anonymous>
    [Landing]/[xstate]/lib/StateNode.js:62:20
  
  - v8-compile-cache.js:178 Module._compile
    [Landing]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - loader.js:700 Object.Module._extensions..js
    internal/modules/cjs/loader.js:700:10
  
  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32
```

Tried deleting node_modules and reinstall, but not chance.

```
$ gatsby -v
Gatsby CLI version: 2.7.8
Gatsby version: 2.13.12
```

**Comment by alexandremottet** [comment]
Same here, cron builds were working fine 3 hours ago.

**Comment by alexblunck** [comment]
Looks like the releases of `xstate` in the last couple of hours are related to this issue.

Pinning the `xstate` version works for me as a temporary workaround:
```
npm i xstate@4.6.4
```

**Comment by email2vimalraj** [comment]
Facing the same issue, tried the `xstate` too, not working. Getting exactly the same error.

**Comment by gojutin** [comment]
I experienced that same issue this morning and can confirm that the workaround provided by @alexblunck temporarily solves this issue.

**Comment by iamkevingreen** [comment]
@alexblunck fix didn't help me, experiencing all types of new weird problems and my `develop` has also stopped working suddenly, tried switching between versions of node/gatsby but with no luck

**Comment by jlfalcon3589** [comment]
@alexandremottet  Thanks, your solution works temporarily

**Comment by talensjr** [comment]
Also the latest version of [xstate](https://github.com/davidkpiano/xstate/releases) which is 4.6.7 work now (but for now you have to install it manually)

**Comment by gojutin** [comment]
@iamkevingreen - I am not sure if it will help, but I also removed `.cache`, `node_modules`, and `package-lock.json` and ran `npm i` before applying @alexblunck's fix. Might be worth a shot.

**Comment by iamkevingreen** [comment]
@gojutin I went a lil crazy, switching node versions, yarn-to-npm, etc. eventually pulled the previous working repo and simply updated xstate and it was finally working again on my end. 🙏

**Comment by jlfalcon3589** [comment]
@CPLepage Recently the [xstate](https://www.npmjs.com/package/xstate) released an update where the error was fixed. I made an npm i and perfectly executed the gastby develop, I hope it worked for you.
