### ISSUE TITLE
[gatsby-source-wordpress] media files with non-ASCII characters in their names are not downloaded

### ISSUE THREAD

**Issue by TitanNano** [gatsbyjs/gatsby#15593]
## Description
When gatsby-source-wordpress creates remote file nodes for URLs with non-ASCII characters, these nodes are silently ignored. 

### Steps to reproduce
Upload a media file that contains a non-ASCII character in its name, like German umlauts `Gädke_01-6.jpg` or other non ASCII symbols `hoeßlin-6.jpg`. 

### Expected result
All kinds of image names are properly downloaded. Therefore, `gatsby-source-wordpress` should encode all URLs to ensure valid URLs.

### Actual result
For some reason WordPress provides these invalid URLs through the API which `gatsby-source-wordpress` in turn does not expect. This causes the file nodes to be ignored.

### Environment
```
  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Yarn: 1.12.1
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 3.7.3 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 66.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.1.0 => 2.1.30 
    gatsby-awesome-pagination: ^0.3.3 => 0.3.4 
    gatsby-image: ^2.0.40 => 2.0.40 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.5 
    gatsby-plugin-netlify: ^2.0.0 => 2.0.0 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.0.1 => 2.0.1 
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3 
    gatsby-plugin-sitemap: ^2.1.0 => 2.1.0 
    gatsby-remark-images: ^2.0.1 => 2.0.1 
    gatsby-source-filesystem: ^2.0.1 => 2.0.1 
    gatsby-source-wordpress: ^3.0.1 => 3.0.44 
    gatsby-transformer-remark: ^2.1.1 => 2.1.3 
    gatsby-transformer-sharp: ^2.1.1 => 2.1.1 
  npmGlobalPackages:
    gatsby: 2.1.30
```

**Comment by jonniebigodes** [comment]
@TitanNano if you can see #14124 , the same happened to some other person using portuguese characters. As a workaround and don't know how big is your media library if you can just "clean" the filenames in the library. Remove the special characters in the files and it should work out alright.

Feel free to provide feedback

**Comment by TitanNano** [comment]
@jonniebigodes I'm afraid modifying the media names won't be possible for us. Would you accept a PR that encodes URLs before handing them to `createRemoteFileNode`? This would not work for URLs which are already properly encoded since they would get encoded a second time. But I assume WordPress will always return invalid / unencoded URLs.

**Comment by jonniebigodes** [comment]
@TitanNano if you're willing to do the change go for it. I'm ccing @gatsbyjs/core so that they are made aware that you're willing to do this small but probably necessary change. With that i would like for you to read the [contribution docs](https://www.gatsbyjs.org/contributing/how-to-contribute/), make the adjustments to the plugin in question and submit a pull request.

**Comment by TitanNano** [comment]
@jonniebigodes I created a PR #15835 for this issue.
