### ISSUE TITLE
Using static queries in dynamic pages

### ISSUE THREAD

**Issue by danboyle8637** [gatsbyjs/gatsby#15607]
I am building out a client routed side of my gatsby app. 

But there are a few plugins I use on my static side I would like to use in the dynamic app side... for example the oembed remark plugin. 

If all queries are run at build time... and I use a static query on the dynamic side of my app... will this work in production? 

It seems to work in development.

I guess my ultimate question is... if it works... how? if the page that would use the data isn't created yet until somebody hits that dynamic route?

Thanks!

**Comment by grantglidewell** [comment]
Can you give more detail?  Im not sure what you mean by dynamic side.

All page and static queries are run at build time. Nothing happens when someone hits a route in gatsby, it serves the static asset that was created at build time using the queries that were already run.

**Comment by danboyle8637** [comment]
@grantglidewell by dynamic I mean client side routing. So the pages don't get built until they are hit by the client. 

At least that's how I understand it. But when I do some static queries using the filesystem... I do get the data displaying... 

That's why I'm a little confused. 

But I've been designing my app data structure and all of my assets will be stored in the cloud anyway.

**Comment by grantglidewell** [comment]
I’ll need to see code to understand how you’re doing this as it’s not something Gatsby is built to handle from what you describe

**Comment by pieh** [comment]
@danboyle8637 Gatsby creates static page for client-only-paths - notice that creating page for client-only-paths looks like this:
```
createPage({
  path: `/app
  matchPath: `/app/*
  component: <path_to_component>
})
```

Gatsby will create `app/index.html` (and run page and static queries used there). Just note that those queries won't be dynamic (in sense that you can't use dynamic url as some kind of input to queries)
