### ISSUE TITLE
Upgrade core-js package to version 3

### ISSUE THREAD

**Issue by abumalick** [gatsbyjs/gatsby#15601]
## Summary
core-js version 2 is deprecated, we would like to be able to use core-js version 3 with gatsby

### Motivation

No one likes to use deprecated packages, Even React's documentation shows code that uses core-js@3 (and it is referenced in [gatsby's documentation](https://www.gatsbyjs.org/docs/browser-support/#note-about-ie--11))

### Problem

It is a breaking change and will need manual intervention of all site maintainers that uses core-js@2 to migrate their imports to version 3

core-js@2
```
import 'core-js/modules/es6.set';
import 'core-js/modules/es6.map';
```

core-js@3
```
import 'core-js/es/map';
import 'core-js/es/set';
```

### If we don't want this
If we are not ready to migrate, we should include a note in documentation on how to add core-js@2 polyfills instead of redirecting the user to reactjs documentation.
https://www.gatsbyjs.org/docs/browser-support/#note-about-ie--11

### Finally
I would be interested to work on this if it is ok.

**Comment by abumalick** [comment]
related issue: https://github.com/gatsbyjs/gatsby/issues/12744

**Comment by abumalick** [comment]
sorry about this, core-js@3 is already working with latest version of gatsby. We tested with an older version.

**Comment by donaldboulton** [comment]
Here is the current yarn only resolutions for gatsby@2.13.12 and other Gatsby plugins updated to current npm modules including `"babel-preset-gatsby": "^0.2.1",`
would be
`
"resolutions": {
    "core-js": "3",
    "lodash": "^4.17.11",
    "graphql": "14.1.1"
  },
`

And then you should use the latest snyk fixes for lodash and gatsby@2.13.12 Vulnerable module: mem Denial of Service (DoS) issues.

**Comment by abumalick** [comment]
I investigated some more, and it is still not possible to use core-js@3 with gatsby. Even if we can actually install it, core-js@2 will be the one that is bundled in the app. 

## Here is a reproduction

Here is a new gatsby site with core-js@3 installed: 
https://github.com/abumalick/gastby-polyfill-test/blob/master/package.json#L8

I print the core-js version from its package.json in the home page here: https://github.com/abumalick/gastby-polyfill-test/blob/master/src/pages/index.js#L14

And you can see the deployed result:
https://gastby-polyfill-test.netlify.com/
![image](https://user-images.githubusercontent.com/8377185/61040479-2a493580-a3c0-11e9-8c15-9f7d9ac60b92.png)

I assume it is due to gatsby's babel configuration.

Can we start working on an upgrade ?

**Comment by saadaouad** [comment]
The same problem for me, we have `core-js@3.1.4` on the node_modules:
```JS
{
  "name": "core-js",
  "description": "Standard library",
  "version": "3.1.4",
  "repository": {
    "type": "git",
    "url": "https://github.com/zloirock/core-js.git"
  },
  "main": "index.js",
  "license": "MIT",
  ...
}
```

But when I try to print the current version of `core-js` I'm getting `core-js@2.6.9`:

![image](https://user-images.githubusercontent.com/17694380/61042044-56b67f00-a3cb-11e9-8377-b0aa58177d4b.png)

**Comment by decimoseptimo** [comment]
+1

**Comment by wardpeet** [comment]
This line https://github.com/gatsbyjs/gatsby/blob/2616e379b157a0693ed8b34afc177027a58ad413/packages/gatsby/src/utils/webpack.config.js#L379 prevents us from switching to core-js. It's done to make sure we only bundle it once. We could probably revisit when modern builds #14289 have landed.

**Comment by abumalick** [comment]
I missed your comment @wardpeet . Thank you for your feedback. I hope you will be able to merge this PR soon!

**Comment by sidharthachatterjee** [comment]
We're now tracking dependency updates in https://github.com/gatsbyjs/gatsby/issues/16840 and that includes core-js v3 so I'm closing this issue for now

**Comment by wardpeet** [comment]
This won't fix it.

**Comment by xkb** [comment]
The problem here isn't that the version of core-js needs to be upgraded but rather that the internal aliasing forces dependencies to a single module resolution.

If you upgrade to core-js@3 you will break every dependency that relies on core-js@2. Since the paths are completely different. Storybook has gone through the same exact issue when trying to minimize the number or bundled core-js instances. In reality, core-js v2 + v3 are a total of 60kb (minified + gzipped). It's really not worth the optimization. 

For those who are looking for a work around, we've internally hacked webpack config via the following:
```
module.exports = {
  ...
  onCreateWebpackConfig: params => {
    ...
    const webpackConfig = params.getConfig();
    delete webpackConfig.resolve.alias['core-js'];
    params.actions.replaceWebpackConfig(webpackConfig);
  }
};
```

**Comment by circlingthesun** [comment]
Storybook appears to be using [corejs-upgrade-webpack-plugin](https://www.npmjs.com/package/corejs-upgrade-webpack-plugin) to translate corejs 2 imports to corejs 3 equivalents.

**Comment by Grsmto** [comment]
Hi,
I'm maintainer of a React plugin called [SimpleBar](https://github.com/Grsmto/simplebar) and currently our users can't use it with Gatsby because we bundle with core-js v3.
Does anyone would know a workaround I could apply to the code so it's usable in Gatsby? Or at least a workaround to get them working together even if it needs extra setup for the user?

Thanks. ref #345

**Comment by shanedg** [comment]
+1

**Comment by shanedg** [comment]
> For those who are looking for a work around, we’ve internally hacked webpack config via the following:
>
> ```
> module.exports = {
>   ...
>   onCreateWebpackConfig: params => {
>     ...
>     const webpackConfig = params.getConfig();
>     delete webpackConfig.resolve.alias['core-js'];
>     params.actions.replaceWebpackConfig(webpackConfig);
>   }
> };
> ```

Also include this when deleting the alias:
```
webpackConfig.resolve.modules = [
  path.resolve(__dirname, 'node_modules/gatsby/node_modules'), // for Gatsby's core-js@2
  'node_modules' // your modules w/ core-js@3
];
```

**Comment by kripod** [comment]
I could barely figure out why [`Object.fromEntries`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries), but it turns out that the reason has been lying in the [changelog](https://github.com/zloirock/core-js/blob/bd50bd56519864758ee5c36a8839c9c3f505a540/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#stable-ecmascript-features) of core-js v2 -> v3. After navigating through Gatsby's codebase, I found [this line](https://github.com/gatsbyjs/gatsby/blob/3d2f82d6909c5ed9621f232b9746cc0196d36193/packages/babel-preset-gatsby/src/index.js#L54) and it lead me up to this issue.

I would like to inquire about the status of this issue, as more and more features are on the way towards ES2019+. Thanks for diving into all the details above!

**Comment by dotansimha** [comment]
If someone is trying to use Yarn Workspaces and do that with a monorepo, you need to make sure `core-js@3` is installed on the root `node_modules` and not being installed in a nested directory, and the only way to ensure that is to add to your *root* `package.json` a dependency for `core-js@3`. 

Then, you should get something like that:

```
- node_modules
    - core-js (v3)
    - gatsby
        - core-js (v2)
```

And you `gatsby-node.js` should do this:

```
  const webpackConfig = getConfig()
  delete webpackConfig.resolve.alias['core-js'];

  webpackConfig.resolve.modules = [
    path.resolve(__dirname, '../../node_modules/gatsby/node_modules'),
    path.resolve(__dirname, './node_modules'),
    'node_modules'
  ]
  actions.replaceWebpackConfig(webpackConfig)

```

**Comment by AnnieTaylorCHEN** [comment]
A total newbie to Gatsby and I noticed this issue when I installed the cli. For learning purpose, I think it's ok to stick with older core-js now but I am also curious if this upgrade is going to happen any time soon. For future real-life projects I would like to use a updated version.

**Comment by aaroncampos** [comment]
Running into this problem here too, trying to use the form.io React library.

**Comment by MarcusCemes** [comment]
> In reality, core-js v2 + v3 are a total of 60kb (minified + gzipped). It's really not worth the optimization.

The real issue is that many libraries can not be used with Gatsby without understanding underlying webpack configurations and Gatsby workarounds to monkey-patch it. [Redoc](https://github.com/Redocly/redoc) is another library that just won't work (#17136).

`core-js@2` also gives a warning, and recommends `@3` due to the "amount of issues" that are present. This will most likely only get worse.

**Comment by florent-andre** [comment]
[This workaround](https://github.com/gatsbyjs/gatsby/issues/17136#issuecomment-568036690) works with an `npm install core-js` to get the @3 version.
Extracting it to help before the in Gatsby solving.

**Comment by vaclavnovotny** [comment]
I run into same issue porting large SPA from custom webpack config to Gatsby. I need corejs@3 features since codebase relies on it heavily. 

After installing corejs@3 I patched babel config in *babel.config.js* to use `corejs: 3` in [babel-preset-gatsby](https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby/src/index.js#L54)

```javascript
// babel.config.js
const presetGatsby = require('babel-preset-gatsby');

module.exports = function(api) {
	const gatsbyBabel = presetGatsby();
	gatsbyBabel.presets[0][1].corejs = 3;

	return gatsbyBabel;
};
```

and I removed alias in webpack config

```javascript
// gatsby-node.js

exports.onCreateWebpackConfig = function onCreateWebpackConfig({ actions, getConfig, stage }) {
	const config = getConfig();
	delete config.resolve.alias['core-js'];
	actions.replaceWebpackConfig(config);
}
```

develop runs and SSR builds, but I haven't tested it intensively yet. Do anyone sea any flaw in this approach?

**Comment by ryparker** [comment]
@vaclavnovotny 

Tried your approach however this is what I get when using `gatsby develop`
```ERROR #98123  WEBPACK

Generating SSR bundle failed

Caching was left unconfigured. Babel's plugins, presets, and .babelrc.js files can be configured
for various types of caching, using the first param of their handler functions:

module.exports = function(api) {
  // The API exposes the following:

  // Cache the returned value forever and don't call this function again.
  api.cache(true);

  // Don't cache at all. Not recommended because it will be very slow.
  api.cache(false);

  // Cached based on the value of some function. If this function returns a value different from
  // a previously-encountered value, the plugins will re-evaluate.
  var env = api.cache(() => process.env.NODE_ENV);

  // If testing for a specific env, we recommend specifics to avoid instantiating a plugin for
  // any possible NODE_ENV value that might come up during plugin execution.
  var isProd = api.cache(() => process.env.NODE_ENV === "production");

  // .cache(fn) will perform a linear search though instances to find the matching plugin based
  // based on previous instantiated plugins. If you want to recreate the plugin and discard the
  // previous instance whenever something changes, you may use:
  var isProd = api.cache.invalidate(() => process.env.NODE_ENV === "production");

  // Note, we also expose the following more-verbose versions of the above examples:
  api.cache.forever(); // api.cache(true)
  api.cache.never();   // api.cache(false)
  api.cache.using(fn); // api.cache(fn)

  // Return the value that will be cached.
  return { };
};

File: .cache/develop-static-entry.js

**Comment by aaroncampos** [comment]
Same here

**Comment by jooola** [comment]
Starting to have some scary warnings here, nothing critical, but this ticket might need to get some more attention.
```
warning gatsby > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby > gatsby-cli > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby > @reach/router > create-react-context > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby > gatsby-cli > yurnalist > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/custom > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/types > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/types > @jimp/bmp > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/types > @jimp/gif > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/custom > @jimp/core > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/types > @jimp/jpeg > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/types > @jimp/tiff > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/types > @jimp/png > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-blur > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-crop > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-color > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-contain > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-displace > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-blit > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-dither > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-flip > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-gaussian > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-mask > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-cover > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-invert > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-normalize > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-resize > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-rotate > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-scale > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/plugins > @jimp/plugin-print > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning gatsby-plugin-sharp > potrace > jimp > @jimp/types > @jimp/bmp > @jimp/utils > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-bootstrap > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning react-bootstrap > react-overlays > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
```

**Comment by Leodau** [comment]
Got warning too, still about core-js...

> 
> warning gatsby > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the n
> umber of issues. Please, upgrade your dependencies to the actual version of core-js@3.
> warning gatsby > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for 
> usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
> warning gatsby > gatsby-cli > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage
>  due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
> warning gatsby > @reach/router > create-react-context > fbjs > core-js@1.2.7: core-js@<3 is no longer maintain
> ed and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual 
> version of core-js@3.
> warning gatsby > gatsby-cli > yurnalist > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained a
> nd not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual vers
> ion of core-js@3.

**Comment by ryparker** [comment]
I seemed to get it to work in my project. This issue was only causing one of my modules (recharts) to fail at build time.

What seemed to fix it on my end was doing the following:
`yarn add core-js` - installs the latest core-js @ v3+

Replacing `gatsby-node.js` with:
```
const path = require("path")

exports.onCreateWebpackConfig = ({ actions, getConfig, stage }) => {
  const config = getConfig()

  const coreJs2config = config.resolve.alias["core-js"]
  delete config.resolve.alias["core-js"]
  config.resolve.alias[`core-js/modules`] = `${coreJs2config}/modules`
  try {
    config.resolve.alias[`core-js/es`] = path.dirname(
      require.resolve("core-js/es")
    )
  } catch (err) {}
  actions.replaceWebpackConfig(config)
}
```

This may not work for anyone else but it did for me.

**Comment by aaroncampos** [comment]
Thanks for the above @ryparker .  Your fix builds for me, which is a step ahead of some of the other patches, in my experience.  But, once I try to add the [react-formio](https://github.com/formio/react-formio) library, I get these errors again:

```
Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/web.dom-collections.iterator' in '/Users/aaroncampos/Projects/gatsby/project/node_modules/formiojs/widgets'

File: node_modules/formiojs/widgets/InputWidget.js
```

Just reporting this in case it's of use to anyone.

**Comment by wardpeet** [comment]
```js
const enableCoreJs3 = config => {
  const coreJs2config = config.resolve.alias['core-js'];
  delete config.resolve.alias['core-js'];
  config.resolve.alias[`core-js/modules`] = `${coreJs2config}/modules`;
  try {
    config.resolve.alias[`core-js/es`] = path.dirname(require.resolve('core-js/es'));
  } catch (err) {
    // ignore-error, core-js3 isn't available in the current directory
  }

  return config;
};

exports.onCreateWebpackConfig = ({ actions, stage, getConfig }) => {
  const config = getConfig();

  actions.replaceWebpackConfig(enableCoreJs3(config));
};
```

This works for core-js & core-js3 users

**Comment by wadkar** [comment]
I would like to report that a fresh install of `gatsby-cli` using `yarn global add gatsby-cli` issues similar warning. A quick look [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/package.json#L23) shows that `gatsby-cli` still depends on `"core-js": "^2.6.11"`. Is there any way with which we can upgrade `gatsby-cli` at least?

Is there a PR where we're tracking this issue? I would like to help!

**Comment by wadkar** [comment]
@wardpeet the PR #14289 is closed and you've mentioned that you'll do it in smaller chunks. Can you please let us know if there are any updates on it? I have a local dev environment setup and would be happy to help!

**Comment by lawwantsin** [comment]
Can we all agree that too many dependencies is the issue here?  This ticket is over a year old.  What a mess this framework is.  Glad they got 16mill to market this flaming pile.

**Comment by wadkar** [comment]
@lawwantsin I am afraid your comments do not help with the situation. It would be great if we all can follow the [code of conduct](https://www.gatsbyjs.org/contributing/code-of-conduct/) and find a way to resolve the issue.

For starters, can you please tell us how many is too many dependencies for this project? How can we reduce them? Would it be possible for us to discuss some rough sketch on how to go about reducing dependencies so maybe we can create separate issues/PRs and go about executing it?

I am sure the core-devs (i.e. those with write access) are doing there bit to improve the situation and we can help them by sending patches and providing constructive criticism.

**Comment by baronyoung** [comment]
Hello all - I'm assessing Gatsby at present for a new project I'm working on.  After seeing this warning message and reading this thread I'm concerned about how big of an issue this may become for me.  I expect the answer is "it depends on what other libraries you want to use".  But I'm hesitant to start work on a framework that may block me from using popular libraries I may decide to use later on.  How concerned should I be about this?  Thanks in advance.

**Comment by ENvironmentSet** [comment]
Oops, sorry for my mistake, I didn't knew that referencing issue from another repository effects to it's source.

**Comment by grohlingr** [comment]
I thinks this issue is quite important. Core.js@2 is obsolete and all the new shiny ECMAScript API wont work in old browsers. Stuff like `Array.prototype.flat`, `Array.prototype.flatMap` or `URLSearchParams` object might silently break your page for visitors using IE11, because *there is no warning you are using feature not polyfilled in corejs@2*, these APIs are not very common but might bring you an ugly surprise sometime soon.

**Comment by anicholls** [comment]
Agreed - this needs to be resolved ASAP! I've tried all the alias removal/remapping fixes suggested above and cannot seem to get past these `Can't resolve 'core-js/modules/*` webpack errors (conflicting with `core-js@3` in storybook). 

This is currently completely preventing me from using gatsby/docz with an existing storybook project.

**Comment by wadkar** [comment]
@wardpeet / other maintainers : can we please get an acknowledgement again that their is some work going on?

It would also be helpful if you can give me/others pointers on how one may approach on resolving the issue and I would be happy to create a PR. Having such a PR that aims to resolve this issue will let people see that the issue is being worked and what the progress is on the issue. (Assuming there's not such a PR already).

**Comment by djma777** [comment]
Hi guys! I managed to fix mine somehow...

My initial install was with the default started fine with `develop`. I got the error after installing styled-components and the plugins. -deprecated core-js

The steps I took to fix:
1. npm outdated -- check packages

2. npm install -- still got errors 
3. npm update -- worked!

**Comment by aivasiuta** [comment]
Hello. I use third-party dependency in my project which has core-js 3. I tried all solutions from this thread an it still doesn't work. Are there any updates on this issue?

**Comment by lylest** [comment]
can somebody please solve this in a very nice neat way please I am stuck here come one

**Comment by abumalick** [comment]
@wardpeet @LekoArts @KyleAMathews I can work on it if you are ok, but I will need some help from you to give me directions and answer my questions.

**Comment by wadkar** [comment]
@abumalick Sure! What questions do you have?

**Comment by lylest** [comment]
I can't create a new project it throws that I should update to core-js 3

**Comment by fxue89** [comment]
This is blocking many libraries with `core-js` 3 dependency. Could try using `@amcharts/amcharts4` to replicate the issue. It's becoming a big development blocker at the moment.

**Comment by tommmyy** [comment]
guys, this is OS, you can make the PR.

**Comment by abumalick** [comment]
Yes, this is open source, and this problem is a breaking change that is on the major version milestone. Personally I don't start working on something like this without any feedback from the maintainers.

**Comment by axe312ger** [comment]
Another way to use core-js v3  in Gatby 2 is to alter `babel-preset-gatsby`

My (hacky) babel.config.js:

```js
const gatsbyPreset = require('babel-preset-gatsby')

const data = gatsbyPreset()

data.presets = data.presets.map((presetData) => {
  if (presetData[1].corejs && presetData[1].corejs === 2) {
    presetData[1].corejs = 3
  }
  return presetData
})

module.exports = {
  presets: [data],
}
```

**Note:** This works for an edge-case I have to generate a tailwind config file using Gatsby & Theme-UI, I do **not** use it (yet) for my actual Gatsby page.


If it turns out that increasing the core-js version to 3 in the babel preset is enough for many people, we could add this as an option to the preset itself till we finally migrated fully to core-js v3: https://github.com/gatsbyjs/gatsby/tree/master/packages/babel-preset-gatsby#options

**Comment by Mandersen21** [comment]
Any news on this?

**Comment by wardpeet** [comment]
i'll be working on this, this week and next week. I'll keep you all posted.

**Comment by Mandersen21** [comment]
thanks @wardpeet :)

**Comment by bsgreenb** [comment]
Wan't to note that this is an issue when trying to integrate with Storybook 6 beta on my Gatsby Typescript setup.  Thanks for taking this on @wardpeet !

**Comment by wadkar** [comment]
Thanks @wardpeet looking forward to the PR against this issue. Will be happy to test and contribute to the PR.

**Comment by NoWorries** [comment]
Thanks @wardpeet, appreciate the effort 👍

**Comment by Undistraction** [comment]
For anyone bitten by missing polyfills in IE11, explicitly adding the ones you need using Gatsby's `onClientEntry` hook seems to work:
```javascript
// gatsby-browser.js
import endsWith from 'string.prototype.endswith'
...
export const onClientEntry = () => {
  // eslint-disable-next-line no-unused-expressions
  endsWith
  …
}
```

**Comment by robbienohra** [comment]
Hey, sorry late to join this thread. Just curious, what are the main blockers right now to fully implement this? (Stumbled onto this thread when trying to use the latest amcharts4 library in my Gatsby app and ran into issues)

**Comment by abumalick** [comment]
> For anyone bitten by missing polyfills in IE11, explicitly adding the ones you need using Gatsby's `onClientEntry` hook seems to work:
> 
> ```js
> // gatsby-browser.js
> import endsWith from 'string.prototype.endswith'
> ...
> export const onClientEntry = () => {
>   // eslint-disable-next-line no-unused-expressions
>   endsWith
>   …
> }
> ```
> 
> Note that the import alone won't work if you are using tree-shaking (and possibly your editor removing unused imports).
> 
> However this might work if there is code in a plugin that needs polyfilling, as I believe there is no guarantee of the order in which `onClientEntry` hooks are called.

you don't need to include endsWith in the onClientEntry function. If it is imported it will be included. 

```
// gatsby-browser.js
import endsWith from 'string.prototype.endswith'

export const onClientEntry = () => {

}
```

**Comment by wardpeet** [comment]
PR is up so should be in, in a few days

**Comment by jonathanstanley** [comment]
Just a note that #25158 was reverted with #25474  

Pending those upcoming changes, it might be good to reopen this issue.

**Comment by balibebas** [comment]
Great job almost getting this finished. I saw @wardpeet mention there were some performance impovements if this is integrated and push though both the upgrade and reversion. Hope this can be tackled without a major. If anything I'm sure some developers wouldn't mind seeing this go through a beta period of sorts so greenfield projects can start developing with the latest goods from the get-go.
