### ISSUE TITLE
Did gatsby clean get removed from CLI?

### ISSUE THREAD

**Issue by matt-subroot** [gatsbyjs/gatsby#15631]
I'm getting "Unknown argument: clean" when I run gatsby clean. Did this get removed or am I missing something? Running version 2.4.8

**Comment by sidharthachatterjee** [comment]
The `clean` command was added in `gatsby-cli@2.4.11` (https://github.com/gatsbyjs/gatsby/pull/9126)

Please upgrade using `npm i -g gatsby`
