### ISSUE TITLE
Port Create React App's eslint setup here

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1564]
Eslint does a much better job of explaining JS errors than browsers do which is helpful for everyone but especially beginners.

Instead of errors being hidden away in the browser console, we'd see something like this:

![eslint error](https://camo.githubusercontent.com/41678b3254cf583d3186c365528553c7ada53c6e/687474703a2f2f692e696d6775722e636f6d2f466e4c566677362e706e67)

Also it'd be great to use their error overlay https://github.com/facebookincubator/create-react-app/tree/master/packages/react-error-overlay

**Comment by saviomuc** [comment]
1) The first case is already covered by https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L10 right?

2) react-error-overlay is available on npm (https://www.npmjs.com/package/react-error-overlay) so we should just require the package.
As far as I understand we just need to add this line:
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js#L60 and this line https://github.com/facebookincubator/create-react-app/blob/af7fbae994e394553e1ecad14155f5e90675f4b5/packages/react-scripts/config/webpackDevServer.config.js#L72-L74 right?
I don't have a way to confirm this right now (no access to dev machine), but maybe somebody can take a look?

**Comment by KyleAMathews** [comment]
>The first case is already covered here, right?

Partly — we still need to add webpack-loader I believe

**Comment by cr101** [comment]
Having used Create-React-App recently, the error overlay in the browser makes debugging your code much easier.
![error_overlay](https://user-images.githubusercontent.com/4064582/28551914-0796307a-713f-11e7-8150-4c6b46a7cf28.gif)

**Comment by tsriram** [comment]
I'm gonna give this a go!

**Comment by tsriram** [comment]
Seems this is working already unless I'm overlooking something. I created a test site with https://github.com/gatsbyjs/gatsby-starter-hello-world and when there is a compile time error, I see the error in the terminal and also an overlay in browser which takes me to the error line in my editor when clicked. Is this what we want? Am I missing something?

**Comment by nickmccurdy** [comment]
I like that CRA includes eslint, but it is unnecessarily difficult to use custom eslint configs in the same project as CRA. Please consider a solution that either involves a peer dependency on eslint or a fully extensible eslint config so using Gatsby doesn't limit how users can use eslint. In my opinion this is already a huge incentive to switch from CRA to Gatsby and it would be great if we could maintain this flexibility.

**Comment by KyleAMathews** [comment]
Definitely want to do peerDependency on eslint. We don't want to show in the browser though minor eslint problems e.g. you add a bunch of more stylistic rules. I do like how CRA how does this.

**Comment by kkemple** [comment]
@KyleAMathews I can take this on with the other related ESLint issues, any information I need other than what's here? Do I have it right that we want the error overlay as well, and only on errors, not for warnings?

**Comment by KyleAMathews** [comment]
The overlay was added since this issue was lasted updated but porting CRA's eslint-loader implementation over would be great!

**Comment by m-allanson** [comment]
Done in #4893 🎉
