### ISSUE TITLE
plugins: readme from npm is sometimes deprecated

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#15651]
## Description

i see sometimes plugins with outdated description, because (i guess) the readme is fetched from npmjs.com

### Steps to reproduce

- go to https://www.gatsbyjs.org/plugins/
- search for mdx
- click on the result: gatsby-mdx
- result: https://www.gatsbyjs.org/packages/gatsby-mdx/?=mdx

### Expected result

- i expect the plugin description from here:
https://github.com/ChristopherBiscardi/gatsby-mdx

### Actual result

- i see an outdated readme from here https://www.npmjs.com/package/gatsby-mdx

**Comment by muescha** [comment]
> If you mark a plugin as deprecated, the plugin library won't show it.

_Originally posted by @KyleAMathews in https://github.com/gatsbyjs/gatsby/pull/15559#issuecomment-510719716_

but the problem is if the owner not update the npmjs then it is not possible :(

**Comment by lannonbr** [comment]
I would say this in particular is resolved as gastby-mdx is deprecated, and if this arises again, we could comment to a developer if they are no longer maintaining the plugin / it doesn't support the newest major version of Gatsby, then we can just ask them to deprecate it on NPM which will make it not show up in our library.
