### ISSUE TITLE
[gatsby-source-shopify] Cannot get image from "allShopifyCollection"

### ISSUE THREAD

**Issue by MaxHill** [gatsbyjs/gatsby#15655]
## Description

I have gatsby-source-shopify setup and I can fetch products and collections and everything. But when fetching collections it's not possible to get the collection image defined in shopify although the docs say that this should be possible.

### Steps to reproduce

Create new gatsby site. 
Install gatsby-source-shopify
Config gatsby-source-shopify

Add collection query to pages/index.js (straight from docs):
```
export const query = graphql`
  query {
    allShopifyCollection {
      edges {
        node {
          id
          descriptionHtml
          handle
          image {
            src
            alt
          }
          products {
            id
            handle
            title
          }
          title
        }
      }
    }
  }
`
```

### Expected result

Get result containing an image in "node"

### Actual result

Getting the following error:
```
 ERROR #85907  GRAPHQL

There was an error in your GraphQL query:

- Unknown field 'image' on type 'ShopifyCollection!'.

File: src/pages/index.js

 ERROR  Failed to compile with 1 errors                                                                                                                    10:11:54 AM
⠀
 error  in ./src/pages/index.js
⠀
Module Error (from ./node_modules/eslint-loader/index.js):

/code/personal/test-g/src/pages/index.js
  31:11  error  Cannot query field "image" on type "ShopifyCollection"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


 @ ./.cache/sync-requires.js 21:54-117
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
⠀
✖ ｢wdm｣:
ERROR in ./src/pages/index.js
Module Error (from ./node_modules/eslint-loader/index.js):

/code/personal/test-g/src/pages/index.js
  31:11  error  Cannot query field "image" on type "ShopifyCollection"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 21:54-117
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.

```

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
    npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.15 => 2.13.15 
    gatsby-image: ^2.2.5 => 2.2.5 
    gatsby-plugin-manifest: ^2.2.2 => 2.2.2 
    gatsby-plugin-offline: ^2.2.2 => 2.2.2 
    gatsby-plugin-react-helmet: ^3.1.1 => 3.1.1 
    gatsby-plugin-sharp: ^2.2.4 => 2.2.4 
    gatsby-source-filesystem: ^2.1.4 => 2.1.4 
    gatsby-source-shopify: ^2.1.5 => 2.1.5 
    gatsby-transformer-sharp: ^2.2.2 => 2.2.2

**Comment by pieh** [comment]
I couldn't reproduce this with my demo:
![Screenshot 2019-07-12 at 15 26 30](https://user-images.githubusercontent.com/419821/61131419-7d52e380-a4b9-11e9-8eec-f493a04825e6.png)

Is there chance of getting temporary access to your store to reproduce this issue? (of course would be handled privately in DMs)

**Comment by MaxHill** [comment]
Strange, getting an error on the same request. Yes, I'll send you a PM to give you access. :)

**Comment by MaxHill** [comment]
Strange, now it seems to work. It still underlines "image" in GraphiQL but it works.
<img width="1357" alt="Screenshot 2019-07-15 17 47 20" src="https://user-images.githubusercontent.com/5380169/61229627-cc528000-a728-11e9-850d-022d188cf059.png">


Sorry if I wasted your time... 
Still open to help if you want to try and reproduce this part of the problem.
