### ISSUE TITLE
Gatsby Plugin Feed (RSS format)

### ISSUE THREAD

**Issue by MaralS** [gatsbyjs/gatsby#15662]
Hello everyone,
I was wondering if I could change the format to the rss feed. I want to activate the automate publish with Pinterest but the platform does not support Atom rss feed yet. Is there an option to change the format of the feed ?
Thanks for your answer :)
Have a good day !

**Comment by pieh** [comment]
We are using https://www.npmjs.com/package/rss under the hoof for `gatsby-plugin-feed`. It seems like it supports adding custom elements, but will likely require pretty custom plugin options to make use of them.

Can you show example of rss feeds that Pinterest supports?

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Comment by MaralS** [comment]
Hello, sorry I'm responding so late. I think I know why I don't work. I have a custom domain but the link are generated from GHOST API (mydomain.ghost.io/ instead of mydomain.com/) that's why pinterest does not want to add automatically the rss feed. I don't know If I can change this. It would be great to change the links

Thanks in advance,
Maral
