### ISSUE TITLE
gatsby-source-wordpress allWordpressWpApiMenusMenusItems 

### ISSUE THREAD

**Issue by matt-subroot** [gatsbyjs/gatsby#15671]
## Description

allWordpressWpApiMenusMenusItems > edges > node > items > object_slug pulls in something other than the item slug when the type_label === "Category"

It should be the slug of the category, but instead pulls in either a blank string or something like "7-revision-v1"

### Steps to reproduce

Create a category in WP with a slug and add it to a menu
Install WP REST API Menus
Run gatsby app and open GraphiQL in the browser
Query allWordpressWpApiMenusMenusItems > edges > node > items > object_slug

### Expected result

It should match the query for allWordpressCategory > edges > node > slug

### Actual result

But it produces something else, in my case "7-revision-v1" and sometimes ""

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.2.1 - ~/.nvm/versions/node/v10.2.1/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v10.2.1/bin/yarn
    npm: 6.9.1 - ~/.nvm/versions/node/v10.2.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.14 => 2.13.14
    gatsby-image: ^2.2.4 => 2.2.4
    gatsby-plugin-manifest: ^2.2.1 => 2.2.1
    gatsby-plugin-offline: ^2.2.1 => 2.2.1
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0
    gatsby-plugin-sharp: ^2.2.3 => 2.2.3
    gatsby-source-filesystem: ^2.1.3 => 2.1.3
    gatsby-source-wordpress: ^3.1.5 => 3.1.5
    gatsby-transformer-sharp: ^2.2.1 => 2.2.1
  npmGlobalPackages:
    gatsby-cli: 2.7.10

**Comment by jonniebigodes** [comment]
@matt-subroot i've been testing this a bit and i can confirm that the issue is happening. Here are the steps i took and the results i got.

- Created a new category in my local wordpress installation, called `awesome category` with the following slug `my-awesome-category`.

- Created a new post associated with that category with random text.

- Created a new menu that "consumes" all the categories available called `newmenu`

- Modified `gatsby-config.js` from another issue that was also regarding wordpress, the WP REST API Menus wordpress plugin and Gatsby, transforming it into:
```javascript
module.exports = {
  plugins:[
    {
      resolve:`gatsby-source-wordpress`,
      options: {
        baseUrl: `localhost/wordpress`,
        protocol: `http`,
        hostingWPCOM: false,
        useACF: false,
        includedRoutes: [
          "**/categories",
          "**/posts",
          "**/pages",
           "**/tags",
           "**/taxonomies",
           "**/menus"
        ],
      }
    }
  ]
}

```

- Issued `gatsby develop` and opened a new browser window to `http://localhost:8000/___graphql` and issued the following query:
```graphql
{
  allMenusInformation: allWordpressWpApiMenusMenusItems {
    edges {
      node {
        name
        slug
        items {
          title
          object_slug
        }
      }
    }
  }
  allCategoriesInformation:allWordpressCategory {
    edges {
      node {
        name
        slug
      }
    }
  }
}

```
And it yelds the following result:
```json
{
  "data": {
    "allMenusInformation": {
      "edges": [
        {
          "node": {
            "name": "newmenu",
            "slug": "newmenu",
            "items": [
              {
                "title": "dummy",
                "object_slug": null
              },
              {
                "title": "i am the special one",
                "object_slug": null
              },
              {
                "title": "awesome category",
                "object_slug": null
              },
              {
                "title": "Sem categoria",
                "object_slug": "ola-mundo"
              }
            ]
          }
        }
      ]
    },
    "allCategoriesInformation": {
      "edges": [
        {
          "node": {
            "name": "awesome category",
            "slug": "my-awesome-category"
          }
        },
        {
          "node": {
            "name": "dummy",
            "slug": "dummy"
          }
        },
        {
          "node": {
            "name": "i am the special one",
            "slug": "i-am-the-special-one"
          }
        },
        {
          "node": {
            "name": "Sem categoria",
            "slug": "sem-categoria"
          }
        }
      ]
    }
  }
}
```
For me it's throwing null for each item. 
- Checking the menu route in the browser, namelly `http://localhost/wordpress/wp-json/wp-api-menus/v2/menus` yelds the following:
```json
[
  {
    "term_id":19,
    "name":"newmenu",
    "slug":"newmenu",
    "term_group":0,
    "term_taxonomy_id":19,
    "taxonomy":"nav_menu",
    "description":"",
    "parent":0,
    "count":4,
    "filter":"raw",
    "ID":19,
    "meta":{
      "links":{
        "collection":"http:\/\/localhost\/wordpress\/wp-json\/wp-api-menus\/v2\/menus\/",
        "self":"http:\/\/localhost\/wordpress\/wp-json\/wp-api-menus\/v2\/menus\/19"
      }
    }
  }
]
```
- Opening up browser window to `http://localhost/wordpress/wp-json/wp-api-menus/v2/menus/19` which is the route to the menu that was created yelds the following:
```json
{
  "ID":19,
  "name":"newmenu",
  "slug":"newmenu",
  "description":"",
  "count":4,
  "items":[
    {
      "id":264,
      "order":1,
      "parent":0,
      "title":"dummy",
      "url":"http:\/\/localhost\/wordpress\/category\/dummy\/",
      "attr":"",
      "target":"",
      "classes":"",
      "xfn":"",
      "description":"",
      "object_id":4,
      "object":"category",
      "object_slug":null,
      "type":"taxonomy",
      "type_label":"Categoria"
    },
    {
      "id":265,
      "order":2,
      "parent":0,
      "title":"i am the special one",
      "url":"http:\/\/localhost\/wordpress\/category\/i-am-the-special-one\/",
      "attr":"",
      "target":"",
      "classes":"",
      "xfn":"",
      "description":"",
      "object_id":12,
      "object":"category",
      "object_slug":null,
      "type":"taxonomy",
      "type_label":"Categoria"
    },
    {
      "id":266,
      "order":3,
      "parent":0,
      "title":"awesome category",
      "url":"http:\/\/localhost\/wordpress\/category\/my-awesome-category\/",
      "attr":"",
      "target":"",
      "classes":"",
      "xfn":"",
      "description":"this is a random category created for gatsby issue 15671",
      "object_id":18,
      "object":"category",
      "object_slug":null,
      "type":"taxonomy",
      "type_label":"Categoria"
    },
    {
      "id":267,
      "order":4,
      "parent":0,
      "title":"Sem categoria",
      "url":"http:\/\/localhost\/wordpress\/category\/sem-categoria\/",
      "attr":"",
      "target":"",
      "classes":"",
      "xfn":"",
      "description":"",
      "object_id":1,
      "object":"category",
      "object_slug":"ola-mundo",
      "type":"taxonomy",
      "type_label":"Categoria"
    }
  ],
  "meta":{
    "links":{
      "collection":"http:\/\/localhost\/wordpress\/wp-json\/wp\/v2\/menus\/",
      "self":"http:\/\/localhost\/wordpress\/wp-json\/wp\/v2\/menus\/19"
    }
  }
}
```
From my testing, it seems that the `object-slug` is actually the post slug associated with a given category.   And it seems that this is coming from wordpress itself not actually the Gatsby plugin. The reason why in my case the data is returning null, when upon checking my categories do exist and have slugs associated  it's a whole different issue non related to this one.

Feel free to provide feedback so that we can close this issue or continue to work on it till we find a suitable solution.

**Comment by matt-subroot** [comment]
Too bad as that plugin's author seems to have abandoned the project and commentors are reporting that PR are going un-merged or responded to.

My work around was to add some JS in the component file to pull the necessary string off the url field, finding the last part of the url which corresponds to the slug.

If there is no response from the plugin contributor(s) (WP REST API Menus), can gatsby-source-wordpress be modified to pull the slug from the last part of the url field?

It's a little hacky... but what else can be done?

**Comment by matt-subroot** [comment]
At least the docs should be updated to suggest the work around
