### ISSUE TITLE
[gatsby-remark-images]: backgroundColor option not working for transparent pngs

### ISSUE THREAD

**Issue by danielj41** [gatsbyjs/gatsby#15676]
## Description

I have the following `gatsby-config.js`, setting `gatsby-remark-images`'s backgroundColor option to `#222`. 

```js
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 590,
              backgroundColor: "#222",
            },
          },
        ]
      }
    }
```

I expect that to make the transparent portion of my pngs show up as `#222`, but they remain the default `white`.

### Steps to reproduce

- Check out demo project https://github.com/danielj41/blog-gatsby/blob/demo-for-issue/gatsby-config.js#L36-L37 .
- Check out branch `demo-for-issue`.
- Run `yarn build`, serve `public`. (`gatsby develop` was giving me inconsistent results)
- Load `/`. Click the "dark mode" checkbox.
- Load `/js-strict-mode`.

### Expected result

The transparent portion of the png should match the page background (`#222`)

<img width="667" alt="Screen Shot 2019-07-12 at 10 44 22 PM" src="https://user-images.githubusercontent.com/5705347/61167673-09373080-a4f7-11e9-822d-0dc95bd46369.png">

### Actual result

The transparent portion of the png shows up as `white`, the default background color setting.

<img width="696" alt="Screen Shot 2019-07-12 at 10 44 53 PM" src="https://user-images.githubusercontent.com/5705347/61167677-16541f80-a4f7-11e9-9b8e-62d4a3211884.png">

### Suggested fix

I was able to get it working as expected by changing https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/gatsby-browser.js#L8 from

```js
exports.onRouteUpdate = ({ pluginOptions }) => {
```

to

```js
exports.onRouteUpdate = (apiCallbackContext, pluginOptions) => {
```

That said, I don't know Gatsby well enough to say if that's the correct fix.

### Environment

```

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.19 => 2.13.19 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-plugin-catch-links: ^2.1.2 => 2.1.2 
    gatsby-plugin-dark-mode: ^1.1.0 => 1.1.0 
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3 
    gatsby-plugin-offline: ^2.2.3 => 2.2.3 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-sharp: ^2.2.6 => 2.2.6 
    gatsby-remark-copy-linked-files: ^2.1.2 => 2.1.2 
    gatsby-remark-custom-blocks: ^2.1.2 => 2.1.2 
    gatsby-remark-images: ^3.1.5 => 3.1.5 
    gatsby-remark-prismjs: ^3.3.3 => 3.3.3 
    gatsby-source-filesystem: ^2.1.5 => 2.1.5 
    gatsby-transformer-remark: ^2.6.4 => 2.6.4 
    gatsby-transformer-sharp: ^2.2.3 => 2.2.3 
  npmGlobalPackages:
    gatsby-cli: 2.7.7
```

Thank you!

**Comment by birjolaxew** [comment]
For the sake of saving someone some debugging time:

This happens because the plugin only uses `backgroundColor` to apply a `box-shadow` on the image. This is done [in `gatsby-browser.js`](https://github.com/gatsbyjs/gatsby/blob/c0ebd6098d5afdf818ce7b40198951fd4fba653b/packages/gatsby-remark-images/src/gatsby-browser.js#L33-L35) once the image finishes loading.

The easiest way to fix this would probably be to apply a `background-color` too, in the same place.

**Comment by danielj41** [comment]
Hi @birjolaxew, thank you for looking into this! I think I'm seeing a slightly different issue, though:

The 400px inset `box-shadow` works correctly for me, if I manually change the `box-shadow` color in devtools. The issue I'm seeing is that the `box-shadow` is always `white`, regardless of what `backgroundColor` I set in my `gatsby-config.js`.

I'm noticing that `pluginOptions.backgroundColor` is always undefined in the existing code, so it gets replaced by the default `white`. Do you think my proposed fix could work, [based on the docs for `onRouteUpdate`](https://www.gatsbyjs.org/docs/browser-apis/#onRouteUpdate)? 

> Change https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/gatsby-browser.js#L8 from
>
> 
> ```js
> exports.onRouteUpdate = ({ pluginOptions }) => {
> ```
> 
> to
> 
> ```js
> exports.onRouteUpdate = (apiCallbackContext, pluginOptions) => {
> ```



Thank you! :)

**Comment by birjolaxew** [comment]
@danielj41 Whoops, didn't even notice the box shadow was inset.

Ye, it seems like the problem just is that the `onRouteUpdate` uses the wrong signature, so the options always use default. The only place where the options are used is for the `backgroundColor`, which defaults to white. Your fix should help with that.

On a related note, it'd probably be nice to update the inset box shadow to use something other than `400px` - in case the image is more than `800px` wide.
