### ISSUE TITLE
Enable the grapgql explorer to run on local host even when the gatsby develop build is failing to aid debugging etc.

### ISSUE THREAD

**Issue by waywardm** [gatsbyjs/gatsby#15679]
## Summary

When the build fails in development mode using gatsby develop due to a graphql error or other error it would be helpful if the graphql server still ran that way it would be easy to distinguish whether errors were coming from the code or the qraphl query.

Sometimes you have to make adjustments to you graphql query in order for the code to work however there is no way of doing this when the build fails.

### Basic example

As an example I am current porting a site which was generated through gatsby using markdown files over to using datocms and sometimes you want to be able to compose new queries when you are in the midst of doing this. However if the build is failing due to me altering code you cannot then compose new queries to get the code working again.

### Motivation

To make development easier and debugging of sites

**Comment by pieh** [comment]
Hi, development server should still start, but there might a bug where we don't display link to it in terminal - please try visiting http://localhost:8000/___graphql even if it isn't displayed in terminal.

I'll take a look to fix this

**Comment by waywardm** [comment]
I even mean for something such as a grave error like this that kills the terminal, the graphql server should still boot up, as in most cases of an error the graphql query or syntax is to blame, even though the site environment might not boot up the should be no reason why the graphql explorer wouldn't.

I hope this makes sense.

![Capture](https://user-images.githubusercontent.com/12498554/61172138-6d4e0900-a578-11e9-94ed-fc562c2128f6.JPG)

**Comment by pieh** [comment]
Hmm yeah, this shouldn't terminate develop completely. I'll take a look at that as well

**Comment by pieh** [comment]
Can you update your gatsby version? It seems like this should be fixed in one of recent releases:
![Screenshot 2019-07-13 at 17 03 55](https://user-images.githubusercontent.com/419821/61173189-3daafb00-a590-11e9-86b0-ba4a97bd882a.png)

**Comment by waywardm** [comment]
i have just updated the cli, and it still kills the terminal generally. The error i made to generate the terminal kill was pretty severe to demonstrate, i just wondered if there should almost be a separate command that allowed you just to launch the graphql explorer such as gatsby dataexplorer so if an error did occur you could always launch that separately to check queries etc

im speaking just as a gatsby user with limited knowledge, I don't know easy that would be to implement.

**Comment by pieh** [comment]
You do need to update `gatsby` package inside your project (not `gatsby-cli`):
`npm install gatsby` (if you are using `npm`) or `yarn upgrade gatsby` (if you are using `yarn`)

Having separate command for running "just" graphql server is something we are considering, but not really for cases like this (debugging should be possible with regular develop command).

**Comment by waywardm** [comment]
i'm currently using the latest gatsby package

**Comment by pieh** [comment]
Can you paste output of `gatsby info`?

**Comment by AnimaMundi** [comment]
I'm also running into this issue.

I get this error `GraphQLDocumentError: Cannot query field "sub_section_sub_title" on type "PrismicBlogPostBodyContentSectionItems". Did you mean "sub_section_title1"?` and then the development server crashes.

The output of `gatsby info` is:
```
System:
  OS: Linux 4.19 Ubuntu 18.04.3 LTS (Bionic Beaver)
  CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
  Shell: 4.4.20 - /bin/bash
Binaries:
  Node: 10.16.3 - /usr/bin/node
  npm: 6.9.0 - /usr/bin/npm
Languages:
  Python: 2.7.15+ - /usr/bin/python
npmPackages:
  gatsby-cli: ^2.7.44 => 2.7.44
npmGlobalPackages:
  gatsby-cli: 2.7.31 
```

I also noticed that the error you posted @pieh happened in `gatsby-node.js`. I messed up my query in that file on purpose to see and it does actually work for me there too. The server crashes in a GraphQL query that I wrote in a template file.
