### ISSUE TITLE
Unknown argument `formatString`

### ISSUE THREAD

**Issue by ahmedelgabri** [gatsbyjs/gatsby#1567]
If I try to use `formatString` on the date from frontmatter [here](https://github.com/ahmedelgabri/gabri.me/blob/master/src/templates/post.js#L92), it shows this error

<img width="812" alt="screen shot 2017-07-19 at 21 23 59" src="https://user-images.githubusercontent.com/63876/28385549-c18934d0-6cc8-11e7-91f8-43167ad01828.png">

It doesn't work even in the graphql console

<img width="1325" alt="screen shot 2017-07-19 at 21 28 10" src="https://user-images.githubusercontent.com/63876/28385663-39aa7f3c-6cc9-11e7-93b4-6ea2bf11958e.png">

**Comment by nicholaswyoung** [comment]
You might try [formatting the date field](https://github.com/ahmedelgabri/gabri.me/blob/master/src/posts/articles/diy-vim-statusline.md) to something a bit more standard and see if that helps.

**Comment by KyleAMathews** [comment]
Yeah, a string has to be a standard date format for the various date formatting options to be added.

**Comment by ahmedelgabri** [comment]
cool, thanks @nicholaswyoung & @KyleAMathews

**Comment by daviddeejjames** [comment]
@KyleAMathews If I am using this with the Wordpress REST API, how do I ensure its being returned as a string, looking at the example in the Gatsby repo it seems that it kind just works? So Im guessing there is a Wordpress setting you've changed to make the REST API return date as a string?

**Comment by KyleAMathews** [comment]
Try using gatsby-source-wordpress which handles this for you.

**Comment by daviddeejjames** [comment]
@KyleAMathews sorry I should have clarified I am using gatsby-source-wordpress and have created a blog page that uses the GraphQL query below. It works as intended! But would like to format the date without having to use something like MomentJS to format after the fact. However by adding the `date(formatString: "MMMM DD, YY")` that you have used in your Wordpress example, I am thrown the Unknown argument "formatString"

Any assistance with this issue would be greatly appreciated 👍 


```js
// Working Query
export const postQuery = graphql`
  query getPostQuery {
    allWordpressPost(sort: { fields: [date] }) {
      edges {
        node {
          id
          title
          excerpt
          slug
          date
        }
      }
    }
  }`
```

**Comment by KyleAMathews** [comment]
This just means that for some reason the data in your "date" field doesn't look dates to Gatsby. You'll need to do some debugging to see what your data looks like. Also might want to add some console.logs here https://github.com/gatsbyjs/gatsby/blob/8e271dac240c9374c654d1576fefafe4319cb314/packages/gatsby-source-wordpress/src/normalize.js#L108 Perhaps the WordPress API doesn't always include `*_gmt` fields.

**Comment by andrejarboe** [comment]
date must be: 2000-01-01
NOT 2000-1-1

that was my problem
