### ISSUE TITLE
Official themes should include "Powered by Gatsby" in footer

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#15686]
Or "Gatsby Inside" logo if we want to go with that.

**Comment by polishedwp** [comment]
I will be glad to work on this one.

**Comment by sidharthachatterjee** [comment]
CC @fk in case we need a logo for this

**Comment by polishedwp** [comment]
What about the "starters?"  Right now their footer's state "[Built with Gatsby](https://github.com/gatsbyjs/gatsby/blob/ef4eea27d6570573ba2cde10d37899ca67b55b72/starters/blog/src/components/layout.js#L66}."
Do we want the themes to match them for consistency?

**Comment by nguyenami** [comment]
@polishedwp do you mind sharing one? I would like to do one for the gatsby-starter-hello-world.

**Comment by polishedwp** [comment]
So, I installed each of the starters and the only starter that displays the 404 error in the terminal is the hello-world starter. 

The 404 message appears in each of the default theme starters including the new workspace theme starter.
