### ISSUE TITLE
The plugin "gatsby-source-filesystem@2.1.5" is exporting a variable named "createSchemaCustomization" which isn't an API.

### ISSUE THREAD

**Issue by jvue96** [gatsbyjs/gatsby#15680]
### Description

(apologies if I'm not being specific enough, first issue I've ever submitted on Github.)

I was following Andrew Meads Gatsby tutorial https://www.youtube.com/watch?v=8t0vNu2fCCM, and successfully deployed an application onto Netlify. However, I'm unable to deploy anything now. 

I did experience some vulnerability messages from Github, but I have updated the things in the yarn.lock that were required to update. 

When deploying on Netlify, I do notice a couple of error that stand out: 
The plugin "gatsby-source-filesystem@2.1.5" is exporting a variable named "createSchemaCustomization" which isn't an API.

### Steps to reproduce

Full project code up to date is in this repo:
https://github.com/jvue96/gatsby/tree/prototype2
download/fork/clone 
or just view my repo.

### Expected result

I should just be able to deploy a branch or a master branch, and upload it. I've tried it with another public repo that used Gatsby and it worked. 

### Actual result

3:53:18 AM: Build ready to start
3:53:23 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
3:53:23 AM: build-image tag: v3.3.2
3:53:23 AM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
3:53:23 AM: Fetching cached dependencies
3:53:23 AM: Failed to fetch cache, continuing with build
3:53:23 AM: Starting to prepare the repo for build
3:53:24 AM: No cached dependencies found. Cloning fresh repo
3:53:24 AM: git clone https://github.com/jvue96/gatsby
3:53:24 AM: Preparing Git Reference refs/heads/prototype2
3:53:25 AM: Starting build script
3:53:25 AM: Installing dependencies
3:53:26 AM: Downloading and installing node v10.16.0...
3:53:27 AM: Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz...
3:53:27 AM: 
##                                                                         3.5%
3:53:27 AM: 
##########################################
3:53:27 AM:                           59.2%
3:53:27 AM: 
######################################################################## 100.0%
3:53:27 AM: Computing checksum with sha256sum
3:53:27 AM: Checksums matched!
3:53:30 AM: Now using node v10.16.0 (npm v6.9.0)
3:53:31 AM: Attempting ruby version 2.6.2, read from environment
3:53:32 AM: Using ruby version 2.6.2
3:53:32 AM: Using PHP version 5.6
3:53:32 AM: Started restoring cached node modules
3:53:32 AM: Finished restoring cached node modules
3:53:32 AM: Started restoring cached yarn cache
3:53:32 AM: Finished restoring cached yarn cache
3:53:32 AM: Installing yarn at version 1.13.0
3:53:32 AM: Installing Yarn!
3:53:32 AM: > Downloading tarball...
3:53:32 AM: [1/2]: https://yarnpkg.com/
3:53:32 AM: downloads/1.13.0/yarn-v1.13.0.tar.gz --> /tmp/yarn.tar.gz.JMPByucu6f
3:53:32 AM:   % Total    % Recei
3:53:32 AM: ved % Xferd  Average Speed   Time    Time     Time  Current
3:53:32 AM:                                  Dload  Upload   Total   Spent    Left  Speed
3:53:32 AM: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:
3:53:32 AM: --:--     0
3:53:33 AM: 
100    93  100    93    0     0
3:53:33 AM:    354      0 --:--:-- --:--:-- --:--:--   354
3:53:33 AM: 
  0     0    0     0    0     0      0      0
3:53:33 AM: --:--:-- --:--:-- --:--:--     0
3:53:33 AM: 
100   609    0   609    0     0    986      0 --:-
3:53:33 AM: -:-- --:--:-- --:--:--  4171
3:53:34 AM: 
100 1142k  100 1142k    0     0  1103k      0  0:00:01  0:00:01 --:--:-- 1
3:53:34 AM: 103k
3:53:34 AM: [2/2]: https://yarnpkg.com/downloads/1.13.0/yarn-v1.13.0.tar.gz.asc --> /tm
3:53:34 AM: p/yarn.tar.gz.JMPByucu6f.asc
3:53:34 AM: 
100    97  100    97    0     0   1679      0 --:--:-- --
3:53:34 AM: :--:-- --:--:--  1679
3:53:34 AM: 
100   613    0   613    0     0   3717      0 --:--:-- --:--:-- --:--:--  3717
3:53:34 AM: 
100   832  100   832    0     0   3769
3:53:34 AM:  0 --:--:-- --:--:-- --:--:--  3769
3:53:34 AM: > Verifying integrity...
3:53:34 AM: gpg: Signature made Tue 18 Dec 2018 04:04:55 PM UTC using RSA key ID B6FF4DE3
3:53:34 AM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
3:53:34 AM: gpg: Note: This key has expired!
3:53:34 AM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
3:53:34 AM:      Subkey fingerprint: E219 30C4 D0A4 AA46 1858  1F7A E074 D16E B6FF 4DE3
3:53:34 AM: > GPG signature looks good
3:53:34 AM: > Extracting to ~/.yarn...
3:53:34 AM: > Adding to $PATH...
3:53:34 AM: > We've added the following to your /opt/buildhome/.profile
3:53:34 AM: > If this isn't the profile of your current shell then please add the following to your correct profile:
3:53:34 AM: export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
3:53:34 AM: 
3:53:34 AM: > Successfully installed Yarn 1.13.0! Please open another terminal where the `yarn` command will now be available.
3:53:35 AM: Installing NPM modules using Yarn version 1.13.0
3:53:36 AM: yarn install v1.13.0
3:53:36 AM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
3:53:36 AM: [1/4] Resolving packages...
3:53:40 AM: [2/4] Fetching packages...
3:54:01 AM: info fsevents@1.2.9: The platform "linux" is incompatible with this module.
3:54:01 AM: info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
3:54:01 AM: [3/4] Linking dependencies...
3:54:01 AM: warning "gatsby-plugin-sass > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
3:54:09 AM: [4/4] Building fresh packages...
3:54:15 AM: success Saved lockfile.
3:54:15 AM: Done in 39.03s.
3:54:15 AM: NPM modules installed using Yarn
3:54:15 AM: Started restoring cached go cache
3:54:15 AM: Finished restoring cached go cache
3:54:15 AM: unset GOOS;
3:54:15 AM: unset GOARCH;
3:54:15 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
3:54:15 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
3:54:15 AM: go version >&2;
3:54:15 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
3:54:15 AM: go version go1.12 linux/amd64
3:54:15 AM: Installing missing commands
3:54:15 AM: Verify run directory
3:54:15 AM: Executing user command: gatsby build
3:54:17 AM: success open and validate gatsby-configs — 0.007
3:54:19 AM: error
3:54:19 AM: Your plugins must export known APIs from their gatsby-node.js.
3:54:19 AM: The following exports aren't APIs. Perhaps you made a typo or your plugin is outdated?
3:54:19 AM: See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby Node APIs
3:54:19 AM: - The plugin "gatsby-source-filesystem@2.1.5" is exporting a variable named "createSchemaCustomization" which isn't an API.
3:54:19 AM: Skipping functions preparation step: no functions directory set
3:54:19 AM: Caching artifacts
3:54:19 AM: Started saving node modules
3:54:19 AM: Finished saving node modules
3:54:19 AM: Started saving yarn cache
3:54:19 AM: Finished saving yarn cache
3:54:19 AM: Started saving pip cache
3:54:19 AM: Finished saving pip cache
3:54:19 AM: Started saving emacs cask dependencies
3:54:19 AM: Finished saving emacs cask dependencies
3:54:19 AM: Started saving maven dependencies
3:54:19 AM: Finished saving maven dependencies
3:54:19 AM: Started saving boot dependencies
3:54:19 AM: Finished saving boot dependencies
3:54:19 AM: Started saving go dependencies
3:54:19 AM: Finished saving go dependencies
3:54:21 AM: Error running command: Build script returned non-zero exit code: 1
3:54:21 AM: Failing build: Failed to build site
3:54:21 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
3:54:21 AM: Finished processing build request in 58.392713305s

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by stefanprobst** [comment]
Thanks for reporting this!

The `createSchemaCustomization` API is only available in Gatsby 2.12 and above. So we should bump the peer dependency [here](https://github.com/gatsbyjs/gatsby/blob/26550a3c87d442584297a44f6c54e3f22931d14f/packages/gatsby-source-filesystem/package.json#L38) to 2.12 (or use the `sourceNodes` API, and bump to 2.2). (Personally I'd prefer just moving the type definitions for `File` into Gatsby core.)

In the meantime updating your Gatsby version should fix this - simply run `npm i gatsby` or `yarn add gatsby`.

**Comment by stefanprobst** [comment]
Let's keep this open until we have a proper fix.

**Comment by RonanOD** [comment]
Getting this error for gatsby-source-filesystem@2.1.6

**Comment by stefanprobst** [comment]
@RonanOD Did you try updating your `gatsby` package?

**Comment by w0404884** [comment]
Hi @stefanprobst 
Thanks. I cloned anew and ran `sudo npm i -g gatsby-cli` and `npm build`. Still got the same error when I ran `npm run build`

**Comment by w0404884** [comment]
Did the same again with latest gatsby (2.7.20) and same problem.

**Comment by stefanprobst** [comment]
@w0404884 you need to update the `gatsby` package in your project (latest version is 2.13.40), not the `gatsby-cli` package.

**Comment by RonanOD** [comment]
Thanks @stefanprobst. That solved the build problem. However, now I am getting 
`Error: React-Hot-Loader: AppContainer should be patched`
when I try and run with `gatsby develop`. I've googled about and can't seem to track down what the issue is.

**Comment by w0404884** [comment]
Figured it out! `npm update` seems to have fixed everything. Thanks again @stefanprobst
