### ISSUE TITLE
[gatsby-theme-blog] use deepmerge instead of lodash.merge

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#15692]
It’s a lot smaller — 3.7kb vs. 0.664 kb (minified and gzipped)

https://github.com/gatsbyjs/gatsby/blob/4a10c54b2ba7866da541257eadbed6c7e206f2f5/themes/gatsby-starter-blog-theme/src/gatsby-theme-blog/gatsby-plugin-theme-ui/colors.js#L1

**Comment by dantehemerson** [comment]
I would like to help with this, I am doing it
