### ISSUE TITLE
Find linked file node issue

### ISSUE THREAD

**Issue by zce** [gatsbyjs/gatsby#15699]
## Description

<img width="1440" alt="屏幕快照 2019-07-14 21 53 19" src="https://user-images.githubusercontent.com/6166576/61184664-09643700-a683-11e9-88ef-28cff461749a.png">

### Steps to reproduce

create an image field by:

```js
createNodeField({ node, name: 'cover', value: node.frontmatter.cover })
```

In fact, `frontmatter.cover` and `fields.cover` are just aliases.

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - ~/.config/yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 77.0.3833.0
    Safari: 12.1.1
  npmPackages:
    gatsby: latest => 2.13.20 
    gatsby-image: latest => 2.2.6 
    gatsby-plugin-feed: latest => 2.3.4 
    gatsby-plugin-nprogress: latest => 2.1.2 
    gatsby-plugin-offline: latest => 2.2.4 
    gatsby-plugin-react-helmet: latest => 3.1.2 
    gatsby-plugin-sharp: latest => 2.2.7 
    gatsby-plugin-sitemap: latest => 2.2.3 
    gatsby-plugin-typography: latest => 2.3.2 
    gatsby-remark-autolink-headers: latest => 2.1.3 
    gatsby-remark-copy-linked-files: latest => 2.1.3 
    gatsby-remark-images: latest => 3.1.6 
    gatsby-remark-prismjs: latest => 3.3.3 
    gatsby-remark-responsive-iframe: latest => 2.2.4 
    gatsby-remark-smartypants: latest => 2.1.2 
    gatsby-source-filesystem: latest => 2.1.5 
    gatsby-transformer-remark: latest => 2.6.5 
    gatsby-transformer-sharp: latest => 2.2.3 
    gatsby-transformer-yaml: latest => 2.2.3

**Comment by zce** [comment]
<img width="1106" alt="屏幕快照 2019-07-14 22 07 41" src="https://user-images.githubusercontent.com/6166576/61184779-25b4a380-a684-11e9-8be1-f2beaf3304ad.png">

**Comment by zce** [comment]
After any graphql query, this becomes normal again

<img width="1439" alt="屏幕快照 2019-07-14 22 52 11" src="https://user-images.githubusercontent.com/6166576/61185317-6ca59780-a68a-11e9-9491-9444b4d0857d.png">

**Comment by zce** [comment]
source: https://codesandbox.io/s/github/zce/zce.me/tree/broken-fields-image

**Comment by zce** [comment]
I find this problem only when I query data by ID.

**Comment by zce** [comment]
sample source: https://github.com/zce/gatsby-example

youtube video for steps to reproduce: https://youtu.be/Pvvo3CP4xuA

**Comment by stefanprobst** [comment]
Could you provide a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) to investigate this? Thanks!
(your provided sample repo is missing `gatsby-transformer-sharp` and `gatsby-plugin-sharp`, and i could not reproduce the issue)

**Comment by zce** [comment]
@stefanprobst 

- https://github.com/zce/gatsby-example
- https://youtu.be/Pvvo3CP4xuA

**Comment by stefanprobst** [comment]
@zce ok thanks, sorry didnt check the video, will have a look!

**Comment by stefanprobst** [comment]
I can reproduce this:
in the provided repo, this query will fail in a clean project:
```graphql
{
  markdownRemark(id: { eq: $id }) {
    id
    fields {
      cover {
        id
      }
    }
  }
}
```
After restarting the dev server it works.

This seems to be an issue with node tracking, because on restart we repopulate the node tracking WeakMap, but we don't have an entry on first run.

**Comment by zce** [comment]
> I can reproduce this:
> in the provided repo, this query will fail in a clean project:
> 
> ```graphql
> {
>   markdownRemark(id: { eq: $id }) {
>     id
>     fields {
>       cover {
>         id
>       }
>     }
>   }
> }
> ```
> 
> After restarting the dev server it works.
> 
> This seems to be an issue with node tracking, because on restart we repopulate the node tracking WeakMap, but we don't have an entry on first run.

The most incomprehensible is why there is only this problem with data query by ID.

```graphql
{
  markdownRemark(frontmatter: {title: {eq: "Placeholder"}}) {
    fields {
      cover {
        id
      }
    }
  }
}
```

It's normal in other ways.

**Comment by stefanprobst** [comment]
@zce
Can you try #15720 (seems to fix the issue for me locally)

**Comment by zce** [comment]
@stefanprobst Thank you. I'll try.

**Comment by zce** [comment]
💯 In my opinion, this problem has been solved.

**Comment by stefanprobst** [comment]
Cool thanks for testing!
