### ISSUE TITLE
Support SVGs in Gatsby Image

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#15690]
## Summary

Support SVGs in `gatsby-image` so that lazy loading can be taken advantage of, and so the API is consistent.

### Motivation

There is currently no mechanism to lazy load SVGs using Gatsby. Certainly some of the features provided by `gatsby-image` make no sense in the case of SVGs: There is no need to generate multiple versions, because SVGs are resolution independent, however it might make sense to generate a Base64 version, especially in the case of complex svgs, and it certainly makes sense to lazy load svgs for the same reasons it makes sense to lazy-load other images. On a page using lots of SVGs, without lazy loading there is no priority in their load order, meaning images above the fold might load after images below it.

**Comment by sidharthachatterjee** [comment]
@Undistraction Supporting SVGs in `gatsby-image` seems redundant because much of the behaviour that it includes isn't relevant for SVGs like you rightly mentioned. 

Native lazy loading (which gatsby-image uses if available under the hood) is almost out (follow in https://github.com/whatwg/html/pull/3752) which should be useful to load SVGs lazily 

In the mean time, if only lazy loading is the goal, perhaps use `React.lazy`?

**Comment by Undistraction** [comment]
@sidharthachatterjee I've been thinking about this again. 

I see the main advantage here that a developer doesn't need to care about implementation details for the image type they have chosen. They should be able to select an image type, and Gatsby should do what is necessary to render that image in the most optimal way possible. 

Currently there is no unity in this regard, and the two routes (for using svgs vs raster formats) are completely different, requiring different queries and components. Switching from using an svg to using a jpeg, or vice-versa requires changes at multiple layers, but gatsby-image could handle this variance.

It still makes sense to lazy-load an svg, and with more complex svgs it might also make sense to render a low-res placeholder image. 

The link you supplied, while encouraging is still a long way from being implemented widely, and for this reason I think SVG support in gatsby-image is definitely desirable, so I'm going to reopen this issue.
