### ISSUE TITLE
Not able to create new gatsby file

### ISSUE THREAD

**Issue by adolfobarreto75** [gatsbyjs/gatsby#157]
Hi, I tried to create a new file and got the following:

C:\WINDOWS\system32>npm install -g gatsby
npm WARN optional dep failed, continuing fsevents@1.0.8
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> history@2.0.0 postinstall C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby\node_modules\react-router\node_modules\history
> node ./npm-scripts/postinstall.js

> react-router@2.0.0 postinstall C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby\node_modules\react-router
> node ./npm-scripts/postinstall.js

npm WARN optional dep failed, continuing fsevents@1.0.8
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> spawn-sync@1.0.15 postinstall C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby\node_modules\node-sass\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

\
> caniuse-api@1.4.1 postinstall C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby\node_modules\postcss-cssnext\node_modules\caniuse-api
> node generator.js

caniuse-api: Generation ok
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
-
> node-sass@3.4.2 install C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby\node_modules\node-sass\vendor\win32-x64-46\binding.node

> node-sass@3.4.2 postinstall C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby\node_modules\node-sass
> node scripts/build.js

` C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby\node_modules\node-sass\vendor\win32-x64-46\binding.node ` exists.
 testing binary.
Binary is fine; exiting.

> history@2.0.0 postinstall C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby\node_modules\history
> node ./npm-scripts/postinstall.js

C:\Users\Adolfo Barreto\AppData\Roaming\npm\gatsby -> C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby\bin\cli.js
gatsby@0.8.4 C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby
├── json-loader@0.5.4
├── raw-loader@0.5.1
├── slash@1.0.0
├── null-loader@0.1.1
├── coffee-loader@0.7.2
├── object-assign@4.0.1
├── react-transform-catch-errors@1.0.2
├── underscore@1.8.3
├── style-loader@0.13.0
├── toml-loader@1.0.0
├── sass-loader@3.1.2
├── negotiator@0.6.0
├── async@1.5.2
├── react-dom@0.14.7
├── html-frontmatter@1.5.1
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── toml@2.3.0
├── debug@2.2.0 (ms@0.7.1)
├── coffee-script@1.10.0
├── node-cjsx@1.0.0 (coffee-react-transform@3.3.0)
├── cjsx-loader@2.1.0 (coffee-react-transform@3.3.0)
├── less-loader@2.2.2
├── boom@2.10.1 (hoek@2.16.3)
├── babel-loader@5.4.0 (object-assign@3.0.0)
├── babel-plugin-react-transform@1.1.1 (path-parse@1.0.5)
├── webpack-hot-middleware@2.7.1 (querystring@0.2.0, strip-ansi@3.0.1)
├── fs-extra@0.26.5 (path-is-absolute@1.0.0, klaw@1.1.3, jsonfile@2.2.3, graceful-fs@4.1.3, rimraf@2.5.2)
├── glob@7.0.0 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
├── redbox-react@1.2.2 (error-stack-parser@1.3.3)
├── react-hot-loader@1.3.0 (react-hot-api@0.4.7, source-map@0.4.4)
├── parse-filepath@0.6.3 (map-cache@0.2.0, is-absolute@0.2.3)
├── webpack-require@0.0.16 (path-is-absolute@1.0.0, object-assign@3.0.0, memory-fs@0.2.0, source-map@0.4.4, invariant@2.2.0)
├── static-site-generator-webpack-plugin@2.0.1 (eval@0.1.1, bluebird@3.3.3)
├── hapi-webpack-plugin@1.3.0 (webpack-dev-middleware@1.5.1)
├── extract-text-webpack-plugin@1.0.1 (webpack-sources@0.1.1)
├── underscore.string@3.3.4 (util-deprecate@1.0.2, sprintf-js@1.0.3)
├── loggy@0.2.2 (growl@1.8.1, ansi-color@0.2.1, date-utils@1.2.18)
├── postcss-browser-reporter@0.4.0 (postcss@5.0.17)
├── postcss-loader@0.8.1 (postcss@5.0.17)
├── postcss-import@8.0.2 (postcss-value-parser@3.3.0, read-cache@1.0.0, resolve@1.1.7, postcss@5.0.17)
├── css-loader@0.23.1 (postcss-modules-scope@1.0.0, postcss-modules-extract-imports@1.0.0, postcss-modules-local-by-default@1.0.1, postcss-modules-values@1.1.1, css-selector-tokenizer@0.5.4, source-list-map@0.1.5, lodash.camelcase@3.0.1, postcss@5.0.17)
├── yaml-loader@0.1.0 (js-yaml@3.5.3)
├── front-matter@2.0.6 (js-yaml@3.5.3)
├── markdown-it@6.0.0 (linkify-it@1.2.0, mdurl@1.0.1, uc.micro@1.0.0, entities@1.1.1, argparse@1.0.6)
├── loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)
├── moment@2.11.2
├── typography@0.7.0 (shallow-copy@0.0.1, is-string@1.0.4, gray-percentage@1.1.2, decamelize@1.1.2, isobject@2.0.0, modularscale@1.0.2, compass-vertical-rhythm@1.2.0)
├── highlight.js@9.2.0
├── postcss-url@5.1.1 (path-is-absolute@1.0.0, mime@1.3.4, js-base64@2.1.9, minimatch@3.0.0, mkdirp@0.5.1, postcss@5.0.17, directory-encoder@0.7.2)
├── react-router@2.0.0 (warning@2.1.0, invariant@2.2.0, history@2.0.0)
├── node-libs-browser@0.5.3 (https-browserify@0.0.0, tty-browserify@0.0.0, path-browserify@0.0.0, constants-browserify@0.0.1, punycode@1.4.0, string_decoder@0.10.31, os-browserify@0.1.2, process@0.11.2, assert@1.3.0, domain-browser@1.1.7, querystring-es3@0.2.1, timers-browserify@1.4.2, stream-browserify@1.0.0, events@1.1.0, vm-browserify@0.0.4, console-browserify@1.1.0, util@0.10.3, url@0.10.3, readable-stream@1.1.13, http-browserify@1.7.0, buffer@3.6.0, browserify-zlib@0.1.4, crypto-browserify@3.2.8)
├── hapi@8.8.1 (topo@1.0.3, statehood@2.1.1, cryptiles@2.0.4, peekaboo@1.0.0, accept@1.0.0, ammo@1.0.0, catbox-memory@1.1.1, items@1.1.0, boom@2.7.2, shot@1.5.3, kilt@1.1.1, iron@2.1.2, wreck@6.0.0, call@2.0.1, qs@4.0.0, catbox@4.3.0, hoek@2.14.0, mimos@2.0.2, h2o2@4.0.1, inert@2.1.6, vision@2.0.1, heavy@3.0.0, subtext@1.1.1, joi@6.4.1)
├── webpack@1.12.14 (interpret@0.6.6, tapable@0.1.10, clone@1.0.2, esprima@2.7.2, supports-color@3.1.2, enhanced-resolve@0.9.1, mkdirp@0.5.1, optimist@0.6.1, memory-fs@0.3.0, webpack-core@0.6.8, uglify-js@2.6.2, watchpack@0.2.9)
├── webpack-configurator@0.3.1 (lodash@3.10.1)
├── react-transform-hmr@1.0.2 (global@4.3.0, react-proxy@1.1.2)
├── babel@5.8.35 (path-exists@1.0.0, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.2, convert-source-map@1.2.0, source-map@0.5.3, output-file-sync@1.1.1, glob@5.0.15, chokidar@1.4.2, lodash@3.10.1)
├── cssnano@3.5.2 (postcss-normalize-charset@1.1.0, postcss-reduce-transforms@1.0.3, postcss-discard-empty@2.0.1, postcss-minify-gradients@1.0.1, postcss-discard-duplicates@2.0.1, indexes-of@1.0.1, postcss-merge-rules@2.0.5, postcss-reduce-idents@2.3.0, postcss-convert-values@2.3.4, postcss-discard-comments@2.0.4, defined@1.0.0, postcss-value-parser@3.3.0, postcss-ordered-values@2.1.0, decamelize@1.1.2, postcss-filter-plugins@2.0.0, postcss-minify-font-values@1.0.3, postcss-zindex@2.0.1, postcss-minify-params@1.0.4, postcss-unique-selectors@2.0.2, postcss-discard-unused@2.2.1, postcss-merge-longhand@2.0.1, postcss-merge-idents@2.1.5, postcss-calc@5.2.0, postcss-normalize-url@3.0.7, postcss-minify-selectors@2.0.4, postcss-colormin@2.1.8, postcss@5.0.17, postcss-svgo@2.1.2, autoprefixer@6.3.3)
├── postcss-cssnext@2.4.0 (postcss-custom-media@5.0.1, postcss-font-variant@2.0.0, postcss-media-minmax@2.1.1, postcss-pseudoelements@3.0.0, postcss-nesting@2.3.0, postcss-selector-not@2.0.0, postcss-custom-selectors@3.0.0, postcss-selector-matches@2.0.1, postcss-color-rgba-fallback@2.2.0, postcss-custom-properties@5.0.0, pleeease-filters@2.0.0, postcss-calc@5.2.0, postcss-color-rebeccapurple@2.0.0, postcss-color-hwb@2.0.0, postcss-color-hex-alpha@2.0.0, postcss-initial@1.4.1, postcss-pseudo-class-any-link@1.0.0, postcss-color-gray@3.0.0, postcss-color-function@2.0.0, postcss@5.0.17, pixrem@3.0.0, autoprefixer@6.3.3, caniuse-api@1.4.1)
├── lodash@4.5.1
├── react-document-title@2.0.1 (react-side-effect@1.0.2)
├── babel-core@5.8.35 (try-resolve@1.0.1, babel-plugin-remove-console@1.0.1, babel-plugin-remove-debugger@1.0.1, babel-plugin-dead-code-elimination@1.0.2, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-jscript@1.0.4, babel-plugin-eval@1.0.1, babel-plugin-property-literals@1.0.1, babel-plugin-react-constant-elements@1.0.3, babel-plugin-react-display-name@1.0.3, babel-plugin-constant-folding@1.0.1, babel-plugin-undefined-to-void@1.1.6, shebang-regex@1.0.0, path-exists@1.0.0, babel-plugin-member-expression-literals@1.0.1, to-fast-properties@1.0.1, trim-right@1.0.1, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.2, babel-plugin-proto-to-assign@1.0.4, babel-plugin-runtime@1.0.7, globals@6.4.1, private@0.1.6, esutils@2.0.2, convert-source-map@1.2.0, js-tokens@1.0.1, home-or-tmp@1.0.0, babel-plugin-undeclared-variables-check@1.0.2, line-numbers@0.2.0, babylon@5.8.35, source-map@0.5.3, detect-indent@3.0.1, minimatch@2.0.10, is-integer@1.0.6, repeating@1.1.3, chalk@1.1.1, bluebird@2.10.2, output-file-sync@1.1.1, resolve@1.1.7, source-map-support@0.2.10, regexpu@1.3.0, json5@0.4.0, regenerator@0.8.40, lodash@3.10.1, core-js@1.2.6)
├── less@2.6.0 (mime@1.3.4, graceful-fs@3.0.8, image-size@0.3.5, promise@6.1.0, errno@0.1.4, source-map@0.4.4, mkdirp@0.5.1, request@2.69.0)
├── react@0.14.7 (envify@3.4.0, fbjs@0.6.1)
└── node-sass@3.4.2 (get-stdin@4.0.1, async-foreach@0.1.3, chalk@1.1.1, nan@2.2.0, mkdirp@0.5.1, glob@5.0.15, npmconf@2.1.2, gaze@0.5.2, meow@3.7.0, cross-spawn@2.1.5, sass-graph@2.1.1, request@2.69.0, node-gyp@3.3.0)

C:\WINDOWS\system32>cd c:/users/adolfo barreto/documents

c:\Users\Adolfo Barreto\Documents>gatsby new my-test-gatsby-site
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EPERM: operation not permitted, open 'C:\Users\Adolfo Barreto\.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at save (C:\Users\Adolfo Barreto\AppData\Roaming\npm\node_modules\gatsby\node_modules\babel-core\lib\api\register\cache.js:35:19)
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:134:18)
    at node.js:962:3

Thanks,
Adolfo

**Comment by KyleAMathews** [comment]
Hey, this is a permissions issue (search for EPERM here: https://nodejs.org/api/errors.html) not a Gatsby bug.

**Comment by adolfobarreto75** [comment]
Thank you!
