### ISSUE TITLE
Default gatsby develop to --open

### ISSUE THREAD

**Issue by karlhorky** [gatsbyjs/gatsby#15718]
First of all, thanks for Gatsby, if I haven't said this already! It's an amazing piece of tooling / ecosystem and a really nice experience for many use cases.

## Summary

Default the `--open` flag to `true` when using `gatsby develop`.

### Motivation

Helpful for those who are new to the command line, and paves the cowpaths for those who are more experienced (most workflows will include opening in browser, and if this is unwanted, the flag can be set to `false`).

**Comment by polishedwp** [comment]
That would be nice. I do love how CRA opens the browser by default on `yarn start`. Would love to see the same option by default in Gatsby.

**Comment by sidharthachatterjee** [comment]
This sounds like a good default to make the first time experience better for inexperienced folks! Thank you for suggesting this. 

We would love to accept a PR including this 💪 💜 

CC @shannonbux @KyleAMathews @marcysutton

**Comment by polishedwp** [comment]
A very simple fix would be to change the script in the `package.json`:
`develop: "gatsby develop -o"`

**Comment by karlhorky** [comment]
Cool, then should someone go ahead on this change? Or rather change the default in the develop script itself?

**Comment by wardpeet** [comment]
Thank you for opening this issue. With Gatsby, you might have to restart the gatsby a few time (changing config options, fetching new data from sources, etc.). If we would enable --open by default it will re-open a new tab each time.

We recently moved to "better-opn" (the same package as CRA is using) which re-uses the browser tab but this only works on mac osx. In a future release, we will have the ability to change config options without rebooting the process. When this feature gets released, we probably will make it a default.

I hope I’ve provided enough information to your question. If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

**Comment by karlhorky** [comment]
@wardpeet Ok, so just that I'm understanding correctly - once the version gets released with `better-opn`, then you'll make it a default? Or did you mean the config changing feature? If it's the config changing feature, not sure I'm understanding why this is something to wait for...

**Comment by hbrls** [comment]
How can I disable it with config? I'm using docz.
