### ISSUE TITLE
Lazy load for gatsby-remark-images

### ISSUE THREAD

**Issue by humphreybc** [gatsbyjs/gatsby#15716]
## Summary

Out of the box, Gatsby does a good job of lazy loading images below the fold through `gatsby-image`. However, `gatsby-remark-images` doesn't appear to do this, which results in “Defer offscreen images” complaints from Lighthouse when testing a Markdown-generated page.

It would be nice if `gatsby-remark-images` added lazy loading so that images below the fold are not loaded until the user scrolls down the page. Bonus points if [support for the new Chrome native lazy loading API](https://twitter.com/chatsidhartha/status/1129118956193640448) was extended to `gatsby-remark-images` too.

## Previous work

There's been an attempt to add lazy-loading to `gatsby-remark-images` in [this plugin](https://www.npmjs.com/package/gatsby-remark-lazy-load). However it doesn't seem to work very well, and requires an external dependency in `lazysizes`. It would be better if this functionality was built into `gatsby-remark-images` like it is with `gatsby-image`.

Another relevant issue: https://github.com/gatsbyjs/gatsby/issues/2288

## Motivation

Improve the performance for Markdown-generated pages.

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @humphreybc 

We'd love to accept a pull request porting the lazy load implementation over to `gatsby-remark-images`

Marking this as `help wanted` for the moment!

**Comment by humphreybc** [comment]
@sidharthachatterjee If you could drop a link to the relevant code in `gatsby-image`, I could take a look and see how difficult it would be to port to `gatsby-remark-images`. The Chrome stuff is just adding an attribute to the HTML tag, so that should be pretty easy.

**Comment by 0tho** [comment]
@humphreybc have a look at gatsby-image, it uses IntersectionObserver to 'defer image loading'.

[gatsby-image](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js#L97)
[mdn IO](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

**Comment by karlhorky** [comment]
not stale

**Comment by sidharthachatterjee** [comment]
gatsby-remark-images@3.1.10 supports native lazy loading thanks to @gabefromutah 🥇
