### ISSUE TITLE
gatsbyjs.org not loading in safari due to some odd errors...

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#15711]
gatsbyjs.org does not load in macOS Safari and these are the errors in the console:

<img width="1440" alt="Screen Shot 2019-07-14 at 8 27 34 PM" src="https://user-images.githubusercontent.com/7884263/61194371-d6677680-a675-11e9-9bf2-72771daf71e1.png">

Just thought I'd let y'all know XD

Cheers XD

**Comment by m-allanson** [comment]
Thanks @rchrdnsh - what versions of macOS and Safari are you using? Do you have any Safari extensions?

I'm using:

- MacOS 10.14.5 (18F203)
- Safari Version 12.1.1 (14607.2.6.1.1)

And the site loads ok here.

**Comment by rchrdnsh** [comment]
Same versions of macOS and Safari here as you.

and I only have a privacy blocker called better running:

<img width="772" alt="Screen Shot 2019-07-16 at 9 59 04 AM" src="https://user-images.githubusercontent.com/7884263/61313946-5a257e00-a7b0-11e9-92a7-f5b2f0e89b1d.png">

...I'll turn that off for a sec and see if it loads:

**Comment by rchrdnsh** [comment]
Turned off the 'Better' extension and still the same thing...dunno 🤷‍♂️

<img width="503" alt="Screen Shot 2019-07-16 at 10 01 34 AM" src="https://user-images.githubusercontent.com/7884263/61314107-b4264380-a7b0-11e9-9715-1a2142049897.png">
