### ISSUE TITLE
(node:18701) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead

### ISSUE THREAD

**Issue by ikey2244** [gatsbyjs/gatsby#1572]
Getting this error after running gatsby serve in my terminal. Maybe its's a node issue?

**Comment by nicholaswyoung** [comment]
What versions of Node and Gatsby display this error? I've seen it in the past, but less so recently, and I'd like to eliminate it.

**Comment by ikey2244** [comment]
node  v7.0

**Comment by ikey2244** [comment]
node v7.0.0
Gatsby 1.3.0

**Comment by nicholaswyoung** [comment]
Try upgrading to the latest Node v7 (7.10.1 as of this writing). Node v8 works as well, if you don't have a hard requirement on v7.

**Comment by KyleAMathews** [comment]
I'm pretty sure it's due to our old Hapi.js dependency in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/serve.js

Would love a PR updating this to use Express!
