### ISSUE TITLE
Error loading a result for the page query in "/404.html". Query was not run and Page not found /404.html

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#15724]
## Description

When using `gatsby develop` with a theme, the following error is printed in the terminal after a page is loaded in the browser:

```
Error loading a result for the page query in "/404.html". Query was not run and
Page not found /404.html
```

### Steps to reproduce

- `gatsby new my-blog gatsbyjs/gatsby-starter-blog-theme`
- `cd my-blog`
- `gatsby develop`
- browse to `http://localhost:8000`
- check the terminal to see this message:

```
Error loading a result for the page query in "/404.html". Query was not run and no cached result was
Page not found /404.html
```

- This message will be printed to the terminal every time the page is refreshed.

There's also a repro available at https://github.com/polishedwp/gatsby-starter-theme-eclectic courtesy of @polishedwp 

### Expected result

The _Error loading a result for the page query..._ message should not appear in the terminal.

### Actual result

The message appears.

### Environment

```

  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 3.5.3 - /Users/mike/.pyenv/shims/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.21 => 2.13.21 
    gatsby-theme-blog: ^1.0.0 => 1.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.7.7
    gatsby-dev-cli: 2.4.19
    gatsby: 2.8.8

```

**Comment by m-allanson** [comment]
Note that running `gatsby build && gatsby serve` will show the same error as `error Error: ENOENT: no such file or directory, stat '/Users/mike/d/gatsby/starters/hello-world/public/404.html'`

**Comment by polishedwp** [comment]
So, I installed each of the starters and the only starter that displays the 404 error in the terminal is the hello-world starter.

The 404 message appears in each of the default theme starters including the new workspace theme starter.

**Comment by sonapraneeth-a** [comment]
As per @jlengstorf , we need to have a 404.js in our site currently as 404 generation is not supported as of now.

**Comment by janosh** [comment]
I'm also getting this error (or a very similar error) on `gatsby build` independently of themes:

>  ERROR ENOENT: no such file or directory, open `'/<project-root>/public/page-data/404.html/page-data.json'`

Running `rm -r .cache` solves the problem until the next build.

**Comment by janosh** [comment]
Could this be related to #15615?

**Comment by guandjoy** [comment]
Though everything works as it should, I'm getting the same error when navigating pages I'm routing with `@reach/router` and `gatsby-plugin-create-client-paths`
My console:
```console
Error loading a result for the page query in "/authentication/navigate". Query was not run and no cached result was found.
Page not found /authentication/navigate
Error loading a result for the page query in "/authentication/login". Query was not run and no cached result was found.
Page not found /authentication/login
```
gatsby-config.js:
```js
...
{
  resolve: `gatsby-plugin-create-client-paths`,
  options: {
  prefixes: [`/confirm-email/*`, `/authentication/*`],
},
...
```

My `pages/authentication/index.js` component:
```jsx
...
const AuthenticationIndex = () => {
  return (
    <Layout>
      <div className="authentication-container">
        <Router>
          <Navigator path="authentication/navigate" />
          <AuthenticationContainer path="authentication" />
          <LoginFormContainer path="authentication/login" />
          <RegistrationFormContainer path="authentication/signup" />
          <PasswordResetFormContainer path="authentication/password-reset" />
          <PasswordResetConfirmFormContainer path="authentication/password-reset/confirm/:uid/:token" />
        </Router>
      </div>
    </Layout>
  )
}
...
```

**Comment by kogal** [comment]
Same issue with client-only paths ('/app/*') using gatsby-plugin-create-client-paths@2.1.3

**Comment by ssijak** [comment]
I also have this printed out with the same setup as @kogal Everything seems to work OK, but those printouts bother me

**Comment by wardpeet** [comment]
Successfully published:
- gatsby@2.13.46

**Comment by janosh** [comment]
For me the error persists. Running `gatsby build` still crashes with

>  ERROR #95313 
> 
> Building static HTML failed for path "/404.html"
> 
> See our docs page for more info on this error: https://gatsby.dev/debug-html
> 
> Error: ENOENT: no such file or directory, open './public/page-data/404.html/page-data.json'
>   
>   - render-page.js:547 Module../.cache/static-entry.js.__webpack_exports__.default

[As mentioned above](https://github.com/gatsbyjs/gatsby/issues/15724#issuecomment-513755203), if I delete the cache, `rm -r .cache`, it builds fine but only once.

**Comment by prodeniser** [comment]
Also having an issue. Only thing that has helped is by clearing the cache as @janosh mentioned

**Comment by yyyyaaa** [comment]
Any update on this? With the latest gatsby version I still have this issue, and it affects `gatsby develop` as well, which leads to hot loading not working

**Comment by JR-Carroll** [comment]
Not sure if anyone is still monitoring this thread, but I am occassionally getting this same (similar, but different) error. 

As others have said, stopping `gatsby develop` and then `rm -rf .cache` fixes, but about every 3rd or 4th time of running `gatsby develop` I get this error, and if I don't catch it, it breaks production build pipelines... 

Did anyone ever find a (more perm) solution for this situation?

**Comment by KishanMaurya** [comment]
Error: ENOENT: no such file or directory, stat 'D:\protfolio\kishan-portfolio\public\404.html'


Please help me, how  can I solve this issue

**Comment by franva** [comment]
hit the same issue here....... anyone has a solution?

**Comment by shanghaikid** [comment]
hit the same issue here....... anyone has a solution?

**Comment by soimyy** [comment]
hit the same issue here....... anyone has a solution?

**Comment by marcus13371337** [comment]
I have the same issue initially when the `serve`-command is finished. We have approx ~22k pages and it seems as the develop command reports that it's finished before all the queries are ready to be consumed by the frontend.

I've noticed that the `/dev-404-page` fetches ALL pages, which makes the result of that query very long. Is it needed to preload all pages in order to show the dev-404 page (with all pages listed). I mean we have a dev-server running which could use server-side pagination and search.

**Comment by barbalex** [comment]
I am getting this now too - never noticed before. Just updated to `"gatsby": "2.28.2"`

**Comment by jaymarkjairi** [comment]
my problem is not solve in running `gatsby clean`. I am using `"gatsby": "^4.11.2",`

**Comment by dpw1** [comment]
Any updates on this? `gatsby clean` doesn't solve my issue, nor any of the aforementioned suggestions. I'm using ` "gatsby": "^4.5.4"`

Any suggestions are greatly appreciated.

**Comment by j127** [comment]
If anyone runs into this problem, make sure the Gatbsy server isn't running in a different terminal window. That's what the problem was in my case (March 2023).
