### ISSUE TITLE
Old fixed errors from nested files reappear

### ISSUE THREAD

**Issue by karlhorky** [gatsbyjs/gatsby#15722]
## Description

When errors occur within files **within directories**, the errors are reported on the command line and in the browser (this is good!). However, when the error has been resolved by removing the offending files, the errors do not go away.

### Steps to reproduce

1. Start a new site using `gatsby new`
2. Start the development server and navigate to a working page such as the root in the browser
3. Add a folder under pages with a JavaScript with an error in it (for instance, `import blah from 'blah'` - an import of a non-existent package)
4. The error appears in the browser and the command line
5. Remove the folder again
6. Refresh the page in the browser a bunch of times - the error appears intermittently until `gatsby develop`

#### Video

![Kapture 2019-07-15 at 12 09 49](https://user-images.githubusercontent.com/1935696/61209279-96e26e00-a6f9-11e9-97e9-cf959613b51a.gif)

### Expected result

At step 6. you should never see the old invalid error anymore.

### Actual result

You do see the error.

### Motivation

To prevent confusion about false negative error reporting.

### Related

Maybe related to #14395 or #11456

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.1.0 - /var/folders/v0/ssn2yzps0wq9j6ngd3128_440000gn/T/yarn--1563185093192-0.21022637200966066/node
    Yarn: 1.16.0 - /var/folders/v0/ssn2yzps0wq9j6ngd3128_440000gn/T/yarn--1563185093192-0.21022637200966066/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.21 => 2.13.21 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-sharp: ^2.2.7 => 2.2.7 
    gatsby-source-filesystem: ^2.1.5 => 2.1.5 
    gatsby-transformer-sharp: ^2.2.3 => 2.2.3

**Comment by sidharthachatterjee** [comment]
Thank you for reporting this @karlhorky and for the detailed steps to reproduce!

I'm going to take a look at this tomorrow and respond here again with further details

**Comment by karlhorky** [comment]
not stale

**Comment by LekoArts** [comment]
I've tested this locally (new hello-world, create a page-2.js file, put something valid in it, bad import, delete page-2.js file) and the page reloads and the error in the browser isn't shown. As such I'll close this as solved.
