### ISSUE TITLE
Ghost and Disqus in a Gatsby website

### ISSUE THREAD

**Issue by Mushu62** [gatsbyjs/gatsby#15729]
## Description

Hi !
I'm trying to play around with the CMS Ghost coupled with a Gatsby website. My goal was to implement a Disqus comment section at the end of each blog post but when trying to publish with Netlify, I get the following result below, any help?

### Actual result

12:28:31 PM: Build ready to start
12:28:33 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
12:28:33 PM: build-image tag: v3.3.2
12:28:33 PM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
12:28:33 PM: Fetching cached dependencies
12:28:33 PM: Starting to download cache of 255.0KB
12:28:33 PM: Finished downloading cache in 85.621169ms
12:28:33 PM: Starting to extract cache
12:28:33 PM: Failed to fetch cache, continuing with build
12:28:33 PM: Starting to prepare the repo for build
12:28:34 PM: No cached dependencies found. Cloning fresh repo
12:28:34 PM: git clone https://github.com/Mushu62/Ghost-Blog
12:28:34 PM: Preparing Git Reference refs/heads/master
12:28:35 PM: Found netlify.toml. Overriding site configuration
12:28:35 PM: Starting build script
12:28:35 PM: Installing dependencies
12:28:36 PM: Downloading and installing node v10.16.0...
12:28:36 PM: Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz...
12:28:37 PM: 
#############
12:28:37 PM:                     18.4%
12:28:37 PM: 
#################################################
12:28:37 PM: ####################### 100.0%
12:28:37 PM: Computing checksum with sha256sum
12:28:37 PM: Checksums matched!
12:28:40 PM: Now using node v10.16.0 (npm v6.9.0)
12:28:40 PM: Attempting ruby version 2.6.2, read from environment
12:28:42 PM: Using ruby version 2.6.2
12:28:42 PM: Using PHP version 5.6
12:28:42 PM: Started restoring cached node modules
12:28:42 PM: Finished restoring cached node modules
12:28:42 PM: Installing NPM modules using NPM version 6.9.0
12:29:14 PM: > dtrace-provider@0.8.7 install /opt/build/repo/node_modules/dtrace-provider
12:29:14 PM: > node-gyp rebuild || node suppress-error.js
12:29:15 PM: make: Entering directory '/opt/build/repo/node_modules/dtrace-provider/build'
12:29:15 PM:   TOUCH Release/obj.target/DTraceProviderStub.stamp
12:29:15 PM: make: Leaving directory '/opt/build/repo/node_modules/dtrace-provider/build'
12:29:15 PM: > sharp@0.22.1 install /opt/build/repo/node_modules/sharp
12:29:15 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
12:29:16 PM: info
12:29:16 PM: sharp
12:29:16 PM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
12:29:18 PM: > core-js@2.6.9 postinstall /opt/build/repo/node_modules/core-js
12:29:18 PM: > node scripts/postinstall || echo "ignore"
12:29:18 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
12:29:18 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
12:29:18 PM: > https://opencollective.com/core-js 
12:29:18 PM: > https://www.patreon.com/zloirock 
12:29:18 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
12:29:18 PM: > core-js-pure@3.1.4 postinstall /opt/build/repo/node_modules/core-js-pure
12:29:18 PM: > node scripts/postinstall || echo "ignore"
12:29:18 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
12:29:18 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
12:29:18 PM: > https://opencollective.com/core-js 
12:29:18 PM: > https://www.patreon.com/zloirock 
12:29:18 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
12:29:18 PM: > gatsby-telemetry@1.1.3 postinstall /opt/build/repo/node_modules/gatsby-telemetry
12:29:18 PM: > node src/postinstall.js
12:29:19 PM: > cwebp-bin@5.1.0 postinstall /opt/build/repo/node_modules/cwebp-bin
12:29:19 PM: > node lib/install.js
12:29:19 PM:   ✔ cwebp pre-build test passed successfully
12:29:19 PM: > mozjpeg@6.0.1 postinstall /opt/build/repo/node_modules/mozjpeg
12:29:19 PM: > node lib/install.js
12:29:19 PM:   ✔ mozjpeg pre-build test passed successfully
12:29:19 PM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
12:29:19 PM: > node lib/install.js
12:29:20 PM:   ✔ pngquant pre-build test passed successfully
12:29:22 PM: npm WARN
12:29:22 PM:  optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
12:29:22 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
12:29:22 PM: added 1921 packages from 1118 contributors and audited 30501 packages in 38.947s
12:29:22 PM: found 0 vulnerabilities
12:29:22 PM: NPM modules installed
12:29:22 PM: Started restoring cached go cache
12:29:22 PM: Finished restoring cached go cache
12:29:22 PM: unset GOOS;
12:29:22 PM: unset GOARCH;
12:29:22 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
12:29:22 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
12:29:22 PM: go version >&2;
12:29:22 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
12:29:22 PM: go version go1.12 linux/amd64
12:29:22 PM: Installing missing commands
12:29:22 PM: Verify run directory
12:29:22 PM: Executing user command: gatsby build
12:29:25 PM: success open and validate gatsby-configs — 0.126
12:29:25 PM: success load plugins — 0.068
12:29:25 PM: success onPreInit — 0.007
12:29:25 PM: success delete html and css files from previous builds — 0.004
12:29:25 PM: success initialize cache — 0.007
12:29:25 PM: success copy gatsby files — 0.021
12:29:25 PM: success onPreBootstrap — 0.003
12:29:25 PM: success source and transform nodes — 0.034
12:29:25 PM: success building schema — 0.127
12:29:25 PM: error #85901 GRAPHQL
12:29:25 PM: There was an error in your GraphQL query:
12:29:25 PM: Cannot query field "allGhostPost" on type "Query".
12:29:25 PM: File: gatsby-node.js:15:25
12:29:25 PM: See our docs page for more info on this error: https://gatsby.dev/issue-how-to
12:29:25 PM: Skipping functions preparation step: no functions directory set
12:29:25 PM: Caching artifacts
12:29:25 PM: Started saving node modules
12:29:25 PM: Finished saving node modules
12:29:25 PM: Started saving pip cache
12:29:28 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
12:29:25 PM: Finished saving pip cache
12:29:25 PM: Started saving emacs cask dependencies
12:29:25 PM: Finished saving emacs cask dependencies
12:29:25 PM: Started saving maven dependencies
12:29:25 PM: Finished saving maven dependencies
12:29:25 PM: Started saving boot dependencies
12:29:25 PM: Finished saving boot dependencies
12:29:25 PM: Started saving go dependencies
12:29:25 PM: Finished saving go dependencies
12:29:28 PM: Error running command: Build script returned non-zero exit code: 1
12:29:28 PM: Failing build: Failed to build site
12:29:28 PM: Finished processing build request in 54.76555886s
### Environment

System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    gatsby: 2.13.3 => 2.13.3
    gatsby-awesome-pagination: 0.3.4 => 0.3.4
    gatsby-image: 2.2.4 => 2.2.4
    gatsby-plugin-advanced-sitemap: 1.2.0 => 1.2.0
    gatsby-plugin-disqus: ^1.1.2 => 1.1.2
    gatsby-plugin-feed: 2.3.2 => 2.3.2
    gatsby-plugin-force-trailing-slashes: 1.0.4 => 1.0.4
    gatsby-plugin-manifest: 2.2.1 => 2.2.1
    gatsby-plugin-offline: 2.2.0 => 2.2.0
    gatsby-plugin-react-helmet: 3.1.0 => 3.1.0
    gatsby-plugin-sharp: 2.2.2 => 2.2.2
    gatsby-source-filesystem: 2.1.2 => 2.1.2
    gatsby-source-ghost: ^3.4.3 => 3.4.3
    gatsby-transformer-sharp: 2.2.1 => 2.2.1
  npmGlobalPackages:
    gatsby-cli: 2.7.8

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @Mushu62 

```
12:29:25 PM: There was an error in your GraphQL query:
12:29:25 PM: Cannot query field "allGhostPost" on type "Query".
12:29:25 PM: File: gatsby-node.js:15:25
```

Based on this, it appears that the query you're trying to make including `allGhostPost` is failing. Is your Ghost Public API setup correctly in the plugin config? 

Do you have any posts at all currently? If there are no posts, schema inference will fail and Gatsby won't know about the `allGhostPost` field 

If none of the above helps, can you perhaps link to a minimal reproduction of this issue? I would also recommend opening an issue at https://github.com/TryGhost/gatsby-source-ghost
