### ISSUE TITLE
Check app bundle size in the hello world starter

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#15736]
## Summary

Add a check for the app bundle size in gatsby-starter-hello-world. Fail any PR that increases the size beyond 60Kb.

### Basic example

Use `size-limit` or `bundlesize` packages to add a check for the `app-*.js` file created by building `gatsby-starter-hello-world`

### Motivation

The size of this file has crept up a little since the launch of Gatsby v2. We should be working to make it smaller, adding checks for the current size is the first step here.

**Comment by KyleAMathews** [comment]
BTW, what I've done in the past is measure _all_ critical JS needed to make a Gatsby page — so this includes not just the app.js file but also the page component, etc. We could parse the index.html file to get the referenced JS files and then count their size.
