### ISSUE TITLE
Add large createPages CI check

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#15737]
## Summary

Add a test that runs the createPages benchmark with a high number of pages (75000?). Run a few times on latest Gatsby, then on the PR changes. Fail if PR changes are ??% slower. 15% as a starting point?

### Motivation

Prevent regressions like this https://github.com/gatsbyjs/gatsby/pull/15503

**Comment by pvdz** [comment]
Would not add this to the CI since it'll be super slow and yield no information. Would decrease devx for CI.

We're actively working on getting a benchmark up and running and that will probably supersede the use case of this issue.

As such I'm going to close it.
