### ISSUE TITLE
Add test coverage threshold for Gatsby package

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#15732]
## Summary

Add a code coverage report for the main Gatsby package. Fail CI on pull requests that drop coverage below the threshold. For now the threshold should be set to whatever the current coverage level is.

Note there's some existing coverage config in `jest.config.js` but I don't think it's used anywhere right now. (confirm this?)

 In particular ensure that coverage is generated for `packages/gatsby/src` and `packages/gatsby/cache-dir`.

### Basic example

Enable code coverage reports in Jest, and fail CI if the coverage for the Gatsby package drops below a certain level.

We can add additional coverage reports and raise the thresholds over time.

### Motivation

Some parts of Gatsby are well tested, others have less tests. For the Gatsby package we want to ensure that coverage goes up over time. A first step towards this is to prevent new features from merging without test coverage. Eventually we can expand coverage reports out to other parts of Gatsby.

**Comment by m-allanson** [comment]
Related to #15272

**Comment by copperwall** [comment]
I'm up to work on this!

**Comment by Qovaros985** [comment]
@m-allanson @copperwall  Could I work on this issue?

**Comment by wardpeet** [comment]
I'll be closing this, we have coverage setup but without the fail when we regress. We don't have proper ways right now to enforce this. We'll revisit this in the future!
