### ISSUE TITLE
[gatsby-source-wordpress] Include user roles for allWordpressWpUsers

### ISSUE THREAD

**Issue by kmcaloon** [gatsbyjs/gatsby#15741]
Although there are a ton of filters and fields available when querying WordPress users, to my knowledge it looks like a pretty important one is missing: user roles. As is, the only workaround I can see is tinker with things by setting up a field for roles and then to programmatically update via a hook when user is edited. I think roles would be a helpful field to have available out of the box though.

**Comment by sidharthachatterjee** [comment]
CC @jasonbahl
