### ISSUE TITLE
Gatsby error when updating graphql nodes using http://localhost:8000/__ refresh

### ISSUE THREAD

**Issue by jlfalcon3589** [gatsbyjs/gatsby#15740]
Useful Links:
  - Documentation: https://www.gatsbyjs.org/docs/environment-variables/#reserved-environment-variables

## Description

Hello guys, I've been looking for documentation in gatsby that I could provide update my nodes in graphql but I have not found a solution. Looking for documentation I have seen that using the environment variable ENABLE_GATSBY_REFRESH_ENDPOINT I can reload my graphql nodes without having to make a new deploy to the project again, simply doing a POST to my project. 

`curl -X POST http://localhost:8000/__refresh`

I am using the integration with [strapi](https://www.npmjs.com/package/gatsby-source-strapi) and when I insert new content in my API, the gatsby updates me the new nodes, not being so with the content that I delete in the api of strapi. 

My question is if there is any way to remove all the graphql nodes for when I update, I only believe the nodes that really exist in my API and I can do all this without stopping the project.

This is really a gatsby bug or is that gatsby does not allow it.

Greetings and thanks in advance

### Environment

System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.8.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
  npmPackages:
    gatsby: ^2.13.21 => 2.8.2
    gatsby-image: ^2.1.2 => 2.1.2
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-source-filesystem: ^2.0.38 => 2.0.38
    gatsby-source-graphql: ^2.0.18 => 2.0.18
    gatsby-source-strapi: 0.0.9 => 0.0.9
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.7.8

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @jlfalcon3589 

> My question is if there is any way to remove all the graphql nodes for when I update, I only believe the nodes that really exist in my API and I can do all this without stopping the project.

If I understand your question correctly, some nodes are not getting deleted in Gatsby when they are deleted from your API? Is that what you mean?

In this case, I would open an issue in https://github.com/strapi/gatsby-source-strapi

**Comment by jlfalcon3589** [comment]
yes, exactly that, once I delete the content of the api (strapi) in the api when I make a query if I see that it is deleted, but not the nodes.  thanks for answering, anyway I will raise an issue in gatsby-source-strapi
