### ISSUE TITLE
WrapRootElement in theme dependencies

### ISSUE THREAD

**Issue by sonapraneeth-a** [gatsbyjs/gatsby#15744]
## Summary

Let us suppose, we have a ```theme-a``` which contains a definition for ```wrapRootElement``` in ```gatsby-browser.js``` and ```gatsby-ssr.js```. We have created another ```theme-b``` which has ```theme-a``` as its regular dependency and a demo site ```demo``` which has ```theme-b``` as a dependency. Now will the behaviour defined in ```wrapRootElement``` of ```theme-a``` be available in ```demo``` or should ```theme-b``` have its own implementation of ```wrapRootElement```?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
As far as I know, the behaviour for `wrapRootElement` in `theme-a` should be available in `demo`

CC @ChristopherBiscardi

**Comment by ChristopherBiscardi** [comment]
Yes the `wrapRootElement` in `theme-a` would be available to `demo`. 

Organizationally, you would need to add `theme-a` to `theme-b`'s plugins list for the `wrapRootElement` (or any other functionality) in `theme-a` to be applied in `demo`. This is generally referred to as "child themes" where `theme-a` is the "parent" and `theme-b` is the "child".
