### ISSUE TITLE
[gatsby-plugin-sharp] Incorrect require path to cpu detection module.

### ISSUE THREAD

**Issue by smurrayatwork** [gatsbyjs/gatsby#15748]
## Description
Within process-file.js, there's a `require` statement that's pointing to maybe an old path to where cpu-core-count.js should be. It should be changed to `gatsby/dist/utils/worker/cpu-core-count`. By default, sharp uses the number of CPUs it detects, but this logic could be different than what Gatsby defines as the number of CPUs in cpu-core-count.js.

### Steps to reproduce
This doesn't really have a reproducible step, as it's just code that isn't being used due to a bad path with no caught error logged.

### Expected result
Either the error that happens due to the path being bad is caught and reported to screen, or the path is updated and cpu-core-count.js is used, allowing `sharp.concurrency` to be set to the value of cpuCoreCount from the cpu-core-count.js file.
`sharp.concurrency` should then return the value from the cpu-core-count.js file once it's been set the first time.

### Actual result
`sharp.concurrency` returns the number of CPUs it detected after being failing to be set by cpu-core-count.js.

### Environment
*NOTE* While the packages don't list gatsby's sharp plugins, it's only because I removed those and added them back in as local plugins so I could experiment/test things out on them, which is how I discovered this bug.

  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.10.0 => 2.13.17 
    gatsby-image: ^2.2.1 => 2.2.6 
    gatsby-plugin-feed: ^2.3.0 => 2.3.4 
    gatsby-plugin-manifest: ^2.2.0 => 2.2.3 
    gatsby-plugin-netlify: ^2.1.0 => 2.1.2 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-offline: ^2.2.0 => 2.2.3 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.2 
    gatsby-plugin-sass: ^2.1.0 => 2.1.3 
    gatsby-source-drupal: ^3.2.5 => 3.2.6 
    gatsby-source-filesystem: ^2.1.0 => 2.1.5 
    gatsby-transformer-json: ^2.2.0 => 2.2.2

**Comment by sidharthachatterjee** [comment]
Great catch @smurrayatwork 

Want to open a PR fixing this with the new path?

**Comment by smurrayatwork** [comment]
@sidharthachatterjee What version of node should I be using for that PR?
