### ISSUE TITLE
Page errors only when hitting back button

### ISSUE THREAD

**Issue by bbaker6225** [gatsbyjs/gatsby#15751]
## Description
We're having an issue on our production site where users will see errors on pages only when returning to them after hitting the back button

### Steps to reproduce

1. Navigate to this prof cert page https://www.edx.org/professional-certificate/harvardx-computer-science-and-mobile-apps
2. Click on the accordion for "CS50's Introduction to Computer Science"
3. Click the view the course link
4. Hit the back button in your browser, and the page should fail to load and give an error in the console

### Expected result
When hitting the back button, you should be returned to the page you were previously on without any errors (or the errors that were there the first time)

### Actual result

We see new errors that seem like they should be build time errors when hitting the back button

### Environment

```
System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (2) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: ~2.12.1 => 2.13.12 
    gatsby-cli: ^2.4.15 => 2.5.12 
    gatsby-image: ^2.0.33 => 2.0.41 
    gatsby-link: ^2.0.16 => 2.1.1 
    gatsby-node-helpers: ^0.3.0 => 0.3.0 
    gatsby-plugin-intl: 0.2.6 => 0.2.6 
    gatsby-plugin-netlify: ^2.0.12 => 2.0.16 
    gatsby-plugin-netlify-cms: ^3.0.14 => 3.0.18 
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-axe: ^0.2.2 => 0.2.2 
    gatsby-plugin-react-helmet: ^3.0.9 => 3.0.12 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-segment-js: ^3.0.1 => 3.0.1 
    gatsby-plugin-sharp: ^2.0.28 => 2.0.36 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.0 => 1.1.0 
    gatsby-source-filesystem: ^2.0.25 => 2.0.33 
    gatsby-transformer-json: ^2.1.10 => 2.1.11 
    gatsby-transformer-remark: ^2.3.3 => 2.3.12 
  npmGlobalPackages:
    gatsby: 2.13.10
```

**Comment by sidharthachatterjee** [comment]
I can reproduce this on the url you posted. It appears that this is being thrown:
```
// Fail the build if the entire program is not in prospectus
    if (updatedCourses.some(course => course === undefined)) {
      const foundCourseTitles = updatedCourses.filter(course => course !== undefined)
        .map(course => `[${course.node.title}]`);
      throw Error(`Program [${program.title}] with uuid [${program.uuid}] does not have all of its
        courses in prospectus. The courses that were found in prospectus are [${foundCourseTitles}]`);
    }
```

I'm not sure that this is a Gatsby issue?

**Comment by bbaker6225** [comment]
That error is being thrown, but it should be thrown anytime you actually visit the page. Also, it should fail the build as well since it throws an error during create page

**Comment by bbaker6225** [comment]
The issue is resolved if we change those links to not use `Link` from `Gatsby`, so it seems like there might be an issue there?

**Comment by bbaker6225** [comment]
```jsx
                  <Link to={relatedTopic.topic_url} >
                      Link
                  </Link>
```
if I change my links to straight up use `Link` from `Gatsby`, I still get the issue, so it seems like this is a bug with `gatsby-link` @sidharthachatterjee
