### ISSUE TITLE
gatsby theme showing blank pages

### ISSUE THREAD

**Issue by molebox** [gatsbyjs/gatsby#15759]
## Description

I have a clean gatsby theme setup which i have used before while themes were experimental. This is not rendering anything, as in the page is blank.

### Steps to reproduce

clone https://github.com/molebox/gatsby-theme-tattoo and run yarn && yarn workspace demo dev

### Expected result

It should at least render something..... but i see nothing

### Actual result

Nothing happens, the page is blank

### Environment

System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: 42.17134.1.0

**Comment by johno** [comment]
Hey @molebox I think it might have something to do with the capitalized component name in `src/pages`. I was able to get it working with: `mv gatsby-theme-tattoo/src/pages/Index.tsx gatsby-theme-tattoo/src/pages/index.tsx`.

![image](https://user-images.githubusercontent.com/1424573/61246062-3c520d80-a70b-11e9-89f7-4cc3d0f1f833.png)

Let me know if that works or not, thanks!

**Comment by molebox** [comment]
> Hey @molebox I think it might have something to do with the capitalized component name in `src/pages`. I was able to get it working with: `mv gatsby-theme-tattoo/src/pages/Index.tsx gatsby-theme-tattoo/src/pages/index.tsx`.
> 
> ![image](https://user-images.githubusercontent.com/1424573/61246062-3c520d80-a70b-11e9-89f7-4cc3d0f1f833.png)
> 
> Let me know if that works or not, thanks!

Wow thats super embarrassing and annoying!! It now works! Thank you for taking the time to look into it! May i ask, do you know why that seems to be a convention? Do all pages have to be lower case?

**Comment by johno** [comment]
No worries!

Yeah, it's a convention since the casing of the filename maps directly to the rendered file. So `/Index/index.html` is isn't rendered at the `/` path, only `/Index/`.

**Comment by molebox** [comment]
Ok great, now i know! Thanks again! :)
