### ISSUE TITLE
gatsby-plugin-sitemap does not throw error if siteUrl is not filled

### ISSUE THREAD

**Issue by lnikell** [gatsbyjs/gatsby#15754]
Using the sitemap gatsby plugin I mentioned that there is no validation of siteUrl and if you don't fill it you will get an error on the building HTML step, but without any clear message that could reference you to this issue.

https://www.gatsbyjs.org/docs/creating-a-sitemap/

In the documentation also that section with gatsby-config with siteMetadata more looks like typical description of the plugin when siteMetadata inserted just to get user an understanding how the default gatsby-config looks like.

Proposal:
- Add in the documentation information about "siteUrl" key
- Add validation for that key and throw proper error message when it is empty

**Comment by sidharthachatterjee** [comment]
Sounds good to me! Want to open a PR adding these in?

**Comment by sagarnasit** [comment]
@sidharthachatterjee I would like to contribute on Gatsby and this good first issue looks perfect for me. Can you help me to move forward on this?

**Comment by afenton90** [comment]
If this needs assigning I don't mind picking this one up.

**Comment by Aswinpookkatt** [comment]
Hey can I work on this?
