### ISSUE TITLE
Issue with page titles and SSR

### ISSUE THREAD

**Issue by jonbellah** [gatsbyjs/gatsby#1575]
Apologies in advance if this question is covered somewhere in the docs, but I didn't quite see what I was looking for when digging through them or the examples/starters.

**Gatsby version**: 1.3.0
**Node version**: 7.7.4
**OS**: macOS 10.12.5
**Repo**: https://github.com/jonbellah/jonbellah.com

**The issue**
When loading my Gatsby site with JS disabled, everything works great, except it appears to be duplicating my page title and the `Gatsby.js` title is superseding my own.

![duplicate-titles](https://user-images.githubusercontent.com/2601219/28418119-d91a099a-6d17-11e7-8945-527b14b5b761.png)

I see this is being set in `static-html.js` by way of `static-entry.js`, but when attempting to`console.log` in the `try...catch`, my log gets removed at build time so I never actually see what's happening.

Looking through the examples, I see that the page title is able to be set server-side... I'm just not quite sure what I'm missing.

Appreciate the help! Really loving Gatsby so far :)

**Comment by jonbellah** [comment]
I do, it's at `src/html.js` and includes `{this.props.headComponents}`, which are rendered correctly by the client.

**Comment by KyleAMathews** [comment]
There's probably a `<title>Gatsby.js</title>` there you can remove. Removed it from the default html.js earlier https://github.com/gatsbyjs/gatsby/pull/1578

**Comment by jonbellah** [comment]
Render method looks like this in my `src/html.js` file.
```
render() {
	return (
		<html lang="en">
			<head>
				<meta charSet="utf-8" />
				<meta httpEquiv="X-UA-Compatible" content="IE=edge" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				{this.props.headComponents}
			</head>
			<body>
				<div id="___gatsby" dangerouslySetInnerHTML={{ __html: this.props.body }} />
				{this.props.postBodyComponents}
			</body>
		</html>
	)
}
```

**Comment by jonbellah** [comment]
But it would help if I imported `{ Component }` from React before extending it. 🥇

**Comment by KyleAMathews** [comment]
Looks like this error striked again https://github.com/gatsbyjs/gatsby/issues/1475

**Comment by jonbellah** [comment]
Got it... Appreciate the help!
