### ISSUE TITLE
docs: Gatsby-link package not showing up in plugins and old docs

### ISSUE THREAD

**Issue by endormi** [gatsbyjs/gatsby#15760]
## Description

I've been trying to find the gatsby-link package inside the plugin list, not finding it (other packages are there). This also seems to be old [docs](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-link/README.md), because it's not showing anywhere probably due to gatsby-link not showing in the plugins list. 

### Expected result

Gatsby-link not found in plugins and found README.md

### Actual result

Can't find neither of them.

If this ends up needing to be fixed, I'm more than happy to work on this. 
If this is how it is supposed to be, feel free to close this.

**Comment by sidharthachatterjee** [comment]
I'll let the @gatsbyjs/docs team weigh in on this since I'm not sure

In the mean time, check out the documentation at https://www.gatsbyjs.org/docs/gatsby-link/

**Comment by gillkyle** [comment]
Hey @endormi, thanks for bringing this up! True it's not showing up in the plugins list, not sure that's intentional or not. Since it is natively a part of Gatsby (not technically a plugin) it seems like it's probably okay the way it is IMO.

**Comment by wardpeet** [comment]
@gillkyle you're correct! I don't think it belongs in the gatsby-plugin listing either. I do get that it might be a bit confusing.

**Comment by endormi** [comment]
If it is needed, I can add it manually or else IMO it should be removed from the packages folder, because it's not connected anywhere.

**Comment by endormi** [comment]
Any updates @wardpeet, @gillkyle ?

**Comment by gillkyle** [comment]
@endormi the `gatsby-image` folder inside of packages is what gets bundled up and released with [the monorepo setup for Gatsby](https://github.com/gatsbyjs/gatsby#a-note-on-how-this-repository-is-organized).

Also, it seems like gatsby-image is showing up in the plugin list as of now, this might have been an issue with algolia and npm-search that we're relying on to get those readmes. That issue is being tracked in other places too: https://github.com/algolia/npm-search/issues/365

`gatsby-link` is now exported from `gatsby` by default, because it doesn't need to be installed it doesn't need to be included in the plugin list.

Because I'm seeing the image package showing up now I think it's fine to close this for now, thanks for brining it up!

**Comment by endormi** [comment]
Okay, good. What about the `gatsby-link.md`. I personally don't think it's not needed.

**Comment by gillkyle** [comment]
@endormi have you been able to find the doc on [linking between pages](https://www.gatsbyjs.org/docs/linking-between-pages/)? Or possibly the [recipe on linking](https://www.gatsbyjs.org/docs/recipes/#linking-between-pages)? Being a part of core Gatsby it's documented in several places (and hopefully isn't too hard to find) 🙂

If those are difficult to find it might be worth considering moving those to make them easier to discover, a lot of this could have been considered in https://github.com/gatsbyjs/gatsby/issues/13712 as well.

**Comment by endormi** [comment]
I meant the gatsby API reference, that is a page with only a link to the reference, I don't think that's needed let alone it's doesn't seem to be on the website.

**Comment by gillkyle** [comment]
I'm not sure I understand what pages or references you're talking about then I guess, my bad! 

Can you provide links to the page or lines of code where that link is?

**Comment by endormi** [comment]
Yeah [old docs](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-link/README.mdl)

**Comment by gillkyle** [comment]
Ah yes! That's a broken link and a PR to fix that would be appreciated! That should link to [this](https://www.gatsbyjs.org/docs/gatsby-image/) page.

**Comment by endormi** [comment]
Hmm, to gatsby-image? That's a gatsby-link.md

**Comment by gillkyle** [comment]
🤦‍♂ my bad haha I'm bouncing around between too many things, you're correct this is the proper link: https://www.gatsbyjs.org/docs/gatsby-link/

**Comment by endormi** [comment]
😄 okay, I will make a pr for it now.
