### ISSUE TITLE
[1.0] Blog post featured image

### ISSUE THREAD

**Issue by oltodo** [gatsbyjs/gatsby#1576]
Hi!

I'm trying to find a way that consists to attribute to each blog post a featured image (like in Wordpress).

By considering the following blog post example :

```md
# /src/pages/hello-world/index.md

---
title: Hello World!
path: /hello-world
image: ./hello.jpg
---

Hello World!
```

I would like to be able to retrieve `hello.jpg` — through the Graphql query's response — in the form as `/static/<hash>.png` like the pictures handled by the `gatsby-transformer-remark` plugin.

That could able me to use it easily on listings and detail pages.

Something ready to use already exists or I have to write my own plugin ?

**Comment by oltodo** [comment]
P.S. : Thanks a lot for this great work.

**Comment by nicholaswyoung** [comment]
First of all, ensure you've installed the `sharp` plugins, too. Those allow Gatsby to resize and crop images as specified.

Next, you'll write a query like [this one](https://github.com/gatsbyjs/gatsby/blob/master/www/src/templates/template-blog-post.js#L199-L206). Maybe try:

```
image {
  childImageSharp {
    responsiveResolution(...args) {
      src
    }
  }
}
```

I left out the exact arguments, but you should see some options in the linked code. Hope this helps!

**Comment by oltodo** [comment]
Thanks for your response @nicholaswyoung. This is a very good idea indeed.

However, the example you linked works with [absolute URL](https://github.com/gatsbyjs/gatsby/blob/524ff171cd890b79ce9535d6dc10550c70365d33/examples/gatsbygram/data/posts.json#L6). In my case, I would like to reference my picture using relative path to the folder where the Markdown post file (`index.md`) is located.

**Comment by nicholaswyoung** [comment]
@oltodo Give it a try. I think you'll find I'm correct. ;) The same technique is being [used on](https://github.com/nicholaswyoung/web/blob/master/src/templates/Post.js#L243-L248) [my blog.](https://github.com/nicholaswyoung/web/blob/master/content/articles/2017-06-10-casual-ableism/index.md)

**Comment by oltodo** [comment]
Lack of faith! You was right @nicholaswyoung, it works fine now.
In fact, I had a slight different think in comparison to my example. The `image` property was not a single string containing the picture's URL but an object with `src` and `credit` fields.

```
---
title: Hello World!
path: /hello-world
image:
  src: ./hello.jpg
  credit: Hello World Production
---

Hello World!
```

I tried something like this in my Graphql query :

```graphql
frontmatter {
  title
  image {
    src {
      childImageSharp {
        responsiveResolution(width: 600) {
          src
        }
      }
    }
  }
}
```

But I didn't have any good result.

Thanks a lot for your help!
