### ISSUE TITLE
Stylesheet imports aren't scoping to pages/components

### ISSUE THREAD

**Issue by joesanchezjr** [gatsbyjs/gatsby#15770]
## Description

When importing stylesheets into pages/components, the stylesheet becomes available globally and on all pages instead of only being used on the page/component it was imported into - even when navigating away from the page that is has been imported into. 

If this isn't a bug and `imports` are happening like they are supposed to, then perhaps clarification is needed in [this part of the docs](https://www.gatsbyjs.org/docs/global-css/#importing-css-files-into-components).

### Steps to reproduce

1. Create a new Gatsby site using the default starter
2. Create a new file called `index-styles.css` in `src/pages` with the following content:
```css
p { background-color: orange; } 
```
3. Create a new file called `page-2-styles.css` in `src/pages` with the following content:
```css
p { background-color: rebeccapurple; }
```
4. Import each file into their corresponding pages as exampled in the official Gatsby [docs](https://www.gatsbyjs.org/docs/global-css/#importing-css-files-into-components)

`index.js` should look like:
```js
import "./index-styles.css"
```
`page-2.js` should look like:
```js
import "./page-2-styles.css"
```
Alternatively, you can view it here: 

[![Edit gatsby-starter-default](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gatsby-starter-default-k8wpo?fontsize=14)

### Expected result

When navigating between pages, only the imported stylesheet of the current page should be loaded. 

In the example above, paragraph elements should have a background color of `orange` when on the `index` page and `rebeccapurple` when on `page-2` because only the stylesheet imported for that page is loaded. `page-2` shouldn't even know that about the `orange` style.

The end result should allow for a folder structure of:
```
src
└─pages/
  |─ index.js
  |─ index.css
  |─ page-2.js
  |─ page-2.css
  |─ etc.js
  |─ etc.css
```
Where each page/component can import a stylesheet that only applies to it. This would be a similar structure to CSS Modules without actually using modules. It should be able to work with CSS and SCSS.

### Actual result

Instead, when navigating between pages, all imported stylesheets are loaded on all pages - regardless of whether or not it was imported on a specific page.

In the example above, the paragraph elements end up having the background color of `rebeccapurple` on both the `index` page and `page-2` because both stylesheets are imported.

The compiled css after running `gatsby build` includes:
```scss
p {
background-color: orange;
background-color: #639; // rebeccapurple
}
```

### Environment

Issue is happening on an unconfigured Gatsby site using the default starter.
 ```
 System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.21 => 2.13.21 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-sharp: ^2.2.7 => 2.2.7 
    gatsby-source-filesystem: ^2.1.5 => 2.1.5 
    gatsby-transformer-sharp: ^2.2.3 => 2.2.3 
  npmGlobalPackages:
    gatsby-cli: 2.7.3
```

**Comment by sidharthachatterjee** [comment]
Thank you for the detailed issue @joesanchezjr 

This is intended behaviour as far as I can see and the section in https://www.gatsbyjs.org/docs/global-css/#limitations describes the limitations of global CSS. 

Would you like to open a PR with a more detailed clarification?

CC @gatsbyjs/docs

**Comment by joesanchezjr** [comment]
Thanks for responding @sidharthachatterjee 

I'd love to contribute to the docs! It might take me a while to get to it, but where can I get started with the process?

**Comment by wardpeet** [comment]
We have a section called [How to contribute](https://www.gatsbyjs.org/contributing/how-to-contribute/) and a more specific section on [docs contributions](https://www.gatsbyjs.org/contributing/docs-contributions/). Let me know if this gets you going. If not we also have [pairing sessions](https://www.gatsbyjs.org/contributing/pair-programming/) where we love to help you get started!

**Comment by stupidehorizon** [comment]
I had the same problem！

**Comment by stupidehorizon** [comment]
I have resolve this problem by using https://www.gatsbyjs.org/packages/gatsby-plugin-purgecss/ this plugin @joesanchezjr
