### ISSUE TITLE
Gatsby Fails when missing a package.json in the cwd

### ISSUE THREAD

**Issue by jerroydmoore** [gatsbyjs/gatsby#15773]
## Description

I want to put the gatsby project in a subdirectory and my NodeJS backend in another subdirectory in my project. I don't want to maintain separate package.json for both directories, and the frontend and backend can't be run independently, they are tightly coupled, so it makes sense to put them in the same repository. Since the gatsby subdirectory doesn't have a package.json, I get the following error: 

```
gatsby <develop> can only be run for a gatsby site.
Either the current working directory does not contain a valid package.json or 'gatsby' is not specified as a dependency
```

Gatsby commands work when I add a dummy package.json with the following contents.:

```package.json
{
  "dependencies": {
    "gatsby": "^2.13.23"
  }
}
```

### Steps to reproduce

1. Create a new gatsby project in `project/ui/`. Move `package.json`, `package-lock.json`, and `node_modules` to the parent directory,`project`. Run `gatsby develop` in `project/ui`.

Demo: https://github.com/jerroydmoore/vogons/tree/demo/broken-gatsby-with-missing-package-json

### Expected result

`gatsby develop` runs successfully

### Actual result

Gatsby fails with an error:

```
gatsby <develop> can only be run for a gatsby site.
Either the current working directory does not contain a valid package.json or 'gatsby' is not specified as a dependency
```

### Environment

```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.0.3
  npmGlobalPackages:
    gatsby-cli: 2.7.15
```

Edit: Formatting.

**Comment by m-allanson** [comment]
Thanks for the clear explanation @jerroydmoore 👍 Creating the 'fake' `package.json` file will get past the check, but you'll probably run into strange issues later on as there are no tests around running Gatsby like that. It might turn out that this totally works but I'd guess there will be some unexpected edge-cases.

I suspect that updating Gatsby to be runnable without a `package.json` would be a surprising amount of work (for a nice, but fairly small improvement). It's probably not something we can focus on in the near future.

However, all is not lost! [Yarn's workspace feature](https://yarnpkg.com/lang/en/docs/workspaces/) and [Lerna](https://github.com/lerna/lerna) are both designed for managing multiple sets of dependencies within one project. I'd recommend using one of those tools to help with managing dependencies in your project structure.

**Comment by jerroydmoore** [comment]
Switching to yarn seems to have worked well for me! Thanks for the tip. I'll close this issue now.
