### ISSUE TITLE
upgrade webpack version

### ISSUE THREAD

**Issue by csr632** [gatsbyjs/gatsby#15775]
## Description

Gatsby fix webpack version at `~4.28.4` in [this commit](https://github.com/gatsbyjs/gatsby/commit/f460b7f59f3e2a71c9ca65276a3e2f0d2c9a7fef), because [there is an regression in webpack 4.29](https://github.com/webpack/webpack/issues/8656).
But now that regression is fixed. It should be ok to use `4.35.x` or later.

Some newer plugin expect [webpack's finishModules hook](https://github.com/webpack/webpack/blob/37d4480382d362a6f44325f13b2f728ef6f1bfb1/lib/Compilation.js#L242) to be `AsyncSeriesHook`. But in webpack~4.28.4, [it is a SyncHook](https://github.com/webpack/webpack/blob/fdb6b139b94273e5b18870262c193a93f65132e8/lib/Compilation.js#L242), which will complain `tapPromise is not supported on a SyncHook` and cause a build failure.

### Expected result

We should use newer webpack version.

### Actual result

Webpack version is fixed at `4.28.x`.

### Environment

all

**Comment by wardpeet** [comment]
nice, now I can upgrade #14792 again

**Comment by csr632** [comment]
For impatient user: `npm install gatsby@webpack-acorn`
This tag use latest webpack.

**Comment by sidharthachatterjee** [comment]
We're now at [`~4.39.2`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json) so this should good to close. 

Further updates to dependencies are tracked in https://github.com/gatsbyjs/gatsby/issues/16840

**Comment by wardpeet** [comment]
It's not really, we need to bump higher but we're currently stuck with an upstream bug so i'm re-opening.
