### ISSUE TITLE
Theme blog colors.js logic

### ISSUE THREAD

**Issue by eclectic-coding** [gatsbyjs/gatsby#15781]
## Description

First, nothing is really broken. However, in the `gatsby-starter-theme-blog` in the `src/gatsby-theme-blog/gatsby-plugin-theme-ui/colors.js` the variables for the color overrides are reversed. 

![colors png](https://user-images.githubusercontent.com/13651291/61292505-59d0b700-a79f-11e9-81dd-78dd3704b275.png)

Notice the `lightBlue` is actually the darker of the blue colors. The site works as expected, but it might be better to have the variables match the description of the colors. 

### Steps to reproduce

Just read the file. 

I will be glad to submit a PR if you agree with this proposal. 

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

  System:
    OS: Linux 5.0 Pop!_OS 19.04
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.5.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0
  npmPackages:
    gatsby: ^2.13.21 => 2.13.21 
    gatsby-theme-blog: ^1.0.0 => 1.0.0 
```

**Comment by dantehemerson** [comment]
I think this is a typo, feel free to add a PR.
