### ISSUE TITLE
[gatsby-source-contentful] Gatsby build not completing

### ISSUE THREAD

**Issue by danspratling** [gatsbyjs/gatsby#15784]
## Description

After installation of gatsby-source-contentful in my gatsby project, setting up gatsby-config.js and running `gatsby develop` the build fails to complete. I'm not seeing any error logs, and there are no errors in the console. The process seems to still be running in the background but the terminal becomes unresponsive. Without this plugin installed build completes and i can access the site on localhost:8000 as per usual. 

This seems very close to the other issues regarding contentful requiring assets/content but i've ensured each content type has data in it and that isn't resolving the issue, so i believe it is different.

Terminal output (windows)
```yarn run v1.16.0
$ gatsby develop
success open and validate gatsby-configs - 0.119 s
success load plugins - 3.173 s
success onPreInit - 0.075 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success initialize cache - 0.123 s
success copy gatsby files - 0.321 s
success onPreBootstrap - 0.097 s
Starting to fetch data from Contentful
Fetching default locale
default locale is : en-US
contentTypes fetched 4
Updated entries  8
Deleted entries  0
Updated assets  2
Deleted assets  0
Fetch Contentful data: 178.954ms
Generating Kentico Cloud nodes for projectId: f6c0cb8d-be9c-00ae-f9b2-42c8ad46455c
Provided language codenames: en-US.
Creating content type nodes.
Creating node: 4e6c30bf-fcb2-56bd-894c-f78338936603(article_example_content_type)
Creating node: d4bfc515-3ae9-51d9-85e2-195a8b27386d(landing_page_example_content_type)
Creating node: 90a5e02e-bc65-59f7-b1dd-e781918aa21b(product_example_content_type)
Creating content item nodes for default language.
Creating content item nodes for non-default languages.
Kentico Cloud nodes generation finished.
warn The gatsby-transformer-sharp plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 0.776 s
success building schema - 0.434 s
success createPages - 0.075 s
success createPagesStatefully - 0.159 s
success onPreExtractQueries - 0.090 s
success update schema - 0.110 s
success extract queries from components - 0.703 s
success write out requires - 0.116 s
success write out redirect data - 0.102 s
success onPostBootstrap - 0.072 s
⠀
info bootstrap finished - 14.919 s
⠀
success run static queries - 0.074 s
success run page queries - 0.124 s — 6/6 123.24 queries/second //dies here every time
```
### Steps to reproduce

1. `yarn add gatsby-source-contentful`
2. add plugin to config (replacing the placeholders with correct tokens)
```
module.exports = {
  /* Your site config here */
  plugins: [{
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: '[space-id]',
        // Learn about environment variables: https://gatsby.dev/env-vars
        accessToken: '[access-token]'
      }
    },
    ....
  ]
};
```
3. `yarn` (install npm modules)
4. `yarn develop` - see above for log.

### Expected result

Build completes without errors and begins running devserver with access to contentful data in Graphiql

### Actual result

Terminal crashes during build (unable to cancel process using CTRL+C), though no errors are logged.

### Environment

```System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.11
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.12.0 => 2.13.23
    gatsby-background-image: ^0.7.6 => 0.7.6
    gatsby-image: ^2.2.3 => 2.2.6
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1
    gatsby-plugin-sass: ^2.1.0 => 2.1.3
    gatsby-plugin-sharp: ^2.2.1 => 2.2.7
    gatsby-plugin-typescript: ^2.1.0 => 2.1.2
    gatsby-source-contentful: ^2.1.13 => 2.1.13
    gatsby-source-filesystem: ^2.1.4 => 2.1.5
    gatsby-source-kentico-cloud: ^3.1.0 => 3.1.0
    gatsby-transformer-sharp: ^2.2.0 => 2.2.3
```

**Comment by jonniebigodes** [comment]
@danspratling i've just finished creating a new Gatsby added `gatsby-source-contentful` and issued `gatsby build` and it indeed finished the build process as you can see below:

![dan_spra_1](https://user-images.githubusercontent.com/22988955/61326279-4b6db400-a80e-11e9-9088-75f0b3606206.png)

Probably something else going on in there. If you can, could you provide a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be looked at with more detail?

**Comment by danspratling** [comment]
I recreated a test case as above and it worked. Then i tried running the main project again and it errored because my node version was behind (i'm often switching for projects), so i corrected it and both failed.

It seems the error was being caused by the node version I was using. I was using v11 for newer projects which appears to be incompatible with gatsby-source-contentful. Reverting back to stable (10.16) works. Current (12.6) also works. Seems there was an issue specific to my version of node - i've removed it now.

**Comment by rudolphfunk** [comment]
Possibly duplicates: https://github.com/gatsbyjs/gatsby/issues/15210

**Comment by danspratling** [comment]
@rudolphfunk Yeah possibly a duplicate. Did you try switching your node version? That was the issue for me, after switching i'm no longer having problems.

**Comment by rudolphfunk** [comment]
@danspratling: Yes, see: https://github.com/gatsbyjs/gatsby/issues/15210#issuecomment-512213778

**Comment by freiksenet** [comment]
Closing as a duplicate.

**Comment by gmtteja** [comment]
it says not finished open and validate gatsby-configs
can you help me ?
