### ISSUE TITLE
Gatsby Transformer Remark Error: Type with name "MarkdownExcerptFormats" does not exists

### ISSUE THREAD

**Issue by fendermaniac** [gatsbyjs/gatsby#15798]
## Description

Trying to follow the basic Gatsby markdown guide, but I get `Error: Type with name "MarkdownExcerptFormats" does not exists` when I run gatsby develop in my environment

### Steps to reproduce

1. Set up a working instance of Gatsby pulling from the WordPress API, creating posts, pages and paginated results for the main posts page. 
2. Follow https://www.gatsbyjs.org/docs/adding-markdown-pages/ to add markdown, but add the query directly into the main query within gatsby-node.js. 
3. Run gatsby develop

### Expected result

I expect that the markdown files render into HTML

### Actual result

```error UNHANDLED REJECTION


  Error: Type with name "MarkdownExcerptFormats" does not exists```

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Python27/python
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.10.0 => 2.10.0
    gatsby-image: ^2.2.3 => 2.2.3
    gatsby-paginate: ^1.1.0 => 1.1.0
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6
    gatsby-plugin-manifest: ^2.2.0 => 2.2.0
    gatsby-plugin-offline: ^2.2.0 => 2.2.0
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1
    gatsby-source-filesystem: ^2.1.5 => 2.1.5
    gatsby-source-wordpress: ^3.1.3 => 3.1.3
    gatsby-transformer-remark: ^2.6.6 => 2.6.6
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0

**Comment by fendermaniac** [comment]
I can confirm that I can get the markdown rendering properly with a clean version of Gatsby.

**Comment by stefanprobst** [comment]
Yes, the latest `gatsby-transformer-remark` has a peer dependency on `gatsby` v2.12 and above, so updating the `gatsby` package should fix this.

**Comment by fendermaniac** [comment]
I can confirm that updating to the latest version of `gatsby` has resolved this error. Thank you @stefanprobst.

**Comment by kxdang** [comment]
@fendermaniac, I have a stupid question but how do I update to the latest version of gatsby?

**Comment by fendermaniac** [comment]
Hi Kien,

I just did npm update gatsby

I hope that helps.

**Comment by kxdang** [comment]
Thank you very much @fendermaniac !
