### ISSUE TITLE
Not able to create new project

### ISSUE THREAD

**Issue by adolfobarreto75** [gatsbyjs/gatsby#158]
Hi, I'm now getting a different error while trying to create a new project. I'm using windows 10:

C:\Users\barre\Documents\sites>gatsby new my-test-gatsby-site
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Users\barre\AppData\Roaming\npm\node_modules\gatsby\bin\cli-new'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

Thanks, 
Adolfo

**Comment by KyleAMathews** [comment]
@adolfobarreto75 this is a known problem on Windows. You can rename files to get things working. See https://github.com/gatsbyjs/gatsby/issues/80

I'd be much appreciated if you could find the source of this problem (and fix it) :)
