### ISSUE TITLE
ESLint not running during `gatsby build`?

### ISSUE THREAD

**Issue by ind1go** [gatsbyjs/gatsby#15800]
## ESLint not running during `gatsby build`?

I'm setting the Gatsby build up in a CI server, so in an automated environment and working out what I can do purely by reacting to return codes. I'm trying to make sure that as a team we don't fall into silly mistakes. Part of that is ensuring our code standards through ESLint.

I've not changed the default setup of Gatsby - i.e. I've not followed any of the steps in https://www.gatsbyjs.org/docs/eslint/.

I'm running `gatsby develop` and I can see that eslint kicks in, which is great. If I leave the same problem in the code and switch to `gatsby build`, the same warning is not emitted. Is this intentional? Should I be running ESLint separately for the production build?

### Environment (if relevant)

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 68.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.8.2 => 2.8.2 
    gatsby-image: ^2.1.2 => 2.1.2 
    gatsby-plugin-offline: ^2.1.1 => 2.1.1 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3 
    gatsby-remark-images: ^3.1.3 => 3.1.3 
    gatsby-source-filesystem: ^2.0.38 => 2.0.38 
    gatsby-transformer-remark: ^2.5.0 => 2.5.0 
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21 
  npmGlobalPackages:
    gatsby-cli: 2.7.8

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
Yes, we do use `eslint-loader` only in development right now:
https://github.com/gatsbyjs/gatsby/blob/67ccf740f42cf2b796dbcc783fbdb4ffd2be9a0b/packages/gatsby/src/utils/webpack.config.js#L299-L306

If you want to use `eslint` in builds I would advice using https://www.gatsbyjs.org/packages/gatsby-plugin-eslint/?=eslint plugin with configuration like this:

```
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-eslint',
      options: {
		// build-javascript stage is one for production builds
        stages: ['develop', `build-javascript`],
        options: {
          emitWarning: true,
          failOnError: false,
          // optionally you can also use fail builds on warnings - depend how much you want to enforce it
          failOnWarning: true
        }
      }
    }
  ]
}
```

**Comment by ind1go** [comment]
Thanks! You even pre-empted my other questions.
