### ISSUE TITLE
Document how to make npm/yarn/node work with corporate supplied certs

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#15807]
Worked through this with some devs at Capital One — there was no good place on the internet that explained this and it’ll be a common problem corporate devs run into so we should make clear docs about how you configure npm/yarn/node to work with a supplied cert.

- npm — `npm config set cafile "<path-to-my-cert.pem>"`
- yarn — `yarn config set cafile "<path-to-my-cert.pem>"`
- node — `export NODE_EXTRA_CA_CERTS=[your CA certificate file path]` (we should show how to add env variable to different OSs that’ll persist across sessions 

There was a very weird error they were running into when installing gatsby-plugin-sharp that we should also add so our docs page will show up when people google for the error.

**Comment by KyleAMathews** [comment]
Here’s an example error:

```
yarn
yarn install v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@mdx-js/mdx > @babel/plugin-syntax-jsx@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@mdx-js/mdx > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] 🔨  Building fresh packages...
[7/8] ⠂ cwebp-bin
[-/8] ⠂ waiting...
[6/8] ⠂ pngquant-bin
[4/8] ⠂ sharp
error /Users/dev/my-mdx-starter/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /Users/dev/my-mdx-starter/node_modules/pngquant-bin
Output:
⚠ unable to get local issuer certificate
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
```

**Comment by sidharthachatterjee** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/16748 thanks to @gillkyle
