### ISSUE TITLE
command-enter doesn't work in graphql explorer

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#15805]
Probably we should ping onegraph about this — @pieh

**Comment by pieh** [comment]
Can you clarify? Keyboard shortcuts are handled by CodeMirror and are defined inside `graphiql` package that we use ( https://github.com/graphql/graphiql/blob/55d6946a1fdad2fa0276e5c33ca3534cc5a63c67/packages/graphiql/src/components/QueryEditor.js#L109-L161 )

Command-space never worked for me - it always seemed to be hijacked by system to show spotlight on macOS

**Comment by polishedwp** [comment]
Actually, I think Ctrl+Space is the command on a Mac. I left Mac a few weeks ago for Ubuntu but I think this [thread](https://github.com/graphql/graphiql/issues/670#issuecomment-453618135) indicates the same.

**Comment by KyleAMathews** [comment]
Both ctrl+space & command+space work for — but only inside the text editor — not the explorer

Annotated:
<img width="1720" alt="GraphiQL_and__11__Notifications___Twitter_and_1__gatsby-starter-blog__gatsby_develop__gatsby__node_" src="https://user-images.githubusercontent.com/71047/61412945-178e9f00-a89f-11e9-92d5-d93dd6801257.png">

**Comment by pieh** [comment]
I'm not sure what ctrl/cmd+space should actually do when you are in explorer honestly

**Comment by pieh** [comment]
If you mean cmd/ctrl + enter then it makes a lot more sense to me

**Comment by KyleAMathews** [comment]
Oh haha, yeah cmd+enter 🤦‍♂

**Comment by KyleAMathews** [comment]
My fingers knew the right keystroke, just not my brain :-D

**Comment by sgrove** [comment]
@pieh we definitely handle this in the explorer whenever an input box is focused, here's the line that should be run: https://github.com/gatsbyjs/gatsby/blob/9ef6dbffb2a1f82d68a5b8ec02eb6d51e4b522ca/packages/gatsby-graphiql-explorer/src/app/app.js#L284 ( [here](https://github.com/OneGraph/graphiql-explorer/blob/master/src/Explorer.js#L561)'s the code detecting the shortcut)

@KyleAMathews Feedback on users tripping up is great - was it happening while they had an input box highlighted, or where they trying to run it after e.g. checking a field?

**Comment by KyleAMathews** [comment]
After checking a field.

**Comment by acao** [comment]
ctrl enter works for me in both gatsby's graphiql with explorer, and in graphiql
not sure how to simulate cmd enter on linux, let's see if i can

**Comment by acao** [comment]
we were able to confirm that graphiql explorer + graphiql have working cmd enter using the latest versions of both graphiql and graphiql-explorer packages

the only delta I could find was this version:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-graphiql-explorer/package.json#L47

possibly if we upgrade to 0.6.4 we won't have this issue?
