### ISSUE TITLE
Using Gatsby for a Component Library

### ISSUE THREAD

**Issue by dwalks12** [gatsbyjs/gatsby#15809]
Currently there seems to be no out of the box solution to using gatsby components within a component library. Namely gatsby-image. I ideally want to use the benefits of gatsby-transformer-sharp and create a compiled component library that utilizes that. 

The Problem:
Because we also use StaticQuery for the gatsby-image if we use graphql the actual compilation does not seem to work well. 
Any help would be greatly appreciated!

Request:
A tutorial on how to create a custom component library utilizing some gatsby components.

**Comment by pieh** [comment]
You can use `gatsby-image` as standalone component, but you would have to handle image transformation on your own in this case:

```
import Image from "gatsby-image"

<Image fluid={{
  // base64 is optional
  base64: "base64-enocded-image-here",
  src: "path-to-main-src",
  srcSet: "srcSet string",
  sizes: "sizes string"
}} />
```

I'm not sure if this helps - but if you are using `gatsby-image` outside of Gatsby, then you will have to somehow handle image transformation on your own.

**Comment by dwalks12** [comment]
@pieh any ideas on how to handle image transformation outside the gatsby build architecture?
