### ISSUE TITLE
Update the tutorial to use the explorer

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#15806]
We need to update the screenshots in general but it'll also be great to teach people the explorer as it's much more approachable than just typing things.

**Comment by fk** [comment]
Could be a nice opportunity to define a "screenshot spec" and try to streamline things a little more (even though the screenshot content is _much_ more important than the appearance).

**Comment by marcysutton** [comment]
@KyleAMathews do you mean reflecting the changes to the GraphiQL interface? I think there are screenshots of it in the tutorial already. Just wanted to clarify for whoever picks this work up.

**Comment by KyleAMathews** [comment]
Yeah mostly screenshots. Probably some of the text could be updated as well to reference it as well.

**Comment by marcysutton** [comment]
What could go in a screenshot spec:

- Screen resolution
- Image dimensions / pixel density
- Image background consistency (I usually go full-width with content and let the website UI add a border)

**Comment by fk** [comment]
I personally really like the visual appearance/feel of the screenshots that show the whole browser window including the window's drop shadow (example from [here](http://localhost:8000/tutorial/part-two/)): 
![image](https://user-images.githubusercontent.com/21834/62011195-506b2580-b175-11e9-9e03-0448336a3be7.png)

But…

- those dropshadows take away a lot of space
- they increase image size, esp. when we think of using `PNG`s with transparency to make the drop shadow work in the context of a dark theme

So if we'd want that appearance, we'd probably want to go with CSS instead. We could even think of creating a "in-browser-content" screenshot component that shows a bit of browser chrome, and allows to set an URL to be displayed in the browser chrome's address field. Probably too much… 😉 🤷‍♂️

Thus a big 👍 for Marcy's suggestion to not include a background:

> I usually go full-width with content and let the website UI add a border

…but I'm wondering if we would add that border for every Markdown image?
If so, I think I'd prefer a box-shadow… 😅 …and ideally control over that, but that comes at a price of course.

**Comment by marcysutton** [comment]
In looking at the tutorial, parts 5 and 6 of the tutorial have GraphiQL screenshots that need to be updated. 

- Part 5, source plugins: https://www.gatsbyjs.org/tutorial/part-five/ (this also includes an animated GIF)
- Part 6, transformer plugins: https://www.gatsbyjs.org/tutorial/part-six/
