### ISSUE TITLE
Deprecate "allSite" GraphQL type

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#15804]
There's a `Site` node type which is why it's created but there's obviously only one site so having `allSite` is confusing.

@freiksenet

**Comment by pieh** [comment]
Should this be considered breaking change? Agree with `allSite` being unnecessary, but still - people could use it

**Comment by joeynimu** [comment]
I agree with @pieh , people could be using this.

**Comment by KyleAMathews** [comment]
yeah — we can deprecate this initially and remove it in v3. If we deprecate it it'll keep working but not show up in graphiql which is my main goal.

**Comment by sidharthachatterjee** [comment]
Notes on what needs to be done for first time contributors

- [ ] Deprecate the field (Example in https://github.com/gatsbyjs/gatsby/pull/15409)
- [ ] Ensure there is no usage of it in this monorepo

**Comment by molebox** [comment]
Oh could i have a go at this?

**Comment by sidharthachatterjee** [comment]
Absolutely @molebox 🙌

**Comment by molebox** [comment]
Is there any chance i could get a little guidance with this? I know its a simple fix but im very lost in the gatsby repo. 

I thought it would be as simple as doing a search for where allSite is declared and go from there but thats turned up nothing for me. Im not 100% where to begin...

**Comment by alexluong** [comment]
Hey @molebox, I believe Gatsby register `allSite` type [here](https://github.com/gatsbyjs/gatsby/blob/27d878f429e7fc45b20f60d72d501aab74ec56a8/packages/gatsby/src/schema/schema.js#L895).

To *remove* `allSite` type, on line 903 you can do something like this:

```js
queryNamePlural !== "allSite" && [queryNamePlural]: {
```

But I'm not sure how to deprecate it. Maybe Gatsby have an extension for that?

If not, I think a reasonable solution to do is to "declare" it as deprecated, check whether it's used, and report that it's deprecated. And then remove it in v3.

Any thoughts, @sidharthachatterjee?

**Comment by KyleAMathews** [comment]
We want it not showing up in the grapiql API which means it needs deprecated.

The fix is to add some code which finds this type and adds `deprecated: true`

**Comment by molebox** [comment]
just wanted to give an update... ive been on holiday but am back this weekend so will get on this! Sorry for the delay! :)

**Comment by molebox** [comment]
My bad ive been busy with other stuff and forgot i was assigned to this! I had solution though im not sure im on the right path. 

Would someone be able to take a look before a open a PR?
