### ISSUE TITLE
Images in post not showing

### ISSUE THREAD

**Issue by Defite** [gatsbyjs/gatsby#15811]
## Description

Images in post is not showing

### Steps to reproduce

Repo: https://github.com/Defite/defite-gatsby

https://defite.ru/blog/full-image-in-markdown - has image, showing
https://defite.ru/blog/netlify-eslint-and-codacy - has images, not showing

### Expected result

Images in post are visible

### Actual result

Images in post has 0px width

### Environment

```
System:
    OS: macOS Sierra 10.12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.2 - /bin/zsh
  Binaries:
    Node: 10.6.0 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 65.0
    Safari: 12.1.1
  npmPackages:
    gatsby: latest => 2.13.25
    gatsby-paginate: ^1.0.17 => 1.1.0
    gatsby-plugin-feed: latest => 2.3.4
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.4
    gatsby-plugin-i18n: ^0.4.2 => 0.4.2
    gatsby-plugin-manifest: latest => 2.2.3
    gatsby-plugin-offline: latest => 2.2.4
    gatsby-plugin-postcss: latest => 2.1.2
    gatsby-plugin-prefetch-google-fonts: ^1.4.0 => 1.4.2
    gatsby-plugin-react-helmet: latest => 3.1.2
    gatsby-plugin-react-svg: ^2.0.0-beta1 => 2.1.1
    gatsby-plugin-sharp: latest => 2.2.7
    gatsby-plugin-typography: latest => 2.3.2
    gatsby-remark-copy-linked-files: latest => 2.1.3
    gatsby-remark-images: latest => 3.1.6
    gatsby-remark-picture: 1.0.1 => 1.0.1
    gatsby-remark-prismjs: latest => 3.3.3
    gatsby-remark-responsive-iframe: latest => 2.2.4
    gatsby-remark-smartypants: latest => 2.1.2
    gatsby-remark-unwrap-images: 1.0.1 => 1.0.1
    gatsby-source-filesystem: latest => 2.1.5
    gatsby-source-graphql: 2.0.10 => 2.0.10
    gatsby-transformer-remark: latest => 2.6.6
    gatsby-transformer-sharp: latest => 2.2.3
  npmGlobalPackages:
    gatsby-cli: 2.4.16
```

Also here is the source for my blog: https://github.com/Defite/defite-gatsby

**Comment by polishedwp** [comment]
I had the same issue. You might want to look here #15486 ... it actually helped me.

**Comment by Defite** [comment]
Well, the thing is I don't have `gatsby-plugin-mdx` at all. Do I have to install it?

**Comment by lannonbr** [comment]
So at least looking around at this, the one on the "Full Image in Markdown" page is contained in a table while the other is not. CSS grid & Flexbox have some gotchas where if a container doesn't explicitly have a defined width, it reduces down to 0px due to how grid / flexbox lays things out. So you could say on all of the images to use a width: 100% to take up the width of it's parent container and that would then explicitly give it a width

**Comment by Defite** [comment]
Case closed: 

```
.gatsby-resp-image-wrapper {
  width: 100%;
}
```

Resolves my issue.
