### ISSUE TITLE
YAML transformer: TypeError [ERR_INVALID_ARG_TYPE] when YAML not sourced as file

### ISSUE THREAD

**Issue by igorakkerman** [gatsbyjs/gatsby#15827]
## Description

With various source plugins, YAML documents are not processed by _gatsby-transformer-yaml_.

The JSON transformer had an analogous issue: https://github.com/gatsbyjs/gatsby/issues/8538

### Steps to reproduce
Use a source plugin like _gatsby-source-contentful_ or _gatsby-source-github-raw_ to read YAML content.

Use the YAML transformer without explicitly setting the `typeName` option:
```
        {
            resolve: `gatsby-transformer-yaml`,
            options: {
                // NOT setting typeName explicitly
            }
        },
```

### Expected result

The YAML document should be processed correctly with a meaningful type name.

### Actual result

A somewhat cryptic error message is shown, it doesn't hint at the actual issue:
```
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

  - validators.js:107 validateString
    internal/validators.js:107:11

  - gatsby-node.js:32 getType
    [gatsby-lab]/[gatsby-transformer-yaml]/gatsby-node.js:32:47

  - gatsby-node.js:74 Object.onCreateNode
    [gatsby-lab]/[gatsby-transformer-yaml]/gatsby-node.js:74:111

  - task_queues.js:85 processTicksAndRejections
    internal/process/task_queues.js:85:5
```

**Comment by igorakkerman** [comment]
PR https://github.com/gatsbyjs/gatsby/issues/8538 fixes the issue.

**Comment by pieh** [comment]
Above PR was merged, and new version of `gatsby-transformer-yaml` (`2.2.4`) was published. I'll close this is as fixed, but feel free to re-open or create new issues for this if problems still occur.
