### ISSUE TITLE
Pass `PageComponent` prop to `wrapPageElement` APIs

### ISSUE THREAD

**Issue by universse** [gatsbyjs/gatsby#15820]
I'm using gatsby-plugin-layout for sharing states that persist across routes. Can pages be components instead of elements when passed to Layout as children?

So, instead of
```javascript
export default function Layout ({ children }) {
  return <State>{children}</State>
}
```

It can be
```javascript
export default function Layout ({ PageComponent }) {
  return <State><PageComponent /></State>
}
```

This is similar to how Next.js does it https://nextjs.org/docs#custom-app.
Use case is passing props from Layout to page components. Since page is direct children of layout, using Context can be a bit of an overkill for some cases.
I understand that React.cloneElement can be used. Yet, I feel that passing props to components is more idiomatic.

**Comment by pieh** [comment]
Not cleanest, but you can do it like this:
```
export default function Layout({ children, ...props }) {
  const PageComponent = props.pageResources.component
  return <State><PageComponent {...props} extraProp="Hi" /></State>
}
```

Note that you probably should pass original props (as I did in my example) - otherwise page components could miss things like query results or location (some props that we pass by default to page components)

**Comment by universse** [comment]
This doesn't work for production build though. console.log(props.pageResources) gives undefined. In development it works as expected.

**Comment by universse** [comment]
Seems like pageResources isn't available during SSR. console.log(props.pageResources) gives undefined in CLI but in browser it works as expected.

**Comment by pieh** [comment]
Yeah, you are right. I think it's reasonable request to pass `PageComponent` as top-level arg/prop and make sure it works both in runtime and ssr.

**Comment by pieh** [comment]
I did some checking and there might be potential issues with https://www.gatsbyjs.org/docs/browser-apis/#replaceComponentRenderer (legacy/deprecated API) - this API allow you to replace Page Component - in v1 of gatsby it was used mostly for the same purpose as wrapPageElement to wrap page component with something - but it returns react element (not component) - which means that if you would not use `children`, it would discard results of that API. We don't use the API anywhere in plugins we maintain, but we don't really know if any 3rd party plugins still use that.

This is not strictly blocker - we can put Note in docs about this - just something to keep in mind.

**Comment by universse** [comment]
Thank you very much for looking into this.

**Comment by universse** [comment]
not stale

**Comment by chocobuckle** [comment]
> Yeah, you are right. I think it's reasonable request to pass `PageComponent` as top-level arg/prop and make sure it works both in runtime and ssr.

I'm a bit confused by this. Could you show an example please? This is my current code for wrapPageElement

```
exports.wrapPageElement = ({ props }) => {
  const PageComponent = props.pageResources.component;
  return (
    <>
      <Layout {...props}>
        <PageComponent {...props} />
      </Layout>
    </>
  );
};
```

How would one do the same server side if implementing your recommendation.

**Comment by joselcvarela** [comment]
I was facing this issue too. But I found a workaround.
In my case I want to prevent re-render of the Layout component, so I put the Layout component into `wrapPageElement`
```
//gatsby-browser.js and gatsby-ssr.js
import wrap_page from "components/wrap-page"

export const wrapPageElement = wrap_page

// components/wrap-page
export default function wrap_page({ element, props }) {
  const { Mobile, DesktopLeft, DesktopMiddle } = element.type(props)

  if (!Mobile) return element

  return (
    <AnimatePresence>
      <Layout
        {...props}
        Mobile={Mobile}
        DesktopLeft={DesktopLeft}
        DesktopMiddle={DesktopMiddle}
      />
    </AnimatePresence>
  )
}
```
As you can see, I am returning an object from my pages with Mobile, DesktopLeft, DesktopMiddle components.

On development it works fine, but on build crashes with this error
```
WebpackError: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BMobile%2C%20DesktopMiddle%7D for the full message or use the non-minifi
  ed dev environment for full errors and additional helpful warnings.
 ```
 
 And on that link it says:
 ```
 Objects are not valid as a React child (found: object with keys {Mobile, DesktopMiddle}). If you meant to render a collection of children, use an array instead.
 ```
 
To fix this error, I just append this property `$$typeof: Symbol.for("react.element")` into all objects exported from pages.

Here is an example:
```
export default function Menu(props) {
  const {
    pageContext: { data },
  } = props

  function Mobile() {
    return (...)
  }

  return {
    Mobile,
    $$typeof: Symbol.for("react.element"),
  }
}

```
 
Finally I could get this working. 
Hope it helps someone else 😉

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v3 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

[reproduction]: https://gatsby.dev/reproduction
