### ISSUE TITLE
How to manually set graphql type / link to existing nodes

### ISSUE THREAD

**Issue by peonmodel** [gatsbyjs/gatsby#1583]
i see that infer-graphql-type.js will automatically inferObjectStructureFromNodes to create links between nodes
such that an .md file with frontmatter (image: '11.jpg') will return from graphql as frontmatter.image = { id: `${dir}/11.jpg` }

is it possible to manually create the links on onCreateNode or something similar?

**Comment by KyleAMathews** [comment]
Yes, you can can use [createNodeField](https://www.gatsbyjs.org/docs/bound-action-creators/#createNodeField) with the not-yet-documented `___NODE` syntax to create links between nodes.

Something like.

```javascript
createNodeField({
  node,
  name: `nodeLink___NODE`,
  value: `ID_OF_ANOTHER_NODE`
})
```

The auto-linking to file nodes is a special case that relies on relative links between file nodes. When you create links like above, you need to use the actual ID of the node you're trying to link to.

**Comment by peonmodel** [comment]
i keep having this error message
```
UNHANDLED REJECTION Invariant Violation: Encountered an error trying to infer a GraphQL type for: "internal.fieldOwners.nodeOtherLink___NODE". There is no corresponding node with the id field matching: "default-site-plugin"
```

it comes from
```
{ contentDigest: '3d75edb4822a6bbdc0d47f3aa1b28e0b',
  type: 'MetadataJson',
  owner: 'gatsby-transformer-json',
  fieldOwners: { nodeOtherLink___NODE: 'default-site-plugin' } }
```

**Comment by toxsick** [comment]
I have the same problem as @peonmodel. Trying to create a node field on a SitePage node with

```js
createNodeField({
  node,
  name: 'source___NODE',
  value: jsFrontmatterNode.id
});
```

but I'm getting

```
Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: "internal.fieldOwners.source___NODE". There is no corresponding node with the id field   matching: "default-site-plugin"
```

what's wrong?
