### ISSUE TITLE
Client only paths

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#15849]
I have question about client only paths

after click on "2" on page 
https://client-only-paths.gatsbyjs.org/

page is loaded corectly, but i i open directly address (or after f5)
https://client-only-paths.gatsbyjs.org/page/2

i get "Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site." 

there is a way to load correcly client only paths directly?

**Comment by pieh** [comment]
Yes. But this is something that Gatsby doesn't have direct control over and requires server or hosting configuration to rewrite dynamic URLs to corresponding html file.

If you are hosting on netlify - you can use `gatsby-plugin-netlify` which will do this automatically (like I did in this pull request https://github.com/gatsbyjs/gatsby/pull/15851 - we should have do this earlier). If you are using something else, than it's up to You to set this up.

There is note in https://github.com/gatsbyjs/gatsby/pull/15851 :
> These routes will exist on the client only and will not correspond to index.html files in an app’s built assets. If you’d like site users to be able to visit client routes directly, you’ll need to set up your server to handle those routes appropriately.

**Comment by pieh** [comment]
Sorry for closing issue (it did automatically by merging linked PR). We can re-open if you feel like question wasn't answered.

After few minutes demo site should also be updated so you will be able to navigate to https://client-only-paths.gatsbyjs.org/page/2 directly (tho there is a catch with this particular demo - that first it will display first page as it loads static html content and then will update once app hydrates)
