### ISSUE TITLE
[Feature] Multi-core processing for gatsby-plugin-sharp's image queue.

### ISSUE THREAD

**Issue by smurrayatwork** [gatsbyjs/gatsby#15845]
## Summary
Processing through a site with thousands (or tens, hundreds of thousands) of images takes a while to process through gatsby-plugin-sharp's scheduler queue. It'd be nice if the queue could take advantage of using multiple workers to process more than one job at a time.

### Basic example
gatsby-plugin-sharp is already using async and its queue functionality, but the concurrency is set to 1. Instead we could set this to adjust as according to how gatsby detects the number of CPUs with cpu-core-count:
```
const cpuCoreCount = require(`gatsby/dist/utils/worker/cpu-core-count`);
const q = queue((task, callback) => {
  task(callback);
}, cpuCoreCount());
```

### Motivation
Speed and performance of image processing for large sites.

**Comment by pieh** [comment]
As mentioned in linked PR - sharp already uses multiple cores. And queues in JS use concurrency not parallelism (unless you implement worker processes - either directly or with packages like `jest-worker`)

**Comment by sidharthachatterjee** [comment]
This is likely going to degrade performance as opposed to improving it due to thrashing since `sharp` already uses multiple cores under the hood.
