### ISSUE TITLE
Is it possible to pass a Link's href to it's child? (migrating from Next)

### ISSUE THREAD

**Issue by estevanmaito** [gatsbyjs/gatsby#15841]
## Summary

I'm migrating a project from Next.js where I use [Reactstrap](https://reactstrap.github.io) (React implementation of Bootstrap).

Right now to create a `nav-link`, for example, I would do this (using Next and Reacstrap):

```html
<Link passHref href="/">
    <NavLink>Home</NavLink>
</Link>
```

And the result would look like:

```html
<a href="/" class="nav-link">
    Home
</a>
```

**With Gatsby**, the following...

```html
<Link to="/">
    <NavLink>Home</NavLink>
</Link>
```

...results in:

```html
<a href="/">
    <a class="nav-link">Home</a>
</a>
```

The immediate and obvious solution I've found is to remove the Reactstrap component and directly add the needed classes to it:

```html
<Link to="/" className="nav-link">
    Home
</Link>
```

But then, the same should be done with with buttons, dropdowns, and everything else that depends on a link, breaking the goal of having components and Reactstrap at all in the beginning.

**Is there a way to pass a Link's href to it's child?**

## Relevant information

Next's documentation on this Link behavior: https://github.com/zeit/next.js/tree/canary/packages/next#forcing-the-link-to-expose-href-to-its-child

**Comment by sidharthachatterjee** [comment]
> Is there a way to pass a Link's href to it's child?

There isn't a straightforward way to do this at the moment. Gatsby's Link component is a wrapper on top of Reach Router's [Link](https://reach.tech/router) component 

However, you could solve your issue (of putting the `nav-link` class on the underlying anchor element in either of the following ways:

- Use the `getProps` prop (takes a function that can return props to be set on the inner anchor element, in your case, you can return `{ className: "nav-link" }` (https://reach.tech/router/api/Link)
- Use `innerRef` to get a ref to the anchor DOM element and do whatever you like with it

Hope this helps! Thank you for using Gatsby 🙌

**Comment by PsychedMagnet** [comment]
Reactstrap's components have a "tag" prop - you can pass in the Gatsby Link component reference to Reactstrap's "tag" and it will use it.

So your example becomes
`<NavLink tag={Link} to="/">Home</NavLink>`

Does this solve your problem?

**Comment by lahirudx** [comment]
> Reactstrap's components have a "tag" prop - you can pass in the Gatsby Link component reference to Reactstrap's "tag" and it will use it.
> 
> So your example becomes
> `<NavLink tag={Link} to="/">Home</NavLink>`
> 
> Does this solve your problem?

Thanks.
I also had the same problem. your solution worked perfectly.
