### ISSUE TITLE
Empty string is not a legal matchPath

### ISSUE THREAD

**Issue by cseebach-tpc** [gatsbyjs/gatsby#15853]
## Description

Gatsby does not allow the empty string - `""` - as a page's matchPath. If I want to add this matchPath, I have to write it into `match-paths.json` in the `.cache` directory myself.

The background here: at work, we host a Gatsby site on a prefix without a trailing slash - "/blog" instead of "/blog/" - and without that trailing slash, Gatsby doesn't load page-data correctly and also rewrites the URL in the browser, both of which we could avoid if we could set `""` as a matchPath for the index.

### Steps to reproduce

I have created a demo project - https://github.com/cseebach-tpc/gatsby-no-blank-match-path - based on the default starter. If you need to build one yourself, here are the steps:

1. Create a new gatsby project from the default starter. (`gatsby new some-directory`)

2. Add this code in your `gatsby-node.js` file:
```
exports.onCreatePage = ({ page, actions }) => {
  const { createPage, deletePage } = actions
  const oldPage = Object.assign({}, page)

  if (page.path === "/") {
    page.matchPath = ""

    deletePage(oldPage)
    createPage(page)
  }
}
```

3. Run `gatsby build`.

### Expected result

`.cache/match-paths.json` should include this entry:
```
[
    {
        "path": "/",
        "matchPath": ""
    }
]
```
### Actual result

Instead, `.cache/match-paths.json` has no entries:
```
[]
``` 

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
    Yarn: 1.15.2 - ~/.nvm/versions/node/v11.13.0/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.13.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.25 => 2.13.25 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-sharp: ^2.2.7 => 2.2.7 
    gatsby-source-filesystem: ^2.1.5 => 2.1.5 
    gatsby-transformer-sharp: ^2.2.3 => 2.2.3

**Comment by pieh** [comment]
I'm not sure if hacking `matchPath` is the way here - seems like root issue lies elsewhere and this is just workaround?

**Comment by cseebach-tpc** [comment]
@pieh maybe! We use this strategy because it's much simpler than rewriting those files ourselves, given the impressive pace of Gatsby development. ❤️ 

The root of our particular issue is that Gatsby assumes the root URL will always be `/` after any pathPrefix is removed. Undoing that assumption requires at least changes to `production-app.js` and `loader.js` and probably some other files that I missed. 

This is the relevant area from production-app.js: https://github.com/gatsbyjs/gatsby/blob/db5694abd0b05d47dd86d4eb181266f9c2bc2128/packages/gatsby/cache-dir/production-app.js#L98-L118

In our production setup, the pathPrefix is `/blog` and the root URL is `/blog`. On page load, none of the conditions are met and so the URL is replaced with `/blog/` after the page has finished rehydrating. This is not desirable from a user experience perspective, and even less desirable would be an immediate location replacement call from within the page code somewhere.

This is the relevant area from `loader.js`:
https://github.com/gatsbyjs/gatsby/blob/db5694abd0b05d47dd86d4eb181266f9c2bc2128/packages/gatsby/cache-dir/loader.js#L14-L17

Here, if the index is empty, as in our production setup, Gatsby believes it can find page data at `/blog//page-data.json` because the path after removing the prefix is simply `""`. When it fails to find that page-data, images and other after-hydrate content do not load correctly.

**Comment by wardpeet** [comment]
Like @pieh said, hacking matchPath isn't the solution. We probably want to make sure https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/ is working for matchPaths and regular pages.

**Comment by cseebach-tpc** [comment]
@wardpeet There's special cases in that plugin that prevent it from working on the index: https://github.com/gatsbyjs/gatsby/blob/2616e379b157a0693ed8b34afc177027a58ad413/packages/gatsby-plugin-remove-trailing-slashes/src/gatsby-node.js#L2

I can add it to the reproduction repo if you would like!
