### ISSUE TITLE
[gatsby-plugin-sass] Add a configuration for sass plugin file regexes

### ISSUE THREAD

**Issue by abumalick** [gatsbyjs/gatsby#15879]
## Summary
We want to use css modules with sass, but we don't want to add `.modules.` to the filename for every scss file in our app. Instead, we want to add `.global.` to global files, and normal scss files are modules by default.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sass/src/gatsby-node.js#L37
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sass/src/gatsby-node.js#L20

### Basic example

add `sassRuleTest` and `sassRuleModulesTest` to the plugin options, that would accept a regex. If no regex is provided we use the current regexes.

### Motivation

- Sass modules files are usually a lot more than global files.
- We copied the plugin code and modified these two tests in our app since we switched to gatsby and want to switch back to official plugin.

Thank you for the excellent framework 💪

**Comment by tkbky** [comment]
@abumalick 
I've made [a PR](https://github.com/gatsbyjs/gatsby/pull/16494) for this, feel free to take a look.

**Comment by sidharthachatterjee** [comment]
Published in `gatsby-plugin-sass@2.1.6` thanks to @tkbky
