### ISSUE TITLE
How to use or setup Foundation CSS with Gatsby

### ISSUE THREAD

**Issue by kumar-gitdev** [gatsbyjs/gatsby#15877]
Hi,

We are planning to use Gatsby as a Framework for our company, one of the requirement is using Foundation CSS with Gatsby, could some one guide me how to use Foundation CSS(https://foundation.zurb.com/) and Gatsby together I don't see any documentation or working examples.

Thanks,
Kumar.

**Comment by grantmoran** [comment]
Since the Foundation CSS is written in Sass, you're best bet is to utilize [gatsby-plugin-sass](https://www.gatsbyjs.org/packages/gatsby-plugin-sass) and load it accordingly.

[Foundation npm install](https://foundation.zurb.com/sites/docs/sass.html#loading-the-framework)

**Comment by kumar-gitdev** [comment]
Hi Grant,

Thanks for the response. currently I was able resolve the issue searching online, right now I am able to use the foundation and gatsby together, but lack of documentation and examples disappointed me, may be in future I will try to create some example and post it in my git hub page.

Below are the steps I have used to resolve the issue (**it might help some one**):

1. Install foundation-sites using **npm install** (in your package JSON you can use **"foundation-sites": "^6.4.3"** or some different version)

2. **gatsby saas plugin:** In your gatsby-config.js you have to use saas plugin (gatsby-plugin-sass)
    
 **plugins: [
    `gatsby-plugin-sass`]**

3. In your code create _settings.scss file and inside this file import the @import '~foundation-sites/scss/util/util';
also copy and paste the foundation style definitions in to the _settings.scss file
**https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss**

4. Inside your main component.js or main Layout.js file you have to (refer) import the the below foundation-sites files from your local node module(foundation-sites).

**@import '~foundation-sites/scss/util/util';
@import './settings';
@import '~foundation-sites/scss/foundation';**

after the above steps you should be able to use the foundation css in your gatsby html code any where inside components or layouts etc..

Hope this will help.

Thanks,
Kumar.

**Comment by kumar-gitdev** [comment]
Just an update everything works fine in **gatsby dev mode**, but when I do a **gatsby production build** I see some error saying "window" is not available during server side rendering.

**Below is the error details:**

 ERROR #95312

"window" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


  276 | /* eslint-disable */
  277 |
> 278 | window.matchMedia || (window.matchMedia = function () {
      | ^
  279 |
  280 |   var styleMedia = window.styleMedia || window.media; // For those that don't support matchMedium
  281 |


  WebpackError: ReferenceError: window is not defined

  - foundation.esm.js:278 Module../node_modules/foundation-sites/dist/js/foundation.esm.js
    node_modules/foundation-sites/dist/js/foundation.esm.js:278:1

**Comment by isaacewing** [comment]
> Just an update everything works fine in **gatsby dev mode**, but when I do a **gatsby production build** I see some error saying "window" is not available during server side rendering.
> 
> **Below is the error details:**
> 
> ERROR #95312
> 
> "window" is not available during server side rendering.
> 
> See our docs page for more info on this error: https://gatsby.dev/debug-html
> 
> 276 | /* eslint-disable */
> 277 |
> 
> > 278 | window.matchMedia || (window.matchMedia = function () {
> > | ^
> > 279 |
> > 280 |   var styleMedia = window.styleMedia || window.media; // For those that don't support matchMedium
> > 281 |
> 
> WebpackError: ReferenceError: window is not defined
> 
> * foundation.esm.js:278 Module../node_modules/foundation-sites/dist/js/foundation.esm.js
>   node_modules/foundation-sites/dist/js/foundation.esm.js:278:1

@kumar-gitdev  where you able to resolve this issue...
