### ISSUE TITLE
[gatsby-plugin-offline] creates link prefetch from link preconnect

### ISSUE THREAD

**Issue by cluk3** [gatsbyjs/gatsby#15883]
## Description

I have both gatsby-plugin gatsby-plugin-google-analytics and gatsby-plugin-offline installed.
When running lighthouse in production, it gives me the following warning: 

![image](https://user-images.githubusercontent.com/6255324/61488016-965a0980-a97d-11e9-8734-2197b1bec028.png)

Which is weird cause I'm not consuming any resource from `https://marketingplatform.google.com` 🤔 
So i started investigating and found out that basically this is coming from 2 redirects:

![image](https://user-images.githubusercontent.com/6255324/61488212-06688f80-a97e-11e9-9704-38d976566996.png)

If you look closely the initiator is gatsby-browser.
What is happening under the hood is that gatsby-plugin-google-analytics is adding a `<link rel="preconnect dns-prefetch" href="https://www.google-analytics.com">` ( https://github.com/gatsbyjs/gatsby/blob/4ba06ab6280756e5467b3179d4dfe27bdc761a5c/packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js#L27 )
and gatsby-plugin-offline is then consuming this link an creating a link prefetch from its href  😱

### Steps to reproduce

Having both the plugins above mentioned should work. You can check this starter as a reference: https://github.com/LekoArts/gatsby-starter-portfolio-cara and run lighthouse on the production demo: https://cara.lekoarts.de

### Expected result

gatsby-plugin-offline should ignore link `preload` · `prefetch` · `preconnect` · `dns-prefetch` 

### Actual result

it just take all the links and creates a link `prefetch` from them.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.12.0 - ~/n/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/n/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.21 => 2.13.27 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.4 
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3 
    gatsby-plugin-netlify: ^2.1.3 => 2.1.3 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-sharp: ^2.2.7 => 2.2.8 
    gatsby-plugin-sitemap: ^2.2.3 => 2.2.3 
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2 
    gatsby-plugin-tailwindcss: ^1.0.3 => 1.0.3 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5 
    gatsby-source-filesystem: ^2.1.5 => 2.1.5 
    gatsby-transformer-sharp: ^2.2.3 => 2.2.4 
  npmGlobalPackages:
    gatsby-cli: 2.7.15
```

**Comment by cluk3** [comment]
If this is really an issue and not the expected behaviour I'd be happy to discuss a possible solution and submit a PR with the fix

**Comment by eknowles** [comment]
does this change when reformatting the ordering of the plugins in gatsby-config?

**Comment by cluk3** [comment]
Yes, if I put  gatsby-plugin-google-analytics after gatsby-plugin-offline it doesn't happen anymore, but I still think gatsby-plugin-offline should ignore link preload · prefetch · preconnect · dns-prefetch as a final and clean solution. Thanks anyway, it works amazingly as an hotfix :)
