### ISSUE TITLE
[docs] permalink jumps to under the navbar

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#15896]
## Description

when i go to something like https://www.gatsbyjs.org/docs/node-api-helpers/#reporter and click the link to get the permalink, it jumps under the navbar.

### Expected result

should have the same result as when i land on https://www.gatsbyjs.org/docs/node-api-helpers/#reporter itself, scrolled just right. or maybe it just copies the link to clipboard for me.

i believe this is related https://github.com/gatsbyjs/gatsby/issues/7475

**Comment by tom-raley** [comment]
I'd like to work on this, but can't seem to replicate the issue when in development mode. If anyone can maybe point me in the right direction on that, I'd be happy to help!

**Comment by sw-yx** [comment]
can you replicate in prod on the live site?

**Comment by tom-raley** [comment]
yes, should have clarified. i see the issue on the live site, but when i try to fix it while developing, the issue doesn't happen for me.

**Comment by sw-yx** [comment]
oh dear. then i dont know. thats an interesting wrinkle. maybe @pieh can point us

**Comment by sw-yx** [comment]
noo

**Comment by LekoArts** [comment]
I don't see this behavior anymore so I'll close this one.
