### ISSUE TITLE
Duplicate data prefetches

### ISSUE THREAD

**Issue by dannybarinshtein** [gatsbyjs/gatsby#15899]
Hello,

I have a situation where I have a link to an archive listing multiple times on a page, this causes Gatsby to prefetch the data for the page as many times as the link exists which is duplicate data. 

This causes unnecessary downloading on the user's end.

Is there a recommended approach for this?

Thanks in advance.

**Comment by aengl** [comment]
I noticed the same behaviour on a site I'm working on:

<img width="1033" alt="Screenshot 2019-08-16 at 09 16 34" src="https://user-images.githubusercontent.com/5022924/63150261-9eea4200-c006-11e9-81c3-5e97df76e5f3.png">

Every image here links to the same page using `Link`, but with a different fragment. I resolved it by using regular anchor tags for all but one link, but it's certainly unexpected.

**Comment by aengl** [comment]
I looked into the source a bit.

`gatsby-link` enqueues the prefetches via an intersection observer here: https://github.com/gatsbyjs/gatsby/blob/883db9aaeef87d656e15c41954ccf606dea18715/packages/gatsby-link/src/index.js#L89-L91

That calls this prefetch method: https://github.com/gatsbyjs/gatsby/blob/b8e2adc6956ae01fa3a94c23debf010e3775d322/packages/gatsby/cache-dir/loader.js#L238-L241

`shouldPrefetch` doesn't make any attempts at caching the paths and preventing multiple prefetches as far as I can tell.

**Comment by aengl** [comment]
@dannybarinshtein Multiple prefetches won't cause multiple downloads:

<img width="462" alt="Screenshot 2019-08-16 at 09 53 00" src="https://user-images.githubusercontent.com/5022924/63152266-b7109000-c00b-11e9-9087-570b732edd1c.png">

Note that subsequent page-data requests are served from cache. So I think this issue is mostly cosmetic, and I'm more concerned about the performance hit from the DOM manipulation.

**Comment by dannybarinshtein** [comment]
@aengl Subsequent page data requests are served from the cache, but a performance tool such as Google Insights counts each one as additional data downloaded and adds it to the total size of network payloads.

These metrics could affect SEO rankings to a degree as per the following change last year https://webmasters.googleblog.com/2018/01/using-page-speed-in-mobile-search.html as this tool is one of the mentioned in the article.

I have also confirmed that disabling prefetches boosts insights score by a significant amount:

`export const disableCorePrefetching = () => true`

However such an approach is not really viable, as it would remove a great feature of Gatsby.

**Comment by dannybarinshtein** [comment]
@aengl I am also noticing that in my case there is a slightly different behaviour.

My subsequent request is not actually an XHR, but JSON data coming from prefetch.js which is not coming from cache.

<img width="832" alt="Screen Shot 2019-08-25 at 1 23 24 PM" src="https://user-images.githubusercontent.com/40195547/63648701-3bfe5680-c73c-11e9-8488-8f53e8916805.png">
