### ISSUE TITLE
[docs] `reporter` docs don't explain when to use it over console.log etc

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#15898]
## Summary

[docs] `reporter` docs don't explain when to use it over console.log etc

## Relevant information

when do i want `panicOnBuild` vs `panic`?

Edit: Also need to document upcoming activities after structured logs are published

**Comment by sw-yx** [comment]
nice docs issue to keep open

**Comment by dcastil** [comment]
Just want to mention it in case anyone is searching for an answer like me.

`panic` always logs the data, exits and fails the process. `panicOnBuild` logs the data and only exits and fails the process when the `gatsby build` command is running.

Source: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/reporter/index.js#L53-L65

**Comment by sw-yx** [comment]
hmm. sounds like it should be callled panicDuringBuild? thanks for investigating!

**Comment by balibebas** [comment]
Not knowing which one of `panicOnBuild` or `panic` is more appropriate to use in a certain context is what led me here. And [it seems](https://github.com/gatsbyjs/gatsby/issues/15898#issuecomment-538543812) I'm not alone:

> `panic` always logs the data, exits and fails the process. `panicOnBuild` logs the data and only exits and fails the process if the `gatsby build` command is running.

I saw `panicOnBuild` [was used](https://www.gatsbyjs.org/blog/2017-07-19-creating-a-blog-with-gatsby/) in some of the Gatsby posts written by Dustin Schau back in mid-2017. In Dustin's example `panicOnBuild` was used in the context of reporting an error when `createPages` failed.

In my limited experience with Gatsby I've seen projects skip use of `reporter` and it's methods entirely. Given the importance of `gatsby-node` I'm surprised I haven't been able to find a blog post or two about how using one over the other burned someone. Oh well, maybe it'll be mine in the future. :sweat_smile:

**Comment by blainekasten** [comment]
I'll throw in a quick response here. I understand that it's not super clear here.. 

Here is the basics:

1. We patch console.log, console.info, and console.error to flow through our reporter. So you can use them and it'll work just like any reporter call.
1. The reporter has some more fancy possibilities, like phantom activities, progress bars and timers. You can use them however you want.

Our reporter was typically treated as an internal implementation, but we did expose it in things like gatsby-node to allow for users to do fancier things if they want. In my opinion, most apps won't need anything fancy from reporter and can just use console.* for any debug/messaging needs.

Fun to note - `console.debug` does not flow through reporter. So you can use that if reporter is accidentally swallowing output.

I'll ping @AishaBlake to see if she wants to get this into our docs
