### ISSUE TITLE
Layouts with graphql queries

### ISSUE THREAD

**Issue by Deathstroke5467** [gatsbyjs/gatsby#1589]
Would be awesome to try to get GraphQL queries on layouts. This way the title, author, etc. could be quickly updated in the gatsby-starter-blog for example. Where as right now you have to change the title in multiple places, with queries on layouts you could simply change the title once and it would update everywhere.

Current solutions is to make a component that can fetch this data and push it into the layout which somewhat defeats the new GraphQL design which is supposed to be a 'pull'  not 'push' system.

**Comment by amirhouieh** [comment]
Same thought here. Just faced it.

**Comment by craig-mulligan** [comment]
@amirhouieh, @Deathstroke5467 this should be added with #1503
