### ISSUE TITLE
How to apply Link's activeStyle when URL ends with a trailing slash?

### ISSUE THREAD

**Issue by moroshko** [gatsbyjs/gatsby#15893]
When I load a URL that has a trailing slash, `Link`'s `activeStyle` isn't applied.
Repro [here](https://github.com/moroshko/gatsby-active-link-issue).
What's the best way to deal with this?

**Comment by grantmoran** [comment]
Adding [gatsby-plugin-remove-trailing-slashes](https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/) plugin should resolve this in production in most cases.

Live example I pushed to Netlify [https://hungry-fermi-93cbb9.netlify.com/]( https://hungry-fermi-93cbb9.netlify.com/). If you are heading in the Netlify direction you might want to also checkout out their  [documentation](https://www.netlify.com/docs/redirects/#trailing-slash) on the issue as well.

Additional resources I've found helpful in the past:

[Gatsby Docs](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#removing-trailing-slashes)
[.htaccess plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-htaccess/?=hta)
[Article on htaccess and redirects ](https://www.danielmorell.com/guides/htaccess-seo/redirects/https-www-and-trailing-slash) (lots of good info here)

Cheers.

**Comment by moroshko** [comment]
@grantmoran Thanks for all this info!

From what I can see in the docs, `gatsby-plugin-remove-trailing-slashes` and also [this](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#removing-trailing-slashes) is intended to remove trailing slashes from paths generated by Gatsby itself, which is not my case.

I use ZEIT's `now`, so Netlify and `.htaccess` stuff is not very helpful.

**Comment by moroshko** [comment]
If anyone else is using ZEIT's `now`, there are some attempts to address this [here](https://spectrum.chat/zeit/now/how-do-i-redirect-all-trailing-slash-urls-without-in-the-best-way-for-all-my-rotes-using-static-hosting-on-now~713d2c70-8167-4836-aa3f-fcc205bafe56).
