### ISSUE TITLE
[Docs] Graphql query does not return remark data for plugin gatsby-source-prismic-graphql

### ISSUE THREAD

**Issue by hypervillain** [gatsbyjs/gatsby#15900]
## Description

[This page](https://www.gatsbyjs.org/packages/gatsby-source-prismic-graphql) is not displaying any README information. When inspecting the query, you can see that NPM does not properly return the README data.

### Steps to reproduce

Go to https://www.gatsbyjs.org/packages/gatsby-source-prismic-graphql, the page should not be displayed properly.

### Expected result

I expect to view the README content form NPM

### Actual result

GraphQL query does not return remark data

### Environment

Web

**Comment by m-allanson** [comment]
Thanks @hypervillain! This should be fixed by https://github.com/gatsbyjs/gatsby/pull/16322. Let me know if that's not the case.
