### ISSUE TITLE
gatsby@^2.13.9 ERROR #85901... Duplicated documents: PagesQuery

### ISSUE THREAD

**Issue by datakurre** [gatsbyjs/gatsby#15917]
## Description

After upgrading gatsby@2.13.8 on a working build to gatsby@2.13.9 (or 2.13.31),  `gatsby develop` outputs the following error during build:

```
success update schema - 0.063 s

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
- PagesQuery

success extract queries from components - 27.823 s
```

`gatsby build` runs without errors, but does output the following warning:

```
success update schema - 0.065 s
warn The GraphQL query in the non-page component
"/.../node_modules/gats
by/dist/internal-plugins/dev-404-page/raw_dev-404-page.js" will not be run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — http://graphql.org/learn/queries/#fragments
success extract queries from components - 28.347 s
```

I'm sorry for being unable to provide an example project yet. If this is not trivial regression, I could try to do one.

### Environment

```

  System:
    OS: Linux 5.1 NixOS 19.03.173068.9ec7625cee5 (Koi) 19.03.173068.9ec7625cee5 (Koi)
    CPU: (4) x64 Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz
    Shell: 4.4.23 - /nix/store/93h01q6yg13xdrabvqbddzbk11w6a928-bash-interactive-4.4-p23/bin/bash
  Binaries:
    Node: 10.15.3 - /run/user/1000/yarn--1563566224038-0.43010443538950893/node
    Yarn: 1.13.0 - /run/user/1000/yarn--1563566224038-0.43010443538950893/yarn
    npm: 6.4.1 - /nix/store/ll4pkaa7ajycqippwp47yypqy5b3x58h-nodejs-10.15.3/bin/npm
  Languages:
    Python: 3.7.3 - /nix/store/gyffk0z9rwcdl1l1654z3b0sry98ddrk-python3-3.7.3/bin/python
  Browsers:
    Firefox: 67.0.4
  npmPackages:
    gatsby: 2.13.9 => 2.13.9 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-sass: ^2.1.3 => 2.1.3 
    gatsby-plugin-sharp: ^2.2.8 => 2.2.8 
    gatsby-source-filesystem: ^2.1.5 => 2.1.5 
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4 
```

**Comment by wardpeet** [comment]
Mmh this is weird, could you try running `gatsby clean` and see if it still persists?

**Comment by datakurre** [comment]
It does persists and I can reproduce this for my project. If no one has really not seen this, I'll try to provide a minimal example.

**Comment by datakurre** [comment]
The error during `gatsby develop` seems to come from `.cache/dev-404-page.js` and `node_modules/gatsby/dist/internal-plugins/dev-404-page/raw_dev-404-page.js` having the same PagesQuery. There's probably something in my project setup that causes that, but it still strange that it starts only from `gatsby@2.13.9`.

**Comment by datakurre** [comment]
This seems to be caused by my project structure where I have a gatsby source plugin in the top directory and an example site in the subdirectory of that plugin. I get the error when trying to build the example site in the subdirectory. If I move the example site out of the source plugin directory, it builds without issues. Still, this did not happen prior gatsby@2.13.9.

Continuing to figure out a minimal example...

**Comment by datakurre** [comment]
I think, I'll accept this as an issue of my unsupported package setup and close this.

As a postmortem:

I have a source plugin that has an example gatsby site project inside its repository for automated end-to-end acceptance testing of the plugin.

Before gatsby@2.13 it was possible to simple use yarn/npm link to use the latest plugin code in the example site project.

After new discovery magic in gatsby@2.13 it was no longer possibly to use gatsby link, but it was still possible to symlink the required files from the source plugin.

After gatsby@2.13.9 even these symlinks stopped working (hence this issue).

I will now refactor my workflows around yalc roundtrips "linking packages" through local releases and does not have the interference of symlinks to all the discovery magic in place.

**Comment by alexlouden** [comment]
I just started seeing this today, running my fork of gatsby (I'm testing my PR #19442) as an alias:

```
  "dependencies": {
    "@bonobolabs/gatsby": "^2.17.12",
    "gatsby": "npm:@bonobolabs/gatsby",
```

>  ERROR #85901  GRAPHQL
> 
> There was an error in your GraphQL query:
> 
> Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
> - PagesQuery

Does anyone have any tips to debug this?

Also "defintitions" has a typo - I couldn't find that string in the gatsby repo, do you know where it comes from?
