### ISSUE TITLE
[themes] linting in gatsby themes

### ISSUE THREAD

**Issue by sonapraneeth-a** [gatsbyjs/gatsby#15914]
## Relevant information

I have setup ```gatsby-plugin-eslint``` in my theme for identifying linting issues. Required plugins necessary for linting are included as dev dependencies in the theme. However, after installing theme from npm, and running ```gatsby develop```, I'm getting ```No ESLint configuration found error```.

Any idea on how to handle linting in themes so that it can be a part of development activity and not for production?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by DSchau** [comment]
@sonapraneeth-a could you provide a [reproduction](https://gatsby.dev/reproduction)?

@LekoArts and myself both use a monorepo and have ESLint configured in the root of the repo, rather than setting it up at the theme level.

As an example, check out [Lennart’s set-up](https://github.com/LekoArts/gatsby-themes/blob/master/package.json#L19)

I think this will work quite well for your use case — but please let me know if this isn’t the case!

**Comment by sonapraneeth-a** [comment]
@DSchau , in the repo provided above, ```gatsby-plugin-eslint``` is not used ```gatsby-config.js```. Is that not required for linting? In my repo, the main issue is due to that plugin and its presence in ```gatsby-config.js```.

[My gatsby-config.js](https://github.com/sonapraneeth-a/gatsby-theme-simple-bio/blob/master/gatsby-theme-simple-bio/gatsby-config.js#L46-L57)

[Starter](https://github.com/sonapraneeth-a/starter-bug)

when running npm install, it complains that ```gatsby-plugin-eslint``` is not available though it is a dependency of ```gatsby-theme-simple-bio.``` When I attempt to fix it, I get ```No ESLint configuration found``` error.

**Comment by sonapraneeth-a** [comment]
@DSchau , 

A question, Is ```gatsby-plugin-eslint``` not required for linting? If yes, then when should that plugin be used?

**Comment by wardpeet** [comment]
https://github.com/sonapraneeth-a/gatsby-theme-simple-bio/blob/master/gatsby-theme-simple-bio/package.json

I don't see gatsby-plugin-eslint as a dependency

**Comment by sonapraneeth-a** [comment]
Hi @wardpeet ,

It was there before but as it was creating I removed it (https://github.com/sonapraneeth-a/gatsby-theme-simple-bio/commit/518cc6be1f0d6099f65b5a75df3d5ba5f202e65d#diff-5ea2cc3858a3de1d3f518aa3f863becf). 

**My question is: will linting work without ```gatsby-plugin-eslint```? If yes, then what is that plugin used for?**

The problem was that with ```gatsby-plugin-eslint``` in ```gatsby-config.js```, it was complaining that ESLint config was missing when installing theme from npmjs (Package: gatsby-theme-simple-bio, Version: 0.1.1).
