### ISSUE TITLE
Handling Error Boundaries In Gatsby

### ISSUE THREAD

**Issue by quetcodesfire** [gatsbyjs/gatsby#15912]
## Summary
I’m currently using a package called `react-error-boundary` to capture errors in my application, log it to a system, and redirect users to another page.  I have simply set up an `errorHandler()` to `console.log()` `errors` and the `componentStack` for now.

Currently, it appears as if errors get caught by Gatsby before they can even be logged by the application.

## Relevant information
You can see the docs for `react-error-boundary` [here](https://github.com/bvaughn/react-error-boundary)

You can find a snippet of my code below:

```
//Layout.js
const errorHandler = (error, componentStack) => {
    console.log(error)
  	console.log(componentStack)
  }

return (
  <ErrorBoundary onError={errorHandler}>
      <div className="error-boundary-example">
        <Navigation />

        <main>{children}</main>

        {footer && <Footer />}
      </div>
  </ErrorBoundary>
)

```

Inside of the `<Navigation />` component that’s wrapped inside of `<ErrorBoundary />` I have run a function that hasn’t been declared called `fakeFunction()` to trigger an error. This error does not get caught when logging `error`. Here is a screenshot of what I’m getting:

[image:52615BD4-BA45-4E0F-8F7E-CD9EDF3D84FB-403-00004EAB16BA4CDE/CF9135C7-D05B-4ED0-B02D-837920672476.png]

### Environment (if relevant)
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.11.0 - ~/.nvm/versions/node/v11.11.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.11.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.13.27 => 2.13.27 
    gatsby-plugin-create-client-paths: ^2.1.3 => 2.1.1 
    gatsby-plugin-manifest: ^2.2.1 => 2.2.1 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0 
    gatsby-plugin-react-leaflet: 2.0.11 => 2.0.11 
    gatsby-plugin-resolve-src: ^2.0.0 => 2.0.0 
    gatsby-plugin-sass: ^2.1.0 => 2.1.0

**Comment by quetcodesfire** [comment]
The screenshot mentioned above (hopefully 🤞🏾):
![image](https://user-images.githubusercontent.com/20568762/61556105-fb216c80-aa2e-11e9-9e0d-356d5f2d5ba4.png)

**Comment by wardpeet** [comment]
ErrorBoundary only catches runtime errors, more info about this topic can be found at https://reactjs.org/docs/error-boundaries.html.

The error you're seeing is an eslint issue which is ran at build time (inside webpack). Which is happening before react is called.

It seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪

**Comment by colbyfayock** [comment]
@wardpeet thoughts on this other example? http://randomtestbucketroot.s3-website-us-east-1.amazonaws.com I set up a quick demo using simple-auth example from the Gatsby repo

if you log in, then go to Details, you'll see an error thrown, which is the big frowny face (I'm guessing that's Gatsby?), and there's no indication that our ErrorBoundary ran, but it seems like Gatsby is catching it within another mechanism (unless im seeing something else).

My example users simple-auth upgraded to latest with the following tweaks:

```
// Layout/index.js

const errorHandler = (error, componentStack) => {
  console.log(error)
  console.log(componentStack)
}

const Layout = ({ children }) => (
  <ErrorBoundary onError={errorHandler()}>
    <div>
      <Helmet title="Simple Authentication With Gatsby" />
      <Header />
      <main className={styles.main}>{children}</main>
    </div>
  </ErrorBoundary>
)```

```
const asdf = 'asdf';

const Details = () => {
  const { name, legalName, email } = getCurrentUser()

  return (
    <View title="Your Details">
      <ul>
        <li>Preferred name: {name}</li>
        <li>Legal name: {legalName}</li>
        <li>Email address: {email}</li>
      </ul>
      { asdf.asdf.asdf }
    </View>
  )
}
```

thoughts?

**Comment by wardpeet** [comment]
can you share your ErrorBoundary class?

**Comment by colbyfayock** [comment]
React Error Boundary: https://github.com/bvaughn/react-error-boundary

**Comment by colbyfayock** [comment]
Sorry nevermind! turns out the :) IS from the library 🤦‍♂
