### ISSUE TITLE
[docs] copy/paste button: leave off diff/multiline shell blocks?

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#15925]
## Summary

For the awesome new copy/paste button in the Gatsby docs, we should discuss how the copy/paste behavior should work for code blocks that need to be digested line-by-line. For diffs, copying the whole block wouldn't make much sense. And for multiline shell commands–particularly where the example includes placeholder text like `[yourrepohere]`–the copy command could create some errors. Maybe it needs a flag to disable for certain types of code blocks?

<img width="780" alt="tutorial with two code blocks" src="https://user-images.githubusercontent.com/1045233/61574404-21b5c680-aa74-11e9-94e4-ea25f0ea56f8.png">

I'd also brought up whether it should look more like a button, since the language tag has button-like appearance and the "Copy" button looks like plain text. But this issue can remain focused on the go/no go behavior for a type of code block. 

@fk @DSchau this issue is meant to help us keep track of this, as I think it will keep coming up as we see IRL usage of the component. Thanks again for shipping that so quickly, it's a great improvement that we can keep iterating on to make it even better!

**Comment by DSchau** [comment]
Unrelated — but wanted to track on it.

I believe it’s also not functioning in Safari. Need to use contenteditable to fix!

**Comment by DSchau** [comment]
@marcysutton I generally get the argument here — but isn’t there an argument to be made for consistency here?

In other words — I could see users being confused if they _don’t_ see a copy button. I think user behavior would be to _use_ the component when they need it—and avoid it when they don’t.

For instance, let’s consider the following shell snippet:

```shell
cd [your-project-name]
gatsby develop
```

If the user _wants_ to get useful data from that snippet, they would copy, paste into a new editor tap or window, and then select what they need. If the copy button isn’t helpful for them in that scenario, they just wouldn’t use it?

I’m not sure 🤷‍♂ I don’t think taking something away is necessarily the best solution. One idea I had would be to make hovering a line show a copy button to copy _just_ that line—but there’s a bit of engineering work to get that done.

**Comment by fk** [comment]
I thought about this a couple of times the past week but never got to comment—sorry!
I'm with Dustin here:

* I'm thinking we are looking at a problem that existed before we added the "Copy" button—either way, just blindly copyiny-and-pasting everything wouldn't always have worked.
* Dustin's argument makes sense to me—I can see users being confused (and annoyed) about the button not being consistently available. While I can also see how the button might increase the potential point of failure for certain users in certain cases—something that is offered to copy could be expected to "just work"—I assume that the majority of our users will benefit from the "Copy" button being consistently present.
* There are multiline blocks where c+p all lines does work, e.g. https://www.gatsbyjs.org/tutorial/part-one/#deploying-a-gatsby-site: ![image](https://user-images.githubusercontent.com/21834/62009452-bd73c080-b15f-11e9-82ec-e159e600e8e4.png)
* IRT to the `cd [your-project-name]` example:
  * _If_ that example (didn't search, so don't have the full context) shows a preceding step (like e.g. [here](https://www.gatsbyjs.org/tutorial/part-zero/#create-a-gatsby-site)), as long as `[your-project-name]` stays consistent, we don't have a problem.
  * If there is that preceding step, I'd argue to remove the square brackets and just go with `your-project-name` (like e.g. [here](https://www.gatsbyjs.org/tutorial/part-one/#using-gatsby-starters))(although `[your-project-name]` does work, at least on OS X).
  * I do understand that we need `[PLACEHOLDERS]` in code examples, like e.g. [here](https://www.gatsbyjs.org/tutorial/part-one/#using-gatsby-starters). I would hope that the context always makes it clear that these are thought to be replaced. Maybe we could add a small "info" (or "warning") icon for code blocks with placeholders—on click, we show a popover that explains them: _This code example contains [PLACEHOLDERS]. Please replace [FOO] with a Gatsby Starter URL […]_ …but maybe this is overthinking, and we just can use comments in the code block to explain them further if we feel the need to?
* Regarding diff code blocks, they seem to be an even better example for such an "info" widget. I can see the need to explain what these type of code blocks are/how they work, and esp. the unexperienced user benefit from such a bit of inline information.
* Dustin's thought about copying individual lines (or blocks of lines, e.g a range of highlighted lines, or a range of additions in a diff block (preferably without the `+ ` 😉… or not 😅)) is interesting!
