### ISSUE TITLE
[gatsby-plugin-mdx] Provide TypeScript typings

### ISSUE THREAD

**Issue by sm1th** [gatsbyjs/gatsby#15924]
## Summary

It'd be nice to have a TypeScript type at least for `MDXRenderer` which is used in code.

<img width="729" alt="Screen Shot 2019-07-19 at 22 58 14" src="https://user-images.githubusercontent.com/3375071/61572752-c6d29e00-aa78-11e9-892e-b57d353b70cd.png">

### Motivation

TypeScript is great. Supporting TypeScript is great!

**Comment by sm1th** [comment]
I will work on creating a pull request for this, but it might take a while due to limited time and lack of experience adding types to a project (although it appears to be simple)

**Comment by rgiese** [comment]
Eh, this shouldn't just go by the wayside. Anyone interested in helping out here?

**Comment by sm1th** [comment]
Thanks for reopening this @rgiese. I don't really have time to work on it but hopefully someone else does.

**Comment by thchia** [comment]
I’m interested in taking this.

**Comment by muescha** [comment]
@thchia you can grab this 👍
