### ISSUE TITLE
I need help creating a relationship between two Gatsby sources

### ISSUE THREAD

**Issue by mrbjjackson** [gatsbyjs/gatsby#15920]
Hi everyone,

So I have two sources loaded into my GraphQL...

Firstly, a list of _Artist_ nodes, coming from a _Contentful_ content model.

This content type contains the _Artist name_, some information about them, and an ID.

Secondly a list of _Track_ nodes automatically imported from a _Spotify playlist_. Each track has a _Track Name_, an _Artist name_ and an ID.

I would like to create a relationship between the _Spotify Tracks_ to the _Contentful Artists_ based on the _Artist name_, when it matches between the two so I can have write some information about an artist on Contentful and then on my website, easily display this info along with a list of their tracks below.

From my reading it looks like I have to use `onCreateNode`. And if the node type is Contentful Artist, use `createNodeField` and do something like `LinkedTracks___NODE = <Spotify Track ID>`

The trouble I'm having is, from within `onCreateNode`, I don't know how to access the information in the Spotify Tracks nodes to work out which tracks have the same Artist as the current Contentful Artist.

I hope that makes sense.

Any help would be much appreciated. Thanks, Ben

**Comment by cluk3** [comment]
https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types
If I understood well that's exactly what you need, right?

**Comment by stefanprobst** [comment]
You could also use the schema customization APIs to [create a foreign-key relation](https://www.gatsbyjs.org/docs/schema-customization/#foreign-key-fields).

**Comment by mrbjjackson** [comment]
Thanks very much for the speedy replies. I'll try them both out.
On first look over it looks like the Mapping solution may not work because the Artist field is not an ID in either the Contentful or Spotify sources. It's just a general field. I'll investigate further.
The foreign-key relation looks very promising.

**Comment by mrbjjackson** [comment]
So I did manage to get this working using the info linked by @stefanprobst .
The code is pretty specific to my needs so may not make sense out of context but I thought I would post it in case it helps anyone else.
```
exports.createSchemaCustomization = ({ actions, schema }) => {
  const { createTypes } = actions
  const typeDefs = [
    `
    #the following three help put the linked artist node into the track node
    type SpotifyTrack implements Node {
      track: Track
    }
    
    type Track{
        artists: [Artist]
    }

    type Artist implements Node {
      artist: [ContentfulArtist] @link(by: "artist", from: "name")
    }

    `
  ]
  createTypes(typeDefs)
}
```

**Comment by stefanprobst** [comment]
Thanks for posting the snippet!
I'm going to close this as answered, but feel free to reopen if anything remains unclear!
