### ISSUE TITLE
Why 404 redirect to main page

### ISSUE THREAD

**Issue by toastyboost** [gatsbyjs/gatsby#15922]
Expected 404 - https://coinrate.com/hello_world, but we see main
In development mode all works fine.
404 pages exist https://coinrate.com/404

```
   'gatsby-plugin-react-helmet',
    'gatsby-plugin-sitemap',
    'gatsby-plugin-no-sourcemaps',
    'gatsby-plugin-eslint',
    'gatsby-plugin-robots-txt',
    'gatsby-plugin-styled-components',
```

**Comment by wardpeet** [comment]
That's weird, where are you hosting coinrate? Also, you're still using an old version of gatsby. Perhaps try to upgrade?
