### ISSUE TITLE
__PREFIX_PATHS_ is undefined in gatsby-link. Question.

### ISSUE THREAD

**Issue by gscopet** [gatsbyjs/gatsby#1592]
This project has been life changing, thanks everyone for your hard work.

In the gatsby-link package, line 6. What would be the correct way to handle this global? I am attempting to create a story w/storybooks with a component that imports gatsby-link. __PREFIX_PATHS__ is undefined and throwing a hard error. I also noticed __PREFIX_PATHS_  != __PATH_PREFIX__ and not sure if that has anything to do with it. 

```
if (__PREFIX_PATHS__) {
  pathPrefix = __PATH_PREFIX__
}
```

Thanks again. I am also open to suggestions on how I can help contribute and fix this if needed.

**Comment by KyleAMathews** [comment]
Gatsby's webpack config sets that variable as a global. There's been talk before of creating a Gatsby plugin for Storybook so Storybook can emulate the Gatsby webpack setup.

**Comment by gscopet** [comment]
Thanks. Ill look out for the plugin.

**Comment by KyleAMathews** [comment]
I don't know if it's actively being worked on so feel free to take it on :-)
