### ISSUE TITLE
Its easy you follow this link https://www.gatsbyjs.org/docs/

### ISSUE THREAD

**Issue by Mohit-Sharma1** [gatsbyjs/gatsby#15935]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by poyea** [comment]
This issue may be incomplete or wrongly opened.
