### ISSUE TITLE
Gatsby build fails on netlify

### ISSUE THREAD

**Issue by DubaniWarrior** [gatsbyjs/gatsby#15930]
I need help to understand what the problem.

The command " dotenv gatsby build" works fine locally. But on netlify it fails with this message: 

failed during stage 'building site': Build script returned non-zero exit code: 1

12:05:39 PM: Build ready to start
12:05:41 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
12:05:41 PM: build-image tag: v3.3.2
12:05:41 PM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
12:05:42 PM: Fetching cached dependencies
12:05:42 PM: Failed to fetch cache, continuing with build
12:05:42 PM: Starting to prepare the repo for build
12:05:42 PM: No cached dependencies found. Cloning fresh repo
12:05:42 PM: git clone https://github.com/DubaniWarrior/wisdom-sagesse
12:05:43 PM: Preparing Git Reference refs/heads/master
12:05:43 PM: Starting build script
12:05:43 PM: Installing dependencies
12:05:45 PM: Downloading and installing node v10.16.0...
12:05:45 PM: Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz...
12:05:45 PM: 
#################################
12:05:45 PM:                              46.3%
12:05:45 PM: 
########################################
12:05:45 PM: ################################ 100.0%
12:05:45 PM: Computing checksum with sha256sum
12:05:45 PM: Checksums matched!
12:05:48 PM: Now using node v10.16.0 (npm v6.9.0)
12:05:48 PM: Attempting ruby version 2.6.2, read from environment
12:05:49 PM: Using ruby version 2.6.2
12:05:50 PM: Using PHP version 5.6
12:05:50 PM: Started restoring cached node modules
12:05:50 PM: Finished restoring cached node modules
12:05:50 PM: Installing NPM modules using NPM version 6.9.0
12:06:22 PM: > sharp@0.22.1 install /opt/build/repo/node_modules/sharp
12:06:22 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
12:06:23 PM: info
12:06:23 PM: sharp
12:06:23 PM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
12:06:25 PM: > core-js@2.6.9 postinstall /opt/build/repo/node_modules/core-js
12:06:25 PM: > node scripts/postinstall || echo "ignore"
12:06:25 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
12:06:25 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
12:06:25 PM: > https://opencollective.com/core-js 
12:06:25 PM: > https://www.patreon.com/zloirock 
12:06:25 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
12:06:25 PM: > core-js-pure@3.1.4 postinstall /opt/build/repo/node_modules/core-js-pure
12:06:25 PM: > node scripts/postinstall || echo "ignore"
12:06:25 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
12:06:25 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
12:06:25 PM: > https://opencollective.com/core-js 
12:06:25 PM: > https://www.patreon.com/zloirock 
12:06:25 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
12:06:25 PM: > gatsby-telemetry@1.1.6 postinstall /opt/build/repo/node_modules/gatsby-telemetry
12:06:25 PM: > node src/postinstall.js
12:06:26 PM: > cwebp-bin@5.1.0 postinstall /opt/build/repo/node_modules/cwebp-bin
12:06:26 PM: > node lib/install.js
12:06:26 PM:   ✔ cwebp pre-build test passed successfully
12:06:26 PM: > mozjpeg@6.0.1 postinstall /opt/build/repo/node_modules/mozjpeg
12:06:26 PM: > node lib/install.js
12:06:27 PM:   ✔ mozjpeg pre-build test passed successfully
12:06:27 PM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
12:06:27 PM: > node lib/install.js
12:06:27 PM:   ✔ pngquant pre-build test passed successfully
12:06:27 PM: > styled-components@4.3.2 postinstall /opt/build/repo/node_modules/styled-components
12:06:27 PM: > node ./scripts/postinstall.js || exit 0
12:06:27 PM: Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
12:06:30 PM: npm WARN
12:06:30 PM:  optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
12:06:30 PM: npm WARN
12:06:30 PM: notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
12:06:30 PM: added 2009 packages from 1056 contributors and audited 35481 packages in 38.895s
12:06:30 PM: found 0 vulnerabilities
12:06:30 PM: NPM modules installed
12:06:30 PM: Started restoring cached go cache
12:06:30 PM: Finished restoring cached go cache
12:06:30 PM: unset GOOS;
12:06:30 PM: unset GOARCH;
12:06:30 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
12:06:30 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
12:06:30 PM: go version >&2;
12:06:30 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
12:06:30 PM: go version go1.12 linux/amd64
12:06:30 PM: Installing missing commands
12:06:30 PM: Verify run directory
12:06:30 PM: Executing user command: gatsby build
12:06:33 PM: success open and validate gatsby-configs — 0.119
12:06:34 PM: success load plugins — 1.373
12:06:34 PM: success onPreInit — 0.013
12:06:34 PM: success delete html and css files from previous builds — 0.016
12:06:34 PM: success initialize cache — 0.019
12:06:34 PM: success copy gatsby files — 0.033
12:06:34 PM: success onPreBootstrap — 0.025
12:06:34 PM: Starting to fetch data from Contentful
12:06:34 PM: Fetching default locale
12:06:34 PM: error
12:06:34 PM: Accessing your Contentful space failed.
12:06:34 PM: Try setting GATSBY_CONTENTFUL_OFFLINE=true to see if we can serve from cache.
12:06:34 PM: Authorization error. Check if accessToken and environment are correct
12:06:34 PM: Used options:
12:06:34 PM: spaceId: "*********lne"
12:06:34 PM: accessToken: "***************************************************************8FEo" - Check if setting is correct
12:06:34 PM: host (default value): "cdn.contentful.com"
12:06:34 PM: environment (default value): "master" - Check if setting is correct
12:06:34 PM: downloadLocal (default value): false
12:06:34 PM: localeFilter (default value): [Function]
12:06:34 PM: forceFullSync (default value): false
12:06:34 PM: See our docs page for more info on this error: https://gatsby.dev/issue-how-to
12:06:35 PM: Skipping functions preparation step: no functions directory set
12:06:35 PM: Caching artifacts
12:06:35 PM: Started saving node modules
12:06:35 PM: Finished saving node modules
12:06:35 PM: Started saving pip cache
12:06:35 PM: Finished saving pip cache
12:06:35 PM: Started saving emacs cask dependencies
12:06:35 PM: Finished saving emacs cask dependencies
12:06:35 PM: Started saving maven dependencies
12:06:35 PM: Finished saving maven dependencies
12:06:35 PM: Started saving boot dependencies
12:06:35 PM: Finished saving boot dependencies
12:06:35 PM: Started saving go dependencies
12:06:35 PM: Finished saving go dependencies
12:06:38 PM: Error running command: Build script returned non-zero exit code: 1
12:06:38 PM: Failing build: Failed to build site
12:06:38 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
12:06:38 PM: Finished processing build request in 56.233021925s

**Comment by wardpeet** [comment]
Can you please fill in the following sections as we need more info on this issue.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
