### ISSUE TITLE
4-part Tutorial

### ISSUE THREAD

**Issue by vilav** [gatsbyjs/gatsby#1593]
Hi there!

Very encouraged to read this: **_"This tutorial is for everyone! You do not need to be a programmer or React.js expert. We'll walk you through things."_**

Any updates on when the rest of the 3 parts get released?

Thanks

**Comment by benjaminhoffman** [comment]
hi @vilav, closing this issue for now.  It appears the add'l tutorial parts have been completed: https://www.gatsbyjs.org/tutorial/

Feel free to re-open if I am mistaken.  Thanks!
