### ISSUE TITLE
How to refresh the localhost https certificate?

### ISSUE THREAD

**Issue by DevinKott** [gatsbyjs/gatsby#15947]
## Summary

I tried following the gatsbyjs local https guide [here](https://www.gatsbyjs.org/docs/local-https/), but I got an error while setting it up. Now, when I try running `npm run develop -- --https`, it does not start because of the error
`UNHANDLED REJECTION request to https://localhost:8000/___graphql failed, reason: unable to verify the first certificate`
## Relevant information

When trying to set up local https, I put in the wrong sudo password a couple of times, and exited the process. Now it's automatically trying to generate certificates on the fly that are wrong and the building/running fails every time.

### File contents (if changed)

`package.json`: N/A 
`"start": "npm run develop -- --https",`

The solution [here](https://github.com/gatsbyjs/gatsby/issues/15441) worked, but firefox/chrome said it was a security risk to visit the localhost website. How can i reset it and try setting up https again?

**Comment by buz-zard** [comment]
I'm having the same issue. I'm trying to upgrade from `"gatsby": "^2.8.2",` to `"gatsby": "^2.13.50",` and the build fails:

```
UNHANDLED REJECTION request to https://localhost:8000/___graphql failed, reason: unable to verify the first certificate



  FetchError: request to https://localhost:8000/___graphql failed, reason: unable to verify the first certificate

  - index.js:1455 ClientRequest.<anonymous>
    [locker-web]/[node-fetch]/lib/index.js:1455:11

  - destroy.js:82 emitErrorNT
    internal/streams/destroy.js:82:8

  - destroy.js:50 emitErrorAndCloseNT
    internal/streams/destroy.js:50:3

  - next_tick.js:63 process._tickCallback
    internal/process/next_tick.js:63:19
```

**Comment by buz-zard** [comment]
For now my workaround is `NODE_TLS_REJECT_UNAUTHORIZED=0 gatsby develop --https`

**Comment by geoffdavis92** [comment]
Would also like to see this looked at. Ran the `--https` command without sudo, now unable to setup a (truly secure) HTTPS connection through Gatsby.

One thing that would be helpful– and I may be able to help with this– is to present a warning on the [`local-https` docs page](https://www.gatsbyjs.org/docs/local-https/) to indicate users should maybe first try this using `sudo` before they run it? At least until this bug is resolved.

**Comment by Bulletninja** [comment]
I simply ran `gatsby develop --https` for the first time in a new project and get a similar error.
```
TypeError: Cannot read property 'replace' of undefined
  
  - develop.js:367 module.exports
    [suscribela]/[gatsby]/dist/commands/develop.js:367:42
  
  
  - next_tick.js:189 process._tickCallback
    internal/process/next_tick.js:189:7
```

**Comment by calsal8** [comment]
Do not stale, please.
