### ISSUE TITLE
Android/iOS app for Gatsby

### ISSUE THREAD

**Issue by bsde1245** [gatsbyjs/gatsby#15948]
## Summary

Android/iOS plugin for Gatsby

### Basic example

No example I can see as of now

### Motivation
Android/iOS apps are great way for promoting any websites

I would like to have a plugin to convert Gatsby site to native android/iOS app

**Comment by wardpeet** [comment]
Supporting multiple platforms is really hard so we focus on the web. Supporting Android/iOS is not something we will support in the near future.

A plugin wouldn't cut it as our runtime is not react-native compatible. Websites can also be "installed" to give a more app like experience. I would suggest having a look at. https://www.gatsbyjs.org/docs/progressive-web-app/

**Comment by magnusarinell** [comment]
You can use gatsby-plugin-offline and publish a TWA app to Google Play

**Comment by thisisGRVTY** [comment]
What about this? https://react-freelancer.ch/blog/build-mobile-apps-using-gatsby-and-capacitor
