### ISSUE TITLE
`gatsby-transformer-remark` update v2.6.0 breaks `gatsby-remark-prismjs` line-numbering

### ISSUE THREAD

**Issue by miraicoding** [gatsbyjs/gatsby#15953]
## Description

`gatsby-transformer-remark` update from v2.5.0 to v2.6.0 breaks `gatsby-remark-prismjs` line-numbering when specified in a Markdown file using the syntax:
```
```javascript{numberLines: true}
```
### Steps to reproduce

Following instructions in:
https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/

Add line numbering option.

In a Markdown file, add following code:
```
```jsx{5-8}{numberLines: true}
// During first render
function Counter() {
  // ...
  useEffect(
    // Effect function from first render
    () => {
      document.title = `You clicked ${0} times`
    }
  )
  // ...
}
\```
```

### Expected result

Line numbers should appear in rendered blog page.
Identified that it works in `gatsby-transformer-remark` version 2.5.0.

![image](https://user-images.githubusercontent.com/50406051/61591394-69b62400-ac01-11e9-95f8-df8fdddfd70d.png)

Relevant part of `package.json`:
```
  "dependencies": {
    "gatsby": "^2.13.25",
    "gatsby-cli": "^2.7.17",
    "gatsby-plugin-typography": "^2.3.2",
    "gatsby-remark-prismjs": "^3.3.3",
    "gatsby-source-filesystem": "^2.1.5",
    "gatsby-transformer-remark": "2.5.0",
    "prismjs": "^1.16.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-typography": "^0.16.19",
    "typeface-merriweather": "0.0.72",
    "typeface-montserrat": "0.0.75",
    "typography": "^0.16.19",
    "typography-theme-wordpress-2016": "^0.16.19"
  },
```

### Actual result

Line numbers do **not** appear in rendered blog page.
Updating to `gatsby-transformer-remark` version 2.6.0, keeping everything else the same, causes the bug.

![image](https://user-images.githubusercontent.com/50406051/61591424-be599f00-ac01-11e9-9aa3-4899e18e7f56.png)

Relevant part of `package.json` file:
```
  "dependencies": {
    "gatsby": "^2.13.25",
    "gatsby-plugin-typography": "^2.3.2",
    "gatsby-remark-prismjs": "^3.3.3",
    "gatsby-source-filesystem": "^2.1.5",
    "gatsby-transformer-remark": "2.6.0",
    "prismjs": "^1.16.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-typography": "^0.16.19",
    "typeface-merriweather": "0.0.72",
    "typeface-montserrat": "0.0.75",
    "typography": "^0.16.19",
    "typography-theme-wordpress-2016": "^0.16.19"
  },
```

### Environment

macOS Mojave (version 10.14.5) on iMac (Late 2014).
node v12.6.0
npm v6.10.1

**Comment by wardpeet** [comment]
Seems like we found our first bug for upgrading remark https://github.com/gatsbyjs/gatsby/pull/15348.

Thanks for reporting, we'll need to investigate.
