### ISSUE TITLE
gatsby-plugin-material-ui ssr styling order

### ISSUE THREAD

**Issue by deltaskelta** [gatsbyjs/gatsby#15954]
## Description

Using the gatsby-plugin-material-ui following the example, I get styles that are ssr rendered that supercede my applied styles (which are based on screen width and stored in state). If I navigate directly to a page that was SSR rendered, I have to trigger a state change in order to get the correct styles. This only happens in production build obviously.

### Steps to reproduce

1. clone and build https://github.com/deltaskelta/deltaskelta.github.io.src/tree/test (I have removed most posts to make the build faster)

2. `gatsby serve`
3. navigate to `http://localhost:9000/blog/reinforcement-learning/2-finite-markov-decision/`
4. set chrome to mobile view 
5. refresh page to see content disappear
6. go to the hamburger menu > sections > blog then click on the markov decision post again 
7. see the correct styles applied. 

### Expected result

styles based on my state should be rendered over SSR styles

### Actual result

SSR styles are rendered until some state changed and component re-rendering happens. I was able to create a hotfix by using the material-ui `<NoSsr>` component, but this is just a stop gap measure until I can figure out what is going on.

### Environment

```

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 3.7.4 - /Users/Jeff/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 62.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.0.64 => 2.13.32 
    gatsby-image: ^2.0.26 => 2.2.6 
    gatsby-link: ^2.0.7 => 2.2.2 
    gatsby-plugin-google-analytics: ^2.0.9 => 2.1.4 
    gatsby-plugin-material-ui: ^2.1.4 => 2.1.4 
    gatsby-plugin-mdx: ^1.0.14 => 1.0.15 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.1.2 
    gatsby-plugin-sharp: ^2.0.17 => 2.2.8 
    gatsby-plugin-typescript: ^2.0.3 => 2.1.2 
    gatsby-remark-images: ^3.0.1 => 3.1.7 
    gatsby-remark-katex: ^3.1.2 => 3.1.2 
    gatsby-source-filesystem: ^2.0.11 => 2.1.5 
    gatsby-transformer-sharp: ^2.1.10 => 2.2.4 
```

**Comment by deltaskelta** [comment]
I'm not sure if I understand this correctly, but I think this might be a bug within React 16 itself...

https://github.com/facebook/react/issues/13260. The solution mentioned in this related thread  https://github.com/gatsbyjs/gatsby/issues/14601 worked for me (although it causes a noticeable double render) 

Maybe someone who has deeper knowledge of JSS and SSR could interpret this? I kind of just fumble with them until they work

**Comment by hhimanshu** [comment]
Did you happen to know the issue? and how you fixed it? It seems I am going through the same pain right now
