### ISSUE TITLE
How to define graphql structure on createNode

### ISSUE THREAD

**Issue by vavra7** [gatsbyjs/gatsby#15951]
I use custom source plugin where I call an external API which returns me for example following data:

```
[
  {
    "id": "1",
    "name": "menu1",
    "items": [
      {
        "label": "Home",
        "slug": "home",
        "url": "http://home.com"
      },
      {
        "label": "About Me",
        "slug": "about-me",
        "url": "http://home.com/about-me"
      }
    ]
  },
  {
    "id": "2",
    "name": "menu2",
    "items": []
  }
]
```
Then I use  sourceNodes API to create node with type `menu`. After that I can query for my data in components like this:

```
query menu {
  menu(id: {eq: 1}) {
    id
    name
    items {
      label
      url
    }
  }
}
```
BUT my external API can returns me also these data:

```
[
  {
    "id": "1",
    "name": "menu1",
    "items": []
  }
]
``` 
Which means that Gatsby crashes on querying non-existing fields `label` and `url` because  Gatsby could never know about such fields.

So my question is how can I define the structure of node with all expecting fields? Or how is it possible deal with this situation?

Thanks for help in advance!

**Comment by wardpeet** [comment]
You can create type definitions and resolvers using our new graphql APIs https://www.gatsbyjs.org/blog/2019-03-18-releasing-new-schema-customization/. With the [createTypes](https://www.gatsbyjs.org/docs/actions/#createTypes) action, you can create your own definition.

If you share your gatsby-node.js file we might be able to assist you better.

**Comment by vavra7** [comment]
Wonderful! I just tested it and your links helped lot! It works exactly I need. Thank you!
