### ISSUE TITLE
Google mobile friendly test

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#15960]
When i test my page on https://search.google.com/test/mobile-friendly 

I get message like "Can't load 25 ... "  for pages (.../page-data.json):  

http://...../page-data.json   | Type XHR | Other error 
.... 

When i manually open this pages, they are loaded ok and it is valid json. 

What can be wrong?

**Comment by wardpeet** [comment]
Could you share your url or mobile-friendly results to see what's happening?
