### ISSUE TITLE
(gatsby-themes) gatsby-link best practive when developing theme

### ISSUE THREAD

**Issue by jordanoverbye** [gatsbyjs/gatsby#15970]
So I'm developing a gatsby-theme and have a question about styling links from gatsby-link. With Theme UI, you can easily have:

```
<Styled.a href="/">Home</Styled.a> 
```

This is great because styles will automatically be applied from you theme. I'm trying to figure out how you can do this but using `gatsby-link` instead of just an anchor tag.

**Comment by lannonbr** [comment]
In Theme UI, you can use as described in the docs for the [Styled component](https://theme-ui.com/styled#changing-the-html-element-or-component), you can use a `as` prop to tell the component what to render as.

So if you wanted to use the anchor tag styles for a gatsby link, you could do something like the following:

```jsx
<Styled.a as={Link} to="/">Home</Styled.a>
```

**Comment by jordanoverbye** [comment]
Thank you @lannonbr! Really appreciate it.
