### ISSUE TITLE
Gatsby v2 with i18next build with Error: Promise resolver null is not a function

### ISSUE THREAD

**Issue by yipsama** [gatsbyjs/gatsby#15985]
## Description
I am trying to intergrate my Gatsby v2 project with i18next. But after solving many issues, it failed on gatsby build process. 

### Steps to reproduce
The whole project is based on gatsby-default-starter and i18next part is based on gatsby-starter-i18next (https://github.com/jb-san/gatsby-starter-i18next).
Since xmlhttprequest contains too many issues for React, I have switched axios for i18next-xhr-backend ajax in its init config.

### Expected result
Gatsby build should success.

### Actual result
C:\Users\***\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: Promise resolver null is not a function
    at new Promise (<anonymous>)
    at exports.default._receive (\node_modules\jest-worker\build\worker.js:185:19)
    at ChildProcess.emit (events.js:197:13)
    at emit (internal/child_process.js:834:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

### Environment
The dependencies I have used in package.json
"dependencies": {
    "axios": "^0.19.0",
    "fs-extra": "^8.1.0",
    "gatsby": "^2.13.32",
    "gatsby-image": "^2.2.6",
    "gatsby-plugin-copy-files": "^1.0.3",
    "gatsby-plugin-i18next": "^1.1.7",
    "gatsby-plugin-manifest": "^2.2.3",
    "gatsby-plugin-offline": "^2.2.4",
    "gatsby-plugin-react-helmet": "^3.1.2",
    "gatsby-plugin-sharp": "^2.2.8",
    "gatsby-source-filesystem": "^2.1.5",
    "gatsby-transformer-sharp": "^2.2.4",
    "i18next": "^17.0.6",
    "i18next-browser-languagedetector": "^3.0.1",
    "i18next-sync-fs-backend": "^1.1.1",
    "i18next-xhr-backend": "^3.0.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1",
    "react-i18next": "^10.11.4"
  }

Run `gatsby info --clipboard` in your project directory and paste the output here.
$ gatsby info --clipboard
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  Binaries:
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.2 - /c/Python37/python
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.13.32 => 2.13.32
    gatsby-image: ^2.2.6 => 2.2.6
    gatsby-plugin-copy-files: ^1.0.3 => 1.0.3
    gatsby-plugin-i18next: ^1.1.7 => 1.1.7
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.8 => 2.2.8
    gatsby-source-filesystem: ^2.1.5 => 2.1.5
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4

**Comment by FLam1992** [comment]
in my case I have switched **local** translation files for i18next-xhr-backend to send them from server to client. 
To allow text changes on the fly without releasing the website each and everytime.

OS: Ubuntu 18.04 LTS

```javascript
.../node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Promise resolver null is not a function
    at new Promise (<anonymous>)
    at exports.default._receive (/home/lam/pinuts/bvv-kundenportal/reactApp/node_modules/jest-worker/build/worker.js:185:19)
    at ChildProcess.emit (events.js:188:13)
    at emit (internal/child_process.js:828:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```


```javascript
"dependencies": {
        "gatsby": "^2.13.46",
        "gatsby-image": "^2.2.8",
        "gatsby-plugin-csp": "^1.1.3",
        "gatsby-plugin-manifest": "^2.2.4",
        "gatsby-plugin-matomo": "^0.7.2",
        "gatsby-plugin-offline": "^2.2.4",
        "gatsby-plugin-react-helmet": "^3.1.2",
        "gatsby-plugin-sass": "^2.1.4",
        "i18next": "^17.0.7",
        "i18next-xhr-backend": "^3.0.0",
        "prop-types": "^15.7.2",
        "react": "^16.8.6",
        "react-feather": "^2.0.3",
        "react-helmet": "^5.2.1",
        "react-i18next": "^10.11.4",
        "react-router-dom": "^5.0.1",
        "react-scripts": "^3.0.1",
        "react-transition-group": "^4.2.1"
         ... and some more ~
}
```

Thanks in advance :)

**Comment by FLam1992** [comment]
@yipsama could you find any solution?
BTW is it possible for you to change the **_Labels_** to **_BUG_** to get some attention?

**Comment by karlromanowski** [comment]
I was able to get a working build by adding:

`react: {
        useSuspense: false
    },`

to i18next.init()

**Comment by slorber** [comment]
also have something similar here, not sure it's the same issue but looks like: https://github.com/gatsbyjs/gatsby/issues/16141
