### ISSUE TITLE
gatsby-plugin-sitemap GraphQL context fail on Netlify

### ISSUE THREAD

**Issue by Kosai106** [gatsbyjs/gatsby#15982]
## Description

Related comment: https://github.com/gatsbyjs/gatsby/issues/15860#issuecomment-512903591

I'm attempting to build a sitemap using only published pages, however the plugin suddenly started causing our Netlify builds to fail and no changes I seem to make will solve this.

#### Gatsby-config example:

```js
{
  resolve: 'gatsby-plugin-sitemap',
  options: {
    query: `
      {
        site {
          siteMetadata {
            siteUrl
          }
        }

        allSitePage {
          edges {
            node {
              path
              context {
                published
              }
            }
          }
        }
    }`,
    serialize: ({ site, allSitePage }) => {
      const pages = [];
      allSitePage.edges.map(({ node }) => {
        if (node.context.published) {
          pages.push({
            url: site.siteMetadata.siteUrl + node.path,
            changefreq: 'daily',
            priority: 0.7,
          });
        }
        return false;
      });
      return pages;
    },
  },
}
```

I should note that I also tried doing the following, but with the same results. (It was suggested somewhere else)

```js
serialize: ({ site, allSitePage }) => {
  const data = JSON.stringify(allSitePage, null, 2);
  const pages = [];
  JSON.parse(data).edges.map(({ node }) => {
    if (node.context.published) {
      pages.push({
        url: site.siteMetadata.siteUrl + node.path,
        changefreq: 'daily',
        priority: 0.7,
      });
    }
    return false;
  });
  return pages;
}
```

### Expected result

The sitemap should be build, only including the pages that contain a truthy `context.published` value.

### Actual result

Netlify refuses to finish the build due to `Error: Cannot query field "context" on type "SitePage"` on the GraphQL request.

### Environment

Netlify (Ubuntu Xenial 16.04) (default)

**Comment by zencephalon** [comment]
Could we see your gatsby-node.js to see how the "context.published" value gets added to your site pages? I assume U do that in your `createPages` somewhere, perhaps?

**Comment by Kosai106** [comment]
@zencephalon  Of course, sorry I should have included this.

I'm querying Firebase Firestore to generate pages based on what we have in our database. It includes things like `slug`, `published` and so forth.

```js
exports.createPages = async ({ actions }) => {
  const { createPage } = actions;

  // Page generation
  const Template = path.resolve('src/templates/index.js');
  const firestore = new Firestore();
  await firestore
    .collection('pages')
    .get()
    .then(snapshot => {
      snapshot.forEach(doc => {
        const node = doc.data();
        if (node.published)
          createPage({
            path: node.slug,
            component: Template,
            context: {
              ...node,
            },
          });
      });
    });
};
```

**Comment by stefanprobst** [comment]
Does the `allSitePage` query work locally in dev when you paste it in the Graph_i_ql explorer?
Do you see any type mismatch warnings during bootstrap?

**Comment by Kosai106** [comment]
@stefanprobst Everything works just fine locally, both the bootstraping and in the explorer, which is why I'm slightly confused.

I should note that I got it working on the very first initial commit, but any commits since are failing because of this.

**Comment by stefanprobst** [comment]
@Kosai106 
hmm weird.

Here's what we know:
* the error message indicates that there is no `context` field on the `SitePage` type.
* it should be inferred in the "update schema" step, but apparently does not.
* one reason for this could be that there are type inference mismatches on context fields (which is why i asked about such warning messages). my guess would be that this is what's happening since you are spreading the whole node on context

First thing to try: provide explicit type definitions for `SitePage`, and either explicitly define all `context` fields you need in the schema, or just make it `JSON` type
```js
// gatsby-node.js
exports.sourceNodes = ({ actions }) => {
  actions.createTypes(`
    type SitePage implements Node @dontInfer {
      buildTime: Date
      path: String
      context: SitePageContext # or maybe just JSON
    }
    type SitePageContext {
      published: Boolean
      # other fields that should be available for querying
    }
  `)
}
```

**Comment by Kosai106** [comment]
@stefanprobst I gave your solution a go and it seems to be working. However, I'm fairly sure this is no longer a Gatsby issue, but a Netlify issue - As I'm getting two builds for each of my commits, with only one of them succeeding (of course not the one used for the git checks).

I'm at a loss for words.

<img width="1184" alt="Screenshot 2019-08-05 at 13 40 06" src="https://user-images.githubusercontent.com/6379824/62462063-b7489a00-b786-11e9-8491-a0323d9fde6d.png">

**Comment by wardpeet** [comment]
Thank you for opening this, @Kosai106

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by Kosai106** [comment]
Thanks @wardpeet, sadly I don't have any new information as of now. The problem described in my previous comment still remains, but I'll reopen this issue once I give this another shot.
