### ISSUE TITLE
missing resources for / 

### ISSUE THREAD

**Issue by mark-mansfield** [gatsbyjs/gatsby#15998]
## Description

when i build  and serve locally my site works fine
deployed to  amazon i get  Missing resources for / error message 

deployed to git hub ghpages

I get 404's for some resources

### Steps to reproduce

my amazon deployment
http://gatsby-brown-sugar-website.s3-website-ap-southeast-2.amazonaws.com

my ghpages deployment
https://mark-mansfield.github.io/gatsby-brown-sugar-website/

### Expected result

I expect the deployed sites on both servers to load error free

### Actual result

both deployments loaded with missing resources errors

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @
3.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.4.0 - /usr/local/bin/node
    npm: 6.1.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 67.0.2
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.3.3 => 2.3.3
    gatsby-background-image: ^0.2.8-alpha4 => 0.2.74
    gatsby-image: ^2.0.35 => 2.0.35
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.11
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32
    gatsby-source-filesystem: ^2.0.28 => 2.0.28
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17
  npmGlobalPackages:
    gatsby-cli: 2.6.7
    gatsby: 2.9.4

**Comment by wardpeet** [comment]
You're on a pretty old gatsby version. Can't really tell why it's failing. Are you sure all resources got uploaded?

**Comment by mark-mansfield** [comment]
On both deployments i can see the missing files in the file lists of both respective platforms. I am going to update my gatsby and see if it persists.

**Comment by mark-mansfield** [comment]
no change after updating to gatsby cli 2.7.17

**Comment by mark-mansfield** [comment]
After starting a new project, and putting all my components in etc ,
then running a build i get 2 errors that say there are missing files 
(sync-requires.js , match-paths.json) in the .cache folder. after browsing the files in .cache i see that the indicated files are actually there. 

here is a sample of the error messages

Error: ENOENT: no such file or directory, open '/Users/markmansfield/Desktop/gatsby_tests/test-latest-gats
by/.cache/sync-requires.js'

also same error for 'match-paths.json'

**Comment by mark-mansfield** [comment]
To try and diagnose this further I read up on the files that were being called out in earlier example
match-paths.json and sync-requires.js but was only able to glean the parts the play in the build process.

So tried a new project

Steps to reproduce
1:  gatsby new build-test
2: npm install gh-pages
3 I created a new github repo
4 commited the project
5 npm run deploy (my build and deploy script)

even the starter project was demonstrating the same issue.

package.json
 homepage URL and scripts

"homepage": "https:/mark-mansfield.github.io/gatsby-build-test",
"scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write src/**/*.{js,jsx}",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\"",
    "deploy": "gatsby build --prefix-paths && gh-pages -d public"
  },


test repo here
https://github.com/mark-mansfield/gatsby-build-test

example here:
https://mark-mansfield.github.io/gatsby-build-test/

environment details:
System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.4.0 - /usr/local/bin/node
    npm: 6.1.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 67.0.2
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.13.36 => 2.13.36
    gatsby-image: ^2.2.6 => 2.2.6
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4
  npmGlobalPackages:
    gatsby-cli: 2.7.17
    gatsby: 2.9.4

I am at a loss..

**Comment by mark-mansfield** [comment]
fixed the problem. Missing pathPrefix in gatsby config was the culprit
