### ISSUE TITLE
default exporting a remark plugin doesn't seem to work

### ISSUE THREAD

**Issue by MichaelDeBoey** [gatsbyjs/gatsby#15991]
## Description
When I use `export default` in the main file of my plugin ([`gatsby-remark-embedder`](https://github.com/MichaelDeBoey/gatsby-remark-embedder)), it's not running.
When I [use `module.exports`](https://github.com/MichaelDeBoey/gatsby-remark-embedder/commit/5e012208a164176d3b919e69895f400c47624b03) it does.

Since the migration guide does say that [ES6 is supported](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#convert-to-either-pure-commonjs-or-pure-es6), I can't figure out why it breaks when using `export default`.

### Expected result
The links should be transformed

### Actual result
The links aren't transformed

**Comment by stefanprobst** [comment]
I think the ESM support in the migration docs refer to the client side of things, i.e. how you import stuff into your components?
The `gatsby-transformer-remark` plugin and its subplugins run in a NodeJS environment, so best to use commonjs there.

**Comment by MichaelDeBoey** [comment]
not stale

**Comment by trevorblades** [comment]
I'm still noticing this issue @gatsbybot @MichaelDeBoey. Trying to use `gatsby-remark-embedder` and it'll only work if i change `exports.default` to `module.exports` in the plugin within `node_modules`.
