### ISSUE TITLE
A Showcase Issue

### ISSUE THREAD

**Issue by dsslimshaddy** [gatsbyjs/gatsby#1600]
For people to submit their websites created using gatsby and if willing then source too.

**Comment by KyleAMathews** [comment]
I'd love for there to be a showcase page on gatsbyjs.org. Would love for people to start adding sites here and then we'll move them over to the website once that feature is built.

**Comment by benjaminhoffman** [comment]
Thanks for the suggestion @dsslimshaddy!  Closing this issue for now as we have included this in the README and will likely expand on it in the near future. https://github.com/gatsbyjs/gatsby#showcase
