### ISSUE TITLE
Is it possible to exclude path prefix on assets (apply only to in-app routing links)

### ISSUE THREAD

**Issue by crhistianramirez** [gatsbyjs/gatsby#16009]
## Summary
We have a somewhat unique hosting scenario where our website is composed of two applications. We have our web app at the root, this is a non-static site in react. Then we have our gatsby static site on /documentation. To achieve this we output the entire contents of `gatsby build` (including the index.html) into a documentation folder at the root. Azure automagically hosts it off `/documentation`. Everything works *except* in-app routing. 

Is there some mechanism we can tap into to update *just* the routeable paths while keeping assets paths untouched? Assets relative to the index are exactly where they should be, so we don't need assets updated just the links in-app.

## Relevant information
I've looked at the documentation on [pathPrefix](https://www.gatsbyjs.org/docs/path-prefix/) and [assetPrefix](https://www.gatsbyjs.org/docs/asset-prefix/). `pathPrefix` prefixes every url in the app *including* assets. I was hoping setting assetPrefix to an empty string would do what I want but it looks like the asset prefix is in addition to any `pathPrefix` value.

**Comment by xavivars** [comment]
Based on what I understood with your setup, everything is actually inside a `documentation` directory (both assets and HTML), right? So why do you need your assets to not to have the documentation prefix?

**Comment by crhistianramirez** [comment]
@xavivars  turns out I actually did. I went down a rabbit hole and thought I didn't it wasn't working. Apparently I needed to set the path of my root component to `/documentation` instead of `/`

Probably something worth calling out at least in the docs. I'm curious if you or others think that should be handled by the `pathPrefix` config as well?
