### ISSUE TITLE
Drop peerDependency on node-sass for gatsby-plugin-sass

### ISSUE THREAD

**Issue by herecydev** [gatsbyjs/gatsby#16002]
### Summary

gatsby-plugin-sass [has a peer dependency on node-sass](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sass/package.json#L30) which is throwing warnings if you are using [Dart Sass](https://sass-lang.com/dart-sass). According to Sass, this is the "primary implementation of Sass" and is a documented and supported implementation for this plugin. Can we change or remove this peer dependency to prevent warnings.

### Motivation

Based on other [similar cases](https://github.com/gatsbyjs/gatsby/issues/11934#issuecomment-477080955) emitting "false" warnings is not helpful for the user.

**Comment by sidharthachatterjee** [comment]
Thank you for pointing this out @herecydev 

> By default the node implementation of Sass (node-sass) is used. To use the implementation written in Dart (dart-sass), you can install sass instead of node-sass and pass it into the options as the implementation

As mentioned in https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sass#alternative-sass-implementations and quoted above, `node-sass` is used by default and using `dart-sass` requires a change in config. 

This means that for the plugin to work _out of the box_ `node-sass` is indeed a required peer dependency. 

Closing this as a result of the above but please feel free to comment or reopen if I'm missing something! Thank you again 💜

**Comment by m-allanson** [comment]
Should we consider switching the plugin to use Dart Sass by default, if that's the primary Sass implementation?

**Comment by herecydev** [comment]
@sidharthachatterjee I understand what you're saying but that doesn't sit well from a UX perspective to have a constant warning about this. I feel like what @m-allanson is suggesting could work or moving what's there into a "core package" and creating 2 separate implementation specific packages that can have the correct peer dependencies on them with zero config, i.e. `gatsby-plugin-dartsass` which doesn't require any additional config and passed options into a `gatsby-plugin-sasscore` package which then does the hard work.
It would therefore remove the peerDependency warnings.

But I do think moving to Dart Sass would solve a few problems and seems to be the "recommended" approach from the Sass team

**Comment by m-allanson** [comment]
There do seem to be some tradeoffs between the two versions, so this change might not be a 100% improvement:

- https://stackoverflow.com/questions/56150402/vue-cli-css-pre-processor-option-dart-sass-vs-node-sass
- https://github.com/JeffreyWay/laravel-mix/issues/1832

I'd be quite strongly against splitting functionality out into multiple plugins like `gatsby-plugin-sasscore` and `gatsby-plugin-dartsass`. This means you have to understand the differences between the different Sass implementations, and then install multiple plugins to get Sass working. I'd argue that this is worse UX than ignoring a peerDependency warning.

As the existing plugin already has the ability to opt-in to using Dart Sass, and that there are cases where node-sass is better than Dart Sass (speed),  I'd agree with @sidharthachatterjee here. Having a `peerDependency` warning that you have to ignore is the least bad approach I can think of for now.
