### ISSUE TITLE
Is it possible to create fully self-contained HTML files with Gatsby?

### ISSUE THREAD

**Issue by Wie-CBD** [gatsbyjs/gatsby#16000]
## Summary

Hi, I was wondering if I can build a Gatsby website into one big HTML file?

So, Instead of separating the scripts / styles, I'd like to compile them in the HTML file itself.

## Relevant information

I'm working on a project that requires me to compile everything (styles, javascript functions) into a single .HTML file, and I won't be able to upload anything else. 

I'm using gatsby since I want to use my existing react components, then generate the static page, however, I couldn't find an option to build everything into the html file itself.  

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @Wie-CBD 

This seems like a fairly niche use case and Gatsby isn't built to support this. You could remove JavaScript with https://github.com/itmayziii/gatsby-plugin-no-javascript but inlining _all_ styles and scripts is not supported at the moment. 

Closing this but please feel free to comment if there is anything else we can help with!
