### ISSUE TITLE
Untitled RSS Feed when using setup function

### ISSUE THREAD

**Issue by Boogy62** [gatsbyjs/gatsby#16018]
## Description

As explained in docs, when I want to add custom_elements with setup function in RSS feeds with 
gatsby-plugin-feed, my RSS title, description and link become "Untitled RSS Feed". When I don't use custom_elements and custom setup, I have the right title.
### Steps to reproduce

Just use custom setup function as explained here https://www.gatsbyjs.org/docs/adding-an-rss-feed/

### Expected result

Title, description and link should are correct.

### Actual result

`<title><![CDATA[Untitled RSS Feed]]></title><description><![CDATA[Untitled RSS Feed]]></description><link>http://github.com/dylang/node-rss</link>`

### Environment

```
System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
Languages:
    Python: 2.7.15
Browsers:
    Edge: 44.18932.1000.0
npmPackages:
    gatsby: ^2.4.0 => 2.4.0
    gatsby-cli: ^2.6.5 => 2.6.5
    gatsby-image: ^2.0.27 => 2.0.27
    gatsby-plugin-favicon: ^3.1.5 => 3.1.5
    gatsby-plugin-feed: ^2.3.4 => 2.3.4
    gatsby-plugin-google-tagmanager: ^2.0.8 => 2.0.8
    gatsby-plugin-react-helmet: ^3.0.5 => 3.0.5
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0
    gatsby-plugin-sharp: ^2.0.18 => 2.0.18
    gatsby-plugin-sitemap: ^2.0.4 => 2.0.4
    gatsby-plugin-zopfli: ^1.0.2 => 1.0.2
    gatsby-remark-emojis: ^0.2.3 => 0.2.3
    gatsby-remark-images: ^3.0.1 => 3.0.1
    gatsby-source-airtable: ^2.0.3 => 2.0.3
    gatsby-source-filesystem: ^2.0.17 => 2.0.17
    gatsby-transformer-remark: ^2.2.0 => 2.2.0
    gatsby-transformer-sharp: ^2.1.12 => 2.1.12
```

**Comment by abuuzayr** [comment]
I can confirm this is happening, as @Boogy62 described: Adding a `setup` method for `gatsby-plugin-feed` options in `gatsby-config` would 'reset' the following fields:

- title
- description
- link
- generator 

![Screenshot 2020-01-26 at 7 22 58 PM](https://user-images.githubusercontent.com/19371989/73134430-65b40480-4071-11ea-8a71-e3e1a0968165.png)

You can also return an empty object for the `setup` method like so to get the same results:

```
...
setup: () => ({}),
...
```

So I suppose we have two options: 

### 1. Shift all our options into the `setup` method like so: 

```
...
        setup: () => ({
          title: 'Title of your site or feed',
          description: 'A short description of the feed.',
          generator: 'Feed generator.',
          feed_url: 'Url to the rss feed.',
          site_url: 'Url to the site that the feed is for.',
          image_url: 'Small image for feed readers to use.',
          docs: 'Url to documentation on this feed.',
          managingEditor: 'Who manages content in this feed.',
          webMaster: 'Who manages feed availability and technical support.',
          copyright: 'Copyright information for this feed.',
          language: 'The language of the content of this feed.',
          categories: [],
          pubDate: 'The publication date for content in the feed',
          ttl: 'Number of minutes feed can be cached before refreshing from source.',
          hub: 'hub url Where is the PubSubHub hub located.',
          custom_namespaces: {},
          custom_elements: [],
        }),
...
``` 

The above options are from https://www.npmjs.com/package/rss#feedoptions

This means we have to update the documentation to inform users that if they wish to use the setup method it will override all other options, whether or not they are explicitly set (the `generator` tag is set by the plugin automatically, but reset when `setup` is used). 

### 2. Fix the plugin to not override the affected fields if they are not set in the `setup` method:

- title
- description
- link
- generator 

Which one of these is preferred by the Gatsby team?

----

# While it is being decided, if someone comes across this issue, please use the first option as a workaround if you need to use `custom_namespaces` or `custom_elements`.

**Comment by leafac** [comment]
A better solution: Pass along the options received by `setup`:

```js
setup: options => ({
  custom_namespaces: {},
  custom_elements: [],
  ...options
})
```

[**Source**](https://github.com/gatsbyjs/gatsby/blob/627d552f2df48ab6354cb0e271338cc0dc56d1ea/packages/gatsby-plugin-feed/src/internals.js#L29-L39)
