### ISSUE TITLE
[bug] code snippets on www do not show new line

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#16011]
## Description

In switching to a React component (and MDX) to render code snippets, we've generally improved the experience and e.g. added copy buttons. However -- we also introduced a small bug (perhaps several 🙃), specifically that blank lines are no longer showing up.

For example: given the following snippet:

```
import React from 'react'

export default () => null
```

this will render as

```
import React from 'react'
export default () => null
```

The correct DOM structure is created (e.g. a blank div with a `token` class), but we are not correctly displaying this structure. Note: #15990 fixed a bug, which re-introduced this behavior. We need that bug fixed (which is a worse bug!) but still want to avoid any edge cases with this new component.

_Note: gatsbyjs.org hasn't deployed yet today -- so this won't show up _yet_ but it will -- trust me!_

### Steps to reproduce

Visit [this page](https://www.gatsbyjs.org/tutorial/part-one/) in about an hour.

### Expected result

Blank line.

### Actual result

🚫 blank line

**Comment by jwithington** [comment]
I wonder if this is due to the [way that Markdown handles line breaks](https://daringfireball.net/projects/markdown/syntax#p), which specifies that 

>When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.

This happens to me all the time when it comes to using Markdown; I often forget to include the double spaces at the end of a line!

**Comment by marcysutton** [comment]
I was just about to open an issue for this, as I saw it too! Definitely something we need to fix.

**Comment by madalynrose** [comment]
It looks like this is fixed! Let me know if I'm mistaken, but looking at the code on [https://www.gatsbyjs.org/tutorial/part-one/](https://www.gatsbyjs.org/tutorial/part-one/) and the [raw file](https://raw.githubusercontent.com/gatsbyjs/gatsby/master/docs/tutorial/part-one/index.md) it looks like it is rendering correctly.
