### ISSUE TITLE
Using gatsby preview with mono-repo

### ISSUE THREAD

**Issue by liamhendricks** [gatsbyjs/gatsby#16024]
## Description

Gatsby preview doesn't seem to play nice with lerna and gatsby themes. We are using gatsby themes with lerna and want to preview a single site, but the preview build dies when trying to resolve themes. Not sure if this is just a feature that hasn't been implemented, or just isn't intended to work.

Our site is a package inside of a monorepo, and most of its dependencies are specified in the project's root package.json, so the build has trouble resolving those. Is there a way to configure gatsby preview to allow for this type of setup?

### Steps to reproduce

- Point gatsby preview to a single lerna project.
- Configure gatsby preview env variables / webhooks.
- Build the preview site.

### Expected result

You should get a built preview site.

### Actual result

Several npm errors resulting in a failed build. Most notably you can see that the build can't figure out how to resolve `gatsby-theme-contentful`. 

`[07/23/2019 - 11:06:58 AM] [Dependencies] code ENOVERSIONS npm ERR! No valid versions available for gatsby-theme-contentful` 

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.0.2
  npmGlobalPackages:
    gatsby-cli: 2.7.13
```

**Comment by DSchau** [comment]
Hey @liamhendricks!

Thanks for opening this issue! This is very much on the Cloud team's roadmap, and we hope to have more information on when that feature is going to be available as soon as we can.

However, as gatsbyjs/gatsby is intended for issues related to the open-source project, I'm going to close this at this time and will open up communication with you from `support@gatsbyjs.com`. Speak to you soon!

**Comment by liamhendricks** [comment]
@DSchau thanks for the reply, sorry I wasn't sure where the best place to raise this issue was (or if this was a bug or not).
