### ISSUE TITLE
Documentation: change "Wordpress" to "WordPress"

### ISSUE THREAD

**Issue by alternatekev** [gatsbyjs/gatsby#1602]
Obviously this isn't a giant deal, but in general, projects that take WordPress seriously capitalize it as I just did. I understand it's pedantic to point out, doesn't really help anyone, and changes very little, but you're going to hear about it from a WP person sooner or later.

WordPress itself even contains a function preventing the "Wordpress" capitalization: https://codex.wordpress.org/Function_Reference/capital_P_dangit

I would submit a pull request for this but the documentation doesn't seem to be versioned/open-sourced.

**Comment by KyleAMathews** [comment]
One reason I think Open Source works so well is we all have different things we care about. Your critical feature is my-nice-to-have. But with everyone able to contribute, open source tools get really robust with everyone contributing to their must haves.

**Comment by Alaev** [comment]
@alternatekev Added PR for the request if you can go over it and add your input that would be great.

**Comment by KyleAMathews** [comment]
Thanks for the fixes!
