### ISSUE TITLE
Query based on `id` return null for Interface

### ISSUE THREAD

**Issue by alexluong** [gatsbyjs/gatsby#16021]
## Description

When using Interface, query based on `id` will return `null`

![kC8k8DVj jpg large](https://user-images.githubusercontent.com/26750127/61733557-0dace600-ad4e-11e9-96e8-d9c3b2c32137.jpg)

### Steps to reproduce

Code based on @ChristopherBiscardi 's `gatsby-data-experiments`

**Comment by stefanprobst** [comment]
Could you provide a repo to quickly reproduce this? Thanks!!

**Comment by ChristopherBiscardi** [comment]
https://github.com/ChristopherBiscardi/gatsby-data-experiments/blob/master/gatsby-node.js

**Comment by stefanprobst** [comment]
Quick question: why did you manually add the `parent` field to the interface? -- it should be available via `... on Node { parent }` because all `@nodeInterface` implementers also implement the Node interface.

**Comment by ChristopherBiscardi** [comment]
@stefanprobst There's no real reason. I talked about this with @freiksenet and he had the same comment. I should remove it.
