### ISSUE TITLE
[gatsby-plugin-mdx] Extra space when link is in excerpt

### ISSUE THREAD

**Issue by scottmartin** [gatsbyjs/gatsby#16035]
## Description

When an MDX file includes a link that would be shown in the plaintext excerpt, an extra space is added after the link.

I found an issue with the same problem in gatsby-transformer-remark. https://github.com/gatsbyjs/gatsby/issues/12398. This issue is basically the same thing but using gatsby-plugin-mdx instead of gatsby-transformer-remark. It appears it was fixed there, but since I believe gatsby-plugin-mdx doesn't use gatsby-transformer-remark, it needs to be fixed here as well.

### Steps to reproduce

All of the steps to reproduce are the same as that original issue. Just substitute in gatsby-plugin-mdx.

**Comment by emgoto** [comment]
Hi! I'm still experiencing this issue so I think this needs to be reopened.

**Comment by theoBLT** [comment]
Bumping this thread — I have the same problem with MDX: an extra space gets added after each link in my excerpts. Can I help re-open this issue to make it visible? ( cc @LekoArts). It looks like the PR which attempted to address it for `gatsby-plugin-mdx` went stale: https://github.com/gatsbyjs/gatsby/pull/26796

![Learn_casual_Indonesian_with_CelotehBahasa_com](https://user-images.githubusercontent.com/1630285/129565710-0e37a6f3-6c56-414e-8fbc-c3618c7edfca.png)
