### ISSUE TITLE
How to get pageQuery variable from nested context property

### ISSUE THREAD

**Issue by Moeriki** [gatsbyjs/gatsby#16053]
It looks like there is no way to access nested context property values in page query variables. Is that correct?

### What I'm doing

Right now I'm duplicating the page context variable `intl.language` as `language` so I can use it as `pageQuery` variable.

_gatsby-node.js_

```js
exports.onCreatePage = ({ page, actions: { createPage, deletePage } }) => {
  if (!page.context.intl || page.context.language) {
    return;
  }
  deletePage(page);
  createPage({
    ...page,
    context: {
      ...page.context,
      language: page.context.intl.language },
  });
};
```

_src/pages/index.jsx_

```js
export const query = graphql`
  query MyQuery($language: String!) {
    # …
  }
`
```

### Ideal scenario

Ideally I could access nested context variables by default.

_gatsby-node.js_

```diff
-exports.onCreatePage = ({ page, actions: { createPage, deletePage } }) => {
-  if (!page.context.intl || page.context.language) {
-    return;
-  }
-  deletePage(page);
-  createPage({
-    ...page,
-    context: {
-      ...page.context,
-      language: page.context.intl.language },
-  });
-};
```

_src/pages/index.jsx_

```diff
export const query = graphql`
-  query MyQuery($language: String!) {
+  query MyQuery($intl__language: String!) {
    # …
  }
`
```

If this is an acceptable addition I'd love to PR.

**Comment by Moeriki** [comment]
Not stale.

**Comment by Moeriki** [comment]
This is not a great experience. I would PR fixes and improvements if I got feedback.

But as it is now I'm not inclined to open another issue again. You're losing potential contributors this way.

**Comment by Hless** [comment]
Hmmm, shame this never got any attention. However, I would like to thank you for sharing your solution nevertheless! Helped me out today

**Comment by llwt** [comment]
Is it still the case that this isn't possible? Running into the same thing.

**Comment by JCMais** [comment]
Having same issue

**Comment by SimonScholz** [comment]
Same here!
