### ISSUE TITLE
emacs autosave files cause builds to fail

### ISSUE THREAD

**Issue by tulsileathers** [gatsbyjs/gatsby#16054]
## Description

`gatsby build` will hang indefinitely at the "Source and transform nodes" step when there is an emacs autosave file for a md file imported using gatsby-source-filesystem.  Emacs autosave files have the same filename as the edited file but prefixed with ".#". I believe  ignoring hidden files 

### Steps to reproduce
edit a markdown file imported by gatsby-source-filesystem in emacs
wait and allow emacs to create an autosave file
attempt to build the project
observe that build hangs indefinitely

### Environment

  System:
    OS: Linux 4.20 Manjaro Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    npm: 6.10.1 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 3.7.3 - /usr/bin/python
  npmGlobalPackages:
    gatsby: 2.13.35

**Comment by tulsileathers** [comment]
i believe this is the same issue https://github.com/gatsbyjs/gatsby/issues/2347

**Comment by mojobnichols** [comment]
Issue #2347 was closed with out a fix.  It seems that someone suggested having file watcher  ignore the editor files.  I'd recommend the opposite create a default list of file extensions that gatsby watches (.css, .js, .xml, .img etc, etc) Then if you need to create some exception you can add it to the list.

**Comment by ianpan870102** [comment]
## [Solved]

Turns out that those aren't auto-saved temp files, but rather symbolic link files.

If you're using Emacs and those `.#` files trouble your development flow, try this option in your `init.el` (Emacs configuration file):

```emacs-lisp
(setq create-lockfiles nil)
```

This will disable the creation of symlink files.

#### References: 
* https://stackoverflow.com/questions/8246483/emacs-how-to-disable-files-creation
* https://stackoverflow.com/questions/5738170/why-does-emacs-create-temporary-symbolic-links-for-modified-files

**Comment by Plurax** [comment]
I am neither a UI guy, nor a Gatsby pro - but a colleague mentioned exclude configs for gatsby-source-filesystem.
I had success with the following plugin config in gatsby-config.js so far (no guarantees) 
With that you dont need to change emacs config (your choice)...
`
plugins: [
        {
      resolve: `gatsby-source-filesystem`,
            options: {
                path: `${__dirname}`,
                name: 'tempfiles',
                ignore: [`**/\.\#*`]
            },
        },
...
]
`

**Comment by wu-lee** [comment]
> With that you don't need to change emacs config (your choice)...
> ```
>     plugins: [
>         {
>             resolve: `gatsby-source-filesystem`,
>             options: {
>                 path: `${__dirname}`,
>                 name: 'tempfiles',
>                 ignore: [`**/\.#*`]
>             },
>         },
>         ...
>     ]
> ```

Although this doesn't seem to work with me for `gatsby develop`, emacs lock files still break the build. (And I don't want to disable the lockfiles)

**Comment by Plurax** [comment]
This is interesting. I dont have time to validate this in depth. But I have a setup running with old dependencies: I am not sure which one is the cause to work - source filesystem is the following version:
```
    "gatsby-source-filesystem": "^2.3.26",
```
After upgrading its not working anymore :(
May be I find the time to enclose this to a specifig package. But I cant promise...

**Comment by wu-lee** [comment]
See also webpack config solution https://github.com/gatsbyjs/gatsby/issues/25562#issuecomment-684399348
