### ISSUE TITLE
Passing qrapthql data between compontens 

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#16063]
when i use "gatsby-plugin-layout", my layout look like below. 
How can i pass props (as i pass to Header to  current page ( to this.props.children )  without using context  ? It's possible ?
```

class Layout extends React.Component {
  render() {
    return (
      <StaticQuery
        query={graphql{
          allLangs {
            nodes {
              content
              code
            }
          }}
        render={data => {
          return (
            <>
            <ContextProviderComponent>
              <Header  allLangs={data.allLangs.nodes} />
              {this.props.children}
            </ContextProviderComponent>
          </>
          )
        }}
      />
    )
  }
}

```
Or if its not possible, it's possible to pass graphql data as DefaultContextValue ?

I want to get data from graphql only once and pass to every component.

I have to put the same data from graqthql into many pages content nad layout, i want to minimalise data sended to client by page-data.json files  .  What is best approach to do it ?

**Comment by universse** [comment]
Hello there. As of now, you can't pass props directly. What you can do instead is use React.cloneElement like so

```javascript
...
<Header  allLangs={data.allLangs.nodes} />
{React.cloneElement(children, {
  allLangs: data.allLangs.nodes
}}
...
```

Also, take a look at #15820.

**Comment by bjatwork** [comment]
@universse  thanks
