### ISSUE TITLE
[gatsby-plugin-mdx] Broken link on readme

### ISSUE THREAD

**Issue by kristiehowboutdat** [gatsbyjs/gatsby#16068]
## Description

The `Why MDX?` link on https://www.gatsbyjs.org/packages/gatsby-mdx/#read-more-about-mdx is returning a 404. The linked page is https://www.gatsbyjs.org/docs/mdx/why/

### Steps to reproduce

- Go to https://www.gatsbyjs.org/packages/gatsby-mdx/#read-more-about-mdx
- Click on the first bullet point (`Why MDX?`)
- View `Page not found`

### Expected result

Clicking the link shows me a wonderful explanation of why MDX is awesome.

### Actual result

Clicking on the link makes me sad because I wanted to learn more about how great MDX is but can't find the page.

### Environment

N/A

**Comment by lannonbr** [comment]
So the plugin `gatsby-mdx` is now deprecated and you can download `gatsby-plugin-mdx` which is now an official plugin maintained by the Gatsby core team.

That said, in the readme of the official plugin, this issue still persists that it links to a non-existant page.

@johno @ChristopherBiscardi Where should we link to for the `Why MDX?` link at the top of the package's readme.

**Comment by johno** [comment]
I think we can probably remove that link altogether and add a short sentence about the “why” in the preceding paragraph since the next link goes straight to the official docs on .org

**Comment by lannonbr** [comment]
How about just copying over the body text from the "Why" section on MDX's homepage as seen here: https://mdxjs.com/#why

> Before MDX, some of the benefits of writing Markdown were lost when integrating with JSX. Implementations were often template string-based which required lots of escaping and cumbersome syntax.
MDX seeks to make writing with Markdown and JSX simpler while being more expressive. Writing is fun again when you combine components, that can even be dynamic or load data, with the simplicity of Markdown for long-form content.

**Comment by johno** [comment]
Works for me 👍

**Comment by kristiehowboutdat** [comment]
So fast! Thanks all - keep up the great work. The Gatsby docs (including plugins) are some of the best docs out there for their readability, thoroughness, and code samples. 🌟

**Comment by ChristopherBiscardi** [comment]
hey @kristiehowboutdat :) thanks for bringing this up! (and @lannonbr for getting the PR in)
