### ISSUE TITLE
Old service working causing old content to show on website

### ISSUE THREAD

**Issue by lukebennett88** [gatsbyjs/gatsby#16072]
## Description

I have a website in production for a café restaurant that you can see here: <https://www.chopnchill.com.au>
I updated the menus (and some other assets) at the beginning of this month, but I've been getting reports from some users that the old menus are showing.

I was able to see this issue on my own machine but in the process of troubleshooting I must have removed/overwritten the old service-worker, so I can no longer troubleshoot it.

### Steps to reproduce

Unfortunately I'm not sure of the exact cause so cannot replicate the issue, but I was able to grab the errors from my console in Chrome during the time that I was also seeing the bug:

```
RTSW: got from cache:
runtime-service-worker.js?v=1:191
https://www.chopnchill.com.au/ runtime-service-worker.js?v=1:190

RTSW: got from cache:
runtime-service-worker.js?v=1:191
https://www.chopnchill.com.au/ runtime-service-worker.js?v=1:191

Failed to load resource: the server responded with a status of 404 ()
logo-portrait-c950537216f706cde4c976640b0d1f4f.svg:1 

Failed to load resource: the server responded with a status of 404 ()
logo-landscape-5a513f9eb613ab0e81a5d50d7fe1c8e9.svg:1 

Failed to load resource: the server responded with a status of 404 ()
menu-mobile-efa6d2cae02a882f8dd088814feaaaaf.png:1 

Failed to load resource: the server responded with a status of 404 ()
component---src-pages-index-js-4e781340d52d66840644.js:1 

Failed to load resource: the server responded with a status of 404 ()
app-2ea6bd211a9deb351faf.js:1 

Failed to load resource: the server responded with a status of 404 ()
2-57e4f21a940379fb28b1.js:1 

Failed to load resource: the server responded with a status of 404 ()
1-49ac3a0d25bc452ba2db.js:1 

Failed to load resource: the server responded with a status of 404 ()
styles-dcca0132f6e9daf009f4.js:1 

Failed to load resource: the server responded with a status of 404 ()
webpack-runtime-74f55f95b0e708c99e32.js:1 

Failed to load resource: the server responded with a status of 404 ()
contact-mobile-07fe6d56e684b65c6e31fbe2cd8cd100.png:1 

Failed to load resource: the server responded with a status of 404 ()
contact-desktop-2fef89d7003cfe2c37c8e09ea6986d3c.png:1 

Failed to load resource: the server responded with a status of 404 ()
runtime-service-worker.js?v=1:190 

RTSW: got from cache:
runtime-service-worker.js?v=1:191 https://www.chopnchill.com.au/

A bad HTTP response code (404) was received when fetching the script.
```

### Expected result

Clients viewing the site should see the most up to date version, with the latest menus and assets.

### Actual result

Clients who have an old service worker (only happening on Chrome from what I've seen) are being shown old menus, and some images/logos are not rendering as they have been changed or renamed since.

![screenshot-homepage](https://user-images.githubusercontent.com/3422401/61840864-00bafe80-aed6-11e9-8cfb-8b66342c094f.png)
![screenshot-menu](https://user-images.githubusercontent.com/3422401/61840865-00bafe80-aed6-11e9-8fdd-1b9992186e72.png)

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.10.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.25 => 2.13.25 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-link: ^2.2.2 => 2.2.2 
    gatsby-plugin-canonical-urls: ^2.1.2 => 2.1.2 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.4 
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3 
    gatsby-plugin-netlify: ^2.1.3 => 2.1.3 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-postcss: ^2.1.2 => 2.1.2 
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sharp: ^2.2.7 => 2.2.7 
    gatsby-plugin-sitemap: ^2.2.3 => 2.2.3 
    gatsby-source-filesystem: ^2.1.5 => 2.1.5 
    gatsby-transformer-json: ^2.2.2 => 2.2.2 
    gatsby-transformer-sharp: ^2.2.3 => 2.2.3 
  npmGlobalPackages:
    gatsby-cli: 2.7.15
    gatsby: 2.0.78

**Comment by lukebennett88** [comment]
I think I've fixed the issue. I've had one reported issue of the website being up and running again.
What I did was use the [`gatsby-plugin-remove-serviceworker`](https://www.npmjs.com/package/gatsby-plugin-remove-serviceworker) plugin to remove the `runtime-service-worker.js` file like so:

```js
{
  resolve: `gatsby-plugin-remove-serviceworker`,
  options: {
    filename: `runtime-service-worker.js`,
  },
},
```

I've also made sure to install the `gatsby-plugin-offline` plugin, so that the website still has the benefits of service worker installed.

**Comment by GiorgioMartini** [comment]
> I think I've fixed the issue. I've had one reported issue of the website being up and running again.
> What I did was use the [`gatsby-plugin-remove-serviceworker`](https://www.npmjs.com/package/gatsby-plugin-remove-serviceworker) plugin to remove the `runtime-service-worker.js` file like so:
> 
> ```js
> {
>   resolve: `gatsby-plugin-remove-serviceworker`,
>   options: {
>     filename: `runtime-service-worker.js`,
>   },
> },
> ```
> 
> I've also made sure to install the `gatsby-plugin-offline` plugin, so that the website still has the benefits of service worker installed.

Which file is this? package.json?

**Comment by lukebennett88** [comment]
`gatsby-config.js`
