### ISSUE TITLE
How do edit gatsby-node.js to fix webpack error 98123 regarding canvas

### ISSUE THREAD

**Issue by thecarney** [gatsbyjs/gatsby#16074]
## Relevant information

https://github.com/thecarney/G778_APP_2
Here's my repo. This project works in development (gatsby develop) but won't built. Issue appears to be related to webpack/SSR and use of canvas. 

My project uses the Deck.gl library, which I think is the culprit, as previous versions that only had react-map-gl were building successfully, but when I added Deck.gl this week, I can't build now. However, I don't actually render a canvas with Deck.gl, I'm just using Deck.gl to build a layer that gets passed to react-map-gl. 

I'm at the edge of my current knowledge with this project (I'm a student), and am not sure how to edit gatsby-node.js to exclude canvas from webpack so that the project will build? 
Where do I start? Is excluding canvas what I need to do? 

I'm just going off of the [Gatsby docs page](https://www.gatsbyjs.org/docs/importing-media-content/) that says "Using canvas and/or WebGL may require modifying your Webpack config. Do you have experience with making this work in your Gatsby site? Contribute to the docs by adding more details to this page."

### Environment (if relevant)
`
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.14 - /c/Python27/python
  Browsers:
    Edge: 41.16299.402.0
  npmPackages:
    gatsby: ^2.13.39 => 2.13.39 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9 
    gatsby-source-filesystem: ^2.1.6 => 2.1.6 
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4 
`

### File contents (if changed)

`gatsby-config.js`: `module.exports = {
  siteMetadata: {
    title: `Projex v1`,
    description: `Version 1`,
    author: `@thecarney`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/Tt-logo.svg`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}`
`package.json`: `{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "@amcharts/amcharts4": "^4.5.9",
    "@fortawesome/fontawesome-svg-core": "^1.2.19",
    "@fortawesome/free-solid-svg-icons": "^5.9.0",
    "@fortawesome/pro-light-svg-icons": "^5.9.0",
    "@fortawesome/pro-regular-svg-icons": "^5.9.0",
    "@fortawesome/pro-solid-svg-icons": "^5.9.0",
    "@fortawesome/react-fontawesome": "^0.1.4",
    "apollo-boost": "^0.4.3",
    "deck.gl": "^7.1.10",
    "gatsby": "^2.13.39",
    "gatsby-image": "^2.2.6",
    "gatsby-plugin-manifest": "^2.2.4",
    "gatsby-plugin-offline": "^2.2.4",
    "gatsby-plugin-react-helmet": "^3.1.2",
    "gatsby-plugin-sharp": "^2.2.9",
    "gatsby-source-filesystem": "^2.1.6",
    "gatsby-transformer-sharp": "^2.2.4",
    "graphql": "^14.4.2",
    "mdbreact": "^4.18.1",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-apollo": "^2.5.8",
    "react-apollo-hooks": "^0.5.0",
    "react-csv": "^1.1.1",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1",
    "react-html-parser": "^2.0.2",
    "react-map-gl": "^5.0.7",
    "react-router-dom": "^5.0.1"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-pro": "^5.9.0",
    "prettier": "^1.18.2"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write src/**/*.{js,jsx}",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\""
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}`
`gatsby-node.js`: N/A 
`gatsby-browser.js`: `export {wrapRootElement} from './src/apollo and context/wrap-root-element';`
`gatsby-ssr.js`: `export {wrapRootElement} from './src/apollo and context/wrap-root-element';`

**Comment by thecarney** [comment]
After spending some time learning more bout webpack and ssr, the short answer is that I just needed to add 'canvas' as an external in my gatsby-node.js and all is well now.

**Comment by thomasgwatson** [comment]
@thecarney I'm fresh to gatsby, how does one "add 'canvas' as an external in my gatsby-node.js"? Assuming it is something I have to do on my CreateWebpackConfig...

**Comment by aikodeio** [comment]
@thecarney how is it done?

**Comment by jonniebigodes** [comment]
@aikodeio see if [this](https://github.com/gatsbyjs/gatsby/issues/17661#issuecomment-532424504) helps you. It uses another plugin that references the canvas but it should give you some insight on how to handle the issue. Otherwise if you're willing please create a reproduction following [steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be looked at in more detail.

**Comment by thecarney** [comment]
Don't know how I missed the notifications this thread had questions, but the issue was solved for me by making my gatsby-node.js file look like this: 

```
exports.onCreateWebpackConfig = ({
  actions //, stage, getConfig, rules, loaders, 
}) => {
  actions.setWebpackConfig({
    externals: ['canvas'],
  });
}
```
