### ISSUE TITLE
Site breaks on build/serve but works perfectly in develop

### ISSUE THREAD

**Issue by TidyIQ** [gatsbyjs/gatsby#16075]
## Description

Here's the repo (note: very much a WIP): https://github.com/TidyIQ/gatsby-themes

This works perfectly when I run it in development mode but once I build and serve it, everything breaks.

Here's how it looks in develop: https://i.imgur.com/rqtMwoL.png

And in build/serve: https://i.imgur.com/Kmi1YCW.png

### Steps to reproduce

Clone repo and install then run:

```
yarn workspace @tidyiq/gatsby-theme-tidyiq build
yarn workspace simple-site dev
```
Then run
```
yarn workspace simple-site build
yarn workspace simple-site serve
```

### Expected result

No issue

### Actual result

See screenshots above

### Environment

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 10.15.3 - ~\AppData\Local\Temp\yarn--1564036881678-0.9003840083964854\node.CMD
    Yarn: 1.16.0 - ~\AppData\Local\Temp\yarn--1564036881678-0.9003840083964854\yarn.CMD
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - C:\Python27\python.EXE
  Browsers:
    Edge: 42.17134.1.0

**Comment by eknowles** [comment]
looks like css, any console errors for network?

**Comment by zoecarver** [comment]
We are having the same issue with a similar config. The issue appears to be that CSS classes are only applied to some elements. For us, the first element does not receive a `class` tag while following elements do receive that tag. Any information about how to proceed with debugging would be much appreciated. This is blocking updates to our website.

**Comment by TidyIQ** [comment]
No console errors at all

**Comment by TidyIQ** [comment]
So there's definitely an issue with how CSS is handled in production vs development...

**gatsby develop**

In development, Gatsby assigns the correct classes to the components. See below.

Style defined correctly:

![image](https://user-images.githubusercontent.com/49704994/61917784-0d446300-af79-11e9-868e-76670997849c.png)

Correct class names in component:

![image](https://user-images.githubusercontent.com/49704994/61917742-e128e200-af78-11e9-833d-b14434249184.png)

**gatsby build, gatsby serve**

In production, Gatsby uses the **incorrect** class names for the components. See below.

Style defined correctly:

![image](https://user-images.githubusercontent.com/49704994/61917944-aa070080-af79-11e9-9918-8e9228c037c9.png)

**INCORRECT** class names in component:

![image](https://user-images.githubusercontent.com/49704994/61918057-2994cf80-af7a-11e9-8f94-09d75651d415.png)

This obviously results in none of the classes being applied. I don't understand why it works fine in development but it breaks on production. Is this a known bug? If so, how do I fix it?

**Comment by TidyIQ** [comment]
Also, it works fine on the initial load for a millisecond or two, then it refreshes and breaks.

**Comment by TidyIQ** [comment]
Further investigation... It seems the issue is with how Gatsby compiles `jss-server-side`. Here's what the initial load looks like:

![image](https://user-images.githubusercontent.com/49704994/61919245-ebe67580-af7e-11e9-958d-7eea9f8e848e.png)

And it has the correct class names:

![image](https://user-images.githubusercontent.com/49704994/61919276-20f2c800-af7f-11e9-92af-5fe424387780.png)

So something Gatsby does when it compiles this is causing the issue.

**Comment by TidyIQ** [comment]
And if I continue with the debugger, I can see the issue starts from here:

![image](https://user-images.githubusercontent.com/49704994/61919630-b2166e80-af80-11e9-82fe-4d9763d1ecc8.png)

**Comment by TidyIQ** [comment]
Annnd a bit more insight...

I realised that the CSS was only failing for the components I've imported from my custom gatsby theme. Basically, that form with the two imports and button are imported from the gatsby theme, while the Open Snackbar button is imported directly from Material UI (in node_modules) in the site itself.

The Open Snackbar button works fine. So the issue is with how Gatsby compiles the theme.

I added the following to my **theme's** `gatsby-browser.js` and `gatsby-ssr.js` files, and now it's working:

```
import NoSsr from "@material-ui/core/NoSsr"; // Imported this
import ContextProvider from "./src/_config/context";

export const wrapRootElement = ({ element }) => (
  <NoSsr> // Added this wrapper
    <ContextProvider>{element}</ContextProvider>
  </NoSsr>
);
```
I'm not sure if this is optimal or if it's going to cause performance and other issues, but it works now in production.

I won't close this as I don't believe the issue is resolved. The expected behaviour is that the production build should work exactly the same as the development build, and that is not the case.

**Comment by zoecarver** [comment]
For us, the issue happens when the site is first loaded. After the site is cached it stops happening. The CSS issue is also only on a few components. We would like to keep SSR, but I will try @TidyIQ's solution and see if it works for us.

**Comment by hmeinertrita** [comment]
Having a similar issue. Wrapping the affected pages in the `NoSsr` component does seem to fix it. However, I would like to know what is causing this issue...

**Comment by Skillz4Killz** [comment]
Not stale. Having a very similar issue with CSS breaking on production. Specifically for **SOME** material UI elements.
