### ISSUE TITLE
generated pages with query string params

### ISSUE THREAD

**Issue by LpmRaven** [gatsbyjs/gatsby#16073]
I have just implemented pagination on my website. The category listing pages are generated in gatsby-node.js. Their url structure looks like this (the number represents the page number):
`mens/1` `mens/2` `mens/3`

I was just wondering if it was possible to make this work but with query string params?

So that the url would look like:
`mens?page=1` `mens?page=2` `mens?page=3`

**Comment by adzshaf** [comment]
@LpmRaven hi! I would like to know how did you solve this problem. I'm currently looking for the solution as well but I haven't found it yet. Sorry for activating this closed issue. Thank you!

**Comment by jonniebigodes** [comment]
@adzshaf i've set up a small [repo](https://github.com/jonniebigodes/testing_url_params_extraction_with_gatsby) on how you can extract query string params from a normal page and a page generated dynamically with `gatsby-node.js`. Take a look at it at your own pace and report back if you have any further issues

**Comment by LpmRaven** [comment]
@adzshaf, In the end, I actually left it as `mens/1` and `mens/2` etc as I read about duplicate content issues using URL params and their impact on SEO. Having each page means they will be indexed correctly. This is just my understanding after reading a few things. If you decide to use URL params, make sure you use the canonical link attribute.
