### ISSUE TITLE
gatsby-transformer-remark not showing in graphql playground

### ISSUE THREAD

**Issue by JACOBIN-SCTCS** [gatsbyjs/gatsby#16093]
## allMarkdownRemark not showing in graphql playground

I had been following the tutorial on gatsby site and in Tutorial 6 I followed all the steps and added package gatsby-transformer-remark . When i go to http://localhost:8000/__graphql and start typinf allMarkdownRemark its not showing suggestions and panel on left doesnt have it.

![alt text](https://i.imgur.com/MinU1Jj.png)

### Steps to reproduce
Link to repo : https://gitlab.com/JACOBIN-SCTCS/gatsbyblog

### Expected result

Should be able to use allMarkdownRemark and markdownremark

### Actual result

allMarkdownRemark and markdownremark

### Environment

  System:
    OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Firefox: 68.0
  npmPackages:
    gatsby: ^2.13.39 => 2.13.39 
    gatsby-plugin-emotion: ^4.1.2 => 4.1.2 
    gatsby-plugin-typography: ^2.3.2 => 2.3.2 
    gatsby-source-filesystem: ^2.1.6 => 2.1.6 
    gatsby-transformer-remark: ^2.6.9 => 2.6.9 
  npmGlobalPackages:
    gatsby-cli: 2.7.17

**Comment by lannonbr** [comment]
Somehow the markdown file you had in `src/pages` had a few spaces at the end of the filename, which is why it wasn't being picked up.

try renaming it and you should be good

**Comment by JACOBIN-SCTCS** [comment]
@lannonbr  That was a mistake out of my carelessness. That helped . Thank you for your help
