### ISSUE TITLE
[docs][tutorial] building a source plugin tutorial

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#16095]
## Summary

Build a “real” source plugin that fetches data from a remote API and each step adds a new feature, e.g. caching, remote images, foreign key relationship, etc. The goal is to show some specific topics that aren't already covered in the Pixabay Source Plugin Tutorial, such as foreign-key relationships, set plugin status, handling caching, linking and transforming nodes to some content type, and more. 

## Motivation

To support people building integrations with Gatsby, we want a solid plugin authoring tutorial in addition to what's on the Gatsby docs.

**Comment by marcysutton** [comment]
Hey @DSchau, there's a related issue to the plugin authoring stuff that may be worthwhile to include as part of this work: https://github.com/gatsbyjs/gatsby/issues/8697

**Comment by marcysutton** [comment]
Hey @DSchau and @amberleyromo, how's this going?

**Comment by marcysutton** [comment]
Learning is going to take this over. Internal doc with more details: https://docs.google.com/document/d/1U8U7lQgsHWjMBuzvG0lpX3JiiDJ5QMHBBHMmcMYFPyk/edit#

**Comment by laurieontech** [comment]
Hey @gillkyle is this content covered in the plugin workflow? Do we need both issues?

**Comment by gillkyle** [comment]
Yeah true, I do have this listed on the workflow evaluation. The other issue (#20232) is getting pretty close, and the content covered here is one of the last things to get taken care of. I think I'll close the other issue and we can instead focus on this one to narrow the scope a little.

**Comment by marcysutton** [comment]
There's a meeting next week to discuss plugin authoring material for first-class integrations, so this issue could be satisfied as part of that discussion!
