### ISSUE TITLE
Investigate the use of <base> instead of linkPrefix

### ISSUE THREAD

**Issue by gesposito** [gatsbyjs/gatsby#161]
I think `linkPrefix` might be some (unnecessary) overhead for newcomers, we could use:

https://developer.mozilla.org/en/docs/Web/HTML/Element/base

http://webdesign.tutsplus.com/articles/quick-tip-set-relative-urls-with-the-base-tag--cms-21399

**Comment by KyleAMathews** [comment]
Wow... I've never heard of <base> actually. Yeah, this looks perfect. So it looks like we could keep things basically as they are now except when someone builds with `--prefix-links`, that'd be a cue to the `html.js` to add the `<base>` tag?

It seems like browser support is near 100%. Is there any downsides to using this technique?

**Comment by gesposito** [comment]
Only downside that I understand is that it needs absolute path, so linkPrefix needs to be the "production" url.
Then, any relative url (`assets/`, `Link to`, etc) is going to be relative to the root `<base>` url.

**Comment by KyleAMathews** [comment]
But you should only prefix links for production? I can't think of any other
time it'd be useful.

**Comment by gesposito** [comment]
Yes, same use of `linkPrefix`

```
<base href="example.github.io/your-project/">
```
when you want to prefix all relative links with `/your-project/`

**Comment by KyleAMathews** [comment]
After some googling, it looks like the <base> tag has some serious downsides...

* http://stackoverflow.com/questions/1889076/is-it-recommended-to-use-the-base-html-tag
* https://www.drupal.org/node/13148

Leaning towards closing this... thoughts @gesposito?

**Comment by gesposito** [comment]
Looks like the only problem we might care about (other two are old issues) is the behaviour with #anchor links.
You can go ahead and close this, I'll try to dig deeper if I'm able to.

**Comment by KyleAMathews** [comment]
Yeah, breaking #anchor links is my main concern as they're often used on static sites.
