### ISSUE TITLE
Gatsby pages with 'adwords' in slug do not work when AdBlock is active

### ISSUE THREAD

**Issue by chungeric** [gatsbyjs/gatsby#16104]
## Description

It seems that any pages with the word **'adwords'** in the url do not work with the Google Chrome AdBlock extension active. I have not experienced this issue with any other page slugs before. I have tested this on a new Gatsby project using `gatsby new` and created a page at /adwords/ and /adwords/remarketing/ and both pages break. The error in the console says:
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT http://localhost:<port>/page-data/adwords/page-data.json:1 
```
and
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT http://localhost:<port>/page-data/adwords/remarketing/page-data.json:1 
```
So it seems that the browser is unable to get the page json data because the filename has 'adwords' in it. Not sure if this is a bug that is preventable, but would be great if this was fixed.

### Steps to reproduce

1. Create a new Gatsby project using `gatsby new <projectname>`
2. Create a page in the src/pages folder named adwords.js
3. Create a subfolder in the src/pages folder titled adwords and create a file inside named remarketing.js
4. Add page content to both and run `gatsby develop`

### Expected result

Pages should work normally, and display the content.

### Actual result

Pages are broken. Errors in console:

<img width="707" alt="Screen Shot 2019-07-26 at 10 00 41 am" src="https://user-images.githubusercontent.com/22333460/61916540-5225c500-af8c-11e9-8750-e02491a99d6d.png">

### Environment

System:
    OS: macOS 10.14.5
    CPU: x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.39 => 2.13.39
    gatsby-image: ^2.2.6 => 2.2.6
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4
  npmGlobalPackages:
    gatsby-cli: 2.4.3

**Comment by pieh** [comment]
We might be able to workaround this by maintaining dictionary of blacklisted adblocker words or hash path segments, but to be honest I'm not sure we should. This would add overhead to gatsby runtime and to me it really seems like overzealous adblocker rule to block resources that contain "ad" in them (but not being actual ad)

**Comment by pieh** [comment]
That said - we should still be able to display content if resources are blocked (using just static html markup, so even if JS runtime wouldn't work for that page - the content should still be there)

**Comment by chungeric** [comment]
@pieh Right, it's creating the page during build time and so must be getting the data fine behind the scenes. The browser is unable to display the static page for some reason. Is this a fixable issue on the Gatsby side of things, or is my only option to change the slug to something else?

**Comment by waltercruz** [comment]
I think that the best option would be just change the slug. Any news @chungeric ?

**Comment by jipiboily** [comment]
Hello folks! I'm getting a similar issue here, with "google-ads".

Changing the slug could be done, obviously, but SEO-wise, I'm not sure it's a good idea.

I was expecting the static HTML to be served.

Is there some way to force service an HTML version of a page?

I'm happy to work on something. But never having worked with Gatsby's internal, I'm not even sure where to start.

Hints?

**Comment by LekoArts** [comment]
This is really an upstream issue and nothing we can/should fix.

**Comment by jipiboily** [comment]
What do you mean by upstream in this context?

I mean, there is no way to fix that other than changing the slug, or fixing that in Gatsby, AFAIK. We can't control what people do with their browser and how the ad blockers behave.

I think having a website compatible with 100% of the browsers would be ideal, as opposed to, what, 70% not using ad blockers?

I just want to be sure to understand. :)

**Comment by rasmuswoelk** [comment]
Hi @jipiboily & @chungeric 

I'm experiencing the same issue – did you by any chance figure out a clever workaround?

**Comment by jipiboily** [comment]
I had to stop using the prefetching (<Link> stuff). Sad but this was the most pragmatic decision.

That said, ideally, we would disable it only when detecting ad blockers. Maybe I’ll look into that in 2021.


JP Boily

Founder @ Metrics Watch ( https://metricswatch.com/?utm_source=jp&utm_medium=gmail-signature )

Metrics Watch is a reporting software tailored to Marketing Agencies, allowing them to automate their client reporting in a beautifully designed, mobile-first, email-based solution. Clients get regular, actionable data on their marketing spend, allowing the Agency to focus on what they do best.

On December 19, 2020 at 11:14 AM, Rasmus Wølk (notifications@github.com) wrote:
Hi @jipiboily ( https://github.com/jipiboily ) & @chungeric ( https://github.com/chungeric )
I'm experiencing the same issue – did you by any chance figure out a clever workaround?
