### ISSUE TITLE
can't  disable dev-404

### ISSUE THREAD

**Issue by JoueBien** [gatsbyjs/gatsby#16112]
## Summary

Please make the 404 dev page an external plugin or allow for it to be disabled. 

### Motivation
I'm Trying to build a router on-top of the 404 page but I am forced to click redirect every time. The existing router plugins don't support page/* catch all routs and adding a router to gatsby-node.js dosen't work when you are using type script or es6 imports. Right now overriding the 404 page is the only way to add catch all routs.

**Comment by pieh** [comment]
You can do something like this in your gatsby-node.js file:

```js
exports.onCreatePage = ({ page, actions }) => {
  if (process.env.NODE_ENV !== `production` && page.path === `/404/`) {
    const { createPage } = actions
    // Make the 404 page match everything client side.
    // This will be used as fallback if more specific pages are not found
    page.matchPath = `/*`
    createPage(page)
  }
}
```

**Comment by pieh** [comment]
I'm thinking tho if persisting that state to localStorage, so you can click once and make gatsby remember your choice would just be nicer. If we did this we would need a way to toggle that state back to dev-404

**Comment by JoueBien** [comment]
> You can do something like this in your gatsby-node.js file:
> 
> ```js
> exports.onCreatePage = ({ page, actions }) => {
>   if (process.env.NODE_ENV !== `production` && page.path === `/404/`) {
>     const { createPage } = actions
>     // Make the 404 page match everything client side.
>     // This will be used as fallback if more specific pages are not found
>     page.matchPath = `/*`
>     createPage(page)
>   }
> }
> ```

that won't work with es6 imports and type script.  createPage(page) ties to build the page and fails.

**Comment by wardpeet** [comment]
@JoueBien would this be a nice workaround for you?
