### ISSUE TITLE
Mapping multiple nodes to a single source node fails

### ISSUE THREAD

**Issue by nathobson** [gatsbyjs/gatsby#16118]
## Description

I can successfully map a single node to another node [as described in the docs](https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types). However, I can't seem to find a way to map multiple nodes to a single other node.

### Steps to reproduce

Add something like this to `gatsby-config`

```
mapping: {
    'WordPressAcf_call_to_action.buttons': ['wordpress__wp_projects.wordpress_id', 'wordpress__PAGE.wordpress_id']
  }
```

The project I'm working on is private so don't have a repo. Can try to abstract something out if that would be needed.

### Expected result

I would expect to be able to pass an array of nodes, which would each then be mapped to the single other node. If multiple keys with the same value are passed, it will not fail but only the last value will be mapped (which makes sense).

### Actual result

This fails on `gatsby develop` with the following error message:

`UNHANDLED REJECTION typeMapping[selector].split is not a function or its return value is not iterable`

Using a single key:value pair works as expected:

```
mapping: {
    'WordPressAcf_call_to_action.buttons': `wordpress__wp_projects.wordpress_id`
  }
```

### Environment

```
  System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 67.0.2
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.8.6 => 2.13.28 
    gatsby-image: ^2.0.31 => 2.2.6 
    gatsby-plugin-manifest: ^2.0.22 => 2.2.3 
    gatsby-plugin-offline: ^2.0.24 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.0.8 => 3.1.2 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-sharp: ^2.0.25 => 2.2.8 
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2 
    gatsby-source-filesystem: ^2.0.23 => 2.1.5 
    gatsby-source-wordpress: ^3.0.43 => 3.1.9 
    gatsby-transformer-sharp: ^2.1.15 => 2.2.4 
  npmGlobalPackages:
    gatsby-cli: 2.7.15
```

**Comment by pieh** [comment]
Right now mapping doesn't support mapping to multiple types, but you can make this work using lower level APIs than mapping:

```js
// in gatsby-node.js
exports.createSchemaCustomization = ({ actions, schema }) => {
  const { createTypes } = actions
  createTypes([
    schema.buildUnionType({
      name: "PageOrProject",
      types:["wordpress__wp_projects", "wordpress__PAGE"],
      resolveType: node => node.internal.type,
    }),
	schema.buildObjectType({
      name: "WordPressAcf_call_to_action",
      fields: {
        buttons: {
          type: "PageOrProject",
          extensions: {
            link: {
              by: "wordpress_id"
            }
          }
        }
      }
    })
  ])
}
```

That snippet might not work on first try and could need some changes (pretty hard to write this up correctly first time without having access to repro ;) )
