### ISSUE TITLE
can we use  react-router-dom to switch routes in gatsby app

### ISSUE THREAD

**Issue by SalmanZahid96** [gatsbyjs/gatsby#16120]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
Gatsby internals use `@reach/router` and you can't change that at this time. You can use different router in [Client-only routes](https://www.gatsbyjs.org/docs/building-apps-with-gatsby/#client-only-routes--user-authentication)

Why do you want to specifically use `react-router-dom`? Maybe we could solve this instead?

**Comment by SalmanZahid96** [comment]
i am currently working on a project i which i want to switch between routes like we do in app.js in react and i also want to pass props while redirecting to other pages

**Comment by pieh** [comment]
> want to switch between routes like we do in app.js in react

You technically could do that using Client-only routes I mentioned before - you can check https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths example that does this:
 - https://github.com/gatsbyjs/gatsby/blob/master/examples/client-only-paths/gatsby-node.js - this makes sure all routes will be handled by `/src/pages/index.js`
 - https://github.com/gatsbyjs/gatsby/blob/42317c16ea1f86b1b3fe04b91cc25e16b79f757b/examples/client-only-paths/src/pages/index.js#L14-L17 (this is using Router in page template - in this case it's `@reach/router`, but you could use `react-router`.

But with this you would lose automatic per route code splitting and SSR so personally I would not recommend doing that unless you actually have need for dynamic routes.

> i also want to pass props while redirecting to other pages

Can you show example of this (can be code snippet with `react-router-dom`), so I can understand usecase a little better? We might have way to do this without giving up on optimisations (mentioned above) that Gatsby does

**Comment by sidharthachatterjee** [comment]
Marking this as answered and closing the issue. Please feel free to comment or reopen if you have any other related questions. 

Thank you for using Gatsby 💜
