### ISSUE TITLE
[gatsby-source-contentful] Cannot fetch all Entries without a localized field

### ISSUE THREAD

**Issue by blessenm** [gatsbyjs/gatsby#16125]
I am trying to fetch all the entries for a contentful type with the following query. I only have 3 fields in it and none of them are localized field

```
query MyQuery {
  allContentfulElementImage(filter: {node_locale: {eq: "de-DE"}}) {
    edges {
      node {
        entryTitle
        contentful_id
        node_locale
      }
    }
  }
}
```

But this returns 
```
{
  "data": {
    "allContentfulElementImage": {
      "edges": [
        {
          "node": null
        }
      }
   }
}
```

This problem goes away the moment I add 1 field that is localized. I would assume the default locale would kick in when there is no localized fields.

**Comment by blessenm** [comment]
@Khaledgarbaya is this a known issue? or how contentful works?

**Comment by Khaledgarbaya** [comment]
Hey @blessenm ,
I think the fallback locale will kick in if you have it set up in your space otherwise it will return null if there are no data with that locale.
