### ISSUE TITLE
Updating gatsby 2.9.0  to 2.13.41 makes localhost:8000 hung

### ISSUE THREAD

**Issue by tareefdev** [gatsbyjs/gatsby#16131]
I have a site using gatsby (based on blog starter). Today after updating gatsby `2.9.0`  to `2.13.41`, I got this problem: using `gatsby develop` makes `http://localhost:8000/` hang in the browser with high CPU usage, there is no error in the terminal nor in the browser's console. so I even don't know how to debug the issue!

`gatsby build && gatsby serve` works fine as usual. I tried to update all gatsby related packages, deleting cache and public, but nothing changed. 

This is the [packages](https://github.com/tareefdev/beta/blob/master/package.json) I'm using.
A screenshot for `localhost:8000` after developing:
![Screenshot_20190726_194056](https://user-images.githubusercontent.com/17391433/61967766-e28cf580-afde-11e9-9cec-5d14e93ece30.png)

### Environment

  System:
    OS: Linux 5.2 Arch Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Shell: 5.0.7 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 3.7.3 - /usr/bin/python
  Browsers:
    Firefox: 68.0.1
  npmPackages:
    gatsby: ^2.13.41 => 2.13.41
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-mdx: ^1.0.0 => 1.0.0
    gatsby-plugin-feed: ^2.3.5 => 2.3.5
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.4
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-mdx: ^1.0.17 => 1.0.17
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-react-leaflet: ^2.0.11 => 2.0.11
    gatsby-plugin-sass: ^2.1.3 => 2.1.3
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-plugin-typography: ^2.3.2 => 2.3.2
    gatsby-remark-copy-linked-files: ^2.1.3 => 2.1.3
    gatsby-remark-images: ^3.1.7 => 3.1.7
    gatsby-remark-prismjs: ^3.3.3 => 3.3.3
    gatsby-remark-responsive-iframe: ^2.2.4 => 2.2.4
    gatsby-remark-smartypants: ^2.1.2 => 2.1.2
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-json: ^2.2.2 => 2.2.2
    gatsby-transformer-remark: ^2.6.9 => 2.6.9
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4
  npmGlobalPackages:
    gatsby-cli: 2.7.20

**Comment by pieh** [comment]
Are you able to share reproduction / your project?

**Comment by tareefdev** [comment]
This is the [repo](https://github.com/tareefdev/beta), this is the [content repo](https://github.com/tareefdev/beta-content), also to build the site on your machine you need [this](https://github.com/gatsbyjs/gatsby/files/3436811/data.zip) `data` folder.

**Comment by chriskekeke** [comment]
This also happened with the project our team is working with
`2.3.0` > `2.13.39`
Also tried to update it `2.13.39` to the latest `2.13.41` and it still hangs

Downgrading to `2.11.0` seems to have resolved the hanging
From `2.11.1` we was experiencing hanging

**Comment by chriskekeke** [comment]
This also happened with the project our team is working with
`2.3.0` > `2.13.39`
Also tried to update it `2.13.39` to the latest `2.13.41` and it still hangs

Downgrading to `2.11.0` seems to have resolved the hanging
From `2.11.1` we was experiencing hanging

**Comment by waltercruz** [comment]
Have you guys tried with the latest version, 2.13.67?

**Comment by tareefdev** [comment]
I updated the packages now then `gatsby clean && gatsby develop` and got the same issue.

**Comment by jonniebigodes** [comment]
@tareefdev i've picked up on your issue. Below are the steps i took to triage your issue.
- Cloned the [repo](https://github.com/tareefdev/beta).
- Cloned the [repo](https://github.com/tareefdev/beta-content) to content folder, some issues while fetching a couple of items, but i think that is because the files are in arabic and my os language does not like it out of the box.
- Installed the dependencies.
- Issued `gatsby develop` and the build failed. Checking on the error it seems that you have `gatsby-mdx` and that package is now deprecated and could lead to some issues. If you don't mind remove the said package and install ` gatsby-plugin-mdx` instead and update accordingly.
- Copied over the data you supplied in your link, side note you forgot to incorporate the `oldIncidents.json` in the zip file. 
- Issued `gatsby develop` and i'm presented with the following:
![tareef_1](https://user-images.githubusercontent.com/22988955/63358848-9de94580-c363-11e9-8039-632e2e0f6803.png)
![tareef_2](https://user-images.githubusercontent.com/22988955/63358893-ab9ecb00-c363-11e9-8b1f-6e1f33461efb.png)
![tareef_3](https://user-images.githubusercontent.com/22988955/63358988-e0ab1d80-c363-11e9-859b-b88ad81cdf58.png)

It looks like the `@` character in that particular file causes issues with `gatsby-transformer-json` and also some other key names aswell.

The graphql error show is due to the update to`gatsby-plugin-mdx`. Like i said above you might need to update accordingly.
![tareef_4](https://user-images.githubusercontent.com/22988955/63359406-99715c80-c364-11e9-9a5d-95451cac914e.png)

But as you can see despite this small issues the build ran to completion.

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by jonniebigodes** [comment]
@tareefdev upon taking a look at the code, it seems that the issue is in `gatsby-node.js` more exactly in:
```javascript
exports.onCreatePage = ({ page, actions }) => {
  const { createPage, deletePage } = actions;
  console.log(`page.path:${page.path}`)
  // deletePage(page);
  Object.keys(locales).map(lang => {
    console.log(`locales[lang].default:${locales[lang].default}`);
    
    const localizedPath = (function() {
      if (locales[lang].default && page.path === "/") {
        return "/"
      } else {
        return `${locales[lang].path}${page.path}`
      }
    })()
    return createPage({
      ...page,
      path: removeTrailingSlash(localizedPath),
      context: {
        ...page.context,
        locale: lang,
        dateFormat: locales[lang].dateFormat,
      },
    })
  })
}
```
Commenting out the `deletePage(page)` in that file and updating the `src/pages/index.js` to accomodate the changes to the plugin mentioned earlier, which in turn leads to the content of the file now being:
```javascript
import React, { useContext, useState } from "react";
import { graphql } from "gatsby";

//import MDXRenderer from "gatsby-mdx/mdx-renderer";
import { MDXRenderer } from "gatsby-plugin-mdx";

import Layout from "../components/layout";
import LocalizedLink from "../components/localizedLink";
import { LocaleContext } from "../context/locale-context";
import useTranslations from "../components/useTranslations";

import SVGMap from "../components/charts/sy-map"

const Index = ({ data }) => {
  const [hoveredDistrict, setHoveredDistrict] = useState({
    name: "On the whole, We have 2500 Sources",
    sources: "",
  });
  const locale = useContext(LocaleContext)
  const tr = useTranslations()

  const partials = data.partials.edges.map(p => p.node) 
  const latestInvestigation = data.latestInvestigation.edges[0].node.frontmatter
  const latestDatabase = data.latestDatabase.edges[0].node.frontmatter
  const latestTechAdvocacy = data.latestTechAdvocacy.edges[0].node.frontmatter
  const numbers = data.allSiteMetadataJson.edges[0].node.numbers
  //const about = partials[0].code.body
  
  const about = partials[0].body

  return (
    <Layout>
      <div className="index-page">
        <MDXRenderer>{about}</MDXRenderer>

        <div className="data-numbers">
          <div className="number">
            <h3>{numbers.collectedVideo}</h3>
            <h5> collected Video</h5>
          </div>

          <div className="number">
            <h3>{numbers.collectedPosts}</h3>
            <h5> collected Posts</h5>
          </div>

          <div className="number">
            <h3>{numbers.collectedTweets}</h3>
            <h5> collected Tweets</h5>
          </div>

          <div className="number">
            <h3>{numbers.verifieddata}</h3>
            <h5> Verified Data</h5>
          </div>
        </div>

        <hr></hr>
        <h2>How we do it</h2>
        <div className="method-workflow">
          <div className="method-element">
            <h3>Discover</h3>
            <p>
              Nam a sapien. Sed id ligula quis est convallis tempor. Sed
              bibendum.{" "}
            </p>
          </div>

          <div className="method-element">
            <h3>Collect</h3>
            <p>
              Nam a sapien. Sed id ligula quis est convallis tempor. Sed
              bibendum.{" "}
            </p>
          </div>

          <div className="method-element">
            <h3>Verify</h3>
            <p>
              Nam a sapien. Sed id ligula quis est convallis tempor. Sed
              bibendum.{" "}
            </p>
          </div>

          <div className="method-element">
            <h3>investigation</h3>
            <p>
              Nam a sapien. Sed id ligula quis est convallis tempor. Sed
              bibendum.{" "}
            </p>
          </div>
        </div>

        <hr></hr>

        <h2>Our latest releases</h2>
        <div className="latest-releases">
          <div className="release-element">
            <h3>{latestTechAdvocacy.title}</h3>
            <small>Tech Advocacy</small>
            <p>{latestTechAdvocacy.desc}</p>
          </div>
          <div className="release-element">
            <h3>{latestInvestigation.title}</h3>
            <small>Investigation</small>
            <p>{latestInvestigation.desc}</p>
          </div>
          <div className="release-element">
            <h3>{latestDatabase.title}</h3>
            <small>Database</small>
            <p>{latestDatabase.desc}</p>
          </div>
        </div>

        <hr></hr>
        <h2>Dicover our sources</h2>

        <div>
          {hoveredDistrict.sources == ""
            ? hoveredDistrict.name
            : `we have ${hoveredDistrict.sources} sources in ${hoveredDistrict.name}`}
        </div>

        <SVGMap setHoveredDistrict={setHoveredDistrict} />
      </div>
    </Layout>
  );
};

export default Index;

export const pageQuery = graphql`
query IndexPartials($locale: String!) {
  partials: allMdx(filter: {frontmatter: {type: {eq: "partial"}}}) {
    edges {
      node {
        body
      }
    }
  }
  latestTechAdvocacy: allMdx(filter: {fields: {locale: {eq: $locale}}, fileAbsolutePath: {regex: "/content/tech-advocacy/"}, frontmatter: {level: {lte: 1}}}, sort: {fields: [frontmatter___date], order: DESC}, limit: 1) {
    edges {
      node {
        frontmatter {
          title
          desc
        }
      }
    }
  }
  latestInvestigation: allMdx(filter: {fields: {locale: {eq: $locale}}, fileAbsolutePath: {regex: "/content/investigations/"}, frontmatter: {level: {lte: 1}}}, sort: {fields: [frontmatter___date], order: DESC}, limit: 1) {
    edges {
      node {
        frontmatter {
          title
          desc
        }
      }
    }
  }
  latestDatabase: allMdx(filter: {fields: {locale: {eq: $locale}}, fileAbsolutePath: {regex: "/content/collections/"}, frontmatter: {level: {lte: 1}}}, sort: {fields: [frontmatter___date], order: DESC}, limit: 1) {
    edges {
      node {
        frontmatter {
          title
          desc
        }
      }
    }
  }
  allSiteMetadataJson {
    edges {
      node {
        numbers {
          collectedPosts
          collectedTweets
          collectedVideo
          verifieddata
        }
      }
    }
  }
}
`;
```
Issuing `gatsby develop` and opening up a new browser window to `http://localhost:8000` the issue is no longer present as you can see below:
![tareef_5](https://user-images.githubusercontent.com/22988955/63388103-32bd6480-c39f-11e9-933e-fbbb64d391b3.png)

**Comment by tareefdev** [comment]
This is a great catch! Even without migration to `gatsby-plugin-mdx`, commenting out `deletePage(page)` solves the issue!

As the site has two languages, the pages which automatically created by Gatsby are unwanted, so instead of `/page/` we want `/en/page` or `/ar/page`, this method was used by [this example](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-i18n/gatsby-node.js). 

I cloned that example again, `npm i && gatsby develop` and the site works fine without any similar issue, I'll try to investigate why deleting pages causes that hung.

Thanks for such great helping.

**Comment by jonniebigodes** [comment]
@tareefdev it could be related to how you're implementing the i18n, as a test, can you simplify your implementation following the gatsby example and also with that enabling the `deletePage(page);` and see if it does not hang.

**Comment by tareefdev** [comment]
@jonniebigodes I found another interesting thing, I returned `deletePage(page)` and commented out this line `createRedirect({ fromPath: '/en', toPath: '/', isPermanent: true });` and the site works fine again. I think this is not a bad solution as I'm still able to perform redirecting using Nginx.

**Comment by tareefdev** [comment]
The issue still happens occasionally, in that case, I comment out `deletePage(page);` run `gatsby develop` then end the process, uncomment `deletePage(page);` && `gatsby develop` and the site works perfectly!

**Comment by wardpeet** [comment]
Hey @tareefdev, is it possible to create a smaller reproduction? This seems like an annoyable bug that we should fix when we can replicate it in a small test case.

**Comment by zslabs** [comment]
@wardpeet I'm having this occur within https://github.com/zslabs/zslabs.com/tree/feature/emotion If you pull down that branch, run `yarn develop` and edit src files (for example, changing some of the inline Emotion-styles in `BubbleList.js`) after the second or third save, the hot-reloader appears to just hang, and the window becomes unresponsive. I need to then use the Chrome Task Manager to manually quit the tab (as cmd+q even stops working) with the CPU percentage of that tab being at 100%.

**Comment by tareefdev** [comment]
Hello @wardpeet. Unfortunately, I can't reproduce this bug every time! I moved the project into a [new repo](https://gitlab.com/tareefdev/sy-beta) where you just need to clone, install, and run (all files are included).

When the issue accrues I comment out `deletePage(page)` or `createRedirect({ fromPath: '/en', toPath: '/', isPermanent: true });` and the site works fine, then I can uncomment them out again without any issue.
