### ISSUE TITLE
CSS doesn't load immediately on page load with styled-components

### ISSUE THREAD

**Issue by paulgaumer** [gatsbyjs/gatsby#16138]
## Description

On page load, one of my components displays raw html first, then applies the CSS a split second later (see gif below). The other components seem to load CSS correctly. All of the components are using styled-components. I found similar issues and the recommendation was to include `gatsby-plugin-styled-components` in the config file. This was the case from the beginning in my project but I still face the issue. I tried to switch to Emotion, same issue...

Could someone please help? 🙏

Link to the repo: [https://github.com/paulgaumer/Portfolio_PG](https://github.com/paulgaumer/Portfolio_PG)

![bug](https://user-images.githubusercontent.com/17173804/61984645-9acd9480-b005-11e9-9af8-d473180b5e0b.gif)

### Environment
```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7Y54 CPU @ 1.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.8.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.13 => 2.13.13 
    gatsby-image: ^2.2.4 => 2.2.4 
    gatsby-plugin-manifest: ^2.2.1 => 2.2.1 
    gatsby-plugin-offline: ^2.2.1 => 2.2.1 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0 
    gatsby-plugin-sass: ^2.1.1 => 2.1.1 
    gatsby-plugin-sharp: ^2.2.3 => 2.2.3 
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-source-filesystem: ^2.1.3 => 2.1.3 
    gatsby-transformer-sharp: ^2.2.1 => 2.2.1 
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```

**Comment by lannonbr** [comment]
So I dug into your repo and found a reasoning for the flash of content. In your [Hero Section](https://github.com/paulgaumer/Portfolio_PG/blob/master/src/components/sections/hero/hero-section.js), you have a React hook to check the window width and conditionally render either a desktop or mobile hero section. The issue with that is when you run `gatsby build`, it has no context of any browser window given it is just a node app, so the styled-components plugin can't SSR that component and leaves it to be rendered when you load the page which leads to a flash on the left side of the page. There are some strategies you could do like render the mobile layout or desktop layout first and then swap out to the other using a hook, but that'll be up for you to decide.

Hope that helped!

**Comment by paulgaumer** [comment]
Thanks a lot @lannonbr, this helps! However I thought that initialising the state of `windowWidth` at 0 was doing this already. The render doesn't give me any flash on mobile, only on desktop.

Here is the code conerned for info:
```
const LandingSection = () => {
  // Initialize state at 0 via context
  const [windowWidth, setWindowWidth] = useState(0)

  const handleWindowResize = () => {
    setWindowWidth(window.innerWidth)
  }

  useEffect(() => {
    // Check for the presence of window. Needed for SSR.
    if (typeof window !== "undefined") {
      setWindowWidth(window.innerWidth)
      window.addEventListener("resize", handleWindowResize)
      return () => {
        window.removeEventListener("resize", handleWindowResize)
      }
    }
  })

  return (
    <div>
      <Wrapper>
        {windowWidth >= 1024 ? <MainLaptop /> : <MainMobile />}
..............
..............
```
