### ISSUE TITLE
Allow "gatsby new" to install from a subdirectory in e.g. a monorepo

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#16135]
This is something we've considered for a long time but with the recent release of themes, has become a lot more pressing as themes are best developed with a yarn workspace that includes the theme & its starter — but it's a pain to have to copy out the starter to another repo so people can easily create sites. Much more ideal is if `gatsby new` could know to clone the monorepo but to create the site from the `starter `directory.

This would require some sort of metadata to be in the root directory that `gatsby new` would read.

This thread is to brainstorm some ways to do this and then we should write an RFC before implementation.

One easy way to do this is [to add a `gatsby` key to the root package.json](https://stackoverflow.com/questions/10065564/add-custom-metadata-or-config-to-package-json-is-it-valid) e.g. 

```json
{
  "gatsby": {
    "starterDirectory": "starter"
  }
}
```

**Comment by pieh** [comment]
I think key in root package.json could be either limiting (allow only single starter in repo) or cumbersome (you could define multiple starters,  but then user has to select which one he actually wants)

Alternative that I don't know if I like yet, is to be able to define directory path in `gatsby new` command as arg.

---

Another problem that needs to be solved is checking out just subdirectory. 

There is "Sparse checkout" in git, but it still will actually fetch everything and only checkout subset locally. Ideally we could use partial clone, but github "git" server doesn't support `--filter` switch.

So in the end users will have to fetch everything (well we can make it shallow - but still full tree) - so this will work for monorepos dedicated to themes development - but we couldn't really migrate official starters from gatsbyjs/gatsby-stater-X to use gatsbyjs/gatsby repo.

**Comment by KyleAMathews** [comment]
Yeah I only see this a solution for monorepos with one theme and starter. So for people doing more, they'd still need the GitHub action.

Which I think is pretty reasonable. If you're investing more, setting up actions isn't too bad. But if you want to whip out child themes and you're perhaps more of a designer than developer, this would help a lot.

**Comment by jxnblk** [comment]
This is probably similar to what @pieh is talking about, but would we not want to support specifying a path from the CLI so that something like `gatsby new gatsbyjs/gatsby/starters/blog` would work if there's a `package.json` file, even if it would mean cloning an entire repo?

My guess is that most repos wouldn't be as large as Gatsby, and it seems like a nice, zero-config way to add a starter to any project. There might be a whole slew of problems with something like this that I'm not thinking about, though

**Comment by vpicone** [comment]
Has there been any more thought about this? Would be a big quality of life fix for the most common theme development workflow.

**Comment by muescha** [comment]
a better sparse checkout is now in Git 2.25:
https://github.blog/2020-01-13-highlights-from-git-2-25/
