### ISSUE TITLE
withWebp and netlify

### ISSUE THREAD

**Issue by Freysi21** [gatsbyjs/gatsby#16140]
Hi

I've been having issues with netlify builds after I added withWebp to my graphql queries. 
Does the webp option add significant load that prevents my netlify builds to complete with it's time limit?

I'm not not using more then 30 images on my site btw.

**Comment by davidbailey00** [comment]
Hi @Freysi21, thanks for opening this issue!

Would you be able to point us to your repository having this issue, or make a minimal reproduction of the issue? Without this it's not clear exactly why the issue is occurring. Thanks!

**Comment by KyleAMathews** [comment]
Webp is many times more expensive to produce than jpeg so yes, switching to webp will slow your builds considerably.
