### ISSUE TITLE
Context API integration with netlify cms

### ISSUE THREAD

**Issue by vsahinid** [gatsbyjs/gatsby#16162]
I wanted to ask if the netlify CMS starter package picks up the gatsby-browser.js file automatically without any more configuration when integrating the Context API. This would be pretty helpful.  Been going off the tutorial here but doesn't seem to be helpful:
https://www.gatsbyjs.org/blog/2019-01-31-using-react-context-api-with-gatsby/

**Comment by sidharthachatterjee** [comment]
If I understand correctly, you mean to ask if `gatsby-browser.js` is automatically picked up when using https://github.com/netlify-templates/gatsby-starter-netlify-cms

To answer your question, `gatsby-browser.js` is _always_ loaded by Gatsby irrespective of the starter you use 🙂 

Marking this as answered and closing but the issue but please feel free to comment or reopen if I haven't understood or answered your question correctly!
