### ISSUE TITLE
How do I convert a blank string value to null at build time?

### ISSUE THREAD

**Issue by davidleger95** [gatsbyjs/gatsby#16174]
## Summary

I want to normalize a field value to `null` if it's an empty string.

## Relevant information

I'm using Netlify CMS for a Gatsby site and some number fields are optional. This is resulting in some number fields being incorrectly stored as an empty string (`field: ''`) and gatsby won't include the fields because of conflicting types.

I assume this is possible to do in `gatsby-node.js`, I'm just not sure how. Thanks in advance for any help! :)

**Comment by stefanprobst** [comment]
You can use the `createTypes` action to convert the empty string to null:
```js
// gatsby-node.js
exports.sourceNodes = ({ actions, schema }) => {
  actions.createTypes(
    schema.buildObjectType({
      name: `Test`,
      interfaces: [`Node`],
      fields: {
        num: {
          type: `Int`,
          resolve(source) {
            return source.num === ``
              ? null
              : source.num
          }
        }
      }
    })
  )
}
```

If you need to do this on more than one field, it might make sense to create a [custom field extension](https://www.gatsbyjs.org/docs/schema-customization/#creating-custom-extensions) for it.

**Comment by davidleger95** [comment]
Thanks @stefanprobst! This helped point me in the right direction.

**Comment by ddennis** [comment]
Would be great if you could share your solution?
