### ISSUE TITLE
Dynamic routes

### ISSUE THREAD

**Issue by klaygomes** [gatsbyjs/gatsby#1617]
Is there any plans to suport dynamic ssr like nextjs does?

**Comment by jbolda** [comment]
Having not used next.js myself, that is rather vague, haha. I am going to go with yes, as you run a build and ship static files to production. Also there are these api points if you need them: https://www.gatsbyjs.org/docs/ssr-apis/

**Comment by KyleAMathews** [comment]
Not like Next.js no. You can use React Router however to build dynamic client-only routes for AJAX driven portions of your site https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#creating-client-only-routes

We think almost all sites can be built using the "static" model — especially by following the [App Shell](https://developers.google.com/web/fundamentals/architecture/app-shell) model (which you get by simply installing [gatsby-plugin-offline](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/)).

On browsers that support Service Workers, on repeat visits, AppShell sites load faster than dynamic SSR.

An interesting model to explore w/ Gatsby would be [BigPipe](https://www.facebook.com/notes/facebook-engineering/bigpipe-pipelining-web-pages-for-high-performance/389414033919/). Serve static portions of pages from pre-built SSRed HTML then as soon as the request is received, start querying data for the different "pagelets" and push that data as it's returned and the React frontend would render pagelets as dynamic data arrives.

**Comment by klaygomes** [comment]
Thanks for you reply, it clarifies a lot of questions about decisions/design principles you have made about this project.

**Comment by SachaG** [comment]
When you say dynamic routes will not be supported, are you talking about dynamic pre-rendered routes like https://middlemanapp.com/advanced/dynamic-pages/ ? Or something else?

Because that kind of dynamic routing can be hugely useful. For example, maybe you have a YAML file containing a product catalog, and you want to generate a `/product/*productname*` page for every item in the YAML file.

**Comment by nickmaltsev** [comment]
@SachaG as i understand your question, you already can do this with gatsby. Take a look at [this](https://www.gatsbyjs.org/docs/creating-and-modifying-pages/)

**Comment by KyleAMathews** [comment]
@SachaG yeah language is hard :-) We do handle dynamic pages as Middleman defines them using `createPage` as @nickmaltsev linked to but we don't do dynamic pages like next.js which of course can have a running server that responds to novel requests and loads data dynamically from a database.

Basically this is build-time vs. runtime. Gatsby can dynamically create pages as long as it knows about the data at build-time.

If you do need run-time route creation with Gatsby, then you should do in client-side with react router with client-only routes https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#creating-client-only-routes

**Comment by SachaG** [comment]
Oh ok, the reason I got confused is that `next export` also handle *this* kind of dynamic routes. So I thought the thread was referring to that… Glad to know about `createPage` :)
