### ISSUE TITLE
Allow 404.js to be customized with pageContext supplied by gatsby-node.js

### ISSUE THREAD

**Issue by aaronshaf** [gatsbyjs/gatsby#16176]
My use-case:

I'd like to generate a 404 page from some of the same data that is used to generate my normal pages.

**Comment by iloveip** [comment]
Hi @aaronshaf,

Did you find a way to populate `404.html` page with pageContext?

**Comment by dannyvaughton** [comment]
I believe you can do this with a `404.js` in `src/pages` and using the `onCreatePage` hook.

Something like this:

```
const onCreatePage = async ({ page, actions }) => {
  const { createPage, deletePage } = actions;
  
  // Look for /404/ path
  if (page.path.match(/^\/404\/$/)) {
    const oldPage = { ...page };
    
    // Add page context
    page.context = {
      foo: 'bar'
    };
    
    // Recreate the modified page
    deletePage(oldPage);
    createPage(page)
  }
};

module.exports = onCreatePage;
```

**Comment by chrispytoes** [comment]
I need to insert context into my 404 page from a query, but the object passed into `onCreatePage` does not have the `graphql` function on it like `createPages` does. How do you make a query within `onCreatePage`?

**Comment by SachaG** [comment]
@chrispytoes I'm running into the exact same issue and as far as I can tell you can't make queries within `onCreatePage`, meaning you can't have dynamic data in your 404 page (or at least not without extra workarounds which I've yet to figure out…)
