### ISSUE TITLE
Cannot access fields on type `MarkdownRemark` in latest version of Gatsby

### ISSUE THREAD

**Issue by beccanelson** [gatsbyjs/gatsby#16191]
## Description

I am following the Gatsby theme tutorial, trying to create a new blog theme with gatsby 2.13.1 and `gatsby-transformer-remark`. Since I'm not currently using mdx, I started with the code from the original gatsby blog starter.

In `gatsby-node.js`:

```
exports.createPages = async ({ reporter, graphql, actions }) => {
  const { createPage } = actions

  const blogPost = path.resolve(`./src/templates/blog-post.js`)
  const result = await graphql(
    `
      {
        allMarkdownRemark(
          sort: { fields: [frontmatter___date], order: DESC }
          limit: 1000
        ) {
          edges {
            node {
              fields {
                slug
              }
              frontmatter {
                title
              }
            }
          }
        }
      }
    `
  )

  if (result.errors) {
    reporter.panic(result.errors)
  }

  // Create blog posts pages.
  const posts = result.data.allMarkdownRemark.edges

  posts.forEach((post, index) => {
    createPage({
      path: post.node.fields.slug,
      component: blogPost,
      context: {
        slug: post.node.fields.slug,
      },
    })
  })
}

exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions

  if (node.internal.type === `MarkdownRemark`) {
    const value = createFilePath({ node, getNode })
    createNodeField({
      name: `slug`,
      node,
      value,
    })
  }
}
``` 

### Steps to reproduce

1. Clone my repo at https://github.com/beccanelson/gatsby-theme-writer
2. run `yarn`
3. run `yarn workspace demo develop`

### Expected result

I would expect to still be able to query fields using the `allMarkdownRemark` graphql query. 

### Actual result

```
  GraphQLError: Cannot query field "fields" on type "MarkdownRemark".
```

If I downgrade gatsby versions to 2.2.5, the query works as expected, but is unable to shadow the template from the theme. If I log `node.internal.type` inside `onCreateNode`, it does not appear to ever be equal to `MarkdownRemark`. 

Aside from the `gatsby-theme-blog` which uses mdx, I cannot find any documentation for creating a theme using the current version of gatsby and `gatsby-trasformer-remark`. 

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.2
  npmGlobalPackages:
    gatsby-cli: 2.7.20
```

**Comment by alexluong** [comment]
Hi @beccanelson, I got your theme to work by doing the following:

1. Upgrade `gatsby` in `demo` and `gatsby-theme-writer` to the latest version. It's `2.13.42` right now, but I think the later version should work too. You may want to delete your `node_modules` to make sure everything is up to date.
2. Change

```
const blogPost = path.resolve(`./src/templates/blog-post.js`)
```

to

```
const blogPost = require.resolve(`./src/templates/blog-post.js`)
```

And your site seems to work for me. Although there is a problem with one of your query on the client regarding `frontmatter.description`, it should be fixable.

**Comment by beccanelson** [comment]
@alexluong Thanks for your help! I did upgrade to the latest version, and got it working again.

**Comment by dancingmonkey** [comment]
For anyone having troubles I have made a starter with only a home and about page created completely using markdown files like _index.md_ and _about/index.md_ inside the pages ( yes the standard directory so not a markdown-pages dir 👍 ). Pay special attention to the gatsby-node.js file which contains exactly what you need. Also don't get fooled by the variable _posts_ in this file as it also treats the home and about pages as kind of posts ( for lack of a better name ). 
https://github.com/dancingmonkey/gatsby-starter-hello-world
