### ISSUE TITLE
Field types in advance

### ISSUE THREAD

**Issue by devrchancay** [gatsbyjs/gatsby#16195]
Hello everyone! I have an acf for API Rest, which answers the following format:

```json
"acf": {
    "video": "",
    "dificultad": "media",
    "ingredientes": [
      {
        "cantidad": "2",
        "tamano": "tazas de ",
        "ingrediente": 47,
        "notas": ""
      }
  ],
    "porciones": "4",
    "tiempo": "45",
    "featured": true,
    "coverphoto": false
  },
```
<hr/>
but "ingredientes" are being omitted in the scheme

![image](https://user-images.githubusercontent.com/4138285/62080719-d5f2e200-b216-11e9-8413-d1e6c2408534.png)

and during the compilation, I get this message.

![image](https://user-images.githubusercontent.com/4138285/62080869-13f00600-b217-11e9-93d8-8fc954bec965.png)

I'm blocked read the documentation and try some options and I can't get it to work on the gatsby side.

**Comment by jlengstorf** [comment]
Hi @devrchancay! It looks like schema customization can help here. https://www.gatsbyjs.org/docs/schema-customization/#explicitly-defining-data-types

Something like this:

```js
exports.createSchemaCustomization = ({ actions }) => {
  actions.createTypes(`
    type Ingredients implements Node @dontInfer {
      # define all of your field types here
    }

    type wordpress_acf_recipeAcf implements Node @dontInfer {
      ingredients: [Ingrediente!]!
      # add the rest of the fields here
    }
  `)
}
```

Check the examples in the docs I linked for specifics. Let us know if this helps!

**Comment by devrchancay** [comment]
Thank you, solve it as follows:

```js
exports.createSchemaCustomization = ({actions}) => {
  actions.createTypes(`
    type Ingredients implements Node @dontInfer {
      cantidad: String
      tamano: String
      ingrediente: Int
      notas: String
    }

    type wordpress__wp_recipeAcf implements Node @dontInfer {
      dificultad:String
      video: String
      ingredientes: [Ingredients!]!
      porciones: Int
      tiempo: Int
      featured: Boolean
    }

    type wordpress__wp_recipe implements Node {
      acf: wordpress__wp_recipeAcf
    }
  `);
};
```
ps: @jlengstorf  I don't miss a twitch transmission of yours.

**Comment by Blumed** [comment]
@devrchancay Isn't this the issue? https://www.gatsbyjs.org/packages/gatsby-source-wordpress/?=wordpress#graphql-error---unknown-field-on-acf
