### ISSUE TITLE
[gatsby-plugin-sharp] fs read/write streams and sharp?

### ISSUE THREAD

**Issue by smurrayatwork** [gatsbyjs/gatsby#16193]
## Summary
In trying to look into how gatsby handles processing and transforming images, I started to look into process-file.js and noticed that for the most part, reading and writing from disc seems to happen without Node streams. Would using streams help performance wise in this file? Was this already tried out and determined to not be such a great idea?

An example would be changing processFile's transforms loop to create a sharp transformation pipeline that takes a single read stream, transforms the data, then writes the transformed data to disk. Something like (but not exactly):
```
const pipeline = sharp();
const readStream = fs.createReadStream(filename);
return transforms.map(async transform => {
  const { outputPath, args } = transform
  await pipeline.clone().toFile(outputPath);
});
const writeStream = fs.createWriteStream(outputPath);
readStream.pipe(pipeline).pipe(writeStream);
```
For the purposes of example, I've skipped the handling of extra sharp processing but can provide how that'd work too.

## Relevant information
[Examples of sharp streams with I/O](https://github.com/lovell/sharp/blob/v0.23.0/test/unit/io.js
)

**Comment by sidharthachatterjee** [comment]
@smurrayatwork We haven't tried this out as far as I know. 

Instinctively, I don't think I/O is the bottleneck here but happy to see a benchmark comparing the two approaches if you're interested!

**Comment by KyleAMathews** [comment]
Yeah — curious what the effects would be — could you benchmark this?

**Comment by smurrayatwork** [comment]
@KyleAMathews @sidharthachatterjee ,

Sure, I'll try my best! I have a WIP modification branch that's mostly completed using streams now. I need to clean up the code and get some benchmarks tied into it, but from what I was seeing, there wasn't a noticeable difference in speed at all.

**Comment by KyleAMathews** [comment]
How many images are you testing with?

**Comment by smurrayatwork** [comment]
@KyleAMathews around 3-4000, with lots of png images that are processed.

**Comment by smurrayatwork** [comment]
So I'm working on cleaning up this code currently and I remembered the real bottleneck for process-file.js at least: imagemin.

For some reason, imagemin doesn't support streams. They tried to at one point, but then removed support for it [due to some sort of unknown issues they were having with it](https://github.com/sindresorhus/gulp-imagemin/pull/19#issuecomment-41141997). This means that you always have to convert sharp's stream to a buffer which is then passed to imagemin-pngquant for processing. Imagemin-pngquant then returns a buffer, which you can then write to disk. If imagemin supported streams, this would likely speed things way up.

An alternative I was trying to experiment with was [pngquant](https://www.npmjs.com/package/pngquant) which supports using streaming with the CLI, which is technically what imagemin-pngquant does too, but I haven't gotten it to work just yet.

**Comment by smurrayatwork** [comment]
See this conversation on sharp performance and streams too:
https://github.com/lovell/sharp/issues/1815

**Comment by smurrayatwork** [comment]
Quick update on this issue:

I managed to fully get streams working, without imagemin-pngquant! This required a ton of research. Turns out that sharp already supports the exact same libraries imagemin-pngquant uses for its compression abilities, it just needs to a few steps to set up first:
- libvips needs to be compiled locally to support libimagequant. Libimagequant is the library pngquant uses for its compression. This can be done with brew for example:
`brew install vips`
`brew install libimagequant`
`export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/libimagequant/lib/pkgconfig`: Adds libimagequant to pkg config path so vips recognizes it.
`brew edit vips` - you need this to add the `--with-imagequant` flag, since brew stopped supporting flags
`brew re-install vips --build-from-source`
`
- Re-install sharp with npm.
- Set sharp to use the library by setting `palette: true` in with the `.png` method. This turns on using that algorithm. Then you just give that method the quality and compression settings you want and it works exactly the same as what imagemin is doing.

Once all of this is done, there's no need to convert things to buffers and you can just have read/write streams work with sharp, as it already can handle it.

Currently I'm not quite sure how to set up a proper benchmark, but I think it should be done as now I've things in a spot where it's worthwhile. I'm noticing about a 1/7th reduction in processing time over around 1000 png images, with the images ranging in resolution from 100 x 100, to 3999x3999.

**Comment by smurrayatwork** [comment]
Update:

I think I have some benchmarks now. I'm using gnu-time for these.
Node: 12.10.0

Original gatsby-plugin-sharp:
```
Command being timed: "node src/__tests__/stream.js"
        User time (seconds): 86.09
        System time (seconds): 64.50
        Percent of CPU this job got: 597%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:25.19
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1275764
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 397
        Minor (reclaiming a frame) page faults: 8781833
        Voluntary context switches: 4423
        Involuntary context switches: 4818575
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 1692
        Socket messages received: 5980
        Signals delivered: 846
        Page size (bytes): 4096
        Exit status: 0
```

Modified gatsby-plugin-sharp:
```
Command being timed: "node src/__tests__/stream.js"
        User time (seconds): 68.60
        System time (seconds): 43.11
        Percent of CPU this job got: 555%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:20.11
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1215360
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 411
        Minor (reclaiming a frame) page faults: 3013657
        Voluntary context switches: 1006
        Involuntary context switches: 4982318
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

Test Code:
```
const sharp = require(`../safe-sharp`)

const fs = require(`fs-extra`)

const { processFile } = require(`../process-file`)
const path = require('path');

const transforms = {
  args: {
    width: '100',
    height: '100',
    pngCompressionLevel: 9,
    toFormat: 'png',
    quality: 100,
    background: 'rgba(0,0,0,1)',
    trim: 0,
    rotate: 0,
    cropFocus: sharp.strategy.attention,
    fit: sharp.fit.cover,
    duotone: null,
    jpegProgressive: false,
  },
};
const runTest = async () => {
  await fs.readdir(path.resolve(__dirname, './stream_images'), (error, files) => {
    files.forEach( async (file) => {
      if (error) {
        throw error;
      }
      const fileTransform = Object.assign(transforms, { outputPath: path.resolve(__dirname, `./stream_test/${file}`)});
      await processFile(path.resolve(__dirname, `./stream_images/${file}`), [fileTransform], {
        stripMetadata: false,
      });
    });
  });
}
runTest();
```
