### ISSUE TITLE
Downgraded: gatsby-source-contentful@2.1.15 -> gatsby-source-contentful@2.0.47

### ISSUE THREAD

**Issue by isubhokarma** [gatsbyjs/gatsby#16203]
I think there might some bug/ issue with the library `gatsby-source-contentful@2.1.15` (version: current version), as there are no queries calls found in GraphQL Playground to fetch the **Rich-Content Images/ Assets**.

Downgrading the package to `gatsby-source-contentful@2.0.47` worked.

**Comment by pieh** [comment]
Can you provide example of queries that work in `gatsby-source-contentful@2.0.47`, but not in newer version?

**Comment by isubhokarma** [comment]
**The following code and query (unable to fetch the required data) isn't working with the latest version - 2.1.15**

**Here's the code to fetch image alt/ image URL only showing up on version - 2.0.47:**
```
const options = {
    renderNode: {
      "embedded-asset-block": node => {
        const alt = node.data.target.fields.title["en-US"];
        const url = node.data.target.fields.file["en-US"].url;
        return <img alt={alt} src={url} />;
      }
    }
  };
```

**And here's the query that showing up the image alt name and image URL only with version - 2.0.47:**
```
query {
  allContentfulBlogPost (
    sort: {
      fields: publishedDate,
      order: DESC
    }
  ) {
    edges {
      node {
        title
        slug
        publishedDate (formatString: "MMMM Do, YYYY")
        body {
          json
        }
      }
    }
  }
}
```
