### ISSUE TITLE
[docs] Update Table of Contents component to highlight sub-sections similar to Tutorial

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#16214]
## Summary

In the tutorial, when your viewport is in a certain section, the sidebar updates so the current section in view has a rebeccapurple color. Here's an example where on Part 4 of the Official Gatsby Tutorial, when I am in the "Data in Gatsby" section, it is highlighted in the sidebar

![Screenshot_2019-07-30 Data in Gatsby](https://user-images.githubusercontent.com/3685876/62131413-261a8480-b2a9-11e9-8ca0-deae36e13150.png)

I think this would be a good feature to have in the Table of Contents component that was newly added to .org.

**Comment by kushthedude** [comment]
@lannonbr I would like to work on this issue

**Comment by gillkyle** [comment]
It looks like this behavior was added in #16486, @kushthedude if you'd like to contribute elsewhere check out more open issues for ideas!
