### ISSUE TITLE
TypeError: Cannot read property 'includes' of null (UNHANDLED REJECTION)

### ISSUE THREAD

**Issue by florinme** [gatsbyjs/gatsby#16210]
## Description

My build is failing every time with an UNHANDLED REJECTION error. 

- Tried clearing cache
- Tried removing node_modules
- Tried debugging build

Note: If I force `callSite === false` in `node_modules/gatsby/dist/utils/stack-trace-utils.js` it builds fine. The issue seems to be on this line of file above:
```
    .find(callSite => !callSite.getFileName().includes(gatsbyLocation))
```

### Steps to reproduce

1. npm run clean
2. gatsby develop

### Expected result

It should build successfully.

### Actual result

`TypeError: Cannot read property 'includes' of null.` 

Stack Trace
```
  - stack-trace-utils.js:18 stackTrace.get.find.callSite
    [frontend-gatsby]/[gatsby]/dist/utils/stack-trace-utils.js:18:46
  
  - Array.find
  
  - stack-trace-utils.js:18 getNonGatsbyCallSite
    [frontend-gatsby]/[gatsby]/dist/utils/stack-trace-utils.js:18:6
  
  - stack-trace-utils.js:21 getNonGatsbyCodeFrame
    [frontend-gatsby]/[gatsby]/dist/utils/stack-trace-utils.js:21:20
  
  - api-runner-node.js:182 createPage
    [frontend-gatsby]/[gatsby]/dist/utils/api-runner-node.js:182:39
  
  - index.js:34 groups.forEach
    [frontend-gatsby]/[gatsby-paginate]/src/index.js:34:12
  
  - Array.forEach
  
  - index.js:32 createPaginatedPages
    [frontend-gatsby]/[gatsby-paginate]/src/index.js:32:10
  
  - gatsby-node.js:66 graphql.then.result
    /Users/florin/JayRay/South Sound YMCA Website - Documents/General/Development/southsoundymca.org/frontend-gatsby/gatsby-node.js:66:9
```

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.15.0/bin/npm
  Languages:
    Python: 2.7.14 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.43 => 2.13.43 
    gatsby-background-image: ^0.7.2 => 0.7.6 
    gatsby-image: ^2.2.1 => 2.2.7 
    gatsby-paginate: ^1.1.0 => 1.1.1 
    gatsby-plugin-compile-es6-packages: ^1.1.0 => 1.2.0 
    gatsby-plugin-emotion: ^4.1.0 => 4.1.2 
    gatsby-plugin-manifest: ^2.2.0 => 2.2.4 
    gatsby-plugin-netlify: ^2.1.0 => 2.1.3 
    gatsby-plugin-netlify-headers: ^1.0.1 => 1.0.1 
    gatsby-plugin-offline: ^2.2.0 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.2 
    gatsby-plugin-sharp: ^2.2.1 => 2.2.9 
    gatsby-plugin-sitemap: ^2.2.0 => 2.2.4 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.1.0 => 2.1.6 
    gatsby-source-wordpress: ^3.1.0 => 3.1.11 
    gatsby-transformer-sharp: ^2.2.0 => 2.2.5 
  npmGlobalPackages:
    gatsby-cli: 2.7.0

**Comment by pieh** [comment]
> Note: If I force `callSite === false` in `node_modules/gatsby/dist/utils/stack-trace-utils.js` it builds fine. The issue seems to be on this line of file above:
> 
> ```
>     .find(callSite => !callSite.getFileName().includes(gatsbyLocation))
> ```

Yeah, we do need to make `callSite.getFileName().includes(gatsbyLocation)` call safe to do. so something like:

```
.find(callSite => callSite && callSite.getFileName() && !callSite.getFileName().includes(gatsbyLocation))
```
I think is good way to do this

**Comment by florinme** [comment]
@pieh, thank you for confirming this. I went ahead and forked, created an issue branch, tested, and submitted a PR. This is my first PR so I hope I did it right :).

**Comment by wardpeet** [comment]
Successfully published:
 - gatsby@2.13.46
