### ISSUE TITLE
Start looking into Pull Panda

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#16211]
Have you guys heard of Pull Panda? It was [acquired by GitHub in June](https://github.blog/2019-06-17-github-acquires-pull-panda), is currently available as a [Marketplace App](https://github.com/marketplace/pull-panda) and will soon be fully integrated into GitHub itself (see last paragraph of the [acquisition announcement](https://github.blog/2019-06-17-github-acquires-pull-panda)).

Might be worth starting to look into it now. Specifically, it might help with implementing the "Next Steps" in [Kyle's blog post on not overlooking high-value PRs](https://www.bricolage.io/bulding-a-slack-bot-to-help-handle-large-numbers-of-prs/). This is one of the 3 areas Pull Panda focuses on:

> Pull Panda helps thousands of teams work together on code and improve their process along the way by combining three features: Pull Reminders, Pull Analytics, and Pull Assigner.
> 
> Pull Reminders: Get a nudge in Slack when a collaborator needs your review. Automatic reminders ensure that pull requests never slip through the cracks.
> Pull Analytics: From wait times to top contributors, get real-time insight into the effectiveness of your team’s process. Then make data-driven improvements that create a more transparent and accountable culture.
> Pull Assigner: Automatically distribute code across your team, so no one gets overloaded and knowledge gets spread around.

![pull-panda-post](https://user-images.githubusercontent.com/30958850/62124016-1e66da00-b2c1-11e9-8c27-453acb5b5d41.png)

**Comment by sidharthachatterjee** [comment]
We've been using it since the past few weeks and love it! Especially the Slack notifications for pull requests. 

Thank you for pointing this out nonetheless @janosh 🙌

**Comment by janosh** [comment]
Good to know. :)
