### ISSUE TITLE
gatsby-plugin-google-analytics has a syntax error

### ISSUE THREAD

**Issue by tinder-kyleboss** [gatsbyjs/gatsby#16226]
## Description
Projects that use gatsby-plugin-google-analytics are noticing console errors. For example: https://github.com/gatsbyjs/gatsby/pull/15280#issuecomment-516401237

### Steps to reproduce

1. Add `gatsby-plugin-google-analytics` to the project with `yarn add gatsby-plugin-google-analytics` as well as adding it to the plugins of `gatsby-config`.
2. `gatsby build && gatsby serve`.
3. Go to the page (e.g. localhost:9000) and observe the console.

### Expected result

No syntax errors should exist.

### Actual result

<img width="1124" alt="gatsby-plugin-google-analytics-console-error" src="https://user-images.githubusercontent.com/42850683/62157471-18252d80-b2c2-11e9-81d2-7eacd66c2ca4.png">

### Environment

  ```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v11.12.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 62.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.0.59 => 2.4.2 
    gatsby-cli: ^2.7.21 => 2.7.21 
    gatsby-image: ^2.0.0 => 2.0.41 
    gatsby-plugin-catch-links: ^2.0.0 => 2.0.13 
    gatsby-plugin-eslint: ^2.0.1 => 2.0.5 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-feed: ^2.0.0 => 2.2.0 
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.19 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.5 
    gatsby-plugin-manifest: 2.0.5 => 2.0.5 
    gatsby-plugin-node-fields: ^1.0.0 => 1.0.0 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.12 
    gatsby-plugin-robots-txt: ^1.3.0 => 1.4.0 
    gatsby-plugin-sass: ^2.0.0 => 2.0.11 
    gatsby-plugin-sharp: 2.0.7 => 2.0.7 
    gatsby-plugin-sitemap: ^2.0.0 => 2.1.0 
    gatsby-plugin-styled-components: ^3.0.0 => 3.0.7 
    gatsby-plugin-twitter: ^2.0.0 => 2.0.13 
    gatsby-source-filesystem: ^2.0.1 => 2.0.33 
    gatsby-source-wordpress: ^3.0.0 => 3.0.58 
    gatsby-transformer-sharp: 2.1.4 => 2.1.4 

```

**Comment by reibusintl-eb** [comment]
I'm also experiencing the same issue, my google analytics account hasn't logged any activity since the error messages started displaying
