### ISSUE TITLE
[transformer-remark] infer title/slug

### ISSUE THREAD

**Issue by craig-mulligan** [gatsbyjs/gatsby#1622]
I know there are other-ways around, but seems like a good addition to automatically add title and slug to the `node.frontmatter` based on first title and filePath respectively, this way it's not necessary to include frontmatter in every file. 

Everyones thoughts?

**Comment by KyleAMathews** [comment]
I think this is a great pattern but shouldn't be added to the transformer-remark plugin. Markdown is used in a 1000 different contexts of which many the markdown isn't coming from a file on disk. 

There's also the problem of what algorithm to use for creating the slug, etc. of which there's 1000 different opinions.

This would however be a great fit for a plugin (which would be a great fit for hosting here).

**Comment by craig-mulligan** [comment]
Oh right I hadn't considered other usecases :P, I guess this is a good application for `createNodeField`. I've worked around the problem for now, I'm going to close until I have a time to create the plugin.
