### ISSUE TITLE
[Seeking For Help] Route-based conditional rendering is not working properly in production site.

### ISSUE THREAD

**Issue by vizFlux** [gatsbyjs/gatsby#1623]
Deployed my website, the contents within work only if you start navigating from `/` to every other page. However, access to a specific path for example `example.com/about` causes conditional rendering based on route to break. Wondering if anyone out there facing the similar problem, been bothered by this issue for hours.

**Comment by MarcCoet** [comment]
@vizFlux try and give more details on your implementation if you are still struggling with that.

**Comment by vizFlux** [comment]
@MarcCoet I actually opened another issue there with more details. #1632

**Comment by MarcCoet** [comment]
maybe close this one then @vizFlux
