### ISSUE TITLE
[starters] Update the docs on how to use the starters from this mono repo

### ISSUE THREAD

**Issue by lipis** [gatsbyjs/gatsby#16237]
Outdated docs: https://www.gatsbyjs.org/tutorial/part-one/#using-gatsby-starters

**Comment by wardpeet** [comment]
Hey @lipis.

The documentation is still correct. We sync the monorepo with the starter repos so starters can be installed. 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
