### ISSUE TITLE
Hot reloading: Initial React state persists until manual refresh. Is this normal?

### ISSUE THREAD

**Issue by marinoguerieri** [gatsbyjs/gatsby#16247]
## Description

Firstly let me say that I'm not sure whether this is in fact a bug, maybe it's normal but it just made me spend 30 minutes trying to find out what's wrong with my code when in fact it was due to hot reloading "issue".

What happens is that React state that is initialized in constructor is not "applied" until manual refresh (one changes the `this.state={...}` in the constructor to something else but it doesn't take effect until reload).

### Steps to reproduce

1) Initialize React state (in constructor).

```
state = {
a: 5
}
```

2) Do a `console.log(this.state.a)` in the browser. You get `5`.

3) Change the constructor code to the following (i.e. just change the value to anything different)

```
state = {
a: 7
}
```

3) _(Hot reload happens after saving the former code.)_ 
Do a `console.log(this.state.a)`. **Again it is `5` (when in fact it should be `7`).** 

Full code:
```
class Something extends Component {
  state = {
    a: 5
    },
  };

  render() {
    console.log(this.state.a);
  }
}
```

### Expected result
`Console.log` should return new state (e.g. `7`, not `5`)

That was weird in my opinion because I presumed that hot reloading indeed reloads everything, however React state was unaffected by that.

### Actual result

Console.log returns old state (5).

### Environment

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.13.34 => 2.13.34 
    gatsby-image: ^2.0.23 => 2.2.6 
    gatsby-plugin-netlify: ^2.1.3 => 2.1.3 
    gatsby-plugin-netlify-cms: ^4.1.6 => 4.1.6 
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.1.2 
    gatsby-plugin-sass: ^2.0.7 => 2.1.3 
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9 
    gatsby-remark-copy-linked-files: ^2.1.3 => 2.1.3 
    gatsby-remark-images: ^3.1.7 => 3.1.7 
    gatsby-remark-relative-images: ^0.2.1 => 0.2.2 
    gatsby-source-filesystem: ^2.1.6 => 2.1.6 
    gatsby-transformer-remark: ^2.6.9 => 2.6.9 
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4

**Comment by freiksenet** [comment]
Hello @marinoguerieri!

This is how hot reloading works. It tries to preserve the state, so that you can see updates in components without refresh. It can't know if you want to see the update to the whole lifecycle or just to parts that aren't affected by it.

I'll be closing this issue, we won't be fixing it - this is the expected behavior for hot reloading.

**Comment by marinoguerieri** [comment]
I see. I guess I could have figured that out by myself but I had just been startjng to use Gatsby and there had been too much going on (errors popping out everywhere), causing a kind of "change blindness" to what is in fact a correct behaviour. :-)

In fact, the Hot Module Replacement [documentation](https://webpack.js.org/concepts/hot-module-replacement/) clearly says:

> **Hot Module Replacement**
> - Hot Module Replacement (HMR) exchanges, adds, or removes modules while an application is running, without a full reload. This can significantly speed up development in a few ways:
> 
> - **Retain application state which is lost during a full reload.**
> - Save valuable development time by only updating what's changed.
> - Instantly update the browser when modifications are made to CSS/JS in the source code, which is almost comparable to changing styles directly in the browser's dev tools.
> 

I'm just puting it out there for others who might be having the same "issue", so that this question hadn't been all for nothing. :)
