### ISSUE TITLE
query compiler error reporting is broken

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#16248]
It looks like the error reporting in query compiler here assumes that this can only throw when a fragment is missing (error no. 85908):

https://github.com/gatsbyjs/gatsby/blob/2c05f11e967f894efe311ca03cded47eb634084c/packages/gatsby/src/query/query-compiler.js#L295-L320

This means that e.g. errors like `"Invariant Violation: GraphQLIRPrinter: Need an InputObject type to print objects."` are swallowed, because the catch block itself [will throw](https://github.com/gatsbyjs/gatsby/blob/2c05f11e967f894efe311ca03cded47eb634084c/packages/gatsby/src/query/query-compiler.js#L310) when `fragmentName` is `null`.

**Comment by m-allanson** [comment]
@stefanprobst hmm yeah the catch block should make less assumptions about the error here. Then we could handle specific types of error, but also fall back to a more generic error. 

This PR is a good reference for how to add new structured errors: https://github.com/gatsbyjs/gatsby/pull/15244/files.

I'd love to see a PR fixing this 😄

**Comment by LekoArts** [comment]
I think this has been solved since then.
