### ISSUE TITLE
HMR Failing on Windows

### ISSUE THREAD

**Issue by jameyvillages** [gatsbyjs/gatsby#16263]
## Summary

HMR failing on Windows.

Gatsby works great at home, but not at work. If this is an outlier we can chalk it up to bad a machine and close.

Share your thoughts.

## Relevant information

Build tools installed as suggested in Gatsby for Windows docs.

Commands run

```bash
npm uninstall node-gyp -g
npm config set python python2.7
npm config set msvs_version 2015
npm cache clean -f
npm install
```

### Environment (if relevant)

gatsby info

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1630 v4 @ 3.70GHz
  Binaries:
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/gleasonj/.windows-build-tools/python27/python
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.13.44 => 2.13.45
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-source-filesystem: ^2.1.6 => 2.1.7
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5

### File contents (if changed)

Default starter

![cmd](https://user-images.githubusercontent.com/53302889/62244815-3cf6cf00-b3ae-11e9-8589-6d4752a08c0e.PNG)

![console](https://user-images.githubusercontent.com/53302889/62244821-3ec09280-b3ae-11e9-865c-57dba6c1e4eb.PNG)

![network_tab](https://user-images.githubusercontent.com/53302889/62244827-4122ec80-b3ae-11e9-89a6-c8e18ab12d07.PNG)

![networ_tab-timing](https://user-images.githubusercontent.com/53302889/62244838-47b16400-b3ae-11e9-9c2a-962dc3c4b284.PNG)

![networ_tab-headers](https://user-images.githubusercontent.com/53302889/62244842-4aac5480-b3ae-11e9-999c-50e9c44efcd7.PNG)

**Comment by elken** [comment]
Try under [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and see if that makes any difference.

**Comment by wardpeet** [comment]
Hi @jameyvillages!

I don't have this issue on windows 😕.

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜
