### ISSUE TITLE
Warn if function is used in root site config

### ISSUE THREAD

**Issue by ChristopherBiscardi** [gatsbyjs/gatsby#16265]
## Description

If you write a gatsby-config.js in the root of your site with the function style, it will fail in weird ways because plugins aren't added when you think they are.

(I'm on my phone and accidentally deleted the rest of the template I'm sorry 😭)

# Solution 

In bootstrap/index.js we should add a typeof config === function check on the root config before it is passed in to loadThemes and reporter.panic with a nice error message if it is a function

**Comment by cephalization** [comment]
I can take a peek

**Comment by cephalization** [comment]
Writing test now

**Comment by wardpeet** [comment]
Successfully published:
 - gatsby@2.13.46
