### ISSUE TITLE
[gatsby-remark-images] allow captions on externally hosted images

### ISSUE THREAD

**Issue by mguida22** [gatsbyjs/gatsby#16276]
## Summary

Allow for captions on images that are loaded from an external source.

### Basic example

with this config
```
options: {
  showCaptions: true
}
```

show captions from this markdown
```
![flowers](https://i.imgur.com/7DxkqAV.jpg "paintbrush flowers")
```

### Motivation

It'd be great to show captions on images that are hosted on other sites. This would allow consistent writing of markdown alt/title/captions regardless of how image is served. 

It looks like [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/index.js#L343) it's ignored if it's not a relative path. I'd be happy to make a PR for this if it's desired!

**Comment by freiksenet** [comment]
Thank you for reporting this!

Would you like to make a PR that adds that functionality? We would greatly appreciate that.

Thanks! :purple_heart: :muscle:

**Comment by mguida22** [comment]
Yup, I'll get started on a PR!
