### ISSUE TITLE
Sourcemap error in firefox only

### ISSUE THREAD

**Issue by qipoy** [gatsbyjs/gatsby#16274]
**how to clear warning on the console.` Source map error: TypeError: Invalid URL:  ...`**

this warning is only show on the **firefox** browser when i'am running in development mode. in chrome its always clear. 

![screenshot](http://images2.imagebam.com/fe/ea/b7/4849ea1289695674.png)

**Comment by elken** [comment]
`Toolbox Options -> Advanced -> Enable Source Maps` should remove the errors.

**Comment by qipoy** [comment]
> `Toolbox Options -> Advanced -> Enable Source Maps` should remove the errors.



did you mean disable Source Maps / uncheck ?  i have enable that.
![ss_fail-sources-map](https://user-images.githubusercontent.com/15064152/62304601-7f043b80-b4a8-11e9-9c82-c20e60575ed4.png)

**Comment by elken** [comment]
Uncheck it and that should remove the errors.

**Comment by wardpeet** [comment]
It seems like an upstream error like @elken mentioned https://github.com/webpack/webpack/issues/1194

I'm closing this one as there isn't much we can do about it :cry:. There is no easy upstream fix we can do. @qipoy it's a warning so it shouldn't break your site anyway so you can just clear it. Sorry for the inconvenience.
