### ISSUE TITLE
Can't add breakpoints in Chrome DevTools

### ISSUE THREAD

**Issue by marcinsydor** [gatsbyjs/gatsby#16281]
## Description

I'm not able to add breakpoints in Chrome DevTools after updating gatsby to version: `2.13.45`

### Steps to reproduce

Use official theme starter
`https://github.com/gatsbyjs/gatsby/tree/master/themes/gatsby-starter-theme`

### Expected result

Be able to debug website in DevTools

### Actual result

When I click on the line number bar I can't add a breakpoint. If I right-click and choose "Add breakpoint" the breakpoint is not showing up.

Just noticed that I'm able to add a breakpoint but on the first line only.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 66.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.45 => 2.13.45 
    gatsby-theme-blog: ^1.0.0 => 1.0.0 
    gatsby-theme-notes: ^1.0.0 => 1.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.4.8```

**Comment by elken** [comment]
AFAIK you can only debug the build process as documented [here](https://www.gatsbyjs.org/docs/debugging-the-build-process/) with node.

**Comment by marcinsydor** [comment]
I'm not talking about the build process, I'm just trying to debug React components. Have not had any problem with it so far. But since I updated Gatsby to the latest version I can't do it anymore. I tested it on tow different MacBooks. I also updated Chrome to version 76 but nothing has changed.
If I add `debugger` code line to my component in the editor then the breakpoint is cached but it is moved to the first line in the component.

**Comment by elken** [comment]
Seems to be a visual bug with manual `debugger` lines.

![Image](https://prnt.sc/on092g)

I can still step through and the locals update accordingly.

**Comment by marcinsydor** [comment]
Just to confirm, did you use `gatsby-starter-theme` project to replicate this issue? Could also please fix that image link so I can see it?

**Comment by elken** [comment]
Yep, just cloned it fresh. Updated comment but: https://prnt.sc/on092g

**Comment by marcinsydor** [comment]
Thanks, I can see you can replicate it. You won't be able to add a breakpoint to e.g. line number 9. All the line numbers part of 1 are greyed out.

**Comment by elken** [comment]
Nope but manual debugger lines work fine. If you want to debug react components in isolation I would recommend storybook. 

⁣Regards,
Ellis Kenyő

GitLab | GitHub | Keybase | elken.me​

**Comment by marcinsydor** [comment]
I just want to debug my sites in DevTools the same way I've been doing so far. 
If you can't replicate this issue can I ask you do make the same screenshot but with the blue breakpoint on the number lines block, please?

**Comment by elken** [comment]
I have replicated this issue and marked as a bug. In the meantime, manual debugger lines work fine apart from the visual representation on the code. Stepping works fine.

**Comment by marcinsydor** [comment]
Sorry, I misunderstood you, I see what mean now.

**Comment by kimbaudi** [comment]
I'm glad I found this issue. I was going crazy because I can no longer add breakpoints to source files in Chrome DevTools when I was able to do so before.

**Comment by wardpeet** [comment]
Thanks for reporting. It seems like source-maps are broken on develop. We'll investigate 🕵

**Comment by yoavniran** [comment]
Ive also been experiencing this since i upgraded to version 2.13.39
been going crazy, thinking it was something i was doing wrong. 
makes it very difficult to develop... :( hopefully will be fixed soon

**Comment by marcinsydor** [comment]
Yes, it's very difficult to debug but also if you have an error in the app it's not showing the right line of the problem which is very confusing. I've changed the version strictly to `2.13.25` and all works fine now.

**Comment by Galzk** [comment]
> Thanks for reporting. It seems like source-maps are broken on develop. We'll investigate 🕵
In the babel config - babel-preset-gatsby
"sourceMaps": "inline"
Might solve the problem?
Interesting why the regression has occured, but for now as @marcinsydor pointed **2.13.25** works well with the debugger

**Comment by ryudice** [comment]
I'm having this issue as well. Is there any workaround or should we just downgrade to 2.13.25?

**Comment by ryudice** [comment]
Confirming downgrading to 2.13.25 works by the way.

**Comment by ryudice** [comment]
This is still happening, shouldnt be closed

**Comment by patspam** [comment]
> > Thanks for reporting. It seems like source-maps are broken on develop. We'll investigate 🕵
> 
> In the babel config - babel-preset-gatsby
> "sourceMaps": "inline"
> Might solve the problem?
> Interesting why the regression has occured, but for now as @marcinsydor pointed **2.13.25** works well with the debugger

FYI The sourceMaps inline suggestion didn't work for me.

**Comment by max-l** [comment]
Please reopen this issue !  Not being able to debug from the browser is a pain !

**Comment by sbodi10** [comment]
When downgrading to `2.13.25`, I get the following error when running `npm run start`

The above error occurred in the <StoreStateProvider> component:
    in StoreStateProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you 
provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.

This does seem like a react error, but why would this result from downgrading gatsby?

**Comment by jkodu** [comment]
Is there a fix to this yet?

**Comment by marcinsydor** [comment]
Just tested 2.17.6 version and nothing has changed. I reported it 3 months ago I also spoke to @davidbailey00 about that problem on Gatsby Days London a few weeks ago. It's a shame that we still need to work with 2.13.25 version.

**Comment by MarkosKon** [comment]
Changing the [webpack devtool](https://webpack.js.org/configuration/devtool/#development) to `eval-source-map` during [develop stage](https://www.gatsbyjs.org/docs/add-custom-webpack-config/) solves the issue for me:

```js
// gatsby-node.js
exports.onCreateWebpackConfig = ({ stage, actions }) => {
  if (stage === "develop") {
    actions.setWebpackConfig({
      devtool: "eval-source-map",
    })
  }
}
```

I still have to [reload the page](https://github.com/microsoft/vscode-chrome-debug/blob/master/README.md#my-breakpoints-arent-hit-whats-wrong) to hit the breakpoints. Also, the breakpoints in JSX are sometimes 1 line off.

**Comment by ryudice** [comment]
Are we ever getting a fix for this?

**Comment by AlbyIanna** [comment]
> Changing the [webpack devtool](https://webpack.js.org/configuration/devtool/#development) to `eval-source-map` during [develop stage](https://www.gatsbyjs.org/docs/add-custom-webpack-config/) solves the issue for me:
> 
> ```js
> // gatsby-node.js
> exports.onCreateWebpackConfig = ({ stage, actions }) => {
>   if (stage === "develop") {
>     actions.setWebpackConfig({
>       devtool: "eval-source-map",
>     })
>   }
> }
> ```
> 
> I still have to [reload the page](https://github.com/microsoft/vscode-chrome-debug/blob/master/README.md#my-breakpoints-arent-hit-whats-wrong) to hit the breakpoints. Also, the breakpoints in JSX are sometimes 1 line off.

This worked for me! As a temporary fix, just paste those lines at the end of your `gatsby-node.js` file.

@wardpeet are you going to implement this solution in the default webpack config?

**Comment by lucasgdev** [comment]
Same problem here, please solve it guys! =/

**Comment by kaceto104** [comment]
Hi...!!!

Not being able to debug from the browser.. please help guys

**Comment by xuchen509** [comment]
The workaround doesn't work for me. I'm on Gatsby 2.15.x and please address the issue thanks!

**Comment by KunalBurangi** [comment]
yes, this issue is happening with me too and I am also unable to resolve it completely.  But I got a workaround just add a comment above the line you are trying to add a breakpoint. once you do that the below line will be available for adding the breakpoint. I don't know if this will work for everyone but it worked for me

**Comment by ndglover** [comment]
@KunalBurangi - this worked for me when using version 2.17.54.

Since updating to the gatsby 2.21.27 it is no longer an issue for me and doesn't require any workarounds.

**Comment by LekoArts** [comment]
I'll close this as resolved this is working in the latest version. We also now use:

https://github.com/gatsbyjs/gatsby/blob/7110189fda3942aba27cf35f577ce14d7b252d0b/packages/gatsby/src/utils/webpack.config.js#L277-L279
