### ISSUE TITLE
[question/theme] How do we pass components required for MDX in gatsby-theme-notes?

### ISSUE THREAD

**Issue by sonapraneeth-a** [gatsbyjs/gatsby#16283]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
@sonapraneeth-a If I understand your question correctly, you're asking how to setup components to use for base tags like p and h1. 

You should be able to do this using `MDXProvider` in `wrapRootElement` as documented in https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/#mdxprovider

Here is an inline example
```
import { MDXProvider } from "@mdx-js/react"

const MyH1 = props => <h1 style={{ color: "tomato" }} {...props} />
const MyParagraph = props => <p style={{ fontSize: "18px", lineHeight: 1.6 }} />

const components = {
  h1: MyH1,
  p: MyParagraph,
}

export const wrapRootElement = ({ element }) => (
  <MDXProvider components={components}>{element}</MDXProvider>
)

```

**Comment by sidharthachatterjee** [comment]
You can also shadow the `components` file in  `src/gatsby-plugin-theme-ui/components.js`

https://theme-ui.com/gatsby-plugin/#components

**Comment by sonapraneeth-a** [comment]
```gatsby-theme-notes``` does not seem to have ```components.js``` for shadowing (```https://github.com/gatsbyjs/gatsby/tree/master/themes/gatsby-theme-notes/src/gatsby-plugin-theme-ui```). I have tried by shadowing ```index.js``` in ```src/gatsby-theme-notes/gatsby-plugin-theme-ui/index.js``` which did not work.

**Comment by sidharthachatterjee** [comment]
Cc @ChristopherBiscardi
