### ISSUE TITLE
[docs] "Adding React Components" docs page

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#16288]
## Summary

As discussed in the Community Maintainers meeting July 24, we discussed it could be useful to have a page describing things to remember when adding React libraries to your Gatsby site.

This could mention things like:

- Looking out for components that depend on the `window` object and then mentioning to either use conditionals to check for these or drop these into `componentDidMount` or `useEffect` so it is only used client-side
- Components that may not have SSR support by default, and then looking for methods to add SSR

It was brought up that these two pages do have similar content that we could pull from / cross-reference:

- [Debugging HTML Builds](https://www.gatsbyjs.org/docs/debugging-html-builds/)
- [Porting From CRA to Gatsby](https://www.gatsbyjs.org/docs/porting-from-create-react-app-to-gatsby/)

@gatsbyjs/learning Is there anything else in particular that could be useful in a page like this? As well, where should this document live as we discussed in the meeting, having a high discoverability for this is important.

**Comment by alexluong** [comment]
Also, it's not just React components. Other libraries may also need `window` object too. One example is `firebase` and everything around it.

**Comment by marcysutton** [comment]
Sounds like a good idea to me! I saw some questions about web components in the issue queue, too. More instructions on how to integrate various component types would be well received.

**Comment by davwheat** [comment]
I can try to do this. No promises though.
