### ISSUE TITLE
[gatsby-plugin-offline] Static routes not working offline

### ISSUE THREAD

**Issue by kogal** [gatsbyjs/gatsby#16308]
## Description

The static pages not served when offline, if you change route or reload.

### Steps to reproduce

1) Download, build and serve the gatsby-starter-blog starter.
2) At first visit (sw registration) if you disable the js and reload, the static content is served correctly
3) If you enable the js and navigate to another page, or reload and repeat step 2, you get a blank page (the offline-plugin-app-shell-fallback without data).

### Expected result

The static page should be served

What should happen?

The static page is not served

### Actual result

I get the the offline-plugin-app-shell-fallback without data

### Environment

System:
    OS: macOS 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
    Yarn: 1.6.0 - ~/.yarn/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.12.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0.1
    Safari: 12.1
  npmPackages:
    gatsby: ^2.13.45 => 2.13.45
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-feed: ^2.3.6 => 2.3.6
    gatsby-plugin-google-analytics: ^2.1.6 => 2.1.6
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-plugin-typography: ^2.3.2 => 2.3.2
    gatsby-remark-copy-linked-files: ^2.1.4 => 2.1.4
    gatsby-remark-images: ^3.1.7 => 3.1.7
    gatsby-remark-prismjs: ^3.3.3 => 3.3.3
    gatsby-remark-responsive-iframe: ^2.2.4 => 2.2.4
    gatsby-remark-smartypants: ^2.1.2 => 2.1.2
    gatsby-source-filesystem: ^2.1.7 => 2.1.7
    gatsby-transformer-remark: ^2.6.10 => 2.6.10
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5
  npmGlobalPackages:
    gatsby: 2.7.3

**Comment by kogal** [comment]
Never mind, it must have been an issue with cache left from another sw.
I'm closing it for now.

**Comment by kogal** [comment]
I'm gonna have to re-open this, as it is happening again and I have not touched anything in the deployment. I'm guessing it is a caching issue, but I'm not really familiar with service workers.

**Comment by Seldszar** [comment]
I have a similar issue with that. I'll also take https://gatsby-starter-blog-demo.netlify.com/ as example.

One the home page, after the initial load, I switch to offline but I get a 404 error. I go to a blog post, reload the page, go back to the home page and switch to offline, it works.

After investigation, it seems that "custom-navigation-whitelist" (IndexedDB) is the source of this issue. I think the current page should be cached during the initial loading.

**Comment by kogal** [comment]
Not stale

**Comment by sidharthachatterjee** [comment]
Cc @davidbailey00

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v3 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction].

[reproduction]: https://gatsby.dev/reproduction
