### ISSUE TITLE
[gatsby-plugin-shopify] Remove undocumented ProductType query

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#16317]
This would be a breaking change, but Shopify's GraphQL API no longer documents the `ProductType` type and the query for product types has started timing out. The product type data is still available via the `product` query, so we don't lose any data by removing this.

Recommendation:

1. Remove the `PRODUCT_TYPE` query in `gatsby-source-shopify`
	- Remove the query itself ([here](https://github.com/gatsbyjs/gatsby/blob/944363288d51d2cd0b845dc46f028122fba9d9a9/packages/gatsby-source-shopify/src/queries.js#L224-L238)) and any code that uses it
2. Remove the `ProductType` node ([here](https://github.com/gatsbyjs/gatsby/blob/944363288d51d2cd0b845dc46f028122fba9d9a9/packages/gatsby-source-shopify/src/nodes.js#L19)) an all the code that relies on it

**NOTE:** This will be a breaking change for the plugin!

As a bonus: some of the queries are deprecated in this plugin. This is not an issue, strictly speaking, but refactoring to use the up-to-date queries will help us stay inline with Shopify's API and docs.

This could be a great way for someone new to Gatsby to get a first PR in!

**Comment by nivekselig** [comment]
I'll take a look at it. I just started using Gatsby this week.

**Comment by mimibar** [comment]
Is this assigned? I think I have identified the changes needed.

**Comment by pqt** [comment]
It's not, would you like to take this one on @mimibar?

**Comment by cj2** [comment]
Thanks, @jlengstorf! This helped me get past the build issue.

**Comment by Aswinpookkatt** [comment]
Is issue still open?

**Comment by pqt** [comment]
Yeah, just pending the merge of #16320 @Aswinpookkatt

**Comment by sidharthachatterjee** [comment]
Published in `gatsby-source-shopify@3.0.0` thanks to @mimibar 🥇
