### ISSUE TITLE
[gatsby-telemetry] error: src/postinstall.js not found in Linux environments

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#16315]
## Description

In a Linux instance, Gatsby CLI is breaking currently because it doesn't find `src/postinstall.js` from gatsby-telemetry when running `gatsby new` with NPX.

### Steps to reproduce

1) Spin up a linux instance (Either a VM or container)
2) Download Node (tested on both 10 and 12 and breaks on both)
3) run `npx gatsby new .`

### Expected result

Should just run

### Actual result

Error:

```
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/17/lib/node_modules/gatsby/node_modules/core-js/scripts/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/17/lib/node_modules/gatsby/node_modules/core-js-pure/scripts/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/17/lib/node_modules/gatsby/node_modules/gatsby-telemetry/src/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-telemetry@1.1.11 postinstall: `node src/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-telemetry@1.1.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-01T21_57_39_926Z-debug.log
Install for [ 'gatsby@latest' ] failed with code 1
```

This may be an issue with this commit: https://github.com/gatsbyjs/gatsby/commit/9d32f3cf45a8155018c4fae0d5ad80f0e195a348

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by jamo** [comment]
Hi @lannonbr, sorry for the late reply. 

I'm still looking for a proper fix, but it appears that `npx` fails with `preinstall` and `postinstall` scripts.
I hope you were able to work around this issue, but a you can`npm -g gatsby-cli` and then run the `gatsby new` without npm.

**Comment by lannonbr** [comment]
@jamo Yeah it was a colleague of mine that was getting stuck with this, he did `npm i -g gatsby-cli` in the docker container he was working in to get around this issue for the time being.

**Comment by jamo** [comment]
Perfect. I'm [pinging npm](https://npm.community/t/npx-crashes-on-postinstall-script/9360) to see if we can figure out a way to make this work with `npx`. Looks like quite a few other modules are impacted as well

**Comment by jamo** [comment]
Closing this as the issue has been reported to upstream npm/npx and we are waiting for them to resolve the issue.
Apologies for the inconvenience
