### ISSUE TITLE
Gatsby Plugins Library broken with gatsby themes

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#16318]
## Description

Clicking on any gatsby plugin in the plugins library causes 404

### Steps to reproduce

go here https://www.gatsbyjs.org/plugins/

and click on any gatsby theme

### Expected result

it should work

### Actual result

![image](https://user-images.githubusercontent.com/6764957/62333679-6a1cad80-b492-11e9-9746-d69d4684640e.png)

**Comment by DSchau** [comment]
Hey Shawn!

Thanks for this -- algolia's index sometimes has some issues, but this is getting a little frustrating. I'll take a deeper look at this right now.

As you can see not _all_ themes are broken, but certainly it seems that a great majority of them are.

- https://www.gatsbyjs.org/packages/gatsby-theme-documentation/?=gatsby-theme
- https://www.gatsbyjs.org/packages/gatsby-theme-notes/?=gatsby-theme
- https://www.gatsbyjs.org/packages/gatsby-theme-blog/?=gatsby-theme
- https://www.gatsbyjs.org/packages/gatsby-theme-powerboard-base/?=gatsby-theme

etc.

**Comment by sw-yx** [comment]
ok :) i'm not sure its algolia's problem, this is maybe a broken build? in any case i'll leave it with you. unsubscribing.

**Comment by wardpeet** [comment]
This one seems fixed by itself so I'll be closing this one.
