### ISSUE TITLE
Timeout Error while sourcing data with Gatsby-source-shopify + ProductType nodes are not available for queries.

### ISSUE THREAD

**Issue by RobRuizR** [gatsbyjs/gatsby#16313]
## Description

I'm getting this error on the console while using the Gatsby-source-shopify plugin: 

```
an error occurred while sourcing data
- 
  message: Timeout
query: 
  """
      query GetProductTypes($first: Int!) {
        shop {
          productTypes(first: $first) {
            pageInfo {
              hasNextPage
            }
            edges {
              cursor
              node
            }
          }
        }
      }

  """
variables: 
  first: 10
  after: null
```

Because of this, ProductType nodes are not available for queries. I've tried reducing the paginationSize for the plugin, but it's not changing anything.

### Steps to reproduce

I actually am not sure on how to reproduce this as it happened without changing anything. However, it can be seen in this project:
- [Repository](https://github.com/RobRuizR/gatsby-theme-simple-shopify)
- [Logs for yesterday's build](https://app.netlify.com/sites/gatsby-theme-simple-shopify/deploys/5d4282acd8026300097dc819)
- [Logs for today's build](https://app.netlify.com/sites/gatsby-theme-simple-shopify/deploys/5d435048f66e8100090f7248)

### Expected result

ProductType nodes should be available for queries.

### Actual result

ProductType nodes are not available for queries.

### Environment

System:                                                                                                                                                                                       
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)                                                                                                                                           
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz                                                                                                                                       
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.10.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 68.0.1

**Comment by elken** [comment]
Seems to be an upstream error, have a look at #16317
