### ISSUE TITLE
Support NO_COLOR environment variable

### ISSUE THREAD

**Issue by evolkmann** [gatsbyjs/gatsby#16324]
## Summary

The console output of e.g. `gatsby build` is not very readable in no-color environments or CI/CD tools, where this is not supported.

### Basic example

Gatsby should support the `NO_COLOR` environment variabel (https://no-color.org/) and disable colored output accordingly.

### Motivation

- Better readability of logs in CI environments
- Better accessibility for users who prefer non-colored output

**Comment by evolkmann** [comment]
#2172 mentioned the same issue, but was closed.

**Comment by wardpeet** [comment]
We currently support `FORCE_COLOR=0` & `gatsby build --noColor`. We're happy to accept a NO_COLOR environment variable.

https://github.com/gatsbyjs/gatsby/blob/f455c217d34c1bce412a3260d056ce27b4649019/packages/gatsby-cli/src/create-cli.js#L85-L90

**Comment by evolkmann** [comment]
Hi @wardpeet, thanks for the clarification. I could not find this in the docs, therefore created #16327. I guess it would be easy to also support 'NO_COLOR' in this context. Maybe I can also have a look at this.

**Comment by evolkmann** [comment]
@wardpeet You can assign this to me or keep it as `good first issue` for someone else just starting out, whatever you prefer :)

**Comment by wardpeet** [comment]
Thank you :pray:. Feel free to take it on.

**Comment by evolkmann** [comment]
Thanks, I will work on it as soon as #16327 is merged so I can work on the updated docs when starting this.
