### ISSUE TITLE
Queries from unused themes cause "gatsby develop" to fail

### ISSUE THREAD

**Issue by johno** [gatsbyjs/gatsby#16338]
## Description

Queries from themes that aren't being used cause an app to fail. It's sort of an abrupt experience to have installing a package make your app crash when it isn't configured. I'm not sure if we should check to make sure a theme is being used or if we should error in a more friendly way that says to configure the theme or use it.

### Steps to reproduce

```
gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme
cd my-theme-blog
yarn add gatsby-theme-documentation
yarn start
```

### Expected result

The blog theme runs unaffected by the docs theme which isn't configured.

### Actual result

We receive an error that crashes the app:

```
 ERROR #85907  GRAPHQL

There was an error in your GraphQL query:

- Unknown field 'docs' on type 'Query'.

File: node_modules/gatsby-theme-documentation/src/templates/doc.js
```

![image](https://user-images.githubusercontent.com/1424573/62389533-4b172d80-b51d-11e9-92df-cc96b66c2f37.png)

## Related

- #11278

**Comment by sw-yx** [comment]
would definitely like gatsby to do a check against gatsby-config before running stuff in node_modules for me.

**Comment by alexluong** [comment]
I think it's the same for source plugins too. Like `gatsby-source-contentful` and `gatsby-sharp`. What @sw-yx seems like a good solution, but it may/may not run into issues with dependency of dependency (`gatsby-theme-using-contentful` depends on `gatsby-source-contentful`).

**Comment by sw-yx** [comment]
recursive check 🤷‍♂️ 

nothing is impossible. bottom line is are you surprising your users? yes? bad.

**Comment by sidharthachatterjee** [comment]
This is unfortunate! We currently parse js in `node_modules` for all deps with gatsby in their name. 

The reason we don’t work backwards from gatsby-config is for the ability to be able to support queries in arbitrary dependencies (like [gatsby-seo](https://www.npmjs.com/package/gatsby-seo) for example) 

The right way to solve this would be to further filter with:  
- files in themes in gatsby-config recursively _or_ 
- files in require tree (for deps like gatsby-seo)

**Comment by sw-yx** [comment]
a filter may not be the only approach available to you. i wonder if query parsing can be made lazier. right now queries are eager, which is ALSO a problem if you have a query in a file that is inside your main project but that isn't imported in anywhere, e.g. i would not expect my query inside `unused_file.js` to be run, but it does, and ofc can crash gatsby, which is no bueno.

making queries lazy would solve both this and that problem.

**Comment by alexluong** [comment]
If I understand Gatsby right, the way it works is that it will run all the query at build time and generates the data into static json. That’s how in prod there is no graphql server.

Not sure how to parse the queries in a lazy way then.

**Comment by KyleAMathews** [comment]
Yeah we don't run the queries, is the validation step. Perhaps we could store the errors for queries and only show them if we know the query is used in a component.

**Comment by progital** [comment]
I wanted to file a similar issue but @johno was faster. My issue is what @sw-yx described above. Is there any workaround or some hints where to start with fixing this validation issue?

**Comment by sw-yx** [comment]
the "workaround" i use is commenting out js files. i literally delete ".js" so that gatsby stops doing its thing. its not good. too magic. i hope gatsby prioritize this as its a nasty experience for beginners who run into it (and it doesnt take long)

**Comment by arshad** [comment]
Hitting this issue as well. @johno is there a way around this for latent shadowing? Currently shadowing a query component but this fails when the dependent theme is in `node_modules` but not configured.

**Comment by arshad** [comment]
OK I created a PR that checks for themes against `gatsby-config` as per @sidharthachatterjee suggestion above. Seems to be working for now.

Any pitfalls of excluding themes from the query compiler?

**Comment by pvdz** [comment]
Anyone know how common this case is? Do people often have unused themes in their build? Or mostly when initially setting up? Wondering about the impact surface of this problem.

**Comment by ukch** [comment]
@KyleAMathews I am being hit by this sort of error from disabled components. I would think your proposed solution would resolve my problem (whereas I suspect the linked PR would not)

**Comment by rogermparent** [comment]
@pvdz I'm running into an issue related to this which is less breaking but possibly more common in theme development. If a theme developer allows page queries to be replaced through shadowing or other means, the original query will still show the "GraphQL query in the non-page component" warning despite the theme being used as intended.
Ultimately, solving this variant of the issue is mostly to assuage the worries of developers consuming themes who may incorrectly think something is wrong, so while it expands the pool of cases it only does so with cosmetic issues.
I think @KyleAMathews proposal would fix this as well.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
