### ISSUE TITLE
Nested URL Routing 

### ISSUE THREAD

**Issue by moelfassi** [gatsbyjs/gatsby#16346]
### To go to, a `competition page` i'm using this function to go to that page:
--> from `gatsby-node.js`
`exports.onCreatePage = async ({ page, actions }) => {`
  `const { createPage } = actions`

 ` if (page.path.match(/^\/competition/)) {`
   ` page.matchPath = "/competition/*"`
   ` createPage(page)`
  `}`
 }

### from `competition page` i'm returning `Game component`:

 `return <Game path="/competition/:id" myid={ props.id }/>`

### then inside `Game component` i'm rendering a button to go to `channel page`:
 
  `<Link to={'/competition/'+this.props.myid+'/'+rowdata['GameName']}/>`

> here i don't know how to go to `channel page` i have inside `src/pages` and keeping my url like in the code: `/competition/'+myid+'/'+GameName`

is my approach correct? i'm open to other solutions

**Comment by elken** [comment]
IIRC Gatsby uses @reach/router, so see [their docs](https://reach.tech/router/example/nested-routes)

**Comment by elken** [comment]
See [this](https://reach.tech/router/example/nested-routes) example.

**Comment by magicspon** [comment]
As @elken said... see the docs...
