### ISSUE TITLE
[docs] table of contents on Recipes page needs fine-tuning

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#16341]
## Summary

The new TOC component needs fine-tuning on the [recipes page](https://gatsbyjs.com/docs/recipes): the automated headings are including "Prerequisites" and "Directions" for every recipe, which is repetitive and not providing value. Instead, we should limit headings in the TOC on the recipes page to only h2's and h3's, not h4's. 

One suggestion from @gillkyle: "we could maybe disable it for the recipes page and import it in the mdx on the page and pass in some props to make it not render those headers?"

## Motivation

By only showing recipe group titles and individual recipe names, it will be easier to scan and navigate the page.

![Recipes page with table of contents](https://user-images.githubusercontent.com/1045233/62395037-ef9c6e00-b523-11e9-907e-014269314c36.png)

**Comment by alexluong** [comment]
The challenging part of @gillkyle's suggestion is how we can place the TOC like in the template from MDX.

To go around that, would adding another frontmatter field work? Something similar to `frontmatter.tableOfContentsHeadings` or `frontmatter.limitedTOC` or the like, and use it inside the template?

**Comment by gillkyle** [comment]
@alexluong I was really just spitballing as I was brainstorming what could be done to make the headers in a specific page more customizable. I think a frontmatter field is a great idea!
