### ISSUE TITLE
Build: Webpack Error Third party tool "react-owl-carousel"

### ISSUE THREAD

**Issue by lesleyNilson** [gatsbyjs/gatsby#16365]
I want to use _"gatsby build"_, but I have difficulties with the third party tool _"react-owl-carousel"_

I got an error message. Please see below

> gatsby build
> 
> success open and validate gatsby-configs - 0.044 s
> success load plugins - 0.435 s
> success onPreInit - 0.002 s
> success delete html and css files from previous builds - 0.003 s
> success initialize cache - 0.006 s
> success copy gatsby files - 0.057 s
> success onPreBootstrap - 0.019 s
> success source and transform nodes - 0.166 s
> success building schema - 0.251 s
> success createPages - 0.001 s
> success createPagesStatefully - 0.052 s
> success onPreExtractQueries - 0.003 s
> success update schema - 0.032 s
> success extract queries from components - 0.318 s
> success write out requires - 0.008 s
> success write out redirect data - 0.001 s
> success Build manifest and related icons - 0.371 s
> success onPostBootstrap - 0.383 s
> ⠀
> info bootstrap finished - 3.409 s
> ⠀
> success run static queries - 0.434 s — 7/7 16.37 queries/second
> success Generating image thumbnails — 35/35 - 5.831 s
> success Building production JavaScript and CSS bundles - 13.616 s
> success Rewriting compilation hashes - 0.003 s
> success run page queries - 0.102 s — 7/7 72.80 queries/second
> 
>  ERROR #95312 
> 
> "window" is not available during server side rendering.
> 
> See our docs page for more info on this error: https://gatsby.dev/debug-html

So I add the following code snippet to `gatsby-node.js`: 
```
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /react-owl-carousel/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
}
```

But I got the error message: 

> > bacon@0.1.0 build /Applications/MAMP/htdocs/bacon
> > gatsby build
> 
> success open and validate gatsby-configs - 0.028 s
> success load plugins - 0.599 s
> success onPreInit - 0.002 s
> success delete html and css files from previous builds - 0.004 s
> success initialize cache - 0.007 s
> success copy gatsby files - 0.062 s
> success onPreBootstrap - 0.019 s
> success source and transform nodes - 0.141 s
> success building schema - 0.248 s
> success createPages - 0.001 s
> success createPagesStatefully - 0.053 s
> success onPreExtractQueries - 0.004 s
> success update schema - 0.029 s
> success extract queries from components - 0.266 s
> success write out requires - 0.004 s
> success write out redirect data - 0.005 s
> success Build manifest and related icons - 0.353 s
> success onPostBootstrap - 0.372 s
> ⠀
> info bootstrap finished - 3.994 s
> ⠀
> success run static queries - 0.479 s — 7/7 14.75 queries/second
> success Generating image thumbnails — 38/38 - 6.761 s
> success Building production JavaScript and CSS bundles - 13.752 s
> success Rewriting compilation hashes - 0.004 s
> success run page queries - 0.105 s — 7/7 72.14 queries/second
> 
>  ERROR #95313 
> 
> Building static HTML failed for path "/"
> 
> See our docs page for more info on this error: https://gatsby.dev/debug-html
> 
> 
> 
>   Error: Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full er
>   rors and additional helpful warnings.
>   
>   - react-dom-server.node.production.min.js:10 ba
>     [bacon]/[react-dom]/cjs/react-dom-server.node.production.min.js:10:312
>   
>   - react-dom-server.node.production.min.js:11 r
>     [bacon]/[react-dom]/cjs/react-dom-server.node.production.min.js:11:166
>   
>   - react-dom-server.node.production.min.js:44 a.render
>     [bacon]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:191
>   
>   - react-dom-server.node.production.min.js:41 a.read
>     [bacon]/[react-dom]/cjs/react-dom-server.node.production.min.js:41:58
>   
>   - react-dom-server.node.production.min.js:53 renderToString
>     [bacon]/[react-dom]/cjs/react-dom-server.node.production.min.js:53:83
>   
>   - render-page.js:835 Module../.cache/static-entry.js.__webpack_exports__.default
>     /Applications/MAMP/htdocs/bacon/public/render-page.js:835:18
>   
>   - render-html.js:35 Promise
>     [bacon]/[gatsby]/dist/utils/worker/render-html.js:35:36
>   
>   - debuggability.js:313 Promise._execute
>     [bacon]/[bluebird]/js/release/debuggability.js:313:9
>   
>   - promise.js:488 Promise._resolveFromExecutor
>     [bacon]/[bluebird]/js/release/promise.js:488:18
>   
>   - promise.js:79 new Promise
>     [bacon]/[bluebird]/js/release/promise.js:79:10
>   
>   - render-html.js:31 Promise.map.path
>     [bacon]/[gatsby]/dist/utils/worker/render-html.js:31:37
>   
>   - util.js:16 tryCatcher
>     [bacon]/[bluebird]/js/release/util.js:16:23
>   
>   - map.js:61 MappingPromiseArray._promiseFulfilled
>     [bacon]/[bluebird]/js/release/map.js:61:38
>   
>   - promise_array.js:114 MappingPromiseArray.PromiseArray._iterate
>     [bacon]/[bluebird]/js/release/promise_array.js:114:31
>   
>   - promise_array.js:78 MappingPromiseArray.init
>     [bacon]/[bluebird]/js/release/promise_array.js:78:10
>   
>   - map.js:30 MappingPromiseArray._asyncInit
>     [bacon]/[bluebird]/js/release/map.js:30:10
>   
> ⠸ Building static HTML for pages
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bacon@0.1.0 build: `gatsby build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the bacon@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/xxxxxx/.npm/_logs/2019-08-04T15_56_58_210Z-debug.log
> 
> Process finished with exit code 1
> 

So I checked the advices of the following links and changed my components according, but without success
[https://github.com/gatsbyjs/gatsby/issues/9214#issuecomment-431073612](https://github.com/gatsbyjs/gatsby/issues/9214#issuecomment-431073612)
[https://github.com/gatsbyjs/gatsby/issues/9038#issuecomment-432548071](https://github.com/gatsbyjs/gatsby/issues/9038#issuecomment-432548071)

Still the error message 

> Error: Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Can anybody help or have anybody links for similar problems?

**Comment by jonniebigodes** [comment]
@lesleyNilson i've picked up on your issue and i think i have a solution for you.

Gatsby during it's build process, is working in node and with that it doesn't have access to some API like `window` and so on. And with that makes some packages like this one a bit tricky to add and some errors like this one tend to happen.

Below are the steps i took to solve your issue.

- Created a new Gatsby site using the hello world starter.
- Added the following dependencies, `react-owl-carousel` and `react-loadable`.
- Created a `gatsby-node.js` with the following content:

```javascript
const webpack= require('webpack');
exports.onCreateWebpackConfig = ({
    stage,
    rules,
    loaders,
    plugins,
    actions,
  }) => {
    actions.setWebpackConfig({
      plugins: [
        new webpack.ProvidePlugin({
          $: 'jquery',
          jQuery: 'jquery',
          'window.jQuery': 'jquery'
        }),
      ],
    })
  }
```
With this the necessary jQuery will be injected during the build process to Gatsby.
- Created a new component called `MyCarousel.js` under `src/components` with the following code:
```javascript
import React from "react"

import OwlCarousel from 'react-owl-carousel';
import 'owl.carousel/dist/assets/owl.carousel.css';
import 'owl.carousel/dist/assets/owl.theme.default.css';

const MyCarousel = () => (
  <OwlCarousel className="owl-theme" loop margin={10} nav>
    <div class="item">
      <h4>1</h4>
    </div>
    <div class="item">
      <h4>2</h4>
    </div>
    <div class="item">
      <h4>3</h4>
    </div>
    <div class="item">
      <h4>4</h4>
    </div>
    <div class="item">
      <h4>5</h4>
    </div>
    <div class="item">
      <h4>6</h4>
    </div>
    <div class="item">
      <h4>7</h4>
    </div>
    <div class="item">
      <h4>8</h4>
    </div>
    <div class="item">
      <h4>9</h4>
    </div>
    <div class="item">
      <h4>10</h4>
    </div>
    <div class="item">
      <h4>11</h4>
    </div>
    <div class="item">
      <h4>12</h4>
    </div>
  </OwlCarousel>
)

export default MyCarousel
```
This is the basic example supplied by the documentation, i used as a means to see if it would work.
- Modified `src/pages/index.js` to the following:
```javascript
import React from "react"
import Loadable from "react-loadable"
const loader=()=>(<div>Loading...</div>)

const MyLoadableCarousel = Loadable({
  loader: () => import("../components/MyCarousel"),
  loading: loader,
})

export default () => (
    <div>
      <p>Hello world!</p>
      <MyLoadableCarousel/>
    </div>
  )
  
````

Here's where the [react-loadable](https://github.com/jamiebuilds/react-loadable) package comes into play. What is actually happening in this page is the following, the carousel component loading will be deferred to when the user visits the page.
- Issued `gatsby build && gatsby serve` to generate a production build and emulate a live production server and i'm presented with the following:

![gatsby_carousel_1](https://user-images.githubusercontent.com/22988955/62427733-39857f80-b6ef-11e9-920f-457b443a8252.png)

Opening up a new browser window to `http://localhost:9000` and i'm presented with the following:
![gatsby_carousel_2](https://user-images.githubusercontent.com/22988955/62427752-c03a5c80-b6ef-11e9-8921-62454aaa2a09.png)


The carousel is working as expected.

If you want i can hoist the code i've used to a repo so that you can look at it in your own pace.

Feel free to provide feedback so that we can close this issue or continue to work on it till we find a suitable solution.

**Comment by lesleyNilson** [comment]
@jonniebigodes

>  If you want i can hoist the code i've used to a repo so that you can look at it in your own pace.

that would be great. I made the changes and I do not get anylonger the error message. That is fine, but now my carousel is not working as expected. The carousel is not available.

**Comment by jonniebigodes** [comment]
@lesleyNilson i've updated the example to incorporate  some images and pushed the code to a repository.
It's in [here](https://github.com/jonniebigodes/gatsby-react-owl-carousel).

**Comment by lesleyNilson** [comment]
@jonniebigodes Thanks a lot. I make it run today. I still have problem, but this is another issue. Your solution is right and solve the problem!
