### ISSUE TITLE
Search results page for Gatsby Docs

### ISSUE THREAD

**Issue by spences10** [gatsbyjs/gatsby#16367]
## Summary

As a user I'd like to use the search box to enter a search query and see the results of that query in a page rather than the suggested content.

### Basic example

Trying to find a blog example just gives the autocomplete results, but if you want browse for more results it is not possible.

![image](https://user-images.githubusercontent.com/234708/62426461-1f42a600-b6dd-11e9-8c07-5088f85f3114.png)

### Motivation

Querying the docs can force you down a route that may not be the best option for you.

Me trying to find a 'basic blog example'

![gif](https://user-images.githubusercontent.com/234708/62426555-11d9eb80-b6de-11e9-9f47-a349c3992b40.gif)

**Comment by spences10** [comment]
@amberleyromo can this be closed?

**Comment by jackbravo** [comment]
Indeed, another related issue came up in #13876. Searching for `gatsby wordpress` should get the doc page [Sourcing from WordPress](https://www.gatsbyjs.org/docs/sourcing-from-wordpress/). But blog posts are being presented first. I would also recommend tweaking the current results to give higher priority to documentation pages over blog posts. Blog posts can become stale (they are not updated after they are created) while documentation pages are constantly being updated.

**Comment by marcysutton** [comment]
@jackbravo if you're interested in working on a PR to improve searchability of Wordpress docs content, we would love a contribution!

**Comment by LekoArts** [comment]
This could be considered for a redesign of the website but for now this won't be fixed.
