### ISSUE TITLE
[gatsby-plugin-sass] resolveUrlLoader not being used for modules

### ISSUE THREAD

**Issue by Js-Brecht** [gatsbyjs/gatsby#16361]
## Description

There is an option to include `resolve-url-loader` support for sass, but it does not include that support for sass modules.  This is causing issues when a sass script I am importing in a `module.scss` uses a `url()` call.

### Steps to reproduce

Add option to plugin to use `resolveUrlLoader`:
```js
{
    resolve: `gatsby-plugin-sass`,
    options: {
        useResolveUrlLoader: true,
    },
},
```
Assuming a `src` folder structure like this:
```
src
|--- assets
    |---css
    |---fonts
|--- components
```
Create an `*.scss` file that uses a `url()` import
```scss
// src/assets/css/fonts.scss
@font-face {
	font-family: "Monotype Corsiva";
	src: url("../fonts/mtcorsva.ttf") format("truetype");
}
```
`@import` the font css from assets/css, within a style module
```js
// src/components/style.module.scss
@import "../assets/css/fonts";
```

### Expected result

What **should** happen, is `resolve-url-loader` should load the font relative to the script that called `url()`.  Shouldn't matter whether or not it was imported from a `.module.scss` or just `.scss`.

### Actual result

Modules could not be resolved.  It looks for the module relative to the script that called `@import`.  Standard behavior when not using `resolve-url-loader`.  Also rather unfortunate.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0.1
  npmPackages:
    gatsby: 2.13.50 => 2.13.50 
    gatsby-image: 2.2.8 => 2.2.8 
    gatsby-plugin-atl: ^0.0.1 => 0.0.1 
    gatsby-plugin-eslint: ^2.0.5 => 2.0.5 
    gatsby-plugin-manifest: 2.2.4 => 2.2.4 
    gatsby-plugin-offline: 2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: 3.1.3 => 3.1.3 
    gatsby-plugin-sass: ^2.1.4 => 2.1.4 
    gatsby-plugin-sharp: 2.2.9 => 2.2.9 
    gatsby-source-filesystem: 2.1.8 => 2.1.8 
    gatsby-transformer-sharp: 2.2.5 => 2.2.5 
    gatsby-transformer-yaml: 2.2.4 => 2.2.4 
```

## Additional

It's a simple enough fix.

[gatsby-plugin-sass#L30-L35](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sass/src/gatsby-node.js#L30-L35) could just be dropped down below `sassRulesModules`, and an additional step could be added to splice in `resolve-url-loader`, just like it does for `sassRule`.

I've implemented the fix locally, and it works well.

**Comment by freiksenet** [comment]
Hello @Js-Brecht!

Thank you for you report! I wonder if you could send us those local changes as a PR?

Thanks! :purple_heart: :muscle:

**Comment by Js-Brecht** [comment]
I would be happy to.

I am just curious about one thing:
The variable [`sassRule`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sass/src/gatsby-node.js#L19) completely skips all loaders if the current build stage is SSR, while the [`sassRuleModules`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sass/src/gatsby-node.js#L36) only skips adding the `miniCssExtract` loader during SSR.  Perhaps I don't fully comprehend the build stages, but why is it that standard `*.scss` files should not be processed during SSR, but the `*.module.scss` files should?  It seems to me that both should be processed in any case. 🤔 

This is shown here for the `sassRule`: [L19-L29](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sass/src/gatsby-node.js#L19-L29)
```js
  const sassRule = {
    test: /\.s(a|c)ss$/,
    use: isSSR
      ? [loaders.null()]
      : [
          loaders.miniCssExtract(),
          loaders.css({ ...cssLoaderOptions, importLoaders: 2 }),
          loaders.postcss({ plugins: postCssPlugins }),
          sassLoader,
        ],
  }
```

And here for the `sassRuleModules`: [L36-L44](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sass/src/gatsby-node.js#L36-L44)
```js
  const sassRuleModules = {
    test: /\.module\.s(a|c)ss$/,
    use: [
      !isSSR && loaders.miniCssExtract({ hmr: false }),
      loaders.css({ ...cssLoaderOptions, modules: true, importLoaders: 2 }),
      loaders.postcss({ plugins: postCssPlugins }),
      sassLoader,
    ].filter(Boolean),
  }
```
