### ISSUE TITLE
How to build static as development

### ISSUE THREAD

**Issue by derit** [gatsbyjs/gatsby#16377]
how to build static html as development environtment

when i build with command `gatsby build` it make static html as production build 
in my case i need test development environtment and deploy to static site

in development `process.env.NODE_ENV` is **development** 
`console.log(process.env.NODE_ENV) ` when using` gatsby build` NODE_ENV is **production** 

thanks

**Comment by sidharthachatterjee** [comment]
@derit There currently isn't a documented way to build your site in development.   `gatsby build` overrides `NODE_ENV` and sets it to `production` 

Can you elaborate on what you're trying to achieve exactly?

**Comment by derit** [comment]
@sidharthachatterjee 
just need build gatsby static with development environment

**Comment by sidharthachatterjee** [comment]
@derit We don't support that unfortunately!

**Comment by wardpeet** [comment]
We have some ideas how you could try to do this https://github.com/gatsbyjs/gatsby/issues/14230. It's not officially supported so we're not sure what sideffects this will give.

**Comment by derit** [comment]
i solved this problem with refered to this document 
[https://www.gatsbyjs.org/docs/add-custom-webpack-config/#examples](url)

**Comment by lucashfreitas** [comment]
+1. 

I am facing the same issue. 

I want to build my website and deploy it using a development environment. 

**Why:** I need to deploy and show the staging website to the users/customers, then they will be able to test and use it on the staging environment. 

We should have a way to build and deploy a gatsby website for development/stage purposes, but currently, gatsby build automatically set the environment variable to Production. 

Any thoughts on this @sidharthachatterjee? 

https://stackoverflow.com/questions/58280325/gatsby-build-website-for-stage-development-which-command-should-i-use 

Thanks!

**Comment by mattjegan** [comment]
@lucashfreitas I just stumbled upon this and found that you can set env vars prefixed with `GATSBY_` and before running `gatsby build`. You can then access the variable in your javascript with `process.env.GATSBY_MY_VAR`. For example, I have set a env var to indicate the dev environment:

```
export GATSBY_APP_ENVIRON=dev
```

and then in one of my components:

```
if (process.env.GATSBY_APP_ENVIRON === "dev") {
    // Do development specific things
}
```

More info here: https://www.gatsbyjs.org/docs/environment-variables/#example

**Comment by Mask2** [comment]
Seems gatsby doc [Additional Environments](https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/#environment-variables-on-gatsby-cloud) has the perfect solution.

We can set a env param `GATSBY_ENV` inside script 

```
"scripts": {
    "develop": "gatsby develop",
    "start": "gatsby develop --host=0.0.0.0",
    "build": "gatsby build",
    "build:dev": "GATSBY_ENV=development gatsby build",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
},
```

and use is to point you env file by the dotenv snippet on the top of gatsby-config.js

```
if (process.env.GATSBY_ENV) {
  require('dotenv').config({
    path: `.env.${process.env.GATSBY_ENV}`,
  })
} else {
  require('dotenv').config({
    path: `.env.${process.env.NODE_ENV}`,
  })
}
```

**Comment by robclancy** [comment]
How is gatsby overriding NODE_ENV ever been considered okay to do?

**Comment by hisuwh** [comment]
I need this because the develop build and production build behave differently when it comes to routing.
In develop it seems to reload the page (presumably linked to the way it progressively builds the pages).
When I do the production build its routing like a proper SPA but I'm experiencing an issue where this event seems to be bubbling up and triggering other things.  But I can't reproduce this in the development build as the page reloads.
