### ISSUE TITLE
[gatsby-source-wordpress]:  Featured Images and Galleries not being returned.

### ISSUE THREAD

**Issue by mavalon** [gatsbyjs/gatsby#16380]
## Description
I am developing a blog that will have thousands of images.  Currently I only have about 600 images.

I am using Custom Post Types and Advanced Custom Fields.

Most data seems to be returned in my GraphQL queries.  I even have some image fields that are being returned properly.  However, the most important fields in my WordPress CMS are featured images and galleries.  Neither of which show up at all in the query responses.  When I run `gatsby develop`, everything compiles successfully without warnings or errors.

### Steps to reproduce

- Enabled ACF with `useACF: true` in `gatsby-config.js`
- Include `**/albums"` Custom Post Type (which has a gallery ACF) in `incudedRoutes` in `gatsby-config.js`
- Run `gatsby develop`
- Open `http://localhost:8001/___graphq` and navigate to `allWordpressWpTests` > `edges` > `nodes` > `acf` and note that other custom fields are available, but the gallery is completely absent. Also, note that no featured photos are returned for _any_ of the post types.  Note that `image` ACFs *do* return the image object.

### Expected result

- Gallery and image object should be returned in GraphQL queries

### Actual result

- Noted above in "Steps to reproduce"

### Environment
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Yarn: 1.3.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.6.2 - C:\Users\Michael\AppData\Local\Programs\Python\Python36\python.EXE
  Browsers:
    Edge: 38.14393.1066.0
  npmPackages:
    gatsby: ^2.13.45 => 2.13.45
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-source-filesystem: ^2.1.7 => 2.1.7
    gatsby-source-wordpress: ^3.1.13 => 3.1.13
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5

```

### Additional info

I should mention that I am saving my media to a separate subdomain from Wordpress.  I'm not sure if this would affect anything.  However, as mentioned above, other Image Fields are returning the data.

I also posted a separate issue, that _may_ be related here: https://github.com/gatsbyjs/gatsby/issues/16353

I'm close to giving up on Gatsby.  Everything seemed to be going swimmingly at first, but now I keep running into insurmountable wals.  The closest thing I found to a solution was something like `add_filter('acf/format_value', 'acf_nullify_empty', 100, 3);`.  While that resolved issues I was having with certain fields, it did not resolve the issue with the gallery or featured images.  Adding the filter specifically to the gallery did not help either (`add_filter('acf/format_value/type=gallery', 'acf_nullify_empty', 100, 3);`)

**Comment by wardpeet** [comment]
Is it possible to share your wp rest api with us? or an export of your graphql query data. It's a bit tricky to get this resolved without it.

**Comment by mavalon** [comment]
This is the shape of one of the albums in `wp-json/wp/v2/albums` -- where `album_photos` is the gallery field:
```
[
    {
      "id": 749,
      "date": "2019-07-30T20:11:20",
      "date_gmt": "2019-07-30T20:11:20",
      "guid": {
        "rendered": "http://cms.midlifetour.localhost/?post_type=album&#038;p=749"
      },
      "modified": "2019-08-05T06:18:32",
      "modified_gmt": "2019-08-05T06:18:32",
      "slug": "las-vegas-nevada",
      "status": "publish",
      "type": "albums",
      "link": "http://cms.midlifetour.localhost/album/las-vegas-nevada/",
      "title": {
        "rendered": "Las Vegas, Nevada"
      },
      "content": {
        "rendered": "",
        "protected": false
      },
      "excerpt": {
        "rendered": "",
        "protected": false
      },
      "featured_media": 764,
      "template": "",
      "meta": [],
      "tags": [],
      "acf": {
        "album_title": "Las Vegas",
        "album_date": "12/10/2016",
        "album_photos": [
          {
            "ID": 750,
            "id": 750,
            "title": "Las Vegas, Nevada",
            "filename": "14444941_985194704924083_200410344069377682_o.jpg",
            "filesize": 659617,
            "url": "http://uploads.midlifetour.localhost/wp-media/2019/07/14444941_985194704924083_200410344069377682_o.jpg",
            "link": "http://cms.midlifetour.localhost/album/las-vegas-nevada/14444941_985194704924083_200410344069377682_o/",
            "alt": "",
            "author": "1",
            "description": "",
            "caption": "",
            "name": "14444941_985194704924083_200410344069377682_o",
            "status": "inherit",
            "uploaded_to": 749,
            "date": "2019-07-30 20:10:10",
            "modified": "2019-07-31 10:27:44",
            "menu_order": 0,
            "mime_type": "image/jpeg",
            "type": "image",
            "subtype": "jpeg",
            "icon": "http://cms.midlifetour.localhost/wp-includes/images/media/default.png",
            "width": 1200,
            "height": 900,
            "sizes": {
              "thumbnail": "http://uploads.midlifetour.localhost/wp-media/2019/07/14444941_985194704924083_200410344069377682_o-150x150.jpg",
              "thumbnail-width": 150,
              "thumbnail-height": 150,
              "medium": "http://uploads.midlifetour.localhost/wp-media/2019/07/14444941_985194704924083_200410344069377682_o-300x225.jpg",
              "medium-width": 300,
              "medium-height": 225,
              "medium_large": "http://uploads.midlifetour.localhost/wp-media/2019/07/14444941_985194704924083_200410344069377682_o-768x576.jpg",
              "medium_large-width": 525,
              "medium_large-height": 394,
              "large": "http://uploads.midlifetour.localhost/wp-media/2019/07/14444941_985194704924083_200410344069377682_o-1024x768.jpg",
              "large-width": 525,
              "large-height": 394,
              "twentyseventeen-featured-image": "http://uploads.midlifetour.localhost/wp-media/2019/07/14444941_985194704924083_200410344069377682_o.jpg",
              "twentyseventeen-featured-image-width": 1200,
              "twentyseventeen-featured-image-height": 900,
              "twentyseventeen-thumbnail-avatar": "http://uploads.midlifetour.localhost/wp-media/2019/07/14444941_985194704924083_200410344069377682_o-100x100.jpg",
              "twentyseventeen-thumbnail-avatar-width": 100,
              "twentyseventeen-thumbnail-avatar-height": 100
            }
          }
        ]
      }
    }
  ]

```

Aside from that, I really don't know what I could share with you in these comments (the files are massive).  If there is a working demo Wordpress + gatsby repo that makes use of featured images and the gallery field, then perhaps I can pull it down and see if it compiles locally.

**Comment by mavalon** [comment]
I created a new WordPress instance with only one Custom Post Type (`albums`) with one Advanced Custom Field (`gallery`) and was able to compile successfully.  The gallery now shows up for this, but the **featured image still does not**.   Furthermore, the response omits all the different sizes (which are necessary for my purposes).  The GraphiQL Explorer window shows a much different structure from the response from the WP API.  

GraphiQL: Explorer
```
- edges
	- node
		-acf
			alt_text
			author
			caption
			children
			comment_status
			date
			description
			guid
			id
			internal
			link
			localfile
				absolutePath
				accessTime
				atime
				atimeMs
				base
				...(it goes on with useless details)
			media_details
				file
				...
			...
```
And the response from REST is same as I posted earlier.

I would continue with this clean project and just keep adding to this WordPress instance until it's where I need it to be (or until it breaks again).  I just don't know if it's worth it if I'm not going to get the image paths for the various sizes.

**Comment by mavalon** [comment]
I've decided to use `gatsby-source-graphql` with some wordpress plugins instead, which gives me all the data I need.

**Comment by firestar300** [comment]
Hello @mavalon . So you removed `gatsby-source-wordpress` and use `gatsby-source-graphql` instead ?

**Comment by mavalon** [comment]
Yes, @firestar300.  Even though I encounter plenty of issues with `gatsby-source-graphql`, at least I'm able to work around them; whereas I kept running into insurmountable problems with `gatsby-source-wordpress`.  I'm new to Gatsby and GraphQL, but I found this tutorial helpful (though it's unnecessarily long): https://www.youtube.com/watch?time_continue=1157&v=DH7I1xRrbxs

**Comment by mpaccione** [comment]
I have a similar issue where I am only having a few images returned on my queries despite the fact that they definitely have featured content.
