### ISSUE TITLE
node_module transpile causing errors in develop mode

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#16396]
## Description

Upgrading my Gatsby site (and all official Gatsby plugins) from `2.10.0` to `2.13.51` is causing my dependencies to not be read correctly.

Not sure if this is related to https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/CHANGELOG.md#2118-2019-07-02

Steps below (Broken example has issue) have nothing but official plugins updated. [Diff of branches](https://github.com/zslabs/zslabs.com/compare/feature/dep-upgrade-broken?expand=1)

#### Working example

1. Clone https://github.com/zslabs/zslabs.com/tree/master
1. Run with `yarn develop`
1. Interact with <img width="214" alt="Screen Shot 2019-08-05 at 4 38 08 PM" src="https://user-images.githubusercontent.com/1018402/62493554-6ee9a600-b79f-11e9-8476-16ef94942f44.png"> to open offcanvas and view articles.

** Note my addition in https://github.com/zslabs/zslabs.com/blob/master/gatsby-node.js#L10 that transpiles ChaosKit which has worked consistently until now.

#### Broken example

1. Clone https://github.com/zslabs/zslabs.com/tree/feature/dep-upgrade-broken
1. Run with `yarn develop`
1. Interact with <img width="214" alt="Screen Shot 2019-08-05 at 4 38 08 PM" src="https://user-images.githubusercontent.com/1018402/62493554-6ee9a600-b79f-11e9-8476-16ef94942f44.png"> to open offcanvas and view articles.
1. Page crashes; not grabbing dependency timeline (GSAP) correctly.

### Expected result

Functionality from "un-transpiled" module should continue to work as expected.

### Actual result

Errors out; as if it's not reading dependencies correctly anymore.

**Comment by wardpeet** [comment]
thanks for letting us know.

Do you have an error message to share? Or it just does nothing?

**Comment by zslabs** [comment]
👋 Thanks @wardpeet for the quick response! The error is in relation to [https://greensock.com/](https://greensock.com/) and how I'm attaching the animation logic to the `<OffCanvas />` component from https://github.com/gremlin/chaoskit/blob/v1.4.3/src/components/OffCanvas.js#L46 Not sure what changed in the deps between versions that would cause that issue - since I haven't changed anything about that logic (in relation to it being used in Gatsby) for quite a long time; so that's why I was thinking there may be some correlation between how `node_modules` are processed now.

**Comment by wardpeet** [comment]
Probably https://github.com/gatsbyjs/gatsby/issues/14111 & https://github.com/gatsbyjs/gatsby/issues/15284 have caused this.

**Comment by zslabs** [comment]
> Probably #14111 & #15284 have caused this.

Ah ok, darn 😢 

Are there any action-items for me to do or docs I missed; or do ya think those PRs are something that may need a second-look?

**Comment by wardpeet** [comment]
probably something on our end ;) I'll have a look tomorrow to see if I can pinpoint the bug.

**Comment by zslabs** [comment]
Thanks @wardpeet greatly appreciated as always!

**Comment by wardpeet** [comment]
Seems like the custom `test: /\.js$|\.jsx$/,` with chaoskit is the problem. I can't really say why the previous versions worked. Maybe they got merged before and with our changes they don't match and it broke.

I would suggest removing your custom rule and use 
```js
{
  resolve: 'gatsby-plugin-compile-es6-packages',
  options: {
    modules: [`chaoskit`]
  }
}
```

**Comment by zslabs** [comment]
This is still an issue https://drive.google.com/open?id=1dVTtG03cUuvz6FtKxqf628FCUW7Nxoux

Prod builds works fine, but not `yarn develop` as I mentioned in the the issue. I tested out the prod build with the original https://github.com/zslabs/zslabs.com/tree/feature/dep-upgrade-broken and that also works fine - so this is an issue with develop-mode.

**Comment by zslabs** [comment]
@wardpeet Is https://github.com/gatsbyjs/gatsby/pull/14111/commits/acfccb6660e4a1679dacc92086e5feba68212313#diff-c4777e791f64fbb6c82255341b381dabR252 causing the issue during develop? Was a plugin or config option created?

**Comment by zslabs** [comment]
cc @sidharthachatterjee @pieh and @KyleAMathews since you all had visibility into the PRs that introduced this issue to see if we have any ideas on how to resolve. Thanks all for any help on this. Super bummed about it, but more than happy to help test out any potential fixes.

**Comment by zslabs** [comment]
https://github.com/zslabs/gatsby-es6-test is probably the simplest reproduction I can make of this issue.

It looks like it may have something to do with two components that use `createPortal` (or some variation of it) as the errors point to the "other" component when you click on the trigger. Removing one combo (notes on index page) works as intended. 

This is not an issue in older versions of Gatsby before the Babel changes, and I tested out this same demo in NextJS 9 and it works 100% as intended. The production-build of the aforementioned repo also works fine for Gatsby on the newest version, so this is an issue with develop mode.

**Comment by zslabs** [comment]
@wardpeet Have you had a chance to test out the minimal reproduction at https://github.com/zslabs/gatsby-es6-test ? Prod builds will work fine, but not develop. This ticket seemed to go quiet after I provided a way to reproduce; so I'm unsure if it's because of lack of interest or it's something being looked at behind the scenes.

**Comment by zslabs** [comment]
Resolved via https://github.com/streamich/react-use/pull/534

**Comment by wardpeet** [comment]
sorry I've been on holiday, does this need extra attention?

**Comment by zslabs** [comment]
> sorry I've been on holiday, does this need extra attention?

I think we're all set here, thanks for checking in.
