### ISSUE TITLE
Data undefined with gatsby build, gatsby develop no issues

### ISSUE THREAD

**Issue by rnnyrk** [gatsbyjs/gatsby#16397]
## Description

As soon as I run a `gatsby build` the data in my project is suddenly undefined. With `gatsby develop` there is no issue. I've tried a lot of things, like using different queries, removing the cache etc. 

Like you can see in my environment I use Wordpress as a backend via `gatsby-source-wordpress`. When I run the build command in my terminal I see all the data loading correctly. 

```
 -> wordpress__acf_options fetched : 1
 -> wordpress__acf_posts fetched : 2
 -> wordpress__acf_pages fetched : 3
 -> wordpress__acf_media fetched : 15
 -> wordpress__acf_blocks fetched : 0
 -> wordpress__acf_categories fetched : 1
 -> wordpress__acf_tags fetched : 0
 -> wordpress__acf_comments fetched : 1
 -> wordpress__acf_users fetched : 1
 -> wordpress__wp_api_menus_menus_items fetched : 1
 -> wordpress__wp_api_menus_menus fetched : 1
 -> wordpress__POST fetched : 2
 -> wordpress__PAGE fetched : 3
 -> wordpress__wp_media fetched : 15
```

Also when I run with `verbose` mode on I can see all the correct API urls getting called and when I visited the urls all data seems to be valid.  

I've added an log in `gatsby-node.js` as well which logs the result of:
```
    const pagesResult = await graphql(`
    {
      allWordpressPage {
        edges {
          node {
            id
            slug
            status
            template
            slug
            acf
          }
        }
      }
    }
  `);

  console.log('pagesResult', pagesResult.data.allWordpressPage.edges);
```

Here I see the correct pages being logged. This is interesting, because when I only display pages it seem to work. The getting of data seems to break because of menu's and acf fields. 

For menu's I use [wp-api-menus](https://wordpress.org/plugins/wp-api-menus/) as suggested in [gatsby-source-wordpress](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/).
```
    wordpressWpApiMenusMenusItems {
      items {
        object_id
        object_slug
        title
        url
      }
    }
```

I understand my `gatsby-node.js` is somehow the local database in a production build. But when I attach the `allWordpressWpApiMenusMenus` to the queried data in there I still get the same issue. 

```
      allWordpressWpApiMenusMenus {
        edges {
          node {
            name
            slug
          }
        }
      }
```

I don't know where to look anymore, or what's going wrong. Anyone any idea? 

### Steps to reproduce

1. Build and develop project via `gatsby develop` without issues
2. Build project via `gatsby build`, project won't build

### Environment
```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.11.0 - ~/.nvm/versions/node/v11.11.0/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.11.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.51 => 2.13.51 
    gatsby-image: ^2.2.8 => 2.2.8 
    gatsby-plugin-create-client-paths: ^2.1.3 => 2.1.3 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4 
    gatsby-plugin-module-resolver: 1.0.3 => 1.0.3 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1 
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9 
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2 
    gatsby-source-filesystem: ^2.1.8 => 2.1.8 
    gatsby-source-wordpress: ^3.1.13 => 3.1.13 
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5 
  npmGlobalPackages:
    gatsby: 2.13.51
```

**Comment by jonniebigodes** [comment]
@rnnyrk see #15671 for what i think is the issue happening to you aswell.

**Comment by rnnyrk** [comment]
Issue is resolved. Seemed to be an issue with requesting the data on the 404 page where I didn't do the graphql logic.. 😓
