### ISSUE TITLE
[Remark Plugin Tutorial]: Document How to Create Async Plugins

### ISSUE THREAD

**Issue by karlhorky** [gatsbyjs/gatsby#16403]
# Summary

@lannonbr added [the Remark Plugin Tutorial](https://www.gatsbyjs.org/docs/remark-plugin-tutorial/) to the docs in #13234 (thanks for that!).

It would be nice if this tutorial included a short section on how to write async plugins too, documented a bit here:

https://spectrum.chat/unified/remark/async-plugins~e3916709-9c3e-494c-9d8e-af3efbf08e80?m=MTU0NjE2NTk5NjMxMQ==

Async Plugin examples:

https://github.com/swimlane/DocSPA/blob/9155c2e07fa3105f4e7858e62e9877cfc4105706/projects/swimlane/docspa-remark-preset/src/plugins/short-codes.ts#L106

https://github.com/huy-nguyen/remark-github-plugin/blob/05abd4ab5c54c24ea47a03f08f7ad4c4c0695501/src/transform.ts#L107

## Motivation

Asynchronous workflows are common in JavaScript, and it would be nice to support these use cases.

**Comment by han-so1omon** [comment]
New contributor here. I'd like to hop on this.
