### ISSUE TITLE
Known Limits on useStaticQuery

### ISSUE THREAD

**Issue by tbrannam** [gatsbyjs/gatsby#16408]
While investigating https://github.com/dotansimha/graphql-code-generator and it's possible use to generate typed (typescript) interfaces for Gatsby Graphql Queries -

I've come across some issues which might be related to this notice:  https://www.gatsbyjs.org/blog/2019-02-20-introducing-use-static-query/#known-limitations

In my case I have an autogenerated file which exposes multiple exported useStaticQuery wrappers - but during `gatsby build` I receive error messages `WebpackError: ReferenceError: useStaticQuery is not defined` 

Is the known-limitation still present today?  Is this how it might manifest itself?  What's the complexity of addressing it (where is this magic implemented)

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by freiksenet** [comment]
CC @sidharthachatterjee

**Comment by tbrannam** [comment]
@sidharthachatterjee  Still curious - if this is a limit of `useStaticQuery` or the underlying Provider - or the stripping in webpack.

**Comment by LekoArts** [comment]
CC @sidharthachatterjee

**Comment by freiksenet** [comment]
You can't use multiple static queries in one file, it's a known limitation. Sorry.
