### ISSUE TITLE
How to generate a theme from a starter

### ISSUE THREAD

**Issue by chrisdesilva** [gatsbyjs/gatsby#16416]
I'm trying to figure out how to implement a Gatsby theme for my company. Basically, we've got 70 or so partner pages, each of which contain roughly the same layout, styling, legal content, etc. and just have partner info swapped out. Here are two example partner pages to illustrate the basic idea: 

1. https://digitalcrafts.skills.fund/
2. https://galvanize.skills.fund/

All of our partner pages are currently set up on a CMS but I'm working to see if migrating over to Gatsby/Netlify makes sense. We've got one demo site up now that's been built with the Gatsby default starter and updated accordingly: https://thisismetis.skills.fund/. And the repo: https://github.com/chrisdesilva/skills_fund_metis

One strategy moving forward would be to set a repo as a template and create new pages from that template. This seems a bit time-consuming and repetitive. It also leads to a bigger headache when there are small changes that need to be pushed to all partner pages, like updated legal terms/disclaimers/rates. I'd prefer not to have to go through 70 projects to add a line of text. 

It sounds like Gatsby themes are a solution to this as I could build a theme and if any changes need to be applied across all partner sites, I can just update the theme and all partner sites via npm. I'm running into a few issues and am having a hard time figuring out how to implement this solution.

I followed along with Gatsby's docs, both Jason Lengstorf videos about composing themes, and a variety of blog posts, but all seem to point in different directions. Some use yaml, some use mdx, some projects have different folder structures than others. I got to the point where I had a root directory with a theme directory and a site directory. In theme > src > components, I built out the components I needed for the site. These are all basic class and functional components. In site > src > index.js, I was able to, for example, import Header from "../themes/src/components" (don't remember the exact path, but I imported theme components into the site directory). I wasn't sure where to go from there. My initial thought was to build theme components as children that accepted props for wherever I needed to inject partner specific information. Here's a small example of my thinking...

Theme > src > components > header.js

```
import React from 'react';
...

const Header = props => {
  return (
    <div>
       <h1>Welcome to the Partner Page for {props.schoolName}</h1>
    </div>
  )
}

export default Header;
```

Site > src > index.js

```
import React from 'react'
...

const Index = () => {
  <div>
    <Header
      schoolName="Galvanize"
    />
  </div>
}

export default Index
```

I'm assuming this isn't the right way to go about it, but I'd love some direction as to how to go about building the theme and site in my yarn workspace and then figuring out how to use that theme to build out the different partner pages.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by freiksenet** [comment]
CC @ChristopherBiscardi @jlengstorf

**Comment by jlengstorf** [comment]
@chrisdesilva it looks like you're headed in the right direction. I recently helped Laurie Barth [convert some of her site into a theme](https://youtu.be/ciGFxNamooI?list=PLz8Iz-Fnk_eTpvd49Sa77NiF8Uqq5Iykx) on my livestream, which might be helpful here.

In addition, you may want to check out the [case study on Apollo's using of Gatsby themes](https://www.gatsbyjs.org/blog/2019-07-03-using-themes-for-distributed-docs/), as it sounds like you're looking to do a pretty similar thing.

There's not really an "official" approach for themes yet, so we don't have a recommended approach.

I'm going to close this issue, but please feel free to ask additional questions here or on [Twitter](https://twitter.com/jlengstorf). Thanks!
