### ISSUE TITLE
warn npm install --global gatsby

### ISSUE THREAD

**Issue by jileieli** [gatsbyjs/gatsby#1642]
**system environments:**
os:ubuntu16. 0.4  x64
nodejs:v6.11.1
npm: 5.3.0

when I Install the “Hello World” starter reference https://www.gatsbyjs.org/tutorial/part-one/.

npm install --global gatsby

detail output:
root@jileilei-virtual-machine:/home/jileilei/gatsbyjslearn# npm install --global gatsby
/usr/bin/gatsby -> /usr/lib/node_modules/gatsby/dist/gatsby-cli.js

> uws@0.14.5 install /usr/lib/node_modules/gatsby/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

sh: 1: cannot create build_log.txt: Permission denied
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/gatsby/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ gatsby@1.5.0

**Comment by jileieli** [comment]
When I do "npm install --global gatsby"  second times,occur follows.But  I can gatsby new now
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/gatsby/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by pigooosuke** [comment]
I've got  the same problem.
But, above WARNs are about mismatch with Mac os option. 
if you avoid from the error npm install --global gatsby --no-optional.
But , i think a install  problem is depended on another point.
Do you have "gatsby new gatsby-site" logs?

**Comment by jileieli** [comment]
thanks @pigooosuke .
my "gatsby new gatsby-site" logs:
jileilei@jileilei-virtual-machine:~/gatsbyjslearn$ gatsby new gatsby-site
2017-07-30T09:38:08+0800 <log> init-starter.js:111 (clone) Cloning git repo git://github.com/gatsbyjs/gatsby-starter-default.git to gatsby-site...
2017-07-30T09:38:11+0800 <log> init-starter.js:118 () Created starter directory layout
2017-07-30T09:38:11+0800 <log> init-starter.js:48 (install) Installing packages...

> uws@0.14.5 install /home/jileilei/gatsbyjslearn/gatsby-site/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

added 1232 packages in 70.208s

**Comment by pigooosuke** [comment]
only these? it's seemed like succeess. 
if so, it's no problem.

**Comment by jileieli** [comment]
I get it,thanks @pigooosuke
