### ISSUE TITLE
The setting of gatsby.config.js is wrong

### ISSUE THREAD

**Issue by cyder777** [gatsbyjs/gatsby#16428]
## Description

According to Readme.md.
Authorization filed is 

gatsby-config.js
```
headers: {
            Authorization: `bearer <token>`
          },
```
But it's not working for me.

This one is collect for me.
```
headers: {
            Authorization: `Bearer  <token>`,
          },
```

### Environment
Mac os Mojave localhost

**Comment by lannonbr** [comment]
Hi @cyder777, so can you point us to the specific Readme that you are referencing? Looking at this, you are saying that using the word `bearer` lowercase doesn't work, but using it being capitalized as `Bearer` does. Then we can validate that this is the case and if so we can quickly fix the docs to be correct.

**Comment by davidbailey00** [comment]
This seems to be a valid issue - all other references to `Bearer` in docs and code are uppercase, outside of the file `packages/gatsby-source-graphql/README.md`:

![image](https://user-images.githubusercontent.com/4248177/62719014-e8330400-b9fe-11e9-8867-07596e43a363.png)

Will open a PR :+1:
