### ISSUE TITLE
Client-only paths like /:foo/:bar/:baz on Netlify: how? 🤔

### ISSUE THREAD

**Issue by kalinchernev** [gatsbyjs/gatsby#16427]
## Summary

I have a multilingual project in which part of the content should be fetched and displayed from an API without modifications. I have a temporary fix using hashes, but these are breaking the existing logic greatly and I'm searching for ways to have paths match server-rendered content paths.

## Relevant information

The [same question has been addressed to Netlify team in their community forum](https://community.netlify.com/t/path-redirect-rewrite-with-several-parts/2269/2).

I've prepared a stripped-down version of the project in a separate repository to facilitate anyone willing to help me run the project: https://github.com/kalinchernev/gatsby-client-routes There are no dependencies to third party systems here and it builds quite fast because there are only 3 languages sufficient to illustrate the issue. Actual site has 24 languages.

The site has already [using the suggested approach](https://github.com/kalinchernev/gatsby-client-routes/blob/master/gatsby-node.js#L9-L25) for [creating client-only paths in Gatsby](https://www.gatsbyjs.org/tutorial/authentication-tutorial/#creating-client-only-routes). The only difference from the example is that `createPage()` is run for each language, so that in terms of paths, end results look like this:

```sh
$ pwd                                                               
/home/kalata/Projects/@eci/gatsby-client-routes/public
$ tree -L 3
.
├── bg
│   ├── 404
│   │   └── index.html
│   ├── 404.html
│   ├── index.html
│   ├── initiatives
│   │   └── index.html
│   └── sitemap
│       └── index.html
├── en
│   ├── 404
│   │   └── index.html
│   ├── 404.html
│   ├── index.html
│   ├── initiatives
│   │   └── index.html
│   └── sitemap
│       └── index.html
├── favicon.ico
├── fr
│   ├── 404
│   │   └── index.html
│   ├── 404.html
│   ├── index.html
│   ├── initiatives
│   │   └── index.html
│   └── sitemap
│       └── index.html
├── index.html
├── page-data
│   ├── bg
│   │   ├── 404
│   │   ├── 404.html
│   │   ├── initiatives
│   │   ├── page-data.json
│   │   └── sitemap
│   ├── en
│   │   ├── 404
│   │   ├── 404.html
│   │   ├── initiatives
│   │   ├── page-data.json
│   │   └── sitemap
│   ├── fr
│   │   ├── 404
│   │   ├── 404.html
│   │   ├── initiatives
│   │   ├── page-data.json
│   │   └── sitemap
│   └── index
│       └── page-data.json
├── _redirects
├── static
```

Also, the [example](https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths) for this particular topic has been implemented in the [corresponding page file](https://github.com/kalinchernev/gatsby-client-routes/blob/master/src/pages/initiatives.jsx).

So current behavior is that locally this works `http://localhost:8000/en/initiatives/open/2019/000010` (probably because of the running server in development mode) and when on Netlify `https://gatsby-client-routes-ecip.netlify.com/en/initiatives/open/2019/000010` moves the user to `https://gatsby-client-routes-ecip.netlify.com/en/initiatives` regardless of the fact I have this

```
/en/initiatives/*  /en/initiatives/index.html 200
```

in https://github.com/kalinchernev/gatsby-client-routes/blob/master/static/_redirects which I know takes effect, because the 404 pages are fine.

Because I have weak knowledge on the Reach router, I have

```jsx
const InitiativeRouter = props => (
  <Location>
    {({ location }) => <Router location={location}>{props.children}</Router>}
  </Location>
);

const Initiative = () => (
  <InitiativeRouter>
    <Page path="/*" />
  </InitiativeRouter>
);
```
and the `Page` is the component itself. Maybe I am trying to achieve something impossible having several paths in the url and not in the directories?

### Environment

`gatsby info --clipboard` gives the following:

```
  System:
    OS: Linux 5.2 Manjaro Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
  Languages:
    Python: 3.7.3 - /usr/bin/python
  Browsers:
    Firefox: 68.0.1
  npmPackages:
    gatsby: 2.9.7 => 2.9.7
    gatsby-background-image: 0.8.0 => 0.8.0
    gatsby-link: 2.1.1 => 2.1.1
    gatsby-plugin-layout: 1.0.15 => 1.0.15
    gatsby-plugin-react-helmet: 3.0.12 => 3.0.12
    gatsby-plugin-sharp: 2.2.3 => 2.2.3
    gatsby-source-filesystem: 2.0.42 => 2.0.42
    gatsby-transformer-json: 2.1.11 => 2.1.11
    gatsby-transformer-sharp: 2.2.1 => 2.2.1
  npmGlobalPackages:
    gatsby-cli: 2.7.27
```

### File contents

All files are provided in the before-mentioned repository: https://github.com/kalinchernev/gatsby-client-routes

**Comment by sidharthachatterjee** [comment]
Have you tried using the [gatsby-plugin-netlify](https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/) plugin? It will automatically generate redirects for Netlify for you to make the deep nested client side routes work correctly.

**Comment by kalinchernev** [comment]
@sidharthachatterjee [I tried it](https://github.com/kalinchernev/gatsby-client-routes/commit/174b5b798d21837f08f49595b790448e321e51e6), yes, it's "simply" taking the regex from the node api file and makes `/initiatives/*` instruction, which does not help.

**Comment by brunapereira** [comment]
Hi @kalinchernev, were you able to solve it? I’m going through the same problem right now.

**Comment by kalinchernev** [comment]
I don't think so, in the end I removed the gatsby plugin generating the redirects together with the redirects and just left the ones generated and actually existing.
