### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by gursewaksingh-jaw** [gatsbyjs/gatsby#16425]
Getting this error :

AIO@DESKTOP-L3FSC3E MINGW64 /e/gatsby
$ gatsby new lovely-gatsby-site
bash: gatsby: command not found

Local Environment : 

AIO@DESKTOP-L3FSC3E MINGW64 /e/gatsby
$ npm -g ls --depth=0
C:\Users\TEMP.DESKTOP-L3FSC3E.031\AppData\Roaming\npm
+-- gatsby-cli@2.7.28
`-- windows-build-tools@5.2.2

**Comment by freiksenet** [comment]
It sounds like gatsby isn't on PATH. You can try using npx (`npx gatsby new lovely-gatsby-site`).

I'm closing this issue for now, feel free to open it if the problem persists.
