### ISSUE TITLE
Better forwarding of graphql properties

### ISSUE THREAD

**Issue by Alxandr** [gatsbyjs/gatsby#1643]
I'm creating childnodes of MarkdownRemark in my gatsby page, and I want to create graphql properties that are forwarded to the GraphQL Markdown node. I've got this working using the following hack:

```js
  const forwardToParent = field => async (postNode, opts, _2, _3) => {
    const { schema } = _3;
    const parent = await getNode(postNode.parent);
    const type = schema.getType('MarkdownRemark');
    const fields = type.getFields();
    const fieldInfo = fields[field];
    return await fieldInfo.resolve(parent, opts, _2, _3);
  };
```

This might just be me being clueless about how to do gatsby, but this should probably be supported somewhat better if it's not. And if it is, please point me at the right direction :).

**Comment by KyleAMathews** [comment]
Not entirely sure I understand what you're trying to do but perhaps https://www.gatsbyjs.org/docs/bound-action-creators/#createNodeField is what you want.

**Comment by Alxandr** [comment]
No. It's not. Because you cannot create a node field for the "html" component of a MarkdownRemark node, because it's being resolved lazily using the `GraphQL` resolve. Meaning that until you run a graphql query, the HTML does not exist. And you can't run this GraphQL query while the GraphQL schema isn't yet constructed.

**Comment by KyleAMathews** [comment]
Curious if other people run into this problem? Generating the HTML lazily is something we only do basically for markdown => html so it's something we could remove.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
