### ISSUE TITLE
Cache all the pages and assets

### ISSUE THREAD

**Issue by GuillaumeAmat** [gatsbyjs/gatsby#16431]
## Relevant information

Hello there 👋

I'm wondering if Gatsby (or gatsby-plugin-offline) is able to prefetch and cache all the pages and assets instead of "just" taking care of the `Link` targets.

Use case: When someone goes to my site, I don't want him to navigate throw all the pages to cache the assets manually... 

Am I missing something in the documentation?

Thanks!

**Comment by freiksenet** [comment]
Unfortunately this isn't currently possible. CC @davidbailey00, who is our offline expert.

**Comment by m-allanson** [comment]
It's worth noting there can be good reasons not to do this. If you have a very large site, or people are visiting from slow (or data-capped) connections, this could cause a lot of extra (and unexpected!) data usage for your visitors. 

The defaults for the offline plugin are designed to try and balance these trade-offs. That said it might be possible to do this with the offline plugin - I'll let @davidbailey00 comment on this later in the week.

**Comment by GuillaumeAmat** [comment]
@freiksenet @m-allanson Thank you both for your answers.

I totally understand the overweight and anti-performance behavior that this kind of need implies. But I the feature I have in mind is actually an opt-in one.

If, and only if, the Gatsby based project contains a full offline part, I would like to call a method to pre-cache all the required assets.

With that imperative way, it still respects the performance goals *and* it creates a lot of opportunities IMHO.

**Comment by davidbailey00** [comment]
Hi @GuillaumeAmat!

This isn't currently possible with the offline plugin although it's certainly something doable - I can get to work on a PR which allows specifying which pages you want to be precached.

**Comment by GuillaumeAmat** [comment]
> This isn't currently possible with the offline plugin although it's certainly something doable

Thanks for the confirmation @davidbailey00 👌

> I can get to work on a PR which allows specifying which pages you want to be precached.

That would be awesome thank you very much!

**Comment by GuillaumeAmat** [comment]
🙌

Can't wait to test that, thank you @davidbailey00!
