### ISSUE TITLE
[docs] improve ESLint docs

### ISSUE THREAD

**Issue by gregrickaby** [gatsbyjs/gatsby#16444]
## Summary

Friend of mine reached out asking if he could disable ESLint. He had already read the [Gatsby docs around ESLint](https://www.gatsbyjs.org/docs/eslint/), but wasn't sure if using native ESLint "stuff" worked in Gastby.

### Basic example

I told him yes, it should. And gave him the following snippet based on the [ESLint documentation](https://eslint.org/docs/user-guide/configuring.html#disabling-rules-with-inline-comments) in order to get around the warnings

```javascript
/* eslint-disable */

... code to be ignored ..

/* eslint-enable */
```

I think we could add a few more examples on how to use native ESLint configuration/options with Gatsby. I'd like to write a few snippets to drop into this page: https://www.gatsbyjs.org/docs/eslint/

### Motivation

Level-up the docs to enhance the experience around working with Gatsby.

**Comment by gregrickaby** [comment]
Adding a note because ESLint throws this into the terminal when there are problems:

```bash
You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
You can now view site in the browser.
```

Might help to mention this too (and quite honestly, I've never noticed it before 😆)

![screenshot](https://dl.dropbox.com/s/pz03pmil37d8u5z/Screenshot%202019-08-07%2020.24.26.png?dl=0)

**Comment by kushthedude** [comment]
@gregrickaby I would like to work on the following.

**Comment by kushthedude** [comment]
@gregrickaby I am working on it

**Comment by marcysutton** [comment]
Any update on this, @kushthedude?

**Comment by kushthedude** [comment]
A PR would be ready by this week. 😁

**Comment by vishakhanihore** [comment]
@kushthedude Any progress, if not I can claim this.

**Comment by laurieontech** [comment]
I believe the new additions on [disabling eslint](https://www.gatsbyjs.org/docs/eslint/#disabling-eslint) improve this experience. I'm going to close this for the moment, but feel free to re-open with further context if you feel additional examples are needed.
