### ISSUE TITLE
How is markdown tableOfContents supposed to work?

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#16445]
`gatsby-transformer-remark` and `gatsby-plugin-mdx` both expose a `tableOfContents` field, which returns a list of headings, with hash links to those headings. However, it seems that those links will do nothing out of the box because the heading elements themselves will not get the required ids.

It is not clear from the docs how this is supposed to work. When including `gatsby-remark-autolink-headers` it seems to works, (because both use `github-slugger`) but it would be a bit weird for core functionality to depend on a plugin?

**Comment by stefanprobst** [comment]
I'm still not clear on the intended use of `tableOfContents`.

**Comment by SANGET** [comment]
I also have doubts about this. Do you find any solution?

**Comment by SANGET** [comment]
> I also have doubts about this. Do you find any solution?

I found the solution, using the plugin `gatsby-remark-autolink-headers` can generate IDs for heading.

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-autolink-headers
