### ISSUE TITLE
The configured pathPrefix is stripped from the path of pages that start with the same prefix

### ISSUE THREAD

**Issue by trt2** [gatsbyjs/gatsby#16457]
## Description

Between version 2.8.8 and 2.9.0 of gatsby a change was made that caused the configured `pathPrefix` to be stripped from the path of pages that start with the same prefix.

The issue is still present in 2.13.52

### Steps to reproduce

I have set `pathPrefix` to `/p`, and I have a directory in the page root directory called `/privacynotice`.
gatsby will incorrectly strip `/p` from the page location, resulting in `rivacynotice` being used.
When hovering a `<Link to="/privacynotice">...</Link>` the browser will attempt to fetch the file `/p/page-data/rivacynotice/page-data.json`.

**Comment by freiksenet** [comment]
Thank you for reporting this @trt2!

Would you like to make a PR to fix that? We would greatly appreciate the help. :purple_heart:

**Comment by trt2** [comment]
I do not think I am familiar enough with the gatsby codebase to submit a patch that reliably fixes this issue without creating undesired side effects.

I did look into the error and it occurs when trimming path name in the function `trimPathname` in `packages/gatsby/cache-dir/find-path.js`.

As a quick hack, for testing, I modified the function so that it looks like this:
```
const trimPathname = rawPathname => {
  let pathname = decodeURIComponent(rawPathname)

  if(__BASE_PATH__.length > 0) {
    if(pathname.startsWith((__BASE_PATH__ + '/').replace(/\/+/g, '/'))) {
      // Remove the pathPrefix from the pathname.
      pathname = stripPrefix(pathname, __BASE_PATH__)
    }
  }

  pathname
    // Remove any hashfragment
    .split(`#`)[0]
    // Remove search query
    .split(`?`)[0]

  return pathname
}
```

This "fixed" the errors I got by only stripping the prefix if it matches the specified pathPrefix followed by a `/`.
This is probably not a proper fix for the issue, and this function might not even be the correct place to fix it.

**Comment by trt2** [comment]
This is still an issue with the latest version (2.15.6). Gatsby 2.8.8 is still the last version that allows the links to be followed when clicked (even if an error message is displayed in the browser console).

**Comment by robin-macpherson** [comment]
Thanks for the great issue description and comments, @trt2 ! 
@freiksenet I'll try my best to take a look at this and open a PR shortly. If for some reason I get stuck I'll be sure to update and ask for guidance in the PR 🙂

**Comment by kmck** [comment]
I'm running into this issue as well! In my naive and shallow investigation after encountering the bug myself, I noticed that `loadPage` is called the same the whether it's processing something definitely prefixed (eg. `browserLoc.pathname` of `"/blog/blog"`) or definitely not prefixed (eg. `<Link to="/blog">`).

Looking for a slash after the prefix helps, but I don't think it solves it 100%. I think trying to guess the context means there can always be ambiguous cases. Can `prefixPath` be processed and removed earlier when the source of the path is still known? That way downstream functions like `loadPage` could assume that the path isn't prefixed and avoid over-processing. Seems like it could requiring updating a bunch of call sites, and I'm not that familiar with Gatsby, so I might be totally off-base!

**Comment by robin-macpherson** [comment]
> I'm running into this issue as well! In my naive and shallow investigation after encountering the bug myself, I noticed that `loadPage` is called the same the whether it's processing something definitely prefixed (eg. `browserLoc.pathname` of `"/blog/blog"`) or definitely not prefixed (eg. `<Link to="/blog">`).
> 
> Looking for a slash after the prefix helps, but I don't think it solves it 100%. I think trying to guess the context means there can always be ambiguous cases. Can `prefixPath` be processed and removed earlier when the source of the path is still known? That way downstream functions like `loadPage` could assume that the path isn't prefixed and avoid over-processing. Seems like it could requiring updating a bunch of call sites, and I'm not that familiar with Gatsby, so I might be totally off-base!

Hi @kmck ! Just left a comment on your PR to let you know that I already have a PR that's about to be merged that fixes this. Just need to update e2e tests and reached out for some guidance on taking care of that and it'll be ready to go (see the PR reference just above in this issue's history). Thanks a lot for inputting!

**Comment by henrikwirth** [comment]
Isn't this connected to this #15334 ?
I also still have these problems.
