### ISSUE TITLE
Support for .jsx extensions

### ISSUE THREAD

**Issue by jalik** [gatsbyjs/gatsby#16450]
## Summary

Like all my projects, I have installed the `eslint-airbnb-config` to check code quality and autoformat code (with IntelliJ IDEA Ultimate), I've run these commands in the root folder :

```sh
npm i -D eslint-config-airbnb eslint-plugin-jest
npx install-peerdeps --dev eslint-config-airbnb
```

Then I added my `.eslintrc` file :
```json
{
  "extends": "airbnb"
}
```

But after that I had errors like `JSX not allowed in files with extension ' .js' (react/jsx-filename-extension)`, so I tried to rename files, but `.jsx` extension not being recognized by default in the current Webpack config of Gatsby...

### Basic example

After digging here and there, I found how to add support for .jsx extension, and would like it to be supported by default in Gatsby, because it should be the case since .jsx is representing files containing JSX code, the following setup allows to use either `.js` or `.jsx`.

I've added a `.babelrc` with this content to support React and ES6 syntax :
```json
{
  "presets": [
    "babel-preset-gatsby"
  ]
}
```

Of course I've installed the preset package:
```sh
npm i -D babel-preset-gatsby
```

Then in the file `gatsby-node.js`, I've added this:
```js
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    module: {
      rules: [
        {
          test: /\.jsx$/,
          loader: 'babel-loader',
        },
      ],
    },
    resolve: {
      extensions: ['.jsx'],
    },
  });
};
```

I did not have to mention `.js` to keep supporting `.js` extension, which is good.

### Motivation

I am not using prettier, which is AFAIK relatively commonly used by Visual Studio Code users (which I am not neither).

Instead I format and check code using ESLint.
It would be awesome to have `.jsx` extension supported by default, so when adding an ESLint config like the AirBnB's one, we would only need to do the steps in the summary, and not the steps in the Basic example.

**Comment by m-allanson** [comment]
@jalik I think Gatsby should support `.jsx` already? Can you share [a minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) that demos jsx files not working? Along with the results of running `gatsby info`.

Thanks!

**Comment by jalik** [comment]
okay... indeed I am unable to reproduce the problem I had, even doing the exact same steps than before, which were :
- run `gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`
- rename `index.js` to `index.jsx` or include a component file which has the extension `.jsx`
- run `gatsby develop`
- check for errors in the console or in the page at http://localhost:8000/

I would says it was something wrong with the setup, I cannot explain, but I was using another computer at the moment (which died the same day...).

Thank you for the assistance and sorry for the time wasted.

Note: Gatsby is what I was looking for several years (matching http requests with files), it is a pleasure to work with. Thanks a lot!

**Comment by olegKusov** [comment]
I have same issue

**Comment by olegKusov** [comment]
Try to delete .cache folder and public folder and build it again

**Comment by kkshmz** [comment]
Hi, this just doesn't work for the index page.
Is there some reason for this or am I debugging the situation wrong?

**Comment by blopa** [comment]
I can only make it work with "index.jsx" but not "Index.jsx". It would be awesome if a support for Index.jsx would be added (capital-case "Index").
