### ISSUE TITLE
gatsby-plugin-offline + React.cloneElement

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#16456]
When i use in the same project: 
gatsby plugin offline , 
gatsby plugin layout , 
and i use  React.cloneElement in layout 

```
class Layout extends React.Component {
...
return(
...
{ React.cloneElement(this.props.children, { lanDefs: this.props.lanDefs, config: this.props.config, lanId: this.context.data.lanId })}
...
}

```

Problem occur after build with service worker active.
Layout is messed, elements in dom are duplicated, one div get id of other div ... 

If i do not use React.cloneElement in layout or if i do not use gatsby plugin offline there is no problems.

**Comment by davidbailey00** [comment]
Hi @bjatwork, thanks for opening this issue!

If possible, please could you create a minimal reproduction so that we can better diagnose what's happening? That will help us to fix the issue faster :slightly_smiling_face: Thanks!
