### ISSUE TITLE
Change in page context between builds doesn't work correctly 

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#16477]
As described in https://github.com/gatsbyjs/gatsby/pull/15404#issuecomment-509507862 consecutive runs of `gatsby build` currently don't take a change in page context into account. 

### Reproduction Instructions

- run `gatsby build`
- change page context
- run `gatsby build` again

### Expected Behaviour

The page should get updated 

### Current Behaviour

The page is not updated 

### Potential Solution

We could fix this by persisting pages in redux

**Comment by LekoArts** [comment]
Duplicate of https://github.com/gatsbyjs/gatsby/issues/26520
