### ISSUE TITLE
gatsby-transformer-remark excerpt tests should not use toMatch but toBe

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#16474]
The [tests](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/__tests__/extend-node.js) for `excerpt` in `gatsby-transformer-remark` currently use `jest`'s  `toMatch` and `toMatchObject`. This seems weird because we want to check the exact excerpt, while `toMatch` will also be cool when the result starts with the expected string -- which is exactly *not* what we want for an excerpt.

**Comment by nguyenami** [comment]
I would like to take this one, if you can point me where to go. I'm newbie.

**Comment by stefanprobst** [comment]
Great!

You will find the tests for the markdown transformer plugin in [`packages/gatsby-transformer-remark/src/__tests__/extend-node.js`](https://github.com/gatsbyjs/gatsby/blob/6dad691f3080a5b3ec9223fe21ccb170519bd395/packages/gatsby-transformer-remark/src/__tests__/extend-node.js#L121-L775) -- look for the tests grouped under the "Excerpt is generated correctly" `describe` block.

The test setup is a bit unconventional, but you will find test assertions like this:
```js
expect(node.excerpt).toMatch('Where oh where is my little pony?')
```

This is problematic because `toMatch` will pass the assertion not only if `node.excerpt` exactly matches the string, but also when `node.excerpt` starts with the string, but is actually longer. For excerpts we want to make sure that the excerpt string has exactly the correct length. (You can find more background info on matchers [here](https://jestjs.io/docs/en/expect))

So the first step would be to replace `toMatch` in those tests with `toBe`, then run the tests and see if anything breaks.

Don't hesitate to ask if anything is unclear!

**Comment by nguyenami** [comment]
Sure, I will take a look.
