### ISSUE TITLE
Remove flow annotations

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#16472]
We don't really use them and there are very few sprinkled through the code base.

**Comment by crutchcorn** [comment]
I'll take this one

**Comment by sidharthachatterjee** [comment]
Sure @crutchcorn Thank you for picking it up! 🙌

**Comment by stefanprobst** [comment]
Can we somehow rescue the scattered types from [type builders](https://github.com/gatsbyjs/gatsby/blob/23a460a146e4de02c53ccf00a57b6e7f76163e44/packages/gatsby/src/schema/types/type-builders.js#L21-L45), [field extensions](https://github.com/gatsbyjs/gatsby/blob/23a460a146e4de02c53ccf00a57b6e7f76163e44/packages/gatsby/src/schema/extensions/index.js#L14-L21) and [node model](https://github.com/gatsbyjs/gatsby/blob/23a460a146e4de02c53ccf00a57b6e7f76163e44/packages/gatsby/src/schema/node-model.js#L11-L54) and put them in TS?

**Comment by sidharthachatterjee** [comment]
@stefanprobst Could definitely do that but I reckon TS will need more repo wide tooling setup? 😞 Or do you propose .d.ts files? That would be good I think

**Comment by stefanprobst** [comment]
yes, just .d.ts files

**Comment by crutchcorn** [comment]
I'll make sure to include the types in .d.ts files

**Comment by crutchcorn** [comment]
Do we also want to do JSDoc types additional to `.d.ts` definition files? 

For example, something like this:

```
type QueryJob = {
  id: string,
  hash?: string,
  query: string,
  componentPath: string,
  context: Object,
  isPage: Boolean,
}

// Run query
module.exports = async (queryJob: QueryJob) => {
```

Could turn into something like this:
```

/**
 * @typedef QueryJob
 * @param {string} id
 * @param {string} [hash]
 * @param {string} query
 * @param {string} componentPath
 * @param {Object} context
 * @param {Boolean} isPage
 */

// Run query
/**
 * @param {QueryJob} queryJob
 */
module.exports = async queryJob => {
```

**Comment by sidharthachatterjee** [comment]
Probably best to not duplicate them across both. Since that’s one more thing that’ll need to be kept consistent. I think typescript definitions are a good source of truth and sufficient.

**Comment by crutchcorn** [comment]
I agree. I just was wondering your thoughts on this.

**Comment by crutchcorn** [comment]
Just wanted to jump in and mention that I have some initial work on this branch:

https://github.com/crutchcorn/gatsby/tree/remove-flow-definitions

But it seems to be causing various test failures. I intend to be looking into them today and tomorrow

**Comment by brolag** [comment]
I'm interested in checking those conflicts
