### ISSUE TITLE
[gatsby-source-wordpress] Empty ACF fields break the query

### ISSUE THREAD

**Issue by mavalon** [gatsbyjs/gatsby#16470]
## Description

I have a number of Custom Field Types with ACF's, including Relationships.  These fields are optional, they may have zero or an unlimited number of children.  

The only way the GraphQL queries actually work, though, is if all the records have at least one relationship specified for each field type.  It seems that instead of building the schema based on the Custom Post Type's fields, it's basing it on the actual response from the REST API.  However, I can't possibly know what the response will be for each query.  Some will have relationships others will not.  How can I get around this issue?

I am new to Gatsby and GraphQL, so maybe I'm just missing something.

### Steps to reproduce

- In Wordpress, create a Custom Field Type
- Add ACF's to it including a Relationship field
- Add a record that specifies a relationship
- Add query to `gatsby-node.js` that queries that field
- Build the project...it works
- Create another record in Wordpress leaving that field empty
- Build the project again and note the errors

### Expected result

It should compile without errors

### Actual result
Errors when building the project
```


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "articles" on type "wordpress__wp_TopicsAcf".

File: gatsby-node.js:39:26


 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

Cannot query field "articles" on type "wordpress__wp_topicsAcf".

GraphQL request:32:15
31 |               gallery
32 |               articles
   |               ^
33 |               locality
  - gatsby-node.js:120 Object.exports.createPages
    C:/htdocs/frontend-gatsby/gatsby-node.js:120:15



```

### Environment
```

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.6.2 - C:\Users\Michael\AppData\Local\Programs\Python\Python36\python.EXE
  Browsers:
    Edge: 38.14393.1066.0
  npmPackages:
    gatsby: ^2.13.45 => 2.13.45
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-google-analytics: ^2.1.7 => 2.1.7
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-source-filesystem: ^2.1.7 => 2.1.7
    gatsby-source-wordpress: ^3.1.13 => 3.1.13
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5


```

**Comment by mavalon** [comment]
I think I might be able to resolve this issue by using `gatsby-source-graphql` instead of `gatsby-source-wordpress` and installing a bunch of wordpress plugins found at https://www.wpgraphql.com/.  So, I'll close this for now.

**Comment by devrchancay** [comment]
To make it work with `gatsby-source-wordpress` you should normalize the data, you can check: https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#using-a-custom-normalizer

I did something similar with a custom field nested for food ingredients.

**Comment by robmarshall** [comment]
Hi devrchancay,

Would you be able to provide link/gist to show how you set up that normalized?

I have been trying to loop through my entities and fix this issue for a few days now but cannot seem to sort it!

**Comment by mavalon** [comment]
I ended up switching to `gatsby-source-graphql` as I was having too many issues with `gatsby-source-wordpress`.

It seemed to me that the issue perhaps is that `gatsby-source-wordpress` derives its schema from the _**first**_ record found.  If that first record has empty fields, those fields are not picked up on and added to the schema.  I came to this conclusion when I added data to all fields in the first record and it worked, and then updated the first record again with some empty fields, and it failed.

So, if my theory is correct, it should be changed to evaluate fields from _all existing_ records (not just the first one in the dataset) when creating the schema.  (Of course, if all records are missing data for a particular field, then the field would still be omitted from the schema, which could still be a problem.)

Anyway, as I mentioned above, I've had better luck using  `gatsby-source-graphql` and I've abandoned  `gatsby-source-wordpress`, so this issue is no longer relevant to me (though it should still be looked into).

**Comment by artypineda** [comment]
i agree with @mavalon. It's 2020 in May and building a new headless setup with gatsby-source-wordpress and I cannot get across not adding dummy data for new pages. Im not having the issue where the conditional statements aren't working either. I will attempt to use gatsby-source-graphql next.
