### ISSUE TITLE
[gatsby-source-wordpress] multilingual support (WPML)

### ISSUE THREAD

**Issue by owenhoskins** [gatsbyjs/gatsby#1648]
Hello again. Using WPML only the default language is fetched with: 

`http://website.com/wp-json/wp/v2/posts`

it is possible to get posts in another language like so:

`http://website.com/de/wp-json/wp/v2/posts`

Setting the baseUrl like `website.com/de` will fetch the German posts.

The goal would be to serve EN posts at `http://website.com/post/name-of-post` and DE posts at `http://website.com/de/post/name-of-post` 

How would this best be approached??

**Comment by sebastienfi** [comment]
An easy fix would be to have one Gatsby site per language with a root url of `http://website.com/de`
