### ISSUE TITLE
[gatsby-plugin-mdx] getting `Cannot read property '__reactstandin__key' of null` from react-hot-loader when i accidentally render `undefined` to MDXRenderer from gatsby-plugin-mdx

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#16481]
## Description

i'm starting to get these a lot:

```
react-hot-loader.development.js:1229 Uncaught TypeError: Cannot read property '__reactstandin__key' of null
    at isProxyType (react-hot-loader.development.js:1229)
    at resolveProxy (react-hot-loader.development.js:1766)
    at resolveSimpleType (react-hot-loader.development.js:1782)
    at Object.React$$1.createElement (react-hot-loader.development.js:2813)
    at MDXRenderer (mdx-renderer.js:24)
    at renderWithHooks (react-dom.development.js:12939)
    at mountIndeterminateComponent (react-dom.development.js:15021)
    at beginWork (react-dom.development.js:15626)
    at performUnitOfWork (react-dom.development.js:19313)
    at workLoop (react-dom.development.js:19353)
    at HTMLUnknownElement.callCallback (react-dom.development.js:150)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:200)
    at invokeGuardedCallback (react-dom.development.js:257)
    at replayUnitOfWork (react-dom.development.js:18579)
    at renderRoot (react-dom.development.js:19469)
    at performWorkOnRoot (react-dom.development.js:20343)
    at performWork (react-dom.development.js:20255)
    at performSyncWork (react-dom.development.js:20229)
    at requestWork (react-dom.development.js:20098)
    at scheduleWork (react-dom.development.js:19912)
    at Object.enqueueSetState (react-dom.development.js:11170)
    at LocationProvider../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:335)
    at index.js:104


index.js:2177 The above error occurred in the <MDXRenderer> component:
    in MDXRenderer (at pages/index.js:81)
    in section (created by Context.Consumer)
	// ...


React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```

i think this is new? and i searched and didnt find a related issue and so i am filing this. 

after some investigation i think i found the cause. see below

### Steps to reproduce

i think this happens when you accidentally pass `undefined` to MDXRenderer from `gatsby-plugin-mdx`. the error message is waaaay unintuitive and should be improved.

### Expected result

we should have a more descriptive error.

### Environment

```

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0.4
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.50 => 2.13.50 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4 
    gatsby-theme: ^0.0.6 => 0.0.6 
  npmGlobalPackages:
    gatsby-theme-workspace: 1.0.0
    gatsby-theme: 0.0.6

```

**Comment by pierrenel** [comment]
Same here +1

**Comment by sw-yx** [comment]
@pierrenel do you see the fix? just make sure you're not rendering undefined. or if you can provide further investigation, please help so that @ChristopherBiscardi has more info to work with

**Comment by pierrenel** [comment]
ah no -  I didn't see the fix - but I'm not using mdx, this is a fresh project using styled components - I get the error when trying to wrap <ThemeProvider theme={theme}> around the outermost level components in layout.js - theme is definitely a JS object though. I also get the same error when trying to add a global style object... super weird. I can give anyone access to the repo if they want to see?

**Comment by CRNRSTD** [comment]
+1 for styled-components' ThemeProvider.

**Comment by freiksenet** [comment]
CC @johno

**Comment by MWalid** [comment]
Same issue here with `<ThemeProvider theme={theme}>`

**Comment by MWalid** [comment]
In my case the error is:

`Cannot read property '__reactstandin__key' of undefined`

**Comment by johno** [comment]
I'll open up a PR/fix for MDX's side today, though this is something that happens in other circumstances as well. I've seen this occur more generally, if you pass `null`/`undefined` to `React.createElement` at the custom pragma level. It _appears_ like the standard React error is swallowed:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

Can anyone reproduce the `styled-components` error and toss it into a repo or codesandbox? I haven't seen it occur there before.

**Comment by CRNRSTD** [comment]
Well this is awkward... See if wrapping a **single child** instead of multiple children in the <ThemeProvider> fixes the issue like it did for me.

**Comment by thalseth** [comment]
Hi @johno ! Thanks for looking at this problem. I reproduced the error with `styled-components` in codesandbox here https://codesandbox.io/embed/gatsby-starter-default-g9xov. It looks like the `createGlobalStyle` function is the root creating the error reported by @MWalid .

**Comment by thalseth** [comment]
Awesome @CRNRSTD ! Your comment showed up after publishing the example 👆 😂 

But maybe the problem is that the standard React error is swallowed as @johno mentioned? Impossible to debug this. Just luck that someone know the requirements for using `ThemeProvider` by styled-components in this case 😎

**Comment by MWalid** [comment]
Thank you @CRNRSTD, you addressed the issue, and a little `<Fragment />` solved this error for me.

**Comment by ZQ-jhon** [comment]
same issue in my electron application.
```md
Node v12.3.0
electron v6.0.2
npm v6.9.0
"react-hot-loader": "v4.12.11",
"react": "16.9.0",
```

**Comment by jacklaurencegaray** [comment]
How I got the error:

```
<>
    <GlobalStyle />
    <ThemeProvider theme={{ mode: "dark" }}>
      {children}
    </ThemeProvider>
  </>
```

```
<>
    <GlobalStyle />
    <ThemeProvider theme={{ mode: "dark" }}>
      <>{children}</> // Wrap with a fragment/div
    </ThemeProvider>
</>
```

It seems that this issue is caused by `<ThemeProvider>` having multiple children.

**Comment by kwangkim** [comment]
In my case, old `react-helmet` caused this error.
By updating it to `5.2.1`, I could remove it.

**Comment by zubayrrr** [comment]
same error in a simple gatsby site

**Comment by egorzekov** [comment]
I faced the same error. The following two steps helped me:
1. Remove `.cache` folder
2. Restart `npm run develop`

**Comment by lisandropat** [comment]
react-tabs for me using Gatsby. Tried removing .cache, reinstalling and updating packages, using <> and <div> within {children}. Nothing.

**Comment by frontendjim-bjss** [comment]
May or may not be related but I was getting this error after having not exported the component before using it.

**Comment by shrugs** [comment]
searchers using react-hot-loader may find themselves here, so:

this is almost definitely because:
1) you either rendered an array of children (instead of a fragment) or
2) you rendered an undefined component

to more easily debug this, turn off react-hot-loader and get react's native error message, which will probably tell you which component is undefined

**Comment by cbillowes** [comment]
In my case the error is:

`Cannot read property '__reactstandin__key' of undefined`

I get this error when I encode a URLs in markdown. Wikipedia has parenthesis in their URLs so I tried to encode them with %28 and %29. I also tried escaping them with \. Escaping them gives me a different error. I'm not sure how to work around this.

**Comment by meronek** [comment]
I also get this error as soon as I use anything from react-stripe-elements. Any ideas on what to do?

**Comment by gyrad** [comment]
> I also get this error as soon as I use anything from react-stripe-elements. Any ideas on what to do?

Had the same issue with `react-styled-elements`. Check within your `Elements` component tags. It should only contain the component with the `injectStripe` HOC.

**Comment by isaacdpierce** [comment]
This error was fixed for me when I realized I was not importing with brackets - import { component } from './component'.

**Comment by PSalaun** [comment]
@isaacdpierce I second this, ran into this issue when using sanity's block-content-to-react and Theme UI, which also relies on a <ThemeProvider>. The error came from a named import instead of a default one.
