### ISSUE TITLE
Is there a way to intercept Link click?

### ISSUE THREAD

**Issue by LucaVerdecchia** [gatsbyjs/gatsby#16487]
Hi,

I'm encountering some problems working with gatsby and page animations, basically, when a user clicks on a link of the component <Link> an effect would start going from left to right filling all the viewport white.

Can I intercept the click of the component Link in gatsby and performing a prevent default?
I saw plugin like gatsby-plugin-layout but the documentation is poorly illustrated and confusing.

Thanks for the help..

**Comment by jonauz** [comment]
What is fixed? Seems like a questions and closed without any answer.. And it's a relevant question.
