### ISSUE TITLE
Router wrapper isn't focused on initial render

### ISSUE THREAD

**Issue by davidbailey00** [gatsbyjs/gatsby#16492]
## Description

On initial render, the focused element is not `#gatsby-focus-wrapper` as it is on subsequent navigations.

### Steps to reproduce

1. Visit a page for the first time
2. Check the focused element e.g. open a console and type `document.activeElement`

### Expected result

Should be the element with ID `gatsby-focus-wrapper`

### Actual result

There is nothing focused, or `document.activeElement` evaluates to the document body

### Environment

```
  System:
    OS: Linux 5.0 Pop!_OS 19.04
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.5.1 - /bin/zsh
  Binaries:
    Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.8.0/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.8.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.1
```

**Comment by davidbailey00** [comment]
@pieh could you give any insight on this? I saw you did a PR recently related to focusing on navigation so wondering if this is actually intended behaviour

**Comment by pieh** [comment]
I think `@reach/router` doesn't do any focus management on initial render. Now I'm not sure if this is best of accessibility, but that's the reason why I test focus only after navigation and not on initial render

**Comment by davidbailey00** [comment]
Closing since this is correct behaviour - thanks @marcysutton for the explanation!

> Compare it to regular HTML pages without client rendering: the page would load from the top, and a screen reader would announce a (configurable) page summary. That should still occur by default here. The only reason we advocate for focus management when client routes change is that otherwise nothing would occur to mimic static html page changes.
