### ISSUE TITLE
gatsby-transformer-sharp silently failing to create images

### ISSUE THREAD

**Issue by dmaynard** [gatsbyjs/gatsby#16507]
## Description

Images from blog post silently fail to build properly with 'gatsby build' but work properly with gatsby develop

### Steps to reproduce
clone and install
https://github.com/dmaynard/website
yarn clean
yarn build
yarn serve
then broswe to http://localhost:8000/software-artist-1982-vs-today/
note sometimes, but not always I get error messages during the build line the following:
(sharp:70391): GLib-CRITICAL **: 14:13:48.058: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:70391): GLib-CRITICAL **: 14:13:48.059: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:70391): GLib-CRITICAL **: 14:13:48.059: g_hash_table_lookup: assertion 'hash_table != NULL' failed

I suspect what is happening is that gatsby is forking a process to do the image processing and then node (running gatsby build) is exiting BEFORE the image processing has completely finished.  
### Expected result
full resolution images in this blog post

### Actual result
only very low resolution images appear

### Environment

System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 3.6.4 - /Users/dmaynard/anaconda3/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.1
    Safari: 12.1.2
  npmPackages:
    gatsby: 2.13.13 => 2.13.13
    gatsby-image: 2.0.31 => 2.0.31
    gatsby-plugin-catch-links: 2.0.12 => 2.0.12
    gatsby-plugin-feed: 2.0.14 => 2.0.14
    gatsby-plugin-google-analytics: 2.0.16 => 2.0.16
    gatsby-plugin-manifest: 2.0.22 => 2.0.22
    gatsby-plugin-netlify: ^2.0.13 => 2.1.4
    gatsby-plugin-nprogress: 2.0.9 => 2.0.9
    gatsby-plugin-offline: 2.0.24 => 2.0.24
    gatsby-plugin-react-helmet: 3.0.8 => 3.0.8
    gatsby-plugin-sass: ^2.0.10 => 2.1.5
    gatsby-plugin-sharp: 2.0.25 => 2.0.25
    gatsby-plugin-sitemap: 2.0.6 => 2.0.6
    gatsby-plugin-twitter: ^2.0.13 => 2.1.2
    gatsby-plugin-typography: ^2.2.10 => 2.3.2
    gatsby-remark-autolink-headers: 2.0.15 => 2.0.15
    gatsby-remark-copy-linked-files: 2.0.9 => 2.0.9
    gatsby-remark-images: 3.0.6 => 3.0.6
    gatsby-remark-prismjs: 3.2.4 => 3.2.4
    gatsby-source-filesystem: ^2.0.23 => 2.1.9
    gatsby-transformer-remark: 2.3.1 => 2.3.1
    gatsby-transformer-sharp: 2.1.15 => 2.1.15
  npmGlobalPackages:
    gatsby-cli: 2.7.9

**Comment by lannonbr** [comment]
Hey @dmaynard, that URL for the GitHub repo gives back a 404. Could you update it to point to a public repo?

**Comment by dmaynard** [comment]
Sorry about that.  The repository is now public.

David Maynard

**Comment by dmaynard** [comment]
repo is is now public.

**Comment by dmaynard** [comment]
Thanks to  @MaximeHeckel Upgrading to "gatsby-plugin-sharp": "^2.2.10" seems to have fixed this problem for me.
