### ISSUE TITLE
Does setWebpackConfig support multi-compiler mode?

### ISSUE THREAD

**Issue by let00** [gatsbyjs/gatsby#16504]
## Summary
I have a Webpack compiled project that I would like to integrate with Gatsby. I am using Gatsby to serve a blog under the '/blog' prefix, while the rest of the site is just static pages built with webpack.config.js. Is it possible to somehow hook into onCreateWebpackConfig API to have Gatsby build both the blog portion and the rest of the site using a separate webpack config?

## Relevant information

I have tried using webpack-merge with actions.replaceWebpackConfig, but that is returning errors. Seems like custom entry/output is not supported by Gatsby anyway.

```
exports.onCreateWebpackConfig = ({
    getConfig,
    actions,
}) => {
    actions.replaceWebpackConfig(require('webpack-merge')(myCustomConfig, getConfig());
};
```
 It would be nice if Gatsby supported something like this though: https://github.com/webpack/webpack/tree/master/examples/multi-compiler

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by m-allanson** [comment]
Hey @let00 here's a couple of things you could try. The `gatsby-plugin-netlify-cms` plugin sets up it's own webpack build, so you might be able to [refer to the code in this file](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify-cms/src/gatsby-node.js) to do what you want.

Alternatively you could use [the `onPostBuild` or `onPreBuild` API hooks](https://www.gatsbyjs.org/docs/node-apis/) to run your separate webpack config before or after the Gatsby build. This wouldn't be as closely integrated but might be the quickest way to get going if you have an existing webpack config and want to get something up and running.
