### ISSUE TITLE
"TypeError: Invalid attempt to spread non-iterable instance" after update...

### ISSUE THREAD

**Issue by busticated** [gatsbyjs/gatsby#16505]
hi there :wave:

## Description

i'm currently running `gatsby@2.9.4`. when i try to update to latest - at the time of posting this `gatsby@2.13.56` - i am no longer able to successfully build my site. when i try to update incrementally, the last version i'm able to use without error is `gatsby@2.9.11`

### Steps to reproduce

1. `npm update gatsby`
2. `gatsby build && gatsby serve`

### Expected result

site builds successfully, i'm able to view the live site locally

### Actual result

```
 ERROR #95313 

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html

  TypeError: Invalid attempt to spread non-iterable instance
```

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.0 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 5.10.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 77.0.3865.19
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.56 => 2.13.56 
    gatsby-cli: ^2.7.28 => 2.7.28 
    gatsby-image: ^2.2.8 => 2.2.8 
    gatsby-plugin-netlify: ^2.1.4 => 2.1.4 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3 
    gatsby-plugin-sharp: ^2.2.10 => 2.2.10 
    gatsby-plugin-sitemap: ^2.2.6 => 2.2.6 
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-source-contentful: ^2.1.18 => 2.1.18 
    gatsby-source-filesystem: ^2.1.9 => 2.1.9 
    gatsby-transformer-sharp: ^2.2.6 => 2.2.6 
    gatsby-transformer-yaml: ^2.2.4 => 2.2.4 
```

_edit: updated w/ more accurate version info_

**Comment by busticated** [comment]
this is especially odd since the [changelog](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/CHANGELOG.md#2100-2019-06-20) says:

```
2.10.0 (2019-06-20)
Note: Version bump only for package gatsby
```

🤔

**Comment by freiksenet** [comment]
The change between 2.9 and 2.10 was that we dropped node 6. This involved changing our babel preset to target node 8, which may have changed some transforms that are used there. It could be that you had some code that became incompatible after the update. :man_shrugging: 

I wonder if you could share the code with us, then we can help you debug it better.

**Comment by busticated** [comment]
> The change between 2.9 and 2.10 was that we dropped node 6.

that usually warrants bumping the major.

> This involved changing our babel preset to target node 8, which may have changed some transforms that are used there

clearly something changed - the interesting question is what exactly? did babel / gatsby's build pipeline support some non-spec compliant usage or something? (edit: yes, [seems so](https://github.com/babel/babel/issues/9942#issuecomment-489389297)).

from the above linked issue:

> All the instances were an attempt to spread a single object into an array

🤔 i don't see this usage in our codebase but i do see a lot of this kind of thing:

```jsx
<Foo key={id} {...props} />
```

...but my understanding is this is allowed and supported.

> I wonder if you could share the code with us, then we can help you debug it better.

it's a fairly large project w/ roughly ~400 individual usages of the spread syntax - all we have to go on atm is the build error posted above.

**Comment by OrKoN** [comment]
I have encountered the same issue, luckily in two places only. A code to reproduce:

```
const notAnArray = undefined;

return <div className={[...notAnArray].join(' ')}></div>
```

Apparently, this used to work fine with the previous version of Babel.

**Comment by wardpeet** [comment]
Invalid attempt to spread non-iterable instance.

This might be due `babel-preset-gatsby@0.2.3`. Could you checkout what version of babel-preset-gatsby that is installed?

@busticated could it be that https://github.com/gatsbyjs/gatsby/issues/16505#issuecomment-524287899 is causing this?

**Comment by ForkInSpace** [comment]
Did anyone figure the fix yet? 
I'm experiencing the same issue. 
I'm on npm v6.14.2 and these are my dependencies
```
  "dependencies": {
    "antd": "^3.26.7",
    "gatsby": "^2.10.12",
    "gatsby-plugin-antd": "^2.1.0",
    "gatsby-plugin-sass": "^2.1.27",
    "gatsby-source-filesystem": "^2.1.43",
    "gatsby-transformer-remark": "^2.6.45",
    "node-sass": "^4.13.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  },
  "devDependencies": {
    "prettier": "^1.19.1"
  }
```
I have tried node:
- v8.17.0
- v.10.19.0
- v.12.16.1
Gatsby: 
- 2.10.12
- 2.18.12

The only thing I can think of is that I recently downgraded from Catalina to High Sierra and only now has the issue turned up. Bit of a stretch may be but node-sass can be quirky with gatsby. 

Any help would be much appreciated.
