### ISSUE TITLE
Adding debug method in reporter API

### ISSUE THREAD

**Issue by iFlameing** [gatsbyjs/gatsby#16519]
## Summary
Can we have a debug method in reporter API as we have info, error, panic...

### Basic example
```Javascript
reporter.debug('text')
```
### Motivation
I am working on gatsby-source-plone and I want to give the user additional information from the plugin. So, that user can debug its code more easily.

thanks! I am happy to send a pr if needed. But some clarification is also needed because there is reporter.log is present in source code but not in docs. I asked this question on twitter and you can see the @KyleAMathews reply at this link.https://twitter.com/iFlameing/status/1160172956942602240

**Comment by johnstonbl01** [comment]
Hey, @sidharthachatterjee ! 👋 

I've just been working in this part of the CLI, and I think this one may already be done. Looks like there's a `verbose` method that logs as `debug` level. Code [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/reporter/index.js#L193).

If that's not acceptable or a debug log function is still needed, I'd be happy to add that in another PR.

**Comment by ediblecode** [comment]
Does look that way. Also looks like the docs for reporter is missing this `verbose` method: https://www.gatsbyjs.org/docs/node-api-helpers/#reporter. So maybe this should be a docs fix rather than a code fix?

**Comment by johnstonbl01** [comment]
That seems reasonable. I can make that change in the docs.
