### ISSUE TITLE
gatsby-remark-images: disable background-image on gatsby-resp-image-background-image to prevent FOUB

### ISSUE THREAD

**Issue by kimbaudi** [gatsbyjs/gatsby#16516]
## Description

[gatsby-remark-images](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images) has a blur-up effect that does not work well on `.png` images with transparent edges. I looked at the gatsby-remark-images [source code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/gatsby-browser.js#L23) and it is using css transition for the blur up effect. Unfortunately, the css transitions does not work well on images with alpha transparent edges. It causes a flash of ugly blur-up (FOUB) effect. We need a way to prevent/disable `background-image` css property on `gatsby-resp-image-background-image` class for `.png`s with transparent edges to prevent FOUB.

Related to https://github.com/gatsbyjs/gatsby/issues/4510#issuecomment-390781917

(**Note:** the blur-up effect doesn't work well even with `backgroundColor: 'transparent'` option set for `gatsby-remark-images`)

### Screenshots

![white-no-box-shadow-error](https://user-images.githubusercontent.com/1864092/62823955-28ec6380-bb4c-11e9-959c-4fc848cc17fb.png)
![black-no-box-shadow-error](https://user-images.githubusercontent.com/1864092/62823957-2b4ebd80-bb4c-11e9-8bae-2a888e047404.png)
![png-transparency-blur-issue](https://user-images.githubusercontent.com/1864092/62823958-2d188100-bb4c-11e9-95fa-c6d48607cf02.png)

### gatsby-config

```js
{
  resolve: `gatsby-transformer-remark`,
  options: {
    plugins: [
      {
        resolve: `gatsby-remark-images`,
        options: {
          maxWidth: 590,
          backgroundColor: `transparent`,
        },
      },
    ],
  },
},
```

We should have the ability to disable background-image css property on `gatsby-resp-image-background-image` class on images if it contains alpha transparency.

I think we should automatically disable background-image css property for `.png` images if  `backgroundColor: 'transparent"` option is set. We can do this for all .png images or only for .png images that have alpha transparency. 

### Steps to reproduce

- Create a gatsby project.
- Install and add `gatsby-transformer-remark` and `gatsby-remark-images` plugins
- set `backgroundColor: 'transparent'` option for `gatsby-remark-images` plugin
- add .png images to your markdown files that contain alpha transparent edges
- open webpage and refresh page to see flash of ugly blur-up (FOUB)

### Expected result

There is no flash of ugly blur-up (FOUB) on page refresh.

### Actual result

There is flash of ugly blur-up (FOUB) on page refresh.

### Link to demo project

- Go to https://paulkode.com/git-cannot-squash-without-a-previous-commit/
- Refresh the page (try in both dark/light modes)

### Environment

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (2) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.2.0/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.2.0/bin/npm
  Languages:
    Python: 3.7.3 - /home/paul/.pyenv/shims/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.1
  npmPackages:
    gatsby: ^2.13.57 => 2.13.57
    gatsby-image: ^2.2.8 => 2.2.8
    gatsby-plugin-emotion: ^4.1.2 => 4.1.2
    gatsby-plugin-feed: ^2.3.6 => 2.3.6
    gatsby-plugin-google-analytics: ^2.1.7 => 2.1.7
    gatsby-plugin-manifest: ^2.2.5 => 2.2.5
    gatsby-plugin-offline: ^2.2.5 => 2.2.5
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sass: ^2.1.6 => 2.1.6
    gatsby-plugin-sharp: ^2.2.11 => 2.2.11
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-remark-copy-linked-files: ^2.1.5 => 2.1.5
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: ^3.1.8 => 3.1.8
    gatsby-remark-katex: ^3.1.2 => 3.1.2
    gatsby-remark-prismjs: ^3.3.5 => 3.3.5
    gatsby-remark-responsive-iframe: ^2.2.4 => 2.2.4
    gatsby-remark-smartypants: ^2.1.2 => 2.1.2
    gatsby-source-filesystem: ^2.1.9 => 2.1.9
    gatsby-transformer-remark: ^2.6.12 => 2.6.12
    gatsby-transformer-sharp: ^2.2.6 => 2.2.6
```

**Comment by freiksenet** [comment]
Hello @kimbaudi!

Thank you for a detailed report! Would you like to add a fix to that via PR? I think a separate flag would be better than automatically doing it on transparent background.

Thanks! :purple_heart: :muscle:

**Comment by stevensukma** [comment]
I'll try working on this one

**Comment by kimbaudi** [comment]
@stevensukma - thanks for taking on this PR! I'm really curious how you plan to implement this. For me, the most interesting part of this task is determining whether `.png` images contain alpha-transparency (at least on the outer edges of the images). There is [this canvas technique](https://stackoverflow.com/a/41287919/1097123), which seems promising. Looking forward to this PR 😄

**Comment by stevensukma** [comment]
Thanks for the information, this is my first attempts on open source contribution. Hope you guys don't mind being a little bit patience :pray:.

**Comment by freiksenet** [comment]
@stevensukma Don't hesitate to ping me if you need any help!

**Comment by freiksenet** [comment]
@kimbaudi I think for now it's enough to have a flag so that user can manually set that, but in future we can detect the alpha layer in a way that you suggested.

**Comment by kimbaudi** [comment]
@freiksenet - I've been thinking about this and the bigger problem for me is the `backgroundColor` option:

1. `backgroundColor` default value should be `transparent` (not `white` or empty string or `undefined`). The initial value for css `background-color` property is `transparent`. See [this MDN doc].(https://developer.mozilla.org/en-US/docs/Web/CSS/background-color). It is wrong to assume that the background color is white by default. In my case, it could be either white or black so `transparent` would be the best default value for this property.

2. **naming the option `backgroundColor` is very misleading** because it does not actually change the `background-color` css property. In reality, it changes the `box-shadow` color. It should have really been named `boxShadowColor`. For backwards compatibility, we should keep `backgroundColor`, but I propose we also add `boxShadowColor` and eventually remove `backgroundColor`.

3. We should change how `backgroundColor` property affects box-shadow color from the current implementation. 

Currently, we do this:

```js
imageElement.style.boxShadow = "inset 0px 0px 0px 400px " + options.backgroundColor;
```

But, I think we should really be doing this:

```js
if (options.backgroundColor) {
  imageElement.style.boxShadow = `inset 0px 0px 0px 400px ${options.backgroundColor}`;
}
```

This way, if `backgroundColor` option is set to `false`, `undefined`, `null` or empty string (``), the box-shadow will not applied, which is what I expect to happen but it doesn't. 😢 

3. instead of having `backgroundColor` option, we should have `imageStyle` option to style `gatsby-resp-image-image` class when the css transition completes the blur-up effect. This would be very similar to the `wrapperStyle` option, except it will style `gatsby-resp-image-image` class instead of the `gatsby-resp-image-wrapper` class. This would be the best solution in my opinion because it allows us full control over how the <img class="gatsby-resp-image-image" /> element is styled once the blur-up css transition is complete:


ideally, i want to change [this](https://github.com/gatsbyjs/gatsby/blob/2c00dc28c0c4e73634c4a071f8a932d0c3b4de52/packages/gatsby-remark-images/src/gatsby-browser.js#L31):

```js
imageElement.style.color = "inherit";
imageElement.style.boxShadow = "inset 0px 0px 0px 400px " + options.backgroundColor;
```

to something like

```js
if (options.imageStyle) {
  imageElement.style = options.imageStyle;
} else {
  imageElement.style.color = "inherit";
  if (options.boxShadowColor) {
    imageElement.style.boxShadow = `inset 0px 0px 0px 400px ${options.boxShadowColor}`;
  }
}
```

I'm going to start a PR. Let me know what you think about my idea. Like it? Hate it?

**Comment by kimbaudi** [comment]
@freiksenet - The flag would be to detect alpha layer on `.png` images and only disable the blurry `background-image` for those images with transparent edges. If the flag was to disable the blurry `background-image` on all images, that would just be creating a flag to disable blur-up effect using this plugin. I think that is still a useful feature (i.e., create `blurUp` flag to enable blur-up effect. default is `true`). However, this is a different feature (i.e. create `disableBlurOnAlpha` flag to disable blur-up if image contains alpha-transparency)

So that is my current thought about this functionality.

Also, I learned something new about `backgroundColor` option so I will probably first work on updating the README, docs and adding more tests before I work on this (`disableBlurOnAlpha`) or the other (`blurUp` enabled by default).

**Comment by kimbaudi** [comment]
@freiksenet - Ok, I will create a new flag to disable blurry bg image for images with alphatransparency. I am most likely only going to check the outer edges for transparency (instead of checking the entire image). This will make this a O(w + h) operation rather than a O(wh) operation. And in the future, set this on by default later on maybe.
