### ISSUE TITLE
Fix path rewrite for first load on some routes

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#16533]
We added tests in https://github.com/gatsbyjs/gatsby/pull/16218 to assert that the url in the address bar and path for the route are identical after navigation and first load for various types of routes. 

When adding these tests, it became apparent that behaviour is inconsistent (only for build) for 
- index route
- static sibling route

Those two have been skipped for now. Fix is unclear at the moment.

**Comment by pieh** [comment]
This is `serve-static` doing 301 redirect when navigating to a "directory" without trailing slash. See:
 - https://github.com/expressjs/serve-static/blob/87f3b37ddd1d8199e9b24c264626d177ccca367f/test/test.js#L306-L310
