### ISSUE TITLE
Problem with Remark (ValidationError) when adding [gatsby-source-contentful]

### ISSUE THREAD

**Issue by primaveraentalca** [gatsbyjs/gatsby#1653]
Hi guys, I'm using
- gatsby 1.0.11 and
- node v6.11.0 on windows 10.

I've just setup a blog with markdown support following [this tutorial](https://www.gatsbyjs.org/blog/2017-07-19-creating-a-blog-with-gatsby/) and everything works, but now I need to grab some data from Contentful for another section of the site, and when I add it to gatsby-config.js, it compiles, but I get the following ValidationError, and pages from markdown aren't created.
```
The upserted page didn't pass validation
ValidationError: child "path" fails because ["path" must be a string]
{ path: null,
  component: 'D:\\CODE\\plazatubo-gatsby\\src\\templates\\post.js',
  context: {},
  componentChunkName: 'page-component---src-templates-post-js',
  jsonName: 'index.json',
  internalComponentName: 'ComponentIndex' }

Plugin default-site-plugin returned an error:

Error: Actions must be plain objects. Use custom middleware for async actions.
    at dispatch (D:\CODE\plazatubo-gatsby\node_modules\redux\lib\createStore.js:165:13)
    at D:\CODE\plazatubo-gatsby\node_modules\redux\lib\bindActionCreators.js:7:12
    at doubleBoundActionCreators.(anonymous function) (D:\CODE\plazatubo-gatsby\node_modules\gatsby\dist\utils\api-runner-node.js:51:37)
    at result.data.allMarkdownRemark.edges.forEach (D:\CODE\plazatubo-gatsby\gatsby-node.js:34:11)
    at Array.forEach (native)
    at graphql.then.result (D:\CODE\plazatubo-gatsby\gatsby-node.js:33:10)
    at tryCatcher (D:\CODE\plazatubo-gatsby\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\CODE\plazatubo-gatsby\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\CODE\plazatubo-gatsby\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\CODE\plazatubo-gatsby\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\CODE\plazatubo-gatsby\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\CODE\plazatubo-gatsby\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\CODE\plazatubo-gatsby\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\CODE\plazatubo-gatsby\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\CODE\plazatubo-gatsby\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\CODE\plazatubo-gatsby\node_modules\bluebird\js\release\promise.js:614:10)
success createPages — 0.063 s
success createPagesStatefully — 0.036 s
success extract queries from components — 0.128 s
success run graphql queries — 0.053 s
success write out page data — 0.006 s
success update schema — 0.179 s

bootstrap finished, time since started: 5.661 s



 DONE  Compiled successfully in 4271ms
```
My gatsby-config.js looks like this: 
```
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
  },
  plugins: [
    {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: `blabla`,
        accessToken: `blablablabla`,
      },
    },
    `gatsby-plugin-catch-links`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages/blog`,
        name: 'pages',
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [] // just in case those previously mentioned remark plugins sound cool :)
      }
    }
  ],
}
```

And my gatsby-node.js just has the code for managing markdown files:
```
const path = require('path');

exports.createPages = ({ boundActionCreators, graphql }) => {
  const { createPage } = boundActionCreators;

  const blogPostTemplate = path.resolve(`src/templates/post.js`);

  return graphql(`{
    allMarkdownRemark(
      sort: { order: DESC, fields: [frontmatter___date] }
      limit: 1000
    ) {
      edges {
        node {
          excerpt(pruneLength: 250)
          html
          id
          frontmatter {
            date
            path
            title
          }
        }
      }
    }
  }`)
    .then(result => {
      if (result.errors) {
        return Promise.reject(result.errors);
      }

      result.data.allMarkdownRemark.edges
        .forEach(({ node }) => {
          createPage({
            path: node.frontmatter.path,
            component: blogPostTemplate,
            context: {} // additional data can be passed via context
          });
        });
    });
}
```
Looking at  [ http://localhost:8000/___graphql](http://localhost:8000/___graphql) I can see it grabs the data from Contentful, but the pages for the markdown posts aren't being created due to the ValidationError that appears when adding 'gatsby-source-contentful' to the config.

Any help would be much appreciated

**Comment by thundernixon** [comment]
Sorry, but I'm now running into the same error. Were you able to solve it, @primaveraentalca? If so, did you find the issue?

**Comment by thundernixon** [comment]
Update: in case anyone else finds this issue via Google, I managed to fix my issue, though I'm still not sure _exactly_ what was causing it.

By simply removing the post folder, I discovered that the issue was in a new blog post I had created, and was something with the frontmatter or text in that post. I found that it was an issue with the index.md text by copy/pasting in text from a post that _was_ working (plus editing the path URL and title slightly, to avoid conflict. 

The post that was causing problems is one I had mostly written in Dropbox paper, then downloaded as a markdown file. I _think_ that possibly, it was fixed by making sure that preformatted code blocks were wrapped in ``` to prevent gatsby from trying to interpret them as javascript (strangely, the export from Dropbox paper left out those backticks from code blocks). I also simply erased the path and title in frontmatter, though I don't think there were any improper characters in them.

After that, it started working. Hope this helps someone else!

**Comment by primaveraentalca** [comment]
@thundernixon, I didn't solved it,
I just decided to use contentful for all the data.

**Comment by jumpalottahigh** [comment]
I was running into the same issue, not using contentful. It appeared that a markdown file was breaking my entire build because it had a backslash (\) in one of the front matter fields like so:

```
ogDescription: "... cause you can\'t replace ..."
```

My advice is to double check carefully your markdown. Hope this helps :)
