### ISSUE TITLE
Periods in query strings seem to throw routing off

### ISSUE THREAD

**Issue by atrauzzi** [gatsbyjs/gatsby#1655]
```
http://localhost:8000/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MDEzMDkyOTksInN1YiI6IjU5N2MxODliMzhmZTE5OTlhOTEzMjRiZCJ9.-YmntW5pTTmyke555OsOLJgeaPRHFIWrsjObsmZzfwQ
```

If I even just strip out the value from token and put any other value in, it's fine.  As soon as I put a period `.` in there, it 404s.  Something about having periods in query string variables seems to be messing things up.

**Comment by alampros** [comment]
It looks like this happens only in development mode, and is **not** limited to the query parameters - it affects the last path component as well:
```
http://localhost:8000/12.0/100/40.0
                        ^        ^
                      Fine     Breaks
```

**Comment by moisesv** [comment]
I keep getting the same error with the periods. I have tracked the problem down to:

/gatsby/src/commands/develop.js
line 130 in gatsby/commonad/develop.js

`if (parsedPath.extname === `` || parsedPath.extname.startsWith(`.html`)) {`

anything coming after a period as an extension in "parsedPath.extname"

**Comment by KyleAMathews** [comment]
@moisesv would love a PR fixing this!

**Comment by alampros** [comment]
Did #2876 not fix this? Did you try it with gatsby@>1.9.108?

**Comment by moisesv** [comment]
Hi @alampros. I tried, did not fix it for me.

**Comment by alampros** [comment]
@moisesv - Does this still happen with gatsby@1.9.123?

**Comment by KyleAMathews** [comment]
This seems fixed. Open a new issue if that's not the case!
