### ISSUE TITLE
Sorting on union types with GraphQL

### ISSUE THREAD

**Issue by adamwade2384** [gatsbyjs/gatsby#16562]
## Summary
I am attempting to sort a list of blog posts by date. I'm using the GraphQL Contentful API with the gatsby-source-contentful plugin. After I run the following query I receive an error suggesting I cannot sort the blog_posts array. Is there an alternative syntax for unions? 

## Query

```
{
  allContentfulSection {
    edges {
      node {
        node_locale
        component {
          __typename
          ... on ContentfulComponentBlogListing {
            blog_posts(sort: {fields: date, order: DESC}) {
              date(formatString: "YYYY-MM-DD")
            }
          }
        }
      }
    }
  }
}
```

## Error

```
{
  "errors": [
    {
      "message": "Unknown argument \"sort\" on field \"blog_posts\" of type \"ContentfulComponentBlogListing\".",
      "locations": [
        {
          "line": 9,
          "column": 24
        }
      ],
      "stack": [
        "GraphQLError: Unknown argument \"sort\" on field \"blog_posts\" of type \"ContentfulComponentBlogListing\".",
        "    at Object.Argument (/Users/adamwade/Projects/visual-cv/visualcv_www/node_modules/graphql/validation/rules/KnownArgumentNames.js:58:29)",
        "    at Object.enter (/Users/adamwade/Projects/visual-cv/visualcv_www/node_modules/graphql/language/visitor.js:324:29)",
        "    at Object.enter (/Users/adamwade/Projects/visual-cv/visualcv_www/node_modules/graphql/language/visitor.js:375:25)",
        "    at visit (/Users/adamwade/Projects/visual-cv/visualcv_www/node_modules/graphql/language/visitor.js:242:26)",
        "    at validate (/Users/adamwade/Projects/visual-cv/visualcv_www/node_modules/graphql/validation/validate.js:54:22)",
        "    at /Users/adamwade/Projects/visual-cv/visualcv_www/node_modules/express-graphql/dist/index.js:154:52",
        "    at <anonymous>",
        "    at process._tickCallback (internal/process/next_tick.js:189:7)"
      ]
    }
  ]
}
```

**Comment by coreyward** [comment]
Gatsby doesn't add arguments to nested fields, unfortunately. You would need to use the top-most field `allContentfulBlogPost` (or whatever type `blog_posts` resolves to) in order to use the `sort` argument. 

Alternately, you can use the APIs exposed during the boot sequence (e.g. [createResolvers](https://www.gatsbyjs.org/docs/node-apis/#createResolvers)) to augment the schema to include `blogPosts` under `ContentfulComponentBlogListing` that already have the transformations applied, or that accept arguments (e.g. `sort`) and implement the desired behavior.

**Comment by adamwade2384** [comment]
Thank you @coreyward! You're right, this query does give me what I'm looking for but my components are already built and composed so that won't work for me. I'll look into using createResolvers.
