### ISSUE TITLE
Is there a way to cancel a build based on validation of a page query?

### ISSUE THREAD

**Issue by jsve** [gatsbyjs/gatsby#16567]
## Summary
I've tried to find the answer to this in the documentation and tried to find suitable methods in source code. Both without luck. Hope this is the correct place to post my question.

I have a main query in my gatsby-node.js and for the fetched pages i pass them to their respective templates. In some of the template.js files I fetch some additional data through a page query. 

For some of my page queries there might be inconsistencies in data, but the query still passes. Say i fetch two entities: 
```
entA { data: { partA: 0, partB: 1 } }
entB { data: null }
```
From my query I get both of these, complete with the data objects (null in the case of entB). Data should never be null, so there must have been a mistake when the data was put in.

My question is this: Can i some how validate this (preferably in the component.js) and throw an error, or somehow cause the gatsby build to fail?

**Comment by matowang** [comment]
You can try to do in the render () of the page component.
entB.data.test
Since data is null it will throw an error.

**Comment by jsve** [comment]
Thanks for your reply @matowang ! This works well for the `build` command. Is there an equally simple solution to catch this from `gatsby develop`?

**Comment by matowang** [comment]
Wait so do you want to do this in gatsby-node.js or the component render? To test at compile time just do it in gatsby-node.js
```node
exports.onCreateNode = ({ node, actions }) => {
    if (node.internal.type === "entB") {
        node.data.test;
}
```
This way the build will fail.

**Comment by poncianodiego** [comment]
Hey @jsve just wondering if you were able to make it fail also on `gatsby develop`?
