### ISSUE TITLE
ACF Gallery [gatsby-wordpress-source]

### ISSUE THREAD

**Issue by ibjorn** [gatsbyjs/gatsby#16569]
Hey peeps, I'm still new to Gatsby. Have been studying React and Gatsby for about 2 months now.

I think I bit off a bit more than I can chew though when I told a friend I'll use him and his Wordpress site as a guinea pig. 

He has galleries on only one category of his Wordpress posts. I followed the instructions for ACF, got the plugin, set up the gallery, blah blah.

Tearing my hair out though trying to get the gallery to play along. As I said, only a specific category has these galleries. 

So hear's my code in my BlogPost template where it should check for a gallery:

```
 {data.wordpressPost.acf.gallery_post && (
                      <div className={classes.section}>
                        <div className={classes.container}>
                          <GridContainer>
                            <GridItem
                              xs={12}
                              sm={12}
                              md={8}
                              className={classes.marginAuto}
                            >
                              <Card carousel>
                                <Carousel {...settings}>
                                  {data.wordpressPost.acf.gallery_post.gallery.map(
                                    localFile => (
                                      <div>
                                        <img
                                          src={
                                            localFile.childImageSharp.fluid.src
                                          }
                                          alt={localFile.name}
                                          className="slick-image"
                                        />
                                      </div>
                                    )
                                  )}
                                </Carousel>
                              </Card>
                            </GridItem>
                          </GridContainer>
                        </div>
                      </div>
                    )}

```
And here's my GraphQl query:

```
export const query = graphql`
  query($id: Int!) {
    wordpressPost(wordpress_id: { eq: $id }) {
      title
      content
      excerpt
      date(formatString: "MMMM DD, YYYY")
      author {
        name
      }
      featured_media {
        localFile {
          childImageSharp {
            sizes(maxWidth: 1920) {
              ...GatsbyImageSharpSizes
              src
            }
          }
        }
      }
      acf {
        gallery_post {
          gallery {
            localFile {
              childImageSharp {
                fluid(maxWidth: 800) {
                  ...GatsbyImageSharpFluid
                  src
                }
              }
            }
          }
        }
      }
    }
  }
`
```

I've tried various things by now and always end up with different errors. So with this code, the latest error is:

`TypeError: Cannot read property 'map' of undefined`

Any help would be much appreciated. I usually just bang it out until I eventually figure out the answer, but, Gatsby wins, I give up on this one. Also have other projects coming up and can't waste more time on this.

Please help! :`-/

**Comment by matowang** [comment]
I don't use wordpress but have you tried printing the object out?
```javascript
console.log(data.wordpressPost.acf.gallery_post);
```
My guess is that gallery_post is an array that contains objects with `gallery` as their property. If the `gallery_post` is an array you might have to map it 
```javascript
gallery_post.map(({gallery})=> 
    gallery.map(({localFile}) =>
        //code
    )
)
``` 
or do 
```javascript
gallery_post[0].gallery.map(({localFile}) =>
    //code
)
```
depending on what size the array is.

Should be a relatively easy bug to fix.

When you do fix it make sure to do 
```javascript
gallery.map(({localFile}) => (
))
```
instead of
```javascript
gallery.map(localFile => (
))
```
Unless gallery isn't an array...
I'm really not sure, just print out the object and check the types.

**Comment by ibjorn** [comment]
You my friend, are a genius! You were 100% spot on. Thank you so very much!

I need to still sharpen my skills here. This is where I still get confused: 
*"My guess is that gallery_post is an array that contains objects with gallery as their property".* 

The fact that gallery is a property of the objects, **IN** the array. Got it.

* also not really into WP, but clients ask for it by name :(

**Comment by manigopal** [comment]
@ibjorn 

can you POST your working Carousel with Wordpress ACF in Gatsby

**Comment by ibjorn** [comment]
@manigopal this takes me back! 

I never completed that project and dumped it along the way. It was my first attempt at React.
