### ISSUE TITLE
Error: Minified React error #130

### ISSUE THREAD

**Issue by jimfilippou** [gatsbyjs/gatsby#1656]
Details: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `t`

It's just an error but on development server it works!. On `gatsby develop` everything works perfectly but when i do `gatsby build` and drop files on github pages it raises this minified error. What is going on?

**Comment by alexbassy** [comment]
I'm also getting this error, and it's very difficult to debug :(

**Comment by jimfilippou** [comment]
Good call , in my case it was a npm package. When i rebuild my app it was working properly but i will follow your proptypes it seems better than mine
