### ISSUE TITLE
HTML works fine in local dev mode, messed up after build

### ISSUE THREAD

**Issue by JulienCorb** [gatsbyjs/gatsby#16576]
## Description

I have three Components : `ArticleList`, `Article` and `SeeAllButton`. As you can see below, `ArticleList` is the parent component and renders 3 `Article` + the `SeeAllButton` at the end. 

Notice that I have the following tree : 

src
||--components
||||||--Article
||||||||||--Article.css
||||||||||--Article.js
||||||--SeeAllButton
||||||||||--SeeAllButton.css
||||||||||--SeeAllButton.js
||||||--ArticleList.js        

And here is the code of each component : 
```
import React from 'react';
import SeeAllButton from './SeeAllButton/SeeAllButton';
import Article from './Article/Article';

const ArticlesList = props => (
  <div className="my-3">
    <h2 className="my-3 font-weight-bold">NOS ARTICLES</h2>
    {props.posts.map((p, i) => <Article post={p} key={i}/>)}
    <div className="d-flex justify-content-end">
      <SeeAllButton path="/all-articles" />
    </div>
  </div>
)

export default ArticlesList;
```

```
import React from 'react';
import { Link } from 'gatsby';
import './Article.css';

class Article extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      width: 0
    }
  }
  componentDidMount() {
    this.updateWindowWidth();
    window.addEventListener('resize', this.updateWindowWidth);
  }

  componentWillUnmount() {
    window.removeEventListener('resize', this.updateWindowWidth);
  }

  updateWindowWidth = () => {
    this.setState({ width: window.innerWidth });
  }

  render() {
    return (
      <Link
        to={this.props.post.node.slug}
        className="article-link"
        >
      <div className="row mb-5 my-sm-3 d-sm-flex flex-column flex-sm-row">
        <div className="col-sm-5 my-2 d-flex" style={this.state.width < 576 ? {flexBasis: "200px"} : {}}>
          <div
          style={{background: `linear-gradient(135deg, rgba(0,0,0,0.3), rgba(0,0,0,0.6)), url(${this.props.post.node.jetpack_featured_media_url})`,
          backgroundRepeat: 'noRepeat',
          backgroundPosition: 'center',
          backgroundSize: 'cover',
          flex: 1
          }}
          >
          </div>
        </div>
        <div className="col-sm-7 pl-sm-0">
          <div className="my-2 d-flex flex-column justify-content-between">
            <h5
              className="text-uppercase font-weight-bold"
              style={{display: "inline-block"}}
              dangerouslySetInnerHTML={{ __html: this.props.post.node.title}}
              />
            <span
                className="mb-0 excerpt-wrapper"
                dangerouslySetInnerHTML={{ __html: (this.state.width < 1026 ? this.props.post.node.excerpt.substring(0, 100).replace(/(<([^>]+)>)/ig,"") : this.props.post.node.excerpt.substring(0, 250 - this.props.post.node.title.length).replace(/(<([^>]+)>)/ig,"")) +  "..." + `<a href=${this.props.post.node.slug} class="font-weight-bold">Lire plus</a>`}}
                />
          </div>
        </div>
      </div>
    </Link>
    )
  }
}

export default Article;
```
```
import React from 'react';
import "./SeeAllButton.css";

const SeeAllButton = props => (
  <a href={props.path} className="see-all-button" aria-label="voir tout">VOIR TOUT</a>
)

export default SeeAllButton;

```

**So the problem is:** When working in dev mode on my local machine, everything works as expected. BUT after the build, in production, It is completely messed up: 

### Steps to reproduce

You can try to run the code of the three components above. If you want to see the production website, go to https://www.lavoixdesnicois.com

### Expected result

This is what I expect : (this is a screenshot of my local dev console)
<img width="579" alt="Captura de pantalla 2019-08-13 a las 15 29 16" src="https://user-images.githubusercontent.com/17184158/62945578-48e78580-bddf-11e9-8bed-6c5b66177ccb.png">

### Actual result

but this is what I get in producition: Notice that the `SeeAllButton` is actually mixed with the sibling `Article` component above (parent div, href, etc.) but it shouldn't be that way ! 

<img width="677" alt="Captura de pantalla 2019-08-13 a las 15 29 36" src="https://user-images.githubusercontent.com/17184158/62945552-3e2cf080-bddf-11e9-9391-47b67338ce3f.png">

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - /usr/local/opt/node@8/bin/node
    Yarn: 1.3.2 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.9.0 => 2.9.0
    gatsby-cli: ^2.6.5 => 2.6.5
    gatsby-image: ^2.0.20 => 2.0.25
    gatsby-plugin-manifest: ^2.0.9 => 2.0.12
    gatsby-plugin-offline: ^2.0.16 => 2.0.20
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.5
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-source-filesystem: ^2.0.39 => 2.0.39
    gatsby-source-graphql: ^2.0.19 => 2.0.19
    gatsby-source-wordpress: ^3.0.65 => 3.0.65
    gatsby-transformer-sharp: ^2.1.8 => 2.1.9
  npmGlobalPackages:
    gatsby-cli: 2.4.8

**Comment by wardpeet** [comment]
I don't think this is an issue with Gatsby. I believe it has something to do with `key={i}`. You shouldn't use index as a key unless you know what you're doing. More info can be found at https://reactjs.org/docs/lists-and-keys.html.

I'm not seeing this issue:
![image](https://user-images.githubusercontent.com/1120926/63582489-754a9100-c599-11e9-80e8-2f63051c9fd7.png)

Thanks so much for opening this issue! As stated, this is slightly tangential to Gatsby, and it seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪

**Comment by JulienCorb** [comment]
Hi @wardpeet, thank you very much for your help. 

I replaced the key with the WordPress ID of the article, instead of using the index. But it does not work. 

I believe it is a Gatsby issue : in this part of my code : 

```
<Link
        to={this.props.post.node.slug}
        className="article-link"
        >
      <div className="row mb-5 my-sm-3 d-sm-flex flex-column flex-sm-row">
        <div className="col-sm-5 my-2 d-flex" style={this.state.width < 576 ? {flexBasis: "200px"} : {}}>
          <div
          style={{background: `linear-gradient(135deg, rgba(0,0,0,0.3), rgba(0,0,0,0.6)), url(${this.props.post.node.jetpack_featured_media_url})`,
          backgroundRepeat: 'noRepeat',
          backgroundPosition: 'center',
          backgroundSize: 'cover',
          flex: 1
          }}
          >
          </div>
        </div>
        <div className="col-sm-7 pl-sm-0">
          <div className="my-2 d-flex flex-column justify-content-between">
            <h5
              className="text-uppercase font-weight-bold"
              style={{display: "inline-block"}}
              dangerouslySetInnerHTML={{ __html: this.props.post.node.title}}
              />
            <span
                className="mb-0 excerpt-wrapper"
                dangerouslySetInnerHTML={{ __html: (this.state.width < 1026 ? this.props.post.node.excerpt.substring(0, 100).replace(/(<([^>]+)>)/ig,"") : this.props.post.node.excerpt.substring(0, 250 - this.props.post.node.title.length).replace(/(<([^>]+)>)/ig,"")) +  "..." + `<a href=${this.props.post.node.slug} class="font-weight-bold">Lire plus</a>`}}
                />
          </div>
        </div>
      </div>
    </Link>
```

If I remove the `Link` component, everything works fine.  Actually, everything was working fine before, until I wrapped my article in a `Link` component. 

So there might be a problem with `Link` maybe ? Or maybe I'm using it wrong ?

**Comment by wardpeet** [comment]
The problem lies in your Article component. You're defining `<a href=${this.props.post.node.slug} class="font-weight-bold">Lire plus</a>`. The link Component will render an "A tag" to mimic a proper hyperlink. The problem you're seeing is that you can't nest A tags inside each outer.

> The a element may be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g. buttons or other links). This example shows how this can be used to make an entire advertising block into a link: https://www.w3.org/TR/html50/text-level-semantics.html#the-a-element

So you should remove the read more link or wrap the link component around the image and title

**Comment by JulienCorb** [comment]
that was the issue indeed. Thank you !
