### ISSUE TITLE
Encoding Relationships between nodes

### ISSUE THREAD

**Issue by benmccormick** [gatsbyjs/gatsby#1658]
I have a situation I have been trying to figure out the idiomatic Gatsby 1 way to handle.

On my blog I have a set of recommended posts that are associated with each post.  I set what those posts should be as a string of comma separated keys in the YAML frontmatter of each post, and add a key value to each post.  In Gatsby 0.x, this was sufficient because I had the whole site available to me, and when I was rendering the page, I would just filter the list of the sites pages on the recommended post keys.

With my initial port to Gatsby 1 I kept this behavior and just queried the attributes I needed for every page alongside the full data for the current post, but it means every page includes (limited) data for every page in the app.

I want to fix this by instead putting the related post on the markdown node directly in pre-processing, but I haven't been able to figure out which lifecycle api I need to do this with.
I tried onCreateNode, but this is called for every individual node as it goes.  Since this is about a relationship between nodes, I'd need to do this very inefficiently and on each onCreateNode, look at all existing nodes and check whether it is a relatedPost of that node or vice versa, and add them to the list.  It turns out that even beyond the innefficiency, this doesn't work, because while I can use `getNodes` to read the previously created Nodes, `createNodeField` fails on those nodes (presumably they're already "locked")

My other option is to find a lifecycle api that occurs after all the markdown nodes have been created but before the graphql schema has been tossed together where I can access and edit all the nodes (in which case I could do a more efficient version where I mapped nodes to their keys and then did a single loop through the nodes to add the related posts by key).  But that doesn't seem to exist right now.

I've fallen back (based on a suggestion on Reactiflux) to passing the related posts through pathContext.  But this isn't very flexible, and feels like a hack on top of the graphQl layer.  On Reactiflux @KyleAMathews asked me to open up an issue to discuss. So any suggestions for how this can be better?

**Comment by Alxandr** [comment]
I've done (more or less) the same using `setFieldsOnGraphQLNodeType`. On my blog I have "series" (sample: https://alxandr.me/2016/09/21/xando-pt-3-json/). The list you see of posts is autogenerated, and included in the query as such:

```gql
node {
  series {
    name
    path
  }
}
```

Though depending on how you link between the posts it might not be as easy (I create Series nodes in my graph that I resolve). You might want to create a plugin that creates a extra node for each of your blog posts just to store the relationships (more or less like what I've done). Then I store a field named `series` for the blog post itself which holds the node id, which I look up in the resolve function to get the id of all the posts in the series. Then it's just a matter of looking them up and returning the requested data.

**Comment by benmccormick** [comment]
> You might want to create a plugin that creates a extra node for each of your blog posts just to store the relationships 

So you're suggesting a plugin that iterates over the markdown files a second time and instead of building a Remark node, creates a second node that maps keys?  Does GraphQL have a join concept that would let me join those?

**Comment by Alxandr** [comment]
No iteration actually. I do this in onNodeCreated. Also, GraphQL is a graph, not tables. It can also be cyclic, so "join" is easy. The "issue" is that you need to "store" the data that you want to query somehow. Secondly, a "node type" is in Gatsby "owned" by a single plugin, so only that plugin can modify nodes of that kind. This is the reason I don't use the markdownremark nodes at all myself, I create BlogPost, Tag and Series nodes that I control and can update as more tags/posts are discovered.

**Comment by Alxandr** [comment]
@benmccormick I've just published, so you can see how I do it here: https://github.com/Alxandr/alxandr.me/blob/master/plugins/%40alxandr/gatsby-transformer-blog-post/create-post.js#L159

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
