### ISSUE TITLE
Adding Firebase for app section of site... worried about bundle size

### ISSUE THREAD

**Issue by danboyle8637** [gatsbyjs/gatsby#16587]
I am getting ready to hook up by backend I created with Firebase functions to the app part of my site. 

Currently, I created the app part in my current Gatsby site per the instructions in the docs. 

But I have been reading lately how big the bundle sizes get when you add in Firebase. So I started to think about making the app part of my site it's own app separate from my marketing Gatsby site. 

This way I can mange sizes better. I don't want my marketing site to have this huge bundle size and be really slow as hopefully my app will grow. 

This is of course assuming that my bundle size will be huge. I hope it won't but, it does seem adding in Firebase does make things get bigger quicker.

Any thoughts on this?

**Comment by universse** [comment]
From my understanding Gatsby performs code-splitting out of the box. So, it's unlikely that firebase will be included in your marketing bundle. One way to check is to use https://github.com/webpack-contrib/webpack-bundle-analyzer
