### ISSUE TITLE
Document structured logging and write check for PRs to prevent new unstructured errors from being added

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#16591]
We added support recently for structured errors.

But we haven't yet documented how to do this.

Because of the lack of documentation & awareness of structured errors — new PRs are adding new unstructured errors which will just have to be converted in the future to be structured.

So we should write a docs page + a check (with peril perhaps?) to check for unstructured errors in the PR (regex for reporter.error("")?) and block the PR from being merged.

**Comment by m-allanson** [comment]
Some related issues / PRs for this: 

- This is the PR that added structured errors: https://github.com/gatsbyjs/gatsby/pull/14904
- Here's an example of converting an existing error to a structured error: https://github.com/gatsbyjs/gatsby/pull/15244
- Here's an umbrella issue for error message improvements: https://github.com/gatsbyjs/gatsby/issues/15019

**Comment by marcysutton** [comment]
Seems like this issue is covering two goals: documentation and writing a check for PRs. Should we update it to focus on one thing (the PR check perhaps)? Looks like the docs stuff is covered pretty well in #15019
