### ISSUE TITLE
Add a "kitchen sink" starter

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#166]
It'll serve to introduce / document in a visual/tangible way all documentation & loader options.

Also it'll be a nice integration test.

**Comment by Bartekus** [comment]
Thank you Kyle for inviting me to be part of the Gatsby team!
I'm at the moment swamped with few pressing issue but as I resolve them I'll be increase my focus and contributions to the Gatsby project!

**Comment by KyleAMathews** [comment]
:100:

**Comment by KyleAMathews** [comment]
Actually working on making this part of the default starter as that's what most people will install first so it should show off many of the capabilities of Gatsby.

**Comment by KyleAMathews** [comment]
This is fixed with https://github.com/gatsbyjs/gatsby-starter-default/pull/7
