### ISSUE TITLE
gatsby-pluggin-offline NOT Working

### ISSUE THREAD

**Issue by aikodeio** [gatsbyjs/gatsby#16618]
## Description

Hi. I have installed the gatsby-plugin-offline plugin.
I put it offline and the site does not load.
Here a case in production to visualize:

https://encuesta-gptw.web.app/

In Firefox: working.
**In Chrome: ERROR**
```
The FetchEvent for "https://encuesta-gptw.web.app/" resulted in a network error response: the promise was rejected.
Promise.then (async)
(anonymous) @ workbox-routing.prod.js:1
**sw.js:1 Uncaught (in promise) TypeError: Failed to fetch**
```

### Steps to reproduce

- Enter https://encuesta-gptw.web.app/
- Activate offline mode
- Refresh page
- View site.

### Expected result

The site should show the home page while I am offline.

### Actual result

The site does not load any pages or content.

### Environment

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.13.62 => 2.13.62
    gatsby-image: ^2.2.8 => 2.2.8
    gatsby-plugin-manifest: ^2.2.5 => 2.2.5
    gatsby-plugin-nprogress: ^2.1.2 => 2.1.2
    gatsby-plugin-offline: ^2.2.6 => 2.2.6
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sharp: ^2.2.11 => 2.2.11
    gatsby-source-filesystem: ^2.1.9 => 2.1.9
    gatsby-transformer-sharp: ^2.2.6 => 2.2.6

**Comment by aikodeio** [comment]
// File gatsby-config.js

module.exports = {
    siteMetadata: {
        version: `2.0.0`,
    },
    plugins: [
        `gatsby-plugin-react-helmet`,
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `images`,
                path: `${__dirname}/src/images`,
            },
        },
        `gatsby-transformer-sharp`,
        `gatsby-plugin-sharp`,
        {
            resolve: `gatsby-plugin-nprogress`,
            options: {
                color: `#e60000`,
                showSpinner: false,
            },
        },
        {
            resolve: `gatsby-plugin-manifest`,
            options: {
                name: `Encuesta`,
                short_name: `Encuesta`,
                start_url: `/`,
                background_color: `#e60000`,
                theme_color: `#e60000`,
                display: `standalone`,
                icon: `src/images/gptw-logo-large.png`,
            },
        },
        `gatsby-plugin-offline`,    
    ],
}

**Comment by sndrs** [comment]
i have this problem too

here's a minimal reproduction of the issue with just the `gatsby-plugin-offline` plugin in use: https://github.com/sndrs/gatsby-offline-test

**Comment by aikodeio** [comment]
There isn't even an answer from the team :(
I saw your repository, knowing that it works with the gatsby-plugin-offline@^2.2.9 version is ideal for me right now.

Thank you.

**Comment by sndrs** [comment]
Does it work for you? 2.2.9 fails for me?

**Comment by aikodeio** [comment]
I will close it since there was no answer or solution ...
