### ISSUE TITLE
API reference pages not indexed in site search

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#16634]
One user on Discord noted that they found it hard to find docs for `createRedirect`, upon investigation realized that the search on the site doesn't pick up any of the API's from the [references page](https://www.gatsbyjs.org/docs/actions/). This seems to be because Algolia picks up elements with the `docSearch` class applied, this happens automatically for a lot of content on the site that's built from `.md` files, but pages like the reference page linked to above don't explicitly add that class.

One of two options could be done to resolve this:
- change https://github.com/algolia/docsearch-configs/blob/master/configs/gatsbyjs.json which defines how content is indexed on the site
- adjust the template files to match the classes defined in that `gatsby.json` file on algolia's repo so that they _do_ get indexed and can be searched for

**Comment by n8finch** [comment]
@gillkyle could I grab this one? If it's still up for grabs?

**Comment by gillkyle** [comment]
Hey @n8finch sorry to get back to you so late, I see you self-assigned the issue and you are welcome to jump in and try and figure things out!

**Comment by fk** [comment]
👍 Maybe we should add a bit of documentation (CSS class, point to the Algolia docsearch config) to `www/README.md`? (or the component that handles docsearch, although that might be too deep in the code)

**Comment by n8finch** [comment]
@fk and @gillkyle I can definitely add this to the README.md, do you want anything other than a new section that says:

1. When you're adding something that needs to be indexed, make sure you add the `docSearch-content` class to the section.
2. This is probably using the `<Layout>` or `<Container>` component to wrap the searchable content.

Anything else?

**Comment by fk** [comment]
Hey Nate! Thanks you so much! 🤗 🙏 

> Anything else?

A reference to Gatsby's docsearch configuration at https://github.com/algolia/docsearch-configs/blob/master/configs/gatsbyjs.json would be 💯
