### ISSUE TITLE
 Static folder asset paths are invalid for nested pages

### ISSUE THREAD

**Issue by seanemmer** [gatsbyjs/gatsby#16636]
## Description

Static folder asset paths are invalid for nested pages

### Steps to reproduce

1. Place an asset in your Static folder
2. Create a nested page (i.e. src/pages/nest/page1.js)
3. Load the nested page in your browser.

### Expected result

The static asset path should be at root of your project

### Actual result

The static asset is in the "/nest" folder

### Environment

  System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.2.0 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.1
    Safari: 12.0.1
  npmGlobalPackages:
    gatsby: 2.13.63

**Comment by pieh** [comment]
I'm not quite sure what do you mean here? Do you mean file placed in `/static` ends up in `/public/nest/`?

**Comment by seanemmer** [comment]
Apologies - I am attempting to use html.js and the static folder to host a third party js library.  Here is some more detail:

I placed the following file in my (root) Static folder: 

`libs/jquery/dist/jquery.min.js`

I then added the following <script> tag to the body of html.js in my /src folder:

`<script src={'libs/jquery/dist/jquery.min.js'} />`

The script loads properly for non-nested pages, but for pages that are nested html.js appears to be looking for the file in the nested directory for the script instead of the root.  It's unclear if this is the intended behavior, and if so, what the solution is (React Helmet?).

**Comment by jonniebigodes** [comment]
@seanemmer from my knowledge of gatsby it will look up assets relative to the folder so if you "point it" that way it ill look for the path relative to that folder namely '/nested/libs/jquery/dist/jquery.min.js'. In your case you'll have to make adjustments probably something like #10713 or go with helmet option or install the jquery package and modify the build in `gatsby-node.js` with the following code:
```javascript
const webpack= require('webpack');
exports.onCreateWebpackConfig = ({
    stage,
    rules,
    loaders,
    plugins,
    actions,
  }) => {
    actions.setWebpackConfig({
      plugins: [
        new webpack.ProvidePlugin({
          $: 'jquery',
          jQuery: 'jquery',
          'window.jQuery': 'jquery'
        }),
      ],
    })
  }
```
It's entirely up to your case and how you want to proceed.

**Comment by seanemmer** [comment]
@jonniebigodes thanks for the guidance.  jQuery is one of multiple third party js files I am installing as part of a Bootstrap Theme and so webpack/js imports are not an option.

I understand that in general asset path references are made relative to the page folder, but this is unusual in that the the asset reference does not originate in the page, but rather in html.js.  

This behavior seems undesirable in that any html.js asset path references are rendered invalid for nested pages.

Helmet is definitely an alternative, but I wonder whether I'll run into the same issue where asset paths referencing the Static folder get prepended with the pages subdirectory and invalidated.

**Comment by seanemmer** [comment]
This is my error - should have been:

<script src={'/libs/jquery/dist/jquery.min.js'} />
