### ISSUE TITLE
Returning a <Redirect /> within render() leads to a broken page

### ISSUE THREAD

**Issue by rjray** [gatsbyjs/gatsby#16631]
## Description

Using @reach/router, if I send a redirect from within a page's `render()`, the target page loads but then crashes. If I go directly to the target page, it loads fine.

The code is currently on GitHub, so I can show it. This is the [current color.js file](https://github.com/modelpaintmixer/mpm-frontend/blob/master/src/pages/color.js). The use of <Redirect /> is on line 59. If the URL does not include an `id` parameter, then it sets the state value `redirect` to true. When that is true, `render()` sends a redirect to `/colors`.

For reference, [here is an earlier version of color.js](https://github.com/modelpaintmixer/mpm-frontend/blob/7e54defc1af714c118d953802c9327b496f45445/src/pages/color.js). In this earlier version, I was passing the ID to the page as path info (i.e., `/color/1` instead of `/color/?id=1`). However, this didn't work in production and I had to switch to query parameters instead. In this version of the component, I am using the router in lines 11-14. I am able to route requests with an ID to the main component (line 12) and redirect requests that are missing the ID (line 13).

I would try the full-on router approach, but I'm not clear on how I can get the path to be sensitive to query parameters.

### Steps to reproduce

To see this without the stack-trace, go to [this link](https://modelpaintmixer.com/color/?id=5), then edit the URL to remove the `?id=5`. When the /color page has no ID in the query params, it tries to redirect to [/colors](https://modelpaintmixer.com/colors/). But when arriving there from the redirect, the page fails. If you then just go directly to /colors, it will work.

### Expected result

A link [like this](https://modelpaintmixer.com/color) should successfully redirect to [here](https://modelpaintmixer.com/colors).

### Actual result

Page is empty, and under `gatsby develop` I have stack frames (none of which refer to any of my code, unfortunately).

### Environment

  System:
    OS: Linux 3.13 Ubuntu 14.04.6 LTS, Trusty Tahr
    CPU: (12) x64 Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
    Shell: 4.3.11 - /bin/bash
  Binaries:
    Node: 12.6.0 - /home/linuxbrew/.linuxbrew/bin/node
    npm: 6.9.0 - /home/linuxbrew/.linuxbrew/bin/npm
  Languages:
    Python: 2.7.6 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 66.0.3
  npmPackages:
    gatsby: ^2.13.42 => 2.13.42
    gatsby-cli: ^2.7.21 => 2.7.21
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-mdx: ^1.0.18 => 1.0.18
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-optimize-svgs: ^1.0.3 => 1.0.3
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-plugin-typography: ^2.3.2 => 2.3.2
    gatsby-remark-images: ^3.1.10 => 3.1.10
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5

**Comment by TheAadithyan** [comment]
if you are using react-router-dom wrap your component export in withRouter provided by react-router-dom .

and all component usage should be returned from render. then only react knows what to render.

import React from 'react'
import { withRouter, Redirect } from 'react-router-dom';

class App extends React.Component {

render() {
if (this.state.toLogin && !this.state.mounted) {
  return (
    <React.Fragment>
      <Route exact path="/Login" component={Login} /> 
      <Route exact strict path="/" render={({location}) => {
          if (location.pathname === window.location.pathname) {
              return <Redirect to="/Login"/>;
          }
          return null;
      }} />
  </React.Fragment>
  );
}

return (
  <div className="App">
    <ReactCSSTransitionGroup
        transitionName="remove"
        transitionEnterTimeout={100}
        transitionLeaveTimeout={100}>
            {child}
    </ReactCSSTransitionGroup>
</div>
)}

}
export default withRouter(App)

**Comment by rjray** [comment]
Is this to say that it can't be done with @reach/router? Since Gatsby is already using that as a dependency, I would prefer to use it over introducing a new dep.
