### ISSUE TITLE
[jss] server render outputs invalid css

### ISSUE THREAD

**Issue by Alxandr** [gatsbyjs/gatsby#1664]
So I just tried the jss plugin, but it doesn't work if you have any HTML entities in any of your selectors. For instance, if you have `.foo > .bar` in your css it will print as `.foo &gt; .bar`. The `<style>` element needs to be rendered using inner html.

**Comment by KyleAMathews** [comment]
Could you create a PR with the fix?

**Comment by Alxandr** [comment]
Sorry, I have an exam in 2 weeks + a full time job at the moment, and I'm trying to create my new blog while figuring out gatsby. I don't think I should be committing to any OSS at the moment (especially if it includes figuring out how to build and test things).

What I can do though is paste you the JSS plugin I wrote (that also does css cleaning):

```js
const React = require('react');
const { renderToString } = require('react-dom/server');
const { JssProvider, SheetsRegistry } = require('react-jss');
const CleanCSS = require('clean-css');

const cssCleaner = new CleanCSS({});

exports.replaceRenderer = ({
  bodyComponent,
  replaceBodyHTMLString,
  setHeadComponents,
}) => {
  const sheets = new SheetsRegistry();

  const bodyHTML = renderToString(
    <JssProvider registry={sheets}>
      {bodyComponent}
    </JssProvider>,
  );

  replaceBodyHTMLString(bodyHTML);
  const css = sheets.toString();
  const minCss = cssCleaner.minify(css).styles;
  setHeadComponents([
    <style
      type="text/css"
      id="server-side-jss"
      key="server-side-jss"
      dangerouslySetInnerHTML={{ __html: minCss }}
    />,
  ]);
};

```

The changes needed to fix this should be as simple as doing dangerouslySetInnerHTML, but as said, there is always more involved when doing PRs for a new project (like figuring out build and testing etc.). If you want to use the code go ahead, else I can look at it in a couple of weeks :)

**Comment by KyleAMathews** [comment]
@wizardzloy you want to look into this?

**Comment by KyleAMathews** [comment]
@Alxandr also when you have more time, would love to help you get up to speed helping out! We have a contributing guide at https://www.gatsbyjs.org/docs/how-to-contribute/#contributing

**Comment by wizardzloy** [comment]
@KyleAMathews I'll take a look at this, @Alxandr provided the code for the fix, so should be a straightforward thing.
