### ISSUE TITLE
How to run GraphQL not in component

### ISSUE THREAD

**Issue by nikita-seliverstov** [gatsbyjs/gatsby#16647]
Hi,

I need to pass source data  using graphQl to to simple object config when i try to use it i get an error
`The GraphQL query in the non-page component "C:/Users/NikitaSeliverstov/Desktop/amblik/src/cms/cms.js" will not be run.`
How can i run query in non component?

**Comment by lannonbr** [comment]
You can use either the [StaticQuery](https://www.gatsbyjs.org/docs/static-query/) component or [useStaticQuery](https://www.gatsbyjs.org/docs/use-static-query/) React hook.

**Comment by nikita-seliverstov** [comment]
I think did't describe my question well sorry. I need to pass data to a non component object

**Comment by lannonbr** [comment]
That's currently impossible. Only places to run graphql queries is in a component or createPages in a gatsby-node api.

**Comment by nikita-seliverstov** [comment]
Sad to hear, I will make feature request if it's not already created

**Comment by peterwiebe** [comment]
@lannonbr does this include `html.js`? I am trying to query an image in there and it doesn't seem to let me.
