### ISSUE TITLE
importing JSON file into a page adds it in all pages

### ISSUE THREAD

**Issue by tareefdev** [gatsbyjs/gatsby#16651]
## Description

Importing JSON file into a page directly (`import things from '../things'`) adds the imported file to all pages 

### Steps to reproduce

Here is a [repo](https://github.com/tareefdev/gatsby-json) to reproduce:

- Add a JSON file to the default starter and import it directly without using GraphQL
- Build the project and check pages size

### Expected result

- Just one page (where the file was imported) should increase in the size.

### Actual result

- All pages now increased in size from 1 MB to 5.7 MB

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (2) x64 Intel Xeon Processor (Skylake, IBRS)
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  npmPackages:
    gatsby: ^2.13.64 => 2.13.64
    gatsby-image: ^2.2.8 => 2.2.8
    gatsby-plugin-feed: ^2.3.6 => 2.3.6
    gatsby-plugin-google-analytics: ^2.1.7 => 2.1.7
    gatsby-plugin-manifest: ^2.2.5 => 2.2.5
    gatsby-plugin-offline: ^2.2.6 => 2.2.6
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sharp: ^2.2.11 => 2.2.11
    gatsby-plugin-typography: ^2.3.2 => 2.3.2
    gatsby-remark-copy-linked-files: ^2.1.6 => 2.1.6
    gatsby-remark-images: ^3.1.11 => 3.1.11
    gatsby-remark-prismjs: ^3.3.5 => 3.3.5
    gatsby-remark-responsive-iframe: ^2.2.4 => 2.2.4
    gatsby-remark-smartypants: ^2.1.2 => 2.1.2
    gatsby-source-filesystem: ^2.1.9 => 2.1.9
    gatsby-transformer-remark: ^2.6.14 => 2.6.14
    gatsby-transformer-sharp: ^2.2.6 => 2.2.6
  npmGlobalPackages:
    gatsby-cli: 2.7.30

**Comment by jonniebigodes** [comment]
@tareefdev i've cloned your code and it looks like what is happening here is the json file is being imported to a component that will be used as a template for dynamically generated pages.

When gatsby goes over the build process and generates the pages in `gatsby-node.js` based on the result of the graphql query, the template component has that import, it will import the json content for all the pages increasing the size of each one. 

Depending on your case and how you want to handle the json content,  you might have to make some adjustments to your code.

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by tareefdev** [comment]
Great! I tried to import the JSON file into a page rather than a template, and now just that page loaded the JSON file not all of them. 

I test another case and found that the same issue happened there:
- Using `gatsby-plugin-mdx` instead of raw markdown.
- Creating a component which imports the JSON file.
- Importing that component into one page, not inside a template.
- Now all pages have the file and their sizes increased too.

I updated the repo to reproduce this issue, although I'm not sure if this related to MDX itself or gatsby's plugin.

**Comment by jonniebigodes** [comment]
@tareefdev i've pulled in the changes and installed the new dependencies. Ran `yarn develop` and waited for the build process to complete. Opened up up `http://localhost:8000/sizes` the data is shown correctly. As it should. 

- I've checked the other pages and no "polution" from the json was present. 

- Checked the filesizes on the pages and they are all consistent.

- Took it even a step further and issued `gatsby clean` to purge `.cache` and `public` folders.
Issued `gatsby build` to generate the production build checked the filesystem and opened a browser window to `http://localhost:9000` and checked all the pages to see if there's a reference to the json in the other pages and no reference to it and the filesizes are consistent.

- Went back to development mode and opened up the graphql explorer and issued the query you have:
```graphql
{
        allMdx(
          sort: { fields: [frontmatter___date], order: DESC }
          limit: 1000
        ) {
          edges {
            node {
              body
              fields {
                slug
              }
              frontmatter {
                title
              }
            }
          }
        }
      }
```
Checked the results and checked for references to the json component that imports the json content and only the first item namely this:
```json
"edges": [
       {
          "node": {
            "body": "function _extends() { _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }\n\nfunction _objectWithoutProperties(source, excluded) { if (source == null) return {}; var target = _objectWithoutPropertiesLoose(source, excluded); var key, i; if (Object.getOwnPropertySymbols) { var sourceSymbolKeys = Object.getOwnPropertySymbols(source); for (i = 0; i < sourceSymbolKeys.length; i++) { key = sourceSymbolKeys[i]; if (excluded.indexOf(key) >= 0) continue; if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue; target[key] = source[key]; } } return target; }\n\nfunction _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }\n\n/* @jsx mdx */\nvar _frontmatter = {};\n\nvar makeShortcode = function makeShortcode(name) {\n  return function MDXDefaultShortcode(props) {\n    console.warn(\"Component \" + name + \" was not imported, exported, or provided by MDXProvider as global scope\");\n    return mdx(\"div\", props);\n  };\n};\n\nvar layoutProps = {\n  _frontmatter: _frontmatter\n};\nvar MDXLayout = \"wrapper\";\nreturn function MDXContent(_ref) {\n  var components = _ref.components,\n      props = _objectWithoutProperties(_ref, [\"components\"]);\n\n  return mdx(MDXLayout, _extends({}, layoutProps, props, {\n    components: components,\n    mdxType: \"MDXLayout\"\n  }), mdx(\"p\", null, \"This is another test\"), mdx(Json, {\n    mdxType: \"Json\"\n  }));\n}\n;\nMDXContent.isMDXComponent = true;",
            "fields": {
              "slug": "/size/"
            },
            "frontmatter": {
              "title": ""
            }
          }
        },
]
```
In your case what could be happening is some items that were cached in your first iteration were never cleaned properly.
Issue `gatsby clean` and issue `gatsby develop` or `gatsby build` and see if the problem persists.

**Comment by tareefdev** [comment]
Thanks for your detailed answer, I tried `gatsby clean && gatsby build` but the issue still present.

- After building, I went to `/public` and found the size of the app bundle file is 5.3 MB (its name in my case `app-0b34f63c3e8cd7ab6e7a.js`).

- I even pulled in the repo on a server, installed the packages, and deployed it. Then I checked it with Chrome developer tools which confirmed that the JSON file exists in homepage (and other posts):
![Screenshot_20190817_100553](https://user-images.githubusercontent.com/17391433/63208089-da554100-c0d8-11e9-8412-0e9dfc047624.png)

- I checked the size of several pages using Browser Calories add-on, and it gave me the same size 5.8 MB for all pages:
![Screenshot_20190817_100617](https://user-images.githubusercontent.com/17391433/63208091-db866e00-c0d8-11e9-85b1-2c6c1d6172b2.png)

- The GraphQL query on homepage itself doesn't return the JSON file, but when building, something makes the file lakes to all other pages.

**Comment by jonniebigodes** [comment]
@tareefdev one thing i forgot to mention is that you're importing a json file directly into a page component. With that, when webpack sees that you have the file import it will copy over the file, significantly increasing the bundle size, let's not forget that you have a json file of roughly 5.4 mb being loaded. It will not be split chunked or anything like that. it will be copied and attached to the build directly as is using the appropriate loader from webpack. 

What i assume you're seeing is that the app-123123213(random number) being that big and having all the data is that the file in question is the "master" bundle file with all the assets/data, but each page is split and chunked into different js files. This is a very loose interpretation, but i assume that's a fairly accurate one of how gatsby interprets and builds the assets /data for the site.

In your case client side loading would be impossible, as awaiting to load 5.4 mb is not a good user experience. And also from what i saw you have another file that is almost 10mb in size. I don't know what your use case is for the file, but i would probably take a different approach, i would load and aggregate the data from the json file inside `gatsby-node`, and pass it down already with all the in it's final stage, ready to be presented in a template or templates, once again depending on the use case. 

Or even i would take into consideration [gatsby-transfomer-json](https://www.gatsbyjs.org/packages/gatsby-transformer-json/) to handle the json and see if it could at least reduce the bundle size.

**Comment by tareefdev** [comment]
So to summarize it, the master bundle will contain all assets/data were imported within components and pages, and that's would increase the size of all pages, exactly as the title says, but this the default behavior and not a bug.

It seems that it's not possible to use GraphQL in some cases, for example [TopoJSON files](https://en.wikipedia.org/wiki/GeoJSON#TopoJSON) can't be queried using GraphQL.

In my real project, I used `gatsby-node` to generate a page for each JSON object, that works perfectly, but I need to add searching in that file. Our previous approach was to serve this file via an API; I thought maybe with Gatsby it's better to import it directly inside a page and then surprised that the file included in the main bundle!

**Comment by universse** [comment]
You can consider using something like fetch api to request that json file instead of directly import it.

**Comment by jonniebigodes** [comment]
@universse no need. If the file is copied over to the static folder it will be treated like a asset and it should be acessible via a http request.

@tareefdev following what i've said above as you need search capabilities you could go with the above approach and move the json files into the static folder and when the site is built the bundle should be trimmed down in size. More on [static folder and gatsby](https://www.gatsbyjs.org/docs/static-folder/). 
With that in mind you can load the json in `gatsby-node` and generate a page for each corresponding item like you said.
Regarding the search aspect, you could do something like the following:

 Create a new page called `search.js` with the following code:

```javascript
import React, { Component } from "react"
import axios from "axios"
class Search extends Component {
  state = {
    incidents: {},
    isError: false,
    isLoading: true,
  }

  async componentDidMount() {
    try {
      const incidentsRequest = await axios(
        process.env.NODE_ENV !== "production"
          ? "./oldIncidents.json"
          : "../oldIncidents.json"
      ) // the conditional is to prevent 404 in production
      const { data } = incidentsRequest
      this.setState({ incidents: data, isLoading: false })
    } catch (err) {
      console.log(`error loading incidents`)
      this.setState({ isLoading: false, isError: true })
    }
  }

  render() {
    const { isError, isLoading } = this.state
    if (isError) {
      return <div>something went wrong while fetching the data</div>
    }
    if (isLoading) {
      return <div>fetching your data please hold on a second</div>
    }

    return <div>data will be displayed here</div>
  }
}

export default Search
```

And you could probably take a look at [this](https://www.gatsbyjs.org/docs/adding-search-with-js-search/) and apply it to your case.

**Comment by universse** [comment]
It depends on where the data comes from. If they come from data queried with graphql, then you need to fs.writeFile. If it's static then just put it in static folder.

**Comment by tareefdev** [comment]
@jonniebigodes Thanks for your exhaustive answer. Fetching JSON file using `axios` instead of importing it directly solves the issue, now just one page has the data. This is an excellent technic for importing Topojson files and building a searching page using JSON file.

I'm considering to open a PR to add this use case in `[When to use the static folder](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/static-folder.md#when-to-use-the-static-folder)` section here, if this could make senes.

Thanks again. I'm going to close this issue as the problem solved.

**Comment by jonniebigodes** [comment]
@tareefdev no need to thank, glad i was able to help out. If you're willing feel free to make the addition to the document go for it, just read up the [how to contribute](https://www.gatsbyjs.org/contributing/how-to-contribute/) document and go from there.

**Comment by Amilight** [comment]
Hi @tareefdev @jonniebigodes .

I have come across a similar issue, in my case we had to implement localization. We needed to import JSON files inside of this i18n instance ( as it needs resources.)
Problem is, it's get added to app-xxx.js to all pages and it bumps up bundle size by 6*x.

Here is a sample code for this i18n instance -

`import i18next from "i18next";
import { initReactI18next } from "react-i18next";

import backend from "i18next-http-backend";
import detector from "i18next-browser-languagedetector";
import en from "../../../static/locales/en/PrivacyMainContentWidget.json";
import asa from "../../../static/locales/as/PrivacyMainContentWidget.json";
import bn from "../../../static/locales/bn/PrivacyMainContentWidget.json";
import te from "../../../static/locales/te/PrivacyMainContentWidget.json";
import ta from "../../../static/locales/ta/PrivacyMainContentWidget.json";
import ml from "../../../static/locales/ml/PrivacyMainContentWidget.json";
import or from "../../../static/locales/or/PrivacyMainContentWidget.json";
import gu from "../../../static/locales/gu/PrivacyMainContentWidget.json";
import hi from "../../../static/locales/hi/PrivacyMainContentWidget.json";
import kn from "../../../static/locales/kn/PrivacyMainContentWidget.json";
import mr from "../../../static/locales/mr/PrivacyMainContentWidget.json";

const resources = {
    en: { PrivacyMainContentWidget: { ...en } },
    bn: { PrivacyMainContentWidget: { ...bn } },
    te: { PrivacyMainContentWidget: { ...te } },
    ta: { PrivacyMainContentWidget: { ...ta } },
    ml: { PrivacyMainContentWidget: { ...ml } },
    or: { PrivacyMainContentWidget: { ...or } },
    gu: { PrivacyMainContentWidget: { ...gu } },
    hi: { PrivacyMainContentWidget: { ...hi } },
    kn: { PrivacyMainContentWidget: { ...kn } },
    mr: { PrivacyMainContentWidget: { ...mr } },
    as: { PrivacyMainContentWidget: { ...asa } },
};

i18next

    .use(backend)

    .use(detector)

    .use(initReactI18next)

    .init({
        ns: ["translations", "PrivacyMainContentWidget"],
        defaultNS: "translations",
        detection: {
            lookupQuerystring: "locale",
        },
        lng: "en",
        fallbackLng: "en",
        debug: false,
        interpolation: {
            escapeValue: false,
        },
        react: {
            useSuspense: false,
        },
        resources,
    });

export default i18next;
`

Any help would be great! Thanks!
