### ISSUE TITLE
GraphQL request's in non component

### ISSUE THREAD

**Issue by nikita-seliverstov** [gatsbyjs/gatsby#16653]
## Summary

The possibility to query data from GraphQL not in component

### Motivation
I run into problem where i wanted to manually initialize cms object with data about created pages to make possible to add list with values of existing pages to make it easy for clients to add links inside site or edit site menu. I think it might be more use cases than mine and it will add more flexibility in using gatsby

**Comment by matowang** [comment]
There's no reason why you cannot do that with queried data inside a component. Something like this:
```javascript
const menu = ({data}) => {
    <ul>
    {data.cmsData.menu.map(({menubtn}) => 
        <li key={menubtn.text}><Link to={menubtn.link}>{navmenu.text}</a></li>
    )}
    </ul>
}
```
Just map your cms data to the way you want it to show up on a component.
You can also query data in createPages
https://www.gatsbyjs.org/docs/creating-and-modifying-pages/

Creating a fully customizable website through a cms really shouldn't be a problem.

**Comment by nikita-seliverstov** [comment]
I don't want query cms data to the component i want to query data about created pages to cms config which is not a component.

**Comment by universse** [comment]
Maybe you can use fs.writeFile to write out the object in gatsby-node during page creation process. Then import that file in your src code.

**Comment by nikita-seliverstov** [comment]
That might work, I will try but it will be much better if i just can query this data

**Comment by devrchancay** [comment]
Can you give a more precious example of what you will need? I also think it would be fixed in the gatsby-node.js file

**Comment by nikita-seliverstov** [comment]
I want to query   ```
allSitePage {
          nodes {
            path
          }
        }
```
To get this data and pass it to cms config so i can have something like list of created pages. As far i understand if i query in gatsby-node the node's aren't created yet. I tried to query inside gatsby-node and I get only /dev-404-page/

**Comment by universse** [comment]
how do you intend to pass the data to cms config? it would be helpful if you share some code.

**Comment by nikita-seliverstov** [comment]
First i tried to use gatsby static queries 
I tried different implementations but basically it looks something like this
> export default () => {
>   const data = useStaticQuery(graphql`
>      query menuQuery {
>       allSitePage {
>     nodes {
>       path
>     }
>     }
>     }
>     `)
> return (
>    CMS.init({
>     config: {
>     load_config_file: true,
>     collections: [
>      { label: "articleAAA", name: "articleaaaa", folder: "src/content/menu", create: true, fields: [
>      { label: "menu", name: "menu", folder: "src/content/menu", create: true, fields: [
>      { label: "slug", name: "slug", widget: "string"},
>      { label: "language code", name: "lang", widget: "string"},
>      { label: "Text", name: "text", widget: "string"},
>      { label: data.allSitePage.nodes[0].path, name: "test", widget: "string"},
>     ]},
>     ],
The problem with gatsby queries that they can work only in component. Then I tried your solution but how I understand the nodes aren't created yet during gatsby-node run. I think to try to use apollo to make query

**Comment by universse** [comment]
any reason why you can't do this in ```componentDidMount``` or ```useEffect```?

**Comment by universse** [comment]
alternatively, you can use ```onPostBuild``` in ```gatsby-node.js``` to make the above query

**Comment by nikita-seliverstov** [comment]
I tried and it did't but maybe because of lack of knowledge i probably something wrong

> export default () => {
>     const data = useStaticQuery(graphql`
>        query menuQuery {
>         allSitePage {
>       nodes {
>         path
>       }
>       }
>       }
>       `)
>       useEffect(() => {
>         CMS.init({
>             config: {
>             load_config_file: true,
>             collections: [
>              
>              { label: "menu", name: "menu", folder: "src/content/menu", create: true, fields: [
>              { label: "slug", name: "slug", widget: "string"},
>              { label: "language code", name: "lang", widget: "string"},
>              { label: "Text", name: "text", widget: "string"},
>              { label: "test", name: "test", widget: "string"},
>             ]},
>             ],
>           },
>       })
>       })
>   return (data)
> }

**Comment by universse** [comment]
You need to use useStaticQuery and useEffect in a React component.

Let say App.js
```javascript
export default function App () {
  const data = useStaticQuery(graphql`
    query {
      allSitePage {
        nodes {
          path
        }
      }
    }
  `)
  
  useEffect(() => {
    CMS.init({
      config: {
        load_config_file: true,
        collections: [
          {
            label: 'menu',
            name: 'menu',
            folder: 'src/content/menu',
            create: true,
            fields: [
              { label: 'slug', name: 'slug', widget: 'string' },
              { label: 'language code', name: 'lang', widget: 'string' },
              { label: 'Text', name: 'text', widget: 'string' },
              { label: 'test', name: 'test', widget: 'string' }
            ]
          }
        ]
      }
    })
  }, [data])

  return <SomeComponent />
}
```

**Comment by nikita-seliverstov** [comment]
Sorry i can't understand how to properly execute this, I tried to just copy this and tried to call this function inside a component and it wont work

**Comment by wardpeet** [comment]
@nikita-seliverstov is it possible to share a small snippet with your problem. It's hard to figure out what exactly the problem is. We also have something called page-context which might be of help here.

**Comment by universse** [comment]
> 
> 
> Sorry i can't understand how to properly execute this, I tried to just copy this and tried to call this function inside another component in layout.js and it wont work

If that's the case then you can do it like this

layout.js
```javascript
function Layout() {
  const data = useStaticQuery(graphql`
    query {
      allSitePage {
        nodes {
          path
        }
      }
    }
  `)

  useEffect(() => {
    CMS.init({
      config: {
        load_config_file: true,
        collections: [
          {
            label: 'menu',
            name: 'menu',
            folder: 'src/content/menu',
            create: true,
            fields: [
              { label: 'slug', name: 'slug', widget: 'string' },
              { label: 'language code', name: 'lang', widget: 'string' },
              { label: 'Text', name: 'text', widget: 'string' },
              {
                label: data.allSitePage.nodes[0].path,
                name: 'test',
                widget: 'string'
              }
            ]
          }
        ]
      }
    })
  }, [data])

  return <YourComponents />
}
```

**Comment by nikita-seliverstov** [comment]
> @nikita-seliverstov is it possible to share a small snippet with your problem. It's hard to figure out what exactly the problem is. We also have something called page-context which might be of help here.

https://github.com/Arvutiamblik/amblik here is the repo i use for tech demos,
At first i wanted to init the cms in src/cms/cms.js but i don't know which component to return it this file so i tried in layout.js in src/components

**Comment by universse** [comment]
is it working the way you intended, initializing in layout.js?

**Comment by nikita-seliverstov** [comment]
I try right now and it seems to be working but now i have the cms page under every page on the site like this 
![image](https://user-images.githubusercontent.com/37171096/63273680-12aa7a00-c2a7-11e9-88e9-93b90c06d511.png)

**Comment by universse** [comment]
are you wrapping every page with ```Layout``` component?
you only need to do that for pages that you want to display the cms in

**Comment by nikita-seliverstov** [comment]
The problem is that i don't have component that displays cms pages I don't know how to add this component to the page

**Comment by universse** [comment]
Sorry this is application code which I'm not familiar with. So can't really help.

**Comment by wardpeet** [comment]
I'm not completely understanding the issue. Maybe it's helpful to post a smaller code snippet of what you're trying to do. [CodeSandbox](https://codesandbox.io) is a great place to do this.

**Comment by nikita-seliverstov** [comment]
> I'm not completely understanding the issue. Maybe it's helpful to post a smaller code snippet of what you're trying to do. [CodeSandbox](https://codesandbox.io) is a great place to do this.

I made a snippet of how i wanted to make it at first [](https://codesandbox.io/s/xenodochial-johnson-sjfyq?fontsize=14)

The issue is that when site builds I want manualy initialize netlify cms with data about created nodes which I want to loop and create list of option based on created pages
