### ISSUE TITLE
CSS output in build mode is essentially empty

### ISSUE THREAD

**Issue by Chalarangelo** [gatsbyjs/gatsby#16650]
## Description

I am running `gatsby build` and the output does not contain all of my CSS (compiled from Sass). 

At first, I thought it was an issue with `gatsby-plugin-sass`, however, that is not the case, as it does not load plain CSS files either.

Meanwhile, `gatsby develop` produces the correct result (which could indicate this is an SSR issue).

I have a very similar project, with a similar configuration, that actually works as expected. Can someone point out why and what I can do to fix it?

### Steps to reproduce

1. Clone [30-seconds-of-code](https://github.com/30-seconds/30-seconds-of-code).
2. Switch to `from-starter` branch.
3. Run `npm i`.
4. Run `npm run webber` or `gatsby build`.
5. See the output without any CSS.

--- 

* Additionally, you can check this [netlify build](https://suspicious-jepsen-e866cc.netlify.com/) to see what the output is. 
* A project with the same structure can be found [here](https://github.com/30-seconds/30-seconds-starter) and its build, found [here](https://30-seconds-starter.netlify.com/), produces the correct result.

### Expected result

The built CSS file should contain all of my compiled CSS.

### Actual result

I am building a Gatsby website with `gatsby build` and the CSS output only contains this:

```css
.tl-edges{max-width:100%;overflow-x:hidden}.tl-wrapper{width:100%;float:left;position:relative}.tl-wrapper+.tl-wrapper{margin-left:-100%;margin-right:0}
```

### Environment

System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.16.2 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 68.0.1
  npmPackages:
    gatsby: ^2.12.0 => 2.13.61
    gatsby-image: ^2.2.6 => 2.2.8
    gatsby-plugin-google-analytics: ^2.1.6 => 2.1.7
    gatsby-plugin-manifest: ^2.2.3 => 2.2.5
    gatsby-plugin-netlify: ^2.1.3 => 2.1.4
    gatsby-plugin-offline: ^2.2.4 => 2.2.5
    gatsby-plugin-page-creator: ^2.1.5 => 2.1.5
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.3
    gatsby-plugin-sass: ^2.1.3 => 2.1.8
    gatsby-plugin-sharp: ^2.2.7 => 2.2.11
    gatsby-plugin-transition-link: ^1.12.4 => 1.12.4
    gatsby-remark-copy-linked-files: ^2.1.3 => 2.1.5
    gatsby-remark-images: ^3.1.6 => 3.1.10
    gatsby-remark-prismjs: ^3.3.3 => 3.3.5
    gatsby-source-filesystem: ^2.1.5 => 2.1.9
    gatsby-transformer-json: ^2.2.2 => 2.2.2
    gatsby-transformer-remark: ^2.6.6 => 2.6.13
    gatsby-transformer-sharp: ^2.2.3 => 2.2.6

*Note that I am getting the same result on Netlify. Haven't tested on Mac or Windows, though. It might work properly on either one or both.*

**Comment by universse** [comment]
Heh did you check your built html files? Think below a certain threshold css is embedded in the <style> tags in the htmls.

**Comment by universse** [comment]
Does your style work as expected tho? Cuz I think below a certain size threshold, css is embedded directly in style tags in html files.

**Comment by Chalarangelo** [comment]
If this information helps, if I copy the essential content files in the `30-seconds-starter` project (which works anyways), the CSS seems to be output properly, so it seems like a filesystem issue on Linux (as mentioned in other similar issues, on Linux you might run in trouble due to improper casing in names) or an issue with some of my code (minor differences between projects) or some naming problem etc. I am looking into it right now, any help would be appreciated.

**Comment by Chalarangelo** [comment]
Turns out, updating my code from this
```js
import '../styles/index.scss';
```

to this:

```js
require('../styles/index.scss');
```
seems to have made it work for now.

I do not understand why or how, but it's working at least.

If someone has an explanation for this, I'd love to hear it.

**Comment by Chalarangelo** [comment]
I would still like to know the root cause of this and how to resolve it permanently.

**Comment by LekoArts** [comment]
There wasn't any other activity here anymore and the dependencies we use to load such styles were bumped to their next majors, so it's possible that this is already resolved (and it might also be a local issue on Linux). Thus I'll close this one.
