### ISSUE TITLE
gatsby-plugin-netlify-cms incorrectly exposes a hook to registerPreviewStyle

### ISSUE THREAD

**Issue by DavidChouinard** [gatsbyjs/gatsby#16671]
## Description

The [README for gatsby-plugin-netlify-cms](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify-cms#readme) states that any imported styles "will automatically be applied to the editor preview pane, there is no need to use `registerPreviewStyle` for imported styles." This does not appear to be the case.

### Steps to reproduce

1. Set a `modulePath` for gatsby-plugin-netlify-cms
```
    {
      resolve: `gatsby-plugin-netlify-cms`,
      options: {
        modulePath: `${__dirname}/src/cms/cms.js`,
      },
    },
```
2. Import a css file in that path
```
import CMS from "netlify-cms-app"
...
import style from "../styles/cms.css"
```
3. Observe the CSS file is applied to the entire Netlify CMS UI, not the preview pane

### Expected result

When importing a CSS file, that file should be used to style the preview pane using the underlying Netlify CMS function `registerPreviewStyle`. For example, when importing a CSS file with `h2 { color: red }`, H2s should be styled red in the preview pane like so:

<img width="920" alt="Screen Shot 2019-08-15 at 5 25 02 PM" src="https://user-images.githubusercontent.com/388552/63135277-0ca05a80-bf82-11e9-94b3-8bb000fc35db.png">

### Actual result

Importing a stylesheet overwrites the styling for the entire Netlify CMS app, not just the preview pane — _all_ H2s are now red everywhere in the UI.

<img width="716" alt="Screen Shot 2019-08-15 at 5 28 59 PM" src="https://user-images.githubusercontent.com/388552/63135329-4f623280-bf82-11e9-8598-0a3a3bbb932b.png">

Notably, when manually importing a string with `registerPreviewStyle`, everything works as expected:

```
CMS.registerPreviewStyle("h2 { color: red; }", { raw: true });
```

The [README for gatsby-plugin-netlify-cms](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify-cms#readme) states that importing a style "will automatically be applied to the editor preview pane, there is no need to use `registerPreviewStyle` for imported styles." 

It appears that the connection between importing and `registerPreviewStyle` isn't working correctly: `gatsby-plugin-netlify-cms` seems to be importing a style that's applied to the entire application rather than piping it to `registerPreviewStyle`.

**Comment by DavidChouinard** [comment]
this might have a common root cause with #15126 @erquhart

**Comment by erquhart** [comment]
It's actually a duplicate of that ticket - try running a build (rather than local development server) and see if the issue still occurs. If it doesn't, it's the same issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DavidChouinard** [comment]
Got it, it does look like this issue doesn't occur with `gatsby build`. Seems like a duplicate, closing.
