### ISSUE TITLE
weird issue with React state update on unmounted component (in GatsbyReporter?)

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#16688]
## Description

install and setup `gatsby-theme-dev-blog@0.0.9` on a new site. `gatsby-develop` and get this:

```
success open and validate gatsby-configs - 0.094 s
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your app lication. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method. in GatsbyReporter

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

no idea what causes it, `DEBUG=* gatsby develop` shows nothing of note. why does a warning cause error with exit code 1? 

### Steps to reproduce

no repro yet

### Expected result

it should run

### Actual result

got that weird error

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0.4
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.50 => 2.13.50 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4 
    gatsby-theme: ^0.0.6 => 0.0.6 
    gatsby-theme-dev-blog: ^0.0.9 => 0.0.9 
  npmGlobalPackages:
    gatsby-theme-workspace: 1.0.0
    gatsby-theme: 0.0.6

```

**Comment by sw-yx** [comment]
updating from `2.13.50` to `2.13.66` fixed it. super weird. clsoing for now.

**Comment by siddharthkp** [comment]
Hey @sw-yx! You got the wrong Sid 😛 

You want @sidharthachatterjee instead of me. (unsubscribing from this thread, byeeeee)

**Comment by jayliu50** [comment]
After a recent update, I'm seeing the issue


  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.10.0/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 66.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.15.20 => 2.15.20
  npmGlobalPackages:
    gatsby-cli: 2.7.44

**Comment by mdunbavan** [comment]
I can 100% confirm this still happens and needs investigating. Please see below:

```
System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 69.0
    Safari: 12.0.2
  npmPackages:
    gatsby: 2.15.13 => 2.15.13
    gatsby-cli: ^2.7.49 => 2.7.49
    gatsby-image: ^2.0.20 => 2.2.20
    gatsby-plugin-algolia: ^0.2.0 => 0.2.0
    gatsby-plugin-fullstory: ^2.0.5 => 2.1.8
    gatsby-plugin-layout: ^1.0.3 => 1.1.8
    gatsby-plugin-manifest: ^2.0.13 => 2.2.18
    gatsby-plugin-postcss: ^2.0.1 => 2.1.8
    gatsby-plugin-react-helmet: ^3.0.2 => 3.1.8
    gatsby-plugin-react-svg: latest => 2.1.2
    gatsby-plugin-robots-txt: ^1.3.0 => 1.5.0
    gatsby-plugin-sharp: ^2.0.13 => 2.2.25
    gatsby-plugin-sitemap: ^2.0.3 => 2.2.14
    gatsby-source-filesystem: ^2.0.9 => 2.1.26
    gatsby-transformer-sharp: ^2.1.8 => 2.2.16
  npmGlobalPackages:
    gatsby-cli: 2.4.8

gatsby develop

success open and validate gatsby-configs - 0.054 s
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmo
unt method.
    in GatsbyReporter
```

Can anyone give me an update please

**Comment by pieh** [comment]
@DZuz14 Can you share reproduction?

**Comment by DZuz14** [comment]
Yup. I can probably do that. Will get back to you on that.

**Comment by willeswa** [comment]
I just had this issue when running Gatsby in development mode for the same code that is running in production just fine. `npm update` seems to have fixed the problem. Since gatsby and a bunch of other packages were updated too, I can't tell which specific package may have been causing the problem. Gatsby was updated to 2.17.8 from 2.17.7

**Comment by willeswa** [comment]
> I just had this issue when running Gatsby in development mode for the same code that is running in production just fine. `npm update` seems to have fixed the problem. Since gatsby and a bunch of other packages were updated too, I can't tell which specific package may have been causing the problem. Gatsby was updated to 2.17.8 from 2.17.7

This is an update to the quoted comment. I ran into the issue again and tried to look into it further. The problem apparently (on Linux) stems from the limit set on inotify and can be solved by setting a permanent limit on the number of directories that can be tracked by inotify. 

The limit can be set by:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

Technical details on inotify are [here](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details):
