### ISSUE TITLE
Client-only doubts

### ISSUE THREAD

**Issue by leomotta121** [gatsbyjs/gatsby#16692]
Hey there, I am trying to learn and understand Gatsby.

I found that with Gatsby I can make client-only routes with @reach/router, I just need to tell the path with gatsby-node.js with the following code: 

```js
 // gatsby-node.js

exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions;

  // page.matchPath is a special key that's used for matching pages
  // only on the client.
  if (page.path.match(/^\/app/)) {
    page.matchPath = `/app/*`;

    // Update the page.
    createPage(page);
  }
};
```

With that, we use @reach/router instead of react-router-dom.

```jsx
// pages/app.js

import React from "react"
import { Router } from "@reach/router"
import Layout from "../components/Layout"
import Details from "../components/Details"
import Home from "../components/Home"
import Login from "../components/Login"
import PrivateRoute from "../components/PrivateRoute"
import Status from "../components/Status"

const App = () => (
 <Layout>
  <Status />
  <Router>
    <PrivateRoute path="/app/profile" component={Home} />
    <PrivateRoute path="/app/details" component={Details} />
    <Login path="/app/login" />
  </Router>
 </Layout>
)

export default
```
My doubt is if I can think of this route as a SPA or Gatsby tries to make pages from those routes? 

With CRA it takes a root `<div class="root"></div>` element to render all pages. With the example I gave, could I think of the `/app/*` route the same way I used to work with CRA?

It is like mixing static pages with some specific page like `/app/*` using dynamic SPA concept, did I get it right?

[here](https://github.com/gatsbyjs/gatsby/tree/master/examples/simple-auth) is a sample project using client-only.

@edit: It is because the project I am looking to migrate to Gatsby I was using nginx to service more than one app, I had a plain html landing page in the root route '/' and a CRA app in the dashboard '/dashboard'. Basically running more than one project with the same domain with nginx. It looks like I could do it with Gatsby out of the box.

**Comment by wardpeet** [comment]
What you say is correct when using dynamic routing it will be **roughly** the same as CRA. Gatsby will still make a static page of your /app route which in your example will be.

```
<Layout>
	<Status />
    <Router>
        // this is empty because nothing matches with /app, you can put in a default path here if you like.
    </Router>
</Layout>
```

**Comment by leomotta121** [comment]
@wardpeet Thank you!
