### ISSUE TITLE
RSS feed support in gatsby-theme-blog-core

### ISSUE THREAD

**Issue by ChristopherBiscardi** [gatsbyjs/gatsby#16694]
## Summary

RSS feed "by default" could be added to `gatsby-theme-blog-core`, which would enable any child theme to automatically have it.

### Basic example

User does nothing, has RSS feed when using gatsby-theme-blog, gatsby-theme-blog-core, or gatsby-theme-blog-core child themes.

### Motivation

Many people still use RSS feed readers to consume content, especially other developer's content. It would be nice if people didn't have to think about this when

## Unanswered Questions

* What does it look like to change the default feed if we include the gatsby-plugin-feed?
* Is there a strong reason to omit the RSS feed from -core? I personally don't think so.
* If someone adds a new source node that implements the `BlogPost` interface, how do we ensure the RSS feed picks it up? Do we add an `rssContent` field requirement to the BlogPost interface? Do we use `html`?
* [Not critical to this PR]: How would we add to support for "subset" RSS feeds like for tags.

cc/ @amberleyromo [who brought this up originally](https://github.com/gatsbyjs/gatsby/issues/16106#issuecomment-515269057).

**Comment by trevordmiller** [comment]
This would be wonderful!

**Comment by trevordmiller** [comment]
I gave this a try in https://github.com/gatsbyjs/gatsby-starter-blog-theme/issues/6. Would love to see this added by default without manual config needed.
