### ISSUE TITLE
MarkdownIt Plugin

### ISSUE THREAD

**Issue by cutemachine** [gatsbyjs/gatsby#167]
Gatsby uses MardownIt. Is there an easy way to configure it to use the [footnote plugin](https://github.com/markdown-it/markdown-it-footnote)?

**Comment by KyleAMathews** [comment]
You should copy the [supplied example Markdown loader](https://github.com/gatsbyjs/gatsby/blob/master/lib/loaders/markdown-loader/index.js) to within your site folder at `loaders/markdown-loader/index.js` and add the footnote plugin there.

I don't want Gatsby to have a large API surface area so providing a plugin for the default Markdown loader seems like a mistake. I think actually shipping any loaders at all with Gatsby is a mistake. I think for the next major release I'm going to move loaders out of core and into the starters to make it very clear that hacking the loaders in your project is the right way to modify the loader.

The larger issue here is what should Gatsby do and not do. I think Gatsby's role should be kept as minimal as possible to ensure maximum flexibility. What is the minimum thing Gatsby does? Map files to URLs, provide a default Webpack config, ensure a fantastic hot-reloading developer experience, and do production builds. Beyond that I think the project should encourage really good conventions through the default starters but people should be free to swap out loaders any which way they want.

**Comment by KyleAMathews** [comment]
@cutemachine issue to track moving Markdown loader out of core https://github.com/gatsbyjs/gatsby/issues/168

**Comment by KyleAMathews** [comment]
@cutemachine site-specific loaders are now supported properly as of 0.8.10 https://github.com/gatsbyjs/gatsby/pull/188

**Comment by cutemachine** [comment]
@KyleAMathews You are the man. Thanks.
