### ISSUE TITLE
gatsby-theme-notes-core

### ISSUE THREAD

**Issue by ChristopherBiscardi** [gatsbyjs/gatsby#16700]
## Summary

Like gatsby-theme-blog-core (PR: https://github.com/gatsbyjs/gatsby/pull/16166), but for the notes theme.

### Motivation

Abstracting the data structures like this allows us to source notes from anywhere on the internet as well as allow people to build compatible child themes and extensions based on the standardized Notes interface.

**Comment by johnletey** [comment]
@ChristopherBiscardi I could help with this

**Comment by laurieontech** [comment]
Now that we've gained experience on theme usage this seems like not the way to go. The existing notes theme is sufficient and we don't see adding a core layer as anything but additional complexity for shadowing.
