### ISSUE TITLE
Custom postcss.config.js isn't loaded by gatsby-plugin-postcss or gatsby-plugin-sass

### ISSUE THREAD

**Issue by StarpTech** [gatsbyjs/gatsby#16707]
## Description

I'm trying to use `postcss.config.js` file to configure postcss but the config isn't loaded at all.

- According to [Gatsby 2 migration](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#3-include-postcss-plugins-in-your-postcssconfigjs-file) the config file is supported 
- The plugin [gatsby-plugin-sass](https://www.gatsbyjs.org/packages/gatsby-plugin-sass/) also use postcss but it doesn't support the config file too.

### Steps to reproduce

- checkout any gatsby starterkit
- Install plugins
```
"gatsby": "^2.13.67"
"gatsby-plugin-sass": "^2.1.8"
"gatsby-plugin-postcss": "^2.1.3"
```
- Create `postcss.config.js` at root
```js
console.log('###############');

module.exports = {};
```
- File is not loaded (no log statement visible)

### Expected result

The config file should be used.

### Environment

```
"gatsby": "^2.13.67"
"gatsby-plugin-sass": "^2.1.8"
"gatsby-plugin-postcss": "^2.1.3"
```

```
  System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (12) x64 AMD Ryzen 5 2600X Six-Core Processor
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 11.14.0 - /tmp/yarn--1566058060211-0.37519524786455727/node
    Yarn: 1.17.3 - /tmp/yarn--1566058060211-0.37519524786455727/yarn
    npm: 6.7.0 - ~/n/bin/npm
  Languages:
    Python: 3.7.2 - /home/starptech/.pyenv/shims/python
  Browsers:
    Chrome: 76.0.3809.100
```

**Comment by christiansakai** [comment]
I can confirm, doesn't work for me either.

**Comment by LekoArts** [comment]
`gatsby-plugin-sass` also supports postcss plugins, have you tried that?
https://www.gatsbyjs.org/packages/gatsby-plugin-sass/#postcss-plugins

**Comment by StarpTech** [comment]
@LekoArts this is about the external `postcss.config.js` file. Using the option works.

**Comment by LekoArts** [comment]
Can you [provide a minimal reproduction][reproduction]?
If I understand you correctly the sass plugin wouldn't be needed?

[reproduction]: https://gatsby.dev/reproduction

**Comment by StarpTech** [comment]
> Can you provide a minimal reproduction?

No time for that yet but you can easil reproduce it with the steps above.

@LekoArts yes according the [docs](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#3-include-postcss-plugins-in-your-postcssconfigjs-file) the `postcss.config.js` is respected when using `gatsby-plugin-postcss`

**Comment by LekoArts** [comment]
> No time for that yet but you can easily reproduce it with the steps above.

Hey @StarpTech 	, I created this test repository https://github.com/LekoArts/postcss/commit/fbdb58f93a8002702c41465da06a8bc21ddc62b4 and it works without problems. Can you please share your reproduction of this problem?

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
