### ISSUE TITLE
Second build always fails

### ISSUE THREAD

**Issue by Alxandr** [gatsbyjs/gatsby#1671]
I'm not entirely sure what's causing this, but consistently, if I don't delete the `.cache` folder, my builds always fails with a query error `Cannot query field "allTag" on type "RootQueryType".`.

Deleting the `.cache` folder and building from "scratch" fixes the issue. Any suggesion on how I can go about figuring out what's causing this? I'm guessing the nodes aren't created but I don't know why they wouldn't be just because they are already cached.

**Comment by KyleAMathews** [comment]
This is weird... try poking around in `.cache/redux-state.json` and see if there is nodes of type `Tag`?

**Comment by KyleAMathews** [comment]
Also if you can create a reproducible example of this that'd be 💯 e.g. do any of the example sites exhibit this behavior?

**Comment by Alxandr** [comment]
I'll have a look. I also need to amend that it might not be the `.cache` folder, but the `public` folder. I'll do some investigating once I have time, but currently I'm just in the habit of starting using `rimraf .cace public && yarn start`.

**Comment by KyleAMathews** [comment]
Any updates on this? If you're still seeing this, I'd love to take a look at your source to debug what's happening.

**Comment by Alxandr** [comment]
Sorry. I had exam this monday, and two job interviews today :P, so this has been pushed back a bit. I'll try to check if this is still an issue later today or tomorow.

**Comment by Alxandr** [comment]
![image](https://user-images.githubusercontent.com/112334/29372864-a7df007e-82ac-11e7-965f-00eee6028f98.png)

**Comment by KyleAMathews** [comment]
Closing out older issues. Let us know if you still need help!
