### ISSUE TITLE
gatsby-cli new fails to complete on OpenBSD

### ISSUE THREAD

**Issue by leonstafford** [gatsbyjs/gatsby#16713]
## Description

Unable to complete the new project provisioning with `gatsby new projectname`.

### Steps to reproduce

 - install OpenBSD
 - `pkg_add node`
 - `npm i -g gatsby-cli`
 - `gatsby new projectname`

### Expected result

Provisioning of new app completes without error.

### Actual result

Receive output:

> ERR! cb() never called

With `NODE_DEBUG=*`:

![VirtualBox_openbsd65stable_18_08_2019_12_21_18](https://user-images.githubusercontent.com/2066833/63220020-0bf20900-c1ba-11e9-9421-30712c707c88.png)

![VirtualBox_openbsd65stable_18_08_2019_12_21_33](https://user-images.githubusercontent.com/2066833/63220031-1a402500-c1ba-11e9-8a03-e65c16173103.png)

### Environment

 - `gatsby info --clipboard`:

<img width="467" alt="Screen Shot 2019-08-18 at 1 09 13 PM" src="https://user-images.githubusercontent.com/2066833/63219986-69d22100-c1b9-11e9-99b9-c4cc194b2af5.png">

Tried on both OpenBSD 6.5 -stable, with latest patches and OpenBSD 6.6-beta -current (Generic#210 amd64) with same results.

**Comment by i-bsd** [comment]
Can also confirm.
Same result with all starters using OpenBSD.

**Comment by sidharthachatterjee** [comment]
We don't really _officially_ support OpenBSD. 

I'm not particularly sure what's going on but based on the error messages, it looks like this is an issue with `npm` itself?

This does appear to break somewhere in `execa` based on that stack so opening an issue in https://github.com/sindresorhus/execa might be helpful!

Keeping this open for now for further discussion and happy to accept a fix. Thanks!
