### ISSUE TITLE
[gatsby-plugin-postcss-sass] Plugin still listed as official plugin, despite being removed

### ISSUE THREAD

**Issue by annaelde** [gatsbyjs/gatsby#16711]
## Description

`gatsby-plugin-postcss-sass` still shows up as an official plugin when searching for plugins on the Gatsby site, despite being removed as a submodule in the project itself, leading to confusion on how to integrate Sass and Postcss.

### Steps to reproduce

- Go to Plugins and search for `gatsby-plugin-postcss-sass`
- Click on the plugin

### Expected result

A notice that the plugin's functionality has been moved over to `gatsby-plugin-sass`.

### Actual result

The detail pane is empty and the GitHub link leads to a 404.

### Environment

N/A

**Comment by KyleAMathews** [comment]
Ooops! My bad — I should have deprecated that a while ago. I deprecated it on npm and it now isn't showing up on the plugins search. Thanks for alerting us to this issue!
