### ISSUE TITLE
which admin setup for Gatsby with Symfony Api Platform?

### ISSUE THREAD

**Issue by BernardA** [gatsbyjs/gatsby#16729]
## Summary
I am planning an app with Symfony's Api Platform as back-end and I am not sure what is the best setup concerning the admin.
By the way, this is not a blog app. It's actually a base for full fledged web apps with members' area, fully interactive, that could be used for a number of applications. 

## Relevant information
As I see, there are a few options:
- Symfony EasyAdminBundle - lots of functionality out of the box but I do not want Twig
- Api Platform Admin - seems fine at a first glance and has the advantage of using the same techno from the back-end, based upon React-Admin, but I am not sure if and how this would combine with Gatsby. I want to avoid things that do not work well together
- React-Admin - not sure how this works together with Gatsby and if it would make sense decoupling it from Api Platform as the previous alternative.
- Netlify CMS - still another techno to learn?? what would be the upside?

I certainly missed something, but that's the gist of it.

Please advise. Thanks

### Environment (if relevant)

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.7.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 65.0.1
    Safari: 12.1.2
  npmGlobalPackages:
    gatsby-cli: 2.6.4

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by Slowwie** [comment]
Its also a issue I am interested in. Cant believe that nobody has to say something about that ...

**Comment by BernardA** [comment]
@Slowwie, just to let you know how I am going about it. I've chosen API-Platform/admin. 
I set it up in a separate app, a plain React app -no Gatsby there - that connects with the same API back-end as the main Gatsby app does. It can either be placed in a sub-domain of the main website or as a completely new domain. 
As you may know, API-platform is built upon react-admin and you could have the same set up above using react-admin directly - no API-platform admin - but you would need to create a specific data provider for API-Platform, which API-platform/admin gives you straight out of the box.
From my experience so far, the downside of using API-Platform/admin is that the support/community for API-Platform/admin is a bit lacking. I am working on and off on it and every time I find a road block is takes ages to receive any feed-back. Hope that helps.

**Comment by Slowwie** [comment]
Ok, thank u for the fast answer. Why do u choosed, not to use gatsby? Because of api-platform/admin uses react-admin?

**Comment by BernardA** [comment]
First because the API-platform/admin and react-admin set up do not work well with Gatsby's set up and second because the admin app being behind a login and with only dynamic content, you do not need or use  the benefits of Gatsby, ie, fast static HTML pages.

**Comment by Slowwie** [comment]
Ok, thank u. I am also interested how to use gatsby and create fast static html pages with api-platform in the frontend section.

**Comment by Enrico724** [comment]
I have created a Gatsby Starter which integrates API Platform: https://github.com/Enrico724/gatsby-api-platform-starter
