### ISSUE TITLE
Suggestion:  Use different example in client-only-paths example repo

### ISSUE THREAD

**Issue by gc** [gatsbyjs/gatsby#16724]
I simply want to suggest that https://github.com/gatsbyjs/gatsby/blob/master/examples/client-only-paths/gatsby-node.js show a more real-world example, I find it a bit confusing currently having *every* page be client-only which I doubt many want to (or should) do.

For example,
```js
const clientOnlyRoutes = ['/account', '/billing', '/myitems/*'];

// clientOnlyRoutes are client-only-paths
exports.onCreatePage = async ({ page, actions }) => {
...
```

I didn't PR this because I'm not sure how to do it.

**Comment by jonniebigodes** [comment]
@gc that example is just a pure example on how to achieve and shows how the feature is implemented. If you take a look at the rest of them, most of them, if not all are really simple use cases. Probably in this case adjust the readme for this example to contain a reference that it's a barebones one and if it's needed a more in depth case probably point to [this](https://www.gatsbyjs.org/tutorial/authentication-tutorial/)  document, or some other example in that nature

**Comment by gc** [comment]
I was originally reading the linked tutorial, which I didn't understand (the `if ()` createPage part), which lead me to looking for more examples to figure out how to do what I want. (which I'm still not sure how to do). Perhaps it's just me being slow.  Closing as I've switched to create-react-app as my application is too dynamic and its just causing me issues.
