### ISSUE TITLE
[gatsby-plugin-less] Upgrade to less-loader v5 required

### ISSUE THREAD

**Issue by anantoghosh** [gatsbyjs/gatsby#16725]
## Description

[Latest less release](https://github.com/less/less.js/releases) v3.10.1 [does not work](https://github.com/less/less.js/issues/3414) with the older less-loader v4 included in `gatsby-plugin-less`.

Upgrade to less-loader v5 is required to [fix this](https://github.com/less/less.js/issues/3414#issuecomment-522283588).

### Steps to reproduce

Use gatsby-plugin-less with less v3.10.1.

### Expected result

No errors

### Actual result

Error thrown while processing less files.
```
Class constructor FileManager cannot be invoked without 'new'
      in undefined (line undefined, column undefined)
```
Example error: https://circleci.com/gh/anantoghosh/gatsby-plugin-purgecss/1132

**Comment by sidharthachatterjee** [comment]
Fixed in `gatsby-plugin-less@3.0.0`
