### ISSUE TITLE
Gatsby not loading pages

### ISSUE THREAD

**Issue by barbalex** [gatsbyjs/gatsby#16730]
## Description

Pages are not being loaded. Instead a page containing this text is shown:

```
Gatsby.js development 404 page
There's not a page yet at /
```

But there _is_ an index.js file in the pages folder.
The same happens with the /test route.

This was a create-react-app project. I tried to convert it to gatsby according to https://www.gatsbyjs.org/docs/porting-from-create-react-app-to-gatsby/ and some other gatsby apps I have built.

So probably I have just forgotten something or made an error?

### Steps to reproduce

1. clone https://github.com/FNSKtZH/ae2/tree/gatsby
1. cd to it's folder
1. run `yarn`
1. run `yarn dev`
1. see the result

(the actual app needs a graphql api to run but the error happens before the api is called)

### Expected result

The contents of `/pages/index.js` should be shown

### Actual result

This is shown:
```
Gatsby.js development 404 page
There's not a page yet at /
```

### Environment

  System:
    OS: Windows 10
    CPU: (20) x64 Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
  Binaries:
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - C:\Python27\python.EXE
  Browsers:
    Edge: 44.18362.267.0
  npmPackages:
    gatsby: 2.13.67 => 2.13.67
    gatsby-plugin-create-client-paths: 2.1.3 => 2.1.3
    gatsby-plugin-eslint: 2.0.5 => 2.0.5
    gatsby-plugin-manifest: 2.2.5 => 2.2.5
    gatsby-plugin-offline: 2.2.6 => 2.2.6
    gatsby-plugin-react-helmet: 3.1.3 => 3.1.3
    gatsby-plugin-styled-components: 3.1.2 => 3.1.2
    gatsby-plugin-typography: 2.3.2 => 2.3.2
    gatsby-plugin-web-font-loader: 1.0.4 => 1.0.4
    gatsby-source-filesystem: 2.1.9 => 2.1.9

**Comment by anantoghosh** [comment]
The `pages` directory needs to be inside the `src` folder. Components under `src/pages` are automatically turned into static pages.

**Comment by barbalex** [comment]
omg

Thanks for this great tool and your friendly patience while helping!
