### ISSUE TITLE
Unwanted component re renders when upgrading from Gatsby version 1 to 2

### ISSUE THREAD

**Issue by davidbbe** [gatsbyjs/gatsby#16745]
## Description

Hey guys, we have been using Gatsby v1 (1.9.279) for a while and have been pretty happy with it. We have been working on updating to v2 and found persistent components like nav, footer, and global styles are being re rendered on internal page changes. I figure this is an implementation issue but we have followed all the migration guides and compared our project against other Gatsby themes. Our repo is private so Im afraid I cant show everything. Ive spent alot of time searching for any others with this issue with but I havent had any luck finding the root of the problem. Please let me know if any others have seen similar issues or knows of a solutions. 

### Steps to reproduce

Updating a Gatsby project from v1 to v2 and following all migration guide steps. We did this [here on staging](https://deploy-preview-410--particle-staging-01110000.netlify.com/). 
`npm update gatsby`
`gatsby build && gatsby serve`

### Expected result

Persistent components should not unmount and remount. These elements should hold across internal page changes. 

### Actual result

Persistent components like the nav, footer, and global styles are flickering on page changes. Further inspection shows them as unmounting and remounting. Fonts loaded through the global styles component are also be reloaded on each page change. 

### Environment

```System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.0 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 5.10.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 77.0.3865.19
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.56 => 2.13.56 
    gatsby-cli: ^2.7.28 => 2.7.28 
    gatsby-image: ^2.2.8 => 2.2.8 
    gatsby-plugin-netlify: ^2.1.4 => 2.1.4 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3 
    gatsby-plugin-sharp: ^2.2.10 => 2.2.10 
    gatsby-plugin-sitemap: ^2.2.6 => 2.2.6 
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-source-contentful: ^2.1.18 => 2.1.18 
    gatsby-source-filesystem: ^2.1.9 => 2.1.9 
    gatsby-transformer-sharp: ^2.2.6 => 2.2.6 
    gatsby-transformer-yaml: ^2.2.4 => 2.2.4```

**Comment by herecydev** [comment]
Do you have a repro for this? Is it similar to #16243 ?

**Comment by universse** [comment]
This article should explain your issue
https://www.gatsbyjs.org/blog/2018-06-08-life-after-layouts/

**Comment by davidbbe** [comment]
@herecydev no, I stated above that the repo is set to private. [#16243](https://github.com/gatsbyjs/gatsby/issues/16243) is a bit different from this as #16243 relies on gatsby-plugin-layout to hold persistent components across internal page changes. My problem seems to be that Im relying on the Gatsby v2 recommended setup instructions of layouts and templates to keep the same functionality that I expect from a React app. 

@universse thats a good article about this issue. I didnt come across that one in my search results. I think this issue is just that I would need to leverage gatsby-plugin-layout or one of the Browser and SSR APIs like wrapRootElement or wrapPageElement.
