### ISSUE TITLE
Modify Template GraphQL Queries Dynamically

### ISSUE THREAD

**Issue by nadrane** [gatsbyjs/gatsby#16753]
## Summary

I want to be able to dynamically modify GraphQL queries exported from my template files. More specifically, inside the gatsby-node.js file or inside a custom plugin, I want to access and modify the AST associated with my GraphQL queries using a programmatic builder API similar to [GraphQL Compose](https://github.com/graphql-compose/graphql-compose)

Let me show you an example. Suppose my following query is exported from `templates/test.js`

```
export const query = graphql`
  query {
    Api {
      title
      url
      html
    }
  }
`
```

I want to be able to programmatically change it to

```
export const query = graphql`
  query($topUserParam: String!) {
    Api {
      title
      url
      html
      widgets {
	  topUsers // a fragment defined elsewhere
      }
    }
  }
`
```

## Why Do I Want to Do This

I recognize that this is an odd use case. Let me talk about why I’m doing it.

Our website is composed of many pages generated with a variety of templates and GraphQL queries, and each page has one of many widgets. The precise widgets that can appear on a page will ideally be determined by a content manger who uses [ContentStack](https://www.contentstack.com/). Each page will have a set of feature flags that can be turned on and off in ContentStack, and these feature flags determine which widgets are visible on which pages. Ideally, when ContentStack changes, the site will rebuild appropriately without any changes to the codebase. 

It’s fairly straightforward to represent each widget as a React component and to conditionally display them based on whether a ContentStack feature flag is on. The challenging part is modifying the GraphQL query to ensure that each widget has access to the information it needs without over querying or imposing unnecessary developer repetition. Let me elaborate on the hard problems:

1. **Only Querying Necessary Data** - Each widget has an associated fragment. A naive solution would be to always request the data necessary for every widget for every page. This produces an unacceptable performance penalty. We need to only query a particular widget’s fragment if the associated feature flag is flipped. Currently, we are using Prisma’s `@include` directive to solve this problem. This creates a lot of code repetition. Ideally, it would be solved programmatically through the requested API above.

2. **Defining Input Parameters** -  Each widget has a set of associated input parameters that need to be supplied to every GraphQL query that can return widget data. There are quite a few of these queries, and we want to avoid having to modify every single one (to add additional input parameters) every time a new widget is added. We can determine the valid set of input parameters using the data on ContentStack and would like to use that information to construct the GraphQL queries dynamically, adding each input parameter that appears in ContentStack to the GraphQL queries to which it applies.

I realize that these issues could be solved by using Apollo Client queries made at runtime. For a variety of operations reasons, we want our website to be built with static content exclusively. I’m hoping someone has some thoughts on how to solve this issue.

Several hooks/actions like [createFieldExtension](https://www.gatsbyjs.org/docs/actions/#createFieldExtension), though the precise one I need eludes me. I’d appreciate any direction or suggestions you can offer.

-Nick

**Comment by nadrane** [comment]
I found `exports.setFieldsOnGraphQLNodeType`, which is definitely aligned with what I want to do, but as far as I can tell, the API is append-only. Is there a mutable version of the same thing?

**Comment by nadrane** [comment]
In case anyone is curious, I learned that we can pass arbitrary data into the `context` argument of `createPage` and that it will be forwarded to the template's associated component via the `pageContext` prop. This gives us all the flexibility we need.

**Comment by LekoArts** [comment]
Great! Closing this issue as solved then.

**Comment by SachaG** [comment]
@nadrane would you have a code example of how you managed this by any chance? I think I have the same use case as you.

**Comment by SachaG** [comment]
Oh I found the explanation here: https://nickdrane.com/optimizing-gatsby-build-times-for-large-websites-using-pagecontext/ 

Interesting approach, I'll look into it!
