### ISSUE TITLE
Gatsby Starter does not pull images from Unsplash

### ISSUE THREAD

**Issue by hhimanshu** [gatsbyjs/gatsby#16751]
## Description

I am following https://www.gatsbyjs.org/tutorial/part-one/ and on `#4`, there is the following code
```js
import React from "react"
export default () => (
  <div style={{ color: `purple` }}>
    <h1>Hello Gatsby!</h1>
    <p>What a world.</p>
    <img src="https://source.unsplash.com/random/400x200" alt="" />
  </div>
)
```

  Useful Links:
  - Documentation: https://www.gatsbyjs.org/tutorial/part-one/

### Steps to reproduce

```
gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
gatsby develop
```  
Replace the code in `src/pages/index.js` with following
```js
import React from "react"

export default () => (
  <div style={{ color: `purple` }}>
    <h1>Hello Gatsby!</h1>
    <p>What a world.</p>
    <img src="https://source.unsplash.com/random/400x200" alt="" />
  </div>
)
```
### Expected result
The image should show up

### Actual result
The image doesn't show up
You get the following error
```
source.unsplash.com/random/400x200:1 GET https://source.unsplash.com/random/400x200 net::ERR_BLOCKED_BY_CLIENT
```  

While, the `URL` works well independently, it does not work with Gatsby project
<img width="625" alt="Screen Shot 2019-08-19 at 4 44 59 PM" src="https://user-images.githubusercontent.com/6589036/63306799-f9063400-c2a0-11e9-8d5d-5356d2735fd8.png">

### Environment
```sh
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v11.14.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Safari: 12.1.2
  npmGlobalPackages:
    gatsby-cli: 2.7.30
```

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by SimonMayerhofer** [comment]
Most of the time as far as I know the error ERR_BLOCKED_BY_CLIENT means that something local (like an extension) is blocking something. have you tried this with no extensions activated?

**Comment by hhimanshu** [comment]
@SimonMayerhofer, that was a fast reply 💯 
you're right, when I ran it in `incognito` window on Chrome, things seemed fine. Thanks for educating me!
<img width="1439" alt="Screen Shot 2019-08-19 at 5 09 35 PM" src="https://user-images.githubusercontent.com/6589036/63307735-4d5ee300-c2a4-11e9-8460-1cf97584fc0f.png">
Closing this issue!
