### ISSUE TITLE
[gatsby-plugin-google-tagmanager] Should have an "disable" option

### ISSUE THREAD

**Issue by evolkmann** [gatsbyjs/gatsby#16756]
## Summary

`gatsby-plugin-google-tagmanager` currently only differentiates between development/production based on `process.env.NODE_ENV`. This is not sufficient for all use cases:

In our particular scenario, we build the app on multiple branches and subdomains (e.g. dev, stage, prod) for clients to review things before going live. In all of those builds, `process.env.NODE_ENV` is set to `production`.

To disable Tag-Manager on those non-prod domains, I would like to disable the plugin based on some other condition (e.g. CI/CD env variables).

I therefore propose a new `disable` option which accepts a boolean or a function returning a boolean to control the behaviour of the plugin. The current option `includeInDevelopment` would be obsolete. The current behavior could be handled internally.

**Comment by evolkmann** [comment]
I would like to implement this sometime in the next 1-2 weeks.

**Comment by wardpeet** [comment]
Hey, it seems like a valid approach but why not disable the plugin as a whole?

In gatsby.config.js
```js
const dynamicPlugins = [];
if ( process.env.CUSTOM_STAGE === 'production') {
  dynamicPlugins.push({
    resolve: "gatsby-plugin-google-tagmanager",
    options: {
      // YOUR OPTIONS
    },
  });
}

module.exports = {
  // some config... 
  plugins: [
    // your plugins
    ...dynamicPlugins,
  ],
  // more config...
}
```

**Comment by evolkmann** [comment]
Yes this would also work. I was looking for a way to do this before creating this issue. Unfortunately I did not come up with this simple idea 😄 

I think yours is the cleaner solution 👍

**Comment by wardpeet** [comment]
Thank you for opening this, @evolkmann

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
