### ISSUE TITLE
Field "sort" is not defined by type FileFilterInput

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#16754]
Looks like sorting doesn't work on `FileFilterInput`

Query works fine in `__graphql` but fails when added to a `StaticQuery` with 

```Field "sort" is not defined by type FileFilterInput. Did you mean root?

@ ./.cache/caches/gatsby-plugin-mdx/mdx-scopes-dir/d1809c33c87039737066d0a8cacc15a5.js 1:1524-1583 1:1932-1944
 @ ./node_modules/gatsby-plugin-mdx/loaders/mdx-scopes.js
 @ ./node_modules/gatsby-plugin-mdx/wrap-root-element.js
 @ ./node_modules/gatsby-plugin-mdx/gatsby-browser.js
 @ ./.cache/api-runner-browser-plugins.js
 @ ./.cache/api-runner-browser.js
 @ ./.cache/app.js```

Reproduction is at https://github.com/sidharthachatterjee/garbage-pail-components 

CC @marcysutton

**Comment by sidharthachatterjee** [comment]
Never mind, not enough ☕️ when I opened this

**Comment by alexeychikk** [comment]
@sidharthachatterjee Do you remember what was the cause of the issue, please? I have a similar one
```
Field "id" is not defined by type MarkdownRemarkFrontmatterFilterInput.
```
I guess it's because there are no markdown files that declare this field. But I want my build not to fail if there are no such md files created yet. How can I overcome this?

**Comment by gyojir** [comment]
I have same issue and found solution.

It is mentioned in
https://stackoverflow.com/questions/57549278/gatsby-not-inferring-graphql-field-if-all-nodes-happen-to-be-null-on-that-field
https://www.gatsbyjs.org/docs/schema-customization/#nested-types

`gatsby-node.js`
```
exports.createSchemaCustomization = ({ actions, schema }) => {
  const { createTypes } = actions

  const typeDefs = `
    type MarkdownRemark implements Node {
      frontmatter: Frontmatter
    }
    type Frontmatter {
      tags: [String!]!
    }
  `
  createTypes(typeDefs)
}
```
