### ISSUE TITLE
Components Not Rendering inside a MDX file

### ISSUE THREAD

**Issue by jnsrikanth** [gatsbyjs/gatsby#16764]
## Description

I have created a GatsbyJS MDX site which seems to display normal MDX files. However, when I import components from the Internet or Local, they are not rendering.

### Steps to reproduce
The code repository is listed below. However, this is a private repo and I will invite you to access it if you are willing to look into this issue. Thanks for understanding.

https://github.com/jnsrikanth/gatsby-starter-mdx-basic

Gatsby Config, Gatsby Node file and the MDX file are pasted below

gatsby-config.js file contents below:

```

const path = require('path')

module.exports = {
  siteMetadata: {
    title: 'Gatsby Starter MDX Basic',
    description:
      'Kick off your next, great Gatsby project with this default starter.
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages`
      }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `blog`,
        path: `${__dirname}/src/pages/blog`
      }
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
	   {
    resolve: `gatsby-transformer-remark`,
    options: {
      plugins: [
        {
          resolve: `gatsby-remark-images`,
          options: {
            // It's important to specify the maxWidth (in pixels) of
            // the content container as this plugin uses this as the
            // base for generating different widths of each image.
            maxWidth: 590,
          },
        },
      ],
    },
  },

    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        extensions: ['.mdx', '.md'],
        defaultLayouts: { default: path.resolve('./src/components/blog-post-layout.js') },
	mdPlugins: [
	   require('remark-images'),
	   require('remark-slug'),
	   require('remark-autolink-headings')
	],
	gatsbyRemarkPlugins: [
	     {
		resolve: 'gatsby-remark-images',
		      options: {
			      maxWidth: 1200,
		      },
	      },
	 ],
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'gatsby-default-mdx-basic',
        short_name: 'starter',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/gatsby-icon.png', // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.app/offline
    // 'gatsby-plugin-offline',
  ],
}
```
`

gatsby-node.js file contents below:

```
const { createFilePath } = require('gatsby-source-filesystem')
const path = require('path')

// Here we're adding extra stuff to the "node" (like the slug)
// so we can query later for all blogs and get their slug
exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions
  if (node.internal.type === 'Mdx') {
    const value = createFilePath({ node, getNode })
    createNodeField({
      // Name of the field you are adding
      name: 'slug',
      // Individual MDX node
      node,
      // Generated value based on filepath with "blog" prefix
      value: `/blog${value}`
    })
  }
}

// Programmatically create the pages for browsing blog posts
exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions
  return graphql(`
    query {
      allMdx(sort: { order: DESC, fields: [frontmatter___date] }) {
        edges {
          node {
            id
            excerpt(pruneLength: 250)
            fields {
              slug
            }
            frontmatter {
              author
              title
            }
          }
        }
      }
    }
  `).then((results, errors) => {
    if (errors) return Promise.reject(errors)
    const posts = results.data.allMdx.edges

    // This little algo takes the array of posts and groups
    // them based on this `size`. I used a small number just
    // for testing since there are only three posts
    let size = 2
    let start = 0
    let groupedPosts = Array.from(Array(Math.ceil(posts.length / size)))
    groupedPosts = groupedPosts.map(() => {
      const group = posts.slice(start, start + size)
      start += size
      return group
    })

    groupedPosts.forEach((group, index) => {
      const page = index + 1
      createPage({
        path: `/blog/${page}`,
        component: path.resolve('./src/components/browse-blog-posts.js'),
        context: { groupedPosts, group, page }
      })
    })
  })
}
```
`
Here is the contents of the MDX file. 

```
---
path: 'apple'
title: 'Apple Services'
date: 2018-11-18T12:33:46+10:00
author: 'Srikanth'
image: 'services/default.png'
---

import { Box, Heading, Text } from 'rebass'

import {
  FacebookShareButton,
  LinkedinShareButton,
  TwitterShareButton,
  WhatsappShareButton,
  PinterestShareButton,
  EmailShareButton,
} from 'react-share'

import {
  FacebookShareCount,
  PinterestShareCount,
  VKShareCount,
  OKShareCount,
  RedditShareCount,
  TumblrShareCount,
} from 'react-share'


# Here is a JSX block
It is using imported components!

<Box>
  <Heading>Here's a JSX block</Heading>
  <Text>It's pretty neat</Text>
</Box>


# Here’s a Social Share


<FacebookShareButton
            url='http://github.com'
            quote='GitHub'
            className="Demo__some-network__share-button">
            <FacebookIcon
              size={32}
              round />
          </FacebookShareButton>

Lorem markdownum aequalis strigis. _Saetigeri iubeas_, vultu huic alvum nondum
de obside ut laniavit arbor palmis, cum quin. Rupes vetat videndo, armigerae
crimen habet Priamum nec.

![gatsbyjs-logo](./gatsbyjs-logo.jpg)

## Ne verba patulosque numen vix libet



Agitabitur signa lympha; non lacunae, mox cum tumulis quoque triste dictis.
Ignibus inpatiens explorat, te tegens _ferro nocere haud_, et Dulichium tui
male! Quo sed [fuit flexit et](#vexant-achivi) hic die solido, gloria?

1. Cum det dixit Parcarum qui spemque est
2. Exit ex huic
3. Quod consiste agitataque claustraque vicina videt lacertis
4. Loquor videt
5. Ardua non igne caelesti coniugis cognovi diversorum
6. Per nunc pariterque saeva vindicet

Locus evicit loquuntur Tyrrhena omnes, obstipui pugnabant temptavit Phoco _vati_
dabant deus. Memorata haberet sepulcrales gentisque dum sic, in flumina templa!
Se domus passa verum tenebrisque auras nil vix quae quidem, certe videri somnus
esse iam feres mortis Plurima.

## Postquam tamen

Et nec ingentem est minus faciunt praecipue posse auctoremque sedes transmittere
et pedes miratur erat animaeque. Tellus admonuit humanam funes, sagittis et
licet! Inserui quamvis Clymeni.

- Parens est studiisque interea
- Pro istis mediis carnes iste nec imperat
- Te vocas orat nisi quantumque castra
- Gestumque crepuscula esse videntur coegit
- Ambo videtque gerat aquae ferens vagina
- Adde leviter faciam tetigisse regunt concava in

Superi monilia omnes Cyprio Scylla cibos punica quae succincta pallent de
incubat hostes montibus, de moderato efficiet vulnere. Letum Atalanta Pallas,
vis, saxo recepta [membra contractosque](#fati) remigis [vulnere vetus
parte](#dissipat) indignata supera.

Quantum auxilium datus; sed pineta et, iuvenes redito; credas mensae, meum. Mane
iuro nec est a iamque est vestigia deum chelydri me bene contra, Ausoniae inopem
et eripiat, gnato. Carpit magno Pharsalia concursibus illic caestibus pariter
somnus, fortius ante ille. Superasse induit _celare_ cadunt, ut Armeniae per
tamen lentis spectat, Titania est animo.
````

### Expected result

Expecting to see React Components render via the MDX markdown file.

### Actual result
Unable to render React components embedded inside the MDX file.

What happened.
The rest of the MDX file is showing up properly and the React Components are simply being ignored for rendering. 

### Environment

 System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/SmartTechies/.windows-build-tools/python27/python
  npmPackages:
    gatsby: ^2.13.50 => 2.13.67
    gatsby-image: ^2.2.8 => 2.2.8
    gatsby-plugin-manifest: ^2.2.5 => 2.2.5
    gatsby-plugin-mdx: ^1.0.0 => 1.0.24
    gatsby-plugin-offline: ^2.2.4 => 2.2.6
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sharp: ^2.2.9 => 2.2.12
    gatsby-remark-images: ^3.1.12 => 3.1.12
    gatsby-source-filesystem: ^2.1.8 => 2.1.9
    gatsby-transformer-mdx: ^1.1.2 => 1.1.2
    gatsby-transformer-remark: ^2.6.14 => 2.6.14
    gatsby-transformer-sharp: ^2.2.5 => 2.2.6

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by jnsrikanth** [comment]
Bringing @KyleAMathews into the loop.

**Comment by jonniebigodes** [comment]
@jnsrikanth if you're willing, i'll post an possible answer to your issue. Currently testing out something to see if that's the case based on your description, if it's not then we'll move from there, sounds good?

**Comment by jonniebigodes** [comment]
@jnsrikanth after testing a bit it looks like i have a solution for your issue.
Below are the steps taken to solve this.
- Created a new gatsby site based on the default starter.
- Saw that your code is probably similar to [this](https://github.com/bradwestfall/gatsby-mdx-blog), so with that in mind i installed the missing dependencies, transforming the package.json into:
```json
dependencies": {
    "@mdx-js/mdx": "^1.3.1",
    "@mdx-js/react": "^1.3.1",
    "@mdx-js/tag": "^0.20.3",
    "gatsby": "^2.13.73",
    "gatsby-image": "^2.2.10",
    "gatsby-plugin-manifest": "^2.2.6",
    "gatsby-plugin-mdx": "^1.0.25",
    "gatsby-plugin-offline": "^2.2.7",
    "gatsby-plugin-react-helmet": "^3.1.4",
    "gatsby-plugin-sharp": "^2.2.13",
    "gatsby-remark-images": "^3.1.13",
    "gatsby-source-filesystem": "^2.1.11",
    "gatsby-transformer-remark": "^2.6.15",
    "gatsby-transformer-sharp": "^2.2.7",
    "prop-types": "^15.7.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-helmet": "^5.2.1",
    "react-share": "^3.0.0",
    "rebass": "^4.0.3",
    "remark-autolink-headings": "^5.2.1",
    "remark-images": "^1.0.0",
    "remark-slug": "^5.1.2"
  },
```
leaving in the dependencies only for brevity.
- Modified both `gatsby-node.js` and `gatsby-config.js` to match yours.
- Based on your previous issue, i replicated the same folder structure so that i could use the mdx content you've supplied in the description. The supplied mdx is inside `services/accounting.mdx`
![no_external_component_mdx](https://user-images.githubusercontent.com/22988955/63466639-9907bd00-c45b-11e9-96c5-6d3a46f9e4fb.png)

Issued `gatsby develop` opened up `http://localhost:8000/services/accounting` and i could see that almost all was alright, the box was rendered with the content, but the social icons were not.
- Took a closer look at your mdx file and saw that you were duplicating the imports namely you had this:
```javascript
import {
  FacebookShareButton,
  LinkedinShareButton,
  TwitterShareButton,
  WhatsappShareButton,
  PinterestShareButton,
  EmailShareButton,
  
} from 'react-share'


import {
  FacebookShareCount,
  PinterestShareCount,
  VKShareCount,
  OKShareCount,
  RedditShareCount,
  TumblrShareCount,
} from 'react-share'
```
And also that you have this:
```jsx
<FacebookShareButton
    url='http://github.com'
    quote='GitHub'
    className="Demo__some-network__share-button">
    <FacebookIcon
        size={32}
        round />
</FacebookShareButton>
```
But you're not importing the icon itself into the mdx.

Rearranged the imports to the following:
```javascript

import {
  FacebookShareButton,
  LinkedinShareButton,
  TwitterShareButton,
  WhatsappShareButton,
  PinterestShareButton,
  EmailShareButton,
  FacebookShareCount,
  PinterestShareCount,
  FacebookIcon,
  VKShareCount,
  OKShareCount,
  RedditShareCount,
  TumblrShareCount,
} from 'react-share'
```
And i'm presented with this:
![no_external_component_mdx_2](https://user-images.githubusercontent.com/22988955/63467603-bf2e5c80-c45d-11e9-84fd-f531efe9f8f9.png)

As you can see by the screenshot above, the icon is imported and displayed.

Feel free to provide feedback so that we can close this issue, if this was the case for you. Or if not let me know so that we can continue to work on your issue until we find a suitable solution.

**Comment by jnsrikanth** [comment]
Hi @jonniebigodes 
Thanks a ton for your support. I was able to add the icon and was able to display the Facebook and other social media icons now. However, I am puzzled as to why the Box from Rebass React package did not render. 

Now, I am stuck at another issue within the same configuration. I am unable to view the images from the frontmatter in my Main Blog List page. I have made the following changes to gatsby-node.js file from before with only one change (added 'image') to the node frontmatter as follows.

// Programmatically create the pages for browsing blog posts
exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions
  return graphql(`
    query {
      allMdx(sort: { order: DESC, fields: [frontmatter___date] }) {
        edges {
          node {
            id
            excerpt(pruneLength: 250)
            fields {
              slug
            }
            frontmatter {
              author
              title
              image
            }
          }
        }
      }
    }


However, upon doing that while accessing that image (from the frontmatter), I get the following error. 

Accessing the image as:
<img 
alt=""
src={node.frontmatter.image}
/>

and getting the below ERROR

ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?

File: gatsby-node.js:24:10


 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

Cannot read property 'allMdx' of undefined

Could you help me with that? Thanks in advance.

**Comment by jnsrikanth** [comment]
Remember that the same way of node creation was successful in the previous repository I shared with you. The only difference is that we have now added MDX support.

**Comment by jonniebigodes** [comment]
@jnsrikanth no need to thank, i'm glad i was able to help you. When i was trying to figure out the reason i thought that rebass could be the culprit. But upon fiddling with the code i was able to change the box component on the fly without any issues whatsoever. Check if the issue applies to your previous issue, namely #16612 . If not, like you said it's a private repo, if you can do invite me to the repo and i'll go about the code and see what could be the issue.

**Comment by jnsrikanth** [comment]
@jonniebigodes - I have added you to the repository. I am also sending you the link to the invitation below through which you could access I think.
https://github.com/jnsrikanth/gatsby-starter-mdx-basic/invitations

**Comment by jnsrikanth** [comment]
Also @jonniebigodes if you are open to or ok with, I can also share a Slack channel with you for a more real-time information exchange.

**Comment by jnsrikanth** [comment]
@jonniebigodes I did realize that removing index.js from the pages folder was not a good idea although browse-blog-posts.js is the main home page renderer for this site. I have added the index.js back into the site.

**Comment by jonniebigodes** [comment]
@jnsrikanth a couple of questions before we delve deeper.
1- Are you going to be using the `gatsby-image` and it's peers `gatsby-transformer-sharp` and `gatsby-plugin-sharp` to handle the images, making them responsive?
2- Seeing your comment above, you want to use `browse-blog-posts.js ` as the main page is that it?

**Comment by jonniebigodes** [comment]
@jnsrikanth i've gone through your code and without divulging any personal information as the work is private, i saw that the issue you're experiencing is that you have some `.mdx` files that have a frontmatter element called `image` and it's not present in other files. When gatsby is processing the data during the build process it will detect that the `image` element references a file and generates the appropriate FileNode in graphql. And as you have `gatsby-plugin-sharp` and `gatsby-transformer-sharp` it will allow you to manipulate the file to some extent, you can read up more on that in [here](https://www.gatsbyjs.org/docs/working-with-images/) and [here](https://www.gatsbyjs.org/docs/using-gatsby-image/). Also you can check the graphql explorer in `http://localhost:8000/___graphql` and you check the docs panel on the right, if you go through it, starting at `allMdx` and navigating through it you'll see what i mean and it will show you all the nodes available.

Like i said in the previous comment if you want to take advantage of `gatsby-image` and `gatsby-plugin-sharp` and `gatsby-transformer-sharp` you can pass the necessary information by changing your query, transforming it into:
```graphql
query {
      allMdx(sort: { order: DESC, fields: [frontmatter___date] }) {
        edges {
          node {
            id
            excerpt(pruneLength: 250)
            fields {
              slug
            }
            frontmatter {
              author
              title
              image {
                childImageSharp {
                  id
                  fluid {
                    src
                    srcSet
                    aspectRatio
                    sizes
                  }
                }
              }
            }
          }
        }
      }
    }
```
With this change it will fetch the necessary information as before and now it will also fetch the information about the images referenced in mdx, already transformed and ready to be injected into the `gatsby-image` image component

And in the template you can do something like this:
```jsx
import Img from "gatsby-image";
const templateUsed= ({ pageContext }) => {
    return(
   ......
    {image !== null ? (
                <Img
                  key={`blogpost_img_${node.id}`}
                  fluid={image.childImageSharp.fluid}
                />
              ) : null}
              {/* <img
                src={node.frontmatter.image}
              /> */}
    )
      
}
```
Instead of using the basic html img element you can use the gatsby image component and it will allow you to use images that are responsive, lazy loaded among other features available.
Also you can manipulate it further depending on your needs.

Feel free to provide feedback

**Comment by jnsrikanth** [comment]
Hi @jonniebigodes 

Yes, I am trying to capitalize on the power of Gatsby Sharp and related image plugins for responsiveness, lazy loading, and other interesting optimizations and make it a standard for all image processing inside my Gatsby Site. 
However, I am still kind of paused at the same issue with the image not rendering even with the suggested changes by you with both 'fluid' and 'key' params for Img suggested by you. I got the below error with a compile failure. 

![img_key_err_gatsby](https://user-images.githubusercontent.com/17452662/63589227-34b53c80-c5c6-11e9-8b88-041ca225db45.PNG)

When I removed the key param and used only the Img->fluid param as below, I did not get to render the image as well. 

```
<Layout>
      {group.map(({ node }) => {
        const { title, author } = node.frontmatter
        return (
          <div key={node.id}>
            <header>

              <div style={{fontSize:'50'}}>{title}</div>
              <div>Posting By {author}</div>
            </header>
                {(node.frontmatter.image)?
                  <Img
                    fluid={node.frontmatter.image.childImageSharp.fluid}
                  />
                :null}
            <p>{node.excerpt}</p>
            <Link to={node.fields.slug}>View Article</Link>
            <hr />
          </div>
        )
      })}
```
Interestingly when I did query graphql editor I can see the image being present for the apple.mdx entry in the graphql query result on the right hand side. 

![graphql-query](https://user-images.githubusercontent.com/17452662/63589577-274c8200-c5c7-11e9-9524-7b0be079e953.PNG)

What am I still doing wrong? I wish I would have somehow gained mastery in gatsby image processing so that can put such issues behind and focus on more beautiful layouts, functionality, and  UI/UX related problems, but I know it takes its own time to learn by example and mastering graphql a little better. 
Please recommend the best approach for this. I have also updated the Git repository with the above changes.

**Comment by jnsrikanth** [comment]
And of course, I did change the Graphql query as per your suggestion to this in gatsby-node.js as below...

```
query {
      allMdx(sort: { order: DESC, fields: [frontmatter___date] }) {
        edges {
          node {
            id
            excerpt(pruneLength: 250)
            fields {
              slug
            }
            frontmatter {
              author
              title
               image {
                childImageSharp {
                  id
                  fluid {
                    src
                    srcSet
                    aspectRatio
                    sizes
                  }
                }
              }
            }
          }

```

**Comment by jonniebigodes** [comment]
@jnsrikanth the issue with error was my fault. when i posted the code excerpt i missed a tick (`) in the code and with that the string template is wrong,
It should instead be:

```jsx
<Layout>
      {group.map(({ node }) => {
        const { title, author, image } = node.frontmatter;
        return (
          <div key={node.id}>
            <header>
              <div style={{ fontSize: "50" }}>{title}</div>
              <div>Posting By {author}</div>
            </header>
            {image !== null ? (
              <Img
                key={`img_${image.childImageSharp.id}`} //<- correct one with the string template
                fluid={image.childImageSharp.fluid}
              />
            ) : null}
            <p>{node.excerpt}</p>
            <Link to={node.fields.slug}>View Article</Link>
            <hr />
          </div>
        );
      })}
    .....rest of the component implementation
    </Layout>
```
The image data obtained from the `apple.mdx` exists because during the build process gatsby detects that the image exists for that item and as you have `gatsby-plugin-sharp` and `gatsby-transformer-sharp` it will manipulate it accordingly and generate the necessary graphql nodes so that they can be used at your discretion.

Now i'm going to try and elaborate more on this with a example.

- Created a new post, not a page inside the appropriate folder, called `fourth.mdx` with following content:
```markdown
---
# This is the frontmatter which goes at the top of the MDX file
# Hashes in the frontmatter are comments
title: Fourth Blog Post
author: Jonniebigodes
date: 2019-02-05
image: ./fourth.jpg
---

## Look it's mdx test
```
The `image` field referenced is just a stock image used for demonstrations.

- Issued `gatsby develop` and waited for it to complete and no errors or anything.
- Opened `http://localhost:8000/___graphql` and issued the query, which is the one used in `gatsby-node.js`:
```graphql
query {
      allMdx(sort: { order: DESC, fields: [frontmatter___date] }) {
        edges {
          node {
            id
            excerpt(pruneLength: 250)
            fields {
              slug
            }
            frontmatter {
              author
              title
              image {
                childImageSharp {
                  id
                  fluid {
                    src
                    srcSet
                    aspectRatio
                    sizes
                  }
                }
              }
            }
          }
        }
      }
    }
```
It shows the correct information as you can see:
```json
{
  "data": {
    "allMdx": {
      "edges": [
        ...other mdx information
        {
          "node": {
            "id": "2c0c6d49-bfa0-5a03-b079-35f98a4dee28",
            "excerpt": "Look it's mdx test",
            "fields": {
              "slug": "/blog/fourth/"
            },
            "frontmatter": {
              "author": "Jonniebigodes",
              "title": "Fourth Blog Post",
              "image": {
                "childImageSharp": {
                  "id": "c457f6f4-3b8e-59cc-a701-ba589c3184b2",
                  "fluid": {
                    "src": "/static/2bd3ddfa6566de7d70653559b70545c5/bc3a8/fourth.jpg",
                    "srcSet": "/static/2bd3ddfa6566de7d70653559b70545c5/d278e/fourth.jpg 200w,\n/static/2bd3ddfa6566de7d70653559b70545c5/8539d/fourth.jpg 400w,\n/static/2bd3ddfa6566de7d70653559b70545c5/bc3a8/fourth.jpg 800w,\n/static/2bd3ddfa6566de7d70653559b70545c5/81ef8/fourth.jpg 1200w,\n/static/2bd3ddfa6566de7d70653559b70545c5/989b1/fourth.jpg 1600w,\n/static/2bd3ddfa6566de7d70653559b70545c5/14dee/fourth.jpg 1920w",
                    "aspectRatio": 1.6,
                    "sizes": "(max-width: 800px) 100vw, 800px"
                  }
                }
              }
            }
          }
        },
        {
          "node": {
            "id": "064cc95b-7302-5b2a-a43b-70913a490770",
            "excerpt": "Here’s a Social Share Lorem markdownum aequalis strigis.  Saetigeri iubeas , vultu huic alvum nondum\nde obside ut laniavit arbor palmis, cum quin. Rupes vetat videndo, armigerae\ncrimen habet Priamum nec. Ne verba patulosque numen vix libet Agitabitur…",
            "fields": {
              "slug": "/apple/"
            },
            "frontmatter": {
              "author": "Srikanth Jallapuram",
              "title": "Apple Services",
              "image": {
                "childImageSharp": {
                  "id": "d114d9be-9de1-5cd5-a24b-6133e2e55fcc",
                  "fluid": {
                    "src": "/static/ddc943df2d5913dba79783d8d4cf1aec/647de/default.png",
                    "srcSet": "/static/ddc943df2d5913dba79783d8d4cf1aec/7c0ed/default.png 200w,\n/static/ddc943df2d5913dba79783d8d4cf1aec/647de/default.png 400w",
                    "aspectRatio": 2.0100502512562812,
                    "sizes": "(max-width: 400px) 100vw, 400px"
                  }
                }
              }
            }
          }
        }
      ]
    }
  }
}
```
As you can see the information is accurate and the image information is shown and the image information is displayed like i said above.

There's some missing data above as it's not needed to be displayed and to keep it brief.
- Which leads us to the following piece of code in `gatsby-node.js`:
```javascript
const posts = results.data.allMdx.edges;

    // This little algo takes the array of posts and groups
    // them based on this `size`. I used a small number just
    // for testing since there are only three posts
    let size = 2;
    let start = 0;
    let groupedPosts = Array.from(Array(Math.ceil(posts.length / size)));
    groupedPosts = groupedPosts.map(() => {
      const group = posts.slice(start, start + size);
      start += size;
      return group;
    });

    groupedPosts.forEach((group, index) => {
      const page = index + 1;
      createPage({
        path: `/blog/${page}`,
        component: path.resolve("./src/components/browse-blog-posts.js"),
        context: { groupedPosts, group, page }
      });
    });
```
When this code is run during the build process it will generate pages like for instance `http://localhost:8000/blog/1` and so on.
- Visiting `http://localhost:8000/blog/3` it shows me the following:
![jnsrikanth_1](https://user-images.githubusercontent.com/22988955/63627402-71515a00-c5ff-11e9-945d-9a26fe360ab6.png)

With that you have the images available in your Main Blog List page

**Comment by jnsrikanth** [comment]
Hi @jonniebigodes 
I am a bit on a backfoot here about this. I can as well see the images in the graphql queries. 
What seems to elude me is the fact that I had to run a raw graphql query again in index.js in order to fetch the image as the pageContext did not seem to do so well with the image portion. My goal was to fetch the image from frontmatter in the main home page of the Blog from the pageContext that we seem to pass to gatsby-node.js. Nevertheless, graphql seems to be doing an excellent job as well here in retrieving the required information from the nodes and pages created by gatsby-node APIs. 

Hence, I am closing this one.

**Comment by jonniebigodes** [comment]
@jnsrikanth if by index.js you mean `src/pages/index.js`, the main page of the site, then you have to add a query in there, as that page itself doesn't contain any data that you supply to `pageContext` prop used in `gatsby-node.js` when you're creating the pages dynamically.

**Comment by jnsrikanth** [comment]
@jonniebigodes yes, I realized that the gatsby-node.js is passing pageContext to the other browseblogposts.js file and not to index.js hence the necessity for the graphql query. Thanks for a detailed buildout of my setup and several resolutions throughout this trail.
