### ISSUE TITLE
timeToRead: take into account different content like code snippets or mdx components.

### ISSUE THREAD

**Issue by codepunkt** [gatsbyjs/gatsby#16760]
## Summary

Time to read seems to take basic text into account, but definitely does not use all text content for calculation of the value.

### Basic example

Two mdx pages, one with a lot of code snippets and a few mdx components, the other one with mostly basic markdown text. Rendered, both consist of text-only content.

- First page spans 19 screens and has a reading time of 12 minutes
- Second page spans 8 screens and has a reading time of 10 minutes

### Motivation

timeToRead does not reflect reading time. Generated table of contents via remark or rehype plugins, code snippets and lots of other contents are not taken into account.

**Comment by slorber** [comment]
I'd like this to be implemented as well, but how can we automatically know how much time does it read to read something like a code fragment (or an image? or embedded tweet/codepen/codesandbox/iframe/widget? or something else?)

We can probably make approximations that make sense, but I think the best solution is to define yourself the reading time of your articles based on user feedback

**Comment by codepunkt** [comment]
Take string length of source code, divide by average word length, multiply with some random factor > 1. Not sure really. Could be pretty doable for source code, will probably be impossible to do for highly interactive things build with MDX.

**Comment by johnletey** [comment]
@codepunkt What's the best way to start working on this?
