### ISSUE TITLE
How to best implement Storybook into a theme

### ISSUE THREAD

**Issue by danspratling** [gatsbyjs/gatsby#16781]
## Summary

I'm in the process of adding Storybook.js to a gatsby theme i'm making but i'm not sure the best way to do this and am struggling with getting it working, but i'm not sure if my approach is correct or would even work so i'm looking for some help/ideas/a push in the right direction.

I'm new to both themes and storybook so i'm probably jumping in the deep end a little. And my project is typescript based which is causing some extra complexity.

## Relevant information

So far, i've got storybook set up inside my theme (not my site) with the intention of having the stories inside the src folder and being able to shadow them in the same way theme files can be shadowed on sites.

**theme/.storybook/config.js**
```import { configure } from '@storybook/react'
import { action } from '@storybook/addon-actions'

// Gatsby's Link overrides:
// Gatsby defines a global called ___loader to prevent its method calls from creating console errors you override it here
global.___loader = {
  enqueue: () => {},
  hovering: () => {},
}
// Gatsby internal mocking to prevent unnecessary errors in storybook testing environment
global.__PATH_PREFIX__ = ''
// This is to utilized to override the window.___navigate method Gatsby defines and uses to report what path a Link would be taking us to if it wasn't inside a storybook
window.___navigate = pathname => {
  action('NavigateTo:')(pathname)
}

// automatically import all files ending in *.stories.{js,jsx,ts,tsx}
const req = require.context('../src', true, /\.stories\.tsx$/)

function loadStories() {
  req.keys().forEach(filename => req(filename))
}

configure(loadStories, module)
```

**theme/.storybook/webpack.config.js** - a mix of solutions i've found which are probably doubling up on some things. Definitely not optimal.
```const { execSync } = require('child_process')
const { dirname, join } = require('path')

module.exports = ({ config }) => {
  // Transpile Gatsby module because Gatsby includes un-transpiled ES6 code.
  config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/]

  // use installed babel-loader which is v8.0-beta (which is meant to work with @babel/core@7)
  config.module.rules[0].use[0].loader = require.resolve('babel-loader')

  // use @babel/preset-react for JSX and env (instead of staged presets)
  config.module.rules[0].use[0].options.presets = [
    require.resolve('@babel/preset-react'),
    require.resolve('@babel/preset-env'),
  ]

  config.module.rules[0].use[0].options.plugins = [
    // use @babel/plugin-proposal-class-properties for class arrow functions
    require.resolve('@babel/plugin-proposal-class-properties'),
    // use babel-plugin-remove-graphql-queries to remove static queries from components when rendering in storybook
    require.resolve('babel-plugin-remove-graphql-queries'),
  ]

  // Prefer Gatsby ES6 entrypoint (module) over commonjs (main) entrypoint
  config.resolve.mainFields = ['browser', 'module', 'main']

  //Use loaders to handle typescript
  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    use: [require.resolve('awesome-typescript-loader')],
  })

  //Allow typescript files
  config.resolve.extensions.push('.ts', '.tsx')

  //Use loaders to handle scss
  config.module.rules.push({
    test: /\.scss$/,
    use: [
      'style-loader',
      'css-loader',
      'sass-loader',
      {
        loader: 'sass-resources-loader',
        options: {
          //shared variable files must be defined here, but only variables. css output will be repeated for every file
          resources: [require.resolve('../src/scss/_init.scss')],
        },
      },
    ],
  })

  // Copy gatsby/cache-dir/pages.json into gatsby/cache-dir/commonjs. This works
  // around an error in the gatsby module where pages.json is not found.
  const destination = join(dirname(require.resolve('gatsby')), 'pages.json')
  const source = join(dirname(dirname(destination)), 'pages.json')
  execSync(`copy ${source} ${destination}`)

  return config
}
```

**The error i get** - this is just a test from a pretty simple react component, built in typescript
```
./src/components/Footer/Footer.stories.tsx 6:72
Module parse failed: Unexpected token (6:72)
File was processed with these loaders: * ../node_modules/awesome-typescript-loader/dist/entry.js
You may need an additional loader to handle the result of these loaders.
| var react_1 = require("@storybook/react");
| var __1 = require("../");
> react_1.storiesOf('Footer', module).add('default', function () { return <__1.Footer />; });
| 
```

I'm not sure if the issue is coming from actually requiring additional loaders, of if the issue is being caused by the fact that this is set up inside of a yarn workspace so the theme isn't able to access the correct node modules (at least how i've set it up currently), or something else i haven't thought of.

The project itself runs fine. It's just the storybook command which doesn't work. The storybook enviroment begins running, but there are never any stories displayed.

[The only example i've found of using storybook with gatsby themes is this one](https://github.com/KatieFujihara/gatsby-storybook-theme), where it's used outside of the theme/site folders which doesn't look like component shadowing would work, and i can't find any other examples of this setup, so i'm looking for an explanation as much as i am a code fix to try and work out the best way of implementing this while allowing the benefits of both themes and storybook.

Thanks!

**Comment by danspratling** [comment]
I spent about 3 days scratching my head trying to figure out why this wasn't working for me, but i think my biggest problem was that i was trying to start up a theme using too many dependencies (it was already a starter i'd converted over using gatsby ofc, typescript, and a handful over other loaders which i believe were conflicting or at least causing unclear errors in storybook.

Instead, i decided to start from a minimum test scenario to see if i could get only gatsby, storybook and typescript working together. Then i would be able to debug any other loaders afterwards.

So i did the following.

### 1. Create a new theme, starting from a typescript theme template 
```gatsby new gatsby-theme-typescript-storybook https://github.com/maecapozzi/gatsby-theme-typescript```
This gives me a new gatsby project essentially forking from the above theme. Storybook doesn't exist yet.

### 2. Install storybook
We're just following the instructions here https://storybook.js.org/docs/guides/guide-react/
```npx -p @storybook/cli sb init --type react```
Great! Storybook is installed but isn't using typescript yet. If we create a story importing a .tsx file, we'll get this error `You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.` This is because storybook must be set up to load typescript files, exactly like react does (storybook is essentially it's own react project).

### 3. Allow storybook to import typescript files

**Comment by danspratling** [comment]
I spent about 3 days scratching my head trying to figure out why this wasn't working for me, but i think my biggest problem was that i was trying to start up a theme using too many dependencies (it was already a starter i'd converted over using gatsby ofc, typescript, and a handful over other loaders which i believe were conflicting or at least causing unclear errors in storybook.

Instead, i decided to start from a minimum test scenario to see if i could get only gatsby, storybook and typescript working together. Then i would be able to debug any other loaders afterwards.

So i did the following.

### 1. Create a new theme, starting from a typescript theme template
```gatsby new gatsby-theme-typescript-storybook https://github.com/maecapozzi/gatsby-theme-typescript```
This gives me a new gatsby project essentially forking from the above theme. Storybook doesn't exist yet.

### 2. Install storybook
We're just following the instructions here https://storybook.js.org/docs/guides/guide-react/
```npx -p @storybook/cli sb init --type react```
Great! Storybook is installed but isn't using typescript yet. If we create a story importing a .tsx file, we'll get this error You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. This is because storybook must be set up to load typescript files, exactly like react does (storybook is essentially it's own react project).

### 3. Allow storybook to import typescript files
For this, we can follow the instructions listed here https://www.gatsbyjs.org/docs/visual-testing-with-storybook/. Ie, we need to edit our `config.js` file to add in the gatsby specific storybook config options and add a `webpack.config.js` file so that storybook knows how to interpret gatsby components and typescript.
*it's worth noting that the stories default directory moves from `./stories` to `../src`. It works the same, just be aware that your root level stories folder won't work - i just dragged it inside of `src` for now.

### 4. Build a typescript component in the theme and create a story
I create two new files inside src/components/Button. `Button.tsx` and `Button.stories.tsx`. Inside `Button.tsx` I create a fairly straightforward button component
```import * as React from 'react'

interface PropTypes {
  children: string
}

const Button = ({ children }: PropTypes) => (
  <button className="btn btn-primary">{children}</button>
)

export { Button }```

And inside `Button.stories.tsx` I demo this button.

```import React from 'react'

import { storiesOf } from '@storybook/react'

import { Button } from './Button'

storiesOf('Button', module).add('button', () => <Button>Test button</Button>)
```
This works as expected, which is great - it means a typescript gatsby theme can handle storybook inside of that theme, and presumably shadowing would work this way too to import pre-built stories into sites (untested).

Unfortunately, this doesn't solve my issue so i'll keep digging.

**Comment by PsychedMagnet** [comment]
Hi! Man, this hits close to home! I recently got Storybook working with TypeScript (and Gatsby of course) for my personal website (it is still a private repo, and the code is still quite a mess). It truly was painful, so a theme like the one you are making is definitely needed. I will contact you via email and I will give you access to my repository to see the way I did it, hopefully it will help you!

**Comment by danspratling** [comment]
I've managed to narrow my issue down to it being the way I was importing scss files. I am using them in a modular manner and there's some discrepancy between the loaders I've got running in gatsby and the ones I've got running in storybook. Not loading scss files makes storybook work (which means I've set everything else up correctly), but atm it looks fine to me so I'm clearly missing or not seeing something important. At least I'm getting close now 🤞

**Comment by PsychedMagnet** [comment]
Are you using CSS modules? The issue I had was that my non-module CSS got bundled as a module and hashed all global classes. I managed to fix that though by telling it to bundle my global classes with their original names

**Comment by danspratling** [comment]
I'm using it in a very similar way to css modules, but i'm using sass and i'm not explicitly making them module files.

![image](https://user-images.githubusercontent.com/11349104/63838361-1c05a780-c975-11e9-9a30-cbed0bf42fcd.png)

```
import * as React from 'react'
import { Link } from '../../components'
const classNames = require('classnames')
import './Button.scss'

interface PropSettings {
  link: any
  className?: string
  children: string
}

const Button = ({ link, className, children }: PropSettings) => {
  const classes = classNames('button', className)

  return (
    <Link to={link.slug} className={classes} title={children}>
      <span className="button-text">{children}</span>
      {className !== undefined && className.includes('primary') ? (
        <span className="button-text clone">{children}</span>
      ) : null}
    </Link>
  )
}

export default Button
```

**Comment by PsychedMagnet** [comment]
Do you need to have so many plugins? Wouldn't it be better to provide a minimal Storybook functionality and leave the rest to the user of the theme? Or maybe I am missing something

**Comment by danspratling** [comment]
This is a different theme to the one i posted earlier. This is my own theme specifically for in-house, and won't be released to the public so the intention here is to keep as much reusable code inside the theme with sites sitting on top of that with as little code as possible. This won't be extended for other sites so can contain as many plugins as required.

**Comment by danspratling** [comment]
Going to close this. The issue is stale and although i haven't managed to fix it, it's not an issue specifically related to Gatsby or Storybook - but how a modular layout interacts with React and Storybook (which admittedly i had set up in a somewhat complex way). Stepping through and recreating this setup from scratch and applying the scss rules one by one would likely resolve the issue, but as it happens i'm moving to css-in-js for my future projects so this issue becomes redundant. Thanks for the help all.
