### ISSUE TITLE
import is not working correctly in mdx

### ISSUE THREAD

**Issue by csr632** [gatsbyjs/gatsby#16799]
## Description

When rendering with [MDXRenderer](https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/#make-a-template-for-your-posts), `import` in different `.mdx` **with same identifer name** will conflict.

I think this bug is caused by this line: https://github.com/gatsbyjs/gatsby/blob/43f29d94f639eb7f64cc4e175fd5f04aff1d47ca/packages/gatsby-plugin-mdx/loaders/mdx-scopes.js#L19
For example, `scope_ 0` and `scope_ 1` may have same property!

### Steps to reproduce

I reproduce this bug with "Gatsby Default Starter"
https://github.com/csr632/reproduce-gatsby-mdx-issue

### Expected result
`import` in different `.mdx` should not interfere each other.

### Actual result
They do.

### Environment
all

**Comment by ChristopherBiscardi** [comment]
closing in favor of #17119. Thanks for the report!
