### ISSUE TITLE
Building the site with webcomponents

### ISSUE THREAD

**Issue by amimas** [gatsbyjs/gatsby#16815]
## Description

I cannot find any docs on how to use/consume a webcomponent in Gatsby. Considering Gatsby is built on top of React, I didn't expect anything special required. When I import a webcomponent into a Gatsby page component, I'm able to see it work in develop mode but I can't build the site.

This is one of the article I followed regarding webcomponents in react:

https://medium.com/jens-jansson/start-using-web-components-in-react-6ccca2ca21f9

Obviously the webcomponent works following that guide, which is using `create-react-app`. I tried to follow the same steps in Gatsby, but couldn't successfully complete the section about "Put the polyfills into use".

I'm relatively new to webcomponents and Gatsby. Not sure exactly what I'm missing and couldn't find any docs/tutorials that shows webcomponents usage in Gatsby.

### Steps to reproduce

Below is a sample repo that was created with Gatsby hello-world starter.

https://github.com/amimas/webcomponent-gatsby

If I run `yarn start` from the repo, the index page displays a date-picker developped by vaadin as a webcomponent. I picked vaadin as an example here.

If I run `yarn build` from the repo, I get the following errors:

```
success run static queries - 0.016 s
success Building production JavaScript and CSS bundles - 6.042 s
success Rewriting compilation hashes - 0.022 s
success run page queries - 0.034 s — 1/1 103.28 queries/second

 ERROR #95313 

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html


> 1 | class Lumo extends HTMLElement {
    | ^
  2 |   static get version() {
  3 |     return '1.5.0';
  4 |   }


  WebpackError: ReferenceError: HTMLElement is not defined
  
  - version.js:1 Module../node_modules/@vaadin/vaadin-lumo-styles/version.js
    node_modules/@vaadin/vaadin-lumo-styles/version.js:1:1
  
  - sizing.js:1 Module../node_modules/@vaadin/vaadin-lumo-styles/sizing.js
    node_modules/@vaadin/vaadin-lumo-styles/sizing.js:1:1
  
  - vaadin-date-picker-overlay-styles.js:1 Module../node_modules/@vaadin/vaadin-date-picker/theme/lumo/vaadin-date-picker-overlay-styl    es.js
    node_modules/@vaadin/vaadin-date-picker/theme/lumo/vaadin-date-picker-overlay-styles.js:1:1
  
  - vaadin-date-picker.js:1 Module../node_modules/@vaadin/vaadin-date-picker/theme/lumo/vaadin-date-picker.js
    node_modules/@vaadin/vaadin-date-picker/theme/lumo/vaadin-date-picker.js:1:1
  
  - vaadin-date-picker.js:1 Module../node_modules/@vaadin/vaadin-date-picker/vaadin-date-picker.js
    node_modules/@vaadin/vaadin-date-picker/vaadin-date-picker.js:1:1
  
  - index.js:1 Module../src/pages/index.js
    src/pages/index.js:1:1
  

⠦ Building static HTML for pages
```

### Expected result

The site is built successfully and the webcomponent is functional

### Actual result

Cannot successfully build the site

### Environment

 ```
 System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 65.0
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.70 => 2.13.70 
  npmGlobalPackages:
    gatsby-cli: 2.7.27
```

**Comment by wardpeet** [comment]
Gatsby uses serverside rendering to build html files. Which means not all browser apis are available. Things like HTMLElement or window aren't set.

You'll have to lazily load data-picker.
```
import React, { useEffect } from "react";

export default () => {
  useEffect(() => {
    import('@vaadin/vaadin-date-picker');
  }, []);

    return (<div>
        <div>Hello world!</div>
        <vaadin-date-picker label="When were you born?"></vaadin-date-picker>
    </div>)
}
```

Thank you for opening this, @amimas

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
