### ISSUE TITLE
Gatsby develop not updating

### ISSUE THREAD

**Issue by tonyelpatron** [gatsbyjs/gatsby#16821]
## Description

After  setting up any gatsby starter and running gatsby develop, update function is not working when changing code

### Steps to reproduce

Install any starter and run gatsby develop

### Expected result

Gatsby should update live changes after changing code

### Actual result

Gatsby does not update, even after i run develop again, changes in code are not visible

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Safari: 12.1.2
  npmGlobalPackages:
    gatsby-cli: 2.7.30

**Comment by MKlblangenois** [comment]
I've had this problem several times and for some reason, the only solution I've found for the moment is to move the working folder to the desktop and start `gatsby build`.

**Comment by tonyelpatron** [comment]
> I've had this problem several times and for some reason, the only solution I've found for the moment is to move the working folder to the desktop and start `gatsby build`.

Thanks, but there should be a way to get this working properly right?

**Comment by dantereve** [comment]
Hi ! What kind of change are you trying to make ?  I have no issue with the latest node version and Gatsby-cli. I’ve used the blog starter. I’m going to try on your node version to check if i can reproduce your issue. 
Don’t you have any warning in Gatsby-cli or in developer console?
