### ISSUE TITLE
[gatsby-plugin-mdx] defaultLayouts should be defaultWrappers

### ISSUE THREAD

**Issue by ChristopherBiscardi** [gatsbyjs/gatsby#16848]
The `defaultLayouts` option is no longer accurate naming for MDX, which merged `layouts` and `wrappers` into the same thing in 1.0.

`defaultLayouts` should become `defaultWrappers` so as to align with mdx core and also avoid confusion with Gatsby page layouts.

We might also want take this opportunity to look at the gatsby-plugin-mdx options and re-evaluate if the API is still serving us well. Renaming would be a breaking change (even though we could have some backwards compat).

**Comment by johno** [comment]
At the very least I'd lean towards dropping `default{Layouts|Wrappers}.default`. It's a bit of a footgun because it seems to do what you "want" initially but as soon as you begin using MDX files as something other than an entrypoint (like a content section) you'll be suddenly surprised by having it pull along the layout.

I have found myself using this option very rarely these days. If you're already programmatically sourcing and creating pages from MDX you may as well introduce the layout at the template level. It's more explicit that way, too.

**Comment by ChristopherBiscardi** [comment]
I don't use `.default` myself either and I agree that it's a footgun as soon as you get any more complex than "my personal test site". I wonder if we can improve the targeting method for wrapper injection. It's basically only useful for `src/pages` so we should remove the wrapper injection from mdx-loader so that it doesn't apply to arbitrary `require`s I think. If you're requiring an MDX file you can always provide a wrapper replacement to it when you use it too, which typically happens in layout-type files.

> If you're already programmatically sourcing and creating pages from MDX you may as well introduce the layout at the template level. It's more explicit that way, too.

True. I wonder if we should remove the automatic `src/pages` support altogether. We could replace it with a filesystem source and `createPages` with some shadowing now that themes are plugins. This would also solve #16845 I think

```
// <site>/src/gatsby-plugin-mdx/templates/src-pages-layout.js

const MyWrapper = props => {
  
}
```

**Comment by cpboyd** [comment]
@ChristopherBiscardi Along the lines of `gatsby-plugin-layout`, is there any similar functionality with `gatsby-plugin-mdx`?

For example, I have a specific layout that I want applied to my entire site (so, obviously, `gatsby-plugin-layout` makes sense to avoid flickering when changing pages), however, there are certain posts that I want to have their own sub-navigation.

Currently, I'm including all the post info for all navigation at the top-level layout, but that's increasingly adding more and more data.

Is there a way that I could possibly achieve a nested layout with `gatsby-plugin-mdx` for different categories? (i.e. an actual default **layout** and not a wrapper)

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
