### ISSUE TITLE
[gatsby-image] art-directing with images of different proportions breaks the layout

### ISSUE THREAD

**Issue by tajchumber** [gatsbyjs/gatsby#16888]
## Description

`gatsby-image` art-directing with images of different proportions breaks the layout.
I want to show a portrait image on mobile and a landscape image on desktop, but gatsby-image keeps the portrait layout on desktop.

#### My GraphQL Query
```js
export const query = graphql`
  query {
    sadlers: file(relativePath: { eq: "sadlers-citrus-tide.jpg" }) {
      childImageSharp {
        fluid(maxWidth: 1400, quality: 100) {
          ...GatsbyImageSharpFluid_withWebp
          presentationWidth
        }
      }
    }
    sadlersMobile: file(
      relativePath: { eq: "sadlers-citrus-tide-ipad-pro.jpg" }
    ) {
      childImageSharp {
        fluid(maxWidth: 800, quality: 100) {
          ...GatsbyImageSharpFluid_withWebp
          presentationWidth
        }
      }
    }
  }
`
```

#### My Definition of the sources
```js
    const sources = [
      {
        ...data.sadlersMobile.childImageSharp.fluid,
        media: `(max-width: 768px)`,
      },
      {
        ...data.sadlers.childImageSharp.fluid,
        media: `(min-width: 769px)`,
      },
    ]
```

#### Using the sources
```js
<Img fluid={sorces} />
```

### Expected result

 - When the windows width is smaller that 768px it should show the smaller portrait image
 - When the windows width is biggern that 768px it should show the larger landscape image with the correct "proportions"

### Actual result

 - On small screens all is well
 - On desktop screens the image keeps the portrait proportions

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.31 => 2.13.31
    gatsby-background-image: ^0.8.3 => 0.8.3
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sass: ^2.1.3 => 2.1.3
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5
  npmGlobalPackages:
    gatsby-cli: 2.7.32
```

**Comment by kimbaudi** [comment]
@tajchumber - take a look at [Art-directing multiple images](https://www.gatsbyjs.org/packages/gatsby-image/#art-directing-multiple-images) section of the [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/) documentation. You can see that they don't set `media` for `data.mobileImage.childImageSharp.fluid` since it is the default.

So try to change your `sources` definition to the following: 

```
    const sources = [
      data.sadlersMobile.childImageSharp.fluid,
      {
        ...data.sadlers.childImageSharp.fluid,
        media: `(min-width: 769px)`,
      },
    ]
```

This should show a 800px wide `sadlers-citrus-tide-ipad-pro.jpg` when browser screen width is between 0 - 768px. And show a 1400px wide `sadlers-citrus-tide.jpg` when browser screen width is at least 769px or more.

Hope that helps 😃!

**Comment by kimbaudi** [comment]
@tajchumber - I just thought of something. I created an issue (https://github.com/gatsbyjs/gatsby/issues/17528) where art-directing might not work depending on the `media` key ordering. So you can just rearrange the `sources` array items so that it becomes like this:

```
    const sources = [
      {
        ...data.sadlers.childImageSharp.fluid,
        media: `(min-width: 769px)`,
      },
      {
        ...data.sadlersMobile.childImageSharp.fluid,
        media: `(max-width: 768px)`,
      },
    ]
```

Could you try that and let me know if that works?

**Comment by grgcnnr** [comment]
gatsby-image-wrapper sets an explicit width and height based on the souce. It looks like this doesn't always update when the media query changes.

a small example from a project i'm working on
```
<GatsbyImage
  fixed={[
     { ...md.fixed, media: `(min-width: 1000px)` },
     {...sm.fixed, media: `(max-width: 999px)`},
  ]}
 />
```
The attached image shows the problem.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/2694014/65086857-85725680-da07-11e9-967f-c51ea721ae81.png">


as you can see the correct image is being set at the appropriate media query but the wrapper (shown selected in the DOM inspector) is forcing the image to unnatural dimensions.

**Comment by grgcnnr** [comment]
see #16763

**Comment by meros** [comment]
Repro of this problem:

https://github.com/meros/gatsby-bug-repro-image-media-queries
