### ISSUE TITLE
Programmatically create pages from pages (.js files)

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#16959]
gatsby 2.13.70, react 16.9.0, w10

I'm trying to programmatically create pages instead of using the `gatsby-plugin-page-creator` plugin, but I can't

I guess it can't be done, but I prefer to ask

I'm using the same code as with `.mdx` posts, i.e.

```js
  // gatsby-node.js
  const PageTemplate = require.resolve(`./src/templates/page-query`)
  const pages = allPages.edges

  pages.forEach(({ node: page }, index) => {
    const { relativePath, id } = page
    createPage({
      path: relativePath,
      component: PageTemplate,
      context: {
        id: id,
      },
    })
  })
```

```js
// page-query.js
import { graphql } from 'gatsby'
import Page from '../components/page'

export default Page

export const query = graphql`
  query PageQuery {
    post_images: allFile(filter: { sourceInstanceName: { eq: "content/posts/images" } }) {
      edges {
        node {
          relativeDirectory
          childImageSharp {
            fluid(maxWidth: 1000, quality: 92) {
              originalName
              src
              ...GatsbyImageSharpFluid_noBase64
            }
          }
        }
      }
    }
    wallpapers: allFile(filter: { sourceInstanceName: { eq: "content/assets/wallpapers" } }) {
      edges {
        node {
          relativeDirectory
          childImageSharp {
            fluid(maxWidth: 5000) {
              originalName
              src
              ...GatsbyImageSharpFluid_noBase64
            }
          }
        }
      }
    }
  }
`
```

```js
// page.js
import React from 'react'

export default ({ location, data }) => {
  console.log('hey')
  return <>hey</>
}
```

But while this works (as it is copy&pasted from the theme-starter) with `.mdx` posts, it doesn't work with `.js` files

![image](https://user-images.githubusercontent.com/4474004/63508493-618c2580-c4da-11e9-832c-5b9d229736b8.png)

**Comment by danspratling** [comment]
Not sure I get what you're trying to do. Could you provide a breakdown of your steps and expected results? It sounds to me like you're trying to use pages as [templates](https://www.gatsbyjs.org/tutorial/part-seven/) but i'm not sure if this is correct

**Comment by kuworking** [comment]
With `mdx` files you grab them with graphQL and create pages with them by using a template, all done programatically in `gatsby-node.js`

I wanted to do the same with `js` files, instead of using `gatsby-plugin-page-creator`, but I couldn't when following the same recipe used for `mdx` files (and then the question)

But I didn't explore the plugin, now I've done it and I see that it uses a similar code (
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-page-creator/src/gatsby-node.js) so I guess it could be done

I close the issue, I should've inspected the plugin code before posting but somehow I didn't think of it (embarrassing)
