### ISSUE TITLE
gatsby new  gatsby-site fails with gyp error 

### ISSUE THREAD

**Issue by spicecoder** [gatsbyjs/gatsby#16969]
## Description
I am getting node_modules/oniguruma: Command failed- When I  run :  gatsby new cool/blogfornight   https://github.com/thomaswangio/gatsby-personal-starter-blog
 
### Steps to reproduce
Just try :  Step 1 of : https://www.gatsbyjs.org/tutorial/blog-netlify-cms-tutorial/
## Expected result
Expect a clean build .

### Actual result
Get Error in node-gyp  --error /Users/pronabpal/fivefridayfree/gatsbysite/blogsite/createdpersonal-blog/cool/blogfornight/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/pronabpal/fivefridayfree/gatsbysite/blogsite/createdpersonal-blog/cool/blogfornight/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.4.0 | darwin | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:290:12)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/anaconda3/bin/node" "/anaconda3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pronabpal/fivefridayfree/gatsbysite/blogsite/createdpersonal-blog/cool/blogfornight/node_modules/oniguruma
## Environment

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /anaconda3/bin/node
    Yarn: 1.17.3 - /anaconda3/bin/yarn
    npm: 6.9.0 - /anaconda3/bin/npm
  Languages:
    Python: 3.6.5 - /anaconda3/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.3.25 => 2.3.25 
    gatsby-image: ^2.0.39 => 2.0.39 
    gatsby-plugin-feed: ^2.1.1 => 2.1.1 
    gatsby-plugin-google-analytics: ^2.0.18 => 2.0.18 
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29 
    gatsby-plugin-netlify-cms: ^4.0.0 => 4.0.0 
    gatsby-plugin-offline: ^2.0.25 => 2.0.25 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
    gatsby-remark-copy-linked-files: ^2.0.11 => 2.0.11 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-remark-vscode: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.0.29 => 2.0.29 
    gatsby-transformer-remark: ^2.3.8 => 2.3.8 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18 
  npmGlobalPackages:
    gatsby-cli: 2.7.37

**Comment by jonniebigodes** [comment]
@spicecoder it seems that you have python 3.x installed and nodegyp which is a dependency for some of the plugins you're using requires python v2.7. More on that [here](https://github.com/nodejs/node-gyp#node-gyp---nodejs-native-addon-build-tool)

**Comment by Paelsis** [comment]
Happens to me as well, I cannot get the blog to work without the gyp ERR and I have the latest version of OS-X, just upgraded.

**Comment by kolstadmagnus** [comment]
> Happens to me as well, I cannot get the blog to work without the gyp ERR and I have the latest version of OS-X, just upgraded.

Help, did you get this to work? I've downloaded Xcode (I didn't have it on my machine) and reinstalled the Command-line tools, but I still get the error :(
