### ISSUE TITLE
Emotion theme is empty when importing component outside the Gatsby root

### ISSUE THREAD

**Issue by moroshko** [gatsbyjs/gatsby#16963]
I'm building a component library alongside a Gatsby demo website. The component library is styled with Emotion + theming.

Here is the basic folder structure I have:
```
src
  components
    button.js
website
  src
    components
      layout.js
    pages
      index.js
```

My problem is that the button doesn't get the theme (the theme appears to be `{}`).

However, if I move the button to `website/src/components`, the theme gets to the button as expected.

See repro [here](https://github.com/moroshko/gatsby-emotion-theme-issue).

What am I missing here?

**Comment by jgatjens** [comment]
@moroshko did you resolve your problem?
