### ISSUE TITLE
Sharing Fragments Across Workspaces

### ISSUE THREAD

**Issue by nadrane** [gatsbyjs/gatsby#16970]
## Summary
We have a project that where we are trying to use Yarn workspaces. The idea is to have 3 separate workspaces:

1. `Gatsby Website #1`
2. `Gatsby Website #2`
3. `Shared Components`

We have two Gatsby websites that share about 80% of their content. Thus, we want to be able to share our our code between them. We are currently running into an issue when executing `createPage` in our `gatsby-node` file for `Gatsby Website #1`. 

The template passed to `createPage` is defined in our` Shared Components` workspace. The GraphQL query associated with this template uses a fragment also defined in the `Shared Components` workspace. We're getting an error when running `gatsby develop` because Gatsby never discovered this fragment when it reviewed our source code. And how would it... At the moment we aren't even importing anything from the `Shared Components` workspace in `Gatsby Website #1`

Is there a way to instruct Gatsby to find this fragment from `Shared Components`? Does it just follow the dependency chain defined in imports?
I know that `gatsby-image`(or one of the sharp dependencies) defines fragments that are visible to my project. Is that much different than defining a fragment in a separate workspace? 

Any guidance would be appreciated.

Thank you

### Environment (if relevant)
```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.9.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.3.23 => 2.10.5
    gatsby-image: ^2.2.12 => 2.2.12
    gatsby-plugin-manifest: ^2.2.6 => 2.2.6
    gatsby-plugin-offline: ^2.0.25 => 2.2.0
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.0
    gatsby-plugin-recaptcha: ^1.0.5 => 1.0.5
    gatsby-plugin-remote-images: ^1.0.5 => 1.0.5
    gatsby-plugin-sass: ^2.0.11 => 2.1.0
    gatsby-plugin-sharp: ^2.2.16 => 2.2.16
    gatsby-plugin-styled-components: ^3.0.7 => 3.1.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-contentstack: ^1.0.2 => 1.0.2
    gatsby-source-graphql: ^2.0.15 => 2.1.0
    gatsby-source-vimeo: ^1.1.8 => 1.1.8
    gatsby-transformer-sharp: ^2.2.10 => 2.2.10
```

**Comment by nadrane** [comment]
We ended up using a somewhat crazy hack to solve this:

We got this from `gatsby-transformer-sharp`

```exports.onPreExtractQueries = async ({ store, getNodesByType }) => {
  const program = store.getState().program

  // Check if there are any ImageSharp nodes. If so add fragments for ImageSharp.
  // The fragment will cause an error if there are no ImageSharp nodes.
  if (getNodesByType(`ImageSharp`).length == 0) {
    return
  }

  // We have ImageSharp nodes so let's add our fragments to .cache/fragments.
  await fs.copy(
    require.resolve(`gatsby-transformer-sharp/src/fragments.js`),
    `${program.directory}/.cache/fragments/image-sharp-fragments.js`
  )
}```

I'd love to know if there's a cleaner way

**Comment by lucashfreitas** [comment]
+1 @nadrane . 

I am having the same issue using yarn workspaces. 

I am also having this bug when trying to execute graphQL queries from shared module: 

![image](https://user-images.githubusercontent.com/11416392/64662263-dfb96780-d49b-11e9-8eab-d8cb6f31c9cf.png)

**Comment by lucashfreitas** [comment]
It sounds that gatsby does not recognize any fragment which is outside from "src" folder. 

Apparently is also not possible to use staticQuery outside of src folder. 

Will try to use the same workaround with gatsby-transformer-sharp.

Thanks for sharing :)

**Comment by wardpeet** [comment]
Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by LekoArts** [comment]
I think I also left this comment on our [Discord server](https://discord.gg/gatsby), but I'd encourage you to try using [Gatsby Themes](https://www.gatsbyjs.org/docs/themes/). I think these will solve the problems you have.

**Comment by lucashfreitas** [comment]
Thanks, @LekoArts.

I did some changes and using my shared workspace now as a Theme and everything is working fine.

@nadrane,  I think if you use your shared workspace as a theme everything will work fine as well.

@wardpeet Maybe we need to recommend users to use a theme instead investigating this issue???

**Comment by wardpeet** [comment]
Mostly the problem lies in shared components not being transpiled, Themes are special in Gatsby and they are getting transpiled correctly. For non themes packages we suggest using https://www.gatsbyjs.org/packages/gatsby-plugin-compile-es6-packages/ to compile your package.
