### ISSUE TITLE
Improve sharp upgrade experience when libvips is upgraded

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#16985]
Currently upgrading `gatsby-plugin-sharp` (or rather its dependency `sharp`) when there is a version change to the underlying libvips dependency is a little problematic because it fails with https://github.com/gatsbyjs/gatsby/issues/16957 unless an `npm rebuild` is run. 

@lovell had some lovely recommendations in https://github.com/lovell/sharp/issues/1680#issuecomment-487701749 on how to tackle this. 

We have to some extent in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/safe-sharp.js but it appears that we'll have to handle this corner case as well 

CC @pieh

**Comment by kuworking** [comment]
If working with `yarn workspaces`, I have 

```
yarn list --pattern sharp
yarn list v1.19.0
├─ gatsby-plugin-sharp@2.3.0
├─ gatsby-transformer-sharp@2.3.5
└─ sharp@0.23.2
```

And `gatsby-node` with

```
const sharp = require('sharp')
sharp.cache(false)
sharp.simd(false)
```

1. Running `npm rebuild` and/or `yarn --force` (the equivalent that should work for workspaces?) doesn't allow `gatsby build` to succeed (after deleting all `node_modules`)

```
 [====================----------] 13710/20646 439.4 s 66% Generating image thumbnailsException code=0xc0000005 flags=0x0 at 0x0000000000000000. Access violation - attempting to execute data at address 0x0000000000000000
error Command failed with exit code 3221225477.
```

2. Running `yarn --force` with 

```
"resolutions": {
    "sharp": "0.22.1"
  }
```

doesn't prevent yarn to install sharp `0.23.2`, and running with or without the `resolutions` part doesn't change the `build` output, identical to the previous one

3. Downgrading to 
```
"gatsby-plugin-sharp": "2.2.14",
```

creates divergences in the different packages of the workspace

```
yarn list --pattern sharp
yarn list v1.19.0
├─ gatsby-plugin-sharp@2.2.14
│  └─ sharp@0.22.1
├─ gatsby-theme-A@0.1.43
│  └─ gatsby-plugin-sharp@2.3.0
├─ gatsby-transformer-sharp@2.3.5
├─ sharp@0.23.3
└─ site@0.1.71
   └─ gatsby-plugin-sharp@2.3.0
Done in 0.84s.
```

So I also downgrade 

```
"gatsby-plugin-manifest": "2.1.1",
"gatsby-transformer-sharp": "2.2.6",
```

delete `node_modules` and `yarn-lock` and run `yarn --force` again

which gives me

```
yarn list --pattern sharp
yarn list v1.19.0
├─ gatsby-plugin-sharp@2.2.14
├─ gatsby-transformer-sharp@2.2.6
└─ sharp@0.22.1
```

and then, `build` fails with a different message

```
Error: Cannot find module 'gatsby/dist/utils/create-content-digest'
```

And now I don't know what else can I try
