### ISSUE TITLE
[docs] improve Recipe readability

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#16980]
## Summary

We've added lots of actionable details recently to the [docs recipes](https://gatsbyjs.org/docs/recipes) page, but that also means it's getting extremely long (and we're not done yet!). Even with the floating table of contents, the page can get hard to navigate. This issue is meant to act as a brainstorming area for user interface improvements that allow learners to isolate the page on specific recipes they're interested in.

A couple ideas I have are:

- A collapsible accordion toggle interface with show all / hide all buttons
- Deep-linked recipe filtering to isolate to a single recipe somehow

If anyone else has ideas, add them here!

**Comment by thecodingaviator** [comment]
I guess we could use fancy `<detail>` `<summary>` tags to do that, if not, we could link the floating scroll to the page so that it moves side by side as the page is scrolled

**Comment by kevee** [comment]
Thoughts as I have been adding things to the Recipe page:

The length of the page also introduces problems with heading depth, especially as H5s are currently almost exactly the same weight and size as body text.

I have had issues with the past with accordions in long documents, especially when linking to anchors within a collapsed area, or when users use in-page find (command+F) to search a long document and the text is not visible.

Automatically-generated anchor links in headings is a fragile way to maintain a canonical link to a section, as there is less editorial friction with changing headings vs. page titles. This is especially true as lots of recipes use the same heading that get auto-appended with numbers (i.e. "Prerequisites"), so a link to #prerequisites-4 might change topics from one revision to the next.

Could the recipes be simply broken up into separate pages?

**Comment by kevee** [comment]
Another idea: change the Recipe page into a [shorter landing page](https://github.com/kevee/gatsby/blob/docs/recipe-page-format/docs/docs/recipes.md) and move the main sections out to separate pages. 

![image](https://user-images.githubusercontent.com/270536/64269428-3e1c9e00-cf10-11e9-8ac6-340e892d4d2d.png)

**Comment by marcysutton** [comment]
I think that's a great idea, and a very straight-forward solution. I'd be in favor of making that happen!

**Comment by kevee** [comment]
@marcysutton - Should I wait for a few of the other PRs to come in for Recipes then do a bigger 'meta' PR on this one?

**Comment by muescha** [comment]
Many receipes per topic or one file per receipt?

### Suggestion: Receipts Database

I would suggest to have a data structure with one Markdown file per receipt

Then we can enhance them with tags and list them under different topics twice
Also make them deep linkable with a single view

If we include a teaser then we can compact the generated topic subpages to display only the teaser

I think with the receipts we can use the power of the Gatsby graphql 😄
And we can use some of the existing showcase/starter infrastructure a little bit

**Comment by kevee** [comment]
I think a content audit followed by a new approach with a different data structure is a good direction. However, such a project might take some time, and as it stands the Recipe page is getting long. 

Can we break them apart quickly now and open an issue to track the idea of a recipe database?

**Comment by marcysutton** [comment]
My recommendation is to break up the recipes by topic, so that people can compare and contrast different techniques in the same category. We are not going to create a tagged database at this time -- it's outside of the scope of this issue.

**Comment by kevee** [comment]
Agreed, I've been buried in other projects for a few weeks but I'll get on a PR early next week.

**Comment by muescha** [comment]
Hi Mr. @Gatsbot - @keeve is in process with #18922

**Comment by marcysutton** [comment]
Closed with #20113.
