### ISSUE TITLE
Unable to run GraphQL Playground.

### ISSUE THREAD

**Issue by isubhokarma** [gatsbyjs/gatsby#16999]
**I'm unable to run GraphQL Playground with the latest update.**
Repeating the following steps: https://www.gatsbyjs.org/docs/using-graphql-playground/

**Please Help ASAP.**

**Comment by LekoArts** [comment]
Working for me to following the instructions, closing this issue. Please reply if you need further help, it seems your local setup is wrong!

**Comment by ernestoalfredo13** [comment]
Hello, im having the same issue, i already did npm cache verify, npm install --save core-js@^3 (it seems it was outdated), npm outdated inside proyect folder and everything is fine, and i'm following step by step this guide:

https://www.gatsbyjs.org/docs/using-graphql-playground/

and also the video about the great gatsby bootcamp, both options "cross-env" and "env-cmd" give me the same error described above from the .log file, i also tried the .env.development solution but still same error

10 silly lifecycle gatsby-starter-hello-world@0.1.0~develop: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'cross-env GATSBY_GRAPHQL_IDE=playground gatsby develop'
10 silly lifecycle ]
11 silly lifecycle gatsby-starter-hello-world@0.1.0~develop: Returned: code: 1  signal: null
12 info lifecycle gatsby-starter-hello-world@0.1.0~develop: Failed to exec develop script
13 verbose stack Error: gatsby-starter-hello-world@0.1.0 develop: `cross-env GATSBY_GRAPHQL_IDE=playground gatsby develop`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid gatsby-starter-hello-world@0.1.0
15 verbose cwd C:\Users\YoMePiro\hello-world
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "develop"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error gatsby-starter-hello-world@0.1.0 develop: `cross-env GATSBY_GRAPHQL_IDE=playground gatsby develop`
22 error Exit status 1
23 error Failed at the gatsby-starter-hello-world@0.1.0 develop script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jonniebigodes** [comment]
@ernestoalfredo13 i just tested and it's working for me, also running windows 10. Created a new Gatsby site with with hello world starter, added `cross-env` as you can see below by the truncated package.json file contents:

```json
"scripts": {
    "build": "gatsby build",
    "develop": "cross-env GATSBY_GRAPHQL_IDE=playground gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "dependencies": {
    "gatsby": "^2.19.7",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  },
  "devDependencies": {
    "cross-env": "^7.0.0",
    "prettier": "^1.19.1"
  },
```

Issued `yarn develop` and i'm presented with:

![ernesto_1](https://user-images.githubusercontent.com/22988955/75598044-0e9ab880-5a91-11ea-8aea-d73b4774d8ec.png)

Same exact npm and node versions
