### ISSUE TITLE
[gatsby-image] Bad schema typing for gatsby-images ?

### ISSUE THREAD

**Issue by slorber** [gatsbyjs/gatsby#17003]
Hi,

The TS defs for a fluid image is:

```tsx
export interface FluidObject {
  aspectRatio: number
  src: string
  srcSet: string
  sizes: string
  base64?: string
  tracedSVG?: string
  srcWebp?: string
  srcSetWebp?: string
  media?: string
}
```

Yet if we look at a graphql image fragment like this one, we can notice they are actually incompatible:

![image](https://user-images.githubusercontent.com/749374/63606583-b4480900-c5d0-11e9-9a36-54dc513158fb.png)

The GraphQL schema says that all those attributes can be undefined (which does not really make sense to me, is it possible to have an image without at least an src?)

The problem is that if you try to generate typedefs from generic queries, you'll end up with incompatible typings and will have to find workarounds (like using "any").

Otherwise you'll get typescript errors like this:

```
[0] src/page/home/queries/Images.tsx(54,3): error TS2322: Type 'Pick<ImageSharpFluid, "src" | "sizes" | "srcSet" | "aspectRatio" | "tracedSVG" | "srcWebp" | "srcSetWebp">[]' is not assignable to type 'Pick<FluidObject, "media" | "src" | "base64" | "sizes" | "srcSet" | "tracedSVG" | "srcWebp" | "srcSetWebp">[]'.
[0]   Type 'Pick<ImageSharpFluid, "src" | "sizes" | "srcSet" | "aspectRatio" | "tracedSVG" | "srcWebp" | "srcSetWebp">' is not assignable to type 'Pick<FluidObject, "media" | "src" | "base64" | "sizes" | "srcSet" | "tracedSVG" | "srcWebp" | "srcSetWebp">'.
```

I suggest to make those types compatible so that people using tools like graphql-codegen can easily use gatsby images

**Comment by daugsbi** [comment]
I experience the same problem with TypeScript generation.
Also relevant for gatsby-source-contentful, as well as the FixedObject.

Instead of weaken the types of gatsby-image, this should be addressed in the schema. As a result we can distinguish between fluid and fixed object and get a type error when used wrong.

**Comment by slorber** [comment]
Yeah, not really for weakening the types either :)

I'd rather have gatsby image being a graphql union type and being more precise on the schema typings, like `union ImageSharpFluid = ImageSharpFluidWithSVG | ImageSharpFluidWebp | ...`

**Comment by daugsbi** [comment]
Not stale

**Comment by bsgreenb** [comment]
Can we re-open?  Not stale.

**Comment by Kerumen** [comment]
Stumbled upon the same problem today. I think this should be reconsidered..

**Comment by daugsbi** [comment]
Not so spooky anymore :ghost: 

Please review my pull request which should resolve the problem for Contentful and ImageSharp
