### ISSUE TITLE
[gatsby-remark-images] Blurred image does not disappear on initial page load in development mode

### ISSUE THREAD

**Issue by dkthehuman** [gatsbyjs/gatsby#17017]
## Description

[gatsby-remark-images] does not hide the blurred image on initial page load in development mode

### Steps to reproduce

Demo:
- Repo: https://github.com/dkthehuman/gatsby-blur-bug-demo
- Netlify: https://pedantic-noether-8663b2.netlify.com (note that the bug is not reproducible here as it only affects development mode)

Note that this bug only appears in development mode (`gatsby develop`), not in production (`gatsby build && gatsby serve`)

1. Clone the repo and run `gatsby develop`
2. Click on "Hello world" to view the test blog post
3. Note that when the image is loaded, the blurred image behind it disappears with opacity set to 0 (as expected)
4. Refresh the page

### Expected result

The blurred image should disappear when the real image is loaded

<img width="620" alt="Screen Shot 2019-08-23 at 7 17 11 PM" src="https://user-images.githubusercontent.com/535248/63630157-7c938e00-c5dd-11e9-8b8f-84dc9bdaba22.png">

### Actual result

The blurred image remains when the real image is loaded. This is not a problem the real image fully covers the blurred image, but is very noticeable when the real image includes transparent sections.

<img width="611" alt="Screen Shot 2019-08-23 at 7 17 18 PM" src="https://user-images.githubusercontent.com/535248/63630158-81584200-c5dd-11e9-8439-3f04647aca3b.png">

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    npm: 6.11.0 - /usr/local/bin/npm
  Languages:
    Python: 3.7.4 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0
    Safari: 12.1.2
  npmPackages:
    gatsby: 2.13.80 => 2.13.80
    gatsby-image: 2.2.13 => 2.2.13
    gatsby-plugin-sharp: 2.2.17 => 2.2.17
    gatsby-remark-images: 3.1.17 => 3.1.17
    gatsby-source-filesystem: 2.1.16 => 2.1.16
    gatsby-transformer-remark: 2.6.19 => 2.6.19
    gatsby-transformer-sharp: 2.2.11 => 2.2.11
  npmGlobalPackages:
    gatsby-cli: 2.7.33

**Comment by dkthehuman** [comment]
Although this is probably low-priority as it doesn't affect production builds, I still wanted to report it because not being able to trust what's rendered under `gatsby develop` results in an unreliable development experience.

**Comment by kennethvandenberghe** [comment]
I think this is a duplicate of https://github.com/gatsbyjs/gatsby/issues/17007 ?

**Comment by glennreyes** [comment]
In #17007 it happens only in production. So I think it’s related but not quite the same.

**Comment by dkthehuman** [comment]
Hey @glennreyes, thanks for submitting your PR! I'd like to test to see whether your changes fixes this problem, but I'm having a bit of trouble figuring out how to set it up as I'm not too familiar with setting up dependencies.

Do you know how I could get my site to use your version of `gatsby-image` rather than the one published on NPM?

**Comment by wardpeet** [comment]
The new version is on NPM `gatsby-image@2.2.15`

**Comment by dkthehuman** [comment]
Thanks @wardpeet.

I updated my test repo (https://github.com/dkthehuman/gatsby-blur-bug-demo) to use `gatsby-image@2.2.15` and unfortunately, this bug is still present.

**Comment by kimbaudi** [comment]
I am also facing this issue on my local machine during development (but not during production). This seems to happen whenever I go to a page and refresh the page (`Ctrl + R`). 

![issue1](https://user-images.githubusercontent.com/1864092/64468937-30694300-d0df-11e9-8533-75fe4fda1b90.png)

![issue2](https://user-images.githubusercontent.com/1864092/64468940-32330680-d0df-11e9-80da-6e5c91c52910.png)

I also find this to be very noticeable when the real image includes transparent sections as you can see from the screenshots.

I've created a PR (https://github.com/gatsbyjs/gatsby/pull/17154) that tries to address issues with transparent images by disabling the background-image css property that is causing the blurry background image.

**Comment by AngelinCalu** [comment]
This is still an issue.
