### ISSUE TITLE
tutorial part zero: Can't connect to localhost:8000

### ISSUE THREAD

**Issue by saritchi** [gatsbyjs/gatsby#17042]
## Description
```

0 pages                                                                                       gatsby-starter-hello-world

 ERROR

UNHANDLED REJECTION request to http://localhost:8000/___graphql failed, reason: connect ECONNREFUSED 127.0.0.1:8000



  FetchError: request to http://localhost:8000/___graphql failed, reason: connect ECONNREFUSED 127.0.0.1:8000

  - index.js:1455 ClientRequest.<anonymous>
    [hello-world]/[gatsby]/[node-fetch]/lib/index.js:1455:11

  - destroy.js:91 emitErrorNT
    internal/streams/destroy.js:91:8

  - destroy.js:59 emitErrorAndCloseNT
    internal/streams/destroy.js:59:3

  - task_queues.js:77 processTicksAndRejections
    internal/process/task_queues.js:77:11

```
### Steps to reproduce

Following the guide https://www.gatsbyjs.org/tutorial/part-zero/. At the step where you input `gatsby develop` to the terminal.

### Expected result

Should see Hello World! on localhost:8000

### Actual result

Compile is successful but can not connect to localhost:8000

### Environment

`  System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.9.0 - /home/linuxbrew/.linuxbrew/bin/node
    npm: 6.10.3 - /home/linuxbrew/.linuxbrew/bin/npm
  npmGlobalPackages:
    gatsby-cli: 2.7.39`

**Comment by sidharthachatterjee** [comment]
Do you have a proxy running? Please link to a minimal reproduction repo of this.

**Comment by saritchi** [comment]
I do not have a proxy running. This is my first time ever using Gatsby so I do not know how I would make a minimal reproduction using it.  In addition, the page on gatsbyjs.org which explains how to do make this min. reproduction suggests using the `hello-world` starter... which is what I am having trouble with.

I've been following all the steps in tutorial zero with no issues up until I had to use `gatsby develop`. There was no issues compiling hello-world, and the results were similar to the gif shown on that tutorial page, but with the addition of ERROR code segment (in _Description_).

**Comment by danspratling** [comment]
Have you tried running on a different port? If you add `-p 8001` to your develop script in `package.json` you should be able to change the port you're running on. This is a guess but i think it's conflicting with something else.

Also, what happens when you run `yarn build && yarn serve`?

**Comment by jonathanprozzi** [comment]
Hello @saritchi -- Are you still having this issue? It seems like what you're experiencing may be similar to [Issue #16728 ](https://github.com/gatsbyjs/gatsby/issues/16728) and it looks like they were able to resolve it.

**Comment by mhirst** [comment]
Thanks @danspratling! That did the trick for me.
