### ISSUE TITLE
[gatsby-transformer-remark] Is there a way to access node.html in onCreateNode?

### ISSUE THREAD

**Issue by problem233** [gatsbyjs/gatsby#17045]
## Summary

`node.html` of `MarkdownRemark` nodes are undefined in `onCreateNode`. Is there a way to access it?

## Relevant information

There are some relevant issues: #2991 #6314, but both of them are not resolved and closed.

### Environment (if relevant)

Irrelevant.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`:
```javascript
exports.onCreateNode = async ({ node }) => {
  if (node.internal.type === 'MarkdownRemark') {
    console.log(typeof node.html) // => undefined
  }
}
```
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by stefanprobst** [comment]
`gatsby-transformer-remark` generates the html from markdown not immediately when creating the `MarkdownRemark` nodes, but lazily when the `html` field resolver is called in a query. This means that the html is not yet available in `onCreateNode`.

What are you trying to achieve? There might be another way to do it.

**Comment by problem233** [comment]
I tried to encrypt the html in a new node, and then decrypt in the browser.

**Comment by problem233** [comment]
I found a tricky solution: create a resolver for the encrypted field, and use `nodeModel.runQuery` in the resolver with a filter on `html` field to force `html` to be resolved.

**Comment by stefanprobst** [comment]
cool, great solution! :+1:

**Comment by Chalarangelo** [comment]
@problem233 Can you provide a sample of the code? I want to do something reasonably similar in my project.

**Comment by problem233** [comment]
@Chalarangelo Here is a better way to get the resolver: 
```javascript
// gatsby-node.js
exports.createResolvers = await ({ createResolvers }) => createResolvers({
  SomeType: {
    someField: {
      resolve: async (source, _, context, info) => {
        const resolver = info.schema.getType("MarkdownRemark").getFields()["tableOfContents"].resolve
        const node = await context.nodeModel.getNodeById(id)
        const args = {} // arguments passed to the resolver
        const toc = await resolver(node, args)
        return toc
      }
    }
  }
})
```

**Comment by ciokan** [comment]
Tried to do something similar (resolving the html field of remark) but my code fails with:

```
"TypeError: Cannot read properties of null (reading 'internal')",
          "    at htmlCacheKey (/usr/app/node_modules/gatsby-transformer-remark/extend-node-type.js:63:71)",
          "    at getHTML (/usr/app/node_modules/gatsby-transformer-remark/extend-node-type.js:366:42)",
          "    at resolver (/usr/app/node_modules/gatsby-transformer-remark/extend-node-type.js:506:18)",
          "    at wrappedTracingResolver (/usr/app/node_modules/gatsby/src/schema/resolvers.ts:683:20)",
```

resolver code:

        Post  : {
			html      : {
				resolve: async (source, _, context, info) => {
					const resolver = info.schema.getType("MarkdownRemark").getFields()["html"].resolve;
					const node = await context.nodeModel.getNodeById(source.id);
					const args = {};
					return await resolver(node, args, context, info);
				}
			}

Filtering based on `html` field does not seem to trigger it any more. I'm out of options here, any ideas?
