### ISSUE TITLE
filter Graphql result by a Date variable

### ISSUE THREAD

**Issue by moelfassi** [gatsbyjs/gatsby#17041]
## Summary
to get data from my DataBase i'm using graphql  this is my query:

```
export const querymk = graphql`
     query HomePageQuery {
      allMongodbAppsOneapps (
         filter : { my_time: { eq : "2019-08-21T12:35:56.863Z" }}
  )  {
    nodes {
      id
      my_time(formatString: "DD MMMM YYYY")
      text {
        title
        developer
        icon
      }
    }
  }
}
`
```

this is working fine.. but i need to replace my filter : eq : "2019-08-21T12:35:56.863Z" by a Date variable..

**Comment by LekoArts** [comment]
You can use `context` to pass variables to page queries and queries in template files. Or what are you asking for?

**Comment by wardpeet** [comment]
here is a tutorial on how you can add variables to queries. It's talking about how to do programmatic pages but it also uses pageContext & query variables.

https://www.gatsbyjs.org/docs/programmatically-create-pages-from-data/

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
