### ISSUE TITLE
Cannot query field "siteMetadata" on type "Site"!

### ISSUE THREAD

**Issue by syncatallah** [gatsbyjs/gatsby#17058]
## Description
I am trying `useSiteMetadata` hook implemented [there](https://github.com/jlengstorf/authoring-gatsby-themes/blob/master/gatsby-theme-events/src/hooks/use-site-metadata.js) which returns 
site meta data using `useStaticQuery` gatsby hook. When I consume this hook in my components, first it throws:
```js
ERROR #85907  GRAPHQL
There was an error in your GraphQL query:
- Unknown field 'siteMetadata' on type 'Site'.
File: src/hooks/use-site-metadata.js
```

and in my component: 
```js 
error  Cannot query field "siteMetadata" on type "Site"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./src/components/layout.js 13:0-57 17:13-28 24:10-25
 @ ./src/templates/events.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
```
I checked many open issues here, trying to import `graphql` as following: 
```js
import graphql from "graphql";
import { useStaticQuery } from "gatsby";
``` 
instead of 

```js
import { graphql, useStaticQuery } from "gatsby";
``` 
But this is only eliminating the `GRAPHQL` error and still throws: 
```js
error  Cannot query field "siteMetadata" on type "Site"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./src/components/layout.js 13:0-57 17:13-28 24:10-25
 @ ./src/templates/events.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
```
### Steps to reproduce
- In your gatsby theme directory create a file name `hooks/use-site-meta-data.js` with the following content:
```js 
import graphql from 'graphql'
import { useStaticQuery } from 'gatsby'

const useSiteMetadata = () => {
  const data = useStaticQuery(graphql`
    query {
      site {
        siteMetadata {
          title
          headline
          basePath
        }
      }
    }
  `)

  return data.site.siteMetadata;
}

export default useSiteMetadata;
```
- consume the hook in your components e.g., layout component: 
```js
import useSiteMetadata from '../hooks/use-site-metadata';
``` 
- run 
```bash
gatsby develop
```
### Expected result
The theme should be compiled successfully as there is no conflict between the wrapped code above  and the docs! 
### Actual result
```js
error  Cannot query field "siteMetadata" on type "Site"  graphql/template-strings
```
### Environment

```bash 
System:
  OS: Linux 5.0 Pop!_OS 18.04 LTS
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Shell: 5.4.2 - /usr/bin/zsh
Binaries:
  Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
  Yarn: 1.17.3 - /usr/bin/yarn
  npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
Languages:
  Python: 2.7.15+ - /usr/bin/python
Browsers:
   Chrome: 76.0.3809.100
   Firefox: 68.0.1
npmGlobalPackages:
   gatsby: 2.13.76
```

**Comment by stefanprobst** [comment]
Do you have a `siteMetadata` field in your `gatsby-config.js`?

Also, you should always import `graphql` from `gatsby`, not directly from `graphql`.

**Comment by syncatallah** [comment]
> Do you have a `siteMetadata` field in your `gatsby-config.js`?
> 
> Also, you should always import `graphql` from `gatsby`, not directly from `graphql`.

Yes I do it in `gatsby-config.js` there is `siteMetadata` in the exported function!
I know but, as I mentioned I tried it as someone said that it could solve the problem!

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

---

On a related note: I use this pattern on nearly all themes of my repo https://github.com/LekoArts/gatsby-themes and it works without problems.

[reproduction]: https://gatsby.dev/reproduction

**Comment by syncatallah** [comment]
> Hi!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.

It's working now after I started a new project as described in [minimal reporduction](https://gatsby.dev/reproduction). Don't know what is the problem with the published theme [there](https://github.com/jlengstorf/authoring-gatsby-themes/blob/master/gatsby-theme-events/src/hooks/use-site-metadata.js).

> 
> Thanks for using Gatsby! 
> 
> On a related note: I use this pattern on nearly all themes of my repo https://github.com/LekoArts/gatsby-themes and it works without problems.

Thanks for the note!
