### ISSUE TITLE
Gatsby site throws an error when I delete a markdown (mdx, md) file from the folder

### ISSUE THREAD

**Issue by jnsrikanth** [gatsbyjs/gatsby#17079]
## Description

I have a basic blog setup using gatsbyjs with support for .md and .mdx markdown files for blogging. When I delete a markdown file, the site throws an error and stops.
### Steps to reproduce

I go to the blog folder in the site root / and delete a random .mdx or .md file.

### Expected result

What should happen?
I expect to see the blog removed from the main blog list on the home page of the gatsby site.

### Actual result

What happened.
It resulted in the site stopping and throwing an error on the site page as follows.

![blog-markdown-deletion-error](https://user-images.githubusercontent.com/17452662/63663753-4aeb1480-c7e1-11e9-88ff-0d1ce0d909f2.PNG)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/SmartTechies/.windows-build-tools/python27/python
  npmPackages:
    gatsby: ^2.13.50 => 2.13.67
    gatsby-image: ^2.2.8 => 2.2.8
    gatsby-plugin-manifest: ^2.2.5 => 2.2.5
    gatsby-plugin-mdx: ^1.0.0 => 1.0.24
    gatsby-plugin-offline: ^2.2.4 => 2.2.6
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sharp: ^2.2.9 => 2.2.12
    gatsby-remark-images: ^3.1.12 => 3.1.12
    gatsby-source-filesystem: ^2.1.8 => 2.1.9
    gatsby-transformer-mdx: ^1.1.2 => 1.1.2
    gatsby-transformer-remark: ^2.6.14 => 2.6.14
    gatsby-transformer-sharp: ^2.2.5 => 2.2.6

**Comment by nguyenami** [comment]
what happens when you restart it?

**Comment by jnsrikanth** [comment]
@nguyenami when I restart, it is fine. I mean the Blog Main Site comes up as expected and the blog entry that I deleted does not show up anymore. 
But I was hoping to be able to remove a blog entry that I no longer need, it should not mess up a running site?

**Comment by jnsrikanth** [comment]
@KyleAMathews any pointers would be highly helpful. Does content add and delete of .mdx and .md files be not dynamic? With a hot reload?

**Comment by PsychedMagnet** [comment]
I think this happens with any file you delete while the development server is running, so it is not just MDX related

**Comment by jnsrikanth** [comment]
@PsychedMagnet so is that the expected behavior? Don't you think adding and removing of markdown or any similar file is a basic need wherein content is added or removed? Is there a fix being discussed so that such errors do not throw up?
Please let me know.

**Comment by PsychedMagnet** [comment]
@jnsrikanth No, I don't think it is expected behavior. I am just pointing it out for anyone who may know more about this.

Now that I think about it, the same happened when I used create-react-app, so it may be a webpack issue.

**Comment by PsychedMagnet** [comment]
imam basi qkoto gadje horaaa

**Comment by jnsrikanth** [comment]
@KyleAMathews this is a serious issue as this is hampering leveraging gatsby local blog capabilities (without a headless CMS API etc.) using powerful features such as MDX wherein a small change in the markdown file or adding, removing of MDX files is causing the entire site restart...If this is a bug or a webpack issue as pointed out above by @PsychedMagnet , please let us know of a fix. If it is not a feature yet, we need this supported as we plan to have hundreds of blog files (.mdx or .md) being added/removed/modified and maintained, and that should not ever lead to a site restart? Where is the whole Hot Reloading thing? Am I missing something? This issue has been pending for way too long and I have not had much success on Stackoverflow either.
