### ISSUE TITLE
[gatsby-source-graphql] Allow to pass transformers

### ISSUE THREAD

**Issue by patrick91** [gatsbyjs/gatsby#17076]
## Summary

Recently I needed to customise the schema for a GraphQL API (making an argument optional). I had to make a copy of gatsby-source-graphql, which I think could have been avoided if we could pass an additional list of transforms.

### Basic example

The configuration could look like this, not sure we should make two options, one for pre transforms and one for post transforms 🤔 

```
module.exports = {
  plugins: [
    // Simple config, passing URL
    {
      resolve: "gatsby-source-graphql",
      options: {
        // This type will contain remote schema Query type
        typeName: "SWAPI",
        // This is field under which it's accessible
        fieldName: "swapi",
        // Url to query from
        additionalTransforms: [new MakeArgumentOptional()]
      },
    },
  ]
}
```

### Motivation

It might be useful to apply transforms, maybe it is a niche feature request, but I needed it :)

Happy to send a PR to add this if the approach is good :)

**Comment by LekoArts** [comment]
> Recently I needed to customise the schema for a GraphQL API (making an argument optional).

Can you clarify what you mean by that? Please show a repository, code examples etc.

Could you use our schema customization API for that? https://www.gatsbyjs.org/docs/schema-customization/

**Comment by patrick91** [comment]
@LekoArts I tried with schema customisation, but wasn't able to, so I made a custom plugin:

https://github.com/pythonitalia/pycon/blob/b564c21363b17c0604be3ac62cb905a446ad5cc9/frontend/plugins/gatsby-source-pycon/src/transforms.js#L82-L166

maybe there was a better way for this :)
