### ISSUE TITLE
gatsby-plugin-antd available

### ISSUE THREAD

**Issue by bskimball** [gatsbyjs/gatsby#1708]
Not sure if this is correct, but I created a plugin to incorporate Ant Design as a plugin. It uses import on demand using babel-plugin-import

https://github.com/bskimball/gatsby-plugin-antd

```javascript
npm install gatsby-plugin-antd --save
```

Let me know if this helps and feel free to add it to the repo.

**Comment by bskimball** [comment]
found some issues, not ready quite yet

**Comment by bskimball** [comment]
fixed the issues and tested. Is working properly with gatsby blog starter

**Comment by KyleAMathews** [comment]
nice! Antd looks like a really nice component library. We don't yet have a way to automatically add community plugins to the website (want to have it pull that info from NPM) but for now, you can add your plugin to https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/plugins.md

Perhaps under a "Community Plugins" section?

**Comment by bskimball** [comment]
I created a pull request [1726](https://github.com/gatsbyjs/gatsby/pull/1726) which adds a community plugins section and the gatsby-plugin-antd
