### ISSUE TITLE
Styles included on every page

### ISSUE THREAD

**Issue by antonmedv** [gatsbyjs/gatsby#17106]
## Relevant information

If include styles (index.css) on one page (index.js), it will be added to others as well (landing-page.js)

### Environment (if relevant)

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 4.4.23 - /usr/local/bin/bash
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.11.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.14.0 => 2.11.7 
    gatsby-plugin-feed: * => 2.3.1 
    gatsby-plugin-google-analytics: * => 2.1.1 
    gatsby-plugin-google-fonts: 1.0.1 => 1.0.1 
    gatsby-plugin-manifest: * => 2.2.0 
    gatsby-plugin-offline: ^2.2.10 => 2.2.0 
    gatsby-plugin-react-helmet: * => 3.1.0 
    gatsby-plugin-sass: * => 2.1.0 
    gatsby-plugin-sharp: ^2.2.18 => 2.2.1 
    gatsby-remark-copy-linked-files: ^2.1.13 => 2.1.0 
    gatsby-remark-images: ^3.1.19 => 3.1.2 
    gatsby-remark-prismjs: * => 3.3.0 
    gatsby-remark-reading-time: ^1.0.1 => 1.0.1 
    gatsby-remark-responsive-iframe: ^2.2.10 => 2.2.1 
    gatsby-remark-smartypants: * => 2.1.0 
    gatsby-source-filesystem: ^2.1.18 => 2.1.1 
    gatsby-source-github-api: 0.1.0 => 0.1.0 
    gatsby-source-google-analytics-reporting-api: ^1.0.2 => 1.0.2 
    gatsby-transformer-remark: ^2.6.19 => 2.5.0 
    gatsby-transformer-sharp: * => 2.2.0 
  npmGlobalPackages:
    gatsby-cli: 2.4.8

**Comment by PsychedMagnet** [comment]
Isn't this expected behavior? I think when you import it like that it gets included in the main JS bundle. If you want to keep it separated, maybe take a look at CSS modules? I may be wrong though

**Comment by antonmedv** [comment]
Yes, I was thinking it should be included only on pages there I use it. At least this what I understand from documentation.
