### ISSUE TITLE
Provide (or document) method for replacing/patching hard-coded libraries, like React

### ISSUE THREAD

**Issue by nbolten** [gatsbyjs/gatsby#1710]
It would be useful to be able to have more direct, use-configurable access to the libraries used by Gatsby, particularly React, as some useful packages requires monkey patching. For example, I want to integrate [react-a11y](https://github.com/reactjs/react-a11y) into a website, but am having trouble implementing it, as it requires monkey patching the React and ReactDOM used on the root component.

My attempts were to

1. Patch the React instance in html.jsx and cross my fingers (of course, does not work - the React instance used on the root of the client code has to be patched).

2. Write a webpack middleware plugin that aliases 'react' and 'react-dom' to `react-a11y`-patched versions. This seemed like a more reasonable approach, but I ran into frequent implementation issues. It's also not very clean: I only really want the one instance to be monkey-patched.

So my question is: is this something that Gatsby could support, and if it already does, could it be documented with an example? I would not be surprised if there is some webpack magic that would still work, but it's a decently complex effort that requires diving deep into the implementation of Gatsby.

**Comment by KyleAMathews** [comment]
Using webpack should work for this. Check out the Preact plugin https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-preact/src/gatsby-node.js
