### ISSUE TITLE
Issues with gatsby-source-filesystem

### ISSUE THREAD

**Issue by MojoJojo86** [gatsbyjs/gatsby#1711]
Hi, I've followed the examples provided in the readme but whenever I add the plugin and restart with gatsby develop, I just end up hanging in terminal on 
success open and validate gatsby-config.js — 0.007 s
success copy gatsby files — 0.025 s
⠁ source and transform nodes

Not sure what else to try, Am I doing something massively wrong or is it a known issue?

This is my code from gatsby-config.js

```module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `files`,
        path: `${__dirname}/eclipse/`,
      },
    },
     `gatsby-transformer-json`
  ],
}
```

Any help appreciated 👍

**Comment by jquense** [comment]
The plugin can silently jsut tall if there are no files found. Make sure there are actually files at that path? (and maybe drop the trailing slash for fun)

**Comment by MojoJojo86** [comment]
Think I may have sussed it. Need to be ```path: `${__dirname}/src/eclipse` ``` and I dropped the trailing slash for good measure 👍

**Comment by KyleAMathews** [comment]
We should validate that the specified path actually exists…

You want to work on that @MojoJojo86?

**Comment by MojoJojo86** [comment]
@KyleAMathews Yeah if I can figure out how to, I'd love to have a go at it! 👍

**Comment by blargity** [comment]
I think I'm having this same issue. We've decided to update the KeystoneJS Docs site we're working on to the latest version, but when I run `gatsby develop` it hangs in the same place as above.

I checked that the folders being passed into `gatsby-source-filesystem` exist, and they do. How else can I help debug this?

Repro: https://github.com/keystonejs/keystone/tree/docs-upgrade-gatsby

**Comment by ccarse** [comment]
I run into this and sometimes I just have to rerun it and it works.

**Comment by KyleAMathews** [comment]
We're now validating if the path specified exists and throwing error if not.
