### ISSUE TITLE
[gatsby-plugin-offline] Error with app-shell.js

### ISSUE THREAD

**Issue by Angelfire** [gatsbyjs/gatsby#17127]
## Description

I'm getting this error when I try to run `npm run build`:

> ERROR #11328
> A page component must export a React component for it to be valid. Please make sure this file exports a React component:
> /Users/myUser/Projects/personal-website/node_modules/gatsby-plugin-offline/app-shell.js

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).
- Install `gatsby-plugin-offline` plugin: `npm install --save gatsby-plugin-offline`
- Add this plugin to your `gatsby-config.js`
- Run `npm run build`

### Expected result

No errors

### Actual result

> ERROR #11328
> A page component must export a React component for it to be valid. Please make sure this file exports a React component:
> /Users/myUser/Projects/personal-website/node_modules/gatsby-plugin-offline/app-shell.js

### Environment

```System:
    OS: macOS 10.14.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 67.0.4
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.19 => 2.13.28
    gatsby-image: ^2.0.15 => 2.2.6
    gatsby-plugin-manifest: ^2.0.5 => 2.2.3
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.0 => 3.1.2
    gatsby-plugin-sharp: ^2.0.13 => 2.2.8
    gatsby-source-filesystem: ^2.0.4 => 2.1.5
    gatsby-transformer-sharp: ^2.1.4 => 2.2.4
  npmGlobalPackages:
    gatsby-cli: 2.7.40
```

**Comment by ripoul** [comment]
duplicate #17059

set `gatsby-plugin-offline` version to 2.2.9 in your `package.json`

**Comment by Saraavana** [comment]
> duplicate #17059
> 
> set `gatsby-plugin-offline` version to 2.2.9 in your `package.json`

@ripoul Thank you. Worked for me 👍

**Comment by Angelfire** [comment]
Thank you, it's something related to the packages version.
