### ISSUE TITLE
Installed but unused plugins with fragments cause "unknown type" errors

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#17124]
## Description

If a plugin with fragments (e.g. `gatsby-transformer-sharp`) is installed as a dependency but not configured in Gatsby — meaning it's in `package.json` but _not_ in `gatsby-config.js` — Gatsby will find its fragments and fail, resulting in an error.

### Steps to reproduce

On a Gatsby site without `gatsby-transformer-sharp` configured:

```
yarn add gatsby-transformer-sharp
yarn develop
```

### Expected result

The site should start and `gatsby-transformer-sharp` should do nothing since it's not added to `gatsby-config.js`.

### Actual result

Gatsby reads the fragment from `gatsby-transformer-sharp`, then fails because (presumably) the plugin is not actually configured for the site.

```
GraphQL Error Unknown type "ImageSharpFixed".

  file: /Users/jlengstorf/dev/learnwithjason.dev/node_modules/gatsby-transformer-sharp/src/fragments.js

  1 | 
> 2 |   fragment GatsbyImageSharpFixed on ImageSharpFixed {
    |                                     ^
  3 |     base64
  4 |     width
  5 |     height
  6 |     src
  7 |     srcSet
  8 |   }
```

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.1
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.73 => 2.13.73 
    gatsby-transformer-sharp: ^2.2.12 => 2.2.12 
  npmGlobalPackages:
    gatsby-cli: 2.5.0
```

**Comment by jlengstorf** [comment]
Marking this as not stale — I know it's edge-casey, but it's painful for me in workshops, etc. because I can't pre-install node_modules and then add things as we get to them. This error means I either have to rely on conference wifi or have the whole `gatsby-config.js` already set up to avoid fragment errors.

**Comment by LekoArts** [comment]
Testing this on a fresh hello-world starter, installing `gatsby-transformer-sharp` but not adding it in the config and using it - this doesn't show anymore.
