### ISSUE TITLE
Defining field type with createTypes returns null

### ISSUE THREAD

**Issue by josh-meredith** [gatsbyjs/gatsby#17144]
## Summary

Hi, I'm currently trying to use the createType action and have hit a wall. In my Wordpress API response I have a `yoast_meta` property for posts/pages, which is returning an array of items as pictured.

![Screen Shot 2019-08-28 at 3 11 55 pm](https://user-images.githubusercontent.com/2338405/63868872-d33c0600-c9e9-11e9-97e2-50838d76a4de.png)

The `content` property sometimes contains image URL's, so as expected the Wordpress source plugin is inferring this as a `wordpress__wp_media` type.

I'm just trying to define this field to be of `String` type. Although I just can't get it it to work. I've done a lot of digging and tried many variations, but still luck.

My closest attempt will compile fine although then it just returns null for all of the `content` fields. Hoping that I'm just missing something obvious here. Any help would be greatly appreciated.

Here is what I currently have in my gatsby-node file.

```
exports.sourceNodes = ({ actions }) => {
    const { createTypes } = actions;
    const typeDefs = `
        type wordpress__wp_services implements Node {
            yoast_meta: wordpress__wp_servicesYoast_meta
        }
        type wordpress__wp_servicesYoast_meta implements Node {
            content: String
        }
    `;
    createTypes(typeDefs);
};
```

Also here is a snippet of the GraphQL structure.

<img width="1441" alt="Screen Shot 2019-08-28 at 11 28 33 pm" src="https://user-images.githubusercontent.com/2338405/63869972-a0930d00-c9eb-11e9-8387-63c49d597eaf.png">

**Comment by stefanprobst** [comment]
is your repo public somewhere to take a closer look?

also, this issue might be slightly related: https://github.com/gatsbyjs/gatsby/issues/16809#issuecomment-523778285

**Comment by josh-meredith** [comment]
Thanks @stefanprobst, yes I've seen that issue and tried a few things based on your answer, but still couldn't solve it.

Unfortunately I can't make my repo public, but I will create a simple version within the next day so I can replicate the issue.

**Comment by josh-meredith** [comment]
Hi @stefanprobst - I've created a test repo [here](https://github.com/josh-meredith/gatsby-test) which demonstrates the issue I'm having.

I'm still stumped on this, so if you've any time to take a look it would be much appreciated!

https://github.com/josh-meredith/gatsby-test

**Comment by stefanprobst** [comment]
@josh-meredith This works for me:
```js
exports.createSchemaCustomization = ({ actions }) => {
  const typeDefs = `
    type wordpress__POST implements Node {
      yoast_meta: [wordpress__POSTYoast_meta]
    }
    type wordpress__POSTYoast_meta {
      content: String
    }
  `
  actions.createTypes(typeDefs)
}
```

Query:

![wp](https://user-images.githubusercontent.com/20753323/64122903-368bb680-cda3-11e9-8e39-9868dbaaa1a7.png)

The important thing to note is that `wordpress__POST` is the top-level type. It therefore implements the Node interface. And it is why you'll get `wordpressPost` and `allWordpressPost` root query fields.
`wordpress__POSTYoast_meta` otoh is just a field type, i.e. it defines the data shape on the `yoast_meta` field, so it must not implement the Node interface.
Also note that `yoast_meta` is a list field -- you can browse the schema in the right `Docs` side-panel in Graph_i_ql

**Comment by josh-meredith** [comment]
@stefanprobst Amazing! Thank you so much for your help. Appreciate the explanation, that all makes perfect sense now.
