### ISSUE TITLE
Deprecation message for `_experimentalThemes`

### ISSUE THREAD

**Issue by robin-macpherson** [gatsbyjs/gatsby#17147]
In `packages/gatsby/src/bootstrap/index.js` on line 92 there is: `// TODO: deprecation message for old __experimentalThemes`.

I just updated documentation and blog posts to switch the `__experimentalThemes` gatsby-config key to `pugins` which is where I found this (see the PR below).

Is there anything I can do to help here with the deprecation message or anything else on this topic?

Thanks! :)

_Originally posted by @robin-macpherson in https://github.com/gatsbyjs/gatsby/pull/17125#issuecomment-525506120_

**Comment by johnletey** [comment]
I would love to work on this!

**Comment by robin-macpherson** [comment]
@lannonbr , @wardpeet , @sidharthachatterjee, @johno , can I ask for clarification on process here please? I created this issue, assigned it to myself, and wrote a clear description asking for some guidance on whether to move forward. I didn't get any response but saw that @johno added it to "To Prioritize" in Themes Roadmap, and so I was waiting for the response. 

It seems that @johnletey ignored all of the above and just created a PR without even waiting for a response, which was then merged.

Is this the expected course of action for how we work on issues at Gatsby?

**Comment by johno** [comment]
Hey @robin-macpherson, we (@gatsbyjs/themes-core) dropped the ball here and I apologize 😬😞.

We should've provided feedback after the initial PR (from the beginning) so you would know what action to take and wouldn't be stuck in limbo.

When everything is working as it should, your creation of the issue and assigning to yourself should've been responded to swiftly with a go ahead so you could begin work on the PR. This was your PR to work on and it was unfair that you were left waiting.

You followed the proper protocol and we let this slip through the cracks. We'll do our best to make sure this doesn't happen again on themes related PRs and want to let you know that we truly appreciate your contributions.

**Comment by robin-macpherson** [comment]
Thanks for your reply @johno ! I appreciate it and I've really enjoyed starting to make contributions these past few weeks. Honestly I understood that you all must be very busy. I was mostly surprised by the fact that this issue was assigned to me and I was very clearly awaiting feedback and @johnletey opened a PR and did it himself.

I know this is a really small PR and I truly don't mean to be unreasonable by complaining about it.  I mostly just wanted to make sure that I understood whether I'm aligned with Gatsby philosophy and conduct because if this were a larger issue and I was in the middle of working on a PR and then we have people just quickly taking it for themselves without properly communicating, that just seems like a recipe for chaos on an open source project and potentially leading to excited contributors feeling discouraged.

Thank you again for your quick response and also all the support and guidance I've gotten from several wonderful people over at Gatsby thus far.

**Comment by johnletey** [comment]
@robin-macpherson I am truly sorry! I’m used to working on projects where people self-assign issues to themselves all of the time but never start working on them, but that is no excuse for me taking the issue/PR from you!

I am truly sorry and I will definitely ask for clarification before I work on any further issues so that this doesn’t happen again! Sorry for any inconvenience that this may have caused you!

**Comment by robin-macpherson** [comment]
@johnletey thank you for your sincere reply and I appreciate that you'll seek clarification in the future. Happy coding! 🙂💪🏼
