### ISSUE TITLE
idea: have a global TODAY variable to Filter GraphQL Date type less than or equal to today without string interpolation

### ISSUE THREAD

**Issue by sw-yx** [gatsbyjs/gatsby#17159]
## Summary

the GraphQL Date type in gatsby is fantastic! It is a pretty common operation to want to filter less than or equal to Today. 

eg. in my `pages/index.js` (so i cant pass in a variable thru `gatsby-node.js`) i want to do query all my data but not show stuff in future.

https://github.com/gatsbyjs/gatsby/issues/4033
https://github.com/gatsbyjs/gatsby/issues/17041

### Basic example

this is just an idea, happy to consider other different solutions to solve this

```js
export const pageQuery = graphql`
  query {
    allMdx(
      limit: 8
      sort: { fields: [frontmatter___date], order: DESC }
      filter: { frontmatter: { date: { lte: TODAY } } }
    ) {
      edges {
        node {
          // ...
		}
	  }
    }
}
`
```

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

to facilitate people writing graphql queries with date filters.

**Comment by sw-yx** [comment]
NO

**Comment by jonniebigodes** [comment]
@sw-yx you need to remove the stale?

**Comment by sw-yx** [comment]
i dont mind the stale, i’d love for a response if it sounds good or not

**Comment by jonniebigodes** [comment]
@sw-yx after considering for a bit, i think that it might be a good idea. More even to newcomers that come into "gatsby world" and probably don't know anything much about GraphQL, instead of seeing what is the default query arguments and syntax used and probably see only one word, i think it would be a no brainer. But that's just me! I would love to hear from the rest of the community and team

**Comment by jlengstorf** [comment]
For any future googlers, there's an easy way to get this functionality with schema customization:

```js
exports.createSchemaCustomization = ({ actions, schema, getNode }) => {
  actions.createTypes([
    schema.buildObjectType({
      name: 'YourNodeType',
      interfaces: ['Node'],
      fields: {
        isFuture: {
          type: 'Boolean!',
          resolve: source => new Date(source.date) > new Date(),
        },
		// ...declare other fields here...
      },
    }),
  ]);
};
```

Then you can add a filter to your queries like this:

```gql
{
  allYourNodeType(filter: { isFuture: { eq: false } }) {
    nodes {
      title
    }
  }
}
```

**Comment by patarapolw** [comment]
For a MarkdownRemark user like me, create this in `/gatsby-node.js`

```js
...
exports.createSchemaCustomization = ({ actions, schema, getNode }) => {
  actions.createTypes([
    schema.buildObjectType({
      name: 'MarkdownRemark',
      interfaces: ['Node'],
      fields: {
        isFuture: {
          type: 'Boolean!',
          resolve: (s) => new Date(s.frontmatter.date) > new Date(),
        },
      },
    }),
  ])
}
```

For more tutorials, see <https://www.gatsbyjs.org/docs/schema-customization/>

**Comment by LeunensMichiel** [comment]
And for a Contentful user like me, make sure to put `name: 'ContentfulYourItem'` with an uppercase `C`. In the graphQL builder, your Contentful object type starts with a lowercase `c`, but you'll need uppercase. So not `contentfulYourItem`.
