### ISSUE TITLE
redirects.find is not a function

### ISSUE THREAD

**Issue by jrusso1020** [gatsbyjs/gatsby#17151]
## Description

After upgrading to gatsby 2.14.1, my build is failing with the following error

 ERROR #11321  PLUGIN

"gatsby-plugin-s3" threw an error while running the createPagesStatefully lifecycle:

redirects.find is not a function

  TypeError: redirects.find is not a function
  
  - gatsby-node.js:39 Object.exports.createPagesStatefully
    [white-glove]/[gatsby-plugin-s3]/gatsby-node.js:39:41
  
  - api-runner-node.js:234 runAPI
    [white-glove]/[gatsby]/dist/utils/api-runner-node.js:234:37
  
  - api-runner-node.js:347 resolve
    [white-glove]/[gatsby]/dist/utils/api-runner-node.js:347:15
  
  - debuggability.js:313 Promise._execute
    [white-glove]/[bluebird]/js/release/debuggability.js:313:9
  
  - promise.js:488 Promise._resolveFromExecutor
    [white-glove]/[bluebird]/js/release/promise.js:488:18
  
  - promise.js:79 new Promise
    [white-glove]/[bluebird]/js/release/promise.js:79:10
  
  - api-runner-node.js:346 Promise.mapSeries.plugin
    [white-glove]/[gatsby]/dist/utils/api-runner-node.js:346:12
  
  - util.js:16 tryCatcher
    [white-glove]/[bluebird]/js/release/util.js:16:23
  
  - reduce.js:155 Object.gotValue
    [white-glove]/[bluebird]/js/release/reduce.js:155:18
  
  - reduce.js:144 Object.gotAccum
    [white-glove]/[bluebird]/js/release/reduce.js:144:25
  
  - util.js:16 Object.tryCatcher
    [white-glove]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:517 Promise._settlePromiseFromHandler
    [white-glove]/[bluebird]/js/release/promise.js:517:31
  
  - promise.js:574 Promise._settlePromise
    [white-glove]/[bluebird]/js/release/promise.js:574:18
  
  - promise.js:619 Promise._settlePromise0
    [white-glove]/[bluebird]/js/release/promise.js:619:10
  
  - promise.js:699 Promise._settlePromises
    [white-glove]/[bluebird]/js/release/promise.js:699:18
  
  - async.js:138 _drainQueueStep
    [white-glove]/[bluebird]/js/release/async.js:138:12
  

⠋ createPagesStatefully

### Steps to reproduce

Upgrade to ruby 2.14.1, and run `npm run build`

### Expected result

Build should succeed

### Actual result

Build errors out saying `redirects.find is not a function

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 3.5.2 - /Users/james/anaconda3/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.14.1 => 2.14.1
    gatsby-image: ^2.2.14 => 2.2.14
    gatsby-plugin-emotion: ^4.1.4 => 4.1.4
    gatsby-plugin-manifest: ^2.2.9 => 2.2.9
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.5 => 3.1.5
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-s3: ^0.3.2 => 0.3.2
    gatsby-plugin-sharp: ^2.2.18 => 2.2.18
    gatsby-source-filesystem: ^2.1.18 => 2.1.18
    gatsby-transformer-sharp: ^2.2.12 => 2.2.12
  npmGlobalPackages:
    gatsby-cli: 2.7.30
    gatsby: 2.5.0

**Comment by danielrussellLA** [comment]
same

**Comment by jrusso1020** [comment]
The fix for now is to downgrade gatsby to 2.14.0, change it in your package.json to
```
"dependencies": {
    ...
    "gatsby": "2.14.0",
    ...
  },
```

I believe it's an issue with `plugin-gatsby-s3`, I've also posted an issue there https://github.com/jariz/gatsby-plugin-s3/issues/104 

And I want to say it has something to do with these changes https://github.com/gatsbyjs/gatsby/commit/193f4cd3728cc6af3e55640fb712747e1b369c7e which I believe were introduced in 2.14.1 but I'm not 100% sure

**Comment by me4502** [comment]
Yeah `gatsby-plugin-s3` need to fix it. As mentioned here https://github.com/gatsbyjs/gatsby/pull/17128#issuecomment-525727777, using redux entries is considered a private API.

**Comment by wardpeet** [comment]
Successfully published:
 - gatsby@2.14.4
