### ISSUE TITLE
Sugestion adding a SEO component?

### ISSUE THREAD

**Issue by Bvlktech** [gatsbyjs/gatsby#17161]
## Summary
Something like this so you can just call <SEO title='WHATEVER_THE_TITLE_IS' /> rather than calling <Helmet /> and adding all the <meta /> tags in each file.

```javascript
import React from 'react';
import Helmet from 'react-helmet';
import PropTypes from 'prop-types';
import { useStaticQuery, graphql } from 'gatsby';

const SEO = ({ meta, title, description, lang }) => {
  const { site } = useStaticQuery(graphql`
    query {
      site {
        siteMetadata {
          author
          title
          description
        }
      }
    }
  `);
  const metaDescription = description || site.siteMetadata.description;
  return(
  <Helmet htmlAttributes={{ lang }} title={ title } titleTemplate={ `%s ${ site.siteMetadata.title }` } meta={[
    {
      name: 'description',
      content: metaDescription
    },
    {
      property: 'og:title',
      content: title
    },
    {
      property: 'og:description',
      content: metaDescription
    },
    {
      property: 'og:type',
      content: 'website'
    },
    {
      name: 'twitter:card',
      content: 'summary'
    },
    {
      name: 'twitter:creator',
      content: site.siteMetadata.author
    },
    {
      name: 'twitter:title',
      content: title
    },
    {
      name: 'twitter:description',
      content: metaDescription
    }
  ].concat(meta) } />
  );
}
SEO.defaultProps = {
  meta: [],
  description: '',
  lang: 'en'
}
SEO.propTypes = {
  meta: PropTypes.arrayOf(PropTypes.object),
  title: PropTypes.string.isRequired,
  description: PropTypes.string,
  lang: PropTypes.string
}
export default SEO;
```

### Motivation

This is just an example it lessens the code in each file in /www/src/pages/* and cleans up a bit

**Comment by jnsrikanth** [comment]
Hi,
It would be good to show a usage example for this SEO component? Seems quite useful.

**Comment by Bvlktech** [comment]
you can view a usage ex. on my starter that i made for GatsbyJS called
AdvancedBlog you can find the repo here
https://github.com/bvlktech/AdvancedBlog

**Comment by jnsrikanth** [comment]
Thank You.

**Comment by Bvlktech** [comment]
welcome

**Comment by lannonbr** [comment]
So the default starter already has a [SEO Component](https://github.com/gatsbyjs/gatsby/blob/776dc1d6fe8d5ce7b5ea6d884736bb3c76280975/starters/default/src/components/seo.js), and Sid on the Core team actually extracted it and published it as a npm module called [gatsby-seo](https://github.com/sidharthachatterjee/gatsby-seo)

**Comment by Bvlktech** [comment]
oh didn't know that ok then no biggy this was just a suggestion this can be
closed as no longer needed ill close soon
