### ISSUE TITLE
Middle click swallowed

### ISSUE THREAD

**Issue by johann-sonntagbauer** [gatsbyjs/gatsby#1716]
The gatsby Link wrapper breaks browser behaviour for middle mouse button clicks.

Clicking on a Link with the middle mouse button should open the linked page in a new browser tab. 
But for production builds that behaviour is broken in the following way, that the browser will simply navigate in the current tab and not open a new one. 
But middle clicking a link for a page which is currently displayed, the browser will open a new tab and navigate accordingly.

Following code causes the problem.
https://github.com/johann-sonntagbauer/gatsby/blob/master/packages/gatsby-link/src/index.js#L82

Only in production builds.

Current gatsby versions. Can also be verified on the gatsy doc pages. 

Not all Browsers are affected by this problem. Chrome behaves fine, Mozilla Firefox is broken, other systems seem to be affected as well.

Reference:
https://github.com/reasonml/reasonml.github.io/issues/65
https://github.com/facebook/reason/issues/1347

**Comment by KyleAMathews** [comment]
Oops, could you submit a PR with your fix?

**Comment by johann-sonntagbauer** [comment]
@KyleAMathews I will try :)
