### ISSUE TITLE
Develop: Update GraphQL data from plugin

### ISSUE THREAD

**Issue by pgegenfurtner** [gatsbyjs/gatsby#17171]
I have a database with base data for the website (contact information, etc.), which is loaded into graphql via my custom plugin. Now if I change something in my database, I need to rerun the develop process to get the new data.

Is it possible to tell the plugin, that new data is available and it should refetch it? Without needing to restart the develop process.

My database content is served via an api, so I could use a webhook to inform the plugin. But what then?
I searched a bit but could not find what I'm looking for.

Thanks!

**Comment by jonniebigodes** [comment]
@pgegenfurtner sorry for the late response, but have you taken a look at [gatsby-source-graphql](https://www.gatsbyjs.org/packages/gatsby-source-graphql/) it refetches the content periodically.

**Comment by pgegenfurtner** [comment]
I will have a look at it, thanks!
