### ISSUE TITLE
Allow Opt-out of data-uri transform for images

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#17182]
## Summary

In many cases, transforming smaller images into a data URI is a nice win, however there are cases where this is not desirable, and it would be very useful to be able to opt out of this behaviour.

### Basic example

If a page makes heavy use of background images across multiple breakpoints, this approach creates a problem. If the images were _not_ converted into data URIs, only the images needed for the current breakpoint would be loaded into the page, however when using data URIs, all images are added to a bundle. In a situation where multiple background images are used for each breakpoint, and potentially multiple components are used, each with multiple images, across multiple breakpoints, this results in a significant increase to the bundle, including a lot of weight taken up by images that the user (at a single breakpoint) would never see.

### Motivation

By allowing an opt-out, images could be loaded instead of encoded in situations like that outlined above.

**Comment by KyleAMathews** [comment]
What does your query look like?

**Comment by Undistraction** [comment]
@KyleAMathews no query. Just a direct import into my react component. On digging deeper, what I'm seeing is that the svgs are being added to the page bundle as data URIs, but the URLs are still present in the components, so the svgs are loaded from the static dir at runtime and the components never actually use the data URIs.

**Comment by KyleAMathews** [comment]
Are you using a * import e.g. `require("./*.svg")`?

You can also tell webpack to not inline svgs which will turn all the data-uris into links to files.

**Comment by Undistraction** [comment]
No. It's just an `import example from '../../../images/example.svg`.

In many cases, the URI makes sense, so it needs to be context dependent. But I guess that's less of a problem than URIs being added to bundles but not used.

**Comment by Undistraction** [comment]
Looks like Gatsby is transforming the URLs properly, but my original request remains: I still think transforming an image into a URI should provide an opt-out on a case-by-case basis.
