### ISSUE TITLE
Unknown argument 'context'

### ISSUE THREAD

**Issue by pavanpodila** [gatsbyjs/gatsby#1718]
If I rely on the sitePage's context parameter to feed some fields into my page, I am getting the error:

```
success extract queries from components — 0.046 s

There was an error while compiling your site's GraphQL queries in document "BlogPostByPath" in 
     Unknown argument `context`
```
Although it works well in GraphiQL and during runtime. I am ignoring this for the moment but would love to see a clean bootstrap from Gatsby.

This is how I am creating the page in `gatsby-node.js`:

```js
createPage({
            path,
            component: blogPostTemplate,
            context: {
                path,
                html,
                title,
                date,
            }
        });
```
and this is how I am setting up the pageQuery for my blog post template:

```js
export const pageQuery = graphql`
    query BlogPostByPath($path: String!) {
        sitePage(context: { path: {eq: $path}}) {
            context {
                path
                html
                title
                date(formatString: "MMMM DD, YYYY")
            }
        }
    }
`;

```

The reason I am doing this is because I don't want to specify the path in my markdown frontmatter. Instead I want to derive it from the title. Most other starter kits require specifying the path, which I don't like much 👎

**Comment by Mziserman** [comment]
I do two thing differently and it works for me :
first in context I pass key values
````createPage({
            path,
            component: blogPostTemplate,
            context: {
                path: path,
            }
        });```

And second, in the page query I don't use the context (It's done by gatsby I think).

````
export const pageQuery = graphql`
    query BlogPostByPath($path: String!) {
        sitePage(path: {eq: $path}) {
                path
                html
                title
                date(formatString: "MMMM DD, YYYY")
        }
    }
```

Hope this help.

**Comment by pavanpodila** [comment]
For some reason, querying without the context is not working for me, so I'm forced to do this:

```
query BlogPostByPath($path: String!) {
        sitePage(context: {path: {eq: $path}}) { ... }
}
```

**Comment by KyleAMathews** [comment]
Page context is already injected as a prop, no need to query it :-)
