### ISSUE TITLE
[gatsby-plugin-prismjs]: Additional classes applied to code-fence being combined

### ISSUE THREAD

**Issue by LA1CH3** [gatsbyjs/gatsby#17195]
## Description

When trying to apply additional classes to a code block when using `gatsby-remark-prismjs`, the classes get weirdly combined together.

example:
````
```jsx live preview
const Button = () => <button></button>
```
````

gets turned into

```
<code class="language-jsxlive preview">...</code>
```

when this is expected:

```
<code class="language-jsx live preview">...</code>
```

For some reason, the language and first class are combined together.

### Steps to reproduce

Using the following packages:

`gatsby @ ^2.11.0`
`gatsby-transformer-remark @ ^2.6.19`
`gatsby-remark-prismjs @ ^3.3.9`

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0
    Safari: 12.1.2
  npmGlobalPackages:
    gatsby-cli: 2.7.38
```

**Comment by LekoArts** [comment]
Yeah, I can reproduce this with: https://codesandbox.io/s/17195-b87vs

**Comment by LA1CH3** [comment]
The fix is needed here- just add a space between `node.lang` and `node.meta` when combining them together. https://github.com/gatsbyjs/gatsby/blob/c956038b85fc75bd07bd8c26723d0bfc1f996ad3/packages/gatsby-remark-prismjs/src/index.js#L34

**Comment by LekoArts** [comment]
Yeah, that seems about right. If you want to fix it yourself we'd be happy to accept a PR from you -- to get you started you can have a look at https://www.gatsbyjs.org/contributing/ and we're happy to answer any questions you have :)
