### ISSUE TITLE
Respect Save-Data client hint in gatsby-image

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#17202]
Many people on constrained data plans turn on data saving — their smartphone browsers then send a "Save-Data" header to servers.

We can use this in the client as well to choose lower-data rendering options for these people.

For gatsby-image, we can render regular resolution images for these people instead of retina.

```js
if ("connection" in navigator) {
    if (navigator.connection.saveData === true) {
        // Implement data saving operations here.
    }
}
```

We can detect in the component if data saving is enabled and then when rendering, only render the `src` and not `srcset` thus avoiding making the user download retina (so much bigger) images.

The source code for gatsby-image is at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js

We can use a similar pattern for this as we do with detecting native lazy loading support https://github.com/gatsbyjs/gatsby/blob/693f3edc43f0dee0766f5e3a07de32a4cfbba22c/packages/gatsby-image/src/index.js#L81

For background reading on Save-Data:

- https://timkadlec.com/remembers/2019-08-29-save-data-usage/
- https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data/

**Comment by charlyx** [comment]
Hi Kyle,

I’d like to work on this if that’s ok :)

**Comment by KyleAMathews** [comment]
Yes please!

Let us know how it's going and if you have any questions!

**Comment by mrbusche** [comment]
@charlyx you still interested in doing this? If not I'd like to.

**Comment by jeremyscatigna** [comment]
Hey ! is there any way I could help? 😀

**Comment by devrchancay** [comment]
Hey! This is very interesting and this issue has open time, I will try to do it.

**Comment by devrchancay** [comment]
```javascript 
const hasClientSaveData = typeof navigator.connection && navigator.connection === true 
```
in the constructor of the Image component

```javascript
this.useClientSaveData = hasClientSaveData
```

```jsx
<Img
    alt={alt}
    title={title}
    sizes={image.sizes}
    src={image.src}
   crossOrigin={this.props.crossOrigin}
   {...(!this.useClientSaveData ? { srcSet: image.srcSet } : {})}  this way you would avoid srcSet rendering
   style={imageStyle}
    ref={this.imageRef}
    onLoad={this.handleImageLoaded}
    onError={this.props.onError}
     itemProp={itemProp}
     loading={loading}
    draggable={draggable} />
```

It is very likely that I am not taking something into account, but I would like to know if I am on the right track @KyleAMathews

**Comment by pvdz** [comment]
Here's the problem we need to resolve first somehow: This datasaver state is an http request header which we can not "read" through plain httml or css without either server-side rewriting/routing or client-side JS. There is currently no `@media` css query, nor is there html like `<noscript>` or special `<img>` attributes which would allow us to prevent fetching heavy images when datasaver was requested. That's sad but appears to be the way it is right now.

Here's a resource on how to work with datasaver: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data

And here's the mdn page on it, which says it's still experimental: https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/saveData

For our solution we need to determine what to do for the first render, without JS: datasaver or not datasaver. I'm inclined to think the default would not be datasaver, but possibly your usecase is mobile-first, in which case you'd definitely want datasaver first. In addition we need to support the conditionals in JS once a page is fully hydrated. This part we could already do, might improve things a little bit.

We should test the impact of perf of datasaver-first on desktop without datasaver. Are there any flashes (when heavier images are requested once JS kicks in) or would it actually be fine for us to use srcsets with low rez only, initially, and to update them with all other resolutions through JS?

The downside, obviously, is that people without JS would not be able to see the high-rez version of images on the site, with very few alternative ways to fix that. Short of double-rendering the entire site, of course. That might be a workaround that works for smaller sites.

We can try to turn to browser vendors and have them implement a `<data-saver>` tag, or some kind of `<img src-data-saver="lowrez.jpg">` attribute. That would be awesome but will have a long turn-around.
