### ISSUE TITLE
Error while adding thumbnail images

### ISSUE THREAD

**Issue by Henzelix** [gatsbyjs/gatsby#17246]
Hi,
I have a problem with adding thumbnail images. I have this error: 

> Cannot query field "timage" on type "MarkdownRemarkFrontmatter". Did you mean "title"?  graphql/template-strings

Here is the code:

### Index.js:
```jsx
import React from "react"
import { Link, graphql, StaticQuery } from "gatsby"
import Image from "../components/image"
import SEO from "../components/seo"
import Post from "../components/Post"


const IndexPage = () => (
  <>
   <StaticQuery query={indexQuery} render={data => {
     return (
       <div>
         {data.allMarkdownRemark.edges.map(({ node }) => (
           <Post 
            title={node.frontmatter.title}
            path={node.frontmatter.path}
            body={node.excerpt}
            fluid={node.frontmatter.timage.childImageSharp.fluid}
           />
         ))}
       </div>
     )
   }}/>
  </>
)

const indexQuery = graphql`
query{
  allMarkdownRemark(sort: { order: DESC, fields: [frontmatter___date] }){
    edges{
      node{
        id
        frontmatter{
          title
          path
          date
          timage{
            childImageSharp{
              fluid{
                ...GatbyImageSharpFluid
              }
            }
          }
        }
        excerpt
      }
    }
  }
}
`;

export default IndexPage
```

### Post file:
```md
---
title: "FIrst post - introduction"
date: "2017-11-07"
path: "/first-post"
timage: ../../images/travisscott.jpg
---

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vel ullamcorper dui. Nam ut aliquam nisi, at rutrum metus. Nunc.
```

### gatsby-config.js:
```js
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages`,
        name: `markdown-pages`,
      },
    },
    `gatsby-transformer-remark`,
    
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#2B60DE`,
        theme_color: `#2B60DE`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
```

Thanks for helping! 😊

**Comment by jpedroschmitz** [comment]
Hey @Henzelix, could you please format the code correctly? This way makes understanding very difficult! Thanks 💜

**Comment by Henzelix** [comment]
@jpedroschmitz I put code in code blocks but idk what happend only the last one works :/

**Comment by lannonbr** [comment]
Updated the code snippets to be formatted correctly

**Comment by Henzelix** [comment]
@lannonbr big thanks

**Comment by ImedAdel** [comment]
`timage` should be a string. That is,

```js
timage: "../../images/travisscott.jpg"
```

**Comment by Henzelix** [comment]
@ImedAdel Still nothing, I get this error:

> ./src/pages/index.js
Module Error (from ./node_modules/eslint-loader/index.js):

C:\Users\mikol\piec\src\pages\index.js
   2:10  warning  'Link' is defined but never used                                                        no-unused-vars
   3:8   warning  'Image' is defined but never used                                                       no-unused-vars
   4:8   warning  'SEO' is defined but never used                                                         no-unused-vars
  37:11  error    Cannot query field "timage" on type "MarkdownRemarkFrontmatter". Did you mean "title"?  graphql/template-strings

✖ 4 problems (1 error, 3 warnings)


GraphQL Error Encountered 1 error(s):
- Unknown field 'timage' on type 'MarkdownRemarkFrontmatter'. 

      file: C:/Users/mikol/piec/src/pages/index.js

**Comment by ImedAdel** [comment]
Can you share a repo with the same problem?

**Comment by Henzelix** [comment]
I can't find anything done by my way but I was helping myself with this tutorial: https://www.youtube.com/watch?v=XpnZ2e7Jns0&t=199s

**Comment by kingingcole** [comment]
Hey @Henzelix, try adding making `timage` a strong if it isn't already. If it is, make sure all other markdown files that serve as your posts each have their `timage` too. That is to say, you should have a `timage` for every post you have. Clear the `public/` folder and restart the development server.
If issue persists, use [this article here](https://codebushi.com/gatsby-featured-images/)

**Comment by tareefdev** [comment]
The official documentation doesn't use string for it, see the section [Featured images with Frontmatter metadata](https://www.gatsbyjs.org/docs/working-with-images-in-markdown/#featured-images-with-frontmatter-metadata).

The `timage` field should include the relative path to an image you want to use. Check it up.

**Comment by jonniebigodes** [comment]
@tareefdev the document you've linked doesn't use a string because it's assuming that the image and the markdown file are siblings, meaning that they are inside the same folder, with that it's not needed a string. It's meant that way to keep it simple and avoid confusion. When gatsby is building it detects that the image file exists next to the markdown, it will be transformed into by the plugin and you can use it like so. It generates the graphql FileNode out of the box.

**Comment by tareefdev** [comment]
@jonniebigodes I'm working on two projects based on Gatsby, and don't use string for image frontmatter's value.

The first one uses NetlifyCMS with `gatsby-remark-relative-images` plugin, where `posts` and `images` are in totally different paths (`./content`, `./static/assets/` respectively)

The second one has this hierarchy:
```JSON
  {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/posts`,
        name: `blog`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/images`,
        name: `images`,
      },
    },
```

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll need to have the images in the same directory as your markdown file (or in a folder in the same directory). Alternatively you could use `gatsby-remark-relative-images`.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
