### ISSUE TITLE
sourcing files from wordpress and built

### ISSUE THREAD

**Issue by Amanrazdan** [gatsbyjs/gatsby#17243]
I am new to gatsby but I have known with my recent discovery that Gatsby graphql comes with the plugin to source content from WordPress. We want to build an application stack with WordPress as headless CMS and react as front end. This is going to be large scale application like Medium.org where anyone can write and anyone can access the content on top of recommender systems. 

my questions -
does gatsby run a site build every time a new post is made or a change is made to the WordPress content? If yes, is this really practical to use for large scale application 
or is it better to use react directly over graph QL to dynamically fetch content for react frontend 

thanks in advance

**Comment by garethpbk** [comment]
If you're using `gatsby-source-wordpress` (or `gatsby-source-graphql` with `wp-graphql`), where your content is sourced at build time, then yes, it will need to rebuild the site every time the content is updated.  You'll have to do that manually or set up a process to have it automatically triggered, e.g. what `littlebot-netlify` does for Netlify deployments.

If you need your content to be more dynamic you're free to do so within Gatsby by using a GraphQL client, a fetch request, whatever works for you. But this won't utilize a `gatsby-source-*` plugin.

Whether this is practical or not is up to you and your team, I'd say. Are you publishing multiple pieces of content every hour? Maybe a rebuild every time won't work well. Would a once or twice daily site deployment suffice? Might be a good solution.

**Comment by Amanrazdan** [comment]
thanks 
that was helpfull
