### ISSUE TITLE
[gatsby-plugin-manifest] Localized manifest not selected on navigation

### ISSUE THREAD

**Issue by dkthehuman** [gatsbyjs/gatsby#17255]
## Description

When a localized page is loaded using the `<Link />` component, the localized manifest is not selected in `<head>`.

### Steps to reproduce

Demo repo: https://github.com/dkthehuman/gatsby-manifest-l10n-bug-demo
Netlify: https://affectionate-franklin-dc4bfb.netlify.com

1. Navigate to the Netlify demo (or run `gatsby build && gatsby serve` on the test repo)
2. Open DevTools and confirm that the manifest in `<head>` is `manifest-en.webmanifest` as expected.
3. Click on the "Spanish" link to navigate to `/es/`.
4. See that the manifest is still `manifest-en.webmanifest` rather than `manifest-es.webmanifest`.

### Expected result

The manifest in `<head>` should be `manifest-es.webmanifest`.

### Actual result

The manifest in `<head>` is still `manifest-en.webmanifest`.

### Considerations

In production builds (`gatsby build && gatsby serve`), the correct manifest is loaded when the localized page is the initial page or if you refresh on it.

In development builds (`gatsby develop`), the correct manifest is never loaded, regardless of whether you refresh or not.

### `gatsby-plugin-manifest` configuration

```javascript
{
      resolve: "gatsby-plugin-manifest",
      options: {
        name: "Hello World",
        short_name: "Test",
        start_url: "/",
        display: "minimal-ui",
        icon: "src/images/gatsby-icon.png",
        lang: "en",
        localize: [
          {
            start_url: "/es/",
            lang: "es",
            name: "Hola Mundo",
          },
        ],
      },
    },
```

### Environment

```

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Languages:
    Python: 3.7.4 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.73 => 2.13.73 
    gatsby-plugin-manifest: ^2.2.6 => 2.2.6 
  npmGlobalPackages:
    gatsby-cli: 2.7.33
```

**Comment by dkthehuman** [comment]
Hey @CanRau, did you notice this behavior at all when working on PR #13471?

**Comment by CanRau** [comment]
Hmm don't know but probably no 😌
Is that even necessary?
I mean wouldn't any bot interested in the manifest load the whole page anyway? Not sure about it though..

**Comment by dkthehuman** [comment]
I'm imagining the use case where someone navigates to a homepage (e.g. English), clicks a link to a translated version (e.g. Spanish), and then chooses the "Add to Home Screen" option. In that case, I think the correct behavior would be to load the Spanish manifest rather than the English manifest.

**Comment by moonmeister** [comment]
@dkthehuman Hey! I hope I've answered all your questions on my various PRs. My guess to the rough problem.... Basically, when all the static pages are being written it's correctly determining the manifest file. Thus, it works on reloading the page. But because the `<Link />` component is connected in with the re-hydrated react app something is probably not getting updated correctly. I'll take a look to see if I can find out what more exactly.

Also, FYI, you mentioned wanting to fix this and do some other cleanup. Please do, i was cringing at some of my code. Just remember the smaller the PR the easier it is to merge. I'd recommend breaking different bugs, and any general cleanup into different PRs. And don't forget tests for any bugs or new features. 👍 Let me know if I can help.

**Comment by dkthehuman** [comment]
@moonmeister Yup, thanks for all the clarifications!

I'll divide up my work into three PRs to keep them small and manageable:
- Fix manifests not being updated on browser navigation
- Fix apple-touch-icons not being updated on browser navigation
- Extend localize functionality to support any child apps, not just localized versions of the same app
