### ISSUE TITLE
[blog] blog idea: using github issue as comment system

### ISSUE THREAD

**Issue by malcolm-kee** [gatsbyjs/gatsby#17262]
## Summary

I would like to propose a blog post on how to use GitHub issue as comment system for a Gatsby site.

### Basic example

You can see a live example here: https://malcolmkee.com/js-the-react-parts/introduction

**Comment by LekoArts** [comment]
Our issue tracker is probably not the right place for this inquiry. Feel free to write that blogpost on your own blog and tweet it out to us. Cheers! :)
