### ISSUE TITLE
How can I use Data API's for blog instead of filesystem?

### ISSUE THREAD

**Issue by MahbbRah** [gatsbyjs/gatsby#1729]
There is an example on gatsby site for creating a blog with a filesystem. However, this isn't a convenient and good way to a blog where will have a lot of posts and need to created folder save file then rebuild. So I want to create a blog with External data But I will love to use GatsbyJS I'm not getting any example to do that. How I can fetchs external data and use them with my blog? Please any guidelines or tutorial appreciated. Thanks and I'm really for that this isn't a issue actually.

**Comment by sebastienfi** [comment]
Look into this doc for gatsby-source plugins : https://www.gatsbyjs.org/docs/plugins/
You will find Contentfull, Drupal, WordPress, and more. Each plugin contains a documentation.
