### ISSUE TITLE
Firebase Init requires Window

### ISSUE THREAD

**Issue by Cobwebster** [gatsbyjs/gatsby#17306]
Hey, I'm attempting to link Redux to firebase, however, when I run develop or build my firebase becomes null because it requires a window and there is no window provided in those environments.

Code:
https://hastebin.com/okiwopidon.js

I saw a few solutions but none seem to be working for me as I cannot use componentDidMount in my store creator. Any help is appreciated, not sure how I can make my store only create on the browser or not error in build.

**Comment by universse** [comment]
Can you try check for window first? Something like this
```js
typeof window === 'object' && firebase.initializeApp(...)
```
