### ISSUE TITLE
How to use gatsby-source-graphql with aws app sync and cognito

### ISSUE THREAD

**Issue by tw1t611** [gatsbyjs/gatsby#17302]
## Summary
Hi, I am trying to use gatsby-source-graphql with cognito (not api key).
The build fails on
`ServerError: Response not successful: Received status code 401`
since there is no valid jwt sent, as expected.
Is there any way to prevent this error?

## Relevant information
The identity and user pool are set up correctly. (unauthenticated users are allowed)

### Environment (if relevant)
Runs with error on dev.
Build fails.

```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    npm: 5.8.0 - /usr/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 60.8.0
  npmPackages:
    gatsby: ^2.14.0 => 2.14.0 
    gatsby-image: ^2.2.14 => 2.2.14 
    gatsby-plugin-manifest: ^2.2.9 => 2.2.9 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.5 => 3.1.5 
    gatsby-plugin-sharp: ^2.2.18 => 2.2.18 
    gatsby-plugin-styled-components: ^3.1.3 => 3.1.3 
    gatsby-source-filesystem: ^2.1.18 => 2.1.18 
    gatsby-source-graphql: ^2.1.11 => 2.1.11 
    gatsby-theme-material-ui: ^1.0.4 => 1.0.4 
    gatsby-transformer-sharp: ^2.2.12 => 2.2.12 
  npmGlobalPackages:
    gatsby-cli: 2.7.30
```

**Comment by ascorbic** [comment]
AppSync permissions can be really confusing and are easy to break. If you haven't already, I'd suggest you try and confirm that it's working unauthenticated outside of Gatsby first, using another GraphQL client.

**Comment by wardpeet** [comment]
Hey, I'm not sure we can help you here as I don't have any experience with AppSync.

I suggest looking at https://github.com/aws-samples/aws-appsync-gatsby-sample and maybe ask around on https://spectrum.chat/gatsby-js or https://discordapp.com/channels/484383807575687178/484383808007962640

**Comment by tw1t611** [comment]
Hi, for everyone getting to the same issue. You don't really need the plugin. Just use the normal graphql transformators from amplify.
https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js

For everyone, who needs access for unauthenticated users.
The solution is under development atm.
https://github.com/aws-amplify/amplify-cli/pull/1916

There is a workaround for now, which I don't really suggest if you can wait just a bit.
https://github.com/aws-amplify/amplify-js/issues/2645

@wardpeet and @ascorbic  thank you for your reply.

**Comment by Bulletninja** [comment]
What i did is adding gatsby's graphiql using gatsby-source-graphql using the auth key approach (via x-api-key header) which i use to build the static content. But then in the client side i do the rest with redux and calling the auth api. I had to add some directives in my scheme though (like this https://medium.com/@ednergizer/multiple-authorization-methods-in-a-single-graphql-api-with-aws-appsync-security-at-the-data-7feeaa968486 ). Which is not very practical because those get overwritten by the cli if you try to regenerate the schema. Hopefully #1916 gets merged soon :)

**Comment by tw1t611** [comment]
Hi, now that I did implement auth, my advice is not to use the gatsby-source-graphql plugin.
Even if you get it working, which I did not. There are 3 auth types for aws right now and you probably will end up using them all. Just use the  amplify graphql transformer, without `graphqlOperation`.

```js
import Amplify, { API } from 'aws-amplify';

const createdTodo = await API.graphql({
  query: queries.createTodo,
  variables: {input: todoDetails},
  authMode: 'AWS_IAM' // or AWS_API_KEY, AMAZON_COGNITO_USER_POOLS, OPENID_CONNECT
});
```

https://aws-amplify.github.io/docs/js/api#aws-appsync-multi-auth

#18684 just for reference
