### ISSUE TITLE
How to get posts based on the tags of the current post?

### ISSUE THREAD

**Issue by laurosilvacom** [gatsbyjs/gatsby#17304]
I've implemented tags following the Gatsby tutorial: ["Creating Tags Pages for Blog Posts"](https://www.gatsbyjs.org/docs/adding-tags-and-categories-to-blog-posts/). 

At the bottom of each post page of my site, I want to display the related posts based on the tags of the current posts. For example, if I have a post with the tag **pizza**, I want to display other post that are also tagged with **pizza**.

What's the best approach to implement this? 🙄🙏🏽

**Comment by universse** [comment]
Hi. It would be better if you share some code so I can test things out. But based on your input, I guess you want something like this.
```js
  posts.forEach(({ node }) => {
    createPage({
      path: node.fields.slug,
      component: blogPostTemplate,
      // pass tag to page context
      context: {
        tags: node.frontmatter.tags
      }
    })
  })
```

then in your blogPostTemplate
```js
export const pageQuery = graphql`
    query ($tags: [String]) {
      allMarkdownRemark(limit: 3, filter: {frontmatter: {tags: {in: $tags}}}) {
        nodes {
          frontmatter {
            title
            categories
          }
        }
      }
    }
  }
`
```

**Comment by jonniebigodes** [comment]
@universse it's not as simple as that. From my understanding of the issue What is needed is a little more complex than that. If you don't mind waiting a bit i'm going to create a reproduction and post a detailed answer later. Sounds good?

**Comment by laurosilvacom** [comment]
That would be really helpful @jonniebigodes! Thank you. 

@universse Thanks! I've tried the steps that you suggested but I kept hitting an error when implementing the query in the `blogPostTemplate`.

```
Query 'usersLauroLocalLaurosilvacomSrcTemplatesEpisodeJs4277587188' references undefined.
```

**Comment by universse** [comment]
I'm not sure why you are running into the issue though. I cloned your [repo ](https://codesandbox.io/s/gatsby-starter-default-jy21d) and it's seem to be fine.

**Comment by laurosilvacom** [comment]
I was missing `$series: [String]` in the episode template. It works. Thank you! 😄
