### ISSUE TITLE
[gatsby-source-contentful] Gatsby build caches are too agressive

### ISSUE THREAD

**Issue by KnisterPeter** [gatsbyjs/gatsby#17312]
## Description

Gatsby build produces pages with stale data.

### Steps to reproduce

1. Create a page with a unique slug field in contentful
1. Publish this page
1. Run `gatsby build`
1. Create a new page with the same slug in contentful (but different content)
1. Unpublish the previous page
1. Publish the new page
1. Run `gatsby build`

### Expected result

After the second build the new page should be created.

### Actual result

After the second build the old page was created.

### Environment

  System:
    OS: Linux 5.2 Arch Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Shell: 5.0.9 - /bin/bash
  Binaries:
    Node: 12.8.1 - /tmp/yarn--1567418085218-0.728818888979579/node
    Yarn: 1.17.3 - /tmp/yarn--1567418085218-0.728818888979579/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.8.1/bin/npm
  Languages:
    Python: 3.7.4 - /usr/bin/python
  Browsers:
    Firefox: 68.0.2

**Comment by KnisterPeter** [comment]
This is the same as #16189

**Comment by LekoArts** [comment]
Let's keep things in https://github.com/gatsbyjs/gatsby/issues/16189 😊 	
Marking this as a duplicate.
