### ISSUE TITLE
[gatsby-plugin-catch-links] documentation for plugin options is not correct

### ISSUE THREAD

**Issue by patrickt010** [gatsbyjs/gatsby#17324]
## Description

The example that is given for Plugin Options for gatsby-plugin-catch-links shows 'excludePattern' the expected value is 'excludeRegex'

### Steps to reproduce

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-catch-links

**Comment by universse** [comment]
Thanks for reporting this.
