### ISSUE TITLE
Material-UI v1 example

### ISSUE THREAD

**Issue by cr101** [gatsbyjs/gatsby#1732]
Does anyone have an example showing how you use [Material-UI v1-beta](https://material-ui-1dab0.firebaseapp.com/) with GatsbyJS?

**Comment by inventanew** [comment]
im looking into this as well

**Comment by cr101** [comment]
I noticed that Material-UI v1-beta has [examples](https://github.com/callemall/material-ui/tree/v1-beta/examples) for CRA and NextJS but not GatsbyJS

**Comment by trung674** [comment]
I just followed the [installation guide ](https://material-ui-1dab0.firebaseapp.com/getting-started/installation) and I was able to import components from [AppBar example](https://material-ui-1dab0.firebaseapp.com/getting-started/installation) without any problem.

**Comment by LegNeato** [comment]
I'm using it, but the resulting page is extremely slow to load from AWS. Not sure if treeshaking is working or what.

**Comment by KyleAMathews** [comment]
There's a starter now with Material https://github.com/Vagr9K/gatsby-material-starter

**Comment by oliviertassinari** [comment]
@KyleAMathews It's a starter with https://github.com/mlaursen/react-md. It's not the project linked in the issue description.

**Comment by oliviertassinari** [comment]
Material-UI now hosts an official integration with Gatsby in [/examples/gatsby](https://github.com/mui-org/material-ui/tree/v1-beta/examples/gatsby).

**Comment by deltaskelta** [comment]
for anyone who stumbles here, the updated link for #issuecomment-355858227 is https://github.com/mui-org/material-ui/tree/master/examples/gatsby

**Comment by 1nullpointer** [comment]
Hi , can someone please help with the below issue posted on Stackoverflow for the official starter
Thanks

[Link](https://stackoverflow.com/questions/50931536/gatsbyjs-how-to-pull-in-graphql-data-with-material-ui-lib)

**Comment by rhernandez2015** [comment]
> I just followed the [installation guide ](https://material-ui-1dab0.firebaseapp.com/getting-started/installation) and I was able to import components from [AppBar example](https://material-ui-1dab0.firebaseapp.com/getting-started/installation) without any problem.

This worked for me, best reply by far ❤️

**Comment by NhielSalvana** [comment]
no gatsby plugin needed right?

**Comment by AryanJ-NYC** [comment]
@NhielSalvana I didn't use one and I successfully got it to work. My `Layout.js` looks something like:

```
import React from 'react'
import Helmet from 'react-helmet'
import { MuiThemeProvider } from '@material-ui/core/styles';
import theme from '../themes/default';
import Navbar from '../components/Navbar'

const TemplateWrapper = ({ children }) => (
  <MuiThemeProvider theme={theme}>
    <Helmet title="The WebDev Coach" />
    <Navbar />
    <div>{children}</div>
  </MuiThemeProvider>
);
```

theme/default.js
```
import { createMuiTheme } from '@material-ui/core/styles';

import red from '@material-ui/core/colors/red';

export default createMuiTheme({
  palette: {
    primary: {
      main: '#113643'
    },
    error: red,
  },
});
```

And I wrap `<Layout>` around all pages.

Good luck!

**Comment by ColinTS** [comment]
@AryanJ-NYC Thanks for this, however I have 2 issues
1.(critical) My component is not recognizing the styles defined in my theme, despite having wrapped the layout component just as you.
2. Gatsby hot reloading does not work with material-ui (kind of separate issue, but maybe you figured it out)

Here's my component:
```
import React from 'react'
import { Link } from 'gatsby'
import { withStyles } from '@material-ui/core/styles'
import Layout from '../components/layout'
import Image from '../components/image'

import Button from '@material-ui/core/Button'

const styles = theme => ({
  button: {
    background: theme.palette.secondary[500],
    height: theme.spacing.unit * 7,
  },
})

class IndexPage extends React.PureComponent {
  render() {
    const { classes } = this.props
    return (
      <Layout>
        <h1>Hi people</h1>
        <p>Welcome to your new Gatsby site.</p>
        <p>Now go build something great.</p>
        <div style={{ maxWidth: '300px', marginBottom: '1.45rem' }}>
          <Image />
        </div>
        <Link to="/page-2/">Go to page 2</Link>
        <Button variant="contained" className={classes.button}>
          Yo
        </Button>
      </Layout>
    )
  }
}

export default withStyles(styles)(IndexPage)
```

**Comment by AryanJ-NYC** [comment]
@ColinTS If that didn't work, can you try everything here? https://github.com/mui-org/material-ui/tree/master/examples/gatsby

Please note [`gatsby-ssr.js` ](https://github.com/mui-org/material-ui/blob/master/examples/gatsby/gatsby-ssr.js), [`getPageContext.js`](https://github.com/mui-org/material-ui/blob/master/examples/gatsby/src/getPageContext.js), [`withRoot.js`](https://github.com/mui-org/material-ui/blob/master/examples/gatsby/src/withRoot.js). All necessary.

Also note that this is completely different than what I described above.
