### ISSUE TITLE
Using Layouts with gatsby-theme-mdx-deck

### ISSUE THREAD

**Issue by iamskok** [gatsbyjs/gatsby#17338]
I have a working example of using [gatsby-theme-mdx-deck](https://github.com/jxnblk/mdx-deck/tree/master/packages/gatsby-theme) with [gatsby-plugin-theme-ui](https://theme-ui.com/gatsby-plugin/) setup and manual imports of `Layout` component for each slide.

* [repo](https://github.com/iamskok/jamstack-gatsby-mdx-deck)
* [website](https://jamstack-gatsby-mdx-deck.netlify.com/)

I ran into a problem when I was adding default layout for MDX slides:

```js
// gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-theme-mdx-deck',
      options: {
        contentPath: './src/decks',
        basePath: '/',
        // mdx: false
      }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `decks`,
        path: `${__dirname}/src/decks/`,
      },
    },
    {
      resolve: `gatsby-plugin-page-creator`,
      options: {
        path: `${__dirname}/src/decks`,
      },
    },
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        defaultLayouts: {
          default: require.resolve(`./src/components/Layout.js`),
        }
      }
    }
  ]
}
```

```js
// Layout.js
import React from 'react'
import HeaderButton from './HeaderButton'

export default ({ children }) => (
  <>
    <HeaderButton />

    { children }
  </>
)
```

```bash
Syntax Error: SyntaxError: unknown: Identifier '_frontmatter' has already been declared (111:13)

  109 | MDXContent.isMDXComponent = true;
  110 |
> 111 | export const _frontmatter = {};
      |              ^
  112 |
```

I was able to get rid of the error by setting `mdx = false` in `gatsby-theme-mdx-deck` options, though it broke the actual deck

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_54764/fZ7ajew2ihfCcBzc5b46KUJfH3wYPw/localhost8000%2B2019-09-03%2B00-42-02.png?Expires=1567497600&Signature=Dx112MjRsmK0~s~pNZOLksJ-qf5QZeEFZpwYckDcw9qN2PnNyLvD1iM892EjTFaCyTVvuYv49nuauGTsAO294DmfSYcIW0ABObVDGIBsa-5ugOJtW7F34YE39wW2us5qkZyHx0-wioyFwttIXrkaD~6~ME7rJ9HIhf3HM2fTy7RRpx9UK3pyNT4IDfBJuUb9SFWDGEs99CmIqtzdnh43xdLa6N8J-aaIBOdfnxxlj2ntGoj7~5aEnsDdRPBBENRqgcMnjtwqby4BTx2E0PF8Mw35U9zZHKpSBh~p2PwUWa4EjgnE1OccArSFXm1hwa65~jtS2Yobjxw9-1yRJ3vkKg__&Key-Pair-Id=APKAJBCGYQYURKHBGCOA)

[The branch with non-working implementation of `gatsby-plugin-mdx`](https://github.com/iamskok/jamstack-gatsby-mdx-deck/compare/feature/mdx-layouts?expand=1)

[This issue seems related](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/354)

---

I also get `Multiple versions of Emotion detected, and theming might not work as expected. Please ensure there is only one copy of @emotion/core installed in your application.` warning and would love to know how to get rid of it too.

**Comment by jxnblk** [comment]
I believe this is mostly an issue with MDX Deck, which I don't think current works with the `defaultLayouts` option in `gatsby-plugin-mdx`. As for the warning about Emotion, that was recently introduced, but I think it's a false-positive in this case.

**Comment by iamskok** [comment]
@jxnblk thanks for the clarification!

Should I close this issue and re-open it in [MDX Deck](https://github.com/jxnblk/mdx-deck)?

**Comment by jxnblk** [comment]
@iamskok I think it would make sense to move the issue there, since I think this is mostly due to how MDX Deck splits MDX files up into slides

**Comment by iamskok** [comment]
@jxnblk [MDX Deck issue](https://github.com/jxnblk/mdx-deck/issues/466)
