### ISSUE TITLE
gatsby-remark-embed-snippet: allow embedding snippet files relative to markdown file

### ISSUE THREAD

**Issue by kimbaudi** [gatsbyjs/gatsby#17337]
## Summary

For the [gatsby-remark-embed-snippet](https://www.gatsbyjs.org/packages/gatsby-remark-embed-snippet/) plugin, I would like the ability to embed snippet files that are relative to my markdown file instead of having to specify a directory that all my snippet files must be relative to

### Basic example

Currently, [gatsby-remark-embed-snippet](https://www.gatsbyjs.org/packages/gatsby-remark-embed-snippet/) requires you to specify a `directory` where all snippet files must be relative to. But what I really want is to be able to put my snippet files relative to my markdown files. And I don't want to specify a directory where all snippet files must be located.

The changes to [gatsby-remark-embed-snippet](https://www.gatsbyjs.org/packages/gatsby-remark-embed-snippet/) will be the following:
- no longer require users to specify `directory` option. make it optional.
- if `directory` is not specified, use directory relative to markdown files for code snippets.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

I want greater flexibility in how we organize our snippet files relative to our markdown files using GatsbyJS. Currently, we all have to specify `directory` in order to use this plugin. I don't want to do that. Instead, I want to place snippet files relative to my markdown files where I will embed the snippets.

**Comment by wardpeet** [comment]
Published in gatsby-remark-embed-snippet@4.1.7
