### ISSUE TITLE
"WIndow is not defined" on the server, even when checking if it is "undefined"

### ISSUE THREAD

**Issue by yassinebridi** [gatsbyjs/gatsby#17340]
## Description

I need to use "window" but it is giving me "not defined" in production.
even though i'm checking if window is undefined. 
```javascript
var selectedText
const handleMouseUp = () => {
  selectedText =
    typeof window !== "undefined" ? window.getSelection().toString() : null

  return selectedText
}
```
or 
```javascript
var selectedText
const handleMouseUp = () => {
  if (typeof window !== "undefined") {
    selectedText = window.getSelection().toString()
  }

  return selectedText
}
```
doesn't work.

this is how i'm accessing that function
```jsx
export const P = ({ children }) => {
  const ref = useRef()

  return (
    <PStyled ref={ref} onMouseUp={handleMouseUp}>
      {children}
    </PStyled>
  )
}
```
### Expected result

For the `window` to work as expected on build time

### Actual result

getting `Window is not defined` error

### Environment

```

  System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.2
  npmPackages:
    gatsby: ^2.14.6 => 2.14.6 
    gatsby-image: ^2.2.10 => 2.2.14 
    gatsby-mdx: ^1.0.0 => 1.0.0 
    gatsby-plugin-algolia: ^0.3.3 => 0.3.3 
    gatsby-plugin-feed: ^2.3.11 => 2.3.11 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.2.6 => 2.2.9 
    gatsby-plugin-mdx: ^1.0.31 => 1.0.33 
    gatsby-plugin-nprogress: ^2.1.5 => 2.1.5 
    gatsby-plugin-offline: ^2.2.7 => 2.2.10 
    gatsby-plugin-page-progress: ^2.0.11 => 2.0.11 
    gatsby-plugin-react-helmet: ^3.1.4 => 3.1.5 
    gatsby-plugin-scroll-indicator: ^0.1.3 => 0.1.3 
    gatsby-plugin-sharp: ^2.2.13 => 2.2.18 
    gatsby-plugin-styled-components: ^3.1.3 => 3.1.3 
    gatsby-plugin-typography: ^2.3.5 => 2.3.5 
    gatsby-remark-copy-linked-files: ^2.1.13 => 2.1.13 
    gatsby-remark-images: ^3.1.18 => 3.1.19 
    gatsby-remark-images-medium-zoom: ^1.2.1 => 1.2.1 
    gatsby-remark-images-zoom: ^1.1.0 => 1.1.0 
    gatsby-remark-prismjs: ^3.3.9 => 3.3.9 
    gatsby-remark-reading-time: ^1.0.1 => 1.0.1 
    gatsby-remark-responsive-iframe: ^2.2.10 => 2.2.10 
    gatsby-remark-smartypants: ^2.1.5 => 2.1.5 
    gatsby-source-filesystem: ^2.1.11 => 2.1.18 
    gatsby-source-graphql: ^2.1.11 => 2.1.11 
    gatsby-transformer-remark: ^2.6.19 => 2.6.19 
    gatsby-transformer-sharp: ^2.2.7 => 2.2.12 
  npmGlobalPackages:
    gatsby-cli: 2.7.40

```

**Comment by yassinebridi** [comment]
I found out the problem is not even with the window.getSelection.
it was with this module ` const Popover = require("react-text-selection-popover")`
i just conditionally rendered the module:
`const Popover = typeof window !== 'undefined' ? require("react-text-selection-popover") : null`
the problem is, using null returns this error
https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=null&args[]=

**Comment by herecydev** [comment]
> 
> 
> I found out the problem is not even with the window.getSelection.
> it was with this module ` const Popover = require("react-text-selection-popover")`
> i just conditionally rendered the module:
> `const Popover = typeof window !== 'undefined' ? require("react-text-selection-popover") : null`
> the problem is, using null returns this error
> [https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=null&args[]=](https://reactjs.org/docs/error-decoder.html?invariant=130&args%5B%5D=null&args%5B%5D=)

Can you show the full component?

**Comment by herecydev** [comment]
```js
if (typeof window !== "undefined") {
  var Popover = require("react-text-selection-popover")
}
```

This might work?

**Comment by muescha** [comment]
Here is the error described:

https://www.gatsbyjs.org/docs/debugging-html-builds/

**Comment by yassinebridi** [comment]
@herecydev Yeah, i've tried that too didn't work.
@muescha i tried both examples, didn't work.

I ended up lazy loading the "Popover" component with "@loadable/component":
https://github.com/smooth-code/loadable-components
since it works with SSR.

**Comment by muescha** [comment]
Great. And thx for sharing your solution

Since this a common error `window is undefined` maybe a blog post or enhancement of the docs would be nice....

I will open a new issue for this ...

**Comment by yassinebridi** [comment]
That would be great.

**Comment by muescha** [comment]
You have some code snippets what or how you changed it to loadabke-components?
