### ISSUE TITLE
[docs][tutorial] Better explanation of how to use React Helmet in Gatsby

### ISSUE THREAD

**Issue by brenzy** [gatsbyjs/gatsby#17346]
## Summary

Better explanation of how to use React Helmet in Gatsby

### Motivation

In the tutorial at https://www.gatsbyjs.org/tutorial/part-eight/#add-page-metadata, `3. Use React Helmet in your pages`, the code sample adds Helmet to class `Application`.  This is confusing, and we would be better served with an explanation of how to add Helmet to `seo.js`

**Comment by n8finch** [comment]
I'll grab this one!

**Comment by marcysutton** [comment]
@brenzy can you elaborate on what is confusing about it so we can try to handle it most effectively? We want to understand this deeply before making changes to the tutorial, which was intentionally kept concise to not overwhelm new learners. It's worth noting that it also limits links out to things that offer more information, but aren't required to complete the tutorial steps.

There is a doc on writing an SEO component here: https://www.gatsbyjs.org/docs/add-seo-component/
And there's an issue open to improve the experience of working the SEO: https://github.com/gatsbyjs/gatsby/issues/14125

Let's chat about it, and we'll figure out what to do!

**Comment by brenzy** [comment]
@marcysutton - Up to section 8, the tutorial is very easy to follow.  It walks me through the code that I should add, and explains to me why I should add it and how it works.

When I hit the section on adding metadata, I assumed that I would be given tutorial steps on how to add metadata, and that it would build on the previous sections of the tutorial.  There are steps given to install the plugin and to add it to the config, but there are no tutorial steps given to use the plug-in.  There is a code sample from the React Helmet docs,  that doesn't directly relate to the tutorial, since it is referring to an Application class with a render method.

Not having seen a helmet before, my initial confusion stemmed from the code sample.  Until I went back to the docs, and looked at some sample applications, it wasn't clear to me where or how to add the helmet.  I didn't know if there was some magic application component like the one in the sample code where the helmet belongs, if it should go into a layout component, or if I needed to copy the same helmet information into every page.

The reason I mentioned the SEO page, is because it does have step-by-step information on how to add the helmet.  

However, if there was a step on how to add a helmet to any of the pages in the tutorial, with code that related directly to the tutorial, I think it would also serve to avoid confusion.

**Comment by n8finch** [comment]
@marcysutton and @brenzy , I've got a PR coming later tonight for this (US Central time). Maybe y'all can take a look when it's ready and let me know if that will work. 

Sorry, also, @marcysutton I figured this one was ok to work on because it had been added to "To prioritize", apologies for jumping the gun 😅

**Comment by marcysutton** [comment]
This should be handled with #17730, so I'm going to close it!

**Comment by Loschcode** [comment]
I'm new using Gatsby and React. I'm very confused about this Application class popping up out of nowhere in the tutorial. I've got an `index.tsx` that's all and adding this piece of code doesn't do anything (of course).

I'll eventually find out but I wanted to point out this remark was valid and it's apparently still not handled properly for newcomers.
