### ISSUE TITLE
[docs] Document convenience shortcut `nodes` field

### ISSUE THREAD

**Issue by froddd** [gatsbyjs/gatsby#17342]
The Gatsby schema generator provides a convenience shortcut `nodes` to access items arrays commonly found in `edges` properties: https://github.com/gatsbyjs/gatsby/blob/ac10d3db4f45bf05ca95745363cbc79523f05daa/packages/gatsby/src/schema/__tests__/queries.js#L661

This is missing in the documentation: https://www.gatsbyjs.org/docs/querying-with-graphql/

The convenience shortcut provides a neat, cleaner way of working with resulting data. Consider the following query:

```graphql
query {
  items {
    edges {
      node {
        title
      }
    }
  }
}
```

The resulting data could look like:
```json
{
  "items": {
    "edges": [
      {
        "node": {
          "title": "foo"
        }
      }
    ]
  }
}
```
Accessing the title of the first item is then: `items.edges[0].node.title`

Using the convenience shortcut:
```graphql
query {
  items {
    nodes {
      title
    }
  }
}
```

Results in the following JSON:
```json
{
  "items": {
    "nodes": [
      {
        "title": "foo"
      }
    ]
  }
}
```

Accessing the title of the first item is now: `items.nodes[0].title`

Should this be added to the docs, or is there any reason to discourage this use?

**Comment by markisadesignerd** [comment]
> Should this be added to the docs, or is there any reason to discourage this use?

I've been wondering the same thing. Would love some clarity around this.
