### ISSUE TITLE
Environment variables in MDX

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#17341]
## Summary

Would be great if [`gatsby-plugin-mdx`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx) could make `process.env` available from within JSX.

### Basic example

This would enable use cases like this one:

```mdx
## Contact Map

<iframe
  title="Contact Map"
  src={`https://www.google.com/maps/embed/v1/place?key=${process.env.GATSBY_GOOGLE_MAPS_API_KEY}&q=Santa+Barbara,CA`}
  css="height: 80vh; width: 100%; border: 0;"
/>
```

**Comment by janosh** [comment]
Maybe (`gatsby-plugin-`)`mdx` could use an infrastructure similar to what [CRA uses to make environment variables available in HTML](https://create-react-app.dev/docs/adding-custom-environment-variables/#referencing-environment-variables-in-the-html).

**Comment by johno** [comment]
I'd recommend breaking the iframe out into a component shortcode which will then have [access to environment variables in Gatsby](https://www.gatsbyjs.org/docs/environment-variables/) and can append it to the `src` prop string.

```js
<GoogleMap
  title="Contact Map"
  src='https://www.google.com/maps/embed/v1/place?&q=Santa+Barbara,CA'
/>
```
