### ISSUE TITLE
Lighthouse reports PWA not working

### ISSUE THREAD

**Issue by tr1s** [gatsbyjs/gatsby#17352]
## Description

I don't think plugin-manifest is fully working. According to my lighthouse report there is service worker issues.

This is my code:

```js
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Juno College of Technology`,
        short_name: `Juno College`,
        description: `Juno College of Technology helps talented developers find success in careers they love through community-oriented classroom training and personalized support.`,
        lang: `en`,
        start_url: `/`,
        background_color: `#f7f0eb`,
        theme_color: `#4a455c`,
        display: `standalone`
      }
    },
```

I left out `icons:` because we have different icons for different screens and don't want them to be auto generated, and we want to keep the cache-busting.

### Expected result

I expected that the PWA section of Lighthouse reports would all come back green. It's showing nothing. This is what I'm expecting:

<img width="124" alt="CleanShot 2019-09-03 at 10 52 11@2x" src="https://user-images.githubusercontent.com/19172250/64184164-0e4e9700-ce39-11e9-8f9a-c5ed21313a20.png">

### Actual result

<img width="1439" alt="CleanShot 2019-09-03 at 10 44 03@2x" src="https://user-images.githubusercontent.com/19172250/64183580-178b3400-ce38-11e9-9d28-cb75549e547c.png">

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
    npm: 6.10.3 - ~/.nvm/versions/node/v10.16.2/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.15.1 => 2.15.1
    gatsby-image: ^2.2.15 => 2.2.15
    gatsby-plugin-catch-links: ^2.1.6 => 2.1.6
    gatsby-plugin-manifest: ^2.2.12 => 2.2.12
    gatsby-plugin-netlify: ^2.1.10 => 2.1.10
    gatsby-plugin-offline: ^3.0.0 => 3.0.0
    gatsby-plugin-react-helmet: ^3.1.5 => 3.1.5
    gatsby-plugin-sass: ^2.1.12 => 2.1.12
    gatsby-plugin-sharp: ^2.2.18 => 2.2.18
    gatsby-remark-images: ^3.1.19 => 3.1.19
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-source-contentful: ^2.1.29 => 2.1.29
    gatsby-source-filesystem: ^2.1.18 => 2.1.18
    gatsby-transformer-remark: ^2.6.19 => 2.6.19
    gatsby-transformer-sharp: ^2.2.12 => 2.2.12
  npmGlobalPackages:
    gatsby-cli: 2.7.39
```

What can I do in order for Google to pick up that this is a PWA?

**Comment by lannonbr** [comment]
So `gatsby-plugin-manifest` isn't actually the one adding a service worker. that is the job of `gatsby-plugin-offline` which seems you have installled so you just need to add it to your `gatsby-config`. Try doing such, deploying it (either locally with gatsby build & gatsby serve or remotely), and then try running lighthouse again

**Comment by tr1s** [comment]
@lannonbr Those results were with `gatsby-plugin-offline` being in the config, it's just way at the bottom so I didn't add it in the original post. It's being deployed on a Netlify preview branch and that's how I'm testing it.

Any other reasons why this wouldn't be working properly?

**Comment by lannonbr** [comment]
Well can you manually check if the service worker is being installed on that preview deploy?

**Comment by tr1s** [comment]
This is my console.

The icons missing are because I took out that line. Is there a way I can disable it?

Also we have code that removes a service worker, but that happens before the new `gatsby-plugin-offline` service worker activates. So it's there!

<img width="681" alt="CleanShot 2019-09-03 at 11 44 11@2x" src="https://user-images.githubusercontent.com/19172250/64188344-3a214b00-ce40-11e9-84e1-db3705c99007.png">

<img width="681" alt="CleanShot 2019-09-03 at 11 47 40@2x" src="https://user-images.githubusercontent.com/19172250/64188577-aef48500-ce40-11e9-92cd-8db331cbceb7.png">

Just tested again, still getting an N/A for Lighthouse PWA.

**Comment by tr1s** [comment]
Turns out it was that code removing service workers that was the issue. I thought since it was doing it before that the new one created will still work properly.

This issue can be closed now, but I have two questions that I hope anyone can help answer:

We were having an issue where the old temporary static (non-gatsby) landing page was being shown even when the new website was deployed. The old website was using [webpack-offline-plugin](https://github.com/NekR/offline-plugin). We figured out that the ServiceWorker was constantly re-registering or cached no matter what. So on hard-refresh the new website would show up, and on regular refresh the old website would show up. We dealt with that by automatically unregistering SW's on page load.

1. **Do you think that this new offline-plugin service worker will override/cache-bust the old site?** This was happening a few weeks back, and we don't really have anymore devices to test cause the removing SW code already fixed all the devices.

2. Is there anyway I can disable the "icons" feature so it doesn't show that icons are missing in the console? Was that the best way to go about things if we're already all of our favicons being loaded into the ``gatsby-plugin-react-helmet`,` ?

**Comment by moonmeister** [comment]
@tr1s FYI: `icons` is part of the manifest spec and required as far as i know. there's no other way to add manifest spec icons. If you don't want the plugin to generate various sizes of icons simply don't include the `icon` property (icon is our own config option and not part of the spec). when icon is included your can leave out icons but it's added in automatically by the plugin later from it's defaults.

if you don't want the plugin to automatically generate the favicon that can be disabled along with the theme_color tag if you want to manage those things iteratively.
