### ISSUE TITLE
warning in console during dev and build

### ISSUE THREAD

**Issue by universse** [gatsbyjs/gatsby#17373]
I'm getting warnings for all pages.

`warn Attempting to create page "/.../", but page "/..." already exists. This could lead to non-deterministic routing behavior`

`gatsby: 2.15.6`

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by universse** [comment]
It's something to do with the latest version gatsby@2.15.6 and gatsby-plugin-remove-trailing-slashes.
Here's [repro](https://codesandbox.io/s/gatsby-starter-default-t1be6). When I downgrade gatsby or remove gatsby-plugin-remove-trailing-slashes, there's no warning.

**Comment by universse** [comment]
Something like this
![image](https://user-images.githubusercontent.com/15166715/64268424-a26c4b80-cf6a-11e9-8fa5-1f1698d189b0.png)

**Comment by ArthurHwang** [comment]
Getting the same warning, @universse thanks for supplying information that its gatsby-plugin-remove-trailing-slashes thats causing it.

**Comment by wardpeet** [comment]
@universse is this just a warning or also breaks things? (if it breaks we'll revert the PR for now)

**Comment by universse** [comment]
It's just a warning. But think I have found out the root cause. Will create a PR.

**Comment by wardpeet** [comment]
Published in gatsby@2.15.11

**Comment by neb-b** [comment]
I'm seeing this after upgrading to gatsby 3. I have a reproduction here https://github.com/neb-b/gatsby-starter-blog which is a fork of `gatsby-starter-blog` and 1 commit that adds `gatsby-plugin-remove-trailing-slashes`

I also see the same warnings when trying to remove them on my own with this snippet from the gatsby docs
https://www.gatsbyjs.com/docs/creating-and-modifying-pages/#removing-trailing-slashes

**Comment by timmywil** [comment]
I think I know the problem. `deletePage` and `createPage` are async but the plugin is calling them as if they were sync. Changing to the following fixes the issue:

```js
const replacePath = (path) => (path === '/' ? path : path.replace(/\/$/, ''))

exports.onCreatePage = async ({ page, actions }) => {
  const { createPage, deletePage } = actions

  const oldPage = Object.assign({}, page)
  page.path = replacePath(page.path)
  if (page.path !== oldPage.path) {
    await deletePage(oldPage)
    await createPage(page)
  }
}
```

In other words, the warnings are because `createPage` is called before `deletePage` has completed.

**Comment by neb-b** [comment]
@timmywil Thanks for the comment. I'm still seeing those warnings with that though

**Comment by timmywil** [comment]
@neb-b Yea, I started making a PR based on that theory, but the problem is more complicated. My newest Pr simply disables the warning until removing trailing slashes has first-class support in core.
