### ISSUE TITLE
There was a problem loading the local develop command

### ISSUE THREAD

**Issue by JaybeeClassical** [gatsbyjs/gatsby#17372]
## Recoded my portfolio page in my gatsby site and tried to run but got an error, so i decided to use my Source control on Visual studio code to undo my code changes and then ran my gatsby site but got an error 

> C:\Users\Jaybee\Desktop\Projects\IamJude>gatsby develop

> 
>  ERROR 
> 
> There was a problem loading the local develop command. Gatsby may not be installed in your site's "node_modules" directory. Perhaps you need to run "npm install"? You might need to delete your "package-lock.json" as well.

I went future to update my npm using "npm install update" but got an error messages 
*C:\Users\Jaybee\Desktop\Projects\IamJude>npm install update
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.2.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm ERR! path C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\events\npm-shrinkwrap.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open
npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\events\npm-shrinkwrap.json'
npm ERR!  [OperationalError: EPERM: operation not permitted, open 'C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\events\npm-shrinkwrap.json'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, open 'C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\events\npm-shrinkwrap.json'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'open',
npm ERR!     path: 'C:\\Users\\Jaybee\\Desktop\\Projects\\IamJude\\node_modules\\@types\\events\\npm-shrinkwrap.json'
npm ERR!   },
npm ERR!   isOperational: true,
npm ERR!   stack: "Error: EPERM: operation not permitted, open 'C:\\Users\\Jaybee\\Desktop\\Projects\\IamJude\\node_modules\\@types\\events\\npm-shrinkwrap.json'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\Jaybee\\Desktop\\Projects\\IamJude\\node_modules\\@types\\events\\npm-shrinkwrap.json',
npm ERR!   parent: '@types/glob'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jaybee\AppData\Roaming\npm-cache\_logs\2019-09-04T02_14_48_339Z-debug.log

C:\Users\Jaybee\Desktop\Projects\IamJude>gatsby develop

 ERROR 

There was a problem loading the local develop command. Gatsby may not be installed in your site's "node_modules" directory. Perhaps you need to run "npm install"? You might need to delete your "package-lock.json" as well.

C:\Users\Jaybee\Desktop\Projects\IamJude>gatsby develop

 ERROR 

There was a problem loading the local develop command. Gatsby may not be installed in your site's "node_modules" directory. Perhaps you need to run "npm install"? You might need to delete your "package-lock.json" as well.

C:\Users\Jaybee\Desktop\Projects\IamJude>npm install
npm ERR! path C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\configstore\npm-shrinkwrap.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open
npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\configstore\npm-shrinkwrap.json'
npm ERR!  [OperationalError: EPERM: operation not permitted, open 'C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\configstore\npm-shrinkwrap.json'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, open 'C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\configstore\npm-shrinkwrap.json'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'open',
npm ERR!     path: 'C:\\Users\\Jaybee\\Desktop\\Projects\\IamJude\\node_modules\\@types\\configstore\\npm-shrinkwrap.json'
npm ERR!   },
npm ERR!   isOperational: true,
npm ERR!   stack: "Error: EPERM: operation not permitted, open 'C:\\Users\\Jaybee\\Desktop\\Projects\\IamJude\\node_modules\\@types\\configstore\\npm-shrinkwrap.json'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\Jaybee\\Desktop\\Projects\\IamJude\\node_modules\\@types\\configstore\\npm-shrinkwrap.json',
npm ERR!   parent: 'devcert-san'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jaybee\AppData\Roaming\npm-cache\_logs\2019-09-04T02_31_48_166Z-debug.log
*
Also ran npm install and got another error message
*
C:\Users\Jaybee\Desktop\Projects\IamJude>npm install
npm ERR! path C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\configstore\npm-shrinkwrap.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open
npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\configstore\npm-shrinkwrap.json'
npm ERR!  [OperationalError: EPERM: operation not permitted, open 'C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\configstore\npm-shrinkwrap.json'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, open 'C:\Users\Jaybee\Desktop\Projects\IamJude\node_modules\@types\configstore\npm-shrinkwrap.json'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'open',
npm ERR!     path: 'C:\\Users\\Jaybee\\Desktop\\Projects\\IamJude\\node_modules\\@types\\configstore\\npm-shrinkwrap.json'
npm ERR!   },
npm ERR!   isOperational: true,
npm ERR!   stack: "Error: EPERM: operation not permitted, open 'C:\\Users\\Jaybee\\Desktop\\Projects\\IamJude\\node_modules\\@types\\configstore\\npm-shrinkwrap.json'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\Jaybee\\Desktop\\Projects\\IamJude\\node_modules\\@types\\configstore\\npm-shrinkwrap.json',
npm ERR!   parent: 'devcert-san'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jaybee\AppData\Roaming\npm-cache\_logs\2019-09-04T02_31_48_166Z-debug.log

*
### Environment: VsCode, git bash terminal, command prompt
OS: windows 10

Please i need help on this urgently

**Comment by marcysutton** [comment]
Hi there, what Node version are you using? Are you using [gatsby-cli](https://www.gatsbyjs.org/docs/gatsby-cli/) globally?

Here are a couple of things you could try:

- Check that gatsby-cli is installed on your PATH by running `gatsby --help`, see if it has the same error
- If it's a problem with a dependency, delete the `node_modules` folder in your project as well as the `package-lock.json` file, run `gatsby clean` to delete the cache, run `npm install` and `gatsby develop` again.

**Comment by JaybeeClassical** [comment]
C:\Users\Jaybee\Desktop\Projects\IamJude>gatsby --version
Gatsby CLI version: 2.7.30
Gatsby version: unknown
  Note: this is the Gatsby version for the site at: C:\Users\Jaybee\Desktop\Projects\IamJude

node version: v12.8.1

Ran the gatsby --help and got 
C:\Users\Jaybee\Desktop\Projects\IamJude>gatsby --help

> Usage: gatsby <command> [options]
> 
> Commands:
>   gatsby develop                   Start development server. Watches files, rebuilds, and hot reloads if something changes
>   gatsby build                     Build a Gatsby project.
>   gatsby serve                     Serve previously built Gatsby site.
>   gatsby info                      Get environment information for debugging and issue reporting
>   gatsby clean                     Wipe the local gatsby environment including built assets and cache
>   gatsby repl                      Get a node repl with context of Gatsby environment, see (https://www.gatsbyjs.org/docs/gatsby-repl/)
>   gatsby new [rootPath] [starter]  Create new Gatsby project.
>   gatsby plugin                    Useful commands relating to Gatsby plugins
>   gatsby telemetry                 Enable or disable Gatsby anonymous analytics collection.
> 
> Options:
>   --verbose                Turn on verbose output                                                                                 [boolean] [default: false]  --no-color, --no-colors  Turn off the color in output                                                                           [boolean] [default: false]  -h, --help               Show help                                                                                                               [boolean]  -v, --version            Show the version of the Gatsby CLI and the Gatsby package in the current project  


deleted the node_modules and package-lock.json files and ran gatsby clean but same error appeared

**Comment by JaybeeClassical** [comment]
Npm install worked just fine now, thank you

**Comment by najimali** [comment]
@marcysutton Thank you it worked for me😊

**Comment by yakuban1** [comment]
Thanks a lot
It worked for me

**Comment by epomschar** [comment]
**Hi all, I have the same issue at the moment.** 
I did as recommended:



> Hi there, what Node version are you using? Are you using [gatsby-cli](https://www.gatsbyjs.org/docs/gatsby-cli/) globally?
> 
> Here are a couple of things you could try:
> 
> * Check that gatsby-cli is installed on your PATH by running `gatsby --help`, see if it has the same error
> * If it's a problem with a dependency, delete the `node_modules` folder in your project as well as the `package-lock.json` file, run `gatsby clean` to delete the cache, run `npm install` and `gatsby develop` again.

that did not help.

When I run the comand `gatsby -v` I get 
```
Gatsby CLI version: 3.5.0
Gatsby version: unknown
```
may Gatsby version is: `"gatsby": "^2.32.3",` 

When I run `gatsby develop` I get:
```
There was a problem loading the local develop command. Gatsby may not be installed in your site's "node_modules" directory. Perhaps you need to run
"npm install"? You might need to delete your "package-lock.json" as well.
```

The problem is, when I remove `node_modules` and `package-lock.json` I am unable to install the modules and install fails at the same point:
```
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm ERR! code 1
npm ERR! path /Users/evschar/Documents/www/sandra-www/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
```

or

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @babel/core@7.12.9
npm ERR! node_modules/@babel/core
npm ERR!   @babel/core@"7.12.9" from @mdx-js/mdx@1.6.22
npm ERR!   node_modules/@mdx-js/mdx
npm ERR!     @mdx-js/mdx@"^1.6.22" from the root project
npm ERR!     peer @mdx-js/mdx@"^1.0.0" from gatsby-plugin-mdx@1.10.1
npm ERR!     node_modules/gatsby-plugin-mdx
npm ERR!       gatsby-plugin-mdx@"^1.10.0" from the root project
npm ERR!   @babel/core@"^7.12.3" from gatsby@2.32.13
npm ERR!   node_modules/gatsby
npm ERR!     gatsby@"^2.32.3" from the root project
npm ERR!     peer gatsby@">=2.0.33" from gatsby-plugin-material-ui@2.1.10
npm ERR!     node_modules/gatsby-plugin-material-ui
npm ERR!       gatsby-plugin-material-ui@"^2.1.10" from the root project
npm ERR!     10 more (gatsby-plugin-react-helmet, gatsby-plugin-sharp, ...)
npm ERR!   26 more (gatsby-plugin-mdx, @babel/plugin-syntax-jsx, ...
```

I am really desperate as I have been working on a project for two months. 


It must be something internal as the project runs on Gatsby Cloud. I just cannot install and run the project locally.

Is there anyone out there to help?


Thank you
