### ISSUE TITLE
feat(gatsby): override default options of gatsby-plugin-page-creator

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#17379]
## Summary
When a user specifies a `gatsby-plugin-page-creator` plugin with a path pointing to `src/pages` we replace the config of our default `gatsby-plugin-page-creator` in gatsby core. This allows people to add `ignore` options.

A step in the right direction:
1) open https://github.com/gatsbyjs/gatsby/blob/abf888147de0c87d5c8560eaf2de18a0da4b5fca/packages/gatsby/src/bootstrap/load-plugins/load.js
2) find a `gatsby-plugin-page-creator` plugin with the path pointing to src/pages and temporary save the config in a variable
3) Replace the options on line (https://github.com/gatsbyjs/gatsby/blob/abf888147de0c87d5c8560eaf2de18a0da4b5fca/packages/gatsby/src/bootstrap/load-plugins/load.js#L217) with your variable.
4) write tests to make sure this works correctly.

### Basic example
```js
// in gatsby-config.js
{
  plugins: [{
    resolve: require.resolve(`gatsby-plugin-page-creator`),
    options: {
      path: `${__dirname}/src/pages`,
      ignore: [`**/examples/**`],
    },
  }]
}
```
Should change the default `gatsby-plugin-page-creator` config in 
https://github.com/gatsbyjs/gatsby/blob/abf888147de0c87d5c8560eaf2de18a0da4b5fca/packages/gatsby/src/bootstrap/load-plugins/load.js#L214-L222

Outcome should be
```js
  plugins.push(
    processPlugin({
      resolve: require.resolve(`gatsby-plugin-page-creator`),
      options: {
        path: slash(path.join(program.directory, `src/pages`)),
        ignore: [`**/examples/**`],
      },
    })
  )
```

### Motivation
We get a lot of requests to override the default `gatsby-plugin-page-creator` plugin. At this point we don't offer a good solution for this problem, there is a workaround but it's not fixing all use cases.

**Comment by akshayymahajan** [comment]
Hey @wardpeet! I would like to work on this issue.

**Comment by wardpeet** [comment]
Nice! Please let us know if we can assist with anything. We suggest opening a draft/WIP PR if you having questions so we can give pointers on specific areas.

Thank you for contributing! ❤️

**Comment by akshayymahajan** [comment]
My PR is failing e2e tests even though all other tests are passing in my local dev environment. Any idea @wardpeet

**Comment by sidharthachatterjee** [comment]
Fixed and published in `gatsby@2.15.11` thanks to @akshayymahajan 🥇

**Comment by karlhorky** [comment]
Thanks @siddharthkp @akshayymahajan @wardpeet !

This is working with the following config in my `gatsby-config.js` (needed to remove the `require.resolve` from @wardpeet's first description):

```js
{
  resolve: `gatsby-plugin-page-creator`,
  options: {
    path: `${__dirname}/src/pages`,
    ignore: [`**/examples/**`],
  },
},
```

**Comment by siddharthkp** [comment]
@karlhorky We meet again! Put you've got the wrong Sid this time 😛 (you want @sidharthachatterjee)

**Comment by karlhorky** [comment]
🤦‍♂️ Ah oops, sorry Siddharth! Tagged Sidhartha now.

**Comment by karlhorky** [comment]
Ah this feature seems to be broken with Gatsby `4.9.0` and the TypeScript configs: https://github.com/gatsbyjs/gatsby/discussions/34613#discussioncomment-2275411
