### ISSUE TITLE
Not able to run local environment

### ISSUE THREAD

**Issue by DomanskaGrzyb** [gatsbyjs/gatsby#17381]
### Description

After downloading the project, I'm not able to run it locally on my machine.

### Steps to reproduce

Download project locally (so there is no `node_modules` folder and `package-lock.json` file), then run

1. npm install
2. gatsby develop

### Expected result

I should be able to run project at localhost

### Actual result

```
(sharp:3359): GLib-GObject-WARNING **: 15:48:17.029: cannot register existing type 'VipsObject'

(sharp:3359): GLib-CRITICAL **: 15:48:17.029: g_once_init_leave: assertion 'result != 0' failed

(sharp:3359): GLib-GObject-CRITICAL **: 15:48:17.029: g_type_register_static: assertion 'parent_type > 0' failed

(sharp:3359): GLib-CRITICAL **: 15:48:17.029: g_once_init_leave: assertion 'result != 0' failed
```

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.3.23 => 2.15.6
    gatsby-image: ^2.0.29 => 2.2.17
    gatsby-plugin-drift: ^1.0.0 => 1.0.0
    gatsby-plugin-favicon: ^3.1.5 => 3.1.6
    gatsby-plugin-google-tagmanager: ^2.0.10 => 2.1.8
    gatsby-plugin-manifest: 2.0.16 => 2.0.16
    gatsby-plugin-netlify: 2.0.7 => 2.0.7
    gatsby-plugin-netlify-cache: 1.0.0 => 1.0.0
    gatsby-plugin-no-sourcemaps: ^2.0.2 => 2.1.1
    gatsby-plugin-offline: ^2.0.25 => 2.2.10
    gatsby-plugin-react-helmet: 3.0.5 => 3.0.5
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-segment-js: ^3.0.1 => 3.0.1
    gatsby-plugin-sharp: 2.2.19 => 2.2.19
    gatsby-plugin-sitemap: ^2.0.10 => 2.2.10
    gatsby-plugin-styled-components: 3.0.4 => 3.0.4
    gatsby-plugin-typography: 2.2.6 => 2.2.6
    gatsby-source-filesystem: ^2.0.28 => 2.1.21
    gatsby-source-storyblok: ^0.1.3 => 0.1.4
    gatsby-transformer-sharp: ^2.1.13 => 2.2.13
  npmGlobalPackages:
    gatsby-cli: 2.7.31

**Comment by fartinmartin** [comment]
I was running into this too. A bit of searching lead me to [this comment](https://github.com/lovell/sharp/issues/1725#issuecomment-498018318) on an issue in the `sharp` repo. When I ran `npm ls sharp` it found two different versions in my dependencies:
- `0.23.0` for `gatsby-plugin-sharp@2.2.19` and `gatsby-transformer-sharp@2.2.13`
- `0.22.1` for `gatsby-plugin-favicon@3.1.6`

Removing `gatsby-plugin-favicon` from my `gatsby.config.js` resulted in no error and I was able to use `sharp` related features.

**Comment by tranthaison1231** [comment]
I have same issue with you, But when I use `npm ls sharp`. It's found same versio in nodemodules. But it's still not working. 

 gatsby-plugin-manifest@2.2.13
│ └── sharp@0.23.0 
└─┬ gatsby-plugin-sharp@2.2.19
  └── sharp@0.23.0  deduped

**Comment by DomanskaGrzyb** [comment]
What helped me solve my issue was [this thread](https://github.com/gatsbyjs/gatsby/issues/16957).

I changed version of sharp to `gatsby-plugin-sharp@2.2.14` and installed node modules once again.
