### ISSUE TITLE
Show in Editor of WordPress the same as I created in gatsby

### ISSUE THREAD

**Issue by lpluispacheco** [gatsbyjs/gatsby#17399]
Hi,

I'm creating pages in Gatsby a couple of months ago and now I'm using the CMS of WordPress, I have everything connected and working perfectly.

My question is, how can I show the page exactly the same as I have created in Gatsby? i.e: A new page that I created with components in Gatsby and other stuff, I want to edit the content in the editor of the CMS Wordpress and it's displayed exactly is showed in the main page but inside of the editor.

Any ideas? Thanks

Best regards,
Luis.

**Comment by LekoArts** [comment]
I don't think it's possible what you're asking for (at least with Wordpress currently). You use Wordpress as a Headless CMS so you only have the communication `Wordpress => Gatsby` and not the other way around. Does that things clear up?

**Comment by lpluispacheco** [comment]
> I don't think it's possible what you're asking for (at least with Wordpress currently). You use Wordpress as a Headless CMS so you only have the communication `Wordpress => Gatsby` and not the other way around. Does that things clear up?

Yes, after deep search in Google I figure out that it's imposible so far.

Thanks for answer @LekoArts
