### ISSUE TITLE
how to create a nested page like `/blog/all` ?

### ISSUE THREAD

**Issue by deebov** [gatsbyjs/gatsby#17390]
Hi there

I have `blog.js` under my the pages directory. But I also need to create a page to show articles. Is there a way to create a page under this url `/blog/all` ??

**Comment by lannonbr** [comment]
I believe you can have a structure like such:

`src/pages/blog/index.js` which routes to /blog

and

`src/pages/blog/all.js` that routes to /blog/all

**Comment by deebov** [comment]
thanks @lannonbr it helped
