### ISSUE TITLE
page-data.json files not deleted with pages

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/gatsby#17402]
## Description

I left a comment in #10844 but realized this is actually a separate issue.
When creating a page from a node and then deleting that node in a subsequent build, the page is deleted but it's `page-data.json` remains. The result of this is that pages aren't fully deleted. The html for the page is removed but the pages data remains. If you visit a page that should be deleted you'll see the 404 page, and then the deleted page will load afterwards.

This is related to the global page manifest updates in Gatsby 2.9.0 (https://www.gatsbyjs.org/blog/2019-06-12-performance-improvements-for-large-sites/), as the issue isn't present in v2.8.8  (the last version before 2.9.0) since there is a `manifest.json` file instead of individual `page-data.json` files.

If I manually go into the `public/page-data` directory and delete the corresponding `page-data.json` file, the issue goes away (although Gatsby still tries to fetch this file).

### Steps to reproduce

- Create a page from a node in a GraphQL query in `gatsby-node.js` using the `createPages` api
- Run `gatsby build`
- Make sure the node that created that page will be fully deleted or not recreated in the next build
- Run `gatsby build && gatsby serve`
- Visit the deleted page to see it load in after the 404 page

### Expected result

The corresponding `page-data.json` file should be deleted and the deleted page shouldn't load.

### Actual result

The deleted page loads.

### Environment

```

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.1
    Safari: 12.1.1
  npmGlobalPackages:
    gatsby-cli: 2.7.44

```

For now I'm just using Gatsby@2.8.8 but this seems like an important one! I noticed this affecting a couple of my projects already as well as a barebones test repo I made with `gatsby-source-wordpress`.

**Comment by GKJCJG** [comment]
Looking at the PR code, it looks like this is viewed as a separate issue from deleting pages while hot reloading, but a similar problem occurs in that scenario. It seems that deleting the underlying asset (markdown file, in my case) leaves the page-data.json untouched, so the page continues to be served. Ideally, I think that if you delete the underlying asset while on the page in a development server, the dev-404 page should appear in place of the now-deleted content. Does that fall within the scope of this issue, or should I open a separate issue?

**Comment by TylerBarnes** [comment]
@GKJCJG I think it falls within the scope of this issue. The linked PR has potential performance issues so a fix for this needs to be rethought. Like you mention, we should also add a fix for during development. I haven't had time to work on this recently so I'm removing myself as an assignee. @pvdz maybe you can think of a good way to do this since you're a performance wizard?

**Comment by pvdz** [comment]
The thing that stands out to me is looping through all the pages and filtering certain cases. That's going to be painful for large sites. I wonder why this couldn't just immediately delete the page, or queue an action to do so afterwards, rather than filtering all pages. In any scenario.

**Comment by GKJCJG** [comment]
Re: a fix for the development use case, I posted a comment over on [Issue 10844](https://github.com/gatsbyjs/gatsby/issues/10844) suggesting that the problem was with a race condition where the page delete is queued and executed before a query to pages is run to determine which page-data.json to delete, so that the query to pages fails.

**Comment by probablyup** [comment]
I think this relates to some unbounded cache growth issues we've been seeing in CI.

**Comment by probablyup** [comment]
@pieh could you comment on this one?

**Comment by josephmarkus** [comment]
Just ran into the same - deleted page that has a corresponding page-data.json would load soon after user sees 404 page. Are there any updates on this?

**Comment by pieh** [comment]
Oh, I missed this issue. https://github.com/gatsbyjs/gatsby/pull/26937 which we merged and released few days ago was looking to fix this problem. It was released in `gatsby@2.24.65`. So please upgrade and let us know if the problem is fixed completely. If you already are on this version and it's not fixed - please let us know too (ideally with some steps to reproduce)

**Comment by pieh** [comment]
To add to above - the PR I linked above only handled `gatsby build` part - similar issue still is there in `gatsby develop` (but if you mix develop and build, the build should clean everything).

**Comment by josephmarkus** [comment]
Thanks @pieh! Will give an upgrade a go!

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
