### ISSUE TITLE
I use npm start but I have error same this. I think this is problem with sharp modules. Please help me!

### ISSUE THREAD

**Issue by tranthaison1231** [gatsbyjs/gatsby#17403]
(sharp:10119): GLib-GObject-WARNING **: 12:04:03.253: cannot register existing type 'VipsObject'

(sharp:10119): GLib-CRITICAL **: 12:04:03.253: g_once_init_leave: assertion 'result != 0' failed

(sharp:10119): GLib-GObject-CRITICAL **: 12:04:03.253: g_type_register_static: assertion 'parent_type > 0' failed

(sharp:10119): GLib-CRITICAL **: 12:04:03.253: g_once_init_leave: assertion 'result != 0' failed

**Comment by fartinmartin** [comment]
Related: #17381

**Comment by LekoArts** [comment]
Please try the solutions in this issue https://github.com/gatsbyjs/gatsby/issues/16957
If that doesn't help, please comment there. Thanks!

Marking this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/16957
