### ISSUE TITLE
feat(gatsby-image): Have 'itemProp' attribute also rendered in HTML

### ISSUE THREAD

**Issue by nathanfoon** [gatsbyjs/gatsby#17419]
## Summary

With the current [`itemProp` implementation](https://github.com/gatsbyjs/gatsby/pull/11296) in gatsby-image, the `itemprop` HTML attribute is applied to the `<img>` after the JS (ie, lazyloading) is run. I think it would be worthwhile to also apply the attribute to the `<img>` that lives in `<noscript>` tag; that way, it's already in the source and ready for search engines to crawl.

### Motivation

It's unclear whether or not structured data—microdata format, specifically—that is added via JS is readable by search engines.

According to [Google's docs](https://developers.google.com/search/docs/guides/intro-structured-data#structured-data-format) and a [discussion in a Google forum](https://support.google.com/webmasters/forum/AAAA2Jdx3sUgsdps9ncUQA/?hl=en&gpf=%23!topic%2Fwebmasters%2Fgsdps9ncUQA), it's possible if the format is JSON-LD but there's no info on it working with microdata.

**Comment by jamessimone** [comment]
@nathanfoon I agree that this would be useful. I just submitted a PR - #18035 - to try to have this addressed
