### ISSUE TITLE
JSX(TSX) component cannot be resolved inside MDX file

### ISSUE THREAD

**Issue by rGustave07** [gatsbyjs/gatsby#17427]
## Description

I'm trying to use some JSX inside of MDX but I receive a webpack error that the component cannot be resolved. I apologize as I don't have this in a repo but I can give my configurations

gatsby-config.js:
```

module.exports = {
    siteMetadata: {
        title: `FEM Gatsby`,
        description: `A thing built for practice with gatsby... and what not`,
        author: `Ritter`,
    },
    plugins: [
        `gatsby-plugin-sass`,
        `gatsby-plugin-typescript`,
        `gatsby-plugin-react-helmet`,
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `images`,
                path: `${__dirname}/src/images`,
            },
        },
        `gatsby-transformer-sharp`,
        `gatsby-plugin-sharp`,
        {
            resolve: `gatsby-plugin-manifest`,
            options: {
                name: `gatsby-starter-default`,
                short_name: `starter`,
                start_url: `/`,
                background_color: `#663399`,
                theme_color: `#663399`,
                display: `minimal-ui`,
                icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
            },
        },
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `pages`,
                path: `${__dirname}/src/pages/`,
            },
        },
        {
            resolve: `gatsby-plugin-mdx`,
            options: {
                defaultLayouts: {
                    default: require.resolve(
                        "./src/components/Layout/Layout.tsx"
                    ),
                },
            },
        },
        // this (optional) plugin enables Progressive Web App + Offline functionality
        // To learn more, visit: https://gatsby.dev/offline
        // `gatsby-plugin-offline`,
    ],
};
```

contact.mdx
```
> > import Wave from '../components/Wave/wave.tsx'
> 
> > # Contact Me
> > 
> > You can get in touch with me by opening the nearest window and yelling out of it real loud.
> > 
> > ## Or wave to me
> > Click this button to simulate wave.
> > 
> > <Wave />
> > 
> > Please note that I may not wave back.
> > 
.
```

### Expected result
 
 Expected contact.mdx to load with wave.tsx inside it

### Actual result

>  ERROR #98123  WEBPACK
> 
> Generating SSR bundle failed
> 
> Can't resolve '..\..\..\..\src\components\wave' in 'C:\Program Files\Git_Repos\gatsby-practice\.cache\caches\gatsby-plugin-mdx\mdx-scopes-dir'
> 
> File: .cache\caches\gatsby-plugin-mdx\mdx-scopes-dir\4cc3d760face17e367d17f70237697b6.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating SSR bundle failed
> 
> Can't resolve '..\..\..\..\src\components\wave' in 'C:\Program Files\Git_Repos\gatsby-practice\.cache\caches\gatsby-plugin-mdx\mdx-scopes-dir'
> 
> File: .cache\caches\gatsby-plugin-mdx\mdx-scopes-dir\7be19439e290e53194700ae646169f1d.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating SSR bundle failed
> 
> Can't resolve '..\..\..\..\src\components\wave.tsx' in 'C:\Program Files\Git_Repos\gatsby-practice\.cache\caches\gatsby-plugin-mdx\mdx-scopes-dir'
> 
> File: .cache\caches\gatsby-plugin-mdx\mdx-scopes-dir\16ada7e453ba88bce425ed412daff4c8.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating SSR bundle failed
> 
> Can't resolve '..\..\..\..\src\src\components\Wave\wave.tsx' in 'C:\Program Files\Git_Repos\gatsby-practice\.cache\caches\gatsby-plugin-mdx\mdx-scopes-dir'
> 
> File: .cache\caches\gatsby-plugin-mdx\mdx-scopes-dir\0a9109dfff2b75415d158c620680e3e6.js
> 
> ⠙ start webpack server
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! gatsby-starter-default@0.1.0 develop: `gatsby develop`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the gatsby-starter-default@0.1.0 develop script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Ritter\AppData\Roaming\npm-cache\_logs\2019-09-05T19_26_39_981Z-debug.log

**Comment by teoboley** [comment]
How were you able to resolve this? I'm having the same problem

**Comment by ooloth** [comment]
@rGustave07 @teoboley I'm having this issue as well. Did either of you find a solution?

**Comment by teoboley** [comment]
I haven't - I resorted to using the mdx plugin to parse only mdx files, or only add components in jsx format. If anyone ever finds a solution, I'd love to hear it!

**Comment by ooloth** [comment]
@teoboley In my case, I'd forgotten to add `gastby-plugin-typescript` to the `plugins` array in `gatsby-config`. 🤦‍♂ 

Once I added that line, everything works and I'm able to import and use `.tsx` components in my `.mdx` files.

**Comment by teoboley** [comment]
@ooloth Thanks for the tip - I've been using [gatsby-plugin-atl](https://www.gatsbyjs.org/packages/gatsby-plugin-atl/) since it adds type checking to the compiler instead of relying on the editor.

I'll see if I can look into getting that to work in a similar way, regardless I'm glad you figured it out for your use-case 👍🏻.
