### ISSUE TITLE
[gatsby-plugin-sass] Autoprefixer does not add '-ms' prefix to grid on build

### ISSUE THREAD

**Issue by claygiffin** [gatsbyjs/gatsby#17428]
## Description

I was able to configure gatsby-plugin-sass to add ```-ms``` prefixes to my grid elements by using ```/* autoprefixer grid: autoplace */```, and they show up fine when I run ```gatsby develop```.

However, when I run ```gatsby build``` the prefixes no longer show up. 

### Environment

  System:
    OS: macOS 10.14.4
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.1 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 65.0
    Safari: 12.1
  npmPackages:
    gatsby: ^2.15.4 => 2.15.4 
    gatsby-image: ^2.2.16 => 2.2.16 
    gatsby-plugin-manifest: ^2.2.13 => 2.2.13 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.6 => 3.1.6 
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2 
    gatsby-plugin-sass: ^2.1.13 => 2.1.13 
    gatsby-plugin-sharp: ^2.2.19 => 2.2.19 
    gatsby-source-filesystem: ^2.1.19 => 2.1.19 
    gatsby-source-prismic: ^2.3.0-alpha.3 => 2.3.0-alpha.3 
    gatsby-transformer-sharp: ^2.2.13 => 2.2.13 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by LekoArts** [comment]
Let's keep the discussion in https://github.com/gatsbyjs/gatsby/issues/15509. Marking as a duplicate - thanks for understanding!
