### ISSUE TITLE
Gatsby + Passport JS

### ISSUE THREAD

**Issue by sekhuat** [gatsbyjs/gatsby#17437]
## Gatsby + Passport JS
Hi, I am new to Gatsby. I want to add authentication in the Gatbsy using PassportJS for Google and Facebook authentication. I had found examples on React JS with Passport JS running on Express but not sure how to implement it on Gatsby especially on bind the Passport component into Gatsby route.

I tried to search the web for examples on how to add authentication using PassportJS in Gatsby but to no avail. 

Please help to provide examples or tutorial on how to add PassportJS authentication into Gatsby. Thank you.

**Comment by sidharthachatterjee** [comment]
Take a look at https://www.gatsbyjs.org/tutorial/authentication-tutorial/

It explains how to use Passport (or other authentication libraries) to check on route change. 

Marking this as answered and closing. Thanks!

**Comment by dandv** [comment]
@sidharthachatterjee: that page is far from the kind of tutorial that would help the OP.

The fact that there's [no `passport`](https://www.gatsbyjs.org/plugins/?=passport) theme or plugin, suggests the integration is far from trivial.

**Comment by LekoArts** [comment]
Please open a new issue following our documentation template. Thanks!

**Comment by dandv** [comment]
@LekoArts: thanks for the suggestion. I've filed #23737.

**Comment by myhendry** [comment]
I did a Gatsby authentication demo using Passport on the server and Context, React-Query and Axios on the web. 

On my development machine, the demo works fine. 

Below are my codes...

https://github.com/myhendry/starter-with-token-server
https://github.com/myhendry/starter-with-token-web

Feel free to use and let me know if there's anything I can or need to do to improve the codes. Thanks :)
