### ISSUE TITLE
Language block 

### ISSUE THREAD

**Issue by Dajamante** [gatsbyjs/gatsby#17439]
## Summary

Including a language block as in Lekoarts website or Gatsby.

## Relevant information

Hello community!
I wish to have a little block indicating the language over the code blocks like in Lekoarts or Gatsby site. I am not ready for adopting Styled Components just yet, so:
- can I make a global .css file instead?
- or can I make a module.css file that is attached to blog-post template javascript page?
- is it something I can do from the config? 
- even better, is it possible to indicate it from Markdown?

I'd rather take the absolute easiest way right now :)!

**Comment by LekoArts** [comment]
> can I make a global .css file instead?
> or can I make a module.css file that is attached to blog-post template javascript page

Both approaches are fine, they both will work.

> is it something I can do from the config?

The CSS mentioned above requires some manual work from you, they code blocks itself are easily done.

> even better, is it possible to indicate it from Markdown?

Yes, that's also how gatsbyjs.org does it (and other sites too).
You can e.g. write

````
```js
const harry = spell('lumos')
```
````

---

So, how does it work?

You'll need to use `gatsby-remark-prismjs` or a remark plugin that adds certain classes to your code blocks.

If you inspect the first shell code block on https://www.gatsbyjs.org/docs/quick-start/, the output is:

```html
<div class="gatsby-highlight"><pre class="language-shell"><button name="copy code to clipboard" class="css-93j64b">Copy<span aria-roledescription="status" class="css-16cz5zo erisdwh3">copy code to clipboard</span></button><code class="language-shell"><div class="token-line"><span class="token function">npm</span><span class="token plain"> </span><span class="token function">install</span><span class="token plain"> -g gatsby-cli</span></div></code></pre></div>
```

The `gatsby-highlight` and `language-shell` class is important. These classes are targeted by the CSS that gets set by Gatsby [here in the source code](https://github.com/gatsbyjs/gatsby/blob/561d33e2e491d3971cb2a404eec9705a5a493602/www/src/utils/typography.js#L86-L205). You essentially want to do the same: Create those CSS definitions.

The code I highlighted creates the label as a pseudo-element (`::before`).

I personally use a CSS-in-JS solution on my site and I adopted some parts of @janosh 	approach, which looks like this: [lekoarts.de PrismJS styles](https://github.com/LekoArts/portfolio/blob/cc0d70d118c0d06736fccec43afa88cf6b42ce59/src/styles/prism.js). But I basically do the same: Create CSS definitions to target those classes.

**Comment by gagan0723** [comment]
@Dajamante have a look at this [issue](https://github.com/andrewbranch/gatsby-remark-vscode/issues/43#issuecomment-525083574). This is how I implement it for my website.

I am sure you are using `gatsby-remark-vscode` plugin. The generated code looks like this:
```html
<pre class="dark-default-dark vscode-highlight language-jsx" data-language="jsx">
  <code class="vscode-highlight-code">
    ....
  </code>
</pre>
```
You can target `data-language=jsx` attribute with css like this:
```css
pre[data-language="javascript"]::before {
  content: "js";
  background: #f7df1e;
}
```

**Comment by Dajamante** [comment]
Thanks to both, this is exactly what I am looking for! 
> So, how does it work?
> You'll need to use `gatsby-remark-prismjs` or a remark plugin that adds certain classes to your code blocks.
> 
I am not used at all to generated code, but If I understood well, instead of using typography themes, I can get more control and redo the whole typography file?
@gagan0723 funny that we ran in the same issue ten days apart 😃 . So does your css lies together with blog-post-template.js, or more global?

**Comment by gagan0723** [comment]
What do you mean by `assembler` code?

**Comment by Dajamante** [comment]
Hello again! I mean MIPS assembler code. I have it at school: https://learnxinyminutes.com/docs/mips/

**Comment by Dajamante** [comment]
> What do you mean by `assembler` code?

By the way, how do you target comments? When looking at the generated code, I get class .mtk3. 
But whatever I try, span.mtk3, .mtk3 or div#gatsby-focus-wrapper span.mtk3, I cannot target it.

**Comment by gagan0723** [comment]
> Last one: now that I have tags, if I want to add some highlighting for assembler code, do I need to do that in vs-plugin options?

It should just work fine as with other code blocks.

For the comments you need to target `.dark-default-dark .mtk3` not `.dark-default.dark .mtk3`.

**Note: I think this issue is more of `gatsby-remark-vscode` specific instead of `Gatsby`, because of which I am closing this.**

For additional queries regarding `Gatsby` you can join [Discord channel](https://discordapp.com/invite/br9rbUE).

Thanks

**Comment by Dajamante** [comment]
Sorry, in hastiness I wrote wrong.
This is what is in my css file:
```css
.dark-default-dark .mtk3 {
  color: orange;
}
```
