### ISSUE TITLE
Development error - UNHANDLED REJECTION Cannot read property 'allSitePage' of undefined

### ISSUE THREAD

**Issue by donaldboulton** [gatsbyjs/gatsby#17450]
I have no queries with "allSitePage" in my site or repo.

package.json
{
  "name": "publiuslogic",
  "description": "PubliusLogic Gatsby, and Netlify CMS",
  "author": "Donald Boulton",
  "version": "3.0.0",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git://github.com/donaldboulton/publiuslogic.com.git"
  },
  "scripts": {
    "develop": "gatsby develop",
    "start": "npm run develop -- --https",
    "build": "gatsby build",
    "serve": "gatsby serve && netlify-lambda serve functions-build",
    "lint": "eslint --ext js,jsx --ignore-path .gitignore . --fix",
    "clean": "rm -rf public/ .cache/",
    "snyk-protect": "snyk protect",
    "prepublish": "npm run snyk-protect",
    "test": "remark . --quiet --frail && node test.js"
  },
  "dependencies": {
    "@emotion/core": "^10.0.10",
    "@emotion/styled": "^10.0.11",
    "@gatsby-contrib/gatsby-plugin-elasticlunr-search": "^2.3.0",
    "apollo-link-http": "^1.5.15",
    "axios": "^0.18.0",
    "babel-plugin-prismjs": "^1.1.1",
    "babel-plugin-styled-components": "^1.10.6",
    "body-parser": "^1.19.0",
    "bulma": "^0.7.4",
    "classnames": "^2.2.6",
    "cloudinary-react": "^1.1.4",
    "core-js": "3.1.4",
    "cors": "^2.8.5",
    "fs": "^0.0.1-security",
    "fs-extra": "^7.0.1",
    "gatsby": "^2.13.41",
    "gatsby-image": "^2.2.7",
    "gatsby-link": "^2.2.3",
    "gatsby-paginate": "^1.1.1",
    "gatsby-plugin-catch-links": "^2.1.2",
    "gatsby-plugin-create-client-paths": "^2.1.3",
    "gatsby-plugin-feed": "^2.3.6",
    "gatsby-plugin-mailchimp": "5.1.2",
    "gatsby-plugin-manifest": "^2.2.4",
    "gatsby-plugin-netlify": "^2.1.3",
    "gatsby-plugin-netlify-cache": "^1.2.0",
    "gatsby-plugin-netlify-functions": "^0.0.3",
    "gatsby-plugin-nprogress": "^2.1.2",
    "gatsby-plugin-offline": "^2.2.4",
    "gatsby-plugin-purgecss": "^4.0.0",
    "gatsby-plugin-react-helmet": "^3.1.3",
    "gatsby-plugin-react-helmet-canonical-urls": "^1.2.0",
    "gatsby-plugin-robots-txt": "^1.5.0",
    "gatsby-plugin-sass": "^2.1.3",
    "gatsby-plugin-sharp": "^2.2.9",
    "gatsby-plugin-sitemap": "^2.2.3",
    "gatsby-plugin-styled-components": "^3.1.4",
    "gatsby-plugin-twitter": "^2.1.2",
    "gatsby-remark-autolink-headers": "^2.1.3",
    "gatsby-remark-code-titles": "^1.1.0-rc.0",
    "gatsby-remark-component": "^1.1.3",
    "gatsby-remark-copy-linked-files": "^2.1.3",
    "gatsby-remark-embed-video": "^1.7.1",
    "gatsby-remark-emojis": "^0.3.2",
    "gatsby-remark-external-links": "^0.0.4",
    "gatsby-remark-images": "^3.1.7",
    "gatsby-remark-normalize-paths": "^1.0.0",
    "gatsby-remark-prismjs": "^3.2.9",
    "gatsby-remark-reading-time-v2": "^1.0.2",
    "gatsby-remark-relative-images": "^0.2.2",
    "gatsby-remark-responsive-iframe": "2.2.4",
    "gatsby-remark-smartypants": "2.1.2",
    "gatsby-source-filesystem": "^2.1.6",
    "gatsby-source-graphql": "2.1.3",
    "gatsby-transformer-json": "^2.2.2",
    "gatsby-transformer-remark": "^2.6.9",
    "gatsby-transformer-sharp": "^2.2.4",
    "gatsby-transformer-yaml": "^2.1.12",
    "graphql": "^14.1.1",
    "lg-autoplay.js": "^1.0.0",
    "lg-hash.js": "^1.0.0",
    "lodash": "^4.17.11",
    "lodash-webpack-plugin": "^0.11.5",
    "modali": "^1.2.0",
    "moment": "^2.24.0",
    "node-fetch": "^2.5.0",
    "node-sass": "^4.12.0",
    "octicons": "^8.5.0",
    "path": "^0.12.7",
    "prismjs": "^1.16.0",
    "prop-types": "^15.7.2",
    "ramda": "^0.26.1",
    "react": "^16.8.6",
    "react-adsense": "^0.1.0",
    "react-dom": "^16.8.6",
    "react-dropzone": "^10.1.5",
    "react-github-btn": "^1.0.5",
    "react-helmet": "^5.2.1",
    "react-lightgallery": "^0.4.3",
    "react-router-dom": "^5.0.0",
    "react-scroll": "^1.7.11",
    "react-share": "^2.4.0",
    "react-slack-feedback": "^2.1.0",
    "react-stars": "^2.2.5",
    "react-typist": "^2.0.5",
    "rehype-react": "^4.0.1",
    "remark-rehype": "^5.0.0",
    "sharp": "^0.23.0",
    "snyk": "^1.192.3",
    "styled-components": "^4.3.2",
    "styled-css-grid": "^1.2.1",
    "styled-icons": "^8.4.0",
    "styled-media-query": "^2.1.2",
    "typeface-bowlby-one-sc": "^0.0.72",
    "typeface-kaushan-script": "0.0.72",
    "typeface-roboto": "^0.0.54",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "uploadcare-widget": "^3.7.7",
    "web-push": "^3.3.5",
    "with-utterances": "^1.4.1"
  },
  "resolutions": {
    "core-js": "3.1.4",
    "lodash": "^4.17.11",
    "graphql": "14.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "babel-eslint": "^10.0.2",
    "babel-preset-gatsby": "^0.2.8",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "enzyme-to-json": "^3.4.0",
    "dotenv": "^7.0.0",
    "eslint": "^6.0.1",
    "eslint-config-standard": "^12.0.0",
    "eslint-config-standard-react": "^7.0.2",
    "eslint-config-standard-trailing-commas": "^6.1.0",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-node": "^9.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-react": "^7.14.2",
    "eslint-plugin-standard": "^4.0.0",
    "gatsby-node-helpers": "^0.3.0",
    "http-proxy-middleware": "^0.19.1",
    "https": "^1.0.0",
    "netlify-lambda": "^1.4.13",
    "prettier": "^1.18.2",
    "remark-cli": "^6.0.1",
    "remark-html": "^8.0.0",
    "remark-preset-lint-markdown-style-guide": "^2.0.0",
    "remark-preset-lint-recommended": "^3.0.3",
    "typescript": "3.4.5"
  },
  "remarkConfig": {
    "plugins": [
      "preset-lint-markdown-style-guide",
      "html"
    ]
  },
  "eslintIgnore": [
    "node_modules",
    ".cache",
    "public"
  ],
  "snyk": true
}

All queries are working in production and no errors in production on localhost or Netlify, just production and the ability to use https://localhost:8000/___graphql or http://.......

**Comment by sidharthachatterjee** [comment]
Can you please link to a reproduction? If I understand correctly, you mean that querying for `allSitePage` is failing only in development?

**Comment by donaldboulton** [comment]
Yes just failing in development on windows 10. The main point is there is no query in [MY PubliusLogic.com REPO](https://github.com/donaldboulton/publiuslogic) with "allSitePage", that is what I do not understand.

**Comment by jonniebigodes** [comment]
@donaldboulton i've picked up on your issue and it seems i could not reproduce your issue.

- Cloned the repo you supplied.
- Installed the dependencies.
- Issued `gatsby develop` and i'm presented with:

```bash
success open and validate gatsby-configs - 0.617 s
success load plugins - 28.830 s
success onPreInit - 0.101 s
success initialize cache - 0.064 s
success copy gatsby files - 2.920 s
warn gatsby-plugin-feed was initialized in gatsby-config.js without a title in a feed.
This means that the plugin will use the default feed title, which may not match your use case.
This behavior will be removed in the next major release of gatsby-plugin-feed.
For more info, check out: https://gatsby.dev/adding-rss-feed
success onPreBootstrap - 0.063 s
success source and transform nodes - 2.398 s
Initializing gatsby-remark-component
success Add explicit types - 0.061 s
success Add inferred types - 0.340 s
success Processing types - 0.189 s
success building schema - 5.953 s
code block or inline code language not specified in markdown. applying generic code block
unable to find prism language 'jsto template' for highlighting. applying generic code block
unable to find prism language 'env' for highlighting. applying generic code block
unable to find prism language 'jsstyled component' for highlighting. applying generic code block
unable to find prism language 'sh' for highlighting. applying generic code block
success createPages - 2.279 s
success createPagesStatefully - 0.420 s
success onPreExtractQueries - 0.093 s
success update schema - 0.155 s
success extract queries from components - 2.250 s
success write out requires - 0.352 s
success write out redirect data - 0.069 s
success Build manifest and related icons - 0.046 s
success onPostBootstrap - 0.126 s
⠀
info bootstrap finished - 91.256 s
⠀

                 The requested width "400px" for a resolutions field for
                 the file 1546351188-1538062800-80x80-hotjar-icon.png
                 was larger than the actual image width of 80px!
                 If possible, replace the current image with a larger one.


gatsby-plugin-purgecss: Only processing  
 DONE  Compiled successfully in 33085ms                                                                                                                         01:55:22
⠀
You can now view publiuslogic in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use npm run build
⠀
i ｢wdm｣: Compiled successfully.


————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
69 pages                                                                                                                                                    publiuslogic
```
Only got some warnings about some images sizes like the one i left in and i was able to browse the site without issues.

![donald_1](https://user-images.githubusercontent.com/22988955/64576282-ca471f00-d36f-11e9-87d5-674c837d70b3.png)

- Issued `gatsby build && gatsby serve` and i'm presented with:

```bash
success open and validate gatsby-configs - 0.199 s
success load plugins - 5.517 s
success onPreInit - 0.062 s
success delete html and css files from previous builds - 0.059 s
success initialize cache - 0.059 s
success copy gatsby files - 1.521 s
warn gatsby-plugin-feed was initialized in gatsby-config.js without a title in a feed.
This means that the plugin will use the default feed title, which may not match your use case.
This behavior will be removed in the next major release of gatsby-plugin-feed.
For more info, check out: https://gatsby.dev/adding-rss-feed
success onPreBootstrap - 0.214 s
success source and transform nodes - 1.329 s
Initializing gatsby-remark-component
success Add explicit types - 0.059 s
success Add inferred types - 0.321 s
success Processing types - 0.204 s
success building schema - 1.418 s
code block or inline code language not specified in markdown. applying generic code block
unable to find prism language 'jsto template' for highlighting. applying generic code block
unable to find prism language 'env' for highlighting. applying generic code block
unable to find prism language 'jsstyled component' for highlighting. applying generic code block
unable to find prism language 'sh' for highlighting. applying generic code block
success createPages - 3.044 s
success createPagesStatefully - 0.260 s
success onPreExtractQueries - 1.459 s
success update schema - 0.125 s
success extract queries from components - 2.093 s
success write out requires - 0.065 s
success write out redirect data - 0.044 s
success Build manifest and related icons - 0.050 s
success onPostBootstrap - 0.116 s
⠀
info bootstrap finished - 30.378 s
⠀

                 The requested width "400px" for a resolutions field for
                 the file 1546351188-1538062800-80x80-hotjar-icon.png
                 was larger than the actual image width of 80px!
                 If possible, replace the current image with a larger one.


success run static queries - 8.781 s — 11/11 1.31 queries/second

gatsby-plugin-purgecss: Only processing  \publiuslogic\src\assets\sass\styles.sass
success Building production JavaScript and CSS bundles - 99.310 s
success Rewriting compilation hashes - 0.142 s
success run page queries - 4.764 s — 68/68 14.47 queries/second
success Generating image thumbnails — 798/798 - 162.087 s

gatsby-plugin-purgecss:
 Previous CSS Size: 234.78 KB
 New CSS Size: 91.81 KB (-60.90%)
 Removed ~142.97 KB of CSS

success Building static HTML for pages - 21.330 s — 68/68 27.45 pages/second
info Done building in 208.007 sec

info gatsby serve running at: http://localhost:9000/     
```
![donald_2](https://user-images.githubusercontent.com/22988955/64576398-45a8d080-d370-11e9-8494-f2e14ad9c82a.png)

Could you issue `gatsby clean && gatsby develop` to see if it could be a cached data issue, or delete the `node_modules` folder and issue `npm install` to get the latest packages versions.

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by donaldboulton** [comment]
Thank You @jonniebigodes. If you got it working then it must be some error in my node modules. Ya just trying localhost queries not production and I get the "allSitePage" error.I will try deleting them and rebuild the folder, I will see if that works.

**Comment by donaldboulton** [comment]
Closing I had updated yarn and have been getting weird local errors ever since. Got rid of yarn.lock with with npm. After about 20 min, "npm fixed", alot of missing and incorrect modules and now it works.
Thank You
Donald Boulton

**Comment by jonniebigodes** [comment]
@donaldboulton no need to thank, glad i was able to help and you get it working.

**Comment by wardpeet** [comment]
Please also clean the cache:

Linux/mac:
`gatsby clean; rm -rf node_modules`

Windows:
`gatsby clean; Remove -Recurse -Force node_modules`
