### ISSUE TITLE
Expose `onDeleteNode` in the Node API

### ISSUE THREAD

**Issue by JulienPradet** [gatsbyjs/gatsby#17457]
## Summary

:wave: I'm still pretty new to developing Gatsby websites even though I've been following the project for quite some time now. So if I don't really make sense or if I'm not in the correct mindset to tackle my issue, feel free to tell me :)

The goal here would be to add a `onDeleteNode` method to the `gatsby-node.js` file.
It would allow one **not** to restart their application in `develop` mode but still keep their data in a correct state.

My particular use case is for node fields. I didn't find a way to delete those fields when the target node has been deleted. (see below for more details)

### Basic example

The `onDeleteNode` would behave exactly like `onCreateNode` except that it should be ran before the deletion.

To illustrate this, let's say that I have two types of nodes :
* *Tutorial* (which is a markdown file)
* *Code* (which is a code example)

Each *Tutorial* can have some *Code* node to display alongside the tutorial. I'm trying to replicate something that would look like the [Svelte tutorial](https://svelte.dev/tutorial/basics).

```js
// gatsby-node.js

// Here is an example of how I associate a "Code" with a "Tutorial" node.
exports.onCreateNode = ({ node, actions, getNodesByType }) => {
  if (node.internal.type === "CodeType") {
    const tutorialNode = getNodesByType("TutorialType").find(
        /* is the tutorial node for the current code node */
    );
    actions.createNodeField({
      node: tutorialNode,
      name: "code___NODE",
      value: node ? node.id : null
    });
  }
};

// But if a "Code" is deleted, I want to remove it from the "Tutorial" node.
// Here it's a simple "delete", but we could imagine to associate the Tutorial
// with another code, a default value, etc.
exports.onDeleteNode = ({ node, actions, getNodesByType }) => {
  if (node.internal.type === "CodeType") {
    const tutorialNode = getNodesByType("TutorialType").find(
      tutorialNode => tutorialNode.field.code.id === node.id
    );
    if (tutorialNode) {
      actions.createNodeField({
        node: tutorialNode,
        name: "code___NODE",
        value: null
      });
    }
  }
};
```

### Motivation

In my particular use case, I've got 2 plugins that each manage the initial creation of the nodes "Tutorial" and "Code". And then I have a theme plugin that creates the link between both using `createNodeField`.

So, when my source plugin detects that a "Code" has been deleted, I want to remove it from the "Tutorial". If I don't, the "Code" is still available in my page even if it no longer exists in my filesystem. However, I can't remove it because the field belongs to the theme plugin and the theme never knows that it was deleted.

This is why I suggest implementing a `onDeleteNode` API. This would allow the theme plugin to remove this field. And I feel like a `onDeleteNode` method would be self explanatory considering one already understands the `onCreateNode` (not sure though).

Another possibility I've thought about is deleting the node field automatically. It would be triggered by the `DELETE_NODE` redux action. But it feels like a less powerful and less natural API. For instance, one might want set another value rather than deleting it, log a message, etc. Using `DELETE_NODE` wouldn't solve these use cases.

____

I didn't create an RFC because it's the first time I contribute to this project. I don't know if what I'm suggesting makes sense. And I don't know if it could be considered to be invisible to other Gatsby users :) But if you think it would make sense, I'll do it.

Have a nice day :rainbow:

**Comment by jonniebigodes** [comment]
i'm onboard with the author and this api should be made available. Probably some cases more than the one reported might benefit from this.
