### ISSUE TITLE
HTTP 403 errors are swallowed by gatsby-plugin-offline

### ISSUE THREAD

**Issue by underyx** [gatsbyjs/gatsby#1745]
Hey! I wrote up a simple gatsby static site for our engineering handbook at Kiwi.com.

Since this is private/secret content, we need to restrict access to it. I've set up https://github.com/bitly/oauth2_proxy to handle this for us — requests to our handbook site go through this proxy, which makes you log in with your company account. Once you're authenticated, it just forwards your requests to the server serving the gatsby static content.

The problem is that when someone's oauth2 token cookie expires, their requests will start getting intercepted by the auth proxy again, prompting them to log in again. The service worker, however, will still serve the last known version of the page, and not indicate that updates are failing due to HTTP 403 errors and that the user needs to log in again. The users then end up seeing outdated content forever :(

Any ideas on how to fix this?

**Comment by KyleAMathews** [comment]
You can't use service workers with authentication unfortunately.

**Comment by underyx** [comment]
@KyleAMathews well, I understand that auth isn't explicitly supported, but are you sure there's no way around this at all? Wouldn't it be possible to handle these erroring requests? Perhaps expose an API to write a custom handlers, which I could use to display an alert if requests are failing with 403s?

**Comment by KyleAMathews** [comment]
Gatsby doesn't need the offline plugin to work. You'll just need to remove it.

**Comment by underyx** [comment]
Alright, I'll do that, with just one meek teardrop in my eye 😿

**Comment by KyleAMathews** [comment]
Service Workers are waiting with open arms on all your public sites :-)
