### ISSUE TITLE
UNHANDLED REJECTION Source and destination must not be the same.

### ISSUE THREAD

**Issue by adelleye** [gatsbyjs/gatsby#17460]
## Description

Tried creating a new gatsby site and got an error message

### Steps to reproduce
Ran the usual
gatsby new personal-site
cd personal-site
gatsby develop

### Expected result

What should happen?

### Actual result

 ERROR 

UNHANDLED REJECTION Source and destination must not be the same.

  Error: Source and destination must not be the same.
  
  - stat.js:80 getStats
    [personal-site]/[fs-extra]/lib/util/stat.js:80:17
  
  - stat.js:38 fs.stat
    [personal-site]/[fs-extra]/lib/util/stat.js:38:16
  
  - polyfills.js:295 callback
    [personal-site]/[graceful-fs]/polyfills.js:295:20
  

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Safari: 13.0
  npmPackages:
    gatsby: ^2.15.9 => 2.15.9
    gatsby-image: ^2.2.17 => 2.2.17
    gatsby-plugin-manifest: ^2.2.14 => 2.2.14
    gatsby-plugin-offline: ^3.0.3 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.6 => 3.1.6
    gatsby-plugin-sharp: ^2.2.20 => 2.2.20
    gatsby-source-filesystem: ^2.1.21 => 2.1.21
    gatsby-transformer-sharp: ^2.2.13 => 2.2.13
  npmGlobalPackages:
    gatsby-cli: 2.7.44

**Comment by sidharthachatterjee** [comment]
@adelleye Can you push this up as a reproduction please?

**Comment by adelleye** [comment]
Sorry, just found out my user is corrupt, thank you anyways @sidharthachatterjee

**Comment by etienneche** [comment]
Hi guys I got the same error without finding out what to change to make it works. What do you mean user is corrupt ?

**Comment by etienneche** [comment]
this is my output when I run `gatsby info --clipboard`

 System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.20.1 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
  npmPackages:
    gatsby: ^2.20.35 => 2.20.35
  npmGlobalPackages:
    gatsby-cli: 2.11.21

**Comment by etienneche** [comment]
This is what I got when run `gatsby info --clipboard` 

  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.20.1 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
  npmPackages:
    gatsby: ^2.20.35 => 2.20.35
  npmGlobalPackages:
    gatsby-cli: 2.11.21

**Comment by rnnyrk** [comment]
Same issue for me as well. Any suggestion on how to solve it?

**Comment by rebwill** [comment]
Same issue for me as well. 

Steps to reproduce:
- installed gatsby cli `npm i -g gatsby-cli`
- created new gatsby project `gatsby new gatsby-site`
- `cd gatsby-site`
- tried to start hot reloading environment `gatsby develop`

Expected behavior:
- launch hot reloading environment at http://localhost:8000

Actual behavior:
- result of running `gatsby develop`:

```
success open and validate gatsby-configs - 0.107s
success load plugins - 6.907s
success onPreInit - 0.043s
success initialize cache - 0.102s
success copy gatsby files - 0.392s
success onPreBootstrap - 0.074s
success createSchemaCustomization - 0.010s
success source and transform nodes - 0.280s
success building schema - 0.389s
success createPages - 0.004s
⠦ createPagesStatefully

 ERROR 

UNHANDLED REJECTION Source and destination must not be the same.

  Error: Source and destination must not be the same.
  
  - stat.js:80 
    [gatsby-site]/[fs-extra]/lib/util/stat.js:80:17
  
  - stat.js:38 
    [gatsby-site]/[fs-extra]/lib/util/stat.js:38:16
  
  - polyfills.js:295 callback
    [gatsby-site]/[graceful-fs]/polyfills.js:295:20
  
 ERROR 

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in StoreStateProvider
    in App

not finished createPagesStatefully - 6.494s
```

Any recommendations on how to solve this? It's unclear how the original user actually solved it before closing, and more people are having the issue now.

**Comment by rebwill** [comment]
I just figured out my issue. After spending a bunch of time trying to reinstall different version of Gatsby, rolling back my Node version, etc....it turns out I was running `gatsby develop ` *from the wrong directory*. 🤦‍♀️ 

If you are encountering this error, make sure you actually cd into the project folder.

**Comment by ashishp166** [comment]
@etienneche @rnnyrk @sidharthachatterjee I have been getting the same error. I was wondering if you found out how to solve the problem. I attached my output of ```gatsby info --clipboard```:
```
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 78.0.2
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12
  npmGlobalPackages:
    gatsby-cli: 2.12.68
```

**Comment by rayer10** [comment]
I had the same issue. Turned out that there can't be any symbols in file path. Hope this helps.

**Comment by rnnyrk** [comment]
Was the same issue for me. Had the project in a folder callend `[Gatsby]`. Seems like that's not possible haha
