### ISSUE TITLE
gatsby-remark-prismjs does not highlight

### ISSUE THREAD

**Issue by robSturcke** [gatsbyjs/gatsby#17462]
## Description

gatsby-remark-prismjs does not highlight code snippets, it only provides blank styles.

### Steps to reproduce

`npm install --save gatsby-transformer-remark gatsby-remark-prismjs prismjs`

Add to `config`:
```{
      resolve: 'gatsby-remark-prismjs',
      options: {
        classPrefix: 'language-',
      },
    },
```

Tried imports from `gatsby-browser.js`, `App.scss`, and my template.
Gatsby-Config
```
require("prismjs/themes/prism-okaidia.css")
```
JSX
```
import 'prismjs/themes/prism-okaidia.css';
```
SCSS
```
@import 'prismjs/themes/prism-okaidia.css
```

### Expected result
Should see Code highlighted in okaidia theme

### Actual result

![Screen Shot 2019-09-06 at 4 41 47 PM](https://user-images.githubusercontent.com/13204145/64459211-584bad00-d0c5-11e9-90bc-fb8637f44d37.png)

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.2/bin/npm
  Languages:
    Python: 3.6.4 - /anaconda3/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.15.9 => 2.15.9 
    gatsby-background-image: ^0.4.1 => 0.4.3 
    gatsby-image: ^2.0.40 => 2.1.4 
    gatsby-mdx: ^0.6.2 => 0.6.3 
    gatsby-plugin-emotion: ^4.0.6 => 4.0.7 
    gatsby-plugin-google-analytics: ^2.1.11 => 2.1.11 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sass: ^2.1.12 => 2.1.12 
    gatsby-plugin-sharp: ^2.0.35 => 2.1.5 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5 
    gatsby-remark-images: ^3.0.11 => 3.0.14 
    gatsby-remark-prismjs: ^3.3.12 => 3.3.12 
    gatsby-source-filesystem: ^2.0.32 => 2.1.18 
    gatsby-source-instagram: ^0.5.0 => 0.5.0 
    gatsby-transformer-remark: ^2.6.21 => 2.6.21 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.21 
  npmGlobalPackages:
    gatsby-cli: 2.7.40

**Comment by satvikpendem** [comment]
I'm having the same issue, what was the solution?

**Comment by robSturcke** [comment]
@satvikpendem unfortunately, I resorted to just using screenshots of my code instead of formatting it by hand etc.

**Comment by converge** [comment]
if you guys need a working example, it's using Gatsby+Markdown+Prism:

https://github.com/converge/personal-website
