### ISSUE TITLE
Broken links to schema-customization.md in a few of the docs.

### ISSUE THREAD

**Issue by yashk2000** [gatsbyjs/gatsby#17471]
## Description

There are few broken links in the following files. The `scheme customization changes` link leads to a 404 error.

- schema-connections.md
- schema-generation.md
- schema-input-gql.md
- schema-sift.md

I would like to work on this issue.

**Comment by LekoArts** [comment]
The connected PR was closed as the docs need to be viewed on the website, not in GitHub itself. Hence we won't fix this and will close this issue. Thanks!
