### ISSUE TITLE
[discussion]: command line syntax refactoring in readme(s) for more beginer friendly 

### ISSUE THREAD

**Issue by LOLdevelopr** [gatsbyjs/gatsby#17473]
## Summary
A current status and PR for the implementation of the solution and
 discussion till can be found https://github.com/gatsbyjs/gatsby/pull/17456

## Relevant information
How a docs can be re written with examples https://github.com/gatsbyjs/gatsby/pull/17456#issuecomment-529095163

Detailed syntax descriptor can be found here http://docopt.org/

### Environment (if relevant)

```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.15.9 => 2.15.9
    gatsby-image: ^2.2.17 => 2.2.17
    gatsby-plugin-manifest: ^2.2.14 => 2.2.14
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.6 => 3.1.6
    gatsby-plugin-sharp: ^2.2.20 => 2.2.20
    gatsby-source-filesystem: ^2.1.21 => 2.1.21
    gatsby-transformer-sharp: ^2.2.13 => 2.2.13
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by muescha** [comment]
I would vote that we have a syntax like

> # syntax
> 
> `gatsby new <site-name> [<starter-url>]`
>
> parameters:
> `<site-name>` the folder where you create your new site. Can also be `.`
> `<starter-url>` an URL to an Gatsby template (Default is: `gatsbyjs/gatsby-starter-default`)
> 
> # examples
> 
> `gatsby new my-app https://github.com/gatsbyjs/gatsby-starter-blog`
> `gatsby new my-app https://github.com/netlify-templates/gatsby-starter-netlify-cms`

**Comment by LOLdevelopr** [comment]
**+1 for https://github.com/gatsbyjs/gatsby/issues/17473#issuecomment-52911878**

its more clear and understandable. 
just one thing 
> <starter-url> an URL to an Gatsby template (Default is: gatsbyjs/gatsby-starter-default)

here instead of `gatsbyjs/gatsby-starter-default`, better to have a full URL with `gatsby-starter-default`  specifying the link

Like this 

```
[gatsby-starter-default](https://github.com/gatsbyjs/gatsby-starter-default)

```

**Comment by muescha** [comment]
Ok

It's because you can leave off the GitHub part

**Comment by LOLdevelopr** [comment]
oh yeah I forgot its gonna be in github only right ! yeah true ! +1 for that

**Comment by LOLdevelopr** [comment]
We can mention that for the `new` command in `gatsby-cli` if leaving all the arg empty, a friendly prompts will appear in order to take those args

**Comment by anikethsaha** [comment]
This looks like a good idea. +1 for this !

**Comment by marcysutton** [comment]
I'm a fan of the syntax and examples sections. There are a few additional places in the docs source that would be worth updating as well (partly why we prompted to open an issue versus starting with a PR):

- https://github.com/gatsbyjs/gatsby/tree/master/docs/docs
- https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/starters.md
- https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-cli

**Comment by LOLdevelopr** [comment]
I will be starting it with this https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-cli .

**Comment by LOLdevelopr** [comment]
@muescha @marcysutton @sidharthachatterjee I would like to know if you guys are okay with this doc 
[`gatsby-cli doc`](https://github.com/LOLdevelopr/gatsby-1/blob/docs/syntax-guided-command-docs/packages/gatsby-cli/README.md)

Changes I made
- Added explained notes for `new` command [here]( https://github.com/LOLdevelopr/gatsby-1/blob/docs/syntax-guided-command-docs/packages/gatsby-cli/README.md#new)
- Added `$` symbol in front of commands to visualize them better as CLI commands

**Comment by muescha** [comment]
in all examples there is no `$` and thats not helpful if you double click for selecting a line

**Comment by muescha** [comment]
i would stick with http://docopt.org/ syntax at:

`gatsby new <site-name> [<starter-url>]`
or also

**Comment by LOLdevelopr** [comment]
> in all examples there is no $ and thats not helpful if you double click for selecting a line

okay will remove it then !

> gatsby new [<site-name> [<starter-url>]]

this one looks neat !

I will also remove the `required` word from the `site-name` argument details. as its not required for prompt!

**Comment by muescha** [comment]
with shell we become fancy color in github readme ;)

```
 	```shell
 	gatsby new [<site-name> [<starter-url>]]
 	```
```

```shell
gatsby new [<site-name> [<starter-url>]]
```

**Comment by LOLdevelopr** [comment]
but this one will take the whole width ......

**Comment by marcysutton** [comment]
Closed with https://github.com/gatsbyjs/gatsby/pull/17549
