### ISSUE TITLE
Make gatsby filters

### ISSUE THREAD

**Issue by wooyg** [gatsbyjs/gatsby#17481]
How can I make search filter page like below?

https://www.gatsbyjs.org/showcase/? (left sidebar)

Can I get some url of tutorial?

(Gatsbyjs is the one what I exactly want. :) )

**Comment by sidharthachatterjee** [comment]
Don't know of a tutorial but the website itself is open source and in this repo in https://github.com/gatsbyjs/gatsby/tree/master/www/src 🙂 

Feel free to look around! 

Closing this in the mean time this might not be the right place for this question. Thank you for using Gatsby 💜
