### ISSUE TITLE
Image loading causes jumpiness when using Link component for internal navigation

### ISSUE THREAD

**Issue by nareg26** [gatsbyjs/gatsby#17485]
## Summary
When navigating using the Gatsby `<Link>` component, the DOM updates but images only appear after a small delay. The following 8-second video demonstrates the issue:
https://vimeo.com/358609882

The first part of the video shows navigation using a regular `<a>` tag. There is a slight delay after the link is clicked before the browser loads the destination page, as expected for an `<a>` tag, but the images are there once the page loads.

The second part of the video shows navigation using a `<Link>` component. The browser responds immediately when the link is clicked and switches to the destination page, however, the images are noticeably late to appear.

The questions:

1. Is this expected behavior?

2. If so, what are some ways to mitigate this?
Only thing I can think of is loading these top-of-page images on all pages so they're ready when we navigate, but worried about detrimental effect this might have to page speed scores.

If there is no good way to fix this, we may stick with the `<a>` tag after all for internal navigation.

## Relevant information

The images are regular `<img>` elements. We're not using `gatsby-image`

## Environment

```
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.2.1 - ~/.nvm/versions/node/v10.2.1/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v10.2.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.9.4 => 2.13.31
    gatsby-plugin-google-analytics: ^2.1.1 => 2.1.4
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.2
    gatsby-plugin-sass: ^2.1.3 => 2.1.3
  npmGlobalPackages:
    gatsby-cli: 2.6.7
```

## File contents

Leaving this empty so as not to create too much bloat. Please let me know if any configs files in particular would be useful to see.

**Comment by sidharthachatterjee** [comment]
Off the top of my head, this is happening because when using `Link`, the next page is prefetched and then layout needs to be recalculated after downloading the images (hence the jump), versus when using `a`, there is no prefetching so it takes longer but doesn't visibly _jump_ 

Any specific reason not to use `gatsby-image` since that will likely fix this and give you a better looking loading state for the image as well?

**Comment by nareg26** [comment]
Thanks for confirming that - It's what I suspected.

We experimented with `gatsby-image` - mainly interested in the potential performance gains. However, there was no significant improvement to performance as measured by:
https://developers.google.com/speed/pagespeed/insights/

So we didn't prioritize it. Seems like a good opportunity now to try it again, at least enabling it for those page-top images so we can comfortably use `<Link>`.

Thanks again! Feel free to close the issue unless you have something to add.

**Comment by sidharthachatterjee** [comment]
> > We experimented with gatsby-image - mainly interested in the potential performance gains. However, there was no significant improvement to performance as measured by:
> developers.google.com/speed/pagespeed/insights

I would highly recommend trying it out owing to 
- the better loading experience on slow networks (blurred placeholder)
- reduced jank (size of img is pre measured so that you don't see shifting content)

Nonetheless, glad we could help! I'll go ahead and close this for now but please feel free to reopen or comment if there is anything else we can help with 🙂

**Comment by hoangbn** [comment]
Hi there, I see the same issue with `gatsby-image` and `gatsby-plugin-image`. 
When navigating internally with `Link`, the pre-built HTML page is not used, so even placeholder images take longer to appear: 
![image-loading-issue](https://user-images.githubusercontent.com/38968280/124053628-97f82d00-d9ee-11eb-98c8-c706018095c3.gif)
