### ISSUE TITLE
'use strict' warning when developing plugins locally

### ISSUE THREAD

**Issue by dkthehuman** [gatsbyjs/gatsby#17489]
I'm working on an official Gatsby plugin (#17426), and when I add it as a local plugin without changing any of the default config, I get a warning from ESLint:

```
/Users/dskang/Code/tmp/gatsby-eslint-strict/plugins/gatsby-plugin-google-analytics/gatsby-browser.js
  1:1  warning  'use strict' is unnecessary inside of modules  strict
```

This happens with all of the official plugins that include a `gatsby-browser.js` because Babel adds "use strict" to the top of all of them. How do I avoid getting this warning when using a local plugin that gets compiled by Babel?

## Example repo

Here's a hello-world starter repo with the `gatsby-plugin-google-analytics` plugin copied to the `/plugins` directory: https://github.com/dkthehuman/gatsby-eslint-strict

## Steps to reproduce

1. Create starter repo

```sh
gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
cd hello-world
```

2. Copy an official plugin and install it

```sh
mkdir plugins
cp -r <gatsby_repo>/packages/gatsby-plugin-google-analytics plugins

cd plugins/gatsby-plugin-google-analytics
npm install
```

3. Add plugin as a local plugin in `gatsby-config.js`

```javascript
module.exports = {
  plugins: ["gatsby-plugin-google-analytics"],
}
```

4. Run `gatsby develop`

## Expected result

No ESLint warnings

## Actual result

ESLint warning about "use strict"

**Comment by LekoArts** [comment]
You'll need to tell ESLint to ignore those files. So this isn't really an issue with Gatsby.
