### ISSUE TITLE
How to Cache data from external resources such as WordPress & Contentful

### ISSUE THREAD

**Issue by lucashfreitas** [gatsbyjs/gatsby#17499]
Hello, 

Sorry in advance if this is a duplicate, but I did not find any information about this. I had a look at [gatsby caching documentation]( https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/caching.md) but did not find anything related to cache data from external sources/API.

I have found this issue #6266 but was just wondering if anyone found a workaround for that. 

**The problem:** 

I am using **gatsby-source-contentful** and **gatsby-source-wordpress** on my gatsby website. I fetch a lot of data from contentful and WordPress which are used on my GraphQL queries. 

Every time when I run gatsby develop to rebuild/build my website in my local environment it downloads all the data again from Wordpress & Contentful API. 

In the most part of times, I don't need to fetch the data again, I just want to rebuild my website to see some layout/design changes that I made in my components. I know that gatsby do cache, but in the most part of cases I am doing changes to **gatsby-node** file which not reloads the website, then I have to rebuild the website and fetch all the data again.

Does anyone have an idea of how would be possible to cache all data from external sources such as contentful & Wordpress and use it in next builds instead of download everything again? 

Thanks in advance!

**Comment by universse** [comment]
Is this what you need? https://www.gatsbyjs.org/docs/build-caching/
