### ISSUE TITLE
gatsby-transformer-remark to load HTML and not markdown. (question)

### ISSUE THREAD

**Issue by rparree** [gatsbyjs/gatsby#17501]
Hi,

I am using a mix of sources: markdown and files with partial html.  At this moment i am also using the remark transformer for the raw html files. But it is causing some problems with empty lines and indententation (it is interpreted as a code block). For examle beow

```html<section>
    <section>
        <h1>Hello</h1>
    </section>

    <section>
       <h1>world</h1>
    </section>
</section>
```

I was thinking  to write my own transformer that just loads the HTML, but that would not allow me to use the many other remark plugins available (`gatsby-remark-copy-linked-files`, `gatsby-remark-images` etc).

I guess i have the following questions:
- Would there be an easier way to use this plugin as a "raw"-HTML transformer?
- Otherwise, Is there a way to turn off the indented code blocks?
- Perhaps someone else has found a way to deal with partial html files.

tx.,

**Comment by bernzJ** [comment]
Have a look [here](https://www.gatsbyjs.org/packages/gatsby-remark-custom-blocks/) .
