### ISSUE TITLE
The remove fingerprints plugin doesn't remove all fingerprints

### ISSUE THREAD

**Issue by richtera** [gatsbyjs/gatsby#17509]
I found a more reliable way by doing this
```javascript
exports.onCreateWebpackConfig = ({
  stage,
  getConfig,
  rules,
  loaders,
  actions,
  plugins,
}) => {
  const config = getConfig();
  const fix = (item, name) => {
    if (item.options && item.options[name] && /\[(content)?hash(:.*)\]/.test(item.options[name])) {
      const newValue = item.options[name].replace(/\.?\[(content)?hash(:.*)?\]/, '');
      if (newValue != item.options[name]) {
        report.log(`WebPack Replaced ${item.options[name]} with ${newValue}`);
        item.options[name] = newValue;
      } else {
        report.error(`WebPack problems replacing ${item.options[name]}`);
      }
    }
  }
  const removeHash = (rule) => {
    fix(rule, 'name');
    fix(rule, 'filename');
    fix(rule, 'chunkFilename');
    if (rule.use) {
      rule.use.forEach(removeHash);
    }
  }
  config.module.rules.concat(config.plugins).forEach(removeHash)
  actions.replaceWebpackConfig(config);
}
```

## Description

There are various plugins that use hash or contenthash.

### Steps to reproduce

Make a production build and then execute this:
```sh
find public/ -type f -exec basename {} \; > output.txt
```
Look in output.txt file for files with hashes.

### Expected result

There should be no hashed file names.

### Actual result

css and some other ones like svg and so are left.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 3.7.0 - /Users/andy/anaconda3/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 65.0.1
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.15.7 => 2.15.11 
    gatsby-awesome-pagination: ^0.3.4 => 0.3.4 
    gatsby-cli: ^2.7.44 => 2.7.45 
    gatsby-image: ^2.2.17 => 2.2.17 
    gatsby-plugin-algolia: ^0.3.0 => 0.3.3 
    gatsby-plugin-google-analytics: ^2.1.14 => 2.1.15 
    gatsby-plugin-manifest: ^2.1.1 => 2.2.15 
    gatsby-plugin-material-ui: ^2.0.1 => 2.1.6 
    gatsby-plugin-netlify: ^2.1.3 => 2.1.11 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-offline: ^3.0.2 => 3.0.4 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.6 
    gatsby-plugin-remove-fingerprints: ^0.0.2 => 0.0.2 
    gatsby-plugin-sharp: ^2.1.2 => 2.2.20 
    gatsby-plugin-styled-components: ^3.0.7 => 3.1.4 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-source-filesystem: ^2.1.21 => 2.1.21 
    gatsby-source-graphql: ^2.1.3 => 2.1.12 
    gatsby-transformer-sharp: ^2.1.20 => 2.2.13 
    gatsby-transformer-yaml: ^2.1.12 => 2.2.8

**Comment by ascorbic** [comment]
This should probably be raised on the https://github.com/narative/gatsby-plugin-remove-fingerprints repo rather than here, as it's a third party plugin.

**Comment by wardpeet** [comment]
as @ascorbic said, sadly we can't provide you any help when using a third party plugin. I'm not sure why you want to remove hashes from your file. It helps browser cache files as long as they can and improve speed for your users.

As stated above, I'll be closing this issue.

Thanks for using Gatsby 💪

**Comment by richtera** [comment]
I see. There was a previous comment about that, but there was no link to the corresponding ticket. Will search.
