### ISSUE TITLE
Native loading="lazy" lacks dimensions inside gatsby-image.

### ISSUE THREAD

**Issue by eriktiekstra** [gatsbyjs/gatsby#17506]
## Description

I am using the fluid queries within gatsby-image. When using the default `loading="lazy"`, I get the following warning inside the console:

<img width="577" alt="Screenshot 2019-09-09 at 15 44 21" src="https://user-images.githubusercontent.com/6928564/64536162-e1a6ed80-d318-11e9-952b-9872c80b3656.png">

```
[Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323
```

I tried to search for this issue, but only found 2 unanswered questions on spectrum. I am using gatsby 2.15.11 and gatsby-image 2.2.17. As far as I can see the native lazy-loading has been introduced in gatsby-image 2.1.0.

It also appears on https://using-gatsby-image.gatsbyjs.org/

**Comment by ascorbic** [comment]
I think the problem here is that fluid images by their nature can't have their size set in the HTML, because they're supposed to resize to fit their container. I'm not sure if there's a way around this (or if it's actually a problem).

**Comment by wardpeet** [comment]
I've created an upstream issue on chromium https://bugs.chromium.org/p/chromium/issues/detail?id=1002455. Seems like chrome doens't detect fluid containers and mark images without dimensions as faulty. You shouldn't worry about it.

**Comment by eriktiekstra** [comment]
@ascorbic 
It is a warning, so nothing breaks the site. I just like to keep my console clean, so I thought to make people aware of it. 

@wardpeet Thanks for creating an issue on chromium, I actually didn't think of that it could be an issue in the browser. It makes sense though.

**Comment by jimmyandrade** [comment]
👀

**Comment by olee** [comment]
This issue is still relevant and should be reopened I think

**Comment by michaelCaleyWhaley** [comment]
Still an issue. Even with it being fluid we should be able to pass in attributes

**Comment by hlolli** [comment]
This causes chrome not to lazy load at all, and the lighthouse/audit rankings are down the drain because of this.

**Comment by fabiobarbosa** [comment]
I'd also like to see this being addressed. Adding attributes to images, even when fluid, is slowly becoming a new best practice.

**Comment by AntoineBourin** [comment]
We can’t use fluid images for now. I’m using only fixed images without the possibility to set attributes on fluid images...

**Comment by christophcar** [comment]
I am facing this issue as well, would be great if this could be adressed any time soon.

**Comment by benyou1969** [comment]
Still facing this issue

**Comment by forwinder15** [comment]
Still a thing

**Comment by Z11** [comment]
Still an issue 😿

**Comment by renguer0** [comment]
Still an issue here too (blazy in css backgrounds).

**Comment by TovlyDeutsch** [comment]
Looks like the removal of this console warning was just merged into Chromium: https://chromium-review.googlesource.com/c/chromium/src/+/2159142. Not sure when it will appear in Chrome, perhaps after the next major release (mid-May I believe)?

**Comment by waynehaffenden** [comment]
As of 1st June using the latest release build of Chrome (Version 83.0.4103.61) this is still an issue.

**Comment by e-asia** [comment]
Still no changes about this issue.

**Comment by RubenNijhuis** [comment]
Still an issue

**Comment by suraneti** [comment]
Still an issue

```
Chrome: version 83.0.4103.116 (Official Build) (64-bit)
```

**Comment by Nnaji-Victor** [comment]
Still an Issue as of today!

**Comment by E-PL** [comment]
I've just updated Chrome to Version 84.0.4147.89 (Official Build) (64 bit) and I'm not getting the console warning anymore, I suppose that the removal of the warning message was merged into Chrome stable 🎉

**Comment by mxstbr** [comment]
Closing as this was a Chrome issue that has apparently been resolved as per @E-PL!

**Comment by Oceanside22** [comment]
Upstream
