### ISSUE TITLE
Problem with remark-images plugin dependencies

### ISSUE THREAD

**Issue by viatsko** [gatsbyjs/gatsby#1751]
Hi,

As you can see remark-images plugin depends on sharp code-wise https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/index.js

But there's no such dependency in package.json. I'm not familiar on how to make lerna manage this case (I'll try to look myself as well), but maybe this can be solved somehow so remark-images will be automatically installing sharp plugin.

Otherwise, it leads to an error after trying to start application, unless you installed sharp plugin as well, which is not a pleasant user experience.

**Comment by KyleAMathews** [comment]
It depends on gatsby-plugin-sharp. Which... might not be documented. That perhaps should be a peerDependency I guess.

**Comment by viatsko** [comment]
I've checked how it's done in another lerna projects and submitted a pull request

**Comment by viatsko** [comment]
Did a couple of runs and actually, I don't like this approach as it's not user-friendly.

Maybe it might make sense to, as you mention, document it or add a note in "postinstall" script (thinking about how to make it more user-friendly).

Will think about it for more time.
