### ISSUE TITLE
All images are being loaded from previous page on route change

### ISSUE THREAD

**Issue by greatwitenorth** [gatsbyjs/gatsby#17520]
## Description

Having a strange issue where all images are being loaded from a blog index page when visiting the blog post page.

### Steps to reproduce

- navigate to https://www.graphicintuitions.com/blog
- open your inspector
- click on the first blog article
- see all images from previous page being loaded in inspector

### Expected result

I only expect image on the new page to load.

### Actual result

I saw all the images from the previous page load. (I'm using lazy loading which is why I don't expect them to load initially).

<img width="1437" alt="Screenshot 2019-09-09 16 38 19" src="https://user-images.githubusercontent.com/547583/64568452-6b0dee00-d320-11e9-8b87-fad4de272f68.png">

### Environment

Github repo:
https://github.com/graphicintuitions/graphic-intuitions

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.1
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.15.12 => 2.15.12 
    gatsby-image: ^2.2.18 => 2.2.18 
    gatsby-plugin-crisp-chat: ^2.2.0 => 2.2.0 
    gatsby-plugin-google-tagmanager: ^2.1.9 => 2.1.9 
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16 
    gatsby-plugin-netlify: ^2.1.12 => 2.1.12 
    gatsby-plugin-netlify-cms: ^4.1.14 => 4.1.14 
    gatsby-plugin-nprogress: ^2.1.6 => 2.1.6 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-purgecss: ^2.4.0 => 2.4.0 
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sass: ^2.1.14 => 2.1.14 
    gatsby-plugin-sharp: ^2.2.21 => 2.2.21 
    gatsby-plugin-sitemap: ^2.2.12 => 2.2.12 
    gatsby-plugin-styled-components: ^3.1.5 => 3.1.5 
    gatsby-remark-copy-linked-files: ^2.1.18 => 2.1.18 
    gatsby-remark-images: ^3.1.21 => 3.1.21 
    gatsby-remark-relative-images: ^0.2.2 => 0.2.3 
    gatsby-remark-responsive-iframe: ^2.2.15 => 2.2.15 
    gatsby-source-filesystem: ^2.1.22 => 2.1.22 
    gatsby-transformer-remark: ^2.6.22 => 2.6.22 
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14 
  npmGlobalPackages:
    gatsby-cli: 2.6.4
```

**Comment by kimdhoe** [comment]
Maybe this is a browser's issue. Doesn't happen on Chrome Canary and Firefox.

**Comment by greatwitenorth** [comment]
Tested in Chrome Version 76.0.3809.132

**Comment by Grsmto** [comment]
I had a similar issue where images are loaded with gatsby-image no matter if they are on screen or not.
Works as intended on Firefox but not on Chrome mac 76.0.3809.132.

**Comment by LekoArts** [comment]
Sounds like a really weird problem 🤔 	Could you [provide a minimal reproduction][reproduction]? We'd appreciate that!

[reproduction]: https://gatsby.dev/reproduction

**Comment by greatwitenorth** [comment]
Here's a minimal reproduction:
https://github.com/greatwitenorth/gatsby-image-load-issue

Here's a video of the above repo in Chrome (mac 76.0.3809.132) and firefox (mac 69.0) showing that all images are loading in chrome, but not in firefox:
https://www.loom.com/share/0ff40f8efd664f51ad97107c7f3d4e0f

**Comment by greatwitenorth** [comment]
Any news on this? It's really putting a performance penalty on Gatsby sites when all images are being loaded by default.

**Comment by mcrisostomo9** [comment]
> I had a similar issue where images are loaded with gatsby-image no matter if they are on screen or not.
> Works as intended on Firefox but not on Chrome mac 76.0.3809.132.

Having same issue on Chrome 76 & 77 for Mac and Windows.  Works for FF/Safari/Edge.  Possible Chrome bug?
