### ISSUE TITLE
[docs][API] a new page on each of the gatsby-* files, with examples

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#17521]
## Summary

In going through the [docs recipes](https://gatsbyjs.org/docs/recipes), I'm wishing I had something to link to for each of the foundational files like `gatsby-config.js`, `gatsby-browser.js`, etc.

There is the [Gatsby File Structure](https://www.gatsbyjs.org/docs/gatsby-project-structure/#files) doc, and API docs for things like Browser and SSR APIs. But if someone wants to know what goes into each of the above files, there isn't a super clear path for doing that. I think we could make things a lot more straight-forward with a page on each of those (with example files).

### Examples

Adding a new API docs section: `Docs > Gatsby API > Files`, I envision it including new docs pages for:
-  `gatsby-config.js` - In addition to [Gatsby Config](https://www.gatsbyjs.org/docs/gatsby-config/), this page would include an easily-digestible starter file. It could link to the API doc and conceptual guide.
- `gatsby-browser.js` - In addition to [Gatsby Browser APIs](https://www.gatsbyjs.org/docs/browser-apis/), this doc would include an example file
- `gatsby-node.js` - This would be in addition to the doc on [Gatsby Node APIs](https://www.gatsbyjs.org/docs/node-apis/)
- `gatsby-ssr.js` - This would be in addition to [SSR APIs](https://www.gatsbyjs.org/docs/ssr-apis/)

### Motivation

Cross-linking between file basics and more conceptual API docs would help lower the barrier to entry for some of this stuff as people learn. Make it as easy as possible to get started, without having to poke around in example repos to find starting points.

**Comment by kevee** [comment]
I started working on this one a bit. Before I continue, let me know if this is the direction you are looking for:

- [The API files landing page](https://github.com/kevee/gatsby/blob/docs/gatsby-api-files-17521/docs/docs/api-files.md)
- [gatsby-config.js documentation page](https://github.com/kevee/gatsby/blob/docs/gatsby-api-files-17521/docs/docs/api-files-gatsby-config.md)

My initial thought is that each page should show basic structure and maybe one or two examples of the most common use cases, then link users off to the rest of the API docs. However, I'm just guessing at "most common" based on my own experience, so I might be off the mark.

**Comment by marcysutton** [comment]
That looks perfect! Having examples of what goes into these files would be excellent. Right now the docs explain some things but in general, you have to go find examples on GitHub to know how they're structured.

One thing I would add to the `gatsby-config.js` example is listing multiple plugins...perhaps an example of a complete file could help with that.

**Comment by kevee** [comment]
Added an example to the config page. How about this structure for the API files:

[intro paragraph]

## Set up [file]

[Describe the structure of the file (object, exports, etc.)

[Show example]

```
[this is the example]
```

## File options

[Paragraph that mentions link to API, this is just example with most common option, etc.]

### Example thing

[Description of example]

```
// Code for example
```

### Example thing 2

[Description of example 2]

```
// Code for example 2
```
