### ISSUE TITLE
Gatsby new and develop not working

### ISSUE THREAD

**Issue by msaaddev** [gatsbyjs/gatsby#17537]
## Description

Every time I do `gatsby new project` , I get this error.

![error](https://i.imgur.com/AEQEXKZ.png)

Then I change directory to the newly created project and if I run `gatsby develop`, I receive a new error.
 
![error](https://i.imgur.com/Ijhrqut.png)

I have also tried installing the package separately but it also doesn't work either.

### Steps to reproduce

I'm not sure how this could be reproduced.

### Expected result

My project should be created with no error. And when I run `gatsby develop`, it should open in localhost.

### Actual result

I receive errors every time I create a project and then run it.

### Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.15.14 => 2.15.14
    gatsby-image: ^2.2.18 => 2.2.18
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7
    gatsby-source-filesystem: ^2.1.22 => 2.1.22

**Comment by jonniebigodes** [comment]
@msaaddev follow the steps documented [here](https://www.gatsbyjs.org/docs/gatsby-on-windows/) and see if it helps.

**Comment by LekoArts** [comment]
Yeah, you need to install `node-gyp`. Some instructions:

- https://github.com/nodejs/node-gyp#on-windows
- https://gist.github.com/jtrefry/fd0ea70a89e2c3b7779c
