### ISSUE TITLE
[gatsby schema] Convert gatsby-transformer-sharp to use schema customization

### ISSUE THREAD

**Issue by freiksenet** [gatsbyjs/gatsby#17531]
Currently `gatsby-transformer-sharp` uses inference and old Gatsby schema customization (`extend-node-type`) for adding fields. There are several obscure errors that happen because of this.

It would be great to move sharp to use new schema customization. We should then also bump the version of transformer and make it rely on latest gatsby that has all the schema customization features.

If there are some features in schema customization that are missing for it to be possible, we should add that to schema customization along the way.

**Comment by sidharthachatterjee** [comment]
Published in `gatsby-transformer-sharp@2.3.0`
