### ISSUE TITLE
Preferred package manager doesn't work when yarn is installed via macports

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#17532]
https://github.com/gatsbyjs/gatsby/blob/24c30b95eac628edc3e1de0748c943e47ada813c/packages/gatsby-cli/src/init-starter.js#L30 doesn't work on macOS when yarn is installed via mac ports because it can't find `yarnpkg --version` as witnessed by @LekoArts 

This results in some folks never having a preferred package manager 😞

**Comment by wardpeet** [comment]
So what its the packageName? Just `yarn`?

**Comment by sidharthachatterjee** [comment]
Yup, just `yarn` ☹️ 

We use `yarnpkg` because 
```
// Checks the existence of yarn package and user preference if it exists
// We use yarnpkg instead of yarn to avoid conflict with Hadoop yarn
// Refer to https://github.com/yarnpkg/yarn/issues/673
```

**Comment by ascorbic** [comment]
I think this is a bug in the Portfile. It should be installing the yarnpkg script too. From the look of [this line](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/init.js#L161), it will be breaking create-react-app too.
