### ISSUE TITLE
Issue with matchPath sorting for nested paths

### ISSUE THREAD

**Issue by dopeters** [gatsbyjs/gatsby#17542]
## Description

With the updated matchPath sorting from https://github.com/gatsbyjs/gatsby/pull/17411, nested client only routes are not correctly displayed.

I believe it is also related to this issue: https://github.com/gatsbyjs/gatsby/issues/9705

### Steps to reproduce

[Code Sandbox](https://codesandbox.io/s/gatsby-starter-default-5pz0q?fontsize=14)

1. Go to /admin
2. Click "User 123"

### Expected result

You are navigated to `/admin/user/123` and `AdminUser` component is displayed

match-paths.json should look like this
```  
    {
        "path": "/admin/",
        "matchPath": "/admin/*"
    },
    {
        "path": "/admin/users/users/",
        "matchPath": "/admin/*"
    },
    {
        "path": "/admin/users/user/",
        "matchPath": "/admin/*"
    }
```

### Actual result

Url changes to `/admin/user/123`, but the `AdminUsers` component is displayed

match-paths.json looks like this:

```  
    {
        "path": "/admin/users/users/",
        "matchPath": "/admin/*"
    },
    {
        "path": "/admin/users/user/",
        "matchPath": "/admin/*"
    },
    {
        "path": "/admin/",
        "matchPath": "/admin/*"
    },
```

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.15.14 => 2.15.14 
    gatsby-image: ^2.2.18 => 2.2.18 
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7 
    gatsby-plugin-sharp: ^2.2.21 => 2.2.21 
    gatsby-source-filesystem: ^2.1.22 => 2.1.22 
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14

**Comment by jonniebigodes** [comment]
@dopeters  I've created new gatsby site based on the hello world starter and grabbed the code you posted. And  i can confirm this. In the meantime depending on your use case and timeframe i would go with [gatsby-plugin-create-client-paths](https://www.gatsbyjs.org/packages/gatsby-plugin-create-client-paths/), if you want i can update the code based on the plugin and hoist it to a repo and you can take a look at it at your own pace. Also i'm going to ping @wardpeet to see if he can chime in and possibly help you out better.

**Comment by pieh** [comment]
I'm not quite sure if this is bug. There are 3 routes with `/admin/*` matchPath so any of those are equally suitable to render `/admin/user/123` route (there is nothing we can use to decide whether to use one or the other)

**Comment by jonniebigodes** [comment]
@pieh it seems that what's intended is to funnel all the requests to the router inside `/admin/` and let it deal with it. Probably this is more a edge case and a possible solution for this case is actually use the plugin.

**Comment by dopeters** [comment]
@jonniebigodes The same thing happens in the actual app I found this issue in, which does use that plugin. If you are able to make an example with that plugin that works, I'd be very interested in seeing that.

Appreciate your help!

**Comment by dopeters** [comment]
@jonniebigodes Thank you this was extremely helpful. Looks like changing the directory of those pages does solve the issue we're seeing. Gonna go ahead and close this out. Appreciate all the help!

**Comment by jonniebigodes** [comment]
@dopeters no need to thank, just glad i was able to help and you were able to solve the issue.
