### ISSUE TITLE
How to change CSS Modules configuration?

### ISSUE THREAD

**Issue by SilencerWeb** [gatsbyjs/gatsby#17552]
## Summary
I want to change CSS Modules configuration but I can't find any information about how to do it

Also, I'm trying to find the current configuration but can't find it anywhere, could you help me with that? I use Storybook with Gatsby and I had to set up CSS Modules by myself for Storybook, and right now they have different configurations and work differently

**Comment by SilencerWeb** [comment]
Okay, I had to pass options in `cssLoaderOptions`

**Comment by adamrasheed** [comment]
@alampros where in the gatsby project would I add this?

**Comment by alampros** [comment]
@adamrasheed the file path is listed right above the snippet. In this case, it's in a local plugin folder called `pascal-case-css-modules`. You'd just have to add it to your plugins array in your `gatsby-config.js` like so:
```
"plugins": [
  'pascal-case-css-modules',
]
```

**Comment by wardpeet** [comment]
@alampros What do you think of creating a `gatsby-plugin-cssmodules-override` plugin that makes it possible to setup your own css-modules configuration?
