### ISSUE TITLE
Broken URL on Contributing page

### ISSUE THREAD

**Issue by anthonygilbertt** [gatsbyjs/gatsby#17561]
## Description

The 'Use an online dev environment' link is broken.

### Steps to reproduce

Go to the following URL: https://www.gatsbyjs.org/contributing/code-contributions/ and click on the 'Use an online dev environment' link

### Expected result

The User should be taken to the gitpod page

### Actual result

The User is taken to the "Page Not Found" page.

### Environment

I used the online dev environment:  https://gitpod.io/#https://github.com/gatsbyjs/gatsby

**Comment by anthonygilbertt** [comment]
The page is available, the URL is just wrong.

**Comment by marcysutton** [comment]
Hi @anthonygilbertt, we'd love a PR to fix it if you've got time to contribute!

**Comment by anthonygilbertt** [comment]
@marcysutton I will jump on it! 
 Just gotta figure out how to make one.  😅

**Comment by anthonygilbertt** [comment]
I think I figured it out.  https://github.com/gatsbyjs/gatsby/pull/17565    hopefully I did it right.  ha

**Comment by marcysutton** [comment]
Fantastic! Looks like the change was merged, so we can now close this issue. Thanks so much for contributing, and stay tuned for that doc!
