### ISSUE TITLE
Layout-render.js doesn't pick up state changes

### ISSUE THREAD

**Issue by craig-mulligan** [gatsbyjs/gatsby#1756]
There seems to be a bug with with the layout state change in dev mode,  with sync requires no `onPostLoadPageResources` is fired which means layouts aren't updated when changing routes. 

Quick look at the code and it looks like the `emitter` isn't emitting the event in dev mode, don't have time to look further right now, but if anyone can confirm that are seeing the same behaviour that'd be useful 👍

**Comment by KyleAMathews** [comment]
So this is a dev-only problem?

**Comment by craig-mulligan** [comment]
@KyleAMathews, yip.
