### ISSUE TITLE
Adding global SCSS styles (e.g. h1,h2,p)

### ISSUE THREAD

**Issue by vtolenti89** [gatsbyjs/gatsby#17608]
## Summary
I am unable to add a global SCSS style file to my project. I currently have the following project structure.
```
gatsby-config.js
/src
  /components
    layout.jsx
    /button
      button.jsx
      button.scss
  /pages
  /context
     default-context.jsx
  /styles
    styles.scss
    _mixins.scss
    _variables.scss
    _typography.scss
```
and `styles.scss` and `_typography.scss` are e.g. configured respectively in the following way:
```
//styles.scss
@import 'typography.scss';
```
```
//_typography.scss
p{
  font-family: "Roboto", "Open Sans", sans-serif;
  font-size:14px;
  color:$color-cello;
 @include bpTabletPortraitUp{
   font-size:16px;
 }
}

h1 {
  font-size: 24px;
  @include bpTabletPortraitUp {
    font-size: 48px;
   }
}

p.light {
  font-weight: lighter;
}
```
Whenever I try to apply any of the styles defined in `_typography.scss` I get e.g. the following error:
```
failed to @extend "p.light".
The selector "p.light" was not found.
```
it seems that `gatsby-browser.js` is not importing the style.
Any ideas?
Thank you

### File contents (if changed)

`gatsby-config.js`: 
```
plugins: [
...,
{
 resolve: `gatsby-plugin-sass`,
    options: {
          data: `@import "./src/styles/_variables.scss" , "./src/styles/_mixins.scss";`
      },
    }
...
]
```
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: 
```
import React from "react"
import { ContextProvider } from "./src/context/default-context"
import './src/styles/styles.scss'
export const wrapRootElement = ({ element }) => (
  <ContextProvider>{element}</ContextProvider>
)
```
`gatsby-ssr.js`: N/A

**Comment by andreas-groos** [comment]
Did you install `node-sass` as well? It's in the code sample in the docs and looking at my projects it's in `package.json` though it's never imported etc otherwise. Otherwise everything seems fine.

**Comment by vtolenti89** [comment]
Yes, I have it installed. I noticed though that I can only use all scss features, such as `color: $color-white;` or `@extend p` if ALL the scss files are imported within the `gatsby-config.js`. However, this leads to another very annoying problem. In case the scss file outputs any css data, it will be imported in all the files of the project, which is a very unwanted behavior.

**Comment by universse** [comment]
Have you tried import your _mixins & _variables in your scss files instead. From my experience, you can import them at the top of your main scss file, styles.scss in your case. Your mixins and variables will become available to other scss files that you import after.

**Comment by ksmorano** [comment]
Hello, this is how I do my scss:

requirements:
- `gatsby-plugin-sass`
- `node-sass`

`styles.scss`
@import("./path/to/variables/and/or/mixins/etc");
@import("./another/path/to/other/scss/files");

`gatsby-config.js`
```
module.exports = {
  plugins: [
`gatsby-plugin-sass`,
]
```

`gatsby-browser.js and gatsby-ssr.js`
import "./src/styles/styles.scss"

**Comment by claide** [comment]
Hi, had the same issue importing `scss` file to jsx component.
**Issue**
```
@import './global.scss'
Invalid CSS after "": expected 1 selector or at-rule, was "var content = requi"
```
**package.json**
```
....
"gatsby-plugin-sass": "^2.3.0",
"node-sass": "^4.14.0",
....
```

**gatsby-config.js**
```
plugins: [
     {
         resolve: `gatsby-plugin-sass`,
     }
]
```
