### ISSUE TITLE
[ gatsby-source-filesystem ]: Globbing in path option

### ISSUE THREAD

**Issue by Wolfsun** [gatsbyjs/gatsby#17607]
## Summary

gatsby-source-filesystem enforces an opinionated file system structure. The plugin path option (gatsby-config.js) configures a single directory (incl. nested dirs) and maps all contained files to a single name (sourceInstanceName). The ignore option provides some ability to exclude files, but is only useful in simple situations. Not blocking support for globbing in the path option (as already supported by chokidar library) would add a lot more flexibility. 

### Basic example

For example storing data for a user profile would currently best fit the following directory structure. Each type of data could then be mapped to a single sourceInstanceName.

```
Profiles >
__________Images >
_____________profile1image.jpg
_____________profile1image2.jpg
_____________profile2image.jpg
_____________etc...
__________Data >
_____________profile1data.json
_____________profile2data.json
_____________ etc...
```

However in some situations the following structure would be more useful and easier to maintain. 

```
Profiles >
__________Profile1 >
_________________image.jpg
_________________image2.jpg
_________________data.json
__________Profile2 >
_________________images.jpg
_________________data.json
```
                          
In this situation configuring two instances of gatsy-source-filesystem in gatsby-config.js with the following path options:

"./src/profiles/\*/\*.jpg" and "./src/profiles/\*/\*.json"

I think this should just work if the following code is modified in the gatsby-node.js file within the gatsy-source-filesystem plugin. To validate the chokidar library could be used to test if any results are found using the .getWatched() method. This will then allow chokidar to use its globbing functionality. 

```
// Validate that the path exists.
  if (!fs.existsSync(pluginOptions.path)) {
    api.reporter.panic(`
The path passed to gatsby-source-filesystem does not exist on your file system:
${pluginOptions.path}
Please pick a path to an existing directory.
See docs here - https://www.gatsbyjs.org/packages/gatsby-source-filesystem/
      `)
  }

  // Validate that the path is absolute.
  // Absolute paths are required to resolve images correctly.
  if (!path.isAbsolute(pluginOptions.path)) {
    pluginOptions.path = path.resolve(process.cwd(), pluginOptions.path)
  }
```

### Motivation

See above. Better file organisation.

**Comment by Wolfsun** [comment]
Please reopen this one thanks.

**Comment by Wolfsun** [comment]
Please reopen this one thanks

**Comment by cbravo** [comment]
I was looking for something along these lines too... 

I co-locate my images in the components that need them and this would help me too create a clean gatsby-source-filesystem config

example:
```
/components/ComponentA/images/image1.jpg,
/components/ComponentA/images/image2.jpg,

/components/ComponentB/images/image1.jpg,
```
