### ISSUE TITLE
Feature Request - Custom Event Tracking [gatsby-plugin-google-analytics] 

### ISSUE THREAD

**Issue by robmarshall** [gatsbyjs/gatsby#17603]
Hi,

I was about to write a custom event tracker in my most recent Gatsby build, but figured if it would help you out I could add it to your Google Analytics plugin.

The concept would be:

User can export a function "customTrackingEvent" from gatsby-plugin-google-anaytics

They can provide values for:
- eventCategory
- eventAction
- eventLabel
- eventValue

An example would be tracking what filters have been used to dynamically sort items on a page. On each press of the sorting button, the event would fire, and then the items would be sorted. Allowing the website admin to see which combination of events are more used.

I use a similar process for tracking a large number of events across my PHP sites, and it is a very useful piece of functionality from Google.

Thoughts? I will be making this over the next few days.

**Comment by LekoArts** [comment]
Hi @robmarshall 	👋 	
Thanks for the feature request, we'd love to have this in our plugin!

If you have questions about contributing to Gatsby, you can head over to https://www.gatsbyjs.org/contributing/
We also offer pair-programming sessions if you need help with implementing this feature. Last but not least you can of course reach out to us here in this issue if any questions arise. Thanks for this great idea! Cheers 👍
