### ISSUE TITLE
How to disable ESLint completely?

### ISSUE THREAD

**Issue by problem233** [gatsbyjs/gatsby#17606]
I want to remove ESLint from my Gatsby site completely, but Gatsby doesn't seem to provide a way to do this.

**Comment by r-i-c-h** [comment]
Try making a .eslintignore file with * or src/* or something like that? 

https://eslint.org/docs/user-guide/configuring

**Comment by problem233** [comment]
@r-i-c-h Is it possible to make gatsby not to call ESLint at all, so that I can remove the eslint dev dependency?

**Comment by LekoArts** [comment]
You should be able to create an empty `.eslintrc`or `.eslintrc.js` file and the eslint config shipped by default should be overwritten.

https://www.gatsbyjs.org/docs/eslint/#how-to-use-eslint

> Gatsby ships with a built-in ESLint setup. For most users, our built-in ESlint setup is all you need. If you know however that you’d like to customize your ESlint config e.g. your company has their own custom ESlint setup, this shows how this can be done.

Why do you want to remove ESLint though? It's highly beneficial for your code's quality.

**Comment by TheKnarf** [comment]
I would like this as well, but for a slightly different reason. I'm having some problems with the eslint setup of Gatsby and would like to setup eslint myself as normal instead of having it included in Gatsby.

**Comment by phil-lgr** [comment]
> Try making a .eslintignore file with * or src/* or something like that?

> https://eslint.org/docs/user-guide/configuring

I think there should be a way to disable it without adding empty files.

I want to let VS Code handle linting, and the CI, I don't need Gastby to do it.

I found no way to disable it, even setting 

```
new ESLintPlugin({
        extensions: ['no'],
        exclude: ['node_modules', 'lib', 'src', '*'],
        emitError: false,
        emitWarning: false,
        failOnError: false,
        failOnWarning: false,
      }),
```

does not work :(

**Comment by Shahzayb** [comment]
My legacy project contains approx 3,000 errors.

```
✖ 2905 problems (2883 errors, 22 warnings)
  721 errors and 0 warnings potentially fixable with the `--fix` option.
```
And it's not our first priority to fix them. I want to implement some new features in the website but the lining is getting in our way. How can I ignore all the lining errors for the `develop` & `build` commands and show them when I run `eslint` or `npm run lint` command.

package.json:
```
{
  "scripts": {
    "lint": "eslint --ext .jsx,.js src/",
    "lint-fix": "eslint --fix --ext .jsx,.js src/",
  },
  "devDependencies": {
    "eslint": "^7.2.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^1.7.0",
    "eslint-webpack-plugin": "^2.5.4",
    "gatsby-plugin-eslint": "^3.0.0",
    "prettier": "^2.2.1",
    "prettier-airbnb-config": "^1.0.0"
  },
}
```
eslintrc.js
```
module.exports = {
  globals: {
    __PATH_PREFIX__: true,
  },
  extends: ['airbnb', 'prettier'],
};
```

gatsby-config.js
```
plugins : [{
      resolve: 'gatsby-plugin-eslint',
      options: {
        stages: [],
        extensions: ['js', 'jsx'],
        exclude: ['node_modules', '.cache', 'public'],
        emitWarning: false,
        emitError: false,
        failOnError: false,
        failOnWarning: false,
      },
}]
```

**Comment by kirillgroshkov** [comment]
I ended up creating a patch for `eslint-webpack-plugin`, and it worked for me!

I had to do it, as it started breaking when I updated to eslint@9 with Flat config.

Here's the patch:

```patch
diff --git a/node_modules/eslint-webpack-plugin/dist/index.js b/node_modules/eslint-webpack-plugin/dist/index.js
index 1be3263..dd3bca4 100644
--- a/node_modules/eslint-webpack-plugin/dist/index.js
+++ b/node_modules/eslint-webpack-plugin/dist/index.js
@@ -79,8 +79,9 @@ class ESLintWebpackPlugin {
    * @param {string[]} exclude
    */
 
-
   async run(compiler, options, wanted, exclude) {
+    // Kirill: short-circuiting from here, otherwise it breaks local Gatsby build
+    return
     // Do not re-hook
     if ( // @ts-ignore
     compiler.hooks.thisCompilation.taps.find(({
```
