### ISSUE TITLE
docs: move inline commands in paragraph into new block in new line

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#17626]
## Summary

move inline commands in paragraph into new block in new line

#### before

5. Run `gatsby-develop` to see the newly generated pages and navigate through them.

#### after 

5. Run gatsby develop to see the newly generated pages and navigate through them:
```shell
gatsby  develop
```

#### code changes 

````diff
- 5. Run `gatsby-develop` to see the newly generated pages and navigate through them.
+5. Run gatsby develop to see the newly generated pages and navigate through them:
+```shell
+gatsby  develop
+```
````

### Motivation

I suggest always put commands which I need to run in terminak to put an extra code block in new line instead of online it in paragraph. 

Then it's more clear that this is command and not a symbol or something else

### sections

[ ] receipts
[ ] Blog
[ ] Docs

### related issue

#17374

**Comment by amreshk005** [comment]
@muescha can I take this issue.

**Comment by muescha** [comment]
you are welcome 👍

**Comment by pranshuchittora** [comment]
IMO, these changes are not required, as it might a bit confusing. 

cc @LekoArts

**Comment by amreshk005** [comment]
@muescha @muescha can I proceed further??

**Comment by muescha** [comment]
@amreshk005 yes go

**Comment by muescha** [comment]
@pranshuchittora 

> Changing all the command patterns on the page would be a helpful addition that would lend more clarity to the viewers. 

_Source @mehtavishwa30_ #17374

**Comment by pranshuchittora** [comment]
Oh, I didn't know that.
@amreshk005 pls go ahead with this and let me know if you need any help.
Happy Hacking :smile:

**Comment by LekoArts** [comment]
Sorry, but I have to disagree with this suggestion. It doesn't add any meaningful improvements but bloats the instructions with bigger code blocks and a longer document in general. People are used to inline comments (that's what they are for) and big code blocks don't add any value besides maybe a better layout. However, in the example you gave the information is secondary and the code block below is important.

On a side-note: Please wait for answers from the team to your questions -- the "approval" you quoted is from the PR author, not from the team. And we might disagree with things in issues/PRs and don't want users to waste their time on PRs which we'd close anyways.

**Comment by amreshk005** [comment]
@LekoArts It means that I can't proceed on this issue?

**Comment by muescha** [comment]
@amreshk005 

No proceeding. It would not be accepted :(

Sorry for misinformation from me.

**Comment by pranshuchittora** [comment]
I recommend closing this issue.

**Comment by muescha** [comment]
The `gatsby develop` was a bad example because this was repeating all over the receipt page and can also be inline. VAnd for the other commands the most of them are already in a block style. 

The idea was to look over all the documentation and see if there other places where inline commands (not the easy trivial `develop ****` ones) are used which can be changed to block style to make better docs.
