### ISSUE TITLE
Gatsby build on localhost works fine, but Github Pages has Network issues

### ISSUE THREAD

**Issue by trevorliberty** [gatsbyjs/gatsby#17625]
## Summary
I am testing out my first Gatsby production build, and when I am on my localhost, the build looks fine.

However, when I put my public build in my github pages repository, the styling is messed up completely.

## Relevant information

I took a look at my Network requests and found that Github pages was getting almost all 404 status for scripts and fetches: 
[img](https://i.imgur.com/AZl2WPc.png)

Then on localhost, the same Network log: 
[img](https://i.imgur.com/05l9LYd.png)

This may not be gatsby specific issue, but regardless I am wondering if anyone has had an issue with this in the past.

Thanks in advance

**Comment by muescha** [comment]
Can you explain how you resolved your issue?

**Comment by trevorliberty** [comment]
Yep - 
I had to set up my prefix paths correctly and run build as such:
`gatsby build --prefix-paths`

[Check out the docs](https://www.gatsbyjs.org/docs/path-prefix/)
