### ISSUE TITLE
Gatsby develop compiles twice

### ISSUE THREAD

**Issue by dardub** [gatsbyjs/gatsby#1762]
node: 8.2.1
gatsby-cli: 1.0.7
gatsby: 1.6.5

When creating a new site:
```
gatsby new my-site
```

Running ```gatsby develop``` will show compile and dev server info twice:

<img width="1516" alt="screen shot 2017-08-10 at 4 37 25 pm" src="https://user-images.githubusercontent.com/561983/29197131-0cc4e58a-7dee-11e7-923a-b875e4ecb835.png">

**Comment by jquense** [comment]
Yeah I'm not sure what causes this. Maybe one of the bootstrap things changing a file after webpack starts?

**Comment by KyleAMathews** [comment]
Never figured it out either :-) Never gotten high enough on list of TODOs to go do serious investigation...

**Comment by dave-elkan** [comment]
It occurs for me when I enable gatsby-remark-images

**Comment by nickmaltsev** [comment]
Seems like it's related to [this bug](https://github.com/webpack/watchpack/issues/25). Did test with mentioned there workaround, and it works well. @KyleAMathews i can create PR with it, if needed

**Comment by KyleAMathews** [comment]
PR would be great!

**Comment by KyleAMathews** [comment]
This was mostly fixed in https://github.com/gatsbyjs/gatsby/pull/3237

**Comment by jquense** [comment]
YEEEESSSSSSSSSS
