### ISSUE TITLE
MDX GraphQL transformer

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#17630]
# Summary

While MDX does work for Markdown body copy, I frequently have content I query via GraphQL; for example from a `yml` file (still in Markdown format though) that I'd like MDX to parse before returning. Is there something within `gatsby-node.js` that I can hook into so that it returns the same rendering engine the compiled JSX `gatsby-plugin-mdx` provides? I've heard of `@mdx/runtime` but that doesn't look like a preferred method. Is there something I can run text through and add it via a Node field?

This is somewhat of an extension on the question when users would want to run frontmatter or random text through remark; and while I do have a component I created that returns Markdown strings formatted input, it's also done on the client-side which I'd prefer not to.

**Comment by MANTENN** [comment]
Updates?

**Comment by zslabs** [comment]
@MANTENN,

@ChristopherBiscardi was nice enough to pass along some very useful links about this in https://twitter.com/chrisbiscardi/status/1173310893255356416 but I haven't had time to dig in yet. Will definitely update this ticket when I'm able to. Would also love to add it to the docs in some way for others that have a similar need can use.

**Comment by ChristopherBiscardi** [comment]
y'all are looking for this: https://www.christopherbiscardi.com/post/creating-mdx-nodes-from-raw-strings/

**Comment by LekoArts** [comment]
Currently the only way is to change the mediaType as described in Chris' blog post.
