### ISSUE TITLE
Issues when having a static query and page query in the same page

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#17643]
## Description

When you use both a static query and page query in a file, it will override one of them even if I name the data variables differently.

### Steps to reproduce

Here's a Repro: https://github.com/lannonbr/gatsby-static-and-page-repro

It's a fresh site with the default starter made by `gatsby new`. Then I added both a page query and static query to `src/pages/index.js`

### Expected result

Each query should build properly and work side by side.

### Actual result

It overwrote the page query with the static query

![Screenshot_2019-09-15 Home](https://user-images.githubusercontent.com/3685876/64924267-9d9c6880-d7b0-11e9-865a-e946dcc9545f.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
 System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  npmPackages:
    gatsby: ^2.15.15 => 2.15.15
    gatsby-image: ^2.2.19 => 2.2.19
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7
    gatsby-plugin-sharp: ^2.2.22 => 2.2.22
    gatsby-source-filesystem: ^2.1.22 => 2.1.22
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14
```

**Comment by sortofdev** [comment]
Also having this issue and is the reason i gave up on Gatsby. Looking forward to this getting solved
