### ISSUE TITLE
gatsby-plugin-manifest npm install sharp not working

### ISSUE THREAD

**Issue by markdid** [gatsbyjs/gatsby#17659]
I tried to install this plugin following the tutorial:
```npm install --save gatsby-plugin-manifest```

the install doesn't throw any errors but once I try building I get back.

```Something went wrong installing the "sharp" module```

Tried multiple times deleting node-modules, reinstalling, reinstalling sharp, etc. Nothing works
Other plugins have worked without any problems.
Thanks for any help

**Comment by muescha** [comment]
#17558 did you checked this?

**Comment by muescha** [comment]
Did you checked the troubleshooting section in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-manifest/README.md

**Comment by LekoArts** [comment]
You typically wouldn't (re-)install sharp but node-gyp. Have you followed the instructions here? https://github.com/nodejs/node-gyp

**Comment by kevinmungai** [comment]
Hi, I have been following the tutorial at [add-a-manifest-file](https://www.gatsbyjs.org/tutorial/part-eight/#add-a-manifest-file) on the official gatsby site but I have been experienced issues with the `gatsby-plugin-manifest` plugin. 

## error I am facing
Every time I run `gatsby build` or `gatsby develop` the error I get is:

```
/usr/bin/node /usr/share/yarn/bin/yarn.js run build
yarn run v1.17.3
$ gatsby build
success open and validate gatsby-configs - 0.021 s

 ERROR 


Something went wrong installing the "sharp" module

Module did not self-register.

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues


⠋ load plugins
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```
**This happens after the `yarn add gatsby-plugin-manifest` ran successfully.**

## what I have tried
1. I have deleted the `yarn.lock` file and the `node_modules` folder. Then ran `yarn` on the terminal without any issues.
2. I have also checked that the  version of the ` "gatsby-plugin-manifest": "^2.2.20",` in the package.json
3. I have tried running `yarn why sharp` and the result is as follows:
```
info Reasons this module exists
   - "gatsby-plugin-manifest" depends on it
   - Hoisted from "gatsby-plugin-manifest#sharp"
```

Thanks for taking your time to look at this.

**Comment by smakosh** [comment]
The issue is still occurring

**Comment by smakosh** [comment]
Duplicate of https://github.com/gatsbyjs/gatsby/issues/19103

**Comment by pvdz** [comment]
One reason might be that there are binaries being used that get explicitly compiled against node versions. This binary gets cached and seems to be unaware of node versions changing, like one might do with `nvm`, or after an upgrade.

If you get hit by this it might be worth to remove the node cache (`~/.npm/_cacache`) and `node_modules`, then running `npm install` again. I think the important bit is that you see the following steps somewhere while installing (this is explicit for my linux machine, on node 8). Important to note is that it downloads the libvips once or twice, and not always fetching it from cache.

```
 > sharp@0.23.3 install node_modules/gatsby-plugin-manifest/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz

> sharp@0.23.3 install node_modules/gatsby-plugin-sharp/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached ~/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz

> sharp@0.23.3 install node_modules/gatsby-transformer-sharp/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached ~/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz

> sharp@0.22.1 install node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
```

I encountered tihs today as well and can confirm this fixed it for me (I removed all of `./.npm` but that was probably overkill and removed some settings) and works on node 8.

**Comment by muescha** [comment]
thanks for the hints for removing also the npm cache 
yes i also use nvm
