### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by markdid** [gatsbyjs/gatsby#17658]
I tried to install this plugin following the tutorial:
```npm install --save gatsby-plugin-manifest```

the install doesn't throw any errors but once I try building I get back.
```success open and validate gatsby-configs - 0.005 s

Something went wrong installing the "sharp" module
```

Tried multiple times deleting node-modules, reinstalling, reinstalling sharp, etc. Nothing works
Other plugins have worked without any problems.
Thanks for any help

**Comment by muescha** [comment]
Can you explain how you resolved your issued?

**Comment by soosap** [comment]
I do get the same error as well.

**Comment by markdid** [comment]
> Can you explain how you resolved your issue?

Accidentely closed the issue, see https://github.com/gatsbyjs/gatsby/issues/17659
