### ISSUE TITLE
Existing unit testing setup provided as an example doesn't work

### ISSUE THREAD

**Issue by Powell-v2** [gatsbyjs/gatsby#17668]
## Description
Unit testing setup guide published on Gatsby's website isn't yielding expected results. The following error is thrown when I invoke Jest:

```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';

SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
```

I tried downloading [an example from this repo](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-jest) in order to verify - same issue.

By the looks of it, files aren't being transformed as they should.

### Steps to reproduce
Just try running tests in a subrepo I linked above.

### Expected result
Files are transformed properly, allowing tests to run.

### Actual result
Error on the first `import` line.

### Environment
  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.0.7 - /usr/local/bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.75
    Firefox: 69.0
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.45 => 2.13.52 
    gatsby-image: ^2.2.7 => 2.2.8 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.5 
    gatsby-plugin-mdx: 1.0.20 => 1.0.20 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.3 
    gatsby-plugin-sass: 2.1.3 => 2.1.3 
    gatsby-plugin-sharp: ^2.2.9 => 2.2.10 
    gatsby-source-filesystem: ^2.1.7 => 2.1.9 
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5

**Comment by LekoArts** [comment]
I cloned the `using-jest` repository and run `yarn jest` and I don't run into any issues. Can you please provide more information on how to reproduce this problem?

**Comment by Powell-v2** [comment]
Hi, thanks a lot for getting back to me and sorry about the delay. I updated `gatsby` to `2.15.28` and the issue vanished. Not sure what exactly caused it, but I'm happy it's running again : )
