### ISSUE TITLE
Add instructions on how dependencies can be updated

### ISSUE THREAD

**Issue by kosvrouvas** [gatsbyjs/gatsby#17665]
It would be really helpful if we added a new page in the docs, describing how someone can update the dependencies (plugins, gatsby etc) like it is here: https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#update-gatsby-related-packages

**Comment by thecodingaviator** [comment]
You mean dependencies as in project dependencies like `eslint` and alike. Right?

**Comment by marcysutton** [comment]
Great idea! This is really similar to https://github.com/gatsbyjs/gatsby/issues/14598, which could be expanded to include all dependencies since the process is the same. I'm going to close this one as a duplicate, so please continue brainstorming in the other issue.

**Comment by kosvrouvas** [comment]
Cool! Haven't seen #14598
