### ISSUE TITLE
gatsby running localhost unreachable

### ISSUE THREAD

**Issue by dbaldoni** [gatsbyjs/gatsby#17662]
Hello I'm a noob trying to learn how to use Gatsby. 
I run Gatsby on Ubuntu Server 18.04. Everything seems to be set correctly
node version is 12.10.0
npm version is 6.11.3

This is the output of gatsby develop 

> caravaggio@ubuntu-standard:~/hello-world$ gatsby develop
> success open and validate gatsby-configs - 0.127 s
> success load plugins - 0.128 s
> success onPreInit - 0.052 s
> success initialize cache - 0.067 s
> success copy gatsby files - 0.135 s
> success onPreBootstrap - 0.070 s
> success source and transform nodes - 0.146 s
> success Add explicit types - 0.056 s
> success Add inferred types - 0.316 s
> success Processing types - 0.212 s
> success building schema - 0.851 s
> success createPages - 0.054 s
> success createPagesStatefully - 0.240 s
> success onPreExtractQueries - 0.047 s
> success update schema - 0.177 s
> success extract queries from components - 0.368 s
> success write out requires - 0.066 s
> success write out redirect data - 0.047 s
> success onPostBootstrap - 0.051 s
> ⠀
> info bootstrap finished - 13.377 s
> ⠀
> success run static queries - 0.051 s
> success run page queries - 0.117 s — 2/2 31.05 queries/second
> success start webpack server - 2.545 s — 1/1 2.39 pages/second
>  DONE  Compiled successfully in 10268ms                                                                                   12:09:05 PM
> ⠀
> You can now view gatsby-starter-hello-world in the browser.
> ⠀
>   http://localhost:8000/
> ⠀
> View GraphiQL, an in-browser IDE, to explore your site's data and schema
> ⠀
>   http://localhost:8000/___graphql
> ⠀
> Note that the development build is not optimized.
> To create a production build, use npm run build
> ⠀
> ℹ ｢wdm｣: Compiled successfully.

however when I try to open to connect to localhost i get the following error:
ERR_EMPTY_RESPONSE

Port 8000 is open on the Ubuntu firewall and forwarded on my router. I also tried 

gatsby develop -H 127.0.0.1 / 0.0.0.0 / 192.168.50.100 

 (my local address) with same result.

Thank you,
Davide

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
