### ISSUE TITLE
A project is repainting constantly now, thought I'd ask here first...

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#17660]
Have a site that was scrolling just fine, and all of a sudden, it's not...trying to figure out why. Went into chrome and fired up some of the rendering overlays and saw this:

<img width="1440" alt="Screen Shot 2019-09-15 at 10 33 33 PM" src="https://user-images.githubusercontent.com/7884263/64936055-e7b13880-d808-11e9-9b9a-6d9c8cb03697.png">

Not sure what this means and googling I end up reading about passive event listeners, but I don't recall adding any event listeners just yet...

Anybody have any thoughts here what that might mean?

Thanks!

**Comment by LekoArts** [comment]
Hi!

We'd need more information here in order to be able to help you. When did this behavior occur, with which changes? Solely with updating Gatsby dependencies?
Do you have a reproduction of that issue?

**Comment by rchrdnsh** [comment]
I don’t really know is the problem. I had some other constant re-painting issues and solved all of them, but then I recently noticed this. Tried to walk a few thing back, but to no avail. I dunno if it happened recently or a while ago. Just threw it out quick to see if anybody might have seen it here before. I don’t remember doing anything css wise I’m that I could imagine would do something like, but then again, I don’t really event know what it means. I’ll try to keep figuring it out, but if you wanna take a look, it’s this repo...

https://github.com/arrowgtp/alma

**Comment by rchrdnsh** [comment]
I googled "touch event listener: NONE" and this is the first result:

https://developers.google.com/web/updates/2016/06/passive-event-listeners

dunno what this is is happening to everything in the app, but it seems to be the case that every element has this on it.

Man, I have no idea how to debug this, and it's driving me nuts...

**Comment by rchrdnsh** [comment]
Any thoughts @KyleAMathews and @DSchau? Ever seen something like this before in a gatsby site?

**Comment by rchrdnsh** [comment]
I downgraded my version of styled-components to try out tina-cms and the issue went away, so I can only assume that it is a styled components issue, so i will close this out.
