### ISSUE TITLE
post about automating deployment with github actions

### ISSUE THREAD

**Issue by jstacoder** [gatsbyjs/gatsby#17671]
#Summary 

I recently worked out a very easy way to setup github automatically running gatsby build and gh-pages for me using github actions/workflows, to totally automate my gatsby sites deployment on pushing to github.  

i was going to write up a post about the process and a brief explanation of the new actions feature, and how i worked it out to automate my deployment, i was wondering if that would be useful here?

**Comment by LekoArts** [comment]
Hi!

That sounds like a great idea for a blog post 👍 	We normally ask people if they want to cross-post their existing posts on our blog. So for your case this means: Feel free to write a blog post about that topic on your own personal blog / or somewhere else and reach out to us afterwards. Our marketing department then will see if we can fit in the post into the schedule.

Hope that clears things up, and thanks for using Gatsby!
