### ISSUE TITLE
feature request: add technologies used as tags to site showcase

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#17670]
## Summary

Just now sites in showcase are tagged by business, but it would be interesting also to have the used technologies tagged like in the starters. 

### Basic example

#17652 removed interesting tags because technology is not in site tags

### Motivation

I can search and see the technologies used and hat's even more interesting if the source code is public and I can sneak into

### Additional

It would also nice to have all plugins used in gatsby-node / package.json somehow indexed (when there is a public repo) - then I can search for it too (I don't know how is the best to display it. But it would be helpful in some cases just to search for it)

**Comment by muescha** [comment]
cc @gatsby/learning 

any interests to add the same tech categories from starters to the showcase?

**Comment by muescha** [comment]
@gatsbyjs/learning

**Comment by laurieontech** [comment]
Thanks for the PR! This is something I want to bring up with the team, so adding it to my list.

**Comment by muescha** [comment]
Just a note:

the dependencies analysis from packages.json is already implemented for the starters and can reused similar for showcase sites with public GitHub repos

**Comment by marcysutton** [comment]
In general, we aren't going to take on work related to site showcase as there is a proposal to move it all out of the repo. Therefore, I'm going to close this issue as it's not something we're going to do. We appreciate your thinking here though!

**Comment by muescha** [comment]
thanks for feedback

is there a link to this showcase proposal to read more about this change	?

**Comment by marcysutton** [comment]
> is there a link to this showcase proposal to read more about this change ?

Not at this time. I can say that we're still merging showcase PRs, but not taking on more substantial changes. We'll create a new issue for it when we have info to share.
