### ISSUE TITLE
.gatsby configuration directory

### ISSUE THREAD

**Issue by tmm** [gatsbyjs/gatsby#17672]
## Summary

One of Gatsby's strengths is its configuration files (`gatsby-config.js`, `gatsby-node.js`, `gatsby-ssr.js`, `gatsby-browser.js`), however, in a project with many files, it's difficult to keep them organized inline with many other tools in the JavaScript ecosystem.

A configuration directory (`.gatsby`) to house Gatsby's config files would help eliminate this sprawl and could serve as a central location for config files (i.e. `gatsby-node`), local plugins, and other configuration resources (webpack config).

### Basic example

Instead of many files prefaced with `gatsby-`, configuration could be moved inside of an optional `.gatsby` directory (and the prefix could be dropped). For example,

```
/
|-- /.cache
|-- /.gatsby
    |-- /plugins
    |-- /webpack
        |-- index.js
    |-- config.js
    |-- node.js
    |-- ssr.js
    |-- browser.js
|-- /public
|-- /src
    |-- /pages
    |-- /templates
    |-- html.js
|-- /static
```

Users that don't have many customizations (local plugins, config files) or are content with their directory structure would not be forced to adopt the `.gatsby` directory. Gatsby could discover what structure is being used (default to `gatsby-config.js`) or take a CLI argument (`--config path/to/config`) to add support for this behavior.

### Motivation

Adding a `.gatsby` configuration directory supports organizing sprawl from large Gatsby projects using all the configuration files, local plugins, and other customization. In short, it centralizes everything related to Gatsby inside its own location instead of residing in the project root.

This is a relatively common pattern (i.e. `.storybook/config.js`) that could be backwards compatible to support those that do not want to upgrade and is extensible for the future if/when Gatsby adds more configuration.

**Comment by Undistraction** [comment]
This is a great idea.

**Comment by Undistraction** [comment]
Still a great idea.

**Comment by tmm** [comment]
@wardpeet said he had some thoughts, then this issue can be closed.

**Comment by Undistraction** [comment]
@tmm so why was this closed?

**Comment by tmm** [comment]
@Undistraction Sorry didn't get your notification for a while. He said they are not considering adding this behavior.

@wardpeet if you have a moment, would be good to hear why for others looking at this issue in the future.

**Comment by Undistraction** [comment]
@tmm thanks for the update. A shame as this would be a really helpful way of organising things.

**Comment by LekoArts** [comment]
Our stance on this hasn't changed since then, we still don't consider adding this. The overhead of changing this is way too high compared to the potential benefits. We haven't heard this request at all in our constant interaction with the community and the whole ecosystem (tutorials, gatsby recipes, themes, plugins) is based on this convention that it isn't worth the breaking change.

**Comment by tmm** [comment]
Thanks for the reply. Doesn't seem like this has to be a breaking change though (you know the codebase better than me). `gatsby-*.js` could be checked first, then `.gatsby/*.js`.

**Comment by waynevanson** [comment]
Absolutely one up on this idea.

Looking forward to this being added to v4 (please)!

**Comment by stefanpl** [comment]
Any updates here?
