### ISSUE TITLE
Debugging plugin conflicts

### ISSUE THREAD

**Issue by AAverin** [gatsbyjs/gatsby#17685]
## Summary

My styled-component plugin doesn't seem to work. styled components work fine in 'develop' without the plugin, but I need it to build the site and as soon as I add the plugin – no components load.
Anyways, I suspect it's a problem in plugins, so my question is – how can I debug plugin conflicts? Probably some of them add something to ssr logic or other gatsby parts. 
Where can I see merged logic to see if there are any possible problems?

**Comment by AAverin** [comment]
I found a problem with style-components not rendering.
It was a mistake in the css styling. Still, odd that there are no errors for that, no checks

**Comment by muescha** [comment]
can you find a place in the code where Gatsby can check it and then throw an error message?
