### ISSUE TITLE
jerky route transitions on dynamic app

### ISSUE THREAD

**Issue by BernardA** [gatsbyjs/gatsby#17688]
## Description

I am starting with Gatsby building a dynamic web app. I've noticed a couple of navigation issues:
- if I try to access a private route, I can see the content of the private page being shown on screen for a moment before being redirected to the login page.
- on logout, particularly if done from the `/admin` page, it will first go to `/login`, before being redirected to the homepage. From `console.log`, I can see that the `/admin` route is kept on the `location` object. That, of course, will explain the momentary transition to `/login` before finally being replaced by `/`.

I mostly followed [your tutorial on private routes](https://www.gatsbyjs.org/tutorial/authentication-tutorial/), with some modifications. 

As I have placed a link to the repository with the full code below, I will not repeat everything here. So just including some more relevant ones:

`gatsby-config.js`

     // private routes
         {
            resolve: 'gatsby-plugin-create-client-paths',
            options: { prefixes: ['/admin/*'] },
        },
        {
            resolve: 'gatsby-plugin-create-client-paths',
            options: { prefixes: ['/mailbox/*'] },
        },
        {
            resolve: 'gatsby-plugin-create-client-paths',
            options: { prefixes: ['/account/*'] },
        },

One example of a private route:

`/pages/admin.js`

      import React from 'react';
      import { Router } from '@reach/router';
     import PropTypes from 'prop-types';
     import Layout from '../components/layout';
     import SEO from '../components/seo';
     import PrivateRoute from '../components/privateRoute';
     import AdminHome from '../components/adminHome';

     class Admin extends React.Component {
      render() {
        console.log('admin props', this.props);
        const { location } = this.props;
        return (
            <Layout location={location}>
                <SEO title="Admin" />
                <Router>
                    <PrivateRoute
                        path="/admin/"
                        component={AdminHome}
                        location={location}
                    />
                </Router>
            </Layout>
        );
      }
     }

`/components/privateRoute.js`

     import React, { Component } from 'react';
     import { navigate } from '@reach/router';
     import { withCookies, Cookies } from 'react-cookie';
     import PropTypes from 'prop-types';

     class PrivateRoute extends Component {
    render() {
        console.log('private route props', this.props);
        const {
            // eslint-disable-next-line no-shadow
            component: Component, cookies, location,
        } = this.props;
        const isAdmin = cookies.get('isAdmin') === 'true';
        const isLoggedIn = cookies.get('username') !== undefined;

        const notOnLoginPage = location.pathname !== '/login';
        const finalRoute = location.pathname;
        if (location.pathname.includes('/admin')) {
            if (isAdmin) {
                return <Component />;
            }
            navigate('/login', { state: { finalRoute } });
        } else if (isLoggedIn) {
            return <Component />;
        } else if (notOnLoginPage) {
            navigate('/login', { state: { finalRoute } });
        }
        return null;
      }
    }

The navigation component:

      import React from 'react';
     import { Link } from 'gatsby';
     import { connect } from 'react-redux';
     import { MenuList, MenuItem } from '@material-ui/core';
     import { withCookies, Cookies } from 'react-cookie';
     import PropTypes from 'prop-types';

     const activeStyle = {
       background: 'red',
    };

    class Nav extends React.Component {
    render() {
        const { cookies } = this.props;
        const isAdmin = () => {
            if (cookies.get('session')) {
                const { roles } = cookies.get('session');
                const isAd = !!roles.includes('ROLE_ADMIN') || roles.includes('ROLE_SUPERADMIN');
                if (isAd) {
                    return (
                        <Link to="/admin" activeStyle={activeStyle}>
                            <MenuItem disableGutters>
                                Admin
                            </MenuItem>
                        </Link>
                    );
                }
            }
            return null;
        };

        return (
            <MenuList className="nav grid">
                <Link to="/" activeStyle={activeStyle}>
                    <MenuItem disableGutters>
                        Home
                    </MenuItem>
                </Link>
                <Link to="/search" activeStyle={activeStyle}>
                    <MenuItem disableGutters>
                        Search
                    </MenuItem>
                </Link>
                <Link to="/account/" activeStyle={activeStyle}>
                    <MenuItem disableGutters>
                        Account
                    </MenuItem>
                </Link>
                <Link
                    to="/mailbox"
                    activeStyle={activeStyle}
                    partiallyActive
                >
                    <MenuItem disableGutters>
                        Mailbox
                    </MenuItem>
                </Link>
                {isAdmin()}
            </MenuList>
        );
     }
    }

The logout method on the `header` component:

       handleLogout = () => {
        const { cookies } = this.props;
        cookies.remove('isAdmin');
        cookies.remove('username');
        cookies.remove('session');
        this.props.actionLogout();
        navigate('/');
    };

### Steps to reproduce

Please see [this repository with the source code](https://github.com/BernardA/quiamo)

### Expected result

Seamless transition

### Actual result

Jerky transition

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
         System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.7.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 65.0.1
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.15.9 => 2.15.9
    gatsby-image: ^2.2.17 => 2.2.17
    gatsby-link: ^2.2.12 => 2.2.12
    gatsby-plugin-create-client-paths: ^2.1.7 => 2.1.7
    gatsby-plugin-manifest: ^2.2.14 => 2.2.14
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-offline: ^3.0.3 => 3.0.3
    gatsby-plugin-react-helmet: ^3.1.6 => 3.1.6
    gatsby-plugin-sharp: ^2.2.20 => 2.2.20
    gatsby-source-filesystem: ^2.1.21 => 2.1.21
    gatsby-source-graphql: ^2.1.12 => 2.1.12
    gatsby-transformer-sharp: ^2.2.13 => 2.2.13
  npmGlobalPackages:
    gatsby-cli: 2.6.4

**Comment by jonniebigodes** [comment]
@BernardA i'm cloning your repo as i type this and let me take a look at and see if i can solve your issue. Do you mind waiting a bit?

**Comment by BernardA** [comment]
I can only be appreciative of your assistance.
