### ISSUE TITLE
Very Slow 'build' and 'develop' times. Netlify deployments fail

### ISSUE THREAD

**Issue by dante-blitz** [gatsbyjs/gatsby#17689]
## Description

Hi there,

We are experiencing very slow times when running deploy and build tasks. This is also causing Netlify deployments to fail as the deployment process exceeds the 15 minute time limit.

A little background info regarding our use case...

We are using Gatsby and gatsby-source-datocms.

Our client has 26,000+ external news articles in their DatoCMS instance. Each record basically holds a title and an external url.

We do not generate individual gatsby pages for each article, rather we place them on landing pages (24 articles per page).

Since adding all 26,000 news articles to DatoCMS we have seen the develop and build tasks slow down significantly. This happened even before we created the landing pages, or ran any queries for the news articles.

The bottleneck happens on the following build tasks:

```
10:59:33 AM: success loading DatoCMS content — 715.684
10:59:55 AM: success source and transform nodes — 737.087
```

My initial suspicions lie with the gatsby-source-datocms plugin. I have created an issue in the gatsby-source-datocms and am awaiting a response. 

I also wanted to report here, in case the issue lies with the gatsby build process.

Can anyone with knowledge of gatsby's inner workings provide any insight as to why this might be happening.  Any resolutions or workarounds are highly apprecaited?

Thanks in advance.

### Steps to reproduce

NA

### Expected result

Fast develop and build times

### Actual result

Slow develop and build times (in excess of 15 minutes)

### Environment

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/user/.windows-build-tools/python27/python
  Browsers:
    Edge: 44.18362.329.0
  npmPackages:
    gatsby: ^2.15.14 => 2.15.14 
    gatsby-image: ^2.2.18 => 2.2.18 
    gatsby-plugin-eslint: ^2.0.5 => 2.0.5 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6 
    gatsby-plugin-offline: ^3.0.6 => 3.0.6 
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7 
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2 
    gatsby-plugin-sharp: ^2.2.21 => 2.2.21 
    gatsby-plugin-sitemap: ^2.2.12 => 2.2.12 
    gatsby-plugin-styled-components: ^3.1.5 => 3.1.5 
    gatsby-plugin-webpack-size: ^1.0.0 => 1.0.0 
    gatsby-source-datocms: 2.1.15 => 2.1.15 
    gatsby-transformer-remark: ^2.6.22 => 2.6.22 
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14

**Comment by dante-blitz** [comment]
https://github.com/datocms/gatsby-source-datocms/issues/78

**Comment by dante-blitz** [comment]
https://github.com/datocms/gatsby-source-datocms/issues/78

**Comment by LekoArts** [comment]
Thank you for opening this!

This seems to be a bottleneck with the network / the API of DatoCMS and pulling down the information. You can see reduced build times in subsequent builds as Gatsby caches things in `.cache`. You could try using https://www.npmjs.com/package/gatsby-plugin-netlify-cache or building the site on CircleCI and push it to Netlify afterwards.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
