### ISSUE TITLE
[Request] Add ability to exclude files / folders when compiling query

### ISSUE THREAD

**Issue by jacksaunders** [gatsbyjs/gatsby#17691]
## Summary

I would like the ability to exclude whole folders form the query compiler rather than scanning every js / ts file in the repo.  
There are use cases where often you don't want every file parsed / built, for example when needing to use the same codebase with separate CMS's. 

### Basic example
In gatsby.config.js` could be defined by 

```
module.exports = {
  excludeFiles: ['/src/templates/folderName/**.js'],
}
```
### Motivation

Motivation for this is the desire to use the same codebase for maintainability / code sharing but the ability to build some templates under certain circumstances. 

My use case is we have one website for UK and one for Germany. The design is similar enough to warrant the same codebase but the layout and content are very different. 
We are using two different Contentful spaces to achieve this. However currently we need to create "Dummy" pages in some occasions to prevent gatsby throwing 
`- Unknown field on type 'Query'.` errors

What i would like to do is separate my templates in the codebase and then exclude those templates and the queries in them from getting built / parsed

**Comment by LekoArts** [comment]
I think what you really want to do is leveraging two of Gatsby's new features:

- [Gatsby Themes](https://www.gatsbyjs.org/docs/themes/)
- [Schema Customization API](https://www.gatsbyjs.org/docs/schema-customization/)

This will save you from duplicate code bases and with the latter you can fix your missing types by defining defaults:

https://www.gatsbyjs.org/docs/schema-customization/#fixing-field-types

**Comment by ssijak** [comment]
@jacksaunders Hey, have you found a solution for this? I need the same thing.

**Comment by villerdex** [comment]
+1

**Comment by jacksaunders** [comment]
Unfortunately I couldn’t find a way to reasonably exclude folders

I ended up having to create a monorepo using lerna for the 2, then duplicate the pages for each and then have a shared component library in there

**Comment by mosesoak** [comment]
@jacksaunders @villerdex @ssijak or anyone else needing to do this: 

I was able to excluded a folder using a [negative lookahead](https://stackoverflow.com/questions/2078915/a-regular-expression-to-exclude-a-word-string) regex: 

`absolutePath: { regex: "/(?!.*/pages/library/.*)(.*/pages/.*)/" }`
