### ISSUE TITLE
Sort group by field values

### ISSUE THREAD

**Issue by universse** [gatsbyjs/gatsby#17690]
I have a use case where I need to sort groups by fieldValue. Apparently there was a similar FR before #3684.

I can open a pull request too and will need some guidance.

**Comment by muescha** [comment]
Similar #7628

**Comment by vladar** [comment]
@universse Isn't it a duplicate of #7628 ?

**Comment by universse** [comment]
I think there's a difference.

For eg, using the following query,

```js
allData(sort: { fields: date, order: DESC }) {
          group(field: category) {
            fieldValue
            nodes {
              id
            }
          }
        }
```

I would want the ability to sort the group by `fieldValue`. So I would get some things like `allData.group = [{ fieldValue: 'group1'}, { fieldValue: 'group2'}, { fieldValue: 'group3'}, ...] `. It's not possible to do this currently. This is similar to #3684, which was closed.

As for #7628, I think what the OP meant is that the `nodes` within each group do not follow the sort order specified in the query, which is `{ field: data, order: DESC }` in the above eg.

**Comment by Ir1d** [comment]
Looking forward to this feature! We're currently sorting this outside graphql on our own.

**Comment by abeMedia** [comment]
Any updates on this? I have the same requirement. Right now I'm sorting in JS from the component but it would be great if this could be done in GraphQL.
