### ISSUE TITLE
Avoiding trademark violations

### ISSUE THREAD

**Issue by horacioh** [gatsbyjs/gatsby#17697]
Hey!👋 

I'm close to publish a video series of tutorials in spanish around Gatsby here: https://aprendegatsby.com/. I also create a twitter account (https://twitter.com/aprendegatsbyjs)

@jasonbahl politely approach me about a trademark violation I was doing on the GatsbyJS logo.

First, I want to say **I'M SORRY**, my intention is not to harm anyone or anything, I did not know there was a trademark violation. What I knew was that I was using the logo wrong 🤦‍♂. I inmediately removed and replaced the previous logo.

The logo is not being used now but another question comes to me:
**Is there another trademarks I'm not aware of that I might be or maybe will violate in the future?**

I think is important that we as content creators use and continue to be respectful with the technologies we are trying to promote and use, that's why I'm asking.

I saw the [Logo guidelines](https://www.gatsbyjs.org/guidelines/logo/) and those are amazing, but I don't know if there's something also being violated about the name "gatsbyjs", "GatsbyJS" or even "Gatsby"...

again, sorry for my big mistake and thanks in advance for the info!

**Comment by marcysutton** [comment]
Hi @horacioh, thanks so much for reaching out, we appreciate it. I see you've got a new logo that's unique to your project, which is awesome (it's got a fun style to it, too!). As for naming restrictions using "gatsbyjs", it's something we're discussing internally–the logo guidelines are our best resource for now. We should have more to say on that topic soon.

As a side-note after seeing the nature of your project, one thing that might help in the future is our [translation effort](https://github.com/gatsbyjs/rfcs/pull/42) for the Gatsby docs. We'd love to have your contributions on translating the docs and tutorials into Spanish, if you're interested. We know how important it is to have localized learning materials to help people learn about Gatsby in a way that works best for them. So stay tuned for that. And thanks for your enthusiasm!

**Comment by horacioh** [comment]
Thanks @marcysutton !

yeah, I'm aware of the RFC, I mentioned [there](https://github.com/gatsbyjs/rfcs/pull/42#discussion_r324398534) that I already started translating the docs to spanish and some others joined me and start translating other parts of the docs :)

also, I proposed [this](https://github.com/gatsbyjs/rfcs/pull/42#issuecomment-531607436) as a crazy idea :)

thanks again and looking forward to see where these RFC goes :)
