### ISSUE TITLE
gatsby-plugin-netlify breaking netlify build

### ISSUE THREAD

**Issue by tr1s** [gatsbyjs/gatsby#17701]
## Description

I'm trying to redirect blog pages to a completely new location.

I tried adding the redirect `/blog/*   https://newsite/:splat` to `_redirects` file, but it only works in dev mode. Then I found out you need to install `gatsby-plugin-netlify` in order to redirect pages, but that just breaks my Netlify build.

I don't know what else I'm missing. What am I doing wrong?

Any information / help would be greatly appreciated!

<img width="1053" alt="CleanShot 2019-09-17 at 16 20 31@2x" src="https://user-images.githubusercontent.com/19172250/65076493-19d8ac80-d967-11e9-9c37-13f75b6e4dfb.png">

### Environment

I'm running Gatsby V1 on the old site, and Gatsby v2 on the new site. So naturally I looked at the v1 docs since I'm setting up the redirects there, but it's the same info. It tell me to make sure gatsby-plugin-netlify is at the end of the array.

```
  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
    npm: 6.11.3 - ~/.nvm/versions/node/v10.16.2/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Safari: 12.1.2
  npmPackages:
    gatsby: 1.9.277 => 1.9.277
    gatsby-image: ^1.0.55 => 1.0.55
    gatsby-link: ^1.6.34 => 1.6.46
    gatsby-plugin-netlify: ^2.1.13 => 2.1.13
    gatsby-plugin-react-helmet: ^2.0.3 => 2.0.11
    gatsby-plugin-remove-trailing-slashes: ^1.0.9 => 1.0.9
    gatsby-plugin-robots-txt: ^1.0.2 => 1.4.0
    gatsby-plugin-sass: 1.0.19 => 1.0.19
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48
    gatsby-plugin-sitemap: ^1.2.25 => 1.2.25
    gatsby-source-contentful: ^1.3.31 => 1.3.54
    gatsby-source-filesystem: ^1.5.39 => 1.5.39
    gatsby-transformer-remark: ^1.7.40 => 1.7.44
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27
  npmGlobalPackages:
    gatsby-cli: 2.7.39
```

**Comment by tr1s** [comment]
I googled webpack.stats.json and I came up with `webpack-stats-plugin` so I decided to install that. Still didn't work. 

I also tried to download a v1 version of `gatsby-plugin-netlify` that matched up with the timing of the old Gatsby v1, but that also didn't work.

Still trying things

**Comment by LekoArts** [comment]
Hi!

Upgrading to v2 is not an option? You'd receive multiple important performance optimizations in comparison to v1.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

[reproduction]: https://gatsby.dev/reproduction
