### ISSUE TITLE
Server side rendering (run time) on client only routes / SEO benefits with client only routes?

### ISSUE THREAD

**Issue by calspre** [gatsbyjs/gatsby#17704]
## Summary

- Can we do server-side rendering (SSR at run time) on client-only routes? 
- Or, is there a way to get SEO boost with client-only routes?

## Relevant information

I am building a client-facing web app with user-generated contents like Reddit / Quora. I understand Gatsby does SSR at build time but I was wondering if there's any way to do SSR at run time with client-only routes. The main reason is SEO. I read docs such as [client data fetching](https://www.gatsbyjs.org/docs/client-data-fetching/) and [building apps with Gatsby](https://www.gatsbyjs.org/docs/building-apps-with-gatsby) and did some search but couldn't find any relevant information.

How do we get the same SEO benefits that we get from statically generated pages?

**Comment by LekoArts** [comment]
> Can we do server-side rendering (SSR at run time) on client-only routes?

No, you unfortunately can’t do that right now.

> Or, is there a way to get SEO boost with client-only routes?

You could build out the client-only routes once a day to static pages after serving them client side before that. So in the "archive" they would be static pages. Does that things clear up?

**Comment by calspre** [comment]
Thanks for your comment @LekoArts! 

> You could build out the client-only routes once a day to static pages after serving them client side before that.

I am not completely sure what this means. Could you clarify a little bit?

**Comment by LekoArts** [comment]
Let's say you have a blog with posts at `/blog/:post-id` and you use a GraphQL endpoint to query data with `gatsby-source-graphql` and use `createPage` action in `gatsby-node.js` to create those posts.

Now you give other people access to your writing backend and they want to publish articles instantaneously. You'd create [client-only routes](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/) for that and fetch your API on the client on these dynamically created pages.

Then e.g. once a day you rebuild your site and the published articles from the last day are queried, too. You now replace the dynamically created pages with the static ones.

**Comment by calspre** [comment]
Thanks! That makes a lot more sense. 🙂 I will close the issue as the questions are resolved.
