### ISSUE TITLE
How do you know when an image is marked as critical?

### ISSUE THREAD

**Issue by Madgeniusblink** [gatsbyjs/gatsby#17702]
I found this paragraph in the gatsby documentation for the image plugin and I am wondering how do I know when an image is marked as critical... 

"Images marked as critical will start loading immediately as the DOM is parsed, but unless fadeIn is set to false, the transition from placeholder to the final image will not occur until after the component is mounted."

**Comment by LekoArts** [comment]
You are setting the prop on the respective image element: https://www.gatsbyjs.org/packages/gatsby-image/#gatsby-image-props

If you search for that on a website, you need to look out for `loading="eager"` on the image element.
