### ISSUE TITLE
babel-preset-gatsby-package doesnt specify corejs in babel preset

### ISSUE THREAD

**Issue by baerrach** [gatsbyjs/gatsby#17706]
## Description

While trying to develop a Gatsby plugin I get the following errors

```
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version.
```

This is because `babel-preset-gatsby-package` does not specify corejs in the preset

https://github.com/gatsbyjs/gatsby/blob/c5cc361d26b2e9e0b31ec68e9f040d7d97c4572f/packages/babel-preset-gatsby-package/index.js

But `babel-preset-gatsby` does.

https://github.com/gatsbyjs/gatsby/blob/c5cc361d26b2e9e0b31ec68e9f040d7d97c4572f/packages/babel-preset-gatsby/src/index.js

**Comment by gonzarodriguezt** [comment]
So the version needs to be the same as in `babel-preset-gatsby`? @LekoArts If that's the case i would like to contribute with this issue :)
