### ISSUE TITLE
Upgraded to last v1.8.2, failed to load.

### ISSUE THREAD

**Issue by syndia** [gatsbyjs/gatsby#1771]
Hello,
I just upgraded to v1.8.2 but now I get error: A local install of Gatsby exists but failed to load.
Before the upgrade everything was running with out problems. And last upgrade before was yesterday.

**Comment by syndia** [comment]
Møre info: ReferenceError: regenratorRuntime is bot defined.

**Comment by KyleAMathews** [comment]
We rolled out some big changes to our build script this morning and it broke some things 😞 fix is in works.

**Comment by syndia** [comment]
Ok, will roll back and wait till its fixed. Thanks and I really enjoy Gatsby. For me it's a great way to learn about react and more...

**Comment by jquense** [comment]
#1772

**Comment by syndia** [comment]
Found some more info: ReferenceError: regeneratorRuntime is not defined
    at .../gatsby/site/node_modules/gatsby-plugin-sharp/index.js:12:47

**Comment by KyleAMathews** [comment]
1.8.3 is out with @jquense's changes and everything looks good again. Sorry for the bother @syndia (and everyone else affected!)

**Comment by syndia** [comment]
Still have problems, see below is the output:

error A local install of Gatsby exists but failed to load.


  Error: Cannot find module 'core-js/modules/es7.string.pad-start'
  
  - module.js:11 require
    internal/module.js:11:18
  
  - cli.js:87 Object.<anonymous>
    [site]/[gatsby]/dist/bin/cli.js:87:1

**Comment by KyleAMathews** [comment]
@syndia could you do a fresh install? Delete `node_modules` and any lock file you have and reinstall?

**Comment by jquense** [comment]
DOH!

**Comment by jquense** [comment]
well no it should be required, npm should handle that deduping, but it can't hurt to add it

**Comment by syndia** [comment]
I added the module locally and it's running

**Comment by KyleAMathews** [comment]
@syndia which version of NPM are you using?

**Comment by syndia** [comment]
I'm using npm v5.0.3 and node V8.1.2

**Comment by KyleAMathews** [comment]
hmmm npm <5.3 has seen a lot of troubles for whatever reason.

Anyways, @jquense I'll just add core-js as a dependency
