### ISSUE TITLE
Gatsby does not load CSS immediately

### ISSUE THREAD

**Issue by alexpreiss** [gatsbyjs/gatsby#17728]
## Description

When you visit https://www.ucode.com/trial/register/ the CSS does not load properly; The checkmarks are huge and the form is a mess. However, some CSS does work, like the bottom of the form and the footer/nav (these are from the SEO component, though). The weird thing is that if you hard refresh it does load properly... a normal refresh following that will break it again. If you open the mobile nav it also seems to trigger the styles to be requested, as they load momentarily after.
This also seems to have started happening after I started using the gatsby-plugin-offline plugin so it could be related to that... I also created a duplicate of the page at https://www.ucode.com/trial/notregister/ and it displays a white screen unless you hard refresh. 

Here are the console errors on /trial/notregister/ :
```
app-47cd0a205929ec73be54.js:1 Uncaught (in promise) TypeError: e.components[t] is not a function
    at r.loadComponent (app-47cd0a205929ec73be54.js:1)
    at app-47cd0a205929ec73be54.js:1

```
### Steps to reproduce

I don't know how it started happening :/ sorry

### Expected result

Styles load immediately.

### Actual result

Styles only load properly on hard refreshes.

### Environment

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.15.15 => 2.15.15 
    gatsby-cli: ^2.7.47 => 2.7.47 
    gatsby-image: ^2.2.19 => 2.2.19 
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1 
    gatsby-plugin-google-tagmanager: ^2.1.9 => 2.1.9 
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16 
    gatsby-plugin-offline: ^3.0.6 => 3.0.6 
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sass: ^2.1.14 => 2.1.14 
    gatsby-plugin-sharp: ^2.2.22 => 2.2.22 
    gatsby-plugin-sitemap: ^2.2.12 => 2.2.12 
    gatsby-plugin-stripe: ^1.2.3 => 1.2.3 
    gatsby-source-filesystem: ^2.1.22 => 2.1.22 
    gatsby-source-wordpress: ^3.1.31 => 3.1.31 
    gatsby-transformer-remark: ^2.6.22 => 2.6.22 
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14 

**UPDATE**
I moved around some CSS imports and this page seems to work fine now.
But now I get white flashes every time I change pages unless im incognito.
I also get his error:
```
sw.js:formatted:63 Uncaught TypeError: messageApi[gatsbyApi] is not a function
    at sw.js:formatted:63
```
But only if I load the page without the console open... Sooo weird.
It seems like the gatsby offline plugin is definitely doing something weird.

**Comment by ARXChrono** [comment]
So it works as you'd expect without gatsby-plugin-offline?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by jamessimone** [comment]
Likely related to #8560

**Comment by alexpreiss** [comment]
> So it works as you'd expect without gatsby-plugin-offline?

I believe it did. I started to notice this around when I added the plugin.
I also get this error in the console occasionally:
sw.js:formatted:63 Uncaught TypeError: messageApi[gatsbyApi] is not a function
    at sw.js:formatted:63
which is in sw.js, I think that is the service worker js file.

**Comment by alexpreiss** [comment]
> Hi!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

I'll do my best to create one.
