### ISSUE TITLE
loader postcss with postcss-purgecss (@fullhuman)

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#17729]
I added in my gatsby a nice thing to purge global css not used in my application (i use wordpress and massive global style was not used) 

I think it s a pretty nice feature.. 
A new plugin to start implement maybe.
The only thing to start with is to configure purge-css with all js,jsx from the app in src/
The condition to work with is to have a full working ssr , if your ssr is broken and html not well generated then your css will be empty as a result .

purge-css need as well one first build of the app folder (so for me i copied one build in a new created folder 'preload ')

Purge-css collect all the class from the html and all the javascript, if there is no match with the css compiled it's stripped

here my rules added in postcss rules located in gatsby/dist/utils/webpack-utils.js for who interested

 postcss: (options = {}) => {
...
```

const purgecsshtml = require(`purgecss-from-html`);


plugins: loader => {
              plugins = (typeof plugins === `function` ? plugins(loader) : plugins) || [];
              
             var firstel= [flexbugs, autoprefixer({
                overrideBrowserslist,
                flexbox: `no-2009`
              }),
               ...plugins]; 
if(PRODUCTION)
              firstel.push(require('@fullhuman/postcss-purgecss')({
		 content: [
        ...glob.sync( directoryPath('preload/**/*.html'), { nodir: true }), //all the html
directoryPath('src/html.js'),
     directoryPath('src/layouts/index.jsx'),     
     ...glob.sync(directoryPath('src/components/*.{js,jsx}'), { nodir: true }), 
 ...glob.sync( directoryPath('src/templates/*.{js,jsx}'), { nodir: true }) ],
							extractors: [					
        {
            extractor: purgecsshtml,
            extensions: ["html"] //for html
        },
	 { extractor: class {  
		 static extract(content) { //for javascript
			 return content.match(/[\w-/:]+(?<!:)/g) || [];
		 	}
			 },
		 extensions: ['js', 'jsx' ]
		 }
                ]
                })
...
```

**Comment by LekoArts** [comment]
Thank you for opening this!

I don't see a question here :)

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
