### ISSUE TITLE
[docs] design iconography for different types of callouts

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#17722]
Similar to the discussion in #15616, we've talked about designing iconography to mark notes, warnings, and errors: things like a red lobster for an error/caution, an owl for an advanced tip, and a purple octopus for a note.

This issue will be satisfied when we have icons/illustrations to use in components. The goal should be to introduce a cohesive style that can be used throughout the docs, including for more editorial visual aids.

**Comment by marcysutton** [comment]
I've contacted two artists so far, I'll add more details here when I have them:

- https://burnttoastcreative.com/
- https://ummmheather.com/

**Comment by gillkyle** [comment]
I think once this is finished it would be to nice to do a big sweep through the docs looking for all the permutations of notes and callouts we have and updating ones we can.

We pretty much have every possible permutation of this in the docs somewhere 😅:
```
> Note: Check out xyz... https://github.com/gatsbyjs/gatsby/blob/master/docs/contributing/blog-and-website-contributions.md#L67

**Note**: Check out xyz... https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/adding-tags-and-categories-to-blog-posts.md#L153

Note: Check out xyz... https://github.com/gatsbyjs/gatsby/blob/master/docs/contributing/blog-and-website-contributions.md#L15

> **Note**: Check out xyz... https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/mdx/programmatically-creating-pages.md#L25

> Check out xyz... https://github.com/gatsbyjs/gatsby/blob/master/docs/tutorial/part-three/index.md#L71

_**Note**: Check out xyz..._ https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/adding-app-and-website-functionality.md#L46
```

The link after the example is where it shows up somewhere. Would be nice to make this all a little more consistent with these callouts.

**Comment by shrey-sachdeva2000** [comment]
Hi! I'm a designer and I can solve this issue. Where exactly shall these icons be used and what style of icons/illustration are you looking for?

**Comment by marcysutton** [comment]
An update: This is in progress now, as we have hired a contract illustrator. Once we have the artwork, we can close this issue and move to implementation of adding them to the docs.
