### ISSUE TITLE
Error: useStaticQuery produces consistent Error.

### ISSUE THREAD

**Issue by rGustave07** [gatsbyjs/gatsby#17721]
## Description

Whenever I create a new project using npx gatsby new, the useStaticQuery hook does not function at all. An error is produced every single time for any query.

### Steps to reproduce

create project with npx gatsby new, implement useStaticQuery.

### Expected result

Expected data back from graphQL

### Actual result

Error: The result of this Static Query could not be fetched. This is likely a bug in Gatsby and if refreshing the page does not fix it please open an issue.

### Environment

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.3.2 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.6.3 - C:\Users\Ritter\Anaconda3\python.EXE
  Browsers:
    Edge: 44.18362.329.0
  npmPackages:
    gatsby: ^2.15.17 => 2.15.17 
    gatsby-image: ^2.2.19 => 2.2.19 
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7 
    gatsby-plugin-sass: ^2.1.14 => 2.1.14 
    gatsby-plugin-sharp: ^2.2.22 => 2.2.22 
    gatsby-plugin-typescript: ^2.1.8 => 2.1.8 
    gatsby-source-filesystem: ^2.1.22 => 2.1.22 
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14

**Comment by thomascorthouts** [comment]
Could you share an example project where you encountered the issue?

**Comment by LekoArts** [comment]
In addition to that:

I'd also advise to use the Gatsby CLI instead of npx: https://www.gatsbyjs.org/docs/gatsby-cli/

**Comment by cpboyd** [comment]
I was seeing a similar error when using `useStaticQuery` multiple times within a single file.

If you're doing the same, have you tried splitting the calls into separate files?

**Comment by rGustave07** [comment]
For me, this issue was fixed by moving the folder holding my custom hooks into the src folder.
