### ISSUE TITLE
Jason is no longer the contact for swag

### ISSUE THREAD

**Issue by anthonygilbertt** [gatsbyjs/gatsby#17736]
## Description

On https://www.gatsbyjs.org/contributing/contributor-swag/  it tells you to contact Jason, whom no longer works for Gatsby. This needs to be updated.

### Steps to reproduce

Visit https://www.gatsbyjs.org/contributing/contributor-swag/  and you see that his email address is still on this page. 

### Expected result

The user should not see an email address for someone who no longer works for gatsby.

### Actual result

According to Marcy Sutton, the email address that the user should see is marketing@gatsbyjs.com

### Environment

I used the online dev env that is provided in the docs.

**Comment by ARXChrono** [comment]
Could I take this?

**Comment by ARXChrono** [comment]
Let me know if this above looks good to you

**Comment by LekoArts** [comment]
Closed by #17741
