### ISSUE TITLE
`Gatsby-plugin-offline` Can't connect to site.

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#17749]
This occure after upgrade gatsby version or gatsby-plugin-offline. 

pure installation: 

https://github.com/bjatwork/gatsbyreproduce

Steps to reproduce: 
1. I install page on serwer with ssl
2. Open page on mobile (chrome) 
3. Save page as PWA 
4. Disable internet connection on mobile 
5. Try open PWA from dekstop 
6. I get "Can't connect to site'

**Comment by bjatwork** [comment]
What i observe after many tests on different mobiles: 

1. gatsby plugin offline 2.2.4:  
- when i lunch PWA from dekstop with no internet connection sometimes works sometimes not
- when i lunch page on mobile chrome (not from dektop) with no innternet connection this usualy works good

2. gatsby plugin offline 3:  
- when i lunch PWA from dekstop with no interent connection usually do not work 
- when i lunch page in chrome (not from desktop) with no innternet connection this usualy not works

**Comment by alampros** [comment]
This can be reproduced on the gatsby site itself (https://www.gatsbyjs.org/).

## Gatsby Site
1. Load the page online https://www.gatsbyjs.org/
1. Open devtools and go offline
1. Reload the page
1. Browser pukes 🤮

![Screen Shot 2019-09-24 at 9 11 52 AM](https://user-images.githubusercontent.com/297461/65514783-00c28500-deac-11e9-9132-d505ec2f1151.png)

## Workbox Site
Meanwhile, on a page that implements the service worker correctly...
1. Load the page online: https://developers.google.com/web/tools/workbox
1. Open devtools and go offline
1. Reload the page
1. Continue with your life

![Screen Shot 2019-09-24 at 9 14 08 AM](https://user-images.githubusercontent.com/297461/65514859-23ed3480-deac-11e9-93c5-a3d35f42d5bb.png)

**Comment by alampros** [comment]
I've found that referencing all routes with their full (trailing slash included) pathname got this working for me. For example, instead of `<Link to="/signin">`, using `<Link to="/signin/">`. Had to change it everywhere also – including client-only routes.

**Comment by bjatwork** [comment]
No changes for me 3.x do not works. 
In console i have no errors. 
Gatsby.org - this problems occurred as well.

**Comment by davidbailey00** [comment]
Hi everyone!

I've had a look at this and not quite sure what's going wrong in the examples, but it seems that if you update your version of Gatsby and `gatsby-plugin-offline` to the latest, then your sites should work offline again, leading me to believe there's some sort of version incompatibility going on.

This is also the issue with `gatsbyjs.org` - we are using offline v2, while upgrading to v3 and the latest Gatsby seems to fix this issue.

Closing for now - please reopen if this is still an issue.

**Comment by jvdsande** [comment]
![Screenshot_20191005-103217__01](https://user-images.githubusercontent.com/12484011/66252402-8d4a2e80-e75b-11e9-8f25-eee435f47b10.jpg)

Updated all my Gatsby dev to the latest yesterday, today I'm getting this on the app when offline. 

If the PWA was running in the background, I can reopen it just fine and everything works inside (no broken navigation). But if I kill the PWA from my phone recents menu (Android), then the initial load fails. 
Can this have something to do with the initial route setting? My initial route is the default, `/`. 

Here is the relevant package.json excerpt : 
```
"gatsby": "^2.15.28",
"gatsby-plugin-manifest": "^2.2.20",
"gatsby-plugin-offline": "^3.0.11",
```

I'm using the default plugin options.

**Comment by obedparla** [comment]
I'm having the same issue with 

```
    "gatsby": "^2.18.17",
    "gatsby-plugin-manifest": "^2.2.34",
"gatsby-plugin-offline": "^3.0.11",
```

All of which are the latest versions of all projects right now :/

**Comment by RahmiTufanoglu** [comment]
Same issue with:
"gatsby": "^2.20.26",
"gatsby-plugin-manifest": "^2.2.47",
"gatsby-plugin-offline": "^3.0.40"

**Comment by marcysutton** [comment]
Hey folks, sounds like this issue should be reopened, so I'll do that for the team to look into. Thanks for your comments with versions, that will help–and the team may ask for more details.

**Comment by LekoArts** [comment]
Please open a new issue following our issue template (providing a reproducible reproduction!) as reviving this old issue without reproductions won't cut it. Thanks!
