### ISSUE TITLE
[Question] Ghost plugin source filtering

### ISSUE THREAD

**Issue by nosuchip** [gatsbyjs/gatsby#17743]
## Summary

I am using plugin `gatsby-source-ghost` without any issues but now found I need to introduce some filtering. This plugin provides all posts from Ghost under `allGhostPost` GraphQL node that used across multiple pages to query featured posts, posts for author page, search and so on. I want to filter this collection based on tags i.e. if some tag exits (for example -started with `#sometag:` - article with this tag should appears only if corresponding environment  variable at build time set. If no such tag exists on article - in include in any build despite of environment variables set.

Example:
- article1 has tags `longread`, `level:average`, `#site:site1`
- article2 has tags `tech`, `level:beginner`

When building like `SITE=site1 gatsby build` both articles appears. If building like `gatsby build` - only second articles appear in all posts collection, featured and author's posts.

I cannot do that using `filter` - it is easy to get posts with some string but unable to get other posts - without such tag at all.

I suppose should be some callback similar to onPreBuild when data already sourced but still can be filtered somehow to use across all GQL queries already filtered collection (now I am filtering it in 4 places so it is not good).

**Comment by universse** [comment]
Would something like this work for you?

```js
  const { data } = await graphql(
    `
      {
        allGhostPost {
          edges {
            node {
              id
              tags
            }
          }
        }
      }
    `
  )

  let filteredPosts

  if (!process.env.SITE) {
    // if no SITE env, only include posts with no #site tag
    filteredPosts = data.allGhostPost.edges.filter(({ node }) => {
      const hasSiteTag = node.tags.some(tag => tag.startsWith('#site'))
      return !hasSiteTag
    })
  } else {
    filteredPosts = data.allGhostPost.edges.filter(({ node }) => {
       const siteTag = node.tags.find(tag => tag.startsWith('#site'))
       
       // always include post with no #site tag
       if (!siteTag) return true

      // for posts that include #site tag
      const [, site] = siteTag.split(':')
      return site === process.env.SITE
    })
  }

  filteredPost.forEach(() => {
    // createPages
  })
```

**Comment by nosuchip** [comment]
@universse thank you for response. This is exact approach I am using right now. But unfortunately if has number of side-effects. For instance, on component that display featured posts also defined GQL query and it read from `allGhostPost` source. Also on author's page I need to inject same code call to filter out posts not belonging to specific site. And finally - I adding search (using Algolia but other search methods affected by this too) and it build index based on [queried posts](https://www.gatsbyjs.org/docs/adding-search-with-algolia/#adding-a-search-interface-to-your-site) which uses same data source - `allGhostPost` .

Also, posts filtered out this way doesn't give 404 on direct url (as Gatsby still handles it), but empty page.

You see, I need put many patches in many places instead of put it into one place - where Gatsby chose what data use and what - do not.

**Comment by universse** [comment]
Ah I understand your use cases better now.

I would suggest you use gatsby's [onCreateNode API](https://www.gatsbyjs.org/docs/node-apis/#onCreateNode) and [deleteNode](https://www.gatsbyjs.org/docs/actions/#deleteNode)

```js
exports.onCreateNode = ({ node, actions: { deleteNode }) => {
  if (node.internal.type !== 'GhostPost') return

  const siteTag = node.tags.find(tag => tag.startsWith('#site'))

  if (!siteTag) return
  
  const [, site] = siteTag.split(':')

  site !== process.env.SITE && deleteNode({ node })
}
```

Basically, this delete all nodes not belong to site set by environment variable.

**Comment by nosuchip** [comment]
@universse wow! That is exactly I looked for, thank you.

**Comment by nosuchip** [comment]
Final note about Ghost sourcing: it looks like `onCreteNode` will not help here because posts, tags an authors retrieved asynchronously and each post contains only kinda ghost ID of tag that looks like `Ghost_Tag_<TAG_UUID>`. I.e. does not contains tag name. And tags retrieved after posts sometimes. So for now there is no good way to filter post by tags unless hardcode TAG ID and filter by it.

**Comment by universse** [comment]
Could you try this? The logic is a bit convoluted unfortunately.

```js
exports.onCreateNode = async ({ node, cache }) => {
  if (node.internal.type !== 'GhostTag') return
  if (!node.name.startsWith('#site')) return

  const [, site] = node.name.split(':')
  if (site === process.env.SITE) return

  const siteTags =  await cache.get('TAG_IDS_TO_EXCLUDE')

  if (siteTags) {
    siteTags[node.id] = true
    await cache.set('TAG_IDS_TO_EXCLUDE', siteTags)
  } else {
    await cache.set('TAG_IDS_TO_EXCLUDE', { [node.id]: true })
  }
}

exports.createResolvers = async ({ createResolvers, cache }) => {
  const tagIdsToExclude = await cache.get('TAG_IDS_TO_EXCLUDE')

  createResolvers({
    Query: {
      filteredGhostPost: {
        type: ['GhostPost'],
        resolve: (source, args, context, info) => {
          const posts = context.nodeModel.getAllNodes({ type: 'GhostPost' })
          const filteredPosts = posts.filter(
            post => !post.tags.some(tagId => tagIdsToExclude[tagId])
          )
          return filteredPosts
        }
      }
    }
  })
}
```
