### ISSUE TITLE
Site display blank page on Windows on IE and Edge

### ISSUE THREAD

**Issue by skrapkam** [gatsbyjs/gatsby#17754]
## Description

My Gatsby site currently works on Mac for all browsers but not for IE and Edge on Windows. On Windows it'll just briefly show the page for less than a second and then display nothing. When I open the console it lists `<div id="___gatsby"></div>` with nothing inside the divs.  

### Steps to reproduce

You can see this in [Browersling](https://www.browserling.com/browse/win/7/ie/11/http%3A%2F%2Fsamchang.design)

The website is: https://samchang.design
You can find the repo here: https://github.com/skrapkam/samchang

### Expected result

Website should display everything. 

### Actual result

Website is not being displayed. 

### Environment

**
  System:
    OS: macOS 10.14.6
    CPU: x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 65.0.1
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.67 => 2.15.14 
    gatsby-image: ^2.2.3 => 2.2.18 
    gatsby-plugin-catch-links: ^2.1.0 => 2.1.9 
    gatsby-plugin-emotion: ^4.1.0 => 4.1.2 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-google-analytics: ^2.1.1 => 2.1.16 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.2.0 => 2.2.16 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.7 
    gatsby-plugin-sharp: ^2.2.1 => 2.2.7 
    gatsby-remark-copy-linked-files: ^2.1.0 => 2.1.3 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-figure-caption: ^2.0.0 => 2.0.0 
    gatsby-remark-images: ^3.1.12 => 3.1.12 
    gatsby-remark-images-medium-zoom: ^1.2.1 => 1.2.1 
    gatsby-source-filesystem: ^2.1.1 => 2.1.5 
    gatsby-source-prismic: ^2.2.0 => 2.2.0 
    gatsby-transformer-remark: ^2.6.19 => 2.6.19 
    gatsby-transformer-sharp: ^2.2.0 => 2.2.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.3
**

**Comment by LekoArts** [comment]
Are you testing this on a local machine you have? Or via the website you linked. Sadly I can't test this myself on my windows machine right now.

**Comment by jonniebigodes** [comment]
@LekoArts and @skrapkam i've tested on my machine and the problem persists, when i open the site it shows me the following error on the console.
![sam_chang_1](https://user-images.githubusercontent.com/22988955/65328078-5b5a9900-dbad-11e9-86d6-4da05b538737.png)

I haven't gone over the code itself as i'm trying to triage another issue.

**Comment by skrapkam** [comment]
> Are you testing this on a local machine you have? Or via the website you linked. Sadly I can't test this myself on my windows machine right now.

Tested this at the Microsoft store and the website I linked haha. Unfortunately, I don't have a windows machine.

**Comment by skrapkam** [comment]
> @LekoArts and @skrapkam i've tested on my machine and the problem persists, when i open the site it shows me the following error on the console.
> ![sam_chang_1](https://user-images.githubusercontent.com/22988955/65328078-5b5a9900-dbad-11e9-86d6-4da05b538737.png)
> 
> I haven't gone over the code itself as i'm trying to triage another issue.

Ah thanks, haven't seen that error in the console yet. Will look into it.

**Comment by moonmeister** [comment]
@skrapkam Babel and core-js, which Gatsby uses to compile modern JavaScript to be compatible cross browsers only compile JavaScript. Not Browser APIs you can access from JavaScript. MDN notes [PerformanceObserver](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver) is a browser API and not supported by Edge/IE. You'll need to manually polyfill that if possible or not use it when it's not available. Checkout: https://github.com/fastly/performance-observer-polyfill

**Comment by skrapkam** [comment]
@moonmeister Great, thanks for that. I'm trying to use the performance-observer-polyfill but am having no luck. Any resources you can point to that uses Gatsby with this?

**Comment by moonmeister** [comment]
As long as it's imported on the component(or any where in your app) it should work. Also, any react example should apply.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by skrapkam** [comment]
@moonmeister  Cool thanks. I later realized that it was a plugin causing this issue so just removed it from my project. Works now!

**Comment by me4502** [comment]
@skrapkam Which plugin was causing the issue for you? I've just been reported it on a site that only uses a small number of the official Gatsby plugins :/

**Comment by Mrazator** [comment]
@me4502 In ma case `gatsby-remark-images-medium-zoom` is causing this issue. However, I successfully made a polyfill for PerformanceObserver, but now getting this error.

![Capture](https://user-images.githubusercontent.com/20387666/69612261-a4a4ea00-102f-11ea-94b5-90b1f921bec9.PNG)

 I tried to add `babel-polyfill` as suggested here: https://github.com/gatsbyjs/gatsby/issues/7169, but with no luck.
