### ISSUE TITLE
Getting "Error: spawn ENOMEM" on gatsby build and gatsby develop

### ISSUE THREAD

**Issue by haertner** [gatsbyjs/gatsby#17757]
## Description

After `npm i` and `gatsby develop` I am getting this error.

> Something went wrong installing the "sharp" module
> 
> Cannot find module '../build/Release/sharp.node'
> 
> - Remove the "node_modules/sharp" directory, run "npm install" and look for errors
> - Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
> - Search for this error at https://github.com/lovell/sharp/issues

After following the first solution and after executing gatsby build or gatsby start I am getting the ENOMEM error.

### Steps to reproduce

At first I tried it with my private Repository. But It also happens on the starter example site from gatsby. On my local windows maschine everything works. If I try to install and start it on the server (debian 10) I am getting the errors. I am using a 5$ Digitalocean Droplet.

### Expected result

Build normally

### Actual result

``` ERROR 

UNHANDLED REJECTION spawn ENOMEM

  Error: spawn ENOMEM
  
  - child_process.js:366 ChildProcess.spawn
    internal/child_process.js:366:11
  
  - index.js:204 module.exports
    [siteFolder]/[imagemin-pngquant]/[execa]/index.js:204:26
  
  - index.js:52 input
    [siteFolder]/[imagemin-pngquant]/index.js:52:13
  
  - index.js:71 Function.module.exports.buffer
    [siteFolder]/[imagemin]/index.js:71:31
  
  - process-file.js:198 pipeline.toBuffer.then.sharpBuffer
    [siteFolder]/[gatsby-plugin-sharp]/process-file.js:198:105
  

⠙ run static queries
[====                        ]   0.569 s 1/6 17% Generating image thumbnails
npm ERR! code ELIFECYCLE
```

### Environment

```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^2.15.18 => 2.15.18
    gatsby-image: ^2.2.19 => 2.2.19
    gatsby-plugin-manifest: ^2.2.17 => 2.2.17
    gatsby-plugin-offline: ^3.0.7 => 3.0.7
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7
    gatsby-plugin-sharp: ^2.2.24 => 2.2.24
    gatsby-source-filesystem: ^2.1.24 => 2.1.24
    gatsby-transformer-sharp: ^2.2.15 => 2.2.15
  npmGlobalPackages:
    gatsby-cli: 2.7.48
```

**Comment by LekoArts** [comment]
Please make sure that your droplet is configured correctly and can install/build sharp: http://sharp.pixelplumbing.com/en/stable/install/

**Comment by willi-dev** [comment]
i also face this issue when using digital ocean $5 droplet

**Comment by waltercruz** [comment]
Have you guys tried enabling some swap space on your droplets? 

gatsby seems to be very memory intensive on buidling

**Comment by willi-dev** [comment]
@waltercruz i did it 3 days ago and it works ! :smile:

**Comment by brettinternet** [comment]
Increasing resources also helped my CI/CD build. I had a different error, but the issue appears to be similar (especially since OP's build stalled at `Generating image thumbnails`):

```sh
success Generating image thumbnails — 105/105 - 18.942 s
error #95313  Call retries were exceeded
Building static HTML failed
See our docs page for more info on this error: https://gatsby.dev/debug-html

  Error: Call retries were exceeded

  - ChildProcessWorker.js:193 ChildProcessWorker.initialize
    [app]/[jest-worker]/build/workers/ChildProcessWorker.js:193:21
  - ChildProcessWorker.js:263 ChildProcessWorker.onExit
    [app]/[jest-worker]/build/workers/ChildProcessWorker.js:263:12
  - child_process.js:248 Process.ChildProcess._handle.onexit
    internal/child_process.js:248:12
```
