### ISSUE TITLE
Change routing to support localizations

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#17759]
## Summary

Make changes to the gatsbyjs.org site's `gatsby-node` to support localized routes.

## Details

A lot of implementation details can be taken from the [using-i18n](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-i18n) example by @LekoArts .

### Step 1

For the first step, we need to reroute all English docs to a localized `/en` path:

* Move translate-able routes (currently /docs, /tutorial, and /contributing) under an `en/` route (e.g. `/en/docs/quick-start`)
* Redirect `/docs/[page]` to `/en/docs/[page]` (same for tutorials and contributing)
* Make a [`LocalizedLink`](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-i18n/src/components/localizedLink.js) component so that links in markdown to localized files are always routed to the localized URL.

### Step 2

Once we are able to [pull in language repos](#19353), we can then proceed to display those localized pages based on the language code:

* Update `gatsby-node` to create pages for each localized markdown file
* Decide on a strategy for dealing with non-localized pages
* Update `LocalizedLink` to keep links in the current language

## Unresolved Questions

* There are a number of redirects from translate-able pages to other translate-able pages (e.g. `/docs/community/` to `/contributing/community/`). How should we deal with these when all pages are being redirected to `/en`?

**Comment by nutboltu** [comment]
@tesseralis I would like to work on this issue

**Comment by tesseralis** [comment]
@nutboltu thanks for the offer, but I think this is something I need to handle myself!

**Comment by nutboltu** [comment]
@tesseralis Cheers!. Just curious if there's any ticket I can tackle regarding translation docs.

**Comment by tesseralis** [comment]
Actually... @nuboltu if you want to take a shot at this, be my guest. The barrier I ran into was that the source takes so long to build that it was difficult to iterate on and it made more sense for me to wait until the core team made improvements to it. I'm focused more on setting up the translation workflow now, but if you want to try your hand, go ahead!

**Comment by nutboltu** [comment]
Thanks, @tesseralis I'll take a look 😄

**Comment by krpeacock** [comment]
Looking forward to seeing how this goes! I've got an MDX project that would benefit from this work once it's ready

**Comment by tesseralis** [comment]
Fiexed as of #20637
