### ISSUE TITLE
Chore(doc): doc about using different online IDE for Gatsby

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#17764]
## Summary

Create docs about using different online IDE for Gatsby

### Motivation

Since there is gitpod and also CodeSandbox and maybe other with Gatsby support:

Maybe we make also an doc about using different online IDE for Gatsby. 

This doc can also linked from the tutorial for students that they can jump to the tutorials without installing additional software. Maybe for some students the installing process (see https://www.gatsbyjs.org/tutorial/part-zero/) is a way too much. 

#### Online

- codesandbox
- gitpod
- glitch
- others?

#### apps

- VS Code
- Intellij IDEA or Webstorm
- Atom
- others?

### related

#17718

**Comment by jonniebigodes** [comment]
You mean setup a codesandbox codesandbox and Gitpod and possibly Glitch? And why not update link this future document to [make a reproducible test case](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)? Possibly informing that you have more options than just use a codesandbox or a github one?

**Comment by muescha** [comment]
Ah. You find the gem where codesandbox was described :) I did not found this place. 

But I would like to have a general point in the docs and maybe as option to skip this: https://www.gatsbyjs.org/tutorial/part-zero/

**Comment by muescha** [comment]
I was for sure there was also a section for IDE and Gatsby (VS Code / Intellij IDEA or Webatoem / others) but I can not find them :(

**Comment by jonniebigodes** [comment]
For intellij IDEA there's already some [documentation](https://www.jetbrains.com/help/idea/react.html), probably tweaking it a bit and make it compliant with Gatsby. Same as with webstorm it also as some [documentation](https://www.jetbrains.com/help/webstorm/react.html). One thing that comes to mind is regarding intellij they have some restrictions and it should be nice to include that it would be only available for the ultimate version. Based on their description.

**Comment by muescha** [comment]
I think this should be available in the gastby docs and not external.

**Comment by muescha** [comment]
Since @marcysutton moved this issue to `parking lot` I removed the `not stale`... is this ok?

**Comment by LekoArts** [comment]
I'll close this as all editors will work the same with Gatsby as with other React codebase, the online editors itself mostly have direct integrations now so that it's not necessary for us to explain a setup (as it's non-existent).
