### ISSUE TITLE
gatsby cli develop & build just returning help information

### ISSUE THREAD

**Issue by dougajmcdonald** [gatsbyjs/gatsby#1777]
I was recently using gatsby to develop a new site, but when running:

`gatsby develop` or `gatsby build` today I just get the following output:

```
c:\github\gatsby-blog>gatsby build

  Usage:  [command] [options]


  Options:

    -V, --version  output the version number
    -h, --help     output usage information


  Commands:

    new [rootPath] [starter]  Create new Gatsby project.
To show subcommand help:

    gatsby [command] -h
```

I can't see anything wrong with my config / packages etc and the fact it outputs the help suggest things are installed. 

Does anyone have any ideas?

**Comment by KyleAMathews** [comment]
Version of gatsby/gatsby-cli?

**Comment by dougajmcdonald** [comment]
I'm on:

`"gatsby-cli": "^1.0.8"`

and

`"gatsby": "^1.6.6"`

I tried updating to `"gatsby": "^1.8.3"` but I'm seeing the same thing

**Comment by KyleAMathews** [comment]
Can you reproduce this on a new Gatsby site? `gatsby new test-site`.

**Comment by dougajmcdonald** [comment]
Hmm, interestingly no. A `gatsby new <some-site>` and then `gatsby build` works.

The only thing I did was merge in some files from my work machine, which was possibly on a different npm/node version.

Any thoughts on the best way to debug things at this level? 

The repo is here if it's easier to cast and eye: https://github.com/dougajmcdonald/gatsby-blog

**Comment by KyleAMathews** [comment]
Thanks for checking.

It's almost certainly something is wrong with your package.json file. We try to require your site's package.json and then if we can't, we assume you're not in a site. But if there's a syntax problem in the file it'll fail. Gatsby should check for syntax errors in the catch and print those out. Feel free to verify this is the problem and submit a PR with the above change if you'd like.

https://github.com/gatsbyjs/gatsby/blob/562d58ec3791ef1d2aee364f1dd756b909cd142f/packages/gatsby-cli/src/index.js#L18

**Comment by dougajmcdonald** [comment]
Gah, so sorry, just checked my commits, I moved gatsby from `dependencies` to `devDependencies` as I needed it there for my Azure kudu build, I put it back, `npm i`'d and it now works, sorry for wasting you time
