### ISSUE TITLE
Move translateable text in home page to `data/`

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#17780]
## Summary

Move all text strings strewn throughout `www/pages/index.js` and its components to various markdown/YAML files in `data/` so that they can be marked for translation.

Part of #17758.

### Motivation

The home page is the first place that visitors to gatsbyjs.org see and it is imperative that it can be translated so that non-English speakers can get an overview of it in their language.

**Comment by mendaomn** [comment]
Would love to help with this. As it would be my first contribution to the project, is there any example or previous commit that I can look at to better understand what should be done?

**Comment by tesseralis** [comment]
Hi @mendaomn! This might be hard as a first contribution since the home page touches a lot of different queries and components. What about this? https://github.com/gatsbyjs/gatsby/issues/17989

**Comment by tesseralis** [comment]
Closing bc this isn't really a good way to break up this section
