### ISSUE TITLE
Javascript in feed

### ISSUE THREAD

**Issue by GuillaumeAmat** [gatsbyjs/gatsby#17796]
## Summary

Hello there!

I just built a blog, based on `gatsby-theme-blog`. I added `gatsby-plugin-feed`, which creates the xml file with the right entries, but their body is full of javascript... FreshRSS is unable to reed it for instance.

Is that on purpose or did I miss something?

Thank you for your help!

## Relevant information

Nothing fancy, I just followed the READMEs and that article: https://www.gatsbyjs.org/docs/adding-an-rss-feed/

### Environment (if relevant)

```
  System:
    OS: Linux 5.2 Fedora 30 (Workstation Edition) 30 (Workstation Edition)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /tmp/yarn--1569089059791-0.272997194949242/node
    Yarn: 1.17.3 - /tmp/yarn--1569089059791-0.272997194949242/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 69.0.1
  npmPackages:
    gatsby: ^2.15.16 => 2.15.16 
    gatsby-plugin-feed: ^2.3.12 => 2.3.12 
    gatsby-remark-images: ^3.1.22 => 3.1.22 
    gatsby-theme-blog: ^1.2.1 => 1.2.1 
```

### File contents (if changed)

`gatsby-config.js`: https://gitlab.com/GuillaumeAmat/devlog/blob/c5c10ed74ff327b4b36ee6fb620f088913df9836/gatsby-config.js
`package.json`: https://gitlab.com/GuillaumeAmat/devlog/blob/c5c10ed74ff327b4b36ee6fb620f088913df9836/package.json
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 

The whole project: https://gitlab.com/GuillaumeAmat/devlog/tree/c5c10ed74ff327b4b36ee6fb620f088913df9836

**Comment by jonniebigodes** [comment]
@GuillaumeAmat i've picked up on your issue and i think i have a solution for your issue.

Here are the steps i took to triage your issue.
- Cloned your repo.
- Installed the dependencies.
- Issued `gatsby build && gatsby serve` to generate a production build and emulate the page as it was being hosted in a production server and i was able to confirm your issue.

 What is actually happening with the use of `body` field is that what you're seeing is actually the content that will be supplied to the `MDXRenderer ` component and be interpreted by it and displayed. In a nutshell the body is the mdx content transformed into a component so that it can be shown. More on that [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx#mdxrenderer).

With that in mind i made some changes to your code. 

-Started by modifying `gatsby-config.js` to the following, i'm leaving your configuration commented out:
```js
const siteMetadata = {
  siteUrl: "https://devlog.amat.io",
  title: "Amat's devlog",
  description: "Dev articles and useful feedback from daily coding",
  author: "Guillaume AMAT",
  social: [
    {
      name: "Twitter",
      url: "https://twitter.com/guillaume_amat",
    },
    {
      name: "Gitlab",
      url: "https://gitlab.com/GuillaumeAmat",
    },
    {
      name: "Github",
      url: "https://github.com/GuillaumeAmat",
    },
    {
      name: "LinkedIn",
      url: "https://www.linkedin.com/in/guillaume-amat-39a234100/",
    },
  ],
}

module.exports = {
  siteMetadata,
  plugins: [
    {
      resolve: "gatsby-theme-blog",
      options: {},
    },
    "gatsby-remark-images",
    {
      resolve: "gatsby-plugin-feed",
      options: {
        query: `
          {
            site {
              siteMetadata {
                title
                description
                siteUrl
                site_url: siteUrl
              }
            }
          }
        `,
        feeds: [
          {
            serialize: ({ query: { site, blogposts, mdxContent } }) => {
              

              /*  return allMdxBlogPost.edges.map(edge => {
                return Object.assign({}, edge.node, {
                  description: edge.node.excerpt,
                  date: edge.node.date,
                  url: site.siteMetadata.siteUrl + edge.node.slug,
                  guid: site.siteMetadata.siteUrl + edge.node.slug,
                  custom_elements: [{ "content:encoded": edge.node.body }],
                })
              }) */
              return mdxContent.edges.map(edge => {
                const contentSlug = blogposts.edges.find(
                  x => x.node.title === edge.node.frontmatter.title
                )
                return Object.assign({}, edge.node, {
                  description: edge.node.excerpt,
                  date: edge.node.frontmatter.date,
                  url: site.siteMetadata.siteUrl + contentSlug.node.slug,
                  guid: site.siteMetadata.siteUrl + contentSlug.node.slug,
                  custom_elements: [{ "content:encoded": edge.node.rawBody }],
                })
              })
            },
            /* query: `
              {
                allMdxBlogPost(
                  sort: { order: DESC, fields: [date] },
                ) {
                  edges {
                    node {
                      excerpt
                      body
                      slug
                      title
                      date
                    }
                  }
                }
              }
            `, */
            query: `
            {
              blogposts: allMdxBlogPost(sort: {order: DESC, fields: [date]}) {
                edges {
                  node {
                    slug
                    title
                  }
                }
              }
              mdxContent: allMdx(sort: {order: DESC, fields: [frontmatter___date]}) {
                edges {
                  node {
                    excerpt
                    rawBody
                    frontmatter {
                      date
                      title
                    }
                  }
                }
              }
            }
            
            `,
            output: "/rss.xml",
            title: siteMetadata.title,
          },
        ],
      },
    },
  ],
}
```
What is happening with this change, i'm aliasing the graphql queries so that i can get some information that is required and  show the rss feed in a more readable fashion. `allMdxBlogPost` will be used only to fetch the `slug` field that is required to show the links correctly and the `title` field as a means of comparison. The actual data will be retrieved from `allMdx`. 
- Issued `gatsby clean && gatsby build && gatsby serve` to purge the cached data and generate a production build and emulate the production server. I opened up `http://localhost:9000/rss.xml` and i'm presented with the following:
![GuillaumeAmat](https://user-images.githubusercontent.com/22988955/65394875-bd242a00-dd8a-11e9-8184-41c47984f8fb.png)

As you can see the content is now shown, and not the js. 

Feel free to provide feedback so that we can close this issue or continue to work on it until we find one.

**Comment by GuillaumeAmat** [comment]
Hi @jonniebigodes, thank you very much for your time and detailed help.

The output is better but it still contains some unwanted things. Take a close look at the start of `content:encoded` content. There are `title`, `date` and an `import`.

In the GraphQL query I tried to replace `rawbody` by `html` but it gives me an error...

**Comment by jonniebigodes** [comment]
the `html` field typically used for this type of scenario, for rss feeds if i'm not mistaken. If you use it graphiql it will throw a error. Modifying your `gatsby-config.js` to the following:
```js
{
      resolve: "gatsby-plugin-feed",
      options: {
        query: `
          {
            site {
              siteMetadata {
                title
                description
                siteUrl
                site_url: siteUrl
              }
            }
          }
        `,
        feeds: [
          {
            serialize: ({ query: { site, blogposts, mdxContent } }) => {
              return mdxContent.edges.map(edge => {
                const contentSlug = blogposts.edges.find(
                  x => x.node.title === edge.node.frontmatter.title
                )
                return Object.assign({}, edge.node, {
                  description: edge.node.excerpt,
                  date: edge.node.frontmatter.date,
                  url: site.siteMetadata.siteUrl + contentSlug.node.slug,
                  guid: site.siteMetadata.siteUrl + contentSlug.node.slug,
                  custom_elements: [{ "content:encoded": edge.node.html }]
                })
              })
            },
            query: `
            {
              blogposts: allMdxBlogPost(sort: {order: DESC, fields: [date]}) {
                edges {
                  node {
                    slug
                    title
                  }
                }
              }
              mdxContent: allMdx(sort: {order: DESC, fields: [frontmatter___date]}) {
                edges {
                  node {
                    excerpt
                    html
                    frontmatter {
                      date
                      title
                    }
                  }
                }
              }
            }
            `,
            output: "/rss.xml",
            title: siteMetadata.title,
          },
        ],
      },
    },
```
And running `gatsby build && gatsby serve` and then opening up a browser window to: `http://localhost:9000/rss.xml` will output the following:
![GuillaumeAmat_2](https://user-images.githubusercontent.com/22988955/65419055-ba125380-ddf5-11e9-8187-b4673cafe9c8.png)

The content is parsed into html and added. To make it more readable you probably have make use of  some other form of tooling. Probably someone more knowledgeable could help you on how to do it.

**Comment by GuillaumeAmat** [comment]
> If you use it graphiql it will throw a error.

That's the one I had. But I did not test in a build :/

Your sample misses the `title` attribute but it works like a charm thank you!

**Comment by jonniebigodes** [comment]
@GuillaumeAmat no need to thank, glad that i was able to help.
