### ISSUE TITLE
[cli] Running an unknown command doesn't show the help section

### ISSUE THREAD

**Issue by tleunen** [gatsbyjs/gatsby#178]
Running the cli with an unknown command displays nothing, but it should display the help. Otherwise we don't really know if the cli actually run something or not.

**Comment by KyleAMathews** [comment]
Good catch. Fixed this in https://github.com/gatsbyjs/gatsby/commit/938d9f07b79365cd07b13ff6f3d32621b51a1064

I'll publish a new release real quick.
