### ISSUE TITLE
Access fields created by setFieldsOnGraphQLNodeType on node returned by getNodyById method

### ISSUE THREAD

**Issue by Wolfsun** [gatsbyjs/gatsby#17809]
## Summary

Access fields created by setFieldsOnGraphQLNodeType on node returned by getNodeById method.

## Relevant information

I'm trying to add a custom resolver using createResolvers to a field on a custom node type created with the createTypes action in sourceNodes. The custom resolver needs to access another field on the custom node type that references an ImageSharp node. This all works fine, however the getNodeById method returns the ImageSharp node without the methods added by gatsby-transformer-sharp e.g. fixed and fluid. Is there any way to access these methods as I need to return the processed image from my custom resolver? Thanks!

### Environment (if relevant)

System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 69.0
  npmPackages:
    gatsby: ^2.15.14 => 2.15.14
    gatsby-image: ^2.2.18 => 2.2.18
    gatsby-plugin-emotion: ^4.1.6 => 4.1.6
    gatsby-plugin-sharp: ^2.2.21 => 2.2.21
    gatsby-plugin-typography: ^2.3.7 => 2.3.7
    gatsby-source-filesystem: ^2.1.22 => 2.1.22
    gatsby-transformer-json: ^2.2.8 => 2.2.8
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14
  npmGlobalPackages:
    gatsby-cli: 2.7.47

**Comment by LekoArts** [comment]
Can you please explain your question in more detail, possibly with your current code? It's hard to help you without seeing that :) Thanks!

**Comment by Wolfsun** [comment]
Please reopen this issue.

**Comment by LekoArts** [comment]
cc @vladar @freiksenet

**Comment by vladar** [comment]
Hey, this is a bit tricky!

`ImageSharp` fields `fluid`, `fixed` and others are not a part of the **node** model. Those fields only exist in the graphql schema. They have their own resolvers that accept exactly the same node (as in your `console.log`) and return the dynamically generated data out of it. 

If the type of your `test` field is `ImageSharp` you can simply return this node from your resolver and it will be passed down to `ImageSharp` and handled correctly.

But if you are trying to do something more complicated inside your resolvers - we need a bit more details on that. In this case, you may end up doing something similar to what `gatsby-transformer-sharp` does in [its resolvers](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/customize-schema.js#L180-L199).

**Comment by Wolfsun** [comment]
Thanks for explaining how this works. I've now taken an alternative approach that is working. Essentially I had a single ImageSharp field, and I wanted to change the aspect ratio of the image returned based on a value in a separate field (I have a custom schema for a json data file I'm using with multiple ObjectTypes). 

The approach I have now taken is to define 3 object types for the image field that share the same interface. Then in my graphql query I set an aspect ratio for each of these 3 ObjectTypes. I can define more ObjectTypes if I need to handle more aspect ratios in future.
