### ISSUE TITLE
upload creator image

### ISSUE THREAD

**Issue by ctrljs** [gatsbyjs/gatsby#17807]
I am trying to upload a creator image for my web development agency , It is showing

" Uploads are disabled.
File uploads require push access to this repository."

How Can I get these rights ?? Because I want enter my creators entry, and there is image atrribute in that .yml , which should point to a image here.

**Comment by LekoArts** [comment]
Thank you for opening this!

Please follow these steps: https://www.gatsbyjs.org/contributing/submit-to-creator-showcase/

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
