### ISSUE TITLE
Accessing siteMetadata (gatsby-config.js)

### ISSUE THREAD

**Issue by kbariotis** [gatsbyjs/gatsby#1781]
I have added a property `siteUrl` in `gatsby-config.js` and I am trying to access it in two places. 

1) `layouts/index.js`: where I need to set OG tags, etc..
2) `templates/blog-post.js`: where I need to set share urls

What's the preferred way to access it in these places?

Thank you! Great work btw! 😎

**Comment by danoc** [comment]
Hi @kbariotis – just ran into this myself and came here to find an answer. 😃 

After poking around I've realized that it can be queried like this:
```
{
  site {
    siteMetadata {
      siteURL
      siteName
    }
  }
}
```

A corresponding `gatsby-config.js` would look like this:
```
module.exports = {
  siteMetadata: {
    siteURL: 'https://danoc.me/',
    siteName: 'Daniel O\'Connor',
  },
};
```

**Comment by kbariotis** [comment]
Thank you @danoc ! Is there a working example?

**Comment by KyleAMathews** [comment]
Search the example sites. We query siteMetadata a number of times.

**Comment by luketeaford** [comment]
I have searched the example sites and don't understand how siteMetadata is used. For example, in the starter site it looks to me like src/layouts/index.js has a hardcoded title. I am working around this like so:
```
import GatsbyConfig from '../../gatsby-config

<Helmet
  title={GatsbyConfig.siteMetadata.title}
```

That feels like it's not what is intended. I also read the migration guide and attempted to export a query as a constant. I get errors that props is not defined.

**Comment by oliverbenns** [comment]
What is the benefit of using graphql for this? I'm also importing like @luketeaford as it's clear and simple, though I'm not sure on the consequences of doing so.

**Comment by KyleAMathews** [comment]
`gatsby-config.js` is used in node so trying to import it into the browser could potentially pull in very large node libraries depending on what else you add to your gatsby-config.js

If you want to import a metadata module, I'd suggest using a different file from gatsby-config.js e.g. `data.yaml` or whatever.

**Comment by Undistraction** [comment]
Got to say I find the docs for this very confusing - in the tutorial you hard-code the title direct from the metadata, but what is really needed is a way to define different metadata for different pages. Last time I checked, using the same title and description across multiple pages is an SEO disaster. Obviously Helmet provides a nice solution for updating meta on the fly but it would make sense to me to offer a mechanism for defining all meta in a separate metadata.json or similar. At the moment I'm adding a `pages` prop on the metadata object in the Gatsby config and declaring per-page meta there. Then I'm fudging it through to the page which uses Helmet to update, but this is a pretty ugly solution.

**Comment by KyleAMathews** [comment]
Closing out older issues — please open a new issue if you need more help!
