### ISSUE TITLE
I want Link to switch pages at a given location, not the entire layout.

### ISSUE THREAD

**Issue by PiccoloYu** [gatsbyjs/gatsby#17818]
I'm doing SPA for my website, and I find that Gatsbyjs'Link routing jump is a jump refresh with the entire layout component. Does Gatsbyjs offer react-router-like'Route'? I want the page to switch pages in the place I specify.
###react-router
![image](https://user-images.githubusercontent.com/44945137/65423392-6d516b80-de3b-11e9-8ca7-314f80cdbc37.png)

###gatsbyjs
![image](https://user-images.githubusercontent.com/44945137/65423468-a25dbe00-de3b-11e9-9af9-c8f086c9fa32.png)

**Comment by jonniebigodes** [comment]
@PiccoloYu gatsby uses @reach/router under the hood to handle all sorts or routing. More on that [here](https://www.gatsbyjs.org/docs/routing/) and [here](https://www.gatsbyjs.org/docs/gatsby-link/). Also take a look at [this](https://www.gatsbyjs.org/docs/layout-components/#how-to-prevent-layout-components-from-unmounting).

**Comment by PiccoloYu** [comment]
I looked at the document carefully and used `gatsby-plugin-layout', but there was a problem of duplicating nested components, T.T.
![image](https://user-images.githubusercontent.com/44945137/65489039-e94fc000-dedc-11e9-8077-aa9e60c8014b.png)
![image](https://user-images.githubusercontent.com/44945137/65489071-f79ddc00-dedc-11e9-9cee-e9e17696b996.png)
![image](https://user-images.githubusercontent.com/44945137/65489656-29637280-dede-11e9-80ef-f773ba00daaf.png)

I think `gatsby-plugin-layout'is another layer of my layout component that automatically wraps up its own layout.

**Comment by wardpeet** [comment]
@PiccoloYu could you share your component project structure and maybe crate a small reproduction?

**Comment by PiccoloYu** [comment]
I found the reason!!! I use `gatsby-plugin-transition-link'for page transitions, which results in a layer of redundant divs leading to duplicate nested components. Maybe [gatsby-plugin-transition-link](https://github.com/gatsbyjs/gatsby/issues/17818) and [gatsby-plugin-layout](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-layout) together will affect the effect.

![2CQN@_7 `H9O4WH%I V)R$Q](https://user-images.githubusercontent.com/44945137/65493042-a09c0500-dee4-11e9-95d3-a0fb968ae574.png)
![MNFVG(71BU$6EK9AT~QWR2T](https://user-images.githubusercontent.com/44945137/65493051-a42f8c00-dee4-11e9-8520-048d63663d19.png)
@jonniebigodes 
@wardpeet 
Thank you very much for your help.  ≧◠◡◠≦✌

**Comment by wardpeet** [comment]
Oh they both use `wrapPageElement` api hook, could you try switching the order in gatsby-config.js?

**Comment by PiccoloYu** [comment]
![1A$9 G{Z0AWTQRO{@I22QA](https://user-images.githubusercontent.com/44945137/65493622-c675d980-dee5-11e9-8dc4-ad4feae0c986.png)

Unfortunately, once `gatsby-plugin-transition-link` is in the front, startup becomes a problem.

![$ODH59~F9 %A_0TQQ 4J9PL](https://user-images.githubusercontent.com/44945137/65493750-0b9a0b80-dee6-11e9-8c28-02e07dc65a38.png)

So I decided to abandon `gatsby-plugin-transition-link'.
