### ISSUE TITLE
Error: RelayParser: Encountered duplicate defintitions for one or more documents

### ISSUE THREAD

**Issue by rgiese** [gatsbyjs/gatsby#17811]
## Description

Same issue as #11688; creating new issue since the previous one was marked as fixed with an attached code change.

Any Gatsby site can fail to build with the following error provided you're building on Windows and your CWD path is using a lower-case drive name:

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
- eReposGrumpyv2GatsbyStarterBlogMdxSrcTemplatesBlogPostJs1876540457
- eReposGrumpyv2GatsbyStarterBlogMdxSrcPagesIndexJs4125737639
```

### Steps to reproduce

- Create a root directory for a new Gatsby site (e.g. `e:\repos\grumpyv2`) and make sure the Windows terminal shows the current path with a lower-case drive letter (clown around with something like `cd /d e:\repos` from a different drive letter to make sure it really is lowercase).

- Clone my sample repo from https://github.com/rgiese/gatsby_issue17811, or just create a new Gatsby site that has a GraphQL query in one of its pages, e.g. `gatsby new gatsby-starter-blog-mdx https://github.com/hagnerd/gatsby-starter-blog-mdx` (which is all my sample repo is).

- `gatsby build`

### Expected result

The site builds.

### Actual result

![image](https://user-images.githubusercontent.com/28382329/65393062-def0c300-dd30-11e9-86e3-2d4f8e1cc590.png)

### Environment

```
e:\repos\grumpyv2\gatsby-starter-blog-mdx>gatsby info --clipboard

  System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16
  Browsers:
    Edge: 44.18362.329.0
  npmPackages:
    gatsby: ^2.14.4 => 2.15.20
    gatsby-image: ^2.0.22 => 2.2.20
    gatsby-plugin-feed: ^2.0.8 => 2.3.13
    gatsby-plugin-google-analytics: ^2.0.5 => 2.1.17
    gatsby-plugin-manifest: ^2.0.5 => 2.2.18
    gatsby-plugin-mdx: ^1.0.33 => 1.0.43
    gatsby-plugin-offline: ^2.0.5 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.0 => 3.1.8
    gatsby-plugin-sharp: ^2.0.6 => 2.2.25
    gatsby-plugin-typography: ^2.2.0 => 2.3.8
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.1.20
    gatsby-remark-images: ^3.1.19 => 3.1.23
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.2.17
    gatsby-remark-smartypants: ^2.0.5 => 2.1.9
    gatsby-source-filesystem: ^2.0.2 => 2.1.26
    gatsby-transformer-remark: ^2.1.6 => 2.6.24
    gatsby-transformer-sharp: ^2.1.3 => 2.2.16
```

### Thoughts on fixes

We should be able to just make this go away - someone's got to be using a non-Windows-enlightened path manipulation library somewhere.

Barring that, at least raise a more useful error message. This wasted three hours of my life yesterday and it's a pretty popular issue judging from Google (even since February when we last tried to fix it).

**Comment by rgiese** [comment]
Tagging @pieh since he last worked in this land (https://github.com/gatsbyjs/gatsby/pull/12005)

**Comment by rgiese** [comment]
Oh and if this ends up being a fix in Relay, I'm happy to help drive that.

**Comment by waltercruz** [comment]
This is windows, right? 

Probably it will work if you do cd E:\ (capital letter) instead of cd e:\

**Comment by rgiese** [comment]
@waltercruz Yes, it's Windows, and the steps you pointed out are the remedy that got me off the ground. 

That said, it's still a bug, it's a regression from earlier this year, and, if I may, in 2019 OS-dependent path casing is not a battle I (or the non-trivial number of other users who are running into this, judging from Google results) should still have to fight, if we can avoid it.

**Comment by waltercruz** [comment]
> in 2019 OS-dependent path casing is not a battle

I wish that this was the case, but Mac OS Filesystem and Windows handling of casing doesn't make things easy, and when you have situations where your develop on a OS and deploys in another, things get even weirder.

> We should be able to just make this go away - someone's got to be using a non-Windows-enlightened path manipulation library somewhere.

There is - [true-case-path](https://github.com/Profiscience/true-case-path), and gatsby it's already using it. But even with it, things aren't that easy.

I solved a [issue](https://github.com/gatsbyjs/gatsby/issues/14962) that prevented gatsby from running on a shared host - and even if it seems strange, it's all about casing on different OS. 

I could try to fix #17811 that, but it's gonna take some time as I don't have access to any windows machine. I'm pretty sure that your test repository will work fine on Linux or mac machines (can try on both tomorrow)

BTW, windows cmd seems really weird. Check [this comment](https://github.com/Profiscience/true-case-path/issues/3#issuecomment-528832215) on true-case-path.

**Comment by Madgeniusblink** [comment]
Hey guys,

I am having a similar issue:

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
- allShopifyCollections

has anyone come up with a solution?

this happened very randomly.. I literally when to eat after taking a break.. and when I when to bring my website up "npm run develop" it started to act out.
any ideas on how to fix it?

**Comment by rgiese** [comment]
@Madgeniusblink , provided you're on Windows, make sure that your current path as shown on the command line has an uppercase drive letter.
