### ISSUE TITLE
[gatsby-transformer-remark]: Add classes to tags

### ISSUE THREAD

**Issue by muuvmuuv** [gatsbyjs/gatsby#17824]
## Summary

On my site I want to have the images wider than the text content like Medium is doing it. So I need to add classes to the tags which this plugin produces.

## Relevant information

I guess I need to create a local plugin which somehow adds classes to tags, but I can not find any documentation for that.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
It also depends on how you defined your overall layout and `max-width` values for e.g. the text surrounding the images.

Have you tried things mentioned here?
https://css-tricks.com/full-width-containers-limited-width-parents/

You can change the `wrapperStyle` of the images:
https://www.gatsbyjs.org/packages/gatsby-remark-images/#options

**Comment by muuvmuuv** [comment]
My layout is very flexible and I have no text that surrounds images.

The CSS-Trick link is a good workaround for now but I would like to give the`figure` a max-width and not transformed. The `wrapperStyle` is a good option too but not responsive.

~~I tried to wrap the images into a `div` but it seems that the transformer does not like HTML inside an MD file.~~

Anyway I think it would be a great option, to allow the user to add classes to compiled tags, e.g.:

```js
classes: {
  p: "container",
  img: "container--fluid",
  ...
}
```

**Comment by LekoArts** [comment]
Correct me if I understand you wrong, but can't you use normal CSS to achieve your goal? You can use selectors to target `p` or `img` elements.

**Comment by muuvmuuv** [comment]
That would be a solution, yes, but would increase the CSS size (not much for sure). I already have classes for this case. I see no reason to extend them, so they also target specific tags in an article. Another case is if I want to have markdown images opened in a lightbox, there I would like to have an additional class `lightbox`. Sure some lightbox plugins or self-programmed versions can be called on a query selector but some work as standalone.

**Comment by LekoArts** [comment]
I couldn't find such plugin in a quick search, but you can try creating your own remark plugin then :) This is an excellent guide explaining you how to edit the Markdown AST: https://www.gatsbyjs.org/docs/remark-plugin-tutorial/

**Comment by muuvmuuv** [comment]
Hey @LekoArts, I quickly typed a plugin together which has two bugs where I would need some help. Maybe you know someone from the Gatsby team or yourself can try to help me?

https://github.com/muuvmuuv/gatsby-remark-custom-classes

- When adding a class to the HTML tag `hr` which contains padding left or right it does not get applied. This is the expected behaviour in HTML, so I tried to wrap it into a `div` which then gets the classes, without success (wrapping existing tree's is not possible?).
- The `footnoteDefinition` is rendered into a `div` with the class `footnotes` which contains a list. I couldn't find a way of adding extra classes and neither the source where it is added/generated.

Maybe you know where I could find references to those two cases or you have an idea how I wrap an existing AST into a new `div`. 

This is what I have tried:

```js
// e.g. use visit to get all `paragraphs`
visit(AST, 'paragraph', node => {
  node = {
    type: "div", // if the type is unknown it is automatically a `div`
    children: node,
    data: {
      hProperties: {
        className: "color-red",
      },
    },
  }
})
```

I'm not very familiar with AST but I have expected that this works, but no, the parser simply ignores the `type: "div"` node and directly goes to the children and renders that.

**Comment by muuvmuuv** [comment]
So I got it working. The plugin is updated and can now wrap root children and/or give specific tags a class. It also can add classes to plugin generated HTML, like the image plugin.

The only thing that is _not_ working is `footnoteDefinition`, which somehow ignores the wrapper and adds itself to the end of the tree.

**Comment by pburtchaell** [comment]
Hi! I created a plugin here for a similar use case: https://github.com/pburtchaell/gatsby-remark-blocks

I'm taking the approach of framing each Markdown AST element in an HTML `div` to create a block in the layout. The use case is a novel design that's a bit more complex than the Medium style photo/text width design. Using CSS grid, I can position the blocks in whatever x/y position or at whatever height/width.
