### ISSUE TITLE
Route update behaviour is inconsistent across dev and prod modes in terms of hash change handling

### ISSUE THREAD

**Issue by smashercosmo** [gatsbyjs/gatsby#17821]
## Description

Route update behaviour is inconsistent across dev and prod modes in terms of hash change handling

### Steps to reproduce

1. Create two links with same url and different hash
2. Add console.log(location) to the route (page) component
3. Run app in dev mode
4. Try to click links (there will be console output after every click)
5. Then run app in prod mode
6. Try to click links again (there will be no output in the console)

### Expected result

Behaviour should be consistent across different modes (seems like desired behaviour is to not update route if only hash has been changed)

### Actual result

In dev mode hash change in the page url causes rerender, while in prod mode - doesn't.

### Environment

```
  System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.15.0 - /usr/local/bin/node
    Yarn: 1.10.1 - ~/.yarn/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.1
    Safari: 12.0
  npmPackages:
    gatsby: 2.15.20 => 2.15.20
    gatsby-image: 2.2.20 => 2.2.20
    gatsby-plugin-postcss: 2.1.8 => 2.1.8
    gatsby-plugin-preact: 3.1.11 => 3.1.11
    gatsby-plugin-react-helmet: 3.1.8 => 3.1.8
    gatsby-plugin-sharp: 2.2.25 => 2.2.25
    gatsby-plugin-svgr: 2.0.2 => 2.0.2
    gatsby-plugin-typescript: 2.1.9 => 2.1.9
    gatsby-plugin-webpack-bundle-analyzer: 1.0.5 => 1.0.5
    gatsby-source-filesystem: 2.1.26 => 2.1.26
    gatsby-transformer-sharp: 2.2.16 => 2.2.16
  npmGlobalPackages:
    gatsby-cli: 2.7.34
```

**Comment by LekoArts** [comment]
Hi, thanks for opening the issue! I haven't gone through your steps to reproduce this yet, however I'd like to ask:

Is there a specific problem or issue you're having with this behavior? So does it break something for you?

`gatsby develop` and `gatsby build` are still different in multiple places so it's not uncommon to see different behavior.

**Comment by smashercosmo** [comment]
Well, behaviour can be different for developer, but can't be different for the end user) Application shouldn't become broken after being deployed.

**Comment by LekoArts** [comment]
> Application shouldn't become broken after being deployed.

Is that the case?

Can you [provide a minimal reproduction][reproduction] since I'm not quite sure what some of your steps mean. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by universse** [comment]
Potentially related #17960

**Comment by universse** [comment]
@smashercosmo can you check if it's still a problem in v2.15.36?

**Comment by smashercosmo** [comment]
I'm gonna test it again tomorrow
