### ISSUE TITLE
Expose JSON logger for Gatsby CLI 

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#17836]
Currently, we don't have a public API for printing JSON logs (which are being added in https://github.com/gatsbyjs/gatsby/pull/14973)

We should expose this under a `--logger` flag or such once this is stable

To see JSON logs at the moment, a user may set `GATSBY_LOGGER=json`

**Comment by gonzarodriguezt** [comment]
I want to give this a try! :)

**Comment by gonzarodriguezt** [comment]
I would like to help with this once #14973 is merged 🙂

One question though, the flag should be a boolean, or it should take `json` as an argument, something like `--logger json`?

If it should take strings, we also need to accept `yurnalist` and `ink`? I see those are handled in the draft PR

Thank you!
