### ISSUE TITLE
dangerouslySetInnerHTML does not work on dev builds

### ISSUE THREAD

**Issue by weisisheng** [gatsbyjs/gatsby#17832]
## Description

I am trying to render a static markdown page in html but only some of the markdown styling effects are taking hold.  In the playground, the html renders perfectly as I checked the code in browser with a text file.  I am using tailwind and stock css with no code addressing markdown specific classes.

Describe the issue that you're seeing.

if I try to "bold" my title or section headers it works as expected. If I try to wrap my section headers with H1/H2/H3 uisng the standard # sign, nothing happens.  More importantly, using standard markdown notation as I understand it, I should be able to space paragraphs but leaving 2 blank spaces at end of paragraph and 2 to 4 blank lines between sections does nothing.

### Steps to reproduce

Click on page link (from home page) to be rendered.

See partially formatted text.

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

Nicely spaced and formatted html page

### Actual result

Plain text with only partial formatting from notation used in the md file, and no spacing.  All paragraphs are one after the other making it illegible.

What happened.

### Environment

  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
  npmPackages:
    gatsby: 2.15.17 => 2.15.17 
    gatsby-cli: ^2.7.47 => 2.7.47 
    gatsby-plugin-catch-links: ^2.1.9 => 2.1.9 
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16 
    gatsby-plugin-postcss: 2.1.7 => 2.1.7 
    gatsby-plugin-purgecss: 4.0.1 => 4.0.1 
    gatsby-plugin-react-helmet: 3.1.7 => 3.1.7 
    gatsby-plugin-typography: ^2.3.8 => 2.3.8 
    gatsby-source-filesystem: ^2.1.23 => 2.1.23 
    gatsby-transformer-remark: 2.6.4 => 2.6.4

**Comment by wardpeet** [comment]
Hi @weisisheng!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by weisisheng** [comment]
Yes, will try to do in next 48 hours.  Thanks very much.

**Comment by weisisheng** [comment]
Thanks for the offer to review and apologies for the delay.  We were essentially cut off from all outside internet last week due to great firewall of mainland China issues around their national holiday.

Hopefully I have got this isolated properly.  A noob at this and graphql at the moment.

https://github.com/weisisheng/tailwindstarter-mdproblem-2019

**Comment by weisisheng** [comment]
I couldn't get to bottom of problem and had to move on, so I began using Prismic and templates to format more attractively.
