### ISSUE TITLE
404 route is not redirected: "TypeError: Cannot read property 'layout' of undefined"

### ISSUE THREAD

**Issue by tangert** [gatsbyjs/gatsby#1784]
Whenever I try to visit an undefined route, instead of getting the 404 page I get this back:

`TypeError: Cannot read property 'layout' of undefined`

then:

```
ComponentRenderer.render
webpack:///.cache/component-renderer.js:95

ComponentRenderer.render
webpack:///~/react-proxy/modules/createPrototypeProxy.js:44
http://localhost:8000/commons.js:20679:22

measureLifeCyclePerf
webpack:///~/react-dom/lib/ReactCompositeComponent.js:75

ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
webpack:///~/react-dom/lib/ReactCompositeComponent.js:794

ReactCompositeComponentWrapper._renderValidatedComponent
webpack:///~/react-dom/lib/ReactCompositeComponent.js:821

ReactCompositeComponentWrapper.performInitialMount
webpack:///~/react-dom/lib/ReactCompositeComponent.js:361

ReactCompositeComponentWrapper.mountComponent
webpack:///~/react-dom/lib/ReactCompositeComponent.js:257

Object.mountComponent
webpack:///~/react-dom/lib/ReactReconciler.js:45

ReactCompositeComponentWrapper.performInitialMount
webpack:///~/react-dom/lib/ReactCompositeComponent.js:370
```

**Comment by kbariotis** [comment]
@tangert are you on development or accessing the static content directly? When on development, you wont see the 404 page directly but rather a predefined page.

Regardless, from your logs, it seems like there is an error somewhere in your code.

**Comment by KyleAMathews** [comment]
This is quite likely a bug in gatsby unfortunately as we just recently made a large change to how Gatsby's client runtime works. I'll look into this Monday.

**Comment by tangert** [comment]
@kbariotis I meant like, if I go to a page that's `myblog.com/undefined-route`, I don't receive the 404 page. I get this compiler error instead.

**Comment by KyleAMathews** [comment]
Fixed in latest release.

**Comment by tangert** [comment]
@KyleAMathews  awesome, all working.
