### ISSUE TITLE
Query parameters incorrectly handled by https://www.gatsbyjs.org/plugins/

### ISSUE THREAD

**Issue by sever1an** [gatsbyjs/gatsby#17854]
## Description
The plugins page puts all query parameters (except for the first character) directly into the search box.

### Steps to reproduce
On the production page, visit the URL: `https://www.gatsbyjs.org/plugins/?hello=world&ga=true`

The plugins page puts all query parameters (except for the first character) directly into the search box, such that this link will open to a plugins page searching for `ello=world&ga=true`

### Expected result

The search box should ignore unrelated query parameters, particularly the the analytics linker id picked up from gatsbyjs.com. Ideally a specific parameter would be used (ie. `?search=gatsby-plugin-`)

### Actual result

The search box is filled with the raw query parameter text.

### Environment

N/A - This is a bug in the production www page.

**Comment by pieh** [comment]
This is component that most likely need to be looked at - https://github.com/gatsbyjs/gatsby/blob/d7656728f2e567ee518ab8a1f23fb108b5650a78/www/src/components/plugin-searchbar-body.js#L468-L477

**Comment by universse** [comment]
I can take this on.

**Comment by sever1an** [comment]
Essentially the search term is whatever key in the querystring that has no associated value. I am not sure how to obtain that value with a library, but it would be easy with a regular expression run **before** `decodeURIComponent`.

```regex
/(^|&)([^&=]+)($|&)/
```
