### ISSUE TITLE
Embedded html not working with preloading

### ISSUE THREAD

**Issue by RobinJayaswal** [gatsbyjs/gatsby#17852]
## Description

I have an HTML snippet to embed a widget from a third party service, and want to put this in a blog post. It works when I load the page directly, but not when I navigate to it from another page.

I am putting the snippet (included below) in my markdown files that go through `gatsby-transformer-remark` and are rendered through `dangerouslyInsertHTML`.

This works properly when I go to the page directly: https://thirsty-perlman-b615a2.netlify.com/blog/2019-08-12-8-in-10-philosophy-majors-favor-socialism/

However, when I first go to the homepage, and click into the article, the widget does not render. Inspecting the network requests, it does not seem like the widget even executes: https://thirsty-perlman-b615a2.netlify.com and press _Test Embedding Post_.

The only reason I can think of for why I would see different results here are the preloading going on in the background.

Here is the embedded snippet loading the graph:

```
<div class="infogram-embed" data-id="53406afd-ad69-4146-8d91-566e54634c65" data-type="interactive" data-title="Socialism by Major">
</div>
<script>!function(e,t,s,i){
    var n="InfogramEmbeds",o=e.getElementsByTagName("script")[0],d=/^http:/.test(e.location)?"http:":"https:";
    if(/^\/{2}/.test(i)&&(i=d+i),window[n]&&window[n].initialized)window[n].process&&window[n].process();
    else if(!e.getElementById(s)){
      var r=e.createElement("script");
      r.async=1,r.id=s,r.src=i,o.parentNode.insertBefore(r,o)}
  }
  (document,0,"infogram-async","https://e.infogram.com/js/dist/embed-loader-min.js");
</script>
```

**Comment by bersot1** [comment]
Hello @RobinJayaswal i have issue almost equal yours... Maybe you can help me...

You can pass me how you put embeded in your md in file?

I'm trying using this same plugin gatsby-remark-embed-markdown but it is not working... you can see more information in my issue: #18503 

please, thks

**Comment by serendipitist** [comment]
Was this issue could be solved
