### ISSUE TITLE
Build specific pages not the entire app every time that we do minimal changes

### ISSUE THREAD

**Issue by Jsalvat** [gatsbyjs/gatsby#17864]
**## Summary**

In case that we want to build specific pages for our website, we can't do it atm. It will be interesting to do something like this for webapps where we've a lot of pages (+2000)

**### Basic example**

We've 2000 pages and we want to only update 1 of them. For that we need to do the full gatsby build to refresh that info. It will be amazing if we can tell gatsby to only build "THAT" page and keep others like before.

**### Motivation**

We need that for huge websites that have +2000 pages, because our changes are not "instant". For example our builds are 25min+. That will help a lot to expand Gatsby to big big companies.

**Comment by LekoArts** [comment]
Hi, thanks for opening the issue! We're working on a solution, you can follow the process here: https://github.com/gatsbyjs/gatsby/issues/5002

But we'll also announce it when it's ready. I'm closing this issue as answered, thanks for using Gatsby!
