### ISSUE TITLE
Styled components vs SCSS

### ISSUE THREAD

**Issue by AlbertZawadzki** [gatsbyjs/gatsby#17867]
Hi,
I've got a question, which is better for app using ReactJS - styled-components or SCSS?

Reason I'm asking this:
Go to https://ukfilmy.netlify.com and check what happens at beginning (both scrolls in loader are visible for 0.2sec), than sometimes when slider is changing foto the menu gets broken for 0.1s (component is missing styles for this time). I'm afraid that such bugs will appear in greater amount which isn't good from UX view.

If I change s-c to SCSS will these things get fixed or not?
Whatismore could you tell me what I did wrong? (If you need code just reply need code)

##
For these who will say you shouldn't need loader - please don't say it because it's required by my boss

**Comment by simjes** [comment]
This is not a `Styled-components` vs `SCSS` issue, there is something wrong in your styling. After a quick look it seems like the elements in `.slick-list` is causing the problem. Probably something with the implementation of the image slider.
