### ISSUE TITLE
[gatsby-plugin-layout] Share data between layout and page error: Maximum update depth exceeded

### ISSUE THREAD

**Issue by muuvmuuv** [gatsbyjs/gatsby#17860]
## Description

I want to share data between my `layouts/index.jsx` and `pages/index.jsx`, in particular I want to set a value in `pages/index.jsx` that will be added into `layouts/index.jsx` in a `div` as a class. I followed the guide in the readme and got two errors. The first one was easy, it was just that `ContextConsumer ` had to return jsx instead of nothing. The second appeared after I tried to `set({siteName: "index"})` which resulted in: Maximum update depth exceeded.

### Steps to reproduce

https://codesandbox.io/s/gatsby-starter-default-soxwl

### Expected result

It should share data

### Actual result

```
×
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
▼ 5 stack frames were expanded.
(anonymous function)
node_modules/react-dom/cjs/react-dom.development.js:23112
checkForNestedUpdates
node_modules/react-dom/cjs/react-dom.development.js:23115
scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js:21386
enqueueSetState
node_modules/react-dom/cjs/react-dom.development.js:13101
ContextProviderComponent../node_modules/react/cjs/react.development.js.Component.setState
node_modules/react/cjs/react.development.js:325
▲ 5 stack frames were expanded.
ContextProviderComponent.setData
src/components/Context.jsx:1
```

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0
    Safari: 13.0
  npmPackages:
    gatsby: ^2.15.21 => 2.15.21 
    gatsby-image: ^2.2.20 => 2.2.20 
    gatsby-plugin-catch-links: ^2.1.10 => 2.1.10 
    gatsby-plugin-layout: ^1.1.8 => 1.1.8 
    gatsby-plugin-manifest: ^2.2.18 => 2.2.18 
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.1.8 => 3.1.8 
    gatsby-plugin-react-helmet-canonical-urls: ^1.2.0 => 1.2.0 
    gatsby-plugin-sass: ^2.1.15 => 2.1.15 
    gatsby-plugin-sharp: ^2.2.25 => 2.2.25 
    gatsby-plugin-sitemap: ^2.2.14 => 2.2.14 
    gatsby-remark-emoji: 0.0.3 => 0.0.3 
    gatsby-remark-images: ^3.1.23 => 3.1.23 
    gatsby-source-filesystem: ^2.1.26 => 2.1.26 
    gatsby-transformer-json: ^2.2.9 => 2.2.9 
    gatsby-transformer-remark: ^2.6.24 => 2.6.24 
    gatsby-transformer-sharp: ^2.2.16 => 2.2.16 
  npmGlobalPackages:
    gatsby-cli: 2.7.50
```

**Comment by LekoArts** [comment]
Thank you for opening this!

As the error message (and subsequent Google searches) shows, you're triggering an infinite render-loop when placing the state update there.

```js
<div>
  TEST
  <button onClick={() => set({ siteName: "test2" })}>
    Change siteName
  </button>
</div>
```

This is working. Please have a look at this StackOverflow question as it should provide the answer you're seeking: https://stackoverflow.com/questions/51611948/pass-a-childs-state-through-react-context-api-to-parent-component

By the way, you have access to the `location` prop (like shown in this modified codesandbox: https://codesandbox.io/s/gatsby-issue-17860-hs98p). Maybe that holds some information you need.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Comment by muuvmuuv** [comment]
What a shame, but it makes sense. I think I have found what I have been looking for, I tried react-helmet and it can add attributes to body, so I'm just going to use that which works pretty good.

Thank you anyway! The link is a nice, will keep that in mind.
