### ISSUE TITLE
Add --no-progress to gatsby build for less verbose build output

### ISSUE THREAD

**Issue by brettinternet** [gatsbyjs/gatsby#17873]
## Summary

Currently, the `gatsby build` command is particularly verbose with progress updates. This causes heavy output for dumb terminals like Jenkins which print a new line for every animation:

![gatsby build command screenshot](https://user-images.githubusercontent.com/20871604/65544458-7b050080-ded0-11e9-9f4c-5a9c681604eb.png)

### Current workaround

I was fortunate to find [an open issue analyzing the effects of Ink on the the build time](https://github.com/gatsbyjs/gatsby/issues/15505). I found the suggestion to set an environment variable `CI=true`.

So to my build script looks like this:

```sh
cross-env CI=true gatsby build
```

### Basic example

It seems a `--no-progress` or `--quiet` option similar to the npm arg should be available to `gatsby build`.

Would having a `--no-progress` [build argument](https://github.com/gatsbyjs/gatsby/blob/561d33e2e491d3971cb2a404eec9705a5a493602/packages/gatsby-cli/src/create-cli.js#L332) setting the `CI` environment variable be appropriate?

### Motivation

An alternative solution would be to hold the `CI` environment variable as a feature and document it. While it's a workaround for me, I worry about the functionality changing since it's not a documented feature. @wardpeet pointed out that [most CI vendors enable `CI=true`](https://github.com/gatsbyjs/gatsby/issues/15505#issuecomment-534971732), but I wasn't aware of this. We use a self-hosted instance of Jenkins rather than a CI vendor.

---

Thank you to the contributors for all your attention to such an awesome project!

**Comment by bitttttten** [comment]
Looks like an issue with https://github.com/sindresorhus/ora no? IIRC that is the library used for the progress spinner.

**Comment by sidharthachatterjee** [comment]
> An alternative solution would be to hold the CI environment variable as a feature and document it. While it's a workaround for me, I worry about the functionality changing since it's not a documented feature. @wardpeet pointed out that most CI vendors enable CI=true, but I wasn't aware of this. We use a self-hosted instance of Jenkins rather than a CI vendor.

Not sure about `--no-progress` but this is a good idea. Would you like to open an PR documenting it?

**Comment by gagandeepp** [comment]
can i taket a look on this one?

**Comment by sidharthachatterjee** [comment]
Documented in https://github.com/gatsbyjs/gatsby/pull/17966

Let's close this for now
