### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by 454de6e** [gatsbyjs/gatsby#17885]
## Description

In my Gatsby project with Gatsby `2.15.21` hot reloading is not working when editing existing Markdown files (managed with `gatsby-plugin-mdx`).

### Steps to reproduce

You can reproduce the issue at the specified commit in this project: https://github.com/UNDataForum/main-website/commit/a0ccd162288aa7b945e790b6c6e5aaa7015036e8.  See https://github.com/UNDataForum/main-website/issues/72 for more info on which Gatsby versions at which commit behaved normal and which commit introduced the bug.

When checking out a specific commit, I ran `yarn run clean` (purge cache) and `yarn run purge` (purge dependencies) and then installed dependencies with `yarn` before testing.

### Expected result

Hot reloading should work when editing Markdown files, but it does not work. I would expect to see

```
info changed file at /Users/thilo/Projects/undataforum/main-website/content/posts/connecting-the-dots.md
```
in the log.

### Actual result

Gatsby does not detect the change, but thinks a new file has been added. In the log I see

```
info added file at /Users/thilo/Projects/undataforum/main-website/content/posts/connecting-the-dots.md
```

Hot reloading does not work.

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 13.0.1
  npmPackages:
    gatsby: ^2.13.71 => 2.15.21 
    gatsby-source-filesystem: ^2.0.37 => 2.1.26

**Comment by wardpeet** [comment]
Looks like HMR is working for me. There seems like an issue with the messaging but HMR is working fine.

Do you have any other issue that i'm not seeing?

**Comment by 454de6e** [comment]
Not an issue any more with 2.18.x
