### ISSUE TITLE
Need a way to set case sensitivity for Graphql queries

### ISSUE THREAD

**Issue by wangsongiam** [gatsbyjs/gatsby#1789]
For now, Graphql querying in Gatsby is case sensitive. But for some situations, eg., pulling tag names, it could be better to ignore cases, so that grouping tags would be less messy than this.
<img width="170" alt="screen shot 2017-08-13 at 3 06 36 am" src="https://user-images.githubusercontent.com/19645990/29254132-920e14ee-805c-11e7-9b61-71840c4a30b1.png">

**Comment by KyleAMathews** [comment]
Not stale!

**Comment by wangsongiam** [comment]
FWIW, my workaround is doing some data post-processing after querying. something like:

```javascript
let hashMap = {}
allTags.forEach(tag => {
  if (hashMap[tag.fieldValue.toLowerCase()]) {
    hashMap[tag.fieldValue.toLowerCase()] += tag.totalCount
  } else {
    hashMap[tag.fieldValue.toLowerCase()] = tag.totalCount
  }
})
let cleanTags =
  Object.entries(hashMap).map(([key, value]) => ({ fieldValue: key, totalCount: value }))
```

**Comment by isaacs** [comment]
I worked around this by just making all my tags lowercase.  This script is handy if anyone wants to do the same: https://github.com/isaacs/blog.izs.me/blob/master/lcase-tags.js  It uses js-yaml to parse and re-encode all your yaml, so it might shift some stuff around a bit.  Use at your own risk, inspect the diff before committing :)

**Comment by baerrach** [comment]
This works fine for tags, but what about `titles`?
Titles need to be case insensitively sorted.

The workaround is to do the sorting in code...

**Comment by isaacs** [comment]
@baerrach Another workaround is to provide something other than the title to sort on?  It's kludgey, but you could even do something like this:

```yaml
title: A Short Walk Through The Park
sortTitle: a-short-walk-through-the-park
...
```

And, you could perhaps define this sortTitle field when ingesting the content, so it doesn't have to be hard-coded in the markdown files.

I personally haven't found any cases where I need to sort titles alphabetically.  Usually there's either some kind of narrative ordering that makes more sense (for documentation sites), so I have an explicit position number, or a date on each post (blog content).

**Comment by baerrach** [comment]
@isaacs Great idea thanks. I'll keep that in the pocket for later.

I'm already converting markdown front matter to fields so I can consistently treat nodes the same across my gatsby spaces.

It wouldn't be a huge burden to add another field for this type of thing.

**Comment by baerrach** [comment]
I use https://www.gatsbyjs.org/packages/gatsby-plugin-node-fields/ to make this easier.

**Comment by coreyward** [comment]
+1 — this is more than an issue of case, though; Gatsby should offer a way to specify the collation ordering. Otherwise accented characters are also not westernized before sorting, so “épicerie” shows up after “zulu”, which is not what is actually desired in the vast majority of cases. 

@KyleAMathews What are your thoughts on the above? Would this sort of change be accepted into Gatsby? If so, can someone on the team point toward the source responsible for sorting today?

**Comment by SGiumelli** [comment]
Not stale !

**Comment by andrzejwp** [comment]
Anyone working on this one?

**Comment by redoper1** [comment]
Are there any updates regarding the support of accented characters sorting as mentioned by @coreyward?

**Comment by igorik77** [comment]
I'm experiencing the same issue. 
With sorting by title, I got the order:
a
b
c
k
č
instead of correct:
a
b
c
č
k

it's quite a surprise that gatsby doesn't have a way to sort accents.

**Comment by igorik77** [comment]
Good news,  guys from Cesko Digital made the solution:
https://github.com/cesko-digital/covid.gov.cz/pull/254
