### ISSUE TITLE
Support incremental production builds

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#179]
Something to research would be how to do partial rebuilds of a Gatsby site. If you have a large site, it'd be nice to avoid having to rebuild everything when you correct a small typo or make some other small change.

**Comment by jquense** [comment]
relevant: https://github.com/webpack/webpack/issues/250

**Comment by KyleAMathews** [comment]
Closing this as it's mainly an upstream Webpack issue to fix. [Happypack](https://github.com/amireh/happypack) and [hard-source](https://github.com/mzgoddard/hard-source-webpack-plugin) are two interesting options we can explore.
