### ISSUE TITLE
How to set html lang attribute in starter site?

### ISSUE THREAD

**Issue by luketeaford** [gatsbyjs/gatsby#1790]
Perhaps I missed this, but I can't seem to find the code that builds the HTML in order to add a lang attribute to the site.

I'm using Gatsby v1 with the starter site.

**Comment by KyleAMathews** [comment]
Added some docs around this!

**Comment by oliverjam** [comment]
Sorry to revive this but it seems a bit excessive to have to extend `html.js` just to set a `lang` attribute, given that every site is going to need one.

Would it not make more sense to allow users to configure this in the siteMetadata?

**Comment by m-allanson** [comment]
@oliverjam I think you can do this in your layouts using `gatsby-plugin-react-helmet`.

Given a default gatsby site with a layout like this: 
https://github.com/gatsbyjs/gatsby-starter-default/blob/b2faa3a3ae2a68ca31e5a6ffb0e321cba123fb78/src/layouts/index.js#L39-L45

You can set the language attribute by adding an `html` tag as a child of `<Helmet>`
 
```javascript
    <Helmet
      title="Gatsby Default Starter"
      meta={[
        { name: 'description', content: 'Sample' },
        { name: 'keywords', content: 'sample, something' },
      ]}
    >
        <html lang="en" />
    </Helmet>
```

**Comment by systemride** [comment]
Since this still shows up in google search results, I thought it was worth mentioning that adding to Helmet no longer works. 

Using the gatsby plugin does:
https://www.gatsbyjs.org/packages/gatsby-plugin-html-attributes/

**Comment by DSchau** [comment]
@systemride we use `htmlAttributes` in our starters.

See [gatsby-starter-default](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/src/components/seo.js#L15) as an example.

**Comment by cbdp** [comment]
> Since this still shows up in google search results, I thought it was worth mentioning that adding to Helmet no longer works (I'm using gatsby 2.0.64).
> Using the gatsby plugin does:
> https://www.gatsbyjs.org/packages/gatsby-plugin-html-attributes/

Still showing up in google searches.
Wanted to add that the github page for gatsby-plugin-html-attributes has a README which reads simply:
> #### legacy-gatsby-plugin-html-attributes
> **DO NOT USE**

I'll implement the solution shown as by @DSchau.

**Comment by amrtaher1234** [comment]
Gatsby released a new `Head` [API here](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/) for such uses and React Helmet is getting deprecated.
