### ISSUE TITLE
Can't use childImageSharp in gatsby-plugin-feed

### ISSUE THREAD

**Issue by carstenblt** [gatsbyjs/gatsby#17908]
## Description
I want to include an image url into an RSS feed using sharp. Depending on the parameters the build process either crashes without an error or I see

```
success Building static HTML for pages - 6.045 s — 31/31 38.01 pages/second
info Done building in 46.407152094 sec
[                            ]   0.025 s 0/12 0% Generating image thumbnails

(sharp:92591): GLib-CRITICAL **: 14:28:21.232: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:92591): GLib-CRITICAL **: 14:28:21.256: g_hash_table_lookup: assertion 'hash_table != NULL' failed
```

I believe this might be a problem with the way the build process works.

### Steps to reproduce
Create a project with the following gatsby-plugin-feed:

```
{
      resolve: `gatsby-plugin-feed`,
      options: {
        custom_namespaces: {
          'g': 'http://base.google.com/ns/1.0'
        },
        query: `
          {
            site {
              siteMetadata {
                title
              }
            }
          }
        `,
        feeds: [
          {
            serialize: ({ query: { allMarkdownRemark } }) => {
              return allMarkdownRemark.edges.map(edge => {
                return {
                  custom_elements: [
                    {'g:image_link': edge.node.frontmatter.productImage.childImageSharp.fixed.src},
                  ]
                }
              })
            },
            query: `
              {
                allMarkdownRemark {
                  edges {
                    node {
                      frontmatter {
                        productImage {
                          childImageSharp {
                            fixed(width: 600) {
                              src
                            }
                        }
                      }
                    }
                  }
                }
              }
            `,
            output: "/merchantfeed.xml",
            title: "Google Merchant center feed",
          },
        ],
      },
    },
```

### Expected result
Sharp should process the image and return a URL for the image.

### Actual result
Build crashes

### Environment
Note: I tried downgrading sharp.

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 68.0.2
    Safari: 13.0.1
  npmPackages:
    gatsby: ^2.15.15 => 2.15.15
    gatsby-background-image: ^0.8.12 => 0.8.12
    gatsby-cli: ^2.7.47 => 2.7.47
    gatsby-image: ^2.2.23 => 2.2.23
    gatsby-plugin-feed: ^2.3.13 => 2.3.13
    gatsby-plugin-google-analytics: ^2.1.17 => 2.1.17
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7
    gatsby-plugin-sass: ^2.1.14 => 2.1.14
    gatsby-plugin-sharp: ^2.2.27 => 2.2.27
    gatsby-plugin-stripe: ^1.2.3 => 1.2.3
    gatsby-plugin-typescript: ^2.1.7 => 2.1.7
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.5 => 1.1.5
    gatsby-plugin-webpack-size: ^1.0.0 => 1.0.0
    gatsby-remark-copy-linked-files: ^2.1.19 => 2.1.19
    gatsby-remark-images: ^3.1.22 => 3.1.22
    gatsby-remark-prismjs: ^3.3.13 => 3.3.13
    gatsby-remark-responsive-iframe: ^2.2.16 => 2.2.16
    gatsby-remark-smartypants: ^2.1.8 => 2.1.8
    gatsby-source-filesystem: ^2.1.22 => 2.1.22
    gatsby-source-graphql: ^2.1.14 => 2.1.14
    gatsby-transformer-remark: ^2.6.23 => 2.6.23
    gatsby-transformer-sharp: ^2.2.15 => 2.2.15

**Comment by LekoArts** [comment]
Please clarify your problem a bit more. Is this the image you're talking about?

```
{'g:image_link': edge.node.frontmatter.productImage.publicURL}
```

The graphql query below doesn't contain the `publicURL` node. If you want to use `childImageSharp.fluid.src` you'll need to adapt the above image link.

**Comment by carstenblt** [comment]
Sorry for that! That was my workaround for now, I just changed back half of it for this report. Actually I used

`{'g:image_link': edge.node.frontmatter.productImage.childImageSharp.fixed.src}`

**Comment by LekoArts** [comment]
No problem! I set up a codesandbox here: https://codesandbox.io/s/gatsby-sitemap-sharp-hz6fy

You can access the rss feed of the codesandbox here: https://hz6fy.sse.codesandbox.io/rss.xml

Seems alright to me? :)

**Comment by carstenblt** [comment]
Huh, alright. For my setup I can narrow it down to the GraphQL query for the image, but I'll try to investigate it more.

Downgrading gatsby-transformer-sharp and gatsby-plugin-sharp doesn't solve it for me. What's weird is that other queries for the same images work fine - the thumbnail generation that is triggered earlier in the build process works fine.
