### ISSUE TITLE
Rendering images and videos from same array in a loop

### ISSUE THREAD

**Issue by fredriknathorst** [gatsbyjs/gatsby#17917]
Hello! I have a nested array via GraphQL from Contentful containing a number of posts. Each post contains (among other things) an array of images which I render in a loop to create a slideshow for each post. So far so good. But I want to be able to mix videos and images in slideshows and I'm stuck. A video src url breaks an image tag and vice versa. Is there a way to conditionally use an image or video tag based on the graphQL data? Or another solution?

**Comment by universse** [comment]
Is there any way you can tell if a src url is a video or image?

**Comment by fredriknathorst** [comment]
@universse yes, i can pull the extension from ...{ localFile { extension } }

**Comment by universse** [comment]
Why can't you conditionally render video or img element based on that?

**Comment by fredriknathorst** [comment]
@universse Because I suck at coding, but I figured it out!

**Comment by universse** [comment]
That's great! :)
