### ISSUE TITLE
blog: except shows unescaped `\$15' instead of `$15'

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#17921]
## Description

Blog except shows unescaped `\$15' instead of `$15'

### Steps to reproduce

open https://www.gatsbyjs.org/blog/

### Expected result

normal text: `15$`

### Actual result

![Bildschirmfoto 2019-09-26 um 20 48 30](https://user-images.githubusercontent.com/184316/65716440-704c9600-e09f-11e9-8295-52bba48faa3a.png)

### Environment

n/a

**Comment by sidharthachatterjee** [comment]
This was an upstream issue in MDX that caused prettier to incorrectly escape blog: `$15' to `\$15' 

This is fixed in upstream so I'll close this once `www` is updated visa Renovate

**Comment by gillkyle** [comment]
I just updated the MDX version to verify this happened since it doesn't seem like renovate is actually making those changes, however I'm seeing the deployed version of the blog doesn't seem to have the backslashes anyway 🤔 hm.
