### ISSUE TITLE
Proxying to backend server

### ISSUE THREAD

**Issue by bvlktech** [gatsbyjs/gatsby#17920]
## Summary
Proxying to backend server
## Relevant information
Im just wondering how to proxy a backend server ie localhost:5000 i know in create-react-app you can just make a "proxy": "http://localhost:5000" in your package.json but in gatsby this doesnt work so much

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@bvlktech take a look at [this](https://www.gatsbyjs.org/docs/api-proxy/). It covers most use cases for proxying requests with gatsby.

**Comment by bvlktech** [comment]
thanks @jonniebigodes 😊👩🏻‍💻
