### ISSUE TITLE
Intrinsic TypeScript support for GraphQL query results

### ISSUE THREAD

**Issue by Silic0nS0ldier** [gatsbyjs/gatsby#17934]
## Summary

Currently GraphQL query results have little to no type information available for TypeScript to perform type checks.

This means you either work without it for the query result (not using TypeScripts strengths), define its type as `never` and validate everything at runtime (high technical debt, high perf cost) or maintain an interface defining the data shape manully (fair amount of technical debt, can be wrong).

For most situations the type information is available in some form, it just cannot be consumed in its current state. In theory tooling could be evolved to expose this information without any refactoring required so that existing projects could reap the benefits with minimal investment.

### Motivation

* Less technical debt required for Gatsby projects with TypeScript to have sufficient type check coverage.
* Projects without TypeScript receive better suggestions in IDEs that run TS against JS such as VS Code.
* Easy adoption (minimal to no configuration necessary)

### Related

There may be some tickets that have overlap here, I've tried to keep this free of implementation suggestions to encourage discussion around the desired outcome first. (User Story oriented, hopefully). I'll try to keep track of anything that does have overlap, or is relevant here however.

* https://twitter.com/Silicon_Soldier/status/1177351905002971136?s=19
* https://github.com/gatsbyjs/gatsby/issues/14185

**Comment by Silic0nS0ldier** [comment]
Stale check here seems tailored to pruning bugs back rather than a feature request backlog. Bot also seems to be ignoring certain interactions (label was added 25 days ago).

**Comment by Silic0nS0ldier** [comment]
I tried out a TypeScript code gen plugin before and figure its worth mentioning some of the pain points which prevented me from adopting it.

1. Passing parts of the query around is difficult to do so in a typesafe manner as for deeply nested values the only option is manually recreating the types (which defeats the purpose).
2. Some data sources (e.g. markdown with yaml head meta) produce extremely loose types as technically all the data may not be present. This means writing typesafe code means lots of boilerplate logic, even if the data source integrity is enforced. Perhaps some validation of data sources (e.g. markdown head yaml) would help here.
3. Types didn't work well for intellisense, potentially due to exceptionally verbose definitions taking longer to be processed.
4. Type errors had incomprehensible reason descriptions due to verbose definitions which are difficult for a human to understand. The VSCode and TypeScript teams are working on this problem, the types here however represented an extreme case.

Other things of note, that same plugin linked to a TypeScript language server plugin which provides GraphQL typing for query composition (along with validation I believe). It seems a natural fit for this.

**Comment by LekoArts** [comment]
Let's track this in the meta issue: https://github.com/gatsbyjs/gatsby/issues/17934
Please add your comments there, thanks!

**Comment by bsgreenb** [comment]
@LekoArts think you wanna fix the meta issue link?  it's just a link to this same PR
