### ISSUE TITLE
docs: remove or skip some TOC for a walkthrough by "Next"-Links

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#17931]
## Summary

i would remove this from the TOC on the left side:

- "Plugin Libary" 
- "Starter Library" 

or skip let skip it for Previous/Next functions

### Motivation

i start with introduction and go through the TOC only by "Next". After the Quickstart and the big receipts page i got "lost" with the "Next walkthrough" in the Libraries. there is no "Next" link.

**Comment by jonniebigodes** [comment]
@muescha i might be wrong about this but the flow is not directed that way, 

Removing the plugin/starter from the toc on the left side would break functionality for users. 

For new users it would remove a key piece of information that gatsby offers. For more experienced users with gatsby that might not know about all of the plugins available or don't remember how to configure a specific one, having that helper link goes the extra mile. And same for starters.

**Comment by muescha** [comment]
but now it breaks the flow with the next button ...

if we replace this with explaining docs and add in this docs at beginning links to the Libraries?

https://www.gatsbyjs.org/docs/starters/
https://www.gatsbyjs.org/docs/plugins/


i mean this links:
![Bildschirmfoto 2019-09-27 um 00 29 14](https://user-images.githubusercontent.com/184316/65731226-29719700-e0c5-11e9-9384-b61badcaefc2.png)

**Comment by jonniebigodes** [comment]
or leave the toc entries as they are because of the reason i've mentioned before and the during the flow when you click the next button after recipes, instead of jumping right into the plugins page introduce a "middle ground" page with some simple content that gatsby offers a increasing set of plugins available and starters and link them using a component like the one used recently by gillkyle.


I'll leave it to the docs team to offer their insight on how to best approach this.

**Comment by muescha** [comment]
also a good idea a small introducing into plugins library and starter library

**Comment by muescha** [comment]
CC @gatsbyjs/learning @marcysutton

**Comment by marcysutton** [comment]
> For new users it would remove a key piece of information that gatsby offers.

That's exactly it. These pages were added at that location in the sidebar to surface important aspects of the Gatsby ecosystem, and we aren't going to remove them without further thinking. However, incorporating another solution is outside of our team's priorities at the moment. I'm going to close this as we aren't going to skip or remove important sidebar links any time soon.
