### ISSUE TITLE
Service worker installed on development URL when gatsby build is run during gatsby develop.

### ISSUE THREAD

**Issue by sever1an** [gatsbyjs/gatsby#17936]
## Description

With `gatsby-plugin-offline` installed running `gatsby build` while `gatsby develop` is running causes for the service worker to be installed on the _development_ url. This causes major and somewhat non-obvious problems with hot reloading.

### Steps to reproduce

1. Create a new `gatsby-starter-hello-world` project. Install `gatsby-plugin-offline`.
2. Run `gatsby develop` and navigate to it in a browser window.
3. Run `gatsby build` in a different terminal.
4. Refresh browser window;

Side note: I am not sure if service workers can be installed on localhost. Due to networking issues I use it through a valid domain name with https. My usage seems to be an edge case, but I report the bug because it is unexpected.

### Expected result

Either develop or build should complain about running concurrently, or it might just work correctly without the service worker being installed.

### Actual result

In the application tab of Chrome dev tools, observe that the service worker is installed. Hot reloading works poorly until it is removed.

### Environment

```
bailey:~/environment/gatsby-error (master) $ gatsby info 

  System:
    OS: Linux 4.14 Amazon Linux AMI 2018.03
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    npm: 6.11.3 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^2.15.28 => 2.15.28
    gatsby-plugin-offline: ^3.0.11 => 3.0.11
  npmGlobalPackages:
    gatsby-cli: 2.7.53


bailey:~/environment/gatsby-error (master) $ 
```

**Comment by davidbailey00** [comment]
Hi @sever1an, thanks for reporting this issue! 

By default, `gatsby serve` and `gatsby develop` run on different ports (9000 and 8000 respectively) so any service worker installed on one of these ports will not affect another. Please can you confirm if you've overridden one of these ports? If not, it sounds like this problem is not caused by running build and develop concurrently, but rather is an unrelated issue with develop.

**Comment by sever1an** [comment]
Welcome back @davidbailey00 

I do change the port of `gatsby develop` to `8080`, but do not run `gatsby serve` at all.

When `gatsby build` runs, the already running instance of `gatsby develop -p 8080` outputs *stuff* like this to the terminal.

```
info ℹ ｢wdm｣: Compiling...
 DONE  Compiled successfully in 518ms                                                                   7:45:56 PM
⠀
info ℹ ｢wdm｣: Compiled successfully.
 WAIT  Compiling...                                                                                     7:45:57 PM
```

Running `gatsby build` is definitely the event that causes the errant service worker to be installed in a page that is connected to and receiving hot updates from `develop`. I suspect that somehow `build` is changing the files that `develop` observes resulting in a hot update including a service worker.

**Comment by sever1an** [comment]
I just updated my dependencies and can confirm this is still an issue.

not stale
