### ISSUE TITLE
Support decoding prop for gatsby-image

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#17941]
## Summary
Based on @addyosmani's comment we would like to experiment with decoding prop.

> My recommendation here would be for someone to put together a test page or site that uses loading=lazy and decoding=async with Gatsby's particular implementation. We can then test that on a slow network and device and see what the typical user experience might be.
> 
> Does that sound reasonable? I can give you advice but I think in this case as we're trying to make a default for a wide range of use cases measurement might be our best option :)

So we would like to have a gatsby test site with a fair amount of images that uses different combinations of the loading prop & decoding prop.

More info, checkout:
https://github.com/gatsbyjs/gatsby/pull/16005

**Comment by Blightwidow** [comment]
Interested into this issue, just wondering if you would prefer a standalone thing or include it into the `using-gatsby-example` ?

**Comment by arturfsousa** [comment]
Hey @Blightwidow are you still interested into this one? I was thinking about creating a `gatsby-photo-gallery` example with images from **unsplash** following a similar UI: https://unsplash.com/.

What do you guys think @wardpeet and @Blightwidow ?

**Comment by wardpeet** [comment]
This will be handled in the next gatsby-image 👍

**Comment by PetroPavlenko** [comment]
hey, @wardpeet, @addyosmani. There is site https://gatsby-image-nextgen.netlify.app/, not sure, but that should be enough to test that on slow devices (p.s. lighthouse mobile test adds CPU and network throttling)

**Comment by wardpeet** [comment]
We'll be shipping this as a default in the next gatsby-image. I haven't tested it but I've seen amp embracing it so I'm going to trust them.

**Comment by ascorbic** [comment]
This is fixed in [gatsby-plugin-image](https://www.gatsbyjs.com/plugins/gatsby-plugin-image/)
