### ISSUE TITLE
gatsby-plugin-mdx throws on empty line in JSX block

### ISSUE THREAD

**Issue by rakannimer** [gatsbyjs/gatsby#17947]
## Description

When I add a an empty line in a function in a JSX block of an MDX file `gatsby-plugin-mdx/loaders/mdx-loader.js` throws : 

```
SyntaxError: unknown: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?
```

### Steps to reproduce

You can either clone this repo : https://github.com/rakannimer/gastby-plugin-mdx-issue-repro

or 

1. 
```sh
gatsby new mdx-gatsby https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic
cd mdx-gatsby
```

2. In `src/pages/index.mdx` add :

```jsx

import { useState } from "react";

<div>
  <h2>count </h2>
  {() => {
    const [count, setCount] = useState(0);

    return <div onClick={() => setCount(count + 1)}>Some message {count}</div>;

}}

</div>
```

3. `npm start`

### Expected result

It should allow for empty lines in jsx code blocks.

### Actual result

It threw an error.

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /var/folders/jn/3z685bls0mv64x4q1vjrzgy40000gn/T/yarn--1569592481666-0.7159453631127595/node
    Yarn: 1.17.3 - /var/folders/jn/3z685bls0mv64x4q1vjrzgy40000gn/T/yarn--1569592481666-0.7159453631127595/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.50 => 2.13.50 
    gatsby-image: ^2.2.8 => 2.2.8 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4 
    gatsby-plugin-mdx: ^1.0.46 => 1.0.46 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3 
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9 
    gatsby-source-filesystem: ^2.1.8 => 2.1.8 
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5

**Comment by kgabryje** [comment]
Hey, can I take this one?

**Comment by samjt** [comment]
This is actually an issue with mdx-js
https://github.com/mdx-js/mdx/issues/767

**Comment by csywweb** [comment]
i have a same question

**Comment by samjt** [comment]
This issue isn’t resolved, the problem still exists up the dependency tree

**Comment by johno** [comment]
I'm going to go ahead and close this since it needs to be addressed upstream. There's nothing actionable on Gatsby or `gatsby-plugin-mdx`'s end.
