### ISSUE TITLE
[gatsby-source-wordpress] add config option to manipulate list of endpoint we fetch

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#17943]
There is need for users to be able to manipulate list of endpoints we get from wp rest introspection endpoint. This includes setting query params on routes and adding/removing routes.

Use cases for it are:
 - adding support for WPML translations (see #10915, #3263, #1648 ) (setting `lang` query param on post types endpoints + hitting them for each language)
 - being able to pull in draft / private posts ( https://github.com/gatsbyjs/gatsby/pull/10942#issuecomment-534182374 )

There were few attempts to implement this ( https://github.com/gatsbyjs/gatsby/pull/10942 , https://github.com/gatsbyjs/gatsby/pull/10335 ), but those implementations didn't allow for general purpose, robust system (they were mostly geared toward fixing particular use case)

I'd like to propose solution that is similar to wordpress filters, where user will be able to programatically manipulate list of endpoints with config option (and is similar to how `normalizer` config option works), where it's optional function that get list of endpoints, do some processing on it and return modified list to wordpress plugin:

```
{
      resolve: "gatsby-source-wordpress",
      options: {
        // [...] rest of config
        routesFilter: async ({ routes }) => {
         // do some work on routes array
          return routes
        }
      }
```

`routesFilter` is not final name of the config option - please comment on better name for it.

`routes` would be array of objects with following fields:
```js
{
  // required fields
  "url", "http://example.com/wp-json/wp/v2/pages", // url to endpoint - possibly this wouldn't be full absolute url and just "/wp/v2/pages" so users don't have to have special cases for wordpress.com hosting which have a bit different endpoints than user hosted wordpress instance
  "type": "wordpress__PAGE", // type used to generated gatsby data nodes
  // optional fields
  "queryParams": {
    "lang": "es"
  }, // optional object with params that will be used when fetching
  "normalizer": ({ entities }) => {
    // manipulate entites that were created after fetching this route - useful to set additional meta fields (like lang)
    return entities
  }, // optional function
}
```

Ultimate goal here is to create API that later on can be packaged into reusable `gatsby-source-wordpress` subplugins (see https://github.com/gatsbyjs/rfcs/pull/23 ). Creating subplugin system wouldn't be in scope for initial implementation. This features is just first step on path to be able to do this.

## Implementation:

Split https://github.com/gatsbyjs/gatsby/blob/4af3f9145e39fbb06222451d3e604ae3ff631111/packages/gatsby-source-wordpress/src/fetch.js#L557-L650 into few stages:
 - fist part that creates `routes` list (but doesn't do `whitelist`/`blacklist` filtering)
 - execute `filterRoutes` function (if it is defined)
 - apply `whitelist`/`blacklist` filters

Adjust https://github.com/gatsbyjs/gatsby/blob/4af3f9145e39fbb06222451d3e604ae3ff631111/packages/gatsby-source-wordpress/src/fetch.js#L396-L399 to use optional `queryParams` object in route object

Figure out where in https://github.com/gatsbyjs/gatsby/blob/4af3f9145e39fbb06222451d3e604ae3ff631111/packages/gatsby-source-wordpress/src/fetch.js#L252-L369 to apply optional `normalizer` function for given route (this is a bit tricky, because `gatsby-source-wordpress` already have special support for some wordpress plugins - do we want to apply normalization before or after those special cases?)

References:
See https://github.com/gatsbyjs/gatsby/pull/10942#issuecomment-534268782 comment (that contains some of information in this issue) about motivation and "roadmap" to be able to create wordpress subplugins in smaller incremental steps

**Comment by LekoArts** [comment]
With v4 of `gatsby-source-wordpress` now being powered by WPGraphQL and not the REST API anymore we'll close outdated issues that we won't fix anymore. Please use the new version and check if your issue is fixed. Thanks!
