### ISSUE TITLE
add margin to code blocks in plugin document page

### ISSUE THREAD

**Issue by XHMM** [gatsbyjs/gatsby#17954]
code block in plugin document page missed `margin` so caused collapse effect , it's bad for read：
![image](https://user-images.githubusercontent.com/24786522/65787346-496b8e00-e18b-11e9-8407-ff6ac23e16cb.png)

should add `margin`  to `gatsby-code-title` class and it will look good as below：
![image](https://user-images.githubusercontent.com/24786522/65787557-c991f380-e18b-11e9-9bf1-f2c77e59a0b3.png)

[associated page link](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/)

**Comment by sidharthachatterjee** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/17969

Thank you so much @ashu8912 🥇
