### ISSUE TITLE
[gatsby-link] Add a callback for preloading

### ISSUE THREAD

**Issue by onestopjs** [gatsbyjs/gatsby#17952]
## Summary

Add a callback to Gatsby Link for preloading

### Basic example

```jsx
const preloadFunction = () => console.log('preloading');

<Link to="/some-page" onPreload={preloadFunction}>Some page</Link>
```

### Motivation

Gatsby Link uses IntersectionObserver to preload linked pages which are visible. I think it would be really useful to be able to pass a callback function to Gatsby Link which will be called when preloading has been triggered.

In my plugin `gatsby-theme-localization` I have a [wrapper for Gatsby Link](https://github.com/onestopjs/gatsby-theme-localization/blob/master/gatsby-theme-localization/src/components/Link.tsx) which preloads namespaces on hover. However, it is not sufficient as Gatsby preloads page data earlier. Having such callback would enable me to preload namespaces whenever Gatsby decides to. 

I am sure that there are many other use cases where this would be really valuable.

I am more than willing to work on this if people agree that it would be a nice feature.

**Comment by jzabala** [comment]
I would like to take this one 🙂

**Comment by wardpeet** [comment]
Hey @jzabala & @onestopjs,

Could you clarify a little bit more about what benefit this would give you? I don't think this is the right approach to get to the solution you're after. This would fix your issue in certain cases but you would need to add onPreload for the same link every time. Let's say you have a header & footer navigation, it means you'll have to add onPreload to both on them to make it work 💯.

For me it seems like we're missing some preload apis to attach to a route.
