### ISSUE TITLE
Allow plugins to create node of type owned by another plugin

### ISSUE THREAD

**Issue by kunxi** [gatsbyjs/gatsby#17962]
## Summary

Allow transform plugins, such as asciidoc to convert the content to Markdown, then create a node of RemarkMarkdownNode, so we can leverage the remark plugins.

This is related to https://github.com/gatsbyjs/gatsby/issues/5289.

### Basic example

The use case:

We build `gatsby-transformer-notebook` plugin to transfrom the jupyter notebook. We can use the `nbconvert` to convert the notebook to either Markdown or HTML fragments. 

Here is the approach we are exploring, suggested by @KyleAMathews 

* Invoke the `jupyter nbconvert` to convert Jupyter Notebook to HTML fragment.
* Parse the exported HTML fragments with `rehype-parse`
* Convert it to the MdAST via `rehype-remark`
* Stringify the MdAST via `remark-stringfy` as `content`

In `onCreateNode` create a `JupyterNoteBookNode`, and assign the content. Then create a 
`MarkdownRemarkNode`, and link the  `JupyterNoteBookNode` as the parent of the `MarkdownRemarkNode`.

Then the build process throws the following error:

```
Error processing JupyterNotebook file ../../Machine_Learning/Linear Regression.ipynb:

      The plugin "gatsby-transformer-notebook" created a node of a type owned by another plugin.

        The node type "MarkdownRemark" is owned by "gatsby-transformer-remark".

        If you copy and pasted code from elsewhere, you'll need to pick a new type name
        for your new node(s).

        The node object passed to "createNode":
```

### Motivation

I think Gatsby team has invested heavily in the remark ecosystem. If we allow other transformer plugin to trans-compile to the markdown format, we can avoid reinvent the wheel.

**Comment by jonniebigodes** [comment]
@kunxi i might be completely off base here, but have taken a look at [this](https://www.gatsbyjs.org/docs/schema-customization/), to see if it can help?

**Comment by KyleAMathews** [comment]
The docs above should help. Real quick what you want to do is create a node with a different type but set the mediaType to text/markdown -- then that will get transformed to MarkdownRemark

**Comment by kunxi** [comment]
Thanks for the tip!
