### ISSUE TITLE
After install CLI update message needs fixing

### ISSUE THREAD

**Issue by jbampton** [gatsbyjs/gatsby#17963]
When I ran `gatsby new default` it installed the starter project and the final message was that I should update the Gatsby CLI as shown in the image below:

![Screen Shot 2019-09-28 at 2 11 12 pm](https://user-images.githubusercontent.com/418747/65811378-db5eaf80-e1fa-11e9-82f9-80c4c4599a4e.png)

If you were to run this command it would install in the current directory and not globally.  The current documentation says `npm install -g gatsby-cli` or to install globally.

So it would seem we need to update this post install message if possible.  
I am new to Gatsby so I am not sure if this is under our control.  

### Environment

System:
    OS: macOS 10.14.6
    CPU: (24) x64 Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 13.0.1
  npmGlobalPackages:
    gatsby-cli: 2.7.53

**Comment by jonniebigodes** [comment]
you're correct, that should be the case. Looks like the message shown in the sanity check does not match the documentation. If you're willing, fork the repo, read the contribution documentation and make a pull request adressing this issue and when you do, mention this issue
