### ISSUE TITLE
[docs] Build Gatsby Portfolio Site tutorial

### ISSUE THREAD

**Issue by HackyRoot** [gatsbyjs/gatsby#17964]
## Summary

Add documentation for creating Gatsby Portfolio site, currenly there's a [stub](https://www.gatsbyjs.org/docs/building-a-portfolio/)  already created in the Gatsby docs for "Building a portfolio" but there's not content available.

### Motivation

While I was seaching for tutorials to create a Portfolio website using Gatsby, I couldn't find official documentation for the same, hence I'd my way of contributing back to the community!

**Comment by jonniebigodes** [comment]
@HackyRoot read the [contribution documentation](https://www.gatsbyjs.org/contributing/how-to-contribute/), fork the repo and work on it. Would like to see the contribution.

**Comment by HackyRoot** [comment]
Thank you, @jonniebigodes for this opportunity!

**Comment by jonniebigodes** [comment]
@HackyRoot no need to thank. Just glad that you picked up on this and are willing to expand the documentation. Don't know about your timetable but a heads up if you manage to work on this and make a pull request during this week, be advised that the review process might take a bit, as the gatsby team is London for the Gatsby days during the coming week for their gathering,
