### ISSUE TITLE
Filtering for articles that DON'T INCLUDE a certain category: "ne" and "nin" do not work.

### ISSUE THREAD

**Issue by aofolts** [gatsbyjs/gatsby#17971]
### Description

I'm trying to filter some articles by excluding a certain category.

`eq` works properly. It returns only articles with the given category slug.

```
filter: {
  categories: {
    elemMatch: {
      slug: {
        eq: "business"
      }
    }
  }
}
```

However `ne` does not work. It returns all the articles, unfiltered.

```
filter: {
  categories: {
    elemMatch: {
      slug: {
        ne: "business"
      }
    }
  }
}
```

### Steps to reproduce

Enter the query in graphql explorer.

### Expected result

`ne` should filter out all articles with the given category slug.

### Actual result

`ne` returns all the articles, unfiltered.

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.4.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.50 => 2.13.50
    gatsby-image: ^2.2.8 => 2.2.8
    gatsby-link: ^2.2.4 => 2.2.4
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1
    gatsby-plugin-feed: ^2.3.6 => 2.3.6
    gatsby-plugin-google-analytics: ^2.1.6 => 2.1.6
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-plugin-sitemap: ^2.2.5 => 2.2.5
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-plugin-svg-sprite: ^2.0.1 => 2.0.1
    gatsby-remark-images: ^2.0.6 => 2.0.6
    gatsby-source-contentful: ^2.1.44 => 2.1.44
    gatsby-source-filesystem: ^2.1.8 => 2.1.8
    gatsby-transformer-json: ^1.0.20 => 1.0.20
    gatsby-transformer-remark: ^2.6.10 => 2.6.10
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5
  npmGlobalPackages:
    gatsby-cli: 2.7.26

**Comment by aofolts** [comment]
There are multiple categories, so I'm trying to filter out any articles that contain the `business` tag regardless of whether they have other tags.

**Comment by aofolts** [comment]
I also tried using "nin" and that didn't work either.

`in` works, but achieves the opposite effect I want: returning all articles that include that category.

**Comment by jonniebigodes** [comment]
@aofolts can you make a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be looked at in more detail?
