### ISSUE TITLE
Can you create nested routes like in React-router?

### ISSUE THREAD

**Issue by tangert** [gatsbyjs/gatsby#1797]
E.g. have a shared component on the page and only change what's displayed below?

**Comment by KyleAMathews** [comment]
Yes, we call them layouts. Try going through the tutorial which walks you through using them https://www.gatsbyjs.org/tutorial/

**Comment by mpolinowski** [comment]
Hi @KyleAMathews ,
is there an easy way to push those nested routes to different URLs? My case looks something like this:

./pages
   chapter1.js
   iBelong2Ch1.js
   chapter2.js
   iBelong2Ch2.js

Following the (awesome, btw) tutorial would lead me to have the following routes:

/chapter1
/iBelong2Ch1
/chapter2
/iBelong2Ch2

But I would need them to be:

/chapter1
/chapter1/iBelong2Ch1
/chapter2
/chapter2/iBelong2Ch2

**Comment by KyleAMathews** [comment]
Create a "chapter1" directory and put index.js and iBelong2Ch1.js page components inside.

**Comment by mpolinowski** [comment]
Just had a chance to test it... Gatsby is amazing. Thank you @KyleAMathews

**Comment by arjunmahishi** [comment]
But is it possible to have something like `/route/<X>` 
and decide which component to render based on the value of `X`

**Comment by mpartipilo** [comment]
@arjunmahishi Yes, it's easy.

If you want to do it manually you can use the Match component: https://reach.tech/router/api/Match

The Route component allows the same, but with a bit more magic: https://reach.tech/router/api/RouteComponent

**Comment by arjunmahishi** [comment]
> If you want to do it manually you can use the Match component: https://reach.tech/router/api/Match
> The Route component allows the same, but with a bit more magic: https://reach.tech/router/api/RouteComponent

And this is recommended to use with gatsby?

**Comment by mpartipilo** [comment]
@arjunmahishi 

You need to create a client only route: https://www.gatsbyjs.org/docs/authentication-tutorial/#creating-client-only-routes

Conditional rendering of components is not a concern for gatsby. That's where React and Reach Router come into play.

**Comment by zacaree** [comment]
I'm trying to do exactly what @mpolinowski described above.

@KyleAMathews responded to him saying:
> Create a "chapter1" directory and put index.js and iBelong2Ch1.js page components inside.

This sounds awesome but it isn't working for me.
I'm getting an error: "TypeError: Cannot read property 'page' of undefined" 
Is it because something changed in Gatsby v2?

I'm struggling to find a solution.
Thanks!

**Comment by alqamabinsadiq** [comment]
@KyleAMathews How to do the same thing using `createPage` API

**Comment by njvoulelis** [comment]
Plus one to the above ^

**Comment by jeffersonnnn** [comment]
definitely need a way to do it with the createPage API
