### ISSUE TITLE
gatsby build end early in docker build

### ISSUE THREAD

**Issue by FengShangWuQi** [gatsbyjs/gatsby#17982]
## Description

gatsby build end early in docker build.

this is my Dockerfile

![image](https://user-images.githubusercontent.com/17982705/65825543-837f8180-e2aa-11e9-9830-dcad188f9778.png)

I try

![image](https://user-images.githubusercontent.com/17982705/65825550-998d4200-e2aa-11e9-944f-f41b81a236c6.png)

even isn't working as expected.

### Steps to reproduce

repositories: https://github.com/FengShangWuQi/fengshangwuqi.github.io

1、`docker build -t blog:v1 .`

### Expected result

![image](https://user-images.githubusercontent.com/17982705/65825178-78c2ed80-e2a6-11e9-8f1b-619f35deeb3d.png)

### Actual result

![image](https://user-images.githubusercontent.com/17982705/65825179-7f516500-e2a6-11e9-828f-7d8169cd8190.png)

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Safari: 13.0.1
  npmPackages:
    gatsby: 2.15.28 => 2.15.28 
    gatsby-image: 2.2.23 => 2.2.23 
    gatsby-plugin-emotion: 4.1.9 => 4.1.9 
    gatsby-plugin-feed: 2.3.15 => 2.3.15 
    gatsby-plugin-google-analytics: 2.1.19 => 2.1.19 
    gatsby-plugin-offline: 3.0.11 => 3.0.11 
    gatsby-plugin-page-creator: 2.1.23 => 2.1.23 
    gatsby-plugin-react-helmet: 3.1.10 => 3.1.10 
    gatsby-plugin-sharp: 2.2.27 => 2.2.27 
    gatsby-plugin-svgr: 2.0.2 => 2.0.2 
    gatsby-plugin-twitter: 2.1.9 => 2.1.9 
    gatsby-plugin-typescript: 2.1.11 => 2.1.11 
    gatsby-plugin-typography: 2.3.10 => 2.3.10 
    gatsby-remark-autolink-headers: 2.1.13 => 2.1.13 
    gatsby-remark-copy-linked-files: 2.1.23 => 2.1.23 
    gatsby-remark-emojis: 0.3.2 => 0.3.2 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-images: 3.1.25 => 3.1.25 
    gatsby-remark-prismjs: 3.3.16 => 3.3.16 
    gatsby-remark-responsive-iframe: 2.2.20 => 2.2.20 
    gatsby-remark-smartypants: 2.1.11 => 2.1.11 
    gatsby-source-filesystem: 2.1.28 => 2.1.28 
    gatsby-transformer-remark: 2.6.26 => 2.6.26 
    gatsby-transformer-sharp: 2.2.19 => 2.2.19 
  npmGlobalPackages:
    gatsby-cli: 2.7.47
```

**Comment by lannonbr** [comment]
Hey @FengShangWuQi So a question to have is does the gatsby build complete successfully? If no then we may have an issue with it misbehaving with Docker. If it does build successfully, then it may be an issue with how the CLI does its logging in a Docker environment.
