### ISSUE TITLE
Paginated Pages Downgrade Priority. 

### ISSUE THREAD

**Issue by Cobwebster** [gatsbyjs/gatsby#17984]
Hey,

So I was wondering if there was an example of the following,

I basically have a blog post site and I paginate like 20 posts for a page with this format

siteurl.net/blogs
siteurl.net/blogs/2
siteurl.net/blogs/3
siteurl.net/blogs/4
(each post just linking to like 20 blog post pages)

The number is dynamic (generated in gatsby buildtime depending on the amount of posts)

I would basically want to make those blog catalogues (just a page that links to like 20 posts)
have a lower priority because I believe google is linking to the blog catalogue and not the posts when searching google.

How would I go about doing this?

Thanks in advance.

**Comment by Cobwebster** [comment]
Is this the right place for gatsby sitemap issues? using the plugin.

**Comment by LekoArts** [comment]
Thank you for opening this!

According to https://support.google.com/webmasters/answer/183668?hl=en Google doesn't even support the priority tag. You could also try excluding the pages or use the serialize function to change the priority and its entries.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Comment by Cobwebster** [comment]
> Thank you for opening this!
> 
> According to https://support.google.com/webmasters/answer/183668?hl=en Google doesn't even support the priority tag. You could also try excluding the pages or use the serialize function to change the priority and its entries.
> 
> We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

Hey,

Thanks for the reply.

So priority isn't a thing anymore, if I blacklist my blog catalogue from being index'd, would it still index any links it finds on those pages?

say for example it doesn't index the page /posts page but it'll still scan it and see that in that page it links to /post/1/

or does it just ignore the page entirely and doesn't even attempt to follow links on it.
