### ISSUE TITLE
Add note about how to disable eslint in gatsby

### ISSUE THREAD

**Issue by JimTheMan** [gatsbyjs/gatsby#17986]
I have deleted all my prettier and .eslint files, but when I fun gatsby develop I still get erros about linting. 

I don't want to use any linting at all. How do I disable it??

**Edit**:

Maybe we should add a small note at the bottom of https://www.gatsbyjs.org/docs/eslint/ explaining how to disable it?

**Comment by pieh** [comment]
Gatsby adds barebones eslint loader when you don't have any `.eslint` files - You can create empty `.eslintrc` file, which will disable it completely (as gatsby assumes once you have eslint file, you are in charge of linting)

**Comment by sidharthachatterjee** [comment]
Maybe we should add a small note at the bottom of https://www.gatsbyjs.org/docs/eslint/ explaining how to disable it?

**Comment by ThomasJanUta** [comment]
I created a pull request to fix this issue with in #19171 https://github.com/gatsbyjs/gatsby/pull/19171
