### ISSUE TITLE
Make pages/docs/index.js into a markdown file.

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#17989]
## Summary

Make the Introduction page of the docs an MDX file.

## Motivation

This is the first page that appears when going to the "docs" section and a core page that should be translated.

**Comment by Yofamb** [comment]
I'm be keen to tackle this issue.

**Comment by Yofamb** [comment]
I've started to work on this issue, it can be found at https://github.com/Yofamb/gatsby/commit/68dbedbad62b232b8c69cca6994d6358be209ead Should I open up a pull request to discuss the thing i'm unsure of?

**Comment by tesseralis** [comment]
Yes! Just make a draft pull request and I can take a look at it.

**Comment by Yofamb** [comment]
Hi Nat, I've created a wip pull request https://github.com/gatsbyjs/gatsby/pull/18014 once you have some spare time, i'd appreciate a bit of guidance.

I'm currently unsure on how to handle the h1 with an id for the anchor. Also need a bit of guidance on general structure.
