### ISSUE TITLE
[gatsby-remark-prismjs] move command-line-prompt span outside code tag

### ISSUE THREAD

**Issue by muuvmuuv** [gatsbyjs/gatsby#17996]
## Summary

I'm giving my code block which gets highlighted an inner padding but because the `command-line-prompt` span is also inside the pre block it gets the padding as well. I think it would make the plugin more consistent to move it out of the code block and put it in the pre block or even better in the outer div `gatsby-highlight`.

### Basic example

```md

```bash{outputLines: 3-7}
~/Documents/M8FINDER/API master !1 *1
marvinheilemann@marvin❯ py src/app.py
Traceback (most recent call last):
  File "src/app.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
\```

```

### Motivation

This would increase the customizability and would make it more consistent with the line hightlighter.

**Comment by LekoArts** [comment]
Thank you for opening this!

As you can fix these issues by leveraging CSS I won't think that this needs to be changed/fixed.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
