### ISSUE TITLE
Run babel-plugin-macros before extracting queries opening way for FixedImage and FluidImage JSX element macros

### ISSUE THREAD

**Issue by TomerAberbach** [gatsbyjs/gatsby#17992]
## Summary

Currently, macros using [babel-plugin-macros](https://github.com/kentcdodds/babel-plugin-macros) are expanded *after* queries are extracted. I think macros would be far more useful in Gatsby if they were expanded *before* queries are extracted because they could then be used to generate queries.

### Basic example & Motivation

I've pretty much finished implementing a JSX element macro wrapper around [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image) (which only accepts constant arguments), but have only now realized that although it expands to proper `StaticQuery` code, the macro does not work with Gatsby because macros are expanded after queries are extracted. I did not realize this until now because I was only testing what the macro expands to rather than testing the macro directly in Gatsby.

Example usage:
```jsx
import { FixedImage } from 'gatsby-image.macro'

export MyAwesomeImage = () => (
  <FixedImage src="my-awesome-image.png" width={200} />
)
```

**Comment by KyleAMathews** [comment]
🤯

That's a great idea!

Does the macro combine queries from multiple queries? Does this only work with gatsby-source-filesystem?

**Comment by pieh** [comment]
Here's part of code that parses files to ast https://github.com/gatsbyjs/gatsby/blob/182248546d0c8e78eac0ddbfd0dfeed6b6b1a78c/packages/gatsby/src/utils/babel-parse-to-ast.js , we are using `@babel/parser` here, can't tell yet if we can plug macros support with this approach, but this surely is something that can be solved (?)

**Comment by TomerAberbach** [comment]
> 🤯
> 
> That's a great idea!
> 
> Does the macro combine queries from multiple queries? Does this only work with gatsby-source-filesystem?

Currently my implementation generates one `StaticQuery` JSX element per use of `FixedImage` and `FluidImage` (with separate queries). Is this allowed by Gatsby? If not, it would not be difficult to modify my current implementation to merge the queries of all `FixedImage` and `FluidImage` usages in the same file.

You are right that it only works with `gatsby-source-filesystem`. I was envisioning that at some point I would make the `src` attribute of the JSX elements configurable to support other sources, but I think that supporting `gatsby-source-filesystem` exclusively is a good starting point.

> Here's part of code that parses files to ast https://github.com/gatsbyjs/gatsby/blob/182248546d0c8e78eac0ddbfd0dfeed6b6b1a78c/packages/gatsby/src/utils/babel-parse-to-ast.js , we are using `@babel/parser` here, can't tell yet if we can plug macros support with this approach, but this surely is something that can be solved (?)

I think we could probably call [transformFromAst](https://babeljs.io/docs/en/babel-core#transformfromast) on the result of that with `{ plugins: ['macros'] }` passed in for the options. If we did that we would want to undo #7129 since there would be no need to run `babel-plugin-macros` twice.

---

Lastly, I have design decision I would like feedback on. My current implementation converts constant JavaScript arguments to their associated GraphQL values. However, I have still not addressed the issue of GraphQL enums (which are used in `gatsby-plugin-sharp`). There isn't really a JavaScript equivalent which I can convert from. I was thinking of either allowing string arguments for enums or providing some `enum` macro which could be used as follows: `` enum`CENTER` ``.

**Comment by TomerAberbach** [comment]
Also, I was planning on publishing the `FixedImage` and `FluidImage` macros as part of my own npm package, but if you would like it to be part of the `gatsby-image` package we could discuss that possibility.

**Comment by pieh** [comment]
> I think we could probably call [transformFromAst](https://babeljs.io/docs/en/babel-core#transformfromast) on the result of that with `{ plugins: ['macros'] }` passed in for the options. If we did that we would want to undo #7129 since there would be no need to run `babel-plugin-macros` twice.

We probably will still need #7129, because extracted ASTs used for finding queries are being discarded right now. I'm not even sure if we can reuse them...

> Lastly, I have design decision I would like feedback on. My current implementation converts constant JavaScript arguments to their associated GraphQL values. However, I have still not addressed the issue of GraphQL enums (which are used in `gatsby-plugin-sharp`). There isn't really a JavaScript equivalent which I can convert from. I was thinking of either allowing string arguments for enums or providing some `enum` macro which could be used as follows: `` enum`CENTER` ``.

Are we talking about "props" that users would use or internal mechanisms for converting props to graphql args? For "props" I would suggest strings, as this will be familiar to users (given that there is no enum in vanilla js).

> Also, I was planning on publishing the `FixedImage` and `FluidImage` macros as part of my own npm package, but if you would like it to be part of the `gatsby-image` package we could discuss that possibility.

This is up to you. We would love to have it in packages we maintain here ultimately, but we are not yet sure if implementing them with babel macros is ideal implementation for gatsby (could be, we just didn't research topic too much yet and see what are potential alternatives)

**Comment by TomerAberbach** [comment]
> > I think we could probably call [transformFromAst](https://babeljs.io/docs/en/babel-core#transformfromast) on the result of that with `{ plugins: ['macros'] }` passed in for the options. If we did that we would want to undo #7129 since there would be no need to run `babel-plugin-macros` twice.
> 
> We probably will still need #7129, because extracted ASTs used for finding queries are being discarded right now. I'm not even sure if we can reuse them...
> 
> > Lastly, I have design decision I would like feedback on. My current implementation converts constant JavaScript arguments to their associated GraphQL values. However, I have still not addressed the issue of GraphQL enums (which are used in `gatsby-plugin-sharp`). There isn't really a JavaScript equivalent which I can convert from. I was thinking of either allowing string arguments for enums or providing some `enum` macro which could be used as follows: `` enum`CENTER` ``.
> 
> Are we talking about "props" that users would use or internal mechanisms for converting props to graphql args? For "props" I would suggest strings, as this will be familiar to users (given that there is no enum in vanilla js).
> 
> > Also, I was planning on publishing the `FixedImage` and `FluidImage` macros as part of my own npm package, but if you would like it to be part of the `gatsby-image` package we could discuss that possibility.
> 
> This is up to you. We would love to have it in packages we maintain here ultimately, but we are not yet sure if implementing them with babel macros is ideal implementation for gatsby (could be, we just didn't research topic too much yet and see what are potential alternatives)

Okay, thanks for all of the feedback. What do you think would be a good first step? Should I submit a pull request which uses [transformFromAst](https://babeljs.io/docs/en/babel-core#transformfromast) to run `babel-plugin-macros` prior to extracting queries?

**Comment by pieh** [comment]
> Okay, thanks for all of the feedback. What do you think would be a good first step? Should I submit a pull request which uses [transformFromAst](https://babeljs.io/docs/en/babel-core#transformfromast) to run `babel-plugin-macros` prior to extracting queries?

As mentioned in previous comment, we are not sure if we want to commit to that yet, but opening PR that do some postprocessing on AST to "run" babel-plugin-macros will be ok. We could at least release feature tag version of gatsby (`gatsby@extract-queries-with-macros` or something like that) to see how it works without people having to build modified gatsby version locally and evaluate pros/cons of that and other approaches

**Comment by TomerAberbach** [comment]
Sorry for the lack of movement on this issue. I tried to add `babel-plugin-macros` to the file you linked, but couldn't get it to work. I was still ending up with static queries in the code after they were supposed to be extracted.

I haven't had the time to explore further recently. Any ideas or pointers?

**Comment by digitaljohn** [comment]
@TomerAberbach Did you make any progress on this?

**Comment by TomerAberbach** [comment]
> @TomerAberbach Did you make any progress on this?

I finished the macro implementation a long time ago, but I could never figure out how to get Gatsby to replace uses of `StaticQuery` *after* my macro runs (the macro converts uses of `FixedImage` and `FluidImage` to `StaticQuery`). If someone figures that out, then I could make the macro available.
