### ISSUE TITLE
FEATURE: Add way to automatically resize/optimize photos

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#18]
When copying assets to the public folder, optimize images.

**Comment by KyleAMathews** [comment]
Perhaps use this https://github.com/tcoopman/image-webpack-loader

**Comment by pamo** [comment]
I actually have this on my [to-do list](https://github.com/pamo/pamo.github.io/issues/2) but after some consideration and poking around, I realized webpack configuration would be a round-about way to do it. 

Images aren't imported as modules when they're inlined in markdown so webpack doesn't really see them. I'm thinking a [markdown-it plugin](https://www.npmjs.com/browse/keyword/markdown-it-plugin?offset=36) may be the easiest way.

**Comment by KyleAMathews** [comment]
@pamo yeah the image optimization only happens if you require an image which is only a sub-set of the images you have on your site and wouldn't include images that are part of a blog like yours.

I'd like something where I could drop and image in a folder and when copying it'd to `/public` it'd resize + optimize the photo size.

I'll change the title to make more clear what this issue is about.

**Comment by pamo** [comment]
That'd be the best solution. My google-fu was waning yesterday but I'm sure there's something that is capable of it.

**Comment by KyleAMathews** [comment]
Probably this isn't something that should be built into gatsby but that
gatsby provides the hooks to build this in user land.

**Comment by KyleAMathews** [comment]
Shipped solution to this in 0.12 https://github.com/gatsbyjs/gatsby/releases/tag/v0.12.0
