### ISSUE TITLE
[gatsby-source-filesystem] Accessing paths to files in graphql

### ISSUE THREAD

**Issue by benjamingrobertson** [gatsbyjs/gatsby#18001]
## Summary
Recently in a project using gatsby-source-drupal, a client requested the ability to link to PDFs and other documents from within a WYSIWYG. 

My understanding is that gatsby-source-drupal uses gatsby-source-filesystem on to generate file nodes. Looking in the graphql schema, I can see that all files from Drupal have a Gatsby node. However, the schema doesn't have a url I can use to link to the file in Gatsby.

I worked around this by using `createNodeField` inside of `onCreateNode`:

```js
exports.onCreateNode = async ({ node, actions }) => {
  const { createNodeField } = actions;

  // Only run on pdf or docs.
  if (!(node.ext === '.pdf' || node.ext === '.doc' || node.ext === '.docx')) {
    return;
  }

  // Generate the file name.
  const fileName = `${decodeURI(node.name)}-${node.internal.contentDigest}${
    node.ext
  }`;

  // Generate a path.
  const publicPath = path.join(process.cwd(), 'public', 'static', fileName);

  // If the path doesn't exist, copy the file from the cache to a public path.
  if (!fs.existsSync(publicPath)) {
    fs.copyFile(node.absolutePath, publicPath, (err) => {
      if (err) {
        console.error(
          // eslint-disable-line no-console
          `error copying file from ${node.absolutePath} to ${publicPath}`,
          err
        );
      }
    });
  }

  // Add a field to the node with the public path.
  createNodeField({
    node,
    name: 'localUrl',
    value: `/static/${fileName}`
  });
};
```

Would it make sense to implement something like this in [createRemoteFileNode](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createremotefilenode) directly?

**Comment by benjamingrobertson** [comment]
I would be willing to PR this if it makes sense :) Just want to make sure I'm not barking up the wrong tree.

**Comment by benjamingrobertson** [comment]
I'm looking at this again, just because I'm curious :)

I see actually that the functionality I'm describing above exists in `gatsby-source-filesystem` here:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/extend-file-node.js

That to me _looks_ like `gatsby-source-filesystem` should expose a `publicURL` on file nodes created using it.

However, it seems like this logic does not run though when `createRemoteFileNode` is called from `gatsby-source-drupal`, which I think may be a bug? Shouldn't `gatsby-source-filesystem/extend-file-nodes` run for any node created with `gatsby-source-filesystem`?

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

This is due to: https://github.com/gatsbyjs/gatsby/issues/4993
It explains a workaround.

**Comment by benjamingrobertson** [comment]
For posterity:

Adding this to my `gatsby-config.js` plugins list:

```js
{
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/gatsby-config.js`,
      },
    },
```

resolved the issue for me.

Thanks for the tip @LekoArts!!
