### ISSUE TITLE
Wrong slug generated as id when using gatsby-remark-autolink-headers and MDX

### ISSUE THREAD

**Issue by jmolivas** [gatsbyjs/gatsby#18000]
## Description

We are having issues when generating slugs for heading.  We are using MDX 

### Steps to reproduce

Clone repository [mdx-slug](https://github.com/jmolivas/mdx-slug) and execute
```
cd gatsby
npm install
gatsby build --prefix-paths
gatsby serve --prefix-paths
```

### Expected result

The page should generate a slug version of the h2 and h3 text-children as `id` 

### Actual result

The build is generating wrong ids for at least one of the h3 elements

![image](https://user-images.githubusercontent.com/366275/65909800-35d44900-e37e-11e9-8b44-c0df8c23d729.png)

### Environment

```
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 68.0.2
    Safari: 13.0.1
  npmPackages:
    gatsby: ^2.13.18 => 2.15.24
    gatsby-image: ^2.0.33 => 2.2.21
    gatsby-plugin-feed: ^2.0.15 => 2.3.13
    gatsby-plugin-google-analytics: ^2.1.7 => 2.1.17
    gatsby-plugin-manifest: ^2.0.24 => 2.2.18
    gatsby-plugin-mdx: ^1.0.39 => 1.0.44
    gatsby-plugin-react-helmet: ^3.0.9 => 3.1.8
    gatsby-plugin-sharp: ^2.2.6 => 2.2.25
    gatsby-plugin-sitemap: ^2.2.12 => 2.2.14
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-autolink-headers: ^2.1.13 => 2.1.13
    gatsby-remark-copy-linked-files: ^2.1.6 => 2.1.21
    gatsby-remark-embed-markdown: 0.0.4 => 0.0.4
    gatsby-remark-embed-video: ^1.7.1 => 1.7.1
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-github: ^2.0.0 => 2.0.0
    gatsby-remark-heading-slug: ^0.2.0 => 0.2.0
    gatsby-remark-images: ^2.0.6 => 2.0.6
    gatsby-remark-prismjs: ^3.2.5 => 3.3.14
    gatsby-remark-responsive-iframe: ^2.0.10 => 2.2.18
    gatsby-remark-static-images: ^1.1.0 => 1.1.0
    gatsby-source-filesystem: ^2.1.5 => 2.1.26
    gatsby-transformer-json: ^2.1.11 => 2.2.9
    gatsby-transformer-remark: ^2.3.2 => 2.6.24
    gatsby-transformer-sharp: ^2.1.17 => 2.2.17
    gatsby-transformer-yaml: ^2.1.10 => 2.2.10
  npmGlobalPackages:
    gatsby-cli: 2.7.7
```

**Comment by jmolivas** [comment]
We also try with a different approach and same issue appears
We wrote  a react component
```
import React from "react"
import GithubSlugger from 'github-slugger'

const slugger = new GithubSlugger();

export const heading2slugger = props => {
  return <h2 id={slugger.slug(props.children)}>{props.children}</h2>
}

export const heading3slugger = props => {
  return <h3 id={slugger.slug(props.children)}>{props.children}</h3>
}
```
And set those components as  `shortcodes`
```
import { heading2slugger, heading3slugger } from "../components/heading-slugger"

const shortcodes = {
  ...
  h2: heading2slugger,
  h3: heading3slugger,
}

```
Then passed to the `MDXProvider`
```
<MDXProvider components={shortcodes}>
  <MDXRenderer>{node.body}</MDXRenderer>
</MDXProvider>
```
And got the same issue after executing
```
gatsby build --prefix-paths
gatsby serve --prefix-paths
```

**Comment by alexfornuto** [comment]
I can confirm that this issue happens on Fedora 30 as well, Node 10.16.3

**Comment by alexfornuto** [comment]
To test, after building the site locally, review the H2 anchors for /docs/git-faq. Remember to build and serve with `--prefix-paths`, as the issue doesn't occur when not using that flag.

**Comment by alexfornuto** [comment]
It's not stale, it's still an issue!

**Comment by nicklasisraelsson** [comment]
We're also seeing this issue on some of our mdx documents. I haven't been able to pinpoint the pattern exactly but for us it seems to be related to when you have two headers next to each other with no content in between:

```
## header1
### header2
```

Then the ids for some headers after that can get mixed up.

**Comment by alexfornuto** [comment]
@nicklasisraelsson thanks for sharing! In [this PR](https://github.com/pantheon-systems/documentation/pull/5366) I went and added a new line between all H2s and H3s. It solved the issue for [Git FAQ](https://tocfix-static-docs.pantheonsite.io/docs/git-faq), but I'm still getting bad anchor links [here](https://tocfix-static-docs.pantheonsite.io/docs/wordpress-solr#install-and-configure-plugin).

So their's either more than one cause, Or I'm missing something obvious. If we can nail it down, I'd be happy to PR an update to Gatsby's docs where appropriate.

**Comment by alexfornuto** [comment]
My [workaround](https://github.com/gatsbyjs/gatsby/issues/18000#issuecomment-560521374) is holding strong. The fix may be to improve documentation around Markdown headers, indicating a need for spacing.
