### ISSUE TITLE
Tailwind docs: Recompile every change?

### ISSUE THREAD

**Issue by beamercola** [gatsbyjs/gatsby#18013]
## Summary

Followed the tailwind guide, but i'm having to reload `gatsby develop` every time i change a class to a class I haven't used before (like it's compiling tailwind file)

## Relevant information

Followed this:
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/tailwind-css.md

### Environment (if relevant)

  System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Safari: 13.0.1
  npmPackages:
    gatsby: ^2.13.31 => 2.15.20 
    gatsby-image: ^2.0.23 => 2.2.20 
    gatsby-plugin-netlify: ^2.0.6 => 2.1.15 
    gatsby-plugin-netlify-cms: ^4.1.6 => 4.1.17 
    gatsby-plugin-postcss: ^2.1.10 => 2.1.10 
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.1.8 
    gatsby-plugin-sass: ^2.0.7 => 2.1.15 
    gatsby-plugin-sharp: ^2.2.9 => 2.2.25 
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.1.20 
    gatsby-remark-images: ^3.1.6 => 3.1.23 
    gatsby-remark-relative-images: ^0.2.1 => 0.2.3 
    gatsby-source-filesystem: ^2.0.26 => 2.1.26 
    gatsby-transformer-remark: ^2.6.9 => 2.6.24 
    gatsby-transformer-sharp: ^2.1.9 => 2.2.16 
  npmGlobalPackages:
    gatsby-cli: 2.7.53
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by dbrookes** [comment]
Looks like you're using Gatsby Plugin Purgecss, you probably don't want that running in development so I'd check if you have `develop: true` in the options for this plugin?

**Comment by beamercola** [comment]
@dbrookes thanks for the reply here's my config:

```
    {
      resolve: 'gatsby-plugin-purgecss', // purges all unused/unreferenced css rules
      options: {
        develop: true, // Activates purging in npm run develop
        purgeOnly: ['/all.css'], // applies purging only on the bulma css file
      },
    }
```

**Comment by dbrookes** [comment]
Try set `develop: false` and then you should be able to use any tailwind classes in develop without rebuilding - any classes you haven't used will still be removed from the final bundle when you run `gatsby build`

**Comment by beamercola** [comment]
@dbrookes that fixed it!  so it's fine to leave it this way?  I don't need to change anything for production?

thank you.

**Comment by dbrookes** [comment]
You don't need to change anything for production, but keep in mind that Purgecss will only run when you run `gatsby build` so you should check everything looks ok with `gatsby serve` or on your staging environment. If it has broken the styles of any third party libraries you can follow the steps here to whitelist them:

https://www.gatsbyjs.org/packages/gatsby-plugin-purgecss/#help-purgecss-breaks-my-site
