### ISSUE TITLE
gatsby-plugin-sitemap - siteMetdata/siteUrl error when building locally

### ISSUE THREAD

**Issue by bloodbee** [gatsbyjs/gatsby#18024]
## Description

When i try to build this repo https://github.com/bloodbee/website locally after a npm install, i got a error about gatsby-plugin-sitemap and that the siteUrl in siteMetadata is not set.

### Steps to reproduce

1) Clone the repo
2) npm install
3) npm run build

### Expected result

The script npm run build should be executed properly

### Actual result

Error about gatsby-plugin-sitemap

### Environment

System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.11.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 3.7.3 - /Users/mathieudufour/anaconda3/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 13.0.1
  npmPackages:
    gatsby: ^2.15.9 => 2.15.28
    gatsby-image: ^2.0.28 => 2.2.23
    gatsby-link: ^2.0.8 => 2.2.17
    gatsby-plugin-catch-links: ^2.0.9 => 2.1.12
    gatsby-plugin-feed: ^2.0.11 => 2.3.15
    gatsby-plugin-google-analytics: ^2.0.9 => 2.1.19
    gatsby-plugin-manifest: ^2.0.29 => 2.2.20
    gatsby-plugin-netlify: ^2.1.11 => 2.1.17
    gatsby-plugin-netlify-cms: ^3.0.9 => 3.0.18
    gatsby-plugin-offline: ^3.0.11 => 3.0.11
    gatsby-plugin-page-transitions: ^1.0.7 => 1.0.8
    gatsby-plugin-react-helmet: ^3.0.5 => 3.1.10
    gatsby-plugin-robots-txt: ^1.4.0 => 1.5.0
    gatsby-plugin-sass: ^2.1.17 => 2.1.17
    gatsby-plugin-sharp: ^2.2.27 => 2.2.27
    gatsby-plugin-sitemap: ^2.0.4 => 2.2.16
    gatsby-remark-copy-linked-files: ^2.0.8 => 2.1.23
    gatsby-remark-images: ^3.0.1 => 3.1.25
    gatsby-remark-prismjs: ^3.2.0 => 3.3.16
    gatsby-remark-relative-images: ^0.2.1 => 0.2.3
    gatsby-remark-responsive-iframe: ^2.0.8 => 2.2.20
    gatsby-remark-smartypants: ^2.1.11 => 2.1.11
    gatsby-source-filesystem: ^2.1.28 => 2.1.28
    gatsby-transformer-remark: ^2.2.0 => 2.6.26
    gatsby-transformer-sharp: ^2.1.10 => 2.2.19
  npmGlobalPackages:
    gatsby-cli: 2.7.53

Thank you for your answers about this issue, I can't push any build to netlify and can't modify my website in accordance.
Cheers.

**Comment by BALAJIRAO676** [comment]
Refer https://github.com/alxshelepenok/gatsby-starter-lumen/issues/199#issue-438047721 
It is very similar issue . Hope you get it.

**Comment by bloodbee** [comment]
Looks like the proposed solution in the other issue can resolve my problem. Thanks for the refer !

**Comment by kay-o** [comment]
for those coming across the above suggested solution, I notice the documentation for `gatsby-plugin-sitemap` now includes a recommended approach: https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/#resolveSiteUrl
