### ISSUE TITLE
Cache with Contentful is too aggressive? Cache needs clear on every change to data

### ISSUE THREAD

**Issue by DmacTorstar** [gatsbyjs/gatsby#18030]
## Description

When I add any new data to contentful, change any field, change any model, make any update whatsoever, including changing one of the graphql queries on the gatsby side, I need to stop the dev server, run gatsby clean and then restart. 

Is this normal? If so, it seems way too aggressive of a caching strategy and makes development extremely tedious. 

### Steps to reproduce

- Run code official code generator to create code, push to github, and setup contentful space.
- Run npm install
- Run gatsby develop
- Make change in contentful
- Changes not reflected in graphqli or visually

---
- Make change in graphql query
- Change is not applied in the app
----

- gatsby clean
- new data is reflected in graphqli and on screen
- any new page query changes are now reflected

### Expected result

When I update a query locally, or change the data in contentful, I should be able to fetch the new data

### Actual result

Data does not change.
No new nodes appear, no changes to existing nodes appear.

### Environment

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.17.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - /c/Python27/python
  Browsers:
    Edge: 44.17763.1.0

**Comment by DmacTorstar** [comment]
Found this semi-solution to this problem:


Just asked this question myself.
https://www.gatsbyjs.org/docs/environment-variables/#reserved-environment-variables

`ENABLE_GATSBY_REFRESH_ENDPOINT=true`

```
 curl -X POST http://localhost:8000/__refresh
```

I really think this should be easier to achieve. Perhaps a 'Refresh Data' button attached in graphiql editor, or something. Maybe a config value to ping this hook on every page refresh by default in development.

**Comment by LekoArts** [comment]
Thank you for opening this!

> Is this normal? If so, it seems way too aggressive of a caching strategy and makes development extremely tedious.

Yes, it is working as expected. It's not really a question about caching things but about inferring and constructing the GraphQL schema. That only happens during the bootstrap and hence you need to restart the development server. As you have already discovered there is an endpoint you can POST to -- some source plugins like from Sanity.io already use that and it's our current solution to the problem.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Comment by braianj** [comment]
Hello. Is there a work around for update data in contentful a see the changes in production without creating a build of using the refresh?
