### ISSUE TITLE
How could I add a language 'switcher' to the 'using-i18n' example?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#18033]
Hi Gatsby and @LekoArts,

I decided to open a new issue as a question so as to try and figure this out. I downloaded the `gatsby-master` folder and copied the 'using-i18n' example to try to learn how to add mdx multi-lingual blog functionality to a site that I am working on. Everything is great up until I click on one of the language links. Instead of switching languages on the same page, which is my expected behavior, I am taken back to the homepage of that language. Check out the example site to see what I mean. Click on a blog post, then click the opposite language and you will be taken back to the homepage, rather than staying on that blog post:

https://using-i18n.netlify.com/

I reported this as a bug in another issue, but @LekoArts informed me that he made it this way intentionally to keep the example as simple as possible, which I can appreciate.

But I do need the functionality of a 'language switcher' so as to not force my user out of their current context, disorienting their user experience. So if @LekoArts and/or anybody else can help me figure out how to implement something like this, I would be most appreciative :-)

As a reference, this is how language switching is implemented in the `using-i18n` example currently:

```jsx
<Link to="/" hrefLang="en">
  English
</Link>
{` `}/{` `}
<Link to="/de" hrefLang="de">
  Deutsch
</Link>
```

...which are just straightforward links, and I want to do something along these lines:

```jsx
{({ languages, language: currentLocale }) =>
  languages.map(language => (
    <button
      key={language}
      onClick={() => changeLocale(language)}
    >
      {languageName[language]}
    </button>
  ))
}
```

...which is an example from `gatsby-plugin-intl`, which does not currently support multi-language blogs, only pages.

Thank you! 🤗

**Comment by onestopjs** [comment]
The way I do it in my localization plugin is the following:
1.I get the current path
2. Trim the language part from the current path
3. Redirect to the trimmed path, prefixed by the new language. 

Here is [an example](https://github.com/onestopjs/gatsby-theme-localization/blob/a415f18452e89d0b5d28fdaa7f3019baf7aa46a6/gatsby-theme-localization/src/wrap-root.tsx#L47) of how I currently do it. 

Keep in mind that the logic for trimming the language is flawed (I am currently refactoring it).

**Comment by muescha** [comment]
thats also interesting for the current translation process https://github.com/gatsbyjs/gatsby/projects/15 

#17759 Change routing to support localizations
#17776 Language Toggel UI


on #17776 there are some examples and drafts
