### ISSUE TITLE
Update page-data.json without redeploy.

### ISSUE THREAD

**Issue by universse** [gatsbyjs/gatsby#18037]
According to [Caching Static Sites](https://www.gatsbyjs.org/docs/caching/) docs, it’s possible page-data.json files to be updated even without a redeploy. Just wondering how it's done.

> ## Page data
>
> Similar to HTML files, the JSON files in the public/page-data/ directory should never be cached by the browser. **In fact, it’s possible for these files to be updated even without doing a redeploy of your site.** Because of this, browsers should be instructed to check on every request if the data in your application has changed.

**Comment by DmacTorstar** [comment]
Just asked this question myself.
https://www.gatsbyjs.org/docs/environment-variables/#reserved-environment-variables

`ENABLE_GATSBY_REFRESH_ENDPOINT=true`

```
 curl -X POST http://localhost:8000/__refresh
```

I really think this should be easier to achieve. Perhaps a 'Refresh Data' button attached in graphiql editor, or something. Maybe a config value to ping this hook on every page refresh by default in development.

**Comment by universse** [comment]
Yeah that's a good suggestion.

Anw I was asking about production environment actually since the linked docs is talking about deployed sites.

**Comment by jamesvidler** [comment]
I'm using the __refresh endpoint while running my site using 'gatsby develop' and it refreshes source nodes just fine, but doesn't refresh page-data.json for page context data unless I stop and start development mode again.

Is this a bug or intended functionality? Ideally I want to replace the existing page-data.json

**Comment by janedzumerko** [comment]
Hey, did someone manage to update page-data.json on production build without redeploying?
