### ISSUE TITLE
Improve core support for Gatsby as a static page generator

### ISSUE THREAD

**Issue by xavivars** [gatsbyjs/gatsby#18046]
## Introduction

Gatsby is defined as a _static site generator_, or even more, as a _static PWA generator_, as its described in gatsbyjs.org. That means is meant to be used to build full websites<sup>1</sup>, that completely own the URL namespace.

<sup>1</sup> It allows building also "subfolders" within a website, but it would still own routing & URLs in that folder.

However, Gatsby can be (and actually is) used also as a _static page generator_: the gatsby app generates a set of HTML pages that are exposed to internet not directly, but with a proxy in between (like nginx or Zalando's [Skipper](https://opensource.zalando.com/skipper/)).

Let me show a couple of scenarios of what I mean by _static page generation_. Let's take this Gatsby app

```
.
└── gatsby-app/
    ├── en-US/
    │   ├── color/
    │   └── weight/
    ├── en-UK/
    │   ├── color/
    │   └── weight/
    └── en-US/
        ├── color/
        └── weight/
```

We want to expose this page into 3 different domains, one for each language:

```
.
├── example.com/
│   ├── color/
│   └── weight/
├── example.co.uk/
│   ├── colour/
│   └── weight/
└── example.es/
    ├── color/
    └── peso/
```

In this scenario, we can just set up a Nginx in front of our deployed Gatsby app, mapping the appropriate domains to the right folder (`.com`->`en-US`, etc.) In this example, you also see that URL localization is taken care at proxy-level, and not at Gatsby.

This approach doesn't benefit of one of the features Gatsby provides: fast client-side-routed web applications, and resource-prefetching. But in some cases, where each team owns a "vertical slice" of a website, this "hyperlink integration"<sup>2</sup>

<sup>2</sup> Term and image _stolen_ from [David Leitner](http://leitner.io/)'s tallk [Micro Frontends – A Strive for Fully Verticalized Systems](https://speakerdeck.com/duffleit/microfrontends-a-strive-for-fully-verticalized-systems-a8fe393b-0247-42cd-b4e2-62ba3eeb460b?slide=22)

![image](https://user-images.githubusercontent.com/134083/66045289-b4b6b680-e523-11e9-9083-370d3dc3f7c8.png)

```
.
└── example.com/
    ├── product-1/  -> gatsby.example.com/gatsbyapp/product-1/index.html
    ├── product-2/  -> gatsby.example.com/gatsbyapp/product-2/index.html
    ├── dasboard/   -> dasboard.ui.example.com/designer.php
    └── cart/       -> cart.ui.example.com/cart.aspx
```

In this example, both product pages (the whole product catalog) are generated by the same gatsby app, but the dashboard is generated by a PHP application, and the cart is powered by a C# application. And they all coexist within the same URL namespace, so the integration is using standard hyperlinks.

## (feature?) request

As I mentioned previously, this feature is already possible by using Gatsby `assetPrefix` functionality and [a (3rd party?) plugin](https://github.com/wardpeet/gatsby-plugin-static-site), created originally by @wardpeet.

The plugin takes care of two things: 

- Disable `reach-router`, so all navigation events are actually server requests
- Override `publicLoader`, so pageResources get downloader from the right URL.

The problem, though, is that the pluging is extremely fragile:

- Changes that appear simple, like [changing how reach router is included](https://github.com/gatsbyjs/gatsby/pull/13197/files/931c911c59f876639b0cfddfd5a5a1a5acc2f1b4#diff-c4777e791f64fbb6c82255341b381dab) can break the plugin. 
- Other bigger changes like the "per-page manifest" also break this plugin.

And the reason for that fragility is that the plugin really changes and relies in _deep_ implementation details, and not public APIs.

After a conversation in September 25th Community Meeting ([see notes](https://docs.google.com/document/d/1VfDVFzwvRLjC7J4Ym44NCpZ_G8rIfuHvhn32K4cFqWI/edit)), I decided to document the challenges here, so it can be discussed from _core_ point of view if *there's a desire to support all (or some) of the features needed to use Gatsby as a _static page generator_ directly from core*, either via configuration flags, or via official plugins (that will break when a breaking change is implemented) that will extremely simplify keeping plugins up to date with gatsby core.

**Comment by LekoArts** [comment]
Sorry, but we currently have no interest in taking this request further. We'd love to hear stories from people who would like to use Gatsby this way and why they want to use it this way. Then we could maybe revisit this topic again if there is enough community interest. Thanks for the issue and the write-up though!
