### ISSUE TITLE
Preact routing doesn't work well

### ISSUE THREAD

**Issue by dtroode** [gatsbyjs/gatsby#18044]
## Description

When I click on link (Gatsby Link component), URL in searchbar is changing, but page doesn't change

### Steps to reproduce

- Install Preact (using official plugin [instruction](https://www.gatsbyjs.org/packages/gatsby-plugin-preact/))
- Use a Link component on the page
- Run build command
- Click on the link

### Expected result

URL changes and new page appears.

### Actual result

Page remains, but you'll get a new URL.

### Environment

```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16
  Browsers:
    Edge: 44.18362.329.0
  npmPackages:
    gatsby: ^2.9.4 => 2.13.50
    gatsby-image: ^2.1.4 => 2.2.8
    gatsby-plugin-feed: ^2.2.3 => 2.3.6
    gatsby-plugin-manifest: ^2.1.1 => 2.2.4
    gatsby-plugin-offline: ^2.1.3 => 2.2.4
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.2
    gatsby-plugin-sass: ^2.1.0 => 2.1.4
    gatsby-plugin-sharp: ^2.1.5 => 2.2.9
    gatsby-plugin-sitemap: ^2.1.0 => 2.2.5
    gatsby-plugin-twitter: ^2.1.2 => 2.1.2
    gatsby-remark-images: ^3.0.16 => 3.1.7
    gatsby-remark-prismjs: ^3.3.1 => 3.3.4
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-remark-responsive-iframe: ^2.2.8 => 2.2.8
    gatsby-source-filesystem: ^2.0.39 => 2.1.8
    gatsby-transformer-remark: ^2.5.0 => 2.6.10
    gatsby-transformer-sharp: ^2.1.21 => 2.2.5
```

**Comment by mendaomn** [comment]
Hey, can you help me reproduce the problem? I've created a codesandbox to help with this but it does seem to work fine: https://codesandbox.io/embed/gatsby-starter-default-bs57n

Did I get anything wrong?

**Comment by dtroode** [comment]
I've solved this. Changed version of Preact in dependencies manually. Gatsby need just to update plugin with stable Preact X. Now Gatsby is using rc.3 beta version with this issue. Closing. Thanks to answer
