### ISSUE TITLE
Netlify deploy: Error #85907 GRAPHQL

### ISSUE THREAD

**Issue by TomFevrier** [gatsbyjs/gatsby#18042]
Hi there!

**Note: Updated with a link to my entire Gatsby project**

I have an issue when deploying my Gatsby project on Netlify, with the following error:

```
12:45:01 PM: error #85907 GRAPHQL
12:45:01 PM: There was an error in your GraphQL query:
12:45:01 PM: - Unknown argument 'relativePath'. Source: document `optBuildRepoSrcComponentsImageJs2969191536` file: `GraphQL request`
12:45:01 PM: File: src/templates/publisher.js
```

Here is the content of `src/templates/publisher.js`:
```
import React from 'react';
import { graphql } from 'gatsby';
import Layout from '../components/layout';
import SEO from '../components/seo';
import ProjectPreview from '../components/project-preview';

import styles from '../pages/index.module.css';

const PublisherTemplate = ({ data }) => (
	<Layout>
		<SEO title={data.strapiPublisher.name} />
		<h1>{data.strapiPublisher.name}</h1>
		<ul className={styles.grid}>
			{data.strapiPublisher.projects.map(node => (
				<li key={node.id} className={styles.item}>
					<ProjectPreview {...node} />
				</li>
			))}
		</ul>
	</Layout>
);

export default PublisherTemplate;

export const query = graphql`
	query PublisherTemplate($id: String) {
		strapiPublisher(id: { eq: $id }) {
			id
			name
			projects {
				id
				slug
				title
				date
				link
				featured_image {
					childImageSharp {
						fluid(maxWidth: 600) {
							...GatsbyImageSharpFluid
						}
					}
				}
			}
		}
	}
`;
```

Here is the entire project: https://github.com/tomfevrier/portfolio

### Environment

- **System:**
  - OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
  - CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  - Shell: 5.4.2 - /usr/bin/zsh
- **Binaries:**
  - Node: 10.16.3 - /usr/bin/node
  - npm: 6.9.0 - /usr/bin/npm
- **Languages:**
  - Python: 2.7.15+ - /usr/bin/python
- **Browsers:**
  - Firefox: 69.0.1
- **npmPackages:**
  - gatsby: ^2.13.73 => 2.13.73 
  - gatsby-image: ^2.2.10 => 2.2.10 
  - gatsby-plugin-manifest: ^2.2.6 => 2.2.6 
  - gatsby-plugin-offline: ^2.2.7 => 2.2.7 
  - gatsby-plugin-react-helmet: ^3.1.4 => 3.1.4 
  - gatsby-plugin-sharp: ^2.2.13 => 2.2.13 
  - gatsby-plugin-transition-link: ^1.12.4 => 1.12.4 
  - gatsby-source-filesystem: ^2.1.11 => 2.1.11 
  - gatsby-source-strapi: 0.0.9 => 0.0.9 
  - gatsby-transformer-sharp: ^2.2.7 => 2.2.7 
- **npmGlobalPackages:**
  - gatsby-cli: 2.4.8

My intuition is that it has something to do with gatsby-image but I don't know what `relativePath` refers to... Any idea? Thanks.

**Comment by pahosler** [comment]
try this, it's similar to the example in the plugin docs

```js
export const query = graphql`
	query PublisherTemplate($id: String) {
		allStrapiPublisher(id: { eq: $id }) {
      edges {
        node {
          id
          name
          projects {
	          id
	          slug
	          title
	          date
	          link
	          featured_image {
		          childImageSharp {
			          fluid(maxWidth: 600) {
				          ...GatsbyImageSharpFluid
			          }
		          }
	          }
          }    
        }
      }
    }
  }
;`
```

**Comment by sidharthachatterjee** [comment]
@TomFevrier Thank you for opening this and apologies for not being able to take a look at this earlier. 

We just took a look at this. The reason you aren't able to query with a `relativePath` argument is because

- Your config an instance of `gatsby-source-filesystem` for the `public/static` directory
- The directory doesn't have any images
- Therefore Gatsby doesn't generate the right schema

A simple fix for this is to include an image in there. We've gone ahead and done that for you in https://github.com/TomFevrier/portfolio/pull/1

Thank you once again! Closing this for now.

**Comment by TomFevrier** [comment]
Thank you for the pull request. However Netlify still gives me a similar error on deployment:
```
3:57:52 PM: error There was an error in your GraphQL query:
3:57:52 PM: - Unknown field 'childImageSharp' on type 'StrapiProjectFeatured_image'. Source: document `Projects` file: `GraphQL request`
```
I must precise that Gatsby builds successfully locally, the issue only occurs on deployment. Is there an issue with Netlify and gatsby-image?

Looking forward to hearing from you!

> @TomFevrier Thank you for opening this and apologies for not being able to take a look at this earlier.
> 
> We just took a look at this. The reason you aren't able to query with a `relativePath` argument is because
> 
> * Your config an instance of `gatsby-source-filesystem` for the `public/static` directory
> * The directory doesn't have any images
> * Therefore Gatsby doesn't generate the right schema
> 
> A simple fix for this is to include an image in there. We've gone ahead and done that for you in [TomFevrier/portfolio#1](https://github.com/TomFevrier/portfolio/pull/1)
> 
> Thank you once again! Closing this for now.

**Comment by TomFevrier** [comment]
I'm sorry but I don't see how my issue relates to [the new issue you raised](https://github.com/gatsbyjs/gatsby/issues/18804)... I am not using the `File` type, just unable to deploy my website because of some issue with gatsby-image...

**Comment by TomFevrier** [comment]
When removing the `gatsby-source-filesystem` plugin (which I actually don't need), I now get the following error:
```
11:00:02 AM: error There was an error in your GraphQL query:
11:00:02 AM: - Unknown field 'file' on type 'Query'. Source: document `optBuildRepoSrcComponentsImageJs2969191536` file: `GraphQL request`
```
Found [a similar issue](https://github.com/gatsbyjs/gatsby/issues/16321) but no solution had been brought... Do you know how to solve this?

**Comment by TomFevrier** [comment]
Hello again!

Turns out my issue is not specifically with Netlify...
Whenever I try to run Gatsby using the Strapi deploy URL (on Heroku) instead of the localhost URL, I get the same errors: (`Cannot query field "childImageSharp" on type "StrapiPublisherProjectsFeatured_image"`).

Can you help me with that?

**Comment by julietrubin** [comment]
I'm having the same issue. Did you find a solution?

**Comment by julietrubin** [comment]
I ran into this issue as well. The fix was to remove the quotes around the api_token value in Netlify.
