### ISSUE TITLE
doc: rename `Life and times of a Gatsby build` to `Overview of the Gatsby Build Process`

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#18050]
## Summary

Rename the title of this doc to match better the content.

### Basic example

rename from: `Life and times of a Gatsby build` 
rename to: `Overview of the Gatsby Build Process`

### Motivation

We should consider a more descriptive title that will make it easier to understand when you see it in the site navigation, a link from social media, surfaced in search (on site and search engines), or when translated to a different language.

"Overview of the Gatsby Build Process" or something similar may satisfy those checkboxes

### related Steps

The stub has been open for a while, so it will need a redirect, too.

### related Issue

suggested by @hashimwarren https://github.com/gatsbyjs/gatsby/pull/17915#issuecomment-537456713

**Comment by dav3evans** [comment]
Is this up for grabs? Happy to take a look! 🤘

**Comment by muescha** [comment]
it is still open for discussion by core / doc team

**Comment by dav3evans** [comment]
Ok no worries, I'll avoid jumping the gun before a title is settled on :)

**Comment by gillkyle** [comment]
Sounds like a good change and I trust @hashimwarren has a solid grasp on what's good to update for the site for discoverability so go ahead and feel free to open a PR @dav3evans 🙂 

I just marked this issue as Hacktoberfest - Claimed

**Comment by dav3evans** [comment]
Thanks guys, I'll get this sorted for you later today!

**Comment by sidharthachatterjee** [comment]
Thank you all of you!
