### ISSUE TITLE
Disable Logs On Gatsby Build Option

### ISSUE THREAD

**Issue by Skillz4Killz** [gatsbyjs/gatsby#18062]
## Summary

`gatsby build --silent` option to disable all logs on gatsby build.

### Basic example

https://community.netlify.com/t/large-build-log-has-huge-impact-on-build-time/1489

### Motivation

Netlify recently has begun implementing limits to Total Build Times used in a month. In order to optimize this I am hoping an option can be added to make the logs in gatsby build be silent.

**Comment by Everspace** [comment]
Everything but errors is pretty common, or keeping log regurgitation to a minimum. The default gatsby stuff is pretty small

```
10:16:03 AM: yarn run v1.3.2
10:16:03 AM: $ gatsby build
10:16:08 AM: success open and validate gatsby-configs — 0.048
10:16:09 AM: success load plugins — 0.778
10:16:09 AM: success onPreInit — 0.173
10:16:09 AM: success delete html and css files from previous builds — 0.026
10:16:09 AM: success initialize cache — 0.030
10:16:09 AM: success copy gatsby files — 0.053
10:16:09 AM: success onPreBootstrap — 0.045
10:16:10 AM: success source and transform nodes — 0.517
10:16:10 AM: success building schema — 0.530
10:16:10 AM: success createPages — 0.108
10:16:10 AM: success createPagesStatefully — 0.059
10:16:11 AM: success onPreExtractQueries — 0.020
10:16:11 AM: success update schema — 0.062
10:16:11 AM: success extract queries from components — 0.317
10:16:11 AM: success write out requires — 0.022
10:16:11 AM: success write out redirect data — 0.024
10:16:11 AM: success onPostBootstrap — 0.020
10:16:11 AM: info bootstrap finished - 7.481 s
10:16:11 AM: success run static queries — 0.027 — 1/1 99.70 queries/second
10:16:11 AM: Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
10:16:25 AM: success Building production JavaScript and CSS bundles — 13.927
10:16:25 AM: success Rewriting compilation hashes — 0.085
10:16:26 AM: success run page queries — 0.598 — 17/17 29.84 queries/second
10:16:27 AM: success Building static HTML for pages — 1.605 — 17/17 52.46 pages/second
10:16:27 AM: info Done building in 23.951 sec
10:16:28 AM: Done in 24.35s.
```

If you want to run silently, `gatsby build > /dev/null` to your heart's content. I have noticed some plugins like to write stuff to the console, so I would investigate those, or your internal log-spew first.

**Comment by Skillz4Killz** [comment]
After much testing, it seems to have negligble impact on build times. Gonna close this issue.

**Comment by DipeshMaywade** [comment]
Hii, this `gatsby build --silent` is not working is there any other way to  Disable console logs while runing gatsby build command

**Comment by chrisclose-nib** [comment]
I changed my build step to pipe to `cat`, it reduced the log size in buildkite from 2.5MB to 50kb.
Alongside and `--no-color` option, can we please have a `--plain` or something similar?
I suspect the spinning progress icon is causing some issues.
