### ISSUE TITLE
Write content in YAML and MDX for everything in 'using-i18n', and everywhere else as well...

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#18063]
So,

Ideally I would be able to write all content and translations, configuration, etc, in YAML and MDX. I would also want to be able to write translations for each page in different files, rather than having one giant JSON file, which becomes really difficult very quickly. YAML would be for when every piece of content on a page has a key: value pair, and MDX when it's an article of other longer form content. Obviously frontmatter could be used for key value pairs, except for when I would like to create an array of objects, which I believe would require YAML.

Anyway, just putting this idea out there in the hopes that others have this desire and might have knowledge as to how to go about it :-)

Thanks! XD

**Comment by CanRau** [comment]
I do it like this
```
- content
-- blog
--- first-post
---- en.mdx
---- de.mdx
```
then in `gatsby-node.js` I add a node field containing the language, stuffing it alongside the slug in pageContext then using it and the slug to query the specific page. The slug is made up of `/langcode/title` like `/de/first-post` 
You can do the same for your non article pages, I think I'd still use mdx just in case or you could go the YAML route and if needed include a mdx for longer content in your .yml, at least that was possible with gatsby-transformer-remark, think it should work but haven't tried it with the mdx plugin so far I guess

Let me know if that makes any sense.

Here's on [example](https://github.com/GaiAma/gaiama.org/blob/master/gatsby/createPages.js), a little messy though

**Comment by rchrdnsh** [comment]
hmmmmm, yeah, sort of :-) So, what are you using for your site-wide translations? I'm currently using `gatsby-plugin-intl` so would this approach using mdx work with that? If I need to switch it up, I don't mind. I don't mind using mdx for the page content as well, as they are functionally equivalent, at least at this point.

**Comment by rchrdnsh** [comment]
I too would like to structure the content like you have, as follows:

```
src
-content
--blog
---post-1
----en.mdx
----vn.mdx
--pages
---index
----en.mdx
----vn.mdx
```

where the content in the blog would be inserted into generated pages and the content in the pages folder would be inserted into pages in the pages folder.

**Comment by CanRau** [comment]
I don't use any additional i18n plugin everything lives in `.yml`'s and `.mdx`'s. Works pretty good so far, I just query them like [here](https://github.com/GaiAma/gaiama.org/blob/master/src/templates/AboutPage.js#L377) for example which I then use like [this](https://github.com/GaiAma/gaiama.org/blob/master/src/templates/AboutPage.js#L86)

I think there are now i18n plugins available doing proper pre-rendering/SSR but at the time I made that site I think all of them would only work in the browser defating the purpose of Gatsby kind of..

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
