### ISSUE TITLE
404 / Not found for a single URL in deployment

### ISSUE THREAD

**Issue by metamn** [gatsbyjs/gatsby#18075]
## Description

I have around 20 articles on my blog. A single article is returning a 404 error when deployed. The rest of the articles all work fine. That single article also works fine in development. 

### Steps to reproduce

1. Clone the repo: https://github.com/metamn/react/releases/tag/v0.0.1
2. Run it locally
3. Check that this article works fine: http://localhost:8001/react-follows-the-functional-reactive-programming-paradigm/
4. Deploy (to Github Pages)
5. See that http://metamn.io/react/react-follows-the-functional-reactive-programming-paradigm/ gives a 404 error 

### Expected result

That article should work well as on localhost.

### Actual result

- First the article is loaded for around 0.5 seconds. Then it is replaced with a 404 error page.
- In the `Inspector/Network` tab there is a 404 GET error unable to return `http://metamn.io/react/page-data/-follows-the-functional-reactive-programming-paradigm/page-data.json` This URL is flawed. A `react` prefix is removed.  It should look like `http://metamn.io/react/page-data/react-follows-the-functional-reactive-programming-paradigm/page-data.json`

![Screenshot from 2019-10-03 12-05-56](https://user-images.githubusercontent.com/86295/66114015-9eb5fe00-e5d6-11e9-889a-1bc9e06a6c54.png)

### Notes

- This bug was also investigated in https://github.com/gatsbyjs/gatsby/pull/17412
- It appeared after adding https://www.gatsbyjs.org/packages/gatsby-plugin-draft/?=draft
- Since then the plugin is removed, cache cleared, the post renamed two times, other new posts were added, the `gh-pages` branch was completely removed and the whole site redeployed -- and still the error persists.

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7Y54 CPU @ 1.20GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 69.0.1
  npmPackages:
    gatsby: ^2.15.22 => 2.15.28 
    gatsby-image: ^2.2.23 => 2.2.23 
    gatsby-plugin-feed: ^2.3.15 => 2.3.15 
    gatsby-plugin-google-analytics: ^2.1.19 => 2.1.19 
    gatsby-plugin-manifest: ^2.2.20 => 2.2.20 
    gatsby-plugin-offline: ^3.0.11 => 3.0.11 
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10 
    gatsby-plugin-sharp: ^2.2.27 => 2.2.27 
    gatsby-plugin-typography: ^2.3.10 => 2.3.10 
    gatsby-remark-copy-linked-files: ^2.1.23 => 2.1.23 
    gatsby-remark-images: ^3.1.25 => 3.1.25 
    gatsby-remark-prismjs: ^3.3.16 => 3.3.16 
    gatsby-remark-responsive-iframe: ^2.2.20 => 2.2.20 
    gatsby-remark-smartypants: ^2.1.11 => 2.1.11 
    gatsby-source-filesystem: ^2.1.28 => 2.1.28 
    gatsby-transformer-remark: ^2.6.26 => 2.6.26 
    gatsby-transformer-sharp: ^2.2.19 => 2.2.19 
  npmGlobalPackages:
    gatsby-cli: 2.7.53

**Comment by dantereve** [comment]
Hello, I've checked your troubleshooting page this morning. 
When you load the page, your content is flashing, then disappears to show your 404 page. 

<img width="968" alt="Screenshot 2019-10-06 at 09 02 34" src="https://user-images.githubusercontent.com/13101343/66265541-c5fc0d80-e818-11e9-84ca-edd39d1ee6ba.png">

In those logs, the culprit seems to be in `loader.js` : 

```js
const doFetch = (url, method = `GET`) =>
  new Promise((resolve, reject) => {
    const req = new XMLHttpRequest()
    req.open(method, url, true)
    req.onreadystatechange = () => {
      if (req.readyState == 4) {
        resolve(req)
      }
    }
    req.send(null)
  })
}
```

For some obscure path mismatching reason `doFetch()` is returning `null` and smash the preloaded data from link preload out of the way to display the 404. 

I can't quite get why this path and only this one is being chopped this way, though ... Can this be related to some weird issues with GitHub Pages support?

**Comment by metamn** [comment]
For now I've re-added the article with a different title and date, and removed the old one. http://metamn.io/react/the-reactive-fuctional-nature-of-react/ Now all works fine.

If someone wants to fix this bug the original state is preserved in this tag: https://github.com/metamn/react/releases/tag/v0.0.1

Thank you!
