### ISSUE TITLE
Gatsby-image loading='eager' && critical is not loading as expected

### ISSUE THREAD

**Issue by D19cannon** [gatsbyjs/gatsby#18109]
## Summary
Hi guys,
I've been running into a small problem regarding the loading property. According to the documentation **loading** is basically replacing the **critical** and to keep it simple I've been trying to apply both. But the result that I am looking for ain't displaying the way I expect it to. The same goes with all the solved issues that I found. 

When I am using the props according to the documentation I get to a point that the image is half blurred out and fully loaded a second or two later. I wish to load the image fully on page load. See the image in the attachment.

<img width="1680" alt="Screenshot 2019-10-04 at 12 21 12" src="https://user-images.githubusercontent.com/14916043/66196624-8b239980-e6a1-11e9-989b-2b6bd2fa31f9.png">

https://www.gatsbyjs.org/packages/gatsby-image/

## Relevant information
Some designers wish to remove the lazy loading so I tried the following:
`<Img src={img.src} fluid={img} loading="eager" fadeIn={false} critical />`

I have gone through a ton of issues and it mentioned that the problem was solved in v2.2.15. I am currently using the latest v2.2.23, but having the same issues. I've also gone through the commitment and as far as I can it is done the correct way. Although, I am suspecting that **critical** has been removed in an earlier version.

Also, some people mentioned that it worked for them in the build but on with the Gatsby develop mode. In my case neither of those two work.

### package.json
```
  "dependencies": {
    "babel-plugin-styled-components": "^1.10.0",
    "bulma": "^0.7.4",
    "gatsby": "^2.1.2",
    "gatsby-awesome-pagination": "^0.3.3",
    "gatsby-image": "^2.2.23",
    "gatsby-plugin-favicon": "^3.1.6",
    "gatsby-plugin-google-tagmanager": "^2.0.15",
    "gatsby-plugin-lodash": "^3.0.1",
    "gatsby-plugin-netlify": "^2.0.10",
    "gatsby-plugin-purgecss": "^2.4.0",
    "gatsby-plugin-react-helmet": "^3.0.6",
    "gatsby-plugin-sass": "^2.0.10",
    "gatsby-plugin-sharp": "2.2.14",
    "gatsby-plugin-styled-components": "^3.0.7",
    "gatsby-remark-images": "^2.0.6",
    "gatsby-source-filesystem": "^2.0.20",
    "gatsby-source-wordpress": "^3.0.34",
    "gatsby-transformer-sharp": "^2.1.13",
    "html-react-parser": "^0.9.1",
    "lodash": "^4.17.5",
    "node-sass": "^4.11.0",
    "parcel-bundler": "^1.11.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.2",
    "react-dom": "^16.8.2",
    "react-helmet": "^5.2.0",
    "react-html-parser": "^2.0.2",
    "react-libre-form": "^0.4.1",
    "react-responsive-embed": "^2.1.0",
    "react-scroll-parallax": "^2.1.2",
    "react-spring": "^8.0.20",
    "react-sticky-el": "^1.0.20",
    "simple-parallax-js": "^5.0.0",
    "styled-components": "^4.2.1",
    "uuid": "^3.2.1"
  },
```

**Comment by hugo-marques-m3** [comment]
Not sure if this is helpful but if you use any query that ends in `_noBase64` like `GatsbyImageSharpFixed_withWebp_noBase64` it doesn't use the blurred image.

Our designers didn't like the blurred effect.

**Comment by D19cannon** [comment]
@hugo-marques-m3 thanks for the suggestion! I will try it out next time. For now I simply used the html image tag. While I am waiting for another release that actually accomplish my expectations.

**Comment by D19cannon** [comment]
@hugo-marques-m3 I just refactored and it works! Thanks for the reply! :)

**Comment by hugo-marques-m3** [comment]
Np, glad it helped 😄
