### ISSUE TITLE
Client-Side @React/React

### ISSUE THREAD

**Issue by RobinHerzog** [gatsbyjs/gatsby#18108]
Hello,

I'm trying to use GatsbyJS with a client-side rendering.

Here is the code:

```
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions;
  // page.matchPath is a special key that's used for matching pages
  // only on the client.
  if (page.path.match(/^\/webapp/)) {
    page.matchPath = "/webapp/*";
    // Update the page.
    createPage(page);
  }
};
```

```
import React from "react";
import { Router } from "@reach/router";

const Profile = () => <p>ok</p>;

const App = () => (
  <Router>
    <Profile path="/webapp/profile" />
  </Router>
);
export default App;
```

On gatsby develop, I get the "OK" page. However, when I use gatsby build, the page is white (not 404)

**Comment by gillkyle** [comment]
Is this when you navigate directly to the URL from the browser (ie typing in `localhost:8000/webapp/profile`)? Or when you try and go to `localhost:8000/webapp/`? 

Gatsby will create html files for all pages that you create by add in `src/pages` and/or the `createPages` API as you've possibly read or seen. However, for client only routes (like yours at webapp/*) that html file won't be generated so a server where your Gatsby build folder is being run from won't have a page there if you try to navigate to it directly. Perhaps you need to install `gatsby-plugin-create-client-paths` like outlined in [this guide](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/)?

**Comment by RobinHerzog** [comment]
> Is this when you navigate directly to the URL from the browser (ie typing in `localhost:8000/webapp/profile`)? Or when you try and go to `localhost:8000/webapp/`?
> 
> Gatsby will create html files for all pages that you create by add in `src/pages` and/or the `createPages` API as you've possibly read or seen. However, for client only routes (like yours at webapp/*) that html file won't be generated so a server where your Gatsby build folder is being run from won't have a page there if you try to navigate to it directly. Perhaps you need to install `gatsby-plugin-create-client-paths` like outlined in [this guide](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/)?

I didn't use gatsby-plugin-create-client-paths since my exports.onCreatePage does the same.

I get a white page when I navigate directly to it.

**Comment by universse** [comment]
Where are you deploying your site to? Cuz you need to set up path rewrites to redirect /webapp/some_path to /webapp. For eg if you are deploying to netlify, there's gatsby-plugin-netlify that automatically does that for you.

**Comment by RobinHerzog** [comment]
I was trying on localhost and my website in on S3 / Cloudfront

**Comment by universse** [comment]
There's gatsby-plugin-s3 you can try that out.
