### ISSUE TITLE
[docs][guides] How to Modify a Starter

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#18116]
## Summary

In the Getting Started with Gatsby sessions at Gatsby Days London, it was mentioned that people weren't sure how to modify a starter when building their first Gatsby site. It would be great to support them with a new Reference Guide in the [Starters](https://www.gatsbyjs.org/docs/starters/) section of the docs called "Modifying a Starter" that talks about common files and conventions in the default and blog starters.

This doc should include information on how to customize JSX and CSS markup, README and package.json files, and more. We also have new [API docs on important files](https://www.gatsbyjs.org/docs/api-files/) in Gatsby, which could be linked from this doc. It should also be linked from the parent [Starters doc](https://www.gatsbyjs.org/docs/starters/) and potentially [Part One of the tutorial](https://www.gatsbyjs.org/tutorial/part-one/#using-gatsby-starters).

## Motivation 

This comment from the feedback widget on Part One of the tutorial echos what we heard at Gatsby Days:

> "I get the site running locally, but cant find the code when I open VS code "

We should have docs to help people figure out where the code lives, since they're often building a Gatsby site for the first time and would benefit from a small tour of the code.

**Comment by glauberm** [comment]
Do you think that copying the [_What's inside?_](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/README.md#-whats-inside) section to the docs is a good first step? Then maybe exploring the `src` folder more in-depth, addressing topics like the ones you mentioned (JSX and CSS markup) and linking to external resources (React Docs, MDN). WDYT?

**Comment by marcysutton** [comment]
Ooh, sure! That sounds like a great place to start!

**Comment by sagarnasit** [comment]
I would to like to claim this for Hacktoberfest.

**Comment by glauberm** [comment]
Sure, @sagarnasit, go ahead! :+1:

**Comment by N7Layla** [comment]
Is there still help needed on this? Being that I made my personal site using a Gatsby starter I think I might be able to put some thoughts together so let me know if there's any piece I could contribute.

**Comment by marcysutton** [comment]
This issue has been internally assigned. There is a PR open in #18126, but as the feedback hasn't been addressed in a timely fashion, we have someone taking it on specifically. 

Thanks so much for the offer, @N7Layla. We would still love to have you as a contributor for other open issues; let us know if you have any questions about the things you find!

**Comment by marcysutton** [comment]
Closed with #18995.
