### ISSUE TITLE
[www] add allowFullScreen to EggheadEmbed component

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#18127]
## Description

From feedback received in the feedback widget of the docs page, it mentioned that videos can't be opened fullscreen which is definitely a behavior we'd like to support, especially because the bitmovin video player that the egghead embed component uses has a button for it.

The `allowFullScreen` attribute is likely enough to make this behavior possible.

One page where you can see an Egghead video with the embed is on the [Quick Start](https://www.gatsbyjs.org/docs/quick-start/) page.

## What needs to be done

- [ ] Add the `allowFullScreen` attribute to the iframe in this component: https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/shared/egghead-embed.js#L6-L12
- [ ] Verify that the above fix works

**Comment by Chopinsky** [comment]
Could I work on this issue?

**Comment by gillkyle** [comment]
Hey @chopinsky it looks like @sagarnasit already put up a PR, there will be other issues soon!
