### ISSUE TITLE
[Epic] Hacktoberfest 2019!

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#18129]
<h1 align="center">👻🎃 Gatsby Hacktoberfest 🎃👻!</h1>
<p align="center">
  <a href="https://www.gatsbyjs.org/">What is Gatsby?</a>  |  <a href="https://www.gatsbyjs.org/docs/">Gatsby Docs</a>
</p>
<p align="center">
<img alt="Halloween with Snoopy" src="https://user-images.githubusercontent.com/1045233/66222556-59262d80-e6c9-11e9-8ed9-a0d83b0dce07.png"/>
</p>

## Welcome!

During Hacktoberfest, you're probably looking to contribute to an open source project. Gatsby is a great project to contribute to because you can learn about Gatsby while tackling issues that help the community. We'll keep adding new issues throughout the month, so continue checking the GitHub repo for additional ways to contribute!

### Back up. What's Hacktoberfest?

[Hacktoberfest](https://hacktoberfest.digitalocean.com/) is "a month-long celebration of open source software run by DigitalOcean and DEV".

- [Register for Hacktoberfest](https://hacktoberfest.digitalocean.com/)
- [Learn more about Hacktoberfest](https://hacktoberfest.digitalocean.com/faq)

### First time contributing to Gatsby?

You may find these links helpful!
- [How to Contribute](https://www.gatsbyjs.org/docs/how-to-contribute/)
- [Code of Conduct](https://www.gatsbyjs.org/contributing/code-of-conduct/)
- [How to Open a Pull Request](https://www.gatsbyjs.org/contributing/how-to-open-a-pull-request/)

PS: When your first PR is merged, you can claim some [free swag from the Gatsby Store](https://www.gatsbyjs.org/docs/contributor-swag/)! 😄

## Issue areas

We are organizing issues into four different areas:

### [Docs][docs-filter]

We love our docs! Improving docs is a never-ending effort, and we have some [stub articles](https://www.gatsbyjs.org/contributing/stub-list/) (docs we want to exist, but haven't been written yet). If you're interested in contributing to the docs and doing some writing, check out [docs issues labelled with Hacktoberfest][docs-filter].

[docs-filter]: https://github.com/gatsbyjs/gatsby/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22Hacktoberfest%22+label%3A%22type%3A+documentation%22

### Docs localization

Want to do help us translate the Gatsby docs? Consider contributing to an existing repo (we have Spanish and Russian so far!), or start a new language translation by [opening an issue](https://www.gatsbyjs.org/contributing/how-to-file-an-issue/) to create a new repo and earn Hacktoberfest credit by contributing PRs to that repo.

- Spanish repo: https://github.com/gatsbyjs/gatsby-es
- Russian repo: https://github.com/gatsbyjs/gatsby-ru
- New translation repo request: https://github.com/gatsbyjs/gatsby/issues/new?template=new_translation.md

### [OSS][oss]

Make OSS contributions to Gatsby plugins, transformers and core by searching [OSS Hacktoberfest issues][oss].

[oss]: https://github.com/gatsbyjs/gatsby/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22Hacktoberfest%22+-label%3A%22type%3A+documentation%22+

### Ecosystem

Learn how to contribute to the Gatsby Ecosystem (starter library, site showcase, themes and plugin library, etc.) by reading the doc on [Community Contributions](https://www.gatsbyjs.org/contributing/community-contributions/). You can gain credit for both Hacktoberfest and Gatsby swag by submitting a PR with your Gatsby project to the starter library or site showcase in this repo. You can also check out issues labeled with [ecosystem](https://github.com/gatsbyjs/gatsby/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3AHacktoberfest+label%3A%F0%9F%8E%AFEcosystem+) to get Hacktoberfest credit! 

Gatsby [plugins](https://www.gatsbyjs.org/docs/creating-plugins/) and [themes](https://www.gatsbyjs.org/docs/themes/building-themes/) (a type of plugin) [published with the necessary files](https://www.gatsbyjs.org/contributing/submit-to-plugin-library/) can also count toward Hacktoberfest credit and earn Gatsby swag. The official Gatsby blog post will list all plugins created during Hacktoberfest: create your own and [add it there](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2019-10-08-hacktoberfest-2019/index.md#ecosystem) in a Pull Request to get credit!

## Gatsby's Hacktoberfest Goals

1. To provide a range of issues with a clearly defined scope, with minimal context needed outside of the issue description.
2. To make contributing to Gatsby as welcoming, friendly, and accessible as we can -- especially to first-time contributors.

**Comment by dpdhruv** [comment]
@marcysutton hey there , my first PR to gatsby is merged and i recieved a coupon but it's not working and hence I'm unable to claim my swag 🥺🥺. 

Could you please help me out?

Thanks

**Comment by marcysutton** [comment]
Since Hacktoberfest is over now, I'm going to close this issue. Thanks to everyone who contributed!
