### ISSUE TITLE
[www] fix padding on gatsby-code-title class

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#18120]
## Description

We introduced [a change to tweak the overlapping code blocks](https://github.com/gatsbyjs/gatsby/pull/17969) in the `gatsby-plugin-offline` README. The change fixes the README which is great, but also affects all pages where the class `gatsby-code-title` is used, and adds unnecessary padding around code titles in others docs pages which would make sense to remove.

Now:

![image](https://user-images.githubusercontent.com/21114044/66217796-2e19ea80-e685-11e9-9f1b-8fd482ff59a6.png)

What we Want:

![image](https://user-images.githubusercontent.com/21114044/66217906-615c7980-e685-11e9-8971-0263f64a1c72.png)

## What Needs to be Done

The line here: https://github.com/gatsbyjs/gatsby/blob/master/www/src/utils/typography.js#L280 should be removed. Instead we could add content between the adjacent code blocks in the offline plugin README, or just include a line break there.

**Comment by anhek** [comment]
Hello, can I try to fix the issue ?

**Comment by fk** [comment]
<3
