### ISSUE TITLE
[docs] misleading link from creating global styles with styled-components

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#18122]
## Description

The page [Creating global styles with `styled-components`]() points to [this doc on Styled Components](https://www.gatsbyjs.org/docs/styled-components/). That page doesn't talk about Creating global styles which makes the link seem misleading. Since we want to cover this information, rather than just changing the text of the link we should cover that in the Styled Components doc.

## Possible info to add

[Here's a possible API](https://www.styled-components.com/docs/api#createglobalstyle) from styled components that could be useful to point to or use as an example in a layout file or maybe better, using Gatsby's [`wrapRootElement`](https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement).

**Comment by erinfox** [comment]
I'd love to jump on this for my first Hacktoberfest :)

**Comment by marcysutton** [comment]
Sounds great, @erinfox!

**Comment by erinfox** [comment]
Awesome! I just submitted a PR. Let me know of any changes or updates 😄

**Comment by marcysutton** [comment]
Closed with #18293
