### ISSUE TITLE
[gatsby] actions.createNode failed to actually create the node

### ISSUE THREAD

**Issue by d4rekanguok** [gatsbyjs/gatsby#18136]
## Description

Hi folks! Love Gatsby & thank you for your work. Just have to start with that on every issue!

I'm writing a remark plugin that create a remote file node for remote images in markdown body, then pass it to sharp in similar fashion to gatsby-remark-images. Everything worked well.

I was hoping to cache the image to avoid unnecessary download. However, during the implementation of this, I found out that the node returned by `createRemoteFileNode` was not stored in Gatsby node store, i.e `getNode(imageFileNodeId)` returns `undefined` and the File node was not queriable in graphql (`query { allFile {...} }`).

It turned out somehow, the action result from `createNode`<sup>[source](https://github.com/gatsbyjs/gatsby/blob/182248546d0c8e78eac0ddbfd0dfeed6b6b1a78c/packages/gatsby/src/redux/actions/public.js#L820)</sup> had its `type` overwritten by `actionOptions`. When I logged it out, it looks like this:

```js
{ type:
   { name: 'ImageSharp',
     nodes: [ [Object], [Object], [Object], [Object] ] },
  traceId: 'initial-setFieldsOnGraphQLNodeType',
  parentSpan: Span {},
  payload: { id: ... }
}
```
I have no idea where this `actionOptions` comes from. I thought it was passed in somehow via `createRemoteFileNode`, but that function itself doesn't call `createNode` with a 3rd argument.

My bandage solution was simple: Don't let `type` be overwritten.

```js
    updateNodeAction = {
-     type: `CREATE_NODE`,
      plugin,
      oldNode,
      ...actionOptions,
      payload: node,
+    type: `CREATE_NODE`,
    }
```

With this, the plugin works properly; node is read from cache and I can query the File node in graphiq (see reproduce repo below). I think it's reasonable to make sure `type & payload` are never overwritten, but I'm not sure of Gatsby's internal and also this bug exposes something deeper -- I wonder where the `actionOptions` for that node comes from and why it has the unfortunate property name.

### Steps to reproduce

Here's the repo:
- https://github.com/d4rekanguok/gatsby-create-node-bug-repo

Step to reproduce:
- Set up
```bash
git clone https://github.com/d4rekanguok/gatsby-create-node-bug-repo.git
cd gatsby-create-node-bug-repo
yarn
gatsby develop
```

### Actual result

- open `content/blog/hello-world/index.md`
- enter random string to trigger refresh
- see this uh console message
```
IS IT IN THE CACHE? IS IT IN THE CACHE?
IT IS NOT IN THE CACHE
success Downloading remote files — 1/1 - 0.525 s
FRESH NODE
undefined
```
- (optional) navigate to localhost:8000/___graphql, enter this query:
```
query AllImageFiles {
  allFile(filter: {
    internal: {
      mediaType: {
        eq: "image/jpeg"
      }
    }
  }) {
    nodes {
      name
      internal {
        mediaType
      }
    }
  }
}
```

- See that the remote file node is missing (name: `photo-1563377176922-062e6ae09ceb`)

### Expected result

- Go to `node_modules/gatsby/dist/redux/actions/public.js`, navigate to `createNode` function
- Modify this line as mentioned above:

```js
    updateNodeAction = Object.assign({
-     type: `CREATE_NODE`,
      plugin,
      oldNode
    }, actionOptions, {
+     type: `CREATE_NODE`,
      payload: node
    });
```
- runs `gatsby clean && gatsby develop`
- open `content/blog/hello-world/index.md`
- enter random strings to trigger refresh
- see this uh console message
```
IS IT IN THE CACHE? IS IT IN THE CACHE?
WELL THE CACHE IS HERE
HERE IS THE NODE ID
66b26d92-e6ba-57f9-a368-d423d0c40dc6
OH BABY ITS IN THE CACHE ALRIGHT
```
- (optional) navigate to localhost:8000/___graphql, refresh the query above
- now the remote image can be seen

The relevant plugin code in the bug repo is [over here (compiled, but very readable)](https://github.com/d4rekanguok/gatsby-create-node-bug-repo/blob/master/.yalc/gatsby-remark-images-anywhere/util-download-image.js).

The source code is [over here](https://github.com/d4rekanguok/gatsby-remark-images-anywhere)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v11.14.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 67.0.4
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.13.25 => 2.13.25 
    gatsby-image: ^2.2.6 => 2.2.6 
    gatsby-plugin-feed: ^2.3.4 => 2.3.4 
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.4 
    gatsby-plugin-manifest: ^2.2.3 => 2.2.3 
    gatsby-plugin-offline: ^2.2.4 => 2.2.4 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2 
    gatsby-plugin-sharp: ^2.2.7 => 2.2.7 
    gatsby-plugin-typography: ^2.3.2 => 2.3.2 
    gatsby-remark-copy-linked-files: ^2.1.3 => 2.1.3 
    gatsby-remark-images: ^3.1.6 => 3.1.6 
    gatsby-remark-images-anywhere: file:.yalc/gatsby-remark-images-anywhere => 1.0.2-6aad3a74 
    gatsby-remark-prismjs: ^3.3.3 => 3.3.3 
    gatsby-remark-responsive-iframe: ^2.2.4 => 2.2.4 
    gatsby-remark-smartypants: ^2.1.2 => 2.1.2 
    gatsby-source-filesystem: ^2.1.5 => 2.1.5 
    gatsby-transformer-remark: ^2.6.6 => 2.6.6 
    gatsby-transformer-sharp: ^2.2.3 => 2.2.3 
  npmGlobalPackages:
    gatsby-cli: 2.7.47

```

**Comment by jamessimone** [comment]
Hopefully somebody from the core team will see this soon. It seems that any plugin that uses caching to optimize local development probably doesn’t properly make use of the cache when deploying, or at least the cache is not used properly when deploying to Netlify while this problem is unresolved.

**Comment by pieh** [comment]
I'll take a look why this happens. You current PR is ok (I think), but I'd much prefer if find root cause of `type` overwrites in `actionOptions`

**Comment by pieh** [comment]
Ok, this "weird" type is created here - https://github.com/gatsbyjs/gatsby/blob/3a41ab93a1aec4d561c8d361bd90e32cbf686afa/packages/gatsby/src/schema/schema.js#L591-L598

And those are arguments for one of our API hooks, but seems like this serves as double duty to pass additional context to action creators. Potentially we could split api hooks args, from action creator context, but that would be pretty large refactor, so I think your PR is most reasonable way to fix it right now.
