### ISSUE TITLE
Build errors with Sharp / Images in Markdown

### ISSUE THREAD

**Issue by sunny-kim-92** [gatsbyjs/gatsby#18144]
## Description

I've been running into a number of errors when trying to introduce plugins for adding images directly in my markdown. I have since removed instances of images within markdown, but an error remains and it seems to be preventing Netlify from building.

I attempted to use gatsby-remark-images and add the following to my markdown:

`
![some caption text](../.path/to/image)
`

I get the following error upon running `gatsby develop`:

```
objc[6387]: Class GNotificationCenterDelegate is implemented in both /Users/home/Code/amici-site/node_modules/sharp/vendor/lib/libgio-2.0.0.dylib (0x10768d578) and /Users/home/Code/amici-site/node_modules/gatsby-transformer-sharp/node_modules/sharp/vendor/lib/libgio-2.0.0.dylib (0x119ca3578). One of the two will be used. Which one is
```

However, `gatsby develop` still finishes and the image would appear fine. But when pushed to Netlify, the build fails with the following error:

```

 ERROR #11321  PLUGIN

"gatsby-transformer-json" threw an error while running the onCreateNode lifecycle:

Unexpected end of JSON input



  SyntaxError: Unexpected end of JSON input

  - JSON.parse

  - gatsby-node.js:63 Object.onCreateNode
    [amici-site]/[gatsby-transformer-json]/gatsby-node.js:63:30

```

I actually used to get both errors upon running `gatsby develop`. After reading through some of the GitHub issues (I can't seem to find the link), I ended up downgrading gatsby-transformer-sharp to 2.2.14, which fixed the second error on `gatsby develop`, but it still appears in the Netlify build logs. I have since removed the image syntax from my markdown, but the first error still remains.

### Steps to reproduce

My project is located at https://github.com/sunny-kim-92/amici-site. Running `gatsby develop` should produce the error.

### Expected result

Page works as anticipated upon `gatsby develop`, even with image in markdown, but the error appears and Netlify will not complete a build.

### Actual result

What happened.

### Environment

```
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 12.1
  npmPackages:
    gatsby: ^2.15.29 => 2.15.29
    gatsby-image: ^2.2.24 => 2.2.24
    gatsby-plugin-eslint: ^2.0.3 => 2.0.5
    gatsby-plugin-nprogress: ^2.1.9 => 2.1.9
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10
    gatsby-plugin-react-svg: ^2.0.0 => 2.1.2
    gatsby-plugin-sharp: 2.2.12 => 2.2.12
    gatsby-plugin-sitemap: ^2.2.16 => 2.2.16
    gatsby-plugin-styled-components: ^3.1.8 => 3.1.8
    gatsby-plugin-webpack-size: ^0.0.3 => 0.0.3
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-figure-caption: ^2.0.0 => 2.0.0
    gatsby-source-filesystem: ^2.1.29 => 2.1.29
    gatsby-transformer-json: ^2.2.12 => 2.2.12
    gatsby-transformer-remark: ^2.6.27 => 2.6.27
    gatsby-transformer-sharp: 2.2.14 => 2.2.14
  npmGlobalPackages:
    gatsby-cli: 2.7.26
```

**Comment by paustint** [comment]
@sunny-kim-92 - what did you do to resolve this?
