### ISSUE TITLE
Hook to control Socket.io configuration

### ISSUE THREAD

**Issue by JoeWrenn** [gatsbyjs/gatsby#18143]
## Summary
I am proposing that a hook should exist for controlling the socket.io connection that is used when rendering a page from gatsby develop. This would allow multiple gatsby develop sites to work behind a proxy.

I am attempting to stitch together several gatsby develop instances behind a proxy environment. There is one final hurdle before it works in that the socket.io connection has a hardcoded connection to a relative URL path of "/socketio" by nature of the default constructor call here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/socketIo.js#L20

I would propose exposing the options passed to the socketio constructor in a similar manner to other gatsby hooks. This would allow for an instance of gatsby develop to be served from behind a proxy server while allowing the socket connection to go directly back to the instance instead of through the proxy. 

I think my general approach to this would mirror the SSR hooks where we provide functions to get and set the socketio configuration object.

**Comment by SamIngram96** [comment]
Bumping for exposure

**Comment by ANDIKKY** [comment]
This would allow multiple gatsby develop sites to work behind a proxy.

**Comment by sidharthachatterjee** [comment]
@JoeWrenn Thank you for opening this!

This sounds like a pretty _niche_ use case and adding a hook for this doesn't seem like it would be worth the long term maintenance burden. 

It is currently possible to run multiple instances of `gatsby develop` on different ports using `gatsby develop -p XXXX` and that should suffice for the use case you describe, I think? 

Closing this for the moment but please feel free to reopen or comment in case I'm missing something. Thank you so much once again!

**Comment by hughevans** [comment]
Just flagging that this is required in order to develop Gatsby sites within Github codespaces. Will have a play and see if I can pull together a PR.
