### ISSUE TITLE
Target container is not a DOM element. in html.js

### ISSUE THREAD

**Issue by billel-boudchicha** [gatsbyjs/gatsby#1814]
```
<div
       key={`body`}
       id="___gatsby"
       dangerouslySetInnerHTML={{ __html: this.props.body }}
 />
```
i think `id="___gatsby"` is required , change it leads to an ` invariant error `
````
Uncaught Error: _registerComponent(...): Target container is not a DOM element.
````

**Comment by billel-boudchicha** [comment]
which is not marker as required in the doc

**Comment by oliverbenns** [comment]
It's in the migrating docs, but not in the standard docs: https://www.gatsbyjs.org/docs/migrating-from-v0-to-v1/#htmljs . I think this is the case for a few things.

**Comment by billel-boudchicha** [comment]
thank you  closing it

**Comment by KyleAMathews** [comment]
Agree this should be better documented. Added a bit to the "Custom html.js" docs page https://github.com/gatsbyjs/gatsby/pull/1821
