### ISSUE TITLE
How to set a image for list of posts?

### ISSUE THREAD

**Issue by GoreStarry** [gatsbyjs/gatsby#1819]
I'm using the `gatsby-transformer-javascript-static-exports` to query the posts list.

```js
export const data = {
  title: 'Book1',
  date: '2017-10-04',
  cover: require('./images/img.jpg'),
}
```
but when I query the `JsFrontmatter` the value of cover will be null.
And the image required by the component will be hashed, so it can't give value by image file name directly.
Is any way to make this work? THX!

**Comment by jbolda** [comment]
Were you able to solve this?
