### ISSUE TITLE
Starter Idea: Careers Page

### ISSUE THREAD

**Issue by couturecraigj** [gatsbyjs/gatsby#1820]
I have been thinking about this.  Why not make Gatsby Template for a Careers Page?  Does this sound like something I should work on.  Obviously, this is more of an 'email this person' type of Careers page (not some complex workflow) but I have been looking around and a lot of tech companies use something very similar in the Hiring page and well why not Gatsby?

**Comment by KyleAMathews** [comment]
Not quite sure what you mean? This is a component? Or a Gatsby starter?

**Comment by couturecraigj** [comment]
Sorry wrong term Gatsby Starter.  It may not be used all the time but I thought it would be neat to have since I see a lot of tech teams essentially just have job posting and ask people to email a certain address with specific formatting to ask for a job.  I thought that would be a neat Idea.  Thoughts?

**Comment by KyleAMathews** [comment]
Sure! Sounds great! The more starters the merrier :-)

**Comment by sebastienfi** [comment]
:+1:

**Comment by KyleAMathews** [comment]
Happy to see this still! Add it to the starters page when it's done.
