### ISSUE TITLE
[Themes] contentPath option in gatsby-theme-blog-core is not properly supporting custom content paths in nested themes

### ISSUE THREAD

**Issue by ehowey** [gatsbyjs/gatsby#18212]
## Description

I have been trying to get a custom content path to work with `gatsby-theme-blog-core` when it is nested inside of other themes.  The default content path of `.../content/posts` does work however as soon as I specify a content path in the options I get the following error:

```
success update schema - 0.182 s
success Generating image thumbnails — 8/8 - 5.982 s
warn The GraphQL query in the non-page component "/Users/erichowey/Coding/test/blog-test/node_
modules/gatsby-theme-blog-core/src/templates/post-query.js" will not be run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — http://graphql.org/learn/queries/#fragments
success extract queries from components - 1.430 s
``` 

### Steps to reproduce

https://github.com/ehowey/gatsby-blog-core-bug

I have the following nested theme structure:
- [Gatsby-Theme-Catalyst-Core](https://github.com/ehowey/gatsby-theme-catalyst-core)
_Core theme, implements most plugins, etc._
  - [Gatsby-Theme-Catalyst-Blog](https://github.com/ehowey/gatsby-theme-catalyst-blog)
  _This is basically just a wrapped implementation of `gatsby-theme-blog-core`_
    - `gatsby-theme-blog-core`
    _This is simply included as a plugin in the above theme_
      - [Gatsby-Blog-Core-Bug](https://github.com/ehowey/gatsby-blog-core-bug)
      _This is just a quick starter implementing the three above themes_

You can duck into the node_modules folder and change the `gatsby-config.js` file in `gatsby-theme-catalyst-blog`, if you remove the line `contentPath: "src/blog"` it should progress fine in the build.

### Expected result

I should be able to specify a custom content path in `gatsby-theme-catalyst-blog` which is successfully picked up by `gatsby-theme-blog-core` and then used by the starter.

### Actual result

See above error report.  Of note the site does successfully build but the nodes are not properly populated with data, e.g. frontmatter, body etc.  The result of querying the data looks like this:

```
{
  "data": {
    "allMdxBlogPost": {
      "edges": []
    },
    "allBlogPost": {
      "edges": []
    }
  }
}
```

### Environment

```

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Firefox: 67.0.2
    Safari: 13.0.1
  npmPackages:
    gatsby: ^2.15.28 => 2.15.29
    gatsby-theme-catalyst-blog: ^0.0.2 => 0.0.2
    gatsby-theme-catalyst-core: ^0.6.3 => 0.6.4
  npmGlobalPackages:
    gatsby-cli: 2.7.53
    gatsby-dev-cli: 2.5.30
```

**Comment by ChristopherBiscardi** [comment]
you're using a path to a directory that doesn't have any mdx files in it. That's why the page template isn't being used. If you look higher up in the error message you'll see a note about how `gatsby-theme-blog-core` didn't generate any nodes.

**Comment by ehowey** [comment]
I must be confused then about properly using this nested configuration. 

Inside of ‘Gatsby-theme-blog-bug’ (the starter) there is a folder ‘src/blog’ which has three different MDX blog posts.  This is the folder I am trying read and pickup...

My goal is to have the following structure:

Core theme -> Blog theme -> Starter

The structure and components would live in the themes while the theme-ui styles and content (e.g. blog posts) would live in the starter. 

I can get this structure to work if I rely on the default contentPath from ‘Gatsby-theme-blog-core’ but not is I specify the path. 

I am on my phone so will take a closer look a second time tonight.

**Comment by ehowey** [comment]
I figured out what was causing the problem - thanks Chris for giving me the hint to look back at the actual core config.

For anyone reading this in the future...in my core theme I had the following set for `gatsby-source-filesystem`:

```
{
        resolve: `gatsby-source-filesystem`,
        options: {
          name: `src`,
          path: `src/`,
        },
      },
```

This was causing a problem for actual core theme when I tried to specify a path like `src/blog`, the fix was to get more granular with my `gatsby-source-filesystem` plugin...like this:

```
{
        resolve: `gatsby-source-filesystem`,
        options: {
          name: `images`,
          path: `src/images`,
        },
      },
```
