### ISSUE TITLE
[gatsby-plugin-remote-images] Download images from multiple external sources locally

### ISSUE THREAD

**Issue by fandy** [gatsbyjs/gatsby#18217]
Currently the plugin only allows images to be downloaded locally from one path:

```
  plugins: [
    {
      resolve: `gatsby-plugin-remote-images`,
      options: {
        nodeType: 'myNodes',
        imagePath: 'nodes[].imageUrl',
      },
    },
  ]
```

This is a problem when your GraphQL API has multiple fields with external images inside them:

![image](https://user-images.githubusercontent.com/19108762/66267931-5af50b80-e805-11e9-85b9-7ddea6851568.png)

**Comment by jonniebigodes** [comment]
@fandy it seems so, probably with some minor changes the plugin can allow multiple fields as you're mentioning and with that more people can benefit from it. If you're willing to make the changes to that plugin and make a pr in the plugin repo.

**Comment by LekoArts** [comment]
Thank you for opening this!

Please take this request to the author's GitHub: https://github.com/graysonhicks/gatsby-plugin-remote-images

Thanks!

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
