### ISSUE TITLE
[gatsby-theme] 404 shadowing doesn't work as expected

### ISSUE THREAD

**Issue by dhhdev** [gatsbyjs/gatsby#18216]
## Description

404 page creation seems to not actually shadow like any other page gatsby creates.
It also makes two paths/files, that seems redundant:

- /404.html (expected)
- /404/ (redundant)

### Steps to reproduce

I have made a test repository to clarify. Simply clone the repository and run it, to see what I mean.

`git clone https://github.com/dhhdev/gatsby-404-shadowing-example`

`yarn install`

`yarn workspace site develop`

### Expected result

My custom 404 on my site, should overwrite/shadow the themes 404 page. Like any other page/file would.

### Actual result

Uses 404 page made in theme, if I delete it - it will use my sites actual 404.js file.

### Environment
  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (8) x64 Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz
    Shell: 5.3.1 - /usr/bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/bin/node
    Yarn: 1.19.0 - /usr/bin/yarn
    npm: 6.11.3 - ~/npm/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 60.9.0
  npmGlobalPackages:
    gatsby-cli: 2.7.53

**Comment by dhhdev** [comment]
I suspect this behaviour could have something to do with, how webpack loader works. As discussed on Twitter yesterday with @ChristopherBiscardi

**Comment by dhhdev** [comment]
Adding to this as a side note. I experience the same, but the other way around - for example a `gatsby-theme-dhhit/src/assets/brandicons/` path.

If this path doesn't exist in my actual site (e.g., `site/src/assets/brandicons/`)

It won't resolve it with a custom `setWebpackConfig` in my `gatsby-node.js`.

### Example gastby-theme/gastby-node.js file:
```js
const path = require('path');

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      alias: {
        '~brands': path.resolve('./src/assets/brandicons/'),
        '~feather': path.resolve('./src/assets/feathericons/')
      }
    }
  });
};
```

The above will **ONLY** work if the site using the theme has the directories and files in place.

E.g., `site/src/assets/brandicons/`

Maybe I am fundamentally wrong in how themes should work to some extend. But I thought the idea was to have anything from images/svgs/markdown to anything really. And having my site shadow it, to do as little work as possible.

**Comment by juanpprieto** [comment]
Experiencing the same shadowing issue. 

Any updates on this one?
