### ISSUE TITLE
Passing data to each page for tracking Mixpanel

### ISSUE THREAD

**Issue by RobinHerzog** [gatsbyjs/gatsby#18225]
Hello,

I'm using Prismic, templates and pages. 
Each one my prismic page have a key "route" and "lang". 

With mixpanel, I track each time a user change the page.
Currently I use gatsby-browser and I get the data with:
```
  const dataLang = document.getElementById("lang").getAttribute("lang");
  const dataRoute = document.getElementById("route").getAttribute("route");
```
This is working but I'm sure there is a better way.

How would do it?

**Comment by LekoArts** [comment]
Thank you for opening this!

This solution seems fine. Have you tried contacting the Mixpanel support? This seems like a more appropriate place to ask this question.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Comment by RobinHerzog** [comment]
This is not related to Mixpanel but to gatsbyjs.

How can I get more data on the function bellow?

```
export const onRouteUpdate = ({ location }) => {
```
