### ISSUE TITLE
Gatsby new site creation using cli is failing

### ISSUE THREAD

**Issue by aldrinpvincent** [gatsbyjs/gatsby#18221]
## Description

gatsby new test failing with error
<img width="1680" alt="Screenshot 2019-10-06 at 8 58 32 PM" src="https://user-images.githubusercontent.com/38835946/66271525-8e26b180-e87c-11e9-8f7e-2eb005bed7b4.png">

### Environment
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Safari: 13.0.1
  npmGlobalPackages:
    gatsby-cli: 2.7.54

**Comment by waltercruz** [comment]
It seems that you're missing automake! 

If you're using homebrew, try:

`brew install automake`

**Comment by aldrinpvincent** [comment]
Awesome it worked.
Thanks @waltercruz for the help.
Closing the issue
