### ISSUE TITLE
Running `gatsby develop` and viewing localhost in Chrome results in constant refresh

### ISSUE THREAD

**Issue by JeffWeim** [gatsbyjs/gatsby#18226]
## Description

After a fresh install of a Gatsby project (`gatsby new [project name]`) and running `gatsby develop` to begin local development, attempting to view the url at `localhost:8000` in Chrome results in the webpage constantly refreshing itself. After canceling the page load, and viewing the console, you can see the following errors:

<img width="1680" alt="Screen Shot 2019-10-06 at 10 17 44 AM" src="https://user-images.githubusercontent.com/8635521/66272752-a10c9800-e822-11e9-92a2-7e712a6370c2.png">

### Steps to reproduce

1. `gatsby new [project name]`
2. `cd [project name]` 
3. `gatsby develop`
4. Open `localhost:8000` in a Chrome window
5. Issue should be visible

### Expected result

The default Gatsby starter landing page should be shown.

### Actual result

The webpage is constantly refreshing itself without any input from the user

### Environment

```
System:
    OS: macOS 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.15.29 => 2.15.29
    gatsby-image: ^2.2.24 => 2.2.24
    gatsby-plugin-manifest: ^2.2.20 => 2.2.20
    gatsby-plugin-offline: ^3.0.11 => 3.0.11
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10
    gatsby-plugin-sharp: ^2.2.28 => 2.2.28
    gatsby-source-filesystem: ^2.1.29 => 2.1.29
    gatsby-transformer-sharp: ^2.2.20 => 2.2.20
  npmGlobalPackages:
    gatsby-cli: 2.7.54
```

**Comment by LekoArts** [comment]
Hi, thanks for opening the issue. I can't reproduce the issue with Chrome 77.0.3865.120. Can you please update your project or give more details on how to reproduce this problem?

**Comment by steven-mercatante** [comment]
I'm running into the same issue with all Gatsby projects, on both Chrome and Firefox. Opening the site in an incognito window doesn't have this problem. I wonder if it has to do with the offline plugin and service worker?

**Comment by JeffWeim** [comment]
@steven-mercatante I found a workaround for now is to use `http://127.0.0.1:8000/` instead of `http://localhost:8000`

Found this while searching through related issues: https://github.com/gatsbyjs/gatsby/issues?utf8=%E2%9C%93&q=is%3Aissue+127.0.0.1

**Comment by barrars** [comment]
I'm usually able to resolved with a hard page reload, ctrl + shift + r

It seems to have to do with cache maybe?

**Comment by leesh22** [comment]
I'm also having this issue, hard reload works but still a pain to work with.

**Comment by cluzier** [comment]
> I'm usually able to resolve with a hard page reload, ctrl + shift + r
> 
> It seems to have to do with cache maybe?

thank you for sharing this. fixed it for me

**Comment by Segun-Ade** [comment]
> I'm usually able to resolve with a hard page reload, ctrl + shift + r
> 
> It seems to have to do with cache maybe?

Thanks for sharing. I had a similar issue, and this fixed it for me.

**Comment by DarthOstrich** [comment]
I'm also having the same issue. hard page reload is the only thing that fixes it.

**Comment by nwpointer** [comment]
can confirm hitting http://127.0.0.1 instead of localhost resolved this issue for me - does anyone know why that might be?

**Comment by AntonOtaner** [comment]
I believe that this is a cache issue with chrome. After reading #5900, @prajapati-parth solution worked for me 

>  But rather than clearing the entire browser's cache, you can just open developer tools and click "clear site data" from Applications tab.

This fixed the issue for me.

**Comment by Ruchika30** [comment]
Hi , I am facing this same issue. And things are not working for me . Can't even open console, hard refresh is also not working.Not even incognito. Kindly help

**Comment by yurqua** [comment]
Hard refresh solves the issue only until the next 'normal' reload, and then nothing helps. Except for the following:
Go to Dev tools > Application > Service workers, make sure the current service worker is on http://localhost:8000/ and hit 'Unregister' link on its right.

![image](https://user-images.githubusercontent.com/9869503/84690544-eef5a600-af42-11ea-9ef1-9bddc8a906ed.png)

**Comment by dolatabadi** [comment]
I am having this issue on Firefox, it loads fine on Chrome - anyone found a fix for this?

**Comment by taylorcenters** [comment]
I'm also experiencing this issue in Firefox - probably because of my privacy settings preventing the service worker from registering 

`Failed to get service worker registration(s): Storage access is restricted in this context due to user settings or private browsing mode.`

**Comment by HarryAdney** [comment]
I've got exactly the same problem on Firefox. Neither localhost:8000 nor 127.0.0.1:8000 work for me (Windows 10 Firefox 83.0b8 (64-bit).

Gatsby serve then localhost:9000 does work.

**Comment by malisbad** [comment]
I'm getting the same issue, although it does seem to stop....eventually...on its own.

Chrome Version 86.0.4240.193 (Official Build) (x86_64)

**Comment by scerelli** [comment]
Same stuff here, every JavaScript error makes the page start an infinite reloading until my pc totally freeze and I have to restart it. I'm working on Linux, ubuntu

**Comment by alvaromb** [comment]
Also experiencing on Safari, not on Chrome or Firefox. In my case, it seems related to the HRM module.

**Comment by nicoputzehl** [comment]
I have the same error on basically all my browsers (brave, chrome, safari, firefox). 
Hat reload makes it work.
And it doesnt appear at 127.0.0.1

**Comment by yakkomajuri** [comment]
My problem for this was cookies. Clearing cookies for `localhost` fixed it for me. 

Generally, if you have a similar problem, hitting `127.0.0.1` for example will work, because that host doesn't have the same associated cookies.
