### ISSUE TITLE
allShopifyPage GraphQL query is not available in GraphiQL Explorer

### ISSUE THREAD

**Issue by Digital-E** [gatsbyjs/gatsby#18249]
## Description

allShopifyPage GraphQL query created with ```gatsby-source-shopify``` plugin is not available to query when using GraphiQL Explorer

### Steps to reproduce

Use ```gatsby-source-shopify``` plugin in Gatsby project and link Shopify store containing pages.

Go to: [localhost:8000/__graphql](url)

### Expected result

I should be able to query allShopifyPage in the GraphiQL Explorer, however the query node doesn't show up.

These queries are all run during build:
```
gatsby-source-shopify/souvenirbyofficial starting to fetch data from Shopify

gatsby-source-shopify/souvenirbyofficial fetched and processed Article nodes: 397.223ms

gatsby-source-shopify/souvenirbyofficial fetched and processed Blog nodes: 402.303ms

gatsby-source-shopify/souvenirbyofficial fetched and processed Collection nodes: 431.017ms

gatsby-source-shopify/souvenirbyofficial fetched and processed ShopPolicy nodes: 433.121ms

gatsby-source-shopify/souvenirbyofficial fetched and processed Page nodes: 436.664ms

gatsby-source-shopify/souvenirbyofficial fetched and processed Product nodes: 726.026ms

gatsby-source-shopify/souvenirbyofficial finished fetching data from Shopify: 723.863ms
```

This is the ```gatsby-source-shopify``` plug-in, in my ```gatsby-config.js``` set-up:

```
plugins: [
  /*
   * Gatsby's data processing layer begins with “source”
   * plugins. Here the site sources its data from Shopify.
   */
  {
    resolve: "gatsby-source-shopify",
    options: {
      // The domain name of your Shopify shop. This is required.
      // Example: 'gatsby-source-shopify-test-shop' if your Shopify address is
      // 'gatsby-source-shopify-test-shop.myshopify.com'.
      shopName: "gatsby-source-shopify-test-shop",

      // An API access token to your Shopify shop. This is required.
      // You can generate an access token in the "Manage private apps" section
      // of your shop's Apps settings. In the Storefront API section, be sure
      // to select "Allow this app to access your storefront data using the
      // Storefront API".
      // See: https://help.shopify.com/api/custom-storefronts/storefront-api/getting-started#authentication
      accessToken: "example-wou7evoh0eexuf6chooz2jai2qui9pae4tieph1sei4deiboj",

      // Set verbose to true to display a verbose output on `npm run develop`
      // or `npm run build`. This prints which nodes are being fetched and how
      // much time was required to fetch and process the data.
      // Defaults to true.
      verbose: true,

      // Number of records to fetch on each request when building the cache
      // at startup. If your application encounters timeout errors during
      // startup, try decreasing this number.
      paginationSize: 250,

      // List of collections you want to fetch.
      // Possible values are: 'shop' and 'content'.
      // Defaults to ['shop', 'content'].
      includeCollections: ["shop", "content"],
    },
  },
]
```

### Environment

  System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 67.0.4
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.15.28 => 2.15.28 
    gatsby-image: ^2.2.23 => 2.2.23 
    gatsby-plugin-manifest: ^2.2.20 => 2.2.20 
    gatsby-plugin-offline: ^3.0.11 => 3.0.11 
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10 
    gatsby-plugin-sharp: ^2.2.27 => 2.2.27 
    gatsby-plugin-styled-components: ^3.1.8 => 3.1.8 
    gatsby-source-filesystem: ^2.1.28 => 2.1.28 
    gatsby-source-graphql: ^2.1.17 => 2.1.17 
    gatsby-source-prismic: ^2.3.0-alpha.3 => 2.3.0-alpha.3 
    gatsby-source-shopify: ^3.0.19 => 3.0.19 
    gatsby-transformer-sharp: ^2.2.19 => 2.2.19 
  npmGlobalPackages:
    gatsby-cli: 2.4.16

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by calebsylvest** [comment]
@Digital-E can I think the documentation is incorrect and needs to be updated. I believe you need to use `allSitePage` to query pages. Not sure if this is a recent change or error in the docs.

![GraphiQL_and_gatsby-source-shopify___GatsbyJS_and_node](https://user-images.githubusercontent.com/4457883/68165083-13f15780-ff24-11e9-9f37-353e32e2e301.png)

**Comment by jamelait** [comment]
@calebsylvest I don't think so. `allSitePage` refers to all the pages built with gatsby. `allShopifyPage` is supposed to return all the pages created in Shopify (ie: about-us, contact-us...). And as you can see on your screenshot, `allShopifyPage` is not even present.

**Comment by tormi** [comment]
`allShopifyPage ` is not in a list of covered types here: https://www.gatsbyjs.org/packages/gatsby-source-shopify/#how-to-query

**Comment by tormi** [comment]
Ok, it's here instead: https://www.gatsbyjs.org/packages/gatsby-source-shopify/#query-pages

**Comment by calebsylvest** [comment]
@jamelait @tormi right, `allShopifyPage` is listed in the documentation as the way to query for pages created in Shopify. But what @Digital-E is running into is that `allShopifyPage` is not an available query in the GraphiQL editor. I'm seeing the same issue (see my screenshot above, `allShopifyPage` is not available in the Explorer tab).

Can either of you confirm you can access `allShopifyPage`?

**Comment by jamelait** [comment]
I am seeing the same issue too. `allShopifyPage` is not available in the GraphiQL explorer.

**Comment by stoufa88** [comment]
Also for me, I will try to open a fix PR in the next days.

**Comment by paveli** [comment]
Hi, I am experiencing the same issue. Any updates on it?

**Comment by paveli** [comment]
Hi, I have made a small reproduction repo. 
Please see it here: https://github.com/paveli/gatsbyjs-issue-18249

**Comment by adamatronix** [comment]
Hi, 

Is anyone still having this problem like I am? I am using gatsby-source-shopify 6.5.2. I will try and follow-up with my findings

**Comment by alexcanessa** [comment]
@adamatronix same here. The plugin source doesn't even seem to query for pages anymore? I'm using version 6.6.0 and doesn't seem to fetch any content (article, pages, etc)
