### ISSUE TITLE
Adding gatsby-plugin-netlify-cms in a monorepo slows down the build time

### ISSUE THREAD

**Issue by chrfritsch** [gatsbyjs/gatsby#18245]
## Description

In a monorepo project, adding gatsby-plugin-netlify-cms slows down the "Building production JavaScript and CSS bundles" step.

Removing "gatsby-plugin-netlify-cms" from example/atsby-config.js brings build time back to normal.
### Steps to reproduce

- Download the netlifycms branch of https://github.com/chrfritsch/netlify-monorepo/tree/netlifycms
- yarn install
- cd example
- gatsby build

### Expected result

The project should build within 5 seconds.

### Actual result

It takes 15-30sec.

### Environment
```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 60.9.0
    Safari: 13.0.1
  npmGlobalPackages:
    gatsby-cli: 2.7.30
```

**Comment by kogal** [comment]
This becomes even more important now that Netlify will start to charge for build minutes.

**Comment by chrfritsch** [comment]
Maybe @erquhart can help with that.

**Comment by erquhart** [comment]
@erezrokah this issue is our first target when we start digging into the Gatsby integration.

Related to #14418.

**Comment by chrfritsch** [comment]
This is already prioritized by the netlify cms team. We should keep it open

**Comment by erezrokah** [comment]
I'm actively working on this issue (and all the other plugin related issues).
Currently trying to include `netlify-cms-app` and `netlify-identity-widget` as external dependencies to avoid having Webpack re-optimzing them.

**Comment by chrfritsch** [comment]
Awesome work. My build time dropped from 110sec to 70sec. That's amazing 🚀
