### ISSUE TITLE
gatsby-source-prismic-graphql or gatsby-source-prismic

### ISSUE THREAD

**Issue by chapster11** [gatsbyjs/gatsby#18255]
Hi all I tried asking this question on Spectrum gatsby.js community with no response so trying her with hopes someone can answer some of these questions. 

Whats the main difference between gatsby-source-prismic-graphql and gatsby-source-prismic?
Apart from the 1 line that is written in githup for gatsby-source-prismic-graphql

> gatsby-source-prismic is a different plugin that fetches data using Prismic's REST and Javascript APIs. Previews must be coded up separately.

I'm currently working on a project that uses gatsby-source-prismic. And so far so good. We wanted to update to using their beta 3 version which does Prismic Preview https://github.com/angeloashmore/gatsby-source-prismic/blob/v3-beta/README.md. When I do a check on Gatsby's docs its now are linking to gatsby-source-prismic-graphql. Does this mean that Gatsby no longer supports gatsby-source-prismic ?

If I was to updated my project using gatsby-source-prismic-graphql would this break the data structure that is currently used with gatsby-source-prismic ? Or would this stay the same.
I'd like to stay using gatsby-source-prismic because the project if pretty large and don't want the headache of having to re-write all our data connections to graphql queries ?

For example: Currently using gatsby-source-prismic. 

> All documents are pulled from your repository and created as prismic${contentTypeName} and allPrismic${contentTypeName}, where ${contentTypeName} is the API ID of your document's content type.

Would this be a different structure if we changed to gatsby-source-prismic-graphql

Thanks

**Comment by LekoArts** [comment]
Thank you for opening this!

> When I do a check on Gatsby's docs its now are linking to gatsby-source-prismic-graphql. Does this mean that Gatsby no longer supports gatsby-source-prismic ?

No, Gatsby of course supports both source plugins. The guide also uses it: https://www.gatsbyjs.org/docs/sourcing-from-prismic/

Switching source plugins will certainly require you to also change GraphQL queries and whatnot. You should contact the maintainers of both plugins if you need clarification about what the differences are and how you could possibly migrate.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Comment by PaulinaVPG** [comment]
I just wrote an article on how to do this, i hope you find it helpful :)

https://user-guides.prismic.io/en/articles/3647135-how-to-migrate-a-project-from-gatsby-source-prismic-to-gatsby-source-prismic-graphql
