### ISSUE TITLE
Bug image Blur-up with theme gitbook-starter

### ISSUE THREAD

**Issue by bersot1** [gatsbyjs/gatsby#18257]
## Description

when I put an image in my post and see how it looks (gatsby develop or build) returns 2 images, one on top of the other (attachment)

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

Show one image.

### Actual result

show 2 image (1 blur up and bellow a original image)
![bug blur image](https://user-images.githubusercontent.com/51892738/66322359-65440200-e8f8-11e9-8c8b-5a2d22c225b4.png)

### Environment

System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.15.28 => 2.15.28
    gatsby-image: ^2.2.24 => 2.2.24
    gatsby-link: ^2.2.17 => 2.2.17
    gatsby-plugin-algolia: ^0.3.4 => 0.3.4
    gatsby-plugin-emotion: ^4.1.9 => 4.1.9
    gatsby-plugin-gtag: ^1.0.11 => 1.0.11
    gatsby-plugin-layout: ^1.1.10 => 1.1.10
    gatsby-plugin-mdx: ^1.0.46 => 1.0.46
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10
    gatsby-plugin-remove-trailing-slashes: ^2.1.9 => 2.1.9
    gatsby-plugin-sharp: ^2.2.28 => 2.2.28
    gatsby-plugin-sitemap: ^2.2.16 => 2.2.16
    gatsby-plugin-styled-components: ^3.1.8 => 3.1.8
    gatsby-remark-copy-linked-files: ^2.1.23 => 2.1.23
    gatsby-remark-images: ^3.1.25 => 3.1.25
    gatsby-source-filesystem: ^2.1.29 => 2.1.29
    gatsby-transformer-remark: ^2.6.26 => 2.6.26
    gatsby-transformer-sharp: ^2.2.20 => 2.2.20

**Comment by arjunsajeev** [comment]
@bersot1 Finally figured out why this was happening. See https://github.com/gatsbyjs/gatsby/issues/15486

**Comment by bersot1** [comment]
Thanks @arjunsajeev !!!
