### ISSUE TITLE
[docs] add note about npx vs npm under quick start video

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#18273]
## Description 

The Quick Start page is really commonly visited and some points of feedback for the page have mentioned that the egghead video showing how to use the Gatsby cli uses npx, whereas the instructions don't mention npx. There should generally continuity between what a video shows and the written content, so I think the easiest fix for now (rather than rerecording the video) is to add a note about the video using npx below the `<EggheadEmbed />` [here](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/quick-start.md#L13).

## What to do

Add a note, maybe something like:

```
**Note**: this video uses `npx`, which is a tool to execute an npm package without first installing it. Running the command `npx gatsby new` is the same as running `gatsby new` after installing the gatsby-cli on your computer.
```

**Comment by garrowp** [comment]
I'd love to work on this!
