### ISSUE TITLE
How do you add sub-routes? like "mysite.com/blog/post-1" or "mysite.com/projects/project-1"

### ISSUE THREAD

**Issue by tangert** [gatsbyjs/gatsby#1827]
Title says it. I know that you can easily add pages into the pages folder but I need to create subroutes like in the title. Not sure how to approach it. I tried just making sub folders and slightly adjusting the GraphQL query but its not working

**Comment by oliverbenns** [comment]
Not sure what you're doing with GraphQL (I'm not currently using it and directly importing the object), but creating subfolders works for me: https://github.com/oliverbenns/oliverbenns.com/tree/gatsby-1.0/src/pages/work

**Comment by tangert** [comment]
I'm going off the gatsby blog starter kit. My file directory looks like this:


- pages 
    -  blog
        -   post1.md
        - post2.md
    -  index.js

but it's still giving me "localhost:8000/post-1" as the path instead of "localhost:8000/blog/post-1"

**Comment by tangert** [comment]
@oliverbenns any advice?

**Comment by tangert** [comment]
Got it working. Just had to restart the server. For some reason it wasnt working the first few times.

Solution:

1. Make the paths in your markdown files absolute, e.g. "/blog/post1"
2. Run `gatsby develop` again

**Comment by jonathanphz** [comment]
Anyone knows a way to do this automatically? I mean prepending `/blog/` to path automatically on page create.

**Comment by oplengs001** [comment]
> Got it working. Just had to restart the server. For some reason it wasnt working the first few times.
> 
> Solution:
> 
> 1. Make the paths in your markdown files absolute, e.g. "/blog/post1"
> 2. Run `gatsby develop` again

can you show the solution here?

**Comment by RectoVersoDev** [comment]
Any update on this?
