### ISSUE TITLE
[docs] new doc on Winning Over Content Creators with Gatsby

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#18281]
## Summary

We have some great docs on [Using Gatsby Professionally](https://www.gatsbyjs.org/docs/using-gatsby-professionally/), including [Winning Over (various) Stakeholders](https://www.gatsbyjs.org/docs/winning-over-stakeholders/). 

Through feedback, it was uncovered that the docs would benefit from an additional resource on Winning Over Content Creators. Given the potential for collaboration in using Gatsby with a Headless CMS, this seems like a great idea. A doc of this nature should talk about the benefits of using the Content Mesh with Gatsby and what a collaborative workflow using modern tools could look like.

For anyone interested in picking this up, please read through the existing Winning over Stakeholders docs as well as these resources to ensure your PR is accepted:

- [Gatsby Style Guide](https://www.gatsbyjs.org/contributing/gatsby-style-guide/)
- [Docs contributions](https://www.gatsbyjs.org/contributing/docs-contributions/), including updating the docs sidebar
- [Reference Guide template](https://www.gatsbyjs.org/contributing/docs-templates/#reference-guides)

**Comment by DaniTulp** [comment]
Hi @marcysutton,

I'm working on an outline for this topic. Hopefully I will have a pull request up by tomorrow. If you have any suggestions please let me know!

Happy  #Hacktoberfest

**Comment by marcysutton** [comment]
Closed with #18388.
