### ISSUE TITLE
[docs] Gatsby Style Guide blitz for those new to open source

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#18284]
## Summary

There are a ton of opportunities for small improvements to the [Gatsby Docs](https://www.gatsbyjs.org/docs/) that Hacktoberfest fans could take on. For folks new to open source, here are some ideas for contributing to the docs to make them adhere to the [Gatsby Style Guide](https://www.gatsbyjs.org/contributing/gatsby-style-guide/):

- Update Markdown docs titles to use [Title Case](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#format-titles-and-headers)
- Update titles in the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) to use Title Case
- Update pronouns in a doc to use ["you" and "your"](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#use-you-as-the-pronoun) instead of "we" and "our"
- Fix the [heading order](https://www.gatsbyjs.org/contributing/docs-contributions/#headings) of a doc to create an accessible content hierarchy (e.g. removing an extra h1, making headings go in order, etc.)

Other suggestions are welcome: chime in through the comments below! One approach could be to do a small set of changes to 5-10 docs in a PR, but one change at a time would be welcome too.

### Process recommendations

To make sure your PR is accepted, try to limit its scope to changes that form logical groups. For example, a PR with 5-10 title case changes or a PR with pronoun changes from "we" to "you" would be helpful (see the [Style Guide](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#use-you-as-the-pronoun) for when the subject of "we" is referring to the code).

### Motivation

Grammar enthusiasm and Hacktoberfest for the win!

### Additional resources

- [Gatsby Hacktoberfest umbrella issue](https://github.com/gatsbyjs/gatsby/issues/18129)
- [Gatsby Style Guide](https://www.gatsbyjs.org/contributing/gatsby-style-guide/)
- [How to Open a PR](https://www.gatsbyjs.org/contributing/how-to-open-a-pull-request/)
- [Docs contributions](https://www.gatsbyjs.org/contributing/docs-contributions/)

If you have any questions, feel free to reach out to us here on GitHub or on Twitter or Discord. https://www.gatsbyjs.org/contributing/how-to-contribute/#not-sure-how-to-start-contributing

**Comment by aditsachde** [comment]
I would like to work on this. I am going to start with the documents in the `contributing` folder, if others want to work on a different set of documents.

**Comment by andiegonzalez** [comment]
I would also like to contribute to this! I can start working with the Tutorials section of the documentation. Is that okay?

**Comment by marcysutton** [comment]
Sounds great, @andiegonzalez!

**Comment by jacob-shu** [comment]
I'd love to work on this. We're looking at incorporating Gatsby at our agency and combing through the docs seems like a great way to get more familiar!  Can I tackle the `themes` docs?

**Comment by bhautikbharadava** [comment]
Hey, @marcysutton I would like to work on this issue. Can you help me with what should I pick up?

**Comment by aitchiss** [comment]
I'd like to help with this - it looks like most people are tackling specific folders, and some odd files already have PRs, so with the hope of not treading on anyone's toes, I'd be happy to look at markdown files in the docs folder beginning with 'w' (so 'webpack-and-ssr.md' down to 'write-pages.md'

**Comment by BeniRupp** [comment]
Cool, I will have a look at all files starting with 'u' and 'v' in `docs/docs/`. That is `unit-testing.md` down to `v2-release-notes.md`.

**Comment by samrae7** [comment]
Taking a similar approach, I will do all files in `docs` starting with `t`

**Comment by margueriteroth** [comment]
Love this. I think "R" is up for grabs in the docs folder so I will snag those.

**Comment by chadwyck242** [comment]
Just did one in the 'a' section, about adding comments functionality. Maybe I will also continue working in that area, is anybody else wanting to take some of those? Happy Hacktoberfest =)

**Comment by aditsachde** [comment]
I've gone through the contributions folder and everything seems mostly alright. If its ok, I'm also going to have a look at the docs in the 'docs/docs/' folder starting with `building`, around half of the 'b' articles.

**Comment by LuisPinedaJR** [comment]
Id like to help with this, I see 'q' hasn't been mentioned so I'll do that section :)

**Comment by FissionCat** [comment]
I'd like to help too! Currently looking at 'starters' through to 'styling' in the docs folder.

**Comment by SarahLKatz** [comment]
I'll take the files in the 'docs/docs' folder that start with C, if nobody else has started on those (if someone has, let me know and I'll take a different letter). It will probably be a few PRs since there are ~20 files, so I'm happy to split if anyone else is attached to the letter C.

**Comment by KiranAkadas** [comment]
I'll take the files starting with 'how', hoping no one has started working on it..

**Comment by dosden** [comment]
I would love to work on this can I take docs/docs/ files starting with A

**Comment by dosden** [comment]
#18488

**Comment by KillMonger1** [comment]
I will take up files starting with 'h'. Let me know if anyone is working on it too

**Comment by kaylasween** [comment]
I didn't see anyone mention it, so I'll start on `write-pages`!

**Comment by adibfirman** [comment]
sorry? is already taken by @aitchiss isn't it?

> I didn't see anyone mention it, so I'll start on `w`!

**Comment by kaylasween** [comment]
> sorry? is already taken by @aitchiss isn't it?
> 
> [#18284 (comment)](https://github.com/gatsbyjs/gatsby/issues/18284#issuecomment-539476354)
> 
> > I didn't see anyone mention it, so I'll start on `w`!

Good catch! I've finished it, but won't open a pull request in case @aitchiss is still working on it.

**Comment by aitchiss** [comment]
Hey @kaylasween my changes were merged in #18331. So if your branch is up to date any you found some issues I've missed, you're good to go 🙂

**Comment by Danondso** [comment]
I'd like to help out, @marcysutton has anyone taken docs that start with ```m```?

**Comment by codingCookie** [comment]
I'd like to contribute as well and will grab the `docs/mdx` folder. Is it ok? 
I didn't see anyone mention it.

**Comment by codingCookie** [comment]
I'd like to contribute more 🤗 i would also grad the **GraphQL-Files** in docsFolder - if nobody already claimed those.

**Comment by codingCookie** [comment]
aaand another one - i will grab the letter **'i'** in the **docs-folder** - hope nobody else already grabed it

**Comment by codingCookie** [comment]
so nobody mentioned **'p'** - as far as i see - so i will take care of the p-files

**Comment by chrismgonzalez** [comment]
Looking forward to tackling some of this later tonight!

**Comment by mickm77** [comment]
Unless i missed it - 'c' looks un-taken - i'll do them...

**Comment by muescha** [comment]
@marcysutton 
> Update pronouns in a doc to use "you" and "your" instead of "we" and "our"

Is the you / your here formal or  informal?

For some translations it is important. 

My guess was informal but I may be wrong ...

**Comment by muescha** [comment]
@marcysutton 

Could we add an info if or when headings are capitalized to the s"Gatsby Style Guide section headings"?

I remember you changes often to capitalized but in #18668 it's changed to lowercased.

**Comment by steph-chan** [comment]
I'd like to work on the remainder of the '**s**' docs that have yet to be worked on

**Comment by mendaomn** [comment]
I'm taking on the 'u' docs!

**Comment by aitchiss** [comment]
@menadomn I think @BeniRupp took those a while back?

**Comment by mendaomn** [comment]
> @mendaomn I think @BeniRupp took those a while back?

You are right! I totally missed his comment! I did find some punctuation fixes with the aid of [Grammarly](https://www.grammarly.com), so I was thinking to open a PR anyway. What do you think? Should I discard my changes and work on something else?

**Comment by aitchiss** [comment]
@mendaomn I'm not sure if @BeniRupp's changes are merged back yet or not, but if they are and you've spotted something else that can be tweaked, sure go for it!

**Comment by KorawitRupanya** [comment]
Are there any works that I can do?

**Comment by muescha** [comment]
@KorawitRupanya

you can look for ideas at the [Hacktoberfest 2019 Umbrella Issue](https://github.com/gatsbyjs/gatsby/issues/18129)

**Comment by marcysutton** [comment]
> Is the you / your here formal or informal?
> For some translations it is important.
> My guess was informal but I may be wrong ...

@muescha this PR only covers changes in the English repo, and there isn't really a formal "you" other than "you", and we aren't going to use "thou". 

Once https://github.com/gatsbyjs/gatsby/pull/18424 is merged, there will be further instructions for translation repos.

**Comment by jasonbodman** [comment]
I'll take a look at files in the docs folder beginning with "L" if no one has taken them up.

**Comment by KiranAkadas** [comment]
I'll take a look at the files starting with 'g' if left out

**Comment by josephkmh** [comment]
I'm taking a look at files starting with "p" and "q"

**Comment by sazhang** [comment]
looks like 'o' and 'f' are left so will tackle those

**Comment by jasonbodman** [comment]
Hi - I'll take the available "B" files in the docs/docs folder. (I think that is "babel" to "browser" since the "building" docs are already claimed.

**Comment by brkn** [comment]
I will work on the 'n' files in docs/docs.

**Comment by marcysutton** [comment]
Hacktoberfest is now over, so I'm going to close this issue. Sincere thanks to each and every one of you who took time to contribute to the Gatsby docs: we appreciate you! Stay tuned for more information about this year's custom swag -- you should be notified via email. 💜
