### ISSUE TITLE
Highlights in Gatsby Style Guide Docs

### ISSUE THREAD

**Issue by aditsachde** [gatsbyjs/gatsby#18294]
While working on #18284, I noticed on the style guide page, there are [two blocks under each highlighting example](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#code-formatting-line-highlighting). One is supposed to be an example and the second one is supposed to be the rendered output. 

The issue is the example uses `// highlight-line` which is stripped with regex I believe around [here](https://github.com/gatsbyjs/gatsby/blob/ecc711614e578f542bbd80568d85d509b431f760/www/src/components/code-block/normalize.js#L16).

I would like to submit a PR to fix this, but I'm not really sure about the best way to fix this. I think there are a few options: Modify the regex, use a soft-hyphen to break the regex, or replace the code example with a written example.

I think the 3rd option is the best solution as it probably will be the least brittle. Explanation could be:

---

Use the `// highlight-line` keyword in order to highlight the line the directive is placed on.
`<current example>`

Use the `// highlight-next-line` keyword in order to highlight the line after the directive.
`<current example>`

Use the `// highlight-start` and `//highlight-end` keywords in order to highlight the lines between the two directives.
`<current example>`

**Comment by marcysutton** [comment]
I believe there's a PR open for this, see https://github.com/gatsbyjs/gatsby/pull/17213

**Comment by aditsachde** [comment]
Ah I missed that! 

I'm going to go ahead and close this issue, but an issue might be useful for tracking the PR.
