### ISSUE TITLE
gatsby-source-graphql returns 401 on develop enviroment (only after its first attempt)

### ISSUE THREAD

**Issue by santinfoa** [gatsbyjs/gatsby#18308]
## Description

I'm fetching data from Wordpress using `gatsby-source-graphql`. 
My Wordpress site is protected with htpasswd and the plugin is configured in order to access within the headers. **`gatsby develop` works fine in its first attempt**, but whenever I stop development and re launch it, it start to return bunch of errors:

> 
> The GraphQL query from /home/user/gatsby-proj/src/pages/index.js failed.
> 
> Errors:
>   Unexpected error value: "failed to process https://admin.mywordpresscms.com/wp/wp-content/uploads/2018/03/some-image.jpg\nHTTPError: Response code 401 (Unauthorized)"

This is how I config my source-graphql plugin: 

```js
{
 resolve: `gatsby-source-graphql`,
 options: {
  typeName: `WordPressGraphQl`,
  fieldName: `wpGraphQl`,
  url: `https://admin.mywordpresscms.com/graphql`,
  refetchInterval: 60,
  headers: {
    Authorization: `Basic ${process.env.TOKEN_HTPASSWD}`,
  },
 }
},
```

My temporal solution is clearing the cache every time `gatsby clean && gatsby develop`, but I think it's a bug. 

### Environment

```
  System:
    OS: Linux 5.0 Antergos Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 11.12.0 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 3.7.2 - /usr/bin/python
  npmPackages:
    gatsby: ^2.15.29 => 2.15.29
    gatsby-image: ^2.2.24 => 2.2.24
    gatsby-plugin-emotion: ^4.1.9 => 4.1.9
    gatsby-plugin-google-analytics: ^2.1.20 => 2.1.20
    gatsby-plugin-htaccess: ^1.2.2 => 1.2.2
    gatsby-plugin-manifest: ^2.2.20 => 2.2.20
    gatsby-plugin-netlify: ^2.1.17 => 2.1.17
    gatsby-plugin-offline: ^3.0.11 => 3.0.11
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.2.28 => 2.2.28
    gatsby-plugin-sitemap: ^2.2.16 => 2.2.16
    gatsby-source-filesystem: ^2.1.29 => 2.1.29
    gatsby-source-graphql: ^2.1.17 => 2.1.17
    gatsby-source-wordpress: ^3.1.39 => 3.1.39
    gatsby-transformer-sharp: ^2.2.20 => 2.2.20
    gatsby-wordpress-inline-images: 1.0.0 => 1.0.0
    gatsby-wpgraphql-inline-images: ^0.2.2 => 0.2.2
  npmGlobalPackages:
    gatsby-cli: 2.7.54
```

**Comment by TylerBarnes** [comment]
Hi @santinfoa !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
