### ISSUE TITLE
[gatsby-plugin] How to use files from a plugin? (Making my own library)

### ISSUE THREAD

**Issue by dhhdev** [gatsbyjs/gatsby#18306]
## Summary

I have tried to search far and wide, but I wonder how I can actually use files from a plugin. For example if my plugin has a directory with .svg files, how do I actually get that directory to "transfer" (in lag of a better term) to my actual site. That uses the plugin.

## Example plugin structure

```
gatsby-plugin-<something>
.
├── feathericons
│   ├── activity.svg
│   ├── airplay.svg
│   ├── alert-circle.svg
│   ├── alert-octagon.svg
│   ├── alert-triangle.svg
│   ├── align-center.svg
│   ├── align-justify.svg
│   ├── align-left.svg
│   ├── align-right.svg
│   ├── anchor.svg
│   ├── aperture.svg
│   ├── archive.svg
│   ├── arrow-down-circle.svg
│   ├── ... (and many more .svg files)
├── gatsby-node.js
└── package.json
```

## The Idea

I guess you could call it a library. The really great idea by making a plugin in my view, is that I could share it as a npm package as well. Maybe I am actually thinking about this wrong. but that's the gist of it.

#### The bullet points

- The site I develop on needs some utilities, could be anything else than icons as well.
- By adding the plugin I get those tools.
- It makes it easier to make and maintain a library of files I normally use a lot when working on projects.

**Comment by universse** [comment]
What other kinds of files are you thinking of? How do you intend to use those files?

**Comment by dhhdev** [comment]
@universse, I intend to use those files by simply doing something along the lines of:

```js
import Icon from './path/to/where/icon.svg'
```

What I am trying to get at:

1. Making a plugin with different folders of tools.

This could be icons in .svg format, it could be actual components, or something completely third option.

2.) A way for me to use those files from the plugin, in my actual site code directly.

Maybe, I am thinking of this wrong. But it is basically the same behaviour I want, as it would be for "installing" theme-ui into my project. But I want to this as an actual gatsby specific plugin. (So I could even add some options to the plugin etc. And to keep it specific to gatsby.)

I hope this makes sense.

**Comment by universse** [comment]
Gatsby plugins usually have a noop `index.js` file. I guess in your case you can export your assets from there.

```js
export { Icon } from './path/to/icon.svg'
```

The exporting of assets is manual but I guess you can write a script to automate it.

Then in your app code, import it like so

```js
import { Icon } from 'gatsby-plugin-<something>'
```

For reference, you can look at [gatsby-plugin-google-analytics](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-analytics), where `OutboundLink` is exported from `index.js`.

**Comment by universse** [comment]
You are welcome 🙂
