### ISSUE TITLE
excerpt needs to fall back to pruneLength when no excerpt_separator

### ISSUE THREAD

**Issue by fabianrios** [gatsbyjs/gatsby#18312]
## Summary

excerpt falling back to pruneLength when there is no custom excerpt_separator on the file

### Basic example
config.js

```
{
      resolve: `gatsby-transformer-remark`,
      options: {
        "excerpt_separator": `<!-- endexcerpt -->`
      }
    },
```

template.js

```
node {
          id
          excerpt(pruneLength: 140, format: MARKDOWN)
}
```

### Motivation

I had to put a custom excerpt for just 2 files and the rest will look just fine with the default 140 pruneLength but it turns out it doesn't fall back so I have to manually edit hundreds of files to add a  which wouldn´t have been necessary if the excerpt function just fall back to pruneLength when there is no  in the file.

EDIT: Reproduction example here: samrae7/gatsby-remark-repro

**Comment by samrae7** [comment]
I would like to take this

**Comment by samrae7** [comment]
@fabianrios do your markdown files contain html or just plain markdown? Can you post an example of the formatting you have? Trying to reproduce this issue.

**Comment by samrae7** [comment]
@fabianrios ignore previous question. I have replicated the behaviour with markdown

**Comment by samrae7** [comment]
still working on this. PR coming in next couple of days

**Comment by fabianrios** [comment]
happy to see action was taken, I lost track of this for a while.

**Comment by samrae7** [comment]
Awaiting reviewing response from @pieh

**Comment by samrae7** [comment]
@fabianrios can you review the PR as well?
