### ISSUE TITLE
gatsby-transformer-asciidoc renders include as links (in safe mode too)

### ISSUE THREAD

**Issue by NicoGim** [gatsbyjs/gatsby#18310]
Hi there!

## Description

When running a site using gatsby-transformer-asciidoc, the "include" directives in my .adoc or .asciidoc files are rendered as links instead of displaying the content of the included file.

Example of include directive:
include::include.adoc[]

The link appears as the following text: "include.adoc".
Clicking on it show the underlying page with slug==include.adoc (in using-asciidoc example).

That is normal if the mode is set as "secure", see:
https://github.com/asciidoctor/asciidoctor.js/issues/197

However, this behaviour is also seen when the mode is set to "safe" or "unsafe" which is not expected.

I see two issues here:
- in "safe/unsafe" mode, include should be replaced by the text of the file being included
- in "secure" mode, links should point to slug "include" instead of "include.adoc" which doesn't exist in the example using-asciidoc

### Steps to reproduce

I  forked the gatsby official repo, and added the file
`gatsby/examples/using-asciidoc/src/pages/include.asciidoc`

I also modified `gatsy/examples/using-asciidoc/src/pages/test.adoc`
to replace `include::include.asciidoc.txt[]` with `include::include[]`

Note that if you write "include::include.asciidoc[]" like you are supposed to according to Asciidoc documentation, the link created will be directed to `http://localhost:8000/pages/include.asciidoc/` which doesn't exist...

I've added the following in gatsby-config.js:

>     {
>       resolve: `gatsby-transformer-asciidoc`,
>       options: {
>         attributes: {
>           safe: `safe`,
>           attributes: ["allow-uri-read",]
> 
>         },
>       },
>     },  

So we are (supposed) to be using safe mode. (I also tried with unsafe mode).

That's the only thing I have changed.

**Just clone the following fork here: https://github.com/baozi-technology/gatsby-source-usingasciidoc**
and then run:

> `cd gatsby-source-usingasciidoc/examples/using-asciidoc`
> `gatsby develop`

Go to `http://localhost:8000/pages/test/` in your browser.

### Expected result

The page should show the content of `src/pages/include.asciidoc`:

`= Included \n
yooooo`

### Actual result

Instead, it shows a link to `http://localhost:8000/pages/include/` with text `include`.

### Environment

Result of `gatsby info --clipboard` in `gatsby-source/examples/using-asciidoc`:

  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 12.11.0 - ~/.nvm/versions/node/v12.11.0/bin/node
    Yarn: 1.19.0 - /usr/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.11.0/bin/npm
  Languages:
    Python: 2.7.5 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 60.9.0
  npmPackages:
    gatsby: ^2.0.0 => 2.15.29 
    gatsby-cli: ^2.7.53 => 2.7.53 
    gatsby-plugin-offline: ^2.0.5 => 2.2.10 
    gatsby-plugin-typography: ^2.2.0 => 2.3.11 
    gatsby-source-filesystem: ^2.0.1 => 2.1.29 
    gatsby-transformer-asciidoc: ^1.0.0 => 1.1.12 

Thank you for your help.

**Comment by hirokihokari** [comment]
@NicoGim `safe` option does not belont to attributes.
Ref: https://asciidoctor-docs.netlify.com/asciidoctor.js/processor/convert-options/

```
    {
      resolve: `gatsby-transformer-asciidoc`,
      options: {
        safe: `server`,
        attributes: {
          showtitle: true,
        },
      },
    },
```
will do.

**Comment by NicoGim** [comment]
Hello @hirokihokari. Thanks for your reply. I do not have time to check it right now, but I ended up using  a work around. I basically built the .html file directly with the perl aciidoctor script, and then embed it directly in the React component using "dangerouslySetInnerHTML" attribute.

In my case, I don't really need to generate a slug for each .adoc/.asciidoc file. It's really about having a page with one big chunk of documentation and a table of content (toc). I happen to have many files because that's just how you're supposed to make a long documentation in asciidoc.

That's also an issue, I don't need those pages to be created... It's not for a blog post.

Your solution might be appropriate, I haven't tested it. I well give it a try.
However, I feel like this package was not meant to be used for the most used purpose of Asciidoctor: making software documentation. It was done with blogging and short articles in mind, like with markdown.

**Comment by hirokihokari** [comment]
Hi @NicoGim .
I think gatsby still does a wonder when you only have one long page. After all, in my understanding, gaysby is only trying to bring all the good stuff that's happening recently. 

It seems that your case is one of typical uses of "include" macro of native asciidoc. Have you tried that?

**Comment by NicoGim** [comment]
Hi @hirokihokari!
Thanks for your reply.
Yes, and I as I said in my original message, "include" doesn't function as expected natively when used with the Gatsby plugin. That's why I had to give up with the Gatsby plugin and generate plain html directly with the original ruby command-line tool (I didn't manage to get Asciidoctor JS work as well).

**Comment by hirokihokari** [comment]
@NicoGim my bad!! I just looked at your last response. 

The "link" by include happened to me before and it turned out the asciidoc was not finding the file. I was confused as to specifying the path in the include macro and ended up using attribute to make it easier thereafter (here, "includeDir" attribute)
![F8DCCA5F-2235-47FF-AE98-E80A59AFF786](https://user-images.githubusercontent.com/7416486/68912069-9af6c900-0789-11ea-802b-47c3b9a7e89e.jpeg)

And include a file like
include::{includeDir}/some_file.adoc[]

**Comment by hirokihokari** [comment]
@NicoGim I've tested your reproduction steps and finally figured out what you mean(sorry it took time). 
Yes, the file is not included like that in the example. It looks like asciidoctor transformer doesn't  recognize relative path, whereas native asciidoc(i'm using asciidoctor executable) does. For now, try using absolute path for the included file( from the project root; in this case of using-asciidoc, `/src/pages/include.asciidoc`

**Comment by hirokihokari** [comment]
@NicoGim In case that becomes tedious in the future, in my recent asciidoc/gatsby project, I created a directory for partials, put all the partials in there, and defined an attribute in transformer config, like below:
```
(in gatsby-config.js)
...
    {
      resolve: `gatsby-transformer-asciidoc`,
      options: {
        safe: `server`,
        attributes: {
          partialDir: `/src/pages/_partials`,
        },
      },
    },
...

(in some asciidoc file)
include::{partialDir}/partial1.asciidoc[]
```

**Comment by NicoGim** [comment]
Thanks so much for your tip :thumbsup:, I'll try it out as soon as if I have time for it, probably this week-end.

**Comment by NicoGim** [comment]
While as usual I was too ambitious, didn't have time to test that out - but I guess we can close the issue for now. I'll re-open it if needed.
