### ISSUE TITLE
[gatsby-plugin-netlify] Error: The "headers" option to gatsby-plugin-netlify is in the wrong shape

### ISSUE THREAD

**Issue by ronanlevesque** [gatsbyjs/gatsby#18319]
## Description

I can't run `gatsby build`. The build fails before the end with the following error message: "Error: The "headers" option to gatsby-plugin-netlify is in the wrong shape. You should pass in a object with string keys (representing the paths) and an array of strings as the value (representing the headers). Check your gatsby-config.js."

### Steps to reproduce

1) Start a new Gatsby project
2) Install `gatsby-plugin-netlify`
3) Update `gatsby-config.js` with the following:

```
{
  resolve: "gatsby-plugin-netlify",
  options: {
    mergeSecurityHeaders: false,
    headers: {
      "X-Frame-Options": ["sameorigin"],
      "/**/*.html": ["cache-control: public, max-age=300"],
      "/static/*": ["cache-control: public, max-age=31536000, immutable"],
      "/*.js": ["cache-control: public, max-age=31536000, immutable"],
      "/*.css": ["cache-control: public, max-age=31536000, immutable"],
      "/sw.js": ["cache-control: public, max-age=0, must-revalidate"],
    },
  },
},
```

### Expected result

The build should pass, the configuration above has been used for months without any issue.

### Actual result

Build is failing (see error message above)

### Environment

```
❯ npx gatsby info --clipboard

  System:
    OS: Linux 4.4 Ubuntu 14.04.4 LTS, Trusty Tahr  
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Shell: 4.3.11 - /bin/bash
  Binaries:
    Node: 10.7.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.6 - /usr/bin/python
  npmPackages:
    gatsby: ^2.15.31 => 2.15.31
    gatsby-image: ^2.2.24 => 2.2.24
    gatsby-plugin-manifest: ^2.2.20 => 2.2.20      
    gatsby-plugin-netlify: ^2.1.17 => 2.1.17       
    gatsby-plugin-offline: ^3.0.12 => 3.0.12       
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10  
    gatsby-plugin-sharp: ^2.2.28 => 2.2.28
    gatsby-source-filesystem: ^2.1.29 => 2.1.29    
    gatsby-transformer-sharp: ^2.2.20 => 2.2.20 
```

**Comment by wardpeet** [comment]
Technically the above config wasn't supported but we didn't break so i'll cook up a fix.

**Comment by ronanlevesque** [comment]
Indeed, it should be the following:

`'/*': ['X-Frame-Options: sameorigin'],`

Working fine now :)
