### ISSUE TITLE
-bash: gatsby: command not found

### ISSUE THREAD

**Issue by nancydocode** [gatsbyjs/gatsby#18327]
## Summary
I try to use Gatsby to build my static site, but there is an issue. I installed "npm install -g gatsby-cli" both inside and outside of my project folder and checked scripts in package.json. However, all command doesn't work. I tried gatsy develop, npm gatsby develop, yarn gatsby develop.  
  
  
> Success!
>
> Welcome to the Gatsby CLI! Please visit https://www.gatsbyjs.org/docs/gatsby-cli/ for more information.

HOWEVER,

> -bash: gatsby: command not found## Relevant information

WAIT.

It is worked following the [video](https://www.gatsbyjs.org/docs/quick-start). 

> npm run develop  

instead of 
> gatsby develop

### Environment (if relevant)
Mac OS + Linux

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi. Please make sure that you installed the CLI correctly. Try running `gatsby --version` and see what the result is. Please also provide more information on what you tried and what errors you're seeing (and when). Thanks!
