### ISSUE TITLE
Uppercase of first letter of path on Windows should not happen when running on WSL

### ISSUE THREAD

**Issue by waltercruz** [gatsbyjs/gatsby#18333]
## Description

When running on WSL, the uppercase of first letter introduced on [this merge](https://github.com/gatsbyjs/gatsby/pull/17492) is not needed

### Steps to reproduce

Run gatsby on WSL on windows. See the comments on ticket #16721

I will handle this in some days.

**Comment by stephen-zhao** [comment]
I believe it's actually a non-issue. When running on WSL, `platform()` outputs `'linux'`.

**Comment by waltercruz** [comment]
Sure? Awesome. I will close this ticket then! Thanks @stephen-zhao !
