### ISSUE TITLE
HTML structure gets messed up in Production build.

### ISSUE THREAD

**Issue by mahaveer0496** [gatsbyjs/gatsby#18337]
## Description
- Initial HTML structure in Small viewport is messed up in Production mode. 
- `MobileFooter.jsx` or `DesktopFooter.jsx` is conditionally rendered, using `useMedia` hook from [`react-use`](https://streamich.github.io/react-use/?path=/story/sensors-usemedia--demo) , but the final html structure is a combined version of both `MobileFooter` and `DesktopFooter`
- Please take a look at the [video.](https://drive.google.com/open?id=149P4PInRaSB_7FewYhiGYaMZhjr1k3ST)

### Steps to reproduce
* [Clone the repo](https://github.com/mahaveer0496/bugRepo)
* `yarn develop` then Open browser in Small Viewport (less than 992px), correct footer will be shown (`MobileFooter.jsx`)
* `yarn build -> yarn serve` then Open browser in Small Viewport (less than 992px), incorrect unstyled footer will be shown, **make sure browser window is already less than 992px, if resized, the correct Footer gets rendered**

### Expected result
- Initial render in small viewport should be correct.
- **Notice that `accordion-wrapper-div` is child of `footer.pt-2.pb-2, div.container`**
![Desktop 2019-10-09 00-08-36](https://user-images.githubusercontent.com/23198481/66423376-38dbd300-ea29-11e9-8303-22bcd5326d23.png)

### Actual result
- **Notice that `footer.pt-2.pb-2, div.container` now has a different child `div.row.justify-content` which is actually defined in `DesktopFooter.jsx`, **but** the accordions are still there, so somehow both `DesktopFooter.jsx` and `MobileFooter.jsx` are getting merged in the same viewport .**
 
![Desktop 2019-10-09 00-15-30](https://user-images.githubusercontent.com/23198481/66423832-15fdee80-ea2a-11e9-93de-3afe5595e1de.png)

### Environment

  System:
    OS: Linux 4.15 Linux Mint 19.1 (Tessa)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v11.15.0/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
  npmPackages:
    gatsby: ^2.15.9 => 2.15.33 
    gatsby-image: ^2.2.17 => 2.2.24 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-emotion: ^4.1.6 => 4.1.9 
    gatsby-plugin-manifest: ^2.2.14 => 2.2.20 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.6 => 3.1.10 
    gatsby-plugin-sass: ^2.1.13 => 2.1.17 
    gatsby-plugin-sharp: ^2.2.20 => 2.2.28 
    gatsby-source-filesystem: ^2.1.21 => 2.1.30 
    gatsby-transformer-sharp: ^2.2.13 => 2.2.20 
  npmGlobalPackages:
    gatsby: 2.15.33

**Comment by universse** [comment]
Are you still having issue with this?
