### ISSUE TITLE
[themes] Shadowing components that live in their own folders causes infinite loop clientside

### ISSUE THREAD

**Issue by Jimmydalecleveland** [gatsbyjs/gatsby#18343]
## Description
We have a Theme directory structure where each component has it's own folder. When a site is using that theme, and attempting to shadow the component folder, the browser will freeze (We believe due to a circular import loop). I've provided a repo link below showcasing the issue.

While we do feel that this is not working as intended, we have a workaround (also shown in the repo), but are worried that it may be brittle or not a good practice. We are hoping for some confirmation that it is a bug, or suggestions on stable workarounds. Thanks you masterful wildebeests!

### Steps to reproduce
Follow the readme here to reproduce (requires checking out the bugged branch):
https://github.com/Jimmydalecleveland/gatsby-theme-templates-example

### Expected result
The `master` branch from the link above shows a working standard example of what we want to accomplish. It has a simple component shadow that loads as expected in the browser.

### Actual result
Gatsby builds just fine, but the browser freezes on load. More info in the readme provided.

The `folder-imports-not-working` branch shows our project's structure, but uses the same code as master aside from the `Header` component being in it's own folder as `index.js` which is a pretty common use case when grouping tests, stories, styles, etc. for a component library.

### Environment
Tried on multiple environments, but here is one:
```
System:
   OS: macOS 10.14.1
   CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
   Shell: 5.3 - /bin/zsh
 Binaries:
   Node: 10.16.0 - /usr/local/bin/node
   Yarn: 1.17.3 - /usr/local/bin/yarn
   npm: 6.9.0 - /usr/local/bin/npm
 Languages:
   Python: 2.7.10 - /usr/bin/python
 Browsers:
   Chrome: 77.0.3865.90
   Firefox: 68.0.2
   Safari: 12.0.1
 npmGlobalPackages:
   gatsby-cli: 2.5.9
   gatsby: 1.9.243
```

**Comment by kalebheitzman** [comment]
I'm having this same issue. Not sure how to resolve it.
