### ISSUE TITLE
[docs] update path for using a local starter

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#18347]
## Description

In the [Using a local starter](https://www.gatsbyjs.org/docs/starters/#using-a-local-starter) section of the starter docs, the instructions provided will incorrectly try to access a starter at the Code org on GitHub with this message in the console:

```
info Creating new site from git: https://github.com/Code/blog.git
```

In order to create a local starter with the command, the path needs to be absolute or relative and the gatsby-cli interprets the command in the docs now as being from a GitHub repo.

## What to do

- change the path [here](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/starters.md#L55) instead to `./Code/my-local-starter`
- change the path [here](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/starters.md#L58) instead to `./Code/my-local-starter`

**Comment by Harrison1** [comment]
I'll take this issue, if that's alright
