### ISSUE TITLE
Cannot read property 'frontmatter' of undefined

### ISSUE THREAD

**Issue by topspinppy** [gatsbyjs/gatsby#18363]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by adibfirman** [comment]
Hello @topspinppy 
can you make some steps to reproduce to make clear your issue?
