### ISSUE TITLE
Recommended way to share code between gatsby-node.js and components?

### ISSUE THREAD

**Issue by Kadrian** [gatsbyjs/gatsby#18379]
Since it's node, `gatsby-node.js` uses commonjs, components use ES6 modules.

Say I want to share a function that calculates the slug of a created page:

```
/* export ? */ function getSlug(post) {
   return `/posts/${post.data}${post.title.toLowerCase()}`
}

/* module.exports = { getSlug }; ? */
```

Now I want to import this function both in

- in `gatsby-node.js` to use it in the `createPage` API
- in `Posts.js` to link to the individual post paths.

How would you recommend sharing code & dealing with the different module systems in this case?

**Comment by universse** [comment]
From my experience, you can just import node modules in your browser code like normal. There shouldn't be any issue. Are you facing any problem?

```js
// shared.js
function getSlug(post) {
   return `/posts/${post.data}${post.title.toLowerCase()}`
}

module.exports = { getSlug }
```

```js
// Posts.js

import { getSlug } from './path/to/shared.js'
```
