### ISSUE TITLE
[gatsby-plugin-guess-js] JWT is exposed to the public bundle

### ISSUE THREAD

**Issue by nd0ut** [gatsbyjs/gatsby#18376]
## Description

JWT private key used by `gatsby-plugin-guess-js` is exposed to the public bundle. 

Gatsby site is also affected. See `https://www.gatsbyjs.org/app-e0ba54deda3d5858a927.js`

### Steps to reproduce

There is the minimal config:

```
{
      resolve: "gatsby-plugin-guess-js",
      options: {
        jwt: {
          client_email: `GOOGLE_SERVICE_ACCOUNT_EMAIL`,
          private_key: `GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY`,
        }
}
```

### Expected result

No unused and private data in the production bundle. This also applies to the other gatsby plugins. Every `pluginOptions` is bundled even if they are not used at all by the browser code.

### Actual result

`private_key` content in the production bundle.

**Comment by wardpeet** [comment]
Oh good catch, it's probably because we pass in pluginOptions. We probably want to sanitize it. Thanks for pointing that out.
