### ISSUE TITLE
Double save for apply changes (hot reload bug?)

### ISSUE THREAD

**Issue by qramilq** [gatsbyjs/gatsby#18382]
## Description

When I make changes in `src/pages/index.js` file in file and save it, console says 
```
info i ｢wdm｣: Compiled successfully.
 WAIT  Compiling...      
```
ant then
```
info i ｢wdm｣: Compiling...
 DONE  Compiled successfully in 238ms  
```
but changes not applying. Then I save again, console says again  same text, as above and changes applying.
~~Looks like the compiled files doesn't have changes,~~ because i see, that hot reload fires after first save too.
UPD: if I update page manually (ex. by pressing F5) the changes applies.

### Steps to reproduce
```gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world```
```cd hello-world```
```gatsby develop```

### Expected result

Changes applies after first save

### Actual result

Changes applies after second save.

### Environment

$ gatsby info --clipboard

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - /c/Python27/python

![1](https://user-images.githubusercontent.com/14158291/66484633-00330c80-eab0-11e9-878f-13799912bb96.gif)

**Comment by scottschup** [comment]
Someone on my team is having the same issue, except that it seems like the update is just one save behind. So if you change `Hello world!` to `Hello Gatsby!` and save, nothing. But then if you change `Hello Gatsby!` to `Hellooooooooo!` and save, it will update to `Hello Gatsby!`. A subsequent change and save will update to `Hellooooooooo!`.

I however cannot duplicate the problem locally. His env is:
```
$ gatsby info
  System:
    OS: macOS 10.14.6
    CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.16.0 - /var/folders/7p/tq5wl8cn36z13q1ch8lnnt1r0000gq/T/yarn--1571167847604-0.4859003868186047/node
    Yarn: 1.16.0 - /var/folders/7p/tq5wl8cn36z13q1ch8lnnt1r0000gq/T/yarn--1571167847604-0.4859003868186047/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.3
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.13.52 => 2.13.52
```

The only difference between my env and his is the npm version (mine is 6.4.1 which is the same as OP, so I doubt that has anything to do with it).

**Comment by sidharthachatterjee** [comment]
@qramilq Sorry for not responding to this before!

Can you please try reproducing this with the latest version of `gatsby`? If it is still reproducible, I would love to take a look and help fix this.

**Comment by adamcronin42** [comment]
I'm having the same issues described above. I'm on a MacOS 10.13.5 and just downloaded the starter based on the tutorial. When I make a change to the index.js page I need to save twice before my changes are hot loaded in the browser. If I save just once I have the same issue as @scottschup described above. Any fix for this?

**Comment by scottschup** [comment]
I'm unaware of any resolution. For the guy on my team, he's a manager and just doesn't do much coding anymore so it's no longer an issue for him 😆

**Comment by adamcronin42** [comment]
Fair enough, that works too lol I guess I'll just have to save twice for now.

**Comment by adamcronin42** [comment]
@sidharthachatterjee I've had the same issue using the latest version of gatsby. Any chance we could look into it to find a fix?

**Comment by daydream05** [comment]
Running into the same issue as well

**Comment by mnoster** [comment]
Having this same issue in a project that is not a gatsby project.

**Comment by Zequez** [comment]
Having same issue, although it seems a little more complex than "double save". Most of the time it works, but sometimes it doesn't, and I have to keep saving until it updates. The times it doesn't update, there is no network activity on the site tab, and the "Re-building development bundle" time says around 0.100ms instead of the usual 0.500ms when the changes stick. It doesn't seem to be anything specific from any file, at least to me, it happens randomly when editing the same line on the same file.
<img width="356" alt="Captura de Tela 2020-09-21 às 16 45 49" src="https://user-images.githubusercontent.com/126037/93813964-48e4c680-fc2a-11ea-8225-55cc34ad0c13.png">

**Comment by WichardRiezebos** [comment]
Having the same issue, and it's driving me _crazy_.

**Comment by tu4mo** [comment]
Please file a new issue to get more attention to this. There seems to be many struggling (me included) with hot reload issues but these comments in closed tickets will get lost.
