### ISSUE TITLE
SCRIPT1014: Invalid character error on IE

### ISSUE THREAD

**Issue by TomiTakussaari** [gatsbyjs/gatsby#1839]
Open https://www.gatsbyjs.org/ or https://op-developer.fi  on IE10 or IE11, and you get this kind of error to console, with unfortunate effect of disabling rest of javascript on site:

(I am using Windows 10 & IE11 on Browserstack)

<img width="450" alt="screen shot 2017-08-17 at 0 02 04" src="https://user-images.githubusercontent.com/1768778/29385156-5d765a86-82df-11e7-95df-9b816ade04ba.png">

<img width="538" alt="screen shot 2017-08-17 at 0 02 13" src="https://user-images.githubusercontent.com/1768778/29385159-5f5e902a-82df-11e7-9ff0-aaf356528e09.png">

https://op-developer.fi is using Gatsby 1.6.6, but same problem seems to be with Gatsby 1.8.11 too.
Pre 1.0 versions of Gatsby did seem to work though.

Looking at IE debug tools, it kind of looks like it happens because of backtick usage in [loaders/gatsby-module-loader/patch.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/loaders/gatsby-module-loader/patch.js), but would have though that Babel would convert those.

Also some Gatsby sites seem to work fine, or atleast better, on IE, so not really sure what is going on.

Should Gatsby even still work with IE's ?

**Comment by TomiTakussaari** [comment]
Funny thing is, if I test with IE11 locally, running `gatsby develop`, everything works just fine and there are no errors.

**Comment by TomiTakussaari** [comment]
After replacing backticks on patch.js with double quotes `(")`, I got different error:

<img width="570" alt="screen shot 2017-08-17 at 1 24 30" src="https://user-images.githubusercontent.com/1768778/29387903-fdf4f2b4-82ea-11e7-865a-c0360a6457be.png">

<img width="604" alt="screen shot 2017-08-17 at 1 24 50" src="https://user-images.githubusercontent.com/1768778/29387905-ffce59c2-82ea-11e7-9673-675ab9d31acf.png">

I guess that's enough for today then, no idea how that could work in other browsers, but fail on IE.

**Comment by TomiTakussaari** [comment]
Reverting back to Gatsby 1.5.0 fixed this issue for me.

**Comment by KyleAMathews** [comment]
Lemme know if the latest release with https://github.com/gatsbyjs/gatsby/pull/1901 fixes things!

**Comment by TomiTakussaari** [comment]
#1901 fixed the original error, and for example https://www.gatsbyjs.org/ now seems to work fine on IE, thanks!

But on my site i now get this same error I reported in https://github.com/gatsbyjs/gatsby/issues/1839#issuecomment-322916975.

<img width="693" alt="screen shot 2017-08-25 at 11 25 29" src="https://user-images.githubusercontent.com/1768778/29705845-729af8ea-8988-11e7-9332-435504fa37bb.png">

Apparently it has something to do with my code, because it does not happen universally, but I have no idea what could cause it only on IE & IOS7 Safari. 

Gatsby 1.5.0 is free of this issue as well.

**Comment by KyleAMathews** [comment]
hey progress!

On your error — best way forward is if you can recreate the error in a small reproduction site. Copy your site and try stripping away everything until you have the smallest site possible that still creates the bug. I can look at it then.

**Comment by TomiTakussaari** [comment]
Ok, so apparently this latest "Unable to get property pathname of undefined or null reference"  was because babel-polyfill was imported in gatsby-browser.js, and not in gatsby-node.js/modifyWebpackConfig.

So importing it via gatsby-browser.js worked for some reason until gatsby 1.5, but with later versions it needs to be added via modifyWebpack.

So I guess this is solved by that.
