### ISSUE TITLE
Integrate smartcrop.js for nicer image crops

### ISSUE THREAD

**Issue by chrfritsch** [gatsbyjs/gatsby#18392]
## Summary

Integrate [smartcrop.js](https://www.npmjs.com/package/smartcrop) as fit strategy in gatsby-plugin-sharp.

### Motivation

When currently maxWidth and maxHeight are provided for a fluid image with the COVER strategy, the image will be cropped around the middle. But the focus of an image is often not in the middle. smartcrop.js can figure out where an image should be better cropped around.

**Comment by LekoArts** [comment]
Thank you for opening this!

Sharp already has a feature called `cropFocus` which you can see in action here: https://image-processing.gatsbyjs.org/

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
