### ISSUE TITLE
Create teams similar to Node.js + Jekyll

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#184]
![](https://pbs.twimg.com/media/CdSapZ1W8AADCwL.jpg)

**Comment by KyleAMathews** [comment]
Add to a community page #149

**Comment by NogsMPLS** [comment]
hahahah, yes windows team!

**Comment by KyleAMathews** [comment]
:D exactly!

**Comment by KyleAMathews** [comment]
Increase project management complexity when it's actually necessary.
