### ISSUE TITLE
CSV values to CSS background color

### ISSUE THREAD

**Issue by rishirD** [gatsbyjs/gatsby#18401]
How to parse graphql query data to css values. For ex. if I've data of colors (hex), I want those colors as background color of the div. How can I possibly do this? Screenshot attached with the below link. Thanks.
-
https://ibb.co/wcdrsHt

**Comment by LekoArts** [comment]
Thank you for opening this!

I think universse already gave a good answer. If you need further help you could also ask on Reactiflux or StackOverflow.

We're marking this issue as answered and closing it for now. We hope we managed to help and thank you for using Gatsby!
