### ISSUE TITLE
Paging issues.

### ISSUE THREAD

**Issue by PiccoloYu** [gatsbyjs/gatsby#18429]
I used [gatsby-paginated-blog](https://github.com/NickyMeuleman/gatsby-paginated-blog) To paginate pages,
but its '/src/templates/blog-list.js' and my 'src/pages/pages/index.js' can not be used at the same time. I would like to ask how to modify the Gatsbyjs project to the front page and change'src/pages/indexjs', or The home page of the heading points to '/src/templates/blog-list. js'.

**Comment by jonniebigodes** [comment]
@PiccoloYu can you create a reproduction of your issue, following [steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) in order to fully understand what you intend to achieve and possibly offer a solution for your issue.
