### ISSUE TITLE
404 Flashes Before Showing Correct Page

### ISSUE THREAD

**Issue by jevinsidhu** [gatsbyjs/gatsby#18425]
I'm trying to have the following route render a page: `/tenants/:name`.

I wrote this code in `gatsby-node.js`: 
```
exports.onCreatePage = ({ page, actions }) => {
  const { createPage } = actions;
  if (page.path.includes("tenants")) {
    page.matchPath = `/tenants/:name`;
    createPage(page);
  }
};
```

This works, however, when I build on Netlify, it returns a 404 error in the console. The page still loads the tenants page, but the 404 page flashes first.

This is not broken in development, just when built.

**Comment by jevinsidhu** [comment]
I solved this by adding a check in my `404.js` for the window. If it's `undefined`, I don't render the 404 page.

**Comment by Yosefc** [comment]
Hi, 
I just wanted to say thank you for posting this issue. I was struggling with this, until I found this.

**Comment by ilyador** [comment]
@jevinsidhu can you please share your check code in the 404.js? It's not clear to me what are you checking.

**Comment by jevinsidhu** [comment]
@ilyador 

`const ErrorPage = () => {
  const browser = typeof window !== "undefined" && window;

  return (
    <>
      {browser && (
        <>
          <SEO title="HXOUSE · 404" />
          <Container id="ErrorContainer">
            <Heading>Page Not Found</Heading>
            <HomeButton to="/">Go Back to Home</HomeButton>
          </Container>
        </>
      )}
    </>
  );
};`

**Comment by jevinsidhu** [comment]
@ilyador Here's what my 404.js looks like:

```
const ErrorPage = () => {
  const browser = typeof window !== "undefined" && window;

  return (
    <>
      {browser && (
        <>
            <Heading>Page Not Found</Heading>
            <HomeButton to="/">Go Back to Home</HomeButton>
          </Container>
        </>
      )}
    </>
  );
};
```

**Comment by MiKatre** [comment]
Checking for window "works", but SEO is still completely broken and canonical declared path is still 404.

I updated to gatsby 3 and the problem remains. In my case it seems to come from "gatsby-plugin-react-i18next"

**Comment by leads** [comment]
The 404 change worked for me
