### ISSUE TITLE
Best way to change content inside components

### ISSUE THREAD

**Issue by qramilq** [gatsbyjs/gatsby#18439]
Hello.
I'm making landing page, with composes from different blocks-screens as simple components, for ex. `<Banner/>`.
The `<Banner />` contains some kind of picture as background-image, some text block with exclusive design and button to scroll to a specific block outside <Banner /> component.
I know that in the future I will have cases that will consist in displaying a different set of blocks and changing the content in some blocks depending on the URL. 
For example, in the `<Banner/>`  there will be a different picture and different text, including a change in its design (size, color, etc.)
Question: What is the best way to resolve the issue of changing content in the `<Banner/>`?

**Comment by kimberrypi** [comment]
I may not have the best way but I usually create components thinking about the moving parts of the component. Whenever I think that a part of the component will be heavily customized in the future, I'd rather add it as children. 

So in your case, maybe I'll make a Banner component like this:

```
import React from "react"

const Banner = ({ children, backgroundImage, button }) => {
  return (
    <div className="banner" style={{ backgroundImage: backgroundImage }}>
      {children}
      {button}
    </div>
  )
}

export default Banner

```

and then I'll use the `Banner` component like this.
```
import React from 'react'
import Banner from "./Banner"

const Header = () => {

    return(
        <Banner backgroundImage={image} button={buttonComponent}>
            <h3>some awesome header here</h3>
        </Banner>
    )
}
```

If you think that the button will always be a `Link` for all the Banners, then it's better to include 
`<Link to={link.path}>{link.label}</Link>` in the Banner component instead.
