### ISSUE TITLE
Can not fetch query from within plugin

### ISSUE THREAD

**Issue by Haroenv** [gatsbyjs/gatsby#18437]
## Description

Data which can be fetched with the graphql playground or in a page, is seemingly not available for plugins.

The Algolia plugin uses this `query` argument:

https://github.com/algolia/gatsby-plugin-algolia/blob/cdb0c955230289d0dbfc630a57f71ef83fc026d3/gatsby-node.js#L13

(onPostBuild)

see the original issue here: https://github.com/algolia/gatsby-plugin-algolia/issues/39

### Steps to reproduce

1. Add `gatsby-plugin-airtable` & `gatsby-plugin-algolia`
2. query airtable in the Algolia 

### Expected result

Get the results into airtable

### Actual result

Error is thrown

```
"gatsby-source-airtable" threw an error while running the sourceNodes lifecycle:
Could not find what you are looking for(NOT_FOUND)[Http code 404]
```

### Environment

Sorry, I don't know, @kayali1411 will be able to provide this

**Comment by LekoArts** [comment]
Thank you for opening this!

Please refer with your question to the respective source plugins as we don't maintain those ourselves. Thanks!

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Comment by Haroenv** [comment]
I’m asking this because I maintain the plugin and I don’t know what’s causing the mismatch in life cycle :(

**Comment by LekoArts** [comment]
Pleaes provide a [minimal reproduction][reproduction] then :)

[reproduction]: https://gatsby.dev/reproduction

**Comment by Haroenv** [comment]
asked to the original author if they could add credentials to debug with, in case you do have them (I don't), this should be a repro: https://github.com/Haroenv/gatsby-bug-report
