### ISSUE TITLE
[gatsby-transformer-remark] Interpret frontmatter description as markdown

### ISSUE THREAD

**Issue by LorenzHenk** [gatsbyjs/gatsby#18438]
## Summary

I use `gatsby-transformer-remark` to transform my markdown posts to html. 
In the frontmatter, there is a `description` field for the google search preview description.

I'd like to use markdown in this `description` field as well, but haven't found a way to do so.

## Relevant information

I'd like to have a `frontmatter` similar to this:

```
---
title: "First post"
description: "This is the **first** post!"
---
```

**Comment by LekoArts** [comment]
Thank you for opening this!

Please have a look at this issue: https://github.com/gatsbyjs/gatsby/issues/5021
It should answer your question.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
