### ISSUE TITLE
Document link correctness priority in Docs Contributions

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#18443]
We've seen a couple of PRs (https://github.com/gatsbyjs/gatsby/pull/18396) that intend to fix links in Markdown to other pages in documentation. These PRs fix links for GitHub (but break gatsbyjs.org as a result)

While having links work on both is a nice to have, the priority is to have all links working on gatsbyjs.org

We should document this in https://www.gatsbyjs.org/contributing/docs-contributions/#fixing-image-and-link-paths

**Comment by simhol** [comment]
I'd like to do that, alright?

**Comment by thecodingaviator** [comment]
@simhol I think 2 other contributors have already made PRs for the purpose if they close, you can go ahead. In the meantime, you might want to look for another issue!

**Comment by atuttle** [comment]
Ha, talk about timing. 1 minute apart. :)

**Comment by lannonbr** [comment]
So I'd say since @JoaoJesus94's PR is merged, I'd say this is done. Any opinions @sidharthachatterjee @marcysutton?

**Comment by marcysutton** [comment]
Yep! I can close it. Thanks all!
