### ISSUE TITLE
Can I download sharp-libvips manually? `npm install` is very slow

### ISSUE THREAD

**Issue by zwl1619** [gatsbyjs/gatsby#18458]
Can I download sharp-libvips manually? `npm install` is very slow:

![image](https://user-images.githubusercontent.com/13177997/66581379-92bbd480-ebb2-11e9-8945-97a228ff7041.png)

The last `downloading` command has taken 30 minutes.

**Comment by Pratikkakkad** [comment]
I had the same issue few days ago.
I'm using Windows 10 machine.
To solve this delete `npm-cache `folder from `C:\Users\User_name\npm-cache`

**Comment by sidharthachatterjee** [comment]
Please open this in https://github.com/lovell/sharp

Thanks!
