### ISSUE TITLE
Shadowing a component with a query throws an error

### ISSUE THREAD

**Issue by raphadeluca** [gatsbyjs/gatsby#18451]
## Description
Shadowing `gatsby-theme-blog/src/components/bio.js` throws a GraphQl error:
```
There was an error in your GraphQL query:

Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
- BioQuery
```

### Steps to reproduce

```
gatsby new shadow-component-with-query https://github.com/gatsbyjs/gatsby-starter-blog-theme
```
Shadow  `gatsby-theme-blog/src/components/bio.js` to change some css in the <Image> component. 
You'll get the error above, indicating duplicated documents: the BioQuery (theme file + shadowed file).
Changing the query's name to another resolve the error:
```
const bioQuery = graphql`
  query ShadowedBioQuery {
     ...
}
`
```

### Expected result

Specify in the error that the shadowed query should be renamed. Or delete the theme query before the shadow query comes in.

### Actual result

Error about duplicated documents

Related to [#16927](https://github.com/gatsbyjs/gatsby/issues/16927)

**Comment by laurenskling** [comment]
Renaming the query is just wiping away an actual error.

What is happening is that the _original_ query is being run. as mentioned here: https://github.com/gatsbyjs/gatsby/issues/14611#issuecomment-542762340
You are probably seeing `warn The GraphQL query in the non-page component ...` on your shadow component in the build steps as well

**Comment by laurenskling** [comment]
Just found this: https://github.com/gatsbyjs/gatsby/issues/16927 🎉

**Comment by jsg2021** [comment]
I don't think this was resolved. A shadowed template still prints this warning. One is helpful: It informed me my shadowed query failed. The other warning tells me the theme's query didn't run when my shadowed query works. :}

**Comment by LeonardoGentile** [comment]
I'm using gatsby "3.13.1" and this is still happening to me.
Using `gatsby-theme-blog` I've simply shadowed the `bio` component (for a simple test just copied the entire file) and it throws "Multiple "root" queries found: "BioQuery" and "BioQuery"."
