### ISSUE TITLE
[docs] add onClick prop to gatsby-image API doc

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#18468]
## Description

Support was just added for an `onClick` handler in `gatsby-image` with this PR: #18465 it was documented in the `gatsby-image` plugin but we have the props you can pass in the [Gatsby Image API](https://www.gatsbyjs.org/docs/gatsby-image/#gatsby-image-props) doc as well.

## What to do

Add a similar note to the Gatsby Image API doc that was [added in the PR](https://github.com/gatsbyjs/gatsby/pull/18465/files#diff-25f180d1063d340f290803ba78f32b75L416-L417) that would look something like this:

```
| `onClick` | `func` | Passed to the rendered HTML `img` element |
```

It would go in this table somewhere: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-image.md#L350-L372

**Comment by Slide109** [comment]
Would love to help with this one

**Comment by gillkyle** [comment]
Go for it @Slide109!

**Comment by marcysutton** [comment]
One issue I can see is that image clicks don't provide accessible interactions. We should add a note about providing another UI affordance to complete the same task the click would provide (like a button or link that performs the same action or navigation) https://uxplanet.org/ux-design-glossary-how-to-use-affordances-in-user-interfaces-393c8e9686e4

**Comment by marcysutton** [comment]
In talking internally, we're actually going to roll this feature back as it wasn't thought through in terms of accessibility. Even with notes about affordances in the docs, encouraging clicking on images has the very real potential to produce inaccessible websites; something that conflicts with our [commitment to accessibility](https://www.gatsbyjs.org/blog/2019-04-18-gatsby-commitment-to-accessibility/). We can certainly talk through alternative APIs in future issues if anyone is interested.

**Comment by frankmalafronte** [comment]
sooo, there's still no way to do this?
