### ISSUE TITLE
[gatsby-plugin-offline] Expose public API for to add/remove items to/from the cache

### ISSUE THREAD

**Issue by davidbailey00** [gatsbyjs/gatsby#18498]
## Summary

Expose a public API to allow adding items to, or removing items from, the service worker cache, while using `gatsby-plugin-offline`.

### Basic example

Something like this:

```js
// MyComponent.js

import { clearCache, setCache } from "gatsby-plugin-offline/api"

export function ClearCacheButton() {
  return <button onClick={() => clearCache()}>Clear cache!</button>;
}

export function CacheImageButton({ imageData }) {
  return (
    <button onClick={() => setCache("/myimage.png", imageData)}>
      Store image in cache!
    </button>
  );
}
```

### Motivation

Allow for more control over the service worker without users having to know the low-level implementation details

**Comment by billy-le** [comment]
I would like to give this a go
