### ISSUE TITLE
Mention on css-in-js docs page that a plugin to extract styles is necessary to prevent flash of unstyled content

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#18495]
https://www.gatsbyjs.org/docs/css-in-js/

It should mention that every css-in-js lib has a Gatsby plugin which extracts styles and inserts them into the HTML during builds which prevents FOUC.

It's very common for people to start building with Gatsby & a css-in-js lib and discover later that styles aren't applied until JS loads so we should document why this happens everywhere.

**Comment by maffsojah** [comment]
Hi, I'd love to work on this

**Comment by thecodingaviator** [comment]
@maffsojah feel free to take it

**Comment by thecodingaviator** [comment]
Feel free to take it up @maffsojah
