### ISSUE TITLE
Memory-related regression introduced in gatsby@1.7.0

### ISSUE THREAD

**Issue by bvaughn** [gatsbyjs/gatsby#1849]
This issue is a follow-up for the noisier issue #1754.

After recently trying to upgrade `gatsby`, I am no longer able to run `gatsby develop`. After ~2 minutes of running, the message "_bootstrap finished_" is logged and then the process hangs and eventually runs out of memory.

I've narrowed the cause of this down to `gatsby` version `1.7.0`. (The previous version `1.6.6` works fine.) So the problem is likely [somewhere in here](https://github.com/gatsbyjs/gatsby/compare/52e36b9994a86fc473cd2f966ab6b6f87ee8eedb...9a1103e02251be49a2dfbc796280ec77216abd1a)).

I have not yet had time to dig through the changes to `packages/gatsby` to determine the likely cause of this. However you can reproduce this problem (if you're interested) by checkout out [the `gatsby` branch of `bvaughn/react`](https://github.com/bvaughn/react/tree/gatsby) and running:

```sh
cd path-to-your-checkout/www
yarn install
yarn dev
```

**Comment by jquense** [comment]
my hunch would be it's somewhere in the createLayouts PR, given it was fairly large and did a lot of stuff.

**Comment by KyleAMathews** [comment]
Seems like this is fixed now by https://github.com/gatsbyjs/gatsby/pull/1879!
