### ISSUE TITLE
embed in markdown

### ISSUE THREAD

**Issue by bersot1** [gatsbyjs/gatsby#18503]
## Summary

I need to put a iframe embed in my blog. I saw that there are some plugins, but I couldnt put it to work...

using this plugin for exemplo: gatsby-remark-embed-markdown

gatsby-config.js
![gatsby config](https://user-images.githubusercontent.com/51892738/66647434-4e0a5a80-ebff-11e9-87a2-96a460556c37.png)

my struct
![struct](https://user-images.githubusercontent.com/51892738/66647358-10a5cd00-ebff-11e9-9270-52174fe69b8c.png)

my file html:
![html file](https://user-images.githubusercontent.com/51892738/66647500-798d4500-ebff-11e9-91c5-813843c44204.png)

my md file:
![md file](https://user-images.githubusercontent.com/51892738/66647523-85790700-ebff-11e9-8f6d-4490012b7cda.png)

but when I run this project, does not work... the result in attachment

![result](https://user-images.githubusercontent.com/51892738/66647325-f7048580-ebfe-11e9-92ea-2280a41dfce5.png)

### Environment (if relevant)

  npmPackages:
    gatsby: ^2.15.28 => 2.15.28
    gatsby-image: ^2.2.24 => 2.2.24
    gatsby-link: ^2.2.17 => 2.2.17
    gatsby-plugin-algolia: ^0.3.4 => 0.3.4
    gatsby-plugin-emotion: ^4.1.9 => 4.1.9
    gatsby-plugin-feed: ^2.3.16 => 2.3.16
    gatsby-plugin-gtag: ^1.0.11 => 1.0.11
    gatsby-plugin-layout: ^1.1.10 => 1.1.10
    gatsby-plugin-mdx: ^1.0.46 => 1.0.46
    gatsby-plugin-react-helmet: ^3.1.11 => 3.1.11
    gatsby-plugin-remove-trailing-slashes: ^2.1.9 => 2.1.9
    gatsby-plugin-sharp: ^2.2.28 => 2.2.28
    gatsby-plugin-sitemap: ^2.2.16 => 2.2.16
    gatsby-plugin-styled-components: ^3.1.8 => 3.1.8
    gatsby-remark-copy-linked-files: ^2.1.23 => 2.1.23
    gatsby-remark-embed-markdown: 0.0.4 => 0.0.4
    gatsby-remark-embed-snippet: ^4.1.11 => 4.1.11
    gatsby-remark-images: ^3.1.25 => 3.1.25
    gatsby-remark-prismjs: ^3.3.18 => 3.3.18
    gatsby-source-filesystem: ^2.1.29 => 2.1.29
    gatsby-transformer-remark: ^2.6.28 => 2.6.28
    gatsby-transformer-sharp: ^2.2.20 => 2.2.20

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

Please reach out to the authors of said remark plugins, I'm sure they are able to help you with the issue. As we don't maintain these plugins we don't have any context on their intended usage.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
