### ISSUE TITLE
[gatsby-transformer-remark] get nodes in custom plugin

### ISSUE THREAD

**Issue by isoftninja** [gatsbyjs/gatsby#18516]
There are many nodes with HeadingMetadata type, each of which is for a specific file .md.
File .md is transformed into gatsby-remark-custom-plugin and it is in it that access to data from HeadingMetadata is required. How to do it? the getNodesByType function is not there...

**Comment by LekoArts** [comment]
Thank you for opening this!

Please follow our issue template in the future as I don't currently understand what you're asking. I'd highly appreciate it if you could open a new issue following that or updating this issue.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
