### ISSUE TITLE
gatsby with contenta cms

### ISSUE THREAD

**Issue by Prabuela** [gatsbyjs/gatsby#18510]
> npm start

> gatsby-starter-default@0.1.0 start /var/www/html/gatsby_demo
> npm run develop

> gatsby-starter-default@0.1.0 develop /var/www/html/gatsby_demo
> gatsby develop

success open and validate gatsby-configs - 0.060 s
success load plugins - 0.915 s
success onPreInit - 0.029 s
success initialize cache - 0.037 s
success copy gatsby files - 0.200 s
success onPreBootstrap - 0.037 s
Starting to fetch data from Drupal
articles fetched 9
fetch Drupal data: 105.431ms
success source and transform nodes - 0.379 s
success Add explicit types - 0.034 s

 ERROR 

UNHANDLED REJECTION Encountered an error trying to infer a GraphQL type for: `image___NODE`. There is no corresponding node with the `id` field matching: "567f322c-d594-49bc-a2e3-fea04856e53b".

  Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: `image___NODE`. There is no correspondi  ng node with the `id` field matching: "567f322c-d594-49bc-a2e3-fea04856e53b".
  
  - invariant.js:40 invariant
    [gatsby_demo]/[invariant]/invariant.js:40:15
  
  - add-inferred-fields.js:262 getFieldConfigFromFieldNameConvention
    [gatsby_demo]/[gatsby]/dist/schema/infer/add-inferred-fields.js:262:3
  
  - add-inferred-fields.js:167 getFieldConfig
    [gatsby_demo]/[gatsby]/dist/schema/infer/add-inferred-fields.js:167:19
  
  - add-inferred-fields.js:91 
    [gatsby_demo]/[gatsby]/dist/schema/infer/add-inferred-fields.js:91:25
  
  - Array.forEach
  
  - add-inferred-fields.js:78 addInferredFieldsImpl
    [gatsby_demo]/[gatsby]/dist/schema/infer/add-inferred-fields.js:78:28
  
  - add-inferred-fields.js:42 addInferredFields
    [gatsby_demo]/[gatsby]/dist/schema/infer/add-inferred-fields.js:42:3
  
  - index.js:102 addInferredType
    [gatsby_demo]/[gatsby]/dist/schema/infer/index.js:102:3
  
  - index.js:68 
    [gatsby_demo]/[gatsby]/dist/schema/infer/index.js:68:43
  
  - Array.map
  
  - index.js:68 addInferredTypes
    [gatsby_demo]/[gatsby]/dist/schema/infer/index.js:68:23
  
  - schema.js:161 updateSchemaComposer
    [gatsby_demo]/[gatsby]/dist/schema/schema.js:161:9
  
  - schema.js:82 async buildSchema
    [gatsby_demo]/[gatsby]/dist/schema/schema.js:82:3
  
  - index.js:68 async Object.module.exports.build
    [gatsby_demo]/[gatsby]/dist/schema/index.js:68:18
  
  - index.js:352 async module.exports
    [gatsby_demo]/[gatsby]/dist/bootstrap/index.js:352:3
  
  - develop.js:380 async module.exports
    [gatsby_demo]/[gatsby]/dist/commands/develop.js:380:7
  

⠋ building schema
⠋ Add inferred types
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-default@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/prabu/.npm/_logs/2019-10-11T13_08_50_261Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@0.1.0 start: `npm run develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-default@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/prabu/.npm/_logs/2019-10-11T13_08_50_327Z-debug.log

**Comment by LekoArts** [comment]
Thank you for opening this!

Please reach out to the authors of the source plugin as we don't maintain it ourselves. Hopefully they can help you with your issue. Thanks!

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
