### ISSUE TITLE
NO_COLOR does not work with Ink 

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#18514]
Ink uses chalk internally which does a bunch of magic to figure out whether to render colours or not. 

In /packages/gatsby-cli/src/reporter/index.js we try to set `FORCE_COLOR` to 0 but that is too late because chalk has already initialised and set colours to true.

**Comment by sidharthachatterjee** [comment]
Probably also want to set `hideColors` correctly in /packages/gatsby-cli/src/reporter/loggers/ink/cli.js

**Comment by jmsv** [comment]
@sidharthachatterjee I think the PR referenced above should fix this, although not sure how to test. Do you have repro steps for attempting to disable colours?

**Comment by jmsv** [comment]
nvm, didn't see the other PR :smile: will close

**Comment by sidharthachatterjee** [comment]
@jmsv Sorry for missing your comment! 

Fixed and published in `gatsby-cli@2.8.4` thanks to @Mrigank11
