### ISSUE TITLE
Markdown local variables from frontmatter without using layout or template

### ISSUE THREAD

**Issue by sheedy** [gatsbyjs/gatsby#18526]
## Summary

The ability to reference the frontmatter of a markdown file in the content - **without the need for the added complexity of things like MDX or Gatsby Templates and Layouts**.

I've searched high and low for what is the most basic (fundamental?) feature of almost every static site generator that came before Gatsby and can't seem to find anything.

### Basic example

`example.md`

```
example: "example value"
---

# Example title

Some text that references the *{{example}}* from the frontmatter

```

Should render:

```
Example title

Some text that references the *example value* from the frontmatter
```

[Example](https://medium.com/ia-writer-tips-and-tricks/build-correspondence-templates-in-with-multimarkdown-metadata-e265ff124193)

Video from the above example: https://vimeo.com/158324329

### Motivation

This is the most basic and fundamental feature of a template (static site generator, or not) that appears (from my research) to have been missed or forgotten.

It is almost as old of a concept as markdown itself and anyone who has used any static site generator in the past will have their markdown files written with this in mind (referencing frontmatter in the body/content of the markdown file).

It supports the use case of containing frontmatter variables to the markdown file it lives in, as opposed (or in addition) to exposing them for use in the layouts/templates or elsewhere in Gatsby.

**Comment by sheedy** [comment]
Not stale

**Comment by LekoArts** [comment]
Thank you for opening this!

We don’t support that for Markdown as you can use MDX for that: https://www.gatsbyjs.org/docs/mdx/writing-pages/#using-frontmatter-in-mdx
MDX is

Or reference this issue: https://github.com/gatsbyjs/gatsby/issues/10174

If you’re interested in this feature we'd gladly accept a PR adding it.
