### ISSUE TITLE
How do I create and query collections of mdx content?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#18536]
I have `content` in a folder structure like so:

```
content
  articles
    first-article
      index.mdx
      images
    second-article
      index.mdx
      images
  music
    first-song
      index.mdx
      first-song-artwork.jpg
      first-song-track.mp3
    second-song
      index.mdx
      second-song-artwork.jpg
      second-song-track.mp3
```

...where the articles and music folders are two different content categories, or collections, but both are using mdx as their main file type and delivery mechanism.

So, I did this in the `gatsby-config` file:

```js
{
  resolve: `gatsby-source-filesystem`,
  options: {
    name: `articles`,
    path: `${__dirname}/src/content/articles`
  },
},
{
  resolve: `gatsby-source-filesystem`,
  options: {
    name: `music`,
    path: `${__dirname}/src/content/music`
  },
},
```

...to give each collection a name.

But now I am unsure as to how to proceed in generating nodes, pages, and querying them as two different content types, but both using mdx under the hood.

I want to be able to query both content types (and more in the future) on the `index` page, where they can be combined, sorted, filtered, etc..and then be able to query only one content type on a dedicated page, like an `articles` page, or `music` page, and then have the mdx files generate pages based on templates for each type, or with templates that share some common components, etc. And the most important part is that I am also trying to query my music folder inside a react context file so they can piped into a persistent music player, which I asked about in this issue as well:

https://github.com/gatsbyjs/gatsby/issues/18404

...so I'm not sure what the best way to approach this might be.

@ChristopherBiscardi suggested on twitter that something like this might work:

```js
allFile(filter: { sourceInstanceName: { eq: "the-relevant-name" }) {
  childMdx {
    body
  }
}
```

...but I'm not exactly sure how to make this work in the explorer...or at all...or if there are any other things that i should be considering in regards to what I am trying to accomplish.

For reference, this is the entirety of my `gatsby-node` file, which is as basic as mdx requires, I believe:

```js
const path = require(`path`)
const { createFilePath } = require(`gatsby-source-filesystem`)

exports.onCreateNode = ({ node, getNode, actions }) => {

  const { createNodeField } = actions

  if (node.internal.type === `Mdx`) {

    const slug = createFilePath({ node, getNode })
    
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }

}

exports.createPages = async ({ graphql, actions }) => {

  const { createPage } = actions
  
  const result = await graphql(`
    {
      posts: allMdx {
        edges {
          node {
            fields {
              slug
            }
          }
        }
      }
    }
  `).then(res => res.data )

  result.posts.edges.forEach(({ node }) => {
    createPage({
      path: node.fields.slug,
      component: path.resolve(`./src/templates/article.js`),
      context: {
        slug: node.fields.slug,
        id: node.id
      },
    })
  })
}

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, 'src'), 'node_modules'],
    },
  })
}
```

Any thoughts on the matter would be much appreciated :-)

Thank you XD

**Comment by universse** [comment]
Can you try this?

```js
query MyQuery {
  allMdx(filter: {fileAbsolutePath: {regex: "/content/articles/"}}) {
    edges {
      node {
        fileAbsolutePath
      }
    }
  }
}
```

I believed I answered your other issue as well.

**Comment by rchrdnsh** [comment]
ok, that worked like a charm, thank you very much! XD

**Comment by slimshreydy** [comment]
@universse, I'm running into the same problem. While the solution you've posted does get the job done, is there a way to use the name assigned in `gatsby-config.js` via the options passed to `gatsby-source-filesystem`? This feels a bit unsatisfactory as is, since we need to refer to the raw file paths here, and the name option from `gatsby-source-filesystem` is supposed to prevent that from happening.

**Comment by birdcar** [comment]
@slimshreydy So, I ran into this, and the solution I came up with was to use `allFile` instead of `allMdx` so I could filter on `sourceInstanceName`.

An example of this for a "draft" post type looks like so:

```graphql
query Drafts {
  allFile(filter: {sourceInstanceName: {eq: "draft"}}) {
    nodes {
      childMdx {
        id
        slug
      }
    }
  }
}
```

Using `childMdx` grants you access to the same `Mdx` data you were expecting from `allMdx`, but it allows you to filter based on that specific type.
