### ISSUE TITLE
Class name of css-in-js overwritten after run build & serve

### ISSUE THREAD

**Issue by gengengengengen** [gatsbyjs/gatsby#18547]
## Summary

Please forgive my pool English.

I am using the injectSheet HOC of 'react-jss' to styling my components.

When I run server in development mode, everything look good and class names between jss and elements are matched:
![image](https://user-images.githubusercontent.com/12140810/66698929-f6f6a980-ed14-11e9-827f-5d50b3abf234.png)
![image](https://user-images.githubusercontent.com/12140810/66698932-fd852100-ed14-11e9-8659-5da336902cb1.png)

But when I run build & serve, the page shows wrong styles. The class names of jss become different from development mode:
![image](https://user-images.githubusercontent.com/12140810/66699026-d0853e00-ed15-11e9-899c-24b1e34b3f50.png)
![image](https://user-images.githubusercontent.com/12140810/66699047-f6aade00-ed15-11e9-92b7-3933a7521466.png)

This issue is similar to #8560 but the solutions in that issue didn't work with me.

Thanks a lot.

### Environment

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
  Binaries:
    Node: 10.16.3 - C:\nodejs\node.EXE
    Yarn: 1.19.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.15.33 => 2.15.35 
    gatsby-image: ^2.2.24 => 2.2.27 
    gatsby-plugin-manifest: ^2.2.20 => 2.2.21 
    gatsby-plugin-offline: ^3.0.12 => 3.0.14 
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.11 
    gatsby-plugin-sharp: ^2.2.28 => 2.2.29 
    gatsby-source-filesystem: ^2.1.30 => 2.1.31 
    gatsby-transformer-sharp: ^2.2.20 => 2.2.21 

### File contents

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by daniyals14** [comment]
i can replicate the same issue
