### ISSUE TITLE
New Translation Request - Portuguese

### ISSUE THREAD

**Issue by virginiarcruz** [gatsbyjs/gatsby#18544]
```yaml
name: Portuguese
code: pt
maintainers:
  - virginiarcruz
```

**Comment by jonniebigodes** [comment]
@virginiarcruz i see that you hail from brazil...there's already a issue requesting a portuguese brazilian created in #18178. If you don't mind reply there and coordinate your efforts with the maintainers involved. And if possible close this issue as it's a duplicate

**Comment by tesseralis** [comment]
duplicate of https://github.com/gatsbyjs/gatsby/issues/18178
