### ISSUE TITLE
JS blocking the rendering TTFP

### ISSUE THREAD

**Issue by canvaspixels** [gatsbyjs/gatsby#18549]
##  Summary

I'm testing my new gatsby blog https://courgette-testing.com/blog/the-sdet-qa-handbag-manbag/ and it looks like all the JS is blocking the Time To First Paint even though the blog works without JS. Is there a plugin or something I need to use? I've been digging around for a while. See the waterfall from https://www.webpagetest.org/result/191012_YX_3678b3a8989e95fcf1e9ae592a4e119c/1/details/#waterfall_view_step1

![Screenshot 2019-10-12 at 14 33 38](https://user-images.githubusercontent.com/1353471/66702307-17ffd000-ecfe-11e9-8bab-94b63b198f1b.png)

**Comment by KyleAMathews** [comment]
What are you seeing? All the purple stuff at the bottom is DOM work which happens before the yellow js execution.
