### ISSUE TITLE
Emotion Guide setup produces error at npm start

### ISSUE THREAD

**Issue by Dave-Lindberg** [gatsbyjs/gatsby#18559]
## Description

Following the steps for the Emotion tutorial (https://www.gatsbyjs.org/docs/emotion/), running `npm start` produces the following output: 

```
> gatsby-starter-hello-world@0.1.0 start /Users/dlindberg/Code/emotion-tutorial
> npm run develop


> gatsby-starter-hello-world@0.1.0 develop /Users/dlindberg/Code/emotion-tutorial
> gatsby develop

success open and validate gatsby-configs - 0.029 s
success load plugins - 0.052 s
success onPreInit - 0.020 s
success initialize cache - 0.035 s
success copy gatsby files - 0.064 s
success onPreBootstrap - 0.030 s
success source and transform nodes - 0.050 s
success Add explicit types - 0.022 s
success Add inferred types - 0.071 s
success Processing types - 0.058 s
success building schema - 0.216 s
success createPages - 0.020 s
success createPagesStatefully - 0.068 s
success onPreExtractQueries - 0.020 s
success update schema - 0.041 s
success extract queries from components - 0.107 s
success write out requires - 0.027 s
success write out redirect data - 0.019 s
success onPostBootstrap - 0.020 s
⠀
info bootstrap finished - 2.861 s
⠀
success run static queries - 0.019 s
success run page queries - 0.037 s — 2/2 109.89 queries/second

 ERROR #98123  WEBPACK

Generating SSR bundle failed

/Users/dlindberg/Code/emotion-tutorial/.cache/develop-static-entry.js: Cannot find module '@babel/core'
Require stack:
- /Users/dlindberg/Code/node_modules/@babel/plugin-transform-react-jsx/lib/index.js
- /Users/dlindberg/Code/node_modules/@emotion/babel-preset-css-prop/dist/babel-preset-css-prop.cjs.dev.js
- /Users/dlindberg/Code/node_modules/@emotion/babel-preset-css-prop/dist/babel-preset-css-prop.cjs.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/@babel/core/lib/config/files/index.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/@babel/core/lib/index.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/babel-loader/lib/index.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/gatsby/dist/utils/babel-loader.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/loader-runner/lib/loadLoader.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/webpack/lib/NormalModule.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/webpack/lib/Compiler.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/webpack/lib/webpack.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/gatsby/dist/commands/develop.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/gatsby-cli/lib/create-cli.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/gatsby-cli/lib/index.js
- /Users/dlindberg/Code/emotion-tutorial/node_modules/gatsby/dist/bin/gatsby.js

File: .cache/develop-static-entry.js

⠹ start webpack server
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-hello-world@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-hello-world@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dlindberg/.npm/_logs/2019-10-13T00_41_47_290Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-hello-world@0.1.0 start: `npm run develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-hello-world@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dlindberg/.npm/_logs/2019-10-13T00_41_47_310Z-debug.log

```
### Steps to reproduce

As per https://www.gatsbyjs.org/docs/emotion/: 

> First, open a new terminal window and run the following to create a new site:
> `gatsby new emotion-tutorial https://github.com/gatsbyjs/gatsby-starter-hello-world`
> Second, install the necessary dependencies for Emotion and Gatsby.
> `npm install --save gatsby-plugin-emotion @emotion/core @emotion/styled`
> And then add the plugin to your site’s gatsby-config.js:
> `module.exports = {`
>  ` plugins: [`gatsby-plugin-emotion`],`
> `}`
> Then in your terminal run npm start to start the Gatsby development server.
> 

### Expected result

Oughtta see a new site at localhost/8000

### Actual result

```
⠹ start webpack server
npm ERR! code ELIFECYCLE
... as per above
```
### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

-- This command won't work without Gatsby running :-(

**Comment by jonniebigodes** [comment]
@Dave-Lindberg i've just ran the tutorial to completion without any issues. Checked it with both windows and a wsl machine running on ubuntu 18.04. The only caveat to my setup is the way i have to run gatsby in wsl, i have to run it with su. But going over your log, it seems that there was problem with a package being transfered. If you don't mind, issue `gatsby clean` to purge both `.cache` and `public` folders and delete `node_modules` and run `npm install` and finally after the installation process finish run `gatsby develop`.

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by Dave-Lindberg** [comment]
thanks @jonniebigodes — Happy to work through this, and appreciate the guidance. However, using `gatsby clean` produces `Unknown argument: clean`.

Fwiw, I proceeded to delete `node_modules` and ran `npm install`. Getting the same error on `gatsby develop`....

**Comment by jonniebigodes** [comment]
Quick question, what version of the cli do you have? On your machine can you run `gatsby info` and supply the version of the cli you have installed?

**Comment by Dave-Lindberg** [comment]
Running `gatsby cli` produces the code below. but running `gatsby -v` gives `1.1.51` 

```
Usage: gatsby <command> [options]

Commands:
  gatsby develop                   Start development server. Watches files, rebuilds, and hot reloads if something
                                   changes
  gatsby build                     Build a Gatsby project.
  gatsby serve                     Serve previously built Gatsby site.
  gatsby new [rootPath] [starter]  Create new Gatsby project.

Options:
  --verbose      Turn on verbose output                                                  [boolean] [default: false]
  --no-color     Turn off the color in output                                            [boolean] [default: false]
  -h, --help     Show help                                                                                [boolean]
  -v, --version  Show version number                                                                      [boolean]

Did you mean new?
```

**Comment by jonniebigodes** [comment]
That explains quite a bit. Current version of `gatsby cli` is 2.7.58 and gatsby is 2.15.36. And sometime ago, don't know which version , the clean flag was introduced. Also taking a look at the version you have and the current version, alot as changed in terms of emotion and gatsby. And it probably it introduced the issue you're experiencing. Can you update the cli to the most recent version running `npm install -g gatsby-cli` and try the tutorial again?

**Comment by Dave-Lindberg** [comment]
Well, that provided some progress...

• Successfully upgraded Gatsby CLI to 2.7.58, Gatsby to 2.15.36
• Ran `gatsby clean`
• Deleted `node_modules`
• ran `npm install`

But `gatsby develop` still produces same error

**Comment by Dave-Lindberg** [comment]
Okay — trashed the old Emotion Tutorial which was built with Gatsby 1.x, and created a new instance. Works like a charm. :-)

Really appreciate for your help!

**Comment by jonniebigodes** [comment]
@Dave-Lindberg glad that you managed to get it to work. Sorry if i wasn't more helpfull. Feel free to close this issue as it's now resolved.
