### ISSUE TITLE
[gatsby-plugin-styled-components] Improve default options

### ISSUE THREAD

**Issue by antoinerousseau** [gatsbyjs/gatsby#18563]
## Summary

Improve the developer experience while producing optimized production output.

### Basic example

I think we should either update the plugin documentation, giving a better example, like this:

```js
{
  resolve: `gatsby-plugin-styled-components`,
  options: {
    displayName: process.env.NODE_ENV === `development`,
  },
},
```

Or maybe even set `process.env.NODE_ENV === "development"` as the default value for `displayName`.

### Motivation

People first adding `gatsby-plugin-styled-components` to their project try it without setting any options, and it's usually fine, since options like `displayName` are enabled by default now.
The documentation gives an example disabling it.
But in my opinion, most of the time you need this option enabled in development and disabled in production.

**Comment by LekoArts** [comment]
https://www.styled-components.com/docs/tooling#better-debugging

The official documentation doesn't mention that you absolutely must disable it in production. I also think that it's OK as of right now, people who want to disable it (and have reasons for it) are able to do it.

**Comment by antoinerousseau** [comment]
Well you don't have to minify your JavaScript either, but doing so makes the payload lighter... And there is no obvious advantage not doing it in production

**Comment by LekoArts** [comment]
Updating the documentation (+ including a short explanation what the line does) should be enough IMO.
