### ISSUE TITLE
New Translation Request - Turkish

### ISSUE THREAD

**Issue by batuhantastekin** [gatsbyjs/gatsby#18567]
```yaml
name: Turkish
code: tr
maintainers:
  - batuhantstkn
  - shuetisha
  - raufsamestone
```

**Comment by raufsamestone** [comment]
So exciting!

**Comment by tesseralis** [comment]
@batuhantastekin could you respond with your level of experience with translation and open source software?

@raufsamestone are you interested in being a maintainer? If so, could you do the same/

**Comment by batuhantastekin** [comment]
@tesseralis I experienced translations during 3 years and I’m an engineer for 5 years

**Comment by shuetisha** [comment]
@tesseralis  Hi, I also want to contribute. I'm a native Turkish speaker and it will be my first time on an open source project.

**Comment by ufukcanli** [comment]
@tesseralis I could help too!

**Comment by raufsamestone** [comment]
@tesseralis Hey Nat! I would like to help. Previously, I contributed to Mozilla and Semantic UI for Turkish translation support. I also wrote a tutorial in Turkish for Gatsby; https://www.gatsbyjs.org/docs/awesome-gatsby-resources/#turkish

**Comment by tesseralis** [comment]
Hi @raufsamestone @shuetisha @batuhantastekin !

Your repository [gatsby-tr](https://github.com/gatsbyjs/gatsby-tr) has been created.

Please use this [progress issue](https://github.com/gatsbyjs/gatsby-tr/issues/1) to keep track of the translation progress.

If you are not already a member of the [gatsbyjs GitHub organization](https://github.com/gatsbyjs), you should have received an invitation to join. You must accept the invitation to be able to review translations! If you do not see one, please let the Gatsby team know!

You're free to use the [Gatsby Discord](https://gatsby.dev/discord) to discuss translations. Ask a moderator to create a channel for you in the `#translations` channel.

Finally, make sure to check out the [maintainer responsibilities](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#maintainer-responsibilities) and review your duties as a maintainer.

Feel free to reach out to the Gatsby team if you need any help!

Happy translating!
