### ISSUE TITLE
Automatic page dependency registration not working as described in the docs (ie hot reloading not always working when it should)

### ISSUE THREAD

**Issue by nickyfahey** [gatsbyjs/gatsby#18579]
## Description

When you create a resolver that uses `context.nodeModel` a page dependency is not automatically added unless a path is specified, or you manually call `trackPageDependencies`.

The [schema customisation docs](https://www.gatsbyjs.org/docs/schema-customization/#taking-care-of-hot-reloading) say:

> When you retrieve nodes from the store with `context.nodeModel` methods, it is usually not necessary to do anything manually, because Gatsby will register dependencies for the query results automatically. The exception is `getAllNodes` which will not register data dependencies by default.

It also implies that specifying a connection type in `gatAllNodes` should be enough to add a page dependency. Except hot reloading does not work unless you either specify a path or call `context.nodeModel.trackPageDependencies` in the resolver.

```js
    // This does not add a page dependency:
    const things = context.nodeModel.getAllNodes(
      { type: "BlogPost" },
      { connectionType: "BlogPost" }
    )
    
    // Neither does this:
    const things = await context.nodeModel.runQuery({
    	type: "BlogPost",
    	query: { filter: { title: { eq: "A Blog Post"} } },
    })
    
    // This does work, but specifying the path manually should not be necessary:
    const things = context.nodeModel.getAllNodes(
    	{ type: "BlogPost" },
    	{ connectionType: "BlogPost", path: context.path }
    )
    
    // This will always work:
    const results = await context.nodeModel.runQuery(...)
    context.nodeModel.trackPageDependencies(results, { connectionType: "BlogPost" })
```

### Steps to reproduce

1. Download [this demo project](https://github.com/nickyfahey/gatsby-page-dependency-bug) and run `gatsby develop`
2. With the development site open in a web browser make a change to src/data/thing.yaml

### Expected result

Hot reloading should work. Changes made to the yaml file should automatically be reflected on the page displayed in the web browser.

### Actual result

Nothing happens

### Environment

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.15.36 => 2.15.36 
    gatsby-source-filesystem: ^2.1.31 => 2.1.31 
    gatsby-transformer-yaml: ^2.2.13 => 2.2.13 

### Possible Cause

I've taken a look at [/schema/node-model.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/node-model.js) and [this PR](https://github.com/gatsbyjs/gatsby/pull/16091), and I think I see what's happened.

The node model methods that can add page dependencies are supposed to automatically get the path from context and add it to page dependencies. This was done in `LocalNodeModel.trackPageDependencies` which is used by all other methods that add page dependencies.

```js
 // LocalNodeModel.trackPageDependencies before Materialization changes
trackPageDependencies(result, pageDependencies) {
  const fullDependencies = {
    path: this.path,
    ...(pageDependencies || {}),
  }
  const { path, connectionType } = fullDependencies
  if (path) {
    // add page dependency ...
  }
  return result
}
```

The problem is the code that automatically adds the path has been moved to **Contextual**NodeModel.trackPageDependencies.

```js
// LocalNodeModel
trackPageDependencies(result, pageDependencies = {}) {
	const { path, connectionType } = pageDependencies
	if (path) {
		// The path is never automatically added so if it's not added manually nothing happens
		// add page dependency ...
	}
	return result
}

// ContextualNodeModel
trackPageDependencies(result, pageDependencies) {
	const fullDependencies = {
		path: this.context.path,
		...(pageDependencies || {}),
	}
	return this.nodeModel.trackPageDependencies(result, fullDependencies)
}
```

All other methods in **Contextual**NodeModel are simply a wrapper for **Local**NodeModel. So when you call a context.nodeModel method from a resolver the **Local**NodeModel method is called which then calls **Local**NodeModel.trackPageDependencies which is no longer setting the path automatically and thus does nothing if the path is not given.

Calling context.nodeModel.trackPageDependencies from a resolver does work as expected because it is **Contextual**NodeModel.trackPageDependencies, which does set the path.

### Possible Solutions

I've experimented a bit with a local copy of Gatsby and got the following solutions to work:

The obvious thing to do is simply put code similar to **Contextual**NodeModel.trackPageDependencies that adds the path to `pageDependencies` in all **Contextual**NodeModel methods that can add page dependencies. While this works it doesn't seem ideal as it could easily be missed out if new methods are added in the future.

```js
class ContextualNodeModel {
  ...

  _getFullDependencies(pageDependencies) {
    return {
      path: this.context.path,
      ...(pageDependencies || {})
    };
  }

  getAllNodes(args, pageDependencies) {
    // make sure page dependencies are not added if none are passed
    const fullDependencies = !pageDependencies
      ? null
      : _getFullDependencies(pageDependencies);
    return this.nodeModel.getAllNodes(args, fullDependencies);
  }

  runQuery(args, pageDependencies) {
    return this.nodeModel.runQuery(
      args,
      _getFullDependencies(pageDependencies)
    );
  }

  ...
}
```

My other idea was to replace the `trackPageDependencies` of the referenced **Local**NodeModel in the constructor of **Contextual**NodeModel. So that methods run from a **Contextual**NodeModel will always call a version of `trackPageDependencies` that adds the path. I'm not super experienced with javaScript nor very familiar with the Gatsby code base, so I don't know if this is a good idea.

```js
class ContextualNodeModel {
  constructor(rootNodeModel, context) {
    this.nodeModel = rootNodeModel;
    this.context = context;

    const rootTrackPageDependencies = rootNodeModel.trackPageDependencies.bind(
      rootNodeModel
    );
    this.nodeModel.trackPageDependencies = function(
      result,
      pageDependencies
    ) {
      const fullDependencies = {
        path: context.path,
        ...(pageDependencies || {})
      };
      return rootTrackPageDependencies(result, fullDependencies);
    };
  }

  ...
}
```

Would be happy to make a PR but will wait for feedback on this first.

**Comment by freiksenet** [comment]
Hello @nickyfahey!

Thank you so much for a very detailed issue. I think first solution is what we should do - it's an oversight that we didn't think of when we removed automatic tracking for all `getAllNodes` calls. We can't really do second solution because we shouldn't mutate root nodeModel - it's possible that there are multiple contextual node models running off the same normal nodeModel at the same time, so this would make this impossible.

If you have time, we would love a PR with your first solution. 

Thanks!

**Comment by nickyfahey** [comment]
@freiksenet That makes sense. I was thinking there was probably some kind of issue with that second solution. Will try and get a PR made later today.
