### ISSUE TITLE
Extra comma and " | Gatsby" in showcase details title

### ISSUE THREAD

**Issue by rosslh** [gatsbyjs/gatsby#18571]
## Description

Showcase details pages have an extra `,` and ` | Gatsby` in the document `<title/>`

### Steps to reproduce

- Visit https://www.gatsbyjs.org/showcase/www.metaprojection.ca
- Visit https://www.gatsbyjs.org/showcase/reactjs.org

### Expected result

- The title should be `MetaProjection: Showcase | GatsbyJS`
- The title should be `ReactJS: Showcase | GatsbyJS`

### Actual result

- The title is `MetaProjection,: Showcase | GatsbyJS | GatsbyJS`
- The title is `ReactJS,: Showcase | GatsbyJS | GatsbyJS`

### Environment

Reproduced on:
- OS
  - Kubuntu 16.04
- Browsers
  - Firefox 69.0.02
  - Chrome 77.0.3865.90

**Comment by fboechats** [comment]
@rosslh How can I reproduce it locally??

**Comment by mrkutly** [comment]
It looks like the happens when you link directly to a showcase page. If you navigate to any of them from the showcase index, the title is fine. The extra comma only gets added if you go directly to a show page.

**Comment by mrkutly** [comment]
Digging around I found at least 2 react Helmet components that were tryin to set the title for each page. Setting the prop `titleTemplate=""` for the Helmet in the showcase-details.js component did the trick.
