### ISSUE TITLE
Contributing to the blog with an article about using PrismJs with Gatsby

### ISSUE THREAD

**Issue by FidelVe** [gatsbyjs/gatsby#18585]
## Summary

I'm interested in adding a new entry to the blog about using PrismJs with Gatsby. I'm asking here first to see if the content is appropriate or not for the blog.

### Basic example

You can see the content I want to post in the blog [here](https://dev.to/fidelve/the-definitive-guide-for-using-prismjs-in-gatsby-4708)

### Motivation

Basically my motivation is that I recently went through this while porting my personal website into Gatsby, I needed to get Prism working and there is a lot of information spread out on the web but I did not find everything I needed to do in one place explained in a simple way.

**Comment by LekoArts** [comment]
Thank you for opening this!

Blog posts on our blog should be news, releases, stories, and ephemeral content and sadly I don't see your blog post fitting in these categories. We'd highly appreciate if you'd be up for improving the current README of the plugin if you think some things are missing. Thanks!

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!
