### ISSUE TITLE
Showcase: Referrer not available on external link visits

### ISSUE THREAD

**Issue by colbyfayock** [gatsbyjs/gatsby#18583]
## Description
I've noticed within GA traffic that the showcase I had submitted isn't showing up even 1 time in the traffic source. Now this could definitely simply be no clicks, but out of curiosity, I tried clicking myself while reviewing a GA debugger, looking at `document.referrer`, and GA itself and sure enough, the referrer was blank and the traffic source was defaulted to direct/none.

I tried looking around about it and unless it's intentionally being stripped, it seems like other issues could be security, https => http, but the links are both https.

### Steps to reproduce
* Visit showcase
* Click on Visit Website for one of the sites
* Open your web console and look at `document.referrer`
* It's blank

If you're running a debugger like Observepoint or the GA debugger, typically you can additionally see the traffic source on the new page, which is not available coming from Gatsby.

### Expected result

Clicking an external link from Gatsby should retain the `document.referrer` and additionally be available with Google Analytics or other traffic analytics tools.

### Actual result

```document.referrer=""```

### Environment

https://www.gatsbyjs.org/showcase/

**Comment by wardpeet** [comment]
Refer-policy is currently set on `same-origin` which means we're not exposing any data. By default netlify sets this to `same-origin`, see https://github.com/gatsbyjs/gatsby/pull/13452.

We could change this into `strict-origin` so we expose `https://www.gatsbyjs.org` instead of the full url. I don't have a strong opinion on this but i'm in favor of moving to `strict-origin`

cc @gatsbyjs/core

**Comment by KyleAMathews** [comment]
Yeah I'm surprised we're not already set to strict-origin -- we want people to know they're getting lots of traffic from us!

**Comment by colbyfayock** [comment]
I'm not well versed on this, but reading the [definitions from MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy), would you all want `strict-origin-when-cross-origin`? Sounds like that will allow same origin requests to still utilize referrer, giving you all more insight between internal traffic, and still restrict the cross origin to only the origin. I noticed you all have GA set up, but unsure of what that actually impacts with internal traffic in GA.

**Comment by wardpeet** [comment]
Oh yeah definitely, I didn't look at mdn yet but yes `strict-origin-when-cross-origin
` is what we want, feel free to open a PR!

What need to be done?
Change https://github.com/gatsbyjs/gatsby/blob/acc3031e74761965339e4e2245338f3dadb4ede5/www/gatsby-config.js#L309

into (I haven't tested this so it might nog be 100% correct):
```js
{
  resolve: `gatsby-plugin-netlify`
  options: {
    headers: {
      "/*": [
        `Referrer-Policy: strict-origin-when-cross-origin`,
      ],
    }
  }
}
```

**Comment by colbyfayock** [comment]
cool, ill grab it 👍

**Comment by colbyfayock** [comment]
@wardpeet this should be ready to go over at https://github.com/gatsbyjs/gatsby/pull/18621
