### ISSUE TITLE
Ideas about importing wordpress posts into gatsby?

### ISSUE THREAD

**Issue by omidfi** [gatsbyjs/gatsby#186]
Does anyone know how to migrate a wordpress website into Gatsby?

**Comment by KyleAMathews** [comment]
There's a lot of stuff about exporting Wordpress to Jekyll. Perhaps adopt something like that for Gatsby? https://www.google.com/search?q=wordpress+to+markdown+export&oq=wordpress+to+markdown+export&aqs=chrome..69i57j0j69i64.8622j0j7&sourceid=chrome&ie=UTF-8

**Comment by scottnonnenberg** [comment]
I suspect that the best strategy would be to point people at the jekyll export tools (which are comprehensive), and then have them copy those markdown into a gatsby project. That's how I converted from ghost to gatsby.

**Comment by KyleAMathews** [comment]
@scottnonnenberg agree

**Comment by omidfi** [comment]
Yes I think it might be a selling point for Gatsbu, worth adding to the readme! :)

**Comment by KyleAMathews** [comment]
Added a FAQ item about Jekyll Import. Thanks for the suggestion!

**Comment by omidfi** [comment]
Just for the records, I used this wordpress plugin to export wordpress posts into markdown: 
https://wordpress.org/plugins/jekyll-exporter/

Thanks again for this amazing tool :)

**Comment by Bartekus** [comment]
Then you just answered your own question my friend, partially that is, at least from wordpress side... Convert wordpress posts to markdown, then Gatsby simply reintegrates it :)

**Comment by interglobalmedia** [comment]
Has anyone successfully done this? I'm wavering between Jekyll and something like Gatsby. Any thoughts?

**Comment by KyleAMathews** [comment]
@interglobalmedia have you tried using the Jekyll import tool for Wordpress? Once you've converted your site to Markdown, it'd be easy to try both Jekyll & Gatsby.

Just copy all the Markdown into the `/pages/` directory of the blog starter http://gatsbyjs.github.io/gatsby-starter-blog/ https://github.com/gatsbyjs/gatsby-starter-blog/tree/master/pages

**Comment by interglobalmedia** [comment]
Thanks @KyleAMathews! I just downloaded Gatsby tonight for another project that is not WordPress related. I wanted to try and go with Gatsby because of the easy integration with React. I already know about Jekyll and will use it for WordPress import. I've decided to check out Gatsby for this smaller project that can use the benefits of React. Have the starter blog downloaded for Gatsby. Pretty cool!

**Comment by KyleAMathews** [comment]
Awesome! Let us know if you have any trouble!

**Comment by interglobalmedia** [comment]
I am having trouble with something, but I don't know where it is emanating from. Suddenly when I tried to install MongoDB onto my computer with homebrew, I was denied permission. This was after I had downloaded Gatsby. It related to the /user/local path. Anyone every complain of that problem? Not saying it's Gatsby, but just thought I would throw it out there. Still trying to figure this one out. Of course, it could purely be an Apple/El Capitan issue.

**Comment by interglobalmedia** [comment]
Hey @KyleAMathews , it was an El Capitan/Homebrew issue that THINK I managed to resolve. I will be testing it out tomorrow. Looking forward to playing around with Gatsby tomorrow as well!

**Comment by KyleAMathews** [comment]
great :-)

**Comment by yangmillstheory** [comment]
For live updates you might try leveraging https://en.support.wordpress.com/webhooks/. On AWS this would be a clear API Gateway to Lambda integration.

**Comment by weiran** [comment]
I know this is an old issue but I just built a tool that converts a WordPress export file into Markdown files and folders with images. It's here: https://www.npmjs.com/package/wordpress-gatsby-migrater
