### ISSUE TITLE
Add link to "Minimal Reproduction" docs in bug report issue template

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#18601]
We do have documentation about creating reproduction cases for bug reports: 
https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/ , but we don't really link this in our bug report template ( https://github.com/gatsbyjs/gatsby/blob/master/.github/ISSUE_TEMPLATE/bug_report.md ). Adding link to that document in our bug report template would be great, as it document what nice reproduction looks like.

**Comment by camilaavilarinho** [comment]
I'd like to do this

**Comment by pieh** [comment]
Go ahead @camilaavilarinho!
