### ISSUE TITLE
Root of a country gives 404 when a matchPath is configured for a 404 per country

### ISSUE THREAD

**Issue by zuuperman** [gatsbyjs/gatsby#18604]
## Description

Homepage of a multilingual site gives 404 when there is a 404 configured per language.

### Steps to reproduce

Follow the guide at https://www.gatsbyjs.org/docs/creating-prefixed-404-pages-for-different-languages/ to create a 404 page per country.
Also add a page that acts as homepage per country. The page should have the path:
/uk/

### Expected result
When you browse to the /uk/ page you should see the homepage.

### Actual result
A 404 page is shown.

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v12.4.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.2
    Safari: 13.0.2
  npmPackages:
    gatsby: 2.15.37 => 2.15.37 
    gatsby-image: 2.2.28 => 2.2.28 
    gatsby-plugin-compile-es6-packages: 2.1.0 => 2.1.0 
    gatsby-plugin-env-variables: 1.0.1 => 1.0.1 
    gatsby-plugin-i18n: 1.0.1 => 1.0.1 
    gatsby-plugin-manifest: 2.2.22 => 2.2.22 
    gatsby-plugin-netlify: 2.1.20 => 2.1.20 
    gatsby-plugin-offline: 3.0.15 => 3.0.15 
    gatsby-plugin-react-helmet: 3.1.12 => 3.1.12 
    gatsby-plugin-schema-snapshot: 1.0.0 => 1.0.0 
    gatsby-plugin-sharp: 2.2.30 => 2.2.30 
    gatsby-plugin-sitemap: 2.2.18 => 2.2.18 
    gatsby-plugin-styled-components: 3.1.10 => 3.1.10 
    gatsby-plugin-typescript: 2.1.13 => 2.1.13 
    gatsby-plugin-typography: 2.3.13 => 2.3.13 
    gatsby-plugin-webpack-bundle-analyzer: 1.0.5 => 1.0.5 
    gatsby-source-contentful: 2.1.48 => 2.1.48 
    gatsby-source-filesystem: 2.1.32 => 2.1.32 
    gatsby-transformer-sharp: 2.2.22 => 2.2.22 
  npmGlobalPackages:
    gatsby-cli: 2.6.7

**Comment by sidharthachatterjee** [comment]
@zuuperman Can you please link to a minimal reproduction and reopen this if it's still an issue?

Thanks!

**Comment by pvdz** [comment]
(I tried the steps manually and it seems to work....)
```
gatsby new 404test
npm install
gatsby develop
```
nav to `localhost:8000/uk` and get the generic 404
add the files as per the linked tutorial to `src/uk/404.js` (your 404 should update upon saving) and then the `src/uk/index.js`. Afterwards `localhost:8000/uk` should not give the 404, while `localhist:8000/uk/fail` will give you the `src/uk/404.js` page.

Make sure caching is disabled...

Otherwise a concrete repro, like with an actual repository of the example page where this doesn't work, would be very helpful.
