### ISSUE TITLE
Add two sites to the site showcase

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#18610]
Both https://www.edenspiekermann.com/eu/ and https://www.ibm.com/design/ are using Gatsby, and are missing in our site showcase! Let's add them to the end of https://github.com/gatsbyjs/gatsby/blob/master/docs/sites.yml, and tag them as `featured: true`. 

Detailed instructions here: https://www.gatsbyjs.org/contributing/site-showcase-submissions/

**Comment by luisFilipePT** [comment]
Can I grab this one? (and set myself as assignee)

**Comment by fk** [comment]
Hey Luis! Sure, and done! 🙏

**Comment by fk** [comment]
Thanks again Luis! 🤗
