### ISSUE TITLE
[gatsby-source-contentful] can't connect on windows - proxy

### ISSUE THREAD

**Issue by ariadne-github** [gatsbyjs/gatsby#18614]
## Description
On windows, gatsby-source-contentful cannot connect to Contentful. 
The issue seems related to the new proxy config, it happens only on version 2.1.44 and above.
It doesn't happen on linux systems (tested on AWS Codebuild).
The error goes away by modifying the following line from 'gatsby-coruce-contentful'
in fetch.js line 18:
```
proxy: pluginConfig.get(`proxy`) || false
```
It seems that an undefined proxy object passed down to axios doesn't work, but passing false fixes it.

### Steps to reproduce
Download https://github.com/gatsbyjs/gatsby/tree/master/examples/using-contentful
Do a fresh npm install
run gatsby develop

### Expected result

gatsby develop should work without errors.

### Actual result

gatsby develop aborts with error:
Fetching default locale

 ERROR 

Accessing your Contentful space failed.

### Environment

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Yarn: 1.19.0 - C:\Users\depace\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.8
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.0.0 => 2.16.0
    gatsby-image: ^2.0.5 => 2.2.28
    gatsby-plugin-google-analytics: ^2.0.5 => 2.1.22
    gatsby-plugin-offline: ^2.0.5 => 2.2.10
    gatsby-plugin-typography: ^2.2.0 => 2.3.13
    gatsby-source-contentful: ^2.1.48 => 2.1.48
    gatsby-transformer-remark: ^2.1.1 => 2.6.29

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by pieh** [comment]
Hey, I think we are missing the required modification in the issue description.

Without seeing the change you made, it's also possible that this is a bug in `contentful` package as we just pass `proxy` plugin options forward to it

**Comment by pieh** [comment]
Hmm, do you use `proxy` plugin option? Or don't use it at all?

**Comment by ariadne-github** [comment]
No, I don't use the proxy option, but hte validation forces me to pass either an object or undefined. Undefined produces the error.

**Comment by pieh** [comment]
Super weird that it doesn't happen on macOS, will try to reproduce on Windows

**Comment by pieh** [comment]
Also - what's your node version? (`node -v`)

**Comment by ariadne-github** [comment]
v10.16.3

**Comment by pieh** [comment]
Took a while, but finally found some time to try to reproduce on windows 10 and it seems I don't get this error:
![Screenshot 2019-10-14 at 22 31 28](https://user-images.githubusercontent.com/419821/66780955-62d24100-eed2-11e9-9c06-20e1995613b5.png)

I'm using latest versions of our packages:
```
PS D:\dev\gatsby-v2\examples\using-contentful> gatsby info

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
  Browsers:
    Edge: 42.17134.1038.0
  npmPackages:
    gatsby: ^2.0.0 => 2.16.1
    gatsby-image: ^2.0.5 => 2.2.29
    gatsby-plugin-google-analytics: ^2.0.5 => 2.1.23
    gatsby-plugin-offline: ^2.0.5 => 2.2.10
    gatsby-plugin-typography: ^2.2.0 => 2.3.14
    gatsby-source-contentful: ^2.0.1 => 2.1.49
    gatsby-transformer-remark: ^2.1.1 => 2.6.30
```
and same contentful example as one you reported

I don't have a clue why this happens :/

**Comment by sidharthachatterjee** [comment]
@ariadne-github Closing this for the moment but please feel free to reopen this with a reproduction so we can help in case you're still seeing this. 

Thanks!
