### ISSUE TITLE
Add four sites to the site showcase

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#18613]
- https://pof.com/ 🐠 
- https://www.bitcoin.com/ 💸 
- https://frame.io/ 🎥 
- https://www.sainsburys.co.uk/ 🛒 

are using Gatsby, and are missing in our site showcase! Let's add them to the end of https://github.com/gatsbyjs/gatsby/blob/master/docs/sites.yml, and tag them as `featured: true`. 

Detailed instructions here: https://www.gatsbyjs.org/contributing/site-showcase-submissions/

**Comment by Areadrill** [comment]
Hi, I can take care of this! :)

**Comment by fk** [comment]
Hey @Areadrill! 👋 
Thank you so much! 🙏

**Comment by Areadrill** [comment]
Wow that was fast! I'll make PR at the end of the workday (in about 5-ish hours).

**Comment by fk** [comment]
Well you were fast, too! ;-)
Please don't stress!
