### ISSUE TITLE
Merged Gatsby starter not showing up on https://www.gatsbyjs.org/starters/?v=2

### ISSUE THREAD

**Issue by gojutin** [gatsbyjs/gatsby#18642]
Hello, my pull request for a new Gatsby TypeScript starter was merged on Sept. 23rd, 2019, however, I can't seem to find the starter on [https://www.gatsbyjs.org/starters/?v=2](https://www.gatsbyjs.org/starters/?v=2).

Here is a link to the original PR:

[https://github.com/gatsbyjs/gatsby/pull/17770](https://github.com/gatsbyjs/gatsby/pull/17770)

I'm not sure if it may have fell through the cracks, so I thought I would file an issue. Thanks!

**Comment by Pratikkakkad** [comment]
It will take some time to reflect your changes on [Gatsby](https://gatsbyjs.org) because they must be updating their site periodically in cycle of 2-3 days.

**Comment by gojutin** [comment]
It's been over a month now. Is this typical? I don't mind waiting. I am just starting to think it may have fell through the cracks somehow. Thanks!

**Comment by gojutin** [comment]
Closing this issue as the starter is not showing up in https://www.gatsbyjs.org/starters/.
