### ISSUE TITLE
Hyperlink to join the Discord is broken

### ISSUE THREAD

**Issue by chrismgonzalez** [gatsbyjs/gatsby#18659]
## Description

Links to join the Discord from the Gatsby website or Github repo lead to an error page: "Gatsby.dev's server IP address cannot be found"

### Steps to reproduce

- How to Contribute page on Gatsbyjs.org - Discord link in the "Not Sure How To Start Contributing?" paragraph leads to the error page
- Gatsby repo front page  - Support: Discord link leads to error page.
- Entering "https://gatsby.dev/discord" leads to error page

### Expected result

What should happen?
Link should lead to the ability to obtain Discord credentials

### Actual result

What happened.
Error page shows

### Environment

Web browser

**Comment by chrismgonzalez** [comment]
I would be happy to tackle the issue - updating the to the working hyperlinks if I could get some guidance/correct links.

**Comment by mendaomn** [comment]
Works fine for me, could it have been a temporary issue? Could you please check now? @chrismgonzalez

**Comment by LekoArts** [comment]
It's been a temporary problem, thanks for the issue though!

**Comment by chrismgonzalez** [comment]
It's working today.  Thanks!
