### ISSUE TITLE
Is it necessary to install `gatsby-plugin-catch-links` when using `Link` or is that behavior build into `Link`

### ISSUE THREAD

**Issue by FidelVe** [gatsbyjs/gatsby#18655]
## Summary
I'm seeing that the 'intercepting local links' behaviour of [gatsby-plugin-catch-links](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-remark/src/pages/2017-03-21---copy-linked-files-intercepting-local-links/index.md) is the default behaviour while using `Link` so I guess that is not necessary to `npm install gatsby-plugin-catch-link`. 

Am I correct in this?

**Comment by universse** [comment]
Yeah you're right.

**Comment by FidelVe** [comment]
Thanks!
