### ISSUE TITLE
Is there a possibility create a function that can still run a query Mutate / subscribe after the build?

### ISSUE THREAD

**Issue by D19cannon** [gatsbyjs/gatsby#18664]
Hi,

I've been playing around with Gatsby, WP + Apollo and I am trying to figure out an efficient way to subscribe and mutate (post) data in the WP backend.

The only solutions I can find are usually related using fetch() or axios(). However, I wish to have either to option to send a graphql mutation from the Gatsby or a Node/Apollo server.

As far as I can tell and understand, Gatsby is removing ALL the graphql queries on build including those from Apollo and the ones I made with the normal Gatsby Mutation functions. thus, a mutation query is not possible.

Then I thought it would be nice if Apollo-client & server are hooked up so that the Apollo server would keep track of the WP-graphql schema and run the mutations and subscriptions from there to Gatsby. But WP-graphql has no solution yet as far the documentation goes.

Is there a way for me to either create a function in Gatsby that could send a mutation to WP after build or perhaps a way to get a schema in order to control the graphql queries from the Apollo server?

Thanks! :)

**Comment by LekoArts** [comment]
Thank you for opening this!

You can't use Gatsby's GraphQL layer to send mutations. You can of course use Apollo to do that on the client. Gatsby doesn't remove those queries as React re-hydrates on the client. Maybe that YouTube video helps a bit: https://www.youtube.com/watch?v=ZRQ94PMNEcg

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
