### ISSUE TITLE
Blacklist bad contibutor

### ISSUE THREAD

**Issue by alexandrtovmach** [gatsbyjs/gatsby#18678]
## Summary

Extended version for #18677 please read it first to understand the whole problem. 

A bit more context, the same "language expert" tried to contribute to Spanish translation too:
https://github.com/gatsbyjs/gatsby-es/pull/52
https://github.com/gatsbyjs/gatsby-es/pull/50

And seems like @xmartinezpujol also had some problems with him.
Also, he's removing comments of other contributions and mark is as spam:
![image](https://user-images.githubusercontent.com/28801003/66811826-70231600-ef3a-11e9-986e-c811023a1b70.png)
![image](https://user-images.githubusercontent.com/28801003/66811882-8af58a80-ef3a-11e9-911e-87332c4c3e74.png)

I'd vote for blacklist contributors like him

**Comment by xmartinezpujol** [comment]
Yes, it's something global even, they are contributing in other projects this way. If you check their profiles you can see they are spammers.

I reported them to Github as spammers, I think the case is pretty clear.

**Comment by tesseralis** [comment]
GitHub already deleted that user: https://github.com/gatsbyjs/gatsby-es/pull/50

Thanks for bringing this up!
