### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by alexandrtovmach** [gatsbyjs/gatsby#18677]
## Description

We are working on Russian translation in https://github.com/gatsbyjs/gatsby-ru repo, and in some reason a few not native speakers sending to us PR with robotic translation of docs (Google Translator or something else):

https://github.com/gatsbyjs/gatsby-ru/pull/7
https://github.com/gatsbyjs/gatsby-ru/pull/17

We are still not sure why they are doing that (maybe for a swag 🤔), but we had a real problem with second case. Developer committed directly to `master` without any approval https://github.com/gatsbyjs/gatsby-ru/commit/b6301dce6f229a9e71a8000b8eaa177d37a0c81c, then he is asked to revert it, but it's still a problem.

### Expected result

`master` branch should be protected from direct commits and allow only PR approach.

### Actual result

Everyone, with member rights able to commit directly to `master`.

**Comment by m-allanson** [comment]
Thanks for pointing this out @alexandrtovmach. The `gatsby-es` and `gatsby-ru` repos now have branch protection and require a CODEOWNERS code review before merging PRs.

**Comment by alexandrtovmach** [comment]
@m-allanson Thank you
