### ISSUE TITLE
Why is gatsby-cli a dependency of gatsby?

### ISSUE THREAD

**Issue by wodenx** [gatsbyjs/gatsby#18672]
## Summary

A follow-on to https://github.com/gatsbyjs/gatsby/pull/14863.  I understand why react-cli needs to declare react/react-dom as dependencies -- but why does gatsby itself need to depend on react-cli?

## Relevant information

Again, the issue is with a monorepo.  We have react defined as a peerDependency for most our packages, and install it at the repo root.  We have an example site in the repo (as well as a gatsby theme), both of which depend on gatsby.  As a result, if we don't keep our react/react-dom versions at the package root in sync with the versions declared in gatsby-cli, we get multiple copies of react.

Would it be possible to move whatever is required by both gatsby and gatsby-cli to a separate package, and make this a dep of both?  Or to make gatsby-cli a peerDependency of gatsby, and require ppl to install it in their site?

\

**Comment by thchia** [comment]
Also, gatsby-cli recently listed React in its dependencies, which is causing issues due to multiple copies of React.

**Comment by wodenx** [comment]
Yes - that was exactly the problem for us.   I understand that gatsby-cli needs react as a dependency (otherwise you couldn't run it without first installing react globally) -- so I'm proposing we move up the chain of dependencies and remove the dep of gatsby on gatsby-cli.

**Comment by pieh** [comment]
Gatsby is making heavy use of `reporter` utility that is part of gatsby-cli (which propably should be ripped out to be separate package). But the issue would remain, because it's actually `reporter` that needs `react` as it uses [ink](https://github.com/vadimdemedes/ink) (React for CLIs) to build out CLI output. And we can't just rely on `react` installed for gatsby site, because CLI can be used as global, so it has to work on it's own.

What issues are there exactly with potentially 2 copies of react?

**Comment by thchia** [comment]
The issue with 2 copies of React is that it will break. It’s a known prohibition (it even throws an error saying that you can’t have 2 copies of React).

**Comment by pieh** [comment]
> The issue with 2 copies of React is that it will break. It’s a known prohibition (it even throws an error saying that you can’t have 2 copies of React.

But one is dependency of CLI - so if there will be 2 copies of react, one will be in `gatsby-cli/node_modules/react`, and nothing on the frontend should ever use that and cli will always use that one (as specified by node module resolution).

It would be different story if one of frontend component depended on react, but it's not the case here.

**Comment by sidharthachatterjee** [comment]
Looks like this is already answered by @pieh 

Closing this for now @wodenx but please feel free to open another issue with a reproduction _if_ this is a bug that we can fix. 

Thanks!
