### ISSUE TITLE
MiniCssExtractPlugin not used in production

### ISSUE THREAD

**Issue by sixclones** [gatsbyjs/gatsby#18682]
## Description

According to [source code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack-utils.js#L184-L192), the plugin [MiniCssExtractPlugin](https://github.com/webpack-contrib/mini-css-extract-plugin) should be used in production mode.  
What I'm seeing it that's not the case.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).
1. Git clone [this repo](https://git.dinde.pro/Sixclones/gatsby-sixclones).
2. `npm run build` after (`npm i`).
3. Serve the `index.html` in `public` directory (`cd public && php -S localhost:3000`).
4. Open the page in a browser.
5. Check network requests, no css files are loaded.

### Expected result

It seems to me that CSS should be loaded on a separate file and not inline (maybe I misunderstood something about Gatsby).

### Actual result

CSS are written in the html file.

### Environment

```
System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
    Shell: 5.5.1 - /usr/bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 69.0.2
  npmPackages:
    gatsby: ^2.16.1 => 2.16.1
    gatsby-image: ^2.2.29 => 2.2.29
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23
    gatsby-plugin-offline: ^3.0.16 => 3.0.16
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13
    gatsby-plugin-sharp: ^2.2.31 => 2.2.31
    gatsby-source-filesystem: ^2.1.33 => 2.1.33
    gatsby-transformer-sharp: ^2.2.23 => 2.2.23
```

**Comment by mendaomn** [comment]
Hey! 

Inlining CSS in the head of the HTML document is a common practice to improve performance, as it greatly reduces the time to first paint. 

I'm not sure about the plugin you are referring to, but my guess is Gatsby is using the plug-in to process the CSS before inlining it into the HTML!

**Comment by sixclones** [comment]
Ok thx for the information, I think my issue comes from an misundertanding of the Gatsby code source and how to use the plugin.
