### ISSUE TITLE
gatsby build Building static HTML failed

### ISSUE THREAD

**Issue by Fdango** [gatsbyjs/gatsby#18688]
my components:

```javascript
import React from 'react'
import PropTypes from 'prop-types'
import AceEditor from 'react-ace'
import 'brace/mode/xml';
import 'brace/theme/github';
import { defaults, pick } from 'lodash'
import styled from 'styled-components'

const Wrapper = styled.div`

  .ace_gutter {
    background: #f9f9f9 !important;
  }

  .ace_gutter-active-line {
    background: transparent;
  }

  .ace_active-line {
    background: transparent;
  }
`

const Editor = ({ mode, theme , setOptions, value}) => {
  return (
      <Wrapper
        height="auto"
        width="100%"
      >
        <AceEditor
          mode={mode}
          theme= {theme}
          value={value}
          width="100%"
          height="auto"
          editorProps={{$blockScrolling: true}}
          onLoad={editor =>
            editor.selection.moveCursorToPosition({ row: 0, column: 0 })}
          focus
          setOptions={defaults({}, setOptions || {}, {
            useSoftTabs: true,
            tabSize: 2,
          })}
        />
      </Wrapper>
    ) 

}


Editor.propTypes = {
  mode: PropTypes.string.isRequired,
  theme: PropTypes.string.isRequired
}

export default Editor

```

index.js:
```javascript
import { Editor } from '../components/common/editor'

<Editor
    mode="xml"
    theme="github"
    value={previewHEML}
    setOptions={{ minLines: 20, maxLines: 20 }}
>
</Editor> 

```

**Comment by Pratikkakkad** [comment]
Can you provide the error message.?

**Comment by urielhdz** [comment]
The error should help us to debug the problem, but I think we can see potential problems with the code you provided. You are using the AceEditor react component which [does not work in server side rendering environments](https://github.com/securingsincity/react-ace/issues/27), this could produce errors during the build step of Gatsby.

There are some suggestions on [the Gatsby docs](https://www.gatsbyjs.org/docs/using-client-side-only-packages/) on how to use client-side only packages, like `react-ace`.  I think that the solution that involves loading your component with `loadable` could work for you, you can check the how to in [this section](https://www.gatsbyjs.org/docs/using-client-side-only-packages/#workaround-3-load-client-side-dependent-components-with-react-loadable) of the gatsby docs.

**Comment by Fdango** [comment]
> 您可以提供错误消息吗？

Building static HTML failed

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html undefined



  Error:

not finished Building static HTML for pages - 3.588s


But I have followed the instructions of https://gatsby.dev/debug-html , but I can't avoid this mistake.

**Comment by Fdango** [comment]
> ，

Well, I'm sorry. I tried the method provided by the official website. Maybe I didn't use the right method or how I said it. I posted a new error. I pasted my changed code and reported the error.

Aceeditor.js :

`import React, { Component } from "react"
import PropTypes from 'prop-types'
import AceEditor from 'react-ace'
import Loadable from "@loadable/component"
import 'brace/mode/xml';
import 'brace/theme/github';
import { defaults, pick } from 'lodash'
import styled from 'styled-components'

const Wrapper = styled.div`

  .ace_gutter {
    background: #f9f9f9 !important;
  }

  .ace_gutter-active-line {
    background: transparent;
  }

  .ace_active-line {
    background: transparent;
  }
`

const Editor = ({ mode, theme , setOptions, value}) => {
  return (
      <Wrapper
        height="auto"
        width="100%"
      >
        <AceEditor
          mode={mode}
          theme= {theme}
          value={value}
          width="100%"
          height="auto"
          editorProps={{$blockScrolling: true}}
          onLoad={editor =>
            editor.selection.moveCursorToPosition({ row: 0, column: 0 })}
          focus
          setOptions={defaults({}, setOptions || {}, {
            useSoftTabs: true,
            tabSize: 2,
          })}
        />
      </Wrapper>
    ) 

}


Editor.propTypes = {
  mode: PropTypes.string.isRequired,
  theme: PropTypes.string.isRequired
}

const LoadableEditor = Loadable(() => import("./Editor"))
export default LoadableEditor
`

error:
The above error occurred in the <StoreStateProvider> component:
    in StoreStateProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.


 ERROR

Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.

**Comment by Fdango** [comment]
@urielhdz Thank you. I used @ loadable / component to pack successfully. But after packing, I opened build / index.html and found that my component was missing. Can you tell me what happened?

**Comment by jonniebigodes** [comment]
@Fdango if you can please make a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be better looked at? Based on your actual info it's not enough to further help you.

**Comment by Fdango** [comment]
@jonniebigodes okey, thanks.

**Comment by rizkyian78** [comment]
136 | 
  137 |                       <td className="tech hide-on-mobile">
> 138 |                         {tech.length > 0 &&
      |                               ^
  139 |                           tech.map((item, i) => (
  140 |                             <span key={i}>
  141 |                               <span key={i}>{item}</span>


Are some one have solution about this problem?. it said:
WebpackError: TypeError: Cannot read property 'length' of null

Thank you
