### ISSUE TITLE
[gatsby-source-wordpress] Incorrect names for GraphQL nodes

### ISSUE THREAD

**Issue by jezallan** [gatsbyjs/gatsby#1869]
For WordPress.com API (could potentially be issue for WordPress.org) the GraphQL nodes created for media, types, statuses and taxonomies differ from documentation. The `type` of these entities are prefixed by `wp_` such that the query must be for example `allWordpressWpMedia` and not `allWordpressMedia` as per docs.

**Comment by sebastienfi** [comment]
Thanks for reporting that.

**Comment by jezallan** [comment]
As soon as I get a chance to check self hosted WP I will put in a PR

**Comment by KyleAMathews** [comment]
Is this issue still current?

**Comment by jezallan** [comment]
Outdated now as docs longer reference allWordpressMedia
