### ISSUE TITLE
More inclusive language in docs

### ISSUE THREAD

**Issue by carolstran** [gatsbyjs/gatsby#18702]
:wave: Sorry I'm ignoring all of your well-thought-out issue templates, but hear me out... 

I noticed that there are a couple of instances of words like "simply" and "easily" in your documentation. Unfortunately, words like this can make people feel frustrated and isolated while reading (myself included, hence the issue) - especially if they are facing issues.

If it's alright with your team, I'd like to take a shot at updating the content to make it more inclusive by removing instances of "simply", "easy", "just", etc. I use the Gatsby often and I'm planning to create a plugin related to this, so I'm happy to help 😊  

Also if you're interested or want more information on this topic, I'd highly recommend watching Jim Fisher's [Don't Say Simply](https://www.youtube.com/watch?v=gsT2BBWBVmM) talk from Write the Docs Prague 2018 ✍️ 🤓 

Thank you for the work you do and please let me know if you need more details!

**Comment by marcysutton** [comment]
That would be fantastic, @carolstran! We would love to have your contributions. I've edited words like that out in every place I see them (particularly in new PRs), but haven't gotten to them all obviously. Thanks for bringing this up!

**Comment by muescha** [comment]
@carolstran you are working on the plugin?

Maybe it fit in the PR #18942 prettier/link setup as bad word settings?

**Comment by carolstran** [comment]
👋 👋 👋  So sorry, I've been on a long vacation so this fell off my plate. I'd still love to tackle this if that's alright/assuming it's still relevant - although I can wait until #18942 is merged. 

@muescha - There are plans for a plugin! @mehtavishwa30 is heading that effort though 🤗

**Comment by AishaBlake** [comment]
I think this is still worth doing! I try to keep an eye on any new docs that come in but there are still a bunch of these types of phrases scattered throughout the docs. Opening this up via label in the hopes that someone will tackle it.

**Comment by muescha** [comment]
i remember that i see a remark-lint plugin which check this....

**Comment by muescha** [comment]
maybe it was this https://github.com/11ty/eleventy-plugin-inclusive-language but i don't checked it

**Comment by gdstewart** [comment]
I'm going to give this a go! Are the docs in the contributing folder included in this as well?

**Comment by fgiuliani** [comment]
@muescha I see you reopened this issue. Is there anything left to do? Can I contribute someway?

**Comment by muescha** [comment]
maybe find more words for inclusive language?

even it would be good if there is a linter for inclusive language?

**Comment by muescha** [comment]
this 11ty plugin also suggest this words - i don't know which we can also change in the docs and in the [Style Guide - Avoid “easy” and “simple”](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#avoid-easy-and-simple):

```javascript
options.words = "simply,obviously,basically,of course,clearly,just,everyone knows,however,easy";
```
*source: https://github.com/11ty/eleventy-plugin-inclusive-language/blob/master/.eleventy.js#L14*

**Comment by gdstewart** [comment]
I submitted a pull request up above earlier last month with a bunch of fairly cursory replacements. I'm not sure if anyone took a look at it. This seems like the sort of issue that would never really be closed and would be an ongoing process, no?

**Comment by fgiuliani** [comment]
Hey @muescha I created this PR with some changes and fixes

https://github.com/gatsbyjs/gatsby/pull/26294

**Comment by Nilovra** [comment]
Is this issue still open? Can i contribute something?

**Comment by wardpeet** [comment]
We're always open to get improvements on our docs :)

**Comment by LekoArts** [comment]
Yeah, this is still open :) @carolstran wrote a post about it here, too: https://dev.to/meeshkan/how-to-remove-condescending-language-from-documentation-4a5p

**Comment by vvkpd** [comment]
I would like to work on this card, could you please assign to me.
Thanks

**Comment by PseudoNerd** [comment]
Can I take this up ?

**Comment by Lucas-Dalamarta** [comment]
I would like to contribute to this issue, may i ?

**Comment by LekoArts** [comment]
Feel free to send in a PR although please notice that we won't accept PRs that just search/grep for `easily` and remove everything. Please read https://dev.to/meeshkan/how-to-remove-condescending-language-from-documentation-4a5p and especially point 3 to understand that sometimes the removal is not necessary or that with the removal the sentence needs to be restructured to have the same meaning.

**Comment by carolstran** [comment]
Totally regret letting this fall off my plate 🙈  Apologies to the maintainers for all of the extra effort dealing with this now 🤪

**Comment by noahsburroughs** [comment]
I removed/replaced the vast majority of occurrences of non-inclusive language in the docs. I used @carolstran wonderful guide to do so. There's still a need for some granular issues, but this tackles near all of them.

**Comment by noahsb** [comment]
Please keep this issue open. I submitted a PR that contributes to this and is still in need of a review (#27252)
