### ISSUE TITLE
Gatsby v1 and Disqus

### ISSUE THREAD

**Issue by nickeblewis** [gatsbyjs/gatsby#1872]
I have until now been using react-disqus but have had trouble getting it to work in Gatsby V1. Does anyone have a recommended approach to integrating Gatsby now?

**Comment by theiliad** [comment]
I'm just doing this in gatsby 1.8.12 and it works
```js
<ReactDisqusThread
            shortname="YOUR_SHORTNAME"
            title="Example Thread"
            onNewComment={this.handleNewComment}/>
```
