### ISSUE TITLE
netlify use problem

### ISSUE THREAD

**Issue by PiccoloYu** [gatsbyjs/gatsby#18720]
I have successfully deployed my website on netlifly, but there are still some problems. When I enter the homepage, I will judge as follows:
` ` ` `
Const rootPath = `${PATH_PREFIX_}/`;
Const test = location. Pathname = = = rootpath;
< div classname = {` main ${test? 'main_sreen': (url = = = 'article'? 'main_img': 'main_none')} `} > < div >
` ` ` `
There will be a problem with the website deployed in netlifly. When entering the website, the judgment of class name is always incorrect. When entering the website, you should point to "main_sreen" instead of "main_none". This will only happen when I first enter my website. If I use link to jump to the homepage, it will be judged correctly.

**Comment by PiccoloYu** [comment]
In this way, I assign a variable to this class through judgment, and the a variable is dynamic.
![image](https://user-images.githubusercontent.com/44945137/66912486-40146980-f045-11e9-9c2e-4438ef5f87e9.png)
His first entry is supposed to be the 'main_sreen'.His output is exactly like this
![image](https://user-images.githubusercontent.com/44945137/66912527-502c4900-f045-11e9-9466-32b33bf9ff37.png)
but..
![image](https://user-images.githubusercontent.com/44945137/66912561-60dcbf00-f045-11e9-891b-c45e4a88e13f.png)
I don't know why it's like this.

**Comment by universse** [comment]
are you using `gatsby-plugin-offline`?

**Comment by PiccoloYu** [comment]
> 你在用`gatsby-plugin-offline`吗？

yes

**Comment by universse** [comment]
I'm assuming you are using gatsby-plugin-layout as well? Take a look [here](https://github.com/gatsbyjs/gatsby/issues/13867#issuecomment-489481343).

**Comment by PiccoloYu** [comment]
> I'm assuming you are using `gatsby-plugin-layout` as well? Take a look [here](https://github.com/gatsbyjs/gatsby/issues/13867#issuecomment-489481343).

thank you very much. This really helped me.

**Comment by universse** [comment]
you are welcome
