### ISSUE TITLE
Temporary dynamic routes 

### ISSUE THREAD

**Issue by kompounder** [gatsbyjs/gatsby#18744]
Hi,

I am evaluating Gatsby for a project that enables users to create their own content on the site.

Let's say that:
- The UGC (user-generated content) is immediately stored in a DB/CMS
- We know what the URL & slug should be at the time of content submission (e.g. it could be something like https://site.com/article/best-beer-ever-2019

Questions:
1) What would be the best technical approach to serve such content dynamically until the static page is built?
2) Is it possible to keep both (temporary dynamic route and the subsequently generated static page) on the same URL?
3) Can Gatsby Link be used on both routes? (e.g. in the case of the dynamic route, for the purpose of serving any static elements such as header and footer immediately until the dynamic content is loaded a few seconds later)

Thank you!

**Comment by kompounder** [comment]
Thank you. I tried the client-only route and it works well - it doesn't conflict statically generated pages. Gatsby-link works as well.

**Comment by universse** [comment]
You are welcome.

**Comment by mcclaskiem** [comment]
@kompounder Have you experienced any SEO issues with the redirect approach for handling this scenario? Also is there some sort of param to check if a static pages exists that is built in to Gatsby?
