### ISSUE TITLE
How do I query an audio file in a staticQuery from some MDX frontmatter?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#18742]
I am trying to query an audio file that is referenced in the frontmatter of an MDX file. My frontmatter looks like this:

```mdx
---
name: Bash
artist: RYKR
genre: Electro
bpm: 124 bpm
artwork: bash.jpg
alt: Bash artwork.
audio: bash.mp3
description: What streamers and confetti sound like if they have souls.
release: 2019-02-01
---
```

The `audio` key is referencing an audio file in the same folder as the `mdx` file. I am then trying to query and use the audio file in a staticQuery inside a context file, like so:

```graphql
const tracks = useStaticQuery(graphql`
    query Tracks { 
      allMdx(filter: {fileAbsolutePath: {regex: "/content/music/"}}) {
        edges {
          node {
            fields {
              slug
            }
            frontmatter {
              name
              artist
              genre
              bpm
              artwork {
                childImageSharp {
                    fluid(maxWidth: 1000) {
                      ...GatsbyImageSharpFluid
                    }
                  }
              }
              alt
              description
              release(formatString: "MMMM Do, YYYY")
              audio {
                absolutePath
              }
            }
          }
        }
      }
    }
  `)
```

...but I have no idea whether or not the absolutePath is actually giving me the file so that I can play it, or just the path to the file. I have been banging my head against the explorer trying to figure out how to do this, but have yet to figure it out at all. I have no idea which sub field to use to get the file so that i can play it back.

Here is a picture of all the sub fields, and none of them seem to simply get the file for me, but I have no idea what half of them even are, and some of them make no sense, like why would there be a `childMdx` sub field of a frontmatter key:value pair?

I have been able to get all of the other frontmatter fields to work, except for this one, as everything else in the query seems to work.

I end up converting the query into a array of objects like so:

```
const trackList = useMemo(
    () =>
      tracks.allMdx.edges.map(track => {
        const { frontmatter } = track.node
        const { name, artist, genre, bpm, artwork, alt, description, audio } = frontmatter

        return { name, artist, genre, bpm, artwork, alt, description, audio }
      }),
    [tracks]
  )
```

but the `audio` just doesn't seem to work, and I don't know how to fix it.

Thank you for any help and assistance that you can give me :-)

R

**Comment by rchrdnsh** [comment]
I actually got this answered somewhere else @gatsbybot, so I'll close this now :-)

**Comment by 454de6e** [comment]
> I actually got this answered somewhere else @gatsbybot, so I'll close this now :-)

Do you have a linkt to the answer?

**Comment by ashishch-98** [comment]
I also have the same issue. Can you please provide the solution that worked for you?

> I actually got this answered somewhere else @gatsbybot, so I'll close this now :-)
