### ISSUE TITLE
What's the best approach to add tags with images?

### ISSUE THREAD

**Issue by ghost** [gatsbyjs/gatsby#18740]
I'm trying to figure out the best approach to adding images to tags. 

Ideally, each tag should have a corresponding image. Example: Tag: **Pizza** has image of 🍕

Any suggestions?

**Comment by cryptofool13** [comment]
do you mean by tag? like html tag <Pizza />?

**Comment by urielhdz** [comment]
You may list your tags on a JSON file and use the [gatsby-transformer-json]( https://www.gatsbyjs.org/packages/gatsby-transformer-json/), you can structure your data like this:

```json
[
 { tag:"pizza", image:"pizza.png" }
]
```

I think that the simplest way to handle dynamic images is to put them in the public folder of a Gatsby site, then you can refer to those images while listing your tags. For example

```javascript
(props)=>{
  <div>
    <span>{props.tag}</span>
    <img src={props.image} /> {/* This route is absolute to your domain if images are placed on the public folder */}
  </div>
}
```

**Comment by LekoArts** [comment]
Let's close this issue as the author's account was deleted.
