### ISSUE TITLE
[gatsby-react-router-scroll] Scroll updates when navigating within the same pathname.

### ISSUE THREAD

**Issue by cloudratha** [gatsbyjs/gatsby#18758]
## Description

When on a page e.g. `/test/`, I use `navigate` to replace the current location state to reference a marker on the page. 

```js
navigate('/test/', { state: { marker }, replace: true })
```

Even though I'm on the same page, the scroll position is set back to the top.

I found this reference in the pakage:

https://github.com/gatsbyjs/gatsby/blob/e4fc96a8d10f861f2f559a77095c790db6f908a9/packages/gatsby-react-router-scroll/src/ScrollBehaviorContext.js#L36-L46

To me this short circuit would never fire, as we are comparing two objects. Shouldn't it rather be

```js
if (location.pathname === prevLocation.pathname) {
    return
}
```

The above is even described in `scroll-behaviour` https://github.com/taion/scroll-behavior#custom-scroll-behavior

NB: This happens if I use navigate from the page prop or import @reach/router.

### Steps to reproduce

If you need me to make a demo repo I guess I can, but the above clearly explains the issue.

### Expected result

If navigating with `navigate` to the same page, scroll position should be preserved.

### Actual result

When navigating with `navigate` to the same page, scroll position is set to 0.

### Environment

System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0.3
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.15.16 => 2.15.16
    gatsby-image: ^2.2.20 => 2.2.20
    gatsby-plugin-create-client-paths: ^2.1.12 => 2.1.12
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16
    gatsby-plugin-offline: ^3.0.7 => 3.0.7
    gatsby-plugin-preload-fonts: ^1.0.14 => 1.0.14
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7
    gatsby-plugin-sharp: ^2.2.22 => 2.2.22
    gatsby-plugin-styled-components: ^3.1.8 => 3.1.8
    gatsby-plugin-transition-link: ^1.13.0 => 1.13.0
    gatsby-source-filesystem: ^2.1.26 => 2.1.26
    gatsby-transformer-json: ^2.2.9 => 2.2.9
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14
  npmGlobalPackages:
    gatsby-cli: 2.7.47

**Comment by cloudratha** [comment]
This can obviously be solved with the `shouldUpdateScroll` browser api method, however I don't see the value in the short circuit, and I'm inclined to think it should be the default behaviour.

**Comment by LekoArts** [comment]
Thanks for the issue! Seems reasonable. Would you be up for submitting a PR fixing it?

**Comment by LekoArts** [comment]
The PR fixing it is currently WIP

**Comment by chandlervdw** [comment]
@LekoArts which PR? Has it merged yet?
