### ISSUE TITLE
[docs] add console.log instructions to debugging the build process

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#18778]
## Description

A suggestion from documentation feedback asked if there was a way to `console.log()` output from the build process. Reviewing the [Debugging the Build Process](https://www.gatsbyjs.org/docs/debugging-the-build-process/#vs-code-debugger-auto-config) doc shows a detailed guide on setting up debugging for VSCode or the Chrome developer tools. However, at its simplest, knowledge that you can `console.log` output from different steps in the build process is nice to be aware of and is much more approachable to those familiar with the browser's `console.log` than setting up new configurations for more sophisticated debugging.

## What to Do

I propose we add a section into the guide with a title like "Node.js console logging" that could mention Node.js' built-in console. 

This section could provide code snippets of places like in [Gatsby Node APIs](https://www.gatsbyjs.org/docs/node-apis/) or in a `gatsby-config` where you can log information and see it show up in logs that could help someone unfamiliar with Gatsby internals to see where their code is being executed in the build process. It could also help to link off to resources like [Overview of the Gatsby Build Process](https://www.gatsbyjs.org/docs/overview-of-the-gatsby-build-process/) for more information.

**Comment by kriswep** [comment]
I‘d like to write something regarding that.
Could you assign me?

**Comment by gillkyle** [comment]
Thanks @kriswep, it's all yours!
