### ISSUE TITLE
[docs] add more specific file instructions for Using Gatsby Image doc

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#18775]
## Description

Several comments on the [Using Gatsby Image](https://www.gatsbyjs.org/docs/using-gatsby-image/) doc mentioned their difficulty understanding where the GraphQL query should be added in step 4 of the instructions. Currently, the code block example in step 4 just shows a GraphQL query, that query is what would be used in the same code block in step 5, but the instructions don't make that super clear.

![image](https://user-images.githubusercontent.com/21114044/67026484-0f741480-f0c5-11e9-9530-594963b8e027.png)

What the code titles look like:

<img width="723" alt="Screen Shot 2019-10-17 at 10 01 36 AM" src="https://user-images.githubusercontent.com/21114044/67026534-274b9880-f0c5-11e9-9348-ece51ac1b365.png">

## What to Do

I propose a good course of action would be updating the code blocks for step 4 and 5 with a title (like in [other code blocks in the same doc](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/using-gatsby-image.md#L60)) to state that the code for each step would be in the same file (maybe something like `src/pages/my-page.js`). 

Ideally, we could update the code blocks in both places to show all the code that would be in that file (both the query and the react component), and then add code line highlighting (example [here](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/using-gatsby-image.md#L65-L72)) to show what code is added at the corresponding step, either step 4 or step 5.

**Comment by sazhang** [comment]
hey, i'd love to tackle this. thanks!

**Comment by gillkyle** [comment]
Sure thing, go for it @sazhang!

**Comment by sazhang** [comment]
@gillkyle I added more to the existing page query, but the embedded videos show an example of a StaticQuery. This may or may not confuse readers, so I’m open to changing the example to stick with what is shown in the videos. Thanks!
