### ISSUE TITLE
[docs] convert reach router and Gatsby stub article to a short doc

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#18781]
## Description

The doc for [Reach Router and Gatsby](https://www.gatsbyjs.org/docs/reach-router-and-gatsby/) is a stub right now, waiting to be filled in. Several comments from the feedback widget have noted finding this page empty is frustrating.

Adding at least an overview of how the two are related would be better than nothing. 

## What to Do

Add some simple information about how Gatsby uses Reach Router under the hood for routing between pages, possible including a code snippet about how you can `import { Router } from "@reach/router"` and then add routes like you would in other React apps.

This page shouldn't just say the same things that other related pages explain about Gatsby's routing, but should add more context specific to Reach Router.

**Comment by tylerwray** [comment]
🙋🏻‍♂️I'll be happy to take this one.

**Comment by tylerwray** [comment]
Got a PR up. I'd love any feedback.
