### ISSUE TITLE
Hide component path in componentChunkName

### ISSUE THREAD

**Issue by d4rekanguok** [gatsbyjs/gatsby#18791]
## Summary

Currently, the component path is exposed publicly via `window.___chunkMapping`:

```
___chunkMapping

"component---src-pages-blog-tags-js": [ "/component---src-pages-blog-tags-js-f81e0bfcd17d0da590e9.js" ]
"component---src-pages-contributing-events-js": [ "/component---src-pages-contributing-events-js-1c105d1d9312ff38c747.js" ]
...
```

I recently saw this SO question <sup>[link](https://stackoverflow.com/questions/58389721/rename-webpack-gatsby-chunkmapping-strings)</sup> & I think it's reasonable to hide these path, maybe only in production build.

Upon a bit of search, I found that the code here is responsible for generating:

https://github.com/gatsbyjs/gatsby/blob/f59ba1542b7328c3abd0b57895baad0bffae515c/packages/gatsby/src/utils/js-chunk-names.js#L11-L12

I tested my idea with `uuidv5`:

```js
  const NAMESPACE = `c8e9d964-7090-46ef-a1ed-8311a822b0e7`

  return process.env.NODE_ENV === `production`
    ? `component---${uuidv5(name, NAMESPACE)}`
    : `component---${kebabCase(name)}`
```

All local unit tests passed & the site I tested this on seems to perform as expected.

```
___chunkMapping

"component---11d478fe-6a55-579c-becf-625ab1e57cf4": [ "/component---11d478fe-6a55-579c-becf-625ab1e57cf4-76c90ae50035c52657a0.js" ]
"component---15c76861-b723-5e0a-823c-b6832aeeb0a0": [ "/component---15c76861-b723-5e0a-823c-b6832aeeb0a0-18eb457ba6c147e1b31b.js" ]
```

What do you think? Should the component path in componentChunkName be hidden?

**Comment by davidhellsing** [comment]
+1

**Comment by d4rekanguok** [comment]
This would affect the caching of currently deployed Gatsby sites, so perhaps we can consider making it an opt-in thing? Like an option in `gatsby-config.js` maybe. 

What do you think @pieh @wardpeet? Could this be considered, or is it a `wont fix` thing?

**Comment by sidharthachatterjee** [comment]
Just discussed with @pvdz @pieh and @m-allanson and we're unsure if this is a good default to have. 

While we see the value in obfuscation, debugability is important to DX in general and human readable names should be preferred over hashes. 

We'd like to avoid adding (yet another) config option to toggle this because that's an obligation to maintain. Let's hear what other folks have to say and we'll move forward accordingly. 

Thank you for bringing this up!

**Comment by youngmanalive** [comment]
+1

Is this still a possibility? The chunk names in the `CDATA` show up in SEO, which has caused multiple issues and headaches for us due to specific words that are forbidden through certain advertising policies.

**Comment by thatjimmy** [comment]
+1 

Just would like to add that having the chunk names (acting as essentially a sitemap) visible in the source is not ideal. Would love to have some way to obfuscate these if possible. We use gatsby for making landing pages for example so there is not a lot of linking between the pages we generate. But competitors or anyone else can see more of our pages than we'd like if they cared to look. Thanks.
