### ISSUE TITLE
Override default options of gatsby-plugin-page-creator doesn't work on windows.

### ISSUE THREAD

**Issue by zteric** [gatsbyjs/gatsby#18795]
## Description

Can not override default options of gatsby-plugin-page-creator on windows because the path can not match.

### Steps to reproduce
I was tring to override the default configurations to avoid some of the files being turned into real pages but failed.
Here's the configuration. 

```
//gatsby-config.js
{
      resolve: 'gatsby-plugin-page-creator',
      options: {
        path: `${__dirname}/src/pages`,
        ignore: {
          patterns: [`**/components/**`],
          options: { nocase: true },
        }
      },
    }
```

Here's what I found after exploring and debug in source code.

`packages/gatsby/src/bootstrap/load-plugins/load.js `
![gatsby](https://user-images.githubusercontent.com/19619837/67076977-cef9c100-f1c0-11e9-8fc1-a56ecd0c8f24.PNG)

### Expected result

Default options can be overrided correctly on windows.

### Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  Binaries:
    Yarn: 1.18.0 - C:\Users\CP697290\AppData\Roaming\npm\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.16.1 => 2.16.1
    gatsby-image: ^2.2.29 => 2.2.29
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23
    gatsby-plugin-offline: ^3.0.16 => 3.0.16
    gatsby-plugin-page-creator: 2.1.27 => 2.1.27
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13
    gatsby-plugin-sharp: ^2.2.31 => 2.2.31
    gatsby-plugin-styled-components: 3.1.11 => 3.1.11
    gatsby-source-filesystem: ^2.1.33 => 2.1.33
    gatsby-transformer-sharp: ^2.2.23 => 2.2.23

**Comment by universse** [comment]
It should be

```js
  ...
  return (
    plugin.resolve === `gatsby-plugin-page-creator` &&
    slash(plugin.options.path) === slash(path.join(program.directory, `src/pages`))
  )
```

You're welcome to open a pull request :)

**Comment by zteric** [comment]
> It should be
> 
> ```js
>   ...
>   return (
>     plugin.resolve === `gatsby-plugin-page-creator` &&
>     slash(plugin.options.path) === slash(path.join(program.directory, `src/pages`))
>   )
> ```
> 
> You're welcome to open a pull request :)

Sure, I've fixed it on my local while debugging and will open a pull request.Thanks.
