### ISSUE TITLE
Sanitise Error in gatsby telemetry

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#18808]
We used to sanitise Error in telemetry and still have code for it in the `sanitizeError` function in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-telemetry/src/error-helpers.js but appears that we don't use it anymore. 

Most errors passed to this are structured errors and shouldn't have an issue. However for other errors, the entire Error object is _indeed_ passed through in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/structured-errors/construct-error.js#L16

And our validation in Joi at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/structured-errors/construct-error.js#L30 allows anything (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/structured-errors/error-schema.js) 🤕 

Hence we need to call `sanitizeError` on the Error here to ensure we remove a couple of unnecessary fields here

**Comment by mrkutly** [comment]
@sidharthachatterjee I would like to work on this if it is open. Is this the only error that needs to be sanitized? Or are there other places where the sanitization is not happening?

**Comment by blainekasten** [comment]
@sidharthachatterjee is this still an issue do you know?
