### ISSUE TITLE
Gatsby compilation much Slower with ink than yurnalist's logger

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#18801]
I have got a big application to build with gatsby,
 
i constated a build much more slower still i ve got updated my gatsby, (it's not related to the last version but the logger to use), i found out that the cause is the logger

I checked that if i force gatsby to use the logger yurnalist instead by default Ink that gatsby-cli select, my application build in 30sec less time!

AS well in all my scrappy code i use lot of console.log that slow down the logger and the time spent to build... ok certainly console.log is not the best way to log, but everybody use that.

Certainly will be great to check and benchmark that as a build time is important for an user, maybe put in default yurnalist?

**Comment by sidharthachatterjee** [comment]
Hello! This is a known issue and is being tracked in https://github.com/gatsbyjs/gatsby/issues/15505

Let's continue the conversation there. Closing this for now! Thank you for opening nonetheless.
