### ISSUE TITLE
Mark gatsby binary as an executable in gatsby-dev-cli

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#18809]
When `gatsby-dev-cli` copies over files in a local project, it doesn't mark the `gatsby` binary in `node_modules/.bin` as an executable which causes running `yarn gatsby develop` to fail. 

We fix this by running `chmod +x node_modules/.bin/gatsby` but it would be nice to get to the root of this issue and fix it in `gatsby-dev-cli`

**Comment by blainekasten** [comment]
It looks like the reason this occurs is on the OS level. https://github.com/jprichardson/node-fs-extra/issues/278

**Comment by blainekasten** [comment]
Actually, we don't copy the bin over. because the bin is in `node_modules/.bin/gatsby`. I think this is happening during the install step.

**Comment by blainekasten** [comment]
Okay, learning new things. `node_modules/.bin/gatsby` is created by the install step. it is a symlink to `gatsby/dist/bin/gatsby.js`.

From what I can tell now, yarn or npm does some special thing with the bin field from the package.json, where it will grab that path and chmod it for us.

**Comment by blainekasten** [comment]
Confirmed: https://github.com/yarnpkg/yarn/blob/98d51d88310eede3d6394a20d5a11dbb258cb54b/src/package-linker.js#L44

**Comment by blainekasten** [comment]
PR incoming
