### ISSUE TITLE
Accessibility audit of official starters and themes

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#18803]
We have several official starters and themes in this repository now and I think it's a good time to consider auditing them for accessibility. 

We should audit the following

### Starters

- [ ] blog
- [ ] default
- [ ] gatsby-starter-blog-theme
- [ ] gatsby-starter-blog-theme-core
- [ ] gatsby-starter-notes-theme
- [ ] gatsby-starter-theme
- [ ] gatsby-starter-theme-workspace
- [ ] hello-world

### Themes

- [ ] gatsby-theme-blog
- [ ] gatsby-theme-blog-core
- [ ] gatsby-theme-notes

**Comment by sidharthachatterjee** [comment]
Tagging the core team accessibility expert @madalynrose 🎉

**Comment by harshil1712** [comment]
Hey :wave:,
Can I work on this too? 
This is great opportunity to learn more about a11y and from the expert @madalynrose herself!

**Comment by madalynrose** [comment]
@harshil1712 yes please do! I'm so excited that people are interested!

**Comment by harshil1712** [comment]
Hey @madalynrose any suggestions you have that I should keep in mind?
I will soon be completing Marcy's FrontendMasters course on Accessibility. I am planning to first start working with the starters and then work with the themes.

**Comment by madalynrose** [comment]
Absolutely! I'm working on a checklist and a rich list of resources that will make it easier for people to do audits but it's not ready yet. 

In the meantime, check out my posts on [how to get set up to manually test accessibility](https://www.gatsbyjs.org/blog/2019-11-13-getting-set-up-to-manually-test-web-accessibility/) and about [keyboard navigation with screen readers](https://dev.to/madalynrose/5-things-you-need-to-know-about-manual-accessibility-testing-with-the-keyboard-and-screen-readers-3512). 

There are a lot of ways to do an audit and you'll find one that feels best for you. Here are two that I really like:
* @marcysutton's [method](https://marcysutton.com/how-i-audit-a-website-for-accessibility)
* @lkopacz's [method](https://www.a11ywithlindsey.com/blog/web-accessibility-testing-process)

Additionally, there are _tons_ of resources that might be helpful, but if we're keeping the scope to basics and auditing, I recommend looking at:
* [A11y With Lindsey](https://www.a11ywithlindsey.com)
* [any resources on this page](https://marcysutton.com/links/)
* [a11y.coffee](https://a11y.coffee/)

**Comment by shrthnd** [comment]
@sidharthachatterjee et al., I would also like to help but this issue hasn't been updated for a while. 

Is there a backlog of outstanding a11y-related tasks you can share?

**Comment by LekoArts** [comment]
The current state of the starters is sufficient in terms of a11y
