### ISSUE TITLE
[site-showcase-validator] check source_url in entries are public

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#18805]
## Summary

Have a way for the site showcase validator to notify us if an entry has a `source_url` pointing to a private repo.

### Basic example

Say I have a site at gatsby-site.dev and in the entry I have the `source_url` at https://github.com/lannonbr/gatsby-site, but that repo is private. then we should contact the site maintainer to either make the repo public or remove the `source_url` field from the entry.

This could likely be done in the matter of when we go through each entry, if the entry has a source_url, take that URL, send a fetch request to it, and if it doesn't return a 200 response, log it.

**Comment by lekterable** [comment]
I could pick it up

**Comment by lannonbr** [comment]
Go ahead!
