### ISSUE TITLE
:focus not working in safari and firefox....

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#18811]
Trying to add some buttons to my site, this time using the `navigate` thing from reach router to create links on the same page, like so:
```jsx
<JobButton
  tabindex="0"
  onClick={() => {navigate('#office-manager')}}
>
  Office Manager
</JobButton>
```

and the links on the same page are working fine. Then I tried to add a `:focus` style in the `styled-component`, like so:

```js
const JobButton = styled.button`
  background: #aaa;
  border: 1px solid grey;
  border: none;
  padding: 0.5rem;
  margin: 0;

  :active {
    background: #333;
  }

  :focus {
    background: #333;
    color: white;
  }
`
```

...and it's working fine in Chrome, but not in Safari or Firefox. I even added a `tabindex`, but that does not seem to have made it work either.

Does anybody have any idea as to why it might not working? Gatsby issue? React Router issue? Obviously a Safari and Firefox issue, but don't know what to do...

Thanks!

XD

**Comment by bvlktech** [comment]
Does the :active sudo-code work?

**Comment by rchrdnsh** [comment]
whoops, sorry, yes, the `:active` pseudo code works, just not `:focus`.

**Comment by bvlktech** [comment]
hmm this is strange because everything looks fine in the code u sent up there ^^ do you get anything in inspect element via safari or firefox under the css section is there like a yellow exclamation point next to the :focus selector? if you hover over it it might say why its not working

**Comment by rchrdnsh** [comment]
if I activate focus in the safari inspector, it seems to work fine, and I'm not noticing any warnings specific to focus. The warning in the console is for react:

<img width="594" alt="Screen Shot 2019-10-18 at 2 15 38 PM" src="https://user-images.githubusercontent.com/7884263/67128864-cd74cc80-f1b1-11e9-90a8-bfc5bb2163ca.png">

but I just saw this when I clicked the button in question:

<img width="594" alt="Screen Shot 2019-10-18 at 2 15 12 PM" src="https://user-images.githubusercontent.com/7884263/67128875-da91bb80-f1b1-11e9-888d-960dbbac4650.png">

So I'm thinking whatever this means has something to do with it?

This is also what I'm seeing when I select the focus state in the element/css inspector:

<img width="1440" alt="Screen Shot 2019-10-18 at 2 13 14 PM" src="https://user-images.githubusercontent.com/7884263/67128916-f4cb9980-f1b1-11e9-8ced-c3cd7cadd9f8.png">

**Comment by bvlktech** [comment]
yea that triangle with the exclamation point in it if you hover over it or you click it it should (at least ik in firefox i dont have / own safari so idk if same) tell you why the selector isnt working but ur code up above ^^ is fine tho

**Comment by rchrdnsh** [comment]
yeah, it looks like all the yellow css warnings are either a duplicate or unsupported property, but nothing that relates in any way to the `:focus` state, as far as i can tell.

**Comment by bvlktech** [comment]
yea this is a issue that shouldent be happning because again all seems fine via ur styled-components umm have u tried this via SASS or SCSS?

**Comment by rchrdnsh** [comment]
no, i have not, but i also don't have those setup, or even know how to, really. I kind of jumped from plain old css to styled-components ¯\_(ツ)_/¯

**Comment by bvlktech** [comment]
ahh SCSS is just like reg css except you can nest stuff ill show some examples

CSS
```
.div {
  background: #fff;
}
.div p {
  color: #000;
}
```

SCSS
```
.div {
  background: #18502  ;
  p {
    color: #000;
  }
}

see its the same although ull have to add this to ur gatsby-config.js `gatsby-plugin-sass`
and then ull have to add the node-sass plugin via yarn or npm to make it work like so
`yarn add node-sass gatsby-plugin-sass`

and then you can just make a file called main.scss and just import it like a regular css file where ever you need it

**Comment by marcysutton** [comment]
Hi there, are you on a new Mac? Because there are settings at the Operating System and browser level that have to be adjusted to allow focusing on some interactive controls.

Safari Preferences, under "Advanced" (see "Press tab to highlight each item on a page"):
![Safari prefs](https://user-images.githubusercontent.com/1045233/67134387-c73d1b00-f1c6-11e9-8bd5-bf166dcf2770.png)

OSX Preferences for Firefox, under Keyboard > Shortcuts (see "Full Keyboard access" > All controls):
![OSX keyboard prefs](https://user-images.githubusercontent.com/1045233/67134417-f0f64200-f1c6-11e9-9a4a-7690bf03ffa6.png)

I will also add that tabIndex alone is not enough to make something non-interactive into a custom button. I'd recommend using the `<button>` element for the stuff you get for free: focusability, the button role for assistive technologies, and keyboard events. https://marcysutton.github.io/gatsby-a11y-workshop/slides/38

**Comment by bvlktech** [comment]
Thank you @marcysutton as I don't own a Mac I was at a loss

**Comment by rchrdnsh** [comment]
Thank you @marcysutton for your reply,

I did not have the tab thing checked, but alas, it is not helping either :-/ But I figure that `:focus` should also work by default, as it does in Chrome, no?

I am also already using the `<button>` element as far as I can tell, as I am extending the `<button>` element in the styled-component, like so:

```js
const JobButton = styled.button`
  ...styles here...
`
```

...and I am under the impression that this is the same as using `<button>` and adding styles via classes, no? Would that not be the same?

**Comment by marcysutton** [comment]
Oh, I totally overlooked the styled button! Yes, that should render a native button element, which is focusable by default -- no `tabindex` should be needed. From reviewing your code again, perhaps you're missing the ampersand to apply `:focus` as `button:focus`? As written, it's looking for a focusable element inside of the button which is probably not what you intended. Does this change things for you? Not sure why `:active` is working except maybe it's applying to a child element or text node? Focus isn't as generous as clicking on stuff so it will only apply to something focusable.

```
const JobButton = styled.button`
  background: #aaa;
  border: 1px solid grey;
  border: none;
  padding: 0.5rem;
  margin: 0;

  &:active {
    background: #333;
  }

  &:focus {
    background: #333;
    color: white;
  }
`
```

**Comment by rchrdnsh** [comment]
hi @marcysutton XD

So I tried adding the ampersand and nothing changed but I also notice that when i click on one of the buttons I get this error message in the console:

<img width="593" alt="Screen Shot 2019-10-18 at 7 27 55 PM" src="https://user-images.githubusercontent.com/7884263/67136625-91576100-f1dd-11e9-9aa6-cb99d62a498a.png">

dunno what it means, but it happens every time I click one of the buttons with this css. I wonder if there might be a bug in gatsby or something?

**Comment by marcysutton** [comment]
Sounds doubtful to be a bug in Gatsby – do you have a repo somewhere to debug? That would really help to figure out what's going on.

**Comment by bvlktech** [comment]
this should help you in your use case this is the docs for styled-components if you scroll down a bit there is a section on styling a btn

https://www.styled-components.com/docs/basics#styling-any-component

**Comment by rchrdnsh** [comment]
hi @marcysutton, here is the repo:

https://github.com/arrowgtp/alma

...and the page in question is the careers page in the pages folder, and the button in question is on line 76 of the careers page.

Hi, @bvlktech, apologies, but i did not see see a button section, or at least, not anythign that is different from what i am doing already, i think?

**Comment by LekoArts** [comment]
Thank you for opening this!

I'd recommend opening an issue on styled-components' repository and ask for help there as it's unlikely to be a bug in Gatsby.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
