### ISSUE TITLE
Is it possible to disable the automatic page creation in the /page folder ?

### ISSUE THREAD

**Issue by gfsd3v** [gatsbyjs/gatsby#18817]
Is it possible to disable the automatic page creation in the /page folder ?

**Comment by bvlktech** [comment]
is this for a blog? if so you can delete the `gatsby-node.js` file from your projects tree because this is the code that auto makes the pages

```javascript
const path = require('path');
const { createFilePath } = require('gatsby-source-filesystem');
const { fmImagesToRelative } = require('gatsby-remark-relative-images');

exports.createPages = ({ actions, graphql }) => {
  const { createPage } = actions;
  return graphql(`{
    allMarkdownRemark(limit: 1000) {
      edges {
        node {
          id
          fields {
            slug
          }
          frontmatter {
            templateKey
          }
        }
      }
    }
  }`).then(result => {
    if(result.errors){
      result.errors.forEach(e => console.error(e.toString()));
      return Promise.reject(result.errors);
    }
    const posts = result.data.allMarkdownRemark.edges;
    posts.forEach(edge => {
      const id = edge.node.id;
      createPage({
        path: edge.node.fields.slug,
        component: path.resolve('src/templates/post.js'),
        context: {
          id
        }
      });
    });
  });
}
exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions;
  fmImagesToRelative(node);
  if(node.internal.type === `MarkdownRemark`){
    const value = createFilePath({ node, getNode });
    createNodeField({
      name: 'slug',
      value,
      node
    });
  }
}
```

**Comment by gfsd3v** [comment]
> is this for a blog? if so you can delete the `gatsby-node.js` file from your projects tree because this is the code that auto makes the pages
> 
> ```js
> const path = require('path');
> const { createFilePath } = require('gatsby-source-filesystem');
> const { fmImagesToRelative } = require('gatsby-remark-relative-images');
> 
> exports.createPages = ({ actions, graphql }) => {
>   const { createPage } = actions;
>   return graphql(`{
>     allMarkdownRemark(limit: 1000) {
>       edges {
>         node {
>           id
>           fields {
>             slug
>           }
>           frontmatter {
>             templateKey
>           }
>         }
>       }
>     }
>   }`).then(result => {
>     if(result.errors){
>       result.errors.forEach(e => console.error(e.toString()));
>       return Promise.reject(result.errors);
>     }
>     const posts = result.data.allMarkdownRemark.edges;
>     posts.forEach(edge => {
>       const id = edge.node.id;
>       createPage({
>         path: edge.node.fields.slug,
>         component: path.resolve('src/templates/post.js'),
>         context: {
>           id
>         }
>       });
>     });
>   });
> }
> exports.onCreateNode = ({ node, actions, getNode }) => {
>   const { createNodeField } = actions;
>   fmImagesToRelative(node);
>   if(node.internal.type === `MarkdownRemark`){
>     const value = createFilePath({ node, getNode });
>     createNodeField({
>       name: 'slug',
>       value,
>       node
>     });
>   }
> }
> ```

I'm using gatsby-node to create my pages with relative paths, is there any other way ?
