### ISSUE TITLE
Issues with gatsby-source-wordpress

### ISSUE THREAD

**Issue by jakewhite1230** [gatsbyjs/gatsby#18812]
## Description

I am trying to start my first Gatsby + WordPress site. When following along with [this](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/) tutorial, I receive errors and can't move forward.

### Steps to reproduce

To reproduce, just follow the steps in the guide. Once I run `gatsby develop`, I get the following errors:
```
The above error occurred in the <ReduxStoreProvider> component:
    in ReduxStoreProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.


 ERROR 

Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.


 ERROR 

UNHANDLED REJECTION Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

Error: Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
  1. You might have mismatching versions of React and the renderer (such as React DOM)
  2. You might be breaking the Rules of Hooks
  3. You might have more than one copy of React in the same app
  See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

```
My versions are
Gatsby: 2.8.3
gatsby-cli: 2.16.1
Node: 10.16.3
OS: MacOS 10.15

**Comment by CRNRSTD** [comment]
Same here. It looks like we found ourselves in the wrong place at the wrong time

**Comment by jakewhite1230** [comment]
> Same here. It looks like we found ourselves in the wrong place at the wrong time.
> 
> EDIT: There you go! purge node_modules & package-lock.json to fix the issue

Thanks for the suggestion. I tried to purge, but that didnt work for me. I tried installing with yarn, and that seemed to do the trick. I've seen several notes on here that npm doesn't seem to always work.
