### ISSUE TITLE
Add to telemetry how big page json & page bundle sizes

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#18819]
probably just send descriptive statistics summary e.g. mean, median, max, min, std dev, & some measure of skew.

We want to warn against sending too much code/data on pages & it'd be good to keep track of how people are doing at the moment.

**Comment by sidharthachatterjee** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/20146
