### ISSUE TITLE
react-intl with wordpress cms

### ISSUE THREAD

**Issue by lpluispacheco** [gatsbyjs/gatsby#18823]
Hello,

I'm looking for the best way to implement internationalisation on the pages that I've creating using Gatsby (the best experience ever btw) and I found react-intl with the plugin "gatsby-plugin-intl", but I need to have the JSON files on one specific folder, the problem is that using the WordPress CMS I get the data with a REST API and I request this data using GraphQL, and not using specific files as react-intl needs.

The "first solution" that I thought  so far is creating the files in the build of Gatsby, but is this the best option to get it work?

Thanks everybody!

**Comment by LekoArts** [comment]
Thank you for opening this!

You could request your data and then write it to local files on the [`onPostBootstrap`](https://www.gatsbyjs.org/docs/node-apis/#onPostBootstrap) or add the data into a provider that wraps your project.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
