### ISSUE TITLE
Gatsby webpack doesn't resolve dependencies from "node_modules" folder

### ISSUE THREAD

**Issue by ryancat** [gatsbyjs/gatsby#18827]
## Description

When using gatsby in a monorepo and as a package, depends on the setup, the dependencies may end up hoisted at root level in that repo. In this case, if I run `gatsby develop`, I have issue with some packages (in my case packages under `lodash/fp/`) cannot be found by webpack during build step. 

Note that this only happens when I already have the same package installed at the root level. In my case, I already have a `lodash` package version 2 installed at root level, which doesn't have `lodash/fp` folder. When npm installs gatsby, it will install the lodash version 4 which gatsby depends on at the second level `node_modules` folder in gatsby. However, gatsby's default webpack doesn't resolve to that folder.

### Steps to reproduce

You can use a normal setup of lerna monorepo, and use gatsby as a package. Make sure the root level depends on lodash version 2. When running `npm install` from the root, the dependencies will be hoisted to the root level. After that just run `gatsby develop` (if you are using `lerna link convert`, you may need to manually resolve the executable for gatsby) and you will see some lodash packages not found.

### Expected result

The package should be resolved correctly.

### Actual result

The package doesn't get resolved correctly.

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Safari: 13.0.1
  npmGlobalPackages:
    gatsby: 2.16.3

**Comment by ryancat** [comment]
I found if I do this 
```
exports.onCreateWebpackConfig = ({actions}) => {
  actions.setWebpackConfig({
    resolve: {
      // It's important to have 'node_modules' in resolve module,
      // otherwise the webpack resolve won't be able to find dependencies
      // correctly.
      modules: ['node_modules']
    }
  })
}
```

The packages will be resolved correctly. I think gatsby by default shouldn't remove `node_modules` from the `resolve.modules` array. It only resolves from current package and root level folder, but not any other folders like second level node_modules folder under root.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look. Your reproduction steps are a bit vague and could maybe result in us using different versions or a slightly different setup. Maybe your general setup is wrong.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by wardpeet** [comment]
If lodash is a dependency of your gatsby site everything should work fine if you have configured your monorepo correctly using `yarn workspaces` or `lerna`

**Comment by StanleySathler** [comment]
Thank you, @ryancat!

I had a similar issue: my Lerna project had two packages: `/shared` and `/site`.

The `/shared` package had `styled-components` as a peer dependency, so `/site` - which is a Gatsby project - should have `styled-components` as one of its dependencies.

The `/shared` package tends to be a set of UI components. They're reused by `/site` and some other packages.

When the `/site` builds (using `$ gatsby develop`), it finds `/shared` trying to import `styled-components` and looks for this package inside of `/shared/node_modules`. However, as styled-components is a peer dependency, it must be imported from `/site/node_modules`.

Is this approach somehow wrong @wardpeet?

**Comment by slash-helmstack** [comment]
@StanleySathler did you find a solution to this? I am facing the exact same issue.

**Comment by StanleySathler** [comment]
Hey @slash-helmstack,
It was a side-project built for fun. I dropped it a long time ago. Don't remember if I came up with a solution, unfortunately. 😕
