### ISSUE TITLE
How to override gatsby-node.js @narative plugin on root

### ISSUE THREAD

**Issue by studentofcoding** [gatsbyjs/gatsby#18835]
# Summary

I use [@novela-gatsby-starter](https://www.gatsbyjs.org/starters/narative/gatsby-starter-novela/) for a project, and recently they requested to make a category sort function, so any article can be seperated by Blog and Event.
How to override gatsby-node.js file on plugin, so i can import the shadow (custom) of 
- createPages, 
- onCreateNode, 
- sourceNode

In the mean time, all the custom shadow work perfectly, but i have to edit the gatsby-node.js directly from the node_modules/@narative/...

### Environment (if relevant)

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.13.41 => 2.15.29
    gatsby-plugin-manifest: ^2.2.18 => 2.2.20
    gatsby-source-contentful: ^2.1.42 => 2.1.45

### File contents (if changed)

`gatsby-config.js`: 
```
require('dotenv').config();

module.exports = {
  siteMetadata: {
    title: `DeepTech`,
    name: `DeepTech Foundation`,
    siteUrl: `https://deeptech.id`,
    description: `Knowledge sharing, meaningful networking, self-improvement & transformation.`,
    hero: {
      heading: `Berbagai blog teknologi kami`,
      maxWidth: 788,
    },
    hero_blog: {
      heading: `Berbagai blog teknologi kami`,
      maxWidth: 788,
      // category for later use
      category: `Blog`, 
    },
    hero_kegiatan: {
      heading: `Berbagai kegiatan kami`,
      maxWidth: 788,
      // category for later use
      category: `Kegiatan`, 
    },
    social: [
      {
         name: `twitter`,
         url: `https://twitter.com/narative`,
      }
    ],
  },
  plugins: [
    {
      resolve: "@narative/gatsby-theme-novela",
      options: {
        contentPosts: "content/posts",
        contentAuthors: "content/authors",
        basePath: "/",
        authorsPage: true,
        sources: {
          contentful: true,
        },
      },
    },
    {
      resolve: 'gatsby-source-contentful',
      options: {
        spaceId: process.env.CONTENTFUL_SPACE_ID,
        accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
        environment: process.env.CONTENTFUL_ENV,
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Novela by Narative`,
        short_name: `Novela`,
        start_url: `/`,
        background_color: `#fff`,
        theme_color: `#fff`,
        display: `standalone`,
        icon: `src/assets/favicon.png`,
      },
    },
  ],
};

```
`package.json`: 
```
{
  "private": false,
  "name": "...",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "dev": "gatsby develop",
    "clean": "gatsby clean"
  },
  "dependencies": {
    "@narative/gatsby-theme-novela": "^0.*",
    "dotenv": "^8.1.0",
    "gatsby": "^2.13.41",
    "gatsby-plugin-manifest": "^2.2.18",
    "gatsby-source-contentful": "^2.1.42",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  }
}
```
`gatsby-node.js`: 
I edit the path so i can use the custom `createPage, onCreateNode, and sourceNodes`
```
exports.createPages = require('./src/@narative/gatsby-theme-novela/gatsby/node/createPages');
exports.onCreateNode = require('./src/@narative/gatsby-theme-novela/gatsby/node/onCreateNode');
exports.sourceNodes = require('./src/@narative/gatsby-theme-novela/gatsby/node/sourceNodes');
```
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by tmvst** [comment]
@studentofcoding were you able to solve this? I'm in a similar situation – I want to add a custom page separate from the articles list, and I want to load two most recent articles from contentful into it. I wasn't able to achieve this from the /pages directory. So my idea is to add it as a template to gatsby-node.js same as how other templates are there currently.

**Comment by juanpprieto** [comment]
I'm also interested to know if this is possible at all. I haven't been able to shadow a plugin's gatsby-[node-ssr-browser] files either. All other files seem to shadow just fine.
