### ISSUE TITLE
Calling `touchNode` on page node throws 'TypeError: locationAndPageResources.pageResources is undefined'

### ISSUE THREAD

**Issue by NathHorrigan** [gatsbyjs/gatsby#18833]
## Description

Calling touchNode on a page causes the following error when you go to the hopefully cached page: `TypeError: locationAndPageResources.pageResources is undefined`.

### Steps to reproduce
Plugin Repo: https://github.com/NathHorrigan/gatsby-source-wagtail

[touchNode call:](https://github.com/NathHorrigan/gatsby-source-wagtail/blob/feature/cache/src/gatsby-node.js#L47)
```
// Code here checks if the page node in Gatsby cache is the same version 
// as backend version. If so 'touch it' and don't  recreate.
await Promise.all(result.data.pages.map(async page => {
    const pageCacheKey = `cache-${page.url}`
    const cacheResult = await pageRecords.getKey(pageCacheKey)
    if (cacheResult) {
        const node = pageNodes.find(node => {
            if (!node.context)
                return
            return node.context.url == page.url
        })
        
        if (node) {
            if (node.context.lastPublishedAt == page.lastPublishedAt) {
              pageRecords.setKey(pageCacheKey, localPublishedAt)
              return touchNode({
                nodeId: node.id
              })
            }
        }
    }
  }))
```

### Expected result

Page Node should persist without having to recreate it (and without requerying backend).

### Actual result

<img width="1182" alt="Screenshot 2019-10-19 at 09 39 37" src="https://user-images.githubusercontent.com/13197111/67140636-6a884180-f254-11e9-928b-509b8e09e833.png">

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.16.5 => 2.16.5 
    gatsby-image: ^2.2.29 => 2.2.29 
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23 
    gatsby-plugin-offline: ^3.0.16 => 3.0.16 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13 
    gatsby-plugin-sharp: ^2.2.32 => 2.2.32 
    gatsby-source-filesystem: ^2.1.33 => 2.1.33 
    gatsby-source-wagtail: git+https://github.com/NathHorrigan/gatsby-source-wagtail.git#feature/cache => 0.1.5 
    gatsby-transformer-sharp: ^2.2.23 => 2.2.23 
  npmGlobalPackages:
    gatsby-cli: 2.7.3
    gatsby-source-wagtail: 0.1.5
    gatsby: 2.15.28

**Comment by LekoArts** [comment]
Hi, thanks for the issue. Could you please describe in long detail what you're trying to achieve?

**Comment by NathHorrigan** [comment]
Hi @LekoArts,

I'm trying to avoid building pages that were already built during the last `gatsby build` and haven't been changed since.

Hence why I'm currently:
- Get all pages from backend, and when they were last changed.
- Iterating through pages matching local versions with remote records.
- TouchNode if timestamp matches.
- Create page if page has changed or is new.

Does this make sense? And if so is it possible?

Cheers!

**Comment by NathHorrigan** [comment]
Hi @LekoArts, Are you able to help with this? We are desperately trying to implement a caching mechanism for our gatsby sites.

**Comment by pieh** [comment]
You are referring to incremental builds and this is not something that you can implement in user code really. There's reason it's not yet implemented in gatsby core - it's difficult problem.

Touching `SitePage` nodes doesn't mean that page will be preserved. `SitePage` is result of creating pages with gatsby APIs, but it is not source of truth for gatsby. Gatsby maintains internal `pages` map which is used to do lot of things (determine if query need to run, determine which page templates need to be included in webpack bundles etc)
