### ISSUE TITLE
Can I access GraphQL Fragment files from a source-plugin?

### ISSUE THREAD

**Issue by NathHorrigan** [gatsbyjs/gatsby#18831]
## Summary
I want to access the all fragments defined in a project so that I can make a query on the frontend? Doesn't matter which Node API method aslong as I can access them? 

### Environment (if relevant)
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.16.5 => 2.16.5
    gatsby-image: ^2.2.29 => 2.2.29
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23
    gatsby-plugin-offline: ^3.0.16 => 3.0.16
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13
    gatsby-plugin-sharp: ^2.2.32 => 2.2.32
    gatsby-source-filesystem: ^2.1.33 => 2.1.33
    gatsby-source-wagtail: git+https://github.com/NathHorrigan/gatsby-source-wagtail.git#feature/cache => 0.1.5
    gatsby-transformer-sharp: ^2.2.23 => 2.2.23
  npmGlobalPackages:
    gatsby-cli: 2.7.3
    gatsby-source-wagtail: 0.1.5
    gatsby: 2.15.28

**Comment by NathHorrigan** [comment]
not stale

**Comment by wardpeet** [comment]
This is only possible if the source-plugin exports the fragments. You can't ask gatsby/graphql which fragments exists.

Could you explain the use case a bit more?

**Comment by NathHorrigan** [comment]
Thanks for the response @wardpeet ,

I have written a source-plugin for the Wagtail CMS that supports previewing posts before publishing them (Basically you use a router that maps django model types to Gatsby templates and the router adds a preview HOC that runs when accessing a `/preview` endpoint with a token).

At the moment the user has to specify to the router if there are any fragments that have been extracted away to separate files so that the fragments can be imported during the preview GraphQL query (run during runtime). Ideally I'd like the user not have to deal with this and be able to scan a Gatsby project and find where there are fragment files that I can import.

Hope that makes sense!

**Comment by wardpeet** [comment]
Could you elaborate a bit on how this would look like? How would you like to see this feature planned out?

**Comment by NathHorrigan** [comment]
Hi @wardpeet,

The most ideal way for this would be to access the fragments as a paramter to the gatsby-node API's. Personally it doesn't matter whether it's an array of strings or AST definitions as long as they can be parsed by a GraphQL client.

An example:
```
exports.createPages = ({ graphql, actions, fragments }) => {
  return createWagtailPages({
      "stories.Story": "templates/story.js",
  }, graphql, actions, fragments)
}
```

If we went with the approach of having the fragments accessible via an array of strings then you could be able to query the internal GraphQL data structure and get them that way:

```
{
  site {
    internal {
      fragments {
        source # String content of fragment.
        file       # Location of where fragment is defined.
      }
    }
  }
}

```

These are just two approaches that quickly come to mind. Both would solve my problem.

**Comment by NathHorrigan** [comment]
@wardpeet Bump

**Comment by NathHorrigan** [comment]
@wardpeet  Bump

**Comment by LekoArts** [comment]
As Ward correctly said this is currently not possible. We have other priorities at the moment so we might come back to this to talk about the finer details later.
