### ISSUE TITLE
Error: Cannot find module './node_modules/detect-libc'

### ISSUE THREAD

**Issue by Henzelix** [gatsbyjs/gatsby#18844]
Hi guys,

When I type `gatsby develop` in the terminal, I get this error:

`Error: Cannot find module './node_modules/detect-libc'`

And:

`error Error in "C:\Users\mikol\piec\node_modules\gatsby-plugin-manifest\gatsby-node.js":`

Does any one knows what to do?

**Comment by LekoArts** [comment]
Thank you for opening this!

Please follow our issue template and include every information requested. I'd recommend updating all your packages, remove `node_modules` and re-install the packages.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
