### ISSUE TITLE
Support for the experimental syntax 'decorators-legacy' isn't currently enabled

### ISSUE THREAD

**Issue by fandy** [gatsbyjs/gatsby#18847]
Are decorators not supported? I'm using `gatsby-plugin-typescript` and have enabled decorators in my `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "es2017"],
    "baseUrl": ".",
    "moduleResolution": "node",
    "allowJs": true,
    "noEmit": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "strict": false,
    "paths": {
      "@/*": ["src/@/*"],
      "~/*": ["src/*"]
    }
  }
}

```

So I tried adding a `.babelrc`, with this config:

```
{
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./"],
        "alias": {
          "@": "./@",
          "pages": "./pages",
          "lib": "./lib"
        }
      }
    ],
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
  ]
}

```

And here's the error I got:

 ERROR #98123  WEBPACK

Generating SSR bundle failed

/Users/fang/app/.cache/develop-static-entry.js: Unexpected token (31:4)

  29 | export default (pagePath, callback) => {
  30 |   let headComponents = [
> 31 |     <meta key="environment" name="note" content="environment=development" />,
     |     ^
  32 |   ]
  33 |   let htmlAttributes = {}
  34 |   let bodyAttributes = {}

File: .cache/develop-static-entry.js:31:4

⠹ start webpack server
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by LekoArts** [comment]
Thank you for opening this!

I'd recommend opening an issue on Babel's repository as the plugin only uses a Babel preset: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-typescript#caveats

They should be able to answer that question :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by dandv** [comment]
@fandy: have you managed to figure this out?

I'm running into the same issue, and I don't think it's a Babel preset problem, because I use a similar setup with Jest, and didn't have to file an issue against Babel:

```js
module.exports = {
  // Enable Jest to parse .test.ts files through Babel
  presets: [
    '@babel/preset-typescript',
  ],
  plugins: [
    '@babel/plugin-transform-modules-commonjs',
    // For Jest - Babel equivalents for experimentalDecorators and emitDecoratorMetadata
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    'babel-plugin-transform-typescript-metadata',
  ],
};
```

How can one instruct `gatsby-plugin-typescript` to also use those two Babel plugins?
