### ISSUE TITLE
Zero-config plugins, based upon the Next.js RFC

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#18850]
## Summary

As [an RFC](https://github.com/zeit/next.js/issues/9133) about zero-config plugins has been submitted to Next.js, I thought a similar approach could be leveraged by Gatsby v3.

### Motivation

Currently, some plugins should be loaded before or after specific packages (e.g. [`gatsby-plugin-offline`](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/) should be listed after `gatsby-plugin manifest` in `gatsby-config.js`).

Zero-config plugins could define their own specificity relative to other known plugins, avoiding issues caused by a wrong loading order. For instance, `gatsby-plugin-offline` could define the following amongst its metadata:

```
{
  loadAfter: [‘gatsby-plugin-manifest’],
  // ...
}
```

This new approach would improve the experience for beginners and seasoned developers alike, lowering the burden caused by configuration management.

**Comment by KyleAMathews** [comment]
This is a cool idea. Thanks for bringing it to our attention!
