### ISSUE TITLE
GraphQL plugin config: document what exactly the `typeName` is

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#18877]
## Summary

New Gatsby user, but experienced with GraphQL. I've cloned [gastby-with-apollo](https://github.com/jlengstorf/gatsby-with-apollo) and I'm trying to use the the [gatsby-source-graphql plugin](https://www.gatsbyjs.org/packages/gatsby-source-graphql/) to fetch a basic list of names. I can't figure out what to pass in the `typeName` field of the plugin configuration.

## Relevant information

In the documentation, the comment above that field is

     // This type will contain remote schema Query type

Overlooking the terse grammar, I don't understand what that comment means, and why that information is necessary, when I'm already specifying the (root) [fieldName](https://github.com/jlengstorf/gatsby-with-apollo/blob/ddb72e839c7da7718165803f84dc4a32206d4ac9/gatsby-config.js#L10), and [the full GatsbyQuery](https://github.com/jlengstorf/gatsby-with-apollo/blob/ddb72e839c7da7718165803f84dc4a32206d4ac9/src/pages/index.js#L7-L16).

### File contents (if changed)

`gatsby-config.js`:
```
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-source-graphql',
      options: {
        typeName: 'Filter',
        fieldName: 'publicFilters',
        url: 'https://graphql.cryptoclimate.io',
      },
    },
  ],
};
```

# Relevant information
* [GraphQL Playground](https://graphql.cryptoclimate.io/graphql)
* GatsbyQuery I'm running: ` { publicFilters { id name } }` (executes fine in the Playground)
* Error: `Unknown field 'id' on type 'Filter!'.`
* Schema includes:
  * `type Filter {  id: String!, name: String!, ... }`,
  * `type Query { publicFilters(userIds: [String!]): [Filter!]! }`

I've tried all sorts of permutations and capitalization of "Filter" and "PUBLICFILTERS" for the `typeName`, but all result in the same error. I can't relate the "RMAPI" from `gastby-with-apollo`, or the SWAPI from other samples to anything in their GraphQL schemas. I'm sure those aren't arbitrary strings, so what am I missing?

**Comment by tbrannam** [comment]
`gatsby-source-graphql` stitches other GraphQL schemas into the Gatsby GraphQL schema.  

When attaching an external schema - you are grouping all those queries under that fieldname.

try renaming Type to CClimate and fieldname to cclimate.

```
query {
  cclimate {
     publicFilters(userIds: ....) {
        id
     }
  }
}
```

**Comment by universse** [comment]
Can you try this?

```js
query MyQuery {
  graphQlSource(typeName: {eq: "Filter"}) {
    fieldName
    id
    typeName
  }

  allGraphQlSource {
    nodes {
      id
      typeName
      fieldName
    }
  }
}

```

**Comment by dandv** [comment]
@tbrannam: thanks for the suggestion, it works. Why the particular capitalization for typeName, `CClimate`, though? I replaced it with `BOGUS`, and the query worked just as well. So,

1. `typeName` can be, literally, anything
2. the `fieldName` is the arbitrary name for the field under which the remote GraphQL source will appear in Gastby's GraphQL schema. You'll use it in the `GatsbyQuery`. Working example: 

## gatsby-config.js
```js
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-source-graphql',
      options: {
        typeName: 'BOGUS',
        fieldName: 'myRemoteGqlSource',
        url: 'https://graphql.cryptoclimate.io',
      },
    },
  ],
};
```

## src/pages/index.js
```js
import React from 'react';
import { graphql } from 'gatsby';

// This query is executed at build time by Gatsby.
export const GatsbyQuery = graphql`
  query {
    myRemoteGqlSource {
      publicFilters {
        id
        name
      }
    }
  }
`;

export default ({ data }) => {
  return (
    <div>{JSON.stringify(data)}</div>
  )
}
```

If the explanation above for `fieldName` is clearer, I'm happy to submit a doc PR. It seems that `typeName` is unnecessary though, so my understanding is perhaps still incomplete.

Here's a [minimalistic working repo with the `BOGUS` typeName](https://github.com/dandv/gatsby-source-graphql-typeName).

@universse: that resulted in all queries nested under `publicFilters`, but publicFilters is a query itself:

![image](https://user-images.githubusercontent.com/33569/67259513-db4d7a80-f45b-11e9-920c-06bcdf1493ab.png)

With the working repo, GraphiQL looks sane:

![image](https://user-images.githubusercontent.com/33569/67260190-9cb9bf00-f45f-11e9-81d0-b18ef1551188.png)

**Comment by tbrannam** [comment]
You are correct - both names are fairly arbitrary.  The typeName is used, if you peek at the Docs generated in GraphiQL you will see that `myRemoteGqlSource: BOGUS` is defined.  In this case BOGUS represents the type of all the resolvers of your GraphQL service.

**Comment by dandv** [comment]
Thanks for the clarifications! I've submitted #18937 to improve the plugin's doc.
