### ISSUE TITLE
Schema customization: `@childOf` directive doesn't cover an edge case with convenience argument for the root field

### ISSUE THREAD

**Issue by vladar** [gatsbyjs/gatsby#18872]
## Description

Schema customization API and a new `@childOf` directive won't add a convenience argument for the root field (only happens when there are no nodes of the type). It does add a convenience _field_ but not an _argument_.

Follow up after #18871
Related to #15305

### Steps to reproduce

- create a site with `gatsby-transform-sharp` plugin (e.g. default starter)
- delete all static images (so that there was no single node of `ImageSharp` after sourcing)
- check graphql schema

### Expected result

```graphql
type Query {
  file:(childImageSharp: ImageSharpFilterInput) File
}

type File {
  childImageSharp: ImageSharp
}
```

What should happen?

### Actual result

```graphql
type Query {
  # Note the searchable argument is missing even though convenience 
  # field `childImageSharp` is added in the `File`
  # This doesn't happen when there is at least one ImageSharp node
  # (in this case argument exists).
  file: File
}

type File {
  childImageSharp: ImageSharp
}
```

### Notes
Looks like the call sequence during schema building causes root field arguments to be added before convenience child fields.
I think it's `addImplicitConvenienceChildrenFields` which causes this as it relies on nodes presence.

**Comment by freiksenet** [comment]
I think this is an ordering problem. In `updateSchemaComposer`:

```js
  await Promise.all(
    Array.from(new Set(schemaComposer.values())).map(typeComposer =>
      processTypeComposer({
        schemaComposer,
        typeComposer,
        fieldExtensions,
        nodeStore,
        parentSpan: activity.span,
      })
    )
  )
  checkQueryableInterfaces({ schemaComposer, parentSpan: activity.span })
  await addConvenienceChildrenFields({
    schemaComposer,
    parentSpan: activity.span,
  })
```

and in `processTypeComposer`

```js
  if (typeComposer instanceof ObjectTypeComposer) {
    await processFieldExtensions({
      schemaComposer,
      typeComposer,
      fieldExtensions,
      parentSpan,
    })
    await determineSearchableFields({
      schemaComposer,
      typeComposer,
      parentSpan,
    })
    if (typeComposer.hasInterface(`Node`)) {
      await addNodeInterfaceFields({ schemaComposer, typeComposer, parentSpan })
      await addImplicitConvenienceChildrenFields({
        schemaComposer,
        typeComposer,
        nodeStore,
        parentSpan,
      })
      await addTypeToRootQuery({ schemaComposer, typeComposer, parentSpan })
    }
  }
```

Implicit children are added in `processTypeComposer`, while `childOf` are added after they are processed. That is a bug, they should both be added at the the time.

CC @stefanprobst
