### ISSUE TITLE
In build, public/app-[hash].js not minimize & uglify

### ISSUE THREAD

**Issue by billel-boudchicha** [gatsbyjs/gatsby#1887]
I've noticed that the generated `app-[hash].js` in public folder has not been minimized and uglify[ed].
Is this by design ?

Gatsby -v: 1.0.7
Node v: 8.3.0 
osx: Sierra 10.12.5

**Comment by claisne** [comment]
duplicate of #1877 ? I've noticed it too.

**Comment by TomiTakussaari** [comment]
I think my IE problems are also caused by that: https://github.com/gatsbyjs/gatsby/issues/1839, as it has'nt gone through Babel either.

**Comment by KyleAMathews** [comment]
Is this still an issue on the latest release?

**Comment by claisne** [comment]
It's now working on my end! Thanks
