### ISSUE TITLE
Cannot read property 'childImageSharp' of undefined

### ISSUE THREAD

**Issue by aaronearl** [gatsbyjs/gatsby#18886]
## Description

I am experiencing a local error, the development cannot read property of 'childImageSharp' of undefined.

### Steps to reproduce

https://github.com/aaronearl/thurz-party

run: gatsby develop

### Expected result

The expected result is to display the image 'LATHURZ' below the event section. however, this is not happening. I am getting the above-mentioned error "cannot read property 'childImageSharp' of undefined.

### Actual result

The actual result is childImageSharp of undefined

What happened. I have examined my query:

```graphql
query Images {
  image: file(relativePath: { eq: "lathurz.jpg" }) {
    childImageSharp {
      fixed(width: 400) {
        ...GatsbyImageSharpFixed
      }
      fluid {
        ...GatsbyImageSharpFluid
      }
    }
  }
}
```

I believe it's correct it performs in the playground correctly.

### Environment

System:
OS: OS X El Capitan 10.11.6
CPU: (4) x64 Intel(R) Core(TM) i7-2677M CPU @ 1.80GHz
Shell: 5.0.8 - /bin/zsh
Binaries:
Node: 11.4.0 - /usr/local/bin/node
Yarn: 1.12.3 - /usr/local/bin/yarn
npm: 6.8.0 - /usr/local/bin/npm
Languages:
Python: 2.7.15 - /usr/local/bin/python
Browsers:
Chrome: 77.0.3865.120
Safari: 9.1.2
npmPackages:
gatsby: ^2.0.64 => 2.15.36
gatsby-image: ^2.0.15 => 2.2.27
gatsby-plugin-manifest: ^2.0.5 => 2.2.21
gatsby-plugin-netlify: ^2.0.6 => 2.1.19
gatsby-plugin-offline: ^2.0.11 => 2.2.10
gatsby-plugin-react-helmet: ^3.0.0 => 3.1.11
gatsby-plugin-sharp: ^2.0.7 => 2.2.29
gatsby-plugin-styled-components: ^3.0.4 => 3.1.9
gatsby-source-filesystem: ^2.0.11 => 2.1.31
gatsby-transformer-json: ^2.1.6 => 2.2.13
gatsby-transformer-sharp: ^2.1.4 => 2.2.21
npmGlobalPackages:
gatsby-cli: 2.7.28

**Comment by aaronearl** [comment]
import React from 'react'
import { graphql } from 'gatsby'
import styled, { css } from 'styled-components'
import { Flex, Box } from 'grid-styled'
import ContactForm from '../components/ContactForm'
import Hero from '../components/Hero'
import Layout from '../components/Layout'
import HeroText from '../components/HeroText'
import Social from '../components/Social'
import { media } from '../utils/style'
import Img from 'gatsby-image'

const StyledHero = styled(Hero)`
  margin-top: -62px;
`

const Section = styled.div`
  text-align: center;
  padding-top: 45px;
  padding-bottom: 40px;
  ${props =>
    props.dark &&
    css`
      background: #292929;
      h2 {
        color: #fff;
      }
      h3 {
        color: #fff;
      }
      div {
        color: #979797;
      }
    `}
`

const SectionTitle = styled.h2`
  font-size: 2em;
  margin: 0.67em 0;
  ${media.xs`
    font-size:1.5em;
  `}
`

const IndexPage = ({ data }) => (
  <Layout>
    <StyledHero fluid={data.hero.edges[0].node.fluid}>
      <HeroText />
      <Social edges={data.allSocialJson.edges} />
    </StyledHero>
    <Section id="event">
      <h1>Event</h1>
      <Flex alignItems="center" flexDirection="column">
        <Box px={2} width={[1, 1 / 2]}>
          <p>
            Party in My Living Room is bringing the house party back in style.
            This is a unique cultural experience bringing live music, alcohol,
            and social engagement all curated by Los Angeles based hiphop artist
            Thurz.
          </p>
          <Img
            fluid={data.file.childImageSharp.fluid}
            alt="Los Angeles Dodgers hat"
          />
        </Box>
      </Flex>
    </Section>    <Section id="rsvp" dark>
      <SectionTitle>RSVP</SectionTitle>
      <Flex alignItems="center" flexDirection="column">
        <Box px={2} width={[1, 1 / 2]}>
          <ContactForm />
        </Box>
      </Flex>
    </Section>
  </Layout>
)

export default IndexPage

export const pageQuery = graphql`
         query indexQuery {
           allSocialJson {
             edges {
               node {
                 url
                 type
               }
             }
           }
           allExperienceJson {
             edges {
               node {
                 id
                 company
                 title
                 start
                 end
               }
             }
           }
           allCertificationsJson {
             edges {
               node {
                 name
                 id
                 start
                 end
                 authority
               }
             }
           }
           allLogos: allImageSharp(
             filter: { original: { src: { regex: "/logo/" } } }
             sort: { fields: original___src }
           ) {
             edges {
               node {
                 id
                 fixed(height: 80, grayscale: true) {
                   ...GatsbyImageSharpFixed_withWebp_tracedSVG
                 }
               }
             }
           }
           hero: allImageSharp(
             filter: { original: { src: { regex: "/hero/" } } }
           ) {
             edges {
               node {
                 id
                 fluid(quality: 100) {
                   ...GatsbyImageSharpFluid_withWebp
                 }
               }
             }
           }
           allEducationJson {
             edges {
               node {
                 id
                 school
                 program
                 start
                 end
               }
             }
           }
         }
         query MyQuery {
           file(relativePath: { eq: "ladodgers-hat.jpg" }) {
             childImageSharp {
               fluid(maxWidth: 400) {
                 ...GatsbyImageSharpFluid
               }
             }
           }
         }
       `

**Comment by dantereve** [comment]
Hi! Your GraphQL query itself is right. But on its own. You have to merge it into your indexQuery.

```graphql
file(relativePath: { eq: "ladodgers-hat.jpg" }) {
      childImageSharp {
        fluid(maxWidth: 400) {
          ...GatsbyImageSharpFluid
        }
      }
    }
```

So now you can use it in gatsby image as you intended to.

```jsx
<Img fluid={data.file.childImageSharp.fluid} alt="alt text" />
```

For better readability, you can even name it as you did with `hero` and `allLogos`.

**Comment by dantereve** [comment]
I'm closing this issue. Feel free to comment if you need any more explanation.
