### ISSUE TITLE
After build the app, i got 404 errors with page-data.json

### ISSUE THREAD

**Issue by aebmknrl** [gatsbyjs/gatsby#18897]
## Description

After build the app with command `gatsby build` i got several 404 errors with page-data.json

![image](https://user-images.githubusercontent.com/5152002/67254949-b81bce80-f44d-11e9-91dd-e7421055b45e.png)

In addition, i have a dynamic routes set in the project (I don't know is this is related to the error, but i have a little suspect about this). Also, if you see something that is wrong i really appreciate your observations.

I just have a `index.js` file in the `pages` folder:
![code](https://user-images.githubusercontent.com/5152002/67255135-90793600-f44e-11e9-835f-d5d659791a8f.png)

And this is my config file `gatsby-node.js`:
![code](https://user-images.githubusercontent.com/5152002/67255191-d9c98580-f44e-11e9-9e2c-8aa0f59bdbd3.png)

### Steps to reproduce

I just do `gatsby build` and serve the folder with a simple http server `live-server`, also tested on WAMP server.

### Expected result

No errors on console should be displayed.

### Actual result

Several 404 errors on the browser console pointing to page-data.json

### Environment

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Yarn: 1.17.3 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/Ali Enrique Briceño/.windows-build-tools/python27/python
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.15.15 => 2.15.15 
    gatsby-plugin-resolve-src: ^2.0.0 => 2.0.0 
    gatsby-plugin-sass: ^2.1.13 => 2.1.14

**Comment by jitendra-koodo** [comment]
I'm also getting 404 for prefetch request /page-data//page-data.json . Not sure where is this double slash coming from, possibly something is missing between these 2 slashes..
