### ISSUE TITLE
Collapse by defaut Closed

### ISSUE THREAD

**Issue by bersot1** [gatsbyjs/gatsby#18909]
## Description

How can i set the Collpase by defaut Closed. Nowadays when I entry in my blog, the collpase come open.

Print:

## Print

![git ask collpase](https://user-images.githubusercontent.com/51892738/67285124-5ee38780-f4ad-11e9-9ec9-192ff0350bc6.png)

### Theme

gitbook-starter

### Environment

  System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.15.28 => 2.15.28
    gatsby-image: ^2.2.24 => 2.2.24
    gatsby-link: ^2.2.17 => 2.2.17
    gatsby-plugin-algolia: ^0.3.4 => 0.3.4
    gatsby-plugin-emotion: ^4.1.9 => 4.1.9
    gatsby-plugin-feed: ^2.3.16 => 2.3.16
    gatsby-plugin-gtag: ^1.0.11 => 1.0.11
    gatsby-plugin-layout: ^1.1.10 => 1.1.10
    gatsby-plugin-mdx: ^1.0.46 => 1.0.46
    gatsby-plugin-react-helmet: ^3.1.11 => 3.1.11
    gatsby-plugin-remove-trailing-slashes: ^2.1.9 => 2.1.9
    gatsby-plugin-sharp: ^2.2.28 => 2.2.28
    gatsby-plugin-sitemap: ^2.2.16 => 2.2.16
    gatsby-plugin-styled-components: ^3.1.8 => 3.1.8
    gatsby-remark-copy-linked-files: ^2.1.23 => 2.1.23
    gatsby-remark-embed-markdown: 0.0.4 => 0.0.4
    gatsby-remark-embed-snippet: ^4.1.11 => 4.1.11
    gatsby-remark-images: ^3.1.25 => 3.1.25
    gatsby-remark-prismjs: ^3.3.18 => 3.3.18
    gatsby-source-filesystem: ^2.1.29 => 2.1.29
    gatsby-transformer-remark: ^2.6.28 => 2.6.28
    gatsby-transformer-sharp: ^2.2.20 => 2.2.20

**Comment by lannonbr** [comment]
Hey @bersot1 so I don't think this is an issue particularly with Gatsby itself but how the specific theme implemented that sidebar. So I would recommend instead opening an issue in that theme.
