### ISSUE TITLE
create validator to check for broken links in www

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#18908]
## Summary

It would be nice to have some link check on the gatsbyjs.org site maybe as validator while an PR or better also on `gatsby develop` to find old broken links

### Caveeats

I know we can not find and check all links because some are generated from sourced data. 

### Motivation

During Hacktoberfest I see also some broken links reported. Example #18905

It would be nice to avoid broken links from beginning. 

### note

I don't mean the broken links reported for viewing files on github

**Comment by lannonbr** [comment]
Maybe putting something like [Hyperlink](https://github.com/Munter/hyperlink) into a GitHub Action could be a good solution to this so it would run similar to how the site showcase validator works right now.

**Comment by muescha** [comment]
I found also https://www.gatsbyjs.org/packages/gatsby-remark-check-links/ but this is only for me files?

**Comment by muescha** [comment]
#19186

**Comment by muescha** [comment]
closing this isssue as duplicate of #19267
