### ISSUE TITLE
Can't deploy or build: Problems with gatsby-source-contentful plugin options: spaceId: undefined - "spaceId" is required accessToken: undefined - "accessToken" is required

### ISSUE THREAD

**Issue by diyarfaraj** [gatsbyjs/gatsby#18904]
## Cant deploy or build

Hi guys, everthing is working fine on localhost, but on when I run build command this error comes up. Please help!
 
ERROR 

Problems with gatsby-source-contentful plugin options:
spaceId: undefined - "spaceId" is required
accessToken: undefined - "accessToken" is required
host (default value): "cdn.contentful.com"
environment (default value): "master"
downloadLocal (default value): false
localeFilter (default value): [Function]
forceFullSync (default value): false

### Steps to reproduce

Just run "npm run build " and the above error comes up.

### Expected result
It should be deployed

### Actual result

In netlify I get this error

10:35:53 AM: Build ready to start
10:35:57 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
10:35:57 AM: build-image tag: v3.3.2
10:35:57 AM: buildbot version: bcf3a8a33ba5ac056b9f7e6a5dd7b48fa2a37b60
10:35:57 AM: Fetching cached dependencies
10:35:57 AM: Starting to download cache of 255.0KB
10:35:57 AM: Finished downloading cache in 76.754895ms
10:35:57 AM: Starting to extract cache
10:35:57 AM: Failed to fetch cache, continuing with build
10:35:57 AM: Starting to prepare the repo for build
10:35:57 AM: No cached dependencies found. Cloning fresh repo
10:35:57 AM: git clone https://github.com/diyarfaraj/gatsby-blog
10:35:58 AM: Preparing Git Reference refs/heads/master
10:35:58 AM: Starting build script
10:35:58 AM: Installing dependencies
10:36:00 AM: Downloading and installing node v10.16.3...
10:36:00 AM: Downloading https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-x64.tar.xz...
10:36:00 AM: 
###############################
10:36:00 AM: ###                                        48.1%
10:36:00 AM: 
########################################################################
10:36:00 AM: 100.0%
10:36:01 AM: Computing checksum with sha256sum
10:36:01 AM: Checksums matched!
10:36:03 AM: Now using node v10.16.3 (npm v6.9.0)
10:36:03 AM: Attempting ruby version 2.6.2, read from environment
10:36:05 AM: Using ruby version 2.6.2
10:36:05 AM: Using PHP version 5.6
10:36:05 AM: Started restoring cached node modules
10:36:05 AM: Finished restoring cached node modules
10:36:05 AM: Installing NPM modules using NPM version 6.9.0
10:36:40 AM: > sharp@0.23.1 install /opt/build/repo/node_modules/sharp
10:36:40 AM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
10:36:40 AM: info
10:36:40 AM: sharp
10:36:40 AM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
10:36:43 AM: > node-sass@4.12.0 install /opt/build/repo/node_modules/node-sass
10:36:43 AM: > node scripts/install.js
10:36:43 AM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-64_binding.node
10:36:44 AM: Download complete
10:36:44 AM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-64/binding.node
10:36:44 AM: Caching binary to /opt/buildhome/.npm/node-sass/4.12.0/linux-x64-64_binding.node
10:36:44 AM: > core-js@2.6.9 postinstall /opt/build/repo/node_modules/core-js
10:36:44 AM: > node scripts/postinstall || echo "ignore"
10:36:44 AM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
10:36:44 AM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
10:36:44 AM: > https://opencollective.com/core-js 
10:36:44 AM: > https://www.patreon.com/zloirock 
10:36:44 AM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
10:36:44 AM: > gatsby-telemetry@1.1.30 postinstall /opt/build/repo/node_modules/gatsby-telemetry
10:36:44 AM: > node src/postinstall.js
10:36:45 AM: > cwebp-bin@5.1.0 postinstall /opt/build/repo/node_modules/cwebp-bin
10:36:45 AM: > node lib/install.js
10:36:45 AM:   ✔ cwebp pre-build test passed successfully
10:36:45 AM: > mozjpeg@6.0.1 postinstall /opt/build/repo/node_modules/mozjpeg
10:36:45 AM: > node lib/install.js
10:36:46 AM:   ✔ mozjpeg pre-build test passed successfully
10:36:46 AM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
10:36:46 AM: > node lib/install.js
10:36:46 AM:   ✔ pngquant pre-build test passed successfully
10:36:46 AM: > gatsby-cli@2.7.58 postinstall /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli
10:36:46 AM: > node scripts/postinstall.js
10:36:46 AM: > gatsby@2.15.36 postinstall /opt/build/repo/node_modules/gatsby
10:36:46 AM: > node scripts/postinstall.js
10:36:46 AM: > node-sass@4.12.0 postinstall /opt/build/repo/node_modules/node-sass
10:36:46 AM: > node scripts/build.js
10:36:46 AM: (node:1319) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
10:36:47 AM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-64/binding.node
10:36:47 AM: Testing binary
10:36:47 AM: Binary is fine
10:36:49 AM: npm WARN
10:36:49 AM: optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
10:36:49 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:36:49 AM: npm WARN
10:36:49 AM:  optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules/chokidar/node_modules/fsevents):
10:36:49 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:36:49 AM: added 2122 packages from 1015 contributors and audited 25304 packages in 43.378s
10:36:49 AM: found 0 vulnerabilities
10:36:49 AM: NPM modules installed
10:36:50 AM: Started restoring cached go cache
10:36:50 AM: Finished restoring cached go cache
10:36:50 AM: unset GOOS;
10:36:50 AM: unset GOARCH;
10:36:50 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
10:36:50 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
10:36:50 AM: go version >&2;
10:36:50 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
10:36:50 AM: go version go1.12 linux/amd64
10:36:50 AM: Installing missing commands
10:36:50 AM: Verify run directory
10:36:50 AM: Executing user command: gatsby build
10:36:52 AM: success open and validate gatsby-configs — 0.059
10:36:53 AM: success load plugins — 0.747
10:36:53 AM: success onPreInit — 0.017
10:36:53 AM: success delete html and css files from previous builds — 0.026
10:36:53 AM: success initialize cache — 0.022
10:36:53 AM: success copy gatsby files — 0.044
10:36:53 AM: success onPreBootstrap — 0.030
10:36:53 AM: Starting to fetch data from Contentful
10:36:53 AM: Fetching default locale
10:36:54 AM: default locale is : en-US
10:36:54 AM: contentTypes fetched 1
10:36:54 AM: Updated entries  2
10:36:54 AM: Deleted entries  0
10:36:54 AM: Updated assets  3
10:36:54 AM: Deleted assets  0
10:36:54 AM: Fetch Contentful data: 244.374ms
10:36:54 AM: success source and transform nodes — 0.506
10:36:54 AM: success Add explicit types — 0.022
10:36:54 AM: success Add inferred types — 0.234
10:36:54 AM: success Processing types — 0.181
10:36:55 AM: success building schema — 0.684
10:36:55 AM: success createPages — 0.042
10:36:55 AM: success createPagesStatefully — 0.085
10:36:55 AM: success onPreExtractQueries — 0.017
10:36:55 AM: success update schema — 0.051
10:36:55 AM: success extract queries from components — 0.357
10:36:55 AM: success write out requires — 0.018
10:36:55 AM: success write out redirect data — 0.015
10:36:55 AM: success onPostBootstrap — 0.014
10:36:55 AM: info bootstrap finished - 5.379 s
10:36:55 AM: success run static queries — 0.050 — 4/4 118.43 queries/second
10:37:11 AM: error #98123 WEBPACK
10:37:11 AM: Generating JavaScript bundles failed
10:37:11 AM: Can't resolve 'React' in '/opt/build/repo/src/components'
10:37:11 AM: File: src/components/head.js
10:37:11 AM: See our docs page for more info on this error: https://gatsby.dev/issue-how-to
10:37:11 AM: Skipping functions preparation step: no functions directory set
10:37:11 AM: Caching artifacts
10:37:11 AM: Started saving node modules
10:37:11 AM: Finished saving node modules
10:37:11 AM: Started saving pip cache
10:37:11 AM: Finished saving pip cache
10:37:11 AM: Started saving emacs cask dependencies
10:37:11 AM: Finished saving emacs cask dependencies
10:37:11 AM: Started saving maven dependencies
10:37:11 AM: Finished saving maven dependencies
10:37:11 AM: Started saving boot dependencies
10:37:11 AM: Finished saving boot dependencies
10:37:11 AM: Started saving go dependencies
10:37:11 AM: Finished saving go dependencies
10:37:21 AM: Error running command: Build script returned non-zero exit code: 1
10:37:21 AM: Failing build: Failed to build site
10:37:21 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
10:37:21 AM: Finished processing build request in 1m24.172314799s

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by ogaston** [comment]
Hi, 

I think the error is caused you didnt define those properties in your `gatsby-config.js`

Please check that file, it must look like: 

```javascript
{
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: "YOUR SPACE ID",
        accessToken:  "YOUR ACCESS TOKEN",
      },
    },
```

**Comment by LekoArts** [comment]
Thank you for opening this!

Like Omar said you most likely didn't provide the necessary options. Make sure to provide them in the correct way.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by jordan314** [comment]
This could be because of #19392

**Comment by vincenttern** [comment]
I'm having the same issue running yarn develop works on local machine but gatsby develop and gatsby build produces this error below. Did anyone figure out how to fix this?

Problems with gatsby-source-contentful plugin options:
spaceId: undefined - "spaceId" is required
accessToken: undefined - "accessToken" is required
host (default value): "cdn.contentful.com"
environment (default value): "master"
downloadLocal (default value): false
localeFilter (default value): [Function]
forceFullSync (default value): false

**Comment by brianjychan** [comment]
If anyone comes across this, take note of `gatsby-config.js`:

```
if (process.env.NODE_ENV !== 'production') {
    dotenv.config()
}
```
