### ISSUE TITLE
support other type of config file

### ISSUE THREAD

**Issue by Austaras** [gatsbyjs/gatsby#18906]
## Summary

I have read [previous issue](https://github.com/gatsbyjs/gatsby/issues/1457) and seen many people interested in writing gatsby config file using TypeScript. IMO it's also possible to write `gatsby-config.js` in json as it's quite simple and straightforward. 

### Motivation

I believe this feature won't involve many work and will benefit many people who value type system and simpilicty.

**Comment by LekoArts** [comment]
Thank you for opening this!

We don't intend to change the format to something else than JavaScript/TypeScript at the moment as `I believe this feature won't involve many work` is certainly not true. Together with our Gatsby Themes JSON is not the best solution for that.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by Austaras** [comment]
> We don't intend to change the format to something else than JavaScript/TypeScript at the moment as `I believe this feature won't involve many work` is certainly not true. Together with our Gatsby Themes JSON is not the best solution for that.

Well for me I only want gatsby to support TypeScript config file natively, and it seems like there are many well-ready solutions for this. I mentioned JSON only because [webpack also support it](https://github.com/webpack/webpack-cli/blob/6964a96c3e44bee8d60696aac8ba2ef9e9c0b829/lib/groups/config.js#L6), which is arguably feasible because user can change to plain js seaminglessly when json is not enough. 

May you reopen this issue @LekoArts?

**Comment by LekoArts** [comment]
You can follow this meta issue regarding TS support: https://github.com/gatsbyjs/gatsby/issues/18983
