### ISSUE TITLE
Page-data not updated on post to __refresh endpoint 

### ISSUE THREAD

**Issue by psantini** [gatsbyjs/gatsby#18911]
## Description

I have a site setup with gatsby and contentful.  When running the preview server locally, if I make a change in a BlogPost (one of our content types in contentful with its own query / createPage call in gatsby), when I reload the page, it does not show the updated content.  However, if I make a change in a MarketingPage (another one of our content types) the change is reflected in the page-data.json and in the browser.  However, that data is updated correctly as visible by the ___graphql endpoint.  Digging into the system to see where the failure is happening, this line: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/query/query-runner.js#L89 ends up returning `undefined` instead of the page.

This only seems to happen with a large number of blog posts, as if I trim down the amount of data in contentful, everything refreshes correctly.

### Steps to reproduce

Starting with a clean system by running `yarn gatsby clean`.
Visit the page in the browser.  Go into contentful and update anything on the blog post, and then post to the __refresh endpoint. 

### Expected result

The page-data should be updated with the newest data.

### Actual result

The system does not update the page data for that post.  However, in a static query that also references that information, the data updates properly.  

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /var/folders/b4/9fxc67bd6vn14sd5g8czvnjw0000gn/T/yarn--1571755737632-0.1316673615401729/node
    Yarn: 1.17.3 - /var/folders/b4/9fxc67bd6vn14sd5g8czvnjw0000gn/T/yarn--1571755737632-0.1316673615401729/yarn
    npm: 6.4.1 - ~/.nodenv/versions/10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 65.0
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.15.29 => 2.15.29 
    gatsby-image: ^2.2.23 => 2.2.23 
    gatsby-link: ^2.2.17 => 2.2.18 
    gatsby-plugin-catch-links: ^2.1.12 => 2.1.12 
    gatsby-plugin-feed: ^2.3.15 => 2.3.15 
    gatsby-plugin-google-tagmanager: ^2.1.12 => 2.1.12 
    gatsby-plugin-manifest: ^2.2.20 => 2.2.20 
    gatsby-plugin-offline: ^3.0.11 => 3.0.11 
    gatsby-plugin-postcss: ^2.1.10 => 2.1.10 
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10 
    gatsby-plugin-react-helmet-canonical-urls: ^1.2.0 => 1.2.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1 
    gatsby-plugin-sharp: ^2.2.27 => 2.2.27 
    gatsby-plugin-sitemap: ^2.2.16 => 2.2.16 
    gatsby-plugin-twitter: ^2.1.9 => 2.1.9 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5 
    gatsby-remark-images-contentful: ^2.1.17 => 2.1.17 
    gatsby-source-contentful: ^2.1.44 => 2.1.44 
    gatsby-transformer-remark: ^2.6.26 => 2.6.26

**Comment by psantini** [comment]
Any ideas or opinions on this from the gatsby team?  It is making it very difficult for our content team to use our system.

**Comment by LekoArts** [comment]
cc @gatsbyjs/core
