### ISSUE TITLE
Gatsby-plugin-manifest does not work, 404 error in console after building site. 

### ISSUE THREAD

**Issue by fullspectrumprocessing** [gatsbyjs/gatsby#18917]
## Description

After deploying my site to netlify I continuously get a 404 error for manifest.json. 
I have installed and configured the gatsby-plugin-manifest just like the docs say however I can not get rid of this 404 error. After reviewing other issues and questions I still haven't found a fix. I deleted modules, lock files, and caches to no avail. I also built the site locally then deployed it to Netlify to see if It still needed to be built prior to Netlify building it, however that still didn't fix anything. Really need to pass the PWA validation and this is holding me back. Does anyone know any solutions. 

### Steps to reproduce

I installed gatsby-plugin-manifest to my application and deployed it from this [Repo](https://github.com/fullspectrumprocessing/FRO-Gatsby-Site-). Once you open up the console in the browser while on the there is this error:

> GET https://federalrecoveryoperations.netlify.com/manifest.json 404 
> Manifest: Line: 1, column: 1, Syntax error.

(I have also included screenshots) 

Here is the live site that STILL throws the error. [Site](https://federalrecoveryoperations.netlify.com)

**I Attached some images below

**

### Expected result
Manifest.json should not throw 404 error. Should be found after building the ste with netlify. 
Site should validate PWA aspects. 

### Actual result
Manifest.json throws 404 error. 
Site does not pass PWA test in DevTools Audit. 

### Environment

System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.18.0 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.3.26 => 2.16.5
    gatsby-image: ^2.0.39 => 2.2.29
    gatsby-plugin-eslint: ^2.0.3 => 2.0.5
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23
    gatsby-plugin-offline: ^2.0.25 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.13
    gatsby-plugin-react-svg: ^2.0.0 => 2.1.2
    gatsby-plugin-sharp: ^2.0.35 => 2.2.32
    gatsby-plugin-sitemap: ^2.0.12 => 2.2.19
    gatsby-plugin-styled-components: ^3.0.7 => 3.1.11
    gatsby-plugin-webpack-size: ^0.0.3 => 0.0.3
    gatsby-source-filesystem: ^2.0.30 => 2.1.33
    gatsby-transformer-json: ^2.1.11 => 2.2.15
    gatsby-transformer-remark: ^2.3.9 => 2.6.30
    gatsby-transformer-sharp: ^2.1.18 => 2.2.23
  npmGlobalPackages:
    gatsby-cli: 2.8.3

![Screen Shot 2019-10-22 at 1 49 42 PM](https://user-images.githubusercontent.com/52926072/67314876-76356b80-f4d3-11e9-9a60-ee73bfd56ad8.png)

![Screen Shot 2019-10-22 at 1 42 38 PM](https://user-images.githubusercontent.com/52926072/67315012-b563bc80-f4d3-11e9-8a39-984b701a3d15.png)

**Comment by patspam** [comment]
I'm seeing this too

**Comment by LekoArts** [comment]
Thank you for opening this!

Seems like you fixed your issue. For future Googlers:

- There was a link to "manifest.json" in React Helmet but the plugin already creates a .webmanifest file
- The `start_url` was wrong

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by joebentaylor1995** [comment]
Not sure why this is closed, still having issues now in Gatsby 5 with manifest@5.8.0
