### ISSUE TITLE
GraphQL Schema rebuilding

### ISSUE THREAD

**Issue by freiksenet** [gatsbyjs/gatsby#18939]
Currently in develop the schema doesn't change when data changes, even thought this can sometimes happen. This proposes adding updating schema when needed.

Lots of the ground work has already been done, things that should react to schema changes do react to them, thus only implementing actual schema updating would be required.

We already rebuild a schema during our bootstrap process due to context inference (however we will disable querying context this way in v3). As a side effect of this PR we can put deprecation warning for this. See [RFC about removing context queryablity](https://github.com/gatsbyjs/rfcs/pull/26)

The basic process should collect node ids and types that change by subscribing to node redux events, then when API_RUNNING_QUEUE_EMPTY is triggered, it should call some kind of schema rebuilding function with those ids/types. Schema rebuilding should compare new nodes example object with an example object that is cached for the previous run (can be maybe metadata stored in type composer) and perform updates to schema in case this happened. It should then recreate the schema.

**Comment by vladar** [comment]
Published in gatsby 2.18.0
