### ISSUE TITLE
Gatsby Navigation doesn't work when its deployed

### ISSUE THREAD

**Issue by nejurgis** [gatsbyjs/gatsby#18944]
## Description
https://warehouse.netlify.com/
I have a Gatsby site thats deployed on netlify, (using netlifyCMS). It works locally and was always working when i would deploy it to netlify, until I implemented react hooks yesterday. Now, when I'm clicking on links in navigation it throws an error:
```
react-dom.production.min.js:4306 TypeError: n is not a function
    at react-dom.production.min.js:4373
    at t.unstable_runWithPriority (scheduler.production.min.js:342)
    at so (react-dom.production.min.js:2559)
    at Da (react-dom.production.min.js:4363)
    at za (react-dom.production.min.js:4557)
    at react-dom.production.min.js:5778
    at t.unstable_runWithPriority (scheduler.production.min.js:342)
    at so (react-dom.production.min.js:2559)
    at Bl (react-dom.production.min.js:5593)
    at Ml (react-dom.production.min.js:4863)
```
I think the component that's causing this is this one:
https://github.com/nejurgis/warehouse/blob/master/src/templates/index-page.js

Describe the issue that you're seeing.
When navigating the site the page crashes with a react-dom error in the console. 
### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).\
1. Go to website
2. Click one of the nav links in the top navbar ( All / Events / Podcast / Shop )
3. Click on another section
4. Broken. Check the console for the error I mentioned above
5. Refresh the page when its broken - it works again

### Expected result

Should Navigate to another page/section without an error

### Actual result

The page is broken / blank

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.1 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.13.31 => 2.13.54 
    gatsby-image: ^2.0.23 => 2.2.8 
    gatsby-plugin-netlify: ^2.0.6 => 2.1.4 
    gatsby-plugin-netlify-cms: ^4.1.6 => 4.1.6 
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.1.3 
    gatsby-plugin-sass: ^2.0.7 => 2.1.4 
    gatsby-plugin-sharp: ^2.2.9 => 2.2.10 
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.1.4 
    gatsby-remark-embed-soundcloud: ^1.0.0 => 1.0.0 
    gatsby-remark-images: ^3.1.6 => 3.1.8 
    gatsby-remark-relative-images: ^0.2.1 => 0.2.3 
    gatsby-source-filesystem: ^2.0.26 => 2.1.9 
    gatsby-transformer-remark: ^2.6.9 => 2.6.11 
    gatsby-transformer-sharp: ^2.1.9 => 2.2.6 
  npmGlobalPackages:
    gatsby-cli: 2.7.29

**Comment by nejurgis** [comment]
EDIT: sorry guys, it was my incorrect usage of state and hooks in a functional component, It seems that I solved it

**Comment by sgal** [comment]
This issue can happen if you return `null` inside `useEffect`. Consider following
```javascript
const isBrowser = typeof window === 'object'

useEffect(() => {
    if (!isBrowser) return null // error here
    ...
    return () => cleanup()
}, [])
```

To fix this, simply return `false` or `undefined` instead of `null`. The closest discussion about this issue is here https://github.com/facebook/react/issues/15369, but it unfortunately lost traction.
