### ISSUE TITLE
Useless app-data.json requests

### ISSUE THREAD

**Issue by linvain** [gatsbyjs/gatsby#18959]
## Description

Since update, `http://localhost:8000/page-data/app-data.json` is requested with every `page-data.json` request (the same file is requested like 20 times). It wasn't requested before.

### Environment

Chromium & Firefox

```
  System:
    OS: Linux 5.3 Manjaro Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz
    Shell: 5.0.11 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.0 - /usr/bin/npm
  Languages:
    Python: 3.7.4 - /usr/bin/python
  Browsers:
    Firefox: 70.0
  npmPackages:
    gatsby: ^2.17.2 => 2.17.2 
    gatsby-image: ^2.2.29 => 2.2.29 
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23 
    gatsby-plugin-offline: ^3.0.16 => 3.0.16 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13 
    gatsby-plugin-sharp: ^2.2.32 => 2.2.32 
    gatsby-source-filesystem: ^2.1.33 => 2.1.33 
    gatsby-transformer-json: ^2.2.15 => 2.2.15 
    gatsby-transformer-sharp: ^2.3.0 => 2.3.0 
```

**Comment by LekoArts** [comment]
Thank you for opening this!

You can read more about the reasoning on the PR that implemented this:
https://github.com/gatsbyjs/gatsby/pull/16686

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
