### ISSUE TITLE
Remove rotation transform of modal prev/next button on small screens

### ISSUE THREAD

**Issue by brockduncan** [gatsbyjs/gatsby#18963]
@fk this is for removing the rotation of previous and next item text on small screens.
#18956 for reference
![image](https://user-images.githubusercontent.com/22098339/67442598-98141880-f5cf-11e9-8eb4-9b098d26e1c7.png)

**Comment by fk** [comment]
👍 🙏

**Comment by fk** [comment]
Stale, but fixed in #18988! ;-)
Thanks again, @brockduncan! 🤗
