### ISSUE TITLE
Link prefetch rules?

### ISSUE THREAD

**Issue by linvain** [gatsbyjs/gatsby#18961]
## Summary

In my project gatsby Link doesn't prefetch links in viewport, only on hover. In both Chromium and Firefox. Why? Can I enable prefetching links in viewport?

### Environment (if relevant)

```
  System:
    OS: Linux 5.3 Manjaro Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz
    Shell: 5.0.11 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.0 - /usr/bin/npm
  Languages:
    Python: 3.7.4 - /usr/bin/python
  Browsers:
    Firefox: 70.0
  npmPackages:
    gatsby: ^2.17.2 => 2.17.2 
    gatsby-image: ^2.2.29 => 2.2.29 
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23 
    gatsby-plugin-offline: ^3.0.16 => 3.0.16 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13 
    gatsby-plugin-sharp: ^2.2.32 => 2.2.32 
    gatsby-source-filesystem: ^2.1.33 => 2.1.33 
    gatsby-transformer-json: ^2.2.15 => 2.2.15 
    gatsby-transformer-sharp: ^2.3.0 => 2.3.0 
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by bjatwork** [comment]
I have the same issue with current version
https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-default/

**Comment by LekoArts** [comment]
Please provide a clear reproduction, I don't see any problems:


![ezgif-1-b488ec8e5c68](https://user-images.githubusercontent.com/16143594/68583126-b5c0f900-047c-11ea-8966-f2d1d0b27d49.gif)

**Comment by bjatwork** [comment]
@LekoArts 
what program do use to make this gif video? 

- In blog starter i also do not see problems. 

- I use gatsby default starter and problems are visable also on 
https://gatsby-starter-default-demo.netlify.com/

- Previously (older gatsby version) i used gatsby default starter and this problem do not occurred.

- I see that prefetching page-data.json working now on mobile, but despite of that still is delay. 

Steps to reproduce: 
1. open https://gatsby-starter-default-demo.netlify.com/ 
2. change to mobile, change parset to 3g slow
3. refresh page
4. go to link 2, wait until page-data.json will download
5. click link2

**Comment by graysonhicks** [comment]
I ran these steps: 
> - open https://gatsby-starter-default-demo.netlify.com/
- change to mobile, change parset to 3g fast
- refresh page
- go to link 2, wait until page-data.json will download
- click link2

I do see that in that scenario the prefetch only happens `onMouseOver`.  However, changing the network speed back up to even 'Fast 3G' does prefetch `page-2` data when it is in viewport.

Not sure if this is an issue with the IntersectionObserver not being set correctly because the page load is too slow?  Does seem like an edge case since you still get the prefetch onMouseOver, but I am curious what is happening.

**Comment by hitchcott** [comment]
I'm experiencing a similar issue; `app-data.json` isn't getting prefetched on mobile, even with a fast simulated network (and over WiFi on a real device). It's making a round trip when navigating links and feels slow.

Here's what it looks like. First on desktop demonstrating `onMouseOver` prefetching, and then on viewport without the same behaviour, and slow navigation.

![Screen Recording 2020-01-25 at 11 51 05 mov](https://user-images.githubusercontent.com/1696942/73116551-b12fbb00-3f6a-11ea-945e-5545c6a9a685.gif)

Example: http://ethereumclassic.org/
Source code: https://github.com/ethereumclassic/ethereumclassic.github.io

**Comment by hitchcott** [comment]
Closing this, I'm assuming this is intended behaviour now.

I must have just had a very slow connection when testing.

**Comment by mantagen** [comment]
related to https://github.com/gatsbyjs/gatsby/discussions/25119
