### ISSUE TITLE
Some brokeness atm

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1897]
From https://github.com/gatsbyjs/gatsby/pull/1880

Two problems I see are:

* hot reloading isn't working
* "gatsby serve" doesn't load on an accessible port

Both seem related to defaults not being set correctly with new CLI stuff which you can see by running `gatsby serve --help` if you install latest `gatsby-cli`.

/cc @jquense

**Comment by KyleAMathews** [comment]
Headed to family thing so can't fix right now.

**Comment by dardub** [comment]
After creating a new project with no changes. Running gatsby build will not terminate after build finishes.

gatsby-cli: 1.1.1
gatsby: 1.9.2

**Comment by KyleAMathews** [comment]
Oh thanks! Pushed & published fix for that as well.

**Comment by KyleAMathews** [comment]
The global CLI also isn't using the locally installed gatsby it looks like.

https://github.com/gatsbyjs/gatsby/issues/1899

**Comment by KyleAMathews** [comment]
Reverted the CLI changes for now https://github.com/gatsbyjs/gatsby/pull/1903
