### ISSUE TITLE
Can't install gatsby on mac

### ISSUE THREAD

**Issue by SokolovAlex** [gatsbyjs/gatsby#18978]
macos mojave 10.14
node 12.13.0

yarn add gatsby
or
npm i gatsby --save

finished with errors

[1/4] 🔍 Resolving packages...
error Couldn't find package "@reach/router@^1.2.1" required by "gatsby" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "@xtuc/ieee754@^1.2.0" required by "@webassemblyjs/ieee754@1.8.5" on the "npm" registry.

I can't do anything with gatsby

**Comment by bvlktech** [comment]
The command to install GatsbyJS is `npm i -g gatsby-cli` this will install GatsbyJS globally in your system then you can just run `gatsby new PROJECT_NAME_HERE` to start a new GatsbyJS project hope this helps!

**Comment by SokolovAlex** [comment]
i try
gatsby new PROJECT_NAME_HERE

1) command starts cloning template but i can't do this behind proxy
2) if i reinstall packages of existing project i catch this error too

**Comment by niklasmtj** [comment]
Hi,
Is it possible for you to install other npm packages? 

You said you are using npm behind a proxy. Did you already told npm what proxy to use?

Could you please check if there is already a proxy set with 
```
npm config get proxy
npm config get https-proxy
``` 
If one or both of them return `null` set them with the following:
```
npm config set proxy http://IP:PORT
npm config set https-proxy http://IP:PORT
```

Then try again to install Gatsby with `npm i -g gatsby-cli`

**Comment by SokolovAlex** [comment]
i set both of them.

now problem only with yarn when i try 

yarn add gatsby

**Comment by sidharthachatterjee** [comment]
You should be able to set the `https-proxy` and `proxy` keys in [yarn config](https://yarnpkg.com/lang/en/docs/cli/config/)

Since this isn't gatsby specific, let's close this issue for now! Thank you so much 🙌

**Comment by SokolovAlex** [comment]
i checked yarn config before too.

other packages install correctly

**Comment by olivertembo** [comment]
Run the install as using sudo like this:
`sudo npm i -g gatsby-cli`

Without admin access, it will fail as it has no writing permission.
