### ISSUE TITLE
Cannot create new Gatsby project

### ISSUE THREAD

**Issue by glynnsmith** [gatsbyjs/gatsby#18984]
## Description

> Describe the issue that you're seeing:

I run `gatsby new test` to create a gatsby project within a new `test` directory, but it fails:

```
gatsby new test     
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git
Cloning into 'test'...
remote: Enumerating objects: 2275, done.
remote: Total 2275 (delta 0), reused 0 (delta 0), pack-reused 2275
Receiving objects: 100% (2275/2275), 11.99 MiB | 3.23 MiB/s, done.
Resolving deltas: 100% (1466/1466), done.
success Created starter directory layout
info Installing packages...
yarn install v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby > eslint-config-react-app@4.0.1" has incorrect peer dependency "eslint-plugin-flowtype@2.x".
warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] 🔨  Building fresh packages...
[-/9] ⠠ waiting...
[-/9] ⠠ waiting...
[-/9] ⠠ waiting...
[-/9] ⠠ waiting...
error /Volumes/Development/test/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Volumes/Development/test/node_modules/sharp
Output:
info sharp Using cached /Users/glynn/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=11.12.0 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.12.0 | darwin | x64
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "/usr/bin/python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/Users/glynn/.nvm/versions/node/v11.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/glynn/.nvm/versions/node/v11.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/Users/glynn/.nvm/versions/node/v11.12.0/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/Users/glynn/.nvm/versions/node/v11.12.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /Users/glynn/.nvm/versions/node/v11.12.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /Users/glynn/.nvm/versions/node/v11.12.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /Users/glynn/.nvm/versions/node/v11.12.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/Users/glynn/.nvm/versions/node/v11.12.0/bin/node" "/Users/glynn/.nvm/versions/node/v11.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/Development/test/node_modules/sharp





 ERROR 

Command failed with exit code 1 (EPERM): yarnpkg



  Error: Command failed with exit code 1 (EPERM): yarnpkg
  
  - error.js:59 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:59:11
  
  - index.js:112 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:112:26
  
  - next_tick.js:81 processTicksAndRejections
    internal/process/next_tick.js:81:5
  


```

### Steps to reproduce

> Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).
> 
> How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

Run `gatsby new test`

### Expected result

> What should happen?

A new Gatsby project should be created

### Actual result

> What happened.

The project creation fails. Please see above for console output.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

>   System:
>     OS: macOS High Sierra 10.13.3
>     CPU: (12) x64 Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
>     Shell: 5.3 - /bin/zsh
>   Binaries:
>     Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
>     Yarn: 1.19.1 - /usr/local/bin/yarn
>     npm: 6.7.0 - ~/.nvm/versions/node/v11.12.0/bin/npm
>   Languages:
>     Python: 3.7.4 - /usr/local/bin/python
>   Browsers:
>     Chrome: 78.0.3904.70
>     Firefox: 67.0.4
>     Safari: 11.0.3
>   npmGlobalPackages:
>     gatsby-cli: 2.8.5

This problem looks like it may be caused by the `Sharp` plugin, but it's above my ability to get any closer to a fix. I've been at this for a few hours now.

This is my first Gatsby attempt, so any help with this would be massively appreciated.

Many thanks 👍

**Comment by bvlktech** [comment]
Oh this is a `node-gyp` Error i got this in that same node version as well what fixed it for me was just by upgrading NodeJS to v12.13.0

**Comment by bvlktech** [comment]
> Oh this is a `node-gyp` Error i got this in that same node version as well what fixed it for me was just by upgrading NodeJS to v12.13.0

Here's a link to NodeJS => https://nodejs.org/en/download/

**Comment by glynnsmith** [comment]
We have a winner! Can't believe it was that trivial!

Thank you for your help here. So very, very much appreciated :)

**Comment by bvlktech** [comment]
was that the trick for you it worked?

**Comment by glynnsmith** [comment]
Yep. Looks like it's all working as it should. It's created the project with no errors, and I'm able to start the local server. Thank you :)

**Comment by bvlktech** [comment]
No problem glad i can help(:
