### ISSUE TITLE
[renovate]: ignore engines.yarn

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#18980]
## Summary

Our current renovate config, result in `engines.yarn` bumps, which is something we don't want. Not only it would unnecessarily force users to be on latest `yarn` version, it also make it problematic to run checks on CI (as images used on CircleCI doesn't seem to come with latest yarn version):

![Screenshot 2019-10-24 at 13 44 01](https://user-images.githubusercontent.com/419821/67484212-e07f1500-f667-11e9-8a0a-78918020f4fc.png)

![Screenshot 2019-10-24 at 14 10 01](https://user-images.githubusercontent.com/419821/67484263-00163d80-f668-11e9-96b7-a863b28090f1.png)

Screenshots from https://github.com/gatsbyjs/gatsby/pull/18875

### Task

Update https://github.com/gatsbyjs/gatsby/blob/master/renovate.json configuration, so it doesn't try to update engines

**Comment by wpanas** [comment]
I can take it :)

**Comment by pieh** [comment]
Nice, go for it @wpanas!

**Comment by wpanas** [comment]
Can you give me a hint how to test if my changes worked?

**Comment by pieh** [comment]
Right now I don't have nice solution, but I think creating test repository that would have `engines.yarn` set in package.json and trying out renovate configuration changes there might be the way to go?

Alternatively if you would find good resource for this, we could just live test changes here directly (as right now we are blocked and can't merge renovate PRs anyway), and we could try force renovate PR refresh

**Comment by wpanas** [comment]
I used https://docs.renovatebot.com/configuration-options/#ignoredeps to fix it. Either it works or not, but I'm certain that it won't not break anything. It uses exact match, so only `yarn` is going to be excluded. Other dependencies are going to stay safe and sound.
