### ISSUE TITLE
Unable to start Gatsby Develop after including in config file

### ISSUE THREAD

**Issue by utaggie08** [gatsbyjs/gatsby#18992]
## Description

Describe the issue that you're seeing.

When I add gatsby-source-filesystem to my gatsby-config file then I am unable to run gatsby-develop in my console after installing gatsby-source-filesystem via npm. Also, I tried installing different versions of gatsby to no avail. 

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

The demo project I used is: gatsby new tutorial-part-four https://github.com/gatsbyjs/gatsby-starter-hello-world

I followed part 5 of this tutorial: https://www.gatsbyjs.org/tutorial/part-five/

I did the following: 
(1) Installed gatsby-source-filesystem
(2) Added the gatsby-source-filesystem to be gatsby-config file
(3) Went back into my console and did gatsby develop command
(4) Hit an error and could not get the site to start.
(5) If I take #2 out of the gatsby-config file then I am able to start the site (via gatsby develop)
 
How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

The site should've started when I did the gatsby develop command. 
### Actual result

What happened.

The console threw an error saying "Can't perform a React state update on an unmounted component."

### Environment

Run `gatsby info --clipboard
<img width="918" alt="gatsby-error" src="https://user-images.githubusercontent.com/8118875/67530570-1d0d3980-f685-11e9-99c5-45c73a95ba2f.png">
` in your project directory and paste the output here.
<img width="918" alt="gatsby-error" src="https://user-images.githubusercontent.com/8118875/67530817-ec79cf80-f685-11e9-86a5-5339d9b80054.png">

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz
  Binaries:
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.16.1 => 2.16.1
    gatsby-plugin-emotion: ^4.1.12 => 4.1.12
    gatsby-plugin-typography: ^2.3.14 => 2.3.14

**Comment by thetanil** [comment]
you don't actually have the "gatsby-source-filesystem" npm module listed in your list of npm packages. have you missed that step, or is it an error in the bug report?

**Comment by sidharthachatterjee** [comment]
@utaggie08 Can you push your repo up as a reproduction so we can see what's going on?

**Comment by utaggie08** [comment]
thanks, guys I was finally able to resolve!
