### ISSUE TITLE
Extract stack-trace-utils.js to gatsby core utils

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#19010]
We currently have duplicate code in `gatsby-cli` and code added in https://github.com/gatsbyjs/gatsby/pull/19009

We should be able to extract that common stack trace sanitisation code into a shared function in `gatsby-core-utils`

**Comment by v-hal** [comment]
I'd like to help with this one.

**Comment by v-hal** [comment]
Pull request here: #19017
