### ISSUE TITLE
refactor: extract custom ci detection code to gatsby core utils

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#19018]
We currently have some custom CI detection code that augments `ci-info` with support for ZEIT's Now and heroku detection in `https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-telemetry/src/ci.js`

This is currently used for telemetry events, but this can be moved to `gatsby-core-utils` package so both `gatsby-telemetry` and `gatsby-cli` ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/util/is-tty.js and https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/reporter/index.js ) could make use of it.

## Task:

Move
 - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-telemetry/src/ci.js
 - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-telemetry/src/__tests__/ci.js

to `gatsby-core-utils`. Make sure that `isCI` and `getCIName` function are exported from that package. And update `gatsby-telemetry` and `gatsby-cli` to use those functions (need to add `gatsby-core-utils` to dependencies)

**Comment by RobinCsl** [comment]
I'd like to help with it :)

**Comment by pieh** [comment]
Awesome! Thanks @RobinCsl!
