### ISSUE TITLE
Move `node-model` documentation to `utils`

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#19027]
## Summary

Move the documentation in `src/schema/node-model` to a stub documentation file in `src/utils` (where `api-node-docs` and `api-browser-docs` are.

### Motivation

This would make it easier to translate this API, since it will be in its own page without any code and can be copied over to the [gatsby-i18n-source repo](https://github.com/gatsbyjs/gatsby-i18n-source).

### Details

All the documentation comments in `src/schema/node-model` should be moved to a file called `api-node-model-docs` with stubs of the content, similar to files `api-node-docs` and `api-browser-docs`.

All graphql queries that reference `node-model` documentation (namely, `www/src/pages/docs/node-model`) should be redirected to use the new file.

**Comment by SunveerSingh** [comment]
Hey @tesseralis I have added the pull request https://github.com/gatsbyjs/gatsby/pull/19033

**Comment by muescha** [comment]
https://github.com/gatsbyjs/gatsby/pull/19033#pullrequestreview-307508703
> Look at the other files — api-node-docs.js and api-browser-files.js. They contain _stubs_: the same function declarations but with everything replaced with the boolean value `true`. In addition, the place where this is referenced, `www/src/pages/docs/node-model.js`, needs the path reference in the GraphQL query changed.

**Comment by muescha** [comment]
i guess it becomes the name `node-model-docs`

**Comment by muescha** [comment]
new name `api-node-model-docs` (see https://github.com/gatsbyjs/gatsby/issues/18704#issuecomment-546507307)

**Comment by SunveerSingh** [comment]
Hello @muescha I am actually new to this community, so I would appreciate if you can get me started on this issue by being a bit more specific.

**Comment by muescha** [comment]
It should be look like the other mentioned files

- copy (not move) the file to `src/utils/` 
- rename it to `api-node-model-docs.js`
- strip out the code for each export to ` = true`

Now you have a barebone code construct with doc text like the other `api-*-docs.js`

I not sure to strip out the comments from the source file too?

**Comment by muescha** [comment]
the goal is to read the JSDocs for the API Guide on webpage. that's why the function body is not needed and replaced just with the stub `= true`

**Comment by tesseralis** [comment]
I'm closing this issue because I'm not sure this is the best approach in the long run after talking with @pieh. See #19382 for the updated issue.
