### ISSUE TITLE
Associate reporter logs with activity

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#19024]
Some logs (ones that are output in plugin code for instance) occur within an activity. We should associate these logs with the activity so that we're able to group (or filter) these in the CLI 

We should be able to do this by setting an activityId on every log. 

The best place to do this is likely in `runAPI` where we can bind `log`, `info`, `warn` functions to the activity instance. 

Follow up to https://github.com/gatsbyjs/gatsby/issues/18383

**Comment by blainekasten** [comment]
@sidharthachatterjee anything you want to add here? should we mark not stale? Or is this sort of not a priority and we could just let this silently go away? 😆
