### ISSUE TITLE
Incorrect and inconsistent reporter type definitions

### ISSUE THREAD

**Issue by ediblecode** [gatsbyjs/gatsby#19025]
## Description

I am writing a source plugin in TypeScript. I have my source code (gatsby-node.ts in this instance) in a _src_ folder and am transpiling to the root. In order to have a strongly typed `sourceNodes` function, I am referencing the `SourceNodesArgs` type from gatsby. This type contains the reporter object, which can be used to report activity whilst the plugin is retrieving data.

Unfortunately the [reporter documentation](https://www.gatsbyjs.org/docs/node-api-helpers/#reporter) is actually missing the docs for the `reporter.activityTimer` function which [can be used by plugins](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-drupal/src/gatsby-node.js#L24) to report activities and statuses. It's this `activityTimer` function that has incorrect type definitions.

The type definitions in gatsby's index.d.ts for `Reporter` are incorrect and different from gatsby-cli's type defs for `Reporter`. I believe (according to [this coment](https://github.com/gatsbyjs/gatsby/issues/18672#issuecomment-543384184)) that gatsby uses the cli's reporter so the type definitions should match up.

These are the 2 issues I've found in [gatsby's index.d.ts](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/index.d.ts):

- the second argument of [`activityTimer`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/index.d.ts#L954) should be [optional](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/reporter/index.js#L219)
- the [returned `ActivityTracker` object](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/index.d.ts#L957)'s status update method should be called [`setStatus`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/reporter/types.js#L6) and not `status`.

### Steps to reproduce

1. Create a TypeScript source plugin with a `sourceNodes` function
2. Import and use the `SourceNodesArgs` type from Gatsby
3. Call `const activity = reporter.activityTimer("A timer");` and then `activity.setStatus("a status")`

```ts
// Plugin's gatsby-node.ts
import { SourceNodesArgs } from "gatsby";

exports.sourceNodes = async (
	{
		reporter
	}: SourceNodesArgs
) => {
	const activity = reporter.activityTimer(`An activity`);
	activity.setStatus(`A status`);
};
```

### Expected result

No TypeScript errors and reporting works as expected

### Actual result

The following TypeScript errors are generated:

- For `activityTimer`: _"Expected 2 arguments, but got 1. An argument for 'activityArgs' was not provided."_
- For `setStatus`: _ "Property 'setStatus' does not exist on type '{ start: () => void; status(status: string): void; end: () => void; span: object; }'"_

### Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.11 - C:\Python27\python.EXE
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.13.41 => 2.13.41
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sass: ^2.1.3 => 2.1.3
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-plugin-typescript: ^2.1.2 => 2.1.2
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4

**Comment by ediblecode** [comment]
Hope that's all enough detail and makes sense. Happy to submit a PR with updated type defs!

**Comment by sidharthachatterjee** [comment]
@ediblecode Thank you so much for the detailed issue! These _indeed_ do look incorrect. Happy to receive a PR!

**Comment by ediblecode** [comment]
I'll get to updating the PR this week

**Comment by vladar** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/19189
