### ISSUE TITLE
`gatsby build` completes without generating all thumbnails.

### ISSUE THREAD

**Issue by tinder-kyleboss** [gatsbyjs/gatsby#19021]
## Description

Hey everyone! 👋

`gatsby build` completes successfully even though it is still generating image thumbnails. When visiting the website that has just been built, a lot of the images end up 404ing. It is almost as if when gatsby finishes the "Building static HTML pages" step, it terminates even though the thumbnails are still being generated. 

Thanks in advanced for the help! I am always in awe of how this community comes together.

```
success run static queries - 0.112 s — 3/3 38.87 queries/second
success Building production JavaScript and CSS bundles - 17.684 s
success Rewriting compilation hashes - 0.034 s
success run page queries - 255.508 s — 829/829 3.25 queries/second
success Building static HTML for pages - 20.398 s — 829/829 150.17 pages/second
info Done building in 745.957071943 sec

info gatsby serve running at: http://localhost:9000/
```

### Steps to reproduce

Run `gatsby build` -- It will probably be more obvious on projects with a lot of images.

### Expected result

`gatsby build` should wait for the thumbnails to be generated before exiting.

### Actual result

`gatsby build` terminates "successfully" once the static sites are generated, even though not all of the thumbnails are generated.

### Environment
```
  System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v11.12.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0.1
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.0.59 => 2.13.25
    gatsby-image: ^2.0.0 => 2.2.6
    gatsby-plugin-catch-links: ^2.0.0 => 2.1.2
    gatsby-plugin-eslint: ^2.0.1 => 2.0.5
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3
    gatsby-plugin-feed: ^2.0.0 => 2.3.4
    gatsby-plugin-google-analytics: ^2.1.6 => 2.1.23
    gatsby-plugin-lodash: ^3.0.1 => 3.1.2
    gatsby-plugin-manifest: 2.0.5 => 2.0.5
    gatsby-plugin-node-fields: ^1.0.0 => 1.0.0
    gatsby-plugin-react-helmet: ^3.0.0 => 3.1.2
    gatsby-plugin-robots-txt: ^1.3.0 => 1.5.0
    gatsby-plugin-sass: ^2.0.0 => 2.1.3
    gatsby-plugin-sharp: 2.0.7 => 2.0.7
    gatsby-plugin-sitemap: ^2.0.0 => 2.2.3
    gatsby-plugin-styled-components: ^3.0.0 => 3.1.2
    gatsby-plugin-twitter: ^2.0.0 => 2.1.2
    gatsby-source-filesystem: ^2.0.1 => 2.1.5
    gatsby-source-wordpress: ^3.0.0 => 3.1.9
    gatsby-transformer-sharp: 2.1.4 => 2.1.4

```

**Comment by tinder-kyleboss** [comment]
A little bit of good news for those who are facing this issue:

Reverting back to `gatsby@2.4.2` fixes the problem.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
