### ISSUE TITLE
Make website components used in MDX files globally available

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#19036]
## Summary

Make website components used in MDX files globally available through gatsby-plugin-theme-ui.

## Motivation

The only way to import components in MDX is to use relative paths, which breaks when pulling in content from translation repos.

## Components to make global

* LayerModel
* HorizontalNavList
* EmailCaptureForm
* APIReference

In addition, there are several components imported in `contributing/docs-and-website-components.md` which are only ever used as a demonstration that they *can* be imported. This isn't as high priority. There's also the examples in the "data-fetching" page.

## Already globally available

* GuideList
* EggheadEmbed

## Related Issues

* #19035 - This will create new components with GraphQL queries in them

**Comment by Qovaros985** [comment]
@tesseralis, could I work on this issue?

**Comment by tesseralis** [comment]
@Qovaros985 sure, go ahead if you still want to!
