### ISSUE TITLE
Markers in lists and Blockquote styles not showing in markdowns as expected

### ISSUE THREAD

**Issue by dillionmegida** [gatsbyjs/gatsby#19032]
## Description

Describe the issue that you're seeing.
When using markdowns, I don't get the expected results. For example,
- lists... When I try creating lists with hyphens or asterisks, I don't see a marker. All I see is some tabbed spaces before the content
- blockquotes... When I try creating blockquotes in markdowns ( > ...), I do not see the normal styles (border and faded background-color) for a blockquote, I also get tabbed spaces before the content

### Steps to reproduce
I followed the Gatsby tutorial docs on [from beginning](https://www.gatsbyjs.org/tutorial/part-zero/) to [the end](https://www.gatsbyjs.org/tutorial/part-eight/) and was able to set up my own blog.

You could check out this article on my blog - [Understanding event...](https://dillionmegida.com/p/understanding-event-target-and-use-cases/).
When you scroll down, you'll notice a blockquote 'According to the MDN docs...'
That's an example of an unexpected result of a blockquote

Also if you scroll down the more, you'll notice some lists without markers.

### Expected result
Markers for lists and styles for blockquotes.

### Actual result
No markers, no styles for blockquotes, just spaces

### Environment
  System:
    OS: Windows 10
    CPU: (4) ia32 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Edge: 40.15063.0.0
  npmPackages:
    gatsby: ^2.13.42 => 2.15.11 
    gatsby-plugin-disqus: ^1.1.2 => 1.1.2 
    gatsby-plugin-google-analytics: ^2.1.17 => 2.1.17 
    gatsby-plugin-gtag: ^1.0.11 => 1.0.11 
    gatsby-plugin-netlify-cms: ^4.1.15 => 4.1.15 
    gatsby-plugin-offline: ^3.0.15 => 3.0.15 
    gatsby-plugin-react-helmet: ^3.1.5 => 3.1.6 
    gatsby-plugin-sitemap: ^2.2.10 => 2.2.11 
    gatsby-remark-prismjs: ^3.3.9 => 3.3.12 
    gatsby-source-filesystem: ^2.1.10 => 2.1.21 
    gatsby-transformer-remark: ^2.6.15 => 2.6.21

**Comment by LekoArts** [comment]
Thank you for opening this!

When going to your reproduction I can't see the issues you're describing. The blockquote works fine (you need to handle the CSS styling) + looking at [your source code](https://raw.githubusercontent.com/dillionmegida/dillionmegida.com/master/src/pages/p/understanding-event-target-and-use-cases.md) you can use hyphens for the lists.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by dillionmegida** [comment]
Thank you for the feedback. I forgot to close the issue as soon as I solved it.
I expected the styles to be default but I realized that I had to manually specify them.
