### ISSUE TITLE
Convert `pages/contributing/index` to an MDX file

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#19034]
## Summary

Convert the index page of [contributing](https://www.gatsbyjs.org/contributing/) to an MDX file.

### Basic example

See the PR for pages/docs/index for a similar conversion:

https://github.com/gatsbyjs/gatsby/pull/18014

### Motivation

There are a few important pages to translate in the Contributing section (style guide and code of conduct) and it makes sense to translate the index of that section as well.

**Comment by sever1an** [comment]
I would like to work on this one.

**Comment by tesseralis** [comment]
@sever1an go ahead!

**Comment by sever1an** [comment]
The breadcrumbs at the top seem to be permanently baked into the mdx template, but are not present in `pages/contributing/index.js`. Are they acceptable in this page, or does a frontmatter option need to be created to disable them?

![image](https://user-images.githubusercontent.com/53988640/67627650-f54cdb80-f814-11e9-976d-233795ccc9ef.png)

**Comment by tesseralis** [comment]
I think it's fine! In fact, I think it's better that it's consistent. Good catch!

**Comment by sever1an** [comment]
This edit on github widget is also mandatory with the current template. It looks a little weird floating so far below (since there is no prev link), but that is beyond the scope of this issue I think. Creating a PR now.

![image](https://user-images.githubusercontent.com/53988640/67627744-eff09080-f816-11e9-85f5-fb801e0cd227.png)

**Comment by tesseralis** [comment]
I think it makes sense for it to be there since you *can* now just edit the page. But you're right that it looks weird. It affects other pages too (docs/index and tutorial/index) -- could you make in issue for it?

**Comment by sever1an** [comment]
Yeah I will make an issue for the edit on github link position, but it will be later this evening or tomorrow.
