### ISSUE TITLE
JSX in gatsby-browser.js causes error in monorepo

### ISSUE THREAD

**Issue by alexluong** [gatsbyjs/gatsby#19042]
## Description

I use a plugin `gatsby-plugin-chakra-ui` that has some JSX in `gatsby-browser.js`. The plugin works fine when it's used inside a normal site.

I'm now building a theme inside a monorepo (yarn workspaces), and I receive an error on `gatsby develop`:

```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (9:2)

File: ../../node_modules/gatsby-plugin-chakra-ui/gatsby-browser.js:9:2
```

I'm not entirely sure if this is because of JSX, but the location in the file (9:2) is the beginning of the JSX section.

When I move the code inside the plugin inside the theme (from `node_modules/gatsby-plugin-chakra-ui/gatsby-browser.js` to `packages/theme/gatsby-browser.js`), it works perfectly fine.

### Steps to reproduce

Here is [a minimal reproduction](https://github.com/alexluong/gatsby-issue-19042). Here is [the code for the `gatsby-plugin-chakra-ui`](https://github.com/chakra-ui/chakra-ui/tree/master/packages/gatsby-plugin-chakra-ui).

```
git clone ...
cd ...
yarn
yarn start
```

### Expected result

The site should work.

### Actual result

I received an error 👆

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.11.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.70
    Safari: 13.0.2
```

**Comment by alexlbr** [comment]
The problem with this issue isn't in Gatsby but in that particular plugin. I've submitted a [PR to fix it](https://github.com/chakra-ui/chakra-ui/pull/265). Related to [#19234](https://github.com/gatsbyjs/gatsby/pull/19234)

**Comment by sidharthachatterjee** [comment]
Nicely done, @alexlbr ❤️ 

Closing this for now then!

**Comment by dustinlacewell** [comment]
I think this issue has come back to life:

`node_modules/@chakra-ui/gatsby-plugin/gatsby-ssr.js`:

```jsx
import React from "react"
import { ColorModeScript } from "@chakra-ui/react"
import { WrapRootElement } from "./src/provider"
import theme from "./src/theme"

export const onRenderBody = ({ setPreBodyComponents }) => {
  setPreBodyComponents([
    <ColorModeScript
      initialColorMode={theme.config.initialColorMode}
      key="chakra-ui-no-flash"
    />,
  ])
}

export const wrapRootElement = (props) => {
  return <WrapRootElement {...props} />
}
```

```
success run page queries - 0.021s - 3/3 141.23/s

 ERROR #98123  WEBPACK

Generating development SSR bundle failed

Unexpected token (8:4)

File: ../../node_modules/@chakra-ui/gatsby-plugin/gatsby-ssr.js:8:4

not finished Building development bundle - 2.205s

Could not start Gatsby Development Server. See errors above.
```
```json
"gatsby": "3.2.1",
"@chakra-ui/gatsby-plugin": "^2.0.0",
```

**Comment by aaronadamsCA** [comment]
@alexluong / @dustinlacewell - did you ever find a long-term solution to this?

Plenty of popular plugins contain raw JSX in `gatsby-browser.js` or `gatsby-ssr.js`, including `gatsby-plugin-image` and `gatsby-plugin-theme-ui`. I'm having the same issue you were, where I'm using one of these plugins within a theme I'm developing in a monorepo, and it's failing; but [when I try to create a minimal reproduction it works just fine](https://github.com/aaronadamsCA/gatsby-issue-theme-plugin-jsx/tree/0cd962ca60ed35ea449238ee6d9be1af9db03902).

I'm reasonably confident that JSX in a shipped Gatsby plugin is legal. What I need to find is the unique set of conditions where it starts to fail.
