### ISSUE TITLE
Make some good tutorial videos for students and working professionals

### ISSUE THREAD

**Issue by abhitnc** [gatsbyjs/gatsby#19053]
### Basic example

A basic example could be official youtube video

### Motivation

Doing this as a part of Hacktoberfest

**Comment by thecodingaviator** [comment]
A basic example of what? Please elaborate

**Comment by sagarhani** [comment]
@abhitnc Checkout this : [Awesome Gatsby Resources](https://www.gatsbyjs.org/docs/awesome-gatsby-resources/)
