### ISSUE TITLE
gatsby-source-shopify does not allow a custom shopify domain

### ISSUE THREAD

**Issue by miracle2k** [gatsbyjs/gatsby#19055]
## Description

I want to use gatsby-source-shopify with my shopify shop, which has it's own domain configured on the shopify side.

If I post a request like this to Shopify:

`curl -X POST "https://my-domain.myshopify.com/api/2019-10/graphql"`

I get a Graphql Response: `{"errors":"Not Found"}`

If I post to:

`curl -X POST "https://my-real-domain.com/api/2019-07/graphql"`

It works.

So it seems I have to use the actual domain of the shop.

Unfortunately, the plugin does not allow `shopName` to be a full domain. It always wraps it in `myshopify.com`.

```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.1 - /var/folders/3m/xjwyhx8s0hx516g5261652vw0000gn/T/yarn--1572120325941-0.00028137310681586314/node
    Yarn: 1.19.0 - /var/folders/3m/xjwyhx8s0hx516g5261652vw0000gn/T/yarn--1572120325941-0.00028137310681586314/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.9.1/bin/npm
  Languages:
    Python: 3.7.3 - /Users/michael/.pyenv/shims/python
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.17.4 => 2.17.4
    gatsby-background-image: ^0.8.15 => 0.8.15
    gatsby-image: ^2.2.29 => 2.2.29
    gatsby-plugin-emotion: ^4.1.12 => 4.1.12
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23
    gatsby-plugin-offline: ^3.0.16 => 3.0.16
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13
    gatsby-plugin-sharp: ^2.2.32 => 2.2.32
    gatsby-plugin-typescript: ^2.1.15 => 2.1.15
    gatsby-source-filesystem: ^2.1.33 => 2.1.33
    gatsby-source-sanity: ^5.0.4 => 5.0.4
    gatsby-source-shopify: ^3.0.24 => 3.0.24
    gatsby-transformer-sharp: ^2.3.0 => 2.3.0
```

**Comment by pieh** [comment]
Seems like you are correct - we have `${shopName}.myshopify.com` hardcoded in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-shopify/src/create-client.js

Would be great to tackle this, just not sure what's best configuration object shape that would allow using short `shopName` or full (custom) domain - open for suggestions here.

In any case - other part of the plugin that uses `shopName` is https://github.com/gatsbyjs/gatsby/blob/3b503427475f4e08c9cd88fa55889604f76bd861/packages/gatsby-source-shopify/src/gatsby-node.js#L39-L53 (one that actually calls `create-client` and also uses shopName for log prefixes if anyone want to work on this

**Comment by miracle2k** [comment]
I'd be willing to do a PR. My personal preference would be to just recognize a `http` url. Alternatively, I'm not sure if shopify allows dots in the subdomain. If not, the presence of one could determine how it is treated.

**Comment by pieh** [comment]
I just tried creating new shop and seems like you can only specify human readable shop name and shopify will automatically convert `.` to `-` in url. So they don't allow `.` in shop url, but they allow it in shop name.

Given that we have this in our docs for the plugin:
```
// The domain name of your Shopify shop. This is required.
// Example: 'gatsby-source-shopify-test-shop' if your Shopify address is
// 'gatsby-source-shopify-test-shop.myshopify.com'.
shopName: "gatsby-source-shopify-test-shop",
```
we expect url part and not human readable name, so testing for `.` dot in this setting seems reasonably (updating note in README to mention how to use custom domain case will also help)

**Comment by miracle2k** [comment]
Still planning to work in this.

**Comment by lezan** [comment]
I am using a custom domain (not the .myshopify.com) but I am getting `The storeUrl value should be your store's myshopify.com URL in the form "my-site.myshopify.com", without https or slashes`. Does this prevent me from using a custom domain (actually just for the checkout page)?
