### ISSUE TITLE
Update react-helmet syntax across project

### ISSUE THREAD

**Issue by markmichon** [gatsbyjs/gatsby#1906]
With react-helmet v5, the syntax [was changed](https://github.com/nfl/react-helmet/blob/master/CHANGELOG.md#500-2017-03-21). This isn't a breaking issue, as it's all backwards compatible for now, but the change notes that the old props-based syntax will be deprecated in the future. Currently Gatsby uses the most recent version (5.1.3) in the core gatsby-plugin-react-helmet plugin.

The larger benefit is new user experience, as react-helmet docs don't include much info on the syntax used throughout Gatsby's docs. As far as I can tell it's only the examples and docs that use the syntax (maybe some starters too). 

I'm happy to make the changes and put together a PR for this if it's something the maintainers think is useful.

**Comment by KyleAMathews** [comment]
Sure! Would love a PR updating us to the latest and greatest. Thanks for offering!
