### ISSUE TITLE
failed Building static HTML for pages ERROR #95313

### ISSUE THREAD

**Issue by mrkyel** [gatsbyjs/gatsby#19077]
I just added a .md file 

I think this is reason.
------------------------------------------------------------------------------------------------------
https://stackoverflow.com/a/54769202
------------------------------------------------------------------------------------------------------

and this is my error code :

failed Building static HTML for pages - 2.873s

 ERROR #95313 

Building static HTML failed for path "/Goodifood/"

See our docs page for more info on this error: https://gatsby.dev/debug-html

  337 |           props = _objectWithoutProperties(_props, ["excludeScrollbar"]);
  338 | 
> 339 |       if (WrappedComponent.prototype.isReactComponent) {
      | ^
  340 |         props.ref = this.getRef;
  341 |       } else {
  342 |         props.wrappedRef = this.getRef;

  WebpackError: TypeError: Cannot read property 'isReactComponent' of undefined

  - react-onclickoutside.es.js:339 onClickOutside.render
    node_modules/react-onclickoutside/dist/react-onclickoutside.es.js:339:1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-nagui@1.0.0 deploy: `gatsby build && gh-pages -d public -b master`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-starter-nagui@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kyel100\AppData\Roaming\npm-cache\_logs\2019-10-28T08_24_59_576Z-debug.log

please somebody help me!

**Comment by sidharthachatterjee** [comment]
@mrkyel Could you please post a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)?
