### ISSUE TITLE
gatsby-plugin-netlify-cms won't load config.yml from a theme

### ISSUE THREAD

**Issue by TidyIQ** [gatsbyjs/gatsby#19078]
## Description

When using the [gatsby-plugin-netlify-cms](https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cms/) plugin within a theme, the plugin won't load the config file from the theme's directory (e.g. `gatsby-theme-mycustomtheme/static/admin/config.yml`). Instead, the config file MUST be placed in the site directory itself (e.g. `my-site/static/admin/config.yml`).

This causes huge issues with using themes as it means users of the theme need to manually apply any changes made to the `config.yml` file themselves - they can't simply update to the latest version of the theme package.

### Steps to reproduce

1. Create a basic theme
2. Install `gatsby-plugin-netlify-cms` as a plugin
3. Create a config file in `gatsby-theme-mytheme/static/admin/config.yml`
4. Add the theme to a Gatsby site
5. Run `gatsby develop`
6. Try to visit `http://localhost:8000/admin`. You should receive an error message
7. Move the config file to the site's static directory (e.g. `my-site/static/admin/config.yml`)
8. Run `gatsby develop`
9. Visit `http://localhost:8000/admin`. It will now be working.

### Expected result

`config.yml` should load from the theme where `gatsby-plugin-netlify-cms` has been installed.

### Actual result

Doesn't work

### Environment

```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - /c/Python27/python
  Browsers:
    Edge: 44.18362.387.0
```

**Comment by sidharthachatterjee** [comment]
Cc @erquhart

**Comment by erquhart** [comment]
The CMS plugin doesn't actually play a role here - the CMS itself looks for a config.yml in the published site, in the same directory the CMS page is located. From what you're describing it sounds like the static directory is ignored in themes, can anyone confirm whether this is the case?

**Comment by sidharthachatterjee** [comment]
@erquhart Yup, indeed. The `static` folder doesn't get copied over for themes at the moment (in `develop`)

We can follow progress on that issue in https://github.com/gatsbyjs/gatsby/issues/14003

**Comment by sidharthachatterjee** [comment]
Since it looks like the `gatsby-plugin-netlify-cms` doesn't need to be fixed for this to work, I'm closing this issue for now. 

@TidyIQ Please follow along in https://github.com/gatsbyjs/gatsby/issues/14003

Thanks for reporting this!
