### ISSUE TITLE
GitHub edit link on markdown template creates excessive whitespace when prev link missing.

### ISSUE THREAD

**Issue by sever1an** [gatsbyjs/gatsby#19070]
## Description
The GitHub edit link on the markdown template creates excessive whitespace when the prev link not present.

Related: https://github.com/gatsbyjs/gatsby/issues/19034

### Steps to reproduce
Visit https://www.gatsbyjs.org/tutorial/ and scroll to the bottom.

### Expected result
The link should appear more visually related to the content above, it seems out of place with so much extra spacing above.

### Actual result
![image](https://user-images.githubusercontent.com/53988640/67644160-175d6100-f8dc-11e9-8d77-925633377cdc.png)

### Environment
- Chrome 78
- No Gatsby environment involved.

**Comment by sever1an** [comment]
To avoid duplicated effort, this is where the affected link is created.

The markdown template adds a footer to each page: https://github.com/gatsbyjs/gatsby/blob/6e8f67b5598b12b7ae7cd27d7c68fcf1d3832f6a/www/src/templates/template-docs-markdown.js#L144

The footer contains a link to edit the markdown file on GitHub:
https://github.com/gatsbyjs/gatsby/blob/6e8f67b5598b12b7ae7cd27d7c68fcf1d3832f6a/www/src/components/markdown-page-footer.js#L23-L25

**Comment by rizqinizamil** [comment]
If the context to make it more visually related with content above, it should be right under the content.
![under the content](https://i.imgur.com/R3j0G2H.png)

What do you think?

**Comment by sever1an** [comment]
It makes sense. Reducing the line spacing (or margin) of the link would help it feel more typographically associated with the body text.

@tesseralis Do you think a PR implementing this would be approved?

**Comment by tesseralis** [comment]
@fk is Gatsby's designer and has all final say on design. What do you think Flo? I think it makes more sense

**Comment by fk** [comment]
Makes sense IMO, too — thanks for bringing it up @sever1an!
Let's do it!
