### ISSUE TITLE
Processed images aren't always copied to public

### ISSUE THREAD

**Issue by freiksenet** [gatsbyjs/gatsby#19083]
## Description

Processed images don't always get copied to public when needed. Seems to be an overly aggressive caching.

### Steps to reproduce

1. Start with `gatsby-blog-starter`
2. Build it
3. Observe `public/static/8058f3f26913fea3b6a89a73344fe94a`
4. Delete `public`
5. Build it
6. Observe that there is no `public/static/8058f3f26913fea3b6a89a73344fe94a`

### Expected result

Both scenarios should have `static/8058f3f26913fea3b6a89a73344fe94a` in `public/` folder.

### Explanation

Image processing isn't called in second case, probably due to some aggressive caching that doesn't check public.

**Comment by abnersajr** [comment]
Digging into the code what I can found is that the problem might be related with the two packages:
`gatsby-transformer-remark` and `gatsby-remark-images`

I noticed that after the first build and cache create, the plugin `gatsby-remark-images` isn't being called anymore.
This make me guess that the issue is with cache management from the `gatsby-transformer-remark`.

**Comment by danabrit** [comment]
@abnersajr Are you still looking into this?

**Comment by abnersajr** [comment]
Sorry @danabrit at that time I wasn't unable to proceed with that task.
I would like to keep going on that. I will recheck it and put my toughts on that. I remember that I had some feelings about this and would like to discuss it.

**Comment by abnersajr** [comment]
If I remember correctly, what I've found is that this doesn't check if the files exist, this only get the cache list and in case it exists it doesn't build again.
Would like to see if check the presence of files is the way to go or there are any other better way to do it?

**Comment by wardpeet** [comment]
This is fixed as we remove caches when public is not present
