### ISSUE TITLE
Gatsby-cli not working

### ISSUE THREAD

**Issue by t2ca** [gatsbyjs/gatsby#19088]
Getting the following error since updating to gatsby-cli@2.8.6

```
➜ gatsby clean
/usr/local/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'gatsby-core-utils'
Require stack:
- /usr/local/lib/node_modules/gatsby-cli/lib/reporter/errors.js
- /usr/local/lib/node_modules/gatsby-cli/lib/reporter/index.js
- /usr/local/lib/node_modules/gatsby-cli/lib/create-cli.js
- /usr/local/lib/node_modules/gatsby-cli/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/lib/reporter/errors.js:13:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/gatsby-cli/lib/reporter/errors.js',
    '/usr/local/lib/node_modules/gatsby-cli/lib/reporter/index.js',
    '/usr/local/lib/node_modules/gatsby-cli/lib/create-cli.js',
    '/usr/local/lib/node_modules/gatsby-cli/lib/index.js'
  ]
}

```

**Comment by RaulCote** [comment]
I was having the same problem today, just installed node 12 on ubuntu (mate) 19.10 and run to install gatsby-cli. I think that usually I just installed gatsby-cli, but I tried by installing gatsby ( npm install -g gatsby ) and everything began to work.

**Comment by boggsey** [comment]
I was just about to post the same thing. Can verify that gatsby-cli@2.8.5 installs without a problem.

**Comment by broeker** [comment]
Also just ran into this same error after running this update `Update available 2.8.2 → 2.8.5` -- also running on Ubuntu.

**Comment by boxdox** [comment]
Yep, facing the same issue.

`Error: Cannot find module 'gatsby-core-utils'`

@RaulCote Does running `npm i -g gatsby` solve the issue?

Node: 10.16.3

**Comment by RaulCote** [comment]
> Yep, facing the same issue.
> 
> `Error: Cannot find module 'gatsby-core-utils'`
> 
> @RaulCote Does running `npm i -g gatsby` solve the issue?
> 
> Node: 10.16.3

To me it did the trick.

**Comment by ryderwishart** [comment]
I was doing a fresh install and got the same error.

`npm i -g gatsby` fixed it for me!

**Comment by vdespa** [comment]
So is this a bug or the solution is to use only `npm i -g gatsby`?

**Comment by SarKurd** [comment]
`npm i -g gatsby` and `yarn global add gatsby-cli` didn't solve it for me, there must be a bug, i tried it with node 8, 10 and 12

**Comment by byebyers** [comment]
I am having the same issue on WSL. `npm i -g gatsby` is not working for me either. I have updated Gatsby, npm, and node. Glad I am not the only one having this problem.

**Comment by nokyantenna** [comment]
same issue too.. i get similar message when I install using `npm install --global gatsby-cli` and try to run `gatsby --help`

**Comment by nokyantenna** [comment]
> same issue too.. i get similar message when I install using `npm install --global gatsby-cli` and try to run `gatsby --help`

I uninstalled gatsby-cli and used `npm install --global gatsby` as others have recommended; it works with error messages about "unmet peer dependencies" but it works..

**Comment by sidharthachatterjee** [comment]
Apologies for this, just published a fix in `gatsby-cli@2.8.7`

Please test and close this 🙂

**Comment by t2ca** [comment]
Thank you @sidharthachatterjee for getting this fixed so quickly, closing.

**Comment by byebyers** [comment]
Thanks 🐱‍💻

**Comment by Kamez** [comment]
I have the same issue .
when I installed it told me "gatsby-cli@2.12.7" looks like nothing error, but when I tried check version it shows like below: 

> gatsby --version

`/usr/local/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Package exports for '/usr/local/lib/node_modules/gatsby-cli/node_modules/clipboardy' do not define a '.' subpath
    at resolveExports (internal/modules/cjs/loader.js:419:17)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/lib/create-cli.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32) {
  code: 'MODULE_NOT_FOUND'
}`

**Comment by keith-elliott** [comment]
FYI, I am getting the same error.  Ultimately, after installing an older version, it worked.  My installation command that produced a working CLI...

npm install -g gatsby-cli@2.12.0

**Comment by sarathm09** [comment]
Downgrading gatsby version did not help. Then I updated my node version to the latest and it started working.

**Comment by mosesoak** [comment]
@sidharthachatterjee Unfortunately this is still a problem. 

I'm on a new machine running WSL, latest Node LTS via NVM (v12.18.1), and latest Gatsby CLI (2.12.52).

Tried globally installing the cli via latest npm and yarn. (Project uses yarn.)

Works fine on my mac but throws the same error listed in WSL:

```bash
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'gatsby-cli'
Require stack:
- /mnt/c/projects/jel011/node_modules/gatsby/dist/bin/gatsby.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/mnt/c/projects/jel011/node_modules/gatsby/dist/bin/gatsby.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/mnt/c/projects/jel011/node_modules/gatsby/dist/bin/gatsby.js' ]
}
error Command failed with exit code 1.
```

**Comment by mosesoak** [comment]
Actually when I look at it, this is a slightly different error, but the cli isn't loading either way.

**Comment by mosesoak** [comment]
Follow up: after another full clean install of the repo and cli it is
working. Not sure what the issue was.

**Comment by eaylward8** [comment]
> I have the same issue .
> when I installed it told me "gatsby-cli@2.12.7" looks like nothing error, but when I tried check version it shows like below:
> 
> > gatsby --version
> 
> `/usr/local/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
> throw ex;
> ^
> 
> Error: Package exports for '/usr/local/lib/node_modules/gatsby-cli/node_modules/clipboardy' do not define a '.' subpath
> at resolveExports (internal/modules/cjs/loader.js:419:17)
> at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
> at Function.Module._load (internal/modules/cjs/loader.js:693:27)
> at Module.require (internal/modules/cjs/loader.js:864:19)
> at require (internal/modules/cjs/helpers.js:74:18)
> at Object. (/usr/local/lib/node_modules/gatsby-cli/lib/create-cli.js:24:20)
> at Module._compile (internal/modules/cjs/loader.js:971:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
> at Module.load (internal/modules/cjs/loader.js:822:32) {
> code: 'MODULE_NOT_FOUND'
> }`

I was getting this error and upgrading my node version fixed it. I think I was on node 13.9, now I'm on 14.5.0.

**Comment by lorensr** [comment]
I had the `Cannot find module 'gatsby-core-utils'` error coming from `./node_modules/yoga-layout-prebuilt` with `gatsby@2.32.8` and `node@12`. Switching to `node@14` removed the error.

**Comment by kubarbaz** [comment]
I've received same error in "Latest Version". LTS version seems OK.

**Comment by ChrisCrossCrash** [comment]
I'm still having this issue on Windows using:

node version 14.17.6 (the latest LTS version)
gatsby-cli (installed globally) version 3.13.0 (the latest version)

## To reproduce
1. open `cmd` on your `Desktop` directory
1. Execute the command `gatsby new gatsby-bug` to start the new Gatsby project.
1. Execute the commands `cd gatsby-bug` and `gatsby develop` to try to start the development server.

This gives me the following error:
```
C:\Users\Chris\Desktop\gatsby-bug>gatsby develop
C:\Users\Chris\Desktop\gatsby-bug\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'gatsby-core-utils'
Require stack:
- C:\Users\Chris\Desktop\gatsby-bug\node_modules\babel-plugin-remove-graphql-queries\index.js
- C:\Users\Chris\Desktop\gatsby-bug\node_modules\gatsby\dist\query\file-parser.js
- C:\Users\Chris\Desktop\gatsby-bug\node_modules\gatsby\dist\query\query-compiler.js
- C:\Users\Chris\Desktop\gatsby-bug\node_modules\gatsby\dist\query\query-watcher.js
- C:\Users\Chris\Desktop\gatsby-bug\node_modules\gatsby\dist\services\extract-queries.js
- C:\Users\Chris\Desktop\gatsby-bug\node_modules\gatsby\dist\services\index.js
- C:\Users\Chris\Desktop\gatsby-bug\node_modules\gatsby\dist\state-machines\develop\services.js
- C:\Users\Chris\Desktop\gatsby-bug\node_modules\gatsby\dist\state-machines\develop\index.js
- C:\Users\Chris\Desktop\gatsby-bug\node_modules\gatsby\dist\commands\develop-process.js
- C:\Users\Chris\Desktop\gatsby-bug\.cache\tmp-20104-WGMTq0uj61Jv
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (C:\Users\Chris\Desktop\gatsby-bug\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\Chris\Desktop\gatsby-bug\node_modules\babel-plugin-remove-graphql-queries\index.js:19:24)
    at Module._compile (C:\Users\Chris\Desktop\gatsby-bug\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (C:\Users\Chris\Desktop\gatsby-bug\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\Chris\Desktop\gatsby-bug\node_modules\gatsby\src\query\file-parser.js:15:5)
    at Module._compile (C:\Users\Chris\Desktop\gatsby-bug\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Chris\\Desktop\\gatsby-bug\\node_modules\\babel-plugin-remove-graphql-queries\\index.js',
    'C:\\Users\\Chris\\Desktop\\gatsby-bug\\node_modules\\gatsby\\dist\\query\\file-parser.js',
    'C:\\Users\\Chris\\Desktop\\gatsby-bug\\node_modules\\gatsby\\dist\\query\\query-compiler.js',
    'C:\\Users\\Chris\\Desktop\\gatsby-bug\\node_modules\\gatsby\\dist\\query\\query-watcher.js',
    'C:\\Users\\Chris\\Desktop\\gatsby-bug\\node_modules\\gatsby\\dist\\services\\extract-queries.js',
    'C:\\Users\\Chris\\Desktop\\gatsby-bug\\node_modules\\gatsby\\dist\\services\\index.js',
    'C:\\Users\\Chris\\Desktop\\gatsby-bug\\node_modules\\gatsby\\dist\\state-machines\\develop\\services.js',
    'C:\\Users\\Chris\\Desktop\\gatsby-bug\\node_modules\\gatsby\\dist\\state-machines\\develop\\index.js',
    'C:\\Users\\Chris\\Desktop\\gatsby-bug\\node_modules\\gatsby\\dist\\commands\\develop-process.js',
    'C:\\Users\\Chris\\Desktop\\gatsby-bug\\.cache\\tmp-20104-WGMTq0uj61Jv'
  ]
}
```

I also tried creating the project folder first, then running `gatsby new .` inside of it, which gave similar results.

## What Did Work

1. Open `cmd` and execute the command `gatsby new` (without any arguments) in the parent directory of where you want your new Gatsby project (for example, execute `gatsby new` on your `Desktop` directory if you want it to live in `Desktop\my-gatsby-site\`).
1. Follow the steps in the guided setup. Use the default values for everything.
1. Execute `cd my-gatsby-site` and then `gatsby develop`. The server should run without any issues.

## Final Thoughts

I've found this work-around, but I think this issue should be re-opened since I'm not the only one having this problem.

It's very interesting that @lorensr fixed this problem by updating to `node@14`, @kubarbaz fixed it by changing from Latest Version to LTS, and I'm having the issue with LTS. Maybe the act of simply re-installing Node is what did it? I don't really feel like re-installing Node to find out.

**Comment by rickwsonlee** [comment]
I am experiencing the same with @ChrisCrossCrash since yesterday. Neither LTS nor latest Node works for me. However, I was still able to run existing projects.

**Comment by damain** [comment]
Also had this issue when following the instructions to setup netlifycms on gatsby https://www.netlifycms.org/docs/gatsby/

```
npm install -g gatsby-cli
gatsby new blog https://github.com/gatsbyjs/gatsby-starter-blog
cd blog
```

After I ran the commands above I cd into the directory and ran `npm run develop` and got the error

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.10
  Browsers:
    Chrome: 93.0.4577.63
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.38)
  npmPackages:
    gatsby: ^3.13.0 => 3.13.0
    gatsby-plugin-feed: ^3.13.0 => 3.13.0
    gatsby-plugin-google-analytics: ^3.13.0 => 3.13.0
    gatsby-plugin-image: ^1.13.0 => 1.13.0
    gatsby-plugin-manifest: ^3.13.0 => 3.13.0
    gatsby-plugin-offline: ^4.13.0 => 4.13.0
    gatsby-plugin-react-helmet: ^4.13.0 => 4.13.0
    gatsby-plugin-sharp: ^3.13.0 => 3.13.0
    gatsby-remark-copy-linked-files: ^4.10.0 => 4.10.0
    gatsby-remark-images: ^5.10.0 => 5.10.0
    gatsby-remark-prismjs: ^5.10.0 => 5.10.0
    gatsby-remark-responsive-iframe: ^4.10.0 => 4.10.0
    gatsby-remark-smartypants: ^4.10.0 => 4.10.0
    gatsby-source-filesystem: ^3.13.0 => 3.13.0
    gatsby-transformer-remark: ^4.10.0 => 4.10.0
    gatsby-transformer-sharp: ^3.13.0 => 3.13.0
  npmGlobalPackages:
    gatsby-cli: 3.13.0

**Comment by r6q** [comment]
Have exactly the same issue after running
```
npx gatsby new myproject https://github.com/gatsbyjs/gatsby-starter-blog
```

```
npm run develop

> gatsby-starter-blog@0.1.0 develop /Users/rob/Development/playground/web/myproject
> gatsby develop

/Users/rob/Development/playground/web/myproject/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'gatsby-core-utils'
Require stack:
- /Users/rob/Development/playground/web/myproject/node_modules/babel-plugin-remove-graphql-queries/index.js
- /Users/rob/Development/playground/web/myproject/node_modules/gatsby/dist/query/file-parser.js 
...etc
```
After manually adding `gatsby-core-utils` it seems to be working fine - `npm i gatsby-core-utils`

Node: v14.17.3
Gatsby dependency version - ^3.13.0

**Comment by damain** [comment]
I had success after running `npm install` then `yarn`

**Comment by victorux** [comment]
Yesterday I have installed `nodejs 14.17.6 LTS` then `npm install -g gatsby-cli` after that I created a new project `gatsby new my-app` all was installed with no errors, then I went into the folder `cd my-app` and tried to start the local server `gatsby develop`, and voila: 
`.../Desktop/my_portfolio/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'gatsby-core-utils'`

I tried all the above options nothing helped.


OS: macOS BigSur 11.5.2
Gatsby CLI version: 3.13.0
Gatsby version: 3.13.0

**Comment by SchwarzerKaiser** [comment]
Still happens for me as well. Running `npm i gatsby-core-utils` fixed it.

**Comment by crisperpo** [comment]
as @ChrisCrossCrash mentioned running `gatsby new` without the name, and then following the instructions with your custom app name works.
node v14.17.3

**Comment by victorux** [comment]
> as @ChrisCrossCrash mentioned running `gatsby new` without the name, and then following the instructions with your custom app name works.
> node v14.17.3

Thank you @crisperpo this worked for me!!

**Comment by danielschmid** [comment]
Same problem as described but the workaround mentioned doesn’t work for me.

But instead i get a new different error message 
`Invalid options object. Ignore Plugin has been initialized using an options object that does not match the API schema.`

Node v14.16.1
Gatsby CLI version: 3.13.0
Gatsby version: 3.13.0

**Comment by AnkitGupta17134** [comment]
`npm install gatsby-core-utils`

For me this worked. Instead of `npm -i g npm`.
