### ISSUE TITLE
Rebuild err: compilation.getPathWithInfo is not a function

### ISSUE THREAD

**Issue by mstys** [gatsbyjs/gatsby#19081]
## Description

Starting with `gatsby develop` project build correctly. Then after changing any file, project starts rebuilding and failing. Error in console:

```

success Re-building development bundle - 3.941s  gatsby-starter-netlify-cms
/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: compilation.getPathWithInfo is not a function
    at compilation.hooks.additionalChunkAssets.tap (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/gatsby/node_modules/webpack/lib/HotModuleReplacementPlugin.js:309:23)
    at SyncHook.eval [as call] (eval at create (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/webpack/lib/Compilation.js:1299:37)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/webpack/lib/Compilation.js:1242:27)
    at hooks.make.callAsync.err (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/webpack/lib/Compiler.js:550:17)
    at _done (eval at create (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err1 (eval at create (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:22)
    at _addModuleChain (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/webpack/lib/Compilation.js:1093:12)
    at processModuleDependencies.err (/Users/michal.stys/OwnProjects/gatsby-blog/node_modules/webpack/lib/Compilation.js:1005:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! gatsby-starter-netlify-cms@1.1.3 develop: `npm run clean && gatsby develop`
npm ERR! Exit status 7
npm ERR! 
```

### Steps to reproduce

Not sure. It was working correctly.

### Expected result

Should rebuild correctly.

### Actual result

Rebuild fails. See above desc

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.2/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.17.0 => 2.17.0 
    gatsby-image: ^2.2.29 => 2.2.29 
    gatsby-plugin-disqus: ^1.1.4 => 1.1.4 
    gatsby-plugin-google-tagmanager: ^2.1.15 => 2.1.15 
    gatsby-plugin-netlify: ^2.1.22 => 2.1.22 
    gatsby-plugin-netlify-cms: ^3.0.18 => 3.0.18 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-purgecss: ^2.4.0 => 2.4.0 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13 
    gatsby-plugin-sass: ^2.1.20 => 2.1.20 
    gatsby-plugin-sharp: ^2.2.32 => 2.2.32 
    gatsby-remark-copy-linked-files: ^2.1.28 => 2.1.28 
    gatsby-remark-images: ^3.1.28 => 3.1.28 
    gatsby-remark-prismjs: ^3.3.20 => 3.3.20 
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3 
    gatsby-source-filesystem: ^2.1.33 => 2.1.33 
    gatsby-transformer-remark: ^2.6.30 => 2.6.30 
    gatsby-transformer-sharp: ^2.3.0 => 2.3.0 
  npmGlobalPackages:
    gatsby-cli: 2.4.3
```

any thoughts?

Cheers !

**Comment by Blockshape01** [comment]
Having same issue, started after latest node update about 48 hours ago.

**Comment by Blockshape01** [comment]
> Having same issue, started after latest node update about 48 hours ago.
/Users/user/TREOS3.0/node_modules/webpack/lib/HotModuleReplacementPlugin.js:287
                                                                        } = compilation.getPathWithInfo(hotUpdateChunkFilenam

e, {
                                                                                        ^

[  TypeError: compilation.getPathWithInfo is not a function

  - HotModuleReplacementPlugin.js:287
    [TREOS3.0]/[webpack]/lib/HotModuleReplacementPlugin.js:287:26


  - Hook.js:154 SyncHook.lazyCompileHook
    [TREOS3.0]/[tapable]/lib/Hook.js:154:20

  - Compilation.js:1301
    [TREOS3.0]/[app]/[webpack]/lib/Compilation.js:1301:37
- Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [TREOS3.0]/[tapable]/lib/Hook.js:154:20

  - Compilation.js:1244 Compilation.seal
    [TREOS3.0]/[app]/[webpack]/lib/Compilation.js:1244:27


  - Compiler.js:625
    [TREOS3.0]/[app]/[webpack]/lib/Compiler.js:625:18

  - Compilation.js:1167
    [TREOS3.0]/[app]/[webpack]/lib/Compilation.js:1167:4


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [TREOS3.0]/[tapable]/lib/Hook.js:154:20

  - Compilation.js:1159 Compilation.finish
    [TREOS3.0]/[app]/[webpack]/lib/Compilation.js:1159:28

  - Compiler.js:622
    [TREOS3.0]/[app]/[webpack]/lib/Compiler.js:622:17



  - Compilation.js:1091
    [TREOS3.0]/[app]/[webpack]/lib/Compilation.js:1091:12

]

**Comment by mstys** [comment]
BTW: I run the same code in docker container and working well so looks like environment issue.

**Comment by zhengjunxin** [comment]
I solve this problem by downgrading the webpack version

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by bbugh** [comment]
@zhengjunxin can you specify which webpack version you downgraded to?

**Comment by Morantron** [comment]
Had the same issue, in my case it went away by bumping `gatsby-plugin-netlify-cms` to version `4.1.27` :man_shrugging:

**Comment by wardpeet** [comment]
> Had the same issue, in my case it went away by bumping gatsby-plugin-netlify-cms to version 4.1.27 🤷‍♂

I guess this is our answer :)

**Comment by Artofaj** [comment]
> Had the same issue, in my case it went away by bumping `gatsby-plugin-netlify-cms` to version `4.1.27` man_shrugging

I can confirm this worked for me. Thank you!
