### ISSUE TITLE
Rename "boundActionCreators" to just actions

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1909]
I went with `boundActionCreators` as that's what they are in Redux but… nobody actually knows (or should care) that we're using Redux under the hood so we could give these functions a much more graceful name e.g. just `actions` or `commands`.

Thoughts?

We could do this as part of #1824

**Comment by KyleAMathews** [comment]
Or we could just do this now as a non-breaking change. Pass both to APIs but change the docs to use the new name.

**Comment by Redmega** [comment]
I like the idea of aliasing `boundActionCreators` to `actions` and deprecating the `boundActionCreators` api. Maybe log a warning to console that using the old name is deprecated.

**Comment by KyleAMathews** [comment]
We shouldn't mark `boundActionCreators` depreciated until v2 though.
