### ISSUE TITLE
Print out timing for steps to build + live progress updates while building

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#191]
https://www.npmjs.com/package/single-line-log

**Comment by KyleAMathews** [comment]
For building html pages, can show # + % progress e.g. `built 17/154 pages 11%`

For building javascript, it'd be easy to cache the time / # pages for the build so after the first build, we could estimate the total time to build the `bundle.js` and show live updating progress towards that.

**Comment by KyleAMathews** [comment]
https://github.com/tj/node-progress

**Comment by Chuloo** [comment]
This issue seems to be resolved 👍
