### ISSUE TITLE
Set mediaType of nested node to text/markdown

### ISSUE THREAD

**Issue by pgegenfurtner** [gatsbyjs/gatsby#19119]
Via a custom source plugin I get the following data structure from my content api:
(Example for a page)
```
{
  "id": 57,
  "status": "published",
  "created_on": "2019-10-29 12:27:51",
  "modified_on": "2019-10-29 12:27:51",
  "name": "Test",
  "layout": "default",
  "parent_page": null,
  "header_images": [],
  "translations": [
    {
      "language": "de",
      "display_name": "Test",
      "slug": "test",
      "seo_title": "Test",
      "seo_description": null,
      "content": "# MDX Inhalt",
      "excerpt": "Lorem Ipsum"
    },
    {
      "language": "en",
      "display_name": "Test",
      "slug": "test",
      "seo_title": "Test",
      "seo_description": null,
      "content": "# MDX Content",
      "excerpt": "Lorem Ipsum"
    }
  ]
}
```

I would like to have the content of the page (under translations) to be recognized as markdown/mdx, so that the mdx-plugin processes it.

I know that I would do it via the schema customization, but I don't fully understand how.

This post https://weknowinc.com/blog/how-create-text-markdown-node-process-content-using-gatsby describes a way, but maybe there is a more elegant solution, than to create many more top nodes and "pollute" the schema.

**Comment by LekoArts** [comment]
Thank you for opening this!

It's perfectly fine to do it the way like the blog post proposed it.
For MDX there is also this possibility: https://www.christopherbiscardi.com/post/creating-mdx-nodes-from-raw-strings/#raw-strings-or-nodes

Generally speaking you can create your own custom field extension to use it in the schema: https://www.gatsbyjs.org/docs/schema-customization/#creating-custom-extensions
Scroll down a bit to see an example of Markdown.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Comment by pgegenfurtner** [comment]
Thank you for your answer.
When I implement it this way, I would create a new mdx node for each translation available and append it to the page node. This gives me the following schema:

```
page {
  name
  layout
  [...]
  translations {
    language
    display_name
    content
  }
  fields {
    PageMdxNodeDE {
      childMdx
    }
    PageMdxNodeEN {
      childMdx
    }
  }
}
```

But I'd rather have the content field in the translations field to have a childMdx. Not a new fields node under page.

This is the structure I desire:
```
page {
  name
  layout
  [...]
  translations {
    language
    display_name
    content {
      childMdx
    }
  }
}
```
I don't know, how I could append the new mdx node to the translations field, because it is not a node.

**Comment by LekoArts** [comment]
Hi!

So I tried some things in the meantime but sadly have to tell you that these are currently the only ways to do it. We can't do what you want right now.

We're tracking this feature request here: https://github.com/gatsbyjs/gatsby/issues/18976

**Comment by pgegenfurtner** [comment]
Okay, then I will do it this way for now and observe the other issue.

Thank you!
