### ISSUE TITLE
<BrowserRouter> ignores the history prop.

### ISSUE THREAD

**Issue by 3axap4eHko** [gatsbyjs/gatsby#1913]
in the line https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/root.js#L86
`<BrowserRouter>` ignores the history prop. To use a custom history, use `import { Router }` instead of `import { BrowserRouter as Router }`.

UPD: As the result you will get an error `You cannot change <Router history>`

**Comment by KyleAMathews** [comment]
>As the result you will get an error You cannot change <Router history>

Where do you get this error?

**Comment by 3axap4eHko** [comment]
@KyleAMathews after a hot reload of a page when page component changed

**Comment by akadop** [comment]
Yeah I've been getting it over and over as well

**Comment by KyleAMathews** [comment]
👍 great! So dev only but yeah, let's fix this. @3axap4eHko could you create a PR with a fix?

**Comment by 01Kuzma** [comment]
Hi,
the react-router version 4.2

The index.js:
```
import { BrowserRouter, Route, Switch } from 'react-router-dom';
import createBrowserHistory from 'history/createBrowserHistory';
const history = createBrowserHistory();

  render() {   

    return (
        <div>
          <BrowserRouter history={history}>
            <Switch>
              <Route exact path="/:lng?" component={App} />
              <Route component={NoMatch} />
            </Switch>
          </BrowserRouter>
        </div>
```

Error: `Warning: <BrowserRouter> ignores the history prop. To use a custom history, use `import { Router }` instead of `import { BrowserRouter as Router }`.`

**Comment by francas** [comment]
Is this fixed or won't be fixed?

**Comment by KyleAMathews** [comment]
It's fixed

**Comment by zwsf** [comment]
how to fixed it?

**Comment by raeesaa** [comment]
I get same warning with HashRouter using version 4.2.2 of `react-router-dom`. Is this fixed for `HashRouter` as well or only for `BrowserRouter`?

**Comment by whmountains** [comment]
@zwsf @raeesaa Try updating gatsby.

**Comment by thorakmedichi** [comment]
I'm getting this error as well. 
React 16.2
React-router 4.2.2
