### ISSUE TITLE
Gatsby-image serving larger images on smaller responsive breakpoints

### ISSUE THREAD

**Issue by gallor** [gatsbyjs/gatsby#19149]
## Description

Similar to #8100 but appears to be more related to how Gatsby-image handles responsive layouts. Whenever I reduce the width of my website, the image served by gatsby image size becomes bigger at a certain point. I'm pretty new to Gatsby so if this is a configuration issue please let me know how to fix it. Thanks!

This is the image when it's in a "mobile" width. Notice the image width being 864px:
<img width="512" alt="Screen Shot 2019-10-30 at 9 43 48 AM" src="https://user-images.githubusercontent.com/4968271/67868463-0427dc80-fafa-11e9-855c-a53ba537b32b.png">

If I make it a little larger to trigger a breakpoint, the image reduces in size to 583.19px
<img width="569" alt="Screen Shot 2019-10-30 at 9 44 19 AM" src="https://user-images.githubusercontent.com/4968271/67868622-39342f00-fafa-11e9-860e-bde9a558a977.png">

### Steps to reproduce

Easiest way to reproduce is to just clone my landing site. It's pretty small and is easier than trying to document the problem here. The page in question is the `src/pages/index.js` page. Open this page in Chrome, launch dev tools and click to toggle device toolbar. Make sure you select "Responsive" for the size and then reduce the width to below 480. You'll see the image jump to be bigger.

### Expected result
When the width is reduced I expect the image to continue to reduce in size to maintain the aspect ratio so there's no jump in size and subsequent "zooming" of the image. 

### Actual result
Reducing the window width makes the image jump bigger, causing the image to zoom in closer and showing less of the image.

### Environment
 System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 3.7.4 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 66.0.3
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.39 => 2.13.39
    gatsby-image: ^2.2.6 => 2.2.6
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sass: ^2.1.3 => 2.1.3
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4
  npmGlobalPackages:
    gatsby-cli: 2.7.19

**Comment by LekoArts** [comment]
Where can we find your landing page / reproduction?

**Comment by gallor** [comment]
@LekoArts Oh drat, sorry about that. Thought I posted a link to it. Here you go: https://github.com/gallor/allorstudio/tree/big-mobile-image. Thanks.

**Comment by gallor** [comment]
So just as an update I discovered, I had set a min-height on the encompassing container for a necessary desktop styling. Removing that fixed the image from getting bigger in mobile. 
However, I think my question still stands though, why, if a min-height is set, would the mobile view serve a bigger sized image than on a viewport slightly larger?

**Comment by graysonhicks** [comment]
> So just as an update I discovered, I had set a min-height on the encompassing container for a necessary desktop styling. Removing that fixed the image from getting bigger in mobile.
> However, I think my question still stands though, why, if a min-height is set, would the mobile view serve a bigger sized image than on a viewport slightly larger?

Two things going on here.  First, `gatsby-image` does not see/use the container's CSS (such as min-height) when generating the images unless it is passed in through gatsby-image props (`imgStyle` or `style`) specifically.  It only cares about the `maxWidth` and `maxHeight` in the query.  In your screenshots, the number that you are saying is getting bigger is the `height` not the `width`.  The width is staying 100% of the viewport as you can also see in the screenshots.

Second, when running the [repro in a CodeSandbox](https://codesandbox.io/s/github/gallor/allorstudio/tree/big-mobile-image), I successfully see the smaller images being loaded at the smaller viewpoints:

![image](https://user-images.githubusercontent.com/16200795/70355559-751c8b80-1840-11ea-80ba-a8ebb05ae7ef.png)

Loading those image files in Chrome separately you can see the file that loads on small devices is a smaller version of the previous image.

Hope this answers your question.
