### ISSUE TITLE
[gatsby-source-contentful] Add option to customize locale fallback mechanism

### ISSUE THREAD

**Issue by disintegrator** [gatsbyjs/gatsby#19145]
## Summary

`gatsby-source-contentful` currently looks at the locale information fetched from Contentful, which includes mapping of fallback locales. I propose letting developers override these definitions by passing an option to the plugin

You can get a good understanding about locales and locale fallbacks in Contentful here: https://www.contentful.com/developers/docs/tutorials/general/setting-locales/ (under "Custom fallback locales")

### Basic example

I propose adding the following option to `gatsby-source-contentful`:
```js
{
  resolve: "gatsby-source-contentful",
  options: {
    getLocaleFallback({
      type,
      fieldName,
      locale,
      defaultLocale,
      defaultFallbacks
    }) {
      // All asset fields should fallback to values in default locale
      // if localized data is missing
      if (type === "ContentfulAsset") {
        return defaultLocale;
      }
      // This is an example of inspect the type AND fieldName which allows
      // finer control over fallback mechanism
      if (type === "ContentfulTag" && fieldName === "title") {
        return "en";
      }
      // Returning null indicates that a field should not rely locale
      // fallback
      return null;
    }
  }
}
```

**`getLocaleFallback` is invoked whenever the source plugin encounters a _localized_ field with a missing value for a locale.**

`getLocaleFallback` has the following TypeScript type:

```ts
type Locale = string;

interface GetLocaleFallbackData {
  /** Content type or asset type **/
  type: string;

  /** The name of the field on the content/asset type that has missing data */
  fieldName: string;

  /** The locale that is missing data on the content/asset type */
  locale: Locale;

  /** The default locale configured in Contentful */
  defaultLocale: Locale;

  /** The default fallback configuration fetched from Contentful */
  defaultFallbacks: Record<Locale, Locale>
}

type GetLocaleFallback = (data: GetLocaleFallbackData) => string | null | undefined;
```

### Motivation

Contentful's locale fallback mechanism is not granular enough. This means you cannot define how locale fallback works on assets and content independently, let alone individual fields in a content type. I assume there are several projects, like ours, that switch off the fallback mechanism because of this but it will break asset management because, for most assets, you need to upload the same file to each locale which is detrimental to content creators' productivity. If the feature proposed in this PR existed, developers can solve this problem like so:

```js
{
  resolve: "gatsby-source-contentful",
  options: {
    getLocaleFallback({
      type,
      defaultLocale,
      defaultFallbacks
    }) {
      if (type === "ContentfulAsset") {
        return defaultLocale;
      }

      return defaultFallbacks[locale];
    }
  }
}
```

**Comment by jessepinho** [comment]
Love this idea! Would be happy to help, @disintegrator . @Khaledgarbaya  / @pieh what do y'all think?

**Comment by disintegrator** [comment]
@jessepinho Thanks :)
I'd like to know if the maintainers are open to such a feature before proceeding...

**Comment by jessepinho** [comment]
Would still love to get @Khaledgarbaya / @Pieh's thoughts on this idea! I think it could be really useful for a lot of Gatsby developers using Contentful (including myself). Thoughts?
