### ISSUE TITLE
Add React "experimental" package to e2e tests

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#19158]
[@acdlite asked](https://twitter.com/acdlite/status/1187086077095362561) that React projects add [React's new `experimental` branch to tests](https://reactjs.org/blog/2019/10/22/react-release-channels.html) to catch breaking changes early.

One way we could do this is to run our e2e tests with it (as a non-blocking check).

Thoughts @gatsbyjs/core?

**Comment by blainekasten** [comment]
This isn't working correctly yet. The nightly run is asserting files change and exiting. Which of course on a nightly job, no files are changing. So need to work on this some more.

**Comment by blainekasten** [comment]
I think ward fixed this. I'll check back tomorrow

**Comment by pieh** [comment]
I think this is done now and working and this ticket can be closed
 - `react@next`: https://circleci.com/workflow-run/8a8f4c4e-26ba-4632-9895-22d1406268b7
 - `react@experimental`: https://circleci.com/workflow-run/75b3b161-2574-4d38-88f8-226e254c20cd
