### ISSUE TITLE
page-data.json returning 404 due to missing path to page

### ISSUE THREAD

**Issue by pr1ntr** [gatsbyjs/gatsby#19156]
## Description

page-data.json not being found in production instead returns 404

### Steps to reproduce

Not sure how, I have a particular setup and we have been working on it for months.
What should be known is that we don't use pagequeries and instead just use a couple of big queries in node.createPages to get all of our data from prismic. This is because prismic is less than ideal for big sites and has no concept of generics. 

### Expected result

It should look for page data here:
http://localhost:5000/page-data/promo/ultimate-texas-holdem/page-data.json

### Actual result

looks for page data here instead
http://localhost:5000/page-data//page-data.json

### Environment

```
 System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.4 - /c/Users/Pavel/AppData/Local/Programs/Python/Python37/python
  Browsers:
    Edge: 44.18362.387.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by pr1ntr** [comment]
Could you shed some light on the process that finds the page-data.json? Maybe I can try to figure it out on my own.

**Comment by jitendra-koodo** [comment]
I'm also getting 404 for prefetch request /page-data//page-data.json . Not sure where is this double slash coming from, possibly something is missing between these 2 slashes..

**Comment by pr1ntr** [comment]
@jitendra-koodo maybe we can work together on this? Do you get any errors that look like this in your console (in dev mode): 
`Error loading a result for the page query in "". Query was not run and no cached result was found.`

**Comment by jitendra-koodo** [comment]
> @jitendra-koodo maybe we can work together on this? Do you get any errors that look like this in your console (in dev mode):
> `Error loading a result for the page query in "". Query was not run and no cached result was found.`

Thanks Pav. Appreciated.

Yes, I see that error.

This is what I see.
--
success Re-building development bundle - 0.776s
Error loading a result for the page query in "". Query was not run and no cached result was found.

**Comment by pr1ntr** [comment]
Interesting, can you paste your gatsby-node.js and gatsby-config.js?

Here are mine 
[gatsby-node.js](https://gist.github.com/pr1ntr/52dac7770fa09efbc8821d8e8ebbb24b)
[gatsby-config.js](https://gist.github.com/pr1ntr/0b44c67f71590fba8ca5381acef5d663)


Are you using prismic by chance?

**Comment by jitendra-koodo** [comment]
Pav, sorry about late reply..

I'm not using Prismic. Both files attached as you asked for...

[gatsby.zip](https://github.com/gatsbyjs/gatsby/files/4033849/gatsby.zip)

**Comment by pr1ntr** [comment]
I was really hoping for some revelation to appear but unfortunately I couldn't fine one. The only real similarity is we have dynamic pages. But as far as I can tell neither of these are building a page with a blank path.

**Comment by jitendra-koodo** [comment]
Thanks Pav for checking this. See this [comment ](https://github.com/gatsbyjs/gatsby/issues/15322#issuecomment-574076721)here suggesting that offline worker might be causing it. I still need to check this.

**Comment by abheist** [comment]
**Resolved for me**: was getting the same error.

Made a `Link` to the `page` which does not exist.

Eg:

```html
<Link to="/articles">
    Articles
</Link>
```

and the `page/article` was not created.
