### ISSUE TITLE
Using with graphql in an app

### ISSUE THREAD

**Issue by Aleksion** [gatsbyjs/gatsby#1916]
I was planning on using gatsby-js to serve both my marketing page and my applicaiton. However, it seems that using other graphql related tools make the compiler fail with the error:

```
There was an error while compiling your site's GraphQL queries
Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
```

Is there anything to be done about this? Or do I just have to accept that I need to move my app into a seperate application and loose the niceness of the super fast initial render.

**Comment by KyleAMathews** [comment]
Hmmm could be a lot simpler than that. Sounds like you might have multiple instances of `graphql` installed in your `node_modules`.

**Comment by Aleksion** [comment]
That's most likely the case. I've been trying to track down which of my dependencies that does it, but the cache makes it very unreliable (installing the dependencies 1 by 1. Nothing fails. Then after restarting a few times it does, and keeps doing it until I delete cache, møde_modules and Yarn.lock).
I intended to use relay (after being fed up with Apollo's magical store on a previous projects). But one of react relays dependencies imports graphql and make it break.

Besides react relay has a function named graphql as well

________________________________
On Friday, August 25, 2017 at 19:53 Kyle Mathews <notifications@github.com> wrote:


Hmmm could be a lot simpler than that. Sounds like you might have multiple instances of graphql installed in your node_modules.

**Comment by KyleAMathews** [comment]
`find node_modules -iname graphql` should find it.

But yeah… not sure what to do about getting Gatsby + Relay work together…

**Comment by jquense** [comment]
vote on https://github.com/graphql/graphql-js/pull/989 !

**Comment by Aleksion** [comment]
Vote has been cast. I'm torn. Split into two app's or abandon relay. (though I might find out the same problem occurs with Apollo).

**Comment by JohnShahawy** [comment]
I'm using graphql at buildtime and runtime...just not calling both from the top level pages component.  I've never run into this issue (using apollo).

**Comment by Aleksion** [comment]
I switched to Apollo for the same reason. It works fine with apollo, but it clashes with relay.

**Comment by KyleAMathews** [comment]
There should be fewer problems installing `graphql` in v2 (out in beta) so closing this now.
