### ISSUE TITLE
Pages starting with Capital letter(s) failing

### ISSUE THREAD

**Issue by TriStarGod** [gatsbyjs/gatsby#19167]
## Summary
Pages starting with Capital letter(s) failing with a white page page.
## Relevant information
As part of my process, I keep a specific name scheme. In a general react project, if I Capitalize the first letter of a page, it renders fine. However, in Gatsby, it renders a white page. Is this normal? I know caps don't matter in urls so I don't know understand why it renders a white page.

### Environment (if relevant)
Windows 10 x64

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
  Binaries:
    Yarn: 1.19.1 - C:\Users\...\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.17.6 => 2.17.6
    gatsby-image: ^2.2.30 => 2.2.30
    gatsby-plugin-manifest: ^2.2.25 => 2.2.25
    gatsby-plugin-offline: ^3.0.17 => 3.0.17
    gatsby-plugin-react-helmet-async: ^1.0.3 => 1.0.3
    gatsby-plugin-sharp: ^2.2.34 => 2.2.34
    gatsby-source-filesystem: ^2.1.35 => 2.1.35
    gatsby-transformer-sharp: ^2.3.1 => 2.3.1
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: 
```
exports.onCreateWebpackConfig = ({ stage, actions }) => {
  if (stage.startsWith("develop")) {
    actions.setWebpackConfig({
      resolve: {
        alias: {
          "react-dom": "@hot-loader/react-dom",
        },
      },
    })
  }
}
```
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

Unfortunately you're required to have your filenames lowercased. You can find the explanation [here](https://github.com/gatsbyjs/gatsby/issues/15759#issuecomment-511557139):

> Yeah, it's a convention since the casing of the filename maps directly to the rendered file. So /Index/index.html is isn't rendered at the / path, only /Index/.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
