### ISSUE TITLE
Nested  dependency issue?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#19169]
```bash
RN:RYKR rchrdnsh$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Machine-In-The-Middle                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ https-proxy-agent                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.2.3                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ npm                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ npm > libcipm > pacote > make-fetch-happen >                 │
│               │ https-proxy-agent                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1184                            │
└───────────────┴──────────────────────────────────────────────────────────────
```

getting this 16 times, so it seems some dependencies need to update their dependencies, or something...

...dunno how to fix this, however...any thoughts on how  to upgrade this nested dependancies?

**Comment by LekoArts** [comment]
Thank you for opening this!

Gatsby depends on a lot of other packages and with our Renovate bot we try to stay on the latest versions (as much as possible, sometimes we can't upgrade as we e.g. still support Node 8). You should look into the warnings and packages yourself to verify if it's actually a vulnerability for your usecase. In most cases those are edge-cases and we (Gatsby) or you aren't affected by it at all.

If you want to update certain deps nevertheless, you can use yarn resolutions: https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by rchrdnsh** [comment]
figured it out....somehow `npm` istelf snuck in to my `package.json` file...super odd...I noticed something was not right when I had two `node-modules` folders...anyway, the issue is gone now :-)
