### ISSUE TITLE
gatsby-remark-prismjs failed to highlight cpp code

### ISSUE THREAD

**Issue by VincentBel** [gatsbyjs/gatsby#1917]
### Problem

`gatsby-remark-prismjs` failed to highlight the following [markdown with cpp code](https://github.com/VincentBel/gatsby-prism-cpp-highlight-bug/blob/master/src/pages/test-blog-with-cpp-code/index.md):

````plain
## A Sample Cpp Code

```cpp
int sum(int a, int b) {
    return a + b;
}
```
````
> I made a repo([VincentBel/gatsby-prism-cpp-highlight-bug](https://github.com/VincentBel/gatsby-prism-cpp-highlight-bug)) to reproduce the issue.  
> Some quick link:
> - [gatsby-config.js](https://github.com/VincentBel/gatsby-prism-cpp-highlight-bug/blob/master/gatsby-config.js)
> - [package.json](https://github.com/VincentBel/gatsby-prism-cpp-highlight-bug/blob/master/package.json)

**The result**:

![image](https://user-images.githubusercontent.com/6076919/29737762-4593e37a-8a46-11e7-875f-bbf039f56475.png)

and the [generated js file](https://github.com/VincentBel/gatsby-prism-cpp-highlight-bug/blob/70ad594a341d7591d8a54e6634e8f30a15da7e40/public/test-cpp-code-highlight/index.html#L12-L14):

```html
      <pre class="language-cpp"><code>int sum(int a, int b) {
    return a + b;
}</code></pre>
```

### Env

- OS: macOS Sierra 10.12.6
- node: v6.9.1
- npm: 5.3.0
- yarn: 0.27.5
- gatsby version:

```js
"gatsby": "^1.9.7",
"gatsby-remark-prismjs": "^1.2.1",
"gatsby-source-filesystem": "^1.4.4",
"gatsby-transformer-remark": "^1.7.2",
```

**Comment by VincentBel** [comment]
I investigated the issue, and here are some info:

### What cause the problem?

`gatsby-remark-prismjs` will try to require prism the required language component:

https://github.com/gatsbyjs/gatsby/blob/9379cbb74fbab841ad113f730963feaf01244c20/packages/gatsby-remark-prismjs/src/highlight-code.js#L6-L12

but for language `cpp`, it extends `c`:([prism: components/prism-cpp.js](https://github.com/PrismJS/prism/blob/5400af9eacef8dc7262cc354c8b2a863c6c0a9f1/components/prism-cpp.js#L1))

```js
Prism.languages.cpp = Prism.languages.extend('c', {
  // ....
})
```

And the `Prism.languages.extend` function ([prism: prism.js#L76-L81](https://github.com/PrismJS/prism/blob/5400af9eacef8dc7262cc354c8b2a863c6c0a9f1/prism.js#L76-L81)): (**See the comments I added**)

```js
extend: function (id, redef) {
  // id is 'c', but it is not added to `_.languages` yet,
  // so the variable `lang` will be undefined
  var lang = _.util.clone(_.languages[id]);

  for (var key in redef) {
   // Throw an `Cannot read property 'keyword' of undefined` Error!!
    lang[key] = redef[key];
  }

  return lang;
}
```

It throw an `Cannot read property 'keyword' of undefined` error. So it failed to load the cpp component.

### How to Fix

For `cpp`:

1. `components/prism-cpp.s` extends 'c', so we load the 'c' component first
2. `components/prism-c.s` extends 'clike', so we load the 'clike' component first
3. `components/prism-c.s` extends nothing', load it

That is: `load clike` => `load c` => `load cpp`.

**So before loading language component, we should load the extended language component first.**


But how can we know the language components dependencies? There exist a [components.js](https://github.com/PrismJS/prism/blob/5400af9eacef8dc7262cc354c8b2a863c6c0a9f1/components.js) file in prism, it has the language components dependencies, We can use it:

[The cpp part](https://github.com/PrismJS/prism/blob/5400af9eacef8dc7262cc354c8b2a863c6c0a9f1/components.js#L140-L144):
```js
languages: {
  // ...
  "cpp": {
	  "title": "C++",
	  "require": "c",
	  "owner": "zeitgeist87"
  },
  // ...
}
```

The fixes won't be hard, I'll send a pull request if you agree with the above. 🤗

**Comment by KyleAMathews** [comment]
Ooooo… prism has more layers. Nice! Would love a PR adding support for the extended language stuff!

**Comment by VincentBel** [comment]
@KyleAMathews Oops, It seem the [components.js file](https://github.com/PrismJS/prism/blob/gh-pages/components.js) is only for interval use. It doesn't have a `module.exports`.  And even the file doesn't exists in npm(<https://unpkg.com/prismjs@1.6.0/>). 😅

---

Maybe we can have a copy of the language part? (But we need to keep in sync if prism changes it)

**Comment by KyleAMathews** [comment]
Copying it in sounds fine. Could you add a make.js script that downloads the file and add the module.exports etc? That way when there is updates it'll be trivial to update the components module.

**Comment by VincentBel** [comment]
Yeah, of course.
