### ISSUE TITLE
Suggestion to replace included .prettierrc with defaults in gatsby-starter-blog-theme output

### ISSUE THREAD

**Issue by trevordmiller** [gatsbyjs/gatsby#19173]
## Summary

Currently the output of the starter blog theme includes a `.prettierrc`. I feel it would be better to remove the `.prettierrc` from the starter output so that Prettier uses its default settings or setting under the hood of Gatsby packages like the ESLint setup. For editor integration, the `prettier` binary could be included in the `devDependencies` per: https://github.com/gatsbyjs/gatsby/issues/15971#issuecomment-547139685

### Basic example

```
rm .prettierrc
npm install --save-dev prettier
```

### Motivation

To me the current `.prettierrc` in the output of the `gatsby-starter-blog-theme` feels like it is going against the philosophy of Gatsby themes:

> "Using a theme, all of your default configuration lives in an npm package...A Gatsby theme is effectively a composable Gatsby config. They provide a higher-level approach to working with Gatsby that abstracts away the complex or repetitive parts into a reusable package."

For example, other tooling config isn't included (like ESLint config). I really like this approach so that all my project's tooling is declarative - it is an implementation detail under the hood of Gatsby that I don't have to care about and that I can get "free" programmatic upgrades for by upgrading my nvm package versions. The Gatsby starter blog theme currently does this everywhere except with Prettier.

**Comment by LekoArts** [comment]
Thank you for opening this!

Your quote refers to Gatsby themes but the repository you're talking about is a starter that uses a theme. So people can just remove the prettier file if they think it's necessary - it's not shipped by default with the theme. Hope that makes sense! (If not, please comment)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
