### ISSUE TITLE
Suggestion to add gatsby-plugin-catch-links by default to gatsby-theme-blog

### ISSUE THREAD

**Issue by trevordmiller** [gatsbyjs/gatsby#19174]
## Summary

I would suggest adding [gatsby-plugin-catch-links](https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/) under the hood of `gatsby-theme-blog`. Currently I'm doing this manually with:

`gatsby-config.js`

```js
module.exports = {
  plugins: [`gatsby-theme-blog`, `gatsby-plugin-catch-links`],
  ...
};
```

### Basic example

Would be nice if this happened automatically under the hood of `gatsby-theme-blog`.

`gatsby-config.js`

```js
module.exports = {
  plugins: [`gatsby-theme-blog`],
  ...
};
```

### Motivation

It seems to me that having relative links in `.md` and `.mdx` files should use [the Gatsby SPA linking](https://www.gatsbyjs.org/docs/gatsby-link/) by default? So that relative links in markdown / mdx files use the SPA linking instead of a full page refresh like can be done in React components with `<Link>`.

**Comment by LekoArts** [comment]
cc @gatsbyjs/themes-core
