### ISSUE TITLE
Change favIcon

### ISSUE THREAD

**Issue by bersot1** [gatsbyjs/gatsby#19184]
## Description

How can i change the favicon? I already tried every way i know and don't work...

By default the theme comes with GraphQL url:

```js
"favicon": "https://graphql-engine-cdn.hasura.io/img/hasura_icon_black.svg"
```

But I no idea how i use this... someone can help me please?

I tried with image base64 but when i do push to my repo in VSTS, return a error...

**Comment by LekoArts** [comment]
Thank you for opening this!

You can place your favicon file inside the [static folder](https://www.gatsbyjs.org/docs/static-folder/) and then reference it like normal from your `<head>` or you use something like [gatsby-plugin-manifest](https://www.gatsbyjs.org/docs/add-a-manifest-file/) and its favicon option. For example if you place your favicon inside the static folder you then can access it on your like https://www.your-domain.tld/favicon.png

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
