### ISSUE TITLE
[docs][guides] new page on top errors with troubleshooting advice

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#19196]
## Summary

To support people of all skill levels building Gatsby sites, we want to add a Reference Guide with the top errors and how to fix them. This would live in the [Debugging Gatsby](https://www.gatsbyjs.org/docs/debugging/) section, and could have a title of "Common Errors and Troubleshooting" or something to that effect.

Some potential subtopics to include:

- Node/Sharp issues
- data sourcing errors
- GraphQL errors
- errors from common plugins

### Structure

A reference guide explains a Gatsby concept or technique without the step-by-step context provided by a tutorial or recipe. Refer to the [contributing docs](https://www.gatsbyjs.org/contributing/docs-templates/#reference-guides) for a reference guide template and the [Gatsby Style Guide](https://www.gatsbyjs.org/contributing/gatsby-style-guide/) for writing conventions.

### Audience

Beginner to novice developers with a limited understanding of Gatsby or GraphQL should be able to follow along with this guide to debug and try to lead them to a solution. As we say in the Style Guide, avoid jargon and assumed knowledge of terminology or extremely technical conventions.

### Motivation

To help people building Gatsby sites solve their issues, so they can move onto something else! Easier debugging means happier development usually.

### Approach

Due to how big this issue is we're going to note various stages of work that we expect to complete.
[ ] - Error messages and debugging
[ ] - Behavior errors (e.g. it works on develop and not built)
[ ] - Interactive page that allows for feedback of top bugs, a component to upvote and help us surface that most common errors and issues

**Comment by gillkyle** [comment]
Discussing this errors on the team led to some additional ideas and notes for this:

- including the full strings of errors (sort of like a GitHub issue might) will be helpful for search and SEO
- when is a `gatsby clean` necessary to clean out the internal cache?

**Comment by gillkyle** [comment]
We added this guide in #19966, I'll close now, though the ideas in original post could add some more cool functionality!
