### ISSUE TITLE
When I introduce the js of the script mode below the mackdown file, the first time I load the page render after packaging?

### ISSUE THREAD

**Issue by Fdango** [gatsbyjs/gatsby#19198]
This is my link：
`http://develop.freeaihub.com/python/%E8%AF%BE%E7%A8%8B%E7%AE%80%E4%BB%8B/`

The first time I refreshed the page, it was rendered multiple times. I don't know what happened.

**Comment by LekoArts** [comment]
Hello,

please follow our issue template and fill out every section. Please also explain your problem in more detail as I don't follow what you're asking. Thanks!
