### ISSUE TITLE
build is not working

### ISSUE THREAD

**Issue by kevohagan** [gatsbyjs/gatsby#192]
first off, great job on gatsby really loving it! 

i just tried the starter default build and the bundle and styles.css dont get referenced correctly in the index.html. No clue why..

:)

**Comment by KyleAMathews** [comment]
Could you paste in the index.html that gets built?

**Comment by kevohagan** [comment]
<!DOCTYPE html>
 <html lang="en"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1.0 maximum-scale=1.0"/><title></title><link rel="shortcut icon"/><style id="typography.js">/*! normalize.css v3.0.2 | MIT License | git.io/normalize */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:baseline}audio:not([controls]){display:none;height:0}[hidden],template{display:none}a{background-color:transparent}a:active,a:hover{outline:0}abbr[title]{border-bottom:1px dotted}b,strong{font-weight:700}dfn{font-style:italic}h1{font-size:2em;margin:.67em 0}mark{background:#ff0;color:#000}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline}sup{top:-.5em}sub{bottom:-.25em}img{border:0}svg:not(:root){overflow:hidden}figure{margin:1em 40px}hr{-moz-box-sizing:content-box;box-sizing:content-box;height:0}pre{overflow:auto}code,kbd,pre,samp{font-family:monospace,monospace;font-size:1em}button,input,optgroup,select,textarea{color:inherit;font:inherit;margin:0}button{overflow:visible}button,select{text-transform:none}button,html input[type=button],input[type=reset],input[type=submit]{-webkit-appearance:button;cursor:pointer}button[disabled],html input[disabled]{cursor:default}button::-moz-focus-inner,input::-moz-focus-inner{border:0;padding:0}input{line-height:normal}input[type=checkbox],input[type=radio]{box-sizing:border-box;padding:0}input[type=number]::-webkit-inner-spin-button,input[type=number]::-webkit-outer-spin-button{height:auto}input[type=search]{-webkit-appearance:textfield;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;box-sizing:content-box}input[type=search]::-webkit-search-cancel-button,input[type=search]::-webkit-search-decoration{-webkit-appearance:none}fieldset{border:1px solid silver;margin:0 2px;padding:.35em .625em .75em}legend{border:0;padding:0}textarea{overflow:auto}optgroup{font-weight:700}table{border-collapse:collapse;border-spacing:0}td,th{padding:0}

html {
  box-sizing: border-box;
  font-size: 112.5%;
  line-height: 1.5em;
  overflow-y: scroll;
}

*, *:before, *:after {
  box-sizing: inherit;
}

body {
  color: hsl(0,0%,20%);
  font-family: georgia, serif;
  font-weight: 300;
  word-wrap: break-word;
}

/* Make image responsive by default */
img {
  max-width: 100%;
}

h1,h2,h3,h4,h5,h6,hgroup,ul,ol,dl,dd,p,figure,pre,table,fieldset,blockquote,form,noscript,iframe,img,hr {
margin: 0;
margin-bottom: 1.5rem;
padding: 0;
}

blockquote {
margin: 1.5rem 3.75rem;
}

b,strong {
font-weight: 700
}

hr {
background: hsl(0,0%,80%);
border: none;
height: 1px;
margin-bottom: calc(1.5rem - 1px);
}

ol,ul {
list-style-position: outside;
margin-left: 1.5rem;
}

ul li,ol li {
padding-left: 0;
}

code,kbd,pre,samp {
font-size: 0.85rem;
line-height: 1.5rem;
}

table {
font-size: 1rem;
line-height: 2.25rem;
width: 100%;
}

thead {
text-align: left;
}

h1,h2,h3,h4,h5,h6 {
color: hsl(0,0%,20%);
font-family: "Avenir Next", "Helvetica Neue", "Segoe UI", Helvetica, Arial, sans-serif;
font-weight: 700;
}

h1 {
font-size: 2.82843rem;
line-height: 3.75rem;
}

h2 {
font-size: 2rem;
line-height: 2.25rem;
}

h3 {
font-size: 1.41421rem;
line-height: 2.25rem;
}

h4 {
font-size: 1.25992rem;
line-height: 1.5rem;
}

h5 {
font-size: 1.12246rem;
line-height: 1.5rem;
}

h6 {
font-size: 1rem;
line-height: 1.5rem;
}


</style><link rel="stylesheet" href="/styles.css"/></head><body><div id="react-mount"><div data-reactid=".118cxv8ny0w" data-react-checksum="-563376078"><div style="max-width:960px;margin-left:auto;margin-right:auto;padding:1.5rem 0.75rem;padding-top:0;" data-reactid=".118cxv8ny0w.0"><div data-reactid=".118cxv8ny0w.0.0"><h1 data-reactid=".118cxv8ny0w.0.0.0">Hi people</h1><div data-reactid=".118cxv8ny0w.0.0.1"><p>Welcome to your new Gatsby site.</p>
</div></div><span style="display:block;clear:both;" data-reactid=".118cxv8ny0w.0.1"> </span></div></div></div><script src="/bundle.js"></script></body></html>

**Comment by KyleAMathews** [comment]
Looks right to me. Are these all inside the `/public/` directory? If you want to test if your built site is working correctly, you'll need software to serve the files. An easy one is the npm module `http-server`. Install it with `npm install -g http-server` then run it like this: `http-server public/`. Let me know if that works.

**Comment by kevohagan** [comment]
yeah styles though referenced but not needed no? its not generated

**Comment by KyleAMathews** [comment]
There's no `styles.css` created in your public folder? It actually isn't inlined atm (though it will be in the future #145). The inlined styles you see there are from the [Typography module](https://github.com/kyleamathews/typography.js) which auto-generates the base theme.

**Comment by kevohagan** [comment]
nope no styles.css in the public folder. anyway the default starter doesn't have a styles.css right?

**Comment by KyleAMathews** [comment]
oh actually it might not :) at least in the version you're using.

It looks like you're using a slightly older version of the default starter. I pushed a bunch of changes yesterday to it to add examples of how to add css. See http://gatsbyjs.github.io/gatsby-starter-default/

Gatsby uses https://github.com/webpack/extract-text-webpack-plugin to automatically create a `styles.css` from the css files that get imported into react components.

Could you try creating a new version of the default starter and build it to see if a `styles.css` is created?

**Comment by kevohagan** [comment]
hey this works fine now! :) great job on gatsby!

**Comment by KyleAMathews** [comment]
👍😀👏
