### ISSUE TITLE
[blog-post] do you guys consider to link a blog post in the how-to section?

### ISSUE THREAD

**Issue by daniele-zurico** [gatsbyjs/gatsby#19209]
Hi guys after few days of struggling I've been able to deploy my blog on github pages with github actions and I wrote a blog post... do you consider to link it to the doc or is something that you don't use to do?
This is my blog post: https://www.dzurico.com/how-to-build-your-blog-with-gatsby-and-deploy-to-github-pages-with-github-actions/

**Comment by sidharthachatterjee** [comment]
Hey @daniele-zurico 

That's a cool write up! https://www.gatsbyjs.org/docs/awesome-gatsby-resources/ might be a good place for this?

Feel free to open a PR adding it! Closing this issue for now. 

Thank you once again 💜
