### ISSUE TITLE
[gatsby-source-wordpress] - Use plugin with Apollo Client

### ISSUE THREAD

**Issue by BlackShabat** [gatsbyjs/gatsby#19201]
I'm using gatsby-source-wordpress and except static queries want to fetch client data with ApolloClient. I need to pass graphql endpoint as "uri" param `new ApolloClient({uri: "mysite.com/graphql"})` But gatsby-source-wordpress doesn't provide such kind of URL 

Is there any way to use Apollo Client with gatsby-source-wordpress ?

**Comment by LekoArts** [comment]
Thank you for opening this!

`gatsby-source-wordpress` connects to your Wordpress' REST API endpoint and doesn't provide you with a GraphQL endpoint. You need to use https://www.wpgraphql.com/ to have a GraphQL endpoint on your Wordpress instance. You then can use that for your ApolloClient.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by BlackShabat** [comment]
Thanks, I've been using wpgraphql, but it has some limitations and gatsby-source-wordpress looks more convenient. But it seems I don't have any other choice.I need to write filter by name in posts list page. Initial data come from server. Filtered posts with client request.

I can use REST API for client data fetching with Axios for example, but I faced a problem with different response structure between GraphQL and REST. And I have to write some kind of adapter to use same component for rendering list item.

Maybe you have some idea? Sorry if it's out of the gatsby issues scope:)
