### ISSUE TITLE
Remove blocking network request when loading site from a service worker (with gatsby-plugin-offline)

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#19207]
You can see the blocking request for the page-data.json in this performance trace of reloading gatsbyjs.org

<img width="447" alt="Screenshot 2019-11-01 10 30 03" src="https://user-images.githubusercontent.com/71047/68015563-b5fa1100-fc92-11e9-865a-c5e16f2e5607.png">

We should use https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.strategies.StaleWhileRevalidate (perhaps just for this initial request) so that the site loads as fast as possible.

**Comment by sever1an** [comment]
Does `gatsby-plugin-offline` do anything to receive cache update notifications from WorkBox? If not, it might be something to consider.

When using `StaleWhileRevalidate` if the cached version exists, it is the only thing the client sees unless *a second request is made later*. The refreshed version is silently added to the cache.

**Comment by KyleAMathews** [comment]
@sever1an I think that's a fine tradeoff as assuming the page is outdated, it'll get refreshed on the next page transition.

@davidbailey00 what do you think? Was this a deliberate change to ensure data is always fresh? Given the extra latency booting the sw adds, the tradeoff is starting to get dicey vs. just always loading from the server.
