### ISSUE TITLE
scss module webpack error after migrating from create-react-app

### ISSUE THREAD

**Issue by zilahir** [gatsbyjs/gatsby#19227]
## Description

`scss` modules not working when migrating from `react-react-app` to `gatsbyjs`

### Steps to reproduce

clone [this](https://github.com/zilahir/react-landing-page/tree/gatsby-dev) repo, (branch `gatsby-dev`), 

hit `npm i` then `gatsby develop`

### Expected result

After providing the `gatsby-plugin-sass` in `gatsby-config` the build should complete. 

### Actual result

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Unexpected token (1:0)

File: src/pages/Jobs/Jobs.module.scss:1:0
```

for every `.scss` file. 

### Environment

```
 System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.8.1 - /usr/local/bin/node
    npm: 6.10.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 78.0.3904.70
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.17.7 => 2.17.7
    gatsby-plugin-manifest: ^2.2.26 => 2.2.26
    gatsby-plugin-offline: ^3.0.17 => 3.0.17
    gatsby-plugin-sass: ^2.1.20 => 2.1.20
    gatsby-source-graphql: ^2.1.21 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.7.0
```

**Comment by zilahir** [comment]
i take it back. the problem was with the regex in the `gatsby-plugin-sass` config. 

changed it to `sassRuleModulesTest` and the problem is gone.

**Comment by nsbabrah** [comment]
I tried sassRuleModulesTest: /.*\.module\.s(a|c)ss$/, no luck.
