### ISSUE TITLE
[gatsby-plugin-sharp] Error when using resize(base64: true)

### ISSUE THREAD

**Issue by troyfendall** [gatsbyjs/gatsby#19220]
## Description

When trying to use the `resize` method from `gatsby-plugin-sharp` with a parameter of `base64: true` I get the following error:

```
Errors:
  Cannot read property 'toFormatBase64' of undefined

  GraphQL request:4:7
  3 |     nodes {
  4 |       resize(width: 20, base64: true) {
    |       ^
  5 |         src
```

### Steps to reproduce

Reproduction repository: https://github.com/troyfendall/gatsby-plugin-sharp-resize-bug

Use the following query:

```
    query IndexQuery {
        allImageSharp {
            nodes {
                resize(width: 20, base64: true) {
                    src
                }
            }
        }
    }
```

### Expected result

What should happen?

A resized base64 image should be available for use and the build should succeed without error.

FWIW I traced through the `gatsby-plugin-sharp` code and found that defaulting `args = {}` on [this line](https://github.com/gatsbyjs/gatsby/blob/452ac098b5c64fd567589c7c558dab9e70b2221f/packages/gatsby-plugin-sharp/src/index.js#L142) fixed the issue. Now, I don't know if the root issue is the lack of default or if there's an underlying issue that explains why the args are undefined there. Hopefully ya'll with better knowledge of the scheduler can decipher what's going on there.

### Actual result

```
Errors:
  Cannot read property 'toFormatBase64' of undefined

  GraphQL request:4:7
  3 |     nodes {
  4 |       resize(width: 20, base64: true) {
    |       ^
  5 |         src
```

### Environment

```
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 69.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: 2.17.6 => 2.17.6
    gatsby-plugin-sharp: 2.2.36 => 2.2.36
    gatsby-source-filesystem: 2.1.35 => 2.1.35
    gatsby-transformer-sharp: 2.3.2 => 2.3.2
```

**Comment by LekoArts** [comment]
Thanks for the issue! Tagging my colleagues cc @gatsbyjs/core

**Comment by wardpeet** [comment]
@troyfendall Thanks for opening this bug! This is a simple one to fix.

The error is at this line:
https://github.com/gatsbyjs/gatsby/blob/0ebe2b4732a40c17a01a09c2ec21705acd39661c/packages/gatsby-plugin-sharp/src/index.js#L154

The fix is to change this line into
```js
async function generateBase64({ file, args = {}, reporter }) {
```

There might be something else going on but this at least fixes the error. More detective work is appreciated 🕵🕵️‍♀️.

**Comment by sidharthachatterjee** [comment]
This appears to have been fixed in https://github.com/gatsbyjs/gatsby/pull/20158 thanks to @rileymiller 

Let's close this issue. Thanks everyone!
