### ISSUE TITLE
Offline plugin "Application Cache" support for ios

### ISSUE THREAD

**Issue by chandmk** [gatsbyjs/gatsby#1923]
Current offline/manifest plugins don't seem to work with non-service worker supported browsers.  I am wondering if there is a way to include optional support for appcache manifest file.

I am thinking that this includes 

a.adding manifest attribute to html
<html manifest="<app>.appcache">

b. automatically generating<app>.appcache file

Any pointers to get there are appreciated.

updated: may be a gatsby plugin that implements web pack offline-plugin would work?

**Comment by KyleAMathews** [comment]
Using offline-plugin might be weird since we have multiple builds and I'm not sure how they handle that. But definitely a new plugin would be a good way to add appcache support.

**Comment by LekoArts** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
