### ISSUE TITLE
Expecting type "Date" on non-Date field containing 4-digit strings - too opinionated?

### ISSUE THREAD

**Issue by laradevitt** [gatsbyjs/gatsby#19239]
## Summary

I'm wondering if it might be an overreach to assume a field containing 4-digit strings is a Date field? 

I created a test repo with a super simple data source that will fail because a field containing 4-digit IDs is assumed to be a Date type. To reproduce:

```cli
gatsby new test-site https://github.com/laradevitt/temp-gatsby-type-error.git
cd test-site
gatsby develop
```

Results in:

> Variable "$nid" of type "String!" used in position expecting type "Date".

Of course there are workarounds including changing the type in the query from "String!" to "Date" (feels wrong since it isn't a date) or explicitly defining type in `createSchemaCustomization` (better, but may not be obvious as a solution). 

Or have I missed something? It's been known to happen on occasion! 🤷‍♀ 😀 

Thanks, all!

**Comment by freiksenet** [comment]
Hello! 

Thank you for creating this issue!

I agree that we accept dates very eagerly. Unfortunately we can't change this easily because that might break sites that might rely on this behavior :(  Schema customization is the recommended way to do it.

Sorry that I couldn't help more! :purple_heart:

**Comment by vladar** [comment]
Here is a link to docs on how to opt-out of inference by the way - https://www.gatsbyjs.org/docs/schema-customization/#opting-out-of-type-inference

**Comment by drdogbot7** [comment]
I was having the same issue with some JSON data and found the example in this post more useful:
https://www.gatsbyjs.com/blog/2019-03-04-new-schema-customization/

Adding this to gatsby-node.js fixed my issue.

```JS
exports.sourceNodes = ({ actions }) => {
  const { createTypes } = actions;
  const typeDefs = `
    type nameOfYourJson implements Node {
      stringThatLooksLikeADate: String
    }
  `;
  createTypes(typeDefs);
};
```
OBVIOUSLY, customize this to your own situation.

I am not entirely clear on what the difference b/w `createSchemaCustomizations` and `sourceNodes` is, and the syntax looks pretty similar, but only the latter is what worked for me. I think maybe `sourceNodes` is just a newer API.

## Note:
* You don't *need* to explicitly set types on all the other fields if they're being inferred correctly.
* The post linked above says you need to install `gatsby@schema-customization`, but I didn't have to, so this is probably in the core now. My project is on ^2.25.3.

**Comment by laradevitt** [comment]
@drdogbot7 - Thanks for sharing your solution. It's essentially the same as mine:

```js
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions;
  const typeDefs = `
    type Neighbourhood implements Node {
      neighbourhood_number: String!
    }
    type License implements Node {
      neighbourhood_id: String!
    }
  `;
  createTypes(typeDefs);
};
```

I wish I could say why `createSchemaCustomizations` didn't work for you. 🤷 Yes the schema customization API is indeed now in core.

**Comment by danharper83** [comment]
I think I'm encountering this issue but can't seem to resolve it using the above.

I'm passing a parameter into a query which is 2895, I'm going to replace this with an environment variable later once I get this working.

This doesn't work
```
`
query Parts($catalogue_id: String!)
{
  allNodePart(
    filter: {relationships: {paragraph__catalogue_item: {elemMatch: {parent_id: {eq: $catalogue_id}}}}}
  ) {
    edges {
      node {
        id
        field_sku
        field_condition
        title
        field_app_notes
        field_sku_notes
        relationships {
          field_part_group {
            name
          }
          field_k_types {
            drupal_internal__id
          }
          field_oe_referneces_1 {
            field_oe_ref
            field_oe_ref_sanitised
          }
        }
      }
    }
  }
}
`,{ catalogue_id: process.env.CATALOGUE_ID}
```
This does

```
`
{
  allNodePart(
    filter: {relationships: {paragraph__catalogue_item: {elemMatch: {parent_id: {eq: "2895"}}}}}
  ) {
    edges {
      node {
        id
        field_sku
        field_condition
        title
        field_app_notes
        field_sku_notes
        relationships {
          field_part_group {
            name
          }
          field_k_types {
            drupal_internal__id
          }
          field_oe_referneces_1 {
            field_oe_ref
            field_oe_ref_sanitised
          }
        }
      }
    }
  }
}
`
```

when I console log the env variable it prints the correct string. I'm not sure which part is causing the error.

Cheers Dan

**Comment by laradevitt** [comment]
@danharper83 Sorry I missed this. Did you resolve it? The error occurs because in the second you aren't specifying a type (`String!`), just passing in a value. To force Gatsby to treat a 4-digit integer as a string you have to explicitly define it, as in the examples above.
