### ISSUE TITLE
How to integrate Gatsby with NodeJs Express Backend

### ISSUE THREAD

**Issue by naissa12** [gatsbyjs/gatsby#19242]
I have Gatsby as my frontend and NodeJs/Express to fetch API data. I edited gatsby-config.js with the following

``````
module.exports = {
  /* Your site config here */

  proxy: {
    prefix: "/api",
    url: "http://localhost:4000",
  },
}
``````

to make this work.

It works in my development environment, but not when I run the gatsby production build. When I run the gatsby production build and go to the live production website, the nodeJS API data is not  being fetched. I'm I missing a build step.

I do

gatsby build
gatsby serve

**Comment by sever1an** [comment]
The proxy option is only supposed to work in develop.

https://www.gatsbyjs.org/docs/gatsby-config/#proxy
> Setting the proxy config option will tell the **develop server** to proxy any unknown requests to your specified server.

How to accomplish this in production will be totally dependent on where/how you are hosting the Gatsby site. 

With Netlify for example, it is just a configuration option. https://docs.netlify.com/routing/redirects/rewrites-proxies/#proxy-to-another-service

A determined AWS developer could use another origin in CloudFront or something with Lambda@Edge & CloudFront.

If the site is self-hosted, basically all web servers trivially support proxies like this with some configuration.

**Comment by sidharthachatterjee** [comment]
Can't answer this better than @sever1an already has!

Closing this for now but feel free to reopen or comment if there's anything else we can help with 🙌
