### ISSUE TITLE
styles are broken for client-only routes in production

### ISSUE THREAD

**Issue by s-kris** [gatsbyjs/gatsby#19251]
## Description

I created client only routes (/route1/:id, /route2/:id) as described [on gatsby docs](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/) in both ways - with plugin & createPage(). The styles are correctly loaded on dev for /route & /route/:id. 
But on production, the styles for /route/:id are broken

### Steps to reproduce
https://codesandbox.io/s/gatsby-starter-default-sguel
correct styles: https://csb-sguel.netlify.com/sample/
broken styles: https://csb-sguel.netlify.com/sample/11

### Expected result

/route & /route/:id should have same styles

### Actual result
styles for /route are correctly loaded
styles for /route/:id are broken

### Environment

  System:
    OS: Linux 5.2 Manjaro Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 12.9.1 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.11.2 - /usr/bin/npm
  Languages:
    Python: 3.7.4 - /usr/bin/python
  Browsers:
    Firefox: 69.0.1
  npmPackages:
    gatsby: ^2.16.1 => 2.17.7 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13 
    gatsby-plugin-sitemap: ^2.2.19 => 2.2.19 
    gatsby-plugin-styled-components: ^3.1.11 => 3.1.11 
  npmGlobalPackages:
    gatsby-cli: 2.8.5

**Comment by etamity** [comment]
I am having same problem

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by universse** [comment]
There is a similar issue #17891

**Comment by s-kris** [comment]
> Hi!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby!
Hi,

No problem. Please find the minimal reproduction here: https://codesandbox.io/s/gatsby-starter-default-sguel
correct styles: https://csb-sguel.netlify.com/sample/
broken styles: https://csb-sguel.netlify.com/sample/11

Thank you :)

**Comment by s-kris** [comment]
This is similar to https://github.com/gatsbyjs/gatsby/issues/19394 
Tried upgrading as mentioned here: https://github.com/gatsbyjs/gatsby/issues/19394#issuecomment-552244848 
The problem persists

**Comment by s-kris** [comment]
Let us assume '/sample' is the client-only route. There are two parts to fix this.
1. [Workaround](https://github.com/gatsbyjs/gatsby/issues/17891#issuecomment-548660698) for React hydration issue. 
```
export default props => {
  if (typeof window === 'undefined') return null
  return <SamplePage {...props} />
}
```

2. Nginx Config (Minimal example)
```
server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  error_page 404 /404.html;

# this is the client-only route
  location /sample { 
    try_files $uri $uri/ /sample/index.html;
  }
}

```

**Comment by alibalbars** [comment]
```
 export default props => {
 if (typeof window === 'undefined') return null
  return <SamplePage {...props} />
 }
```

I put the condition line to /pages/index.js file and it solved my css broke issue, thanks!
