### ISSUE TITLE
eslint isn't working out of the box

### ISSUE THREAD

**Issue by gyfchong** [gatsbyjs/gatsby#1925]
Hey guys,

Just started working with Gatsby, and I used the `gatsby-cli` to get started, but it doesn't look like Atom's `linter-eslint` is detecting any errors when I delete things like `const` declarations.

I've tried adding my own `eslintrc` and that seems to work, but I was wondering how a lot of the other projects' work with the linter but not mine.

On a different note, I have a few `eslint` related unmet peerdeps which require me to manually install, however they don't seem to fix the issue!
```js
warning "eslint-config-fbjs@1.1.1" has unmet peer dependency "babel-eslint@^6.1.2".
warning "eslint-config-fbjs@1.1.1" has unmet peer dependency "eslint@^3.0.0".
warning "eslint-config-fbjs@1.1.1" has unmet peer dependency "eslint-plugin-babel@^3.3.0".
warning "eslint-config-fbjs@1.1.1" has unmet peer dependency "eslint-plugin-flowtype@^2.15.0".
warning "eslint-config-fbjs@1.1.1" has unmet peer dependency "eslint-plugin-react@^5.2.2".
```

Any help would be great!

**Comment by KyleAMathews** [comment]
Closing this issue as it's fairly old and we have way too many open issues! If you have additional problems in this area, please open a new issue!
