### ISSUE TITLE
Gatsby Production Build Breaks Material-UI Styling and Loading Fonts

### ISSUE THREAD

**Issue by hhimanshu** [gatsbyjs/gatsby#19256]
## Description

The `gatsby` and `material-ui` frameworks does not seems to be working correctly together **in production mode**

I have an entire repository that reproduces this issue. You can find it at 
https://github.com/bonsaiilabs/gatsby-material-ui-embed-custom-font/tree/repro

I have additionally created a [video](https://imgur.com/GIozKfj) that explains the issue

This is a blocker since I cannot deploy my changes to production. Any help is greatly appreciated

### Steps to reproduce

```sh
git clone --single-branch --branch repro https://github.com/bonsaiilabs/gatsby-material-ui-embed-custom-font
cd gatsby-material-ui-embed-custom-font

yarn && gatsby build
gatsby serve
```
Go to http://localhost:9000

- Observe that the page has issues as font is not loaded and the material-ui styling is not applied on the `AppBar`. You can also find this in this [video](https://imgur.com/GIozKfj)
- Click on `Page1` or `Page2` and this will load the fonts and the styling correctly
- Go to the home http://localhost:9000 and you will see the rubik font and material-UI styling being applied correctly
- Refresh the page and you are back on step 0, where the page did not load the fonts and the styling is broken

This complete [video](https://imgur.com/GIozKfj) shows every part in detail.

P.S.
- As I understand from Gatsby [documentation](https://www.gatsbyjs.org/docs/what-you-dont-need-plugins-for/), we do not need to use plugin to use Material-UI. This is what you would see in the codebase where the issue is reproducible.  
- However, I also tried [gatsby-plugin-material-ui](https://www.gatsbyjs.org/packages/gatsby-plugin-material-ui/?=material) and the issue still persists.

### Expected result

The styling and fonts should have worked normally

### Actual result

The *production* application breaks when served using `gatsby serve` or deployed on `firebase`

### Environment

```sh

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v11.14.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.70
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.73 => 2.13.73
    gatsby-image: ^2.2.10 => 2.2.10
    gatsby-plugin-manifest: ^2.2.6 => 2.2.6
    gatsby-plugin-offline: ^2.2.7 => 2.2.7
    gatsby-plugin-react-helmet: ^3.1.4 => 3.1.4
    gatsby-plugin-sharp: ^2.2.13 => 2.2.13
    gatsby-source-filesystem: ^2.1.11 => 2.1.11
    gatsby-transformer-sharp: ^2.2.7 => 2.2.7
  npmGlobalPackages:
    gatsby-cli: 2.7.30
```

**Comment by laradevitt** [comment]
I took a quick look but sadly I'm not that familiar with material-ui.

Have you seen these threads? 
https://github.com/gatsbyjs/gatsby/issues/9911
https://github.com/gatsbyjs/gatsby/issues/9121

Not sure if it offers up a clue, but the styles will appear on initial page load for the main content if I remove the material-ui components in header.js (or just remove the header component from layout.js altogether).

**Comment by LekoArts** [comment]
Thank you for opening this!

Please review the linked issues and add `gatsby-plugin-material-ui` to your project. If that doesn't help you can follow this high-level issue: https://github.com/gatsbyjs/gatsby/issues/17914

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by hhimanshu** [comment]
The real issue is at https://github.com/gatsbyjs/gatsby/pull/19277. No actions needed here, thanks

**Comment by kpennell** [comment]
any luck @hhimanshu ?

**Comment by hhimanshu** [comment]
@kpennell, yes, https://github.com/mui-org/material-ui/issues/18197 helped me

**Comment by mghazanfar** [comment]
> Thank you for opening this!
> 
> Please review the linked issues and add `gatsby-plugin-material-ui` to your project. If that doesn't help you can follow this high-level issue: #17914
> 
> We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

Worked for me. Thanks @LekoArts

**Comment by nickgrealy** [comment]
The solution for me - copy `gatsby-browser.tsx` to `gatsby-ssr.tsx`.
