### ISSUE TITLE
Add link checker for Gatsby Docs

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#19267]
## Summary

There is a plugin for a remark Link check: https://www.gatsbyjs.org/packages/gatsby-remark-check-links/

Can this also work on the Gatsby docs/Blog?

Or as a PR check?

*new edit:*

### Ideas

- check local links
  - add a linter to check before it is submitted
    - check if it has a local domain name (A lint rule is WIP)
    - check if local domains begin with a `.`, `..` or `/`
  - allow local domain and remove local domain on build time with a transformer

- check local anchors
  - with a linter and analyse each linked file?
  - on `gatsby develop`/`gatsby build` via a graphql query to query all headers?

- check internal links for trailing slashes (because breadcrumbs and selected sidebar is depend on it)
  - check with linter

- check external links
  - HEAD request
  - with blc (broken link checker)

- check internal link files (like `doc-links.yml`, `redirects.yml`)
  - with a link checker script (like site showcase validator)

### possible tools
- https://gatsbyjs.org/packages/gatsby-remark-check-links
- https://github.com/davidtheclark/remark-lint-no-dead-urls/
- https://npmjs.com/package/mdx-link-checker 
   - no repo: but source @ unpkg: 
     - https://unpkg.com/mdx-link-checker 
     - hightlighted: https://unpkg.com/browse/mdx-link-checker@0.1.1/index.js)
- https://github.com/remarkjs/remark-validate-links
  - Test: it finds some links, but just now it only checks the:
	- relative links (like `[abc](docs/wronglink)` but they have to be `[abc](docs/rightlink.md)`
    - but not find absolute paths like:
      - `[abc](/docs/wronglink)`
      - `[abc](https://www.gatsbyjs.org/docs/wronglink)`
  - maybe i have to tweak settings...
- https://github.com/zslabs/remark-relative-links -> transformer to remove domains, but can only used if we use remark instead off prettier

**Comment by muescha** [comment]
any opinion about this?

as seen in the linked issues there some places where 404 exists without any notification when a PR is done...

**Comment by muescha** [comment]
closing #18908 as duplicate of this Issue. 
copy some comments from duplicate


> ## Summary
> It would be nice to have some link check on the gatsbyjs.org site maybe as validator while an PR or better also on `gatsby develop` to find old broken links
> 
> ### Caveeats
> I know we can not find and check all links because some are generated from sourced data.
> 
> ### Motivation
> During Hacktoberfest I see also some broken links reported. Example #18905
> 
> It would be nice to avoid broken links from beginning.
> 
> ### note
> I don't mean the broken links reported for viewing files on github

_Originally posted by @lannonbr in
https://github.com/gatsbyjs/gatsby/issues/18908#issue-510606085_


> Maybe putting something like [Hyperlink](https://github.com/Munter/hyperlink) into a GitHub Action could be a good solution to this so it would run similar to how the site showcase validator works right now.

_Originally posted by @lannonbr in https://github.com/gatsbyjs/gatsby/issues/18908#issuecomment-544929178_

**Comment by muescha** [comment]
it should also check the anchor links to headers

**Comment by muescha** [comment]
there should also an internal anchor link checker for headings.

see:
#21061 `fix (www) additional links to "install nodejs"`
#20762 `fix(www) - Fix anchor link in tutorial sidebar `

**Comment by muescha** [comment]
#22461 `update link to json section`

**Comment by muescha** [comment]
the checker should also check if all pages are in the TOC files for the sections. for example in `www/src/data/sidebars/doc-links.yaml`

related issue:
- #22923 `fix(docs): Adding a Redux Store to TOC`

**Comment by marcysutton** [comment]
> the checker should also check if all pages are in the TOC files for the sections. for example in www/src/data/sidebars/doc-links.yaml

I don't think this needs to be part of it, since there could be times when we don't want to list a page in the TOC (for example, if it's linked elsewhere and not meant to be a highly prioritized page). 

I found these two potential packages:
- https://www.gatsbyjs.org/packages/gatsby-remark-check-links/
- https://www.npmjs.com/package/mdx-link-checker

I've also tagged this issue with `topic: website`, since it could be added as part of the website redesign project.

**Comment by muescha** [comment]
link checker should also check if internal links are having trainling slashes because breadcrumbs and selected sidebar is depend on it:

-  #20767 `[docs] Breadcrumb shouldn't be dependent on trailing slash`

**Comment by muescha** [comment]
#25469 `Docs links that start with docs/ rather than /docs/`

**Comment by muescha** [comment]
Not stale

**Comment by karlhorky** [comment]
FYI for root-relative links with `remark-validate-links` I have opened an issue for that here: https://github.com/remarkjs/remark-validate-links/issues/57

**Comment by karlhorky** [comment]
@muescha ok if you want to try it out, here it is:

npm: https://www.npmjs.com/package/mdx-local-link-checker
Source: https://github.com/upleveled/mdx-local-link-checker

**Comment by karlhorky** [comment]
Not stale

**Comment by karlhorky** [comment]
Not stale

**Comment by muescha** [comment]
Not stale
