### ISSUE TITLE
How to include react-map-gl in Gatsby

### ISSUE THREAD

**Issue by arhoy** [gatsbyjs/gatsby#19263]
I am looking to see how I can include this library in a gatsby app.
I have it working in development but the mapbox is not loading in production, with the issue being No Token Warning.

If anyone has any experience including a mapbox map inside Gatsby I can help me out, it would be greatly appreciated.

I have added the environment variable to Netlify like usual. 

My repo where I am using MapBox is : https://github.com/arhoy/fashion-two

I was not able to find any mapbox related plugin in Gatsby currently

**Comment by muescha** [comment]
This starter is also using map-gl:

https://github.com/gatsbyjs/gatsby/pull/19250

**Comment by arhoy** [comment]
@Michael it also has a no token warning issue on there demo page :)

**Comment by muescha** [comment]
ok :(

**Comment by LekoArts** [comment]
Thank you for opening this!

Please have a look at issues like https://github.com/gatsbyjs/gatsby/issues/6667 or this starter: https://github.com/brendan-ward/gatsby-starter-mapbox
You can also consult our documentation about debugging the build: https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by muescha** [comment]
and if you find a solution how you fixed your issue it would be nice to see your solution

**Comment by arhoy** [comment]
I figured out the issue, The only thing I changed was how i named the env variable inside Netlify.
Must be prefixed with GATSBY which is kinda strange. I don't always do this for all environment variables but maybe I will start to.
ie GATSBY_MAPBOX_API_TOKEN=<your api key from mapbox>

**Comment by muescha** [comment]
Thx. In your code or in netlify settings. 

is it described here: https://www.gatsbyjs.org/docs/environment-variables/ ?

Or here: https://www.gatsbyjs.org/docs/deploying-to-netlify/ ?

Or is there something missing so An PR can improve the docs?

**Comment by arhoy** [comment]
Interesting, Thanks for this.
