### ISSUE TITLE
Limit past community event listings

### ISSUE THREAD

**Issue by caitlinthefirst** [gatsbyjs/gatsby#19260]
Our community event listing page currently seems to list all past events. Can we limit it to only showing events from the past 3-6 months? 

If we want _all_ the events saved somewhere public, maybe we can add an archive page? 

  - Live page: https://www.gatsbyjs.org/contributing/events/c
  - GitHub page: https://github.com/gatsbyjs/gatsby/blob/master/www/src/pages/contributing/events.js

**Comment by marcysutton** [comment]
Glad this is tagged with `topic: website`, I think it should be done as part of the site redesign. I'll leave it open for the team working on that to find amongst the other website-related issues.
