### ISSUE TITLE
Read markdonw files from git history

### ISSUE THREAD

**Issue by Tenseiga** [gatsbyjs/gatsby#19266]
Hi Team, 
Is there a way to list commits history for a branch and then read the md files in each commit history. 
Say My team is noting down alll the chnages in a MD file for each commit. So I want to read the md file by providing a list of commits and reading the MD files.

**Comment by LekoArts** [comment]
Thank you for opening this!

I'd recommend reading GitHub's [API docs](https://developer.github.com/v3/repos/commits/) or reaching out to them as this isn't related to Gatsby.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
