### ISSUE TITLE
Combine different repos in the same domain, is it possible?

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#19279]
If I have 3 gatsby sites in a different github repo each one, I could build each one and then upload their `public` folders to have something like this

www.mydomain.com >>> first site
www.mydomain.com/site2 >>> second site
www.mydomain.com/site3 >>> third site

Perhaps I'd need to change the prefix path as shown here https://www.gatsbyjs.org/docs/path-prefix/

**But can this be done on a continuous deployment manner (e.g. in Netlify)?**

**Comment by kuworking** [comment]
Should work out of gatsby responsability, as explained in the link below for netlify, so I close the question (but still, this would be like doing the opposite of composing several gatsby-themes, perhaps of interest?)

https://community.netlify.com/t/common-issue-can-i-deploy-multiple-repositories-in-a-single-site/179

**Comment by mostafachatillon** [comment]
@kuworking yes, it looks much simpler than composing several themes (I got stuck here: https://github.com/gatsbyjs/gatsby/issues/21512), thanks for sharing a non-gatsby alternative
