### ISSUE TITLE
[docs] Add a "Last updated" date to reference in docs (reference guides, recipes, tutorials)

### ISSUE THREAD

**Issue by thomaswang** [gatsbyjs/gatsby#19272]
## Description

Related to https://github.com/gatsbyjs/gatsby/pull/19222, an incorrect date of Feb 9, 2011 appears in Google SERP in the [tutorial "Building a Theme"](https://www.gatsbyjs.org/tutorial/building-a-theme/). 

![image](https://user-images.githubusercontent.com/41944255/68194771-7b31fa80-ff6a-11e9-9c13-d26e0b226c02.png)

### Goal 
To prevent issues like this from happening and to convey transparency on the maintenance of the docs, It may be worth to add a "Last updated" date for docs pages and make it dynamically pull from git.

**Comment by gillkyle** [comment]
Found this issue that seems related: https://github.com/gatsbyjs/gatsby/issues/9785

This PR is also implementing similar functionality: https://github.com/gatsbyjs/gatsby/pull/19391
