### ISSUE TITLE
Gatsbygram returns 404

### ISSUE THREAD

**Issue by hashimwarren** [gatsbyjs/gatsby#19283]
## Description

The example site, Gatsbygram returns a 404 status

### Steps to reproduce

Visit https://gatsbygram.gatsbyjs.org/

The page will display a "Not Found" message

### Expected result

I expected to see the Gatsbygram example website

### Actual result

The site returned a 404 status

### Environment

n/a

**Comment by m-allanson** [comment]
I deleted the site 🤦‍♂ 

Now it should be fixed 😅
