### ISSUE TITLE
How do i add a line break in a value in a JSON file?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#19289]
I want to add a line break to a piece of JSON, but can't figure out how to make it work...

Anyway way to do this so that the transformer understands it?

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll need to add the line breaks manually `\n` and then parse the response you get from GraphQL. I'd recommend consulting a Google search for that.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
