### ISSUE TITLE
add Guidelist header to Table of Contents

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#19291]
## Problem

As described in this PR comment: https://github.com/gatsbyjs/gatsby/pull/19214/files#r342771110 the Guidelist gets "swallowed" up in Reference Guide articles that have a lot of content because it's not included in the Table of Contents (like the proposed changes in that PR or like this example: https://www.gatsbyjs.org/docs/mdx/)

In pages like this one:

![image](https://user-images.githubusercontent.com/21114044/68254755-ac511000-ffe8-11e9-8ff6-da3e0c5ae06a.png)

There should be a way to link to this "In this section" content from the Table of Contents:

![image](https://user-images.githubusercontent.com/21114044/68254853-ed492480-ffe8-11e9-8840-3e9871eb539a.png)

## What changes should be made

The exact nature of what should be changed to make this work is unclear. I haven't done much digging but possible avenues for fixing this could be:

- Adding the ability to pass something into the Table of Contents component somewhere
- Detecting if the Guidelist is on a page in the docs-template and adding the header to the ToC
- Digging into how `gatsby-plugin-mdx` creates the tableOfContents and seeing if inline components can be included as a part at build time

Researching a good solution and then implementing it would help several of those pages where the ToC is harder to see.

**Comment by muescha** [comment]
But if there is just a sport teaser on an "index page" then double guidelists are a way to much. 


How about as workaround:
- add the guidelist component twice (at beginning and at the end)
- add a header before the guidelist, then this is available in TOC
