### ISSUE TITLE
No response in gatsby develop when changing the path in onCreatePage

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#19295]
When I generate pages from `.js` files (in `pages` folder), in order to remove the trailing slash I'm doing this in `gatsby-node.js`

```js
const replacePath = _path => (_path === `/` ? _path : _path.replace(/\/$/, ``))

exports.onCreatePage = ({ page, actions }, themeOptions) => {
  const { createPage, deletePage } = actions

  const newPage = Object.assign({}, page)
  newPage.path = replacePath(newPage.path)

  console.log(newPage.path) 
  /* /me, /404, etc */

  newPage.context = { pre_path: `${basePath}` }
  deletePage(page)
  createPage(newPage)
}
```

And it works as expected

Now I am trying to create the page with a different path in order to add a `pre_path` there

so that instead of `/me` I want to generate `/extra-path/me`

To do this I'm doing the following

```js
const { urlResolve } = require(`gatsby-core-utils`)
const replacePath = _path => (_path === `/` ? _path : _path.replace(/\/$/, ``))

exports.onCreatePage = async ({ page, actions }, themeOptions) => {
  const { basePath } = withDefaults(themeOptions)
  const { createPage, deletePage } = actions

  const newPage = Object.assign({}, page)
  newPage.path = urlResolve(replacePath(basePath), replacePath(newPage.path))

  console.log(newPage.path)
  /* /newpath/me, /newpath/404, etc */

  newPage.context = { pre_path: `${basePath}` }
  deletePage(page)
  createPage(newPage)
}
```

And when I'm doing `gatsby develop`, compilation goes well, __but__ when I go to `localhost:8000` the web doesn't respond, no error message, just a Chrome message after a while asking whether I want to kill the tab or wait

The same if I test any other page (that I know should be there), gatsby simply doesn't respond to anything (neither the `http://localhost:8000/___graphql`)

So, I'll try to make a small repo to see if I can reproduce the error there

But before I wanted to ask whether I am doing something wrong here (?)

 "gatsby": "^2.13.70",
 "react": "^16.9.0",
 "react-dom": "^16.9.0"

------------

Apparently I can fix it __if__ I don't `deletePage()`, so that I end up with two copies of the same page with different paths (but I can navigate as expected)

I don't get why is this happening ...

**Comment by LekoArts** [comment]
Have you looked at how the plugin does it? https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-remove-trailing-slashes/src/gatsby-node.js

Also:
Do you want that path everywhere? If yes, you should use the `pathPrefix`. You can also place the pages inside a folder to get a prefix.
Lastly you could have a look at how I do it on my site: https://github.com/LekoArts/portfolio/blob/8577b5da43b1f06a0ed00f04e6d671e4fda6e595/gatsby-node.js#L72-L102

**Comment by kuworking** [comment]
Yes, I have, and I have no problems in removing the slashes (using their strategy), but that's it, if I change the path then it kind of stops working

I'd need to generate a simple repo and try the same thing to see things clearer

---------------------

That said, yes, I probably should use pathPrefix, but it's like there are two approaches in doing this, one is pathPrefix and the other is programatically, sort of

E.g. like it is done in the official theme-blog with the options that the user throws

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-theme-blog-core/gatsby-node.js#L101

I've preferred to use this second way, it looks like it is simpler, but then I've found what I'm saying here

---------------------

Looking at your code, it is like when you do this

```
`${locales[lang].path}${page.path}`
```

you are changing the path, so in my hands this would break gatsby

Since it doesn't happen to you, it is one of those obfuscated problems I like so much

Does this `${locales[lang].path}` involve any structure with slashes? If you confirm that you are here doing a transformation like from `/my-page` to `/english/my-page` then it definitively does work

**Comment by kuworking** [comment]
@LekoArts I've found it :D

Your line

```js
  if (page.path.includes('404')) {
    return
  }
```

made me think, with the fact that I was breaking gatsby if I was not creating the pages that I was deleting before, except if I was only removing the slash

So, if I include this line, everything works

My assumption is that gatsby needs one of these two pages with the path intact

![image](https://user-images.githubusercontent.com/4474004/68381824-c9095700-0152-11ea-9cd8-402fa71e1e83.png)

- If I don't delete them, everything runs smothly

- If I delete them (and substitute them by versions located in folders, such as `/blog/404`), then gatsby collapses (Chrome becomes unresponsive until it snaps)

Does it make sense?
