### ISSUE TITLE
Error: RelayParser

### ISSUE THREAD

**Issue by bersot1** [gatsbyjs/gatsby#19307]
## Description

`Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents: dA1SSrcTemplatesDocsJs3677288088`

this error appear when I make the push to my VSTS. I don't know what is wrong... because my alterations was only em text in the post (content folder).

https://github.com/bersot1/blogWFM <-- code of my blog

### Environment
  System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1038.0
  npmPackages:
    gatsby: ^2.15.28 => 2.15.28
    gatsby-image: ^2.2.24 => 2.2.24
    gatsby-link: ^2.2.17 => 2.2.17
    gatsby-plugin-algolia: ^0.3.4 => 0.3.4
    gatsby-plugin-emotion: ^4.1.9 => 4.1.9
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6
    gatsby-plugin-feed: ^2.3.16 => 2.3.16
    gatsby-plugin-gtag: ^1.0.11 => 1.0.11
    gatsby-plugin-layout: ^1.1.10 => 1.1.10
    gatsby-plugin-mdx: ^1.0.46 => 1.0.46
    gatsby-plugin-react-helmet: ^3.1.11 => 3.1.11
    gatsby-plugin-remove-trailing-slashes: ^2.1.9 => 2.1.9
    gatsby-plugin-sharp: ^2.2.28 => 2.2.28
    gatsby-plugin-sitemap: ^2.2.16 => 2.2.16
    gatsby-plugin-styled-components: ^3.1.8 => 3.1.8
    gatsby-remark-copy-linked-files: ^2.1.23 => 2.1.23
    gatsby-remark-embed-markdown: 0.0.4 => 0.0.4
    gatsby-remark-embed-snippet: ^4.1.11 => 4.1.11
    gatsby-remark-images: ^3.1.25 => 3.1.25
    gatsby-remark-prismjs: ^3.3.18 => 3.3.18
    gatsby-source-filesystem: ^2.1.29 => 2.1.29
    gatsby-transformer-remark: ^2.6.28 => 2.6.28
    gatsby-transformer-sharp: ^2.2.20 => 2.2.20

**Comment by pjeziorowski** [comment]
Could you provide the steps to reproduce this?

I can't reproduce this error after cloning gatsby-gitbook-starter and replacing content files. Everything works fine for me.

Also, I see you changed package.json (I got npm ERR! Invalid name: "Lucas Bersot Marinho" after trying to 'npm install' your repo)

It would be easier to reproduce if we saw all the changes you made.

**Comment by bersot1** [comment]
So, whats going on, this blog is private, because of that I took the posts (content files) and other company identification...

I'm sure that the problem is not in content... I upgraded the package.json, maybe NPM i will work now...

Step by step:
- clone the repo (vsts)
- edit my post
- git status / git add / git cz / git push
- error: 

```js
Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
- dA1SSrcTemplatesDocsJs3677288088

See our docs page for more info on this error: https://gatsby.dev/issue-how-to
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Company name@0.0.1 build: `gatsby build --prefix-paths`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Company name@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2019-11-06T12_17_34_432Z-debug.log

> Company name@0.0.1 build d:\a\1\s
> gatsby build --prefix-paths

success open and validate gatsby-configs — 0.095
success load plugins — 2.112
success onPreInit — 0.052
success delete html and css files from previous builds — 0.143
success initialize cache — 0.050
success copy gatsby files — 0.128
success onPreBootstrap — 0.073
success source and transform nodes — 7.555
success Add explicit types — 0.093
success Add inferred types — 0.262
success Processing types — 0.172
success building schema — 0.637
success createPages — 2.598
success createPagesStatefully — 0.599
success onPreExtractQueries — 0.310
success update schema — 0.095
Found npm debug log, make sure the path matches with the one in npm's output: C:\npm\cache\_logs\2019-11-06T12_17_34_432Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Company name@0.0.1~prebuild: Company name@0.0.1
6 info lifecycle Company name@0.0.1~build: Company name@0.0.1
7 verbose lifecycle Company name@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle Company name@0.0.1~build: PATH: C:\Program Files\;C:\..................................... 9 verbose lifecycle Company name@0.0.1~build: CWD: d:\a\1\s
10 silly lifecycle Company name@0.0.1~build: Args: [ '/d /s /c', 'gatsby build --prefix-paths' ]
11 silly lifecycle Company name@0.0.1~build: Returned: code: 1  signal: null
12 info lifecycle Company name@0.0.1~build: Failed to exec build script
13 verbose stack Error: Company name@0.0.1 build: `gatsby build --prefix-paths`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid Company name@0.0.1
15 verbose cwd d:\a\1\s
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error Company name@0.0.1 build: `gatsby build --prefix-paths`
22 error Exit status 1
23 error Failed at the Company name@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ] ```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
