### ISSUE TITLE
Why does my query result not get passed to my component?

### ISSUE THREAD

**Issue by Knaackee** [gatsbyjs/gatsby#19300]
I have a page template inside `src/templates`. The query runs (if I change something I get an error). But the data does not get passed to the component.

What I am missing here?

```
export default ({ data }) => {
  // data is undefined
}

export const pageQuery = graphql`
  query($id: String!) {
    site {
      siteMetadata {
        title
      }
    }
    mdx(fields: { id: { eq: $id } }) {
      fields {
        id
        title
        slug
      }
      body
    }
    allMdx {
      edges {
        node {
          fields {
            slug
            title
          }
        }
      }
    }
  }
`
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Knaackee** [comment]
Thanks! 

I've noticed the following below but ive used queries in templates before. 
My repo with this issue is now public at https://github.com/Knaackee/testtest

Thank you very much!

```
warn The GraphQL query in the non-page component "/Users/dknaack/Projects/temp/testtest/src/templates/BlogPostTemplate.tsx" will not be run.
warn The GraphQL query in the non-page component "/Users/dknaack/Projects/temp/testtest/src/templates/PageTemplate.tsx" will not be run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — http://graphql.org/learn/queries/#fragments
```

**Comment by LekoArts** [comment]
Why are you not running the `createPages`? https://github.com/Knaackee/testtest/blob/fcd9218c0a1c2737e7b6849fd0dafd8ad1a96168/gatsby-node.js#L4-L47

The queries in the template only will get the necessary variables if you run that.

**Comment by Knaackee** [comment]
I do this because `gatsby-plugin-mdx`does create the pages. But even with the `createPages`. It does not work. I've pushed the changes to the repo.

Thank you very much!

**Comment by Knaackee** [comment]
I looked at `gatsby-starter-blog-mdx` which does pageQueries inside the templates folder too but can't tell why my version isn't working.

**Comment by Knaackee** [comment]
Solved. 
The problem was that `gatsby-plugin-mdx` creates pages and `createPage` does the same.
@LekoArts You can close this.
