### ISSUE TITLE
setFieldsOnGraphQLNodeType does not add fields as input arguments

### ISSUE THREAD

**Issue by Zalastax** [gatsbyjs/gatsby#1931]
When I call `setFieldsOnGraphQLNodeType` I expect to be able to use those fields in my GraphQL queries to filter documents just as if the field was included in the original type. I guess it's possible to use `createNodeField` instead, as that can be used as an input field, but it doesn't feel as clean.
 Input fields /arguments are inferred at https://github.com/gatsbyjs/gatsby/blob/524ff171cd890b79ce9535d6dc10550c70365d33/packages/gatsby/src/schema/build-node-types.js#L140 and we can see that fields from plugins are not included.

**Comment by KyleAMathews** [comment]
`setFieldsOnGraphQLNodeType` lets you add raw GraphQL fields. I suppose there could be code added to the infer input type step which takes the type of user added graphql fields and uses that to construct input fields.

Sounds like a lot of work though :-)

Why not just add node fields?

**Comment by Zalastax** [comment]
I ended using node fields, which works, but it doesn't feel right. The problem with how it works now is that some fields are special for no apparent reason, which is unintuitive. As a user of the graphql API I got confused by why some fields in markdownRemark were filterable, while others were not (I use the remark transformer plugin).  

In an API sense (don't think about how they work but what their goal is), why does both `setFieldsOnGraphQLNodeType` and `createNodeField` exist? Is `createNodeField` for adding meta-data ad hoc and `setFieldsOnGraphQLNodeType` for permanent fields?

If you agree to make `setFieldsOnGraphQLNodeType` add input fields I should be able to write the code and leave a pull request.

**Comment by KyleAMathews** [comment]
`setFieldsOnGraphQLNodeType` is for adding "graphql" fields which can include lots of things beyond straight code/data e.g. they can accept arguments, set defaults, etc.

If you can figure out how to reliably create input fields from `setFieldsOnGraphQLNodeType` that'd be great!

**Comment by KyleAMathews** [comment]
I definitely agree it's not intuitive right now on why some fields are filterable and others aren't.

**Comment by dfrench1** [comment]
@KyleAMathews how do i use:
 const { GraphQLString } = require("gatsby/graphql") within version 1, not an option to upgrade to v2 yet and there is no equivalent syntax in the docs.
I have tried const { GraphQLString } = require("gatsby").graphql
but this does not work, any help would be appreciated, thanks
