### ISSUE TITLE
Replace Tokens in Content Before Rendering

### ISSUE THREAD

**Issue by sumachaa** [gatsbyjs/gatsby#19319]
Building a gatsby site. 
Content is fetched from an external CMS system, have created a plugin to import the content from the external source

In `gatsby-node.js` we use `sourceNodes()` and `actions.createNode()` to create and export nodes. Sample code shown below
```
exports.sourceNodes = ({ actions, createNodeId, createContentDigest }) => {
  // Fetch data from External source & create the node .
  const node = {
    
  }

  // Create node
  actions.createNode(node);
};
```

the content in the external CMS system is created using tokens within the content. Say one example is given below
```
<div>
  <h2>This is page title</h2>
  <p>some content content...</p>
  [api-token:["content-id"]]
  [api-token:["grpah.jpg"]]
</div>
```
These token are used to place image, files, embed other content etc.

We have created pages using `exports.createPages`. But when viewing the page in the browser we see that the tokens are displayed as is.

What we are looking for is to see if there are any methods available in Gatsby to replace these tokens before the content is displayed in the browser; (say the current website builder tool uses render functions replace these tokens before its displayed on the browser) 

OR 

Do we have to replace these tokens during the `exports.sourceNodes` where export nodes are created.

**Comment by LekoArts** [comment]
Hi. Thanks for using Gatsby! Can you please explain your problem in more detail, possibly with code snippets or your repository? I don't follow what you mean.

**Comment by sumachaa** [comment]
@LekoArts updated the query again, please let me know if its clear now

**Comment by wardpeet** [comment]
hey @sumachaa,

It's not simple to convert shortcodes to something workable in gatsby. You'll have to convert these nodes into markdown nodes or MDX nodes. Like I said it's not easy and not straight forward at the moment. You're best bet is to look at https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/ or https://www.gatsbyjs.org/packages/gatsby-transformer-remark/

**Comment by nerdess** [comment]
so do i understand this right: shortcodes/tokens are only supported in markdown/mdx nodes but not inside plain HTML right now?

this is kind of a bummer because what would be a smart way to enrich html content coming from a headless cms?
