### ISSUE TITLE
gatsby-theme-blog code line highlighting

### ISSUE THREAD

**Issue by pjeziorowski** [gatsbyjs/gatsby#19310]
## Summary
Any suggestions how to add specific code lines highlighting using gatsby-theme-blog?

I guess this is a common requirement in most IT-related blogs but I haven't found any satisfying solution. 

I see the theme uses prism-react-renderer underneath and the only solution to add line highlighting is digging in code https://github.com/FormidableLabs/prism-react-renderer/issues/26#issuecomment-474678595

**Comment by LekoArts** [comment]
Thank you for opening this!

The theme uses Theme UI's Prism highlighting: https://theme-ui.com/guides/syntax-highlighting

You could e.g. follow this issue to see how or when this would be possible:
https://github.com/system-ui/theme-ui/issues/212

In the meantime you could switch to prism-react-renderer or gatsby-remark-prismjs (the latter definitely has that feature).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
