### ISSUE TITLE
Can't get pathPrefix or assetPrefix to work on static html files

### ISSUE THREAD

**Issue by kmcaloon** [gatsbyjs/gatsby#19337]
Maybe this is a very specific use case, but there might be others that could call for something like this. I am serving a gatsby page behind a reverse proxy, so all of the actual files are fetched from a different domain. Now using `assetPrefix` with an absolute url `//otherdomain.com` works for everything other than the prerendered html file, so I have to wait until the page rehydrates to see anything. The static html is using the proxied url and results in a 404. Does gatsby not have a way to customize he actual prefix/url of the prerendered html pages?

**Comment by odinho** [comment]
:scream: 

I have the same issue. I don't think that's a strange issue at all. The images are on the CDN, not on the main page, and this breaks it. It actually never loads for me.

The reason is that the script's also don't take assetprefix into account: `<script src="/styles-91d11edb97723d57091d.js" async=""></script>`. Maybe it's not seen as an asset, but that's how it is for me. We only serve the HTML files, the rest is on cloudfront.

**Comment by kmcaloon** [comment]
Thanks @odinho, you are serving you app behind a proxy and it is loading the prerendered HTML? I definitely have your two recommendations in place.

**Comment by odinho** [comment]
> Thanks @odinho, you are serving your app behind a proxy and it is loading the prerendered HTML? I definitely have your two recommendations in place.

Yes we are. I can't make `gatsby develop` work in our dev setup sadly, so I have made a listener that looks for changed files, and will re-run `gatsby build` based on that. There's also major problems when two gatsby's try to work on the same files, that's a real problem if you forget you're running the full-dev-stack in the background and want to have the faster `gatsby develop` for a fix.

But `gatsby build` is for us doing as it needs. Though I'm unsure what you mean about the "HTML".

```
$ grep -i prefix gatsby-config.js 
    assetPrefix: "https://yo-its-a-test.com/",

$ gatsby build --prefix-path
 ... snip ...

$ html-beautify public/index.html | grep webpack
    <link as="script" rel="preload" href="https://yo-its-a-test.com/webpack-runtime-141f057652110d5b9792.js" />
    <script src="https://yo-its-a-test.com/webpack-runtime-141f057652110d5b9792.js" async=""></script>

$ html-beautify public/index.html | grep "About us"
                                <li class="index--navItem--OWy2G"><a class="index--navItemLink--34g0L theme--themedComponent--O9Y4l index--AnchorLink--14Ys5" href="/information/about-us/">About us</a></li>
```

As you can see, this doesn't influence the actual links. However, we don't really want that. Also, we're not currently using `<Link>` from gatsby, so I'm sure even if we set `pathPrefix` and not `assetPrefix`, we'd still not get the prefix in there. But we actually have our own Javascript-code that already does this, so I could set another env var that would make all the `/information` urls be at a different URL.

However, not needing such special urls for each "part of the application" is the reason we started using the proxy in the first place, so everything can be at `/` on the same domain with https just like in production :)

Hope this helps, or you can show with code what you're talking about. Here's a test with pathPrefix too:

```
$ gatsby new testproject

# add this to gatsby-config.js:
#     assetPrefix: "https://asset-prefix.com/",                                                                                                                
#    pathPrefix: "https://path-prefix.com/",  

$ gatsby build --prefix-paths

$ html-beautify public/index.html  | grep "page-2/"
                    </div><a href="/path-prefix/page-2/">Go to page 2</a>

# so it works, but only with relative paths (which should be okay?), why would the files not
# be at the same place?

# Sadly, it also messes up the assetPrefix though, so you'd have to work around that:

$ html-beautify public/index.html  | grep "webpack"
    <link as="script" rel="preload" href="https://asset-prefix.com/path-prefix/webpack-runtime-ca7797724c44da2c1f54.js" />
    <script src="https://asset-prefix.com/path-prefix/webpack-runtime-ca7797724c44da2c1f54.js" async=""></script>

```
