### ISSUE TITLE
Frontmatter property type dependent on existing file

### ISSUE THREAD

**Issue by UliPlabst** [gatsbyjs/gatsby#19339]
## Description
I just tracked down very strange behavior of the nodes (and schema) of the markdown frontmatter. It appears that if I have a string property in the frontmatter that can be interpreted as a path to a file relative to the directory the markdown file lives in, then the created node for that property will be a file node and it's schema will be of type File. What's even worse that this totally depends on the first markdown file that gets parsed. For example if I have a markdown file with the following frontmatter 
```yaml
---
someprop: asd
image: asd.png
---
```
the type of the image property depends on whether there is a file *asd.png* in the same directory as the markdown file. If there isn't it will be just string, if there is it will be of type file. I don't know if this is a feature but in my opinion it shouldn't be as it is very unintuitive to just assume that by writing a string that (accidentally) also can be interpreted as a relative path the developer wants to have a file property. Also what happens if I depend on the frontmatter property to be of type File and accidentally delete the referenced file of the first parsed markdown post. My whole toolchain would break (this is what happened to me) just by me deleting a file that does not have any obvious connection frontmatter schema.    
I'm not entirely sure if gatsby-remark is the issue here or if it's something in gatsby itself but this was my best guess. If this is not the right place I would be glad if you could redirect me to somewhere else.

### Steps to reproduce
[repository to reproduce](https://github.com/UliPlabst/gatsby-remark-bug-reproduce). 
Launch gatsby develop and go to the graphql playground.  
Check the **markdownRemark > frontmatter > image** type. Realize it is of type File.   
Remove the **asd.png** in */contents/blog/**  
Execute *gatsby clean; gatsby develop*  
Go to the graphql playground again and see that **image** is now of type string.  

### Expected result
Frontmatter properties should just be forwarded and never be secretly exchanged by some hidden implicit logic. 

### Actual result

Frontmatter properties are transformed by some hidden logic that is dependent on the environment of the first markdown file parsed.

### Environment

    gatsby-plugin-sharp: ^2.2.22 => 2.2.22
    gatsby-remark-autolink-headers: ^2.1.10 => 2.1.10
    gatsby-remark-images: ^3.1.22 => 3.1.22
    gatsby-remark-katex: ^3.1.8 => 3.1.8
    gatsby-source-filesystem: ^2.1.22 => 2.1.22
    gatsby-transformer-json: ^2.2.8 => 2.2.8
    gatsby-transformer-remark: ^2.6.22 => 2.6.22
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14

**Comment by LekoArts** [comment]
Thank you for opening this!

Gatsby's inference of types won't always work magically (but it does in most cases). We have to make some assumptions and most of the times they make sense. But you have the option to explicitly define the type yourself with our schema customization API:
https://www.gatsbyjs.org/docs/schema-customization/#explicitly-defining-data-types

This will solve your problem :) 

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
