### ISSUE TITLE
Gatsby source contentful - Can't see full schema in GraphQl

### ISSUE THREAD

**Issue by Keshavishan** [gatsbyjs/gatsby#19334]
## Description

I have a field in Contentful (see below) 

<img width="840" alt="Screenshot 2019-11-07 at 10 09 40" src="https://user-images.githubusercontent.com/35744671/68379937-c7d22d00-0146-11ea-9553-58a032058da4.png">

As you can see the validation is set to accept only specific content types.

This is the relevant section in my gatsby-config.js file

`{
        resolve: 'gatsby-source-contentful',
        options: {
          spaceId: process.env.CFUL_SPACE_ID,
          accessToken: process.env.CFUL_API_KEY
        }
      }`

But when I look in the GraphQl Schema, as you can see below, I'm not able to see all the options that i have defined in Contentful and so am not able to get all the data

<img width="599" alt="Screenshot 2019-11-07 at 10 14 39" src="https://user-images.githubusercontent.com/35744671/68380490-dc62f500-0147-11ea-9e86-4aab91f0ab4e.png">

I can provide a demo project if it would really help but it will take a couple hours for me to set up which is why i haven't provided in the first instance
### Environment

  System:
    OS: macOS 10.14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.87
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.15.28 => 2.15.28
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10
    gatsby-plugin-sass: ^2.1.17 => 2.1.17
    gatsby-plugin-sharp: ^2.2.27 => 2.2.27
    gatsby-remark-images: ^3.1.25 => 3.1.25
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-source-contentful: ^2.1.44 => 2.1.44
    gatsby-source-filesystem: ^2.1.28 => 2.1.28
    gatsby-source-s3: 0.0.0 => 0.0.0
    gatsby-transformer-remark: ^2.6.26 => 2.6.26
  npmGlobalPackages:
    gatsby-cli: 2.7.53

**Comment by LekoArts** [comment]
Hello, please first ask Contentful's support if and how they expose that option via their API and then how this could be related to the Gatsby plugin. Furthermore a reproduction would be great. Thanks!

**Comment by grgcnnr** [comment]
Is there at lease on instance of all those content types in contentful? There may be a situation where any that don't concretely exist aren't being added to the union.

**Comment by Keshavishan** [comment]
There is definitely an instance of all the content types, with every single field being filled. My laptop is out of commission at the moment so I haven’t been able to upload a reproduction
