### ISSUE TITLE
Can't insert SSI code

### ISSUE THREAD

**Issue by angelod1as** [gatsbyjs/gatsby#19336]
## Description

I'm building a Gatsby app and I need to insert a few SSI lines (styled as HTML comments). Example

```html
<!--#set var="section" value="#{section}"-->
<!--#include virtual="/virtual/3.0/script-app.inc"-->
```

I can't find how to do this.

I need to put these (and other scripts) before the `head` tag, inside the `head` tag, at the end of the `body` tag and directly after it.

I've tried a lot of ways but none of them work. I've tried changing html.js but it just strips the comments out of the outputted code. I also tried working with gatsby-ssr and gatsby-browser but I keep thinking I don't know exactly what to do in those documents.

What I expect the output to be (with the exemplified codes):
```html
<!DOCTYPE html>
    <!--#set var="section" value="#{section}"-->
    <html>
        <head>
             <!--#include virtual="/virtual/3.0/script-app.inc"-->
             [rest of head code]
        </head>
    <body>
</html>
```

What happens: my output page has no comments whatsoever OR has it stringified (as in `&lt;!--#include virtual="/virtual/3.0/script-app.inc"--&gt;`

### Steps to reproduce

- Insert SSI comments in React code, through `dangerouslySetInnerHTML` or `html-react-parser` 
- Insert SSI comments in [html.js](https://www.gatsbyjs.org/docs/custom-html/) 

### Expected result

SSI codes remain on final code without changes

### Actual result

SSI code is removed or transformed into string (encoded)

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.config/yarn/global/node_modules/.bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 78.0.3904.87
    Firefox: 69.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: 2.13.21 => 2.13.21 
    gatsby-cli: ^2.7.13 => 2.8.8 
    gatsby-image: ^2.2.4 => 2.2.30 
    gatsby-plugin-catch-links: ^2.1.2 => 2.1.15 
    gatsby-plugin-manifest: ^2.2.1 => 2.2.26 
    gatsby-plugin-mdx: ^1.0.22 => 1.0.55 
    gatsby-plugin-offline: ^2.2.4 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.13 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.2 
    gatsby-plugin-sharp: ^2.2.6 => 2.2.36 
    gatsby-plugin-styled-components: ^3.1.0 => 3.1.11 
    gatsby-remark-external-links: ^0.0.4 => 0.0.4 
    gatsby-remark-images: ^3.1.5 => 3.1.29 
    gatsby-remark-lazy-load: ^1.0.1 => 1.0.2 
    gatsby-remark-picture: ^1.0.1 => 1.0.1 
    gatsby-remark-prismjs: ^3.3.3 => 3.3.21 
    gatsby-remark-relative-images: ^0.2.2 => 0.2.3 
    gatsby-remark-unwrap-images: ^1.0.1 => 1.0.1 
    gatsby-source-filesystem: ^2.1.2 => 2.1.35 
    gatsby-transformer-remark: ^2.6.0 => 2.6.32 
    gatsby-transformer-sharp: ^2.2.1 => 2.3.2

**Comment by angelod1as** [comment]
I solved this using gatsby-node.js and `onPostBuild()`. Copying the `html/js` then adding custom components (like `<ssi-code />` then replacing them using [replace-in-file](https://www.npmjs.com/package/replace-in-file):

```javascript
  replace.sync({
    files: ['./public/**/*.html', './public/*.html'],
    from: /<SSI-before-html>(.*?)<\/SSI-before-html>/g,
    to: '<!--#include virtual="/virtual/example.inc"-->',
  });
```

**Comment by beliayeu** [comment]
I believe another option is to insert the comment using dangerouslySetInnerHTML.
`<div dangerouslySetInnerHTML={{ __html: '<!--#set var="section" value="#{section}"-->'}}></div>`

cc: @angelod1as

**Comment by angelod1as** [comment]
@beliayeu tested and it doesn't work. React strips all html comments. I built a Gatsby Plugin for that: [Gatsby Plugin Html Comments](https://www.npmjs.com/package/gatsby-plugin-html-comments).

**Comment by beliayeu** [comment]
@angelod1as, hm, interesting. dangerouslySetInnerHTML approach works on my side.
please find codesandbox links: https://codesandbox.io/s/gatsby-starter-default-vpb6n and https://vpb6n.sse.codesandbox.io/
I have added a comment below `<h1>Hi people</h1>`.

also, tried it locally on latest gatsby version and in development and static modes. also, tried adding it using gatsby ssr api.

did I miss anything?
