### ISSUE TITLE
feature request: add version to gatsby-dev-cli

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#19348]
## Summary

add `-v` and `--version` to the `gatsby-dev-cli` to be equal to the `gatsby-cli`

### Motivation

i try to update the `setting-up-your-local-dev-environment` and it would be nice to have `gatsby-dev-cli` equal to the `gatsby-cli` with version info.

**Comment by pjeziorowski** [comment]
If this request is approved then I could take it on.

**Comment by LekoArts** [comment]
Sure, go ahead.

**Comment by muescha** [comment]
fixed by #19459
