### ISSUE TITLE
[gatsby-image] force polyfill lazy loading

### ISSUE THREAD

**Issue by afenton90** [gatsbyjs/gatsby#19344]
## Summary

During recent tests of some Gatsby sites I maintain I have found that I get better rendering results by NOT going with native image lazy loading on Chrome.

I have found that the current implementation in Chrome of `img` lazy is pretty inconsistent and too keen when loading images below the fold, resulting in performance degrading once the feature was GA on Chrome.

Would there be appetite for adding a `forcePolyfill` or `ignoreNative` prop on `gatsby-image` to enforce that the native prop is ignored if it is supported and instead always use the polyfill.

I get that this may be seen as some as sub-optimal, but the polyfill for lazy loading gives more consistent results at the moment.

**Comment by handreistoicescu** [comment]
I second this. It seems that Chrome sets a 'distance from top of page' threshold for lazy-loading images which is inversely proportional to the detected connection speed. The threshold lies between 3000px for fastest connections to 8000px for slowest connections. I see a lot of cases when webpages have a shorter height than 8000px, and all the advantages of lazy loading could be lost.

Source: [https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/frame/settings.json5?l=971-1003&rcl=e8f3cf0bbe085fee0d1b468e84395aad3ebb2cad](url)
