### ISSUE TITLE
Gatsby develop generated pages not rendering, but Gatsby build pages do render

### ISSUE THREAD

**Issue by matrix4123** [gatsbyjs/gatsby#19347]
## Description

I'm using the **createPage** function to generate a section of pages. 

When I use **gatsby develop**, all the pages appear to generate into the appropriate folder, but when I open them in a browser the browser returns no errors and just renders a blank page. 

When I use **gatsby build**, and host the static output through firebase the pages render just fine.

Of note... I have another folder of generated pages that seem to render just fine with **gatsby develop**...

I've also tried running **gatsby clean** a number of times.

### Steps to reproduce

1) Use **createPage** to generate a folder of pages
2) Run **gatsby develop**
3) Navigate to a page that was generated
4) Doesn't show anything other than blank page

### Expected result

Page should render

### Actual result

A blank page, no errors in browser or gatsby develop terminal

### Environment

System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Yarn: 1.17.3 - C:\Users\matri\AppData\Roaming\npm\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.17.10 => 2.17.10
    gatsby-image: ^2.2.30 => 2.2.30
    gatsby-plugin-create-client-paths: ^2.1.15 => 2.1.15
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5
    gatsby-plugin-manifest: ^2.2.26 => 2.2.26
    gatsby-plugin-offline: ^3.0.18 => 3.0.18
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13
    gatsby-plugin-sharp: ^2.2.36 => 2.2.36
    gatsby-source-filesystem: ^2.1.35 => 2.1.35
    gatsby-source-firestore-saphi: ^1.0.4 => 1.0.4
    gatsby-transformer-sharp: ^2.3.2 => 2.3.2

**Comment by jonniebigodes** [comment]
@matrix4123 can you share a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be looked at in more detail?

**Comment by matowang** [comment]
I think you have a misunderstanding here. Gatsby develop doesn't actually generate your pages into a folder or tile. You should use go to http://localhost:8000/ and navigate to the slug of your created page. Gatsby develop is just for development purposes and hosts a local server so you can view your website and edit it real time.

**Comment by matrix4123** [comment]
Hi @matowang , that is my understanding as well and that's what I'm doing. I am navigating to localhost:8000 and the return is just a blank page, this is while the local server is running via gatsby develop. If I just generate the pages with gatsby build and host them in another server, the pages render just fine.

**Comment by matrix4123** [comment]
> @matrix4123 can you share a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be looked at in more detail?

Sure, I'll try to reproduce!

**Comment by jonniebigodes** [comment]
@matowang technically it does generate into files and folders. I'm inclined to believe that the problem lies elsewhere, seeing the included packages in the environment section of the issue, it seems that the issue here lies on how to setup `gatsby-plugin-create-client-paths` properly to generate the client side paths and pages. But until a reproduction is made we can't say for sure.

**Comment by matrix4123** [comment]
> @matowang technically it does generate into files and folders. I'm inclined to believe that the problem lies elsewhere, seeing the included packages in the environment section of the issue, it seems that the issue here lies on how to setup `gatsby-plugin-create-client-paths` properly to generate the client side paths and pages. But until a reproduction is made we can't say for sure.

I'll work on the repro when I get a free moment, but I have only one path in create client paths: 

`{
      resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`/catalog/*`] },
    },`

The pages in question that are not rendering go under **/auction**

**Comment by jamestharpe** [comment]
I was able to reproduce this via a mismatch between my query and my template component.

e.g. query:

```
query TemplateArticle($slug: String!) {
		article: ...
```

And the template:

```
const tags = props.data.articles.frontmatter.tags // `articles` instead of `article` causes blank page, no errors!
```

**Comment by matrix4123** [comment]
I tracked this down, appears to be a data source issue on my end. The slug I was using to generate the page had a leading "/" so the link would start with "//" in the middle of the URL. Created some odd behavior!
