### ISSUE TITLE
Fix permissions issues in translation repositories

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#19358]
Right now we have two problems regarding permissions for maintainers of the [translation repositories](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#process-for-starting-a-new-translation):

1. Codeowners need to be members of the gatsby org, but only organization owners (NOT codeowners) can add people to the gatsby org. This means translation owners cannot appoint new owners.
2. Codeowners do not have permission to view "settings" of a project.

I can see two ways of fixing this:

## Option 1: Switch to using GitHub Teams

This is what we use for the React translation repos. This solves the second issue but not the first one: an owner of the gatsby org still needs to approve and invite

## Option 2: Use Outside Collaborators (Preferred)

We can use GitHub's [Outside Collaborators](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-outside-collaborators-to-repositories-in-your-organization) feature to give repo maintainers the proper permissions needed.

This means that translation maintainers have the ability to invite other maintainers to the repo without requiring a core team member to approve it.

Note that, regardless of the method chosen, we'll need to change the [repo creation script](https://github.com/gatsbyjs/gatsby/blob/master/scripts/i18n/create.js) to support it.

**Comment by LekoArts** [comment]
@tesseralis Is this still an issue?
