### ISSUE TITLE
Make Spanish and Russian translation repos easier to sync

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#19359]
## Summary

The [Spanish](https://github.com/gatsbyjs/gatsby-es) and [Russian](https://github.com/gatsbyjs/gatsby-ru) repos were made before the translation process was standardized, and need to follow a different process to [sync with the source repo](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#manually-syncing-translation-repos) than the others. We're going to need to do some git sorcery to get the repos synced up with [gatsby-i18n-source](https://github.com/gatsbyjs/gatsby-i18n-source)

## The Problem

Most of the translation repos are created by creating a copy of [gatsby-i18n-source](https://github.com/gatsbyjs/gatsby-i18n-source). This means the two repos share a [merge base](https://git-scm.com/docs/git-merge-base), and we can always merge the source into the translation.

However, the Spanish and Russian repos were created *before* this process was finalized. Instead of cloning from gatsby-i18n-source (which didn't exist yet), they are just raw copies of the `/docs` directory from the monorepo with no shared git history. Trying to do a `git merge` will fail:

```
Narcisse:tesseralis.club tesseralis$ git pull source master
warning: no common commits
...
From https://github.com/gatsbyjs/gatsby-i18n-source
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> source/master
fatal: refusing to merge unrelated histories
```

This means that these two repositories are special cases that can't follow the same steps as the other repos, and makes it complicated (if not impossible) to automate.

## The Solution

I figured it out! It's a little bit convoluted BUT

Execute these steps:

```
git remote add source https://github.com/gatsbyjs/gatsby-i18n-source.git
git fetch source master
git checkout -b rebase-source
git rebase source/master -Xtheirs
git checkout master
git checkout -b merge-source
git merge --allow-unrelated rebase-source
# <fix conflicts>
```

The `git rebase -Xtheirs` does a rebase picking the English version if there is a conflict. This creates a version of the repo with the source repo in its history. We could push this if we like -- but this takes a while since we're pushing a completely new commit history. We do the next step to make it easier:

The `git merge --allow-unrelated` allows us to merge the rebased version back into the master branch, only conflicting when there has been a **change** to the English repo. If we had just done `git merge --allow-unrelated source master`, it would have caused a conflict whenever the translated and English versions differed.

I've successfully executed these steps on both repos and opened PRs:

* https://github.com/gatsbyjs/gatsby-es/pull/174
* https://github.com/gatsbyjs/gatsby-ru/pull/30

**Comment by lex111** [comment]
@tesseralis so is this issue resolved? Or do we need to reinitialize the translation repository?

Off topic: please create a progress issue for the Russian translation, we were waiting for a reaction from you, but apparently you forgot about the Russian translation :(

**Comment by tesseralis** [comment]
@lex111 yeah! You just need to approve and merge this PR: https://github.com/gatsbyjs/gatsby-ru/pull/30

Also.. sorry for not creating a progress issue for Russian. I'll make one right away. Thanks for your patience!

**Comment by lex111** [comment]
@tesseralis thank you, but it seems to me that there should be much more pages for translation?

**Comment by tesseralis** [comment]
This should be resolved.
