### ISSUE TITLE
Static assets must still always revalidate, max-age=0

### ISSUE THREAD

**Issue by jtheberge** [gatsbyjs/gatsby#19363]
## Description
Files in the static folder still return with header `cache-control: public, max-age=0, must-revalidate` instead of `cache-control: public, max-age=31536000, immutable` as stated in docs: https://www.gatsbyjs.org/docs/caching/#static-files
![image](https://user-images.githubusercontent.com/13157499/68456470-b0308e00-01b2-11ea-923a-7b8981e8940d.png)

### Steps to reproduce
Followed quick start guide: https://www.gatsbyjs.org/docs/quick-start/
`gatsby new gatsby-site`
`cd gatsby-site`
`gatsby develop`

### Environment
```
  Browsers:
    Chrome: 78.0.3904.97
...
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
...
  npmPackages:
    gatsby: ^2.17.6 => 2.17.6
    gatsby-image: ^2.2.30 => 2.2.30
    gatsby-plugin-manifest: ^2.2.25 => 2.2.25
    gatsby-plugin-offline: ^3.0.17 => 3.0.17
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13
    gatsby-plugin-sharp: ^2.2.34 => 2.2.34
    gatsby-source-filesystem: ^2.1.35 => 2.1.35
    gatsby-transformer-sharp: ^2.3.1 => 2.3.1
```

Are docs outdated, and is it expected to ping the server each time even with static assets for revalidation? Between switching pages on starter app, sometimes the astronaut image temporarily shows the lower resolution fallback for ~100ms, and I'm thinking if max-age > 0, this might fix the issue since since it won't make the extra request which slows time to image paint for the high resolution version.

**Comment by muescha** [comment]
You are in `gatsby develop` mode. 

Try to simulate the production mode:

```bash
gatsby build
gatsby serve
```

**Comment by jtheberge** [comment]
> You are in `gatsby develop` mode.
> 
> Try to simulate the production mode:
> 
> ```shell
> gatsby build
> gatsby serve
> ```

Hey @muescha , thanks for the response. I should've also mentioned it happens in production mode as well.

**Comment by muescha** [comment]
it happens only in production mode. in development mode with hot reloading this not good. 

can you make a PR for the caching doc to say this more detailed?

**Comment by jtheberge** [comment]
@muescha Meant to say that production mode also has max-age=0. I can make a PR to update docs if that is not expected, but I think it shouldn't need to revalidate.

production mode:
![image](https://user-images.githubusercontent.com/13157499/68532509-d3eaf580-02d2-11ea-845b-9907309adaf7.png)

**Comment by LekoArts** [comment]
Thank you for opening this!

The docs state what you _yourself_ should do / how you should set up your hosting. Gatsby doesn't do that for you (It can't). You'll need to set those headers yourself or use e.g. `gatsby-plugin-netlify` if you use Netlify.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
