### ISSUE TITLE
Error `Failed to load config "react-app" to extend from.` after update to `2.17.10`

### ISSUE THREAD

**Issue by pedroapfilho** [gatsbyjs/gatsby#19377]
## Description

After updating to the version `2.17.10`, I'm having issues with this error message:

<img width="407" alt="Screenshot 2019-11-08 at 14 34 01" src="https://user-images.githubusercontent.com/13142568/68498239-2249b700-0235-11ea-87d5-a31d127dafec.png">

The repository of this project is this one: https://github.com/pedroapfilho/gatsby-theme-awesomeness

After the update, I can't start the `example` site anymore (it was made to test my gatsby theme).

The weird part is that after I publish it to NPM, it works on my website without any issue: https://github.com/pedroapfilho/website

### Steps to reproduce

Download the repo:
`git clone https://github.com/pedroapfilho/gatsby-theme-awesomeness.git`

Run Yarn (I use yarn workspaces)
`yarn`

Run the example (there's a script to run the correct workspace)
`yarn develop`
or
`yarn workspace example develop`

### Expected result

It should load without any warnings or errors.

### Actual result

This error appears:

```

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Failed to load config "react-app" to extend from.
Referenced from: BaseConfig

File: .cache/app.js

failed Building development bundle - 0.488s
```

<img width="407" alt="Screenshot 2019-11-08 at 14 34 01" src="https://user-images.githubusercontent.com/13142568/68498239-2249b700-0235-11ea-87d5-a31d127dafec.png">

### Environment

  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 69.0.1
    Safari: 13.0.3

**Comment by Noviny** [comment]
Facing the same error. Error appears to be coming from `utils/eslint-config.js` line 12:

https://github.com/gatsbyjs/gatsby/blob/f488d4a82eae0c7e0aae7d47052f2fc204acf0a2/packages/gatsby/src/utils/eslint-config.js#L12

Commenting out this line causes the error to go away (though obviously other effects).

I am unsure *why* this is the case as changes to this file haven't occurred for some time.

Happy to provide more system details, but I encountered this in a different monorepo context.

**Comment by LekoArts** [comment]
You most likely have misaligned/different versions of packages installed.

I cloned your repo, removed the `yarn.lock`, run `yarn install` and can run `yarn workspace example develop` without problems. Please try upgrading all your versions (e.g. React or Gatsby) to the same version.

**Comment by pedroapfilho** [comment]
Thanks a lot @LekoArts, it worked. It seems that running `yarn upgrade-interactive --latest` and upgrading gatsby on the `theme` and then upgrading it on the `example` made this issue happen. Deleting yarn.lock and running `yarn` again fixed the issue.
