### ISSUE TITLE
Build script returned non-zero exit code: 254

### ISSUE THREAD

**Issue by Richi92d** [gatsbyjs/gatsby#19373]
hello,
I can not find a solution need help please when i deploy angular project in Netlify i have this error:
Build script returned non-zero exit code: 254

![dist](https://user-images.githubusercontent.com/38420876/68485579-dbad8a00-023f-11ea-8c52-0a3dde8389f2.JPG)
![netlify](https://user-images.githubusercontent.com/38420876/68485582-dbad8a00-023f-11ea-9071-9ef876105d3f.JPG)

![package](https://user-images.githubusercontent.com/38420876/68485704-0a2b6500-0240-11ea-9a6d-92ac1975a835.JPG)

**Comment by jonniebigodes** [comment]
@Richi92d it seems that you posted the issue in the wrong place. Gatsby doesn't handle angular projects. You probably need to create a issue in the [netlify community](https://community.netlify.com/), as they are better suited to help you triage your specific issue.
