### ISSUE TITLE
Can Netlify Large File Image be called by Gatsby CMS (Kaldi) ? How? 

### ISSUE THREAD

**Issue by beerneko** [gatsbyjs/gatsby#19384]
I successfully deployed and brows Gatsby Kaldi CMS site with a new image from static/img in my local. Also I uploaded the same Git LFS tracked new image into Netlify Large Media. But as soon as I pushed the code for using the new image file, it just failed as below error message.

3:49:24 PM: success Rewriting compilation hashes — 0.043
3:49:24 PM: error Input file contains unsupported image format
3:49:24 PM: Failed to process image /opt/build/repo/static/img/gyosen.jpg Input file contains unsupported image format
3:49:24 PM: See our docs page for more info on this error: https://gatsby.dev/issue-how-to
3:49:24 PM: 
3:49:24 PM:   Error: Input file contains unsupported image format
3:49:24 PM: 

I saw the other git question post (Using Gatsby together with Netlify Large Media #12438), but It doesn't say if it's possible to do or just give up on this way and use something else.

thanks

**Comment by muescha** [comment]
In the other issue I don't see that is possible to fetcg the images while compile time. 

I only have this idea for a Transform plugin for this images:

https://github.com/gatsbyjs/gatsby/issues/12438#issuecomment-552100760

> As I understand would be here instead of pulling an processing the image on build time and then create the different sourcemaps with the processed result:
> 
> Skip the first Step and then generate image Sourcemaps which fits the netlify image processing on netlify like this`/images/apples.jpg?nf_resize=fit&w=300&h=400`
> Processing and caching is then on the netlify side
> 
> Maybe an plugin also trigger all the possible image formats once so that they created

**Comment by beerneko** [comment]
Thanks for your reply! I'm such a newbie for using any CMS and frameworks. How do I generate image Sourcemaps and compile the index.md file with a Transform plugin by the gatsby build?

---
templateKey: index-page
title: Kaldi
**image: /img/gyosen.jpg?nf_resize=fit&w=300&h=400**
heading: Kaldi
subheading: Kaldi Coffee!
mainpitch:
  title: Why Kaldi
...

any help would be so helpful.

**Comment by LekoArts** [comment]
Thank you for opening this!

As written in the other issue it's currently not possible to use it. I also don't know what "Kaldi" is but I'd try asking them how to use their product with that.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by muescha** [comment]
I think Kaldi is means the demo shop of the "Kaldi Coffee Shop"

**Comment by muescha** [comment]
Is this plugin possible in this construct that it just create the links which are pointing to the netlify without physical touching the images?
