### ISSUE TITLE
Gatsby Environment Variables docs are confusing

### ISSUE THREAD

**Issue by patspam** [gatsbyjs/gatsby#19387]
The gatsby [docs](https://www.gatsbyjs.org/docs/environment-variables/) on environment variables are pretty confusing.

For example, this text:

> You can define your own OS Env Var to track the active environment, and then to locate the relevant Project Env Vars to load. Gatsby itself **will not do anything with that OS Env Var**, but you can use it in gatsby-config.js

..is followed by an example using `process.env.GATSBY_ACTIVE_ENV`, which makes it seem like Gatsby will not do anything with `GATSBY_ACTIVE_ENV`, which is not true (it's used in `gatsby/src/utils/webpack.config.js`).

Also, it doesn't help that the examples given are immediately discouraged ("However we strongly advise against that!").

Personally, I would have found things clearer if you'd just said:
* In Node, env vars are accessed via `process.env`
* You can use dotenv to add additional env vars to `process.env`, but we recommend against checking these files into source control
* Gatsby helpfully embeds `process.env.GATSBY_*` in compiled JS (as `process.env`)

**Comment by patspam** [comment]
Hey, it takes time and effort to file bugs. Auto-closing them because you didn't get around to triaging them is a de-motivator for community involvement. Putting emojis at the end of your message doesn't make it any better,

This is the one and only time I'm going to ping on this bug to say that it's not stale.

**Comment by LekoArts** [comment]
Thanks for the issue and sorry that it slipped through. We'd be happy to receive a PR improving the document :)
