### ISSUE TITLE
dev(core): add note note about developer-runner

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#19380]
## Summary

add a note about [`developer-runner`](https://github.com/pieh/develop-runner) because this gem is somewhere hidden in the issues and not documented

### Motivation

- introduce this tool new core contributors 
- plugin-developers could use to test their plugins on many repos
- inform when you need it and when not

### Steps

- add a small readme to developer-runner (with the text snippets)
- put a hint and a link to in readme at gatsby-dev-cli
- ??? or other places

### Doc snippets 

i found this doc snippets as a start:

comment 1 https://github.com/gatsbyjs/gatsby/pull/19092#pullrequestreview-308303725

> This is so cool! 👍
> 
> I think you are missing child/parent relationship cases, so when child/parent relationship is added either through action or by setting 'parent' field.
> 
> We usually test against .org (www folder in monorepo) using gatsby-dev-cli. You can test against multiple sites using [develop-runner](https://github.com/pieh/develop-runner). You need to modify source code a bit, but it's still very handy.
> 
> We often publish a pre-release version for packages with big changes, then you can use it to test with develop-runner. Eg you can reuse tag `@schema-customization`. (To do it, go to `gatsby/packages/gatsby` and do `yarn publish --tag schema-customization`).

comment 2 https://github.com/gatsbyjs/gatsby/pull/19349#issuecomment-551580922

> > should we also add some notes about develop-runner - i only found this description here [#19092 (review)](https://github.com/gatsbyjs/gatsby/pull/19092#pullrequestreview-308303725)
> 
> I'm not sure - we ourselves use this pretty rarely, only when there is rewrite of one of major core function that potentially could introduce bugs (or unforeseen breaking changes). Last time we used it (before schema rebuilding PR) was materialization for data layer.
> 
> The script itself also takes a loong time to run, so I don't want to force it on contributors, as it's not needed for most of PRs.
> 
> It makes sense to me to make a note about it somewhere, but this could be separate PR to not scope creep this one?

**Comment by LekoArts** [comment]
Hi, thanks for the issue!
I don't think the motivation you listed would outweigh the possible negative impacts of mentioning this somewhere.

Most if not all PRs that contributors other than the core team don't touch code that would need that test runner. Plugin developers also use well tested public APIs that don't need that runner. Lastly, mentioning this somewhere would make the impression that this tool could be necessary or is even stable.

Maybe once this is a more fleshed out solution that is actually usable by normal contributors we could revisit that. For now I'd want to close this.
