### ISSUE TITLE
How to filter by content type using gatsby-source-drupal?

### ISSUE THREAD

**Issue by Vacilando** [gatsbyjs/gatsby#19385]
It's not clear to me how can I in the options of gatsby-source-drupal specify that Gatsby should only fetch data about one particular content type.

In https://mysite.org/jsonapi I see -links and therein -node--page, so I tried filters like 
```
        filters: {
          links: "node--page",
        },
```
and many other variants, but none of them work.

From https://www.drupal.org/docs/8/modules/jsonapi/filtering it's clear how to filter by fields, but it's filtering by content type is what we need.

Advice would be much appreciated.

**Comment by graysonhicks** [comment]
I believe if you have a content type that you do not want `gatsby-source-drupal` to pull down, you should use [Drupal JSON API Extras](https://www.drupal.org/project/jsonapi_extras) to disable/restrict permissions for the content types you don't want `gatsby-source-drupal` to fetch.  I believe the Drupal path for those settings are `admin/config/services/jsonapi/resource_types` after you enable JSON API Extras.

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
