### ISSUE TITLE
Make JSDoc API files more easily extractable for translation

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#19383]
The following files are queried by dot-org in order to generate JSDoc API pages:

* gatsby/src/redux/actions/public.js
* gatsby/src/redux/actions/restricted.js
* gatsby/src/utils/api-browser-docs.js
* gatsby/src/utils/api-node-helpers-docs.js
* gatsby/src/utils/api-node-docs.js
* gatsby/src/schema/node-model.js
* gatsby/cache-dir/api-ssr-docs.js

Since they contain publicly consumable text content, they will need to be made available for translation. But this is cumbersome: they're scattered throughout the codebase, and some of them are integrated with logic-heavy JS files. 

To mitigate this, I propose we create a new directory gatsby/src/public-apis/ containing flow/typescript type definitions for these APIs. The implementations can be typed to these interfaces, and we can easily find them and point at them as files to localize.

## Related Issues

Depends on: #19035

**Comment by muescha** [comment]
> If we move them during the sourcing phase, it would require us to source things and access things differently for English and translated content

As I suggested before: if we use the repo `gatsby-i18n-source` as the source for the english documentation generation then we don't have to distinct the sources. 
All language repos are equal (except that it is called `-source` and not `-en`)
