### ISSUE TITLE
Figure out what to do with the `node-model` and `actions` API JSDoc.

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#19382]
## Summary

We need to do some work to make JSDocs translate-able: #18704. For most of them, it's relatively straightforward, since they're stub files that don't have any implementation. But for two files, `actions` and `node-model`, the documentation is tied directly to the implementation (as doc comments are generally supposed to be) and it's more difficult.

## Ideas

Some suggestions for dealing with this problem:

* Switch from JSDoc to plain Markdown documentation
* In the update-source script, pull out all the JSDoc without the functions
* Switch to Typescript and document these types in the `.d.ts` file

**Comment by muescha** [comment]
i would vote for TypeScript

(copied from https://github.com/gatsbyjs/gatsby/issues/19035#issuecomment-551948092)

> Since there is a goal for native TypeScript (#18983) in Gatsby:
> 
> would it make sense to put the JSDoc information instead in separate `api-*-docs.js` better into the TypeScript `.d.ts` files?
> 
> Then we have this goals fixed:
> 
> * doc are decoupled from code (can be pushed to repo for translatIon)
> * dts files are up to date (this is needed for right type checking)
> * IDE editors can use it for assistance
> * more rich descriptive types can be displayed in API Reference

**Comment by tesseralis** [comment]
Typescript isn't a bad idea, but we have to consider how long it's going to take to get set up. We're still in the process of deciding what to do, 

@sidharthachatterjee, how long do you think it'll take for Gatsby to start using Typescript? And maybe once we start, we can use the API doc files as the first things we type?

**Comment by tesseralis** [comment]
We're going to go with @muescha's suggestion and create an interface for actions and node-model in flow/typescript with the doc comments attached.
