### ISSUE TITLE
Issues&PullRequest: add template for technical repos

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#19381]
## Summary

Some of the mirror repos ( [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed), [gatsby-starter-default](https://github.com/gatsbyjs/gatsby-starter-default/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed), [gatsby-starter-hello-world](https://github.com/gatsbyjs/gatsby-starter-hello-world/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed) and the new [gatsby-i18n-source](https://github.com/gatsbyjs/gatsby-i18n-source)) get always some pull requests which are closed immediately

### Basic example

see pull requests in:

- [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed)
- [gatsby-starter-default](https://github.com/gatsbyjs/gatsby-starter-default/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed)
- [gatsby-starter-hello-world](https://github.com/gatsbyjs/gatsby-starter-hello-world/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed)

### Motivation

it's not welcoming for new contributors if PR are closed immediately. with this hint it would be less frustrating when the contributor read the issue/pr template and can then make pr to the right repo

**Comment by LekoArts** [comment]
Hey, thanks for your suggestion! We currently see no need to change the behavior as we think the bot is the most effective way of communicating that. From experience we can say that comments in a PR template are often overlooked.
