### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jaisadana19** [gatsbyjs/gatsby#19393]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by jonniebigodes** [comment]
@jaisadana19 can you elaborate a bit more on the issue you're having with gatsby? It seems that you only uncommented the issue template and created a new issue?
