### ISSUE TITLE
Gatsby themes does not work well through symlinks

### ISSUE THREAD

**Issue by Noviny** [gatsbyjs/gatsby#19409]
## Description

In my monorepo, I have a gatsby plugin as a package, and a test gatsby website as a second package designed to ensure that plugin acts as expected. The linked plugin cannot be found.

### Steps to reproduce

1. Check out [branch here](https://github.com/atlassian/brisk-docs/tree/noviny/as-gatsby-theme) from our repository
2. DO NOT run `yarn` to install. Instead run `bolt` to install (may require globally installing bolt :/ )
3. `cd packages/test-website && yarn gatsby develop`

### Expected result

Gatsby resolves plugin found at:

```
brisk-docs/packages/test-website/node_modules/@brisk-docs/gatsby-plugin
```

which is a symlink to:

```
brisk-docs/packages/gatsby-plugin
```

### Actual result

We get the following error:

```
$ /Users/bconolly/Development/brisk-docs/packages/test-website/node_modules/.bin/gatsby develop

 ERROR #10226  CONFIG

Couldn't find the "@brisk-docs/gatsby-plugin" plugin declared in "/Users/bconolly/Development/brisk-docs/packages/test-website/gatsby-config.js".

Tried looking for a local plugin in /Users/bconolly/Development/brisk-docs/packages/test-website/plugins/@brisk-docs/gatsby-plugin.

Tried looking for an installed package in the following paths:
 - /Users/bconolly/Development/brisk-docs/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/@brisk-docs/gatsby-plugin
 - /Users/bconolly/Development/brisk-docs/node_modules/gatsby/dist/bootstrap/node_modules/@brisk-docs/gatsby-plugin
 - /Users/bconolly/Development/brisk-docs/node_modules/gatsby/dist/node_modules/@brisk-docs/gatsby-plugin
 - /Users/bconolly/Development/brisk-docs/node_modules/gatsby/node_modules/@brisk-docs/gatsby-plugin
 - /Users/bconolly/Development/brisk-docs/node_modules/@brisk-docs/gatsby-plugin
 - /Users/bconolly/Development/node_modules/@brisk-docs/gatsby-plugin
 - /Users/bconolly/node_modules/@brisk-docs/gatsby-plugin
 - /Users/node_modules/@brisk-docs/gatsby-plugin
 - /node_modules/@brisk-docs/gatsby-plugin
```

From this, it looks in `brisk-docs/packages/test-website/plugins`, but does not look in `brisk-docs/packages/test-website/node-modules`

Instead, it tests the remainder of the paths from where gatsby has been installed, not locally from where it is being run, so in this instance, it checks for a package with the correct name from `brisk-docs/node_modules` up, instead of `brisk-docs/packages/test-website/node_modules` up.

In a yarn monorepo, local linked packages are symlinked to the root directory, meaning this will will not lead to an error state, but in a `bolt`-based monorepo, the local packages are not linked at root, leading to an error.

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.15.2 - ~/.nvm/versions/node/v10.13.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 69.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.17.10 => 2.17.10 
```

**Comment by LekoArts** [comment]
Thank you for opening this!

Please try asking `bolt` maintainers first as we only recommend using `yarn workspaces` and I personally have never heard of `bolt`. If it's not an issue with them feel free to reopen.

Furthermore, your local plugin is missing an entry point: https://github.com/atlassian/brisk-docs/tree/noviny/as-gatsby-theme/packages/test-website/plugins/%40brisk-docs/gatsby-plugin

So an empty `index.js` and `main` entry in the package.json is missing. Maybe that's the culprit.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
