### ISSUE TITLE
Navigate without scrolling to top?

### ISSUE THREAD

**Issue by linvain** [gatsbyjs/gatsby#19401]
Can I use `navigate` without scrolling to top? I use it just to change the language.

**Comment by sidharthachatterjee** [comment]
@linvain Sure! The way `shouldUpdateScroll` works is that it lets you return an Array of coordinates to scroll to. 

In case you're just updating the language (and want to persist scroll between equivalent pages in different locales), check out the following code snippet:

```
export const shouldUpdateScroll = ({
  routerProps: { location },
  getSavedScrollPosition,
}) => {
  // Construct other possible location values based on current one 
  const queriedPosition = getSavedScrollPosition(location)

//   If any of them are an [] return that value 
}

```

You can use the [`getSavedScrollPosition`](https://www.gatsbyjs.org/docs/browser-apis/#shouldUpdateScroll) API to get the last known scroll position for that path. In your case, you would need to get it for the path in any other possible language (assuming language is a part of the path, strip it out, generate other possible paths and check) and then return coordinates for that page. 

Hope that helps! Marking this as answered in the mean time and closing it. Feel free to comment or reopen if you have anything else you would like to discuss. Thanks!
