### ISSUE TITLE
[docs] update docs for createRemoteFilenode usage

### ISSUE THREAD

**Issue by riencoertjens** [gatsbyjs/gatsby#19414]
## Summary
I was using `createRemoteFilenode` and found some things in the docs that could use an update 
- using the examples on [this page](https://www.gatsbyjs.org/docs/preprocessing-external-images/#gatsby-node) I got a warning `warn Deprecation warning - adding inferred resolver for field GhostPost.feature_image_localFile. In Gatsby v3, only fields with an explicit directive/extension will get a resolver.` so I think the example should be changed to (not interily sure about this, since I'm not familiar with `@infer` / `@noInfer`):
```
...
createTypes(`
    type MarkdownRemark implements Node @infer(noDefaultResolvers: false) {
      frontmatter: Frontmatter
    }
    type Frontmatter {
      title: String!
      featuredImgUrl: String
      featuredImgAlt: String
    }
  `)
...
```
- the readme if the [`gatsby-source-filesystem`](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/?=filesys#createremotefilenode) doesn't really have a clear usage example (to me at least) since there is no context given as to where it is recommended to use `createRemoteFilenode` , maybe we can add a link to above mentioned page?

not sure if anyone is working on any of these pages? if not I can make a pr for this.

**Comment by laurieontech** [comment]
Hey @riencoertjens, sorry for the delay. If you're able to make a PR we'd love to have your contributions!

**Comment by LekoArts** [comment]
The page was updated in the meantime :)
