### ISSUE TITLE
Source plugins documentation should clarify that they are integrations

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#19415]
**Story**

Imagine Suzanne is a Magento user who's heard about this cool newfangled thing called Gatsby and want to check it out.

Suzanne [Google "magento gatsby"](https://www.google.com/search?q=magento+gatsby&oq=magento+gatsby&aqs=chrome..69i57.3817j0j7&sourceid=chrome&ie=UTF-8) and once I get past the ads I get:

![image](https://user-images.githubusercontent.com/4388699/68563001-ed8a5b00-0400-11ea-83f5-110589307212.png)

Hmm. Well, the first result looks kind of relevant. So Suzanne clicks it...

![image](https://user-images.githubusercontent.com/4388699/68563037-2296ad80-0401-11ea-8df4-0a57772f4edb.png)

**Challenges**

Now Suzanne has a bunch of questions:

- What does `gatsby-source-magento` mean?
- Why would I use this plugin instead of `gatsby-source-magento-2`? That also appeared on the Google search results.
- The first words on the documentation mention that `gatsby-source-magento` is a "source plugin". So....what's a source plugin?

**Takeaway:** We can do more to provide context to casual users / visitors to our `packages`.

**Proposal:** Make "what this page is" more clear by:

1) State that this is an integration between Gatsby and Service X, which we call a "source plugin". 

2) Prominently adding a link to the source plugin documentation (I'm making this doc more clear in https://github.com/gatsbyjs/gatsby/pull/19413)

3) change the page title from eg `gatsby-source-magento | GatsbyJS` to `Gatsby + Magento integration docs | gatsby-source-magento | GatsbyJS`. (This will also help in search results)

Here's an example of a design that could solve 1) and 2): (note, I am definitely not a designer!)

![image](https://user-images.githubusercontent.com/4388699/68572151-8b8a1f80-0419-11ea-9a79-371883869612.png)

**Deal with later, but not now**: Official disclaimers or summaries for appropriate packages (like `gatsby-source-magento2` or `gatsby-source-graphql-universal`) could help. There are few enough confusing instances that we shouldn't worry about this right now.

**Comment by AishaBlake** [comment]
This seems like it would be helpful. A couple of questions to consider for anyone implementing this: 

- Presumably, this would _only_ be for source plugins and not transformer plugins, themes, etc. Do we have a better way of identifying source plugins programmatically than pattern matching on the package name?
- Where would we be getting the service name from? For example, if the package name is `gatsby-source-wordpress`, how does my template know that it should display "Gatsby + WordPress integration" and not, for example, "Gatsby + Wordpress"?
