### ISSUE TITLE
gatsby develop breaks gatsby build/serve when running concurrently

### ISSUE THREAD

**Issue by apolopena** [gatsbyjs/gatsby#19431]
**Description:**
This is all on a vanilla gatsby installation and came up in my normal workflow when I was trying to keep `gatsby develop` running on port 8000 while testing a production build (`gatsby serve`) on port 9000:

If I have `gatsby serve` running after a successful `gatsby build`, the site is displayed properly in the browser at localhost:9000. I then run `gatsby develop` in another terminal and the site is displaying properly at localhost:8000 in another tab in the same browser. Then when I go back to the localhost:9000 tab and refresh it, the screen goes white with the following 2 errors:
```
localhost/:1 GET http://localhost:9000/socket.io/socket.io.js net::ERR_ABORTED 404 (Not Found)
localhost/:1 GET http://localhost:9000/socket.io/socket.io.js net::ERR_ABORTED 404 (Not Found)
```

Furthermore `gatsby serve` will exhibit the above issue until I rebuild the site using `gatsby build`

**Steps to reproduce:**
1. At the terminal:
```
$ gatsby new client
$ cd client
$ gatsby build
$ gatsby serve
```

2. Open the browser to: localhost:9000
3. Then in another terminal:
`$ gatsby develop`

4. Open the browser in another tab to: localhost:8000
5. Go back to the localhost:9000 tab and hit refresh

**Expected result:**
localhost:9000 should display the site propely as per the last build

**Actual result:**
localhost:9000 displays a white screen with the following 2 errors in the console:
```
localhost/:1 GET http://localhost:9000/socket.io/socket.io.js net::ERR_ABORTED 404 (Not Found)
localhost/:1 GET http://localhost:9000/socket.io/socket.io.js net::ERR_ABORTED 404 (Not Found)
```

This issue is not rectified until the production build is rebuilt using the `gatsby build` command

**Environment:**
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - /c/Python27/python
  Browsers:
    Edge: 44.18362.387.0
    Chrome: 78.0.3904.97 (Official Build) (64-bit)
    Firefox: 70.0.1 (64-bit)

**Comment by wardpeet** [comment]
Hey, you can't run 2 gatsby instances at the same time in the same folder. They both save files to public so you'll end up with mixed html.

A solution would be to move your public folder to a different folder and run `npx serve` on the folder to launch another http sever.

Thank you for opening this, @apolopena 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by apolopena** [comment]
Thank you, this makes sense.

**Comment by cchoe1** [comment]
I ran into a similar issue where `gatsby serve` doesn't perform a build before hand.  I was racking my brain forever wondering why a simple serve wouldn't work and kept telling me 404.html isn't found.  Then I tried a `gatsby develop` and that seemed to do a partial build but it still didn't work.  I had to explicitly run a `gatsby build` and then a `gatsby serve` to get the project to run.
