### ISSUE TITLE
Client-only routes do not work with pathPrefix 

### ISSUE THREAD

**Issue by imalexsq** [gatsbyjs/gatsby#19440]
## Description

Adding pathPrefix to gatsby-config while using client-only routes breaks routing in production builds.

### Steps to reproduce
Use https://github.com/gatsbyjs/gatsby/tree/master/examples/simple-auth
- add pathPrefix: '/activate'
-  gatsby build --prefix-paths
- move public/* to server/activate
- client-only routes do not render

### Expected result
Client-only routes should render components

### Actual result

No components are rendered, reloading a route returns 404 from server

### Environment
  System:
    OS: Linux 4.15 Linux Mint 19.2 (Tina)
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.2/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0.1
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14

**Comment by laradevitt** [comment]
I think what you might need to do is import the helper function `withPrefix` from gatsby into app.js and then apply it to your routes.

*src/pages/app.js*

```js
// ...snipped
import { withPrefix } from "gatsby"

const App = () => (
  <Layout>
    <Status />
    <Router>
      <PrivateRoute path={withPrefix('/app/profile')} component={Home} />
      <PrivateRoute path={withPrefix('/app/details')} component={Details} />
      <Login path={withPrefix('/app/login')} />
    </Router>
  </Layout>
)

export default App
```

You'll have to update the Form component, as well.

Hope that helps.

**Comment by imalexsq** [comment]
@laradevitt thanks for your input. I tried your suggestion but the result is still the same - the client-only routes are called but their components are not rendered.

**Comment by laradevitt** [comment]
You're welcome. Sorry to hear it's still not working though!

I cloned the simple-auth example and after running `yarn install` and making the changes above, I did:

```cli
$ gatsby build --prefix-paths
$ cd public && mkdir activate | mv * activate
$ cd ..
$ gatsby serve
```

And it appears to be working fine. 

Note that in the above steps I'm moving the *public/* files to *public/activate/*.

**Comment by imalexsq** [comment]
@laradevitt thank you for all your help. The issue was on my end with wrongly configured router paths.

**Comment by truongngoctuan** [comment]
I think the answer should be put in docs, it takes a while for me to find out the solution in here

**Comment by stanleyyuenyiu** [comment]
so what is the soluition?
