### ISSUE TITLE
Importing css from an npm package works in develop, but not on serve

### ISSUE THREAD

**Issue by JasonStoltz** [gatsbyjs/gatsby#19446]
## Summary

Importing css from an npm package works in develop, but not on serve

## Relevant information

I added an external stylesheet, imported from an npm package.

```
import "@elastic/react-search-ui-views/lib/styles/styles.css"
```

The styles are present when running `gatsby develop`, but not `gatsby build` / `gatsby serve`.

Steps to reproduce:
1. `gatsby new gatsby-starter-default https://github.com/gatsbyjs/gatsby-starter-default`
2. https://github.com/JasonStoltz/example-for-gatsby-issue/commit/1a54162958e5ae89a758089d3e3c24116c65b101

For reference: https://github.com/JasonStoltz/example-for-gatsby-issue

### Environment (if relevant)

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 68.0
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11
    gatsby-image: ^2.2.31 => 2.2.31
    gatsby-plugin-manifest: ^2.2.27 => 2.2.27
    gatsby-plugin-offline: ^3.0.19 => 3.0.19
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14
    gatsby-plugin-sharp: ^2.2.37 => 2.2.37
    gatsby-source-filesystem: ^2.1.36 => 2.1.36
    gatsby-transformer-sharp: ^2.3.3 => 2.3.3
  npmGlobalPackages:
    gatsby: 2.17.11
```

### File contents (if changed)

I made minimal changes to the starter, which can be seen here: https://github.com/JasonStoltz/example-for-gatsby-issue/commit/1a54162958e5ae89a758089d3e3c24116c65b101

**Comment by blainekasten** [comment]
@JasonStoltz Thank you for the great write up! We're diving into this to understand what's happening. I was able to reproduce your issue. I also found a strange work around if you need a time-sensitive solution. 

It seems that if you have a named import and "use it" then it gets included in the bundle. So I did the following change and now it's working:

```js
import styles from "@elastic/react-search-ui-views/lib/styles/styles.css"
console.log({ styles })```

I'll report back if we find a better understanding or fix.

**Comment by JasonStoltz** [comment]
@blainekasten Oh wow, that's really interesting. Thanks for the workaround.

**Comment by JasonStoltz** [comment]
So it would appear that something is pruning it during the build because it appears to be unused.

**Comment by blainekasten** [comment]
@JasonStoltz Yeah. So we dug in a bit more and it's a problem with `@elastic/react-search-ui-views`. In their [package.json](https://github.com/elastic/search-ui/blob/master/packages/react-search-ui-views/package.json#L8) they mark the library as sideEffect free. This is problematic though, wSokra suggests css libraries should do [this](https://github.com/webpack/webpack/issues/6741#issuecomment-372720641).

So the real fix here is to work with the library author to update their package. @JasonStoltz would you want to handle that or should I?

I'm going to close this as this is not a problem with Gatsby. Feel free to keep discussion going however!

**Comment by JasonStoltz** [comment]
@blainekasten I am the library author so I can update my package. Thanks!

**Comment by GiliStern** [comment]
This happened to me too when importing scss from swiper
` import "swiper/components/navigation/navigation.scss"`

And I can confirm the workaround works 👍

**Comment by fullstacksk** [comment]
> This happened to me too when importing scss from swiper
> ` import "swiper/components/navigation/navigation.scss"`
> 
> And I can confirm the workaround works 👍

Same , I am not able to import css from package for navigation and pagination. How did u resolvedit?

**Comment by carlaiau** [comment]
Can confirm this is also happening with swiper.

```
import "swiper/css"
import "swiper/css/effect-fade"
import "swiper/css/navigation"
import "swiper/css/pagination"
```

all get pruned in production

**Comment by cbroomemktw** [comment]
Confirmed this happens when importing plyr.css from https://plyr.io/
