### ISSUE TITLE
Gatsby 'develop' requires constant terminal window resizing to work

### ISSUE THREAD

**Issue by cyberwombat** [gatsbyjs/gatsby#19451]
## Description

`gatsby develop` hangs. But unlike the issues experienced by people in [#17131](https://github.com/gatsbyjs/gatsby/issues/17131) this is not related to any connection or processing issues - it appears as if the spinner gets stuck and the only choice is to either restart the process (which I was doing until I discovered the trick) or resize the terminal window. Now I just keep my window shaking to get it going. 

Please see the other people with issue at bottom of thread on #17857 

I am opening this so this issue can focus solely on the terminal resize issue. 

### Steps to reproduce

Unfortunately this is is hard to reproduce - It may be a OS/UI thing. I am on iTerm2 on Catalina myself. 
Its important to understand that this is not a normal gatsby process hanging like some other people had with the non terminal resize fix - if I let it sit it will never complete (I waited a whole day). And If I keep the window resizing it works fine.  I have made some attempts at disabling the spinner as it may be related but unsure yet.

### Expected result

It should not hang

### Actual result

Hangs

### Environment

```

  System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Safari: 13.0.1
  npmPackages:
    gatsby: ^2.15.34 => 2.15.34 
    gatsby-image: ^2.2.20 => 2.2.24 
    gatsby-plugin-breadcrumb: ^3.2.1 => 3.2.1 
    gatsby-plugin-feed: ^2.3.13 => 2.3.15 
    gatsby-plugin-google-analytics: ^2.1.17 => 2.1.20 
    gatsby-plugin-manifest: ^2.2.18 => 2.2.20 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6 
    gatsby-plugin-mdx: ^1.0.49 => 1.0.49 
    gatsby-plugin-offline: ^3.0.8 => 3.0.12 
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10 
    gatsby-plugin-remove-trailing-slashes: ^2.1.7 => 2.1.9 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-sass: ^2.1.15 => 2.1.17 
    gatsby-plugin-sharp: ^2.2.25 => 2.2.28 
    gatsby-plugin-sitemap: ^2.2.14 => 2.2.16 
    gatsby-remark-autolink-headers: ^2.1.11 => 2.1.13 
    gatsby-remark-copy-linked-files: ^2.1.20 => 2.1.25 
    gatsby-remark-external-links: ^0.0.4 => 0.0.4 
    gatsby-remark-images: ^3.1.23 => 3.1.25 
    gatsby-remark-prismjs: ^3.3.14 => 3.3.17 
    gatsby-remark-responsive-iframe: ^2.2.17 => 2.2.22 
    gatsby-remark-smartypants: ^2.1.9 => 2.1.11 
    gatsby-source-filesystem: ^2.1.26 => 2.1.30 
    gatsby-source-git: ^1.0.2 => 1.0.2 
    gatsby-source-graphql: ^2.1.21 => 2.1.21 
    gatsby-transformer-remark: ^2.6.24 => 2.6.27 
    gatsby-transformer-sharp: ^2.2.16 => 2.2.20 
  npmGlobalPackages:
    gatsby-cli: 2.7.40
```

**Comment by ehowey** [comment]
We tracked this down to fsEvents, see this PR, https://github.com/fsevents/fsevents/pull/290

With caution, you may want to try deleting your yarn.lock and rebuilding a fresh node_modules and lock file. If you get a new version of fsEvents this should fix it for you.  You can also dig into your lock files, you should be resolving v2.1.1 or later of fsEvents.

**Comment by cyberwombat** [comment]
I rebuild my `noide_modules` - my yarn.lock shows 2 fsevents in place and one is 1.2.9. I also 
 get a message about outdated `fsevents` but its triggered by gatsby and jest both of which recent?
```
warning gatsby > babel-plugin-add-module-exports > chokidar > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
warning jest > jest-cli > @jest/core > jest-haste-map > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
```

[here](https://gist.github.com/cyberwombat/9ca80631f3d832be4fff2fd35aa19385) is a gist w my package.json and yarn.lock

**Comment by cyberwombat** [comment]
I deleted gatsby and jest and readded them to latest. Still have same fsevents but no warnings. Looks like jest is the one adding 1.2.9 now. I will test things out with this setup. If it freezes I will try it with jest removed and report. Stay tuned.

**Comment by cyberwombat** [comment]
Still testing. Been focused on side projects but am coming back for full testing in a couple weeks.
