### ISSUE TITLE
Intermittent failures for gatsby-transformer-screenshot

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#19452]
## Description

The screenshot service used by gatsby-transformer-screenshot is incorrectly marking sites as offline, resulting in missing screenshots.

Perhaps the screenshot service is incorrectly caching failed screenshots?

### Steps to reproduce

Check a recent build log such as https://circleci.com/gh/gatsbyjs/gatsby/272289

### Expected result

Online sites should have screenshots taken

### Actual result

Many sites are reported as offline, despite being online. e.g.

`warning Site showcase entry "https://themes.lekoarts.de" seems offline. Skipping.`

### Environment

n/a

**Comment by danisal** [comment]
Is there an update on this issue? Having the same problem
