### ISSUE TITLE
Add these sites to the showcase

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#19466]
In case they aren't already in there 

- [x] Particle (https://www.particle.io/)
- [ ] Rollbar (http://rollbar.com/)
- [ ] EQX (https://digitalexperience.equinox.com/)
- [ ] WagWalking (https://wagwalking.com/)
- [ ] Firstborn (https://www.firstborn.com/)

**Comment by Qovaros985** [comment]
particle.io is already in there

**Comment by mubarak23** [comment]
I want to contribute to open source using this issue, any guides
