### ISSUE TITLE
Gatsby-source-drupal installation error

### ISSUE THREAD

**Issue by Danishkhurshid** [gatsbyjs/gatsby#19463]
## Description

On adding drupal-source plugin with "npm install --save gatsby-source-drupal" it is throwing an error of package not found.

### Steps to reproduce

Add drupal-sorce plugin to your gatsby project to reproduce the issue. 

### Expected result

It is trying to fetch the package from "https://registry.npmjs.org/gatsby-source-drupal/-/gatsby-source-drupal-3.3.4.tgz" when it should fetch it from "https://registry.npmjs.org/gatsby-source-drupal/gatsby-source-drupal-3.3.4.tgz"  Note the difference between the 2 urls. 

<img width="932" alt="Screenshot 2019-11-12 at 5 55 27 PM" src="https://user-images.githubusercontent.com/19993386/68740578-652ed480-0611-11ea-9976-7acf5c00baf7.png">

### temporary fix
You can download the package from the above url and add it as a local dependency.

**Comment by wardpeet** [comment]
I don't have an issue running `npm install --save gatsby-source-drupal`, I would check your npm settings and see if you have any other issues.

Thanks so much for opening this issue! As stated, this is slightly tangential to Gatsby, and it seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪
