### ISSUE TITLE
Document the usage of design tokens

### ISSUE THREAD

**Issue by thecodingaviator** [gatsbyjs/gatsby#19468]
## Summary

At the moment, the [design tokens](https://www.gatsbyjs.org/guidelines/design-tokens/) page does not really cover how the tokens are used on the website. For beginners with absolutely no familiarity to the codebase, this poses a problem as the text on the page is very _convoluted_

**Comment by wardpeet** [comment]
Hey, it's still a work in progress. At the moment it's a list of all available tokens. I'm unsure if it's worth documenting at this point. You can search inside our codebase to see how they are used.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
