### ISSUE TITLE
 ERROR #85907  GRAPHQL

### ISSUE THREAD

**Issue by JaybeeClassical** [gatsbyjs/gatsby#19477]
## Description
C:\Users\Jaybee\Desktop\Projects\IamJude>gatsby develop
success open and validate gatsby-configs - 0.715 s
success load plugins - 32.864 s
success onPreInit - 0.377 s
success initialize cache - 0.374 s
success copy gatsby files - 2.561 s
success onPreBootstrap - 0.183 s
Starting to fetch data from Contentful
Fetching default locale
default locale is : en-US
contentTypes fetched 1
Updated entries  5
Deleted entries  0
Updated assets  12
Deleted assets  0
Fetch Contentful data: 22835.375ms
success source and transform nodes - 24.890 s
success Add explicit types - 0.153 s
success Add inferred types - 0.687 s
success Processing types - 0.541 s
success building schema - 2.422 s
success createPages - 0.685 s
success createPagesStatefully - 1.132 s
success onPreExtractQueries - 0.502 s
success update schema - 0.409 s

 ERROR #85907  GRAPHQL

There was an error in your GraphQL query:

- Unknown field 'allMarkdownRemark' on type 'Query'.

File: src\pages\portfolio.js

success extract queries from components - 3.752 s
success write out requires - 0.605 s
success write out redirect data - 0.248 s
warn The icon(src/images/avataaars.png) you provided to 'gatsby-plugin-manifest' is not square.      
The icons we generate will be square and for the best results we recommend you provide a square icon.

success Build manifest and related icons - 1.121 s
success onPostBootstrap - 1.398 s
⠀
info bootstrap finished - 172.149 s
⠀
success run static queries - 0.142 s
success run page queries - 3.981 s — 12/12 3.20 queries/second
success start webpack server - 14.344 s — 1/1 0.66 pages/second
 ERROR  Failed to compile with 1 errors                                                                                            12:47:53 PM⠀
 error  in ./src/pages/portfolio.js
⠀
Module Error (from ./node_modules/eslint-loader/index.js):

C:\Users\Jaybee\Desktop\Projects\IamJude\src\pages\portfolio.js
  67:5  error  Cannot query field "allMarkdownRemark" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 2:965-1047
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false C://Users//Jaybee//Desktop//Projects//IamJude//.cache//app
⠀
× ｢wdm｣:
ERROR in ./src/pages/portfolio.js
Module Error (from ./node_modules/eslint-loader/index.js):

C:\Users\Jaybee\Desktop\Projects\IamJude\src\pages\portfolio.js
  67:5  error  Cannot query field "allMarkdownRemark" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 2:965-1047
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false C://Users//Jaybee//Desktop//Projects//IamJude//.cache//app
i ｢wdm｣: Failed to compile.

### Environment
Windows 10 OS
Using VS code as Text Editor 

Please i need help

**Comment by sidharthachatterjee** [comment]
Hey @JaybeeClassical 

Can you please post a minimal reproduction? Here are steps on how to do that 

https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/
