### ISSUE TITLE
Add CodeSandbox CI to the repo

### ISSUE THREAD

**Issue by MichaelDeBoey** [gatsbyjs/gatsby#19482]
CodeSandbox made their CI public, so I think it would be nice to add it to the repo.

https://codesandbox.io/post/codesandbox-ci-embeds

**Comment by wardpeet** [comment]
Thanks for raising this issue so quickly. We're already talking to codesandbox to see if we can set it up.

**Comment by wardpeet** [comment]
Codesandbox isn't supporting containers yet in CI mode so we won't be able to use it yet.
