### ISSUE TITLE
Any way to disable Gatsby returning to scroll position on refresh?

### ISSUE THREAD

**Issue by notbrian** [gatsbyjs/gatsby#19488]
## Description

I don't want Gatsby to save the scroll position on refresh, instead I want it to start at the top of the page. 

I tried using shouldUpdateScroll() returning false in `gatsby-browser.js` but that doesn't seem to disable this functionality. 

`exports.shouldUpdateScroll = () => {
  return false;
};
`

### Expected result

Disables Gatsby starting on the previous scroll position on a refresh. 

### Actual result

Gatsby stays at the same scroll position on refresh

**Comment by wardpeet** [comment]
Hi @notbrian !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

I'm thinking that you're hitting the default browser behavior. Please have a look at https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration

Thanks for using Gatsby! 💜

**Comment by notbrian** [comment]
Hey @wardpeet I couldn't get that route to work so I just decided to scroll the window to the top of the page in my `gatsby-browser.js` on initial client render.

```
exports.onInitialClientRender = () => {
  window.scrollTo(0, 0);
};
```

**Comment by sidharthachatterjee** [comment]
`shouldUpdateScroll` not working is likely a bug. Thanks @notbrian 

Please post a reproduction if you have one.

**Comment by notbrian** [comment]
> `shouldUpdateScroll` not working is likely a bug. Thanks @notbrian
> 
> Please post a reproduction if you have one.

I think I was reading something that `shouldUpdateScroll`only runs when navigating to a new page, not refresh of the same page. My application behaved like this.

**Comment by sidharthachatterjee** [comment]
> I think I was reading something that shouldUpdateScroll only runs when navigating to a new page, not refresh of the same page. My application behaved like this.

This is true indeed. `shouldUpdateScrollonly` is only called on navigation. 

Perhaps return `[0, 0]` to reset back to the top? 

```exports.shouldUpdateScroll = () => { return [0, 0] }```

Curious if this works. Let me know!

**Comment by alainpatrick** [comment]
@sidharthachatterjee it doesn't work.
nothing works so far.

I tried this:

`export function shouldUpdateScroll() {
  return [0, 0]
}`

`export function onInitialClientRender() {
  window.scrollTo(0, 0)
}`

**Comment by chandlervdw** [comment]
I can get `shouldUpdateScroll()` to fire in `gatsby-browser` but neither returning `false` nor firing `window.scrollTo(0,0,)` does what it claims it should.

**Comment by chandlervdw** [comment]
After digging, I've realized that when `shouldUpdateScroll()` fires, `window` always has `scrollY: 0` and `scrollX: 0`, regardless of how far down the screen I have scrolled. Thusly, `window.scrollTo(0,0)` does nothing... so something isn't updating the scroll position of `window` within gatsby.

Personally, I think this feature is a bit of a black sheep. Everything else about gatsby makes so much sense but I've fought this one for far too long just to try and restore what I would call normal functionality...

**Comment by dnakhla** [comment]
@chandlervdw check to see if perhaps you have a div with 'overflow' set to auto or scroll. I tihnk this would require you call ScrollTo on the div not the window

**Comment by zslabs** [comment]
Not sure if it's appropriate to re-open this one or just leave https://github.com/gatsbyjs/gatsby/issues/19480 open, but that link has a reproduction repo (just updated the deps as well to confirm this is still an issue).

**Comment by Ys-sudo** [comment]
For me adding this `"gatsby-react-router-scroll": "3.0.0",` to `package.json` dependencies fixed the issue.

**Comment by SwatDoge** [comment]
> For me adding the `"gatsby-react-router-scroll": "3.0.0",` to `package.json` dependencies fixed the issue.

Wait, why does this work!?

**Comment by Ys-sudo** [comment]
> > For me adding the `"gatsby-react-router-scroll": "3.0.0",` to `package.json` dependencies fixed the issue.
> 
> Wait, why does this work!?

I think it is linked to the scroll offset set in sessionStorage, this package adds custom scroll behavior that overwrites gatsby's original settings. **For my use case this was causing problems with anchor links, adding this package fixed the bug and anchor links started to work properly.**

**Comment by Alicino88** [comment]
What has worked for me is to add the following css to the main css file:
```
:root {
  scroll-behavior: auto !important;
}
```

**Comment by enphnt** [comment]
i know this is closed but if others find themselves here, like @Alicino88, I found that for me the issues are caused by setting `scroll-behavior: auto !important;`. Although in my case it had been set like so:
```css
  html {
      scroll-behavior: smooth;
  }
```

I found that I could still use smooth scroll by wrapping the specific page I wanted in a wrapper class like so: 
```css
.landing-page {
  overflow-y: scroll;
  scroll-behavior: smooth;
  display: block;
  height: 100vh;
}
```

in this case, the index page needed to be wrapped: 
```jsx
const IndexPage = () => (
  <div className={landingPage}> 
    {children}
  </div>
);
```

you may need to also offset the scroll positions, say for a nav bar. just add `scroll-padding-top: 50px;` to the class where the `px` is your nav bar height.

**Comment by therealgilles** [comment]
Here is what I ended up with for the scroll behavior I wanted:

```TSX
// gatsby-browser.tsx
export const onRouteUpdate = ({ location, prevLocation }) => {
  if (!prevLocation && !location.hash) {
    setTimeout(() => window.scrollTo({ top: 0, left: 0, behavior: 'instant' }), 0)
  }
}

export const shouldUpdateScroll = ({ routerProps: { location }, getSavedScrollPosition }) => {
  window.history.scrollRestoration = 'manual'
  const currentPosition = getSavedScrollPosition(location)

  setTimeout(() => {
    if (location.hash) {
      const item = document.querySelector(`${location.hash}`)
      item?.scrollIntoView({ behavior: 'smooth' })
    } else {
      window.scrollTo({
        top: currentPosition[1],
        left: currentPosition[0],
        behavior: 'instant',
      })
    }
  }, 0)

  return false
}
```

I have set the CSS scroll behavior as `smooth` by default:
```CSS
  html {
      scroll-behavior: smooth;
  }
```
