### ISSUE TITLE
Anchors not working as expected when using shouldUpdateOnScroll

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#19480]
## Description

Anchor links are not responding as normal when using the `shouldUpdateOnScroll` method within `gatsby-browser.js`. The page does not move at all.

### Steps to reproduce

1. Clone https://github.com/zslabs/gatsby-anchor
2. `gatsby develop`
3. Visit `New Beginnings` blog post
4. Attempt to interact with `[Bottom](#bottom)` (at the top of the article) and `[Top](#top)` (at the bottom). Page does not shift.
5. Visit `gatsby-browser.js` and remove the `shouldUpdateOnScroll` method; which for this minimal example just returns `true` as the [docs state](https://www.gatsbyjs.org/docs/browser-apis/#shouldUpdateScroll) as valid (my actual implementation returns false in some cases, but this shows the issue).
6. Anchors should work as normal.

This works fine in a previous version of Gatsby; so I'd imagine this is a more recent regression. Potentially related to https://github.com/gatsbyjs/gatsby/pull/16328 cc @wardpeet @stefanprobst 

### Expected result

Anchors should work as normal when interacting with `shouldUpdateScroll` method.

### Actual result

Nopers.

### Environment

```
  System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.0.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.npm-packages/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11
    gatsby-image: ^2.2.31 => 2.2.31
    gatsby-plugin-feed: ^2.3.20 => 2.3.20
    gatsby-plugin-google-analytics: ^2.1.25 => 2.1.25
    gatsby-plugin-manifest: ^2.2.27 => 2.2.27
    gatsby-plugin-offline: ^3.0.19 => 3.0.19
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14
    gatsby-plugin-sharp: ^2.2.37 => 2.2.37
    gatsby-plugin-typography: ^2.3.16 => 2.3.16
    gatsby-remark-copy-linked-files: ^2.1.29 => 2.1.29
    gatsby-remark-images: ^3.1.30 => 3.1.30
    gatsby-remark-prismjs: ^3.3.22 => 3.3.22
    gatsby-remark-responsive-iframe: ^2.2.26 => 2.2.26
    gatsby-remark-smartypants: ^2.1.15 => 2.1.15
    gatsby-source-filesystem: ^2.1.36 => 2.1.36
    gatsby-transformer-remark: ^2.6.33 => 2.6.33
    gatsby-transformer-sharp: ^2.3.3 => 2.3.3
  npmGlobalPackages:
    gatsby-cli: 2.8.9
```

**Comment by zslabs** [comment]
Not exactly sure if this is related, but noticed https://github.com/gatsbyjs/gatsby/issues/18758 and wanted to add it as a note.

**Comment by zslabs** [comment]
https://github.com/gatsbyjs/gatsby/issues/19488 and  https://github.com/gatsbyjs/gatsby/issues/18758 seem to be related to this one. @LekoArts did we make any headway on the fix that you mentioned in [this](https://github.com/gatsbyjs/gatsby/issues/18758)?

**Comment by zslabs** [comment]
I just updated the deps to the latest versions to confirm this is still an issue.

**Comment by zslabs** [comment]
Should we be using `getSavedScrollPosition` and not `true` for default behavior as mentioned in https://github.com/gatsbyjs/gatsby/issues/20641#issuecomment-575190937 ?

**Comment by lewislbr** [comment]
I also have this issue. Any news?

**Comment by zslabs** [comment]
> I also have this issue. Any news?

I ended up using the following:

```
export const shouldUpdateScroll = ({
  routerProps: { location },
  getSavedScrollPosition,
}) => {
  const currentPosition = getSavedScrollPosition(location)

  // Don't update scroll position on certain pages
  // @NOTE This is just an internal function I run, so stub in your own logic here
  if (scrollCheck(location)) {
    return false
  }

  window.scrollTo(...(currentPosition || [0, 0]))
}
```

**Comment by lewislbr** [comment]
Thanks @zslabs, I’ll try that by now!

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v3 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

[reproduction]: https://gatsby.dev/reproduction

**Comment by anesask** [comment]
Any updates on this issue?
