### ISSUE TITLE
Gatsbygram clone won't load for some users on cell— gatsby-plugin-offline serviceworker issue?

### ISSUE THREAD

**Issue by dustinhorton** [gatsbyjs/gatsby#19496]
## Description

I've built several Gatsby sites without much issue. However I wanted to put up a quick landing page, and used the gatsbygram starter.

I've got two users for whom the site refuses to load, only on their phones, and only on cellular—not wifi. Sounds—wrong, but I witnessed first-hand.

Having not experienced issues like this before, I'm assuming it's a gatsby-plugin-offline issue.

The site barely starts loading and just stops, and the server logs report nothing:

![IMG_0715](https://user-images.githubusercontent.com/378165/68823920-36d9e500-0663-11ea-8907-fd2b25eebbd5.png)

Things I've tried, each followed by them clearing their browser cache:

- Removing the [offline plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/)
- Adding the [remove serviceworker plugin](https://www.npmjs.com/package/gatsby-plugin-remove-serviceworker)
- Removing both plugins
- Wiping everything from the server, rebuilding, re-deploying

### Steps to reproduce

Site is a very light gatsbygram clone, deployed at http://flowmetalfab.com

### Expected result

Site should load everywhere

### Actual result

Site loads everywhere but on cell networks from some users' phones.

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.0.1 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/n/bin/yarn
    npm: 6.12.0 - ~/n/bin/npm
  Languages:
    Python: 2.7.9 - /Users/Dustin/.pyenv/shims/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 69.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.0.0 => 2.17.2
    gatsby-image: ^2.0.5 => 2.2.29
    gatsby-plugin-glamor: ^2.0.5 => 2.1.13
    gatsby-plugin-google-analytics: ^2.0.5 => 2.1.23
    gatsby-plugin-manifest: ^2.0.2 => 2.2.23
    gatsby-plugin-offline: ^3.0.16 => 3.0.16
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.13
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-root-import: ^2.0.4 => 2.0.5
    gatsby-plugin-sass: ^2.1.14 => 2.1.20
    gatsby-plugin-sharp: ^2.0.5 => 2.2.32
    gatsby-plugin-typography: ^2.2.0 => 2.3.14
    gatsby-source-filesystem: ^2.0.1 => 2.1.33
    gatsby-transformer-json: ^2.1.1 => 2.2.15
    gatsby-transformer-sharp: ^2.1.1 => 2.3.0
  npmGlobalPackages:
    gatsby-cli: 2.5.15
    gatsby: 2.0.118
```

**Comment by wardpeet** [comment]
It seems like a really hard issue to solve from our side, it looks like the service worker is still active on the phone and is misbehaving.

I'm unsure if we can help you with this issue as it's a service worker issue.and not really a gatsby issue.

**Comment by dustinhorton** [comment]
Understood—I haven't really followed gatsby-plugin-offline issues but i know there were a lot of them in this realm before, so was hoping some others might chime in with some advice how to actually be rid of it.

**Comment by dustinhorton** [comment]
DNS issue—really weird.
