### ISSUE TITLE
gatsby-transformer-remark doesn't work on Windows

### ISSUE THREAD

**Issue by 8ctopotamus** [gatsbyjs/gatsby#1949]
I get "unknown field" errors when trying to use gatsby-transformer-remark on Windows. 

I followed these instructions to set up my machine: https://www.gatsbyjs.org/docs/gatsby-on-windows/

Any suggestions?

**Comment by KyleAMathews** [comment]
You probably hit this https://github.com/gatsbyjs/gatsby/pull/1945

Try upgrading to the latest versions of packages and see if things work again.

**Comment by 8ctopotamus** [comment]
Thanks for responding. I checked out the link, but am not sure what I am supposed to do?

**Comment by 8ctopotamus** [comment]
Thanks! it's working now
