### ISSUE TITLE
Contentful reference fields only returns data for one reference at a time

### ISSUE THREAD

**Issue by dnlmzw** [gatsbyjs/gatsby#19493]
## Description
I'm executing a query through GraphiQL to get data from Contentful but I only get a single reference at a time.

Basically I'm running the following query:
```{
  contentfulPage(frontpage: {eq: true}) {
    title
    sections {
      id
      title
      pretitle
      moduleReference {
        __typename
      }
    }
  }
}
```
Both "sections" and "moduleReference" is set to the content type "Reference" inside Contentful, but I'm only getting the following data:
```{
  "data": {
    "contentfulPage": {
      "title": "Forside",
      "sections": [
        {
          "id": "250b9abd-2984-57a7-9833-2154d51fc72e",
          "title": "Vi er firmanavn",
          "pretitle": "Om os",
          "moduleReference": null
        },
        {
          "id": "71f9195d-68cb-5052-8ee6-d29f21525116",
          "title": "Faglige specialister",
          "pretitle": "Kompetencer",
          "moduleReference": {
            "__typename": "ContentfulModuleList"
          }
        },
        {
          "id": "14e8d309-4646-5579-b59a-f0dca0817ff7",
          "title": "Vi arbejder med",
          "pretitle": "Referencer",
          "moduleReference": null
        },
        {
          "id": "091a133e-c3ce-5be9-97be-b75b716ed6ec",
          "title": "Start processen",
          "pretitle": "Kontakt",
          "moduleReference": null
        }
      ]
    }
  }
}
```

In Contentful I can see that moduleReference is populated on all 4 sections. However, I only get the __typename for one of them at a time.

If I remove the data in Contentful for the node with the pretitle "Kompetencer" the moduleReference's __typename for the "section" with the pretitle: "Om os" all of a sudden appears, which tells me that the data is there. I can't get it to return "moduleReference" for two nodes at the same time.

I've tried grouping it with `... on Node` but the outcome is the same: I only get the moduleReference on one of the items.
```
{
  contentfulPage(frontpage: {eq: true}) {
    title
    sections {
      id
      title
      pretitle
      moduleReference {
        __typename
        ... on Node {
          ... on ContentfulModuleRichText {
            id
          }
          ... on ContentfulModuleList {
            id
          }
        }
      }
    }
  }
}
```

```
{
  "data": {
    "contentfulPage": {
      "title": "Forside",
      "sections": [
        {
          "id": "250b9abd-2984-57a7-9833-2154d51fc72e",
          "title": "Vi er Netgen",
          "pretitle": "Om os",
          "moduleReference": null
        },
        {
          "id": "71f9195d-68cb-5052-8ee6-d29f21525116",
          "title": "Faglige specialister",
          "pretitle": "Kompetencer",
          "moduleReference": {
            "__typename": "ContentfulModuleList",
            "id": "9a51f55f-c59f-5cb9-ab29-f1dfcbd9c6bb"
          }
        },
        {
          "id": "14e8d309-4646-5579-b59a-f0dca0817ff7",
          "title": "Vi arbejder med",
          "pretitle": "Referencer",
          "moduleReference": null
        },
        {
          "id": "091a133e-c3ce-5be9-97be-b75b716ed6ec",
          "title": "Start processen",
          "pretitle": "Kontakt",
          "moduleReference": null
        }
      ]
    }
  }
}
```

### Expected result

All of the "moduleReference" should return the __typename instead of null

### Actual result

Only one of the "moduleReference" returns the __typename at a time

### Environment

  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.8 - /usr/local/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11
    gatsby-image: ^2.2.31 => 2.2.31
    gatsby-plugin-manifest: ^2.2.27 => 2.2.27
    gatsby-plugin-offline: ^3.0.19 => 3.0.19
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14
    gatsby-plugin-sass: ^2.1.21 => 2.1.21
    gatsby-plugin-sharp: ^2.2.37 => 2.2.37
    gatsby-source-contentful: ^2.1.56 => 2.1.56
    gatsby-source-filesystem: ^2.1.36 => 2.1.36
    gatsby-transformer-sharp: ^2.3.3 => 2.3.3
  npmGlobalPackages:
    gatsby-cli: 2.8.9

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by dnlmzw** [comment]
I found that my issue was the same as [https://github.com/gatsbyjs/gatsby/issues/10090](#10090)
