### ISSUE TITLE
[gatsby-remark-prismjs] Add new option to avoid warning "code block or inline code language not specified in markdown" when not specifying the language of inline-code

### ISSUE THREAD

**Issue by sergkudinov** [gatsbyjs/gatsby#19508]
## Summary

A boolean option for the plugin `gatsby-remark-prismjs` which defines whether or not to throw a warning `code block or inline code language not specified in markdown` when the inline code language is not specified.

### Basic example

In the `gatsby-config.js`:
```js
{
  resolve: `gatsby-remark-prismjs`,
  options: {
    throwInlineCodeLanguageWarning: false
  },
},
```

### Motivation

When a website has multiple markdown sources (like technical blog website) with a lot of inline code it is quite difficult to specify a language to the each one. At the same time you want using highliting of inline code by keeping the option `noInlineHighlight: false` as a default. The option like `throwInlineCodeLanguageWarning: false` (by default it is `true`) could disable throwing the unwanted warning.

For example, we have a markdown like:

```md
The Rook cluster will take some time to deploy,
while it pulls the Rook images and deploy the pods. 
After a few minutes the output of `kubectl get pods -n rook-ceph`
should look like this.
```

When not specifying language like here:
```
`kubectl get pods -n rook-ceph`
```
we won't get the warning `code block or inline code language not specified in markdown`.

Now we have to specify it like this:
```
`bash›kubectl get pods -n rook-ceph`
```
or
```
`bash±kubectl get pods -n rook-ceph`
```

**Comment by pjeziorowski** [comment]
Hi, 

if this request is approved then I could take this on.

**Comment by LekoArts** [comment]
Thank you for opening this!

You can implement this behavior on your own by writing a remark plugin:
https://www.gatsbyjs.org/docs/remark-plugin-tutorial/

Be sure to place it after the prismjs entry in gatsby-config.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by fabiosantoscode** [comment]
For future readers and the OP as well:

If you set `noInlineHighlight: true` in your gatsby-remark-prismjs options, it will not even attempt to highlight inline code blocks. So no warning.
