### ISSUE TITLE
Web.config file creation

### ISSUE THREAD

**Issue by KoushikGoramane** [gatsbyjs/gatsby#19505]
I deployed the simple Gatsby application on Azure but if I click on the link the website is not opening , How to to write the web.config file for this?

**Comment by wardpeet** [comment]
Hey,

Sadly I don't know enough about azure to be of any help.

I found these resources that might help you
- https://www.gatsbyjs.org/blog/2018-11-05-deploying-gatsby-to-azure/
- https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

Thank you for opening this, @KoushikGoramane
