### ISSUE TITLE
[gatsby-remark-images] Add new option to always wrap images in <figure>

### ISSUE THREAD

**Issue by emmenko** [gatsbyjs/gatsby#19506]
## Summary

Allow to pass a new configuration option to the `gatsby-remark-images` plugin to wrap the HTML output in `<figure>` element, **independent of the existence of an image caption**.

### Basic example

At the moment, the `<figure>` element is rendered only whenever there is a caption:

https://github.com/gatsbyjs/gatsby/blob/38af21a17ed88554b1332c29dafd5dade4e9d7bd/packages/gatsby-remark-images/src/index.js#L333-L340

According to the [`<figure>` HTML documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure), the `<figcaption>` is optional, so having only `<figure>` is semantically valid.

The option could be something like `wrapFigureOnlyWithCaptions` (_defaults to `true`_ for backwards compatibility).

### Motivation

The reason for this is mostly for styling purposes. In our case we want to style the `<figure>` element and have a consistent style not matter if there is a caption or not.

> I can open a PR and work on this if the new option is accepted.

**Comment by blainekasten** [comment]
@emmenko I definitely understand the need for consistent styling. Before we consider a default figure wrapping, we're going to internally test some the accessibility of doing that.

Aside from that -- does the `wrapperStyle` option not support this?
https://www.gatsbyjs.org/packages/gatsby-remark-images/#options

**Comment by emmenko** [comment]
Unfortunately the `wrapperStyle` only injects some inline styles to the default wrapper container.

Alright, I’ll wait for some feedback from you on how to proceed. Thanks 🙏

**Comment by blainekasten** [comment]
Can you explain in a bit more detail what you're trying to achieve and why `wrapperStyle` can't achieve it?

**Comment by emmenko** [comment]
Sure, let me try to explain our use case. Our images should have a "frame" style which, in case of a caption, the image title should be included within the "frame". See below:

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/1110551/68890614-88e04080-071f-11ea-814d-6b35e67d5300.png">

However, when an image does not have a title, we don't want to show the caption, but we still need to show the "frame". I manage to do that by hacking a bit around the styles since the `<figure>` wrapper is not there anymore:

<img width="1616" alt="image" src="https://user-images.githubusercontent.com/1110551/68890662-b2996780-071f-11ea-8d66-3b342c1e1ac4.png">

Now, when I have a smaller image though, it becomes even more problematic to have this "frame"

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/1110551/68890876-17ed5880-0720-11ea-8d21-3f5fc708d592.png">

All those problems would be solve by keeping the `<figure>` wrapper around all images.

Using the `wrapperStyle` won't help, as I need a real container element.

---

Hopefully this gives you a better understanding of the issue. Thanks

**Comment by emmenko** [comment]
I opened a PR as suggested by the stale bot.

**Comment by blainekasten** [comment]
Closing this as we discussed further in the PR and will not be accepting a code change for this feature. ❤️
