### ISSUE TITLE
gatsby-transformer-asciidoc include directive looks in wrong folder

### ISSUE THREAD

**Issue by benfreke** [gatsbyjs/gatsby#19502]
### Description

I'm using a Docker based environment to do this work. It's a Node based image that I've installed the gatsby cli tools into.

I'm using the `include` directive to reuse a code snippet in the file `content/blog/2019/november/creating-a-new-project.adoc`

I've also ensured I've set `safe: 'safe'` settings in config for this to work.

Specifically, I've extracted a bash script out of my adoc file and into a .bash file.

I then used this code to include it: `include::creating-a-new-project.bash[tag=creates]`

That fails with the error message of `asciidoctor: ERROR: <stdin>: line 14: include file not found: /app/creating-a-new-project.bash`

According to my IDE (PhpStorm), this is the correct way to reference the file. I would expect links in an include to be relative to the page that it is included in, not the project directory.

### Steps to reproduce

**Shows the include directive not working the way it should.**

`git clone https://gitlab.com/benfreke/blog.git wrongway && cd wrongway && git checkout 2f3205e9c94c094fdeb054901620ca0b595aa487 && docker-compose up install && docker-compose up develop`

**Shows the include directive working the way it should.**

`git clone https://gitlab.com/benfreke/blog.git rightway && cd rightway && git checkout b66b3036d400d4d447de82b41578cd19942518de && docker-compose up install && docker-compose up develop`

If you're not using docker, simply replace the `docker-compose up install` with `npm install` and `docker-compose up develop` with `gatsby develop`

### Expected result

Include paths should be relative to the file being edited

### Actual result

Include paths are relative to the root of the project

### Environment

`gatsby info --clipboard` didn't provide any output sorry within my docker container sorry.

**Comment by benfreke** [comment]
I had hoped I'd get an official response and fix. I'll give it a try myself to fix, so I'm reopening this while I attempt that.

**Comment by wardpeet** [comment]
Hey @benfreke,

Sorry for the late response, I've been digging into this issue a little to see what's going on. The base directory is by default the gatsby root, that's why you have to add the full path instead of a relative path.

If you would like to fix this a good idea is to add a baseDir option to ascii-transformer that excepts a string or a function. The function will receive the ascii node where you can get the file directory from.

For your use case the baseDir function would look like
```
baseDir: node => node.dir
```

Does this make sense?

**Comment by benfreke** [comment]
Thanks for the reply.

Yes it makes sense, I'll see how I get on with it.
