### ISSUE TITLE
[gatsby-transformer-remark] excerpt(format: HTML) returns null in some cases

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#19513]
## Description

For some inputs `excerpt(format: HTML)` crashes and return `null` (without crashing entire query run)

### Steps to reproduce

Minimal repro repo: https://github.com/pieh/html-excerpt-error-repro

Steps: 

```
git clone https://github.com/pieh/html-excerpt-error-repro.git
cd html-excerpt-error-repro
npm install
gatsby develop
```

Go to `http://localhost:8000/___graphql` and use query:

```graphql
{
  markdownRemark {
    excerpt(format:HTML)
  }
}
```

You should see following in result pane:
```
{
  "errors": [
    {
      "message": "Cannot read property 'value' of undefined",
      "locations": [
        {
          "line": 6,
          "column": 5
        }
      ],
      "path": [
        "markdownRemark",
        "excerpt"
      ],
      "stack": [
        "TypeError: Cannot read property 'value' of undefined",
        "    at getExcerptAst (/Users/misiek/test/html-excerpt-error-repro/node_modules/gatsby-transformer-remark/extend-node-type.js:383:90)",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
      ]
    }
  ],
  "data": {
    "markdownRemark": {
      "excerpt": null
    }
  }
}
```

This seems to point to this part https://github.com/gatsbyjs/gatsby/blob/2acda68708b9731c7ac0e98cc355016c55aefcd5/packages/gatsby-transformer-remark/src/extend-node-type.js#L375-L380 (based on stack trace and transpiled code: https://unpkg.com/browse/gatsby-transformer-remark@2.6.34/extend-node-type.js) 

This was discovered during pairing session with @stephencweiss, and excerpt not showing up seems like anomaly. Markdown file for it is https://github.com/stephencweiss/personal-blog/blob/master/content/blog/2019-11-13/repeat-command-unix.md (and it's used in minimal reproduction repo)

### Expected result

See actual excerpt

### Actual result

Excerpt is `null`

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.3/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Firefox: 70.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11
    gatsby-image: ^2.2.31 => 2.2.31
    gatsby-plugin-feed: ^2.3.20 => 2.3.20
    gatsby-plugin-google-analytics: ^2.1.25 => 2.1.25
    gatsby-plugin-manifest: ^2.2.27 => 2.2.27
    gatsby-plugin-offline: ^3.0.19 => 3.0.19
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14
    gatsby-plugin-sharp: ^2.2.37 => 2.2.37
    gatsby-plugin-typography: ^2.3.16 => 2.3.16
    gatsby-remark-copy-linked-files: ^2.1.29 => 2.1.29
    gatsby-remark-images: ^3.1.30 => 3.1.30
    gatsby-remark-prismjs: ^3.3.22 => 3.3.22
    gatsby-remark-responsive-iframe: ^2.2.26 => 2.2.26
    gatsby-remark-smartypants: ^2.1.15 => 2.1.15
    gatsby-source-filesystem: ^2.1.36 => 2.1.36
    gatsby-transformer-remark: ^2.6.33 => 2.6.33
    gatsby-transformer-sharp: ^2.3.3 => 2.3.3
  npmGlobalPackages:
    gatsby-cli: 2.8.7
    gatsby-dev-cli: 2.5.36
```

**Comment by stephencweiss** [comment]
@pieh -- I wrote it up too: https://github.com/gatsbyjs/gatsby/issues/19511. You can close mine.

The only thing I discovered that I think this ticket hasn't noted yet is that it appears to be due to the image.

**Comment by pieh** [comment]
Oh snap, we doubled on the issue creation. Yours was first, so probably will keep that one open (we can just copy over the minimal repro I created for this one so it's hopefully easier to debug)

**Comment by pieh** [comment]
Copied minimal repro to your issue, and closing this one as duplicate
