### ISSUE TITLE
Is it possible to use React-Router inside of Gatsby v2

### ISSUE THREAD

**Issue by seanemmer** [gatsbyjs/gatsby#19518]
I understand that it is possible to create client-only routes using the @reach/router implementation within Gatsby:

https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/

However, given that React Router will be merging with @reach/router (https://reacttraining.com/blog/react-router-v5-1/) I am attempting to use React Router across my entire project including my Gatsby app.

I have attempted to set up React Router within Gatsby using the onCreatePage API and the vanilla React-Router BrowserRouter implementation.  While this works in development, Gatsby throws an Invariant Failure during the "building static HTML for pages" step of build.

I would like to know if what I am attempting to do is possible, and if so what the correct implementation path is.

**Comment by wardpeet** [comment]
React-router will work for client-only routes but not for gatsby routes created from the src/pages directory or the createPage API. Also note, including react-router means your bundle now has 2 routers which makes your bundle bigger for no real reason.

checkout https://bundlephobia.com/result?p=react-router@5.1.2

Thank you for opening this, @seanemmer 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by seanemmer** [comment]
Thanks for confirming @wardpeet .

For those looking to go down this path - I was able to get React Router working by using StaticRouter in gatsby-ssr and BrowserRouter in gatsby-browser.

**Comment by WonderPanda** [comment]
@seanemmer Can you share a bit more information about your set up for this? I'm hoping to achieve something similar but am still a bit new to the Gatsby APIs

**Comment by marconucara** [comment]
@seanemmer Can you share more please?

**Comment by Douglasacost** [comment]
interesting. now i'm looking to use that

**Comment by mortscode** [comment]
![](https://media.giphy.com/media/S5n7Wkhhw5A2IrfKER/giphy.gif)

**Comment by codeithuman** [comment]
@mort, try this `NoSSR` component, https://github.com/kadirahq/react-no-ssr. 

Or, you can just implement the component in your local repo and avoid installed another npm dependency. Here is the source for the component. https://github.com/kadirahq/react-no-ssr/blob/master/src/index.js

**Comment by stanleyyuenyiu** [comment]
but how to make mutli language URL? with using react-router, i can easy to do the client routing.

if we are talking to pre generate those page, is it too stupid to generate all language?  (assume url will be /en-us/mypage.html)

for example, if i have 32 language in the application, and the application has 10pages, that means it have to generate 320 pages? and let say some of the page only have 1 translation, but there is many many content, is it worth to do this????????
