### ISSUE TITLE
[gatsby-remark-transformer] excerpt(format: HTML) errors on images

### ISSUE THREAD

**Issue by stephencweiss** [gatsbyjs/gatsby#19511]
## Description

I was working with @pieh and discovered an issue with how Gatsby Remark Transformer creates excerpts for posts. 

Using my blog as an example, the transformer works appropriately for `HTML` on almost all of my posts, though we found at least one error.

![Screen Shot 2019-11-14 at 8 49 37 AM](https://user-images.githubusercontent.com/39878535/68867634-cb703180-06bb-11ea-8648-c4854c6592ce.png)

![Screen Shot 2019-11-14 at 8 39 06 AM](https://user-images.githubusercontent.com/39878535/68866728-754ebe80-06ba-11ea-9ef1-2f826388d131.png)

Some of the experiments I ran to try to narrow this down:
1. Switch from `HTML` to `MARKDOWN` it works:
![Screen Shot 2019-11-14 at 8 41 26 AM](https://user-images.githubusercontent.com/39878535/68866828-9adbc800-06ba-11ea-86c8-11204df1ad89.png)
2. The default `PLAIN` doesn't work because it strips out any code, but it doesn't error
![Screen Shot 2019-11-14 at 8 42 14 AM](https://user-images.githubusercontent.com/39878535/68866999-cfe81a80-06ba-11ea-9be5-46b8d7a84617.png)
3. Remove the Image that would appear in the excerpt. This seems to be where the error occurs and when I remove the image from the first 200 characters (the length of my excerpt), the `HTML` excerpt works as expected. 
![Screen Shot 2019-11-14 at 8 54 03 AM](https://user-images.githubusercontent.com/39878535/68868009-5bae7680-06bc-11ea-9071-c48764c20da5.png)

The query I'm using is:
```graphql
{
  allMarkdownRemark(
    filter:{frontmatter:{title:{eq: "Repeat A Terminal Command In UNIX"}}}, 
    sort: {fields: [frontmatter___date], order: DESC}) {
    edges {
      node {
        excerpt(format: HTML)
        fields {
          slug
        }
        frontmatter {
          date(formatString: "MMMM DD, YYYY")
          publish(formatString: "MMMM DD, YYYY")
          title
        }
      }
    }
  }
}
```

### Steps to reproduce

Minimal repro: 

https://github.com/pieh/html-excerpt-error-repro

```
git clone https://github.com/pieh/html-excerpt-error-repro.git
cd html-excerpt-error-repro
npm install
gatsby develop
```

Go to `http://localhost:8000/___graphql` and use query:

```graphql
{
  markdownRemark {
    excerpt(format:HTML)
  }
}
```

You should see following in result pane:
```
{
  "errors": [
    {
      "message": "Cannot read property 'value' of undefined",
      "locations": [
        {
          "line": 6,
          "column": 5
        }
      ],
      "path": [
        "markdownRemark",
        "excerpt"
      ],
      "stack": [
        "TypeError: Cannot read property 'value' of undefined",
        "    at getExcerptAst (/Users/misiek/test/html-excerpt-error-repro/node_modules/gatsby-transformer-remark/extend-node-type.js:383:90)",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
      ]
    }
  ],
  "data": {
    "markdownRemark": {
      "excerpt": null
    }
  }
}
```

Source site where bug was discovered:

1. Pull down my site: https://github.com/stephencweiss/personal-blog/
2. Install and run `gatsby develop`
3. Look at the excerpt for this post (https://github.com/stephencweiss/personal-blog/blob/master/content/blog/2019-11-13/repeat-command-unix.md) -- it should be blank. To see the post, it should be at `localhost:8000/2019-11-13/repeat-command-unix.md`. You'll note however, on the main page, no blurb appears.

### Expected result

The `HTML` transform should not error on the presence of an image in the transform.

### Actual result

The `HTML` transform errors when there's an image present and nothing is returned. 

### Environment

```shell
npx gatsby info --clipboard

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.13.2 => 2.17.12
    gatsby-image: ^2.0.22 => 2.2.32
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3
    gatsby-plugin-feed: ^2.0.8 => 2.3.20
    gatsby-plugin-google-analytics: ^2.1.1 => 2.1.25
    gatsby-plugin-manifest: ^2.0.5 => 2.2.27
    gatsby-plugin-offline: ^2.0.5 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.0 => 3.1.14
    gatsby-plugin-sharp: ^2.2.1 => 2.2.38
    gatsby-plugin-typography: ^2.2.0 => 2.3.16
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-remark-autolink-headers: ^2.1.0 => 2.1.17
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.1.29
    gatsby-remark-embed-video: ^1.7.0 => 1.7.1
    gatsby-remark-images: ^2.0.4 => 2.0.6
    gatsby-remark-prismjs: ^3.0.0 => 3.3.22
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.2.26
    gatsby-remark-smartypants: ^2.0.5 => 2.1.15
    gatsby-source-filesystem: ^2.1.1 => 2.1.36
    gatsby-transformer-remark: ^2.1.6 => 2.6.34
    gatsby-transformer-sharp: ^2.1.3 => 2.3.4
```

**Comment by pieh** [comment]
Pull request with initial fix is up - https://github.com/gatsbyjs/gatsby/pull/19519
