### ISSUE TITLE
Adding import for axios breaks build

### ISSUE THREAD

**Issue by matrix4123** [gatsbyjs/gatsby#19527]
## Summary

Added axios to my project, works OK with develop. When I try to build the production version if fails.

## Relevant information

Error: 

`failed Building static HTML for pages - 1.648s

 ERROR #95313 

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html

  45 |         children
  46 |       );
> 47 |     }
     | ^
  48 |   );
  49 | };
  50 | 

  WebpackError: C:\projects\ssllc-gatsby2\public\render-page.js:5292

  - index.js:47 Module._compile
    node_modules/@reach/router/es/index.js:47:1

  - index.js:113 Object.Module._extensions..js
    node_modules/@reach/router/es/index.js:113:1

  - index.js:1 Module.load
    node_modules/@reach/router/es/index.js:1:1

  - index.js:16 Module.require
    node_modules/@reach/router/es/index.js:16:50`

If I remove the import of axios line it builds fine... anyone had this issue before? I've updated every package to latest.

### Environment (if relevant)

  System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor             
  Binaries:
    Yarn: 1.17.3 - C:\Users\matri\AppData\Roaming\npm\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.17.13 => 2.17.13 
    gatsby-image: ^2.2.32 => 2.2.32 
    gatsby-plugin-create-client-paths: ^2.1.16 => 2.1.16 
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5 
    gatsby-plugin-manifest: ^2.2.27 => 2.2.27 
    gatsby-plugin-offline: ^3.0.20 => 3.0.20 
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14 
    gatsby-plugin-sharp: ^2.2.38 => 2.2.38 
    gatsby-source-filesystem: ^2.1.36 => 2.1.36 
    gatsby-source-firestore-saphi: ^1.0.4 => 1.0.4 
    gatsby-transformer-sharp: ^2.3.4 => 2.3.4 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: 

`{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "",
  "dependencies": {
    "@firebase/firestore-types": "^1.7.0",
    "axios": "^0.19.0",
    "firebase": "^7.4.0",
    "gatsby": "^2.17.13",
    "gatsby-image": "^2.2.32",
    "gatsby-plugin-create-client-paths": "^2.1.16",
    "gatsby-plugin-html-attributes": "^1.0.5",
    "gatsby-plugin-manifest": "^2.2.27",
    "gatsby-plugin-offline": "^3.0.20",
    "gatsby-plugin-react-helmet": "^3.1.14",
    "gatsby-plugin-sharp": "^2.2.38",
    "gatsby-source-filesystem": "^2.1.36",
    "gatsby-source-firestore-saphi": "^1.0.4",
    "gatsby-transformer-sharp": "^2.3.4",
    "prop-types": "^15.7.2",
    "query-string": "^6.9.0",
    "react": "^16.11.0",
    "react-collapsible": "^2.6.0",
    "react-dom": "^16.11.0",
    "react-helmet": "^5.2.1"
  },
  "devDependencies": {
    "eslint": "^6.6.0",
    "eslint-plugin-react-hooks": "^2.2.0",
    "eslint-plugin-react": "^7.16.0",
    "prettier": "^1.19.1"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing \""
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
`

`gatsby-node.js`: 

`const path = require(`path`);

exports.onCreateWebpackConfig = ({
  stage, loaders, actions,
}) => {
  const { setWebpackConfig } = actions;
  setWebpackConfig({
    externals: {
      jquery: 'jQuery', // important: 'Q' capitalized
    },
    // resolve: {
    //   alias: {
    //     ['@firebase/app']: path.resolve(__dirname, 'node_modules/@firebase/app/dist/index.cjs.js')
    //   }
    // },
    module: {
      rules: [
        {
          test: /@firebase/,
          use: loaders.null(),
        }
      ]
    }
  })
}`

`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wardpeet** [comment]
Have you checked out https://gatsby.dev/debug-html?

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by matrix4123** [comment]
> Have you checked out https://gatsby.dev/debug-html?
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

Yes, I was able to get around my issue by telling webpack not to add "axios" and then just including axios in the html.js file with the CDN path.

`actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /axios/,
            use: loaders.null(),
          },
        ],
      },
    })`

I have been trying to create a repro with a simple case but not luck yet. :/

**Comment by iDVB** [comment]
We have a very similar issue with gatsby trying to build axios and not having the right babel deps or something, this results in a successful build but an unstable axios as seen [here](https://github.com/axios/axios/issues/1178#issuecomment-595883506).
