### ISSUE TITLE
[gatsby-plugin-mdx] Router props missing from pages created with defaultLayouts

### ISSUE THREAD

**Issue by South-Paw** [gatsbyjs/gatsby#19526]
## Description

Pages created by the `gatsby-mdx-plugin` with a `defaultLayout.default` do not have any router props like normal pages do.

A 'normal' page receives the following props:

![chrome_2019-11-15_13-05-59](https://user-images.githubusercontent.com/2154764/68906701-110b2800-07aa-11ea-9945-35bab2243840.png)

Where-as a `gatsby-mdx-plugin` page only has `frontmatter` and no router props:

![chrome_2019-11-15_13-17-49](https://user-images.githubusercontent.com/2154764/68906781-57f91d80-07aa-11ea-95cc-7363d1b36157.png)

Alternatively, docs should mention a way to access router props on a `gatsby-mdx-plugin` page (it does not mention anything in this space at all yet)

### Steps to reproduce

Log the props of a 'normaly' created page and then log the props of a `gatsby-mdx-plugin` created page and compare.

### Expected result

`gatsby-mdx-plugin` pages should have the same router props as other pages.

### Actual result

There are no router props on `gatsby-mdx-plugin` pages

### Environment

```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - C:\Users\Alex\.windows-build-tools\python27\python.EXE
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11
    gatsby-image: ^2.2.31 => 2.2.31
    gatsby-plugin-manifest: ^2.2.27 => 2.2.27
    gatsby-plugin-mdx: ^1.0.56 => 1.0.56
    gatsby-plugin-offline: ^3.0.19 => 3.0.19
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14
    gatsby-plugin-sharp: ^2.2.37 => 2.2.37
    gatsby-plugin-styled-components: ^3.1.12 => 3.1.12
    gatsby-source-filesystem: ^2.1.36 => 2.1.36
    gatsby-transformer-sharp: ^2.3.3 => 2.3.3
```

**Comment by South-Paw** [comment]
It looks like that by loading the pages specifically with `gatsby-source-filesystem`, they start receiving router props

```
{
  resolve: 'gatsby-source-filesystem',
  options: {
    name: 'pages',
    path: `${__dirname}/src/pages/`,
  },
},
```

![chrome_2019-11-15_13-51-51](https://user-images.githubusercontent.com/2154764/68908120-1a4ac380-07af-11ea-9072-e17f90da7979.png)

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
