### ISSUE TITLE
Starter hello world link not working

### ISSUE THREAD

**Issue by vmr1532** [gatsbyjs/gatsby#19559]
## Description
Displaying link not found while clicking the link
https://app.netlify.com/start/deploy?repository=https://github.com/gatsbyjs/gatsby-starter-/
on 
https://github.com/gatsby/blob/master/starters/README-template.md

### Steps to reproduce

Goto

https://github.com/gatsby/blob/master/starters/README-template.md
and click the link below on the deploy session on the below the page
it will redirect to the link
https://app.netlify.com/start/deploy?repository=https://github.com/gatsbyjs/gatsby-starter/

### Expected result
Redirects to the correct deploy page 

### Actual result
Error in the deploy netflify page showing page not found

### Environment
![Screenshot from 2019-11-16 16-36-20](https://user-images.githubusercontent.com/47889807/68992275-50f80b00-088f-11ea-9893-65d87cfe722b.png)

**Comment by LekoArts** [comment]
Hi. Not sure what you're saying but everything works fine in regards to the hello-world starter and the Netlify deploy badge.

Therefore I'm closing this one.
