### ISSUE TITLE
gatsby breaks when .cache has been created from read-only node_modules

### ISSUE THREAD

**Issue by datakurre** [gatsbyjs/gatsby#19555]
## Description

To ensure reproducibility of my build environments, I'd like to package my build dependencies with Nix package manager. This has the side-effect of `node_modules` becoming read-only to ensure immutability for integrity and security (technically it gets located under read-only mount).

Unfortunately, gatsby expects files under `node_modules` have writable mode when it copies files into its `./cache`, resulting in errors like the following:

```
gatsby build
success open and validate gatsby-configs - 0.021s
success load plugins - 0.021s
success onPreInit - 0.007s
success delete html and css files from previous builds - 0.015s
success initialize cache - 0.009s

 ERROR 

EACCES: permission denied, open '/.../.cache/api-runner-browser-plugins.js'
```

### Steps to reproduce

Make node_modules not longer writable, for example on Linux with

```
chmod u-w -R node_modules
```

### Expected result

Gatsby should ensure that files it copies under `./cache` are writable (removable) after it has been copied them, and run just fine.

### Actual result

Gatsby creates `.cache`, but populates it with read-only files failing to replace them later in build (either by unlinking or opening them in writable mode as in below):

```
gatsby build
success open and validate gatsby-configs - 0.021s
success load plugins - 0.021s
success onPreInit - 0.007s
success delete html and css files from previous builds - 0.015s
success initialize cache - 0.009s

 ERROR 

EACCES: permission denied, open '/.../.cache/api-runner-browser-plugins.js'
```

### Environment

```
  System:
    OS: Linux 5.3 NixOS 19.09.976.c75de8bc12c (Loris) 19.09.976.c75de8bc12c (Loris)
    CPU: (4) x64 Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz
    Shell: 4.4.23 -   Binaries:
    Node: 10.16.0 - 
    Yarn: 1.17.3 - 
    npm: 6.9.0 -
  Languages:
    Python: 3.7.5 -
  Browsers:
    Firefox: 70.0b2
```

**Comment by wardpeet** [comment]
Hey @datakurre!

Thanks for opening this issue. We're happy to receive a pull request fixing this issue. It seems like a bit of a niche problem so I'm sorry to say that the core-team won't prioritize this any time soon.

Thanks for using gatsby! ❤️

**Comment by datakurre** [comment]
No problem. For me it is more than enough that your are open for reviewing the fix when I’ve done it ❤️

**Comment by m1cr0man** [comment]
Hi folks! Is there any chance this will be patched in the near future? I am trying to use Gatsby on NixOS and the exact same thing is happening.

**Comment by datakurre** [comment]
@m1cr0man I’m still using my patch related to this pull. But because it has been working well enough, I have not polished it as required by the review to make it mergeable.

**Comment by andir** [comment]
Also just ran into this on NixOS. Working on proper hermetic builds for node projects and one of my examples that I am working on is using gatsby. I guess a sane solution would be to honor the current umask instead of just copying the file modes from the source files? If files aren't writeable in the .cache directory, why even bother copying them?
