### ISSUE TITLE
configure.yml file is not present

### ISSUE THREAD

**Issue by rutikwankhade** [gatsbyjs/gatsby#19564]
## Description

After developing a gatsby site using gatsby develop
according to the documentations and the videos provided, we were supposed to edit the configure.yml file to add our github username and repo-name.
but surprisingly, there is no configure.yml file in the static folder of my project. I couldn't even create a new file. what shall i do now.

**Comment by LekoArts** [comment]
Thank you for opening this!

Not sure to which documentation or videos you're referring to but there is no `configure.yml` file with Gatsby. Please make sure that you read the instructions from third-party tutorials carefully, maybe you missed a step.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
