### ISSUE TITLE
Complied large template file blocking home page activities

### ISSUE THREAD

**Issue by vikingmute** [gatsbyjs/gatsby#19568]
In slow network connection, this compiled article template js file "src-templates-article-template-tsx.js"(about 825 Kb) will take a little while to load, during this time, all the activities on the home page will be blocked, click the article title has no responding. Do we have a dynamic import mechanism  when we actually go to that route? Sceenshots below:

<img width="896" alt="屏幕快照 2019-11-15 上午9 05 20" src="https://user-images.githubusercontent.com/343954/68909085-2bcca500-0788-11ea-9327-f883b48cce4a.png">

![block clicking](https://user-images.githubusercontent.com/343954/68909526-8c101680-0789-11ea-96d4-ed89f462d29c.gif)

**Comment by LekoArts** [comment]
Thank you for opening this!

And why is that template so big? Are you importing some huge libraries?
You should manually lazy load those libraries then:
https://github.com/smooth-code/loadable-components

We do the same with `react-highcharts` on our docs pages:
https://github.com/gatsbyjs/gatsby/blob/314526e2bc28715d83ffde0e6c172b483db1184c/www/src/components/chart.js

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
