### ISSUE TITLE
[Remark-smartypants] does not look like plugin works at all

### ISSUE THREAD

**Issue by Rulikkk** [gatsbyjs/gatsby#1957]
Maybe, we need to use `processSync` in this line, maybe there are more fixes required.
https://github.com/gatsbyjs/gatsby/blob/ca12b4dedefd386943c725561037c0dcac44c4a6/packages/gatsby-remark-smartypants/src/index.js#L11

**Comment by KyleAMathews** [comment]
What makes you think it doesn't work?

**Comment by Rulikkk** [comment]
Process method is async. 
Need processSync here.

**Comment by KyleAMathews** [comment]
Oh :-) ok! Would you like to create a PR with the fix?

**Comment by Rulikkk** [comment]
May be in several days. Overall I'm not really happy with quality of retext/remark and probably will make another markdown engine for Gatsby. 
 Also not sure if this is the only fix required.

**Comment by KyleAMathews** [comment]
>Overall I'm not really happy with quality of retext/remark and probably will make another markdown engine for Gatsby.

Woah cool! I was wondering how long it'd be until someone made a new set of transformers :-D

**Comment by KyleAMathews** [comment]
Closing out older issues — thanks for everyone that participated on this thread — please open more issues if you need help!
