### ISSUE TITLE
CreatePages runs infinite

### ISSUE THREAD

**Issue by adardesign** [gatsbyjs/gatsby#19581]
Using createPage freezes the develop.
## Description
I am using gatsby-source-woocommerce via @pasdo501/gatsby-source-woocommerce and configured it to createPages. 

### Steps to reproduce
It all work nicely when querying for data, but when it comes to creating the pages it freezes at  `source and transform nodes..` 
 
```
const path = require(`path`)
const slash = require(`slash`)
exports.createPages = async ({ graphql, actions }) => {
    const { createPage } = actions
    // query content for WordPress posts
    const result = await graphql(`{
    allWcProductsCategories(sort: {fields: name, order: [ASC]}, filter: {description: {eq: "<!-- show -->"}}) {
      nodes {
        id
        slug
        wordpress_id
        count
        name
        products {
          wordpress_id
          id
          name
          status
          slug
        }
      }
    }
  }`)
    const collectionTemplate = path.resolve(`./src/templates/collection.js`)
    const productDetail = path.resolve(`./src/templates/productDetail.js`)
    

result.data.allWcProductsCategories.nodes.forEach(node => {
        createPage({
            path: "collections/" + node.slug,
            component: slash(collectionTemplate),
            context: {
                id: node.id,
                wpId: node.wordpress_id
            },
        });
    });

    // it works great when I only run this.
    result.data.allWcProductsCategories.nodes.forEach(node => {
        if (!node.products) return;
        if (node.products.status !== 'publish') return;
        // now iterate over each product
        node.products.forEach(product => {
            createPage({
                path: product.slug,
                component: slash(productDetail),
                context: {
                    id: product.id,
                    wpId: product.wordpress_id
                },
            })
        });
    })
}

```
Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result
To fetch the needed data and build/create the pages
What should happen?

### Actual result
it hangs forever at the `source and transform nodes`

### Environment
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.0.0 - ~/.nvm/versions/node/v11.0.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v11.0.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.17.15 => 2.17.15 
    gatsby-image: ^2.2.33 => 2.2.33 
    gatsby-plugin-manifest: ^2.2.28 => 2.2.28 
    gatsby-plugin-offline: ^3.0.21 => 3.0.21 
    gatsby-plugin-react-helmet: ^3.1.15 => 3.1.15 
    gatsby-plugin-sharp: ^2.3.0 => 2.3.0 
    gatsby-source-filesystem: ^2.1.37 => 2.1.37 
    gatsby-transformer-sharp: ^2.3.5 => 2.3.5 
  npmGlobalPackages:
    gatsby-cli: 2.4.12

**Comment by s-kris** [comment]
There's a workaround https://github.com/gatsbyjs/gatsby/issues/9706#issuecomment-527519075

**Comment by adardesign** [comment]
When I do wait, it takes:
success source and transform nodes - 220.586s

**Comment by LekoArts** [comment]
Please try upgrading your `gatsby-plugin-sharp` version to 2.3.1

**Comment by adardesign** [comment]
@LekoArts Much better now!!

Thanks!
