### ISSUE TITLE
Adding onPostRenderHTML API

### ISSUE THREAD

**Issue by patrick91** [gatsbyjs/gatsby#19598]
## Summary

I'd like to see a onPreRenderHTML hook that gets called when a page is rendered.

### Basic example

I'd like to run screenshots for each page that gets rendered and currently I need to do this at the onPostBuild hook, would be ideal to have a hook when each page is rendered (and written to disk?).

Hope this makes sense :)

**Comment by LekoArts** [comment]
Could you please explain your motivation, use cases and why our current API isn't ideal in more detail?

**Comment by patrick91** [comment]
hi @LekoArts, so what I'm currenly doing is to wait for all the pages to be written on disk in order to fire the task to generate the screenshots. I think is is mostly fine, but what I need to do is also to have a onCreatePage hook that stores all the pages that have been created in an array and then in the onPostBuild I need to iterate over this array and fine the correct file.

I think it would be much easier to have a onPostRenderHTML hook[1] so we can do all the screenshot generation there, as soon as the page is rendered, this should make things a bit more performant too.

So the current flow I have is this:

1. onPageCreate -> store page in a global array
2. on onPostBuild -> open browser; iterate over pages and render screenshot; close browser

Ideal flow:

1. onPreBuild -> openBrowser
2. onPostRenderHTML -> render screenshot
3. onPostBuild -> closeBrowser

hope this clarifies things more :)

[1] I also just realised that I don't need the file to written on disk (puppeteer allows to set HTML directly).

**Comment by patrick91** [comment]
I don't think this is stale :)

**Comment by wardpeet** [comment]
Hey @patrick91 we're not considering this one as a valuable feature to have at this moment. Adding more lifecycles means more maintenance. We would advise doing a regular yarn build and do your tests after the build. Note that you can get all possible pages out of the redux store `store.getState().pages`. If you save it into a json file during postBuild, you can use it inside your test.

**Comment by patrick91** [comment]
@wardpeet yeah I get it :) my current solution works, so this is not a huge deal, but the hook would have made it more efficient I think :)
