### ISSUE TITLE
Gatsby New fails on cwebp-bin -- how to debug which sites the script is going to get sources? 

### ISSUE THREAD

**Issue by lawrenceong001** [gatsbyjs/gatsby#19593]
hello,

I'm having trouble creating a new Gatsby new site, and was wondering how this can be solved. Essentially, i'm behind our corporate network, which has a firewall (Fortinet) which we don't control but may be able to request exceptions (whitelisting), so i'm getting all sorts of issues when downloading packages. 

setting `NODE_TLS_REJECT_UNAUTHORIZED=0` got me to install gatsby on my desktop. however, attempting to create a new site results in an error. 

one comment was to turn on verbose debugging -- how do i do this so I can see which sites the script is attempting to download and install packages from? 

is there another directive to prevent this from happenning? 

tks,
Lawrence

ps this is similar, but not identical to another closed issue here, so plugging in a new one to detail out the error log:

`gatsby new g01`
`info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git`

`Cloning into 'g01'...`
`remote: Enumerating objects: 10, done.`
`remote: Counting objects: 100% (10/10), done.`
`remote: Compressing objects: 100% (6/6), done.`
`remote: Total 2309 (delta 4), reused 10 (delta 4), pack-reused 2299R`
`Receiving objects: 100% (2309/2309), 12.62 MiB | 5.89 MiB/s, done.`
`success Created starter directory layout`
`info Installing packages...`
``
``
`> sharp@0.23.2 install C:\Dev\gatsby01\g01\g01\node_modules\sharp`
`> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
``
`info sharp Using cached C:\Users\a_ongl\AppData\Roaming\npm-cache\_libvips\libvips-8.8.1-win32-x64.tar.gz`
`info sharp Creating C:\Dev\gatsby01\g01\g01\node_modules\sharp\build\Release`
`info sharp Copying DLLs from C:\Dev\gatsby01\g01\g01\node_modules\sharp\vendor\lib to C:\Dev\gatsby01\g01\g01\node_modules\sharp\build\Release`
`(node:8832) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.`
``
`> core-js@2.6.10 postinstall C:\Dev\gatsby01\g01\g01\node_modules\core-js`
`> node postinstall || echo "ignore"`
``
`Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!`
``
`The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:`
`> https://opencollective.com/core-js`
`> https://www.patreon.com/zloirock`
``
`lso, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)`
``
``
`> gatsby-telemetry@1.1.36 postinstall C:\Dev\gatsby01\g01\g01\node_modules\gatsby-telemetry`
`> node src/postinstall.js`
``
``
`> cwebp-bin@5.1.0 postinstall C:\Dev\gatsby01\g01\g01\node_modules\cwebp-bin`
`> node lib/install.js`
``
`(node:8364) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.`
`  ‼ self signed certificate in certificate chain`
`  ‼ cwebp pre-build test failed`
`  i compiling from source`
`  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "./configure --disable-shared --prefix="C:\Dev\gatsby01\g01\g01\node_modules\cwebp-bin\vendor"--bindir="C:\Dev\gatsby01\g01\g01\node_modules\cwebp-bin\vendor""`
`'.' is not recognized as an internal or external command,`
`operable program or batch file.`
``
``
`    at C:\Dev\gatsby01\g01\g01\node_modules\execa\index.js:231:11`
`    at processTicksAndRejections (internal/process/task_queues.js:89:5)`
``
`> mozjpeg@6.0.1 postinstall C:\Dev\gatsby01\g01\g01\node_modules\mozjpeg`
`> node lib/install.js`
``
`(node:16256) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.`
`  ‼ self signed certificate in certificate chain`
`  ‼ mozjpeg pre-build test failed`
`  i compiling from source`
`  × RequestError: self signed certificate in certificate chain`
`    at ClientRequest.<anonymous> (C:\Dev\gatsby01\g01\g01\node_modules\download\node_modules\got\index.js:111:21)`
`    at Object.onceWrapper (events.js:284:20)`
`    at ClientRequest.emit (events.js:196:13)`
`    at TLSSocket.socketErrorListener (_http_client.js:402:9)`
`    at TLSSocket.emit (events.js:196:13)`
`    at emitErrorNT (internal/streams/destroy.js:91:8)`
`    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)`
`    at processTicksAndRejections (internal/process/task_queues.js:84:17)`
``
`> pngquant-bin@5.0.2 postinstall C:\Dev\gatsby01\g01\g01\node_modules\pngquant-bin`
`> node lib/install.js`
``
`(node:15424) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.`
`  ‼ self signed certificate in certificate chain`
`  ‼ pngquant pre-build test failed`
`  i compiling from source`
`  × Error: pngquant failed to build, make sure that libpng-dev is installed`
`    at C:\Dev\gatsby01\g01\g01\node_modules\execa\index.js:231:11`
`    at processTicksAndRejections (internal/process/task_queues.js:89:5)`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\chokidar\node_modules\fsevents):`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`
``
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! pngquant-bin@5.0.2 postinstall: `node lib/install.js``
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the pngquant-bin@5.0.2 postinstall script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`npm ERR! A complete log of this run can be found in:`

` ERROR`

`Command failed with exit code 1 (Unknown system error -1): npm install`

`  Error: Command failed with exit code 1 (Unknown system error -1): npm install`

`  - error.js:58 makeError`
`    [npm]/[gatsby-cli]/[execa]/lib/error.js:58:11`
``
`  - index.js:112 handlePromise`
`    [npm]/[gatsby-cli]/[execa]/index.js:112:26`

`  - task_queues.js:89 processTicksAndRejections`
`    internal/process/task_queues.js:89:5`

**Comment by LekoArts** [comment]
Hi!

> one comment was to turn on verbose debugging -- how do i do this so I can see which sites the script is attempting to download and install packages from?

Since you're running `gatsby new` the CLI clones `https://github.com/gatsbyjs/gatsby-starter-default.git` - or what do you mean? :)

> this is similar, but not identical to another closed issue here, so plugging in a new one to detail out the error log

Can you link that issue?

**Comment by lawrenceong001** [comment]
hello, 

yes this issue still persists unfortunately. 

tks
Lawrence
