### ISSUE TITLE
Tried to add lost grid

### ISSUE THREAD

**Issue by cutemachine** [gatsbyjs/gatsby#196]
Hello

I just tried to use [lost grid](https://github.com/peterramsing/lost) which is build with PostCSS.

I added the following lines to my `gatsby.config.js`:

```
  config.merge({
    postcss: [
      require('lost')
    ]
  })
```

When I load my page I get errors liek this one:

```
.get-started:hover {
  background: white;
  color: #E05B49;
  text-decoration: none;
}
 is not a PostCSS plugin
```

Can anybody provide we with a sample on how to do this? Thanks

**Comment by KyleAMathews** [comment]
I just tested doing exactly this and things worked. Perhaps you forgot to return `config`?

**Comment by cutemachine** [comment]
Thanks for the quick answer.

I return config. Here is the complete config file:

```
module.exports = function(config, env) {
  var is_static = env === 'static'
  var is_develop = env === 'develop'
  var is_production = env === 'production'

  config.loader('sh', function(cfg) {
    cfg.test = /\.(sh|zip|lua|snippets|opacity)$/
    cfg.loader = 'file-loader'
    return cfg
  });

  config.removeLoader('png')
  config.loader('png', function(cfg) {
    cfg.test = /\.png$/
    cfg.loader = 'url-loader'
    return cfg
  })

  config.merge({
    postcss: [
      require('lost')
    ]
  })

  return config
}
```

**Comment by kevohagan** [comment]
the lumen starter uses lost, check it out :
https://github.com/hb-gatsby/gatsby-lumen-starter

**Comment by cutemachine** [comment]
@kevohagan Many Thanks. That helped. It is now working. Unfortunately, I do not know what the issue was. But I guess it was related to a missing package or config in gatsby.config.js, as I have not changed anything else to resolve the isse.
