### ISSUE TITLE
Gatsby crashes every time I update existing .md files

### ISSUE THREAD

**Issue by louishugens** [gatsbyjs/gatsby#19608]
## Description

I have a blog with gatsby and every time i update an existing blog posts .md file, the gatsby develop command crashes with the following error:
Field "featuredImage" must not have a selection since type "String" has no subfields.

### Steps to reproduce

install gatsby default starter

gatsby-node.js content:
```
const path = require(`path`)

exports.createPages = async ({ actions, graphql, reporter }) => {
  const { createPage } = actions

  const blogPostTemplate = path.resolve(`src/templates/blogPost.js`)

  const result = await graphql(`
    {
      allMarkdownRemark(limit: 1000) {
        edges {
          node {
            fields {
              slug
            }
          }
        }
      }
    }
  `)

  // Handle errors
  if (result.errors) {
    reporter.panicOnBuild(`Error while running GraphQL query.`)
    return
  }

  result.data.allMarkdownRemark.edges.forEach(({ node }) => {
    createPage({
      path: node.fields.slug,
      component: blogPostTemplate,
      context: {}, // additional data can be passed via context
    })
  })
}


const { createFilePath } = require('gatsby-source-filesystem')
const { fmImagesToRelative } = require('gatsby-remark-relative-images')

exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions
  fmImagesToRelative(node) // convert image paths for gatsby images

  if (node.internal.type === `MarkdownRemark`) {
    const value = createFilePath({ node, getNode })
    createNodeField({
      name: `slug`,
      node,
      value,
    })
  }
}
```

gatsby-config.js content:
```
plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/static/images`,
        name: 'images',
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/blog-posts`,
        name: 'blog-posts',
      },
    },
    `gatsby-plugin-sharp`,    
    `gatsby-transformer-sharp`,
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-relative-images',
            options: {
              name: 'images',
            },
          },
          {
            resolve: 'gatsby-remark-images',
            options: {},
          },
          // {
          //   resolve: 'gatsby-remark-copy-linked-files',
          //   options: {
          //     destinationDir: 'static',
          //   },
          // },
        ],
      },
    },
```

### Expected result

It work properly until I edit posts.

### Actual result

it fails with :

Field "featuredImage" must not have a selection since type "String" has no subfields.

### Environment

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0-next.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.6.5 - /c/Users/Hugens/AppData/Local/Programs/Python/Python36-32/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.17.6 => 2.17.15 
    gatsby-background-image: ^0.8.18 => 0.8.19 
    gatsby-image: ^2.2.30 => 2.2.33 
    gatsby-plugin-manifest: ^2.2.25 => 2.2.28 
    gatsby-plugin-netlify-cms: ^4.1.26 => 4.1.28 
    gatsby-plugin-offline: ^3.0.17 => 3.0.21 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.15 
    gatsby-plugin-sharp: ^2.2.34 => 2.3.0 
    gatsby-remark-copy-linked-files: ^2.1.28 => 2.1.30 
    gatsby-remark-images: ^3.1.29 => 3.1.31 
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3 
    gatsby-source-filesystem: ^2.1.35 => 2.1.37 
    gatsby-transformer-remark: ^2.6.32 => 2.6.35 
    gatsby-transformer-sharp: ^2.3.1 => 2.3.5

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by vladar** [comment]
Likely related to `gatsby-remark-relative-images`. Have you tried [this advice](https://github.com/danielmahon/gatsby-remark-relative-images#im-getting-the-error-field-image-must-not-have-a-selection-since-type-string-has-no-subfields) from their docs?

Also seems to be related: #19748

**Comment by tomivirkki** [comment]
This is still an issue with the latest version of Gatsby. It's reproducible with `gatsby-source-filesystem` and `gatsby-transformer-remark` alone.

I bumped into this while working with `gatsby-transformer-asciidoc` to be precise, but it seems to be about the same issue.

My current workaround is to fix Gatsby version to `2.17.16`.

Created a repro at https://github.com/tomivirkki/bug-repro

**Comment by vladar** [comment]
Thanks for the repro. I'll take a look when I have a chance!

**Comment by vladar** [comment]
Looks like we have some sort of race condition which causes hot-page-reloader to start rebuilding pages prematurely (internal event `API_RUNNING_QUEUE_EMPTY` is called prematurely somehow).

This required further investigation.

**Comment by vladar** [comment]
Oh but if I upgrade all packages to the latest versions - it stops crashing. So I guess this was already fixed somewhere. Probably here: #20836

**Comment by tomivirkki** [comment]
Great, it seems to work now.
