### ISSUE TITLE
Gatsby Source Contentful suddenly loses nearly all types

### ISSUE THREAD

**Issue by sashafklein** [gatsbyjs/gatsby#19605]
## Description

Over the weekend, my fully-functioning Gatsby app using Gatsby Source Contentful just broke. Specifically, all sorts of types that had previously worked were suddenly no longer recognized, so I started seeing a host of errors like this when booting up the app. 

```
Cannot query field "allContentfulProject" on type "Query". Did you mean "allContentfulAsset", "allContentfulQuote", "allContentfulBlogPost", "allContentfulPageSection", or "contentfulQuote"?
```

I figured it was an error on Contentful's end, because I hadn't explicitly upgraded my Gatsby/GSC version, but if so, it's a very confusing error. I've managed to fix it by going into Contentful and explicitly unpublishing and republishing each relevant piece of content. 

That supplies all the types needed to get the linting to work and the build step to pass, but now there are all sorts of pieces of content which aren't fetched at all. Specifically *anything* I didn't un/re-publish doesn't seem to be detected by the plugin. 

I don't have a sense of what's causing this, and I don't really see how I could set up a reproduction to debug (it's a private space, with lots of specific content). 

Nothing changed to produce this, and it seemed to appear simultaneously on my and my coworker's systems. I've reached out to Contentful support about this, but I can't really tell what's going on.

I suspect it's probably on their end (because nothing appeared to change on mine)

I'm on version `2.1.55` of Gatsby Source Contentful, and version `2.17.7` of Gatsby. Neither of these is the newest, or was updated in the last few days, but I wanted to see if it's possibly something caused by this plugin (eg, there's some sort of type caching somewhere!?). How would I debug that?

### Steps to reproduce

No idea. This was working Friday, and then not working Monday, with nothing done by me (or my coworker) in between.

### Expected result

The published content from Contentful is available, and fed into GraphQL types, on the frontend.

### Actual result

Nothing is recognized from Contentful until I unpublish and republish it.

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.17.7 => 2.17.7
    gatsby-image: ^2.2.30 => 2.2.30
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
    gatsby-plugin-manifest: ^2.2.20 => 2.2.20
    gatsby-plugin-offline: ^3.0.11 => 3.0.11
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-sass: ^2.1.17 => 2.1.17
    gatsby-plugin-sharp: ^2.2.27 => 2.2.27
    gatsby-plugin-sitemap: ^2.2.20 => 2.2.20
    gatsby-plugin-transition-link: ^1.13.0 => 1.13.0
    gatsby-source-apiserver: ^2.1.3 => 2.1.3
    gatsby-source-contentful: ^2.1.55 => 2.1.56
    gatsby-source-filesystem: ^2.1.35 => 2.1.35
    gatsby-transformer-sharp: ^2.3.2 => 2.3.2
  npmGlobalPackages:
    gatsby-cli: 2.7.40
```

**Comment by LekoArts** [comment]
Hi! This is indeed very weird thing to happen.

So you didn't change your Gatsby code or dependencies at all? I suspect it's something on Contentful's end so please await their support response. If they say that this must be an issue with Gatsby we can try to find out what's going on.

**Comment by pgegenfurtner** [comment]
I'm experiencing the same issue with `gatsby-source-apiserver`. Nothing changed, but the schema is incomplete.
