### ISSUE TITLE
Using react-l18n with Gatsby

### ISSUE THREAD

**Issue by zasuh** [gatsbyjs/gatsby#19611]
## Summary

I'm using react-l18n for the first time with my Gatsby site and am following this tutorial: https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/

The translations aren't working how they are suppose to. The tutorial seems to be using classes while I have functional components so maybe the problem is how I pass the `t` prop? Can someone please take a look? Thanks!

## Relevant information

`Header.js` component where I'm trying to translate Contact and Biography, but getting `contact` and `biography`:
```javascript
import React from 'react'
import { withTranslation } from 'react-i18next'
import styled from 'styled-components'
import PropTypes from 'prop-types'
import { Link } from 'gatsby'

const Wrapper = styled.div`
  background: url("${props => props.theme.bgPattern}") #b6b6b6;
  display: flex;
  position: relative;
`

const Content = styled.div`
  margin: 0 auto;
  max-width: ${props => props.theme.maxWidths.general};
  padding: 3rem 1.0875rem 3rem 1.0875rem;
  color: ${props => props.theme.colors.secondary};
  text-align: center;
  height: 400px;
  @media (max-width: ${props => props.theme.breakpoints.s}) {
    height: 500px;
  }
`

const Name = styled.h1`
  margin: 1rem 0 0.25rem 0;
  color: ${props => props.theme.colors.color};
  font-size: 4rem;
`

const Contact = styled(Link)`
  margin-top: 3rem;
  padding: 0 1rem 0 0;

  a {
    margin: 0 0.3rem;
    color: black;
    text-decoration: underline;
  }
`

const Bio = styled(Link)`
  margin-top: 3rem;

  a {
    margin: 0 0.3rem;
    color: black;
    text-decoration: underline;
  }
`

const Header = ({ name, t }) => {
  console.log(t)
  return (
    <Wrapper>
      <Content>
        <Name>{name}</Name>
        <Contact to="/contact/">{t('contact')}</Contact>
        <Bio to="/about/">{t('biography')}</Bio>
      </Content>
    </Wrapper>
  )
}

export default withTranslation('Header')(Header)

Header.propTypes = {
  name: PropTypes.string.isRequired,
  t: PropTypes.func.isRequired,
}
```

locales for `Header.json`

```json
{
  "contact": "Contact",
  "biography": "Biography"
}
```

### Environment

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.13.25 => 2.13.25
    gatsby-cypress: ^0.2.3 => 0.2.4
    gatsby-image: ^2.2.8 => 2.2.8
    gatsby-plugin-google-analytics: ^2.1.6 => 2.1.7
    gatsby-plugin-lodash: ^3.1.2 => 3.1.2
    gatsby-plugin-manifest: ^2.2.4 => 2.2.5
    gatsby-plugin-mdx: ^1.0.22 => 1.0.23
    gatsby-plugin-netlify: ^2.1.3 => 2.1.4
    gatsby-plugin-offline: ^2.2.4 => 2.2.5
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sharp: ^2.2.9 => 2.2.11
    gatsby-plugin-sitemap: ^2.2.5 => 2.2.6
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-normalize-paths: ^1.0.0 => 1.0.0
    gatsby-source-filesystem: ^2.1.8 => 2.1.9
    gatsby-transformer-remark: ^2.6.30 => 2.6.30
    gatsby-transformer-sharp: ^2.2.5 => 2.2.6

### File contents

`gatsby-node.js`:
```javascript
const fs = require('fs-extra')
const path = require('path')
const _ = require('lodash')

// graphql function doesn't throw an error so we have to check to check for the result.errors to throw manually
const wrapper = promise =>
  promise.then(result => {
    if (result.errors) {
      throw result.errors
    }
    return result
  })

exports.onCreateNode = ({ node, actions }) => {
  const { createNodeField } = actions
  let slug
  // Search for MDX filenodes
  if (node.internal.type === 'Mdx') {
    // If the frontmatter has a "slug", use it
    if (
      Object.prototype.hasOwnProperty.call(node, 'frontmatter') &&
      Object.prototype.hasOwnProperty.call(node.frontmatter, 'slug')
    ) {
      slug = `/${_.kebabCase(node.frontmatter.slug)}`
    }
    // If not derive a slug from the "title" in the frontmatter
    else if (
      Object.prototype.hasOwnProperty.call(node, 'frontmatter') &&
      Object.prototype.hasOwnProperty.call(node.frontmatter, 'title')
    ) {
      slug = `/${_.kebabCase(node.frontmatter.title)}`
    }
    createNodeField({ node, name: 'slug', value: slug })
  }
}

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions

  const projectTemplate = require.resolve('./src/templates/project.js')

  const result = await wrapper(
    graphql(`
      {
        projects: allMdx(sort: { fields: [frontmatter___date], order: DESC }) {
          nodes {
            fileAbsolutePath
            fields {
              slug
            }
            frontmatter {
              title
            }
          }
        }
      }
    `)
  )

  const projectPosts = result.data.projects.nodes

  projectPosts.forEach((n, index) => {
    const next = index === 0 ? null : projectPosts[index - 1]
    const prev = index === projectPosts.length - 1 ? null : projectPosts[index + 1]

    createPage({
      path: n.fields.slug,
      component: projectTemplate,
      context: {
        slug: n.fields.slug,
        // Pass the current directory of the project as regex in context so that the GraphQL query can filter by it
        absolutePathRegex: `/^${path.dirname(n.fileAbsolutePath)}/`,
        prev,
        next,
      },
    })
  })
}

exports.onPostBuild = () => {
  console.log('Copying locales')
  fs.copySync(path.join(__dirname, '/src/locales'), path.join(__dirname, '/public/locales'))
}

```

**Comment by LekoArts** [comment]
Thank you for opening this!

The tutorial is a bit outdated and since then the library mentioned there released a bunch of stuff, including hooks support:
https://react.i18next.com/latest/usetranslation-hook

I'd recommend following their documentation to implement the library or reaching out to them if you have questions: https://github.com/i18next/react-i18next

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
