### ISSUE TITLE
React-Id-Swiper, Bootstrap Toggle Navbar… are not working in Gatsby project after 'gatsby build'

### ISSUE THREAD

**Issue by Teo0303** [gatsbyjs/gatsby#19627]
I am using Swiper and Bootstrap Toggle Navbar on my Gatsby project.

After building my project, neither Swiper nor Navbar Toggle are working. But when I run my project on development mode everything works fine.

I think there's something wrong with js files. Other data something like images, icons, text are working. Should I configure gatsby-config.js or smth else?

In development mode everything is working: https://i.imgur.com/aUFG7Gg.gifv

After building interactions are not working: https://i.imgur.com/MdeipPE.gifv  

Here's my gatsby-config.js

```
require('dotenv').config({
	path: `.env`
});

module.exports = {
	siteMetadata: {
		title: `Raisense`,
		description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
		author: `@gatsbyjs`
	},
	plugins: [
		`gatsby-plugin-react-helmet`,
		{
			resolve: `gatsby-source-filesystem`,
			options: {
				name: `images`,
				path: `${__dirname}/src/images`
			}
		},
		`gatsby-transformer-sharp`,
		`gatsby-plugin-sharp`,
		{
			resolve: `gatsby-plugin-manifest`,
			options: {
				name: `gatsby-starter-default`,
				short_name: `starter`,
				start_url: `/`,
				background_color: `#663399`,
				theme_color: `#663399`,
				display: `minimal-ui`,
				icon: `src/images/gatsby-icon.png` // This path is relative to the root of the site.
			}
		},
		{
			resolve: `gatsby-source-prismic-graphql`,
			options: {
				repositoryName: process.env.PRISMIC_REPOSITORY_NAME,
				accessToken: process.env.PRISMIC_ACCESS_TOKEN
			}
		},
	]
};

```

**Comment by anuraghazra** [comment]
@Teo0303 Thanks for opening an issue regarding your specific problem.

Can you provide some information about how are you loading the "stylesheets" for the react-id-swiper and if you are getting any error message in chrome's dev tools?

**Comment by Teo0303** [comment]
> @Teo0303 Thanks for opening an issue regarding your specific problem.
> 
> Can you provide some information about how are you loading the "stylesheets" for the react-id-swiper and if you are getting any error message in chrome's dev tools?

Of course. here's my console.
![image](https://user-images.githubusercontent.com/39439363/69158943-f79b1080-0b08-11ea-9626-bce0b0f82ff4.png)

gatsby-browser.js

![image](https://user-images.githubusercontent.com/39439363/69159031-1f8a7400-0b09-11ea-8484-5ddc35ff9fe0.png)

Slider component 

```
import React, { Component } from 'react';
import Swiper from 'react-id-swiper';
import './slider.css';

export default class Slider extends Component {
	state = {
		sliders: this.props.data
	};

	render() {
		const params = {
			navigation: {
				nextEl: '.swiper-button-next',
				prevEl: '.swiper-button-prev'
			}
		};
		return (
			<div className="slider">
				<Swiper {...params}>
					{this.state.sliders.map((slider, index) => {
						return (
							<img
								key={index}
								src={slider.node.imageSharp.childImageSharp.fluid.srcWebp}
								srcSet={slider.node.imageSharp.childImageSharp.fluid.srcSetWebp}
								alt={slider.node.title[0].text}
							/>
						);
					})}
				</Swiper>
			</div>
		);
	}
}

```

**Comment by jonniebigodes** [comment]
@Teo0303 can you make a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) to be better looked at. Looking at the screenshots and component helps a bit, but having a full reproduction would help out immensely

**Comment by Teo0303** [comment]
> @Teo0303 can you make a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) to be better looked at. Looking at the screenshots and component helps a bit, but having a full reproduction would help out immensely

Here's a link to reproduction https://github.com/Teo0303/raisense-bug-repro

I think there's something wrong whith gatsby-source-prismic-graphql.
When I loaded data from local file everything worked great after building. But when I installed  gatsby-source-prismic-graphql and fetched data from prismic, the issue appeared again

**Comment by LekoArts** [comment]
Thank you for opening this!

We don't maintain react-id swiper or gatsby-source-prismic-graphql. Please go to their respective repositories and reach out to the authors. It's also possible that this is not related to both projects at all but your React usage (in this case you can ask on e.g. Stackoverflow or React communities).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
