### ISSUE TITLE
Module.createRequireFromPath() is deprecated.

### ISSUE THREAD

**Issue by hu0p** [gatsbyjs/gatsby#19634]
## Description

[`Module.createRequireFromPath()` is deprecated ](https://nodejs.org/api/modules.html#modules_module_createrequirefrompath_filename)as of Node v13.1.0. An error is thrown when it is used.

### Steps to reproduce

1. Upgrade to node v13.1.0 (can also use nvm or n to just use it)
2. Grab a project and start/build it.

### Expected result

No deprecation warnings from core when using latest stable version of Node.js.

### Actual result

This is logged to the console during the [load plugins lifecycle](https://github.com/gatsbyjs/gatsby/blob/2e8f3817266cfc8fc5bd01c79dcdb452ff7b7487/packages/gatsby/src/bootstrap/load-plugins/load.js#L89):

```sh
 ERROR 

(node:9331) [DEP0130] DeprecationWarning: Module.createRequireFromPath() is deprecated. Use Module.createRequire() instead.
```

[Line 6](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/create-require-from-path.js#L6) of `gatsby/src/utils/create-require-from-path.js` is causing it.

### Proposed solution
A simple solution could be to just remove [line 4](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/create-require-from-path.js#L4) (polyfill comment) and line 6 and continue using the function as is.

 If that's the route you'd like to take, let me know and I'd be happy to open a quick PR for it.

Thanks!

**Comment by blainekasten** [comment]
@hu0p Thanks for the report! I don't think we can remove the polyfill comment because we support back to Node 8.

It seems like we just need to add the new api and order them correctly. 

Something like.

```js
module.exports = Module.createRequire || Module.createRequireFromPath ||
  function(filename) {...}
```

Would you be interested in contributing this fix and testing it?

**Comment by cstoddart** [comment]
Created this PR and can confirm it removes the deprecation warning 👍 

https://github.com/gatsbyjs/gatsby/pull/19677

**Comment by vladar** [comment]
Published in `gatsby 2.18.2`

**Comment by colorful-tones** [comment]
I just encountered this same issue when spinning up my first Gatsby site. I ran `npx gatsby new gatsby-site` from the [Quick Start video](https://www.gatsbyjs.org/docs/quick-start). 

Did a quick Google for the issue, landed here, went to Releases page to see if `2.18.2` had landed, and it has. So, I'm thinking it must be lag in the publishing from my end, as I see `2.18.2` was published "6 hours ago" on GH [Releases](https://github.com/gatsbyjs/gatsby/releases) _and_ [npmjs.org](https://www.npmjs.com/package/gatsby)

**Comment by colorful-tones** [comment]
Never mind, I forgot I had system version installed and had to update. 🤦‍♂

**Comment by Remzi1993** [comment]
I needed to run: `npm install gatsby@latest` to fix this issue. I post this here for others who might stumble upon this.
