### ISSUE TITLE
How to implement Firebase Analytics without the other stuff?

### ISSUE THREAD

**Issue by donmasakayan** [gatsbyjs/gatsby#19631]
## Summary
**How do I enable Firebase Analytics only, without the other Firebase features?**

There exists a Gatsby plugin for Firebase:
https://www.gatsbyjs.org/packages/gatsby-plugin-firebase/

However, you're required to set at least one of the features to `true` for it to work. But I don't need any of these features. I only need the analytics feature of Firebase.

In a typical website, I simply need to call `firebase.analytics()` for tracking to be enabled, such as below:

```
<script src="https://www.gstatic.com/firebasejs/7.4.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.4.0/firebase-analytics.js"></script>

<script>
  var firebaseConfig = {
    // ...
  };
  firebase.initializeApp(firebaseConfig);
  firebase.analytics();
</script>
```

**Comment by blainekasten** [comment]
Hey @donmasakayan, sorry to throw you for loops. But the plugin you are asking about we don't own. 

The repo for that plugin is here: https://github.com/alexluong/gatsby-packages/issues. 

You should open an issue on that repository and the owner can help you out. I'll close out this issue. Feel free to ping back if there is any way we can help!
