### ISSUE TITLE
styled-components classes can't be found on the site

### ISSUE THREAD

**Issue by kimlianlopez** [gatsbyjs/gatsby#19646]
## Description

All styled-component styles are gone on a normal google chrome tab. I thought at first that this was a caching issue, but all other changes I'm making are reflected unto the development site. It's working properly on other browsers, also on chrome incognito. I have tried uninstalling google chrome, clearing browser data and all, but still the same.

When trying to fix the issue, I also installed gatsby-plugin-styled-components and babel-plugin-styled-components as mentioned [here](https://www.gatsbyjs.org/packages/gatsby-plugin-styled-components/) that it is now required. But still, it didn't do anything.

### Steps to reproduce

I'm not sure yet if this is also happening to anyone, but I'm more than happy to share the private repo with anyone who can help.

### Expected result

Here is the hero section of the site on incognito:
![Hero Section Fixed](https://i.ibb.co/tPyCpRk/onincognito.png)

Opened Sidebar
![Hero Section Opened Sidebar](https://i.ibb.co/tBNFTyT/onincognito-opened-sidebar.png)

### Actual result

Here is the site with broken styled-component styles:
![Hero Section Broken](https://i.ibb.co/xSRCB7B/onregulartab.png)

styled-components classes not found
![Classes not found](https://i.ibb.co/jgQfcC7/noclasses-found.png)

### Environment

I am using WSL:

  System:
    OS: Linux 4.4 Ubuntu 18.04.3 LTS (Bionic Beaver)      
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    npm: 6.13.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11
    gatsby-background-image-es5: ^0.8.18 => 0.8.18
    gatsby-image: ^2.2.31 => 2.2.31
    gatsby-plugin-manifest: ^2.2.27 => 2.2.27
    gatsby-plugin-offline: ^3.0.19 => 3.0.19
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-sass: ^2.1.21 => 2.1.21
    gatsby-plugin-sharp: ^2.2.37 => 2.2.37
    gatsby-plugin-styled-components: ^3.1.13 => 3.1.13
    gatsby-source-filesystem: ^2.1.36 => 2.1.36
    gatsby-transformer-remark: ^2.6.37 => 2.6.37
    gatsby-transformer-sharp: ^2.3.3 => 2.3.3
  npmGlobalPackages:
    gatsby-cli: 2.8.9

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by kimlianlopez** [comment]
Closing this issue as this likely an issue for styled-components.
For any future encounters, this may help: 

[styled-components does not inject styles in head
#2254](https://github.com/styled-components/styled-components/issues/2254)
