### ISSUE TITLE
Add support for SVG favicons

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#19641]
SVG favicons [just came out](https://twitter.com/mathias/status/1196816651834068994). It would be nice to integrate them well along with Gatsby.

**Comment by LekoArts** [comment]
Thank you for opening this!

I don't see why Gatsby would need to do something about that, you can use react-helmet to set your desired favicon and changing the MIME type is something you can set on your CDN :) Also, this landed in Chromium which means it'll still take a while until Chrome gets it.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
