### ISSUE TITLE
[gatsby-theme-blog] unused css property in Switch.js

### ISSUE THREAD

**Issue by apolopena** [gatsbyjs/gatsby#19648]
## Summary
While I was shadowing the components needed to modify the theme switcher switch I came across some code that appears to do nothing at all so I am wondering why it is there. The code is the 'css' property in the Switch.js component. Switch.js does nothing but pass this property to to whats it wraps which is a ReactSwitch component from [react-switch](https://github.com/markusenglund/react-switch). 
According to the [react-switch api](https://github.com/markusenglund/react-switch#api), there is no 'css' property. Also removing the css property from Switch.JS has no visible effect. 
Should this code be removed?

## Relevant information
gatsby-theme-blog css property on line #8 in [Switch.js](https://github.com/gatsbyjs/gatsby/blame/master/packages/gatsby-theme-blog/src/components/switch.js#L8)
react-switch [api](https://github.com/markusenglund/react-switch#api)
[react-switch doesnt use the css property to change its 'bg'](https://github.com/markusenglund/react-switch/blob/master/src/index.jsx)
"gatsby-theme-blog": "^1.1.22"

**Comment by LekoArts** [comment]
The `css` comes from Theme UI and is valid. However, the background-color gets overwritten by the inline styles from react-switch (see defaultProps). So the `css` part can be removed.
