### ISSUE TITLE
Redirect to static file?

### ISSUE THREAD

**Issue by bogdancss** [gatsbyjs/gatsby#19655]
We are trying to implement a programmatic redirect to a static pdf hosted in the static folder of the project.

Trying the `navigate` method from `gatsby` or straight from `@reach/router` does redirect to the pdf page, however, it renders the 404 page and errors:

`VM614:1 GET https://www.example.com/page-data/uploads/pdfname.pdf/page-data.json 404`

If you refresh the page after the redirect, it renders the pdf file just fine, but initially, it loads the 404 page.

Is there a way around this?

**Comment by anuraghazra** [comment]
Hi @bogdancss, as far as i know, i think gatsby's navigate method only can be used for internal pages and cannot redirect to external resources.

One solution i can think of is to use the browser api's to redirect to your pdf :-

```js
// checking if the window is available otherwise `gatsby build` will fail
  if (typeof window !== 'undefined') {
    // redirect after 1sec
    window.setTimeout(function() {
      window.location.pathname = 'myFile.pdf';
    }, 1000)
  }
```

Further info: https://www.gatsbyjs.org/docs/gatsby-link/

**Comment by scottalan** [comment]
I know this is an old issue thread but did you find a solution to your issue @anuraghazra? I'm running into the exact same problem.

**Comment by NZI** [comment]
@scottalan If possible, avoid using `gatsby-link` and just use a direct `window.location` manipulation or and `<a href` tag
