### ISSUE TITLE
Consider making @reach/router a peer dependency

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#19669]
### Motivation

There are many use-cases in which functionality of `@reach/router` must be used directly, e.g. [client-only routes & user authentication](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/). When using [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import), even through popular configs like [the one made by Airbnb](https://github.com/airbnb/javascript), it throws an error about `@reach/router` being an extraneous dependency.

While linting rules like above may be disabled, it feels unnatural to rely on the implicit implementation details of Gatsby. New users may not know that routing is based on Reach, but adding it as a peer dependency would make it more explicit.

**Comment by LekoArts** [comment]
Thank you for opening this!

> New users may not know that routing is based on Reach, but adding it as a peer dependency would make it more explicit.

The automatic routing via Gatsby's Link component and page creation in src/pages is a core part of Gatsby and most users don't care what is used under the hood. If they want to find that out, our documentation is mentioning that.

We want to author the underlying router and its version (especially needed for when react router and reach router merge etc.) so I don't think we'll make it a peer dependency for now.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by codyzu** [comment]
Just hit this while setting up my linter with [import/no-extraneous-dependencies](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md).

Any ideas how to work around this with Gatsby?

I can add eslint ignore comments into the files that import reach router, but we have over 20 files that import the router.
