### ISSUE TITLE
CSS differ between Gatsby BUILD and DEVELOP | theme-ui

### ISSUE THREAD

**Issue by pjeziorowski** [gatsbyjs/gatsby#19661]
## Description
Hi!

CSS attribute used in this way:
```jsx
          <Styled.li
            key={link.label}
            css={{
              listStyleType: `none`,
              padding: `0 1rem`,
              margin: "0",
            }}
          >
            <Styled.a as={Link} to={link.path}>
              {link.label}
            </Styled.a>
          </Styled.li>
```
works well when using `gatsby develop` i.e. the styles are applied to components, however, using the same with production site (after `gatsby build ; gatsby serve public`) works only for the first render - navigating to a different page and going back makes the styles disappear.

According to theme-ui [docs](https://theme-ui.com/sx-prop) it should work properly with jsx pragma:

![image](https://user-images.githubusercontent.com/44570539/69258424-d85dbb00-0bbc-11ea-8960-5d70ca6b5fe6.png)

But it works only for `gatsby develop`

In the end, I fixed the problem with `gatsby build` by importing `css` from `theme-ui` and applying styles in this way:
```jsx
          <Styled.li
            key={link.label}
            css={css({        // added css() invocation
              listStyleType: `none`,
              padding: `0 1rem`,
              margin: "0",
            })}
          >
            <Styled.a as={Link} to={link.path}>
              {link.label}
            </Styled.a>
          </Styled.li>
```

I could not find any information in Gatsby/theme-ui docs that I should use the imported `css` function.

Even more confusing is that it looks like the styles are applied correctly without the `css` func on `gatsby develop` and not after `gatsby build`.

### Steps to reproduce

1. Clone my repo [https://github.com/pjeziorowski/talkoverflow](https://github.com/pjeziorowski/talkoverflow)
2. Replace 
```jsx
            css={css({
              listStyleType: `none`,
              padding: `0 1rem`,
              margin: "0",
            })}
```
with
```jsx
            css={{
              listStyleType: `none`,
              padding: `0 1rem`,
              margin: "0",
            }}
```
in `src/gatsby-theme-blog/components/header.js`
3. Execute `yarn install ; gatsby build ; gatsby serve public`
4. Go to [localhost:9000](http://localhost:9000)
5. Take a look at nav links - styles are applied. Go to different page e.g.`Posts` - styles disappear. 

EDIT:
One more thing I noticed - all of the above seems to apply to my custom components or components that I shadow. For example, original ` header.js` from `gatsby-theme-blog` does not use the `css` function - 
```jsx
        <Styled.a
          as={Link}
          css={{
            color: `inherit`,
            boxShadow: `none`,
            textDecoration: `none`,
          }}
          to={`/`}
        >
          {children}
        </Styled.a>
```
The styles are applied both with `gatsby develop` and `gatsby build`.

However, after shadowing this component, additional `css` func must be invoked otherwise the styles do not work as expected (again, during `gatsby build` only!).

### Expected result
1. If it's by design, it should be documented.
2. I would prefer to have more consistency between develop / build version of sites.

Let me know if I can be of any help.

**Comment by LekoArts** [comment]
Hi. Thanks for the issue!

Please copy that over to the Theme UI repository as its behavior and documentation is not maintained here. Thanks!

**Comment by pjeziorowski** [comment]
I was thinking about it but I also wonder if something inside `gatsby build` may be causing the issue as everything seems to work properly with `gatsby develop`...?`
