### ISSUE TITLE
Blazing fast claims may be overstated

### ISSUE THREAD

**Issue by jackmahoney** [gatsbyjs/gatsby#19668]
[Google PageSpeed Insights for gatsbyjs.org](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.gatsbyjs.org%2F) show a performance score not in keeping with Gatsby's "fast in every way" claim. 

![gatsby-screenshot](https://user-images.githubusercontent.com/1240270/69257086-c11dce00-0bba-11ea-9e64-141a604ac476.png)

**Comment by davwheat** [comment]
They say that Gatsby is blazingly fast. They never said anything about their own site ;)

**Comment by anuraghazra** [comment]
But chrome lighthouse audit's shows this, maybe there's some inconsistency .

![image](https://user-images.githubusercontent.com/35374649/69337956-25f32a00-0c88-11ea-82be-4d2404736b0c.png)

**Comment by jbampton** [comment]
[Google PageSpeed Insights in desktop mode](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.gatsbyjs.org%2F&tab=desktop) seems more consistent with what  @anuraghazra showed with the Chrome Lighthouse report in desktop mode.

![pagespeed-gatsbyjs-org-desktop](https://user-images.githubusercontent.com/418747/69338901-dfb1c100-0caf-11ea-9d0a-85f5b8dc7671.png)

**Comment by mtheoryx** [comment]
Can I ask an honest question....

Does this really matter, in the least bit?

I feel this should be closed. But, if you disagree, that is fine. But it seems to me we have mixed metrics measurement tools (of which we have no control over) being fixated on .... not the end product of actually using gatsby for something, but on the marketing site of the framework itself.

So, what would provide more value: Actual scores from actual sites built with the framework? OR the site trying to advertise the framework?

(Full disclosure: I completely understand the "yeah but your splinter vs board in your eye)" mentality... but it doesn't deserve an issue or any action, IMHO. Feel free to disagree and offer some **positive, actionable tasks that could and should be done.**

![bitmoji](https://render.bitstrips.com/v2/cpanel/718544a4-4b26-48e5-8e88-f14f24b50766-c3b45c6e-2943-4fd5-ab6e-fe23bffcb90b-v1.png?transparent=1&palette=1&width=246)

**Comment by LekoArts** [comment]
Lighthouse tends to be flaky sometimes - and as this isn't an actionable issue or something that needs to be addressed I'm closing it. Thanks for the issue though! We found some potential to lazy load some components: https://github.com/gatsbyjs/gatsby/pull/19713
