### ISSUE TITLE
Warning: You cannot change <Router history> in browser.js/HMR stops working when changing layout, template or page

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#1966]
When picking up work on #1765 (www) today I merged the current master. After that I started noticing that in `gatsby develop` whenever I changed a layout, template or page, HMR stopped working (until I reload the page). Console says `Warning: You cannot change <Router history>`:

![image](https://user-images.githubusercontent.com/21834/29851708-f4022a38-8d35-11e7-90eb-00815a3375d7.png)

I can reproduce this in www of the current master, too (Gatsby v1.9.10). Also tried v1.9.14 and run into the same. Searched and found #1913 and #1936 … confused now! ;-) `¯\_(ツ)_/¯`

**Comment by fk** [comment]
Seems I'm not the only one seeing this. @3axap4eHko not sure if this is related to your PR, but maybe you can take a look?

**Comment by jamesslock** [comment]
I am also having the same issue.

**Comment by stolinski** [comment]
+1

**Comment by fk** [comment]
@KyleAMathews Thank you! 🎉

**Comment by KyleAMathews** [comment]
Sorry for the slow fix here — gatsby 1.9.31 has the fix from https://github.com/gatsbyjs/gatsby/pull/2110
