### ISSUE TITLE
Lazy load more code in gatsbyjs.org

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#19678]
Gatsbyjs.org is getting a bit fat! We're loading some modules upfront that should be lazy loaded.

- prism-react-renderer is ~70kb and can be lazy loaded https://github.com/gatsbyjs/gatsby/blob/78a7858b755e3202efcfb95c179ec8506ad48827/www/src/components/code-block/index.js#L5
- react-modal is ~18kb and can be lazy loaded https://github.com/gatsbyjs/gatsby/blob/78a7858b755e3202efcfb95c179ec8506ad48827/www/src/components/layout.js#L6

A good example of where we're doing this already:
- https://github.com/gatsbyjs/gatsby/blob/78a7858b755e3202efcfb95c179ec8506ad48827/www/src/components/chart.js#L2

**Comment by pjeziorowski** [comment]
Opened a PR
