### ISSUE TITLE
[gatsby-plugin-mdx][gatsby-remark-images-contentful] missing createContentDigest functionn

### ISSUE THREAD

**Issue by brokeyourbike** [gatsbyjs/gatsby#19676]
## Description

I use MDX with contentful. When I use `gatsby-remark-images-contentful` plugin and build the project. It throw me the error (posted bellow).

I have created a separate [repo](https://github.com/brokeyourbike/gatsby-remark-images-contentful-test) for the `gatsby-remark-images-contentful` where I [required](https://github.com/brokeyourbike/gatsby-remark-images-contentful-test/commit/6185ecb42004776d7cb9610e2ca8561f1e64c909) the `createContentDigest` directly from `gatsby-core-utils`. In this case, plugin working correctly.

I think when the `gatsby-plugin-mdx` load the plugins, it's missing the `createContentDigest` function, and therefore error occurs. 

### Steps to reproduce

You can use any contentfull starter. And add `gatsby-plugin-mdx` to it. 
In the `gatsby-config.js`, add  `gatsby-remark-images-contentful` to the `gatsbyRemarkPlugins`, like so:

```javascript
{
  resolve: `gatsby-plugin-mdx`,
  options: {
    gatsbyRemarkPlugins: [
      {
        resolve: `gatsby-remark-images-contentful`,
        options: {
          maxWidth: 650,
          withWebp: true,
          backgroundColor: 'white',
          linkImagesToOriginal: false
        }
      },
    ]
  }
},
```

### Expected result

`gatsby-remark-images-contentful` plugin not throwing errors in the middle of the build process.
### Actual result

```
UNHANDLED REJECTION createContentDigest is not a function

  TypeError: createContentDigest is not a function

  - index.js:69 generateImagesAndUpdateNode
    [~]/[gatsby-remark-images-contentful]/index.js:69:25
```

**Comment by danhowitt** [comment]
I'm getting the exact same issue.
