### ISSUE TITLE
[gatsby-transformer-remark] Inline code isn't included in excerpt when using gatsby-remark-prismjs

### ISSUE THREAD

**Issue by chenesan** [gatsbyjs/gatsby#19679]
## Description

Inline code (i.e. `code`) isn't included in excerpt when using `gatsby-remark-prismjs`.

### Steps to reproduce

[Reproducer is here.](https://github.com/chenesan/gatsby-bug-repro)

Just run `yarn develop` and see the text in index page. 

In the markdown content there is an inline code. But the content in inline code isn't included in excerpt when using `gatsby-remark-prismjs`. 

I tried to dig into this and found out that `gatsby-remark-prismjs` will transform the `inlineCode` node to html node. Then when getting excerpt https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/extend-node-type.js#L449-L460 the content is ignored.

### Expected result

The text in inline code should also appeared in excerpt.

### Actual result

The text in inline code disappears in excerpt.

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Languages:
    Python: 2.7.10 - /Users/yishan/.pyenv/shims/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0.1
    Safari: 12.0
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11
    gatsby-remark-prismjs: ^3.3.24 => 3.3.24
    gatsby-source-filesystem: ^2.1.38 => 2.1.38
    gatsby-transformer-remark: ^2.6.37 => 2.6.37

**Comment by marceloschreiber** [comment]
It worked as expected here:

<img width="751" alt="Screen Shot 2019-11-26 at 11 26 24" src="https://user-images.githubusercontent.com/13343185/69641863-a9719a00-103f-11ea-9b8e-417666fd9735.png">

I'll try with the same versions you posted and see if I can reproduce.

### Environment tested
**System:**
OS: macOS Catalina 10.15.1
CPU: 2,8 GHz Quad-Core Intel Core i7
Shell: 5.7.1 /bun/zsh

**Languages:**
Python: 2.7.16

**Browsers:**
Chrome: 78.0.3904.108
Binaries:
Node: 12.6.0
Yarn: 1.17.3
npm: 6.9.0

**npmPackages:**
gatsby: ^2.17.11 => 2.17.11
gatsby-remark-prismjs: ^3.3.24 => 3.3.24
gatsby-source-filesystem: ^2.1.38 => 2.1.38
gatsby-transformer-remark: ^2.6.37 => 2.6.37

**Comment by chenesan** [comment]
@marceloschreiber Sorry maybe the text in the page is somehow misleading. In markdown content, the code text "Here Is My Code" is shown, but in excerpt it isn't. The excerpt should include the code text.
You can try removing gatsby-remark-prismjs then the "HERE IS MY CODE" will also appear in excerpt, which is correct behavior.
