### ISSUE TITLE
All the gatsby developed and displayed normally, but the HTML layout after the gatsby was built was disordered, the image SRC path was wrong, and the navigation link was not normal. Could you please tell me how to solve this?

### ISSUE THREAD

**Issue by ZhuningS** [gatsbyjs/gatsby#19681]
## Description

Describe the issue that you're seeing.
All the gatsby developed and displayed normally, but the HTML layout after the gatsby was built was disordered, the image SRC path was wrong, and the navigation link was not normal. Could you please tell me how to solve this?

### Steps to reproduce
gatsby build

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result
![yb](https://user-images.githubusercontent.com/38108376/69326365-a0bb4580-0c86-11ea-8354-748c9f36b24b.PNG)
We hope it can display normally as gatsby developed

What should happen?
We hope it can display normally as gatsby developed

### Actual result
![123](https://user-images.githubusercontent.com/38108376/69326341-91d49300-0c86-11ea-8007-93ddcceb2185.PNG)
What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

gatsby info --clipboard

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 10.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.10.4 => 2.10.5
    gatsby-plugin-intl: ^0.2.8 => 0.2.8
    gatsby-plugin-layout: ^1.1.0 => 1.1.0
    gatsby-plugin-react-css-modules: ^2.1.0 => 2.1.0
    gatsby-plugin-sass: ^2.1.0 => 2.1.0

**Comment by ZhuningS** [comment]
gatsby-node.js：
`
const replacePath = path => (path === `/` ? path.toLowerCase() : path.replace(/\/$/, ``).toLowerCase())

// Implement the Gatsby API “onCreatePage”. This is called after every page is created.
exports.onCreatePage = ({ page, actions }) => {
  const { createPage, deletePage } = actions
  console.log(page);
  const oldPage = Object.assign({}, page);
  // 删除尾部斜杠，除非页面为/
  page.path = replacePath(page.path);
  //是否生成新页面
  let createNews = false;
  if (page.path !== oldPage.path) {                                                                                                     
    // Replace new page with old page
    deletePage(oldPage);
    createNews = true;
  }
  //根据路由设置对应的layout层
  let excludes = [/cloud/,/product$/];
  // 
  let includes = [
    {r:/index/,l:'index'},//设置首页特定样式
    {r:/solution/,l:'solution'},
    {r:/recruit/,l:'recruit'},
    {r:/product/,l:'product'},
  ];
  let eArr = excludes.filter(r => page.path.match(r));
  let obj = includes.filter(({r,l}) => page.path.match(r))[0];
  if(eArr.length) {

  }else if(obj){
    page.context.layout = obj.l;
    createNews = true;
  }
  // console.log('node-page',page);
  createNews && createPage(page);
};
`

**Comment by graysonhicks** [comment]
Can you link to a repo or codesandbox to reproduce this issue?
