### ISSUE TITLE
The tutorial's development environment setup page is misleading for Windows users

### ISSUE THREAD

**Issue by nickmccurdy** [gatsbyjs/gatsby#19687]
https://www.gatsbyjs.org/tutorial/part-zero/

This part of the tutorial seems to imply that Homebrew has native Windows support. This is not accurate, only the Linux version of Homebrew is supported on WSL, which not all users have installed or know how to use. It's also in beta, not stable.

As a result, it would be better to have a separate section for installing Node on Windows, either using Chocolatey (which is similar to Homebrew) or the official installer.

Alternatively, we could scrap this info and just link to the Node installers/docs, which has sections for each OS.

**Comment by laurieontech** [comment]
Thanks for opening this! You're absolutely right that these docs need improvement for non Mac users.

The issue for it is #15529
and the PR that's working on this particular page is #18262 

I'm going to close this issue in favor of those. But we'd welcome your feedback or review on the proposed write up!

**Comment by nickmccurdy** [comment]
Thanks for following up, and sorry for the duplicate!

**Comment by laurieontech** [comment]
It's perfectly ok! So many issues and PRs to keep track of. Duplicates are to be expected sometimes :) And in this case is further drives home how important this set of docs is.
