### ISSUE TITLE
SASS includePaths in Grommet 1.7 & Gatsby 1.8

### ISSUE THREAD

**Issue by DisruptiveMind** [gatsbyjs/gatsby#1968]
Hi,

I'm just playing around with Gatsby + Grommet...

I was having some issues trying to get Grommet 1.7 + Gatsby 1.8 to play nice due to the `includePaths` option. I found a workaround but would like some direction on the proper way or if I'm missing some details.

I know there is the related starter [gatsby-starter-grommet](https://github.com/alampros/gatsby-starter-grommet) that has a custom plugin that extends `gatsby-plugin-postcss-sass`.

I ran into the issue with `options.includePaths.push is not a function`.

I'm able to _hijack_ the `precision` option and just add my `includePaths` option as follows:

```javascript
{
      resolve: `gatsby-plugin-postcss-sass`,
      options: {
        precision: `8&includePaths[]=${path.resolve(__dirname, './node_modules')}`,
        postCssPlugins: [
          autoprefixer({
            browsers: ['last 2 versions'],
          })
        ]
      }
    }
```

This feels dirty, is there a better way?

**Comment by jquense** [comment]
You can add any options to the sass-loader via the plugin options there:
```
options: {
        precision: 8,
        includePaths: [path.resolve(__dirname, './node_modules')],
        postCssPlugins: [
          autoprefixer({
            browsers: ['last 2 versions'],
          })
        ]
      }
```

should just work

**Comment by jquense** [comment]
oops sorry no it doesn't...we should fix that

**Comment by DisruptiveMind** [comment]
@jquense It never worked for me

**Comment by DisruptiveMind** [comment]
I can create a PR on it since it seems to be quick.
