### ISSUE TITLE
Remark internal links to use Gatsby Link

### ISSUE THREAD

**Issue by brendanator** [gatsbyjs/gatsby#19688]
## Summary

If I include a internal links in a markdown file that is transformed by gatsby-transformer-remark they should be rendered using gatsby Link component

### Basic example

```md
This [internal link](/faq) should be a Gatbsy Link
But this is [external](https://example.org) so shouldn't
```

### Motivation

The user experience for prefetched pages is great. It would be amazing to extend that to markdown generated code

**Comment by brokeyourbike** [comment]
@brendanator  You can safely switch to [MDX plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/)

then define [custom component](https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/#mdxprovider) for the **a** tag, and in this new component you can use any checks specific for your use case, to check if this link is internal or external. For example something like this:

```javascript
import React, { Component } from 'react'
import { MDXProvider } from "@mdx-js/react"
import navigateHelper from './navigateHelper'

class MyA extends Component {
  constructor(props) {
    super(props)
    this.handleClick = this.handleClick.bind(this)
  }

  handleClick(e) {
    e.preventDefault()
    const { href } = this.props
    if (href) {
      return navigateHelper(href)
    }
  }

  render() {
    return <a onClick={this.handleClick} {...this.props} />
  }
}

const components = {
  a: MyA,
}

export const wrapRootElement = ({ element }) => (
  <MDXProvider components={components}>{element}</MDXProvider>
)
```

`navigateHelper.js`
```javascript
import { isString } from 'lodash'
import { navigate } from 'gatsby'

const navigateHelper = link => {
  if (isString(link)) {
    if (link.charAt(0) === '/' && link.charAt(1) !== '/') {
      return navigate(link)
    } else {
      return (window.location.href = link)
    }
  }
}

export default navigateHelper

```

this code should work for this type of links, since internal links should not have `//`
```
This [internal link](/faq) should be a Gatbsy Link
But this is [external](//example.org) so shouldn't
```

**Comment by mathieudutour** [comment]
> You can safely switch to MDX plugin

Not necesserary: `<SomeJSXComponentOutsideScope>` is valid markdown but not valid mdx.

I do think there is value in having internal links go through Gatbsy Link. Seems like an easy performance win for blogs based on md.

**Comment by LekoArts** [comment]
Thank you for opening this!

You can use this plugin: https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/
Both in MD and MDX or with content coming from a CMS.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
