### ISSUE TITLE
Improve warning when multiple pages have the same path

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#19689]
@laurieontech and I were just pairing and she made a great point about how the duplicate page path warning is _very_ easy to miss. Here's what it looks like:
<img width="1018" alt="Screenshot 2019-11-21 at 8 39 22 PM" src="https://user-images.githubusercontent.com/7701981/69350155-05829a00-0c9f-11ea-87cd-55d661905d2e.png">
(Try to find it 😛)

In case you couldn't (we don't blame you), the warning currently says:

> warn Attempting to create page "/page-2/", but page "/page-2" already exists. This could lead to non-deterministic routing behavior

We could do one of the following:
- Make this warning bigger and more noticeable
- Make this a structured error instead (that would be a breaking change though)

**Comment by pjeziorowski** [comment]
@sidharthachatterjee Do you think this looks good?

![Screenshot 2019-11-22 at 1 04 08 PM](https://user-images.githubusercontent.com/44570539/69424343-a79a9480-0d28-11ea-9a5a-ca7000c63ebc.jpg)


Added some colours and split the text into two lines.

I also noticed that at the moment the warning is only printed for duplicate paths that differ only with ending slash i.e.

for `/page-2/` and `/page-2` the warning **IS** printed
for `/page-2/` and `/page-2/` the warning **IS NOT** printed

Is it desired behaviour? I would expect the warning is also printed when the paths are exactly the same.

**Comment by laurieontech** [comment]
I'd also expect to see the warning in both cases.
What you've shown above is certainly an improvement. I'm still concerned about this getting lost among many other warnings, but unless we're going to change it to an error I don't see a way around that.

**Comment by cangSDARM** [comment]
I meet same problem. When I want to create a page under `src/pages` directory using `createPages` API manually, it caused same warning. Perhaps using `onCreatePage` instead of `createPages` is a potential solution, but I think it's create-time problem. What is the order inside gatsby when creating a page? I hope it is in this order: `gatsby create a page -> plugin create a page -> manually create a page`. Sorry for my English : )

**Comment by sidharthachatterjee** [comment]
@pjeziorowski Sorry for missing your comment and thank you for fixing!

Fixed in https://github.com/gatsbyjs/gatsby/pull/19719
