### ISSUE TITLE
Default nerv alias

### ISSUE THREAD

**Issue by janat08** [gatsbyjs/gatsby#19694]
## Summary
I feel like nerv should be better supported for it's speed.

### Basic example
A plugin, that you may as well make default (I don't know that the API parity 💯 but it's certainly a goal of nerv).

### Motivation
Currently there's a very old plugin for nerv that it claims that it doesn't work, although apparently nerv just works with next. Nerv initializes much faster than react and is lighter. I've never found article addressing how you deal with uncanny valley (no event handlers), but nerv will help either way.

**Comment by LekoArts** [comment]
Thank you for opening this!

We currently don't plan on integrating this into core, however you can create a plugin if you want similar to preact: https://www.gatsbyjs.org/packages/gatsby-plugin-preact/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by janat08** [comment]
https://hashnode.com/post/nerv-alias-plugin-better-preact-ck3frvk1s007toms1b6tuvi77
https://hashnode.com/post/uncanny-valley-no-event-handlers-on-initial-load-ck3frt10i007qoms1rpja4hp7
