### ISSUE TITLE
Show React component on service worker update

### ISSUE THREAD

**Issue by davwheat** [gatsbyjs/gatsby#19705]
I'm using `gatsby-plugin-offline` to allow for offline use on my site.

I'm familiar with `onServiceWorkerUpdateReady` insite `gatsby-browser.js` but, using the browser js file, you can't do much in terms of changing page content React-wise.

Is there any way to using a React library to display a message when an update is available?

For example, I'm using **notistack**, a Material library for Snackbars. I have managed to create a function that shows a persistent snackbar saying an update is available:

```jsx
const { enqueueSnackbar } = useSnackbar()

// ...

() => {
  enqueueSnackbar(`This site has been updated.`, {
    action: () => (
      <Button
        aria-label="Refresh page"
        onClick={() => {
          window.location.reload()
        }}
        color="inherit"
      >
        Refresh
      </Button>
    ),
    persist: true,
    variant: "info",
  })
```

![](https://puu.sh/EHd9l/26de10e927.png)

The only issue is that it needs to use a React Hook, which you can't do in `gatsby-browser.js`. The library also supports `withSnackbar` for functional components, but that won't be much use either.

Is there any way around this? I was thinking assigning a variable if an update is available, but that seems 'janky' and difficult to detect the change in React.

**Comment by cactoo** [comment]
Hi, take a look at my solution, works pretty neat. It will check for app update every 30 minutes and when it's found, it will show button allowing to do update and will activate new Service Worker.
https://gist.github.com/cactoo/d3c5031d86a2a210a2024a3466907006

What I did, step by step:
1) In _gatsby-browser.js_ file set `window.___swUpdated` to false to prevent auto update on page navigation. (optional)

2) In _gatsby-config.js register custom Service Worker ([line 42](https://gist.github.com/cactoo/d3c5031d86a2a210a2024a3466907006#file-gatsby-config-js-L42)) and modify workbox config (set `skipWaiting` to false - [l30](https://gist.github.com/cactoo/d3c5031d86a2a210a2024a3466907006#file-gatsby-config-js-L30))

3) Add custom SW file, handling `skipWaiting` message from browser

4) Create UpdateButton component where most of the magic happens. The key is to understand how Service Worker updates and what are its states (_updating, waiting, redundant). Then watch for these changes.

Next recommended lectures:
- https://developers.google.com/web/fundamentals/primers/service-workers
- https://redfin.engineering/how-to-fix-the-refresh-button-when-using-service-workers-a8e27af6df68

![image](https://user-images.githubusercontent.com/11618314/69634060-c1521980-1051-11ea-97ca-e400a190701b.png)

**Comment by sidharthachatterjee** [comment]
@davwheat Can't answer this any better than @cactoo has already. 

@cactoo Thank you so much for the detailed answer. Would you like to maybe write a blog post or a docs page for us on how you approached this? I think a lot of people might find it useful!

Anyway, closing this issue for now. Thank you, both of you! 💜

**Comment by cactoo** [comment]
I created __[service-worker-updater](https://www.npmjs.com/package/service-worker-updater)__ package checking for app (and service worker) updates. It works well with Gatsby, [here is sample app](https://github.com/cactoo/gatsby-update-button). 😁

Also here's an article explaining my approach:
https://www.ziebikiewicz.com/adding-update-button-to-gatsby-app

@sidharthachatterjee maybe something to be mentioned in the docs? :)
