### ISSUE TITLE
Gatsby Docz Tutorial

### ISSUE THREAD

**Issue by astridx** [gatsbyjs/gatsby#19706]
Today I did the Step-by-Step Tutorial (Part 1 to 8) and everything works fine. Thank for this.

My goal is to use Gatsby for a documentary. So, after that I did the Docz Tutorial (https://www.gatsbyjs.org/tutorial/writing-documentation-with-docz/)

Here I get an Error

`return <Img fluid={data.placeholderImage.childImageSharp.fluid} />
`
![Home   Gatsby Default Starter(1)](https://user-images.githubusercontent.com/9974686/69380102-05d86080-0cb2-11ea-883e-01652a0c9e50.png)

At first, I thought I was doing something wrong. Therefore, the instructions have been done again. But also on the second attempt came after` gatsby -serve `again this message in the Browser.

What have I done wrong?

**Comment by astridx** [comment]
Thanks for reopening the issue.

I have now worked through the tutorial again. I think the following should be changed:

1. Add `docz@next` to `npm install --save gatsby-theme-docz@next`
2. In component/image.js we should change

```
    query {
      placeholderImage: file(relativePath: { eq: "gatsby-astronaut.png" }) {
        childImageSharp {
          fluid(maxWidth: 300) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
```
to

   ```
 query {
      placeholderImage: file(relativePath: { eq: "src/images/gatsby-astronaut.png" }) {
        childImageSharp {
          fluid(maxWidth: 300) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
```

So we should add the `src/images`

If you also consider it good and comment on this here, I would submit a PR.

**Comment by laurieontech** [comment]
Thanks for the additional info @astridx! From the looks of it the `gatsby-source-filesystem` plugin may not be configured correctly. Can you look at your `gatsby-config.js` file and let us know what the path configuration for that plugin is? There may be multiple instances of it.

**Comment by sidharthachatterjee** [comment]
@astridx We fixed the first issue in the documentation! Thanks again for pointing that out. 

With respect to the second one, `gatsby-astronaut.png` should work just fine as long as you have the following in your `gatsby-config.js` file (which is included in the default starter)

```
{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
```

Thanks!
