### ISSUE TITLE
Using image in markdown as a link to an external site

### ISSUE THREAD

**Issue by mrbjjackson** [gatsbyjs/gatsby#19701]
I want to add links to images in my .mdx powered markdown link to external sites. I would also like to add the "target:_blank" attribute to the link tag.

I've tried wrapping the images in an html anchor tag like so:
```
<a href="https://www.externalsite.com" target="_blank">
![Local Image](../images/sites/localimage.jpg)
</a>

```
but wrapping the image markdown in an anchor tag causes the image to no longer be rendered by the markdown renderer (I'm using MDXRenderer.

Is there a way to accomplish this or must I use a normal image tag and miss out on all that juicy Gatsby image loading goodness?

Thanks very much,
Ben

**Comment by LekoArts** [comment]
Thank you for opening this!

You can use normal markdown syntax to wrap the image with a link:

```md
[![text](image)](link)
```

You can also use this plugin to add attributes to external links:
https://www.gatsbyjs.org/packages/gatsby-remark-external-links/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
