### ISSUE TITLE
ContentfulAssets localFile node is missing in the graphql query result with gatsby v2.18.0+

### ISSUE THREAD

**Issue by gitsaysno** [gatsbyjs/gatsby#19716]
### Description

Seems like localFile node from gatsby-source-contentful is missing in graphql with the release of gatsby 2.18.0. Worked in gatsby 2.17.17. 

Gatsby 2.18.0 missing localFile:
![gatsby_localfile_2 18 0](https://user-images.githubusercontent.com/988605/69429771-a0798380-0d34-11ea-86ee-87691d4f34ba.png)

Gatsby 2.17.17 not missing localFile:
![gatsby_localfile_2 17 17](https://user-images.githubusercontent.com/988605/69430028-2eee0500-0d35-11ea-8342-755e38933f93.png)

### Steps to reproduce

Install gatsby 2.18.0 (or higher), add "downloadLocal: true" in gatsby-source-contentful in gatsby-config.js and connect to contentful with assets. Check GraphiQL IDE and localFile node is missing. If you install gatsby 2.17.17 localFile node exist.

### Expected result

Expected localFile node to exist in the graphql query result.

### Actual result

localFile node didnt exist in the graphql query result.

### Environment

  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.18.0 => 2.18.0
    gatsby-background-image: ^0.9.6 => 0.9.6
    gatsby-image: ^2.2.30 => 2.2.33
    gatsby-plugin-google-analytics: ^2.1.23 => 2.1.28
    gatsby-plugin-google-tagmanager: ^2.1.15 => 2.1.17
    gatsby-plugin-gtag: ^1.0.11 => 1.0.11
    gatsby-plugin-hotjar-tracking: ^1.0.0 => 1.0.0
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5
    gatsby-plugin-manifest: ^2.2.29 => 2.2.29
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.15
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.3.2 => 2.3.2
    gatsby-plugin-sitemap: ^2.2.19 => 2.2.21
    gatsby-source-contentful: ^2.1.62 => 2.1.62
    gatsby-source-filesystem: ^2.1.38 => 2.1.38
    gatsby-transformer-remark: ^2.6.32 => 2.6.37
    gatsby-transformer-sharp: ^2.3.2 => 2.3.5
  npmGlobalPackages:
    gatsby-cli: 2.8.8

**Comment by lordoffreaks** [comment]
I think the problem is in `gatsby-source-filesystem`, I'm using `createRemoteFileNode` and getting the same error now

**Comment by gitsaysno** [comment]
The latest release fixes the issue. 🥇

**Comment by vladar** [comment]
The root cause of the issue is actually in the plugin. See the follow-up issue for some details #19876
