### ISSUE TITLE
[question] how to import dependency as CSS module?

### ISSUE THREAD

**Issue by stefanmaric** [gatsbyjs/gatsby#1971]
Hi!

So I have this package `some-styles` in the npm registry which all it has is a `index.css` file and its `package.json`'s `main`, `module` and `style` fields point to `index.css`.

And I have a Gatsby project which has `some-styles` as a dependency. Inside a component, I want to import this dependency as a CSS Module.

Doing `import styles from 'some-styles'` imports it as a global style.

Haven't found a way to configure this so I'm looking for a bit of guidance.

Thanks!

```
node@8.4.0
npm@5.3.0
gatsby@1.8.12
```

**Comment by KyleAMathews** [comment]
Gatsby only treats css files named `filename.module.css` as css modules.

So it might work to rename your `index.css` to `index.module.css` or better probably to just modify Gatsby's webpack config to use css modules for your particular package https://www.gatsbyjs.org/docs/add-custom-webpack-config/

**Comment by stefanmaric** [comment]
Thanks for the feedback @KyleAMathews.

After a lot of trial and error I got to this which seems to work well so far:

```javascript
// gatsby-node.js
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const { cssModulesConfig } = require('gatsby-1-config-css-modules')

const packages = ['griddity'].join('|')
const modulePath = new RegExp(`node_modules\\/${packages}\\/.*?\\.css$`)

exports.modifyWebpackConfig = ({ config, stage }) => {
  switch (stage) {
    case 'develop':
      config.loader(`customCssModule`, {
        test: modulePath,
        loaders: [`style`, cssModulesConfig(stage), `postcss`]
      })

      break

    case 'build-css':
    case 'build-html':
    case `develop-html`:
    case 'build-javascript':
      config.loader(`customCssModule`, {
        test: modulePath,
        loader: ExtractTextPlugin.extract(`style`, [
          cssModulesConfig(stage),
          `postcss`
        ])
      })

      break
  }

  config.loader(`css`, {
    exclude: modulePath
  })

  return config
}
```

I basically copy&pasted all the rules inside gatsby's webpack config that match `module.css` and applied them to the path that resolves the relevant packages. Then modifying the `css` rule to exclude that same path, preventing it from being double-loaded.

I had to name the loader other than `cssModule`, otherwise I get an error, that makes me think it is still double-loaded, but I don't actually understand why:

```shell
info bootstrap finished - 1.496 s

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                               23:09:11

 error  in ./~/griddity/griddity.css

Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../css-loader/index.js?modules&minimize&importLoaders=1&localIdentName=[path]---[name]---[local]---[hash:base64:5]&sourceMap!../postcss-loader/index.js!./griddity.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // add the styles to the DOM
  7 | var update = require("!../style-loader/addStyles.js")(content, {});


 @ ./~/griddity/griddity.css 4:14-370 13:2-17:4 14:20-376
```
Anyway, I got it working but... is it well enough? Or is there a simpler way?

Thanks!

**Comment by KyleAMathews** [comment]
Nice! This looks pretty reasonable. I'd imagine webpack gives you 5 other ways to solve the problem but just adding a new loader stack for your css seems like it works well enough.

**Comment by NerdCowboy** [comment]
@KyleAMathews 
>Gatsby only treats css files named filename.module.css as css modules.

I've spent way too much time trying to figure out why my css modules weren't working, so would like to make sure other folks are aware of this.

I'd submit a PR to update the docs for `gatsby-plugin-react-css-modules`, but it appears it's only on npm—can you update or publish it so we can get this added?
