### ISSUE TITLE
How to override or intercept default anchor link clicks?

### ISSUE THREAD

**Issue by jonauz** [gatsbyjs/gatsby#19728]
How to override or take control of page anchors when they being clicked?
Is it possible some how within `gatsby-browser.js`?
In our case default is not working, because we need to scroll not the main page but content in one of div elements.
And content is build using remark transformer, there for don't have direct access to link components, and don't want to handle each small peace separately from Markdown files.

**Comment by sidharthachatterjee** [comment]
You should be able to do something similar to https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-catch-links but only for anchor links
