### ISSUE TITLE
First Input Delay (FID) Metric Consistently Does Not Pass in Lighthouse

### ISSUE THREAD

**Issue by graysonhicks** [gatsbyjs/gatsby#19729]
## Summary
Gatsby prides itself on building blazing fast, performant websites.  This is often measured using third-party tools like Google Lighthouse dev tools.  One of the metrics Lighthouse uses is First Input Delay (FID), described by Philip Walton as:

> First Input Delay (FID) measures the time from when a user first interacts with your site (i.e. when they click a link, tap on a button, or use a custom, JavaScript-powered control) to the time when the browser is actually able to respond to that interaction.
_source_: [here](https://developers.google.com/web/updates/2018/05/first-input-delay?utm_source=lighthouse&utm_medium=devtools)

I have audited dozens of Gatsby sites, and only a small handful pass.  Most outperform standard React or other types of sites, but they still do not pass the threshold set by Lighthouse.  I believe it Gatsby is going to continue to pride itself on performance, and often tout Lighthouse scores, that any metrics that are not passing consistently need to be investigated and improved.

### Examples/Reproducing

To test this, I tested several sites built for clients with Gatsby, but the same behavior can be replicated for any Gatsby site.  One place to look around is the sites featured on the [showcase](https://www.gatsbyjs.org/showcase/).

To test, visit one of the sites with Chrome (I believe other dev tools also audit this metric?) and under the Performance tab, you will see the 'Max Potential First Input Delay' metric (in milliseconds).

I am testing on a fast internet connection (400mb/s down) with caching having no effect on this metric.  Here are some example numbers:

https://reactjs.org/ - 500ms
https://airbnb.io/ - 210ms
https://impossiblefoods.com/ - 200ms

### Motivation + Resources

This metric is relatively new to the Lighthouse audit, so I think it's important Gatsby stays on top of it and shows it can build sites that address it consistently.  Here are a few resources for possible strategies that can make the JS produced by Gatsby more performant in this area.

https://philipwalton.com/articles/idle-until-urgent/
https://www.sitepen.com/blog/reducing-first-input-delay-for-a-better-user-experience/
https://premium.wpmudev.org/blog/how-to-improve-google-pagespeed-user-interaction-metrics-in-wordpress/

I have not found any Gatsby specific resources on this issue, and hope this is something that can be investigated and improved, as it is consistently the only red metric for performance on Gatsby sites.

**Comment by benjamingrobertson** [comment]
For added context - I received some error notifications in Google Search Console this week that pages on https://frontendremotejobs.com (a Gatsby site) are failing the FID metric, so it seems to be a metric that will impact or is already impacting search results.

**Comment by KyleAMathews** [comment]
This measure is an interesting one. 

It's defined at https://web.dev/lighthouse-max-potential-fid/

>Max Potential FID measures the worst-case First Input Delay that your users might experience. First Input Delay measures the time from when a user first interacts with your site, such as clicking a button, to the time when the browser is actually able to respond to that interaction.
>
>Lighthouse calculates Max Potential FID by finding the duration of the longest task after First Contentful Paint. Tasks before First Contentful Paint are excluded because it's unlikely that a user will attempt to interact with your page before any content has been rendered to the screen, which is what First Contentful Paint measures.

Gatsby sites are _perhaps_ more prone to higher Max FID due to React hydration as that's a fairly long task. Also ironically because our FCP is faster than other client-side apps due to SSR so React hydrating can cause input delay. The React's team work on partial hydration will be huge here as it'll mean React will do block the main thread for shorter periods of time.

Other common sources of FID is larger JS bundles — particularly later arriving ones. 3rd party scripts, etc.

In this trace of frontendremotejobs.com — it looks like the main problems are evaluating JS & rendering. Rendering & workbox coming in are causing the second busy thread period https://www.webpagetest.org/result/191123_TY_59d444590ff0352eed20a56895921cfe/1/details/#waterfall_view_step1

**Comment by KyleAMathews** [comment]
reactjs.org is fast if you test other pages. The frontpage loads in the entire babel.js toolchain to power their live updating code editor. It'd be nice if that was lazy loaded.

Impossiblefoods.com has tons of 3rd party scripts & a lot of big widgets they load all upfront.

**Comment by KyleAMathews** [comment]
So the solution here is the same as elsewhere — load less JS upfront & lazy load the rest later in smaller bundles to avoid blocking the main thread.

**Comment by graysonhicks** [comment]
I agree that the fast paint, plus wait for hydration is probably the issue.  And also, not 100% sold on this metric.  But thought it was important to note since it seems to be the hardest one to 'turn green' on a DevTools report for me.

> So the solution here is the same as elsewhere — load less JS upfront & lazy load the rest later in smaller bundles to avoid blocking the main thread.

I agree with this overall, but perhaps a guide for implementing would be helpful. Gatsby uses 'route-based' code-splitting out of the box, which works great by default for many sites.  I have used [https://github.com/smooth-code/loadable-components](loadable-components) to dynamically import some hefty components with Gatsby, but the SSR guide for loadable-components doesn't fit the Gatsby API cleanly, and not sure I have implemented it as intended (it does create a new bundle but can cause page jumps, etc).  Would love to see a guide for lazy-loading components with Gatsby specifically as that may help with this metric at times, and be useful overall.

**Comment by KyleAMathews** [comment]
>And also, not 100% sold on this metric

Yeah... my main complaint is it's confusing — it takes the longest period of thread blocking within the first 5 seconds after FCP. Which a user _could_ happen to be interacting with the page during that time but they're not necessarily going to. So a synthetic probability-based score seems more useful e.g. this is the probability that a user is going to have trouble — as that would distinguish between a site that has one 100ms long task vs. one that has e.g. five 75ms long tasks which would be worse.

They're really focused on a quiet main thread which is tough if you're lazy loading bundles & 3rd party scripts.

**Comment by graysonhicks** [comment]
So I am good to close this, but was looking for some relevant core React issues regarding partial hydration since that should help alleviate this issue.  Would be nice to have this issue linked to that, since I expect Gatsby will leverage whatever those improvements in React are, probably without needing a ton of changes itself.

For now, [this umbrella issue on Suspense](https://github.com/facebook/react/issues/13206) mentions partial hydration so I'll leave it here, but @KyleAMathews if you know of a better issue to track feel free to add it.

**Comment by KyleAMathews** [comment]
This tweetstorm from Dan Abramov is great. Perhaps the best current info.

https://twitter.com/dan_abramov/status/1200111677833973760?s=19
