### ISSUE TITLE
Add Docker environment for WordPress Site with WPGraphQL, WP Gatsby and a Gatsby site for testing in Circle CI

### ISSUE THREAD

**Issue by jasonbahl** [gatsbyjs/gatsby#19734]
As we work on the Gatsby Source GraphQL v4, we'll want to be able to run tests against a WordPress install in CI. 

We'll need to be able to spin up a WordPress site with a consistent dataset (possibly something like WPTest.io data) that the Gatsby site can build from. 

This will allow us to make assertions against the WP site and the Gatsby site, such as: 

- [ ] Does the Gatsby site have the same content as the WP site?
- [ ] Does the Gatsby site include the same pages/posts/users as the WP Site?
- [ ] Does searching on the Gatsby site execute and return results (by actually fetching the WP site)?
- etc...

**Comment by shrthnd** [comment]
@jasonbahl is this still an issue? 

For what it's worth, here's a link to a docker + docker-compose boilerplate I use for rapid wordpress development: https://gitlab.com/helpful.dev/docker-wordpress

Image/container-wise this relies on php7fpm-alpine, mariadb, and an extra nginx-alpine container to save about ~100mb between the standard wordpress + mysql images. It also works well in production behind a [reverse-proxy](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/).

Recently I've been using this for plugin development in WordPress 5.0 - 5.4 (with an add'l volume mapped to a single copy of my plugin) with zero issues standing-up and tearing down these projects repeatedly. 

If you uncomment [this line](https://gitlab.com/helpful.dev/docker-wordpress.git) and add a .sql file to the `./mysql-dump/` your backup should be restored to the database container once it's had a chance to warm up (the database name should match the database defined in the .env.)   

I know all the cool kids might be running kubernetes on the raspberry pi clusters these days, but this setup works for me and might be useful for anyone working in this direction. There's plenty of room for improvement but felt like it might be help spur some discussion here. I'm not too familiar with CircleCI but it looks like there is support for docker-compose. 

Hope this helps. If not, no worries!
