### ISSUE TITLE
How do I append `/index.html` to the end of every <a> href route link in my Gatsby build files?

### ISSUE THREAD

**Issue by drake-smith** [gatsbyjs/gatsby#19736]
## Summary
The routes in my index.html files are relative urls (ie. `<a href="/articles/article-title" />`). I am being asked by IT to add /index.html at the end of every url (making it `<a href="/articles/article-title/index.html" />` because their server is not set up to return the index.html file automatically. 

I tried adding `/index.html` to some links and testing in`gatsby develop` but I get 404s in develop.

Is this possible in the Gatsby build process? If so, how might I be able to?

## Relevant information

    "gatsby": "^2.16.1",
    "gatsby-image": "^2.2.29",
    "gatsby-plugin-catch-links": "^2.1.15",
    "gatsby-plugin-favicon": "^3.1.6",
    "gatsby-plugin-manifest": "^2.2.23",
    "gatsby-plugin-offline": "^3.0.16",
    "gatsby-plugin-react-helmet": "^3.1.13",
    "gatsby-plugin-sass": "^2.1.20",
    "gatsby-plugin-sharp": "^2.2.31",
    "gatsby-plugin-sitemap": "^2.2.19",
    "gatsby-plugin-svgr": "^2.0.2",
    "gatsby-source-contentful": "^2.1.49",
    "gatsby-source-filesystem": "^2.1.33",
    "gatsby-transformer-remark": "^2.6.30",
    "gatsby-transformer-sharp": "^2.2.23",

**Comment by michaellopez** [comment]
@drake-smith Maybe you could try what [`gatsby-plugin-remove-trailing-slashes`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-remove-trailing-slashes/src/gatsby-node.js) is doing in `onCreatePage`. But instead of removing trailing slash you would add `index.html` to all paths that end with `/`. I'm not sure it would work but its the only thing I can think of right now.

Then as the notes state for `gatsby-plugin-remove-trailing-slashes` you have to make sure all your `Link`s are correct and pointing to `.../index.html`.

**Comment by michaellopez** [comment]
@drake-smith I actually tested this out really fast and it works as I expect. Is this what you want?
```js
// gatsby-node.js
exports.onCreatePage = ({ page, actions }, { suffix }) => {
  const { createPage, deletePage } = actions;

  return new Promise(resolve => {
    const oldPage = Object.assign({}, page);
    page.path += 'index.html';
    if (page.path !== oldPage.path) {
      deletePage(oldPage);
      createPage(page);
    }
    resolve();
  });
};
```

Then include `'gatsby-plugin-path-suffix'` in your `plugins` array inside `gatsby-config.js`

Also don't forget to use `<Link to="/about/index.html">About</Link>`, only using `/about` will work, but Gatsby will redirect you...it isn't pretty

**Comment by sidharthachatterjee** [comment]
Can't answer this better than @michaellopez already has! Their example should have you covered. 

Let's close this issue for now. Thanks both of you! 💜

**Comment by jtwoodru** [comment]
@michaellopez , this solution nearly works for me as well. Experiencing a similar situation as @drake-smith , site 404s on refresh in client's environment and IT has asked us to add index.html to all links and urls.

Solution works for all my pages, except the home page and 404 page. Not sure of everything that might be going on, but here are a few things I'm seeing in my build that appear problematic:

- The /index directory is rewritten as /index.html (just to be clear, it's folder named "index.html")
- 404.html is rewritten as 404.htmlindex.html
- The /404 directory receives an /index.html directory (another folder named "index.html")

Not sure if this is illuminating or not, and if anyone has ideas? Any help is much appreciated.

**Comment by foxaltus** [comment]
Yeah doesn't work for me either (same as @jtwoodru)... has anyone found a valid solution?
