### ISSUE TITLE
Create WordPress source site that is updated with WPGraphQL and WPGatsby whenever there are releases

### ISSUE THREAD

**Issue by jasonbahl** [gatsbyjs/gatsby#19733]

**Comment by webmaeistro** [comment]
@jasonbahl hi, I got a project where  wp had to be the crm (Minimal wp experience, I was a drupalist before Gatsbyjs) but I had this idea of maybe using a pantheon or platformsh spin up that sets to rebuild when the dep. repo's update..? id greatly appreciate any help with setting up a old wp as source and I'll help in any way I can back. :)
