### ISSUE TITLE
Broken links to https://gatsby.dev

### ISSUE THREAD

**Issue by janedotbiz** [gatsbyjs/gatsby#19742]
## Description

In the default starter (and perhaps elsewhere, I have not searched the whole repo) there are links to https://gatsby.dev but this site does not load at all.

These broken links can be found in these 3 files here in the default starter:

- https://github.com/gatsbyjs/gatsby/blob/master/starters/default/package.json#L35
- https://github.com/gatsbyjs/gatsby/blob/master/starters/default/src/components/image.js#L12
- https://github.com/gatsbyjs/gatsby/blob/master/starters/default/gatsby-config.js#L31

### Steps to reproduce

Visiting these three urls:

- https://gatsby.dev/unit-testing
- https://gatsby.dev/gatsby-image
- https://gatsby.dev/offline

### Expected result

Should load the content at these equivalent pages:

- https://gatsbyjs.org/docs/unit-testing
- https://gatsbyjs.org/docs/gatsby-image
- https://gatsbyjs.org/docs/add-offline-support-with-a-service-worker/

### Actual result

 Results in a `This site can’t be reached gatsby.dev refused to connect.` error message

### Environment

This is the case in Chrome (75.0.3770.100) and Firefox (70.0.1) on macOS (10.14.6)

-----

I’d be happy to help replace broken links _if_ the intention is that `https://gatsby.dev` is no longer expected to exist.

**Comment by sidharthachatterjee** [comment]
Thank you for the detailed issue @janedotbiz 

gatsby.dev is back up, looks like it was a temporary issue. All links work fine now. 

Let's close this 🙌
