### ISSUE TITLE
CSS missing/class name changing after initial site load in production

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#19751]
When opening [this site](https://janosh.io) ([repo](https://github.com/janosh/janosh.io)) with clean cache on a mobile-sized screen, the navbar is missing some CSS and displaying (it should be hidden). After reloading the page, everything looks as expected, likely due to the fact that the navbar changes its class name and appropriate CSS is now applied. This only happens in production. `gatsby develop` does not exhibit this behavior even with cleared cache.

I thought it might be an issue with my setup for `styled-components` but revisiting the instructions for [`gatsby-plugin-styled-components`](https://www.gatsbyjs.org/packages/gatsby-plugin-styled-components), everything looks fine.

| Initial page load | After reload |
|---|---|
| ![initial-page-load](https://user-images.githubusercontent.com/30958850/69494472-e4df5d80-0eb3-11ea-8dfe-159881ba31c1.png) | ![after-reload](https://user-images.githubusercontent.com/30958850/69494473-e90b7b00-0eb3-11ea-9490-b476df5d1c68.png) |

## Similar Issues

I tried the suggestions in these threads but nothing applied to/helped my case:

- #9121
- #5100
- #9911
- #7376

**Comment by graysonhicks** [comment]
Had a look at this, but didn't have a chance to run locally.  Looks like the main issue is something with the `useScreenQuery` [here](https://github.com/janosh/janosh.io/blob/5d172e58ed3933629cb714b9c2e99ea72a059917/src/components/Nav/index.js#L20).  That logic is controlling whether the Mobile or Desktop Nav renders, which in turn pulls in its respective className.   Not sure why that hook is returning Desktop on initial load, but overall that's a better problem to have than a difficult to debug 'webpack compiling CSS out of order' error.

One possibility is that the `useScreenQuery` is trying to SSR when there is no `window` and that is getting served first.  Would have to dig more in to that.

**Comment by janosh** [comment]
@graysonhicks Thanks for taking a look! After investigating this a bit more, I came to the same conclusion. That led me to discover a project called [`fresnel`](https://github.com/artsy/fresnel) which [explains the issue very well](https://github.com/artsy/fresnel#why-not-conditionally-render). Still trying to figure out a fix atm.

**Comment by LekoArts** [comment]
Thank you for opening this!

I have to agree that this is most probably an issue with the use of your hook and differences in SSR/Client and hence not related to Gatsby itself (thus I'm closing).
I personally never had problems with this package, maybe you can try that: https://github.com/ReactTraining/react-media

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by janosh** [comment]
@LekoArts Thanks for pointing me at `react-media`!

In case anyone stumbles across this issue with similar problems, for now I just went with the quick and dirty fix of deferring the relevant component, i.e. not rendering it at all during SSR.

```js
const [render, setRender] = useState(false)
useEffect(() => setRender(true), [])
return render && <SomeJsx />
```

This approach is actually documented on [reactjs.org](https://reactjs.org/docs/hooks-reference.html#uselayouteffect).

**Comment by marekmika** [comment]
Hi folks,

I am facing the same problem. Even I tried your advice. I hoped that I implemented that in the right way. Problem is that my css style is applied after some time so the user can see the lag which doesn't look very good. 

Here is a [video](https://vimeo.com/user106814212/review/381543018/6ad1c550de) of the page and here is [repo](https://github.com/marekmika/gatsby-landing-page-problem). Please, can you tell me what I am doing wrong? Maybe I can add just some loader spin...

**Comment by janosh** [comment]
@marekmika Is the video private? The link isn't working for me. Could you link to the relevant code in your repo?

**Comment by marekmika** [comment]
Hi @janosh, 

Here is a link for video: https://streamable.com/p1inc  also you the webpage is deployed [here](https://adoring-visvesvaraya-fff191.netlify.com/) 

Basically webpage is composed of [section-one.tsx](https://github.com/marekmika/gatsby-landing-page-problem/blob/master/src/components/sections/section-one.tsx).

**Comment by janosh** [comment]
I don't think you're facing the same issue. Loading your webpage, it looks like a regular delay until necessary JavaScript for painting has been loaded. It's just a wild guess but maybe you could avoid some of that delay by not making `content` a child of `BackgroundImage`.

**Comment by marekmika** [comment]
@janosh  Ok, thanks for your review. However, I will create a separate issue for this.
