### ISSUE TITLE
View App in development on your local network.

### ISSUE THREAD

**Issue by yashguptaz** [gatsbyjs/gatsby#19750]
## Summary
A CLI feature which can help the developer use the app in development build on their local network.

### Brief explanation of the feature.
This feature makes the development preview available on the local network so that it can be accessed from anywhere over a LAN.

After making the development preview available, the CLI shows something like `On Your Network:  http://192.168.xx.xxx:8000/` 

I can enter the address on my mobile device/another PC connected to the same network. 

### Basic example
Create React App already implements it and it works pretty well.

![Gatsby Issue - On Your Network](https://user-images.githubusercontent.com/36479718/69493166-8032fb80-0ed1-11ea-8844-7bb27a84c7bf.png)

### Motivation
Many times, you want to preview the app you're making on a different device so that you have space to code. 

Many times, devs run into a situation where they need to check the app with a mobile device because you cannot use touch on non-touch devices.

Many times testing the app on a phone gives greater insights about the size of the fonts etc. of the app.

___

*It would be nice if I can help to implement this feature with Gatsby, this is my first issue/feature request and I would be glad to work on it.*
If this feature sounds something we can do, let's discuss how and what are the changes we can make to implement this with Gatsby CLI.

**Comment by anuraghazra** [comment]
You can do this via [Gatsby CLI Options](https://www.gatsbyjs.org/docs/gatsby-cli/#options)

```js
"scripts": {
    "dev": "gatsby develop --host=0.0.0.0",
    "build": "gatsby build"
  }
```

**Comment by yashguptaz** [comment]
@anuraghazra 
Why not have it by default in every Gatsby app just like CRA?

**Comment by sidharthachatterjee** [comment]
Thanks for the well written and detailed issue @yashguptaz 

As @anuraghazra mentioned, this already works when host is set to `0.0.0.0`

> Why not have it by default in every Gatsby app just like CRA?

We don't print this on default because it wouldn't work unless host was set to `0.0.0.0` (which binds to all interfaces) and we don't think that's a great default. 

Closing this for now but thank you nonetheless! We appreciate it 🙂
