### ISSUE TITLE
Gatsby build error  ERROR #95313  WebpackError: Invariant failed

### ISSUE THREAD

**Issue by mikeytown19** [gatsbyjs/gatsby#19759]
Here is my repo.
https://github.com/mikeytown19/new-personal
Ok, i am having an issue with building this gatsby site for a new portfolio site i am working on. 
i tried implementing this project from framer-motions codesandbox https://codesandbox.io/s/app-store-ui-using-react-and-framer-motion-ecgc2
It uses react-router (which i am not very familiar with)
here is my error 
```[                            ]   0.001 s 0/4 0% Building static HTML for pages
failed Building static HTML for pages - 1.202s

 ERROR #95313 

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


   7 | 
   8 |   if (isProduction) {
>  9 |     throw new Error(prefix);
     | ^
  10 |   } else {
  11 |     throw new Error(prefix + ": " + (message || ''));
  12 |   }


  WebpackError: Invariant failed
  
  - tiny-invariant.esm.js:9 invariant
    node_modules/tiny-invariant/dist/tiny-invariant.esm.js:9:1
  
  - history.js:250 createBrowserHistory
    node_modules/history/esm/history.js:250:115
  
  - react-router-dom.js:29 new BrowserRouter
    node_modules/react-router-dom/esm/react-router-dom.js:29:41```

I would love it if someone could help me figure this out! 
Thank you in advance

**Comment by graysonhicks** [comment]
Looks like you have installed and are using `react-router-dom` in a few components [here](https://github.com/mikeytown19/new-personal/blob/4387a14e882e52aef74058eac0c2e06487e39661/src/components/projects/CardList.js) and [here](https://github.com/mikeytown19/new-personal/blob/4387a14e882e52aef74058eac0c2e06487e39661/src/components/projects/Card/index.js).  You should uninstall `react-router-dom` and use `reach-router` instead which is what Gatsby uses under the hood for routing.  Check out [this page for creating client only routes](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/), which is what I think you are going for with the animated Cards.  Hope that helps.  Looks slick by the way!

**Comment by mikeytown19** [comment]
@graysonhicks Thank you so much for this! i ended up just scrapping the react-router all together because i think it was just way over complicating things and just decided to make it work off of state. 
Thanks again tho!
