### ISSUE TITLE
Feature request: secure local Gatsby server option (https protocol)

### ISSUE THREAD

**Issue by syndia** [gatsbyjs/gatsby#1975]
Feature request for local https protocol some API's don't accepts local http protocol returning URL's. It would be nice feature to have the option to a secure local Gatsby server.

**Comment by KyleAMathews** [comment]
preact-cli has a nice implementation we could copy.

**Comment by KyleAMathews** [comment]
Would love a PR for this!

**Comment by pwener** [comment]
Can I try, can you sign me?

**Comment by KyleAMathews** [comment]
@pwener it's yours!

**Comment by tsriram** [comment]
@pwener are you working on this? If not, I'll give it a try.

**Comment by tsriram** [comment]
Done in #4522
