### ISSUE TITLE
gatsby-theme-blog 1.2.1 ?

### ISSUE THREAD

**Issue by yokomotod** [gatsbyjs/gatsby#19755]
## Summary

I have confused that gatsby-theme-blog 1.2.1 has been released 3 month ago,
but current version is 1.1.28

## Relevant information

https://www.npmjs.com/package/gatsby-theme-blog/v/1.2.1

**Comment by sidharthachatterjee** [comment]
Great catch! Thank you for pointing this out. Looks like this was done by mistake in https://github.com/gatsbyjs/gatsby/pull/16609/files

I've just published `1.2.2` so that we're back to correct versioning. 

Thank you once again! 💜
