### ISSUE TITLE
[gatsby-transformer-remark] Unable to set options from gray-matter

### ISSUE THREAD

**Issue by redblue9771** [gatsbyjs/gatsby#19762]
## Description

The options from gray-matter in gatsby-transformer-remark not working.

```javascript

//gatsby.config.js

const toml = require("toml")

module.exports = {
  plugins: [
     ....
     {
      resolve: `gatsby-transformer-remark`,
      options: {
        excerpt_separator: `<!-- test -->`,
        engines: {
          toml: toml.parse.bind(toml),
        },
        language: "toml",
        delimiters: "+++",
       },
     },
     ....
  ]
}
```

Throw error

```bash

Expected "\n" but end of input found.

```

### Environment

- gatsby-transformer-remark: 2.6.37
- toml: 3.0.0

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by redblue9771** [comment]
> Hi!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

🤦‍♂️I'm very sorry because I didn't have enough time to find the truth to open this issue and it's unclear.  Within two hours after receiving your reply, I verified that the problem was caused by TOML dependency. 

 [![Edit gatsby-starter-default](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gatsby-starter-default-3fksq?fontsize=14&hidenavigation=1&theme=dark)

👀And found according to [https://github.com/11ty/eleventy/issues/586](https://github.com/11ty/eleventy/issues/586).

😃If the dependency problem is resolved, I will leave a message here and actively close the issue。 

By the way, I really like the Gatsby theme you designed. They are so amazing! ✨

I learned a lot from you about design knowledge and programming techniques. thank you very much! 💜

**Comment by wardpeet** [comment]
Hey @redblue9771,

any chance you know this got resolved?
