### ISSUE TITLE
How to change the path where gatsby-remark-images looks (for netlify cms)?

### ISSUE THREAD

**Issue by Barsonax** [gatsbyjs/gatsby#19764]
## Summary

My blog posts are in `content/posts` and my images are in `static/images`. This way netlify cms can find and render the images however I cannot find a option to make `gatsby-remark-images` look in `static/images`. This only seems to work if I put the images in `content/images` but then netlify cms cannot find the images anymore.

So atm its either the cms that works or the site that works...

How can I make it so gatsby plays nicely with netlify cms while still using the image transformations? Would be nice if one can just set a path where it will look for images.

**Comment by sidharthachatterjee** [comment]
@Barsonax Have you tried changing `config.yml` for netlify cms to look for media in `content/images` instead of `static/images`?

**Comment by Barsonax** [comment]
Yes I did but that doesn't work as content/images only exists in the git repository

**Comment by Barsonax** [comment]
Managed to fix it with relative images.

https://github.com/Barsonax/gatsby-blog/blob/master/gatsby-config.js#L26
