### ISSUE TITLE
How to change default port 8000 to 8080? I tried the -p flag but it did not work.

### ISSUE THREAD

**Issue by jerickBilalat** [gatsbyjs/gatsby#1977]

**Comment by rafaelrpbelo** [comment]
You just need run the command with `-p [port]` or `--port [port]` as args, e.g:

```javascript
gatsby develop -p 4000
```

or 

```javascript
gatsby develop --port 4000
```

**Comment by KyleAMathews** [comment]
Closing out older issues — thanks for everyone that participated on this thread — please open more issues if you need help!
