### ISSUE TITLE
Upgrade from 1.6.6 to 1.9.14 == breaking change?

### ISSUE THREAD

**Issue by Bouncey** [gatsbyjs/gatsby#1978]
In 'develop' the bundle compiles fine, but with I open the page in my browser I get an `invariant` warning:

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `_default`
```

We don't have a `_default` component so I'm guessing it is something gatsby uses? But I can't find a reference to it in the repo.

**Comment by KyleAMathews** [comment]
Haven't ever seen that error so dunno. We definitely don't have a component named `_default`

**Comment by KyleAMathews** [comment]
Searching with the react extension might help find it.

**Comment by cyrilepinat** [comment]
Hi I continue in this thread as the title is related to my problem. 
I'm trying to upgrade from 1.6.3 to 1.9.18 but everything explodes. 
Do you have somewhere a list of breaking changes ? I cannot build or run my app with last versions although It's working just fine with v1.6.3.

for example, I implemented react-intl in my app, it works very well with v1.6.3, but with v1.9.18 my component has suddenly all props undefined so react-intl is crashing. I don't know if this is a bug or a config to do differently but I'm very stuck. 

any help will be very great. thanks guys.
and thank for this great tool, I like using it very much.

**Comment by jquense** [comment]
Gatsby follows semver so there should be no breaking changes between those versions, you are probably seeing a bug, in which case please  (if you can) provide some more info to your problem so we can fox it!

**Comment by JohnShahawy** [comment]
Hi @Bouncey , that error typically comes from not exporting a component in vanilla react.  I'd check to make sure you're exporting everything you should be, especially in your pages folder.

**Comment by Bouncey** [comment]
A quick update, I started another project from scratch with the latest gatsby and found the `_default` is a direct child of `ComponentRenderer` according to the React section of chrome dev tools.

**Comment by KyleAMathews** [comment]
Can you build a site reproducing the problem you're seeing? I haven't seen this error so am not sure what's happening. Thanks!

**Comment by cyrilepinat** [comment]
Hello, for me the problem was that my layouts folder was containing components and not only layout files. Moving components outside this directory fixed the problem.

**Comment by Bouncey** [comment]
@cyrilepinat That was exactly the problem! Thank you :+1: 

So, post `v1.6.6`, no `components`  inside of `layouts`

**Comment by tayiorbeii** [comment]
In case someone else happens upon this error, I was getting it when I forgot to actually `export` the component I was trying to use...
