### ISSUE TITLE
Vulnerable Package Dependency: mem

### ISSUE THREAD

**Issue by akoumany** [gatsbyjs/gatsby#19784]
## Description

Not sure if it is my setup but the version of mem that's shiped with gatsby is vulnerable to [Denial of Service (DoS)](https://npmjs.com/advisories/1084). This was reported Jan 17th, 2018 but published a few days ago. How can update this myself or is there a fix coming down the pipeline?

### Steps to reproduce

```bash
gatsby new gatsby-site
npm install
npm audit
```
### Expected result

found 0 low severity vulnerability in 25230 scanned packages

### Actual result

found 1 low severity vulnerability in 25230 scanned packages

**Low**                        Denial of Service
**Package**                mem
**Patched in**             >=4.0.0
**Dependency of**     gatsby
**Path**                        gatsby > @gatsbyjs/relay-compiler > yargs > os-locale > mem  
**More info**                https://npmjs.com/advisories/1084 

### Environment

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v11.12.0/bin/npm
  Languages:
    Python: 3.7.1 - /Users/komiakoumany/miniconda3/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.3 => 2.18.3 
    gatsby-image: ^2.2.29 => 2.2.29 
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23 
    gatsby-plugin-offline: ^3.0.16 => 3.0.16 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13 
    gatsby-plugin-sass: ^2.1.20 => 2.1.20 
    gatsby-plugin-sharp: ^2.2.31 => 2.2.31 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.1.33 => 2.1.33 
    gatsby-transformer-sharp: ^2.2.23 => 2.2.23 
  npmGlobalPackages:
    gatsby-cli: 2.8.13

**Comment by LekoArts** [comment]
Thank you for opening this!

Putting the warning into context you won't be affected by it as it only applies to certain use cases that are not true for Gatsby's use of that package. We're also in the process of moving away from relay anyways: https://github.com/gatsbyjs/gatsby/pull/19665

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
