### ISSUE TITLE
[gatsby-source-contentful] Plugin should expose 'sys' properties in GraphQL API

### ISSUE THREAD

**Issue by peabnuts123** [gatsbyjs/gatsby#19791]
## Summary

Not all information from the Contentful API is surfaced by the `gatsby-source-contentful` plugin. One important example is the Contentful API's `sys` object, which contains meta data and IDs used by Contentful internally. The plugin itself heavily uses this object, but does not surface it to the GraphQL interface in Gatsby.

![image](https://user-images.githubusercontent.com/2322840/69594418-24977800-1061-11ea-9d4e-5b58aa4e4fe7.png)

The most important part of this information for me is the path `sys.contentType.sys.id` which tells you the ID of the content type this content entry is based on. This may used, for example, to determine which component is used to render this entry within the application. 

I think that at the very least, this path `sys.contentType.sys.id` should be surfaced in the result node data, if not the entirety of the `sys` object, or any property that isn't currently being surfaced. 

Without the content type ID, I'm unable to associate Contentful Content Types with Components in my project other than assuming some kind of fixed layout or type validation in CMS.

### Basic example

I am able to hack-in this functionality by making this simple change in `normalize.js:383`:

![image](https://user-images.githubusercontent.com/2322840/69600777-c4abcc00-1076-11ea-92c6-7bb4f202eec8.png)

however, I would like to hear from those more familiar with the codebase the ramifications of doing so, or any historical reasons why this object has not been exposed before now.

Alternatively, you could map specifically the content type ID field when applicable in a manner such as this: 

![image](https://user-images.githubusercontent.com/2322840/69600898-2f5d0780-1077-11ea-8968-313d2a2af5c8.png)

I would be happy to put together a small PR for one of these suggested changes if people think it's appropriate. 

Thanks.

**Comment by LekoArts** [comment]
Maybe at the time of creation of this plugin this field wasn't exposed via the API yet. In my opinion it doesn't hurt to also expose that information and we'd gladly accept a PR adding it.

**Comment by peabnuts123** [comment]
Have opened a PR with my suggested changes. Most fields within `sys` are not useful or already included, so I have raised a change to include just 2 fields that aren't being included at-present. See: #19811
