### ISSUE TITLE
gatsby-plugin-google-tagmanager Expiry Headers

### ISSUE THREAD

**Issue by joebentaylor1995** [gatsbyjs/gatsby#19798]
Hi, wondering if you can help me at all.

So the plugin works totally fine, beautifully.

However I'm getting a rank down in page score due to the expiry headers.

Could somebody advise me on how to fix these errors?

The error is:
```
There are 4 static components without a far-future expiration date.
https://www.googletagmanager.com/gtm.js?id=GTM-NNQWDS5
https://www.google-analytics.com/analytics.js
```

Can I change this or is this a common problem?

Please see:
[`here`](https://gtmetrix.com/reports/www.mortgagesrm.co.uk/Cut954sZ)

**Comment by LekoArts** [comment]
Thank you for opening this!

I fear this is not the right place to ask this question as we want to focus on bug reports / feature requests about Gatsby here. I'd recommend reaching out to your hosting provider or try using Google, StackOverflow etc.

We're marking this issue as answered and closing it for now. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
