### ISSUE TITLE
campjs.com using Gatsby

### ISSUE THREAD

**Issue by lukebrooker** [gatsbyjs/gatsby#198]
Another site to add to your list (if you want it). I created the latest campjs site using gatsby.

Site: http://vii.campjs.com/
Source: https://github.com/campjs/campjs-vii

Thanks for creating Gatsby and making it easier for me :smile:

**Comment by KyleAMathews** [comment]
This is too cool! Very nicely executed. That was fun playing with your site + poking around your code :)

I'd love to add this to the list. Would you like to create the PR so you can get the Github juice?

**Comment by KyleAMathews** [comment]
Feel free to add your personal site as well ;-) https://github.com/lukebrooker/lukebrooker.github.io

**Comment by lukebrooker** [comment]
Sure, I was going to do that first, but your "Add yours" link pointed to issues.

Yeah I was going to add my site, but I wasn't totally happy with it yet :wink:

**Comment by lukebrooker** [comment]
Oh and thanks for your kind words :smile:

**Comment by KyleAMathews** [comment]
haha, good point. I'll change that real quick to point at the edit this page link :)

**Comment by KyleAMathews** [comment]
thanks for giving Gatsby a spin!
