### ISSUE TITLE
TypeError during runtime - Gatsby Cloud Preview + Ghost CMS

### ISSUE THREAD

**Issue by elibenton** [gatsbyjs/gatsby#19801]
## Description

When using Gatsby Cloud's preview feature, the preview link always throws a `TypeError` at runtime, even though the codebase builds without issue. When the same repo is served on Netlify, there is no issue. 

My hunch is that the error is thrown in the `data-schema` files, which seem to be automatically generated for each of my files in Gatsby's `templates`, post and list. You can see for yourself at [`post/data-schema`](https://personal-website-6362486677.gtsb.io/post/data-schema) and [`list/data-schema`](https://personal-website-6362486677.gtsb.io/). 

### Steps to reproduce

The Gatsby Cloud preview link: https://personal-website-6362486677.gtsb.io
The same code, hosted on Netlify: https://5ddccabc338922000840f442--elibenton.netlify.com/

This issue only began when I started sourcing from Ghost. 

<img width="1021" alt="Screen Shot 2019-11-26 at 5 15 17 PM" src="https://user-images.githubusercontent.com/19228802/69627445-9925e300-1070-11ea-8e21-b3fed251c04d.png">

The variable `countries` referred to in the error is a Ghost Tag. The error is only thrown when I am at the [`index`](https://personal-website-6362486677.gtsb.io/) or when I specifically navigate to the [`post/data-schema`](https://personal-website-6362486677.gtsb.io/post/data-schema) route. All other routes have no issue.

### Expected result

I don't understand why the error is thrown on some pages and not others. I would expect all pages to be the same.

### Actual result

They're not.

### Environment

Here is my (bloated) environment. Leftover packages are from when I was just using the filesystem and MDX.

```
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 70.0.1
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.9.1 => 2.17.2
    gatsby-image: ^2.1.3 => 2.2.29
    gatsby-plugin-feed: ^2.2.3 => 2.3.19
    gatsby-plugin-mailchimp: ^5.1.0 => 5.1.2
    gatsby-plugin-manifest: ^2.1.1 => 2.2.23
    gatsby-plugin-mdx: ^1.0.9 => 1.0.53
    gatsby-plugin-netlify: ^2.0.17 => 2.1.22
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-offline: ^2.1.1 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.13
    gatsby-plugin-remove-trailing-slashes: ^2.1.2 => 2.1.12
    gatsby-plugin-sharp: ^2.1.4 => 2.2.32
    gatsby-plugin-sitemap: ^2.2.3 => 2.2.19
    gatsby-plugin-styled-components: ^3.0.7 => 3.1.11
    gatsby-plugin-use-dark-mode: ^1.1.2 => 1.1.2
    gatsby-remark-audio: ^1.0.2 => 1.0.2
    gatsby-remark-autolink-headers: ^2.0.18 => 2.1.16
    gatsby-remark-copy-linked-files: ^2.0.13 => 2.1.28
    gatsby-remark-images: ^3.0.14 => 3.1.28
    gatsby-remark-prismjs: ^3.2.11 => 3.3.20
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-remark-responsive-iframe: ^2.2.18 => 2.2.25
    gatsby-remark-smartypants: ^2.0.9 => 2.1.14
    gatsby-source-filesystem: ^2.0.39 => 2.1.33
    gatsby-source-ghost: ^4.0.0 => 4.0.0
    gatsby-transformer-remark: ^2.3.12 => 2.6.30
    gatsby-transformer-sharp: ^2.1.21 => 2.3.0
```
---

I love the instantaneous nature of Gatsby Cloud preview. Would love to migrate over entirely once the build feature is out of beta, but I need to identify and solve this issue first! All help would be appreciated! This is my first website ever!

**Comment by LekoArts** [comment]
Hi!

Please contact support@gatsbyjs.com for inquiries regarding Gatsby Cloud. Thanks!
