### ISSUE TITLE
html pages in static folder now return 404 errors in "gatsby develop"

### ISSUE THREAD

**Issue by ReactAcademyCa** [gatsbyjs/gatsby#19807]
## Description

Html pages stored in the "static" folder now return 404 errors using "gatsby develop".  That was not the case with the previous version of the Gatsby CLI.  (I am using gatsby-cli@2.8.14 )

The html pages still show up correctly when using "gatsby build" followed by "gatsby serve".

Other extensions (.pdf, .css, .js, etc.) still show up correctly.  Only ".html" and ".htm" extensions are affected.

### Steps to reproduce

1. Create a starter Gatsby project
2. Add a static folder in the project folder
3. Add a file called "test.html". Put some static html in it.
4. In your command line, run "gatsby develop".
5. In your file explorer, notice that the folder public now has a copy of "test.html" file in it. (as expected.)
6. In your browser, type "http://localhost:8000/test.html".  You get a 404 error.
7. In your comand line, hit ctrl-c, run "gatsby build" followed by "gatsby serve".
8. In your browser, type "http://localhost:9000/test.html". You get the expected page.

### Expected result

In step 6, you should get the test.html page.

### Actual result

In step 6, you got a 404 error instead.

### Environment

System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Users\EricCote\AppData\Roaming\npm\yarn.CMD       
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: 2.17.17 => 2.17.17
    gatsby-image: ^2.2.27 => 2.2.34
    gatsby-plugin-gtag: ^1.0.11 => 1.0.11
    gatsby-plugin-hubspot: ^1.3.3 => 1.3.3
    gatsby-plugin-manifest: ^2.2.17 => 2.2.30
    gatsby-plugin-offline: ^3.0.14 => 3.0.24
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.16
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sass: ^2.1.14 => 2.1.24
    gatsby-plugin-sharp: ^2.2.24 => 2.3.4
    gatsby-source-filesystem: ^2.1.24 => 2.1.39
    gatsby-transformer-json: ^2.2.9 => 2.2.20
    gatsby-transformer-remark: ^2.6.35 => 2.6.38
    gatsby-transformer-sharp: ^2.2.15 => 2.3.6

**Comment by beliayeu** [comment]
the same problem is on my side
I believe the discussion for the long term solution is in https://github.com/gatsbyjs/gatsby/issues/13072
workaround is https://github.com/gatsbyjs/gatsby/issues/17761#issuecomment-533816520
