### ISSUE TITLE
CORS issues in development when using api calls

### ISSUE THREAD

**Issue by ergunpp** [gatsbyjs/gatsby#19806]
Hi, 
I am using AWS Cloud9 as development environment for several projects I am working on. When testing external apis I get the below error:

```
Access to XMLHttpRequest at 'https://loripsum.net/api' from origin 'https://2311c2aae23a4d48ad3c673bdfa4da7c.vfs.cloud9.us-east-1.amazonaws.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Here is the sample code I am trying to run:

```
import React from "react"
import axios from "axios"

const URL="https://loripsum.net/api"
//"http://31.145.34.42:4900/api/stock/code/"
const HEADERS={
            "Access-Control-Allow-Origin" : "*",
            "Content-Type": "application/json"
}
class StockForm extends React.Component {
    
    constructor(props) {
        super(props)
        this.state={
            stockCode : "",
            response : ""
        }
        
        this.handleChange = this.handleChange.bind(this)
        this.handleSubmit = this.handleSubmit.bind(this)
    }
    
    handleChange = event => {
        const { target } = event
        const { value } = target
        const { name } = target
    
        this.setState({ [name]: value })
        
  }
  
    handleSubmit = event => {
        event.preventDefault()
        const { stockCode, response } = this.state
        axios.get(URL, {
            headers: HEADERS,
            
        })
        .then((response)=>{
            console.log(response)
            this.setState({ response : response.data})
        })
        .catch(function (error) {
            console.log(error);
          })
    }

    
    render() {
        const {
            stockCode,
            response
        } = this.state
        return (
            <div>
              <form id="stock" onSubmit={this.handleSubmit}>
              <label>Stok Kodu</label>
              <input name="stockCode" type="text" value={stockCode} onChange={this.handleChange}/>
              <p>{response}</p>
              <button onClick={this.handleSubmit}>Gönder</button>
              </form>
            </div>
            )
    }
} 

export default StockForm

```

Is there an easy solution to this problem?
Thanks,

**Comment by universse** [comment]
Maybe this guide will help https://www.gatsbyjs.org/docs/api-proxy/

**Comment by ergunpp** [comment]
I added the proxy as in the document:
````
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  proxy: {
    prefix: "/api",
    url: "https://loripsum.net",
  },}
```
But now the url fetch runs locally and does not reach the targeted external url.

**Comment by universse** [comment]
Is there any sort of error message?

**Comment by ergunpp** [comment]
No but the api returns the html of my site as data

**Comment by sidharthachatterjee** [comment]
> But now the url fetch runs locally and does not reach the targeted external url.

With an API proxy of the kind that gatsby can include (which @universse linked to documentation about), what you get is that a local server intercepts requests and makes them for you (to origins that don't support CORS since CORS is a browser only thing and doesn't affect API calls on the server)

Maybe rather than a proxy, you need to look into if https://loripsum.net/api supports setting allowed origins in CORS? A preliminary look suggests that it doesn't. Maybe check out another API? Or fetch data from this in `gatsby-node.js`

Nonetheless, we'll be closing this since it doesn't exactly pertain to Gatsby but always happy to answer any other questions that you might have! 

Happy coding 💜

**Comment by db10101** [comment]
I'm currently having an issue where CORS-enabled servers (tested with test-cors.org) are returning the error

"Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by Douglasacost** [comment]
i have the same issue now... any help?

**Comment by db10101** [comment]
> i have the same issue now... any help?

@Douglasacost what fixes it for me was abandoning Axios and using the Fetch API. For some reason, Axios always returned the same CORS errors while fetch worked just fine.

**Comment by Douglasacost** [comment]
@db10101 thanks friend. I solved my issue a few hours ago using Axios instead Fetch, the cors was given when im using Fetch, the opposite happened to you. 
The reason for that i don't know

**Comment by shaikho** [comment]
@Douglasacost how did you end up solving the axios cros issue, I'm having the same issue over here.

**Comment by Douglasacost** [comment]
@shaikho I had to use fetch instead of axios. Never knew the reason of those CORS errors, but probably some misconfiguration on the gatsby project
