### ISSUE TITLE
Contributing to Gatsby : Yarn errors on Windows

### ISSUE THREAD

**Issue by sebastienfi** [gatsbyjs/gatsby#1981]
Hi guys,

Updated the repo to latest and running `npm i` gave me the error "Yarn : command not found". 
I'm on Windows. Has Yarn become a prerequisite ?

Then if I install Yarn globally, I get a bunch of errors...

I reproduced the error with a fresh clone of the repo.

![image](https://user-images.githubusercontent.com/5808108/29933004-499b0cb2-8e76-11e7-8ed1-ace53be7dcc9.png)

**Comment by KyleAMathews** [comment]
Yarn is required now. We might need to upgrade the docs for that. From your screenshot, it looks like coffeescript requires a more recent version of node than what you have installed.

**Comment by sebastienfi** [comment]
Then this is a real problem because the latest version of Nodejs on Windows is 6.11.2 and it seems that Yarn is requesting for >= 7.6.0

**Comment by sebastienfi** [comment]
Fixed!
Updated to latests NPM and NODEJS.

**Comment by jquense** [comment]
Updated contribution docs in my most recent build PR fyi
