### ISSUE TITLE
bug: codesandbox errror on docs/graphql-reference

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#19823]
## Description

- in section 
https://www.gatsbyjs.org/docs/graphql-reference/#complete-list-of-possible-operators the codesandbox is not loading.
- all other sandboxes below also stop loading

### Steps to reproduce

go to https://www.gatsbyjs.org/docs/graphql-reference/#complete-list-of-possible-operators
link in `<iframe title="Complete list of possible operators"` get a 400 http error

### Expected result

display without error

### Actual result

error:

![Bildschirmfoto 2019-11-27 um 07 53 58](https://user-images.githubusercontent.com/184316/69700604-1ee67480-10eb-11ea-8ded-247d68fba595.png)

**Comment by LekoArts** [comment]
Thanks for the issue. It's not something we directly have power over but I reached out to codesandbox to fix it.
