### ISSUE TITLE
How to filter files by name?

### ISSUE THREAD

**Issue by mrtnbroder** [gatsbyjs/gatsby#19834]
## Summary

I have a very basic gatsby starter project with the following config:

```
module.exports = {
  ...
  plugins: [
    `gatsby-transformer-json`,
    `gatsby-transformer-remark`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `content`,
        path: `${__dirname}/src/content`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    ...
  ],
}
```

And a json file that contains the data I want to show:

`src/content/mydata.json`
```json
{
  "title": "Title",
  "description": "Text",
  "image": "image.jpg",
  "gallery": [{ "image": "wallpaper.jpg" }]
}
```

And I have two images inside `src/images`: `image.jpg` and `wallpaper.jpg`

---

As you can see, I am describing which images I want to show on the page inside `mydata.json` within the `image` and `gallery` attributes.

Since `gatsby-source-filesystem` with `gatsby-transformer-sharp` and `gatsby-plugin-sharp` will/can create optimized images, I know make use of them and query these optimized images with the data provided. However, this is where I am stuck can't cant really find something in this crazy big documentation land that gatsby has.

Pseudo Query:

```
query MyQuery {
  // how can I set eq: to the relative path when I can't use variables with useStaticQuery?
  image: file(relativePath: { eq: ??? }) {
    childImageSharp {
      fixed(width: 320) {
        src
      }
    }
  }
  // how can I describe the filter to only get the files that are described inside `gallery` from `mydata.json`?
  gallery: allFile(filter: ???) {
    edges {
      node {
        childImageSharp {
          fixed(width: 320) {
            src
          }
        }
      }
    }
  }
}

```

I hope I made everything as clear as possible and someone can provide some help!

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

I created a codesandbox from your example here: https://codesandbox.io/s/json-images-link-tlegq

Your goal should be to query `allMydataJson` and to automatically have the images in there as images processed by sharp. Messing with `file` and filtering is cumbersome.

Your current problem is that you don't link those images relatively (so e.g. `"image": "../images/image.jpg"`) and thus Gatsby can't find it automatically.

By using the schema customization API you can find all nodes of `File` (same as a `allFile` query) and filter out the desired image:

```js
// in gatsby-node.js
exports.createSchemaCustomization = ({ actions, schema }) => {
  const { createTypes } = actions
  const typeDefs = [
    schema.buildObjectType({
      name: "MydataJson",
      interfaces: ["Node"],
      fields: {
        image: {
          type: "File",
          resolve: (source, args, context, info) => {
            return context.nodeModel
              .getAllNodes({ type: "File" })
              .find(
                file =>
                  file.base === source.image &&
                  file.sourceInstanceName === "images"
              )
          },
        },
        gallery: {
          type: ["Gallery"],
        },
      },
    }),
    schema.buildObjectType({
      name: "Gallery",
      fields: {
        image: {
          type: "File",
          resolve: (source, args, context, info) => {
            return context.nodeModel
              .getAllNodes({ type: "File" })
              .find(
                file =>
                  file.base === source.image &&
                  file.sourceInstanceName === "images"
              )
          },
        },
      },
    }),
  ]

  createTypes(typeDefs)
}
```

`file.base` is the name of the image, by additionally filtering by `sourceInstanceName` only images inside the images folder are looked at.

You then can query it like:

```graphql
allMydataJson {
  nodes {
    image {
      childImageSharp {
        fluid {
          src
        }
      }
    }
    gallery {
      image {
        childImageSharp {
          fluid {
            src
          }
        }
      }
    }
  }
}
```

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by mrtnbroder** [comment]
Thanks a bunch @LekoArts !

`Your current problem is that you don't link those images relatively`

That actually helped me solve my problem! <3
