### ISSUE TITLE
Best way to prepend an element to body?

### ISSUE THREAD

**Issue by alfred-pb** [gatsbyjs/gatsby#19835]
Hi, I have a question. I need to prepend an element to body on every page. 

I need to do something this: 

```
const coverImg = document.createElement('div');
document.body.prepend(coverImg);
coverImg.className = 'coverImg';
```

Should I put it as a portal, in gatsby-browser.js, every page or where?

**Comment by LekoArts** [comment]
Thank you for opening this!

You can use the [`onRenderBody`](https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody) API and use `setPostBodyComponents` to add elements:

These three plugins use it in their gatsby-ssr.js file:

- https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-gtag/src/gatsby-ssr.js
- https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js
- https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-facebook-analytics/src/gatsby-ssr.js

So you'd write:

```js
// in gatsby-ssr.js

import React from "react"

export const onRenderBody = ({ setPostBodyComponents }) => {

  setPostBodyComponents([
    <div key="unique-cover-image" className="coverImg" />
  ])
}
```

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
