### ISSUE TITLE
How do I replace text during build?

### ISSUE THREAD

**Issue by clementhk** [gatsbyjs/gatsby#19833]
I need to build my project for multiple websites, need to replace all "ABC Inc" to "XYZ Inc" and "https://external.link.abc" to "https://external.link.xyz", etc.
Is there an easy way to do it in the config or something?

**Comment by LekoArts** [comment]
Thank you for opening this!

There are multiple ways of achieving your goal and you can use the method you prefer.

You could place the information in your `siteMetadata` and query it with GraphQL:
https://www.gatsbyjs.org/docs/gatsby-config/#sitemetadata

You could place it in environment variables:
https://www.gatsbyjs.org/docs/environment-variables/

I'd prefer the `siteMetadata` version. An example query is shown here: https://www.gatsbyjs.org/tutorial/part-four/#use-a-page-query

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by clementhk** [comment]
Hi @LekoArts,

Thanks, but is there a global search and replace?

**Comment by LekoArts** [comment]
Gatsby doesn't handle that for you. If you want to do a search and replace you can use e.g. your editor to do that. I'd advise using `siteMetadata` and queries in your components.
