### ISSUE TITLE
bug(starters): starter pages are not created for some starter repos

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#19849]
## Description

for some starters in the `starters.yml` there are no starters pages created and creating a 404. with the gatsbyjs starter there is a page with blurred preview but with fore reload there is an error page.

at first i guessed it was because of capital letters in username, but there are others with capital letters in name:
- https://www.gatsbyjs.org/starters/ButterCMS/gatsby-starter-buttercms/ OK
- https://www.gatsbyjs.org/starters/Kentico/gatsby-starter-kontent/ OK
- https://www.gatsbyjs.org/starters/GraphCMS/gatsby-graphcms-tailwindcss-example/ OK
...

### TryGhost/gatsby-starter-ghost

https://github.com/TryGhost/gatsby-starter-ghost

https://github.com/gatsbyjs/gatsby/blob/e0c16184e434bef7a8c4b3b3d9f636b487529bc4/docs/starters.yml#L1645-L1664

1 link from: 
- https://www.gatsbyjs.org/docs/headless-cms/

### AlexanderProd/gatsby-shopify-starter

https://github.com/gatsbyjs/gatsby/blob/e0c16184e434bef7a8c4b3b3d9f636b487529bc4/docs/starters.yml#L1904-L1918

2 links from: 
- https://www.gatsbyjs.org/docs/building-an-ecommerce-site-with-shopify/

### gatsbyjs/gatsby-starter-blog/

https://www.gatsbyjs.org/starters?s=%22gatsby-starter-blog%22

https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-blog/ --> visible somehow from cache but if i force reload then it gets an 404

https://github.com/gatsbyjs/gatsby/blob/e0c16184e434bef7a8c4b3b3d9f636b487529bc4/docs/starters.yml#L25-L39

links from:
- https://www.gatsbyjs.org/docs/gatsby-cli/
- https://www.gatsbyjs.org/docs/gatsby-repl/
- https://www.gatsbyjs.org/tutorial/part-eight/
- https://www.gatsbyjs.org/tutorial/blog-netlify-cms-tutorial/

**Comment by LekoArts** [comment]
This is the cause of the issue :/
https://github.com/gatsbyjs/gatsby/issues/19452

**Comment by muescha** [comment]
updated: links to the starter pages and the search.

result of this lines:

https://github.com/gatsbyjs/gatsby/blob/8a2aeb3f3aa41ddd8e841753ed3c16b26b0546dd/www/gatsby-node.js#L616-L628

**Comment by muescha** [comment]
PR for shopify starter url #19871

**Comment by muescha** [comment]
more starters:

- gatsby-contentful-starter
https://www.gatsbyjs.org/starters/contentful-userland/gatsby-contentful-starter
https://github.com/contentful-userland/gatsby-contentful-starter

- gatsby-portfolio
https://www.gatsbyjs.org/starters/datocms/gatsby-portfolio
https://www.github.com/datocms/gatsby-portfolio

**Comment by muescha** [comment]
FYI: following starters are back again

- AlexanderProd/gatsby-shopify-starter -> fixed
- gatsbyjs/gatsby-starter-blog/ -> fixed
