### ISSUE TITLE
Gatsby Build Error

### ISSUE THREAD

**Issue by 8ctopotamus** [gatsbyjs/gatsby#1985]
```gatsby develop``` works fine. When I use ```gatsby build```, I get this error:

**Cannot read property 'body' of undefined**
render-page.js: 45431

I looked at render-page.js and it seems that ```doc.body``` is the problem, but "doc" is just referring to "document", so not sure why that's undefined...

I am using windows, if that matters.

**Comment by jquense** [comment]
Have you read the link in the error for debugging HTML builds? In order to generate static sites gastby renders out your app on the server, where there is no `document` or `window` or other browser globals. You need to do browser specific things in `componentDidMount` or guard against the globals not being present.

https://www.gatsbyjs.org/docs/debugging-html-builds/

**Comment by 8ctopotamus** [comment]
Yes, I did read that. I have no code in my src folder that uses ```document``` or ```window```.

**Comment by jquense** [comment]
huh?

> I looked at render-page.js and it seems that doc.body is the problem, but "doc" is just referring to "document", so not sure why that's undefined...

Somewhere someone is referring to the document, either your code or one of the packages your using.

**Comment by 8ctopotamus** [comment]
render-page.js was generated by ```gatsby build```

**Comment by jquense** [comment]
`render-page.js` is all of your site's code, its the output bundle from compiling and compiling your pages together. That line in `render-page.js` maps back to one of your files or library your using.

You might want to also upgrade gatsby it will give you a better error, using source-maps to point to the original file

**Comment by 8ctopotamus** [comment]
Ah ok understood, thanks! 

I had used the sketch-js npm package. Do I need to go through this and fix references to document in that package for this to work?

**Comment by jquense** [comment]
yeah :/ or maybe conditionally require it only when in a browser

```
let sketch:
if (typeof document !== 'undefined')
  sketch = require('sketch-js')
```

or something similar

**Comment by 8ctopotamus** [comment]
```
let sketch
if (typeof document !== 'undefined')
  sketch = require('sketch-js')
```
