### ISSUE TITLE
Is it possible to disable 'Install gatsby-starter' on Chrome browser

### ISSUE THREAD

**Issue by aaayumi** [gatsbyjs/gatsby#19857]
## Summary
We released a static website using gatsby today. We just noticed that user will see 'Install gatsby-starter' on Chrome browser setting.  

Why is it appearing on?  Can we disable it?

## Relevant information
 "gatsby": "^2.13.39",

### Environment (if relevant)
Chrome browser 
![Screen Shot 2019-11-28 at 12 41 51](https://user-images.githubusercontent.com/18599973/69803673-0ce4fe80-11dd-11ea-9065-0d39ce343e46.png)

**Comment by LekoArts** [comment]
Thank you for opening this!

This is Chrome supporting PWAs in the browser itself. If you open your site with an Android Phone you'll also see a prompt to install it. You can remove this functionality by removing the manifest (+ optionally offline) plugin:
https://github.com/gatsbyjs/gatsby/blob/7b814f8d2c3b3d7ee0cd8e21d7641c199c96d014/starters/default/gatsby-config.js#L18-L32

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
