### ISSUE TITLE
gatsby-transformer-javascript-static-exports not working

### ISSUE THREAD

**Issue by PolGuixe** [gatsbyjs/gatsby#1986]
I have install it following the docs: https://www.gatsbyjs.org/packages/gatsby-transformer-javascript-static-exports/

Querying it in GraphiQL doesn't work. 

I have stopped the Gatsby run-time and started it again. 

Do I have to do anything more?

**Comment by jquense** [comment]
Can you provide more info? where are you doing hte export, what does it look like?

**Comment by PolGuixe** [comment]
@jquense this is the project https://github.com/Zetoff/Portfolio/tree/feature/add-sections

Here is the data: https://github.com/Zetoff/portfolio/tree/feature/add-sections/src/data

I have also tried different `gatsby-config.js` set ups for this plugin. From the plain and simple one to this one.

**Comment by KyleAMathews** [comment]
@PolGuixe have you tried the example site for the plugin in the examples directory?

**Comment by PolGuixe** [comment]
Does the `gatsby-transformer-javascript-static-exports` have to be used along with other packages or have extra dependencies?

**Comment by PolGuixe** [comment]
It worked it was missing the `gatsby-source-filesystem`.  Probably it should be added.

**Comment by PolGuixe** [comment]
Are the data fields limited to

```
export const data = {
    title: 'Choropleth on d3v4',
    written: '2017-05-04',
    layoutType: 'post',
    path: 'choropleth-on-d3v4',
    category: 'data science',
    description: 'Things about the choropleth.'
}
```

**Comment by jbolda** [comment]
The plugin is a "transformer" type. That is the Gatsby convention that this plugin requires data from gatsby-source-*. If that is unclear in the tutorials or docs, I think it makes sense to clarify it there. A doc PR is always helpful there. A relevant reason to not add it here is that someone could add gatsby-source-github, and this plugin should still work.

Regarding the data, it just passes the whole data object statically, so technically anything that isn't a variable reference to my knowledge. The overriding use case is strings, dates and numbers. Feel free to PR clarifications if it will help others, or if you find other uses.

**Comment by jbolda** [comment]
Seems like all questions have been answered. Closing.
