### ISSUE TITLE
Related fields not showing in gatsby-source-drupal

### ISSUE THREAD

**Issue by webdobe** [gatsbyjs/gatsby#19868]
## Description

Drupal fields are not showing as relationships in graphql using gatsby-source-drupal.

### Steps to reproduce

- Setup drupal with jsonapi
- Create a field_image on a content type.
- Add content and attache image
- Use gatsby-source-drupal and the graphiql query browser.

### Expected result

What should happen?  I should see the "field_image" either at:
```
nodeBlog {
  field_image OR
  relationships {
    field_image
  }
}
```
I do see it when I query the jsonapi endpoint directly.  So drupal is providing it.  gatsby-source-drupal isn't doing anything with it.

### Actual result

Image field is not there.  file__file is.. But that doesn't narrow it down to the field.  It get's all related files.

### Environment
```
System:
    OS: Linux 4.15 Linux Mint 19.2 (Tina)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    npm: 3.5.2 - /usr/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
  npmGlobalPackages:
    gatsby-cli: 2.8.12
```

**Comment by vladar** [comment]
It is not clear which version of gatsby you are using. Can you try it with `gatsby 2.18.5`?

**Comment by webdobe** [comment]
The gatsby-cli is at 2.8.12 you want me to downgrade to 2.18.5?

**Comment by webdobe** [comment]
We were running ^2.17.11.  We just started this project within the last month.  We set to ^2.18.5 and updated.  But still, the related image fields are not showing.

**Comment by vladar** [comment]
Can you make a [minimum reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) with some public drupal setup? That would help a lot.

**Comment by rodperottoni** [comment]
Just ran into the same issue. Created a new project with the Gatsby Default Starter, added `gatsby-source-drupal` and can't see any image fields from the content types available in the Umami Food Maganize demo.

Environment:
- Gatsby 2.18.12 
- gatsby-source-drupal 3.3.12
- latest Drupal 8 docker image (v8.8)
- latest Maria DB docker image
