### ISSUE TITLE
[gatsby-plugin-sharp] Add extract (crop)

### ISSUE THREAD

**Issue by Oppzippy** [gatsbyjs/gatsby#19873]
## Summary

sharp has an [extract operation](https://sharp.pixelplumbing.com/en/v0.17.1/api-operation/#extract) but there's no way to access it through gatsby-plugin-sharp. This would be a nice feature to have.

### Basic example

Maybe something like
```graphql
resize {
  extract (top: 250, left: 250, width:  500, height: 500)
}
```

### Motivation

I'm pulling images from an external source and only want a small section of the image. I'd rather not have to serve the entire image.

**Comment by jackweinbender** [comment]
Looks like nothing ever came of this-- @oppzippy, did you come up with a way to do this?
