### ISSUE TITLE
How to render a component styled with Emotion in an iframe?

### ISSUE THREAD

**Issue by moroshko** [gatsbyjs/gatsby#19872]
I work on a component library and a demo site.

Components are styled using Emotion and the demo site is built with Gatsby.

For preview purposes, I'd like to render components in an iframe. This will ensure that styles from the website are not cascading to the components, make it easier to deal with responsive layouts, etc.

[Here](https://codesandbox.io/s/gatsby-starter-default-jw5u5), you can see an example of how `line-height` from the website is cascading to the `Button` component causing it to be very tall.

<img width="424" alt="Screen Shot 2019-11-29 at 3 22 40 pm" src="https://user-images.githubusercontent.com/259753/69843755-02019b00-12bd-11ea-8db1-8d40b186fcec.png">

How could I render the `Button` with all its styles inside the iframe?

**Comment by LekoArts** [comment]
Thank you for opening this!

Depending on how you create the site (with Markdown, MDX, other things) you should look into how it's done in React in general as it's not specific to Gatsby:

https://medium.com/@ryanseddon/rendering-to-iframes-in-react-d1cb92274f86
https://github.com/ryanseddon/react-frame-component

You could also use something like https://github.com/FormidableLabs/react-live or https://www.gatsbyjs.org/packages/gatsby-remark-embed-snippet/?=embed

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by moroshko** [comment]
@LekoArts Thanks for your response.

I feel like it is a Gatsby specific issue, not a general React one.

Here is the more specific issue that I'm hitting: https://github.com/gatsbyjs/gatsby/issues/19928
