### ISSUE TITLE
Offline plugin not catching icons from manifest plugin

### ISSUE THREAD

**Issue by matanui159** [gatsbyjs/gatsby#19870]
## Description

When using both offline plugin and manifest plugin, icons generated will not be cached.

### Steps to reproduce

[Demo project here](https://gitlab.com/matanui159/gatsby-offline-bug)

Run `gatsby build` and `gatsby serve`, refresh page a couple of times, turn offline, refresh again.

### Expected result

It caches the icon and shows it offline.

### Actual result

Icon is not cached and doesn't show when offline. Checking the workbox logs shows that it doesn't take any caching action for the icons and fails when it tries to fetch it while offline.

### Environment

I'm away from my computer right now since I had to leave and I'm submitting this on my phone.

I'm on Linux x64 Arch, using Chrome stable, latest version of all packages (at least since yesterday afternoon).

**Comment by universse** [comment]
Have you tried placing the manifest plugin above the offline plugin in gatsby-config?

**Comment by matanui159** [comment]
It already is. You can check yourself in the project provided. It caches the manifest itself, just not the icons

**Comment by matanui159** [comment]
I was able to fix it with these settings:
```js
{
   resolve: 'gatsby-plugin-manifest',
   options: {
      icon: 'icon.svg',
      cache_busting_mode: 'none'
   }
},
{
   resolve: 'gatsby-plugin-offline',
   options: {
      workboxConfig: {
         globPatterns: ['**/*']
      }
   }
}
```

The `cache_busting_mode` is there since the query parameter cache busting would break workbox since it could never find the cached URLS.
And the `globPatterns` is there so offline will cache everything.

Even though this technically fixes I still feel something like this should work out of the box or at the very least have documentation somewhere explaining how to get it working.

**Comment by LekoArts** [comment]
We'd be happy to receive a PR updating the README to include this :)

**Comment by wardpeet** [comment]
Let me re-open this, it seems easy and a good addition to your docs.

**Comment by StefanNieuwenhuis** [comment]
Which README file must be edited? I'll add it :)

**Comment by wardpeet** [comment]
add it to gatsby-plugin-offline and gatsby-plugin-manifest is what I would say.

**Comment by matanui159** [comment]
I moved onto other projects and haven't touched Gatsby for a while but is there a reason why this doesn't work out of the box or why it can't be fixed?

Seems kind of silly (imo) that this does not work without workarounds, especially since they're both [official plugins](https://github.com/gatsbyjs/gatsby/tree/master/packages) recommended by the [docs for creating a PWA](https://www.gatsbyjs.org/docs/progressive-web-app/) which would be the first result if someone was looking for it, only for it to not cache the favicons which is definitely unexpected.

At the very least since they're both official plugins can't they detect each other and modify their default config accordingly?

**Comment by ahmad-reza619** [comment]
Hey @matanui159 , i already opened pull request documenting your issue, check it out in #22462
