### ISSUE TITLE
Index page load does not apply global CSS styles

### ISSUE THREAD

**Issue by fergusfrl** [gatsbyjs/gatsby#19880]
### Summary
I have a single CSS file which I'm importing into gatsby-browser.js.
When running `gatsby develop`, I can see the styles displayed correctly and as expected. When I `gatsby build` and `gatsby serve`, the styles are not applied to `/` route.
Other routes once reloaded do apply the correct styles, but never the index page.

I am experiencing this problem on the latest versions of: chrome, firefox, safari and edge.

This problem seems very similar to https://github.com/gatsbyjs/gatsby/issues/10324 but in that case there were multiple stylesheets loading which is not something that is happening for me.

Has anyone encountered this problem before? And if so how was if overcome?

## Relevant information
Live example: https://www.fergusfrl.xyz/

I am using CSS variables
I am importing a google font using the `gatsby-plugin-google-fonts` plugin

### Environment (if relevant)

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
    npm: 6.11.1 - ~/.nvm/versions/node/v10.9.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11 
    gatsby-cli: ^2.8.14 => 2.8.14 
    gatsby-image: ^2.2.31 => 2.2.31 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.2.27 => 2.2.27 
    gatsby-plugin-offline: ^3.0.19 => 3.0.19 
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14 
    gatsby-plugin-sharp: ^2.2.37 => 2.2.37 
    gatsby-source-filesystem: ^2.1.36 => 2.1.36 
    gatsby-source-strapi: 0.0.10 => 0.0.10 
    gatsby-transformer-sharp: ^2.3.3 => 2.3.3 

### File contents (if changed)

`gatsby-browser.js`: 
```
import React from "react"
import Layout from "./src/components/layout"

// this is my only CSS file with all my styles in it
import "./src/styles/global.css"

export const wrapPageElement = ({ element, props }) => {
  return <Layout {...props}>{element}</Layout>
}

```

**Comment by universse** [comment]
Can you try doing the same thing for gatsby-ssr.js?

**Comment by fergusfrl** [comment]
That's worked!
I added the same code from `gatsby-browser.js` to `gatsby-ssr.js` and now styles are applied on initial page load. Thanks for that 😄

I ran into some problems because I am working with the `window` object in my `Layout` component which is `undefined` during SSR.
A simple `typeof window !== "undefined" && ...` will fix that for anyone struggling with the same problem 👍
