### ISSUE TITLE
<error> new.js:12 () Error: Killed

### ISSUE THREAD

**Issue by hjcd** [gatsbyjs/gatsby#1988]
Hi there.

Just getting started with Gatsby and haven't had any luck creating a new site or pulling one of the tutorials from Github.

gatsby -V
1.1.6
npm -v
3.10.8
node -v
v6.9.1

OS
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"

Following similar errors, I've tried globally uninstalling gatsby-cli and reinstalling it via npm. Tried new/other directories and still not luck. 

Is there a log I can find out more information regarding this error or can someone shed light on this?

Error is

2017-09-01T06:51:52+0000<log> init-starter.js:107 (clone) Cloning git repo git://github.com/gatsbyjs/gatsby-starter-default.git to test...
2017-09-01T06:51:57+0000 <log> init-starter.js:114 () Created starter directory layout
2017-09-01T06:51:57+0000 <log> init-starter.js:44 (install) Installing packages...
2017-09-01T06:58:00+0000 <error> new.js:12 () Error: Killed
at /usr/lib/node_modules/gatsby-cli/init-starter.js:52:16
at ChildProcess.exithandler (child_process.js:213:5)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:877:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by briansaycocie** [comment]
I'm getting the same issue but on Windows 7. It's possible it is related to the git repo protocol `git://github.com/gatsbyjs/gatsby-starter-default.git`, and should possibly be changed to `https://github.com/gatsbyjs/gatsby-starter-default.git`. Just a guess though.

**Comment by hjcd** [comment]
Hi Brian.

Thanks for the suggestion. In my instance I was trying to do the first tutorial:

gatsby new tutorial-part-one https://github.com/gatsbyjs/gatsby-starter-hello-world

which uses the https protocol. Out of curiosity I also tried changing it to git:// as well as starting a new project from scratch, ie: gatsby new mysite and in each case the same error occurs.

**Comment by hjcd** [comment]
Not sure what etiquette is here but has does anyone have suggestions for this?

**Comment by KyleAMathews** [comment]
Hey — hopefully you've got this fixed. One thing to try is upgrading to the latest version of gatsby-cli `npm install -g gatsby-cli@latest`. Closing out older issues but feel free to create a new issue if you need help!

**Comment by hjcd** [comment]
Thanks Kyle. After about a month a new version of gatsby was released and the update fixed it.
