### ISSUE TITLE
A `.git`-folder is left when doing a `gatsby new [site-name]`

### ISSUE THREAD

**Issue by jmrnilsson** [gatsbyjs/gatsby#19895]
## Description

I am seeing leftovers for from a git-repository. The folder .git exists which I think makes for an uncertain git state.

### Steps to reproduce

    gatsby new MinMQ.org
    cd MinqMq.org

### Expected result

If you check git it should not know about a previously existing clone. 

    cd MinMQ.org
    git status
    fatal: not a git repository (or any of the parent directories): .git

Similarly not .git-folder should exists since I didn't create one myself:

    ls .git
    ls: cannot access '.git': No such file or directory

### Actual result

Then,

    git status
    On branch master
    nothing to commit, working tree clean

And trying figure out where it goes

    git remote show origin
    fatal: 'origin' does not appear to be a git repository
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights

Checking for .git-folder

    ls .git
    COMMIT_EDITMSG  config  description  HEAD  hooks/  index  info/  logs/  objects/  refs/

#### Work around

    rm -drf .git

### Environment

N/A

**Comment by sidharthachatterjee** [comment]
@jmrnilsson You're seeing a `.git` folder because `gatsby new` initialises a new repo for you when you create a site. 

This is _by design_ and you're seeing expected behaviour 🙂
