### ISSUE TITLE
Wordpress Content Stripped After Client Hydrates

### ISSUE THREAD

**Issue by yazeedb** [gatsbyjs/gatsby#19892]
## Description

In production, all Wordpress-sourced content is removed when the client-side JavaScript kicks in and hydrates the page.

However visiting subsequent pages works fine, and the client-side render does not strip any content.

### Demo
![](https://im2.ezgif.com/tmp/ezgif-2-81f444486e2f.gif)

### Steps to reproduce
Unfortunately my WP data is still local, so you won't be able to reproduce locally.

### Repository
https://github.com/yazeedb/elzahra-website

### Expected result
Wordpress content shouldn't be stripped after client-side JS kicks in.

### Actual result
Server-side render is fine, but client-side JS strips Wordpress content from the page.

### Environment
  System:
    OS: macOS 10.15.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11 
    gatsby-image: ^2.2.31 => 2.2.31 
    gatsby-plugin-manifest: ^2.2.27 => 2.2.27 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6 
    gatsby-plugin-offline: ^3.0.19 => 3.0.19 
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14 
    gatsby-plugin-sharp: ^2.2.37 => 2.2.37 
    gatsby-source-filesystem: ^2.1.36 => 2.1.36 
    gatsby-source-wordpress: ^3.1.47 => 3.1.47 
    gatsby-transformer-json: ^2.2.18 => 2.2.18 
    gatsby-transformer-sharp: ^2.3.3 => 2.3.3 
  npmGlobalPackages:
    gatsby: 2.4.2

**Comment by LekoArts** [comment]
Hi, thanks for the issue! You didn't provide a demo link and a reproduction. Please do that so that we're able to help you. Thanks!
