### ISSUE TITLE
How to create dynamic content/Pages using JSON files in Gatsby?

### ISSUE THREAD

**Issue by prashant1k99** [gatsbyjs/gatsby#19894]
I wish to create a complex routing in Gatsby using multiple JSON files:

First JSON file is based on routing:
**File Location:** */src/data/route.json*
```json
[
  {
    "type": "Article",
    "title": "Post One",
    "slug": "/post-one",
    "data": "post-one.json"
  },
  {
    "type": "Course",
    "title": "Course One",
    "slug": "/course-one",
    "data": "course-one.json"
  },
  "Multiple data here"
]
```
It is the Json file which contains route data.
Now in `post-one.json` file contains all the required data about the post that is required to render the post.

**File Location:** */src/data/articles/post-one.json*
**Routes:** */post-one*
```json
{
  "title": "Post One",
  "head": {
    "title": "Some title here",
    "image": "/path/to/image.jpg",
    "description": "Some description here..."
  },
  "body": {
    "Body data here"
  }
}
```

But the main problem arises now as the courses is the collection of the different chapters.
Now for the main course page:
**File location :** */src/data/courses/course-name.json*
**Route is like:** */course-name*

```json 
{
  "title": "Course One",
  "head": {
    "title": "Some title here",
    "image": "/path/to/image.jpg",
    "description": "Some description here..."
  },
  "info": {
    "Some info about the course..."
  },
  "chapter": [
    {
      "title": "chapter one",
      "slug": "/:courseId/chapter-one",
      "description": "Something about the chapter"
    },
    {
      "title": "chapter two",
      "slug": "/:courseId/chapter-two",
      "description": "Something about the chapter"
    },
    "Multiple chapters in the same course"
  ]
}
```

Now the chapters will have the data like
**File location :** */src/data/chapters/chapter-name.json* 
**Route:** */courseId/chapter-name*
```json
{
  "title": "Chapter one",
  "description": "Some description here",
  "body": {
    "Content for the body that can be rendered easily"
  }
}
```

**Comment by prashant1k99** [comment]
@asilgag It is somewhat similar to the scenario you explained https://github.com/gatsbyjs/gatsby/issues/19512#issuecomment-557527111 here. Can you help me out please.

**Comment by LekoArts** [comment]
Thank you for opening this!

I'm not sure what your question is however I assume you want those JSON files to "connect"? You can map files together via the schema customization API:
https://www.gatsbyjs.org/docs/schema-customization/#foreign-key-fields

You previously mostly did this via mapping in gatsby-config:
https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
