### ISSUE TITLE
Reconciliation issue when node contains text and JSX expression

### ISSUE THREAD

**Issue by vtrpldn** [gatsbyjs/gatsby#19904]
Hey everyone!

## Description

This one looks much more like a React issue than a Gatsby one but since I was unable to reproduce the behavior on a codesandbox with the same React and React DOM versions I'm filling it here.

Here's the gist: `<div>{count}</div>` and `<div>Count: {count}</div>` are not rendering state updates the same way. The first example works every time while the former stops working if you increment the state faster.

### Steps to reproduce

Reproducible test case is available below but the example is so simple that I'll post here as well:

```
const App = () => {
  const [count, setCount] = useState(0)

  return (
    <>
      <h2 onClick={() => setCount(count => count + 1)}>Click to increment</h2>
      <h2>This count will update normally:
          <div>
          {count}
        </div>
      </h2>
      <h2>This count will stop updating if you click really fast: <br /> {count}</h2>
    </>
  )
}
```

Repro repo built from gatsby-starter-default: https://github.com/vtrpldn/gatsby-issue-repro

### Expected result

The expected result would be like the codesandbox below. Both `<div>{count}</div>` and `<div>Count: {count}</div>` should keep incrementing and rendering despite how fast you change the state.

https://codesandbox.io/s/forceupdateusingusereducer-k8wbu?fontsize=14&hidenavigation=1&theme=dark

### Actual result

`<div>{count}</div>` updates all the time and `<div>Count: {count}</div>` sort of breaks if you make it update faster than a second (give or take a few ms)

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Shell: 2.7.1 - /usr/bin/fish
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0.1
  npmPackages:
    gatsby: ^2.18.4 => 2.18.5 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-manifest: ^2.2.30 => 2.2.30 
    gatsby-plugin-offline: ^3.0.24 => 3.0.25 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16 
    gatsby-plugin-sharp: ^2.3.4 => 2.3.4 
    gatsby-source-filesystem: ^2.1.39 => 2.1.39 
    gatsby-transformer-sharp: ^2.3.6 => 2.3.6 
  npmGlobalPackages:
    gatsby-cli: 2.8.14

**Comment by blainekasten** [comment]
@vtrpldn thanks for the detailed issue and the example repo. I really appreciate the effort here. I cloned the repo and ran it as yarn develop. I didnt see any issues clicking "very fast" 😆 but maybe i'm not the fastest clicker.

This would surprise me if gatsby had anything at play here. We don't tie into the reconilliation phase of react at all, but maybe we are goofing something up with a babel transpile. 

My best guess as of right now is that you have some browser plugins that are causing issues. Do you mind testing on your machine in an incognito window and reporting back?

**Comment by blainekasten** [comment]
I'm going to close this issue as I don't believe it's reporting a problem with Gatsby. I'm happy to keep the discussion going, so don't take this as a negative sign. Please report back if you need continued support! 😃
