### ISSUE TITLE
Help improving lighthouse performance score

### ISSUE THREAD

**Issue by zanehiredevs** [gatsbyjs/gatsby#19902]
Hi we recently launched a `gatsby` + `contentful` site on Netlify for a restaurant in SF [Bamboo Asia](https://www.bambooasia.com) and it seems really fast but lighthouse is showing a bad number for performance even on our simple pages.

I'm not sure what is causing it, we aren't doing anything special, we are using styled components and mobx-react but it's a standard gatsby v2 setup for the most part.  I did notice that the logo/top nav seems to flicker on first load and not really sure why.  Can someone help us figure out how to troubleshoot it and why it's getting the bad performance score?  I'd love to send this out and have it as a showcase gatsby site but I'd like to fix the lighthouse performance score first.

Note we are not doing a PWA or using the offline plugin because we were seeing strange caching issues with page-data.json after deploys.  Also the home page uses a legacy jquery slideshow with no react equivalent so we're stuck with that but even the [jobs page](https://www.bambooasia.com/jobs/) that has nothing on it is getting a bad score (83) for performance.

![image](https://user-images.githubusercontent.com/44630404/69917324-6d607f80-1419-11ea-9e63-4883f9b2d3ff.png)

Any help appreciated!

**Comment by danoszz** [comment]
@zanehiredevs I think this is not the right place to ask your question. Gatsby never promises to score 100/100 on Google Lighthouse. Please consider moving your question to [Discord](https://discordapp.com/invite/br9rbUE) to get more help.

I think you answered your question by saying that you aren't doing anything special. Making your website perfectly optimized for Lighthouse is a specialized task. But, when I run an audit, it shows 96/100 - 82/100 - 100/100 - 100/100, so I think you did a great job already. 

To answer your other question regarding the logo flickering, you can try to define a height and width for the logo wrapper; it shouldn't flicker and move the layout. If every element has a predefined area to load in, the layout should stay intact.

**Comment by zanehiredevs** [comment]
@danoszz Sounds good thanks for the feedback I'll see what I can figure out and hit up Discord if necessary 👍
