### ISSUE TITLE
Link inside link causes wrong static html build

### ISSUE THREAD

**Issue by LesleyLai** [gatsbyjs/gatsby#19906]
## Description

Link in link causes wrong static HTML to get generated. The incorrect visual can be seen for a short period of time when first load the page or when Javascript got disabled.

### Steps to reproduce

Create a page in a gatsby project with the following contents:

```jsx
export default () => <div>
  <a href="#1">
  <p>Outer a</p>
  <a href="#2">inner A</a>
  <p>More outer a</p>
  </a>
</div>
```

`gatsby build` and open the HTML in the `public` folder.

### Expected result
![right](https://user-images.githubusercontent.com/8359374/69929611-d1685f80-147c-11ea-82fb-f17940bf03a8.png)
![right_html](https://user-images.githubusercontent.com/8359374/69929615-d62d1380-147c-11ea-9e67-ceb369122fbc.png)

### Actual result
![wrong](https://user-images.githubusercontent.com/8359374/69929573-b269cd80-147c-11ea-8e64-b6a39b8364ae.png)
![wrong_html](https://user-images.githubusercontent.com/8359374/69929591-beee2600-147c-11ea-87c0-1657ad5dca08.png)

### Environment
```
  System:
    OS: Linux 4.19 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 13.2.0 - /usr/bin/node
    Yarn: 1.19.2 - /usr/bin/yarn
    npm: 6.13.1 - /usr/bin/npm
  Languages:
    Python: 3.8.0 - /usr/bin/python
  Browsers:
    Firefox: 70.0.1
  npmPackages:
    gatsby: ^2.18.4 => 2.18.4
  npmGlobalPackages:
    gatsby: 2.18.5
```

**Comment by LekoArts** [comment]
Thank you for opening this!

Nesting anchor tags is not legal and will always show the results you're seeing:
https://stackoverflow.com/questions/34733391/are-nested-a-links-legal

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
