### ISSUE TITLE
question about license and gatsby-plugin-sharp plugin dependency

### ISSUE THREAD

**Issue by mislocin** [gatsbyjs/gatsby#19913]
The entire gatsby is licensed under MIT and the gatsby-plugin-sharp plugin does not list any other license, therefore, I would normally assume it falls also under the same license? However, it depends on potrace which is GPL 2.0 (https://github.com/tooolbox/node-potrace) -> meaning that gatsby-plugin-sharp should also be released under GPL 2.0? Or should entire gatsby be distributed under GPL 2.0? Any thoughts are welcome, I'm slightly confused regarding legal consequences of using gatsby & gatsby-plugin-sharp.

**Comment by LekoArts** [comment]
Hi! There is an issue for that already :)
https://github.com/gatsbyjs/gatsby/issues/17584
