### ISSUE TITLE
Couldn't find any versions for "gatsby-core-utils" that matches "^1.0.22"

### ISSUE THREAD

**Issue by salvoravida** [gatsbyjs/gatsby#19912]
## Description
Couldn't find any versions for "gatsby-core-utils" that matches "^1.0.22"
### Steps to reproduce

gatsby new gatsby-site

npm 1.0.22 is not published!

**Comment by csergiu** [comment]
Same error, I need to deploy the website in production right now, what is happening?!

**Comment by salvoravida** [comment]
ok now it is on npm!
