### ISSUE TITLE
Generating an html file for use in iframe

### ISSUE THREAD

**Issue by moroshko** [gatsbyjs/gatsby#19928]
I'm using [`html-webpack-plugin`](https://webpack.js.org/plugins/html-webpack-plugin/) to generate `frame.html` that will be used in an iframe like this:

```jsx
<iframe src="/frame.html" ... />
```

However, when I run `gatsby develop`, I get:

```
ERROR #98123  WEBPACK

Generating SSR bundle failed

Conflict: Multiple chunks emit assets to the same filename render-page.js (chunks frame and main)
```

Repro is here: [moroshko/gatsby-iframe-issue](https://github.com/moroshko/gatsby-iframe-issue)

See [here](https://github.com/gatsbyjs/gatsby/issues/19872) for more context.

Any ideas?

**Comment by LekoArts** [comment]
Seems like you got your answer here:
https://stackoverflow.com/questions/59147394/generating-an-html-file-for-use-in-iframe

Would appreciate it if you could close your issues in the future then. Thanks!
