### ISSUE TITLE
Gatsby Link's activeClassName Does Not Work When the URL Contains Germanic Umlauts 

### ISSUE THREAD

**Issue by adonig** [gatsbyjs/gatsby#19927]
## Description

The active class does not get appended if a URL contains German umlauts like ä, ö, ü or ß.

### Steps to reproduce

Add a Link to a page pointing to the page itself and set the activeClassName.

https://github.com/adonig/gatsby-bug-repro-active-link-with-umlauts

### Expected result

The active class should get appended.

### Actual result

The class gets appended only if the link does not contain umlauts.

### Environment

  System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 10.17.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/opt/node@10/bin/npm
  Languages:
    Python: 2.7.17 - /Users/asd/.pyenv/shims/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.18.4 => 2.18.4 
  npmGlobalPackages:
    gatsby-cli: 2.8.15

**Comment by LekoArts** [comment]
Thank you for opening this!

Searching through the internet it seems that umlauts are not allowed in CSS class names:
https://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by adonig** [comment]
Hi @LekoArts! Thank you for your reply. I think I did not express myself well. The problem is not that I want to use Germanic umlauts in CSS class names. The problem is that my slugs contain Germanic umlauts (because it is a German website and we have 2019). I think Gatsby Link's mechanism setting the active class should also work for websites having umlauts in their slugs. Nowadays more and more websites (i.e. amazon.de) start having unicode in their slugs in the sense of Google's "Make slugs for humans, not robots" guideline.
