### ISSUE TITLE
Regular check to find unlinked docs

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#19932]
Per @shannonbux, it would be ideal to have a way to call out docs that aren't linked in the sidebar.

The Gatsby sidebar is populated from this file: https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml

It's possible to create a doc in https://github.com/gatsbyjs/gatsby/tree/master/docs/docs and forget to update `doc-links.yaml`.

The automation would be on a cron job (maybe monthly?) that would:

1. Read all the files in `/docs/docs`
2. Load `doc-links.yaml`
3. Find all files that are **not** referenced in `doc-links.yaml`
4. Create (or update) an issue assigned to @gatsbyjs/docs that lists unlinked docs

**Comment by m-allanson** [comment]
This could be done as a GitHub Action I think? And could then run on any PR that adds / renames a file in the docs directory.
