### ISSUE TITLE
async-requires.js relative includes broken since #18973

### ISSUE THREAD

**Issue by jrestall** [gatsbyjs/gatsby#19931]
## Description

After the changes made in https://github.com/gatsbyjs/gatsby/pull/18973, specifically [these](https://github.com/gatsbyjs/gatsby/pull/18973/files#diff-ac5196f8e8e35e4455b30b9164e3c45bR148-R158) lines, my website no longer builds successfully.

This is because async-requires.js previously imported components like this, which worked great:
```
  "component---cache-page-templates-example-jsx": () => import("C:\\git\\nexus-ui\\website\\.cache\\page-templates\\example.jsx" /* webpackChunkName: "component---cache-page-templates-example-jsx" */),
```

After the recent change, components are now imported like this:
```
"component---cache-page-templates-example-jsx": () => import("page-templates/example.jsx" /* webpackChunkName: "component---cache-page-templates-example-jsx" */),
```

It works if I change it to import files using ./ at the start:
```
import("./page-templates/example.jsx" /* webpackChunkName: "component---cache-page-templates-example-jsx" */)
```
The templates are dynamically generated so need to be in the cache folder so that they get cleaned up during ```gatsby clean```.

### Steps to reproduce

1. Create a page using a component path that is within the /.cache/ folder. e.g. ```createPage({component: "C:\\git\\website\\.cache\\page-templates\\example.jsx"})```
2. Run gatsby build.

### Expected result

Successful build.

### Actual result

```
ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Can't resolve 'page-templates/example.jsx' in 'C:\git\nexus-ui\website\.cache'

File: .cache\async-requires.js
```

### Environment

  System:
    OS: Windows 7
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15

@wardpeet

**Comment by jaymdq** [comment]
Having the same problem

**Comment by Atr0p** [comment]
Also with gatsby-plugin-i18next

**Comment by jrestall** [comment]
Can this please be triaged @gatsbyjs/core. It seems to have been missed and is breaking existing sites that were working fine.

**Comment by R1cro** [comment]
@Atr0p got the same issue with `gatsby-plugin-i18next` when `gatsby build`...

```
Generating JavaScript bundles failed

Can't resolve '@wapps/redirect.js' in '../.cache'

File: .cache/async-requires.js
```

@wardpeet  @pieh @freiksenet could you kindly take a look?

**Comment by R1cro** [comment]
I made downgrade to  

```"gatsby": "2.16.5",``` 

...and it resolved my issue. 

CC: @jrestall, @Atr0p

**Comment by vladar** [comment]
This starter could be used for reproduction: https://github.com/ikhudo/gatsby-i18n-plugin/tree/master/starters/gatsby-starter-i18next
