### ISSUE TITLE
Dynamically building page queries

### ISSUE THREAD

**Issue by SachaG** [gatsbyjs/gatsby#19936]
## Summary

Currently, you can pass arguments to a page query but the *contents* of the query itself can't be changed for a given template. 

It could be useful to have an API for programmatically generating a page template's query at build time. 

### Motivation

Let's imagine a site that has 10 pages that all follow the same template, except they contain different widgets. So page 1 has widgets A, B; page 2 has widgets A, C, E; page 3 has B, D, E, etc.

Each widget needs its own set of data loaded via Gatsby's GraphQL API, which in turn means its own query fragment. Currently, since each page has different data requirements it would mean having a different template for each page which is not ideal. 

On the other hand, if queries could be put together dynamically you would be able to look at the widget list for each page and put together a query based on that. 

See also: https://github.com/gatsbyjs/gatsby/issues/16753

**Comment by SachaG** [comment]
Note that there would probably be less of a need for this if StaticQuery accepted arguments (https://github.com/gatsbyjs/gatsby/issues/10482)

**Comment by vladar** [comment]
Did you try using `skip` and `include` directives depending on page query variables?

As in the following [example](https://graphql.org/swapi-graphql/?operationName=Hero&query=query%20Hero(%24withHomeworld%3A%20Boolean!)%20%7B%0A%20%20allPeople%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20homeworld%20%40include(if%3A%20%24withHomeworld)%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22withHomeworld%22%3A%20false%0A%7D):

```graphql
query Hero($withHomeworld: Boolean!) {
  allPeople {
    edges {
      node {
        name
        homeworld @include(if: $withHomeworld) {
          name
        }
      }
    }
  }
}
```

This should also work [with fragments](https://graphql.org/swapi-graphql/?operationName=Hero&query=query%20Hero(%24withHomeworld%3A%20Boolean!)%20%7B%0A%20%20allPeople%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20...Homeworld%20%40include(if%3A%20%24withHomeworld)%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Afragment%20Homeworld%20on%20Person%20%7B%0A%20%20homeworld%20%7B%0A%20%20%20%20name%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22withHomeworld%22%3A%20false%0A%7D):

```graphql
query Hero($withHomeworld: Boolean!) {
  allPeople {
    edges {
      node {
        name
        ...Homeworld @include(if: $withHomeworld)
      }
    }
  }
}

fragment Homeworld on Person {
  homeworld {
    name
  }
}
```

**Comment by SachaG** [comment]
@vladar that's a nice tip but I don't know if it works for what I'm trying to do. You can compare pages like https://2018.stateofjs.com/front-end-frameworks/overview/ and https://2018.stateofjs.com/front-end-frameworks/react/ and see that they both are made of similar blocks, but because the blocks are different the corresponding queries are also completely different…

**Comment by vladar** [comment]
`Fragment` is the main concept in GraphQL to support this kind of composition unless you have a very dynamic page structure (as some CMSes do), but that is usually not the case with Gatsby sites.

You could put fragment definitions in your components and spread them in your page query (with include/skip depending on page variables). Components may, in turn, spread fragments of child components they render, etc.

Adding new APIs is expensive in terms of maintenance and it's worth exploring existing options first.

**Comment by jrestall** [comment]
I wonder if something like this would work for you, it would depend on where and how you are defining the pages.

```
query Page($title: String) {
  pages(title: $title) {
    widgets {
      ...Widgets
    }
  }
}

fragment Widgets on CMS_Widget {
  name
  ...WidgetA
  ...WidgetB
  ...WidgetC
  ...WidgetD
  ...WidgetE
}

fragment WidgetA on CMS_WidgetA {
  data1
  data2
}
```

And then you could have a Widgets component in the page template that takes the array of widgets and can render them based on the name of each widget. E.g.

```
export function Widgets({ widgets }) {
  if (!widgets) {
    return null
  }

  // Loop through all the page widgets and render
  return widgets.map((widget, index) => (
    <Widget key={index} widget={widget} />
  ))
}

export default function Widget({ widget, ...props }) {
  // A registry of all your widget mappings
  const widgetsRegistry = {
    'WidgetA': WidgetA,
    'WidgetB': WidgetB
  }

  const Component = widgetsRegistry[widget.name]

  if (!Component) {
    console.log(`Couldn't find a registered widget for the ${widget.name} widget.`)
    return null
  }

  return React.createElement(Component, { widget, ...props })
}
```
A more complex approach than this, with bundle splitting and widget discovery, has worked well for me when I needed to define lots of pages that can all be configured with different widgets.

**Comment by SachaG** [comment]
Thanks that's really interesting!

Another related issue (that this feature would admittedly not solve) is that even if we build our query in a modular fashion, we then also need to tell each component how to extract its own data from the entire page query data, which adds a little complexity to our architecture. But I guess that's a separate issue…

**Comment by jrestall** [comment]
The interface approach solves that by just having the widget's properties passed into the component from the Widget component, so no need for it to know about the entire query e.g.

widgetA.js
```graphql
export default function WidgetA({ data1, data2 }) {

}

fragment WidgetA on CMS_WidgetA {
  data1
  data2
}
```
I agree though, it would be better if the gatsby framework was more extensible and had more events that could be tapped similar to how webpack is architected. 80% of webpack's core is made up of its own plugin system and since it is an event-driven architecture there is always a hook available to insert your own code. With gatsby it's a struggle if you want to extend its core behavior in a lot of areas e.g. plugin loading, query compilation etc.

**Comment by vladar** [comment]
> Another related issue (that this feature would admittedly not solve) is that even if we build our query in a modular fashion, we then also need to tell each component how to extract its own data from the entire page query data

Apollo has tools for [filtering fragment data](https://www.apollographql.com/docs/react/data/fragments/#filtering-with-fragments). I guess we could do something similar. But yeah, this is a separate thing.

**Comment by SachaG** [comment]
FYI I ended up going with [this approach](https://nickdrane.com/optimizing-gatsby-build-times-for-large-websites-using-pagecontext/) where I don't use page queries at all. Since our whole site is built from YAML files through gatsby-node I think this is what made the most sense.

**Comment by jrestall** [comment]
Thanks for the update @SachaG, that's also the approach I use, except I dynamically discover the widget fragments which means avoiding the downside of not colocating template components alongside their associated GraphQL queries.

https://github.com/jrestall/gatsby-orchardcore/blob/master/packages/gatsby-theme-orchardcore-contents/gatsby-node.js#L83-L90

I also wrap each page in its own generated template since I have 100's of widgets and want code splitting to manage bundle sizes. Definitely more complex than most sites need though.

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
