### ISSUE TITLE
CSS Ordering in Gatsby

### ISSUE THREAD

**Issue by brsanthu** [gatsbyjs/gatsby#1994]
I have been trying to setup gatsby build with bootstrap but not getting the things as expected. Here is what I'm looking to achieve.

1. Load bootstrap
2. Load open sans font using typeface-open-sans module
3. Load application's global styles
4. Load layout's styles
5. Load component styles

Tried putting import in html.js, didn't work
Tried putting import in layouts/index.jsx, didn't work

I get the exact order opposite of what I'm looking for (that is loading comps styles, layout styles, fontface and then finally bootstrap).

Any help is much appreciated.

**Comment by KyleAMathews** [comment]
A reproduction site would be nice!

**Comment by hew** [comment]
Using sass? I've noticed that webpack will inject style imports into the head in seemingly random orders. Since Sass mostly depends on the order (resets, etc), it's problematic. I have not yet found a workaround. I'll update if I do.

**Comment by brsanthu** [comment]
Yes, we are using Saas.

**Comment by hew** [comment]
Yeah check out [this issue](https://github.com/webpack/webpack/issues/215). According to Sokra, the order is random during development, which isn't good.

**Comment by hew** [comment]
To be fair, this seems to be not a Gatsby-specific issue. More a webpack one.

**Comment by speedDeveloper** [comment]
I am having the same problem, any suggestions yet?

**Comment by 304NotModified** [comment]
Yes, please create a small sample application to reproduce the problem ;)

**Comment by speedDeveloper** [comment]
Thank you @304NotModified, the repo is here https://github.com/speedDeveloper/philippczernitzki.me
When you start the gatsby blog, you see that font-awesome overrides styled-components styles.
For example the icons below the banner should have an increased font-size. It's not working because font-awesome is loaded after styled-components stylesheet.

![image](https://user-images.githubusercontent.com/10871302/33949711-b7fff1d0-e02a-11e7-9e72-52478e746f66.png)

**Comment by KyleAMathews** [comment]
You need to modify the default order of loading CSS — the default is CSS is loaded *after* css-in-js. Copy `.cache/default-html.js` to `src/html.js` and then switch the order of these two lines https://github.com/gatsbyjs/gatsby/blob/99e3249438f4bf23267d68c538a42c3a1aba04b5/packages/gatsby/cache-dir/default-html.js#L32-L33

**Comment by speedDeveloper** [comment]
Hey thank you very much. But sadly it doesn't work for my project. Font-Awesome still overrides the css of styled-components.
Here is the html.js file https://github.com/speedDeveloper/philippczernitzki.me/blob/master/src/html.js

**Comment by KyleAMathews** [comment]
Oh how are are you adding font-awesome?

**Comment by speedDeveloper** [comment]
```import '../css/index.css';
import React from 'react'
import Link from 'gatsby-link'
import 'font-awesome/css/font-awesome.min.css';

import styled, { ThemeProvider } from 'styled-components';
```
I am adding the styles like this. It's in `layouts/index.js`. Hope this helps @KyleAMathews 

https://github.com/speedDeveloper/philippczernitzki.me/blob/master/src/layouts/index.js

**Comment by KyleAMathews** [comment]
@speedDeveloper I tried cloning your repo and running it locally and it had a bunch of errors e.g. you were querying markdown and there isn't a markdown file, you'd commented out the typography.js module which broke components which had imported the rhythm function from it. There was also an error while generating the HTML.

If you could fix your site so I can build it, I'd be happy to try to figure out why you can't get the CSS working.

**Comment by speedDeveloper** [comment]
Thank you @KyleAMathews. I am sorry for the errors. They are solved now. Creating a build works now but the css order is still wrong.

**Comment by speedDeveloper** [comment]
It seems like `pages/blog.js` loads before `pages/index.js` and `layouts/index.js`.

**Comment by codejamninja** [comment]
I'm having a similar issue at #9908

**Comment by selrond** [comment]
> You need to modify the default order of loading CSS — the default is CSS is loaded _after_ css-in-js. Copy `.cache/default-html.js` to `src/html.js` and then switch the order of these two lines
> 
> https://github.com/gatsbyjs/gatsby/blob/99e3249438f4bf23267d68c538a42c3a1aba04b5/packages/gatsby/cache-dir/default-html.js#L32-L33

@KyleAMathews Why is that? Does it make sense to import static files after css-in-js? I would like to know the reasoning behind this

**Comment by fullofcaffeine** [comment]
> You need to modify the default order of loading CSS — the default is CSS is loaded _after_ css-in-js. Copy `.cache/default-html.js` to `src/html.js` and then switch the order of these two lines
> 
> https://github.com/gatsbyjs/gatsby/blob/99e3249438f4bf23267d68c538a42c3a1aba04b5/packages/gatsby/cache-dir/default-html.js#L32-L33

How do I go about re-ordering the CSS placement on the header nowadays? The latest Gatsby version's `default-html.js` does not include that logic anymore, it seems you're injecting the css from somewhere else, but I couldn't find where yet. 

I need to force the css (included (somehow) by `gatsby-plugin-sass`) to be loaded BEFORE the styles added by `gatsby-typography`. 

Any insights greatly appreciated!
