### ISSUE TITLE
Warn on invalid config format

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#19941]
## Description

Gatsby does not support using functions in its config, but it does not complain if you do. This can result in silent failures that are difficult to debug.

Possibly related PR: https://github.com/gatsbyjs/gatsby/pull/16027

### Steps to reproduce

cc @sidharthachatterjee do you have an example that can go here?

### Expected result

Gatsby should complain that your config is invalid.

### Actual result

Gatsby does not complain, instead unrelated errors appear later in the build process.

### Environment

n/a

**Comment by wardpeet** [comment]
We're launching a new api soon. It will give proper error messages based on Joi schema.
