### ISSUE TITLE
Proposal: Implement optimizations for JSX, Hooks and Code Splitting

### ISSUE THREAD

**Issue by developit** [gatsbyjs/gatsby#19943]
## Summary

Over the past few months, we've been working with the Next.js team to implement various transparent optimizations. There are three that seem highly applicable to Gatsby.

## The Optimizations

[**Transparent JSX Optimization**](https://github.com/zeit/next.js/pull/8350)

This Babel transform changes JSX output to avoid thousands of JavaScript property accesses in compiled JSX and reduces the impact of JSX on JavaScript parsing time.

[**Optimize Hook Destructuring**](https://github.com/zeit/next.js/pull/8381)
This Babel plugin implements [my original recommendation](https://twitter.com/_developit/status/1057636803354648582) from the V8 team's [investigation](https://docs.google.com/document/d/1hWb-lQW4NSG9yRpyyiAA_9Ktytd5lypLnVLhPX9vamE/edit#heading=h.itx3j0uehx4f) into the performance impact of Array destructuring in React Hooks. It's transparent to the developer, and has the added benefit of producing significantly less code when Babel is configured in strict mode.

[**Granular Code Splitting**](https://github.com/zeit/next.js/pull/7696)
Gatsby and Next both shared similar [SplitChunks](https://webpack.js.org/guides/tree-shaking/) configurations up until recently. @atcastle [proposed](https://github.com/zeit/next.js/issues/7631) and subsequently [landed an implementation](https://github.com/zeit/next.js/pull/7696) of a more granular chunking strategy that has been [shown](https://twitter.com/NatalieMarleny/status/1162841909875892224) to load less code per-entry for common cases by producing additional shared dependency chunks loaded on-demand.

### Motivation

Collectively, bringing these optimizations to Gatsby would represent a nontrivial improvement in output and performance.

## Further Optimization

It may also be possible to implement the `module/nomodule` pattern (#2114) using a Child Compiler technique similar to what @janicklasralph [implemented in Next](https://github.com/zeit/next.js/pull/7704). His work was based on [babel-esm-plugin](https://github.com/prateekbh/babel-esm-plugin), which I'm working to backport the generalized improvements into. This would enable Gatsby to benefit from [@babel/preset-modules](https://github.com/babel/preset-modules), especially true here since Babel is already being used to transform `node_modules` (yay!).

/cc @wardpeet @spanicker

**Comment by wardpeet** [comment]
Awesome @developit, thanks for opening this issue. The babel plugins should be low effort to implement. Module/no-module was stalled because of our work on gatsby cloud. I'll continue with it after the jobs api, which should be in a week or so.

Nonetheless, other core members could do the babel transformations plugins if they can get to it. The granular chunks we need to check if we can implement it as an experiment or as a plugin for now.

**Comment by developit** [comment]
Sounds good. I like the idea of testing out the new chunking stuff as a plugin.

**Comment by wardpeet** [comment]
This has only been partially fixed, I still have to add the 2 babel plugins

**Comment by moonmeister** [comment]
In #22253 it was mentioned that `react`/`react-dom` were move to a framework package. Does this apply if we're using preact? If not is this possible?

**Comment by moonmeister** [comment]
Okay, after some attempts to do this I did manage to get preact working (i think). But It'd be nivce if there was a better way we could use to update the preact plugin. 
```js

const FRAMEWORK_BUNDLES = [
  `preact`,
  `react`,
  `react-dom`,
  `scheduler`,
  `prop-types`,
];

exports.onCreateWebpackConfig = ({ stage, getConfig, actions }) => {
  if (stage === "build-javascript") {
    const config = getConfig();

    config.optimization.splitChunks.cacheGroups.framework.test = new RegExp(
      `(?<!node_modules.*)[\\\\/]node_modules[\\\\/](${FRAMEWORK_BUNDLES.join(
        `|`
      )})[\\\\/]`
    );

    actions.replaceWebpackConfig(config);
  }
};
```
