### ISSUE TITLE
Is code-splitting done different since 2.13?

### ISSUE THREAD

**Issue by manuelJung** [gatsbyjs/gatsby#19957]
I have a very big Gatsby app with over 800 pages and many components. In Gatsby v2.13 code-splitting works very well. But when I want to upgrade Gatsby to a newer version only 2 chunks are created: commons.js and app.js. That leads my commons.js to a g-zipped size of 800kb what is way to much. 
The really dramatic part about this is, that my lighthouse performance drops from 94 to 62 in average. So what is done different in later Gatsby versions? how can I get the old behaviour in newer gatsby versions?

**Comment by manuelJung** [comment]
for more context: the generated files for gatsby v2.18:
![image](https://user-images.githubusercontent.com/12029269/70248939-f8c07480-177b-11ea-99e4-c1031f975305.png)

and the generated bundles for gatsby v2.13:
![image](https://user-images.githubusercontent.com/12029269/70249026-168dd980-177c-11ea-8351-16a52ddc038d.png)

**Comment by wardpeet** [comment]
Hey, yes things have changed but they should have changed for the better not the worst. Could you perhaps send me your git repository so I can have a look? You can send it to ward@gatsbyjs.com, thanks in advance!

**Comment by philip-akerfeldt** [comment]
Any news on this matter?

**Comment by turistua** [comment]
Is there any additional ways to investigate commons.js content? I use gatsby-plugin-webpack-bundle-analyzer, however it doesn't explain why I have these components inside of commons.js

For my case the size of the page is around 280kB, which is not what I expect when open lightweight home page

**Comment by wardpeet** [comment]
Hey @manuelJung,

sorry to keep you waiting but our bundle strategy should be way better starting from `gatsby@2.20.7`. Please let me know if this works for you or not.

Thanks!

**Comment by manuelJung** [comment]
@wardpeet looks good. bundles are splitted correctly :) thanks for your effort

**Comment by wardpeet** [comment]
Awesome! I'll be marking this issue as resolved.

Thank you again for filling this bug!
