### ISSUE TITLE
How to add style in 404 page?

### ISSUE THREAD

**Issue by zhaozhiming** [gatsbyjs/gatsby#1995]
Hi, I add a `404.js` in `src/pages/` and it work, but I found the styles in pages no working.  
How can I add style with the 404 page? Thanks.   

![image](https://user-images.githubusercontent.com/1436694/29991554-aba069c0-8fbb-11e7-964c-716081a1424c.png)

**Comment by dvzrd** [comment]
If your css dir is in root and not src, you need to update your import path to something like this: `../../css/404.css'`

**Comment by zhaozhiming** [comment]
@dvzrd Thanks, but my css file is in the `src` folder.

![image](https://user-images.githubusercontent.com/1436694/29995510-5cb22602-901d-11e7-8831-b6861e79c519.png)

**Comment by zhaozhiming** [comment]
I finally found the problem. The reason is my class name start with number (something like `404-outter`, so it is no working.  
When I change the class to normal word (something like `not-found-outter`) and everything is ok.
