### ISSUE TITLE
Is there any guide for analyzing a site to identify bottlenecks in performance?

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#19955]
After developing a site I find now that I have a main-thread work (LightAudit) that should/could be reduced

I am wondering if is there any guide to benchmark the site to see if there is a specific problem somewhere in the code?

**Comment by alotama** [comment]
If I understood your question. There is a dependency called [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) witch analyze your chunks and give you the size of each of them and let you see what are you importing.

**Comment by LekoArts** [comment]
Thank you for opening this!

I'd also recommend using the bundle-analyzer to see if you can lazy load some components to reduce the initial bundle size.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by kuworking** [comment]
I'll definitively try the package

The problem is the audits I get when using low-power computers, I'm unsure whether I should just forget them or whether gatsby is also supposed to be fast there

@alotama thanks for the suggestion :)
