### ISSUE TITLE
Gatsby CLI not working on NodeJS 8.0.0

### ISSUE THREAD

**Issue by jessevdp** [gatsbyjs/gatsby#19954]
# Description

I can't run any `gatsby-cli` commands on NodeJS v8.0.0 (Windows 10). Due to some ES6 syntax.

### Steps to reproduce

1. Install NodeJS at `8.0.0` (E.g. using [NVM](https://github.com/coreybutler/nvm-windows))
1. Install `gastsby-cli` globally
1. Attempt to run ANY gatsby command. E.g. `gatsby --help`
1. See the error

### Actual result

```
gatsby --help
C:\ProgramData\nvm\v8.0.0\node_modules\gatsby-cli\node_modules\configstore\index.js:26
                                ...defaults,
                                ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\ProgramData\nvm\v8.0.0\node_modules\gatsby-cli\node_modules\gatsby-telemetry\lib\event-storage.js:17:21)
```

### Environment

I can't run the command 🙃. But here is some info about the environment:

OS: Windows 10 Pro 64 bit

```
node -v
v8.0.0

npm -v
5.0.0

npm ls -g gatsby-cli
C:\Program Files\nodejs
`-- gatsby-cli@2.8.15
```

**Comment by lannonbr** [comment]
Try updating to the latest version of Node 8 as it seems the spread operator in object literals was not added in 8.0.0 but rather 8.3.0 as noted on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by jessevdp** [comment]
I'm not _actually_ trying to run a Gatsby site on Node 8. If I were, I'd definitely be using some later minor version of Node 8.

This issue is meant to point out that Gatsby will actually not work on a version that it is supposed to support. (The `package.json` files of all gatsby packages list `>=8.0.0` as the NodeJS requirement.)

I have a Gatsby plugin. I need to make sure that my plugin works on all the same NodeJS versions as Gastsby does. For this reason, I decided to just downgrade to the earliest supported version -> `8.0.0`.

**Comment by m-allanson** [comment]
Hmmm. Maybe we should be supporting the LTS release of Node 8 rather than Node 8.0.0? The first LTS release was[Node 8.9.0](https://nodejs.org/fr/blog/release/v8.9.0/). I suspect a _lot_ of our dependencies won't work with Node 8.0.0. 

I've opened a PR to check if our tests pass on Node 8.9.0: https://github.com/gatsbyjs/gatsby/pull/19973

Note that Node 8 will reach _End of Life_ status at the end of this month. But this issue is probably worth thinking about when we bump the minimum version up to Node 10.

**Comment by jessevdp** [comment]
Sort of related (maybe). Perhaps there should be a doc explaining the strategy here. Gatsby is a big project, lots of packages. Also a lot of 3th party plugins.

The "get up and running" docs mention a set of system requirements, the NodeJS number there. You want to make sure every Gatsby plugin and package _actually_ works with those requirements. And to do that every plugin author needs to make sure their plugin follows the correct strategy.

As a plugin author I don't have anywhere to go right now. I personally do have some experience with babel so I can probably get this working—but I have no doubt this will be a first for some people.

**Comment by jessevdp** [comment]
> Note that Node 8 will reach End of Life status at the end of this month. But this issue is probably worth thinking about when we bump the minimum version up to Node 10.

Also not _really_ related to this issue, but my underlying problem -> I'll just focus on Node 10.0.0 right now.

**Comment by MichaelDeBoey** [comment]
We're waiting for Node  10 I guess? 🤔

**Comment by sidharthachatterjee** [comment]
Yup, we'll be bumping our minimum supported version to 10 LTS once we're back from  holiday next week!

**Comment by wardpeet** [comment]
@jessevdp we definitly need to do a better job at upgrading our dependencies.

**Comment by lannonbr** [comment]
Closing this issue as Node 8 support was dropped as of Gatsby 2.20.0. Update to at least Node 10.13.0 or higher.
