### ISSUE TITLE
Using "gatsby-remark-prismjs" prompt feature creates redundant pipe symbol

### ISSUE THREAD

**Issue by sp4rc** [gatsbyjs/gatsby#19964]
## Summary

When writing a markup like the example below, I get a result like this `[root@localhost] # | rm -rf /` and `1 | [alice@dev.localhost] $ | rm -rf /`. Here is a [Screenshot](https://i.imgur.com/FJg6JLq.png). 

Where does this extra pipe symbol between the prompt and command come from? 

N.B: `<three-backticks>` are really backticks... I just don't know how to properly quote it here...

```markdown
<three-backticks>bash
rm -rf /
</three-backticks>
```

or like so 

```markdown
<three-backticks>bash{promptUser: alice}{promptHost: dev.localhost}{numberLines: true}
rm -rf /
</three-backticks>
```

## Relevant information
My `_highlight.scss`

```
@import "~prismjs/themes/prism-solarizedlight";
@import "~prismjs/plugins/line-numbers/prism-line-numbers";
@import "~prismjs/plugins/command-line/prism-command-line";

/* Adjust the position of the line numbers */
.gatsby-highlight pre[class*="language-"].line-numbers {
  padding-left: 2.8em;
}

.gatsby-highlight {
  background-color: #fdf6e3;
  border-radius: 0.3em;
  margin: 0.5em 0;
  padding: 1em;
  overflow: auto;
}

.gatsby-highlight pre[class*="language-"].line-numbers {
  padding: 0;
  padding-left: 2.8em;
  overflow: initial;
}

.gatsby-highlight-code-line {
  background-color: #feb;
  display: block;
  margin-right: -1em;
  margin-left: -1em;
  padding-right: 1em;
  padding-left: 0.75em;
  border-left: 0.25em solid #f99;
}
```

### Environment (if relevant)

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.4 => 2.18.4 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-catch-links: ^2.1.19 => 2.1.19 
    gatsby-plugin-manifest: ^2.2.30 => 2.2.30 
    gatsby-plugin-offline: ^3.0.24 => 3.0.24 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16 
    gatsby-plugin-sass: ^2.1.24 => 2.1.24 
    gatsby-plugin-sharp: ^2.3.4 => 2.3.4 
    gatsby-remark-prismjs: ^3.3.25 => 3.3.25 
    gatsby-source-filesystem: ^2.1.39 => 2.1.39 
    gatsby-transformer-remark: ^2.6.39 => 2.6.39 
    gatsby-transformer-sharp: ^2.3.6 => 2.3.6 

### File contents (if changed)

`gatsby-config.js`: 
```
module.exports = {
  siteMetadata: {
    title: `Code Blog`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-sass`,
    `gatsby-plugin-catch-links`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `posts`,
        path: `${__dirname}/src/posts`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-prismjs`,
            options: {
              showLineNumbers: false,
              prompt: {
                user: "root",
                host: "localhost",
                global: true,
              },
            },
          },
        ],
      },
    },
  ],
}
```

`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi!

What happens when you remove the line numbering options + CSS? Can you [provide a minimal reproduction][reproduction]?

[reproduction]: https://gatsby.dev/reproduction

**Comment by sp4rc** [comment]
Thanks for replying. I figured it out. This additional _pipe symbol_ actually is a `border-right` set by `node_modules\prismjs\plugins\command-line\prism-command-line.css`. No idea what this border setting is doing there...

```css
.command-line-prompt {
	border-right: 1px solid #999;
	display: block;
	float: left;
	font-size: 100%;
	letter-spacing: -1px;
	margin-right: 1em;
	pointer-events: none;

	-webkit-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	user-select: none;
}

// ...
```
