### ISSUE TITLE
Question about remark and rendering markdown into HTML

### ISSUE THREAD

**Issue by dvzrd** [gatsbyjs/gatsby#1997]
From what I understand, remark is a safer way to render markdown files and I really appreciate the integration of graphql into the new version of gatsby. I just have a question that's more specific to the rendering of the actual html elements.

Before 1.0, I was using the [npm package marked](https://github.com/chjj/marked) to render my markdown into html. The reason I liked it is because it gave me the ability to control what kind of html elements would be rendered using it's renderer function. It allowed me to use markdown syntax as shortcodes to render different types of elements as need. 

For example, I can have different types of headings like so:

```
renderer.heading = function(text, level) {
    var name = kebabCase(text);
    var levelClasses;

    switch (level) {
        case 1:
            levelClasses = 'hero title';
            break;
        case 2:
            levelClasses = 'page title';
            break;
        case 3:
            levelClasses = 'statement title';
            break;
        default:
            levelClasses = 'title';
            break;
    }

    return `<h${level} class='${levelClasses}'>${text}</h${level}>`;
};
```
You could also render different image styles using renderer without having to wrap them in html inside your markdown file:

```
renderer.image = function(href, title, text) {
    var img = `<img src='${href}' alt='${text}'`;

    if (title === 'container') {
        img = `<div class='container'><img src='${href}' alt='${text}' class='image' /></div>`;
    }  else {
        img = `<img src='${href}' alt='${text}' class='image' />`;
    }

    return img;
};
```
So my question is if the same is possible with remark. I looked through the packages that exist for it but couldn't find anything  relating to this type of rendering. 

In order to use marked like in the example above would I need to make a gatsby package that uses marked to render markdown instead of remark or is there a chance I could still use both - using remark for fetching the data and using marked to actually render the html. 

Thanks for looking at the issue. I love this project and hope to contribute in some way. Maybe I can help with this if you could give me some direction.

**Comment by KyleAMathews** [comment]
Yeah you could either a) make a "gatsby-transformer-marked" plugin or b) create a remark plugin to handle conversion of specific markdown to html yourself. Many of the Remark plugins do this e.g. https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/index.js#L33-L40
