### ISSUE TITLE
[gatsby-transformer-remark] Table of contents not being generated

### ISSUE THREAD

**Issue by milesalex** [gatsbyjs/gatsby#19979]
## Summary

```
warn Skipping TableOfContents. Field 'fields.slug' missing from markdown node
warn Skipping TableOfContents. Field 'fields.slug' missing from markdown node
warn Skipping TableOfContents. Field 'fields.slug' missing from markdown node
```

Is there something im missing when implementing the query?

```
{
  allContentfulGuide(filter: {published: {eq: true}}) {
    edges {
      node {
        title
        description
        childContentfulGuideBodyTextNode {
          childMarkdownRemark {
            tableOfContents
            html
          }
        }
      }
    }
  }
}
```
Results
```
{
  "data": {
    "allContentfulGuide": {
      "edges": [
        {
          "node": {
            "title": "Testing guides",
            "description": "This is a description",
            "childContentfulGuideBodyTextNode": {
              "childMarkdownRemark": {
                "tableOfContents": "<ul>\n<li>\n<p></p>\n<ul>\n<li></li>\n</ul>\n</li>\n<li></li>\n</ul>",
                "html": "<h1>Chapter 1</h1>\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Hendrerit dolor magna eget est lorem ipsum. Nulla facilisi etiam dignissim diam quis enim lobortis. Id nibh tortor id aliquet lectus. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Vulputate ut pharetra sit amet aliquam id. Odio morbi quis commodo odio aenean sed. Auctor neque vitae tempus quam. In nulla posuere sollicitudin aliquam ultrices sagittis.
```

I read through https://github.com/gatsbyjs/gatsby/issues/4038 but i didnt find anything helpful
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by milesalex** [comment]
I got it working but the way to add it is confusing

I needed to add


      ```toc
      ```
 to every markdown article. Is this correct?

**Comment by muuvmuuv** [comment]
How did u solved it? I can not see TOC as well but have no error/warn in the console. Tried your solution but this should only affect the `gatsby-remark-table-of-contents` plugins.

**Comment by g1eny0ung** [comment]
@milesalex @muuvmuuv 

See this: https://www.gatsbyjs.org/packages/gatsby-transformer-remark/?=#configuring-the-tableofcontents

For example, `tableOfContents(pathToSlugField: "frontmatter.title")` will generate TOC relative to `"frontmatter.title"`.

**Comment by muuvmuuv** [comment]
Using `gatsby-plugin-mdx` now generate all my pages. Works better and I can add custom elements.
