### ISSUE TITLE
Blog theme's footer link not styled

### ISSUE THREAD

**Issue by nakah** [gatsbyjs/gatsby#19976]
## Description

When gatsby-theme-blog in Night mode, the 1st link is not using same CSS styles as other links:
![image](https://user-images.githubusercontent.com/10684049/70338874-fe868a80-184d-11ea-81c4-b056f54ea894.png)

However it's working fine in Day mode

### Steps to reproduce

1. Install gatsby-theme-blog
2. Start the application (gatsby develop)
3. Toogle Night mode

### Expected result

The 1st link should have the same CSS styles as other links

### Actual result

The 1st link's color is different

### Environment

System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE      
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD        
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.7 => 2.18.7
    gatsby-plugin-feed: ^2.3.23 => 2.3.23
    gatsby-theme-blog: ^1.2.6 => 1.2.6

**Comment by muescha** [comment]
it can be closed because #19977 is merged?

**Comment by nakah** [comment]
Yes 👍
