### ISSUE TITLE
External css styling

### ISSUE THREAD

**Issue by keithpacana** [gatsbyjs/gatsby#19988]
So in the production build of my website the css are all inlined. I'm trying to reduce text to code ratio and the inline CSS is affecting this. Is there any way to externalize the CSS instead?

**Comment by pieh** [comment]
What's the motivation for this? This css still be loaded it will just need another request, but there will be same amount of css so text to code ratio overall won't change

**Comment by keithpacana** [comment]
> What's the motivation for this? This css still be loaded it will just need another request, but there will be same amount of css so text to code ratio overall won't change

So is text to code ratio not affected by whether the css styling is inlined or not? My understanding was text to code ratio was calculated based on the code on the page source and I saw that the CSS was inlined and therefore I thought externalizing the CSS would solve this issue. We're trying to increase our text to code ratio for better SEO since it's very low right now (5%) compared to our old website (built in plain HTML,CSS and jQuery) which has a 20% text to code ratio. Then is it that gatsby is just heavy in js, which explains the low text to code ratio?

**Comment by tikicoder** [comment]
If you prefer I can create a new one.  I know there have been several conversations around this before, and the current CSS was done for performance.  From SEO standpoint the recommendation seems that the CSS should be external. 

https://github.com/gatsbyjs/gatsby/issues/20710

https://github.com/gatsbyjs/gatsby/issues/2289#issuecomment-517276598
