### ISSUE TITLE
[gatsby-source-contentful]: Fix plugin for Mailchimp compatibility

### ISSUE THREAD

**Issue by slavakurilyak** [gatsbyjs/gatsby#19990]
Please fix the [gatsby-source-contentful](https://www.gatsbyjs.org/packages/gatsby-source-contentful/) plugin to work with [gatsby-plugin-mailchimp](https://www.gatsbyjs.org/packages/gatsby-plugin-mailchimp) plugin.

The Mailchimp form does not show up when both plugins are added to Gatsby.

This issue was originally posted on [gatsby-theme-novela](https://github.com/narative/gatsby-theme-novela) repository as [issue #223](https://github.com/narative/gatsby-theme-novela/issues/223) and reposted on [gatsby-plugin-mailchimp](https://github.com/benjaminhoffman/gatsby-plugin-mailchimp/) repository as [issue #51](https://github.com/benjaminhoffman/gatsby-plugin-mailchimp/issues/51).

**Comment by pieh** [comment]
Is this general Gatsby issue or issue in Novela theme?
