### ISSUE TITLE
[gatsby-source-graphql] Make typeName option not required to re-use GraphQL fragments during gatsby build  and client side

### ISSUE THREAD

**Issue by jmolivas** [gatsbyjs/gatsby#19995]
## Summary

Make typeName option not required to re-use GraphQL fragments during gatsby build  and client side.

If that is optional can be useful for a use case like one GraphQL as source of truth during gatsby build  and client side rendering. if that is the case and you have a collision then you should fix this at your own GraphQL endpoint.

As mentioned by @KyleAMathews on the Drupal slack channel:
> making it optional could make sense in a sort of “use this at your own risk we will not be blamed if it messes up your site”

### Basic example

![image](https://user-images.githubusercontent.com/366275/70379967-00e9f280-18e9-11ea-9c97-fa7fbaf4f0a3.png)

As you will see on the following example I will show the same GraphQL fetching data and the one on the template file contains the prefixed name `Drupal_` 

GraphQL query used on a Gatsby template file:
```
        ... on Drupal_NodeArticle {
          fieldComponents {
            entity {
              ... on Drupal_ParagraphHeroCta {
                __typename
                id
                fieldImage {
                  entity {
                    name
                    ... on Drupal_MediaImage {
                      fieldMediaImage {
                        url
                      }
                    }
                  }
                }
              }
              ... on Drupal_ParagraphTextblock {
                __typename
              }
            }
          }
        }
```

Same GraphQL query used client side: 
```
        ... on NodeArticle {
          fieldComponents {
            entity {
              ... on ParagraphHeroCta {
                __typename
                id
                fieldImage {
                  entity {
                    name
                    ... on MediaImage {
                      fieldMediaImage {
                        url
                      }
                    }
                  }
                }
              }
              ... on ParagraphTextblock {
                __typename
              }
            }
          }
        }
```

### Motivation

We are trying to use one GraphQL as single source of truth and our goal is to reuse the GraphQL queries and fragments during gatsby build and client side

Also pinging @freiksenet as suggested by Kyle.

**Comment by vladar** [comment]
This is a bit complicated and potentially may add even more confusion. Changes may occur on both sides. Imagine Gatsby (or one of the plugins) introduces new types that conflict with your existing schema. Usually, additive changes are not breaking but in this case, they may break your site and force you to change your schema in a breaking way. This all sounds super fragile.

I would say this is something that should be solved in GraphQL itself. They have [namespaces](https://github.com/graphql/graphql-spec/issues/163) proposal so the best path is to push it forward.

Also, `gatsby-source-graphql` has several underlying issues (see #15906). I think we should solve them first (maybe in a new major version of the plugin).

**Comment by yaacovCR** [comment]
Seems in the meantime you should use the prefixed version as canonical and strip prefix (the namespace) on client end (if possible).

**Comment by yaacovCR** [comment]
Or possibly Gatsby could be smart enough to optionally add the prefix to unprefixed queries using a flag in config prior to delegation, would have to be done prior to validation...
