### ISSUE TITLE
Yarn pnp gives error

### ISSUE THREAD

**Issue by kemalgencay** [gatsbyjs/gatsby#19996]
When I add
 {
  "installConfig": {
    "pnp": true
  }
}
to the end of package.json and run yarnn install I get this error:

An unexpected error occurred: "/home/kemal/dene/kemalBlog/package.json: Unexpected token { in JSON at position 1228".
Can you help please
TIA

**Comment by pieh** [comment]
Can you show your full `package.json`?

Error you're seeing usually means that your package.json doesn't contain valid json.

**Comment by kemalgencay** [comment]
/*I just added the last 5 lines as given in https://yarnpkg.com/en/docs/pnp/getting-started
Before the addition yarn install worked fine
/*

{
  "name": "gatsby-starter-hello-world",
  "private": true,
  "description": "A simplified bare-bones starter for Gatsby",
  "version": "0.1.0",
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "dependencies": {
    "gatsby": "^2.18.4",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  },
  "devDependencies": {
    "prettier": "^1.19.1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-hello-world"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
{
  "installConfig": {
    "pnp": true
  }
}

**Comment by kemalgencay** [comment]
OK, it was a typo and I fixed it by:
 },

  "installConfig": {
	    "pnp": true
	  }
	
}
Thanks a lot
