### ISSUE TITLE
Type definition for createParentChildLink() requires owner in child node

### ISSUE THREAD

**Issue by audunru** [gatsbyjs/gatsby#19993]
## Description

I'm writing a transformer plugin in Typescript. When calling `createParentChildLink`, Typescript complains that I've not set owner in the child node.

However, I believe the owner is set by Gatsby itself.

The definition of `createParentChildLink` is:

```ts
  createParentChildLink(
    args: { parent: Node; child: Node },
    plugin?: ActionPlugin
  ): void
```

### Steps to reproduce

Given the following `gatsby-node.ts` in `plugins/gatsby-test-plugin/src`, taken from [gatsby-transformer-sharp](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/on-node-create.js)

```ts
import { GatsbyNode } from "gatsby"

const onCreateNode: GatsbyNode["onCreateNode"] = async ({ node, actions, createNodeId }) => {
  const { createNode, createParentChildLink } = actions

  const imageNode = {
    id: createNodeId(`${node.id} >> ImageSharp`),
    children: [],
    parent: node.id,
    internal: {
      contentDigest: `${node.internal.contentDigest}`,
      type: `ImageSharp`,
    },
  }

  createNode(imageNode)
  createParentChildLink({ parent: node, child: imageNode })

  return
}

module.exports = {
  onCreateNode,
}
```

### Expected result

Typescript should not report any issues in the file

### Actual result

Typescript reports the following problems:

```
Type '{ id: any; children: never[]; parent: string; internal: { contentDigest: string; type: string; }; }' is not assignable to type 'Node'.
  Types of property 'internal' are incompatible.
    Type '{ contentDigest: string; type: string; }' is not assignable to type '{ type: string; mediaType?: string | undefined; content?: string | undefined; contentDigest: string; description?: string | undefined; } & { owner: string; }'.
      Property 'owner' is missing in type '{ contentDigest: string; type: string; }' but required in type '{ owner: string; }'.
```

### Environment

```
 System:
    OS: Linux 4.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64        Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.0 - /usr/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
```

**Comment by pieh** [comment]
I think we do need to change `Node` to `NodeInput` in signature of that function (and potentially more).

For ref - here's our defs for `Node` and `NodeInput`:

https://github.com/gatsbyjs/gatsby/blob/a2901d24a0670fc0b1ac08b3e2d2c173ff0cb400/packages/gatsby/index.d.ts#L1167-L1188

Would you be interested in submitting change to our types?

**Comment by audunru** [comment]
Thanks for the reply. Yes, I will look into it.

**Comment by jngbng** [comment]
any update on this issue?

**Comment by dustinlacewell** [comment]
Just want to know that this is still an issue.

**Comment by alvis** [comment]
After analysing the code, it appears to me that we may need the complete parent node as the action basically just replaces the parent with the one we supply. (Yes, you read me right. You can basically modify any node via this action...)

https://github.com/gatsbyjs/gatsby/blob/eed610813da645356316826a4558640ecc4365b5/packages/gatsby/src/redux/actions/public.js#L1026-L1039

https://github.com/gatsbyjs/gatsby/blob/334d2bc2d3a03c83882dbc55bdc168647903c9f9/packages/gatsby/src/datastore/lmdb/updates/nodes.ts#L13-L15

What we need from the child node, however, is just the `id` field. In this case, `NodeInput` suffices.
