### ISSUE TITLE
Override the hierarchy of sub directory templates

### ISSUE THREAD

**Issue by tleunen** [gatsbyjs/gatsby#200]
I have a usecase where I'd like to have a landing page with a layout structure different than the documentation or the example section... Therefore, having a way to decide for a template to decide if it should be set as a child of the parent template, or being its own "root" template would be nice.
Here's what Kyle suggests:

> So would I'd suggest is let templates export a static function which explicitly returns a parent template (or null if it should be a root template like in your case) that create-routes can use to override the algorithm.

I really like that idea to have the template specify who is its "parent" template.

**Comment by ivanoats** [comment]
Yes this would be really useful.

**Comment by drusellers** [comment]
Are there any documents on how templates work today?

**Comment by jbolda** [comment]
@drusellers The only documentation that I have seen is in [Structure of a Gatsby site](https://github.com/gatsbyjs/gatsby#structure-of-a-gatsby-site). Essentially each folder can have a _template, and the nested templates in nested folders all warp each other.

ie: Parent(Child(Grandchild())) when /pages/parent/child/grandchild/post.md

**Comment by KyleAMathews** [comment]
Yeah, "templates" are for structural elements of the site. Parts of the site that repeat across pages e.g. headers and footers. As @jbolda mentioned, you can have sub-templates as well which contain pages in the same directory and further down the file system hierarchy. The only public example of this that I know of is the documentation starter which has an additional `_template.jsx` file for the docs sidepage https://github.com/gatsbyjs/gatsby-starter-documentation/blob/master/pages/docs/_template.jsx

Gatsby uses react-router so if you're familiar with that, what's happening is Gatsby is setting up the nested component structure described in https://github.com/ReactTraining/react-router/blob/master/docs/Introduction.md

In 1.0, this will change significantly as while it'll still support an automatic global `_template` file (though changing name to `layout`, any sub-layouts will need to be specified programmatically (https://github.com/gatsbyjs/gatsby/issues/421)

**Comment by danielres** [comment]
so, as I understand, there is no way, in Gatsby 0.12, to use a different "top" template ?

To describe my case: 

I'd like to write my CV using Gatsby and React components, and have it served under `/cv/`.
I don't want to have the same layout as the rest of the site though, with the navigation and all.
I haven't found a way to make that happen, except playing with some conditionals in the current top `_template.js file` to hide the relevant parts. 

Any suggestions ? 
Or should I go that way and keep the better approach on the side for version 1.0 ?

**Comment by KyleAMathews** [comment]
@danielres yeah, conditionals is the best choice for 0.x. In 1.0 you'll be able to completely replace the top-level layout component on different routes.
