### ISSUE TITLE
Plugin option not queryable under certain circumstances

### ISSUE THREAD

**Issue by angeloashmore** [gatsbyjs/gatsby#20007]
## Description

I have a custom Gatsby theme that uses a plugin option called `defaultTemplate`. Only when the following criteria is met, the option is no longer queryable via GraphQL:

- The option value is "page".
- A function is provided as another plugin option.

As soon as `defaultTemplate` changes to another value, such as "foo", or no other plugin options are functions, `defaultTemplate` becomes queryable again.

```js
// defaultTemplate is no longer available if the above criteria are met.
const queryData = useStaticQuery(graphql`
  {
    sitePlugin(name: { eq: "my-custom-theme-name" }) {
      pluginOptions {
        otherPluginOptions
        defaultTemplate
      }
    }
  }
`)
```

Console output when defaultTemplate is no longer available:

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "defaultTemplate" on type "SitePluginPluginOptions".

GraphQL request:8:11
7 |           accessToken
8 |           defaultTemplate
  |           ^
9 |         }
```

No GraphQL type conflicts are printed to the console output.

### Steps to reproduce

1. In Gatsby site, use a theme with a `defaultTemplate` plugin option and any another option with any function as its value.

   ```js
   {
     defaultTemplate: 'page',
     foo: () => 'bar',
   }
   ```

2. Query the node store via GraphQL with the following query:

   ```graphql
   sitePlugin(name: { eq: "my-custom-theme-name" }) {
     pluginOptions {
       defaultTemplate
     }
   }
   ```

### Expected result

`defaultTemplate` should be queryable even when its value is "page" and another plugin option value is a function.

(It is expected that the function is not available to query)

### Actual result

`defaultTemplate` is removed from the GraphQL schema when its value is "page" and another plugin option is a function.

### Environment

```
  System:
    OS: macOS Mojave 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 11.15.0 - /var/folders/ft/2phzc48d0d54xhq7rrsl_5kc0000gn/T/yarn--1575844230276-0.9015681377298961/node
    Yarn: 1.19.2 - /var/folders/ft/2phzc48d0d54xhq7rrsl_5kc0000gn/T/yarn--1575844230276-0.9015681377298961/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Safari: 12.0
  npmPackages:
    gatsby: ^2.18.7 => 2.18.7 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-compile-es6-packages: ^2.1.0 => 2.1.0 
    gatsby-plugin-local-search: ^1.0.0 => 1.0.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-remark-images: ^3.1.35 => 3.1.35 
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7 
  npmGlobalPackages:
    gatsby: 2.18.7
```

**Comment by LekoArts** [comment]
Hey, thanks for the issue!

Can you please use https://www.gatsbyjs.org/packages/gatsby-plugin-schema-snapshot/ and post the inferred schema for both cases? Thanks!

**Comment by vladar** [comment]
Thanks for the detailed explanation but I still can't reproduce it locally. Can you provide a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that we could continue investigating this?
