### ISSUE TITLE
Command failed with exit code 128: git clone

### ISSUE THREAD

**Issue by wispyco** [gatsbyjs/gatsby#20003]
## Description

I am developing under WSL for windows, in a hyper.is terminal. Gatsby cli installs fine however a gatsby new site command returns the following error 
```
Error: Command failed with exit code 128: git clone https://github.com/gatsbyjs/ga  tsby-starter-default.git example --single-branch
```

### Steps to reproduce

Install WSL for Windows in powershell as an adminstrator
```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```
Install Ubuntu, Launch Ubuntu, Change hyper shell to base.exe

Open Hyper.is terminal insall nvm
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
```
install stable node version
```
nvm install stable
```
install gatsy cli
```
npm install -g gatsby-cli
```

Create a new Gatsby site
```
gatsby new gatsby-site
```

### Expected result

Created new gatsby site in current directory.

### Actual result

Received following error

```
  Error: Command failed with exit code 128: git clone https://github.com/gatsbyjs/ga  tsby-starter-default.git example --single-branch

  - error.js:56 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:114:26

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
```

### Environment

  System:
    OS: Linux 4.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64         Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
  npmGlobalPackages:
    gatsby-cli: 2.8.16

**Comment by LekoArts** [comment]
I'm personally using WSL and didn't encounter any problems. Please make sure that you followed the instructions and e.g. installed build-essentials: https://www.gatsbyjs.org/docs/gatsby-on-linux/#windows-subsystem-linux-wsl

**Comment by wispyco** [comment]
Yes that worked I had not done the build essentials part. I for some reason did not have to do this on my other machine, but that was the correct solution for me.
