### ISSUE TITLE
List the individual properties of the Gatsby Image GraphQL query fragments in docs.

### ISSUE THREAD

**Issue by chocobuckle** [gatsbyjs/gatsby#20005]
## Summary

In [the docs for Gatsby Image](https://www.gatsbyjs.org/packages/gatsby-image/#fragments), have a dropdown list display the individual properties of the GraphQL query fragments, so that they can be easily referenced and copied/pasted when writing queries in gatsby-node.js, which doesn't support the use of query fragments.

### Basic example
Clicking on 'GatsbyImageSharpFluid_withWebp_tracedSVG' would display the following beneath it:

```
                        src
                        srcSet
                        srcWebp
                        srcSetWebp
                        sizes
                        aspectRatio
                        tracedSVG
```

### Motivation
I, and I'm sure many others, find it difficult remembering which properties to include when writing Gatbsy Image queries in gatsby-node.js. Depending on the requirements, it's sometimes hard remembering which parts of the query should be included and which ones can be left out. Having a single source to reference, and then copy/paste from, would be very useful and clear up any confusion.

**Comment by LekoArts** [comment]
Hey, thanks for the issue!

I kinda disagree with your reasoning: We don't want to encourage people querying everything in gatsby-node.js. People should do page queries and use the fragments.

However, displaying them from the source code could be valuable for other cases.

**Comment by chocobuckle** [comment]
@LekoArts Oh I agree that image querying/processing should be kept to page/static queries as much as possible, but I recently had a use case that meant I had to do some image processing in gatsby-node.js first and then pass that data in via pageContext to various different templates. Doing it that way just made more sense than querying multiple times in different pages or setting up some static query higher order component! ¯\_(ツ)_/¯

I'll close this issue, as it was more an edge case than a typical user scenario.
