### ISSUE TITLE
How to save buttons state in URL parameters?

### ISSUE THREAD

**Issue by markvital** [gatsbyjs/gatsby#20018]
I would like to implement filter and sort buttons in my Gatsby theme, so when the user click these button URL of the page change to something like this:

```
example.org/?sort=asc  &sortBy=name
example.org/?filter=all
example.org/?filter=none&&sort=desc

```

![sort-button](https://user-images.githubusercontent.com/742796/70455495-b44f1480-1aac-11ea-932a-a1a1d5172edd.png)
 
I also want page with URL `example.org/?filter=all ` to be indexed in Google (but not the one with sorting parameters)

How to do this in Gatsby the proper way?

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll need to look at using a `querystring`. Google warrants results like:
https://medium.com/@chrisfitkin/how-to-get-query-string-parameter-values-in-gatsby-f714161104f

We also do something like this with our plugin search:

https://github.com/gatsbyjs/gatsby/blob/1b44f333de0a8c8768f925f99f4834e07bcb5fa7/www/src/components/plugin-searchbar-body.js#L319-L327

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by markvital** [comment]
@LekoArts Thank you!
It would be great to have better support of URL query string parameters in Gatsby core.

Many parsing URL string in such a high level framework like Gatsby feels for me just not right.
Another inconvenience is that I can't use Gatsby <Link  /> component to navigate to those links with parameters (like /page1?p=1&p=2), have to use [Reach Router](https://github.com/reach/router) instead.
