### ISSUE TITLE
 Video does not work ‘gatsby-remark-video’

### ISSUE THREAD

**Issue by sk894703472** [gatsbyjs/gatsby#20029]
## Summary

I hope gatsby supports video, but after configuring it according to the documentation, the syntax does not take effect
https://www.gatsbyjs.org/packages/gatsby-remark-video/?=video

## Relevant information

According to the official documentation：`video: /static/shots-demo-369bfe714a6b8981ecfc743f7e7e7008.mp4`，
I use ss syntax, but it parses into code blocks, not video elements

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

Please reach out to the author of this plugin as we don't maintain it ourselves. Thanks!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
