### ISSUE TITLE
remove noscript "This app works best with JavaScript enabled." from gatsby

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#20021]
### Basic example
https://user-images.githubusercontent.com/3924690/50913894-07cb6500-13fb-11e9-8102-dc833a71f8a3.png

### Motivation
Currently, we show a banner "This app works best with JavaScript enabled." when javascript is disabled. This was necessary to keep Lighthouse happy when gatsby-plugin-offline was enabled. We fixed gatsby-plugin-offline to refresh when javascript was disabled + lighthouse checks if any content is available so we should be able the message.

The message can be found at https://github.com/gatsbyjs/gatsby/blob/07e4b1165317a3b5a795f79b683e5ddeeaa441d2/packages/gatsby/cache-dir/default-html.js#L18-L20

**Comment by gilbertoayala12** [comment]
Hi, can I work on this issue?
