### ISSUE TITLE
[docs][guides] new guide on working with HubSpot

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#20022]
## Summary

Based on commonly searched terms with no results on gatsbyjs.org, we'd like to add a Reference Guide on working with HubSpot in Gatsby. HubSpot is a CRM and marketing/sales platform used by many teams to reach new and existing customers, and Gatsby users are likely looking to integrate it with their site.

There was a recent post on this subject: https://chaseohlson.com/hubspot-forms-gatsby

While that post could be used as inspiration and be quoted/linked for further reading, a Gatsby reference guide needs to have new and original content. It should follow the [Gatsby Style Guide](https://www.gatsbyjs.org/contributing/gatsby-style-guide/) and can be based on the [Reference Guide docs template](https://www.gatsbyjs.org/contributing/docs-templates#reference-guide-template).

### Motivation

To help Gatsby learners understand their options when it comes to working with HubSpot! This would be a good thing to link from the [Winning Over Marketers](https://www.gatsbyjs.org/docs/winning-over-marketers/) guide as a workflow with precedent.

**Comment by brohlson** [comment]
@marcysutton Please feel free to use any part of my original post in the Gatsby guide.

**Comment by nik72619c** [comment]
shall I work on this one ?

**Comment by marcysutton** [comment]
Thanks so much @brohlson, that's very kind of you! We had something similar come up recently with the [security doc](https://github.com/gatsbyjs/gatsby/pull/19778), so that's why I wanted to make sure any contributions credited original authors.

@nik72619c that sounds great, it's definitely up for grabs!

**Comment by nik72619c** [comment]
cool, thanks !

**Comment by marcysutton** [comment]
Hi @nik72619c, checking up on this: are you still up for writing about Gatsby and HubSpot?

**Comment by nik72619c** [comment]
Yup,I would be sending a PR soon. I could not work due to some relocation issues :)

**Comment by nik72619c** [comment]
@marcysutton could you tell me where is this doc gonna be inserted in the Gatsby docs ?

**Comment by marcysutton** [comment]
Hey @nik72619c, sorry for the delay! This page could live under Adding App and Site Functionality, potentially as a new subpage under [Adding Forms](https://www.gatsbyjs.org/docs/adding-forms/).

**Comment by marcysutton** [comment]
Hey @nik72619c, are you still interested in writing about HubSpot? We would be pumped to read your contribution!
