### ISSUE TITLE
Relative Images Directory for yaml data

### ISSUE THREAD

**Issue by yudyananda** [gatsbyjs/gatsby#20027]
Useful Links:
  - Querying for multiple images from YAML data: https://www.gatsbyjs.org/tutorial/gatsby-image-tutorial/#querying-for-multiple-images-from-yaml-data
  - Image Optimization image https://github.com/gatsbyjs/gatsby/issues/8078
 

## Summary

I just tried Gatsby in a few weeks. Some plugins that I use are `gatsby-image` and `gatsby-transformer-yaml`

In this case I want to make a storage of the markdown and data of yaml and others in one directory (for example src / images), but it seems that [it cannot be done](https://github.com/gatsbyjs/gatsby/issues/8078) because the images that I include in the yaml data must be stored in the same where data stored.

### Motivation

I think this will be a problem if I use Headless cms which requires a centralized image directory. I really hope that images sourced from yaml can be stored outside the data directory, making it easier to integrate with headless cms such as foresty.io and netlify-cms

**Comment by LekoArts** [comment]
Thank you for opening this!

You can use the schema customization API and `@link` directive to enable these relative directories: https://www.gatsbyjs.org/docs/schema-customization/#foreign-key-fields

I've also created a similar codesandbox: https://codesandbox.io/s/json-images-link-tlegq

And this blogpost also explains it: https://www.byderek.com/post/a-stackoverflow-question--a-use-case-for-gatsbys-field-extension

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
