### ISSUE TITLE
How to get fluid image to change sources/sizes

### ISSUE THREAD

**Issue by jtheberge** [gatsbyjs/gatsby#20028]
## Summary
Whenever I make graphQL query :
```
import React from 'react';
import { useStaticQuery, graphql } from 'gatsby';
import Img from 'gatsby-image';

const data = useStaticQuery(graphql`
  query {
    placeholderImage: file(relativePath: { eq: "seniors.jpg" }) {
    childImageSharp {
      fluid(maxWidth: 500) {
        ...GatsbyImageSharpFluid_withWebp_noBase64
        presentationWidth
      }
    }
  }
}
...
const Image = () => <Img fluid={fluid} />;
export default Image;
```

The src's intrinsic size / actual downloaded image is always 1000px (twice the maxWidth), no matter if my viewport is mobile or desktop. I see that there are many different image sizes generated. How does the fluid image work to change the src attribute to bigger and smaller images?

### Environment (if relevant)

  npmPackages:
    gatsby: ^2.15.20 => 2.15.20
    gatsby-image: ^2.2.20 => 2.2.20
    gatsby-plugin-manifest: ^2.2.18 => 2.2.18
    gatsby-plugin-netlify: ^2.1.24 => 2.1.24
    gatsby-plugin-offline: ^3.0.19 => 3.0.19
    gatsby-plugin-react-helmet: ^3.1.8 => 3.1.8
    gatsby-plugin-sass: ^2.1.15 => 2.1.15
    gatsby-plugin-sharp: ^2.2.25 => 2.2.25
    gatsby-source-filesystem: ^2.1.26 => 2.1.26
    gatsby-transformer-sharp: ^2.2.16 => 2.2.16
  npmGlobalPackages:
    gatsby-cli: 2.8.8

**Comment by LekoArts** [comment]
Thank you for opening this!

You can get more information (and further reading links) here: https://www.gatsbyjs.org/docs/using-gatsby-image/

You'll see a 1000px image generated as it is the image served to devices with "Retina" resolution (so 2x the size). You can also test this by setting the pixel density in Chrome Devtools.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
