### ISSUE TITLE
Gatsby Website not working at: https://www.gatsbyjs.org/docs/graphql-reference/

### ISSUE THREAD

**Issue by andrejarboe** [gatsbyjs/gatsby#20045]
## Summary
The gatsby website doesn't have the example code for a basic GrapgQLquery : 

https://www.gatsbyjs.org/docs/graphql-reference/

## Relevant information

Users on windows are having problems with queries. 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by mark-casias** [comment]
What browser are you using and are you getting any console errors that may help locate the issue?

**Comment by andrejarboe** [comment]
the new edge, chrome, and opera

**Comment by mark-casias** [comment]
Interesting.. when I go in Chrome, Firefox Developer and Safari, I see the below:
 
![image](https://user-images.githubusercontent.com/7987464/70577787-27b65c00-1b69-11ea-9d62-db87f2ce9d8f.png)

The samples are using an external service to display the widgets so I am wondering if you have a script blocker or can look at your console log to determine if there are any errors.

**Comment by andrejarboe** [comment]
i just cleared my cache and everything works except for that last example

**Comment by andrejarboe** [comment]
Now I am geting this for most of them:
![msedge_3AnLybTqDu](https://user-images.githubusercontent.com/17892981/70818315-5fa7e400-1da1-11ea-986c-5fbebf063a48.png)

I am on windows...

**Comment by andrejarboe** [comment]
it has the thinking cloud then it says:
"It looks like 711808k40x.sse.codesandbox.io closed the connection"

**Comment by LekoArts** [comment]
Thanks for the issue! It's an issue with codesandbox and they're aware of it. They'll try to fix it as quick as possible.
