### ISSUE TITLE
How to use react-app-polyfill in gatsby

### ISSUE THREAD

**Issue by y-sumanth** [gatsbyjs/gatsby#20047]
`react-app-polyfill` says to include the following lines in `src/index.js`
```
// These must be the first lines in src/index.js
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
```
How to use this in Gatsby? Do I have to include in every page?
Is there any other better way?

**Comment by LekoArts** [comment]
Thank you for opening this!

By default Gatsby already polyfills to a certain degree:
https://www.gatsbyjs.org/docs/browser-support/#polyfills

So you shouldn't need to use the mentioned package. If you need to do it nevertheless you'll want to place it inside gatsby-browser.js like shown here:
https://github.com/gatsbyjs/gatsby/issues/2177#issuecomment-382280801
or
https://github.com/gatsbyjs/gatsby/issues/2177#issuecomment-400976675

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
