### ISSUE TITLE
Add support for programmatically configuring HTTPS

### ISSUE THREAD

**Issue by langri-sha** [gatsbyjs/gatsby#20040]
## Summary

Provide a way to configure HTTPS options programmatically from the Gatsby configuration.

### Basic example

Providing here an example that follows webpack's [`devServer.https`](https://webpack.js.org/configuration/dev-server/#devserverhttps).

```
module.exports = {
  https: {
      key: fs.readFileSync('/path/to/server.key'),
      cert: fs.readFileSync('/path/to/server.crt'),
      ca: fs.readFileSync('/path/to/ca.pem')
  }
}
```

### Motivation

Looking at the currently available options, there doesn't some to be a way to configure how the HTTPS server is initialized by Gatsby other than providing CLI options.

In my monorepository I've added support for creating, signing and verifying X.509 certificates progammatically. Once the development server starts up, a short-lived server certificate is issued by a trusted CA.

I'm sure there might be some scenarios where developers would like to host servers for internal previews and would like to create/fetch certificates using some Node.js clients that would know how to authenticate themselves with provider/custom services for this.

**Comment by wardpeet** [comment]
@langri-sha, you should be able to use `--key-file ../relative/path/to/key.key --cert-file ../relative/path/to/cert.crt`, checkout https://www.gatsbyjs.org/docs/local-https/ for more info.

could you perhaps explain why you need https locally?

**Comment by rlamana** [comment]
@wardpeet, I don't know about @langri-sha's use case, but I think there is a general misconception that `development == local`. Nowadays more and more teams take development to the cloud where they can work with production-like environments during development. This means running inside containers, behind HTTPs configurations, etc.

**Comment by langri-sha** [comment]
@wardpeet I need to programmatically talk to an X.509 PKI API to issue the server certificate signed by a trusted authority.

Previously I have patched `http.createServer` when the configuration was loading with a handler that fetched these and started an HTTPS server, but that seems to have stopped working with migrating to TS. I'm going to take a look at what APIs are available to see if I can lease a certificate [before the server is created](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/develop.ts) and the SSL paths are read.

**Comment by langri-sha** [comment]
I was able to patch `https.createServer` this time with `--https --key-file=/dev/null --cert-file=/dev/null`. Did try to find a viable alternative during the bootstrapping phase to avoid patching or providing a platform-specific solution to avoid having Gatsby generate the credentials, but wasn't able to find anything that could lend a hand.

I'd like to help out with a PR if someone has a suggestion on what would be a suitable approach for asynchronously providing certificates. It seems like a good approach would be to extend the existing Gatsby Node API.
