### ISSUE TITLE
Is Gatsby right for us?

### ISSUE THREAD

**Issue by salientknight** [gatsbyjs/gatsby#20053]
Hi All, 

I am the Frontend Dev for a University and we are trying to figure out if Gatsby is right for us. I have been watching training videos specifically Jason Lengstorf's course on Frontend Masters. I'm left with a few questions and a generally question about if this is the right tool for my team. 
About our team: 

1. We are a team of two developers — our work is basically divided front & back 
2. We have been using React for about 14 months
3. We work with a headless Drupal environment and support over 200 content editors and authors.

Questions: 

1. How does Gatsby work with new and dynamic content? I get that it's precompiled, so how do we get new user content life? We may be looking at dozen's of pages added a day. Is this a deal breaker? 
2. I found 1 person is the IRC room. Is there a broad and supportive community? Is it still building?
3. With the cool image functionality, does that also work when the images are stored on a remote server and coming in through data? Or does it only work on local images? 
4. Can this be easily hosted on our site and environments? If so, where is the documentation for getting that working? 

Thank you in advance

 

 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@salientknight regarding your questions:
1- Without going into much detail, when you need to create pages dynamically with data coming from the cms, you can trigger a build, a [example](https://www.gatsbyjs.org/docs/sourcing-from-drupal/) for your particular case. Or use the recent released [Gatsby Cloud](https://www.gatsbyjs.org/blog/2019-11-14-announcing-gatsby-cloud/). If you're just populating with data that is constantly mutating, You could use something like [this](https://github.com/jlengstorf/gatsby-with-apollo) for instance.
2- The community is extremely responsive, the [discord](https://discordapp.com/invite/br9rbUE) server is up and running and you'll probably get a faster response there, but always welcome to create a issue and a member of the teams, or a contributor like myself can guide you with a solution.
3- Yes it does, for the majority of cms it does, i saw that you're using Drupal and if i'm mistaken it also allows the responsive images with `gatsby-image`, if not someone please correct on this.
4- For the hosting, i would like you to read up on documentation hosted [here](https://www.gatsbyjs.org/docs/deploying-and-hosting/)

The docs are a really good place to find information, the documentation is always growing and it covers pretty much every aspect of Gatsby, also in the repo a good [list of examples](https://github.com/gatsbyjs/gatsby/tree/master/examples) is present

**Comment by salientknight** [comment]
Thank you.
