### ISSUE TITLE
[docs] improvements to offline, PWA, and service worker guides 

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#20050]
## Description

While working on the workflow for users building apps with Gatsby (#18993) I encountered this last portion of docs that could use some fine-tuning. Since a lot of this information is located in different places like plugin READMEs, blog posts, and guides, it would make sense to consolidate it all in a little more streamlined of an approach in the guides that exist.

### Notes of possible improvements

Some notes that I have from that issue and that I saw reviewing those docs that could lead to some wins:

- transfer content from the ["Gatsby for Apps"](https://www.gatsbyjs.org/blog/2018-11-07-gatsby-for-apps/) post to guides which has content on PWA's including service workers and the app shell model that Gatsby follows
- link to `/packages/gatsby-plugin-offline` instead of npm in guides like [this one](https://www.gatsbyjs.org/docs/add-offline-support-with-a-service-worker/) to keep users on .org
- update the guides on service workers with more steps from the plugin README that describes newer configuration options
	- the current guide [says](https://www.gatsbyjs.org/docs/add-offline-support-with-a-service-worker/#using-a-custom-service-worker-in-gatsby) "You can add a custom service worker if your use case requires something that gatsby-plugin-offline doesn’t support.", though it looks like the offline plugin supports appending code to the service worker to extend it's functionality so distinguishing between adding a default service worker with the offline plugin, extending the default plugin, or just using your own service worker seems like it would help
- add information about pulling in app data quickly using service workers so you don't have to wait on the network (this would be awesome if it included an example of an app with a logged in user using a service worker) 

_this issue is to capture the last bits of improvements of the gatsby for apps workflow so we can close the meta issue that has been tracking that work_

**Comment by marcysutton** [comment]
I'm opening this up to the community; if anyone wants to work on it let us know!
