### ISSUE TITLE
[docs] How Redux works in GatsbyJS

### ISSUE THREAD

**Issue by bball07** [gatsbyjs/gatsby#20056]
## Summary

Doc explaining what Redux is and how it works in GatsbyJS.  Refer to the contributing docs for a reference guide template and the Gatsby Style Guide for writing conventions.

### Motivation

I was looking for documentation on Redux in the Gatsby docs and the only thing that I was able to find was a [stub](https://www.gatsbyjs.org/docs/data-storage-redux/) so I decided to add in more information on this topic.

**Comment by aisflat439** [comment]
I can write this up if you like. Please let me know.

**Comment by LekoArts** [comment]
This was fixed in https://github.com/gatsbyjs/gatsby/pull/20248
