### ISSUE TITLE
Data type passed down to context

### ISSUE THREAD

**Issue by CeoFred** [gatsbyjs/gatsby#20052]
When using the createaPage method, the object key , context passes down whatever value you set it to be to some graph query written in some specified component. I want to know if it's possible to pass an object and somehow still access each key in the graphql query.

**Comment by LekoArts** [comment]
Thank you for opening this!

It's currently not possible to use nested values for GraphQL variables. You'll need to use it one level deep.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
