### ISSUE TITLE
Markdown inline footnotes

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#20078]
## Summary

Is there a recommended way to get inline footnotes in markdown [the way Pandoc offers](https://pandoc.org/MANUAL.html#footnotes)?

> Inline footnotes are also allowed (though, unlike regular notes, they cannot contain multiple paragraphs). The syntax is as follows:
> ```md
> Here is an inline note.^[Inlines notes are easier to write, since
> you don't have to pick an identifier and move down to type the
> note.]
> ```

There doesn't yet seem to be a Remark or MDX plugin for this.

**Comment by LekoArts** [comment]
Thank you for opening this!

You can use `Something something[^or something?].` like shown here:
https://github.com/remarkjs/remark/blob/master/packages/remark-parse/readme.md#optionsfootnotes

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by janosh** [comment]
Sorry, I wasn't clear enough here. I'm referring to footnotes that are _displayed_ (not just written) inline when hovering/tapping the footnotes anchor, sort of like a tooltip/mouseover text.

I believe I misread the Pandoc docs, thinking that's what they were describing when in fact they only support footnotes that are written inline but still displayed at the end of the document. So maybe no markdown parser has implemented such a feature yet? Perhaps not surprising considering it would require a combination of HTML and CSS to implement mouseover text with possible cross-browser issues.

**Comment by tmm** [comment]
@janosh You could try https://github.com/goblindegook/littlefoot

**Comment by janosh** [comment]
@tmm Very cool project, thanks for the link!

**Comment by ltjds** [comment]
> @janosh You could try https://github.com/goblindegook/littlefoot

YES! This is awesome. Thank you!

_PS: For those of you using Hugo and Markdown content, I recommend using the [CDN Option](https://github.com/goblindegook/littlefoot#usage-from-a-cdn), and pasting the `<script>` elements at the bottom of the **footer** partial._
