### ISSUE TITLE
[gatsby-source-contentful] Allow for cached content whenever possible

### ISSUE THREAD

**Issue by doronnac** [gatsbyjs/gatsby#20072]
Hi, this is my first issue, I could not find duplicates but sorry in advance if it exists.
Also, thank you for a great plugin.

## Summary

Allow for something like `GATSBY_CONTENTFUL_OFFLINE=prefer` which always uses cached data (if exists) in development

### Motivation

I'm working on a project with a pretty large amount of contentful data.
Having contentful data completely synced all the time is not a priority for my use case, so I would like a way to (at least attempt to) manually opt out of contentful re-sync whenever I add a dependency, change a `gatsby-*.js` file, etc.

It will considerably speed development time for me. Hope this is possible.

Thanks.

**Comment by TylerBarnes** [comment]
Hey @doronnac , thanks for the feature request!
This would actually be a Gatsby core feature, not specific to the contentful plugin, and this is not currently possible.
Right now, the entire cache for all plugins is invalidated if `gatsby-*.js` files or dependencies are changed, regardless of wether it's needed or not.
Work is currently being done to selectively invalidate the cache of only the plugins that need it, see https://github.com/gatsbyjs/gatsby/pull/8379. 
Once that's merged though, it wont solve your problem. IMO we need a gatsby-node API for plugins to run logic to decide if their cache (or parts of their cache) should be invalidated.

**Comment by muescha** [comment]
@doronnac maybe then should help an external proxy/vcr for your test setup?

something like the "famous" VCR ruby gem i found (but not tested): 
- [node-vcr](https://github.com/mbaertschi/node-vcr) (based on [flickr/yakbak](https://github.com/flickr/yakbak) & [talkback](https://github.com/ijpiantanida/talkback))

**Comment by doronnac** [comment]
Hmm looks interesting, but I see how it'll help with the slow startup time when cache is invalidated during `gatsby develop`

**Comment by muescha** [comment]
i read you fetching always all data again from Contentful

with the tools you can speed up the api calls - it comes from your local cache and goes not over the internet to Contentful (after the second time of an api call)
