### ISSUE TITLE
[gatsby-remark-prismjs] root@localhost as default is particularly specific, implies elevated privilege

### ISSUE THREAD

**Issue by dskvr** [gatsbyjs/gatsby#20098]
## Summary
The default `user@host` is `root@localhost`, consider a more neutral default user, that doesn't suggest elevated privilege required for the respective bash snippet. In my default use cases, `root` as a default user had a ton of implications, and I cannot imagine I'm the only one. 

It seems to me that an implementer's need to impose the privileges of `root` on their snippet is a corner-case and not a common case. While this global can be changed, it feels it is more responsible for the default to be less "powerful" 

### Basic example

```javascript
defaults = {
    user: "user",
    host: "localhost"
}
```

Only defaults change.

### Motivation

- Support common-cases by default while still empowering implementer to address corner-cases
- Mitigate miscommunication of elevated privilege to audience.

**Comment by LekoArts** [comment]
Thank you for opening this!

We don't feel like needing to change this as the defaults are fine for a default use case. As you pointed out you can already change it if needed.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
