### ISSUE TITLE
[gatsby-remark-prismjs] Unclear how bash prompt decides on `$` or `#`

### ISSUE THREAD

**Issue by dskvr** [gatsbyjs/gatsby#20097]
## Description

The bash prompt functionality seems to randomly switch between `#` and `$` depending on it's mood. I can also identify no logic in the [source file](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/command-line.js) that would result in this behavior. 

I can infer that if the bash commands are only one line, the plugin uses `#` but if there's two lines back-to-back with commands, it uses `$`. 

I'm unaware of any convention, specification or standard that warrants this behavior, but I assume if it's there it's there for some reason. So in that case, consider educating me or including a short bit of documentation around this behavior. 

_Or maybe I'm the only one?_ 😟

### Steps to reproduce

To be honest, I don't know, that's kind of why I am here. Here's some snippets and screenshots of their render. 

````
```bash{outputLines: 3}{promptUser: false}{promptHost: false}
hw = "Hello World!"
echo $hw
Hello World!
```
````
(those `false` settings are me being optimistic about #20096) 

![Screen Shot 2019-12-12 at 12 03 55 PM](https://user-images.githubusercontent.com/299465/70707298-1fc8fa00-1cd8-11ea-905c-81fa6c938e97.png)

````
```bash{outputLines: 2-3}{promptUser: root}{promptHost: localhost}
echo "HELLO\r\nWORLD"
HELLO
WORLD
```
````

![Screen Shot 2019-12-12 at 12 03 51 PM](https://user-images.githubusercontent.com/299465/70707306-25264480-1cd8-11ea-8e86-c6b82bd44229.png)

### Expected result

I usually see  `#` and `$` being used interchangeably. I generally expect `$` and I rarely see `#` used anymore. 

### Actual result

`$` and `#` seem to be arbitrarily interchangeable, and cannot find relevant logic in source.  

### Environment

```
  System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.79
    Safari: 12.0
```

**Comment by LekoArts** [comment]
Thank you for opening this!

> The resulting prompt displays a # for the root user and $ for all other users

https://prismjs.com/plugins/command-line/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
