### ISSUE TITLE
[gatsby-remark-prismjs] Should have the ability to hide user@host for bash prompts

### ISSUE THREAD

**Issue by dskvr** [gatsbyjs/gatsby#20096]
## Summary

Add ability to hide `user@host` in `gatsby-remark-prismjs`. The ability to include `user@host` left of the shell is a gorgeous feature. It enables more creative use of bash prompts, for example differentiating between two users or user levels. However, as far as I can tell, the requirements for this functionality are a corner case, not a common-case. 

### Basic example
````
```bash{outputLines: 2-3}{showUserHost: false}
ll | lolcat
.
..
```
````

This would hide the user from the rendered codeblock. 

_IMO_ This should be disabled by default, but to avoid breaking present implementations, it should probably be enabled by default.

`global.showUserHost=true`  or `global.hideUserHost=false`

### Motivation
- Provide authors with more control
- Potentially a discussion around `user@host` and whether or not it is a common-case.

**Comment by LekoArts** [comment]
I'd propose using CSS to hide it on a one-off basis but we'd accept a PR to include this option.

**Comment by dskvr** [comment]
Thanks for your quick response @LekoArts 😄  

My intention for bringing up this topic is that as it is implemented, it violates an important principle of software engineering, **generality**. 

> The principle of generality is closely related to the principle of anticipation of change. It is important in designing software that is free from **unnatural restrictions and limitations.** One excellent example of an unnatural restriction or limitation is the use of two digit year numbers, which has led to the "year 2000" problem: software that will garble record keeping at the turn of the century. Although the two-digit limitation appeared reasonable at the time, good software frequently survives beyond its expected lifetime.

In the context of this request, it seems unnatural to impose the inclusion of of `user@host` when the common case for the majority of shell/bash code blocks looks something like this:
```bash
$ ll | lolcat
```

The inclusion of `user@host` is an awesome feature, and is elegantly implemented. As one of your target audiences, I am voicing that this feature as a default is counter-intuitive and forces implementation to workaround the feature, instead of the feature working with the implementation. The CSS solution as a "one off" may seem reasonable, except when you consider that this request comes from the perspective of thousands of pages of documentation that is supported by tens of developers. Thus, consistency is required. 

I'm going to publish a draft PR for this issue either today or tomorrow, should I tag you in it?
