### ISSUE TITLE
× Error: The result of this StaticQuery could not be fetched.

### ISSUE THREAD

**Issue by BotMasterza** [gatsbyjs/gatsby#20108]
## Description

useStaticQuery
/Users/smartnet/flodev/JCTA_MEM/1/.cache/gatsby-browser-entry.js:63
  60 | if (context[query] && context[query].data) {
  61 |   return context[query].data
  62 | } else {
> 63 |   throw new Error(
  64 |     `The result of this StaticQuery could not be fetched.\n\n` +
  65 |       `This is likely a bug in Gatsby and if refreshing the page does not fix it, ` +
  66 |       `please open an issue in https://github.com/gatsbyjs/gatsby/issues`

### Steps to reproduce

On gatsby develop command

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

Index.js should render

### Actual result
ERROR;
This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.79
    Firefox: 56.0
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.8 => 2.18.11
    gatsby-image: ^2.2.34 => 2.2.36
    gatsby-plugin-manifest: ^2.2.31 => 2.2.33
    gatsby-plugin-offline: ^3.0.27 => 3.0.29
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.18
    gatsby-plugin-sharp: ^2.3.5 => 2.3.7
    gatsby-source-filesystem: ^2.1.42 => 2.1.42
    gatsby-source-strapi: 0.0.10 => 0.0.10
    gatsby-transformer-sharp: ^2.3.7 => 2.3.9
  npmGlobalPackages:
    gatsby-cli: 2.8.18

**Comment by connorlindsey** [comment]
Can you include some more info on this? Can you provide the component and the StaticQuery you're trying to run?
