### ISSUE TITLE
Ethereum Classic chinese page doesn't load sometimes.

### ISSUE THREAD

**Issue by ProphetDaniel** [gatsbyjs/gatsby#2010]
More information can be found [here](https://stackoverflow.com/questions/46023659/chinese-url-loads-correctly-in-edge-but-not-other-browsers?noredirect=1#comment79006936_46023659).

**Comment by ProphetDaniel** [comment]
According to [Hugues M.](https://stackoverflow.com/users/6730571/hugues-m) there looks to be a bug with GatsbyJs. 

> _after the page has loaded_ React will wipe out the content and replace it with empty node

**Comment by KyleAMathews** [comment]
Hey — this still an issue? Closing out old issues — if you still have struggles please open a new issue!
