### ISSUE TITLE
Tutorial Part One: <Link> not working when hot reloading

### ISSUE THREAD

**Issue by hsribei** [gatsbyjs/gatsby#2011]
While following the tutorial (Part One) to the letter, I encountered this problem: 

* I add the `<Link>` element
* I save the file
* The link shows up on the page with hot reloading
* I click on the link
* The URL does get updated
* **But** *nothing happens to the page content.*

Doing a full page reload (Command-R) makes it work properly with JS navigation from then on.

Is there anything I'm doing wrong or that I could do to help debug this? Thanks!

**Comment by fk** [comment]
Please check #1966, sounds like the same issue.

**Comment by KyleAMathews** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/2110
