### ISSUE TITLE
Can I deploy gatsby project to node server?

### ISSUE THREAD

**Issue by ichenzhifan** [gatsbyjs/gatsby#20112]
## Summary
Currently, I run "gatsby build" command to generate static html files, and then deploy the static files to server. it looks good for single language, by now, the project would support multi-languages, I don't want to build different static html file for every language。 Can I deploy the gatsby project to Node and run as SSR?

 thanks a lot.

**Comment by LekoArts** [comment]
Thank you for opening this!

Gatsby can't be run in your described "SSR" mode. I'd recommend building your pages for every language anyways. If you don't want to do that you could render them client-only:
https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/#understanding-client-only-routes

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
