### ISSUE TITLE
gatsby telemetry module not exiting properly when disabled on netlify

### ISSUE THREAD

**Issue by mattbeck** [gatsbyjs/gatsby#20125]
## Description

We're getting intermittent warnings in our build logs on Netlify about Gatsby Telemetry not completing its process. We have `GATSBY_TELEMETRY_DISABLED=1` set, but the process still executes and doesn't always get killed properly.

![Screen Shot 2019-12-13 at 12 07 58 PM](https://user-images.githubusercontent.com/2372870/70829058-8c5bfb80-1da1-11ea-974c-b80a35bfff73.png)

### Steps to reproduce
set `GATSBY_TELEMETRY_DISABLED=1`
run production builds

### Expected result

Disabling the telemetry should exit the process started by the node module.

### Actual result

process hangs after build is otherwise complete.

### Environment

Netlify

**Comment by sidharthachatterjee** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/20170
