### ISSUE TITLE
Referencing local font files not working as expected

### ISSUE THREAD

**Issue by dougajmcdonald** [gatsbyjs/gatsby#2012]
I'm trying to understand how to correctly include local webfonts in my gatsby blog. I'm keeping an eye on https://github.com/KyleAMathews/typefaces and hope to use this eventually but in the meantime I'd like to include some webfonts I have local to my site.

I've put a `fonts` folder inside the `src` folder where my `ttf`, `woff`s etc live, and I have a `fonts.scss` file inside `layouts\sass` where I have referenced the fonts like this:

```
@font-face {
    font-family: 'League Spartan';
    src: url('/fonts/leaguespartan-bold.eot');
    src: url('/fonts/leaguespartan-bold.eot?#iefix') format('embedded-opentype'),
         url('/fonts/leaguespartan-bold.woff2') format('woff2'),
         url('/fonts/leaguespartan-bold.woff') format('woff'),
         url('/fonts/leaguespartan-bold.ttf') format('truetype'),
         url('/fonts/leaguespartan-bold.svg#league_spartanbold') format('svg');
    font-weight: bold;
    font-style: normal;
}
```

When I look at the http requests made either locally after `gatsby develop` or remotely post deployment I see that the font requests look like this `http://localhost:8000/fonts/leaguespartan-bold.woff` as per the stylesheet, but the fonts seem to be copied into `public\static` with a guid type thing on the back `leaguespartan-bold.3812d86f.woff2` for example. 

How should I reference to the font files in the right way? it seems using the absolute URLs in the sass probably isn't the way to go but I'm struggling to see any other options

**Comment by dougajmcdonald** [comment]
@KyleAMathews You can probably close this one if you want as I used https://github.com/KyleAMathews/typefaces/ to import the fonts in the end (thanks for that project!).

I suspect the solution to the problem above is to use the static folder correctly but the typefaces project is excellent and serves the same purpose for me.

**Comment by KyleAMathews** [comment]
👍
