### ISSUE TITLE
Rebuild Entire Site Locally, Like A Webhook but Locally 

### ISSUE THREAD

**Issue by ethaneisenhard** [gatsbyjs/gatsby#20129]
I would like to be able to trigger a rebuild of my entire gatsby site, like a webhook, when an event fires like a form completion. Is this possible? If so, could someone point me in the direction of how to accomplish this task?

This is not for prod. I understand how to do it for prod with webhooks. But I would like to be able to do it locally. 

This ticket does not apply because of my situation. https://github.com/gatsbyjs/gatsby/issues/17985

> Use Case: I have an endpoint I am pulling from locally, with each new post to the local endpoint, I would like to rebuild my site automatically to grab the new data, without manually doing it my self.

**Comment by LekoArts** [comment]
Thank you for opening this!

There is an [`ENABLE_GATSBY_REFRESH_ENDPOINT`](https://www.gatsbyjs.org/docs/environment-variables/#reserved-environment-variables) env var you could use but besides that we don't know of anyone who asked for your use case and hence we can't give you a definitive answer. Maybe you can get something working with `ngrok` like shown here: https://www.freecodecamp.org/news/testing-webhooks-while-using-vagrant-for-development-98b5f3bedb1d/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
