### ISSUE TITLE
gatsby-remark-prismjs optionally allow additional html entities to be escaped

### ISSUE THREAD

**Issue by patricksimonian** [gatsbyjs/gatsby#20128]
## Summary

Digging into the `gatsby-remark-prismjs` code highlights that the most common __HTML__ entities ( `<`, `>`, `"`, ```, etc) are escaped using the `lodash.escape` function. I have personally encountered the requirement to expand on the number of characters escaped to include curly braces (`{`). 

### Basic example

Allow another option in the plugin to allow for additional characters to be replaced by an encoded version. 
Immediately I foresee two ways to accomplish this:

1. The plugin stores a dictionary of all HTML entities and their encoded versions and the __plugin option__ allows the user to pass in a list of entities.

```js
{
   resolve: 'gatsby-remark-prismjs`
   options: {
      ...,
     escapeEntities: [ '}',  '{' ],
    },
}
```

2. The plugin allows a dictionary to be passed in so that the user is in control of how values get replaced.
```js
{
   resolve: 'gatsby-remark-prismjs`
   options: {
      ...,
     escapeEntities: {
          '{': '&#123;',
      }
    },
}
```

### Motivation

During the support of my application, I encountered a very hard to debug the issue. The static site Server I was using (Caddy Server) was evaluating __ansible handle bar code examples__ `{{ .. }}` as valid Caddy template variables. This was causing my server to crash.

To me, the most sensible solution allows for additional HTML entities to be escaped. 

I initially authored my own remark plugin to escape these entities...__which did work__ but unfortunately, it is not compatible with the `remark-prismjs` because it requires changing the `mdast node.type`

**Comment by patricksimonian** [comment]
I'm also happy to make a PR for these changes if the approach is acceptable

**Comment by LekoArts** [comment]
Option 2 seems like a good idea. Would appreciate a PR!
