### ISSUE TITLE
allImageSharp originalName regex not returning all images

### ISSUE THREAD

**Issue by iamstevedavis** [gatsbyjs/gatsby#20121]
## Description

This is very similar to this issue here that was closed without resolution: https://github.com/gatsbyjs/gatsby/issues/4843

I have a folder that has 4 images titled main_1.jpg, main_2.jpg, main_3.jpg and main_4.jpg. Using the following query, only three of the images are returned:

```
{
  allImageSharp(filter: {fluid: {originalName: {regex: "/^main.+/gm"}}}) {
    edges {
      node {
        id
        fluid {
          originalName
          originalImg
          src
          srcSet
        }
      }
    }
  }
}
```

### Steps to reproduce

1. Create a folder with 4 or more images
2. Use the above query with a regex that will match all images in the folder
3. Run the query against graphql 

### Expected result

All images return.

### Actual result

Only a subset of the images are returned.

![image](https://user-images.githubusercontent.com/5615792/70808203-2c5b5a00-1d8d-11ea-825b-392d62d77b27.png)

### Environment

  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.0.11 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 3.8.0 - /usr/bin/python
  Browsers:
    Firefox: 71.0

**Comment by LekoArts** [comment]
Thank you for opening this!

You can leave out the `gm` options and see it working:

![image](https://user-images.githubusercontent.com/16143594/70894784-fff24880-1fed-11ea-93b0-04e741b1e8fc.png)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
