### ISSUE TITLE
Gatsby Image and query data with src

### ISSUE THREAD

**Issue by nalewka0** [gatsbyjs/gatsby#20123]
Hi! I query data from prismic.io and in rich text sometimes I've got images. 

page query: 
`query MyQuery {
  prismicProduct {
    data {
      rich_text {
        html
      }
    }
  }
}
`

and response: ```{
  "data": {
    "prismicProduct": {
      "data": {
        "rich_text": {
          "html": "<p>example rich text. example rich text. Example rich text. </p>\n    <p class=\" block-img\">\n      <img src=\"https://wroomdev.s3.amazonaws.com/tutoblanktemplate%2F97109f41-140e-4dc9-a2c8-96fb10f14051_star.gif?auto=compress,format?auto=compress,format\" alt=\"\" copyright=\"\">\n    </p>\n  <p></p>\n    <p class=\" block-img\">\n      <img src=\"https://wroomdev.s3.amazonaws.com/tutoblanktemplate%2F97109f41-140e-4dc9-a2c8-96fb10f14051_star.gif?auto=compress,format\" alt=\"\" copyright=\"\">\n    </p>\n  "
        }
      }
    }
  }
}```

how to convert it by gatsby-image?

**Comment by connorlindsey** [comment]
I'm currently working on the same thing. Here are a few pages in the docs that could be helpful:

https://www.gatsbyjs.org/docs/gatsby-image/
https://www.gatsbyjs.org/docs/preprocessing-external-images/

I think the second page is the key. I haven't had the time to try it, but I will soon.

**Comment by nalewka0** [comment]
I found also this plugin:
https://github.com/mikegajda/gatsby-transformer-remote-image
but 

`    {
      resolve: `gatsby-plugin-remote-images`,
      options: {
        nodeType: 'prismicProduct',
        imagePath: 'localImage',
      },
    },`
it's doesn't work

**Comment by connorlindsey** [comment]
> I found also this plugin:
> https://github.com/mikegajda/gatsby-transformer-remote-image
> but
> 
> ` { resolve:`gatsby-plugin-remote-images`, options: { nodeType: 'prismicProduct', imagePath: 'localImage', }, },`
> it's doesn't work

Just checked that plugin and it only works for Markdown pages, so it wouldn't work with Prismic.

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll want to use Prismic's [Slices](https://user-guides.prismic.io/en/articles/383933-slices) feature. So one Slice would be your text, another slice would be your image.

![image](https://user-images.githubusercontent.com/16143594/70892934-64aba400-1fea-11ea-81b1-2f395dcbd0e8.png)

This way `gatsby-source-prismic` can download the images and you can use them with an image slice like in the starter of the [Prismic guide](https://www.gatsbyjs.org/docs/sourcing-from-prismic/): https://github.com/LekoArts/gatsby-starter-prismic/blob/80acf9e8f847bff09a096b43dae43dd4b0f75872/src/slices/Image.jsx

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by connorlindsey** [comment]
@LekoArts Hey, thanks for the link. Would the same thing work for `gatsby-source-prismic-graphql`? I've been using that as recommended by the Prismic team.

**Comment by LekoArts** [comment]
Never used it but it should work:
https://www.youtube.com/watch?v=N85Tw06e29Q
