### ISSUE TITLE
Netlify Functions to sendgrid on Gatsby Cloud (working on Netlify and local dev)

### ISSUE THREAD

**Issue by wispyco** [gatsbyjs/gatsby#20137]
###Repo

The full repo is located here 
https://github.com/wispyco/riel-design

## Description

I am using Netlify Lambda functions to send email with sendgrid through a contact form. This works just fine locally in development, and when it is built to Netlify. However in Gatsby cloud it does not work.

### Steps to reproduce

I push up to my github which should trigger a Gatsby cloud build, I double checked that my env variables were in Gatsby cloud. And I installed the neccesary npm packages `npm install -D http-proxy-middleware netlify-lambda npm-run-all` gatsby cloud log says the port is started at 9000, 
Here is my code for the sendmail lamda function

```
const sgMail = require('@sendgrid/mail');
require('dotenv').config();
const { SENDGRID_API_KEY, SENDGRID_TO_EMAIL } = process.env

exports.handler =  async (event, context, callback) => {

    const payload = JSON.parse(event.body)
    const { email, subject } = payload

    sgMail.setApiKey(SENDGRID_API_KEY)

    // const body = Object.keys(payload).map((k) => {
    //     return `${k}: ${payload[k]}`
    // }).join("<br><br>");

    console.log(payload);

    const msg = {
        //to: SENDGRID_TO_EMAIL,
        from: email,
        // subject: subject ? subject : 'Contact Form Submission',
        // html: body,
        template_id: 'd-29d0416f9a954880ab612f742f4e0c38',
        personalizations: [{
            subject: 'From Test App',
            to: { email: SENDGRID_TO_EMAIL, },
            dynamic_template_data: {
                subject: 'Testing Templates',
                name: payload.name,
                message: payload.message,
                package: payload.package,
            },
        }],
        
    };

    try{

        

       await sgMail.send(msg)
        
        return {
            statusCode: 200,
            body: "Message sent"
        }
    } catch(e){

        console.log(e.message);

        return {
            statusCode: 500,
            body: e.message
        }
    }
};
```

### Expected result

A 200 Response saying email sent in the console, and a email gets sent.

### Actual result

I get the following error in the console

```
Response
type: "basic"
url: "https://riel-design-2611766185.gtsb.io/.netlify/functions/sendmail"
redirected: false
status: 504
ok: false
statusText: "Gateway Timeout"
headers: Headers {}
body: (...)
bodyUsed: false
__proto__: Response
```
and this error in Gatsby cloud logs
`12:46:53 PM: error [HPM] Error occurred while trying to proxy request sendmail from riel-design-2611766185.gtsb.io to http://localhost:9000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors) See our docs page for more info on this error: https://gatsby.dev/issue-how-to`

### Environment

System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)     
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz 
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node 
    Yarn: 1.19.2 - /usr/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v13.2.0/bin/npm   
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  npmPackages:
    gatsby: ^2.15.30 => 2.18.7
    gatsby-image: ^2.2.24 => 2.2.34
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.16        
    gatsby-plugin-sass: ^2.1.17 => 2.1.24
    gatsby-plugin-styled-components: ^3.1.16 => 3.1.16
    gatsby-source-datocms: ^2.1.18 => 2.1.20
    gatsby-source-filesystem: ^2.1.29 => 2.1.40
    gatsby-transformer-remark: ^2.6.27 => 2.6.39
  npmGlobalPackages:
    gatsby-cli: 2.8.16

**Comment by LekoArts** [comment]
Thank you for opening this!

Please reach out to Gatsby Cloud's support at support@gatsbyjs.com - thanks!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
