### ISSUE TITLE
How to prevent 302 redirect with trailing slashes?

### ISSUE THREAD

**Issue by keithpacana** [gatsbyjs/gatsby#20139]
For some weird reason gatsby 302 redirects my pages such as "/about" to "/about/". I tried the "remove-trailing-slashes" plugin but for some weird reason it only removes the trailing slash from my website? Any ideas on this?

**Comment by JustFly1984** [comment]
I guess this is an issue with web server. We had the same issue with AWS Cloudfront/S3. it also swallows querystrings if you do not have / at the end of path and before querystring.

```
https://example.com/page?query=string // bad
```

```
https://example.com/page/?query=string // good!
```

PS: we do not have this issues at netlify

**Comment by keithpacana** [comment]
> @keithpacana
> I guess this is an issue with web server. We had the same issue with AWS Cloudfront/S3. it also swallows querystrings if you do not have / at the end of path and before querystring.
> 
> ```
> https://example.com/page?query=string // bad
> ```
> 
> ```
> https://example.com/page/?query=string // good!
> ```
> 
> PS: we do not have this issues at netlify

were you able to resolve this by any chance? or did you just switch to netlify?

**Comment by LekoArts** [comment]
Thank you for opening this!

As this seems unrelated to Gatsby I'll close this.

Feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by JustFly1984** [comment]
@keithpacana we have fixed the link in email so it contains "/" before "?" and also fixed cloudfront behavior caching queryString.

We can't use netlify for production, cos it DNS servers are blocked in Russia, and we need to serve traffic to Russia, however we using netlify for dev and staging deploys.

Suffering a lot with Cloudfront intricacies and would love to switch to Netlify, but for now I can't

**Comment by devth** [comment]
This issue seems to break Amplify authentication. It redirects and in the process drops the querystring that Amplify attaches when redirecting back from Cognito hosted auth.

**Comment by JustFly1984** [comment]
@devth I think you need to fail an issue in aws-amplify repository

**Comment by devth** [comment]
Can do, but I suspect it's actually a gatsby bug where querystring is being dropped? I might be wrong.

**Comment by JustFly1984** [comment]
@devth does your site hosts at AWS CloudFront?

**Comment by devth** [comment]
Yeah, it's on Amplify, which uses CloudFront.

**Comment by JustFly1984** [comment]
@devth so it is a double failure from aws side

**Comment by 10686142** [comment]
Did anybody figure out a solution? I am using cloudfront with S3
