### ISSUE TITLE
Can mackdown files customize click events?

### ISSUE THREAD

**Issue by Fdango** [gatsbyjs/gatsby#20140]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

Your question seems unrelated to Gatsby and you probably meant "Markdown" files? For general React questions I'd recommend visiting sites like StackOverflow or go on Reactiflux (Discord).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
