### ISSUE TITLE
Gatsby image hyphen bug with GraphQL

### ISSUE THREAD

**Issue by MatthewWilson24** [gatsbyjs/gatsby#20151]
## Description

I have been working on a project using Gatsby in conjunction with Netlify CMS and repeatedly ran into the GraphQL error 'Field "image" must not have a selection since type "String" has no subfields' when querying my page markdown files. It turned out that this occurred only when the name of the image's parent node contained a hyphen. This issue has previously been raised (https://github.com/gatsbyjs/gatsby/issues/14644) but was never resolved as it was closed by gatsbot.

### Steps to reproduce

A minimal reproduction is available here: https://github.com/MatthewWilson24/gatsby-hyphen-bug-reproduction.

In src/pages/index.md I have the following markdown page data:
```
---
templateKey: index-page
image-with-text:
  image: /img/test.jpg
  text: Subfield of hyphenated field
imageWithText:
  image: /img/test.jpg
  text: Subfield of camelcase field
---
```

Which is queried in src/templates/index-page.js as follows:
```
export const pageQuery = graphql`
  query IndexPageTemplate {
    markdownRemark(frontmatter: { templateKey: { eq: "index-page" } }) {
      frontmatter {
        image_with_text {
          image {
            childImageSharp {
              fluid {
                ...GatsbyImageSharpFluid
              }
            }
          }
          text
        }
        imageWithText {
          image {
            childImageSharp {
              fluid {
                ...GatsbyImageSharpFluid
              }
            }
          }
          text
        }
      }
    }
  }
```

### Expected result

Gatsby should convert both image file paths to file nodes and the queries should succeed.

### Actual result

The query for "imageWithText" succeeds but the query for "image_with_text" causes the GraphQL error 'Field "image" must not have a selection since type "String" has no subfields'.

### Environment
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.13.31 => 2.18.12
    gatsby-image: ^2.0.23 => 2.2.36
    gatsby-plugin-netlify: ^2.0.6 => 2.1.30
    gatsby-plugin-netlify-cms: ^4.1.6 => 4.1.33
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.1
    gatsby-plugin-react-helmet: ^3.0.4 => 3.1.18
    gatsby-plugin-sass: ^2.0.7 => 2.1.26
    gatsby-plugin-sharp: ^2.2.9 => 2.3.8
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.1.33
    gatsby-remark-images: ^3.1.6 => 3.1.38
    gatsby-remark-relative-images: ^0.2.1 => 0.2.3
    gatsby-source-filesystem: ^2.0.26 => 2.1.42
    gatsby-transformer-remark: ^2.6.9 => 2.6.42
    gatsby-transformer-sharp: ^2.1.9 => 2.3.9

**Comment by vladar** [comment]
Thanks for reporting! The fix should be published in the next version of gatsby (which will be `2.18.15`)
