### ISSUE TITLE
fluid images with srcSetBreakpoints: unnecessary images generated

### ISSUE THREAD

**Issue by schoeneu** [gatsbyjs/gatsby#20152]
## Summary

We are creating **fluid** images with gatsby-image/sharp with original images of dimension 1440x700. We configured `maxWidth: 800` and `maxHeight: 640`, and a single `srcSetBreakpoint: [800]`.

When gatsby runs, it creates an 800x640 image as requested, but also a 1440x1152 image. This does not make sense to me as it's larger than the requested `maxWidth`.

The comment in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js#L387 says that it's there to "to ensure the largest image possible is available for small images". I don't understand - if I specifically set `maxWidth`, why does gatsby create a larger one?

Thanks!

**Comment by ascorbic** [comment]
I agree that this is questionable behaviour, particularly if the user has specified breakpoints explicity. If the user wants the original image then they can easily get it, so it needn't be added automatically. Also, it doesn't just copy the image. If the query includes other formats such as WebP then it recompresses the full-res image too.

**Comment by schoeneu** [comment]
Thanks, that was my impression as well.
It's especially weird if I have very high-res source images but only need smaller ones for the pages (specified by breakpoints), because then I get all of the original large high-res images in the build result and the build result becomes much larger than needed.

**Comment by schoeneu** [comment]
I don't think this is stale. What would be a good way to progress with this?

It seems to me that the line that adds the original size could just be removed, but I can't decide what it would break...

**Comment by decimoseptimo** [comment]
Also lighthouse may throw `Properly size images` warnings. When the srcset includes an aditional breakpoint (with the original image size, at a larger size), that you're not inteded to publish.

This has been [ asked before.]

**Comment by ascorbic** [comment]
I'd be happy to look at a PR that changes this

**Comment by alimoosavi15** [comment]
If you only need one image size, you can use `resize` instead of `fluid`.
