### ISSUE TITLE
Navigating between programmatically created pages doesn't update data

### ISSUE THREAD

**Issue by max-dotdev** [gatsbyjs/gatsby#20161]
## Summary

We have a problem with programmatically generated pages displaying the wrong data if the user refreshes the page on any of the programmatically created pages and navigates to another. It then shows the data of the first page (the one that was refreshed). 

## Relevant information

We're creating an e-commerce store sourcing products from Shopify and Articles from Prismic and have created Product and Article template components which export a gatsby build query. The query seems to work fine. But if you refresh the page while on any of the products and navigate to another product page, it shows all the data from the first one. The same happens for article pages. To clarify, it works perfectly if you refresh on anything but a product page or article page (if you refresh on a product page the articles still work and vice versa).

It wasn't like that from the start, but I didn't notice it until quite far down the line. If I run the product/article query in `gatsby-node.js` it works as expected. 

I wish I knew how to duplicate this, but the only way I know is to clone our repo and unfortunately, it has to be kept private. 

For a demo of the issue, you can go to this link: https://quizzical-noyce-4f2028.netlify.com/product/max-burger/ and navigate to a different product. This is the old base of our project that still has the bug present in it. 

Is anyone aware of anything that could cause this? Specifically that the programmatically generated pages query data doesn't update, even though the `pageContext` does?

### Environment (if relevant)

System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.79
    Firefox: 69.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.17.7 => 2.17.7
  npmGlobalPackages:
    gatsby-cli: 2.8.3
    gatsby-source-prismic-graphql: 3.4.0-beta.2

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

> It wasn't like that from the start, but I didn't notice it until quite far down the line

Since you deployed to Netlify can you go through the previews it created and see at which commit this behavior started?

> If I run the product/article query in gatsby-node.js it works as expected.

What do you mean with that? :)

> I wish I knew how to duplicate this, but the only way I know is to clone our repo and unfortunately, it has to be kept private.

Since it only seems to happen on certain pages, can you recreate the setup with that? Sounds like you're using context in `createPage`. Or share your gatsby-node.js file or other relevant files?

**Comment by max-dotdev** [comment]
Hi @LekoArts, thanks for the reply.

> Since you deployed to Netlify can you go through the previews it created and see at which commit this behavior started?
Thanks for the suggestion, I didn't think of that. It might not lead to the answer though as it wasn't deployed to Netlify until quite far down the road of refactoring. Still worth having a look.

> > If I run the product/article query in gatsby-node.js it works as expected.

> What do you mean with that? :)
Following the Gatsby documentation for programmatic pages, I run a query for the unique identifier each page needs to fetch the relevant data. If I add the whole product/article query there and pass it down through `pageContext`, I'm able to generate the correct data regardless of where the user landed or refreshed. 

> > I wish I knew how to duplicate this, but the only way I know is to clone our repo and unfortunately, it has to be kept private.

> Since it only seems to happen on certain pages, can you recreate the setup with that? Sounds like you're using context in createPage. Or share your gatsby-node.js file or other relevant files?
I can't duplicate it, I have started other Gatsby builds later that build pages programmatically and they work fine. I've compared them carefully as well and can't see a difference.

I'll share `gatsby-node.js` and the `ProductPage.js` template, maybe I'm missing something.

```js
// gatsby-node.js

const wrapper = promise =>
  promise.then(result => {
    if (result.errors) {
      throw result.errors
    }
    return result
  })

exports.createPages = async ({ graphql, actions: { createPage } }) => {
  const create = (data, amp) => {
    createPage(data)

    if (amp)
      createPage({
        ...data,
        path: `${data.path}/amp`,
      })
  }

  const result = await wrapper(
    graphql(`
      {
        products: allShopifyProduct {
          edges {
            node {
              handle
            }
          }
        }
        articles: allPrismicArticle {
          edges {
            node {
              id
              uid
            }
          }
        }
      }
    `),
  )

  const templates = {
    products: require.resolve("./src/templates/Product/ProductPage.jsx"),
    articles: require.resolve("./src/templates/Article/ArticlePage.jsx"),
  }

  // products
  result.data.products.edges.forEach(({ node }) => {
    create(
      {
        path: `/product/${node.handle}`,
        component: templates.products,
        context: {
          handle: node.handle,
        },
      },
      true,
    )
  })

  // articles
  result.data.articles.edges.forEach(({ node }) => {
    create(
      {
        path: `${config.routes.ARTICLE}/${node.uid}`,
        component: templates.articles,
        context: {
          uid: node.uid,
        },
      },
      true,
    )
  })
}

exports.onCreateWebpackConfig = ({ actions, stage, getConfig }) => {
  if (stage === "build-javascript") {
    actions.setWebpackConfig({
      devtool: false,
    })
  }
}
```

```js
// ProductPage.js
import React from "react"
import { graphql } from "gatsby"

import Head from "../../components/Head"
import ProductForm from "../../components/Products/ProductForm/ProductForm"
import { Section, Container, Heading } from "../../components/Styled/Tailwind"

import ProductImages from "./ProductImages"
import ProductDescription from "./ProductDescription"

export const query = graphql`
  query ProductPageQuery($handle: String!) {
    shopifyProduct(handle: { eq: $handle }) {
      // Shopify product query 
    }
  }
`

const ProductPage = ({ data: { shopifyProduct: product }, pageContext }) => {
  console.log("pageContext", pageContext) // shows fresh data

  return (
    <div>
      <Head title={product.title} description={product.description} url={`/${product.handle}`} />
      <Section>
        <Container>
          <Heading>{product.title}</Heading>
          <ProductImages productTitle={product.title} images={product.images} />
          <ProductDescription descriptionHtml={product.descriptionHtml} />
          <ProductForm product={product} />
        </Container>
      </Section>
    </div>
  )
}

export default ProductPage
```

**Comment by max-dotdev** [comment]
@LekoArts thanks for the Netlify suggestion. It helped me narrow down when the issue was introduced and points to 3 commits pushed a little over a month ago that enabled Prismic previews. Looks like I need to take a look at that. For documentation purposes, I will update this issue when I have the solution.
