### ISSUE TITLE
Using gatsby-plugin-intl for multilingual markdown files?

### ISSUE THREAD

**Issue by zasuh** [gatsbyjs/gatsby#20166]
## Summary
I'm using the `gatsby-plugin-intl` package for internationalization on my site. Works great for strings and arrays, but what about markdown files? Is there some documentation that I am missing with this plugin? The demo site only uses regular strings for it's demonstration no markdown files.
https://www.gatsbyjs.org/packages/gatsby-plugin-intl/

**Comment by HenriqueOmena** [comment]
Plz some one help with that
