### ISSUE TITLE
[gatsby-plugin-preload-fonts] Add option to skip checking if fonts change - to use in CI

### ISSUE THREAD

**Issue by masives** [gatsbyjs/gatsby#20185]
## Summary

gatsby-plugin-preload-fonts requires user action if fonts are detected to be unchanged. This makes it impossible to use with any CI tool as it will hang the build. It would be useful to have an option to provide a flag/env variable that would skip this check or force it to be done again.

### Basic example

Currently for each page hash is created a
```js
const {GATSBY_PLUGIN_PRELOAD_FONTS_FORCE} = process.env

const shouldForceCrawl = GATSBY_PLUGIN_PRELOAD_FONTS_FORCE

const hash = crypto.createHash(`md5`)
  routes.forEach(r => hash.update(r))
  if (cache.hash === hash.digest(`hex`)) {
    const lastRun = formatRelative(new Date(cache.timestamp), new Date())
    const ok = shouldForceCrawl ? true : await logger.confirm(`

  ${blue(`note`)} routes have not changed from the last run; if you haven't
       added any new routes or font requirements since then, you
       should be good to go! would you like to crawl them anyways?

         - ${dim(`last run`)} ${bold(lastRun)}
         - ${dim(`route hash`)} ${bold(cache.hash)}

`)
    if (!ok) process.exit(0)
  }

```

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation

To enable using this plugin in CI

I can provide PR

**Comment by pieh** [comment]
We do have [`isCi`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-core-utils/README.md#isci) utility that could be used to automatically make some default decision as well. (so it just works with sane default and doesn't hang)

I honestly am not quite sure the why we even need to prompt user in the first place. @superhawk610 can you provide some context around this? This get's prompted when hash matches so instinctively I would say that not re-reunning should be default (unless there are subtle things that don't quite work, which I'm not aware of). I tried to look over discussion in https://github.com/gatsbyjs/gatsby/pull/14608 but I don't think this was ever target of discussion there

**Comment by masives** [comment]
@pieh I'm afraid this will not work as `gatsby-preload-fonts` script that uses puppeteer is ran outside of gatsby build. This happens before the build and then `gatsby-plugin-preload-fonts` uses it's result in the build process

**Comment by masives** [comment]
Could you please suggest if I should make this pull request or should we abandon this as unneeded feature?

**Comment by superhawk610** [comment]
Hey everyone, sorry for the delay in chiming in. Let me explain a bit about my reasoning for keeping this outside of CI, hopefully that will provide some clarity.

There are 3 situations where you need to run `gatsby-preload-fonts` to regenerate the font cache:

- after you have manually added new routes (usually by adding a new file in the `pages` directory)
- after you’ve added a new plugin that generates new routes (e.g. source plugins, etc)
- after you’ve added new fonts that require preloading to existing routes

Gatsby can automatically detect new routes (the first situation), which is what we use to check/update the cache hash. However, the 2nd and 3rd situation are too high-level to be automatically detected and thus must be manually enforced by the developer.

Detecting fonts that need to be preloaded can become quite time consuming for any project larger than a few routes, often taking 10-15 minutes or more (it has to crawl _every_ route in your site, dynamic and static). As such, I believe rerunning this script on every CI build will very often simply waste resources without any actual benefit.

That being said, I do think rerunning this script anytime the cache hash changes (whenever new routes can be detected by Gatsby) would be useful and wouldn’t needlessly waste resources. @masives if you’d like to open a PR to add a non-interactive mode for `gatsby-preload-fonts` in CI environments whenever the cache hash has changed, I believe that would be a useful addition.

@pieh does that help clear things up?

**Comment by masives** [comment]
@superhawk610 Thanks for the explanation, I'll draft a PR for this in this or next week.

**Comment by masives** [comment]
@pieh I've drafted PR https://github.com/gatsbyjs/gatsby/pull/21037
