### ISSUE TITLE
[gatsby-image] Fluid image has a blank accessibility element

### ISSUE THREAD

**Issue by dantman** [gatsbyjs/gatsby#20181]
## Description

When using the `gatsby-image` `<Img fluid={...} alt="..." />` in VoiceOver this results in a blank item where VoiceOver does not speak anything when you navigate into the item before the actual image item.

### Steps to reproduce

https://codesandbox.io/s/vigorous-hooks-dxm00?fontsize=14&hidenavigation=1&theme=dark

Just the starter template with some alt text. Try it in VoiceOver.

### Expected result

Using `<Img>` should result in only an image element showing up in VoiceOver.

### Actual result

A blank element is present before the image element.

### Extra notes

Adding `role="none"` or `role="presentation"` to the first image element with the small inline image gets rid of the issue.

**Comment by pieh** [comment]
/cc @madalynrose 

From my check seems like this happens on Safari. On chrome it doesn't happen (but it also behave very differently than Safari) - is this correct?
