### ISSUE TITLE
Upon site change, pages error on initial load until refresh, preventing JS from running

### ISSUE THREAD

**Issue by me4502** [gatsbyjs/gatsby#20180]
## Description

After a site change has occurred, Gatsby's `ProdLoader` component loader errors on page load. After a refresh this fixes itself, which leads me to believe this is `gatsby-plugin-offline`.

I stupidly didn't screenshot the error, however I remember the places it occurred. Inside the `ProdLoader` constructor, it occurred during `asyncRequires.components[chunkName]()` due to the function call occurring on something that isn't a function.

This does somewhat confuse me as the `chunkName` should not have changed, as no page templates were changed. Only the contents. This also leads me to think it could be a race condition somehow? Or for some reason the `asyncRequires.components` map hasn't yet been filled.

### Steps to reproduce

This is a fairly hard one to reliably reproduce (sorry), it seems to only happen sometimes, and only for some pages. I haven't been able to reliably reproduce it (hence why the error is from memory).

It's definitely plagued us for a while, and after a large change where we switched CMS's it affected a lot of pages.

It seems to occur sometimes when a release has gone out, and the user has an outdated cached copy of the page.

### Expected result

The site should load fine despite a change having occurred.

### Actual result

An error occurs, preventing any JS from running.

### Environment

```
  System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
    Yarn: 1.19.0 - ~/.nvm/versions/node/v12.11.1/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.11.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.79
    Firefox: 70.0.1
    Safari: 13.0.3
```

**Comment by me4502** [comment]
Not stale

**Comment by danabrit** [comment]
@me4502 Sorry for this going so long without any response from us. It must have just gotten lost in the holiday break then never re-surfaced.

Is this still an issue? To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by me4502** [comment]
Hey, sorry yeah we ended up removing `gatsby-plugin-offline` to work around this.

I've been able to reproduce it on basically everything though, even a site that's basically a re-skinned `gatsby-starter-default` was having the issue, so I've removed `gatsby-plugin-offline` from all of my sites.

Due to this I'm unsure whether it's still a problem.

**Comment by danabrit** [comment]
@me4502 Thank you for your prompt reply! I'm glad you have a workaround. If you run into this again and would like to attach a minimal reproduction, we'd be happy to take a look. Thanks! 💜
