### ISSUE TITLE
Safari is not working whit Gatsby Link

### ISSUE THREAD

**Issue by cesarchavezcal** [gatsbyjs/gatsby#20195]
## Description
Gatsby Link doesn't change the page when you click/tap on Safari for macOS/iOS, the page appears like charging but doesn't load the redirected page.

### Steps to reproduce
This is the project where I'm having the problem: [http://valoremoseltrabajoartesanal.com/](Valoremos Arte).

1. Click on "Disfruta los documentales".
![image](https://user-images.githubusercontent.com/6935723/71101882-124ebc80-217d-11ea-86bc-b9d604298a98.png)

2. On the next screen click this button, It will display a section with some images in which each one is a link.
![image](https://user-images.githubusercontent.com/6935723/71104203-1086f800-2181-11ea-8bdd-26c7d4756bd3.png)
![image](https://user-images.githubusercontent.com/6935723/71104403-56dc5700-2181-11ea-80d7-9babe356992f.png)
3. Select one item and there is the problem, the page doesn't load the next page.
![image](https://user-images.githubusercontent.com/6935723/71104499-7ffce780-2181-11ea-828f-59ffdee20dfc.png)

**If you reproduce the steps in Chrome/Firefox, there is no problem**

### Expected result

**Move to the selected page**, Chrome and Firefox have the expected behavior but Safari on macOS/iOS doesn't have the expected result.

### Actual result

It doesn't move to the next page and sometimes the page freeze when its loading making Safari stop working.

### Environment
package.json
`{ 
   "name":"valoremos-arte-cms",
   "private":true,
   "description":"A starter for a blog powered by Gatsby and Markdown",
   "version":"0.1.0",
   "author":"Cesar Chávez <cesarchavezcal@gmail.com>",
   "dependencies":{ 
      "eslint-plugin-react":"^7.16.0",
      "gatsby":"^2.18.13",
      "gatsby-cli":"^2.8.19",
      "gatsby-image":"^2.2.10",
      "gatsby-plugin-manifest":"^2.2.6",
      "gatsby-plugin-netlify-cms":"^4.1.11",
      "gatsby-plugin-offline":"^2.2.7",
      "gatsby-plugin-react-helmet":"^3.1.4",
      "gatsby-plugin-sharp":"^2.2.13",
      "gatsby-remark-relative-images":"^0.2.3",
      "gatsby-source-filesystem":"^2.1.18",
      "gatsby-transformer-remark":"^2.6.19",
      "gatsby-transformer-sharp":"^2.2.7",
      "gatsby-transformer-yaml":"^2.2.7",
      "netlify-cms-app":"^2.9.7",
      "prop-types":"^15.7.2",
      "react":"^16.9.0",
      "react-device-detect":"^1.11.14",
      "react-dom":"^16.9.0",
      "react-feather":"^2.0.3",
      "react-flexbox-grid":"^2.1.2",
      "react-helmet":"^5.2.1",
      "react-player":"^1.14.2",
      "react-slick":"^0.25.2",
      "screenfull":"^5.0.0",
      "styled-components":"^4.3.2"
   },
   "devDependencies":{ 
      "prettier":"^1.18.2"
   },
   "homepage":"https://github.com/gatsbyjs/gatsby-starter-blog#readme",
   "keywords":[ 
      "gatsby"
   ],
   "license":"MIT",
   "main":"n/a",
   "repository":{ 
      "type":"git",
      "url":"git+https://github.com/gatsbyjs/gatsby-starter-blog.git"
   },
   "scripts":{ 
      "build":"gatsby build",
      "develop":"gatsby develop",
      "format":"prettier --write \"**/*.{js,jsx,json,md}\"",
      "start":"npm run develop",
      "serve":"gatsby serve",
      "test":"echo \"Write tests! -> https://gatsby.dev/unit-testing\""
   }
}`

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by pieh** [comment]
I couldn't reproduce the problem on:
 - macOS (10.14.5) and Safari (12.1.1) (that's my local env)
 - macOS (10.15) and Safari (13.0.2) (that's with browserstack)

Could you share what versions you are running?

**Comment by cesarchavezcal** [comment]
I'm sorry, I did not update the status but the page is working, I don't know what happened but is not a problem anymore. Thanks!
