### ISSUE TITLE
graphiql doesn't make use of `variables` search param

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#20192]
Editing "Query Variables" in graphiql:

![Screenshot 2019-12-18 at 16 49 14](https://user-images.githubusercontent.com/419821/71101104-6d50d580-21b6-11ea-84eb-dd92555a23b1.png)

Updates the `variables` search param (for example https://711808k40x.sse.codesandbox.io/___graphql?variables=%7B%0A%20%20%22variablesFromParam%22%3Atrue%0A%7D ), but loading this url, doesn't make use of passed variables and uses values stored in localStorage

We are missing `variables` prop in https://github.com/gatsbyjs/gatsby/blob/69ecf6a534b2be20e3b1ffe0b694ea677b68bb66/packages/gatsby-graphiql-explorer/src/app/app.js#L322-L330

Per `graphiql` documentation ( https://www.npmjs.com/package/graphiql ):

> `variables`: an optional GraphQL string to use as the initial displayed query variables, if undefined is provided, the stored variables will be used.

### Work to be done

Check how we set initial query: https://github.com/gatsbyjs/gatsby/blob/69ecf6a534b2be20e3b1ffe0b694ea677b68bb66/packages/gatsby-graphiql-explorer/src/app/app.js#L83-L91 and implement analogous logic for `variables`, and use that to pass `variables` prop to `Graphiql` element

**Comment by peaonunes** [comment]
Hello, @pieh. I would enjoy working on this if its possible. I need some help to get this running though. I've forked and setup the gatsby locally, but I was unable to run this specific package and see changes being updated. I tried building the package using the `scripts` in `package.json` and hosting them locally in a HTTP server, but I have ran into erros. How would be the ideal way to get it running?

**Comment by abrahamcuenca** [comment]
Hi Peaonunes, silly question but did you set up everything according to the document here: https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/ ?

**Comment by dvrylc** [comment]
I have a version of this working, just wanted to check if @peaonunes is still working on it? 

Also @pieh, seems like there's a key `graphiql:variables` in localStorage, do you know where that's set and/or used?

**Comment by pieh** [comment]
That localstorage key is used internally by graphiql package - that's how graphiql stores and restores variables when you refresh. We want to first use params from url, if those are not set, use localstorage and if that is not set use empty object or nothing
