### ISSUE TITLE
[docs][guides] New Reference Guide on working with Stripe

### ISSUE THREAD

**Issue by AishaBlake** [gatsbyjs/gatsby#20199]
## Summary

As part of the ongoing effort to improve on the top 25 learning workflows identified in #13708, we'd like to add a Reference Guide on working with Stripe in Gatsby. This will be one of several guides added as part of the [e-commerce workflow](https://github.com/gatsbyjs/gatsby/issues/19768).

Some recommended topics to cover:

- setting up your Stripe account
- Stripe Elements vs. Stripe Checkout
- existing plugins and starters using Stripe (like [gatsby-plugin-stripe](https://www.gatsbyjs.org/packages/gatsby-plugin-stripe/?=stripe))
- recurring payments & auth

### Motivation

The ability to build e-commerce sites with Gatsby gives developers (and business owners) a lot of flexibility. We'd like to provide a starting point for folks using some of the most popular e-commerce tools.

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a guide to imitate](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-site-with-authentication.md)
  - [Example of a similar article](https://www.gatsbyjs.org/docs/building-an-ecommerce-site-with-shopify/)
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the "Building an E-commerce Site" section.

### Open a pull request
- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by connorlindsey** [comment]
I just finished a project using gatsby checkout for one-time payments and elements for creating subscriptions with Stripe billing. I’d love to get involved and will start working on this. If anyone else wants to help, let me know.

**Comment by AishaBlake** [comment]
That sounds great, @connorlindsey! Thanks! Please note that the team will mostly be on [vacation through the end of the year](https://github.com/gatsbyjs/gatsby/issues/20247), so responses will be delayed.
