### ISSUE TITLE
Automatically inject css for a md page

### ISSUE THREAD

**Issue by tleunen** [gatsbyjs/gatsby#202]
Sometimes, a markdown page requires specific css that we might not want to initially load. It would be great if gatsby could automatically load the css based on the filename.

For example, it could be this syntax:
`pages/sub/doc.md` --> load `pages/sub/doc.css`
`pages/sub/doc/index.md` --> load `pages/sub/doc/styles.css`

What do you think?
This is not required for js pages because we can import the css inside the js.

**Comment by KyleAMathews** [comment]
Very interesting. It'd also need to support `styles.(sass|scss|less|*)` for each preprocessor out there.

Has anyone else out there wanted something like this? Is there other static site generators that have a similar pattern?

**Comment by ColeTownsend** [comment]
@KyleAMathews it's doable with yaml in jekyll, it's nice for custom pages.
