### ISSUE TITLE
Query nodes built by transfomers based on gatsby-source-filesystem sourceInstanceName

### ISSUE THREAD

**Issue by djhi** [gatsbyjs/gatsby#2020]
Hi!

We use `gatsby-transformer-remark` and `gatsby-transformer-sharp` alongside the `gatsby-source-filesystem` plugin.

We currently filter the `allMarkdownRemark` query with a regex on the `fileAbsolutePath` property (as also explained in #1634). However, this workaround does not apply to the `gatsby-transformer-sharp` plugin.

Wouldn't it be nice to always have the `sourceInstanceName` property in the filter ? As far as I understand gatsby, this should always be available for any source plugin ?

**Comment by KyleAMathews** [comment]
In retrospect it was a mistake adding that field to gatsby-transformer-remark and will be removed in the future as the transformer shouldn't know or care what the source of the markdown is.

What you want to do instead is just query allFile filtering on the source and then select childImageSharp, etc.
