### ISSUE TITLE
Images quality issue while using gatsby-image plugin

### ISSUE THREAD

**Issue by rohitkothiya** [gatsbyjs/gatsby#20215]
## Description

 I am getting quality issue in image while using gatsby-images plugins

In below images you can see that quality different in both images.

without gatsby-image : https://drive.google.com/file/d/1Y0lg2jUyuVfitOrYw-MRKPi82u3R9DLi/view?usp=sharing

using gatsby-image :
 https://drive.google.com/file/d/1BkfagziS7jOVU_st-RGowZ4eg9YxyTsQ/view?usp=sharing
query : 
     const data = useStaticQuery(graphql`
      query GrowSpotlightBannerQuery {
           spotlightImage: file(relativePath: { eq: "spotlight-1a.jpg" }) {
          childImageSharp {
          fluid(quality: 100) {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
    }
  `)

 image component :   <Img fluid={data.spotlightImage.childImageSharp.fluid}   />

**Comment by ephemer** [comment]
We're having the same issue here, would be great if you could re-open this so we can investigate further
