### ISSUE TITLE
'gatsby develop' is missing dependencies after yarn install.

### ISSUE THREAD

**Issue by MattHam98** [gatsbyjs/gatsby#20216]
## Description
'gatsby develop' reports a missing dependency issue after installing (with yarn) a starter project as per docs.

After installing with NPM 'gatsby develop' works fine.

The issue seems to be related to the **optionalDependencies**.  Perhaps they are handled differently by Yarn and NPM.

If I manually install ink and ink-spinner (using Yarn) then run 'gatsby develop' it works.

### Steps to reproduce

simple install of any starter project using both NPM and Yarn package managers.

### Expected result

It should launch the site on localhost:8000

### Actual result

Installing with Yarn (v19.2) succeeds but when I run 'gatsby develop' I get... 
> Error: Cannot find module 'ink'.

### Environment

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31 
    gatsby-plugin-offline: ^3.0.27 => 3.0.27 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16 
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5 
    gatsby-source-filesystem: ^2.1.40 => 2.1.40 
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7

**Comment by TylerBarnes** [comment]
Hi @MattHam98 !

I tried this out just now using the same version of yarn and node as you and wasn't able to reproduce with the hello world starter. Which starter are you seeing this issue in?

**Comment by MattHam98** [comment]
Yeah, it did seem odd that no one else had reported the issue.

I simply run 'gatsby new gatsby-site' so the default starter is used.  There must be something odd about my yarn install or config.

UPDATE: Just checked my yarn config and 'ignoreOptional:true' is set for some reason. 
I changed it to  'ignoreOptional:false' and tried again and it worked.  

I have no idea how it was set to true or indeed if this is the default setting for Yarn.

Thanks for your help. I think this can now be closed.

**Comment by MattHam98** [comment]
I should also say that changing the config and rerunning 'yarn install' did not work.  Yarn simply reported that all packages were up to date.  I had to do a clean install 'gatsby new yarn-test-site'

**Comment by wardpeet** [comment]
Could it be that you have a yarnrc file something that has a rule to not install optional dependencies? When ink cannot be found it should use another cli tool.

Let me give this a spin.

**Comment by MattHam98** [comment]
Reopening because I still think there is an issue. gatsby-cli (installed in the node_modules folder of the project rather than the global one) seems to have a hard dependency on 'ink' for logging but it listed as an optional dependency in the package.json.  

I'm not sure if the default behaviour of NPM and Yarn is different for optional dependencies or if I have changed some config in the past to make them behave differently.

I can say that when I use NPM, ink and ink-spinner are in the node_modules directory and when I use yarn, they are not.

I'm reverting my Yarn config to 'ignoreOptional:true' which seems to me to be the correct behaviour and working around this issue by manually installing ink and ink-spinner again.

**Comment by MattHam98** [comment]
Hi @wardpeet.  Nope, no yarnrc.

**Comment by wardpeet** [comment]
but you had `ignoreOptional:true`?

**Comment by MattHam98** [comment]
I did initially.  I then set it to false to see if that resolved the issue (which it did).

**Comment by MattHam98** [comment]
@wardpeet, does 'yarn config list' show ignore-optional as true or false for you?  Just curious.

**Comment by wardpeet** [comment]
it shows false :) When typing `yarn config list --verbose` it shows what config files it tries to load

**Comment by wardpeet** [comment]
@MattHam98 what version of gatsby-cli are you running? `gatsby --version`. I tried installing a starter with `yarn --ignore-optional` and `gatsby develop` worked. It fallbacks to a different reporter.

**Comment by MattHam98** [comment]
Gatsby CLI version: 2.8.19

**Comment by MattHam98** [comment]
Stranger and stranger.  I'm happy to close the issue since it seems to be something weird in my setup but I just can't see what.
