### ISSUE TITLE
Improve Creators Showcase

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#20211]
## Summary

Collect ideas how to improve the creators showcase.

### Motivation

The creators showcase was removed #19362 and then it comes back #19362. but maybe it is possible to improve the creators showcase and address some concern about the current list.

### related Issues

#19362 Remove Creator Showcase from gatsbyjs.org
#20198 Revert "Remove creator showcase"

**Comment by muescha** [comment]
for me the creators list was looking very outdated (not current active users was there) 

maybe creators should confirm regulary that they provide this service?

- pro
fresh confirmed content
- contra
overhead because of confirm system


workaround:
- make a `valid until date` field for 6Month / 1year and then creators should update their record to be listet in the showcase

**Comment by muescha** [comment]
### Small List

#### concern 

it was a very small list there. only a small representation.

#### Ideas

- inform every submission to the Site Showcase to add to creators showcase
- populate the `Creators Showcase` from data of the `Site Showcase` and maybe `Starters/Themes` -> the list is larger


#### Pro/Contra

- Pro
more creators in the list with examples

- Contra 
list gets too long from the showcase
maybe some users from site showcase don't provide services


#### Workarounds

- add a field to site showcase file `open for projects` or similar

**Comment by sidharthachatterjee** [comment]
Thanks @muescha 

We _do_ plan on revamping the Creators showcase in the future but this isn't on the roadmap for the near future so I suppose it's best to close this and revisit once we have the bandwidth for this. 

Thanks once again and cheers!
