### ISSUE TITLE
[docs][guides] New Reference Guide on working with WooCommerce

### ISSUE THREAD

**Issue by AishaBlake** [gatsbyjs/gatsby#20222]
## Summary

As part of the ongoing effort to improve on the top 25 learning workflows identified in #13708, we'd like to add a Reference Guide on working with WooCommerce in Gatsby. This will be one of several guides added as part of the [e-commerce workflow](https://github.com/gatsbyjs/gatsby/issues/19768).

Some recommended topics to cover:

- note on headless WordPress
- any overlap with [gatsby-source-wordpress](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/)
- [existing plugins](https://www.gatsbyjs.org/plugins/?=woocommerce)
- getting product information
- cart functionality 

### Motivation

The ability to build e-commerce sites with Gatsby gives developers (and business owners) a lot of flexibility. We'd like to provide a starting point for folks using some of the most popular e-commerce tools.

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a guide to imitate](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-site-with-authentication.md)
  - [Example of a similar article](https://www.gatsbyjs.org/docs/building-an-ecommerce-site-with-shopify/)
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the "Building an E-commerce Site" section.

### Open a pull request
- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by TylerBarnes** [comment]
Great idea! Heads up that there will be a new major version of `gatsby-source-wordpress` coming out in the new year and that will likely change what the best way to use Woo with Gatsby is. https://github.com/gatsbyjs/gatsby/issues/19292

Most likely once we have the new source plugin, using the [`wp-graphql-woocommerce`](https://github.com/wp-graphql/wp-graphql-woocommerce) plugin will be the way to go. We've been talking about making a Woo theme for the new source plugin as well!
