### ISSUE TITLE
Sorce code

### ISSUE THREAD

**Issue by gagan0723** [gatsbyjs/gatsby#2022]
I think the website for [gatsbyJS](https://www.gatsbyjs.org/) has a great design. It will be great if site's code is open source.

**Comment by jquense** [comment]
it is ! https://github.com/gatsbyjs/gatsby/tree/master/www

**Comment by KyleAMathews** [comment]
We also have a bunch of other example sites (though generally not with great design) https://github.com/gatsbyjs/gatsby/tree/master/examples

**Comment by gagan0723** [comment]
1. Please update [README](https://github.com/gatsbyjs/gatsby/tree/master/www). It says **gatsby-starter-default**, which it isn't.


2. I cloned the gatsby repo, copied **www** folder into another directory and did **npm install.** After, served it by **gatsby develop**, but I get following two errors: 
```success source and transform nodes — 0.191 s
success building schema — 0.797 s
success createLayouts — 0.035 s
error Plugin default-site-plugin returned an error

  TypeError: Cannot read property 'allMarkdownRemark' of undefined
    gatsby-node.js:61 graphql.then.result
    /home/gagan/Desktop/www/gatsby-node.js:61:22
```
**and**
```success createPages — 0.141 s
success createPagesStatefully — 0.170 s
GraphQL Error Unknown type "MarkdownRemark".

  file: /home/gagan/Desktop/www/src/components/blog-post-preview-item.js

   1 | 
>  2 |   fragment BlogPostPreview_item on MarkdownRemark {
     |                                    ^
   3 |     excerpt
   4 |     fields {
   5 |       slug
   6 |     }
   7 |     frontmatter {
   8 |       excerpt
   9 |       title
  10 |       date(formatString: "MMMM Do YYYY")
  11 |       author {
  12 |         id

success extract queries from components — 1.315 s
```
Haven't figured it out.

**Comment by KyleAMathews** [comment]
@gagan0723 Could you PR updating the README?
