### ISSUE TITLE
--prefix-paths breaks gatsby-image in build

### ISSUE THREAD

**Issue by jorgebustamante** [gatsbyjs/gatsby#20237]
## Local Build runs fine when served, breaks after deploy because of --prefix-paths(i think)
running build and serve shows me my project working right. After I run npm run deploy to deploy with gh-pages, the --prefix-paths ran during deploy breaks the build.   
The deploy should show img srcset as:      
`<img sizes="(max-width: 600px) 100vw, 600px" srcset="/PATHPREFIX/static/655054bd2b11872551ad6037bad00b9b/421ae/anayancy.jpg 150w>`   
![rightsrcset](https://user-images.githubusercontent.com/43390616/71242643-3f0cec00-22c3-11ea-9ead-3d53ce60d708.JPG)   

but after the --prefix-paths ran to deploy it changes to:     
`<img sizes="(max-width: 600px) 100vw, 600px" srcset="/static/655054bd2b11872551ad6037bad00b9b/421ae/anayancy.jpg 150w>`    
![brokesrcset](https://user-images.githubusercontent.com/43390616/71242621-34eaed80-22c3-11ea-95bd-3992ee93d354.JPG) 

### Steps to reproduce
[Reproduction Repo](https://github.com/jorgebustamante/gatsby-prefixpath-bug-repro)   
[Deployment of bug](https://jorgebustamante.github.io/gatsby-prefixpath-bug-repro/)   

1. Git clone reproduction Repo(master branch)   
2. npm install   
3. Gatsby Develop, view localhost8000 to preview that content was queried smoothly
4. Gatsby Build, gatsby serve localhost9000 to preview the optimized build
5. npm run deploy, gatsby serve and view githubpages deploy, the build is now broken

### Expected result

src for images in deployed build should point to "/reponame/static/...'   
![working](https://user-images.githubusercontent.com/43390616/71242657-4502cd00-22c3-11ea-9950-91825a669f51.JPG)
### Actual result
src for images in deployed build instead point to an invalid path of just '/static/'   
![notworking](https://user-images.githubusercontent.com/43390616/71242664-47652700-22c3-11ea-9c9e-3d8d421a9b19.JPG)

### Environment

`
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz
  Binaries:
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.0 - /c/Users/pauli/AppData/Local/Programs/Python/Python38-32/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.15 => 2.18.15 
    gatsby-image: ^2.2.37 => 2.2.37 
    gatsby-plugin-sharp: ^2.3.9 => 2.3.9 
    gatsby-source-filesystem: ^2.1.42 => 2.1.42 
    gatsby-source-graphql: ^2.1.29 => 2.1.29 
    gatsby-transformer-json: ^2.2.22 => 2.2.22 
    gatsby-transformer-sharp: ^2.3.9 => 2.3.9 
`   
hope i filled this out right, I haven't submitted an issue on github before but I really got stuck on this problem, and cant tell if its a bug or if I'm doing something within gatsby thats too conflicting.   
gh-pages, gatsby-transformer-json, and gatsby-image are the 3 packages that I feel are most significant with this issue.

**Comment by jorgebustamante** [comment]
### UPDATE DIOS MIO   
Okay so the docs show pathPrefix to be written in gatsby-config as `pathPrefix: "/reponame",`   
[How Gatsby Works with GitHub Pages
](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/)   
i previously had my pathPrefix written in double quote, but changed it to back ticks and it works, this is odd because doublequote previously worked for me on older version gatsby projects.  
So i changed this:   
![doublequote](https://user-images.githubusercontent.com/43390616/71314058-d888ea80-23f6-11ea-862e-25051068f67f.JPG)   
To backticks:   

![backtick](https://user-images.githubusercontent.com/43390616/71314059-daeb4480-23f6-11ea-844b-805075b998e3.JPG)    
However when I changed it back to double quotes and ran deploy, I couldn't replicate the bug in my reproduction! Since I can't consistently recreate the problem-- I'm going to close this now because I found that backticks fixed my issue, but I think that double quotes in pathprefix is somehow causing a problem.

**Comment by vhermecz** [comment]
The nondeterminism of the problem hints at a cache issue.
Running a `gatsby clean` before the `gatsby build` did it for me.

**Comment by iosonosempreio** [comment]
Hi, back ticks saved me as well.
`gatsby clean` was not helpful.

**Comment by richseviora** [comment]
Can I suggest reopening this issue? Running `gatsby clean` solved the problem for me, so it sounds like there's at least _something_ here

**Comment by zaidakhterr** [comment]
Yes indeed. Neither does adding backticks.

**Comment by zaidakhterr** [comment]
> Can I suggest reopening this issue? Running `gatsby clean` solved the problem for me, so it sounds like there's at least _something_ here

Yes indeed. Neither does adding backticks.

**Comment by michelebruno** [comment]
Yes, it looks like a bug in caching. Images URLs should not be cached when prefix changes, because there is no need to clean cache and rebuild image just to change the urls.
