### ISSUE TITLE
Tailwind plugins not working

### ISSUE THREAD

**Issue by tw1t611** [gatsbyjs/gatsby#20244]
###  Description
Tailwind plugins not working on standard installation.
Everything is working fine, except the plugins.
If you add a class from a plugin to `global.css` like
```
.rotate-90 {
  transform: rotate(90deg);
}
```
, it is working fine:

### Steps to reproduce
- init gatsby project
- setup tailwind as descriped here: https://www.gatsbyjs.org/docs/tailwind-css/
  - there is a mistake in the docs: npm install tailwindcss --save-dev -> npm install tailwindcss
- npm install tailwindcss-transforms
- npx tailwind init
- tailwind.config.js (shortened):
```
module.exports = {
  theme: {
    extend: {
      colors: {
        "grey-100": "#EEEDED",
      },
    },
  },
  variants: {},
  plugins: [
    require("tailwindcss-transforms")(),
  ],
}
```
- gatsby-browser.js (first line):
```
import "./src/styles/global.css"
```
- global.css:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
@import "gradients.css"; // this is not related, but included just in case
// this would work:
// .rotate-90 { 
//   transform: rotate(90deg);
// }
```
- apply `.rotate-90` to any element

### Expected result
The element is rotated.

### Actual result
It is not.

**Comment by vladar** [comment]
Hi @tw1t611 !

Sorry to hear you're running into an issue. I followed all steps you outlined above and it worked for me on a default Gatsby starter.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by tw1t611** [comment]
Hi, did that same thing.
Maybe I miss something really stupid.

Here is the repro:
[bug repro](https://github.com/tw1t611/bug-repro)

**Comment by merelinguist** [comment]
@tw1t611 Why do you have the `.rotate-90` styling commented out in your [demo](https://github.com/tw1t611/bug-repro/blob/master/src/styles/global.css#L5)?

**Comment by tw1t611** [comment]
That is the rotate directive I would implement myself. However, I want to use the rotate directive of the `tailwindcss-transforms` plugin. This shows, that rotate styling is working and `tailwindcss-transforms`'s .rotate-90 should give the same result.

**Comment by vladar** [comment]
According to `tailwindcss-transforms` [docs](https://github.com/benface/tailwindcss-transforms) the rotate option is empty by default:

```js
    rotate: { // defaults to {}
      '90': '90deg',
      '180': '180deg',
      '270': '270deg',
      '3d': ['0', '1', '0.5', '45deg'],
    },
```

So you must add it to your `tailwind.config.js`:

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        "grey-100": "#EEEDED",
      },
    },
    rotate: {
      '90': '90deg',
    },
  },
  variants: {},
  plugins: [
    require("tailwindcss-transforms")(),
  ],
}
```

**Comment by tw1t611** [comment]
Ok... I am sorry, did not get, that the shown values aren't the defaults. I will close this. Thank you.
