### ISSUE TITLE
How to filter posts by Front Matter variables value

### ISSUE THREAD

**Issue by zhandosweb** [gatsbyjs/gatsby#20259]
Hello! 

I want to create category pages. Then I display **Active** and **Archive cars.** 

For it, I want to use Front Matter variable: `status: active` or `status: archive`. 

Here is a screenshot, what I mean: https://prnt.sc/qe437a. 

Please, tell me. Can I filter category posts using GraphQL? Filter by variable's value or something else? 

Sorry for the bad English. I'm still learning.

**Comment by jonniebigodes** [comment]
@zhandosweb i've picked up on your issue and you can filter content based on a frontmatter key.

Here are the steps i took to triage your issue:
- Created a new Gatsby website based on the [blog starter](https://github.com/gatsbyjs/gatsby-starter-blog).
- After the site was setup added a new markdown entry to make a even number. The entry was placed under `content\blog\another-post\index.md`, with the following content:
```markdown
---
title: Another post
date: "2015-05-01T22:12:03.284Z"
description: "some random post"
status: 'active'
---

# random data

this is some random text
```
- Changed the other blog entries to include the `status` frontmatter key, two of them with `active` and two others with `archive`.
- Changed `src\pages\index.js` to the following:
```js
import React from "react"
import { Link, graphql } from "gatsby"

import Bio from "../components/bio"
import Layout from "../components/layout"
import SEO from "../components/seo"
import { rhythm } from "../utils/typography"

class BlogIndex extends React.Component {
  render() {
    const { data } = this.props
    const siteTitle = data.site.siteMetadata.title
    const posts = data.allMarkdownRemark.edges

    return (
      <Layout location={this.props.location} title={siteTitle}>
        <SEO title="All posts" />
        <Bio />
        {posts.map(({ node }) => {
          const title = node.frontmatter.title || node.fields.slug
          return (
            <article key={node.fields.slug}>
              <header>
                <h3
                  style={{
                    marginBottom: rhythm(1 / 4),
                  }}
                >
                  <Link style={{ boxShadow: `none` }} to={node.fields.slug}>
                    {title}
                  </Link>
                </h3>
                <small>{node.frontmatter.date}</small>
                <p>The {node.frontmatter.status}</p>
              </header>
              <section>
                <p
                  dangerouslySetInnerHTML={{
                    __html: node.frontmatter.description || node.excerpt,
                  }}
                />
              </section>
            </article>
          )
        })}
        <Link to="/page-2/">View Archived Items</Link>
      </Layout>
    )
  }
}

export default BlogIndex

export const pageQuery = graphql`
  query {
    site {
      siteMetadata {
        title
      }
    }
    allMarkdownRemark(filter: { frontmatter: { status: { eq: "active" } } }) {
      edges {
        node {
          excerpt
          fields {
            slug
          }
          frontmatter {
            date(formatString: "MMMM DD, YYYY")
            title
            description
            status
          }
        }
      }
    }
  }
`
```

The key thing to take from the change is the `allMarkdownRemark` portion of the query. That bit will grab the data, filtered by all the items marked as active.
- Created a new page inside the `src\pages` folder called `page-2.js` with the following content inside:
```js
import React from "react"
import { Link, graphql } from "gatsby"

import Bio from "../components/bio"
import Layout from "../components/layout"
import SEO from "../components/seo"
import { rhythm } from "../utils/typography"

class Page2 extends React.Component {
  render() {
    const { data } = this.props
    const siteTitle = data.site.siteMetadata.title
    const posts = data.allMarkdownRemark.edges

    return (
      <Layout location={this.props.location} title={siteTitle}>
        <SEO title="All posts" />
        <Bio />
        {posts.map(({ node }) => {
          const title = node.frontmatter.title || node.fields.slug
          return (
            <article key={node.fields.slug}>
              <header>
                <h3
                  style={{
                    marginBottom: rhythm(1 / 4),
                  }}
                >
                  <Link style={{ boxShadow: `none` }} to={node.fields.slug}>
                    {title}
                  </Link>
                </h3>
                <small>{node.frontmatter.date}</small>
                <p>The {node.frontmatter.status}</p>
              </header>
              <section>
                <p
                  dangerouslySetInnerHTML={{
                    __html: node.frontmatter.description || node.excerpt,
                  }}
                />
              </section>
            </article>
          )
        })}
         <Link to="/">View Active Items</Link>
      </Layout>
    )
  }
}

export default Page2

export const pageQuery = graphql`
  query {
    site {
      siteMetadata {
        title
      }
    }
    allMarkdownRemark(filter: { frontmatter: { status: { eq: "archive" } } }) {
      edges {
        node {
          excerpt
          fields {
            slug
          }
          frontmatter {
            date(formatString: "MMMM DD, YYYY")
            title
            description
            status
          }
        }
      }
    }
  }
`

```
In this page is the oposite, the data that will be fetched and displayed are the items marked as `archive` .

- Ran `gatsby develop` and if open `http://localhost:8000` i'm getting the data and if i go to `http://localhost:8000/page-2` the oposite will be displayed.

As you mentioned in the description, you're still learning, i've setup a repo with the code used, it's located [here](https://github.com/jonniebigodes/gatsby-filter-frontmatter), so that you can look at it at your own pace and fiddle with it.

Feel free to provide feedback so that we can close this issue, or continue to work on it until we find a suitable solution.

**Comment by DaTurboD** [comment]
You can filter your posts by categories, tags, layouts or anything else which comes to your mind.

I created a seperate folder for each category in which i save the markdown files.

- content
-- posts
--- category1
---- post1
----- post1.md
--- category2
---- post1
----- post1.md
---- post2
----- post2.md

My frontmatter looks for example like this:
`---
layout: "post"
title: "8 Open-Source Web-GIS Anwendungen"
date: "2019-04-24"
category: "Geoinformatik"
tags: ["Web GIS","Open-Source","GIS"]
cover: "Open-Source Web-GIS Anwendungen.jpg"
caption: "ESA/DLR/FU Berlin; CC BY-SA 3.0 IGO"
published: "yes"
---`

For every category i have created a seperate page which graphql query looks like this:
`export const pageQuery = graphql`
  query Category1Query {
    allMarkdownRemark(
      limit: 2000
      sort: { fields: [fields___date], order: DESC }
      filter: {fileAbsolutePath: {regex: "/posts/category1/.*\\.md$/"}}
    ) {
      edges {
        node {
          fields {
            slug
            date
          }
          excerpt
          timeToRead
          frontmatter {
            layout
            title
            tags
            cover
            date
            category
          }
        }
      }
    }
  }
`;`

With the following PostListing Component (in every category page) all the posts are created with a preview.
`import React from "react";
import PostPreview from "../PostPreview";

class PostListing extends React.Component {
  getPostList() {
    const postList = [];
    this.props.postEdges.forEach(postEdge => {
      postList.push({
        path: postEdge.node.fields.slug,
        tags: postEdge.node.frontmatter.tags,
        cover: postEdge.node.frontmatter.cover,
        title: postEdge.node.frontmatter.title,
        date: postEdge.node.fields.date,
        excerpt: postEdge.node.excerpt,
        timeToRead: postEdge.node.timeToRead,
        category: postEdge.node.frontmatter.category,
        layout: postEdge.node.frontmatter.layout
      });
    });
    return postList;
  }
  render() {
    const postList = this.getPostList();
    return (
      <div className="row">
          {postList.map(post => (
            <PostPreview key={post.title} postInfo={post} />
          ))}
      </div>
    );
  }
}

export default PostListing;`

Your gatsby-node.js is responsible for creating actual pages from your markdown files.

`if (edge.node.frontmatter.layout === 'post' && edge.node.frontmatter.published == "yes") { //post 
      createPage({
        path: edge.node.fields.slug,
        component: post,
        context: {
          slug: edge.node.fields.slug,
          category: edge.node.frontmatter.category,
          timetoread: edge.node.frontmatter.timetoread,
          tags: edge.node.frontmatter.tags,
          date: edge.node.frontmatter.date,
          nexttitle: nextEdge.node.frontmatter.title,
          nextslug: nextEdge.node.fields.slug,
          prevtitle: prevEdge.node.frontmatter.title,
          prevslug: prevEdge.node.fields.slug
        }
      });
    }`

I used a gatsby starter from Vagr9K which helped me alot to setup my current blog.
https://github.com/Vagr9K/gatsby-advanced-starter/tree/master/src

**Comment by jonniebigodes** [comment]
@DaTurboD i've been reading up on your answer. And you're correct also. But upon checking the code, more specifically:
```javascript
import React from "react";
import PostPreview from "../PostPreview";

class PostListing extends React.Component {
  getPostList() {
    const postList = [];
    this.props.postEdges.forEach(postEdge => {
      postList.push({
        path: postEdge.node.fields.slug,
        tags: postEdge.node.frontmatter.tags,
        cover: postEdge.node.frontmatter.cover,
        title: postEdge.node.frontmatter.title,
        date: postEdge.node.fields.date,
        excerpt: postEdge.node.excerpt,
        timeToRead: postEdge.node.timeToRead,
        category: postEdge.node.frontmatter.category,
        layout: postEdge.node.frontmatter.layout
      });
    });
    return postList;
  }
  render() {
    const postList = this.getPostList();
    return (
      <div className="row">
          {postList.map(post => (
            <PostPreview key={post.title} postInfo={post} />
          ))}
      </div>
    );
  }
}
export default PostListing;
```
This is doing some unnecessary work. You technically wouldn't need the array that is created here, this is introducing extra data that is not needed. All of this could come from `gatsby-node.js` through the `context` and with that remove the need of a extra query, which will add time to the build and so on. And leave only this component to do it's job that is to render information. I have skimmed through the starter and it seems that this could be better optimized to get more "bang for your buck" (pardon the bad pun).
