### ISSUE TITLE
Differences between commands for Gatsby development

### ISSUE THREAD

**Issue by zhandosweb** [gatsbyjs/gatsby#20256]
Hello!

Please, let me ask one question. Whats differences between commands below:

```
gatsby develop
gatsby serve
npm run develop
```

What're differences? All of those commands run local development server.. And which of them should I use?

**Comment by lannonbr** [comment]
So the 1st and 3rd are likely the same. `npm run develop` looks for a `develop` key in the scripts section of your `package.json`. Usually it is set to `gatsby develop` by default if you use a starter. `gatsby develop` is the Gatsby CLI which will start up a development server of your site.

`gatsby serve` on the other hand is a command you can run after `gatsby build` to spin up a local server that serves the production version of your site which was made with `gatsby build`.

Hope that helps!

**Comment by jonniebigodes** [comment]
@anuraghazra adding a bit more context to what @lannonbr said. Look at [this](https://www.gatsbyjs.org/docs/gatsby-cli/) for a bit more context on the different commands available to gatsby.

**Comment by zhandosweb** [comment]
Thank you very much for the answers! I clearly understand all!
