### ISSUE TITLE
package installation error

### ISSUE THREAD

**Issue by Muizuddeen** [gatsbyjs/gatsby#20254]
### package.json

{
  "_from": "gatsby-cli",
  "_id": "gatsby-cli@2.8.21",
  "_inBundle": false,
  "_integrity": "sha512-lRf9xm9qa0Zzp6N/sfPXot01WLm6ABjREeKQgZ8pxNYngVZFtR3N51/+NIEY4VMEGvaALBanhAD5MiOcPYoiOQ==",
  "_location": "/gatsby-cli",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "gatsby-cli",
    "name": "gatsby-cli",
    "escapedName": "gatsby-cli",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/gatsby-cli/-/gatsby-cli-2.8.21.tgz",
  "_shasum": "456277538b983545be5dc2ce036616f5a5b43fdf",
  "_spec": "gatsby-cli",
  "_where": "C:\\Users\\user",
  "author": {
    "name": "Kyle Mathews",
    "email": "mathews.kyle@gmail.com"
  },
  "bin": {
    "gatsby": "lib/index.js"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@babel/code-frame": "^7.5.5",
    "@babel/runtime": "^7.7.6",
    "@hapi/joi": "^15.1.1",
    "better-opn": "^1.0.0",
    "bluebird": "^3.7.2",
    "chalk": "^2.4.2",
    "clipboardy": "^2.1.0",
    "common-tags": "^1.8.0",
    "configstore": "^5.0.0",
    "convert-hrtime": "^3.0.0",
    "core-js": "^2.6.11",
    "envinfo": "^7.5.0",
    "execa": "^3.4.0",
    "fs-exists-cached": "^1.0.0",
    "fs-extra": "^8.1.0",
    "gatsby-core-utils": "^1.0.25",
    "gatsby-telemetry": "^1.1.46",
    "hosted-git-info": "^3.0.2",
    "ink": "^2.6.0",
    "ink-spinner": "^3.0.1",
    "is-valid-path": "^0.1.1",
    "lodash": "^4.17.15",
    "meant": "^1.0.1",
    "node-fetch": "^2.6.0",
    "object.entries": "^1.1.0",
    "opentracing": "^0.14.4",
    "pretty-error": "^2.1.1",
    "progress": "^2.0.3",
    "prompts": "^2.3.0",
    "react": "^16.12.0",
    "redux": "^4.0.4",
    "resolve-cwd": "^2.0.0",
    "semver": "^6.3.0",
    "signal-exit": "^3.0.2",
    "source-map": "0.7.3",
    "stack-trace": "^0.0.10",
    "strip-ansi": "^5.2.0",
    "update-notifier": "^3.0.1",
    "uuid": "3.3.3",
    "yargs": "^12.0.5",
    "yurnalist": "^1.1.1"
  },
  "deprecated": false,
  "description": "Gatsby command-line interface for creating new sites and running Gatsby commands",
  "devDependencies": {
    "@babel/cli": "^7.7.5",
    "@babel/core": "^7.7.5",
    "babel-preset-gatsby-package": "^0.2.14",
    "cross-env": "^5.2.1"
  },
  "files": [
    "lib",
    "scripts"
  ],
  "gitHead": "f5f0c9b91d914cc86f9ce483e062357ed7ebbb7d",
  "homepage": "https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-cli#readme",
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "lib/index.js",
  "name": "gatsby-cli",
  "optionalDependencies": {
    "ink": "^2.6.0",
    "ink-spinner": "^3.0.1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gatsbyjs/gatsby.git",
    "directory": "packages/gatsby-cli"
  },
  "scripts": {
    "build": "babel src --out-dir lib --ignore \"**/__tests__\" --extensions \".ts,.js\"",
    "postinstall": "node scripts/postinstall.js",
    "prepare": "cross-env NODE_ENV=production npm run build",
    "watch": "babel -w src --out-dir lib --ignore \"**/__tests__\"  --extensions \".ts,.js\""
  },
  "version": "2.8.21",
  "yargs": {
    "boolean-negation": false
  }
}

Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\user>gatsby -v
Gatsby CLI version: 2.8.21

C:\Users\user>npm install gatsby-cli
^C^CTerminate batch job (Y/N)? Y

C:\Users\user>npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

C:\Users\user>npm install -g gatsby-cli
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
Terminate batch job (Y/N)? Y

C:\Users\user>core-js -v
'core-js' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\user>npm install -g core-js

> core-js@3.6.0 postinstall C:\Users\user\AppData\Roaming\npm\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

+ core-js@3.6.0
added 1 package in 6.944s

C:\Users\user>core-js -v
'core-js' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\user>npm install -g gatsby-cli
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
C:\Users\user\AppData\Roaming\npm\gatsby -> C:\Users\user\AppData\Roaming\npm\node_modules\gatsby-cli\lib\index.js

> gatsby-cli@2.8.21 postinstall C:\Users\user\AppData\Roaming\npm\node_modules\gatsby-cli
> node scripts/postinstall.js

Success!

Welcome to the Gatsby CLI! Please visit https://www.gatsbyjs.org/docs/gatsby-cli/ for more information.

Usage: gatsby <command> [options]

Commands:
  gatsby develop                   Start development server. Watches files, rebuilds, and hot reloads if something changes
  gatsby build                     Build a Gatsby project.
  gatsby serve                     Serve previously built Gatsby site.
  gatsby info                      Get environment information for debugging and issue reporting
  gatsby clean                     Wipe the local gatsby environment including built assets and cache
  gatsby repl                      Get a node repl with context of Gatsby environment, see (https://www.gatsbyjs.org/docs/gatsby-repl/)
  gatsby new [rootPath] [starter]  Create new Gatsby project.
  gatsby plugin                    Useful commands relating to Gatsby plugins
  gatsby telemetry                 Enable or disable Gatsby anonymous analytics collection.

Options:
  --verbose                Turn on verbose output                                                                                             [boolean] [default: false]
  --no-color, --no-colors  Turn off the color in output                                                                                       [boolean] [default: false]
  --json                   Turn on the JSON logger                                                                                            [boolean] [default: false]
  -h, --help               Show help                                                                                                                           [boolean]
  -v, --version            Show the version of the Gatsby CLI and the Gatsby package in the current project                                                    [boolean]
npm WARN ink@2.6.0 requires a peer of @types/react@>=16.8.0 but none is installed. You must install peer dependencies yourself.

+ gatsby-cli@2.8.21
updated 2 packages in 372.649s

C:\Users\user>cd desktop

C:\Users\user\Desktop>**gatsby** new gatsby-site
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git
Cloning into 'gatsby-site'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 28 (delta 2), reused 17 (delta 2), pack-reused 0
Unpacking objects: 100% (28/28), done.
success Created starter directory layout
info Installing packages...
npm WARN tarball tarball data for terser-webpack-plugin@1.4.3 (sha512-QMxecFz/gHQwteWwSo5nTc6UaICqN1bMedC5sMtUc7y3Ha3Q8y6ZO0iCR8pq4RJC8Hjf0FEPEHZqcMB/+DFCrA==) seems to be corrupted. Trying one more time.
Terminate batch job (Y/N)? Y

C:\Users\user\Desktop>

> How can i upgrade core-js and install peer dependencies .

**Comment by vladar** [comment]
Most of the issues I see in the output are warnings, not errors. You should let `npm` commands to finish.

And you don't need to update `core-js` dependency yourself. This is something we must do one day in Gatsby core. Sadly, there are some issues with a newer version that do not allow us switching immediately but this is not related to your situation.

Please try again and wait until npm command finishes (do not terminate). Then run `gatsby build` from your `gatsby-site` directory and report if it doesn't work.

**Comment by majorboob** [comment]
Can someone explain what this warning means? and how to fix it? 

Windows and Linux issue.

`npm WARN ink@2.6.0 requires a peer of @types/react@>=16.8.0 but none is installed. You must install peer dependencies yourself.`

**Comment by LekoArts** [comment]
As vladar said those are warnings and you don't have to do anything. The `ink` warning appears as our CLI uses [ink](https://github.com/vadimdemedes/ink) and they might have changed their `peerDependencies` in the past. Everything should work fine nevertheless :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
