### ISSUE TITLE
Unhandled Rejection (SecurityError) 

### ISSUE THREAD

**Issue by astridx** [gatsbyjs/gatsby#20263]
## Relevant information

I have just worked through the first part of the tutorial (https://www.gatsbyjs.org/tutorial/part-one/)

When I open` localhost:8080` in the last step I see the following message.

I'm too new to judge why this message is displayed. You can also simply click them away.
However, since it appears in the beginner's tutorial, a brief note in Tutotial would be helpful.
### File contents (if changed)

![localhost 8000 ](https://user-images.githubusercontent.com/9974686/71324071-ae105d80-24da-11ea-914c-38fd7cef02cd.png)

```
Unhandled Rejection (SecurityError): The operation is insecure.
./.cache/app.js/</<
//hallo-welt/.cache/app.js:41

  38 |  * Let's warn if we find service workers in development.
  39 |  */
  40 | if (`serviceWorker` in navigator) {
> 41 |   navigator.serviceWorker.getRegistrations().then(registrations => {
  42 |     if (registrations.length > 0)
  43 |       console.warn(
  44 |         `Warning: found one or more service workers present.`,

This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
```

### Environment (if relevant)

```
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.17.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.79
    Firefox: 71.0
  npmGlobalPackages:
    gatsby-cli: 2.8.21

```

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by joshwcomeau** [comment]
Hey @astridx!

Thanks for the report. I believe that this is a duplicate of #16076 (though it's noteworthy that this is happening in the latest stable release of Firefox, and not just the developer edition!)

I tried to reproduce this myself, after I saw it happened to a friend, though I wasn't able to (not on Mac Firefox 71, nor in a Windows VM). So there may be some work ahead to get a reliable repro going =(

Just a heads-up for anyone who takes a look at this issue: I looked into whether `network.websocket.allowInsecureFromHTTPS` was to blame, but I don't see the issue even when I'm not allowing insecure requests.

**Comment by astridx** [comment]
> Your report lists both Chrome _and_ Firefox - is it happening in Chrome for you as well?

No, it does not happen in Chrome.

Maybe that's helpful: I worked through the tutorial for the first time about 6 weeks ago. On the same computer with Firefox - unfortunately I don't know the version at that time. At that time, the error did not occur.

**Comment by LekoArts** [comment]
Let's close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/16076
