### ISSUE TITLE
Gatsby markdown remark transforms underscore characters incorrectly

### ISSUE THREAD

**Issue by piavgh** [gatsbyjs/gatsby#20266]
## Description

Describe the issue that you're seeing.

The markdown remark plugin doesn't work correctly when underscores ( _ ) are used. It turns the word between to italic.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

Please check my repository: https://github.com/piavgh/hoangtrinhj.com/blob/master/content/posts/2019-12-22-mysql-create-database-with-utf8-character-set.md

And the result here: https://hoangtrinhj.com/mysql-create-database-with-utf-8-character-set

Just set up a normal Gatsby project with markdown remark plugin, and test with this line:

`CREATE DATABASE `mydb` CHARACTER SET utf8 COLLATE utf8_general_ci;`

### Expected result

What should happen?

The text `utf8_general_ci` should appear as is

### Actual result

What happened.

It turns to `utf8generalci` with the `general` in italic font

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.14.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Languages:
    Python: 3.7.5 - /Users/piavgh/anaconda3/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.4.3 => 2.15.28
    gatsby-image: ^2.0.41 => 2.2.23
    gatsby-plugin-catch-links: ^2.0.13 => 2.1.12
    gatsby-plugin-emotion: ^4.1.9 => 4.1.9
    gatsby-plugin-feed: ^2.2.0 => 2.3.15
    gatsby-plugin-google-analytics: ^2.0.19 => 2.1.19
    gatsby-plugin-lodash: ^3.0.5 => 3.1.10
    gatsby-plugin-manifest: ^2.1.1 => 2.2.20
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-nprogress: ^2.0.10 => 2.1.9
    gatsby-plugin-offline: ^3.0.29 => 3.0.29
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.10
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-sharp: ^2.0.37 => 2.2.27
    gatsby-plugin-sitemap: ^2.1.0 => 2.2.16
    gatsby-plugin-twitter: ^2.0.13 => 2.1.9
    gatsby-plugin-typescript: ^2.1.11 => 2.1.11
    gatsby-plugin-typography: ^2.3.6 => 2.3.10
    gatsby-remark-autolink-headers: ^2.0.16 => 2.1.13
    gatsby-remark-copy-linked-files: ^2.0.12 => 2.1.23
    gatsby-remark-images: ^3.0.11 => 3.1.25
    gatsby-remark-prismjs: ^3.2.9 => 3.3.16
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.2.20
    gatsby-source-filesystem: ^2.0.33 => 2.1.28
    gatsby-transformer-remark: ^2.3.12 => 2.6.26
    gatsby-transformer-sharp: ^2.1.19 => 2.2.19
```

**Comment by vladar** [comment]
Thank you for opening this, @piavgh 

Looks like this a default behavior of [`pedantic`](https://github.com/remarkjs/remark/tree/master/packages/remark-parse#optionspedantic) option of the remark (which is `true` in Gatsby by default).

Fortunately `gatsby-transformer-remark` allows [changing this option](https://www.gatsbyjs.org/packages/gatsby-transformer-remark/?=remark#how-to-use):

```js
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        pedantic: false,
        // ... other options
      }
    }
```

I am marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. I hope we managed to help and thank you for using Gatsby! 💜

**Comment by piavgh** [comment]
Thank you,  @vladar . It works properly now.
