### ISSUE TITLE
Poor Google Page Insights score for mobile

### ISSUE THREAD

**Issue by keithpacana** [gatsbyjs/gatsby#20260]
So I'm using gatsby for its "blazing fast" property, which is apparent on desktop, however, on mobile my page insights score is poor (30-44) and I'm not sure why?  I use gatsby-image to optimize/resize images, so I'm not sure why the score is so low? Is there a property of gatsby that I missed that may contribute to this poor score? Or could this possibly just the contents on my website?

**Comment by daugsbi** [comment]
I haven't experienced any problems regarding the speed of our company website (https://twteam.ch).

When it is related to the bundle size, the plugin "gatsby-plugin-webpack-bundle-analyzer" comes in really handy.

Do you place a lot of images on the same page?

Please share a link and we can check it out

**Comment by LekoArts** [comment]
Thank you for opening this!

Gatsby performs as well on mobile as on desktop so it has to be something on your website. Maybe these docs help: https://www.gatsbyjs.org/docs/performance/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by s1awek** [comment]
There's still a performance problem with Gatsby, at least according to Google Speed Insights: ![2021-12-23 13_36_36-PageSpeed Insights](https://user-images.githubusercontent.com/3338469/147241881-784c6698-d239-40d5-a716-dc39100144f3.png)
