### ISSUE TITLE
Unable to find prism language and code block or inline code language. 

### ISSUE THREAD

**Issue by e76971072** [gatsbyjs/gatsby#20297]
I am having trouble try to deploy my app to Google Cloud engine, since my app worked on my localhost but I can't deploy it with these 4 issues : I also tried @DSchau  solutions but I still can't get rid of it. Any suggestion ? Thanks in advance 

 <strong> -  warn unable to find prism language 'shell:title=bin/composer' for highlighting. applying generic code block  </strong>
 <strong>  - warn unable to find prism language 'yaml:title=docker-compose.yml' for highlighting. applying generic code block </strong>
 <strong> - warn code block or inline code language not specified in markdown. applying generic code block </strong>
 <strong> - warn unable to find prism language 'javascript:title=highlight.js' for highlighting. applying generic code block </strong>

`{
       

            resolve: `gatsby-remark-prismjs`,

            options: {
               aliases: {
                dosini: `ini`,
                env: `zshrc`,
                es6: `javascript`,
                sh: `shell`, 
                flowchart: `none`,
                gitignore: `none`,
                gql: `graphql`,
                htaccess: `apacheconf`,
                mdx: `markdown`,
                ml: `fsharp`,
                styl: `stylus`,
              },
              languageExtensions: [
                {
                  language: 'superscript',
                  extend: 'javascript',
                  definition: {
                    superscript_types: /(SuperType)/,
                  },
                  insertBefore: {
                    function: {
                      superscript_keywords: /(superif|superelse)/,
                    },
                  },
                },
              ],
              // Customize the prompt used in shell output
              // Values below are default
              prompt: {
                user: 'root',
                host: 'localhost',
                global: false,
              },
            },
          },`

**Comment by e76971072** [comment]
Updated: I fixed 3 issues so far, notice that only specify the language in markdown
Ex: 

<strong>'shell:title=bin/composer' -> ```shell </strong>

<strong>'yaml:title=docker-compose.yml' -> ```yaml </strong>

<strong>'javascript:title=highlight.js' ->```javascript</strong>


still having trouble with

-   warn unable to find prism language 'javascript:title=highlight.js' for highlighting. applying generic code block

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
