### ISSUE TITLE
Cannot query field "fields" on type "MarkdownRemark"

### ISSUE THREAD

**Issue by kherwata** [gatsbyjs/gatsby#20296]
i copied a code from gatsby docs but i think "fields" does not exist in MarkdownRemark :
**Reproduction :** 
1 - install latest version of gatsby cli
2 - copy code and install plugins from docs https://www.gatsbyjs.org/docs/adding-tags-and-categories-to-blog-posts/
3 - run gatsby develop

**Comment by ymqy** [comment]
How did you solve it? I encountered this problem too.

**Comment by vexilar** [comment]
???

**Comment by vexilar** [comment]
Root cause for me was I had put gatsby-node.js in the src folder instead of the root of the site as the tutorial directs -- my bad. Hopefully this helps someone else.
