### ISSUE TITLE
Gatsby build production error with lots of type undefined

### ISSUE THREAD

**Issue by Wayne-CO** [gatsbyjs/gatsby#20292]
## Description
My site is using Material UI as the only external library. 
I developed a website locally and everything is working as expected when on 

> gatsby develop

Issue is now that I'm trying to build production files by running 

> gatsby build

I get lots of property ____ of undefined. For example: WebpackError: TypeError: Cannot read property 'headline' of undefined

I'm confused why there are no errors during develop but why only during the production build there are lots of these type errors. It's not like these properties are undefined because they are passed actual values. For example props passed from a parent to child. 

### Steps to reproduce
Here is my repository: https://github.com/Wayne-CO/Greenstone-Wellness

Running `gatsby develop` works fine but when running `gatsby build` different type undefined errors keep showing up as I comment those parts out.

### Expected result

I should be getting production files made when running gatsby build

### Actual result

Type errors like for example in header.js where data is a prop passed in from the parent component.

   98 |           </Box>
   99 |         </Toolbar>
> 100 |         <Hero
      |         ^
  101 |           headline={data.headline}
  102 |           tagline={data.tagline}
  103 |           primaryBtnLabel={data.primaryBtnLabel}

  WebpackError: TypeError: Cannot read property 'headline' of undefined

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    npm: 6.12.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.8 => 2.18.17 
    gatsby-image: ^2.2.34 => 2.2.37 
    gatsby-plugin-manifest: ^2.2.31 => 2.2.34 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6 
    gatsby-plugin-offline: ^3.0.27 => 3.0.30 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.18 
    gatsby-plugin-sharp: ^2.3.5 => 2.3.10 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.1.40 => 2.1.43 
    gatsby-theme-material-ui: ^1.0.5 => 1.0.5 
    gatsby-transformer-sharp: ^2.3.7 => 2.3.9 
  npmGlobalPackages:
    gatsby-cli: 2.8.22

**Comment by vladar** [comment]
Thank you for opening this, @Wayne-CO 

In `develop` Gatsby generates a special development 404 page. But for `build` your `404.js` page gets rendered. And that's where the error occurs.

Your 404.js page doesn't pass props to Layout (see [those lines](https://github.com/Wayne-CO/Greenstone-Wellness/blob/8db1e298910b891d387c1be160a6a73b5fdfe55e/src/pages/404.js#L6-L7)). And layout [expects props](https://github.com/Wayne-CO/Greenstone-Wellness/blob/8db1e298910b891d387c1be160a6a73b5fdfe55e/src/components/layout.js#L8-L11) (which are later passed to the header component).

I am marking this issue as answered and closing it but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by Wayne-CO** [comment]
Thank you so much @vladar !
