### ISSUE TITLE
how to filter a list from allMarkdownRemark ?

### ISSUE THREAD

**Issue by PolGuixe** [gatsbyjs/gatsby#2029]
I want to filter the node by its title e.g.

```
{allMarkdownRemark(filter: { frontmatter:  { title: { eq:"Hello, World!"}}}){
   edges{
    node{
      frontmatter{
        title
      }
    }
  }
  }
}
```

This code above works.

I am trying to get the titles that are contained in a list. The coce below, obviusly doesn't work :(
```
{allMarkdownRemark(filter: { frontmatter:  { title: { in:["Hello, World!", "Goodbye, World!]} }}){
   edges{
    node{
      frontmatter{
        title
      }
    }
  }
  }
}
```

How can I implement this query?

**Comment by KyleAMathews** [comment]
Best thing to do now is the regex operator. It'd be cool to be able to exact match against an array!

**Comment by cr101** [comment]
I would also love to see an example of how to filter the data on a search page. I'm building an events related site and I will need to filter the results by location, category, price, etc

**Comment by MarcCoet** [comment]
@cr101 atm (or rather last time I checked) it is not possible to modify a query after build so you can't use the graphQL layer to implement client side filtering. Fortunately it will leave you with the power of React to do what you need. ;)

**Comment by PolGuixe** [comment]
Thanks, then I'll have to find other ways.

**Comment by brandonmp** [comment]
I don't know if this is an antipattern, but one thing I do for cases like this is to do my filtering etc in `gatsby-node.js`, then pass it down via `pageContext`


eg

```
createPage({
            path: `/blog/${post.slug}/`,
            component: blogPostTemplate,
            context: {
                id: post.id,
                shortPosts: myQueryResults.filter(r => r.length <= 300),
                prev,
                next
            }
        });
```

**Comment by KyleAMathews** [comment]
It's a bit of an antipattern as then it's not clear in the component where the data came from not how to modify it.

**Comment by brandonmp** [comment]
Got it--so it sounds like antipattern wrt clarity of code. are there perf/stability/etc implications?

**Comment by KyleAMathews** [comment]
>are there perf/stability/etc implications?

Nah, data added that way or from a query are handled in the same way e.g. written out to the same json file in .cache/json.

**Comment by LegNeato** [comment]
Note the regex operator works for finding multiple inclusions, but is a lot more difficult for exclusions (have to use a bunch of negative lookaheads). Adding an `nregex` or something similar would help.

**Comment by KyleAMathews** [comment]
@LegNeato that's a great idea! Or perhaps add a new top-level inverse of "filter" e.g. "exclude? Then keep the same operators but they remove instead of adding?

Want to create a new issue to discuss this idea?

**Comment by KyleAMathews** [comment]
Closing out older issues. Please open a new issue if you have questions!
