### ISSUE TITLE
Cannot resolve module 'warning'

### ISSUE THREAD

**Issue by danistefanovic** [gatsbyjs/gatsby#203]
I'm trying to follow the tutorial from the README but I always get the same error, when I start it with `gatsby develop`:
```
Listening at: http://0.0.0.0:8000
webpack built efaccc0b6dd2efb51363 in 3679ms
Hash: efaccc0b6dd2efb51363
Version: webpack 1.12.14
Time: 3679ms
    Asset     Size  Chunks       Chunk Names
bundle.js  1.42 MB       0       main
chunk    {0} bundle.js (main) 1.24 MB [rendered]
    [0] multi main 40 bytes {0} [built]
    [1] ./~/react/~/fbjs/lib/invariant.js 1.51 kB {0} [built]
    [2] ./~/react/lib/Object.assign.js 1.26 kB {0} [built]
...
  [465] ./~/typography/~/shallow-copy/index.js 798 bytes {0} [built]
  [466] ./~/underscore.string/helper/makeString.js 161 bytes {0} [built]
  [467] ./wrappers ^\.\/.*$ 182 bytes {0} [optional] [built]

ERROR in /Users/ds/.nvm/versions/node/v4.4.0/lib/~/gatsby/~/history/lib/DOMStateStorage.js
Module not found: Error: Cannot resolve module 'warning' in /Users/ds/.nvm/versions/node/v4.4.0/lib/node_modules/gatsby/node_modules/history/lib
 @ /Users/ds/.nvm/versions/node/v4.4.0/lib/~/gatsby/~/history/lib/DOMStateStorage.js 10:15-33
```

### Steps
1. `gatsby new docs-site gh:gatsbyjs/gatsby-starter-documentation`
1. `cd docs-site`
1. `gatsby develop`

Same error with the default starter:

1. `gatsby new test-gatsby`
1. `cd test-gatsby`
1. `gatsby develop`

### Versions
Node: 4.4.0
Gatsby: 0.8.10
OS: OS X 10.11.3

**Comment by KyleAMathews** [comment]
Just ran those steps w/o problems... are you on NPM 2 by chance?

**Comment by danistefanovic** [comment]
Damn, that was it. The only thing I didn't update. Thanks and sorry for the inconvenience!

**Comment by KyleAMathews** [comment]
Hrmm... well... things should work even with NPM 2 given it ships with Node 4.

**Comment by BerkeleyTrue** [comment]
This is still an issue. I get this all the time.
