### ISSUE TITLE
Choose createPages gatsby component based on server side rendering or browser rendering

### ISSUE THREAD

**Issue by arekkas** [gatsbyjs/gatsby#2031]
I am using createPages to automatically generate components based on some JSON input, like this:

```
exports.createPages = ({ graphql, boundActionCreators }) => {
  const { createPage } = boundActionCreators
  return new Promise((resolve, reject) => {
    graphql(`
{
  allPageJson{
    edges {
      node {
        id
        url
      }
    }
  }
}
    `).then(result => {
      result.data.allPageJson.edges.map(({ node }) => {
        createPage({
          path: node.url,
          component: path.resolve(`./src/templates/page.js`),
          context: {
            id: node.id,
          },
        })
      })
      resolve()
    })
  })
}
```

According to [this SO question](https://stackoverflow.com/questions/46059325/choose-createpages-gatsby-component-based-on-server-side-rendering-or-browser-re/46064923#46064923) that is only possible using NODE_ENV. I think that instead we should pass this info as an argument:

```
exports.createPages = ({ isBuildMode }) => {
  if (isBuildMode) {
     console.log('looks like you ran gatsby build')
     return
  }
  console.log('looks like you ran gatsby develop')
}
```

ping @KyleAMathews because you answered the SO question.

**Comment by KyleAMathews** [comment]
Happy to take a PR adding passing the build mode to plugins.

**Comment by KyleAMathews** [comment]
Closing this issue as it's fairly old. If you have additional problems in this area, please open a new issue!
