### ISSUE TITLE
Source plugins that execute HTTP requests should not DDoS the source

### ISSUE THREAD

**Issue by mglaman** [gatsbyjs/gatsby#20317]
## Summary

When developing or building a Gatsby app that uses a source plugin which integrates with an HTTP API, there should be some sort of throttling added that prevents DDoSing the source server.

I recently had this happen, asked in Drupal Slack and @KyleAMathews asked me to open an issue.

> source plugins need to handle this — we’ve been discussing ways to make it easier for source plugins to handle back pressure & automatically throttle themselves
> 
> would love it if you could write an issue with details about your situation! (edited) 

Relates to #20317

### Basic example

I have a $10 DigitalOcean droplet running Docker. It has an `nginx-proxy`, `jwilder/docker-gen`, and `jrcs/letsencrypt-nginx-proxy-companion`.

I then have my source Drupal site running -- based on php-apache and uses SQLite database backend.

I then began to compile my three Gatsby apps and everything shut down as the VM ran out of memory. _However_ that's because I was running `docker-compose logs -f`. Still, the site was normally accessible when browsing like normal as one user. But then Gatsby hit it with a sledgehammer.

### Motivation

* Prevent CDN's from flagging Gatsby builds as DDoS attacks
* Prevent Gatsby from gobbling up server resources (regardless of statements for better proxy and frontend caching of your backend)

Gatsby technically makes it so you can run a low-resource private source backend -- which means you don't need the fancy reverse proxies and caching.

**Comment by sidharthachatterjee** [comment]
Thank you so much for opening this! 

This is something we've discussed and very much plan to do. We've documented some ideas in https://github.com/gatsbyjs/gatsby/issues/10049. Would you like to leave a comment on that issue so we can track it there? 

I'll close this in the mean time as a duplicate. Thanks again!
