### ISSUE TITLE
Querying JSON from nested folders without polluting global types

### ISSUE THREAD

**Issue by cmwall** [gatsbyjs/gatsby#20325]
## Summary

My app has a structure as follows:

```
src/
  database/
    season-one/
      data.json
      category-one/
        data.json
        item-one/
          variant-one/
            01.jpg
            02.jpg
          variant-two/
            01.jpg
            02.jpg
          data.json
        item-two/
          variant-one/
            01.jpg
            02.jpg
          variant-two/
            01.jpg
            02.jpg
          data.json
      category-two/
        data.json
        item-one/
          variant-one/
            01.jpg
            02.jpg
          variant-two/
            01.jpg
            02.jpg
          data.json
        item-two/
          variant-one/
            01.jpg
            02.jpg
          variant-two/
            01.jpg
            02.jpg
          data.json
```

I would like to be able to query all JSON data within the JSON files through graphql.

There are hundreds (maybe 1,000+) `item` directories within categories.

I have `gatsby-transformer-json` and `gatsby-source-filesystem`:

```
    `gatsby-transformer-json`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `database`,
        path: path.join(__dirname, `src`, `database`),
      },
    },
```

This, however, pollutes my global graphql types with hundreds (maybe thousands) of different "Json" types. e.g. 
![image](https://user-images.githubusercontent.com/13528491/71548121-56a53e00-296f-11ea-8a87-b5abc840d49b.png)

I assume this is because of the nested folder structure I have. 

I would like to be able to query the JSON data inside each file without having to know its "type".

Ideally, my queries could look something like this (where I am querying JSON files with no slash (so only direct children of the top-level "database" directory and I am querying JSON keys "title" and "canonical"):

```graphql
  allFile(filter: {relativeDirectory: {regex: "/^[^/]+$/"}}) {
    edges {
      node {
        relativeDirectory
       	childDatabaseJson {
          title
          canonical
        }
      }
    }
  }
```

Is this possible? I would really rather not separate my images and my json files since the titles of the json files aren't specific and could potentially be repeated throughout seasons and even categories.

**Comment by cmwall** [comment]
To add a little more context:

I am trying to prevent myself from having to put my entire database into the `static/` folder because I want to take advantage of `gatsby-image` because my images are pretty big and load slowly.

Right now, I create all of my pages using `gatsby-node` and querying the file system but I would much rather use graphql in place `fs`.

**Comment by sidharthachatterjee** [comment]
@cmwall Absolutely possible! 

You can use schema customization API documented at https://www.gatsbyjs.org/docs/schema-customization/ to setup a schema yourself that looks more like the example you posted. 

Pro tip: Use `@dontInfer` on `Query` so that the global types don't get "polluted" 😉 

Hope this helps. Thanks!
