### ISSUE TITLE
gatsby-starter-blog-theme  printing "Functions that are interpolated in css calls will be stringified" error in console

### ISSUE THREAD

**Issue by seetdev** [gatsbyjs/gatsby#20326]
## Description
Fresh Gatsby instance created  using the command `gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme-core` is printing a "Functions that are interpolated in css calls will be stringified" error in browser console

<img width="1371" alt="Screen Shot 2019-12-28 at 10 42 29 PM" src="https://user-images.githubusercontent.com/35116035/71552318-b54ad600-29c8-11ea-8770-984f18c1ef5f.png">

### Steps to reproduce
1. On a machine with gatsby and yarn installed globally run `gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme-core`
2. go into newly created folder and run `gatsby develop`
3. view the site in chrome and open the developer tools -> console. You should be able to see the error

Minimal Reproduction 
https://github.com/seetdev-opensource/interpolated-in-css-calls-error

### Expected result
No "Functions that are interpolated in css calls will be stringified" error in browser console should be printed

### Actual result
"Functions that are interpolated in css calls will be stringified" was printed twice

### Environment
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v13.3.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v13.3.0/bin/npm
  Languages:
    Python: 3.7.3 - /Users/darrens/miniconda3/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 69.0.3
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-theme-blog: ^1.2.7 => 1.2.7
  npmGlobalPackages:
    gatsby-cli: 2.8.22

Additional Information
The error messages appear to be caused by the following block of code around lines 57-62 of packages/gatsby-theme-blog/src/components/header.js

```
const iconCss = [
  css({
    pointerEvents: `none`,
  }),
  { margin: 4 }, // Explicitly leave margin out of theme-ui, this positioning should not change based on theme
]
```
I can make the error go away if I change the same block of in node_modules to the following:
```
const iconCss = [
  {
    pointerEvents: "none",
  },
  { margin: 4 }, // Explicitly leave margin out of theme-ui, this positioning should not change based on theme
]
```

Not sure if it might be related but issue 997 in emotion-js/emotion mention something about not being able to compose themed css in emotion 10. The same issue mentioned that it might be fixed in version 11.

**Comment by LekoArts** [comment]
Thanks for the issue. This is indeed a problem and is concurring here:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-theme-blog/src/components/header.js#L57-L62

A PR should change this to (as you correctly wrote):

```
const iconCss = [
  {
    pointerEvents: "none",
  },
  { margin: 4 }, // Explicitly leave margin out of theme-ui, this positioning should not change based on theme
]
```

This way Theme UI is not used in this instance which is fine as a design token isn't used here anyways.

**Comment by seetdev** [comment]
I will create the PR for this.

**Comment by seetdev** [comment]
This is the first time I am trying to contribute to a monorepo and so I might be asking a lot of common sense questions. I was looking at both https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/ and https://www.youtube.com/watch?v=D0SwX1MSuas. But I could not figure out where to start. May I have some pointers (documentation or videos) on how to start on this. Sorry to take up your precious time.

**Comment by samovertonjr** [comment]
@seetdev the gatsby contribution docs would be what I recommend. Can you tell me any specific issues you are having with the setup? Also I can get on a call later today to help if needed.

**Comment by seetdev** [comment]
@samovertonjr In https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/ the part that I wasn't sure about was the statement about `Gatsby test sites` in the section `Gatsby functional changes` listed below

```
For each of your Gatsby test sites, run the gatsby-dev command inside the test site’s directory to copy the built files from your cloned copy of Gatsby. It’ll watch for your changes to Gatsby packages and copy them into the site. For more detailed instructions see the gatsby-dev-cli README and check out the gatsby-dev-cli demo video.

Note: if you plan to modify packages that are exported from gatsby directly, you need to either add those manually to your test sites so that they are listed in package.json (e.g. yarn add gatsby-link), or specify them explicitly with gatsby-dev --packages gatsby-link).
```

There is also the section on the tests that I was not able to locate the files. The location of the code to be changed is at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-theme-blog/src/components/header.js#L57-L62

**Comment by samovertonjr** [comment]
@seetdev  Were you able to get your local environment setup? Basically the Gatsby test site is a`gatsby new` site to test the changes you will be making on the theme. The site is so you can make sure the fix you are making to the theme is actually working in a dev environment before it is pushed live. The test just needs to have the package you are trying to test ex `gatsby-theme-blog`.

If you need help locating the file can you post a snapshot of the last folder you are stuck on trying to find the file.

**Comment by seetdev** [comment]
Sorry for the radio silence I am picking this back up and so I will try it again and let you know

**Comment by seetdev** [comment]
I have created the code change at https://github.com/seetdev-opensource/gatsby/tree/37d0cb547f89c95a81c6d91c0b68a3e00d2d40e6

But I was not able to test using the development environment or figure out where to add the unit tests for it.

**Comment by samovertonjr** [comment]
Hey @seetdev awesome on the progress! It is recommended to make sure the change is working on a development environment. I don't think we will need to write any unit test for this pr. The link 
below will show you how to get it setup.

On the left:
The local Gatsby Open Source Repo that you downloaded  
https://www.youtube.com/watch?v=D0SwX1MSuas

**Comment by seetdev** [comment]
@samovertonjr Thanks for the pointers. I managed to get the change working in the test environment. The following screen shots show the difference.

Pre Code Change
<img width="1360" alt="Screen Shot 2020-01-28 at 11 46 19 PM" src="https://user-images.githubusercontent.com/35116035/73328665-9c804b00-4228-11ea-8aa1-0611b7e78ea9.png">

Post Code Change
<img width="1221" alt="Screen Shot 2020-01-28 at 11 47 02 PM" src="https://user-images.githubusercontent.com/35116035/73328675-a144ff00-4228-11ea-8e85-5cfcdf59879a.png">

**Comment by samovertonjr** [comment]
Awesome! Get a PR up for this and you should be good to go.
