### ISSUE TITLE
Where can I find all possible config settings for `gatsby-config.js?

### ISSUE THREAD

**Issue by arekkas** [gatsbyjs/gatsby#2032]
The same question goes for `gatsby-node`, for example there is no docs available on which arguments are being passed to [`createPages`](https://www.gatsbyjs.org/docs/node-apis/#createPages) and for some reason it's not possible to console.log the values either.

**Comment by jbolda** [comment]
Are you looking for https://www.gatsbyjs.org/docs/bound-action-creators/#createPage ? See the first link within the section of the createPages link you linked.

**Comment by arekkas** [comment]
I want to know what other arguments are passed in `exports.createPages = ({ graphql, boundActionCreators }) => ...` so basically:

```
exports.createPages = (...args) => console.log(args)
```

**Comment by arekkas** [comment]
I want to know which arguments are being passed to: `exports.createPages = (...args) => ...`

I also want to know which configuration options are available in `gatsby-config`

**Comment by Undistraction** [comment]
@arekkas Did you find them?

**Comment by arekkas** [comment]
no :(

**Comment by Charon77** [comment]
Hi.
I was stumbled upon this question as well and believe I have found the answer inside the source code
(Man, this project really needs more docs 😸 )

[Here](https://github.com/gatsbyjs/gatsby/blob/e9bb320ef7ac5d36e1a6ff9898c0a2fbc2c58c17/packages/gatsby/src/joi-schemas/joi.js) it is.

**Comment by KyleAMathews** [comment]
@amberleyromo added a docs page for gatsby-config.js!

https://www.gatsbyjs.org/docs/gatsby-config/
