### ISSUE TITLE
Gatsby issue on first time install

### ISSUE THREAD

**Issue by erickacevedor** [gatsbyjs/gatsby#20320]
Hello!
This is the first time I'm trying Gatsby, but when I'm attempting to install it, the following error comes up, I tried a lot of fixes and commands but none of them works, so I come here if you can give me a hand on this: 

```
erickacevedor@Erick-Acevedos-MacBook-Pro ~ % gatsby new gatsby-site
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git
Cloning into 'gatsby-site'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 28 (delta 2), reused 17 (delta 2), pack-reused 0
Unpacking objects: 100% (28/28), done.
success Created starter directory layout
info Installing packages...

> fsevents@1.2.11 install /Users/erickacevedor/gatsby-site/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> sharp@0.23.4 install /Users/erickacevedor/gatsby-site/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/erickacevedor/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
ERR! sharp Please delete /Users/erickacevedor/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz as it is not a valid tarball
ERR! sharp zlib: unexpected end of file
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/erickacevedor/gatsby-site/node_modules/sharp
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.4 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.23.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/erickacevedor/.npm/_logs/2019-12-28T00_20_17_409Z-debug.log

 ERROR 

Command failed with exit code 1: npm install



  Error: Command failed with exit code 1: npm install

  - error.js:56 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:114:26

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7


erickacevedor@Erick-Acevedos-MacBook-Pro ~ % 
```

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

erickacevedor@Erick-Acevedos-MacBook-Pro bitbucket % gatsby info --clipboard

  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 71.0
    Safari: 13.0.3
  npmGlobalPackages:
    gatsby-cli: 2.8.22

erickacevedor@Erick-Acevedos-MacBook-Pro bitbucket % 

```

**Comment by auspic7** [comment]
It seems like you haven't completely installed dependencies yet. Executing `npm update` to update modules and dependencies would help.

**Comment by djkloop** [comment]
Ubuntu:18.04 docker, the same problem.

**Comment by LOKESH-97** [comment]
How to fix the problem for gatsbyjs windows config Error
  - error.js:56 makeError
    [npm]/[gatsby-cli]/[execa]/lib/error.js:56:11

  - index.js:114 handlePromise
    [npm]/[gatsby-cli]/[execa]/index.js:114:26

  - task_queues.js:86 processTicksAndRejections
    internal/process/task_queues.js:86:5

**Comment by elfilalime** [comment]
Have the same problem on windows 10

**Comment by sidharthachatterjee** [comment]
@erickacevedor @elfilalime The issue here is that `libvips` is a dependency for `sharp` which `gatsby-plugin-sharp` uses (which is in the default starter that you're using)

Please check out https://github.com/libvips/libvips/#install for instructions on how to install it. 

That should resolve the issue. If it doesn't, please feel free to reopen and comment. Thanks!

**Comment by maverick-27** [comment]
This issue occurs on first Time install how to resolve ???

C:\Users\Akhil Joshi\AppData\Roaming\npm\node_modules\gatsby-cli\lib\init-starter.js:117
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Akhil Joshi\AppData\Roaming\npm\node_modules\gatsby-cli\lib\create-cli.js:28:20)

**Comment by kentmz** [comment]
There is a workaround for this. Go to the file that its complaining about on that line and change the `catch{` to `catch(err) {` and try again. It worked for me. I had to do the change on init-starter.js and ensure-windows-drive-letter-is-uppercase.js

**Comment by apanagar** [comment]
@kentmz I followed the suggestion, but just hit the same error somewhere else

```
/.nvm/versions/node/v8.9.4/lib/node_modules/gatsby-cli/lib/util/ensure-windows-drive-letter-is-uppercase.js:41
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```

**Comment by kentmz** [comment]
@apanagar You will need to make the change to this file as well. I've already mentioned in my comment. :)

**Comment by apanagar** [comment]
> @apanagar You will need to make the change to this file as well. I've already mentioned in my comment. :)

Ah got it. Thanks for letting me know, I wasn't sure if I was going down a path of lots and lots of changes 👍

**Comment by apanagar** [comment]
Actually, upgrading to node 10 using the instructions here solved my problem

https://www.gatsbyjs.org/docs/upgrading-node-js/

I was on node 8

**Comment by SJI-ParthaSarathi** [comment]
Upgrading to node 10.18.0 worked for me. thanks @apanagar
