### ISSUE TITLE
Does Gatsby support generating navigation/menus based on arbitrary nested directory structure?

### ISSUE THREAD

**Issue by mpodlasin** [gatsbyjs/gatsby#20331]
Hi.

This is a very basic use case, but believe me, I have been looking whole evening - in docs, on stackoverflow and on google in general. Maybe I don't know how to phrase the problem correctly.

I have some file structure of arbitrary nesting:
```
- folder-1
  - folder-2
    - file-1.md
    - file-2.md
- folder-3
  -file-3.md
- file-4.md
```
All these md files successfully generate their respective pages.

But I don't know how to go about constructing dynamic navigation page based on this file structure, so that whenever this structure changes, the navigation page changes "by itself":

- folder 1
  - folder 2
    - file 1
    - file 2
- folder 3
  - file 3
- file 4

Could someone point me in the right direction? Thanks in advance!!!

**Comment by mpodlasin** [comment]
![Screenshot from 2019-12-29 20-12-40](https://user-images.githubusercontent.com/7916523/71561512-bd158380-2a77-11ea-923e-80d229ff07bc.png)

My problem is that I cannot easily retrieve a nested tree representing file system structure.

**Comment by jonniebigodes** [comment]
@mpodlasin i've picked up on your issue and i think i have a answer for you. Here are the steps taken to try and solve your issue.

- Created a new Gatsby site with the default blog starter.
- Created a folder structure to replicate yours.
- Created a new page with the following content inside:
```javascript
import React from "react"
import { graphql } from "gatsby"
import Bio from "../components/bio"
import Layout from "../components/layout"
import SEO from "../components/seo"

class TestNavigation extends React.Component {
  render() {
    const { data } = this.props
    const listofFolders = data.allDirectory.edges

    return (
      <Layout
        location={this.props.location}
        title={"testing folder navigation"}
      >
        <SEO title="Navigation" />
        <Bio />
        <div
          style={{
            display: "flex",
            margin: "0 auto",
            flexDirection:'column',
            alignContent:'center',
            justifyContent:'space-around'
          }}
        >
          <div>
              
            {listofFolders.map(({ node }) =>
              node.relativeDirectory === "" ? (
                <div>
                  <p>{node.relativePath}</p> <p>is a root folder</p>
                </div>
              ) : (
                <div>Folder: {node.base } is a child of {node.relativeDirectory}</div>
              )
            )}
          </div>
          <div>
            <h3>this is the direct output of the query </h3>
            <pre>{JSON.stringify(listofFolders, null, 2)}</pre>
          </div>
        </div>
      </Layout>
    )
  }
}

export default TestNavigation

export const pageQuery = graphql`
  query {
    allDirectory(filter: {sourceInstanceName: {ne: "assets"}}) {
      edges {
        node {
          relativeDirectory
          relativePath
          base
        }
      }
    }
  }
  
`
```

Key thing to take from this, is the slight change to the query that was introduced it will give probably a bit more of information that you actually need.

I've setup a repo [here](https://github.com/jonniebigodes/gatsby_markdown_navigation) with the code, should you be interested in checking it out. 

Feel free to provide feedback so that we can close this issue, or continue to work on it until we do find a suitable solution.

**Comment by mpodlasin** [comment]
@jonniebigodes thank you for you answer!

I haven't run the snippet yet, but just looking at it, it seems it will just give me a flat list of directories?

In order to create a nested list, which is what I want, I would have to make a lot of effort to parse url's to find out which directory is the child of which one?

Unless I am missing something. I will run the snippet and get back to you!

**Comment by wardpeet** [comment]
Hey @mpodlasin. This is not natively supported in gatsby. It's possible with our APIs to build a structure with custom types but it's going to be tricky. Checkout https://www.gatsbyjs.org/docs/schema-customization/ for more information on how to create custom types.

My solution if you're not really in the graphql space yet, you can move this structure into json by traversing your directory manually and use the json inside your pages instead.

Does that make sense?

**Comment by mpodlasin** [comment]
@wardpeet I am ok with closing this issue.

I used yaml file do define my catalogues structure.

It's kind of double the work, but it works and arguably has other benefits, like explicitly defining order of files.

I guess it's just weird that in the docs it's not clearly explained what are the good practices on creating menus and tables of contents, unless I missed something?

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by brootle** [comment]
So looks like everybody should invent their own way of generating menus based on nested directory structure? why not make is as native Gatsby feature? I bet the demand for this is high!

**Comment by acuthbert** [comment]
Yeah I arrived here after some searching for this. If you're creating anything more than a basic blog with gatsby this is going to be a question we all ask. I'm surprised it's not covered in the excellent documentation. Even if it said it's not possible or not easy - it would save a lot of wasted time hunting.

**Comment by brootle** [comment]
I made some walk around by building menu tree parsing urls generated for each node... It would be good if Gatsby was at least generating an object that represents posts tree, why not?

**Comment by acuthbert** [comment]
> I made some walk around by building menu tree parsing urls generated for each node... It would be good if Gatsby was at least generating an object that represents posts tree, why not?

@brootle how would you feel about posting a snip or a gist for that? I'd be interested to see how you tackled it. I was thinking of trying to mine the graphql data for a flat list of all pages with their path - I was then going to split that up using a forward slash and then manipulate into a tree structure. I'm interested to see if you did something similar?

**Comment by brootle** [comment]
@acuthbert yes, I did exactly same thing! Looked like most easy and straight forward approach to me and my file structure was only 4 level deep, I mean the longest url looks like this /folder/folder/folder/post/ where post is generated based on post.md and I am not sure if this is mentioned in the docs, but you can get url like /folder/folder/folder/ by simply creating index,md file inside /folder/folder/folder/, so you kind of have index file for each folder as well and that can be some blog category.... For file structure that can go deep any level, I would use recursion to analyze urls to build the tree

**Comment by acuthbert** [comment]
Thanks @brootle - any chance you could share the graphql you used to get the data?

**Comment by brootle** [comment]
@acuthbert I just used title from frontmatter to generate user-friendly name for the menu item, basically I needed this graphql request just to get the list of urls of all markdown documents
`{
  allMarkdownRemark {
    totalCount
    edges {
      node {
        id
        frontmatter {
          title
        }
        fields {
          slug
        }
      }
    }
  }
}
`

**Comment by JacksonMalloy** [comment]
This was my solution to dynamically generate navigation (only works 2 levels deep). 
**Not a great solution but it works for me**

Figured I'd share how I did it. 

graphql query:
```
allFile(filter: { sourceInstanceName: { eq: "pages" }, name: { regex: "/^(?!index|404).*$/" } }) {
...
}
```

Logic to structure data -
```
export const getTreeItems = (data: { node: any }[]) => {
  // Create array of nodes
  const getBaseDirectories = (data: { node: any }[]) => {
    let baseDirectories: any[] = []

    data.forEach(({ node }) => {
      baseDirectories.push(node)
    })

    return baseDirectories
  }

  const baseDirectories = getBaseDirectories(data)

  // Set up data structure to include relativeDirs array
  const configureRelativeDirectory = () => {
    return baseDirectories.map(({ name, childMdx, relativeDirectory }) => {
      return {
        name,
        frontmatter: childMdx ? childMdx.frontmatter : null,
        relativeDir: relativeDirectory.substring(relativeDirectory.lastIndexOf('/') + 1),
      }
    })
  }

  const directoryList = configureRelativeDirectory()

  const configuredDirectoryList = directoryList.map((item, index, array) => {
    const node = array
      // Filter children matching relative directories
      .filter((child) => {
        return child.relativeDir === item.name
      })
      // Append children array to first level
      .map((firstChild) => {
        // Filter children matching relative directories
        const node = array
          .filter((child) => {
            return child.relativeDir === firstChild.name
          })
          // Append children array to second level
          .map((child) => {
            return { ...child, children: [] }
          })

        return { ...firstChild, children: node }
      })

    const newItem = { ...item, children: node }

    return newItem
  })

  const filteredDirectories = [
    { name: 'home', frontmatter: null, relativeDir: '', children: [] },
    ...configuredDirectoryList.filter((dir) => {
      // Remove copies of directorys at base level
      return !dir.relativeDir && dir.children.length
    }),
    { name: 'contact', frontmatter: null, relativeDir: '', children: [] },
  ]

  return filteredDirectories
}
```

Should output an array of objects with children arrays.
