### ISSUE TITLE
Hot Reloading not working out of the box (with start template)?

### ISSUE THREAD

**Issue by AidanRRR** [gatsbyjs/gatsby#20339]
### Steps to reproduce

Gatsby starter template & Gatsby develop

### Expected result

On changing the styling / content of a component the webpage should refresh itself.

### Actual result

Page is not refreshed. Manually pressing reload updates the content.

### Environment

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Users\arypens\AppData\Roaming\npm\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12 

After reading through the documentation, hot reloading seems to be shipped with Gatsby? When opening the developer tools in Chrome I do see:
' gatsby react-hot-loader react-🔥-dom patch is not detected '. Do you have to install something locally?

**Comment by AidanRRR** [comment]
It does work on my home computer and laptop.

**Comment by jonniebigodes** [comment]
@AidanRRR see #11934 if it helps

**Comment by AidanRRR** [comment]
> @AidanRRR see #11934 if it helps

It does not.. Might be a problem with my computer. Thanks for the tip though!

**Comment by sidharthachatterjee** [comment]
Hot reload _should_ (_and does_) work just fine. Just tried it out. 

@AidanRRR Does updating to the latest version of `gatsby` help?

**Comment by AidanRRR** [comment]
Updated all the packages, still not working.

**Comment by lestgabo** [comment]
@AidanRRR 
What I did was do `gatsby build`
I dont know why, but it makes hot reloading work on `gatsby develop` after doing gatsby build.
source: https://github.com/gatsbyjs/gatsby/issues/13918#issuecomment-493997902

**Comment by holylander** [comment]
Hi friends!

Im running `gatsby develop` on windows. After trying many things, including wsl, npm clenaup etc, I realized that my antivirus _sophos_ was blocking the webpack hot reload socket `__webpack_hmr`. 

> All I had to do is to disable the antivirus for a while. ( You are free to uninstall it or maybe change to another one ).

hope it works for you ;)

**Comment by carljustineoyales** [comment]
having the same problem firefox displays an HMR error

![image](https://user-images.githubusercontent.com/51884760/109704965-2fc94400-7bd2-11eb-8ddf-ed9d80b3d1aa.png)

however running it in incognito in chrome fixed the issue. I'm new to gatsby anyone here why is it working only in incognito?
