### ISSUE TITLE
Tips on organising a Gatsby project

### ISSUE THREAD

**Issue by PolGuixe** [gatsbyjs/gatsby#2034]
Hey, I am having some trouble with my folder structure. 

I like to structure my pages with the following way:
```
page1
    | ----- index.js
    | ----- page1.jsx
    | ----- styles.js  
    | ----- other page 1 related code
```

This approach doesn't work with the Gatsby `/src/pages/` API. Hence I have to do the following?

```
src/
  | ----- hidden/
  |               | ------ page1/
  |               | ------ page2/
  |
  | ----- pages/
  |               | ----- page1.js    // Here I import page1
  |               | ----- page2.js   // Here I import page2
```

Then I can't export graphQL queries from  e.g.`src/hidden/page1/page1.jsx`. I have to do it from `src/pages/pages1.js`.

How do you manage "complex" pages?

**Comment by brandonmp** [comment]
afaik only top-level components (ie pages & templates) support graphql queries atm. 

one dev's 'complex' is another's side-project, so hard to say for sure what'll help you, but ultimately i think the solutions on the table are the same that you'd consider for a vanilla react project to avoid the tedium of passing props/state down thru a dozen children.

that is: 

- you could use redux (or some other state management library) & hydrate the store @ the pages/ level component, then just `connect()` the children you care about

- make generous use of the spread operator & pass props down the chain, picking-off at the component level (`{...props}`)

- make a flatter app :)

**Comment by KyleAMathews** [comment]
People often use a `components` directory for shared components. If you want to put other JS files in `src/pages` that *shouldn't* be turned into pages, you can start the filename with an underscore e.g. `_not-a-page.js`.
