### ISSUE TITLE
Upgrade emotion to v11

### ISSUE THREAD

**Issue by stramel** [gatsbyjs/gatsby#20356]
## Summary

Just wanted to bring up awareness that Emotion has started to release some `next` builds for v11. It sounds like it _should_ be coming in the next month for official release.

### Motivation

`docz` currently utilizes `gatsby-plugin-emotion` and I'm trying to get `docz` bumped to v11 as soon as it releases a stable release.

**Comment by DSchau** [comment]
@stramel presumably this is specific to `gatsby-plugin-emotion`?

Have you seen any indication as to whether there will be breaking changes in this release?

For context, here's the [Emotion 11 milestone](https://github.com/emotion-js/emotion/milestone/1)

**Comment by stramel** [comment]
@DSchau You are correct, it should be specific to `gatsby-plugin-emotion`. 

I think there will be some but waiting for the official release to see their final result. They have some breaking changes in their Typescript definitions, moved theming into the core, and are discussing renaming the packages.

I'm good with `status: blocked` for now. I will update here again when the official release lands.

Thank you for the quick response!

**Comment by dlimx** [comment]
One big change so far is renaming `@emotion/core` to `@emotion/react` if anyone has experimented with the @next builds

**Comment by stramel** [comment]
yeah, I have a few PRs to various libs that are utilizing `@emotion`. The library renaming seems to be the major change.

**Comment by LekoArts** [comment]
There shouldn't be a need to have this open so long. We'll update it when they release v11.
