### ISSUE TITLE
How to enable redux-devtools

### ISSUE THREAD

**Issue by arekkas** [gatsbyjs/gatsby#2035]
I would like to take a look at the internal state of gatsby. Is it possible to enable redux-devtools in devmode?

**Comment by KyleAMathews** [comment]
Yeah! Check out the how to contribute page on gatsbyjs.org

**Comment by arekkas** [comment]
Sorry, I meant if its possible to get access to the gatsby store when running `gatsby development` - I basically want to debug a little bit and it would be helpful to be able to explore the store.

**Comment by KyleAMathews** [comment]
Ah yeah the store object is passed to all the gatsby-node APIs

**Comment by arekkas** [comment]
Ok thanks - just to reiterate, it's then (I assume) not possible to connect redux devtools when running `gatsby development`?

**Comment by KyleAMathews** [comment]
https://www.gatsbyjs.org/docs/how-to-contribute/#redux-devtools

**Comment by arekkas** [comment]
Thanks!
