### ISSUE TITLE
Question about siteMetadata in gatsby-config.js

### ISSUE THREAD

**Issue by zhandosweb** [gatsbyjs/gatsby#20358]
Hello!

Please, let me ask one question about `siteMetadata ` in gatsby-config.js file. 

In siteMetadata can I set URL-s for my social profiles (like twitter, facebook etc). Then get this data when I need using GraphQL. 

Will it be the correct way? Or for social profile URL-s, I should create a separate component?

**Comment by jonniebigodes** [comment]
@zhandosweb yes, you can set up twitter,linkedin, facebook and other urls. If you take a look at the [blog starter](https://github.com/gatsbyjs/gatsby-starter-blog) it has setup some social network elements inside `gatsby-config.js` and in the [bio component](https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/src/components/bio.js) you have a way to query for the data.

Normally from what i've seen people tend to stick to the approach of putting any social network references in the footer, some inside a dedicated page, it's all up to you on how you want to build up the site and how to display the information
