### ISSUE TITLE
[gatsby-image] with gradient image 

### ISSUE THREAD

**Issue by t-zander** [gatsbyjs/gatsby#20355]
## Description

Gradient image is messed up when using `BackgroundImage` component + .png image + `GatsbyImageSharpFluid_withWebp` fragment

### Steps to reproduce

Create any gradient image with some overlay shapes. When you try to use it with gastby `BackgroundImage` component you will see lines instead of smooth gradient.
E.g.
[this gradient image from figma](https://www.figma.com/file/LhPrTbocYv9n0ubEccT0FX/Untitled?node-id=0%3A1)

Will loose smooth gradient and look like this
https://prnt.sc/qhxisy

Full code 
```
const data = useStaticQuery(graphql`
    query {
      desktop: file(relativePath: { eq: "test.png" }) {
        childImageSharp {
          fluid(quality: 100, maxWidth: 1980) {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
      }
    }
  `);

  return (
    <BackgroundImage
      Tag="div"
      fluid={data.desktop.childImageSharp.fluid}
      className={classes.root}
    >
      <p>Test</p>
    </BackgroundImage>
```

Styling is as follows:
```
.root{
  width: 100%;
  height: calc(100vh - 100px);
  background-position: center center;
  background-size: cover;
}
```
For some reason if I use `GatsbyImageSharpFluid` instead of  `GatsbyImageSharpFluid_withWebp` it seems to work fine. And I cannot find any description for these fragments.
Any thoughts on why it happens?
I agree that I may use plain css gradient, but when there are many shapes it may be useful to have it as .png image.

### Expected result

Colors should be preserved

### Actual result

Image colors were broken

### Environment
 System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-background-image: ^0.9.12 => 0.9.12
    gatsby-image: ^2.2.37 => 2.2.37
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sass: ^2.1.26 => 2.1.26
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5
    gatsby-source-filesystem: ^2.1.40 => 2.1.40
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7
  npmGlobalPackages:
    gatsby-cli: 2.8.16

**Comment by freiksenet** [comment]
Hi!

[`gatsby-background-image`](https://github.com/timhagn/gatsby-background-image) isn't an official Gatsby plugin. You should re-create this issue in their repository.

Thank you very much! :purple_heart:
