### ISSUE TITLE
gatsby-remark-autolink-headers doesn't work properly inside relatively positioned container

### ISSUE THREAD

**Issue by Rikpat** [gatsbyjs/gatsby#20362]
## Description

If generating pages from markdown and having a relatively positioned container in template that is generated into, window doesn't scroll to header, because element.offsetTop takes offset from relative parent.

### Steps to reproduce

Place generated html inside a container with relative possition and offset from document top

Here's a codesandbox

[![Edit gatsby-remark-autolink-headers-problem-example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gatsby-remark-autolink-headers-problem-example-hi4m7?fontsize=14&hidenavigation=1&theme=dark)

### Expected result

Window should scroll to header on click on link

### Actual result

Window doesn't scroll to header, it only scrolls down to distance between header and relative ancestor.

### Fix

I'll be publishing PR that gets the distance from document top instead of parent top shortly

**Comment by freiksenet** [comment]
Thank you for a great bug report with a reproduction! 

Would you like to make a PR that will fix this issue? We would really appreciate that.

Thank you! :purple_heart:

**Comment by Rikpat** [comment]
@freiksenet I already did, look at #20363. It works for me locally using patch-package.
