### ISSUE TITLE
Unable to set layout id

### ISSUE THREAD

**Issue by arekkas** [gatsbyjs/gatsby#2036]
It is not possible to set the layout id as shown in [this example](https://www.gatsbyjs.org/docs/node-apis/#createLayouts):

```
exports.createLayouts = ({ graphql, boundActionCreators }) => {
 boundActionCreators.createLayout({
   id: 'custom',
   component: path.resolve(`src/templates/custom-layout.js`),
  })
}
```

It is not possible because the id is *always* generated from the filename, see [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/actions.js#L127-L128):

```
actions.createLayout = (layout, plugin = ``, traceId) => {
  layout.id = path.parse(layout.component).name
```

Getting this working is pretty easy:

```
actions.createLayout = (layout, plugin = ``, traceId) => {
  layout.id = layout.id || path.parse(layout.component).name
```

**Comment by jquense** [comment]
I _feel_ like this was because we decided exposing the `id` wasn't necessary or useful to a consumer of API, and maybe just didn't update the docs. But I could be way off base...

**Comment by arekkas** [comment]
Being able to define an id that is not based on the filename is incredible useful - especially if the layout is loaded from eg npm.

**Comment by jquense** [comment]
The id is really only used internally to build a hash and a path is always going to be unique even if it's from an npm package. Can you talk about why you'd want to know about it or change it?

**Comment by arekkas** [comment]
Yes, I want to set the layout of pages and for that I want to know the ID which might be generated automatically as it is loaded from a database in `createLayouts`.

**Comment by KyleAMathews** [comment]
Oh interesting. Yeah that makes sense then. Happy to take a PR then that uses an I'd if it's passed in. Also please update the docs to indicate the id is optional and generally not needed.

**Comment by arekkas** [comment]
Perfect, I will!

**Comment by arekkas** [comment]
Done -> https://github.com/gatsbyjs/gatsby/pull/2046 :)
