### ISSUE TITLE
styled-components not being applied on `gatsby-develop`

### ISSUE THREAD

**Issue by pedroapfilho** [gatsbyjs/gatsby#20374]
## Description

Styles using `gatsby-plugin-styled-components` not being applied locally when running `gatsby-develop`, but working when opening from the `/public` folder, or after deployed (online).

### Steps to reproduce

This one is the theme where the gatsby-plugin-styled-component is: https://github.com/pedroapfilho/gatsby-theme-awesomeness

This one is the website where I used this theme: https://github.com/pedroapfilho/website

To run the theme or/and the website you just have to run `yarn` and then `yarn develop`.

### Expected result

The website should have all the styles applied.

### Actual result

No styles from any `styled-component` are rendered, only on the "built" versions.

### Environment

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/n/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 70.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.17 => 2.18.17 
    gatsby-plugin-manifest: ^2.2.34 => 2.2.34 
    gatsby-source-filesystem: ^2.1.43 => 2.1.43 
    gatsby-theme-awesomeness: ^0.0.18 => 0.0.18

**Comment by kephin** [comment]
Try with Chrome incognito https://github.com/gatsbyjs/gatsby/issues/20111

**Comment by pedroapfilho** [comment]
Thanks! That's exactly what was happening to me. I didn't find this issue before because I was searching for the wrong keywords. Thanks for your help!
