### ISSUE TITLE
Link on the Bottom Right corner of "Was this doc helpful to you?" 

### ISSUE THREAD

**Issue by aryamanpuri** [gatsbyjs/gatsby#20375]
https://www.gatsbyjs.org/tutorial/part-two/

It should be of small size as it is covering area of Blog also.
There should be close ion for that too.
It is just an Enhancement.

**Comment by srs231198** [comment]
Do you still require someone to work on this?

**Comment by jonniebigodes** [comment]
@srs231198 probably yes. If that's not the case and preparing for future contributions it would a good thing that you read up on [contribution documentation](https://www.gatsbyjs.org/contributing/how-to-contribute/) and go from there. Also check out the issues labeled "Good First issue" to get some bearings on what needs help and if you're able go for it.

**Comment by aryamanpuri** [comment]
@srs231198 @jonniebigodes I guess it is corrected, so I am closing this issue .
