### ISSUE TITLE
OutboundLink Component Example

### ISSUE THREAD

**Issue by kayali1411** [gatsbyjs/gatsby#20370]
How I can use `OutboundLink` component from `gatsby-plugin-google-analytics` module without reloading the page.

OutboundLink example from gatsby doc [link to example](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/#outboundlink-component)
```
<OutboundLink href="https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/">
      Visit the Google Analytics plugin page!
</OutboundLink>
```

**Comment by freiksenet** [comment]
Hi!

`OutboundLink` is supposed to be used for links that are external to the website, so it's not possible to load them without page reload. I wonder if you could describe what you are trying to do? GA should be able to track url changes inside the website without any need for `OutboundLink`.

**Comment by kayali1411** [comment]
Hi @freiksenet 
thanks for the explanation. I want to track users clicks on "add to cart" button
