### ISSUE TITLE
Recipe for adding Google Analytics

### ISSUE THREAD

**Issue by laurieontech** [gatsbyjs/gatsby#20384]
## Summary

[gatsby-plugin-google-analytics](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/?=) is a very popular plugin for Gatsby sites. It could use a [recipe](https://www.gatsbyjs.org/docs/#go-further) for setting it up and generating a tracking ID to use.

What problem(s) did you run into that caused you to request additional documentation? What questions do you think we should answer? What, if any, existing documenation relates to this proposal?

Some recommended topics to cover:

- Creating a domain
- Linking that domain to Google analytics admin
- Getting the analytics tracking id
- Using that id in the plugin

### Motivation

Why should we document this and who will benefit from it?
This is a common use case and it would be helpful for new users to have a single place to figure out how to navigate the various steps.

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) in the "Recipes" section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #20384" in the pull request description

**Comment by srs231198** [comment]
I would love to work on this... is it still available?

**Comment by laurieontech** [comment]
It is! Thanks @srs231198 :)

**Comment by marcysutton** [comment]
Hi @srs231198, checking up on this issue -- are you still interested in working on it? Let us know!

**Comment by marcysutton** [comment]
This issue is still open, so I've added the help wanted label to it for now. If anyone would like to work on it let us know!

**Comment by jeffpascal** [comment]
Hello @marcysutton, i would like to work on this. I have already started.
I will go through:
Buying domain from AWS
Configuring Route 53
Adding the tracking id
Verifying the domain
Code

**Comment by laurieontech** [comment]
Sounds great @jeffpascal! I'll assign this to you then.

**Comment by marcysutton** [comment]
One suggestion I would make is to limit to what is essential and common to integrating Google Analytics into a Gatsby site, and make generous use of the Prerequisites section. E.g. there's multiple ways to set this up, and will someone be able to follow it if they aren't using AWS or S3?

**Comment by jeffpascal** [comment]
@marcysutton I understand.

**Comment by jeffpascal** [comment]
Hello @marcysutton https://www.gatsbyjs.org/docs/adding-analytics/ already talks about the essentials to integrating google analytics.

I guess i should focus on the creation of the domain and verification?

**Comment by marcysutton** [comment]
Following up on this, my apologies for the delay! @jeffpascal this issue is about creating a recipe, while that doc is a Reference Guide. They are different formats, and a recipe is meant to be short and actionable (like a stripped-down tutorial with only the essentials). You can read more about the recipe format here: https://www.gatsbyjs.org/contributing/docs-templates/

**Comment by jeffpascal** [comment]
@marcysutton got it. Will be done soon.

**Comment by laurieontech** [comment]
This is handled in the recently merged PR! So going to close this issue.
