### ISSUE TITLE
[gatsby-image] Cannot add classes directly to image

### ISSUE THREAD

**Issue by panzarino** [gatsbyjs/gatsby#20380]
## Summary

Currently it does not appear that there is a way to apply classes to the actual `img` element with the gatsby-image library. For my project requirements, I must be able to apply classes to the actual `img` element. Currently it seems like classes can only be applied to the wrapping element and the placeholder. Is there a workaround that I'm not seeing here? I feel like this would be a very useful feature for many users and can be implemented quite easily.

**Comment by jonniebigodes** [comment]
@panzarino have you taken a look at [this](https://www.gatsbyjs.org/docs/gatsby-image/#gatsby-image-props) to see if it helps in you case?

**Comment by panzarino** [comment]
@jonniebigodes after looking again I realize that I misunderstood what placeholder image meant. Closing.
