### ISSUE TITLE
docker ubuntu:latest error

### ISSUE THREAD

**Issue by djkloop** [gatsbyjs/gatsby#20393]
## Description

```sh
 It feels like a sharp problem.
```

### Steps to reproduce
```sh
# docker file 
FROM ubuntu:latest as builder

RUN apt-get update \
    && apt-get install -y python2.7 \
    && apt-get install -y python3.7 \
    && apt-get install -y python3-pip \
    && apt-get install -y libvips libvips-dev libvips-tools \
    && apt-get install -y glib2.0-dev \
    && apt-get install -y python-pip python-dev \
    && apt-get install -y curl

RUN rm /bin/sh && \
	ln -s /bin/bash /bin/sh

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN npm --version
RUN node -v

RUN npm i -g yarn

RUN npm i -g gatsby-cli
# Pull git project operation
...

RUN cd /tmp && yarn

// error

```

### Expected result
```sh
  Be able to install successfully
```
### Actual result

![image](https://user-images.githubusercontent.com/21050914/71720097-6505c500-2e5b-11ea-81eb-56498e33662f.png)

### Environment

```sh
gatsby-cli@latest
```

**Comment by DanielRuf** [comment]
Not a problem on the side of gatsby. Please report this at https://github.com/lovell/sharp-libvips/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by DanielRuf** [comment]
You might want to delete the mentioned incomplete tarball file.

**Comment by sidharthachatterjee** [comment]
Thanks @DanielRuf 🤗 

Closing this since it is upstream and the comment at https://github.com/lovell/sharp-libvips/issues/35 resolves it.
