### ISSUE TITLE
[gatsby-image] using gatsby-remark-images the placeholder never fades out

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#20408]
## Description

When using `gatsby-remark-images` and `gatsby-image`, the placeholder image never fades out, which is a problem for transparent images.

It looks like this:

<img width="788" alt="Screen Shot 2020-01-03 at 12 33 40 PM" src="https://user-images.githubusercontent.com/163561/71747850-a67b7d80-2e25-11ea-9000-3ca98992e131.png">

I had to write extra code to hide the placeholders, which I _think_ Gatsby used to handle automatically in the past.

```js
useLayoutEffect(() => {
  const wrappers = document.querySelectorAll('.gatsby-resp-image-wrapper');

  wrappers.forEach(wrapper => {
    const img = wrapper.querySelector('img');
    const placeholder = wrapper.querySelector('span');

    img.addEventListener('load', () => (placeholder.style.opacity = 0));
  });
}, []);
```

After adding the above code to my post wrappers, I get the desired result:

<img width="721" alt="Screen Shot 2020-01-03 at 12 34 12 PM" src="https://user-images.githubusercontent.com/163561/71747910-c448e280-2e25-11ea-8273-11fd5c7c6593.png">

### Steps to reproduce

Add any transparent PNG to a markdown file.

### Expected result

Image should be visible with no placeholder below.

### Actual result

The placeholder remains visible.

### Environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 2.15.12 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 70.0.1
    Safari: 13.0.4
```

**Comment by LekoArts** [comment]
Maybe related https://github.com/gatsbyjs/gatsby/issues/11280

**Comment by dvrylc** [comment]
@jlengstorf I can't seem to reproduce this, are you still able to?

**Comment by danabrit** [comment]
Closing due to no response. If this is still a problem, please re-open.

**Comment by jlengstorf** [comment]
sorry, missed the original follow-up. yes, this seems to have been patched at some point earlier this year. thanks!

**Comment by CodeAndWeb** [comment]
I can still reproduce this issue in the current version.

  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1
    gatsby-plugin-mdx: ^2.1.0 => 2.1.0
    gatsby-plugin-sharp: ^3.1.2 => 3.1.2
    gatsby-remark-autolink-headers: ^3.1.0 => 3.1.0
    gatsby-remark-images: ^4.1.1 => 4.1.1
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
