### ISSUE TITLE
Running a Gatsby App from node_modules - "Generating SSR bundle failed"

### ISSUE THREAD

**Issue by puzzledbytheweb** [gatsbyjs/gatsby#20404]
Hello everyone!

I think I already read the relevant issues but I don't think they are the same problem.

What I'm trying to do is to run a Gatsby app that I've published to NPM from another project, that is after installing it. The idea is to build a generic Gatsby app and overwrite some components from the root project.

However I cannot even start a fresh Gatsby app from the node_modules by using this script:
`cd ./node_modules/mygatsbyapp && yarn start`

The error that is thrown is:
```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (31:4)

File: .cache/develop-static-entry.js:31:4
```

The line that causes the error has this code:
`<meta key="environment" name="note" content="environment=development" />`

The same project runs fine when I run it as a normal project (`cd mygatsbyapp && yarn start`)

EDIT:
This is my `gatsby info` output:
```
System:
    OS: Linux 5.2 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 3.8.1 - /usr/bin/python
  Browsers:
    Firefox: 71.0
  npmGlobalPackages:
    gatsby-cli: 2.8.22


```
Thanks and Happy new year!

**Comment by blakewilson** [comment]
Hey @puzzledbytheweb , I'm having the same exact issue you are. How did you resolve it?

**Comment by puzzledbytheweb** [comment]
> Hey @puzzledbytheweb , I'm having the same exact issue you are. How did you resolve it?

Hey @blakewilson, I had this problem when I was starting my app by doing:
```cd node_modules/my_app && yarn start ```  

I found out about themes and decided to go that way because it as much cleaner and with better support. I also encountered this error and found out that I got a similar error! In the end it was a naming problem as Gatsby requires that all themes start with "gatsby-theme".

When I was debugging this problem I think I've read some code in the build process that made it impossible to start a project from another location that wasn't the root, something to do with paths and such.

I would suggest you to try out the themes feature and be especially careful with your naming as I ended up losing a lot of time trying to debug something because of my tendency to give stupid names to my testing projects.

Hope you can solve it!
Cheers!

**Comment by blakewilson** [comment]
@puzzledbytheweb Gatsby Themes is exactly what I was looking for! Can't believe I haven't came across them yet. Thanks a lot for your response.

**Comment by obains** [comment]
@puzzledbytheweb thank you for your comment here - this really helped me as well. 
Much appreciated!

**Comment by appledevguru1226** [comment]
I have not to use gatsby-theme in my project.
But i have same error.
Can you inform the solution to fix this issue?

**Comment by obains** [comment]
If you're not running Gatsby then most likely you create a new issue and post your code, as it won't be related to this one.
