### ISSUE TITLE
gatsby-plugin-sitemap exclude not working 

### ISSUE THREAD

**Issue by keithpacana** [gatsbyjs/gatsby#20405]
Hi, so I'm using this plugin to generate my sitemap, but for some reason when I try to exclude one of my pages from the sitemap it still shows.

The page I'm trying to exclude is in src/pages/contact-success.
I've tried these strings of multiple paths in the exclude array: `/contact-success`, `/contact-success/index.html`, `/contact-success/*`, `src/pages/contact-success`, and `/pages/contact-success`, but none seem to work. Any ideas as to why this is?

**Comment by freiksenet** [comment]
Thank you for the issue!

I wounder if you could include a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)? We can't help you without more context. :purple_heart:

**Comment by ssolod** [comment]
make sure your `exclude` goes into `options`
```
{
      resolve: `gatsby-plugin-sitemap`,
      options: {
        exclude: [ 'here' ]
     }
}
```
myself made this typo by placing it one level up, spent some time debugging.

**Comment by keithpacana** [comment]
> make sure your `exclude` goes into `options`
> 
> ```
> {
>       resolve: `gatsby-plugin-sitemap`,
>       options: {
>         exclude: [ 'here' ]
>      }
> }
> ```
> 
> myself made this typo by placing it one level up, spent some time debugging.

ahh yeah saw this was my error too lol ty!

**Comment by cesarvarela** [comment]
In case someone comes here and copy/pastes this, the property is plural in v3 `excludes`:

```
{
      resolve: `gatsby-plugin-sitemap`,
      options: {
        excludes: [ 'here' ]
     }
}
```
