### ISSUE TITLE
Import of package in regular CSS breaks build, "cannot find module" on browser

### ISSUE THREAD

**Issue by stefanmaric** [gatsbyjs/gatsby#2041]
To replicate:

```shell
$ gatsby new tmp https://github.com/gatsbyjs/gatsby-starter-default
$ cd tmp
$ npm install --save normalize-css
$ npm install
$ mkdir src/css
$ echo '@import "normalize-css/normalize.css";' > src/css/new.css
$ echo 'body { color: red; }' >> src/css/new.css
```

Then you include `@import '../css/new.css'` in `src/layouts/index.js`.

If you run `npm run develop` works OK but a weird message prompts:

```shell
info bootstrap finished - 1.334 s

src/css/new.css
undefined [undefined]

 DONE  Compiled successfully in 3266ms                                                                                                                                                                                                11:06:07
```

Anyway, the real problem comes when you create the build, it succeeds normally, but this error appears in the browser console:

![image](https://user-images.githubusercontent.com/1009040/30168221-2369c30a-93bf-11e7-9c3d-b42b92bb0ab8.png)

In this case, the page renders and the styles are applied:

![image](https://user-images.githubusercontent.com/1009040/30168323-752c7ee4-93bf-11e7-9d35-e0e6305f0d64.png)

But in my real case, only `src/pages/index.js` renders, this error stops all other pages from rendering the page body (only the pieces of the layout are rendered).

Note: this doesn't happen if you `@import` other CSS files in your `src/`, only nodejs packages.

**Comment by jquense** [comment]
can you try `@import "~normalize-css/normalize.css"` which is the "Webpack Way™"

**Comment by stefanmaric** [comment]
> can you try @import "~normalize-css/normalize.css" which is the "Webpack Way™"

That gives me:

```

src/css/new.css
1:1	⚠  Failed to find '~normalize-css/normalize.css'
    in [ 
        /home/sam/Code/tmp/src/css
    ] [postcss-import]

 WARNING  Compiled with 1 warnings                                                                                                                                                                                                    14:24:12

 warning  in ./src/css/new.css

postcss-import: /home/sam/Code/tmp/src/css/new.css:1:1: Failed to find '~normalize-css/normalize.css'
    in [ 
        /home/sam/Code/tmp/src/css
    ]

 WAIT  Compiling...                                                                                                                                                                                                                   14:24:12

 WARNING  Compiled with 1 warnings                                                                                                                                                                                                    14:24:12

 warning  in ./src/css/new.css

postcss-import: /home/sam/Code/tmp/src/css/new.css:1:1: Failed to find '~normalize-css/normalize.css'
    in [ 
        /home/sam/Code/tmp/src/css
    ]
```

**Comment by stefanmaric** [comment]
To clarify: adding the tilde fixes the build, but makes the develop server unusable.

**Comment by stefanmaric** [comment]
> tilde fixes the build

I spoke too son; it removes the error from the gatsby-starter example and ti seems to work but in my project, even tho it removes the error, does **not** do what I expect it to do: place the content of the dependency where the import is declared, and then pass the concatenated file through postCSS.

**Comment by m-allanson** [comment]
This sounds like the same issue as #1086

**Comment by KyleAMathews** [comment]
Closing this issue as it's fairly old. If you have additional problems in this area, please open a new issue!
