### ISSUE TITLE
Add warning to gatsby develop if window is not defined

### ISSUE THREAD

**Issue by bowenac** [gatsbyjs/gatsby#20422]
## Summary
Not sure if this is possible but adding a warning to gatsby develop if window is not defined could be useful to some.

## Relevant information
Forgive me if this is obvious, I've just started my journey learning react and gatsby and so far I'm having a great time, however I thought this was very strange. I was playing around today on a project and was using the below code which worked on local dev.

```
let parentClass = ''
if (window.location.pathname === `${parentlink}${edge.node.childMarkdownRemark.fields.slug}/`) {
    parentClass = 'active'
}
```

I then committed to github which then deploys to netlify, I was watching the netlify build/deploy log and I received the following error...

**error "window" is not available during server side rendering.**

It took me a while to figure out why this was... I thought to myself, why would this work on dev but not on a build. After doing some research and talking to some people on gatsby discord, someone pointed me in the right direction... I then changed my code to the following, committed, and it deployed fine.

```
let parentClass = ''
if (typeof window !== `undefined`) {
    if (window.location.pathname === `${parentlink}${edge.node.childMarkdownRemark.fields.slug}/`) {
        parentClass = 'active'
    }
}
```

### Why was I doing this
If anyone is curious why I was even doing this you can see my commit here https://github.com/bowenac/gatsby-playground/commit/2e0d4d18ef340dcac611505cf8befb065be0b330 As I said I'm new to react and gatsby. I was trying to figure out a way I could add a class when a link with a hash was clicked. activeClassName="active" does not work on <Link> with hashtags. This is something that would only take like 3 lines of code in jQuery, but I could not figure out a solution for this... tried all sorts of different examples I was seeing. Then I said wait, I can use chrome tools react components view, and that is when I was like ok I could just check the location pathname if it matches this hashtag add this class etc. It worked, not sure if this was the "correct" solution to my problem, but it did work and does what I wanted. I just wasn't expecting to see an error during the build as I didn't see any issues during develop.

### Environment (local)

  System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-background-image: ^0.9.12 => 0.9.12
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5
    gatsby-remark-autolink-headers: ^2.1.21 => 2.1.21
    gatsby-remark-prismjs: ^3.3.28 => 3.3.28
    gatsby-remark-source-name: ^1.0.0 => 1.0.0
    gatsby-source-filesystem: ^2.1.40 => 2.1.40
    gatsby-transformer-remark: ^2.6.45 => 2.6.45
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7

**Comment by sidharthachatterjee** [comment]
Thank you for opening this @bowenac 

You're absolutely right. We should lint for `window` and other browser globals. Going further than what you described we should lint in all places other than `componentDidMount`, `useEffect` (and other client only code paths) 

I have a prototype of this as an eslint plugin on my local machine that I'll push up and only a PR so we can move forward with this. 

Let's track this in https://github.com/gatsbyjs/gatsby/issues/12769 (which describes this in more detail)

Closing this for now but thank you once again for being thoughtful enough to open an issue 🤗
