### ISSUE TITLE
How to change pages or urls in gatsby without Link component?

### ISSUE THREAD

**Issue by Prottoy2938** [gatsbyjs/gatsby#20435]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 

In gatsby official page theres a search bar which shows suggestions, and when user clicks on one,it changes pages. How can I change pages like that? I have form and when the form submits, I want redirect the user to the input value that they provided. How do I do that without Link component?

**Comment by TheFirstMe** [comment]
You want the pages to change based on the input value provided by the user?

**Comment by LekoArts** [comment]
Thank you for opening this!

You can use `navigate` to change pages programmatically:
https://www.gatsbyjs.org/docs/gatsby-link/#how-to-use-the-navigate-helper-function

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
