### ISSUE TITLE
[gatsby-transformer-remark] Question about using gray-matter vs remark-frontmatter

### ISSUE THREAD

**Issue by canibanoglu** [gatsbyjs/gatsby#20432]
I've been recently reading the documentation for `remark` and [`unifiedjs`](https://unifiedjs.com/) and trying to understand how that whole ecosystem works. I also stumbled on a package called `remark-frontmatter` which is a plugin that seems to parse frontmatter data as part of the markdown parsing/processing stage. 

But when I look at the source code for `gatsby-transformer-remark` I see that frontmatter data is handled by `gray-matter`. 

I haven't made a comparison of the APIs offered by both `gray-matter` and `remark-frontmatter` and I don't expect it would be a simple thing to start using `remark-frontmatter` instead but I'm curious about the decision here. Was/is there a specific reason for using `gray-matter` and not `remark-frontmatter`? Are there plans to make this more "uniform", for lack of a better term?

**Comment by freiksenet** [comment]
Thank you for your question!

We are using `graymatter`, because back in April 2017 `remark-frontmatter` didn't exist yet. I don't think we have ever evaluated moving to `remark-frontmatter`.
