### ISSUE TITLE
RFC: Check-in dependencies with yarn offline cache 

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#2043]
https://yarnpkg.com/blog/2016/11/24/offline-mirror/

Anyone done this? Sounds pretty nice as would speed up bootstrap a lot (maybe?).

**Comment by jquense** [comment]
We should see what yarn@1.0.0 and workspaces feels like first maybe. I think with hot cache that will be nice a quick as well

**Comment by KyleAMathews** [comment]
It'd be cool to do more research this and evaluate how helpful it is but closing this now.
