### ISSUE TITLE
minimize bundle => use named or path imports?

### ISSUE THREAD

**Issue by BernardA** [gatsbyjs/gatsby#20436]
## Summary
I am using `react-material-ui` and I am not sure what's the best way to import modules in order to minimize bundle.

Should I do like this: path import 

      import Table from '@material-ui/core/Table';
      import TableBody from '@material-ui/core/TableBody';
      import TableCell from '@material-ui/core/TableCell';

or rather: named imports

      import { Table, TableBody, TableCell } from '@material-ui/core';

## Relevant information

According to [this link](https://material-ui.com/guides/minimizing-bundle-size/) one should prefer named imports, provided that one uses a Babel plugin. That's what I normally do in my 'regular' React apps.

As I am not sure if Gatsby uses the Babel plugin internally, I am asking you.

### Environment (if relevant)

         System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
    Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Languages:
    Python: 2.7.16 - /usr/bin/python
    Browsers:
    Chrome: 79.0.3945.88
    Firefox: 65.0.1
    Safari: 13.0.4
    npmPackages:
    gatsby: ^2.18.2 => 2.18.2
    gatsby-cli: ^2.6.4 => 2.6.4
    gatsby-image: ^2.2.33 => 2.2.33
    gatsby-link: ^2.2.24 => 2.2.24
    gatsby-plugin-create-client-paths: ^2.1.17 => 2.1.17
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-manifest: ^2.2.29 => 2.2.29
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-offline: ^3.0.22 => 3.0.22
    gatsby-plugin-react-helmet: ^3.1.15 => 3.1.15
    gatsby-plugin-sass: ^2.1.23 => 2.1.23
    gatsby-plugin-sharp: ^2.3.2 => 2.3.2
    gatsby-source-filesystem: ^2.1.38 => 2.1.38
    gatsby-source-graphql: ^2.1.24 => 2.1.24
    gatsby-transformer-sharp: ^2.3.5 => 2.3.5

**Comment by rubas** [comment]
Install `"babel-plugin-transform-imports` and add the following to your `gatsbyjs-node.js` and you're good.

````
exports.onCreateBabelConfig = ({ actions }) => {
  // https://material-ui.com/guides/minimizing-bundle-size/
  actions.setBabelPlugin({
    name: "babel-plugin-transform-imports",
    options: {
      "@material-ui/core": {
        transform: "@material-ui/core/esm/${member}",
        preventFullImport: true,
      },
      "@material-ui/icons": {
        // Use "transform: '@material-ui/icons/${member}'," if your bundler does not support ES modules
        transform: "@material-ui/icons/esm/${member}",
        preventFullImport: true,
      },
    },
  })
}

**Comment by LekoArts** [comment]
Thank you for opening this!

> For convenience, Material-UI exposes its full API on the top-level material-ui import. If you're using ES6 modules and a bundler that supports tree-shaking (webpack >= 2.x, parcel with a flag) you can safely use named imports and expect only a minimal set of Material-UI components in your bundle

Gatsby supports the tree-shaking that is mentioned in this quote. Since Material-UI doesn't use CommonJS (like mentioned in this issue: https://github.com/gatsbyjs/gatsby/issues/7581) it'll work fine.

https://github.com/mui-org/material-ui/blob/master/babel.config.js#L3-L17

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by valoricDe** [comment]
Hey folks, in this document (https://github.com/mui-org/material-ui/blob/master/docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md) it says tree shaking is only performed on production mode. So I guess it is always recommended to use @rubas snipped, right?

**Comment by shinaBR2** [comment]
> Hey folks, in this document (https://github.com/mui-org/material-ui/blob/master/docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md) it says tree shaking is only performed on production mode. So I guess it is always recommended to use @rubas snipped to also profit of faster initial bootup in gatsby develop, right?

@valoricDe You can use that snipet to help reducing load time for **development** only. Production is **automatically optimized**.
