### ISSUE TITLE
[gatsby-plugin-netlify-cms] customize webpack `actions` not exposed, core-js not found

### ISSUE THREAD

**Issue by joshdcomp** [gatsbyjs/gatsby#20442]
Hi! Thank you for this great plugin, it's opened a lot of possibilities for my team

## Description

From what I can tell, the `customizeWebpackConfig` option for `gatsby-plugin-netlify-cms` does not pass the `actions` object, ostensibly meaning that the plugin's method can't actually mutate the Webpack config (I could be mis-reading the file, forgive my ignorance if that's the case). 

Further, it appears that whatever changes _would_ have been made if `actions.replaceWebpackConfig` or `actions.setWebpackConfig` were called would be [overwritten by the next stanza](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify-cms/src/gatsby-node.js#L261) where the plugin itself calls `setWebpackConfig`.

The end result for me is that Gatsby throws this error (`@uitk/ui-toolkit-react` is a privately-hosted React component lib):

```bash
 ERROR  Failed to compile with 3 errors                                                                                                                                  6:07:19 PM
⠀
This dependency was not found:
⠀
* core-js/stable in ./node_modules/@uitk/ui-toolkit-react/dist/wip/luna-container/LunaContainer.jsx, ./node_modules/@uitk/ui-toolkit-react/dist/wip/luna-icon/LunaIcon.jsx and 1 other
⠀
To install it, you can run: npm install --save core-js/stable
```

As a side note: It's also completely possible I'm using core-js incorrectly—all components in `@uitk/ui-toolkit-react` import `core-js/stable` at the top. If it's the case that I'm doing this wrong, could someone please point me in the right direction in terms of how I _should_ apply ES6 pollyfills in a component lib?

The fix outlined in #17136 works for the rest of my Gatsby site (site compiles without warnings if I remove the plugin), but I seemingly cannot apply the `config.resolve.alias` patch to Netlify CMS's webpack config (not sure about the best way to verify)

### Steps to reproduce

- create a NetlifyCMS previewTemplate which uses a React component that imports `core-js/stable`
- include `gatsby-plugin-netlify-cms` in the `gatsby-config` plugins array
- `$npm run dev`

### Expected result

I'd expect the `config.resolve.alias` patch to resolve `core-js/stable` for netlify-cms

### Actual result

Gatsby throws an error saying it can't resolve `core-js/stable` 

### Environment

```

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.31 => 2.18.17 
    gatsby-cli: ^2.8.22 => 2.8.22 
    gatsby-image: ^2.0.23 => 2.2.37 
    gatsby-plugin-mdx: ^1.0.64 => 1.0.64 
    gatsby-plugin-netlify-cms: ^4.1.6 => 4.1.33 
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.1.18 
    gatsby-plugin-sass: ^2.1.26 => 2.1.26 
    gatsby-remark-copy-linked-files: ^2.1.33 => 2.1.33 
    gatsby-remark-images: ^3.1.39 => 3.1.39 
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3 
    gatsby-source-filesystem: ^2.1.43 => 2.1.43 
    gatsby-transformer-remark: ^2.6.45 => 2.6.45 
  npmGlobalPackages:
    gatsby-cli: 2.8.22
```

**Comment by sidharthachatterjee** [comment]
Cc @erquhart

**Comment by erquhart** [comment]
@wardpeet on the PR that added the `customizeWebpackConfig` option, [you mentioned](https://github.com/gatsbyjs/gatsby/pull/17442#issuecomment-534020542) that the proper fix would be to utilize a child compiler - would doing so cause the plugin to receive webpack config customizations that occur in a project's own `gatsby-node.js`?

**Comment by joshdcomp** [comment]
to give a quick update: my workaround was to forego `core-js/stable` and just use `core-js` in all its glory
