### ISSUE TITLE
GraphQL: don't filters work for inside the array?

### ISSUE THREAD

**Issue by avtara** [gatsbyjs/gatsby#20449]
I have REST API 
`{
    "data": [
        {
            "id": 1,
            "title": "Ini Pertama",
            "content": "Aw aw",
            "tags": "Asik",
            "status": 1,
            "authorid": "Muhammad Avtara Khrisna",
            "createdat": "2020-01-06T07:18:52.130666-08:00",
            "updateat": "2020-01-07T06:08:55.925902-08:00"
        },
        {
            "id": 2,
            "title": "Ini Kedua",
            "content": "tolong",
            "tags": "Lonely",
            "status": 0,
            "authorid": "Muhammad Avtara Khrisna",
            "createdat": "2020-01-07T04:54:42.796867-08:00",
            "updateat": "2020-01-07T04:54:42.796867-08:00"
        },
        {
            "id": 3,
            "title": "Ini Ketiga",
            "content": "Aw aw",
            "tags": "Asik",
            "status": 1,
            "authorid": "Muhammad Avtara Khrisna",
            "createdat": "2020-01-07T06:08:20.561482-08:00",
            "updateat": "2020-01-07T06:08:20.561482-08:00"
        },
        {
            "id": 4,
            "title": "Ini Keempat",
            "content": "Aw aw",
            "tags": "Asik",
            "status": 1,
            "authorid": "Muhammad Avtara Khrisna",
            "createdat": "2020-01-07T06:08:29.418792-08:00",
            "updateat": "2020-01-07T06:08:29.418792-08:00"
        }
    ],
    "status": 200
}`

and I will filter the data that I have into:
`{
  "data": {
    "allRestApiApiV1Blogs": {
      "edges": [
        {
          "node": {
            "data": [
              {
                "authorid": "Muhammad Avtara Khrisna",
                "status": 1,
                "id": 1
              },
              {
                "authorid": "Muhammad Avtara Khrisna",
                "status": 1,
                "id": 3
              },
              {
                "authorid": "Muhammad Avtara Khrisna",
                "status": 1,
                "id": 4
              }
            ]
          }
        }
      ]
    }
  }
}`

My query:
![image](https://user-images.githubusercontent.com/26185394/71898560-a8c03d80-317f-11ea-91d9-2d89267ef32d.png)

**and always produces queries that I don't want**

![image](https://user-images.githubusercontent.com/26185394/71898621-c8effc80-317f-11ea-85b4-128fb36a3050.png)

**how to filter data correctly?**

**Comment by nimahkh** [comment]
What must be the result? I don't get it.

**Comment by avtara** [comment]
> What must be the result? I don't get it.
I want, I get data like this:
![image](https://user-images.githubusercontent.com/26185394/71899776-6ea46b00-3182-11ea-8acf-2613d6d8500a.png)


only displays that have status: 1

**Comment by nimahkh** [comment]
try this: 
`
(filter : { data : { elemMatch : { status: "1"} } })
`

**Comment by avtara** [comment]
still not working on me
