### ISSUE TITLE
No Changes in any file still create difference in number of files after sequential builds

### ISSUE THREAD

**Issue by AkashRajpurohit** [gatsbyjs/gatsby#20444]
## Description

I was going through lots of issues (both open and closed) for the problem that for a small change in gatsby site, netlify takes lots of time as it has to reupload all the files to CDN even those which haven't changed. 

Following the PR from [#16686](https://github.com/gatsbyjs/gatsby/pull/16686) I updated gatsby to v2.17.0 and tried building it again. This time unlike previously, not that many files were changed. However, I tried to build the site, take a copy of public/ folder and then rebuild the website without any changes. Even in this case, there was difference in few files.

### Steps to reproduce

Any gatsby site generated with v2.17.0

```sh
yarn build

cp -r public public-1

yarn build

diff --brief -Nr public/ public-1/
```

### Expected result

```
No output
```

### Actual result

```
Files public/404/index.html and public.first/404/index.html differ
Files public/404.html and public.first/404.html differ
Files public/about/index.html and public.first/about/index.html differ
Files public/archive/1/index.html and public.first/archive/1/index.html differ
Files public/blog/learn-map-method-in-javascript-with-code-examples/index.html and public.first/blog/learn-map-method-in-javascript-with-code-examples/index.html differ
Files public/blog/welcome-to-my-website/index.html and public.first/blog/welcome-to-my-website/index.html differ
Files public/index.html and public.first/index.html differ
Files public/offline-plugin-app-shell-fallback/index.html and public.first/offline-plugin-app-shell-fallback/index.html differ
Files public/page-data/app-data.json and public.first/page-data/app-data.json differ
Files public/project/chat-application/index.html and public.first/project/chat-application/index.html differ
Files public/project/currency-converter/index.html and public.first/project/currency-converter/index.html differ
Files public/project/ezlyrics/index.html and public.first/project/ezlyrics/index.html differ
Files public/project/hex2rgb-color-conversion/index.html and public.first/project/hex2rgb-color-conversion/index.html differ
Files public/project/shortly/index.html and public.first/project/shortly/index.html differ
Files public/project/spell-it/index.html and public.first/project/spell-it/index.html differ
Files public/projects/index.html and public.first/projects/index.html differ
Files public/sitemap-blogs.xml and public.first/sitemap-blogs.xml differ
Files public/sitemap-pages.xml and public.first/sitemap-pages.xml differ
Files public/sitemap-projects.xml and public.first/sitemap-projects.xml differ
Files public/sitemap-tags.xml and public.first/sitemap-tags.xml differ
Files public/sitemap.xml and public.first/sitemap.xml differ
Files public/styles-2d30114aa17022518b80.js and public.first/styles-2d30114aa17022518b80.js differ
Files public/styles-2d30114aa17022518b80.js.map and public.first/styles-2d30114aa17022518b80.js.map differ
Files public/sw.js and public.first/sw.js differ
Files public/tag/index.html and public.first/tag/index.html differ
Files public/tag/javascript/index.html and public.first/tag/javascript/index.html differ
Files public/tag/personal/index.html and public.first/tag/personal/index.html differ
Files public/webpack-runtime-a808e44b2f341d1b33cf.js and public.first/webpack-runtime-a808e44b2f341d1b33cf.js differ
Files public/webpack-runtime-a808e44b2f341d1b33cf.js.map and public.first/webpack-runtime-a808e44b2f341d1b33cf.js.map differ
Files public/webpack.stats.json and public.first/webpack.stats.json differ
```

### Environment

  System:
    OS: Linux 4.19 Kali GNU/Linux Rolling 2019.3
    CPU: (4) x64 AMD A8-7410 APU with AMD Radeon R5 Graphics
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 10.16.2 - /usr/bin/node
    Yarn: 1.16.0 - ~/.npm/bin/yarn
    npm: 6.12.1 - ~/.npm/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 60.8.0
  npmPackages:
    gatsby: 2.17.0 => 2.17.0 
    gatsby-image: ^2.2.24 => 2.2.24 
    gatsby-plugin-advanced-sitemap: 1.4.5 => 1.4.5 
    gatsby-plugin-google-analytics: 2.1.23 => 2.1.23 
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1 
    gatsby-plugin-less: ^3.0.9 => 3.0.9 
    gatsby-plugin-manifest: ^2.2.20 => 2.2.20 
    gatsby-plugin-offline: 3.0.16 => 3.0.16 
    gatsby-plugin-page-progress: 2.0.12 => 2.0.12 
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.10 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sharp: ^2.2.28 => 2.2.28 
    gatsby-remark-copy-linked-files: 2.1.33 => 2.1.33 
    gatsby-remark-images: ^3.1.25 => 3.1.25 
    gatsby-remark-prismjs: ^3.3.17 => 3.3.17 
    gatsby-remark-relative-images: 0.2.3 => 0.2.3 
    gatsby-source-filesystem: ^2.1.29 => 2.1.29 
    gatsby-transformer-remark: ^2.6.27 => 2.6.27 
    gatsby-transformer-sharp: ^2.2.20 => 2.2.20 
  npmGlobalPackages:
    gatsby-cli: 2.8.4

**Comment by freiksenet** [comment]
This is very curious!

I'd love to take a look at this project, I wonder if you could share code for it? If you can't share it publicly, you can email it to me at freiksenet@gatsbyjs.com.

**Comment by AkashRajpurohit** [comment]
Okay so here's an update to this.

I upgraded my gatsby globally to the latest version which was `^2.18.12` and created a new project using `gatsby new test1`

package.json of this project
```
{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^2.18.12",
    "gatsby-image": "^2.2.34",
    "gatsby-plugin-manifest": "^2.2.31",
    "gatsby-plugin-offline": "^3.0.27",
    "gatsby-plugin-react-helmet": "^3.1.16",
    "gatsby-plugin-sharp": "^2.3.5",
    "gatsby-source-filesystem": "^2.1.40",
    "gatsby-transformer-sharp": "^2.3.7",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^5.2.1"
  },
  "devDependencies": {
    "prettier": "^1.19.1"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
```

Now I tried the steps mentioned above and the result was the expected result i.e `No Output` when I did not change any file and just rebuild the website again, there was no difference shown from the `diff` command as above.

---

Now I simply downgraded it to `2.17.0` which is the current version of gatsby in my project and tried the same thing. Then without any changes made to files led to the following output to the `diff` command.

```
Files public/404/index.html and public-1/404/index.html differ
Files public/404.html and public-1/404.html differ
Files public/commons-483f0c4cbae47f541132.js and public-1/commons-483f0c4cbae47f541132.js differ
Files public/commons-483f0c4cbae47f541132.js.map and public-1/commons-483f0c4cbae47f541132.js.map differ
Files public/index.html and public-1/index.html differ
Files public/page-2/index.html and public-1/page-2/index.html differ
Files public/page-data/app-data.json and public-1/page-data/app-data.json differ
Files public/webpack.stats.json and public-1/webpack.stats.json differ
```
So I'm guessing that this issue is with gatsby@2.17.0 and probably removed in the latest 2.18.12 ???

Linking the repo on which I tested this. Let me know if you can reproduce it on this repo and confirm it as well. @freiksenet 

Repo: https://github.com/AkashRajpurohit/gatsby-test-repo

**Comment by AkashRajpurohit** [comment]
Any update @freiksenet ?
