### ISSUE TITLE
merging runtime remote data fetching w/ build-time sources

### ISSUE THREAD

**Issue by brandonmp** [gatsbyjs/gatsby#2044]
#2034  got me thinking abt my last project, which used `react-relay` ('classic' flavor, not modern, fwiw)

the best part about relay is it almost totally abstracts away the complexities of dealing w/ remote data-sources. 

just to recap the thrust of how relay does that, here's a pseudocode example:

```
/** ListItem.js */

// this ListItem essentially gets its props from the container wrapping it.
// this is the colocation magic Relay touts
const ListItem = props => (
  <li>{props.thing.name} | {props.thing.id}</li>
)

export default RelayContainer(List, graphql`
  fragment on Thing {
      id
      name
  }
`)

/** List.js */

// then, any parent of ListItem is responsible for passing the correctly typed 
// node to ListItem in the form of a so-called fragment via props
const List = props => (
   // pass the node of type Thing down to the ListItem
  <ul>{props.things.edges.map(t => <ListItem thing={t}>)</ul>
)

export default RelayContainer(List, graphql`
  fragment on User {
     usersThings {
        edges { 
             // ListItem has told its parent (List) that it needs a fragment called "thing".
             // List doesn't care what's in the fragment, it just needs to know where in its  own 
             // query it can find the node of the correct type
            ${ListItem.getFragment('thing')} 
        }
     }
  }
`)
``` 

Gatsby catches a lot of that same magic b/c I don't have to worry about handling data fetching at run time, which is ~~nice~~ great.

But some data isn't static-friendly, so some use cases need to add systems to handle their data fetching at runtime. 

And so, I can't help but wonder what it would look like if I could seamlessly include my remote data requirements alongside my gatsby data requirements.

Is this feasible? Say, if the build system were to replace the gatsby queries with static data & leave the adjacent remote queries? 

I don't know enough about Gatsby's guts to speculate on implementation, but assuming it could be done in a way that abstracted-away the delineation b/t static data requirements & run-time remote data requirements, I think the end result would be neat.

**Comment by KyleAMathews** [comment]
Huh, this is an interesting approach. Figuring out a great approach for mixing static/runtime data requirements is super important.

Perhaps a custom directive would be what we want? `@relay` or `@runtime` perhaps?

Just posted on another directive idea https://github.com/gatsbyjs/gatsby/issues/2080

**Comment by jquense** [comment]
Perhaps some of the schema stitching stuff apologizing is so working on is relevant?

**Comment by KyleAMathews** [comment]
This is live! https://github.com/gatsbyjs/rfcs/blob/master/text/0000-native-graphql-source.md

**Comment by KyleAMathews** [comment]
Oh ooops, "runtime" kyle

**Comment by Daniel15** [comment]
@KyleAMathews Is there an example of combining compile-time and runtime GraphQL queries in a single page, or is this still unsolved?

**Comment by KyleAMathews** [comment]
Yeah — you can do it with Apollo. See @jlengstorf's talk on this exact subject https://www.youtube.com/watch?v=wNUg1jpj9T0

If you want something more fancy where Gatsby internally swaps out the build-time graphql result for run-time i.e. makes live requests instead of loading the built ones — that's something we'll be working on in the future but no ETA just yet.

**Comment by JonJamesDesign** [comment]
@KyleAMathews being able to re-run graphql queries at runtime would be a game changer, specifically in the context of getting preview modes to work with headless CMS', such as the one offered by Prismic.

Ideally, I'd determine what type of content I need to load as a preview (based on a URL param from the CMS), then render the appropriate template for that content type, passing a prop to said template component, telling it to re-fetch the data.
