### ISSUE TITLE
OnCreatePage dynamically not working

### ISSUE THREAD

**Issue by jojobagings78** [gatsbyjs/gatsby#20445]
I am currently using gatsby-node.js to forward all url requests using /product/*/ to a page, however 
on doing /product/id/ if that id does not exist it does not render the 404 page, it does however render the 404 page if the url is /product or /product/ without the id.

I am trying to figure out what is the correct way to handle this issue and currently I have the following:

```
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions
  if (page.path.match("/product/")) {
    page.matchPath = "/product/*/"
    createPage(page)
  }
}
```

Then I have in pages a page called product.js that has the following:
```
const App = () => (

  <Router>
    <ErrorPage path="/product/" />
    <ErrorPage path="/product/*/" />
    <UserPage path="/product/:id" />
  </Router>

)
export default App;
```

Then UserPage calls api request with a useEffect and if loaded will render page and if not will be null. Once loaded it will then check if exists and if not and if exists renders page however all animations on load do not work and page shows blank and if does not exist it should render 404 but it renders only a blank page even that I am calling 404 because the 404 page has animations on it which are not starting.

Is this the best way to handle this and what is the solution to get this to work correctly ?

What I am after doing is on clicking the page it check if exists and loads the page if does not exist then 404. But seems to be an issue in how gatsby is handling it or something I am doing wrong and feedback would be great.

**Comment by freiksenet** [comment]
There is a [gatsby-plugin-force-trailing-slashes](https://www.gatsbyjs.org/packages/gatsby-plugin-force-trailing-slashes/) that might solve this. Could you try if it works for you? This way you don't need to add `/product/*/`.

**Comment by jojobagings78** [comment]
> There is a [gatsby-plugin-force-trailing-slashes](https://www.gatsbyjs.org/packages/gatsby-plugin-force-trailing-slashes/) that might solve this. Could you try if it works for you? This way you don't need to add `/product/*/`.

Does not solve the issue I also noticed recently that the page with an id that it gets in the database is not showing meta data such as title, description or keywords which is a big problem for SEO.

**Comment by sidharthachatterjee** [comment]
> I am currently using gatsby-node.js to forward all url requests using /product/*/ to a page, however
> on doing /product/id/ if that id does not exist it does not render the 404 page
> 

Just to confirm, the `/product/:id` pages are generated at build time right and are not client side only routes right? 

Can you post a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)?
