### ISSUE TITLE
Unable to use Gatsby environment variable for gatsby-source-git patterns

### ISSUE THREAD

**Issue by hirenoble** [gatsbyjs/gatsby#20458]
## Description

Gatsby-source-git plugin expects the patterns to be defined as [\`\*\`, \`!\*.md\`] (without grave accent symbols)where as gatsby environment variable inserts the patterns as \`[\`\*\`, \`!\*.md\`]\`

### Steps to reproduce
gatsby-config.js
    {
      resolve: `gatsby-source-git`,
      options: {
        name: ``,
        remote: `${process.env.GATSBY_SOURCE}`,
        // Optionally supply a branch. If none supplied, you'll get the default branch.
        branch: `${process.env.GATSBY_SOURCE_BRANCH}`,
        // Tailor which files get imported eg. import the docs folder from a codebase.
        patterns: process.env.GATSBY_SOURCE_PATTERNS,
      },
    },
### Expected result
Source files from Github repository as per the patterns.
The build should complete successfully.
### Actual result
Because of extra `` the patterns are not recognized and the build fails.
### Environment
Production

**Comment by freiksenet** [comment]
Hello @hirenoble!

[gatsby-source-git](https://github.com/stevetweeddale/gatsby-source-git) isn't maintained by Gatsby team, it's an external plugin. You should create this issue in their repository.

Thank you! :purple_heart:
