### ISSUE TITLE
Deprecation warnings for non-Gatsby code

### ISSUE THREAD

**Issue by robinmetral** [gatsbyjs/gatsby#20451]
## Description

On develop, Gatsby parses the codebase for deprecated APIs like `pathContext` and `boundActionsCreator`. In some cases, these keywords are detected in non-Gatsby code, as mentioned already in #11679 (closed) and #10211 (stale), and a warning is shown:

![pathContext is deprecated](https://user-images.githubusercontent.com/35560568/71908407-33983c80-316e-11ea-8c45-f6ebeb3e1c55.png)
_Real example of the warning being thrown for minified Storybook code_

### Steps to reproduce

1. `gatsby new bug-repro https://github.com/gatsbyjs/gatsby-starter-hello-world`
2. `cd bug-repro`
3. `mkdir random-files && echo pathContext > random-files/random-file.js`
  ➡️ this creates a js file and writes `pathContext` in it
4. `gatsby develop`

### Expected result

These warnings should only be shown if these deprecated APIs are actually being used in the Gatsby project.

### Actual result

![pathContext is deprecated](https://user-images.githubusercontent.com/35560568/71908836-05ffc300-316f-11ea-8b63-b0acf5aa45a7.png)

### Environment

```
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12 
```

**Comment by sidharthachatterjee** [comment]
Love detailed issues like these. Thanks @robinmetral 🙌 

So the deprecation warning here isn't for APIs in non-Gatsby code but for instances of `pathContext` and `boundActionsCreator` in _any_ code because they are available as props and could be passed down arbitrarily. 

The heuristic isn't great though and we should improve this since it is confusing. 

Perhaps we can lint for if they are props and then print this warning? What do you think?

**Comment by robinmetral** [comment]
@sidharthachatterjee checking if they are props before printing the warning could work! Not sure how we could lint this though, any ideas? :think

I had another related idea - could we somehow stop Gatsby from parsing files that are ignored in `.gitignore` (or `.gatsbyignore` 😛)? In my case for instance, the `storybook-public` folder is ignored, similarly to Gatsby's `public` folder. This is where keywords like `boundActionsCreator` come up unexpectedly.

If Gatsby took an ignore file as a CLI flag or a config option, we could avoid some warnings. There's probably already some ignore logic built in, to avoid parsing `node_modules` for instance. This could ensure that warnings are only thrown for code that is actually intended to be in the Gatsby project (i.e. not ignored).

**Comment by jlarmstrongiv** [comment]
Can confirm, the warning occurs with the latest versions of gatsby and storybook:
```
pathContext is deprecated. Please use pageContext instead. For migration instructions, see https://gatsby.dev/pathContext
Check the following files:
⠀
storybook-static/vendors~main.25ccc0c30aa0c97984ed.bundle.js
```
I like the `.gitignore` idea

**Comment by gitonthescene** [comment]
It's also confusing that pathContext is still being used [inside gatsby](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/page-renderer.js#L11).  I'm still getting acclimated to the code, but I'm getting this warning from code which is used by PageRenderer and hence exposing pathContext.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
