### ISSUE TITLE
Integration testing of graphQL query and a page component in gatsbyJS

### ISSUE THREAD

**Issue by aiwatko** [gatsbyjs/gatsby#20475]
## Summary
Integration testing of graphQL query and a page component in gatsbyJS

## Relevant information

I would like to have an integration test for my page query + page component:
```
import React from "react";
import { graphql } from "gatsby";

const NotFound = ({ data }) => {
  const { title, text } = data.allFile.edges[0].node.childDataJson;

  return (
    <React.Fragment>
      <h1>{title}</h1>
      <p>{text}</p>
    </React.Fragment>
  );
};

export const query = graphql`
  query {
    allFile(filter: { name: { eq: "404" } }) {
      edges {
        node {
          childDataJson {
            title
            text
          }
        }
      }
    }
  }
`;

export default NotFound;
```
What I would like to test is if the query structure is correct, and therefore check the presence of the title in DOM:
```
describe("404 page", () => {
  it("Contains a title", () => {
    const { getByText } = render(<NotFound />);
    expect(getByText("Not found")).toBeInTheDocument();
  });
});
```

I get the following error:
`It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away. Unfortunately, something went wron
g and the query was left in the compiled code.`

Is it possible to write integration test checking graphQL queries?

I know that I can mock the graphql page query in `mocks` to avoid this error, but I would like for graphql not to be mocked:
```
const React = require("react");
const gatsby = jest.requireActual("gatsby");

module.exports = {
  ...gatsby,
  graphql: jest.fn(),
};
```

**Comment by freiksenet** [comment]
Hi!

Unfortunately it's not possible to test pages in an isolated context at the moment. I do feel it would be a very valuable enhancement though. I've created [an issue for that](https://github.com/gatsbyjs/gatsby/issues/20481).

One thing you could try is using cypress to test pages. You can find an example in [Gatsby's end-to-end tests](https://github.com/gatsbyjs/gatsby/tree/master/e2e-tests).

I hope that helps! :purple_heart: 

I'll be closing an issue for now, feel free to reopen it if you have any more questions.
