### ISSUE TITLE
Are namespaced/scoped plugin names allowed ? 

### ISSUE THREAD

**Issue by jooola** [gatsbyjs/gatsby#20482]
## Summary

Are namespaced / scoped plugin names allowed ? Are plugins named like @directus/gastby-source-directus valid ?

## Relevant information

We are planning on pushing a Gatsby plugin under the Directus umbrella https://github.com/directus/gatsby-source/issues/5 in order to gather all possible people creating such tools to work together.

We are now searching for the right name for the plugin, and we hoped we could release it under a scoped name like `@directus/gastby-source-directus` or `@directus/gastby-source`.

Which one should be the best for visibility and fit in the gatsby naming rules ?

**Comment by jooola** [comment]
See https://github.com/directus/gatsby-source/issues/5#issuecomment-572125733

**Comment by LekoArts** [comment]
Thank you for opening this!

> Are namespaced / scoped plugin names allowed ? Are plugins named like @directus/gastby-source-directus valid ?

Yes, as long as `gatsby` is in the name (https://www.gatsbyjs.org/docs/naming-a-plugin/) it's valid. However, we have a certain naming scheme that ultimately everyone follows.

I would recommend using `@directus/gatsby-source-directus`. It's more verbose, yes, but people are more familiar with it this way as already other scoped plugins do it this way. Furthermore if you plan to publish other packages under the same namespace in the future this short form could become confusing.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by jooola** [comment]
@LekoArts Ok, I think this is missing from the website documentation, it is unclear to say the least.
