### ISSUE TITLE
[gatsby-transformer-remark plugin] Created nodes visible to GraphIQL but queries on Gatsby pages return null

### ISSUE THREAD

**Issue by timothymcmackin** [gatsbyjs/gatsby#20484]
## Description

I'm working on a plugin for gatsby-transformer-remark. In my plugin, I take data from the Remark transformer and create a graphql node of a new type. When I start the site and open GraphIQL at http://localhost:8000/___graphql, I can see my plugin's new node and its data. However, when I try to access that node's data in a Gatsby page component, the graphql query returns null for that node type.

### Steps to reproduce

I have a minimal reproduction repo at this link. Instructions for running it and seeing the issue are in the readme.

https://github.com/timothymcmackin/test-create-nodes

### Expected result

The graphql node data that I create in the plugin is available to both graphiql and graphql queries on Gatsby pages.

### Actual result

The node data is available to graphiql but graphql queries on Gatsby pages return null.

### Environment

  System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.14.0 - /tmp/yarn--1578508131320-0.0607713459349386/node
    Yarn: 1.19.1 - /tmp/yarn--1578508131320-0.0607713459349386/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  npmPackages:
    gatsby: ^2.18.12 => 2.18.17
    gatsby-image: ^2.2.34 => 2.2.37
    gatsby-plugin-manifest: ^2.2.31 => 2.2.34
    gatsby-plugin-offline: ^3.0.27 => 3.0.30
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.18
    gatsby-plugin-sharp: ^2.3.5 => 2.3.10
    gatsby-remark-autolink-headers: ^2.1.21 => 2.1.21
    gatsby-source-filesystem: ^2.1.40 => 2.1.43
    gatsby-transformer-remark: ^2.6.45 => 2.6.45
    gatsby-transformer-sharp: ^2.3.7 => 2.3.9

**Comment by LekoArts** [comment]
Hi! I tried to clone your repository but `yarn install` can't finish:

```sh
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "http://artifactory.shuttercorp.net/artifactory/api/npm/npm-composite/@babel/runtime-corejs3/-/runtime-corejs3-7.7.7.tgz: getaddrinfo ENOTFOUND artifactory.shuttercorp.net".
```

**Comment by timothymcmackin** [comment]
Sorry about that @LekoArts . My yarn.lock referred to internal packages. I've deleted the lockfile -- `yarn install` should work now.

**Comment by timothymcmackin** [comment]
I've fixed my minimal  reproduction so it should work now. Can anyone have a look?

**Comment by timothymcmackin** [comment]
Per this comment, I can't create nodes within a Remark plugin.
https://github.com/gatsbyjs/gatsby/issues/23569#issuecomment-621129483
