### ISSUE TITLE
Inconsistent support for PNG image

### ISSUE THREAD

**Issue by bvaughn** [gatsbyjs/gatsby#2048]
While working on  [the `gatsby` branch of `facebook/react`](https://github.com/facebook/react/tree/gatsby) I noticed an unexpected behavior with regard to how Gatsby handles different image types within markdown files.

This may be caused by something upstream (haven't dug into it yet) but the docs made no mention of this limitation that I saw so I wanted to file it.

- [x] This works
```jsx
<img src="../path/to/image.gif" alt="Some title"> 
```

- [ ] This does not work (the image will fail to load at runtime)
```jsx
<img src="../path/to/image.png" alt="Some title"> 
```

- [x] This works
```markdown
![Some title](../path/to/image.png)
```

Another difference is that eg .gif and .jpg image types output regular HTML image tags, eg:
```markdown
![Some title](../path/to/image.gif)
```
...becomes...
```html
<img src="/b967396662319e6aa6170dab232f0286.gif" alt="...">
```

But .png images output "responsive" image anchor tags, eg:
```markdown
![Some title](../path/to/image.png)
```
...becomes...
```html
<a class="gatsby-resp-image-link" href="undefined" style="display: block" target="_blank" rel="noopener">
  <span class="gatsby-resp-image-wrapper" style="position: relative; z-index: -1; display: block; ">
    <span class="gatsby-resp-image-background-image" style="...">
      <img class="gatsby-resp-image-image" style="...">
    </span>
  </span>
</a>
```

**Comment by bvaughn** [comment]
This looks at least related to #1138.

Although I've updated to the latest releases of Gatsby (and plugins) and I'm still seeing PNG image types treated differently than eg .jpg and .gif.

**Comment by KyleAMathews** [comment]
Hmmm @chiedo worked on adding support for <img> tags. Wonder why that's not working. 

We don't generate responsive markup for gifs as there's not an easy way afaik to resize gifs so they just get copied over.

**Comment by bvaughn** [comment]
Would be great to be able to embed PNGs via `<img>` tags since the existing React blog posts so heavily make use of this syntax.

There's also some weird nested syntax (eg [in files like this](https://raw.githubusercontent.com/facebook/react/gatsby/docs/_posts/2013-11-06-community-roundup-10.md)) that isn't compatible with the markdown flavor of image tags:

> Rendered markup on the server:
> <figure>[![](/react/img/blog/react-php.png)](http://www.phpied.com/server-side-react-with-php-part-2/)</figure>

**Comment by chiedo** [comment]
Kyle's right @bvaughn 

Open to any suggestions/pull requests to improve!

I only write posts in markdown if they're VERY simple otherwise, I'll do the whole thing in HTML so if you find more cases where markdown is having issues and could help fix, that would be awesome!

Most of the crazy logic should be taken care of already. The code should be pretty easy to follow. I tried to write good comments.

**Comment by bvaughn** [comment]
Cool. So just to confirm, it sounds like the fact that `<img>` tags don't work at all with PNGs is not a known/expected issue then? I'll see if I can find some time to look into it and submit a PR.

**Comment by KyleAMathews** [comment]
Yup! Just add a failing test and fix the bug! https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/__tests__/index.js

**Comment by chiedo** [comment]
Also, I just realized, I haven't been using gatsby-remark-images any more and am using this version of gatsby-copy-linked-files. Can't get it to build on the gatsby site for whatever reason but it's working in all my codebases.

https://github.com/gatsbyjs/gatsby/pull/1571

So it's possible the fix for that problem is already fixed and you'll just be able to port it!

**Comment by bvaughn** [comment]
Got around to setting up a minimal repro today in hopes of fixing this but immediately hit a blocker:

```sh
$ gatsby new gatsby-test https://github.com/gatsbyjs/gatsby-starter-blog
$ cd gatsby-test
$ gatsby develop # Works ok
```

I then edit one of the markdown files, eg `2015-05-01-hello-word` like so:
```md
---
title: Hello World
date: "2015-05-01T22:12:03.284Z"
path: "/hello-world/"
---

# Markdown
![image](./salty_egg.jpg)

# <img> tag
<img src="./salty_egg.jpg" alt="image"/> 
```

Now if I try re-running, I see a couple of errors it permanently hangs:
```sh
$ gatsby develop
Something is already running at port 8000
Would you like to run the app at another port instead? [Y/n] y
success delete html files from previous builds — 0.006 s
success open and validate gatsby-config.js — 0.003 s
success copy gatsby files — 0.018 s
success source and transform nodes — 0.059 s
success building schema — 0.199 s
success createLayouts — 0.006 s
success createPages — 0.023 s
success createPagesStatefully — 0.007 s
success extract queries from components — 0.075 s
⠁ Unhandled rejection TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1239:7)
    at /Users/bvaughn/gatsby-test/node_modules/gatsby-remark-copy-linked-files/index.js:76:28
    at one (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:23:16)
    at all (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:44:20)
    at one (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:27:14)
    at all (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:44:20)
    at one (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:27:14)
    at visit (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:14:3)
    at module.exports (/Users/bvaughn/gatsby-test/node_modules/gatsby-remark-copy-linked-files/index.js:69:3)
    at /Users/bvaughn/gatsby-test/node_modules/gatsby-transformer-remark/extend-node-type.js:137:32
    at Array.map (<anonymous>)
    at /Users/bvaughn/gatsby-test/node_modules/gatsby-transformer-remark/extend-node-type.js:134:55
    at tryCatcher (/Users/bvaughn/gatsby-test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/bvaughn/gatsby-test/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/bvaughn/gatsby-test/node_modules/bluebird/js/release/promise.js:569:18)

Unhandled rejection TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1239:7)
    at /Users/bvaughn/gatsby-test/node_modules/gatsby-remark-copy-linked-files/index.js:76:28
    at one (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:23:16)
    at all (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:44:20)
    at one (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:27:14)
    at all (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:44:20)
    at one (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:27:14)
    at visit (/Users/bvaughn/gatsby-test/node_modules/unist-util-visit/index.js:14:3)
    at module.exports (/Users/bvaughn/gatsby-test/node_modules/gatsby-remark-copy-linked-files/index.js:69:3)
    at /Users/bvaughn/gatsby-test/node_modules/gatsby-transformer-remark/extend-node-type.js:137:32
    at Array.map (<anonymous>)
    at /Users/bvaughn/gatsby-test/node_modules/gatsby-transformer-remark/extend-node-type.js:134:55
    at tryCatcher (/Users/bvaughn/gatsby-test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/bvaughn/gatsby-test/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/bvaughn/gatsby-test/node_modules/bluebird/js/release/promise.js:569:18)

⠂ run graphql queries(node:77675) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'slice' of undefined
(node:77675) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:77675) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'slice' of undefined
⠐ run graphql queries
````

**Comment by bvaughn** [comment]
Darn it. Did _not_ mean to click that button.

**Comment by KyleAMathews** [comment]
Hey, closing out old issues. Please re-open if you have additional questions, thanks!
