### ISSUE TITLE
Allow multiple themes to provide developMiddleware

### ISSUE THREAD

**Issue by wodenx** [gatsbyjs/gatsby#20492]
## Summary

Currently if two themes (or a theme and the site) both export the `developMiddleware` key in `gatsby-config`, only one will win.  Of course you can overcome this by implementing the node api, but it would be nice to be able to do it simply using the config.

Am checking here to see if there is appetite for this feature.  If so, I will formalize a PR.

### Basic example

See this draft pr [#20491](https://github.com/gatsbyjs/gatsby/pull/20491).  

### Motivation

Our use case - one theme which adds an authentication middleware, and another which adds a proxy.

**Comment by vladar** [comment]
CC @ChristopherBiscardi

**Comment by wodenx** [comment]
@ChristopherBiscardi thoughts on this?

**Comment by wardpeet** [comment]
@wodenx sorry for the late response. So if 2 themes have a developMiddleware in their config, the latest wins? Just to make sure, you're talking about, https://www.gatsbyjs.org/docs/api-proxy/? If so this is definitely a bug, we should convert it to an array.

I haven't checked your PR yet, first I want to validate if this I understand the problem correctly.

**Comment by danabrit** [comment]
@wodenx Hi there! I'm closing this issue as it has gone quiet. Please open with updated response to @wardpeet 's comment above if this is still something you would like to pursue.
