### ISSUE TITLE
Lighthouse audit problem with Gatsby image.

### ISSUE THREAD

**Issue by TheFirstMe** [gatsbyjs/gatsby#20493]
## Summary
I get performance score of 84-89 for my home page using Lighthouse audits. It is showing a problem saying: "Properly size images: Serve images that are appropriately-sized to save cellular data and improve load time." 

## Relevant information
Gatsby Image fluid is used with both minWidth and maxWidth provided to maintain aspect ratio. 

### Environment (if relevant)

Not relevant

### File contents (if changed)

`gatsby-config.js`: N/A
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by TheFirstMe** [comment]
@LekoArts 
Here's the repo for a minimal reproduction: [https://github.com/TheFirstMe/bug-repo](url) 
The production deploy for performing audits: [https://gatsby-image.now.sh](url)

The Lighhouse audit for the same is as below: 

![lighthouse_audit](https://user-images.githubusercontent.com/23120939/72265030-c4c15480-3641-11ea-92d9-b1e457951377.png)

Note the 
> Serve images that are appropriately-sized to save cellular data and improve load time.

What am I doing wrong here?

**Comment by TheFirstMe** [comment]
Not stale.

**Comment by TheFirstMe** [comment]
Still not stale

**Comment by TheFirstMe** [comment]
@LekoArts Can you check this out?

**Comment by TheFirstMe** [comment]
Not stale

**Comment by TheFirstMe** [comment]
Closing this for now. I will open a new one when I encounter this issue again.

**Comment by andrezimpel** [comment]
@TheFirstMe I'm running into the same issue! I can give someone access to to the repo if needed because the page is not online yet.

**Comment by maxcct** [comment]
Same issue. This is my query:

```
                  card_imageSharp {
                    childImageSharp {
                      fluid(maxWidth: 300, quality: 100) {
                        ...GatsbyImageSharpFluid
                      }
                    }
                  }
```

**Comment by bogdansoare** [comment]
Also having this issue

**Comment by hal-efecan** [comment]
I've also run into this issue - Performance has been floating around 85%. The biggest opportunity area is "properly sized images". I've been using Gatsby Image fluid with maxWidth.

**Comment by AvilaAi** [comment]
I've been troubled by this issue for weeks.. anyone can help?

**Comment by samgermain** [comment]
I have this issue also

**Comment by JordanHoffman** [comment]
A website I made with Gatsby gets a terrible Lighthouse performance score of 30 on mobile with the main recommendation being to properly size the images. I've used Gatsby Fluid so I don't know how else to optimize. This is the website: MoncktonPhotos.com

**Comment by laradevitt** [comment]
Regarding comment above by @JordanHoffman and @benbehringer - I'm also still getting blur-up effect with GatsbyImageSharpFluid_withWebp_noBase64. On the upside, the LCP hit is apparently something that's being worked on in Lighthouse so I'm not going to fuss about it too much. 

See: 
Kyle Mathews comment: https://github.com/gatsbyjs/gatsby/issues/24332#issuecomment-650799066 
Twitter exchange between KM and Lighthouse dev: https://twitter.com/addyosmani/status/1277293541878673411 
Issue tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1045640

**Comment by authoritydental** [comment]
Is this problem solved?

We get the lighthouse error `properly size images` on our gatsby site no matter what we do.

https://i.gyazo.com/92d9863b09d6bd95691c4bf31ca452ee.png

**Comment by obinasBaba** [comment]
where is this issue at? lighthouse error `properly size images`
