### ISSUE TITLE
passing argument to useStaticQuery but it doesn't filter data properly

### ISSUE THREAD

**Issue by ghanshyammac** [gatsbyjs/gatsby#20500]
```
import React from 'react';
import PropTypes from 'prop-types';
import { graphql, useStaticQuery } from 'gatsby';

const TipsAndAdvice = (props) => {
	const {
		data
	} = props;

	if (!data || !data.dynamic_tags)
		return null;

	const {
		dynamic_tags = []
	} = data;

	const flattenTags = dynamic_tags.map(tag => tag.tag_name);
	console.log("data",flattenTags);
	const fdata = useStaticQuery (graphql`
	 query($flattenTags:[String!])  {
		allContentstackImageWithContent(filter: {tag: {elemMatch: {tag_name: {in: $flattenTags}}}}) {
		  nodes {
			...ImageWithContent
		  }
		}
	  }
	`);
	console.log("fggggggg ",fdata);

	return (
		<div>
			hello
		</div>
	);
};

TipsAndAdvice.propTypes = {
	data: PropTypes.object,
	theme: PropTypes.string,
	className: PropTypes.string,
	hasContainer: PropTypes.bool
};

export default TipsAndAdvice;
```

## Description

When I running with "flattenTags" as parameter returning 38 data  entries. But it should return only 2 data entries. 
When I running without "flattenTags" as parameter returning 239 data  entries that is correct

**Comment by lannonbr** [comment]
You cannot use parameters right now in static queries (or likely ever). There is plans to make a [`useQuery`](https://gist.github.com/sidharthachatterjee/e0c961fd92ce287dc020939037b915ce) in the future that will support variables, but if you need to pass in a variable, try a [PageQuery](https://www.gatsbyjs.org/docs/page-query/) for now.

**Comment by ghanshyammac** [comment]
Is their any ETA for this because we want dynamic query inside component not at the page level

**Comment by lannonbr** [comment]
No clue, that's something you'd have to ask the Gatsby OSS team.

**Comment by sidharthachatterjee** [comment]
@ghanshyammac `useStaticQuery` as the name suggests is statically extracted at build time and does not support runtime variables. 

Please use page queries in case you want to use variables passed in as context. 

> Is their any ETA for this because we want dynamic query inside component not at the page level

Not at the moment. We're experimenting with ideas. 

Thanks!
