### ISSUE TITLE
no support for native lazy loading to gatsby-image (version > 2.1.0) 

### ISSUE THREAD

**Issue by MarwenCH** [gatsbyjs/gatsby#20506]
## Description

native lazy loading **is not supported** in gatsby-image for version >= 2.1.0 in **chrome**.
### Steps to reproduce

package.json 
`"gatsby-image": "2.2.37"`
Card.tsx
`<Img fluid={picture.fluid} alt={picture.title} loading="lazy" />`

### Expected result

Image shoud be loaded only when it is visible on screen ( when user scroll down)

### Actual result

Image loaded even it is not yet visible on the screen
### Environment

  System:
    OS: Linux 4.15 Linux Mint 19.2 (Tina)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
    npm: 6.11.3 - ~/.nvm/versions/node/v12.12.0/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Firefox: 68.0.1
  npmPackages:
    gatsby: 2.18.17 => 2.18.17
    gatsby-cli: 2.8.22 => 2.8.22
    gatsby-image: 2.2.37 => 2.2.37
    gatsby-plugin-mailchimp: 5.1.2 => 5.1.2
    gatsby-plugin-manifest: 2.2.34 => 2.2.34
    gatsby-plugin-netlify: 2.1.30 => 2.1.30
    gatsby-plugin-react-helmet: 3.1.18 => 3.1.18
    gatsby-plugin-react-helmet-canonical-urls: 1.4.0 => 1.4.0
    gatsby-plugin-robots-txt: 1.5.0 => 1.5.0
    gatsby-plugin-sharp: 2.3.10 => 2.3.10
    gatsby-plugin-sitemap: 2.2.24 => 2.2.24
    gatsby-plugin-styled-components: 3.1.16 => 3.1.16
    gatsby-plugin-typescript: ^2.1.23 => 2.1.23
    gatsby-plugin-typescript-checker: ^1.1.1 => 1.1.1
    gatsby-plugin-webpack-bundle-analyzer: 1.0.5 => 1.0.5
    gatsby-source-contentful: 2.1.69 => 2.1.69
    gatsby-transformer-sharp: 2.3.9 => 2.3.9
  npmGlobalPackages:
    gatsby-cli: 2.8.25

**Comment by tcope25** [comment]
Works for me. What version of Chrome are you on?

**Comment by MarwenCH** [comment]
> Works for me. What version of Chrome are you on?

![1](https://user-images.githubusercontent.com/19206246/72081816-72113100-32ff-11ea-9065-aeb5187bac3e.png)

you can check with https://developers.google.com/speed/pagespeed/insights 
website : https://monbanquet.fr/

using `gatsby-image: 2.2.37 `
![capture1](https://user-images.githubusercontent.com/19206246/72081935-aa187400-32ff-11ea-8c08-5d21ff0a6a96.png)

with `"gatsby-image": "2.0.41" `
![capture2](https://user-images.githubusercontent.com/19206246/72082148-f8c60e00-32ff-11ea-863c-485c42606ab4.png)
