### ISSUE TITLE
Be able to build having .proto files inside the project (ie with firebase-admin)

### ISSUE THREAD

**Issue by lucasavila00** [gatsbyjs/gatsby#20510]
## Description

If I try to build a gatsby site that happens to include any library that includes .proto files then I get this error:
```
 ERROR #95313 

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html


  263 |     //if the first dir fails its a real error
  264 |     if(path == _path) {
> 265 |       emitter.emit('error',new Error('error reading first path in the walk '+path+'\n'+err),err);
      | ^
  266 |     }
  267 |   });
  268 | 


  WebpackError: error reading first path in the walk /protos
  
  - walkdir.js:265 EventEmitter.<anonymous>
    node_modules/walkdir/walkdir.js:265:1
  
  - walkdir.js:100 fn
    node_modules/walkdir/walkdir.js:100:1
  
  - walkdir.js:137 statter
    node_modules/walkdir/walkdir.js:137:1
  
  - walkdir.js:269 walkdir
    node_modules/walkdir/walkdir.js:269:1
  
  - walkdir.js:15 Function../node_modules/walkdir/walkdir.js.walkdir.sync
    node_modules/walkdir/walkdir.js:15:1
  
  - grpc.js:50 Object.<anonymous>
    node_modules/google-gax/build/src/grpc.js:50:1
  
  - index.js:33 Object../node_modules/google-gax/build/src/index.js
    node_modules/google-gax/build/src/index.js:33:16
  
  - util.js:18 Object../node_modules/@google-cloud/firestore/build/src/util.js
    node_modules/@google-cloud/firestore/build/src/util.js:18:22
  
  - validate.js:19 Object../node_modules/@google-cloud/firestore/build/src/validate.js
    node_modules/@google-cloud/firestore/build/src/validate.js:19:16
```

It doesn't matter if I never use the file. Just having it inside the project tree will fail to build.

### Steps to reproduce

Clone the minimal repro and follow it's README.me

https://github.com/lucasavila00/gatsby-typesaurus-err-sample

### Expected result

Gatsby should be able to build sites that happens to have .proto files inside the project.

### Actual result

It fails to build.

### Environment

```

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.2 - /usr/local/opt/node@8/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.18.20 => 2.18.20 
    gatsby-plugin-firebase: ^0.1.7 => 0.1.7 
    gatsby-plugin-typescript: ^2.1.25 => 2.1.25 
  npmGlobalPackages:
    gatsby-cli: 2.8.18
```

# Where this is an issue in real life?
Using "universal libraries", ie. ones that have an implementation for the browser and one for the server.
In my repro the problem arises when using typesaurus.

When doing SSR typesaurus thinks it's running on node and imports firebase-admin. Even though I'm not using any of the code while building it will make gatsby fail just because the .proto files are included.

@zeit/ncc had the same error and fixed it on their behalf instead of "upstreaming" to webpack: https://github.com/zeit/ncc/issues/317

https://github.com/zeit/webpack-asset-relocator-loader/pull/12

I don't know if gatsby could work around this...
As my concern is really how to use typesaurus with gatsby there is a sister issue on typesaurus repository: https://github.com/kossnocorp/typesaurus/issues/25

**Comment by wardpeet** [comment]
Hey @lucasavila00,

This one is a bit tricky as typesaurus isn't playing well with SSR. I would suggest doing a dynamic import like what gatsby-plugin-firebase is doing under the hood.

```
useEffect(() => {
  import('typesaurus').then(mod => {
	// use typesaurus in here
  })
})
```

If you want a quickfix, this works too but i'm unsure of all other side-effects it might hold. By default webpack mocks `__dirname` into '/' and you can tell webpack to not do it in node land with the following code. (More info can be found here 
https://webpack.js.org/configuration/node/#node__dirname)

```js
exports.onCreateWebpackConfig = ({ stage, actions }) => {
  if (stage !== "build-html") {
    return;
  }

  actions.setWebpackConfig({
    node: {
      __dirname: true
    }
  });
};
```
