### ISSUE TITLE
Tutorial Part Two: No style tag present after adding gatsby-plugin-typography

### ISSUE THREAD

**Issue by hsribei** [gatsbyjs/gatsby#2051]
At [this point](https://github.com/gatsbyjs/gatsby/blame/8bf416e7e327b82266c1614fd2135f67527a849a/docs/tutorial/part-two/index.md#L119) in the tutorial, after `npm install --save gatsby-plugin-typography` and adding it to `gatsby-config.js`, there should be a `<style>` tag in the `<head>`, but nothing shows up for me. 

No errors on `gatsby develop` or the browser console either. Anything I'm doing wrong? Appreciate hints on debugging this. Thanks!

**Comment by KyleAMathews** [comment]
Perhaps you need to restart `gatsby develop`?

**Comment by hsribei** [comment]
I did that, no luck :/ Also did `gatsby build && gatsby serve` and the `<style>` tag for `gatsby-plugin-typography` is still missing. 

(Sorry for the typo in the first message. It was a `<style>` tag, not a `<script>` that was missing.)

**Comment by KyleAMathews** [comment]
What do expect to be seeing?

**Comment by hsribei** [comment]
The tutorial says:

>Once you load the site, if you inspect the generated HTML using the Chrome developer tools, you'll see that the typography plugin added a `<style>` element to the head with its generated CSS.

![style tag](https://www.gatsbyjs.org/static/2c34a22832b1dd0828ac87fde925622a-0c745.png)

But when I inspect the head there's no style element there.

**Comment by hsribei** [comment]
Ok, I started the tutorial from scratch and now somehow it works. Can't reproduce it anymore. I'm guessing I might have left the `gatsby-config.js` in the wrong path, could be something else. Sorry for the trouble, closing this.
