### ISSUE TITLE
[gatsby-plugin-feed] - how to access the html that gatsby has already generated

### ISSUE THREAD

**Issue by dylanjha** [gatsbyjs/gatsby#20518]
## Relevant information

I'm really trying to find a way to use `gatsby-plugin-feed` to generate an RSS feed for a blog.

Here's what I'm running into:

1. Blog created via [gatsby-source-sanity](https://github.com/sanity-io/gatsby-source-sanity) - no issues with this source, it works great
1. `gatsby-source-sanity` does NOT give me raw html back in the graphql query, it gives me back structured json. In my pages, I pass the structured json into react components that eventually render html.
1. In all the examples I see for `gatsby-plugin-feed` I see this pattern:
    1. query graphql - get back html
    1. in the `serialize` function, return an object with `custom_elements` that include something like `edge.node.html`

My problem is, `gatsby-source-sanity` doesn't give me html, so in the graphql query for `allSanityPost` I'm not able to get the html that I need to pass into `custom_elements`.

----

**My question** At some point in the build process, gatsby is turning my sanity posts into nodes that have html, how can I access the html that gatsby has already built and use that to create my RSS feed?

**Comment by LekoArts** [comment]
Hi, please try these options: https://gist.github.com/kmelve/0e4de671d08769cc7c60b948f7e15a29#file-gatsby-config-js-L202-L203

**Comment by dylanjha** [comment]
Thank you, the gist by @kmelve solved it for me :)
