### ISSUE TITLE
Gatsby-link : navigateTo function causes "Window is not defined" error on build

### ISSUE THREAD

**Issue by cyrilepinat** [gatsbyjs/gatsby#2052]
Hello, is this normal that in gatsby-link code navigateTo function is stored in window global var ? it is causing errors "Window is not defined" on build 

for example: 
https://github.com/gatsbyjs/gatsby/blob/0675e275d57bf857fbcf1214849affea40a87b63/packages/gatsby-link/src/index.js#L114

**Comment by KyleAMathews** [comment]
This code shouldn't be called during build (you don't navigate while statically rendering pages).

**Comment by cyrilepinat** [comment]
I was calling navigateTo during componentWillMount for redirection if needed, I moved the call in componentDidMount and it's building fine. So it's ok
