### ISSUE TITLE
Document about the 404 page when handling client-only routes with Gatsby

### ISSUE THREAD

**Issue by ThewBear** [gatsbyjs/gatsby#20526]
## Summary

When handling client-only routes with Gatsby without configuring rewrite on a server, the server will serve the 404 page causing a flickering screen. This behavior should be documented in the docs.

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/client-only-routes-and-user-authentication.md

### Motivation
#10070
#19394
https://stackoverflow.com/questions/52051090/gatsbyjs-client-only-paths-goes-to-404-page-when-the-url-is-directly-accessed-in

**Comment by JustFly1984** [comment]
really interested to solve this issue

**Comment by wardpeet** [comment]
Thank you for creating the issue. Are you talking about specific providers?

The stackoverflow seems to have a nice list:

https://stackoverflow.com/questions/52051090/gatsbyjs-client-only-paths-goes-to-404-page-when-the-url-is-directly-accessed-in
```
Netlify: Redirects
Firebase: URL Rewrites
Nginx: Rewrite Directions
Apache: Mod_Rewrite
Amazon S3: Configuring a Webpage Redirect
Amazon Amplify: Using redirects
Cloudflare: URL Forwarding
```
