### ISSUE TITLE
Errors with Link component when running unit tests

### ISSUE THREAD

**Issue by SheaBelsky** [gatsbyjs/gatsby#20523]
## Description

When running unit tests with components that mount the Gatsby `Link` component, there are errors in the console that only produce themselves in a test environment. They do not appear when serving from the local filesystem or in a production build.

### Steps to reproduce

1. Clone this repository: https://github.com/wayfair/awesome-learning
2. `npm install`
3. `npm run test`

### Expected result

Unit tests that mount a Link should not throw errors regarding the Link component.

### Actual result

Tests that mount the component reveal these errors (but do not cause the test to outright fail.) It's noise more than anything, but it's unnecessary noise in my opinion.

```
Warning: React does not recognize the `activeClassName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activeclassname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

```
Warning: <Link /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
```

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.1 - ~/.nvm/versions/node/v8.16.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0
    Safari: 13.0.1
  npmPackages:
    gatsby: ^2.18.21 => 2.18.21 
    gatsby-plugin-catch-links: ^2.1.24 => 2.1.24 
    gatsby-plugin-google-gtag: ^1.1.20 => 1.1.20 
    gatsby-plugin-manifest: ^2.2.37 => 2.2.37 
    gatsby-plugin-offline: ^3.0.31 => 3.0.31 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21 
    gatsby-plugin-sass: ^2.1.27 => 2.1.27 
    gatsby-plugin-sitemap: ^2.2.25 => 2.2.25 
    gatsby-remark-autolink-headers: ^2.1.23 => 2.1.23 
    gatsby-remark-copy-linked-files: ^2.1.36 => 2.1.36 
    gatsby-remark-responsive-iframe: ^2.2.31 => 2.2.31 
    gatsby-source-filesystem: ^2.1.46 => 2.1.46 
    gatsby-transformer-remark: ^2.6.48 => 2.6.48

**Comment by g1eny0ung** [comment]
This is because of the Link mock in your project act as a string.

It's recommended to refer: https://www.gatsbyjs.org/docs/unit-testing/#3-useful-mocks-to-complete-your-testing-environment

**Comment by sidharthachatterjee** [comment]
You'll want to update the mocks in https://github.com/wayfair/awesome-learning/blob/master/tests/__mocks__/gatsby.js

They're currently setting `Link` to a `String`

Instead, we recommend (https://www.gatsbyjs.org/docs/unit-testing/#3-useful-mocks-to-complete-your-testing-environment)
```
const React = require("react")
const gatsby = jest.requireActual("gatsby")
module.exports = {
  ...gatsby,
  graphql: jest.fn(),
  Link: jest.fn().mockImplementation(
    // these props are invalid for an `a` tag
    ({
      activeClassName,
      activeStyle,
      getProps,
      innerRef,
      partiallyActive,
      ref,
      replace,
      to,
      ...rest
    }) =>
      React.createElement("a", {
        ...rest,
        href: to,
      })
  ),
  StaticQuery: jest.fn(),
  useStaticQuery: jest.fn(),
}
```

Went ahead and opened a PR 🙂 

Closing this issue. Thanks!
