### ISSUE TITLE
Gatsby Store has changed its implementation

### ISSUE THREAD

**Issue by ThewBear** [gatsbyjs/gatsby#20525]
## Summary
Gatsby store is mentioned in the docs as an example of client routing and authentication. However Gatsby store has changed its auth implementation so current gatsby docs isn't up to date.
gatsbyjs/store.gatsbyjs.org#318

https://github.com/gatsbyjs/gatsby/blob/4b6e778f75f531dba4f7dbe6c0af7daec1deac2a/docs/docs/building-a-site-with-authentication.md#L76-L105

**Comment by Developerayo** [comment]
Hey @thewBear can you open a PR here to fix this?
