### ISSUE TITLE
filesystem plugin: possible to query directory?

### ISSUE THREAD

**Issue by thisiscam** [gatsbyjs/gatsby#2053]
I am wondering if the filesystem plugin can query directories? This will be useful e.g. when I want to generate a menu list based on several directories, each having multiple markdown files.

**Comment by jquense** [comment]
have you tried `gatsby-source-filesystem`? It creates nodes for each file in the glob you specify and the files can be queried. File nodes contain fs.stat info as well

**Comment by thisiscam** [comment]
I was probably unclear. I am already using gatsby-source-filesystem

What I'm asking is the ability to query directory instead of file, e.g. I want to list all directories under a certain directory.

I can do this:
```
{
  allFile {
  	edges {
    	node {
      	dir
      }
    }
  }
}
```
but the returned dir won't be unique, plus it won't return empty directories..

**Comment by KyleAMathews** [comment]
This is something new that could be added. We create nodes for files but we could do the same thing for directories. That way you could query them directly as you suggest. Happy you take a PR!

**Comment by KyleAMathews** [comment]
Then you could query directories directly.

**Comment by thisiscam** [comment]
I'm cool with a PR. but how would you imagine the API to look like?

It seems like a more sensible way would be to return all file type directory or not, and let user make queries to perform filtering. Unfortunately this will break the current API

**Comment by thisiscam** [comment]
How can I add [md5-dir](https://github.com/LinusU/md5-dir) to the dependency of the filesystem plugin? Seems like a simple npm install --save inside the package directory won't work...

**Comment by KyleAMathews** [comment]
Why do you need md5-dir?

You just need to create new nodes of type "Directory". Nothing about the existing setup would change or break.

**Comment by thisiscam** [comment]
@KyleAMathews Maybe I misunderstood your goal. Are you saying that it's better to just create another query kind called e.g. allDirs ?

Otherwise, the file node currently uses md5-file to compute a contentDigest, which I can't seem to ignore if I want to use a unified node type.

**Comment by alveshelio** [comment]
Hi guys,

I'm trying to create a menu component that would automatically add items to the menu based on the files in the 'page' directory.

I've checked this page: https://www.gatsbyjs.org/packages/gatsby-source-filesystem/ but I don't understand how I can query the directory and get back the file names.

In my gatsby-config.js I have 2 intances of gatsby-source-filesystem and one of them is:
`{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages/`,
  },`

In the page you say that we can query like so:

`{
  allFile {
    edges {
      node {
        extension
        dir
        modifiedTime
      }
    }
  }
}`

I guess this is a graphQL query, and I guess I need to add another exports.createPages to gatsby-node.js?

Do you guys have an example of something similar to what I'm trying to achieve?

Thank you

**Comment by sandys** [comment]
@KyleAMathews did you ever solve this ? 
We have a usecase where we want to iterate over a bunch of directories - inside each directory I have a jpg and a yml and i want to create a page based on this pair. So I need to loop over directories... and for each directory, get all the files inside.

Currently, allfile and alldirectory dont intersect - so i am not able to use either of them . Is there something I can do ?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
