### ISSUE TITLE
[gatsby-plugin-sass] Accessing the filename of the generated css file

### ISSUE THREAD

**Issue by HarshilShah** [gatsbyjs/gatsby#20547]
## Summary

Currently `gatsby-plugin-sass` generated CSS files with a randomly (to my eye at least) chosen name which is mostly fine for the use case of writing global CSS.

If one wishes to write and import separate CSS stylesheets on a case by case basis, this doesn’t really work. As recommended by @superhawk610 here: https://github.com/gatsbyjs/gatsby/issues/14333#issuecomment-499344433, the best solution to achieve that is to reference the appropriate CSS file using Helmet, however that isn’t really possible given the aforementioned randomly chosen names. If it were possible to have some way to reference the CSS file directly that’d be great.

I realise that CSS-in-JS and CSS modules are ways of achieving this, but still for the use case of having just a handfu of stylesheets and referencing the appropriate one based on say the template this would be really helpful.

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll need to use CSS modules (which also work with SCSS) as you can't access those names. As an alternative you could write your own SCSS -> CSS pipeline and put the CSS files into the static folder: https://www.gatsbyjs.org/docs/static-folder/
I'd recommend using CSS modules!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
