### ISSUE TITLE
www algolia

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [gatsbyjs/gatsby#20546]
Hello, how would you like to know if it is feasible to access the scheme or attributes of algolia, to see how the searches work on the official website.

**Comment by LekoArts** [comment]
Thank you for opening this!

We're using DocSearch: https://community.algolia.com/docsearch/
So there is nothing we can share with you except the component:
https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/search-form.js

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by FranciscoImanolSuarez** [comment]
Well, I'll read the documentation to understand how it works -DocSearch-

**Comment by FranciscoImanolSuarez** [comment]
I'm sorry, I can't understand this, I want to try using that search for my documents and I have a problem according to the error related to the API key or the name, attached capture, can you explain how it would really work? I am using my own Api key and index name

https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/search-form.js

![Captura de pantalla de 2020-01-20 13-45-27](https://user-images.githubusercontent.com/28679360/72743867-3857ea00-3b8b-11ea-810e-1b91aa6f4e26.png)

**Comment by LekoArts** [comment]
Sorry, I can't help you with that. The component is specific to our site and not necessarily able to be used outside of the site - you'll need to read up on their documentation and see what parts you extract/combine. Good luck!
