### ISSUE TITLE
expose a api to write static file

### ISSUE THREAD

**Issue by Austaras** [gatsbyjs/gatsby#20562]
## Summary

Expose a helper function in maybe shared node helper, which write/copy the file/content to `public/static/[contenthash]/[filename]`, and return its new path.

### Basic example

``` js
const file = fs.readFileSync('test.txt')
const newPath = await generateStaticFile(file)
```

### Motivation

When I search for examples for how to deal with static file in gatsby, I find you guys at least write it twice(in `gatsby-remark-images` and `gatsby-remark-copy-linked-files`), so it will be good to standardize this action and it will benefit to other plugins like `gatsby-remark-audio`.

**Comment by wardpeet** [comment]
You can create a webpack plugin and use the emit to support this.

This is a small snippet you can use
```
const path = require(`path`)
const hasha = require(`hasha`)
const fs = require(`fs-extra`)

const file = 'test.txt'
const contentDigest = hasha.fromFileSync(file , { algorithm: `sha1` })
fs.writeFileSync(path.join(`public`, `static`, contentDigest, file)
```

**Comment by Austaras** [comment]
@wagoid sure it isn't hard, I'm just asking is it suitable for gatsby to provide this api. If so, I'd happy to pr it once I have time
