### ISSUE TITLE
React Helmelt doc warning for begginers

### ISSUE THREAD

**Issue by Gitboiboi** [gatsbyjs/gatsby#20563]
Hello,

I know it is a detail but as you seem to make your docs as accessible as possible for begginers I think you might want to put a warning on the react-helmet doc to precise that the Helmet element must be placed inside a div that contains the Helmet AND the content of the page together.

As a react begginer, I spent a few hours not understanding why I got a Webpack error telling me some tag might not be closed properly.

I precise that the doc (and the official react-helmet example provided) only shows the Helmet element alone in a div, wich will make begginers like me think it should be placed alone in that div at the beggining of the file, wich causes the error attached to my message.

Beside that, thanks for your awesome work! Gatsby is the second framework I learn and it has been a pleasure to learn from the tutorial, very clear and easy.

Have a nice day !

![Capture d’écran 2020-01-13 à 02 45 05](https://user-images.githubusercontent.com/41550991/72229419-bc6c0980-35ae-11ea-9c50-f60997502923.png)

**Comment by robinmetral** [comment]
@Gitboiboi welcome to Gatsby, and thanks for reporting!

This is not specific to Gatsby but to [JSX](https://reactjs.org/docs/introducing-jsx.html). As mentioned by the error,

> Adjacent JSX elements must be wrapped in an enclosing tag.

In JSX, you can not render multiple children without a parent element. You can either wrap them in a `div`, or, to avoid creating an extra DOM node, use a [React Fragment](https://reactjs.org/docs/fragments.html):

```jsx
<> // <= React Fragment
  <Helmet {/* your Helmet props */} />
  <Layout>
    {children}
  </Layout>
</>
```

Let me know if this helps, and happy learning!

**Comment by robinmetral** [comment]
@Gitboiboi yes 🙂 Look into styled-components `createGlobalStyles` API, or emotion's `Global` API.

Here's a concrets example with Gatsby on the Gatsby docs: https://www.gatsbyjs.org/docs/emotion/#adding-global-styles-in-gatsby-with-emotion

**Comment by Gitboiboi** [comment]
Wonderfull, thank you very much 😄


Le lun. 13 janv. 2020 à 19:00, Robin Métral <notifications@github.com> a
écrit :
