### ISSUE TITLE
Remove/rewrite redux section from gatsby-magic documentation

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#20565]
## Summary
https://www.gatsbyjs.org/docs/gatsby-magic/ does a great job of explaining the magic behind gatsby. The Redux section, however, isn't correct. Gatsby uses redux internally for holding state & sending out events. It is not used on the website itself. Personally I would remove it from the document as it's just an internal tool (we could have picked any store/event library).

Feel free to not remove it and rewrite it in a way it's more accurate.

@bball07 I think you know best what to do as you were the author of that doc. I'll assign you.

### Motivation

Information isn't 100% accurate and it should :smile:

## Steps to resolve this issue

Remove the redux section from https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-magic.md

**Comment by marcysutton** [comment]
I'd advocate for keeping it in, as it can help clarify how Redux _is_ used in Gatsby as people otherwise won't be able to find details on it.

**Comment by marcysutton** [comment]
Here's another area that illustrates how this should actually be documented, not removed: a stub on data storage with Redux (if still in use) https://www.gatsbyjs.org/docs/data-storage-redux/

**Comment by Jeddf** [comment]
Could I pick this up?

I'm thinkin'
- Add some talk about https://www.gatsbyjs.org/docs/actions/
- Move most of the section that talks about how to use Gatsby in a gatsby app, to the stub and link to it.

**Comment by bball07** [comment]
@Jeddf sure :)

**Comment by Jeddf** [comment]
Still working on this!

I had missed that the stub is part of the _internals_ section of the docs, not a page about how to integrate Redux with a Gatsby app, so I've been spending time reading code.

Have had my fair share of Redux fun in the past so am enjoying it and have made good progress, closing in on a complete draft.
