### ISSUE TITLE
Imports are in the same bundle as `react-dom`

### ISSUE THREAD

**Issue by jojobagings78** [gatsbyjs/gatsby#20577]
Currently having an issue where gatsby is bundling all imports into the same bundle as react-dom which is causing a few small performance issues on the website as well as insights reporting a very high and excessive DOM size.

I have not change any gatsby config so is this generic with the gatsby webpack configuration or what ? Because I have checked a few other websites out that dont include commons file and other that have that are using gatsby.

Imports
`import React from "react"
import { Link } from "gatsby"
import LazyLoad from 'react-lazyload';
import { StaticQuery, useStaticQuery, graphql } from "gatsby"
import Img from "gatsby-image"
import Dropdown from 'react-bootstrap/Dropdown';`

**Comment by sidharthachatterjee** [comment]
The packages you referred to _are_ all included in `commons` along with `react-dom` 

This is intended behaviour. What was the behaviour you were expecting in this case?
