### ISSUE TITLE
Is it possible to use the action "createNodeField" from "sourceNodes" API?

### ISSUE THREAD

**Issue by david-nossebro** [gatsbyjs/gatsby#20573]
I have a use case where I want to add information from the last commit that affected a sourced markdown file. To do this I need to fetch the git information by traversing the git history, but to avoid traversing the same history multiple times, I need to know all files for which I need to fetch the git information first, and then traverse the history only once.

To do this I tried to put my logic in "sourceNodes" like this:

```javascript
// Get all markdown nodes
let mdNodes = getNodes().filter((node) => node.absolutePath && node.absolutePath.endsWith(".md"));

let gitCache = ... code to build git-cache

mdNodes.forEach(n => {
   createNodeField({
      n,
      name: 'git',
      value: gitCache.getLatestCommitInfo(n.absolutePath) //Gives last commit info for given markdown file
});
```

When executing the code I get this error:
`TypeError: Cannot read property 'internal' of undefined`

In the documentation I can´t see anywhere that the "createNodeField" should not be working from "sourceNodes".

**Comment by LekoArts** [comment]
Hi, thanks for the issue! Can you link a reproduction repository?

In the meantime, could you please try using the `onCreateNode` API? You can check for `node.internal.type === 'MarkdownRemark'` to get all markdown files and then push those nodes into an array to use `createNodeField`.

**Comment by david-nossebro** [comment]
@LekoArts, thanks for your response. I´ll try to compile a reproduction repo this afternoon.

If I push all nodes to an array during "onCreateNode", when do I trigger the "createNodeField" functionality? I can only create the git info cache when all markdown nodes are added to the array, and there is no indication of that the "onCreateNode" is called the last time. The next step from my understanding would be "sourceNodes"? Do you mean that I should store the nodes during "onCreateNode" instead of fetching them with the "getNodes()" function?

**Comment by LekoArts** [comment]
Yeah, that's what I meant. In theory `getNodes()` should already work (see: https://www.gatsbyjs.org/docs/gatsby-repl/#getnodes) but somehow your `n` seems undefined as `createNodeField` tries to access `node.internal.type`.

**Comment by david-nossebro** [comment]
Here is a repo with the error I'm getting:
https://github.com/david-nossebro/gatsby-createNodeField-in-sourceNodes

**Comment by david-nossebro** [comment]
In the branch below I tried to collect the nodes in 'onCreateNode' instead, but got the same issue:
https://github.com/david-nossebro/gatsby-createNodeField-in-sourceNodes/tree/load-nodes-in-oncreatenode

However, it seems like 'sourceNodes' is called before 'onCreateNode' is finished? I had to use a sleep method, otherwise the array of nodes was not populated in 'sourceNodes'.

**Comment by david-nossebro** [comment]
I still need this fix (or a workaround).

**Comment by david-nossebro** [comment]
Still needed.

**Comment by jlkiri** [comment]
I'm looking at a signature of `createNodeField` and it looks like this:

```
  { node, name, value, fieldName, fieldValue }: CreateNodeInput,
  plugin: Plugin,
  actionOptions?: ActionOptions
```

Internally it tries to access `internal` property of the destructured `node` but there is no `node`, there is `n` instead. Which means that you cannot use `n`, but `node: n` instead. Does it fix your issue?
