### ISSUE TITLE
Adding fields to frontmatter

### ISSUE THREAD

**Issue by neohed** [gatsbyjs/gatsby#20572]
## Summary
Hi,
I added a new field, "card," to the frontmatter in the .md file for a post.

```
---
slug: test-post
date: "2019-12-30T13:19:01.001Z"
title: 'A Test Post'
description: 'bla bla'
published: true
card: "twitterCard.jpeg"
---
```

The idea is to be able to specify a twitter card image per post.

I then modified the GraphQL query in post.js adding "card" at the end after "slug" and "keywords":

```
export const pageQuery = graphql`
  query($id: String!) {
    site {
      ...site
    }
    mdx(fields: { id: { eq: $id } }) {
      frontmatter {
        title
        date(formatString: "MMMM DD, YYYY")
        author
        banner {
          childImageSharp {
            fluid(maxWidth: 900) {
              ...GatsbyImageSharpFluid_withWebp_tracedSVG
            }
          }
        }
        slug
        keywords
        card
      }
      body
    }
  }
`
```

I thought I could then use this image name to modify the twitter meta tags, but I get an error when trying to build.

> Field "card" of type "File" must have a selection of subfields. Did you mean "card { ... }"?

And in the browser:

> Failed to compile
> There was an error in your GraphQL query:
> 
> Field "card" of type "File" must have a selection of subfields. Did you mean "card { ... }"?
> 
> File: D:/Workspace/Github/neohed-blog/src/templates/post.js

I am completely new to GraphQL!  Only read a few blog posts.  I tried to find where the typedefs for these types are but couldn't find anything...

What am I doing wrong?

### Environment (if relevant)
I'm using gatsby forked from [gatsby-starter-egghead-blog](https://github.com/eggheadio/gatsby-starter-egghead-blog/)

**Comment by LekoArts** [comment]
Hi, thanks for the issue! Let me explain you how to read the error message 👍 

> Field "card" of type "File"

So it tells you that "card" is inferred as type "File". Now the question is: Is that what you want or should it stay of type "String"?

> must have a selection of subfields. Did you mean "card { ... }"

As you can see in your above query on `banner`: It has subfields, namely `childImageSharp` and etc.
Gatsby expects you to also write the query:

```graphql
card {
  childImageSharp { ... }
}
```

**Comment by neohed** [comment]
Thanks for the quick reply.

I want the `card` field to be of type string. I was then going to use the page URL to make an image path.

I tried 2 plugins for twitter card images:

-  gatsby-remark-twitter-cards
-  gatsby-remark-social-cards

but they seemed to generate images. I want to use images I specify.

How do I tell GraphQL that `card` is type String?
Also, can you tell me what image is held in `banner`?

Thanks,

**Comment by LekoArts** [comment]
> How do I tell GraphQL that card is type String?

You can use the `createSchemaCustomization` API: https://www.gatsbyjs.org/docs/schema-customization/#fixing-field-types

So for your this should be (this is untested):

```js
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions
  const typeDefs = `
    type Mdx implements Node {
      frontmatter: Frontmatter
    }

    type Frontmatter {
      card: String
    }
  `
  createTypes(typeDefs)
}
```

This makes `card` optional but always of type `String`. If it should be enforced, write `String!`

> Also, can you tell me what image is held in banner?

Seems like an image above the text: https://github.com/eggheadio/gatsby-starter-egghead-blog/blob/0669b48e51f16b8b464e4bc4081c54be3465d3e1/src/templates/post.js#L61-L75

**Comment by neohed** [comment]
That's brilliant!  Works perfectly, thanks.
