### ISSUE TITLE
gatsby-image producing large size images for iOS devices.

### ISSUE THREAD

**Issue by TheFirstMe** [gatsbyjs/gatsby#20575]
## Description

gatsby-image displays large size images for iOS devices (works fine on android devices) when it should be displaying small size images for mobile devices. 

### Steps to reproduce

Image component used:

```
<Img         
      fluid={image.childImageSharp.fluid} 
      placeholderStyle={{ filter: "blur(15px)" }} 
      alt={name} 
      title={name} 
      backgroundColor 
      onLoad={ () => console.log("Image loaded")} 
/>
```
Query used:

```
allMembers: allExecomMembersJson(
                    filter: { year: { eq: "2019" } }
                  ) {
                      edges {
                        node {
                            execom{
                                members{
                                    name
                                    designation
                                    image{
                                        childImageSharp{
                                            fluid(maxWidth: 180, quality: 80){
                                                ...GatsbyImageSharpFluid_withWebp
                                            }
                                        }
                                    }
                                }
                            }
                        }
                     }
                }
```
### Expected result

gatsby-image should load responsive images according to screen size (Small size images in case of mobile devices)

### Actual result

gatsby-image produced the original large size image on iOS Safari.

### Environment

```

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.18 => 2.18.18 
    gatsby-image: ^2.2.37 => 2.2.37 
    gatsby-plugin-algolia: ^0.5.0 => 0.5.0 
    gatsby-plugin-breadcrumb: ^6.3.0 => 6.3.0 
    gatsby-plugin-catch-links: ^2.1.21 => 2.1.21 
    gatsby-plugin-feed: ^2.3.25 => 2.3.25 
    gatsby-plugin-google-analytics: ^2.1.31 => 2.1.31 
    gatsby-plugin-lodash: ^3.1.18 => 3.1.18 
    gatsby-plugin-manifest: ^2.2.34 => 2.2.34 
    gatsby-plugin-nprogress: ^2.1.17 => 2.1.17 
    gatsby-plugin-react-helmet: ^3.1.18 => 3.1.18 
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sass: ^2.1.26 => 2.1.26 
    gatsby-plugin-sharp: ^2.3.10 => 2.3.10 
    gatsby-plugin-sitemap: ^2.2.24 => 2.2.24 
    gatsby-plugin-styled-components: ^3.1.16 => 3.1.16 
    gatsby-plugin-twitter: ^2.1.17 => 2.1.17 
    gatsby-remark-autolink-headers: ^2.1.22 => 2.1.22 
    gatsby-remark-copy-linked-files: ^2.1.33 => 2.1.33 
    gatsby-remark-images: ^3.1.39 => 3.1.39 
    gatsby-remark-prismjs: ^3.3.29 => 3.3.29 
    gatsby-remark-responsive-iframe: ^2.2.30 => 2.2.30 
    gatsby-source-filesystem: ^2.1.43 => 2.1.43 
    gatsby-transformer-json: ^2.2.22 => 2.2.22 
    gatsby-transformer-remark: ^2.6.45 => 2.6.45 
    gatsby-transformer-sharp: ^2.3.9 => 2.3.9 

```

**Comment by sidharthachatterjee** [comment]
My guess here is what's happening is that iOS is loading a larger size due to Retina? 

Have you tried looking at the network tab in the console when running on iOS and confirming what size loads?

**Comment by TheFirstMe** [comment]
@sidharthachatterjee Unfortunately, I don't have a Mac so I can't test that. But when I checked the link for the image, it was pointing to the original file (the one before processing). This started happening when I updated the outdated npm packages (gatsby and gatsby-image were among them). So when I checked the netlify deploy before updating the npm packages, the correct sized images were loading on iOS (images pointing to processed images, not the original file).

**Comment by TheFirstMe** [comment]
@sidharthachatterjee gatsby 2.4.3 was updated to 2.18.18 and gatsby-image from 2.0.41 to 2.2.37 among many others.

**Comment by sidharthachatterjee** [comment]
@TheFirstMe Interesting. That's useful context. Let me try bisecting changes between those versions.

**Comment by TheFirstMe** [comment]
@sidharthachatterjee I just found out the issue and it was so silly. The query above was used to display images of all members of a group. I used another query to get images of a subset of people from the group. But in the new query, the quality was set to 100. I feel so stupid now. Sorry for any trouble caused. I am closing this issue now.
