### ISSUE TITLE
gatsby-source-wordpress unknown error when you have a post with a PHP fatal error

### ISSUE THREAD

**Issue by jrotering** [gatsbyjs/gatsby#20585]
## Description

I set up a new project using gatsby-source-wordpress pointing at an existing Wordpress site, and it kept failing on the wordpress__POST query.

`Fetching the JSON data from 1 valid API Routes...

=== [ Fetching wordpress__POST ] === https://www.uwalumni.com/wp-json/wp/v2/posts

Total entities : 1921
Pages to be requested : 20
The request failed with error code "undefined"
no routeResponse for  https://www.uwalumni.com/wp-json/wp/v2/posts` 

I have access to the PHP error logs, so I was able to watch them while running the build and determine that one specific page of the paginated query was causing a 500 error. 

`/wp-json/wp/v2/posts?per_page=100&page=8`

Through a lot of trial and error (including adding `orderby=title` to my posts query so I would have a fighting chance), I eventually traced this to a single post that was throwing a Fatal Error. I unpublished the post and was then able to successfully run `gatsby develop` and get all my posts. 

I'm not sure what course of action to suggest in terms of improving gatsby-source-wordpress to address this. Probably something a little more helpful than 'unknown error' would be good... and maybe, if possible, help the user determine which page of results is causing the error.

I mainly just wanted to document my findings in case it helps anyone else who runs into this. 

### Steps to reproduce

- WordPress site with lots of posts so that you have to make multiple paginated calls to the API (you can set a lower perPage value in your options, ie on a site with 80 posts set perPage=10 so that 8 paginated calls are made).
- Set one of your WordPress posts to generate a fatal error. Easiest way I can think of is to write & reference a bad shortcode.
- Point a gatsby project with gatsby-source-wordpress at the WordPress site with the bad post

### Expected result
Gatsby should pull in all of the posts from the paginated requests that are successful, and generate an error for any paginated requests that fail.

### Actual result
No posts are pulled in, and you see `The request failed with error code "undefined"`

### Environment

System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.15.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 69.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.1 => 2.18.1
    gatsby-awesome-pagination: ^0.3.3 => 0.3.5
    gatsby-plugin-lodash: ^3.1.7 => 3.1.15
    gatsby-plugin-netlify: ^2.1.12 => 2.1.25
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.15
    gatsby-plugin-sass: ^2.1.14 => 2.1.23
    gatsby-plugin-sharp: ^2.2.21 => 2.3.2
    gatsby-remark-images: ^3.1.21 => 3.1.32
    gatsby-source-filesystem: ^2.1.22 => 2.1.38
    gatsby-source-wordpress: ^3.1.31 => 3.1.49
    gatsby-transformer-remark: ^2.6.22 => 2.6.37
    gatsby-transformer-sharp: ^2.2.14 => 2.3.5
  npmGlobalPackages:
    gatsby-cli: 2.8.13

**Comment by jrotering** [comment]
I can also re-publish the bad post on my site if anyone wants to use it as an example to reproduce the issue without having to go through the steps. Let me know if this would help.

**Comment by marcospaiva** [comment]
Hi @jrotering !

I had the same mistake!

Apparently, the problem is in the Wordpress server. I still don't understand what happens, but the higher the number of posts, the more likely these parameters will fail.

After many tests, I got a configuration that worked well for me. At the `gatsby-config.js` I put this options:

```
perPage: 5,
verboseOutput: true,
concurrentRequests: 4,
```

**Comment by sidharthachatterjee** [comment]
Thanks for opening this @jrotering 

While the issue is on WordPress, `gatsby-source-wordpress` should definitely print a nicer error. 

@TylerBarnes What do you think?

**Comment by TylerBarnes** [comment]
@marcospaiva I believe your issue is different than the original issue. Yours sounds like your server is getting overloaded by the requests, while @jrotering's issue is about 1 post in a list of posts causes an internal error on the WP server.

We should definitely have a nicer error in this case. I think we should print out whatever error the server responded with as well as which endpoint was currently being fetched. I think since it's REST we can't determine which post caused the error (in the list of 100 posts), but if we print the endpoint, at least that endpoint can be visited in a browser or REST client to try to figure out what's going on.

**Comment by TylerBarnes** [comment]
One more thing! The next major version of `gatsby-source-wordpress` will use WPGraphQL, so we will receive clearer errors from the server and that will be a huge help for those that upgrade.
