### ISSUE TITLE
IE10 - page scrolled down immediately on load

### ISSUE THREAD

**Issue by andrejpavlovic** [gatsbyjs/gatsby#20582]
## Description

When opening any gatsby page in IE10, the page is immediately scrolled down by a couple of hundred pixels (varies by screen size).

### Steps to reproduce

Using IE10, go to https://www.gatsbyjs.org/ for example.

### Expected result

Once page loads and hydrates, it should stay at the top (not scrolled down)
 
### Actual result

The page is scrolled down.

### Environment
Gatsby 2.15.9

### Details

After some digging around and going through past releases, looks like the regression was introduced by this IE10-specific fix: https://github.com/gatsbyjs/gatsby/pull/13027 (version 2.3.7 and onward)

The call to `document.documentElement.doScroll()` in https://github.com/mikaelkristiansson/domready/blob/0e1e0fd082cc161b909f809390782e7f70396cc4/src/ready.js#L19 seems to be causing the page to automatically scroll on load

**Comment by pieh** [comment]
I'll mark this as upstream. Seems like @mikaelkristiansson is already looking into it ( https://github.com/ded/domready/pull/59#issuecomment-573894249 )

**Comment by andrejpavlovic** [comment]
Issue seems to have been fixed in @mikaelkristiansson/domready v1.0.10

**Comment by sidharthachatterjee** [comment]
Looks like this has been fixed upstream (https://github.com/mikaelkristiansson/domready/commit/689caa8dfbf2bfeab1f25bd9ed860416ad364682) and updated in Gatsby's dependencies as well (https://github.com/gatsbyjs/gatsby/pull/20617)

Thanks everyone!
