### ISSUE TITLE
[gatsby-source-graphql]: Support changing the internal type name

### ISSUE THREAD

**Issue by lrholmes** [gatsbyjs/gatsby#20599]
## Summary

When using `gatsby-source-graphql` alongside another package that implements this, such as `gatsby-source-prismic-graphql` (https://github.com/birkir/gatsby-source-prismic-graphql), we are running into an error due to a conflicting `internal.type` value.

The error looks like this:
```
The plugin "gatsby-source-graphql" created a node of a type owned by another plugin.
The node type "GraphQLSource" is owned by "gatsby-source-prismic-graphql".
```

and there is discussion around the issue here: https://github.com/birkir/gatsby-source-prismic-graphql/issues/29. It can be recreated simply by including both `gatsby-source-graphql` and `gatsby-source-prismic-graphql` as plugins in `gatsby-config.js`.

We were able to overcome this issue easily by reimplementing the `gatsby-source-graphql` module - copy-pasting most of the logic, and just changing the internal type name. However it would be great to be able to continue using the module directly.

Because of this, I wonder if it might be a good idea to enable developers to overwrite the internal type name for cases such as this, or even better do something like append the `fieldName` value to the `internal.type` name to make clashes like this less common (unless there is a better solution altogether?).

**I will gladly make the PR for this change, if a maintainer can confirm that they'd be happy to merge a solution.**

Thank you! 🙏

**Comment by pieh** [comment]
Ok, this is difficult problem. The way that:
 - `gatsby-source-prismic-graphql` imports `sourceNodes` from `gatsby-source-graphql-universal/gatsby-node` ( https://github.com/birkir/gatsby-source-prismic-graphql/blob/29256bf921829769f34c68a1707e0e2afd36e85a/packages/gatsby-source-prismic-graphql/src/gatsby-node.ts#L3 )
 - `gatsby-source-graphql-universal` import `sourceNodes` from `gatsby-source-graphql/gatsby-node` ( https://github.com/birkir/gatsby-source-graphql-universal/blob/a68e20d0cad230a778928809300959a95a536788/src/gatsby-node.js#L1 )

Is bound to generate conflicts when using either `gatsby-source-graphql` or `gatsby-source-graphql-universal` with `gatsby-source-prismic-graphql`

Tho there is undocumented way to force node owner by using second argument to `createNode` call - we do this here - https://github.com/gatsbyjs/gatsby/blob/cc4ad7db244b00b2f9196f7da04e40894c5b2bdf/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L242-L246

So maybe applying same trick inside `gatsby-source-graphql` for `GraphQLSource` nodes would be solution (if we decide that way that those plugin import internals of other plugins is fine).

/cc @freiksenet Thoughts on the pattern that those plugin use? Would you suggest different approach for them?
