### ISSUE TITLE
Bug in Gatsby preview when a new build is deployed

### ISSUE THREAD

**Issue by dylanjha** [gatsbyjs/gatsby#20600]
I reported to @sidharthachatterjee vida email and was directed here, as it's suspected to be a Gatsby OSS issue.

## Description

When using Gatsby Preview with a deployed gatsby application the page loads fine and content is updated as expected.

When a new build is pushed to Gatsby Preview, the page breaks. Perhaps this is reproducible outside of Gatsby Preview, but I'm not sure how to go about it (it doesn't happen in development mode, presumably b/c react's hot reloading handles fetching new javascript)

<img width="1329" alt="gatsby-preview_2020-01-14_08-22-38" src="https://user-images.githubusercontent.com/764988/72373531-4eface80-36bd-11ea-8641-e6f77d09e3b1.png">

### Steps to reproduce

1. Set up a Gatsby Preview site
1. Connect github to the master branch of your gatsby project
1. Deploy and see that Gatsby preview is working
1. Merge a new PR into master on github - this should trigger a new build for Gatsby Preview
1. See that the Gatsby preview page breaks, which appears to be because the hash of the hot-update.json file changed

### Expected result

1. The page should not break

### Actual result

1. The page broke

### Gatsby Info

```

  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.17.0 - /var/folders/4n/nd5y3s7x00gbr3mk4fq0jv4c0000gn/T/fnm-shell-4328485/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /var/folders/4n/nd5y3s7x00gbr3mk4fq0jv4c0000gn/T/fnm-shell-4328485/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 72.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.13 => 2.18.17 
    gatsby-cli: ^2.4.11 => 2.8.22 
    gatsby-image: ^2.0.29 => 2.2.37 
    gatsby-link: ^2.0.11 => 2.2.27 
    gatsby-plugin-canonical-urls: ^2.0.12 => 2.1.18 
    gatsby-plugin-catch-links: ^2.0.11 => 2.1.21 
    gatsby-plugin-feed: ^2.3.25 => 2.3.25 
    gatsby-plugin-google-tagmanager: ^2.0.9 => 2.1.20 
    gatsby-plugin-intercom-spa: ^0.1.0 => 0.1.0 
    gatsby-plugin-layout: ^1.0.12 => 1.1.18 
    gatsby-plugin-mdx: ^1.0.62 => 1.0.64 
    gatsby-plugin-netlify: ^2.0.11 => 2.1.30 
    gatsby-plugin-react-helmet: ^3.0.6 => 3.1.18 
    gatsby-plugin-sharp: ^2.3.9 => 2.3.10 
    gatsby-plugin-sitemap: ^2.0.5 => 2.2.24 
    gatsby-plugin-styled-components: ^3.0.6 => 3.1.16 
    gatsby-remark-autolink-headers: ^2.0.14 => 2.1.21 
    gatsby-remark-prismjs: ^3.2.4 => 3.3.28 
    gatsby-source-airtable: ^2.0.10 => 2.0.12 
    gatsby-source-filesystem: ^2.1.38 => 2.1.43 
    gatsby-source-sanity: ^5.0.4 => 5.0.5 
    gatsby-transformer-remark: ^2.2.5 => 2.6.45 
    gatsby-transformer-sharp: ^2.1.14 => 2.3.9 
```

### Diff of the code that was changed when this bug happened

<img width="1495" alt="gatsby-preview-diff_2020-01-14_21-07-40" src="https://user-images.githubusercontent.com/764988/72406677-f0137480-3711-11ea-9d74-235441702638.png">

**Comment by pieh** [comment]
What kind of changes (in PR) are you making? I just tried this with smallest component change and couldn't reproduce, which indicate to me that there must be something specific at work here that triggers this.

Also, please share output of `gatsby info` (package versions is what I'm most interested in).

**Comment by dylanjha** [comment]
@pieh thanks so much for looking into this.

Gatsby info is included now. Sorry about that, I saw the note and I totally forgot.

WRT your other question I put a screenshot of the diff in the PR that triggered - two line change. One change to gatsby-node and one change to one of the components that was used on the page that reloaded.

**Comment by pieh** [comment]
Does your project by any chance implements [`onCreateDevServer`](https://www.gatsbyjs.org/docs/node-apis/#onCreateDevServer) API in gatsby-node? (depending on implementation of that, it could cause issue like that)

**Comment by dylanjha** [comment]
@pieh good thinking. I checked this project, we're not implementing that API.

In gatsby-node we'are doing things like `createPages`, `onCreateNode`, `onCreatePage`, `sourceNodes`

**Comment by dylanjha** [comment]
@pieh I don't think this is stale... maybe you have more insight?

Next time I'll deploy I'll see if it happens, but as far as I know, it's still an issue.

**Comment by pieh** [comment]
Did this happen again @dylanjha? I don't have any insight into this

**Comment by dylanjha** [comment]
I haven't seen it again, let's hope it's resolved. If I see it again, I'll re-open. Thank you!
