### ISSUE TITLE
Gatsby Deploy Issue

### ISSUE THREAD

**Issue by AydenMusles** [gatsbyjs/gatsby#20601]
## Description

My Gatsby repository on github will not deploy to Netlify. https://github.com/AydenMusles/gatsby-starter-storefront-shopify

**Comment by pieh** [comment]
Please provide more details - what exactly happens? What are the errors (if there are any)?

**Comment by sidharthachatterjee** [comment]
@AydenMusles Could you please post logs from the build on Netlify so we can investigate what's failing? Thanks!

**Comment by sidharthachatterjee** [comment]
Let's close this for now. Please feel free to reopen with more details. Thanks!
