### ISSUE TITLE
[gatsby-transformer-sharp] errors copying files

### ISSUE THREAD

**Issue by denisbabineau** [gatsbyjs/gatsby#20602]
## Description

When I run `gatsby develop` I randomly encounter many errors (in some cases / environments always happening) similar to the following (with `unlink` or `chmod` syscall):

```
 ERROR 

error copying file from /project/.cache/gatsby-source-filesystem/c15bd9f18d6833c5dd8e5b404f866e89/DrawExampleNoHyphen.png to /project/public/static/DrawExampleNoHyphen-81a5fc052b034037ac401c7b26d96a89.png { [Error: ENOENT: no such file or directory, chmod '/project/public/static/DrawExampleNoHyphen-81a5fc052b034037ac401c7b26d96a89.png']
  errno: -2,
  code: 'ENOENT',
  syscall: 'chmod',
  path:
   '/project/public/static/DrawExampleNoHyphen-81a5fc052b034037ac401c7b26d96a89.png' }
```

The files are copied in the destination regardless of the errors displayed. Investigating this further I've isolated it to multiple async calls to `fsExtra.copy()` in `createFields()` for the same file which the underlying `fs-extra` can't handle properly when overwriting files.

I was able to resolve this locally by replacing the async call with sync `fsExtra.copySync()` which may make more sense given the paired `fsExtra.existsSync()` call beforehand. However a similar issue (https://github.com/gatsbyjs/gatsby/issues/4709) was fixed in `gatsby-transformer-remark` using a different approach to preven the duplicate calls in the first place which might be preferred.

### Steps to reproduce

Unfortunately not able to easily reproduce in a sandbox

### Expected result

No errors

### Actual result

Errors described above

### Environment

gatsby-transformer-sharp@2.3.12

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.npm-global/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.11.3 - ~/.npm-global/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Safari: 13.0.4
  npmPackages:
    gatsby-plugin-eslint: ^2.0.5 => 2.0.8 
  npmGlobalPackages:
    gatsby-cli: 2.8.26

**Comment by pieh** [comment]
Assuming we are talking about this code path:

https://github.com/gatsbyjs/gatsby/blob/cc4ad7db244b00b2f9196f7da04e40894c5b2bdf/packages/gatsby-transformer-sharp/src/customize-schema.js#L431-L440

My approach here would be to keep track of `fs(extra).copy` that already "started":

```diff
-       if (!fsExtra.existsSync(publicPath)) {
+       if (!fsExtra.existsSync(publicPath) && !inProgressCopy.has(publicPath)) {
+         // keep track of in progress copy
+         inProgressCopy.add(publicPath)
          fsExtra.copy(details.absolutePath, publicPath, err => {
+           // this is no longer in progress, we should rely on `existSync`
+           inProgressCopy.remove(publicPath)
            if (err) {
              console.error(
                `error copying file from ${details.absolutePath} to ${publicPath}`,
                err
              )
            }
          })
        }
```

and somewhere above (maybe it root scope of the module) init `inProgressCopy`:

```
const inProgressCopy = new Set()
```

The Sync variant will block Node.js event loop so we should not use it, unless we have very good reason to do so. If we have means to "lock" it in other ways, usually that's good idea.
