### ISSUE TITLE
Gatsby GraphQL queries, fragments, gatsby cache - best practices

### ISSUE THREAD

**Issue by Jaikant** [gatsbyjs/gatsby#20614]
Are there any best practices while writing queries across the various files gatsby-node, template files,  pages and components. For example, some questions being -

- Does gatsby fetch every query from the remote server or does it fetch it from the cache if available? 

- Is it beneficial to do a large query within gatsby-node and pass it as a pageContext or do a smaller query and let the template file fire another specific query? 

- If we have the same query at multiple places with different fields, is it better to have just one query with the superset of fields and use gatsby-node to pass the data as pageContext? Example being a single page, which uses a subset of a query which is used in a template file.

- I have used apollo client and the apollo cache is a great example. Does Gatsby cache function similarly? Insights?

**Comment by vladar** [comment]
Those are very good questions!

Pretty sure you saw this, but if not, you may find [this section in docs](https://www.gatsbyjs.org/docs/graphql/) relevant.

We also acknowledge that GraphQL docs could be improved and have a separate issue for it: #15231 

I encourage you to comment there with topics missing in docs. This way we can keep issues better localized. But if you feel that we need a separate set of documents - we can probably keep this issue open.
