### ISSUE TITLE
gatsby develop throws an error after initializing default project

### ISSUE THREAD

**Issue by aviramga** [gatsbyjs/gatsby#2061]
Hi,

I've just installed gatsby and started a new project (default starter).
Running gatsby develop I get the following error:
/yurnalist/dist/reporters/console/console-reporter.js:93
cols[i] = Math.max(...widths);
                         ^^^
SyntaxError: Unexpected token ...

Any idea why?

Thanks

UPDATE: I've tried other layouts with the same issue.
Im running it on a Mac Pro with Sierra and the latest gatsby-cli

**Comment by aviramga** [comment]
Solution: Use yarn and make sure you have node > 4.6

**Comment by mattcotter** [comment]
Just FYI, I was running into this exact issue and this post was the first result that came up in Google.

Instead of using Yarn though, I just removed the "..." on line 93 and it started right up. No yarn required.

**Comment by KyleAMathews** [comment]
@mattcotter what version of Node are you using?

**Comment by mattcotter** [comment]
Yikes - it was running v4.5.0 lol It was on an older desktop that I was forced to develop on the other day out of necessity. I thought I had upgraded Node on it recently but I guess I was wrong.

**Comment by solarkraft** [comment]
The introduction states Gatsby to be compatible down to node 4 and npm 3. This apparently does not apply to the CLI. Seems like it'd be a good idea to edit the intro accordingly.
