### ISSUE TITLE
SSR doesn't seems to work

### ISSUE THREAD

**Issue by blatinier** [gatsbyjs/gatsby#20628]
## Description

My website doesn't seem to have working SSR.
When I curl it, no html is there, only a bunch of scripts

### Steps to reproduce

Reproducable steps are kind of hard to get since it's a quite big website with multiple months of development…

### Expected result

Full html with div and other stuffs

### Actual result

Lots of scripts tags, no other html.

### Environment

```
  System:
    OS: Linux 4.9 Debian GNU/Linux bullseye/sid undefined
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Shell: 5.0.11 - /bin/bash
  Binaries:
    Node: 12.8.0 - ~/.nvm/versions/node/v12.8.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v12.8.0/bin/npm
  Languages:
    Python: 2.7.17 - /home/benoit/.pyenv/shims/python
  Browsers:
    Firefox: 72.0.1
  npmPackages:
    gatsby: ^2.18.22 => 2.18.22 
    gatsby-background-image: ^0.8.15 => 0.8.19 
    gatsby-image: ^2.2.38 => 2.2.38 
    gatsby-plugin-google-tagmanager: ^2.1.20 => 2.1.20 
    gatsby-plugin-gtag: ^1.0.12 => 1.0.12 
    gatsby-plugin-manifest: ^2.2.37 => 2.2.37 
    gatsby-plugin-offline: ^3.0.11 => 3.0.32 
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.18 
    gatsby-plugin-react-redux: ^1.0.10 => 1.0.10 
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2 
    gatsby-plugin-sharp: ^2.3.13 => 2.3.13 
    gatsby-plugin-stripe: ^1.2.3 => 1.2.3 
    gatsby-plugin-styled-components: ^3.1.17 => 3.1.17 
    gatsby-plugin-typescript: ^2.1.11 => 2.1.22 
    gatsby-remark-images-contentful: ^2.1.30 => 2.1.30 
    gatsby-source-contentful: ^2.1.76 => 2.1.76 
    gatsby-source-filesystem: ^2.1.28 => 2.1.42 
    gatsby-transformer-sharp: ^2.3.12 => 2.3.12 
    gatsby-transformer-sqip: ^2.1.58 => 2.1.58 
  npmGlobalPackages:
    gatsby-cli: 2.7.54
```

There is no gatsby-ssr.js file.
Here is the gatsby-config:

```
module.exports = {
  siteMetadata: {
    title: `***`,
    description: `***`,
    author: `***`,
  },
  plugins: [
    {
      resolve: `gatsby-plugin-gtag`,
      options: {
        // your google analytics tracking id
        trackingId: `UA-***`,
        head: true,
        anonymize: true,
      },
    },
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `***`,
        short_name: `***`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/icon-48x48.48.png`, // This path is relative to the root of the site.
      },
    },
    `gatsby-plugin-offline`,
    // I tried below conf too, and also no offline plugin too
    //{
    //  resolve: `gatsby-plugin-offline`,
    //  options: {
    //    navigateFallbackWhitelist: [],
    //  }
    //},
    `gatsby-plugin-typescript`,
    `babel-plugin-styled-components`,
    {
      resolve: `gatsby-plugin-styled-components`,
      options: {
        ssr: true,
      },
    },
    {
      resolve: `gatsby-plugin-react-redux`,
      options: {
        pathToCreateStoreModule: "./src/store/index",
        serialize: {
          space: 0,
          isJSON: true,
          unsafe: false,
        },
      },
    },
    {
      resolve: "gatsby-plugin-react-svg",
      options: {
        rule: {
          include: /images/,
        },
      },
    },
    {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: `***`,
        accessToken: `***`,
      },
    },
    {
      resolve: "gatsby-plugin-stripe",
      options: {
        async: true,
      },
    },
    {
      resolve: "gatsby-plugin-google-tagmanager",
      options: {
        id: "GTM-***",
        includeInDevelopment: true,
        defaultDataLayer: { platform: "gatsby" },
      },
    },
  ],
};
```

**Comment by vladar** [comment]
Hi @blatinier !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by sidharthachatterjee** [comment]
@blatinier What does your public directory look like? Do you see `index.html` generated there and does it contain what you expect or is it empty?

**Comment by blatinier** [comment]
@sidharthachatterjee My `index.html` contains all the js chunks tags. but no html redenred.
My guess is that some plugin are interfering on the ssr and kill ohters modification…
Possible culprits: 
 - redux
 - styled-components
 - stripe
 - manifest
 - gtag
 - google-tagmanager
 - react-helmet

I'm trying to get one out without the others but it ain't that easy on my codebase :(

**Comment by sidharthachatterjee** [comment]
@blatinier This isn't likely to be caused by any of those. Can you try removing `gatsby-plugin-offline` and trying to build again?

**Comment by blatinier** [comment]
@sidharthachatterjee  All the same without offline plugin.

**Comment by sidharthachatterjee** [comment]
Interesting @blatinier To further help, we'll need a reproduction. Want to invite me to your repo in case it's private? I'm happy to take a look.

**Comment by blatinier** [comment]
@sidharthachatterjee I setup an example and invited you
If you find anything I'd be delighted!

**Comment by sidharthachatterjee** [comment]
Just took a look and found two issues @blatinier 

1. You have several styled components that wrap the entire site in Layout but no `gatsby-plugin-styled-components`. Please install and add that to your `gatsby-config`
2. You wrap the entire site in Layout with `{ StripeProvider } from 'react-stripe-elements';`

As documented in https://github.com/stripe/react-stripe-elements#server-side-rendering-ssr, to use Stripe with SSR you need to do a bunch of stuff. Fixing this should sort you out. 

Thanks!

**Comment by blatinier** [comment]
@sidharthachatterjee Thanks for having a look at my problem!
I added `gatsby-plugin-styled-components` and configured it. and dropped the stripe provider and it still not working.
I also tried the ssr instruction of the stripe link you gave with no more luck. 
I pushed it into my private repo if you still have time for it.
