### ISSUE TITLE
Include details on blog post fields on gatsby-theme-blog

### ISSUE THREAD

**Issue by Phizzard** [gatsbyjs/gatsby#20631]
#  Summary

When installing and using the gatsby-theme-blog, details past initial installation and configuration are absent. The user has to guess the fields or look through source code to find what blog post fields are available or even required for the theme to work.

Appending information on the blog post fields to the existing readme files of gatsby-theme-blog-core and gatsby-theme-blog should help solve this issue.

### Motivation

We should document this to ensure a smooth theme installation and usage and uphold a standard of giving users all the important information.

#### Blog Post Fields

The following are the defined blog post fields based on the node interface in the schema

| Field    | Type     |
| -------- | -------- |
| id       | String   |
| title    | String   |
| body     | String   |
| slug     | String   |
| date     | Date     |
| tags     | String[] |
| keywords | String[] |
| excerpt  | String   |

**Comment by blainekasten** [comment]
Looks awesome, interested submitting a PR? ❤️

**Comment by Phizzard** [comment]
I have 2 separate PRs already submitted!

- gatsby-theme-blog #20632 (Has 1 approval, waiting for 1 more)
- gatsby-theme-blog-core #20633 (Has 0 approval, waiting for 2)

**Comment by blainekasten** [comment]
MERGED AND THANK YOU!!
