### ISSUE TITLE
[gatsby-remark-embed-snippet] Does this plugin work in MDX files?

### ISSUE THREAD

**Issue by DRiFTy17** [gatsbyjs/gatsby#20645]
## Summary

I'm trying to use gatsby-remark-embed-snippet in an .mdx file, but I'm not having any luck getting it working. Is this supported, or does it only work in .md files without the gatsby-plugin-mdx plugin?

I followed the guidance here:
https://www.gatsbyjs.org/packages/gatsby-remark-embed-snippet/

I also made sure to follow this working gatsby example app here:
https://codesandbox.io/s/github/gatsbyjs/gatsby/tree/master/examples/using-remark?from-embed

Here is what the code looks like in my test.mdx file:
```
import PageCardLayout from '../components/layouts/page-card-layout';
export default PageCardLayout;

# Test

`embed:plain.js`
```

The plain.js file lives under `src/code-examples`, has code in it, and I can see it being picked up by gatsby-source-filesystem as well.

See my gatsby-config.js below. I've tried quite a few variations of it, as well as passing the plugins to the mdx plugin options (current version below).

## Relevant information

The page renders fine in my site, but I just see the following:

![image](https://user-images.githubusercontent.com/2653457/72534580-0ff78500-3845-11ea-96d2-34949626d968.png)

### File contents (if changed)

`gatsby-config.js`:
```
module.exports = {
  plugins: [
    `gatsby-plugin-react-helmet`,    
    {
      resolve: `gatsby-plugin-layout`,
      options: {
        component: require.resolve(`./src/components/layout`),
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `code-examples`,
        path: `${__dirname}/src/code-examples`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        gatsbyRemarkPlugins: [
          {
            resolve: `gatsby-transformer-remark`,
            options: {
              plugins: [
                {
                  resolve: `gatsby-remark-embed-snippet`,
                  options: {
                    directory: `${__dirname}/src/code-examples/`
                  },
                },
                {
                  resolve: `gatsby-remark-prismjs`,
                  options: {
                    classPrefix: "language-",
                    showLineNumbers: true,
                  },
                },
              ],
            },
          }
        ]
      }
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
```

`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by DRiFTy17** [comment]
For anyone else running into this, I figured it out with some trial and error. Might be worth mentioning this on the docs page, but you don't want to include `gatsby-transformer-remark` inside of the `gatsbyRemarkPlugins` option for `gatsby-plugin-mdx`:

```
{
  resolve: `gatsby-plugin-mdx`,
  options: {
    extensions: [`.mdx`, `.md`],
    gatsbyRemarkPlugins: [
      {
        resolve: `gatsby-remark-embed-snippet`,
        options: {
          directory: `${__dirname}/src/code-examples/`
        },
      },
      {
        resolve: `gatsby-remark-prismjs`,
        options: {},
      }
    ]
  }
}
```

**Comment by kimbaudi** [comment]
I also managed to embed snippets in mdx files using `gatsby-remark-embed-snippet` with the following configuration in `gatsby-config.js`:

```js
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        gatsbyRemarkPlugins: [`gatsby-remark-embed-snippet`],
      },
    },
```

However, I notice that the embedded snippet is wrapped in `<p>` tags and normal code blocks are not. The wrapping of the `<p>` tag is throwing `validateDOMNesting` error since certain elements (i.e., `<pre>` and `<div>`) cannot be descendants of `<p>`.

For example, the following mdx file

```raw
``js
console.log('hello')
``

`embed:hello.js`
```

will become

```html
<pre>
  <code class="language-js">console.log('hello')</code>
</pre>
<p>
  <pre>
      <code class="language-js">console.log('hello')</code>
  </pre>
</p>
```

So `gatsby-remark-embed-snippet` works with mdx, but wraps code in `<p>` tag and causes `validateDOMNesting` error.

**Comment by falconmick** [comment]
I am having this issue @DRiFTy17 @kimbaudi and I have been unable to fix it.

This is where I am configuring it:
https://github.com/falconmick/blog/blob/post/building-a-button/packages/gatsby-theme-blog-core/gatsby-config.js#L23

and here is where I try to consume it:
https://github.com/falconmick/blog/blob/post/building-a-button/sites/blog/content/posts/2022-03-09-how-to-make-a-button/index.mdx

To understand what's going on in my repo:
my site is split into 5 packages, the blog its self which is under /sites/ and the 4 themes that stack upon eachother to make up the theme that my site utilises. The config I have sent you is for the blog theme, of which my blog posts' MDX renderer is built from. I am yet to configure the Page MDX plugin over in gatsby-theme-page-core but it shouldn't be the cause of the issue.

See a live preview of the site not working here: https://38d23372.blog-ctg.pages.dev/blog/2022/03/how-to-make-a-button/

If anyone has a working Gatsby 4 project running with this maybe they could share the repo?
