### ISSUE TITLE
Wrong presentationWidth of uploaded image

### ISSUE THREAD

**Issue by dongepulango** [gatsbyjs/gatsby#20647]
I'm using Gatsby and WPGraphQL to build my site and I came to this error.

I uploaded an image with a width of **`1320px`** but somehow the **`presentationWidth`** is only **`800`**.
Did I miss something here? Why did Gatsby reduced it to 800?
Thanks in advance.

**Comment by blainekasten** [comment]
Hey @dongepulango!

This is the logic that sets the `presentationWidth`: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js#L335-L342

And here is a the README for gatsby-image that relates to image sizing. https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/README.md#avoiding-stretched-images-using-the-fluid-type

For now I'm going to close this issue as there isn't any problems relating to gatsby's code here. More than happy to keep discussing though to figure out, so please reply if you're situation can't be resolved through those 2 links.

If you're having trouble figuring it out, seeing some of the code would be helpful!
