### ISSUE TITLE
Client side Env. vars - different behavior between .env.*** files and OS env vars.

### ISSUE THREAD

**Issue by salvoravida** [gatsbyjs/gatsby#20646]
https://www.gatsbyjs.org/docs/environment-variables/#client-side-javascript

it is inconsistent the different behavior of reading env vars between dot.env files and OS ones.

i suggest to filter only GATSBY_* vars also when reading from
.env.development or env.production (like react-scripts "REACT_APP")

Don't let people develop with some env vars in .env.development like MY_APP_BACKEND
and then discover that production build is corrupted because OS vars are filtered by GATSBY_ prefix.

**Comment by blainekasten** [comment]
Hey @salvoravida!

Thanks for pointing out this inconsistency. I can understand where you are coming from. I'm curious did this trip you and cause you to spend time researching or how did you stumble upon this inconsistency?

> and then discover that production build is corrupted because OS vars are filtered by GATSBY_ prefix.

I'm also not sure I understand, how the build is "corrupted", can you explain?

Lastly, Gatsby wants to create a safe space for everyone! Safe for you, other contributors, and the core team. Creating issues with potentially rude or sarcastic statements are not welcome here. Let's try to keep this conversation going with positive tones and sort out how Gatsby could be improved for everyone here. ❤️

**Comment by salvoravida** [comment]
First of all, i want to say that i opened this issue to contribute to gatsbyJS as it is a great framework and i just want to be always better!

That said, 
i spent a some time before i suspect that "gatsby build" process could have filtered OS env vars:

1) i start a new project and i use a .env.development file with some vars like BACKEND_SERVER_HOST etc..., of course all works as expected
2) then i tested from a "local" build .env.production vars to test and connect to the remote backend.
all works as expected
3) finally i started a new project on Zeit now.sh (think just as any CI deployment process) and configured on the ENV vars on CI process OS (with it's CLI)
4) run deploy, test the online build and BACKEND_SERVER_HOST was "" !

Then i spent about half day to debug,
first i suspect that the problem was my "yarn workspaces" project and the nested build packanges...
then i suspect i have done an error on NOW cli while configure ENV vars,
etc...

at the end i search online GATSBY env var, i read
https://www.gatsbyjs.org/docs/environment-variables/#client-side-javascript
the inconsistent behavior!

Ok, i now that we should first read the official docs, but there are many "standard" or just ecxpected behavior that as you can think, all of us devs expected without read every docs!

That's my experience, than it is up to you make a choice!

Anyway good work with gatsbyJS project! 💘

**Comment by salvoravida** [comment]
Just to be clear, i agree that using a prefix like GATSBY_ for custom env vars is ok, but it should be done on .env.xxx files too!

**Comment by blainekasten** [comment]
Closing this in favor of discussion here : #21004
