### ISSUE TITLE
Gatsby Image seems to serve 4 sets of the same image

### ISSUE THREAD

**Issue by valtism** [gatsbyjs/gatsby#20653]
## Description

Using `gatsby-image`'s `<Img />` tag with a fluid image leads to the image being served 4 times on the front end.

### Steps to reproduce

1. Create a new default Gatsby starter
2. Open the default page and look at the console
3. Refresh

### Expected result

The image should be served once

### Actual result

The image is served 4 times despite all being the same

### Environment

```
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /var/folders/kd/xcj3shg91bl96wn3bl4_7k6c0000gn/T/fnm-shell-5309695/bin/node
    npm: 6.13.6 - /var/folders/kd/xcj3shg91bl96wn3bl4_7k6c0000gn/T/fnm-shell-5309695/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5
    gatsby-source-filesystem: ^2.1.40 => 2.1.40
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7
  npmGlobalPackages:
    gatsby-cli: 2.8.27
```

**Comment by StefanNieuwenhuis** [comment]
Can you please provide a screenshot/dump of your console?

**Comment by valtism** [comment]
<img width="734" alt="Screen Shot 2020-01-17 at 10 24 16 am" src="https://user-images.githubusercontent.com/1286001/72600256-95496b00-3913-11ea-94bf-aa7a158989f5.png">

I just realised that this only happens on Safari (not Chrome or Firefox), and only when the resource cache is disabled.

**Comment by valtism** [comment]
They are all the same image, but have different initiators.

<img width="734" alt="Screen Shot 2020-01-17 at 10 29 30 am" src="https://user-images.githubusercontent.com/1286001/72600866-b494c800-3914-11ea-950d-8cfa988ce54c.png">

This one occurs twice.

<img width="734" alt="Screen Shot 2020-01-17 at 10 30 01 am" src="https://user-images.githubusercontent.com/1286001/72600943-caa28880-3914-11ea-8191-8d52695e140a.png">

<img width="734" alt="Screen Shot 2020-01-17 at 10 29 53 am" src="https://user-images.githubusercontent.com/1286001/72600961-d42bf080-3914-11ea-936c-2e8d05efaa63.png">

Then these two fire
