### ISSUE TITLE
chore(gatsby): processing queue is never set with a job id

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#20664]
## Summary

`processing` queue is never set with a job id

## Description

in this line the queue `processing` is defined:

https://github.com/gatsbyjs/gatsby/blob/631ba49765463ab514336a84b9182ec3600c76c1/packages/gatsby/src/query/queue.js#L26

and it is checked i line 45:

https://github.com/gatsbyjs/gatsby/blob/631ba49765463ab514336a84b9182ec3600c76c1/packages/gatsby/src/query/queue.js#L45-L50

and jobs deleted in 

https://github.com/gatsbyjs/gatsby/blob/631ba49765463ab514336a84b9182ec3600c76c1/packages/gatsby/src/query/queue.js#L69

but in this file i can not find a `processing.add()`, maybe there is some hidden place where this is set?

i assume there is a missing command in line 49
```diff
 if (processing.has(job.id)) { 
   waiting.set(job.id, job) 
   cb(`already running`) 
 } else { 
+  processing.add(job.id)
   cb(null, job) 
 } 
   
```

i like to cc @pvdz @vladar for confirmation

**Comment by vladar** [comment]
Heh, looks like it was introduced here: #13061 Before this PR `processing.add` was within the [queue handler](https://github.com/gatsbyjs/gatsby/pull/13061/files#diff-e352d688cfae020eae9fa453b302e792L48-L50). ATM I have no idea if we should restore previous logic or just remove this one.

Just dropping more context here.

**Comment by vladar** [comment]
A quote from @KyleAMathews:

> I don't think processing is necessary any more
> It used to be that there was glitchiness if you updated a node (e.g. by saving a file) at the exact same time that node was being queried as that'd mess up the state
> This PR fixed it by pausing query running whenever nodes were being created / transformed https://github.com/gatsbyjs/gatsby/pull/8859#issuecomment-428020953
> I think processing came from an even earlier attempt at a fix by me and wasn't removed

So I think we are good to remove it. Want to send a PR for this?

**Comment by muescha** [comment]
I will do it

**Comment by muescha** [comment]
PR is #20757 `fix(chore): remove processing and waiting queue`
