### ISSUE TITLE
Throws on empty markdown fields in contentful

### ISSUE THREAD

**Issue by brandonmp** [gatsbyjs/gatsby#2067]
I have an optional field on a Contentful type (with `gatsby-source-contentful`) that holds markdown.

When trying to run `gatsby develop`, nodes with an empty field break the build:

```
The new node didn't pass validation
ValidationError: child "internal" fails because [child "content" fails because ["content" is not allowed to be empty]]
{ id: 'c5YauqPb1uwSOy624aESCWodescriptionOverviewTextNode',
  parent: 'c5YauqPb1uwSOy624aESCWo',
  children: [],
  descriptionOverview: '',
  internal:
   { type: 'contentfulAgencyDescriptionOverviewTextNode',
     mediaType: 'text/markdown',
     content: '',
     contentDigest: 'd41d8cd98f00b204e9800998ecf8427e',
     owner: 'gatsby-source-contentful' } }
```

I thought the problem was from [`on-node-create` in the `source-contentful` repo](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/on-node-create.js), but skipping `createNode()` when `internal.content` is empty doesn't fix the problem.

**Comment by KyleAMathews** [comment]
Oh weird https://github.com/hapijs/joi/issues/251

I'll PR a fix for this real quick.
