### ISSUE TITLE
Slow "update schema" part of the build process

### ISSUE THREAD

**Issue by MartinMikusat** [gatsbyjs/gatsby#20671]
## Description

The "update schema" part of the build process is very slow - close to 20 minutes for only 850 pages. From what I've read it seems that the build process should be much faster than this and considering you're currently looking for projects with 50k+ pages which would take close to 20 hours at this pace. 

Every part of the build process seems reasonably fast, only the "update schema" takes very long and "run queries" also being slower than I would expect.

### Steps to reproduce

Github repo
https://github.com/MartinMikusat/gatsby-reproduce

I've made it create only 50 pages so it doesn't do more work than necessary to make the point and added some instructions in README for making it create all ~850 pages if you want to test it like that as well. It takes too long even with 50 pages.

Just run `npm install` and `gatsby develop`

### Expected result

Running the initial build should be fast

### Actual result

Running the initial build is slow

### Environment

  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12 
    gatsby-image: ^2.2.38 => 2.2.38 
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6 
    gatsby-plugin-postcss: ^2.0.7 => 2.1.19 
    gatsby-source-sanity: ^5.0.5 => 5.0.5

**Comment by vladar** [comment]
@MartinMikusat thanks for bringing this up!

It looks like you put too much data into the page context. You put your whole data set into it:
https://github.com/MartinMikusat/gatsby-reproduce/blob/master/gatsby-node.esm.js#L83

Page context is not meant for passing data to pages. It is meant to pass simple parameters that could be later passed to the GraphQL query of the page as variables.

There is an overhead associated with context - Gatsby has to visit every field of every object in context to infer `SitePageContext` type.

You have pages for 850 nodes (`SanityLens` in your example) and each page context has all the nodes in it. Also, each node has about 30 fields. It means that Gatsby has to visit `850 * 850 * 30` fields (which is approx. 21,7 million fields to visit).

We could do better by showing a warning in cases like this (when the context is not used appropriately)  and we actually have an issue exactly for this problem: #14213

**Comment by MartinMikusat** [comment]
Thanks, that explains it. 

What I thought should be reasonable to do is that I fetch all the data at once, then create the pages one by one based on that data. I also needed all the data on every page, that's why I did it like that.

From what I understand now, I should fetch only enough data to identify each piece of data, give that little piece to the pageContext of the component I want to render, and fetch the corresponding data inside that element. The problem I have right now is that I still need to have all the data in every page. 

Now I have to fetch all the data on every single page which happens to take even more time (and probably counts as API requests). Is there any way to fetch all the data only once and have it available in every page? I've searched for some solutions but found nothing that would solve this.

**Comment by vladar** [comment]
You must also understand that the context is included in `page-data.json` when you build (as well as data returned by your query). So every single page of your site will carry it. I don't think it is a reasonable solution.

I guess you should just explain your use-case in more detail. Then we'll try to help. There are usually several ways to achieve the same goal.

**Comment by MartinMikusat** [comment]
I'm trying to migrate to Gatsby from a React app so I can show you exactly what use case I have with an alpha version of the site.

If you go to https://camerakitbuilder.com/lenses, you get a list of 774 lenses through which you can filter. These are hard-coded, so there are no calls to any servers, it just happens because you have all the data locally. As you can see, it's a viable option. The whole thing is less than 300kb, the filtering is instant and the page has 1.3s TTI on my old notebook. 

You can link to a specific lens though, for example
[https://camerakitbuilder.com/lenses?item=Leica+Super-Vario-Elmar-SL+16-35mm+f/3.5-4.5+ASPH](https://camerakitbuilder.com/lenses?item=Leica+Super-Vario-Elmar-SL+16-35mm+f/3.5-4.5+ASPH)

Right now, it parses the link, find that lens in the list of all of them and shows it.

I want to move to Gatsby for the SSR, the SEO from SSR, and easy PWA support. What I need is a page for each lens but I also need to be able to filter through all of them at that page. So that when I go to [camerakitbuilder.com/lenses/Leica-Super-Vario-Elmar-SL-16-35mm-f3.5-4.5-ASPH](https://camerakitbuilder.com/lenses/Leica-Super-Vario-Elmar-SL-16-35mm-f3.5-4.5-ASPH), there's a server-rendered page for that lens and the whole UI for filtering through all of the lenses. For that, I need to have all the lenses available somehow. That's why I was putting all of the data into the "pageContext". When I did that it worked but I'm getting that really slow build and now I understand why it happens. 

That said, is there any other way I could achieve the same result? I could fetch the data using Apollo after the initial load but if there's a way to do it with Gatsby I would prefer that.

**Comment by vladar** [comment]
@MartinMikusat Sorry for the delay with response.

You have a couple of viable options here:

1. Create a separate component for a full list of items with a [static query](https://www.gatsbyjs.org/docs/static-vs-normal-queries/). And only fetch individual item data on every page.

2. Have a separate component for a list but fetch JSON data [outside of GraphQL](https://www.gatsbyjs.org/docs/using-gatsby-without-graphql/)

Technically though those options are roughly the same (as gatsby static query is transformed to JSON file for you under the hood on build).

Hope it helps!

**Comment by MartinMikusat** [comment]
Thanks for the reply. I figured out something similar myself at the end but I have since redesigned the whole website completely, so unfortunately I can't show a working example of this for others. I guess I can close this issue now. Thanks again!
