### ISSUE TITLE
Add more global links

### ISSUE THREAD

**Issue by bball07** [gatsbyjs/gatsby#20678]
## Summary

Going through the PR's and came across this one https://github.com/gatsbyjs/gatsby/pull/20515/files . After reading through the description and supporting documentation and searching our docs for 'sessionStorage' I noticed there was no documentation explaining this global. 

## Steps to resolve this issue

Add more global links to https://www.gatsbyjs.org/docs/porting-from-create-react-app-to-gatsby/#server-side-rendering-and-browser-apis such as:

https://developer.mozilla.org/en-US/docs/Web/API/Window
https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Local_storage
https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage
https://developer.mozilla.org/en-US/docs/Web/API/Window/navigator
https://developer.mozilla.org/en-US/docs/Web/API/document

**Comment by jacobdcastro** [comment]
Are you looking to add separate sections in the Gatsby docs explaining each of the global variables listed? Or would you just like a section explaining 'sessionStorage' in the Gatsby docs? Or just add links to the docs that the reader can go to to learn more about each variable?

**Comment by arku** [comment]
@bball07 I would like to fix this.

/cc @wardpeet
