### ISSUE TITLE
`createNodeField` is not working in `gatsby-remarked` plugin

### ISSUE THREAD

**Issue by crutchcorn** [gatsbyjs/gatsby#20684]
## Description

Describe the issue that you're seeing.

I'm seeing that whenever I use a `gatsby-transformer-remark` plugin that has a `createFieldNode` function call, it does not add said field to the GQL instance

### Steps to reproduce

Add in a `createNodeField` in an example plugin, add said plugin to `gatsby-transformer-remark` plugins array

Load develop version, query for the field name, see that it's not being grabbed and throwing errors 

#### Example Project I'm Seeing This In
https://github.com/unicorn-utterances/unicorn-utterances/blob/fix-count/plugins/count-inline-code/index.js#L21

And include the plugin locally in the `gatsby-config` file:

https://github.com/unicorn-utterances/unicorn-utterances/blob/fix-count/gatsby-config.js#L64

### Expected result

What should happen?

I want to be able to query for a field I've created in the `createNodeField` in the GQL instance

### Actual result

What happened.

I am not able to query the inlineCount of the node I expect that field to be on with the error:

`Cannot query field "inlineCount" on type "MarkdownRemarkFields"`

![Cannot query field \"inlineCount\" on type \"MarkdownRemarkFields\"](https://user-images.githubusercontent.com/9100169/72647123-9e930180-392c-11ea-88c8-c074cff1a2d4.jpeg)

Which is strange, because running through the node debugger diving into the gatsby code, it seems that the `internal` value is being set on the node, as expected:

![A chrome debugger showing `node`'s `inlineCount` being added properly in Gatsby code](https://user-images.githubusercontent.com/9100169/72647303-1a8d4980-392d-11ea-99b3-af403e12eb39.jpeg)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```
  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.15.35 => 2.15.35
    gatsby-image: ^2.2.26 => 2.2.26
    gatsby-plugin-feed: ^2.3.16 => 2.3.16
    gatsby-plugin-google-analytics: ^2.1.21 => 2.1.21
    gatsby-plugin-lunr: ^1.5.2 => 1.5.2
    gatsby-plugin-manifest: ^2.2.21 => 2.2.21
    gatsby-plugin-offline: ^3.0.14 => 3.0.14
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.1.11 => 3.1.11
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-sass: ^2.1.18 => 2.1.18
    gatsby-plugin-sharp: ^2.2.29 => 2.2.29
    gatsby-plugin-sitemap: ^2.2.17 => 2.2.17
    gatsby-plugin-transition-link: ^1.13.0 => 1.13.0
    gatsby-remark-autolink-headers: ^2.1.14 => 2.1.14
    gatsby-remark-copy-linked-files: ^2.1.26 => 2.1.26
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: ^3.1.26 => 3.1.26
    gatsby-remark-images-medium-zoom: ^1.4.0 => 1.4.0
    gatsby-remark-prismjs: ^3.3.18 => 3.3.18
    gatsby-remark-responsive-iframe: ^2.2.23 => 2.2.23
    gatsby-remark-video: ^1.2.4 => 1.2.4
    gatsby-source-filesystem: ^2.1.31 => 2.1.31
    gatsby-transformer-json: ^2.2.13 => 2.2.13
    gatsby-transformer-remark: ^2.6.28 => 2.6.28
    gatsby-transformer-sharp: ^2.2.21 => 2.2.21
```

**Comment by crutchcorn** [comment]
This is still a bug and it's still blocking me in various ways. I plan to, in the next week or so, dive in and see if I can fix it

**Comment by jlkiri** [comment]
I built your project and cannot reproduce the bug... It works for me, i.e. I can query `inlineCount` of any markdown node by id.

<img width="1141" alt="Screen Shot 2020-02-14 at 15 11 26" src="https://user-images.githubusercontent.com/38713361/74506174-59b6b680-4f3c-11ea-9fc7-f1d9e7ebc2c2.png">

**Comment by crutchcorn** [comment]
Golly! I must've been running an old version. This seems to've been fixed. Sorry about that, all!

**Comment by hassankhan** [comment]
Hi @crutchcorn, I think I'm having the same issue. I've got a [Gatsby Remark plugin](https://github.com/cube-js/cube.js/tree/hassankhan/docs/gatsby-page-menu-plugin/docs/plugins/gatsby-page-menu-plugin) as per the Gatsby docs, and in the `index.js` I'm using `createNodeField()` to add a custom field but it won't show up.

Steps to reproduce:

1. Clone https://github.com/cube-js/cube.js
2. Check out the `hassankhan/docs/gatsby-page-menu-plugin` branch
3. Navigate to `docs/` within the repo and run `yarn start`
4. Go to `localhost:8000/__graphql` and use the Explorer to check `markdownRemark.fields`
