### ISSUE TITLE
New Translation Request - Persian

### ISSUE THREAD

**Issue by BaseMax** [gatsbyjs/gatsby#20687]
```yaml
name: Persian
code: fa
maintainers:
  - basemax
  - jassab
```

**Maintainers**

> your experience level in open source

I'm Max, As one of most active programmers, I want to add Persian language.
https://github.com/BaseMax

> your level of experience in the target language and localization

Fluent, No problem.
Also I have native friends.

> how much time you can commit to being a maintainer

I did added Persian to Open Source Friday website recently.
https://opensourcefriday.com/?locale=fa

I want to add Persian for **gatsbyjs** at now.

It's one of problem, This contains many documents. But we decide to do one by one, and It's not easy.

We accept help from other maintainers. @alipiry

**Comment by alipiry** [comment]
Hey @BaseMax, what you're going to do sounds good! Although I've asked the same translation request that you're requesting almost 3 months ago and Gatsby team hasn't respond yet!
BTW, let me know if your request got accepted 🤘

**Comment by alipiry** [comment]
> Hey @BaseMax, what you're going to do sounds good! Although I've asked the same translation request that you're requesting almost 3 months ago and Gatsby team hasn't respond yet!
> BTW, let me know if your request got accepted 🤘
@BaseMax 
Also if you've read the translation guidelines, you would understand how to start translating!

**Comment by tesseralis** [comment]
Hi @alipiry, sorry we haven't gotten around to your translation request yet. If you would still like to participate, would you all mind working together with @BaseMax as maintainers? Then I can create the repo for you.

**Comment by BaseMax** [comment]
Hello,
Thanks you for your reply.

I want to be part of this.
Also I will try and hope find more contributors.

Regards,
Max
-- 
Regards,
Max

**Comment by alipiry** [comment]
> Hi @alipiry, sorry we haven't gotten around to your translation request yet. If you would still like to participate, would you all mind working together with @BaseMax as maintainers? Then I can create the repo for you.

Hi @tesseralis, yeah of course, I'd be happy to participate! Tnx btw.

**Comment by BaseMax** [comment]
> **Nat Alison:** would you all mind working together with @BaseMax as maintainers?

Hello, I agree with it. When we can cooperate and work together?

I hope so.
Cheers,
Max

**Comment by tesseralis** [comment]
@BaseMax sure! I'll close out this issue and add you to the first one that @alipiry created.
