### ISSUE TITLE
Can't use async function to set headers. (gatsby-source-graphql).

### ISSUE THREAD

**Issue by ajmar** [gatsbyjs/gatsby#20690]
## Description

In the gatsby-source-graphql plugin options, the headers object only accepts regular synchronous values. Trying to pass async functions / promises in will set the header to just that.

I was not able to just pass in the result of calling such a function, as Gatsby does not seem to like gatsby-config.js being async, and would throw errors about loading all the active plugins, not to mention making the config a promise would be a bit overkill.

This is needed for my purposes to authenticate using wp-graphql-jwt-authentication, which uses a mutation to get the WP authToken (which goes in the Authorization header), and since Gatsby can only do queries, I am using Apollo Client to run the mutation and get the authToken. But ApolloClient.mutate returns a promise and so cannot presently be used / referenced by gatsby-source-graphql.

### Steps to reproduce

Pass any asynchronous function to the headers object in the gatsby-source-graphql plugin options (gatsby-config.js). For instance:

```
const getAuthToken = async () => {
	return new Promise(resolve => {
		setTimeout(() => {
			resolve('authTokenValue');	
		}, 500);
	});
}
```
```
{
    resolve: "gatsby-source-graphql",
    options: {
        typeName: "WPGraphQL",
        fieldName: "wpgraphql",
        url: "http://localhost:666/wordpress/graphql",
        headers: {
            Authorization: getAuthToken()
        }
    }
}
```

### Expected result

The plugin should use await to execute get the result of the function and then set the header to the result. With the function above, the 'Authorization' header should be set to 'authTokenValue'.

### Actual result

The plugin sets the header to a Promise:

```
headers: {
	Authorization: Promise {
		'authTokenValue'
	}
}
```

### Environment

```
  System:
    OS: Linux 5.4 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
    Shell: 5.0.11 - /bin/bash
  Binaries:
    Node: 13.5.0 - /usr/bin/node
    npm: 6.13.4 - /usr/bin/npm
  Languages:
    Python: 3.8.1 - /usr/bin/python
  Browsers:
    Firefox: 71.0
  npmPackages:
    gatsby: ^2.18.23 => 2.18.23
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-manifest: ^2.2.30 => 2.2.30
    gatsby-plugin-offline: ^3.0.24 => 3.0.24
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sass: ^2.1.24 => 2.1.24
    gatsby-plugin-sharp: ^2.3.4 => 2.3.4
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.1.40 => 2.1.40
    gatsby-source-graphql: ^2.1.28 => 2.1.28
    gatsby-transformer-remark: ^2.6.39 => 2.6.39
    gatsby-transformer-sharp: ^2.3.6 => 2.3.6
  npmGlobalPackages:
    gatsby-cli: 2.8.14
```

### Fixes
https://github.com/ajmar/gatsby/commit/5346c7b31eefc6808f14a423d739965b02cfed57
I put together this commit as a (working) solution to the issue. It simply maps the headers object to an array, loops through it and executes any functions using `await`, then puts the results back into an object.

I made it so that it can be passed functions and not just function calls so that gatsby-config does not need to use async (which resulted in many exceptions anyway).
```

Proposed solution usage:
{
    resolve: "gatsby-source-graphql",
    options: {
        typeName: "WPGraphQL",
        fieldName: "wpgraphql",
        url: "http://localhost:6000/wordpress/graphql",
        headers: {
            Authorization: getAuthToken, // getAuthToken is an async function
            RegularHeader: "regularvalue" // Nothing changes (non-breaking)
        }
    }
}
```

**Comment by wardpeet** [comment]
Hey, we currently do not support any async values in our config. A good workaround would be to fetch your token before running `gatsby build` or `gatsby develop`

We could enable authorization to be an async function inside `gatsby-source-graphql` to fix your issue. Fixing this for gatsby-config will be a bigger challenge.

**Comment by ajmar** [comment]
Hi, yes allowing Authorization (or all headers) to be an async function in gatsby-source-graphql would be a good fix. (This is what the patch I linked above does).

**Comment by wardpeet** [comment]
Oh I missed that snippet, we love to get a PR for it. Please also add tests for this option when you do.

Thank you! 🙏
