### ISSUE TITLE
[docs][workflows] Deploying to other hosting services

### ISSUE THREAD

**Issue by jamstack-elise** [gatsbyjs/gatsby#20691]
Part of the **Top 25 Learning Workflows initiative**. See #13708 for the meta issue that this issue falls under.

# User story
As a new Gatsby user, I want to know other hosting services that can deploy Gatsby that is not listed [here](https://www.gatsbyjs.org/docs/deploying-and-hosting/).

# Evaluation
| Search | Discover | Complete | Linked | Tone | Style | Overall |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| 😐| 😞 | n/a | 😐 | n/a | n/a | 😐 |

# Steps taken to implement
**1. Searchability**
> #### Google
> - Google search keywords: "deploy gatsby" 
> results: 
1st page: no relevant links. A reference to keyword "deploy gatsby to digitalocean" found in related search.
> 3rd page: [Drupal](https://www.drupal.org/project/gatsby_deploy)
> - Google search keywords: "deploy gatsby digitalocean" 
>results: 1st page: [Gatsby GitHub Issue](https://github.com/gatsbyjs/gatsby/issues/5484), Google snippet video tutorials: ([1](https://www.youtube.com/watch?v=E59__Fc5qNM)) ([2](https://www.youtube.com/watch?v=OfzqlUE2TDU)) ([3](https://www.youtube.com/watch?v=oK5yJ2OTJHM))
> - Google search keywords: "deploy gatsby to other hosting services" 
> results: 1st page: [DeployHQ](https://www.deployhq.com/guides/gatsby)

> #### Bing
> - Bing seach keywords: "deploy gatsby" 
> results: 1st page: [DeployHQ](https://www.deployhq.com/guides/gatsby)

**2. Discoverability**
From a "deploy gatsby" search on Google, the first result was [Gatsby's documentation](https://www.gatsbyjs.org/docs/deploying-and-hosting/). I could not find links relating to "Other hosting domains."

**3. Completeness** - n/a
By 2, document discovery is null. Completeness is ∅.

**4. Linkedness**
As a new Gatsby user, perhaps [Adding a Path Prefix](https://www.gatsbyjs.org/docs/path-prefix/), [Multi-Core Builds](https://www.gatsbyjs.org/docs/multi-core-builds/), [Asset Prefix](https://www.gatsbyjs.org/docs/asset-prefix/) could help. In addition, I'd do some discovery on the links found on: "The Gatsby blog also has posts on both [deployment](https://www.gatsbyjs.org/blog/tags/deployment/) and [hosting](https://www.gatsbyjs.org/blog/tags/hosting/)." Cross fingers! 🤞🤞

**5. Tone and accessibility** - n/a
By 2, document discovery is null. Tone & accessibility is ∅.

**6. Style** - n/a 
By 2, document discovery is null. Style is ∅.

# Recommendations
- I agree that an explicit "other options" page is helpful to determine other hosting domain platforms found on the [Top 25 Workflows spreadsheet](https://docs.google.com/spreadsheets/d/175iZyC8khLy1JQncvgyvAD_vXpfsHxswQcn6N7GDeRA/edit#gid=0).
- Ask Gatsby's developer community through an open form what other hosting platforms they are curious about (E.g. GoDaddy, Dreamhost, Bluehost, DigitalOcean, et al).
- Use form data to 
     1. determine other hosting services documentation to generate.
     2. determine what keywords can be used to find already existing tutorials.

**Comment by rationalthinker1** [comment]
It is marked as done but where is the instructions to deploy this manually? I have it on digitalocean.

**Comment by AishaBlake** [comment]
Opening this back up! We weren't quite ready to tackle this work before gatsbot closed it automatically but this is still a priority. If folks in the community would like to work on it, we welcome contributions.

In addition to the initial assessment, I'd like to revisit the quality of _existing_ documentation. We have a _lot_ of options listed and I want to make sure they're still accurate, useful, discoverable, etc. I also wonder if we need to provide any more background information around what's happening when you host a project.

> It is marked as done but where is the instructions to deploy this manually? I have it on digitalocean.

@rationalthinker1 do you mean that you _want_ to see documentation around how to host a Gatsby site on DigitalOcean?

**Comment by rationalthinker1** [comment]
> @rationalthinker1 do you mean that you _want_ to see documentation around how to host a Gatsby site on DigitalOcean?

Hey Aisha, I'm sorry. That's what I meant. I want to host gatsby on digital ocean.

**Comment by AishaBlake** [comment]
Taking another look at this issue, it looks like some things have improved. I'd also like to note that, though the initial line item in the umbrella issue is "Deploying to other hosting services" that's not actually a search I'd assume people are using. It's more likely people are looking for either a specific service or a more general page on "deploying a Gatsby site" which I think we have pretty well covered.

This issue _has_ uncovered a desire for docs on deploying with DigitalOcean. We have a _lot_ of services covered, so I'm going to close this in favor of a new issue specifically calling for a DigitalOcean guide. Some notes on where I think we're at with this:

- Searching "deploy Gatsby" now turns up links to our Deploying and Hosting page first. Most results on the first page of both Google and Bing are either gastbyjs.org or .com
- We now have docs on deploying to 18 different services.
- The docs seem to generally follow the style guide but they've been added over quite a long time and their formatting isn't as consistent as I would like. This might be confusing for users trying to decide where to deploy their Gatsby sites. I'll write up a specific issue for this as well. Thank you both for your input! I really appreciate your interest and effort in making the Gatsby docs even better.
