### ISSUE TITLE
gatsby build giving 404s on image assets when deployed

### ISSUE THREAD

**Issue by MTyson** [gatsbyjs/gatsby#20700]
## Description

gatsby build is failing to load some images

shows 404s for some build assets.

It works in `gatsby develop`

### Steps to reproduce

Go to this website: www.wholisticsoftware.com

### Expected result

The main background image should load

### Actual result

Image remains blurry, errors are seen in console.

take a look at this site:

http://wholisticsoftware.com/

The background image fails to load with this error:

The script from “http://wholisticsoftware.com/component---src-pages-index-js-9a1eac2df65d05ab8479.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
wholisticsoftware.com
Loading failed for the <script> with source “http://wholisticsoftware.com/component---src-pages-index-js-9a1eac2df65d05ab8479.js”. wholisticsoftware.com:124:1
The script from “http://wholisticsoftware.com/app-c537bbf82b58c94a3901.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
wholisticsoftware.com
Loading failed for the <script> with source “http://wholisticsoftware.com/app-c537bbf82b58c94a3901.js”. wholisticsoftware.com:124:1
The script from “http://wholisticsoftware.com/webpack-runtime-d65cff8220bf32f5b5d1.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
wholisticsoftware.com
Loading failed for the <script> with source “http://wholisticsoftware.com/webpack-runtime-d65cff8220bf32f5b5d1.js”.

### Environment

This is on a static hosted website.

**Comment by MTyson** [comment]
I don't know, I guess it's working now.  Deleted /public, ran gatbsy clean and wiped remote server and redeployed.

**Comment by fzyzcjy** [comment]
@MTyson `gatsby clean` and gatsby develop again works for me. Thanks!
