### ISSUE TITLE
Unhelpful error messages for invalid gatsby-config properties

### ISSUE THREAD

**Issue by geeofree** [gatsbyjs/gatsby#20704]
## Description

Running `gatsby develop` or `gatsby build` with an invalid property on `gatsby-config.js` that's not in any of [these](https://github.com/gatsbyjs/gatsby/blob/ea00e523ce5c32040c931bfe4bef081b11b13f68/docs/docs/gatsby-config.md) throws an unhelpful error message. See below:

### gatsby-config.js
![gb-config](https://user-images.githubusercontent.com/17492631/72674544-ffe4dd00-3ab2-11ea-8c41-dbf57c4f975f.png)

### Gatsby's CLI Output
![error](https://user-images.githubusercontent.com/17492631/72674549-0ffcbc80-3ab3-11ea-9b0f-ac5ddef71e4b.png)
 

### Steps to reproduce

1. Go to `gatsby-config.js` and add any property that's not any of [these](https://github.com/gatsbyjs/gatsby/blob/ea00e523ce5c32040c931bfe4bef081b11b13f68/docs/docs/gatsby-config.md)

2. Run `gatsby develop` or `gatsby build` commands

See [repo demo file](https://github.com/geeofree/unhelpful-gatsby-error-demo/blob/master/gatsby-config.js)

### Expected result

What should happen?

### Need to have a useful CLI error messages on gatsby

What happened.

### Environment

![environment](https://user-images.githubusercontent.com/17492631/72674676-4edf4200-3ab4-11ea-854f-fe785dec162f.png)

### P.S.
I'd like to help resolve this issue and file a PR if someone is willing to guide me through the codebase that needs to be looked at. Currently I've only searched for terms such as _dispatch_ as I guess there's a reducer that's firing an effect somewhere but I'm finding it hard which to look for.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!
This could potentially be solved with: https://github.com/gatsbyjs/gatsby/pull/16027
I'll try to make the error message better in: https://github.com/gatsbyjs/gatsby/pull/20597

Related issue: https://github.com/gatsbyjs/gatsby/issues/19941

So I'll work on this but we'd be happy to receive a PR from your for our open issues (e.g. tagged with "help wanted"). Thanks!

**Comment by geeofree** [comment]
Oh. Cool! I'll close this now then. Didn't know this was being worked on already so my b and thanks!
