### ISSUE TITLE
Add option to generate external css file instead of inlining all styles in a `<style>` tag 

### ISSUE THREAD

**Issue by kije** [gatsbyjs/gatsby#20710]
## Summary

Currently, Gatsby inlines **all** CSS styles in a `<style>` tag inside the `<head>`, which is not optimal for most pages (except maybe for pages with very little CSS rules) and prevents crucial performance optimizations like "above-the-fold" critical-path CSS inlining, etc...

Therefore I think there should at least be an option in Gatsby to choose if all styles should be inlined (current behavior) or if an external CSS file should be generated and linked via a `<link>` tag.

### Motivation

Inlining **all** styles in the page is actually very bad for page load and rendering performance, mainly because:

1. The same CSS rules are included in every generated HTML page. This not only hugely increases the size of every HTML page, but also prevents the browser from caching the CSS 
2. The browser needs to download and parse the entire CSS (including CSS rules that are not even used on the current page). While it is downloading and parsing the CSS, the browser cannot do anything else useful, like continue parsing the rest of the page, prefetching images, rendering, etc... 
3. It prevents crucial performance optimizations like "above-the-fold" critical-path CSS inlining and asynchronously loading styles for content that is "below-the-fold".

With an option in Gatsby to choose if the styles should be inlined or put in an external CSS file, this then would enable developers to implement further optimizations, like the above-mentioned "above-the-fold" critical-path CSS inlining, etc...

An older but still relevant talk about this subject:
https://www.youtube.com/watch?v=PkOBnYxqj3k

**Comment by LekoArts** [comment]
Thank you for opening this!

We extract CSS into the `<head>` for performance reasons. You can read more here:
https://github.com/gatsbyjs/gatsby/issues/145

If you want to change that nevertheless, try these suggestions:
https://github.com/gatsbyjs/gatsby/issues/14333#issuecomment-499344433
https://github.com/gatsbyjs/gatsby/issues/2289#issuecomment-517276598

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
