### ISSUE TITLE
link(doc): bit.ly link broken on blog Kentico Cloud

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#20716]
## Description

Bitly link broken on blog page

### Steps to reproduce

https://www.gatsbyjs.org/blog/2018-12-19-kentico-cloud-and-gatsby-take-you-beyond-static-websites/

look for the link: `Kentico Cloud webhooks`
http://bit.ly/2QzOdeS

### Expected result

redirect

### Actual result

```shell
Fastly error: unknown domain: developer.kenticocloud.com. Please check that this domain has been added to a service.

Details: cache-fra19162-FRA
```

## General

i personaly not like bitly links, because i not see the final destination.

-> should we general remove bit.ly as link? the only in 2 blog posts

**Comment by muescha** [comment]
possible links to fix:
- https://docs.kontent.ai/tutorials/develop-apps/integrate/using-webhooks-for-automatic-updates

**Comment by shrey-sachdeva2000** [comment]
The link is properly working now and this issue can be closed.

**Comment by shrey-sachdeva2000** [comment]
The link is properly working now and this issue can be closed. Thanks.
