### ISSUE TITLE
gatsby-announcer div introduced in v2.18.25

### ISSUE THREAD

**Issue by t2ca** [gatsbyjs/gatsby#20728]
Since upgrading to gatsby@2.18.25, the code bellow is added to the bottom of the page.

`<div id="gatsby-announcer" role="alert" aria-live="assertive" aria-atomic="true" style="position: absolute; width: 1px; height: 1px; padding: 0px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); white-space: nowrap; border: 0px;"></div>`

This adds a 1px line to the bottom of the page.

Going back to gatsby@2.18.24 will fix this problem.

edit:

https://github.com/gatsbyjs/gatsby/issues/20697

**Comment by madalynrose** [comment]
Thank you for filing this issue @t2ca! Could you confirm that adding `top:0` to the list of styles for that div using browser dev tools fixes your issue? If that's the case, I'll whip up a PR!

**Comment by t2ca** [comment]
Hey @madalynrose, yes I can confirm it fixes the issue.
