### ISSUE TITLE
Directory structure for a gatsby-source plugin

### ISSUE THREAD

**Issue by loganwishartcraig** [gatsbyjs/gatsby#20722]
## Summary

Is it possible to have our gatsby-source plugin files contained within a ```dist``` folder at the root of our npm package? E.g .```node_modules/gatsby-source-our-plugin/dist/gatsby-node.js```

## Relevant information

We're developing a gatsby-source plugin. Currently, our build process builds our project into the root directory. Due to the structure of our project, it creates our ```gatsby-node.js``` file, and several folders, cluttering up the root directory. For organizational purposes, we'd like to have our plugin build the project to a ```dist``` folder.

Thus the path to our ```gatsby-node.js``` file would be ```node_modules/gatsby-source-our-plugin/dist/gatsby-node.js```.

Is this achievable, or are we required to have our ```gatsby-node.js``` at our projects root?

I've tried setting ```"main": "dist/gatsby-node.js"``` and ```"main": ./dist/gatsby-node.js``` in our ```package.json``` with no luck. The ```gatsby build``` process throws an error saying our plugin can't be found. Currently, it's ```"main": "gatsby-node.js"``` which is working fine.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by TylerBarnes** [comment]
Hi @loganwishartcraig , my personal workflow for this is to have my publish script copy necessary files (`package.json`, `.npmignore`, etc) to the `dist` directory after building the plugin, the script then publishes from within the `dist` directory.

**Comment by loganwishartcraig** [comment]
Appreciated, @TylerBarnes !
