### ISSUE TITLE
Support pnpm in gatsby-cli

### ISSUE THREAD

**Issue by kaushalyap** [gatsbyjs/gatsby#20737]
## Summary

Currently `gatsby-cli` only support `yarn` and `npm` as package managers, Please support `pnpm` also.

### Motivation

Allowing to use `pnpm` as package manager for gatsby projects allows to avoid re-downloading of dependencies when creating a project for after first time.

Related: https://github.com/gatsbyjs/gatsby/issues/19316

**Comment by vladar** [comment]
Thanks for bringing this up. But how is this issue different from #19316? Also, check out [this comment](https://github.com/gatsbyjs/gatsby/issues/19316#issuecomment-566066664) from it which explains how to move this forward.
