### ISSUE TITLE
(www) Autogenerate explicit IDs for headings

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#20732]
## Description

Create a pre-commit git hook to generate custom IDs for all headings in markdown, e.g.

```
## Using the CLI {#using-the-cli}
```

## Motivation

The primary motivation is localization. When headings are translated, `gatsby-plugin-autolink-headers` creates a hash that is different from the English hash, which breaks any links to the page (see the example below for more details).

In addition to that, having explicit headings could be useful for the following reasons:

* Makes it easier to search where a particular link to a hash is linked to
* Enables authors to come up with shorter hash names if necessary
* Allows authors to change heading titles without breaking links

## Steps

* [x] Get buy-in from Learning Team
* [ ] Add remark-lint to the gatsby repo #18942
* [ ] Update `gatsby-plugin-autolink-headers` to enable custom IDs
* [ ] Create a custom lint rule to add custom-ids to each markdown page

## Example

In [tutorial/part-zero](https://www.gatsbyjs.org/tutorial/part-zero/), the following header exists:

```md
## Familiarize yourself with the command line
```

This gets turned into an slug, `familiarize-yourself-with-the-command-line`, which is referenced in the navigation to link to that section: https://www.gatsbyjs.org/tutorial/part-zero/#familiarize-yourself-with-the-command-line

When this page is translated to Spanish, the title gets changed to:

```md
## Familiarízate con la línea de comandos
```

When this class is pulled in, it creates a different slug than the English version: `familiarízate-con-la-línea-de-comandos`. This means that the sidebar link breaks, and any link to this page section breaks as well.

If the English version had a custom ID:

```md
## Familiarize yourself with the command line {#familiarize-yourself-with-the-command-line}
```

Then the Spanish translation can translate the title but keep the English hash:

```md
## Familiarízate con la línea de comandos {#familiarize-yourself-with-the-command-line}
```

**Comment by AishaBlake** [comment]
I'm on board with this! Is the plugin you're talking about [`gatsby-plugin-autolink-headers`](https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/?=gatsby-plugin-autolink-headers#gatsby-remark-autolink-headers)?

**Comment by muescha** [comment]
some notes:

### 1) remark heading id

maybe this plugin is also useful, if the current processor can not use the heading id: 

https://github.com/imcuttle/remark-heading-id

#### Input

```markdown
### My Great Heading {#custom-id}
```

#### Output

```html
<h3 id="custom-id">My Great Heading</h3>
```

### 2) gatsby-remark-lang-slug

if we don't use the english header id then this can be interesting for creating better language aware slugs:

https://github.com/GaiAma/Coding4GaiAma/tree/master/packages/gatsby-remark-lang-slug
