### ISSUE TITLE
[2.19.0] Cannot find module slash

### ISSUE THREAD

**Issue by le0nik** [gatsbyjs/gatsby#20740]
This file imports slash module
https://github.com/gatsbyjs/gatsby/blob/616b95b51186b6e0e7e4d24926aed4f6cc70e5f3/packages/gatsby/src/utils/jobs-manager.js#L6

but it's absent in package.json's dependencies https://github.com/gatsbyjs/gatsby/blob/616b95b51186b6e0e7e4d24926aed4f6cc70e5f3/packages/gatsby/package.json#L12

thus we get an error "Cannot find module slash" during build

**Comment by wardpeet** [comment]
Oh my, my bad. i'll patch it

**Comment by LekoArts** [comment]
Fixed by #20744
