### ISSUE TITLE
[docs] Mark localhost URLs as code snippets

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#20756]
To be consistent in the Gatsby docs, we want to mark all localhost URL references as code highlighted strings instead of links and document this preference in the Gatsby Style Guide. 

This is in response to PR https://github.com/gatsbyjs/gatsby/pull/19067, which changed some of these references into links; the problem is that unless you're running `gatsby develop` or `gatsby build` locally, those links will not work. We'd therefore prefer to have these listed as code blocks, so we don't have invalid links throughout the docs.

This should be documented in the Style Guide. We could add a new section under "Use clear hyperlinks" that says "Mark localhost URLs as code strings" or something along those lines. https://www.gatsbyjs.org/contributing/gatsby-style-guide

**Comment by bball07** [comment]
PR: [docs] Mark localhost URLs as code snippets #20899

**Comment by muescha** [comment]
more PR for this issue:

- #21177 `fix(docs): fix links to localhost (on pixabay tutorial)`
- #21178 `fix(docs): fix links to localhost, rewording (on strapi blog post)`
- #21179 `fix(docs): fix links to localhost on docs/blog/tutorials ...`

**Comment by marcysutton** [comment]
I think this issue can be closed now, thanks for the watchful eye and PRs @muescha!
