### ISSUE TITLE
[docs][contributing] Settle on a VSCode profile for consistency

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#20764]
We're developing a screencast and screenshot specification for Gatsby Learning, and this includes a custom VSCode Profile which needs to be developed with accessibility in mind. We have the [steps written to launch VSCode](https://docs.google.com/document/d/1za0rTGBzxpdYxPkYIncArfbSngSI0IldePDHFdUUzHQ/edit#); this issue is about creating the VSCode Theme that each team member will download from GitHub and install locally. 

The profile should have a Gatsby.js color scheme and ensure proper contrast for text and icons. We'll have to decide on light mode or dark mode, as it's unsustainable to try and support both; whatever we choose should somewhat match the look and feel of gatsbyjs.org as that's where assets using this profile will be published.

Some tips:

- The "Quiet Light" theme in VSCode could be a great starting point, as it uses a purple theme.
- Any typefaces or plugins will need to be included as part of the VSCode Theme. See https://egghead.io/lessons/vs-code-maintain-multiple-vscode-configurations and https://github.com/avanslaars/code-profiles/tree/master for examples.
- If you do want to recommend a typeface, try to keep it simple and stick with monospace fonts with broad readability.
- The profile will be deployed to the Gatsby github org, where anyone can download it. Bonus!

**Comment by freiksenet** [comment]
Closing this as it's marked as done.
