### ISSUE TITLE
[docs] Use soft-line wraps for all markdown pages.

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#20769]
## Description

There are a couple of (mostly older) markdown pages that still use hard line wraps for paragraphs. This poses a problem for localization, since the lines will be split up and it will be a hassle to track.

We should convert these to use soft line wraps like most of the gatsby docs for easier readibily, maintainability, and translation.

## Example

From how-shadowing-works.md:

```md
Shadowing is a powerful feature that allows theme users to override components,
objects, and anything else in a theme's `src` directory.
```

But it should be:

```md
Shadowing is a powerful feature that allows theme users to override components, objects, and anything else in a theme's `src` directory.
```

**Comment by dvrylc** [comment]
I can help with this!
