### ISSUE TITLE
[docs] Breadcrumb shouldn't be dependent on trailing slash

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#20767]
When writing an issue for new docs recipes, I noticed the breadcrumb fails to work if there is a trailing slash. Oddly, if you remove the trailing slash, the breadcrumb shows the full page hierarchy.

Here are some screenshots showing the difference:

## With trailing slash (broken)
![Gatsby recipe page with broken breadcrumb](https://user-images.githubusercontent.com/1045233/72858898-0fad1e80-3c77-11ea-9d9f-4d149889f1ec.png)

## Without trailing slash (working)
![Gatsby recipe page with working breadcrumb](https://user-images.githubusercontent.com/1045233/72858929-2784a280-3c77-11ea-874f-99e18f2ca946.png)

It would be good to fix this so the breadcrumb works either way, since the pages render either way. This one is up for grabs if anyone is interested in contributing a useful PR; it would be good to fix in the long term in case a URL with a trailing slash gets bookmarked or shared.

**Comment by JijiiMac** [comment]
It'd be my first, may I help out on this one?

**Comment by gabeszrozsa** [comment]
I'd like to grab it, interested in contributing

**Comment by marcysutton** [comment]
Hi @gabeszrozsa, this issue is still open! We would welcome your contribution.
