### ISSUE TITLE
[docs][recipes] Transforming an image with GraphQL

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#20766]
The Gatsby docs recipes would benefit from an example on transforming an image into grayscale (or some other treatment) with GraphQL. This short, step-by-step example could go in the Transforming Data recipes, which otherwise only have one example:  https://www.gatsbyjs.org/docs/recipes/transforming-data

There are a couple of docs that cover the same material. A recipe version would list prerequisites, the limited steps required to complete the task, and some links to learn more (such as the longer doc): 
- API docs, including grayscale and duotone query tips: https://www.gatsbyjs.org/docs/gatsby-image/#shared-query-parameters
- Gatsby Image docs: https://www.gatsbyjs.org/packages/gatsby-image/
- Image processing examples: https://github.com/gatsbyjs/gatsby/tree/master/examples/image-processing

Recipes follow a specific format, which is documented here: https://www.gatsbyjs.org/contributing/docs-templates/#recipes
You can also refer to the Style Guide for conventions and requirements: https://www.gatsbyjs.org/contributing/gatsby-style-guide/

**Comment by bball07** [comment]
PR #20898
