### ISSUE TITLE
image compression not working

### ISSUE THREAD

**Issue by Aleksion** [gatsbyjs/gatsby#2077]
I'm fairly certain I've probably misunderstood something, but image compression does not seem to work for me.

this release: https://github.com/gatsbyjs/gatsby/releases/tag/v0.12.0

mentioned that image-webpack-loader is now being used whenever you import an image in javascript. However, I haven't been able to find anything in the source code indicating that to be the case. I've tried adding a file-loader step myself to the build-javascript step, but that doesn't seem to work either.

**Comment by Aleksion** [comment]
I got it to work by doing the following:

```


exports.modifyWebpackConfig = ({ config, stage }) => {
    switch (stage) {
        case 'develop':
            config.loader('images', {
                test: /\.(gif|png|jpe?g|svg)$/i,
                loaders: [
                    'file-loader?hash=sha512&digest=hex&name=static/[hash].[ext]',
                    'image-webpack-loader?{optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}, mozjpeg: {quality: 65}}'
                ]
            });

            break;

        case 'build-css':
            config.loader('images', {
                test: /\.(gif|png|jpe?g|svg)$/i,
                loaders: [
                    'file-loader?hash=sha512&digest=hex&name=static/[hash].[ext]',
                    'image-webpack-loader?{optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}, mozjpeg: {quality: 65}}'
                ]
            });

            break;

        case 'build-html':
            config.loader('images', {
                test: /\.(gif|png|jpe?g|svg)$/i,
                loaders: [
                    'file-loader?hash=sha512&digest=hex&name=static/[hash].[ext]',
                    'image-webpack-loader?{optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}, mozjpeg: {quality: 65}}'
                ]
            });

            break;

        case 'build-javascript':
            config.loader('images', {
                test: /\.(gif|png|jpe?g|svg)$/i,
                loaders: [
                    'file-loader?hash=sha512&digest=hex&name=static/[hash].[ext]',
                    'image-webpack-loader?{optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}, mozjpeg: {quality: 65}}'
                ]
            });

            break;
    }

    return config;
};
```

but the images are now caught by the url loader, and they don't seem to load anymore

**Comment by KyleAMathews** [comment]
We removed image-webpack-loader for 1.0. Perhaps that's the source of confusion.

**Comment by Aleksion** [comment]
Arrhh I see. 
Any chance you could point me in the right direction on how to implement it?
It's been a bit hard for me to figure out which build stage it should be done in, and how I make it work with the existing loaders.

Thank you for making a great tool by the way :)

**Comment by mingaldrichgan** [comment]
I'm curious—why was this removed? Image compression seems like a pretty uncontroversial feature to have out of the box.

I found it easier to add the [Imagemin plugin](https://github.com/Klathmon/imagemin-webpack-plugin/blob/master/README.md) than to mess with the built-in loaders, FWIW.

**Comment by Aleksion** [comment]
@mingaldrichgan that is so much easier. Thank you!

**Comment by monsieurnebo** [comment]
I gave up `image-webpack-loader` usage, because the `file-loader` require Webpack v2+ .... 

... But `imagemin-webpack-plugin` doesn't seem to optimize my images at all. I'm wondering if the `url-loader` of GatsbyJS isn't moving the files before they have been optimised.

@mingaldrichgan @Aleksion What is your full image configuration guys ?

**Comment by lbittner-pdftron** [comment]
Same issue as above, can't get imagemin-webpack to do anything with a similar config.
