### ISSUE TITLE
chore(gatsby):  remove all require(`slash`)

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#20770]
## Summary

to unify the codebase @vladar moved in the `slash` in to the `gatsby-core-utils` package in this PR:

- #19600 `fix(gatsby): Handle special characters in windows paths`

but there are still places where the `slash` package is included and not the `gatsby-core-utils` are used: [see this Search](https://github.com/gatsbyjs/gatsby/search?p=2&q=%22require%28%60slash%60%29%22&unscoped_q=%22require%28%60slash%60%29%22)

## Motivation

unify the code

### gatsby code

- [ ] [www/gatsby-node.js](https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-node.js)

### packages

- [ ] [packages/babel-preset-gatsby/src/utils/path-serializer.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby/src/utils/path-serializer.js)

### docs

- [ ] [docs/blog/gatsbygram-case-study/index.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/gatsbygram-case-study/index.md)
- [ ] [docs/docs/sourcing-from-wordpress.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/sourcing-from-wordpress.md)
- [ ] [docs/docs/recipes/sourcing-data.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes/sourcing-data.md)
- [ ] [packages/gatsby-source-lever/README.md](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-lever/README.md)
- [ ] [packages/gatsby-source-wordpress/README.md](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/README.md)

### examples

- [ ] [examples/gatsbygram/gatsby-node.js](https://github.com/gatsbyjs/gatsby/blob/master/examples/gatsbygram/gatsby-node.js)
- [ ] [examples/hn/gatsby-node.js](https://github.com/gatsbyjs/gatsby/blob/master/examples/hn/gatsby-node.js)
- [ ] [examples/sitemap/gatsby-node.js](https://github.com/gatsbyjs/gatsby/blob/master/examples/sitemap/gatsby-node.js)
- [ ] [examples/using-asciidoc/gatsby-node.js](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-asciidoc/gatsby-node.js)
- [ ] [examples/using-contentful/gatsby-node.js](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-contentful/gatsby-node.js)
- [ ] [examples/using-remark/gatsby-node.js](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-remark/gatsby-node.js)
- [ ] [examples/using-wordpress/gatsby-node.js](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-wordpress/gatsby-node.js)
- [ ] [examples/using-wordpress-with-acf/gatsby-node.js](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-wordpress-with-acf/gatsby-node.js)

## related issues

- #19600 `fix(gatsby): Handle special characters in windows paths`
- #20744 fix(gatsby): use slash from gatsby-core-utils

**Comment by vladar** [comment]
Technically people can still use `slash` for their sites and be perfectly fine (even our `www` or example sites). We needed this fix in the core to support edge cases which affect a very little number of projects (only those using special characters in filenames under windows).

So not sure if it makes sense to remove all mentions of it.
