### ISSUE TITLE
[gatsby-plugin-manifest] Can i change between favicons on browser tab change?

### ISSUE THREAD

**Issue by DENYHAX** [gatsbyjs/gatsby#20779]
I want to change between 2 favicons on browser tab change.
Can i do this with gatsby-plugin-manifest or should I use react-helmet somehow?

I'm using this starter: [gatsby-starter-hello-friend](https://www.gatsbyjs.org/starters/panr/gatsby-starter-hello-friend/)

**Comment by wardpeet** [comment]
you'll have to use a react-helmet to achieve this. Note that favicons are cached aggressively by the browser so your outcome might not be what you're hoping for.

I'm marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
