### ISSUE TITLE
Manifest plugin does not respect the path prefix conf

### ISSUE THREAD

**Issue by lilac** [gatsbyjs/gatsby#2078]
It is hard coded as "/manifest.json" as in
https://github.com/gatsbyjs/gatsby/blob/78aaeab9f98153615b6c1e8510a89a11edc2e2d1/packages/gatsby-plugin-manifest/src/gatsby-ssr.js#L8

This causes manifest 404 when deployed in hosts like Github.

**Comment by KyleAMathews** [comment]
Hmm you're right. Thanks for reporting this! Would you like to put together a PR with a fix?
