### ISSUE TITLE
"Programmatically create pages from data" tutorial doesn't build on Netlifly

### ISSUE THREAD

**Issue by Pet3ris** [gatsbyjs/gatsby#20786]
## Description

My `gatsby` code builds locally but doesn't build on Netlifly due to problems with a missing query field:

```
4:40:44 PM: success initialize cache - 0.073s
4:40:44 PM: success copy gatsby files - 0.043s
4:40:44 PM: success onPreBootstrap - 0.003s
4:40:44 PM: success createSchemaCustomization - 0.003s
4:40:45 PM: success source and transform nodes - 0.112s
4:40:45 PM: success building schema - 0.344s
4:40:45 PM: error There was an error in your GraphQL query:
4:40:45 PM: Cannot query field "fields" on type "File".
4:40:45 PM: not finished createPages - 0.032s
4:40:45 PM: Skipping functions preparation step: no functions directory set
```

### Steps to reproduce

The code is available in this [tutorial](https://www.gatsbyjs.org/tutorial/part-seven/), but I've modified it to use with `.html` files. Obviously the GraphQL query will index some files that are not the .html files and that will have `fields: null`.

This is the query:

```javascript
exports.createPages = async ({ graphql, actions }) => {
    // **Note:** The graphql function call returns a Promise
    // see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise for more info
    const { createPage } = actions
    const result = await graphql(`
        query {
            allFile {
                edges {
                    node {
                        fields {
                            slug
                        }
                    }
                }
            }
        }
    `);

    // Create a page for each slug starting with "/cheatsheet/"
    result.data.allFile.edges.forEach(({ node }) => {
        if (node.fields !== null && typeof node.fields.slug !== 'undefined' && node.fields.slug.includes("/cheatsheet/")) {
            createPage({
                path: node.fields.slug,
                component: path.resolve(`./src/templates/cheatsheet.js`),
                context: {
                    slug: node.fields.slug,
                },
            })
        }
    });
}

```

### Expected result

The build should work on Netlifly just like it works locally.

### Actual result

It doesn't build with the above error.

### Environment

```

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 72.0.2
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-cli: ^2.8.21 => 2.8.21
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-google-analytics: ^2.1.31 => 2.1.31
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-postcss: ^2.1.18 => 2.1.18
    gatsby-plugin-react-helmet: ^3.1.18 => 3.1.18
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5
    gatsby-source-filesystem: ^2.1.43 => 2.1.43
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7
```

**Comment by jonniebigodes** [comment]
@Pet3ris to add a little context, i've checked the tutorial and it leans towards the usage of the `gatsby-transformer-remark` and `gatsby-source-filesystem` packages in conjunction to generate your website pages based on the markdown and make some changes to the GraphQL schema to add in the `slug` node field to the already existing node. You mentioned that you're using html files and by that you mean that you replaced the markdown with html files? Is that it?

If that's the case and looking at both your query and the tutorial in question, it will apply to a node type, more specifically to the `MarkdownRemark` node type. Also technically you can go without the need of adding the necessary complexity to this, if you really want to have the content and pages inside the html files you've setup you can take a look at [this](https://www.gatsbyjs.org/docs/static-folder/) and #13072 to see how you can set up html pages with Gatsby.

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

**Comment by Pet3ris** [comment]
@jonniebigodes that's exactly right, I'm using `.html` files so instead of `Markdown` nodes I have a working setup using `File` nodes. I still use the same logic for adding a slug field to the `File` nodes, but obviously it picks up other files also, which I'm filtering out by checking the filename.

These `.html` pages are not simply static content but content that is injected into other pages. It includes tables, etc. that are meant to be used with a common layout.

**Comment by jonniebigodes** [comment]
@Pet3ris that's what i thought also why i mentioned the issue, if you scroll down a bit you'll be redirected to #17761 and you can base what you want to achieve based on that. With probably a small ammount of work i think you can use the query you already have grab the necessary file name and in the layout/template inject the html content at will based what is passed down through gatsby's special prop `context` in `gatsby-node.js`. Simplifying what you have. If you're willing to wait a bit i can try and implement a reproduction and come back and detail the steps i took and you pick up from there. Sounds good?

**Comment by Pet3ris** [comment]
@jonniebigodes I'm definitely happy to wait to get this right, thanks a lot for the offer to help!

I'm afraid I do need to generate new pages dynamically based on the `.html` files, because over time I'll be adding more `.html` pages. I'm also using other parts of the tutorial like referencing all of the `.html` pages to create a table of contents, etc. Before I was using a `raw-loader!` which was super easy and seems somewhat similar to the above approach but didn't give me the flexibility.

Having said that I'm new to `gatsby` so maybe it's posssible to do it with the above approach also.

**Comment by marcysutton** [comment]
Perhaps there could be an advanced reference guide on this technique in the future? I would recommend keeping it separate from the main tutorial, as we want to focus that on the happy path for new users and wouldn't want to complicate things. But I'm sure you're not the only one to have that need, especially from the referenced issue above (thanks for your help, @jonniebigodes!).

**Comment by Pet3ris** [comment]
One thing that was mentioned to me in Discord by someone else and may be worth adding into the tutorial is that markdown files accept html and hence that technique could easily be used for html. They had gone through my path until realizing this :).

**Comment by jonniebigodes** [comment]
@marcysutton i think the tutorial should stay as is, simple concise and focused on the task at hand. This particular case is somewhat of a edge case that could be documented further, possibly through adding a advanced case scenario. @Pet3ris yes, adding html is perfectly valid in markdown and it will parsed by the plugin mentioned in the tutorial, And no need to thank, i'm more than happy to help you out

**Comment by Pet3ris** [comment]
Unfortunately this inconsistency between my local gatsby implementation of the tutorial and Netlify is still blocking me for pushing out an update to my website. Locally I’m perfectly able to add a fields item to File graphql records, but Netlify doesn’t seem to accept that.

**Comment by Pet3ris** [comment]
Still blocked on this I'm afraid.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
