### ISSUE TITLE
The server response was "403 Forbidden

### ISSUE THREAD

**Issue by KamranMaqbool** [gatsbyjs/gatsby#20788]
when i am run gatsby develop command then give me this error
using wordpress source plugin 
Path: /wp-json
The server response was "403 Forbidden"
"gatsby-source-wordpress" threw an error while running the sourceNodes lifecycle:
Cannot read property 'data' of undefined
TypeError: Cannot read property 'data' of undefined 

warn The gatsby-source-wordpress plugin has generated no Gatsby nodes. Do you need it?

**Comment by vladar** [comment]
This sounds like a configuration issue. Did you follow all the steps from the [Wordpress plugin documentation](https://www.gatsbyjs.org/docs/sourcing-from-wordpress/)?

Also what happens when you try to open `https://{your_site}/wp-json` in the browser?

**Comment by KamranMaqbool** [comment]
@vladar i'am using WordPress it has live on this URL
https://okaraherbal.com/
when i'am hit  API request using postman then return me proper results using this URL
( https://okaraherbal.com//wp-json/wp/v2/posts)
i'am follow all the steps that are give in gatsbyjs website

**Comment by KamranMaqbool** [comment]
@vladar when using wordpress demo (https://demo.wp-api.org/) API then return me proper results
but when using our hosting wordpress site then give me error

Path: /wp-json
The server response was "403 Forbidden"
 ERROR #11321  PLUGIN
"gatsby-source-wordpress" threw an error while running the sourceNodes lifecycle:
Cannot read property 'data' of undefined
 TypeError: Cannot read property 'data' of undefined

**Comment by vladar** [comment]
Probably you have a special WordPress plugin installed (like https://wordpress.org/plugins/wp-rest-api-authentication/ or similar)

So you must up WordPress `auth` properly in Gatsby plugin. Check out `auth` option in the [plugin documentation](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/).

Also, quick google returns [this article](https://www.dajocarter.com/posts/wordpress-authentication-with-gatsby/) on Gatsby and WordPress auth (although it is just one option of how API auth could be set)

**Comment by KamranMaqbool** [comment]
@vladar i also follow article that you share 
my gatsbyjs file are this

/**
 * Configure your Gatsby site with this file.
 *
 * See: https://www.gatsbyjs.org/docs/gatsby-config/
 */

module.exports = {
  /* Your site config here */
  // iteMetadata: {
  //   stitle: "Gatsby Default Starter",
  // },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-wordpress`,
      options: {
        // your WordPress source
        baseUrl: `www.okaraherbal.com`,
        protocol: `https`,
        // is it hosted on wordpress.com, or self-hosted?
        hostingWPCOM: false,
        // does your site use the Advanced Custom Fields Plugin?
        useACF: false,
        auth:{
          htaccess_user: process.env.WP_CLIENT_ID,
          htaccess_pass: process.env.WP_CLIENT_SECRET,
          htaccess_sendImmediately: false,
        },
        includedRoutes: [
          '**/posts',
          "**/pages",
          "**/categories",
          "**/tags",
          "**/users",
        ],
        excludedRoutes: ["**/posts/1456"],
        keepMediaSizes: false,
        normalizer: function({ entities }) {
          return entities
        },
        normalizers: normalizers => [
          ...normalizers,
          {
            name: "nameOfTheFunction",
            normalizer: function({ entities }) {
              // manipulate entities here
              return entities
            },
          },
        ],
      }
    },
  ],
}

but still give me error

**Comment by KamranMaqbool** [comment]
error are this 

Path: /wp-json
The server response was "403 Forbidden"

 ERROR #11321  PLUGIN

"gatsby-source-wordpress" threw an error while running the sourceNodes lifecycle:

Cannot read property 'data' of undefined

  TypeError: Cannot read property 'data' of undefined
  
  - fetch.js:141 fetch
    [hello-world]/[gatsby-source-wordpress]/fetch.js:141:21
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
  

warn The gatsby-source-wordpress plugin has generated no Gatsby nodes. Do you need it?

**Comment by sidharthachatterjee** [comment]
@KamranMaqbool It looks like you're setting 

```auth:{
htaccess_user: process.env.WP_CLIENT_ID,
htaccess_pass: process.env.WP_CLIENT_SECRET,
htaccess_sendImmediately: false,
},```

That likely isn't working though because the error suggests that you're not authorised. Maybe check if the credentials are correct?

**Comment by KamranMaqbool** [comment]
@sidharthachatterjee i'am checking credentials also and update source-wordpress-plugin then above error are gone but new error are generated.like this

**The request failed with error code "ENOTFOUND"**
ERROR #11321  PLUGIN
"gatsby-source-wordpress" threw an error while running the sourceNodes lifecycle:
Cannot read property 'data' of undefined
TypeError: Cannot read property 'data' of undefined

**Comment by KamranMaqbool** [comment]
any one help i'am send our wordpress admin panel credentials for test what's the problem are there

**Comment by vladar** [comment]
As far as I understand you've opened a new issue for this: #20863 Let's close this one and continue there (since the error seem to be different now)
