### ISSUE TITLE
[www] Use `localizedLink` for all links

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#20797]
## Description

Now that we are pulling in translations (#19353), we have a `localized-link` component that routes to the correct locale. I updated some of the links to use it, but the most still use the default gatsby `<Link>`. We need to change them all to use localized link and lint against the normal `<Link>`.

**Comment by samovertonjr** [comment]
Awesome work! I would like to help with this if I can 😄 .

**Comment by muescha** [comment]
should also an update code snippets for the `Link` imports in the examples in  https://www.gatsbyjs.org/contributing/docs-templates/ ?


_PS: Note the PR #21574 `feat(docs): Split up Docs Templates into Different Pages`) for this page_

**Comment by AishaBlake** [comment]
@muescha, I think that's a fair point. Would you mind opening an issue?

**Comment by muescha** [comment]
added:
- issue #22446 `docs: add section about LocalizedLink`

**Comment by marcysutton** [comment]
Can this issue be closed now that there is a merged PR for updating links?
