### ISSUE TITLE
Make spelling of "e-commerce" consistent across the site

### ISSUE THREAD

**Issue by AishaBlake** [gatsbyjs/gatsby#20790]
## Summary

We're using a mix of spellings of the word "e-commerce" across the site. The biggest issue this causes arises when someone tries to search the term. If you use "ecommerce" in the search bar, you'll get results from the blog before results from the documentation.

<img width="549" alt="search results for the term ecommerce showing blog posts and then docs" src="https://user-images.githubusercontent.com/7365296/72929350-a9cc9f80-3d27-11ea-8e25-3206ea4b42e4.png">

### Motivation

We use **"e-commerce"** and we should be consistent throughout the site.

## Steps to resolve this issue

- Search through the docs for alternate spellings of "e-commerce" and correct them!

### Open a pull request

- [ ] Open a single pull request with your work including the words "fixes #20790" in the pull request description

**Comment by kingisaac95** [comment]
@bball07 are you still looking into this? If not, I can take it on as my first issue to resolve

**Comment by AishaBlake** [comment]
@kingisaac95 I appreciate you asking before submitting a PR, particularly since this was originally assigned to a specific person! You may want to check [issues with the "help wanted" label](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) for potential first PRs if you haven't already.

**Comment by AishaBlake** [comment]
Looks like we still have several lingering instances of spellings other than "e-commerce". Personally, I'm less concerned about changing URLs/filenames than I am about making sure the _text_ uses the correct spelling.

**Comment by marcysutton** [comment]
@AishaBlake do you know if have the remaining instances been solved yet? Maybe we could close this issue now?

**Comment by AishaBlake** [comment]
They haven't been solved. We had two sort of related PRs last month that only addressed a couple of instances each. I'm going to add it to the backlog and get it done in a batch next week.

I think it _also_ makes sense to alter the search behavior if we can. Reading the Algolia documentation on [replacing words](https://www.algolia.com/doc/guides/managing-results/rules/detecting-intent/#replacing-words), I'm thinking we treat e-commerce and ecommerce as synonyms in case people are trying to search on "ecommerce". Since that would have to happen internally, I'll add it to our backlog for now.
