### ISSUE TITLE
gatsby-transformer-remark has no html field

### ISSUE THREAD

**Issue by saadsaifse** [gatsbyjs/gatsby#20799]
## Relevant information

I am following a guide [here](https://www.gatsbyjs.org/packages/gatsby-transformer-remark/) but the `gatsby-transformer-remark` does not seem to have `html` field. I have tried reinstalling and everything else. Following is my query that does not read `html` 

```
query {
  allMarkdownRemark {
    edges {
      node {
        html        
        frontmatter {
          title
        }
      }
    }
  }
}
```

Error: `"message": "Cannot query field \"html\" on type \"MarkdownRemark\".",`

### Environment (if relevant)

```
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31 
    gatsby-plugin-offline: ^3.0.27 => 3.0.27 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16 
    gatsby-plugin-sass: ^2.1.26 => 2.1.26 
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5 
    gatsby-remark-autolink-headers: ^2.1.22 => 2.1.22 
    gatsby-remark-copy-linked-files: ^2.1.33 => 2.1.33 
    gatsby-remark-images: ^3.1.39 => 3.1.39 
    gatsby-remark-prismjs: ^3.3.29 => 3.3.29 
    gatsby-source-filesystem: ^2.1.40 => 2.1.40 
    gatsby-transformer-remark: ^2.6.48 => 2.6.48 
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7 
```

### File contents (if changed)

`gatsby-config.js`: 
```
{
      resolve: "gatsby-transformer-remark",
      options: {
        plugins: [
          {
            resolve: "gatsby-remark-images",
            options: {
              maxWidth: 850,
            },
          },
          "gatsby-remark-prismjs",
          "gatsby-remark-copy-linked-files",
          {
            resolve: `gatsby-remark-autolink-headers`,
            options: {
              offsetY: `100`,
              maintainCase: false,
              removeAccents: true,
            },
          },
        ],
      },
}
```
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
@saadsaifse Can you post the rest of your `gatsby-config`? Do you have `gatsby-source-filesystem` included? 

A [minimal reproduction](https://gatsby.dev/reproduction) would help!

**Comment by saadsaifse** [comment]
Thank you @sidharthachatterjee. I created a minimal reproducible project [here](https://github.com/saadsaifse/gatsby-repro) and that helped me identify my issue. 

As you can see, I am using `gatsby-remark-prismjs` pulgin that depends on `prismjs` but `prismjs` was not installed (my bad) that was causing the issue. If you want to reproduce the issue, checkout my repository and follow the README. 

Cheers!
