### ISSUE TITLE
Require a whitelist for "page" file types

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#208]
Depends on https://github.com/gatsbyjs/gatsby/issues/17

**Comment by KyleAMathews** [comment]
Right now if you add a file type to your pages directory which doesn't have a webpack loader, Gatsby will throw an error. Instead users should whitelist which file types are "pages" and everything else should be treated as an "asset" which is just copied over to public on build.

**Comment by cutemachine** [comment]
+1
