### ISSUE TITLE
Localization for client-side route announcements

### ISSUE THREAD

**Issue by madalynrose** [gatsbyjs/gatsby#20801]
### Summary

Support localization for the "Navigated to" portion of the [route announcement](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/navigation.js#L179) in the `gatsby-announcer` div. 

### Motivation

This announcement is to increase the accessibility of Gatsby. Serving users content in a way that is adapted to their language & culture is part of that mission.

### Related
This builds on work done in #19290

**Comment by marcus13371337** [comment]
Hello! We are very interested in getting this feature working. As an MVP solution, would it be possible to add a manual message somehow with a config or such? We only use one language at our site (which is not Englisht)
