### ISSUE TITLE
gatsby-remark-images: images remain blurry on load after update w/ $ ncu -u

### ISSUE THREAD

**Issue by averyfreeman** [gatsbyjs/gatsby#20810]
## Description

Attempted to update to latest node_modules versions using ncu -u, gatsby-remark-images images stayed blurry on load

Would be nice if updating to latest available packages were possible, but not while using gatsby-remark-images ATM

### Steps to reproduce

cd  /my/project/size
npm install -g npm-check-updates
ncu -u
npm install
gatsby develop 
or
gatsby build && gatsby serve

visit localhost:8/9000 in browser - blurry images persist

Demo:
https://test-site.averyfreeman.com/

Edit: Demo not working properly, please disregard until I have time to update its config - it is not a hosting issue.

### Expected result

images to blur on load but become sharp in ~1sec

### Actual result

Blurry images do not become sharp

### Environment

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.14.1/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1

### You can see here they're all the latest available versions:

  npmPackages:
    gatsby: ^2.19.2 => 2.19.2 
    gatsby-awesome-pagination: ^0.3.5 => 0.3.5 
    gatsby-image: ^2.2.39 => 2.2.39 
    gatsby-plugin-manifest: ^2.2.38 => 2.2.38 
    gatsby-plugin-offline: ^3.0.32 => 3.0.32 
    gatsby-plugin-postcss: ^2.1.19 => 2.1.19 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21 
    gatsby-plugin-sharp: ^2.4.0 => 2.4.0 
    gatsby-plugin-sitemap: ^2.2.26 => 2.2.26 
    gatsby-remark-embed-video: ^2.0.1 => 2.0.1 
    gatsby-remark-images: ^3.1.42 => 3.1.42 
    gatsby-remark-prismjs: ^3.3.30 => 3.3.30 
    gatsby-source-filesystem: ^2.1.46 => 2.1.46 
    gatsby-transformer-remark: ^2.6.48 => 2.6.48 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13 
  npmGlobalPackages:
    gatsby: 2.18.23

**Comment by sidharthachatterjee** [comment]
In this case it looks like it's unable to load the actual image because it isn't being served? 

https://test-site.averyfreeman.com/static/c78df94be856ff14ee88a2bb20f6a4e7/08bc8/trench-for-buildings-2.jpg gives me a 404 Not Found

That's the reason it stays blurry. Likely an issue with your hosting setup?

**Comment by averyfreeman** [comment]
I just threw the test site up there, I forgot to add the subdomain to `gatsby-config.js`  

I first noticed the problem after uploading it to my production site  `gatsby serve` and `gatsby develop` also do not load images.

Tried to get the updated packages to work before I finally gave up, reverted back to the depreciated packages and re-uploaded.

Same exact site works fine with the old packages, I did not change anything else.

**Comment by averyfreeman** [comment]
I stand corrected

I fixed the "siteURL' under module.exports {} and the images appear to load properly

This is kind of weird though because the siteUrl was properly set for the production server, but the images didn't load.

Unfortunately I don't really feel like it's resolved unless I know what actually happened, but it doesn't appear to be the subject of the original report topic, so I'll go ahead and close this.  Thanks for your help :)

**Comment by averyfreeman** [comment]
I just noticed I tried to use 'gatsby build' in another terminal that was using node 13.5.0 through nvm and it failed bc of the sharp module

switched to node 12.14.1 and gatsby build worked straight away.  Perhaps this is related.
