### ISSUE TITLE
useStaticQuery returning TypeError: Cannot read property 'edges' of undefined in Production

### ISSUE THREAD

**Issue by Davey-Wright** [gatsbyjs/gatsby#20818]
I'm trying to query an image in my repository at src/assets/images/logo.png using the useStaticQuery hook inside of a functional component. Everything is working great in development, however in production I am getting a "TypeError: Cannot read property 'childImageSharp' of undefined"

### Steps to reproduce
[This is the production site which is hosted on Netlify](https://focused-banach-89bab7.netlify.com/) If you open the console you can see the error as well as the result from the query as I have logged it.

[This component file where the query lives in my repo](https://github.com/Davey-Wright/the-pursuit-collective/blob/master/src/atoms/Logo/Logo.js)

This is the logo component where the graphql query lives, and where the error is occurring.
```
import React from 'react';
import Img from 'gatsby-image';
import { useStaticQuery, graphql } from 'gatsby';

export default ({ type, width, height, className }) => {
  const data = useStaticQuery(graphql`
    query {
      logo: file(relativePath: { eq: "logo.png" }) {
        childImageSharp {
          fluid(maxWidth: 350) {
            ...GatsbyImageSharpFluid_noBase64
          }
        }
      },
      icon: file(relativePath: { eq: "logo-icon.png" }) {
        childImageSharp {
          fluid(maxWidth: 100) {
            ...GatsbyImageSharpFluid_noBase64
          }
        }
      }
    }
  `)

  const setWidth = () => width ? width : 'auto';
  const setHeight = () => height ? height : 'auto';

  const Horizontal = () => (
    <Img fluid={ data.logo.childImageSharp.fluid }
      className={ className }
    />
  )

  const Icon = () => (
    <Img fluid={ data.icon.childImageSharp.fluid }
      style={{
        width: `${ setWidth() }`,
        height: `${ setHeight() }`
      }}
      className={ className }
    />
  )

  const Responsive = () => {
    const sources = [
      data.icon.childImageSharp.fluid,
      {
        ...data.logo.childImageSharp.fluid,
        media: `(min-width: 320px)`,
      },
    ]

    return (
      <Img fluid={ sources }
        className={ className }
      />
    )
  }

  return (
    <>
      {{
        horizontal: <Horizontal/>,
        icon: <Icon/>,
        responsive: <Responsive/>
      }[type]}
    </>
  );
}
```

The component is being used in the header like so

```
import React from 'react'
import { Link } from 'gatsby'
import Logo from '../../atoms/Logo/Logo'
import Sidebar from '../Sidebar/Sidebar'

import './header.scss'

export default () => {

  return (
    <header className="main-header flex">
        <div className='w-2/6 flex'>
          <Sidebar/>
          <div className="search-button"><i className="far fa-search"></i></div>
          <div className="search-input"><input name="se" id="se" type="text" className="search" placeholder="Search.." /></div>
        </div>

        <Link to='/' className="logo-holder w-2/6">
          <Logo type='responsive' className='mx-auto' name='Home'/>
        </Link>

        <div className="nav-button-wrap">
            <div className="nav-button"><span></span><span></span><span></span></div>
        </div>

        <div className="nav-holder main-menu w-2/6">
            <nav>
                <ul>
                    <li>
                        <Link to='/' activeClassName='act-link'>Home</Link>
                    </li>
                    <li>
                        <Link to='/articles' activeClassName='act-link'>Articles</Link>
                    </li>
                    <li>
                        <Link to='/journals' activeClassName='act-link'>Journals</Link>
                    </li>
                    <li>
                        <Link to='/about' activeClassName='act-link'>About</Link>
                    </li>
                    <li>
                        <Link to='/contact' activeClassName='act-link'>Contact</Link>
                    </li>
                </ul>
            </nav>
        </div>

    </header>
  )
}
```

### Expected result

Should display the image in the top middle of the header. As I mentioned before in development this is working as expected

### Actual result

Image is not displayed in production

### Environment

System:
    OS: macOS High Sierra 10.13.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 11.1.1
  npmPackages:
    gatsby: ^2.18.23 => 2.18.23
    gatsby-image: ^2.2.23 => 2.2.33
    gatsby-plugin-catch-links: ^2.1.12 => 2.1.17
    gatsby-plugin-feed: ^2.3.15 => 2.3.21
    gatsby-plugin-google-analytics: ^2.1.19 => 2.1.27
    gatsby-plugin-lodash: ^3.1.10 => 3.1.15
    gatsby-plugin-manifest: ^2.2.20 => 2.2.28
    gatsby-plugin-nprogress: ^2.1.9 => 2.1.14
    gatsby-plugin-offline: ^3.0.11 => 3.0.21
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.15
    gatsby-plugin-sass: ^2.1.27 => 2.1.27
    gatsby-plugin-sharp: ^2.2.27 => 2.3.0
    gatsby-plugin-sitemap: ^2.2.16 => 2.2.21
    gatsby-remark-autolink-headers: ^2.1.13 => 2.1.18
    gatsby-remark-copy-linked-files: ^2.1.23 => 2.1.30
    gatsby-remark-images: ^3.1.25 => 3.1.31
    gatsby-remark-prismjs: ^3.3.16 => 3.3.23
    gatsby-remark-responsive-iframe: ^2.2.20 => 2.2.27
    gatsby-source-filesystem: ^2.1.28 => 2.1.37
    gatsby-source-instagram: ^0.6.1 => 0.6.1
    gatsby-source-prismic-graphql: 3.4.0-beta.2 => 3.4.0-beta.2
    gatsby-transformer-remark: ^2.6.26 => 2.6.35
    gatsby-transformer-sharp: ^2.2.19 => 2.3.5
  npmGlobalPackages:
    gatsby-cli: 2.8.22

**Comment by lqze** [comment]
Was this working prior or has this just started occurring. Did you recently update Gatsby?

**Comment by Davey-Wright** [comment]
I just added the query hook today and it hasn't worked in production yet

**Comment by lqze** [comment]
Interesting, and obviously it's not giving any output on `gatsby build`?

**Comment by Davey-Wright** [comment]
here is the output, there is an DeprecationWarning error, but don't think that is the issue.

```
the-pursuit-collective (master) gatsby build
success open and validate gatsby-configs - 0.337s
success load plugins - 1.784s
success onPreInit - 0.016s
success delete html and css files from previous builds - 0.015s
success initialize cache - 0.014s
success copy gatsby files - 0.079s
success onPreBootstrap - 0.007s
success createSchemaCustomization - 0.037s

 ERROR

(node:57131) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

success source and transform nodes - 2.794s
warn Plugin `gatsby-source-filesystem` tried to define the GraphQL type `File`, which has already been defined by the
success building schema - 0.606s
success createPages - 0.413s
success createPagesStatefully - 0.100s
success onPreExtractQueries - 0.005s
success update schema - 0.116s
success extract queries from components - 0.638s
success write out requires - 0.018s
success write out redirect data - 0.006s
warn The icon(src/assets/images/logo-icon.png) you provided to 'gatsby-plugin-manifest' is not square.
The icons we generate will be square and for the best results we recommend you provide a square icon.

success Build manifest and related icons - 0.463s
success onPostBootstrap - 0.485s
⠀
info bootstrap finished - 12.721 s
⠀
success Building production JavaScript and CSS bundles - 39.978s
success Rewriting compilation hashes - 0.004s
success Downloading remote files - 2.661s - 10/10 3.76/s
success run queries - 44.366s - 13/13 0.29/s
success Building static HTML for pages - 2.801s - 11/11 3.93/s
info Generated public/sw.js, which will precache 6 files, totaling 636391 bytes.
The following pages will be precached:
/offline-plugin-app-shell-fallback/index.html
info Done building in 61.344131761 sec
```

**Comment by Davey-Wright** [comment]
I'm also using the gatsby-source-instagram plugin and making a staticquery to get posts and then using that query to render them in the sidebar. But I am getting the same error with these as well, it works as expected in development/localhost but in production these errors are being raised. It's almost like I can't use the useStaticQuery hook at all!?

**Comment by lqze** [comment]
Hmm.,..anyway you can get a reproducible environment to test?

I can clone your repo but I need the .env config

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by TimFletcher** [comment]
I have this one too. It doesn't make sense to me why `useStaticQuery` would be executing on the client. It's build-time only, right?

> Gatsby v2.1.0 introduces `useStaticQuery`, a new Gatsby feature that provides the ability to use a React Hook to query with GraphQL at _build time_.

**Comment by mjsarfatti** [comment]
This may have something to do with the issue: https://github.com/gatsbyjs/gatsby/issues/8790#issuecomment-602857090

The only solution at the moment seems to be using the component `StaticQuery` and inlining the query...
