### ISSUE TITLE
Custom port not respected

### ISSUE THREAD

**Issue by atulmy** [gatsbyjs/gatsby#20811]
## Description
When running `npm run serve -p 4005` the port is not respected and the is served on default port 9000

### Steps to reproduce
In any gatsby project

### Expected result
Gatsby should respect `-p <PORT>` with `npm run serve` i.e.`npm run serve -p <PORT>`

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
  System:
    OS: macOS 10.15.2
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5
    gatsby-source-filesystem: ^2.1.40 => 2.1.40
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7

**Comment by sidharthachatterjee** [comment]
When using npm to run commands and to pass down arguments, you need to run `npm run serve -- -p 9001` as opposed to `npm run serve -p 9001`

You could also run `gatsby serve -p 9001`

Thanks!
