### ISSUE TITLE
Scrolling fast causes rendering issues

### ISSUE THREAD

**Issue by joebentaylor1995** [gatsbyjs/gatsby#20821]
## Description
Whenever I scroll a gatsby site really fast, its like gatsby cant keep up with how fast i am scrolling and i end up seeing the background or only partial components, I've got a really basic static site without much animation, this happens on every project.

Its sounds very similar to this discussion but without the listeners:
https://spectrum.chat/gatsby-js/general/ways-to-avoid-scroll-flicker-scroll-jank~9bececde-43d4-4110-a64b-2bbba21682e5

### Steps to reproduce
Scroll really fast up and down
[View issue](https://nostalgic-bhabha-249f5f.netlify.com)

### Expected result
Scrolls buttery smooth without seeing the background / bg video

### Environment
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    npm: 6.13.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.7 => 2.19.1 
    gatsby-image: ^2.2.34 => 2.2.39 
    gatsby-plugin-alias-imports: ^1.0 => 1.0.5 
    gatsby-plugin-google-tagmanager: ^2.1.18 => 2.1.24 
    gatsby-plugin-layout: ^1.0 => 1.1.15 
    gatsby-plugin-manifest: ^2.0 => 2.2.28 
    gatsby-plugin-netlify: ^2.0 => 2.1.25 
    gatsby-plugin-offline: ^3.0.27 => 3.0.32 
    gatsby-plugin-postcss: ^2.0 => 2.1.15 
    gatsby-plugin-postcss-sass: ^1.0 => 1.0.22 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.21 
    gatsby-plugin-robots-txt: ^1.3 => 1.5.0 
    gatsby-plugin-sass: ^2.0 => 2.1.23 
    gatsby-plugin-sharp: ^2.0 => 2.3.0 
    gatsby-plugin-sitemap: ^2.2.22 => 2.2.26 
    gatsby-plugin-styled-components: ^3.0 => 3.1.13 
    gatsby-plugin-transition-link: ^1.12 => 1.16.2 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0 => 1.0.5 
    gatsby-remark-prettier: ^1.0 => 1.0.0 
    gatsby-remark-prismjs: ^3.3.25 => 3.3.30 
    gatsby-source-filesystem: ^2.1.40 => 2.1.46 
    gatsby-transformer-remark: ^2.6.39 => 2.6.48 
    gatsby-transformer-sharp: ^2.3.7 => 2.3.13 
  npmGlobalPackages:
    gatsby-cli: 2.8.27

**Comment by joebentaylor1995** [comment]
On further insection, this issue only becomes apparent in Firefox

**Comment by sidharthachatterjee** [comment]
The site scrolls fine for me on Chrome. I haven't tried Firefox. 

I would attribute this to user land code or React and _not_ Gatsby as the spectrum page suggests. 

Closing this for that reason. Thank you so much for taking the time to open this though!

**Comment by joebentaylor1995** [comment]
Im sorry but thats such a poor reason to close this issue, this issue needs fixing in firefox

**Comment by michaeljblum** [comment]
Hey @joebentaylor1995 have you seen [this](https://github.com/gatsbyjs/gatsby/issues/12520)? I've noticed this issue on and off too on some projects - janky micro-stuttering upon scroll in Gatsby projects. The one perf sore spot that I've never really been able to understand. But I think it might have to do with the scroll-behavior package.

**Comment by conspireagency** [comment]
> Im sorry but thats such a poor reason to close this issue, this issue needs fixing in firefox

Agreed.  We've also run into issues (cross browser) where as you scroll portions of the page take a long time to paint.  If you scroll away after they paint and scroll back... issue repeats itself.

**Comment by joebentaylor1995** [comment]
Exactly my issue too!

This issue shouldn’t be closed

**Comment by joebentaylor1995** [comment]
This issue is still here...
