### ISSUE TITLE
plugin gatsby-transformer-xml not working

### ISSUE THREAD

**Issue by pjuerg** [gatsbyjs/gatsby#2083]
I'm fairly new to gatsby! My case is to convert a side based on one xml file to gatsby. I start building most simple project  with gatsby-starter
- add plugin gatsby-source-filesystem and gatsby-transformer-xml
- used bookss.xml from the example to have a simple xml

then gatsby develop throws 
(node:11236) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'internal' of undefined
and  hangs up while building the schema.

Did I misunderstood some concept or is this an issue?

**Comment by KyleAMathews** [comment]
A site reproducing the error would be very helpful!

**Comment by pjuerg** [comment]
Sorry. No idea how to simple host this example?
Without transform-xml runs everything, with other transformer like gatsby-transformer-javascript-static-exports it works also fine. 
I just thought maybe it's the place of the xml-file in the file-system. I put it in src/pages/bookss.xml

files in src
<img width="285" alt="bildschirmfoto 2017-09-11 um 16 08 53" src="https://user-images.githubusercontent.com/5476320/30278795-be2e7666-970b-11e7-873e-4206e1b0547c.png">

gatsby-configs.js
<img width="360" alt="bildschirmfoto 2017-09-11 um 16 09 46" src="https://user-images.githubusercontent.com/5476320/30278824-d4e1a3a6-970b-11e7-882d-990c681bf5f6.png">

**Comment by KyleAMathews** [comment]
Create a repo on GitHub and then add a site reproducing the problem there.

**Comment by pjuerg** [comment]
here ist the repo:
https://github.com/pjuerg/gatsby-xml-transform-problem <https://github.com/pjuerg/gatsby-xml-transform-problem>

**Comment by pjuerg** [comment]
Hi, mathew, could you retrace the problem with the  xml transofmer?
