### ISSUE TITLE
A more elegant way to create pages with multiple routes

### ISSUE THREAD

**Issue by ArcaneTSGK** [gatsbyjs/gatsby#20842]
## Summary

The project requires conditional rendering of components depending on which platform the end user accesses our gatsby application, requiring multiple routes/paths for the same page. We know what we need to render for each platform, therefore these pages should be created at build time (static content).

For example, two platforms, Web and Download. 

The following is the solution I have come up with in gatsby-node.js, this works but I would like to think there is a more elegant approach.

The default platform 'web' should generate the page without platform prefix in the URL

```
    const platforms = ['web', 'download'];

    platforms.forEach((platform) => {
      actions.createPage({
        path: platform !== 'web' ? `/${platform}/login/` : '/login/',
        component: path.resolve(`src/templates/login/loginPage.tsx`),
        context: {
          pageData: {
            platform: platform
          }
        }
      });
    });

    platforms.forEach((platform) => {
      actions.createPage({
        path: platform !== 'web' ? `/${platform}/forgotten-password/` : '/forgotten-password/',
        component: path.resolve(`src/templates/forgottenPassword/forgottenPasswordPage.tsx`),
        context: {
          pageData: {
            platform: platform,
            data: forgotPasswordPageData
          }
        }
      });
    });
```

 System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE     
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD        
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.1.0 => 2.18.11
    gatsby-image: ^2.0.20 => 2.2.36
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5
    gatsby-plugin-manifest: ^2.0.9 => 2.2.33
    gatsby-plugin-react-helmet: ^3.0.2 => 3.1.18
    gatsby-plugin-recaptcha: ^1.0.5 => 1.0.5
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.0.12 => 2.3.7
    gatsby-plugin-sitemap: ^2.1.0 => 2.2.24
    gatsby-plugin-typescript: ^2.0.2 => 2.1.22
    gatsby-source-filesystem: ^2.0.33 => 2.1.42
    gatsby-source-graphql: ^2.0.11 => 2.1.28
    gatsby-transformer-remark: ^2.1.15 => 2.6.42
    gatsby-transformer-sharp: ^2.1.8 => 2.3.9

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by vladar** [comment]
Thank you for opening this, @ArcaneTSGK 

Did you check our [docs on routing](https://www.gatsbyjs.org/docs/routing/)? This quote from docs sounds like what you describe:

> Alternatively, if you want to create pages that will display different subcomponents depending on the URL path (such as a specific sidebar widget), Gatsby can handle that at the page level using [layouts](https://www.gatsbyjs.org/docs/layout-components/).
