### ISSUE TITLE
Heroku deployment doesn't work

### ISSUE THREAD

**Issue by snigp** [gatsbyjs/gatsby#20858]
Hello, I'm trying to deploy gatsby on Heroku but it doesn't work... I'm getting this error:

<img width="363" alt="Schermata 2020-01-25 alle 06 52 37" src="https://user-images.githubusercontent.com/60283077/73116998-a449a200-3f3f-11ea-997a-e56d3ef2bb18.png">

`2020-01-25T05:46:32.061460+00:00 app[web.1]: 2020/01/25 05:46:32 [error] 32#0: *5 directory index of "./public/" is forbidden,`

### **Setup:**

<img width="454" alt="Schermata 2020-01-25 alle 07 00 26" src="https://user-images.githubusercontent.com/60283077/73117045-64cf8580-3f40-11ea-9a30-1a8416ab0d7b.png">
<img width="592" alt="Schermata 2020-01-25 alle 07 00 16" src="https://user-images.githubusercontent.com/60283077/73117046-64cf8580-3f40-11ea-97a6-1b5b23c4e545.png">

```
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop -p 3000",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean ",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
------------
{
  "root": "public/",
  "headers": {
    "/**": {
      "Cache-Control": "public, max-age=0, must-revalidate"
    },
    "/**.svg": {
      "Cache-Control": "public, max-age=31536000, immutable"
    },
    "/**.ttf": {
        "Cache-Control": "public, max-age=31536000, immutable"
    },
    "/**.js": {
      "Cache-Control": "public, max-age=31536000, immutable"
    },
    "/static/**": {
      "Cache-Control": "public, max-age=31536000, immutable"
    }
  },
  "https_only": true,
  "error_page": "404.html"
}
------------
{
  "buildpacks": [
    {
      "url": "heroku/nodejs"
    },
    {
      "url": "https://github.com/heroku/heroku-buildpack-static"
    }
  ]
}
------------
```

It would be great if someone could tell me if there is an error in my setup.

**Comment by vladar** [comment]
Thanks for opening this issue! It seems to be unrelated to Gatsby directly but let's keep it open for some time, maybe someone will be able to help. In the meantime, you could ask for help in [Heroku community](https://stackoverflow.com/questions/tagged/heroku)

**Comment by sidharthachatterjee** [comment]
Let's go ahead and close this as it's unrelated and _also_ hasn't had any activity since.

@snigp Hope you managed to figure this out. Thanks!
