### ISSUE TITLE
How to create a checkout process using gatsby-source-shopify

### ISSUE THREAD

**Issue by arhoy** [gatsbyjs/gatsby#20861]
Hello,
Quick question on how to create a checkout process using this plugin. It seems like there is no way to handle checkout via this plugin. Am I missing something?

https://www.gatsbyjs.org/packages/gatsby-source-shopify/?=shopify

Thank you!

**Comment by lqze** [comment]
Also interested, as have only really seen Gatsby sites use the Storefront API to get product information and have a cart, but every instance of the checkout takes you to your Shopify checkout page.

This is probably relevant:
https://www.gatsbyjs.org/packages/gatsby-source-shopify/?=shopify#a-note-on-customer-information

**Comment by arhoy** [comment]
Just want to update.
This really helped me out so adding here for future developers
https://github.com/AlexanderProd/gatsby-shopify-starte

If you are using the Shopify Button, ($9.month plan as of this writing ) then there is no way to have the checkout page remain on your domain. (I asked Shopify)

If you want to have the checkout remain on your domain, than you need to upgrade to at least the basics plan $29/month
