### ISSUE TITLE
The request failed with error code "ENOTFOUND"

### ISSUE THREAD

**Issue by KamranMaqbool** [gatsbyjs/gatsby#20863]
when run `gatsby develop` command then this error are generated. i'am using wordpres source plugin and use live wordpress site for data fetching. 

The request failed with error code "ENOTFOUND"
ERROR #11321 PLUGIN
"gatsby-source-wordpress" threw an error while running the sourceNodes lifecycle:
Cannot read property 'data' of undefined
TypeError: Cannot read property 'data' of undefined

fetch.js:141 fetch
[hello-world]/[gatsby-source-wordpress]/fetch.js:141:21

next_tick.js:68 process._tickCallback
internal/process/next_tick.js:68:7

![Screenshot from 2020-01-25 18-35-46](https://user-images.githubusercontent.com/53546053/73122031-acd2c480-3fa1-11ea-9542-f64ef1754873.png)

**Comment by KamranMaqbool** [comment]
![Screenshot from 2020-01-21 23-46-48](https://user-images.githubusercontent.com/53546053/73122022-9462aa00-3fa1-11ea-83fd-07beb4355e30.png)

**Comment by vladar** [comment]
Hi @KamranMaqbool !

We'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look. You can create a private github project (with all credentials) and invite me if you don't want to make it public.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
