### ISSUE TITLE
onCreatePage runs into a loop

### ISSUE THREAD

**Issue by hejsfj** [gatsbyjs/gatsby#20872]
I am using onCreatePage to localise all my existing pages and add context as well as manipulate the path. However onCreatePage triggers every time the new page is created. The Gatsby mechanism which should prevent this does not seem to work in my case. What am I missing here?

`const locales = require(`./config/i18n`)

const {
    removeTrailingSlash,
} = require(`./src/utils/gatsby-node-helpers`)

exports.onCreatePage = async ({ page, actions }) => {
    const { createPage, deletePage } = actions

    // First delete the incoming page that was automatically created by Gatsby
    // So everything in src/pages/
    deletePage(page)

    // Grab the keys ('en' & 'de') of locales and map over them
    Object.keys(locales).map(lang => {
        // Use the values defined in "locales" to construct the path
        const localizedPath = locales[lang].default
            ? page.path
            : `${locales[lang].path}${page.path}`;
        console.log(localizedPath);

        return createPage({
            // Pass on everything from the original page
            ...page,
            // Since page.path returns with a trailing slash (e.g. "/de/")
            // We want to remove that
            path: removeTrailingSlash(localizedPath),
            // Pass in the locale as context to every page
            // This context also gets passed to the src/components/layout file
            // This should ensure that the locale is available on every page
            context: {
                ...page.context,
                locale: lang,
            },
        })
    })
};`

### Environment

`
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.12.0 => 2.18.18 
    gatsby-image: ^2.2.20 => 2.2.37 
    gatsby-plugin-catch-links: ^2.0.12 => 2.1.21 
    gatsby-plugin-emotion: ^4.1.0 => 4.1.18 
    gatsby-plugin-gdpr-cookies: ^1.0.4 => 1.0.4 
    gatsby-plugin-google-analytics: ^2.1.6 => 2.1.31 
    gatsby-plugin-hubspot: ^1.3.3 => 1.3.3 
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.34 
    gatsby-plugin-offline: ^3.0.8 => 3.0.30 
    gatsby-plugin-react-helmet: ^3.1.8 => 3.1.18 
    gatsby-plugin-remove-trailing-slashes: ^2.0.11 => 2.1.17 
    gatsby-plugin-resolve-src: ^2.0.0 => 2.0.0 
    gatsby-plugin-sass: ^2.0.11 => 2.1.26 
    gatsby-plugin-sharp: ^2.2.25 => 2.3.10 
    gatsby-source-filesystem: ^2.1.26 => 2.1.43 
    gatsby-source-prismic-graphql: 3.4.0-beta.1 => 3.4.0-beta.1 
    gatsby-transformer-sharp: ^2.2.16 => 2.3.9 
  npmGlobalPackages:
    gatsby-cli: 2.8.15
`

**Comment by jonniebigodes** [comment]
@hejsfj can you make a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that i can further looked at and based on it possible offer you a solution ?

**Comment by vladar** [comment]
You should probably add something like this at the top of your `onCreatePages`:

```js
  if (page.context.locale) {
    return 'Skipping localized page';
  }
```

Otherwise, this cycle is pretty expected.

**Comment by hejsfj** [comment]
Solved it by using the **gatsby-source-prismic-graphql** plugin. All my pages are now in the `/templates` folder. The plugin automatically generates static pages for each language. This repo shows a nice implementation: [https://github.com/PaulinaVPG/multilanguage-gatsby](url)
