### ISSUE TITLE
Could not start the server locally

### ISSUE THREAD

**Issue by jack2gs** [gatsbyjs/gatsby#20885]
## Description

Could not start the local develop server.

### Steps to reproduce

```shell
gatsby new blog-gatsby
cd blog-gatsby&&gatsby develop
```

### Expected result

the local server should start.

### Actual result

*symbol lookup error* happened.

> success open and validate gatsby-configs - 0.033s
success load plugins - 0.294s
success onPreInit - 0.007s
success initialize cache - 0.008s
success copy gatsby files - 0.013s
success onPreBootstrap - 0.005s
success createSchemaCustomization - 0.003s
success source and transform nodes - 0.054s
warn Plugin `gatsby-source-filesystem` tried to define the GraphQL type `File`,
success building schema - 0.207s
success createPages - 0.001s
success createPagesStatefully - 0.041s
success onPreExtractQueries - 0.002s
success update schema - 0.020s
success extract queries from components - 0.168s
success write out requires - 0.017s
success write out redirect data - 0.002s
⠋ onPostBootstrap
⠋ Build manifest and related icons
vips warning: pngload: no property named `fail'

>vips warning: pngload: no property named `fail'

>node: symbol lookup error: /home/jgao/workspace/blog/blog-gatsby/node_modules/sharp/build/Release/sharp.node: undefined symbol: _ZNK4vips
6VImage11premultiplyEPNS_7VOptionE

### Environment
  System:
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Xeon(R) E-2174G CPU @ 3.80GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31 
    gatsby-plugin-offline: ^3.0.27 => 3.0.27 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16 
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5 
    gatsby-source-filesystem: ^2.1.40 => 2.1.40 
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7 
  npmGlobalPackages:
    gatsby-cli: 2.8.27

**Comment by Js-Brecht** [comment]
@jack2gs Have you tried using a newer version of Node?  I seem to recall seeing an issue somewhere where ImageSharp was having some similar issues on some of the less current versions of Node

**Comment by Js-Brecht** [comment]
I use Ubuntu v19, with Node v12, and I don't have any problems running Gatsby

**Comment by Js-Brecht** [comment]
Information for reference: `_ZNK4vips
6VImage11premultiplyEPNS_7VOptionE` is a symbol in `libvips-cpp` which is used by [`sharp`](https://github.com/lovell/sharp), which is in turn used by [`gatsby-transformer-sharp`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/package.json#L16).

If it's not node, perhaps there were some issues during the install process?

Pretty sure `sharp` uses your globally installed version of `libvips-cpp`, if there is one, otherwise I think it downloads it.  So, if you have one installed already, maybe that version is not compatible.

**Comment by jack2gs** [comment]
@Js-Brecht , thank you very much! I installed the libvips manually following this instruction: https://github.com/libvips/libvips/wiki/Build-for-Ubuntu
