### ISSUE TITLE
Change the outline-color of buttons

### ISSUE THREAD

**Issue by shrey-sachdeva2000** [gatsbyjs/gatsby#20884]
**Issue:**
The outline-color of buttons in the docs is currently set to #90bafe which doesn't match the Gatsby theme. 

**Solution:** 
It would be much better if the outline-color matches the Gatsby primary color palette to bring consistency, as mentioned here: [](https://www.gatsbyjs.org/guidelines/color/
Please find attached screenshots of the same.

![issue#3](https://user-images.githubusercontent.com/47667325/73134034-76f01780-4057-11ea-82e4-1f3a980047c3.jpg)
![issue#4](https://user-images.githubusercontent.com/47667325/73134035-76f01780-4057-11ea-9f21-01edf9c476a6.jpg)

**Comment by b0nbon1** [comment]
Can I take this one @shrey-sachdeva2000 ?

**Comment by shrey-sachdeva2000** [comment]
Sure! @b0nbon1

**Comment by b0nbon1** [comment]
thanks

**Comment by Ar3Tea** [comment]
Still in progress or need a new taker?

**Comment by sidharthachatterjee** [comment]
We want to stick to native focus styling as much as possible (per response in https://github.com/gatsbyjs/gatsby/pull/21077#issuecomment-585404418)

Let's close this for now. Thank you everyone!
