### ISSUE TITLE
On iOS Safari, refreshing page issue after navigating to an external link and pressing the browser back button

### ISSUE THREAD

**Issue by ptlab-la** [gatsbyjs/gatsby#20883]
## Description

On iOS Safari, after I navigate away from Gatsby to an external site and then press the back button, I get strange results with the page not refreshing after clicking a Gatbsy Link. Often when I first tap Links they change to the hover state but don't load the next page. Sometimes the next page loads scrolled halfway down the page.

### Steps to reproduce

1. On Gatsby site, either click on an external link anchor tag or type an external link in the browser to navigate away from the site.
2. Press the browser back button
3. Tap Gatsby Links

### Expected result

Pages load as normal.

### Actual result

Clicking a Link shows hover state but doesn't load the page until you touch/move/scroll the screen again.

### Environment

Testing on: iOS 13.3
Site hosted on AWS S3.

System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    npm: 6.13.6 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.19.5 => 2.19.5
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-manifest: ^2.2.38 => 2.2.38
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-s3: ^0.3.2 => 0.3.2
    gatsby-plugin-sharp: ^2.4.0 => 2.4.0
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-source-graphql: ^2.1.32 => 2.1.32
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13
  npmGlobalPackages:
    gatsby-cli: 2.8.27

**Comment by Js-Brecht** [comment]
@ptlab-la that's interesting.  Do you, perhaps, have a minimal reproduction repository you could share?  I've tried to replicate the issue using a default gatsby starter, and serving it on my local network so I can run the site using Safari on my iPhone.  I was unsuccessful in recreating the problem.
