### ISSUE TITLE
How to use childMarkdownRemark

### ISSUE THREAD

**Issue by 3CordGuy** [gatsbyjs/gatsby#2088]
Tutorial 4 covers the user of MarkdownRemark but doesn't dive into anything pertaining to using `childMarkdownRemark` which I have seen used in queries in some projects that pull from sources like contentful (Which is actually my end goal). 

I have contentful data coming through but I can't figure out how to transform just the one field ("body") into html using this means. 

I've seen something like this:
```
{
  contentfulBlogPost(slug: {eq: "test-post"}) {
    title
    slug
    postDate
    body {
      childMarkdownRemark {
        html
      }
    }
    cover {
      responsiveResolution {
        src
        srcSet
        width
        height
      }
    }
  }
}
```

Any direction would be greatly appreciated.

**Comment by KyleAMathews** [comment]
1. Open Graph*i*QL
2. Paste in

```graphql
allContentfulBlogPost {
  edges {
    node {
      id
    }
  }
}
```
3. Use Graph*i*QL's autocomplete to explore the schema.

https://www.howtographql.com/ should have some videos on using Graph*i*QL.

**Comment by KyleAMathews** [comment]
And if this isn't enough, you gotta describe more what the issue is as your query looks correct.

**Comment by 3CordGuy** [comment]
Yes. Thanks. I do understand that. What I don't understand is why `childMarkdownRemark` is not in my schema if it's supposed to "just work." Yet There's so a few examples of it's use elsewhere in github projects. It is not mentioned/documented anywhere but the npm package page when I google it.

Maybe I should note that I am using the advanced-starter and it has this as the config for the plugin setup by default:

```
{
      resolve: "gatsby-transformer-remark",
      options: {
        plugins: [
          {
            resolve: "gatsby-remark-images",
            options: {
              maxWidth: 690
            }
          },
          {
            resolve: "gatsby-remark-responsive-iframe"
          },
          "gatsby-remark-prismjs",
          "gatsby-remark-copy-linked-files",
          "gatsby-remark-autolink-headers"
        ]
      }
    },
```
Here's my schema autocomplete response for the inner body of my content model.
<img width="302" alt="content-schema" src="https://user-images.githubusercontent.com/30707961/30324989-93957472-9788-11e7-98d1-d0a665120e4c.png">

I would guess that there's no configuration on the plugin that is needed because other examples on github just have `gatsby-transformer-remark` listed in their `gatsby-config`

**Comment by 3CordGuy** [comment]
💩 ...
This whole time it's been the `gatsby-transformer-remark` version that has kept it from not showing in my schema.
I ran yarn and got it to `1.7.7` and now it works.

<img width="267" alt="screen shot 2017-09-12 at 7 15 06 am" src="https://user-images.githubusercontent.com/30707961/30325451-6e779b00-978a-11e7-9311-f2981dd63fb6.png">

**Comment by KyleAMathews** [comment]
Sweet, glad you got it working!

**Comment by 3CordGuy** [comment]
I had to run off to work when I posted that earlier so I actually didn't get a chance to try it out until now on my lunch break. Any idea why the schema inside `childMarkdownRemark` would not have `html`? Does my markdown need to have frontmatter in the contentful field to render the html?

See screenshot: Only frontmatter is listed... 🤔 
<img width="235" alt="screen shot 2017-09-12 at 12 43 30 pm" src="https://user-images.githubusercontent.com/30707961/30340477-3e0dd6d6-97b8-11e7-9115-f5c7b0bc227b.png">

**Comment by 3CordGuy** [comment]
After more tinkering, it turns out it was related to the way it was defined in the config file shown 

```
{
      resolve: "gatsby-transformer-remark",
      options: {
        plugins: [
          {
            resolve: "gatsby-remark-images",
            options: {
              maxWidth: 690
            }
          },
          {
            resolve: "gatsby-remark-responsive-iframe"
          },
          "gatsby-remark-prismjs",
          "gatsby-remark-copy-linked-files",
          "gatsby-remark-autolink-headers"
        ]
      }
    },
```

I commented it out and just included: `gatsby-transformer-remark` in the plugin list and it works fine showing `childMarkdownRemark{ html }`. 

So is this a bug with `gatsby-remark-images`? Or perhaps that's not usable with pulling source from contentful?

Hopefully this helps someone else who is trying to use contentful and uses the **advanced-starter** as a springboard.

**Comment by smakosh** [comment]
I'm trying to get `excerpt` inside the `childMarkdownRemark` but it returns an empty string, any idea why?

I'm getting my content from Contentful btw.

**Comment by steoneill** [comment]
Yeah i'm having issues with it too, i just get ```      "message": "getNodesByType is not a function",```
