### ISSUE TITLE
503 Errors from gatsby-source-drupal 

### ISSUE THREAD

**Issue by clintvidler** [gatsbyjs/gatsby#20897]
## Description

info Starting to fetch data from Drupal
⠹ source and transform nodes
⠋ Fetch data from Drupal

5-10 seconds after the above I get a bunch of 503 errors resulting in failure to build. 

The Drupal site being sourced from has only 17 pages, and the host has already had the CPU level turned up to 300%, the highest I can make it will be 400%. On 200% CPU all builds failed, on 300% CPU building without basic authentication succeeds but fails mostly otherwise. I've set 
`concurrentFileRequests: 1,`, but it doesn't appear to help in the slightest. 

### Steps to reproduce

I cannot provide reproducible steps because it requires a Drupal instance of sorts.

### Expected result

Successful build.

### Actual result

An attack of 503 errors when running gatsby develop or gatsby build.

### Environment

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    npm: 6.13.6 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.11 => 2.18.11 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31 
    gatsby-plugin-offline: ^3.0.27 => 3.0.27 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16 
    gatsby-plugin-sass: ^2.1.26 => 2.1.26 
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5 
    gatsby-plugin-styled-components: ^3.1.18 => 3.1.18 
    gatsby-plugin-typescript: ^2.1.23 => 2.1.23 
    gatsby-source-custom-api: ^2.1.4 => 2.1.4 
    gatsby-source-drupal: ^3.3.12 => 3.3.12 
    gatsby-source-filesystem: ^2.1.40 => 2.1.40 
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7 
  npmGlobalPackages:
    gatsby-cli: 2.8.27

**Comment by ascorbic** [comment]
Hi. This is almost always a configuration or load issue with the server. If you load `/jsonapi` on your site in a browser, does it load ok? Copy the URL from your gatsby-config to make sure you've got it exactly the same. Do this in an incognito/private window. If your API needs authentication, use the same basic auth credentials as in the site config. Let me know if this helps.

**Comment by clintvidler** [comment]
The URLs are all correct, and the basic auth isn't required. The 503 errors are caused by the server being overloaded by Gatsby requests. During the build I visit jsonapi in my browser and it comes back with a 503, this usually works. It's certainly an issue of the server being overloaded but it's strange that it happens even when I set the number of concurrent requests to 1.

**Comment by kmajzlik** [comment]
Interesting. I had exactly same problem but it helped me..

```
  plugins: [
    {
      resolve: `gatsby-source-drupal`,
      options: {
        baseUrl: `***`,
        concurrentFileRequests: 2,
      },
    },
  ],
```

**Comment by kmajzlik** [comment]
And hints:
- disable all not needed sources (really there is no need to node_type jsonapi endpoint...)
- you can filter for local only by enabling jsonapi_default (from jsonapi_extras module) and putting this(just example for files) to your settings.local.php 
```
$config['jsonapi_extras.jsonapi_resource_config.file--file']['third_party_settings']['jsonapi_defaults']['default_filter'] = [
  'filter:datefilter#condition#path' => 'created',
  'filter:datefilter#condition#operator' => '>',
  'filter:datefilter#condition#value' => '1546300800',
];
```

**Comment by sidharthachatterjee** [comment]
Setting `concurrentFileRequests` should fix this and hitting `/jsonapi` should give you more information (since that's what the plugin hits) 

Closing this for now since it isn't strictly Gatsby related. Do let us know if none of this works and if we can help further. Thanks!
