### ISSUE TITLE
Service workers in Development mode

### ISSUE THREAD

**Issue by franzejr** [gatsbyjs/gatsby#2089]
Hey all,

I am using gatsby on a project and It seems the service workers don't work locally. Also, It does not found the `manifest.json`. I am using [gatsby-plugin-manifest ](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-manifest).

I published the project and it worked perfectly on my server.

Any thoughts on this?

**Comment by KyleAMathews** [comment]
Service workers are only meant for production. It's pretty confusing to cache during development as you always want changes to updates.

Try building the site and then running it with `gatsby serve` and you'll there see the service worker in action.

**Comment by franzejr** [comment]
I got your point. Working before with Service Workers it was allowed to run it locally using localhost. I just thought this could be good for debugging purposes

**Comment by y1n0** [comment]
but how are we supposed to test the service worker? building the site after each change does not sound like the best way to do it
