### ISSUE TITLE
'sizes' param for fluid images should be well documented

### ISSUE THREAD

**Issue by mjmaurer** [gatsbyjs/gatsby#20895]
## Summary

What problem(s) did you run into that caused you to request additional documentation? What questions do you think we should answer? What, if any, existing documentation relates to this proposal?

The [documentation](https://www.gatsbyjs.org/docs/gatsby-image/#fluid-image-query-parameters) for fluid images doesn't mention the "[sizes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-sizes)" parameter that is passed through to the `img` component. If left out, it defaults to `(max-width: 1000px) 100vw, 1000px`.

This means you lose a lot of the benefits of a fluid image. Most of my images for example are smaller than the viewport width, so if the browser picks the `100vw` bucket it is already too big. I couldn't find a good explainer on this in the docs, but it seems pretty important.

Maybe add a link to Mozilla's [walkthrough for responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images).

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by Phizzard** [comment]
I've done had some experience manually using srcsets and sizes on images and using the gatsby-image component.

I'd be happy to write some documentation for the sizes parameter if it's available?

**Comment by marcysutton** [comment]
@Phizzard we would love your contribution to the Gatsby docs, and would welcome a PR if you're able!

**Comment by mjmaurer** [comment]
`sizes` is actually a param on `childImageSharp.fluid`. If set, I believe it doesn't affect sharp processing and just gets passed through to the `fluid` attribute of Gatsby's `Img`.

As such, it should be listed [here](https://www.govtrack.us/congress/members/bernard_sanders/400357) as well as in the image docs. Happy to do this as well! Just let me know if you plan on tackling

**Comment by vpicone** [comment]
@mjmaurer errr did you mean to link to bernie sander's profile?

**Comment by mjmaurer** [comment]
Whoops! Maybe I was trying to figure out the `sizes` of some of his proposals (i give this joke 5/10)

**Comment by Phizzard** [comment]
Sorry if I've been a little quiet since taking it, got a little sidetracked but am currently tackling it :)
