### ISSUE TITLE
Error: Invariant Violation: Encountered an error trying to infer a GraphQL. There is no corresponding node with the   `id` 

### ISSUE THREAD

**Issue by Borisboky** [gatsbyjs/gatsby#20906]
I'm using Strapi and Gatsby. I want to rebuild Gatbsy everytime when something is changed in Strapi.

I have one content type (bsixtbanner). Inside /api/bsixtbanner/models/Bsixtbanner I have code as follows:

    const updateFrontend = require('../../../updateFrontend');
    
    module.exports = { 
    
      // After creating a value.
      // Fired after an `insert` query.
      afterCreate: async (model, attrs, options) => {
        updateFrontend.updateFrontend();
      },  
    
      // After updating a value.
      // Fired after an `update` query.
      afterUpdate: async (model, attrs, options) => {
        updateFrontend.updateFrontend();
      },
    
      // After destroying a value.
      // Fired after a `delete` query.
      afterDestroy: async (model, attrs, options) => {
        updateFrontend.updateFrontend();
      }
    };

And update frontend is as follows:

    const shell = require('shelljs');
    
    module.exports = {
      updateFrontend: () => {
        // const path = "cd && cd Projects/dealers/frontend";
        // const actions = "kill -9 $(lsof -t -i:8000 -sTCP:LISTEN) && npm run clean && gatsby develop -H 0.0.0.0";
    
        const path = "cd /home/web";
        const actions = "bash release_frontend.sh";
    
        try {
          shell.exec(`${path} && ${actions}`, function(code, stdout, stderr) {
            if (code) {
              console.error(code);
              return;
            }
          });
        } catch (error) {
          console.log(error);
        }
      }
    };

When I try it on localhost with:

    const path = "cd && cd Projects/dealers/frontend";
    const actions = "kill -9 $(lsof -t -i:8000 -sTCP:LISTEN) && npm run clean && gatsby develop -H 0.0.0.0";

It works fine, and the content is updated.

But when I try to do it on the server, with:

    const path = "cd /home/web";
    const actions = "bash release_frontend.sh";

Where `release_frontend.sh` is as follows:

    #!/bin/bash
    
    
    cd /home/web/project/frontend
    cp /var/www/frontend/gatsby-config.js gatsby-config.js
    
    rm -rf .cache
    rm -rf public
    npm run clean
    npm run build
    
    
    cp gatsby-config.js /var/www/frontend/gatsby-config.js
    cd public
    cp -r * /var/www/frontend
    
    
    echo Frontend Done !

I'm getting bunch of error as:

    Encountered an error trying to infer a GraphQL type for: `ninth_banner_image_1___NODE`. There is no corresponding node with the `id` field matching: "/home/web/project/frontend/.cache/gatsby-source-filesystem/6b4e342a100b59958d193a7e332510bb.png absPath of file".

Those errors are connected to `gatsby cache` I think. When I get similar error on localhost I do `npm run clean` and the errors are gone.

What am I doing wrong?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
