### ISSUE TITLE
gatsby-plugin-typescript missing dependency on @babel/core and graphql

### ISSUE THREAD

**Issue by bradleyayers** [gatsbyjs/gatsby#20900]
## Description

gatsby-plugin-typescript ([package.json](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-typescript/package.json)) depends on @babel/plugin-proposal-nullish-coalescing-operator which depends on @babel/core, but gatsby-plugin-typescript doesn't provide that. Under Yarn 2, it's required that gatsby-plugin-typescript has a dependency on @babel/core to satisfy the peer dependency.

There are a few other similar problems, see the **Actual result** for details.

### Steps to reproduce

Using Yarn 2, install gatsby-plugin-typescript:

```
yarn add gatsby-plugin-typescript
```

### Expected result

No warnings.

### Actual result

The following warnings:

```
➤ YN0002: │ gatsby-plugin-typescript@npm:2.1.26 [c440d] doesn't provide @babel/core@^7.0.0-0 requested by @babel/plugin-proposal-nullish-coalescing-operator@npm:7.8.3
➤ YN0002: │ gatsby-plugin-typescript@npm:2.1.26 [c440d] doesn't provide @babel/core@^7.0.0-0 requested by @babel/plugin-proposal-numeric-separator@npm:7.8.3
➤ YN0002: │ gatsby-plugin-typescript@npm:2.1.26 [c440d] doesn't provide @babel/core@^7.0.0-0 requested by @babel/plugin-proposal-optional-chaining@npm:7.8.3
➤ YN0002: │ gatsby-plugin-typescript@npm:2.1.26 [c440d] doesn't provide @babel/core@^7.0.0-0 requested by @babel/preset-typescript@npm:7.8.3
➤ YN0002: │ gatsby-plugin-typescript@npm:2.1.26 [c440d] doesn't provide graphql@^14.1.1 requested by babel-plugin-remove-graphql-queries@npm:2.7.22
```

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /var/folders/bb/_7t480814vs707cy3zwd2nmw0000gn/T/tmp-75203E13XLopLwHnI/node
    Yarn: 2.0.0-rc.27 - /var/folders/bb/_7t480814vs707cy3zwd2nmw0000gn/T/tmp-75203E13XLopLwHnI/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 13.0.4
```

**Comment by Austaras** [comment]
for anyone fixing this, please remove @babel/plugin-proposal-nullish-coalescing-operator and @babel/plugin-proposal-optional-chaining from dependence, they are provided by @babel/preset-env already
