### ISSUE TITLE
Sorting in GraphQL 

### ISSUE THREAD

**Issue by sonapraneeth-a** [gatsbyjs/gatsby#20912]
## Summary

Is it possible to sort entries in a graphql query based on multiple fields?

Let us suppose, our graphql schema is as below. Can we sort allEmployee based on ```id``` in ASC and ```date``` in DESC?
```
allEmployee {
  id
  date
}
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by classicmatsuo** [comment]
yes, [codepen example](https://711808k40x.sse.codesandbox.io/___graphql?query=%7B%0A%20%20allMarkdownRemark(%0A%20%20%20%20sort%3A%20%7B%0A%20%20%20%20%20%20fields%3A%20%5Bfrontmatter___date%2C%20frontmatter___title%5D%0A%20%20%20%20%20%20order%3A%20%5BASC%2C%20DESC%5D%0A%20%20%20%20%7D%0A%20%20)%20%7B%0A%20%20%20%20totalCount%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20frontmatter%20%7B%0A%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%20%20date%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&explorerIsOpen=false).
you would add `id` and `date` to the fields array and `ASC` and `DESC` to the order array.

**Comment by sonapraneeth-a** [comment]
Why does such an option not show in GraphiQL?

**Comment by sidharthachatterjee** [comment]
Looks like it _does_ show up

<img width="742" alt="Screenshot 2020-02-13 at 1 37 49 AM" src="https://user-images.githubusercontent.com/7701981/74372916-7f8b7080-4e01-11ea-8bc6-0397c70ee68a.png">

Closing this for now. Thanks!
