### ISSUE TITLE
The request failed with error code "ENOTFOUND"

### ISSUE THREAD

**Issue by KamranMaqbool** [gatsbyjs/gatsby#20916]
gatsby-source-wordpress give error

The request failed with error code "ENOTFOUND"
ERROR #11321  PLUGIN

"gatsby-source-wordpress" threw an error while running the sourceNodes lifecycle:

Cannot read property 'data' of undefined

  TypeError: Cannot read property 'data' of undefined

**Comment by vladar** [comment]
As far as I understand this is the same issue as #20863 Let's close this one and track the status there as it has more info.
