### ISSUE TITLE
why did you stop using dangerouslyset

### ISSUE THREAD

**Issue by redknite** [gatsbyjs/gatsby#20929]
Why did you stop using dangerouslysethtml in page.js and post.js? 

it used to be 
```
                <h1 dangerouslySetInnerHTML={{__html: currentPage.title}}/>
                <div dangerouslySetInnerHTML={{__html: currentPage.content}}/>
```

but now is just
```

        <h1>{StaticPage.title}</h1>
        <div>{StaticPage.content}</div>
```

**Comment by redknite** [comment]
no one?

**Comment by LekoArts** [comment]
To what are you referring to? Sorry, but I don't understand your question. Please give more details or provide links. Thanks!

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
