### ISSUE TITLE
Couldn't find preset "env" relative to directory

### ISSUE THREAD

**Issue by tylermcginnis** [gatsbyjs/gatsby#2092]
node: v8.4.0
npm: 5.4.1
yarn: 1.0.1
gatsby-cli@1.1.6

Tried deleting node_modules and reinstalling.

<img width="821" alt="screen shot 2017-09-12 at 12 27 29 am" src="https://user-images.githubusercontent.com/2933430/30311198-621da8d8-9751-11e7-8d69-87828a08f829.png">

**Comment by KyleAMathews** [comment]
Perhaps you have a babelrc that's causing trouble? Is this a vanilla starter install?

**Comment by tylermcginnis** [comment]
Yeah brand new. 

npm install --global gatsby-cli
gatsby new gatsby-site
cd gatsby-site
gatsby develop

Just tried with `gatsby new blog https://github.com/gatsbyjs/gatsby-starter-blog` and it worked 🤷‍♀️. Not sure what happened the first time but I assume it was something on my end. Thanks again Kyle! xoox
