### ISSUE TITLE
(www) Invalid prism language 

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#20926]
## Description

When running `gatsby develop` on `www`:

```
warn code block or inline code language not specified in
warn unable to find prism language 'sh' for highlighting.
warn unable to find prism language 'console' for
warn unable to find prism language 'plain' for
warn unable to find prism language ' for highlighting.
warn unable to find prism language 'dotenv' for
warn unable to find prism language '.gitignore' for
warn unable to find prism language 'grahpql' for
warn unable to find prism language '.json' for
warn unable to find prism language 'jsxharmony' for
warn unable to find prism language 'gatsby-config.js' for
warn unable to find prism language 'shellscript' for
```

### Steps to reproduce

Run `gatsby develop` on the `www` directory of the gatsby repo.

### Expected result

No warnings.

### Actual result

The above warning

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.1 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 70.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.8 => 2.18.22 
    gatsby-design-tokens: ~1.0.10 => 1.0.10 
    gatsby-image: ^2.2.34 => 2.2.38 
    gatsby-plugin-canonical-urls: ^2.1.16 => 2.1.19 
    gatsby-plugin-catch-links: ^2.1.19 => 2.1.24 
    gatsby-plugin-emotion: ^4.1.16 => 4.1.21 
    gatsby-plugin-feed: ^2.3.23 => 2.3.26 
    gatsby-plugin-google-analytics: ^2.1.29 => 2.1.33 
    gatsby-plugin-google-tagmanager: ^2.1.18 => 2.1.24 
    gatsby-plugin-guess-js: ^1.1.26 => 1.1.29 
    gatsby-plugin-layout: ^1.1.16 => 1.1.21 
    gatsby-plugin-mailchimp: ^2.2.3 => 2.2.3 
    gatsby-plugin-manifest: ^2.2.31 => 2.2.37 
    gatsby-plugin-mdx: ^1.0.59 => 1.0.67 
    gatsby-plugin-netlify: ^2.1.28 => 2.1.31 
    gatsby-plugin-netlify-cache: ^0.1.0 => 0.1.0 
    gatsby-plugin-nprogress: ^2.1.15 => 2.1.18 
    gatsby-plugin-offline: ^3.0.27 => 3.0.31 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.21 
    gatsby-plugin-sharp: ^2.3.5 => 2.3.13 
    gatsby-plugin-sitemap: ^2.2.22 => 2.2.25 
    gatsby-plugin-theme-ui: ^0.2.43 => 0.2.53 
    gatsby-plugin-twitter: ^2.1.15 => 2.1.18 
    gatsby-plugin-typography: ^2.3.18 => 2.3.21 
    gatsby-remark-autolink-headers: ^2.1.19 => 2.1.23 
    gatsby-remark-code-titles: ^1.1.0 => 1.1.0 
    gatsby-remark-copy-linked-files: ^2.1.31 => 2.1.36 
    gatsby-remark-embedder: ^1.11.0 => 1.7.0 
    gatsby-remark-graphviz: ^1.1.18 => 1.1.21 
    gatsby-remark-images: ^3.1.35 => 3.1.42 
    gatsby-remark-normalize-paths: ^1.0.0 => 1.0.0 
    gatsby-remark-prismjs: ^3.3.25 => 3.3.30 
    gatsby-remark-responsive-iframe: ^2.2.28 => 2.2.31 
    gatsby-remark-smartypants: ^2.1.17 => 2.1.20 
    gatsby-source-airtable: ^2.0.12 => 2.0.12 
    gatsby-source-filesystem: ^2.1.40 => 2.1.46 
    gatsby-source-git: ^1.0.2 => 1.0.2 
    gatsby-source-npm-package-search: ^2.1.19 => 2.1.22 
    gatsby-transformer-csv: ^2.1.19 => 2.1.24 
    gatsby-transformer-documentationjs: ^4.1.20 => 4.1.23 
    gatsby-transformer-remark: ^2.6.39 => 2.6.48 
    gatsby-transformer-screenshot: ^2.1.44 => 2.1.49 
    gatsby-transformer-sharp: ^2.3.7 => 2.3.12 
    gatsby-transformer-yaml: ^2.2.18 => 2.2.23 
  npmGlobalPackages:
    gatsby-cli: 2.8.26

**Comment by muescha** [comment]
most of the wrong languages comes from external readme (plugins)

maybe it helps a little bit, to also print to the console the file/doc/repo where this happening

**Comment by muescha** [comment]
-> `prism language 'gatsby_graphql_endpoint=http://localhost:20002/graphql'`
- https://github.com/praisegeek/gatsby-plugin-appsync/pull/2
