### ISSUE TITLE
[1.9.28] gatsby-ssr.js onRenderBody does not contain definition pathname

### ISSUE THREAD

**Issue by davidhouweling** [gatsbyjs/gatsby#2093]
Based on the [documentation for Gatsby Server Rendering APIs](https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody), there should be a property `pathname`, however I believe a [recent refactor](https://github.com/gatsbyjs/gatsby/pull/1254) caused the property to not be included.

I believe [this method call](https://github.com/gatsbyjs/gatsby/pull/1254/files#diff-d9b5ae54c723d4333b9e6e3dc40e880fR40) should include the pathname should it not?

I'm on Gatsby 1.9.28 on Windows 10 (but have a colleague on Mac with the same problem).

**Comment by KyleAMathews** [comment]
Indeed! Would you mind restoring it in a PR?

**Comment by davidhouweling** [comment]
@KyleAMathews i've tried to run the repo locally on windows by doing `yarn && yarn lerna bootstrap` but it doesn't seem to work too well on windows, resulting in a bunch of busy lock errors...

**Comment by icodejs** [comment]
@KyleAMathews I'd like to fix this bug and submit a PR, but I'm having trouble working out how to make the fix locally and point my personal Gatsby application at it.

I intend on making the following change to `packages/gatsby/cache-dir/develop-static-entry.js`:

```javascript
  apiRunner(`onRenderBody`, {
    setHeadComponents,
    setPreBodyComponents,
    setPostBodyComponents,
    setBodyProps,
    pathname: locals.path,
  })
``` 
Would you be able to give me instructions on how to build the above change and where to point my personal Gatsby application too so I can test it works?

Thanks

**Comment by KyleAMathews** [comment]
Awesome! Looking forward to your PR!

Check out the instructions at https://www.gatsbyjs.org/docs/how-to-contribute/#contributing

**Comment by sebastienfi** [comment]
@davidhouweling Avoid the `&&` operator unless you've [installed the Linux Subsystem on Windows](https://msdn.microsoft.com/fr-fr/commandline/wsl/install_guide)

You can chain commands on the regular Windows Bash using `&`

Therefore, try `git clone https://github.com/gatsbyjs/gatsby.git & cd gatsby & yarn run bootstrap & yarn test`.
You may also want to give a look at [Gatsby on Windows](https://www.gatsbyjs.org/docs/gatsby-on-windows/) docs section.

**Comment by davidhouweling** [comment]
@sebastienfi thanks for the tip. I was running them separately locally, just made it easier for documenting here. I did pair with @icodejs and another work colleague to attempt to fix it. We did get it fixed, but found that the `pathname` isn't called for every instance, but only for the top level html file I believe.

I felt the idea of onRenderBody should trigger after all the createPage calls are performed, but doesn't seem to be so.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
