### ISSUE TITLE
(docs) Figure out how to localize the glossary

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#20930]
## Description

The [glossary](https://www.gatsbyjs.org/docs/glossary/) is a Markdown file that lists Gatsby-related terms in alphabetical order:

```md
## A

### AST

Abstract Syntax Tree: A tree representation of the source code that is found during a [compilation](#compiler) step between two languages. For example, [gatsby-transformer-remark](/packages/gatsby-transformer-remark/) will create an AST from [Markdown](#markdown) to describe a Markdown document in a tree structure using the [Remark](#remark) parser.

### API

Application Programming Interface: A method for one application to communicate with another. For example, a [source plugin](#source-plugin) will often use an API to get its data.

### Accessibility

The inclusive practice of removing barriers that prevent interaction with, or access to websites, by people with disabilities. When sites are correctly designed, developed and edited for accessibility, generally all users have equal access to information and functionality. Read about [Gatsby's Commitment to Accessibility](/blog/2019-04-18-gatsby-commitment-to-accessibility/).
```

While this is simple and works for English, we run into problems when we try to translate this page. Pages in other languages may have entries that begin with different letters. This puts an undue burden on translators to rearrange the glossary, and makes it difficult to track which translated entries refer to which English ones.

Also, some languages don't use the Latin script, and will need to sort their entries a different way.

## Solutions

One way to fix this is by splitting up each of the glossary's terms to a single markdown page in the `glossary/` directory:

```
docs/
  glossary/
    ast.md
    api.md
    accessibility.md
    ...
```

Then, instead of creating a page for each of these markdown pages, we can query them all at once in `pages/docs/glossary.js`:

```js
export default function Glossary({ data }) {
  return <Container>
    <h1>Glossary</h1>
    {data.allMdx.nodes.map(node => {
    return <MDXRenderer>{node.body}</MDXRenderer>
  })}
  </Container>
}

export const pageQuery = graphql`
  query {
    allMdx(filter: { fields: { slug: { in: "/docs/glossary" } } }) {
      nodes {
       body
      }
    }
  }
`
```
This allows maintainers and translators to edit each markdown file individually, but lets us do things like sorting by local alphabet, or even a filter.

**Comment by AishaBlake** [comment]
I'm seeing this organized like a blog sourced from Markdown in that we could still have the existing blurbs show up on the Glossary page and link out to the individual encyclopedia articles. @hashimwarren it looks like the PR I merged today is the last in that series... Am I correct there?

**Comment by marcysutton** [comment]
I think those encyclopedia articles are still going, based on internal activity. I'd recommend bringing it up in Slack to discuss!
