### ISSUE TITLE
Simple login password authentication not working on PROD version

### ISSUE THREAD

**Issue by Monsiter** [gatsbyjs/gatsby#20938]
## Description

I just added password protection to the documentation app. The protection functionality working as expected but the styling crashing when I use `gatsby build` and `gatsby serve`. Everything working as expected on `gatsby develop`

### Steps to reproduce

In `gatsby-ssr.js` and `gatsby-browser.js` I have same code as bellow
```
import React from 'react';
import {
  isLoggedIn
} from './src/utils/utils';
import PasswordProtect from './src/components/PasswordProtect';
import "./src/styles/login.css";

export const wrapPageElement = ({ element, props }) => {
  // correct password
  if (isLoggedIn()) {
    return;
  }

  // check password
  return <PasswordProtect />;
};
```
The `isLoggedIn()` function is very simple(utils.js bellow):
```
import Cookies from 'js-cookie';

const COOKIE_NAME = 'gatsby-theme-password-protect';

export const setSessionPassword = passwordCandidate => {
  Cookies.set(COOKIE_NAME, passwordCandidate);
};

export const getSessionPassword = () => {
  return Cookies.get(COOKIE_NAME);
};

export const isLoggedIn = () => {
  return getSessionPassword() === 'SamplePassword';
};
```
And finally in `PasswordProtect` component I have:
```
import React, {Component} from 'react';
import {setSessionPassword, isLoggedIn} from '../utils/utils';

export default class PasswordProtect extends Component {
    state = {
        password: '',
        isLoggedIn: false
    }

    componentDidMount() {
        if (isLoggedIn()) {
            this.setState({
                isLoggedIn: true
            });
        }

        this.forceUpdate();
    }

    render() {
        const {
            password,
            isLoggedIn
        } = this.state;

        const onSubmit = event => {
            event.preventDefault();
            setSessionPassword(password);
            window.location.reload();
        };

        return (
            <React.Fragment>
                <div className={(isLoggedIn ? null : 'login-wrapper')}>

                    <form onSubmit={onSubmit} className="login">

                        <fieldset>
                            <div className="input">
                                <input value={password} onChange={event => this.setState({password: event.target.value})} type="password" placeholder="Password" required/>
                            </div>

                            <button type="submit" className="submit">SUBMIT</button>
                        </fieldset>
                    </form>
                </div>
            </React.Fragment>
        )
    }
}
```

### Expected result

I should have on login screen in the wrapper div the class `login-wrapper` and when I log in then the class should disappear

### Actual result

I have `login-wrapper` on the login screen and after log in

### Environment

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.10 => 2.18.10
    gatsby-link: ^2.2.27 => 2.2.27
    gatsby-plugin-algolia: ^0.5.0 => 0.5.0
    gatsby-plugin-emotion: ^4.1.18 => 4.1.18
    gatsby-plugin-gtag: ^1.0.12 => 1.0.12
    gatsby-plugin-layout: ^1.1.18 => 1.1.18
    gatsby-plugin-manifest: ^2.2.33 => 2.2.33
    gatsby-plugin-mdx: ^1.0.61 => 1.0.61
    gatsby-plugin-offline: ^3.0.29 => 3.0.29
    gatsby-plugin-react-helmet: ^3.1.18 => 3.1.18
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.1.17 => 2.1.17
    gatsby-plugin-sharp: ^2.3.7 => 2.3.7
    gatsby-plugin-sitemap: ^2.2.24 => 2.2.24
    gatsby-remark-copy-linked-files: ^2.1.33 => 2.1.33
    gatsby-remark-images: ^3.1.37 => 3.1.37
    gatsby-source-filesystem: ^2.1.42 => 2.1.42
    gatsby-transformer-remark: ^2.6.42 => 2.6.42
  npmGlobalPackages:
    gatsby-cli: 2.8.27

**Comment by devrchancay** [comment]
I see no error with the naked eye, you think you can replicate it in codesanbox to help you better

**Comment by sidharthachatterjee** [comment]
@Monsiter When `gatsby build` is run, your code is rendered via React SSR in which case cookies would be unavailable and hence that class is rendered.

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
