### ISSUE TITLE
Gatsby develop and build getting failed when I unpublish an entry on Contentful. It started happening after I update the gatsby version.

### ISSUE THREAD

**Issue by sonusynup** [gatsbyjs/gatsby#20937]
## Description

I have been using gatsby and contentful for my static website.
After I unpublish a Contentful entry, gatsby develop and build getting failed. I've tried to clear the cache but unfortunately the problem still persists.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

gatsby develop should be successful and should create all pages.

### Actual result

gatsby develop getting failed with this error:

![Screenshot 2020-01-28 at 1 43 57 PM](https://user-images.githubusercontent.com/48202771/73246339-5ef1d280-41d4-11ea-84ba-56b344384e31.png)

### Environment

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/local/bin/node
    npm: 6.13.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.19.5 => 2.19.5
    gatsby-image: ^2.2.30 => 2.2.36
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6
    gatsby-plugin-manifest: ^2.2.26 => 2.2.33
    gatsby-plugin-modal-routing: ^1.1.0 => 1.1.0
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.18
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sass: ^2.1.20 => 2.1.26
    gatsby-plugin-sharp: ^2.4.0 => 2.4.0
    gatsby-plugin-sitemap: ^2.2.21 => 2.2.24
    gatsby-plugin-tidy: ^1.0.1 => 1.0.1
    gatsby-plugin-zopfli: ^1.3.2 => 1.3.2
    gatsby-source-contentful: ^2.1.82 => 2.1.82
    gatsby-source-filesystem: ^2.1.35 => 2.1.42
    gatsby-transformer-sharp: ^2.3.2 => 2.3.9
  npmGlobalPackages:
    gatsby-cli: 2.8.27

**Comment by vladar** [comment]
Please try `gatsby@2.19.7`. This issue should be fixed there via #20904

**Comment by sonusynup** [comment]
Thanks @vladar. It works!
