### ISSUE TITLE
(www) Update Algolia DocSearch to support localizations

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#20932]
## Description

Update DocSearch so that it has intuitive behavior once localized docs are on the main site. Ideally, searching the docs will only yield content in the current language.

**Comment by tesseralis** [comment]
It seems like there is support here: https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/how-to/multilingual-search/

**Comment by marcysutton** [comment]
This could be done as part of https://github.com/gatsbyjs/gatsby/issues/12503; search improvements have been on our list for a while, and are currently slated for Q2 in terms of priorities.
