### ISSUE TITLE
Styles not applying on page load

### ISSUE THREAD

**Issue by vinyltek** [gatsbyjs/gatsby#20933]
The css on my thank-you and 404 page seem to be applying a many seconds after page load. This seems to be happening on build. I have required **babel-plugin-styled-components**, **gatsby-plugin-styled-components** & s**tyled-components** installed and configured in my project.

 I've looked into related issues: https://github.com/gatsbyjs/gatsby/issues/14978#issuecomment-514372027 & https://github.com/gatsbyjs/gatsby/issues/9902 but i cant seem to find a solution!

Thanks in advance!

**UPDATE**
I also noticed quite a few duplications of things within my <head></head> tags

**Comment by danspratling** [comment]
We're going to need more info to be able to diagnose the issue you're having. Styled components works well across multiple projects, and it sounds like you're only having the issue on 2 pages?

If you can create a minimal reproducible example that would be really useful to help others diagnose your problem. You may also realise the issue which is happening as you're creating it.

Instructions for setting up styled components can be found here https://www.gatsbyjs.org/docs/styled-components/

You can also find a substantial number of starters using styled components which may guide you in the right direction by comparing code.
https://www.gatsbyjs.org/starters/?d=gatsby-plugin-styled-components&v=2

**Comment by vinyltek** [comment]
> We're going to need more info to be able to diagnose the issue you're having. Styled components works well across multiple projects, and it sounds like you're only having the issue on 2 pages?
> 
> If you can create a minimal reproducible example that would be really useful to help others diagnose your problem. You may also realise the issue which is happening as you're creating it.
> 
> Instructions for setting up styled components can be found here https://www.gatsbyjs.org/docs/styled-components/
> 
> You can also find a substantial number of starters using styled components which may guide you in the right direction by comparing code.
> https://www.gatsbyjs.org/starters/?d=gatsby-plugin-styled-components&v=2

Hey @danspratling thanks for the reply! Yes it only seems to be happening on two pages (thank-you & 404). For now here's a link to the errors:

Thank You Page: https://vinyl-tekshutters.com/thank-you/
404 Page: https://vinyl-tekshutters.com/wrong-path

The styles either take a REALLY long time to load, or dont load at all. I can notice quite a few things going on in the network tab in chrome, but i dont know hot to analyze this data :( 

I can get a reproduction tonight for you!

**Comment by vinyltek** [comment]
**UPDATE:**
It seems as if the styles tend to load whenever you hover near to a <Link></Link>

**Comment by vinyltek** [comment]
**UPDATE**
Problem solved!!! It seems as if i forgot to wrap my 404.js & thank-you.js pages with the <Layout /> component!
