### ISSUE TITLE
Bundle Consumable Self-hydrating Gatsby Component Library

### ISSUE THREAD

**Issue by mythril** [gatsbyjs/gatsby#20940]
## Summary

I think it would be nice if gatsby could easily generate a self-hydrating component library that can be consumed by other projects / static HTML. 

### Basic example

Maybe a `library.js` entry point that would export the components meant for the library. I kind of assume this would only make sense for components based around `StaticQuery` / `useStaticQuery` but I haven't thought too deeply about it.

### Motivation

My current use case for this is that I am looking to incrementally upgrade a static HTML site with a new one, and a big ticket is to make the navigation consistent across all of the pages, (legacy and gatsby). The cleanest way I can think of to do this with the least amount of rewriting is to just export the Nav components into their own standalone components and then `ReactDOM.render()` them into their respective places in the legacy structure.

At least [one other developer has](https://stackoverflow.com/questions/58942573/access-json-chunk-exported-from-gatsby-static-query?newreg=fc9b44f01f434b03b88fdc18408870a8) had a similar problem, and I'm sure it's a common thought for migrating sites to gatsby.

**Comment by mythril** [comment]
Thinking about it a second longer maybe each `libraries/*.js` would create a separate library bundle named after the file it was sourced from.

**Comment by mythril** [comment]
@coreyward mentioning you just in case you are interested in critiquing my suggestion / adding to it.

**Comment by mythril** [comment]
It looks like @coreyward was kind enough to write up how they did it https://coreyward.svbtle.com/exporting-an-embeddable-react-component-from-a-gatsby-app

**Comment by coreyward** [comment]
For what it's worth, the approach I took doesn't instrument SSR, but if you wanted to include that it would be reasonably straightforward to add.
