### ISSUE TITLE
Clean up query runner

### ISSUE THREAD

**Issue by freiksenet** [gatsbyjs/gatsby#20941]
Query runner is currently controlled by the queue and then recreated. Ideally it should know how to reset it's state (which is basically node-model) on changes like schema or data. In future that can lead to us being able to do partial cache resets, not full.

**Comment by vladar** [comment]
Related: #20586

**Comment by rbelow** [comment]
For my understanding @freiksenet : The query runner should know; how to reset its state on changes like schema or data.

The query runner only should know; how, or it also should do it? If it only knows; how - who should trigger the state reset instead?
