### ISSUE TITLE
gatsby-plugin-mdx infinite render loop on changing file content

### ISSUE THREAD

**Issue by DominicTobias** [gatsbyjs/gatsby#20942]
## Description

Hi, using the following MDX example: https://github.com/mdx-js/mdx/tree/master/examples/syntax-highlighting

I observed that while everything works (even without `gatsby-source-filesystem`, though following this README I added it but seems to make no difference), if I make a change to a component in the MDX tree (works fine for other components), it causes an infinite render loop coming from the a level above user code and infinitely rendering the Layout pointed to here:

```
resolve: 'gatsby-plugin-mdx',
  options: {
    defaultLayouts: {
      default: require.resolve('./src/components/Layout'),
    },
  },
}
```

I observed that all of the objects entering the Layout component are new every loop, so `memo` and `PureComponent` do nothing to prevent it.

I also observed that there is nothing in the terminal to indicate a loop is going on.

Doing a browser refresh fixes it until the next change.

### Steps to reproduce

Clone https://github.com/mdx-js/mdx/tree/master/examples/syntax-highlighting

Put a console log in the render method of components/Layout .

Run it and go to the browser. Change the console log text and observe an infinite render loop starts.

```
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1
    Safari: 13.0.4
  npmGlobalPackages:
    gatsby-cli: 2.8.27
    gatsby: 2.19.7
```

**Comment by vladar** [comment]
Hi @DominicTobias 

I tried but couldn't reproduce it locally. I don't have an infinite render loop. Maybe you could [provide a minimal reproduction][reproduction] or alternatively try reproducing it on [codesandbox](https://codesandbox.io/) to eliminate platform-specific issues?

[reproduction]: https://gatsby.dev/reproduction

**Comment by DominicTobias** [comment]
Hi Thanks for the effort, that’s interesting I’ll try and repro on
codesandbox tomorrow

**Comment by DominicTobias** [comment]
@vladar I had trouble getting codesandbox to run, but I can reliably repo the issue.

Here is a prepared repo, even simpler than the original: https://github.com/DominicTobias/mdx-infinite-render-loop

Steps to repo:
- `yarn start`
- Open up browser and observe this page:
![Screenshot 2020-01-30 at 18 41 53](https://user-images.githubusercontent.com/760314/73442666-33b3e280-4390-11ea-9fac-96d51ecbf49b.png)
- Go to `index.mdx` and change anything for example `padding: "20px",` -> `padding: "21px",`
- Observe infinite render loop in browser:
![Screenshot 2020-01-30 at 18 42 50](https://user-images.githubusercontent.com/760314/73442742-5514ce80-4390-11ea-87bb-4aed1bf1ccdf.png)

**Comment by DominicTobias** [comment]
Interestingly the issue only occurs if `<LivePreview />` component is rendered 🤔
