### ISSUE TITLE
[docs][Tutorial] Using Multiple Themes Together. 

### ISSUE THREAD

**Issue by Ekwuno** [gatsbyjs/gatsby#20947]
## Summary

When new Gatsby users come across the concept of themes they become excited about the possibilities it offers. Even more when they see the added advantage of using themes over starters, with more emphasis on using "Multiple themes" on one site.

The concept is explained in this [part of the theme doc](https://www.gatsbyjs.org/docs/themes/using-multiple-gatsby-themes/). However, the docs could benefit from a tutorial on how to use multiple themes at once.

Some recommended topics to cover:

- Using multiple themes in `gatsby-config` 
- Component shadowing 
*This list is more extensive, but further research is necessary*

### Motivation
To provide Gatsby users with a detailed tutorial, on understanding how multiple themes can work together in Gatsby. Practical examples are always helpful. 

### Location in Doc 

https://www.gatsbyjs.org/tutorial/using-multiple-themes-together

**Comment by ehowey** [comment]
I have some experience with this - I would be interested to help out if you wanted any help?

**Comment by Ekwuno** [comment]
Awesome! @ehowey I am happy to collaborate with you on this. Would you like to share your thoughts on topics to cover?

**Comment by Ekwuno** [comment]
I am looking to use the gatsby-theme-blog & gatsby-theme-notes to show this as these are themes Gatsby maintains.

**Comment by ehowey** [comment]
Hi Ekwuno,
These are just some thoughts that have been rambling in my head:

- A mental model for explaining themes, I think what Gatsby has is different enough from WP and Drupal that it would maybe be helpful for their to be an introduction so people can understand that themes are _composed_ together, almost like building a lego set, or orchestrating a music piece. 

- I agree with sticking with official Gatsby themes but it would be nice to be able to demonstrate both "large" themes, like gatsby-theme-blog, and "small" themes like gatsby-mdx-embed. I think this would help to start opening people's eyes as to how themes can be small discrete units of function or larger more complex full featured sites e.g. Novela. It would be interesting to build from the ground up to a "finished" site using only themes and plugins.

- Maybe worthwhile to explain latent component shadowing? Maybe this is more advanced though...

I think that is all I have for now. I would be happy to take a go at writing a first draft but don't want to take this away from you if you have a vision for it.

**Comment by Ekwuno** [comment]
Hi Eric, I apologize for my slow response, other projects became higher priority. I am ready to start working on this.  I agree it would be great to show how themes can be small discrete units of function or larger more complex full-featured sites. Kindly send in the first draft if you have started anything and we could work on it from there. 😄

**Comment by ehowey** [comment]
Hi Ekwuno,

I didn't do any work yet - didn't want both us working simultaneously, or unnecessarily.  I don't mind taking a go at a first draft.  It will probably take me over the weekend to have something useful to look at.  I will open a PR and an example repo. Does that work for you?

**Comment by Ekwuno** [comment]
Yes! That sounds great. Thank you 💜

**Comment by Ekwuno** [comment]
Hi Eric, How's it going? Did you get a minute to work on this over the weekend?

**Comment by ehowey** [comment]
HI Obinna,

I had a freelance contract pop up that ate up my time over the weekend. Sorry about that.  I do have this on my mental to-do list but the paid work had to take precedent.  I will aim to get something rough done soon!

**Comment by Ekwuno** [comment]
oh, no worries. I appreciate you even taking the time to work on this with me. I will keep an eye out

**Comment by ehowey** [comment]
If you look now there is some progress in that PR. There is about 75% of a first draft in there.  Hopefully I will finish a first draft in the next few days.
