### ISSUE TITLE
gatsbyjs.com loads blank screen

### ISSUE THREAD

**Issue by brotzky** [gatsbyjs/gatsby#20954]
## Description

When loading gatsbyjs.com I get a blank white screen.
This appears to be a service worker issue.

Here's the console and network:
<img width="1715" alt="Screen Shot 2020-01-28 at 9 37 44 AM" src="https://user-images.githubusercontent.com/8007686/73289629-e4b05680-41b1-11ea-9cd0-d4d2546a6e44.png">
<img width="1715" alt="Screen Shot 2020-01-28 at 9 38 01 AM" src="https://user-images.githubusercontent.com/8007686/73289633-e7ab4700-41b1-11ea-9295-495f8237d939.png">

When I clear storage the site loads without issue for the first reload. But then reloading the page I get a different error.

<img width="1715" alt="Screen Shot 2020-01-28 at 9 40 45 AM" src="https://user-images.githubusercontent.com/8007686/73289874-47a1ed80-41b2-11ea-93b7-49ac7f5f4f7a.png">

```
idb-keyval-iife.min.js:1 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at https://www.gatsbyjs.com/idb-keyval-iife.min.js:1:353
```

**Comment by brotzky** [comment]
I wasn't going to open this issues but the second error was really strange. Occurred after I cleared the SW, refreshed the page, and then hard refreshed the page.

I know the report isn't too helpful but SWs are hard to nail down and report. Feel free to close this issue without discussion and just add it as a mental note that there could be something up with the SW or caching / IndexDB.

**Comment by t2ca** [comment]
I can confirm, I am having the same experience. @KyleAMathews 

Steps to reproduce:
1. Go to gatsbyjs.com 
2. Click on docs in the menu
3. Click reload page
4. White screen

Error in console:

```
Uncaught (in promise) Error: Loading CSS chunk 1 failed.
(/styles.10a829321d99231116e5.css)
    at HTMLLinkElement.a.<computed>.a.<computed>.<computed>.t.push.a.<computed>.m.onerror (bootstrap:129)
```

**Comment by pieh** [comment]
We are looking into this now

**Comment by pieh** [comment]
Not yet fixed, but we are using bit old version of offline plugin, so we will be updating that (once it goes through review etc)

**Comment by lablancas** [comment]
I was having the same issue, but removing `gatsby-plugin-offline` and installing `gatsby-plugin-remove-serviceworker` fixed the issue for me. Looking forward to adding this plugin back into my site when this issue is fixed.

**Comment by marcysutton** [comment]
Is this issue still occurring for anyone? It isn't for me. I'm wondering if we can close the issue now. Thanks for opening it!

**Comment by brotzky** [comment]
It's not occurring for me anymore. Good call, @marcysutton. I'll close this for now.
