### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by KamranMaqbool** [gatsbyjs/gatsby#20957]
install gatsby-plugin-sharp plugin but when run command 

> gatsby develop
then return error

![Screenshot from 2020-01-28 23-05-22](https://user-images.githubusercontent.com/53546053/73291811-c0409280-4222-11ea-9f0c-5c286e351021.png)

**Comment by galvogalvo** [comment]
@KamranMaqbool I sometimes see this, especially when moving between different branches that have different dependency versions, sharp seems especially vulnerable to this. 

To resolve I do (with yarn):
- `rm -r node_modules/sharp`
- `yarn install --check-files`

**Comment by vladar** [comment]
Thank you for opening this, @KamranMaqbool 

There are several issues discussing this problem with suggested solutions:

#18277
#17659
#15320

Try those, one of them should fix it for you.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by Riya0503** [comment]
**TypeError: Cannot read property '_context' of undefined in Gatsby**
Gatsby build shows no error but on opening http://localhost:8000/ it's showing this error.

useContext node_modules/react/cjs/react.development.js:1481
```
> 1478 | } // TODO: add a more generic warning for invalid values.  
> 1479 |   
> 1480 |   
> 1481 | if (Context._context !== undefined) {  
> 1482 |   var realContext = Context._context; // Don't deduplicate because this legitimately causes bugs  
> 1483 |   // and nobody should be using this in existing code.  
> 1484 |
```

**Comment by goodpixels** [comment]
I am sorry @vladar, but I don't think this issue should be closed. Clearly many people run into this problem, and all of the "solutions" mentioned in other tickets are just workarounds.

I understand Sharp is an external dependency, but since it's a problem that's been bugging it for a long time and their developers have not fixed it yet, I think it's time to move away from Sharp, or at least make it optional.

I work on three different machines, and each time I want to clone a repository on one of them and work on my project I get this error.

Sharp should be removed or replaced with a better solution.

**Comment by belal-mazlom** [comment]
I tried all suggested solutions. it turns out yarn cache was the issue!
These steps fix my issue:
```properties
yarn cache clean
rm -rf node_modules
yarn
...
```

**Comment by matstlo** [comment]
> This error is killing me, spent 2 days trying to fix it and nothing...

Me too !!! Argggg. Did you solve your problem? How?!

**Comment by SergiOca87** [comment]
> > This error is killing me, spent 2 days trying to fix it and nothing...
> 
> Me too !!! Argggg. Did you solve your problem? How?!

Not yet, but I have found out this  and while I haven't tried yet, I feel it's close to my problem so it could potentially fix it:

https://github.com/lovell/sharp/issues/3086

I think there is a new version to address the issue.

**Comment by matstlo** [comment]
> 



> > > This error is killing me, spent 2 days trying to fix it and nothing...
> > 
> > 
> > Me too !!! Argggg. Did you solve your problem? How?!
> 
> Not yet, but I have found out this and while I haven't tried yet, I feel it's close to my problem so it could potentially fix it:
> 
> [lovell/sharp#3086](https://github.com/lovell/sharp/issues/3086)
> 
> I think there is a new version to address the issue.

I solved my problem here ! I really don't know why, but completely uninstalling NodeJs and reinstalling it (checking the box with tools) worked for me. Just updating it is not enough. Good luck !
