### ISSUE TITLE
[Docs] Gatsby Docs autolink headers need to be offset by navbar

### ISSUE THREAD

**Issue by Rikpat** [gatsbyjs/gatsby#20967]
## Description

I've noticed that after I've updated autolink-headers in #20363, Gatsby Docs scroll past the heading, not being offset by the navbar, since the autolink plugin now calculates from top of the page.

### Steps to reproduce

Go to docs and click on any header link, for example [here](https://www.gatsbyjs.org/docs/#go-further)

### Expected result

The heading should be below navbar, not hidden underneath

### Actual result

Heading is hidden underneath navbar

### Fix

Add offset (40 + 64px ?) to autolink headers, or dynamically to ::target pseudoelement (that's how I do it on my website)
I would do it myself, but I actually have no idea where the build repo for docs is (and if it's even publicly available)

**Comment by b0nbon1** [comment]
I can help you with this @Rikpat
