### ISSUE TITLE
Generating SSR bundle fails only during development with gatsby-ssr.js

### ISSUE THREAD

**Issue by kmcaloon** [gatsbyjs/gatsby#20961]
### Description

I have an app with custom `gatsby-browser.js` and `gatsby-ssr.js` leveraging `wrapRootElement` and `wrapPageElement` pretty much for a global context provider and layout component. Everything is working smoothly with `gatsby build`.  However, the ssr file is causing some issue during development as the process crashes because webpack can't resolve certain modules. If I comment out `gatsby-ssr.js`, development works fine.

I'm pretty sure this is related to a customized `setWebpackConfig` with some resolve settings (see below). Any idea what I might be doing wrong?

Here is the relevant code:

 **gatsby-ssr.js**
```
import React from 'react';
import App from './src/App';
import { AppContextProvider } from './src/AppContext';

/**
 * Wrapping root element with global providers.
 */
export const wrapRootElement = ( { element } ) => (

  <AppContextProvider>
    { element }
  </AppContextProvider>

);


/**
 * Wrapping html with Layout that persists between page transitions.
 */
export const wrapPageElement = ( { element, p } ) => {

  return(

    <App>
      { element }
    </App>

  );
};

```

**gatsby-node.js**
```
  actions.setWebpackConfig( {
    node: {
      fs: 'empty',
      net: 'empty'
    },
    resolve: {
      alias: {
        '@ant-design/icons/lib/dist$': path.resolve( __dirname, 'src/lib/icons.js' ),
        '~abstracts': path.resolve( __dirname, 'src/lib/_abstracts.scss' ),
        '~static': path.resolve( __dirname, 'static' ),
        '~components': path.resolve( __dirname, 'src/components' ),
      },
      modules: [
        path.resolve( __dirname, 'src' ),
        path.resolve( __dirname, 'src/components' ),
        'node_modules',
        path.resolve( __dirname ),
      ],
      plugins: [
        new DirectoryNamedWebpackPlugin( {
          honorIndex: true,
        } ),
      ],
    },
    plugins: [
      new LoadablePlugin(),
    ]
  } );
```

**Example errors**
```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't resolve 'AppContext' in '/Applications/MAMP/htdocs/dartdrones.com/src'

File: src/App.js

 ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't resolve 'lib/cart' in '/Applications/MAMP/htdocs/dartdrones.com/src'

File: src/AppContext.js
```

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.13.2 - ~/.nvm/versions/node/v13.2.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 65.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.13.9 => 2.19.5 
    gatsby-plugin-compression: ^0.0.1 => 0.0.1 
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1 
    gatsby-plugin-hotjar-tracking: ^1.0.0 => 1.0.0 
    gatsby-plugin-import: ^2.1.4 => 2.1.5 
    gatsby-plugin-loadable-components-ssr: ^1.0.7 => 1.0.7 
    gatsby-plugin-manifest: ^2.0.29 => 2.2.38 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-no-javascript: ^2.0.5 => 2.0.5 
    gatsby-plugin-olark: ^1.0.0 => 1.0.0 
    gatsby-plugin-preact: ^3.1.25 => 3.1.25 
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.21 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-sass: ^2.0.11 => 2.1.27 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5 
    gatsby-plugin-zopfli: ^1.3.2 => 1.3.2 
    gatsby-query-params: ^1.1.0 => 1.2.0 
    gatsby-source-filesystem: ^2.1.5 => 2.1.46

**Comment by pieh** [comment]
Are you able to provide reproduction project for this?

It's not immediately apparent what might be causing this - there's plenty of plugins also that can cause some weirdness with this (as a lot of them "mess" with webpack configs)

**Comment by kmcaloon** [comment]
Thanks @pieh. Unable to provide a realistic reproduction at the moment but will do some troubleshooting and try to put together a minimal repo that replicates the issue.

**Comment by kmcaloon** [comment]
Still need to put together a repo for this. For what it's worth it's definitely an issue with the build cache. If I just delete it after build everything works fine.
