### ISSUE TITLE
gatsby-plugin-google-tagmanager initialize after accept cookies

### ISSUE THREAD

**Issue by AskatDzhambulov** [gatsbyjs/gatsby#20963]
Hey!
I need some help! I m using gatsby-plugin-google-tagmanager plugin. Now this google tag manager is set to cookies automatically when page open, but in my case i need to initialize this google tag manager after i accept cookies, how can i do this ?

`gatsby-config.js`:
```  
plugins: [
    {
      resolve: 'gatsby-plugin-google-tagmanager',
      options: {
        id: 'MY_GOOGLE_TAGMANAGER_ID',

        // Include GTM in development.
        // Defaults to false meaning GTM will only be loaded in production.
        includeInDevelopment: false,

        // datalayer to be set before GTM is loaded
        // should be an object or a function that is executed in the browser
        // Defaults to null
        defaultDataLayer: { platform: 'gatsby' },
      },
    }]
```

**Comment by freiksenet** [comment]
Unfortunately that plugin doesn't support it. You would have to write some custom logic in `gatsby-ssr.js` or in your app code. You can try looking at `gatsby-plugin-google-tagmanager` code for inspiration.

I hope that helps!

**Comment by AskatDzhambulov** [comment]
Thanks!
