### ISSUE TITLE
Onesignal 

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [gatsbyjs/gatsby#20972]
Query, any Onesignal implement with React in Gatsby? if you can give me an example because i don't know how to do it

**Comment by devrchancay** [comment]
This is likely to work for you: https://github.com/c0b41/gatsby-plugin-onesignal

**Comment by FranciscoImanolSuarez** [comment]
From what I saw is a plugin that is installed using NPM, isn't it, if so, is there any kind of documentation?

**Comment by sidharthachatterjee** [comment]
Looks like that plugin is available on npm at https://www.npmjs.com/package/@c0b41/gatsby-plugin-onesignal and doesn't have any documentation. 

In case it doesn't work, you can try creating a source plugin by following the documentation at https://www.gatsbyjs.org/docs/creating-a-source-plugin/

Thanks!
