### ISSUE TITLE
libXtst.so.6 missing on Gatsby Cloud

### ISSUE THREAD

**Issue by hasparus** [gatsbyjs/gatsby#20970]
## Summary

**`libXtst.so.6` seems to be missing on Gatsby Cloud.**

Not sure if I should open an issue, but this may be relevant for other people too.

I'm running puppeteer to screenshot social card images for my blog posts.
Chromium requires some shared objects (libXtst.so.6) to run and they're not there on Gatsby Cloud.
I'm not sure what docker image / OS is used and what can be on user side.

I realize running a headless browser during the build step may be a bit unconventional, so this is more a question than a bug report.

## Relevant information

[Gatsby Cloud Build URL](https://www.gatsbyjs.com/dashboard/c9a9e0f4-a6af-483b-8b56-d58dd90ccd5b/sites/0751622d-8096-4778-a415-d85573b52748/builds/b6ed7952-be7a-4622-808b-c75674336644/details?returnTo=%2Fdashboard%2Fc9a9e0f4-a6af-483b-8b56-d58dd90ccd5b%2Fsites%2F0751622d-8096-4778-a415-d85573b52748%2Fbranches%2Fgatsby-cloud)

> "gatsby-node.js" threw an error while running the onPreInit lifecycle: Failed to launch chrome! /usr/src/app/www/node_modules/puppeteer/.local-chromium/linux-706915/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

![image](https://user-images.githubusercontent.com/15332326/73314825-cb012480-422e-11ea-9450-9b1cd9da2291.png)

### File contents (if changed)

_not sure if relevant, but here you go_

`gatsby-config.js`: https://github.com/hasparus/homepage/blob/master/gatsby-config.js
`package.json`: https://github.com/hasparus/homepage/blob/master/package.json
**`gatsby-node.js`: https://github.com/hasparus/homepage/blob/master/gatsby-node-ts.ts**

interesting parts:
```ts
import puppeteer, { Browser } from "puppeteer";

let browser: Browser;

export async function onPreInit() {
  browser = await puppeteer.launch({
    // Toggle to preview generated images
    headless: true,
  });
}

export async function onPostBuild() {
  await browser.close();
}


async function createSocialImageNodeField({
  node,
  store,
  createNodeId,
  actions: { createNodeField, createNode },
}: CreateMdxNodeArgs) {
  const { program } = store.getState();

  const cacheDir = path.resolve(`${program.directory}/.cache/social/`);
  await fs.ensureDir(cacheDir);

  try {
    const ogImage = await makeSocialCard(
      cacheDir,
      browser,
      (node as unknown) as generated.Mdx
    );

    const ogImageNode = await createFileNode(
      ogImage,
      createNode,
      createNodeId,
      node.id
    );

    createNodeField({
      name: "socialImage___NODE",
      node: (node as unknown) as Node,
      value: ogImageNode.id,
    });
  } catch (e) {
    console.error(e);
  }
}

export const onCreateNode: GatsbyNode["onCreateNode"] = async args => {
  const {
    node,
    getNode,
    actions: { createNodeField },
  } = args;

  if (node.internal.type === "Mdx") {
    //...
    await createSocialImageNodeField({ ...args, node: mdxNode });
  }
};
```
`gatsby-browser.js`: https://github.com/hasparus/homepage/blob/master/gatsby-browser.tsx
`gatsby-ssr.js`: https://github.com/hasparus/homepage/blob/master/gatsby-ssr.js

**Comment by sidharthachatterjee** [comment]
@hasparus Thanks for reporting this! 

I've opened an issue on our internal Gatsby Cloud tracker. 

> I'm not sure what docker image / OS is used and what can be on user side.

We currently run a stripped out linux container and don't support this. I'll keep you posted if we do in the future! 

Let's close this for now. Thank you once again! 💪

**Comment by bruqui** [comment]
FWIW, I'd like to be able to do this too. I guess I could build it locally in static/assets and copy it over or something, but it would be much easier to generate a PDF during the build.

**Comment by phil-lgr** [comment]
This is preventing us from using puppeteer based plugins like https://github.com/remcohaszing/gatsby-remark-mermaid

**Comment by robmarshall** [comment]
I would also like to be able to use this feature.

**Comment by f-kottek** [comment]
@phil-lgr, @robmarshall  and everybody else trying to get Mermaid to work on Gatsby-Cloud:

I came up with an ugly, but feasible workaround that'll let you at least incorporate graphs until this issue gets resolved. 

1. install and configure the [mermaid plugin](https://www.gatsbyjs.com/plugins/gatsby-remark-mermaid/) like it says.
2. add a mermaid graph to your MD-content piece and render the site locally. (If this also doesnt work, there are more underlying issues with your project)
3. open your locally built site in your browser
4. inspect your site with the dev-tools of your browser, go to the graphic and select+copy the whole <div> with the class "mermaid" that capsules the svg 
5. use some online HTML to JSX tool, to convert your copied HTML to JSX
6. in your repo, create a react-component and put your resulting JSX in
7. use the component inside your MD-content like you would use any other JSX-component inside MDX. (If you have not used components inside MD-content before, the Gatsby docs about this are quite plentiful) 

Hope this helps to get you along until puppeteer (and the mermaid remark plugin) are usable in Gatsby Cloud.
