### ISSUE TITLE
Starter processing Square payments

### ISSUE THREAD

**Issue by AishaBlake** [gatsbyjs/gatsby#20975]
## Summary

In attempting to write a reference guide for processing payments with Square, I realized we could use a starter to help people do this without quite as much digging into the Square documentation and adapting of available examples.

### Motivation

Square is a solid choice for people who are just starting a business because they don't charge a monthly fee for their basic service. Right now, there's no starter that people can use to get up and go and the existing plugin is pretty minimal.

### Build the starter

- Potentially helpful resources:
  - [`SqPaymentForm` documentation](https://developer.squareup.com/docs/api/paymentform#navsection-paymentform)
  - [Square's tutorial for online payment options](https://developer.squareup.com/docs/online-payment-options)
  - Square's blog post on [Online Payments with React + Square](https://developer.squareup.com/blog/online-payments-form-react/)
- [ ] Read through the contributing [docs on contributing code](https://www.gatsbyjs.org/contributing/code-contributions/)
- [ ] Make sure your starter is [accessible](https://www.gatsbyjs.org/docs/making-your-site-accessible/)
- [ ] Include a README file

### Open a pull request to add it to the Starter Library

- [ ] Read through the [docs on adding to the Starter Library](https://www.gatsbyjs.org/contributing/submit-to-starter-library/)
- [ ] Open a pull request with your work including the words "Fixes #20975" in the pull request description

**Comment by jonniebigodes** [comment]
@AishaBlake is this time sensitive? if not i can start going over this during the weekend and report back when i have something more concrete. Also once #20977 goes through it would help out immensely

**Comment by AishaBlake** [comment]
@jonniebigodes, this isn't super time-sensitive. (I'd also _love_ any feedback on that guide as you go through this.) The team will be occupied with Gatsby Days and Gatsby Gathering next week, so my response time will be a bit slower, FYI.

**Comment by AishaBlake** [comment]
@jonniebigodes I'm assuming you're still working on this based on your comments on my docs PR. How is it going?

**Comment by jonniebigodes** [comment]
@AishaBlake it's almost done. I have the starter almost ready i'm currently working out some quirks with the starter and issues with the production build. As soon as i'm able to solve them i'll make the repo public and make the pr. Sounds good?
