### ISSUE TITLE
Add how to style remark-autolink-headers anchor icon

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#20982]
## Summary
It's unclear how to style the SVG that is generated by https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/. This was raised on https://github.com/gatsbyjs/gatsby/pull/20968.

We should add a small section to the readme that explains how to do this with css.

### Motivation

Users who use the gatsby-remark-autolink-headers plugin.

## Steps to resolve this issue

Edit [Readme.md of gatsby-remark-autolink-headers](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-autolink-headers/README.md) and add a section how to style the anchor svg

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by akshitkrnagpal** [comment]
Hey 
Are you working on this? @keplersj
Can I work this? @wardpeet

**Comment by Lundbyit** [comment]
Hi can I give this one a try?

**Comment by wardpeet** [comment]
Definitely! This will style the svg
````
You can add currentColor with the following css
```
a.anchor {
  fill: currentColor
}
```

Or if you want to only target the svg (note that the first selector is faster than the one below but that's micro optimisations)
```
a.anchor > svg
```
````

**Comment by Lundbyit** [comment]
Thanks :)
