### ISSUE TITLE
Error re graphql and contentful

### ISSUE THREAD

**Issue by esentai8** [gatsbyjs/gatsby#20983]
When attempting to run the server in development mode I get this error:

`Cannot query field "allContentfulBlogPost" on type "Query".
`
This error occurred immediately after I tried to wire up relation with contentful in order to dynamically create blogposts.

Now this causes problem with webpack. Here is the additional message I am seeing.

> ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

C:\Users\feat\Documents\Personal\node-course\gatsby-bootcamp\src\pages\blog.js
  11:7  error  Cannot query field "allContentfulBlogPost" on type "Query". Did you mean "allContentfulAsset", "contentfulAsset", or "allContentfulContentType"?  graphql/templa
te-strings

✖ 1 problem (1 error, 0 warnings)
 
Instead of my website I am now seeing white scree

**Comment by pieh** [comment]
Do you have any content in your contentful space?

Right now by default we infer types from data, so if you: a) either don't have "ContentfulBlogPost" type or b) don't have any entries of that type in your contentful space, then we won't be able to build schema for it and you will get graphql errors like that

**Comment by esentai8** [comment]
Thank you pieh for a quick response. Yes I do have content of contentfulBlogPost. In addition to that I searched for similar errors and found that uploading a media file in contentful (even if I don't use it) might help to resolve the issue, however this was not helpful so far.

**Comment by vladar** [comment]
Also, can you paste `gatsby build` output? It may be useful to see contentful fetching/sourcing messages.

**Comment by esentai8** [comment]
Hello Vladimir. I just have resolved this issue. I am not sure why but for some reasons deleting the .cache and running the server again helped to fix the problem. Thank you and your colleagues for taking time to review my request
