### ISSUE TITLE
Standardize `gatsby-starter-blog` components and functions

### ISSUE THREAD

**Issue by nicolasrouanne** [gatsbyjs/gatsby#20985]
I've been using Gatsby recently to teach _React_ to beginners, especially [`gatsby-starter-blog`](https://github.com/gatsbyjs/gatsby-starter-blog). I find they are often confused by React's possibility to use both _Function_ and _Class_ components. Same goes for _classic_ functions vs _arrow_ functions.

Both are used indifferently in `gatsby-starter-blog`; I would like to suggest using only one kind. I totally agree it's a matter of personal preference. IMO I find it simpler to use and to teach.

My suggestions:
- replace all _Class_ components by _Function_ components (e.g. [here](https://github.com/gatsbyjs/gatsby-starter-blog/blob/686783b0f0eaca06d240d275576eb24031c2d30d/src/templates/blog-post.js#L9))
- replace all _classic_ functions by _arrow_ functions (e.g. [here](https://github.com/gatsbyjs/gatsby-starter-blog/blob/c67ba4e511635dd52e4e634f9d4487b4d7f9b799/src/components/seo.js#L13))

Let me know what you think, as I got a PR ready, but first wanted your feedback first.

**Comment by vladar** [comment]
Thank you for opening this, @nicolasrouanne 

It makes sense to me and it also seems to be in line with our tutorials, so feel free to send a PR! Hopefully, it will make it easier to teach Gatsby! 💜

**Comment by Strangehill** [comment]
I'm glad that we changed our mind on changing class components to function components.

Some work duplication could have been avoided if the following pre-existing PRs had been taken into account:
- [#12218](https://github.com/gatsbyjs/gatsby/pull/12218) 
- [#14920](https://github.com/gatsbyjs/gatsby/pull/14920)
- [#17142](https://github.com/gatsbyjs/gatsby/pull/17142)
