### ISSUE TITLE
[gatsby-source-contentful] No way to link to non-image local asset when `downloadLocal` enabled

### ISSUE THREAD

**Issue by mjmaurer** [gatsbyjs/gatsby#20999]
## Description

I have a PDF as a Contentful asset and `downloadLocal` enabled. With images, `downloadLocal` works fine as childImageSharp will link to `/static/...` for `src`. 

For a query like: 

 ```
 contentfulAsset(title: {eq: "some-pdf"}) {
    localFile {
      absolutePath
      relativePath
      url
      relativeDirectory
    }
  }
```
none of the paths link to somewhere in `/static/`, so I'm not sure if there is even a way to do this right now. Instead, everything links to the CDN or somewhere in `/cache/`

### Steps to reproduce

1. Contentful + Gatsby project
2. Add a PDF as an 'Asset'
3. Attempt query above after running 'gatsby develop'

### Expected result

One url at least should link through `/static/`. (Preferably all IMO, doesn't cache just exist to move to /static/?)

### Actual result

None link through /static/

### Environment

  System:
    OS: Linux 4.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  npmPackages:
    gatsby: ^2.17.4 => 2.18.10
    gatsby-image: ^2.2.30 => 2.2.36
    gatsby-plugin-emotion: ^4.1.18 => 4.1.18
    gatsby-plugin-glamor: ^2.1.13 => 2.1.18
    gatsby-plugin-manifest: ^2.2.23 => 2.2.33
    gatsby-plugin-modal-routing: ^1.1.0 => 1.1.0
    gatsby-plugin-offline: ^3.0.17 => 3.0.29
    gatsby-plugin-postcss: ^2.1.16 => 2.1.18
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.18
    gatsby-plugin-resolve-src: ^2.0.0 => 2.0.0
    gatsby-plugin-sharp: ^2.2.32 => 2.3.7
    gatsby-plugin-typography: ^2.3.15 => 2.3.20
    gatsby-source-contentful: ^2.1.73 => 2.1.73
    gatsby-source-filesystem: ^2.1.33 => 2.1.42
    gatsby-transformer-json: ^2.2.16 => 2.2.22
    gatsby-transformer-sharp: ^2.3.0 => 2.3.9
  npmGlobalPackages:
    gatsby-cli: 2.8.18

**Comment by mjmaurer** [comment]
Happy to work on this btw. Probably best to add another field under 'localfile' so it's not a breaking change. Maybe something like `localUrl`?

**Comment by LekoArts** [comment]
Thank you for opening this!

Try adding `gatsby-source-filesystem` and point it to somewhere, e.g. your `src/pages` directory. After configuring the plugin correctly you should see a `publicURL` field on your asset. Hope that helps!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by mjmaurer** [comment]
Thanks for the suggestion. Looks like what I need is [createRemoteFileNode](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createremotefilenode). 

To be clear though, the PDF is not local at build time (it's hosted by Contentful). Even with the contentful plugin and `downloadLocal` enabled, there is no way to get a local file link to a non-image asset. Since this feature exists for images, this should be a feature request. `createRemoteFileNode` should be unnecessary if you have the Contentful plugin installed and `downloadLocal` enabled.

**Comment by LekoArts** [comment]
Have you tried my suggestion about `publicURL` ?

**Comment by mjmaurer** [comment]
Ahh I see now! Thanks!

`gatsby-source-filesystem` actually adds the `publicURL` field to the `localFile` node wherever it exists.

**Comment by mjmaurer** [comment]
I think this behavior is a bit opaque (I have `gatsby-source-filesystem` pointing at `src/pages` even though there isn't static data there). I don't have any suggestion though
