### ISSUE TITLE
Improve .env.* usage

### ISSUE THREAD

**Issue by blainekasten** [gatsbyjs/gatsby#21004]
## Summary

Our current setup with `.env.development` and `.env.production` has some limitations.

- First it is [confusing](https://github.com/gatsbyjs/gatsby/issues/20646#issuecomment-575518340) that command line variables must be prefixed with `GATSBY_` to end up in the client bundle while the `.env` files do not have this rule.
- Secondly we have had [security issues with hacky patches](https://github.com/gatsbyjs/gatsby/issues/10021#issuecomment-439944662) to fix the fact that `.env` files are used for both server and client development.
- Third loading `.env` files for server development requires the users to load them in user code.

### Basic example

From a conversation with @pieh [here](https://gatsbyjs.slack.com/archives/CA1GW1HNU/p1580227588036500) (sorry its a slack conversation), we think it would be good to make the following changes.

1. Deprecate and remove the basic `.env.(dev|prod)` files
1. Replace with `.env.node.(dev|prod)` that would hold node only variables that would get loaded for node runtime
1. Replace with `.env.browser.(dev|prod)` that would hold only variables that should be exposed to the browser. In addition this file would require all variables be prefixed by `GATSBY_` to remain consistent.

### Motivation

The motivation is to allow our APIs to remain clear and prevent security holes.

**Comment by muescha** [comment]
there was also a confusion between .dev and .prod:

#19388 Gatsby automatically loading dotenv in an undocumented way

i think the arguments there can also goes into consideration ...
