### ISSUE TITLE
[gatsby-source-lever] Does not support `createNodeField`

### ISSUE THREAD

**Issue by iDVB** [gatsbyjs/gatsby#21009]
## Description

The `gatsby-source-lever` source does not support adding custom fields with `gatsby-node.js` and `createNodeField`.

### Steps to reproduce
Go to codesandbox example:
https://codesandbox.io/s/gatsby-source-lever-bug-5n2op

Make this GraphiQL call which **WORKS**:
```javascript
query MyQuery {
  allSitePage {
    nodes {
      fields {
        slug
      }
      id
    }
  }
}
```

Then make this GraphiQL call which **FAILS**:
```javascript
query MyQuery {
  allLever {
    nodes {
      lever_id
      text
      description
      fields {
        slug
      }
    }
  }
}
```

**Additional Test:**
Make this GraphiQL call which also **WORKS**:
```javascript
query MyQuery {
  allHnStory {
    nodes {
      fields {
        slug
      }
      title
    }
  }
}
```

### Expected result

Custom Node field `node.fields.slug` should be added to ALL nodes.

### Actual result

Custom Node field `node.fields.slug` is NOT added to `lever` nodes which are part of the `gatsby-source-lever` plugin

### Environment

 System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-source-lever: 2.1.24 => 2.1.24

**Comment by Js-Brecht** [comment]
I kind of wonder if this has to do with the usage of [`createSchemaCustomization`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-lever/src/gatsby-node.js#L6-L35).  According to [the docs](https://www.gatsbyjs.org/docs/node-apis/#createSchemaCustomization), that API endpoint runs immediately before schema generation.  Perhaps it is overriding the adjustment you made during `onCreateNode`.

I'm not actually familiar with `createSchemaCustomization`, so I couldn't say for sure.  Just a thought.

**Comment by Js-Brecht** [comment]
Well, maybe it's not quite as direct as that.  `gatsby-source-hacker-news` uses the same endpoint.  However, they do differ in that `gatsby-source-lever` uses the `@dontinfer` directive.

`gatsby-source-hacker-news`:
```js
    type HNStory implements Node {
      title: String
      score: Int
      timeISO: Date! @dateformat
      url: String
      by: String!
      descendants: Int
      content: String!
      domain: String
      order: Int!
    }
```

`gatsby-source-lever`:
```js
    type lever implements Node @dontInfer {
      additional: String
      additionalPlain: String
      applyUrl: String
      createdAt: Date @dateformat
      description: String
      descriptionPlain: String
      hostedUrl: String
      lever_id: String
      text: String
      categories: leverCategories
      lists: [leverList]
    }
```

**Comment by iDVB** [comment]
Thanks @Js-Brecht. 
I found that the issue was that the package's [typeDefs](https://github.com/gatsbyjs/gatsby/blob/dd96604b91227a281df279626ae0d34002d89436/packages/gatsby-source-lever/src/gatsby-node.js#L8) we're opting out of [inference](https://www.gatsbyjs.org/docs/schema-customization/#opting-out-of-type-inference) with `dontInfer`. 

Removing it fixed the issue. I created a PR https://github.com/gatsbyjs/gatsby/pull/21017
