### ISSUE TITLE
[gatsby-plugin-netlify-cms] Multiple git branches support

### ISSUE THREAD

**Issue by tristanMatthias** [gatsbyjs/gatsby#21011]
# Summary

I would like to be able to configure what git branch my Netlify CMS instance uses. Currently, I have not found any way to pass in environment variables from Gatsby to Netlify (attempted webpack configs)

### Motivation

This allows us to deploy to multiple environments and the content is linked to the current environment, not the one setting for all.

**Comment by deriegle** [comment]
It looks like this is probably a limitation on the Netlify side of things and not Gatsby.

According to [this section](https://www.netlifycms.org/docs/authentication-backends/#options) in their docs which gives you all the options that you can set in your `config.yml` file,  Netlify currently only supports a single git branch.

**Comment by tristanMatthias** [comment]
Yeah, that's what I was afraid of. Ok, thanks @deriegle
