### ISSUE TITLE
GraphQl Data not showing up in "build", but showing in "develop"

### ISSUE THREAD

**Issue by alex-nicaise** [gatsbyjs/gatsby#21013]
## Description

Hello,

I have a netlify build of my site [here](https://boring-wilson-2d2823.netlify.com/).

As you can see under the "SOS Meetings in New York State" section, some meetings do not contain a location (in grey text) like the others. I'm confused why this is happening, because in the development bundle, this works fine and all the data shows up as it should. However, after netlify triggers the build action, this data disappears, and I cannot figure out why.

### Steps to reproduce

You can find the source code for the development build in [my github repo](https://github.com/alex-nicaise/sos-nys). Clone the repo, then "gatsby develop" to see how the development bundle looks.

Then, head over to the live netlify build, and see that data is missing.

If anyone can point me in the right direction, that would be extremely appreciated.

### Environment

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE 
    Yarn: 1.17.3 - ~\AppData\Roaming\npm\yarn.CMD    
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD    
  Languages:
    Python: 2.7.17 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.1 => 2.19.1
    gatsby-image: ^2.2.8 => 2.2.8
    gatsby-plugin-manifest: ^2.2.5 => 2.2.5
    gatsby-plugin-offline: ^2.2.5 => 2.2.5
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sharp: ^2.2.11 => 2.2.11
    gatsby-source-filesystem: ^2.1.9 => 2.1.9
    gatsby-source-graphql: ^2.1.17 => 2.1.17
    gatsby-transformer-sharp: ^2.2.6 => 2.2.6

**Comment by marcysutton** [comment]
Here's a suggestion, try running `gatsby build && gatsby serve` locally so you can investigate the data layer in your built site before deploying to Netlify. Do you get any errors?

**Comment by jonniebigodes** [comment]
@marcysutton i think you meant to say `gatsby develop` and open up `http://localhost:8000/__graphql` as the combination of those two commands and the said url is opened then a error will pop up, more specifically a 404 page

**Comment by alex-nicaise** [comment]
@marcysutton @jonniebigodes i have tried locally doing gatsby buid & serve, the same error still occurs. I'm not sure what's wrong, I've checked the wordpress posts backend - that's okay; I've double checked the way I call the hooks in - seems okay. Just really confused at this point.

You can also inspect the title of each post, it should be displaying as `<p class="my-5"<strong>{{content}}</strong></p>` but some are displaying without the `my-5`. Which is confusing me even more.

**Comment by alex-nicaise** [comment]
This is fixed. There was a problem with the way the returned HTML was written.

**Comment by jonniebigodes** [comment]
@alex-nicaise glad to know that you managed to solve it...i was just finishing cloning the repo and check your issue. But it's great that you managed to solve it.
