### ISSUE TITLE
Question about Google Analytics code insert

### ISSUE THREAD

**Issue by zhandosweb** [gatsbyjs/gatsby#21016]
Hello!

Please, tell me. If I want to insert Google Analytics code to my site, then I should use [Google Analytics Plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/?=google%20analytics), or create a custom component? 

Why I can't just insert Google Analytics code to header.js, or footer.js component? This is isn't work? For example, on simple HTML-sites (Jekyll or Wordpress) I just insert Google Analytics code to before `</body>` close tag, and it's enough.

Sorry for the noob question, I'm still learning Javascript + React..

**Comment by connorlindsey** [comment]
Use the google analytics plugin with your tracking id. When your gatsby site is built, the plugin will automatically insert the tag into your HTML.

**Comment by zhandosweb** [comment]
> Use the google analytics plugin with your tracking id. When your gatsby site is built, the plugin will automatically insert the tag into your HTML.

Thank you for your answer. But I'm living in Kazakhstan, and do SEO sites in Russia. And what, if I want to add Yandex Metrika code? It's a Google Analytics alternative from Russia.

Also in the future, I want to add Google Adsense, Yandex Ads, and other ad platforms code. For all of this, I should create custom components?  

Why I can't just insert Google Analytics code to the footer.js component? (before `</body>` tag?)

**Comment by marcysutton** [comment]
The plugin is an abstraction to make working with Google Analytics easier to control from a gatsby-config without having to go deep into other files. But that makes sense why you'd want to have more fine-grained control over it: you could insert it yourself by creating an html.js file: https://www.gatsbyjs.org/docs/custom-html/

**Comment by zhandosweb** [comment]
> The plugin is an abstraction to make working with Google Analytics easier to control from a gatsby-config without having to go deep into other files. But that makes sense why you'd want to have more fine-grained control over it: you could insert it yourself by creating an html.js file: https://www.gatsbyjs.org/docs/custom-html/

Thank you very much for your answer! Html.js is solution for my case. 

And great blog: https://marcysutton.com/, I subscribed :)

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
