### ISSUE TITLE
gatsby-dev-cli: how to remove the installed plugins

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#21027]
### Summary

describe better the removal of changes when not use `gatsby-dev` anymore

### Steps to replay this issue

- i installed gatsby-dev-cli
- i used it to run `gatsby-dev` or the `gatsby-dev --packages`
- now i run again `yarn install`
- but the changed files still stay there (my `console.log`s are still there)

### Draft the doc

add it to the gatsby-dev-cli docs

**Comment by sidharthachatterjee** [comment]
Unfortunately, the only fool proof way to really revert changes from `gatsby-dev-cli` is to `rm -rf node_modules` at the moment 

Feel free to open a PR adding that to the `README`. Thanks!

**Comment by muescha** [comment]
reminder to me: PR to update the docs

**Comment by wardpeet** [comment]
@muescha `git checkout package.json; npm install --force` or `git checkout package.json; yarn --force` should work

**Comment by muescha** [comment]
i will update the docs

makes it sense to have it as a `gatsby-dev` sub command?
