### ISSUE TITLE
Custom page URL

### ISSUE THREAD

**Issue by glauberfc** [gatsbyjs/gatsby#21028]
## Relevant information

I have a page on my Gatsby website w/ name profile, but I want to customize the url to **profile/some-string**. I want to open the profile page w/ this custom url and could read the string after the bar. I already tried to do this manually w/ reach router, but it not worked.

There is a way to do this?

### Environment (if relevant)

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7 
    gatsby-image: ^2.2.39 => 2.2.39 
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39 
    gatsby-plugin-modal-routing: ^1.1.0 => 1.1.0 
    gatsby-plugin-offline: ^3.0.32 => 3.0.32 
    gatsby-plugin-postcss: ^2.1.19 => 2.1.19 
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.21 
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3 
    gatsby-source-filesystem: ^2.1.46 => 2.1.46 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by deriegle** [comment]
[Looks like this comment could help you](https://github.com/gatsbyjs/gatsby/issues/1171#issuecomment-446171714)

Here is a sample that you could add to your `gatsby-node.js` file to make this work for your use case.

```js
// called after every page is created.
exports.onCreatePage = ({ page, actions }) => {
  const { createPage } = actions
  // Make the front page match everything client side.
  // Normally your paths should be a bit more judicious.
  if (page.path === `/profile`) {
    page.matchPath = `/*`
    createPage(page)
  }
}
```

**Comment by glauberfc** [comment]
Thanks @deriegle!

**Comment by deriegle** [comment]
You're welcome! I think you will. I am not 100% sure, but it seems like you'll need to rebuild everytime you make a change on the server. It depends if the plugin actually listens for changes on the server, the documentation for the AppSync plugin doesn't say anything about that.
