### ISSUE TITLE
Related Blog Posts

### ISSUE THREAD

**Issue by theiliad** [gatsbyjs/gatsby#2102]
Not too savvy with GraphQL yet, but gonna look into this.

In the meantime, does anybody have a previous solution they used to achieve this?

**Comment by markmichon** [comment]
I haven't done this personally on a gatsby site, but I know in the past the easiest solution is generally to match categories.

You should be able to capture the category from your current page, and run a query on the current category.
Something like...

```js
{
  allMarkdownRemark(filter: { frontmatter: {categories: {eq: "development"  }}} ) {
    edges {
      node {
        id
      }
    }
  }
}
```
Subbing in the string "development" for whatever your current category is. I suspect you could run this at the same time that you run the page creation or in one of the templates itself.

**Comment by theiliad** [comment]
Good idea. I think using tags will also help.

Thanks.

**Comment by muhajirdev** [comment]
In someone wanted to rank related pages by tags.
http://github.com/muhajirdev/related-pages
