### ISSUE TITLE
Markdown image not showing

### ISSUE THREAD

**Issue by Olanetsoft** [gatsbyjs/gatsby#21038]
## Description

image not showing in the markdown file

{
			resolve: `gatsby-transformer-remark`,
			options: {
				plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
                maxWidth: 590
            },
          },
					`gatsby-remark-prismjs`,
					`gatsby-remark-smartypants`,
          `gatsby-remark-copy-linked-files`,
          
				]
			}
		},
### Steps to reproduce

link to repository
https://github.com/Olanetsoft/my-site

### Expected result

Image is meant to show up in markdown

![imageError](https://user-images.githubusercontent.com/45847909/73436211-633ffc00-434a-11ea-8cb0-df7244efe1f0.PNG)

**Comment by freiksenet** [comment]
Hi!

In your config, you have declared two `gatsby-transformer-remark` and only the latter is used. You should combine their config together in plugin and then the images would show correctly.

Thank you for using Gatsby and feel free to open new issue if you have further questions!

**Comment by Olanetsoft** [comment]
Oh my goodness it worked like magic.
thank you @freiksenet
