### ISSUE TITLE
Sorting of markdown-pages is incorrect

### ISSUE THREAD

**Issue by andreasnett** [gatsbyjs/gatsby#21043]
## Description

Describe the issue that you're seeing.

As specified in the tutorial I added the line of code `(sort: { order: DESC, fields: [frontmatter___date] })` to the allMarkdownRemark to sort the md files by frontmatter date. However, this sorting is incorrect. It gives a different sorting than not having it there, and order ASC gives the opposite of DESC, but for some reason a few files that is dated back to 2018 is put in front of files dated 2019. And one of the 2019 posts is back with the rest of the 2018 posts.

My .md-frontmatter looks like this

`layout: blog
title: <>
path: <>
descriptiveText: <>
date: 06.06.2018
thumbnail: ../images/IMG_4967-min.jpg
author: <>`
(remove <> for real info)
However the sorting seems pretty much random. The graphql query looks like this 
`
export const mdQuery = graphql'
  {
    allMarkdownRemark(sort: { order: DESC, fields: [frontmatter___date] }) {
      edges {
        node {
          frontmatter {
            date
            thumbnail {
              childImageSharp {
                fluid {
                  src
                }
              }
            }
            title
            author
            descriptiveText
            path
          }
        }
      }
    }
  }
'`

### Steps to reproduce

Create blog
Create blog posts that are dated earlier than they are posted (but posted in the same order as they are dated)
Sort with GraphQL

### Environment

GatsbyJS app with .md-blog and graphql queries. Running locally with gatsby develop. Netlify CMS and Chrome browser. 

Run `gatsby info --clipboard` in your project directory and paste the output here.
  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-catch-links: ^2.1.24 => 2.1.24
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-netlify-cms: ^4.1.37 => 4.1.37
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5
    gatsby-plugin-typescript: ^2.1.26 => 2.1.26
    gatsby-remark-images: ^3.1.42 => 3.1.42
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-transformer-remark: ^2.6.48 => 2.6.48
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7

**Comment by freiksenet** [comment]
Hi!

`06.06.2018` is not a valid Gatsby date format, thus it's interpreted and sorted as string. It will work correctly if you use eg `2018-06-06`.

**Comment by andreasnett** [comment]
How might I change the date formats of all my files efficiently?

**Comment by andreasnett** [comment]
@freiksenet

**Comment by iamaakashbasnet** [comment]
@andreasnett It should be in YYYY-MM-DD.
