### ISSUE TITLE
Query data in Pages (class component)

### ISSUE THREAD

**Issue by vavra7** [gatsbyjs/gatsby#21042]
I walked through [documentation](https://www.gatsbyjs.org/docs/page-query/) and all examples are using function components. However I need to use graphql query on page using **class component**. But using class component, there are no queried data available in props. I didn't find single mention that graphql is supposed to work only in function component.

Is it a bug, or it is not supported in class component or I just don't know how? Eventually, can you please provide how to access queried data in page using class component?

**Comment by Fatme** [comment]
Hey @vavra7,

Most probably you can access them using `this.props.data`.

**Comment by vavra7** [comment]
Hi @Fatme, you are right.
I made several attempts and did mistake. I considered my [client-only route](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/) as a page but it appears that on this type of pages, page graphql query unfortunately can not be used  at all.

Thank you for you answer.
