### ISSUE TITLE
Gatsby Config Validation Fails When Proxy is an Array (expects object)

### ISSUE THREAD

**Issue by dubble-G** [gatsbyjs/gatsby#21055]
## Description

gatsby develop fails due to validation error.  I have an array of proxies, but proxy is expected to be an object.

### Steps to reproduce

I have multiple endpoints that I wish to proxy.  I used the following Gatsby documentation:

https://www.gatsbyjs.org/docs/api-proxy/  to configure. Note the proxy docs indicate that proxy can be an array.

### Expected result

According to the example in the docs, I should be able to set proxy to an array.  Here is the example straight out of the docs:

`proxy: [
    {
      prefix: "/api",
      url: "http://dev-mysite.com",
    },
    {
      prefix: "/api2",
      url: "http://dev2-mysite.com",
    },
  ],`

### Actual result

I get error when running gatsby develop:

The site's gatsby-config.js failed validation
ValidationError: child "proxy" fails because ["proxy" must be an object]
⠋ open and validate gatsby-configs

Is the documentation out of date, and if so, what is the proper way to configure multiple proxies?

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 52.57s. - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.15.5 => 2.18.6 
    gatsby-image: ^2.2.16 => 2.2.34 
    gatsby-node-helpers: ^0.3.0 => 0.3.0 
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.2.13 => 2.2.31 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.6 => 3.1.16 
    gatsby-plugin-sharp: ^2.2.19 => 2.3.5 
    gatsby-remark-images: ^3.1.38 => 3.1.38 
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3 
    gatsby-source-filesystem: ^2.1.19 => 2.1.40 
    gatsby-source-instagram: ^0.5.1 => 0.5.1 
    gatsby-source-youtube: ^1.0.1 => 1.0.1 
    gatsby-transformer-remark: ^2.6.38 => 2.6.39 
    gatsby-transformer-sharp: ^2.2.13 => 2.3.6 
  npmGlobalPackages:
    gatsby-cli: 2.8.11

**Comment by sidharthachatterjee** [comment]
That's odd. Multiple proxies should work when passed in as an Array. The validation happens in packages/gatsby/src/joi-schemas/joi.js and the key is rightly set to an Array. 

The documentation is correct as well. Let me try this out myself.

**Comment by nileshbhingaradiya** [comment]
i am also trying this but getting some unexpected error of Reducers

> UNHANDLED REJECTION Reducers may not dispatch actions.
  Error: Reducers may not dispatch actions.

`module.exports = {
  proxy: [
    {
      prefix: "/api",
      url: "http://dev-mysite.com",
    },
    {
      prefix: "/api2",
      url: "http://dev2-mysite.com",
    },
  ],
}`


if I remove array and make the object it will work fine  

`module.exports = {
  proxy: 
    {
      prefix: "/api",
      url: "http://dev-mysite.com",
    }
},`
