### ISSUE TITLE
Redirecting pages

### ISSUE THREAD

**Issue by attfarhan** [gatsbyjs/gatsby#2105]
What's the recommended way to redirect pages?  For example, if i want https://example.com/foo to redirect to https://example.com/foo/bar/, what's the best way to do this?

**Comment by pierrenel** [comment]
My vote would be that it hinges on what you're using to server the public folder - apache / nginx / express have their own redirect mechanisms built in?

**Comment by KyleAMathews** [comment]
This is still WIP but yeah, like @pierrenel said we want to leverage the host you're on. So you'd install a plugin for the host you're using and it would write out redirect instructions for the web server. See this discussion for more https://github.com/gatsbyjs/gatsby/pull/1068 lemme know if you want to tackle writing the PR!

**Comment by attfarhan** [comment]
Great, thanks!
