### ISSUE TITLE
[docs] stub: Adding Search with Elasticlunr

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21066]
## Summary

Write the article for [Adding Search with elasticlunr](https://www.gatsbyjs.org/docs/adding-search-with-elasticlunr/)

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by kunxi** [comment]
I am interested in contributing the document.

I have tried the [Lunr](https://lunrjs.com) integration in this [blog post](https://www.kunxi.org/2020/02/adding-search-to-gatsby-via-lunrjs/). 

It looks like the elasticlunr is no longer actively maintained, do you think integration lunrjs is acceptable option?

**Comment by duffn** [comment]
We could have both Lunrjs and Elasticlunr or are they too similar? This fork of Elasticlunr is maintained and functioning. https://github.com/gatsby-contrib/gatsby-plugin-elasticlunr-search

**Comment by marcysutton** [comment]
We would love to have your contribution @kunxi, are you still interested in working on a doc about search with Lunr / Elasticlunr? I haven't worked with those tools before, what are the differences? Could a single doc mention both libraries to help users understand their options?

**Comment by kunxi** [comment]
Yes, I'd like to contribute.

I have a blog post about the Lunrjs:
https://www.kunxi.org/2020/02/adding-search-to-gatsby-via-lunrjs/.
<https://www.kunxi.org/2020/02/adding-search-to-gatsby-via-lunrjs/>

Can you leave some feedback for the gap between the blog post to the
document?

Thanks,
Kun

**Comment by ehrencrona** [comment]
Elasticlunr is apparently a reimplementation of lunr that's supposed to give some more features and a smaller index size.

But: Elasticlunr doesn't seem to be in active development; there has hardly been any [commits](https://github.com/weixsong/elasticlunr.js/commits/master) for the last year.

Furthermore, the [npm downloads for Lunr](https://www.npmjs.com/package/lunr) are about 30 times [those of Elasticlunr](https://www.npmjs.com/package/elasticlunr) so I'd say it would make sense to jump horses to lunr.
