### ISSUE TITLE
[docs] stub: Maintaining a Plugin

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21067]
##  Summary

Write the article for [Maintaining a Plugin](https://www.gatsbyjs.org/docs/maintaining-a-plugin/)

**Comment by gillkyle** [comment]
Related to some evaluation material written up in #20232, I'll remove that from my issue there so it can be handled by this issue when @Ekwuno works on it 🙂

**Comment by gillkyle** [comment]
This was addressed by @Ekwuno's PR: #21221
