### ISSUE TITLE
[docs] stub: Gatsby for Freelancers

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21069]
## Summary

Write the article for [Gatsby for Freelancers](https://www.gatsbyjs.org/docs/gatsby-for-freelancers/).

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by ng29** [comment]
Hiya @tesseralis  / @marcysutton 

Can i pick this up if available for grabs? 

Cheers
