### ISSUE TITLE
Unable to setup Google Analytics

### ISSUE THREAD

**Issue by ajayns** [gatsbyjs/gatsby#21074]
## Description

I'm unable to setup Google Analytics on my Gatsby site. I've used 3 different approaches and all of them failed to send any data to GA. 

1. `gatsby-plugin-google-analytics` based on the plugin documentation
2. `gatsby-plugin-gtag` tried this as Google seems to be pushing for gtag instead of analytics code.
3. Manually placing code snippet for analytics in Helmet:
```
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxxx"></script>
 <script type="application/ld+json">
    {`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('config', 'UA-xxxx');
    `}
</script>
```

I've used production builds to test, so that isn't a problem too. Even more confusing is that inspecting the site, I can find the code being injected to the HTML yet no results.

### Steps to reproduce

Use one of the methods used above and production build. 

gatsby-config.js
```
const path = require('path');

module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: 'UA-xxxx',
        head: true,
        anonymize: true,
        respectDNT: true,
      },
    },
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-transition-link`,
    {
      resolve: `gatsby-plugin-svgr`,
      options: {
        svgoConfig: {
          plugins: {
            removeViewBox: false,
          },
        },
      },
    },
    `gatsby-plugin-styled-components`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `misc`,
        path: `${__dirname}/src/images/misc`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `works`,
        path: `${__dirname}/src/images/works`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `exp`,
        path: `${__dirname}/src/images/explorations`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
       ....
      },
    },
    `gatsby-plugin-offline`,
    {
      resolve: `gatsby-plugin-google-fonts`,
      options: {
        fonts: [`didact gothic`, `raleway\:600`],
      },
    },
    {
      resolve: `gatsby-plugin-alias-imports`,
      options: {
        alias: {
          ....
        },
      },
    },
  ],
};

```

### Expected result

GA should work realtime as expected

### Actual result

No data sent to GA.

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 69.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.19.0 => 2.19.0 
    gatsby-image: ^2.2.39 => 2.2.39 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-google-analytics: ^2.1.34 => 2.1.34 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-gtag: ^1.0.12 => 1.0.12 
    gatsby-plugin-manifest: ^2.2.37 => 2.2.37 
    gatsby-plugin-offline: ^3.0.33 => 3.0.33 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21 
    gatsby-plugin-sharp: ^2.4.0 => 2.4.0 
    gatsby-plugin-styled-components: ^3.1.18 => 3.1.18 
    gatsby-plugin-svgr: 2.0.1 => 2.0.1 
    gatsby-plugin-transition-link: ^1.17.7 => 1.17.7 
    gatsby-source-filesystem: ^2.1.46 => 2.1.46 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13 
  npmGlobalPackages:
    gatsby-cli: 2.8.4
```

**Comment by Olanetsoft** [comment]
Oh sorry for that. Are you running the site locally? if yes you need to run the command:

gatsby develop && gatsby serve

or

npm run build && npm run serve

**Comment by ajayns** [comment]
> I've used production builds to test, so that isn't a problem too.

@Olanetsoft nope already doing that.

**Comment by AkashRajpurohit** [comment]
The plugin configuration seems fine to me `other than I have just added the trackingId and head : true` as I am also using google analytics on my website and able to get realtime updates.
Can you check on your google analytics dashboard if there is any issue with that.

Or use the current tag on some other website to check if you are getting updates on that or not.

**Comment by ajayns** [comment]
@LekoArts I'm unsure how exactly to provide a reproduction since Sandbox runs on dev server. So what I've done is run it locally: gatsby build and then gatsby serve, and still doesn't work. So I've replicated the exact code on this sandbox: https://codesandbox.io/s/adoring-http-1ey28

I hope that helps.

@AkashRajpurohit are you using the latest version? Maybe it could something to do with that? Also, how do I debug the Google dashboard? Afaik their setup is fairly simple once you've pasted the tracking Id, nothing much to check there.

**Comment by AkashRajpurohit** [comment]
@ajayns I'm using `"gatsby-plugin-google-analytics": "2.1.23"`
Try using only the head flag for the plugin. Remove the other two flags and check again.

**Comment by sidharthachatterjee** [comment]
@ajayns Do you happen to have _Do Not Track_ set to `true` on your browser? All the plugin does is loads and sets the GA script which I understand does happen in your case. 

I did just try it out on a site and it works fine. 

This doesn't look like it's related to Gatsby or the plugin in particular since it _does_ load the GA script. Let's close this for now. Thanks!

**Comment by ajayns** [comment]
@sidharthachatterjee It could possibly because of that or maybe a GA issue since I'm collecting data but not getting real-time data. So yes we can close this issue.

Just a recommendation though, as of now there is a couple of Google Analytics plugin for Gatsby which confuses a new user. It could be nice to have documentation stating the difference and what's the latest tool recommended by Google (As of now I believe they're recommending GTag instead of GA)
