### ISSUE TITLE
e-commerce tutorial need not SEO keywords

### ISSUE THREAD

**Issue by naoya7076** [gatsbyjs/gatsby#21088]
https://www.gatsbyjs.org/tutorial/ecommerce-tutorial/#what-did-you-just-do
## Description
Why there are SEO keywords?
```
<SEO title="Home" keywords={[`gatsby`, `application`, `react`]} />
```
following the e-commerce tutorial, this place should be like this:
```
<SEO title="Home" />
```

### Actual result

```
<SEO title="Home" />
```

### Environment
```
  System:
    OS: macOS Mojave 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5
    gatsby-plugin-stripe: ^1.2.3 => 1.2.3
    gatsby-source-filesystem: ^2.1.40 => 2.1.40
    gatsby-source-stripe: ^3.0.5 => 3.0.5
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7
  npmGlobalPackages:
    gatsby-cli: 2.8.28
```

**Comment by DSchau** [comment]
Could you explain this? I don't see why we wouldn't want keywords for an SEO tutorial (albeit that keywords aren't actually the best way to maximize SEO).

**Comment by naoya7076** [comment]
In e-commerce tutorial, it doesn't explain about SEO and how to use.
I suppose that we should add link to SEO like this:
```
[SEO](https://www.gatsbyjs.org/docs/add-seo-component/)
```
or delete SEO components.

**Comment by LekoArts** [comment]
Thank you for opening this!

The ecommerce tutorial is a bit more advanced and starts with the default starter that comes with the SEO component. We assume that you followed more basic tutorials at the beginning and hence know what that component does.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
