### ISSUE TITLE
Is it possible to support 410 pages ?

### ISSUE THREAD

**Issue by Axnyff** [gatsbyjs/gatsby#21091]
## Summary
For Seo reasons, I need to be able to return a 410 page for gone pages.
It works fine with a couple of nginx directives but the gatsby browser runtime gets in my way.
It will redirect to my template url : /410 but I need to stay at the original location.
I've noticed there's an exception in the gatsby code for a 404 page but no for 410.

Is there a way to properly handle this case ?
## Relevant information

I tried adding either 
```
export const onClientEntry = () => {
  if (window.pagePath === '/410') {
    window.pagePath = '';
  }
};
```
or
```
export const onClientEntry = () => {
  if (window.pagePath === '/410') {
    window.pagePath = document.location.pathname;
  }
};
```
in gatsby-browser
but in both cases, the frontend runtime will try and get the page data for the current url and after getting a 404, will modify the pages to use the 404 template.

**Comment by sidharthachatterjee** [comment]
Have you tried using [createRedirect](https://www.gatsbyjs.org/docs/actions/#createRedirect) along with `statusCode` set to 410?

**Comment by Axnyff** [comment]
Hi, thanks for your help !

I didn't know about createRedirect. However, I tried it and it does not seem to change the behavior. Maybe I didn't actually understand what createRedirect is doing but I actually want to stay on the inital page while serving the static content of my 410 page

**Comment by Axnyff** [comment]
Your comment helped me find the right solution: I just need to create pages for each of my 410 pages and it will work fine. 

Thanks for your help!

**Comment by Rupendra22** [comment]
Hi @Axnyff , I have a similar request. I have few pages that are to be removed and in gatsby I need to work with 410 status code. Can you help me with this?
