### ISSUE TITLE
Question about Gatsby update

### ISSUE THREAD

**Issue by zhandosweb** [gatsbyjs/gatsby#21097]
Hello!

Please, let me ask one question. 

If I create my site on the previous Gatsby version. And now is available new Gatsby framework version. 

In this case, I should update Gatsby to the latest version? Or after updating, can I encounter issues on real working site? For example, plugin compatibility issues after updating Gatsby ..

And if my site working well, can I just not update Gatsby? 

Sorry, sir for bad English.

**Comment by LekoArts** [comment]
Thank you for opening this!

> In this case, I should update Gatsby to the latest version? 

We constantly improve Gatsby so updating is recommended to receive free updates to e.g. performance.

> Or after updating, can I encounter issues on real working site? For example, plugin compatibility issues after updating Gatsby

We do our best to follow semver so you shouldn't hit any problems.

> And if my site working well, can I just not update Gatsby?

You can, yes. It's still just a static site at the end :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
