### ISSUE TITLE
[gatsby-source-contentful] Initial page queries filtered by reference fields are missing content on initial `gatsby 

### ISSUE THREAD

**Issue by benrobertsonio** [gatsbyjs/gatsby#21102]
## Description

Starting in Gatsby 2.15 and up, page queries that filter on a reference field in `gatsby-source-contentful` are failing to hydrate in the initial `gatsby develop`. Once the development server is running, changing any portion of the page query fixes the issue and the query works as expected.

### Steps to reproduce

Here is an example query - working on getting a sandbox setup for better debugging but here's an initial stab at it.

```
{
  contentfulAuthor(id: $id) {}
  allContentfulBlogPosts(
    filter: {
      author: { id: { eq: $id } }
    }
    limit: 10
  ) {
    nodes {
      title
    }
  }
}
```

### Expected result

`allContentfulBlogPosts` should have data on initial build. 

### Actual result

`allContentfulBlogPosts` doesn't have data until the query is edited and the page hot reloads (eg. `limit` changes from 10 to 9)

### Environment

Gatsby version 2.15 and up
Node: 12.13.1
gatsby-source-contentful: ^2.1.65

**Comment by renrizzolo** [comment]
I am also experiencing this. it happens for me on `gatsby build` as well as `gatsby dev`.
e.g: build > no data on queries with reference filter > edit query (just swap the order of filter and limit in above example is enough) > build > data on queries with reference is there

**Comment by benrobertsonio** [comment]
@renrizzolo glad to know there's more than one person with the issue. Do you by chance have a repo to share to help reproduce?

**Comment by renrizzolo** [comment]
@benrobertsonio I do not have a reproduction at this stage, sorry.

a few things I can note for my case are:
- it's only happening on a specific linked reference. Filtering on other linked references on the same content type works, as do others on other content types.
- the behaviour is as though the filter string is not being passed - i.e `eq "[string]"` returns nothing, `ne "[string]"` returns all results.

**ETA**: I believe I have now fixed this by changing my `gatsby-node.js` page creation and article/custom template page creation to async/await and separating the graphql queries.

```JS
exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions
  const pages = await graphql(`
    {
      allContentfulPage(limit: 1000) {
        edges {
          node {
            ...
          }
        }
      }
      allContentfulPost(limit: 1000) {
        edges {
            node {
            ...
          }
        }
      }
      allContentfulCategory {
        edges {
          node {
            ...
          }
        }
      }
    }
  `).then(result => {
   // create pages, create news articles, create category pages
  }

  const otherContentType = await graphql(`
    {
    allContentfulStuff(limit: 1000) {
        edges {
          node {
            ...
          }
        }
      }
      allContentfulStuffType(limit: 1000) {
        edges {
          node {
            ...
          }
        }
      }
    }
  `).then(result => {
  // create more pages from other content types
 }
}
```

Before I had a long script where I was looping through each page, then if the page was 'news', looping through categories and creating category pages, then the same for creating the news articles etc, for multiple content types. I'm still doing nested/adjacent forEach loops, but I moved the problematic content type out of the outer pages loop (which it didn't rely on).
