### ISSUE TITLE
UNHANDLED REJECTION Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jack2gs** [gatsbyjs/gatsby#21119]
## Description

*UNHANDLED REJECTION Maximum call stack size exceeded* shows when run `gatsby develop`

### Steps to reproduce

```shell
gatsby new blog-gatsby-org https://github.com/orgapp/gatsby-orga
cd blog-gatsby-org&&gatsby develop
```

### Expected result

Gatsby should run successfully in local.

### Actual result

*UNHANDLED REJECTION Maximum call stack size exceeded* shows

### Environment

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 Intel(R) Xeon(R) E-2174G CPU @ 3.80GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
  npmPackages:
    gatsby: ^2.14.0 => 2.19.10 
    gatsby-source-filesystem: ^2.1.18 => 2.1.47 
    gatsby-transformer-orga: ^1.5.2 => 1.8.4 
  npmGlobalPackages:
    gatsby: 2.19.10

### log
![Screenshot from 2020-02-01 20-12-52](https://user-images.githubusercontent.com/7608222/73591905-62b48a80-452f-11ea-9158-9133bc56a09b.png)

**Comment by sidharthachatterjee** [comment]
Looks like this is happening in `deepmerge` which isn't used in `gatsby` as far as I can tell from the top of my head. This might have to do with the `gatsby-transformer-orga` plugin (which I couldn't find on GitHub)

That does package use `deepmerge`?

**Comment by jack2gs** [comment]
https://github.com/orgapp/gatsby-orga
