### ISSUE TITLE
[docs][i18n] Replace live examples docs/data-fetching with a CodeSandbox <iframe>

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21112]
## Summary

Remove the "live" examples from [Build Time and Client Runtime Data Fetching](https://www.gatsbyjs.org/docs/data-fetching/) and replace them with <iframes> to CodeSandbox for an example app.

### Motivation

The "live examples" in this page just show special code that is run on www/. They don't really allow for interactivity and don't clearly show *how* it's live. By replacing this with a CodeSandbox example, we can provide a link to the codesandbox and encourage readers to try editing the example so they can see the differences themselves.

In addition, these live examples require us to make a couple of special changes to the www code, increasing its complexity:

* Creating a special node and requiring an extra API call to GitHub in [gatsby-node](https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-node.js#L742)
* Importing two special components for the examples, which would break localized versions of the file: #20795

## Steps

* Replace the "live examples" components with iframes to the example site on codesandbox.
* Delete the special handler code in gatsby-node and the example components from www/.

### Related Issues

Part of: #20795

**Comment by gunjanmimo** [comment]
May I take this issue?
May you please assign me this problem?

**Comment by LekoArts** [comment]
@gunjanmimo This issue got stale but you can look at the other ["help wanted" issues](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22).
