### ISSUE TITLE
[gatsby-source-shopify] - timeout error on build

### ISSUE THREAD

**Issue by kingingcole** [gatsbyjs/gatsby#21110]
## Description

I have a client's Shopify store with over 1000 products. When I use this plugin, I always get a timedout error when running `gatsby develop`.
I have tried reducing  paginationSize to as low as 50, but it still shows same error.

### Steps to reproduce

I don't know how else someone can reproduce this if not using the plugin on a large Shopify store.

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

All queries should run and site developed.

### Actual result

`gatsby develop` always stops at the stage for running category queries with a timedout error.

**Comment by sidharthachatterjee** [comment]
My best guess is the timeout is a result of some request limiting on Shopify's end. Can you paste the specific error you're seeing? Maybe that'll shed some light.

**Comment by LekoArts** [comment]
Thank you for opening this!

I'd recommend contacting Shopify if there is indeed a request limiting on their end. If you can provide a minimal reproduction, feel free to link that here.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
