### ISSUE TITLE
Routing With Gatsby Link Crashes Returns Blank Page

### ISSUE THREAD

**Issue by MrCEO63** [gatsbyjs/gatsby#21122]
## Description

Experiencing crash with errors when using gatsby Link. 

### Steps to reproduce
```
import { useStaticQuery, Link, graphql } from 'gatsby';

  const NavLinks = (link, name) => (
    <li tabIndex="0" className="px-5 focus:outline-none">
      <Link activeClassName="text-cf-200" to={link}>
        {name}
      </Link>
    </li>
  );
```

### Expected result
Route to other pages with no error.

### Actual result

Throw errors, blank page
`backend.js:6 TypeError: n is not a function
at t.unstable_runWithPriority
`

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz  
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.0 - /c/Program Files/Python37/python       
  Browsers:
    Edge: 44.19041.1.0
  npmPackages:
    gatsby: ^2.18.3 => 2.19.10
    gatsby-image: ^2.2.33 => 2.2.39
    gatsby-plugin-mailchimp: ^5.1.2 => 5.1.2
    gatsby-plugin-manifest: ^2.2.29 => 2.2.40
    gatsby-plugin-offline: ^3.0.23 => 3.0.33
    gatsby-plugin-postcss: ^2.1.16 => 2.1.19
    gatsby-plugin-react-helmet: ^3.1.15 => 3.1.21
    gatsby-plugin-sharp: ^2.3.3 => 2.4.4
    gatsby-plugin-styled-components: ^3.1.14 => 3.1.18
    gatsby-plugin-transition-link: ^1.17.7 => 1.17.7
    gatsby-source-filesystem: ^2.1.38 => 2.1.47
    gatsby-source-medium-feed: ^1.0.6 => 1.0.6
    gatsby-transformer-json: ^2.2.20 => 2.2.25
    gatsby-transformer-sharp: ^2.3.5 => 2.3.13

**Comment by blainekasten** [comment]
Hey there! Sorry for the snafu your hitting! The details above isn’t enough yet to action upon.. the stack trace for `n` is a bit obtuse. Can you give us any more of a trace? Or use reacts developer tools to figure out what it’s referring to?

**Comment by MrCEO63** [comment]
> Hey there! Sorry for the snafu your hitting! The details above isn’t enough yet to action upon.. the stack trace for `n` is a bit obtuse. Can you give us any more of a trace? Or use reacts developer tools to figure out what it’s referring to?

`react-dom.production.min.js:4684 TypeError: n is not a function
    at react-dom.production.min.js:4782
    at t.unstable_runWithPriority (scheduler.production.min.js:274)
    at Ga (react-dom.production.min.js:2842)
    at hl (react-dom.production.min.js:4772)
    at bl (react-dom.production.min.js:4953)
    at bu (react-dom.production.min.js:6311)
    at t.unstable_runWithPriority (scheduler.production.min.js:274)
    at Ga (react-dom.production.min.js:2842)
    at gu (react-dom.production.min.js:6153)
    at ou (react-dom.production.min.js:5456)
fl @ react-dom.production.min.js:4684
o.componentDidCatch.n.callback @ react-dom.production.min.js:5151
Eo @ react-dom.production.min.js:3107
bo @ react-dom.production.min.js:3093
bu @ react-dom.production.min.js:6377
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
gu @ react-dom.production.min.js:6153
ou @ react-dom.production.min.js:5456
(anonymous) @ react-dom.production.min.js:2877
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
$a @ react-dom.production.min.js:2872
Qa @ react-dom.production.min.js:2862
eu @ react-dom.production.min.js:5239
enqueueSetState @ react-dom.production.min.js:3139
E.setState @ react.production.min.js:82
a.safeSetState @ Transition.js:404
(anonymous) @ Transition.js:383
nextCallback @ Transition.js:416
setTimeout (async)
a.onTransitionEnd @ Transition.js:441
(anonymous) @ Transition.js:382
nextCallback @ Transition.js:416
Eo @ react-dom.production.min.js:3107
bo @ react-dom.production.min.js:3093
bu @ react-dom.production.min.js:6377
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
gu @ react-dom.production.min.js:6153
ou @ react-dom.production.min.js:5456
(anonymous) @ react-dom.production.min.js:2877
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
$a @ react-dom.production.min.js:2872
Qa @ react-dom.production.min.js:2862
eu @ react-dom.production.min.js:5239
enqueueSetState @ react-dom.production.min.js:3139
E.setState @ react.production.min.js:82
(anonymous) @ index.js:154
requestAnimationFrame (async)
(anonymous) @ index.js:152
Promise.then (async)
(anonymous) @ index.js:150
(anonymous) @ history.js:96
navigate @ history.js:95
(anonymous) @ navigation.js:116
Promise.then (async)
x @ navigation.js:83
UxWs.window.___navigate @ navigation.js:155
y @ index.js:240
onClick @ index.js:207
onClick @ index.js:483
h @ react-dom.production.min.js:128
T @ react-dom.production.min.js:148
(anonymous) @ react-dom.production.min.js:152
k @ react-dom.production.min.js:172
A @ react-dom.production.min.js:201
O @ react-dom.production.min.js:190
N @ react-dom.production.min.js:214
Sn @ react-dom.production.min.js:1724
ce @ react-dom.production.min.js:7305
An @ react-dom.production.min.js:1789
Pn @ react-dom.production.min.js:1826
Nn @ react-dom.production.min.js:1801
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
le @ react-dom.production.min.js:7290
On @ react-dom.production.min.js:1758
react-dom.production.min.js:4684 TypeError: n is not a function
    at react-dom.production.min.js:4782
    at t.unstable_runWithPriority (scheduler.production.min.js:274)
    at Ga (react-dom.production.min.js:2842)
    at hl (react-dom.production.min.js:4772)
    at bl (react-dom.production.min.js:4953)
    at bu (react-dom.production.min.js:6311)
    at t.unstable_runWithPriority (scheduler.production.min.js:274)
    at Ga (react-dom.production.min.js:2842)
    at gu (react-dom.production.min.js:6153)
    at ou (react-dom.production.min.js:5456)
fl @ react-dom.production.min.js:4684
Sl.n.callback @ react-dom.production.min.js:5129
Eo @ react-dom.production.min.js:3107
bo @ react-dom.production.min.js:3093
bu @ react-dom.production.min.js:6393
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
gu @ react-dom.production.min.js:6153
ou @ react-dom.production.min.js:5456
(anonymous) @ react-dom.production.min.js:2877
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
$a @ react-dom.production.min.js:2872
Qa @ react-dom.production.min.js:2862
eu @ react-dom.production.min.js:5239
enqueueSetState @ react-dom.production.min.js:3139
E.setState @ react.production.min.js:82
a.safeSetState @ Transition.js:404
(anonymous) @ Transition.js:383
nextCallback @ Transition.js:416
setTimeout (async)
a.onTransitionEnd @ Transition.js:441
(anonymous) @ Transition.js:382
nextCallback @ Transition.js:416
Eo @ react-dom.production.min.js:3107
bo @ react-dom.production.min.js:3093
bu @ react-dom.production.min.js:6377
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
gu @ react-dom.production.min.js:6153
ou @ react-dom.production.min.js:5456
(anonymous) @ react-dom.production.min.js:2877
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
$a @ react-dom.production.min.js:2872
Qa @ react-dom.production.min.js:2862
eu @ react-dom.production.min.js:5239
enqueueSetState @ react-dom.production.min.js:3139
E.setState @ react.production.min.js:82
(anonymous) @ index.js:154
requestAnimationFrame (async)
(anonymous) @ index.js:152
Promise.then (async)
(anonymous) @ index.js:150
(anonymous) @ history.js:96
navigate @ history.js:95
(anonymous) @ navigation.js:116
Promise.then (async)
x @ navigation.js:83
UxWs.window.___navigate @ navigation.js:155
y @ index.js:240
onClick @ index.js:207
onClick @ index.js:483
h @ react-dom.production.min.js:128
T @ react-dom.production.min.js:148
(anonymous) @ react-dom.production.min.js:152
k @ react-dom.production.min.js:172
A @ react-dom.production.min.js:201
O @ react-dom.production.min.js:190
N @ react-dom.production.min.js:214
Sn @ react-dom.production.min.js:1724
ce @ react-dom.production.min.js:7305
An @ react-dom.production.min.js:1789
Pn @ react-dom.production.min.js:1826
Nn @ react-dom.production.min.js:1801
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
le @ react-dom.production.min.js:7290
On @ react-dom.production.min.js:1758
react-dom.production.min.js:4782 Uncaught TypeError: n is not a function
    at react-dom.production.min.js:4782
    at t.unstable_runWithPriority (scheduler.production.min.js:274)
    at Ga (react-dom.production.min.js:2842)
    at hl (react-dom.production.min.js:4772)
    at bl (react-dom.production.min.js:4953)
    at bu (react-dom.production.min.js:6311)
    at t.unstable_runWithPriority (scheduler.production.min.js:274)
    at Ga (react-dom.production.min.js:2842)
    at gu (react-dom.production.min.js:6153)
    at ou (react-dom.production.min.js:5456)
(anonymous) @ react-dom.production.min.js:4782
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
hl @ react-dom.production.min.js:4772
bl @ react-dom.production.min.js:4953
bu @ react-dom.production.min.js:6311
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
gu @ react-dom.production.min.js:6153
ou @ react-dom.production.min.js:5456
(anonymous) @ react-dom.production.min.js:2877
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
$a @ react-dom.production.min.js:2872
Qa @ react-dom.production.min.js:2862
eu @ react-dom.production.min.js:5239
enqueueSetState @ react-dom.production.min.js:3139
E.setState @ react.production.min.js:82
a.safeSetState @ Transition.js:404
(anonymous) @ Transition.js:383
nextCallback @ Transition.js:416
setTimeout (async)
a.onTransitionEnd @ Transition.js:441
(anonymous) @ Transition.js:382
nextCallback @ Transition.js:416
Eo @ react-dom.production.min.js:3107
bo @ react-dom.production.min.js:3093
bu @ react-dom.production.min.js:6377
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
gu @ react-dom.production.min.js:6153
ou @ react-dom.production.min.js:5456
(anonymous) @ react-dom.production.min.js:2877
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
$a @ react-dom.production.min.js:2872
Qa @ react-dom.production.min.js:2862
eu @ react-dom.production.min.js:5239
enqueueSetState @ react-dom.production.min.js:3139
E.setState @ react.production.min.js:82
(anonymous) @ index.js:154
requestAnimationFrame (async)
(anonymous) @ index.js:152
Promise.then (async)
(anonymous) @ index.js:150
(anonymous) @ history.js:96
navigate @ history.js:95
(anonymous) @ navigation.js:116
Promise.then (async)
x @ navigation.js:83
UxWs.window.___navigate @ navigation.js:155
y @ index.js:240
onClick @ index.js:207
onClick @ index.js:483
h @ react-dom.production.min.js:128
T @ react-dom.production.min.js:148
(anonymous) @ react-dom.production.min.js:152
k @ react-dom.production.min.js:172
A @ react-dom.production.min.js:201
O @ react-dom.production.min.js:190
N @ react-dom.production.min.js:214
Sn @ react-dom.production.min.js:1724
ce @ react-dom.production.min.js:7305
An @ react-dom.production.min.js:1789
Pn @ react-dom.production.min.js:1826
Nn @ react-dom.production.min.js:1801
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
le @ react-dom.production.min.js:7290
On @ react-dom.production.min.js:1758
navigation.js:173 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at navigation.js:173
(anonymous) @ navigation.js:173
requestAnimationFrame (async)
n.componentDidUpdate @ navigation.js:168
bu @ react-dom.production.min.js:6374
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
gu @ react-dom.production.min.js:6153
ou @ react-dom.production.min.js:5456
(anonymous) @ react-dom.production.min.js:2877
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
$a @ react-dom.production.min.js:2872
Qa @ react-dom.production.min.js:2862
eu @ react-dom.production.min.js:5239
enqueueSetState @ react-dom.production.min.js:3139
E.setState @ react.production.min.js:82
(anonymous) @ index.js:154
requestAnimationFrame (async)
(anonymous) @ index.js:152
Promise.then (async)
(anonymous) @ index.js:150
(anonymous) @ history.js:96
navigate @ history.js:95
(anonymous) @ navigation.js:116
Promise.then (async)
x @ navigation.js:83
UxWs.window.___navigate @ navigation.js:155
y @ index.js:240
onClick @ index.js:207
onClick @ index.js:483
h @ react-dom.production.min.js:128
T @ react-dom.production.min.js:148
(anonymous) @ react-dom.production.min.js:152
k @ react-dom.production.min.js:172
A @ react-dom.production.min.js:201
O @ react-dom.production.min.js:190
N @ react-dom.production.min.js:214
Sn @ react-dom.production.min.js:1724
ce @ react-dom.production.min.js:7305
An @ react-dom.production.min.js:1789
Pn @ react-dom.production.min.js:1826
Nn @ react-dom.production.min.js:1801
t.unstable_runWithPriority @ scheduler.production.min.js:274
Ga @ react-dom.production.min.js:2842
le @ react-dom.production.min.js:7290
On @ react-dom.production.min.js:1758`

**Comment by blainekasten** [comment]
This stack trace is minified, which means it is compiled in a production mode. Is there a non-production stack trace? like can you reproduce in `gatsby develop` ? does that yield a different stack trace?


I actually have a guess at what's happening here. If the code above is not sample code and indeed your actual code, you forgot to export your component. So the parent component is likely importing nothing and thus trying to render a component that doesn't exist giving the `n is not a function` error.

So maybe try changing to `export default NavLinks`?

**Comment by MrCEO63** [comment]
> This stack trace is minified, which means it is compiled in a production mode. Is there a non-production stack trace? like can you reproduce in `gatsby develop` ? does that yield a different stack trace?
> 
> I actually have a guess at what's happening here. If the code above is not sample code and indeed your actual code, you forgot to export your component. So the parent component is likely importing nothing and thus trying to render a component that doesn't exist giving the `n is not a function` error.
> 
> So maybe try changing to `export default NavLinks`?

Hi, @blainekasten I appreciate your help, This doesn't occur in an earlier build version, we are rolling back, and try to figure out where the problem might be from.
