### ISSUE TITLE
TypeError: keywords.join is not a function

### ISSUE THREAD

**Issue by expatguideturkey** [gatsbyjs/gatsby#21133]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 

I want to implement SEO on my gatsby project, I am using https://wordpress.org/plugins/wp-api-yoast-meta/ to fetch Yoast fields. I can see the values in Graphql but when I implement it to page.js and post.js `<SEO title={data.currentPage.yoast.title} description={data.currentPage.yoast.metadesc} keywords={data.currentPage.yoast.focuskw} />`

I receive **TypeError: keywords.join is not a function** what could be the reason.

**SEO.JS**

```
/**
 * SEO component that queries for data with
 *  Gatsby's useStaticQuery React hook
 *
 * See: https://www.gatsbyjs.org/docs/use-static-query/
 */

import React from 'react';
import PropTypes from 'prop-types';
import Helmet from 'react-helmet';
import { useStaticQuery, graphql } from 'gatsby';

function SEO({ description, lang, meta, keywords, title }) {
  const { site } = useStaticQuery(
    graphql`
      query {
        site {
          siteMetadata {
            title
            description
            author
          }
        }
      }
    `
  );

  const metaDescription = description || site.siteMetadata.description;

  return (
    <Helmet
      htmlAttributes={{
        lang,
      }}
      title={title}
      titleTemplate={`%s | ${site.siteMetadata.title}`}
      meta={[
        {
          name: `description`,
          content: metaDescription,
        },
        {
          property: `og:title`,
          content: title,
        },
        {
          property: `og:description`,
          content: metaDescription,
        },
        {
          property: `og:type`,
          content: `website`,
        },
        {
          name: `twitter:card`,
          content: `summary`,
        },
        {
          name: `twitter:creator`,
          content: site.siteMetadata.author,
        },
        {
          name: `twitter:title`,
          content: title,
        },
        {
          name: `twitter:description`,
          content: metaDescription,
        },
      ]
        .concat(
          keywords.length > 0
            ? {
                name: `keywords`,
                content: keywords.join(`, `),
              }
            : []
        )
        .concat(meta)}
    />
  );
}

SEO.defaultProps = {
  lang: `en`,
  meta: [],
  keywords: [],
  description: ``,
};

SEO.propTypes = {
  description: PropTypes.string,
  lang: PropTypes.string,
  meta: PropTypes.arrayOf(PropTypes.object),
  keywords: PropTypes.arrayOf(PropTypes.string),
  title: PropTypes.string.isRequired,
};

export default SEO;

```
**page.js**

```
/* eslint-disable react/no-danger */
import React from 'react';
import { graphql } from 'gatsby';
import styled from 'styled-components';
import SEO from '../components/seo';

import Layout from '../components/layout';
import BreadCrumb from '../components/BreadCrumb';
import PageHero from '../components/PageHero';
import './styles/fontawesome.css';


const PageContent = styled.article`
  margin: 20px 0 0 0;
`;

const PageTemplate = ({ data }) => (
<Layout>
<SEO title={data.currentPage.yoast.title} description={data.currentPage.yoast.metadesc} keywords={data.currentPage.yoast.focuskw} />
    {data.currentPage.featured_media ? (
      <PageHero
        img={data.currentPage.featured_media.localFile.childImageSharp.fluid}
      />
    ) : null}
    <BreadCrumb parent={data.parent} />
    <div className="container">
      <div className="row" style={{ marginBottom: '40px'}}>
            
         <PageContent className="col-lg-12">
         
         <div className="col-md-8"
          data-sal="fade"
          data-sal-delay="300"
          data-sal-duration="20s"
          data-sal-easing="ease">
         <h1 dangerouslySetInnerHTML={{ __html: data.currentPage.title }} />
         </div> 
         <div  dangerouslySetInnerHTML={{ __html: data.currentPage.content }} />
         </PageContent>
         </div>
    </div>
  </Layout>
  );

export default PageTemplate;

export const pageQuery = graphql`
  query($id: String!, $parent: Int!, $wpId: Int!) {
    currentPage: wordpressPage(id: { eq: $id }) {
      id
      title
      content
      slug
      wordpress_parent
      yoast {
        focuskw
        canonical
        title
        metadesc
        metakeywords
      }
      featured_media {
        localFile {
          childImageSharp {
            fluid(quality: 100, maxWidth: 1200) {
              ...GatsbyImageSharpFluid_withWebp
            }
          }
        }
      }

      acf {
        section_1_heading
        section_2_heading
        section_3_heading
        section_1_text
        section_2_text
        section_3_text
       }

    }
    parentChildren: allWordpressPage(
      filter: { wordpress_parent: { eq: $parent } }
    ) {
      edges {
        node {
          id
          title
          link
        }
      }
  
    
    }
    children: allWordpressPage(filter: { wordpress_parent: { eq: $wpId } }) {
      edges {
        node {
          id
          title
          link
        }
      }
    }
    parent: wordpressPage(wordpress_id: { eq: $parent }) {
      title
      link
    }
  }
`;
```

**Comment by danspratling** [comment]
Yoast no longer supports keywords so i'm not sure why it's not erroring sooner.
https://yoast.com/meta-keywords/

Join can only be used on an array so if something else is being returned you may have to adjust it (assuming you _really need_ keywords that is).

What does the data of keywords look like when it's returned?

**Comment by expatguideturkey** [comment]
> Yoast no longer supports keywords so i'm not sure why it's not erroring sooner.
> https://yoast.com/meta-keywords/
> 
> Join can only be used on an array so if something else is being returned you may have to adjust it (assuming you _really need_ keywords that is).
> 
> What does the data of keywords look like when it's returned?

Thanks for your response @danspratling If I remove join function, as I have only one focus keyword for each post/page:

```
  .concat(
          keywords.length > 0
            ? {
                name: `keywords`,
                content: keywords,
              }
            : []
        )
```
then it works fine no errors. It fetches the same focus keyword value that I have entered in the WordPress post/page Yoast SEO section. 

But is this process is enough to implement SEO on gatsby projects by having SEO component and setting it values on page.js and post.js like this:
`<SEO title={data.currentPage.yoast.title} description={data.currentPage.yoast.metadesc} keywords={data.currentPage.yoast.focuskw} />`

or I need to do anything else to make sure my Yoast SEO settings work as it used to work on my WordPress website.

**Comment by danspratling** [comment]
My best guess is that keywords is being returned as a string, not an array. OR keywords is being returned as a string if there's only a single keyword.

This would pass `keywords.length` as a string will return the number of characters, but will fail `keywords.join()` because you can't join a string.

What do you see when you `console.log(keywords)`?

**Comment by expatguideturkey** [comment]
> My best guess is that keywords is being returned as a string, not an array. OR keywords is being returned as a string if there's only a single keyword.
> This would pass keywords.length as a string will return the number of characters, but will fail keywords.join() because you can't join a string (it's already joined).
> What do you see when you console.log(keywords)?
> Being able to see the data in the array would be really useful for debugging here.

@danspratling thanks for your response. I get these values as displayed in this screenshot https://prnt.sc/qxqzni this keyword value is actually my Yoast Focus Keyword, If I use this value for keywords in my component will it work similar to the purpose of Yoast Focus Keyword or is there anyother way to use it. Can you please clearify this concept.

**Comment by danspratling** [comment]
I think you may be misunderstanding what i'm asking. I don't care about the **contents** of your keywords. I just care about their Type. Here's an example, comparing a string and an array.

https://prnt.sc/qxzcfj

Note that both strings and arrays have length. But strings cannot be joined.

I don't use yoast so i can't test this myself, and debugging yoast is out of scope within the Gatsby issues.

You should `console.log(keywords)` so you understand what type you're working with before going any further. If you're already working with a string then you don't need to join anything.

**Comment by expatguideturkey** [comment]
When I console.log(keywords) and console.log(typeof(keywords)) I get this result https://prnt.sc/qysx4h

**Comment by danspratling** [comment]
Ah just as I thought! So as it’s a string, you can’t join it. You’ll probably just need to output it as it is to display all the keywords you need.

**Comment by sidharthachatterjee** [comment]
Looks like @danspratling was right. 

Closing this for now. Thank you to the two of you!
