### ISSUE TITLE
Build and develop inconsistent Styling

### ISSUE THREAD

**Issue by Altrum** [gatsbyjs/gatsby#21148]
## Description

When I run `gatsby develop`, everything looks fine. However, when I do `gatsby build` and upload the site to s3, the site looks way off--except for the pages created by `exports.createPages` in gatsby-node.js

### Steps to reproduce

The code is available here: https://github.com/Altrum/PersonalWebsite/tree/master/frontend

### Expected result

Should look like:
![image](https://user-images.githubusercontent.com/19492578/73610509-f0729300-458c-11ea-97d1-311974b4ff9c.png)

### Actual result

Looks like: http://www.robertchung.me.s3-website-us-west-2.amazonaws.com/

But if you click on one of the posts (the ones created by `createPages`, it looks fine: http://www.robertchung.me.s3-website-us-west-2.amazonaws.com/welcome

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 68.4.1
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-feed: ^2.3.23 => 2.3.23
    gatsby-plugin-google-analytics: ^2.1.29 => 2.1.29
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5
    gatsby-plugin-typography: ^2.3.18 => 2.3.18
    gatsby-remark-copy-linked-files: ^2.1.31 => 2.1.31
    gatsby-remark-images: ^3.1.35 => 3.1.35
    gatsby-remark-prismjs: ^3.3.25 => 3.3.25
    gatsby-remark-responsive-iframe: ^2.2.28 => 2.2.28
    gatsby-remark-smartypants: ^2.1.17 => 2.1.17
    gatsby-source-filesystem: ^2.1.40 => 2.1.40
    gatsby-source-ghost: ^4.0.3 => 4.0.3
    gatsby-transformer-remark: ^2.6.39 => 2.6.39
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7
  npmGlobalPackages:
    gatsby-cli: 2.8.27

**Comment by elken** [comment]
Would recommend starting with [Ghost's](https://github.com/TryGhost/gatsby-starter-ghost) own starter project rather than the default.

**Comment by LekoArts** [comment]
Hi!

Please use this plugin to enable SSR for Material UI:
https://www.gatsbyjs.org/packages/gatsby-plugin-material-ui/

**Comment by elken** [comment]
Ah yep, didn't spot the material ui I assumed it was custom.

**Comment by Altrum** [comment]
using the gatsby-plugin worked! Thanks so much :)
