### ISSUE TITLE
SEO and gatsby-plugin-intl

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#21155]
Hello Gatsby,

I have a big sites with around 30 pages manually created in `/pages` and around 40K+ client route only pages.

I would like to use `react-intl` with the plugin `gatsby-plugin-intl` but I'm wondering about SEO for client route only. 

Does my 40K+ pages will be referenced by search engine or not? 
I'm confident for the others 30 pages. They are static, not dynamic.

**Comment by crock** [comment]
As far as I understand, you would need to use pre-rendering for all of the client routes if you want the SEO meta tags to be recognized for all the client-side only pages. Services like https://prerender.io exist for this purpose.

**Comment by Steffi3rd** [comment]
Each commit trigger build in with Netlify, how can I plug https://prerender.io ?

**Comment by crock** [comment]
> Each commit trigger build in with Netlify, how can I plug https://prerender.io ?

Netlify has an option under Site Settings -> Build and Deploy -> Prerendering
https://docs.netlify.com/site-deploys/post-processing/prerendering/

**Comment by Steffi3rd** [comment]
@crock Thank you. I will try that suggestion ^^
