### ISSUE TITLE
Is this a hydration problem?

### ISSUE THREAD

**Issue by Altrum** [gatsbyjs/gatsby#21154]
## Relevant information

When loading a page, it gets "re-rendered" and loses the data that actually exists.

To illustrate, if you go to this site: https://www.robertchung.me/about/
You can see a brief flash of the content being there (you can spam refresh and you'll see it pop up for a second and then disappear)

The weird thing is that the s3 bucket that the website is serving from actually has the page: https://s3-us-west-2.amazonaws.com/robertchung.me/about/index.html that renders fine.

I'm wondering if it's related to the hydration issue here: https://github.com/gatsbyjs/gatsby/issues/17914 or if anyone has an idea on what this is.

The source code for my site can be found here: https://github.com/Altrum/PersonalWebsite

### Environment (if relevant)

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 68.4.1
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-feed: ^2.3.23 => 2.3.23
    gatsby-plugin-google-analytics: ^2.1.29 => 2.1.29
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-s3: ^0.3.2 => 0.3.2
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5
    gatsby-plugin-typography: ^2.3.18 => 2.3.18
    gatsby-remark-copy-linked-files: ^2.1.31 => 2.1.31
    gatsby-remark-images: ^3.1.35 => 3.1.35
    gatsby-remark-prismjs: ^3.3.25 => 3.3.25
    gatsby-remark-responsive-iframe: ^2.2.28 => 2.2.28
    gatsby-remark-smartypants: ^2.1.17 => 2.1.17
    gatsby-source-filesystem: ^2.1.40 => 2.1.40
    gatsby-source-ghost: ^4.0.3 => 4.0.3
    gatsby-transformer-remark: ^2.6.39 => 2.6.39
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7
  npmGlobalPackages:
    gatsby-cli: 2.8.29

**Comment by owen-riley** [comment]
I believe your problem is nested `<p>` tags. If you switch line 27 of about.jsx to be a `div` instead of a `p` tag then it should work. The data you are dangerously setting inside of it is already wrapped in`<p>` tags and since `<p>` can't contain child `<p>` tags, they are getting purged after the app rehydrates.

**Comment by Altrum** [comment]
Thanks so much! This was haunting me for so long...
