### ISSUE TITLE
bug(mdx): absolute image path not throw an error

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#21174]
## Description 

i see this code snippet:

https://github.com/gatsbyjs/gatsby/blob/3aa180ac1a9a1b1e94760edbbc5ed4648a45bf4e/docs/blog/100days/index.md#L12

but the image is in the same directory, so it should throw an error?

### Steps to reproduce

- checkout gatsbyjs and run the www website

### Expected result

- some error

### Actual result

no error

**Comment by LekoArts** [comment]
Not sure we can thrown an error there, this could be solved with some remark linting I guess. I don't see any actionable here, so closing.

**Comment by muescha** [comment]
but the question is: why this is working here? it should not working?

because an `/100daysofgatsby.png` should be pointed to 
https://gatsbyjs.org/100daysofgatsby.png` and not to some sub directory?
