### ISSUE TITLE
Layout json cache is not invalidated (even after restarting) when query result is null

### ISSUE THREAD

**Issue by arekkas** [gatsbyjs/gatsby#2117]
I have a layout component that queries

```
export const query = graphql`
query TestQuery {
  testJson(id: { eq: "id1" }) {
    id
    data
  }
}
`
```

from a json file

```
[
  {
    "id": "id2",
    "data": "foo"
  }
]
```

with the following gatsby-config:

```
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `${__dirname}/src/data/`,
      },
    },
    'gatsby-transformer-json'
  ],
}
```

When I update the json file and add `id1`

```
[
  {
    "id": "id2",
    "data": "foo"
  },
  {
    "id": "id1",
    "data": "foo"
  }
]
```

the query still returns `null`. I checked the cache (in `.cache`) and it seems that the null value is not updated. I have to remove the 

The same procedure works fine in regular pages. Here's a reproducible case:  https://github.com/ory/sites/tree/ar-prototype/repro-case

**Comment by jlengstorf** [comment]
This should be fixed in V2, since layouts are going away. I'm going to close this, but please reopen if you see similar issues in V2.
