### ISSUE TITLE
Blog: Challenge 6 don't show up in lists

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#21197]
## Description

- you can open the blog with direct link: https://www.gatsbyjs.org/blog/100days/serverless/
- but it not show up in this places:
  - blog lists
  - tags list
  - next link in the previous blog post

### Steps to reproduce

Not listed as blog post:
- https://www.gatsbyjs.org/blog/
- https://www.gatsbyjs.org/blog/tags/100-days-of-gatsby

Missing next link:
- https://www.gatsbyjs.org/blog/2020-01-08-git-workflows/

### Expected result

- Blog post should be listed

### Actual result

- Blog post is not listed

### Environment

- Web-Browser

**Comment by muescha** [comment]
ping to @hashimwarren

**Comment by sidharthachatterjee** [comment]
I see the blog post titled _Challenge 6 - Use Serverless Functions and Services to Collect Form Data_ showing up on both https://www.gatsbyjs.org/blog/tags/100-days-of-gatsby/ and https://www.gatsbyjs.org/blog/

Closing this for now!

**Comment by muescha** [comment]
what changes make them show up in the list?
