### ISSUE TITLE
CSS Differs between Gatsby Develop and Build

### ISSUE THREAD

**Issue by henkka01** [gatsbyjs/gatsby#21205]
## Description

The site is working fine in develop mode, but once the sites is built the CSS differs from what is seen in develop mode. 

### Steps to reproduce

1. Pull repository from https://github.com/henkka01/spill_agency
2. Apply Gatsby develop 
3. Apply Gatsby build +  gatsby serve 
4. Compare 2 and 3 in Chrome Developer Tools on a _mobile device_ 

### Expected result

Develop and Build would look the same.

### Actual result

Develop and Build do not look the same.

### Environment

System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.12 => 2.19.12
    gatsby-awesome-pagination: ^0.3.5 => 0.3.5
    gatsby-image: ^2.2.39 => 2.2.40
    gatsby-plugin-sharp: ^2.4.0 => 2.4.5
    gatsby-plugin-styled-components: ^3.1.17 => 3.1.19
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-contentful: ^2.1.79 => 2.1.85
    gatsby-source-instagram: ^0.6.1 => 0.6.1
    gatsby-transformer-sharp: ^2.3.13 => 2.3.14

**Comment by andrico1234** [comment]
Potentially the same issue as this? 
https://github.com/gatsbyjs/gatsby/issues/21296

**Comment by sidharthachatterjee** [comment]
Let's follow this on https://github.com/gatsbyjs/gatsby/issues/21296 since these are both the same issue
