### ISSUE TITLE
[gatsby-source-filesystem]: enhance options for a more specific file selection and disabling watching on them

### ISSUE THREAD

**Issue by muuvmuuv** [gatsbyjs/gatsby#21219]
## Summary

I am trying to get [`gatsby-transformer-leasot`](https://github.com/GaiAma/Coding4GaiAma/tree/master/packages/gatsby-transformer-leasot) to work, so I can show my "todos" somewhere on my website together with GitHub issues. The plugin suggest to use `__dirname` as a path and ignore everything else, this works as expected and I got my "todos" listed.

The issue with `__dirname` is simply that on EVERY change I do on `Issue.jsx` `gatsby-source-filesystem` is triggered :D. This causes a lot of "run queries" and sometimes breaks the process. 

My suggestion is to provide an option `watch: false` to stop `gatsby-source-filesystem` from watching file changes. Additionally, it would be great to allow an array or glob in `path` to only watch those files, the `ignore` "hack" is pretty messy.

So instead of:

```js
module.exports = {
  resolve: `gatsby-source-filesystem`,
  options: {
    name: `leasot`,
    path: __dirname,
    ignore: [
      `**/.*`,
      `**/.cache/**`,
      `**/.git/**`,
      `**/.vscode/**`,
      `**/assets/**`,
      `**/docker/**`,
      `**/node_modules/**`,
      `**/public/**`,
      `**/reports/**`,
      `**/tests/**`,
      `**/static/**`,
      `**/fonts/**`,
      /\.(jpe?g|png|webp|webm|svg|mp4|gif|json|ya?ml|pdf)/,
    ],
  },
},
```

I would prefer this:

```js
module.exports = {
  resolve: `gatsby-source-filesystem`,
  options: {
    name: `leasot`,
    watch: false,
    paths: [
      `${__dirname}/plugins`,
      `${__dirname}/src`
    ],
    include: [
      /\.(jsx?|tsx?|md)/
    ],
    // OR
    extensions: ['js','jsx','ts','tsx','md']
  },
},
```

### Basic example

Use the suggested configuration from the mentioned plugin and edit a file multiple times.

### Motivation

- Nice to just parse contents initially
- Great for people that want to parse multiple directories
- Exclude files by extension
- Include specified files

**Comment by LekoArts** [comment]
Thank you for opening this!

This seems like an edge-case to me and specific to this transformer. There shouldn't be a case were we want users to disable the watching, it's a crucial feature for the smooth hot-reloading and good DX while running `gatsby develop`. You can get around the issue with the current plugin or by e.g. not using `__dirname` for the path.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by muuvmuuv** [comment]
Okay, seems reasonable. I'll then create a local plugin for myself to archieve this :)
