### ISSUE TITLE
GraphQL problem parsing query in gatsby@2.18.20 and later

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#21212]
After upgrading from `gatsby@2.18.19-jobs-api-v2.39` to `gatsby@2.18.20` (and all later versions) I get this error

>  ERROR #85915  GRAPHQL
There was a problem parsing the GraphQL query in file:
`src/components/Nav/index.js`

The [file in question](https://github.com/janosh/janosh.io/blob/master/src/components/Nav/index.js) looks pretty harmless. So maybe the changes introduced a bug? The [log states](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/CHANGELOG.md#21820-2020-01-09):

> **Bug Fixes**
gatsby: Webpack /_ webpackPrefetch/webpackPreload _/ comments causing a bug (#20403) (1b89b10)
**Features**
gatsby: Allow alternative import syntax for useStaticQuery (#20330) (17eaa72)

#20330 sounds like it might be related.

### Environment

<details>
<summary>`gatsby info --clipboard`</summary>

  System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.5
  npmPackages:
    gatsby: 2.18.20 => 2.18.20 
    gatsby-image: 2.2.40 => 2.2.40 
    gatsby-plugin-algolia: ^0.5.0 => 0.5.0 
    gatsby-plugin-catch-links: 2.1.25 => 2.1.25 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-feed-mdx: ^1.0.1 => 1.0.1 
    gatsby-plugin-google-analytics: 2.1.35 => 2.1.35 
    gatsby-plugin-lodash: ^3.1.16 => 3.1.20 
    gatsby-plugin-manifest: 2.2.41 => 2.2.41 
    gatsby-plugin-mdx: ^1.0.59 => 1.0.70 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-offline: 3.0.34 => 3.0.34 
    gatsby-plugin-react-helmet: 3.1.22 => 3.1.22 
    gatsby-plugin-sharp: 2.4.5 => 2.4.5 
    gatsby-plugin-styled-components: ^3.1.19 => 3.1.19 
    gatsby-remark-autolink-headers: ^2.1.19 => 2.1.24 
    gatsby-remark-code-titles: ^1.1.0 => 1.1.0 
    gatsby-remark-copy-linked-files: ^2.1.31 => 2.1.37 
    gatsby-remark-embed-video: 2.0.1 => 2.0.1 
    gatsby-remark-emojis: ^0.4.2 => 0.4.2 
    gatsby-remark-images: 3.1.44 => 3.1.44 
    gatsby-remark-katex: ^3.1.18 => 3.1.24 
    gatsby-remark-responsive-iframe: 2.2.32 => 2.2.32 
    gatsby-remark-smartypants: 2.1.21 => 2.1.21 
    gatsby-remark-sub-sup: ^1.0.0 => 1.0.0 
    gatsby-remark-vscode: ^2.0.1 => 2.0.1 
    gatsby-source-filesystem: 2.1.48 => 2.1.48 
    gatsby-transformer-sharp: 2.3.14 => 2.3.14 
    gatsby-transformer-yaml: 2.2.24 => 2.2.24 
</details>

**Comment by owen-riley** [comment]
Upgrading to `gatsby@2.18.20` also gives me this exact error on a file that simply exports a fragment. It looks something like:
```javascript
import { graphql } from 'gatsby';
export const query = graphql`
  fragment useMenuHook on Drupal_MenuLinkContent {
    entityId
  }
`;
```
If I move that fragment to any other file, it works. The error gives no stack trace or any other contextual information other than stating that `ERROR #85915  There was a problem parsing the GraphQL query in file: {filepath}`

**Comment by willpaige** [comment]
Yup, I'm getting what I expect as being a related issue. I'm unable to build with `gatsby 2.19.7` as `gatsby-source-contentful/src/fragments.js` isn't compatible. 

<img width="1099" alt="Screenshot 2020-02-08 at 10 39 29 am" src="https://user-images.githubusercontent.com/3032885/74083780-b8bd8c80-4a5f-11ea-89ef-bd24b97d493e.png">

**Comment by willpaige** [comment]
Fixed my issue by following this suggestion - https://github.com/gatsbyjs/gatsby/issues/16455#issuecomment-520710861

**Comment by vladar** [comment]
Here is an actual error (swallowed by gatsby catch block [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/query/file-parser.js#L442)):

```
TypeError: Cannot read property 'path' of undefined
    at followVariableDeclarations (janosh.io\node_modules\gatsby\dist\query\file-parser.js:330:47)
    at ExportSpecifier (janosh.io\node_modules\gatsby\dist\query\file-parser.js:346:31)
    at NodePath._call (janosh.io\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (janosh.io\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (janosh.io\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (janosh.io\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitMultiple (janosh.io\node_modules\@babel\traverse\lib\context.js:79:17)
    at TraversalContext.visit (janosh.io\node_modules\@babel\traverse\lib\context.js:138:19)
    at Function.traverse.node (janosh.io\node_modules\@babel\traverse\lib\index.js:84:17)
    at traverse (janosh.io\node_modules\@babel\traverse\lib\index.js:66:12)
    at NodePath.traverse (janosh.io\node_modules\@babel\traverse\lib\path\index.js:148:24)
    at ExportNamedDeclaration (janosh.io\node_modules\gatsby\dist\query\file-parser.js:342:16)
    at NodePath._call (janosh.io\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (janosh.io\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (janosh.io\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (janosh.io\node_modules\@babel\traverse\lib\context.js:112:16)
```

So it is definitely #20330 causing this.

CC @jfrolich

**Comment by jfrolich** [comment]
@vladar: can you share the exact file where this is happening? We can add a test and fix this situation.

**Comment by vladar** [comment]
@jfrolich The line causing the error is this: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/query/file-parser.js#L352

For some reason `binding` is undefined there

**Comment by wardpeet** [comment]
Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by jfrolich** [comment]
> @jfrolich The line causing the error is this: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/query/file-parser.js#L352
> 
> For some reason `binding` is undefined there

Sorry I meant the code that triggers this issue so it is possible to reproduce the error.

**Comment by vladar** [comment]
It is linked in the issue description: https://github.com/janosh/janosh.io/blob/master/src/components/Nav/index.js

**Comment by jfrolich** [comment]
Sorry I can't reproduce this on master. I thought the destructuring was the problem, but I created a test and it doesn't fail. Can you see if it works without destructuring for you (as that scenario is currently not covered in tests).

**Comment by janosh** [comment]
@jfrolich You mean without destructuring the `useStaticQuery` import? I just updated to `gatsby@2.19.16` and modified the file to this:

```js
import * as G from 'gatsby'
import React from 'react'
import { useScreenQuery } from 'hooks'
import DesktopNav from './Desktop'
import MobileNav from './Mobile'

export { NavLink } from './styles'

export default function Nav(props) {
  const data = G.useStaticQuery(G.graphql`
    {
      nav: file(base: { eq: "nav.yml" }) {
        nav: childrenNavYaml {
          title
          url
        }
      }
    }
  `)
  // ...
}
```

Still the same error.

**Comment by vladar** [comment]
So this was happening because of this line:

```js
export { NavLink } from './styles'
```

The new algorithm didn't account for this case.

**Comment by peterpunk** [comment]
In our case was completely different problem, the size of some image were too big making the memory issue. Thanks!

**Comment by kije** [comment]
I've encountered this issue in another case with `gastby@2.19.32`.
I have components written in typescript (using `gatsby-plugin-ts`, so "real" typescript not `babel-preset-typescript`) and I'm getting the error in components which also export typescript interfaces together with the component, even when there is no graphql query whatsoever.

Example:

```typescript
// src/components/test.tsx

import React from 'react';

interface TestProps {
    test: boolean;
}

const Test: React.FC<TestProps> = ({ test }) => (<p>This is { !test ? 'not' : '' } a test</p>);

export { Test, TestProps };
```

If I export the interface like this:
```typescript
// src/components/test.tsx

import React from 'react';

export interface TestProps {
    test: boolean;
}

const Test: React.FC<TestProps> = ({ test }) => (<p>This is { !test ? 'not' : '' } a test</p>);

export { Test };
```

everything works fine.

**Comment by city41** [comment]
I just upgraded one of my apps to `gatsby@2.24.14` and have hit this issue. I appear to have the same problem that @kije hit. 

I get this error

```
 ERROR #85915  GRAPHQL
[1] 
[1] There was a problem parsing the GraphQL query in file: /home/matt/dev/jumpclub/packages/web-client/src/play/playSlice.ts
```

But the file in question has no graphql in it at all. It does export a type along other things at the bottom of the file

```
type Foo = ...

export { stuff, Foo, otherStuff }
```

If I change it to

```
export type Foo = ...

export { stuff, otherStuff }
```

the issue goes away.

**Comment by jatinrupeja** [comment]
> Fixed my issue by following this suggestion - [#16455 (comment)](https://github.com/gatsbyjs/gatsby/issues/16455#issuecomment-520710861)

I am still getting the same issue. even after following the steps in that commit.
