### ISSUE TITLE
(www) Factor out <Layout> component in dot-org from most pages/templates

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21229]
## Summary

Move the `<Layout>` component so that instead of being imported in each page/template, it is imported only once in layouts/index.js:

```jsx
import Layout from '../components/layout`

export default ({ location, children, pageContext }) => {

  return <Layout location={location}>{children}</Layout>
}
```

## Motivation

This is needed to split gatsbyjs.org into themes (#19105) to make the site easier to work with. This allows us to not need to import the site-wide layout for specific section themes, which can cause errors. For example, `<Layout>` uses `<SiteMetadata>` which has a static query that refers to a field that shouldn't exist on the different sections.

## Considerations

* The brand guidelines section uses its own layout. Either refactor it to use the global layout or use logic in `layouts/index.js` use the correct layout for those pages.
* Packages have a special `PluginLibraryWrapper` that is applied in `layouts/index.js`. We'll need to do some refactoring
* The Layout component has a completely different rendering pattern where it renders as a modal, used only in the Site Showcase. This also needs some refactoring.
* The logic for the `enableScrollSync` prop needs to be moved elsewhere.

**Comment by crock** [comment]
This isn't really something that needs to be done in the default theme because it can be easily changed. The default theme only has a single layout component for simplicity's sake. Most users are going to want to create a layouts directory at `src/layouts` that contains all the different layouts their app will need. Then each page component imports only the layout it needs.

**Comment by tesseralis** [comment]
@crock this is specifically about the gatsbyjs.org website, not gatsby sites in general. I've updated the title to make this more clear.
