### ISSUE TITLE
how can I turn on the service worker using 'gatsby-plugin-offline'

### ISSUE THREAD

**Issue by getElementsByName** [gatsbyjs/gatsby#21222]
## Relevant information
- When I develop by `npm start develop` and `gatsby-plugin-offline`, service worker is not working. But it turns on serving **built static resources**

### Environment (if relevant)
perhaps `NODE_ENV=development`

### File contents (if changed)
- plugins: `gatsby-plugin-offline`
- command: `npm start develop`

**Comment by sidharthachatterjee** [comment]
The service worker registers only for production builds at the moment as documented in https://www.gatsbyjs.org/docs/add-offline-support-with-a-service-worker/#using-service-workers-in-gatsby-with-gatsby-plugin-offline

Thanks!
