### ISSUE TITLE
Make Sure All Requests Get Served with the Authorization Header at Browser Time

### ISSUE THREAD

**Issue by trueblood12** [gatsbyjs/gatsby#21237]
Hello. We're currently debugging an issue with Netlify support. When we password protect our site with Netlify's Password protection, then open our site in Safari, when we provide the password and click submit, the site is broken (JS errors and no JS execution). When we open up a new Safari tab, the site functions just fine. In all other browsers, the site functions just fine after providing the password. It's just an issue with Safari in the first tab.

Netlify support is looking into the issue on their end, but they have recently asked me to do the following:

_"What you need to do is make sure that all requests - by service worker, by browser, by API - all get served with the Authorization header that is set at browse time to indicate that the password has been entered."_

Our gatsby-config.js file just pulls in 'gatsby-plugin-netlify' without any configurations. I'm not exactly sure where to go to "make sure all requests get served with the Authorization header that is set at browser time". We're not setting any type of custom authorization headers in our code anywhere.

Any help would be greatly appreciated. Thanks!

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by trueblood12** [comment]
Hi. Thank you for your comment. Here is a minimal reproduction:

[https://heuristic-agnesi-7edf2e.netlify.com](https://heuristic-agnesi-7edf2e.netlify.com)

1. Upon going there, you'll be prompted for the Netlify password which is _header_
2. Upon successfully providing the password, the home page will appear... broken
3. Simply bring up another Safari tab and put the same URL above in the web address. On this new tab, you'll notice here that there are no JS errors

**Comment by trueblood12** [comment]
Hi, @LekoArts. I just wanted to follow up here to see if you were able to review the minimal reproduction provided, and what I might answer back to Netlify with? Your help is greatly appreciated!

**Comment by wardpeet** [comment]
Hey @trueblood12,

Sorry to keep you waiting but you should be able to add a plugin to add the new authorization token. Normally the authentication token should be cached with the service worker request.

More info on this:
https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-cacheable-response.CacheableResponsePlugin
