### ISSUE TITLE
How to not trigger RTE build from a simple commit on the branch which not "in production" / master ?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#21234]
Hello, 

I have a free plan on Gatsby Cloud. 

I'm already on 4 RTE builds / 20. 
I created a new branch to commit some code but don't want to build it or deploy.

How can disable or not trigged Gabtsy Cloud please?

Thanks

**Comment by LekoArts** [comment]
Please contact support@gatsbyjs.com for inquiries about Gatsby Cloud. Thanks!
