### ISSUE TITLE
"Invisible" prefetching of common.js from other sites according to Lighthouse Pagespeed

### ISSUE THREAD

**Issue by oskareke** [gatsbyjs/gatsby#21235]
##  Summary
![image](https://user-images.githubusercontent.com/2181306/73926348-63e70e00-48c7-11ea-8f30-795f9a195707.png)

When running a Lighthouse PageSpeed Insights test on any site in my network of Gatsby sites it tells me to "Avoid enormous network payload" and shows me a list of the common.js-file from every other site in the network. The sites are different language versions of the same site so I have "alternate"-tags like these: 

`<link data-react-helmet="true" rel="alternate" href="https://mylocalsite.co.uk" hreflang="en-GB">`

As well as a language-switcher using regular `<a href="">` links between the sites. This is the only way the sites are connected. I cannot see any requests between the sites being made in the network tab and I have no idea what is going on here but it's negative for my page speed. Any ideas what is going on here? Could share the real URL in DM if helpful.

### Environment (if relevant)

System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  npmPackages:
    gatsby: ^2.18.22 => 2.18.22 
    gatsby-image: ^2.0.26 => 2.2.38 
    gatsby-plugin-catch-links: ^2.0.2-beta.10 => 2.1.24 
    gatsby-plugin-feed: ^2.0.0-beta.4 => 2.3.26 
    gatsby-plugin-google-tagmanager: ^2.0.7 => 2.1.24 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.37 
    gatsby-plugin-netlify: ^2.0.0-beta.6 => 2.1.31 
    gatsby-plugin-nprogress: ^2.0.9 => 2.1.18 
    gatsby-plugin-offline: ^2.0.24 => 2.2.10 
    gatsby-plugin-preact: ^2.0.10 => 2.0.11 
    gatsby-plugin-react-helmet: ^3.0.8 => 3.1.21 
    gatsby-plugin-react-next: ^2.0.1-13 => 2.0.1-13 
    gatsby-plugin-remove-fingerprints: 0.0.2 => 0.0.2 
    gatsby-plugin-robots-txt: ^1.3.0 => 1.5.0 
    gatsby-plugin-sass: ^2.0.0-beta.10 => 2.1.27 
    gatsby-plugin-sharp: ^2.2.9 => 2.3.13 
    gatsby-plugin-sitemap: ^2.0.0-beta.4 => 2.2.25 
    gatsby-plugin-styled-components: ^3.0.0-beta.4 => 3.1.17 
    gatsby-plugin-twitter: ^2.0.11 => 2.1.18 
    gatsby-remark-copy-linked-files: ^2.0.9 => 2.1.36 
    gatsby-remark-images: ^3.0.6 => 3.1.42 
    gatsby-remark-prismjs: ^3.0.0-beta.7 => 3.3.30 
    gatsby-remark-responsive-iframe: ^2.0.9 => 2.2.31 
    gatsby-remark-smartypants: ^2.0.8 => 2.1.20 
    gatsby-source-airtable: 0.0.5 => 0.0.5 
    gatsby-source-filesystem: ^2.0.23 => 2.1.46 
    gatsby-transformer-remark: ^2.1.1-beta.7 => 2.6.48 
    gatsby-transformer-sharp: ^2.2.5 => 2.3.12 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
