### ISSUE TITLE
How to keep commit message on deploy from Gatsby Cloud to Netlify?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#21233]
Hello, 

I just switched to Gatsby Cloud. 

So the workflow was : 

```
Git commit -> Netlify Build -> Netlify Deploy -> (The commit message is visible from Netlify UI)
```

Now the workflow is : 

```
Git commit -> Gatsby Build from Gatsby Cloud (the commit is still here) -> Netlify Deploy -> (The commit message is not visible)
```

It said "No deploy messagee"

How can I solve that please?

**Comment by sidharthachatterjee** [comment]
@Steffi3rd Thanks for reporting this! I've gone ahead and communicated this to the Gatsby Cloud team. 

Closing this issue here for now since this is only for Gatsby OSS
