### ISSUE TITLE
StrictMode Error: Please update the following components: ScrollContext

### ISSUE THREAD

**Issue by master12** [gatsbyjs/gatsby#21231]
I copied this comment from #10179 since it was not really related to that particular error. However this does occur in StrictMode and it would be nice to get this resolved.

It was also posted in this issue #13676 but that has been closed without a resolution.

> I'm getting the following error with `StrictMode`:
> 
> ```
> Warning: Legacy context API has been detected within a strict-mode tree: 
>     in StrictMode (created by App)
>     in App
>     in _default
> 
> Please update the following components: ScrollContext
> 
> Learn more about this warning here:
> https://fb.me/react-strict-mode-warnings
> ```
> 
> It seems that `ScrollContext` is still using legacy context:
> https://github.com/gatsbyjs/gatsby/blob/bddfcbc978da93ae8c13e11622381c8c2a311e4f/packages/gatsby-react-router-scroll/src/ScrollBehaviorContext.js#L14-L16
> 
> Related:
> 
> > Reminder: mere presence of legacy context API in the tree puts everything below it onto a slower code path. It is worth migrating away from.
> > — https://twitter.com/dan_abramov/status/1097866569701621763

**Comment by sidharthachatterjee** [comment]
Happy to accept a PR fixing this!

**Comment by akshitkrnagpal** [comment]
@sidharthachatterjee 
Hey, I am just getting started with Gatsby. 
Can I work on this? 😄

**Comment by skarunakar** [comment]
@akshitkrnagpal  Are you working on this ??

**Comment by herecydev** [comment]
I've added a PR that should resolve this

**Comment by herecydev** [comment]
It's worth noting this plugin also calls `findDOMNode` which needs replacing to be "strict mode compliant"
