### ISSUE TITLE
Unable to run Gatsby in docker

### ISSUE THREAD

**Issue by asinha08** [gatsbyjs/gatsby#21246]
## Summary
Unable to run Gatsby in docker
## Relevant information
**My docker file looks like below**
```
FROM node:12.14.1-alpine
ENV NODE_ENV=production
WORKDIR /app
COPY ./package.json ./
RUN apk add --no-cache --virtual .gyp python make g++ && yarn --frozen-lockfile --non-interactive
COPY ./ ./
RUN yarn build
EXPOSE 9000
CMD ["yarn", "run", "serve"]
```

**My script in package.json looks like below**
```

"scripts": {
		"build": "node_modules/.bin/gatsby build",
		"develop": "node_modules/.bin/gatsby develop",
		"format": "prettier --write \"**/*.{js,jsx,json,md}\"",
		"start": "npm run develop",
		"serve": "node_modules/.bin/gatsby telemetry --disable && node_modules/.bin/gatsby serve",
		"clean": "node_modules/.bin/gatsby clean",
		"test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
	}

```

But when I build my image and run docker and visit http://localhost:9000/ on browser . browser do not show any content.

I get following message on browser

> This site can’t be reachedlocalhost refused to connect.
 Try:
 Checking the connection
 Checking the proxy and the firewall 
 ERR_CONNECTION_REFUSED

**If i run Gatsby without docker on my machine. The appilcation works fine.**

### Environment (if relevant)
docker

### File contents (if changed)

`gatsby-config.js`: N/A
`package.json`: N/A
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A
`gatsby-ssr.js`: N/A

**Comment by piyushkantm** [comment]
You can try this:

```
FROM node:lts as builder

WORKDIR /app
RUN chown node:node /app

USER node
COPY --chown=node:node . .
RUN yarn install
RUN yarn global add gatsby-cli
ENV GATSBY_TELEMETRY_DISABLED=1
RUN yarn build

FROM node:10-alpine
USER node
ENV GATSBY_TELEMETRY_DISABLED=1
COPY --from=builder --chown=node:node /app/ /app/
RUN rm -rf ./src
WORKDIR /app

EXPOSE 9000
CMD ["node_modules/.bin/gatsby", "serve", "-H", "0.0.0.0"]
```

Although for prod applications, using gatsby serve could not be a good idea. It is just to test how prod website will look..

**Comment by asinha08** [comment]
Thanks a lot @piyushkantm for your reply. What do you suggest I should do to run Gatsby application in prod.

**Comment by piyushkantm** [comment]
Basically use Netlify, But if your requirements are to use Docker, then use an nging server to host the static files...

**Comment by sidharthachatterjee** [comment]
@asinha08 Gatsby compiles your site into static assets which you can serve off of any CDN (Netlify, CloudFront, Fastly etc)

We wouldn't recommend using `gatsby serve` to serve your site in production. 

Thanks!

**Comment by asinha08** [comment]
Thanks a lot @piyushkantm and @sidharthachatterjee
