### ISSUE TITLE
How to write mdx plugin for inserting React component between paragraphs?

### ISSUE THREAD

**Issue by magnusarinell** [gatsbyjs/gatsby#21248]
## Summary

I would like information on where to start for writing a plugin for inserting a React element between paragraphs.

## Relevant information

Hi, I've been working with GatsbyJS a couple of years and it's great. My scenario is the following:

I have mdx pages with a lot of text content grouped in paragraphs (so the rendered page is a text page with a bunch of `<p>` tags with content. Now between every third paragraph or so I want to insert a React element.

I don't know where to start looking. `gatsby-plugin-mdx` has support for rehype plugins and remark plugins. Should I write one of these? I need to visit the entire ast or hast tree and for each third paragraph insert a React element. 

For another use case where I was not using mdx I have written a plugin which replaces inline code with some specific HTML elements and then in my layout I did some React.renderElement to "hydrate" these elements and add React functionality. Correct me if I'm wrong but isn't it possible with the remark and rehype plugin systems to directly insert React components into the ast/hast instead of hydrating manually?

### Environment (if relevant)

  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: 2.18.16 => 2.18.16 
    gatsby-image: 2.2.37 => 2.2.37 
    gatsby-link: 2.2.27 => 2.2.27 
    gatsby-plugin-catch-links: 2.1.21 => 2.1.21 
    gatsby-plugin-google-gtag: 1.1.19 => 1.1.19 
    gatsby-plugin-layout: 1.1.18 => 1.1.18 
    gatsby-plugin-manifest: 2.2.34 => 2.2.34 
    gatsby-plugin-mdx: 1.0.64 => 1.0.64 
    gatsby-plugin-netlify: 2.1.30 => 2.1.30 
    gatsby-plugin-react-helmet: 3.1.18 => 3.1.18 
    gatsby-plugin-sass: 2.1.26 => 2.1.26 
    gatsby-plugin-sharp: 2.3.10 => 2.3.10 
    gatsby-plugin-sitemap: 2.2.24 => 2.2.24 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.8 => 1.1.8 
    gatsby-remark-autolink-headers: 2.1.21 => 2.1.21 
    gatsby-remark-copy-linked-files: 2.1.33 => 2.1.33 
    gatsby-remark-images: 3.1.39 => 3.1.39 
    gatsby-remark-relative-images: 0.2.3 => 0.2.3 
    gatsby-source-filesystem: 2.1.43 => 2.1.43 
    gatsby-transformer-sharp: 2.3.9 => 2.3.9 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by sidharthachatterjee** [comment]
Thanks for the detailed issue! https://github.com/mdx-js/mdx might be a better place to ask.
