### ISSUE TITLE
warn The gatsby-plugin-mdx plugin has generated no Gatsby nodes. Do you need it?

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#21242]
## Description

I have `.mdx` files in my project but I have a warning on `gatsby develop` or `gatsby build`.

```
warn The gatsby-plugin-mdx plugin has generated no Gatsby nodes. Do you need it?
```

### Steps to reproduce

On `gatsby develop` or `gatsby build`

### Expected result

No warning 

### Actual result

Warning 

### Environment

 Binaries:
    Node: 10.16.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.0.0 => 2.15.24 
    gatsby-cli: ^2.4.16 => 2.7.50 
    gatsby-image: ^2.0.26 => 2.2.21 
    gatsby-plugin-emotion: ^4.0.1 => 4.1.7 
    gatsby-plugin-google-tagmanager: ^2.1.4 => 2.1.10 
    gatsby-plugin-manifest: ^2.2.13 => 2.2.18 
    gatsby-plugin-mdx: ^1.0.44 => 1.0.44 
    gatsby-plugin-netlify: ^2.0.12 => 2.1.15 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.1.8 
    gatsby-plugin-sharp: ^2.0.17 => 2.2.25 
    gatsby-plugin-sitemap: ^2.2.3 => 2.2.14 
    gatsby-source-filesystem: ^2.0.12 => 2.1.26 
    gatsby-transformer-sharp: ^2.1.10 => 2.2.17 
  npmGlobalPackages:
    gatsby-cli: 2.4.8

**Comment by sidharthachatterjee** [comment]
Are those files currently being processed by `gatsby-plugin-mdx`?

**Comment by Steffi3rd** [comment]
If I remove it from gatsby-plugin, all my `.mdx` files is 404.

**Comment by sidharthachatterjee** [comment]
Okay, in which case that means you _do_ have nodes being created. Do you have a minimal reproduction?

**Comment by Steffi3rd** [comment]
Maybe is there an "order" in the list of plugins ?

**Comment by LekoArts** [comment]
Please provide a [minimal reproduction][reproduction]. Thanks!

[reproduction]: https://gatsby.dev/reproduction
