### ISSUE TITLE
docs: overview features table lacks descriptions but shows up as clickable

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#21247]
## Summary

The overview table on the Features page here: https://www.gatsbyjs.org/features/ shows a focusable button for each section: Performance, Developer Experience, etc. with an info button next to it. This is misleading because the data we have for the table doesn't have any descriptions in it: https://github.com/gatsbyjs/gatsby/blob/master/docs/features/gatsby-features-specs.csv

### Motivation

Why should we document this and who will benefit from it?

The info in the table and the data represented should be in parallel.

## Steps to resolve this issue

I see two routes to fix this:

1. update the simple-evaluation-table component to make the buttons open up a row of details like the tables on these pages: https://www.gatsbyjs.org/features/jamstack/ and add a 1 sentence description to each row

2. update the text on the page to remove the content that says you can click on the row to see more details

I think the first option is more ideal, though the 2nd might be a good enough solution for now.

## Related issues

This came up in this issue originally: #16233

**Comment by b0nbon1** [comment]
Can I take this one @gillkyle?

**Comment by gillkyle** [comment]
That'd be great @b0nbon1!
