### ISSUE TITLE
Refactor (www): Use `nodes` in gatsbyjs.org code instead of `edges.node`

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21255]
## Summary

Since Gatsby v2.2.0, it's been possible to [use `nodes` instead of `edges.node`](https://github.com/gatsbyjs/gatsby/pull/20746/files) in GraphQL queries. All instances of:

```jsx
query {
  someNodes {
    edges {
      node {
        <fields>
      }
    }
}
```

can be replaced with:

```
query {
  someNode {
    nodes {
      <fields>
    }
  }
}
```

The code that iterates over these can also change from

```
someNode.edges.forEach({ node }) => {
 doSomething(node)
})
```

to:

```
someNode.nodes.forEach(node => {
  doSomething(node)
})
```

## Motivation

Code cleanliness of the gatsby website. Using up-to-date examples in our codebase can help guide people in showing good patterns, even if our docs can't update those examples due to back-compat issues.

**Comment by b0nbon1** [comment]
@tesseralis  Awesome, interested in contributing I'd like to grab it.

**Comment by tesseralis** [comment]
@b0nbon1 sure, go ahead!
