### ISSUE TITLE
Refactor (www, docs) Reorganize data YAML/JSON files used in gatsbyjs.org

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21258]
## Summary

Reorganize data used in www/ based on whether it's sourced in graphql or not, and 

## Steps

1. Move the YAML files in `docs` and associated files under `www/src/data`: `creators/`, `sites.yml`, `startes.yml`, `categories.yml`.
2. Rename the data directory to something like `source-data` and move out the files that aren't sourced in graphql into a new `data` directory (`sidebars/`, `features/`, `tags-docs.js`) 
3. Replace all the `gatsby-source-filesystem` calls in `gatsby-config` to the various data files to one call that just sources `source-data`
4. Update all references to these files in the docs and in imports.

## Motivation

Our data is kind of a mess right now, and the way we source them is cumbersome if we ever need to add a new data source (like for i18n). It doesn't really make sense for stuff like starters and sites to be under the `docs/` directory: they're lists that are relevant to the site, not general documentation.

**Comment by b0nbon1** [comment]
@tesseralis I'm interested in this one, I just need more clarification on:
- The files in the `YAML` files in the docs folder should they be moved to new folders; `source-data` and `data` in `www/src` ?

**Comment by tesseralis** [comment]
I'm going to close this for now since it turns out it's going to be a bigger hassle than it's worth (e.g. a lot of scripts look at the current location of `starters.yml`)
