### ISSUE TITLE
Refactor (docs, www): make a GraphqlEmbed MDX component to use in docs.

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21256]
## Summary

Our docs relating to GraphQL sometimes have [CodeSandbox samples](https://www.gatsbyjs.org/docs/graphql-reference/#limit) where viewers can edit their query. However, these pages are represented in the markdown as [raw iframes](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/graphql-reference.md) and are quite ugly:

```html
<iframe title="A basic query" src="https://711808k40x.sse.codesandbox.io/___graphql?query=%7B%0A%20%20site%20%7B%0A%20%20%20%20siteMetadata%20%7B%0A%20%20%20%20%20%20title%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&explorerIsOpen=false" width="600" height="400" loading="lazy"></iframe>
```

Thankfully, with the power of MDX, we can change that! We could create a component to process GraphQL queries:

```jsx
<GraphqlEmbed title="Using limit" query={`
{
  allMarkdownRemark(limit: 3) {
    totalCount
    edges {
      node {
        frontmatter {
          title
        }
      }
    }
  }
}
`}/>
```

The component would escape the query using `encodeURIComponent` and return the original iframe.

Also make sure to export the component in `www/src/gatsby-plugin-theme-ui/components.js` so it can be used globally without importing.

## Documentation

Change the documentation in [Adding embedded GraphQL examples](https://www.gatsbyjs.org/contributing/docs-contributions/#adding-embedded-graphql-examples) to refer to the new component.

## Motivation

Clarity, reducing error, make it easier to create new interactive GraphQL elements in docs.

**Comment by akshitkrnagpal** [comment]
Is this taken?
Can I work on this?

**Comment by tesseralis** [comment]
@akshitkrnagpal go ahead!

**Comment by tesseralis** [comment]
@akshitkrnagpal, it seems like @dhausser has already assigned themselves to it. @dhausser are you still working on this?

**Comment by dhausser** [comment]
@akshitkrnagpal feel free to grab it, I didn't get a chance to start working on it yet.

**Comment by tesseralis** [comment]
@akshitkrnagpal it's all yours!

**Comment by akshitkrnagpal** [comment]
Hi @tesseralis 
Thanks for assigning the issue to me.

I found that a different subdomain of CodeSandbox has been used in [sourcing-data.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes/sourcing-data.md). Therefore I have added `url` prop to the `GraphiQLEmbed` component.

I have created a draft PR. I also found two problems that are preventing to achieve the desired result. I am investigating them and will create a separate issue if necessary.

**Comment by mujeex** [comment]
@tesseralis Hey! Just went over your conversations in this PR and noticed the changes are still yet to be completed. With a little bit of hand holding, I'd be more than happy to pick where you guys left off. Thanks.

**Comment by EmilioCastilloW** [comment]
Hi I want to make my first contribution to Gatsby. Can I work on it? What changes are still yet to be completed?

**Comment by EmilioCastilloW** [comment]
Hi! I want to make my first contribution to Gatsby, what is the status of this issue?, What changes are still yet to be completed?

**Comment by remorses** [comment]
I made a mini graphiql component to document graphql queries, it has also auto completion
https://github.com/remorses/mini-graphiql-playground

**Comment by LekoArts** [comment]
See: https://github.com/gatsbyjs/gatsby/pull/25629#issuecomment-689536774
