### ISSUE TITLE
[gatsby-source-graphql] createResolvers for array of images not working

### ISSUE THREAD

**Issue by secretlifeof** [gatsbyjs/gatsby#21272]
## Description

I am trying to create a file node in gatsby-node.js. It works for single images but not arrays of images, and do not understand why. GraphQL API is Strapi, and I use gatsby-source-graphql to get the data.

### Steps to reproduce
```
// gatsby-node.js
createResolvers({
    STRAPI_UploadFile: {
      imageFile: {
        type: `File`,
        resolve(source, args, context, info) {
          // if (Array.isArray(source)) {
          //   source.map(content => console.log("content", content))
          // }

          if (source && typeof source === "object" && source.url == undefined) {
            console.log("source.id: ", source.id)
            // for (const key of Object.keys(context)) {
            //   const field = context[key]
            //   console.log("key: field: ", key + ":" + field)
            // }
          }

          return createRemoteFileNode({
            url: `${source.url}`,
            store,
            cache,
            createNode,
            createNodeId,
            reporter,
          })
        },
      },
    },
})
```
It returns the correct source.id but source.url is returned as undefined. With single images the correct src url is returned. The __typename for single and multiple images are the same.

GraphQL Query:
```
query {
  pages(where: { title_contains: "home" }) {
    content {
      __typename
      ... on ComponentPageArticle {
        article {
          cover {
            __typename
            url
          }
          gallery {
            __typename
            url
          }
        }
      }
    }
  }
}
```

Returned from Query:
```
"content": [
  {
    "__typename": "ComponentPageArticle",
    "article": {
      "cover": {
        "__typename": "UploadFile",
        "url": "https://fra1.cdn.digitaloceanspaces.com/hauptmannhaus.de_dev/4a389b2dc464419882b7%22%20%22.jpg"
      },
      "gallery": [
        {
          "__typename": "UploadFile",
          "url": "https://fra1.cdn.digitaloceanspaces.com/139572624eaaa58d660c0f958bdf%22%20%22.jpg"
        },
        {
          "__typename": "UploadFile",
          "url": "https://fra1.cdn.digitaloceanspaces.com/24eaaa58d66%22%20%22.jpg"
        }
      ]
    }
  },
```

### Expected result
imageFile nodes are created correctly for single images and an array of images.

### Actual result
Array of images with the same __typename as single images return src url undefined.

### Environment
  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.18.12 => 2.19.12 
    gatsby-image: ^2.2.34 => 2.2.40 
    gatsby-plugin-chakra-ui: ^0.1.2 => 0.1.2 
    gatsby-plugin-emotion: ^4.1.21 => 4.1.22 
    gatsby-plugin-manifest: ^2.2.31 => 2.2.41 
    gatsby-plugin-offline: ^3.0.27 => 3.0.34 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.22 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-sharp: ^2.3.5 => 2.4.5 
    gatsby-source-filesystem: ^2.1.40 => 2.1.48 
    gatsby-source-graphql: ^2.1.33 => 2.1.33 
    gatsby-source-strapi: ^0.0.10 => 0.0.10 
    gatsby-transformer-sharp: ^2.3.7 => 2.3.14 
  npmGlobalPackages:
    gatsby-cli: 2.8.27

### Question
Why is the id returned but not the source url? How can I change gatsby-node.js to make it work?

**Comment by vladar** [comment]
Given what I see your field is defined as a single file instance (`File`) not a list of files (`[File]`):

```
imageFile: {
        type: `File`,
        resolve(source, args, context, info) {
```

You should not even receive `source` as an array there. I feel that I might be missing something or there is not enough information in your issue description. Can you provide a bit more context and ideally a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)?

**Comment by secretlifeof** [comment]
This was caused due an embarrassing fault on my part. While make a reproduction I noticed the error came from not adding url to all the GraphQL queries, so that createRemoteFileNode could not find the URL.
@vladar I am still thankful for your fast answer
