### ISSUE TITLE
Page Content not loaded

### ISSUE THREAD

**Issue by ovidiumihaibelciug** [gatsbyjs/gatsby#21279]
## Description
Hello, I found this weird bug and I'm not sure if it's a problem with Gatsby or it's my browser

### Steps to reproduce
When I right click and View Page source on a website made with Gatsby the content doesn't appear on the source, but after I refresh it appears as shown in the videos below.

https://www.loom.com/share/73c52572693048f898deb7b32342d329

https://www.loom.com/share/0ae9024c4b99476ea3d91369b60ccc55

### Expected result
I expected the content of the website without having to refresh.

### Actual result
I had to refresh to see the content.

**Comment by davwheat** [comment]
Pretty sure this is expected behaviour because of how Gatsby loads pages via a service worker but I'll let someone more experienced decide if that's the case :P

**Comment by sidharthachatterjee** [comment]
This is expected behaviour due to our use of `gatsby-plugin-offline`

Read more at https://www.gatsbyjs.org/packages/gatsby-plugin-offline/#empty-view-source-and-seo

Thanks!
