### ISSUE TITLE
SEO for Recipes needs improvement

### ISSUE THREAD

**Issue by laurieontech** [gatsbyjs/gatsby#21277]
## Summary

Since the recipes section of the docs was refactored, it appears that SEO has suffered.
For example, searching "Gatsby local font" on Google does not surface the [adding a local font recipe](https://www.gatsbyjs.org/docs/recipes/styling-css#adding-a-local-font) but it does list the associate GitHub issue.

### Motivation

This section of the docs is information-rich and we want it to be discoverable.

## Steps to resolve this issue

This deserves some research, but it appears the lack of "Gatsby" in titles may contribute to the SEO challenges. Perhaps the title of each page needs to include "Gatsby"? This would be preferable to each recipe header including that keyword.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by marcysutton** [comment]
Steps to complete this issue, which is focused on search engine optimization of individual recipes, which are listed on category pages:

- [ ] Meet with @hashimwarren to discuss strategies for improving SEO without being overly repetitive (especially in a recipe page's Table of Contents)
- [ ] Search for each recipe on Google and record results in a spreadsheet
- [ ] Make improvements in a PR to improve SEO of individual recipes
- [ ] Set a calendar reminder to revisit the searches in 30 days to see if things improved

**Comment by hashimwarren** [comment]
We currently use a tool to track the performance of our pages in Google search. 

I can add the queries we want to monitor and it will show us performance over time - without us having the check by hand or set reminders.

Let's talk when we meet.

**Comment by marcysutton** [comment]
Migrated to Clubhouse internally, so I'm going to close this issue as it's something an internal team should tackle.
