### ISSUE TITLE
gatsby-plugin-sharp caches files/data in both the public and .cache directories which can create confusion when the public folder is deleted but not .cache

### ISSUE THREAD

**Issue by mplis** [gatsbyjs/gatsby#2128]
I ran into a problem today that I was discussing in the reactiflux chat room and @KyleAMathews asked me to write up my story. Here's what I believe are the minimal steps required to reproduce my problem. Also, I'm on `gatsby@1.9.32`.

1. `gatsby new some-project && cd some-project`
2. `npm install --save gatsby-source-filesystem gatsby-transformer-sharp`
3. Create `src/images/` folder and add some images into it
4. Set up `gatsby-config.js` to look like this:
```
module.exports = {
    plugins: [
        `gatsby-plugin-react-helmet`,
        {
            resolve: 'gatsby-source-filesystem',
            options: {
                name: 'images',
                path: `${__dirname}/src/images`
            }
        },
        'gatsby-transformer-sharp',
    ]
};

```
5. Add this to `src/pages/index.js` (this is required for `public/static/` to be populated with images)
```
export const pageQuery = graphql`
    query ImageQuery {
        allFile {
            edges {
                node {
                    id
                    childImageSharp {
                        responsiveSizes {
                            src
                        }
                    }
                }
            }
        }
    }
`;
```
6. `npm run build`
    * Observe that `public/static/` is populated with files generated by `gatsby-transformer-sharp`
7. Rename `src/pages/page-2.js` to something else like `another-page.js`
8. `npm run build`
    * Observe that `public/static/` is still populated but that `public/page-2/` still exists even though we renamed the file
9. `rm -rf public && npm run build`
    * I did this in order to remove `public/page-2/` from my build
    * Observe that `public/page-2/` is now gone, _**but `public/static/` is now empty**_. This results in my page breaking if I try to use the images I queried for with `ImageQuery`.
    * I need to run `rm -rf .cache public && npm run build` to fix it

I wouldn't have run into this issue if I had deleted `.cache/` in addition to `public/` before rebuilding, but it was an easy thing to miss and not necessarily intuitive. I don't know exactly where the bug is, but there are a couple things that seem off, like `public/page-2/` still be present after `page-2.js` was deleted and `public/static/` being empty after deleting `public/`, but not deleting `.cache/`, and rebuilding.

**Comment by KyleAMathews** [comment]
One possible fix is to always write static files to .cache and then copy them to public so that way deleting the public folder has no effect.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
