### ISSUE TITLE
Adding any gatsby dependency to a plugin causes build to fail

### ISSUE THREAD

**Issue by bradgarropy** [gatsbyjs/gatsby#21299]
## Description

My end goal is to create my own blog theme which provides a `gatsby-config.js` file that loads and parses `markdown` files.

Using the [`using-multiple-local-plugins`][local] as a starting point, I added the `gatsby-plugin-twitter` as a dependency to the `gatsby-plugin-console-log-a` directory. After doing so, `npm start` fails to build the `gatsby-site-using-local-plugins`.

### Steps to reproduce

1. Copy the [`using-multiple-local-plugins`][local] to your machine.
2. Install `gatsby-plugin-twitter` in the `gatsby-plugin-console-log-a` plugin.
```shell
cd gatsby-site-using-local-plugins/plugins/gatsby-plugin-console-log-a
npm i gatsby-plugin-twitter
```
3. Add a `gatsby-config.js` file to `gatsby-plugin-console-log-a` which uses `gatsby-plugin-twitter`.
```javascript
// gatsby-site-using-local-plugins/plugins/gatsby-plugin-console-log-a/gatsby-config.js

module.exports = {
  plugins: ["gatsby-plugin-twitter"],
}
```
4. Attempt to build the `gatsby-site-using-local-plugins` and observe the error.
```shell
$ npm start

> using-multiple-local-plugins@0.1.0 start D:\projects\gatsby-theme-issue\gatsby-site-using-local-plugins
> npm run develop


> using-multiple-local-plugins@0.1.0 develop D:\projects\gatsby-theme-issue\gatsby-site-using-local-plugins
> gatsby develop


 ERROR #10226  CONFIG

Couldn't find the "gatsby-plugin-twitter" plugin declared in "D:\projects\gatsby-theme-issue\gatsby-site-using-local-plugins\plugins\gatsby-plugin-console-log-a\gatsby-config.js".

Tried looking for an installed package in the following paths:
 - D:\projects\gatsby-theme-issue\gatsby-site-using-local-plugins\node_modules\gatsby\dist\bootstrap\load-themes\node_modules\gatsby-plugin-twitter
 - D:\projects\gatsby-theme-issue\gatsby-site-using-local-plugins\node_modules\gatsby\dist\bootstrap\node_modules\gatsby-plugin-twitter
 - D:\projects\gatsby-theme-issue\gatsby-site-using-local-plugins\node_modules\gatsby\dist\node_modules\gatsby-plugin-twitter
 - D:\projects\gatsby-theme-issue\gatsby-site-using-local-plugins\node_modules\gatsby\node_modules\gatsby-plugin-twitter
 - D:\projects\gatsby-theme-issue\gatsby-site-using-local-plugins\node_modules\gatsby-plugin-twitter
 - D:\projects\gatsby-theme-issue\node_modules\gatsby-plugin-twitter
 - D:\projects\node_modules\gatsby-plugin-twitter
 - D:\node_modules\gatsby-plugin-twitter
```

Minimal reproduction can be found in this repository on the `repro` branch:  
[gatsby-theme-issue](https://github.com/bradgarropy/gatsby-theme-issue/tree/repro)

The `master` branch represents the clean state of the [`using-multiple-local-plugins`][local] example.

This PR shows the only changes I made to cause the error.
[add gatsby-plugin-twitter dependency. issue reproduced.][pr]

### Expected result

The `gatsby-site-using-local-plugins` build should succeed, and I should see the `Twitter` JavaScript loaded onto the page.

### Actual result

Build failed with the above result.

### Environment

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Binaries:
    Node: 12.13.1 - D:\nodejs\node.EXE
    npm: 6.13.7 - D:\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.12 => 2.19.12
    gatsby-image: ^2.2.34 => 2.2.40
    gatsby-plugin-manifest: ^2.2.31 => 2.2.41
    gatsby-plugin-offline: ^3.0.27 => 3.0.34
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.22
```

[local]: https://github.com/gatsbyjs/gatsby/tree/master/examples/using-multiple-local-plugins
[pr]: https://github.com/bradgarropy/gatsby-theme-issue/pull/1

**Comment by vnugent** [comment]
I'm also having the same issue.

main project
```
gatsby develop

 ERROR #10226  CONFIG

Couldn't find the "gatsby-plugin-material-ui" plugin declared in "/projects/git/leanstack/gatsby-mdx-editor/gatsby-config.js".
```

gatsby-plugin-material-ui is indeed included in my plugin project.
```
# package.json

  "dependencies": {
    "gatsby-plugin-material-ui": "^2.1.6",
     ...
   }
```

**Comment by gael-boyenval** [comment]
same here, is there a workaround pls ?

**Comment by aletisunil** [comment]
Same problem, Any help would be appreciated

**Comment by vnugent** [comment]
I think at the moment it's not possible to build a plugin that has other plugins as dependencies since plugin doesn't have a gatsby-config.js file.  I ended up building a theme instead.

**Comment by gcko** [comment]
I'm running into this issue while using `docker-compose up`, specifically "gatsby-plugin-extract-schema". The plugin is in  package.json and is indeed downloaded and added to `node_modules/gatsby-plugin-extract-schema`. I have verified by running `docker-compose build --no-cache && docker-compose run web sh`, and indeed the directory is there. In addition, running `npx gatsby develop --host 0.0.0.0 --port 8000` directly in the container works just fine. running that same command using within the `Dockerfile` using `docker-compose up` fails.

**Comment by Kidist-Abraham** [comment]
Same here, with `Couldn't find the "gatsby-plugin-material-ui" plugin declared in "project/gatsby/gatsby-config.js".` while it is declared in `gatsby-config.js`
