### ISSUE TITLE
Add a tag in the Link tag to stop the browser from pre-caching it. 

### ISSUE THREAD

**Issue by asah27** [gatsbyjs/gatsby#21298]
## Summary

When we load a Gatsby site, it checks all the Link tags on the pages and pre-cache's it for better user experience. But what if I know according to some stats that this page does not have very frequent visitors and what to stop the browser from pre-caching it? The page might contain a lot of data and I might not want to do that.

### Example
This would involve some addition to the Link tag's implementation. Would love to work on it.

### Motivation
While working on a website and presenting the working and idea behind Gatsby to my team at work and this came up as doubt and this edit was suggested. I thought this would be a great way to join the Gatsby community and appreciate what a wonderful product they have built.

I'd also like to take on this task. I created this issue because according to the contributing guideline, this is necessary for discussion before implementation.

**Comment by sidharthachatterjee** [comment]
@asah27 Thanks for opening this! We don't currently support opting out of Link prefetching but I could see this being valuable as discussed in https://github.com/gatsbyjs/gatsby/issues/20568

Perhaps we could add a `prop` to the Link component like `prefetch={false}` (which defaults to true) 

Happy to accept a PR!
