### ISSUE TITLE
watch files outside of `gatsby-config.js`

### ISSUE THREAD

**Issue by ColdFire87** [gatsbyjs/gatsby#21290]
## Summary

I need Gatsby to pick up changes made to files imported by `gatsby-config.js`

## Relevant information

A simple `gatsby-config.js` file looks like this:

```javascript
module.exports = {
  siteMetadata: {
    title: "My Site",
    description: "Cool blog",
  },
  plugins: [
    // ...
  ],
};
```

I want to put `siteMetadata` into a separate json file like so:

```json
{
  "title": "My Site",
  "description": "Cool blog",
}
```

```javascript
const siteMetadata = require("./content/siteMetadata")

module.exports = {
  siteMetadata,
  plugins: [
    // ...
  ],
};
```

The reason for that is so I can make `content/siteMetadata.json` available for editing
in a CMS like Forestry.io or NetlifyCMS.

The problem I am facing is that by taking this data into an external file (`siteMetadata.json`), Gatsby (webpack) doesn't pick up the changes for HMR. I am not sure how to configure webpack to watch files in `/content/**/*.json`. I don't know if I need to update `devServer` settings, `watch` settings or HMR settings. I tried using a `filewatcherPlugin` but I got this error:

> ConcurrentCompilationError: You ran Webpack twice. Each instance only supports a single concurrent compilation at a time.

Here is my attempt in `gatsby-node.js`:

```javascript
const filewatcherPlugin = require(`filewatcher-webpack-plugin`);

// Configure webpack options for Gatsby
exports.onCreateWebpackConfig = ({
  stage,
  actions,
}) => {
  if(stage === 'develop') {
    // Watch config files outside of `gatsby-config.js`
    actions.setWebpackConfig({
      plugins: [
        new filewatcherPlugin({
          watchFileRegex: [
            'content/siteMetadata.json',
          ]
        })
      ],
    })
  }
}
```

### Environment (if relevant)

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 AMD FX(tm)-8350 Eight-Core Processor           
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7 
    gatsby-core-utils: ^1.0.28 => 1.0.28 
    gatsby-image: ^2.2.40 => 2.2.40 
    gatsby-plugin-emotion: ^4.1.22 => 4.1.22 
    gatsby-plugin-feed: ^2.3.27 => 2.3.27 
    gatsby-plugin-manifest: ^2.2.41 => 2.2.41 
    gatsby-plugin-mdx: ^1.0.70 => 1.0.70 
    gatsby-plugin-netlify-cms: ^4.1.38 => 4.1.38 
    gatsby-plugin-offline: ^3.0.34 => 3.0.34 
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22 
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5 
    gatsby-plugin-theme-ui: ^0.3.0 => 0.3.0 
    gatsby-remark-code-titles: ^1.1.0 => 1.1.0 
    gatsby-remark-copy-linked-files: ^2.1.37 => 2.1.37 
    gatsby-remark-images: ^3.1.44 => 3.1.44 
    gatsby-remark-responsive-iframe: ^2.2.32 => 2.2.32 
    gatsby-remark-smartypants: ^2.1.21 => 2.1.21 
    gatsby-source-filesystem: ^2.1.48 => 2.1.48 
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wardpeet** [comment]
If you import it inside your react code it should HMR. How does these files get imported?

**Comment by ColdFire87** [comment]
```javascript
const siteMetadata = require("./content/siteMetadata")

module.exports = {
  siteMetadata,
  plugins: [
    // ...
  ],
};

**Comment by ColdFire87** [comment]
I took a different approach to fix the issue and put data in `yaml` files instead.
I am loading them using `gatsby-source-filesystem` & `gatsby-transformer-yaml`, then source the data in my pages/components using GraphQL. Updating the yaml files trigger HMR so it works fine this way.

**Comment by vicentereig** [comment]
Thanks @ColdFire87 for the hint. In our case, we needed to trigger HMR with a config file in the root of the project. Adding another instance of `gatsby-source-filesystem` to _watch_ it did the trick for us:

```js
   // gatsby-config.js
  // ..  
   {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'fflags',
        path: `${__dirname}/localFeatureFlags.json`,
      },
    },
 // ...
```
