### ISSUE TITLE
Include Share Action for Docs and Blog

### ISSUE THREAD

**Issue by dillionmegida** [gatsbyjs/gatsby#21297]
## Summary

This feature makes it easy to share post and docs in Gatsby with other applications like Twitter and Facebook.

### Motivation

Many content-based websites makes it easy for users to share contents with their audience. I noticed Gatsby didn't have such, hence my request.

I'd also like to take on this task. I created this issue because according to the contributing guideline, this is necessary for discussion before implementation.

**Comment by sidharthachatterjee** [comment]
@dillionmegida Hey! Thank you so much for being thoughtful and opening this issue!

> Many content-based websites makes it easy for users to share contents with their audience. I noticed Gatsby didn't have such, hence my request.

I think most devices (phones and tablets) natively support sharing buttons for the stuff you mentioned. We don't think adding these to the site is necessary _per se_ 🙂 

Thank you once again! 💜

**Comment by dillionmegida** [comment]
Thanks for the feedback.

I've never noticed a sharing button on the platform on my device. Are you referring to navigator.share() API or something else?

Anytime I wanted to share from Gatsby, I'd have to copy the link and paste it wherever. I've never seen a direct share action.

 Please, could you explain it more to me.

**Comment by dillionmegida** [comment]
Hi @sidharthachatterjee please check out my last response concerning the pull request.

**Comment by dillionmegida** [comment]
Hi @sidharthachatterjee 

Sorry to bother you, my issue has been left unattended to. I'd appreciate if you give it more consideration and please, refer to this comment - https://github.com/gatsbyjs/gatsby/issues/21297#issuecomment-585461455

Looking forward to hearing from you.
