### ISSUE TITLE
gatsby-background-image - no blur effect with art direction / image array

### ISSUE THREAD

**Issue by as703** [gatsbyjs/gatsby#21307]
## Description

I'm using gatsby-background-image to generate a hero image. As per the instructions regarding Art Direction, I have two images (one desktop and on mobile) that I source using graphql and define in an array with a media key per image which is then passed to the fluid prop of background image.

The correct (i.e. responsive to viewing port) image is displayed but there is no blur-up while the image loads - just a gap of a second or two.

If I just pass one of the images to background-images (rather than the array) the image is displayed with the usual blur-up effect.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

Please see: https://github.com/as703/gatsby-test.git

using the index page, if you change the background-image fluid prop to 'sources' there is no blur. If you give it an image directly (e.g. 'data.desktopHero.childImageSharp.fluid') there is a blur effect.

Code from example:

import * as React from 'react'
import { graphql} from 'gatsby'
import BackgroundImage from 'gatsby-background-image'

export const query = graphql`
  query {
    mobileHero: file(relativePath: { eq: "mobileHero.jpg" }) {
      childImageSharp {
        fluid(maxWidth:800, quality: 100) {
          ...GatsbyImageSharpFluid
        }
      }
    }
    desktopHero: file(relativePath: { eq: "desktopHero.png" }) {
      childImageSharp {
        fluid(maxWidth:1600, quality: 100) {
          ...GatsbyImageSharpFluid
        }
      }
    }
  }
`

export default ({data}) => {

  const sources = [
    {
      ...data.mobileHero.childImageSharp.fluid,
      media: `(max-width: 767px)`,
    },
    {
      ...data.desktopHero.childImageSharp.fluid,
      media: `(min-width: 768px)`,
    },
  ];

  return (
    <div>

    <BackgroundImage fluid={sources} style={{width:'100vw',
                                            height:'500px',
                                            backgroundPosition: 'left top'}}/>

    </div>

  )
}

### Expected result

Art directed images from an array should blur up while loading in background-image

### Actual result

The correct image (as defined by media key) loads from the sources array but there is no blur effect.

### Environment

  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    npm: 6.13.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /Users/Alasdair/anaconda/bin/python
  Browsers:
    Firefox: 72.0.2
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7 
    gatsby-background-image: ^0.9.14 => 0.9.14 
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5 
    gatsby-source-filesystem: ^2.1.48 => 2.1.48 
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14 
  npmGlobalPackages:
    gatsby-cli: 2.7.53

Any insight would be greatly appreciated.

**Comment by timhagn** [comment]
Closing this issue, as `gatsby-background-image` isn't a core module. 
Am tackling it further in the linked issue over at the `gbi` repo.
