### ISSUE TITLE
Dark color scheme for favicon & apple-touch-icons with gatsby-plugin-manifest

### ISSUE THREAD

**Issue by qinyiyao** [gatsbyjs/gatsby#21308]
## Summary

Some websites are now supporting dark favicon & app icon when the device color scheme is dark. Some [tutorials](https://jross.me/updating-your-website-favicon-dynamically-with-dark-mode/) suggest switching files sources with head script. You will need to refresh and empty cache multiple times to reproduce the effect. 

### Basic example

[nytimes.com](https://www.nytimes.com): In Safari, both the favicon and apple-touch-icon change based on system color scheme. 
 
<img width="120" alt="Screen Shot 2020-02-09 at 3 39 42 AM" src="https://user-images.githubusercontent.com/6311717/74101410-5b245100-4aee-11ea-8fdf-d5fbdc369e85.png">

<img width="120" alt="Screen Shot 2020-02-09 at 3 39 21 AM" src="https://user-images.githubusercontent.com/6311717/74101412-5c557e00-4aee-11ea-9dbc-f89a710cd6ca.png">

_More examples needed._

### Motivation

Just a little visual improvement.

**Comment by sidharthachatterjee** [comment]
Great idea!
