### ISSUE TITLE
Eslint stopped working

### ISSUE THREAD

**Issue by hugofabricio** [gatsbyjs/gatsby#21300]
My eslint stopped working on my computer when I don't have the configuration file at the root, I tested it on other computers the problem is the same, is anyone experiencing this?

<img width="1366" alt="Screen Shot 2020-02-08 at 17 27 54" src="https://user-images.githubusercontent.com/425678/74091648-5cc32a00-4a98-11ea-834f-612f0398f5d2.png">

**Comment by Js-Brecht** [comment]
This doesn’t really apply to Gatsby.  It’s a [`vscode-eslint`](https://github.com/microsoft/vscode-eslint/issues) thing

**Comment by sidharthachatterjee** [comment]
Indeed. Like @Js-Brecht mentioned, you'll probably want to configure [vscode-eslint](https://github.com/microsoft/vscode-eslint/issues) correctly. 

Thanks!

**Comment by hugofabricio** [comment]
It is set up correctly, I tested it on 6 different computers that worked normally and suddenly stopped, I was only able to solve it by placing .eslintrc.js at the root of the project.

**Comment by Js-Brecht** [comment]
@hugofabricio You will be able to get more help for that if you file an issue at the [vscode-eslint](https://github.com/microsoft/vscode-eslint/issues) repository. Gatsby doesn't change how your IDE handles `eslint`.
