### ISSUE TITLE
Why does any query wrapped in graphql-tag get validated at build time?

### ISSUE THREAD

**Issue by cif** [gatsbyjs/gatsby#21304]
My team is working on a "hybrid" web client, which requires queries to be run against a remote endpoint/schema at runtime (Auth, persona, account info), along side queries intended to run against static build data sources (Image, CMS, config).

@jlengstorf put together a seemingly clear approach to this https://github.com/jlengstorf/gatsby-with-apollo, however it seems as of gatsby@2.19.12, any of the runtime queries that are wrapped in the `graphql-tag` default export (i.e. not against gatsby data sources) are being validated against those sources and failing builds like so: 

```
GraphQLDocumentError: Cannot query field "getCustomer" on type "Query".
        at /Users/benipsen/Development/moonshot-client/src/providers/AuthProvider.tsx:2:3
```

An easy-but-not-ideal workaround was to fork graphql-tag and publish a new package https://www.npmjs.com/package/not-graphql-tag then use that to generate `DocumentNode` for Apollo `useQuery` hook.  

I can see why this is challenging given tapping values passed to `useStaticQuery` and gatsby tools are already AST parsed, but tapping this module at build time should be reconsidered IMO. 

Originally opened issue on the example here: https://github.com/jlengstorf/gatsby-with-apollo/issues/8

### Environment (if relevant)

System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.87
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.12 => 2.19.12
    gatsby-image: ^2.2.40 => 2.2.40
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1
    gatsby-plugin-google-tagmanager: ^2.1.25 => 2.1.25
    gatsby-plugin-manifest: ^2.2.41 => 2.2.41
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-offline: ^3.0.34 => 3.0.34
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5
    gatsby-plugin-svgr-loader: ^0.1.0 => 0.1.0
    gatsby-plugin-typegen: ^0.2.0 => 0.2.0
    gatsby-plugin-typescript: ^2.1.27 => 2.1.27
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-contentful: ^2.1.85 => 2.1.85
    gatsby-source-filesystem: ^2.1.48 => 2.1.48
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14

**Comment by vladar** [comment]
I just tried https://github.com/jlengstorf/gatsby-with-apollo with the latest Gatsby and it builds fine for me. Can you share the steps to reproduce this?

**Comment by cif** [comment]
Interesting, could a plugin be failing the build?  As you can see, we're using many. I'd have to eliminate those one by one or dig into source.  Unfortunately I can't share the repo experiencing the problem. 

Given you were able to run that example seems clear this isn't a core Gatsby issue. I'll update this issue if I ever I ever happen across the problem but going to close it out. Thanks a lot for looking into this!
