### ISSUE TITLE
text in tutorial referrs to nvm, not npm

### ISSUE THREAD

**Issue by chris-s-friedman** [gatsbyjs/gatsby#21301]
## Summary

The code block under [Set default node.js version](https://www.gatsbyjs.org/tutorial/part-zero/#set-default-nodejs-version) refers to `nvm`, not `npm`.

### Motivation

To make the code block refer to the correct command

### Draft the doc

```shell
npm install 10
npm use 10
```
### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by KyleAMathews** [comment]
`nvm` is correct. It's a tool to let you change node versions.

https://github.com/nvm-sh/nvm

**Comment by KyleAMathews** [comment]
Thanks for contributing!

**Comment by chris-s-friedman** [comment]
oof I feel so foolish for not googling that first 🤦‍♂ Thanks!

**Comment by muescha** [comment]
this issue point out that the doc is missing a short sentence here to explain what is the `nvm` tool
