### ISSUE TITLE
SASS changes are not being detected.

### ISSUE THREAD

**Issue by EmilioHerrera** [gatsbyjs/gatsby#2132]
I am using gatsby with sass (gatsby-plugin-sass) but everytime I make change to scss it is not detected by gatsby. Any help would be appreciated as now I have to run gatsby develop every time. Thanks in advance!

**Comment by KyleAMathews** [comment]
Can you verify this happens on the official sass example site? https://github.com/gatsbyjs/gatsby/tree/master/examples/using-sass

**Comment by EmilioHerrera** [comment]
I tried the 'using-sass' example with no luck.
