### ISSUE TITLE
(docs) Split up Docs Templates into different pages

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21321]
## Summary

Split up [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/) into different pages for each type of template.

### Motivation

The table of contents for this page is already really long and doesn't lead to a lot of discoverability. It's not clear what "docs templates" are, and if I want to write a specific type of doc, I don't know what to look for. If they're split up with clear titles, e.g. "How to Write a Recipe", it's clearer and visible from the main sidebar 

## Steps to resolve this issue

Split up "Doc Templates" to different pages based on each different type of doc:

* How to Write A Reference Guide
* How to Write a Recipe
* How to Write a Tutorial
* How to Write a Plugin README/How to Write Docs for a Plugin (stub)
* How to Write a Starter README/How to Write Docs for a Starter (stub)

**Comment by JQuinnie** [comment]
Hi @tesseralis , 

I'd love to start contributing to Gatsby and think this would be a great place to start. Do you mind if I work on this?

Also, is there anything specific you'd like to see on the breakup of the pages?

I'm assuming the outline on the side panel would look like this;

- Docs Contributions
  - Docs Templates
    - Reference Guide
    - Recipes
    - Tutorial
    ....

**Comment by tesseralis** [comment]
@JQuinnie yeah! that sounds perfect. Go ahead :)

**Comment by marcysutton** [comment]
In the future, can @gatsbyjs/learning be consulted before making these kinds of recommendations? That way we can have a discussion about expectations and set contributors up for success.

**Comment by gillkyle** [comment]
This was merged in #21574
