### ISSUE TITLE
(docs) Remove links in docs/ and contributing/ sidebar that aren't part of their hierarchies

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21324]
## Summary

Remove links from docs/ and contributing/ that aren't part of their hiearachies: for example, the links to "Starter Library" and "Plugin Library" near the top of the docs sidebar.

### Motivation

These links break the flow of the sidebar as a list of organized contents. It can be jarring to click on a link in the sidebar and be taken to a completely new page, or to click on doc pages in sequence using the "next" and "prev" buttons to be taken to a completely different article.

## Steps to resolve this issue

The following lists all non-hierarchal links in the docs and contributing sidebars along with reasons for removal. The ones I feel most strongly about are **bolded**, while the non-bolded ones can be more justifiably kept.

Remove the following links from the docs sidebar:

- [**Plugin Library**](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml#L9) - already a top-level nav item, also covered in "Gatsby Resources" page just below. Takes up space and pushes actual doc content below the fold.
- [**Starter Library**](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml#L11) - starters are deprecated in favor of themes; also repeated in the "Gatsby Resources page" directly below
- [Plugins -> Plugin Library](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml#L242) Again, there is already a link to the plugins library on top. Also can just link to it in the top level "Plugins" page. It's smooshed right between two doc articles, leading to confusion if traversing docs in order.
- [Plugins -> Submit to Plugin Library](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml#L257) should just be a link in one of the other pages.
- [Starters -> Starter Library](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml#L289) Can just link to the top level "Starters" page.
- [**Contributing**](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml#L706) - already a top level directory

Remove the following links from the Contributing sidebar:

- [Gatsby Brand Guidelines](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/contributing-links.yaml#L74) - These aren't really "contributing" guides, and already have a link in the footer of each page.

## Alternatives

If we feel the links should stay, we can alternatively create different styling for out-of-hierarchy links so the user is prompted that the link is different.

**Comment by JQuinnie** [comment]
@tesseralis I'd be more than willing to help out with this.

**Comment by tesseralis** [comment]
@JQuinnie This issue is more for discussion. I want to make sure the learning/core team is okay with it before proceeding.

**Comment by JQuinnie** [comment]
> @JQuinnie This issue is more for discussion. I want to make sure the learning/core team is okay with it before proceeding.

Ah understood, thank you for letting me know!

**Comment by marcysutton** [comment]
This has come up a few times before, and we’ve kept the links there for strategic reasons. I would request that we investigate alternative styling to keep those links in, if possible.

**Comment by tesseralis** [comment]
@marcysutton could you elaborate on what the strategic reasons are? I can change the issue to be less prescriptive in a solution and just outline the general possible confusion

**Comment by AishaBlake** [comment]
We've been talking about some reorganization/redesign and I feel like these are valid concerns. We may choose not to work on this right now but I think we should keep it mind when we have that conversation. @tesseralis, I'm assuming this isn't blocking anything to do with i18n and is instead something you noticed while doing that work?

**Comment by tesseralis** [comment]
@AishaBlake not really. It's just "one more thing that we have to translate but it would be nice if we didn't have to."

**Comment by AishaBlake** [comment]
I'm going to go ahead and close this because it doesn't seem like we're in a position to prioritize this work anytime soon and it would need to be considered in the context of larger .org changes. Thank you for thinking through justification for each of these, @tesseralis! We'll have something to refer to when we do get to this.

**Comment by muescha** [comment]
in #17931 my suggestion was: 

- don't link to the starter / plugin / themes sections directly 
- put there a small introducing into plugins library / starter /themes library
- explaining a little bit more what are this directories (and with links to the directories)

this would not breaking the flow next/prev flow
