### ISSUE TITLE
Unkown argument "fields", if I don't run `npm clean` first

### ISSUE THREAD

**Issue by hristov296** [gatsbyjs/gatsby#21335]
## Summary
Unkown argument "fields", if I don't run `npm clean` first

## Relevant information

I use `createNodeField` to create a custom field on the "file" type. It works fine, but the problem is that if I don't run `npm run clean` first, before `npm run develop`, I get this error every time. If I do `npm run clean`, then `npm run develop` everything works as expected.

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown argument "fields" on field "file" of type "Query".

GraphQL request:56:26
55 |     }
56 |     site_logo_dark: file(fields: { optionId: { eq: "site_logo_dark" } }) {
   |                          ^
57 |       childImageSharp {

File: src/templates/page.js:139:26
```

### Environment (if relevant)

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 Intel(R) Xeon(R) CPU           W3565  @ 3.20GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.87
    Firefox: 72.0.2
  npmPackages:
    gatsby: ^2.19.12 => 2.19.12 
    gatsby-image: ^2.2.40 => 2.2.40 
    gatsby-plugin-emotion: ^4.1.22 => 4.1.22 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5 
    gatsby-source-filesystem: ^2.1.48 => 2.1.48 
    gatsby-source-strapi: 0.0.10 => 0.0.10 
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14 
  npmGlobalPackages:
    gatsby-cli: 2.8.29
    gatsby: 2.19.9

### File contents (if changed)

`gatsby-config.js`: 
```
module.exports = {
  siteMetadata: {
    title: "KTI",
    description: "KT International",
    author: "Supersait",
  },
  plugins: [
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-emotion",
    {
      resolve: "gatsby-source-strapi",
      options: {
        apiURL: "http://localhost:1337",
        contentTypes: ["page", "menu", "option"],
        queryLimit: 1000,
      },
    },
    {
      resolve: "gatsby-plugin-google-fonts",
      options: {
        fonts: ["Roboto Condensed:300"],
        display: "swap",
      },
    },
    "gatsby-transformer-sharp",
    "gatsby-plugin-sharp",
  ],
};
```
`package.json`: N/A 
`gatsby-node.js`: 
```
exports.onCreateNode = async ({
    node,
    actions: { createNode, createNodeField },
    store,
    cache,
    createNodeId,
  }) => {

  if (
    node.internal.type !== null &&
    node.internal.type === "StrapiOption" &&
    node.type === "image"
  ) {
    let fileNode;
    try {
      fileNode = await createRemoteFileNode({
        url: "http://localhost:1337/uploads/" + node.option_value,
        // parentNodeId: node.id,
        createNode,
        createNodeId,
        cache,
        store,
      })

      await createNodeField({
        node: fileNode,
        name: "optionId",
        value: node.option_id,
      })
    } catch (e) {}
  }
};
```

`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
The commented out `// parentNodeId: node.id,` will make it so those file nodes will be garbage collected on next run. Was there a reason for commenting it out?

**Comment by hristov296** [comment]
That fixed it! I don't remember anymore why I have commented it out. I must have forgot it like that after some test
