### ISSUE TITLE
(www) Organize components in dot-org by section

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21331]
## Description

Organize the many components of the site based on the section that they fall under.

## Motivation

The components library is very big and disorganized, making discoverability difficult. A lot of components are specific to certain paths (like `showcase-details`) but are dumped into the main `components` directory. In addition, filtering out section-specific components will be beneficial for [splitting the site up into themes](https://github.com/gatsbyjs/gatsby/issues/19105)

## Steps

The following is an (incomplete) lists of components that could be factored into subfolders. The refactor of each section should be in its own pull request.

layout/ - should contain layout components common to all pages

* layout
* site-metadata
* banner
* skip-nav
* navigation
* navigation-mobile
* search-form/
* footer links

homepage/

* card-headline
* card
* diagram
* futura-paragraph
* masthead

docs/ - should contain things in the docs, tutorial, contributing, and features pages

* api-reference/
* sidebar/
* page-with-sidebar
* docs-breadcrumb
* docs-table-of-contents
* markdown-page-footer

blog/

* pagination/
* avatar
* blog-post-preview-item
* tags-section

packages/ or plugins/

* gatsby-monogram
* package-readme
* page-with-plugin-searchbar
* plugiin-searchbar-body
* rotator
* slider

showcase/

* showcase-details

creators/

* creator-data (this is just a graphql fragment)

In addition, the src/views directory can probably be folded into src/components. There really isn't a distinction between "components" and "views".

ecosystem/

* layout-with-heading
* page-heading

## Related Issues

Part of: #19105

**Comment by DallasGale** [comment]
@tesseralis i can look into this if you like?

**Comment by tesseralis** [comment]
@DallasGale go ahead!

**Comment by DallasGale** [comment]
@tesseralis I have forked the repo and made the changes outlined in the description. Do you want the remainder components to be sorted based on my own discretion? 

I was thinking...

**/shared**
- banner
- button
- copy

**/layout**
- container
- layout
- markdown-page-footer
- page-with-sidebar
- visually-hidden
- dark-mode-toggle

**/navigation**
- navigation-mobile
- navigation
- prev-and-next
- share-menu

**/forms**
- discord
- debounce-input
- email-capture-form
- docsearch-content ?
- react-hubspot-form

**/modal**
- lazy-modal
- modal

**/global**
- site-metadata  ??
- localized-link ??

- build-data-example ??
- client-data-example ??
- lazy-highlight ??
- search-icon (icons) ??
- skip-nav-link (a11y) ??
- tech-with-icon (icons) ??

**Comment by tesseralis** [comment]
@DallasGale the primary motivation for this is to pull out components that are specific to a single section that can be factored out when splitting up the website into themes. The problem with proactively is that it can lead to inconsistencies if it's not clear what the folder is used for.

To use the currently existing folders as an example: the shared folder contains `<EggheadEmbed>` and `<Pullquote>`, two components meant to be used in MDX, `<HorizontalScroller>` a generic component used in a couple places, and `<FooterLinks>`, a navigation item included in all our spaces. The current "layout" folder only contains "page-with-heading", which is only used in "ecosystem".

Here's what I'm thinking:

* "shared/" should just be dumped out to the top level components directory
* Everything currently in "layout/" should be moved to "ecosystem/" (and possibly renamed to be less confusing)
* page-with-sidebar and markdown-page-footer can actually be moved to docs/, since they're specific to docs templates
* egghead-embed, pullquote, email-capture-form, react-hubspot-form go in mdx/
* "layout/" should be "stuff in everyone's layout" and should contain:
  * layout
  * site-metadata
  * banner
  * skip-nav
  * navigation
  * navigation-mobile
  * search-form/
  * discord (i guess. I don't even know why we're using a custom discord icon instead of the one provided by react-icons)
  * footer links
* everything else, let's leave top-level for now.

**Comment by fk** [comment]
> In addition, the src/views directory can probably be folded into src/components. There really isn't a distinction between "components" and "views".

💯

**Comment by LekoArts** [comment]
Since we merged .org and .com together the `www` folder here isn't the source of truth anymore. The structure is already different so even after open-sourcing the site again this issue won't be actionable thus I'll close it.
