### ISSUE TITLE
(docs) Highlight the Table Of Contents for more readability

### ISSUE THREAD

**Issue by Kiittyka** [gatsbyjs/gatsby#21339]
## Summary
The table of contents to the right of every page takes up space but is not highlighted enough to be used primarily.

### Motivation
When I looked through the docs, I did not notice it at first and I find it less helpful .

## Steps to resolve this issue
The scrollbar can either be highlighted or removed. If removed, it can be added to the main scrollbar on the left as hyperlinks which on click, navigates to the relevant subtopics.

**Comment by sidharthachatterjee** [comment]
> The table of contents to the right of every page takes up space but is not highlighted enough to be used primarily.

Thanks for the feedback! We think the Table of Contents is fine at the moment and definitely useful for some folks. 

In terms of visually highlighting it more than it is at the moment, I'll pass that feedback on to the design team! (Cc @fk)

**Comment by fk** [comment]
👋Hey, and thank you for the suggestion @Kiittyka! 🙏  

As @sidharthachatterjee said, we think the sidebar is working relatively well for most people — I believe it's the first time we hear this feedback. We should take a look at our analytics to see how much the current sidebar is used, and validate our assumption.
