### ISSUE TITLE
[Docs] Logo animation between home and docs is slow and choppy

### ISSUE THREAD

**Issue by damassi** [gatsbyjs/gatsby#2134]
Since Gatsby is so concerned with speed I thought I would post a screen-cap of the transition between the home and docs pages as it seems to really distract from the snappiness of the engine:

![skip](https://user-images.githubusercontent.com/236943/30505111-9992197e-9a27-11e7-8919-8a06d9639a21.gif)

While somewhat hard to capture (and ignoring the fact that its a low-res animated .gif) the animation isn't smooth IRL, and I'm running a fairly new 16gb MBP. Why not keep it simple (no animation) so that the first impression is raw speed?  The transition between distracts for little gain.

**Comment by fk** [comment]
I kinda agree. It was one of those "looks nice, let's keep it" things but it never was 100% right. Recently I also often noted Chrome to get really choppy at times, but then again it's what I sometimes run for a week, hoarding 100s of tabs.
I quickly tested just now and while Chrome doesn't feel right – just as you describe – in Firefox things are running nice and smooth. :D

**Comment by damassi** [comment]
Gatsby is crazy fast -- let others worry about animation. Clicking around the site (without distraction) I'm sure will be sufficient!

**Comment by KyleAMathews** [comment]
I really love the animation… but agree it is choppy sometimes which is pretty noticable :-(

Perhaps instead of animating padding, we just animation the position? https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/

Not sure how well that'd work with the design but if it does, it's much faster to animate than padding.

**Comment by damassi** [comment]
Just make everything instant! Gatsby is such to where I'm starting to notice if a site is built with it or not; it's noticeable. This is just my opinion, but I think y'all should do everything possible to express that "wow" aspect and animation (regardless of how simple) feels a bit cheap compared to the overall engineering.
