### ISSUE TITLE
How to avoid generating extra unused files

### ISSUE THREAD

**Issue by solid-studio** [gatsbyjs/gatsby#21341]
Hello, I'm following the gatsby tutorial https://www.gatsbyjs.org/tutorial/part-zero/

Which basically does a 

> gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world

That example gives you a single page that contains a div with Hello World.

I ran the **gatsby build** command and I got this.

![Screen Shot 2020-02-10 at 10 31 13](https://user-images.githubusercontent.com/56453782/74142405-b63e6c80-4bf0-11ea-8cb8-be697ef4c03e.png)
]

Does that means that to publish a simple HelloWorld page I need to upload all those files? Is there a way to avoid that? i.e there is not data fetching or any other behaviour, why do I need a lot of js files?

Thanks

**Comment by pieh** [comment]
`hello-world` is barebones starter, which lets you start your projects without any additional boilerplate that you need to remove. It isn't example of site people usually build as most of them have multiple pages (this needs routing) and are actually interactive (more js). So yes, to not have broken deploys you do need all of those files.

If you don't want / need to use javascript in your site then you can use plugin https://www.gatsbyjs.org/packages/gatsby-plugin-no-javascript/ that will remove script tags from html files and then you can upload just .html files (and any non-javascript assets like images or fonts) selectively (tho not sure if that plugin removes js files from `public` or not)

**Comment by solid-studio** [comment]
thanks a lot

**Comment by wardpeet** [comment]
Thank you for opening this, @solid-studio 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
