### ISSUE TITLE
Is it possible to use 'gatsby-remark-graph' plugin with MDX?

### ISSUE THREAD

**Issue by aaronuurman** [gatsbyjs/gatsby#21347]
Is it possible to use 'gatsby-remark-graph' plugin with MDX?

**Comment by sidharthachatterjee** [comment]
Yup! Should work just fine as documented in https://www.gatsbyjs.org/docs/mdx/plugins/#gatsby-remark-plugins

**Comment by aaronuurman** [comment]
@sidharthachatterjee Thank you!
