### ISSUE TITLE
Layout behaviour inconsistencies in production (Netlify)

### ISSUE THREAD

**Issue by thibautvs** [gatsbyjs/gatsby#21344]
## Description

Several layout behaviour inconsistencies in production on my website (www.urge2code.com)

### Steps to reproduce

- **On the homepage** (www.urge2code.com), in the section "Featured Work", the video is too large (1240px instead of 1000px) and the title "Featured Work" is misaligned compared to the other section titles. Use the top menu to navigate to another page, then come back to /home, the video has the correct width (1000px) and the section title is well aligned.

I see in the browser source that, when the section title is misaligned, it's because it is contained in the container of the video, while this isn't the case at all in my source code.

- **On contact page** (navigate directly to www.urge2code.com/contact-us, without using the menu), see the layout problem: "Get in touch" is displayed next to "Contact Us" instead of below and the 2 icons below are an "@". Navigate to any other page using the top menu then come back to "Contact" page => observe that the layout is correct (title & subtitle on a separate line and the icons aren't an "@" two times). For info, the "@" icons are using React Font Awesome.

### Expected result

I expect the layout to be correct. This doesn't happen locally, only in production. Reloading a page in production also causes the abovementioned issues to happen. The website is hosted on Netlify.

### Environment

  System:
    OS: macOS 10.15.3
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.87
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.14 => 2.19.14 
    gatsby-plugin-react-helmet: ^3.1.15 => 3.1.15 
    gatsby-plugin-styled-components: ^3.1.13 => 3.1.13 
  npmGlobalPackages:
    gatsby-cli: 2.4.0

Thanks!

**Comment by pieh** [comment]
Cases like that:
![Screenshot 2020-02-11 at 00 47 30](https://user-images.githubusercontent.com/419821/74200770-1ae8de00-4c68-11ea-8c89-908b812e4308.png)
don't work well with SSR (because SSR doesn't have concept of viewport). It will render things like for mobile to .html file

And later on React hydration will mess things up because first render on the client will produce different DOM tree than what SSR did.

You can try loading your page in a narrow viewport, resize it to be in desktop size and then everything (seems to) match.

**Comment by thibautvs** [comment]
Hi @pieh,

Thx very much for the info!

Do you have any recommendations on best practices regarding responsive web design with Gatsby? Should I get rid of React Responsive altogether?

Thx!

**Comment by pieh** [comment]
At the moment I don't have advice other than to try not to use `react-responsive` (or other solutions that let you render different things based on viewport) and try to use media queries just in styling (so single component tree for all layouts and every difference between desktop/tablet/mobile is done via styling).

There might be a way to workaround this `react-responsive` issue (by somehow forcing first render / hydration to use same thing as what was used for .html generation and then making subsequent re-render using actual viewport), but I'm not sure how this could be done + it would result in things moving around on screen (so not great user experience).

**Comment by wardpeet** [comment]
Thank you for opening this, @thibautvs 

As @pieh suggested, it's better to rely on css media queries. It's okay to use display block and none to hide things from the user. You can use react-responsive somewhere below on your page which only becomes visible after scrolling so users won't see any of the flickr effect but a rule of thumb is to use css instead.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by thibautvs** [comment]
Hi @pieh and @wardpeet,

I'll resort to good ol' media queries then!

Thanks for the help!
