### ISSUE TITLE
[gatsby-transformer-remark] Refactor wordCount and timeToRead to not count words twice

### ISSUE THREAD

**Issue by jlkiri** [gatsbyjs/gatsby#21357]
## Summary

Currently words are counted twice, for each of `wordCount` and `timeToRead` fields. `wordCount` counts words as a custom step in the `unified` process, and `timeToRead` uses `lodash`. There might be a better way to unify the counting.

For example, solutions like [`retext-japanese`](https://github.com/muraken720/retext-japanese) could be used, but this particular library does not seem to work on my machine. Maybe `wordCount` could use logic that `timeToRead` uses now.

**Comment by wardpeet** [comment]
Hi, looks like you fixed your issue youreself which is ace! 💯 👏 

Thank you! I'll be closing this issue, if this is not the case feel free to re-open or re-create it.

**Comment by jlkiri** [comment]
Ah, sorry, that PR was fixing the other issue and simply mentioned this one. This one is not resolved yet, but I'm working on it.
