### ISSUE TITLE
How can I use a standalone HTML file as page?

### ISSUE THREAD

**Issue by mojovski** [gatsbyjs/gatsby#21360]
Hi,
I would like to integrate an automatically generated HTML page from Facebook's Hiplot as an iframe.
However, I don't see a way on how to setup Gatsby to enable direct access to the HTML file.
Similarly to put the file in some published directory and then access it via
```
localhost:8000/published_plots/hiplot1_output.html
```

Thanks a lot for your support!

**Comment by jonniebigodes** [comment]
@mojovski see if [this](https://github.com/gatsbyjs/gatsby/issues/17761#issuecomment-533816520) helps you.

**Comment by mojovski** [comment]
@jonniebigodes  thanks! This solved my problem.
