### ISSUE TITLE
[gatsby-plugin-google-tagmanager] Custom events, rather than limited to 'gatsby-route-change'

### ISSUE THREAD

**Issue by robmarshallhome** [gatsbyjs/gatsby#21362]
The Google Tag Manager plugin currently uses a hardcoded event on a page change: 'gatsby-route-change'.

https://github.com/gatsbyjs/gatsby/blob/79326a5f26e1a79610849d3992e44a6c7afbec7d/packages/gatsby-plugin-google-tagmanager/src/gatsby-browser.js#L12

To allow more flexibility, it would be great for users to add their own event for this. This could be managed within gatsby-config.js.

If this is a feature that interests you I would be happy to create a PR.

Thanks,
Rpb

**Comment by wardpeet** [comment]
Hi,

could you explain why this would help your use case? You can add any tag to an event if I'm not mistaken so you should be just fine with gatsby-route-change.

**Comment by robmarshallhome** [comment]
Hi @wardpeet,

Some clients have specific naming conventions that they like to stick to. Although it is possible to fire events with any named tag event, to ensure consistency for the client it would be great to pass a custom name to this plugin.

**Comment by rbelow** [comment]
Hi, @robmarshallhome! If I understand it corectly the `gatsby-plugin-google-tagmanager` should have a plugin option where you can pass your custom event name like in this example:

```js
// gatsby-config.js

    {
      resolve: "gatsby-plugin-google-tagmanager",
      options: {
        id: "TAG_MANAGER_ID",

        // Include GTM in development.
        // Defaults to false meaning GTM will only be loaded in production.
        includeInDevelopment: false,

        // datalayer to be set before GTM is loaded
        // should be an object or a function that is executed in the browser
        // Defaults to null
        defaultDataLayer: { platform: "gatsby" },

        // Defaults to gatsby-route-change
        routeChangeEventName: "CUSTOM_EVENT_NAME"

        // More options...
      },
    },
```

I can take a look on this if @wardpeet agrees.

**Comment by robmarshallhome** [comment]
@rbelow I have seen that in the options, but if you look at the gatsby-browser.js file, this option is not implemented. So the page change has the default name always.

**Comment by rbelow** [comment]
Ok. Seems clear to me. Should we then move forward on this? I would implement it if nobody disagrees.

**Comment by marcysutton** [comment]
@rbelow we would welcome a PR to make that change, especially since there's an issue here discussing the use case. I'd say go for it!

**Comment by rbelow** [comment]
@robmarshallhome the issue is now closed. I hope the solution will address your needs.

_Follow me on [GitHub](https://github.com/rbelow) or [Twitter](https://twitter.com/rbelow_)._
