### ISSUE TITLE
Scrollabe element scrolls to top on route change

### ISSUE THREAD

**Issue by brandondurham** [gatsbyjs/gatsby#21368]
I have a `<nav />` element in my `Layout.js` file that is scrollable via `overflow: auto;`. When scrolling to the bottom and clicking a nav item, the route updates and my scrollable nav scrolls back to the top, pushing the clicked nav item back offscreen.

Possible to avoid this?

### Environment (if relevant)

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Shell: 5.6.2 - /usr/local/bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/Cellar/yvm/3.4.0/shim/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 41.0.2
    Safari: 13.0.4
  npmPackages:
    gatsby: 2.19.7 => 2.19.7 
    gatsby-cli: 2.8.27 => 2.8.27 
    gatsby-image: 2.2.39 => 2.2.39 
    gatsby-plugin-feed: 2.3.26 => 2.3.26 
    gatsby-plugin-google-analytics: 2.1.34 => 2.1.34 
    gatsby-plugin-manifest: 2.2.39 => 2.2.39 
    gatsby-plugin-offline: 3.0.32 => 3.0.32 
    gatsby-plugin-postcss: 2.1.19 => 2.1.19 
    gatsby-plugin-react-helmet: 3.1.21 => 3.1.21 
    gatsby-plugin-react-svg: 3.0.0 => 3.0.0 
    gatsby-plugin-sharp: 2.4.3 => 2.4.3 
    gatsby-source-filesystem: 2.1.46 => 2.1.46 
    gatsby-transformer-remark: 2.6.49 => 2.6.49 
    gatsby-transformer-sharp: 2.3.13 => 2.3.13 

### File contents (if changed)

`gatsby-config.js`:
```javascript
module.exports = {
	siteMetadata: {
		title: 'A Memoir Project',
		description: 'An online memoir by Michael Blankenburg with new chapters published every other Monday.',
		author: '@brandondurham',
	},
	plugins: [
		'gatsby-plugin-react-helmet',
		'gatsby-plugin-postcss',
		'gatsby-transformer-sharp',
		'gatsby-plugin-sharp',
		{
			resolve: 'gatsby-source-filesystem',
			options: {
				name: 'images',
				path: `${__dirname}/src/images`,
			},
		},
		{
			resolve: 'gatsby-transformer-remark',
			options: {
				plugins: [
					'gatsby-remark-smartypants',
					{
						resolve: 'gatsby-remark-figure-caption',
						options: {},
					},
					{
						resolve: `gatsby-remark-images`,
						options: {
							backgroundColor: 'transparent',
							linkImagesToOriginal: false,
							maxWidth: 1080,
							quality: 100,
						},
					},
				],
			},
		},
		{
			resolve: 'gatsby-source-filesystem',
			options: {
				name: 'chapters',
				path: `${__dirname}/src/chapters`,
			},
		},
		{
			resolve: 'gatsby-plugin-manifest',
			options: {
				name: 'a-memoir-project',
				short_name: 'a-memoir-project',
				start_url: '/',
				background_color: '#663399',
				theme_color: '#663399',
				display: 'minimal-ui',
				icon: 'src/images/icon.png',
			},
		},
		{
			resolve: `gatsby-source-filesystem`,
			options: {
				path: `${__dirname}/src/chapters`,
			},
		},
	],
}
```
`package.json`:
```json
{
  "name": "a-memoir-project",
  "private": true,
  "description": "An online memoir by Michael Blankenburg with new chapters published every other Monday.",
  "version": "2.0.0",
  "author": "Brandon Durham <brandon@smallparade.com>",
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "dependencies": {
    "gatsby": "2.19.10",
    "gatsby-background-image": "0.9.14",
    "gatsby-image": "2.2.39",
    "gatsby-plugin-manifest": "2.2.40",
    "gatsby-plugin-offline": "3.0.33",
    "gatsby-plugin-postcss": "2.1.19",
    "gatsby-plugin-react-helmet": "3.1.21",
    "gatsby-plugin-sharp": "2.4.4",
    "gatsby-remark-figure-caption": "^2.0.0",
    "gatsby-remark-images": "3.1.43",
    "gatsby-remark-smartypants": "2.1.20",
    "gatsby-source-filesystem": "2.1.47",
    "gatsby-transformer-remark": "2.6.49",
    "gatsby-transformer-sharp": "2.3.13",
    "intersection-observer": "0.7.0",
    "postcss-css-variables": "0.14.0",
    "postcss-custom-media": "7.0.8",
    "prop-types": "15.7.2",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-helmet": "5.2.1"
  },
  "devDependencies": {
    "stylelint": "13.0.0",
    "stylelint-config-standard": "19.0.0",
    "stylelint-order": "4.0.0"
  }
}
```
`gatsby-node.js`:
```javascript
const path = require(`path`)

exports.createPages = async ({ actions, graphql, reporter }) => {
	const { createPage } = actions

	const chapterTemplate = path.resolve(`src/templates/chapter.js`)

	const result = await graphql(`
		{
			allMarkdownRemark(
				sort: { order: ASC, fields: [frontmatter___chapter] }
				limit: 1000
			) {
				edges {
					node {
						frontmatter {
							path
						}
					}
				}
			}
		}
	`)

	// Handle errors
	if (result.errors) {
		reporter.panicOnBuild(`Error while running GraphQL query.`)
		return
	}

	result.data.allMarkdownRemark.edges.forEach(({ node }) => {
		createPage({
			path: node.frontmatter.path,
			component: chapterTemplate,
			context: {}, // additional data can be passed via context
		})
	})
}
```
`gatsby-browser.js`:
```javascript
/**
 * Implement Gatsby's Browser APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/browser-apis/
 */

export const onClientEntry = () => {
	// IntersectionObserver polyfill for gatsby-background-image (Safari, IE)
	if (!(`IntersectionObserver` in window)) {
		require('intersection-observer')
	}
}
```
`gatsby-ssr.js`: N/A

**Comment by blainekasten** [comment]
@brandondurham is there a public URL to see this in? Are you basically wanting to not auto-scroll to the top on route change?

**Comment by brandondurham** [comment]
This is the site being built: https://5e4327994fb75d0194d5bf57--brave-sammet-902b00.netlify.com/chapter/the-burial

You’ll see the numbers on the far left are independently scrollable via `overflow: auto;`. If you scroll down and click on 18, you’ll see that both the page AND this scrollable element are scrolled back to the top. I want the page to scroll to top, but not this scrollable element.

**Comment by blainekasten** [comment]
@brandondurham The site looks great!

From my test the left sidebar is not actually scrollable. It looks to be full height always. Either way, I think you'll want to do some configuration of the `shouldUpdateScroll` function of your gatsby-browser.js file. Here is some documentation:


https://www.gatsbyjs.org/docs/browser-apis/#shouldUpdateScroll


I'm going to close this issue as there isn't anything wrong with Gatsby here to fix. Feel free to keep the conversation going on here if you need more assistance! Closing just helps us maintain our issues, but we're happy to keep engaged and help you out :)

**Comment by blainekasten** [comment]
Sorry I didn't think of this before. We also have a `ScrollContainer` component exported from `gatsby-react-router-scroll` which if you wrap an overflow container with this component, it will maintain and restore scroll between page loads.

```jsx
<ScrollContainer scrollKey="static-unique-key">
  <ul>...</ul>
</ScrollContainer>
```
