### ISSUE TITLE
Two types notation of e-commerce

### ISSUE THREAD

**Issue by naoya7076** [gatsbyjs/gatsby#21361]
# Summary
Gatsby docs have two types notation of e-commerce and ecommerce.
```
https://www.gatsbyjs.org/docs/building-an-e-commerce-site/
https://www.gatsbyjs.org/docs/building-an-ecommerce-site-with-shopify/
```
Which type of notation is we should use?

**Comment by laurieontech** [comment]
Thanks for your question! You're correct that this should be consistent. `e-commerce` is best. Feel free to open a PR if you'd like and we can make the change.

**Comment by AishaBlake** [comment]
Closing this because I've reopened #20790, which should encompass any instances where it's necessary to update URLs in this way.
