### ISSUE TITLE
[www] Constant repainting in Safari

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#2136]
The gatsbyjs.org homepage in Safari 10.1.2 clogs the CPU at around 70%-120% 🌪, constantly repainting stuff:

![image](https://user-images.githubusercontent.com/21834/30507688-47f78336-9a88-11e7-853a-7ef4dd2faa88.png)

As reported by https://twitter.com/tngranados on Twitter: https://twitter.com/tngranados/status/908700748451598336

**Comment by fk** [comment]
Commenting [CSS keyframe animations](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/diagram.js#L25) ([2](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/diagram.js#L86)) in the Gatsby diagram component stops Safari from going nuts.

**Comment by markmichon** [comment]
I can confirm it happens on my end too. There's a really old chromium bug report about it, but nothing in the webkit bugtracker.

Possible stopgap solution might be to reduce the offset value to something more realistic than 1000, as the paths look to all be pretty short in length.

**Comment by fk** [comment]
Hi @markmichon, thanks for looking and commenting! 🤗 

> There's a really old chromium bug report about it, but nothing in the webkit bugtracker.

Yeah, weird that there's no webkit issue.
I stumbled upon those two:

* https://bugs.chromium.org/p/chromium/issues/detail?id=167569
* https://bugs.chromium.org/p/chromium/issues/detail?id=642601

Also thought about offset and path length, but haven't had the time to really look into this over the weekend. I only tried `path` instead of `line` and cleaned up things a little along the way until now. Ah, also before implementing the animated lines, I prepared https://codepen.io/fk/pen/QMbqyV to show Kyle. Over there, perf looks okay in Safari, but this obviously misses the flexbox stuff that gets repainted on gatsbyjs.org.

**Comment by fk** [comment]
@markmichon Adjusted `stroke-dashoffset` but this didn't change anything as far as I could see. Forcing Safari into putting the constantly repainted elements on their own layers in the compositor then did – each `translateZ(0)` lowered CPU time by ~5%. May I ask you to check again once the preview is built?

**Comment by fk** [comment]
Preview ready: https://deploy-preview-2160--gatsbyjs.netlify.com/

**Comment by markmichon** [comment]
I'm seeing ~ 25% CPU utilization on that preview. Better by miles, but still horrendous. I'm going to try and make some time to abstract this out into a standalone reproduction and do some testing. I have almost the same technique running on another react project and it doesn't experience this, so I suspect it's not stroke-dashoffset alone, but rather how it interacts with something else.

**Comment by fk** [comment]
> I'm seeing ~ 25% CPU utilization on that preview. Better by miles, but still horrendous.

:D :/ ;) Thanks for checking! I have to admit I never animated SVG with CSS _keyframes_ before this, so my only reference values are some websites and codepens (e.g. https://codepen.io/thebabydino/pen/LuoCq at 20-30%, https://segment.com at an easy 100%). Most if not all of them drove Safari relatively nuts, too – without causing repaints for seemingly unrelated elements though – so I had a hard time making sense of those CPU usage numbers until you chimed in. I was happy to improve things a bit, at least until reading your comment 😆 
Really appreciate the help!

> I'm going to try and make some time to abstract this out into a standalone reproduction and do some testing.

Oooh that'd be sweet! 😍  🙏

**Comment by markmichon** [comment]
I'll keep playing with it when I get some time, but you might be right that it's going to be a concession we have to deal with. 

If there's interest in improving it down the road, it might be worth tweaking the component to only run the animation when it's first in view and letting it "end" with non-moving dotted lines. This way there's just a burst of usage. If that's done though, it might be worth animating the whole diagram in, piece by piece, so it has a nice flow effect.

**Comment by fk** [comment]
> but you might be right that it's going to be a concession we have to deal with.

Hmm I don't have any real information at all, still, just a few quick looks so didn't want to imply that we can't be better in Safari. I will take another look when I have some time, too – those littering `translateZ`s do not feel right at all. Also a peek at mobile Safari.

**Comment by fk** [comment]
Just saw your edited comment –

> codepen […] appears to cause the same ~20% spike in chrome (harder to see in activity monitor, but it's definitely doing it)

Uh, in Chrome too? :/

**Comment by markmichon** [comment]
Yep, chrome too. Just harder to notice as activity monitor doesn't name tabs from chrome like it does in safari. For what it's worth, I tried swapping to hacky translate-based animations and they are even less performant than the dashoffset method.

**Comment by fk** [comment]
Yeah just looked at it in Chrome :( Btw., Chrome has a Taskmanager (Menu -> Tools -> Taskmanager) that makes it really easy to see. As soon as the diagram is scrolled into view I see 20-25% CPU there.

> For what it's worth, I tried swapping to hacky translate-based animations and they are even less performant than the dashoffset method.

Thank you! And grrrr… :/ ;)
