### ISSUE TITLE
gatsby-plugin-sharp - how to set cover position?

### ISSUE THREAD

**Issue by chrisui** [gatsbyjs/gatsby#21370]
## Summary

Currently when using the plugin I am seeing a bad crop. Looking at sharp documentation with the default fit as `cover` (great) I should be able to set a position to anchor this to (ie. I want `top` not the default `center`).

I can't seem to see this documented in the plugin?

## Relevant information

See docs

https://sharp.pixelplumbing.com/api-resize#parameters

https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/?=

### Environment (if relevant)

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.7 => 2.19.14 
    gatsby-image: ^2.2.39 => 2.2.40 
    gatsby-plugin-ffmpeg: ^0.3.1 => 0.3.1 
    gatsby-plugin-google-analytics: ^2.1.35 => 2.1.35 
    gatsby-plugin-layout: ^1.1.22 => 1.1.22 
    gatsby-plugin-manifest: ^2.2.39 => 2.2.41 
    gatsby-plugin-offline: ^3.0.32 => 3.0.34 
    gatsby-plugin-preload-link-crossorigin: ^1.0.2 => 1.0.2 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.22 
    gatsby-plugin-sharp: ^2.4.3 => 2.4.5 
    gatsby-plugin-styled-components: ^3.1.19 => 3.1.19 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.1.48 => 2.1.48 
    gatsby-transformer-ffmpeg: ^0.3.8 => 0.3.8 
    gatsby-transformer-remark: ^2.6.50 => 2.6.50 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.14 
    gatsby-video: ^0.1.3 => 0.1.3 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by blainekasten** [comment]
I think this heading might help you out: https://sharp.pixelplumbing.com/api-resize#resize

e.g., what I think you want is `position: top`

**Comment by chrisui** [comment]
@blainekasten Thanks for getting back to me and sorry about my slow response time!

Indeed position is exactly what I want from the underlying sharp API however my question is how do I access that through the gatsby-sharp-plugin api.

Ie. I can't see `position` documented here: https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/?=

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll want to use `cropFocus` for that: https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/?=#cropfocus

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
