### ISSUE TITLE
gatsby command not found

### ISSUE THREAD

**Issue by yaronlevi** [gatsbyjs/gatsby#2137]
node @8.2.1
npm@5.3.0

Following the official guide I run:
`npm install --global gatsby-cli`

Then when running:
`gatsby new tutorial-part-one https://github.com/gatsbyjs/gatsby-starter-hello-world`

**gatsby: command not found**

When looking at the globally installed npm packages I get:
<img width="1163" alt="screen shot 2017-09-16 at 13 28 10" src="https://user-images.githubusercontent.com/5398977/30511512-45bc1928-9ae3-11e7-99cc-bf98b34cd8a4.png">

**Comment by KyleAMathews** [comment]
Try uninstalling and reinstalling the global package. Probably just an install error.

**Comment by yaronlevi** [comment]
I've tried installing and reinstalling but I get the same error. (Also the same red error when listing the global packages).

Any other direction you can point me to?

**Comment by KyleAMathews** [comment]
Try Yarn

**Comment by yaronlevi** [comment]
The same result )-:

**Comment by yaronlevi** [comment]
Looking into this now:
https://github.com/yarnpkg/yarn/issues/2064

If I lookup "Gatsby" in this thread, the same issue is mentioned.

**Comment by Oluwasetemi** [comment]
Yarn sure solved the problem for me on Ubuntu
`sudo yarn global add gatsby-cli`

**Comment by jasonxia23** [comment]
Problem may be you switch your node version using `nvm`, and package is installed under `~/.nvm/versions/node/{version}/lib`, so run `gatsby` will throw error.

**Comment by nodox** [comment]
not sure why but @Oluwasetemi your `sudo` command worked for me

**Comment by m1r9h71** [comment]
I had the issue after installing Gatsby globally several times on a mac (OS 10.13.2). I tried different node & npm versions. It turned out that the node/npm installs were not in the standard /usr/local/lib/ folder. I reinstalled both from https://nodejs.org/en/download/ making sure the location was correct and then cd to that location before installing Gatsby. Gatsby commands worked perfectly after that.

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍

**Comment by RyanPWalker** [comment]
For me, I had to [update my npm config](https://stackoverflow.com/questions/52378823/gatsby-version-bash-gatsby-command-not-found).

`npm config delete prefix `
`npm config set prefix /usr/local`
`npm i -g gatsby-cli`
`gatsby --version`

**Comment by mccrodp** [comment]
None of the above work for me. I had to follow this StackOverflow: https://stackoverflow.com/questions/42285518/sh-sysctl-command-not-found-for-mac-os-x-running-a-cron-job But actually, I had to add `/usr/sbin` to my PATH on Mac. Wasn't finding `sysctl` on my path. Maybe a Gatsby v2 thing, didn't happen before on same Mac.

**Comment by YLD1** [comment]
> On the latest MacOS, I had to [update my npm config](https://stackoverflow.com/questions/52378823/gatsby-version-bash-gatsby-command-not-found).
> 
> `npm config delete prefix `
> `npm config set prefix /usr/local`
> `npm i -g gatsby-cli`
> `gatsby --version`

This worked for me

thank you very much

**Comment by kipps** [comment]
> On the latest MacOS, I had to [update my npm config](https://stackoverflow.com/questions/52378823/gatsby-version-bash-gatsby-command-not-found).
> 
> `npm config delete prefix `
> `npm config set prefix /usr/local`
> `npm i -g gatsby-cli`
> `gatsby --version`

Thank you so much! It works!

**Comment by Rosin355** [comment]
> On the latest MacOS, I had to [update my npm config](https://stackoverflow.com/questions/52378823/gatsby-version-bash-gatsby-command-not-found).
> 
> `npm config delete prefix `
> `npm config set prefix /usr/local`
> `npm i -g gatsby-cli`
> `gatsby --version`

I had the problem above...now by following this command it works also for me...

**Comment by jstansbe** [comment]
I ran into this issue when installing (2.7.47) via npm on mac os.
Managing node with nvm... not sure if relevant!

The fix for me (@Oluwasetemi solution):
1. sudo npm uninstall -g gatsby-cli
2. sudo yarn global add gatsby-cli

**Comment by askiebaby** [comment]
> On the latest MacOS, I had to [update my npm config](https://stackoverflow.com/questions/52378823/gatsby-version-bash-gatsby-command-not-found).
> 
> `npm config delete prefix `
> `npm config set prefix /usr/local`
> `npm i -g gatsby-cli`
> `gatsby --version`

This solution solved my problems, thank you.

**Comment by life-efficient** [comment]
`npm install -g gatsby-cli` to install globally

**Comment by vishnupriyavr** [comment]
> On the latest MacOS, I had to [update my npm config](https://stackoverflow.com/questions/52378823/gatsby-version-bash-gatsby-command-not-found).
> 
> `npm config delete prefix `
> `npm config set prefix /usr/local`
> `npm i -g gatsby-cli`
> `gatsby --version`

Thanks, this worked for me, however only npm works and yarn does not.
