### ISSUE TITLE
default export in gatsby-ssr/browser doesn't produce warnings

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#21382]
Right now we produce error when there are named export in `gatsby-ssr` or `gatsby-browser` that don't match any of our API hooks ( https://www.gatsbyjs.org/docs/ssr-apis/ / https://www.gatsbyjs.org/docs/browser-apis/)

For example:

```js
// in gatsby-ssr.js
export const notExistingAPIHook = () => {
  console.log("this won't show")
}
```

will produce

```
 ERROR #11329 

Your plugins must export known APIs from their gatsby-ssr.js.

See https://www.gatsbyjs.org/docs/ssr-apis/ for the list of Gatsby ssr APIs.

- Your local gatsby-ssr.js is using the API "notExistingAPIHook" which is not a known API.
```

When there is default export:

```js
// in gatsby-ssr.js
export default () => {
  console.log("this won't show")
}
```

We don't get any warnings or errors, but it won't ever be executed by gatsby. Behaviour for exports should be consistent and we should warn about default exports as well

### Task

Adjust https://github.com/gatsbyjs/gatsby/blob/d2fa8f72b551995a973639d1d9e8ee2b15442d0c/packages/gatsby/src/bootstrap/resolve-module-exports.js#L50-L98

to handle `default` exports as well and ideally add test case for that in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/__tests__/resolve-module-exports.js

**Comment by danilobuerger** [comment]
Related to this, when keeping the ssr code somewhere else, including it like:
```
export * from "./src/utils/gatsby-ssr";
```
fails silently too.
