### ISSUE TITLE
How to generate custom urls for some wordpress blogs

### ISSUE THREAD

**Issue by expatguideturkey** [gatsbyjs/gatsby#21397]
I have one clients WordPress website that has a nested WordPress website inside the main website. The main website blogs url structure is **www.domain.com/blog-content** and the nested website has **www.domain.com/nested-site-name/blog/blog-content** 
when I am creating posts in Gatsby-node.js I have set below path
```
createPage({
     path: `${edge.node.link}`,
     component: slash(postTemplate),
      context: {
        id: edge.node.id,
        relatedPosts: getRelatedPosts(edge.node, result.data.allWordpressPost.edges),
        categoryList:edge.node.categories.map(category=>category.id),
        
      },
```
how should I create posts path for nested website blog. As the having the same URL structure is important for saving the website google ranking. Please advise.

**Comment by sidharthachatterjee** [comment]
You should be able to call `createPages` (like you do above) with the `blog-content` path and then the `nested-site-name/blog/blog-content` path 

Let me know if that doesn't work! Closing this for now

**Comment by expatguideturkey** [comment]
Hi @sidharthachatterjee how should I configure two **baseUrl** WordPress websites so that I can extract blogs/pages from both WordPress websites:

```
{
      resolve: `gatsby-source-wordpress`,
      options: {
        excludedRoutes: [
          '/wp/v2/users/**',
          '/wp/v2/settings*',
          '/wp/v2/themes*',
        ],
        baseUrl: `cms.firstdomain.com`,
        protocol: `https`,
        hostingWPCOM: false,
        useACF: true,

     searchAndReplaceContentUrls: {
          sourceUrl: 'https://cms.firstdomain.com',
          replacementUrl: '',
        }, 
      },
    },
```
