### ISSUE TITLE
Customise filename and path for generated page 

### ISSUE THREAD

**Issue by ashoksudani** [gatsbyjs/gatsby#21393]
Hello,

I am building a small react web application where I need to create simply two pages 1)login.html 2)signup.html but both shares many components, considering this requirement of multiple entries from single page application kind of structure I am trying to use GATSBY.

But GATSBY generates html page as "login/index.html" while I need it to be "index.html" at root folder generated after "gatsby build" or accessible during "gatsby develop"

I tried using templates in``gatsby-node.js`` to provide custom names in path e.g. "/login" but it still generates ``login/index.html``.

Is there any way I can achieve this?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
```
exports.createPages = ({ actions: { createPage } }) => {
  createPage({
    path: "/login",
    component: require.resolve("./src/templates/login.js"),
  })
  createPage({
    path: "/singup",
    component: require.resolve("./src/templates/singup.js"),
  })
}
```
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wardpeet** [comment]
Hey,

We generate html so they have to be inside /login/index.html to achieve the /login/ url. We have a plugin called [gatsby-plugin-remove-trailing-slashes](https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/) that achieves what you're trying to do.

I'm not 100% sure why it matters, you can always configure your webhost to support this with rewrite rules.

I'm marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by ashoksudani** [comment]
Thanks @wardpeet for your prompt reply.

But I followed instructions set at https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/ to install suggested plugin but still it generates html as e.g. "public/page-2/index.html" instead of "public/page-2.html"

I would like to achieve this because my requirement is to just export generated html pages(without any folder e.g. page-2.html) to other module.

I did start project by  ``gatsby new ..``

Only change I made is 

1) installed package ``pm install --save-dev gatsby-plugin-remove-trailing-slashes``
2) updated https://github.com/ashoksudani/gatsby-nullify-index-html/blob/master/gatsby-config.js to include plugin.

Then I run ``npm run build``

and output is still not expected as shown below :

```
 user  ~/work/gatsby-nullify-index-html   master  ls -l public
total 2496
drwxr-xr-x   3 user  staff      96 Feb 13 11:32 404
-rw-r--r--   1 user  staff    9882 Feb 13 11:32 404.html
-rw-r--r--   1 user  staff   98139 Feb 13 11:32 app-3c0c60211941d9af6008.js
-rw-r--r--   1 user  staff  390091 Feb 13 11:32 app-3c0c60211941d9af6008.js.map
-rw-r--r--   1 user  staff     317 Feb 13 11:32 chunk-map.json
-rw-r--r--   1 user  staff  150340 Feb 13 11:32 commons-e16acd6960a392227066.js
-rw-r--r--   1 user  staff  471151 Feb 13 11:32 commons-e16acd6960a392227066.js.map
-rw-r--r--   1 user  staff     461 Feb 13 11:32 component---src-pages-404-js-0290f163286959b63491.js
-rw-r--r--   1 user  staff     618 Feb 13 11:32 component---src-pages-404-js-0290f163286959b63491.js.map
-rw-r--r--   1 user  staff   12983 Feb 13 11:32 component---src-pages-index-js-9f8ee3cdc463c772041b.js
-rw-r--r--   1 user  staff   43802 Feb 13 11:32 component---src-pages-index-js-9f8ee3cdc463c772041b.js.map
-rw-r--r--   1 user  staff     507 Feb 13 11:32 component---src-pages-page-2-js-c533758acaabdefda86a.js
-rw-r--r--   1 user  staff     705 Feb 13 11:32 component---src-pages-page-2-js-c533758acaabdefda86a.js.map
drwxr-xr-x  10 user  staff     320 Feb 13 11:31 icons
-rw-r--r--   1 user  staff   12488 Feb 13 11:32 index.html
-rw-r--r--   1 user  staff     986 Feb 13 11:32 manifest.webmanifest
drwxr-xr-x   3 user  staff      96 Feb 13 11:32 page-2
drwxr-xr-x   8 user  staff     256 Feb 13 11:32 page-data
drwxr-xr-x   4 user  staff     128 Feb 13 11:31 static
-rw-r--r--   1 user  staff     141 Feb 13 11:32 styles-46e0e26cf4fc3c90315b.js
-rw-r--r--   1 user  staff     107 Feb 13 11:32 styles-46e0e26cf4fc3c90315b.js.map
-rw-r--r--   1 user  staff    5402 Feb 13 11:32 styles.d5ef0abb16ee382cea7f.css
-rw-r--r--   1 user  staff    3590 Feb 13 11:32 webpack-runtime-26de3d9d79d4abbbc555.js
-rw-r--r--   1 user  staff   16498 Feb 13 11:32 webpack-runtime-26de3d9d79d4abbbc555.js.map
-rw-r--r--   1 user  staff    2213 Feb 13 11:32 webpack.stats.json

 user  ~/work/gatsby-nullify-index-html   master  ls -l public/page-2
total 24
-rw-r--r--  1 user  staff  9876 Feb 13 11:32 index.html


```



Sample repository : https://github.com/ashoksudani/gatsby-nullify-index-html

**Comment by AndrewKMoses** [comment]
@ashoksudani hey did you solve this issue? Facing the same problem. Remove trailing slash plugin didn't work for me as well.

**Comment by ashoksudani** [comment]
@AndrewKMoses Correct, I did not waste more time and later moved to NextJs. 

NextJs works exactly I expected and I did not have any specific requirements of features specifically provided by Giatsby.

**Comment by muzhaqi16** [comment]
I am looking into doing the same thing, but I have been unsuccessful. Hopefully, they will come up with a solution.
