### ISSUE TITLE
[gatsby-plugin-offline] - after rebuild I need to refresh the page twice

### ISSUE THREAD

**Issue by Bram-Zijp** [gatsbyjs/gatsby#21409]
## Summary
While using the `gatsby-plugin-offline`, having visited a page before, changes included in a rebuild that occurred after that, don't reflect before reloading a page twice/navigating back and forward in the page itself.

Another finding; 

When I use the following config in my `gatsby-config.js` file:
```
    },
    `gatsby-plugin-offline`,
    {
```
It updates after the second reload as illustrated in *case 1*.
When I use the following config in my `gatsby-config.js` file:
```
   },
    {
      resolve: `gatsby-plugin-offline`,
    },
    {
```
It doesn't updated after n+ refresh. It will only update when I open the DevTools and refresh.

### Environment (if relevant)
```
  System:
    OS: Linux 5.3 Pop!_OS 19.10
    CPU: (12) x64 Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 13.7.0 - /home/linuxbrew/.linuxbrew/bin/node
    Yarn: 1.21.1 - /home/linuxbrew/.linuxbrew/bin/yarn
    npm: 6.13.6 - /home/linuxbrew/.linuxbrew/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.87
    Firefox: 72.0.2
  npmPackages:
    gatsby: ^2.19.16 => 2.19.16
    gatsby-image: ^2.2.40 => 2.2.40
    gatsby-plugin-manifest: ^2.2.41 => 2.2.41
    gatsby-plugin-netlify: ^2.1.32 => 2.1.32
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-offline: ^3.0.34 => 3.0.34
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5
    gatsby-plugin-styled-components: ^3.1.19 => 3.1.19
    gatsby-plugin-typescript: ^2.1.27 => 2.1.27
    gatsby-source-filesystem: ^2.1.48 => 2.1.48
    gatsby-source-prismic-graphql: ^3.4.1-alpha.0 => 3.4.1-alpha.0+474efaa
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Bram-Zijp** [comment]
@LekoArts This starter can reproduce the issue: https://www.gatsbyjs.org/starters/Vagr9K/gatsby-material-starter/

**Comment by myagoo** [comment]
I think this behavior is intended, see https://developers.google.com/web/tools/workbox/modules/workbox-strategies#cache_first_cache_falling_back_to_network

**Comment by wardpeet** [comment]
I've seen this on .org too.

**Comment by blogwebpl** [comment]
I confirm that, you must reload the page twice to see the changes. First reload download changes but not show. Second reload show changes.

**Comment by Bram-Zijp** [comment]
Looking

> I think this behavior is intended, see https://developers.google.com/web/tools/workbox/modules/workbox-strategies#cache_first_cache_falling_back_to_network

You might be right. I believe this plugin uses/used [stale-while-revalidate](https://developers.google.com/web/tools/workbox/modules/workbox-strategies#stale-while-revalidate) by default.

Thinking about it now, I think the service worker needs to be configured to update the page if cached items are changed in an stale-while-revalidate model. Found this recipe, which looks like an example. https://serviceworke.rs/strategy-cache-update-and-refresh_service-worker_doc.html
