### ISSUE TITLE
[gatsby-transformer-remark] Inline footnote return links

### ISSUE THREAD

**Issue by HarshilShah** [gatsbyjs/gatsby#21419]
## Summary

I’m not entirely sure what the canon style is since the original Markdown itself doesn’t include support for footnotes, but in most sites I’ve seen (including [the one run by John Gruber](https://daringfireball.net/2020/02/df_tootbot_is_fully_operational), who created Markdown) return links from footnotes are present in the last `<p>` or similar block level tag, rather than as a separate top level link after it. MDX also supports inline footnote return links right out of the box, as tested here: [mdxjs.com/playground](https://mdxjs.com/playground/)

If not changing the current rendering, an option to have inline return links to match this style would be great.

### Basic example

```
This is a test[^1].

[^1]: footnote
```

currently generates:

```
<li id=“fn-1”>
   <p>footnote</p>
   <a href="#fnref-1" class="footnote-backref">↩</a>
</li>
```

but it should generate:

```
<li id=“fn-1”>
   <p>footnote<a href="#fnref-1" class="footnote-backref">↩</a><p>
</li>
```

### Motivation

It changes footnote rendering to match what I think is the more commonly used formatting on the web.

**Comment by jbhannah** [comment]
I'm going to test disabling footnotes in the plugin configuration and manually adding remark-footnotes to the set of dependent plugins.

**Comment by sebastianwr** [comment]
I'd also be very interested in a solution as the current format is quite ugly and cumbersome to style in CSS: I also tried using jamessimone/gatsby-remark-footnotes but the footnotes are still generated as separate` <p>` and `<a>`
