### ISSUE TITLE
Gatsby ssr / hydration replacing components

### ISSUE THREAD

**Issue by jenkshields** [gatsbyjs/gatsby#21418]
## Description

When navigating directly (via URL or on refresh) to a 'gallery' page on my site (like [this one](https://jenniferkshields.nz/shot-on-iphone-january-2020)), a div that contains a grid of images is unstyled/replaced with a blank div. This happens during hydration just after refresh

I've built a site using Gatsby, sourcing from Prismic.io, and using styled-components to style. I use framer-motion for page transitions and have added my layout component to gatsby-browser so that only page content gets transitioned, and have added similar code to gatsby-ssr to fix some initial ssr errors. I also ran into some ssr errors relating to a media query library that didn't support ssr, and that has since been resolved, leaving only this issue. ([More info on those ssr issues here](https://stackoverflow.com/questions/60104190/gatsby-build-ssr-swapping-out-components-causing-display-errors))

### Steps to reproduce

[A full repository is available here.](https://github.com/jenkshields/jenniferkshields.nz/)

This issue only appears when built, not in development.

### Expected result

The DOM/styling should remain the same.

### Actual result

The DOM/styling gets modified by SSR / hydration, only when a page is refreshed or navigated to via direct URL. Using the site's navigation works as expected.

### Environment

Local: 
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
    Yarn: 2.0.0-rc.28 - ~/.nvm/versions/node/v10.16.1/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.5

The site is built via CircleCI 2.1 (using a node 10 docker image and yarn v2) and deployed on Netlify.

**Comment by TylerBarnes** [comment]
Hey @jenkshields, I pulled down your repo to give it a try. First I had a lot of weird problems with your yarn setup so I deleted it all and used npm and I was able to run the repro but now it looks like I need a prismic access token to run the site. 

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
