### ISSUE TITLE
(examples/docs) Gatsby configurations written in Typescript

### ISSUE THREAD

**Issue by Js-Brecht** [gatsbyjs/gatsby#21414]
### Summary

I wonder if it would make sense to include something like I've done in [this starter](https://github.com/Js-Brecht/gatsby-starter-pnpm-ts) in the list of examples setups.

Deviation:

- This starter is obviously pretty specific to my uses.  It includes a non-official typescript plugin (which also provides graphql query interface generation, btw) and it also includes support for `pnpm`.  However, it could be generalized, to exclude any of my personal preferences for setup

### Motivation

I think that using Typescript while defining your Gatsby configuration files would be a considerable benefit.  You get full type support, making it easier, and less error prone, to design your API endpoints.

I also think moving to Typescript for this kind of thing will encourage plugin developers to write stricter code (with static types, especially), which generally makes it easier to read/maintain, but ultimately makes it easier for consumers to use.

I have noticed that there are quite a few plugins out there which are already written in Typescript.  This is great for developing the plugins, but as of right now, it doesn't really carry over much into using them.  With a setup like the one I laid out in my starter, and type interfaces exported by plugin authors, the full benefit of writing the plugins in Typescript will be available to the consumers as well.

### Additional Information

Pay close attention to the files in the [`.gatsby` subdirectory](https://github.com/Js-Brecht/gatsby-starter-pnpm-ts/tree/master/.gatsby).  The way those are used should be pretty clear.  The only thing that's special about any of them is in `gatsby-config`, which uses some type unions to describe the `plugins` array of the configuration export.  Also, the export for `gatsby-node` and `gatsby-config` are functions, which allows you to put those files anywhere, and still know where the project root is without much fuss... that's the only reason I did it that way.

I also use `ts-node` so that the file are usable without having to go through the extra effort to transpile them.  This makes it especially useful if you want to import extra modules/json files, or even any of your `src` files, into any of your configuration files (e.g. I've used json files to describe some data structures in my `gatsby-node` using this method, or even imported components from `src` for use in my `gatsby-browser`/`gatsby-ssr`).  If you were going through the trouble of transpiling the files, you would wind up with an interesting `outDir`, and most likely with duplicates of the files you imported (assuming they weren't located inside of that `.gatsby` dir).

Another thing I like about having those files under a `.gatsby` subdirectory is my project root doesn't get polluted with extra files/modules (or more subdirectories to store those files/modules) that are used in my configurations.  It's a better separation of concerns, IMO.  Granted, that's easy to accomplish even without Typescript, but this kind of setup pushes things more that direction.

### Draft the doc / Open Pull Request

I'm certainly willing to write up a howto doc on this type of setup, assuming you guys agree that it is something you want.

**Comment by marcysutton** [comment]
Hey there, thanks for the issue! It's a bit unclear what you're hoping to achieve with this initiative. Can you expand on what changes would be involved so we can determine feasibility and scope?

**Comment by Js-Brecht** [comment]
I'm not suggesting any real changes to Gatsby; just an addition to the documentation and examples.  I'm suggesting that we document a method for users to use Typescript when writing their Gatsby configuration files.  I think if we made that whole setup really easy, it might encourage users to use it, which could prompt developers to move that direction as well.  The end result, ideally, would be self-documenting plugins and other build processes, which would enable the use of intellisense and the like, not to mention build-time type checking which can help catch bugs in the config.

I know I find it really helpful, so I just thought I would share.

Eventually it would be great if Gatsby would be able to consume Typescript configuration files automatically, but that's not really very feasible at the moment.  It would require something to be added to the build chain that does the translation (e.g. `ts-node), and that can cause a performance hit (and potentially a host of other problems)... so it would have to be opt-in, at the very least.

**Comment by Js-Brecht** [comment]
If, on the other hand, you think that it's maybe too much to be throwing in there, I totally understand.

**Comment by LekoArts** [comment]
Hello Jeremy,

we think that the explanation + setup should go into a blogpost of your own rather than into our docs / codebase. We currently don't have the bandwidth to investigate all available TS options for Gatsby and document them all (as your approach is certainly opinionated and there are other options). Best case scenario would be that all this setup is included, but that will take a while to implement. You can follow https://github.com/gatsbyjs/gatsby/issues/18983 for that.

Thanks for the write-up here and the starter. If you haven't already, feel free to submit the starter to the starters showcase and let us know if/when you have written something about that setup. Thanks!
