### ISSUE TITLE
Calling javascript in gatsbyjs

### ISSUE THREAD

**Issue by expatguideturkey** [gatsbyjs/gatsby#21425]
How to call JavaScript in a gatsbyjs website. I am using below code but don't understand where to add the JS code. I am using this source https://codepen.io/jackocnr/pen/EyPXed 

Please advise.

HTML file
```
<h1>International Telephone Input - BOOTSTRAP INPUT GROUP</h1>
<form>
  <div class="input-group">
    <input type="tel" class="form-control">
    <span class="input-group-addon">Tel</span>
  </div>
  <br>
  <div class="input-group">
    <input type="tel" class="form-control">
    <span class="input-group-addon">Tel</span>
  </div>
</form>
```

CSS File

```
body {
  margin: 20px;
}
form {
  width: 300px;
}

// workaround
.intl-tel-input {
  display: table-cell;
}
.intl-tel-input .selected-flag {
  z-index: 4;
}
.intl-tel-input .country-list {
  z-index: 5;
}
.input-group .intl-tel-input .form-control {
  border-top-left-radius: 4px;
  border-top-right-radius: 0;
  border-bottom-left-radius: 4px;
  border-bottom-right-radius: 0;
}
```

JS file
```
$("input").intlTelInput({
  utilsScript:
    "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/8.4.6/js/utils.js"
});
```

**Comment by Js-Brecht** [comment]
Mixing `jQuery` and `React` isn't usually recommended.  In React land, it's usually better to just use `React`.  There are circumstances where you might still need to do it the way you're trying to here, but I don't think this is one of them.

You could try using [react-intl-tel-input](https://www.npmjs.com/package/react-intl-tel-input).

Your HTML file will become a React file, so your form will become a React component tree.  Your individual telephone inputs will become those `react-intl-tel-input` components.

Maybe something like [this](https://codesandbox.io/s/youthful-grothendieck-vr5rp)

**Comment by LekoArts** [comment]
Thank you for opening this!

As Jeremy already said I also wouldn't recommend mixing jQuery and React. However, if you absolutely must include scripts into your HTML, you can use APIs for that:
https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by expatguideturkey** [comment]
@Js-Brecht Thank you for your response. If I use this inside netlify form as shown below is this going to work and I will recieve input values.

 ```
<form 
            name="contact" 
            method="POST" 
            action="/success/" 
            data-netlify="true"
            data-netlify-honeypot="bot-field" 
            class="needs-validation"
            novalidate netlify
            >

<div className="half left cf">
              <input type="hidden" name="form-name" value="contact" />
              <input type="text" name="name" id="input-name" className="form-control" placeholder="Your Name" required /> 
              <input type="email" name="email" id="input-email" className="form-control" placeholder="Email address" title="Email (format: your@example.com)" required  />
              <div className="invalid-feedback">
                Please enter a valid email address.
              </div>
<IntlTelInput id="phonenum" name="phonenum" containerClassName="intl-tel-input" inputClassName="form-control" defaultCountry="tr"/>
<input type='submit' id="input-submit" className="btn btn-primary btn-lg btn-block" value="Send Message"
            />
            </form>
```

**Comment by Js-Brecht** [comment]
Yes, you should.  If you look [here](https://github.com/patw0929/react-intl-tel-input/blob/master/src/components/IntlTelInput.js#L1309-L1330) and [here](https://github.com/patw0929/react-intl-tel-input/blob/master/src/components/TelInput.js#L57-L77), you'll see that `IntlTelInput` resolves down to a normal `<input>` element.

**Comment by Js-Brecht** [comment]
However, you will want to use the `fieldName` property, instead of the `name` property.  See [this](https://github.com/patw0929/react-intl-tel-input/blob/master/src/components/IntlTelInput.js#L1340-L1341)

Same with `fieldId` instead of `id`. Property description [here](https://github.com/patw0929/react-intl-tel-input/blob/master/src/components/IntlTelInput.js#L1342-L1343)

**Comment by expatguideturkey** [comment]
> fieldId

@Js-Brecht Thanks a lot for your assistance.
