### ISSUE TITLE
gatsby-link/createRedirect doesn't properly handle static content

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/gatsby#21420]
## Description
I'm attempting to redirect `/terms/` to a pdf that's sourced from WP and while the server side redirect works gatsby doesn't handle it well client side.

### Steps to reproduce
here is my code:

```js
const {
    data: {
      wpgraphql: { terms },
    },
  } = await graphql(`
    query {
      wpgraphql {
        terms: mediaItem(id: "TERMS-CONDITIONS-2020", idType: SLUG) {
          mediaItemUrl
          mediaItemId
          modified
          mediaFile {
            publicURL
          }
        }
      }
    }
  `);

  createRedirect({
    fromPath: "/terms/",
    toPath: `${terms.mediaFile.publicURL}`,
    isPermanent: true,
    redirectInBrowser: true,
  });

```

### Expected result

When clicking the link to `/terms/` on the client side I'd expect it to open the PDF file and not 404 or hang like it currently is. My guess is we just need to detect if links start with `/static` and make them a non-gatsby link.

### Actual result

currently it 404s. ~~I did figure out a work around, by prepending the Site URL the link works correctly after a couple second delay.~~ Nvm, doesn't work, still gives 404 then routes on refresh.

### Environment

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.15.0 - /tmp/yarn--1581573867501-0.4081065427154833/node
    Yarn: 1.22.0 - /tmp/yarn--1581573867501-0.4081065427154833/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.87
    Firefox: 72.0.2
  npmPackages:
    gatsby: ^2.18.3 => 2.19.12 
    gatsby-gravityforms-component: ^2.0.0 => 2.0.0 
    gatsby-image: ^2.2.33 => 2.2.40 
    gatsby-plugin-google-tagmanager: ^2.1.24 => 2.1.25 
    gatsby-plugin-manifest: ^2.2.29 => 2.2.41 
    gatsby-plugin-netlify: ^2.1.30 => 2.1.32 
    gatsby-plugin-offline: ^3.0.23 => 3.0.34 
    gatsby-plugin-preact: ^3.1.24 => 3.1.26 
    gatsby-plugin-react-helmet: ^3.1.15 => 3.1.22 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sass: ^2.1.26 => 2.1.28 
    gatsby-plugin-sharp: ^2.3.3 => 2.4.5 
    gatsby-plugin-sitemap: ^2.2.26 => 2.2.27 
    gatsby-source-filesystem: ^2.1.38 => 2.1.48 
    gatsby-source-graphql: ^2.1.24 => 2.1.33 
    gatsby-source-gravityforms: ^1.0.15 => 1.0.15 
    gatsby-transformer-json: ^2.2.25 => 2.2.26 
    gatsby-transformer-sharp: ^2.3.5 => 2.3.14

**Comment by wardpeet** [comment]
Thanks @moonmeister! The code we're looking for are in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/navigation.js#L83-L118.

I don't see the immediate bug as we should reload if we can't find a page-data file. That's all I can tell so far.  If someone can dig in, that would be great. Maybe you can do that @moonmeister   😄

**Comment by jzabala** [comment]
I tested this issue with Gatsby 2.23.3 and it seems to be working.

CodeSanbox: https://codesandbox.io/s/inspiring-dirac-7yzhp

Example: https://7yzhp.sse.codesandbox.io/

In the example `Go to page 2` is a redirect to a pdf file.

**Comment by moonmeister** [comment]
Hey, Thanks for taking a look. Maybe it got fixed but I am seeing two issues with you repro that don't match the details above. First, my `/terms/` page doesn't exist in  anyway other than in the redirect, you have a `page-2` that exists and is redirected. Second, My PDF is a relative url (i.e. `/Terms-and-conditions.pdf`) not an absolute url (i.e. `https://example.com/Terms-and-conditions.pdf`). If you could test under these conditions that'd be great, thanks.

**Comment by jzabala** [comment]
Hi @moonmeister, I tried with you details and it works but for some reason only with the production build. I deployed it in Netlify: https://csb-7yzhp.netlify.app/. Clicking `Go to page 3`, opens up the PDF.

**Comment by moonmeister** [comment]
Cool, I'll double check when I'm not on a phone but maybe this got resolved.

**Comment by moonmeister** [comment]
Looks like this did get resolved, closing.
