### ISSUE TITLE
Bad Links in GraphQL Node Types Creation

### ISSUE THREAD

**Issue by alexfornuto** [gatsbyjs/gatsby#21437]
## Summary

The links in [this section](https://www.gatsbyjs.org/docs/schema-gql-type/#gqltype-creation) of the **GraphQL Node Types Creation** page are broken

### Motivation

> Why should we document this and who will benefit from it?

It's already documented, but it's broken.

## Steps to resolve this issue

Identify what those links are supposed to point to and update them.

Also consider a link validator in your CI process.

### Open a pull request

> - [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

If Y'all wanna point me to where they should go, I can make a PR if you want. [This](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/types/built-in-types.js) looks like it may be the new location for the first link, but I can't be sure.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!
The mentioned issue at the top is the umbrella issue about that:
https://github.com/gatsbyjs/gatsby/issues/14228

Please comment there if you're interested in fixing parts of the docs. Thanks!
