### ISSUE TITLE
Is there anyway to self host Gatsby preview? 

### ISSUE THREAD

**Issue by sharanrprasad** [gatsbyjs/gatsby#21435]
## Summary

What problem(s) did you run into that caused you to request additional documentation? What questions do you think we should answer? What, if any, existing documentation relates to this proposal?

Some recommended topics to cover:

- List the topics you think should be here.
- This list does not need to be exhaustive!

### Motivation

Why should we document this and who will benefit from it?

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by LekoArts** [comment]
Thank you for opening this!

We think that Gatsby Preview is a great product and will benefit you already on the free tier, so we'd be happy to see you try it. You can try to replicate the behavior by running your own server with `gatsby develop` and a `___refresh` webhook. This similar issue should give you some insights: https://github.com/gatsbyjs/gatsby/issues/16616

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
