### ISSUE TITLE
How to create subdirectory page from dynamic page generated from template?

### ISSUE THREAD

**Issue by apmsooner** [gatsbyjs/gatsby#21444]
Assuming i have a page template that creates unique url based on title of content, how could i extend the url with a subdirectory that serves another page leveraging context from existing url?

here's a real world example: https://www.wyndhamhotels.com/laquinta/sebring-florida/la-quinta-sebring/rooms-rates

The /rooms-rates part is what i'm after as another page that leverages context from existing path.

I've tried a <Router /> component using reach router in the existing page template passing variable of existing url but leads to 404 still. Not sure best way to approach this.

Here's an example of what I tried to do with reach router in the hotel page template where i'm passing variable from graphql:
`<Router>
        <Rooms path={`${hotel.path.alias}/rooms`} />
      </Router>`

I know that i can use client path structure for known path like order/:orderId but in my case, i have a dynamic path structure that i'm trying to build on to.

**Comment by LekoArts** [comment]
Hi!

Using client-only paths on such templates should work. Could you please post a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by apmsooner** [comment]
I don't know what the correct approach is to my problem thats why i poised it as a question for advice on how to do such a thing so creating a minimal reproduction doesn't make sense if its not a bug but more a request for advice. How do you do client-only paths with a template when the path is dynamically created and thus no pattern to identify with? All the examples for client only paths are using known paths like /order, /blog, /article, etc... or just root /*.

**Comment by apmsooner** [comment]
I think i may have figured this out but would appreciate any feedback if this is indeed the right approach. I modified the createPage function in gatsby-node.js by adding matchPath like so:

`hotels.data.allHotel.edges.forEach(({node}) => {
    createPage({
      path: node.path.alias,
      matchPath: `${node.path.alias}/*`,
      component: path.resolve(`./src/templates/hotel.js`),
      context: {
        slug: node.path.alias,
      },
    })
  })`

so now in the template i've moved everything that was originally rendering in the hotel template to a separate component and defined router as such:

`const HotelPage = ({data}) => {
  const hotel = data.hotel;
  return (
    <Layout>
      <Router basepath={hotel.path.alias}>
        <HotelDefault path="/*" hotel={hotel} />
        <HotelRooms path="/rooms" hotel={hotel} />
      </Router>
    </Layout>
  )
};`

So this seems to now resolve anything after the basepath /* to the default component and when /rooms is in path, serves up a specific component with its own content. I can pass the hotel variable extracted from graphql in template as props and it all seems to work well. I'm wondering now if i ever had to create a redirect for the basepath if all subpaths would behave along with that?

**Comment by apmsooner** [comment]
My approach works fine. Closing issue.
