### ISSUE TITLE
Running Gatsby app from file

### ISSUE THREAD

**Issue by bitttttten** [gatsbyjs/gatsby#21454]
## Summary

I am looking to run Gatsby without a webserver, and just run the app from opening the index.html file in a browser. This is mainly to get the app running in an environment like PhoneGap. Is it possible to do it at the moment? If so what are the steps to ensure it will work?

## Relevant information

A hurdle I ran into is that gatsby expects the app to be served from the root, as all paths start with "/". Even after fixing this in index.html, I noticed that the app still wasn't running although it didn't produce any errors in the console. I assumed it was perhaps related to lazy loading components or when fetching page-data.

**Comment by blainekasten** [comment]
Hey @bitttttten 

Gatsby is typically not served with a server, but via a CDN. I'm not sure what your environment is like, but you've probably noticed that when you run `gatsby build` it generates a `public/` folder. This will have all of your html files and assets. You'll need to somehow serve those files in your environment. You could consider running `gatsby serve` which is a light server to make your files accessible at a url.

It's hard to know what advice to give you without knowing the environment. 

I'm going to close this issue for now as it's not revealing an issue with Gatsby's source for us to fix.  Please keep the conversation going though so we can continue to support you!
