### ISSUE TITLE
gatsby-image with media quieres and fixed image sizes

### ISSUE THREAD

**Issue by qramilq** [gatsbyjs/gatsby#21455]
Hi!

I have a task to make component with image. For this goals i want to use the `Img` component from `gatsby-image`

For example, I have 2 types of device's breakpoints
`mobile-device`: 0-959px;
`desktop-device`: 960px+

I have some design for this, which says that my image have different sizes for different device
`mobile-image-size`: 400 * 600px
`desktop-image-size`: 700 * 900px

So I need, that 
on `mobile-device` my image's size will be `mobile-image-size`,
on  `desktop-device` : `desktop-image-size`

So if it's retina display i want that 
on `mobile-device` my image's size will be `mobile-image-size` *2,
on  `desktop-device` : `desktop-image-size`*2

What the best solution to make this with gatsby-image? Thank's

**Comment by blainekasten** [comment]
This documentation should help you query for specific media query related images.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/README.md#art-directing-multiple-images

I'm going to close this issue as we're not reporting anything wrong with Gatsby to be fixed. Feel free to keep the conversation going if you need more support!
