### ISSUE TITLE
Gatsby Image cache is reset on page refresh or hard navigation change, does not properly cache previously downloaded images

### ISSUE THREAD

**Issue by jamessimone** [gatsbyjs/gatsby#21452]
## Description

Found while investigating https://github.com/timhagn/gatsby-background-image/issues/92 - the empty object initialized as the gatsby-image cache is always reset on page refresh or hard navigation changes, forcing the browser to re-download images unnecessarily and causing the placeholder image to be shown again. (The placeholder image, it should be noted, _is_ properly cached by the browser).

### Steps to reproduce

Refresh a page where gatsby-image images are used with your network pane open in Developer Tools. Notice that any images loaded using gatsby-image always get re-downloaded.

### Expected result

It would be amazing if gatsby-image properly cached downloaded images to limit network requests.

### Actual result

Images are repetitively downloaded, particularly evident on mobile.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by jamessimone** [comment]
@LekoArts hi there. A minimal reproduction is available using any gatsby starter with images.

For example, I just spun up a new instance of gatsby-starter-blog:

1. use "gatsby new"
2. select "gatsby-starter-blog"
3. run the "develop" command
4. navigate to localhost:8000
5. open the network pane in your browser. refresh the page several times.
6. observe that the placeholder image is served from the cache, while the gatsby astronaut image is re-downloaded every refresh. I would expect that it would only be re-downloaded the first time the page loads, and be cached for subsequent renders / refreshes

**Comment by jamessimone** [comment]
![gatsby-starter-blog-network-pane](https://user-images.githubusercontent.com/16430727/75268410-af992300-57b4-11ea-9c18-7e24eda93e22.JPG)

**Comment by KyleAMathews** [comment]
@jamessimone hey this is as expected. The placeholder is in the page data so it isn't actually downloaded separately as it's base64 encoded. That's what "memory cache" means. The full image will be served from the cache if your server is setup to do so which I believe the local dev server is not. So I believe everything is working correctly!

**Comment by jamessimone** [comment]
@KyleAMathews thanks for the context and the detailed response — much appreciated
