### ISSUE TITLE
feature(www): Persist filters on Site Showcase in opened modals

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21467]
## Description

Keep current filters when opening and closing modals in the site showcase.

### Steps to reproduce

1. Go to https://gatsbyjs.org/showcase
2. Click on some filters (for example, "Accessibility" and "Blog")
3. Click on one of the sites to open a modal
4. Close the modal

### Expected result

* When opening the modal, the current filters (?filters=Accessibility&filters=Blog) should remain in the URL
* The "Next" and "Previous" links should lead to the next and previous sites with the filters applied
* ~~When closing the modal, the current filters should still be applied to the site~~

### Actual result

As soon as the modal is opened, the filters disappear immediately from the URL. The "Next" and "Previous" links show the next and previous items out of the global list of showcased sites.

~~When the modal is closed, the filters are still gone.~~

### Environment

N/A

### Related Issues

I believe this is related to my recent refactors #21330 and #21352

**Comment by tsriram** [comment]
I'm working on this 🙏
