### ISSUE TITLE
Unable to replace avatar in Using a Theme tutorial

### ISSUE THREAD

**Issue by tsongas** [gatsbyjs/gatsby#21464]
## Description

I just started the Using a Theme tutorial and followed these instructions to replace the avatar:

```
Replace your avatar
The blog theme starter ships with a solid gray image for the avatar. Add your own avatar by choosing the image you want, and overwriting the file located at /content/assets/avatar.png.
```

Once I did that, the following appeared in the console:

```
info changed file at /Users/chris/Documents/Gatsby/my-blog/content/assets/avatar.png
success createPages - 0.090s
success run queries - 0.113s - 1/1 8.87/s
success Generating image thumbnails - 0.172s - 3/3 17.48/s
success write out requires - 0.004s
info changed file at /Users/chris/Documents/Gatsby/my-blog/content/assets/avatar.png
```

However, the image refuses to update in the browser. I tried clearing my browser cache as well as restarting `gatsby develop` in the console.

### Steps to reproduce

```
gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme
cd my-blog
gatsby develop
```
then replace `/content/assets/avatar.png` with a different image.

### Expected result

Avatar image should update in the browser.

### Actual result

Avatar image stays the same.

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 13.0.5
  npmGlobalPackages:
    gatsby-cli: 2.8.29

**Comment by tsongas** [comment]
Just noticed something curious, now when I refresh the browser I see a fuzzy version of the new avatar image for a split second, then it is replaced by the old avatar image.

**Comment by elykahn** [comment]
Followed your steps to reproduce this bug but it instantly updates the avatar as expected on my system. Not sure if this is a bug that was fixed in the last gatsby-cli update, I'm running 2.8.3 on Catalina.

**Comment by laurieontech** [comment]
You mentioned clearing your browser cache, did you run `gatsby clean` as well? Wondering if something else cached unexpectedly. As with the previous commenter, I don't see this behavior when trying to reproduce it.

**Comment by laurieontech** [comment]
Hey @tsongas I'm going to close this for now and assume it solved your issue. If not, please feel free to reopen. Thanks!
