### ISSUE TITLE
documentation for implementing sidebar/menu

### ISSUE THREAD

**Issue by groovehost** [gatsbyjs/gatsby#21460]
Hi! I'm totally new to Gatsby and React alike, and I'm working on putting together a simple static port of a Wordpress blog I currently have set up. One big issue I'm running into is that I can't figure out how to implement a sidebar menu and can't really find any good documentation on the topic. Is there anywhere that you can point me? If not, I'd really recommend including some documentation on that on your website!

**Comment by LekoArts** [comment]
Thank you for opening this!

Depending on how your site/stack will look in the end you'll need to change some details but generally speaking you have two steps:

1) Define the data and/or shape for the navigation somewhere. This could be in Wordpress or in a local file or generated from e.g. your frontmatter in markdown files. Whatever source you have you'll use Gatsby's GraphQL data layer to access this data. So I'd recommend going through our [tutorial](https://www.gatsbyjs.org/tutorial/) to learn the basics and read about [GraphQL in Gatsby](https://www.gatsbyjs.org/docs/graphql/).

2) Once you have your data available it's "just" React code you have to write. You can use Google to find tons and tons of content, e.g.: https://dev.to/jsmanifest/create-a-modern-dynamic-sidebar-menu-in-react-using-recursion-36eo

The part where those tutorials define the data/shape for the navigation in e.g. a variable you'll use the data coming from Gatsby's GraphQL data layer.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
