### ISSUE TITLE
'gatsby develop' throwing Syntax error in IE11

### ISSUE THREAD

**Issue by jlouis-onrr** [gatsbyjs/gatsby#21474]
## Description

When running `gatsby develop` and then viewing the site in IE11, seeing a white screen of death, with the following error in the console:

Syntax error @ commons.js (219675,70)
`const getCharacterClassEscapeSet = (character, unicode, ignoreCase) => {`

### Steps to reproduce

Clone the following repo `git@github.com:ONRR/nrrd.git`,  run `npm install`, run `gatsby develop` and view in IE11, then :sob:

### Expected result

Expecting IE11 to have died by 2020, but that didnt happen, so hoping to see the site as I do in all the other great browsers.

### Actual result

Get white screen of death, with console log error above

### Environment

```
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/louisj/.windows-build-tools/python27/python
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: ^2.18.18 => 2.18.18
    gatsby-image: ^2.2.29 => 2.2.36
    gatsby-plugin-layout: ^1.1.16 => 1.1.18
    gatsby-plugin-manifest: ^2.2.23 => 2.2.33
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-mdx: ^1.0.57 => 1.0.62
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1
    gatsby-plugin-offline: ^3.0.16 => 3.0.29
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.18
    gatsby-plugin-sharp: ^2.3.7 => 2.3.7
    gatsby-remark-autolink-headers: ^2.1.23 => 2.1.23
    gatsby-source-filesystem: ^2.1.33 => 2.1.42
    gatsby-source-graphql: ^2.1.21 => 2.1.28
    gatsby-theme-apollo: ^3.0.0-beta.0 => 3.0.0-beta.0
    gatsby-transformer-react-docgen: ^5.0.25 => 5.0.25
    gatsby-transformer-sharp: ^2.2.23 => 2.3.9
    gatsby-transformer-yaml: ^2.2.16 => 2.2.20
```

**Comment by wardpeet** [comment]
Hey, you're using an NPM module that doesn't transpile to IE11. If you know which npm package it is you can use https://www.gatsbyjs.org/packages/gatsby-plugin-compile-es6-packages/ to fix it.

Thank you for opening this, @jlouis-onrr

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
