### ISSUE TITLE
Trying to make placeholder image disappear after original image loaded

### ISSUE THREAD

**Issue by 1244k** [gatsbyjs/gatsby#2147]
I am trying to load a list of images into an index page. I have already populated data into the index page, but the problem is the "placeholder" base64 image does not want to disappear, it just got appended below the "loaded" image. Where should the `onLoad` function be implemented like in the `gatsby-remark-images` and [this](https://www.perpetual-beta.org/weblog/silky-smooth-image-loading.html)?

**Comment by benjaminhoffman** [comment]
hi @1244k, did you get your issue resolved?  Have you looked into https://www.gatsbyjs.org/packages/gatsby-image/ ?  That should address your problem.  Closing this issue now bc of lack of recent activity but feel free to re-open if you'd like to continue to troubleshoot.
