### ISSUE TITLE
perf(www): low-hanging fruit for reducing gatsbyjs.org bundle

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21470]
Recently @pieh took a bundle analyzer off a recent build of gatsbyjs.org:

![Gatsby sitemap](https://user-images.githubusercontent.com/1278991/74564695-7cd56c00-4f24-11ea-8837-5837c75c182b.png)

I noticed a couple of things that stood out as unnecessary that we should probably fix:

* An SVG file, `8-double-work.svg` used in a recent blog post, is included for some reason
* A lot of components used in MDX were made global (#19036) to solve a localization related issue. Some of these components have significant footprints, like `layer-model`, which pulls in `layer-icon`. We need to figure out another solution so that these components don't clutter up the bundle.
* A lot of the `algolia-styles` can probably be lazy-loaded. Even though the search form is included in every page, a lot of these styles involve the actual dropdown and can be loaded later.
* [FragmentsQuery](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/api-reference/doc-static-queries.js#L23) is included in the bundle for some reason, even though it's only used in the GraphQL API page.

**Comment by wardpeet** [comment]
Thanks for letting us know, i'll be changing our bundle strategy so it might solve this problem partially. .org is a mess though 😛
