### ISSUE TITLE
bug(www): Add missing <FooterLinks> from gatsbyjs.org pages

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21482]
## Description

Add missing footer links to the following pages/templates

* https://gatsbyjs.org/blog/tags
* https://www.gatsbyjs.org/blog/tags/themes (and other tag pages)
* https://www.gatsbyjs.org/creators/

**Comment by guilhermedeandrade** [comment]
I'd be glad to help with this!
