### ISSUE TITLE
is markdownRemark still available in gatsby@2?

### ISSUE THREAD

**Issue by oprogramador** [gatsbyjs/gatsby#21484]
After upgrading to `gatsby@2`, I don't obtain any longer the `data` field in the `Template` component props (I need `data.markdownRemark.html`).

I noticed https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/ mentions `markdownRemark` but it doesn't help me.

On the other hand, in the props, I see `pageResources.component` but inserting this component makes an empty page (beside the footer).

**Comment by oprogramador** [comment]
I obtain the `data.markdownRemark.html` field after using `graphql` back (`import { graphql } from 'gatsby';`) because previously I deleted it, having the query as only a template string.

However, I still have a problem with CSS.

**Comment by oprogramador** [comment]
You write `Include PostCSS plugins in your postcss.config.js file` but I don't have any `postcss.config.js` file.

**Comment by LekoArts** [comment]
Thank you for opening this!

MarkdownRemark is still available in v2. Seems like you resolved your issue. About PostCSS: You need to create that file yourself for the config.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by oprogramador** [comment]
@LekoArts 

the problem is the page with gatsby@1 looks in this way:
<img width="1427" alt="Screenshot 2020-02-17 at 11 08 10" src="https://user-images.githubusercontent.com/8701039/74650320-b525b600-5181-11ea-9e8a-f9e9772eabbe.png">

with gatsby@2 in this way:
<img width="986" alt="Screenshot 2020-02-17 at 11 26 08" src="https://user-images.githubusercontent.com/8701039/74650475-206f8800-5182-11ea-87e4-b0054230dafe.png">

and with gatsby@2 locally:
<img width="1029" alt="Screenshot 2020-02-17 at 11 26 20" src="https://user-images.githubusercontent.com/8701039/74650490-28c7c300-5182-11ea-9d16-8c845c85019f.png">
