### ISSUE TITLE
Use multiple providers with wrapRootElement

### ISSUE THREAD

**Issue by myhendry** [gatsbyjs/gatsby#21495]
Im trying to implement Gatsby with both Auth0 and Redux

As both Auth0 and Redux needs to use wrapRootElement in gatsby-browser.js, how can I merge the two in order to use them successfully in gatsby? Thanks in advance

**gatsby-browser.js**

// used by Auth0
```
export const wrapRootElement = ({ element }) => {
  return <SessionCheck>{element}</SessionCheck>
}
```

// used by Redux
`export { default as wrapRootElement } from "./src/state/ReduxWrapper"`

**gatsby-ssr.js**

Take note Im also importing then exporting ReduxWrapper in gatsby-ssr.js

`export { default as wrapRootElement } from "./src/store/ReduxWrapper"`

**ReduxWrapper.js**

```
import React from "react"
import { Provider } from "react-redux"
import { createStore as reduxCreateStore } from "redux"
import rootReducer from "."

const createStore = () => reduxCreateStore(rootReducer)

export default ({ element }) => (
  <Provider store={createStore()}>{element}</Provider>
)
```

I tried doing the following in gatsby-browser.js but it returns a blank page

```
export const wrapRootElement = ({ element }) => {
  return (
    <SessionCheck>
      <ReduxWrapper>{element}</ReduxWrapper>
    </SessionCheck>
  )
}
```

**Comment by freiksenet** [comment]
You aren't passing element to ReduxWrapper, you are passing `children`. Changing your code as follows should fix it:

```js

export default ({ children }) => (
  <Provider store={createStore()}>{children}</Provider>
)
```

I'll be closing this issue, please feel free to open a new open if you have any further questions.
