### ISSUE TITLE
"Document" is not available during server side

### ISSUE THREAD

**Issue by benfranzoso1** [gatsbyjs/gatsby#21490]
## Description

I am working on getting responsive typography on this site. I came around typetura.js on youtube. Gave it a try. Got it working on localhost. Pushed project to Github so I could go to bed. I wanted to see it on my phone so I sent it to Netlify and when Netlify tried to build it the project it through a WebpackError. Tried to build site on localhost and same thing happened. See error below.

I am relatively new to React and came from Jekyll. So please bear with my ignorance. Gatsby is still fairly complex to me. But hey, I got something up and running!! I did read the debug guide Gatsby put out but tbh all It did was confuse me.

Link to typetura: https://github.com/typetura/typetura.js

[Sat Feb 15] ben@wsl:  /mnt/c/Users/benfr/Documents/Projects/hello-world
$gatsby build
success open and validate gatsby-configs - 0.022s
success load plugins - 0.066s
success onPreInit - 0.006s
success delete html and css files from previous builds - 0.015s
success initialize cache - 0.006s
success copy gatsby files - 0.213s
success onPreBootstrap - 0.012s
success createSchemaCustomization - 0.003s
success source and transform nodes - 0.057s
success building schema - 0.272s
success createPages - 0.002s
success createPagesStatefully - 0.041s
success onPreExtractQueries - 0.002s
success update schema - 0.035s   
success extract queries from components - 0.033s
success write out requires - 0.010s
success write out redirect data - 0.003s
success onPostBootstrap - 0.002s
⠀
info bootstrap finished - 5.039 s
⠀
success Building production JavaScript and CSS bundles - 3.824s
success run queries - 5.022s - 1/1 0.20/s
**failed Building static HTML for pages - 0.317s

 ERROR #95312 

"document" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html

  39 | 
  40 | // Initiate Typetura on page load
> 41 | document.onreadystatechange = function() {
     | ^
  42 |   if (window.document.readyState === 'interactive') {
  43 |     typeturaInit(document.querySelectorAll(typeturaContexts));
  44 |   }

  WebpackError: ReferenceError: document is not defined

  - typetura.js:41 Object../node_modules/typeturajs/js/typetura.js
    node_modules/typeturajs/js/typetura.js:41:1

  - index.js:1 Module../src/pages/index.js
    src/pages/index.js:1:1**

### Steps to reproduce

1. I installed Typetura via npm. 
2. I imported it into gatsby-config.js
3. I imported it into index.js
4. I then worked in type.css in the styles folder

everything worked as it should on localhost.

Here is the like to the Github project https://github.com/benfranzoso1/equipmentloans

### Expected result

The expected result should just work. It should build as it works on my localhost.

### Actual result

Cannot build project

### Environment

System:
    OS: Linux 4.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.6.0 - /home/linuxbrew/.linuxbrew/bin/node
    npm: 6.13.4 - /home/linuxbrew/.linuxbrew/bin/npm
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-postcss: ^2.1.20 => 2.1.20
    gatsby-plugin-typography: ^2.3.22 => 2.3.22
  npmGlobalPackages:
    gatsby-cli: 2.8.28

**Comment by jlkiri** [comment]
Apparently, on line 44 in this file - https://github.com/typetura/typetura.js/blob/master/js/typetura.js - there is a reference to `document`. `document` is not available in the Node environment, where your pages are built.

It is mentioned in this doc: https://www.gatsbyjs.org/docs/debugging-html-builds/

**Comment by benfranzoso1** [comment]
Thanks @jlkiri. I did read that doc page and was still unsure of how to fix it. I guess I'll go back to typograpghy.js for now. I don't know enough to fix it myself.

**Comment by BFMarks** [comment]
This sucks
