### ISSUE TITLE
package 'gastby-cli' not found 

### ISSUE THREAD

**Issue by pedro1958** [gatsbyjs/gatsby#21498]
I am creating a project with gatsby, when installing gatsby-cli this message is indicated: "**package 'gastby-cli' not found**".
When checking on npmjs.com I have this message in response; '**0 packages found**'.
I await your comments, to continue with this project, thank you

**Comment by LekoArts** [comment]
Thank you for opening this!

The package name is `gatsby-cli` so you have a typo there. You can follow this docs page for instructions: https://www.gatsbyjs.org/docs/quick-start/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
