### ISSUE TITLE
set path for posts written as react components

### ISSUE THREAD

**Issue by ahfarmer** [gatsbyjs/gatsby#2149]
I'd like to write posts with React components.

Currently, this works. You just add your components somewhere in `/pages.`

But how do you set the path for that post?

For instance, I would like to store my post component file at this path:

`src/pages/posts/2015-10-02-static-site-generators/index.js`

And have that show up in my site at this URL:

`/static-site-generators`

I know that JS files [now support frontmatter](https://github.com/gatsbyjs/gatsby/pull/591), but setting the 'path' in the frontmatter does not seem to do anything.

Am I missing something? Thanks!

**Comment by markmichon** [comment]
The easiest way would be to name your `index.js` as `title-of-post.js`.

Alternately, you might be able to do something similar to the technique that removes trailing slashes:


```js
// gatsby-node.js
exports.onCreatePage = ({ page, boundActionCreators }) => {
  const { createPage, deletePage } = boundActionCreators

  return new Promise(resolve => {
    const oldPath = page.path
    page.path = page.path === "/" ? page.path : page.path.replace(/\/$/, "")
    if (page.path !== oldPath) {
      deletePage({ path: oldPath })
      createPage(page)
    }
    resolve()
  })
}
```

`onCreatePage` is going to run for each page, so maybe you'd be able to grab more info from page. There's a `componentPath` property on page that gives you the full local path. Might be able to parse that.

I suspect if there isn't an easier way, there probably should be. Maybe we can start exporting a path value along with the component (v2 perhaps).

**Comment by ahfarmer** [comment]
I ended up doing it like @markmichon suggested - thanks Mark!

A related issue I had was that I would have rather put my articles in `/src/articles` instead of `/src/pages/articles`. Maybe the core functionality that deals with `/src/pages` could be converted into a configurable plugin.

Anyways since my issue is resolved I'll close the issue.
