### ISSUE TITLE
StaticQuery - render not invoked

### ISSUE THREAD

**Issue by oprogramador** [gatsbyjs/gatsby#21499]
OS: Mac OS X 10.14.6
Node.js version: 10.17.0
gatsby version: 2.19.17

My code:
```js
import React from 'react';
import { StaticQuery, graphql } from 'gatsby';

export default () => <StaticQuery
  query={graphql`
    query($relativePath: String!) {
      markdownRemark(fields: { relativePath: { eq: $relativePath } }) {
        html
      }
    }
  `}
  render={data => {
    console.log({ data });
    return (<div>foo</div>);
  }}
/>
```

The `render` method is never run and I see `Loading (StaticQuery)` in the rendered page.

However, the `GET /page-data.json` request is successful and I obtain the `result.data.markdownRemark.html` field.

**Comment by LekoArts** [comment]
Thank you for opening this!

`StaticQuery` and `useStaticQuery` don't support variables (see: https://www.gatsbyjs.org/docs/static-query/#how-staticquery-differs-from-page-query). Hence your query fails and you don't see a result. You'll need to replace the variable with data or put the query into a page.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
