### ISSUE TITLE
How to combine 2 Gatsby sites?

### ISSUE THREAD

**Issue by mostafachatillon** [gatsbyjs/gatsby#21496]
I want to combine 2 Gatsby sites in one domain, for example, Gatsby1 (landing page) in mydomain.com, and Gatsby2 (blog) in mydomain.com/blog , how can I do that?

**Comment by shrey-sachdeva2000** [comment]
You can simply create another page in the `/pages` folder named `blog.js` of your Gatsby application. This page can be accessed on your local server i.e, localhost:8000/blog.

Hope this helps. Please let know if you have any further queries.

**Comment by mostafachatillon** [comment]
@shrey-sachdeva2000 thank you, but I am still confused about the details, do you have a simple example where it is done?

**Comment by LekoArts** [comment]
Thank you for opening this!

The main tutorial explains the concept of `src/pages`: https://www.gatsbyjs.org/tutorial/part-one/#building-with-components
As Shrey said you create a `blog.js` file and have your /blog route. I would recommend going that route as only having one Gatsby site simplifies the deploy/maintenance process.

If you really want to have two separate sites, you'll need to use the pathPrefix on the "blog" one: https://www.gatsbyjs.org/docs/path-prefix/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by mostafachatillon** [comment]
@LekoArts the tutorial explains how to add an html page at /blog, not a second Gatsby website, so it's still unclear to me

**Comment by LekoArts** [comment]
The linked doc on using pathPrefix explains what you have to do with your second "blog" site. Besides that it's only having two Gatsby sites. The deployment can be more complicated though - that's why I recommend using a single site.
