### ISSUE TITLE
Gatsby WebPack Externals

### ISSUE THREAD

**Issue by helmutgranda** [gatsbyjs/gatsby#21500]
## Summary

I am using a method to include jQuery on an older project that is being converted to React. This will be a several month process so that is why I just include jQuery for development. Following the link below that is how my project is set up and works as expected:

https://webpack-gatsby.netlify.com/configuration/externals/

    setWebpackConfig({
      externals: {
        jquery: 'jQuery', // important: 'Q' capitalized
      }
    })

## Relevant information

The problem is building the same project in two different environments. In my computer it works as expected, however I am using AzWebOps and the project is failing as follows:

```yaml
1 | function _interopRequireDefault(obj) {
  2 |   return obj && obj.__esModule ? obj : {
> 3 |     "default": obj
    | ^
  4 |   };
  5 | }
  6 | 

  WebpackError: Cannot find module 'jQuery'
````
 By accident I prevented externals from doing its job, I say by accident because I meant to compare `stage` to `build-javascript` but I instead compared to `build-build-javascript` which will never be true, with that the build works on AzDevOps but of course it will be included as part of the deliverable which I do not want or need. I can live with that since the project is internal but I am trying to figure out what the issue is since I will be sharing this project with other team members and their computer setup may be the same as AzDevOps and I will not have a way to debug the issue.

```js
  if (stage === "build-build-javascript") {
    setWebpackConfig({
      externals: {
        jquery: 'jQuery', // important: 'Q' capitalized
      }
    })
  }
```

I also went ahead and took another look at the documentation and I could not find the same setup as the link that I provided before which makes me believe that I may be setting up my `externals` the wrong way:

https://www.gatsbyjs.org/docs/using-client-side-only-packages/

#### My computer Setup

System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.13.50 => 2.19.17 
    gatsby-image: ^2.2.8 => 2.2.41 
    gatsby-link: ^2.2.28 => 2.2.29 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.41 
    gatsby-plugin-mdx: ^1.0.0 => 1.0.72 
    gatsby-plugin-offline: ^2.2.4 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.22 
    gatsby-plugin-sharp: ^2.2.9 => 2.4.5 
    gatsby-source-filesystem: ^2.1.8 => 2.1.48 
    gatsby-transformer-sharp: ^2.2.5 => 2.3.14 
  npmGlobalPackages:
    gatsby-cli: 2.7.58

### AzDevOps

 System:
    OS: Linux 3.10 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: (24) x64 Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 10.19.0 - /opt/hostedtoolcache/node/10.19.0/x64/bin/node
    Yarn: 1.13.0 - /usr/bin/yarn
    npm: 6.13.4 - /opt/hostedtoolcache/node/10.19.0/x64/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
  npmPackages:
    gatsby: ^2.13.50 => 2.19.17 
    gatsby-image: ^2.2.8 => 2.2.41 
    gatsby-link: ^2.2.28 => 2.2.29 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.41 
    gatsby-plugin-mdx: ^1.0.0 => 1.0.72 
    gatsby-plugin-offline: ^2.2.4 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.22 
    gatsby-plugin-sharp: ^2.2.9 => 2.4.5 
    gatsby-source-filesystem: ^2.1.8 => 2.1.48 
    gatsby-transformer-sharp: ^2.2.5 => 2.3.14 

### File contents (if changed)

Not a lot has changed other than using the externals below and using the template below:
https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wardpeet** [comment]
```
setWebpackConfig({
  externals: {
    jquery: 'jQuery', // important: 'Q' capitalized
  }
})
```

this is correct, just make sure you guard inside your components that window is undefined. The only reason I can think of you should only do this in `build-javascript` is because jquery isn't available on ssr.

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜
