### ISSUE TITLE
Static Image is not loaded correctly based on params

### ISSUE THREAD

**Issue by huylocit14054** [gatsbyjs/gatsby#21519]
## Description
I'm having a page that requires params to render the correct data. In this page, I used static image to render the user avatar. Everything works fine, the all the data rendered correctly. However, if I reload the page the url will add a trailing slash `/` before the url and the image will render the first image of the array instead of the correct one.

Correct data:
Url : `/leadership?leader=3`
<img width="1381" alt="Screen Shot 2020-02-17 at 16 52 27" src="https://user-images.githubusercontent.com/28186870/74642636-edd78680-51a5-11ea-8d22-727c67cf72ba.png">

Incorrect data after reload the page:
Incorrect url : `/leadership/?leader=3`
<img width="1492" alt="Screen Shot 2020-02-17 at 16 53 44" src="https://user-images.githubusercontent.com/28186870/74642730-1d868e80-51a6-11ea-8d61-8663c614a482.png">

As I investigate when I reload the page my url was redirected to the incorrect url with the trailing slash. Is there any way to prevent this ?

### Environment
```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.2 - ~/.nvm/versions/node/v10.15.2/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.2 - ~/.nvm/versions/node/v10.15.2/bin/npm
  Languages:
    Python: 2.7.8 - /Users/imac27/.pyenv/shims/python
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.1
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.17.11 => 2.18.17
    gatsby-background-image: ^0.9.6 => 0.9.12
    gatsby-image: 2.2.31 => 2.2.31
    gatsby-plugin-manifest: ^2.2.27 => 2.2.34
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3
    gatsby-plugin-offline: ^3.0.19 => 3.0.30
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.18
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-sass: ^2.1.22 => 2.1.26
    gatsby-plugin-sharp: ^2.2.37 => 2.3.10
    gatsby-plugin-styled-components: ^3.1.14 => 3.1.16
    gatsby-plugin-typescript: ^2.1.17 => 2.1.23
    gatsby-source-filesystem: ^2.1.36 => 2.1.43
    gatsby-transformer-sharp: ^2.3.3 => 2.3.9
  npmGlobalPackages:
    gatsby-cli: 2.8.21
```

**Comment by wardpeet** [comment]
Hey,

we have `https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/` to remove trailing slashes from gatsby but you'll still need to configure your hosting to make this work on the server.

It's a bid odd that / or no / breaks the site. Why are you using query parameters if I may ask?

**Comment by huylocit14054** [comment]
Hi @wardpeet,
I am using parameters as a way to render correct data in my page. I want the user to share the url of leaders to others. 
I expect that when user access the url `/leaders?id=1`, the page will render the info and avatar of leader 1. If user access url `/leaders` the page will render the default leader.
My problem is that when I access to the url `/leaders?id=1` the leader info was correct. However, the leader avatar was wrong, instead of rendering the avatar with id 1, the page rendered the default avatar (I'm using img inside static folder).

As I dig in further, I think this is not a problem with the `/` in the url. All the redirect I use `<Link>` component will correctly render the avatar. However when I reload the page or redirect using url, the avatar will be the default avatar instead of the correct one (Other info load correctly). I think some how gatsby cannot load static image correctly based on params. 

Please not that I changed the approach way to use `@reach/router` `leader/:id` instead of params and the image still to loaded correctly.

I fixed this problem by using gatsby-image instead. The first reason I did not use gatsby-image is that it is not compatible with Swiperjs loop. But I managed to override the gatsby-image styling so every works fine now.
