### ISSUE TITLE
WorkerError: failed to process image

### ISSUE THREAD

**Issue by pol4b** [gatsbyjs/gatsby#21515]
I was using gatsby to well until yesterday. Today I moved whole gatsby site folder to my laptop. On my laptop there's all dependencies installed and all files posts, images, files etc. were moved successfully. But, if I try to build my site gatsby throws error on processing images. Permissions are right what do I have to check else?
```
gatsby --version
Gatsby CLI version: 2.8.29
Gatsby version: 2.19.12
  Note: this is the Gatsby version for the site at: /home/pol4bear/Blog/Blog
```
```
# gatsby clean && gatsby build
success open and validate gatsby-configs - 0.111s
success load plugins - 0.564s
success onPreInit - 0.006s
success initialize cache - 0.018s
success copy gatsby files - 0.029s
success onPreBootstrap - 0.013s
success createSchemaCustomization - 0.084s
success source and transform nodes - 2.696s
success building schema - 0.530s
success createPages - 0.139s
success createPagesStatefully - 0.049s
success onPreExtractQueries - 0.002s
success update schema - 0.042s
success extract queries from components - 0.350s
success write out requires - 0.077s
success write out redirect data - 0.011s
success Build manifest and related icons - 0.164s
success onPostBootstrap - 0.189s
⠀
info bootstrap finished - 6.855 s
⠀

 ERROR 

Processing /home/pol4bear/Blog/Blog/static/media/2016/07/CIA.png failed

Original error:




  WorkerError: Processing /home/pol4bear/Blog/Blog/static/media/2016/07/CIA.png failed
  Original error:
  
  - jobs-manager.js:314 exports.enqueueJob
    [Blog]/[gatsby]/dist/utils/jobs-manager.js:314:23
  
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
  

not finished run queries - 0.389s
not finished Generating image thumbnails - 0.315s
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by nkcr** [comment]
I'm glad you reported this, the same happens to me. Works fine on OS X but fails on my Ubuntu server.

**Comment by gayatri89** [comment]
> ```
> npm install
> ```

hey thank you so much , it's working for me

**Comment by ElijahLynn** [comment]
> Solved by re-installing the modules
> 
> ```
> rm -rf node_modules
> rm package-lock.json
> npm cache clear --force
> npm install
> ```

You just saved me after an hour of debugging! THANK YOU! :heart: :rocket:

**Comment by hari5004** [comment]
Facing the same issue when buidling on GitLab CI

**Comment by perstromswe** [comment]
I have the same problem. Works on OS X but not on production Ubuntu 16.

**Comment by stevemarksd** [comment]
I have same problem, deleted cache and everything a few times...


```
$ gatsby info

  System:
    OS: Windows 10 10.0.x
    CPU: (12) x64 Intel(R) Core(TM) i7-xx00K CPU @ 3.70GHz
  Binaries:
    Node: 14.7.0 - ~\AppData\Local\Temp\yarn--x\node.CMD
    Yarn: 1.22.4 - ~\AppData\Local\Temp\yarn--x\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.5 - C:\Python38\python.EXE
  Browsers:
    Chrome: 84.0.x
  npmPackages:
    gatsby: 2.24.47 => 2.24.47
    gatsby-image: ^2.4.0 => 2.4.16
    gatsby-plugin-catch-links: ^2.0.9 => 2.3.11
    gatsby-plugin-emotion: ^3.0.1 => 3.0.1
    gatsby-plugin-layout: ^1.3.0 => 1.3.10
    gatsby-plugin-manifest: ^2.0.12 => 2.4.27
    gatsby-plugin-react-helmet: ^3.0.0 => 3.3.10
    gatsby-plugin-s3: ^0.3.4 => 0.3.5
    gatsby-plugin-sharp: ^2.0.15 => 2.6.31
    gatsby-plugin-sitemap: ^2.0.3 => 2.4.12
    gatsby-plugin-typescript: ^2.0.3 => 2.4.18
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.9 => 1.1.12
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-images: ^3.0.1 => 3.3.28
    gatsby-source-filesystem: ^2.3.23 => 2.3.27
    gatsby-transformer-remark: ^2.1.15 => 2.8.32
    gatsby-transformer-sharp: ^2.1.9 => 2.5.14
```

**Comment by davet42** [comment]
I have been working ona  similar problem and found both this issue and the aforementioned #26273 
See notes there for what I believe is a fix - the imagemin-pngquant package.
I have a pull request in and am doing more testing.  See the notes on https://github.com/gatsbyjs/gatsby/issues/26723 for the fix.
In my environment, I thought first it was transparent png, then calls with quality = 100.  Eventually found that status code 99 was not being checked properly in the imagemin-pngquant.

**Comment by AndyBrownlie** [comment]
yep, getting this same issue. Removed a png and now building as expected

**Comment by andreibardas** [comment]
> I'm glad you reported this, the same happens to me. Works fine on OS X but fails on my Ubuntu server.
> 
> **Edit**:
> Solved by re-installing the modules
> 
> ```
> rm -rf node_modules
> rm package-lock.json
> npm cache clear --force
> npm install
> ```

not working for me (tried cleaning everything) :(

**Comment by mjmaurer** [comment]
Yup, also tried cleaning. Worked a month ago. Must be something new?

**Comment by nikhilag** [comment]
Why is this issue closed? I am still seeing the same issue on Windows 10.

**Comment by nikhilag** [comment]
This solution worked for me from the thread - https://github.com/gatsbyjs/gatsby/issues/26723

> My current solution is to downgrade gatsby-plugin-sharp to version 2.6.26.

**Comment by andreibardas** [comment]
so guys, I solved my issue by changing all image quality from 100 to 99. took me 1 hour (be carefull with "replace all"). I hope this will help someone!

**Comment by karlhorky** [comment]
### Workaround with latest versions of plugins

1. Install [`patch-package`](https://www.npmjs.com/package/patch-package) (`npm install patch-package` or `yarn add patch-package postinstall-postinstall`)
2. Add `"postinstall": "patch-package"` to `scripts` in `package.json`
3. Go into `node_modules/imagemin-pngquant/index.js` and change `error.code` to `error.exitCode` on line 66 (see diff below)
4. Run `npx patch-package imagemin-pngquant`
5. Commit the changes, including the patch

This will save the change that you make to the `index.js` file and apply it any time / anywhere that `npm install` or `yarn` is run in the project.

#### Diff (difference before and after)

```diff
	const promise = subprocess
		.then(result => result.stdout) // eslint-disable-line promise/prefer-await-to-then
		.catch(error => {
-			if (error.code === 99) {
+			if (error.exitCode === 99) {
				return input;
			}
```
