### ISSUE TITLE
How to access content folder through a proxy redirect 200?

### ISSUE THREAD

**Issue by mostafachatillon** [gatsbyjs/gatsby#21525]
Hi, I have 2 Gatsby websites on Netlify (one for landing page, one for blog) under 1 domain. I serve the blog through the main website (mywebsite.com/blog), and I serve the landing page through a  proxy 200 redirect (mywebsite.com). 

But the proxied website cannot access the `content` folder: in my landing page, the background image does not show. (and if instead, I proxy the blog and put the landing page on the main website, then blog posts do not show, so it is even worse)

Theme for blog: https://github.com/narative/gatsby-theme-novela
Theme for landing page: https://github.com/ekafyi/gatsby-theme-musician

But it's not a theme issue, it's a gatsby issue.

**Comment by LekoArts** [comment]
Thank you for opening this!

This doesn't appear to be a problem with Gatsby but how you set up your proxy and hosting. Gatsby doesn't change anything about that. Please reach out to Netlify's support about your question. Thanks!
