### ISSUE TITLE
Gatsby-Image - Full size versions only load on develop, not build

### ISSUE THREAD

**Issue by bdk6000** [gatsbyjs/gatsby#21526]
I have a landing page with several instances of gatsby-image. In development, the base64 images load and then the full size image blurs in, and it works perfectly.

In production, only the base64 image loads. The full size image never blurs in or takes its place. If I disable base64, nothing loads at all, just a blank area.

Here is my Graphql query:

              introimage
              introimageSharp {
                childImageSharp {
                  fixed(width: 2000, quality: 80) {
                    ...GatsbyImageSharpFixed
                  }
                }
             }

### Steps to reproduce

Running gatsby develop loads website properly and works as expected. Running gatsby build and serve loads a version with images not working. I've tried gatsby clean as well. The production issue is the same on my local machine as well as when I publish to Netlify.

### Expected result

Full size images should blur in after loading base64 version.

### Actual result

Images are stuck on base64 or don't load full size at all.

### Environment

 System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.106
    Firefox: 61.0
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-background-image: ^0.10.0 => 0.10.0
    gatsby-image: ^2.2.40 => 2.2.40
    gatsby-plugin-google-tagmanager: ^2.1.25 => 2.1.25
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39
    gatsby-plugin-netlify: ^2.1.32 => 2.1.32
    gatsby-plugin-offline: ^3.0.32 => 3.0.32
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-source-prismic-graphql: ^3.3.1 => 3.3.1
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13
  npmGlobalPackages:
    gatsby-cli: 2.8.29

**Comment by bdk6000** [comment]
It looks like in production, the code for the full size images is there inside a noscript tag, but the code isn't being applied for some reason.

**Comment by austinbutler** [comment]
This was closed without resolution, but I had a similar issue when deploying to GitLab Pages and it was because I was missing `pathPrefix`: https://www.gatsbyjs.org/docs/deploying-to-gitlab-pages/#add-path-prefix-to-gatsby.
