### ISSUE TITLE
Where to place the _redirects file?

### ISSUE THREAD

**Issue by mostafachatillon** [gatsbyjs/gatsby#21520]
Hi, I am trying to use a proxy redirect, but I don't know where to place the _redirects file. If I place it in the root directory of my github repo, it does not work.

**Comment by pieh** [comment]
You can put `_redirects` inside `static` directory:

`<project_directory>/static/_redirects` - files from `static` directory will be copied "as-is" into `public` and Netlify will pick this up on deploys

**Comment by pieh** [comment]
Alternatively you could use `gatsby-plugin-netlify` and make use of `createRedirect` actions ( https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/#redirects )

**Comment by LekoArts** [comment]
Closing this issue as answered then 👍
