### ISSUE TITLE
add `--profile` command flag to `develop` and `build` commands

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#21535]
## Summary

React (or more specifically `react-dom` and `scheduler/tracing`) have special builds that allow to use React Dev Tools profiling. Because profiling support adds additional overhead in the browser - users need to opt into using that.

Create React App allows using that by passing `--profile` flag:
https://create-react-app.dev/docs/production-build/#profiling

You can read a bit more about react profiling in this blog post - https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html (React Dev Tools changed a bit so screenshots are outdated, but general idea remains the same)

### How to

Modify `gatsby-cli` to accept `--profile` switch for `build` and `develop` commands. Modify webpack config to use profiling versions of `react-dom` and `scheduler/tracing` ( https://gist.github.com/bvaughn/25e6233aeb1b4f0cdb8d8366e54a3977#react-dom1660--scheduler0100 ). In gatsby that would mean adding it somewhere in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L367-L412 if the flag was used  (probably good idea to target just `web` webpack builds).

It might also be good idea to implicetely turn off terser in `build` command when using `--profile` flag to keep React component names readable

### Motivation

In complex applications / sites it gets difficult to pinpoint performance bottlenecks. We can use builtin "performance" tab in dev tools and record a profile, but it will lack granularity as to what component(s) are causing most performance hits. See for example https://github.com/gatsbyjs/gatsby/issues/21533 where browser profiling just pretty much confirm the issue. Even when you zoom in on browser profiler results you still see details of react internals more than your components:
![Screenshot 2020-02-17 at 21 20 00](https://user-images.githubusercontent.com/419821/74684125-5be27480-51cb-11ea-965f-316cc7cd5274.png)

**Comment by herecydev** [comment]
I'll take a stab at this 🤞

**Comment by pieh** [comment]
Published in `gatsby-cli@2.10.0` / `gatsby@2.19.26`

**Comment by ethaneisenhard** [comment]
This looks awesome! If I am reading it correctly, we should be able to run `gatsby develop --profile` in order to use the React Dev Tools?

**Comment by herecydev** [comment]
> This looks awesome! If I am reading it correctly, we should be able to run `gatsby develop --profile` in order to use the React Dev Tools?

It works in dev without the flag, but I would caution using it reliably as dev is very unoptimized.
