### ISSUE TITLE
.org sidebar performance 

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#21533]
## Description

Clicking on links on gatsbyjs.org/docs is pretty unresponsive, which is confirmed by following profile from Performance tab in dev tools:

<img width="1080" alt="browser-profile" src="https://user-images.githubusercontent.com/419821/74680865-356c0b80-51c2-11ea-92fb-6da34b366e63.png">

I created build with react profiling enabled to get more insights and those are results - clicking on sidebar item cause 3 re-renders - only one of which actually re-renders page content, but all of the re-render sidebar:

1. Just sidebar updates (all items are getting re-rendered)
![Screenshot 2020-02-17 at 20 00 55](https://user-images.githubusercontent.com/419821/74681746-782ee300-51c4-11ea-82d2-2b3bdf85e343.png)
2. Sidebar re-render + content change
![Screenshot 2020-02-17 at 20 01 06](https://user-images.githubusercontent.com/419821/74681756-7b29d380-51c4-11ea-92f8-593cd2c2e219.png)
3. Another just sidebar re-render
![Screenshot 2020-02-17 at 20 01 15](https://user-images.githubusercontent.com/419821/74681766-7fee8780-51c4-11ea-848a-b9c7f5ea22cb.png)

 ### Steps to reproduce

1. Open https://www.gatsbyjs.org/docs/
2. Click on link from sidebar (ideally one that uses same page template to reduce variables - so for example "Recipes -> Pages and Layouts") 

### Expected result

Navigation should be snappy

### Actual result

Navigation feels unresponsive

**Comment by tesseralis** [comment]
@pieh this seems to be fixed as of #23159, so I think this can be closed (unless you want to do some more detailed profiling).
