### ISSUE TITLE
Will gatsby move back to react router with new v6?

### ISSUE THREAD

**Issue by kaushalyap** [gatsbyjs/gatsby#21544]
Will gatsby move to [react router v6 which is much lighter](https://www.reddit.com/r/reactjs/comments/f543xl/react_router_v6_will_be_29kb_70_smaller_because/) than reach router? Since [Reach router will only receive bug fixes and react router will be the surviving project](https://reacttraining.com/blog/reach-react-router-future/).

[react-router-dom@6.0.0-alpha.1  :     2.9   KB](https://bundlephobia.com/result?p=react-router-dom@6.0.0-alpha.1)
[@reach/router@1.3.1                   :     6.4   KB](https://bundlephobia.com/result?p=@reach/router@1.3.1)
Potential savings                                         :     3.5   KB

**Comment by LekoArts** [comment]
Thank you for opening this!

We're not sure about it yet but definitely consider it. We'll wait until the merge is done and see how the reach project is doing. We track it in this issue: https://github.com/gatsbyjs/gatsby/issues/15277

So can't give you a definitive answer for now.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by dvakatsiienko** [comment]
Actually, why this issue is closed and didn't get any attention?

React Router 6 will merge Reacth Router into it, so Reach Router is't the good solution as main router for Gatsby.

**Comment by medoms** [comment]
Hello, any news on this issue?? 

I am very interested in moving from Create React App (using react router) to Gatsby using client side only stuff at the beginning. Right now I can see Gatsby using reach router... as both libraries will be merged soon, people in my situation are somehow stuck.

Could anyone shed some light about what plans there are regarding client routers?

Thanks for your time¡¡

**Comment by eckdanny** [comment]
react-router@6 GA'd today. We *just* did a PoV migration from a CRA impl to gatsby@4, and react-router@5.x => @reach | static pages was a pain point. If those `invariant` build errs went away, we and many others could have a very pleasant migration path

**Comment by SirLemuel** [comment]
Bumping this, any plans to merge V6?

**Comment by LekoArts** [comment]
It seems like V6 made a step backwards in accessibility and thus it's not something we should take lightly: https://twitter.com/mmatuzo/status/1456722149260070916

**Comment by olliejm** [comment]
Are there any updates on this? Seeing as `@reach/router` is presumably dead now, is it not an eventuality that Gatsby will have to move to a different router?

**Comment by dan2k3k4** [comment]
Looks like a fork for `@reach/router` was made:
https://github.com/gatsbyjs/reach-router
