### ISSUE TITLE
Gatsby develop/serve difference

### ISSUE THREAD

**Issue by otech-nl** [gatsbyjs/gatsby#21546]
## Description

I set up a blog with Gatsby and gatsby-transformer-orga. Details are [here](https://dwim.nl/setting-up-this-blog), source is [here](https://github.com/randomrambler/dwim).

The [index page](https://dwim.nl/) shows 'teasers' of the latest posts. Each teaser shows the title and first pragraph of that post. With `gatsby develop` this works fine, but with `gatsby serve` (and in production after `gatsby build`) the first teaser shows the entire first page again (instead of the title and first paragraph of the latest post). 

When I navigate to another page and than the starting page again, the problem vanishes and the first teaser is as it should be. I have inspected the location prop, and in both cases it is "/".

### Steps to reproduce

I have no idea what the problem is. It's probably me, maybe it's my GraphQL query, maybe it's the Orga transformer, maybe it's Gatsby. So, unfortunately, I don't know how to give steps to reproduce, other than my site. What stumps me is that the problem only happens with `gatsby serve`, and disappears when I navigate. 

The index page is built [here](https://github.com/randomrambler/dwim/blob/develop/src/pages/index.js). It uses a [Layout](https://github.com/randomrambler/dwim/blob/develop/src/components/layout.js) and [Teaser](https://github.com/randomrambler/dwim/blob/develop/src/components/Teaser.jsx) component.

### Expected result

Each teaser on the index page should show the title and first paragraph of a post.

### Actual result

The first teaser shows the entire index again.

### Environment

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 3.7.5 - /usr/bin/python
  Browsers:
    Firefox: 73.0
  npmPackages:
    gatsby: ^2.18.21 => 2.18.25 
    gatsby-plugin-feed: ^2.3.26 => 2.3.26 
    gatsby-plugin-mdx: ^1.0.67 => 1.0.67 
    gatsby-plugin-sharp: ^2.3.13 => 2.3.13 
    gatsby-remark-images: ^3.1.42 => 3.1.42 
    gatsby-source-filesystem: ^2.1.46 => 2.1.46 
    gatsby-transformer-orga: ^1.8.4 => 1.8.4

**Comment by wardpeet** [comment]
The problem you're having is `const excerpt = cut > 0 ? html.substring(0, cut - 1) : html;`. It doesn't take in account html tags so you might end up with broken html for example

<details>
<summary>full html</summary>
```
<div class="section"><p>I distinguish between work and problems.</p><p>Work can be done by following well-known, accepted rules. It may not be easy, but you know from the start how hard it is and how much effort it takes. Work just takes time, energy and commitment. So, just do it already!</p><p>There are no predefined rules for problems. You have to figure them out as you go along. It's not even clear how to know which solution is best, because problems usually have multiple perspectives with (possibly conflicting) interests. Problems may even have multiple stakeholders. So you have to analyze the problem to come up with possible solutions, evaluate the solutions by all different criteria, and than choose on basis of incomplete information. And that's all <i>before</i> you can start actually solving the problem itself.</p><p>The obvious trap here is that you can get stuck in the analysis/evaluation, because choosing is hard and often involves conflict. So my approach often is to just choose one option, fix the problem and deal with the consequences. Which may require me to get back to the drawing board to come up with a whole new solution. I am happy to solve a problem more than once, because it means you always have a solution in place (as imperfect as it may be), and it will gradually get better.</p></div>
```
</details>

<details>
<summary>excerpt</summary>
```
<div class="section"><p>I distinguish between work and problems.</p><p>Work can be done by following well-known, accepted rules. It may not be easy, but you know from the start how hard it is and how much effort it takes. Work just takes time, energy and commitment. So, just do it already!</p><p>There are no predefined rules for problems. You have to figure them out as you go along. It's not even clear how to know which solution is best, because problems usually have multiple perspectives with (possibly conflicting) interests. Problems may even have multiple stakeholders. So you have to analyze the problem to come up with possible solutions, evaluate the solutions by all different criteria, and than choose on basis of incomplete information. And that's all <i>before</i> you can start actually solving the problem itself.
```
</details>

In develop we only do a single render on the client, on build we do a Server side render and a  client render. If the client render does not match server render, you might get in a broken state like yours.

I would suggest stripping all html out of your excerpt before cutting it in react.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by otech-nl** [comment]
Thank you. That solved it.

However, I think that's not the whole story. The real cause may be that `gatsby build` gives:

```  
GraphQL request:9:23
   8 |                     node {
   9 |                       html
     |                       ^
  10 |                       fields { slug }, Cannot read property 'split' of undefined
```
Possibly related to [this](https://github.com/orgapp/gatsby-orga/issues/9) issue of orgajs.
