### ISSUE TITLE
refactor(www): standardize common page metadata in <Helmet>

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21562]
## Description

Create a `<PageMetadata>` wrapper component around `<Helmet>` with common metadata attributes:

```jsx
<PageMetadata
  title={/* Used for <title> and "og.title" */}
  description={/* Used for "description", "og:description" and "twitter:description" */}
  type={/* Used for "og:type" */}
  image={/* Used for "og:image" and "twitter:image" */}
  readingTime={/* Used for Twitter reading time label */}
  author={/* Used for <link rel="author/>, "article:author", "twitter:creator" */}
/>
```

## Motivation

For each page and template in gatsbyjs.org, we want to add page metadata for SEO and sharing on social media. Right now, we do this manually, meaning that the same content needs to be populated for multiple metadata fields:

```jsx
      <Helmet>
        <title>{page.frontmatter.title}</title>
        <meta name="description" content={description} />
        <meta property="og:description" content={description} />
        <meta property="og:title" content={page.frontmatter.title} />
        <meta property="og:type" content="article" />
        <meta name="twitter:description" content={description} />
        <meta name="twitter.label1" content="Reading time" />
        <meta name="twitter:data1" content={`${page.timeToRead} min read`} />
      </Helmet>
```

Here, there are several repeated fields: `page.frontmatter.title` needs to be passed into `<title>` and `og:title`, `description` needs to be passed into three fields, and so on. This is error prone: copy pasting across fields can lead to errors and inconsistencies, and adding a new metadata field means updating across all the different pages. For example, there are many pages where only `<title>` and `<meta propety="description">` are defined, and the `og:` versions unpopulated.

By having a wrapper component, we can simplify the above to the following:

```jsx
<PageMetadata
  title={page.frontmatter.title}
  description={description}
  type="article"
  timeToRead={page.timeToRead}
/>
```

**Comment by marcysutton** [comment]
Should this issue and PR be tagged with `topic: i18n`?
