### ISSUE TITLE
refactor(www): Standardize page layout to enforce consistency in dot-org

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21569]
## Description

Create a standardized `<PageContent>` component to be used in all pages of gatsbyjs.org.

## Motivation

We've recently surfaced some consistency issues among various pages of dot-org:

* #21562 Inconsistent metadata in `<Helmet>`
* #21492 Missing `<FooterLinks>`
* #21565 Missing skip nav element in some pages

We can solve all these issues individually, but they speak to the fact that there are certain constants that we want in each Gatsby page that should always be there:

* site metadata, like a title and description
* footer links after the main content
* a `<main>` tag and an element with `id="reach-skip-nav"` for skip navigation.

## Proposed Solution

We can wrap each page in a `<PageContent/>` component that works as follows:

```jsx
<PageContent
  title="My Gatsby Page"
  description="This is a page of gatsbyjs.org"
>
  { /* Content goes here */}
</PageContent>
```

It can be implemented like so:

```jsx
function PageContent({ title, description, children }) {
  return (
    <>
      <Helmet>
        <title>{title}</title>
        <meta name="description" content={description} />
      </Helmet>
      <main id="reach-skip-nav">
        {children}
      </main>
      <FooterLinks />
    </>
  )
}

```

**Comment by madalynrose** [comment]
I'm definitely on board for standardization! We do need to be careful in our implementation to make sure we're only using it to wrap the actual main content and not wrap the entire page including nav etc in order to preserve skip link usefulness.

**Comment by tesseralis** [comment]
We shouldn't be wrapping the nav/skip link -- that's in the <Layout> component which we're factoring out to not be part of the page: https://github.com/gatsbyjs/gatsby/pull/21478

**Comment by madalynrose** [comment]
I meant more like what if there is still stuff that we want to skip over inside of `{children}` and just being mindful to only wrap the most important content using this component.

**Comment by tesseralis** [comment]
Ah, got it. Yeah, we should be able to keep say, the sidebar out of it:

```jsx
<>
  <PageContent>
    <PackageReadme />
  </PageContent>
  <PluginSidebar />
</>
```
