### ISSUE TITLE
bug(www): Fix "og:url" in <SiteMetadata>

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21563]
## Description

The "og:url" description in SiteMetadata is [defined as `siteUrl`](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/site-metadata.js#L34). However, according to the [Open Graph protocol](https://ogp.me/)

> og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".

It should be the same as `<link rel="canonical"/>`, defining the canonical URL for the page.

`og:url` is also set in `template-blog-post`, though I'm not sure how it interacts because the canonical link is sometimes set to a page outside of Gatsbyjs.org.

**Comment by DallasGale** [comment]
@tesseralis I can look into this if you like?

**Comment by tesseralis** [comment]
@DallasGale go ahead!
