### ISSUE TITLE
Excerpt doesn't appear on Gatsby page

### ISSUE THREAD

**Issue by kinnikumegane** [gatsbyjs/gatsby#21560]
Hi all,

so, let me briefly explain my issue.
My issue is that Excerpt doesn't appear on top page of Gatsby blog, source is Contentful even though I have content in the post in Contentful.

Very strange thing is that it depends on content of each post wether post shows excerpt on top page of blog or not as you can see the image below.

![Screen Shot 2020-02-18 at 7 22 01 PM](https://user-images.githubusercontent.com/56922464/74765540-15048580-5284-11ea-96b7-a54a673e19ee.png)

This is the link of page
https://vigilant-dubinsky-0307bb.netlify.com/
 
### this is post in contentful that shows excerpt properly on top page of blog

![screencapture-app-contentful-spaces-hislj6a1ae2m-entries-LaITi24sICaQu82i6mKuG-2020-02-18-19_30_19](https://user-images.githubusercontent.com/56922464/74766174-2601c680-5285-11ea-81e1-4d0dc15f49dd.png)

### this is post in contentful that doesn't show excerpt properly on top page of blog

![screencapture-app-contentful-spaces-hislj6a1ae2m-entries-4dFnYYGOC4yK28WEUY042m-2020-02-18-19_32_24](https://user-images.githubusercontent.com/56922464/74766321-6c572580-5285-11ea-981b-63a5d4623943.png)

## what I have found out
In Contentful, I changed following items one by one to find out which item impacts on the condition show/or not show excerpt, and figured out that excerpt appear on top of blog page based on the "Body(required)" field in post in Contentful.

In some of case of "Body(required)", excerpt appears on top page of blog, but some case of "Body(required)" doesn't show excerpt on top page of blog.

I could image that there are some conditional check in gatsby to judge whether excerpts should appear or not, or it might come from setting in Contentful.

Would anybody have idea how I can fix it so that I can see excerpts of all post in top page of blog ?

I use this template;
https://github.com/ryanwiemer/gatsby-starter-gcn

### File contents

**gatsby-config.js**
```
let contentfulConfig
try {
  contentfulConfig = require('./.contentful')
} catch (e) {
  contentfulConfig = {
    production: {
      spaceId: process.env.SPACE_ID,
      accessToken: process.env.ACCESS_TOKEN,
    },
  }
} finally {
  const { spaceId, accessToken } = contentfulConfig.production
  if (!spaceId || !accessToken) {
    throw new Error('Contentful space ID and access token need to be provided.')
  }
}

module.exports = {
  siteMetadata: {
    title: 'Yang-Musikzimmer',
    description:
      'My name is Yangja Yang, I write my life in Germany and Japan as Violinist.',
    siteUrl: 'https://yang-musikzimmer.com',
    image: '.static/images/yangprofile.jpg',
    menuLinks: [
      {
        name: 'Home',
        slug: '/',
      },
      {
        name: 'About',
        slug: '/about/',
      },
      {
        name: 'Contact',
        slug: '/contact/',
      },
    ],
    postsPerFirstPage: 7,
    postsPerPage: 6,
    basePath: '/',
  },
  plugins: [
    `gatsby-plugin-emotion`,
    'gatsby-plugin-theme-ui',
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-prismjs`,
          },
          `gatsby-remark-autolink-headers`,
          {
            resolve: `gatsby-remark-images-contentful`,
            options: {
              maxWidth: 650,
              backgroundColor: 'white',
              linkImagesToOriginal: false,
            },
          },
        ],
      },
    },
    `gatsby-plugin-catch-links`,
    {
      resolve: 'gatsby-source-contentful',
      options:
        process.env.NODE_ENV === 'development'
          ? contentfulConfig.development
          : contentfulConfig.production,
    },
    {
      resolve: 'gatsby-plugin-google-analytics',
      options: {
        trackingId: process.env.GOOGLE_ANALYTICS,
        head: true,
      },
    },
    'gatsby-plugin-sitemap',
    {
      resolve: 'gatsby-plugin-manifest',
      options: {
        name: 'GCN',
        short_name: 'GCN',
        start_url: '/',
        background_color: '#ffffff',
        theme_color: '#ffffff',
        display: 'minimal-ui',
        icon: './static/images/favicon.jpg',
      },
    },
    'gatsby-plugin-offline',
    {
      resolve: `gatsby-plugin-schema-snapshot`,
      options: {
        path: `./src/gatsby/schema/schema.gql`,
        update: process.env.GATSBY_UPDATE_SCHEMA_SNAPSHOT,
      },
    },
    'gatsby-plugin-netlify',
  ],
}
```
**src/templates/posts.js**
```
import React from 'react'
import { graphql } from 'gatsby'
import Layout from '../components/Layout'
import CardList from '../components/CardList'
import Card from '../components/Card'
import Container from '../components/Container'
import Pagination from '../components/Pagination'
import SEO from '../components/SEO'
import { startCase } from 'lodash'

const Posts = ({ data, pageContext }) => {
  const posts = data.allContentfulPost.edges
  const { humanPageNumber, basePath } = pageContext
  const isFirstPage = humanPageNumber === 1
  let featuredPost
  let ogImage

  try {
    featuredPost = posts[0].node
  } catch (error) {
    featuredPost = null
  }
  try {
    ogImage = posts[0].node.heroImage.ogimg.src
  } catch (error) {
    ogImage = null
  }

  return (
    <Layout>
      <SEO title={startCase(basePath)} image={ogImage} />
      <Container>
        {isFirstPage ? (
          <CardList>
            <Card {...featuredPost} featured basePath={basePath} />
            {posts.slice(1).map(({ node: post }) => (
              <Card key={post.id} {...post} basePath={basePath} />
            ))}
          </CardList>
        ) : (
          <CardList>
            {posts.map(({ node: post }) => (
              <Card key={post.id} {...post} basePath={basePath} />
            ))}
          </CardList>
        )}
      </Container>
      <Pagination context={pageContext} />
    </Layout>
  )
}

export const query = graphql`
  query($skip: Int!, $limit: Int!) {
    allContentfulPost(
      sort: { fields: [publishDate], order: DESC }
      limit: $limit
      skip: $skip
    ) {
      edges {
        node {
          title
          id
          slug
          publishDate(formatString: "MMMM DD, YYYY")
          heroImage {
            title
            fluid(maxWidth: 1800) {
              ...GatsbyContentfulFluid_withWebp_noBase64
            }
            ogimg: resize(width: 1800) {
              src
            }
          }
          body {
            childMarkdownRemark {
              timeToRead
              html
              excerpt(pruneLength: 80)
            }
          }
        }
      }
    }
  }
`

export default Posts
```

**src/components/Card.js**
```
import React from 'react'
import styled from '@emotion/styled'
import { Link } from 'gatsby'
import Img from 'gatsby-image'

const Post = styled.li`
  position: relative;
  border: 1px solid ${props => props.theme.colors.secondary};
  border-radius: 2px;
  margin: 0 0 1em 0;
  width: 100%;
  transition: background 0.2s;
  @media screen and (min-width: ${props => props.theme.responsive.small}) {
    flex: ${props => (props.featured ? '0 0 100%' : '0 0 49%')};
    margin: 0 0 2vw 0;
  }
  @media screen and (min-width: ${props => props.theme.responsive.medium}) {
    flex: ${props => (props.featured ? '0 0 100%' : '0 0 32%')};
  }
  &:hover {
    background: ${props => props.theme.colors.tertiary};
  }
  a {
    display: flex;
    flex-flow: column;
    height: 100%;
    width: 100%;
    color: ${props => props.theme.colors.text};
    text-decoration: none;
    .gatsby-image-wrapper {
      height: 0;
      padding-bottom: 60%;
      @media screen and (min-width: ${props => props.theme.responsive.small}) {
        padding-bottom: ${props => (props.featured ? '40%' : '60%')};
      }
    }
  }
`

const StyledImg = styled(Img)`
  border-top-left-radius: 1px;
  border-top-right-radius: 1px;
`

const Title = styled.h2`
  font-size: 1.5em;
  font-weight: 600;
  text-transform: capitalize;
  margin: 1rem 1rem 0.5rem 1rem;
`

const Date = styled.h3`
  margin: 0 1rem 0.5rem 1rem;
  color: gray;
`

const ReadingTime = styled.h4`
  margin: 0 1rem 1.5rem 1rem;
  color: gray;
`

const Excerpt = styled.p`
  margin: 0 1rem 1rem 1rem;
  line-height: 1.6;
`

const ConsoleLog = ({ children }) => {
  console.log(children);
  return false;
};

const Card = ({ slug, heroImage, title, publishDate, body, ...props }) => {
  return (
    <>
      {heroImage && body && (
        <Post featured={props.featured}>
          <Link to={`${props.basePath}/${slug}/`}>
            <StyledImg fluid={heroImage.fluid} backgroundColor={'#eeeeee'} />
            <Title>{title}</Title>
            <Date>{publishDate}</Date>
            <ReadingTime>
              {body.childMarkdownRemark.timeToRead} min read
            </ReadingTime>
            <Excerpt
              dangerouslySetInnerHTML={{
                __html: body.childMarkdownRemark.excerpt,
              }}
            />
            <ConsoleLog>{ body.childMarkdownRemark.excerpt }</ConsoleLog>
          </Link>
        </Post>
      )}
    </>
  )
}

export default Card
```

**Comment by KashafS** [comment]
Hi, I had the same issue with Wordpress CMS.
Here I see that you have created the Excerpt styled component as a p tag and dangerously set inner html in the tag. I had initially done the same thing and it didn't work for me.
The reason is that the excerpt coming from wordpress was already in a <p> tag.
Try changing the element to DIV instead of P tag and see if that works for you :)

So your Excerpt component would be : 
`const Excerpt = styled.div`

instead of 
`
const Excerpt = styled.p`

**Comment by vladar** [comment]
Hi @kinnikumegane !

Sorry to hear you're running into an issue. It is really hard to say what is going on without having a [minimum reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) or at least some code at hand which can help to reproduce this.

One way of creating a minimum reproduction is to start a new gatsby site based on https://github.com/gatsbyjs/gatsby-starter-blog

Then put your content into markdown files for blog posts and see if the excerpt is also broken there. If it is - that would be enough for minimum reproduction.

You may also try to narrow down the issue:

1. Do you have a full text of the post (when switching `excerpt` to `html` in output)?
2. Try running the text of the bad post against [`grey-matter`](https://github.com/jonschlinkert/gray-matter#optionsexcerpt) (that's what Gatsby uses under the hood to produce excerpts)

Thanks for using Gatsby! 💜

**Comment by kinnikumegane** [comment]
Hi @KashafS ,
thank you so much for your quick answer ! Any help is really really appreciated !
I did following, but it's still not working unfortunately, it seems my case is a bit different from yours...
1. deleted .cache
2. changed to  

`const Excerpt = styled.div`

instead of 
`const Excerpt = styled.p`

3. gatsby develop
4. issue is still there...

![Screen Shot 2020-02-19 at 9 13 53 PM](https://user-images.githubusercontent.com/56922464/74872031-c4149000-535c-11ea-8497-13a94838717d.png)

**Comment by kinnikumegane** [comment]
Hi @vladar 
thank you so much for your support !
I am trying to narrow down the issue by following your suggestion

1. Do you have a full text of the post (when switching excerpt to html in output)?
1. Try running the text of the bad post against grey-matter (that's what Gatsby uses under the hood to produce excerpts)

After I changed from `excerpt` to `html`, I can see the full text of post on top page of blog as you can see image below.

Changed to
`dangerouslySetInnerHTML={{
                __html: body.childMarkdownRemark.html,
              }}`
from
`dangerouslySetInnerHTML={{
                __html: body.childMarkdownRemark.excerpt,
              }}`

However, due to lack of my experience and knowledge, it's difficult for me to understand what exactly I would need to do for point 2....

Would you please write a bit more detail of point 2 what I should do ... ?

Thanks a lot for your sincere support !!!


### This is Image after I changed to `dangerouslySetInnerHTML={{
                __html: body.childMarkdownRemark.html,
              }}`
![Screen Shot 2020-02-20 at 6 38 26 AM](https://user-images.githubusercontent.com/56922464/74904219-a7ec0f80-53ab-11ea-994b-15751092fc7c.png)

**Comment by kinnikumegane** [comment]
Hi @vladar 
I also created minimum reproduction, and put content into markdown files for blog post that didn't show excerpt originally, and I can see that excerpt is there...
so, I couldn't reproduce the issue on minimum reproduction...
Would you please support ?

Repository is here;
[my-blog-starter](https://github.com/kinnikumegane/my-blog-starter)

**Image that shows excerpt**
![Screen Shot 2020-02-20 at 7 06 51 AM](https://user-images.githubusercontent.com/56922464/74905980-ee436d80-53af-11ea-9f8c-3c9ba2b2e4c2.png)

**content/blog/new-beginnings/index.md**
```
---
title: 8月10日17時から。
date: "2015-05-28T22:40:32.169Z"
description: こんにちは、梁です。数日に渡ってプログラムのご紹介をしてまいりましたが、いよいよ、明日「梁洋子&有元裕子デュオ・リサイタル」京都公演でございます！開演時間17時00分というのは珍しいのでしょうか？お間違えのないように会場までお越しください！
---

こんにちは、梁です。

数日に渡ってプログラムのご紹介をしてまいりましたが、いよいよ、明日「梁洋子&有元裕子デュオ・リサイタル」京都公演でございます！

開演時間17時00分というのは珍しいのでしょうか？
お間違えのないように会場までお越しください！

2019年8月10日(土)
17:00開演 (16:30開場)
京都・バロックザール

ピアノの裕子嬢と私、ドイツ・日本の様々な場所でリハーサルをしてきたのですが、何と言っても、変わり種は京都のとある旧小学校の音楽室。
施設長さんの歓迎も嬉しく、何よりも懐かしい雰囲気が漂っていましたね。(母校ではないのですが！)

それでは、明日会場でたくさんの方にお目にかかれますようにー！！
```

**Comment by vladar** [comment]
Can you adjust your GraphQL query so that markdown-related part looks like this:

```
          body {
            body # this is a new added field 
            childMarkdownRemark {
              timeToRead
              html
              excerpt(pruneLength: 80)
            }
          }
```

And then publish the result somewhere on netlify. I want to inspect the `raw` markdown (and maybe run gray-matter on it locally).

It is possible that you just have hidden data at the beginning of the text which gets removed on copy-and-paste (and that's why it is not reproduced with starter blog). But that's just a guess - need to see a raw markdown on your site to check it.

**Comment by kinnikumegane** [comment]
thanks @vladar !
So, in src/templates/posts.js
I have changed GraphQL

from
```
body {
  childMarkdownRemark {
    timeToRead
    html
    excerpt(pruneLength: 80)
  }
}
```

to
```
body {
  body
  childMarkdownRemark {
    timeToRead
    html
    excerpt(pruneLength: 80)
  }
}
```

and, published to following url on Netlify;
https://app.netlify.com/sites/vigilant-dubinsky-0307bb/overview

> It is possible that you just have hidden data at the beginning of the text which gets removed on copy-and-paste (and that's why it is not reproduced with starter blog). But that's just a guess - need to see a raw markdown on your site to check it.

Understand, it might be possible, but I would definitely need your support to find out...
Thanks again @vladar  !!

**Comment by vladar** [comment]
Unfortunately, I don't have access to this URL. I guess it has to be available publicly.

**Comment by kinnikumegane** [comment]
Sorry @vladar , here is the public url, it was mistake.
https://vigilant-dubinsky-0307bb.netlify.com/

It would be highly appreciated if you would support me !

**Comment by vladar** [comment]
Finally, I was able to reproduce this (doing some tweaks to your repro). Don't have time now to debug this but there are several tricks you can try:

1. In your query change `excerpt(pruneLength: 80)` to `excerpt(format:HTML, pruneLength: 80)`
2. Alternatively, try changing it to `excerpt(pruneLength: 81)` which is insane but worked for me locally

Looks like `pruneLength` less than 80 makes this happen. We need to debug this further when we have a chance. Also, I [posted a PR](https://github.com/kinnikumegane/my-blog-starter/pull/1) to your repro which helps to see the issue.

Please merge it so that it was easier to reproduce for anyone.

For now, those tricks should (hopefully) unblock you.

**Comment by kinnikumegane** [comment]
Hi @vladar ,
Fantastic ! Solution No.1 adding `format:HTML` worked for me, and I can see excerpt in all post on blog top page !!!

Thank you so much for your support !!
I am going to check PR and merge it )

![Screen Shot 2020-02-23 at 12 52 50 AM](https://user-images.githubusercontent.com/56922464/75101048-021ce880-55d7-11ea-93ff-1f49a5a06886.png)
