### ISSUE TITLE
bug(www) Missing `html=lang` attribute on www

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21567]
## Description

gatsbyjs.org doesn't have an `<html lang>` attribute

### Steps to reproduce

1. Open gatsbyjs.org
2. Run a Lighthouse audit for accessibility

### Expected result

100% passing.

### Actual result

97% passing with the following failure:

```
<html> element does not have a [lang] attribute
```

### Environment

N/A

**Comment by Neilblaze** [comment]
Hey @tesseralis can you assign this task to me?

**Comment by madalynrose** [comment]
I can't reproduce this in prod. Are you seeing it on development or in a particular browser? I know that we don't set the lang attribute pre-hydration. Is it possible that lighthouse was running against a pre-hydrated version of the page?

**Comment by tesseralis** [comment]
@madalynrose Hmm that's weird… I tried it again in prod and it looks like we're getting 100% on accessibility in Lighthouse. It might have been some weird blip. I'll close this issue for now since we can't reproduce it.
