### ISSUE TITLE
bug(www): Missing skip nav in certain pages of dot-org

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21565]
## Description

Certain pages of dot-org are missing `id="reach-skip-nav"` in the `<main>` element meaning that our [skip-nav](https://reacttraining.com/reach-ui/skip-nav/) doesn't work:

* template-contributor-page
* template-creator-details
* template-feature-comparison

In addition, these pages don't have a `<main>` element at all and thus no `reach-skip-nav` id:

* 404.js
* ecosystem.js
* newsletter.js
* pages/blog/tags.js
* templates/tags.js
* template-starter-page.js
* filtered-starters.js

## Steps to reproduce

1. Go to https://www.gatsbyjs.org/features/jamstack/gatsby-vs-nextjs/ or any one of the listed pages
2. Tab so that "skip to main content" is visible
3. Press "Enter"
4. Press tab

## Expected result

The next tabbed content is the main content.

## Actual result

The next tabbed content is the navigation.

**Comment by Wu-Bowen** [comment]
Hi @tesseralis, we'd like to take on this issue. You mention that 

> In addition, these pages don't have a <main> element at all and thus no reach-skip-nav id:

We're wondering where you had in mind to have the next tabbed content direct to. Would you like us to add a reach-skip-nav id to a non-main element?

**Comment by tesseralis** [comment]
@Wu-Bowen Ideally each page should have a `<main>` content. Also, ideally we would switch all instances to use `<SkipNavContent>` instead of relying on an ID.

@madalynrose what do you think?

**Comment by LekoArts** [comment]
Fixed all issues.
