### ISSUE TITLE
A little description on how to use jss in a gatsby component or page would be so great.

### ISSUE THREAD

**Issue by alexdobsom** [gatsbyjs/gatsby#21571]
I am trying to figure it out on how to use jss in Gatsby without Emotion or StyledComponents, and I have found good examples with [JS](https://codesandbox.io/s/z21lpmvv33) or [React-JSS](https://codesandbox.io/s/j3l06yyqpw) but I wish here were some examples with Gatsby so beginners would know how to use it right away inside their projects. 
Unfortunately the documentation only tells how to install the plugin basically. ☹

**Comment by vladar** [comment]
We do have a plugin [gatsby-plugin-jss](https://www.gatsbyjs.org/packages/gatsby-plugin-jss/) and an [example project](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-jss)

Does it help?

**Comment by alexdobsom** [comment]
Yeah, I already saw that example, but it cannot make it work in my project for some reason. But thanks anyways @vladar ;) I will keep on trying

**Comment by vladar** [comment]
Thank you for opening this, @alexdobsom 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
