### ISSUE TITLE
Google Tag Manager scroll depth trigger doesn't reset on new page route with Gatsby

### ISSUE THREAD

**Issue by AmberWilliams** [gatsbyjs/gatsby#21577]
Looks like I am not the only one with this issue either - https://stackoverflow.com/questions/55472262/scroll-depth-gtm-gatsby

The only way I have found around this using Gatsby is to create a scroll depth trigger for each and every page and then the events will still only fire once, which is not ideal.

**Comment by vladar** [comment]
Hi @AmberWilliams !

Do you have an example project where we could see this? Or even better - [a minimal reproduction][reproduction] so that we could start looking into it.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by AmberWilliams** [comment]
Hey @vladar if you head to https://test.kortical.com/articles/ scroll down to the bottom then look at the `dataLayer` in the console you will notice there are 4 `gtm.scrollThreshold` events (set to record 25/50/75/100 of scroll depths)

Then if you navigate to another article page and scroll to the bottom there are **not** another 4 events...however if you refresh that same page then scroll to the bottom the 4 events will appear. 

This shouldn't happen since I have under the tag firing options set to `unlimited` in the Tag configuration 
![image](https://user-images.githubusercontent.com/51619139/74838686-ea660b80-531b-11ea-9e11-cec150511637.png)
![image](https://user-images.githubusercontent.com/51619139/74838791-1aadaa00-531c-11ea-82f2-b6facc02d41c.png)

**Comment by vladar** [comment]
Thank you for the repro @AmberWilliams 

Looks like this plugin is mostly maintained by the community. So if you (or anyone) wants to tackle this - we will be happy to accept a PR!

**Comment by araphiel** [comment]
In GTM, you'll need to track events based on page load & history changes.
