### ISSUE TITLE
RFP for critical CSS plugin using Penthouse

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#2157]
This tool just came across my radar https://medium.com/@pocketjoso/penthouse-1-0-official-release-ece995b0d29e

It'd be a fantastic addition to gatsby to have a plugin for setting up critical css automatically. Perhaps with this we'd inline just the critical css then async load the rest.

**Comment by vilav** [comment]
Great idea! Was just researching about this (https://www.filamentgroup.com/lab/async-css.html)

**Comment by KyleAMathews** [comment]
Bummer, no one has done it yet :-(

Closing out old issues so if someone stumbles across this, `gatsby-plugin-penthouse` could still be yours to build!
