### ISSUE TITLE
Add Gatsby Cloud to the Deployment and Hosting Docs

### ISSUE THREAD

**Issue by laurieontech** [gatsbyjs/gatsby#21588]
## Summary

Currently, Gatsby Cloud is not represented on the OSS docs. A good choice for doing so is the [deployment and hosting docs](https://www.gatsbyjs.org/docs/deploying-and-hosting/).

Since Gatsby Cloud is a bit unique as an option there are a few things this doc could mention:
- What is Gatsby Cloud with a link to appropriate sections on [gatsbyjs.com](https://www.gatsbyjs.com/)
- GitHub integration
- CMS support
- The hosting integrations available

Note that this doc should point to Gatsby Cloud docs wherever possible/necessary. But the goal is to show how community members with Gatsby sites could use Gatsby Cloud for deployment and hosting.

### Motivation

Gatsby Cloud is a great option for Gatsby sites and we want people in the OSS docs to be aware of it.

### Draft the doc

- [x] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [x] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [x] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by ajzeller** [comment]
I'd like to take on this issue 🙌

**Comment by laurieontech** [comment]
Sounds great! Thanks @ajzeller.
