### ISSUE TITLE
How to link to another posts in Gatsby MDX

### ISSUE THREAD

**Issue by nikolayval** [gatsbyjs/gatsby#21585]
Hello!

I'm using Gatsby MDX for my blog posts. And I want to internal linking to another mdx-posts. 

Please, tell me. Whats there best way for linking? I should to use standart `<a href="">` tag, or I should import Gatsby-Link component, and use `<Link to=""` for internal links between mdx-posts?

Im internal linking not between .js-pages. I'm linking between .MDX-pages.

Sorry for bad English, im from Russia and thank you so much for Gatsby framework!

**Comment by vladar** [comment]
Hi @nikolayval !

You can do this with regular markdown links or using a Link component. 

Check out how we do it for Gatsby blog: https://raw.githubusercontent.com/gatsbyjs/gatsby/master/docs/blog/2019-06-25-profitable-agency-wordpress/index.md

Is it what you are looking for?

**Comment by nikolayval** [comment]
Yes, it's that I want. Thank you for your answer! I close the issue. Thank you very much!

**Comment by dsmitchell** [comment]
Hi @vladar 

The link appears broken now. I can see the actual blog post here: https://www.gatsbyjs.com/blog/2019-06-25-profitable-agency-wordpress/

But the index.md file in the source is no longer at the location. If you have time, can you re-locate it please?

**Comment by accoumar12** [comment]
> Hi @vladar
> 
> The link appears broken now. I can see the actual blog post here: https://www.gatsbyjs.com/blog/2019-06-25-profitable-agency-wordpress/
> 
> But the index.md file in the source is no longer at the location. If you have time, can you re-locate it please?

I am interesting in the solution if someone knows how to do it
