### ISSUE TITLE
(docs) Add context to the Starter README template

### ISSUE THREAD

**Issue by JQuinnie** [gatsbyjs/gatsby#21600]
## Summary

With the refactor of the Starter README template into its own page additional ( #21574) context should be added. This issue covers adding a quick blurb explaining a README and its purpose/goal for Starter projects.

### Motivation

Help people creating Starters make them more approachable to users!

### Draft the doc

- [ ] Update the doc with the above information

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by laurieontech** [comment]
Going to echo my [comment on the plugin PR](https://github.com/gatsbyjs/gatsby/issues/21599#issuecomment-597596989). This issue should be updated to reflect that it's creating a README template for a starter.

**Comment by marcysutton** [comment]
I'd also recommend looking at the [docs templates](https://www.gatsbyjs.org/contributing/docs-templates/) page, as that's where templates should go.
