### ISSUE TITLE
[gatsby-source-shopify] create parent-child link between products and variants

### ISSUE THREAD

**Issue by alexluong** [gatsbyjs/gatsby#21602]
## Summary

Create parent-child link between `ShopifyProduct` and `ShopifyProductVariant`

### Motivation

When working with Shopify, some time it's quite helpful to go up 1 level from variant to product. One example is to get product thumbnails from `checkout.lineItems` which contains `variantId`s.

---

I'd love to hear what you think about this idea?

**Comment by pieh** [comment]
Generally agree, just would want to clarify that this shouldn't be `parent/child` in sense of "gatsby nodes", but instead it should be regular link that will allow to traverse from variant to product.

From what I understand `gatsby-source-shopify` let's you access variants from product:
https://github.com/gatsbyjs/gatsby/blob/3197b6965106d7a1ca1ec0a6af9788f3ceab14f2/packages/gatsby-source-shopify/src/nodes.js#L102-L110

We would need similar thing for https://github.com/gatsbyjs/gatsby/blob/3197b6965106d7a1ca1ec0a6af9788f3ceab14f2/packages/gatsby-source-shopify/src/nodes.js#L148-L169

That would set `product___NODE` (but we would have to pass product node (full object or id) to that factory from https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-shopify/src/gatsby-node.js#L89-L99

**Comment by alexluong** [comment]
@pieh Thanks for promptly addressing the issue. I'd be happy to work on this.

**Comment by jzabala** [comment]
Hi @alexluong, still working on this one?

**Comment by alexluong** [comment]
Hey @jzabala, no I'm not working on this one. Turn out there are other ways to solve my problem.

I still think this is a great addition though. Feel free to take it on!

**Comment by jzabala** [comment]
> Hey @jzabala, no I'm not working on this one. Turn out there are other ways to solve my problem.
> 
> I still think this is a great addition though. Feel free to take it on!

Awesome @alexluong. Thanks for letting me know.

**Comment by LekoArts** [comment]
Hi! We've released a new major verison (v5) which fundamentally works different. Please try the upgrade and if you still hit this please open a new issue with a reproduction. Thanks!
