### ISSUE TITLE
Use of Gatsby source and transformer plugins for GraphQl outside of Gatsby

### ISSUE THREAD

**Issue by asos-jamesinnes** [gatsbyjs/gatsby#21616]
There are many great [extensions ](https://github.com/gatsbyjs/gatsby/tree/master/packages) as part of the Gatsby ecosystem with the the [gatsby-source-filesystem](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem/src) plugin allowing GraphQL queries to be made against a local file system which is best combined with appropriate file transformer plugins such as [gatsby-transformer-json](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-json) and [gatsby-plugin-sharp](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sharp)

Gatsby's `useStaticQuery` hook has some limitations mainly that it does not support variables https://github.com/gatsbyjs/gatsby/issues/10482 and the alternative solution of programmatically creating pages does not satisfy my use case either. Amongst other reasons this has prompted me to move to a full React stack with a backend.

 I have found a project [json-graphql-server](https://github.com/marmelab/json-graphql-server) that also allows for GraphQL queries against Json using an express server but I haven't found anything for file systems

My question is does anyone know how I might make use of the existing Gatsby plugins for GraphQL and other sources in a normal React stack running express/ node backend?

```js
// gatsby-config.js

module.exports = {
  siteMetadata: {
    title: `James Innes`,
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `${__dirname}/data`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-transformer-json`
  ],
}
```

```js
// server.js

const express = require("express");
const jsonGraphqlExpress = require("json-graphql-server");

const PORT = 3000;
const server = express();
const data = require("../data/db.js")

// Implementation of  'json-graphql-server' as middleware for Express
server.use('/graphql', jsonGraphqlExpress.default(data));

// Imagine adding some middleware based on 'gatsby-source-filesystem' :)

server.listen(PORT);
```

**Comment by pieh** [comment]
We don't have solution for production cases like that ... but you can run `gatsby develop` on some server and use `<url>/___graphql` endpoint (it shows the GraphiQL IDE when you visit using GET request, but it acts as regular graphql endpoint if you POST to it).

Now this is not great solution to use in production because there is no caching happening and it might be just slow. 

There is previous issue on similar topic: https://github.com/gatsbyjs/gatsby/issues/10230

**Comment by freiksenet** [comment]
Closing this issue as this isn't our priority, not on our roadmap and a workaround was provided.

Thanks!
