### ISSUE TITLE
Add graphqlRunner to onCreatePage Node API/event

### ISSUE THREAD

**Issue by tgallacher** [gatsbyjs/gatsby#21611]
## Summary

I have a use case for a plugin that requires access to the internal GraphQL data layer. However, this is not accessible from the `onCreatePage` Node API as the `graphql` runner is not passed to this event (unlike, for example, the `createPages` Node API). 

### Basic example

I would like to run something like: 

```js
// gatsby-node.js
exports.onCreatePage = async ({ page, graphql, actions }) => {
  const { createPage, deletePage } = actions;
  
  const { data, errors } = await graphql(`
  query {
    ...
  }
  `);

  // do something with data
  // ...

  deletePage(page);
  createPage({
    ...page,
    context: {
      ...page.context,
      // something from data layer
    });
}
```
### Motivation

This helps modularise functionality inside plugins (local or otherwise) and will help with encapsulation / re-use. 

As the above is not available in the `onCreatePage` Node API, this functionality is currently implemented as part of the `createPages` Node API, which bloats this event implementation, and makes it impossible to share with our other apps -- without copy paste. 

### Notes

I believe this will be a very simply change to implement, and shouldn't have a significant impact as all the necessary pieces (async runners, etc) are already in place. 

Happy to raise a PR for this.

**Comment by pieh** [comment]
What kind of things you want to query?

Implementation wise, yes this should be easy to pass `graphql` to `onCreatePage`. But it has some scaling problems associated with it - the `onCreatePage` doesn't run concurrently - it will always run one by one now. So we will be limited to executing single query at a time (as opposed to things like page queries where we execute many of them concurrently). It can quickly become bottleneck.

**Comment by tgallacher** [comment]
Ah. That could be a potential problem. 

And I suppose we can't really make this concurrent as then you will run into race conditions between plugins implementing this API.. I suppose if added, it is done so that the user's choice -- i.e. just document the potential impact of running large queries?

In the first case I have in mind, I basically want to run a query to grab some details from the `frontmatter` of each MD(x) file. This data is then used with some business logic to construct some extra context for the page, which is then used to display something on the page. 

p.s. thanks for the super fast response!

**Comment by freiksenet** [comment]
Frontmatter should already be accessible in page context for MDX.

https://www.gatsbyjs.org/docs/mdx/writing-pages/#using-frontmatter-in-mdx

**Comment by alexmacarthur** [comment]
I can't speak to the performance, maintainability, or anything else, but I wanted to do a similar thing and found a workaround using [Gatsby's Cache API](https://www.gatsbyjs.org/docs/build-caching/#the-cache-api). 

In my particular case, I'm sourcing nodes that I later want to attach as page context for particular pages. In the `sourceNodes` hook, I set my cache items: 

```js
exports.sourceNodes = async (
  { actions, cache, createContentDigest },
  configOptions
) => {
  // do all my sourceNode-y stuff. 
  await cache.set("someCacheKey", someData)
}
```

And then, later, I reference that key in `onCreatePage` and attach data to context: 

```js

exports.onCreatePage = async ({ page, actions, cache }) => {
  const someData = await cache.get("someCacheKey");

  deletePage(page)

  createPage({
    ...page,
    context: {
      ...page.context,
      someData
    }
  })
}
```

Again, this might be a bad idea for reason I have yet to discover, but it does meet my needs for now.
