### ISSUE TITLE
[gatsby-link] Programmatically change a.href

### ISSUE THREAD

**Issue by nicolaiparlog** [gatsbyjs/gatsby#21610]
First of all, I want to thank you folks for creating/maintaining Gatsby. I really like using it - in fact, this is the first time I genuinely enjoy web development! 1000 x Thanks! :revolving_hearts: 

## Summary

Is there a way to change `a.href` of an anchor created with Gatbsy's `Link` component, so that clicking the link leads to the new location. (It currently always leads to the one given to `Link.to`.

### What I did

I'm currently building a blog and it has the typical "tag pages", i.e. pages that show all posts belonging to a certain tag. Every post's header lists the tags it belongs to, and they link to the tag pages, e.g. `<Link to="/design-patterns">`. All of that works as expected, including for folks who have JS disabled.

I wanted to go beyond that, though, and created a live filter on the landing page. It's a small control with a list of all tags. Clicking on tags puts the selected tag(s) into the URL's hash and the post list next to the filter is then updated accordingly. This also works as expected, but of course only for people how have JS enabled.

### What I want to do

Now, here's the thing: For readers with JS enabled, I would like to change the behavior of the tag links in the post headers. Instead of `<Link to="/design-patterns">`, they should behave like `<Link to="/#design-patterns">` (note the hash). It's important that this only happens if JS is enabled because otherwise readers end up on the landing page with a hash in the URL that does nothing and so all tag links would effectively be broken for them.

### What I tried

The first one is the one this issue is actually about - the other ones are just here to clarify what else I tried and discarded.

#### Updating `href`

Adding this to my own Gatsby `Link` wrapper looked promising:

```jsx
useLayoutEffect(() => {
	const anchor = // get the <a... element
	anchor.href = anchor.href.replace(tag, "#" + tag)
})
```

But while the browser shows the correct URL (landing.page/#hash) as the link's target, clicking it still leads to the tag page - I assume the `Link` component doesn't expect `a.href` to change under it.

#### CSS only

I hoped that, with CSS' `:target`, I could filter the list of posts without JS:

* apply tags as CSS classes
* only show a post if one if it's "tag classes" is selected with `:target)

This would void the entire use case because then even non-JS users can be linked to landing.page/#hash. I don't think this can work, though, because if several tags are selected, none of the corresponding `:target` selectors get activated.

#### Forwarding from tag pages

It's easy to forward from the tag pages to the landing page with the according hash:

```jsx
useLayoutEffect(() => {
	window.location.replace(`/#${tag}`)
})
```

That works, but is very unpleasant because the tag page is visible for a split second before the landing page is shown. This also prevents `Link` from prefetching the eventual target of the link (i.e. the landing page).

#### Two links, one of them hidden

Instead of rendering a tag in the post header as `<Link to="/design-patterns">` I can use two links, one to the tag page and another to the landing page. Initially, the first is shown and the second is not, but `useLayoutEffect` runs some JS that hides the first and shows the second.

This works, but feels clunky.

## What I hope for

A way to update the href after the `Link` creation so that Gatsby's JS code realizes it and leads to the correct location when clicked.

## Environment

```
  System:
    OS: Linux 5.4 Gentoo/Linux
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Shell: 4.4.23 - /bin/bash
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
  Languages:
    Python: 3.6.9 - /usr/bin/python
  Browsers:
    Firefox: 68.4.2esr
  npmPackages:
    gatsby: ^2.19.5 => 2.19.17
    gatsby-background-image: ^0.9.14 => 0.9.14
    gatsby-image: ^2.2.39 => 2.2.41
    gatsby-link: ^2.2.28 => 2.2.29
    gatsby-plugin-feed: ^2.3.26 => 2.3.27
    gatsby-plugin-matomo: ^0.7.2 => 0.7.2
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.22
    gatsby-plugin-sharp: ^2.4.0 => 2.4.5
    gatsby-react-router-scroll: ^2.1.20 => 2.1.21
    gatsby-remark-autolink-headers: ^2.1.23 => 2.1.24
    gatsby-remark-prismjs: ^3.3.30 => 3.3.31
    gatsby-source-filesystem: ^2.1.46 => 2.1.48
    gatsby-transformer-json: ^2.2.25 => 2.2.26
    gatsby-transformer-remark: ^2.6.48 => 2.6.51
    gatsby-transformer-sharp: ^2.3.13 => 2.3.14
```

**Comment by pieh** [comment]
> #### Updating `href`
> Adding this to my own Gatsby `Link` wrapper looked promising:
> 
> ```js-jsx
> useLayoutEffect(() => {
> 	const anchor = // get the <a... element
> 	anchor.href = anchor.href.replace(tag, "#" + tag)
> })
> ```
> 
> But while the browser shows the correct URL (landing.page/#hash) as the link's target, clicking it still leads to the tag page - I assume the `Link` component doesn't expect `a.href` to change under it.

That's because with JS enabled we will prevent executing actual default html anchor behaviour and we will rely on runtime implementation for it, so it will use whatever `to` prop is saying.

I think if we could come up with solution using `use(Layout)Effect`, but one that doesn't change `href` of html element but rather changes `to` prop on a `Link` component. Something along those lines:


```jsx
import React, { useState, useLayoutEffect } from "react"
import { Link } from "gatsby"

// wrapper around gatsby-link for post header tag links
// pass `tagName` that will be used to generate `/${tagName}` in SSR
// that will be changed to `#${tagName}` in browser if JS is enabled
const HeaderTagLink = ({ tagName, children }) => {
  const [jsEnabled, setJsEnabled] = useState(false)
  useLayoutEffect(() => {
	setJsEnabled(true)
  }, [])
  return <Link to={jsEnabled ? `/${tagName}` : `#${tagName}`}>{children}</Link>
}
```

and use it in your other components like this:

```jsx
<HeaderTagLink tagName="someTag">
  this is a header tag link
</HeaderTagLink>
```

I didn't try it, but "should work" (might need some iterations)

**Comment by freiksenet** [comment]
I'll be closing this issue, please feel free to reopen it if you have any further questions.

**Comment by nicolaiparlog** [comment]
Found some time to give @pieh's idea a try and it works like a charm, thank you! I already have a custom wrapper around `Link` (I use it for all URLs and it then distinguishes between internal and external ones) and I put it there, so it gets a `jsTo` in addition to its `to` attribute. Maybe something to consider for `Link` itself?

Either way, this one is solved, thanks again! :smiley:

**Comment by pieh** [comment]
I would be against increasing API surface of `gatsby-link` - it's meant to be "basic" link that should work (somewhat) the same regardless if JS is enabled or not.

However it's also composable (users can create wrappers around it like you already did), so maybe this could be documented 🤔 

But I'm honestly not sure if the solution I provided is accessible - there are some thoughts about this in https://a11y-101.com/design/button-vs-link where it's mention that we should use proper markup that reflect kind of action that will happen when you "execute" interactive element. So because in here you are not actually navigating - maybe the proper solution here in terms of accessibility would be to actually making this a <button> instead of changing `to` prop (as it filters things on the same page) - that is if JS is disabled - baseline should still use Link

**Comment by nicolaiparlog** [comment]
In my use case, it's still a proper link - just the target changes: either tag page or landing page with tag in hash
