### ISSUE TITLE
Remote file nodes removed as stale every develop/ build

### ISSUE THREAD

**Issue by AitchWebb** [gatsbyjs/gatsby#21629]
## Description

File nodes created by feeding remote images into gatsby-image are removed as stale nodes every develop/ build.

### Steps to reproduce

When following this [example](https://www.gatsbyjs.org/docs/schema-customization/#feeding-remote-images-into-gatsby-image.) the 'File' nodes are deleted every develop/ build for me.

But I have found that following this [tutorial](https://thoughtsandstuff.com/gatsby-with-wordpress-caching-downloaded-media-images-to-reduce-build-time/) as well as touching all 'File' nodes using the 'sourceNodes' API helper remedies the situation.

[Here's an example repo.](https://github.com/AitchWebb/aitchwebb.github.io)

### Expected result

Unchanged images should remain cached as long as plugins have not changed.

### Actual result

Images are redownloaded and reprocessed each time.

### Environment

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 80.0.3987.116
    Firefox: 67.0.3
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.10 => 2.19.12
    gatsby-image: ^2.2.31 => 2.2.39
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-extract-image-colors: 0.0.14 => 0.0.14
    gatsby-plugin-graphql-image: ^1.0.1 => 1.0.1
    gatsby-plugin-layout: ^1.1.22 => 1.1.22
    gatsby-plugin-manifest: ^2.2.37 => 2.2.38
    gatsby-plugin-netlify: ^2.1.32 => 2.1.32
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-offline: ^3.0.19 => 3.0.32
    gatsby-plugin-preact: ^3.1.26 => 3.1.26
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-react-helmet-async: ^1.0.15 => 1.0.15
    gatsby-plugin-remote-images: ^2.1.0 => 2.1.0
    gatsby-plugin-sass: ^2.1.24 => 2.1.27
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5
    gatsby-plugin-sitemap: ^2.2.26 => 2.2.26
    gatsby-plugin-transition-link: ^1.17.7 => 1.17.7
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-source-graphql: ^2.1.31 => 2.1.32
    gatsby-transformer-sharp: ^2.3.6 => 2.3.13

**Comment by freiksenet** [comment]
Hi!

Does etag stay the same for the file you are downloading? We are using etag to select whether something is stale or not.

Thanks!

**Comment by danabrit** [comment]
Closing due to no response.
