### ISSUE TITLE
bug(www): square-starter causing validation errors

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21635]
## Description

The recently added square-starter is causing a validation error:

https://github.com/gatsbyjs/gatsby/runs/459451213

Please fix this error by removing the invalid tags or adding a new tag to categories.yml.

**Comment by jonniebigodes** [comment]
@tesseralis thank you for bringing this to my attention. I'll update the necessary files and submit a pr later to you. Sorry for the inconvenience that the starter submission introduced.

**Comment by tesseralis** [comment]
@jonniebigodes no worries! it's not failing any builds so no inconvenience to me. :)
