### ISSUE TITLE
chore(docs): Use parser="mdx" for formatting docs

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21630]
## Description

All our docs are read as MDX in our site, but because they all use the extension `.md`, they are treated as Markdown when formatted with prettier. This can lead to issues when prettier interprets code as text: #21609.

The fix is to (1) convert all our docs to use the `.mdx` file extension (bad idea) or (2), add a config override in our `.prettierrc.js`:

```
{
  "overrides": [
    {
      "files": "/docs/*.md",
      "options": {
        "parser": "mdx"
      }
    }
  ]
}
```

**Comment by pieh** [comment]
Let's go with prettier config. 

Renaming files would be tedious and what add unneeded noise in the repo (worst case scenario would be losing history for some files, which shouldn't happen, but we had some issue with that in the past)

**Comment by akshitkrnagpal** [comment]
@tesseralis Yes. You can assign this to me. I'll create a PR for this too.
