### ISSUE TITLE
The service worker no longer works

### ISSUE THREAD

**Issue by Skeinet** [gatsbyjs/gatsby#21643]
I am building an app with Gatsby and I had set up the working service worker.
Lately, I believe following a Chrome update, the service worker no longer starts.
I specify that I am testing the app locally https: // localhost: 8000 /

Any suggestion?

gatsby-config.js
require('dotenv').config()

module.exports = {
  siteMetadata: {
    title: `My App`,
    siteUrl: `https://www.local.org`,
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sass',
    'gatsby-plugin-eslint',
    'gatsby-plugin-resolve-src',
    'gatsby-plugin-polyfill-io',
    {
      resolve: 'gatsby-plugin-nprogress',
      options: {
        // Setting a color is optional.
        color: '#663399',
        // Disable the loading spinner.
        showSpinner: false,
      },
    },
    {
      resolve: 'gatsby-plugin-manifest',
      options: {
        name: 'gatsby-sleek-starter',
        short_name: 'sleek',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: `${__dirname}/src/assets/images/logos/logo.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: 'gatsby-plugin-favicon',
      options: {
        logo: './src/assets/images/logos/logo.png',
        injectHTML: true,
        icons: {
          android: true,
          appleIcon: true,
          appleStartup: true,
          coast: false,
          favicons: true,
          firefox: true,
          twitter: false,
          yandex: false,
          windows: false,
        },
      },
    },
    {
      resolve: 'gatsby-plugin-react-svg',
      options: {
        rule: {
          include: `${__dirname}/src/assets/`,
        },
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: `src`,
        path: `${__dirname}/src/`,
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    'gatsby-plugin-offline',
    'gatsby-plugin-sitemap',
    {
      resolve: 'gatsby-plugin-google-tagmanager',
      options: {
        id: process.env.GTM_CONTAINER_ID,
        includeInDevelopment: false,
      },
    },
    'gatsby-plugin-netlify-cache',
    'gatsby-plugin-netlify', // make sure to put last in the array
  ],
}

**Comment by freiksenet** [comment]
Could you specify your current chrome version where it doesn't work?

Thanks!

**Comment by Skeinet** [comment]
Versione 80.0.3987.116 (Build ufficiale) (a 64 bit)

**Comment by freiksenet** [comment]
It's likely that you had that service worker registered previously from your production build, but it got unregistered. We don't register service workers in `gatsby develop`. You should see that sw works fine by running `gatsby build` and then running `gatsby serve`.

Feel free to re-open this issue if you have any further questions.
