### ISSUE TITLE
gatsby-transformer-remark to add break support

### ISSUE THREAD

**Issue by LuckyRabbitFeet** [gatsbyjs/gatsby#21641]
## Summary

Hope to integrate [remark-breaks](https://github.com/remarkjs/remark-breaks) plugin.

> plugin to add break support, without needing spaces

### Basic example

![Snipaste_2020-02-21_15-41-00](https://user-images.githubusercontent.com/32757528/75014215-c09a1980-54c0-11ea-901c-0b982fc9e8f6.png)

### Motivation

I know Markdown can use double space or `<br>` for line breaks, but I always forget to add them😓

And I have too many old Markdown without double space or `<br>`,  organizing them is a very energy and time consuming job, so I want to ask for help in this regard.

**Comment by freiksenet** [comment]
We don't usually add new packages to Gatsby monorepo and currently this isn't a priority for us. However, you are welcome to create this package and add it to our Plugin repository. Here is a [Remark Plugin Tutorial](https://www.gatsbyjs.org/docs/remark-plugin-tutorial/) that shows how to do that.

Thank you! :purple_heart:
