### ISSUE TITLE
Connect to another graphql server

### ISSUE THREAD

**Issue by fitfab** [gatsbyjs/gatsby#2165]
so I want to point to another graphql server, where should I do that? in the webpack configuration?

**Comment by craig-mulligan** [comment]
Interesting, I've also been thinking about this a little. If gatsby's data generator was it's own module we could you gatsby plugins in non-gatsby apps too. 

For instance if it had the following api: 
```
cont { schema } = await require('gatsby-data')(gatsbyConfig)
```
Then we could load that schema and run it with other apps, it'd also have the side effect of have the schema generation self contained and easy to run gatsby without graphql for instance:

```
gatsby develop --no-data
```

**Comment by dbrookes** [comment]
Is there a way to do this without building a `gatsby-source` plugin for the external graphql server?

**Comment by KyleAMathews** [comment]
Not yet. There's a proposal for mirroring external GraphQL servers but the work needs done still.

**Comment by johanneslamers** [comment]
@KyleAMathews any updates on this proposal?

**Comment by Joostvanderlaan** [comment]
I tried this with GraphCMS source plugin, that works fine! I think that could be used as a base for a more generic GraphQL-source plugin.

**Comment by KyleAMathews** [comment]
Closing this issue as it's fairly old and we have far too many open issues! If you have additional problems in this area, please open a new issue!
