### ISSUE TITLE
Add Cloudflare Workers Sites to the Deployment and Hosting Docs 

### ISSUE THREAD

**Issue by victoriabernard92** [gatsbyjs/gatsby#21652]
## Summary
 Currently, Cloudflare Workers Sites is not represented on the OSS docs. A good choice for doing so is the [deployment and hosting docs](https://www.gatsbyjs.org/docs/deploying-and-hosting/).
 
Content to include:
* [x]  Barebone how to install and config wrangler but point to Cloudflare docs for details
* [x]  Github action for auto deploys

 ### Motivation
Cloudflare Workers is a great, affordable option for Gatsby sites and we want people in the OSS docs to be aware of it.
 
 ### Draft the doc
 * [x]  Write the doc, following the format listed in these resources:
   * [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
   * [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
   * Example of a similar article: https://github.com/gatsbyjs/gatsby/issues/21588
 * [x]  Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.
 
 ### Open a pull request
 * [x]  Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by victoriabernard92** [comment]
I'd like to take this issue :)

**Comment by TylerBarnes** [comment]
@victoriabernard92 this sounds like a good addition to the docs! CC @gatsbyjs/learning
