### ISSUE TITLE
devcert wrong upstream

### ISSUE THREAD

**Issue by jacopomaroli** [gatsbyjs/gatsby#21668]
## Description

As you can see from here https://www.npmjs.com/package/devcert-san this NPM package is not receiving updates since 3 years. It seems the name has been changed and this is the new NPM package corresponding to the same updated repo https://www.npmjs.com/package/devcert

### Steps to reproduce

`npm i gatsby`
check your package-lock.json for devcert and you'll see devcert-san listed instead of currently maintained package named devcert

### Expected result

devcert should be used

### Actual result

devcert-san got used

### Environment

  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.14
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: ^2.18.3 => 2.18.3

**Comment by LekoArts** [comment]
Hi, thanks for the issue. You can follow progress on that here: https://github.com/gatsbyjs/gatsby/pull/16726
