### ISSUE TITLE
chore(www): Use react-icons' discord icon instead of our custom one

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21661]
## Description

I don't see why we're using a custom discord icon component instead of the one that react-icons has. I'm guessing we included it before react-icons added it in, but we should be able to switch it out now.

**Comment by HarryFray** [comment]
@tesseralis looking into it. This might be my first contribution to open source! 😅

 Looks like the Icon is only used in one place.

**Comment by tesseralis** [comment]
@HarryFray go ahead!

**Comment by fk** [comment]
> I'm guessing we included it before react-icons added it in

Yep! `www` is still using `react-icons` v2
https://github.com/gatsbyjs/gatsby/blob/ff5458502473b4f50febc717266ce039ac26a93f/www/package.json#L89
The version of Font Awesome icons it includes didn't have it: https://react-icons.github.io/react-icons/fa.html

> but we should be able to switch it out now.

💯https://react-icons.netlify.com/#/icons/fa
