### ISSUE TITLE
abruptly scroll to the target URL 

### ISSUE THREAD

**Issue by nitishk72** [gatsbyjs/gatsby#21676]
## Summary

Whenever I click on the Link which don't open the other page but scroll page to the particular section. 
The scroll is done abruptly and we can make it better using the CSS property smooth scroll 

### Motivation

I didin't like the default scroll property because it is not good for eye as it's abruptly .  I think of making the scroll smooth and  start searching for the solution . I landed to a article on [CSS Tricks](https://css-tricks.com/almanac/properties/s/scroll-behavior/) which explains this.

## Steps to resolve this issue

Add CSS Propery `smooth-scroll` to the html element becasue target URL is available in almost every page.

**Comment by herecydev** [comment]
Better is subjective, it might not be better for every user especially for [those who prefer reduced motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion). Are you asking how to implement this on your gatsby site?

**Comment by LekoArts** [comment]
Hi, thanks for the issue. This doesn't seem to describe a bug or feature request and hence I'm closing this for now.
