### ISSUE TITLE
DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/js').

### ISSUE THREAD

**Issue by inthedeepend** [gatsbyjs/gatsby#2167]
I am receiving this error on a `gatsby build` deployed to S3/Cloudfront.
 
If I check the metadata of the file on S3 it is definitely  Content-Type : 'text/js'. 
I'm curious if anyone else has experienced this and if so, how did they fix it? Is this an issue with Gatsby or am I missing something here...?

`app-661592789047219aa410.js:1 Error during service worker registration: DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/js').
(anonymous) @ app-661592789047219aa410.js:1`

**Comment by dbrookes** [comment]
I think the correct mime type to use is `application/javascript`, check the settings in the software you're using to upload to S3

**Comment by andersonsantos** [comment]
I'm having the same problem. Even tried to change the content type at the S3 bucket, but for some reason S3/Cloudfront changes it back to text/js.

@inthedeepend did you find a fix for this?

Thanks!

**Comment by inthedeepend** [comment]
@andersonsantos It's not elegant by any stretch, but as @dbrookes mentioned. You need to set the meta for the sw.js file as application/javascript. You will need to manually type this as S3 does not provide this MIME type by default.

**Comment by KyleAMathews** [comment]
Closing this issue as it's fairly old and we have far too many open issues! If you have additional problems in this area, please open a new issue!
