### ISSUE TITLE
Gatsby warning: Plugin `gatsby-source-filesystem` tried to define the GraphQL type `File`

### ISSUE THREAD

**Issue by sniperyork** [gatsbyjs/gatsby#21673]
## Summary
when I run "gatsby develop" or "gatsby build" command for my gatsby site, the site launches/builds fine, however it displays the following warning during the build process:

`warn Plugin `gatsby-source-filesystem` tried to define the GraphQL type `File`, which has already been defined by the plugin `null`.`

I want to understand what this is a warning and how to get it fixed.
## Relevant information
I'm getting the same warning on a fresh install of gatsby starter default during gatsby develop. The site builds but the warning persists.

### Environment (if relevant)

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.116
    Firefox: 63.0
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.17 => 2.18.17
    gatsby-background-image: ^0.9.18 => 0.9.18
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-canonical-urls: ^2.1.18 => 2.1.18
    gatsby-plugin-manifest: ^2.2.30 => 2.2.30
    gatsby-plugin-offline: ^3.0.24 => 3.0.24
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sass: ^2.1.24 => 2.1.24
    gatsby-plugin-sharp: ^2.3.4 => 2.3.4
    gatsby-source-filesystem: ^2.1.39 => 2.1.39
    gatsby-transformer-sharp: ^2.3.6 => 2.3.6
  npmGlobalPackages:
    gatsby-cli: 2.8.30

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by mniederm** [comment]
I get the same message: warn Plugin `gatsby-source-filesystem` tried to define the GraphQL type `File`, which has already been defined by

{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },

Would be also interesting for me. THX

**Comment by vladar** [comment]
This happens when you use an older version of `gatsby-source-filesystem` plugin with the newer version of gatsby core.

This is a harmless warning but the solution is to upgrade to `gatsby-source-filesystem@^2.1.41`

**Comment by vladar** [comment]
Thank you for opening this, @sniperyork 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
