### ISSUE TITLE
gatsby-plugin-mdx: MDXRender accepts components - but no functionality

### ISSUE THREAD

**Issue by ohlr** [gatsbyjs/gatsby#21682]
## Description

https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/#mdxprovider
accepts components to allow modification

MDXRerender also accepts components but it does not do anything with them.

### Steps to reproduce

```
    <MDXRenderer
      components={{
        a: MdxLink,
      }}
    >
      {mdx.code.body}
    </MDXRenderer>
```

This neither changes the a tag to MdxLink nor throws an error.
This should not be the case at least in typescript

### Expected result

What should happen?
Either remove the components property or add the the functionality of MDXProvider to MDXRenderer.

### Environment
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Languages:
    Python: 3.7.3 - /home/user/anaconda3/bin/python
  Browsers:
    Chrome: 80.0.3987.106
    Firefox: 73.0
  npmPackages:
    gatsby: ^2.15.24 => 2.15.24 
    gatsby-plugin-layout: ^1.1.22 => 1.1.22 
    gatsby-plugin-mdx: ^1.0.73 => 1.0.73 
    gatsby-plugin-react-helmet: ^3.1.8 => 3.1.8 
    gatsby-plugin-typescript: ^2.1.9 => 2.1.9 
    gatsby-source-filesystem: ^2.1.46 => 2.1.46 
    gatsby-transformer-json: ^2.2.26 => 2.2.26 
  npmGlobalPackages:
    gatsby-cli: 2.8.27

**Comment by johno** [comment]
Thanks for opening this issue! We should remove the `components` prop from MDXRenderer because it's not actually being used and that functionality can be achieved using the MDXProvider.

We won't need to make it a breaking change to remove the prop because it was never being passed on properly in the first place.

**Comment by LekoArts** [comment]
@johno @gatsbyjs/learning This will also need some documentation work.

**Comment by Arthur092** [comment]
Hi guys, so are we removing the component property from documentation?
I am a new contributor, I'd like to do it if you don't mind :)
Let me know so I can create the PR

**Comment by floAr** [comment]
I took it up as the issue was getting rather quiet. Quick question: Would it also be preferred to directly convert to typescript?
