### ISSUE TITLE
Working with content from a Headless CMS

### ISSUE THREAD

**Issue by chrish-d** [gatsbyjs/gatsby#21680]
## Summary

I'm using a Headless CMS called [Storyblok](https://storyblok.com) which has a very useful live editor. To render out the components for each page you essentially do a `React.createElement` function and pass it the props for the page you're viewing (there's more on that [here](https://www.storyblok.com/tp/gatsby-multilanguage-website-tutorial)).

This works great when you're passing things like text or other simple bits of content as you can just do `props.text` inside your component to grab whatever you need. It becomes a headache when you're trying to work with something dynamic like images and you want to use `gatsby-image` to handle them because suddenly you're kind of required to use GraphQL which up until now hasn't been necessary.

I'm at a bit of a crossroads with how to approach this; on the one hand, I know what I'm doing works (except for the images unless you just want to serve whatever the user uploads (bad idea)). On the other hand, I feel like it's the wrong approach, as GraphQL seems to be the correct way to do things.

Could anyone help point me in the right direction? What is the proper way of getting content down from the CMS? Help 🤯

## Relevant information

The `editor.js` file I use is a customised version of the one linked in the tutorial (I updated it to use functional components) and it looks like this;

```
import React, { useState, useEffect, useCallback } from 'react';
import config from '../../gatsby-config';
import StoryblokComponents from '../components/StoryblokComponents';

// ============================================================================

const sbConfigs = config.plugins.filter(item => {
  return item.resolve === `gatsby-source-storyblok`;
});
const sbConfig = sbConfigs.length > 0 ? sbConfigs[0] : {};

// ============================================================================

const LoadStoryblokBridge = cb => {
  const script = document.createElement('script');
  script.type = 'text/javascript';
  script.src = `//app.storyblok.com/f/storyblok-latest.js?t=${sbConfig.options.accessToken}`;
  script.onload = cb;
  document.getElementsByTagName('head')[0].appendChild(script);
};

// ============================================================================

const StoryblokEntry = () => {
  const [story, setStory] = useState();

  const loadStory = useCallback(() => {
    window.storyblok.get(
      {
        slug: window.storyblok.getParam(`path`),
        version: `draft`,
        resolve_relations: sbConfig.options.resolveRelations || [],
      },
      data => {
        setStory(data.story);
      }
    );
  });

  const initStoryblokEvents = useCallback(() => {
    loadStory();

    const sb = window.storyblok;

    sb.on(['change', 'published'], () => {
      loadStory();
    });

    sb.on(['input'], payload => {
      const pl = payload;
      pl.story.content = sb.addComments(pl.story.content, pl.story.id);
      setStory(payload.story);
    });

    sb.pingEditor(() => {
      if (sb.inEditor) {
        sb.enterEditmode();
      }
    });
  }, [loadStory, story]);

  useEffect(() => {
    LoadStoryblokBridge(() => {
      initStoryblokEvents();
    });
  }, []);

  if (!story) {
    return <div />;
  }

  const { content } = story;

  return (
    <>
      {React.createElement(StoryblokComponents(content.component), {
        // eslint-disable-next-line no-underscore-dangle
        key: content._uid,
        blok: content,
      })}
    </>
  );
};

// ============================================================================

export default StoryblokEntry;
```

**Comment by herecydev** [comment]
There's a [StoryBlok plugin](https://www.gatsbyjs.org/packages/gatsby-source-storyblok/) that you can integrate into your site using the [instructions here](https://www.gatsbyjs.org/docs/using-a-plugin-in-your-site/).

[Part 4 of the tutorial](https://www.gatsbyjs.org/tutorial/part-four/) shows how to query the data once Gatsby has sourced it from StoryBlok via the plugin. The example uses different data, but you should be able to understand how to query your own data after reading that tutorial section.

Let me know if you need any help.

**Comment by chrish-d** [comment]
@herecydev thanks for the input on this, it looks like this could be the right approach, however this plugin kind of just gives you a stringified object for all of the content. For example;

**Comment by herecydev** [comment]
I simply don't know enough about StoryBlok or what you're trying to achieve to give you a solid answer. But it might be worth trying to form some graphl queries together first via the explorer (default: http://localhost:8000/___graphql).

All gatsby can do is provide the means to source your data and run your queries, it's up to you and how you want to structure react components to make the magic happen. If you've got the object to work with now perhaps try rendering the parts you care about (i.e. the img)

```
export default () => {
  const data = useStaticQuery(graphql`
    {
      allStoryblokEntry {
        edges {
          node {
            content
          }
        }
      }
    }
  `);
const parsed = JSON.parse(data)
  return (
    <img src={parsed.foo.bar.image} />
  )
}
```

**Comment by LekoArts** [comment]
Thank you for opening this!

Since we don't maintain the plugin I'd recommend opening an issue on their repository:
https://github.com/storyblok/gatsby-source-storyblok

They will be able to help you, e.g. with: https://github.com/storyblok/gatsby-source-storyblok/issues/9

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
