### ISSUE TITLE
[www] Portions of layout not loading on hard refresh OR direct link

### ISSUE THREAD

**Issue by markmichon** [gatsbyjs/gatsby#2169]
When navigating to a page from within the site, tutorial 4 for example, the page shows fine. However, when directly linking from an outside source or going to the page manually (or hard refreshing) the sidebar and various containing styles are lost. [Tutorial 4](https://www.gatsbyjs.org/tutorial/part-four/)

Correct behavior:
<img width="1679" alt="screen shot 2017-09-19 at 10 01 32 am" src="https://user-images.githubusercontent.com/1649672/30596301-b7162042-9d21-11e7-81a3-8952dd2dad14.png">

Incorrect behavior:
<img width="1680" alt="screen shot 2017-09-19 at 10 01 18 am" src="https://user-images.githubusercontent.com/1649672/30596312-c1aa6522-9d21-11e7-951b-c38575678e50.png">

**Comment by fk** [comment]
👍  Noticed that yesterday, too, also popped up on Twitter: https://twitter.com/scottnonnenberg/status/909884944452694017

**Comment by fk** [comment]
@KyleAMathews FWIW – seeing this again, right after adding gatsby-plugin-react-next.

**Comment by nickytonline** [comment]
@KyleAMathews, great project. Thanks for all your work you've put into this. I'm currently using it for my blog that I host on now.sh. I see a similar behaviour with the Twitter plugin. If I navigate to my blog post, the Twitter plugin loads correctly, but if I refresh the page, I see just the blockquote rendered in my markdown file. To see this in action, https://www.iamdeveloper.com/why-you-might-want-to-consider-using-typescript/ (not trying to promote my blog, it's just the only place where I can show the bug 😉).

If you need any more info, let me know.

**Comment by KyleAMathews** [comment]
@nickytonline this PR might have fixed that issue https://github.com/gatsbyjs/gatsby/pull/2432

I doubt your twitter issue is related to the original issue.

**Comment by nickytonline** [comment]
Cool, thanks @KyleAMathews. 👍 I'll check it out tonight.
