### ISSUE TITLE
Migrate to import * as React from 'react' and remove commonjs interop import

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#21697]
# Description
Reactjs has merged https://github.com/facebook/react/pull/18102 and are moving into es module exports so the correct way of importing react will be `import * as React from 'react'`, they will keep the default exports to keep everything working as expecting.

We should update our documentation and internal code to move to the new import statement.

### Expected result

All react imports should be `import * as React from 'react'`

### Actual result

All react imports should be `import React from 'react'`

More info:
- https://github.com/facebook/react/pull/18102
- https://github.com/facebook/react/pull/18106
- https://github.com/facebook/react/pull/18094

**Comment by kartik918** [comment]
Hi I'm new to the Gatsby repo. This seems like a good first issue to work on and get started here. 
I see the first attempt at this issue had multiple test failures. Can you guide me what directories require to be migrated and why the early tests failed?
