### ISSUE TITLE
Unclear License and Copyright in Gatsby Default Starter

### ISSUE THREAD

**Issue by jeffrafter** [gatsbyjs/gatsby#21695]
## Summary

When starting a new Gatsby project following the https://www.gatsbyjs.org/docs/quick-start/ a site is generated using the Gatsby Default Starter. By default this project skeleton includes a `LICENSE` file (https://github.com/gatsbyjs/gatsby-starter-default/blob/master/LICENSE) committed in 2015. This file leverages the MIT license:

```
The MIT License (MIT)
```

and contains a Copyright:

```
Copyright (c) 2015 gatsbyjs
```

Additionally the `package.json` contains [authorship](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/package.json#L6):

```
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
```

And a [license](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/package.json#L27):

```
  "license": "MIT",
```

It is unclear what the intent of these declarations are in the generated project but, without any modification, subsequent changes by the blog author would appear to be covered by both the license and the copyright which feels incorrect.

In general, I am in favor of protecting Gatsby's (and @KyleAMathews) copyright and IP here but for my own blog I would like guidance on the changes I add. Should I:

1. Remove the license and copyright from the generated project (they were just there for the default)
2. Live with the license and the copyright forever (don't use the default when making something real)
3. Dual license and dual copyright going forward (confusing)

If the answer is `1` then it might make sense to omit these from the generated project to begin with. In any case it might make sense to include any such guidance in the `gatsby-default-starter` and Quick Start documentation. I'd be happy to put together a PR if that's helpful.

**Comment by LekoArts** [comment]
Hi Jeff, thanks for opening the issue!

I'm not a lawyer so this is my personal interpretation of those terms:
The important bit is the license (MIT) here, the copyright doesn't change that. The author field is a metatag for npmjs.com and not related to any authorship.

Quoting from [GitHub](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project):

> It’s short, very easy to understand, and allows anyone to do anything so long as they keep a copy of the license, including your copyright notice.

Or https://choosealicense.com/licenses/mit/:

> A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.

So do whatever the MIT license allows with the project which would for example be:
Keep the MIT license and add you copyright statement above the one from us.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by jeffrafter** [comment]
Thanks for the response @LekoArts. I'm happy to discuss this further over in communities but was really hoping that the outcome here would be a PR that either exempted the blog author in the form of documentation or had the Copyright removed in the generated blog. Clearly it isn't a big deal to have both but it means someone might have to evaluate this for every Gatsby blog they create. 

The backstory here is: I was working on a blog post about setting up Gatsby (because Gatsby is the best, obviously)  from the ground up and wanted to switch part of it to use the quick start tutorial. But because of the copyright (and to a lesser extent the license) I find myself in a position where I'll recommend against using the quick start. I don't think that is the intent of the copyright in the generated blog. My interpretation is that it is included to copyright the work in the original repository.

**Comment by LekoArts** [comment]
I asked Kyle:

Our stance on this is: Feel free to edit the LICENSE in the starters.
The LICENSE is more like a template for the user where the person enters their information. In the future we definitely will want to automatically add this while e.g. running `gatsby new` or on Gatsby Cloud.
