### ISSUE TITLE
Hosting it to traditional hositng server instead of Netlify

### ISSUE THREAD

**Issue by expatguideturkey** [gatsbyjs/gatsby#21699]
Is it possible to host the Gatsby website on Plesk based hosting server. 

As if I am hosting it to Netlify and then if I configure my external DNS provider to point my domain to Netlify. I believe there will be troubles with email accounts that are associated with my domain after pointing it to Netlify domain or any trouble in receiving emails.

Please advise.

**Comment by idindrakusuma** [comment]
**Basically, You can host Gatsby in any hosting server.** 
If your hosting server not support Git. You can upload your Gatsby build into your hosting server.

Please refer this doc: https://www.gatsbyjs.org/docs/preparing-for-deployment/

**Comment by expatguideturkey** [comment]
> Basically, You can host Gatsby in any hosting server.
> If your hosting server not support Git. You can upload your Gatsby build into your hosting server.
> Please refer this doc: https://www.gatsbyjs.org/docs/preparing-for-deployment/

@idindrakusuma thanks for your response. I am using Netlify forms, what should I do about that. My existing site is hosted on https://www.plesk.com/ I installed Git and pushed the Gatsby files but Gatsby site did not show up just the default page of Plesk show up. The files are deployed to httpdocs/
![image](https://user-images.githubusercontent.com/59199468/75157428-24bd1780-5725-11ea-97e4-448baf3db7fa.png)

**Comment by idindrakusuma** [comment]
Unfortunately, I never use Plask. But the concept is, you need to build your page and pointing to the public directory.

> I installed Git and pushed the Gatsby files but Gatsby site did not show up just the default page of Plesk show up.

Are you already running `gatsby build` into your hosting? 
and make sure pointing your hosting to `/public` gatsby directory?

**Comment by expatguideturkey** [comment]
> atsby build into your hosting



> Unfortunately, I never use Plask. But the concept is, you need to build your page and pointing to the public directory.
> 
> I installed Git and pushed the Gatsby files but Gatsby site did not show up just the default page of Plesk show up.
> 
> Are you already running gatsby build into your hosting?
> and make sure pointing your hosting to /public gatsby directory?

> Are you already running gatsby build into your hosting?

 Where should I run this command locally or on host server.

The files got stored here:
![image](https://user-images.githubusercontent.com/59199468/75159673-a3b44f00-5729-11ea-8bca-9914efed08e5.png)

How should I setup my Netlify form here.

**Comment by idindrakusuma** [comment]
Ah i see. You still upload the raw file.

Try to run `gatsby build` in your local machine.
then see the `/public` directory. You should upload all files in `/public` into your hosting .

**Comment by LekoArts** [comment]
Thank you for opening this!

Gatsby's output (`public` after a `gatsby build` can be hosted on any CDN or "traditional hosting" server). Please refer to the documentation of e.g. Plesk or Netlify if you have specific questions about these technologies. Providers like Netlify make it easier though to host your site as they handle everything for you.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by expatguideturkey** [comment]
> Ah i see. You still upload the raw file.
> Try to run gatsby build in your local machine.
> then see the /public directory. You should upload all files in /public into your hosting .
> For example, I upload  the build version into branch gh-pages in my repo
> https://github.com/idindrakusuma/me/tree/gh-pages

Hi @idindrakusuma I uploaded all my public files to root directory but the site is not showing anything: http://testsite.expatguideturkey.com/ can you please advise what I am doing wrong?

![image](https://user-images.githubusercontent.com/59199468/75609191-8ca1a280-5b17-11ea-844d-8d7ef6aae4c6.png)
