### ISSUE TITLE
Generate _redirects file automatically

### ISSUE THREAD

**Issue by mostafachatillon** [gatsbyjs/gatsby#21704]
Hi, I have 2 Gatsby websites on Netlify (one for landing page, one for blog) under 1 domain. I serve the blog through the main website (mywebsite.com/blog), and I serve the landing page through a proxy 200 redirect (mywebsite.com).

But in order to serve images in the landing page, I have to write the _redirects file manually. My landing page is very simple (still ~20 redirects written manually), but it would be convenient to be able to generate the _redirects file automatically each time.

(and for speed, using a _redirects file is recommended)

Related issues: 
https://github.com/gatsbyjs/gatsby/issues/21525
https://github.com/gatsbyjs/gatsby/issues/21496

**Comment by LekoArts** [comment]
Thank you for opening this!

You can use `gatsby-plugin-netlify` and its `createRedirect` function to (programmatically) create redirects: https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/#redirects

This is the best way to not manually write that file.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
