### ISSUE TITLE
Add documentation on Storybook.js in Gatsby

### ISSUE THREAD

**Issue by bball07** [gatsbyjs/gatsby#21702]
## Summary

Add documentation on using [Storybook.js](https://storybook.js.org/docs/basics/introduction/) + Gatsby 

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by LekoArts** [comment]
I think we already have that? :)
https://www.gatsbyjs.org/docs/visual-testing-with-storybook/
