### ISSUE TITLE
enhancement(docs): Increase discoverability in docs navigation

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21716]
## Summary

Increase discoverability and site performance by splitting up the docs sidebar into multiple sections.

## Detailed Description

Gatsby's documentation navigation is pretty darn big -- with more than 300 files in it and 5 layers deep[citation needed]. This negatively affects the docs in two ways:

1. It reduces discoverability of the docs, and makes it harder for people to find the documentation they want. Personally, I rarely ever use the navigation to find documentation, preferring to use search instead. I didn't realize certain sections like the Conceptual Guide existed because they're pushed down below the fold in the sidebar.
2. It affects site performance. `doc-links.yaml` is 6.4kb gzipped, and it needs to be loaded for every documentation page, even if all the sections are closed.

## Proposed solution

My main thought for doing this is by splitting the different sections up. Each section of the docs has its [own personality](https://www.gatsbyjs.org/contributing/docs-templates/#other-types-of-guide-articles) and aren't really part of the same "flow" as the other sections.

One way to do this is to do something like [MDN](https://developer.mozilla.org/en-US/) or [Vue](https://vuejs.org) and have the "Docs" tab in the navigation be a dropdown with the core sections:

<img width="300" alt="MDN section dropdown" src="https://user-images.githubusercontent.com/1278991/75206579-9d26d700-572b-11ea-9af0-b50836a8f944.png">

<img width="278" alt="Vuejs.org section dropdown" src="https://user-images.githubusercontent.com/1278991/75207300-2c80ba00-572d-11ea-9634-a4a72fb6d038.png">

In addition to "splitting up" different doc sections, it means we can make really useful pages, like the cheat sheet and CLI commands, accessible from the front-page.

The sidebar for each section would then only need the items for that section, instead of every section of the docs:

<img width="278" alt="MDN section sidebar" src="https://user-images.githubusercontent.com/1278991/75206816-18888880-572c-11ea-8694-c0fd6e1d85e2.png"> <img width="310" alt="Vuejs.org sidebar" src="https://user-images.githubusercontent.com/1278991/75207442-94cf9b80-572d-11ea-906f-0c0230b43c80.png">

An alternative UI would be to have a secondary sidebar, like we currently do for the [Design Guidelines](https://www.gatsbyjs.org/guidelines/logo/) section:

<img width="1280" alt="Gatsbyjs.org Guidelines page, screenshot" src="https://user-images.githubusercontent.com/1278991/75207412-7c5f8100-572d-11ea-9438-089f1c9420a0.png">

**Comment by tesseralis** [comment]
Additional thoughts: Splitting up the sections would give us much more space to refine the content of the docs. For example, we could add scroll-sync to [Recipes](https://gatsbyjs.org/docs/recipes) much like we do our [Tutorials](https://www.gatsbyjs.org/tutorial/part-zero/#familiarize-yourself-with-the-command-line). Instead of having just "Plugins" and "Showcase", we could put the [Ecosystem page](https://gatsbyjs.org/ecosystem) as the top level nav and have "Plugins", "Themes", "Starters", "Showcase" be in the dropdown.

**Comment by Usamaliaquat123** [comment]
+1
