### ISSUE TITLE
chore(docs): Files missing links in sidebar nav

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21712]
The files below are stubs with little-to-no content:

* /docs/add-a-service-worker/
* /docs/building-a-blog/
* /docs/building-a-portfolio/
* /docs/building-an-image-heavy-site/
* /docs/coming-from-react-to-gatsby/
* /docs/creating-global-styles/
* /docs/glamor/
* /docs/interactive-pages/
* /docs/overview/
* /docs/thinking-in-gatsby/
* /docs/preparing-for-site-launch/

1. tagged with an issue and added to the sidebar nav if we still intend to write them
2. deleted if we don't want them or if their content is repeated in other documents

The following files are **not** stubs:

* /docs/upgrading-node-js/

These all have a fair amount of content. ~~Most are sourcing guides and are referenced in headless-cms.md.~~ These files should probably be added to the sidebar nav.

**Comment by gillkyle** [comment]
In response to the headless CMS guides, we haven't added all guides to the Headless CMS section to keep that section from exploding in size (was what I think the reasoning was).

The comments in the doc-links file have a little note about it: https://github.com/gatsbyjs/gatsby/blob/0fc12e4cfcee92985f681716cc7d76dc684abe6c/www/src/data/sidebars/doc-links.yaml#L181-L183

**Comment by tesseralis** [comment]
@gillkyle Thanks for the clarification! I'll remove them from the list for now.
