### ISSUE TITLE
Hot Reloading broken by wrapPageElement

### ISSUE THREAD

**Issue by ovsw** [gatsbyjs/gatsby#21729]
## Description

Hot reload stops working for any part of the component used to wrap the page. Continues to work for any children components (the pages themselves).

### Steps to reproduce

1. clean minimal install of gatsby latest version eg: from `gatsby-starter-hello-world`
2. install `gatsby-plugin-layout` and add it to `gatsby-config.js` plugins array.
3. create a minimal layout component at `./src/layouts/index.js`
4. `npm run develop`
5. edit anything in the `./src/layouts/index.js` component while development server is running
6. open `http://localhost:8000/`

### Expected result

1. What should happen: the developlment server page at `http://localhost:8000/` should update via hot-reload,
2. the console should read:
```
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 318ms
process-update.js:51 [HMR] Checking for updates on the server...
process-update.js:125 [HMR] Updated modules:
process-update.js:127 [HMR]  - ./src/layouts/index.js
process-update.js:127 [HMR]  - ./.cache/sync-requires.js
process-update.js:132 [HMR] App is up to date.
```

### Actual result

1. the page does a complete refresh instead of hot-reloading.
2. the console gets to:
```
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 318ms
process-update.js:51 [HMR] Checking for updates on the server...
```
at which point the page fully refreshes, **no hot-reload is performed**.

**Conversly, editing anything in `./src/pages/index.js` causes a perfect hot-reload.**

This is **not** tied to `gatsby-plugin-layout` specifically. Uninstalling it and manually doing something like:
```
// gatsby-browser.js
import React from 'react'
import Layout from './src/containers/layout'

const wrapPageElement = ({element, props}) => {
  return <Layout {...props}>{element}</Layout>
}

export {wrapPageElement}
```
yields exactly the same behavior (full refresh instead of hot-reload when editing anything aside from the children of the `Layout` element. 

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```
  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor            
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.21 => 2.19.21 
    gatsby-plugin-layout: ^1.1.22 => 1.1.22 
```

**Comment by LekoArts** [comment]
There's an open PR for this. If you want you can help with getting it in:
https://github.com/gatsbyjs/gatsby/pull/19056

**Comment by ovsw** [comment]
thanks! unfortunately I'm no position to help, though I'd like to.
used the workaround:
```
// ./src/layouts/index.js
import React from 'react'
import {hot} from 'react-hot-loader/root'

const Layout = (props) => {... whatever ..}

export default hot(Layout)
```

note that importing from `react-hot-loader` threw an error, while importing from `react-hot-loader/root` worked.
