### ISSUE TITLE
gatsby-cli: Better handling of colored output

### ISSUE THREAD

**Issue by r1b** [gatsbyjs/gatsby#2172]
I have a light terminal theme and frequently I cannot read the stack traces `gatsby build` outputs. I would like to see the following:

* `--no-color` option to disable colored output
* Detect when redirecting to a file and disable colored output in this case

**Comment by benjaminhoffman** [comment]
closing in favor of https://github.com/gatsbyjs/gatsby/issues/2645

**Comment by tmccombs** [comment]
Why was this closed in favor of #2645? That fixes the problem of  light terminal backgrounds, but doesn't solve other use cases such as CI tools that can't handle ANSI color codes, or other  if you want to redirect the output to a file (or pipe to another program) that can't handle color codes.
