### ISSUE TITLE
CLI docs: link to "starters" leads to 404 on npm and GitHub

### ISSUE THREAD

**Issue by kaelig** [gatsbyjs/gatsby#21720]
In the CLI docs, in this sentence:

>You can also use the package.json script variant of these commands, typically exposed for you with most **starters**.

The link on the word "starters" leads to a 404.

* From GitHub: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-cli.md has a link pointing to 
https://github.com/gatsbyjs/gatsby/blob/master/docs/starters
* From npm: https://www.npmjs.com/package/gatsby-cli has a link pointing to https://github.com/gatsbyjs/gatsby/blob/HEAD/docs/starters/

(I was going to propose a fix but wasn't sure what the best way to go about it would be, thank you for your understanding!)

**Comment by herecydev** [comment]
I think the docs/gatsby-cli.md is fine, there are relative links as this is intended to be hosted (i.e: https://www.gatsbyjs.org/docs/gatsby-cli/).

But I can see some issues using relative links for the README.
