### ISSUE TITLE
maintenance(www): Add more test coverage to dot-org

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21739]
## Description

Recently, we've had a couple of dot-org build failures (mostly due to my i18n work/refactoring): #21559 #21356 #21101 #21358

A lot of these regressions could be prevented if we had better test coverage of components and pages in www -- including integration tests to make sure that the whole pathway from queries to display works as expected. Critical paths include places we've had regressions in the past -- stuff labelled with "fix(www)"

**Comment by nshaphan** [comment]
Can I try this one as my first contribution to gatsby?

**Comment by tesseralis** [comment]
@nshaphan yes of course! I'll try to get a more concrete list of components and files that should be tested. Until then, see if you can look at the PRs I mentioned and make tests for those.

Thanks!

**Comment by nshaphan** [comment]
Thanks @tesseralis, I'm going to look at the mentioned PRs. However, the concrete list of files that should be tested will help a lot!

**Comment by nshaphan** [comment]
@tesseralis were you able to find a list of components that need to be tested? also, take look at my pull request, I need your feedback!

**Comment by tesseralis** [comment]
@nshaphan Thanks! Aside from these files, I think the next biggest thing that we could use tests for is the sidebar. It's definitely the biggest and most intricate of all our components, and we're probably about to do some feature changes on it. Do you think you could take a look at it and see what functionality needs to be tested? If you write some tests, could you put it in a different PR than the one you already have?

**Comment by nshaphan** [comment]
I will look into that too @tesseralis what do think about the testing approach? can I continue like that?
