### ISSUE TITLE
Unknown argument \"formatString\" on field \"date\" of type \"frontmatter_2\".

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#2173]
Since upgrading from Gatsby v1.9.33 to v1.9.39, I get the error message showcased in the issue title when running a query similar to the [gatsby-plugin-remark usage example](https://github.com/gatsbyjs/gatsby/blob/01d06c1a7a04f855f66e97f042cd89d51182cbb0/examples/using-remark/src/templates/template-blog-post.js#L127-L162):

```
allMarkdownRemark {
  edges {
    node {
      frontmatter {
        date(formatString: "YYYY-MM-DD")
      }
    }
  }
}
```

I'm not sure about the cause, but found an issue which might be related to the problem: #2096

**Comment by KyleAMathews** [comment]
The problem is your date field isn't being inferred as a "date".

I'd look at your posts to see if some of the fields aren't valid. These are the supported formats https://github.com/gatsbyjs/gatsby/blob/7945bc569687d54b1bb761f4615b694fb65681fe/packages/gatsby/src/schema/infer-graphql-type.js#L45

**Comment by kripod** [comment]
My date formats were correct, but it turns out that dates now have to be put inside quotes, so

- `date: 2000-01-01` doesn't work
- `date: "2000-01-01"` works

**Comment by kripod** [comment]
After a bit of thinking, I'm not sure about when quotes should be used inside a front matter. According to the [Jekyll Front Matter docs](https://jekyllrb.com/docs/frontmatter), quotes should not be necessary.

**Comment by KyleAMathews** [comment]
They're not. Thanks easiest way for me to help you would be if you could build me a site reproducing the problem like Joseph did here https://github.com/gatsbyjs/gatsby/issues/2096#issuecomment-329984651

**Comment by kripod** [comment]
Clone [this repository at 865a0ad75214e85304edbf72906abde6b3a1d040](https://github.com/simonyiszk/mvk-web/tree/865a0ad75214e85304edbf72906abde6b3a1d040) and then run `yarn upgrade-interactive`, selecting everything related to Gatsby. I've put all the dates inside quotes in my next commit.

**Comment by KyleAMathews** [comment]
Thanks for the reproduction! Problem was I didn't actually fix the issue in my last PR… I used Date.toString instead of Date.toJSON which meant that the serialized dates weren't recognizable as dates later when inferring the GraphQL schema!

New PR is up fixing this, thanks again for testing! Also nice looking site :-)

**Comment by rchrdnsh** [comment]
I'm running into this now, not sure what to change, tho.

**Comment by rchrdnsh** [comment]
oh, i get it now...I have to put a `0` before a date that does not have two digits, like the first 9 days of a month...that's a bit annoying... :-/

**Comment by discordianfish** [comment]
@KyleAMathews It would be so, so useful if the error returned which document it happened on.

**Comment by chancesmith** [comment]
Agreed! What post do I need to fix?
