### ISSUE TITLE
Self hosting font files not working

### ISSUE THREAD

**Issue by pedrolopes101** [gatsbyjs/gatsby#21732]
Hello I'm trying to load a font i found online into my app but It doesn't ever seem to get imported.
I followed the following guide: https://alligator.io/gatsbyjs/custom-fonts-in-gatsby/#typefaces.js
I also read the following issue page: https://github.com/gatsbyjs/gatsby/issues/2583
But I can't seem to figure out what im doing wrong.
I created my fonts folder 
![image](https://user-images.githubusercontent.com/45852886/75257471-50073b80-57e5-11ea-9e1e-060b6f3bc8de.png)
And added the following code to my fonts css:
![image](https://user-images.githubusercontent.com/45852886/75257529-64e3cf00-57e5-11ea-8557-fab017e5c6f5.png)
After that I imported the folder in my gatsby-config.js like following
![image](https://user-images.githubusercontent.com/45852886/75257620-85138e00-57e5-11ea-8290-ac170b3fa195.png)
But I still dont see the font being loaded in the network tab in the browser and I also my font stays the default one when I try to call the font in component css like:
![image](https://user-images.githubusercontent.com/45852886/75257766-bab87700-57e5-11ea-91e4-7f10c2f76a37.png)
Do I need to import the font in my component aswell for this to work?

**Comment by pedrolopes101** [comment]
Also when I go look in my sources folder structure in browser It seems like the fonts folder is missing
![image](https://user-images.githubusercontent.com/45852886/75258044-31ee0b00-57e6-11ea-9b35-f7c747857d0f.png)

**Comment by LekoArts** [comment]
Thank you for opening this!

The guide you linked over-complicates things a bit. I'd recommend following this short recipe: https://www.gatsbyjs.org/docs/recipes/styling-css/#using-google-fonts

You add the npm package, import it into your layout component (or components that wraps every page / component that should have the fonts) and use it like normal in CSS. This way you don't have to have a `fonts` folder and `@font-face` declarations.

**Comment by pedrolopes101** [comment]
Hello Leko,
the problem is that the font I want to use is not on google-fonts. 
I think I found what I had to do though. It seems that I have to import the fonts.css in my component to use it if I want to only use it on a single component.
Or I can change my default font in my layout.module.scss without having to import anything and that fixes my issue since then it gets inherited globally. I appreciate the help though :)

**Comment by tynsoltys** [comment]
I'm also having an impossible time trying to import custom fonts right now. I've tried everything posted online and a few of my own workarounds, and while I can get the font loading in development mode, it will NOT load when built and served.

**Comment by pedrolopes101** [comment]
@tynsoltys I havent deployed my application yet so I will have to see. Will see if I deploy it this week. Will update this post if I also face the same issue.
