### ISSUE TITLE
bug(docs): Strange formatting in docs/caching

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21738]
## Summary

The page [docs/caching](http://gatsbyjs.org/docs/caching) is the only page in the docs that uses footnotes and it's implemented in a non-optimal way:

1. The footnotes labelled <sup>1</sup> are unlinked, meaning the user has to scroll up and down to get the information.
2. The footnotes <sup>[2][3]</sup> don't refer to anything in the main text but instead are supposed to clarify footnote <sup>1</sup> -- but it doesn't work because embedded markdown doesn't work in MDX.
3. The tone of the footnotes seems... off, but I can't really place my finger on it. I don't think it gives information to the reader clearly. 

## Solutions

A few ways we could solve this.

1. Use something like [Markdown footnotes](https://www.markdownguide.org/extended-syntax/#footnotes)
2. (preferred option) restructure the content in this document to use components common to other Gatsby docs. For example, instead of a footnote, we could use a quote block and make it a "Note".

**Comment by b4skyx** [comment]
Can I try this one as my first issue? I already made a pr I guess.
