### ISSUE TITLE
chore(www) Update nested markdown when prettier is upgraded to 1.19.2/1.20.0

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21743]
### Summary

PR #21671 switches us to use Prettier's MDX parser. Which mostly works, but it behaves weirdly when pages have nested files, as in the following cases:

* [hard wraps prose](https://github.com/gatsbyjs/gatsby/pull/21671/files#diff-9385004e658c12d7f967e8aca335d0f0R22)
* [fails without prettier-ignore](https://github.com/gatsbyjs/gatsby/pull/21671/files#diff-cf453622f51379319be07004140645d2R21)
* [requires Link instead of markdown links](https://github.com/gatsbyjs/gatsby/pull/21671/files#diff-e21bfa92aee63109eeaddf7042a101e2R44)
* [fails footnotes](https://github.com/gatsbyjs/gatsby/pull/21671/files#diff-8dd590c3413ff595840a9136c12dd834R54)

The primary issue is that prettier fails when parsing nested markdown in MDX, which will be fixed soon: https://github.com/prettier/prettier/issues/7041

**Comment by pvdz** [comment]
Any chance you could do a perf test for a large site? I don't think we have a benchmark site for mdx, but perhaps we should. Maybe we can modify one of the markdown benchmarks we already have...?
