### ISSUE TITLE
feat(www): /languages page of dot-org

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21750]
## Summary

A top-level `/languages` page of gatsbyjs.org that lists all available languages.

## Design

<img width="1024" alt="Languages" src="https://user-images.githubusercontent.com/21834/65888511-f0287800-e39f-11e9-803e-0438471ca693.png">

## Specs

* Lists all languages that are built on the site (as determined by the `LOCALES` env variable and accessed through `utils/i18n.js`)
* Displays each language's localized and native name.
* Has an external link to the language repo.
* _Displays current translation progress_ (depends on: #21104)

**Comment by wouterraateland** [comment]
I'd like to tackle this issue as a first contribution.
This would also depend on #21746 , correct?

**Comment by tesseralis** [comment]
@wouterraateland sure! It sort of depends on #21746... For now, you can just make the /languages page and not link to it just yet.

**Comment by fk** [comment]
Just posted an adjusted design in #21882: https://github.com/gatsbyjs/gatsby/pull/21882#issuecomment-610042355
