### ISSUE TITLE
how to redirect to a path when the url doesn't match the route created by createPage. 

### ISSUE THREAD

**Issue by evershy** [gatsbyjs/gatsby#21759]
https://github.com/gatsbyjs/gatsby/tree/master/examples/recipe-createPage

## Summary

after the command below,  

```js
npm run  build

npm run serve
```
if I change the url http://localhost:8000/Fido to http://localhost:8000/aaa, the browser displays Error: ENOENT..... How can I redirect http://localhost:8000/aaa to http://localhost:8000/Fido or any known item in the dogData.

### File contents

`gatsby-node.js`: 

```
exports.createPages = ({ actions }) => {
  const { createPage } = actions

  const dogData = [
    {
      name: `Fido`,
      breed: `Sheltie`,
    },
    {
      name: `Sparky`,
      breed: `Corgi`,
    },
  ]
  dogData.forEach(dog => {
    createPage({
      path: `/${dog.name}`,
      component: require.resolve(`./src/templates/dog-template.js`),
      context: { dog },
    })
  })
}
```

**Comment by vladar** [comment]
The example you posted is the most basic one. You may want to add [404 page](https://www.gatsbyjs.org/docs/add-404-page/) and handle non-existing routes as you need.

Also, you can use [`createRedirect`](https://www.gatsbyjs.org/docs/actions/#createRedirect) action for a specific redirect routes. There is an [example](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redirects) project for its usage.

**Comment by evershy** [comment]
> 
> 
> The example you posted is the most basic one. You may want to add [404 page](https://www.gatsbyjs.org/docs/add-404-page/) and handle non-existing routes as you need.
> 
> Also, you can use [`createRedirect`](https://www.gatsbyjs.org/docs/actions/#createRedirect) action for a specific redirect routes. There is an [example](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redirects) project for its usage.

> Thanks anyway. how can I redirect  /aaa or /bbb which is not the item of dogData to /Fido, the first item, instead of displaying the 404 page.  createRedirect seems only works when redirecting a known path to a specified route.

**Comment by vladar** [comment]
Usually, redirects like this are implemented in your hosting provider settings.

Doing this client-side in Gatsby is possible via a custom 404 page and a [`navigate`](https://www.gatsbyjs.org/docs/gatsby-link/#how-to-use-the-navigate-helper-function) function. Any missing route will land there and then you can redirect from there anywhere you want.

Try doing something like this in your custom 404 page:

```js
// pages/404.js
import { useEffect } from 'react';
import { navigate } from 'gatsby';

export default () => {
  useEffect(() => {
    navigate('/Fido');
  }, []);
  return null;
};
```

**Comment by evershy** [comment]
> 
> 
> Usually, redirects like this are implemented in your hosting provider settings.
> 
> Doing this client-side in Gatsby is possible via a custom 404 page and a [`navigate`](https://www.gatsbyjs.org/docs/gatsby-link/#how-to-use-the-navigate-helper-function) function. Any missing route will land there and then you can redirect from there anywhere you want.
> 
> Try doing something like this in your custom 404 page:
> 
> ```js
> // pages/404.js
> import { useEffect } from 'react';
> import { navigate } from 'gatsby';
> 
> export default () => {
>   useEffect(() => {
>     navigate('/Fido');
>   }, []);
>   return null;
> };
> ```

Thank you. It works!

**Comment by vladar** [comment]
Thank you for opening this, @evershy 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
