### ISSUE TITLE
`Conflicting Fields` message should say where the node was created.

### ISSUE THREAD

**Issue by GKJCJG** [gatsbyjs/gatsby#21779]
## Summary

The current warning when conflicting fields are detected specifies the type of node that generated the error, but not the plugin. This was confusing in a case where I didn't believe any of my plugins could create a type with that name.

### Motivation

This would make debugging somewhat easier, and very likely cost little in terms of additional complexity or run time.

I got this error while working on a custom plugin:

```
warn There are conflicting field types in your data.

If you have explicitly defined a type for those fields, you can safely ignore this warning message.
Otherwise, Gatsby will omit those fields from the GraphQL schema.

If you know all field types in advance, the best strategy is to explicitly define them with the `createTypes` action, and skip inference with the `@dontInfer` directive.
See https://www.gatsbyjs.org/docs/actions/#createTypes
GQLType.<field with conflicting types>:
 - type: [string,object]
   value: [ './...a string', { ...an object } ]
```
Figuring out what was going wrong took a bit of work because I wasn't sure which plugin was handling the file that had the data with conflicting fields. It would be great to say something like 'A node generated by `<plugin here>` has generated a node with conflicting field types...'

**Comment by pieh** [comment]
/cc @vladar 

I'm not sure if we are able to now (at least not in all cases). If the conflict doesn't happen on root fields of node type, we don't have information about this I think (unless type composer track this as well)

But this is good idea @GKJCJG  (if it's feasible to implement)

**Comment by vladar** [comment]
@GKJCJG thank you for the suggestion, it makes total sense! 💜

We have a similar report here: #22016 which already has a bit more actionable context. So let's track this feature request there.
