### ISSUE TITLE
(www) Configure docsearch to value docs > blog

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21783]
## Summary

Configure gatsbyjs.org's searching algorithm to value documentation over blog posts.

### Motivation

I was trying to look up "Contentful" in the search bar for docs on sourcing from contentful, but the search bar just gave me a list of blog posts about it.

<img width="1280" alt="Screen Shot 2020-02-26 at 3 31 22 PM" src="https://user-images.githubusercontent.com/1278991/75398016-582aae00-58ad-11ea-8f75-3d602805aa0b.png">

This is an egregious example, but it's not the first time it's happened. Usually I try to click on the first link for "graphql api" or "gatsby node" and I click on the first link expecting to be taken to the recipes or reference guides, but it takes me to a blog page instead, which means I have to go and search for it again...

**Comment by saadpasta** [comment]
In my case, it is valuing documentation over blog posts. It might be something else another than searching algorithm I guess.

![](https://user-images.githubusercontent.com/23307811/75602817-48e47400-5aea-11ea-998c-1257f3b456af.png)

**Comment by tesseralis** [comment]
@saadpasta right, it's doing that for me too sometimes. The problem is that it _switches_ and is inconsistent—you type in one thing and expect that the first link is a doc but get taken to a blog, and vice versa.

**Comment by LekoArts** [comment]
Since `www` isn't public anymore I've noted this internally as a ticket.
