### ISSUE TITLE
Creators Showcase showing all sites on all creators

### ISSUE THREAD

**Issue by coreyward** [gatsbyjs/gatsby#21788]
The Creators showcase pages, like [mine here](https://www.gatsbyjs.org/creators/people/corey-ward), are showing what appear to be all sites in the Showcase under each Creator:

![Kapture 2020-02-26 at 22 00 47](https://user-images.githubusercontent.com/81224/75411048-84612180-58e3-11ea-8d42-1a54361c8cc0.gif) 

As busy as I feel like I've been over the last couple years, I this is a _bit_ much. 😅

**Comment by pieh** [comment]
I checked the link and I don't see same result 
![Screenshot 2020-02-27 at 15 17 42](https://user-images.githubusercontent.com/419821/75453595-6c85ae00-5974-11ea-8e60-07cf9f33c0b5.png)

I checked this on Chrome, Firefox and Safari on mac os, but if you use any other browser please let me know so I could try to reproduce.

There is also option of weird desync of service worker - is there any errors in console showing up?

**Comment by coreyward** [comment]
Hey @pieh, I'm using Chrome 80. I'm not able to reproduce this morning. Last night it seemed a bit intermittent; like the first time I visit a profile it would have the bug, then subsequent visits were mostly okay. Might be related to service workers, but I don't see any errors related to the service worker in the console right now, and I didn't check yesterday.
