### ISSUE TITLE
Cannot use PostCSS plugins via gatsby-node.js

### ISSUE THREAD

**Issue by kylegach** [gatsbyjs/gatsby#218]
I’m trying to use `postcss-cssnext` in my project. To do so, I used the [Lumen config](https://github.com/hb-gatsby/gatsby-starter-lumen/blob/master/gatsby.config.js) as a reference, per [this comment on #196](https://github.com/gatsbyjs/gatsby/issues/196#issuecomment-198923408). Here’s my gatsby-node.js:

```
import cssnext from 'postcss-cssnext'
import postcssReporter from 'postcss-reporter'
import ExtractTextPlugin from 'extract-text-webpack-plugin'
import stylelintPlugin from 'stylelint-webpack-plugin'

exports.modifyWebpackConfig = function(config, env) {

  var is_static = env === 'static';
  var is_develop = env === 'develop';
  var is_production = env === 'production';

  config.removeLoader('css');

  if (is_develop) {
    config.loader('css', function(cfg) {
      cfg.test = /\.css/;
      cfg.loaders = ['style', 'css', 'postcss', 'stylelint'];
      return cfg
    })
  } else {
    config.loader('css', function(cfg) {
      cfg.test = /\.css/;
      cfg.loader = ExtractTextPlugin.extract(['css', 'postcss']);
      return cfg
    })
  }

  config.merge({
    postcss: [
      cssnext
      // postcssReporter
    ]
  });

  config.plugin('extract-css',
    ExtractTextPlugin,
    ['styles.css']
  );

  // config.plugin('stylelint'
  //   stylelintPlugin()
  // );

  return config;
}
```

_Ideally, I want to run `stylelint` in addition to `cssnext`, which is why those comments are there. I get the same error regardless of those lines being commented-out, not commented-out, or removed entirely._

But when running `gatsby develop`, I get this error:

> ERROR in /usr/local/lib/~/gatsby/~/css-loader!./~/postcss/lib/postcss.js!./styles/global.css
> Module build failed: Error: :root {
>   --textColor: rebeccapurple;
> }
> 
> body {
>   color: var(--textColor);
> }
> 
> h1 {
>   display: flex;
> }
>  is not a PostCSS plugin

_The styles themselves are not important, they're just a temporary means to test whether cssnext is transforming correctly._

I had this working in webpack directly in a previous project, but I'm not sure how to correctly translate that configuration to the gatsby config abstraction. Any help please?

Thanks!

**Comment by KyleAMathews** [comment]
Gah so sorry — the README is for the new version of Gatsby that I'll hopefully get released tonight. I made a bunch of changes Saturday but didn't quite get it pushed out the door. I [added a note to the README](https://github.com/gatsbyjs/gatsby#the-readme-has-updates-for-the-not-quite-yet-released-version-09-go-here-to-read-documentation-for-the-current-version-0811-on-npm) to the version of the docs for the current version on NPM.

This will be easier to manage once docs are on a proper website.

**Comment by kylegach** [comment]
I changed the file name to gatsby.config.js and changed `exports.modifyWebpackConfig = function(config, env) {` to `module.exports = function(config, env) {` (the only changes I could see between the current version and 0.9), but I'm still getting errors. I'll just go back to how I had it before and wait for the update to go from there.

Thanks for Gatsby, btw. I've been trying on my own for a while to combine Webpack, React, React Router, and PostCSS w/CSSNext for a statically-generated (and optionally driven by React on the client) site. I never quite cracked it, and it looks like Gatsby is going to make it possible.

**Comment by KyleAMathews** [comment]
Looking a bit more at your config — you probably only want the stylelint during development right? Perhaps try moving it there?

Also cssnext is already in the default config so you don't need to add that — https://github.com/gatsbyjs/gatsby/blob/69be4f618ca8ec3abd3b905d7a690a83da8180ee/lib/utils/webpack.config.js#L250

**Comment by KyleAMathews** [comment]
(And glad Gatsby is working out well!)

**Comment by kylegach** [comment]
Thanks for sharing the default config. Turns out the only thing I need to add is stylelint. Which, yes, should only run during development.

**Comment by KyleAMathews** [comment]
:100:

**Comment by schoenwaldnils** [comment]
Maybe the wrong ticket, but is there a simple way to apply postcss-cssnext config into the postcss-plugin?

I tried config.merge but it didn't quite work.

`gatsby-node.js`
```
const webpackPostcssTools = require('webpack-postcss-tools');
const map = webpackPostcssTools.makeVarMap('./css/theme.css');

exports.modifyWebpackConfig = function(config, env) {
  config.merge({
    postcss (wp) {
      return [
        require('postcss-cssnext')({
          customProperties: {
            variables: map.vars,
          },
          customMedia: {
            extensions: map.media,
          },
          autoprefixer: {
            browsers: 'last 2 versions',
          }
        }),
      ]
    },
  })
  return config
};
```

**Comment by imjared** [comment]
@kylegach trying to follow along here a bit here

> Turns out the only thing I need to add is stylelint

Did you end up doing this in your `gatsby-node.js` as seen in your first comment or in `gatsby-config.js`?

Totally get that it's been a year+ so if you have no idea, that's cool too :)
