### ISSUE TITLE
Custom graphql schema

### ISSUE THREAD

**Issue by WilliamCSA04** [gatsbyjs/gatsby#21803]
## Summary
Hi, I'm having a hard time trying to use custom graphql schema. 

## Relevant information

I am getting data from Wordpress and sometimes happens that the data don't come for any reason, when this happens I receive the following message: `It is recommended to explicitly type your GraphQL schema if you want to use optional fields`. That is exactly what I'm trying to do, and it is working on basic cases where I use the gastby types like `Int` or `String`, but for nested attributes, I'm having a problem that the data just returns `null` on `source_url.`

If I do this code on `gatsby-node`:
```
    type wordpress__wp_galleriesAcf implements Node @infer {
      hidden: Boolean
    }
```
with this query:

```
  allWordpressWpGalleries {
    nodes {
      acf {
        images {
          image {
            source_url
          }
        }
      }
    }
  }
```
returns this:
```
"allWordpressWpGalleries": {
      "nodes": [
        {
          "acf": {
            "images": [
              {
                "image": { source_url: "http://mediaurl.com" }
              },
              {
                "image": { source_url: "http://mediaurl.com" }
              }
           ]
        }
     }
   ]
}
```

but if I add this:
```
    type wordpress__wp_galleriesAcf implements Node @infer {
      hidden: Boolean
      images: [Images]
    }
    type Images implements Node {
      image: Image
    }
    type Image implements Node {
      source_url: String
    }
```
The same query returns:
```
"allWordpressWpGalleries": {
      "nodes": [
        {
          "acf": {
            "images": [
              {
                "image": null
              },
              {
                "image": null
              }
           ]
        }
     }
   ]
}
```
I hope these informations are enough, I also have read [Gatsby schema custom page](https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions), I'm probably missing something. My Gatsby version is `2.15.16`. I want to know how to add this custom field without breaking everything.

Thank you.

**Comment by pieh** [comment]
Try this:
```
 type wordpress__wp_galleriesAcf implements Node @infer {
      hidden: Boolean
      images: [Images]
    }
    type Images {
      image: Image
    }
    type wordpress__wp_media implements Node {
      source_url: String
    }
```

(`Images` shouldn't be a Node I think and the `Image` should be  `wordpress__wp_media`)

but this is just guessing and hard to guess right.

You could also use https://www.gatsbyjs.org/packages/gatsby-plugin-schema-snapshot/ to generate schema snapshot once (you could just include `gatsby-source-wordpress` there). You might either continue using it or just pull snippet it generated in `schema.gql` file related to the galeries

**Comment by WilliamCSA04** [comment]
Oh, thank you, it did work, the only difference is that I changed your Image by wordpress__wp_media as you recommended.

For future reference, the final version is like this:

 ```
type wordpress__wp_galleriesAcf implements Node @infer {
      hidden: Boolean
      images: [Images]
    }
    type Images {
      image: wordpress__wp_media
    }
    type wordpress__wp_media implements Node {
      source_url: String
    }
```
