### ISSUE TITLE
Is gatsby-image compatible with Netlify?

### ISSUE THREAD

**Issue by TrevPennington** [gatsbyjs/gatsby#21802]
**Summary**
I've followed the gatsby-image guide which works great locally but fails at deployment. I've seen this issue tons of places but all of them seem to go unsolved. Should I just use regular img tags? 

## Relevant information

Here is some relevant code, let me know if anything else would help! 
Thank you. 

`import React from "react"
import { graphql } from "gatsby"
import Layout from "../components/layout" 
import RecentBlock from "../components/recentBlock"

export const data = graphql`
query {
  hero: file(relativePath: { eq: "demo/amanda-frank-tvw_dg4UYzU-unsplash.jpg" }) {
    childImageSharp {
      fluid(
        maxWidth: 1000
        quality: 100
      
        ) {
        ...GatsbyImageSharpFluid
      }
    }
  }

}`

export default ({ data }) => {
    return (
        <Layout 
          location={`recent`}
          image={data.hero.childImageSharp.fluid}
        >
            <RecentBlock />
        </Layout>
    )
}`

### File contents (if changed)

`gatsby-config.js`: `const path = require(`path`)

module.exports = {
  siteMetadata: {
    title: `The Pennington Co.`,
    description: `Raleigh, NC`,
    author: `Trevor Pennington`,
  },
  plugins: [

    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },

    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-styled-components`,
    // `gatsby-transformer-remark`,

    {
      resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 1500,
              withWebp: true,
              showCaptions: true,
              quality: 100,
              
            },
    },

    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `white`,
        theme_color: `white`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },

    {
      resolve: `gatsby-source-prismic-graphql`,
      options: {
        repositoryName: 'thePenningtonCo',
        pages: [{
          type: 'Post',          // Custom type of the document
          match: '/blog/:uid',   // Pages will be generated in this pattern
          path: '/blog-preview', // Placeholder route for previews
          component: require.resolve('./src/templates/post.js') // Template file
        }]
      }
    },
  ],
}
` 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
`gatsby-image` does work on Netlfiy - it works pretty much everywhere. What's the exact error you are seeing?

**Comment by TrevPennington** [comment]
Thanks for the reply and my apologies for the lack of info. This is my first issue post.

Upon build and serve, all images are blurred and I get 'failed to load resource' on all images in the console. Let me know if I can attach any code for you.

**Comment by pieh** [comment]
Can you link to netlify site (preview or production url)?

**Comment by TrevPennington** [comment]
https://quirky-ramanujan-5bef9e.netlify.com/

https://quirky-ramanujan-5bef9e.netlify.com/test/ this page has a test for a regular image

**Comment by pieh** [comment]
There is error in your `gatsby-browser` code, that prevent java script that handles image loading to run:
![Screenshot 2020-02-27 at 21 22 41](https://user-images.githubusercontent.com/419821/75483542-5a713300-59a7-11ea-915e-00f86e13de23.png)

**Comment by TrevPennington** [comment]
`const { registerLinkResolver } = require('gatsby-source-prismic-graphql');
const { linkResolver } = require('./src/utils/linkResolver');

registerLinkResolver(linkResolver);`

That is what is in my gatsby-browser file. I just tried deleting it all as I am not using it right now anyways. I rebuilt and nothing changed.

**Comment by pieh** [comment]
Ah my bad - this is in `gatsby-source-prismic-graphql` - it might be related to https://github.com/birkir/gatsby-source-prismic-graphql/issues/140

**Comment by TrevPennington** [comment]
Oh wow - it could be a prismic problem. I tried that npm install it mentioned but nothing still. I don't plan on using Prismic anymore so I could just get rid of it. My photos are stored locally just like in that thread. 

Would removing it from config be enough or should I do anything from the terminal as well?

**Comment by pieh** [comment]
Removing from `gatsby-config` should be enough, but you could also remove that package from `package.json` -> `dependencies` field and rerun `npm install` (or `yarn install` if you are using `yarn`)

**Comment by TrevPennington** [comment]
I npm uninstalled all prismic and removed all Prismic references and everything works now! 

Thanks so much for your help @pieh
