### ISSUE TITLE
feat(www) Table of contents for API reference pages

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#21808]
## Summary

API reference pages, such as [node-apis](https://www.gatsbyjs.org/docs/node-apis/) do not use our standard table of contents, instead using an inline component:

<img width="818" alt="API table of contents" src="https://user-images.githubusercontent.com/1278991/75500915-300d7e80-5983-11ea-985f-998a5b999298.png">

This is suboptimal, since it's stuck on the page content and we don't get the nice table of contents sidebar like we do in normal docs.

## Implementation

We'd need to change the [table of contents](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/docs-table-of-contents.js#L64) component to take in a generic list of items rather than a `page` objects. Once this is done, it should be fairly straightforward to add it to the [api template](https://github.com/gatsbyjs/gatsby/blob/master/www/src/templates/template-api-markdown.js).

## Related Issues

We may want to wait until #21762 to go in, since that also changes the table of contents component a fair bit.

**Comment by andresz1** [comment]
Hi! I'd like to contribute taking this one!

**Comment by andresz1** [comment]
Just opened a PR @wardpeet
