### ISSUE TITLE
How to put PageContext or SiteQuery data into preBodyComponents?

### ISSUE THREAD

**Issue by pr1ntr** [gatsbyjs/gatsby#21800]
## Summary

In my project, I need to add a <noscript> tag for a facebook pixel in the body. However the code that goes into this script is only available from the CMS which i have to query for. I can't find a way to inject anything with queried data right after the <body> tag.

## Relevant information

I have several of these. Also for google GTM. I can see that <Helmet> can do this but its has its own crazy way it does it. I just want to be able to inject stuff into preBodyComponents that has data from my cms.

**Comment by pieh** [comment]
You can use `react-helmet` in your layout component and put `<script>` tag there.

We use `react-helmet` in our starters mostly for `<title>` and `<meta>` tags, but `<script>` tag also supported ( https://github.com/nfl/react-helmet#reference-guide )
In the layout component you can use `StaticQuery` to grab the data from data store

**Comment by pr1ntr** [comment]
I need to put <noscript> into the body not in the head though.
