### ISSUE TITLE
Display a warning when some GraphQL query gets stuck

### ISSUE THREAD

**Issue by vladar** [gatsbyjs/gatsby#21825]
## Summary

There are situations when GraphQL queries run too long (due to cycles in data or very deep query structure). For example #21758

We should account for this and display a warning after 30 seconds of query running (the timeout value may change). This warning will mention the Component with a bad query.

We should also consider adding complexity scoring in the future which could warn users about possible problems during the query validation step.

**Comment by chuyenlee** [comment]
That's great.

**Comment by vladar** [comment]
This is actually done via #23261
