### ISSUE TITLE
[gatsby-plugin-mdx] Remark plugins are not required correctly

### ISSUE THREAD

**Issue by jlkiri** [gatsbyjs/gatsby#21821]
## Description

`gatsby-plugin-mdx` fails to require plugins that have default exports.

### Steps to reproduce

1. Clone a default `gatsby-plugin-mdx` starter project

```
gatsby new my-mdx-starter https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic
```

2. Include `gatsby-remark-shiki` as a plugin

```
{
      resolve: `gatsby-plugin-mdx`,
      options: {
        gatsbyRemarkPlugins: [{ resolve: `gatsby-remark-shiki` }],
        defaultLayouts: { default: path.resolve("./src/components/layout.js") }
      }
    },
```

3. Add some code to markdown files

4. Run `gatsby develop`

### Expected result

Code should be formatted by `gatsby-remark-shiki`

### Actual result

Code is not formatted. No errors occur.

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: 73.0.1
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.13.50 => 2.19.22
    gatsby-image: ^2.2.8 => 2.2.41
    gatsby-plugin-manifest: ^2.2.4 => 2.2.42
    gatsby-plugin-mdx: ^1.0.0 => 1.0.74
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.22
    gatsby-plugin-sharp: ^2.2.9 => 2.4.5
    gatsby-remark-prismjs: ^3.3.31 => 3.3.31
    gatsby-source-filesystem: ^2.1.8 => 2.1.48
    gatsby-transformer-sharp: ^2.2.5 => 2.3.16
  npmGlobalPackages:
    gatsby-dev-cli: 2.5.44
```

**Comment by jlkiri** [comment]
Supposedly, the reason the quoted line below. The result of a `require` is always an object. So there is literally no way it can be a `function`. Instead some interoperable require function should be used. I confirmed that it works. Example:

```
function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }
```

https://github.com/gatsbyjs/gatsby/blob/4bc595b5dc54ad8bdbbbc34220cc3c54f72db0a6/packages/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js#L46

**Comment by jlkiri** [comment]
It also MIGHT be the reason for other open bugs but I haven't checked yet.

**Comment by gpbl** [comment]
I believe this change is breaking other plugins, like `gatsby-remark-custom-blocks`.
