### ISSUE TITLE
query-runner crashes if error does not include locations[0].line

### ISSUE THREAD

**Issue by ricokahler** [gatsbyjs/gatsby#21838]
## Description

Describe the issue that you're seeing.

I'm getting the following error resulting from a Gatsby panic:

![image](https://user-images.githubusercontent.com/10551026/75577493-1118f600-5a30-11ea-9769-853e8cac5608.png)

It seems like my error does not include `e.locations`…

https://github.com/gatsbyjs/gatsby/blob/068ef1b422cd775dcbd0ea502d5ff6cb8b48a991/packages/gatsby/src/query/query-runner.js#L59-L63

…so as a result, gatsby CLI has an uncaught error and panics:

https://github.com/gatsbyjs/gatsby/blob/3e9bf0775886c29770ebaa5996e466cb2f92ff35/packages/gatsby-cli/src/index.ts#L49-L60

### Steps to reproduce

Let me know if you'd like me to setup a reproduction, however I think this issue is simple enough not to need one.

### Expected result

What should happen?

instead of `e.locations[0]`, you just need to include some optional chaining.

e.g.

```js
codeFrame: getCodeFrame( 
   queryJob.query, 
   e.locations[0].line, 
   e.locations[0].column 
 ), 
```

👇

```js
codeFrame: getCodeFrame( 
   queryJob.query, 
   e.locations?[0].line, 
   e.locations?[0].column 
 ), 
```

`getCodeFrame` already accepts those params as optional:

https://github.com/gatsbyjs/gatsby/blob/068ef1b422cd775dcbd0ea502d5ff6cb8b48a991/packages/gatsby/src/query/graphql-errors.js#L96

I'll create quick lil PR to make things easier.

Edit: [here you go](https://github.com/gatsbyjs/gatsby/pull/21839)

**Comment by vladar** [comment]
Can you share what error do you actually get there? I tried to reproduce this in the past but couldn't come up with a situation when such an error is thrown. It is quite possible that this has to be handled somewhere else. Maybe you can provide a [minimum repoduction](https://gatsby.dev/reproduction) for this?

**Comment by vladar** [comment]
Here is a similar bug report: #21730

**Comment by ricokahler** [comment]
@vladar okay i think I have a working repro: https://github.com/ricokahler/query-runner-thing

So this is occurring when using `gatsby-source-graphql`. The scenario I tried to mock (and the scenario I'm currently in) is:

- using gatsby-source-graphql with some external graphql server
- server has internal server error and returns an error similar to this one: https://github.com/ricokahler/query-runner-thing/blob/822963149796d5f09ed2b94d03cf916ab7a569cc/gatsby-config.js#L21-L33

I know ideally the server shouldn't error like this but in this case I would like Gatsby to tell me which file was causing the trouble to make it easier to debug.

Thanks for all your help!
