### ISSUE TITLE
gatsby-plugin-mdx doesn’t hot reload frontmatter

### ISSUE THREAD

**Issue by leafac** [gatsbyjs/gatsby#21837]
## Description

Hot reloading doesn’t work when I change the frontmatter in an `.mdx` file. I have to rerun `gatsby develop` to observe the changes.

### Steps to reproduce

Here’s a project that exemplifies the issue:

[gatsby-mdx-frontmatter-hot-reload.zip](https://github.com/gatsbyjs/gatsby/files/4268528/gatsby-mdx-frontmatter-hot-reload.zip)

Run:

```console
$ npm install
$ npx gatsby develop
```

Visit `http://localhost:8000`. Change the `title` in the frontmatter in `src/pages/index.mdx`. Observe how the contents in the browser don’t change, not even if you refresh the page. You have to restart Gatsby.

### Expected result

The frontmatter should hot reload, just like the contents of the page do.

### Actual result

The frontmatter doesn’t reload.

### Environment

<details>

```
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    npm: 6.14.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.122
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.23 => 2.19.23 
    gatsby-plugin-mdx: ^1.0.74 => 1.0.74 
    gatsby-source-filesystem: ^2.1.48 => 2.1.48 
```

</details>

**Comment by blainekasten** [comment]
Hey @leafac 

So sorry it's been 19 days with no response. I'm going to try and look into this soon. Our team is running in a limited capacity due to Covid-19 which is a bit to explain why it took so long. But I just wanted to drop a comment to let you know I'll be looking into this (ideally) this week.

**Comment by leafac** [comment]
Don’t worry about it. We all have bigger fish to fry.

**Comment by ConradSchmidt** [comment]
A quick workaround for me is to rename the mdx file to `page.mdx_`, then back to `page.mdx` and save the content again - at least its better than restarting the whole building process.

**Comment by colebemis** [comment]
Any updates on this?

**Comment by simplenotezy** [comment]
There should be a way to not have issues auto closed. This is still an issue.
