### ISSUE TITLE
How can gatsby-ssr.js access environment variables?

### ISSUE THREAD

**Issue by JonVisc** [gatsbyjs/gatsby#21844]
The basic premise is this

I want to add a `<meta name="robots" content="noindex, nofollow" />` tag to our development environment pages.  Yes we shouldn't have our dev environment exposed and all that stuff but sometimes the real world (clients / third-parties outside of the office / VPN want to see the work) bumps up against the ideal and being able to have the comfort of knowing at least bots will not list these pages if its there.

Ideally I was thinking I can do something like this:

**gatsby-ssr.js**
```javascript
const SiteUrl = process.env.SITE_URL || 'https://dev.example.com'
console.log(`--------------- Site URL is: ${SiteUrl} ---------------`)
const React = require('react')

export const onPreRenderHTML = ({ getHeadComponents, replaceHeadComponents }) => {
    let headComponents = getHeadComponents()
    //If the site isn't built on production then we are adding a noindex, nofollow to every page
    if (SiteUrl !== 'https://www.example.com') {
        headComponents.push(
            React.createElement('meta', {name: 'robots', content: 'noindex,nofollow'})
        )
    }
    replaceHeadComponents(headComponents)
}
```

But `console.log(SiteUrl)` will return `https://dev.example.com`

This is opposed to:
**gatsby-config.js**
```javascript
const SiteUrl = process.env.SITE_URL || 'https://dev.example.com'
console.log(`--------------- Site URL is: ${SiteUrl} ---------------`)
```
And `console.log(SiteUrl)` will return `https://www.example.com` as picked up from the env vars.

I know I can add the `options` variable onto this function:
```javascript
export const onPreRenderHTML = ({ getHeadComponents, replaceHeadComponents }, options) => {
console.log(options) //produces plugins:[]
...
}
```

But I am assuming it isn't intended to be used in that way?  I also know the documentation expressly calls out only `gatsby-config.js` and `gatsby-node.js` as having access to the env vars but what is preventing from `gatsby-ssr.js` from using them during the build as well?

There is probably something easy I am overlooking.

**Comment by herecydev** [comment]
If you haven't seen it already, [this should help](https://www.gatsbyjs.org/docs/environment-variables/#defining-environment-variables)

I believe that the `gatsby-ssr.js` and `gatsby-browser.js` are intentionally locked down to prevent env variables accidentally spilling into compiled pages, etc. So if you create a:

```
//.env.production
SITE_URL=https://foo.bar
```

It should then be available to consume in `gatsby-ssr.js`

**Comment by blainekasten** [comment]
@herecydev is spot on! That's exactly what I would suggest and his reasoning for why ssr/client runtime doesn't get process.env vars is right. Try putting the `SITE_URL` in the `.env.development` or `.env.production` files 

I'm going to close this issue as I don't believe it's reporting a problem with Gatsby. I'm happy to keep the discussion going, so don't take this as a negative sign. Please report back if you need continued support! 😃

**Comment by jonniebigodes** [comment]
@JonVisc recently i had to address a similar issue and i went with a more granular approach. Instead of using the ssr approach i went with a per page approach. Going to detail the steps i took to tackle this. The code i'm presenting is based off on the default starter for Gatsby.

- Created a new Gatsby site with the default starter.
- Changed `src\components\seo.js` to the following:

```js
/**
 * SEO component that queries for data with
 *  Gatsby's useStaticQuery React hook
 *
 * See: https://www.gatsbyjs.org/docs/use-static-query/
 */

import React from "react"
import PropTypes from "prop-types"
import Helmet from "react-helmet"
import { useStaticQuery, graphql } from "gatsby"

function SEO({ description, lang, meta, title, isDev }) {
  const { site } = useStaticQuery(
    graphql`
      query {
        site {
          siteMetadata {
            title
            description
            author
          }
        }
      }
    `
  )
  const metaDescription = description || site.siteMetadata.description
  return (
    <Helmet
      htmlAttributes={{
        lang,
      }}
      title={title}
      titleTemplate={`%s | ${site.siteMetadata.title}`}
      meta={[
        {
          name: `description`,
          content: metaDescription,
        },
        {
          property: `og:title`,
          content: title,
        },
        {
          property: `og:description`,
          content: metaDescription,
        },
        {
          property: `og:type`,
          content: `website`,
        },
        {
          name: `twitter:card`,
          content: `summary`,
        },
        {
          name: `twitter:creator`,
          content: site.siteMetadata.author,
        },
        {
          name: `twitter:title`,
          content: title,
        },
        {
          name: `twitter:description`,
          content: metaDescription,
        },
      ].concat(
        isDev
          ? {
              name: `robots`,
              content: "noindex,nofollow",
            }
          : meta
      )}
    />
  )
}

SEO.defaultProps = {
  lang: `en`,
  meta: [],
  description: ``,
}

SEO.propTypes = {
  description: PropTypes.string,
  lang: PropTypes.string,
  meta: PropTypes.arrayOf(PropTypes.object),
  title: PropTypes.string.isRequired,
}

export default SEO
```

- Changed `src\pages\page-2.js` to the following:

```js
import React from "react"
import { Link } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"

const SecondPage = () => (
  <Layout>
    <SEO title="Page two" isDev/>
    <h1>Hi from the second page</h1>
    <p>Welcome to page 2</p>
    <Link to="/">Go back to the homepage</Link>
  </Layout>
)

export default SecondPage
```
- Issued `yarn develop` and opened up `http://localhost:8000` and i'm presented with:

![jonhvisc_1](https://user-images.githubusercontent.com/22988955/75722978-45f8a780-5cd3-11ea-81f3-d602df99ce12.png)

And opening up `http://localhost:8000/page-2/` with the following:

![jonhvisc_2](https://user-images.githubusercontent.com/22988955/75723111-8f48f700-5cd3-11ea-9d05-2851e348e28c.png)

If you look the second page will have the meta tag added but not for the first one.

**Comment by theblang** [comment]
I was able to resolve the issue by following the instructions in [this section](https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/#server-side-nodejs) of the Gatsby docs, notably:

```
const activeEnv = process.env.GATSBY_ACTIVE_ENV || process.env.NODE_ENV || 'development';
dotenv.config({ path: `.env.${activeEnv}` });
```
After adding that my `gatsby-ssr.js` code was being rendered with my ENV variables. Note that they had to be prefixed with `GATSBY_`.
