### ISSUE TITLE
[docs][guides] New guide on porting from Hugo to Gatsby

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#21850]
As a Hugo user interested in migrating my site to Gatsby, I should find a section in the docs explaining how to do it. This new doc would live in the [Porting to Gatsby](https://www.gatsbyjs.org/docs/porting-to-gatsby/) section alongside the pages on Create React App and HTML.

This post from the Gatsby blog may be a good starting point: https://www.gatsbyjs.org/blog/2017-11-06-migrate-hugo-gatsby/

For a docs guide PR to be accepted, it needs to follow the Reference Guide format and Gatsby Style Guide:

- https://www.gatsbyjs.org/contributing/docs-templates/ 
- https://www.gatsbyjs.org/contributing/gatsby-style-guide/

**Comment by laneparton** [comment]
I'd like to give this a shot. It may take some time. I will open a PR when I have a solid draft next week for collaboration/feedback.

**Comment by marcysutton** [comment]
Sounds great, thanks @laneparton!
