### ISSUE TITLE
[www] update react-icons version to latest 3.x.x

### ISSUE THREAD

**Issue by akshitkrnagpal** [gatsbyjs/gatsby#21859]
### Update react-icons from 2.2.7 to 3.x.x (latest)

https://github.com/react-icons/react-icons#migrating-from-version-2---3

### Motivation

The latest version of `react-icons` has more icons than the current version we are using in `www`. After updating react-icons we won't need some custom icons we created as components.

### Related issues and PRs

#21661 - discord icon PR - #21820
#21847 - users icon (community icon) PR - #21847

**Comment by akshitkrnagpal** [comment]
@mohouyizme I assigned you since you already have a PR. Not sure why you closed it. Let me know if you don't want to do it. 😄

**Comment by mohouyizme** [comment]
@akshitkrnagpal I closed it by mistake lol
