### ISSUE TITLE
 The Starter Library category page is not displayed. 

### ISSUE THREAD

**Issue by kawamataryo** [gatsbyjs/gatsby#21867]
## Description

The Starter Library category page is not displayed. 

![Mar-01-2020 06-18-08 (1)](https://user-images.githubusercontent.com/11070996/75615294-46832800-5b85-11ea-87af-0532e99096d2.gif)

### Steps to reproduce

1. See Starters page 
https://www.gatsbyjs.org/starters?v=2

2. Click on any category list
(ex 
https://www.gatsbyjs.org/starters?c=CMS%3AContentful&v=2

### Expected result

Displayed category page.

### Actual result

Displayed white page, and show this errors in console.

```
react-dom.production.min.js:4684 TypeError: Cannot read property 'tags' of undefined
    at filtered-starters.js:280
    at Array.filter (<anonymous>)
    at filtered-starters.js:279
    at n.render (filtered-starters.js:93)
    at qi (react-dom.production.min.js:4289)
    at Ki (react-dom.production.min.js:4280)
    at So (react-dom.production.min.js:6722)
    at hu (react-dom.production.min.js:5696)
    at pu (react-dom.production.min.js:5685)
    at au (react-dom.production.min.js:5441)
```
### Environment

Mac OS Catalina 10.15.3 

Checked  browser.
- Safari 13.05
- Chrome 80.0.3987.122

**Comment by LesleyLai** [comment]
Same issue with showcase.

**Comment by Vincent440** [comment]
![image](https://user-images.githubusercontent.com/45357263/75615588-a5a85480-5b13-11ea-8e51-f47f0cf0efef.png)

Showcase page does not display after clicking any items in the search pane. This is the error I am getting

**Comment by kawamataryo** [comment]
I sent a pull request #21876.
