### ISSUE TITLE
Add a defintion of 'slug' to Part 7 tutorial

### ISSUE THREAD

**Issue by mokyox** [gatsbyjs/gatsby#21864]
### Refine the definition of “slug” in the Part 7 Tutorial

I think some extra information on what a ‘slug’ is could be a nice improvement given how often the term is used the tutorial. Users might not be 100% clear on what exactly ‘path’ is referring to.   

#### Current definition on https://www.gatsbyjs.org/tutorial/part-seven/
```
Creating slugs for pages 

Creating new pages has two steps:
1. Generate the “path” or “slug” for the page.
2. Create the page.
```
A possible suggestion:

```
Creating slugs for pages

A ‘slug’ is the unique identifying part of a web address, 
such as the `tutorial/part-seven` part of the page https://www.gatsbyjs.org/tutorial/part-seven/.

It is also referred to as the ‘path’ but we will use the term ‘slug’ during this tutorial.

 Creating new pages has two steps:
1. Generate the “path” or “slug” for the page.
2. Create the page.
```

### Motivation

Why should we document this and who will benefit from it?

Adding extra information to make the already __very__ beginner-friendly tutorial would be a good step in preventing people distracted by going to search for unfamiliar terms. I think the Gatsby tutorials already does a really good job of this, such as the explanation on GraphQL in Part 4. 

I'm happy to add further clarification or even admit this might not be necessary but I myself had to look up on what a `slug` meant after going through the tutorials. I'm hoping if there's others out there who also had to look up the term that maybe in the future this would prevent people from going to search for it and continue with the amazing tutorials! 😄 

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [x] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by pvdz** [comment]
Looking forward to your PR :) I'm sure @gatsbyjs/learning has some thoughts on this as well

**Comment by mokyox** [comment]
Thanks @pvdz! I was considering doing a PR but perhaps it might be better to wait for see what the @gatsbyjs/learning team thinks?

**Comment by laurieontech** [comment]
This certainly seems like an area we could expand on! I'd be open to a PR for this :)

**Comment by mokyox** [comment]
Thank you @laurieontech! I've created PR [here](https://github.com/gatsbyjs/gatsby/pull/21939). 😄
