### ISSUE TITLE
Static Site on IPFS

### ISSUE THREAD

**Issue by HTEredrock** [gatsbyjs/gatsby#2187]
Hi there,

I may be missing something obvious, but I can't seem to get the built static site (public folder) to have working links.

I have basically setup the default starter package, added two pages and used:

`<Link to="/page/">link text</Link>`

to link to the new pages from index.js. This works fine in Develop mode, but when I open Index.html locally once it's built, it gives me the 404 page.

My goal was to attempt to add the site to IPFS and experiment with a fully decentralized hosting setup, but that also does not seem to work. 

Publishing the same site to Surge works fine as well. I am very obviously missing something here as this is my first foray into static site generation, but I would gladly accept any help to point me in the right direction.

Thanks!

**Comment by HTEredrock** [comment]
Nevermind, I think I figured it out. I need to `--prefix-paths` when building the site to get the right path.

One other question though, locally, it doesn't seem to open the index.html of the generated page, only the folder. Am I missing something here? (Probably)

**Comment by satazor** [comment]
I've actually made a plugin to add support for IPFS relative paths, see. https://github.com/moxystudio/gatsby-plugin-ipfs
