### ISSUE TITLE
Opt-out of telemetry data should be changed to opt-in

### ISSUE THREAD

**Issue by vschwaberow** [gatsbyjs/gatsby#21878]
## Summary

The current practice of handing over telemetry data to the development community via an opt-out procedure is questionable in my view and violates data protection requirements. 

The procedure should therefore be changed to an opt-in procedure. 

### Basic example

gatsby telemetry --enable

### Motivation

Don't be evil and be compliant to European laws.

**Comment by ascorbic** [comment]
Hello. The telemetry feature does not collect any personally identifiable information. For more details of what it does collect, see [the telemetry documentation](https://www.gatsbyjs.org/docs/telemetry/)

**Comment by vschwaberow** [comment]
This is no personal information for you?

Gatsby machine ID. This is generated with UUID and stored in global gatsby config at ~/.config/gatsby/config.json.

Unique session ID. This is generated on each run with UUID.

You don't collect IP addresses?

**Comment by markuszeller** [comment]
Should be re-opened. Data is **not anonymized** and can be converted to back to personalized data.

Please ask for opt-in before collecting anything.
