### ISSUE TITLE
Example on proactively fetch updates

### ISSUE THREAD

**Issue by nojaf** [gatsbyjs/gatsby#21896]
## Summary

When reading https://www.gatsbyjs.org/docs/creating-a-source-plugin/#improve-plugin-developer-experience-by-enabling-faster-sync, it would be nice if an easy example could be listed on how a data source could be synced. The mentioned example of `gatsby-source-sanity` is not beginner friendly and doesn't illustrate what the constraints are for updating nodes.

### Motivation

I believe anyone who wishes to integrate an external data source could be interested in seeing this.

### Suggestion

Maybe an example where the current time is being added as a node.
Then (if that is possible), the node is being updated by a `setInterval` function.
In the `setInterval` users can see how exactly an existing node is being updated.

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by pvdz** [comment]
Looking forward to your PR :) Be sure to tag @gatsbyjs/learning

**Comment by nojaf** [comment]
This seems to be working for me
```js
exports.sourceNodes = async ({ actions, createNodeId, createContentDigest }) => {
    const { createNode } = actions;

    const processResult = (time) => {
        const nodeId = createNodeId(`currentTime-1`);
        const nodeContent = JSON.stringify(time)
        const nodeData = {
            id: nodeId,
            iso: time.toISOString(),
            parent: null,
            children: [],
            internal: {
                type: `time`,
                content: nodeContent,
                contentDigest: createContentDigest(time),
            },
        };

        createNode(nodeData);
    }

    const scheduleTime = () => {
        setTimeout(() => {
            processResult(new Date());
            scheduleTime();
        }, 5000);

    }

    scheduleTime();

    return
}
```

My query 
```gql
{
  time {
    iso
  }
}
```

**Comment by nojaf** [comment]
After reading [this guide](https://www.gatsbyjs.com/docs/integration-guide/source-plugin/) I learned that it is totally fine to call `createNode` to update existing nodes.
