### ISSUE TITLE
[Discussion] Experimental APIs

### ISSUE THREAD

**Issue by ascorbic** [gatsbyjs/gatsby#21898]
##  Summary

As we add new APIs to Gatsby, we need a way to indicate which are unstable, experimental or otherwise liable to change or disappear.

##  Discussion

In this context, APIs can refer to [Node APIs](https://www.gatsbyjs.org/docs/node-apis/), [Node helpers](https://www.gatsbyjs.org/docs/node-api-helpers/), or functions and components exported by the Gatsby core package.

When developing new features and APIs it is sometimes helpful to be able to add them to Gatsby core before they are stable. This allows us to test them in production sites, and allows plugin authors to experiement with the new APIs. We do not currently have a standard mechanism to do this in a way that makes the experimental status of the APIs clear.

Currently if there are experimental features or behaviours that can be enabled, these are usually behind an env var feature flag. This doesn't apply to new APIs though. The way new APIs are handled is quite ad hoc. They may be added quietly, undocumented, or the fact that they are unstable could be documented. Alternatively they may be given a name that indicates that they are unstable or experimental.

## Suggestion

The simplest approach would be to adopt a standardised naming convention, such as prefixing function names with `UNSTABLE` or `EXPERIMENTAL`. If the APIs are then stabilised, then the prefixed version could be retained with a deprecation warning. Any API marked experimental or unstable could be removed or changed without warning.

## Prior Art

We've previously handled this in two ways:

- Ad hoc via environment variables (Loki)
- `__experimental` (Themes)

**Comment by sidharthachatterjee** [comment]
`unstable` seems like a nice prefix to use for these

**Comment by LekoArts** [comment]
What's the status here @ascorbic ?

**Comment by ascorbic** [comment]
@LekoArts We went with `EXPERIMENTAL` for the conditional builds flag. We never decided on an official policy though. Happy to close this though
