### ISSUE TITLE
RSS feed of the website does not produce item publishing date

### ISSUE THREAD

**Issue by stevebeauge** [gatsbyjs/gatsby#21894]
## Description

Gatbsy's website RSS feed (https://www.gatsbyjs.org/blog/rss.xml) does not produce `pubDate` element under the `item` element. This leeds to confuse RSS readers, because each time the global `pubDate` changes, all items are considered as new.

Exemple with netvibes:

![netvibes](https://user-images.githubusercontent.com/184604/75656834-26c33100-5c65-11ea-8872-7491ffbe1ac7.png)

### Steps to reproduce

Subscript to the RSS of gatsby's website.

All articles are new.

Mark all as read.

Wait for the next feed update.

All articles, even the read ones, are seen as new.

### Expected result

Only new articles should appears unread.

### Actual result

All articles appears unread.

### Environment

RSS reader.

**Comment by freiksenet** [comment]
Thanks, fixed in #21903

**Comment by stevebeauge** [comment]
Very quick resolution ! Thanks !

I confirmed it works as expected in netvibes now.
