### ISSUE TITLE
there are some broken web links

### ISSUE THREAD

**Issue by fatihyildizhan** [gatsbyjs/gatsby#21891]
1- Open this URL : https://www.gatsbyjs.org/showcase/
2- Click any Category and I see a blank page

* Sometimes, it refreshes multiples times and browser-back button disables.

**Comment by b0nbon1** [comment]
@fatihyildizhan I think this one is being fixed by this issue https://github.com/gatsbyjs/gatsby/issues/21867.

**Comment by LekoArts** [comment]
This is a duplicate of #21867
