### ISSUE TITLE
Building and deploying multiple sites within the same Gatsby app

### ISSUE THREAD

**Issue by clarksandholtz** [gatsbyjs/gatsby#2189]
I'm working on automatic page generation and deployment but need to be able to deploy to different domains.

I'd like to be able to have a dynamic number of `src` folders that generate a dynamic number of `public` folders when `gatsby build` is run.

I've tried to approach it by initializing several different gatsby apps and moving the node modules to a parent directory so they can share and save a lot of space, but Gatsby throws a local install was not found error.

Gatsby Version: 1.8.13
Node Version: 8.5.0
OS: macOS Sierra 10.12.6 

<b>Imagined Project Structure</b>

```
root
|-- .cache
|
|-- public_folders
|     |-- public1
|     |
|     |-- public2
|     |
|     |-- ...
|     |
|     |-- publicN
|
|-- src_folders
|     |
|     |-- src1
|     |    |-- layouts
|     |    |-- pages
|     |
|     |-- src2
|     |    |-- layouts
|     |    |-- pages
|     |
|     |-- ...
|     |
|     |-- srcN
|     |    |-- layouts
|     |    |-- pages
|
|-- node_modules
|
|-- .gitignore
|-- gatsby-config.js
|-- gastby-node.js
  .
  .
  .
```

**Comment by KyleAMathews** [comment]
Why not just have each site in its own directory?

**Comment by clarksandholtz** [comment]
That would work well too and that is what I am currently doing. The only downside is each directory needs its own node modules so it quickly takes up a lot of space. 

If you could just host the node modules in the parent directory then that would solve the problem, but there currently needs to be a local install of Gatsby for it to work.

**Comment by KyleAMathews** [comment]
>If you could just host the node modules in the parent directory then that would solve the problem, but there currently needs to be a local install of Gatsby for it to work.

Cool, would love a PR fixing this! I know @jquense has looked into this as well.

**Comment by abumalick** [comment]
You can make a symlink in all websites directories that point to one
folder.

**Comment by sebastienfi** [comment]
@abumalick can you detail on this ?

@clarksandholtz I'm facing the same issue, i'd love to help testing your PR.
What is your idea about the `.cache` folder ?

This improvement could help in having a Gatsby Build Farm with a couple dozen sites, which we plan to have.

**Comment by clarksandholtz** [comment]
@sebastienfi Awesome. I just forked and created a [branch](https://github.com/clarksandholtz/gatsby/tree/issue-2189)

I didn't have any specific ideas about the `.cache` folder.

I have tried using a symlink and a my modified version of Gatsby and the error I'm running into now is `Class constructor ProvidePlugin cannot be invoked without 'new'` when I run `gatsby develop`.

Here's the stack trace:

```
➜  test-page git:(gatsby) ✗ gatsby develop
success delete html files from previous builds — 0.028 s
success open and validate gatsby-config.js — 0.005 s
success copy gatsby files — 0.035 s
success source and transform nodes — 0.039 s
success building schema — 0.143 s
success createLayouts — 0.034 s
success createPages — 0.007 s
success createPagesStatefully — 0.012 s
success extract queries from components — 0.147 s
success run graphql queries — 0.022 s
success write out page data — 0.005 s
success write out redirect data — 0.003 s
success update schema — 0.068 s

info bootstrap finished - 3.425 s

error Class constructor ProvidePlugin cannot be invoked without 'new'


  TypeError: Class constructor ProvidePlugin cannot be invoked without 'new'

  - plugin.js:8 F
    [contra]/[webpack-configurator]/lib/resolve/plugin.js:8:33

  - plugin.js:13
    [contra]/[webpack-configurator]/lib/resolve/plugin.js:13:16

  - plugin.js:14 module.exports
    [contra]/[webpack-configurator]/lib/resolve/plugin.js:14:8

  - index.js:180 Config.resolve
    [contra]/[webpack-configurator]/index.js:180:22

  - webpack-modify-validate.js:67 _callee$
    [contra]/[gatsby]/dist/utils/webpack-modify-validate.js:67:70

  - next_tick.js:131 _combinedTickCallback
    internal/process/next_tick.js:131:7

  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9

```

**Comment by abumalick** [comment]
Something like:
```
mv node_modules ../
ln -s ../node_modules .
```
Should work

**Comment by abumalick** [comment]
Mmhh
Maybe you will have to
```
cd ..
ln -s node_modules project_folder/
```
Symlinks have always been tricky. 
You can check if the symlink is ok with ls -l

**Comment by clarksandholtz** [comment]
When I did the symlink, I just did 
```ln -s ../node_modules node_modules```
but I think we would want to program a fix into Gatsby so you don't have to do a symlink each time you make a new folder.

To do a symlink programmatically in Node you can use `fs.symlink()`, but I think it would be best to avoid the symlink all together and just follow the node standard of searching upwards through parent directories until the proper node_module is found.

**Comment by crucialfelix** [comment]
I set mine up with in the opposite manner:


```
.
├── make.ts
├── activate.ts
├── made
│   └── crucial-systems
│       ├── gatsby-config.js
│       └── src

├── node_modules
├── package.json

├── gatsby-config.js -> /Users/crucialfelix/code/matterminds/made/crucial-systems/gatsby-config.js
├── src -> /Users/crucialfelix/code/matterminds/made/crucial-systems/src


├── public
│   ├── index.html
│   ├── render-page.js.map
│   └── static
```

Where `make` produces all the assets and config for a gatsby site. `activate` symlinks one of those into the root folder. 

So I can activate a site, build it, upload it.

**Comment by KyleAMathews** [comment]
Would love a docs page exploring different options for this problem but closing this for now.

**Comment by jehns** [comment]
Any chance there has been progress on this topic? Struggling with this, any input appreciated! Thanks!

**Comment by maxa11an** [comment]
Why not just symbolic link the node_modules? Seems to work in my project accomplishing the same.
