### ISSUE TITLE
Add prefix links option during development

### ISSUE THREAD

**Issue by BerkeleyTrue** [gatsbyjs/gatsby#219]
I'd be awesome if we can get this option during development.

Our use case involves embedding our static generated app inside a regular app using an Iframe. I need to set up some communication between these two apps so I've got my dev machine set up to alias our github pages url to a specific port on localhost.

This works fantastically when combined with a static server but when working with the dev server I can't get it to work with the main app due to the missing prefix.

**Comment by KyleAMathews** [comment]
Sounds great to me! Not a high priority for me but I'd take a PR.
