### ISSUE TITLE
Ability to query .txt / byte files

### ISSUE THREAD

**Issue by jaminhaber** [gatsbyjs/gatsby#21905]
## Summary

For some project structures it would be helpful to include simple .txt files

### Basic example

query: 
```
files {
    byteContent
}
```

### Motivation

.txt files are useful for getting copy from clients in the freelance world. The ability to simply drag and drop a bio.txt file into a designated folder would speed up my workflow with gatsby. 

Thanks for reading!

**Comment by herecydev** [comment]
If the files you get are json then you can use the [gatsby-transformer-json](https://www.gatsbyjs.org/packages/gatsby-transformer-json/?=json#gatsby-transformer-json) along with the `gatsby-source-filesystem`.

Essentially your workflow would become drag and drop `.json` files into a static folder, i.e. `src/data/` and these are then digested into the graphql world for gatsby pages/components to use.

Now, the files would need to have an appropriate file extension and follow the rules of json or yaml, xml etc. These are all supported with various transformer plugins.

Failing that if you do have a agreed schema with your clients then you can create a transformer yourself. Gatsby is very flexible in that regard.

Let me know if you need any help

**Comment by jaminhaber** [comment]
@herecydev 
I agree that JSON/ yaml is very useful but it would also be helpful in some instances to read simple files in as a string. Sometimes it doesn't make sense to have a JSON file for a single property when a .txt file could do the same thing. 

Since the file is already being picked up by the transformer, I feel like granting developers access to the raw text (even with JSON/YAML) couldn't hurt.

**Comment by KyleAMathews** [comment]
A `gatsby-transformer-txt` would be great for this! Check out this tutorial on how you could create it. https://www.gatsbyjs.org/docs/creating-a-transformer-plugin/

**Comment by jaminhaber** [comment]
@KyleAMathews Thank you, I will look into that :)

**Comment by sidharthachatterjee** [comment]
Let's close this since it'll likely live _outside_ this repo. Thanks, everyone!
