### ISSUE TITLE
Very slow site build on large number of files

### ISSUE THREAD

**Issue by benday280412** [gatsbyjs/gatsby#2190]
Hi there,

I'm currently trying to build a site with over 37,000 pages.  Most pages are very small, but i think the sheer number is causing problems.

Is there any known limitations in this regard?  Is this a loosing battle, or something that should/may be possible.

Thanks for a great project by the way.

**Comment by KyleAMathews** [comment]
We haven't focused yet on issues around building larger sites. There are many ways to speed things up but we've focused so far on the developer experience and correctness.

Gatsby v2 will move us to webpack 3 which has a number of performance improvements.

Gatsby v3 will have a number of improvements to caching + ability to parallelize builds which will help significantly.

If you want to try profiling the build process that'd be very interesting/helpful to see!

**Comment by benday280412** [comment]
OK, cool.

I'm something of a novice with regards to Node, but I'll have a dig around and see if i can turn up some useful insight into where the execution time is being spent.

**Comment by imjared** [comment]
@benday280412 when you say "very slow site build", can you provide some numbers?

**Comment by drupalninja** [comment]
Would also love some follow-up on this

**Comment by theangryangel** [comment]
I’m not the OP but when a client was looking at gatsby v2 we found that they were using the CSV module/input (sorry I’ve forgotten the terminology) to generate a bunch of pages. I think somewhere in the region of 3k pages would hit about a 10-15 minute build time. The box they were trying this out on was a decent spec laptop with SSDs and a fairly well clocked Core i7. Can’t remember much more information than that, and I’m pretty sure that’s where the client chose to look elsewhere as they were in need of an immediate solution.

**Comment by jlengstorf** [comment]
@drupalninja @theangryangel speeding up large builds is very much a focus right now. There's no official timeline, but it's under active development.

**Comment by drupalninja** [comment]
Thanks for responding so quickly! @jlengstorf do you have a general recommendation for a "comfortable" number of pages before build times start to slow significantly?

**Comment by jlengstorf** [comment]
Hey, @drupalninja — it's going to vary quite a bit based on what kind of work each page is doing. For example, it'll be much faster to process a page with no images.

So unfortunately, the answer is, "It depends." 😄

**Comment by csadai** [comment]
Hi @jlengstorf - I'm currently working on the migration of a large (100K+ pages) website currently on PHP/Symfony to React/GastbyJS (SEO critical, cannot go fully dynamic). The underlying CMS would be GraphCMS. We are currently considering Next.js or Hugo in the meantime, as Gatsby builds seem to fail. As large sites seem to be the focus for Gatsby, let me know if you are in the looks for beta testers for at some point.

**Comment by jlengstorf** [comment]
@csadai Do you have a build log we can look at? Any chance you'd be willing to share the code?

If you're not already using Gatsby v2, it may be worth a try. We made some major improvements that should add a decent speed boost. (V2 is mostly stable; the beta should be officially out soon.) We're also working on architectural adjustments that would allow us to build huge sites _really_ fast; that's a little ways off, though. (Feel free to drop your name into our [contact form on the support page](https://www.gatsbyjs.com/support/) to be added to our alpha waitlist!)

I don't know if it's in your budget, but Gatsby Inc now has [support packages](https://www.gatsbyjs.com/support/) — we can help troubleshoot and/or spot-and-patch issues in the Gatsby core that are preventing your builds from completing.

Let me know if there's anything I can do to help!

**Comment by KyleAMathews** [comment]
Improving Gatsby's build speed & number of pages it can handle is a continual focus but as this issue isn't actionable, closing for now.
