### ISSUE TITLE
createRemoteFileNode crashes when url doesn't have an extension

### ISSUE THREAD

**Issue by chpio** [gatsbyjs/gatsby#21901]
## Description

calling `createRemoteFileNode` with an url (<https://fakeimg.pl/300x300/?text=2>) without an extension crashes.

```
Unexpected error value: "failed to process https://fakeimg.pl/300x300/?text=2\nError: ENOENT: no such file or directory, stat '.../.cache/gatsby-source-filesystem/7a1221ea4c61551f928908dd873a3738/300x300'"
```
I think it has something to do with how the caching is handled.

### Steps to reproduce

1. use `createRemoteFileNode` to create remote file nodes from an url without an ext
2. use the remote file node in eg. sharp-image
3. the first build goes through
4. all builds afterwards crash

### Environment

```
  System:
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.9.0 - /usr/bin/node
    Yarn: 1.22.0 - ~/bin/yarn
    npm: 6.13.7 - /usr/bin/npm
  Languages:
    Python: 2.7.15+ - /usr/bin/python
  Browsers:
    Firefox: 73.0.1
  npmPackages:
    gatsby: ^2.19.21 => 2.19.24
    gatsby-cli: ^2.9.0 => 2.9.0
    gatsby-image: ^2.2.41 => 2.2.42
    gatsby-plugin-graphql-codegen: ^2.2.2 => 2.2.3
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.22
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^2.1.27 => 2.1.29
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5
    gatsby-source-filesystem: ^2.1.48 => 2.1.48
    gatsby-transformer-json: ^2.2.26 => 2.2.26
    gatsby-transformer-sharp: ^2.3.14 => 2.3.16
```
### Repro
<https://github.com/chpio/gatsby-remote-wo-ext> commit https://github.com/chpio/gatsby-remote-wo-ext/commit/8d898f6915221495e092798e5bfcbacdd3faaf30

**Comment by freiksenet** [comment]
See [this documentation about using `createRemoteFileNode` without extension](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#retrieving-the-remote-file-name-and-extension)

**Comment by chpio** [comment]
Ok, what are you saying?

> If the url does not contain an extension, we use the file-type package to infer the file type. 

That's works for the 1. build, but not for following builds. The cache file gets created with an extension, but the following builds try to read the file from cache without an extension.

**Comment by freiksenet** [comment]
@chpio You should pass extension of file explicitly, does it work?

```  
  ext: ".jpg",
  name: "image"
```

**Comment by chpio** [comment]
1. Why *should* i do that? The doc even says, that it *can* be passed in:  

    > Finally, the name and the extension *can* be explicitly passed
  
2. to pass it in i need to know it, but i do not. My first workaround was to just pass in ".jpeg", but then i needed the actual extension (to generate the `download` argument on an `<a>` tag)
3. a crash is clearly a bug

**Comment by muescha** [comment]
Can you create a [reproducie test case](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)?

**Comment by chpio** [comment]
@muescha https://github.com/chpio/gatsby-remote-wo-ext

**Comment by darcy** [comment]
Following... I'm having this issue using the same technique in the provided test case.

**Comment by THE108** [comment]
We're having the same issue.

```
Gatsby CLI version: 2.7.47
Gatsby version: 2.20.22
```

**Comment by dimileeh** [comment]
When a new user logs in to my Gatsby website with Google, I get their avatar from their Google account. Google's URLs for avatars look like this:
`https://lh3.googleusercontent.com/a-/AAuE7mBhk7bsX8uoSh9mRLwM2An0u1tyPcu_bv1TQI6Y`.

In `gatsby-node.js`, I use `createRemoteFileNode` with this url.

This first build, as @chpio mentioned, finishes successfully. 

If I don't clear Gatsby cache, upon consecutive builds I get:
`ERROR Fetching Author Avatar: failed to process https://lh3.googleusercontent.com/a-/AAuE7mBhk7bsX8uoSh9mRLwM2An0u1tyPcu_bv1TQI6Y Error: ENOENT: no such file or directory, stat '/usr/src/app/www/.cache/caches/default-site-plugin/766d6ed63d9b327f1affaea984564e91/AAuE7mBhk7bsX8uoSh9mRLwM2An0u1tyPcu_bv1TQI6Y'`

**Comment by vladar** [comment]
The issue is probably somewhere along those lines:

https://github.com/gatsbyjs/gatsby/blob/03803999bd35018a599a8644f16424b75e6c89a3/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L249-L250

`fileTypes.minimumBytes` were removed here: https://github.com/sindresorhus/file-type/pull/319

So we probably need to update `gatsby-source-filesystem` to accommodate this change. PR is welcome!

**Comment by ynnoj** [comment]
@vladar Seems like [`FileType.fromFile()`](https://github.com/sindresorhus/file-type#filetypefromfilefilepath) should do the job?

**Comment by vladar** [comment]
Yup, looks like it should do the trick!

**Comment by ynnoj** [comment]
#27559 awaiting review to resolve.
