### ISSUE TITLE
Edit/change page path

### ISSUE THREAD

**Issue by daniel-winter** [gatsbyjs/gatsby#21904]
I have the following problem. We are generating different static HTML files with gatsby for different countries via `createPage: path: `${rail}/_error/503-${country}.html``.

The static HTML should be available under
```
`${rail}`.${country}
`${rail}`.${country}
`${rail}`.${country}
```

Instead if we open/call the URL they are redirecting to:

```
${rail}.${country}/_error/503-${country}.html
${rail}.${country}/_error/503-${country}.html
```

So my question is: Is it possible to edit/change the path that it not adds the parameter to the URL?
Maybe the `window.pagePath` in the `<script id="gatsby-script-loader">` has something do to with that problem?

P.S. After a lot of research I see no other option to add a issue/question here. Sorry for the circumstances

Thanks in advance for your help.

### Environment (if relevant)
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /var/folders/tl/t49w203n4rn7ym68xvvc1_9h00019b/T/yarn--1583161853028-0.7615433747877345/node
    Yarn: 1.22.0 - /var/folders/tl/t49w203n4rn7ym68xvvc1_9h00019b/T/yarn--1583161853028-0.7615433747877345/yarn
    npm: 6.13.7 - ~/Documents/code/xxxl-webshop-frontend/node_modules/.bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: 72.0.2
    Safari: 13.0.5

### File contents (if changed)

`gatsby-config.js`:

```
module.exports = {
  plugins: [
    `gatsby-transformer-json`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/data`,
      },
    },
  ],
  pathPrefix: `maintenance`,
};
```

`package.json`:
```
  "scripts": {
    "build": "gatsby build --prefix-paths",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "yarn run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "information": "gatsby info --clipboard"
  },
  "dependencies": {
    "@xxxlgroup/hydra-icons": "12.11.0",
    "@xxxlgroup/hydra-ui-components": "12.11.0",
    "@xxxlgroup/hydra-utils": "12.11.0",
    "eslint-plugin-graphql": "3.1.1",
    "gatsby": "2.16.0",
    "prop-types": "15.7.2",
    "react": "16.12.0",
    "react-dom": "16.12.0"
  },
  "devDependencies": {
    "gatsby-plugin-react-helmet": "3.1.21",
    "gatsby-source-filesystem": "2.1.46",
    "gatsby-transformer-json": "2.2.26",
    "react-helmet": "5.2.1",
    "sass-loader": "7.3.1"
  },
  "comments": {
    "gatsby-version": "Please be careful if updating the gatsby version, there are problems with newer versions than 2.16.0 in production building"
  }
```

**Comment by pvdz** [comment]
Hi @daniel-winter 

I think you should be able to achieve what you want with client-side routing. This doesn't scale very well, but should be fine for error pages with different languages.

Docs: https://www.gatsbyjs.org/docs/adding-app-and-website-functionality/#client-only-routes

**Comment by daniel-winter** [comment]
> Hi @daniel-winter
> 
> I think you should be able to achieve what you want with client-side routing. This doesn't scale very well, but should be fine for error pages with different languages.
> 
> Docs: https://www.gatsbyjs.org/docs/adding-app-and-website-functionality/#client-only-routes

Thanks @pvdz for your answer. I will have a look.

**Comment by pvdz** [comment]
Going to close this issue. Please re-open it if you have more questions. Thank you :)
