### ISSUE TITLE
Gastby site brokes when try to search dependency

### ISSUE THREAD

**Issue by afucher** [gatsbyjs/gatsby#21916]
## Description

When try to search for starters that use some plugin, the site broke and just show a blank page.
example: https://www.gatsbyjs.org/starters/?d=gatsby-source-googlemaps-static&v=2

### Steps to reproduce

Enter in the plugin search page, click on any plugin and then click on the `See starters using this` link.

### Expected result

I should see a page with the result of the search.

### Actual result

It shows a blank page

**Comment by pvdz** [comment]
Hi @afucher. Thanks for your report.

I've confirmed the problem. Trace:

Bug introduced in https://github.com/gatsbyjs/gatsby/commit/fda78f1f9e6ed0af75fa9bca19c5cf0ad283889e#diff-51865a2ea87f4bfd5fb20a85ed340a9bL25 by https://github.com/gatsbyjs/gatsby/pull/21792
Then https://github.com/gatsbyjs/gatsby/pull/21876 tried to fix it which is leading to the current problem where the node does not have the property that was read from the edge in filterByDependencies in gatsby/www/src/views/starter-library/filtered-starters.js and therefor this breaks

```
  starters = starters.filter(
    ({ node: starter }) =>
      starter.fields &&
```
