### ISSUE TITLE
Gatsby's webpack-dev-server should ignore project's gatsby-config.js by default to avoid infinite reload loop (from require.resolve()'s)

### ISSUE THREAD

**Issue by jussikinnula** [gatsbyjs/gatsby#21922]
## Description

When using instructions from https://www.gatsbyjs.org/packages/gatsby-source-prismic-graphql/ (e.g. using Gatsby + Prismic via GraphQL), there's a conflict in Gatsby's webpack-dev-server configuration. The development server should ignore at least `gatsby-config.js`, since it's lazy requiring (e.g. `require.resolve()`) the templates.

A workaround to get rid of this problem is to add `gatsby-node.js` file containing the following:

```js
const path = require('path');

exports.onCreateWebpackConfig = ({ actions, getConfig }) => {
  const config = getConfig();
  config.devServer = {
    watchOptions: {
      ignored: [
        path.resolve(__dirname, 'gatsby-config.js'),
        path.resolve(__dirname, 'public'),
      ]
    }
  };
  actions.replaceWebpackConfig(config);
};
```

### Steps to reproduce

Follow the steps described here: https://www.gatsbyjs.org/packages/gatsby-source-prismic-graphql/ 

A full example: https://github.com/jussikinnula/femafi

### Expected result

Gatsby's defaults should prevent infinite reload loops using `gatsby develop`.

### Actual result

There's infinite reload loop, if using `require.resolve()` in one of the entrypoints Gatsby's webpack-dev-server uses.

### Environment

N/A

**Comment by jussikinnula** [comment]
I might have time to fix this in next month, if nobody else can't.

**Comment by pvdz** [comment]
Maybe @wardpeet has some insight here to help you out.

**Comment by jussikinnula** [comment]
Actually ignoring `gatsby-config.js` doesn't seem to work as intended, but anyway - this problem is tied so that when changing some files (in `src/` -directory), at some point webpack-dev-server (that `gatsby develop` started) just gets stuck. I think it maybe helps a little bit to add `aggregateTimeout` - but in the end - there should be a way to ignore files, so that the indefinite reloading loop wouldn't be triggered.

A colleague of mine did get the indefinite loop even with commenting out `require.resolve()` files and not actually using preview at all. So it might be that actually a lot of more directories would have to be ignored, like `.cache`, etc).

**Comment by jussikinnula** [comment]
So far what I've discovered. Actually the indefinite loop has nothing to do with Webpack. The problem is in `page-hot-reloader`. Basically it should trigger rebuild only if needed.

**Comment by jussikinnula** [comment]
Fix might be by changing this: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/requires-writer.js#L199-L217

Instead of using debounce, we actually need to ensure that there's only one running function at the time. 

But this is not the full solution, since during createPages (which is triggered by files changing) `debouncedWriteAll` still gets called indefinite amount of times. So basically the root cause is that changing files trigger `createPages`, which then trigger indefinite amount of `debouncedWriteAll` calls.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
