### ISSUE TITLE
Docs: "Gatsby on Windows" should list python 3

### ISSUE THREAD

**Issue by LorenAmelang** [gatsbyjs/gatsby#21920]
### Description

I actually don't know if this is a documentation glitch or deeper confusion, or if the project is really using a dead Python. But it has the potential to really confuse new users like me. 

### Steps to reproduce

Go to 
https://www.gatsbyjs.org/docs/gatsby-on-windows/

Where you are told to enter:
npm config set python python2.7

### Expected result

I'd expect Gatsby to know about Python 3...  

### Actual result

I actually don't know. Maybe this was a factor in Gatsby failing miserably for me, long before the new Windows install documentation...  

### Environment

Windows, of any version...  

See:
https://github.com/gatsbyjs/gatsby/issues/15529#issuecomment-593622962

**Comment by pvdz** [comment]
Hi @LorenAmelang and thanks for your report :)

According to @LekoArts the tools will install python 3 so this is a matter of the docs being outdated.

**Comment by pvdz** [comment]
cc @gatsbyjs/learning

**Comment by pieh** [comment]
Hey @LorenAmelang! In principle I do agree with you, but the issue is a little more nuanced:

Gatsby still supports Node 8, which comes with npm@^5, which comes with node-gyp@^3.6.2

If you look at docs for node-gyp@^3 ( https://github.com/nodejs/node-gyp/tree/v3.8.0 ), you will find that in this scenario you do need to use python@2.7 and python@3 is actually not supported.

On newer Node versions this changes (I would need to track exact versions how and when), but yes, you should be able to use python@3.

The docs could be more specific about this, but using python@2.7 will still work everywhere (even if it's not best idea to use "dead" version), while python@3 will work only in some cases.

**Comment by pieh** [comment]
Also to add to above. Gatsby itself doesn't make use of `node-gyp` - setting `node-gyp`/`python` is needed for some dependencies that we don't control. Notably to build `sharp` package if there is no prebuilt binary available for system, but there are more dependencies that need `node-gyp`

**Comment by LorenAmelang** [comment]
> Hey @LorenAmelang! In principle I do agree with you, but the issue is a little more nuanced:
> 
> Gatsby still supports Node 8, which comes with npm@^5, which comes with node-gyp@^3.6.2

> The docs could be more specific about this, but using python@2.7 will still work everywhere (even if it's not best idea to use "dead" version), while python@3 will work only in some cases.

I suspected there was something deep going on there! Thank you for knowing the details I could never have realistically dug up. 

Maybe there could be a note beside those Python 2.7 lines in the Windows doc page, pointing to this issue...  And anywhere else 2.7 is still mentioned?

**Comment by laurieontech** [comment]
As a general rule we try not to link to issues from the docs if we can help it.
An alternative might be explaining the dependency being pulled from python 2.7 and while it's still the correct version to use?

**Comment by LorenAmelang** [comment]
I'm not clear how to tell if this has been put on someone's ToDo list or not...  
@laurieontech suggested I create this issue to get it handled. 

https://www.gatsbyjs.org/docs/gatsby-on-windows/ still has no explanation of why python 2.7 is needed! Until that is fixed I think this issue is a valuable clue for dedicated searchers.

**Comment by laurieontech** [comment]
I'm open to someone submitting a PR with a note about why this is still the recommendation.

**Comment by marcysutton** [comment]
Perhaps this could be revisited now that Gatsby has dropped support for Node 8? https://www.gatsbyjs.org/blog/2020-03-20-dropping-support-for-node-8/
