### ISSUE TITLE
Reuse fragments at runtime for client-side GraphQL query

### ISSUE THREAD

**Issue by maltoe** [gatsbyjs/gatsby#21935]
Hello, 👋 

thanks for making Gatsby! 💚 

## Summary

We have a site that feeds from a custom GraphQL endpoint and would like to query the same GraphQL endpoint at runtime and reuse the component fragments.

## Relevant information

* The project uses `gatsby-source-graphql` to source data from an external GraphQL endpoint
* We have Apollo-Client set up in a component that fetches data from the same external endpoint, at runtime, and using more or less the same queries (for "live" updates)
* We would like to reuse fragments that are used at compile time. However, since the `graphql` template literal doesn't allow string interpolation, it's not possible to simply export the fragments as strings  and use them in a runtime apollo `query`.

Question would be: Is there a way to either pass string fragments to Gatsby, or retrieve fragments back from Gatsby at build time (e.g. can they be found somewhere in the store?)

## Example

```
# We would like to reuse the string passed to the graphql tag below.
export const fragment = graphql`
  fragment Foo on FooType {
    ...
  }
`;

# This does not work.
export const fragmentString = '...';
export const fragment = graphql`${fragmentString}`;

# This does not work.
export const fragmentString = '...';
export const fragment = graphql([fragmentString]);

# This does not work (gql from graphql-tag)
export const fragmentString = gql`...`;
export const fragment = graphql([fragmentString]);
```

Any suggestions / hints?

Thanks,
malte

**Comment by vladar** [comment]
Hey @maltoe 

Sadly, there is no easy way to do this at the moment.

Gatsby extracts queries in build-time (basically during babel pass). Interpolation makes it harder to do this. In theory, we could support a limited subset of interpolation but that would make things way harder to maintain and can make things more confusing (like why do we support one case of interpolation and not the other).

The only approach I can think of is if you had a [custom babel plugin](https://www.gatsbyjs.org/docs/babel/#how-to-use-a-custom-babelrc-file) that would copy those fragments into another variable (which you can use from Apollo). But that may be too magical.

Let's keep this issue open for some time, maybe someone will come up with other ideas.
