### ISSUE TITLE
Gatsby Image lazy loading intermittently fails to trigger onLoad callback. (Chrome only)

### ISSUE THREAD

**Issue by elliott-greaves-babylon-health** [gatsbyjs/gatsby#21932]
## Description
I am finding `Gatsby-Image` is intermittently failing to display the full-size lazy loaded image, leaving the blurred variant visible. This only occurs when loading a web page from a cold cache. Refreshing the browser window once renders the images as initially expected.

### Steps to reproduce
1. You will need a Gatsby application with Contentful added as a data source.
2. Within React-based page template (not markdown), paste this Static GraphQL query, which requests for fluid variants of all contentful assets
```graphql
      const { allContentfulAsset } = useStaticQuery(graphql`
        query CONTENTFUL_IMAGE_QUERY {
          allContentfulAsset {
            nodes {
              file {
                url
              }
              fluid(maxWidth: 1050, quality: 85) {
                ...GatsbyContentfulFluid
              }
            }
          }
        }
      `)
```  
3. Select the first image from the response
```js
 const singleFluidImage = allContentfulAsset.nodes[0]
```

4. Use the Gatsby Image component with the requested image
```jsx
<GatsbyImage
      title="string value..."
      fluid={singleFluidImage}
      loading="lazy"
      onStartLoad={e => console.log('onStartLoad: Image is loading', e)}
      onLoad={() => console.log('onLoad triggered: Image has loaded')}
/>
```

5. Build the static site locally running
```bash
gatsby build
```

6. Preview the page template within Chrome (I have version 79.0.3945.130)
7. Gatsby Image renders the blurred image variant
8. `onStartLoad` callback is called.
9. Full-size images are loaded (See screenshot of Chrome network tab)
10. onLoad` callback is intermittently called after full-size images have downloaded.
![image](https://user-images.githubusercontent.com/48715907/75778946-a974ea80-5d50-11ea-96a7-2bb49f270d86.png)

11. Images remain blurry
![image](https://user-images.githubusercontent.com/48715907/75778803-5f8c0480-5d50-11ea-82cb-cea9438bad89.png)

### Expected result
Once a full-size image has finished loading over the network, the onLoad callback should be called, and the blurred image should be replaced with the full-size variant.

### Actual result
1. onLoad callback is never called
2. The blurred image is never swapped with the full-size variant

### Environment
  System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: 72.0.1
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.13.50 => 2.19.19 
    gatsby-image: ^2.2.42 => 2.2.42 
    gatsby-plugin-google-analytics: ^2.1.34 => 2.1.35 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.41 
    gatsby-plugin-mdx: ^1.0.0 => 1.0.73 
    gatsby-plugin-offline: ^3.0.16 => 3.0.35 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.22 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sass: ^2.1.20 => 2.1.29 
    gatsby-plugin-sharp: ^2.2.9 => 2.4.5 
    gatsby-plugin-typescript: ^2.1.15 => 2.1.27 
    gatsby-source-contentful: ^2.1.62 => 2.1.86 
    gatsby-source-filesystem: ^2.1.33 => 2.1.48 
    gatsby-source-graphql: ^2.1.22 => 2.1.33 
    gatsby-transformer-remark: ^2.6.37 => 2.6.53 
    gatsby-transformer-sharp: ^2.2.5 => 2.3.14 
  npmGlobalPackages:
    gatsby-cli: 2.8.3

**Comment by TrentYetzer** [comment]
I am having the exact same issue, and I have not really been able to find anything that helps. Additionally, when I try to use the `...GatsbyImageSharpFluid_noBase64` fragment to avoid lazy loading the image, it does not appear altogether. However, I don't have any of the issues listed above with gatsby develop, only with gatsby build.

**Comment by skingston91** [comment]
I have the same issue, working fine with gatsby develop locally but once deployed to zeit now with the git integration my images are only loading the placeholder images. I can see the complied json has the full srcSets etc but they are never loaded.

**Comment by wardpeet** [comment]
@elliott-greaves-babylon-health can you link us to a real url? This might be a browser issue that we have to workaround

**Comment by elliott-greaves-babylon-health** [comment]
@wardpeet the site isn't public yet so I'm not able to share a link. I can confirm this is only an issue in Google Chrome.

**Comment by elliott-greaves-babylon-health** [comment]
Not stale

**Comment by vonba** [comment]
I'm also seeing this same issue. Please see example at https://nifty-jepsen-2ac991.netlify.app
If you click on "past projects" you will consistently see only blurry previews. Refresh the page and images load correctly.
