### ISSUE TITLE
docs: add info about location.href

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#21946]
## Summary

- add section about `location.href` is not available in SSR

### Motivation

some mistakes are coming from using `location.href` in server side rendering - but there is no place in docs where is a hint about this

```diff
-const href = location.href
+const href = `${siteUrl}${pathname}`
```

### References

https://css-tricks.com/how-to-the-get-current-page-url-in-gatsby/#article-header-id-4

### Docs

maybe placing infos here:
- https://www.gatsbyjs.org/docs/troubleshooting-common-errors/
- https://www.gatsbyjs.org/docs/location-data-from-props/

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by pieh** [comment]
On top of documention, we can make trying to access `location.href` to throw error in code (which would contain link to appropriate docs. Alternatively we could maybe construct `.href` for SSR? But I feel like constructing it ourselves might just hide some problems and introduce even more problems (subtle, and hard to debug)

**Comment by seaneking** [comment]
Also ran into this, using `location.href` for meta tags, which have to be SSRd. I think Gatsby should:

- Document what's available on `location` in SSR/buildtime
- Error if trying to access `location.href` when it's not available
- Document using `location.pathname` and the site's canonical URL instead

I don't think Gatsby should try and construct `location.href` in SSR envs. It's pretty trivial to do yourself, and far less opaque. Just needs to be documented, and not silently fail.

**Comment by imrishabh18** [comment]
Can i work on this documentation ?

**Comment by marcysutton** [comment]
Sure @imrishabh18, we would love your contribution!

**Comment by imrishabh18** [comment]
@marcysutton Hey, can you please help me what should i write in the docs ?

**Comment by seaneking** [comment]
Not stale, still needs a fix AFAIK

**Comment by seaneking** [comment]
Still not stale

**Comment by ehrencrona** [comment]
To provide an error message in this situation, there needs to be a change to reach/router. I've submitted [an issue](https://github.com/reach/router/issues/397) and [a PR](https://github.com/reach/router/issues/397) on reach that should fix it.
