### ISSUE TITLE
Search on starters

### ISSUE THREAD

**Issue by rathesDot** [gatsbyjs/gatsby#21942]
## Description

If you go to https://www.gatsbyjs.org/starters/?v=2 and start searching (the input field for searching starters, not the main search), you will get a blank page.

### Steps to reproduce

_see above_

### Expected result

You should see filtered results based on the input value.

### Actual result

Page breaks and renders nothing.

### Environment

Gatsby website, the starters page.

---

The error message that I get is
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at filtered-starters.js:86
```

which is here
 https://github.com/gatsbyjs/gatsby/blob/5baaa0f739fc14055ab874a86380ebdd69ebedc2/www/src/views/starter-library/filtered-starters.js#L86

if I'm not mistaken.

**Comment by Usamaliaquat123** [comment]
@rathesDot  right I think it causes the problem with  `toLowerCase` or  `includes` cause its getting `undefined`..

**Comment by pvdz** [comment]
Thanks for reporting.

I've filed #21951 which should fix this issue.
