### ISSUE TITLE
gatsby-source-patronus not found on npm

### ISSUE THREAD

**Issue by gadzet** [gatsbyjs/gatsby#21952]
## Summary
Not sure if Its a documentation or a bug, but in the environment variables documentation there is an option to use something called `gatsby-source-patronus` which is not available on npm. On top of that there is no documentation on how to retrieve the value in the front end after adding it as an option. 

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/environment-variables.md

## Draft of the documentation
```
// In any server-side code, e.g. gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-patronus`,
      options: {
        apiKey: process.env.API_KEY,
      },
    },
  ],
}
```

I would suggest either remove it or to update the documentation and npm.

**Comment by LekoArts** [comment]
Thank you for opening this!

All the code shown in this documentation page is example/dummy code. It's not supposed to work and there isn't such a package. It's not the goal of this doc to teach you how to use a source plugin, even if it would do that: We would share a ENV var publicly and that's exactly what this document is telling you to not do :)

Hope that clears things up a bit.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
