### ISSUE TITLE
Gatsby cache issues

### ISSUE THREAD

**Issue by expatguideturkey** [gatsbyjs/gatsby#21958]
I have hosted my Gatsby public folder files on root of the host server (Plesk). Whenever I update the new version of my Gatsby website I still see old version on some of the pages. Is there a way or a gatsby plugin to clear the browser or server cache whoever is causing this issue.

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll need to incorporate the correct caching headers in your Plesk setup. A reference is here: https://www.gatsbyjs.org/docs/caching/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
