### ISSUE TITLE
gatsby-node.js file in themes

### ISSUE THREAD

**Issue by kayali1411** [gatsbyjs/gatsby#21968]
I am wondering if I can add gatsby-node.js to gatsby project when I am using a theme.
I checked the document [building-a-theme](https://www.gatsbyjs.org/tutorial/building-a-theme/), I found nothing is mentioned about adding gatsby-node.js to gatsby project.
I need to add this file to the project in order to fetch data from a different data source.

**Comment by LekoArts** [comment]
Thank you for opening this!

Sure, you can use gatsby-node.js, gatsby-browser.js, gatsby-ssr.js or gatsby-config.js
In particular gatsby-node.js is used in the tutorial here: https://www.gatsbyjs.org/tutorial/building-a-theme/#define-resolvers-for-any-custom-fields-slug

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by kayali1411** [comment]
Thanks for your quick response!
Actually I am asking on the ability to add `gatsby-node.js` to gatsby project` not `gatsby-theme`
so I will have two different `gatsby-node.js` files one in the theme another one in the project that running theme, is that doable?

**Comment by LekoArts** [comment]
Yeah, you can do that :)
