### ISSUE TITLE
(docs): add most visited pages on gatsbyjs repo to Troubleshooting Common Errors guide

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#21966]
## Summary

A few months ago a guide called [Troubleshooting Common Errors](https://www.gatsbyjs.org/docs/troubleshooting-common-errors/) was made to aid discoverability of issues that many people kept stumbling into.

I wandered across a traffic page on the repo (https://github.com/gatsbyjs/gatsby/graphs/traffic) that showed some issues were getting the most page views. I think that adding specifically the issue on hitting system file watcher limits would be a nice easy win: https://github.com/gatsbyjs/gatsby/issues/11406

### Motivation

The answer in that issue has over 750 (!!) 👍 reactions, this could help a lot of people get to an answer faster.

## Steps to resolve this issue

Let's add information about this error to the Common Errors guide!

### Draft the doc

- [ ] Write a section under Heading 2 "Errors building and deploying", following the format of the other error sections and using answers from the issue thread to help.
- [ ] Link back to the issue thread with a note saying "you may be able to find more information or discuss this issue here..." 

### Open a pull request

- [ ] Open a pull request with your work including the words "Closes #[this issue's number]" in the pull request description

**Comment by dmitriyaa** [comment]
Hi @gillkyle, I can try to do this one 🙂

**Comment by gillkyle** [comment]
Thanks @dmitriyaa that would be great!

**Comment by dmitriyaa** [comment]
@gillkyle, just submitted a PR 🙃
