### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by aditya-lw** [gatsbyjs/gatsby#21977]
## Description

Site build fails when trying to deploy from netlify. Works and successfully builds when running locally.

### Expected result

Should build and deploy like as it happens locally.
### Actual result

![Screenshot from 2020-03-05 12-23-02](https://user-images.githubusercontent.com/60033184/75955794-92fb9a00-5edc-11ea-9b36-14d4f226cf53.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.14.0 - ~/.nvm/versions/node/v10.14.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 73.0.1
  npmPackages:
    gatsby: ^2.19.28 => 2.19.28 
    gatsby-image: 2.0.23 => 2.0.23 
    gatsby-plugin-feed: 2.0.11 => 2.0.11 
    gatsby-plugin-google-analytics: 2.0.8 => 2.0.8 
    gatsby-plugin-google-tagmanager: 2.1.23 => 2.1.23 
    gatsby-plugin-hotjar: 1.0.1 => 1.0.1 
    gatsby-plugin-hubspot: 1.3.3 => 1.3.3 
    gatsby-plugin-mailchimp: 5.1.2 => 5.1.2 
    gatsby-plugin-netlify: 2.0.6 => 2.0.6 
    gatsby-plugin-netlify-cms: 4.1.35 => 4.1.35 
    gatsby-plugin-purgecss: 4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: 3.0.4 => 3.0.4 
    gatsby-plugin-robots-txt: 1.3.0 => 1.3.0 
    gatsby-plugin-sass: 2.0.7 => 2.0.7 
    gatsby-plugin-sharp: 2.2.9 => 2.2.9 
    gatsby-plugin-sitemap: 2.0.2 => 2.0.2 
    gatsby-plugin-tawk: 1.0.0 => 1.0.0 
    gatsby-remark-copy-linked-files: 2.0.7 => 2.0.7 
    gatsby-remark-images: 3.1.6 => 3.1.6 
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0 
    gatsby-source-filesystem: 2.0.26 => 2.0.26 
    gatsby-transformer-remark: 2.6.9 => 2.6.9 
    gatsby-transformer-sharp: 2.2.6 => 2.2.6 
  npmGlobalPackages:
    gatsby-cli: 2.4.9

**Comment by pieh** [comment]
I tried to reproduce using https://github.com/netlify-templates/gatsby-starter-netlify-cms and wasn't able to (either locally or on netlify).

Could you try to bump `gatsby-plugin-netlify-cms` to latest? I checked with version 4.1.40 and your version is 4.1.35 so that might have been fixed already?

If updating plugin doesn't fix anything, we will need reproduction repository for this

**Comment by aditya-lw** [comment]
Nevermind. The error was with the version I guess. Tried 4.1.6 and it seems to work now.

**Comment by kevrowe** [comment]
I'm getting this same error with newer versions, updated to 4.1.41 because I was having issues at 4.1.6

```
gatsby-background-image@0.9.19
gatsby-cli@2.8.30
gatsby-core-utils@1.0.28
gatsby-graphiql-explorer@0.2.34
gatsby-image@2.2.41
gatsby-link@2.2.29
gatsby-page-utils@0.0.39
gatsby-plugin-google-tagmanager@2.1.25
gatsby-plugin-netlify-cms-paths@1.3.0
gatsby-plugin-netlify-cms@4.1.41
gatsby-plugin-netlify@2.1.32
gatsby-plugin-page-creator@2.1.40
gatsby-plugin-purgecss@4.0.1
gatsby-plugin-react-helmet@3.1.22
gatsby-plugin-react-svg@2.1.2
gatsby-plugin-sass@2.1.29
gatsby-plugin-sharp@2.4.5
gatsby-plugin-sitemap@2.2.27
gatsby-react-router-scroll@2.1.21
gatsby-remark-copy-linked-files@2.1.37
gatsby-remark-images@3.1.44
gatsby-remark-relative-images@0.2.3
gatsby-source-filesystem@2.1.48
gatsby-telemetry@1.1.49
gatsby-transformer-remark@2.6.53
gatsby-transformer-sharp@2.3.14
gatsby@2.19.19
```

**Comment by kevrowe** [comment]
Updating to `gatsby@2.19.40` resolved this for me
