### ISSUE TITLE
Prefix-paths not always prefixing static assets on build

### ISSUE THREAD

**Issue by ReillyBova** [gatsbyjs/gatsby#21975]
## Description
When I run `gatsby build --prefix-paths` after running `gatsby clean`, all of the paths in my site are appropriately link; however, if I run `gatsby build --prefix-paths` again (without cleaning), certain assets lose their path prefix. This affects the assets that have a link starting with `/static/` in particular, and effects objects across my site, such as images loaded with Gatsby Image in JSX, as well as images and files generated from markdown.

### Steps to reproduce

1. Use a prefix path, and add an image somewhere in your gatsby site
2. Run `gatsby clean`
3. Run `gatsby build --prefix-paths`
4. Inspect the link to that image in the generated ssr html file in `/public/`. It should have the form `PREFIX_PATH/static/...`
5. Run `gatsby build --prefix-paths` again
6. Return to that image in the generated ssr html file in `/public/`. It should now have the (incorrect) form `$static/...`

This is happening with a class website site I'm building for fun: https://github.com/ReillyBova/COS426-Website

### Expected result

Prefix paths should always prefix paths! It should not be necessary to clean the compiled files and build from scratch every time.

### Actual result

Prefix paths does not work for certain assets when the build is not 100% fresh.

### Environment

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    npm: 6.14.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.122
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.27 => 2.19.27 
    gatsby-image: ^2.2.42 => 2.2.42 
    gatsby-plugin-layout: ^1.1.22 => 1.1.22 
    gatsby-plugin-manifest: ^2.2.42 => 2.2.42 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6 
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3 
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22 
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5 
    gatsby-plugin-sitemap: ^2.2.27 => 2.2.27 
    gatsby-remark-copy-linked-files: ^2.1.37 => 2.1.37 
    gatsby-remark-images: ^3.1.44 => 3.1.44 
    gatsby-remark-katex: ^3.1.24 => 3.1.24 
    gatsby-remark-prismjs: ^3.3.32 => 3.3.32 
    gatsby-remark-smartypants: ^2.1.21 => 2.1.21 
    gatsby-source-filesystem: ^2.1.48 => 2.1.48 
    gatsby-transformer-remark: ^2.6.53 => 2.6.53 
    gatsby-transformer-sharp: ^2.3.16 => 2.3.16 
  npmGlobalPackages:
    gatsby-cli: 2.8.29
    gatsby: 2.19.27

**Comment by TylerBarnes** [comment]
Hi @ReillyBova , thanks for opening an issue and for providing a reproduction!
I pulled down your repo, ran `gatsby build --prefix-paths && gatsby serve --prefix-paths` and noticed your path prefix is missing a leading slash.
That means Gatsby was trying to serve from `http://localhost:9000courses/archive/spring20/cos426` (notice `:9000courses`)

I adjusted your Gatsby config like so `pathPrefix: '/courses/archive/spring20/cos426'`, and ran the build a few times, serving the site in between each build, but I wasn't able to reproduce.
I believe this is related to that leading slash, can you update it and see if it fixes it for you?

Thanks!

**Comment by ReillyBova** [comment]
Yes this worked! Thank you so much @TylerBarnes!

**Comment by ReillyBova** [comment]
WAIT! This is actually still an issue. When I added a new page to my app, and when I modified an old page, all the static assets on these pages were not assigned path prefixes. I had to run `gatsby clean` to get the site to build properly.

**Comment by TylerBarnes** [comment]
@ReillyBova you may have had improperly cached assets from your earlier builds. If you run a few builds after you ran `gatsby clean` do things keep working?

**Comment by ReillyBova** [comment]
Unfortunately, the buggy behavior is not straightforward. I have to run Gatbsy clean frequently (basically every build) to get things working. Using the path prefix you suggested, and having updated all my packages since the original post, I observe the following:

Broken path 1:
1. Starting with `npm run clean`
2. I run `develop` and modify one of my markdowns. (I think this can be on any page though; I haven't checked to see what happens if I just change a React component)
3. I finish my changes and run `npm run build; npm run serve` (these scripts include the prefix-paths option in my package.json)
4. I load up `http://localhost:9000/courses/archive/spring20/cos426/assignments`
5. Images loaded with Gatsby Image are all missing :(
6. I look in the .html files in `/public` generated by the build, and observe that the images loaded with Gatsby Image do **not** contain their path prefix. Searching `/public` for `="/static` returns over 2k results.
7. `npm run clean; npm run build; npm run serve`
8. Everything is fixed!

Broken path 2:
1. Starting with `npm run clean`
2. I run `npm run build; npm run serve`
3. Everything looks fine
4. I modify one of my markdowns on some page that contains images
5. I rerun `npm run build; npm run serve`
6. The images on that page are broken! (same linking issue as before)
7. `npm run clean; npm run build; npm run serve`
8. Everything is fixed!

Broken path 3:
1. Starting with `npm run clean`
2. I run `npm run build; npm run serve`
3. Everything looks fine
4. I switch to develop: `npm run develop`
6. All the Gatsby Images on the develop build of the site are broken because they contained prefixed paths that haven't been "unprefixed" when switching back to develop from the production build.
7. This is where things get fuzzy, but I think if I run `npm run develop` again, the links are fixed. I did something that worked, but unfortunately I was not able to replicate this behavior when going from develop to production, which is the critical issue and the direction of the other two broken paths.

In any case, my private build of the site ([available in production here](https://www.cs.princeton.edu/courses/archive/spring20/cos426/)) has so many images that running a build after `npm run clean` takes a *really really long time* since it has to completely reprocess all the images. It would be really great to be able to make changes to the site, and switch between dev and prod, without having to completely rebuild from scratch everytime.

**Comment by TylerBarnes** [comment]
Hi @ReillyBova, I just had a chat with Michal from the core team about this.
He said that the problem is that running in develop between your builds is what causes this issue because develop interferes with the cached data. You should be able to use `pathPrefix` in production and test locally without it to get around this problem. Apparently this is currently not something we're able to fix due to the way everything is set up.

**Comment by ReillyBova** [comment]
Ah gotcha — that makes sense. Thank you!

**Comment by brootle** [comment]
having a problem with pathPrefix when deploying to Github pages, the pathPrefix is not added to images that are used from static folder, I checked generated urls that are on gh-pages, the actual files are there... when importing images into same component via **import** everything is fine, pathPrefix is added

**Comment by philsinatra** [comment]
Same problem for me. All assets in the `static` directory do not include the `pathPrefix` in the production build. 

```bash
$ gatsby clean
info Deleting .cache, public
info Successfully deleted directories

$ gatsby build --prefix-paths
```

Browser console reports:

    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)
    https://mydomain/data/myfile.json

The rest of the site is running properly from `https://mydomain/subfoler/another-subfolder/`

**Comment by brootle** [comment]
@philsinatra the solution would be to check if you are in production or development environment and add pathPrefix to those assets that are in static folder if you are not in development, here is pretty nice code to solve that Gatsby bug https://github.com/gatsbyjs/gatsby/issues/8479#issuecomment-576067799

**Comment by philsinatra** [comment]
I was able to use a Gatsby function `withPrefix` to solve this without having to incorporate the production/development check.

```javascript
import { withPrefix } from 'gatsby'
```

Had to wrap each reference to a static asset in this function call. For example:

```javascript
<link
  rel="apple-touch-icon"
  sizes="57x57"
  href={withPrefix('/apple-icon-57x57.png')}
/>
```

This solved the issue, assets load properly with the correct paths in both development and production mode.

**Comment by brootle** [comment]
Thank you @philsinatra! This is the best solution, I just checked Gatsby docs and found location where this function is mentioned! If guys from Gatsby team are reading this, it would be great if they moved info regarding withPrefix function to documentation section that describe deployment.

**Comment by ibrent** [comment]
This feature still doesn't work correctly.  Even after CLEAN and building with the prefix-path, my app related JS and CSS are still going to the ROOT and not a sub directory as I listed in pathPrefix: `/subdirectory`.

All it does is move my static assets into the subdirectory.  My app js etc are all at the root of the domain, and get a 404 unfound asset error.  This doesn't work as listed on this page:  https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/path-prefix/

Please review and QA this feature.  Thanks.
