### ISSUE TITLE
WSL problems while npm installing

### ISSUE THREAD

**Issue by pvdz** [gatsbyjs/gatsby#21980]
Split from https://github.com/gatsbyjs/gatsby/issues/21879

There appears to be an issue that's specifically hitting WSL users when they're trying to install a starter. Reported by @garethiv and supported by @talves 

## Steps to reproduce

1.Install WSL Ubuntu 18.04
2.Curl install npm
3.Install gatsby with npm install -g gatsby-cli
4.New gatsby app with gatsby new blog https://github.com/gatsbyjs/gatsby-starter-hello-world

See also the full npm log as reported in https://github.com/gatsbyjs/gatsby/issues/21879#issuecomment-595109870

## Bisect

As the original report mentioned, first version to regress is 2.19.22. 

Root cause of this problem is yet to be determined.

## Workaround

Downgrading to .21 seems to be a workaround.

Clearing the `~/.npm` and `node_modules` and running npm again MIGHT be a viable workaround for `.22` but I'm not sure yet since I think that's more like a viable workaround for the other problem mentioned in that ticket. This needs verification.

I do NOT think this issue is related to caching as Gatsby never runs in this case.

**Comment by pvdz** [comment]
Haven't seen this report any further. Original commenters haven't posted new responses. I'm closing this.

**Comment by talves** [comment]
Only saw this one more time. Caused by default on new file creation the wrong file encoding (utf8 with BOM) when creating files.

**Note to solve:** Make sure the default setting inside VSCode (File > Preferences > Files : Text Editor : Encoding) is set to a compatible encoding (utf8).
