### ISSUE TITLE
Gatsbyjs of webpack config ？

### ISSUE THREAD

**Issue by Chad97** [gatsbyjs/gatsby#21981]
```js
var webpack = require('webpack');

exports.onCreateWebpackConfig = ({ stage, loaders, actions, plugins }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /react-cplayer/,
            use: loaders.null(),
          },
        ],
        plugins: [
          new webpack.optimization.UglifyJsPlugin({
            uglifyOptions: {
              compress: {
                warnings: false,
                drop_console: true,//console
                pure_funcs: ['console.log']//delete console
              }
            },
            sourceMap: config.build.productionSourceMap,
            parallel: true
          }),
        ]
      },
    })
  }
}
```
- Error： TypeError: Cannot read property 'UglifyJsPlugin' of undefined

How do I configure webpack `plugins` —— `UglifyJsPlugin`?

**Comment by pieh** [comment]
Few things here:
 - if you want to target browser bundles - `stage` should be `build-javascript` (`build-html` is for static .html files)
 - we use Terser plugin (not uglify js) and you also need to use `optimization.minimizer` and not `plugins`

Here's working example:

```js
exports.onCreateWebpackConfig = ({ getConfig, stage, actions, plugins }) => {
  if (stage === "build-javascript") {
    const currentConfig = getConfig()

    // sanity check so we don't access undefined
    if (
      currentConfig.optimization &&
      currentConfig.optimization.minimizer &&
      currentConfig.optimization.minimizer.length
    ) {
      // replace instance of TerserPlugin with new one with custom options
      currentConfig.optimization.minimizer = currentConfig.optimization.minimizer.map(
        plugin => {
          if (plugin.constructor.name !== `TerserPlugin`) {
            return plugin
          }

          return plugins.minifyJs({
            terserOptions: {
              compress: {
                ecma: 5,
                pure_funcs: [`console.log`],
              },
            },
          })
        }
      )

      actions.replaceWebpackConfig(currentConfig)
    }
  }
}
```

The options for terser are largely compatible with uglify options - but you can check those in https://github.com/terser/terser#minify-options. In here I removed `console.log`, but `drop_console` can be used also to drop all `console` methods usage.

**Comment by Chad97** [comment]
- Thank you very much for your answer ！
- Can solve my problem！[emoji](good)

This configuration is not the same as `"webpack"`, I need to study it again

**Comment by pieh** [comment]
The `plugin.minifyJS` is gatsby wrapper that uses `TerserPlugin` - so it actually is pretty much what Terser / webpack documentation is doing ( https://webpack.js.org/plugins/terser-webpack-plugin/ ), just using Gatsby APIs
:
https://github.com/gatsbyjs/gatsby/blob/627d552f2df48ab6354cb0e271338cc0dc56d1ea/packages/gatsby/src/utils/webpack-utils.js#L5
https://github.com/gatsbyjs/gatsby/blob/627d552f2df48ab6354cb0e271338cc0dc56d1ea/packages/gatsby/src/utils/webpack-utils.js#L514-L543

The additional thing that replaces default setting is definitely bit different than using/configuring webpack yourself. But in the end webpack config ends up similar as in webpack docs when it comes to minimization related options
