### ISSUE TITLE
[gatsby-source-wordpress] 'htaccess_user' undefined

### ISSUE THREAD

**Issue by chrisgeary92** [gatsbyjs/gatsby#2199]
Just trying this out with a self hosted copy of WordPress at https://indigotree.co.uk with the following plugin configuration:

```
plugins: [
  {
    resolve: `gatsby-source-wordpress`,
    options: {
      baseUrl: `indigotree.co.uk`,
      protocol: `https`,
      hostingWPCOM: false,
      useACF: false,
      verboseOutput: true
    }
  }
]
```

But running `npm run develop` throws the following error:

```
error Plugin gatsby-source-wordpress returned an error
TypeError: Cannot read property 'htaccess_user' of undefined

  - fetch.js:69 _callee$
    [indigotree-co-uk]/[gatsby-source-wordpress]/fetch.js:69:73

  - fetch.js:207 fetch
    [indigotree-co-uk]/[gatsby-source-wordpress]/fetch.js:207:18

  - gatsby-node.js:75 _callee$
    [indigotree-co-uk]/[gatsby-source-wordpress]/gatsby-node.js:75:20
```

I also tried setting `auth` to `{}` and to `false`, which gets me a little further through the process, but fails again wither other errors.

**Comment by sebastienfi** [comment]
You need the `auth` section of the config even if you don't use it.
The fact that this auth object is required should be removed.
