### ISSUE TITLE
How to add css classes?

### ISSUE THREAD

**Issue by kennetpostigo** [gatsbyjs/gatsby#220]
Hello,

I'm currently working on a site with gatsby and I wanted to know how to add a css class to the markdown that will be rendered to a react-component.

for example:
```md
# List
1. one
2. two
3. three
```

how can I add a class to the `h1` and `ol` with gatsby?

**Comment by KyleAMathews** [comment]
Take a look at the Kitchen Sink Starter — it shows how to add a markdown-it plugin which adds syntax for adding classes to markdown.

http://gatsbyjs.github.io/gatsby-starter-default/markdown/
