### ISSUE TITLE
gatsby-plugin-offline file won't be precached despite config

### ISSUE THREAD

**Issue by smoke-indica** [gatsbyjs/gatsby#22001]
## Summary

Despite configuring a larger precache limit, I still get a precache warning during deployment on render.com

## Relevant information

When deploying to render I get the following error:

```
Mar 6 12:27:29 AM  success Building static HTML for pages - 189.683s - 10359/10359 54.61/s
Mar 6 12:27:31 AM  warn commons-c3f7ebcacc44b1b8f9fa.js is 6.61 MB, and won't be precached. Configure
Mar 6 12:27:31 AM  info Generated public/sw.js, which will precache 7 files, totaling 200373 bytes.
```

I've attempted to configure the option to expand this precache limit to no success:

```
    {
      resolve: `gatsby-plugin-offline`,
      options: {
        workboxConfig: {
          maximumFileSizeToCacheInBytes: 1000000
        },
      },
    },
```

Is my configuration incorrect?

### Environment (if relevant)

Render.com

### File contents (if changed)

`gatsby-config.js`: 

```
    {
      resolve: `gatsby-plugin-offline`,
      options: {
        workboxConfig: {
          maximumFileSizeToCacheInBytes: 1000000
        },
      },
    },
```

**Comment by vladar** [comment]
I don't have too much context here but from the first look, it seems that the limit you are trying to set is still too low:

```js
maximumFileSizeToCacheInBytes: 1000000
```

This is slightly less than `1mb`. Your file is `6mb`. Try adding one more `0` to this limit?

```js
maximumFileSizeToCacheInBytes: 10000000
```

And just out of curiosity, what kind of site are you working on? `6mb` sounds like a huge chunk of javascript.

**Comment by smoke-indica** [comment]
You're right, after changing it I'm getting the following precache message now `info Generated public/sw.js, which will precache 8 files, totaling 6811195 bytes.` (no error).

My site is blog, using the lumen starter
