### ISSUE TITLE
Error: Cannot find module 'relay-compiler/lib/RelayCompilerContext' on fresh install

### ISSUE THREAD

**Issue by justan0therdave** [gatsbyjs/gatsby#2200]
I'm just starting the tutorial part one and get this error message on `gatsby develop`

`error A local install of Gatsby exists but failed to load.
`
`  Error: Cannot find module 'relay-compiler/lib/RelayCompilerContext'
`  
` - module.js:11 require
`   internal/module.js:11:18
  
` - query-compiler.js:37 Object.<anonymous>
`  [tutorial-part-one]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:37:29
  
`  - module.js:11 require
`   internal/module.js:11:18
` 
` - query-watcher.js:22 Object.<anonymous>
`  [tutorial-part-one]/[gatsby]/dist/internal-plugins/query-runner/query-watcher.js:22:21`

Not a great start to the tutorial

**Comment by iv-mexx** [comment]
I've got the same problem after running `npm install` again (after switching branches). 
I also had another tutorial project where everything was still working until I ran `npm install` there as well as well as a test...

**Comment by TomiTakussaari** [comment]
I also encountered this today, while trying out different Gatsby versions.

Version 1.4.0 of relay-compiler was apparently just released, with changes like this.

As a workaround, you can add "relay-compiler": "1.1.0" as a direct dependency in your package.json. Probably anything pre 1.4.0 will work.

Problems like this seem to be quite common in npm world, as everyone is just depending on ^x.y.z, and hoping that it will be future-proof.

**Comment by justan0therdave** [comment]
Just running `npm install` fixed this for me.

**Comment by ukaric** [comment]
Yeah there is error confirmed I updated `gatsby-cli` and tried a fresh run it throws an error. Running `npm i` or `yarn install` does fix the issue.

**Comment by KyleAMathews** [comment]
@TomiTakussaari yeah looks like you're right that the new version of Relay Compiler broke us. I have a PR up to pin us to the last version of Relay Compiler.

Generally ^ is safe and helps the ecosystem move along quickly. We could investigate a Greenkeeper like solution where we pin more and then have PRs auto-created for updates which run against our tests. But this is also a ton more work for questionable gain given I think this is only the second time in the 2+ years of Gatsby that a dependency's minor update has broke Gatsby.

https://github.com/gatsbyjs/gatsby/pull/2202

**Comment by KyleAMathews** [comment]
I published a new Gatsby release. Lemme know if there's any more trouble.

**Comment by iv-mexx** [comment]
Works again, thx @KyleAMathews 👍

**Comment by spences10** [comment]
I was having this error message too and I installed and reinstalled gatsby and still got the same error message, it wasn't until I used yarn that it started working?
