### ISSUE TITLE
Direct-ID lookup for nodes in graphql fails in some instances

### ISSUE THREAD

**Issue by me4502** [gatsbyjs/gatsby#22004]
## Description

When querying a single node by a direct-ID lookup, the query sometimes returns null. Querying for the whole list, and filtering by something such as slug finds the document fine, with the same ID. 

Thanks to @DSchau for helping me debug this.

I had a feeling it was related to https://github.com/gatsbyjs/gatsby/issues/20609, but after testing on a version from before that change (2.18.22), the issue still occurs.

### Steps to reproduce

I have no idea how to reliably reproduce this sorry. It has randomly occurred on my project. It appears to just be the one node, on a page with >10k pages (so therefore a lot of nodes are in the db)

This query on the site shows it in a simple way, however.

![image](https://user-images.githubusercontent.com/546754/76053249-5f8e3d80-5fb8-11ea-9a71-5c54c718f534.png)

### Expected result

The `contentfulBlogPost` query should be able to find a node, as the above query has proven it exists and provided an ID.

### Actual result

A direct-ID lookup for this object does not work. Looking up by other things, such as contentful_id, do work.

### Environment

```

  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - ~/.npm/bin/node
    Yarn: 1.22.0 - ~/.npm/bin/yarn
    npm: 6.13.6 - ~/.npm/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Firefox: 70.0.1
    Safari: 13.0.5
```

**Comment by vladar** [comment]
Can you clarify the "random" part? I mean - if you run this query twice in GraphiQL - do you get different results? Or maybe some action during the development session changes the behavior?

**Comment by me4502** [comment]
Sorry, by random I meant that I couldn’t find any reason why this one is the one affected.

It is always the same node, and it always fails

**Comment by vladar** [comment]
Is it possible to get access to your project so that we could take a look locally? I'll post an email in the next message (will delete later)

**Comment by vladar** [comment]
vladimir@gatsbyjs.com

**Comment by me4502** [comment]
I've looked into it and I don't think we're able to provide access to the project sorry. It's in a monorepo with a few other intertwined projects, as well as it uses a few libraries from private NPM repos.

**Comment by vladar** [comment]
Hi @me4502

I understand but the problem is that it is nearly impossible to debug this without reproduction. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

[reproduction]: https://gatsby.dev/reproduction

**Comment by me4502** [comment]
So we've had this occur again in a way that cannot be worked around.

Using contentful, rich text fields are a separate node, accessed through `content___NODE`. Direct ID lookups are failing for some of these, and therefore the `content___NODE` field comes up as `null`.

I understand this is almost impossible to debug without a minimal reproduction, however I have not been able to create one reliably. The best I can do is using the exact same data so that the node store is in the same state. However this is still not minimal and is very intertwined with systems that can't easily be shared.

I'm happy to debug and solve this, my main reason for asking again now is to work out if anyone on the Gatsby team has any ideas about what areas of the codebase could cause something like this. I've been looking into it for a few days and haven't been able to find a concrete cause.

**Comment by benrobertsonio** [comment]
@me4502 There are some known issues with Contentful's rich text feature, documented below, which might give some direction!

- https://github.com/gatsbyjs/gatsby/pull/15084
- https://github.com/contentful/rich-text/issues/94

**Comment by me4502** [comment]
@benrobertsonio Those issues are referring to the partial sync the API does on update, we’re using the option to force a full sync to get around that issue.

This issue is outside of the Contentful plugin from what I can tell. The data is all there correctly in Gatsby’s node store, it just cannot be queried by ID from graphql.

**Comment by vladar** [comment]
I am curious if it is the same with `in` operator? i.e.

```graphql
contentfulBlogPost(id: { in: ["your-mysterious-id"] }) {
  id
}
```
(at the moment this bypasses id indexes). Also worth trying `regex` by partial match. Just to collect a bit more data.

And just to clarify - you can't reproduce it on the same contentful space but with some simple starter (using GraphiQL to check the results)?

**Comment by me4502** [comment]
Using `in` or `regex` also fail, they don't find the node.

I haven't specifically tested with just the contentful space, as the issue doesn't only occur with contentful data. It happens to pretty much any type of node, just a very small percentage of them.

I will do a test with just that shortly.

**Comment by me4502** [comment]
I just confirmed that the same issue occurs with a fresh `gatsby-default-starter`with /just/ `gatsby-source-contentful` setup for this space.

**Comment by vladar** [comment]
Sounds like a repro? Can you share it? As far as I understand we need a temporary content delivery token only to see it?

**Comment by me4502** [comment]
Thanks, I've just emailed the key and other required info to the email you posted earlier

**Comment by vladar** [comment]
Surprisingly, I can't reproduce it locally. Tried this query:

```graphql
{
  allContentfulBlogPost(filter:{slug:{eq:"download-youtube-videos"}, node_locale:{eq:"en-US"}}) {
    nodes {
      id
      contentful_id
      title
    }
  }
  contentfulBlogPost(id:{eq:"cd0ea374-9b02-5fdd-8294-08fb642c741d"}) {
    id
    title
  }
}
```

And got the expected result:
```json
{
  "data": {
    "allContentfulBlogPost": {
      "nodes": [
        {
          "id": "cd0ea374-9b02-5fdd-8294-08fb642c741d",
          "contentful_id": "blog-download-youtube-videos",
          "title": "How to Download YouTube Videos, Step-by-Step"
        }
      ]
    },
    "contentfulBlogPost": {
      "id": "cd0ea374-9b02-5fdd-8294-08fb642c741d",
      "title": "How to Download YouTube Videos, Step-by-Step"
    }
  }
}
```
The screenshot:

![screenshot](https://user-images.githubusercontent.com/115628/80209055-8a614d80-865b-11ea-847d-748a9a3ec06a.png)


Maybe it is some other node now? Can you share your steps?

**Comment by me4502** [comment]
I'm on my phone so don't have the exact query, but I basically queried for `allContentfulBlogPost`, with a filter on `content` equalling `null`.

This gave me a list of all the ContentfulBlogPost nodes that had a content___NODE that was unable to be resolved

**Comment by vladar** [comment]
Did some digging. A rich text node is a child of a blog post node. And we have a weird sequence of calls in contentful plugin:

```
createNode(blogPostNode)
createNode(richTextNode)
createNode(blogPostNode)
```

So the same blog post node is created twice. The problem though that when we re-create existing node Gatsby deletes all of its children (assuming they will be re-created too).

But contentful plugin never re-creates them hence we get the blog post without text node. Still digging why contentful calls `createNode` twice for the same blog post node.

**Comment by vladar** [comment]
Ok, it looks like you have identical `contentful_id` (and hence node `id`) for blog posts AND related assets. As a result, we face a weird collision that causes this. In reality the sequence of calls is:

```
createNode(blogPostNode)
createNode(richTextNode)
createNode(blogPostAssetNode)
```

The `blogPostAssetNode` has the same id as `blogPostNode`, so Gatsby confuses it with `blogPostNode` and clears children of the blog post.

Ideally, ids should be unique for a single contentful space. But contentful source plugin could have namespaced it with content type to avoid collisions like this.

A PR is welcome - it shouldn't be too complex! Basically add `type` to this function (and adjust all usages):

https://github.com/gatsbyjs/gatsby/blob/c350f596c424a2df032e98a6622596976e957f00/packages/gatsby-source-contentful/src/normalize.js#L100-L103

**Comment by me4502** [comment]
Ah, thanks - I’ll submit a PR on Monday.

When testing this new issue I used getNode to see if it still existed and it retuned a result, which a conflicting ID would explain.

For the original issue, using just the Contentful data made it return different broken pages so I’ll try finding which ones are affected with just that data, thanks
