### ISSUE TITLE
How to display source file for conflicting fields types?

### ISSUE THREAD

**Issue by henricazottes** [gatsbyjs/gatsby#22016]
Hi,
When building my site containing a lot of `.md` files full of frontmatter, I get warnings about conflicting field types. This is a valuable information, but it's missing one thing: which files are conflicting.

I've seen this conversation [here](https://github.com/gatsbyjs/gatsby/pull/3905) where you can see screenshots with the path to the source file.
![Screenshot](https://camo.githubusercontent.com/78ff255a588088b4b424d69e4973e51b12da2086/68747470733a2f2f636c2e6c792f33753357336d304d304c33542f646f776e6c6f61642f496d616765253230323031382d30342d31312532306174253230342e30352e3235253230504d2e706e67)

But for me `source` is not showing up.
``` bash
MarkdownRemark.frontmatter.mepheader.provenance.prov_number:
 - type: object
   value: { anote: [Object] }
 - type: string
   value: 'p. 264'
MarkdownRemark.frontmatter.head:
 - type: object
   value: { dateline: 'sans date', persname: [Object], object: 'Dessin de M. Isabey de la manufacture des frères Sevennes à Rouen.' }
 - type: string
   value: '[1133]'
```

Digging a little where the message is actually prompted, I've found that the source line is displayed only if the node has a description:

[type-conflict-reporter.js](https://github.com/gatsbyjs/gatsby/blob/3e91b0c9f5184dd5b5da4d03ae12b9d8ea4e94f0/packages/gatsby/src/schema/infer/type-conflict-reporter.js#L92)
``` javascript
    report.log(
      `${this.selector}:${sortedByTypeName
        .map(
          ([typeName, { value, description }]) =>
            `\n - type: ${typeName}\n   value: ${formatValue(
              value
            )}${description && `\n   source: ${description}`}` // <-- Here
        )
        .join(``)}`
    )
```
I've quickly looked around but didn't find what is this description. On the node interface [documentation page](https://www.gatsbyjs.org/docs/node-interface) no sign of it.

I think adding this description is not the way to go, but I'm missing leads.

Any suggestion how to proceed?

**Comment by vladar** [comment]
Hi @henricazottes !

Thanks for this question. This sounds like a reasonable thing to have. The PR you linked is for Gatsby v1. But I did some digging and looks like we stopped displaying the source after #16091.

There is actually this comment: https://github.com/gatsbyjs/gatsby/pull/16091/files#r316047900 which hints that it is probably possible to restore this behavior.

@freiksenet Do you remember why it was removed in the first place?

Given what I see `gatsby-source-filesystem` still sets `description` so the scope of the change seems to be relatively narrow.

We'll be happy to accept a PR for this change 💜 Feel free to ping me for any help or advice if you decide to tackle it!

**Comment by henricazottes** [comment]
Interesting!

On my part I've found that [prepareConfilctExample](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer/build-example-data.js#L158-L161) never returns any parent:

``` js
    return {
      type: typeNameMapper(type),
      value: reportedValueMapper(type),
    }
```
And as the description is found in the parent (see [addExample](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer/type-conflict-reporter.js#L82)):
``` javascript
  addExample({
    value,
    type,
    parent
  }) {
    this.types.set(type, {
      value,
      description: findNodeDescription(parent)
    });
  }
```
I guess it explains why it's not displayed.

However we do have access to `first` in the descriptor given to `buildExampleValue`, which looks like a `nodeId`:
``` json
// descriptor
{
  "string": {
    "total": 1103,
    "first": "31b3aa77-7e13-5954-82b7-6661162f20d6",
    "example": "sans date",
    "empty": 2,
  }
}
```
With that and the `node api helper` it should be pretty easy to access the parent (if this nodeId looking stuff is the parent Id). But as I don't have the big picture of that block I don't know where is the best place to inject/retrieve it.

@vladar if you give me some directions it would be a pleasure to make a PR :)

**Comment by rbelow** [comment]
If @freiksenet gives a good reason why it was removed it would mean that this behavior cannot be restored easily?

**Comment by henricazottes** [comment]
You're right, I'll wait for his answer before investigating more

**Comment by vladar** [comment]
@henricazottes You are right about `first` - it is a node id that you can use to find a root ancestor node. I guess the best advice I can give is to try to restore [this line]( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer/type-conflict-reporter.js#L25)

The implementation of this function still exists [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/node-model.js#L371) but it is not easily accessible from type conflict reporter anymore. I suspect it was the main reason for the change.

So you will probably have to re-implement it using [node store](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/db/nodes.js) directly. I would suggest putting this new implementation in the utils folder for now as a standalone utility function.
