### ISSUE TITLE
How to mutation my data?

### ISSUE THREAD

**Issue by Marksteinsong** [gatsbyjs/gatsby#22012]
## Summary

Can the graphql client of Gatsby.js used like Apollo client ?
## Relevant information

I want to make a comment on my  blog ,Implement login and sign up function etc.

And I dont want to use 3rd platform , i want to control my data 100%。

**Comment by jonniebigodes** [comment]
@Marksteinsong if you mean using Gatsby data layer and by that the graphql portion of it to apply a crud functionality in your site, then no. Gatsby's data layer is a "one way street" it's designed to pull in data, if you want to use mutations and/or subscriptions, you'll have to use something like Apollo to handle the mutations aspects of the data. Going about this in portions, login/signup you could take a look at [this](https://auth0.com/blog/securing-gatsby-with-auth0/) or [this](https://swizec.com/blog/gatsby-auth0/swizec/8895), for comments it will boil down on how you want to implement that feature

**Comment by vladar** [comment]
Hey @Marksteinsong 

This is a good question! Gatsby data layer exists only during build time. After that, it is transformed into HTML and plain JSON files which you can deploy as a static site.

So at the moment if you want to use Apollo on the client, you need a separate GraphQL server. Check out [this talk](https://youtu.be/wNUg1jpj9T0?list=PLz8Iz-Fnk_eQGt4-VFFCXYuYcuKaw4F07) on this subject and this [starter](https://github.com/jlengstorf/gatsby-with-apollo).

Also, we had several similar questions in the past which might be of your interest: 
#21616
#10230
(but they only touch querying aspect, not mutations)

One of the other options is using 3rd-party services for data mutations. Here is a [simple example](https://www.gatsbyjs.org/docs/building-a-contact-form/) of a form submission process using getform.io.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by EosWaxDev** [comment]
I'm sorry but this is not really useful. That's why you call this solution secure. I get it. I won't use it again.
All this gatsby offers is promises and marketing.
