### ISSUE TITLE
How I can show Yandex Ads into MDX-posts

### ISSUE THREAD

**Issue by nikolayval** [gatsbyjs/gatsby#22030]
Hello!

In some time ago I send question, how I can show Yandex Ads into my Gatsby MDX-posts. It's Google Adsense analog from Russia. 

Here is my question: https://github.com/gatsbyjs/gatsby/issues/21853. Also I ask my question in Gatsby Discord group. 

But I don't get answer to my question(( Please, can you look and help me? https://github.com/gatsbyjs/gatsby/issues/21853

Sorry for bad English, I'm from Russia and still learning. Thank you for gatsby project and your work! I love you all!

**Comment by pvdz** [comment]
Please don't open a new issue if you already have another issue about this. As Blaine mentioned, you can continue the conversation there. He closed it as there's not a problem with Gatsby.
