### ISSUE TITLE
[Catch errors] gatsby build returns success even on failure to build

### ISSUE THREAD

**Issue by eduaquiles** [gatsbyjs/gatsby#2203]
I was facing issue #2200 but our build agent kept reporting success because `gatsby build` was returning 0 even though the command was failing.

```
» ./node_modules/.bin/gatsby build
error A local install of Gatsby exists but failed to load.

  Error: Cannot find module 'relay-compiler/lib/RelayCompilerContext'
  - module.js:20 require
    internal/module.js:20:19
  - query-compiler.js:37 Object.<anonymous>
    [myproj]/[gatsby]/dist/internal-plugins/query-runner/query-compiler.js:37:29
  - module.js:20 require
    internal/module.js:20:19
  - query-watcher.js:22 Object.<anonymous>
    [myproj]/[gatsby]/dist/internal-plugins/query-runner/query-watcher.js:22:48
  
» echo $?
0

```

**Comment by KyleAMathews** [comment]
Hey sorry this is happening! Thanks for bringing up the issue.

There are many places where we catch errors and exit with an error code. Could you put together a PR that catches this sort of error and exits correctly?

**Comment by jmoujaes** [comment]
I can't seem to reproduce this. Is it still an issue?

**Comment by KyleAMathews** [comment]
Closing this issue as it's fairly old and we have far too many open issues! If you have additional problems in this area, please open a new issue!
