### ISSUE TITLE
[chore]: migrate gatsby-core-utils to TypeScript

### ISSUE THREAD

**Issue by danielkov** [gatsbyjs/gatsby#22041]
### Description

This is a ticket to keep track of all the individual PRs for each file required to update this package to TypeScript.

Umbrella: #22040

**Comment by MichaelDeBoey** [comment]
This is already tracked in #21995

**Comment by danielkov** [comment]
@MichaelDeBoey I wanted to keep track of `gatsby-core-utils` related changes separately for convenience. Both tickets are mentioned in PRs. Is this something I shouldn't do?

**Comment by MichaelDeBoey** [comment]
I don't see any benefits in tracking the same thing twice

**Comment by blainekasten** [comment]
@danielkov No worries on the duplicate issue. It'll be closed soon after we merge all of your PR's :) 

One request that I see consistent on all of your PRs is that we want to change our exports to be named exports and shy away from export default. Can you make that change in all your PRs?

**Comment by blainekasten** [comment]
Also tests are failing. Let me know when you get that fixed up!

**Comment by JustFly1984** [comment]
#22070
