### ISSUE TITLE
gatsby-remark-images: "image has shrunk to nothing" error

### ISSUE THREAD

**Issue by bvaughn** [gatsbyjs/gatsby#2204]
While working on the [React Gatbsy site](https://github.com/facebook/react/tree/gatsby) I found a problem with the `gatsby-remark-images` and certain images on the site. This issue causes Gatsby (prod and dev) to crash when certain images are referenced in markdown files (eg [this one](https://github.com/facebook/react/blob/master/docs/img/docs/perf-exclusive.png) or [this one](https://github.com/facebook/react/blob/master/docs/img/docs/perf-dom.png)). Both of these images are relatively short compared to their width (eg 687 x 32).

The [Gatsby docs for `gatsby-remark-images`](https://www.gatsbyjs.org/packages/gatsby-remark-images/) say:
> Useing the “blur up” technique popularized by Medium and Facebook where a small 20px wide version of the image is shown as a placeholder until the actual image is downloaded.

This means an image originally sized 687 x 32 would get scaled down to a height of < 1 pixel which probably gets rounded to 0 and causes [`shrinkv` to error](https://github.com/jcupitt/libvips/blob/master/libvips/resample/shrinkv.c#L388).

Seems like the Gatsby plug-in should be more robust to this case. I will look into this and hopefully submit a PR.

PS. While poking around I noticed that the `gatsby-remark-images` plugin declares a dependency on `image-size` but it isn't used anywhere in the plugin. (IT _is_ used in `gatsby-plugin-sharp` though.)

**Comment by bvaughn** [comment]
I _think_ a reasonable fix for this _might be_ to make use of the metadata  provided by Sharp and change [`base64Args `](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js#L419-L423) to something like:

```js
  const base64Args = {
    duotone: options.duotone,
    grayscale: options.grayscale,
    rotate: options.rotate,
    height: width / height >= 20 ? 1 : undefined, // Prevent 0 height
  }
```

**Comment by KyleAMathews** [comment]
(thanks for tip on image-size — removed that)
