### ISSUE TITLE
gatsby-transformer-sharp 2.3.17 regression: You can't use childImageSharp together with

### ISSUE THREAD

**Issue by vlknhslk** [gatsbyjs/gatsby#22064]
After updated my previous 'gatsby-transformer-sharp' plugin package - started getting this error below: 

**Actual result**

> You can't use childImageSharp together with index.js — use publicURL instead. The childImageSharp portion of the query in this file will return
> null:

**Enviroment**

>  "@mdx-js/mdx": "^1.5.7",
>     "@mdx-js/react": "^1.5.7",
>     "gatsby": "^2.19.32",
>     "gatsby-cli": "^2.10.2",
>     "gatsby-image": "^2.2.43",
>     "gatsby-plugin-antd": "^2.2.0",
>     "gatsby-plugin-google-tagmanager": "^2.1.26",
>     "gatsby-plugin-intl": "^0.3.3",
>     "gatsby-plugin-less": "^3.0.20",
>     "gatsby-plugin-mailchimp": "^5.1.2",
>     "gatsby-plugin-manifest": "^2.2.44",
>     "gatsby-plugin-mdx": "^1.0.77",
>     "gatsby-plugin-netlify": "^2.1.34",
>     "gatsby-plugin-offline": "^3.0.37",
>     "gatsby-plugin-page-creator": "^2.1.42",
>     "gatsby-plugin-react-helmet": "^3.1.23",
>     "gatsby-plugin-react-helmet-canonical-urls": "^1.4.0",
>     "gatsby-plugin-robots-txt": "^1.5.0",
>     "gatsby-plugin-sass": "^2.1.30",
>     "gatsby-plugin-sharp": "^2.4.7",
>     "gatsby-plugin-sitemap": "^2.2.28",
>     "gatsby-plugin-web-font-loader": "^1.0.4",
>     "gatsby-remark-reading-time": "^1.1.0",
>     "gatsby-source-filesystem": "^2.1.50",
>     "gatsby-transformer-json": "^2.2.27",
>     "gatsby-transformer-remark": "^2.6.55",
>     "gatsby-transformer-sharp": "^2.3.17",
>     "gulp-sass": "4.0.2",
>     "less": "^3.11.1",
>     "node-sass": "^4.13.1",
>     "prop-types": "^15.7.2",
>     "rc-drawer": "^3.1.3",
>     "rc-queue-anim": "^1.8.4",
>     "rc-scroll-anim": "^2.7.4",
>     "rc-tween-one": "^2.6.8",
>     "react": "^16.13.0",
>     "react-dom": "^16.13.0",
>     "react-helmet": "^5.2.1",
>     "react-share": "^4.0.1",
>     "react-visibility-sensor": "^5.1.1",
>     "to": "^0.2.9",
>     "update": "^0.7.4"

**.mdx file**

> ---
> title: Tesla gets OK to produce long-range Model 3 at Chine factory
> date: "2020-04-09T22:12:03.284Z"
> description: "hello"
> featuredImage: "./hero.jpg"
> category: "Deal Of The Week"
> ---
> 
> A little more than two and half years ago, Waymo engineers began working on a hardware sensor suite that would improve upon previous generations and have the capability to work on a variety of vehicles, from self-driving passenger cars to autonomous semi-trucks.
> 
> The autonomous vehicle technology company is now showing off the fruits of its labor, starting with its fleet of all-electric Jaguar I-Pace vehicles.
> 
> Waymo has integrated the next-gen hardware system into the Jaguar I-Pace vehicles and is using them for data collection to train machine-learning models. Waymo will then begin testing the I-Pace vehicles in autonomous mode with a human safety driver behind the wheel. Once Waymo hits that milestone, it will turn to its big-rig trucks. The I-Pace testing on public roads will continue and eventually Waymo employees will be able to hail the vehicles and try them out. The final step will be to roll the I-Pace vehicles into its Waymo One service, which operates in the Phoenix area.
>

**Comment by pvdz** [comment]
This was introduced by https://github.com/gatsbyjs/gatsby/pull/20782
Assigning to @LekoArts

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by vlknhslk** [comment]
<img width="792" alt="Screen Shot 2020-03-25 at 12 15 49 PM" src="https://user-images.githubusercontent.com/4762042/77559281-5e9f4c00-6e92-11ea-90c1-d5052a637a72.png">
