### ISSUE TITLE
Problems with gatsby-source-contentful plugin options:

### ISSUE THREAD

**Issue by jindal368** [gatsbyjs/gatsby#22075]
hii there....
I am not able to understand the error. may be due to short docs of gatsby-source-plugin option:
please help me to identify the problem or provide sufficient docs to move forward.
//Here is my gatsby-config.js

require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
})
module.exports = {
  siteMetadata: {
    title: `Trading-web`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `Vishesh`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      }
    },
    {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: process.env.CONTENTFUL_SPACE_ID,
        // Learn about environment variables: https://gatsby.dev/env-vars
        accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
      }
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
         // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}

//This is the error message..

spaceId: undefined - "spaceId" is required
accessToken: undefined - "accessToken" is required
host (default value): "cdn.contentful.com"
environment (default value): "master"
downloadLocal (default value): false
localeFilter (default value): [Function]
forceFullSync (default value): false
pageLimit (default value): 100
useNameForId (default value): true

not finished onPreBootstrap - 0.110s

thankYou

**Comment by nayres** [comment]
I think this has to do with your dotenv config. Do you have different `.env` files for development, production, etc? 

The `path` option is going to look for different `.env` files dependent on the current `NODE_ENV`. I believe there would be a fallback if environment isn't specified; such as `.env`, `.env.local`.

For example:
`.env.development`
`.env.production`

'require("dotenv").config({
    path: '.env.${process.env.NODE_ENV}',
})'

**Comment by jindal368** [comment]
Thanks for help ... the path is now specified for .env.development

**Comment by coreybruyere** [comment]
@jindal368  - how did you resolve this? I'm getting an undefined `spaceId` and `accessToken when trying to run `serve`. I have a .env.development along with a .env.production. In fact, when I log those variables they're logged to my CLI when I start building but relogged as undefined when the build finishes.

**Comment by jindal368** [comment]
@coreybruyere  make sure that .env is in root directory  or else path specified by you should be correct

**Comment by Meshugah** [comment]
So if you're all using github. Doesn't your **.gitignore** include a **.env** in it? Or are you pushing it to your, I would assume private, repo?

**Comment by lillastar824** [comment]
I have same issue.
Please help me.

**Comment by jindal368** [comment]
@lillastar824 make sure that .env is in root directory or else path specified by you should be correct

**Comment by lillastar824** [comment]
The .env files are in root directory.
