### ISSUE TITLE
yarn.lock is beign ignored

### ISSUE THREAD

**Issue by snitin315** [gatsbyjs/gatsby#22072]
## Description

`yarn.lock` file is being ignored inside `.gitignore` , but I can see that the repository do have yarn.lock file. 

Describe the issue that you're seeing.

### Expected result

`yarn.lock` should not be inside `.gitignore`

What should happen?

remove `yarn.lock` from `.gitignore`

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by nayres** [comment]
Have you pushed `yarn.lock` to be tracked by git prior to ignoring it? If so, git is still tracking the file. You can run:

`git rm --cached .`
`git add .`
`git commit -m "Remove ignored files from git"`

This will update git and your file will no longer be tracked.

**Comment by snitin315** [comment]
What I want to say that the project has `yarn.lock` file,  but we are also ignoring it .

![Screenshot from 2020-03-12 06-51-37](https://user-images.githubusercontent.com/46647141/76478244-05fd9700-642e-11ea-9dbc-204a194c3b4e.png)

corresponding .gitignore -

![Screenshot from 2020-03-12 06-51-55](https://user-images.githubusercontent.com/46647141/76478270-1b72c100-642e-11ea-9518-b5791de213f3.png)
