### ISSUE TITLE
Warning: Parameter fromContext must resolve to a value in pixel units.

### ISSUE THREAD

**Issue by kudabux** [gatsbyjs/gatsby#2207]
Running `yarn dev` throws a strange warning with no stack trace that seems to repeat 50+ times.

<img width="718" alt="screen shot 2017-09-22 at 1 56 10 pm" src="https://user-images.githubusercontent.com/14833732/30760082-54411dd0-9f9e-11e7-9d09-d327a309861b.png">

I should also note this doesn't apparently break anything and I couldn't Google up another example of this happening.

**Comment by KyleAMathews** [comment]
I'd search through your code & code you're pulling in from NPM. `fromContext` and `toContext` aren't used in the Gatsby code base.
