### ISSUE TITLE
gatsby-transformer-sharp gives error - Remove node_modules/sharp/vender when added in config

### ISSUE THREAD

**Issue by B4ljeets1ngh** [gatsbyjs/gatsby#22088]
## Description

So, I am trying to use gatsby-source-drupal and I'm getting :- 
"Error in "/app/node_modules/gatsby-plugin-sharp/gatsby-node.js": 'linux-x64' binaries cannot be used on the 'linuxmusl-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.
" but when i remove this plugin from the gatsby-config.js i get :- 
There was an error in your GraphQL query:
 Unknown type "ImageSharpSizes".
File: node_modules/gatsby-transformer-sharp/src/fragments.js:304:46
### Steps to reproduce

1. I'm using the default gatsby starter generated by gatsby cli ( gatsby new <project name>). 
2. Dockerised the app
3. Then i did npm install gatsby-source-drupal.
4. And then i provided the BaseUrl in the gatsby-souce-drupal options.

### Expected result

it should successfully build pages without any errors

### Actual result

It Should connect without following errors when i add gatsby-transformer-sharp:-
Error in "/app/node_modules/gatsby-plugin-sharp/gatsby-node.js": 'linux-x64' binaries cannot be used on the 'linuxmusl-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.

Error: 'linux-x64' binaries cannot be used on the 'linuxmusl-x64' platform. Pl  ease remove the 'node_modules/sharp/vendor' directory and run 'npm install'.

- libvips.js:67 Object.hasVendoredLibvips
 [app]/[sharp]/lib/libvips.js:67:13
- constructor.js:8 Object.<anonymous>
[app]/[sharp]/lib/constructor.js:8:22
- v8-compile-cache.js:178 Module._compile
[app]/[v8-compile-cache]/v8-compile-cache.js:178:30
 - loader.js:789 Object.Module._extensions..js
internal/modules/cjs/loader.js:789:10
 - loader.js:653 Module.load
internal/modules/cjs/loader.js:653:32
- loader.js:593 tryModuleLoad
 internal/modules/cjs/loader.js:593:12
- loader.js:585 Function.Module._load
internal/modules/cjs/loader.js:585:3
- loader.js:692 Module.require
 internal/modules/cjs/loader.js:692:17
 - v8-compile-cache.js:159 require
[app]/[v8-compile-cache]/v8-compile-cache.js:159:20

- index.js:3 Object.<anonymous>
   [app]/[sharp]/lib/index.js:3:15

- v8-compile-cache.js:178 Module._compile
 [app]/[v8-compile-cache]/v8-compile-cache.js:178:30

 - loader.js:789 Object.Module._extensions..js
 internal/modules/cjs/loader.js:789:10

 - loader.js:653 Module.load
 internal/modules/cjs/loader.js:653:32

 - loader.js:593 tryModuleLoad
 internal/modules/cjs/loader.js:593:12

- loader.js:585 Function.Module._load
internal/modules/cjs/loader.js:585:3

 - loader.js:692 Module.require
 internal/modules/cjs/loader.js:692:17

### Environment

I'm getting an error when i run gatsby info --clipboard, that is "gatsby: command not found"

**Comment by madalynrose** [comment]
* it's likely that `gatsby info --clipboard` didn't run because you didn't have gatsby installed globally. you could try running `yarn gatsby info --clipboard`.
* it seems like your environment is having a hard time installing sharp binaries. here's an issue that might help https://github.com/lovell/sharp/issues/1459#issuecomment-519021235
* as far as the GraphQL error goes, this might be happening because Gatsby auto-includes any package that starts with `gatsby-`. If you're not using sharp explicitly, you could try removing that package from your `node_modules` folder manually and seeing if your code runs.

**Comment by B4ljeets1ngh** [comment]
@madalynrose I removed sharp from node modules and package.json, It is working now thanks mam.
