### ISSUE TITLE
Path attribute in .md front-matter should be relative by default?

### ISSUE THREAD

**Issue by kylegach** [gatsbyjs/gatsby#221]
_This is a suggestion, not a bug._

Given that one of the project’s goals is:

> Intuitive directory-based URLs. The URL of a page is derived from its spot on the file system.

...it seems odd that the path attribute in the front-matter of an index.md file is always treated as absolute.

Imagine I have a directory structure:
```
/pages
    /writes
        /1-hello-world
            index.md
    /another-page
        index.md
```

And the front-matter of `/pages/writes/1-hello-world/index.md` includes:
```
path: "hello-world"
```
(note the lack of starting “/”)

Based on the goal quoted above, I'd expect the resulting URL to be `/writes/hello-world`. Currently, though, the resulting URL is `/hello-world`.

I realize I can simply leave off the path attribute (which results in `/writes/1-hello-world`), but I like using a preceding number or date to keep the pages in the correct order in the filesystem, and I would like that number or date to _not_ be in the URL. Right now, the workaround is to add a path like “writes/hello-world”.

For people that like the current behavior, using an absolute instead of relative path could provide that.

I’m just diving into this stuff, but if someone can point me in the right direction, I’ll try to investigate further toward an eventual PR.

I also realize this is breaking change, so maybe it should just stay as-is.

**Comment by KyleAMathews** [comment]
Hmmm... interesting point. I don't have a great intuition for this as I don't regularly hard-code paths in markdown files (part of my reason for wanting to derive urls from the directory position ;-)).

@gatsbyjs/gatsby-core-maintainers any thoughts?

**Comment by KyleAMathews** [comment]
(there's also I should note the poorly documented rewritePath where you can programmatically rewrite paths to remove leading values from the path which is [what I do on my blog](https://github.com/KyleAMathews/blog/blob/e590c31a1b0f9f72b3725f40664cf064fd4595f6/app.coffee#L11))

**Comment by kylegach** [comment]
That’ll probably work for my needs just fine. Thanks!

**Comment by michaeljdeeb** [comment]
Coming from Jekyll, I liked being able to separate out pages from posts in different directories and you could have a permalink option set in the site's config that would be applied to anything in the post directory.

With gatsby's focus on providing the minimal feature set and relying on plug-ins to fill in the gaps, I think building out a plug-in with rewritePath would be a good solution.

**Comment by KyleAMathews** [comment]
@kylegach hard coded where? In the parsed file info?

@michaeljdeeb great point. I'm going to be working on fine-tuning/filling out the API + adding a plugin architecture soon so yeah, someone could create a plugin easily enough to add this sort of functionality.

**Comment by kylegach** [comment]
Hard-coded in that snippet I included. Ideally, I could replace “writes” with some representation of the parent of `parsedFilePath.dirname`, but I don't know how or if it's possible.

**Comment by KyleAMathews** [comment]
Ah ok. Yeah `writes` should be somewhere in the `parsedFilePath` object if you want to make this work across multiple directories.

**Comment by kylegach** [comment]
It seems that #223 would make this a moot issue. Or rather, it shows that I had an incorrect understanding of the way the path is intended to work in front-matter.

**Comment by KyleAMathews** [comment]
Yeah I think defaulting to paths that are relative to the site root is the
simplest default. And with the future plunging architecture as Michael
mentioned someone could easily create a relative path plugin.
