### ISSUE TITLE
wrapRootElement + contextAPI : Page changes cause provider to re-render therefore resetting state. 

### ISSUE THREAD

**Issue by PaulBunker** [gatsbyjs/gatsby#22107]
## Summary
I am using React context api and hooks to create a global 'StateProvider' however when I change pages my provider re-renders causing me to loose the active state and return to the default.

It is my understanding that using the wrapRootElement method should mean that my stateProvider should persist. 

Some advice on how I can debug this issue would be greatly appreciated!

## Relevant information
gatsby-browser.js
```javascript
const StateProvider = require("./src/components/store/store").StateProvider
exports.wrapRootElement = ({ element }) => {
  return <StateProvider>{element}</StateProvider>
}
```

store.js
```javascript
const StateProviderContext = createContext()
const DispatchProviderContext = createContext()

const StateProvider = ({ children }) => {
  console.log("init")
  const tocTree = useEntries()
  const initialState = reducer(
    {},
    {
      type: INIT_PAGE,
      value: { pathname, tocTree },
    }
  )
  const [state, dispatch] = useReducer(reducer, initialState)
  return (
    <StateProviderContext.Provider value={state}>
      <DispatchProviderContext.Provider value={dispatch}>
        {children}
      </DispatchProviderContext.Provider>
    </StateProviderContext.Provider>
  )
}
```

**Comment by jonniebigodes** [comment]
@PaulBunker can you make a reproduction of your issue following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be better looked at? I wouldn't mind taking a look at it.

**Comment by PaulBunker** [comment]
Hey @jonniebigodes, Thanks for your reply! I'm working on a test case now. My most basic example didn't reproduce the problem so I'll keep adding things to try and break it.

**Comment by PaulBunker** [comment]
I've created a test-case [here](https://github.com/PaulBunker/examplegatsby) Although I have not managed to reproduce the exact issue with the state being reset you can see that "init" is logged when you click the home link and the state is logged twice which I don't believe should be happening.

I'll spend some more time tomorrow trying to more closely replicate my exact problem. I suspect it might be because the state is a little more complex than a counter in my actual app.

**Comment by jonniebigodes** [comment]
@PaulBunker i'll clone it shortly and go over and see if i can help you out. Do you mind waiting a bit?

**Comment by PaulBunker** [comment]
Not at all, I'm great-full for the help!

Still working on a version with more complex state to try and reproduce the state resetting but my brain is a little mushy at this point 🤪

**Comment by PaulBunker** [comment]
I fixed this problem using the 3rd argument for useReducer() that is used for initialising the state

**Comment by dagoss** [comment]
@PaulBunker I'm also running into this issue. Can you clarify by what you did to solve this?
