### ISSUE TITLE
[gatsby-source-graphql]: refetchInterval causes schema cache issue

### ISSUE THREAD

**Issue by MRDRMUFN** [gatsbyjs/gatsby#22112]
When refetchInterval has a value set under gatsby-config content will update as expected but changes to the remote graphql schema will not refresh, even when restarting gatsby develop. At that point it won't refresh the schema until I remove refetchInterval from gatsby-config and restart gatsby-develop.

I don't expect it to keep up with schema changes as it polls, but I would at least expect it to get a fresh schema structure on first start of the gatsby develop process.

**Comment by joshuagagne** [comment]
If I recall correctly the cache sticks around beyond the build cycle. Could you try a `gatsby clean` before a `gatsby develop` to force the schema to update?

**Comment by vladar** [comment]
@MRDRMUFN One of the options is to use `__refresh` endpoint for develop. You will need to pass `ENABLE_GATSBY_REFRESH_ENDPOINT` environment variable to `gatsby develop` to enable this feature. [See related docs](https://www.gatsbyjs.org/docs/environment-variables/#reserved-environment-variables).

So any time when you need to refetch you could call this endpoint (I think you can even open it as a browser tab to trigger refetch)

Please let me know if it helps?

**Comment by MRDRMUFN** [comment]
Found that running gatsby clean works. Turns out the default starter npm dev script no longer runs gatsby clean first. Or it could be that I'm just used to the Netlify starter which has that as default.

**Comment by vladar** [comment]
Thank you for opening this, @MRDRMUFN 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
