### ISSUE TITLE
Querying `allMarkdownRemark` with no markdown nodes fails

### ISSUE THREAD

**Issue by LegNeato** [gatsbyjs/gatsby#2212]
If you have no markdown files in your page directory and have `gatsby-transformer-remark` enabled, querying for `allMarkdownRemark` throws an error. I would expect the query to be empty instead, as the support is there but there are no nodes.

**Comment by gre** [comment]
a bit on that line, I'm having hard time figure out where is `allMarkdownRemark` handled in the code. at no place there is a "allMarkdownRemark" endpoint so it feels magic naming inferring? (but where?)

**Comment by LegNeato** [comment]
It looks like the magic is for every node type registered (in this case `MarkdownRemark`) a field for `all[Typename]` (in this case `allMarkdownRemark`) is added to `RootQueryType`:

https://github.com/gatsbyjs/gatsby/blob/524ff171cd890b79ce9535d6dc10550c70365d33/packages/gatsby/src/schema/index.js#L13

This only happens if there are nodes, hence this issue.

**Comment by nihgwu** [comment]
the `MarkdownRemark` node type will only be created when there is a markdown node, or there will be no `MarkdownRemark` node type at all, so you can't query `allMarkdownRemark`

**Comment by LegNeato** [comment]
Right, changing that behavior is what this issue is about 😄 . It was immensely confusing to install the transformer, have it in the config, yet have my queries marked as invalid. I spent a while debugging until I realized it was due to not having an existing `.md` file yet so there were no nodes. This also means if one were to transition off sources/transformers, a perfectly valid config can suddenly start throwing errors (like, for example if you deleted your last `.md` file).

While I don't think this is a *huge* issue, I would expect sources/transformers to register their "all" queries on source/transformer activation regardless if there are any existing nodes or not.

**Comment by djm** [comment]
This one caught me too; I agree it's not the largest of issues but it'd be a move that improved developer experience in my opinion.

The core issue for me was that my first thought when it occurred was not "oh, I don't have any markdown files in that folder yet", but rather "why hasn't the plugin registered the type? There must be an issue with how I installed the plugin...". and that let on a bit of a wild goose chase.

**Comment by KyleAMathews** [comment]
So this is interesting. I'm a bit surprised this is causing confusion. Let me try to explain my mental model for these parts of Gatsby.

At a high level this is how I see Gatsby

```

   +-----------+   +------------+   +----------------+
   |           |   |            |   |                |
   |  Source   +---> Transform  +--->  Infer GraphQL |
   |  Data     |   | Data       |   |  Schema        |
   |           |   |            |   |                |
   +-----------+   +------------+   +---------^------+
                                              |
                                              |
                  +-------------------+       |
                  |   GraphQL Queries+--------+
                  |                   |
                  |                   |
                  | React Web App     |
                  +-------------------+
                           |
                           v
                    Optimized Production
                    Build
                           +
                           |
                           v
                      Static Files Output

```

(I hope you enjoy my 5 minute ascii drawing :-D)

Source & Transformer plugins don't (generally) have anything to do with the GraphQL schema directly. They just "source" data from remote sources or "transform" data that source plugins pull in. So they don't create a schema, they create data (nodes in Gatsby-speak) which after they've finished their work, another Gatsby system comes along and infers a GraphQL schema from the nodes.

So if there's no markdown files, there's no `File` nodes with a `mediaType` of `text/markdown` which means `gatsby-transformer-remark` doesn't create an nodes of type `MarkdownRemark` which means there's no GraphQL types `allMarkdownRemark` or `MarkdownRemark`.

Transformer plugins don't need to know the type of nodes they're creating as often the type is only known at runtime e.g. "gatsby-source-contentful" creates nodes whose types are taken from the types of content created through the Contentful UI.

I get this is confusing as there's multiple data transformations going on and many layers of types going on as well.

I suppose a solution could be if a) a transformer plugin only creates "static" types (e.g. type names we know at code-writing time e.g. `MarkdownRemark`) then b) it could register with Gatsby this type name with any fields in knows for sure would be in the eventual type (generally not much).

Perhaps we just need to do a better job in docs explaining the setup so it's less surprising what's going on?

Other ideas?

**Comment by fk** [comment]
(To cut down drawing time: http://asciiflow.com/ ;))

**Comment by djm** [comment]
@KyleAMathews What you said makes full sense! The confusion on my part (I can't speak for LegNeato) came from making the assumption that the transformers have any say whatsoever in the graphql schema generation.  

I think you're right, a documentation solution is probably enough – just telling users that transformers return just data (nodes) in the same sense source plugins do.

Edit: Perhaps if the confusion continues another solution could be that the transformers were made to report/log on the runs when they found nothing to transform; this may also help with people not realising they can remove certain transformers as they don't use them (for build perf). I can't think of a reason why you'd leave a transformer in if it wasn't transforming anything.

**Comment by KyleAMathews** [comment]
>transformers were made to report/log on the runs when they found nothing to transform

Ooo! That's a great solution. But for helping people build good mental models of Gatsby and avoiding confusion about why things aren't showing up in Graph*i*QL but also, yeah having lots of unused transformers would slow things down somewhat (though not a ton most likely as most plugins just do a simple if check on nodes which is very cheap).

**Comment by djm** [comment]
I'm not by an editor at the mo, but I imagine it could probably happen in one place too? In whatever bit of code expects data from all the transformers.

**Comment by KyleAMathews** [comment]
Yeah that would work. We track which plugin creates which nodes. We could add a check for plugins which implement "sourceNodes" or "onCreateNode" and check that each of these plugins created at least one node and warn if not. Wanna make the PR?

**Comment by djm** [comment]
Yeah I'll take it, need to learn my away around those bits anyway!

**Comment by KyleAMathews** [comment]
Sweet! Add the validation code here: https://github.com/gatsbyjs/gatsby/blob/e739a597e77c1d0ff78bd39965d453d4a18aa07d/packages/gatsby/src/utils/source-nodes.js#L13

**Comment by djm** [comment]
@KyleAMathews 

Had a crack at this last night and got pretty far but I need some guidance..

Internal output from a test example project:

```
# Plugins that implement sourceNodes or onCreateNode.
[ 'internal-data-bridge',
  'gatsby-source-filesystem',
  'gatsby-plugin-typography',
  'gatsby-transformer-remark',
  'gatsby-transformer-sharp',
  'default-site-plugin' ]

# state.nodes are owned by:
[ 'internal-data-bridge',
  'gatsby-source-filesystem',
  'gatsby-transformer-remark' ]

# Therefore, the following are listed as "should warn". They use the APIs but don't own nodes.

[ 'gatsby-plugin-typography',
  'gatsby-transformer-sharp',
  'default-site-plugin' ]
```


Out of that final list, I believe the only one we actually want to politely warn about is `gatsby-transformer-sharp`, as my project had no images to find and therefore it wasn't actually used.

1) `gatsby-plugin-typography` implements `sourceNodes` but doesn't source anything.
2) `default-site-plugin` - sounds like it can be ignored?

What shall we do about these two? and do you know of any others that might be edge cases?

Thanks!

**Comment by KyleAMathews** [comment]
Sounds like the other plugins need a PR to remove the unused API implementation? Also realized that plugins can use onCreateNode to create nose fields.

**Comment by djm** [comment]
@KyleAMathews You realised that yesterday so the code checks for sourceNodes _and_ onCreateNode already :)

I'm happy making the PR to change gatsby-plugin-typography, [there's a comment](https://github.com/gatsbyjs/gatsby/blob/8fffb724cd32749ff8c939190e552716315d2d6a/packages/gatsby-plugin-typography/src/gatsby-node.js#L7) in there which says:

> // TODO add a new API hook e.g onPreBootstrap

Do you know the status of that?

**Comment by djm** [comment]
I think it'd have to be a new one, I don't see a similar API in [api-node-docs](https://github.com/gatsbyjs/gatsby/blob/8fffb724cd32749ff8c939190e552716315d2d6a/packages/gatsby/src/utils/api-node-docs.js), but the [api-specification](https://github.com/gatsbyjs/gatsby/blob/8fffb724cd32749ff8c939190e552716315d2d6a/docs/docs/api-specification.md) does mention it.

**Comment by KyleAMathews** [comment]
Yeah, it'd be new. Lemme add it and move gatsby-plugin-typography over.

**Comment by KyleAMathews** [comment]
@djm https://github.com/gatsbyjs/gatsby/pull/2241

**Comment by Alxandr** [comment]
You might want to allow this warning to be turned off (by the plugin). If you want to be general about it, how about something like

```
exports.disabledWarnings = [
  'core/no-nodes-created'
];
```

**Comment by djm** [comment]
Yeah, that's something that can be added in time when it's definitely needed. For now, ensuring plugins don't use the incorrect APIs because there's nothing else available to them was the better option.

**Comment by djm** [comment]
Update on this: near completion - just need to update the tests and add a few new cases. I don't have any time tonight so I would expect the PR more likely on Friday/over the weekend. Thanks Kyle!

**Comment by sebastienfi** [comment]
@djm This is great, it will help a lot

**Comment by djm** [comment]
As ever, real life got in the way! This is coming along though:

<img width="588" alt="screen shot 2017-10-05 at 09 27 04" src="https://user-images.githubusercontent.com/88744/31217717-dc49e50c-a9af-11e7-87f3-d4b3728ada5b.png">

Next step, update the tests then PR.

**Comment by koluch** [comment]
Hi,

Is there is any workaround for this issue? I want to make my site work fine when there are no Markdown files, but build fails with `Unknown field 'allMarkdownRemark' on type 'RootQueryType'`. How can I deal with it?

**Comment by nileshgulia1** [comment]
@koluch I am also experiencing this issue, did you resolved your problem?

**Comment by koluch** [comment]
@nileshgulia1 I ended up with putting empty file in every folder I use for markdown files and then filtering them out in all the places I need them. It looks terrible, but it also fixed an issue with empty folders, because Git doesn't stores empty folders, and `gatsby-source-filesystem` is unable to handle non-existed folders properly :(

You can look at it here, this is the project I just started working on: https://github.com/koluch/he-he-2

**Comment by nileshgulia1** [comment]
@koluch Thanks a lot, I will look into it :)

**Comment by KyleAMathews** [comment]
I believe this was fixed so closing

**Comment by JGallardo** [comment]
for anyone doing a google search and ends up here, your answer may be at 
https://www.gatsbyjs.org/packages/gatsby-transformer-remark/

**Comment by tfaieta** [comment]
Hi all, really loving Gatsby, but I'm running into the same issue when I'm trying to build my site. Running `gatsby develop` works fine but I get this error when I run `gatsby build`:

 ```
  Error: Cannot query field "allMarkdownRemark" on type "Query".
  GraphQL request (3:9)
  2:       {
  3:         allMarkdownRemark(
             ^
  4:           limit: 1000,
```

The problems started after I added gatsby-mdx and reconfigured my gatsby-config and gatsby-node files. I currently have no .MD files and only have one .MDX file.

Here's a link to the repo if you all can help me out I'd appreciate it:
https://github.com/tfaieta/tfaieta.com

**Comment by jonniebigodes** [comment]
@tfaieta i've cloned your repo, installed the dependencies and issued `gatsb build && gatsby serve`. And i'm presented with this:
![tfaieta_error](https://user-images.githubusercontent.com/22988955/54640843-9fe36b80-4a88-11e9-8af0-6f9c0ec21d18.png)

Doing a bit of digging it looks like you have installed `gatsby-plugin-feed` and activated it in the `gatsby-config.js`.
Disabling it will allow a sucessful build as you can see here:
![tfaieta_build_ok](https://user-images.githubusercontent.com/22988955/54641107-3879eb80-4a89-11e9-9264-814af8e3f227.png)

If you need that plugin, a little more of a configuration might be needed.

More on the plugin usage [here](https://www.gatsbyjs.org/packages/gatsby-plugin-feed/)

**Comment by tfaieta** [comment]
@jonniebigodes Awesome! Thanks so much!
