### ISSUE TITLE
"vips2png: unable to write to buffer" after removing an image

### ISSUE THREAD

**Issue by mkloar** [gatsbyjs/gatsby#22125]
## Description

Hey. We're getting weird error during gatsby build process on our pipeline in gitlab. An error occurs like every 2-3 days. We're running build process on our custom docker image.

**Error:**
vips2png: unable to write to buffer

Pipeline:
![pipelineFail](https://user-images.githubusercontent.com/17946736/76207843-d3218c00-61fe-11ea-898d-870e104ef4d9.PNG)

### Steps to reproduce

We can't reproduce this error during development, only on pipelines.

### Expected result

Build succeeded

### Actual result

Build failed

### Environment

  System:
     OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
     CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
     Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.9.0 - /usr/bin/node
    Yarn: 1.22.0 - /usr/bin/yarn
    npm: 6.13.7 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    gatsby: ^2.15.28 => 2.17.7
    gatsby-cli: ^2.7.53 => 2.8.8
    gatsby-image: 2.2.23 => 2.2.23
    gatsby-plugin-antd: ^2.0.2 => 2.0.2
    gatsby-plugin-catch-links: ^2.1.12 => 2.1.15
    gatsby-plugin-emotion: ^4.1.9 => 4.1.13
    gatsby-plugin-less: ^3.0.9 => 3.0.12
    gatsby-plugin-manifest: 2.2.20 => 2.2.20
    gatsby-plugin-mdx: ^1.0.46 => 1.0.55
    gatsby-plugin-offline: 3.0.11 => 3.0.11
    gatsby-plugin-react-helmet: 3.1.10 => 3.1.10
    gatsby-plugin-remove-trailing-slashes: ^2.1.9 => 2.1.12
    gatsby-plugin-sharp: ^2.2.27 => 2.2.36
    gatsby-remark-autolink-headers: 2.1.16 => 2.1.16
    gatsby-remark-copy-linked-files: ^2.1.29 => 2.1.29
    gatsby-remark-images: ^3.1.25 => 3.1.28
    gatsby-remark-mathjax: ^1.0.0 => 1.0.0
    gatsby-remark-prismjs: ^3.3.16 => 3.3.20
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-source-filesystem: 2.1.28 => 2.1.28
    gatsby-transformer-remark: ^2.6.27 => 2.6.32
    gatsby-transformer-sharp: 2.2.19 => 2.2.19
  npmGlobalPackages:
    gatsby-cli: 2.8.30

**Comment by pvdz** [comment]
Hi @mkloar, thanks for reporting. It's a little difficult to see what's going on without seeing the code that caused it.
Could you post a (minimal) repro, please? A repo to check out and build that reproduces this would be perfect.

**Comment by mkloar** [comment]
We didn't reproduce this error on gatsby develop until now.

![errorThrown](https://user-images.githubusercontent.com/17946736/76605886-89dc7f80-6511-11ea-812b-1945b98a07c9.PNG)

We deleted some images inside our content folders.

**Comment by vladar** [comment]
@mkloar We need to reproduce this locally somehow to help you. We'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by mkloar** [comment]
I manage to figure it out. It was a broken png image which causes this error. After removing that picture everything worked as expected. You can close this up.

**Comment by pvdz** [comment]
Glad you resolved it. Changed the title for better visibility. Hopefully it'll help somebody else looking for this error.
