### ISSUE TITLE
build deployment fails on netlify

### ISSUE THREAD

**Issue by jindal368** [gatsbyjs/gatsby#22132]
Here is deploy LOG>>>

5:31:14 PM: Build ready to start
5:33:51 PM: build-image version: 6b66e79d54a8f76b01392124644c3052ac0d32ef
5:33:51 PM: build-image tag: v3.3.6
5:33:51 PM: buildbot version: 2ba6f2db8150441c8469e6ae3ab3561a2c9d03fa
5:33:51 PM: Fetching cached dependencies
5:33:51 PM: Starting to download cache of 254.9KB
5:33:51 PM: Finished downloading cache in 85.612613ms
5:33:51 PM: Starting to extract cache
5:33:51 PM: Failed to fetch cache, continuing with build
5:33:51 PM: Starting to prepare the repo for build
5:33:52 PM: No cached dependencies found. Cloning fresh repo
5:33:52 PM: git clone https://github.com/jindal368/gatsby_trading-webapp
5:33:52 PM: Preparing Git Reference refs/heads/master
5:33:53 PM: Starting build script
5:33:53 PM: Installing dependencies
5:33:55 PM: v10.19.0 is already installed.
5:33:56 PM: Now using node v10.19.0 (npm v6.13.4)
5:33:56 PM: Attempting ruby version 2.6.2, read from environment
5:33:58 PM: Using ruby version 2.6.2
5:33:58 PM: Using PHP version 5.6
5:33:58 PM: Started restoring cached node modules
5:33:58 PM: Finished restoring cached node modules
5:33:58 PM: Installing NPM modules using NPM version 6.13.4
5:34:45 PM: > sharp@0.23.4 install /opt/build/repo/node_modules/sharp
5:34:45 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
5:34:45 PM: info
5:34:45 PM: sharp
5:34:45 PM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
5:34:48 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/core-js
5:34:48 PM: > node -e "try{require('./postinstall')}catch(e){}"
5:34:48 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
5:34:48 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
5:34:48 PM: > https://opencollective.com/core-js 
5:34:48 PM: > https://www.patreon.com/zloirock 
5:34:48 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
5:34:48 PM: > core-js-pure@3.6.4 postinstall /opt/build/repo/node_modules/core-js-pure
5:34:48 PM: > node -e "try{require('./postinstall')}catch(e){}"
5:34:48 PM: > gatsby-telemetry@1.1.47 postinstall /opt/build/repo/node_modules/gatsby-telemetry
5:34:48 PM: > node src/postinstall.js || true
5:34:49 PM: > cwebp-bin@5.1.0 postinstall /opt/build/repo/node_modules/cwebp-bin
5:34:49 PM: > node lib/install.js
5:34:49 PM:   ✔ cwebp pre-build test passed successfully
5:34:49 PM: > mozjpeg@6.0.1 postinstall /opt/build/repo/node_modules/mozjpeg
5:34:49 PM: > node lib/install.js
5:34:50 PM:   ✔ mozjpeg pre-build test passed successfully
5:34:50 PM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
5:34:50 PM: > node lib/install.js
5:34:50 PM:   ✔ pngquant pre-build test passed successfully
5:34:50 PM: > gatsby-cli@2.8.27 postinstall /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli
5:34:50 PM: > node scripts/postinstall.js
5:34:51 PM: > gatsby@2.19.7 postinstall /opt/build/repo/node_modules/gatsby
5:34:51 PM: > node scripts/postinstall.js
5:34:54 PM: npm
5:34:54 PM: WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
5:34:54 PM: npm WARN
5:34:54 PM:  notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
5:34:54 PM: npm WARN
5:34:54 PM: optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/chokidar/node_modules/fsevents):
5:34:54 PM: npm WARN
5:34:54 PM: notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
5:34:54 PM: added 2048 packages from 994 contributors and audited 27265 packages in 53.521s
5:34:56 PM: 43 packages are looking for funding
5:34:56 PM:   run `npm fund` for details
5:34:56 PM: found 20 vulnerabilities (2 moderate, 18 high)
5:34:56 PM:   run `npm audit fix` to fix them, or `npm audit` for details
5:34:56 PM: NPM modules installed
5:34:56 PM: Started restoring cached go cache
5:34:56 PM: Finished restoring cached go cache
5:34:56 PM: unset GOOS;
5:34:56 PM: unset GOARCH;
5:34:56 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
5:34:56 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
5:34:56 PM: go version >&2;
5:34:56 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
5:34:56 PM: go version go1.12 linux/amd64
5:34:56 PM: Installing missing commands
5:34:56 PM: Verify run directory
5:34:56 PM: Executing user command: gatsby build
5:34:59 PM: success open and validate gatsby-configs - 0.025s
5:35:00 PM: success load plugins - 0.780s
5:35:00 PM: success onPreInit - 0.003s
5:35:00 PM: success delete html and css files from previous builds - 0.013s
5:35:00 PM: success initialize cache - 0.008s
5:35:00 PM: success copy gatsby files - 0.042s
5:35:00 PM: success onPreBootstrap - 0.013s
5:35:00 PM: success createSchemaCustomization - 0.004s
5:35:00 PM: Starting to fetch data from Contentful
5:35:00 PM: Fetching default locale
5:35:00 PM: default locale is : en-US
5:35:01 PM: contentTypes fetched 2
5:35:01 PM: Updated entries  15
5:35:01 PM: Deleted entries  0
5:35:01 PM: Updated assets  11
5:35:01 PM: Deleted assets  0
5:35:01 PM: Fetch Contentful data: 941.218ms
5:35:01 PM: success source and transform nodes - 1.080s
5:35:01 PM: success building schema - 0.486s
5:35:01 PM: success createPages - 0.000s
5:35:02 PM: success createPagesStatefully - 0.088s
5:35:02 PM: success onPreExtractQueries - 0.001s
5:35:02 PM: success update schema - 0.032s
5:35:02 PM: warning Using the global `graphql` tag is deprecated, and will not be supported in v3.
5:35:02 PM: Import it instead like:  import { graphql } from 'gatsby' in file:
5:35:02 PM: /opt/build/repo/src/pages/index.js
5:35:02 PM: success extract queries from components - 0.592s
5:35:02 PM: success write out requires - 0.004s
5:35:02 PM: success write out redirect data - 0.001s
5:35:02 PM: success Build manifest and related icons - 0.001s
5:35:02 PM: success onPostBootstrap - 0.003s
5:35:02 PM: ⠀
5:35:02 PM: info bootstrap finished - 5.843 s
5:35:02 PM: ⠀
5:35:03 PM: error There was an error in your GraphQL query:
5:35:03 PM: VipsJpeg: Corrupt JPEG data: bad Huffman code
5:35:03 PM: VipsJpeg: out of order read at line 320
5:35:03 PM:    1 | fragment GatsbyContentfulFluid_tracedSVG on ContentfulFluid {
5:35:03 PM: >  2 |   tracedSVG
5:35:03 PM:      |   ^
5:35:03 PM:    3 |   aspectRatio
5:35:03 PM:    4 |   src
5:35:03 PM:    5 |   srcSet
5:35:03 PM:    6 |   sizes
5:35:03 PM:    7 | }
5:35:03 PM:    8 |
5:35:03 PM:    9 | query optbuildreposrccomponentshomeproductsJs1310321567 {
5:35:03 PM:   10 |   products: allContentfulMenFashion {
5:35:03 PM:   11 |     edges {
5:35:03 PM:   12 |       node {
5:35:03 PM: File path: /opt/build/repo/src/components/home/products.js
5:35:03 PM: Plugin: none
5:35:03 PM: error There was an error in your GraphQL query:
5:35:03 PM: VipsJpeg: Corrupt JPEG data: bad Huffman code
5:35:03 PM: VipsJpeg: out of order read at line 320
5:35:03 PM:    1 | fragment GatsbyContentfulFluid_tracedSVG on ContentfulFluid {
5:35:03 PM: >  2 |   tracedSVG
5:35:03 PM:      |   ^
5:35:03 PM:    3 |   aspectRatio
5:35:03 PM:    4 |   src
5:35:03 PM:    5 |   srcSet
5:35:03 PM:    6 |   sizes
5:35:03 PM:    7 | }
5:35:03 PM:    8 |
5:35:03 PM:    9 | query optbuildreposrccomponentshomeproductsJs1310321567 {
5:35:03 PM:   10 |   products: allContentfulMenFashion {
5:35:03 PM:   11 |     edges {
5:35:03 PM:   12 |       node {
5:35:03 PM: File path: /opt/build/repo/src/components/home/products.js
5:35:03 PM: Plugin: none
5:35:03 PM: not finished run queries - 1.014s
5:35:03 PM: not finished Generating image thumbnails - 0.971s
5:35:03 PM: Skipping functions preparation step: no functions directory set
5:35:03 PM: Caching artifacts
5:35:03 PM: Started saving node modules
5:35:03 PM: Finished saving node modules
5:35:03 PM: Started saving pip cache
5:35:03 PM: Finished saving pip cache
5:35:03 PM: Started saving emacs cask dependencies
5:35:03 PM: Finished saving emacs cask dependencies
5:35:03 PM: Started saving maven dependencies
5:35:03 PM: Finished saving maven dependencies
5:35:03 PM: Started saving boot dependencies
5:35:03 PM: Finished saving boot dependencies
5:35:03 PM: Started saving go dependencies
5:35:03 PM: Finished saving go dependencies
5:35:07 PM: Error running command: Build script returned non-zero exit code: 1
5:35:07 PM: Failing build: Failed to build site
5:35:07 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
5:35:07 PM: Finished processing build request in 1m15.973242834s

**Comment by axe312ger** [comment]
One thing, unrelated but you should fix it: `warning Using the global graphql tag is deprecated, and will not be supported in v3`


I see similar issues happending when loading assets from contentful, in my case its mostly timeouts.

But ive seen warnings of corrupted image data in the past week while heavily using netlify & gatsby cloud.


My workaround, annoying and time intense, but working:

* just restart it... multiple times if needed...

**Comment by pvdz** [comment]
Might be related to https://github.com/gatsbyjs/gatsby/issues/22125 

Can you check whether this is related to netlify at all? Can you repro it locally? Can you post a minimal repro somewhere so we can verify?

**Comment by pvdz** [comment]
Or is this a dupe of https://github.com/gatsbyjs/gatsby/issues/8301 ... Can you try renaming the file? :)

**Comment by jindal368** [comment]
it is running on localhost .....with all the queries
I think it might be related with netlify.
can you explain why  i am getting error in GraphQL
as it is running fine on local server

**Comment by pvdz** [comment]
@jindal368 it would help a lot if you can post a repro. It's difficult to say from this report what's going on. There are many reasons why something works locally but not in a remote host.

**Comment by jindal368** [comment]
[https://github.com/jindal368/gatsby_trading-webapp](url)

**Comment by vladar** [comment]
> 5:35:03 PM: VipsJpeg: Corrupt JPEG data: bad Huffman code
> 5:35:03 PM: VipsJpeg: out of order read at line 320

This usually means that your JPEG images were corrupted somehow while downloading.

**Comment by jindal368** [comment]
how  i can fix it. plz help

**Comment by axe312ger** [comment]
The updates released on of 2020 and the fixes from March (v3)  and April (v2) should fix these issues!
