### ISSUE TITLE
Is there a built-in way to provide mini-css-extract-plugin options?

### ISSUE THREAD

**Issue by dustinhorton** [gatsbyjs/gatsby#22148]
I'm using `gatsby-plugin-sass`, and getting incorrect 'Conflicting order' warnings. [These can be disabled](https://github.com/webpack-contrib/mini-css-extract-plugin#remove-order-warnings):

```js
// webpack.config.js

const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  plugins: [
    new MiniCssExtractPlugin({
      ignoreOrder: true,
    }),
  ],
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [MiniCssExtractPlugin.loader, 'css-loader'],
      },
    ],
  },
};
```

Is there an easier way to add this `ignoreOrder` option than [creating a custom webpack config](https://www.gatsbyjs.org/docs/add-custom-webpack-config/)?

**Comment by dustinhorton** [comment]
Found an example of editing the webpack config that wasn't how I would've done it: https://spectrum.chat/gatsby-js/general/having-issue-related-to-chunk-commons-mini-css-extract-plugin~0ee9c456-a37e-472a-a1a0-cc36f8ae6033?m=MTU3MjYyNDQ5OTAyNQ==

**Comment by pieh** [comment]
The example you found is probably most correct way of doing this right now.

There are plans to make it nicer to adjust webpack config that come from core (like changing option, or even bumping loader versions), but it's not done yet (and it's TBD if we will try to do it ultimately)
