### ISSUE TITLE
Q: is it possible to have multiple sources / multiple transformers?

### ISSUE THREAD

**Issue by gre** [gatsbyjs/gatsby#2214]
I'm having difficult time figuring out some magic behind gatsby (like wtf allMarkdownRemark come from, I didn't find any occurence of "allMarkdownRemark" in the back code).

> quick pith of my project idea: I want to have a single file, that contains a list of URLs. from that list, I generate a feed of articles. An url can be a link to markdown on gists, link to youtube videos, link to twitter,... (in 2017, I feel like we don't just write articles, we write many kind of documents in many places, I want to unify that)

**so I'm looking for a way to implement an aggregation of different type of documents.** like pulling from different places. I have zero experience in gatsby but deeping 1 hour into the architecture, it looks like I need to write my own source ? But then the issue is I don't want to have just a feed of markdowns, but I want a feed of articles, tweets, videos,... all interleaved... Is gatsby architecture ready for that? What i'm seeing so far is you have to do `allMarkdownRemark` or `allDrupalNodeArticle` but is there a `all` generic graphql collection I can pull from (and I would be ok doing a `... on MarkdownRemark {}` in the graphql). In other words, can I write a gatsby source that emit different type of nodes (markdown / other new types of my own). I don't want to "transform" at the source place by I think it's more powerful to 

If it is not fundamentally not possible I will probably write a simpler solution without gatsby.

Thanks,
feel free to close this issue if it makes no sense / out of scope ^^

PS: is there a way to explore the graphql, e.g. using  graphiql? would be neat if you would mention that in the doc

**Comment by nihgwu** [comment]
What you want is just what the magic power Gatsby provides, you can read the source code of the transformer plugins like `gatsby-transformer-json` and others

`gatsby-source-filesystem` provides the file nodes, then the transformers turn them into your wanted format, for example I wrote my our plugin to transform the nodes to raw codes

for `allMarkdownRemark` and `markdownRemark`, they are defined in the transformer plugin, like `createNode({internal: {type: 'MarkdownRemark'}})`, then the rest will be generated by Gatsby

**Comment by nihgwu** [comment]
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/on-node-create.js#L47

**Comment by nihgwu** [comment]
another hint is that the `pageQuery` in templates will be extracted by Gatsby in building, so it's actually not the part of the template component,  you can rename `pageQuery` to any name if you like

**Comment by revolunet** [comment]
And yes, when you start gatsby, it tells you you can access the GraphiQL client :
```
Your site is running at http://localhost:8000
Your graphql debugger is running at http://localhost:8000/___graphql
```

**Comment by gre** [comment]
thanks for your answer @nihgwu . I need to study this more (including gatsby-transformer-json) but i'm not yet sure how to handle interleaved documents, I mean, you have a markdown and then you have a another kind of document, & at the end I want to have them all listed. I feel like I have to write a transformer that handle them all, this can't work in a loosely coupled way, like I would have transformer-markdown and transformer-foo in the pipe and at the end I can list them all and retrieve each individual result.

sorry if this is confusing and thanks for answer, I think a transformer that handle all types and then yield them in an unified graphql collection will do it for now :)

**Comment by nihgwu** [comment]
@gre it's really easy to combine transformer-foo and transformer-bar in one pipe, `onCreateNode` is a map callback for you called `allNodes`, you can create node-foo and node-bar in the same time for a node, then you can create. And actually `allNodes` is called `allFile` in Gatsby, but it's just a collection of file node, you can create new node upon it

**Comment by nihgwu** [comment]
It's the source plugins provide the `allNodes`, then you can transform them into wanted format

**Comment by KyleAMathews** [comment]
Check out what @craig-mulligan is doing over at https://github.com/resin-io/landr

He has several specialized transformers for extracting data out of markdown files e.g. his readme & changelog transformers https://github.com/resin-io/landr/tree/master/packages

**Comment by KyleAMathews** [comment]
But yeah, the basic idea behind all this is that source/transformer plugins do all the heavy lifting on transforming data into the desired shape and then you can just pull them into your React components to build the UI. In the source/transformer plugins, you have complete control over data manipulation and it's super easy to create your own custom transformers!

**Comment by leekad** [comment]
Hi, i tried to using 2 gatsby-sources plugin to get data from markdown and wordpress, but got error 

> The plugin "gatsby-source-wordpress" created a node of a type owned by another plugin.
          The node type "File" is owned by "gatsby-source-filesystem".
          If you copy and pasted code from elsewhere, you'll need to pick a new type name
          for your new node(s).

Any ideas? Thank you

**Comment by KyleAMathews** [comment]
@leekad same error as https://github.com/gatsbyjs/gatsby/issues/2314

Hopefully will get fix in for that today.
