### ISSUE TITLE
navigate() does not return a Promise

### ISSUE THREAD

**Issue by antoinerousseau** [gatsbyjs/gatsby#22151]
## Description

When importing the `navigate` function

### Steps to reproduce

```js
import { navigate } from "gatsby"

navigate("/somewhere/").then(doSomething)
```

### Expected result

When the navigation completes, `doSomething` should be called.

### Actual result

This throws an error because `navigate()` returns `undefined` instead of an expected `Promise` (see [type](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/index.d.ts#L3)).

Looks like `gatsby-link` is wrapping that function using a global variable:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-link/src/index.js#L202-L204

Instead of `@reach/router`'s `navigate` as indicated in the types.

When I use the one from `@reach/router`, it works, but is it safe to do so?

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 72.0.2
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.17.15 => 2.19.35
    gatsby-image: ^2.2.33 => 2.2.43
    gatsby-plugin-google-analytics: ^2.1.27 => 2.1.37
    gatsby-plugin-manifest: ^2.2.28 => 2.2.45
    gatsby-plugin-netlify: ^2.1.25 => 2.1.34
    gatsby-plugin-offline: ^3.0.21 => 3.0.38
    gatsby-plugin-react-helmet: ^3.1.15 => 3.1.23
    gatsby-plugin-sharp: ^2.3.0 => 2.4.9
    gatsby-plugin-sitemap: ^2.2.21 => 2.2.28
    gatsby-plugin-styled-components: ^3.1.13 => 3.1.20
    gatsby-plugin-typescript: ^2.1.18 => 2.2.2
    gatsby-source-contentful: ^2.1.59 => 2.1.93
    gatsby-source-filesystem: ^2.1.37 => 2.1.51
    gatsby-transformer-inline-svg: ^0.0.7 => 0.0.7
    gatsby-transformer-sharp: ^2.3.5 => 2.3.18
```

**Comment by pieh** [comment]
I'm not sure if it was ever intended to return promise (and thus typings are wrong). Making navigate return promise might be difficult to implement (because we would actually wait for new path template to render before resolving the promise)

**Comment by dandv** [comment]
I've also run into this issue. What's the word, wrong typings?

Please [document](https://www.gatsbyjs.org/docs/gatsby-link/#how-to-use-the-navigate-helper-function), thanks! :purple_heart:

**Comment by antoinerousseau** [comment]
@dandv PR welcome ;)

**Comment by dandv** [comment]
@antoinerousseau: I was [told](https://github.com/gatsbyjs/gatsby/issues/24135#issuecomment-630250247) `navigate` would be deprecated.

**Comment by antoinerousseau** [comment]
@dandv so why suggest documenting it?

**Comment by dandv** [comment]
Because I suggested documenting that [it's not available during SSR](https://github.com/gatsbyjs/gatsby/issues/24135) before being told it would be deprecated.

**Comment by casewalker** [comment]
The version is now Gatsby 5 and navigate is still alive and well! And the signature still appears to be wrong!
