### ISSUE TITLE
`gatsby-source-git` and `gatsby-source-filesystem` when used together gives duplicate file nodes.

### ISSUE THREAD

**Issue by santoshdahal12** [gatsbyjs/gatsby#22159]
# Summary 
I am trying to pull .md files from private git repo. After doing some research, I was able to pull them using [gatsby-source-git](https://www.gatsbyjs.org/packages/gatsby-source-git/#gatsby-source-git). However, this clones into `.cache` folder. 

And then again I am using  gatsby-source-filesystem that I need it to see at the `.cache` directory for data source. The build is fine except , when I iterate through edges, I see there is duplicate MarkdownRemarkEdge. 
There are only two `.md` files in the remote repository, but when it is puled down by [gatsby-source-git](https://www.gatsbyjs.org/packages/gatsby-source-git/#gatsby-source-git) I can see in `graphql` that are 4 edge instances. Thus, while iterating through edges I get dupliacte posts.

I know I am doing a hack to point to `./cache` folder for `gatsby-source-filesystem` as I didnt find anywhere how to achieve this. 

This is the blog I have made [www.howsthere.com](https://www.howsthere.com/) and it shows two posts but this is being served from same git repo. 

However after I try to pull only md files from private git repo and build it from different repo,  it gives duplicate 

![image](https://user-images.githubusercontent.com/22568545/76375333-ed04c100-631b-11ea-85da-c8b3b4ff2347.png)

## Relevant information

Following is my `gatsby-config.js`

```
const GITHUB_USER="santoshdahal12"
const GITHUB_TOKEN = "################"
const GITHUB_REPOSITORY = "howstheredotcom-blog-mdfiles"

module.exports = {
  siteMetadata: {
    title: `how's there`,
    description: `Blogging for structuring thoughts.`,
    author: `santosh dahal`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`,
      },
    },
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: process.env.GOOGLE_ANALYTICS_TRACKING_ID,
      },
    },
    `gatsby-transformer-remark`,
    {
      resolve: `gatsby-source-git`,
      options: {
        name: `blogs`,
        remote: `https://${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${GITHUB_REPOSITORY}.git`,
        branch: `master`,
        pattern: [`2020-02-26-post/**`, `2020-02-27-post/**`]
      }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        plugins: [`gatsby-remark-reading-time`],
        name: `pages`,
        path: `${__dirname}/.cache/gatsby-source-git/blogs`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
  ],
}
```

### File contents (if changed)

`gatsby-config.js`: Yes 
`package.json`: N/A 
`gatsby-node.js`: Yes 
```
const path = require('path')
exports.createPages = (({graphql, actions})=>{

    const {createPage} = actions;
    return new Promise((res, rej)=>{
        const blogTemplate = path.resolve('src/templates/blogPost.js')

        res(
            graphql(`
            query MyQuery {
                allMarkdownRemark {
                  edges {
                    node {
                      frontmatter {
                        path
                      }
                    }
                  }
                }
              }
            `).then(result=>{
                result.data.allMarkdownRemark
                .edges.forEach(({node}) => {
                    const {path} = node.frontmatter
                    createPage({
                        path,
                        component:blogTemplate,
                        context:{
                            pathSlug:path
                        }
                    })
                    res()
                });
            })
        )
    })
});

```
`gatsby-browser.js`: No 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
`gatsby-source-git` already creates `File` nodes from git imported files, so adding another `gatsby-source-filesystem` that checks `.cache` is creating duplicates - you shouldn't need additional `gatsby-source-filesystem` here

**Comment by santoshdahal12** [comment]
@pieh Thanks. I initially understood that from the documentation of `gatsby-source-git`.  But, how to tell `gatsby-transformer-remark` to read from from the file node. I thought `gatsby-source-filesystem` makes it easy to source markdown data.

**Comment by vladar** [comment]
Remark should transform nodes coming from `gatsby-source-git` the same way it transforms nodes coming from `gatsby-source-filesystem`.

Have you tried removing `gatsby-source-filesystem` (which points to .cache)? You should still get the markdown parsed.

**Comment by santoshdahal12** [comment]
I have tried so many times.  I cant query normally like I do with source-filesystem. It always fails to start. Should I push the code to a branch .
 
The following is the query in my index.js to list all the posts. It fails to get allMarkdownRemark although the files are in .cache folder.
 ``` 
allMarkdownRemark(sort:{order:DESC,fields:[frontmatter___date]}) {
    edges {
      node {
        timeToRead
        frontmatter {
          excerpt
          title
          path
          date(formatString: "MMMM Do, YYYY")
          tags
          featuredImage {
            childImageSharp {
              fluid(maxWidth: 400) {
                ...GatsbyImageSharpFluid
              }
            }
        }
        featuredImgAlt
        featuredImgSrc
        }
      }
    }
  }
}
`
```

**Comment by LekoArts** [comment]
Yeah, please create a [minimal reproduction][reproduction]. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by santoshdahal12** [comment]
I cant share my auth token for pulling static files from github.  I am going with basic, easy way of putting everything in single repo. Looks like I will need to dig little more if I have to go this route and have very less time.  Thanks.
