### ISSUE TITLE
gatsby-image: what is the difference between Image and Img ?

### ISSUE THREAD

**Issue by apolopena** [gatsbyjs/gatsby#22184]
Both `Image` and `Img`, I am wondering what the difference is I have a gatsby starter with:
`import Image from 'gatsby-image';`
and then using the `Image` tag in the code.

but everywhere in the docs I see only this implementation:
`import Img from 'gatsby-image';`
and then using the `Img` tag in the code

Both implementations seems to work the same.

I looked in the [source code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js) for `gatsby-image` and the differences were not apparent to me. I also could not find anything about this in the documentation.

Thanks.

**Comment by jonniebigodes** [comment]
@apolopena it's just the name of the component/module that is being exported. Both are the same, it's just a matter of how the documentation author and author of the starter called it in the imports. Technically you could even call it `banana` that it wouldn't matter.

**Comment by smthomas** [comment]
@apolopena I think @jonniebigodes answered the question. The Gatsby docs prefers using `Img` but it's really just a preference as the name you give the component when importing doesn't matter. 

If you have additional questions, please re-open this issue.

**Comment by apolopena** [comment]
Thanks!
