### ISSUE TITLE
Can I source "a record of built pages" from anywhere?

### ISSUE THREAD

**Issue by k4y4k** [gatsbyjs/gatsby#22193]
## Summary
I have a tiny $5 Droplet that limps along when building my ~200-page site on Drone CI - so I'm looking for any way (other than upgrading :joy:) to speed this up. I've come across [this page in the docs](https://www.gatsbyjs.org/docs/page-build-optimizations-for-incremental-data-changes/) and, while this all seems well and good, I have a question about this line specifically:

> You may want to retrieve a list of the pages that were built. For example, if you want to perform a sync action in your CI/CD pipeline.

## Relevant information

From what I understand, I can run `gatsby build --write-to-file` to generate records in `.cache/`, but I'd like to know if I have to:
(a) manually script some sort of hack to retrieve this file from "staging", or;
(b) if I can specify a path for Gatsby to look in for it.

Ideally I'd love (b) but I suppose I can do (a). 

#### CI/CD workflow

- commit to my Gitea instance;
- commit picked up by Drone CI;
- Drone CI clones the repo;
- Drone builds the site with `gatsby build`;
- Drone rsyncs the build results to my staging area;
- A new Docker container is built from these results and deployed;

Thanks for reading!

**Comment by pieh** [comment]
Hey @k4y4k! The feature / docs you linked to are in experimental phase and was actually very recently released, so there are rough edges there.

Gatsby right now just output those files when using a flag (`newPages.txt` and `deletedPages.txt`) and for now it's up to you / your CI setup to make use of them. Gatsby doesn't take any input from that files - those are more of a "report" style thing or output that can let you deploy incrementally (but that does need custom code to do)

**Comment by k4y4k** [comment]
Ah, cheers fam :smile:. Yeah, I was afraid you might say that, but oh well. Cheers!
