### ISSUE TITLE
Webpack "window is not defined" error when using gatsby-plugin-layout and Pts.js

### ISSUE THREAD

**Issue by gusbmurphy** [gatsbyjs/gatsby#22190]
## Summary

I've been working on my first Gatsby site (a personal site), and am attempting to use the creative visual library [Pts.js](https://ptsjs.org/) to have some stuff going on in the background. It's important to me that the artwork isn't interrupted when navigating to different pages, so I've gone ahead and tried to implement `gatsby-plugin-layout`, however I'm now getting an error on build: `WebpackError: ReferenceError: window is not defined`. I've attempted a few things like using `typeof window !== 'undefined'` or using `detect-node` (as outlined [here](https://www.npmjs.com/package/detect-node)), but I'm pretty stumped.

## Relevant information

I've worked out a decent reproduction using the Gatsby default starter, which is on my Github [here](https://github.com/gusbmurphy/gatsby-window-error-repro). If you build that version, you should get the Webpack error that I mentioned above. However, if you comment out lines 15 and 55 through 60 in `layout.js`, it will build without error. Once it's built, you can uncomment those lines and the artwork (an example from Pts.js) should be in the background. I'm assuming this has everything to do with how the layout is being rendered on the server, and as I said before I have no idea where to go from here! Thanks in advance for your time and attention!

### Environment (if relevant)

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 48.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7 
    gatsby-image: ^2.2.39 => 2.2.39 
    gatsby-plugin-layout: ^1.1.23 => 1.1.23 
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39 
    gatsby-plugin-offline: ^3.0.32 => 3.0.32 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21 
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3 
    gatsby-source-filesystem: ^2.1.46 => 2.1.46 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13 
  npmGlobalPackages:
    gatsby-cli: 2.8.18
    gatsby: 2.19.21

### File contents (if changed)

`gatsby-config.js`: 
```
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-plugin-layout`,
      options: {
        component: require.resolve(`${__dirname}/src/components/layout`),
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    }
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
```

`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by jonniebigodes** [comment]
@gusbmurphy if you don't mind i can take a look at it tomorrow and possibly come back with a response. Do you mind waiting a bit?

**Comment by gusbmurphy** [comment]
@jonniebigodes no rush at all! Thanks for the quick response.

**Comment by pieh** [comment]
Best bet here is that Ptj.js tries to use `window` object at import time.

I would suggest using something like `React.lazy` and dynamically import `bg-art.js` (from repro). This should prevent trying the render of ptj.js in SSR

**Comment by gusbmurphy** [comment]
@pieh that seems to have done it! Thanks so much Michal, and also @jonniebigodes. I essentially copy-pasted the example from [React's docs on code splitting](https://reactjs.org/docs/code-splitting.html). Good to know it's something so simple and well-implemented.
