### ISSUE TITLE
Bypass react router path matching

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#222]
I discovered recently that react-router can be very slow at matching routes https://github.com/reactjs/react-router/issues/3215

This will soon be (mostly) fixed but there'll still be 10-15 milliseconds spent matching the router (that's on a 2015 MBP so much much slower on an old android) that we should avoid.

[We can load our own routing table into the browser and match path changes against that](https://github.com/reactjs/react-router/issues/3215#issuecomment-199517321) which will drop path matching times down to microseconds.

This will also probably make code splitting more convenient #10

**Comment by taion** [comment]
This will be cleaner with https://github.com/reactjs/react-router/issues/3262.

**Comment by taion** [comment]
As of React Router v2.2.0, `getComponent` now gets called with the router state, including `params`.

**Comment by KyleAMathews** [comment]
This is great! Thanks!

**Comment by KyleAMathews** [comment]
Closing as very old
