### ISSUE TITLE
Color of text in WSL terminal such that it is invisible after running gatsby develop

### ISSUE THREAD

**Issue by rnwolf** [gatsbyjs/gatsby#22207]
## Color of text in WSL terminal such that it is invisible after running gatsby develop

Using Gatsby in WSL2/ubuntu environment, and when I run `gatsby develop` and then escape to the terminal prompt again, the terminal text color is such that I cannot see the text that is typed. 

### Steps to reproduce

I am using https://github.com/rnwolf/rnwolf.net.github.io
cd ~
cd rnwolf.net.github.io
gatsby develop
press Ctrl-c
Now anything typed at the terminal prompt is invisible.

I am able to workaround this by using the `reset` command
https://askubuntu.com/questions/443560/how-do-i-reset-the-colors-of-my-terminal/443561#443561

### Expected result

I would expect to see text typed at the terminal prompt.

### Actual result

Text is not visible.

### Environment

Windows 10 and WSL2

System:
    OS: Linux 4.19 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.19.2 - /mnt/c/Users/rnwol/scoop/apps/yarn/current/Yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 3.7.6 - /home/rnwolf/.pyenv/shims/python
  npmPackages:
    gatsby: ^2.13.55 => 2.13.55
    gatsby-cli: ^2.10.9 => 2.10.9
  npmGlobalPackages:
    gatsby-cli: 2.10.0

**Comment by pieh** [comment]
Would use `--no-color` switch help here? to avoid gatsby from having any color outputs?

**Comment by rnwolf** [comment]
No that does not seem to work. Just to add the colours have been removed from the output to the screen. 
I still need to `reset` in order to see typing at the terminal.

![Annotation 2020-03-12 150030](https://user-images.githubusercontent.com/117415/76535198-67475980-6472-11ea-8559-a74e1ac1a38d.png)

**Comment by vladar** [comment]
@LekoArts I am curious have you seen something like this on WSL?

**Comment by LekoArts** [comment]
No, I never run into this. Neither in VSCode internal terminal nor while using ConEmu. WSL sometimes has hiccups so I do a 'Ctrl + C' two or three times. But I always saw the text.

**Comment by holm** [comment]
I am seeing the exact same behaviour. After running "gatsby develop" my terminal is not showing any text I type.
