### ISSUE TITLE
something questions about graphql

### ISSUE THREAD

**Issue by FourEyebrowXiake** [gatsbyjs/gatsby#2220]
export const pageQuery = graphql`
  
`
what does it means?  is "graphql``"  a string?

Do `` have a difference with ''?

**Comment by swim** [comment]
Hello,

hopefully these resources will answer the above.
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
- http://graphql.org/learn/queries/#fields

**Comment by FourEyebrowXiake** [comment]
I know that Gatsby used redux.But ,where is the containers? where is reducers? How can components accept the props Redux pass over.

**Comment by FourEyebrowXiake** [comment]
@swim  I know that Gatsby used redux.But ,where is the containers? where is reducers? How can components accept the props Redux pass over.

**Comment by KyleAMathews** [comment]
Gatsby doesn't use redux in the client. Redux is used during the gatsby bootstrap during development and builds but it's not something you normally work with.

**Comment by FourEyebrowXiake** [comment]
@KyleAMathews  How do i know the redux in gatsby.  Where should i start?
And [this](https://github.com/gatsbyjs/gatsby/issues/2276) is my new question, can you help me?

**Comment by KyleAMathews** [comment]
Copy what the "using-redux" example site does.
