### ISSUE TITLE
texts gets highlighted when clicking on not related area

### ISSUE THREAD

**Issue by luishocke** [gatsbyjs/gatsby#22208]
## Description

When clicking and dragging somewhere on a page, text that is above gets highlighted, even if there is no relation between the element (if any) where the click/drag event happens and the text element.

### Steps to reproduce
1) create project or use [https://gatsby-starter-hello-world-demo.netlify.com/](url)
1a) 
`gatsby new gatsby-starter-hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world` 
1b) 
 `gatsby develop`
1c) navigate to [http://localhost:8000](url)

2) click and drag somewhere below the "Hello World" text

### Expected result

What should happen?
Nothing should happen

### Actual result
Texts gets selected, you can drag it etc

### Environment
any (?)

**Comment by pieh** [comment]
This is not Gatsby issue - if you have following html snippet (no gatsby):

```html
<html>
  <body>
    hello world
  </body>
</html>
```

It will behave the same:
![Kapture 2020-03-12 at 15 42 24](https://user-images.githubusercontent.com/419821/76533284-1dfa0880-6478-11ea-8b95-d8a198a195c9.gif)
