### ISSUE TITLE
Broken built by url in sites.yml

### ISSUE THREAD

**Issue by jbampton** [gatsbyjs/gatsby#22215]
Hey @marcfehr your built by url is broken.  

Should it be [https://www.marcfehr.ch/](https://www.marcfehr.ch/)

https://github.com/gatsbyjs/gatsby/blob/eb94fe9d4bbe4a51e03127d3596a92838fba8176/docs/sites.yml#L7521

**Comment by marcfehr** [comment]
Thanks, added pull request for this.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
