### ISSUE TITLE
Can't access contentful space from gastby.

### ISSUE THREAD

**Issue by mujeex** [gatsbyjs/gatsby#22211]
## Description

I have been trying to get my gatsby project to connect to my contentful space. I made sure I added all the required fields (spaceId, accesstoken) in the config files, but I keep on getting the following error message.
```
Accessing your Contentful space failed.
Try setting GATSBY_CONTENTFUL_OFFLINE=true to see if we can serve from cache.

Used options:
spaceId: "*********ppq"
accessToken: "*********************************************z13o"
downloadLocal: true
environment: "develop"
host (default value): "cdn.contentful.com"
localeFilter (default value): [Function]
forceFullSync (default value): false
pageLimit (default value): 100
useNameForId (default value): true
```

### Steps to reproduce

Here is a bug repo to reproduce the error.
https://github.com/mujeex/gatsby-bug-repo
### Expected result

I expected the site to build successfully without any issues.

### Actual result

Encountered this error.
```
Accessing your Contentful space failed.
Try setting GATSBY_CONTENTFUL_OFFLINE=true to see if we can serve from cache.
```

### Environment
 System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.10.0 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 80.0.3987.132
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.32 => 2.19.32
    gatsby-background-image: ^0.8.0 => 0.8.0
    gatsby-image: ^2.1.4 => 2.1.4
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5
    gatsby-plugin-manifest: ^2.2.44 => 2.2.44
    gatsby-plugin-netlify: ^2.1.34 => 2.1.34
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.1.9 => 2.1.9
    gatsby-source-contentful: ^2.1.92 => 2.1.92
    gatsby-source-filesystem: ^2.0.43 => 2.0.43
    gatsby-transformer-remark: ^2.6.32 => 2.6.32
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.10.4

**Comment by pieh** [comment]
Do you have `develop` environment in your contentful space?

Our contentful example site ( https://github.com/gatsbyjs/gatsby/tree/master/examples/using-contentful ) is working correctly, so this have to be configuration issue.

**Comment by mujeex** [comment]
> Do you have `develop` environment in your contentful space?
> 
> Our contentful example site ( https://github.com/gatsbyjs/gatsby/tree/master/examples/using-contentful ) is working correctly, so this have to be configuration issue.

Yes I do have that configured in my contentful space.

**Comment by mujeex** [comment]
> Do you have `develop` environment in your contentful space?
> 
> Our contentful example site ( https://github.com/gatsbyjs/gatsby/tree/master/examples/using-contentful ) is working correctly, so this have to be configuration issue.

I don't think this issue was encountered in the version of the gatsby-source-contentful plugin used in your project. It worked perfectly fine in version 2.1.42

**Comment by pieh** [comment]
I used latest version of `gatsby-source-contentful` - `2.1.96`

**Comment by mujeex** [comment]
Mine is 2.1.92. Let me try getting it to your version and see how it goes.

**Comment by mujeex** [comment]
Still not working after upgrading to the latest

**Comment by pieh** [comment]
Hmm it does here regardless of using environment (other than default `master`). Do you have your access token setup to be allowed in this `develop` environment? By default previous access tokens doesn't seem to be allowed for other branches in Contentful (branches other than `master` were ticked off for me). So initially I saw same message, but after fixing access token in contentful to allow for other envs - it worked.

![Screenshot 2020-03-12 at 17 56 08](https://user-images.githubusercontent.com/419821/76546101-34f62600-648b-11ea-81cb-09b42adea3e0.png)

**Comment by mujeex** [comment]
> Hmm it does here regardless of using environment (other than default `master`). Do you have your access token setup to be allowed in this `develop` environment? By default previous access tokens doesn't seem to be allowed for other branches in Contentful (branches other than `master` were ticked off for me). So initially I saw same message, but after fixing access token in contentful to allow for other envs - it worked.
> 
> ![Screenshot 2020-03-12 at 17 56 08](https://user-images.githubusercontent.com/419821/76546101-34f62600-648b-11ea-81cb-09b42adea3e0.png)

Yes, I made sure I ticked both environments as well. I initially didn't even create any other environment, and was using the **master** env as the default, then I tried to add another env to see if the problem was from my **master** env which turned out to not be the case.

**Comment by mujeex** [comment]
This is really weird as I have another site fetching data from the contentful space with no issues whatsover.

**Comment by mujeex** [comment]
Okkk... It works now! Turns out I was using a **personal access token**

**Comment by mujeex** [comment]
Sorry for all the troubles. It's safe to say that updating to the latest version of the **gatsby-contentful-plugin** solved this problem for me, because I only switched to trying **personal access token** when I exhausted all the approaches using the default content delivery API
