### ISSUE TITLE
Provide better explanation of staleness during page loading

### ISSUE THREAD

**Issue by herecydev** [gatsbyjs/gatsby#22229]
## Summary

Gatsby has a mechanism to prevent staleness by forcing a `window.location` refresh when the site has changed on the server-side. This isn't an obvious behavior, or at least not for me initially. Gatsby acts like a SPA until the point it detects a content change. This can be problematic if the site is being used to track any state, e.g. Redux.

What adds to the problem is that it only happens for _new_ pages **and** when the content has changed, so it can be difficult to understand the nature of it's occurence

### Motivation

Adding some documentation might help others down the line

**Comment by KyleAMathews** [comment]
Curious to hear more about what problems this causes. Do you only load data into redux on certain routes? People can refresh the app at any moment which is the same thing as Gatsby triggering a refresh on a route change right?

Also is this during clientside routes? I can see us not triggering refreshes there as being a good thing as no content is changing while there

**Comment by herecydev** [comment]
> Curious to hear more about what problems this causes. Do you only load data into redux on certain routes? 

As a hypothetical example: A pet store selling pet products. Each product has it's own route and pages are generated for them (SEO + perf benefits 👍 ). A typical flow looks like the following:

Lands on pet product page => chooses to purchase => goes to payment details screen => payment is handed off to paypal/stripe

During the payment details screen they need to enter some brief personal details (simple form). In a "regular SPA" it's trivial to track the details in state, so navigating around won't lose that user details and they can simply proceed once happy. In Gatsby the following situation becomes problematic:

Lands on pet product page => chooses to purchase => goes to payment details screen and fills in some data => goes back to product to double check => (new site gets deployed in background) => user sees alternative pet product and clicks link => hard reload and state is lost

>People can refresh the app at any moment which is the same thing as Gatsby triggering a refresh on a route change right?

It would have the same effect, but I think few people would be surprised to see data lost when _they_ triggered a reload. Data loss when the user was navigating through the site seems off though.
