### ISSUE TITLE
Hash Params, after OpenID Redirect

### ISSUE THREAD

**Issue by mbwatson** [gatsbyjs/gatsby#22221]
## Summary

I'm attempting to integrate a Gatsby app with an external authentication tool that uses OIDC. I link over to their external login page, enter credentials, log in, then the redirect URL contains a bunch of hash parameters, `token_type`, `id_token`, etc.

The problem I'm having is that Gatsby seems to want to check the DOM for an element with an ID given by the hash string appended to the redirect URL. The error 
```
Document.querySelector: '#token_type=Bearer&id_token=eyJ...Y1st5OQ' is not a valid selector
```
is thrown, and the page never renders.

I can grab those parameters from the URL with `location.hash` if I link directly within my app with a `<Link/>` component like
```
<Link to="/path/to/page/#token_type=Bearer&id_token=eyJ...Y1st5OQ">Click here!</Link>
```
but the hash params string seems to get in the way when coming in from the redirect.

Is there something I'm doing wrong to handle this, or is there a simple workarouund? I'm guessing  I may need to intercept the request to remove the hash parameters before the page is built so I can let the page render as it should and pass those params, for example, as props to the page to use within it.

**Comment by mbwatson** [comment]
So I realized this is in conflict with the plugin 'gatsby-plugin-anchor-links'. I suppose a workaround would be to tell that plugin to ignore the redirect route from my OIDC provider.

**Comment by LekoArts** [comment]
So can you confirm that when removing the said plugin it works as expected? If yes, I'd recommend closing this issue and opening an issue on the plugin's repo.

**Comment by mbwatson** [comment]
yes, thanks for the reminder. [i did do that](https://github.com/brohlson/gatsby-plugin-anchor-links/issues/4) and forgot to close this. closing now. thanks!
