### ISSUE TITLE
gatsby-transformer-remark not surport node v13.8

### ISSUE THREAD

**Issue by frank-26** [gatsbyjs/gatsby#22239]
I think this need update.

**Comment by LekoArts** [comment]
Thank you for opening this!

Please follow our issue template for filing a bug, especially the section about creating a minimal reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

Feel free to open a new issue where you followed these instructions and included such a project. Thanks!
