### ISSUE TITLE
XMLHttpRequest cannot load http://localhost:8000/page-data/app-data.json due to access control checks.

### ISSUE THREAD

**Issue by igigi** [gatsbyjs/gatsby#22235]
## Description

safari don't work, chrome is ok

safari debug display " XMLHttpRequest cannot load http://localhost:8000/page-data/app-data.json due to access control checks."

"XMLHttpRequest cannot load http://localhost:8000/page-data/qrcode/page-data.json due to access control checks."

### Steps to reproduce
1. open https://smallsticker.com website, add a product to cart.
2. open cart, click "结算".
3. input order information, "支付方式" field select "微信支付"
4. submit order, bug display

### Expected result

display a qrcode picture

### Actual result

display a qrcode content

### Environment

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 62.0.3
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.5.0 => 2.17.9
    gatsby-image: ^2.0.41 => 2.2.30
    gatsby-plugin-algolia: ^0.3.4 => 0.3.4
    gatsby-plugin-emotion: ^4.0.6 => 4.1.13
    gatsby-plugin-google-analytics: ^2.0.20 => 2.1.24
    gatsby-plugin-layout: ^1.0.15 => 1.1.13
    gatsby-plugin-manifest: ^2.1.1 => 2.2.26
    gatsby-plugin-offline: ^2.1.0 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.13
    gatsby-plugin-sharp: ^2.0.37 => 2.2.36
    gatsby-source-strapi: ^0.0.10 => 0.0.10
    gatsby-transformer-sharp: ^2.1.19 => 2.3.2
  npmGlobalPackages:
    gatsby-cli: 2.8.8

**Comment by JustFly1984** [comment]
well, it is not a bug of Gatsby, you need to run localhost:8000 with HTTPS.

**Comment by igigi** [comment]
> well, it is not a bug of Gatsby, you need to run localhost:8000 with HTTPS.

The production environment with HTTPS is same bug.

"XMLHttpRequest cannot load https://www.smallsticker.com/page-data/qrcode/page-data.json due to access control checks."

"XMLHttpRequest cannot load https://www.smallsticker.com/page-data/app-data.json due to access control checks.

**Comment by JustFly1984** [comment]
Do you have static page qrcode, or is it dynamic page?

**Comment by JustFly1984** [comment]
If I remember correctly, Link component imported from gatsby preloads data with added functionality. Try to import Link from @reach/router directly for dynamic pages.
Sorry can’t type code from phone, will publish something to npm later

**Comment by igigi** [comment]
> Do you have static page qrcode, or is it dynamic page?

It is page, should be dynamic, display a QR code with attributes through link

**Comment by igigi** [comment]
> If I remember correctly, Link component imported from gatsby preloads data with added functionality. Try to import Link from @reach/router directly for dynamic pages.
> Sorry can’t type code from phone, will publish something to npm later

I will try it, thank you! But why is chrome ok?

**Comment by igigi** [comment]
> well, it is not a bug of Gatsby, you need to run localhost:8000 with HTTPS.

The production environment is same bug.

"XMLHttpRequest cannot load https://www.smallsticker.com/page-data/qrcode/page-data.json due to access control checks."

"

> > If I remember correctly, Link component imported from gatsby preloads data with added functionality. Try to import Link from @reach/router directly for dynamic pages.
> > Sorry can’t type code from phone, will publish something to npm later
> 
> I will try it, thank you! But why is chrome ok?

just check code, go to the page is not through "Link", it is through "navigate". how to do it?

**Comment by TylerBarnes** [comment]
Hi @igigi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by igigi** [comment]
> Hi @igigi!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

This is source code https://github.com/smallsticker/smallsticker-client.

it is base on Gatsby store, add order fix service, you can build it directly.

### Steps to reproduce
1. open https://smallsticker.com website, add a product to cart.
2. open cart, click "结算".
3. input order information, "支付方式" field select "微信支付"
4. submit order, bug display

Thanks!
