### ISSUE TITLE
Gatsby Cloud builds should not fail on deprecation warnings

### ISSUE THREAD

**Issue by styxlab** [gatsbyjs/gatsby#22238]
# Description

Deprecation warnings from the Node environment should not lead to failing Gatsby Cloud builds.
Currently [gatsby-starter-try-ghost](https://github.com/styxlab/gatsby-starter-try-ghost) is hit by #18433. As this is only a warning, it should not lead to failing builds on Gatsby Cloud.

# Reproduction

Simply try to build a starter affected by #18433, e.g. [gatsby-starter-try-ghost](https://github.com/styxlab/gatsby-starter-try-ghost) on Gatsby Cloud and observe the build logs.

# Solution

I'm not sure if this should be solved in the Gatsby Cloud environment or in `Gatsby CLI`. It seems wrong that `Gatsby CLI` is issuing an `ERROR` in case of these warnings. However, when you build locally, the build finishes correctly.

**Comment by styxlab** [comment]
gatsbyjs/gatsby/issues/#22238

**Comment by LekoArts** [comment]
Thank you for opening this!

Please contact support@gatsbyjs.com - the repository is not the right place for inquiries about Gatsby Cloud.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by styxlab** [comment]
I think this issue should be kept open as it looks like a `Gatsby-cli` issue and is probably best solved here.
