### ISSUE TITLE
gatsby-source-filesystem's publicURL should keep file name

### ISSUE THREAD

**Issue by KoltesDigital** [gatsbyjs/gatsby#22244]
## Summary

Change the file publicURL pattern from `${file.name}-${file.internal.contentDigest}${details.ext}` to `${file.internal.contentDigest}/${file.base}`.

https://github.com/gatsbyjs/gatsby/blob/2c089098a841fc74c4db57cc111ebf68988f3397/packages/gatsby-source-filesystem/src/extend-file-node.js#L17

### Motivation

My concern is that files which should be downloaded are renamed, and visitors shouldn't know about that.

Right now, if I'm giving a link to say `Brand-ProductCatalog.pdf`, the link actually points to `/static/Brand-ProductCatalog-f4c0ceb6e2839acca98c07d3839833e4.pdf`, and this looks weird if someone downloads it and see the digest in their finder.

If instead I'm putting the link in a .md file, thanks to `gatsby-remark-copy-linked-files` the path is `/static/f4c0ceb6e2839acca98c07d3839833e4/Brand-ProductCatalog.pdf` which is what I want: the filename isn't changed.

But I want to do it directly, without having to put the link in a .md file.

This problem was mentioned at https://github.com/gatsbyjs/gatsby/pull/9777#issuecomment-445879392 but I can't find a commit that changes this.

**Comment by KoltesDigital** [comment]
Well, even though the link href is exactly the same, the manual link opens the 404 page, and when the browser reloads it opens the PDF (using the component Link imported from gatsby), whereas with the Markdown link the PDF opens directly. And I can't see any hook in the code.

**Comment by KoltesDigital** [comment]
Ah I shouldn't use `Link` actually. It makes sense. Using `a` instead, both work fine.

I can make a PR if you want. It's only about this single line.

**Comment by LekoArts** [comment]
We'd appreciate a PR fixing this. Thanks a lot!

**Comment by KoltesDigital** [comment]
Here's the PR!
