### ISSUE TITLE
Fix typos across project

### ISSUE THREAD

**Issue by shivaylamba** [gatsbyjs/gatsby#22241]
## Description
A lot of typos across docs. 

### Expected result
Typos are resolved.

### Actual result
Typos are resolved

**Comment by vladar** [comment]
Thanks for the suggestion. I think it would be helpful to mention at least several examples so that other people at least knew where to start?

**Comment by LekoArts** [comment]
Let's close this issue. If you found a typo feel free to open a PR. Thanks!
