### ISSUE TITLE
gatsby-plugin-sitemap returned an error ==>   SyntaxError: Unexpected template string

### ISSUE THREAD

**Issue by Abderrahmenla** [gatsbyjs/gatsby#22243]
### Description
executing gatsby build command fails after adding , gatsby-plugin-sitemap .

### Steps to reproduce
![1](https://user-images.githubusercontent.com/29304794/76621622-20b83480-6530-11ea-955f-2f52aa4f1132.png)

### Expected result
Build must be successful with sitemap.xml file created

### Actual result
Getting Error

error Plugin gatsby-plugin-sitemap returned an error
SyntaxError: Unexpected template string

### Environment

  System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v13.7.0/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: 74.0
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-background-image: ^0.10.1 => 0.10.1
    gatsby-image: ^2.2.41 => 2.2.41
    gatsby-plugin-manifest: ^2.2.47 => 2.2.47
    gatsby-plugin-playground: ^1.0.6 => 1.0.6
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5
    gatsby-plugin-sitemap: ^2.2.29 => 2.2.29
    gatsby-plugin-styled-components: ^3.1.19 => 3.1.19
    gatsby-plugin-transition-link: ^1.17.7 => 1.17.7
    gatsby-source-contentful: ^2.1.86 => 2.1.86
    gatsby-source-filesystem: ^2.1.48 => 2.1.48
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14
  npmGlobalPackages:
    gatsby-cli: 2.10.9

**Comment by vladar** [comment]
I think you need another `}` on line 46? The one on line 45 is for `options` key, not for the whole `gatsby-plugin-robots-txt` plugin section.

**Comment by Abderrahmenla** [comment]
It works now...I didn't pay attention to the missing '}',thanks man ^^
