### ISSUE TITLE
gatsby-plugin-offline: Cannot overwrite workboxConfig.runtimeCaching

### ISSUE THREAD

**Issue by Enter-tainer** [gatsbyjs/gatsby#22264]
## Description

Cannot overwrite `workboxConfig.runtimeCaching`.

### Steps to reproduce

Install `gatsby-plugin-offline` and use the config below. And then open the generated `sw.js`, and you will find that the default options of runtimeCaching are not overwritten.

### Expected result

```
plugins: [
    {
      resolve: `gatsby-plugin-offline`,
      options: {
        workboxConfig: {
          runtimeCaching: [{
            // I expected that this rule will overwrite the default ones.
            urlPattern: /^https?:.*\.(png|jpg|jpeg|webp|svg|gif|tiff|woff|woff2|css)$/,
            handler: `NetworkOnly`,
          },]
        }
      },
    },
]
```

What should happen?

I expected that my own rule will **overwrite** the default ones.

### Actual result

When I want to overwrite the default `runtimeCaching`, I find it impossible, because `_.merge()` do **merge** the two object. See code [here](https://github.com/gatsbyjs/gatsby/blob/4d25f4a24e5fcf48265992eb99a61f0bbfb60ac2/packages/gatsby-plugin-offline/src/gatsby-node.js#L154).

### Environment

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.1 - D:\Software\msys2\mingw64\bin\python.EXE
  Browsers:
    Edge: 44.18362.449.0
```

This issue is similar with #19029, but that issue do not contain any useful infomations.

**Comment by Enter-tainer** [comment]
Lodash's `_.merge` performs weirdly on arrays:

```
>> _.merge([1, 2, 3], ['a', 'b'])
<- Array(3) [ "a", "b", 3 ]
```

**Comment by LekoArts** [comment]
Since the related PR was closed, also close this :)

**Comment by Enter-tainer** [comment]
Actually the issue is not solved. Have you seen [this reply](https://github.com/gatsbyjs/gatsby/pull/22266#issuecomment-601478745)?

**Comment by Enter-tainer** [comment]
Changing the merging policy maybe is not enough, my own workaround for this issue is adding more than 3 routing strategies to completely overwrite the default ones.

**Comment by LekoArts** [comment]
Ah, okay!
