### ISSUE TITLE
process.env is an empty object

### ISSUE THREAD

**Issue by algebrathefish** [gatsbyjs/gatsby#22277]
I am trying to access env variables on development environment

I added dotenv to gatsby config, and created a .env.development file with

`GATSBY_API_URL=https://dev.example.com/api`

as stated https://www.gatsbyjs.org/docs/environment-variables/

When I console log process.env it is an empty object

### Environment (if relevant)

Gatsby CLI version: 2.8.30
Gatsby version: 2.19.7
Node v13.7.0

  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 AMD A6-3670 APU with Radeon(tm) HD Graphics
  Binaries:
    Node: 13.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.2.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /c/Python27/python
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7 
    gatsby-image: ^2.2.39 => 2.2.39 
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39 
    gatsby-plugin-offline: ^3.0.32 => 3.0.32 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21 
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3 
    gatsby-source-filesystem: ^2.1.46 => 2.1.46 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13 

  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 AMD A6-3670 APU with Radeon(tm) HD Graphics
  Binaries:
    Node: 13.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.2.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /c/Python27/python
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7 
    gatsby-image: ^2.2.39 => 2.2.39 
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39 
    gatsby-plugin-offline: ^3.0.32 => 3.0.32 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21 
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3 
    gatsby-source-filesystem: ^2.1.46 => 2.1.46 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13 

### File contents (if changed)

`gatsby-config.js`: 

```
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
});
module.exports = {
  // ...
}
```

`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by DSchau** [comment]
Hi @algebrathefish!

This is intentional, so that variables aren't accidentally linked/viewable and the "plucking" of them is deliberate.

In other words -- if you log `process.env.GATSBY_API_URL` that will contain the value you want. Technically we do this by iterating through all the GATSBY_ environment variables, and use Webpack's definePlugin to make these "strings" available.

So, long answer short -- the solution is to grab the variable you want a la

```js
const url = process.env.GATSBY_API_URL // this should be defined
```

Hope this helps! Thanks!

**Comment by algebrathefish** [comment]
Thank you @DSchau !! yes, it Helps

**Comment by algebrathefish** [comment]
@DSchau it is undefined unless I do

`NODE_ENV=development gatsby develop `

it seems the .env.* file is ignored

**Comment by DSchau** [comment]
@algebrathefish what's your gatsby-config.js look like? That shouldn't be necessary since Gatsby sets that environment variable by default.

**Comment by algebrathefish** [comment]
@DSchau 

```
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
});

module.exports = {
  siteMetadata: {
    title: ``,
    description: ``,
    author: ``,
  },

  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-stylus`,
    `gatsby-plugin-postcss`,   
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,

  ],

}
```

Thanks

**Comment by j127** [comment]
> In other words -- if you log process.env.GATSBY_API_URL that will contain the value you want. Technically we do this by iterating through all the GATSBY_ environment variables, and use Webpack's definePlugin to make these "strings" available.

It seems like something recently broke with this.

I used to do things like:

```
const { SOME_VAR } = process.env;
```

but that is now undefined. It seemed to have stopped working within the past couple of weeks, because I can see that it was working in August.

There might be a lot of sites out there that are silently breaking at the moment.

**Comment by rarest-adam** [comment]
> > In other words -- if you log process.env.GATSBY_API_URL that will contain the value you want. Technically we do this by iterating through all the GATSBY_ environment variables, and use Webpack's definePlugin to make these "strings" available.
> 
> It seems like something recently broke with this.
> 
> I used to do things like:
> 
> ```
> const { SOME_VAR } = process.env;
> ```
> 
> but that is now undefined. It seemed to have stopped working within the past couple of weeks, because I can see that it was working in August.
> 
> There might be a lot of sites out there that are silently breaking at the moment.

Yes, same for me! I had a wrapper function `process.env[SOME_VAR]` and it's broken now
