### ISSUE TITLE
How to overwrite ESLint rules

### ISSUE THREAD

**Issue by algebrathefish** [gatsbyjs/gatsby#22285]
## Relevant information

I tried with the steps here: https://www.gatsbyjs.org/docs/eslint/

`npm install --save-dev eslint-config-react-app`
Created the` .eslintrc.js` file

The file´s content looks like this

```
module.exports = {
  globals: {
    __PATH_PREFIX__: true,
  },
  extends: `react-app`,
  "rules": {
    'jsx-a11y/no-static-element-interactions': [
      'error',
      {
        handlers: [
          'onClick',
          'onMouseDown',
          'onMouseUp',
          'onKeyPress',
          'onKeyDown',
          'onKeyUp',
        ],
      },
    ],
  }
}
```

When I do that normal errors like unused vars or imports cease showing.

I would like to know what I am doing wrong. Thank you

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

> When I do that normal errors like unused vars or imports cease showing.

You're extending `react-app` (eslint-config-react-app) which contains those rules: https://unpkg.com/browse/eslint-config-react-app@5.2.0/index.js

If you don't want them or want to use another ruleset to extend, you'll need to handle that yourself by e.g. disabling those warnings/errors or installing a different preset.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by algebrathefish** [comment]
Hi @LekoArts thanks for answering

What I want to achieve is to have the same rules that come with the gatsby starter except for `'jsx-a11y/no-static-element-interactions' `which I want to overwrite

**Comment by stevenkkim** [comment]
@arualana I think you need to also install https://www.gatsbyjs.org/packages/gatsby-plugin-eslint/

I had a similar issue and tried following https://www.gatsbyjs.org/docs/eslint/ like you did. I finally got mine to work after installing and configuring gatsby-plugin-eslint
