### ISSUE TITLE
Yes, remark-images options should be configurable in theme-blog-core.

### ISSUE THREAD

**Issue by DavidSabine** [gatsbyjs/gatsby#22282]
## Reference

I am referring to the comment on this line of `gatsby-config.js` in `gatsby-theme-blog-core` package:
 https://github.com/gatsbyjs/gatsby/blob/6874ccad594c67d87de6d5030a900a32ee834558/packages/gatsby-theme-blog-core/gatsby-config.js#L32

## Summary

That comment in the source code is evidence that the thought has crossed others' minds. I appreciate that.

## Motivation

I have a small blog. Perhaps 15 articles in total. I use gatsby-theme-blog-core, MDX, and so on. [live site here](https://scrum.works/articles) (I love it, btw)

Each article has only a couple of images. When images are generated during `gatsby develop` or `gatsby build`, this plugin processes approximately 2 dozen original files *to render more than 290 images*. It takes 102 seconds on average.

This is *very* problematic when editing the blog articles (MDX files) because gatsby watches for changes and tries to hot-reload the browser. That, of course, triggers the process to recreate images and, as you might expect, that process never completes in time for yet another edit will trigger the process again. And again.

And the problem is compounded with every article I add to the blog. I can't imagine how others are managing with perhaps 100 or more articles in their blog.

*If these settings were exposed and configurable:* In `develop` mode, I could perhaps adjust quality to 10 or maxWidth to 300 and it may speed the process enough to not interrupt editing too badly.

*Or even better:* if `srcSetBreakpoints` were configurable here then one could tune the setting so that a minimal number of images are produced.

**Comment by LekoArts** [comment]
Thank you for opening this!

The options is already configurable more or less. You'll need to set `mdxOtherwiseConfigured` to true and copy/paste the config of `gatsby-plugin-mdx` into your own config. This is a workaround until we find a reasonable API to expose such plugin options. Because surfacing every option as public API isn't an option really.

Hence this issue could be closed really.

> This is very problematic when editing the blog articles (MDX files) because gatsby watches for changes and tries to hot-reload the browser. That, of course, triggers the process to recreate images and, as you might expect, that process never completes in time for yet another edit will trigger the process again. And again.

This doesn't sound right though. You need to persist `.cache´ and `public` locally so that every `gatsby develop` run doesn't re-generate the images. Also, editing a single file shouldn't re-generate all images.

**Comment by DavidSabine** [comment]
> The options is already configurable more or less. You'll need to set `mdxOtherwiseConfigured` to true and copy/paste the config of `gatsby-plugin-mdx` into your own config. This is a workaround until we find a reasonable API to expose such plugin options. Because surfacing every option as public API isn't an option really.

I'll try that. Thank you for the tip.

And about your other comment:

> You need to persist `.cache´ and `public`locally so that every`gatsby develop` run doesn't re-generate the images. Also, editing a single file shouldn't re-generate all images.

I posted this at Spectrum a few weeks ago: https://spectrum.chat/gatsby-js/general/generating-image-thumbnails-endless-loop~35f1a7d1-e4c6-4ea9-abb1-d6fe2a6840c9

The problem seems to have improved with recent updates to gatsby's packages. I'll continue to watch this problem and will raise an issue in future if I can reproduce it reliably.
