### ISSUE TITLE
Can't perform a React state update on an unmounted component. When adding useeffect on navigation component

### ISSUE THREAD

**Issue by faizhameed** [gatsbyjs/gatsby#22288]
## Summary
I am getting the following error
```
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
when using `useEffect` hook scroll event listener in the navigation component

## Relevant information
navigation.jsx
```
export default props => {
  const [fixed, setFixed] = useState(null)
  useEffect(() => {
    window.addEventListener('scroll', handleScroll)
    return () => {
      window.addEventListener('scroll', handleScroll)
      setFixed(null)
    }
  }, [window.removeEventListener('scroll', handleScroll)])

  function handleScroll() {
    var navbar = document.getElementById('nav-cont')
    var sticky = navbar.offsetTop
    if (window.pageYOffset >= sticky + 90) {
      setFixed('top')
    } else {
      setFixed(null)
    }
  }
```
and then on return
```
Navbar
        collapseOnSelect
        expand="lg"
        fixed={fixed} // where i am using it
        bg="primary"
        variant="dark"
        id="nav-cont"
      >
...
```

So how to produce this error
when i am on my home page i can scroll no error occurs 
then I navigate to blog page. but navigation is not unmounted only the children from home to blog happens, then when i scroll i get this error in the console. but my usecase runs fine

**Comment by herecydev** [comment]
Is the navigation component part of a page or is it at a higher level, i.e. through [wrapPageElement](https://www.gatsbyjs.org/docs/browser-apis/#wrapPageElement)?

**Comment by faizhameed** [comment]
@herecydev its part of the layout component which is used to wrap around each page

**Comment by LekoArts** [comment]
Thank you for opening this!

This doesn't seem related to Gatsby and thus I'd recommend asking in communities like Reactiflux, general React reddits or StackOverflow to get an answer.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by dandv** [comment]
I'm getting the same error, without useEffect (only useState), and only in Gatsby development mode; not from the statically built and deployed pages.

**Comment by r9software** [comment]
@LekoArts this seems to be related to gatsby, I'm having the same issue in a code that works just fine outside of gatsby, just to reference this is a workaround for this issue
https://github.com/gatsbyjs/gatsby/issues/23850

useEffect(() => {
      if(typeof window !== 'undefined' &&((window.performance.navigation.type === 1) ||
      window.performance
          .getEntriesByType('navigation')
          .map((nav) => nav.type)
          .includes('reload'))) {
        navigate(-1)
      }
    }, [])
