### ISSUE TITLE
Unable to load custom fonts using Typefaces

### ISSUE THREAD

**Issue by mujeex** [gatsbyjs/gatsby#22293]
## Summary
Good day everyone. I am currently trying to use Typefaces to import fonts into my gatsby project, but for some reason I am not aware of, the fonts do not get loaded to the browser in the network request tab in the chrome dev tools.
## Relevant information
I however, have implemented the usage of typefaces successfully in my previous gatsby project which was 2~3months ago. I tried going back to replicate the exact same steps I used to achieve those results then but to no avail. Here is a repo to reproduce the problem I am encountering https://github.com/mujeex/gatsby-bug-repo             

### Environment (if relevant)

  ```
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.10.0 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 80.0.3987.132
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39
    gatsby-plugin-offline: ^3.0.32 => 3.0.32
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13
  npmGlobalPackages:
    gatsby-cli: 2.10.10
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`:
```
{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "dotenv": "^8.2.0",
    "gatsby": "^2.19.7",
    "gatsby-image": "^2.2.39",
    "gatsby-plugin-manifest": "^2.2.39",
    "gatsby-plugin-offline": "^3.0.32",
    "gatsby-plugin-react-helmet": "^3.1.21",
    "gatsby-plugin-sharp": "^2.4.3",
    "gatsby-source-filesystem": "^2.1.46",
    "gatsby-transformer-sharp": "^2.3.13",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^5.2.1",
    "typeface-ibm-plex-sans": "0.0.75"
  },
  "devDependencies": {
    "prettier": "^1.19.1"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
```

`gatsby-node.js`: N/A 
`gatsby-browser.js`: 
```
/**
 * Implement Gatsby's Browser APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/browser-apis/
 */

// You can delete this file if you're not using it
require('typeface-ibm-plex-sans');
```
`gatsby-ssr.js`: N/A

**Comment by herecydev** [comment]
There's 2 issues I think, both easy to solve 👍 

1. [You've used font-family: 'typeface-ibm-plex-sans'](https://github.com/mujeex/gatsby-bug-repo/blob/master/src/components/layout.css#L3), which isn't a font family. The font family is `IBM Plex Sans`
2. There will be some specificity issues as font-family is declared in a number of places, such as in [Line 204](https://github.com/mujeex/gatsby-bug-repo/blob/master/src/components/layout.css#L204).

But the font family is definitely being loaded. Let me know if you need any further help

**Comment by mujeex** [comment]
> There's 2 issues I think, both easy to solve 👍
> 
> 1. [You've used font-family: 'typeface-ibm-plex-sans'](https://github.com/mujeex/gatsby-bug-repo/blob/master/src/components/layout.css#L3), which isn't a font family. The font family is `IBM Plex Sans`
> 2. There will be some specificity issues as font-family is declared in a number of places, such as in [Line 204](https://github.com/mujeex/gatsby-bug-repo/blob/master/src/components/layout.css#L204).
> 
> But the font family is definitely being loaded. Let me know if you need any further help

Thank you very much sir! You saved my day! Turns out I assigned the wrong naming to the font family and I only needed to declare that property in the body block. Thank again!
