### ISSUE TITLE
Add some kind of error message when you are creating redirects, but don't have a plugin to act on them

### ISSUE THREAD

**Issue by orta** [gatsbyjs/gatsby#22299]
## Description

I guess I expected by default gatsby would make client-side redirects, and then plugin APIs would allow more complex setups - however, a few months down the line I discovered that the redirect API is _basically_ a NOOP unless you have a plugin like `gatsby-plugin-client-side-redirect` installed to actually do something.

Took a few bug reports to get there, so it might be worth having a check somewhere at build time that you have any plugins which can act on your redirects?

### Steps to reproduce

Create a blank gatsby project, use `createRedirect` via `createPages` - see nothing happening

### Expected result

A warning, or if you want to be really strict, an exception because it's a somewhat broken state

### Actual result

No redirects, even though I was using the API right

### Environment

N/A - on `gatsby@^2.19.18`

**Comment by orta** [comment]
Hrmmmm, this might be me holding it wrong 🍡

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Seems reasonable to add some kind of warning (e.g. single line note) to the build output. In theory the API page already mentions that: https://www.gatsbyjs.org/docs/actions/#createRedirect

However, I understand that those pages are not too discover able. A dedicated documentation page would also be reasonable to solve this issue in my opinion.
