### ISSUE TITLE
What built-in function saves previous scroll data (and can I manipulate it)?

### ISSUE THREAD

**Issue by ZeeEssDoubleU** [gatsbyjs/gatsby#22304]
## What built-in function saves previous scroll data (and can I manipulate it)?

**I'm familiar with the shouldUpdateScroll function and know how to use it.**  My question is, is there a function already built into to Gatsby, where I can manipulate how the scroll information is saved?  

I ask because I'm using an animation library (framer-motion) to manipulate page transitions, which requires me to make a scrollable element at the root of my project (actually it's in wrapPageElement, but you get the idea).  The problem with putting the element at the root, is that Gatsby saves my previous scroll positions as [0,0] (verified in session storage).  I'm guessing it does this because it's basing scroll position off of the window, instead of factoring in the scrollable element.

So, to restate my initial question, I would like to know where (what function?) scroll information is saved and if it's possible to manipulate the built-in function, instead of making my own and saving scroll data twice.  If not, is it possible to add this feature?  Thanks.

**Comment by LekoArts** [comment]
Thank you for opening this!
I'm not sure if I understand your question 🤔 

> My question is, is there a function already built into to Gatsby, where I can manipulate how the scroll information is saved?

We use https://github.com/taion/scroll-behavior to save the information and then read it: https://github.com/gatsbyjs/gatsby/blob/a2e8e718eb1e6146dca1c3a560cd281ba65d49b8/packages/gatsby/cache-dir/navigation.js#L121-L127

> The problem with putting the element at the root, is that Gatsby saves my previous scroll positions as [0,0] (verified in session storage). I'm guessing it does this because it's basing scroll position off of the window, instead of factoring in the scrollable element.

There is also this project: https://github.com/ryanwiemer/gatsby-using-page-transitions
Or this codesandbox: https://codesandbox.io/s/h4t2t

So maybe try using a different method for page transitions? I used `react-spring` in the past to do page transitions and in a nutshell I made the overall layout "position: relative" and then placed the individual pages on "position: absolute" and I had no problems with scroll behavior.

> So, to restate my initial question, I would like to know where (what function?) scroll information is saved and if it's possible to manipulate the built-in function, instead of making my own and saving scroll data twice

We only expose the aforementioned `shouldUpdateScroll` function.
