### ISSUE TITLE
new starter installs fail as soon as something else is installed

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#22302]
## Description

after creating a new Gatsby site using `gatsby new`, things appear to work until another package is installed with `npm install`, at which point weird errors start to show up

[Video of the errors + steps to fix here](https://www.dropbox.com/s/9lyqs2eslykt0or/gatsby-starter-error.mp4?dl=0)

### Steps to reproduce

```bash
npx gatsby new starter-bug-repro
cd starter-bug-repro
npm i gatsby-source-graphql
npm run develop
```
this results in the error:
```
> gatsby-starter-default@0.1.0 develop /Users/jlengstorf/dev/starter-bug-repro
> gatsby develop

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'react'
```

if you run `npm install`, then `npm run develop` again, you get a different error:
```
> gatsby-starter-default@0.1.0 develop /Users/jlengstorf/dev/starter-bug-repro
> gatsby develop

The above error occurred in the <StoreStateProvider> component:
    in StoreStateProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
```

to fix it, run `npm update`

### Expected result

the starter should work

### Actual result

the starter throws errors immediately

### Environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.43 => 2.19.43 
    gatsby-image: ^2.2.43 => 2.2.43 
    gatsby-plugin-manifest: ^2.2.47 => 2.2.47 
    gatsby-plugin-offline: ^3.0.40 => 3.0.40 
    gatsby-plugin-react-helmet: ^3.1.23 => 3.1.23 
    gatsby-plugin-sharp: ^2.4.12 => 2.4.12 
    gatsby-source-filesystem: ^2.1.55 => 2.1.55 
    gatsby-source-graphql: ^2.1.34 => 2.1.34 
    gatsby-transformer-sharp: ^2.3.18 => 2.3.18 
```

**Comment by jlengstorf** [comment]
this also happens when using `gatsby-starter-hello-world`, FYI

**Comment by jlengstorf** [comment]
bumping this, because it seems like a pretty big deal that Gatsby breaks as soon as you install a dependency @gatsbyjs/core

**Comment by LekoArts** [comment]
Hi Jason,

this is an issue with npm and not necessarily with Gatsby. As per https://github.com/gatsbyjs/gatsby/issues/10607#issuecomment-450290701 the starters ship with both lock files. As per https://github.com/gatsbyjs/gatsby/issues/13210 the lock file that is not from your default package manager gets deleted.
You have `yarn` as your default package manager set.

If you now try to use npm it falsely deletes everything except your new package 🤦‍♂

So sadly this must be fixed by npm and you know, that could take a while...
