### ISSUE TITLE
two div's with id "gatsby-announcer" when root element gets wrapped with an Fragment

### ISSUE THREAD

**Issue by herrwitzi** [gatsbyjs/gatsby#22306]
## Description

when wrapping the root Element with the Gatsby-Browser-API wrapRootElement() with an React.Fragment it creates two div's with the id "gatsby-announcer"

### Steps to reproduce

use gatsby version 2.19.43
https://github.com/herrwitzi/gatsby-bug

### Expected result

wrapping the root Element with an React.Fragment should have the same behavior as wrapping it with an Component or an html-Element 

### Actual result

First Element after the React.Fragment get's the id "gatsby-announcer"

### Environment

  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.16.0 - C:\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: 2.19.43 => 2.19.43 
    gatsby-image: ^2.2.39 => 2.2.43 
    gatsby-plugin-manifest: ^2.2.39 => 2.2.47 
    gatsby-plugin-offline: ^3.0.32 => 3.0.40 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.23 
    gatsby-plugin-sharp: ^2.4.3 => 2.4.12 
    gatsby-source-filesystem: ^2.1.46 => 2.1.55 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.18

**Comment by pieh** [comment]
Hey @herrwitzi! You have `wrapRootElement` with additional DOM markup in [`gatsby-browser`](https://github.com/herrwitzi/gatsby-bug/blob/master/gatsby-browser.js), but not in [`gatsby-ssr`](https://github.com/herrwitzi/gatsby-bug/blob/master/gatsby-ssr.js). This cause DOM markup mismatch and problems for react to reconcile the difference.

As noted in https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement (might need more emphasis on this):
> Note: There is an equivalent hook in Gatsby’s SSR API. It is recommended to use both APIs together. For example usage, check out Using redux.

Other option would be to use [`gatsby-plugin-layout`](https://www.gatsbyjs.org/packages/gatsby-plugin-layout/) which automatically creates ssr and browser wrappers

**Comment by pieh** [comment]
As for reason that started happening recently - we fixed SSR bug, which apparently was masking this behaviour
