### ISSUE TITLE
default starter throws sharp errors

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#22303]
## Description

when creating a new site with the default starter, an error is immediately thrown before any code changes are made

<img width="878" alt="Screen Shot 2020-03-15 at 4 50 00 PM" src="https://user-images.githubusercontent.com/163561/76713322-0ec7c480-66dd-11ea-8ac5-99c076d4335c.png">

### Steps to reproduce

1. create a new site with the default starter (`gatsby new mysite`)
2. start it (`npm run develop`)

### Expected result

starter site should start with no errors

### Actual result

errors

### Environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.43 => 2.19.43 
    gatsby-image: ^2.2.43 => 2.2.43 
    gatsby-plugin-manifest: ^2.2.47 => 2.2.47 
    gatsby-plugin-offline: ^3.0.40 => 3.0.40 
    gatsby-plugin-react-helmet: ^3.1.23 => 3.1.23 
    gatsby-plugin-sharp: ^2.4.12 => 2.4.12 
    gatsby-source-filesystem: ^2.1.55 => 2.1.55 
    gatsby-source-graphql: ^2.1.34 => 2.1.34 
    gatsby-transformer-sharp: ^2.3.18 => 2.3.18 
```

**Comment by femesq** [comment]
Found this issue when search for problems with `gatsby-source-filesystem@2.1.55`...
Was using `2.1.54` on a project and it was working fine... after upgrading to `2.1.55` started throwing error trying to find some images on `cache` dir...

**Comment by LekoArts** [comment]
Hi Jason,

I followed your steps but couldn't reproduce it. I installed the starter via our CLI, updated all packages to latest version and run a `yarn develop`. No error was thrown.

I could imagine this being an issue with sharp alone, have you recently updated e.g. your node version so that the sharp version is out of sync?

For reference, my setup:

```
  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  npmPackages:
    gatsby: ^2.19.43 => 2.19.43
    gatsby-image: ^2.2.43 => 2.2.43
    gatsby-plugin-manifest: ^2.2.47 => 2.2.47
    gatsby-plugin-offline: ^3.0.40 => 3.0.40
    gatsby-plugin-react-helmet: ^3.1.23 => 3.1.23
    gatsby-plugin-sharp: ^2.4.12 => 2.4.12
    gatsby-source-filesystem: ^2.1.55 => 2.1.55
    gatsby-transformer-sharp: ^2.3.18 => 2.3.18
  npmGlobalPackages:
    gatsby-cli: 2.9.0
    gatsby-dev-cli: 2.5.43
```

**Comment by jlengstorf** [comment]
@LekoArts have you tried using npm and not updating packages before running `develop`?

I was able to fix by updating packages, but that's not an obvious debugging step unless someone is already familiar with npm, etc., so it's not very friendly to new devs

**Comment by LekoArts** [comment]
I tried running it before upgrading and it worked :) I only upgraded because your versions were the latest ones.

Our renovate bot got stalled a bit so when you cloned the repo the dependencies were a bit outdated. The lock files are now up-to-date and hence all dependencies. I cloned the starter, ran npm install and develop and everything works 🤷‍♂

**Comment by jlengstorf** [comment]
just ran it again — still broken

here's what I'm doing:
```
npx gatsby new tt
cd tt
npm run develop
```

error:
```
success write out redirect data - 0.002s

 ERROR #11321  PLUGIN

"gatsby-plugin-manifest" threw an error while running the onPostBootstrap lifecycle:

Input file contains unsupported image format



  Error: Input file contains unsupported image format
```

<img width="922" alt="Screen Shot 2020-03-17 at 10 16 43 AM" src="https://user-images.githubusercontent.com/163561/76882821-6fb7df80-6838-11ea-8342-82f9648dbd73.png">

it doesn't fail the dev server (I didn't check to see what the UI looks like), but it's not a great experience for first-time users to create a new site and see a big red error

**Comment by l19861225q** [comment]
The same problem to me, I can't dev & build, please help ~

**Comment by jlengstorf** [comment]
@l19861225q you can remove the configuration for `gatsby-plugin-manifest` if you want to get unblocked immediately — it's not a fix, but it'll work around the problem for now

**Comment by kelvindecosta** [comment]
Hi @jlengstorf & @LekoArts ,

I failed to reproduce the bug but I noticed something interesting in the output generated by `gatsby info`.

When run from within @jlengstorf 's reproduction, it shows that the `gatsby-source-graphql` package is present:

```diff
    gatsby-source-filesystem: ^2.1.55 => 2.1.55 
+   gatsby-source-graphql: ^2.1.34 => 2.1.34 
    gatsby-transformer-sharp: ^2.3.18 => 2.3.18 
```

This package is not present / used in the [default starter](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/gatsby-config.js)

As far as I know, `gatsby info` only shows packages within the current project. Please correct me if I am mistaken.

Maybe this bug is not associated with another starter?

**Comment by jlengstorf** [comment]
@kelvindecosta there's another bug (#22302) that I was creating a repro for as well, so that's unrelated to this bug

**Comment by pieh** [comment]
This seems related with https://github.com/gatsbyjs/gatsby/issues/21032 / https://github.com/libvips/libvips/issues/1539

Where globally installed `libvips` mess with `sharp` - can you try running `vips --version` (to verify if you have it globally installed and if you do what version you have)?

**Comment by jlengstorf** [comment]
@pieh yeah, looks like I have it installed globally

```
$ vips --version
vips-8.9.1-Tue Jan 28 13:05:46 UTC 2020
```

what's the fix, do you think? uninstall?

**Comment by pieh** [comment]
I would call it workaround, but uninstalling (if you don't need it for anything else) will probably be best solution

**Comment by jlengstorf** [comment]
for future googlers: I just ran `brew uninstall vips` and it _appears_ to have removed this issue

if you need `vips` installed locally for whatever reason, this will still be broken, so... I don't think this bug is solved, but if `vips` is optional for you, you can work around it at least?
