### ISSUE TITLE
chore(www): prism language is not visible

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#22334]
## Description

code block prims language is not visible above the codeblock.

I remember that i see it at least for this languages:
- `md`
- `po`

### Steps to reproduce

open:
- `po` -> https://www.gatsbyjs.org/contributing/translation/ui-messages/#opening-and-closing-tags

![Bildschirmfoto 2020-03-16 um 15 40 31](https://user-images.githubusercontent.com/184316/76769452-ce2f8000-679c-11ea-90ad-6560e314bdac.png)

- `md` -> https://www.gatsbyjs.org/contributing/translation/style-guide/#use-soft-line-wraps

![Bildschirmfoto 2020-03-16 um 15 42 32](https://user-images.githubusercontent.com/184316/76769477-d7b8e800-679c-11ea-8d11-157a0c803b12.png)

### Expected result

show the language above the code block

### Actual result

no language is visible

**Comment by tesseralis** [comment]
I can't seem to reproduce this. I think what's happening is that the code blocks are lazy-loaded, so if you have javascript disabled and start at a subheader, the code doesn't load immediately. Since this isn't an issue, I'll close it for now.

**Comment by muescha** [comment]
ok - they are visible now. 

but i have to hit on every doc page the `force reload`, because i have always an old cache. caching is fine, but if i can not trust anymore the content i see thats not fine :(
