### ISSUE TITLE
Error when writing test using @testing-library/react and Gatsby Link

### ISSUE THREAD

**Issue by tommaton** [gatsbyjs/gatsby#22348]
## Description

Hi,
I'm trying to write some unit tests using `@testing-library/react` which is working absolutely fine on other components but as soon as I introduce Gatsby Link (`import { Link } from 'gatsby'`) as a child component then my tests fail and complain about Gatsby Link.

It's never happened on previous projects, on difference is the way it's imported now.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

Unfortunately I cant provide a reproduction (security) but this is my simple test

navigation.test.tsx
```
import { render } from '@testing-library/react';

describe('components-navigation component', () => {
  let props;

  beforeAll(() => {
    props = {
      navTree: NavTree,
    };
  });

  it('should display the MegaMenu on hover', () => {
    const { getByText } = render(<DesktopNav {...props} />);
     getByText('Dashboard');
  });
});
```

### Expected result

What should happen?

### Actual result

```
TypeError: ___loader.enqueue is not a function

      24 |
      25 |   it('should display the MegaMenu on hover', () => {
    > 26 |     const { getByText } = render(<DesktopNav {...props} />);
         |             ^
      27 |     getByText('Dashboard');
      28 |   });

console.error node_modules/react-dom/cjs/react-dom.development.js:21843
      The above error occurred in the <GatsbyLink> component:
          in GatsbyLink (created by ForwardRef)
          in ForwardRef (created by SiteLink)
          in SiteLink (created by TopLevelNav)
          in li (created by TopLevelNav)
          in TopLevelNav (created by DesktopNav)
          in ul (created by styled.ul)
          in styled.ul (created by DesktopNav)
          in div (created by styled.div)
          in styled.div (created by DesktopNav)
          in DesktopNav
          in ThemeProvider
          in IntlProvider
          in Provider

      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
    console.error node_modules/react-dom/cjs/react-dom.development.js:21843
      The above error occurred in the <GatsbyLink> component:
          in GatsbyLink (created by ForwardRef)
          in ForwardRef (created by SiteLink)
          in SiteLink (created by TopLevelNav)
          in li (created by TopLevelNav)
          in TopLevelNav (created by DesktopNav)
          in ul (created by styled.ul)
          in styled.ul (created by DesktopNav)
          in div (created by styled.div)
          in styled.div (created by DesktopNav)
          in DesktopNav
          in ThemeProvider
          in IntlProvider
          in Provider

      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

```

### Environment
```
 System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.4 - ~/.yvm/shim/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 69.0.1
    Safari: 13.0.5
```

**Comment by herecydev** [comment]
A reproduction would have been ideal, but I'll assume you're not mocking any of Gatsby (it looks that way from the stacktrace).

The Gatsby Link component expects ___loader to be defined and testing in isolation with react testing library will cause issues. You could either define these in your environment or mock the Gatsby Link to render an anchor element instead. Depends on your view of testing...

**Comment by tommaton** [comment]
@herecydev 

I do have `___loader` in my jest config as this is how I set it up for `gatsby-link` previously.

```
globals: {
    __PATH_PREFIX__: '',
    ___loader: '',
  },
```

Silly question but how would I mock the Gatsby Link?

**Comment by herecydev** [comment]
See [Unit testing](https://www.gatsbyjs.org/docs/unit-testing/#mocking-gatsby)

For the above ___loader is not a string it's an object. It'll also need to have an enqueue function as referenced by `TypeError: ___loader.enqueue is not a function`

**Comment by tommaton** [comment]
So the `___loader` wasn't actually the problem, I needed to add a Mock in for the Gatsby Link https://www.gatsbyjs.org/docs/unit-testing/#3-useful-mocks-to-complete-your-testing-environment

Once I done this, the tests all passed with no errors from Gatsby Link
