### ISSUE TITLE
Documentation page about A/B testing with Google Analytics and Netlify not available

### ISSUE THREAD

**Issue by metalcamp** [gatsbyjs/gatsby#22354]
## Description

Documentation page about A/B testing with Google Analytics and Netlify isn't available.
URL: https://www.gatsbyjs.org/docs/ab-testing-with-google-analytics-and-netlify/

**Comment by connorlindsey** [comment]
I'm having trouble reproducing the bug. Are you still having this issue? 

Could you provide more information like the browser you're using?

**Comment by metalcamp** [comment]
I just figured out that this particular page was blocked due to PiHole. Sorry for false bug report.
