### ISSUE TITLE
How to debug a source plugin on Gatsby side?

### ISSUE THREAD

**Issue by winstonma** [gatsbyjs/gatsby#22357]
## Summary
I am using the plugin [gatsby-source-datocms](https://github.com/datocms/gatsby-source-datocms) and I faced that **createNodeField** doesn't create anything. I believe it is not related to the Gatsby side but I would like to know how can I trace down the root cause of my additional fields can't be queried.

I would like to place some logs on the Gatsby side to see the node content, after it is processed by the plugin.

Reference: https://github.com/datocms/gatsby-source-datocms/issues/92

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by connorlindsey** [comment]
You can use the `reporter` to log info to your terminal from gatsby-node. That may help.

[Reporter API](https://www.gatsbyjs.org/docs/node-api-helpers/#reporter)

**Comment by Js-Brecht** [comment]
@winstonma I wonder what the root type is that you're adding fields to.  I see that plugin adds several different types, and there are some that are set to _not_ infer types, which means that for those types, your fields won't be picked up automatically.

**Comment by winstonma** [comment]
@connorlindsey Thanks for the info.

I saw the log from the `onCreateNode` that the new item is added onto my node. However I couldn't saw the item in GraphQL. The API would be perfect but where should I place the `reporter` to see the node content after the function `onCreateNode` is being executed? Thank you very much.

**Comment by winstonma** [comment]
@Js-Brecht I am adding fileNode, using `createRemoteFileNode`. I also tried string but I have no luck getting my desired result.

**Comment by Js-Brecht** [comment]
> I am adding fileNode, using `createRemoteFileNode`. I also tried string but I have no luck getting my desired result in GraphQL.

Do you mean you're trying to link a `File` node to your DatoCMS node via `createFileNode()`?

> where should I place the `reporter` to see the node content after the function `onCreateNode` is being executed?

One thing you could do here is subscribe to the store events, and look for the `ADD_FIELD_TO_NODE` event.  Something kind of like this:
```js
// gatsby-node.js
let unsubscribe;
export const onPreBootstrap = async ({ store }) => {
    console.log('onPreBootstrap()')
    unsubscribe = store.subscribe(() => {
        const lastAction = store.getState().lastAction;

        if (lastAction.type === 'ADD_FIELD_TO_NODE') {
            console.log(lastAction.payload);
        }
    })
}

export const onPostBootstrap = async () => {
    unsubscribe();
}
```

That will show you what the payload looked like that went into the redux store (after `createNodeField()` is executed).  Or you could look for `CREATE_NODE` to see what is added when `createNode()` is called.

Another thing you could do is use `getNodes()` in the `onPostBootstrap()` endpoint, and examine the contents of the store.  That's what will wind up being used for GraphQL.

Looking at what the underlying data looks like to GraphQL, as opposed to what's shown to you by GraphiQL, after it's been loaded is a different story.

**Comment by winstonma** [comment]
@Js-Brecht  Thanks

I just have a look at the source code of the plugin and find no `onCreateNode` in src/gatsby-node.js. Would that be a sign?

**Comment by Js-Brecht** [comment]
> I printed out the content and it shows that the added content doesn't exist. I guess my added content doesn't exist in the log as I desired.

It seems odd to me that they would wipe out any transformations that are being done by consumers, but I guess it's not outside the realm of possibility.

> I also find that the logs inside of `onPreBootstrap→CREATE_NODE` comes before `onCreateNode`, does it mean that my additional code in `onCreateNode` will never be reflected inside the GraphQL?

The store subscription event will be fired after `createNode()` is called, so it is not dependent on `sourceNodes` or `onCreateNode`.

Try doing `getNodes()` in `onPostBootstrap` to see the entire collection of nodes that have been generated by the build.  Like this:
```js
export const onPostBootstrap = ({ getNodes }) => {
   console.log(getNodes())
}
```

> I just have a look at the source code of the plugin and find no `onCreateNode` in src/gatsby-node.js. Would that be a sign?

I don't know if I'd worry too much about that.

If I suspected that a plugin was reversing a transformation I did to a node, then one of the things I would probably do is trace through it with the debugger.  There's information here on how to [configure your debugger](https://www.gatsbyjs.org/docs/debugging-the-build-process/#vs-code-debugger-manual-config) (if you're using vscode, that is).

You can clone that plugin, add it to [the local plugins folder](https://www.gatsbyjs.org/docs/loading-plugins-from-your-local-plugins-folder/), then build it with source maps enabled (don't forget to remove it from your `package.json`, so it's not in `node_modules` anymore).  Set a breakpoint in the entry point, so you can trace through and see what happens when you try to do whatever it is you're doing.  Look for any event listeners that look like they could be mutating things.

---

Can you share the code that is having trouble?  There's a lot going on in that plugin, so it might be easier to have somewhere to start.

**Comment by ascorbic** [comment]
I'm not sure about this specific issue, but if you haven't updated the Dato plugins in the last few days then you really should, as there have been some significant updates that @sidharthachatterjee in the Gatsby team has been contributing. He will be opening more PRs later this week, but our whole company has been on leave for the past two days.

**Comment by winstonma** [comment]
@ascorbic I am using the latest verison

**Comment by winstonma** [comment]
@Js-Brecht Thanks again

After digging in the plugin code, it seems to me that the `CreateNode` is being called too late. Therefore I modified the source code and added an item. Also by using `getNodes` I could confirm that my added items are displayed on the node.

**Comment by Js-Brecht** [comment]
@winstonma without anything more to go on, it's difficult to provide any more direction.  My suggestion would be to work with the plugin's team on it.  However, since @ascorbic says @sidharthachatterjee is working on the plugin, I think it's in very good hands.

**Comment by winstonma** [comment]
@Js-Brecht Thanks

I guess I learn a bit debugging method from this

**Comment by matjack1** [comment]
hello, I'm chiming in from DatoCMS!

I've tried to reproduce the issue and following your suggestion I've tried to inspect the nodes with `getNodes` in `onPostBootstrap`.

I can find the added field in the `fields` attribute correctly, but the I cannot see it in the GraphiQL. Are we doing something strange on our source plugin?

I'm trying with latest versions of both Gatsby (2.19.49) and our plugin (2.1.29).

**Comment by Js-Brecht** [comment]
@matjack1 is there any `infer: false` or `@dontinfer` on the type that the field is being added to?

**Comment by winstonma** [comment]
Thanks @Js-Brecht 

After I changed the last `infer: false` to `infer: true` in https://github.com/datocms/gatsby-source-datocms/blob/master/src/hooks/sourceNodes/createTypes/item/index.js

I can see my added field in GraphQL.

**Comment by Js-Brecht** [comment]
I had a feeling it was that one, but it was hard to be sure without knowing what data was going into it, so I could extrapolate the result

**Comment by matjack1** [comment]
@Js-Brecht should we remove that? We stop inferring because we had some compatibility issues and it was going to be deprecated in the future?

What's the recommended behaviour there? Thank you!

**Comment by LekoArts** [comment]
I would suggest moving that issue to the plugin repo then as it doesn't seem to be an issue with Gatsby - and the initial question was answered. Thanks!
