### ISSUE TITLE
Yarn run bootstrap error

### ISSUE THREAD

**Issue by m-henderson** [gatsbyjs/gatsby#2236]
I am getting an error when running `yarn run bootstrap`. have a look at the screen shot: 
![image](https://user-images.githubusercontent.com/16070192/30871436-841cfefa-a2ac-11e7-8f22-86ec919ab4ab.png)

the directory on my dev machine is a fresh clone.

**Comment by KyleAMathews** [comment]
I'm not sure from the screenshot what could be wrong. The babel warning drowns out any error message.

Is there anything that shows up below what you screenshot? 

Also… installs just fail sometime. Does running it again work?

**Comment by m-henderson** [comment]
Running again doesn't work. I will post more info when I get to my laptop.

**Comment by sebastienfi** [comment]
@m-henderson I see you are on Windows, have you looked at [gatsby-on-windows](https://www.gatsbyjs.org/docs/gatsby-on-windows/) ?

**Comment by KyleAMathews** [comment]
Closing this issue as it's fairly old and we have far too many open issues! If you have additional problems in this area, please open a new issue!
