### ISSUE TITLE
Error 95313 on gatsby build no hints

### ISSUE THREAD

**Issue by lmnnarciso** [gatsbyjs/gatsby#22360]
## Description
[https://imgur.com/LmM6kVs](url)
I'm encountering error #95313 but no hints on why or where its happening. Okay when running 

> gatsby develop

and errors on 

> gatsby build

### Steps to reproduce

I just build it

### Actual result
Build error #95313

### Environment

$ gatsby info --clipboard

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.4 - /c/Users/Miguel/AppData/Local/Programs/Python/Python37-32/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-alias-imports: ^1.0.4 => 1.0.4
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39
    gatsby-plugin-offline: ^3.0.32 => 3.0.32
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-sass: ^2.1.30 => 2.1.30
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13

**Comment by connorlindsey** [comment]
Could you provide more information? Please provide a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) or share your code.

**Comment by connorlindsey** [comment]
I'm going to close this issue as we never received information to reproduce the issue.

**Comment by armandoborge** [comment]
@lmnnarciso did you manage to solve this one?

**Comment by lmnnarciso** [comment]
@armandoborge If you encountered this issue its only due to instance when trying to access windows variable during build time but its not available since its gonna be run on the server.

I suggest enclosing variables such as the windows or documents and check if the environment is node or browser.

**Comment by armandoborge** [comment]
Done that already, same problem!
Thanks
