### ISSUE TITLE
gatsby build leads to an error

### ISSUE THREAD

**Issue by esentai8** [gatsbyjs/gatsby#22367]
## Description

When I run command `gatsby develop` everything works fine and I can see the website working properly, however when I run `gatsby build` command below error is logged to the terminal. While error seem to be related to contentful-plugin, the same error is not present when `gatsby develop` command is ran

` ERROR 

Problems with gatsby-source-contentful plugin options:
spaceId: undefined - "spaceId" is required
accessToken: undefined - "accessToken" is required
host (default value): "cdn.contentful.com"
environment (default value): "master"
downloadLocal (default value): false
localeFilter (default value): [Function]
forceFullSync (default value): false
pageLimit (default value): 100
useNameForId (default value): true`

### Steps to reproduce

Run `gatsby build`

Here is the link to my repository [https://github.com/esentai8/personalBlog](url)

### Expected result

What should happen?
static assets should be generated with successful build process completed and website must be accessible

### Actual result
an error in the terminal
` ERROR 

Problems with gatsby-source-contentful plugin options:
spaceId: undefined - "spaceId" is required
accessToken: undefined - "accessToken" is required
host (default value): "cdn.contentful.com"
environment (default value): "master"
downloadLocal (default value): false
localeFilter (default value): [Function]
forceFullSync (default value): false
pageLimit (default value): 100
useNameForId (default value): true`
What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.3 - /c/python/python
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-plugin-sass: ^2.1.31 => 2.1.31
    gatsby-source-contentful: ^2.1.97 => 2.1.97
    gatsby-source-filesystem: ^2.1.56 => 2.1.56

**Comment by connorlindsey** [comment]
It looks like accessToken and spaceId are not defined in production. Using [Environmental Variables in Gatsby](https://www.gatsbyjs.org/docs/environment-variables/) requires that you prefix the variable with GATSBY_ which may be causing the problem.

You may also need to define the environmental variables in Netlify in wherever you're building your website.

**Comment by esentai8** [comment]
> It looks like accessToken and spaceId are not defined in production. Using [Environmental Variables in Gatsby](https://www.gatsbyjs.org/docs/environment-variables/) requires that you prefix the variable with GATSBY_ which may be causing the problem.
> 
> You may also need to define the environmental variables in Netlify in wherever you're building your website.

I thought I define accessToken and spaceId in the .env file and used environment variables in the options setup of gatsby-source-contentful plugin. Previously it worked perfectly. I don't know what has changed now.

On a separate note, what do you mean 'are not defined in production'? in what file I would separately define them?

**Comment by ascorbic** [comment]
Hello. Prefixing with `GATSBY_` is only required if you need the variables in the browser, not for build. 

You need to ensure that you have a `.env.production` file if you're running gatsby build locally. If you look at your `gatsby-config.js` file, you can see that dotenv is trying to load a different file depending on the NODE_ENV variable, so you need both files. If you don't need different settings for dev and prod then feel free to edit that part of the file and just use one .env file. As @connorlindsey poinst out, you'll also need to set these variables in your CI environment if you're using one. This will have been done automatically if you're using Gatsby Cloud, but if you're using something like Netlify you'll need to do it manually. I'm going to close this, but if this doesn;t fix it feel free to reopen.
