### ISSUE TITLE
Gatsby build form run on own server issue with nodemailer error on webpack

### ISSUE THREAD

**Issue by SajithRAP** [gatsbyjs/gatsby#22379]
I tried to implement the **Run your own server** concept given in the gatsby document link [https://www.gatsbyjs.org/docs/building-a-contact-form]. But it throws lots of webpack error in nodemailer. 

I have refershed the node modules and also reinstalled the nodemailer package. But still didnt work.

I have tried both the import and also declaring as const. But both did't work.

Below is my code and the error 

// import bodyParser from 'body-parser';
// import express from 'express';
// import nodemailer from 'nodemailer'; 
---------
    const bodyParser = require("body-parser")
    const express = require("express")
    const nodemailer = require("nodemailer")
    
    const app = express()
    app.use(bodyParser.urlencoded())
    
    const contactAddress = "tomailaddress@gmail.com"
    
    const mailer = nodemailer.createTransport({
      service: "Gmail",
      auth: {
        user: 'myaddress@gmail.com',
        pass: 'somepassword',
      },
    })
    
    app.post("/contact", function(req, res) {
      mailer.sendMail(
        {
          from: req.body.from,
          to: [contactAddress],
          subject: req.body.subject || "[No subject]",
          html: req.body.message || "[No message]",
        },
        function(err, info) {
          if (err) return res.status(500).send(err)
          res.json({ success: true })
        }
      )
    })
    
    app.listen(8000)

--------------------------------------------------------

WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'child_process' in 'C:\\node_modules\nodemailer\lib\sendmail-transport'
File: ..\..\node_modules\nodemailer\lib\sendmail-transport\index.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'dns' in 'C:\\node_modules\nodemailer\lib\mailer'        
File: ..\..\node_modules\nodemailer\lib\mailer\index.js
 
ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'dns' in 'C:\\node_modules\nodemailer\lib\shared'        
File: ..\..\node_modules\nodemailer\lib\shared\index.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'fs' in 'C:\\node_modules\destroy'
File: ..\..\node_modules\destroy\index.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'fs' in 'C:\\node_modules\etag'
File: ..\..\node_modules\etag\index.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'fs' in 'C:\\node_modules\express\lib'
File: ..\..\node_modules\express\lib\view.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'fs' in 'C:\\node_modules\nodemailer\lib\dkim'
File: ..\..\node_modules\nodemailer\lib\dkim\index.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'fs' in 'C:\\node_modules\nodemailer\lib\mime-node'      
File: ..\..\node_modules\nodemailer\lib\mime-node\index.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'fs' in 'C:\\node_modules\nodemailer\lib\shared'
File: ..\..\node_modules\nodemailer\lib\shared\index.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'fs' in 'C:\\node_modules\send'
File: ..\..\node_modules\send\index.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'fs' in 'C:\\node_modules\send\node_modules\mime'        
File: ..\..\node_modules\send\node_modules\mime\mime.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'net' in 'C:\\node_modules\express\lib'
File: ..\..\node_modules\express\lib\request.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'net' in 'C:\\node_modules\nodemailer\lib\mailer'        
File: ..\..\node_modules\nodemailer\lib\mailer\index.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'net' in 'C:\\node_modules\nodemailer\lib\shared'        
File: ..\..\node_modules\nodemailer\lib\shared\index.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'net' in 'C:\\node_modules\nodemailer\lib\smtp-connection'
File: ..\..\node_modules\nodemailer\lib\smtp-connection\http-proxy-client.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'net' in 'C:\\node_modules\nodemailer\lib\smtp-connection'
File: ..\..\node_modules\nodemailer\lib\smtp-connection\index.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'tls' in 'C:\\node_modules\nodemailer\lib\smtp-connection'
File: ..\..\node_modules\nodemailer\lib\smtp-connection\http-proxy-client.js

 ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Generating development JavaScript bundle failed
Can't resolve 'tls' in 'C:\\node_modules\nodemailer\lib\smtp-connection'
File: ..\..\node_modules\nodemailer\lib\smtp-connection\index.js

failed Re-building development bundle - 7.493s

**Comment by connorlindsey** [comment]
Based on the tutorial you linked, you should be creating a completely separate application from your gatsby website. This node application would require it's own package.json, index.js (which you have above), and node_modules. You'd want to host that on another service like Heroku. Here are some good [ways to host a node app](https://flaviocopes.com/nodejs-hosting/). 

Once you have it hosted, you'll have some new url like my-app-29083afj.now.sh. Your gatsby website should send the form data to your node application's contact endpoint (my-app-29083afj.now.sh/contact). 

I'm guessing you tried to add the server code to your gatsby website, causing some errors as you wouldn't normally run webpack and node together (as far as I understand). Let me know if this helps.

**Comment by jonniebigodes** [comment]
@SajithRAP you can take two routes here:
1- One create a separate repo and put the server code in there and deploy where you'll want it to be deployed. [Here](https://github.com/jonniebigodes/gatsby_wizard_form_dummy_server) is a sample for you, this repo was used to answer another issue, but it will get you some insights.
2- You can use a lambda function with express and with that you can have the code in the same "place". Netlify has some good examples, one even that works pretty well with express. Take a look [here](https://github.com/netlify-labs/netlify-functions-express) and [here](https://functions.netlify.com/examples/) for a list of other examples.

**Comment by LekoArts** [comment]
Thank you for opening this!

As Connor said this is probably the Gatsby setup interfering with the setup you should to separately. Hence this isn't an issue with Gatsby.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by SajithRAP** [comment]
> Based on the tutorial you linked, you should be creating a completely separate application from your gatsby website. This node application would require it's own package.json, index.js (which you have above), and node_modules. You'd want to host that on another service like Heroku. Here are some good [ways to host a node app](https://flaviocopes.com/nodejs-hosting/).
> 
> Once you have it hosted, you'll have some new url like my-app-29083afj.now.sh. Your gatsby website should send the form data to your node application's contact endpoint (my-app-29083afj.now.sh/contact).
> 
> I'm guessing you tried to add the server code to your gatsby website, causing some errors as you wouldn't normally run webpack and node together (as far as I understand). Let me know if this helps.

Thanks I will give a try on that

**Comment by SajithRAP** [comment]
> @SajithRAP you can take two routes here:
> 1- One create a separate repo and put the server code in there and deploy where you'll want it to be deployed. [Here](https://github.com/jonniebigodes/gatsby_wizard_form_dummy_server) is a sample for you, this repo was used to answer another issue, but it will get you some insights.
> 2- You can use a lambda function with express and with that you can have the code in the same "place". Netlify has some good examples, one even that works pretty well with express. Take a look [here](https://github.com/netlify-labs/netlify-functions-express) and [here](https://functions.netlify.com/examples/) for a list of other examples.

Thanks. That helped much. I will try on that.

**Comment by Tyerlo** [comment]
I'm trying to build gatsby application with lambda function and nodemailer, doesn't seem to work. 
I followed this: [here](https://github.com/netlify-labs/netlify-functions-express) and [here](https://github.com/gustavdz/nodemailer-AWS-ses-smtp/blob/master/index.js)
I get a 200 status code but no email.

[build]
command = "yarn build"
functions = "src/functions"
publish = "build"

Do I need to setup something else? I've already unlocked sandbox mode for sending mail with simple mail service Amazon.

In my frontend I have an submit form built with formik.
`onSubmit={(values, actions) => {
        axios
          .post("/.netflify/functions/ses-send-email", {
            values
          })
          .then((result) => {
            let data = JSON.parse(result.config.data);
            console.log(data);
            return data;
          })
          // .then(() => {
          //   navigate("/thanks");
          //   actions.resetForm();
          // })
          .catch((error) => {
            console.log(error);
            navigate("/error");
          });
      }}
`


`
require("dotenv").config();
const bodyParser = require("body-parser");
const express = require("express");
const nodemailer = require("nodemailer");
const cors = require("cors")({ orign: true });

const app = express();
app.use(express.json());

app.use(bodyParser.json());

app.post("/ses-send-emaill", (req, res) => {
  const mailOptions = {
    from: "myadress@gmail.com",
    to: "a@gmail.com",
    subject: "contact form message",
    html: `<h1>Welcome</h1>
       <p> <b>This is a form: </b> </p>`
  };

  const transporter = nodemailer.createTransport({
    port: 465,
    host: process.env.AWS_REGION_MAIL,
    secure: true,
    auth: {
      username: process.env.SMTP_USERNAME,
      password: process.env.SMTP_PASSWORD
    },
    sendingRate: 1,
    debug: true
  });

  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log(error);
      res.status(error.responseCode).send(error.response);
    } else {
      console.log("Message sent: " + info.response);
      res.status(200).send(info);
    }
  });
});
`
