### ISSUE TITLE
Redux applyMiddleware not working

### ISSUE THREAD

**Issue by algebrathefish** [gatsbyjs/gatsby#22384]
## Relevant information

I followed  [this](https://www.freecodecamp.org/news/how-to-get-started-with-gatsby-2-and-redux-ae1c543571ca/)  to add redux to gatsby, but changed the wrapper to

```
import React from 'react';
import { Provider } from 'react-redux';
import { createStore as reduxCreateStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk'

import rootReducer from '.';

const createStore = () => reduxCreateStore(rootReducer, applyMiddleware(thunk));

export default ({ element }) => (
  <Provider store={createStore()}>{element}</Provider>
);

```

I am getting no logs for reducers

Is there some other way to configure this?

### File contents (if changed)

`gatsby-config.js`: 

```
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
});

module.exports = {
  siteMetadata: {
    title: ``,
    description: ``,
    author: ``,
  },

  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-stylus`,
    `gatsby-plugin-postcss`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,

  ],

}
```

 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: 

`export { default as wrapRootElement } from './src/state/ReduxWrapper';`

 
`gatsby-ssr.js`: 

`export { default as wrapRootElement } from './src/state/ReduxWrapper';`

**Comment by jonniebigodes** [comment]
@algebrathefish by logs do you mean with the devtools?

if that's the case take a look at #17661 to see if it helps

**Comment by algebrathefish** [comment]
yes @jonniebigodes I mean with the devtools, I will check your answer in that thread.

Thank you very much

**Comment by algebrathefish** [comment]
@jonniebigodes 

I did this is my wrapper

```
import React from 'react';
import { Provider } from 'react-redux';
import { createStore as reduxCreateStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk'

import rootReducer from '.';

const windowGlobal = typeof window !== 'undefined' && window;

const devtools =
  process.env.NODE_ENV === 'development' && windowGlobal.devToolsExtension
    ? window.__REDUX_DEVTOOLS_EXTENSION__ &&
  window.__REDUX_DEVTOOLS_EXTENSION__()
    : f => f;

const createStore = () => reduxCreateStore(rootReducer, compose(applyMiddleware(thunk), devtools));

export default ({ element }) => (
  <Provider store={createStore()}>{element}</Provider>
);

```

It is not logging anything, keep in mind I am not expert,

**Comment by jonniebigodes** [comment]
@algebrathefish i'm going to create a repo and come back with the detailed answer. Do you mind waiting a bit?

**Comment by algebrathefish** [comment]
@jonniebigodes I don't mind, no. Thank you very much

**Comment by algebrathefish** [comment]
@jonniebigodes I am sorry, it is working fine, I did not add the logger there, that is why it was not working.

I feel very ashamed, I am sorry

**Comment by jonniebigodes** [comment]
@algebrathefish no problem and no need to appologize whatsoever. Glad that you managed to get it working.

And no need to feel ashamed aswell. We all make mistakes and we're here to learn.
