### ISSUE TITLE
Gatsby Website main container shifted to the right

### ISSUE THREAD

**Issue by olegKusov** [gatsbyjs/gatsby#22389]
## Summary

Make text on website docs closer to left menu. Now it centred inside main container.

### Basic example
Here -> https://www.gatsbyjs.org/tutorial/
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/28058268/77015927-52455b80-6987-11ea-947e-c35338626af0.png">

I have to look at the right side of my monitor. Moreover because of Google people used to watch most of time at the left side and maybe it will be good not just center it on the monitor but make it closer to the left menu. Maybe it will be better to set specific margin-left property. Margin-Left 18% is pretty good and comfortable to read

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/28058268/77016358-76556c80-6988-11ea-8cd1-ce76b1a8b7e3.png">

### Motivation

It will make documentation more comfortable to read.

**Comment by LekoArts** [comment]
Thanks for the issue, but that is nothing we will or want to fix.
