### ISSUE TITLE
Weird bug with pruneLength and Chinese text

### ISSUE THREAD

**Issue by lucasholder** [gatsbyjs/gatsby#22390]
## Description

When the Chinese text in a MDX file is too long, `excerpt(pruneLength: 250)` returns an empty string. When the text is a bit shorter, it returns the expected string of length 250.

### Steps to reproduce

I'm a gatsby noob, not sure how to make a smaller reproduction of the bug... Basically, I did `gatsby new gatsby-prunelength-bug https://github.com/vim-labs/gatsby-theme-sky-lite-starter` and [changed last 2 blog posts](https://github.com/lucasholder/gatsby-prunelength-bug/commit/27efcc4da44c3a48f2cb53f58dd6387cbff6e1d0), one with long Chinese text and other with shorter Chinese text. Here's the guilty line: https://github.com/vim-labs/gatsby-theme-sky-lite/blob/master/src/templates/home.js#L139

```bash
git clone https://github.com/lucasholder/gatsby-prunelength-bug.git;
cd gatsby-prunelength-bug;
npm install;
gatsby develop;
```

<img width="1007" alt="Screenshot 2020-03-18 21 03 36" src="https://user-images.githubusercontent.com/62086489/77021014-f2858b00-695b-11ea-9b07-e139bc36c47a.png">

### Environment

```
gatsby 2.19.48
```

**Comment by jlkiri** [comment]
Apparently this is a bug in the `prune` function that `gatsby-plugin-mdx` uses. Here is the full code:

```
module.exports = function prune(str, length, pruneStr) {
  str = makeString(str);
  length = ~~length;
  pruneStr = pruneStr != null ? String(pruneStr) : '...';

  if (str.length <= length) return str;

  var tmpl = function(c) {
      return c.toUpperCase() !== c.toLowerCase() ? 'A' : ' ';
    },
    template = str.slice(0, length + 1).replace(/.(?=\W*\w*$)/g, tmpl); // 'Hello, world' -> 'HellAA AAAAA'

  if (template.slice(template.length - 2).match(/\w\w/))
    template = template.replace(/\s*\S+$/, '');
  else
    template = rtrim(template.slice(0, template.length - 1));

  return (template + pruneStr).length > str.length ? str : str.slice(0, template.length) + pruneStr;
};
```

The particular line `c.toUpperCase() !== c.toLowerCase()` is the culprit. It returns `false` for every character in the Chinese string, so the whole result is just whitespace. I think we need to switch it to some new dependency.

**Comment by lucasholder** [comment]
@jlkiri thanks.. hopefully your fix will get merged soon!

**Comment by danabrit** [comment]
@lucasholder Can you confirm whether this PR fixed your issue?

**Comment by pvdz** [comment]
Going to close this due to lack of response. If this is still the case please reopen or open a new issue pointing to this issue. Thanks!
