### ISSUE TITLE
my inline image of markdown  from cockpit cms is not transformed by gatsby-remark-image or by gatsby-remark-images-anywhere

### ISSUE THREAD

**Issue by muhzulzidan** [gatsbyjs/gatsby#22398]
my config :

module.exports = {
  siteMetadata: {
    title: `muhzulzidan`,
    author: `muhzulzidan`,
    description: `A student`,
    siteUrl: `https://muhzulzidan.com/`,
    social: {
      twitter: `muhzulzidan`,
    },
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'src',
        path: `${__dirname}/src/`,
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'src',
        path: `${__dirname}/public/static/`,
      },
    },
    
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          `gatsby-remark-copy-linked-files`,
          {
            resolve: `gatsby-remark-images`,
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 590,
            },
          },
          // `gatsby-remark-images-anywhere`,
          {
            resolve: `gatsby-remark-images-anywhere`,
            options: {
              staticDir: '/',
              createMarkup: ({
                src,
                srcSet,
                sizes,
                aspectRatio,
                alt,
                base64,
                presentationWidth,
              }) => {
                return `<custom-image src="${src}" srcset="${srcSet}" sizes="${sizes}" aspectratio="${aspectRatio}" alt="${alt}" base64="${base64}" presentationwidth="${presentationWidth}"></custom-image>`
              },
              loading: 'lazy',
              backgroundColor: '#fff',
              linkImagesToOriginal: true,
              wrapperStyle: 'padding-bottom: 0.5rem;',
              sharpMethod: 'fluid',
              maxWidth: 650,
              quality: 50,
            }
          }
        ]
        }
      },
    {
      resolve: '@fika/gatsby-source-cockpit',
      options: {
        token: 'aaaaa',
        baseUrl:
          'https://blog.muhzulzidan.com', 
        locales: ['id'], 
        collections: [], 
        singletons: [], 
        aliases: {
          collection: {
            A_COLLECTION_NAME: 'aaaa',

          },
          singleton: {
            A_SINGLETON_NAME: 'aaaaa',

          }
        }, 
        brokenImageReplacement: 'https://blog.muhzulzidan.com/storage/uploads/2020/03/18/5e71e3f57ce6dcover.jpg', // (6)
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `cockpit-blog`,
        short_name: `cockpit`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/logo.ico`, 
      },
    },
  ],
}
and i get like this 
![Screenshot from 2020-03-19 17-10-56](https://user-images.githubusercontent.com/55260315/77051015-9aa35e80-6a05-11ea-9e0c-ca7f3c3e6d2d.png)

**Comment by LekoArts** [comment]
Thank you for opening this!

You probably use the plugin `gatsby-remark-images-anywhere` incorrectly. As the normal plugin only works for local files. Please contact the plugin author for help on that as we don't maintain it.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
