### ISSUE TITLE
PackageJson typing

### ISSUE THREAD

**Issue by dvrylc** [gatsbyjs/gatsby#22394]
## Summary

https://github.com/gatsbyjs/gatsby/blob/d2d32d4f61619da5200f2dd15a034cd51f5e9932/packages/gatsby/index.d.ts#L1184-L1202

I'm currently working on something that uses the `PackageJson` interface and was wondering why `dependencies`, `devDependencies`, `peerDependencies`, `optionalDependencies` and `bundledDependencies` are typed as `Array<Record<string, string>>`? 

From the [package.json docs](https://docs.npmjs.com/files/package.json#dependencies), it seems like:  
- `dependencies`, `devDependencies`, `peerDependencies` and `optionalDependencies`: plain objects that map a package name (string) to a version (string)
- `bundledDependencies`: an array of package names (string)

I'd be happy to send a PR if this is a bug. Thanks!

**Comment by dvrylc** [comment]
@blainekasten could I get your help on this? Ran into it while migrating `gatsby-dependents` to TS.

**Comment by blainekasten** [comment]
@dvrylc yeah this isn't correct. It shouldn't be wrapped as an Array. Try and make the change and see if `yarn typecheck` throws any errors. Maybe we are doing some goofy transform in the codebase, but I think this should just be `Record<string, string>`

**Comment by dvrylc** [comment]
Made the changes, `yarn typecheck` looks good!
