### ISSUE TITLE
Folder names containing `()` will silently fail build process

### ISSUE THREAD

**Issue by BerkeleyTrue** [gatsbyjs/gatsby#224]
Seems like If you end a folder name with `(` you get the following error thrown.

![1__tmux](https://cloud.githubusercontent.com/assets/6775919/14123958/db017ef6-f5b7-11e5-819e-fa036bbb31d3.png)

**Comment by benstepp** [comment]
`react-router` uses the parenthesis as a special symbol when creating routes. You can read about the syntax they use [here](https://github.com/reactjs/react-router/blob/master/docs/guides/RouteMatching.md#path-syntax), and it's trying to create an optional group but cannot. Gatsby could decide to support parenthesis in the url with #222. Dynamic routing isn't really needed in a static site.

**Comment by BerkeleyTrue** [comment]
If that is the case, it seems strange that it didn't fail while in develoment mode

**Comment by benstepp** [comment]
Could you visit the broken page in development mode? 

I'm trying to recreate the error, but I just cannot reproduce the same error. I cannot visit a page with parenthesis through hapi or through <Link> even though the page exists in the routing table, but it doesn't get matched ever.

**Comment by BerkeleyTrue** [comment]
That is a good point, I don't remember trying to hit the link directly. With that in mind, it makes sense the static build would fail and the development server wouldn't.

**Comment by KyleAMathews** [comment]
This is perhaps what we need https://github.com/sindresorhus/filenamify

**Comment by BerkeleyTrue** [comment]
What about using encodeURI before hitting the RR matching scheme?

**Comment by jbolda** [comment]
Assuming this is no longer an issue. Reopen if it is.
