### ISSUE TITLE
Make good adaptive design for iPad

### ISSUE THREAD

**Issue by olegKusov** [gatsbyjs/gatsby#22401]
## Summary

![изображение](https://user-images.githubusercontent.com/28058268/77068732-1bf3f480-69f8-11ea-946a-e38bcafc1faa.png)
iPad Mini has menu on the left side of the screen. Very uncomfortable to read. It will be better to set mobile design for 768px. Now it's changes to mobile on 745px.

### Basic example

![изображение](https://user-images.githubusercontent.com/28058268/77068880-6ffed900-69f8-11ea-96ca-e27d092ca15b.png)
I want this design, but not just for 745px but for 768px too. Cause a lot of people using iPads for reading docs.

### Motivation
It will make docs better to read

**Comment by b0nbon1** [comment]
I'd love to work on this one

**Comment by marcysutton** [comment]
Sounds good @b0nbon1, we would welcome your contribution! Here is some info on Website Contributions: https://www.gatsbyjs.org/contributing/website-contributions/

**Comment by b0nbon1** [comment]
@marcysutton, Let me start working on it. Almost forgot about it

**Comment by b0nbon1** [comment]
@marcysutton and @olegKusov the breakpoints that being used are from `gatsby-design-tokens` plugin. So my question is, should I modify the plugin md breakpoint from `750px` to `770px`?
And if yes, I think I'll to also change `gatsby-design-tokens`  docs is that okay?
