### ISSUE TITLE
Recipe to clone Gatsby documentation website

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [gatsbyjs/gatsby#22411]
I want to create a documentation website and I really like how Gatsby documentation website looks like, I know about Docz but it is not cool like Gatsby documentation website.

Is there any recipe, advises about how to achieve this?

**Comment by LekoArts** [comment]
Thank you for opening this!

You could look for documentation themes on our plugins search: https://www.gatsbyjs.org/plugins/
Or study our `www` code: https://github.com/gatsbyjs/gatsby/tree/master/www
Or the starters: https://www.gatsbyjs.org/starters/?c=Documentation&v=2

But besides that you can't reuse our own site. I'd advise trying out one of the above mentioned options.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
