### ISSUE TITLE
How to configure a webpack loader for markdown files (gatsby-plugin-netlify-cms)

### ISSUE THREAD

**Issue by apolopena** [gatsbyjs/gatsby#22420]
I need to load data from frontmatter in an `.md` file generated by a CMS from a `.js` file where graphql is not available (that would be my cms module `.js` file for `gatsby-plugin-netlify-cms`). The error message I continue to receive leads me to believe that all I need to do is add a webpack loader to handle frontmatter ([frontmatter-markdown-loader](https://github.com/hmsk/frontmatter-markdown-loader)) files and configure that in `gatsby-node.js`. All my tests so far have been in the development environment. I have installed the npm ([frontmatter-markdown-loader](https://github.com/hmsk/frontmatter-markdown-loader)) package and added the following to my `gatsby-node.js`:
```
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    module: {
      rules: [
        {
          test: /\.md$/,
          use: [
            {
              loader: 'frontmatter-markdown-loader'
            }
          ]
        }
      ]
    },
  })
}
```

but the following error still appears during development bundle creation:

```
 ERROR  Failed to compile with 1 errors                                                                                                     4:53:43 PM⠀
 error  in ./content/data/cms_ui/blog_tags/section1.md
⠀
Module parse failed: Assigning to rvalue (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> ---
| name: Work
| tags:

 @ ./src/cms/config-netlify.js 12:0-67
 @ ./src/cms/custom-netlify.js
 @ multi ./node_modules/gatsby-plugin-netlify-cms/cms.js ./node_modules/gatsby-plugin-netlify-cms/cms-identity.js ./src/cms/custom-netlify.js
```

I am trying to load the file in /src/cms/config-netlify.js like this:
`import data from '../../content/data/cms_ui/blog_tags/section1.md'`

my `src/cms/custom-netlify.js' looks like this:
```
import CMS from 'netlify-cms-app'
import config from './config-netlify'

CMS.init(config)
```

`src/cms/custom-netlify.js` is configured as a module for `gatsby-plugin-netlify-cms` in `gatsby-config.js` like this:
```
{
      resolve: `gatsby-plugin-netlify-cms`,
      options: {
        manualInit: true,
        modulePath: `${__dirname}/src/cms/custom-netlify.js`
      }
}
```

and finally The contents of the file being loaded `./../content/data/cms_ui/blog_tags/section1.md` is:
```
---
name: Work
tags:
  - headlines
  - UI/UX
  - Design
  - CSS/SCSS/SASS
  - React
  - Front-end
  - Back-end
  - client-side
  - server-side
  - development
  - fullstack
  - MERNStack
  - JAMStack
  - Javascript
  - Python
  - computerlanguage
  - AI/MachineLearning
  - nodejs
  - libraries/packages
  - open-source
  - hardware
  - software
  - bestpractices
  - documentation
---
```
I am guessing there is an issue with how I am configuring ([frontmatter-markdown-loader](https://github.com/hmsk/frontmatter-markdown-loader)) as a webpack plugin in `gatsby-node.js`

I have tried alot of things in gatsby-node.js but nothing works including this:
```
exports.onCreateWebpackConfig = ({   
  stage,
  rules,
  loaders,
  plugins,
  actions, }) => {
  actions.setWebpackConfig({
    devtool: 'eval-source-map',
    module: {
      rules: [
        {
          test: /\.md$/,
          use: [
              'frontmatter-markdown-loader'
          ]
        }
      ]
    },
    plugins: [
      plugins.define({
        __DEVELOPMENT__: stage === `develop` || stage === `develop-html`,
      }),
    ],
  })
}
```

Any light that can be shed on is greatly appreciated.

**Comment by pieh** [comment]
I think this might be the case of plugin ordering - my guess is that we run webpack for cms portion before you add your `.md` webpack rule.

Could your try creating local plugin and test it out:
 - in root of your project create `plugins/gatsby-plugin-frontmatter-markdown-loader` directory
 - create package.json with just
  ```json
  {
    "main": "gatsby-node.js"
  }
  ```
 - create `gatsby-node.js` with your `onCreateWebpackConfig` there
 - add `gatsby-plugin-frontmatter-markdown-loader` to your gatsby-config before `gatsby-plugin-netlify-cms`

**Comment by apolopena** [comment]
Yeah that was it. Thank you so much @pieh.
I will look into making it an external plugin and submitting it to the plugin library.
