### ISSUE TITLE
Gatsby-source-filesystem plugin graphql returns null

### ISSUE THREAD

**Issue by iamsrk** [gatsbyjs/gatsby#22429]
## Summary
I created a gatsby-site and used gatsby-source-filesystem for generating dynamic pages as well as get images. But my Image is not rendered and when I check GraphiQl, I got null.

## Relevant information
I asked a question in [stackoverflow](https://stackoverflow.com/questions/60769666/gatsby-image-plugin-not-working-properly-for-my-web-site#60769841)

### File contents (if changed)
my gatsby-config.js:

```js
module.exports = {
  siteMetadata: {
    title: "Sivaramakrishnan C",
    description: "Full Stack Developer & Systems Engineer @ TCS (Ltd.)",
    author: "Sivaramakrishnan C",
    twitter: "isrkc98",
    facebook: "isrkc",
    instagram: "isrkc",
    telegram: "isrkc",
    github: "iamsrk"
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-sass`,
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'src',
        path: `${__dirname}/src`
      }
    },
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`
      }
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 750,
              LinkImagesToOriginal: false
            }
          }
        ]
      }
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `SRKC`,
        short_name: `srk`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/s.png`,
      },
    },

  ]
}

```

## How to reproduce?

1. Create a gatsby project with the quickstart template [gatsby-starter-hello-world](https://github.com/gatsbyjs/gatsby-starter-hello-world)

2. use gatsby-source-filesystem plugin as shown in above code for two purposes.
3. Restart dev server and go to [GraphiQl](http://localhost:8000/___graphql) page.
4. try to fetch the image file source.
5. The query will return null.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by iamsrk** [comment]
I just updated the way to reproduce

**Comment by LekoArts** [comment]
Please provide a repository that one can clone. Thanks!

**Comment by iamsrk** [comment]
Actually now I changed my starter to gatsby-starter-default and it works now.
