### ISSUE TITLE
Gatsby site not rendering in IE 11

### ISSUE THREAD

**Issue by HiltonGiesenow** [gatsbyjs/gatsby#22437]
I've created a new site using the https://github.com/codebushi/gatsby-starter-photon template, and I've upgraded to the latest version of Node.js (12.16.1) and the latest Gatsby (2.20.1), but I can't get the site to render in IE or the original Edge browsers. I've tried a ton of things I've found on the net, and I'm injecting polyfill.js as well. In fact, I've tried injecting another polyfill directly into the system to support "forEach", but I'm still getting a blank page, and the following error: 

`Object doesn't support property or method 'forEach'`

Can anyone help with this?

**Comment by herecydev** [comment]
It should be fine, I can definitely get the photon starter to work in ie11. Do you want to push a repo with your changes, so we can see what additions are breaking?

**Comment by HiltonGiesenow** [comment]
Sorry if this is a silly question, but what does "push" a repo mean? I've got two private repos here on GH, which I've invited you to check, if that works? The one is described as above, the other is a Docz site, with the same problem (but using a default Docz template, not the Photon starter)

**Comment by KyleAMathews** [comment]
Have you tried building the site to see if the production version works? Babel isn't setup to do polyfilling during development.

**Comment by HiltonGiesenow** [comment]
Yes, I should have specified - both sites (Photon and Docz) I've tried dev, build+serve, and even running live on the internet - same result in both, separate, sites.

**Comment by HiltonGiesenow** [comment]
Here are the sites, live:
https://www.chitchattr.com/ <- In this one it's complaining about forEach
https://apps.chitchattr.com/Help/Shortlinks <- In this one it's complaining about scrollTo

**Comment by herecydev** [comment]
Right so the issue is that you're not doing an array `forEach` you're doing it on a `NodeList` which is a different `forEach` and that is both:

1. Not supported in ie11
2. Not polyfilled by corejs 2. It is done in corejs 3 but Gatsby has [yet to migrate](https://github.com/gatsbyjs/gatsby/issues/15601)

So you can either rewrite the `forEach` or polyfill it like so:

```
if (
  typeof window !== 'undefined' &&
  window.NodeList &&
  !NodeList.prototype.forEach
) {
  NodeList.prototype.forEach = Array.prototype.forEach
}
```

**Comment by HiltonGiesenow** [comment]
Thanks @herecydev , I appreciate your help on this. I've tried the polyfill you've suggested, but it's still not working - same error (I haven't tried live www, only build+serve). I can't even see how to track down which object it's trying to execute the forEach on - how are you seeing that?

**Comment by HiltonGiesenow** [comment]
ah, I figured it out - I wasn't using the browser tools correctly to track the error stack - now I see where the forEach is that's giving the trouble! It was in Photon's TopNav.js, so I've just replaced:

```
		document.querySelectorAll(".navbar li").forEach(function (elem) { 
            elem.onclick = function() {
                document.getElementById("topnav").classList.remove("open");
            };
        });
```
with
```
var liElements = document.querySelectorAll(".navbar li");
		for (let i = 0; i < liElements.length; i++) {
			const elem = liElements[i];
			
			elem.onclick = function() {
                document.getElementById("topnav").classList.remove("open");
            };
		}
```
and now it's working perfectly - thanks so much for the help tracking this down! I'll look more into the docz site now, with this knowledge

**Comment by herecydev** [comment]
@HiltonGiesenow You're most welcome, reach out if you need any further assistance.

**Comment by HiltonGiesenow** [comment]
I got it working for Docz as well, albeit with some ugliness, in case it can help others. Posted here: https://github.com/doczjs/docz/issues/1428
