### ISSUE TITLE
gatsby-plugin-offline only caches page-data.json

### ISSUE THREAD

**Issue by I-Valchev** [gatsbyjs/gatsby#22439]
Hi, I am trying to get a website working offline using `gatsby-offline-plugin`.

It is set up correctly and caches all the files I want cached. However, the service worker only caches `page-data.json` files, not the `.html` files, which means that when offline, I get a page 'No internet' error.

config is:

```
{
      resolve: `gatsby-plugin-offline`,
      options: {
        precachePages: ['/**/!(404).html'],
        debug: true,
      }
    },
```

Any idea on how to fix it?

![Screenshot 2020-03-20 at 15 04 06](https://user-images.githubusercontent.com/7093518/77170958-1233c500-6abc-11ea-86d1-892e30778411.png)

**Comment by LekoArts** [comment]
Hi!

Can you please be more specific of what behavior you're trying to achieve? Your current description is a bit too cryptic to me.

Is this something you want to achieve? https://github.com/gatsbyjs/gatsby/pull/21794

Otherwise, I would expect the service worker to not cache the page-data.json files according to https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-offline#overriding-workbox-configuration

**Comment by I-Valchev** [comment]
Hi @LekoArts , I want the site to work offline... but it does not work, because the `page-data.json` file is cached, rather than the `.html` files themselves.

If you check the code, you'll find that `.html` files are specifically excluded...
https://github.com/gatsbyjs/gatsby/blob/1cfa511af81dabf3f9ceb4741a63f726c774d4d8/packages/gatsby-plugin-offline/src/gatsby-node.js#L111

**Comment by LekoArts** [comment]
Yeah, that's what the linked PR is doing. It's changing the `globPatterns` option. Have you tried following that?

**Comment by I-Valchev** [comment]
Can you provide me with the settings that would be necessary to cache all pages? As in, `**/*`

**Comment by blurr83** [comment]
Hey @I-Valchev - I've had some success with using `globPatterns: ['**/*']` or `globPatterns: ['**/*.{js,jpg,png,html,css}']` under workboxConfig in gatsby-plugin-offline. 

However, my issue is even though its caching everything, nothing works when going offline.

**Comment by I-Valchev** [comment]
@blurr83 right, thanks for this. If I try to use `globPatterns` like you did, I had the same success. It _says_ it caches them, but if you inspect the cache under Application -> Cache -> gatsby-plugin-offline (runtime or precache), there is nothing there. So, it looks like it _says_ it caches the pages, but it _does not_.
