### ISSUE TITLE
docs: Suggestion: unify npm / remove --save from npm install

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#22444]
## Summary

Unify `npm install` commands in docs and all README

Suggested changes:

- [ ] 1) remove `--save` from `npm install`
- [ ] 2) replace `npm i` with `npm install`
- [ ] 3) put `--save-dev` as first param after install
  (`npm install dep1 dep2 --save-dev` -> `npm install --save-dev dep1 dep2`)
- [ ] 4) put commands in code blocks for better copy paste	

### Motivation

- `--save` is not anymore needed - see cpmments:
  - https://github.com/gatsbyjs/gatsby/pull/22359#discussion_r394322764
	> laurieontech: --save is no longer necessary for modern versions of npm, but overall this looks like a solid change!
  - https://github.com/gatsbyjs/gatsby/pull/20520#discussion_r365015636
    > gillkyle: This brings up a good point as something that might be good to start updating across docs elsewhere.
    > 
    > npm 5.0.0 was apparently the version to remove the need to add --save which was published more than 3 years ago

- `i` -> `install` more easy to know for new users what `i` means
- `--save-dev` more visible option
- Putting the install snippet in its own code block makes it easier for people to copy the snippet. I believe this is also consistent with other doc pages. (#22359)

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by muescha** [comment]
it makes sense to have 4 PR after each step?

**Comment by marcysutton** [comment]
Hi @muescha, separate PRs would be helpful to reviewers. Are you still working on this issue? Thanks for filing it!

**Comment by muescha** [comment]
I was waiting for an `ok` before i start

I will do it the next days :)

**Comment by mwlai288** [comment]
Hi, if this still needs to be worked on, I can help out.
