### ISSUE TITLE
docs: add section about LocalizedLink 

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#22446]
## Summary

there should be a section about the `LocalizedLink` in docs (for example in https://www.gatsbyjs.org/contributing/docs-and-blog-components/ )

### Motivation

`LocalizedLink` is introduced with:
- #20797 `[www] Use `localizedLink` for all links`
- #20820 `[www] Update links to use localizedLink` 

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by caitlinselca** [comment]
Hi! I am a new contributor to Gatsby and this particular issue interests me a lot. May I open up a pull request to resolve this ticket?

**Comment by AishaBlake** [comment]
Hey, @caitlinselca! I'm sorry I missed your message! You're welcome to pick this up if you've still got the bandwidth and if you think you'll be able to put up a PR in the next couple of days. This is one of my priorities for this week, so I'll pick it up if that's not possible.

**Comment by AishaBlake** [comment]
Going to go ahead and pick this up for the sake of time. (Again, totally on me. You did the right thing by asking in the issue!) Thank you so much for volunteering, @caitlinselca and please have a look at our [open issues](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) when you have the time. We'd absolutely love to have you as a contributor.
