### ISSUE TITLE
Gatsby cloud doesn't seem to respect the build in packages.json

### ISSUE THREAD

**Issue by raRaRa** [gatsbyjs/gatsby#22450]
## Description

I'm creating a Gatsby blog which should be located inside the directory `/blog`, so I've added the path prefix `/blog` to `gatsby-config.js` and the build inside packages.json has the --prefix-paths prefix: 

```"build": "gatsby build --prefix-paths"```

This looks good locally, but Gatsby cloud doesn't seem to respect it.

### Expected result

I expected Gatsby cloud to run the build with the prefix `--prefix-paths`

### Actual result

Gatsby cloud ran the build without the prefix (it seems).

Any clue if this is a bug or if there's something I'm missing? My blog is open-source and is located here: https://github.com/raRaRa/slidesome.blog

**Comment by LekoArts** [comment]
Hi!

This isn't the right place for issue about Gatsby Cloud, please reach out to support@gatsbyjs.com

Thanks!

**Comment by probablyup** [comment]
@raRaRa what did support end up saying?

**Comment by raRaRa** [comment]
@probablyup You can set an environment variable named `PREFIX_PATHS` to `true` in Gatsby Cloud and your site will be built with the pathPrefix and/or assetPrefix set in your gatsby-config.js. This requires gatsby-cli version 2.9.0 or higher.

Ref: https://www.gatsbyjs.com/docs/cloud-configuration/#how-can-i-build-my-site-with-the---prefix-paths-option
