### ISSUE TITLE
Accordion Items in FAQ on Gatsby Cloud / Pricing has an infinite animation

### ISSUE THREAD

**Issue by timhagn** [gatsbyjs/gatsby#22452]
## Description

On FF: 74.0, Chrome 80.0.3987.149 & Chromium 82.0.4083.0 (Developer Build) Built on Ubuntu 18.04, running on LinuxMint 19.3 (64-bit) your Pricing site has an infinite animation Problem.
The up and down arrows spin endlessly, when an Item's header is opened and focused.

### Steps to reproduce

Open [Pricing | Gatsby Cloud](https://www.gatsbyjs.com/pricing/) on one of the mentioned browsers (haven't tested it on another system yet). Click any of the FAQ Accordion headers to open it. Should the header stay focused, the infinite animation occurs. Only occurs when opened and focused.

### Solution

Set `animation-iteration-count: 0;`, or change the 5th of its `animation` properties from `1` to `0`. (The buttons' classes I am speaking of).

EDIT: Added "Chromium" & the last sentence.

**Comment by greglobinski** [comment]
Thank you @timhagn  The fix is on the way.
