### ISSUE TITLE
Erratic 404 when deploying to GitHub Pages

### ISSUE THREAD

**Issue by ROODAY** [gatsbyjs/gatsby#22459]
## Description

Sometimes when deploying my gatsby page to gh-pages, going to the site gives the github pages 404. However, going to a subpage like /about loads properly, and the whole site is usable, including the home page. However, reloading on the home page or trying to go to it in the address bar results in the 404. After a while it resolves itself, but this is super confusing and I'd like to debug why it happens (I just don't know where to begin).

### Steps to reproduce

1. Have a site on gh-pages (with custom domain and behind cloudflare)
2. Deploy gatsby site
3. Sometimes error happens

### Expected result

Site loads normally

### Actual result

Going to site root gives the github pages 404, but going to a subpage, like /about etc. will load the site properly, and the site works from there. However, reloading on / gives the 404. Eventually the issue solves itself but I'd like to know why.

### Environment
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /c/Python27/python
  Browsers:
    Edge: 44.17763.831.0
```

I've tried hard reloading and turning on dev mode in cloudflare so I don't believe it's a cache problem. Gh-pages

**Comment by ROODAY** [comment]
Update: Deploying another version of the site seemed to fix the issue. I'm starting to suspect that pushing to gh-pages with a build issue present causes this? Not sure why the site semi-works in this state though (going to a subpage load normally)

**Comment by LekoArts** [comment]
Hi!

Can you provide a [minimal reproduction][reproduction]?

> Going to site root gives the github pages 404, but going to a subpage, like /about etc. will load the site properly, and the site works from there. However, reloading on / gives the 404. Eventually the issue solves itself but I'd like to know why.

This sounds more like a caching issue with e.g. Cloudflare? Can you share a live URL where it happens? What happens if you do a hard refresh, so ctrl + F5?
Do you use `gatsby-plugin-offline`?

[reproduction]: https://gatsby.dev/reproduction

**Comment by ROODAY** [comment]
- This sounds more like a caching issue with e.g. Cloudflare: Don't think so, I turned on development mode (disable cache) when the issue occurred and it didn't cause any changes
- Can you share a live URL where it happens: https://quaranteen.university/ however the error isn't there right now
- What happens if you do a hard refresh, so ctrl + F5: When the bug is present this doesn't do anything unfortunately
- Do you use gatsby-plugin-offline: Yes, could this be part of the issue? Something with serviceworkers? (I don't really understand how they work)

**Comment by carloskvasir** [comment]
Add CNAME file in ./static dir
