### ISSUE TITLE
How to I change image paths in meta tag during production build?

### ISSUE THREAD

**Issue by hhimanshu** [gatsbyjs/gatsby#22454]
## Summary
I want to use `Helmet` to add the twitter card. However, I am confused about what path do I mention in **content** attribute?
Assuming I have an image at `src/imgs/post1.jpg`, how can I specify the path once that works in both `dev` and `production` builds?

#### Local Build
```js
<meta name="og:image" content="src/imgs/post1.jpg">`
```
#### Production Build
And what path will be in production build? and how will it get replaced? Do I need to do something?
```js
<meta name="og:image" content="?????">`
```

### File contents (if changed)

```text
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 72.0.2
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.18.17 => 2.18.17
    gatsby-image: ^2.2.32 => 2.2.32
    gatsby-image-sitemap: ^1.2.1 => 1.2.1
    gatsby-plugin-google-analytics: ^2.1.28 => 2.1.28
    gatsby-plugin-iubenda-cookie-footer: ^1.1.1 => 1.1.1
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-mdx: ^1.0.57 => 1.0.57
    gatsby-plugin-react-helmet: ^3.1.14 => 3.1.14
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.2.38 => 2.2.38
    gatsby-plugin-sitemap: ^2.2.21 => 2.2.21
    gatsby-plugin-typography: ^2.3.14 => 2.3.14
    gatsby-source-filesystem: ^2.1.33 => 2.1.33
    gatsby-transformer-sharp: ^2.3.4 => 2.3.4
  npmGlobalPackages:
    gatsby-cli: 2.8.3
```

**Comment by LekoArts** [comment]
Thank you for opening this!

Please have a look at our docs: https://www.gatsbyjs.org/docs/images-and-files/

Especially at the sections:

- Importing Assets Directly into Files
- Using the Static Folder
- Working with Images in Gatsby

You have three options to include the image:

- Import it and let Webpack do the work
- Place the image in `static` folder and reference it
- Use GraphQL to fetch the image

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by hhimanshu** [comment]
This has worked for me. I needed following things things
- A `GraphQL` query to fetch the image
```graphql
allFile(filter: {name: {regex: $slug}, extension: {eq: "jpeg"}}) {
    edges {
      node {
        name
        sourceInstanceName
        childImageSharp {
          fluid {
            src
            sizes
            srcSet
            base64
            aspectRatio
          }
        }
      }
    }
  }
}
```

- Retrieve `imagePath` and send it to `SEO.js` 
```js
const imagePath = data.allFile.edges[0].node.childImageSharp.fluid.src
```

- Use it in `<meta>` tag
```js
  <meta name="twitter:image" content={`${siteUrl}${imagePath}`} />
```

Thanks @LekoArts for the reading references.
