### ISSUE TITLE
Repeated JSON schema due to service worker?

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#22451]
When analyzing my site with a schema tester like [google's one](https://search.google.com/structured-data/testing-tool), I see that the JSON schema is there two times

The first one appears in the head, but it is not completely correct

The second one is an almost identical copy (but with all data correct) and appears at the end, after the `html` end tag, like this:

```js
<!-- Inserted by https://www.mywebsite.com/app-133ed8a06d4862de90ac.js -->
<script type="application/ld+json">
  [
    {
      "@context": "https://schema.org",
``` 

Where this script is from the service worker (`gatsby-plugin-offline`)

The way I'm adding the schema is equivalent to [this one](https://github.com/jlengstorf/gatsby-theme-jason-blog/blob/e6d25ca927afdc75c759e611d4ba6ba086452bb8/src/components/SEO/SchemaOrg.js)

```js
      <Helmet>
        <script type="application/ld+json">{JSON.stringify(schema)}</script>
      </Helmet>
```

Then, what is happening here? Because I am having a partially wrong schema (that is also the first one to be grabbed) and a duplicated schema (that triggers an error in google validator)

**Comment by kuworking** [comment]
Closing, somehow the problem existed only when there were differences in constructing the schema between build time and execution time, and then the service worker somehow inserted the different schema at the end of the document

Once I've used variables that were also available during build time, the issue has disappeared

**Comment by rumbaa01** [comment]
@kuworking hello,

We have the same issue. Our stack is Gatsby, Netlify.
Google test tool says us that schemas are duplicated: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fcodempire.io%2F
One fact is another tool tests it correct: https://search.google.com/test/rich-results?id=Ddk41xl4DLDNargx2baRQg

Could you clarify how did you get the chance to solve this issue? Thanks a lot in advance!

**Comment by kuworking** [comment]
@rumbaa01 hi,

Without being able to actually remember what was the problem and how I solved it, I "think" that my problem was that I was not creating the same schema in development and in building time. This created the duplicated schema I imagine due to the service worker, but this was misleading since the problem was that the schema was wrong.

I imagine (from what I wrote) that once I solved this, the duplicated schema dissapeared as well.

In your case I can see that your duplicated schemes look identical, so my impression is that you have a different problem.

That said, if you don't need the service worker you could try deleting it and see if this helps. I ended up concluding that unless I wanted my content available as a pseudo-offline app, this plugin wasn't worth for me.

Sorry for not being able to help more!
