### ISSUE TITLE
[gatsby-plugin-typography] Getting a error after adding gatsby-plugin-typography config

### ISSUE THREAD

**Issue by lianglingjiang** [gatsbyjs/gatsby#2246]
I am following the tutorial at part two. After adding typography.js config `gatsby-config.js`, and run 
```
gatsby develop
```
I get the following error, the server not starting.
```
Your plugins must export known APIs from their gatsby-node.js.
The following exports aren't APIs. Perhaps you made a typo or
your plugin is outdated?

See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby Node APIs

 — The plugin "gatsby-plugin-typography@1.7.10" is exporting a variable named "onPreBootstrap" which isn't an API.
```
 I try to copy and paste the code form the tutorial and reinstall node, but keep getting the same error. Please help to check.

**Comment by KyleAMathews** [comment]
Oh hmmm sorry. This plugin along with gatsby were updated earlier together. Just update Gatsby to the latest version and it'll work.

**Comment by lianglingjiang** [comment]
Just tried again, the npm command
```
npm install --global gatsby-cli
```
installs:
 `gatsby-cli@1.1.7`
I think this is the lastest. Still not working. :/

**Comment by KyleAMathews** [comment]
In your site run:

`npm install --save gatsby@latest`

**Comment by lianglingjiang** [comment]
It works! Thanks for helping.
Hope the main release will fix this soon. :)
