### ISSUE TITLE
Dealing with a large number of images

### ISSUE THREAD

**Issue by LpmRaven** [gatsbyjs/gatsby#22486]
I'm looking for some advice on dealing with a large number of images. I currently have an e-commerce website with ~2000 images (which could increase 100x). Up to this stage in development, I have not been using images for each product, but I now have an AWS S3 bucket for the images. Gatsby is referencing that S3 bucket using `gatsby-source-s3-image` through my image component. I'm not sure if it is wise to be using gatsby to process all of these images at build time, or whether I should be processing these images server-side when they are added to the bucket. The production build is already timing out when processing this number of images, I don't think this setup is sustainable for growth of an e-commerce site.

Summary:
- Ecommerce website
- ~2000 image (could be 100x that amount)
- Using AWS Codebuild to build production code
- Using `gatsby-source-s3-image` plugin
- Production build is timing out

Does anyone have any suggestions of how I should deal with this?

**Comment by LekoArts** [comment]
Thank you for opening this!

> Does anyone have any suggestions of how I should deal with this?

Short answer: Keep your `.cache` and `public` around. Gatsby already has a good caching mechanism in place with these two folders. This way you will only generate the added images with changes (after an initial build of all images of course). And if that initial build times out, build it on a more powerful machine once and push the build artifacts to that cache.

You can also try to put the image generation into cloud functions like Netlify did it with their (experimental) plugin: https://www.netlify.com/blog/2020/02/25/gatsby-build-speed-improvements-with-parallel-image-processing/

Some other folx use things like [Cloudinary](https://cloudinary.com/).

Last but not least, there is also our own CI/CD solution called [Gatsby Cloud](https://www.gatsbyjs.com/). We keep the cache around and put the image transformations into parallel cloud functions. You could try it for free :)

Hope these answers clear some things up, we can't be experts on any stack so those might feel a bit more like general advice. I'd suggest asking in our communities and see how other people do it.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by LpmRaven** [comment]
Cheers @LekoArts. I'm not sure how I'll be able to retain those between builds but I'll take a look, thanks for the guidance.
