### ISSUE TITLE
Incremental Builds question

### ISSUE THREAD

**Issue by babyPrince** [gatsbyjs/gatsby#22489]
Hi there, 

I just discovered Gatsby now offers Incremental Builds. Are incremental builds offered only for Gatsby Cloud or they are by default working with Netlify for eg.?

Asking because I'm planning to use gatsby for medium/large editorial site (lots of articles) and having concerns about build time (rebuilding the same pages again and again).

**Comment by LekoArts** [comment]
Thank you for opening this!

Thank you for opening this!

> I just discovered Gatsby now offers Incremental Builds.

Where have you read that? As it's (factual) not correct (yet). We announced Gatsby Builds here and said that they will follow: https://www.gatsbyjs.org/blog/2020-01-27-announcing-gatsby-builds-and-reports/

> Asking because I'm planning to use gatsby for medium/large editorial site (lots of articles) and having concerns about build time (rebuilding the same pages again and again).

"Incremental" is really only a scale, not something absolute. We're working on quicker and quicker builds to eventually get to e.g. builds under 10 seconds. We recently made a lot of improvements to build times and will keep doing that. Those of course benefit all users, e.g. on Netlify. But Gatsby Cloud will always be the best platform for building and deploying Gatsby sites - you can try our generous free tier, too.

Other than that: You can optimize your build speeds by using the mentioned methods in the blog post, so keeping the cache or outsourcing your image transformations.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by babyPrince** [comment]
Thanks for the reply. I've read it in the same post. The article presents incremental builds as an available thing, not a future feature.
