### ISSUE TITLE
Do not copy tests into .cache directory

### ISSUE THREAD

**Issue by LegNeato** [gatsbyjs/gatsby#2249]
It appears gatsby caches its tests:

```sh
$ ls -1 .cache/__tests__/
__snapshots__
find-page.js
loader.js
prefetcher.js
```

I am using `yarn`'s workspace support and `jest`. Jest by default tries to run the tests in the cache and fails with a bunch of errors like:

```
Loader › It stops downloading when the resourcesArray is empty

    TypeError: Cannot read property 'empty' of undefined
      
      at Object.<anonymous> (my_site/.cache/__tests__/prefetcher.js:11:15)
          at Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)
```

In order to get my tests to pass I had to add the cache directory to jests's ignores in `package.json`:
```
    "testPathIgnorePatterns": ["/node_modules/", "/\\.cache/"],
```

**Comment by KyleAMathews** [comment]
Oh hmmm... that is bad. Could you put together a PR fixing the copying here?

https://github.com/gatsbyjs/gatsby/blob/f05d736ca8a4aa7b188ceaefa3fee80cebba6343/packages/gatsby/src/bootstrap/index.js#L153

**Comment by LegNeato** [comment]
Hmmm, could possibly be due to my setup? I get the same error running `yarn test` in gatby's repo too.

**Comment by KyleAMathews** [comment]
Closing this issue as it's fairly old and we have far too many open issues! If you have additional problems in this area, please open a new issue!
