### ISSUE TITLE
www: error with documentationjs at comments in TS files

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#22492]
## Note

this issue created from comments from this PR:
- #22455 `fix(www): remove comments that are causing builds to fail`

## Description

When #22381 was merged builds started failing for `www` (the docs site). The error looks like this:

```text
11:01:06 AM: error { "commentNumber": null, "level": 1, "id": "827a9a3a-6d53-5ec1-bde7-32147298b648", "parent": "ec28ebff-f198-59bc-9d97-9f0662e37679", "children": [ "f923a690-d5e9-5170-a02b-b51a17706ae7", "4bddd280-f7d7-5922-821a-89604b600b2f", "ed3d70f6-d142-5e7b-92f7-29ede823380d" ], "internal": { "type": "DocumentationJs", "contentDigest": "358a5703a82d2d403134479c9cf283fe", "counter": 7689, "owner": "gatsby-transformer-documentationjs" }, "kind": "function", "memberof": "plugins", "name": "minifyJs", "scope": "static", "examples": [], "tags": [], "optional": false, "docsLocation": { "start": { "line": 519, "column": 2 }, "end": { "line": 522, "column": 5 } }, "codeLocation": { "start": { "line": 523, "column": 2 }, "end": { "line": 551, "column": 6 } }, "description___NODE": "f923a690-d5e9-5170-a02b-b51a17706ae7", "params___NODE": [ "4bddd280-f7d7-5922-821a-89604b600b2f" ], "returns___NODE": [ "ed3d70f6-d142-5e7b-92f7-29ede823380d" ], "members": {} } 
error The node internal.owner field is set automatically by Gatsby and not by plugins
11:01:06 AM: not finished source and transform nodes - 21.021s
11:01:06 AM: ERROR Failed to compile: Error: Exited with code 1
```

```json
{
  "commentNumber": null,
  "level": 1,
  "id": "827a9a3a-6d53-5ec1-bde7-32147298b648",
  "parent": "ec28ebff-f198-59bc-9d97-9f0662e37679",
  "children": [
    "f923a690-d5e9-5170-a02b-b51a17706ae7",
    "4bddd280-f7d7-5922-821a-89604b600b2f",
    "ed3d70f6-d142-5e7b-92f7-29ede823380d"
  ],
  "internal": {
    "type": "DocumentationJs",
    "contentDigest": "358a5703a82d2d403134479c9cf283fe",
    "counter": 7689,
    "owner": "gatsby-transformer-documentationjs"
  },
  "kind": "function",
  "memberof": "plugins",
  "name": "minifyJs",
  "scope": "static",
  "examples": [],
  "tags": [],
  "optional": false,
  "docsLocation": {
    "start": {
      "line": 519,
      "column": 2
    },
    "end": {
      "line": 522,
      "column": 5
    }
  },
  "codeLocation": {
    "start": {
      "line": 523,
      "column": 2
    },
    "end": {
      "line": 551,
      "column": 6
    }
  },
  "description___NODE": "f923a690-d5e9-5170-a02b-b51a17706ae7",
  "params___NODE": [
    "4bddd280-f7d7-5922-821a-89604b600b2f"
  ],
  "returns___NODE": [
    "ed3d70f6-d142-5e7b-92f7-29ede823380d"
  ],
  "members": {}
} 
```

This error pointed at the `documentationjs` transformer and the lines it identified didn't seem problematic, but removing them is enough to fix builds.

The problematic lines are:

https://github.com/gatsbyjs/gatsby/blob/e65eef43570c41c4f49c9e7dd177218702bb7bf5/packages/gatsby/src/utils/webpack-utils.ts#L519-L522
https://github.com/gatsbyjs/gatsby/blob/e65eef43570c41c4f49c9e7dd177218702bb7bf5/packages/gatsby/src/utils/webpack-utils.ts#L625-L628

It only became a problem when the file changed to TypeScript. Maybe there's a discrepancy between how it parses JS and TS?

### Steps to reproduce

Checkout PR #22381

### Expected result

no error

### Actual result

error:

`error The node internal.owner field is set automatically by Gatsby and not by plugins`

### Related Issues

- #22455 `fix(www): remove comments that are causing builds to fail`

**Comment by marcysutton** [comment]
Although we've seen this in the past week, I'm not getting this error when I run the site locally. Are you sure you're on the latest `master`?

**Comment by muescha** [comment]
it was fixed with #22455 with removing the comments

**Comment by muescha** [comment]
but i check it with current master

**Comment by muescha** [comment]
steps to reproduce:
- updated gatsby-cli 
- checkout master
- start `gatsby develop`
- i see no errors
- changed code with adding comments
- i get the error in the console
