### ISSUE TITLE
docs: starter missing in README and in /starters/

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#22503]
## Summary

when i look at this places:

- https://github.com/gatsbyjs/gatsby/tree/master/starters
- https://www.gatsbyjs.org/starters?s=gatsby-starter&v=2
- https://www.gatsbyjs.org/docs/starters/
- https://www.gatsbyjs.org/docs/gatsby-cli/
- https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/README.md
- https://github.com/gatsbyjs/gatsby/blob/f79f26b268c635874fb4eb8199a8231b31fd889b/packages/gatsby-cli/src/init-starter.ts#L224-L232

there are only 3 starters listed.

but there are much more listet in: https://github.com/gatsbyjs/gatsby/tree/master/starters

this starters also not have a home page like https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-hello-world/

### Motivation

all official starters should have should be visible also in the starters library

## Steps to resolve this issue

- [ ] add more starters to the readme at https://github.com/gatsbyjs/gatsby/blob/master/starters/README.md

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by Edmund-Adewu** [comment]
Hello. I am a new contributor to Gatsby. This particular issue is of great interest to me. Would it be alright if I opened a pull request to resolve it?

**Comment by Edmund-Adewu** [comment]
Good afternoon, @muescha. I am still interested in the issue. Would it be possible to remove the stale label? I would appreciate it.

**Comment by muescha** [comment]
Friendly ping to @gatsbyjs/learning 
asking if it is ok for Edmund to go on working on a PR or is there a reason not listing it?

**Comment by praveenweb** [comment]
Related issue - https://github.com/gatsbyjs/gatsby/issues/22733

**Comment by muescha** [comment]
@praveenweb it is not related, because in 22733 it describes a bug, that configured starters are not created/skipped

but in the current issue there are some default gatsby starters which are not added to docs and configs

**Comment by muescha** [comment]
not stale

PR is still open...

- #24089 `fix(docs) Add missing starter info to Gatsby/starters`

**Comment by pieh** [comment]
Absolutely - this is not stale.

**Comment by pieh** [comment]
> add missing starters to starters.yml

I think we need to update this issue a little bit, because showcase/starter submissions are temporarily on pause ( https://github.com/gatsbyjs/gatsby/pull/26442 ), but the rest of it is still relevant.
