### ISSUE TITLE
[contributing] Document available Frontmatter keys for blog posts and docs

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#22511]
## Summary

When writing a blog post on the Gatsbyjs.org website, it's very unclear what the available options are for frontmatter–particularly around images and social sharing. One has to look at other content in the repo to see what's in use, which is not easy for content contributors to do.

This issue is about documenting available Frontmatter fields in the contributing docs. These additions could go here: https://www.gatsbyjs.org/contributing/docs-and-blog-components/#writing-content-in-markdown

### Motivation

To make it easier to contribute blog posts and docs written in Markdown

## Steps to resolve this issue

Edit the contributing doc for [Docs and Blog Components](https://www.gatsbyjs.org/contributing/docs-and-blog-components/) with every Frontmatter entry used on the gatsbyjs.org website, such as `image` (including expected dimensions: is it square? horizontal? which templates resize in GraphQL queries?), `imageTitle`, `showImageInArticle`, `excerpt`, etc. The doc should explain how to use the fields and what to expect in terms of rendering, including social sharing on Twitter or Facebook. Be sure to reference the various templates in `src/www` to explore what is used from Markdown files.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by laneparton** [comment]
I'm working on this and will open a PR within the next few days.

**Comment by marcysutton** [comment]
@laneparton that's amazing! Let us know if you have any questions as you embark on this spelunking mission.

**Comment by muescha** [comment]
i missed `frontmatter` also in the glossary...
