### ISSUE TITLE
Add a way to add "frontmatter" to React pages

### ISSUE THREAD

**Issue by LegNeato** [gatsbyjs/gatsby#2251]
If you want pages to define metadata that can be queried via GraphQL, you are stuck using markdown or writing your own plugin. If your pages are React components, there is no way to expose metadata/frontmatter for querying (if I missed it let me know!).

**Comment by LegNeato** [comment]
I'm thinking we `require` the component and add any non-default exports to a field (`exports`?) similar to `frontmatter` in the markdown plugin.

Happy to put up a patch if you agree with that direction and can point me in the proper direction on where to make the change 😄 .

**Comment by jquense** [comment]
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-javascript-static-exports :)

**Comment by LegNeato** [comment]
Whoo!
