### ISSUE TITLE
Get link to compiled stylesheet without inserting in the document

### ISSUE THREAD

**Issue by deammer** [gatsbyjs/gatsby#22514]
## Summary

I'm attempting to embed React components inside of an iframe to document my codebase. The most difficult problem to solve has been *passing CSS to that iframe*. I have a working prototype where I am adding the stylesheet to the entire page and then copying its `href` to the iframe's body.

**My question is:** is there is a cleaner way to reference that stylesheet? I don't want to import it in my Gatsby app, I only want to import it within the iframe. My ideal scenario would be telling Gatsby to compile the file and give me a link to it.

## Relevant information

I use `react-frame-component` to write JSX inside of an iframe.

```jsx
// App.jsx
/* The entry point of my Gatsby app  */

import React from 'react'
import "./styles/index.css" // import the stylesheet

// ... render my Gatsby app
```

```jsx
// Demo.jsx
/* The iframe wrapper I use to preview components */
import React, { Fragment } from "react"
import Frame from "react-frame-component"

const Demo = props => {
  // Get the stylesheet from the <head> of the site
  const topLevelStylesheet = document.getElementsByTagName("link")[0]

  return (
    <Frame>
      <Fragment>
        {/* Hard-code the stylesheet within the iframe (not great!) */}
        <link rel="stylesheet" href={topLevelStylesheet.href}></link>
        {props.children}
      </Fragment>
    </Frame>
  )
}
```

```jsx
// ButtonDemo.js
/* An example component preview (I use Tailwind CSS) */

import React from 'react'

const ButtonDemo = () => (
  <Demo>
    <button className="bg-blue-500 text-white font-bold p-4 rounded">Click me!</button>
  </Demo>
)
```

### File contents (if changed)

_Not including any config here because I don't think it's relevant._

**Comment by Js-Brecht** [comment]
Couldn't you put the `.css` file in your `static` folder?  Something like `./static/styles/index.css`.  Then in your iframe you could reference that location like `/styles/index.css`.  If you wanted to make it more dynamic, the `Demo` component could receive the css url as a prop, so the calling component can determine what css will be loaded.

**Comment by Js-Brecht** [comment]
If you wanted Webpack to process the CSS before you insert it into the iFrame, you could use an [inline loader](https://webpack.js.org/concepts/loaders/#inline), and inject that data into a `<style>` tag, instead of using a `<link>` tag

**Comment by deammer** [comment]
@Js-Brecht those are both great ideas, thank you! With your help, I was able to maintain the hot-reload functionality and have webpack process my CSS. Here's how I modified my original code:

```jsx
// Demo.jsx
/* The iframe wrapper I use to preview components */
import React, { Fragment } from "react"
import Frame from "react-frame-component"
import styles from "!raw-loader!postcss-loader!../../src/styles/index.css"

const Demo = props => {
  return (
    <Frame>
      <Fragment>
        <style dangerouslySetInnerHTML={{ __html: styles }} />
        {props.children}
      </Fragment>
    </Frame>
  )
}
```
