### ISSUE TITLE
Cannot destructure property `wpgraphql` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by rayjencode** [gatsbyjs/gatsby#22526]
## Description

Always getting an error "Cannot destructure property `wpgraphql` of 'undefined' or 'null'" 
See Screesnhot: https://imgur.com/hQCGxaR

### Steps to reproduce

Im using wpgraphql ACF CPT UI. At first I registered a Custom Post type for "Event" then everything works. fetching wpgraphql schema and creating pages works like a charm. Then suddenly when I registered a new one "Courses" custom post type, this error happens. I trouble shoot it assuming I have a typo until I notice that my code is not the problem because even I try to comment some code to see the changes then error still the same. So what I did is I ask for help from the wpgraphql slack group and mentioned JSON bahl, so he told me try to Gatsby clean, but it won't fix the issue. So he mentioned TylerB hoping for help and it seems Tyler recommend to open an issue at Gatsby Repo. 

See screenshot: https://imgur.com/J2tQAUW

### Actual result

See Screesnhot: https://imgur.com/hQCGxaR

### Environment

Run `gatsby develop`

### My Project Repo

https://github.com/rayjencode/gatsby-wp-university

**Comment by TylerBarnes** [comment]
@vladar , Rayjens brought this up on the WPGraphQL slack. To me it sounds like a `gatsby-source-graphql` bug but I'm not entirely sure. Do you have any thoughts on what it could be?

**Comment by TylerBarnes** [comment]
@rayjencode are you able to put your WP instance up on a server somewhere so we can use it to reproduce the issue?

**Comment by rayjencode** [comment]
> @rayjencode are you able to put your WP instance up on a server somewhere so we can use it to reproduce the issue?

Hello Tyler, you mean I have to host it online or just the root file of WP?

**Comment by rayjencode** [comment]
I manage to host my wordpress to live sir. 
http://melon.rankdepartment.com/wp-admin (user & pass: admin)

My project repo: https://github.com/rayjencode/gatsby-wp-university

Hope it helps

**Comment by vladar** [comment]
Your [GraphQL schema](http://melon.rankdepartment.com/graphql) has no `events` field on RootQuery type. And you are [querying it here](https://github.com/rayjencode/gatsby-wp-university/blob/a21ac51ebbb46a48df1c4e05b6d0b5bce71e5247/gatsby/createEvents.js#L7-L10).

So either your query is wrong (maybe you must change it to `eventFields`?) or something is wrong with server-side schema.

**Comment by rayjencode** [comment]
Thank you so much guys :) Fixed it :D
