### ISSUE TITLE
i got this error  how to fixd owlcarousel error

### ISSUE THREAD

**Issue by maulikserantec** [gatsbyjs/gatsby#22534]
how to fixd : https://user-images.githubusercontent.com/47684990/77394423-588f6980-6dc5-11ea-8630-042a32458afb.png

  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.org/docs/
  - How to File an Issue: https://www.gatsbyjs.org/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues

**Comment by LekoArts** [comment]
Thank you for opening this!

This is an error in how you use that particular package. I'd advise opening an issue on their repository. You don't have access to `window` on the build process and the library should guard against it. Alternatively you can read https://www.gatsbyjs.org/docs/debugging-html-builds/ to fix it.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
