### ISSUE TITLE
gatsby-telemetry "isTrackingEnabled" is always truthy (returns a function)

### ISSUE THREAD

**Issue by Eyas** [gatsbyjs/gatsby#22531]
## Description

gatsby-telemetry's index.js exports an ["isTrackingEnabled" function](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-telemetry/src/index.js#L31).

That function is defined as:

```
  isTrackingEnabled: () => instance.isTrackingEnabled,
```

where `instance` is:

```
const instance = new Telemetry()
```

but `isTrackingEnabled` on `Telemetry` is a **boolean returning function**, not a boolean.

Elsewhere in the code, e.g. in [`gatsby commands/build.js`](https://github.com/gatsbyjs/gatsby/blob/e4cd2f135cd2385cc9ba1dd78cb3f3d457c5b6d3/packages/gatsby/src/commands/build.js#L138) uses `isTrackingEnabled` like so:

```
  if (telemetry.isTrackingEnabled()) {
```

... which will always be true, since it will return a function.

### Steps to reproduce

1. Disable tracking
2. Run build

### Expected result

No tracking.

### Actual result

Build will still be tracked.

**Comment by Eyas** [comment]
Hi @rase- (author) and @sidharthachatterjee / @pieh / @jamo (reviewers). Just wanted someone with some domain expertise in gatsby-telemetry to look at this bug, probably introduced in #20146

**Comment by jamo** [comment]
Nice catch and thanks for the ping!

I have a feeling in the index.js it should be calling the function instead of returning the function.

**Comment by jamo** [comment]
It's worth mentioning that inside of the telemetry instance we check if tracking is enabled, before buffering any events. This means that we never sent and captured any telemetry events. Despite the optimization of avoiding unnecessary flushing events wasn't working. 

https://github.com/gatsbyjs/gatsby/pull/22532/files#diff-5ba4bdbd00073c090bffb5c50d1f64e6R376

**Comment by AhsanAyaz** [comment]
Hey folks.
I saw that a PR for migrating to typescript is already in progress. Investigated the code for this issue and created a fix (PR) still just in case 🙃
