### ISSUE TITLE
gatsby develop stop mid-action after cli update

### ISSUE THREAD

**Issue by EliranGooner** [gatsbyjs/gatsby#22543]
I had some error who crushed the localhost server which I fixed the initial problem 100% but then I saw a new gatsby cli update available so I updated it before re-running ```gatsby develop```. 

This is the project: https://github.com/EliranGooner/zeitouni (didn't push anything today as of yet)

From there on whenever I try to run ```gatsby develop``` the process gets to 'initialize cache'  and abruptly stopping without throwing any error.

So now I'm not able to run the development gatsby server.

edit: I just now noticed in the environment check that the gatsby-cli actually did not update from the command ```yarn add gastby cli``` so I ran it again and still it's not updated. I should add that yarn says it installed gatsby-cli 2.11.1 successfully which is odd.

My environment: 
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.7 => 2.19.43 
    gatsby-background-image: ^0.10.2 => 0.10.2 
    gatsby-cli: ^2.11.1 => 2.11.1 
    gatsby-image: ^2.2.39 => 2.2.43 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.2.39 => 2.2.47 
    gatsby-plugin-offline: ^3.0.32 => 3.0.40 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.23 
    gatsby-plugin-sass: ^2.1.30 => 2.1.30 
    gatsby-plugin-sharp: ^2.4.3 => 2.4.12 
    gatsby-source-filesystem: ^2.1.46 => 2.1.55 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.18 
  npmGlobalPackages:
    gatsby-cli: 2.10.9

**Comment by connorlindsey** [comment]
I'm not sure, but it may be worth a shot to run `gatsby clean` and re-try `gatsby develop`. That often fixes errors.

**Comment by EliranGooner** [comment]
> I'm not sure, but it may be worth a shot to run `gatsby clean` and re-try `gatsby develop`. That often fixes errors.

Yeah ```gatsby clean``` fixed it, I was just about to close the issue having it working and saw your comment.
