### ISSUE TITLE
Can see active users but graph of user is always 0

### ISSUE THREAD

**Issue by manan2501** [gatsbyjs/gatsby#22575]
## Description

I am able to observe active users. But there is no reflection in the user, it always remains zero. This is the repository of my website => https://github.com/bhavesh0206s/wizards-words

### Steps to reproduce

I cannot say anything specific. But, I just followed these instructions https://www.gatsbyjs.org/docs/adding-analytics/

### Expected result

Active users should be reflected in users graph

### Actual result

Active users can be observed but no reflection is found in users graph
![image](https://user-images.githubusercontent.com/43081866/77582743-e1adba00-6f05-11ea-91c6-213820d5c110.png)

**Comment by wardpeet** [comment]
Hey,

I can't immediately see any issues on our side. How long have you been running analytics? It might take some time to show this data.

Google Analytics is sending it's data to `UA-132331512-1`, are you sure it's the correct account?

**Comment by manan2501** [comment]
I have been running analytics since 23:00 IST on 25th march (Yesterday night). And yes `UA-132331512-1` is the correct Tracking ID.

**Comment by manan2501** [comment]
Sorry, I had closed it by mistake.

**Comment by madalynrose** [comment]
Yeah I'd say give it a little more time. Google analytics takes 24+ hours to start showing accurate data. Let us know if this isn't resolved in the next day or so! Additionally, they have some [good documentation around initial setup troubleshooting](https://www.analyticsmania.com/post/google-analytics-real-time-reports-not-working/) that might prove useful. Closing for now.
