### ISSUE TITLE
[gatsby-transformer-yaml] Support for multiple data layouts

### ISSUE THREAD

**Issue by r1b** [gatsbyjs/gatsby#2257]
I have been struggling to integrate gatsby with netlify-cms when using `gatsby-transformer-yaml`. Currently netlify-cms does not support collections defined in a single file [1]. I created a custom yaml plugin [2] to reconcile the two projects. Now I am curious if there is a path towards integrating this custom transformer with `gatsby-transformer-yaml` to support a variety of data layouts.

[1] https://github.com/netlify/netlify-cms/issues/531
[2] https://github.com/computer-lab/gatsby-transformer-yaml-netlify

**Comment by KyleAMathews** [comment]
So what does your transformer do differently? Looks at a quick glance to be quite similar.

**Comment by r1b** [comment]
`gatsby-transformer-yaml` mandates a data layout where collections are stored as lists at the top-level of a yaml file. Each entry in the list becomes a node with the `type` determined by the name of the file.

`gatsby-transformer-yaml-netlify` mandates a data layout where collections are stored as multiple yaml files in a subfolder. The top level of the yaml file is an object. Each yaml file becomes a node with the `type` determined by the name of the subfolder.

**Comment by KyleAMathews** [comment]
Hmmm yeah it could make sense then yeah that if the top-level of the YAML file is an object, make it into a node with the directory name as the type and then if it's an array, make it into a node with the filename as the type.

Yeah, that seems like a really good pattern. You want to make a PR for this? Also to the JSON transformer since they work the same way?

**Comment by r1b** [comment]
For sure - I should have some time later tonight to start working on it.

**Comment by swim** [comment]
Having the JSON transformer behave in this manner as well would be very nice =)

**Comment by r1b** [comment]
Closed by #2324
