### ISSUE TITLE
Where is this extra viewport tag coming from? Is this a bug?

### ISSUE THREAD

**Issue by jcontonio** [gatsbyjs/gatsby#22595]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/2809/77692814-8959d500-6f64-11ea-8a24-ad83fd0146f2.png">

I have a very basic Gatsby site, using only `react-helmet`, not the Gatsby React Helmet plugin, as I want total control of my meta tags. Here is my Gatsby plugins list:

```
plugins: [
    `gatsby-plugin-sass`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
]
```

Something, somewhere, is sticking in the `charset`, `viewport`, and `http-equiv` into my documents and shouldn't be. Any ideas?

**Comment by arthurjdam** [comment]
These are part of the wrapper defined in [html.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/default-html.js), and generally considered good practice.
If you want to change or remove these, take a look at [Customizing html.js](https://www.gatsbyjs.org/docs/custom-html/)

**Comment by LekoArts** [comment]
Thank you for opening this!

As Arthur said we include those as they are considered best practice and necessary for every site. I wouldn't recommend changing those however, the linked doc would explain how to do it.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
