### ISSUE TITLE
[gatsby-transformer-json] Example given in Readme seems to not be working

### ISSUE THREAD

**Issue by azer** [gatsbyjs/gatsby#2259]
Hey there,

I've tried the example in README, and got following error in GraphiQL:

```

  "errors": [
    {
      "message": "Cannot query field \"query\" on type \"RootQueryType\".",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
```

I saved letters.json file under src folder. Am I doing anything wrong ?

**Comment by delacannon** [comment]
Hi,

It's working for me. Make sure your letters.json file is well formatted:

```
[
	{ "value": "a" }, 
	{ "value": "b" }, 
	{ "value": "c" }
]
```

You'd be able to query your letters like

```
{
  allLetterJson {
    edges {
      node {
        value
      }
    }
  }
}
```

**Comment by KyleAMathews** [comment]
It'd help to post the query you tried.

Also, try using the auto-complete (ctrl-space) to explore the schema.

Also go through part 4 of the tutorial if you haven't already.

**Comment by azer** [comment]
I tried the same example in the README and got this result. I went through the tutorial before, markdown plugin works fine. Only JSON gives this error:

```
{
  "errors": [
    {
      "message": "Cannot query field \"allLettersJson\" on type \"RootQueryType\".",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
``` 

I tried many queries, including the one @delacannon recommended above. I have a letter.json saved under src folder in the project.

**Comment by sebastienfi** [comment]
Hello @azer  Could you please build a small reproduction site to check out and upload to a Git repo ? That way it's way quicker to reproduce your error and solve it ;)

**Comment by Kalcode** [comment]
gatsby-source-filesystem is needed to use JSON transformer. I think that is missing from the readme and causing the confusion?

**Comment by azer** [comment]
Yeah, filesystem was missing. Fixed now.

**Comment by marcata** [comment]
Would you kindly tell me or point me to a resource about how to make the transformer work, specifically how I have to configure gatsby-source-filesystem so it works with letters.json? I can't find any information about this.

**Comment by m-allanson** [comment]
Hey @marcata, the [gatsbygram example site](https://github.com/gatsbyjs/gatsby/blob/master/examples/gatsbygram/gatsby-config.js) uses `gatsby-source-filesystem` with `gatsby-transformer-json`, does that help?
