### ISSUE TITLE
[gatsby-plugin-google-analytics] Need custom definition usage (custom dimensions and metrics)

### ISSUE THREAD

**Issue by ZLevine** [gatsbyjs/gatsby#22608]
## Summary

The gatsby-plugin-google-analytics plugin works well but lacks information on how to set custom dimensions (or other fields) prior to the pageview hit being sent. Some data can be set in `gatsby-config` but this doesn't work for anything dynamic.

## Relevant information

For example, I need to retrieve a GET parameter value and set it as a custom dimension _before_ the pageview hit is sent so that all subsequent hits (including pageview) will include this information.

For example, take the following URL: `https://howchoo.com/h/pi?ref=interest_list`

_Before_ the GA pageview it is sent, I would normally set it here:

```javascript
ga('set', 'dimension5', 'custom data');
```

I could theoretically retrieve the value in `gatsby-browser` and set it there, but GA doesn't provide a true async queue before the `ga` object is defined AFAIK. Therefore, I'd need to be sure it gets set _before_ the plugin sends the pageview hit.

How could this be done? The plugin isn't clear about how custom definitions (dimensions and metrics) can be set _before_ the pageview hit is sent. [This](https://github.com/gatsbyjs/gatsby/blob/230e8d70b3581ae635b649810ec5b682841bfd74/packages/gatsby-plugin-google-analytics/src/gatsby-browser.js#L19) seems to be a relevant section of code.

### Environment (if relevant)

```bash
  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    npm: 6.10.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.45 => 2.19.45
    gatsby-plugin-disqus: ^1.1.4 => 1.1.4
    gatsby-plugin-google-analytics: ^2.1.38 => 2.1.38
    gatsby-plugin-google-tagmanager: ^2.1.27 => 2.1.27
    gatsby-plugin-less: ^3.0.21 => 3.0.21
    gatsby-plugin-lodash: ^3.1.22 => 3.1.22
    gatsby-plugin-manifest: ^2.2.48 => 2.2.48
    gatsby-plugin-mdx: ^1.0.83 => 1.0.83
    gatsby-plugin-offline: ^3.0.41 => 3.0.41
    gatsby-plugin-react-helmet: ^3.1.24 => 3.1.24
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.1.24 => 2.1.24
    gatsby-plugin-sass: ^2.1.31 => 2.1.31
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-source-filesystem: ^2.1.56 => 2.1.56
    gatsby-source-graphql: ^2.1.35 => 2.1.35
    gatsby-source-shopify: ^3.0.52 => 3.0.52
    gatsby-source-youtube: ^1.0.1 => 1.0.1
    gatsby-transformer-yaml: ^2.2.27 => 2.2.27
  npmGlobalPackages:
    gatsby-cli: 2.10.2
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by vladar** [comment]
As far as I understand Google suggests using gtag now instead of analytics. Maybe `gatsby-plugin-google-gtag` will work for you instead? It has a section in docs on sending [custom events](https://www.gatsbyjs.org/packages/gatsby-plugin-google-gtag/?=gtag#custom-events).

**Comment by ZLevine** [comment]
> As far as I understand Google suggests using gtag now instead of analytics. Maybe `gatsby-plugin-google-gtag` will work for you instead? It has a section in docs on sending [custom events](https://www.gatsbyjs.org/packages/gatsby-plugin-google-gtag/?=gtag#custom-events).

Unfortunately, I don't have time to refactor all our Google Analytics/GTM code to use gtag instead. It's not like Google Analytics is being sunset anytime soon; most sites still use it.

Therefore, this isn't a good solution.

**Comment by ZLevine** [comment]
This issue is not resolved.

**Comment by noah-hornak** [comment]
Would also like to know how to accomplish this. Trying to send custom dimension on page view event for a specific page so I can A/B test.
