### ISSUE TITLE
Gatsby-Cli wont work. 

### ISSUE THREAD

**Issue by NotMoni** [gatsbyjs/gatsby#22614]
## Description

I installed gatsby by doing ```npm install -g gatsby-cli``` Then i did ```gatsby new gatsby-site``` according to the quickstart. But I got an error

### Steps to reproduce

```npm install -g gatsby-cli```
```gatsby new gatsby-site```

### Expected result

What should happen?

I should be able to quickstart the Gatsby, but it won't work.

### Actual result
![Screen Shot 2020-03-27 at 7 34 02 PM](https://user-images.githubusercontent.com/40552237/77808485-ec7d6180-7061-11ea-8456-8edf3d4fc54d.png)

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 13.0.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 3.8.1 - /usr/local/bin/python
  Browsers:
    Chrome: 81.0.4044.34
    Safari: 13.0.5
  npmGlobalPackages:
    gatsby-cli: 2.7.2

**Comment by NotMoni** [comment]
I got it to work after when i did ```npm install -g  gatsby-cli@2.7.2```

**Comment by connorlindsey** [comment]
Looks like this is working, so I'll close the issue.

**Comment by NotMoni** [comment]
No

**Comment by NotMoni** [comment]
When you do npm i gatsby-cli it doesnt work.

**Comment by NotMoni** [comment]
@connorlindsey
