### ISSUE TITLE
Webpack config to eliminate react duplication

### ISSUE THREAD

**Issue by 0x6e6562** [gatsbyjs/gatsby#2261]
This is just a heads up to help save other people time debugging.

On 1.9.45 I noticed the following issue trying to render the `auth0-lock` component:

```
Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

The cause of this issue appears to be having two different versions of react being packed up. In my example, I was using `auth0-lock` which pulls in `"^15.6.1 || ^16.0.0"`, but gatsby 1.9.45 loads `15.6.2`.

To work around this, I configured webpack in `gatsby-node.js` thusly:

```js
exports.modifyWebpackConfig = ({ config, stage }) => {
  return config.merge({
    resolve: {
      alias: {
        'react': __dirname + '/node_modules/gatsby/node_modules/react',
      }
    }
  })
};
```

**Comment by dangerdespain** [comment]
This fixed a yuuuge headache for me while adding redux-form to my project. Thanks @0x6e6562 !

**Comment by geraldyeo** [comment]
Thanks @0x6e6562 for this workaround!

**Comment by m-allanson** [comment]
In the upcoming Gatsby v2 React is moved to a `peerDependency`, so there should be less cases of multiple React versions.
