### ISSUE TITLE
How to recreate/update gatsby source nodes 

### ISSUE THREAD

**Issue by ryanto** [gatsbyjs/gatsby#22611]
I'm creating a couple source nodes with gatby's `sourceNodes` API. I noticed that in development mode all nodes are correctly created when the dev server is started, but as I work on my app the nodes become stale due to changes in the data they are reading.

I'm wondering if there's any API or examples I can see that will show me how to update (or re-create) these source nodes while the dev server is running.

Thanks!

**Comment by arthurjdam** [comment]
You can indeed! The API is here: [src/commands/develop.ts](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/develop.ts#L199)

The comment describes a wrong environment variable (fixes in #22633), but in short:
If you set `ENABLE_GATSBY_REFRESH_ENDPOINT=1`, you should be able to send a POST request to `/__refresh` on your development server. 

For example, using curl: `curl -X POST http://localhost:8000/__refresh`

**Comment by laurieontech** [comment]
Thanks so much for the question and for chiming in @arthurjdam!

This doc may provide additional context as well: https://www.gatsbyjs.org/docs/running-a-gatsby-preview-server/

**Comment by ryanto** [comment]
Thanks, is there an API to refresh the data without using curl? I'd love to wire something up inside of gatsby-node that can update source nodes as files on disk change.

**Comment by arthurjdam** [comment]
No problem!

No built-in method is exposed, but you could put it together pretty easily using something like [watch](https://www.npmjs.com/package/watch)
For example, to "scripts" in your package.json, add:
```
"develop-keep-fresh": "ENABLE_GATSBY_REFRESH_ENDPOINT=1 gatsby develop & watch \"curl -s -X POST http://localhost:8000/__refresh > /dev/null\"",
```

You'll likely want to add some de-bouncing and ignore anything outside of src/ (not excluding .cache would probably result in loop, I'd imagine). 
It will probably still would be pretty inefficient though, since refreshing is a relatively slow process.

**Comment by ryanto** [comment]
Gotcha, thanks. Just a quick question - how to plugins like gatsby-mdx (and similar) trigger a rebuild as files on disk change? Is there something linking the plugins source nodes to gatsby-source-filesystem nodes? I think my mental model on how gatsby knows to rebuild source nodes has some gaps.

Also - just wanted to say thanks again for taking the time to answer my questions. I really appreciate it :D

**Comment by ryanto** [comment]
Ok I think I figured it out, wanted to add it here incase anyone runs into this in the future.

https://www.gatsbyjs.org/docs/creating-a-source-plugin/#option-1-transformation-relationships

> An example of a transformation relationship is the gatsby-transformer-remark plugin, which transforms a parent File node’s markdown string into a MarkdownRemark node. The Remark transformer plugin adds its newly created child node as a child of the parent node using the action createParentChildLink. Transformation relationships are used when a new node is completely derived from a single parent node. E.g. the markdown node is derived from the parent File node and wouldn’t ever exist if the parent File node hadn’t been created.

> Because all children nodes are derived from their parent, when a parent node is deleted or changed, Gatsby deletes all of the child nodes (and their child nodes, and so on) with the expectation that they’ll be recreated again by transformer plugins. This is done to ensure there are no nodes left over that were derived from older versions of data but shouldn’t exist any longer.

The trick is to use createParentChildLink between your node and the node that represents the file on disk (which you can get from onCreateNode).

Thanks again!

**Comment by arryanggaputra** [comment]
@ryanto I have similar question with you, and figure out about `createParentChildLink` but have no clue, can I know how you implement it? Thanks
