### ISSUE TITLE
issue while starting new project "using latest nodejs "

### ISSUE THREAD

**Issue by kherwata** [gatsbyjs/gatsby#22622]
# Informative
### issue
Desktop@desktop-O-E-M:~$ sudo gatsby new my-default-starter https://github.com/gatsbyjs/gatsby-starter-default
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git
Cloning into 'my-default-starter'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 28 (delta 2), reused 14 (delta 2), pack-reused 0
Unpacking objects: 100% (28/28), done.
success Created starter directory layout
info Installing packages...
error Command was killed with SIGILL (Invalid machine instruction): npm install

  Error: Command was killed with SIGILL (Invalid machine instruction): npm install
  
  - error.js:56 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:56:11
  
  - index.js:114 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:114:26
  
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
  
### Solution

i had this issue but i solved it by uninstalling the latest nodejs and npm and deleting nodesource.list from etc/apt/source.list.d

then i installed nodejs LTS (version 12) recommanded

**Comment by connorlindsey** [comment]
It seems like this was resolved by updating node, so I'm  going to close this issue. If you continue to have this issue, feel free to reopen.
