### ISSUE TITLE
pageResources is undefined on build

### ISSUE THREAD

**Issue by danilobuerger** [gatsbyjs/gatsby#22621]
## Description

`pageResources` is undefined on build, works in develop.

Typings suggest that this is never undefined: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/index.d.ts#L68

### Steps to reproduce

Try to access `pageResources` in any page during build.

### Expected result

`pageResources !== undefined`

### Actual result

`pageResources === undefined`

### Environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Safari: 13.0.5
  npmPackages:
    gatsby: 2.20.4 => 2.20.4
    gatsby-image: 2.3.1 => 2.3.1
    gatsby-plugin-postcss: 2.2.1 => 2.2.1
    gatsby-plugin-react-helmet-async: 1.0.16 => 1.0.16
    gatsby-plugin-remove-generator: 1.0.4 => 1.0.4
    gatsby-plugin-sharp: 2.5.3 => 2.5.3
    gatsby-plugin-sitemap: 2.3.1 => 2.3.1
    gatsby-plugin-typescript: 2.3.1 => 2.3.1
    gatsby-remark-images: 3.2.1 => 3.2.1
    gatsby-source-filesystem: 2.2.2 => 2.2.2
    gatsby-transformer-remark: 2.7.1 => 2.7.1
    gatsby-transformer-sharp: 2.4.2 => 2.4.2
  npmGlobalPackages:
    gatsby-cli: 2.8.29
```

**Comment by jlkiri** [comment]
Works for me in `gatsby-starter-blog` in both development and production. 
What does your project look like?

![image](https://user-images.githubusercontent.com/38713361/77846796-81639480-71f3-11ea-96e1-e4912c9af24d.png)

**Comment by danilobuerger** [comment]
@jlkiri You only checked runtime.

Reproduction with `gatsby-starter-blog`:
```
diff --git a/src/pages/index.js b/src/pages/index.js
index 092d193..950cc0b 100644
--- a/src/pages/index.js
+++ b/src/pages/index.js
@@ -6,10 +6,10 @@ import Layout from "../components/layout"
 import SEO from "../components/seo"
 import { rhythm } from "../utils/typography"
 
-const BlogIndex = ({ data, location }) => {
+const BlogIndex = ({ data, location, pageResources }) => {
   const siteTitle = data.site.siteMetadata.title
   const posts = data.allMarkdownRemark.edges
-
+  console.log(pageResources.page.path)
   return (
     <Layout location={location} title={siteTitle}>
       <SEO title="All posts" />
```
Then run `gatsby build`. Output:
```
❯ yarn run gatsby build
yarn run v1.22.4
$ /Users/danilo/GIT/gatsby-starter-blog/node_modules/.bin/gatsby build
success open and validate gatsby-configs - 0.044s
success load plugins - 0.517s
warn The Google Analytics plugin requires a tracking ID. Did you mean to add it?
success onPreInit - 0.012s
success delete html and css files from previous builds - 0.016s
success initialize cache - 0.006s
success copy gatsby files - 0.049s
warn gatsby-plugin-feed was initialized in gatsby-config.js without a feeds
option.
This means that the plugin will use the internal RSS feed creation, which may
not match your use case.
success onPreBootstrap - 0.013s
success createSchemaCustomization - 0.076s
success source and transform nodes - 0.054s
success building schema - 0.313s
success createPages - 0.027s
success createPagesStatefully - 0.050s
success onPreExtractQueries - 0.001s
success update schema - 0.034s
success extract queries from components - 0.233s
success write out requires - 0.005s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.110s
success onPostBootstrap - 0.115s
⠀
info bootstrap finished - 3.516 s
⠀
success Building production JavaScript and CSS bundles - 6.196s
success Rewriting compilation hashes - 0.002s
failed Building static HTML for pages - 1.117s

 ERROR #95313 

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  10 |   const siteTitle = data.site.siteMetadata.title
  11 |   const posts = data.allMarkdownRemark.edges
> 12 |   console.log(pageResources.page.path)
     |                             ^
  13 |   return (
  14 |     <Layout location={location} title={siteTitle}>
  15 |       <SEO title="All posts" />


  WebpackError: TypeError: Cannot read property 'page' of undefined
  
  - index.js:12 BlogIndex
    src/pages/index.js:12:29
  

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vladar** [comment]
Thanks for opening this issue! The thing is this prop `pageResources` is an internal structure that shouldn't even show up in props. It leaked somehow, maybe through invalid spreading and then someone added types for it.

We should probably remove it in the next major. In the meantime, can you share how you are using it and why? Just to make sure we are on the same page here.

**Comment by danilobuerger** [comment]
@vladar I don't use it. But it's in the props and its documented in the typings, thats why I opened the issue.

**Comment by danilobuerger** [comment]
I would argue that this doesn't have to be removed in a major release only. If it leaked into the page props and was never intentionally there, it was never part of the api. It should rather be considered a bug that it was ever there and could just be fixed in a patch release.

In any case there should probably a warning somewhere that people don't use it (and/or that its deprecated).

**Comment by icetee** [comment]
I try to move `src` folder to `src/client/{components, images, pages}`. I set `pathPrefix: '/client'`, add gatsby-node.js `const assetsDirectory = 'client'` and run this command `gatsby develop --prefix-paths` and same error.

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v3 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

[reproduction]: https://gatsby.dev/reproduction

**Comment by paulkre** [comment]
My app relies on the `componentChunkName` attribute which is only present in `pageRessources.page`. Is there a different way to retrieve it?
