### ISSUE TITLE
Error when updating gatsby-plugin-sharp : unexpected token {

### ISSUE THREAD

**Issue by gregorylalle** [gatsbyjs/gatsby#22630]
Hi, I got an error after running a simple "npm audit fix". I think It's due to a new version of the plugin gatsby-plugin-sharp ? I tried to uninstall the package and reinstall it, I tried to downgrade the package to an older version, but nothing is working... I also tried to update all my packages, but still nothing is working.

All my site is broken due to this error and I can't find any solutions... Here is the error :

`Error: /Users/greg/Projects/gatsby-starter-prismic/node_modules/gatsby-plugin-sharp/safe-sharp.js:94
    } catch {
            ^
  SyntaxError: Unexpected token {`

If somebody could help me I would be very grateful. I'm trying to learn gatsby and I can't find any solutions. Thank you!

**Comment by arthurjdam** [comment]
Will need a bit more information to debug this. Could you run `gatsby info --clipboard` in your project directory and paste the output here

**Comment by gregorylalle** [comment]
That's fine I managed to solve the error. I just had to update my Node.js version, and it solved the error!
Thank's anyway!
