### ISSUE TITLE
gatsby-image throws "currentData is undefined" with Gatsby theme

### ISSUE THREAD

**Issue by robinmetral** [gatsbyjs/gatsby#22635]
###  Description

I'm trying to use `gatsby-image` in a Gatsby theme.

Essentially, theme users should be able to add an image in an assets directory, and it will be rendered on a page with gatsby-image.

I'm using `gatsby-source-filesystem` to source from the assets directory, `gatsby-plugin-sharp` and `gatsby-transformer-sharp` to process the image, and `gatsby-image` to render it.

`gatsby-image` throws the following error in development:

```
TypeError: currentData is undefined
```

_[(more context in the reproduction repo's README)](https://github.com/robinmetral/gatsby-theme-image-bug)_

### Steps to reproduce

Here's a [reproduction repo](https://github.com/robinmetral/gatsby-theme-image-bug).

Run it locally:
```
git clone https://github.com/robinmetral/gatsby-theme-image-bug.git && cd gatsby-theme-image-bug && yarn && yarn develop
```

### Expected result

The image should be rendered.

### Actual result

`currentData` is undefined and throws an error. The stack trace points to the `gatsby-image` package, `getCurrentSrcData` method. It seems like the image has been detected to be in cache (via the `inImageCache` method), but the actual source can't be found afterwards.

Note that the image is being fetched and processed correctly (you can query it in GraphiQL) - it's a render error.

The error is thrown in both dev and prod builds, including when deploying to Netlify (clean environment).

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /var/folders/39/ckp57kpn5td4dvrdqf8xv0qw0000gp/T/yarn--1585472500682-0.839597419841517/node
    Yarn: 1.22.0 - /var/folders/39/ckp57kpn5td4dvrdqf8xv0qw0000gp/T/yarn--1585472500682-0.839597419841517/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.0.5
```

**Comment by vladar** [comment]
Thank you for opening this, @robinmetral 

It works as expected if I change `src` to `fluid` on [this line](https://github.com/robinmetral/gatsby-theme-image-bug/blob/a13c73bbebf49063767ab5209f98af375d321853/theme/src/pages/index.js#L9):

```diff
- <Img src={data.image.childImageSharp.fluid} alt="" />
+ <Img fluid={data.image.childImageSharp.fluid} alt="" />
```

So it looks like this is a usage problem?

**Comment by robinmetral** [comment]
![facepalm](https://user-images.githubusercontent.com/35560568/78140106-c4a74880-7429-11ea-8f97-693c3b9ff92d.gif)

Thanks a lot @vladar!

Would it make sense to catch this error and print an error message to the console on `develop`, or is it just happening to me?

**Comment by laurieontech** [comment]
You're not the first person to come across this error! (I've done it more than a few times). 
I'm going to close this as solved. But I'll definitely note the potential for error improvement here!

**Comment by subtleaaron** [comment]
Hi there, I've come across the same issue when following this tutorial. I cannot seem to get the ErrroType is disappear. It is due to the childImageSharp.Fluid; function  https://www.youtube.com/watch?v=afCjUsXtAtE&t=1s
