### ISSUE TITLE
Images are Extremely Blurry

### ISSUE THREAD

**Issue by JimLynchCodes** [gatsbyjs/gatsby#22643]
Hi. I have a gatsby site, and the images are extremely blurry. I tried setting `qaulity: 100`, but it doesn't seem to change anything...

```
import React from 'react';
import { useStaticQuery, graphql } from 'gatsby';
import Img from 'gatsby-image';

/*
 * This component is built using `gatsby-image` to automatically serve optimized
 * images with lazy loading and reduced file sizes. The image is loaded using a
 * `useStaticQuery`, which allows us to load the image from directly within this
 * component, rather than having to pass the image data down from pages.
 *
 * For more information, see the docs:
 * - `gatsby-image`: https://gatsby.dev/gatsby-image
 * - `useStaticQuery`: https://www.gatsbyjs.org/docs/use-static-query/
 */

const Image = () => {
  const data = useStaticQuery(graphql`
    query {
      placeholderImage: file(relativePath: { eq: "ec-logo.png" }) {
        childImageSharp {
          fluid(maxWidth: 500, quality: 100) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
  `);

  return <Img fluid={data.placeholderImage.childImageSharp.fluid} />;
};

export default Image;
```

![Screen Shot 2020-03-29 at 11 34 44 AM](https://user-images.githubusercontent.com/5354163/77853272-535d6080-71b1-11ea-9bd5-5a0925674f87.png)

**Comment by JKHarley** [comment]
Hi @JimLynchCodes, it looks like it's stuck in its lazy loading state.
Add `GatsbyImageSharpFluid_noBase64` instead of just `GatsbyImageSharpFluid` and see if that helps? Let me know if it changes anything.

**Comment by JimLynchCodes** [comment]
Hey @JKHarley !

Thanks, but after changing it to `GatsbyImageSharpFluid_noBase64` the images don't render at all after building...

![Screen Shot 2020-03-29 at 3 10 15 PM](https://user-images.githubusercontent.com/5354163/77858136-8d3d5f80-71cf-11ea-938f-0a27b2705ac2.png)

**Comment by KyleAMathews** [comment]
You want to look at your network tab? It seems like the images aren't being loaded. So either problem with image processing or a problem with the deployment.

**Comment by JimLynchCodes** [comment]
Thanks @KyleAMathews and @JKHarley .

Yes, when I use `GatsbyImageSharpFluid` I get a LOT of errors after building. It looks fine when I run `gatsby develop`, but I can't see the images at all after running `gatsby build` and `gatsby serve`...

```
import React from 'react';
import { useStaticQuery, graphql } from 'gatsby';
import Img from 'gatsby-image';

const EcLogoImage = () => {
  const data = useStaticQuery(graphql`
    query {
      placeholderImage: file(relativePath: { eq: "ec-logo.png" }) {
        childImageSharp {
          fluid(maxWidth: 500) {
            ...GatsbyImageSharpFluid_noBase64
          }
        }
      }
    }
  `);

  return <Img fluid={data.placeholderImage.childImageSharp.fluid} />;
};

export default EcLogoImage;
```

![Screen Shot 2020-03-31 at 11 15 45 AM](https://user-images.githubusercontent.com/5354163/78043433-55eec000-7341-11ea-8c80-9f43012bab06.png)


Do I need to install something extra in order to use `GatsbyImageSharpFluid_noBase64`?

@KyleAMathews, do you think using `GatsbyImageSharpFluid_noBase64` is the correct thing to do here?

I also tried setting `quality: 90`, but it doesn't seem to change anything. Images don't show up...
```
fluid(maxWidth: 500, quality: 90) {
            ...GatsbyImageSharpFluid_noBase64
          }
```

When I use the original `` with `quality: 90` and run `gatsby build` and `gatsby serve` I still get blurry images and lots of errors though, not sure why as this is pretty much a fresh gatsby scaffold. 😢

![Screen Shot 2020-03-31 at 11 22 09 AM](https://user-images.githubusercontent.com/5354163/78044015-18d6fd80-7342-11ea-847b-d32b382743d3.png)

Really strange though because everything works fine when I do `gatsby develop`... does anyone know what's going on here and what I should change? 🤔

**Comment by JimLynchCodes** [comment]
After some help in this thread (https://spectrum.chat/gatsby-js/general/images-are-very-blurry-when-running-gatsby-build~8de44138-f260-47e7-951e-c7e470909751) I was able to get it working by adding `--prefix-paths` to my `gatsby serve` command (and using the correct prefix path). Thanks! ♥️

**Comment by dulajdilshan** [comment]
> After some help in this thread (https://spectrum.chat/gatsby-js/general/images-are-very-blurry-when-running-gatsby-build~8de44138-f260-47e7-951e-c7e470909751) I was able to get it working by adding `--prefix-paths` to my `gatsby serve` command (and using the correct prefix path). Thanks! hearts

This didn't work for me
