### ISSUE TITLE
Cannot read property 'node' of undefined - on build ( gatsby-source-prismic-graphql)

### ISSUE THREAD

**Issue by nikita-seliverstov** [gatsbyjs/gatsby#22656]
Hi I get this error on build:
TypeError: Cannot read property 'node' of undefined
`const itSupportServicePlans = data.prismic.allServicess.edges[0].node.service_plan;`
But there is no empty fields returning in gragphQl
![image](https://user-images.githubusercontent.com/37171096/77903546-b7ecee00-728b-11ea-874a-90696843be68.png)

Query: 
` query Services($lang: String, $uid: String ) {
    prismic {
        allServicess(lang: $lang, uid: $uid ) {
        edges {
          node {
            _meta {
              uid
              lang
            }
            pros {
              pros_heading
              pros_description
            }
            description
            heading
            choose_your_plan
            title
            service_plan {
            ... on PRISMIC_It_support_service_plan {
              guaranteed_prompt_response_header
              guaranteed_confidentiality_header
              financial_guarantee_of_confidentiality_header
              hourly_payment_header
              minimum_time_for_performing_work_in_remote_mode_header
              minimum_time_for_performing_work_on_site_header
              it_support_service_plan {
                financial_guarantee_of_confidentiality
                guaranteed_confidentiality
                guaranteed_prompt_response
                hourly_payment
                it_support_button
                it_support_monthly_price
                it_support_subtitle
                it_support_title
                minimum_time_for_performing_work_in_remote_mode
                minimum_time_for_performing_work_on_site
              }
            }
          }
          }
        }
      }
    }
    
  }`

### Environment
 System:
    OS: Windows 10 10.0.17134
    CPU: (4) x64 Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.13
  Browsers:
    Edge: 42.17134.1098.0
  npmPackages:
    gatsby: ^2.20.8 => 2.20.8
    gatsby-image: ^2.3.1 => 2.3.1
    gatsby-node-helpers: ^0.3.0 => 0.3.0
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3
    gatsby-plugin-offline: ^3.1.2 => 3.1.2
    gatsby-plugin-optimize-svgs: ^1.0.4 => 1.0.4
    gatsby-plugin-prismic-preview: ^2.0.0 => 2.0.0
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1
    gatsby-plugin-sharp: ^2.5.3 => 2.5.3
    gatsby-plugin-sitemap: ^2.3.1 => 2.3.1
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-source-prismic-graphql: ^3.5.0 => 3.5.0
    gatsby-transformer-remark: ^2.7.1 => 2.7.1
    gatsby-transformer-sharp: ^2.4.3 => 2.4.3

**Comment by madalynrose** [comment]
Thank you for opening this issue @nikita-seliverstov! I was about to recommend that you open an issue in the [repo for this plugin](https://github.com/birkir/gatsby-source-prismic-graphql) and am happy to see that you've already done so [here](https://github.com/birkir/gatsby-source-prismic-graphql/issues/174). I'm going to close this issue but feel free to reopen if you discover that this is indeed a bug within Gatsby and not within the plugin.
