### ISSUE TITLE
new pages dont update: Tutorial can't be followed

### ISSUE THREAD

**Issue by MattAppleton** [gatsbyjs/gatsby#22655]
## Description

I am new to Gatsby (ie. today is my first dive). Following the Gatsby tutorials here https://www.gatsbyjs.org/tutorial/ I find I have to restart Gatsby develop to view new pages.

### Steps to reproduce

1. Follow the Gatsby tutorials on a new machine with a new Gatsby setup

2. Add a new page (ie src/pages/about.js)

3. Check the develop browser window, and go to the new page

all new pages use this initial structure:

`import React from "react"
export default () => (`

4. We see a 404 page with "There's not a page yet at /test/"

5. Stop, then restart the Gatsby develop processs

6. Now it works!

(I have installed nvm, and tried toggling from latest node (13.12.0) back to LTS node (12.16.1), no difference)

### Expected result

We shouldn't have to restart Gatsby develop according to your tutorial.

### Actual result

See above - -pages don't load.

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 73.0.1
    Safari: 13.1

**Comment by MattAppleton** [comment]
Other than this bug, so far I am enjoying the tutorial, thanks :)

**Comment by herecydev** [comment]
Glad you're enjoying it so far @MattAppleton. I do agree there is a problem when the 404 page says: "and this page will automatically refresh to show the new page component you created."

As it doesn't automatically refresh, however you shouldn't need to restart gatsby to see the page now. You can refresh the browser and it should appear.

With that said, I think there is a problem; either with the wording or the HMR functionality.

**Comment by MattAppleton** [comment]
@herecydev — I have just been checking my tutorial files again and I can confirm that refreshing the browser does NOT work. This has been test in Safari + Chrome, including hard refresh in Chrome.

I just added a newpage.js, and Gatsby tells me "There's not a page yet at /newpage/"

— until I stop / start Gatsby develop.

**Comment by herecydev** [comment]
That's weird, let me capture some steps. Definitely works in the order that I was doing things

**Comment by vladar** [comment]
Hi @MattAppleton !

Sorry to hear you're running into an issue. I tried to reproduce this but couldn't - pages are created normally, I don't need to restart develop to see the page.

To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by MattAppleton** [comment]
OK, I should have some time later, will update asap...

**Comment by marcysutton** [comment]
Curious to hear more, if you've got a reproduction that would be awesome!

**Comment by MattAppleton** [comment]
Hi there. Apologies for the delay, finally had a moment to revisit Gatsby.

Tutorial stage three folder form before still gives me the same new page error. I have added it to GitHub [here](https://github.com/MattAppleton/GATSBY-newpage-error)

**Comment by MattAppleton** [comment]
And if you would like the entire folder, node modules and all, it can be download [here... ](https://www.dropbox.com/s/q5d3kg3zihgep6r/tutorial-part-three.zip?dl=0)

thanks!

**Comment by MattAppleton** [comment]
Netlify deploy here: https://sleepy-perlman-896c11.netlify.app

**Comment by vladar** [comment]
I tried your repo and couldn't reproduce it. Created several new pages with `gatsby develop` and it worked without a restart.

I think it may have something to do with your local machine. Gatsby relies on chokidar listeners to catch new pages. Maybe it doesn't work on your machine for some reason.

To confirm, run `gatsby develop`. When it's ready the last lines in console should be something like:

```
To create a production build, use gatsby build
⠀
success Building development bundle - 4.583s
```

Now create a new page (and don't do anything else). It should now display something like this:
```
To create a production build, use gatsby build
⠀
success Building development bundle - 4.583s
success run queries - 0.043s - 2/2 46.57/s
success write out requires - 0.018s
success Re-building development bundle - 0.551s
success extract queries from components - 0.023s
success Re-building development bundle - 0.346s
```

If you don't have those lines - then it's something related to file system watching. Try changing directory and a text editor (some of them do tricky things with new files, e.g. creating them in a temporary location and then moving).

If you do see those lines, then try running following GraphQL query in GraphiQL (http://localhost:8000/___graphql):

```graphql
{
  allSitePage {
    nodes {
      path
    }
  }
}
```

And check if the result contains your newly created page.

**Comment by MattAppleton** [comment]
Thanks for looking @vladar ... you are right, it does seem to be a file watching issue. Up till now my development folder has been on a Dropbox shared folder (still local though, on an SSD external drive). I am using VS Code throughout these tests.

As soon as I try a basic Gatsby install on my **system drive** it behaves properly, ie it 'hot loads' new pages.

So — something to do with Dropbox file system perhaps? 
Or even the SSD?

Basic system info is

`  System:
    OS: macOS 10.15.4
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 75.0
    Safari: 13.1`

I'll test further.

**Comment by MattAppleton** [comment]
Doesn't seem directly related to being inside a Dropbox shared folder. As soon as I run the test repo in the root the usual dev drive (external Crucial SSD) I encounter the same 'new page' issue ie the new page doesn't trigger 

`success Re-building development bundle - 0.035s`

If I try the same thing on the internal drive it works fine.

**Comment by MattAppleton** [comment]
A bit more info.

On my external SSD drive, I can get the minimal reproduction files to work correctly  — UNLESS — the Gatsby folder is sited inside the Dropbox-linked folder.

It seems like the issue may well be related to Dropbox.

**Comment by wardpeet** [comment]
Thanks so much for opening this issue! As stated, this is slightly tangential to Gatsby, and it seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪
