### ISSUE TITLE
Can A Built Gatsby.js Site Be Hosted On Ubuntu Expressjs Server?

### ISSUE THREAD

**Issue by doverradio** [gatsbyjs/gatsby#22664]
Please consider the following circumstance: I have just finished my first gatsby.js build for "production" but want to self host on my Linux (Ubuntu 16.04 to be exact).

Can this be done without the listed service companies listed in the [docs?](https://www.gatsbyjs.org/docs/deploying-and-hosting/)

I stumbled into [gatsby-plugin-express](https://www.gatsbyjs.org/packages/gatsby-plugin-express/) and was unable to get it to work with my first Gatsy.js build.

The steps I took with `gatsby-plugin-express` [per this post](https://github.com/wille/gatsby-plugin-express/issues/4) were as follows:

1. Install the plugin. `npm i gatsby-plugin-express`
2. Set up the `const gatsbyExpress = require('gatsby-plugin-express');` in my existing app.js file (in preexisting Express.js server)
3. Created the configuration file.
 ```
mkdir config
touch config/gatsby-express.json
```
4. Added the plugin to gatsby-config.js, like so:

```
plugins: [
  {
    resolve: 'gatsby-plugin-express',
    options: {
      output: 'config/gatsby-express.json',
    }
  }
]
```
Then I updated my existing app.js file with the following:

```
const app = express();

// serve static files before gatsbyExpress
app.use(express.static('public/'));
app.use(gatsbyExpress('config/gatsby-express.json', {
  publicDir: 'public/',
  template: 'public/404/index.html',

  // redirects all /path/ to /path
  // should be used with gatsby-plugin-remove-trailing-slashes
  redirectSlashes: true,
}));

app.listen(9000, function() {
  console.log('App started on port 9000');
});
```
I tried running my app.js file but get a 404 error when I try to access the site at http://myhost:9000. Despite this, it's not displaying my production build gatsby.js site.

Can you please point me in the right direction as to how to do it?

**Comment by herecydev** [comment]
Gatsby is very versatile in what can host it, for example I use Azure (which is not listed there) and that works just fine. I'm certain that express will work just fine.

Would you be able to create a repo, I'm more than happy to help you out.

**Comment by doverradio** [comment]
Hello @herecydev, thank you so much.  I created this: https://github.com/doverradio/gatsby-express

I will try to add there a basic express server. Please, if possible, show what I must do.

**Comment by herecydev** [comment]
Okay, if you commit what you've done to that repo I can take a look and see what's not working.

**Comment by doverradio** [comment]
@herecydev  Ok please see again https://github.com/doverradio/gatsby-express, I have uploaded a basic express server.  So, my question is if you serve static assets from the `/public` folder and a built gatsby.js site is intended to be served as static assets, how would you put the built gatsby site on this express server?

**Comment by LekoArts** [comment]
Thank you for opening this!

As this isn't related to Gatsby directly you should ask on other communities (shown below). Also refer to internet tutorials/documentation on how to set up a webserver and/or node server (like express) on a Ubuntu machine. To answer your question: Yes, Gatsby can of course be hosted on that.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
