### ISSUE TITLE
Properly detecting homepage URL when using a path prefix

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#2266]
I started to use a `pathPrefix` in my `gatsby-config.js` as soon as a website had to be deployed automatically to GitHub Pages via Travis CI.

As soon as the website got published, I realized that my `const isHomepage = location.pathname === '/'` statement inside the `IndexLayout` didn't work in production anymore. I would like to ask about adding an official way of getting around this issue to the docs (e.g. detecting debug/production mode using an environment variable).

**Comment by thisiscam** [comment]
#2254 

I just happen to run across this yesterday :)

**Comment by kripod** [comment]
Sorry for the duplicate, unfortunately, I didn’t notice your issue. I’m closing this one for housekeeping.
