### ISSUE TITLE
Categories and tags are are the same?

### ISSUE THREAD

**Issue by olegKusov** [gatsbyjs/gatsby#22665]
I set up tags with gatsby docs, but where I can find info about categories set up? Can I set up them same as tags?

**Comment by LekoArts** [comment]
Thank you for opening this!

Yes, you can set up them the same. It's the same concept.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
