### ISSUE TITLE
404 Page handled differently by some static site

### ISSUE THREAD

**Issue by thisiscam** [gatsbyjs/gatsby#2267]
I noticed that when I access http://gatsbyjs.github.io/gatsby-starter-blog/none, I can see the layout component is wrapped around the 404 page.

How can we augment gatsby's core to achieve the above effect?  Specifically, seems like if we are hosting on something like surge or a simple apache server, the server will server 404.html directly, instead of going through gatsby's routing?

**Comment by m-allanson** [comment]
For surge [it looks like](https://surge.sh/help/adding-a-custom-404-not-found-page) you need to create your own 404.html page. Gatsby should handle this if you create a page at `/404`

>create a page whose path matches the regex `/404*`. Most often you’ll just want to create a React component page at `src/pages/404.js`.

There's a bit more info on the Gatsby docs: https://www.gatsbyjs.org/docs/add-404-page/

**Comment by thisiscam** [comment]
The question I have is that I don't really understand the behavior of  404.js.

If I have 404.js, it will be compiled into 404.html happily. Yet when I hit a non existing page, the layout component disappears and JS is not loaded correctly. 

I can still access mysite/404 directly, and the result page will be wrapped in layout component again..

Am I missing something here? What is the intended behavior of that standalone 404.html?

Lastly, this could be related: if I goto mysite/index.html , the server will serve only that html file for some reason I'm not able to understand.. maybe its just how it works, but generally I would expect "mysite.com/index.html" and "mysite.com/"  to be functioning similarly?

**Comment by KyleAMathews** [comment]
Closing this issue as it's fairly old and we have far too many open issues! If you have additional problems in this area, please open a new issue!
