### ISSUE TITLE
Missing type WPGraphQL

### ISSUE THREAD

**Issue by WilliamCSA04** [gatsbyjs/gatsby#22685]
## Summary

Hello, I hope someone can help me with something. I'm having a strange behavior while using gatsby-source-graphql, the field itself is kinda missing.
I say "kinda" because if you look after you build the project, you can see him there.
This is the plugin configuration:
```
{
  resolve: 'gatsby-source-graphql',
  options: {
    typeName: 'WPGraphQL',
    fieldName: 'wpgraphql',
    url: `${process.env.WORDPRESS_URL}/graphql`,
  },
},
```
When I look up on `http://localhost:8000/___graphql` you can see that WPGraphQL is there: 
![wp](https://user-images.githubusercontent.com/12972870/78025662-c8a36f80-7330-11ea-8c2b-dd75e6a88e41.JPG)

However, during build time, it is impossible to get it. I'm creating a search, that worked before when we used the Wordpress plugin instead with gatsby-plugin-elasticlunr-search, I could access things like wordpress__PAGE, but I cannot do the same with WPGraphQL. Using some logs, I have found a weird configuration on GraphQLSource type that is `ignoreType: true`, I tried to change it to see if this is the problem but I could not find a way to do it. That is the print of GraphQLSource:
```
{
  id: '1b63645c-6c74-524d-9692-fe90f16fad60',
  typeName: 'WPGraphQL',
  fieldName: 'wpgraphql',
  parent: null,
  children: [],
  internal: {
    type: 'GraphQLSource',
    contentDigest: 'e6729cd805dacd83ad5027f471f01849',
    ignoreType: true,
    counter: 64,
    owner: 'gatsby-source-graphql'
  }
}
```
Thanks a lot, if anyone have an idea how to solve it, I wil appreciate it.

**Comment by vladar** [comment]
Hi @WilliamCSA04 !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by WilliamCSA04** [comment]
Hello, sorry for taking so long to respond. I had problems trying to reproduce the error because for some reason I could not make work [gatsby-source-graphql](https://www.gatsbyjs.org/packages/gatsby-source-graphql/#how-to-use) sample code, so I decided to change my search plugin, which in the end, was way better, the new plugin called [gatsby-plugin-local-search](https://www.gatsbyjs.org/packages/gatsby-plugin-local-search/?=search#gatsby-plugin-local-search) worked way better than the one I was using before. So, if anyone finds this issue, I highly recommend use this [gatsby-plugin-local-search](https://www.gatsbyjs.org/packages/gatsby-plugin-local-search/?=search#gatsby-plugin-local-search) with [gatsby-source-graphql](https://www.gatsbyjs.org/packages/gatsby-source-graphql/)
