### ISSUE TITLE
Gatsby as a "Static API Generator"

### ISSUE THREAD

**Issue by david-nossebro** [gatsbyjs/gatsby#22682]
I would love to be able to use the Gatsby infrastructure to generate static APIs. 

Instead of rendering html using React, a new type could be used to create an API response (header + body). 

This would be useful:

- If you have 2 sites that needs to communicate at runtime.
- If you have a site where you have a dataset that needs to be rebuilt often to be up to date, and you do not want to rebuild the entire site just for a small part.
- If you have multiple sites that share the same data.

I know this can be achieved in a somewhat hacky way by creating json-files (or whatever format you like) and save them in the public folder during the build process. It would be nice with a more official solution with the possibility to add headers as well.

What do you think? :smiley:

**Comment by freiksenet** [comment]
Hello David!

This would require quite a lot of changes to Gatsby to work. I don't think we would be working on this in near future. I think your best bet right now is generating it in postBuild - after all you have access to GraphQL there. It should also be possible to extract it to plugin that is similar to gatsby-plugin-sitemap. It's also possible to generate headers there that will be picked up by your current static hosting, like how gatsby-plugin-netlify generates redirects.

Thank you for using Gatsby!
