### ISSUE TITLE
Mdx with Typescript import same file name cause endless loop

### ISSUE THREAD

**Issue by shaodahong** [gatsbyjs/gatsby#22681]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

1. In my project, have three files
```bash
- index.mdx
- index.tsx
- button.tsx
```

*index.mdx*
```tsx
# Hello world

import ButtonDemo from "./button.tsx"

<ButtonDemo />
```

*index.tsx*
```tsx
import React from "react"

export default function Demo({ children }) {
  return <button>{children}</button>
}
```

*button.tsx*
```tsx
import React from "react"

import Button from "./index"

export default function ButtonDemo() {
  return <Button>CLick</Button>
}

```

Like in `button.tsx` import from `./index` extension is '.mdx'

Github repositiry: https://github.com/shaodahong/gatsby-bug-report

### Expected result

What should happen?

render normal

### Actual result

What happened.

endless lopp

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```bash
❯ npx gatsby info --clipboard                      

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 72.0.2
    Safari: 13.1
  npmPackages:
    gatsby: ^2.19.45 => 2.20.9
    gatsby-image: ^2.2.44 => 2.3.1
    gatsby-plugin-manifest: ^2.2.48 => 2.3.3
    gatsby-plugin-mdx: ^1.1.4 => 1.1.4
    gatsby-plugin-offline: ^3.0.41 => 3.1.2
    gatsby-plugin-react-helmet: ^3.1.24 => 3.2.1
    gatsby-plugin-sharp: ^2.4.13 => 2.5.3
    gatsby-plugin-typescript: ^2.3.1 => 2.3.1
    gatsby-source-filesystem: ^2.1.56 => 2.2.2
    gatsby-transformer-sharp: ^2.3.19 => 2.4.3
```

**Comment by shaodahong** [comment]
But in `button.tsx` if import with extension `.tsx` will be fine, but can find `An import path cannot end with a '.tsx' extension. Consider importing '../index' instead.ts(2691)
`

**Comment by LekoArts** [comment]
Thank you for opening this!

Every JS/JSX/TSX file inside `src/pages` gets turned into a page. With `gatsby-plugin-mdx` and your `gatsby-source-filesystem` configuration also every `.mdx` file inside `src/pages` gets turned into a page. So `index.tsx` and `index.mdx` are clashing. Also you're relying on Webpack to resolve the file ending which doesn't correctly work if you have two files with the same name.

You should move your components to the folder `src/components` and not into `src/pages`. So it's a wrong use on your end. Hope that clears things up!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
