### ISSUE TITLE
react-refresh is not hoisted when using gatsby in monorepo

### ISSUE THREAD

**Issue by adrienharnay** [gatsbyjs/gatsby#22684]
## Description

When using gatsby in a monorepo (yarn workspaces), react-refresh is not hoisted and therefore there's an error:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '@pmmmwh/react-refresh-webpack-plugin/src/overlay' in '/fakepath/packages/service/.cache'

File: .cache/error-overlay-handler.js
```

The only thing that "fixes" it is to specifically install `@pmmmwh/react-refresh-webpack-plugin`, because else it is in `node_modules/gatsby/node_modules/` and cannot be accessed.

### Steps to reproduce

1. Create a monorepo with yarn workspaces
2. Install gatsby in one of the monorepo packages, and start it

### Expected result

https://github.com/gatsbyjs/gatsby/pull/21534#issuecomment-606565937

### Actual result

Error

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /var/folders/mt/71kkzssd3fq24s3x3y6wpc4h0000gn/T/yarn--1585653908181-0.6528599744136716/node
    Yarn: 1.22.4 - /var/folders/mt/71kkzssd3fq24s3x3y6wpc4h0000gn/T/yarn--1585653908181-0.6528599744136716/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 72.0.2
    Safari: 13.0.5
```

**Comment by pieh** [comment]
Note to why this can happen:
We copy `gatsby/cache-dir` ( Gatsby runtime:  http://unpkg.com/browse/gatsby/cache-dir/ ) to project's `.cache` directory, so any modules/packages we import in runtime need to be accessible from project node_modules otherwise those can't be resolved.

We can do hotfix and add webpack alias so `@pmmmwh/react-refresh-webpack-plugin` resolve to location that `gatsby` package know about - we already do so for `@babel/runtime` and `core-js` ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L388-L391 ), so just adding new entry for `@pmmmwh/react-refresh-webpack-plugin` should fix it.

Longer term we should restructure how Gatsby runtime get's built (we should not copy to project directory?)

**Comment by pieh** [comment]
Can you try installing `gatsby@i22684` and see if that fixes the issue?

**Comment by pieh** [comment]
(above canary release contain this change - https://github.com/gatsbyjs/gatsby/compare/react-refresh-webpack-alias )

**Comment by adrienharnay** [comment]
Hey @pieh, running gatsby develop gives this output:

```
{
  updatedCacheKeys: {
    dbType: 'redux',
    experimentalSelectiveHtmlBuilds: false,
    coreVersion: '2.20.10-i22684.18+1507557b91'
  },
  changedCacheKeys: [],
  pluginVersions: {
    'dev-404-page': '1.0.0',
    'load-babel-config': '1.0.0',
    'internal-data-bridge': '1.0.0',
    'prod-404': '1.0.0',
    'webpack-theme-component-shadowing': '1.0.0',
    'gatsby-plugin-typescript': '2.3.1',
    'gatsby-plugin-sass': '2.2.1',
    'gatsby-plugin-postcss': '2.2.1',
    'gatsby-plugin-react-helmet': '3.2.1',
    'gatsby-plugin-sitemap': '2.3.1',
    'gatsby-plugin-robots-txt': '1.5.0',
    'gatsby-plugin-manifest': '2.3.3',
    'gatsby-plugin-s3': '0.3.3',
    'gatsby-source-graphql': '2.3.0',
    'gatsby-plugin-page-creator': '2.2.1',
    'default-site-plugin': 'a1fc2684eea54faecc073cf24ede2524'
  },
  changedPlugins: [
    'dev-404-page',
    'load-babel-config',
    'internal-data-bridge',
    'prod-404',
    'webpack-theme-component-shadowing',
    'gatsby-plugin-typescript',
    'gatsby-plugin-sass',
    'gatsby-plugin-postcss',
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sitemap',
    'gatsby-plugin-robots-txt',
    'gatsby-plugin-manifest',
    'gatsby-plugin-s3',
    'gatsby-source-graphql',
    'gatsby-plugin-page-creator',
    'default-site-plugin'
  ]
}
⠋ initialize cache
✨  Done in 2.35s.
```

But doesn't build my project. Not sure if this is to be expected?

**Comment by pieh** [comment]
Oh, sorry! That was botched canary release - this wasn't what I wanted to publish :S will do another publish shortly

**Comment by adrienharnay** [comment]
Alright no worries! Since the gatsby upgrade, rebuilds take 6 seconds instead of a few hundred ms before... Which makes the fast refresh kind of useless 😅 I guess it was tested on large projets before being merged into Gatsby?

**Comment by pieh** [comment]
I pushed new version to `gatsby@i22684` npm dist tag, so if you could try installing again and checking if that fixes the issue would be great. I'm not exactly able to reproduce this locally. It seems like wether the problematic package is hoisted or not depends on your monorepo (and dependencies of it).

As for rebuilds taking longer, we didn't see that, but also we don't actually use `fast-refresh` by default yet (you do need to use `GATSBY_HOT_LOADER=fast-refresh` env var to enable it - this will likely be default in gatsby v3, but we can't switch in v2). So if rebuilds are taking longer, it's something to look into, but I'm not exactly sure if it's fast-refresh that cause it - we might need reproduction site at this point to research it

**Comment by Js-Brecht** [comment]
This is the same issue encountered in #22250.  The solution use here should fix that one as well.
