### ISSUE TITLE
Starter Pages do not appear to be loading correctly

### ISSUE THREAD

**Issue by boborchard** [gatsbyjs/gatsby#22695]
## Description

When visiting the starters on https://gatsbyjs.org, it appears that some of them are not loading correctly in a Brave browser

### Steps to reproduce

- Open a browser window and visit the starters page https://www.gatsbyjs.org/starters
- Randomly select a starter and open the starter's page
- Sometimes you'll need to do a hard refresh to get it to load, but on some browsers that doesn't show the correct layout (like on Brave).
- It does not appear to matter which starter you look at, but it does seem to be random. A few I've experienced this issue on are https://www.gatsbyjs.org/starters/seabeams/gatsby-starter-auth-aws-amplify/ and https://www.gatsbyjs.org/starters/service-relief/gatsby-starter-service-relief/

I've observed this on Chrome and Brave (as well as in incognito/private for each) so far.

### Expected result

The page should load entirely, showing the header and correct page styles.

![image](https://user-images.githubusercontent.com/1667106/78063527-fcdd5700-7355-11ea-9f45-f12d395c4c51.png)

### Actual result

The page flashed, showing the header and styles initially, but then showed the main body of the page without a header/footer. 

Recording: https://share.getcloudapp.com/GGuNgobJ

Screenshot:
![image](https://user-images.githubusercontent.com/1667106/78063409-ca335e80-7355-11ea-90de-ae38e2fc3ce6.png)

**Comment by smkamranqadri** [comment]
Not able to reproduce.
<img width="1678" alt="Screenshot 2020-04-01 at 10 21 40 AM" src="https://user-images.githubusercontent.com/13115396/78102015-a843e580-7402-11ea-8253-fabd0090799f.png">

**Comment by laneparton** [comment]
Are you able to reproduce the issue without an ad blocker on Chrome (such as an incognito window)? Does your ad blocker say anything interesting in its log of loading the page?

**Comment by smkamranqadri** [comment]
I checked on brave, not.chrome.

**Comment by boborchard** [comment]
@laneparton I checked in Incognito without any extensions in Chrome and Brave when I encountered this.

**Comment by AhsanAyaz** [comment]
What chrome version do you have at the moment @boborchard .
I'm not able to reproduce this as well :(

**Comment by boborchard** [comment]
I'm currently using v80.0.3987.149

**Comment by smkamranqadri** [comment]
@boborchard I am using the same version of Chrome, here is the video.

https://recordit.co/bpGvkpGNyE
