### ISSUE TITLE
gatsby-node try catch hides errors in modifyWebpackConfig 

### ISSUE THREAD

**Issue by BerkeleyTrue** [gatsbyjs/gatsby#227]
If an require fails in this try/catch [lib/utils/webpack.config.js](https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/webpack.config.js#L8) for a reason other than the file is non-existent, the try/catch will swallow the error without information the user of the error.

**Comment by KyleAMathews** [comment]
Oh good catch. Could you create a PR to fix it?

**Comment by KyleAMathews** [comment]
@BerkeleyTrue tell me if my fix looks right.

**Comment by BerkeleyTrue** [comment]
LGTM
