### ISSUE TITLE
Tutorial part 4 - cannot read site of undefined

### ISSUE THREAD

**Issue by barbush** [gatsbyjs/gatsby#2270]
After following steps from "Now let’s start querying" to "It worked!!" - it didn't work :/

https://imgur.com/a/B1Lqw 

I get the fail and die error with a red bg as pasted below:

TypeError: Cannot read property 'site' of undefined
new
webpack:///src/layouts/index.js:19
http://localhost:8000/commons.js:39277:25
instantiate
webpack:///~/react-proxy/modules/createClassProxy.js:103
_default (http://localhost:8000/commons.js:39292:23),
http://localhost:8000/commons.js:27122:17
measureLifeCyclePerf
webpack:///~/react-dom/lib/ReactCompositeComponent.js:73
ReactCompositeComponentWrapper._constructComponentWithoutOwner
webpack:///~/react-dom/lib/ReactCompositeComponent.js:302
ReactCompositeComponentWrapper._constructComponent
webpack:///~/react-dom/lib/ReactCompositeComponent.js:277
ReactCompositeComponentWrapper.mountComponent
webpack:///~/react-dom/lib/ReactCompositeComponent.js:185
Object.mountComponent
webpack:///~/react-dom/lib/ReactReconciler.js:43

**Comment by barbush** [comment]
Tutorial errors always make me really nervous about using new tech. Hopefully this isn't a problem I made myself, however I followed the tutorial to the letter.

**Comment by KyleAMathews** [comment]
Hey! Thanks for reporting this issue! Sorry you ran into trouble with the tutorial.

Could you try modifying your render function in the layout component to look like:

```jsx
export default ({ children, data }) => {
  console.log(data)
  return (
  <g.Div
    margin={`0 auto`}
    maxWidth={700}
    padding={rhythm(2)}
    paddingTop={rhythm(1.5)}
  >
    <Link to={`/`}>
      <g.H3 marginBottom={rhythm(2)} display={`inline-block`}>
        {data.site.siteMetadata.title}
      </g.H3>
    </Link>
    <Link className={linkStyle} to={`/about/`}>
      About
    </Link>
    {children()}
  </g.Div>
)
```

**Comment by KyleAMathews** [comment]
Then look in your console to see what's logged out.

If that doesn't work, try restarting your development server.

**Comment by barbush** [comment]
Thanks @KyleAMathews 

I couldn't get that working. Here are the results below.

Also screenshot of console: https://imgur.com/a/L9Jf9

Result of 'gatsby develop':
C:\Users\barne\Documents\GitHub\tutorial-part-four>gatsby develop
success delete html files from previous builds — 0.011 s
success open and validate gatsby-config.js — 0.006 s
success copy gatsby files — 0.054 s
success onPreBootstrap — 0.009 s
success source and transform nodes — 0.017 s
success building schema — 0.109 s
success createLayouts — 0.036 s
success createPages — 0.012 s
success createPagesStatefully — 0.014 s
GraphQL Error Unknown field `siteMetadata` on type `Site`

  file: C:/Users/barne/Documents/GitHub/tutorial-part-four/src/pages/about.js

  1 |
  2 |   query AboutQuery {
  3 |     site {
> 4 |       siteMetadata {
    |       ^
  5 |         title
  6 |       }
  7 |     }
  8 |   }
  9 |

success extract queries from components — 0.091 s
success run graphql queries — 0.007 s
success write out page data — 0.011 s
success write out redirect data — 0.001 s
success update schema — 0.056 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 3.153 s

 ERROR  Failed to compile with 1 errors                                                                      10:25:42 AM

 error  in ./src/layouts/index.js

Syntax Error: Unexpected token (29:3)

  27 |       {children()}
  28 |     </g.Div>
> 29 |   )
     |    ^



 @ ./.cache/layouts/index.js 13:13-95

 WAIT  Compiling...                                                                                          10:25:42 AM

 ERROR  Failed to compile with 1 errors                                                                      10:25:43 AM

 error  in ./src/layouts/index.js

Syntax Error: Unexpected token (29:3)

  27 |       {children()}
  28 |     </g.Div>
> 29 |   )
     |    ^



 @ ./.cache/layouts/index.js 13:13-95

**Comment by barbush** [comment]
Apologies - this is the console error : https://imgur.com/OAHC7Cl

**Comment by KyleAMathews** [comment]
Looks like there's a JS error now in your component.

Would you mind just starting over? It does look like something went wrong while you were copying files over. If the same error happens again, I'll check it out later to see if a bug has popped up in Gatsby recently.

**Comment by barbush** [comment]
Ran through again, definitely broken sadly, with this issue: https://imgur.com/a/B1Lqw 

C:\Users\barne\Documents\GitHub\tutorial-part-four2>gatsby develop
success delete html files from previous builds — 0.010 s
success open and validate gatsby-config.js — 0.006 s
success copy gatsby files — 0.059 s
success onPreBootstrap — 0.009 s
success source and transform nodes — 0.018 s
success building schema — 0.123 s
success createLayouts — 0.042 s
success createPages — 0.013 s
success createPagesStatefully — 0.013 s
GraphQL Error Unknown field `siteMetadata` on type `Site`

  file: C:/Users/barne/Documents/GitHub/tutorial-part-four2/src/layouts/index.js

  1 |
  2 |   query LayoutQuery {
  3 |     site {
> 4 |       siteMetadata {
    |       ^
  5 |         title
  6 |       }
  7 |     }
  8 |   }
  9 |

success extract queries from components — 0.105 s
success run graphql queries — 0.007 s
success write out page data — 0.012 s
success write out redirect data — 0.001 s
success update schema — 0.049 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 3.231 s

**Comment by barbush** [comment]
To confirm, the error is happening from the requested changes either to about.js or to layouts/index.js

**Comment by oreny1** [comment]
I have the same problem as well.

Looks like the schema is not updated (grphiql don't show the new data after restart)

Any suggestions how get around it?

Thanks

**Comment by SilasOtoko** [comment]
Same problem here, even after copying and pasting the code straight from the tutorial and restarting the server.

**Comment by SilasOtoko** [comment]
I've figured it out! Well, for myself at least. The tutorials don't always specify where a gatsby-config.js should go. In tutorial 3, I had the config file in my 'src' file without issues, but after talking with KyleAMatthews I realized that it should actually be created in the root folder, not in src. After moving it to the root directory the error went away! So for Tutorial 4, gatsby-config.js _must_ be in the root directory.

Hope this helps someone else!

**Comment by barbush** [comment]
Confirmed resolved!

**Comment by kildareflare** [comment]
Followed the tutorial step by step. And I get the following error related to the graph query.

```
  GraphQL Error Unknown field `siteMetadata` on type `Site`
  file: C:/Code/Projects/bss3/prt4-data/src/layouts/index.js

  1 |
  2 |   query LayoutQuery {
  3 |     site {
> 4 |       siteMetadata {
    |       ^
  5 |         title
  6 |       }
  7 |     }
  8 |   }
```

As per tutorial, this is defined in  `gatsby-config.js` which is in the root.
![image](https://user-images.githubusercontent.com/5456669/32149287-a79eb4fc-bd66-11e7-9fe0-b6f6924244c9.png)

Repeated more than once, starting from scratch.
npm: 5.4.2
node: 6.11.3

**Comment by theroncross** [comment]
Having the same issue - data is undefined (verified by logging as above).
Steps taken:
1) copied and pasted all files for this tutorial
2) restarted with `gatsby develop` with each file change looking for where the issue was
3) object structure is fine in graphiQL ( I get the title when queried )
4) `gatsby-config.js` is in root
5) tried a different browser

**Comment by mrYakamoto** [comment]
same as @theroncross, carefully copied the tutorial and data is undefined.

GraphQL Error There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLParser: Unknown field `siteMetadata` on type `Site`. Source: document `LayoutQuery` file: `GraphQL request`.

**Comment by heyalbert** [comment]
Same issue here: TypeError: Cannot read property 'site' of undefined

**Comment by althe3rd** [comment]
Did anyone ever find a solution to this? I am getting this as well having tried everything suggested but don't see a solution suggested.

**Comment by oreny1** [comment]
@SilasOtoko solution solved the issue for me the tl;dr is move the gatsby-config.js  file to the root directory.

**Comment by AlbertWhite** [comment]
For me the problem is that we should give a name to the query.

From
```js
export const query = graphql`
  query {
    site {
      siteMetadata {
        title
      }
    }
  }
`
```

To 
export const query = graphql`
  query SiteQuery{
    site {
      siteMetadata {
        title
      }
    }
  }
`

For me there is a problem with the tutorial.

**Comment by whiteleopard0424** [comment]
it is not working

**Comment by xirapo** [comment]
Make sure you are under a page component because graphql works for page components and useStaticQuery works better in non-page components, that can be causing the error.

`const data = useStaticQuery(
    graphql`
      query {
        site {
          siteMetadata {
            title
          }
        }
      }
    `
  )`
