### ISSUE TITLE
gatsby-plugin-sitemap: restore the ability to pass additional query data 

### ISSUE THREAD

**Issue by abohannon** [gatsbyjs/gatsby#22703]
## Summary

It appears that with the latest version, the ability to pass additional data in the sitemap query was removed. Our sitemap is constructed using data from `site`, `allSitePage` and another query, but after updating our additional query data is no longer being returned. The issue seems to be with the explicit shape being returned on line 55 in `internals` vs. returning `r.data` as before.
https://github.com/gatsbyjs/gatsby/commit/07319d061c8af703a22403d9cd52acd0b458706d#diff-a627f3ef3dc8b682479f174b8c29fc20

### Basic example

The query we're using that no longer works is:
```
const sitemapPageQuery = `
{
  site {
    siteMetadata {
      siteUrl
    }
  }
  allSitePage {
    nodes {
      path
      context {
        index
        filterValue
      }
    }
  }
  allContentfulP0001Page {
    nodes {
      robotsMetaTags
      url
    }
  }
}
`
```

`allContentfulP0001Page` data comes back undefined.

### Motivation

Being able to pass additional query data allows us to tailor the creation of our sitemap. It would be helpful if this feature could be restored.

**Comment by vladar** [comment]
@moonmeister Any thoughts on this?

**Comment by abohannon** [comment]
We were able to refactor to include the data we needed on the `allSitePage` query and get rid of the additional individual page query, but I still think it's helpful to be able to make a broader query here, in case additional data is needed.

**Comment by moonmeister** [comment]
hmmm...sounds like we found some code that wasn't covered by tests. I think I may know where I caused this...I should have some time in the next couple days to take a look. Anyone else is welcome to if I don't get to it.
