### ISSUE TITLE
[gatsby-plugin-sharp] issue with example on 'using-gatsby-image' micro-site

### ISSUE THREAD

**Issue by clanceyp** [gatsbyjs/gatsby#22714]
## Description 
Trace LQIP SVG placeholder is incorrectly positioned on one of the example images.
On the using-gatsby-image micro-site, the LQIP for one of the images is out of alignment. 

### Steps to reproduce

- Go to https://using-gatsby-image.gatsbyjs.org/traced-svg/ (I'm using Brave)
- Observe “Beach and tents from above” by Syd Sujuaan (via unsplash.com) image loading (first-row third image) 
- Hover over the above image with your mouse 

### Expected result

The LQIP should line up with the fully loaded image 

### Actual result

The LQIP doesn't line up with the fully loaded image 

### Environment

Prod

**Comment by vladar** [comment]
Do you experience the same issue in other browsers? (I couldn't repro in Chrome or Firefox)

**Comment by clanceyp** [comment]
Yes, I get the same behaviour in Chrome MacOS and Chrome on Google pixel 3XL

**Comment by vladar** [comment]
Could reproduce in Chrome in device emulation mode. Interestingly it looks like it's the image itself that is displayed incorrectly, not the SVG.

**Comment by clanceyp** [comment]
Oh, that's interesting, I didn't think of that.

**Comment by clanceyp** [comment]
I'm no longer seeing the offending behaviour. So closing issue.
