### ISSUE TITLE
[gatsby-source-drupal] Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by robdecker** [gatsbyjs/gatsby#22724]
## Description

I'm using the Gatsby Cloud live preview. The build compiles fine, and the preview functionality works. When creating a new Drupal node and Gatsby Cloud attempts to rebuild, it fails/crashes. A manual restart of the live preview works. 

This is a blocker since I can't expect the client to restart the live preview after each new Drupal node.

### Expected result

The build should complete, and the new Drupal node should be preview-able.

### Actual result

```
10:33:13 AM: TypeError: Cannot read property 'map' of undefined 
 - utils.js:148 handleWebhookUpdate [www]/[gatsby-source-drupal]/utils.js:148:70 
 - gatsby-node.js:217 [www]/[gatsby-source-drupal]/gatsby-node.js:217:20 
 - layer.js:95 Layer.handle [as handle_request] [www]/[express]/lib/router/layer.js:95:5 
 - index.js:317 trim_prefix [www]/[express]/lib/router/index.js:317:13 
 - index.js:284 [www]/[express]/lib/router/index.js:284:7 
 - index.js:335 Function.process_params [www]/[express]/lib/router/index.js:335:12 
 - index.js:275 next [www]/[express]/lib/router/index.js:275:10 
 - read.js:130 [www]/[body-parser]/lib/read.js:130:5
 - index.js:224 invokeCallback [www]/[raw-body]/index.js:224:16 
 - index.js:213 done [www]/[raw-body]/index.js:213:7 
 - index.js:273 IncomingMessage.onEnd [www]/[raw-body]/index.js:273:7
 - task_queues.js:84 processTicksAndRejections internal/process/task_queues.js:84:21
```

### Environment

I only see this on live preview, and not on my local.

**Comment by pieh** [comment]
@smthomas want to take a look at this?

If @robdecker used one of recent versions the error would happen in here:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-drupal/src/utils.js#L150-L152 (converting dist line from error to src line)

And it might happen that `referencedNodesLookup.get(newNode)` is `undefined` if the new node didn't have any references, so probably doing sanity check before mapping would be good idea

**Comment by smthomas** [comment]
I am able to replicate this issue and am currently working on a fix.

**Comment by robdecker** [comment]
Our team has worked on this, and have created a couple patches that seem to be working well.

```
diff --git a/node_modules/gatsby-source-drupal/utils.js b/node_modules/gatsby-source-drupal/utils.js
index 85c6b8f..ec4cd12 100644
--- a/node_modules/gatsby-source-drupal/utils.js
+++ b/node_modules/gatsby-source-drupal/utils.js
@@ -145,8 +145,11 @@ const handleWebhookUpdate = async ({
     nodesToUpdate.push(...addedReferencedNodes);
   } else {
     // if we are inserting new node, we need to update all referenced nodes
-    const newNodeReferencedNodes = referencedNodesLookup.get(newNode).map(id => getNode(id));
-    nodesToUpdate.push(...newNodeReferencedNodes);
+    const newNodes = referencedNodesLookup.get(newNode);
+    if (typeof newNodes !== `undefined`) {
+      const newNodeReferencedNodes = newNodes.map(id => getNode(id));
+      nodesToUpdate.push(...newNodeReferencedNodes);
+    }
   } // download file
```

```
diff --git a/node_modules/gatsby/dist/bootstrap/page-hot-reloader.js b/node_modules/gatsby/dist/bootstrap/page-hot-reloader.js
index 149d82a..a71aea5 100644
--- a/node_modules/gatsby/dist/bootstrap/page-hot-reloader.js
+++ b/node_modules/gatsby/dist/bootstrap/page-hot-reloader.js
@@ -53,7 +53,9 @@ module.exports = graphqlRunner => {
     }
   });
   emitter.on(`DELETE_NODE`, action => {
-    if (action.payload.internal.type !== `SitePage`) {
+    // Gatsby Drupal preview does not send a valid payload.
+    // We need to make sure it is set.
+    if (typeof action.payload !== `undefined` && action.payload.internal.type !== `SitePage`) {
       pagesDirty = true; // Make a fake API call to trigger `API_RUNNING_QUEUE_EMPTY` being called.
       // We don't want to call runCreatePages here as there might be work in
       // progress. So this is a safe way to make sure runCreatePages gets called
```

cc: @arshad

**Comment by arshad** [comment]
> diff --git a/node_modules/gatsby/dist/bootstrap/page-hot-reloader.js b/node_modules/gatsby/dist/bootstrap/page-hot-reloader.js
> index 149d82a..a71aea5 100644
> --- a/node_modules/gatsby/dist/bootstrap/page-hot-reloader.js
> +++ b/node_modules/gatsby/dist/bootstrap/page-hot-reloader.js
> @@ -53,7 +53,9 @@ module.exports = graphqlRunner => {
>      }
>    });
>    emitter.on(`DELETE_NODE`, action => {
> -    if (action.payload.internal.type !== `SitePage`) {
> +    // Gatsby Drupal preview does not send a valid payload.
> +    // We need to make sure it is set.
> +    if (typeof action.payload !== `undefined` && action.payload.internal.type !== `SitePage`) {
>        pagesDirty = true; // Make a fake API call to trigger `API_RUNNING_QUEUE_EMPTY` being called.
>        // We don't want to call runCreatePages here as there might be work in
>        // progress. So this is a safe way to make sure runCreatePages gets called
> ```

This one is on NODE DELETE and should most probably happen on the Drupal side. 

The Drupal module should be updated to send an empty payload on delete. We'll send a patch on drupal.org.

**Comment by smthomas** [comment]
The Delete will need to happen on the Drupal side. I created a stub issue in the Drupal.org issue queue and will follow up on this there. It will require changes to the Drupal module and to the gatsby-source-drupal plugin.

https://www.drupal.org/project/gatsby/issues/3125786

**Comment by arshad** [comment]
Looks good. Thanks @smthomas
