### ISSUE TITLE
bug(starters): starter pages are not created for some starter repos

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#22733]
## Description

for some starters in the starters.yml there are no starters pages created and creating a 404. with the gatsbyjs starter there is a page with blurred preview but with fore reload there is an error page.

this starters are affected:

- gatsby-starter-stripe
  - https://www.gatsbyjs.org/starters/brxck/gatsby-starter-stripe/
  - https://github.com/brxck/gatsby-starter-stripe

### Steps to reproduce

open starter page 

### Expected result

should be an page

### Actual result

404 page

### Related Issues

- #22431 `Update docs/processing-payments-with-stripe`
- #19849 `bug(starters): starter pages are not created for some starter repos` 
- #19267 `Add link checker for Gatsby Docs`

**Comment by pieh** [comment]
At every build there is percentage of sites/starters that fail to take screenshot of sites. To not fail .org builds completely we skip them. It's not always same demo sites also - the screenshot service is pretty flaky. For now we skip those in builds, but maybe instead we could show them with some placeholder image/screenshot

![Screenshot 2020-04-02 at 18 37 14](https://user-images.githubusercontent.com/419821/78274772-fe9f4a00-7510-11ea-9cd2-6f8a3aeb37b9.png)

**Comment by muescha** [comment]
yes - a placeholder would be better instead of skipping the starter

**Comment by muescha** [comment]
note for changing this: 
- the field `hasScreenshot` is used in more places and not only at the `reporter.warn` lines: [search for `hasScreenshot`](https://github.com/gatsbyjs/gatsby/search?q=hasScreenshot&unscoped_q=hasScreenshot)

**Comment by pieh** [comment]
Right, this is how we skip displaying full entries right now. We could instead opt into removing those filters from queries and in right components fallback to some placeholder images (or just don't show anything, depending on layout? https://www.gatsbyjs.org/starters?v=2 will need some image to keep grid layout, but details page - https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-blog/ could just skip the screenshot I think )

**Comment by muescha** [comment]
it is still a bug (#23383)

**Comment by LekoArts** [comment]
Since the starters are now sourced from WordPress this issue was resolved.
