### ISSUE TITLE
Feature Request: Table of Content (TOC) for blogs

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#22730]
## Summary

There should be also a TOC available in blogs.

it should be default deactivated and similar to the docs could be enabled by a frontmatter setting `disableTableOfContents: false` or similar

### Basic example

in #22548 `(blog) service relief project` there is a need of a TOC also in a blog post. this is solved via a manual TOC.

### Motivation

avoid DRY

## Related Issues

- #22548 `(blog) service relief project`
- #22728 `bug: markdown anchor links for a header with html`

**Comment by pieh** [comment]
Just to make sure - this is feature request for gatsbyjs.org site and not for remark/mdx (which does have `tableOfContents` support?

**Comment by muescha** [comment]
i would say to the gatsbysjs website and the blog part. 

i see there as a blog post using a manual toc but with this error: 
- #22728 `bug: markdown anchor links for a header with html`

so i see a small need to maybe have a TOC also in blogs

**Comment by Rizwanjamal** [comment]
Hello ! I would like to contribute to this one. Can anyone guide me how can we connect for pair programming.
Thanks !

**Comment by LekoArts** [comment]
I don't think that we'll need this as typically the blog posts don't have a TOC. The post you linked was an exception.
