### ISSUE TITLE
Image loading slow using gatsby-image 

### ISSUE THREAD

**Issue by EliranGooner** [gatsbyjs/gatsby#22734]
## Summary

I have this website: https://zeitouni.herokuapp.com which has quite a few images in high quality. When user first loads the website it takes forever for gatsby-image to load most of the images.

## Relevant information

repo of the project is here: https://github.com/EliranGooner/zeitouni

First thing I suspect for being the issue is the image sizes. I'm not sure which sizes I should strive for, to make the image loading faster.
The issue also might be the component I use to get the Images. It's a method I found on Spectrum that was suggested in order to get around the inability to interpolate on queries with Graphql.
The component looks like this:

```
const Image = ({ imgName, ...props }) => (
  <StaticQuery
    query={graphql`
      query {
        allImageSharp {
          edges {
            node {
              fluid(maxWidth: 1200, quality: 100) {
                ...GatsbyImageSharpFluid
                originalName
                presentationWidth
              }
            }
          }
        }
      }
    `}
    render={data => {
      const image = data.allImageSharp.edges.find(
        edge => edge.node.fluid.originalName === imgName
      )
      if (!image) {
        return null
      }
      return <Img fluid={image.node.fluid} {...props} />
    }}
  />
)
```

### Environment (if relevant)

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.7 => 2.19.41 
    gatsby-background-image: ^0.10.2 => 0.10.2 
    gatsby-cli: ^2.10.9 => 2.11.1 
    gatsby-image: ^2.2.39 => 2.2.43 
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.2.39 => 2.2.47 
    gatsby-plugin-offline: ^3.0.32 => 3.0.40 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.23 
    gatsby-plugin-sass: ^2.1.30 => 2.1.30 
    gatsby-plugin-sharp: ^2.4.3 => 2.4.12 
    gatsby-plugin-sitemap: ^2.3.1 => 2.3.1 
    gatsby-source-filesystem: ^2.1.46 => 2.1.54 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.18 
  npmGlobalPackages:
    gatsby-cli: 2.10.9

**Comment by EliranGooner** [comment]
Optimising images was the problem, sorry about that.

**Comment by dellwatson** [comment]
@EliranGooner hello, how did u optimise the image ? my gatsby image also rendering slow,  imnot sure how to do it in best practise...

did u compress the image ? does having 1mb consider as big ?
