### ISSUE TITLE
Gatsby plugin lunr docs correction

### ISSUE THREAD

**Issue by olegKusov** [gatsbyjs/gatsby#22735]
## Summary

I try to use multi language search with Gatsby but my attemp failed.

1. On official docs at the bottom there is link to the Medium outdated material wich is not actual now.
![image](https://user-images.githubusercontent.com/28058268/78183133-15419480-7470-11ea-969a-6ac2d2c4f0f5.png)

2. With Gatsby lunr official tutorial there is no info about frontmatter.lang field. Thats why i had errors until i deleted it.

![image](https://user-images.githubusercontent.com/28058268/78183317-5f2a7a80-7470-11ea-8a94-79d4f561b957.png)

now it look like that
![image](https://user-images.githubusercontent.com/28058268/78183351-6ea9c380-7470-11ea-9b65-38bf94e34bfa.png)

Error dissapear but know i have another error with this.props.lng. In docs there is no info about props and in Medium article there is no props too. and Medium article doesnt have this line of code at all. 

![image](https://user-images.githubusercontent.com/28058268/78183429-900aaf80-7470-11ea-9990-b334b658d564.png)

if i insert "en" or "ru" lang there im getting error with index.search. There is no that method in window.__Lunar__en.index and ru.index.

Some recommended topics to cover:

- We need working solution for multi-language search.

**Comment by pieh** [comment]
Hey @olegKusov! This plugin is not maintained in this repository - we pull plugin README from npm, and this particular one is hosted in this repository https://github.com/humanseelabs/gatsby-plugin-lunr so please, for lunr plugin specifric help - make issue in that repository
