### ISSUE TITLE
navigation.js causing app to crash in specific pages

### ISSUE THREAD

**Issue by EliranGooner** [gatsbyjs/gatsby#22751]
## Description

For 2 specific pages in my app, the app crashes and points to an error in the ```navigation.js``` file. I'm not sure what to make of this error message and not sure where to start trying to fix it.

### Steps to reproduce

repo is here: https://github.com/EliranGooner/zeitouni
This is my app: https://zeitouni.herokuapp.com/
I know it's a foreign language for most of you but you can play with pages until 2 of them cause a crash.
These 2 URLs are the problem:
https://zeitouni.herokuapp.com/herzliya
https://zeitouni.herokuapp.com/kfar-saba
They just give you a blank screen in production but in development, it returns me the error below.
The only change I made before noticing this issue is optimising most of the images on the app.

### Expected result

Pages should load normally as they did yesterday.

### Actual result

In production: blank page. In development: this error - 
```
×
TypeError: Cannot read property 'getElementsByTagName' of null
(anonymous function)
/Users/eliran/code/gatsby/zeitouni/.cache/navigation.js:173
  170 | if (document.title) {
  171 |   pageName = document.title
  172 | }
> 173 | const pageHeadings = document
  174 |   .getElementById(`gatsby-focus-wrapper`)
  175 |   .getElementsByTagName(`h1`)
  176 | if (pageHeadings && pageHeadings.length) {
```

sandbox with the complete ```navigation.js``` file: https://codesandbox.io/s/proud-worker-v69q7

### Environment

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.7 => 2.19.41 
    gatsby-background-image: ^0.10.2 => 0.10.2 
    gatsby-cli: ^2.10.9 => 2.11.1 
    gatsby-image: ^2.2.39 => 2.2.43 
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.2.39 => 2.2.47 
    gatsby-plugin-offline: ^3.0.32 => 3.0.40 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.23 
    gatsby-plugin-sass: ^2.1.30 => 2.1.30 
    gatsby-plugin-sharp: ^2.4.3 => 2.4.12 
    gatsby-plugin-sitemap: ^2.3.1 => 2.3.1 
    gatsby-source-filesystem: ^2.1.46 => 2.1.54 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.18 
  npmGlobalPackages:
    gatsby-cli: 2.10.9

**Comment by JustFly1984** [comment]
@EliranGooner
I had exactly the same error, had fixed it by fixing runtime issues in components of the page. Please use typescript for help. There is some kind of unhandled error exception creeping up in the component tree, and navigation can't find `h1` element in non existing `gatsby-focus-wrapper`. There should be definitely check for `gatsby-focus-wrapper` before searching `h1`

**Comment by EliranGooner** [comment]
@JustFly1984 
Thank you for your response but I'm struggling to figure out a plan of action for this. I'm pretty new to gatsby (with no experience in typescript)  and coding in general. 
Do you reckon I need to make a condition inside this componentDidMount to check if ```gatsby-focus-wrapper``` exists and then run the rest of the function? What would I direct it to do if there's no ```gatsby-focus-wrapper```.

**Comment by EliranGooner** [comment]
Fixed it, apparently the placement of some download link I placed caused this for some reason.
I moved and it's all good now.
