### ISSUE TITLE
Filter by a paragraph value (in relationship)

### ISSUE THREAD

**Issue by Vacilando** [gatsbyjs/gatsby#22765]
The excellent plugin [gatsby-source-drupal](https://www.gatsbyjs.org/packages/gatsby-source-drupal/) allows navigating and filtering Drupal content using GraphQL.

We make heavy use of Drupal paragraphs and it works excellent except that we cannot find a way to filter by values in paragraphs.

For example, how to filter by value "name" in the query below?

```graphql
allNodePage {
  nodes {
    relationships {
      field_paragraph {
        ... on paragraph__author {
          relationships {
            field_person {
              name
            }
          }
        }
      }
    }
    title
    drupal_internal__nid
  }
}
```

And in case it's not possible, are there any workarounds you would suggest?

**Comment by freiksenet** [comment]
Unfortunately we don't support filtering on Unions and Interfaces at this moment. It could be a very confusing behaviour for fields that only exist on some interfaces. 

I'll assign @smthomas who is working on Drupal plugin, maybe he has a workaround for it.

**Comment by smthomas** [comment]
@Vacilando There are a few things I can think of that might help as a workaround. First, if you don't have that much data, you can query the data and filter by name in gatsby-node.js with some JavaScript.

If you have a lot of data and this will hurt your build times too much, you could create a field on your Drupal content type and then just syndicate the value in the paragraph to this field using hook_entity_insert/hook_entity_update in a Drupal module. Essentially you just grab the name field if the entity has an author paragraph and save it in this other field that is directly on the node entity.

In the example below I created a `field_author_name` field on my Basic Page content type and can filter by that using:

`query MyQuery {
  allNodePage(filter: { field_author_name: { eq: "Shane" } }) {
    edges {
      node {
        id
        field_author_name
      }
    }
  }
}`

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
