### ISSUE TITLE
Passing props from page to wrapPageElement Element

### ISSUE THREAD

**Issue by algebrathefish** [gatsbyjs/gatsby#22762]
## Summary

I have a menu that toggles and untoggles. To keep the animation between page changes, I am using wrapPageElement as suggested here: https://levelup.gitconnected.com/keeping-state-between-pages-with-local-state-in-gatsby-js-96f8583e0db2

the thing is, the menu content is different depending on the pages. I wanted to pass a prop from the page to the menu, but now the layout does not contain the menu anymore since it is added in the wrapper element component for it to preserve the state.

How would I pass a prop from the page to a component that is imported in the wrapPageElement component (for clarity, in the case of the example in the link, the component is imported in MailWidgetWrapper)

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by Js-Brecht** [comment]
You could use React's `<Context>` component, or some other state manager.   You would need a consumer in your menu component and in the page component.  The page component can set the value it needs, and the value will be reflected in the menu component

**Comment by algebrathefish** [comment]
Thank you @Js-Brecht !
