### ISSUE TITLE
Feature Request: add support operator "in" for types string, int, float

### ISSUE THREAD

**Issue by 3axap4eHko** [gatsbyjs/gatsby#2277]
It would be great to have support of `in` operator for scalar types to create simple queries with arrays like:
``` graphql
{
  allMarkdownRemark(
    filter: {
      id: { in: ["0","1"] }
    }
  ) {
    edges{
      node {
        id
      }
    }
  }
}
```
for now I need to build regexp

**Comment by KyleAMathews** [comment]
Oh interesting!

So the above would turn into something like `["0", "1"].some(f => _.includes(id, f))`

**Comment by 3axap4eHko** [comment]
I guess it should be in ES6 notation like `["0","1"].includes(id)` =)

**Comment by KyleAMathews** [comment]
So it's an equality match then? You basically want `eq` for for matching against multiple things?

**Comment by 3axap4eHko** [comment]
Against multiple things passed through arguments

**Comment by 3axap4eHko** [comment]
it's something like `$in` in mongodb

**Comment by chmac** [comment]
This would be really helpful for pagination. For example, I have ~2k blog posts, I'm showing 15 per page. Being able to query for an array of post IDs would be helpful in the `pageQuery`.
