### ISSUE TITLE
docs: add new query stats to doc at telemetry

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#22794]
## Summary

the new stats should be also noted in the doc telemetry, introduced in:

- #22540 `Make build collect GraphQL/Sift query data for telemetry`

### Motivation

all collected data should be transparent

## Steps to resolve this issue

add information about the new stats to this page:

https://www.gatsbyjs.org/docs/telemetry/

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

## related issues

- #22540 `Make build collect GraphQL/Sift query data for telemetry`

**Comment by caitlinselca** [comment]
Hi! I am a new contributor to Gatsby and this particular issue interests me a lot. May I begin working on this ticket to resolve the issue?

**Comment by marcysutton** [comment]
@caitlinselca yes, absolutely! We would welcome your contribution. Let us know if you have any questions.

**Comment by caitlinselca** [comment]
awesome! thank you 😄

**Comment by caitlinselca** [comment]
> @caitlinselca yes, absolutely! We would welcome your contribution. Let us know if you have any questions.

Hi! I was wondering if I could get help on this issue. I'm having trouble understanding what data I should be documenting/how to get this data. It would be greatly appreciated if you can direct me on how to get information about the new stats/what exactly these stats are. Thank you! :)

**Comment by AishaBlake** [comment]
Hi, @caitlinselca! If you look at the [files changed](https://github.com/gatsbyjs/gatsby/pull/22540/files) in the PR linked above, that should give you a starting point. @freiksenet, do you have any more human-friendly info that might help make what we're collecting more clear? Just looking at property names, I'm not sure what everything is either.
