### ISSUE TITLE
`getNode` returns null on upgrade from gatsby-source-contentful 2.1.88 to 2.2.5

### ISSUE THREAD

**Issue by glenna** [gatsbyjs/gatsby#22792]
## Description

Upgrading `gatsby-source-contentful` from 2.1.88 to 2.2.5 resulted in build errors, as we're unable to use gatsby's `getNode` function with a valid node id string. Using the graphql search I can find the node.

Of note: it's a parent node to the current node we're inspecting

### Expected result

I should be able to fetch a node by `getNode` on `gatsby-source-contentful` 2.2.5

### Actual result

`getNode` returns null

### Environment

 System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 3.7.6 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12
    gatsby-image: ^2.0.13 => 2.0.33
    gatsby-plugin-canonical-urls: ^2.1.5 => 2.1.5
    gatsby-plugin-catch-links: ^2.1.5 => 2.1.17
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6
    gatsby-plugin-google-gtag: ^1.0.17 => 1.0.17
    gatsby-plugin-hotjar: ^1.0.1 => 1.0.1
    gatsby-plugin-netlify-cache: ^1.0.0 => 1.0.0
    gatsby-plugin-polyfill-io: ^1.1.0 => 1.1.0
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0
    gatsby-plugin-sass: ^2.0.1 => 2.0.7
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5
    gatsby-plugin-sitemap: ^2.0.5 => 2.0.5
    gatsby-plugin-typescript: ^2.0.15 => 2.0.15
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-source-contentful: ^2.2.5 => 2.2.5
    gatsby-source-filesystem: ^2.0.2 => 2.0.5
    gatsby-source-stripe: ^3.0.4 => 3.0.4
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14
  npmGlobalPackages:
    gatsby-cli: 2.11.5
 I've also updated node to 12.16.1 -- and still fails

**Comment by wardpeet** [comment]
Hey @glenna, thanks for filling this bug.

That's a big leap in versions, I'll see if I can find the culprit and create an update. When does this happen? Initially or when you get a contentful update?

Is it possible to give me some steps to reproduce? (I have access to gatsby cloud 😄 )

**Comment by glenna** [comment]
So, internally, we have a gatsby plugin that transforms some of our nodes into data that our code understands.

We have a content model that has another content model as a child. When we are doing our transformations on the child node, we get the reference to the parent node like so

```
  const parentNode = rest.getNode(
    node['name of content type of parent node___NODE'][0]
  )
```

It's important to note that `node['name of content type of parent node___NODE'][0]` does return a node ID, and in graphiql, we're able to find a node with that ID when querying in allContentfulNameOfContentTypeOfParentNode and filtering for IDs matching the one returned above.

If it helps, you can look at our branch builds on gatsby builds: `upgrade/gatsby-source-contentful`

**Comment by xmflsct** [comment]
Same here, though I am querying the other way around, from parent to child.
`2.2.x` did not work, `getNode` returns `undefined` for me. I downgrade to `2.1.100` which works perfectly fine.

**Comment by scnroy** [comment]
Potentially related: Contentful nodes aren't showing up when calling the `onCreateNode` in `gatsby-node.js`. As with the other issues, this isn't a problem in `2.1.100`. Puzzle!

**Comment by xmflsct** [comment]
Any updates on this?

**Comment by xmflsct** [comment]
Not stable. I believe it is in the backlog to work on.

**Comment by xmflsct** [comment]
Not stale.

**Comment by xmflsct** [comment]
Not stale. Still waiting to be fixed.

**Comment by xmflsct** [comment]
More waiting..

**Comment by xmflsct** [comment]
Curious, any progress of this case?

**Comment by Inambe** [comment]
I'm facing same in gatsby-source-contentful @ 2.3.48
```javascript
if (node.internal.type === "ContentfulPost") {
    if (node.categories___NODE && node.categories___NODE.length)
      console.log(getNode(node.categories___NODE[0]))
}
``` 
returns `null` or `undefined` but works other way:
```javascript
if (node.internal.type === "ContentfulCategory") {
    if (node.post___NODE && node.post___NODE.length)
      console.log(getNode(node.post___NODE[0]))
}
```

I'm new to Gatsby, so I thought I didn't understand the concept thus spent the last 2 days in Gatsby docs and QA sites but I think it should work when it is not.

**Comment by Inambe** [comment]
I can confirm that `gatsby-source-contentful@2.1.100`  has solved my problem but it's not the latest version of course.

**Comment by axe312ger** [comment]
@xmflsct 

Hey there, we changed a lot related to the ids of nodes. Could you check with latest v4 of the plugin if your issue still exists?

Thanks :)

**Comment by xmflsct** [comment]
@axe312ger Thanks for the update! I have been using `2.3.51` for a while now without problem. :)

**Comment by axe312ger** [comment]
Seems to be fixed in the latest versions. If you still run into this issue, and use v4 of the gatsby-source-contentful plugin, feel free to comment here.

**Comment by osartun** [comment]
I'm not using v4 of gatsby-source-contentful but I want to add to the conversation because I can confirm that the functionality breaks between 2.1.100 and 2.2.5 even though there are not that many changes in the code of the plugin.

If you compare the commits between these version you see that the contentful plugin creates nodes asynchronously since https://github.com/gatsbyjs/gatsby/pull/22307: https://github.com/gatsbyjs/gatsby/compare/d2d32d4f61619da5200f2dd15a034cd51f5e9932..f9133d2fb4698b59a055ba4ed711303133ccdd34#diff-b2ca51ba722d6b47f74a2227bfebd74836ff08c1e0184236b001ae30b52d25e0

My theory is that by the time the transformer plugin runs the referenced node doesn't exist in Gatsby's node store yet. That's why it returns `undefined` there and yet GraphiQL works just fine because by the time GraphiQL accesses the node store all the sourcing and transforming is completed.

I don't know a fix for this yet.

**Comment by wardpeet** [comment]
You should open an issue if this is still a problem with the latest contentful source plugin

**Comment by osartun** [comment]
@wardpeet It took a while, but today I created a reproducible test case: https://github.com/osartun/gatsby-contentful-transformer-issue

And opened a new issue: https://github.com/gatsbyjs/gatsby/issues/32363

**Comment by PierrickHus** [comment]
Hi,
I seems to be not working with the latest version : 5.12.0
I tried to downgrade to 2.1.100 and it's working.

This is weird because getNode does't return `undefined` all the time.
