### ISSUE TITLE
[SSR] How to invoke `reporter`, as from gatsby-node.js?

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#22818]
## Summary

While trying to update the [Gatsby plugin for glaze](https://github.com/kripod/glaze/tree/master/packages/gatsby-plugin-glaze), I realized that emitting warnings during SSR would improve the DX. For instance, when dynamic styles are applied without a valid SSR style injector associated with them. I would like to pass Gatsby's `reporter` to glaze's `setReporter`, before calling any of the following code:

https://github.com/kripod/glaze/blob/bb8a31a4c38c39b045d89ab13b2552a8ff406e8b/packages/gatsby-plugin-glaze/gatsby-ssr.js

Related issue: #14873

**Comment by freiksenet** [comment]
That's a good idea. Currently there is no way to do it. It's also complicated by the fact that `gatsby-ssr` happens in React land, while `gatsby-node` happens in node land. It could be possible to pass reporter there. However it needs to work also in develop, which doesn't go through SSR, but is rendered on client.

At this moment, I feel it's too much work for a not very common use case, so we aren't going to fix it ourselves. We would be happy to accept a PR that would add this functionality though.
