### ISSUE TITLE
Error when adding siteMetaData. it won't run

### ISSUE THREAD

**Issue by a-ditucalan** [gatsbyjs/gatsby#22812]
## Description

When I tried to add `siteMetaData` in config file and start running it. it shows  Error: Reducers may not dispatch actions. this is new project using gatsby-starter-hello-world-template
### Steps to reproduce

module.exports = {
  siteMetaData:{
    title: 'Fullstack bootcamp'
  },
   plugins:[
    'gatsby-plugin-sass',
   ],
}

### Expected result
it should run the script gatsby develop

### Actual result

it return error when I start running gatsby develop
![image](https://user-images.githubusercontent.com/58244709/78418656-dcbcd900-7670-11ea-9a22-f33a1e17b8c8.png)

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.0 - /usr/local/opt/node@12/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/opt/node@12/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Safari: 13.1
  npmPackages:
    gatsby: ^2.19.45 => 2.20.12
    gatsby-plugin-sass: ^2.2.1 => 2.2.1
  npmGlobalPackages:
    gatsby-cli: 2.11.4

**Comment by Js-Brecht** [comment]
Hello @a-ditucalan.  Can you share a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) of the issue?  It would help a great deal to track down the problem.

**Comment by Js-Brecht** [comment]
Hey @a-ditucalan, I just noticed something: `Data` in `siteMetaData` shouldn't be capitalized.

If I make my `gatsby-config` look like that, I get the same error you do.  I can't be 100% sure that's what's causing the issue, but at the very least, you won't be able to use that value in your project with it like it is.

**Comment by pieh** [comment]
Seems like we have fairly similar report in https://github.com/gatsbyjs/gatsby/issues/23468 and we do have reproduction there (linked issue is bit more complex than just unhelpful error message)
