### ISSUE TITLE
Store login information/user state over multiple pages without server?

### ISSUE THREAD

**Issue by vedantroy** [gatsbyjs/gatsby#22825]
## Summary
With a traditional react app that uses Firebase, you can store info about the user's session (eg: are they logged in/what's their username) in some global variable at the top of your component hierarchy.

However, let's say you use Gatsby, so each route is rendered to a different HTML page. Now you can no longer store user state inside a global variable, because each page is effectively its own react app. How can we get around this?

What's the solution?

**Comment by jonniebigodes** [comment]
@vedantroy you could always use redux or even React's context for what you need. or you could take a look at the [starters](https://www.gatsbyjs.org/starters) and search for firebase

**Comment by vedantroy** [comment]
@jonniebigodes . I've browsed through a bunch of examples with firebase + gatsby. I understand that you can use redux/react context to store data about login information. My question is, since Gatsby will generate a separate HTML page for each route, won't that information not be persisted because each HTML page is effectively its own react app?

**Comment by Js-Brecht** [comment]
@vedantroy I wouldn't say that each page is its own app.  In a sense, they are, but they are only the **start** of the app.  After React hydrates, it effectively becomes a SPA (using `@reach/router`).  Navigating to internal routes does not load more HTML, just more Javascript.  So each HTML page only provides a pre-rendered route, and an entry point to the app, when navigating to the site from outside.

So, if you place a Context provider in `wrapRootElement()`, that provider can be consumed throughout the lifetime of the app; i.e. when you leave the site.

**Comment by Js-Brecht** [comment]
Of course, the HTML pages also mean the site is usable when Javascript is turned off (at least the public portion).  In that case, you don't really have to worry too much about storing state anyway :slightly_smiling_face:

**Comment by vedantroy** [comment]
Thanks! That really cleared up how stuff works.
