### ISSUE TITLE
How to use hooks inside wrapRootElement?

### ISSUE THREAD

**Issue by vedantroy** [gatsbyjs/gatsby#22833]
## Summary

I assume that `exports.wrapRootElement` in "gatsby-browser.js" is meant to be a component that accepts another component and well... wraps it.

As such, I assume I could use hooks inside this component. Take a look at this simplified example of my "gatsby-browser.js":
```
// Assigning the function directly to wrapRootElement causes a react hooks
// linter error because it thinks wrapRootElement is not a function component.
// Probably because the name starts with a lowercase letter?
const Wrapper = ({ element }) => {
  const [loggedIn, setLoggedIn] = useState(/* some code */)
  useEffect(() => {
    firebase.auth().onAuthStateChanged(user => {
      setLoggedIn(!!user)
    })
  })
  return (
    <FirebaseContext.Provider value={{ loggedIn }}>
      {element}
    </FirebaseContext.Provider>
  )
}

exports.wrapRootElement = Wrapper 
```

This throws the following error:

Unhandled Rejection (Error): Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

**Comment by herecydev** [comment]
Off the top of my head try this:

```js
const FireBaseApp = () => {
const [loggedIn, setLoggedIn] = useState(/* some code */)
  useEffect(() => {
    firebase.auth().onAuthStateChanged(user => {
      setLoggedIn(!!user)
    })
  })
  return (
    <FirebaseContext.Provider value={{ loggedIn }}>
      {element}
    </FirebaseContext.Provider>
  )
}

const Wrapper = ({ element }) => {
  return <FireBaseApp element={element} />
}

exports.wrapRootElement = Wrapper 
```

So we're just wrapping everything in a fragment so that it is now a component. I think that should work

**Comment by vedantroy** [comment]
Thanks, this worked! I'm a bit surprised, because I thought a functional component in React was just a function that returns JSX, but I guess it also depends on the way it is called behind the scenes?

**Comment by Js-Brecht** [comment]
@vedantroy `wrapRootElement` is [here](https://github.com/gatsbyjs/gatsby/blob/3af9ec0c9a81196a3054be336633d8adae024d9f/packages/gatsby/cache-dir/production-app.js#L141-L148).

If you look at the way the `apiRunner` is called, you'll see why it doesn't work using hooks inside of `wrapRootElement`.  It has to be a react element that contains the hook, and that's what you're doing by wrapping it with another React Functional Component.

I actually just got done talking about this [here](https://spectrum.chat/gatsby-js/general/it-it-possible-to-use-react-hooks-inside-gatsby-browser-js~bda3fe45-352f-4a35-99b6-29026c6257b1), the other day.
