### ISSUE TITLE
OnClick event doens't work in builded version, working on development

### ISSUE THREAD

**Issue by brechtarnou** [gatsbyjs/gatsby#22849]
## Description
I have a hamburger menu, with an onClick event
```
          <div
            className="flex flex-col pointer"
            onClick={() => handleOverlay(true)}
          >
                  <div className="hamburger"></div>
                  <div className="hamburger"></div>
                  <div className="hamburger"></div>
          </div>
```
This onClick event should open a overlay menu, which works perfectly fine on development. When I do a gatsby build and gatsby serve, the onClick event isn't triggered.
I am also facing some other build issue, where a gatsby-background-image is not rendered in the builded site, while working perfectly in gatsby develop. 

### Steps to reproduce

I have set up an example repo, do a build & serve and try to click on the hamburger menu on the homepage.
https://github.com/brechtarnou/example-repo-gbi-build-issue

### Expected result
 Open a overlay menu as in gatsby develop

### Actual result
Click event is not triggered

### Environment

System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.7 => 2.20.12
    gatsby-background-image: ^0.10.2 => 0.10.2
    gatsby-cli: ^2.10.0 => 2.11.5
    gatsby-image: ^2.2.39 => 2.3.1
    gatsby-plugin-layout: ^1.1.22 => 1.2.1
    gatsby-plugin-manifest: ^2.2.39 => 2.3.3
    gatsby-plugin-offline: ^3.0.32 => 3.1.2
    gatsby-plugin-postcss: ^2.1.21 => 2.2.1
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.1.21 => 3.2.1
    gatsby-plugin-sharp: ^2.4.3 => 2.5.4
    gatsby-plugin-styled-components: ^3.1.19 => 3.2.1
    gatsby-plugin-transitions: ^2.1.6 => 2.1.6
    gatsby-source-filesystem: ^2.1.46 => 2.2.2
    gatsby-transformer-sharp: ^2.3.13 => 2.4.4
  npmGlobalPackages:
    gatsby-cli: 2.10.0
    gatsby: 2.19.27

**Comment by herecydev** [comment]
Works fine for me, running

1. `gatsby build` 
2. `gatsby serve`
3. Navigate to localhost:9000

Were there are console errors for you? Perhaps try a `gatsby clean` to flush everything away?

**Comment by brechtarnou** [comment]
Hi,

It works fine now, I did a gatsby clean. Thanks for pointing this out
