### ISSUE TITLE
I have come across a new error that suddenly happened without changing any code

### ISSUE THREAD

**Issue by arhoy** [gatsbyjs/gatsby#22841]
Not sure what this is and how to fix

```variables: 
  first: 250
  after: eyJsYXN0X2lkIjo0NzE1NzIwNDA5MjI4LCJsYXN0X3ZhbHVlIjoiNDcxNTcyMDQwOTIyOCJ9

success source and transform nodes - 45.263s
⠙ building schema

 ERROR 

UNHANDLED REJECTION Encountered an error trying to infer a GraphQL type for: `products___NODE`. There is no corresponding node with the `id` field matching: "Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ4MDA4NzAyODU0NTI=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ4MDA4Njk2MzAwOTI=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1OTg2MDc2MDk5OTY=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1OTg2MDY0OTU4ODQ=,Shopify__Product__

```

**Comment by moonmeister** [comment]
The team will need much more info...the template for bugs is there for a reason. Please include the output of `gatsby info` and some context about your setup and what is even throwing the error. 

Outside of that, my first guess is that the API is returning null and there are no nodes from which to infer data...but that's just a guess...verify your API is returning the proper data.

**Comment by moonmeister** [comment]
It's possible that if your pagination rate is too high that you are hitting a limit on the shopify API then getting the null return.
