### ISSUE TITLE
Typekit support broken w/ Gatsby 1.0

### ISSUE THREAD

**Issue by kevinschaich** [gatsbyjs/gatsby#2285]
Since migrating to Gatby 1.0, I haven't been able to get a Typekit font working with Gatsby. Has anyone had success with this?

I've tried the following two packages so far:

https://www.npmjs.com/package/react-typekit
this does not play nice with Sharp, can post logs here if it'd be helpful.

https://www.npmjs.com/package/webfontloader
this one needs access to window. I tried customizing webpack config via [gatsby docs](https://www.gatsbyjs.org/docs/debugging-html-builds/), that gets me past the `window` error but then manifests another. 

Thank you!

**Comment by kevinschaich** [comment]
Finally got it to work. Solution requires three steps:

1. `npm add --save webfontloader` or `yarn add webfontloader`

2. In the layout where you want to use the font, add a `ComponentDidMount` declaration as follows:

```javascript
import WebFont from 'webfontloader';

...

  componentDidMount = () => {
    WebFont.load({
      typekit: {
        id: 'dov0slp'
      }
    });
  }
```

3. In your `gatsby-node.js`, add the following:

**Comment by grgur** [comment]
Understanding if the code is executed during Server Side Rendering (SSR) or Client Side Rendering (CSR) can be used for purposes beyond conditionally loading modules.

That said, you could add something like this to your `gatsby-node.js`

```js
const webpack = require('webpack');

exports.modifyWebpackConfig = ({ config, stage }) => {
  config.merge({
    plugins: [
      new webpack.DefinePlugin({
        _SSR_: stage === 'build-html',
      }),
    ],
  });

  return config;
};
```

then in your code you could load WebFontLoader like this:

```js
if (_SSR_) {
  const WebFont = require('webfontloader');
  WebFont.load({
    google: {
      families: ['Montserrat:300,400,600', 'Roboto', 'Roboto+Condensed'],
    },
  });
}
```

**Comment by rickymetz** [comment]
I've been banging my head against the wall trying to get this to work.
I used the [gatsby-starter-basic](https://github.com/PrototypeInteractive/gatsby-react-boilerplate) starter which has this code for its `layouts/index.js`:

```
import React from 'react';
import PropTypes from 'prop-types';
import Helmet from 'react-helmet';
import WebFont from 'webfontloader';

import '../../sass/style.scss';

const TemplateWrapper = ({ children }) => (
  <div>
    <Helmet
      title="Gatsby React Boilerplate"
    />
    {children()}
  </div>
);

TemplateWrapper.propTypes = {
  children: PropTypes.func,
};

export default TemplateWrapper;
```

I'm not sure where to implement the code shown in @kevinschaich's comment above to get webfont loader to work. I'm at my wits end and any help would be appreciated.

**Comment by m-allanson** [comment]
@rickymetz you'll need to convert your `TemplateWrapper` component from [a stateless React component to a class-based React component](https://reactjs.org/docs/components-and-props.html#functional-and-class-components). That will allow you to add the [`componentDidMount` lifecycle method](https://reactjs.org/docs/react-component.html#componentdidmount).

`componentDidMount` runs in the browser and not when doing server side rendering, which is why it's safe to call `WebFont.load` there.
