### ISSUE TITLE
Using scss variables in js is invalid on build version

### ISSUE THREAD

**Issue by rishavpandey43** [gatsbyjs/gatsby#22853]
## Description

Styling done through scss variables in js file is not working in build version of project

### Steps to reproduce

1. Creating a scss variable and exporting it:
````
$website-theme-color: #ff0077;
:export {
  websiteThemeColor: $website-theme-color;
}
````

2. Importing it in any component for example, index.js and using it as-
```
...
import scssVariables from "../styles/sass/_variables.scss"
...

<div
      css={css`
      color: ${scssVariables.websiteThemeColor};
      background-color: #00000080;
    `}
>
....
</div>
```

On serving the project in gatsby build, everything is working properly, but when serving build version all the css styling done through scss variables are being invalid.

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

**Note:- ** I cross-checked by removing all the scss variables and then build the file, everything is working fine.

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

I expected that the same styling in gatsby build version as on gatsby development version

### Actual result

All the styling done on the page through scss variables are being invalid.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by ascorbic** [comment]
Hello. Can you include a minimal reproduction, as per the instructions in the description. There a lot of information missing that I'd need to help.
