### ISSUE TITLE
gatsby-plugin-smoothscroll offset top

### ISSUE THREAD

**Issue by SajithRAP** [gatsbyjs/gatsby#22852]
Is there a way to offset the top position ? Thanks

`
<Box onClick={() => scrollTo('#__ct1')}>Go Top</Box>
-> **offset top 120px**
`

**Comment by herecydev** [comment]
That plugin uses [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) which doesn't have a concept of offsets.

If you're trying to create a "Go to top of page" functionality you could use:

```
window.scroll({
  top: 120,
  behavior: "smooth"
})
```

**Comment by LekoArts** [comment]
Thank you for opening this!

Please refer to the issues of the plugin you're using. Thanks!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by SajithRAP** [comment]
> That plugin uses [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) which doesn't have a concept of offsets.
> 
> If you're trying to create a "Go to top of page" functionality you could use:
> 
> ```
> window.scroll({
>   top: 120,
>   behavior: "smooth"
> })
> ```

Cant use this because "window" will error out as undefined while building the site!

**Comment by herecydev** [comment]
> Cant use this because "window" will error out as undefined while building the site!

So check for the presence of the window first;

```js
typeof window !== 'undefined' && window.scroll({
    top: 120,
    behavior: "smooth"
  })
```
