### ISSUE TITLE
Using Location component in wrapRootElement causes navigate to reload page even if on same url

### ISSUE THREAD

**Issue by vedantroy** [gatsbyjs/gatsby#22878]
## Description
In gatsby-browser.js, use the following code:

```javascript
let global = false;

const App = (props) => {
  console.log('rendering')
  if (!global) {
    global = true
    navigate('/')
  }
  return <div>Hello World!</div>
}
export const wrapRootElement = _ => <App/>
```
This code works fine. However, changing the last line to:

```javascript
export const wrapRootElement = _ => (
  <Location>
    {location => <App {...location} />}
  </Location>
) 
```
causes "rendering" to be printed twice.

### Steps to reproduce
Described above. The default repository with the above code in "gatsby-browser.js" should result in this behavior.

I ran into this bug when debugging an infinite looping issue in my application.
### Expected result
Render should only be called once. (Navigate should not reload the page when its parameter is equal to the current path)

### Actual result
Render is printed twice. (Navigate is reloading the page even when its parameter is equal to the current path). At the very least, the behavior should be consistent.

Also, if you remove the `global` variable and the if statement, I assume render will be printed an infinite amount of times (infinite loop).
### Environment
```
  System:
    OS: Linux 5.5 EndeavourOS
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
    Yarn: 1.22.0 - ~/.nvm/versions/node/v13.9.0/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.9.0/bin/npm
  Languages:
    Python: 3.8.2 - /usr/bin/python
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12
    gatsby-image: ^2.3.1 => 2.3.1
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3
    gatsby-plugin-offline: ^3.1.2 => 3.1.2
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1
    gatsby-plugin-typescript: ^2.3.1 => 2.3.1
  npmGlobalPackages:
    gatsby-cli: 2.11.3
```

**Comment by ascorbic** [comment]
Hi. I'm afraid I can't reproduce this. Here are the steps I took:

• Created a site with the default starter
• Replaced `gatsby-browser.js` with the following:

```jsx
import React from "react"
import { Location } from "@reach/router"

const App = ({ navigate }) => {
  console.log("rendering")
  navigate("/")
  return <div>Hello World!</div>
}
export const wrapRootElement = _ => (
  <Location>{location => <App {...location} />}</Location>
)
```
I then ran both `gatsby develop` and `gatsby build` + `gatsby serve` and tried loading the page. It worked fine both times, in Firefox and Chrome. 

Can you create a repo with a minimal reproduction please.

**Comment by vedantroy** [comment]
Here is a reproduction repo: https://github.com/vedantroy/gatsby-possible-bug

It's the default repository with "gatsby-browser.js" changed. I believe I gave an incorrect code sample in my original post. The actual bugged code is:

```
const wrapRootElement = ({element}) => (
    <Location>
        {location => <App {...element} />}
    </Location>
)
```

**Comment by ascorbic** [comment]
OK, thanks for that. The difference is that you're using the `navigate()` function imported from `gatsby`, whereas in my example I'm using the `navigate()` function passed in from the `@reach/router` `<Location>` HOC. These are different functions. The Gatsby version does use the Reach version under the hood, but it adds the logic for async loading of page data. This isn't what you want here. The Gatsby version will _always_ load the page data, even if it's the same page, because otherwise it has no way of knowing if it has been updated on the server. For the redirect, you should use the Reach version, either imported directly or from the `<Location>` props. Change your example this and it works fine:

```jsx
import { Location } from '@reach/router'
import React from 'react'

const App = ({ element, navigate }) => {
    console.log("rendering...")
    navigate('/')
    return <div>Hello World!</div>
}

const wrapRootElement = (props) => (
    <Location>
        {location => <App {...props} {...location} />}
    </Location>
)

export { wrapRootElement }
```

**Comment by vedantroy** [comment]
@ascorbic Thanks for the explanation! When should we use `@reach/router`'s `navigate` vs Gatsby's `navigate`? It seems like we should always use `@reach/router`'s version, unless we know that something has changed on the server?
