### ISSUE TITLE
Unit cannot be used for conversion, so 16px is used. [pixrem]

### ISSUE THREAD

**Issue by nodox** [gatsbyjs/gatsby#2287]
How can I ignore this warning? I can't work on anything else until I can bypass this warning (or get it fixed).

```
src/themes/massively/css/main.css
undefined [undefined]
⚠  Unit cannot be used for conversion, so 16px is used. [pixrem]
```

**Comment by KyleAMathews** [comment]
This has something to do with your `main.css` file and not Gatsby. Perhaps try removing parts of the CSS until you narrow it down.

Perhaps the error can be improved but we use a pretty vanilla CSS setup so it's not likely anything we can fix here and would need to be fixed in an upstream project.

**Comment by nodox** [comment]
The webpack postcss loader is using `pixrem` and issuing plugin warnings. I found that you can configure these warnings to be turned off but I would need access to the webpack config.
```
config.stats = {
    warnings: false
}
```

How can I go about making my own gatsby/gatsby-cli (I'm not sure which one is actually responsible for CLI) fork so I can make the patch and use that for my `$ gatsby develop` commands? Or where can I find an exposed webpack.config within my gatsby project? Would `gatsby-config.js` be a makeshift place for additional options like this one?

**Comment by KyleAMathews** [comment]
Check out the docs page for that https://www.gatsbyjs.org/docs/add-custom-webpack-config/
