### ISSUE TITLE
Possible to do at runtime what Gatsby does for GraphQL queries at build time?

### ISSUE THREAD

**Issue by jcchingithub** [gatsbyjs/gatsby#22875]
Hi,

My team at work is trying to implement what we need within our new Gatsby-based website to use Contentful's Content Preview feature to preview our pages. Our high-level requirement is the following:
-add a dynamic Gatsby route of /preview/[pathname] to enable one to use Contentful's Content Preview feature at runtime (on-demand) to preview our pages (/[pathname]), the contents of which are stored in Contentful as "Page"-type entries that contain nested entries at various levels (that map to our Gatsby components).

Within Gatsby's gatsby-node.js, we're using a single GraphQL query to source the Contentful data for our pages at build time. Initially, we wanted to use Contenful's GraphQL Content API to query the data for our Contentful Content Preview pages at runtime. Unfortunately, our Contentful Content Preview GraphQL query (converted from our gatsby-node.js GraphQL query (32000+ bytes)) would still exceed the limit (8192 bytes) for a single Contentful GraphQL Content API query.

What's interesting, though, is that gatsby-node.js GraphQL queries are converted by Gatsby at build time to API queries that go through Contentful's (non-GraphQL) Content Delivery API. Does anyone know of a way to do at runtime what Gatsby does for gatsby-node.js GraphQL queries at build time?

(Otherwise, our last resort, for each Contentful Content Preview page, would be to recursively query each page's nested entries via Contentful's Content Delivery API and then transform the aggregated query results into the object structures that our components expect.)

My research via https://github.com/gatsbyjs/gatsby/issues seems to indicate that it is currently not possible to do at runtime what Gatsby does for GraphQL queries at build time:

Via https://www.google.com/search?q=site%3Agithub.com%2Fgatsbyjs%2Fgatsby%2Fissues+createPages+runtime
--------------------------------------------------------------------------------
https://github.com/gatsbyjs/gatsby/issues/10482
https://github.com/gatsbyjs/gatsby/issues/11966
https://github.com/gatsbyjs/gatsby/issues/17704

Via https://www.google.com/search?q=site:github.com/gatsbyjs/gatsby/issues+%22gatsby-source-contentful%22+runtime
--------------------------------------------------------------------------------
https://github.com/gatsbyjs/gatsby/issues/1538
https://github.com/gatsbyjs/gatsby/issues/10099
https://github.com/gatsbyjs/gatsby/issues/14138

However, maybe I'm missing something here and/or maybe someone knows something new about this.

Thanks in advance!

**Comment by ascorbic** [comment]
Hi. There seems to be two issues here. One is creating the dynamic client-only routes, and the other is querying the Gatsby data layer at runtime. The first is fine: see [the client only routes guide](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/) for this. The second is harder. The Gatsby GraphQL servber isn't available at runtime (though this is something that is under discussion). However even that wouldn't help, as it doesn't query Contentful's API during query resolution, but beforehand, so you'd be stuck with the same issue.

Looking at this from another direction, and sorry for the plug, but have you looked at [Gatsby Preview](https://www.gatsbyjs.com/preview/), which does seem like it would solve this. It works with Contentful by hitting a webhook when previewing, which updates the data layer in realtime, meaning you get a live preview. If you want to run it yourself you can run `gatsby develop` with the refresh endpoint enabled, and set Contentful up to hit your webhook in a similar way.

I'm going to close this issue so we can keep on top of them, but feel free to reopen it if this doesn't help.
