### ISSUE TITLE
Gatsby-Source-GraphQL: how to deal with .graphqlconfig files

### ISSUE THREAD

**Issue by romainbessugesmeusy** [gatsbyjs/gatsby#22886]
## Summary

I'd like to be know if there's a way to make my IDE understand Gatsby "fieldName" property in order to correctly map my queries.

We use "apiMG" as the "fieldName".

<img width="364" alt="Capture d’écran 2020-04-07 à 16 18 59" src="https://user-images.githubusercontent.com/3127404/78680209-80b1b900-78eb-11ea-81cf-9642ef55f68b.png">

And here's the .graphqlconfig content we use:
```json
{
  "name": "Pimcore",
  "schemaPath": "./pimcore.graphql",
  "extensions": {
    "endpoints": {
      "Remote Pimcore Endpoint": {
        "url": "...",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}
```

**Comment by vladar** [comment]
Gatsby constructs its own schema. So your existing remote schema won't work for IDE integration with Gatsby. You can try using `http://localhost:8000/___graphql` endpoint for your GraphQL config when developing Gatsby.

**Comment by romainbessugesmeusy** [comment]
Thank you so much. Will try immediately.
