### ISSUE TITLE
ugly to replace image links with html  in gatsby-remark-copy-linked-files

### ISSUE THREAD

**Issue by cecilpeng** [gatsbyjs/gatsby#22887]
## Description

two problems here:
1. the regexp is not exact for some special characters, eg .
2. the regexp should validate the full image tag

source:

![image](https://user-images.githubusercontent.com/3832621/78682010-0c453d00-7920-11ea-9810-00b1739cd4cf.png)

### Steps to reproduce

use html in the markdown file, and don't forget to prepare a image - 15857286868631.png

```html
<div>
    <img src="./15857286868631.png" />
    <img src="./15857286868631.png" />
</div>
```

### Expected result

it should do well with duplicated images. We can use parse5 to get a image node and then do a same logic.

### Actual result

What happened.
![image](https://user-images.githubusercontent.com/3832621/78682801-0a2fae00-7921-11ea-8620-d2ec2d4f3674.png)

### Environment

gatsby-remark-copy-linked-files@2.0.9 is ok, but 2.2.1 is broken. 2.0.9 replace the link with a hash suffix, which can avoid the problem

**Comment by LekoArts** [comment]
Hi, I don't understand what you're asking for. Could you please rephrase your request or write it out in more detail?
