### ISSUE TITLE
[gatsby-images] [gatsby-remark-images] Customizing html of a markdown to implement lazy-loading

### ISSUE THREAD

**Issue by grdpr** [gatsbyjs/gatsby#2288]
I would like to customize the html of a Markdown Post to implement lazy-loading. I need to add a class to the images and change the "src" attribute to "data-src".  I have tried directly in the markdown file `<img class="lazyload" data-src="…"/>` but it didn't work. Anyone has an idea how to make it? Thanks!

```
import React from "react"

class BlogPostTemplate extends React.Component {
  render() {
    const post = this.props.data.markdownRemark

    return (
      <div>
        <h1>{post.frontmatter.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: post.html }} />
      </div>
    )
  }
}

export default BlogPostTemplate

export const pageQuery = graphql`
query BlogPostBySlug($slug: String!) {
  markdownRemark(fields: { slug: { eq: $slug }}) {
    html
    frontmatter {
      title
    }
  }
}
`
```

**Comment by sebastienfi** [comment]
Have you looked at [gatsby-remark-images](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images) ?

**Comment by KyleAMathews** [comment]
I've always intended gatsby-remark-images to support lazy loading but haven't gotten there quite yet. Now that I've been exploring this more with https://using-gatsby-image.gatsbyjs.org/, I'd love to make it happen.

**Comment by roberpoldo** [comment]
@KyleAMathews  `gatsby-image` seems perfect! Thanks a lot! 
Is this working on top of gatsby-remark-images? How does it work to use it?

**Comment by sebastienfi** [comment]
@roberpoldo I believe it will be transparent, `gatsby-image` being a component called by `gatsby-remark-image` itself. But let's see :)

**Comment by KyleAMathews** [comment]
@roberpoldo the two are mostly unrelated. `gatsby-image` is a React component. `gatsby-remark-images` is a markdown transformer plugin that transformers markdown images into responsive images. 

So for markdown images, someone just needs to add support to gatsby-remark-images for lazy-loading. For `gatsby-image`, you can use that today. See the source code for the example for how to use it. I'll be writing some docs later today for it.

**Comment by roberpoldo** [comment]
@KyleAMathews I'm now using `gatsby-image` (v1.0.1) on my index page. It works great but the lazy-loading works only in Google Chrome and not in Safari (tested on v11.0)…

**Comment by roberpoldo** [comment]
More precision: the `gatsby-image`'s lazy-load is only working in Chrome in `gatsby develop`. When I make a build and serve it, the lazy-load doesn't work either in Chrome or Safari. It's displaying all the images of the page…

**Comment by KyleAMathews** [comment]
There's new versions which fix that.

**Comment by roberpoldo** [comment]
@KyleAMathews Thanks for this new version! Is there any -webkit fix to make` gatsby-image` working in Safari with the intersection observer?

**Comment by KyleAMathews** [comment]
You'll need to add a polyfill for the IntersectionObserver API. I haven't investigated this closely so can't offer much help there but would love to hear back from your research.

**Comment by roberpoldo** [comment]
`gatsby-image` is working in Safari now after a build using the [intersection-observer](https://www.npmjs.com/package/intersection-observer) polyfill package. Just have imported in the index.js and have added this trick in gatsby-node.js:
```
exports.modifyWebpackConfig = ({ config, stage }) => {
  if (stage === 'build-html') {
    config.loader('null', {
      test: /intersection-observer/,
      loader: 'null-loader'
    })
  }
}
```

**Comment by roberpoldo** [comment]
Anyone has an idea how to disable the blur effect option (base64) in the html markdown graphql query with `gatsby-remark-images`? I know how do it in the frontmatter but not in the body/html of a markdown. Is there a similar "tweak" as the frontmatter one in the query for the html?
like this one:
```
allMarkdownRemark(sort: { order: DESC, fields: [frontmatter___date] }) {
      edges {
        node {
          excerpt(pruneLength: 250)
          id
          frontmatter {
            title
            date(formatString: "YYYY")
            path
            caption
            cat
            client
            image {
              childImageSharp {
                responsiveSizes(maxWidth: 1200, quality: 80) {
                  aspectRatio
                  src
                  srcSet
                  sizes
                  originalImg
                }
              }
            }
          }
        }
```

**Comment by fk** [comment]
> So for markdown images, someone just needs to add support to gatsby-remark-images for lazy-loading.

@KyleAMathews I might be that someone 😍  – I'd love to have lazy loading gatsby-remark-images. I however fear that integrating gatsby-image like @sebastienfi wrote earlier

> I believe it will be transparent, `gatsby-image` being a component called by `gatsby-remark-image` itself.

might be a little over my head? I probably need some guidance/hint on how to approach this (as usual ;-D)…

**Comment by fk** [comment]
No worries! Understood…and :-/.

A shot in the dark (obviously not fully understanding what's happening here ;-D – layman wishful thinking): Could #3596, #3731 (#3732) change what you explained above in any way?

**Comment by KyleAMathews** [comment]
Maybe... but we'd need a gatsby-remark-image-component or something like that to change from adding `<img/>` to the markdown html to adding `<Image />`. Probably not worth it. Lazy loading is actually pretty easy.

**Comment by thomasboyt** [comment]
Went ahead and [hacked this into my blog](https://github.com/thomasboyt/loud-places/blob/7bca5da45f2b5c3ea676a2681be3a6809d47a53b/src/templates/blog-post.js#L9) and it seems to work okay ([example page](http://loudplaces.disco.zone/travel/europe-trip-edinburgh/)), though it's quite a bit less graceful than what you'd get from `gatsby-images` (e.g. doesn't properly handle cached images so there's an awkward bit where it flashes loaded->unloaded->loaded, runs only on the client so there's a bit of jank on initial load...). Would be great to have this as part of `gatsby-remark-images` in the future.

**Comment by jumpalottahigh** [comment]
@alexandernanberg Thanks for sharing your approach. I was just wondering if MDX would in that case be a bit simpler to set this up. Going down the rabbit hole :)

**Comment by 1kohei1** [comment]
Hi, I came across this issue and checked both solutions by @alexandernanberg and @thomasboyt. My solution takes hints from both of you. Let me share it!

I created a npm package [gatsby-remark-lazy-load](https://www.npmjs.com/package/gatsby-remark-lazy-load). This converts `img` tag generated by `gatsby-remark-images`to the format of [lazysizes](https://github.com/aFarkas/lazysizes/). 

Then, you load `lazysiezes` in the `gatsby-browser.js`. 

That's it! I'm not fully happy about the solution, but it does what I want to achieve. So, I am okay with this solution right now. You can find my repo [here](https://github.com/1kohei1/1kohei1).

Let me know if you have any suggestions!
