### ISSUE TITLE
Processing external images

### ISSUE THREAD

**Issue by algebrathefish** [gatsbyjs/gatsby#22888]
## Summary

I am taking a look at this https://www.gatsbyjs.org/packages/gatsby-plugin-remote-images/

The node type and path where my remote images are is not always the same. They are always called the same (mediaItemUrl) but the path is variable

Is it possible to achieve this? Thank you

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

As this is a community plugin I'd recommend opening an issue here:
https://github.com/graysonhicks/gatsby-plugin-remote-images

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by algebrathefish** [comment]
@LekoArts as this plug in is not the only option, I opened it here. I looked also into https://www.gatsbyjs.org/packages/gatsby-source-custom-api/ and this option https://www.gatsbyjs.org/docs/preprocessing-external-images/

So help with any to get started would be good.

Could you please open again?
