### ISSUE TITLE
Firefox breaks when moving to latest version of Gatsby (2.9.6 to 2.20.10)

### ISSUE THREAD

**Issue by KyeMaloy97** [gatsbyjs/gatsby#22890]
## Description

Updating our website (master branch) to the latest version of the npm packages breaks firefox as it begins to hang, which means the site cannot make of use of fixes and API changes.

The website is using Gatsby 2.9.6 but if I run `npm update gatsby` or just `npm update`, once it completes everything is fine on Safari and Chrome but Firefox hangs when the page loads and eventually pops up saying the page is causing the computer to slow down. Firefox will never sort it, so you have to stop the page and then it works as normal and the rest of the page pops in.

We have tried to troubleshoot the issue, but the fact it is working on Safari and Chrome tell us it's some Firefox specific issue, and the dev tools in Firefox aren't providing any extra details.

Additionally, running a `gatsby develop` ends with nothing loading on Firefox, the page is blank and nothing loads. Running `gatsby build && gatsby serve` lets a full view of the website load but a scroll results in white space showing instead of the rest of the website and none of the website is interactive, until the warning happens and you click "stop", not "wait" after which the website loads and can be used as normal. Clicking a link to a new page start the process again which tells me it might be something to do with the internal parts of the site like Gastby node etc.

### Steps to reproduce

I am unable to make a minimal project as I don't know what is causing the issue. However, if you clone https://github.com/appsody/website, and on master run `npm install` and see how the pages load fine on their older versions on Firefox, Chrome and Safari.

Then if you run `npm update`, then run `gatsby develop` or `gatsby build && gatsby serve` you will see that Firefox stops working completely.

### Expected result

Firefox should work as it did before with no issues.

### Actual result

Firefox is broken and something is causing the website to not load properly.

### Environment

Before `npm update`

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /Users/kyemaloy/.pyenv/shims/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.9.6 => 2.9.6 
    gatsby-plugin-client-side-redirect: 0.0.2 => 0.0.2 
    gatsby-plugin-google-analytics: ^2.1.0 => 2.1.0 
    gatsby-plugin-manifest: ^2.2.41 => 2.2.41 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-remove-trailing-slashes: ^2.1.15 => 2.1.15 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5 
    gatsby-remark-autolink-headers: ^2.1.10 => 2.1.10 
    gatsby-remark-embed-youtube: 0.0.7 => 0.0.7 
    gatsby-remark-images: ^3.1.28 => 3.1.28 
    gatsby-source-filesystem: ^2.1.0 => 2.1.0 
    gatsby-transformer-remark: ^2.5.0 => 2.5.0 
    gatsby-transformer-yaml: ^2.2.4 => 2.2.4 
  npmGlobalPackages:
    gatsby-cli: 2.8.29

after `npm update`

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /Users/kyemaloy/.pyenv/shims/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.9.6 => 2.20.10
    gatsby-plugin-client-side-redirect: 0.0.2 => 0.0.2
    gatsby-plugin-google-analytics: ^2.1.0 => 2.2.2
    gatsby-plugin-manifest: ^2.2.41 => 2.3.3
    gatsby-plugin-react-helmet: ^3.0.12 => 3.2.1
    gatsby-plugin-remove-trailing-slashes: ^2.1.15 => 2.2.1
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.4.5 => 2.5.3
    gatsby-remark-autolink-headers: ^2.1.10 => 2.2.1
    gatsby-remark-embed-youtube: 0.0.7 => 0.0.7
    gatsby-remark-images: ^3.1.28 => 3.2.1
    gatsby-source-filesystem: ^2.1.0 => 2.2.2
    gatsby-transformer-remark: ^2.5.0 => 2.7.1
    gatsby-transformer-yaml: ^2.2.4 => 2.3.1
  npmGlobalPackages:
    gatsby-cli: 2.8.29

**Comment by LekoArts** [comment]
Can you share a live URL? Have you updated Firefox to the latest version? What errors are you seeing specifically? Does this only happen on your project or also on e.g. https://github.com/gatsbyjs/gatsby-starter-hello-world ?

**Comment by KyeMaloy97** [comment]
The website is live at https://appsody.dev and it happens specifically on our project. Error wise, all that happens if firefox hangs until you cancel loading, so it seems something breaks when updating the packages. Firefox is fully up to date too, as are Safari and Chrome but Firefox is the only one with an issue.
