### ISSUE TITLE
Error when adding Facebook Messenger Chat to site

### ISSUE THREAD

**Issue by ROODAY** [gatsbyjs/gatsby#22912]
## Description
I'm trying to add [this feature](https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/) from Facebook that lets you integrate a page's Messenger chat directly into a website. I did so by creating the following component:
```
import React from "react";

class MessengerChat extends React.Component {
  componentDidMount() {
    window.fbAsyncInit = function() {
      FB.init({ //eslint-disable-line
        xfbml: true,
        version: 'v6.0'
      });
    };

    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  }

  render() {
    return (
      <>
        <div id="fb-root" />
        <div
          className="fb-customerchat"
          attribution="setup_tool"
          page_id="XXXXXXXXXXXX"
          theme_color="#2f8dff"
          logged_in_greeting="Hi there! Have any questions?"
          logged_out_greeting="Hi there! Have any questions?" />
      </>
    );
  }
} 

export default MessengerChat;
```

I then include this component in my layout like so:
```
const Layout = withTheme((props) => (
  <>
    <GlobalStyle theme={props.theme} />
    <Header />
    <ContentWrapper>{props.children}</ContentWrapper>
    <MessengerChat />
    <Footer/>
  </>
));
```

All my pages are wrapped in this layout so the chat appears in all of them. However, including this plugin seems to break routing, as when I click a Gatsby Link I get the following error: `TypeError: Cannot read property 'getElementsByTagName' of null at navigation.js:174`, and nothing renders on the page (just a blank page). Here's the specific line that gets the error:
```
  171 | if (document.title) {
  172 |   pageName = document.title
  173 | }
> 174 | const pageHeadings = document
  175 |   .getElementById(`gatsby-focus-wrapper`)
  176 |   .getElementsByTagName(`h1`)
  177 | if (pageHeadings && pageHeadings.length) {
```

Removing the MessengerChat component from my layout fixes this issue, but I'd like to include it. However I have no clue why it's breaking the routing (going to a page URL directly, or refreshing after getting the error works).

### Steps to reproduce
Include the above component on your pages' layout and try clicking a Gatsby Link to another page.

### Environment
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /c/Python27/python
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: ^2.19.45 => 2.19.45
    gatsby-image: ^2.2.44 => 2.2.44
    gatsby-plugin-google-analytics: ^2.1.38 => 2.1.38
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.2.48 => 2.2.48
    gatsby-plugin-offline: ^3.0.42 => 3.0.42
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.1.24 => 3.1.24
    gatsby-plugin-sharp: ^2.4.13 => 2.4.13
    gatsby-plugin-sitemap: ^2.2.30 => 2.2.30
    gatsby-plugin-styled-components: ^3.2.1 => 3.2.1
    gatsby-source-filesystem: ^2.1.56 => 2.1.56
    gatsby-styled-components-dark-mode: ^1.1.1 => 1.1.1
    gatsby-transformer-sharp: ^2.3.19 => 2.3.19
```

Also if it helps here's the full log output from my console (it's really long though):
[localhost-1586319860749.log](https://github.com/gatsbyjs/gatsby/files/4448173/localhost-1586319860749.log)

**Comment by herecydev** [comment]
Can you [create a reproduction of the problem](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)?

**Comment by ROODAY** [comment]
I'm actually having trouble creating a reproduction as I ran into another issue, for some reason the FB chat plugin won't re-init when going to a new page. After looking into their source code (as best as I could since it's obfuscated), it seems there are some flags set to make sure it won't run multiple times. I can't get around this, so I think the best thing to do would be a different approach. Is there a way in Gatsby to keep a component mounted the whole time while navigation goes to different pages?

**Comment by herecydev** [comment]
> Is there a way in Gatsby to keep a component mounted the whole time while navigation goes to different pages?

Sure, [wrapRootElement](https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement)

**Comment by ROODAY** [comment]
Thanks! I actually ended up using [wrapPageElement](https://www.gatsbyjs.org/docs/browser-apis/#wrapPageElement). I originally used it to wrap my pages with a Layout and had the Messenger Chat component in the Layout, but strangely although it worked under `gatsby develop`, under `gatsby serve` all my CSS was messed up, I finally got it working by keeping the Layout component inside my individual page components, and via this `gatsby-browser.js`:
```
const React = require("react");
const MessengerChat = require("./src/components/MessengerChat").default;

exports.wrapPageElement = ({ element, props }) => (
  <React.Fragment {...props}>
    {element}
    <MessengerChat />
  </React.Fragment>
);
```

**Comment by hronchetti** [comment]
Using the same logic posted by @ROODAY I get this console warning

`index.js:2177 Warning: Invalid prop `path` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
    in Fragment (at gatsby-browser.js:7)
    in PageRenderer (at query-result-store.js:86)
    in PageQueryStore (at root.js:56)
    in RouteHandler (at root.js:78)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by EnsureResources)
    in ScrollContext (at root.js:69)
    in RouteUpdates (at root.js:68)
    in EnsureResources (at root.js:66)
    in LocationHandler (at root.js:124)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:123)
    in Root (at root.js:132)
    in StaticQueryStore (at root.js:138)
    in _default (at app.js:94)`

Is there anything we can do about it?

**Comment by herecydev** [comment]
Don't spread props on a fragment, it doesn't make any sense as a fragment is meant to be an empty element.

**Comment by hronchetti** [comment]
Solved this, the Gatsby Browser documentation actually says props don't necessarily need to be passed: https://www.gatsbyjs.org/docs/browser-apis/#wrapPageElement

**Comment by jlisbz** [comment]
@ROODAY @herecydev @hronchetti Thanks a lot. This fixed the issue for my gatsby / facebook messenger integration.
