### ISSUE TITLE
How to create a component with paginated data

### ISSUE THREAD

**Issue by davidshare** [gatsbyjs/gatsby#22910]
I am working on a blog using Gatsby. In the index page of my blog, I display a list of all my articles. However, I want only 10 articles excerpts to be displayed per time.

The solution provided in the documentation requires that I use Gatsby-node to automatically generate pages. This doesn't work for my use case.

The list on my landing page id displayed using a component. How can I display paginated data on the index page using the component for my article list.

**Comment by herecydev** [comment]
Hi David 👋 

If you want a paginated component then pass the list of articles into your index page and into your component. At that point it just becomes a standard react problem to solve

**Comment by LekoArts** [comment]
Thank you for opening this!

As Dan said: If you don't want to create individual pages for each paginated page it's a React problem to solve.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
