### ISSUE TITLE
`formatError` is deprecated and replaced by `customFormatErrorFn`. It will be removed in version 1.0.0. [Error: ENOENT: no such file or directory, open 'G:\PROJET\images\2020-04-08T21:12:27.377Z-duck.jpg'] {   errno: -4058,   code: 'ENOENT',   syscall: 'open',

### ISSUE THREAD

**Issue by maschine13** [gatsbyjs/gatsby#22949]
when i'm trying to upload an image i got this ! and here is my Front End code ....
finishEditHandler = postData => {
    this.setState({
      editLoading: true
    });
    const formData = new FormData();
    formData.append('image', postData.image);
    if (this.state.editPost) {
      formData.append('oldPath', this.state.editPost.imagePath);
    }
    fetch('http://localhost:8080/post-image', {
      method: 'PUT',
      headers: {
        Authorization: 'Bearer ' + this.props.token
      },
      body: formData
    })
      .then(res => res.json())
      .then(fileResData => {
        const imageUrl = fileResData.filePath;
        let graphqlQuery = {
          query: `
          mutation {
            createPost(postInput: {title: "${postData.title}", content: "${
            postData.content
          }", imageUrl: "${imageUrl}"}) {
              _id
              title
              content
              imageUrl
              creator {
                name
              }
              createdAt
            }
          }
        `
        };

**Comment by LekoArts** [comment]
Thank you for opening this!

This won't be an issue with Gatsby but with your React code. I'd suggest visiting the https://www.reactiflux.com/ Discord and asking there or creating a question on StackOverflow.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
