### ISSUE TITLE
The correct way to update ssr-rendered links on hydration

### ISSUE THREAD

**Issue by orshick** [gatsbyjs/gatsby#22948]
## Summary

I want certain links to render a default href on server render, but update to a link to the specific operating system the visitor is using. I wanted to accomplish this by returning the url via a function that tests the useragent on hydration. While the inner content of the html updates on hydration, the "to" value does not, even though they are both using the same value.

Here is a test page that displays this: https://gatsby-ssr-dynamic-link-handling.netlify.com/

This can be verified by going into responsive mode in dev-tools and refreshing the page. The links at the bottom all say `https://www.andoird.com` but the actual href attribute remains `https://www.default.com`, even though in the jsx they use the same value

All the relevant code is right in the [index.js page component](https://github.com/orshick/gatsby-ssr-dynamic-link-handling/blob/master/src/pages/index.js). I tried to set the data 3 different ways, but all had the same outcome.

## Relevant information

To reproduce locally, clone [this repository](https://github.com/orshick/gatsby-ssr-dynamic-link-handling) and run 'npm run build', then 'gatsby serve'

All the relevant code is in the index.js page component.

### Environment (if relevant)
 Here is my system, though the results are the same when I build on netlify.

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
  Binaries:
    Node: 10.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12 
    gatsby-image: ^2.3.1 => 2.3.1 
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3 
    gatsby-plugin-offline: ^3.1.2 => 3.1.2 
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1 
    gatsby-plugin-sharp: ^2.5.3 => 2.5.3 
    gatsby-source-filesystem: ^2.2.2 => 2.2.2 
    gatsby-transformer-sharp: ^2.4.3 => 2.4.3

**Comment by pieh** [comment]
The way hydration works is it react expect the first render in the browser to match exactly what is returned by the "server"/.html file. Check https://reactjs.org/docs/react-dom.html#hydrate :

> React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them.

As to how to workaround this - there is also note for this in react documentation:

> If you intentionally need to render something different on the server and the client, you can do a two-pass rendering. Components that render something different on the client can read a state variable like this.state.isClient, which you can set to true in componentDidMount(). This way the initial render pass will render the same content as the server, avoiding mismatches, but an additional pass will happen synchronously right after hydration. Note that this approach will make your components slower because they have to render twice, so use it with caution.

**Comment by orshick** [comment]
Thanks for your reply @pieh, this is indeed very relevant information. However the documentation is pretty light on explaining how to actually solve this. All they say is to use a state variable that gets changed on componentDidMount. I tried to replicate this with useLayoutEffect (which I understand to be the functional component equivalent) to update the link value but still the href is set to the initial value. Could you help point me in the direction for solving this? Also, is there a way to encapsulate that logic into a hook that updates itself on hydration, which I could just import into components and use?

**Comment by pieh** [comment]
Looking at your recent changes - https://github.com/orshick/gatsby-ssr-dynamic-link-handling/blob/115d462bbd00f5a69e690c4dbfce2d58a954cfcf/src/pages/index.js#L38-L41

The problem here is that `useState` use `getPlatformSpecificLink()` as initial state value. For this to work - this should always use same value you get in SSR as initial one - so in this case it should be:
`const [link1, setLink1] = React.useState(`https://www.default.com`)` (might need to restructure code a bit, so you don't use literal value, but have some function like `getDefaultLink` or so)

> Also, is there a way to encapsulate that logic into a hook that updates itself on hydration, which I could just import into components and use?

You could do something like this to create custom hook:

```js
const useBrowserSpecificLink = (getterFunction, ssrValue) => {
  const [link, setLink] = React.useState(ssrValue)

  React.useLayoutEffect(() => setLink(getterFunction()), [])

  return link
}
```

and then use like that:

```js
  const link3 = useBrowserSpecificLink(
    getPlatformSpecificLink,
    `https://www.default.com`
  )
```

**Comment by orshick** [comment]
Thanks a lot @pieh! Updated the repo with this this hook and now it does indeed work.

Curious though, is this just a quirk of how server rendering work for react, or something that makes sense from the perspective of someone who only deals with the public api for react? So odd to me that the text value of a component would update on hydration, but not the attributes. And odd that we have to recreate the server conditions on the client-side to make it work. This completely breaks my understanding of how react reconciles data.

**Comment by pieh** [comment]
I don't have a lot of context on internals of React (I mostly know about React public APIs and gotchas like that when it comes to hydration), so can't exactly explain why it works this way other than to quote react docs ;) 
> This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.

This is for sure trade-off that React team decided to do minimize performance impact for initial render (when used together with "server-side rendering"). This in particular impacts "time-to-interactive" metric (less work that has to be done on visitor machine). I do trust React team judgement on this - they have whole lot more data on this than I have.

**Comment by orshick** [comment]
Understood. Thanks again @pieh !

**Comment by pieh** [comment]
I'll close the issue as resolved so it's easier for us to triage active tickets. Stay safe @orshick!
