### ISSUE TITLE
Rendering Issue Chrome Canary

### ISSUE THREAD

**Issue by colbyfayock** [gatsbyjs/gatsby#22951]
## Description
I'm having an issue when hard-refreshing certain pages in Chrome Canary, the rendering of the page is inconsistent and just kind of weird. Elements are printed multiple times in what seems to be somewhat random positions beyond the actual expected position. It seems to only be happening in Canary from what I can tell.

It appears to happen intermittently but for me the majority of times.  If you notice in this gif below, when the page looks messed up, it's when I hard refresh (CMD+Shift+R). When it looks normal, its when I refresh normally (CMD+R).

![Screen Capture on 2020-04-08 at 18-51-55](https://user-images.githubusercontent.com/1045274/78840930-1459b700-79ca-11ea-994e-fc1a03494eca.gif)

This is also happening on my team's website: https://www.element84.com/blog/ - I'm not sure if that's coincidental or if it's something specific I'm doing.

I was however not able to reproduce this on the Gatsby blog.

My website is deployed to Netlify, my team's site is deployed to S3 + Cloudfront.

You can find my full source here if it helps: https://github.com/colbyfayock/colbyfayock

Couldn't seem to find anything related but maybe I just don't know the right thing to search for. Let me know if I can provide any additional information. I appreciate your time.

### Steps to reproduce
This appears to only happen on Chrome Canary. I was able to confirm others were able to reproduce this and I can NOT reproduce this on Chrome stable. Steps:
* Load up a page with a list of posts
* Hard refresh the page (might take a few times)

### Expected result
![image](https://user-images.githubusercontent.com/1045274/78840586-2d159d00-79c9-11ea-8a7a-fec4446414bc.png)

### Actual result
![image](https://user-images.githubusercontent.com/1045274/78840555-166f4600-79c9-11ea-9f60-bb1d7ebafdb6.png)

### Environment
```
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 74.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.14 => 2.20.14
    gatsby-plugin-google-marketing-platform: ^0.1.20 => 0.1.20
    gatsby-plugin-netlify-cms: ^4.2.2 => 4.2.2
    gatsby-plugin-postcss: ^2.2.1 => 2.2.1
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1
    gatsby-plugin-resolve-src: ^2.0.0 => 2.0.0
    gatsby-plugin-sass: ^2.2.1 => 2.2.1
    gatsby-plugin-webmention: ^0.2.0 => 0.2.0
    gatsby-source-filesystem: ^2.2.2 => 2.2.2
    gatsby-transformer-remark: ^2.7.1 => 2.7.1
```

**Comment by herecydev** [comment]
I would be utterly surprised if this was a gatsby issue. The nature of Chrome canary is highly experimental/unstable and shouldn't be relied upon

**Comment by pieh** [comment]
We will likely not investigate this problem if it's chrome canary only, as per https://www.chromium.org/getting-involved/dev-channel :
> Canary build: Canary builds are the bleeding edge. Released daily, this build has not been tested or used, it's released as soon as it's built.

If similar behaviour happens in "more stable" releases - like Beta channel, then we will investigate

**Comment by colbyfayock** [comment]
Sounds good - thanks

**Comment by LekoArts** [comment]
Will close this for now :) As my colleague said, if you see this in stable releases, please let us know. Thanks!
