### ISSUE TITLE
Is it possible to use a nested router inside of a layout component?

### ISSUE THREAD

**Issue by DRiFTy17** [gatsbyjs/gatsby#22950]
## Summary
Currently I have a layout component that contains my site header and side navigation menu. Each page loads within the body of the layout correctly.

I'm trying to now create a tabbed interface within one of my MDX pages.

Is it possible to use a nested router, nested layout, or any other mechanism to avoid reloading the whole body content (including the tabs) when changing pages?

I'm hoping that I can define sub-pages as MDX as well, and reference those as content to load for each of the tabs without reloading my main layout component, or current surrounding page content. Just curious if this is possible or if I should try to pursue a different approach.

**Comment by pieh** [comment]
From the description it feels like [`gatsby-plugin-layout`](https://www.gatsbyjs.org/packages/gatsby-plugin-layout/) _might_ solve the problem you are describing - per the plugin description:
> This can be helpful for:
> - Persisting layout between page changes for e.g. animating navigation
> - Storing state when navigating pages

With this plugin, the layout (component that wraps page templates) stays mounted and it doesn't get unmounted and remounted on page changes

**Comment by DRiFTy17** [comment]
@pieh Thanks for the idea! So, I am currently using that plugin to place a wrapper component (`<AppLayout>`) around all pages, which works very well (sorry, I should have noted that in my question). I also am using `gatsby-plugin-mdx` and its `defaultLayouts` option to set a layout around my MDX page content (`<PageLayout>`). When switching pages, the content within my `<AppLayout>` is swapped out with the new `<PageLayout>` for the next MDX page as expected. I'd like to have a tab component within a specific MDX page, that allows for switching between other MDX page fragments without reloading the full content of that specific page.

Here is my current layout hierarchy to help visualize (if you have any suggestions about approaching this in a different way, I am definitely open to that as well!):

```html
<Root>
    /* AppLayout is static around ALL pages and contains header, navigation, and footer */
    <AppLayout>
        /* PageLayout is the wrapper around each MDX page content (which I want to contain the tabs) */
        <PageLayout>
            {MDX page content}
        </PageLayout>
    </AppLayout>
</Root>
```

In the above example, `{MDX page content}` contains the tab component. Upon switching tabs, it reloads the whole thing, which I expect, but I'm not quite sure how to adjust this to achieve what I'm looking for... Appreciate the help!
