### ISSUE TITLE
Gatsby Content Preview

### ISSUE THREAD

**Issue by arhoy** [gatsbyjs/gatsby#22957]
IN the Gatsby Source Contentful Plugin mentioned here 
https://www.gatsbyjs.org/packages/gatsby-source-contentful/

How do I do the following to create a gatsby config instance for using the preview and for the production environment when the host is not required for production
// In your gatsby-config.js
```
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: `your_space_id`,
        // Learn about environment variables: https://gatsby.dev/env-vars
        accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
        host: `preview.contentful.com`,
      },
    },
  ],
}

```

I have tried to modify my config file like so, so I can use it for both envir
```
    {
      resolve: `gatsby-source-contentful`,

      options: {
        spaceId: process.env.CONTENTFUL_ID,
        accessToken:
          process.env.NODE_ENV === 'production'
            ? process.env.CONTENTFUL_ACCESS_TOKEN
            : process.env.CONTENTFUL_PREVIEW_ACCESS_TOKEN,
        host:
          process.env.NODE_ENV === 'production'
            ? 'https://rentalyeg.com'
            : 'preview.contentful.com',
      },
    },
```
Pleaes advise

**Comment by LekoArts** [comment]
Thank you for opening this!

As laid out in the options (https://www.gatsbyjs.org/packages/gatsby-source-contentful/#configuration-options) the default for `host` is `cdn.contentful.com` - so you can use that or the production value. Or you only add the `host` option for development. It's JavaScript so you can do it multiple ways.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
