### ISSUE TITLE
[gatsby-remark-prism]: Additional line numbers kept after line removal

### ISSUE THREAD

**Issue by miles-crighton** [gatsbyjs/gatsby#22962]
## Description
This issue occurs when using the [gatsby-remark-prism](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-prismjs) plugin to process code-fences in markdown.

When enabling both line numbers and commented directives (ie. //highlight-start) within code-fences, the plugin's [line number generator](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/add-line-numbers.js) does not compensate for lines removed by the commented directives.

This leads to a discrepancy between the commented lines removed by the directive handler and the line number spans added beforehand, resulting in scrollable overflow of empty lines in the output code-fence.

This obviously does not occur when either the code-fence is not selected to use line numbers in the header (\`\`\`js{numberLines: true}) or the showLineNumbers: false option is passed to `gatsby-remark-prismjs` in `gatsby-config.js`. Rather, when both line numbers and comment directives are used in conjunction with one another.

#### Example 
Input:
```js
1: function test() {
2:   // highlight-start
3:  return "This is a test"
4:   // highlight-end
5: }
```

Output (* indicating line highlighting):
```js
1: function test() {
2:  *return "This is a test"*
3: }
4:  
5: 

```

I've tested this for both highlighting and hiding directives. To get a better understanding of what's happening in the directive handler, check out [this part of my proposed solution](https://github.com/gatsbyjs/gatsby/compare/master...miles-crighton:remark-prism-highlighting#diff-5fd2ab3304a334d4977bdcb27e492e3e), described later in this issue.

### Steps to reproduce

I've generated a minimised test case on [Github](https://github.com/miles-crighton/gatsby-prism-issue)

This includes 3 test cases, each using different directives. One for highlighting, one for hiding and a final for a combination of multiple.

**Code sandbox**

[Online sandbox](https://codesandbox.io/s/github/miles-crighton/gatsby-prism-issue)

**Run it locally**

`git clone https://github.com/miles-crighton/gatsby-prism-issue.git` to a local folder
then run `gatsby develop` find the test cases at `localhost:8000`

### Expected result

![Screenshot 2020-04-09 at 12 06 11](https://user-images.githubusercontent.com/39874506/78888966-a6a99b80-7a5a-11ea-81ea-913781afce84.png)

### Actual result
![gatsby-prism-issue](https://user-images.githubusercontent.com/39874506/78888949-9f828d80-7a5a-11ea-8a5b-720ead6980c7.gif)

### Environment
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 66.0.4
    Safari: 13.0.5
  npmGlobalPackages:
    gatsby-cli: 2.11.5

# Proposed solution
I've developed a naive solution [in this branch](https://github.com/gatsbyjs/gatsby/compare/master...miles-crighton:remark-prism-highlighting).

This involves adding an additional action to the directives handler ([`directives.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/directives.js)) that keeps track of lines removed during processing. The count of `linesRemoved` is then passed back through [`highlight-code.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/highlight-code.js) and then once again to [`index.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/index.js). This value can then be fed into the line number generator to compensate for the lines removed during directive processing. Essentially this solution tries to allow feedback from the code-highlighter to be provided to the line number generator as currently, they run independently from one another. On the one hand, the independent modularity is good, but with the addition of comment directives outside of prismjs there needs to be some connection between components so that the additional features are being recognised at each part of the plugin. 

The alternative solution I initially considered involved performing an additional round of directive handling independently within `add-line-numbers.js` but ultimately the solution described above sounded more robust and required less unneccesary duplication.

Due to the fact that I'm changing the main return of `directives.js` and `highlight-code.js` to an object composed of both the highlighted code and total lines removed, **this will cause the currently implemented tests to fail, [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/__tests__/directives.js) and [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/__tests__/highlight-code.js)**. Ideally, I'd love to hear a better solution for passing `linesRemoved` to [`add-line-numbers.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/add-line-numbers.js) Also I'd like to know if this will have any unintended side-effects that I haven't seen.

If any maintainers have suggestions or comments on how to move forward with this issue or how to modify/create the solution feel free.

Thanks for taking the time to check this out.

**Comment by pieh** [comment]
Hey - feel free to open "draft" pull request with your current code changes - at very least we will get bit more insight into those failing tests (other just the information that those fail)

Depending on how those tests fail - we can either fix up tests to account for the code changes or if the failing tests just mean that there is unintended behaviour changes it would just be easier to follow the code.

That said - as you moved highlighting before adding line numbers - is it possible to not use `node.value` for line numbers and instead make it to use highlighted code? (might need changes to implementation of `addLineNumbers` as we would operate on html markup at that point and not on source text directly)

**Comment by miles-crighton** [comment]
Thanks for your input @pieh :)

I've created a pull request implementing your suggestion. This shouldn't break as many tests as the first solution, check it out here #23031
