### ISSUE TITLE
dynamic route e.g hero/:id

### ISSUE THREAD

**Issue by softchris** [gatsbyjs/gatsby#22988]
## Summary

Some routes are easy to create like for example

`/pages/heroes.js`

That becomes `/pages/heroes`

However, if I wanted to create `/hero/:id` I would need to go through a whole lot more

currently, I need to add the following to `gatsby-node.js`

```
/**
 * Implement Gatsby's Node APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/node-apis/
 */
const path = require('path');

// You can delete this file if you're not using it
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions;
  console.log('path', page.path);

  if (page.path.match(/\/hero\/?$/)) {
    console.log('creating page ', '/hero/:id');
    createPage({
      path: '/hero/:id',
      matchPath: "/hero/*",
      component: path.resolve('src/pages/hero.js')
    })
  }
}
```

and have my hero.js component parse out the `id` like so:

```
import React from "react"

export default ({ location }) => {
  // parse hero and dig out 
  console.info('location', location);
  const { groups: { id } } = location.href.match(/\/hero\/(?<id>\d+)/);
  console.log('id', id);
  return (
    <div>hero</div>
  )
}
```

I'm sure there must be either a convention-based way to do this e.g creating something like this

```
/pages
  /hero
   _id.js
```

Or maybe there's a plugin that solves this?

**Comment by jzabala** [comment]
I think what you want are some client-only routes https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/

**Comment by LekoArts** [comment]
Client-only routes is not correct here.

---

What you're requesting is something that is currently not available. We plan on adding this in the near future but for now you'll have to go the route you laid out.
