### ISSUE TITLE
Is it possible to  disable auto withPrefix at Link component by manual

### ISSUE THREAD

**Issue by suziwen** [gatsbyjs/gatsby#22989]
Is it possible to disable auto withPrefix at Link component by manual?

just like this code

```
<Link to={'link'} disablePrefix={true}>link</Link>
```

## why need this feature?

I use `gatsby-plugin-mdx` , and need to rewrap `a` component to `Link` with custom style. When building with the prefix path, the link in mdx is broken.

The demo [repo](https://github.com/suziwen/testgatsbylink)

```
gatsby new testgatsbylink suziwen/testgatsbylink
cd testgatsbylink
gatsby build --prefix-paths
gatsby serve --prefix-paths
```

goto http://localhost:9000/testlink
you will see `test` link is broken. The `href` value becomes `http://localhost:9000/testlink/testlink/link` .

**Comment by vladar** [comment]
Maybe I am missing something but have you tried this:

```jsx
<Link to={'/link'}>link</Link>
```

**Comment by suziwen** [comment]
The Link's `to` value is from mdx,  which is already `withPrefix`.  If I want to rewrap `a` component to `Link` with custom style, and `Link` component doesn't have the option to disable `withPrefix`, I need manually remove the prefix path of  `to` value. 

``` javascript
const StyleLink = ({href, children, ...props})=>{
  const to = props.to || href
  return (
    <Link
      {...props}
      to={to}
      activeClassName="active"
    >
      {children}
    </Link>
  )
}

const components = {
  a: StyleLink
}

export default ()=> {
  return (
    <div>
      <MDXProvider components={components}>
        <Content />
      </MDXProvider>
    </div>
  )
}
```

**Comment by herecydev** [comment]
Related: #23901

**Comment by vladar** [comment]
@blainekasten what do you think about this?
