### ISSUE TITLE
v2.20.15 causes 404

### ISSUE THREAD

**Issue by barbalex** [gatsbyjs/gatsby#22996]
## Description

Updating from v2.20.14 to v2.20.15 causes the site to fail: 
<img width="461" alt="2020-04-10_12h11_06" src="https://user-images.githubusercontent.com/669783/78983405-6e6e8f80-7b24-11ea-80cc-71e677d52c00.png">

This does not happen if your cache has not (yet) replaced index.html. So this error is rather hard to notice: To me it seemed that my app was working fine - while users were telling me they encountered a blank page.

### Steps to reproduce

Not sure if this is universal but: 
- take a working app using v2.20.14
- update gatsby to v2.20.15
- build and publish
- empty the cache for your app
- visit your app

### Expected result

The app should work

### Actual result

Blank page with above error. Also: index.html seems to point to a script called `commons.js`. Which does not exist:
<img width="214" alt="2020-04-10_12h15_45" src="https://user-images.githubusercontent.com/669783/78983770-2308b100-7b25-11ea-8439-825e438bec29.png">

Example project using v2.20.15: https://apflora-cz9davoh5.now.sh/
Same project using v2.20.14: https://apflora-ngrdihq51.now.sh/

Downgrading v2.20.15 to v2.20.14 solved the issue for me.

### Environment

```
$ yarn run gatsby info --clipboard
yarn run v1.21.1
$ C:\Users\alexa\apf2\node_modules\.bin\gatsby info --clipboard

  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 13.7.0 - C:\Users\alexa\AppData\Local\Temp\yarn--1586513843303-0.6222992253623871\node.CMD
    Yarn: 1.21.1 - C:\Users\alexa\AppData\Local\Temp\yarn--1586513843303-0.6222992253623871\yarn.CMD
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: 2.20.14 => 2.20.14
    gatsby-image: 2.3.2 => 2.3.2
    gatsby-plugin-create-client-paths: 2.2.1 => 2.2.1
    gatsby-plugin-eslint: 2.0.8 => 2.0.8
    gatsby-plugin-manifest: 2.3.3 => 2.3.3
    gatsby-plugin-offline: 3.1.2 => 3.1.2
    gatsby-plugin-react-helmet: 3.2.1 => 3.2.1
    gatsby-plugin-sharp: 2.5.4 => 2.5.4
    gatsby-plugin-styled-components: 3.2.1 => 3.2.1
    gatsby-plugin-typography: 2.4.1 => 2.4.1
    gatsby-plugin-web-font-loader: 1.0.4 => 1.0.4
    gatsby-remark-autolink-headers: 2.2.1 => 2.2.1
    gatsby-remark-copy-linked-files: 2.2.1 => 2.2.1
    gatsby-remark-embed-video: 2.0.1 => 2.0.1
    gatsby-remark-emojis: 0.4.2 => 0.4.2
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: 3.2.2 => 3.2.2
    gatsby-remark-images-medium-zoom: 1.5.0 => 1.5.0
    gatsby-source-filesystem: 2.2.2 => 2.2.2
    gatsby-transformer-remark: 2.7.1 => 2.7.1
    gatsby-transformer-sharp: 2.4.4 => 2.4.4
```

**Comment by barbalex** [comment]
The weird thing is: This does not seem to happen in every project. I have another project that works perfectly fine using v2.20.15. Here index.html looks like this:
<img width="508" alt="2020-04-10_12h24_26" src="https://user-images.githubusercontent.com/669783/78984322-41bb7780-7b26-11ea-831d-3cd65d3ce79c.png">

**Comment by barbalex** [comment]
Hm. I now rebuilt the project using v2.20.15 and got a working version: https://apflora-ozge59nxa.now.sh

So maybe this was some random error during the build process?

**Comment by LekoArts** [comment]
Thank you for opening this!

I updated 10 sites or so to `>2.20.15` yesterday and haven't noticed any problems at all (built on Gatsby Cloud). Maybe you had incomplete build artifacts and/or something wonky with the service worker happened.

I'll close this for now then as it appears to work again but if you find yourself in this situation again please let us know. Thanks!
