### ISSUE TITLE
warn Error persisting state: EXDEV: cross-device link not permitted, rename

### ISSUE THREAD

**Issue by xBLADEx** [gatsbyjs/gatsby#23010]
## Summary
after npm run develop, this warning continues to happen.
## Relevant information
Windows 10, Cmder terminal

### Environment (if relevant)
"dependencies": {
    "gatsby": "^2.20.12",
    "gatsby-image": "^2.3.1",
    "gatsby-plugin-manifest": "^2.3.3",
    "gatsby-plugin-offline": "^3.1.2",
    "gatsby-plugin-react-helmet": "^3.2.1",
    "gatsby-plugin-sharp": "^2.5.3",
    "gatsby-source-filesystem": "^2.2.2",
    "gatsby-source-wordpress": "^3.2.3",
    "gatsby-transformer-sharp": "^2.4.3",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^5.2.1"
  },

**Comment by vladar** [comment]
Looks like we already have a report about this: #22999

So Let's track it there. Closing this one as a duplicate.
