### ISSUE TITLE
What's the reason to prefix client-side env vars with GATSBY_

### ISSUE THREAD

**Issue by shavidzet** [gatsbyjs/gatsby#23013]
Some hours I tried to configure what was happening, after diving in documentations and some research I found that:

> In addition to these Project Environment Variables defined in .env.* files, you could also define OS Env Vars. OS Env Vars which are prefixed with GATSBY_ will become available in browser JavaScript.

So my question is why is it necessary to prefix with `GATSBY_` and my suggestion is about ability to configure if someone wants to use vars in client side without specific prefix.

**Comment by jzabala** [comment]
I think [React documentation](https://create-react-app.dev/docs/adding-custom-environment-variables/) has a great explanation for this practice.

> Note: You must create custom environment variables beginning with REACT_APP_. Any other variables except NODE_ENV will be ignored to avoid accidentally exposing a private key on the machine that could have the same name.

**Comment by shavidzet** [comment]
> I think [React documentation](https://create-react-app.dev/docs/adding-custom-environment-variables/) has a great explanation for this practice.
> 
> > Note: You must create custom environment variables beginning with REACT_APP_. Any other variables except NODE_ENV will be ignored to avoid accidentally exposing a private key on the machine that could have the same name.

Great, I didn't know it, that's good answer for my question.
