### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tayron123** [gatsbyjs/gatsby#23019]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by vladar** [comment]
This is an empty issue. Please check out [How to File an Issue](https://www.gatsbyjs.org/contributing/how-to-file-an-issue/) in the documentation and create a new one if you have an actual problem.
