### ISSUE TITLE
Gatsby Rich Text Fix does not unlocalize multiple entry links with nesting

### ISSUE THREAD

**Issue by bsgreenb** [gatsbyjs/gatsby#23018]
## Description

 I really appreciate the recent Contentful Rich Text fix by @jessepinho  https://github.com/gatsbyjs/gatsby/pull/21619 but in implementing it I get build errors where it's still returning "en-US" localization https://pastebin.com/9hkKgjPa

Our data model: `Post.body` is a rich text field.  It has `ProductCardSet` embed.  `ProductCardSet.productCards` has is a many-entry link to `ProductCard`, which points to a single `Product` via `ProductCard.product`

When a `ProductCardSet` embed has multiple `ProductCard` entries, only the first `Product` is unlocalized.  The second one looks like
```"fields": { "title": {"en-US": "Some random hoop"}...``` which this fix was supposed to address.  This is the inconsistent types message I get when I have multiple ProductCards.  In this case I used the same `ProductCard` to prove it's not contingent:

```
warn There are conflicting field types in your data.

If you have explicitly defined a type for those fields, you can safely ignore this warning message.
Otherwise, Gatsby will omit those fields from the GraphQL schema.

If you know all field types in advance, the best strategy is to explicitly define them with the `createTypes` action, and skip inference with the
 `@dontInfer` directive.
contentfulPostBodyRichTextNode.content.data.target.fields.productCards.fields.title:
 - type: object
   value: { 'en-US': 'Dorfman Hat Card' }
 - type: string
   value: 'Dorfman Hat Card'
```

It breaks our build currently because the first `ProductCard` is localized and the second is not.  A single card of any type works, but multiple cards will not.

All of our contentful fields/entries are set to `"localized": false`.  I am confident that this is a bug in the rich text fix not on code or data.

### Steps to reproduce

On a Contentful rich text field, embed a model on it that has a many-link entry.  On that model, nest another embed.  When pulling the rich text json you will find that the first entry is unlocalized but the second is not.

If a new repo is needed to demonstrate this, I could do so, additionally I can share any necessary exports, or even share private repro access to someone who's working on this.

### Expected result
All of the rich text embeds should be unlocalized.

### Actual result

https://pastebin.com/9hkKgjPa (Note: this example uses two different cars, one is a Hoop Card which is not localized, and one is the Dorfman Hat card which failed above but localizes correctly there)

#### Gatsby Env
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.1 - ~/.nvm/versions/node/v12.8.1/bin/node
    Yarn: 1.22.4 - ~/sources/glowystuff/node_modules/.bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.8.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12
    gatsby-cli: ^2.11.5 => 2.11.5
    gatsby-image: ^2.3.1 => 2.3.1
    gatsby-plugin-google-analytics: ^2.2.2 => 2.2.2
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3
    gatsby-plugin-netlify: ^2.2.1 => 2.2.1
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1
    gatsby-plugin-sass: ^2.2.1 => 2.2.1
    gatsby-plugin-styled-jsx: ^3.2.1 => 3.2.1
    gatsby-plugin-typescript: ^2.3.1 => 2.3.1
    gatsby-source-contentful: ^2.2.6 => 2.2.6
    gatsby-source-filesystem: ^2.2.2 => 2.2.2

#### Package.json
https://pastebin.com/NCxNze8L

**Comment by madalynrose** [comment]
Thank you so much for opening this issue @bsgreenb! It would be helpful if you could provide a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) either by pointing to a public repo that we can poke at or to something like [codesandbox](https://codesandbox.io/). It sounds like a bug to me, but reproducing in an intentionally simplistic environment will help us narrow down and debug.

**Comment by bsgreenb** [comment]
Hey @madalynrose I can produce a repro, but is not a huge priority right now as I simply made my data model less nested to avoid this (was two birds with one stone, cus ProductCardSet wasn't necessary once we inlined ProductCards)
