### ISSUE TITLE
Markdown images in frontmatter creating strings, not image nodes

### ISSUE THREAD

**Issue by jacobdcastro** [gatsbyjs/gatsby#23012]
## Description

I'm refactoring my markdown blog posts to have the .md file and the images it references in the same folder. Each .md is formatted the exact same way. Querying the frontmatter with the image subfields (publicURL, childImageSharp, etc) continues to return an error saying the image field is a string, and cannot have subfields. I've followed the tutorials/docs closely and I do not know why it keeps saying it's a string of the image filename.

Here is an example of my frontmatter (`image` is the field of concern here):
```
---
slug: "getting-my-deactivated-instagram-account-back-2019-09-28"
title: "Getting My Deactivated Instagram Account Back (Sept. 2019)"
subtitle: "It was pretty annoying... But I learned a cool lesson."
image: prateek-katyal-xv7-GlvBLFw-unsplash.jpg
imageTitle: "Getting My Deactivated Instagram Account Back"
imageAlt: "Instagram 'likes' notification with 0 new likes"
date: "2019-09-28T00:00:00-07:00"
tags:
  - "social media"
  - "instagram"
  - "content"
type: "blogPost"
---
```

My `gatsby-config.js` does include the plugins stated in the docs for it to work: 
```javascript
// gatsby-config.js
plugins: [
  'gatsby-plugin-sharp',
  'gatsby-transformer-sharp',
  {
    resolve: 'gatsby-source-filesystem',
    options: {
      name: 'images',
      path: path.join(__dirname, 'content'), // where all the .md files and their images live
    },
  },
  {
    resolve: 'gatsby-transformer-remark',
    options: {
      plugins: [
        {
          // for inline blog images
          resolve: 'gatsby-remark-images',
          options: {
            maxWidth: 880,
          },
        },
      ],
    },
  },
],
```

My query for my blogPost.js page templates looks like this:
```javascript
export const BLOG_POST_QUERY = graphql`
  query BLOG_POST_QUERY($slug: String!) {
    markdownRemark(frontmatter: { slug: { eq: $slug } }) {
      id
      html
      excerpt(pruneLength: 370)
      timeToRead
      frontmatter {
        image {
          publicURL
          childImageSharp {
            fluid {
              ...GatsbyImageSharpFluid_withWebp
            }
          }
        }
      }
    }
  }
`;
```

### Steps to reproduce

Clone [my repo](https://github.com/jacobdcastro/personal-site), **change to development branch**, and `npm install` and `npm run dev`.

- All markdown blog post files and images are in content/blogPosts/20xx
- Page template is src/templates/blogPost.js

### Expected result

Querying frontmatter image field returns image sharp subfields as shown in query.

### Actual result

Frontmatter image fields are built as strings, disallowing image subfields to be queried.

```
 ERROR #85922  GRAPHQL

There was an error in your GraphQL query:

Field "image" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" make sure that your input source and/or plugin is correct.

File: src\templates\blogPost.js:116:15

failed extract queries from components - 0.157s
```

### Environment

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 13.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.1 - /c/Python38/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.43 => 2.19.43 
    gatsby-image: ^2.2.43 => 2.2.43 
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8 
    gatsby-plugin-google-analytics: ^2.1.37 => 2.1.37 
    gatsby-plugin-lodash: ^3.1.21 => 3.1.21 
    gatsby-plugin-manifest: ^2.2.47 => 2.2.47 
    gatsby-plugin-offline: ^3.0.40 => 3.0.40 
    gatsby-plugin-react-helmet: ^3.1.23 => 3.1.23 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sharp: ^2.4.12 => 2.4.12 
    gatsby-plugin-sitemap: ^2.2.29 => 2.2.29 
    gatsby-plugin-styled-components: ^3.1.20 => 3.1.20 
    gatsby-plugin-typography: ^2.3.24 => 2.3.24 
    gatsby-remark-images: ^3.1.49 => 3.1.49 
    gatsby-remark-prismjs: ^3.3.35 => 3.3.35 
    gatsby-source-filesystem: ^2.1.55 => 2.1.55 
    gatsby-transformer-remark: ^2.6.58 => 2.6.58 
    gatsby-transformer-sharp: ^2.3.18 => 2.3.18

**Comment by lannonbr** [comment]
so the `image` field needs to be a relative path, so if `prateek-katyal-xv7-GlvBLFw-unsplash.jpg
` is in the same folder as your markdown files, it should instead be like this:

```markdown
image: ./prateek-katyal-xv7-GlvBLFw-unsplash.jpg
```

**Comment by LekoArts** [comment]
Yeah, this should solve your problem. You'll also see this usage in all other starters/projects that have the images in the same folder as the markdown file.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
