### ISSUE TITLE
refactor(www): Make the dot-org sidebar into a function component

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#23023]
## Description

Turn www/src/components/sidebar/sidebar.js into a function component.

## Motivation

The sidebar performance is really slow: #21533. Changing it to a function component with hooks would let us reason about the state updates better, and would prevent gotchas that are present in class components.

Sidebar performance is also an issue for localization: #20587. We're going to have to add more functionality in order to make the sidebar localizable and it's easier to do that with an updated codebase.

**Comment by Gerigot** [comment]
Hi, I'm interested in trying porting this from component class to a function component, I'm reading all the contributing guidelines.
I'll open a pull request when and if I finish something.

**Comment by Gerigot** [comment]
I see that it has been done so I'll stop working on it. I'll check out the new version and see if I can find something
