### ISSUE TITLE
Graphql relativePath  and absolutePath Question 

### ISSUE THREAD

**Issue by kMamani** [gatsbyjs/gatsby#23027]
MyQuery 
`query MyQuery {
  file(relativePath: {eq: "logo.png"}) {
    id
    name
  }
}`

result 

`
 
        {
          "name": "logo",
          "relativePath": "logo.png",
          "absolutePath": "E:/Gatsby/dhayzon/src/images/logo.png"
        },
        {
          "name": "bulma-logo",
          "relativePath": "images/bulma-logo.png",
          "absolutePath": "E:/Gatsby/dhayzon/src/images/bulma-logo.png"
        }
        {
          "name": "gatsby-astronaut",
          "relativePath": "images/gatsby-astronaut.png",
          "absolutePath": "E:/Gatsby/dhayzon/src/images/gatsby-astronaut.png"
        },  
`

all images are inside same folder /images/

but  logo.png relativePath not similiar another images why?

**Comment by vladar** [comment]
Thanks for opening this issue. But your query can't produce those results. You request a single file but the result contains 3 items. You also request only `id` and `name` fields but your result has a different set of fields.

So please double check that you posted the correct query. I suggest you:

1. Run `gatsby develop`
2. Open `http://localhost:8000/___graphql` in browser
3. Run the query and post the result here

**Comment by kMamani** [comment]
Sorry, the Query codes is this 

`  allFile {
    edges {
      node {
        absolutePath
        relativePath
        name
      }
    }
  }`


but, I'am fixed  ¿why?

move images an other dir 
example 
 move to / temp/  after  return files to  /images/ and fiexed it  

GraphQL udate all Path, its okay

Why did this happened? I do not know

**Comment by vladar** [comment]
This query has no filter on it. See, just `allFile`, not `allFile(filter: { relativePath: {eq: "logo.png"} })`. So it simply returns all files you have.
