### ISSUE TITLE
Is issue #10090 really resolved?

### ISSUE THREAD

**Issue by LukasMachetanz** [gatsbyjs/gatsby#23047]
Hey, should this issue be resolved already? Because I am experiencing the exact same problem in the moment. And the mentioned workaround does not work for me either.

Any updates on this? I would appreciate it.

**Comment by LekoArts** [comment]
Hi, yes, this should be resolved. Please create a [minimal reproduction][reproduction] and share it in the original issue.

Closing this as a duplicate for now.

[reproduction]: https://gatsby.dev/reproduction
