### ISSUE TITLE
Simplify site generation with gatsby CLI

### ISSUE THREAD

**Issue by Bam92** [gatsbyjs/gatsby#23057]
## Summary

Add a feature that lets us fetch a starter by just passing its name.

### Basic example

Instead of typing `gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`, dev can just type `gatsby new hello-world gatsby-starter-hello-world`. You can even simplify it by just typing `starter-hello-world` because almost all starters start with `gatsby` 

### Motivation

Improve dev experience by letting them go faster.

**Comment by LekoArts** [comment]
Thank you for opening this!

You can run `gatsby new` and then select from a list of official starters.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
