### ISSUE TITLE
Error when using double quotes in useStaticQuery 

### ISSUE THREAD

**Issue by kawhyte** [gatsbyjs/gatsby#23081]
## Description

Unable to add  double quotes in a useStaticQuery graphql (gatsby-source-graphql) request to a private API.

The query works fine with double quotes (" ") when using  GraphiQL  but this does not work in Gatsby’s useStaticQuery

I need the quotes to get an “exact match”. Similar to when you do a Google search with quotes.

<img width="1012" alt="Screen Shot 2020-04-12 at 9 58 49 PM" src="https://user-images.githubusercontent.com/9040355/79160440-9f51fd00-7d8e-11ea-8f44-5f199533aff8.png">

For Example: 
{
  
  bills(first: 10, updatedSince: "2019-11-15" searchQuery:"\"paid family leave\"") {
        edges {
            node { 
              
  
    title
  
            
            }
        }
    }
}

### Steps to reproduce
 Go to the following link to test  - 

1. https://openstates.org/graphql

2. use the following query :

{
  bills(first: 10, updatedSince: "2019-11-15" searchQuery:"\"paid family leave\"") {
        edges {
            node { 
    title

            }
        }
    }
}

3. perform that query in a Gatsby project  using  useStaticQuery graphql (gatsby-source-graphql) 

### Expected result

Should be able to search using double quotes .

### Actual result

Error. Syntax Error: Expected :, found Name "family"

<img width="899" alt="Screen Shot 2020-04-13 at 7 36 54 AM" src="https://user-images.githubusercontent.com/9040355/79163503-1211a700-7d94-11ea-9958-f3f982af96c2.png">

<img width="936" alt="Screen Shot 2020-04-13 at 8 04 34 AM" src="https://user-images.githubusercontent.com/9040355/79163553-25247700-7d94-11ea-9183-2bf0ee2b0b50.png">

<img width="955" alt="Screen Shot 2020-04-13 at 8 14 16 AM" src="https://user-images.githubusercontent.com/9040355/79163568-2ce41b80-7d94-11ea-95a7-49c72ce44e85.png">

### Environment

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm

  npmPackages:
    gatsby: ^2.19.49 => 2.20.15
    gatsby-cli: ^2.11.5 => 2.11.5
    gatsby-image: ^2.3.1 => 2.3.2
    gatsby-plugin-postcss: ^2.2.1 => 2.2.1
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1
    gatsby-plugin-sharp: ^2.5.3 => 2.5.4
    gatsby-remark-images: ^3.2.1 => 3.2.2
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-source-contentful: ^2.1.19 => 2.2.7
    gatsby-source-filesystem: ^2.2.2 => 2.2.2
    gatsby-source-graphql: 2.1.20 => 2.1.20
    gatsby-transformer-remark: ^2.7.1 => 2.7.1
    gatsby-transformer-remark-frontmatter: ^0.1.0 => 0.1.0
    gatsby-transformer-sharp: ^2.4.3 => 2.4.4
  npmGlobalPackages:
    gatsby-advanced-blog: 1.1.4
    gatsby-cli: 2.11.4
    gatsby-plugin-typography: 2.3.21

**Comment by Js-Brecht** [comment]
Does it work like this:
```graphql
{
  bills(first: 10, updatedSince: "2019-11-15", searchQuery: "\\\"paid family leave\\\"") {
    edges {
      node {
        title
        subject
        classification
        abstracts {
          abstract
          note
          date
        }
      }
    }
  }
}
```

**Comment by kawhyte** [comment]
> Does it work like this?
> 
> ```graphql
> {
>   bills(first: 10, updatedSince: "2019-11-15", searchQuery: "\\\"paid family leave\\\"") {
>     edges {
>       node {
>         title
>       }
>     }
>   }
> }
> ```

This worked! Thank you @Js-Brecht  ✌🏽+ ❤️
