### ISSUE TITLE
print warning when resolvers take too long

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#23098]
Custom graphql resolvers can hang indefinitely.

This is hard to discover and debug. We should print a warning when resolvers take too long to return. We tried setting a maxTimeout in https://github.com/gatsbyjs/gatsby/pull/23095 but this broke some sites as @pvdz said:

>for reference; this will block builds because the time isn't properly measured so if the first query gets delayed by another blocking process (webpack?) it'll measure a timeout for the first query and then abort the build

**Comment by vladar** [comment]
Related: #21825

**Comment by freiksenet** [comment]
Closing as duplicate of #21825.
