### ISSUE TITLE
Netlify problem with deploy!

### ISSUE THREAD

**Issue by SirmiumTag** [gatsbyjs/gatsby#23090]
Does anybody know how can i fix this? Here is project repo: https://github.com/SirmiumTag/stc
Application is working perfectly at localhost:3000!

11:05:53 AM: Build ready to start
11:05:55 AM: build-image version: 2dbd444fcdce00cf06325060a8238d5ae3e86774
11:05:55 AM: build-image tag: v3.3.7
11:05:55 AM: buildbot version: 134ec431c6a3ff76e87cc4dc34007fe13842272f
11:05:55 AM: Fetching cached dependencies
11:05:56 AM: Starting to download cache of 161.8MB
11:05:59 AM: Finished downloading cache in 3.571238476s
11:05:59 AM: Starting to extract cache
11:06:07 AM: Finished extracting cache in 8.463860764s
11:06:08 AM: Finished fetching cache in 12.101483238s
11:06:08 AM: Starting to prepare the repo for build
11:06:08 AM: Preparing Git Reference refs/heads/master
11:06:09 AM: Starting build script
11:06:09 AM: Installing dependencies
11:06:09 AM: Started restoring cached node version
11:06:14 AM: Finished restoring cached node version
11:06:16 AM: Downloading and installing node v10.20.1...
11:06:16 AM: Downloading https://nodejs.org/dist/v10.20.1/node-v10.20.1-linux-x64.tar.xz...
11:06:17 AM: 
############################                                              39.9%
11:06:17 AM: 
######################################
11:06:17 AM: ################################## 100.0%
11:06:17 AM: Computing checksum with sha256sum
11:06:17 AM: Checksums matched!
11:06:20 AM: Now using node v10.20.1 (npm v6.14.4)
11:06:20 AM: Attempting ruby version 2.6.2, read from environment
11:06:22 AM: Using ruby version 2.6.2
11:06:22 AM: Using PHP version 5.6
11:06:22 AM: Started restoring cached node modules
11:06:22 AM: Finished restoring cached node modules
11:06:22 AM: Installing NPM modules using NPM version 6.14.4
11:06:39 AM: > grpc@1.24.2 install /opt/build/repo/node_modules/grpc
11:06:39 AM: > node-pre-gyp install --fallback-to-build --library=static_library
11:06:39 AM: node-pre-gyp
11:06:39 AM: WARN Using request for node-pre-gyp https download
11:06:40 AM: [grpc] Success: "/opt/build/repo/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" is installed via remote
11:06:40 AM: > core-js@3.6.4 postinstall /opt/build/repo/node_modules/@firebase/polyfill/node_modules/core-js
11:06:40 AM: > node -e "try{require('./postinstall')}catch(e){}"
11:06:40 AM: > protobufjs@6.8.9 postinstall /opt/build/repo/node_modules/protobufjs
11:06:40 AM: > node scripts/postinstall
11:06:42 AM: npm
11:06:42 AM: WARN
11:06:42 AM:  bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
11:06:42 AM: npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
11:06:42 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.10 (node_modules/jest-haste-map/node_modules/fsevents):
11:06:42 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.10: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
11:06:42 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.10 (node_modules/chokidar/node_modules/fsevents):
11:06:42 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.10: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
11:06:42 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
11:06:42 AM: npm
11:06:42 AM:  WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
11:06:42 AM: added 186 packages from 116 contributors and audited 906709 packages in 18.944s
11:06:43 AM: 31 packages are looking for funding
11:06:43 AM:   run `npm fund` for details
11:06:43 AM: found 38937 vulnerabilities (38919 low, 18 moderate)
11:06:43 AM:   run `npm audit fix` to fix them, or `npm audit` for details
11:06:43 AM: NPM modules installed
11:06:44 AM: Started restoring cached go cache
11:06:44 AM: Finished restoring cached go cache
11:06:44 AM: unset GOOS;
11:06:44 AM: unset GOARCH;
11:06:44 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
11:06:44 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
11:06:44 AM: go version >&2;
11:06:44 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
11:06:44 AM: go version go1.12 linux/amd64
11:06:44 AM: Installing missing commands
11:06:44 AM: Verify run directory
11:06:44 AM: Executing user command: npm run build
11:06:44 AM: > myapp@0.1.0 build /opt/build/repo
11:06:44 AM: > react-scripts build
11:06:46 AM: Creating an optimized production build...
11:07:45 AM: Treating warnings as errors because process.env.CI = true.
11:07:45 AM: Most CI servers set it automatically.
11:07:45 AM: Failed to compile.
11:07:45 AM: ./src/Documentation.js
11:07:45 AM:   Line 18:116:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank
11:07:45 AM:   Line 23:7:    No duplicate props allowed                                                                                                    react/jsx-no-duplicate-props
11:07:45 AM: ./src/Footer.js
11:07:45 AM:   Line 18:34:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank
11:07:45 AM:   Line 18:82:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                     jsx-a11y/alt-text
11:07:45 AM:   Line 19:34:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank
11:07:45 AM:   Line 19:83:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                     jsx-a11y/alt-text
11:07:45 AM:   Line 20:34:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank
11:07:45 AM:   Line 20:87:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                     jsx-a11y/alt-text
11:07:45 AM: ./src/Html.js
11:07:45 AM:   Line 1:17:   'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:    'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 102:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Csssrb.js
11:07:45 AM:   Line 1:17:   'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:    'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 113:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Mongodb.js
11:07:45 AM:   Line 1:17:   'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:    'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 114:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Php.js
11:07:45 AM:   Line 1:17:   'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:    'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 117:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Htmlsrb.js
11:07:45 AM:   Line 1:17:   'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:    'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 118:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Css-grid.js
11:07:45 AM:   Line 1:17:   'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:    'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 120:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Javascript.js
11:07:45 AM:   Line 1:17:   'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:    'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 143:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Graphql.js
11:07:45 AM:   Line 1:17:   'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:    'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 143:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Nodejs.js
11:07:45 AM:   Line 1:17:   'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:    'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 145:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Css.js
11:07:45 AM:   Line 1:17:  'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:   'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 91:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Reactjs.js
11:07:45 AM:   Line 1:17:  'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:   'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 93:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Css-flexbox.js
11:07:45 AM:   Line 1:17:  'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:   'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 95:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/Nexjs.js
11:07:45 AM:   Line 1:17:  'Component' is defined but never used  no-unused-vars
11:07:45 AM:   Line 3:8:   'AdSense' is defined but never used    no-unused-vars
11:07:45 AM:   Line 96:7:  No duplicate props allowed             react/jsx-no-duplicate-props
11:07:45 AM: ./src/App.js
11:07:45 AM:   Line 26:3:  Useless constructor  no-useless-constructor
11:07:45 AM: ./src/Navbar.js
11:07:45 AM:   Line 3:8:     'App' is defined but never used                                                                            no-unused-vars
11:07:45 AM:   Line 4:8:     'Bootstrap' is defined but never used                                                                      no-unused-vars
11:07:45 AM:   Line 5:8:     'Css' is defined but never used                                                                            no-unused-vars
11:07:45 AM:   Line 6:8:     'Csssrb' is defined but never used                                                                         no-unused-vars
11:07:45 AM:   Line 7:8:     'Reactjs' is defined but never used                                                                        no-unused-vars
11:07:45 AM:   Line 8:8:     'Html' is defined but never used                                                                           no-unused-vars
11:07:45 AM:   Line 11:8:    'Pocetna' is defined but never used                                                                        no-unused-vars
11:07:45 AM:   Line 12:8:    'Htmlsrb' is defined but never used                                                                        no-unused-vars
11:07:45 AM:   Line 13:8:    'Documentation' is defined but never used                                                                  no-unused-vars
11:07:45 AM:   Line 14:8:    'Cssgrid' is defined but never used                                                                        no-unused-vars
11:07:45 AM:   Line 15:8:    'Cssflexbox' is defined but never used                                                                     no-unused-vars
11:07:45 AM:   Line 16:8:    'Javascript' is defined but never used                                                                     no-unused-vars
11:07:45 AM:   Line 17:8:    'Nodejs' is defined but never used                                                                         no-unused-vars
11:07:45 AM:   Line 18:8:    'Graphql' is defined but never used                                                                        no-unused-vars
11:07:45 AM:   Line 19:8:    'Nexjs' is defined but never used                                                                          no-unused-vars
11:07:45 AM:   Line 20:8:    'Php' is defined but never used                                                                            no-unused-vars
11:07:45 AM:   Line 21:8:    'Mongodb' is defined but never used                                                                        no-unused-vars
11:07:45 AM:   Line 111:64:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
11:07:45 AM: ./src/Bootstrapsrb.js
11:07:45 AM:   Line 5:8:    'AdSense' is defined but never used  no-unused-vars
11:07:45 AM:   Line 121:9:  No duplicate props allowed           react/jsx-no-duplicate-props
11:07:45 AM: ./src/Bootstrap.js
11:07:45 AM:   Line 5:8:   'AdSense' is defined but never used  no-unused-vars
11:07:45 AM:   Line 92:9:  No duplicate props allowed           react/jsx-no-duplicate-props
11:07:45 AM: npm
11:07:45 AM:  ERR! code
11:07:45 AM:  ELIFECYCLE
11:07:45 AM: npm ERR! errno 1
11:07:45 AM: npm
11:07:45 AM: ERR! myapp@0.1.0 build: `react-scripts build`
11:07:45 AM: npm ERR!
11:07:45 AM:  Exit status 1
11:07:45 AM: npm ERR!
11:07:45 AM: npm
11:07:45 AM:  ERR! Failed at the myapp@0.1.0 build script.
11:07:45 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
11:07:45 AM: npm ERR!
11:07:45 AM:  A complete log of this run can be found in:
11:07:45 AM: npm ERR!     /opt/buildhome/.npm/_logs/2020-04-14T09_07_45_886Z-debug.log
11:07:45 AM: Skipping functions preparation step: no functions directory set
11:07:45 AM: Caching artifacts
11:07:45 AM: Started saving node modules
11:07:45 AM: Finished saving node modules
11:07:45 AM: Started saving pip cache
11:07:46 AM: Finished saving pip cache
11:07:46 AM: Started saving emacs cask dependencies
11:07:46 AM: Finished saving emacs cask dependencies
11:07:46 AM: Started saving maven dependencies
11:07:46 AM: Finished saving maven dependencies
11:07:46 AM: Started saving boot dependencies
11:07:46 AM: Finished saving boot dependencies
11:07:46 AM: Started saving go dependencies
11:07:46 AM: Finished saving go dependencies
11:07:53 AM: Error running command: Build script returned non-zero exit code: 1
11:07:53 AM: Failing build: Failed to build site
11:07:53 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
11:07:53 AM: Finished processing build request in 1m57.378083083s

**Comment by LekoArts** [comment]
Hi!

You're using https://github.com/facebook/create-react-app so you should create an issue there ;) Thanks!
