### ISSUE TITLE
× TypeError: Cannot read property 'component---src-templates-home-js' of undefined createComponentUrls D:/projects/someProject/.cache/loader.js:348

### ISSUE THREAD

**Issue by ArmenMelk** [gatsbyjs/gatsby#23105]
After add gatsby-plugin-offline plugin I have this issue when do gatsby develop I have got this error messages 
×
TypeError: Cannot read property 'component---src-templates-home-js' of undefined
createComponentUrls
D:/projects/myproject/.cache/loader.js:348
  345 |   }
  346 | }
  347 | 
> 348 | const createComponentUrls = componentChunkName =>
  349 |   window.___chunkMapping[componentChunkName].map(
  350 |     chunk => __PATH_PREFIX__ + chunk
  351 |   )
View compiled
DevLoader.getResourceURLsForPathname
D:/projects/p7s1p4-4gc-web/.cache/loader.js:303
  300 | if (page) {
  301 |   const pageResources = toPageResources(page.payload)
  302 | 
> 303 |   return [
  304 |     ...createComponentUrls(pageResources.page.componentChunkName),
  305 |     createPageDataUrl(pagePath),
  306 |   ]
View compiled
getResourceURLsForPathname
D:/projects/p7s1p4-4gc-web/.cache/loader.js:411
  408 | enqueue: rawPath => instance.prefetch(rawPath),
  409 | 
  410 | // Real methods
> 411 | getResourceURLsForPathname: rawPath =>
  412 |   instance.getResourceURLsForPathname(rawPath),
  413 | loadPage: rawPath => instance.loadPage(rawPath),
  414 | loadPageSync: rawPath => instance.loadPageSync(rawPath),
View compiled
▶ 2 stack frames were collapsed.
(anonymous function)
D:/projects/p7s1p4-4gc-web/.cache/api-runner-browser.js:35
  32 | args.loadPage = loadPage
  33 | args.loadPageSync = loadPageSync
  34 | 
> 35 | const result = plugin.plugin[api](args, plugin.options)
  36 | if (result && argTransform) {
  37 |   args = argTransform({ args, result, plugin })
  38 | }
View compiled
./.cache/api-runner-browser.js.exports.apiRunner
D:/projects/p7s1p4-4gc-web/.cache/api-runner-browser.js:22
  19 |   }
  20 | }
  21 | 
> 22 | let results = plugins.map(plugin => {
  23 |   if (!plugin.plugin[api]) {
  24 |     return undefined
  25 |   }
View compiled
onRouteUpdate
D:/projects/p7s1p4-4gc-web/.cache/navigation.js:45
  42 | 
  43 | const onRouteUpdate = (location, prevLocation) => {
  44 |   if (!maybeRedirect(location.pathname)) {
> 45 |     apiRunner(`onRouteUpdate`, { location, prevLocation })
  46 |     // Temp hack while awaiting https://github.com/reach/router/issues/119
  47 |     window.__navigatingToLink = false
  48 |   }
View compiled
RouteUpdates.componentDidMount
D:/projects/p7s1p4-4gc-web/.cache/navigation.js:218
  215 | }
  216 | 
  217 | componentDidMount() {
> 218 |   onRouteUpdate(this.props.location, null)
  219 | }
  220 | 
  221 | componentDidUpdate(prevProps, prevState, shouldFireRouteUpdate) {
View compiled
▶ 18 stack frames were collapsed.
(anonymous function)
D:/projects/p7s1p4-4gc-web/.cache/app.js:67
  64 | const preferDefault = m => (m && m.default) || m
  65 | let Root = preferDefault(require(`./root`))
  66 | domReady(() => {
> 67 |   renderer(<Root />, rootElement, () => {
  68 |     apiRunner(`onInitialClientRender`)
  69 |   })
  70 | })

I have checked 'component---src-templates-home-js+somehash.js` is exist in pucblic directory. 
I am using windows 10

**Comment by ArtsrunKar** [comment]
.

**Comment by ArtsrunKar** [comment]
I also encountered this problem

**Comment by madalynrose** [comment]
Hello and thanks for letting us know about your issue. Is your site repo public? Otherwise, can you [create a reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so we can help you debug? Thanks!

**Comment by ArmenMelk** [comment]
@madalynrose after clean site data from browser it's start work properly
