### ISSUE TITLE
gatsby-image lazy loading not working in MacOS Safari

### ISSUE THREAD

**Issue by rzubrycki** [gatsbyjs/gatsby#23126]
Description
In MacOS Safari, when coming to the base url, images from gatsby-image are not loading. All images in different pages are working correctly.
Everything works ok on firefox, chrome.
I thought it may be issue with intersection observer, but latest safari supports it now.

Expected result
Display image on safari.

Actual result
No images, only deep blue default background.

Environment
System:
OS: macOS 10.14.3

  "dependencies": {
    "@rhysforyou/gatsby-plugin-react-helmet-async": "^0.1.3",
    "formik": "^2.1.4",
    "gatsby": "^2.20.8",
    "gatsby-background-image": "^0.10.2",
    "gatsby-image": "^2.3.1",
    "gatsby-plugin-google-analytics": "^2.2.2",
    "gatsby-plugin-intl": "^0.3.3",
    "gatsby-plugin-manifest": "^2.3.3",
    "gatsby-plugin-offline": "^3.1.2",
    "gatsby-plugin-robots-txt": "^1.5.0",
    "gatsby-plugin-sass": "^2.2.1",
    "gatsby-plugin-sharp": "^2.5.3",
    "gatsby-plugin-sitemap": "^2.3.1",
    "gatsby-source-filesystem": "^2.2.2",
    "gatsby-transformer-sharp": "^2.4.3",
    "node-sass": "^4.13.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-helmet-async": "^1.0.4",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^0.88.2",
    "yup": "^0.28.3"
  },
  "devDependencies": {
    "html-loader": "^1.0.0",
    "nodemon": "^2.0.2",
    "prettier": "^2.0.2"
  },

**Comment by ascorbic** [comment]
Hi. I've tried this with the default starter and can't reproduce it. Is your site repo public? Otherwise, can you [create a reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/). Thanks.

**Comment by rzubrycki** [comment]
Hello! Thanks for the reply. Here's the link, repo is private.
https://www.tacticool.site/en/
Nothing fancy going on under the hood, just staticQuery to fetch image url and that's it.

**Comment by madalynrose** [comment]
Hello! I can see it reproduced when I visit your site in Safari but can't debug further without some code. Could you create a minimal reproduction with either a public repository or with something like [codesandbox](https://codesandbox.io/)?

**Comment by rzubrycki** [comment]
@madalynrose 
https://github.com/rzubrycki/tc-wiki

src/pages/intro.js
src/components/LogoComponent/logo.js

**Comment by rzubrycki** [comment]
Ok, i found it.
Safari don't support images in .webp format.
Topic can be closed.
