### ISSUE TITLE
Formatstring on BST datetimes for midnight are returning the wrong day

### ISSUE THREAD

**Issue by theAdhocracy** [gatsbyjs/gatsby#23135]
## Description

On a GraphQL query I have a `date` field which is being reformatted to `DD MMM YYYY`. That worked fine for all entries until we entered British Summer Time, at which point any dates set to midnight are being formatted to the next day e.g. 12th April becomes 13th April.

### Steps to reproduce

_I'm having problems creating a test GraphQL node and getting it to show up/be queriable; if anyone can pass on a tutorial on how to setup a mock GraphQL node with hardcoded data then I'd be happy to set this up_

1. Have a GraphQL node that contains a date in the format `2020-04-12T00:00:00+01:00`
2. Within a query, try to reformat to `DD MMM YYYY` like so:

```
export const query = graphql`
 {
    allDates{
        nodes {
            date(formatString: "DD MMM YYYY")
        }
     }
  }
`
```

3. Output formatted date value to console

### Expected result

Returns `12 Apr 2020`.

### Actual result

Returned `13 Apr 2020`.

### Environment

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  Binaries:
    Node: 13.10.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.10.4 => 2.19.19 
    gatsby-cli: ^2.11.8 => 2.11.8 
    gatsby-plugin-feed: ^2.3.4 => 2.3.27 
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.22 
```

**Comment by ascorbic** [comment]
Hi. The date formatter converts everything to UTC even if the source field includes a timezone. Midnight BST is still the previous day in UTC, which is why it displays that day.

**Comment by theAdhocracy** [comment]
@ascorbic but wouldn't that mean it should give the day before, not the day after. 12th should become 11th if what you're saying is true, but it doesn't, it becomes the 13th.

**Comment by theAdhocracy** [comment]
Thanks, you're right and my original question had the values the wrong way around (i.e. 13th was becoming 12th, not 12th -> 13th as I've written). That makes sense, though it's a shame there isn't any way to change that to work on local times/different timezones instead.
