### ISSUE TITLE
bug(blogs): blog posts are not visible

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#23147]
## Description

blogposts LA Days higher than Video 7 are not visible in: 
- https://www.gatsbyjs.org/blog/ and in 
- https://www.gatsbyjs.org/blog/tags/gatsby-days

but i can open them direct:
- https://www.gatsbyjs.org/blog/2020-04-14-LA-2020-Kim/ Video 10
- https://www.gatsbyjs.org/blog/2020-04-13-LA-2020-Comeau/ Video 9
and others

### Steps to reproduce

open:
- https://www.gatsbyjs.org/blog/ 
- https://www.gatsbyjs.org/blog/tags/gatsby-days

### Expected result

Blogpost should be visible

### Actual result

not visible

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by laurieontech** [comment]
Thanks. We're aware of this one and working on it!

**Comment by manishsundriyal** [comment]
Is anyone working on it? If not then I might give it a try.

**Comment by laurieontech** [comment]
I believe @DSchau is?

**Comment by wardpeet** [comment]
I believe we want to fix this internally as we're aware of the issue and have ideas on how to solve it.

**Comment by wardpeet** [comment]
Yes @DSchau is #23207

**Comment by manish-nx** [comment]
Thanks for the info. I will look into other issues then.

**Comment by muescha** [comment]
note: i removed the label `stale?`, because the blog posts not visible in overviews, the PR #23207 is canceled

**Comment by muescha** [comment]
the blog post are now visible - i will close the issue

**Comment by muescha** [comment]
@wardpeet @DSchau how this problem was fixed?
