### ISSUE TITLE
Is it possible to prefetch pages with `<Link>` but applying a delay?

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#23165]
If the `Link` elements are on top of pages, prefetching occurs immediately

I was wondering whether it is possible to start the prefetching with a specific delay, so that page loads faster and becomes responsive earlier

**Comment by freiksenet** [comment]
Page should be interactive even when links are loading - do you have a reproduction where you have interactivity problem because of link preloading?

**Comment by wardpeet** [comment]
@kuworking Prefetch shouldn't necessary slow down your page load as it's prioritized low by the browser. However, they can interfere with resources embedded in the react tree.

This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/12850. I'll be closing this one. Thank you for opening!
