### ISSUE TITLE
Gatsby Cloud not updating after publish ContentStack with Webhook

### ISSUE THREAD

**Issue by thomasledoux1** [gatsbyjs/gatsby#23186]
## Summary
I have set up a Preview environment on Gatsby Cloud, and a Preview environment on ContentStack. 
I configured the environment variables correctly, and everything is working correctly, except for the Webhook.
I was expecting my Preview website on Gatsby Cloud to update the component for which I did a content change in ContentStack (on the Preview environment), but there is no change coming through after the publish. 
I can see in ContentStack that the webhook returned a 200 status code, so I don't know what I'm doing wrong here.

## Relevant information

I'm using the "gatsby-source-contentstack" plugin and createPage API to create my 'event' pages. This is where it's going wrong.

### Environment (if relevant)

System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Users\tledoux\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12
    gatsby-image: ^2.3.2 => 2.3.2
    gatsby-plugin-intl: ^0.3.3 => 0.3.3
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3
    gatsby-plugin-offline: ^3.1.2 => 3.1.2
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1
    gatsby-plugin-sharp: ^2.5.3 => 2.5.3
    gatsby-source-contentstack: ^2.1.0 => 2.1.0
    gatsby-source-filesystem: ^2.2.2 => 2.2.2
    gatsby-transformer-sharp: ^2.4.3 => 2.4.3

### File contents (if changed)

`gatsby-config.js`: `require('dotenv').config({
  path: `.env.${process.env.NODE_ENV}`
})

module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-source-contentstack`,
      options: {
        // API Key is a unique key assigned to each stack. This is required.
        api_key: process.env.CONTENTSTACK_API_KEY,
        environment: process.env.CONTENTSTACK_ENVIRONMENT,
        // Delivery Token is a read-only credential . This is required.
        delivery_token: process.env.CONTENTSTACK_ACCESS_TOKEN,

        expediteBuild: process.env.CONTENTSTACK_EXPEDITE_BUILD === 'true',

        // Optional: CDN set this to point to other cdn end point. For eg: https://eu-cdn.contentstack.com/v3 
        cdn: `https://eu-cdn.contentstack.com/v3`,
      },
    },
    {
      resolve: 'gatsby-plugin-intl',
      options: {
        path: `${__dirname}/src/intl`,
        languages: [`en`, `nl`, `fr`],
        defaultLanguage: `en`,
      }
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
`
`package.json`: `{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-fontawesome": "^0.1.9",
    "gatsby": "^2.20.12",
    "gatsby-image": "^2.3.2",
    "gatsby-plugin-intl": "^0.3.3",
    "gatsby-plugin-manifest": "^2.3.3",
    "gatsby-plugin-offline": "^3.1.2",
    "gatsby-plugin-react-helmet": "^3.2.1",
    "gatsby-plugin-sharp": "^2.5.3",
    "gatsby-source-contentstack": "^2.1.0",
    "gatsby-source-filesystem": "^2.2.2",
    "gatsby-transformer-sharp": "^2.4.3",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^5.2.1"
  },
  "devDependencies": {
    "dotenv": "^8.2.0",
    "prettier": "^1.19.1"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
`
`gatsby-node.js`: `exports.createPages = async ({ actions, graphql }) => {
    const { data } = await graphql(`
        query {
            allContentstackEvent(sort: {fields: date}) {
                edges {
                    node {
                      url
                      id
                      publish_details {
                          locale
                      }
                    }
                }
            }
            allContentstackUniversalPage {
                edges {
                    node {
                      id
                      url
                      publish_details {
                        locale
                      }
                    }
                }
            }
        }
    `)
    data.allContentstackEvent.edges.forEach(edge => {
        const event = edge.node;
        actions.createPage({
            path: `${event.publish_details.locale !== 'en' ? event.publish_details.locale : ''}/events/${event.id}`,
            component: require.resolve(`./src/components/event.js`),
            context: { id: event.id, },
        })
    });
    data.allContentstackUniversalPage.edges.forEach(edge => {
        const page = edge.node;
        if (page.url !== '/') {
            actions.createPage({
                path: `${page.publish_details.locale !== 'en' ? page.publish_details.locale : ''}${page.url}`,
                component: page.url === '/events' ? require.resolve(`./src/components/eventOverviewPage.js`) : require.resolve(`./src/components/contentPage.js`),
                context: { id: page.id, },
            })
        }
    });
}`
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi!

Please use the little "Help" button at the top right or support@gatsbyjs.com for help about Gatsby Cloud. Thanks!

![image](https://user-images.githubusercontent.com/16143594/79546769-41c1f700-8093-11ea-8726-e11de10dc91a.png)
