### ISSUE TITLE
[Webpack] A single file doesn't get minified after `gatsby build`

### ISSUE THREAD

**Issue by angeloocana** [gatsbyjs/gatsby#2318]
Hi!

I need some help here, I don't know if it is my mistake or a bug.

When I run `gatsby build` a single file `public/component---src-layouts-index-js-....js` is not minified by Webpack.

Project: https://tic-tac-toe-ai.surge.sh
Source: https://github.com/angeloocana/tic-tac-toe-ai

The files below are minified:

`public/app-....js`
`public/commons-....js`

Does anyone have a guess about what is happing?

Thanks!

**Comment by KyleAMathews** [comment]
This seems... unlikely? Can you reproduce the problem?

**Comment by sebastienfi** [comment]
This could occur if the file to optimize is bigger than 500kb.
Splitting the file to components should solve this.

**Comment by angeloocana** [comment]
Thank you @sebastienfi ! That was the problem.
