### ISSUE TITLE
gatsby recipes gives me Error: No valid exports main found for '/Users/John/node_modules/@urql/core'

### ISSUE THREAD

**Issue by otherjohn** [gatsbyjs/gatsby#23202]
## Description

When running `gatsby recipes` I get the following:
```
 www % gatsby recipes
/Users/John/.nvm/versions/node/v13.5.0/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: No valid exports main found for '/Users/John/node_modules/@urql/core'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/John/node_modules/urql/dist/urql.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}
```

### Steps to reproduce

1. `npm install -g gatsby-cli@latest`
2. `npm install gatsby@latest`
3. `gatsby new www https://github.com/gatsbyjs/gatsby-starter-hello-world`
4. `cd www`
5. `gatsby recipes`

### Environment

System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.2 - ~/.nvm/versions/node/v13.5.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12
  npmGlobalPackages:
    gatsby-cli: 2.11.9

**Comment by jeffbarg** [comment]
Have the same issue here!

**Comment by LekoArts** [comment]
Node 13 isn't currently working and a known issue (mentioned here: https://github.com/gatsbyjs/gatsby/issues/22991). Please stick to the umbrella issue, thanks!

**Comment by kitten** [comment]
@otherjohn Hiya 👋 maintainer of `urql` here,
I was wondering whether this is still happening. We pushed some fixed versions and it seems to be unreproducible now. So I’m hoping this is fixed as long as a reinstall / upgrade takes place and a newer version of `@urql/core` is installed

**Comment by dcsan** [comment]
@kitten yeah its still happening for me, that brought me here.
so if gatsby is broken on certain node versions, shouldn't it at least warn on building/

**Comment by kitten** [comment]
@dcsan Hiya 👋 I tested this very thoroughly on all major Node releases, and a fresh install with the latest version hasn’t been causing this anymore. If you see this happening please let me know which exact Node Version this is and what version of `@urql/core` is installed (which you can check with `yarn list @urql/core` or manually in `node_modules/@urql/core/package.json`

**Comment by ikteru** [comment]
Still happening to me as well: 
![image](https://user-images.githubusercontent.com/24244295/85068627-6afa2300-b1bb-11ea-8c26-4c052b19b725.png)

**Comment by kitten** [comment]
@ikteru the same command works fine for me and we've verified that this has been fixed, so I'm a little confused; but as stated above as it only happens with older versions of `@urql/core` there may be some caching going on. Now this can be fixed if the version of `urql` is bumped in Gatsby or if the cached modules are wiped. But you can check which version is being used manually and it's likely going to be one without those fixes.

**Comment by amirAHD77** [comment]
same issue .how can i fix it?

**Comment by kitten** [comment]
@amirAHD77 either upgrade to node 14 or downgrade to node 12, and/or upgrade `@urql/core` if you’re on one of the affected versions (which can still be the case due to caching / odd version resolutions sometimes) https://github.com/gatsbyjs/gatsby/issues/24514#issuecomment-634435861
