### ISSUE TITLE
onClick is not working in production mode on buttons and elsewhere. 

### ISSUE THREAD

**Issue by aesthytik** [gatsbyjs/gatsby#23200]
## Description

onClick event is not triggered in my gatsby build. Everything works fine in development mode. I tried deleting cache and public folder, nothing works

### Steps to reproduce

Create a button and add console.log("test") to onClick. works on development but no console is shown in production 

### Expected result

onClick should works

### Actual result

Nothing is triggered on click 

### Environment

System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.2 - /var/folders/dg/9dqk3_gd2ll9xkvm_7shxcc00000gp/T/yarn--1587071256577-0.43262280506991035/node
    Yarn: 1.13.0 - /var/folders/dg/9dqk3_gd2ll9xkvm_7shxcc00000gp/T/yarn--1587071256577-0.43262280506991035/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 68.0.1
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.20.12 => 2.20.18
    gatsby-image: ^2.3.1 => 2.3.2
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3
    gatsby-plugin-offline: ^3.1.2 => 3.1.2
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.2
    gatsby-plugin-sharp: ^2.5.3 => 2.5.4
    gatsby-source-filesystem: ^2.2.2 => 2.2.2
    gatsby-source-prismic-graphql: ^3.5.0 => 3.5.0
    gatsby-transformer-sharp: ^2.4.3 => 2.4.4

**Comment by wardpeet** [comment]
Hi @aesthytik!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by aesthytik** [comment]
hi @wardpeet 
https://github.com/aesthytik/gatsby-test

above is a public repository. i added prismic plugin for gatsby here and onClick handlers stopped working. I tried consoling some text onClick and no response in chrome debugger.

**Comment by aesthytik** [comment]
fixed it !

**Comment by wjchat** [comment]
Hey @aesthytik how did you fix it? I'm having a similar problem with my Gatsby build.

**Comment by aesthytik** [comment]
@wjchat are u using prismic?

**Comment by wardpeet** [comment]
That's odd, could you give us an example of what you had before? I can't see useStaticQuery on your demo site.

**Comment by aesthytik** [comment]
> That's odd, could you give us an example of what you had before? I can't see useStaticQuery on your demo site.

https://github.com/aesthytik/gatsby-test/blob/master/src/components/image.js
