### ISSUE TITLE
Dynamically rendered component in static pages only works in dev environment

### ISSUE THREAD

**Issue by JCachada** [gatsbyjs/gatsby#23204]
## Summary

Using Theme-UI and gatsbyjs, I'm attempting to have a button on my website that, when clicked, cycles between three color schemes. The button's implementation works only on the development environment (gatsby develop) and not in production (gatsby serve). I suspect this is because gatsby is generating the static content on build time and I can't properly update "state" on the component after it's been generated. I'm looking for alternative ways of achieving this behavior without having to pollute my layout class with the logic reserved for the "Change Theme" button.

## Relevant information

My button's implementation uses a simple if/else clause to decide which icon to render (all of the icons have been previously loaded through a graphql query). Then I render a button component that, when clicked, cycles through the available themes. The code for my button component that changes the theme is here:

https://github.com/JCachada/personal-website-dev/blob/master/src/components/change-theme-button.js

Then, in my layout.js, I simply insert this button with a `<ChangeThemeButton></ChangeThemeButton>` tag.

This works just fine and produces the correct behavior when I run gatsby develop, but not when I build and serve the project. In this scenario, the button doesn't even show up / get rendered, and if I assign it an initial icon, clicking that icon triggers nothing.

 I suspect gatsby's server side rendering of static pages is messing with my ability to update "state" on the original component that's already been rendered in the mean time. 

I'm looking for a way to achieve this behavior that doesn't require me to change the changing theme logic to layout.js, losing out on modularity. 

Apologies if this is a fundamental misunderstanding of how gatsby or react building blocks work - I'm still learning both, as I'm usually a backend dev.

Thank you!

**Comment by wardpeet** [comment]
Hey, I checked your website and theme-ui starts with a default theme. More info here `https://theme-ui.com/color-modes/`

I didn't saw a difference between develop & build for me. It didn't work on either.

How to fix your bug:
1. open up `src/components/change-theme-button.js` and move all variables of dark out of the theme-ui config.
```diff
export default {
  colors: {
    text: "#c0c0c0",
    background: "#111111",
    modes: {
-      dark: {
-        text: "#c0c0c0",
-        background: "#111111",
-      },
      light: {
        text: "#111111",
        background: "#ffffff",
      },
      deep: {
        text: "#c0c0c0",
        background: "#141821",
      },
    },
  },
}
```
2. replace all "dark" color-modes to "default"
```diff
- if (colorMode === "dark") {
+ if (colorMode === "default") {
```

**Comment by wardpeet** [comment]
Thank you for opening this, @JCachada

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by JCachada** [comment]
@wardpeet This is not the case/problem. If you'll notice in my project, I shadow theme-ui settings at src/gatsby-plugin-theme-ui/index.js and assign the proper "dark" name to the default theme. You can see this here: https://github.com/JCachada/personal-website-dev/blob/master/src/gatsby-plugin-theme-ui/index.js

I'm also puzzled that you didn't manage to reproduce the behavior. If I run `gatsby develop` on my repo, the button works perfectly. If I run `gatsby clean`, then `gatsby build`, then `gatsby serve -o`, the button isn't even rendered. 

Any other suggestions?

**Comment by JCachada** [comment]
Solved in https://github.com/gatsbyjs/gatsby/issues/23253
