### ISSUE TITLE
Gatbsy is breaking the styles when having two components rendering in the same page

### ISSUE THREAD

**Issue by ferreiro** [gatsbyjs/gatsby#23212]
### Context of the problem

I'm building an [application](http://developersindepth.com/) using Gatsby, Firebase and Emotion for CSS-in-JS. Since it's not yet launched, the app is blocking users to access the website, and they are prompt with a *signup form*.

However, when the user has a valid access token (so they can access the beta version), Gatbsy is rendering the real website using the stylesheets from the landing page component:
![Screen Shot 2020-04-17 at 4 30 25 AM](https://user-images.githubusercontent.com/7242959/79526009-8e420e00-8064-11ea-8dd9-626f1e780a74.png)
![Screen Shot 2020-04-17 at 4 30 38 AM](https://user-images.githubusercontent.com/7242959/79526135-e547e300-8064-11ea-8f6c-8d0949062d62.png)

### Steps to reproduce

1. Go [to this website](http://developersindepth.com/)
2. Open your chrome console.
3. Add a token in your local storage. localStorage.token = 'mytoken'
4. Refresh. You will see now the home page of the application
5. As you see, it's incorrectly applying the CSS FROM the landing page (the container...).

### Expected result

Each page is individual and you don't see any styles from landing page being applied in the other page.

### Actual result

Home page is getting styles from landing page.

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.4.3 => 2.20.22 
    gatsby-plugin-emotion: 4.1.24 => 4.1.24 
    gatsby-plugin-firebase: 0.2.0-beta.4 => 0.2.0-beta.4 
    gatsby-plugin-google-analytics: 2.2.2 => 2.2.2 
    gatsby-plugin-manifest: 2.3.3 => 2.3.3 
    gatsby-plugin-meta-redirect: 1.1.1 => 1.1.1 
    gatsby-plugin-react-helmet: 3.2.1 => 3.2.1 
    gatsby-plugin-react-svg: 3.0.0 => 3.0.0 
    gatsby-plugin-typography: 2.3.24 => 2.3.24 
    gatsby-source-filesystem: 2.1.55 => 2.1.55 
    gatsby-transformer-json: 2.2.27 => 2.2.27 
  npmGlobalPackages:
    gatsby-cli: 2.10.9

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
