### ISSUE TITLE
gatsby npm install wrong

### ISSUE THREAD

**Issue by aslkami** [gatsbyjs/gatsby#23210]
cwebp-bin@5.1.0 postinstall E:\demo\gatsby_blog\node_modules\cwebp-bin
  ‼ getaddrinfo ENOENT raw.githubusercontent.com
  ‼ cwebp pre-build test failed
  i compiling from source

mozjpeg@6.0.1 postinstall E:\demo\gatsby_blog\node_modules\mozjpeg
  ‼ getaddrinfo ENOENT raw.githubusercontent.com
  ‼ mozjpeg pre-build test failed
  i compiling from source

### Expected result

npm install sucessfully

### Actual result

npm install failed

### Environment

os: window

**Comment by wardpeet** [comment]
@aslkami can you show us more info about your env and your website?

```
Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by aslkami** [comment]
when i ran  `npm i` , it show
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.

> sharp@0.25.2 install E:\demo\gatsby_blog\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\fate\AppData\Roaming\npm-cache\_libvips\libvips-8.9.1-win32-x64.tar.gz
info sharp Creating E:\demo\gatsby_blog\node_modules\sharp\build\Release
info sharp Copying DLLs from E:\demo\gatsby_blog\node_modules\sharp\vendor\lib to E:\demo\gatsby_blog\node_modules\sharp\build\Release

> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\bmp\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\core\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\custom\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\gif\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\jpeg\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-blit\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-blur\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-circle\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-color\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-contain\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-cover\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-crop\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-displace\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-dither\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-fisheye\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-flip\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-gaussian\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-invert\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-mask\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-normalize\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-print\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-resize\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-rotate\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-scale\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-shadow\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugin-threshold\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\plugins\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\png\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\tiff\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\types\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\@jimp\utils\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.11 postinstall E:\demo\gatsby_blog\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall E:\demo\gatsby_blog\node_modules\jimp\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> gatsby-telemetry@1.2.4 postinstall E:\demo\gatsby_blog\node_modules\gatsby-telemetry
> node src/postinstall.js || true


> cwebp-bin@5.1.0 postinstall E:\demo\gatsby_blog\node_modules\cwebp-bin
> node lib/install.js

  ‼ read ECONNRESET
  ‼ cwebp pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "./configure --disable-shared --prefix="E:\demo\gatsby_blog\node_modules\cwebp-bin\vendor" --bindir="E:\demo\gatsby_blog\node_modules\cwebp-bin\vendor""
'.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���


    at E:\demo\gatsby_blog\node_modules\bin-build\node_modules\execa\index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

> mozjpeg@6.0.1 postinstall E:\demo\gatsby_blog\node_modules\mozjpeg
> node lib/install.js

  ‼ read ECONNRESET
  ‼ mozjpeg pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -fiv"
'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���


    at E:\demo\gatsby_blog\node_modules\bin-build\node_modules\execa\index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

> pngquant-bin@5.0.2 postinstall E:\demo\gatsby_blog\node_modules\pngquant-bin
> node lib/install.js

  ‼ read ECONNRESET
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at E:\demo\gatsby_blog\node_modules\bin-build\node_modules\execa\index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\fork-ts-checker-webpack-plugin\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules\fsevents\node_modules\abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\abbrev' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules\fsevents\node_modules\ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\ansi-regex' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules\fsevents\node_modules\aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\aproba' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules\fsevents\node_modules\balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\balanced-match' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.1.4 (node_modules\fsevents\node_modules\chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\chownr' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules\fsevents\node_modules\code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\code-point-at' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules\fsevents\node_modules\concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\concat-map' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules\fsevents\node_modules\console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\console-control-strings' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules\fsevents\node_modules\core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\core-util-is' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules\fsevents\node_modules\deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\deep-extend' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules\fsevents\node_modules\delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\delegates' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules\fsevents\node_modules\detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\detect-libc' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules\fsevents\node_modules\fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\fs.realpath' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules\fsevents\node_modules\has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\has-unicode' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules\fsevents\node_modules\inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\inherits' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules\fsevents\node_modules\ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\ini' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules\fsevents\node_modules\isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\isarray' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.5 (node_modules\fsevents\node_modules\minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\minimist' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@2.1.2 (node_modules\fsevents\node_modules\ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\ms' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.ms.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm-normalize-package-bin@1.0.1 (node_modules\fsevents\node_modules\npm-normalize-package-bin):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\npm-normalize-package-bin' -> 
'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.npm-normalize-package-bin.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules\fsevents\node_modules\number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\number-is-nan' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules\fsevents\node_modules\object-assign):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\object-assign' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.object-assign.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-homedir@1.0.2 (node_modules\fsevents\node_modules\os-homedir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\os-homedir' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.os-homedir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules\fsevents\node_modules\os-tmpdir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\os-tmpdir' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.os-tmpdir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.1 (node_modules\fsevents\node_modules\path-is-absolute):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\path-is-absolute' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.path-is-absolute.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@2.0.1 (node_modules\fsevents\node_modules\process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\process-nextick-args' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.process-nextick-args.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules\fsevents\node_modules\safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\safe-buffer' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safer-buffer@2.1.2 (node_modules\fsevents\node_modules\safer-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\safer-buffer' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.safer-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.4 (node_modules\fsevents\node_modules\sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\sax' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.sax.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.7.1 (node_modules\fsevents\node_modules\semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\semver' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.semver.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: set-blocking@2.0.0 (node_modules\fsevents\node_modules\set-blocking):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\set-blocking' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.set-blocking.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: signal-exit@3.0.2 (node_modules\fsevents\node_modules\signal-exit):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\signal-exit' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.signal-exit.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules\fsevents\node_modules\strip-json-comments):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\strip-json-comments' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.strip-json-comments.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules\fsevents\node_modules\util-deprecate):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\util-deprecate' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.util-deprecate.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules\fsevents\node_modules\wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\wrappy' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules\fsevents\node_modules\yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\yallist' -> 'E:\demo\gatsby_blog\node_modules\fsevents\node_modules\.yallist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.2 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fate\AppData\Roaming\npm-cache\_logs\2020-04-17T08_40_53_215Z-debug.log

**Comment by aslkami** [comment]
I wanna reinstall the node_module, and it failed, And I try to gatsby new blog, it had same problem
I could not install successfully!  But it works 2 days ago
I don't know why.

**Comment by aslkami** [comment]
here are my dependences
"dependencies": {
    "gatsby": "^2.20.12",
    "gatsby-image": "^2.3.1",
    "gatsby-plugin-manifest": "^2.3.3",
    "gatsby-plugin-offline": "^3.1.2",
    "gatsby-plugin-react-helmet": "^3.2.1",
    "gatsby-plugin-sharp": "^2.5.3",
    "gatsby-remark-images": "^3.2.2",
    "gatsby-remark-relative-images": "^0.3.0",
    "gatsby-source-contentful": "^2.2.7",
    "gatsby-source-filesystem": "^2.2.2",
    "gatsby-transformer-remark": "^2.7.1",
    "gatsby-transformer-sharp": "^2.4.3",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^5.2.1",
    "typeface-source-sans-pro": "^1.1.5"
  },
  "devDependencies": {
    "env-cmd": "^10.1.0",
    "gatsby-plugin-stylus": "^2.2.1",
    "imagemin-pngquant": "^8.0.0",
    "prettier": "^1.19.1"
  }

OS: Window

**Comment by aslkami** [comment]
> @aslkami can you show us more info about your env and your website?
> 
> ```
> Run `gatsby info --clipboard` in your project directory and paste the output here.
> ```

It still doesn't make sense /(ㄒoㄒ)/~~

**Comment by wardpeet** [comment]
This is odd indeed, I installed blog starter and did not have any issues.

Perhaps reinstall windows-build tools? `npm install --global windows-build-tools`

**Comment by aslkami** [comment]
> This is odd indeed, I installed blog starter and did not have any issues.
> 
> Perhaps reinstall windows-build tools? `npm install --global windows-build-tools`

‼ getaddrinfo ENOENT raw.githubusercontent.com
  ‼ cwebp pre-build test failed
  i compiling from source
  × RequestError: getaddrinfo ENOTFOUND downloads.webmproject.org
    at ClientRequest.<anonymous> (E:\demo\gatsby_blog\node_modules\download\node_modules\got\index.js:111:21)
    at Object.onceWrapper (events.js:297:20)
    at ClientRequest.emit (events.js:209:13)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

I try again，and I  failed

**Comment by donaldboulton** [comment]
Forget installing Gatsby after "gatsby": "^2.19.39", Its build is for mac computers now.
They use fs and fs-events to much which is not windows installable or compatible.
This core-js stuff has gotten way out of control with no end in site, Goodby Gatsby off to Docusarus.
To may errors on gatsby-cli and gatsby over 700 errors lately, did not used to have any errors???
Try version 12.19.39

**Comment by aslkami** [comment]
> Forget installing Gatsby after "gatsby": "^2.19.39", Its build is for mac computers now.
> They use fs and fs-events to much which is not windows installable or compatible.
> This core-js stuff has gotten way out of control with no end in site, Goodby Gatsby off to Docusarus.
> To may errors on gatsby-cli and gatsby over 700 errors lately, did not used to have any errors???
> Try version 12.19.39

I have to apply proxy to install，now it works

**Comment by mcljs** [comment]
> > Olvídate de instalar Gatsby después de "gatsby": "^ 2.19.39", su compilación es para computadoras Mac ahora. 
> > Usan fs y fs-events para mucho, lo que no es instalable o compatible con Windows. 
> > Estas cosas de core-js se salieron de control sin fin en el sitio, Goodby Gatsby se fue a Docusarus. 
> > ¿Puede haber errores en gatsby-cli y gatsby más de 700 errores últimamente, no solía tener ningún error? 
> > Pruebe la versión 12.19.39
> 
> Tengo que aplicar proxy para instalar, ahora funciona

Explicame para hacerlo desde mi pc por favor, tambien tengo el mismo problema

**Comment by thiagomgd** [comment]
> Forget installing Gatsby after "gatsby": "^2.19.39", Its build is for mac computers now.
> They use fs and fs-events to much which is not windows installable or compatible.
> This core-js stuff has gotten way out of control with no end in site, Goodby Gatsby off to Docusarus.
> To may errors on gatsby-cli and gatsby over 700 errors lately, did not used to have any errors???
> Try version 12.19.39

waaaaiiittt
You mean gatsby won't work on windows anymore?
Glad I saw that, I was going to move my blog to Gatsby and, although I'm on a mac today, my main computer is windows.

**Comment by UncleWang8898** [comment]
error An unexpected error occurred: "/Users/moutai/moufans.com/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: sh
Arguments: -c node lib/install.js
Directory: /Users/moutai/moufans.com/node_modules/pngquant-bin
Output:
⚠ connect ECONNREFUSED 0.0.0.0:443
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng is installed
    at /Users/moutai/moufans.com/node_modules/bin-build/node_modules/execa/index.js:231:11

**Comment by AlexanderMZhao** [comment]
Same error here. But it was gone after I connected VPN.

**Comment by wardpeet** [comment]
It seems like a firewall issue

**Comment by winkerwinker** [comment]
the same problem occurred when I run the `gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-blog`.

**Comment by winkerwinker** [comment]
the same problem occurred when I run the` gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-blog`.This problem maybe because you can't connect to `raw.githubusercontent.com`.  you can test ping to  ` raw.githubusercontent.com`.If you cannot connect to the host, that means DNS cache pollution. I have resolved the problem by using yogaDNS.
