### ISSUE TITLE
docs: Add short detailed explanation why browser globals are not available

### ISSUE THREAD

**Issue by shennan** [gatsbyjs/gatsby#23213]
## Summary

Find a way around denying application writers the ability to use browser globals (e.g `window`, `document`) freely without suffering errors/warnings.

### Motivation

As outlined in [Debugging HTML](https://www.gatsbyjs.org/docs/debugging-html-builds/), Gatsby suffers an unusual quirk in that it doesn't allow the use of browser globals without a logical check to see if they exist first. The implication is that this is a compiling issue, and a necessary evil in Gatsby-land. The solution touted by the documentation is to simply check if the global exists first, with a less-then-pretty type checking method:

```
if (typeof window !== `undefined`) {

  /* Do your worst */

}
```

It seems like a strange requirement for an application that is destined for the browser to expect Gatsby developers to write their code with this quirk constantly in-mind. It means they must write everything a little bit differently to how they would in any other React application.

Aside from the inconvenience of peppering code with Gatsby-centric logic, there are several practical issues with this quirk:

- Portability; porting code from a non-Gatsby project becomes harder
- Consistency; Gatsby development builds often silently ignore this issue, creating a false-positive where production builds then fail
- Community; every module that hard-references browser globals creates a problem for the consumer. Asking a module developer to "get the module patched" (as the [documentation suggests](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules)) seems a bit presumptuous.

At the very least, an in-depth technical explanation within the documentation explaining specifically why this is _**impossible**_ to achieve with Gatsby's current approach, would perhaps allay any doubt that the quirk was absolutely necessary.

**Comment by LekoArts** [comment]
Thanks for the issue!

> Gatsby suffers an unusual quirk in that it doesn't allow the use of browser globals without a logical check to see if they exist first

This is not Gatsby specific at all, everything that runs in a Node process or does SSR if you will suffers from that (e.g. Next.js too).

> Portability; porting code from a non-Gatsby project becomes harder

That depends on the libraries, most of the popular libraries handle SSR now.

> Consistency; Gatsby development builds often silently ignore this issue, creating a false-positive where production builds then fail

This is tracked here: https://github.com/gatsbyjs/gatsby/issues/10706

> At the very least, an in-depth technical explanation within the documentation explaining specifically why this is impossible to achieve with Gatsby's current approach, would perhaps allay any doubt that the quirk was absolutely necessary.

Thus I edited your title so that we can get a little explanation at the bottom in.

**Comment by shennan** [comment]
Thanks for a quick response. And good to see there is an issue tracked on the last point.

I understand that Node errors out on Browser-specific global variables, but from a user experience perspective it's disappointing that I must adjust code that is destined for the browser to account for this "gotcha". I expect the code itself to be fully replicated in the browser, and I don't expect the mangle of compilation to change it drastically. Perhaps I don't understand how Gatsby is changing my code when it's being compiled. In my ignorance I'm thinking; why not encapsulate the code?

Of course, an explanation as to **_why_** may be all that Gatsby can provide - but I think it should be detailed rather than "short" (as in your issue title adjustment).

We already have a "short" version. What I think is preferable is a more detailed explanation of why this cannot be implemented (either by encapsulating the compiled code somehow or by some other means of compilation). So I have edited the issue title to reflect that.

**Comment by LekoArts** [comment]
> I understand that Node errors out on Browser-specific global variables, but from a user experience perspective it's disappointing that I must adjust code that is destined for the browser to account for this "gotcha". I expect the code itself to be fully replicated in the browser, and I don't expect the mangle of compilation to change it drastically. Perhaps I don't understand how Gatsby is changing my code when it's being compiled. In my ignorance I'm thinking; why not encapsulate the code?

Gatsby is not changing your code, it runs it in a Node environment/process. And browser globals are not accessible in a Node environment. It would be unexpected behavior that Gatsby would change code (e.g. guard against browser globals) -- it's not something Gatsby should do ever.

As I said it's the library author's responsibility to think about SSR as it wouldn't be safe at all to try to monkey-patch things.

> We already have a "short" version. What I think is preferable is a more detailed explanation of why this cannot be implemented (either by encapsulating the compiled code somehow or by some other means of compilation)

I don't think that there is a "detailed explanation" you can give as it's as simple as:

It's runs in a Node environment and hence browser globals are not accessible. It's not safe at all to let Gatsby try to fix your code so it's the task of the library authors or users to guard against it.

As this is currently missing.

**Comment by shennan** [comment]
Perhaps I wasn't making myself clear; I understand already (as I believe most do) that browser variables are not available in Node. But compilers don't typically need to _run_ all of the code that they're compiling. Why is it not possible for Gatsby to simply compile the Gatsby build without running user space code (the code that is destined for a browser)? This is what I meant by using encapsulation to fix the problem.

**Comment by ascorbic** [comment]
The trouble is that in order to pre-render the HTML, we have to run the component's render function. If your render function accesses a browser global we have to assume that the browser global is required in order to render. If it isn't required, then you can either check if it exists (I recommend optional chaining if it makes sense for your situation), or better still by putting the code that accesses it into a `useEffect` hook, which isn't needed for SSR so is only run in the browser.

We could probably explain this better. We already intercept these errors and improve the wording, but we might be able to do that better.

**Comment by shennan** [comment]
Thanks @ascorbic, that is a clearer explanation of the _why_.

It's surprising to me that not more problems arise from this approach when running render functions in a non-browser environment. Has anybody ever had the crazy idea of running them in an emulated browser environment? Asking for a friend...
