### ISSUE TITLE
Page preload not working for all pages

### ISSUE THREAD

**Issue by TomiTakussaari** [gatsbyjs/gatsby#2321]
Gatsby: 1.9.43
Node: v6.10.2

So when user loads first page in Gatsby site, Gatsby starts to preload other pages asynchronously, which means that usually there is no delay between clicking internal link and showing content behind it.

However, I have managed to somehow create site where this does not happen.
Gatsby preloads just a few of the pages, which means that when user clicks a link, there is a delay while Gatsby loads page's JS scripts.

Unfortunately my site is not yet public, so I cannot share it or the code, but there is'nt anything that I can think that would cause this. 
Just somewhat usual combination of markdown and plain .js pages.

Anyone have any ideas on how I should start investigate this ? 
What code is responsible for starting that preload sequence on first page load ?

**Comment by KyleAMathews** [comment]
Yeah preloading is triggered by gatsby-link. You could look in there for the code at work. So links in markdown won't trigger preloading. It'd be a cool plugin that'd automatically setup preloading for a markdown page. It'd need to extract out links and then in the client, trigger preloading whenever that page is visited.

**Comment by KyleAMathews** [comment]
For a smaller site, it should be quite doable to manually setup preloading in gatsby-browser.js in response to route changes.

Would be nice to automate this someday.

**Comment by TomiTakussaari** [comment]
Ah, that explains it all. Thanks!

I have both links in markdown, and I also use navigateTo, instead of Link element, in some places, so I'll have to see what I can do. Atleast replacing navigateTo with Link should be doable.

I'll report back here if I come up with something reusable.

**Comment by sebastienfi** [comment]
@TomiTakussaari Have you tried `gatsby-plugin-catch-links` ? Looking at its source code it seems to me that hyperlinks in markdown would trigger the function and act as is a `gatsby-link` were used in the first place.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-catch-links/src/catch-links.js

**Comment by KyleAMathews** [comment]
@sebastienfi gatsby-plugin-catch-links just does the redirect but it doesn't do preloading.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
