### ISSUE TITLE
Slow page renders (probably because of page-data.json) on Gatsby app hosted in Netlify

### ISSUE THREAD

**Issue by johnmikel** [gatsbyjs/gatsby#23222]
## Summary
Slow page renders (probably because of page-data.json) on Gatsby app hosted in Netlify

## Relevant information

I've built a web app using Gatsby over at https://polee.co. For some reason, the pages are loading slowly. Checking the network tab (I'm using Chrome), the page-data.json files take too much time to load upon navigation. I don't know where to start to troubleshoot this. I've previously built a Gatsby app at https://tashgeel-doha.com and I am dumbfounded by this issue.

The two links I have sent are both hosted in Netlify.

### Environment (if relevant)
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.8.2 => 2.13.50
    gatsby-cli: ^2.11.3 => 2.11.3
    gatsby-image: ^2.1.2 => 2.2.8
    gatsby-plugin-create-client-paths: ^2.0.5 => 2.1.3
    gatsby-plugin-less: ^2.0.13 => 2.1.2
    gatsby-plugin-manifest: ^2.1.1 => 2.2.4
    gatsby-plugin-nprogress: ^2.0.10 => 2.1.2
    gatsby-plugin-offline: ^2.1.1 => 2.2.4
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.3
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1
    gatsby-plugin-sass: ^2.0.11 => 2.1.4
    gatsby-plugin-sharp: ^2.1.3 => 2.2.9
    gatsby-plugin-styled-components: ^3.0.7 => 3.1.2
    gatsby-plugin-typescript: ^2.1.2 => 2.1.2
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.0.38 => 2.1.8
    gatsby-transformer-sharp: ^2.1.21 => 2.2.5

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wardpeet** [comment]
Hey,

There are a few things here. I've noticed you're running Gatsby v2.13.50. I would advice upgrading to the latest version, we've don't some improvements to how we bundle things.

When looking through your bundle I saw some big libraries being used.
- axios
- @ant-design/icons
- lodash
- redux
- redux-saga
- webfontloader

They all make your initial load time slower. A few suggestions to speed things up:
- replace axios with https://npm.im/redaxios
- install https://www.gatsbyjs.org/packages/gatsby-plugin-lodash/ so lodash get smaller
- Make sure you can tree-shake @ant-design/icons (if you don't know what that means), please post how you're importing icons
- webfontloader: why do you use webfontloader?
- install https://www.gatsbyjs.org/packages/gatsby-plugin-netlify to have better loading performance on netlify.

**Comment by johnmikel** [comment]
Hey @wardpeet, imma try these tips. Thank you so much!

**Comment by ghashi** [comment]
@johnmikel , have you fixed this delay? I'm also experiencing this issue (but only on iOS 💁‍♂️).

ps: I posted it on the netlify community: https://community.netlify.com/t/gatsby-delay-to-navigate-to-link-only-on-ios/13633

**Comment by johnmikel** [comment]
@ghashi yes, almost though, there are still some improvements that I think that can be made but @wardpeet's comments were really powerful and useful. :)

**Comment by johnmikel** [comment]
Moved to Gatsby Cloud, fantastic performance!!!
