### ISSUE TITLE
[gatsby-transformer-remark] [Migration from 0.x to 1.0] Add CSS class to markdown elements

### ISSUE THREAD

**Issue by JLongley** [gatsbyjs/gatsby#2322]
I'm working on migrating my site from 0.x to 1.0. On many of my markdown pages, I've annotated the text with css classes using the syntax supported by the [markdown-it-attrs](https://github.com/arve0/markdown-it-attrs) plugin.

I see that gatsby has switched over to using remark for markdown parsing, and I've started reemplementing some of the features I lost as plugins. As far as I can tell, however, there is no existing remark plugin for adding CSS classes. Is there a plan for implementing this feature?

**Comment by KyleAMathews** [comment]
Someone else mentioning needed this. Not sure if they added a plugin. Try searching npm? If it doesn't exist, it'd be great to have it!

**Comment by JLongley** [comment]
If I find some time, I may pick this up soon.

FWIW, for the time being, I've gone back through and replaced the styled markdown tags with HTML spans.

**Comment by VinSpee** [comment]
I'd love a way to handle this feature in a remark plugin or somehow at the configuration level

**Comment by julianomoreira** [comment]
I wish Gatsby hadn't changed from `markdown-it-attrs` to `remark` because we have lots of pages with custom styles using classes. Our entire a11y procedures (40+ pages) are using custom styles. Has anyone built a way to handle custom classes with Remark?

**Comment by KyleAMathews** [comment]
It'd be great to have a Gatsby remark plugin that wraps this https://github.com/sethvincent/remark-bracketed-spans

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by vadimshvetsov** [comment]
@KyleAMathews I'm trying to implement gatsby-remark-bracketed-spans. Is it sufficient to have a code like that?

```js
const remarkBracketedSpans = require('remark-bracketed-spans')
module.exports = () => ({})
module.exports.setParserPlugins = () => [remarkBracketedSpans]
```

**Comment by KyleAMathews** [comment]
Have you checked out other remark plugins?

**Comment by vadimshvetsov** [comment]
I've thought about `gatsby-remark-katex` as example. There are some processing with nodes for getting done with katex.
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-katex/src/index.js
But below we add a markdown plugin `remark-math`, which would be used within gatsby-tranformer-remark.
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/extend-node-type.js#L86-L93
I thought its sufficient for work, isn't? 
But plugin with only `setParserPlugins` exports looks strange 😄

**Comment by vadimshvetsov** [comment]
@KyleAMathews I've made a PR #8044 with adding [remark-bracketed-spans](https://github.com/sethvincent/remark-bracketed-span) parser plugin
