### ISSUE TITLE
Potential global CSS recipe inaccuracy

### ISSUE THREAD

**Issue by Js-Brecht** [gatsbyjs/gatsby#23236]
I am curious about something that stuck out as kind of odd to me.

In the [directions](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes/styling-css.md#directions) for the `Using global CSS files without a Layout component` recipe, it says:

> Note: You can also make use of `require('./src/styles/global.css')` to import the global CSS file in your `gatsby-config.js` file.

AFAIK, `gatsby-config` is not processed by Webpack.  Saying that you can `require()` your CSS in `gatsby-config` is misleading, and will actually cause the build to fail since CSS is generally not CommonJS.

Please correct me if I'm wrong.  I didn't want to alter it without first determining if I had misunderstood the run path, or if maybe this bit was meant to convey something different than what it currently does.

**Comment by marcysutton** [comment]
Hi there! The recipe talks about using `gatsby-browser.js`, and that's what the examples show. From looking at [the PR that introduced that recipe](https://github.com/gatsbyjs/gatsby/pull/17359) before we broke them up into sections, looks like it was an erroneous note that was left in despite being raised by the reviewer. 

If you've got time to contribute a PR to remove that note, that would be super helpful!

**Comment by Js-Brecht** [comment]
Sure thing!
