### ISSUE TITLE
failed Building production JavaScript and CSS bundles

### ISSUE THREAD

**Issue by xBLADEx** [gatsbyjs/gatsby#23246]
I didn't know where else to turn to, searched everything I could but I'm stuck.
During gatsby build or npm run build I get this Unknown word error.
I'm using SCSS files and I can't help but wonder if that is the culprit since it points to a problem with styles.css. 
I've removed node modules, removed cache, restarted everything. 
Develop works perfectly, but build breaks and cannot complete.

plugins has `gatsby-plugin-sass`, no options being used.
I have node-sass. Where should I look?
```
D:\MAMP\htdocs\project (master -> origin)                                   
λ npx gatsby build                                                                 
success open and validate gatsby-configs - 0.021s                                  
success load plugins - 0.657s                                                      
success onPreInit - 0.002s                                                         
success delete html and css files from previous builds - 0.012s                    
success initialize cache - 0.005s                                                  
success copy gatsby files - 0.047s                                                 
success onPreBootstrap - 0.007s                                                    
success createSchemaCustomization - 0.004s                                         
success source and transform nodes - 0.276s                                        
success building schema - 0.201s                                                   
success createPages - 1.740s                                                       
success createPagesStatefully - 0.038s                                             
success onPreExtractQueries - 0.001s                                               
success update schema - 0.018s                                                     
success extract queries from components - 0.259s                                   
success write out requires - 0.004s                                                
success write out redirect data - 0.001s                                           
success onPostBootstrap - 0.001s                                                   
⠀                                                                                  
info bootstrap finished - 5.059 s                                                  
⠀                                                                                  
failed Building production JavaScript and CSS bundles - 4.994s                     
                                                                                   
 ERROR #98123  WEBPACK                                                             
                                                                                   
Generating JavaScript bundles failed                                               
                                                                                   
D:\MAMP\htdocs\project \styles.48f74db053b2eb5ceb4c.css:382:5: Unknown word  
                                                                                   
not finished run queries - 5.947s 
```

**Comment by xBLADEx** [comment]
Commenting out my single scss import allowed me to build. This line is in my Layout.js:
```
import '../assets/scss/index.scss';
```

**Comment by TylerBarnes** [comment]
Hi @xBLADEx !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by xBLADEx** [comment]
Ok cool, I will work on setting up a reproduction, I might even be able to narrow in myself, thanks for the response.

**Comment by xBLADEx** [comment]
So the problem was caused by setting a background image with a .svg in the .scss file. Still figuring out why but closing this as it's not a gatsby build issue.

**Comment by crazydev901** [comment]
@xBLADEx how did you solve the issue?

**Comment by mosesoak** [comment]
@xBLADEx just ran into the exact same problem

**Comment by mfanuzzi** [comment]
for those who may run into this in the future; in our case it was due to a bug within `cssnano`, that has just recently been patched:

https://github.com/gatsbyjs/gatsby/issues/31589
