### ISSUE TITLE
Filtering through reference field running fine on local Server but after being deployed on Netlify or even on local Build its not working 

### ISSUE THREAD

**Issue by amaan-nadeem** [gatsbyjs/gatsby#23258]
## Description
When filtering through a reference field through page query in graphql working on local host after clearing cache and rerun graphql doesnot aware about it so we need to move the query manually a bit to run it again like move the query code from line 11 to 12 then it gives the expected result. . The scenario is that i have a specific reference field in all coupon cards that i have in contentful where i have two separate content models for store and coupon cards each coupon card created on contentful is related to any specific store and for that i have given a field in it named storeReference which stores a reference of the store it belongs. Both content models have different fields where each store is related to specific category like food, health, tech etc. I wanted to query all those coupon cards which is related to specific category which i can found on each card storeReference nested field category. But when i'm trying doing it, it gives me the data on local server not at first but after moving query code a bit like i explain above.  After deploying the site on netlify all these filtered cards are not being queried and not been shown on the deployed site.

## view of an entry of one coupon card entry 
![DeepinScreenshot_select-area_20200418192702](https://user-images.githubusercontent.com/44071255/79640356-ab80f480-81aa-11ea-9757-c3f2f061e7ad.png)

this is actual query code which is working fine on graphql playground and on local server and build but not on deployed server.

```
  allContentfulCouponCard(
    limit: 18
    filter: { storeReference: { category: { eq: "clothing & shoe" } } }
  ) {
    edges {
      node {
        contentful_id
        discount
        couponType
        discountDescription
        totalHits
        sitewide
        verified
        cardLogo {
          fluid(maxWidth: 400) {
            src
          }
        }
        details {
          details {
            details
            minimumOrder
            exclusion
          }
        }
        storeReference {
          slug
          storeName
          category
        }
        verified
        sitewide
        createdAt
        id
        expiryDate
        revealCode
        dealUrl
      }
    }
  }
```
### Expected result
This is picture of local server

![DeepinScreenshot_select-area_20200418193122](https://user-images.githubusercontent.com/44071255/79640485-47aafb80-81ab-11ea-8327-d5b7eead4474.png)

```
{
  "data": {
    "allContentfulCouponCard": {
      "edges": [
        {
          "node": {
            "contentful_id": "7pd562XJBtCT2A1oQj1knv",
            "discount": "save",
            "couponType": "reveal",
            "discountDescription": "Wall Art, Decor, Accent Pieces & Home Essentials from under $10 ",
            "totalHits": 0,
            "sitewide": false,
            "verified": false,
            "cardLogo": {
              "fluid": {
                "src": "//images.ctfassets.net/7xb0xkjda9hw/flCqhEBzGhDFuY3LndFEo/f95a20e46cc0aa3df8b1cc00197c95a4/Pampering-Products.jpg?w=400&q=50"
              }
            },
            "details": null,
            "storeReference": {
              "slug": "helly-hansen",
              "storeName": "helly hensen",
              "category": "clothing & shoe"
            },
            "createdAt": "2020-04-16T14:41:37.673Z",
            "id": "141cf5df-951c-5892-8cf3-73fe76cacc5e",
            "expiryDate": null,
            "revealCode": "EB452",
            "dealUrl": null
          }
        }
      ]
    }
  }
}
```

### Actual result
this one is of deployed website

![DeepinScreenshot_select-area_20200418193142](https://user-images.githubusercontent.com/44071255/79640490-50033680-81ab-11ea-8ae8-77f2b61c8f00.png)

on after deploy the json data above is not been queried and thus no response is coming 

I shall be very thankful if anyone of you could explain and resolve this issue
### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by beldur** [comment]
Hi @LekoArts,

we are running into the same issue at my company. The error seems to happen only during `gatsby build` and is not deterministic.

Here is a minimal setup to reproduce:

1. Create a ContentModel "Item" with two fields
   - ItemTitle of type ShortText
   - Image of type Reference
2. Create a ContentModel "Image" with two fields
   - ImageTitle of type ShortText
   - ImagePath of type ShortText
3. Create some Item Entries and Image Entries and reference them each other
4. Write a graphql Query that looks like this:
```
query {
  allContentfulItem(filter: { image: { title: { eq: "Landscape" } } }) {
    nodes {
      title
    }
  }
}
```
5. Write a 2nd graphql Query that looks like this:
```
query {
  allContentfulItem(filter: { image: { path: { eq: "/path/to/landscape/image" } } }) {
    nodes {
      title
    }
  }
}
```
6. Execute these two queries after another in gatsby's `createPages`.

The crazy thing now is, that we only get the result for the first query. Not the second.
When we switch the execution order of the queries, we still get only a result for the first query.
