### ISSUE TITLE
Dynamically rendering components only working in dev (not production)

### ISSUE THREAD

**Issue by JCachada** [gatsbyjs/gatsby#23253]
**Reopening from this https://github.com/gatsbyjs/gatsby/issues/23204** as it didn't get solved.

## Summary

Using Theme-UI and gatsbyjs, I'm attempting to have a button on my website that, when clicked, cycles between three color schemes. The button's implementation works only on the development environment (gatsby develop) and not in production (gatsby serve). I suspect this is because gatsby is generating the static content on build time and I can't properly update "state" on the component after it's been generated. I'm looking for alternative ways of achieving this behavior without having to pollute my layout class with the logic reserved for the "Change Theme" button.

Steps to reproduce:

1. Clone my repo at https://github.com/JCachada/personal-website-dev

2. Install dependencies with npm install.

3. Run `gatsby develop`. The button in the header for changing themes should work fine and change themes when clicked.

4. Run `gatsby build`, then `gatsby serve -o`. In the production build, the button doesn't get rendered and attempting to click it does nothing.

## Relevant information

My button's implementation uses a simple if/else clause to decide which icon to render (all of the icons have been previously loaded through a graphql query). Then I render a button component that, when clicked, cycles through the available themes. The code for my button component that changes the theme is here:

https://github.com/JCachada/personal-website-dev/blob/master/src/components/change-theme-button.js

Then, in my layout.js, I simply insert this button with a `<ChangeThemeButton></ChangeThemeButton>` tag.

This works just fine and produces the correct behavior when I run gatsby develop, but not when I build and serve the project. In this scenario, the button doesn't even show up / get rendered, and if I assign it an initial icon, clicking that icon triggers nothing.

I suspect gatsby's server side rendering of static pages is messing with my ability to update "state" on the original component that's already been rendered in the mean time. 

I'm looking for a way to achieve this behavior that doesn't require me to change the changing theme logic to layout.js, losing out on modularity. 

Apologies if this is a fundamental misunderstanding of how gatsby or react building blocks work - I'm still learning both, as I'm usually a backend dev.

Thank you!

**Comment by vladar** [comment]
I suspect that in develop, you have a `colorMode` saved in localStorage which allows you cycling through `dark`, `deep` and `light`.

But you don't handle the case when `colorMode === "default"` (which is the [default value in theme ui](https://theme-ui.com/color-modes/)).

Try clearing localStorage in develop and I suspect you'll see what I mean.

**Comment by JCachada** [comment]
Hi @vladar,

I don't think 'default' is the issue, as I shadow the theme-ui settings here:

https://github.com/JCachada/personal-website-dev/blob/master/src/gatsby-plugin-theme-ui/index.js

'default' should no longer be a mode when shadowing this way. I checked some popular themes (like LekoArts') and they cycle between just "light" and "dark" with no "default" by shadowing in this manner.

**Comment by vladar** [comment]
I tried your repo locally and did `console.log(colorMode)` which reported `default` value to me on the first run.

**Comment by vladar** [comment]
Also, the following patch made it work for me (in both `serve` and `develop`):

```patch
Index: src/components/change-theme-button.js
<+>UTF-8
===================================================================
--- src/components/change-theme-button.js	(revision 54abae702f0fd91d34cec9fd0e1a502145f7155b)
+++ src/components/change-theme-button.js	(date 1587312952967)
@@ -41,7 +41,9 @@
 
   let themeImage
 
-  if (colorMode === "dark") {
+  // console.log(colorMode)
+
+  if (colorMode === "dark" || colorMode === "default") {
     themeImage = (
       <Image
         fixed={data.deepThemeButton.childImageSharp.fixed}
@@ -115,7 +117,7 @@
 }
 
 function nextTheme(colorMode) {
-  if (colorMode === "dark") {
+  if (colorMode === "dark" || colorMode === "default") {
     return "deep"
   } else if (colorMode === "deep") {
     return "light"
```

**Comment by JCachada** [comment]
Interesting. I wonder what I misunderstood about the shadowing - I was under the impression that if I shadowed the settings, default would no longer be, well, the default. Thank you for the solution!

**Comment by LekoArts** [comment]
In the future please refrain from creating duplicate issues and answer in the closed one instead. It makes it more complicated for everyone, e.g. if other people now find your first issue they won’t know about the solution.

**Comment by LekoArts** [comment]
You need to use initialColorModeName:
https://theme-ui.com/theming#configuration-flags

**Comment by JCachada** [comment]
@LekoArts Will do! I went ahead and linked to this issue in the old one to try and mitigate that problem, but will have it in mind next time. Thanks :)
