### ISSUE TITLE
gatsby-remark-autolink-headers optionally specify which header element types to link

### ISSUE THREAD

**Issue by jmadelaine** [gatsbyjs/gatsby#23250]
## Summary

`gatsby-remark-autolink-headers` adds an anchor link `<a />` as a child of each header element (`h1`, `h2`, `h3`, `h4`, `h5`, and `h6`) generated by `gatsby-transformer-remark`.

As of [v2.2.3](https://github.com/gatsbyjs/gatsby/releases/tag/gatsby-remark-autolink-headers%402.2.3) there is no way to specify the type of header element for which anchors should be generated. Anchors are automatically generated for all six header element 'depths'.

**I propose that the type of header elements for which anchors are generated be configurable.**

One way would be to add an option to the current [configuration](https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/#options):

```js
{
  resolve: `gatsby-remark-autolink-headers`,
  options: {
    elements: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']
  },
}
```

The config name and value are up for discussion. Other possible names could be `elementsToLink`, `depthsToLink`, and `depths`, and the value could be an array of element name strings `['h1', 'h2', 'h3', 'h4', 'h5', 'h6']` or simply numbers `[1, 2, 3, 4, 5, 6]`.

> I prefer numbers as they play nicely with `node.depth` (see the proposed solution below).

Proposed rules:

- If no config is provided, default to generating anchors for all header elements (this is the current behavior and **retains backwards compatibility**).
- If a config array is provided, generate anchors for header elements whose type appears in the array.
- If an empty array is provided `[]`, do not generate anchors. As length is 0, we _could_ fallback to generating all anchors, but specifying an empty array is not the same as leaving the config empty, so I propose we honor the configuration and assume it is deliberately specified as an empty array.

### Basic example

Markdown input:

```markdown
# Some H1

# Some H2

# Some H3

# Some H4

# Some H5

# Some H6
```

Config:

```js
{
  resolve: `gatsby-remark-autolink-headers`,
  options: {
    elements: [2, 5]
  },
}
```

HTML output:

```html
<h1>Some H1</h1>
<h2 id="some-h2" style="position:relative;">
  <a href="#some-h2" aria-label="some-h2 permalink" class="anchor before">
    <!-- SVG here -->
  </a>
  Some H2
</h2>
<h3>Some H3</h3>
<h4>Some H4</h4>
<h5 id="some-h5" style="position:relative;">
  <a href="#some-h5" aria-label="some-h5 permalink" class="anchor before">
    <!-- SVG here -->
  </a>
  Some H5
</h5>
<h6>Some H6</h6>
```

### Motivation

I came across this issue when building a documentation site. I use `h2` elements to organise sections of documentation, and tend to go a couple of layers deep (`h3` and `h4`), mostly for styling and readibility. I don't necessarily want all header elements to have anchors.

While the current implementation is not broken (creating anchors for _every_ header doesn't negatively impact the site), it would be nice to have more control over the generation of anchors.

### Solution

I have the following solution running locally:

```js
// gatsby/packages/gatsby-remark-autolink-headers/src/index.js

// some code above this ...

module.exports = (
  { markdownAST },
  {
    icon = svgIcon,
    className = `anchor`,
    maintainCase = false,
    removeAccents = false,
    enableCustomId = false,
    isIconAfterHeader = false,
    // New config item 'elements'
    elements = null,
  }
) => {
  slugs.reset();

  visit(markdownAST, `heading`, (node) => {

    // If elements array exists but does not include current node depth, do not create anchor...
    if (Array.isArray(elements) && !elements.includes(node.depth)) {
      return markdownAST;
    }

    // ...otherwise create anchor as usual.

    let id;
    if (enableCustomId && node.children.length > 0) {

// some more code below this ...
```

The above code expects that the `elements` config value is a `number[]`, which is easier to work with as `node.depth` is a `number` between 1 and 6 [as described here](https://github.com/syntax-tree/mdast#heading).

If we used a config of `['h1', 'h2', 'h3', 'h4', 'h5', 'h6']`, we'd have to do some string parsing which is a bit more involved.

No tests have been written yet, pending proposal feedback.

I'm happy to work on this if it's given the green light.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

I also wished that it had that capability in the past so appreciate you opening this. Your proposed rules sound reasonable.

As we all know, naming things is hard, so I'd suggest going with `elements` and `[h1, h2]` for now. `elements` could be changed once the docs team has an eye on it. If you need any help with getting started with that, please let me know :)

**Comment by jmadelaine** [comment]
Thanks @LekoArts, I've submitted a PR as discussed and will wait for feedback on naming from the docs team.
