### ISSUE TITLE
"Can't resolve" importing errors when using canvg

### ISSUE THREAD

**Issue by Pauan** [gatsbyjs/gatsby#23254]
## Description

I am speaking on behalf of amCharts. Our users have found some errors when using amCharts with Gatsby. You can see more details [here](https://github.com/amcharts/amcharts4/issues/2295).

Our library internally uses `canvg`, which uses `core-js`. When compiling, Gatsby is unable to find the `core-js` files, even though those files exist.

This is a problem specifically with Gatsby, it does not happen with create-react-app or Angular.

### Steps to reproduce

I have created a [reduced test case](https://github.com/Pauan/gatsby-core-js-error-demo).

I created it with the following steps:

1. [Create a new hello world template](https://www.gatsbyjs.org/tutorial/part-zero/#create-a-gatsby-site).

2. [Make these changes](https://github.com/Pauan/gatsby-core-js-error-demo/commit/23337d0d41c43a2c47581bfdc422ac43969f0e94).

3. Run `yarn install` and then `yarn gatsby develop`.

### Expected result

The project should compile fine.

### Actual result

I get the following errors when compiling:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.concat' in 'C:\Users\Pauan\gatsby-core-js-error-demo\node_modules\canvg\lib'

File: node_modules\canvg\lib\index.es.js


... many more similar errors ...


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/web.dom-collections.iterator' in 'C:\Users\Pauan\gatsby-core-js-error-demo\node_modules\canvg\lib'

File: node_modules\canvg\lib\index.es.js
```

I have verified that the `node_modules/canvg/node_modules/core-js/modules/*` files *do* exist, Gatsby is simply unable to find them.

### Environment

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Users\Pauan\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.20.12 => 2.20.23 
```

**Comment by LekoArts** [comment]
I just skimmed your issue and before digging deeper into it, have seen this issue already?
https://github.com/gatsbyjs/gatsby/issues/15601

Gatsby uses core-js@2 and this might be the cause of the problem?

**Comment by Pauan** [comment]
@LekoArts That shouldn't matter, because npm supports having multiple versions of the same package at the same time.

This is clear because `node_modules/core-js` is version 2, but `node_modules/canvg/node_modules/core-js` is version 3.

The problem is that Gatsby is not properly loading `core-js` from `node_modules/canvg/node_modules/core-js` like it should. In other words, Gatsby is *not* following the [Node module resolution algorithm](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders) like it should. This is a module resolution problem, not a version problem.

**Comment by Pauan** [comment]
@LekoArts After looking more deeply at the issue you linked, I found [this](https://github.com/gatsbyjs/gatsby/blob/ff911e2300fd4212d10fdef03470dd01f6075693/packages/gatsby/src/utils/webpack.config.js#L391). So it seems that Gatsby is intentionally changing the Webpack module resolution rules, which is causing core-js to break. This is related to https://github.com/gatsbyjs/gatsby/issues/15601 but it's actually a separate issue.

**Comment by aikodeio** [comment]
Hello! This is not yet resolved

**Comment by blainekasten** [comment]
So this was interested [here](https://github.com/gatsbyjs/gatsby/pull/6327) to solve [this issue](https://github.com/gatsbyjs/gatsby/issues/6030).

I'm not sure right now how to resolve your issue and not break theirs.

**Comment by blainekasten** [comment]
I personally don't understand why a library is explicitly depending on core-js and importing it's functionality. Usually libraries should just write the code to achieve a solution, and if polyfills are needed, the end users webpack/babel set up will take care of that.

**Comment by Pauan** [comment]
@blainekasten You will have to ask canvg that, we don't control their library.

Although I agree with you that core-js should be left up to the user, gatsby should still work with libraries which choose to use core-js.

Overriding specific hardcoded libraries like core-js and react-hot-loader seems like a very fragile solution.

**Comment by aikodeio** [comment]
This problem does not allow me to run my gitlab CI :( Is there a way to fix or patch?

**Comment by blainekasten** [comment]
Hey! Latest version of gatsby upgrades to core-js@3. Try out the new version, it should fix your errors!

**Comment by aikodeio** [comment]
@blainekasten Hello, I keep getting the same error (there are actually several) but this is one of them:

```
 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/web.dom-collections.for-each' in 'G:\Apps\corejs\node_modules\@amcharts\amcharts4\.internal\canvg'     

If you're trying to use a package make sure that 'core-js/modules/web.dom-collections.for-each' is installed. If you're trying to use 
a local file make sure that the path is correct.

File: node_modules\@amcharts\amcharts4\.internal\canvg\index.js 
```


```
"dependencies": {
    **"@amcharts/amcharts4": "^4.9.30",
    "gatsby": "^2.23.12",**
    "gatsby-image": "^2.4.9",
    "gatsby-plugin-manifest": "^2.4.14",
    "gatsby-plugin-offline": "^3.2.13",
    "gatsby-plugin-react-helmet": "^3.3.6",
    "gatsby-plugin-sharp": "^2.6.14",
    "gatsby-source-filesystem": "^2.3.14",
    "gatsby-transformer-sharp": "^2.5.7",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^6.1.0"
  },
```
