### ISSUE TITLE
Gatsby CLI and $NODE_PATH

### ISSUE THREAD

**Issue by angeloashmore** [gatsbyjs/gatsby#2325]
The Gatsby CLI looks for a local install of `gatsby` on the following line:

https://github.com/gatsbyjs/gatsby/blob/a4124ab7f23ea410aa06688d55c6793ec66786b1/packages/gatsby/src/gatsby-cli.js#L23

Do you think this could be changed to reference `$NODE_PATH`, with a fallback to the current implementation?

I am attempting to use Gatsby within a larger Rails app where the file structure is different than a typical Gatsby setup. Using `$NODE_PATH` would allow for more flexibility in Gatsby's root folder structure.

**Comment by angeloashmore** [comment]
There are a couple of other places that assume root-level `node_modules` and `package.json` that could also benefit from using `$NODE_PATH`:

https://github.com/gatsbyjs/gatsby/blob/a4124ab7f23ea410aa06688d55c6793ec66786b1/packages/gatsby/src/bin/cli.js#L35-L55

As a workaround, I symlinked `node_modules` and `package.json` in the Gatsby root directory (located in `app/javascript` the my Rails app).

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
