### ISSUE TITLE
[gatsby-plugin-mdx] create-webpack-config loader paths in pnpm context

### ISSUE THREAD

**Issue by ksjogo** [gatsbyjs/gatsby#23265]
Coming from #21950 

In a pnpm context with a site depending on a plugin which depends on gatsby-plugin-mdx the gatsby-plugin-mdx config wont work.
Original
```
   loader: path.join(
                `gatsby-plugin-mdx`,
                `loaders`,
                `mdx-components`
              ),
```
Has the problem that webpack running within the actual site root can't resolve the loader at that path, as the actual path would be:
`node_modules/other_plugin/node_modules/gatsby-plugin-mdx/loaders/mdx-components`.
Changing to the following seems to fix these loaders.
```
   loader: path.join(
                __dirname,
                "..",
                //`gatsby-plugin-mdx`,
                `loaders`,
                `mdx-components`
              ),
```

Though building the site will still require adding these to its package.json
```
@mdx-js/mdx": "^1.5.8",
"@mdx-js/react": "^1.5.8",
```
as they are not added to the resolve config.

**Comment by Js-Brecht** [comment]
IMO, those loaders _should_ be resolved to absolute paths.  I'd probably do it like this, but it amounts to the same thing:
```js
loader: require.resolve(
  `gatsby-plugin-mdx/loaders/mdx-components`
),
```

> Though building the site will still require adding these to its package.json
> 
> ```
> @mdx-js/mdx": "^1.5.8",
> "@mdx-js/react": "^1.5.8",
> ```
> 
> as they are not added to the resolve config.

Those are [peer dependencies](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/package.json#L16-L19) for `gatsby-plugin-mdx`, so it doesn't really make sense for _it_ to add them to the webpack config.  It kind of pushes the responsibility of dependency management off onto the consumer.

Your plugin could easily add them to the webpack config, though:
```js
// gatsby-node.js
const path = require('path');

const resolve = (pkg) => path.dirname(require.resolve(`${pkg}/package.json`))

exports.onCreateWebpackConfig = ({ actions }) => {
    actions.setWebpackConfig({
        resolve: {
            alias: {
                '@mdx-js/js': resolve('@mdx-js'),
                '@mdx-js/react': resolve('@mdx-js'),
            }
        }
    });
}
```

**Comment by Js-Brecht** [comment]
However, I don't imagine that the issues with `@mdx-js/mdx` and `@mdx-js/react` would be such an issue if you simply re-exported the `gatsby-plugin-mdx` exports:

```js
export { MDXRenderer } from 'gatsby-plugin-mdx';
```

And import that from the consumer of your plugin?  Theoretically, that should take care of the context of `@mdx-js/mdx` and `@mdx-js/react`, so long as they are installed as dependencies of your plugin :thinking:

**Comment by ksjogo** [comment]
The onCreateWebpackConfig worked great for pushing the peer dependencies up into my plugin, thank you.

The concrete site is actually not using the MDXRenderer directly, as all the templates are provided by my plugin.

I am not sure what you mean with "those loaders should be resolved to absolute paths" as they already are in that format currently.

https://github.com/gatsbyjs/gatsby/blob/4043129519dd466e4468527656175465cf3f916b/packages/gatsby-plugin-mdx/gatsby/create-webpack-config.js#L50

https://github.com/gatsbyjs/gatsby/blob/4043129519dd466e4468527656175465cf3f916b/packages/gatsby-plugin-mdx/wrap-root-element.js#L26

**Comment by Js-Brecht** [comment]
> The concrete site is actually not using the MDXRenderer directly, as all the templates are provided by my plugin.

Maybe it would help to see your repo, or a simplified example.

> I am not sure what you mean with "those loaders should be resolved to absolute paths" as they already are in that format currently.

FS absolute, not “Node” absolute.  Using a (real) absolute path means Webpack doesn’t have to do any resolution to find the file.
