### ISSUE TITLE
gatsby-source-shopify throwing error on netlify build

### ISSUE THREAD

**Issue by moritzsalla** [gatsbyjs/gatsby#23278]
# Description

This plugin works during local builds and returns an error during Netlify builds.

### Steps to reproduce

I've set up a minimal Gatsby site that queries product names from the Shopify Storefront API.
Querying data works on my computer – the site builds without complaints and displays correctly.

When deploying from my Github repo, however, the plugin throws an error, causing the build to fail on both Netlify and Zeit.

#### Page Query

```jsx
const SecondPage = ({ data }) => {
  const product = data.allShopifyProduct.edges

  return (
    <Layout>
      <SEO title="Products" />
      <ul>
        {product.map(i => (
          <li key={i}>{i.node.vendor}</li>
        ))}
      </ul>
      <Link to="/">Go back to the homepage</Link>
    </Layout>
  )
}

export const query = graphql`
  query queryVendors {
    allShopifyProduct {
      edges {
        node {
          vendor
        }
      }
    }
  }
`

export default SecondPage
```

#### gatsby-config.js

```js
{
      resolve: "gatsby-source-shopify",
      options: {
        shopName: process.env.SHOPIFY_STORE_NAME,
        accessToken: process.env.SHOPIFY_ACCESS_TOKEN,
        apiVersion: "2020-04",
        verbose: true,
        paginationSize: 250,
        includeCollections: ["shop", "content"],
      },
},
```

#### Local Build

The site is deploying from Netlify without build errors, just as it does locally:

```console
$ gatsby build
success open and validate gatsby-configs - 0.043s
success load plugins - 5.525s
success onPreInit - 0.004s
success delete html and css files from previous builds - 0.017s
success initialize cache - 0.006s
success copy gatsby files - 0.462s
success onPreBootstrap - 0.038s
success createSchemaCustomization - 0.006s

gatsby-source-shopify/XXXXXXXXXX starting to fetch data from Shopify

gatsby-source-shopify/XXXXXXXXXX fetched and processed Page nodes: 728.707ms

gatsby-source-shopify/XXXXXXXXXX fetched and processed Article nodes: 732.245ms

gatsby-source-shopify/XXXXXXXXXX fetched and processed Collection nodes: 754.611ms

gatsby-source-shopify/XXXXXXXXXX fetched and processed ShopPolicy nodes: 738.58ms

gatsby-source-shopify/XXXXXXXXXX fetched and processed Product nodes: 759.498ms

gatsby-source-shopify/XXXXXXXXXX fetched and processed Blog nodes: 1.269s

gatsby-source-shopify/XXXXXXXXXX finished fetching data from Shopify: 1.269s
success source and transform nodes - 1.354s
success building schema - 0.299s
success createPages - 0.001s
success createPagesStatefully - 0.054s
success onPreExtractQueries - 0.001s
success update schema - 0.024s
success extract queries from components - 0.348s
success write out requires - 0.011s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.126s
success onPostBootstrap - 0.130s
⠀
info bootstrap finished - 26.278 s
⠀
success Building production JavaScript and CSS bundles - 10.725s
success Rewriting compilation hashes - 0.003s
success run queries - 10.894s - 5/5 0.46/s
success Building static HTML for pages - 1.867s - 4/4 2.14/s
success onPostBuild - 0.001s
info Done building in 39.058419406 sec
```

#### Netlify Build (from GitHub repo)

```
20:56:03.931  
 ERROR #11321  PLUGIN
20:56:03.932  
"gatsby-source-shopify" threw an error while running the sourceNodes lifecycle:
20:56:03.932  
Cannot read property 'includes' of undefined
20:56:03.932  
  40 |   includeCollections = [_constants.SHOP, _constants.CONTENT]
20:56:03.932  
  41 | }) => {
20:56:03.932  
> 42 |   const client = (0, _createClient.createClient)(shopName, accessToken, apiVersion); // Convenience function to namespace console messages.
20:56:03.932  
     |                                                 ^
20:56:03.932  
  43 |
20:56:03.932  
  44 |   const formatMsg = msg => (0, _chalk.default)`\n{blue gatsby-source-shopify/${shopName}} ${msg}`;
20:56:03.932  
  45 |
```
### Environment

 System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 3.7.6 - /Users/moritzsalla/anaconda3/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 72.0.2
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.25 => 2.20.25
    gatsby-image: ^2.3.4 => 2.3.4
    gatsby-plugin-manifest: ^2.3.5 => 2.3.5
    gatsby-plugin-offline: ^3.1.4 => 3.1.4
    gatsby-plugin-react-helmet: ^3.2.4 => 3.2.4
    gatsby-plugin-sharp: ^2.5.6 => 2.5.6
    gatsby-source-filesystem: ^2.2.4 => 2.2.4
    gatsby-source-shopify: ^3.1.4 => 3.1.4
    gatsby-transformer-sharp: ^2.4.6 => 2.4.6

**Comment by moritzsalla** [comment]
I have tried setting the API version to 2020-1 to no effect

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Are you sure that your build environment has access to the necessary plugin options like `shopname`, `accessToken` etc.?

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by moritzsalla** [comment]
@LekoArts I have added some information to my issue, hope this helps.

**Comment by vladar** [comment]
Sounds like you don't have environment variables in your deployment setup. Most likely `process.env.SHOPIFY_STORE_NAME` is undefined when you are deploying.

**Comment by moritzsalla** [comment]
Seems like I misconfigured `dotenv`. Adding this to my `gatsby-config.json` solved it: 
```js
if (process.env.NODE_ENV !== "production") {
  dotenv.config()
}
```
