### ISSUE TITLE
Automatic builds on Heroku 

### ISSUE THREAD

**Issue by imadyaici** [gatsbyjs/gatsby#23270]
## Summary

Hi,

We deployed our Gatsby site on Heroku, sourcing content from a Wordpress website deployed on GoDaddy. I installed the WP Hooks plugin on Wordpress.

What's the way to trigger automatic builds on Heroku? is there any web build hooks that we can use as in Netlify ?

**Comment by LekoArts** [comment]
Thank you for opening this!

It's probably best to ask Heroku's support directly as they will know best. In the meantime you could look at our documentation: https://www.gatsbyjs.org/docs/deploying-to-heroku/

Or look at these articles that touch on webhooks inside Heroku:
https://www.freecodecamp.org/news/how-to-deploy-a-static-gatsby-app-to-heroku-3362e3ecda0f/
https://www.contentful.com/developers/docs/tutorials/general/automate-site-builds-with-webhooks/
https://devcenter.heroku.com/articles/app-webhooks-tutorial

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
