### ISSUE TITLE
Using graphql variables for ImageSHarp

### ISSUE THREAD

**Issue by ajmeraaxesh** [gatsbyjs/gatsby#23271]
this is the default code. why not allow image src, height and widht as a configurable attribute?

const Image = () => {
  const data = useStaticQuery(graphql`
    query {
      placeholderImage: file(relativePath: { eq: "gatsby-astronaut.png" }) {
        childImageSharp {
          fluid(maxWidth: 300) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
  `)

  return <Img fluid={data.placeholderImage.childImageSharp.fluid} />
}

export default Image

**Comment by LekoArts** [comment]
Thank you for opening this!

Height and width doesn't exist for `fluid` as it doesn't make sense, it needs to be e.g. `maxWidth`. You can use these options with `fixed` or `resize` as explained here:
https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/?=sharp#methods

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by lannonbr** [comment]
On top of such, Gatsby Static Queries do not support passing variables into them. If you want to use variables now, you can use page queries which likely in this instance won't help much, as I'm betting you want a component like `<Img src="foo.jpg" />` and it will pass it to the graphql for you, but there is discussions on making a new query that does support variables here: #10482
