### ISSUE TITLE
codesandbox is unable to fetch changes to github

### ISSUE THREAD

**Issue by Niksgupta** [gatsbyjs/gatsby#23275]
![Screenshot from 2020-04-19 22-11-18](https://user-images.githubusercontent.com/33507803/79694396-9fba2e80-828d-11ea-812d-d9906c8519ae.png)
Codesandbox is unable to fetch the changes that i made and now I am not able to push my work to github, so let me know the alternative or the solution for the same issue. I am attaching the picture where it is occuring. It only shows fetching changes but not fetching.

**Comment by wardpeet** [comment]
Hi,

I'm unsure if we can help you here. Please contact Codesandbox's support or ask help at our [discord channel](https://gatsby.dev/discord).

I'll be closing this issue as there is nothing we can do from a Gatsby perspective.

Thank you for using Gatsby! 💜
