### ISSUE TITLE
Using JSX to assign node value in gatsby-plugin-mdx

### ISSUE THREAD

**Issue by hgezim** [gatsbyjs/gatsby#23283]
## Summary

I'm writing a transformer plugin for `gatsby-plugin-mdx`. How can I use JSX to swap out the node value I'm interested in?

## Relevant information

I tried this:
```
node.type = 'jsx'
node.value = <a>....</a>
```

However it generates an object an the final output in the browser ends up being `[object Object]`.

I tried looking for how other plugins are doing it without too much success. It seems people are using lodash or cheerio.

I also tried assigning a JSX string template likes so:

```
cons card = {...}
node.type = 'jsx'
node.value = `<a href={...} title={'${card.title}'}`
```
However if `card.title` ends up with a `'` (single quote), broken HTML is generated like so:

`<a ... title={'Inside small food companies' struggle to survive the coronavirus outbreak'}>`

### Environment (if relevant)

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.7.0/bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12 
    gatsby-background-image: ^1.0.1 => 1.0.1 
    gatsby-image: ^2.3.1 => 2.3.1 
    gatsby-plugin-emotion: ^4.2.1 => 4.2.1 
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3 
    gatsby-plugin-mdx: ^1.1.9 => 1.1.9 
    gatsby-plugin-netlify-cms: ^4.2.2 => 4.2.2 
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1 
    gatsby-plugin-sharp: ^2.5.4 => 2.5.4 
    gatsby-plugin-typescript: ^2.3.1 => 2.3.1 
    gatsby-remark-images: ^3.2.2 => 3.2.2 
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0 
    gatsby-source-filesystem: ^2.2.2 => 2.2.2 
    gatsby-transformer-remark: ^2.7.1 => 2.7.1 
    gatsby-transformer-sharp: ^2.4.4 => 2.4.4 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

I'm not too sure what you're trying to do, can you give a full example or a link to your current code? It sounds like you're trying to do this: https://www.gatsbyjs.org/docs/mdx/customizing-components/

**Comment by hgezim** [comment]
Thanks, @LekoArts.

My goal is to have a transformer plugin that takes URL in markdown and creates an unfurled (preview link) version with metadata.

Here's my code:

```
export default async (
    {
      markdownAST,
      markdownNode,
      cache,
      reporter,
    }: { markdownAST: any; markdownNode: any; cache: any; reporter: any },
    rawOptions: any
  ) => {
    try {
      const options = rawOptions
  
      const nodes = selectPossibleOembedLinkNodes(markdownAST)
  
      if (nodes.length > 0) {
        const results = await Promise.all(
          nodes.map((node: any) => processNode(node, options))
        )
        logResults(results, markdownNode, reporter)
      }
    } catch (error) {
      reporter.error(`gatsby-remark-oembed: Error processing links`, error)
    }
  }
  
  // For each node this is the process
  const processNode = async (
    node: any,
    options: any,
  ): Promise<Node> =>  {
      {
    try {
      console.log('node.url:', node.url)
      const metaData = await unfurl(node.url)
      console.dir(metaData)
      console.log('cache path:', options)
  
      const metadata = {
          title: ...,
          description:...node,
          url: ...,
          video: ...,
          image: ...,
          logo: ...,
          site: ...node
        }
        
      }
  
      return tranformsLinkNodeToOembedNode(node, metadata)
    } catch (error) {
      error.url = node.url
      return error
    }
}


export const tranformsLinkNodeToOembedNode = (node: Node, card: IOembed) => {
  node.type = 'jsx'
  node.value = `
  <a className='gatsby-remark-link-unfurl__container' href={'${card.url}'} target='_blank' title={'${card.title}'}>
    <div className='gatsby-remark-link-unfurl__media' style={{backgroundImage: 'url(${card.image?.url})'}}></div>
    <div className='gatsby-remark-link-unfurl__content'>
      <header className='gatsby-remark-link-unfurl__title'><p  title={'${card.title}'}>${card.title}</p></header>
      <div className='gatsby-remark-link-unfurl__description'><p title={'${card.description}'}>${card.description}</p></div>
      <footer><p title={'${card.site}'}>${card.site}</p><span title={'${card.site}'} style={{backgroundImage: 'url(${card.logo})', backgroundRepeat: 'no-repeat', backgroundPosition: 'center center'}}></span></footer>

    </div>
    </a>
  `

  console.log('innerhtml:', node.value)
  delete node.children

  return node
}
```

The issue I'm having is in `tranformsLinkNodeToOembedNode`. If `card.title` ends up with a single quote (`'`) in the string, the HTML generated is invalid:

```
<a ... title={'Inside small food companies' struggle to survive the coronavirus outbreak'}>
```

**Comment by Js-Brecht** [comment]
@hgezim I wonder if it would work if you escape any single quotes in the string?

```js
<a ... title={'${card.title.replace(/'/g, "\\'")}'}>
```

I guess depending on what processing is done to it, you may need this: `"\\\\'"`

**Comment by hgezim** [comment]
I ended up using `mustache` templates and it works: https://github.com/hgezim/gatsby-remark-link-unfurl
