### ISSUE TITLE
linear-gradient doesn't work with background-image plugin after implementing my sass styling

### ISSUE THREAD

**Issue by Abderrahmenla** [gatsbyjs/gatsby#23287]
## Description

linear-gradient doesn't work with background-image plugin after implementing my sass styling

### Steps to reproduce

https://github.com/Abderrahmenla/Scouting
clone/download it then npm install

### Expected result

the styling of the class header in the file sass/layout/header.scss should work with the linear-gradient

### Actual result

linear-gradient doesn't work

### Environment

  System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    npm: 6.14.3 - ~/.nvm/versions/node/v13.7.0/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.92
    Firefox: 75.0
  npmPackages:
    gatsby: ^2.20.23 => 2.20.23

    gatsby-background-image: ^0.10.2 => 0.10.2
    gatsby-image: ^2.3.3 => 2.3.3
    gatsby-plugin-manifest: ^2.3.4 => 2.3.4
    gatsby-plugin-playground: ^1.0.6 => 1.0.6
    gatsby-plugin-react-helmet: ^3.2.3 => 3.2.3
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sass: ^2.2.3 => 2.2.3
    gatsby-plugin-sharp: ^2.5.5 => 2.5.5
    gatsby-plugin-sitemap: ^2.3.3 => 2.3.3
    gatsby-plugin-styled-components: ^3.2.2 => 3.2.2
    gatsby-plugin-transition-link: ^1.18.0 => 1.18.0
    gatsby-source-contentful: ^2.2.8 => 2.2.8
    gatsby-source-filesystem: ^2.2.3 => 2.2.3
    gatsby-transformer-sharp: ^2.4.5 => 2.4.5
  npmGlobalPackages:
    gatsby-cli: 2.11.11

**Comment by LekoArts** [comment]
Thank you for opening this!

We're not maintaining the plugin `gatsby-background-image` so please open an issue on the plugin's repository. Thanks!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
