### ISSUE TITLE
gatsby-plugin-mdx: Remote markdown body fetched before Mdx processes node content

### ISSUE THREAD

**Issue by dhakan** [gatsbyjs/gatsby#23281]
I'm not sure if to label this as being related to `gatsby-plugin-mdx` or `gatsby-source-filesystem`, but here it goes.

I have markdown files whose body is located at a remote URL, specified in the frontmatter as `sourceUrl`. How would I go about sourcing this into a `File` node which contains both the frontmatter and the body, so that MDX can start processing as if the body was always there? 

Since `gatsby-plugin-mdx` is expecting `File` nodes, I assumed I could create these myself before MDX starts processing. This doesn't work because of the restrictions of creation of nodes, namely that you're expected to create your own nodes, or extend existing ones. This led me to overwrite the `node.internal.content` of created `File` nodes, to include a now-fetched body, concatenated with the frontmatter(this is the field MDX is operating upon). This works, but [according to these docs about changing node fields](https://www.gatsbyjs.org/docs/node-creation/#changing-a-nodes-fields) it seems to be outside of the realm of what I should be doing.

Another strategy I've thought about is creating files before they are being sourced by `gatsby-source-filesystem`, but it sounds like this goes against the gatsby philosophy.

Any ideas would be very helpful.

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll want to use [createRemoteFileNode](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createremotefilenode) to pull the file from `sourceUrl`. This is the first step in getting the file. To let `gatsby-transformer-remark` or `gatsby-plugin-mdx` transform the node and add a child node of `childMdx` you should also be sure to set the MIME type to `text/markdown`.
This is more explained here: https://www.gatsbyjs.org/docs/creating-a-source-plugin/#working-with-data-received-from-remote-sources

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by dhakan** [comment]
Thanks for the reply.

The strategy I'm seeing based on what you're suggesting:

1. Have `gatsby-source-filesystem` run.
2. Utilize `createRemoteFileNode` based on the `sourceUrl` frontmatter field from the `File` nodes that were created in step (1). Do this inside of `onCreateNode`.
3. Mark these nodes with a `mediaType` of `text/markdown`.
4. Have MDX pick them up as if these files were always there.

Is this interpretation correct?

Won't I have duplicate files in this scenario?
