### ISSUE TITLE
How to use a blank prefix link?

### ISSUE THREAD

**Issue by jhanstra** [gatsbyjs/gatsby#233]
Maybe not an issue, but I'm wondering if it's possible to have a blank prefix link? I'm using a custom domain to point to github pages, and I want mydomain.com/about to work instead of having to use mydomain.com/prefixLink/about. When I have `prefixLink=""`, this doesn't work because the index.html links to /styles.css and /bundle.js instead of styles.css and bundle.js.

Am I missing something?

**Comment by KyleAMathews** [comment]
Building with prefixes is totally optional. If you don't need it, don't add the `--prefix-links`  flag to `gatsby build` and then the `prefixLink` function does nothing.

See the docs for this: https://github.com/gatsbyjs/gatsby#deploying-to-github-pages-and-other-hosts-where-your-sites-links-need-prefixes

Also the function: https://github.com/gatsbyjs/gatsby/blob/master/lib/isomorphic/gatsby-helpers.js#L6

**Comment by SachaG** [comment]
Small note in case people have this issue: by default the `--prefix-links` flag [is included](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/package.json#L37) when you do `npm run deploy` to deploy to GitHub Pages.
