### ISSUE TITLE
Translate Visual Component

### ISSUE THREAD

**Issue by laurieontech** [gatsbyjs/gatsby#23302]
Per #23241 we need to refactor these components to support translation. 

The `<ComponentModel>` and `<ImageModel>` titles are currently hardcoded in an array inside of the component files. These need to be translatable.

Note that the markdown files are fine as is and the rotating examples in the ComponentModel are code rather than text and should also be fine.

**Comment by lelouchB** [comment]
Hi, if this issue is still open, can I work on this?
I will need some help since this will be my first contribution to Gatsby.
Thanks

**Comment by laurieontech** [comment]
Go for it @lelouchB!
