### ISSUE TITLE
Add support for composing plugins multiple times in GatsbyPlugin resource

### ISSUE THREAD

**Issue by johno** [gatsbyjs/gatsby#23300]
## Summary

Many plugins, like `gatsby-plugin-filesystem` are configured multiple times for different types and locations of data. We should be able to support that in recipes.

### Basic example

```jsx
<GatsyPlugin
  name="gatsby-source-filesystem"
  options={{
    name: 'foo',
    path: 'bar'
  }}
/>
<GatsyPlugin
  name="gatsby-source-filesystem"
  options={{
    name: 'foo2',
    path: 'bar2'
  }}
/>
```

Related to #23299

**Comment by KyleAMathews** [comment]
Terraform lets you name resources — which solves this problem but is also handy so you can reference resources elsewhere.

`name` is obviously used in lots of resources already so I've thought about a standard prop being liked `rName` or `resourceName`. `alias` could work perhaps too.
