### ISSUE TITLE
[gatsby-image] should hide base64 when full image loaded

### ISSUE THREAD

**Issue by MarcCoet** [gatsbyjs/gatsby#2330]
Awesome job with Gatsby-image. Really excited about it! :)

When using PNG with transparency, the blurry version is still visible behind the full sized image after load.
In the meantime I am simply transforming to JPG but I guess this is something we want to handle.

**Comment by KyleAMathews** [comment]
Oh right! Absolutely. Should be an easy PR if you want to tackle it — just fade out the base64 image / background when the new image is loaded.

**Comment by MarcCoet** [comment]
Quick fix indeed! #2338
Feel free to double check though

**Comment by alexkirsz** [comment]
This issue still occurs for me in Safari macOS/iOS, but only in production. I'm investigating.

**Comment by alexkirsz** [comment]
It looks like the style of the placeholder is partially updated. In production, it shows:

![image](https://user-images.githubusercontent.com/1621758/44435234-50e75d80-a5af-11e8-8801-206d1d7c064d.png)

In development, it shows:

![image](https://user-images.githubusercontent.com/1621758/44435252-63fa2d80-a5af-11e8-8535-2293736911f5.png)

This might be a problem with server-side rendering.

**Comment by alexkirsz** [comment]
I popped open the React Devtools for Safari, and they show that the base64 image's props are correctly set.

![Uploading image.png…]()

However, the actual style isn't properly updated in the DOM. At this point I'm tempted to say that this is either a bug in React or Safari.

**Comment by alexkirsz** [comment]
The root of the issue is that the image initializes its state differently when server rendering than when rendering in the browser, and React doesn't update the markup properly.

As such, one way to fix this problem is to move most of the state initialization logic from constructor to `componentDidMount`. I should have a PR ready today or in the next few days.
