### ISSUE TITLE
Gatsby not working after yarn install

### ISSUE THREAD

**Issue by matchatype** [gatsbyjs/gatsby#23312]
## Description

Having a pretty weird issue. My Gatsby app used to run just fine. Today I updated to v2.20.26 using yarn as usual. From that point on, running any command, like `gatsby develop` returned me this error:

```
 ERROR 

There was a problem loading the local develop command. Gatsby may not be installed. Perhaps you need to run "npm install"? Cannot find module 'date-fns/getDayOfYear'
```

I tried `gatsby clean` , `rm -rf node_modules`, even rolling back to a previously working app... nothing... Always triggering that error. Then I tried `npm install` and that's working.

So, after a couple of tests, I noticed that if I clean `node_modules` and use `npm install`, everything works. With `yarn install` it doesn't. Tried also removing `package-lock.json` and `yarn.lock`. Nothing seems to help yarn.

If I install via npm and then run any command with yarn, it will work just fine. So apparently there's an issue with yarn install. I'm running yarn v1.22.4 and always worked fine till today.

I tried comparing the contents of the `node_modules` directory using both package managers (with no lock files) and they actually differ.

**Comment by herecydev** [comment]
What are the differences you see?

**Comment by matchatype** [comment]
Pretty much every dependency folder is different, as you can see from the screenshot, but the most notable issue is that `gatsby-cli` is completely missing in yarn's node_modules directory (screenshot #4).
Forgive the amount of screenshots please... Yarn is on the left:

![CleanShot 2020-04-20 at 15 55 29@2x](https://user-images.githubusercontent.com/28128/79794406-2d465e80-8320-11ea-8fab-9bb6ecb8a0c7.png)

![CleanShot 2020-04-20 at 15 55 44@2x](https://user-images.githubusercontent.com/28128/79794412-320b1280-8320-11ea-94d6-aed531786244.png)

![CleanShot 2020-04-20 at 15 56 06@2x](https://user-images.githubusercontent.com/28128/79794419-359e9980-8320-11ea-95c6-ecbf4c9c2d1c.png)

![CleanShot 2020-04-20 at 15 56 18@2x](https://user-images.githubusercontent.com/28128/79794429-3b947a80-8320-11ea-8b86-de019650e2a1.png)

![CleanShot 2020-04-20 at 15 56 36@2x](https://user-images.githubusercontent.com/28128/79794442-40592e80-8320-11ea-9e33-a86dca669cb6.png)

![CleanShot 2020-04-20 at 15 56 55@2x](https://user-images.githubusercontent.com/28128/79794449-43ecb580-8320-11ea-81a8-3d9129a0ea19.png)

![CleanShot 2020-04-20 at 15 57 04@2x](https://user-images.githubusercontent.com/28128/79794459-4818d300-8320-11ea-90d4-0eba4acfed52.png)

**Comment by herecydev** [comment]
What version of yarn are you using?

**Comment by matchatype** [comment]
yarn v1.22.4
npm v6.13.4
node v12.16.1

**Comment by matchatype** [comment]
What worked in my case was cleaning my cache with `yarn cache clean`. I ran into other rather similar issues of people having similar problems, however with npm rather than yarn, and nobody tried this. Npm has similar feature `npm cache clean`.

**Comment by a-maccormack** [comment]
I checked documentation (https://classic.yarnpkg.com/en/docs/cli/global),
and this is what ended up working for me on Linux (pop-os 21.10):

Add the following line to `~/.bashrc` or `~/.zshrc` (depending on what you use) 
```
export PATH="$HOME/.yarn/bin:$PATH"
```
And you're done. 

If this doesn't work for you, you can search for your yarn bin directory with the following command:
```
yarn global bin
```

Then replace (yarn bin path) on  `~/.bashrc` or `~/.zshrc` with the path you got by using the command above

```
export PATH="$(yarn bin path):$PATH"
```

Hope this helps anyone struggling to solve this
