### ISSUE TITLE
GatsbyJS with Firebase - WebpackError: ReferenceError: IDBIndex is not defined

### ISSUE THREAD

**Issue by olafsulich** [gatsbyjs/gatsby#23327]
## Description

I'm received error with **gatsby develop**. It's very similar to this one: https://github.com/firebase/firebase-js-sdk/issues/2222, but I'm received error with gatsby develop, not with gatsby build. I did a lot of research but I can't find working solution. At first I had a problem with **gatsby build**, like in this post: https://github.com/firebase/firebase-js-sdk/issues/2222, but I resolved it with custom onCreateWebpackConfig(you can find it below).

I tried also that: https://github.com/gatsbyjs/gatsby/issues/17725, but with negative results.

Stack: - Gatsby - Firebase(error probably with that) - Redux

I'm also delete .cache and node_modules and install everything again, but it didn't work.
### Steps to reproduce

Can u help me figure it out?

**Project repo**: https://github.com/olafsulich/Projecty

**Post on Github issues:** https://github.com/firebase/firebase-js-sdk/issues/2946

**My gatsby-node:** 
```
exports.onCreateWebpackConfig = ({ stage, actions, getConfig }) => {
  if (stage === 'build-html') {
    actions.setWebpackConfig({
      externals: getConfig().externals.concat(function(context, request, callback) {
        const regex = /^@?firebase(\/(.+))?/;
        if (regex.test(request)) {
          return callback(null, `umd ${request}`);
        }
        callback();
      }),
    });
  }
};
```
**My firebase dependencies:**
```
 "@firebase/firestore-types": "^1.10.1",
 "firebase": "^7.13.1",
 "firebase-admin": "^8.10.0",
 "firebase-functions": "^3.5.0",
 "firebase-tools": "^7.16.1",
```
**Firebase index file:**
```
import firebase from 'firebase/app';
import 'firebase/firestore';
import 'firebase/auth';
import 'firebase/storage';
import 'firebase/analytics';
const firebaseConfig = {...};
firebase.initializeApp(firebaseConfig);
export const firestore = firebase.firestore();
export const auth = firebase.auth();
export const storage = firebase.storage();
```

### Expected result
Run development server without receiving an error. 
### Actual result
```
There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html ReferenceError: IDBIndex is not defined
]);
  86 | 
> 87 | proxyRequestMethods(Index, '_index', IDBIndex, [
     | ^
  88 |   'get',
  89 |   'getKey',
  90 |   'getAll',

  WebpackError: ReferenceError: IDBIndex is not defined

  - idb.mjs:87 Module../node_modules/idb/lib/idb.mjs
    node_modules/idb/lib/idb.mjs:87:1

  - index.esm.js:1 Module../node_modules/@firebase/installations/dist/index.esm.js
    node_modules/@firebase/installations/dist/index.esm.js:1:1

  - index.esm.js:1 Module../node_modules/@firebase/analytics/dist/index.esm.js
    node_modules/@firebase/analytics/dist/index.esm.js:1:1

  - index.esm.js:1 Module../node_modules/firebase/analytics/dist/index.esm.js
    node_modules/firebase/analytics/dist/index.esm.js:1:1

  - index.ts:1 Module../src/firebase/index.ts
    src/firebase/index.ts:1:1

  - index.esm.js:32 emit
    node_modules/@firebase/analytics/dist/index.esm.js:32:1
```

### Environment

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.10.0 => 2.20.9
    gatsby-image: ^2.2.1 => 2.3.1
    gatsby-plugin-canonical-urls: ^2.1.0 => 2.2.1
    gatsby-plugin-create-client-paths: ^2.2.1 => 2.2.1
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.1.0 => 3.2.1
    gatsby-plugin-react-redux: ^1.1.0-0 => 1.1.0-0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.2.1 => 2.5.3
    gatsby-plugin-typescript: ^2.1.0 => 2.3.1
    gatsby-remark-copy-linked-files: ^2.1.0 => 2.2.1
    gatsby-remark-images: ^3.1.0 => 3.2.1
    gatsby-remark-prismjs: ^3.3.0 => 3.4.1
    gatsby-remark-smartypants: ^2.1.0 => 2.2.1
    gatsby-source-filesystem: ^2.1.0 => 2.2.2
    gatsby-transformer-json: ^2.2.0 => 2.3.1
    gatsby-transformer-remark: ^2.5.0 => 2.7.1
    gatsby-transformer-sharp: ^2.2.0 => 2.4.3
  npmGlobalPackages:
    gatsby-cli: 2.10.4

**Comment by LekoArts** [comment]
Thank you for opening this!

As you also asked that on StackOverflow, you already got the correct answer there :)
https://stackoverflow.com/questions/61334290/gatsbyjs-with-firebase-webpackerror-referenceerror-idbindex-is-not-defined/61336305#61336305

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
