### ISSUE TITLE
Problem when importing components from a "central" index.js

### ISSUE THREAD

**Issue by akoenig** [gatsbyjs/gatsby#2332]
* Gatsby version: `1.1.7`
  * Node.js version: `v8.2.1`
  * OS version: `macOS 10.12.3`

Exporting components from a central `index.js` file and importing it in a layout doesn't work. Test case:

## Directory layout
```
src/
    layouts/
        components/
            Header.js
            index.js
        index.js
```

### Exposing components from the `components` subdir

```jsx
// src/layouts/components/Header.js
import React from "react";
import styled from "styled-components";

const Header = styled.header`
    margin-top: 1em;
`;

export { Header };
```

```jsx
// src/layouts/components/index.js

import { Header } from "./Header";

export { Header };
```

## Using `<Header/>` in `index.js` layout

```jsx
// src/layouts/index.js

import React from "react";

import { Header } from "./components";

export default () =>
  <div>
       <Header />
  </div>;
```

This leads to a `Invariant Violation:`:

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `_default`.
```

**Comment by akoenig** [comment]
I figured that the transpiled output in the cache looks like this:

```jsx
// .cache/layouts/index.js
import React from "react"
import Component from "/.../src/layouts/components/index.js"
import data from "/.../.cache/json/layout-index.json"

export default (props) => <Component {...props} {...data} />
```

The problem is that `Component` is `undefined`, because of the wrong import path. I guess that the correct import should look like.

`import Component from "/.../src/layouts/index.js"`

 Is that correct? :)

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
