### ISSUE TITLE
Gatsby Docs Recipes is confusing now that there is Gatsby Recipes

### ISSUE THREAD

**Issue by micahgodbolt** [gatsbyjs/gatsby#23321]
I was searching for this page:

https://www.gatsbyjs.org/blog/2020-04-15-announcing-gatsby-recipes/

But instead found this page

https://www.gatsbyjs.org/docs/recipes/

Is there another word you can use instead of Recipes for that docs page?

https://www.bing.com/search?q=gatsby+recipes&cvid=472355232b23496683bbdc40d136cdee&FORM=ANNTA9&PC=U531

**Comment by LekoArts** [comment]
Thank you for opening this!

It wasn't directly mentioned in [What are future plans for Gatsby Recipes?](https://www.gatsbyjs.org/blog/2020-04-15-announcing-gatsby-recipes/#what-are-future-plans-for-recipes) but the /docs/recipes page you mentioned will eventually be converted to recipes itself. So it wouldn't make sense to rename this now for the short period of time where it isn't ready yet. As Recipes are still more experimental than stable it wasn't just done yet. If you want, you can help my chiming in into the umbrella issue :)
https://github.com/gatsbyjs/gatsby/issues/22991

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by micahgodbolt** [comment]
Sounds good. Thanks for addressing
