### ISSUE TITLE
Gatsby Image in SVG not working

### ISSUE THREAD

**Issue by SajithRAP** [gatsbyjs/gatsby#23338]
I was importing images via GraphQL. Its working for jpg and png format but svg are not working. Errors are throwing out for svg file. Note: The directory and file names were correct

            Sample {
              title
              description
              avatar {
                childImageSharp {
                  fluid {
                    ...GatsbyImageSharpFluid
                  }
                }
              }
            }

Is there any other work around for it other than import "image" and hard coding as" img src={image}"

Thanks

**Comment by LekoArts** [comment]
Thank you for opening this!

As you correctly noticed you'll get a warning for svg files as you can't use gatsby image with SVG. You'll need to use `publicURL` instead and use a normal `<img src="" />` tag.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
