### ISSUE TITLE
"Unknown version 4 of Samsung" only on AWS

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#23331]
## Description

I'm getting this error on `gatsby develop` or `gatsby build`, in what is AFAICT an identically set up Ubuntu 18 environment, with the only difference being that the error occurs on AWS Lightsail, but not locally. I used `npm ci` to make sure I install the same package versions - here's [package-lock.json](https://gist.github.com/dandv/c19b9dc9fa5e9c9c7fb6039aaf3f2fea).

> ERROR #98123  WEBPACK
>
> Generating SSR bundle failed
>
> [BABEL] /home/dandv/website/.cache/develop-static-entry.js: Unknown version 4 of samsung (While processing: "/home/dandv/website/node_modules/@babel/preset-env/lib/index.js")
>
> File: .cache/develop-static-entry.js

Searching for the error shows it occurring [with Parcel too](https://github.com/parcel-bundler/parcel/issues/3201).

Hopefully someone has a clue as to what the culprit is (browserlist?) and how to fix it.

### Environment

```
~/website$ node_modules/.bin/gatsby info --clipboard

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.13.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    gatsby: ^2.19.39 => 2.20.25
    gatsby-plugin-manifest: ^2.2.31 => 2.3.5
    gatsby-plugin-offline: ^3.0.26 => 3.1.4
    gatsby-plugin-typescript: ^2.3.1 => 2.3.3
    gatsby-source-graphql: ^2.4.2 => 2.4.2
```

**Comment by dandv** [comment]
The error doesn't happen if I use `npx yarn` instead of `npm install`.

I've added to [the gist](https://gist.github.com/dandv/c19b9dc9fa5e9c9c7fb6039aaf3f2fea) `yarn.lock` and the original `package.json`.

**Comment by ascorbic** [comment]
I think this may be fixed if we update `@pmmmwh/react-refresh-webpack-plugin`. The version we have installed includes a dependency on react-dev-utils, which has an exact dependency on an ancient version of browserslist. The new version of @pmmmwh/react-refresh-webpack-plugin removes that.

**Comment by LekoArts** [comment]
Can you please [provide a minimal reproduction][reproduction]? I don't see any in here.

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment]
Hi!

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Comment by Halunks** [comment]
For me deleting the docker cashed files was the solution $ docker builder prune -a
