### ISSUE TITLE
After updating package gatsby stoped working

### ISSUE THREAD

**Issue by nikita-seliverstov** [gatsbyjs/gatsby#23343]
After updating packages the build stopped working. In development enviorment it outputs this error: 
![image](https://user-images.githubusercontent.com/37171096/79854276-e153f200-83d1-11ea-9570-2cf042a19272.png)
 
```
SEO file : 
import React from "react"
import PropTypes from "prop-types"
import Helmet from "react-helmet"

const SEO = ({ description, lang, meta, title }) => {
  const metaDescription = description
  return (
  <Helmet
      htmlAttributes={{
        lang,
      }}
      title={title}
      titleTemplate={`%s`}
      meta={[
        {
          name: `description`,
          content: metaDescription,
        },
        {
          property: `og:title`,
          content: title,
        },
        {
          property: `og:description`,
          content: metaDescription,
        },
        {
          property: `og:type`,
          content: `website`,
        },
      ].concat(meta)}
       > </Helmet>
  )
}


export default SEO
```

When I remove the Helmet component everything starts working

### Environment
  System:
    OS: Windows 10 10.0.17134
    CPU: (4) x64 Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.13
  Browsers:
    Edge: 42.17134.1098.0
  npmPackages:
    gatsby: ^2.20.27 => 2.20.27 
    gatsby-image: ^2.3.4 => 2.3.4 
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.3.5 => 2.3.5 
    gatsby-plugin-offline: ^3.1.4 => 3.1.4 
    gatsby-plugin-react-helmet: ^3.2.4 => 3.2.4 
    gatsby-plugin-sass: ^2.2.3 => 2.2.3 
    gatsby-plugin-sharp: ^2.5.6 => 2.5.6 
    gatsby-source-filesystem: ^2.2.4 => 2.2.4 
    gatsby-source-prismic-graphql: ^3.5.0 => 3.5.0 
    gatsby-transformer-sharp: ^2.4.6 => 2.4.6

**Comment by vladar** [comment]
Hi @nikita-seliverstov !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by jbryce** [comment]
@nikita-seliverstov try adding curly brackets for the Helmet import, replacing 

`import Helmet from "react-helmet"`

with 

`import { Helmet } from "react-helmet"`

**Comment by wardpeet** [comment]
Thank you for opening this, @nikita-seliverstov

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
