### ISSUE TITLE
How to create multiple pages for same node

### ISSUE THREAD

**Issue by rishabh09** [gatsbyjs/gatsby#23340]
I am using markdown to create posts,

my current routes are like `product/post-name`

I want `product/index` URL which will redirect to `product/post-name`

I am calling `createPage` 2 times in `exports.createPages` but it is redirecting to itself

**Comment by LekoArts** [comment]
Thank you for opening this!

That is something you'll need to handle on your server side / host. So e.g. if you use Netlify you can use [gatsby-plugin-netlify](https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/#redirects). Then you would run the `createRedirect` function in a loop through the `index` you have. This may vary depending on the host you're using.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
