### ISSUE TITLE
[gatsby-transformer-json] support for more types

### ISSUE THREAD

**Issue by ianrtracey** [gatsbyjs/gatsby#2334]
Hey there Gatsby team! Really digging gatsby so far. 

I need the ability to parse lots of different kinds of json files to use in a Gatsby project but saw that the current transformer only supports json arrays and string types. https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-json

Is anyone working on a more full-featured version? If not, I am willing and able to try implementing it.

**Comment by sebastienfi** [comment]
Hello @ianrtracey 
I don't think anyone is working on that yet. Would be glad to receive your PR !

**Comment by KyleAMathews** [comment]
This PR might be what you want. Reviewing it now and it should be going in soon https://github.com/gatsbyjs/gatsby/pull/2324

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
