### ISSUE TITLE
How to use username and password in graphql sourcing

### ISSUE THREAD

**Issue by kannanseeni** [gatsbyjs/gatsby#23341]
```js
  {
      resolve: "gatsby-source-graphql",
      options: {
        typeName: "GitHub",
        fieldName: "github",
        url: "https://api.github.com/graphql",
        // HTTP headers
        headers: {
          // Learn about environment variables: https://gatsby.dev/env-vars
          Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
        },
        // HTTP headers alternatively accepts a function (allows async)
        headers: async () => {
          return {
            Authorization: await getAuthorizationToken(),
          }
        },
        // Additional options to pass to node-fetch
        fetchOptions: {},
      },
    },
```

can any one help me how to add username and password

**Comment by vladar** [comment]
Could you clarify your question? Do you want to use HTTP Basic Auth or some custom Auth mechanism? Also What API are you trying to access? Snippet above references GitHub. Is it the case?

**Comment by kannanseeni** [comment]
I am using API platform graphql and jwt token. Without authorization, it is working fine.

I have added the token 
Authorization: `Bearer ${process.env.TOKEN}`,
it is not working.

I want to pass username, password to get  JWT token. After that, I want to use JWT token

**Comment by vladar** [comment]
A token is generated on the server-side by API Platform. So you should refer to API Platform documentation/community with this question. It is not directly related to Gatsby. Quick googling suggests this docs page: https://api-platform.com/docs/core/jwt/#adding-endpoint-to-swaggerui-to-retrieve-a-jwt-token

**Comment by shawngrona** [comment]
I have the same question - is it possible to use HTTP Basic Auth with this plug?

Here's the background:
1. Using wp graphql plugin on wordpress instance: https://www.wpgraphql.com/
2. Based on WpGraphQl instructions I added Basic Authentication plugin on Wordpress https://docs.wpgraphql.com/guides/authentication-and-authorization/#gatsby-focus-wrapper
3. Confirmed that I can call and get 'restricted' fields (eg user email address) via GraphiQL https://github.com/graphql/graphiql


In Gatsby, using gaysby-source-graphql I have the following config:
```
{
      resolve: `gatsby-source-graphql`,
      options: {
        typeName: `WPGraphQL`,
        fieldName: `wpgraphql`,
        url: `https://{domain}/graphql`,
        Headers: {
          Authorization: `Basic {base64 username:password}`
        }
      },
    },
``` 
On gatsby develop there are no errors from the above, however after graphql runs I dont see the 'restricted' fields - like user email address. Any suggestions?

**Comment by vladar** [comment]
You have `Headers` in uppercase but the option is lowercase. Have you tried changing it? I.e.

```js
{
      resolve: `gatsby-source-graphql`,
      options: {
        typeName: `WPGraphQL`,
        fieldName: `wpgraphql`,
        url: `https://{domain}/graphql`,
        headers: { // note the lowercase
          Authorization: `Basic {base64 username:password}`
        }
      },
    },
```

**Comment by shawngrona** [comment]
@kannanseeni i can confirm that basic auth works, i was using wordpress graphql plugin on along w/ a wordpress plugin for basic auth.  more details in that link above

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
