### ISSUE TITLE
Error message usability tests

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#23356]
## Problem

We already knew that error messages needed to be improved ([see this RFC up for improving error messages](https://github.com/gatsbyjs/rfcs/pull/37)) and [a recent survey further validated that knowledge](https://www.gatsbyjs.org/blog/2020-04-17-gatsby-survey-goes-command-line/)! We have been preparing usability testing for error messages. The number one way to improve Gatsby is for you to participate in error message testing!

Here are two ways you can help by testing error messages:

[Setup a usability test with us](https://github.com/gatsbyjs/rfcs/pull/37). If you do this, don’t “cheat” on the test and look up the errors in the repo ahead of time! It’s most useful for us to see you face the error message for the first time, without preparation.

OR

[Clone this repo](https://github.com/gatsbyjs/error-testing) and find two sites under error-testing/sites/. Screen record yourself running one site at a time to test how fast you can resolve the errors in them. Send the screen recording to shannon@gatsbyjs.com!

## Progress
Here are folks signed up for tests already (a checkmark means they completed the test)

- [x] @Canopix
- [ ] Luis
- [x] @ehrencrona 
- [x] @graysonhicks 
- [ ] [insert your name here]

**Comment by shannonbux** [comment]
Ideas for improving error messages so far:
- quick wins:
    - indicate that GraphiQL is still available even when error occurred. When is this the case? Are there errors that break GraphiQL?
    - Improve information hierarchy to emphasize suggestions after error message. Can use white space, bigger or bolder typeface, headers, color.
    - Give clearer feedback in the CLI when a user resolves an error. Could show error name and number again but green and with success messages? Or perhaps show that they saved a change so they know the success messages that come later are in response to their saved change (ideas: timestamps for errors and status lines, give some indication that we know they saved a change)
- potentially more difficult wins
    - is there a way to warn users in GraphiQL that their staticQuery can't be tested there? Or warn in the error itself?
    - more information in GraphiQL about the meaning of arguments and what they are for (is there already a way to do this?)

**Comment by graysonhicks** [comment]
@marcysutton Videos recorded, will be emailing with Google Drive links shortly.

**Comment by shannonbux** [comment]
@graysonhicks received and putting a time on my calendar to watch them! Will add notes and link to notes here once done!

**Comment by LekoArts** [comment]
We'll pause this for now :)
