### ISSUE TITLE
Jobs API v2 breaks caching plugins

### ISSUE THREAD

**Issue by chris-hammond** [gatsbyjs/gatsby#23365]
## Description

This was originally reported as [Issue #25 for gatsby-plugin-netlify-cache](https://github.com/axe312ger/gatsby-plugin-netlify-cache/issues/25), but the root cause is a breaking change in the gatsby jobs API.

With the introduction of API v2, gatsby-transformer-sharp how uses completed jobs stored in redux, rather than existing output filenames to determine whether or not to reprocess an image. Unfortunately, due to how plugins are called, by the time the caching plugin's `onPreInit()` function is called, the redux store has already been created and the cached version is not used.

To fix this, we either need an API that allows the caching plugin to import the cached redux files or we need a way to run a plugin function _before_ the redux store is created. The only other option is to return to using hashed output filenames to determine whether to process files, which would require code to be created in each plugin that uses the jobs API v2...

Please note: this is **breaking** builds on Netlify and the only solutions currently require reverting gatsby and/or gatsby-transformer-sharp.

### Steps to reproduce

To reproduce, add the gatsby-plugin-netlify-cache plugin to the default starter and build it on netlify. (See config below.) Rebuild the site, and you will see the images being processed a second time, even though they already existed in the /public/static folder. Roll back the version of gatsby-transformer-sharp to a version prior to the jobs API v2 change, and suddenly rebuilds will used the cached images correctly.

```
    {
      resolve: `gatsby-plugin-netlify-cache`,
      options: {
        cachePublic: true,
      },
    },
```

### Expected result

Subsequent rebuilds on netlify (or other build platform) shouldn't have to reprocess images as they haven't changed.

### Actual result

Every rebuild results in all images being reprocessed despite functinoal caching.

### Environment

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Binaries:
    Node: 12.10.0 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.3 - E:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.14 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.20.26 => 2.20.26
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.3.4 => 2.3.4
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1
    gatsby-plugin-excerpts: ^1.0.2 => 1.1.0
    gatsby-plugin-google-analytics: ^2.2.4 => 2.2.4
    gatsby-plugin-manifest: ^2.3.5 => 2.3.5
    gatsby-plugin-netlify: ^2.2.3 => 2.2.3
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-netlify-cms: ^4.2.4 => 4.2.4
    gatsby-plugin-offline: ^3.1.4 => 3.1.4
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^3.2.4 => 3.2.4
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sass: ^2.2.3 => 2.2.3
    gatsby-plugin-sharp: ^2.5.6 => 2.5.6
    gatsby-plugin-sitemap: ^2.3.5 => 2.3.5
    gatsby-plugin-tawk: ^1.0.0 => 1.0.0
    gatsby-remark-copy-linked-files: ^2.2.3 => 2.2.3
    gatsby-remark-custom-blocks: ^2.2.3 => 2.2.3
    gatsby-remark-images: ^3.2.4 => 3.2.4
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-source-filesystem: ^2.2.4 => 2.2.4
    gatsby-transformer-remark: ^2.7.3 => 2.7.3
    gatsby-transformer-sharp: ^2.4.6 => 2.4.6

```

**Comment by wardpeet** [comment]
I do get where you're coming from, but this is not a bug, nor a regression. The previous caching behavior for sharp wasn't correct. You could change the input file's content and your file would not recreate the image.

Jobs API checks the `content digest` of your input files to make sure we only re-create the images when necessary. Gatsby sadly clears the cache way too often when plugins get updated, gatsby-config changes. We could move the jobs cache out of the redux store, so caching would still be there for jobs, and we solely rely on this content digest.

There is some work planned to improve these caching mechanisms for jobs, but we haven't added estimation of delivery to it. Another thing is that we have an open PR for selective cache invalidation https://github.com/gatsbyjs/gatsby/pull/8379. That will help us only clear the cache when necessary. There are edge cases why we can't just merge that PR as of now. We're looking into maybe whitelisting some plugins like gatsby-source-filesystem, ... as we know they do not have cache side-effects like transformer-remark.

**Comment by shanekenney** [comment]
@wardpeet whether it was correct or not I’m not too concerned about. IMO the regression is you can no longer use `onPreInit` to  restore cached files before the cache is initialized.

This is important for platforms like Netlify and others that aren’t able to retain cached content in the directories Gatsby stores them in.

Is there an alternative approach that can be taken?

**Comment by wardpeet** [comment]
oh I read this issue wrong, that makes sense. I'll see if I can move it after the onPreInit phase.

**Comment by slorber** [comment]
Hey,

I'm impacted by this too, thanks for giving explanations on why it fails.

Also note Netlify just released a cache build plugin so it should be able to restore images before running the gatsby build command, so maybe the solution is to move out of the gatsby plugin and use the netlify plugin instead? 

https://www.netlify.com/blog/2020/04/23/enable-gatsby-incremental-builds-on-netlify/

**Comment by shcheklein** [comment]
We were affected by this as well with our custom build system. I understand more or less that we now need to cache both `.cache` _and_ `public` to make it work, right?

But for some reason it works fine when we run it locally, on the same machine (and push/pull directories to S3), but breaks on a build server (Heroku). It just does not respect the previously saved versions of the `.cache` and `public` and rebuilds all images again.

We had to go the previous set of packages for now and are still trying to figure out what's going here.

@wardpeet you mentioned that cache is being cleaned often (plugins, etc), but what else Job API or Gatsby state cache take into account besides calculating hashes of the plugins, Gatsby config, images? We would appreciate any ideas to check here. Thanks 🙏

**Comment by wardpeet** [comment]
Hi, we're not going to pursue this anymore. We have spent a lot of work in making the cache better especially on Gatsby Cloud.

Thank you for understanding.
