### ISSUE TITLE
☂️ Improve error messages based on usability tests

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#23361]
## Biggest sources of friction:

- Suggestions after error message are not emphasized enough - CLI is a "big messy wall of text" - Lennart
    - He also missed new errors and scrolled by them
    - He didn't see the doc suggestions for a while, and when he did, only chose the first doc
- It's not clear that you actually succeeded even when you resolve the error message. The bottom bar wasn't clear enough. The word "success" in that bar isn't clearly related to anything in the code or the side.
- It's not clear that staticQuery can't be tested in GraphiQL
- It's not clear what arguments mean in GraphiQL. e.g. what does `buildTime` mean anyway?
- It's not clear when [`localhost`](http://localhost) is available/working or not - bug

## Quick wins
- [ ] fix bug: GraphiQL is still available even when error occurred. When is this the case? Are there errors that break GraphiQL?
- [ ] Improve information hierarchy to emphasize suggestions after error message. Can use white space, bigger or bolder typeface, headers, color.
- [ ] Perhaps a page dedicated to each error

![Image from iOS (16)](https://user-images.githubusercontent.com/32467162/80040232-7debc200-84ae-11ea-8c98-8b23c468ddc7.jpg)

- [ ] Give clearer feedback in the CLI when a user resolves an error. 

Ideas: 
  - clear old information and only show current success messages and/or local host success message + status bar. 
  - Show error name and number again but green and with success message. 
  - Show that the user saved a change (perhaps show name of the file that changed) so they know the success messages that come later are in response to their saved change (ideas: timestamps for errors and status lines, give some indication that we know they saved a change). Here's an idea of how Next.js does that:
![Image from iOS (17)](https://user-images.githubusercontent.com/32467162/80040629-5c3f0a80-84af-11ea-9921-633b6ae3ee6b.jpg)
- [ ] For GraphQL errors, link to a "how to use GraphiQL to debug" article
- [ ] Code sandbox readme didn’t obviously show steps for how to run the project in CodeSandbox
- [ ] Surface actionable information in the status bar: show a list of action items that a user can select with arrow and enter keys: visit site, GraphiQL, each error # and details if you select it

## Potentially more difficult wins
- is there a way to warn users in GraphiQL that their staticQuery can't be tested there? Or warn in the error itself? @acao any ideas here?
- more information in GraphiQL about the meaning of arguments and what they are for (is there already a way to do this?)
- idea: MDX errors we could pull into the top of docs about each error (so the doc would show an exact copy of the error message with extra details below)
- Possibly Gatsby needs to give more feedback on strings that aren’t formatted right, like date format strings
- It’s worth exploring whether we can increase our confidence about the error. Can we validate yes/no they have a typo. Yes/no it’s a variable they’re trying to pass to staticQuery. If we can validate those things, we can throw more specific error messages

Thanks @jasonbahl for adding to these ideas!

**Comment by shannonbux** [comment]
Idea from @mxstbr React errors link to a page that shows the error number and adjusts the page to describe your specific error and more specific suggestions. What if we generate a recipe that proposes a fix for them and then a button to implement it?

Idea from @KyleAMathews:  What about opening their graphiQL with their erroring query already in it?

**Comment by LekoArts** [comment]
I published `2.20.32-cli-ux.0` & `2.20.32-cli-ux.1` to test out these two changes:
- https://github.com/LekoArts/gatsby/commit/6d90a1881c986426108998e31f425c34c3e2e052
- https://github.com/LekoArts/gatsby/commit/c9b40b8e3ca7d596351dab03e8e0f02df6067321

We'll test out these changes in the next call.

**Comment by LekoArts** [comment]
We'll pause this for now :)
