### ISSUE TITLE
Error while creating new gatsby site

### ISSUE THREAD

**Issue by nfornadim** [gatsbyjs/gatsby#23386]
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js

PATH: 
  C:\Users\NeoN\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\NeoN\bin;C:\Python38\Scripts;C:\Python38;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\MongoDB\Server\4.2\bin;C:\Program Files\Git\cmd;C:\Go\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs;C:\Users\NeoN\AppData\Local\Programs\Python\Python38-32\Scripts;C:\Users\NeoN\AppData\Local\Programs\Python\Python38-32;C:\Python\Python38\Scripts;C:\Python\Python38;C:\Users\NeoN\AppData\Local\Microsoft\WindowsApps;C:\Users\NeoN\AppData\Local\Programs\Microsoft VS Code\bin;C:\Hugo\bin;C:\Users\NeoN\go\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\bin;C:\Users\NeoN\AppData\Local\Yarn\bin;C:\Users\NeoN\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl

Yarn version: 
  1.22.4

Node version: 
  12.16.2

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/date-fns/-/date-fns-2.12.0.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:141375:19)
      at Object.onceWrapper (events.js:416:28)
      at ClientRequest.emit (events.js:310:20)
      at TLSSocket.emitRequestTimeout (_http_client.js:714:9)
      at Object.onceWrapper (events.js:416:28)
      at TLSSocket.emit (events.js:310:20)
      at TLSSocket.Socket._onTimeout (net.js:479:8)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

npm manifest: 
  {
    "name": "gatsby-starter-default",
    "private": true,
    "description": "A simple starter to get up and developing quickly with Gatsby",
    "version": "0.1.0",
    "author": "Kyle Mathews <mathews.kyle@gmail.com>",
    "dependencies": {
      "gatsby": "^2.20.25",
      "gatsby-image": "^2.3.4",
      "gatsby-plugin-manifest": "^2.3.5",
      "gatsby-plugin-offline": "^3.1.4",
      "gatsby-plugin-react-helmet": "^3.2.4",
      "gatsby-plugin-sharp": "^2.5.6",
      "gatsby-source-filesystem": "^2.2.4",
      "gatsby-transformer-sharp": "^2.4.6",
      "prop-types": "^15.7.2",
      "react": "^16.12.0",
      "react-dom": "^16.12.0",
      "react-helmet": "^6.0.0"
    },
    "devDependencies": {
      "prettier": "2.0.4"
    },
    "keywords": [
      "gatsby"
    ],
    "license": "MIT",
    "scripts": {
      "build": "gatsby build",
      "develop": "gatsby develop",
      "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
      "start": "npm run develop",
      "serve": "gatsby serve",
      "clean": "gatsby clean",
      "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
    },
    "repository": {
      "type": "git",
      "url": "https://github.com/gatsbyjs/gatsby-starter-default"
    },
    "bugs": {
      "url": "https://github.com/gatsbyjs/gatsby/issues"
    }
  }

**Comment by alewin** [comment]
@nfornadim When did the problem occur? 

During installation? If yes, have you tried with
 ```bash
yarn add gatsby-cli --network-timeout 600000
```

**Comment by nfornadim** [comment]
Thank you
