### ISSUE TITLE
Few starters in docs/starters.yml are not listed on starter page - www.gatsbyjs.org/starters

### ISSUE THREAD

**Issue by anubhavsrivastava** [gatsbyjs/gatsby#23383]
## Description
There are few entries which are present in docs/starters.yml does not show up in www.gatsbyjs.org/starters.

As on 22 April, 2019
Total starters in starters.yml is 413
Total starters shown on main site is 395 (all starters, no filters)

### Steps to reproduce

For sample, "gatsby-starter-prologue" starter does not show up in site while it is present in starters.yml

### Expected result

All available starters should be shown on main site.

### Actual result

Not all starters are shown on starters page

### Environment

Browser

### Additional info
There are set of already similar issues #19849 , #22733.
#19452 talks about intermittent failure of screenshot causing similar issue.
"gatsby-starter-prologue" starter mentioned in above issue is available and runs on github-pages, which *may be*  screenshot failed issue. A similar fix was tried on https://github.com/gatsbyjs/gatsby/pull/20427

**Comment by vladar** [comment]
Yeah, most likely related to failing screenshots. Website only shows starters with screenshots:

https://github.com/gatsbyjs/gatsby/blob/8241cc336dd5b0743c7f961bcdf95ded1938d3c1/www/src/pages/starters.js#L19

**Comment by anubhavsrivastava** [comment]
Still replicable
