### ISSUE TITLE
Subdirectory for images in /pages?

### ISSUE THREAD

**Issue by AdamWagner** [gatsbyjs/gatsby#2339]
First - thanks for the amazing work on Gatsby. It's streamlined creation of my portfolio site significantly. 

In my portfolio, each case study is a page with many images. Since I'd like to import images in the recommended way, I'm placing them all at the top level of /pages adjacent to the page.js file. This has become quite cluttered. I experimented with placing the images in a subdirectory for each case study, but this doesn't seem to work. 

I'm probably missing something. Would appreciate input from others with more experience with Gatsby. Thank you!

**Comment by bernhardw** [comment]
Hi Adam, please show your site structure, your import statement and your `<img>` element and I'm happy to take a look.

**Comment by benjaminhoffman** [comment]
@AdamWagner I simply import from an `src/assets/img/...` directory.  If you prefer better organization, try `src/assets/img/case-study/...`

Closing this issue now for lack of recent activity. Feel free to re-open if I am mistaken and you'd like to continue to troubleshoot.
