### ISSUE TITLE
(gatsby-source-filesystem): Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by Ir1d** [gatsbyjs/gatsby#23399]
## Description

I get this error when running `gatsby develop` or `gatsby build`.

However, 

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

Check https://github.com/ir1d/pkuscholar and run it on a small ulimit.

For my case, `ulimit -n` is 1024.

### Expected result

When running develop, the error shows, but it doesn't effect other pages.

### Actual result

But when running build, the error shows and no other pages were generated.

I would expect there's a solution for this and dont kill the other pages.

Currently I'm on a strange device and couldn't edit the ulimit.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

<details>
<summary>Details</summary>

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Languages:
    Python: 3.6.5 - /home/ir1d/anaconda3/bin/python
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: 75.0
  npmGlobalPackages:
    gatsby-cli: 2.8.27
</details>

**Comment by stevemarksd** [comment]
I'm also getting this: `Error: EMFILE: too many open files, open app-data.json`

**Comment by Ir1d** [comment]
not stale, this wasn't solved, I've switched the implementation from reading a ton of .md to reading a .json

**Comment by wamir79** [comment]
Hi all,

the best way i found to solve this issue is using graceful-fs.
add in the beginning of gatsby-config.js:
```
const fs = require('fs');
const gracefulFs = require('graceful-fs');
gracefulFs.gracefulify(fs);
```
