### ISSUE TITLE
Blank page using client-paths and pathPrefix 

### ISSUE THREAD

**Issue by elrumordelaluz** [gatsbyjs/gatsby#23392]
## Description

Maybe I am missing something, but found a simple _use case_ that finishes with an unexpected result. I created [this repo](https://github.com/elrumordelaluz/gatsby-client-with-prefix) with the minimal reproduction.

In this example, i am using _Client only routes_. I tried both, using `onCreatePage` hook as explained [here](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/#configuring-pages-with-matchpath) or by using the [gatsby-plugin-create-client-paths](https://www.gatsbyjs.org/packages/gatsby-plugin-create-client-paths/).

In the _development_ environment (`gatsby develop`) everything works as expected:

![dev](https://user-images.githubusercontent.com/784056/80038617-54ef1f80-84f6-11ea-9561-d21d8d8590f5.gif)

The unexpected results came when _building_ the website by running `gatsby build --prefix-paths` and serving through `gatsby serve --prefix-paths`

![prod](https://user-images.githubusercontent.com/784056/80038676-6e906700-84f6-11ea-852a-bf9a668f35c0.gif)

I didn't found related _issues_ on using _Client only routes_ and `prefixPath`, but a recurrent situations could be publishing the website into `gh-pages` as explaned [here](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/) where the `/reponame` sholud be prefixed.

[Here](https://elrumordelaluz.github.io/gatsby-client-with-prefix/) is the published website into `gh-pages` branch where is visible the current result.

### Steps to reproduce

1. Create a super basic `gatsby` website
1. Add `gatsby-plugin-create-client-paths` and `gatsby-source-filesystem`.
1. Add one static _Page_, like `/pages/index.js` and the other that will be only-client, in this case `/pages/app.js`.
1. Add some for testing purpose
1. Run in development to check that is working as expected
1. Run `gatsby build --prefix-paths`, then `gatsby serve --prefix-paths` 
1. Navigate to `/app`…

### Expected result

I expect to navigate the website the same way as in _development_

### Actual result

Blank page.

### Environment

```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: 2.20.29 => 2.20.29
    gatsby-plugin-create-client-paths: 2.2.3 => 2.2.3
    gatsby-source-filesystem: 2.2.4 => 2.2.4
```

**Comment by DysonLinDev** [comment]
+ 1

**Comment by kkarkos** [comment]
Not sure how your folder structure looks like but this worked for me:

gatsby-config.js for dynamic routes looks like that
```
{
      resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`/app/*`] },
    },
```

Now, my App component lives under `src/components/app/**index.js**`

In my netlify.toml (or _redirects file, whatever you are using) you need to make sure that you are pointing to the **index**:

```
[[redirects]]
  from = "/app/index/*"
  to = "/app.html"
  status = 200
  force = true
```

and not `from = "/app/*"` only.

Hope that helps.

**Comment by elrumordelaluz** [comment]
Thanks @kkarkos. That is what i tried. Since I wasn't working on _Netlify_ but in my own server, could you confirm me that in your _use-case_ you access to the `/app` dynamic routes through an url similar to `lorem-ipsum.netlify.app/website/app` where `/website` is the `pathPrefix`.

Apparently the issue it isn't related only to a redirect (which I used to set in some `nginx` servers when using dynamic routes), but the combination of dynamic routes with `pathPrefix`.

**Comment by ehrencrona** [comment]
@elrumordelaluz I tried running your reproduction repo. `AppPage` does get called even with the prefix when you run `gatsby serve`; the issue is that the client-side router you've built assumes the site is served on the root. 

If you just replace tell the router where you serve the site from using `<Router basepath={__PATH_PREFIX__}>` it will work fine in both cases. 

`__PATH_PREFIX__` is a global variable set by Gatsby. I'm not sure if there's maybe any cleaner way of accessing it.

**Comment by wardpeet** [comment]
We would love an update to our docs, stating this fix when path-prefix is used!

**Comment by ehrencrona** [comment]
@wardpeet So you think it's ok to access `__PATH_PREFIX__ ` in this way? The name kind of makes it smell "private" to me. Could we an accessor function somewhere instead? 

Or re-export a Router component that always binds `basepath` to it? There's not really any case when you wouldn't want it.

**Comment by ehrencrona** [comment]
I found the client-only routes chapter a bit confusing so I wound up rewriting quite a bit. Thankful for feedback!

**Comment by kylegoetz** [comment]
For what it's worth __PATH_PREFIX__ does not seem to work after building. Above someone claims it's a global variable set by Gatsby, but if I'm in my Gatsby site being served by Apache and I open the browser console and type __PATH_PREFIX__ the variable does not exist.
