### ISSUE TITLE
Allow frontend templates to access/print the GraphQL pageQuery string

### ISSUE THREAD

**Issue by sanscheese** [gatsbyjs/gatsby#23391]
## Summary

I am hoping to be able to access the GraphQL `pageQuery` in the frontend build.

### Basic example

```js
// /src/pages/index.js:
// ...
export default ({ data }) => {
  return (
    <Layout>
      <div>Hello Query: {{ pageQueryString }}</div>
    </Layout>
  )
}

export const query = graphql`query {
  allSitePage {
    edges {
      node {
        internalComponentName
      }
    }
  }
}`
// ...
```

This would then print `Hello Query: query { allSitePage { edges { node { internalComponentName } } } }` to the browser.

Am not sure of the best way/possibility to do this. If able to have a plugin hook into the `PageQueryStore` to add a 'PageQueryString` to the state?

**Comment by LekoArts** [comment]
Thank you for opening this!

This isn't currently possible. You might want to follow https://github.com/gatsbyjs/gatsby/pull/23423 as it might help you a bit.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
