### ISSUE TITLE
Test performance of starters

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#234]
Using webpagetest. This probably shouldn't be an automated test but something that we periodically check + use to test against major performance improvements e.g. #145 

Currently both the docs/blog score <= 1000 in their Speed Index. That seems like a nice milestone to stay under.

Results from tests I just ran:

* http://www.webpagetest.org/result/160404_B3_1390/ — documentation starter
* http://www.webpagetest.org/result/160404_PJ_138T/ — blog starter

**Comment by tehkaiyu** [comment]
It would be nice if we can show what modules are being bundled together and their pre/post build sizes.

**Comment by KyleAMathews** [comment]
Not very actionable, closing.
