### ISSUE TITLE
Keep frontmatter declaration in content

### ISSUE THREAD

**Issue by florent-andre** [gatsbyjs/gatsby#23403]
... so other remark plugins can parse and process them. 
It make the behaviour of gatsby-plugin-mdx more coherent with direct mdx call when you configure 'remarkplugins' that works on frontmatter elements.
A [PR was done](https://github.com/gatsbyjs/gatsby/pull/21663#event-3261657005) was done, but close because causing breakings changes. 
As suggested by @johno I create this issue to discuss possibles implementation of this to be non breaking and in the same time more coherent with the way it's handled in the remark ecosystem.
 

## Description

The objectif is to keep frontmatter related informations in the content, and thus available to other remarkplugins configured.

### Documentation

Documentation states that remarkplugins attribute works like mdx's one, but the frontmatter informations are removed, so it create question like : "why this not works on Gatsby, whereas it's okay on mdx(content, option) processor configuration ?"

## Related Issues

It"s a little bit Related to #16865.

## Side notes : 

1/ A mdx() processing is called during `gatsby-plugin-mdx/gatsby/preprocess-source.js` step, but this is a different code from "genMDX" that seems used everywhere else.
This may cause miss-understandings between results from Gatsby with no cache and Gatsby with caches. no ? 
The linked PR update both.

2/ Also, in the current plugin implementation, results of MDX processing are not stored, but re-processed on each call of Graphql. This may be more efficient to store the processing results serve them. What do you think ? It may be another issue however.

**Comment by pieh** [comment]
I've marked this as topic:MDX (for now), but I wonder how we handle this in `gatsby-transformer-remark` - would be great context to have if that plugin does it in way you wish mdx to do it, or if remark plugin would also need similar handling

**Comment by florent-andre** [comment]
Many thanks for the feedback. Will try with this plugin on the next iteration and keep you posted. 
Regards
