### ISSUE TITLE
Markdown content is not being rendered in the static build

### ISSUE THREAD

**Issue by animysore** [gatsbyjs/gatsby#23406]
## Description

My gatsby site works without issues when I run it with `gatsby develop`. However, the static version I deployed (made with `gatsby build`) does not render the markdown content correctly. There are no errors or warnings when running the build command, and no errors in the browser console.

Upon inspection of browser requests, it looks like the markdown content is present when the static page is fetched and is then being removed after the page renders fully.  Screenshots below.

### Steps to reproduce

[Repository Link](https://github.com/animysore/animysore.github.io). The `source` branch contains the project source code and the `master` branch is the rendered static site deployed to Github pages.

[Deployed Site link](https://animysore.com). The deployment was done as per the Gatsby guide on deploying to Github pages. 

### Expected result
![image](https://user-images.githubusercontent.com/6796491/80076661-214ddd00-856a-11ea-96c3-df4447a5e374.png)

### Actual result

![image](https://user-images.githubusercontent.com/6796491/80076693-2ad74500-856a-11ea-8553-d949dbdfd8e5.png)

This screenshot of the Chrome Inspector window shows the rendered markdown is indeed present on initial page load but is being removed after full render.

![image](https://user-images.githubusercontent.com/6796491/80076435-d338d980-8569-11ea-957d-b1689f74b8df.png)

### Environment

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 75.0
  npmPackages:
    gatsby: ^2.3.16 => 2.20.29 
    gatsby-image: ^2.0.37 => 2.3.4 
    gatsby-plugin-feed: ^2.1.0 => 2.4.3 
    gatsby-plugin-google-analytics: ^2.0.18 => 2.2.4 
    gatsby-plugin-manifest: ^2.0.28 => 2.3.6 
    gatsby-plugin-offline: ^2.0.25 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.2.4 
    gatsby-plugin-sass: ^2.1.17 => 2.2.3 
    gatsby-plugin-sharp: ^2.0.32 => 2.5.6 
    gatsby-plugin-typography: ^2.2.12 => 2.4.3 
    gatsby-remark-copy-linked-files: ^2.0.11 => 2.2.3 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-remark-prismjs: ^3.2.8 => 3.4.4 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.3.3 
    gatsby-remark-smartypants: ^2.0.9 => 2.2.3 
    gatsby-source-filesystem: ^2.0.29 => 2.2.4 
    gatsby-transformer-remark: ^2.3.8 => 2.7.4 
    gatsby-transformer-sharp: ^2.1.17 => 2.4.6 
  npmGlobalPackages:
    gatsby-cli: 2.5.6
```

**Comment by kevintab95** [comment]
Hi @animysore, does this still happen? Looks like the deployed site works fine now.

**Comment by animysore** [comment]
Resolved. 
The issue was with dangerouslySetInnerHTML - https://github.com/gatsbyjs/gatsby/issues/11108.
