### ISSUE TITLE
Bug : transformer-sharp with .tif images

### ISSUE THREAD

**Issue by Mozart409** [gatsbyjs/gatsby#23410]
## Description
After talking to @AskGatsby -MS which recommended that I should report a bug.
I wanted to use a .tif image with gatsby image and the "gatsby develop" command kept failing. I uploaded a gist.

### Steps to reproduce
I've made the project public, so you can hopefully reproduce the errors I got. 
https://github.com/Mozart409/PatrickLandingPage

Here is the gist with the original bugs.
https://gist.github.com/Mozart409/66f2963039f316660feda0d8620a0b97

### Expected result

What should happen?
Transformer sharp should convert a .tif image and make it available via graphql

### Actual result

What happened.
The gatsby develop command failed

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.22 => 2.20.29 
    gatsby-cli: ^2.11.8 => 2.11.15 
    gatsby-image: ^2.3.2 => 2.3.4 
    gatsby-plugin-manifest: 2.3.3 => 2.3.3 
    gatsby-plugin-offline: 3.1.2 => 3.1.2 
    gatsby-plugin-postcss: 2.2.1 => 2.2.1 
    gatsby-plugin-purgecss: 5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: 3.2.2 => 3.2.2 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sharp: ^2.5.3 => 2.5.6 
    gatsby-plugin-sitemap: ^2.3.2 => 2.3.5 
    gatsby-source-filesystem: ^2.2.2 => 2.2.4 
    gatsby-source-instagram: ^0.7.0 => 0.7.0 
    gatsby-transformer-sharp: ^2.4.3 => 2.4.6 
  npmGlobalPackages:
    gatsby-cli: 2.11.13

**Comment by pieh** [comment]
Hey, the repository you linked fails with
```
The path passed to gatsby-source-filesystem does not exist on your file system:
/Users/misiek/test/i23410/src/images/Booklet
Please pick a path to an existing directory.
See docs here - https://www.gatsbyjs.org/packages/gatsby-source-filesystem/
```

for me. Removing this path from `gatsby-config` let me go forward from that error, but then it fails in building .html step (but not the image related one).

But looking at the gist with error message and error stack - the `potrace` errors are usually related to "Traced SVG" feature ( https://using-gatsby-image.gatsbyjs.org/traced-svg/ ) - did you use that? (I can't find references to it right now in repo)

**Comment by Mozart409** [comment]
Hey,
don’t worry. It was an out of date dependency. I yarn-dedublicated reinstalled all my modules and now it works. 👍🏻

**Comment by wardpeet** [comment]
Repro is gone :'( How big is the tif? Maybe that's part of the issue?
