### ISSUE TITLE
Unable to install Optional chaining support plugin

### ISSUE THREAD

**Issue by dimaninc** [gatsbyjs/gatsby#23417]
## Description

I am trying to add Optional chaining support to my project, [here's its page](https://www.gatsbyjs.org/packages/gatsby-plugin-optional-chaining/)

### Steps to reproduce

I am adding the plugin using yarn as it said in manual:
```
yarn add gatsby-plugin-optional-chaining && yarn add -D @babel/core @babel/plugin-proposal-optional-chaining
```

### Expected result

Plugin should have been added to my project.

### Actual result

But it's not found, and [plugin's github](https://github.com/jameygleason/gatsby-plugin-optional-chaining) not exists any more, 404 error returned

```
yarn add gatsby-plugin-optional-chaining && yarn add -D @babel/core @babel/plugin-proposal-optional-chaining
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
error Received malformed response from registry for "gatsby-plugin-optional-chaining". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.16.1 => 2.16.1 
    gatsby-image: ^2.2.29 => 2.2.29 
    gatsby-plugin-lodash: ^3.1.13 => 3.1.13 
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23 
    gatsby-plugin-offline: ^3.0.16 => 3.0.16 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.1.29 => 2.1.29 
    gatsby-plugin-sharp: ^2.2.31 => 2.2.31 
    gatsby-source-filesystem: ^2.1.33 => 2.1.33 
    gatsby-source-graphql: ^2.2.0 => 2.2.0 
    gatsby-transformer-sharp: ^2.2.23 => 2.2.23

**Comment by LekoArts** [comment]
Thank you for opening this!

As this is a community plugin we normally advise to ask on their respective repository. However, in this specific case I can tell you that the plugin is not necessary. You can use optional chaining in Gatsby out of the box today :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
