### ISSUE TITLE
Puppeteer: upgrade from v1 to v3

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#23421]
## Summary

> @muescha Puppeteer v1 is very out-dated - we just released v3. I'll see if we can get Gatsby (or the plugin) to upgrade their version.

_Originally posted by @jackfranklin in https://github.com/puppeteer/puppeteer/issues/5685#issuecomment-617246723_

### Motivation

new version is available

### Usages:

- `gatsby-plugin-preload-fonts`: 
  - `"puppeteer": "^1.20.0"`
- `gatsby-transformer-screenshot/lambda`: 
  - `"puppeteer-core": "^2.1.1"`

**Comment by ElijahCano33** [comment]
I would like to try to tackle this issue if that's fine. It doesn't seem as though puppeteer and puppeteer-core are used in many places around the project.  V3 relies on Node 10.18.1, but fortunately Gatsby is currently supporting all node versions from Node 10.13.0 and up so there shouldn't be a conflict. I believe all there is to do is to verify that there aren't any breaking changes from v1 to v3 that would break what is already in the Gatsby project and then just test everything after upgrading.

**Comment by ElijahCano33** [comment]
I made a PR with the changes [here](https://github.com/gatsbyjs/gatsby/pull/23949)
