### ISSUE TITLE
How to get 100 score in Lighthouse?

### ISSUE THREAD

**Issue by w3bdesign** [gatsbyjs/gatsby#23434]
## Summary

How to get 100 score in Lighthouse on my site?

## Relevant information

I am trying to achieve a 100 score on Google Lighthouse on my site. 
I have uploaded a HTML report online on https://romantic-euler-fe7783.netlify.app/ and would like some best practicce tips/advice on how to improve my score even further.

I am currently using React Helmet with the Gatsby plugin as well as hosting the site on Netlify.

Any tips/ideas are highly welcome.

### Environment (if relevant)

  System:
    OS: Windows 7 6.1.7601
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn x\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.4
  npmPackages:
    gatsby: ^2.20.29 => 2.20.29
    gatsby-plugin-netlify-headers: ^1.0.1 => 1.0.1
    gatsby-plugin-postcss: ^2.2.3 => 2.2.3
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^3.2.4 => 3.2.4
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.5.6 => 2.5.6

### File contents (if changed)

I have the following information in my SEO/Helmet component:

```
import React from "react"
import PropTypes from "prop-types"
import { Helmet } from "react-helmet"
import { useLocation } from "@reach/router"
import { useStaticQuery, graphql } from "gatsby"

const SEO = ({ title, description, image, article }) => {
  const { pathname } = useLocation()
  const { site } = useStaticQuery(query)

  const {
    defaultTitle,
    titleTemplate,
    defaultDescription,
    siteUrl,
    defaultImage,
    twitterUsername,
    lang,
  } = site.siteMetadata

  const seo = {
    lang: lang || "nb",
    title: title || defaultTitle,
    description: description || defaultDescription,
    image: `${siteUrl}${image || defaultImage}`,
    url: `${siteUrl}${pathname}`,
  }

  return (
    <Helmet title={seo.title} titleTemplate={titleTemplate}>      
      <meta name="description" content={seo.description} />
      <meta name="image" content={seo.image} />

      {seo.url && <meta property="og:url" content={seo.url} />}

      {(article ? true : null) && <meta property="og:type" content="article" />}

      {seo.title && <meta property="og:title" content={seo.title} />}

      {seo.description && (
        <meta property="og:description" content={seo.description} />
      )}

      {seo.image && <meta property="og:image" content={seo.image} />}

      <meta name="twitter:card" content="summary_large_image" />

      {twitterUsername && (
        <meta name="twitter:creator" content={twitterUsername} />
      )}

      {seo.title && <meta name="twitter:title" content={seo.title} />}

      {seo.description && (
        <meta name="twitter:description" content={seo.description} />
      )}

      {seo.image && <meta name="twitter:image" content={seo.image} />}
    </Helmet>
  )
}

export default SEO

SEO.propTypes = {
  title: PropTypes.string,
  description: PropTypes.string,
  image: PropTypes.string,
  article: PropTypes.bool,
}

SEO.defaultProps = {
  title: null,
  description: null,
  image: null,
  article: false,
}

const query = graphql`
  query SEO {
    site {
      siteMetadata {
        defaultTitle: title
        titleTemplate
        defaultDescription: description
        siteUrl: url
        defaultImage: image
        twitterUsername
      }
    }
  }
`
```

**Comment by herecydev** [comment]
Lighthouse is already flagging a few issues to look at. Surely best to tackle those first?

**Comment by w3bdesign** [comment]
> 
> 
> Lighthouse is already flagging a few issues to look at. Surely best to tackle those first?

I tried to set the language attribute, but no matter what I did, I wasn't able to get it to work.

Maybe somebody has better luck with it?

**Comment by w3bdesign** [comment]
Made some tweaks and updated the report here: https://romantic-euler-fe7783.netlify.app/

**Comment by herecydev** [comment]
> 
> 
> > Lighthouse is already flagging a few issues to look at. Surely best to tackle those first?
> 
> I tried to set the language attribute, but no matter what I did, I wasn't able to get it to work.
> 
> Maybe somebody has better luck with it?

Try adding `<html lang="en" />` into your react helmet code. (change the lang key to the correct language)

**Comment by LekoArts** [comment]
Thank you for opening this!

As this isn't really related to Gatsby but your site I'll close this. But I also recommend following the suggestions to get your 100. You can also head over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) to ask people about those things. We hope we managed to help and thank you for using Gatsby!
