### ISSUE TITLE
Show total build time

### ISSUE THREAD

**Issue by hitchcott** [gatsbyjs/gatsby#23445]
## Summary

Back in #191, build times were added to show each stage of the build. This is great, but it would also be nice to see the *total* build time in addition to individual stages, so we don't have to manually check each step to see how heavy the build is at a glance.

I want to gather feedback to see if this is likely to be accepted, happy to submit a PR if it is.

**Comment by LekoArts** [comment]
Thank you for opening this!

We already do that! :)

![image](https://user-images.githubusercontent.com/16143594/80195769-a42f7000-861c-11ea-843d-06dadb624353.png)

At the end of `gatsby build` you'll get the total time.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by hitchcott** [comment]
I see, I was referring to develop mode.
