### ISSUE TITLE
Can gatsby-plugin-page-creator whitelist pages to include?

### ISSUE THREAD

**Issue by diminishedprime** [gatsbyjs/gatsby#23441]
## Summary

I'm curious if there is a way to whitelist the pages that `gatsby-plugin-page-creator` creates. I see that there's a way to blacklist files via [ignore specific files](https://www.gatsbyjs.org/packages/gatsby-plugin-page-creator/#ignoring-specific-files), but I'm specifically interested in whitelisting the files to include. This might already be possible with ignore options you can pass to multimatch, but I haven't been able to get it to work. 

My ideal config would be something like the following:

```
...
    {
      resolve: `gatsby-plugin-page-creator`,
      options: {
        path: `${__dirname}/src/pages`,
        include: [`404.tsx`, `**/index.tsx`, `index.tsx`]
      }
    }
...
```

## Relevant information

My use case is that I want to include page-specific components in the `src/pages/` directory to keep related code together. Ideally I could have.a structure like the following:

```
├── 404.tsx
├── index.tsx
├── page1
│   ├── index.tsx
│   └── PageSpecificComponent.tsx
```

Any new pages would be put in a new directory (or subdirectory) with an index.tsx file. 

I understand that I can (remember) to name `PageSpecificComponent.tsx` `_PageSpecificComponent.tsx` since all files starting with `_` are excluded, but that seems error-prone since If I ever forget, the build breaks (after a long wait for it to run, I might add).

**Comment by diminishedprime** [comment]
not stale

**Comment by LekoArts** [comment]
Thank you for opening this!

Our convention is that only page files are allowed inside `src/pages` and we don't want to change this. Thus I'd recommend using the blacklist and a special naming scheme if you want that behavior. From our end we don't want to add this option as we require this convention for a bunch of (future) behaviors.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by diminishedprime** [comment]
Thanks for the response!

I'll continue with my current approach then. For anyone that's interested, it's just naming any page-specific components with a starting `_`, since those files are already ignored. It looks a bit odd, but it's a way to get this functionality without needing an explicit blacklist.
