### ISSUE TITLE
No pageContext in built pages, warn: Action createPage was called outside of its expected...

### ISSUE THREAD

**Issue by joshsmith01** [gatsbyjs/gatsby#23454]
## Description

Describe the issue that you're seeing.
1. `pageContext` is `undefined` even though the pages are built _and_
2. I receive a warning about **createPage** was called outside of its expected asynchronous lifecycle **createPages** in default-site-plugin.

### Steps to reproduce
npm run develop

### Expected result
- `createPage` should wait for all WPGraphQL data to return before building the page. 
- `pageContext` should exist on pages

### Actual result
1. I get the warning in the console
2. Pages with smaller amounts of data are built sooner
3. Pages with more data take a little longer (minutes) but eventually get built
4. No pageContext exists on any pages
5. Later pages sort of trickle in as they are built

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 74.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.18 => 2.20.18 
    gatsby-awesome-pagination: ^0.3.5 => 0.3.5 
    gatsby-background-image: ^0.9.7 => 0.9.19 
    gatsby-image: ^2.3.2 => 2.3.2 
    gatsby-plugin-catch-links: ^2.1.25 => 2.2.1 
    gatsby-plugin-disqus: ^1.1.4 => 1.1.4 
    gatsby-plugin-exclude: ^1.0.2 => 1.0.2 
    gatsby-plugin-force-trailing-slashes: ^1.0.4 => 1.0.4 
    gatsby-plugin-google-analytics: ^2.2.2 => 2.2.2 
    gatsby-plugin-google-tagmanager: ^2.1.20 => 2.2.1 
    gatsby-plugin-lodash: ^3.1.7 => 3.2.1 
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3 
    gatsby-plugin-netlify: ^2.1.12 => 2.2.1 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-offline: ^3.1.2 => 3.1.2 
    gatsby-plugin-polished: ^1.0.4 => 1.0.4 
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.2.2 => 3.2.2 
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2 
    gatsby-plugin-sass: ^2.1.14 => 2.2.1 
    gatsby-plugin-sharp: ^2.5.4 => 2.5.4 
    gatsby-plugin-smoothscroll: ^1.0.4 => 1.1.0 
    gatsby-plugin-styled-components: ^3.1.14 => 3.2.1 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-remark-images: ^3.2.2 => 3.2.2 
    gatsby-source-filesystem: ^2.1.22 => 2.2.2 
    gatsby-source-graphql: ^2.3.2 => 2.3.2 
    gatsby-source-wordpress: ^3.2.3 => 3.2.3 
    gatsby-transformer-remark: ^2.6.22 => 2.7.1 
    gatsby-transformer-sharp: ^2.4.4 => 2.4.4 
  npmGlobalPackages:
    gatsby-cli: 2.10.0

```
const path = require(`path`)
module.exports = async ({ actions, graphql }) => {
  const GET_CONTRIBUTOR_POSTS = `
    query GET_CONTRIBUTOR_POSTS($first: Int, $after: String, $contributorId: ID) {
      wpgraphql {
        posts(where: {allContributionsByContributor: $contributorId}, first: $first, after: $after) {
          nodes {
            id
            postId
            title
          }
          pageInfo {
            endCursor
            hasNextPage
          }
        }
      }
    }
  `
  const GET_CONTRIBUTOR = `
  query GET_CONTRIBUTOR($first:Int $after:String){
    wpgraphql {
      contributors(
        where: {
          taxQuery: 
            {
              relation: OR, 
                taxArray: [
                  {
                    terms: ["author"], 
                    taxonomy: CONTRIBUTORROLE, 
                    operator: IN, 
                    field: SLUG
                  }, 
                  {
                    terms: ["illustrator"],
                    taxonomy: CONTRIBUTORROLE,
                    operator: IN,
                    field: SLUG
                  }, 
                  {
                    terms: ["speaker"],
                    taxonomy: CONTRIBUTORROLE, 
                    operator: IN, 
                    field: SLUG
                  }, 
                  {
                    terms: ["presenter"], 
                    taxonomy: CONTRIBUTORROLE, 
                    operator: IN, 
                    field: SLUG
                  }
                  ]
                }
              }, first: $first, after: $after) {
          pageInfo {
            endCursor
            hasNextPage
          }
        nodes {
          id
          slug
          title
          contributorId
        }
      }
    }
  }
  `
  const { createPage } = actions
  const allContributors = []
  const allContributorPosts = []
  const blogPages = []

  const fetchContributorPosts = async (variables, slug) =>
    await graphql(GET_CONTRIBUTOR_POSTS, variables).then(({ data }) => {
      const {
        wpgraphql: {
          posts: {
            nodes,
            pageInfo: { hasNextPage, endCursor },
          },
        },
      } = data

      nodes.map(post => {
        allContributorPosts[slug].push(post.postId)
      })

      if (hasNextPage) {
        return fetchContributorPosts(
          {
            first: 12,
            after: endCursor,
            contributorId: variables.contributorId,
            id: variables.id,
          },
          slug
        )
      }

      // If there are no more posts to fetch, start building pages
      if (!hasNextPage) {
        const categoryTemplate = path.resolve(
          `./src/templates/post-contributor.js`
        )
        let pageNumber = 1
        const totalPosts = allContributorPosts[slug].length

        // Run this at least once, since some contributors may not have contributions :shrug
        do {
          const blogPagePath =
            pageNumber <= 1
              ? `/contributor/${slug}/`
              : `/contributor/${slug}/page/${pageNumber}/`

          // Take all the post IDs (WordPress post ID) and chunk them into groups of 12 to feed to create page. Consume
          // the whole array until there is nothing left.
          const firstIds = allContributorPosts[slug].splice(0, 12)
          createPage({
            path: blogPagePath,
            component: categoryTemplate,
            context: {
              id: variables.id,
              ids: firstIds,
              pageNumber: pageNumber,
              hasNextPage: hasNextPage,
              totalPosts: totalPosts,
              totalPages: Math.ceil(totalPosts / 12),
              slug: slug,
            },
          })
          pageNumber++
        } while (allContributorPosts[slug].length > 0)
      }

      return blogPages
    })

  const fetchContributors = async variables =>
    await graphql(GET_CONTRIBUTOR, variables).then(({ data }) => {
      const {
        wpgraphql: {
          contributors: {
            nodes,
            pageInfo: { hasNextPage, endCursor },
          },
        },
      } = data

      nodes.map(post => {
        allContributors.push(post)
      })

      if (hasNextPage) {
        fetchContributors({ first: 12, after: endCursor })
      }

      return allContributors
    })

  // Get every writer, illustrator, speaker, etc
  await fetchContributors({ first: 12, after: null }).then(() => {
    allContributors.forEach(contributor => {
      console.log('contributor: ', contributor)

      // Create an array assigned to this specific contributor inside of all the contributors array
      if (!allContributorPosts[contributor.slug]) {
        allContributorPosts[contributor.slug] = []
      }
      // Get all posts created by this contributor, could be 200 or 12 it doesn't really matter
      fetchContributorPosts(
        {
          first: 200,
          after: null,
          contributorId: contributor.contributorId,
          id: contributor.id,
        },
        contributor.slug
      )
    })
  })
}

```

**Comment by copperwall** [comment]
Just curious, is the snippet your `gatsby-node.js` file? If you change `module.exports` to `exports.createPages` does that fix the problem for you?

**Comment by CollierCZ** [comment]
You also don't have `await` in a couple of your `wpgraphql` queries, so it might not wait for the query to return data. See the link from the warning: https://www.gatsbyjs.org/docs/debugging-async-lifecycles/

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
