### ISSUE TITLE
Query non-existing node and try/catch issue

### ISSUE THREAD

**Issue by lnikell** [gatsbyjs/gatsby#23457]
I'm very like gatsby however today I got frustrated that there is no proper(documented) solution for how to deal with non-existing nodes queries which should be pretty typical stuff that people should face every day.

Problem: I have gatsby-node.js file and want to query WP with something like this
```
await graphql(
      `
        {
          allWordpressWpCareers {
            nodes {
              id
              path
            }
          }
        }
      `
    );
```
If I don't have any careers created in WP I receive the error. It's ok, but why I can't to wrap it in try/catch block? So if I do so it still somehow throws an error, so I even can't handle it in the simplest possible manner. 

So the solution such as "You can add a dummy record", sounds terrible for me.

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll want to explicitly define the GraphQL type for `WordpressWpCareers` to make it return `null`. You can read up on the documentation here: https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

To get the correct type add some dummy content, open GraphiQL and click on the top right "Docs" part. There you can inspect the available types. It's most likely the mentioned `WordpressWpCareers`.

So it could look like:

```js
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions;
  const typeDefs = `
    type WordpressWPCareers {
      path: String
    }
  `;
  createTypes(typeDefs);
};
```

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
