### ISSUE TITLE
Create a bare-bones gatsby-config.js in recipe

### ISSUE THREAD

**Issue by jbolda** [gatsbyjs/gatsby#23464]
Create a bare-bones gatsby-config.js file when creating GatsbyPlugin resources if one doesn't exist. Currently it assumes that it exists and silently skips the step.

My current cheeky workaround (assuming the user doesn't have  a config already) is to use this step.

```
---

Bootstrap a config file for you (this step should go away eventually when `GatsbyPlugin` is smarter).

<File
 path="gatsby-config.js"
 content="https://raw.githubusercontent.com/gatsbyjs/gatsby/master/starters/hello-world/gatsby-config.js"
/>

---
```

**Comment by KyleAMathews** [comment]
This is published!
