### ISSUE TITLE
What causes these looping console logs?

### ISSUE THREAD

**Issue by appjitsu** [gatsbyjs/gatsby#23481]
after:

success Building development bundle - 32.524s

every 10 seconds it logs another: 

success createPages - 0.009s
success write out requires - 0.001s

![Screen Shot 2020-04-25 at 12 12 56 PM](https://user-images.githubusercontent.com/10903600/80285990-64d15400-86ee-11ea-9304-f3f2d141a83a.png)

**Comment by LekoArts** [comment]
Hi!

Please follow our issue template for filing bugs as otherwise we won't be able to assist you. I can't reproduce this behavior in my local environment. Do you have an editor open for the project that e.g. auto-saves the project? Something on your computer must be triggering the saves.
