### ISSUE TITLE
Make Documentation paragraphs/descriptions single line

### ISSUE THREAD

**Issue by shakib609** [gatsbyjs/gatsby#23482]
## Summary

Hello I am a maintainer of the [gatsby-bn](https://github.com/gatsbyjs/gatsby-bn) project. While translating some documentations I found that in some cases the paragraphs/descriptions are spread over multi-lines rather than a single one. The single line for paragraphs/descriptions is followed in the **React.js** documentation repository too. This leads to easier translation process and updating the translations easier when there's an update. Also, in most files this convention is maintained as far as I can see. Some files got missed I guess.

Some files where I found this issue:
- [docs/tutorial/part-six/index.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/tutorial/part-six/index.md)
- [docs/tutorial/part-seven/index.md](https://raw.githubusercontent.com/gatsbyjs/gatsby/master/docs/tutorial/part-seven/index.md)

### Motivation

We should write the documentations following a single convention so that it's easier for maintainers and translators. As most of the documentations are currently following the single-line convention I think it would be better to follow that. Also, I've seen in my experience while maintaining the **React.js** translation repository that following this makes the update process much easier as you don't have to search every line of a PR and can easily find it by the change on a specific line-number.

## Steps to resolve this issue

We can format our existing documentation to follow the single-line paragraph convention.
I would be happy to work on this.

**Comment by caitlinselca** [comment]
Hi! I am a new contributor to Gatsby and this particular issue interests me a lot. May I begin working on this ticket to resolve the issue? Furthermore, I believe I understand what you expect of this ticket but would you be able to link me to a repo that follows this single-line convention? Thank you!
