### ISSUE TITLE
Change to hyphen for consistency in Tutorial part 4

### ISSUE THREAD

**Issue by adamjamesturner93** [gatsbyjs/gatsby#23487]
## Summary

In tutorial part 4, there is an inconsistency with the hyphens used.

> Gatsby’s data layer lets you pull data from these (and any other source) directly into your components—in the shape and form you want.

vs 

>  data — like the
> Page queries live outside of the component definition — by convention at the end of a page component file — and are only available on page components.

### Motivation

This is suggested for consistency, also my first ever PR to an OS project! Please tell me if I could do anything better!

### Open a pull request

PR #23486 has been opened for this

**Comment by akashjoffl** [comment]
this is fixed now?

**Comment by adamjamesturner93** [comment]
Fixed in the PR I raised above, yes. Just waiting for a review
