### ISSUE TITLE
babel-preset-gatsby-package not working ...

### ISSUE THREAD

**Issue by muhzulzidan** [gatsbyjs/gatsby#23496]
my site muhzulzidan.com is working on old browser, but if i enter a page, like muhzulzidan.com/apa-itu-font... then it will load at frst then it will be blank after load finish..

p.s : i tried it on android browser 4.0.0..in newer browser it is working...

my 

.babelrc

```
{
  "plugins": ["@babel/plugin-proposal-optional-chaining"],
  "presets": [
    [
      "babel-preset-gatsby",
      {
        "targets": {
          "browsers": [">0%", "not dead"]
        }
      }
    ]
  ]
}
```

**Comment by LekoArts** [comment]
Thank you for opening this!

You don't need to use babel-preset-gatsby yourself (also the optional chaining plugin, it already works in Gatsby by default). You should add the browserlist entry in your package.json: https://www.gatsbyjs.org/docs/browser-support/#specify-what-browsers-your-project-supports-using-browserslist

This should solve your problem :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
