### ISSUE TITLE
gatsby-plugin-manifest - programmatically change theme-color in manifest

### ISSUE THREAD

**Issue by shreyansh-zazz** [gatsbyjs/gatsby#23498]
How can I change the `theme-color` in manifest programmatically when the navigation changes?

**Comment by LekoArts** [comment]
Thank you for opening this!

You can use this option to disable it being set by the plugin:
https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/#remove-theme-color-meta-tag

Then you would use react-helmet to set the tag yourself.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
