### ISSUE TITLE
[gatsby-plugin-mdx] Migrating a site using gatsby-transformer-remark to MDX

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#23502]
## Summary

I believe this would be a good document to have in the MDX docs on how do you take a site that was previously built with gatsby-transformer-remark and migrate it to using MDX with gatsby-plugin-mdx.

Some recommended topics to cover:

- Update gatsby-node `onCreateNode` and `createPages` functions
- Update a div with dangerouslySetInnerHTML to MDXRenderer
- Update the GraphQL query in templates to MDX from markdownRemark

### Motivation

Anyone who may be using remark to generate pages but would like the additional features of MDX.

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the "Adding Components to Markdown with MDX" section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by lannonbr** [comment]
If anyone on the @gatsbyjs/learning team is up for it, I think this would be a good topic for a pair programming stream and I'd be interested in pairing on this.

**Comment by Ekwuno** [comment]
Hey @lannonbr thanks for suggesting this. Here is a guide on  how to move forward with the pair programming session.  https://www.gatsbyjs.org/contributing/pair-programming/

**Comment by lannonbr** [comment]
Yep just submitted the form for this

**Comment by mtheoryx** [comment]
I don't know if it helps, but I went through these docs and successfully converted 3 different Gatsby sites from MarkdownRemark to MDX.

Good docs, thanks!
