### ISSUE TITLE
Using multiple Google Analytics tracking codes with gatsby-plugin-google-analytics

### ISSUE THREAD

**Issue by healingfromjava** [gatsbyjs/gatsby#2350]
Hi, is it possible to use multiple Google Analytics tracking codes with gatsby-plugin-google-analytics? It doesn't look like it from looking at the source code at the moment.

If not, looks like I can get around it with the workaround here (unless react-ga doesn't play nicely with Gatsby?): https://github.com/react-ga/react-ga/issues/26#issuecomment-308745075

**Comment by KyleAMathews** [comment]
You can add a PR to the plugin to add support for multiple tracking codes. At the moment it does only support one.

**Comment by healingfromjava** [comment]
We ended up just using React Helmet for whatever we needed, but thanks for the info. I'd love to contribute back further in the future when I have more time.
