### ISSUE TITLE
Can gatsby-source-shopify query videos?

### ISSUE THREAD

**Issue by moritzsalla** [gatsbyjs/gatsby#23500]
Is it possible to query the urls of youtube videos that are added to shopify?

![Bildschirmfoto 2020-04-26 um 14 51 04](https://user-images.githubusercontent.com/42788026/80308119-5c9c1600-87cd-11ea-9304-b948e374fff2.jpg)

**Comment by nandorojo** [comment]
This issue probably belongs on the gatsby-source-shopify repo

**Comment by moritzsalla** [comment]
The gatsby-source-shopify repo states:

NOTE: This repo is archived!
gatsby-source-shopify has been moved to the official Gatsby monorepo. Please submit PRs and issues to that repo instead.

**Comment by LekoArts** [comment]
It depends on whether the Storefront API supports it or not. If you can find the correct API endpoint in their docs (https://shopify.dev/docs/storefront-api) or in their GraphiQL (https://shopify.dev/graphiql/storefront-graphiql) we could know if the source plugin can query that. (I'm asking you to do this as I don't have a Shopify instance set up)
