### ISSUE TITLE
Dynamic meta tags

### ISSUE THREAD

**Issue by jojobagings78** [gatsbyjs/gatsby#23512]
I am currently implementing a page with /asset/:id and routing however when it comes to dynamic meta data it seems to not show anything or even without dynamically changing the title it seems to still not show anything.

`  <Router>
      <ErrorPage default component={ErrorPage}/>
      <Product path="/product/:id" />
    </Router>`

Then I call SEO component passing the title which is static at the moment and not based on data from the page. However it seems that static or dynamic does not work when routing. 

Does anyone have any idea how to get dynamic meta data for pages in gatsby to work and even static while using router ?

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll need to use react-helmet (https://github.com/nfl/react-helmet) on your client-only page and or use the provided <SEO /> component. Here's a working example:

- Router: https://github.com/LekoArts/gatsby-source-tmdb-example/blob/d3f4f23b446526cad2ea2c4fac3c1b8d6b11ee09/src/pages/detail.jsx
- SEO inside the component route: https://github.com/LekoArts/gatsby-source-tmdb-example/blob/d3f4f23b446526cad2ea2c4fac3c1b8d6b11ee09/src/components/DetailedView.jsx#L309-L338
- SEO component: https://github.com/LekoArts/gatsby-source-tmdb-example/blob/d3f4f23b446526cad2ea2c4fac3c1b8d6b11ee09/src/components/SEO.jsx
- Live result: https://tmdb.lekoarts.de/detail/tv/72750

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by jojobagings78** [comment]
> Thank you for opening this!
> 
> You'll need to use react-helmet (https://github.com/nfl/react-helmet) on your client-only page and or use the provided component. Here's a working example:
> 
> * Router: https://github.com/LekoArts/gatsby-source-tmdb-example/blob/d3f4f23b446526cad2ea2c4fac3c1b8d6b11ee09/src/pages/detail.jsx
> * SEO inside the component route: https://github.com/LekoArts/gatsby-source-tmdb-example/blob/d3f4f23b446526cad2ea2c4fac3c1b8d6b11ee09/src/components/DetailedView.jsx#L309-L338
> * SEO component: https://github.com/LekoArts/gatsby-source-tmdb-example/blob/d3f4f23b446526cad2ea2c4fac3c1b8d6b11ee09/src/components/SEO.jsx
> * Live result: https://tmdb.lekoarts.de/detail/tv/72750
> 
> We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!


I took a look at your example and it does not work for sharing eg on social media or skype and etc because it does not read the meta data still. https://tmdb.lekoarts.de/detail/tv/72750

**Comment by jonasbarsten** [comment]
Hi!

I'm having a similar issue as @jojobagings78.

I also checked @LekoArts example with facebooks sharing debugger and it doesn't look happy:

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Ftmdb.lekoarts.de%2Fdetail%2Ftv%2F72750

@jojobagings78, did you figure this out? Or does anyone else have a solution?

All the best.

**Comment by lambdahands** [comment]
Hello, I'm having the same issue with Facebook and meta tag rendering through Gatsby. This seems like a use case that isn't easily supported after digging through other threads with related issues (specifically rendering static content with react-helmet). Has anyone found a good solution to this?

**Comment by Cassianosch** [comment]
Same here

**Comment by Jaime5Alvarez** [comment]
any solution ? Same problem here
