### ISSUE TITLE
gatsby repo is huge, separate blog

### ISSUE THREAD

**Issue by szepeviktor** [gatsbyjs/gatsby#23513]
Current master as a ZIP takes up **half** a CD-ROM!

Do you plan to remove the blog contents and remove its files from git history?
Thank you for considering :)

**Comment by LekoArts** [comment]
Thank you for opening this!

We're aware of the problem and are working on pulling some stuff out of the repository. As a lot of things are intertwined you can't just pull out the blog out of the repo. Anyways, we'll solve it eventually.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
