### ISSUE TITLE
`gatsby develop` does not serve static `index.html` files when directory is accessed

### ISSUE THREAD

**Issue by tech4him1** [gatsbyjs/gatsby#2352]
If my directory structure is this:
```
/static
    /test
        /index.html
```
and I run `gatsby develop`, then I cannot access my `index.html` file by going to `localhost:8000/test/`, I have to go to `localhost:8000/test/index.html`.

**Comment by KyleAMathews** [comment]
Hmmm this is perhaps either a limitation of the node server or a misconfiguration. Feel free to submit a PR if you can see ways to improve it.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/develop.js

**Comment by tech4him1** [comment]
I wonder why there is both of these:
https://github.com/gatsbyjs/gatsby/blob/392e7f2aebda08279a541fadad65eaae6d4f2dca/packages/gatsby/src/utils/develop.js#L88
https://github.com/gatsbyjs/gatsby/blob/392e7f2aebda08279a541fadad65eaae6d4f2dca/packages/gatsby/src/utils/develop.js#L108-L112

**Comment by KyleAMathews** [comment]
Haha probably an oversight.

**Comment by tech4him1** [comment]
We should just be able to use one *or* the other, right?

**Comment by KyleAMathews** [comment]
Yeah we should be using the later. See if anything breaks when removing the first.

**Comment by tech4him1** [comment]
Well, I think this bug is caused because the second (manual) one doesn't check for index files like the built-in middleware. I could try to implement it, it shouldn't be too hard.

**Comment by KyleAMathews** [comment]
Great! Yeah would love a PR.

**Comment by tech4him1** [comment]
I just had a thought for a simpler method:
```js
app.use(express.static(__dirname + `/public`))
  // Render an HTML page and serve it.
  app.use((req, res, next) => {
    const parsedPath = parsePath(req.originalUrl)
    if (parsedPath.extname === `` || parsedPath.extname.startsWith(`.html`)) {
      res.sendFile(directoryPath(`public/index.html`), err => {
        if (err) {
          res.status(500).end()
        }
      })
    } else {
      res.status(404).end()
    }
  });
```
What about just like this? Then we can use the built-in one, and we are still essentially doing the same checking.

**Comment by tech4him1** [comment]
@KyleAMathews Do you see any obvious problems with that example?

**Comment by KyleAMathews** [comment]
Oh… now that I think about it, we could probably just use the built-in static serving now. I added to the bootstrap process a step to delete all html files in public directory which I think was the only reason to have the custom file serving.

So yeah, your code looks like what we want.

**Comment by tech4him1** [comment]
Sounds good. I'm not going to be able to make a PR right away -- if you want to just do it that's fine with me.

**Comment by KyleAMathews** [comment]
@tech4him1 probably won't get to this soon so would love a PR when you have time or anyone else who sees this issue and wants it solved!

**Comment by KyleAMathews** [comment]
Hey, closing out old issues. Please re-open if you have additional questions, thanks!

**Comment by Bouncey** [comment]
@KyleAMathews This issue is still relevant in gatsby@2.0.0-rc.10, we @freecodecamp are trying to resolve this. Would you like a new issue or should I reopen this one?

**Comment by pieh** [comment]
Let's reopen this one

**Comment by tech4him1** [comment]
Thanks for implementing @Yurickh!

**Comment by simoneb** [comment]
Already commented in the linked [PR](https://github.com/gatsbyjs/gatsby/issues/2352), but this doesn't seem to work for me.

**Comment by patriziosotgiu** [comment]
I'm having the same issue, also commented on the PR.

**Comment by simoneb** [comment]
New issue created #13072
