### ISSUE TITLE
[gatsby-source-contentful] Getting Cannot query field "xxx" on type "Query" error when changing content model name

### ISSUE THREAD

**Issue by jgabriele** [gatsbyjs/gatsby#23539]
## Description

I was able to fetch content until I changed the display name of the content model on contentful. Looks like all graphql elements are bound to the display name (red) and not the api name (green)

![image](https://user-images.githubusercontent.com/395650/80412084-92c0bf00-88cd-11ea-86f6-a67cdc3f4407.png)

### Steps to reproduce

- Create an app with gatsby-source-contentful setup.
- Create a content model and create a content of that type
- Run `gatsby develop`
- Open http://localhost:8000/__graphql
→ You will see the content model with the initial name, everything is ok

- Modify the display name of the content model (content model > select your content model > Edit on the top, next to the name)
- Run `gatsby develop`
→ Error in the console. If you open http://localhost:8000/__graphql you'll see that you can query type with the "new name" `allContentful<CamelcasedNewName>`)

### Expected result

Nothing should change. Display name is for contentful.com only, should not impact the api

### Actual result

```bash
There was an error in your GraphQL query:

Cannot query field "contentfulCompanyFiles" on type "Query".

If you don't expect "contentfulCompanyFiles" to exist on the type "Query" it is most likely a typo.
However, if you expect "contentfulCompanyFiles" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "contentfulCompanyFiles" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
```

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 74.0.1
    Safari: 12.0
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12 
    gatsby-image: ^2.3.1 => 2.3.1 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6 
    gatsby-plugin-s3: ^0.3.3 => 0.3.3 
    gatsby-plugin-sharp: ^2.5.3 => 2.5.3 
    gatsby-plugin-typography: ^2.4.1 => 2.4.1 
    gatsby-source-contentful: ^2.2.7 => 2.2.7

**Comment by wardpeet** [comment]
Hey,

https://www.gatsbyjs.org/packages/gatsby-source-contentful/#configuration-options has an option called `useNameForId` that is set to `true` by default. If you set it to false, your bug will be fixed.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
