### ISSUE TITLE
Converting an array of paths to local files

### ISSUE THREAD

**Issue by yepes** [gatsbyjs/gatsby#23533]
## Summary
Trying to use a local file (a string from a graphql query) as a File in the Img component
## Relevant information

This is a sample query:
```
{
  mysqlSet(entity_id: {eq: "10270"}) {
    name
    images {
      url
    }
  }
}
```

Result:

```
{
  "data": {
    "mysqlSet": {
      "name": "My Entity Name",
      "images": [
        {
          "url": "./images/10270-0.png"
        },
        {
          "url": "./images/10270-1.png"
        },
        {
          "url": "./images/10270-2.png"
        }
      ]
    }
  }
}
```

I need to use the first image as a cover in a page. I know I'm suppossed to update the schema, but I can't get my head around this issue. All images are on my filesystem

Basically, I need to grab the images as files to use them with gatsby's built-in Img component.

### Environment (if relevant)

System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.19.45 => 2.20.12
    gatsby-cli: ^2.11.5 => 2.11.5
    gatsby-image: ^2.3.1 => 2.3.1
    gatsby-plugin-manifest: ^2.2.48 => 2.3.3
    gatsby-plugin-offline: ^3.0.41 => 3.1.2
    gatsby-plugin-react-helmet: ^3.1.24 => 3.2.1
    gatsby-plugin-sass: ^2.2.1 => 2.2.1
    gatsby-plugin-sharp: ^2.5.4 => 2.5.4
    gatsby-source-filesystem: ^2.2.2 => 2.2.2
    gatsby-source-mysql: ^2.2.2 => 2.2.2
    gatsby-transformer-remark: ^2.7.1 => 2.7.1
    gatsby-transformer-sharp: ^2.4.4 => 2.4.4
  npmGlobalPackages:
    gatsby-cli: 2.11.5

**Comment by marcysutton** [comment]
Hi @yepes, do you have an example repo for us to check out? And have you tried following the Schema Customization section on feeding remote images? I know they're local to your computer, but you could try to write some customResolver code for your `mysqlSet` type: https://www.gatsbyjs.org/docs/schema-customization/#feeding-remote-images-into-gatsby-image
