### ISSUE TITLE
gatsby's error catching development code found in production

### ISSUE THREAD

**Issue by pindjur** [gatsbyjs/gatsby#23550]
I found bunch of error checks and messages  in gatsby production build coming from app-[hash].js
Can we remove this like React did in their production code?
I tried to contribute but im still begginer.
If this is a feature, can it be disabled through env variables?
We dont debug production code but if we do could it will be possible to debug via source maps without error checks in app-[hash].js?

**Comment by LekoArts** [comment]
Hi, please follow our issue template as otherwise we don't understand what you're asking and thus we can't help you.

```markdown
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.org/docs/
  - How to File an Issue: https://www.gatsbyjs.org/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by pindjur** [comment]
## Description
There is unnecessary code in production build generated by gatsby

### Steps to reproduce
run gatsby build and gastby serve  in gatsby starter default project root folder. 
Open developer tools and go to sources panel.
open app.js
here is hosted gatsby starter default script at the time of writing 
https://gatsby-starter-default-demo.netlify.app/app-812755817ebf00dbab64.js


### Expected result
There should'n be error throwing and checking for error throwing


### Actual result
there is 50 + error messages, even for PropTypes which is used only in development while in react srcipt 



What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the 

https://gatsby-starter-default-demo.netlify.app/app-812755817ebf00dbab64.js

**Comment by pieh** [comment]
Ok few notes:

`prop-types` specific: we do use https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types but it tuns out it doesn't handle some cases (including ones we pack by default):

Cases that it can't handle is when you set `propTypes` on component that is wrapped with `React.forwardRef` (like our `gatsby-link`). I would expect similar thing happening with `React.memo` (but not confirmed that yet). I will be creating reproduction and creating issue in its repository of plugin about this.

In any case - in production `shim`ed version is used (which is pretty much just this https://github.com/facebook/prop-types/blob/master/factoryWithThrowingShims.js and this does include the warning you mentioned).

But let's make a list of thing that are in default starter bundles and see which ones we actually can fix:

Ones that actually originate from `gatsby` (and not from some dependencies) and we can drop:
 - https://github.com/gatsbyjs/gatsby/blob/b24d80249f6c6aeab8fc8bd9c6265dd8d1933230/packages/gatsby/cache-dir/gatsby-browser-entry.js#L64-L71
For this we can add ``process.env.NODE_ENV === `development` `` (similar to error we have a bit above it) to remove it from production (builds will fail anyway before we reach this stage)
 - https://github.com/gatsbyjs/gatsby/blob/b24d80249f6c6aeab8fc8bd9c6265dd8d1933230/packages/gatsby/cache-dir/gatsby-browser-entry.js#L75-L81
similarly - we can wrap it as well as we don't actually use this function in production (it get's replaced)

We for sure can't really touch react-dom ones:
 - `Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.` for example

There few coming from `@reach/router` ( https://github.com/reach/router/blob/1f26ef04fce873a78c6a4c4605b6c1ec29bea7a8/src/index.js#L526-L578 ) 

Few coming from `react-side-effect` (dependency of `react-helmet`) - https://github.com/gaearon/react-side-effect/blob/f1e020719f5cc429b96b260cab80ed51b63421a5/src/index.js#L14-L22

There are few cases of error we throw, but they are actually meant specifically for production code in lot of cases as well.

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v4 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

[reproduction]: https://gatsby.dev/reproduction
