### ISSUE TITLE
Adding assetPrefix to Blog starter adds slash to beginning of gif urls after gatsby build

### ISSUE THREAD

**Issue by leadream** [gatsbyjs/gatsby#23556]
## Description

I created a blog stater project and add `assetPrefix` to `gatsby-config.js`, but it generates a wired url for gif in markdown file when building.

### Steps to reproduce

1. Clone [this repository](https://github.com/leadream/gatsby-starter-blog), the diff from gatsby-stater-blog is [here](https://github.com/leadream/gatsby-starter-blog/commit/1d00c00263f8bdf87f0709db0310c78cf0cd971d).
2. Install dependencies
3. Run `yarn build`
4. Look into `public/hello-world/index.html` and find `Kabutack.gif`
5. This img's url is wired (It's `/https:/cdn.jsdelivr.net/gh/leadream/juuun.io@gh-pages/63c893e9f09f78fd314f5205a266006f/Kabutack.gif`)

### Expected result
This img's url should be `https://cdn.jsdelivr.net/gh/leadream/juuun.io@gh-pages/63c893e9f09f78fd314f5205a266006f/Kabutack.gif`, without the first slash.

### Actual result
This img's url is `/https:/cdn.jsdelivr.net/gh/leadream/juuun.io@gh-pages/63c893e9f09f78fd314f5205a266006f/Kabutack.gif` and can't access.

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 70.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.21.0 => 2.21.0
    gatsby-image: ^2.4.0 => 2.4.0
    gatsby-plugin-feed: ^2.5.0 => 2.5.0
    gatsby-plugin-google-analytics: ^2.3.0 => 2.3.0
    gatsby-plugin-manifest: ^2.4.0 => 2.4.0
    gatsby-plugin-offline: ^3.2.0 => 3.2.0
    gatsby-plugin-react-helmet: ^3.3.0 => 3.3.0
    gatsby-plugin-sharp: ^2.6.0 => 2.6.0
    gatsby-plugin-typography: ^2.5.0 => 2.5.0
    gatsby-remark-copy-linked-files: ^2.3.0 => 2.3.0
    gatsby-remark-images: ^3.3.0 => 3.3.0
    gatsby-remark-prismjs: ^3.5.0 => 3.5.0
    gatsby-remark-responsive-iframe: ^2.4.0 => 2.4.0
    gatsby-remark-smartypants: ^2.3.0 => 2.3.0
    gatsby-source-filesystem: ^2.3.0 => 2.3.0
    gatsby-transformer-remark: ^2.8.0 => 2.8.0
    gatsby-transformer-sharp: ^2.5.0 => 2.5.0
```

**Comment by tribotissues** [comment]
Is there any work around for this in the time being?

**Comment by darron1217** [comment]
Why this issue closed?
I'm still experiencing same issue on `3.2.1` version

**Comment by jcomo** [comment]
For anyone else who stumbles on this abandoned issue, the fix is to update `gatsby-remark-copy-linked-files` 2.3.16. See the patch here: https://github.com/gatsbyjs/gatsby/pull/26976
