### ISSUE TITLE
Backticks (or expressions) used in exported constants in mdx files are not seen in GraphiQL

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#23564]
Trying to access `exported` constants within a `mdx` file through `GraphQL`

I can see them if I define the constant with normal quotes

```js
export const howareyou = 'very well'
```

This example works (I can see it in `GraphiQL`)

But if I use the backtick quotes (i.e. [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals))

```js
export const howareyou = `very well`
```

 Then it doesn't work (I cannot see it in `GraphiQL`)

(my use case is that I'd like to have multi-lines there)

Is it a bug of there's an explanation not to allow them? 

EDIT: any expression fails (I was trying to workaround the backticks unavailability)

```js
export const howareyou = 'very' + 'well'
```

**Comment by ivandevp** [comment]
May I help with this issue?

**Comment by ivandevp** [comment]
After debugging through the source code, I found that ignoring expressions is the [expected behavior](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/utils/babel-plugin-gather-exports/index.test.js). Not sure why, hope someone else can help us understand it.

**Comment by kuworking** [comment]
> After debugging through the source code, I found that ignoring expressions is the [expected behavior](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/utils/babel-plugin-gather-exports/index.test.js). Not sure why, hope someone else can help us understand it.

In my case this forces me to duplicate constants, one without new lines (obfuscated) so that I can read it through a graphql static query, and the other for consumption within the same mdx document (not obfuscated, easy to be modified if it has to)

If that's the expected behavior, then it would be a great feature for the future ...

**Comment by laurieontech** [comment]
Thanks for the PR! This is expected behavior at the moment but certainly something we'd consider supporting down the road. We'd likely limit that support to template literals rather than interpolated template literals or full-fledged expressions.
