### ISSUE TITLE
Gastby Image not working after Netlify Build

### ISSUE THREAD

**Issue by bradleyDouglas** [gatsbyjs/gatsby#23577]
## Description

I'm currently developing a simple site using Prismic, Gatsby and Netlify. When I use `gatsby develop` everything works and looks just like I would expect.

However, after Netlify builds, all of the `gatsby-images` do not work. Technically, the gatsby-image-wrapper is there in the DOM and the `img` that's used for the blur-up is there too. What's missing is the `picture` element. 

In my console I am seeing this error: `TypeError: Cannot read property 'childImageSharp' of undefined`

When I inspect a log of the object in the console, I can drill down and see that the image is in the static file. `Object => node => splash_imageSharp => fluid`

If I copy the `src` and tack it onto the end of my URL I can see the image. 

### Steps to reproduce

Here is a link to the site. If you inspect the console you will see what I am talking about:
https://modest-bell-fb1e56.netlify.app/

### Expected result

I would expect the `gatsby-image` to work like it does when I use it locally.

### Actual result

Gatsby Image is just a blurred image. 

### Environment

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.9.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.21.1 => 2.21.1 
    gatsby-image: ^2.4.0 => 2.4.0 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-layout: ^1.3.0 => 1.3.0 
    gatsby-plugin-manifest: ^2.4.1 => 2.4.1 
    gatsby-plugin-offline: ^3.2.0 => 3.2.0 
    gatsby-plugin-react-helmet: ^3.3.0 => 3.3.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.3.0 => 2.3.0 
    gatsby-plugin-sharp: ^2.6.0 => 2.6.0 
    gatsby-plugin-sitemap: ^2.4.0 => 2.4.0 
    gatsby-source-filesystem: ^2.3.0 => 2.3.0 
    gatsby-source-prismic-graphql: ^3.6.2 => 3.6.2 
    gatsby-transformer-sharp: ^2.5.0 => 2.5.0 
  npmGlobalPackages:
    gatsby-cli: 2.4.8

**Comment by madalynrose** [comment]
Hi there, @bradleyDouglas! Thanks for letting us know about this issue. Is this specific to Netlify or are you seeing this locally with `gatsby build` as well? Is it possible to link to your repo or create a simplistic reproduction in something like [codesandbox](https://codesandbox.io/)? It's hard to debug without seeing code.

**Comment by bradleyDouglas** [comment]
Hi @madalynrose, thanks for the reply. Unfortunately, this is happening locally with `gatsby build` as well. Absolutely, here is the repo: [Repo](https://github.com/bozell-omaha/wine-whiskey-wishes)

I've also opened up my Prismic API for the time being so you can remove the line for the `accessToken` in the `gatsby-source-prismic-graphql` plugin and run the commands to develop and build.

**Comment by chrish-d** [comment]
Just wanted to drop a note to say I'm having the same issue, also using `gatsby-source-prismic-graphql`

**Comment by bradleyDouglas** [comment]
@chrish-d and @madalynrose, this issue appears to be an issue with the `gatsby-source-prismic-graphql` plugin. 

I switched to the `gatsby-source-prismic` plugin and now everything is working.

**Comment by chrish-d** [comment]
@bradleyDouglas yeah I eventually noticed that's what you did, but it requires refactoring everything.

For now, I've had to disable `gatsby-image` but hopefully we can get a fix from the author soon.

I've opened a separate issue [here](https://github.com/birkir/gatsby-source-prismic-graphql/issues/195) as I feel this is strictly an issue with the plugin and not a gatsby issue.

**Comment by MartinSchere** [comment]
Same issue here. On build it's not working...
