### ISSUE TITLE
gatsby-plugin-netlify Caching configuration examples

### ISSUE THREAD

**Issue by juliensl** [gatsbyjs/gatsby#23586]
Hi everybody !

## Summary

What problem(s) did you run into that caused you to request additional documentation? What questions do you think we should answer? What, if any, existing documentation relates to this proposal?

It's not easy to fill the **gatsby-plugin-netlify** headers in the gatsby-config.js

Some recommended topics to cover:

- https://www.gatsbyjs.org/docs/caching/
- https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/
- https://docs.netlify.com/routing/headers/

### Motivation

Why should we document this and who will benefit from it?

Currently, developer has to read the Caching doc, the gatsby-plugin-netlify doc and the Netlify headers doc to understand and fill the headers config.
But, I think that lot's of people just want to configure the classical schema that you describe in the Caching documentation, no more.

## Steps to resolve this issue

It could be nice to have one or more examples of the "classic" configurations for headers and caching in the gatsby-plugin-netlify doc. I guess that lot's of devs just need to copy past it.

## Caching headers example

Here, a code example of the configuration describe here [Caching Static Sites Caching](https://www.gatsbyjs.org/docs/caching/)

```
module.exports = {
    plugins: [
      {
      resolve: `gatsby-plugin-netlify`,
      options: {
        headers: {
          "/**/*.html": [
            "cache-control: public",
            "cache-control: max-age=0",
            "cache-control: must-revalidate",
          ],
          "/page-data/*.json": [
            "cache-control: public",
            "cache-control: max-age=0",
            "cache-control: must-revalidate",
          ],
          "/app-data.json": [
            "cache-control: public",
            "cache-control: max-age=0",
            "cache-control: must-revalidate",
          ],
          "/static/*": [
            "cache-control: public",
            "cache-control: max-age=31536000",
            "cache-control: immutable",
          ],
        },
      },
    },
  ],
```

Currently, I did not configure the "JavaScript and CSS" part, because I do not understand how to except the /sw.js file. 

### Open a pull request

I will do it at the beginning of the afternoon

Thank you everybody, have a good day :)

**Comment by pixelfreak** [comment]
@juliensl Would love to see what you have or to help out if I can. Thanks

**Comment by doublejosh** [comment]
Javascript and CSS are placed in the root and this config doesn't address them at all :)
