### ISSUE TITLE
Using incremental build feature in Gatsby-Cloud

### ISSUE THREAD

**Issue by jay-coditas** [gatsbyjs/gatsby#23585]
Hello
I have a trial professional account in GatsbyCloud, I need to see the incremental build feature in action
So I've linked my Gatsby-application from GitHub and I've made sure that the incremental build feature is ON in the site setting
I know it takes time to build for the first time
The Gatsby-application that I have linked from GitHub account contains a plugin gatsby-source-git which picks up content files from a repository
Rest of the things are all local, I have to yet do the hosting part
So, from the Gatsby dashboard, I did the Trigger build 
I did not select the clear cache and build option
So as of now, I'm manually triggering build from the dashboard in Gatsby-Cloud,
Yet I don't see any noticeable time difference in the subsequent builds.
What am I doing wrong here?

**Comment by KyleAMathews** [comment]
Hi! Thanks for the question. This forum is for discussions around the open source project. For questions on Gatsby Cloud, you can write in the help box there.
