### ISSUE TITLE
Importing header.js to index greyed out and white black page death.

### ISSUE THREAD

**Issue by theboyonline** [gatsbyjs/gatsby#23584]
## Description

I'm trying to Importing header.js to index greyed out and white black page death.
This is the repo https://github.com/theboyonline/gatsbynewsite

### Steps to reproduce

import Header from "../components/header"
 to index page.

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

import success and render page 

### Actual result

import greyed out and render of page white page death.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.17.4 => 2.17.4 
    gatsby-image: ^2.2.29 => 2.2.29 
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23 
    gatsby-plugin-offline: ^3.0.16 => 3.0.16 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13 
    gatsby-plugin-sass: ^2.1.20 => 2.1.20 
    gatsby-plugin-sharp: ^2.2.32 => 2.2.32 
    gatsby-source-filesystem: ^2.1.33 => 2.1.33 
    gatsby-transformer-sharp: ^2.3.0 => 2.3.0 
  npmGlobalPackages:
    gatsby-cli: 2.11.22

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll need to capitalize your component:
https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
