### ISSUE TITLE
Provide refresh webhook headers in API NodePluginArgs

### ISSUE THREAD

**Issue by Simply007** [gatsbyjs/gatsby#23593]
# Summary

Allow working with [webhook's](https://www.gatsbyjs.com/docs/webhook) headers as well.
Extend `NodePluginArgs` with headers of the webhook (currently only `NodePluginArgs.webhookBody` is available).

### Basic example

The common practice using webhook is to validate the signature to prevent faking the webhooks.
The signature is commonly sent as a part of the headers of the request.

I.e. Headless CMS [Kentico Kontent webhooks notification docs](https://docs.kontent.ai/reference/webhooks-reference#a-notification-signatures).

To be able to validate that hash/signature, it would be great to have the data accessible in `NodePluginArgs`.

### Motivation

That could prevent to mock refresh webhooks and potentially protect Gatsby Cloud for some DDoS attacks.

**Comment by Simply007** [comment]
@vladar - any update on this?

**Comment by vladar** [comment]
Want to prepare a PR for this? I think simple passing webhookHeaders along with webhookBody should be enough?

**Comment by Simply007** [comment]
Yeap - it could do that.

I checked the [occurrences if webhookBody](https://github.com/gatsbyjs/gatsby/search?q=webhookBody&unscoped_q=webhookBody) in code and it looks quite OK to add the functionality there. 

I might need some guidance on [e2e tests](https://github.com/gatsbyjs/gatsby/blob/561d33e2e491d3971cb2a404eec9705a5a493602/e2e-tests/development-runtime/plugins/gatsby-source-fake-data/gatsby-node.js#L19) and [integration ones](https://github.com/gatsbyjs/gatsby/blob/fc61f067cb9fbcdcb743c3baaf6abe0037435da0/integration-tests/structured-logging/gatsby-node.js).

**Comment by Simply007** [comment]
There is a draft pull request with the implementation:
* https://github.com/gatsbyjs/gatsby/pull/24430
