### ISSUE TITLE
How do I add .gif with gatsby-image plugin?

### ISSUE THREAD

**Issue by beingabstrac** [gatsbyjs/gatsby#23598]
# How do I add .gif with gatsby-image plugin?

**Comment by vladar** [comment]
Hi @beingabstrac 

The official documentation has a [note on this](https://www.gatsbyjs.org/packages/gatsby-image/#some-other-stuff-to-be-aware-of):

> Gifs can’t be resized the same way as pngs and jpegs, unfortunately—if you try to use a gif with gatsby-image, it won’t work. For now, the best workaround is to import the gif directly.

Also, check out the [working with gifs](https://www.gatsbyjs.org/docs/working-with-gifs/) section of docs.

**Comment by vladar** [comment]
Thank you for opening this, @beingabstrac 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
