### ISSUE TITLE
[bug] gatsby-plugin-mdx timeToRead drastically increases memory usage

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#23614]
## Description

A recent change to gatsby-plugin-mdx adds HTML generation to the `timeToRead` slug, which I believe is causing pretty severe issues with increasing build time (potentially causing OOM issues in some environments).

I'd recommend we revert #19763 as we most likely won't want to render all MDX posts to HTML to get time to read.

### Steps to reproduce

1. Use gatsbyjs.org (www/ in this example) and build; you may hit OOM, and you'll definitely see warnings a la
	```
	Query takes too long: File path: /usr/src/app/www/www/src/templates/template-blog-post.js URL path: /blog/2020-04-29-incredimental-builds/ Context: { "slug": "/blog/2020-04-29-incredimental-builds/", "prev": { "title": "2 Months and 2x Performance: Codebrahma accelerates Serverless.com with Gatsby", "link": "/blog/2020-04-27-building-Serverless-site-faster-with-Gatsby/" }, "next": null }
	```
1. Pin the version of gatsby-plugin-mdx to 1.2.1 (Change was introduced in 1.2.2 -> https://github.com/gatsbyjs/gatsby/compare/gatsby-plugin-mdx@1.2.1...gatsby-plugin-mdx@1.2.2) and build.
1. No errors / no OOM / etc.

### Expected result

It should not OOM.

### Actual result

It did.

## Related Issues

#19763

**Comment by wardpeet** [comment]
We reverted the change and everything should be back to normal when using
- gatsby-plugin-mdx@1.2.5
- gatsby-transformer-remark@2.8.5
