### ISSUE TITLE
normalization of siteUrl metadata property in gatsby-config can cause confusion

### ISSUE THREAD

**Issue by rwlnd** [gatsbyjs/gatsby#23616]
Hi. I'm reporting some confusion I encountered related to the normalization of the siteUrl property of the gatsby-config metadata, done in this PR: https://github.com/gatsbyjs/gatsby/pull/12139

## Summary

Although I'm sure that the normalization of the siteUrl of the metaData was done with good intentions, I must say that I just ran into some confusing behavior when working with the `siteUrl`.

While adding a sitemap to my gatsby project (using the gatsby-plugin-advanced-sitemap) I added the `siteUrl` property to the metadata in gatsby-config in order to make the plugin work. By accident I added a trailing slash in the siteUrl. I had a similar property `url` which I used for SEO meta image tag generation. After refactoring my code to only use `siteUrl`, I noticed that a slash was missing in my generated path. After _googling around_ to see if something was wrong with the plugin, and investigating quite further, I came across the mentioned PR and found out that gatsby is stripping the trailing slash of the metadata `siteUrl`.

Long story short: It can be very confusing that gatsby is silently changing the content of the `siteUrl` property on the metadata. There is no info about this behavior (as far as I can tell) and can lead to weird effects when people add the property and rely on it for path generation somewhere else in the code.

I also did a quick search through the gatsby repo and found that some starters / plugins are still using url's with trailing slashes for siteUrl in metadata. This makes it extra confusing. Some examples:
- https://github.com/gatsbyjs/gatsby/blob/master/starters/blog/gatsby-config.js
- https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/themes/getting-started.md

## Steps to resolve this issue

I think it would be nice to make a list of "reserved"  or "normalized" metadata keywords and add those on the gatsby config page in the documentation - https://www.gatsbyjs.org/docs/gatsby-config/

Another solution might be to work with a normalized version of the `siteUrl` behind the scenes without actually changing the `siteUrl` on the metadata object.

I Hope I made this somewhat understandable and make sense.

Would like hear your thoughts about this + ways I maybe could help to streamline this.

**Comment by pieh** [comment]
You are right. I was actually recently caught by surprise that we validate (and modify) `siteUrl` in other issue ( https://github.com/gatsbyjs/gatsby/issues/23468 ). I think that lot of plugins right now rely on those values being sanitized, so I don't think we will remove it.

`siteUrl` is only `siteMetadata` that we normalize:  https://github.com/gatsbyjs/gatsby/blob/09054c1b7749e0b910de98e719b0835794477704/packages/gatsby/src/joi-schemas/joi.ts#L35-L37

One thing we could do in code - is to print out message when something is being sanitized, so user see that and can adjust their config, and so it's not a surprise later that the value is different than supplied.

The suggestions about documentation are good points, we should add information to page about `gatsby-config` as well as look for any instances of `siteUrl` in docs and make sure they are uniform. Adjusting starters also should be done.
