### ISSUE TITLE
Remove webpack.stats.json from production build

### ISSUE THREAD

**Issue by slaking** [gatsbyjs/gatsby#23629]
## Summary

Could we have an option to remove all files from the build directory that is not necessary for the final working site?

### Basic example

It seems like webpack.stats.json is not needed. Are some of the other *.js files also not needed for a functioning website.

### Motivation

I would like to have minimal output and not have any unecessary files. Also, some files like webpack.stats.json leak some internal info about the source files. It would be cleaner to have only the minimal set of files in the final build output directory.

**Comment by pieh** [comment]
> It seems like webpack.stats.json is not needed.

Right now this file is used by various plugins, but we could remove it just before the finishing the build

> Are some of the other *.js files also not needed for a functioning website.

What other *.js files do you mean here? I know that there is another .json file (chunks-map?) that could use similar treatment.

**Comment by slaking** [comment]
I don't know enough about the internals to know what's used, but if I were treating it as a black box, I'd just try removing every file and see if the site still works. If it does, then we can remove that file. "manifest.webmanifest" is another one if you don't care about PWA. Maybe "chunk-map.json", but I don't know what that does.

This request might be some post-build step that cleans up the output directory.

**Comment by slaking** [comment]
I still think this would be useful.

**Comment by wardpeet** [comment]
I agree there is no need to upload this file. Let's put it in the .cache folder in a major release. I don't think that this is a big deal, to be honest.

**Comment by coreyward** [comment]
Bump. Not stale.

**Comment by davidstelter** [comment]
Files like webpack.stats.json being deployed can cause false positives for information exposure in automated security scanners, so having a clean way to address this without custom intervention by end-users would be good.

**Comment by vicdemgit** [comment]
Our security scan flags this file. This needs to be reopened

**Comment by samajammin** [comment]
We'd also like to have this file removed from production build for security purposes.

Agree a Gatsby-native solution would be ideal but has anyone found an alternative way to accomplish this?

**Comment by tmttn** [comment]
@thompsonsj did you try out your last comment about the server redirect rules? We are also getting security flagged for this and I would like to know if your solution worked.

**Comment by vtc-ivanb** [comment]
any news here?
