### ISSUE TITLE
gatsby-source-drupal : Remote images download fails for images stored on S3, when using Basic Auth.

### ISSUE THREAD

**Issue by rugggger** [gatsbyjs/gatsby#23632]
## Description

I am sourcing data to Gatsby using gatsby-source-drupal plugin with authentication:
```
 {
      resolve: 'gatsby-source-drupal',
      options: {
        baseUrl: process.env.DRUPAL_API_BASEURL,
        preview: true,
        basicAuth: {
          username: 'admin',
          password: 'password',
        },
      }
    },
```

The sourcing of the data works but the remote images are not downloaded correctly. 
(the images are not local on the drupal site but stored on S3 using the Drupal module s3fs).

When I remove the 'basicAuth' part and connect as an anonymous user it works fine.

### Steps to reproduce

Create a Drupal site that stores images on S3 (s3fs module for example).

Connect to the site using 'gatsby-source-drupal' with basic authentication, and your remote images will fail to download.

### Expected result

Remote images should be downloaded locally.

### Actual result

The remote images download fails.

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.7.0/bin/npm
  Languages:
    Python: 3.7.3 - /Users/yaronbar/anaconda3/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.3.3 => 2.3.3
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-offline: ^3.1.2 => 3.1.2
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1
    gatsby-plugin-s3: ^0.3.3 => 0.3.3
    gatsby-plugin-sharp: ^2.5.5 => 2.5.5
    gatsby-source-drupal: ^3.4.3 => 3.4.3
    gatsby-source-filesystem: ^2.2.2 => 2.2.2
    gatsby-transformer-sharp: ^2.4.5 => 2.4.5
  npmGlobalPackages:
    gatsby-cli: 2.11.8

**Comment by LekoArts** [comment]
What does your `gatsby-config.js` look like?

**Comment by rugggger** [comment]
`require('dotenv').config({
  path: `.env.${process.env.NODE_ENV}`
});

module.exports = {
  siteMetadata: {
    title: `Top 10 Israel`,
    description: `Top 10 Israel info.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-material-ui`,
    {
      resolve: 'gatsby-source-drupal',
      options: {
        baseUrl: process.env.DRUPAL_API_BASEURL,
        preview: true,
        basicAuth: {
          username: 'admin',
          password: 'pass',
        },
      }
    },
    {
      resolve: `gatsby-plugin-s3`,
      options: {
        bucketName: process.env.S3_BUCKET_NAME,
        protocol: "https",
        hostname: "www.top10israel.com",
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-plugin-prefetch-google-fonts`,
      options: {
        fonts: [
          {
            family: `Merriweather`,
            variants: [`300`, `700`,`900`]
          },
          {
            family: `Roboto`,
            subsets: [`latin`]
          },
        ],
      },
    },
    {
      resolve: 'gatsby-background-image',
      options: {
        // add your own characters to escape, replacing the default ':/'
        specialChars: '/:',
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
`

**Comment by rugggger** [comment]
Upon further investigation I noticed that the basicAuth option actually doesn't seem to work.  It seems the JSON API logs as an anonymous reason.

**Comment by eojthebrave** [comment]
Do you have the HTTP Basic Authentication module enabled in Drupal? If not, does turning it on fix the problem?

**Comment by rugggger** [comment]
Basic Authentication is enabled.

Seems to me the issue is really about the Basic Authentication module. I do not manage to send an authenticated request through Postman either.

**Comment by rugggger** [comment]
It was a Basic Authentication issue - not related to gatsby at all. It is working properly. Closing the issue.
