### ISSUE TITLE
Inline Images On Markdown Don't Work

### ISSUE THREAD

**Issue by alphonso06** [gatsbyjs/gatsby#23630]
## Description

Hello, I was checking out how to correctly put inline images into markdown files using `gatsby-transformer-remark` and it doesn't seem to function properly. It displays the 'broken image' icon.

![image](https://user-images.githubusercontent.com/43776043/80678550-acd8e800-8aed-11ea-85d0-6af9a7f53895.png)

### Steps to reproduce

1. Follow [these instructions](https://www.gatsbyjs.org/docs/working-with-images-in-markdown/) for transformer remark

2. Your `gatsby-config.js` file should have the following:
```js
`gatsby-plugin-sharp`,
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 800,
            }
          }
        ]
      }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `markdown`,
        path: `${__dirname}/src/markdown`,
      },
    },
```

### Expected result

I assume it's supposed to allow me to display images on my markdown posts.

### Actual result

It fails with the result above.

### Environment

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - C:\Python27\python.EXE
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.20.2 => 2.20.36 
    gatsby-image: ^2.4.0 => 2.4.0 
    gatsby-plugin-manifest: ^2.3.1 => 2.3.7 
    gatsby-plugin-offline: ^3.1.0 => 3.1.5 
    gatsby-plugin-react-helmet: ^3.2.0 => 3.2.5 
    gatsby-plugin-sass: ^2.2.0 => 2.2.4 
    gatsby-plugin-sharp: ^2.6.0 => 2.6.0 
    gatsby-remark-images: ^3.3.0 => 3.3.0 
    gatsby-source-filesystem: ^2.3.0 => 2.3.0 
    gatsby-transformer-remark: ^2.8.0 => 2.8.0 
    gatsby-transformer-sharp: ^2.5.0 => 2.5.0 
```

**Comment by alphonso06** [comment]
# Possible Solution
I'm not sure if it's considered good practice but I have been able to correctly display the image on the markdown file using `gatsby-remark-relative-images`.

## How to do it
1. Install the plugin `npm install --save gatsby-remark-relative-images`
2. Adjust your `gatsby-config.js`:
```js
{
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/assets/images`,
        name: `images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `markdown`,
        path: `${__dirname}/src/markdown`,
      },
    },
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-relative-images`,
          },
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 600,
            },
          },
        ],
      }
    },
```
3. Run the development server `npm run develop`

Everything should just work fine after that.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by danabrit** [comment]
Closed due to no response for reproduction, and to issue being apparently resolved.
