### ISSUE TITLE
Firefox HMR error in console 

### ISSUE THREAD

**Issue by wesbos** [gatsbyjs/gatsby#23647]
This isn't breaking anything, but on every single page load, I get this error with either versions of hot reloading turned on:

```
The connection to http://localhost:8000/__webpack_hmr was interrupted while the page was loading
```

Followed by `[HMR] Connected`.

This is in Firefox only and I had the exact same issue in Next.js, which was fixed here: 

https://github.com/zeit/next.js/issues/9776

It seems like the fix was adding this:

```js
    window.addEventListener('beforeunload', () => {
      closePing()
    })
```

https://github.com/zeit/next.js/pull/9798/files

### Steps to reproduce

1. Clone a website - like gatsby starter. 
2. Open in Firefox (I'm using developer edition)
3. View the console error

### Environment

  System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.9.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 59.0.1
    Safari: 13.0.4
  npmGlobalPackages:
    gatsby: 2.15.14

**Comment by pieh** [comment]
Thanks for pointer to Next.js fix, but `closePing()` is using some of Next.js internals that make use of `EventSource`. We likely do need similar fix, but we don't use `EventSource` directly, so this is hidden somewhere in our dependencies. So from initial evaluation this might need fix somewhere upstream - we just need to figure out where :)
