### ISSUE TITLE
Do the routes (publicURL) created by `gatsby-image` change in every build?

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#23654]
If I am using a gatsby processed image to be consumed by the website AND also for schema purposes with `publicURL`, will the route vanish with every compilation, so that any twitter of facebook post will lose the link to that image?

In that case (that I guess is the case), the recommended way is to use an image located in the static folder?

**Comment by pieh** [comment]
The paths are using some hash value calculated from file content. So if you edit the file in any way, the path will change. This is important to be able to setup permanent caching of assets like that.

You can see how it's implemented in https://github.com/gatsbyjs/gatsby/blob/69ee9e32220b44d6dd52d316a7a9218ae727100d/packages/gatsby-source-filesystem/src/extend-file-node.js#L16-L37

If you want the path to stay as-is, you will need to use `static` directory, so it copy file "as-is" without using any content hashes.

**Comment by kuworking** [comment]
This is indeed problematic, for instance in facebook where they are now not allowing you to modify the link to the main post image

If you cannot prevent this likely (at some point in the future) name change by gatsby, then the risk is very high that you will eventually end up losing all your FB post images

This kind of forces you to create redundant images to locate them in the `static` folder to make sure your FB page will keep its integrity over time 

My point is, it'd be great to have the possibility to indicate a fixed public path for these images
