### ISSUE TITLE
GraphQL last modifed/updated 

### ISSUE THREAD

**Issue by Sondro** [gatsbyjs/gatsby#23659]
Hi, I can do something like this in JS or PHP, but my excerpts and other data will appear blank:
``` JavaScript
 input = input.replace(/id="updated">/gi, `id="updated">${format(new Date(document.lastModified), 'MMM.DD.YYYY')}`);

```

Maybe I shouldn't GraphQL post since this is stored in the file and should just extract and parse per item query. 

Anyways, can't find the syntax on this for GraphQL and any help would be appreciated.

Thanks

**Comment by TylerBarnes** [comment]
Hi @Sondro can you share more info about what you're trying to achieve? It's hard to know what to recommend without more context. Sharing a repo where we can see this code is helpful. Thanks! :)

**Comment by Sondro** [comment]
Well at this point I'm just using Markdown without a  DB for my blog. I already have a **date** field that I can query and manually place (which I don't mind). But I like to be able to update the blog entries with a **last updated date**. For this I am thinking of making a new **updated** field and using GraphQL maybe to check and post to it like in REST.

However, maybe I don't even need to store this and can just query and extract the date modified each time from the server or .md docs?

Looking at this reference, but I'm not seeing anything about querying date or document modified: https://www.gatsbyjs.org/docs/recipes/querying-data/

**Comment by LekoArts** [comment]
Thank you for opening this!

When you have local markdown files or get markdown from your server (with the `mediaType: 'text/markdown'`) and have the remark transformer and all installed, your `markdownRemark` queries have the `File` type as a parent. The `File` type has these information stored for you. In [this GraphQL example](https://711808k40x.sse.codesandbox.io/___graphql?query=%7B%0A%20%20books%3A%20allMarkdownRemark(filter%3A%20%7Bfrontmatter%3A%20%7Btitle%3A%20%7Bne%3A%20%22%22%7D%7D%7D)%20%7B%0A%20%20%20%20totalCount%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20frontmatter%20%7B%0A%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20parent%20%7B%0A%20%20%20%20%20%20%20%20%20%20...%20on%20File%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20modifiedTime%0A%20%20%20%20%20%20%20%20%20%20%20%20birthTime%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) a list of markdown files is queried and as you can see you have access to e.g. `modifiedTime`. This will give you the information you want.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by interglobalmedia** [comment]
Hi LekoArts,

I was trying to add this as well, but the GraphQL example link you provided here is broken. Thanks!

**Comment by LekoArts** [comment]
@interglobalmedia I updated the link
