### ISSUE TITLE
Gatsby Serve not picking up styling?

### ISSUE THREAD

**Issue by mhyrr** [gatsbyjs/gatsby#2366]
Building a very simple Gatsby site based on the starter.. 'gatsby develop' seems to pick up the styling properly and serve what's expected, whereas 'gatsby build/serve' defaults the styling back to defaults, or doesn't pick them up.  

Very new to this ecosystem, so what am I missing?

Repo: https://github.com/mhyrr/testStyles
Run gatsby develop and the background color is gray and fontSize is appropriately set to 128px from typography.js
Build and gatsby server and those changes don't seem to be there.

Thanks!

**Comment by KyleAMathews** [comment]
Have you checked out the styled-components example site? https://github.com/gatsbyjs/gatsby/tree/master/examples/using-styled-components

See if you can reproduce your problem there.

**Comment by arlair** [comment]
Similar issue [here](https://stackoverflow.com/questions/46696753/gatsby-styles-are-not-working-in-production-build/).

Perhaps check if you have an `extract-text-webpack-plugin` compatible with Webpack 1 in `node_modules` and try add `extract-text-webpack-plugin@^1.0.1.` to `packages.json`

**Comment by jonathan-chin** [comment]
I'm getting a similar problem. Issue here: https://github.com/gatsbyjs/gatsby/issues/3360
