### ISSUE TITLE
Missing spec createTypes on Gatsby API > Actions page

### ISSUE THREAD

**Issue by czterystaczwarty** [gatsbyjs/gatsby#23668]
## Summary

Section "Fixing field types" in "Customizing the GraphQL Schema" article has link to `createTypes` action, but the spec is missing there.
url: https://www.gatsbyjs.org/docs/actions/#createTypes is incorrect.

### Motivation

There are no `createTypes` in Docs.

**Comment by marcysutton** [comment]
Thanks for the issue, @czterystaczwarty! There are some improvements coming to the Schema Customization docs, and this could be corrected at that time. I've filed it internally to be picked up as part of that workflow, so stay tuned for improvements. I'll leave this issue open until then.

**Comment by pieh** [comment]
It seems like all actions defined in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/actions/restricted.ts are not shown. This was probably result of our typescript migration and fact that [`actions.md`](https://github.com/gatsbyjs/gatsby/blob/8897e4c5f55ed5a504d19ca4fc351df09a1c9aa0/docs/docs/actions.md) file reference `.js` version of the file (it was missed during conversion) - so I hope adjusting frontmatter to use `.ts` extension for `restricted` actions will fix it

**Comment by pieh** [comment]
I'll create pull request to test it out shortly

**Comment by pieh** [comment]
Yeah, updating file I mentioned above fixes it - so until the PR is merged and deployed you can temporarily use https://build-006d12bc-19e7-4d17-8d08-0bfef95dd7db.gtsb.io/docs/actions/#createTypes for those missing actions documentation
