### ISSUE TITLE
maintenance(docs): Add remark-lint-heading-increment

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#23660]
## Summary

Enable the [`heading-increment`](https://github.com/remarkjs/remark-lint/tree/master/packages/remark-lint-heading-increment) rule to our remark-lint config.

Followup of #21919 

## Motivation

[Headings should only increase 1 level at a time](https://www.w3.org/WAI/tutorials/page-structure/headings/#heading-ranks) for accessibility.

## Steps

1. Delete the [line in `.remarkrc.js`](https://github.com/gatsbyjs/gatsby/blob/master/.remarkrc.js#L16) disabling this configuration.
2. Run `yarn lint:docs`
3. Fix the lint errors

**Comment by flavianunes** [comment]
Hey there, can I do this?

**Comment by flavianunes** [comment]
> Hey there, can I do this?

Oh, sorry, saw someone already did it.

**Comment by gabesharpton** [comment]
I would like to work on this.

**Comment by ahmad3700** [comment]
اود العمل على مشروع اقتصادي يخص الأدخار ودور التحفيز على بناء ثقافة الأدخار
