### ISSUE TITLE
maintenance(docs): Prevent use of h1s in markdown

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#23662]
## Description

Add the rule [`remark-lint-first-heading-level`](https://github.com/remarkjs/remark-lint/tree/master/packages/remark-lint-first-heading-level) and prevent the use of h1s in markdown.

## Motivation

A page should only one `<h1>` tag. In Gatsby, this is the `title` of the document in the frontmatter, so it is incorrect formatting to include another in the body of the document.

## Steps

1. `yarn add remark-lint-first-heading-level`
2. Add the line `["remark-lint-first-heading-level", 2]` to our `.remarkrc`
3. Run `yarn lint:docs` and fix the errors

## Related Issues

#23660 is another issue regarding remark lint headings and may need to be worked on in concert with this one.

**Comment by guilhermedeandrade** [comment]
Hey there! I'd be glad to help with this!

**Comment by tesseralis** [comment]
@guilhermedeandrade sure! thanks for the help.

**Comment by guilhermedeandrade** [comment]
@tesseralis you're welcome! I got a question about situations like this one here:

```
#### Pros

- Free
- No ads
- No third party scripts injected into your site
- Complete control over functionality and design
- Can be as simple or complicated as you want
- Little to no spam because spambots aren't set up to spam your custom content
- Easy to migrate - it all exists in one Heroku + Postgres server

#### Cons

- More work to set up
- Less features
- Need to set up manual anti-spam measures and moderation
```

Even though the lint error will go away just by changing `#### Pros` to `## Pros`, it feels strange because there is the "Cons" section right after which would be a h4. What should we do in those cases?

**Comment by guilhermedeandrade** [comment]
Another similar example from `docs/docs/recipes/gitlab-continuous-integration.md`:

```
### Prerequisites

- Make sure you have the [Gatsby CLI](/docs/gatsby-cli) installed
- A [Gitlab](https://gitlab.com/) account

### Directions

1. Create a gatsby site
[...]
```

**Comment by tesseralis** [comment]
@guilhermedeandrade Both of the headings should be changed. In general, if one heading is changed, *all* the headings of the same level should change as well.

**Comment by guilhermedeandrade** [comment]
Ok, thanks for the info! I will double check the files I have changed

**Comment by guilhermedeandrade** [comment]
@tesseralis I adjusted the files considering your last comment and here is the PR: https://github.com/gatsbyjs/gatsby/pull/23664
