### ISSUE TITLE
Any equivalent to "onPostExtractQueries" or "onExtractQueries"??

### ISSUE THREAD

**Issue by kmcaloon** [gatsbyjs/gatsby#23679]
I'm pretty sure this is a feature request since there doesn't seem to be a way to do this yet using the built-in  Lifecycle APIs. With regards to query extraction, are we only able to hook into `preExtractQueries` during the bootstrap phase? I am looking to see if I can run some functionality _**whenever**_ Gatsby extracts queries from components -- including when files are changed during development. Is this possible, and if not is it a viable feature request?

**Comment by LekoArts** [comment]
Can you please expand on why you need those APIs, possibly with longer examples of your usecase? We're not keen on adding more APIs as our API surface is quite big already.

**Comment by kmcaloon** [comment]
@LekoArts understood. My use case is very specific and I am wondering if there is another way of doing it.

Long story short, I am experimenting with seeing if I can put together a plugin that implements [groq](https://www.sanity.io/docs/groq) in place of GraphQL while trying to stay as close with Gatsby's query patterns as I can.

For example, I am using a `groqQuery` export on page files to mimic Gatsby's page queries, and `useGroqQuery` within components to mimic `useStaticQuery`, and traversing the files somewhat similar to how Gatsby extracts GraphQL queries during initial bootstrap and subsequent changes. Everything is actually working very well for builds, but things are a little tricky when trying to provide real-time updates during development.

If you are interested I can provide some examples of the code, but overall I would like to detect when a component changes, then update the "static groq"  and all "page groq" queries related to that component. I am doing this imperfectly with static queries by just using `fs.watch()` to detect changes and update the static query results, but it gets tricker with page queries as I need access to the context.

I was interested in seeing how `setPageData` might help with my setup, but after a quick glance I wasn't quite sure how it works.

Anyway I don't want to bog you down with code/questions as this is an extremely unique use-case, I just thought that in general it might be helpful if we had a simple way to hook into whenever an update is run during development (i.e. change in source data or code) .
