### ISSUE TITLE
[Bug] gatsby-browser cannot resolve regenerator-runtime package in yarn 2

### ISSUE THREAD

**Issue by sashkashishka** [gatsbyjs/gatsby#23676]
## Description

When adding to gatsby-browser.js file `onClientEntry` API to add IntersectionObserver polyfill just like that (with async/await syntax):
```js
export const onClientEntry = async () => {
  if (typeof IntersectionObserver === `undefined`) {
    await import(`intersection-observer`);
  }
}
```
 it causes a resolve error in yarn 2:
```bash
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Your application tried to access regenerator-runtime, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: regenerator-runtime (via "regenerator-runtime/runtime")
Required by: /$HOME/my-default-starter/gatsby-browser.js


File: gatsby-browser.js
```
But when you using Promise based syntax - everything is okay:
```js
export const onClientEntry = () => {
  if (typeof IntersectionObserver === 'undefined') {
    return import('intersection-observer');
  }

  return Promise.resolve();
};
```

As yarn 2 documentation [says](https://yarnpkg.com/advanced/migration#a-package-is-trying-to-access-another-package-) - it happens when you importing some dependency that is not declared in `package.json` file.

### Steps to reproduce

[Reproduce repo](https://github.com/sashkashishka/gatsby-browser-yarn-2-error)

1. Install dependencies
2. Run `yarn develop`

### Expected result

Yarn 2 should find needed package and then gatsby-browser will be successfully transpiled in es5 syntax.

### Actual result

Yarn 2 cannot resolve `regenerator-runtime` package and development build fails.

### Environment

```bash
  System:
    OS: Linux 4.19 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 2.0.0-rc.33 - ~/.yarn/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Languages:
    Python: 3.8.2 - /usr/bin/python
  Browsers:
    Firefox: 75.0
```

**Comment by chrisands** [comment]
Have same issue using `yarn v2` and `react-hook-form@5.7.2`. 
Workaround is to install `regenerator-runtime` as direct dependency.

**Comment by wardpeet** [comment]
Should be fixed in v3 & v4 where we have yarn 2-3 support
