### ISSUE TITLE
docs: No return statements and incorrect parenthesis

### ISSUE THREAD

**Issue by ahhda** [gatsbyjs/gatsby#23687]
## Summary

Changes in #23600 have caused syntax issues in some of the tutorial docs. This is because the arrow functions were changed to named components but the parenthesis were not changed to curly braces and return statements were not added.

`(<args>) => (<body>)` was replaced with `function Component(<args>) (<body>)` instead it should have been replaced with `function Component(<args>) { return <body>; }`.

Example: https://github.com/gatsbyjs/gatsby/pull/23600/files#diff-fe8bc44a6ee934d34f2666b686be60b1R27

<details>
<summary>Recording:</summary>

![edited](https://user-images.githubusercontent.com/7795956/80844048-5ec60080-8c23-11ea-8811-fa78a132fb13.gif)

</details>

### Motivation

This needs to be resolved soon, otherwise people who have just started out might face a lot of issues moving forward with the docs.

## Steps to resolve this issue

Change all occurrences of the format `function Component(<args>) (<body>)` to `function Component(<args>) { return <body>; }`.

**Comment by marcysutton** [comment]
Thanks so much for filing the issue, @ahhda. That is definitely something that needs to be fixed ASAP. 

cc'ing @Ekwuno who reviewed the PR, for visibility.

**Comment by victoriadouglas** [comment]
I am that fabled beginner who has been struggling to figure out why my build was failing on literally the first change of the tutorial. I've been beating my head against it for a day and a half, trying to figure out why the code was structured that way. 

On the plus side, all that troubleshooting has taught me a LOT more about es6, naming components, and default exports. 

But thanks for finding it and fixing it so quickly. I just picked a laughably poor time to follow the tutorial so strictly.

**Comment by Brian-Pho** [comment]
I'm also a victim of this issue. Also, if you're updating the code example, please update the gifs on the tutorial page to have the same code.

**Comment by eightbit** [comment]
This page needs to be updated: https://www.gatsbyjs.org/tutorial/part-three/
