### ISSUE TITLE
Gatsby seems to be using yarn but has a lot of "npm run" in the package.json

### ISSUE THREAD

**Issue by bcye** [gatsbyjs/gatsby#23686]
## Summary
There are a lot of yarn files in the repository, but all `package.json` have script that call other scripts via `npm run ...`. Shouldn't these be replaced by `yarn ...`?

### Basic example
The repository has a `yarn.lock` and not `package-lock.json`, the www README says one should run `yarn install`. Still, the root `package.json` has a script like `"format:other": "npm run prettier -- --write",`.

### Motivation
This can avoid confusion over which package manager is preffered to use and avoid bugs that are coming from npm.

**Comment by bcye** [comment]
Can't edit the labels.

**Comment by LekoArts** [comment]
Thank you for opening this!

`npm run <script-name>` and `yarn <script-name>` are the same so it doesn't matter what it says. There won't be any bugs with using `npm run` in your scripts section :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by bcye** [comment]
This wasn't really a question, but more of an idea for improving the docs.

I thought that it might be better to either use yarn or npm in all examples, currently it seems like sometimes yarn and sometimes npm is used.
