### ISSUE TITLE
Please patch - babel-plugin-styled-components

### ISSUE THREAD

**Issue by bvandermeersch** [gatsbyjs/gatsby#23682]
Testing /builds/xxx/www/gatsby...
506 Tested 2358 dependencies for known issues, found 1 issue, 6011 vulnerable paths.
507 Patchable issues:
508   Patch available for lodash@4.17.15
509   ✗ Prototype Pollution (new) [Medium Severity][https://snyk.io/vuln/SNYK-JS-LODASH-567746] in lodash@4.17.15
510     introduced by babel-plugin-styled-components@1.10.7 > lodash@4.17.15 and 6010 other path(s)

Security patch avaliable for loadash
https://snyk.io/vuln/SNYK-JS-LODASH-567746

**Comment by LekoArts** [comment]
Thank you for opening this!

We don't maintain this package here, you can open an issue on their repository :)
https://github.com/styled-components/babel-plugin-styled-components

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
