### ISSUE TITLE
Subdomains missing for some of the examples

### ISSUE THREAD

**Issue by reviewher** [gatsbyjs/gatsby#2368]
Some of the `using-*` examples have configured subdomains e.g. [`using-css-modules`](https://using-css-modules.gatsbyjs.org/) but others are missing:

- using-csv
- using-excel
- using-javascript-transforms
- using-page-loading-indicator
- using-path-prefix
- using-redux

**Comment by KyleAMathews** [comment]
Hey, closing out old issues. Please re-open if you have additional questions, thanks!
