### ISSUE TITLE
Gatsby image not pulling give 6:18  error  React Hook "useStaticQuery" is called in function "section2" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks

### ISSUE THREAD

**Issue by theboyonline** [gatsbyjs/gatsby#23683]
## Description

I'm trying to put up a image on a section 

https://github.com/theboyonline/gatsbynewsite/blob/master/src/components/section2.js

gives 

`6:18  error  React Hook "useStaticQuery" is called in function "section2" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks`

```
import React from "react"
import { useStaticQuery, graphql } from "gatsby"
import Img from "gatsby-image"

const section2 = () => {
    const data = useStaticQuery(graphql`
    query {
      placeholderImage: file(relativePath: { eq: "gatsby-astronaut.png" }) {
        childImageSharp {
          fluid(maxWidth: 300) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
`)

return (
<div className="section2">
    <div className="container">
        <div classname="row">
            <h1 classname="covertitle">Hello I'm Gatsby, I load things faster;<br></br>
                I can behave like a Human.
            </h1>
            <div className="secimg">
                <div className="col">
                <Img fluid={data.placeholderImage.childImageSharp.fluid} />
                </div>
            </div>
        </div>
    </div>
</div>
)
}

export default section2
```

### Steps to reproduce

creating a new gatsby section with image.

### Expected result

Image should appear on page.

### Actual result

6:18  error  React Hook "useStaticQuery" is called in function "section2" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.17.4 => 2.21.1 
    gatsby-image: ^2.2.29 => 2.4.0 
    gatsby-plugin-manifest: ^2.2.23 => 2.4.1 
    gatsby-plugin-offline: ^3.0.16 => 3.2.0 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.3.0 
    gatsby-plugin-sass: ^2.1.20 => 2.3.0 
    gatsby-plugin-sharp: ^2.2.32 => 2.6.0 
    gatsby-source-filesystem: ^2.1.33 => 2.3.0 
    gatsby-transformer-sharp: ^2.3.0 => 2.5.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.5

**Comment by TylerBarnes** [comment]
Hi @theboyonline! the reason for this is that React components are required to be named in PascalCase, otherwise they're not considered proper React components.

If you name your component as `Section2`, it will work :)
