### ISSUE TITLE
Gatsby ^2.20.12 auth0-js ^9.13.2

### ISSUE THREAD

**Issue by atmollohan** [gatsbyjs/gatsby#23681]
## Description

Hello gatsby community, this is my first time here so go easy on me. I have been using gatsby to build a blog and wanted to implement authentication so that the user could have a profile and other various protected routes. 
I followed the gatsby authentication tutorial: https://www.gatsbyjs.org/tutorial/authentication-tutorial/
This method worked for both development and production modes. When I went on to implement auth0 authentication I followed the guide at: https://auth0.com/blog/securing-gatsby-with-auth0/

I was able to implement authentication into my local instance but as soon as I tried to run 'npm run build' I started getting this error:

WebpackError: TypeError: auth0_js__WEBPACK_IMPORTED_MODULE_0___default.a.WebAu  th is not a constructor
  
  - auth.js:11 Module../src/services/auth.js
    src/services/auth.js:11:7
  
  - header.js:1 Module../src/components/header.js
    src/components/header.js:1:1
  
  - about.js:1 Module../src/pages/about.js

I wasn't really sure where to turn for this. I made sure to add a custom web pack rule in 'gatsby-node.js' so that it wouldn't break the build but then it broke the build anyways. I also added a isBrowser boolean in the /services/auth to make sure auth0-js was being used in the correct place.

Im not sure if this has to do with my components and pages using the auth functions and the build is getting crossed up.

Any thoughts here?

Here is a link to the repo: https://github.com/L-Town-FC/we-roast

### Steps to reproduce

git clone https://github.com/L-Town-FC/we-roast.git
cd we-roast
npm i
npm run build

### Expected result

App should build into public folder at root

### Actual result

Build crashes with error about webpack:

WebpackError: TypeError: auth0_js__WEBPACK_IMPORTED_MODULE_0___default.a.WebAu  th is not a constructor
  
  - auth.js:11 Module../src/services/auth.js
    src/services/auth.js:11:7
  
  - header.js:1 Module../src/components/header.js
    src/components/header.js:1:1
  
  - about.js:1 Module../src/pages/about.js

### Environment

System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 3.7.7 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
  npmPackages:
    gatsby: ^2.20.12 => 2.21.7
    gatsby-image: ^2.3.2 => 2.4.0
    gatsby-plugin-antd: ^2.2.0 => 2.2.0
    gatsby-plugin-manifest: ^2.3.7 => 2.4.1
    gatsby-plugin-offline: ^3.1.5 => 3.2.0
    gatsby-plugin-react-helmet: ^3.2.1 => 3.3.0
    gatsby-plugin-sharp: ^2.5.3 => 2.6.0
    gatsby-plugin-typography: ^2.4.3 => 2.5.0
    gatsby-source-filesystem: ^2.2.2 => 2.3.0
    gatsby-transformer-remark: ^2.7.4 => 2.8.3
    gatsby-transformer-sharp: ^2.4.3 => 2.5.0
  npmGlobalPackages:
    gatsby-cli: 2.11.15

**Comment by TylerBarnes** [comment]
Hi @atmollohan , you're so close!

in this code:
```js

export const isBrowser = () => typeof window !== "undefined"

// this fails on build
const auth = isBrowser
    ? new auth0.WebAuth({
          domain: process.env.AUTH0_DOMAIN,
          clientID: process.env.AUTH0_CLIENTID,
          redirectUri: process.env.AUTH0_CALLBACK,
          responseType: "token id_token",
          scope: "openid profile email",
      })
    : {}
```

You're asking, is the isBrowser function defined? If it is then use my auth package.

What you want to ask is, is the window undefined?

Like so:

```js

export const isBrowser = () => typeof window !== "undefined"

// this fails on build
const auth = isBrowser()
    ? new auth0.WebAuth({
          domain: process.env.AUTH0_DOMAIN,
          clientID: process.env.AUTH0_CLIENTID,
          redirectUri: process.env.AUTH0_CALLBACK,
          responseType: "token id_token",
          scope: "openid profile email",
      })
    : {}
```

This moves the build forward onto a few more errors with the same cause. You need to call the `isBrowser` function through the whole file instead of checking if the function exists :) then your build works! 🚀

**Comment by atmollohan** [comment]
@TylerBarnes , I cant believe I spent 3 hours last night thinking that I had something set up wrong in my components and pages. You're a lifesaver! Are you one of the main contributors to gatsby? Im about two weeks 3 weeks into my first gatsby site.

**Comment by TylerBarnes** [comment]
@atmollohan glad I could help :) I am a core member! Hope you're enjoying building your first site. Let us know if you run into any other issues.

**Comment by atmollohan** [comment]
@TylerBarnes Thats great to know! Are there any good places to post gatsby related questions? For instance I am currently working on making my sites navigation and layout look and feel better but I wasn't sure if it was better to build and style my own components or use UI libraries such as antd. I also wasnt sure if it was better to wrap my whole app in a class based component or to make every page use the same layout and header components. I really want a slick looking slight but I want to make sure Im not following any anti patterns in react.

**Comment by TylerBarnes** [comment]
@atmollohan there are a bunch of great places for it actually 😄 

https://www.gatsbyjs.org/contributing/community/#where-to-get-support

I would recommend the discord as one of our core team members @LekoArts manages it.
