### ISSUE TITLE
Suggestion: Creating A Dedicated Animation For Website Partner Section

### ISSUE THREAD

**Issue by MichaelGrigoryan25** [gatsbyjs/gatsby#23699]
## Summary

Let's add automatic animation to scroll through the "partners" section, instead of having the user to scroll it.
![image](https://user-images.githubusercontent.com/56165400/80864185-1eea3200-8c92-11ea-959e-0a185636e8f9.png)

### Basic example

Change or add CSS values to the website.

### Motivation

Much frendlier User Interface and improved first impression

**Comment by LekoArts** [comment]
Thank you for opening this!

The homepage will undergo a design refresh in the future so at this stage it's not necessary to make bigger changes. Thanks for the suggestion though!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
