### ISSUE TITLE
Themes: Shadowing algorithm for page templates doesn't allow other extensions

### ISSUE THREAD

**Issue by LekoArts** [gatsbyjs/gatsby#23697]
## Description

The PR https://github.com/gatsbyjs/gatsby/pull/17681 added the ability to shadow queries that e.g. are used in createPage calls. But this [comment](https://github.com/gatsbyjs/gatsby/pull/17681#issuecomment-588442955) (and I was able to reproduce it) showed a flaw:

> I hit an edge case. Create a site from `@lekoarts/gatsby-theme-minimal-blog` and attempt to shadow the `template/homepage-query.tsx` with a local `src/@lekoarts/gatsby-theme-minimal-blog-core/templates/homepage-query.js`. It won't shadow over the in-theme file. Rename it with the same extension...it works.

> the documents for `createPage` tells you to use an absolute path to the component. So, the theme author didn't do anything wrong. (per docs) The component will always have an extension, so the algorithm resolving the shadowed component will not allow extension overriding. :(

It also shows a false warning:

```shell
warn The GraphQL query in the non-page component "/mnt/c/Users/Lennart/Development/Playground/minimal-blog-additional-field/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/src/templates/page-query.tsx" will Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.
```

### Steps to reproduce

Clone https://github.com/LekoArts/minimal-blog-additional-field and change the file extensions of the shadowed files to `.jsx`. On `localhost:8000/about` you shouldn't see the the `subtitle` line.

### Expected result

Users should be able to use .js, .jsx or .tsx

### Actual result

Users need to use .tsx

### Environment

```
  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
  npmPackages:
    gatsby: ^2.20.36 => 2.21.9
    gatsby-plugin-google-analytics: ^2.1.4 => 2.3.0
    gatsby-plugin-manifest: ^2.2.3 => 2.4.1
    gatsby-plugin-netlify: ^2.1.3 => 2.3.0
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-sitemap: ^2.2.19 => 2.4.1
  npmGlobalPackages:
    gatsby-cli: 2.12.1
    gatsby-dev-cli: 2.7.0
```

**Comment by LekoArts** [comment]
cc @laurieontech @jxnblk @johno

**Comment by LekoArts** [comment]
cc @laurieontech @jxnblk @johno

**Comment by laurieontech** [comment]
Thanks @LekoArts. We have a sense of how to fix this and have put it on our list to address. Apologies for the delay in response.
