### ISSUE TITLE
Nit: gatsby-plugin-manifest is using underscores instead of camelcase config

### ISSUE THREAD

**Issue by bsgreenb** [gatsbyjs/gatsby#23707]
I believe this is an issue for both [javascript](https://eslint.org/docs/rules/camelcase) eslint and typescript.  My setup is typescript and I have to disable the rule in [gatsby-config.ts](https://gist.github.com/JohnAlbin/2fc05966624dffb20f4b06b4305280f9): 
```
export const plugins = [
  `gatsby-plugin-typescript`,
  /* eslint-disable @typescript-eslint/camelcase */
  {
    resolve: `gatsby-plugin-manifest`,
    options: {
      name: `GlowyStuff`,
      short_name: `GlowyStuff`,
      start_url: `/`,
      background_color: `#ffffff`,
      theme_color: `#663399`, // TODO: set theme color
      display: `minimal-ui`,
      icon: `./static/favicon.png`,
    },
  },
  /* eslint-enable @typescript-eslint/camelcase */
```

**Comment by LekoArts** [comment]
Thank you for opening this!

Unfortunately this isn't something we'll change unless we decide to enforce a certain naming convention around plugin options or make a breaking change to the plugin. So for now we'll keep it as-is.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by bsgreenb** [comment]
Why isn't there a naming convention around plugin params?  This breaks typical eslint setup and is a plugin created by Gatsby originally
