### ISSUE TITLE
Stuck on Webpack and parsing error when following the Gatsby Tutorial

### ISSUE THREAD

**Issue by erm87** [gatsbyjs/gatsby#23712]
## Summary
I'm following the Gatsby tutorial, however, I'm stuck on early in Chapter 1  — specifically:
https://www.gatsbyjs.org/tutorial/part-one/#-make-changes-to-the-hello-world-homepage

On step 2., I'm supposed to replace the initial "Hello world!" div with this function:
```
import React from "react"

export default function Home() (
  <div style={{ color: `purple`, fontSize: `72px` }}>Hello Gatsby!</div>
)
```

However, I receive this error on re-build in develop:
![Screen Shot 2020-05-02 at 10 23 38 PM](https://user-images.githubusercontent.com/23239478/80897129-9edcc000-8cc3-11ea-9285-d393e1fa901c.png)

Similarly, my terminal displays:
![Screen Shot 2020-05-02 at 10 24 55 PM](https://user-images.githubusercontent.com/23239478/80897143-c5026000-8cc3-11ea-96da-3bc2b128a5ba.png)

I thought I could just skip this part but unfortunately, I get the same issue later in the same chapter 😕. I've spent a few hours so far trying to find a solution but have not had any luck.

## Relevant information

Doing some searching, I found #17557 which seemed related but unfortunately, none of the suggested solutions in that thread has helped my situation.

I've attempted:
- Deleting yarn.lock and running yarn
- Deleting yarn.lock, .cache, node_modules and running npm install
- Changing to various version of node
- Creating a .eslintrc.json config file to specify a parser option (idea from [here](https://github.com/babel/babel-eslint/issues/312))
- Deleting the project and reinstalling several times
- gatsby clean

I followed the tutorial exactly so far and hit the same issue on every fresh attempt at a run-through.

### Environment (if relevant)

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.20.1 - ~/.nvm/versions/node/v10.20.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 67.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.21.0 => 2.21.0 

### File contents (if changed)

`gatsby-config.js`: 
```/**
 * Configure your Gatsby site with this file.
 *
 * See: https://www.gatsbyjs.org/docs/gatsby-config/
 */

module.exports = {
  /* Your site config here */
  plugins: [],
}
```
`package.json`:
```{
  "name": "gatsby-starter-hello-world",
  "private": true,
  "description": "A simplified bare-bones starter for Gatsby",
  "version": "0.1.0",
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "dependencies": {
    "gatsby": "^2.21.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  },
  "devDependencies": {
    "prettier": "2.0.5"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-hello-world"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
```
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by robertwt7** [comment]
For quick fix try

```
export default function Home() {
 return (
    <div style={{ color: `purple`, fontSize: `72px` }}>Hello Gatsby!</div>
 )
}
```

**Comment by erm87** [comment]
Thanks so much @robertwt7 !!
