### ISSUE TITLE
Error: pngquant failed to build, make sure that libpng-dev is installed

### ISSUE THREAD

**Issue by baliyan9887** [gatsbyjs/gatsby#23725]
Hi Gatsby team,
I'm stuck to create a new app using gatsby-cli.  I've installed windows build tools according to the gatsby [docs]( https://www.gatsbyjs.org/docs/gatsby-on-windows/). but it does not work for me 

Error: -

> pngquant-bin@5.0.2 postinstall E:\worked\appp\node_modules\pngquant-bin
> node lib/install.js

  ‼ spawn UNKNOWN
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (E:\worked\appp\node_modules\bin-build\node_modules\execa\index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.5 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@5.0.2 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@5.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gauta\AppData\Roaming\npm-cache\_logs\2020-05-04T05_39_57_172Z-debug.log

Please help me out with this issue.

**Comment by LekoArts** [comment]
Thank you for opening this!

The error means that you didn't correctly install the necessary build tools. Please make sure to follow the guide exactly. Other issues before like https://github.com/gatsbyjs/gatsby/issues/10792, https://github.com/gatsbyjs/gatsby/issues/23210, https://github.com/gatsbyjs/gatsby/issues/20623 have shown that it's resolvable with the solutions mentioned there. Please let us know what you have tried. I'll close this as it's an issue with your local environment and not an issue with Gatsby itself.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by baliyan9887** [comment]
I've tried all given method 
Please let what I do. I'm sharing my npm config there is some error please let me know how to handle these errors.
 
E:\worked>npm ls -g --depth=0
C:\Users\Gauta\AppData\Roaming\npm
+-- @types/react@16.9.34
+-- acorn@6.0.0
+-- babel-eslint@10.1.0
+-- create-react-app@3.4.1
+-- eslint@6.8.0
+-- gatsby-cli@2.12.8
+-- ink@2.7.1
+-- npm@6.14.4
+-- npx@10.2.2
+-- react@16.13.1
+-- rimraf@3.0.2
+-- webpack@4.43.0
`-- windows-build-tools@5.2.2

npm ERR! error in C:\Users\Gauta\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\fsevents: ENOENT: no such file or directory, open 'C:\Users\Gauta\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\fsevents\package.json'
npm ERR! peer dep missing: gatsby@^2.0.0, required by babel-plugin-remove-graphql-queries@2.9.0
npm ERR! peer dep missing: acorn@^6.0.0, required by acorn-dynamic-import@4.0.0
npm ERR! error in C:\Users\Gauta\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents: ENOENT: no such file or directory, open 'C:\Users\Gauta\AppData\Roaming\npm\node_modules\webpack\node_modules\fsevents\package.json'

I've also tried manually to install dependencies
but doesn't work for me

**Comment by baliyan9887** [comment]
> Thank you for opening this!
> 
> The error means that you didn't correctly install the necessary build tools. Please make sure to follow the guide exactly. Other issues before like #10792, #23210, #20623 have shown that it's resolvable with the solutions mentioned there. Please let us know what you have tried. I'll close this as it's an issue with your local environment and not an issue with Gatsby itself.
> 
> We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

I've shared my npm config please let know what's wrong with it

**Comment by fahadprod** [comment]
**I also have the same issue** 

$ npm install gatsby-plugin-image gatsby-plugin-sharp gatsby-source-filesystem gatsby-transformer-sharp

> mozjpeg@7.1.0 postinstall D:\BlankSlate Work\Prep React, Next and Micro\Gatsby\recipes-project\node_modules\mozjpeg
> node lib/install.js

  √ mozjpeg pre-build test passed successfully

> pngquant-bin@6.0.0 postinstall D:\BlankSlate Work\Prep React, Next and Micro\Gatsby\recipes-project\node_modules\pngquant-bin
> node lib/install.js

  ‼ Command failed: D:\BlankSlate Work\Prep React, Next and Micro\Gatsby\recipes-project\node_modules\pngquant-bin\vendor\pngquant.exe --version


  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at D:\BlankSlate Work\Prep React, Next and Micro\Gatsby\recipes-project\node_modules\bin-build\node_modules\execa\index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
npm WARN eslint-config-react-app@6.0.0 requires a peer of babel-eslint@^10.0.0 but none is installed. You must install peer dependencies yourself.npm WARN ts-node@9.1.1 requires a peer of typescript@>=2.7 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@6.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@6.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2021-07-31T07_22_38_892Z-debug.log
