### ISSUE TITLE
Unnecessary import in PrivateRoute example

### ISSUE THREAD

**Issue by chrissantamaria** [gatsbyjs/gatsby#23721]
## Description

In the docs tutorial "Making a Site with User Authentication", there is a [section](https://www.gatsbyjs.org/tutorial/authentication-tutorial/#controlling-private-routes) displaying the usage of a custom `PrivateRoute` component:

https://github.com/gatsbyjs/gatsby/blob/075e2da3ed856486eafbd935195d72e6facbcd85/docs/tutorial/authentication-tutorial.md#L261-L276

From my understanding, it looks like the `Component` import from React is never used as the `component: Component` destructing in the `PrivateRoute` function has precedence. Looks like a leftover from when `PrivateRoute` was previously a class component.

I'm happy to open a PR to fix this assuming this is actually a typo.

**Comment by LekoArts** [comment]
Yeah, seems correct. Looking forward to your PR :)

**Comment by chrissantamaria** [comment]
Just opened #23751 :)
