### ISSUE TITLE
Search by using cached pages

### ISSUE THREAD

**Issue by janat08** [gatsbyjs/gatsby#23736]
## Summary
If user visited page products/abc, is there a way to link that page during query for products if offline.
## Relevant information
Ideally you could extract more than the fact that the cached page exists, but at least the page title would do.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by janat08** [comment]
Yes i'd like to open this issue open. The use case being offline usage, where user may wish to revisit one of the pages previously visited, with only route towards it being through search.

**Comment by marcysutton** [comment]
Hi there, interesting question. There are a few parts in play here:

- Keeping track of user visits, which in Gatsby will require client-side JavaScript and some kind of storage (localStorage, cookies, indexedDb)
- Offline and caching

The first item could be an example of personalization, for which there's an issue open but no official recommended solution: https://github.com/gatsbyjs/gatsby/issues/15537

You mention "querying" for products, which in Gatsby space signals a build-time query–which wouldn't really help at client runtime when a user is visiting the site. So I'm assuming you mean displaying products dynamically? Personalizing product pages would require looking at stored data from user navigation, and dynamically populating a widget based on that data using custom JavaScript code. I don't know of an off the shelf tool in Gatsby that would do such a thing, even before factoring in the offline aspect.

Caching also signifies a saved version of a page, and to my knowledge the only thing that updates the cache is connecting to the network and finding an update; it wouldn't update pages in the cache based on user data. But cc'ing @LekoArts and @wardpeet to gather their thoughts.

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll want to create a PWA:
https://www.gatsbyjs.org/docs/progressive-web-app/

By using `gatsby-plugin-offline` you'll create a Workbox service worker that can cache all your pages if you have set up the cache paths correctly.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
