### ISSUE TITLE
Integration with Passport.js

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#23737]
## Summary

Authentication is very frequently necessary for web apps, and [very easy to get wrong](https://hackernoon.com/your-node-js-authentication-tutorial-is-wrong-f1a3bf831a46). The leading open-source solution for authentication with Node.js seems to be Passport.js. It would be great if Gatsby had an authoritative, audited, tutorial (more in depth than #17437) on integrating with Passport.js.

### Motivation

3rd party providers likes Firebase and Auth0 come with their own set of problems. Firebase authentication is [several times slower than native](https://github.com/firebase/firebaseui-web/issues/511), and its bundle size is [very large](https://github.com/firebase/firebase-js-sdk/issues/332#issuecomment-423402372). [Auth0 is over-engineered](https://github.com/firebase/firebaseui-web/issues/665), the [integration with GraphQL](https://auth0.com/blog/build-and-secure-a-graphql-server-with-node-js/) is tedious, and it forces the user through an interstitial.

### Other thoughts

[No Passport.js plugins or themes](https://www.gatsbyjs.org/plugins/?=passport) can currently be found, which suggests that the problem is non-trivial.

**Comment by lalasmuathasim** [comment]
I was also looking for Gatsby user authentication using passport and eventually I reached here.

**Comment by marcysutton** [comment]
Can you expand on your use case for using Passport.js with Gatsby? Node is used at Build time to compile static pages that rehydrate with React on the client-side, so authentication is typically done with client-side routes. It would help to know more about what you're trying to accomplish to determine the best way forward. I've marked this issue as help wanted for now in case someone wants to take it on.

**Comment by bogdansoare** [comment]
Gatsby just gives you some static assets html, javascript and css, there is no server involved, if you want do authentication you would do it like in any other react app, gatsby doesn't care about how you implement your api.

**Comment by AdrianoCahete** [comment]
> Gatsby just gives you some static assets html, javascript and css, there is no server involved, if you want do authentication you would do it like in any other react app, gatsby doesn't care about how you implement your api.

Nuxt (vue) has the same idea and [they have a Github Auth plugin](https://auth.nuxtjs.org/providers/github). If you go with that path, Gatsby doesn't need any plugin. 🤷🏻‍♂️
