### ISSUE TITLE
On Page change layout component is getting unmounted 

### ISSUE THREAD

**Issue by asinha08** [gatsbyjs/gatsby#23748]
## Summary
I am using Gatsby Link (```import { Link } from "gatsby";```) to navigate from one page to another. When I do so, **Layout component is getting unmounted**

In ```gatsby-ssr.js``` I have following code
```
import React from "react";
import { StoreProvider } from "./src/context";

export const wrapRootElement = ({ element }) => (
	<StoreProvider>{element}</StoreProvider>
);
```

In ```gatsby-browser.js``` I have following code
```
import React from "react";
import { StoreProvider } from "./src/context";

export const wrapRootElement = ({ element }) => (
	<StoreProvider>{element}</StoreProvider>
);
```
My Store Provider looks like below
```
import React, { createContext } from "react";
import {appStore} from './applicationStore';

const initState = appStore();

export const Store = createContext();

export const StoreProvider = (props) => {
	const [state, dispatch] = React.useReducer(appStore, initState);
	const value = { state, dispatch };
	return (
		<Store.Provider value={value}>
			{props.children}
		</Store.Provider>
	);
};
```

### Environment (if relevant)
```
 System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.21.9 => 2.21.9
    gatsby-cli: ^2.12.7 => 2.12.7
    gatsby-image: ^2.4.0 => 2.4.0
    gatsby-plugin-manifest: ^2.4.1 => 2.4.1
    gatsby-plugin-offline: ^3.2.0 => 3.2.0
    gatsby-plugin-react-helmet: ^3.3.0 => 3.3.0
    gatsby-plugin-sass: ^2.3.0 => 2.3.0
    gatsby-plugin-sharp: ^2.6.0 => 2.6.0
    gatsby-plugin-sitemap: ^2.4.1 => 2.4.1
    gatsby-source-filesystem: ^2.3.0 => 2.3.0
    gatsby-transformer-sharp: ^2.5.0 => 2.5.0

```

### File contents (if changed)

`gatsby-config.js`: Yes 
`package.json`: Yes 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: Yes 
`gatsby-ssr.js`: Yes

**Comment by asinha08** [comment]
Any help..?

**Comment by danabrit** [comment]
Hi @asinha08 !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by danabrit** [comment]
Closing this issue due to no reproduction
