### ISSUE TITLE
Importing icons based on a contentful variable

### ISSUE THREAD

**Issue by yoppoy** [gatsbyjs/gatsby#23740]
## Summary
Hi, I'm using Contentful to load a data model that contains a string referencing an icon to display: I need to load/display each icon needed based on that variable.

## Relevant information
In order to import my icon, I was initially doing using a `require` like so. 
````
import React from 'react';
import Icon from "@iconify/react"; //icons: @iconify for react and @iconify/icons-simple-icons. 

export default function SimpleIcon({name, ...props}) {
    const icon = require('@iconify/icons-simple-icons/' + name + '.js').default;

    if (icon)
        return (<Icon icon={icon} {...props}/>);
    return null;
}
````
That worked, however my site performance dropped by 25% since it looks like it's bundling the 1300 icons from the icon pack. I am quite unfamiliar with customising webpack, is there a way along with gatsby to only import the necessary files based on the contentful queried data ?

Thanks for your time!

**Comment by LekoArts** [comment]
Thank you for opening this!

I'd recommend asking on their repository (https://github.com/iconify/iconify) on whether they support tree-shaking (this is mandatory) and/or how to enable it. Alternatively you could look into other libraries that definitely support that.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
