### ISSUE TITLE
Step Image Thumbnails Generation locally 

### ISSUE THREAD

**Issue by Canopix** [gatsbyjs/gatsby#23745]
## Summary

Sometimes when the user needs to clone a repo with many images or clear the cache, the dev server takes a long time to start.  Maybe give the user more control about this process make a better experience with Gatsby.

### Motivation
Give the user more control about the build process of Gatsby.

**Comment by LekoArts** [comment]
Thank you for opening this!

We're tracking this in this issue :)
https://github.com/gatsbyjs/gatsby/issues/10815

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
