### ISSUE TITLE
Validate that a URL doesn't return HTML

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#23768]
It is a pretty common error to try getting the non-raw link to an HTML page. So whenever the content type isn't mdx, we should display a pretty error.

We can also automatically convert github/gist URLs into their raw equivalent with e.g. this package

https://github.com/doowb/github-content

**Comment by guilhermedeandrade** [comment]
I'd like to work on this issue! Could you please provide more info, @KyleAMathews? I didn't understand what should be done exactly
