### ISSUE TITLE
Cannot build gatsby website

### ISSUE THREAD

**Issue by ilyaryabchinski** [gatsbyjs/gatsby#23763]
## Description

trying to build www package but getting errors.

### Steps to reproduce

- `git clone https://github.com/gatsbyjs/gatsby.git`
- `cd www`
- `npm install`
- add .env.development file with my github API key
- `npm start`

### Expected result

Gatsby website should be run on the dev server with `gatsby develop`

### Actual result
<img width="916" alt="Screen Shot 2020-05-04 at 22 28 35" src="https://user-images.githubusercontent.com/20639767/81010148-7806c100-8e5e-11ea-8371-dc8774c6c2fb.png">

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.0 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.21.11 => 2.21.11 
    gatsby-alias-imports: ^1.0.4 => 1.0.4 
    gatsby-core-utils: ^1.2.0 => 1.2.0 
    gatsby-design-tokens: ^2.0.5 => 2.0.5 
    gatsby-image: ^2.4.0 => 2.4.0 
    gatsby-plugin-canonical-urls: ^2.3.0 => 2.3.0 
    gatsby-plugin-catch-links: ^2.3.0 => 2.3.0 
    gatsby-plugin-emotion: ^4.3.0 => 4.3.0 
    gatsby-plugin-feed: ^2.5.0 => 2.5.0 
    gatsby-plugin-google-analytics: ^2.3.0 => 2.3.0 
    gatsby-plugin-google-tagmanager: ^2.3.0 => 2.3.0 
    gatsby-plugin-guess-js: ^1.3.0 => 1.3.0 
    gatsby-plugin-layout: ^1.3.0 => 1.3.0 
    gatsby-plugin-mailchimp: ^2.2.3 => 2.2.3 
    gatsby-plugin-manifest: ^2.4.1 => 2.4.1 
    gatsby-plugin-mdx: 1.2.5 => 1.2.5 
    gatsby-plugin-netlify: ^2.3.1 => 2.3.1 
    gatsby-plugin-netlify-cache: ^0.1.0 => 0.1.0 
    gatsby-plugin-nprogress: ^2.3.0 => 2.3.0 
    gatsby-plugin-offline: ^3.2.0 => 3.2.0 
    gatsby-plugin-react-helmet: ^3.3.0 => 3.3.0 
    gatsby-plugin-sharp: ^2.6.0 => 2.6.0 
    gatsby-plugin-sitemap: ^2.4.1 => 2.4.1 
    gatsby-plugin-theme-ui: ^0.3.0 => 0.3.0 
    gatsby-plugin-twitter: ^2.3.0 => 2.3.0 
    gatsby-plugin-typography: ^2.5.0 => 2.5.0 
    gatsby-remark-autolink-headers: ^2.3.0 => 2.3.0 
    gatsby-remark-code-titles: ^1.1.0 => 1.1.0 
    gatsby-remark-copy-linked-files: ^2.3.1 => 2.3.1 
    gatsby-remark-embedder: ^1.16.0 => 1.16.0 
    gatsby-remark-graphviz: ^1.3.0 => 1.3.0 
    gatsby-remark-http-to-https: ^1.0.2 => 1.0.2 
    gatsby-remark-images: ^3.3.0 => 3.3.0 
    gatsby-remark-normalize-paths: ^1.0.0 => 1.0.0 
    gatsby-remark-prismjs: ^3.5.0 => 3.5.0 
    gatsby-remark-responsive-iframe: ^2.4.1 => 2.4.1 
    gatsby-remark-smartypants: ^2.3.0 => 2.3.0 
    gatsby-source-airtable: ^2.1.1 => 2.1.1 
    gatsby-source-filesystem: ^2.3.0 => 2.3.0 
    gatsby-source-git: ^1.0.2 => 1.0.2 
    gatsby-source-npm-package-search: ^2.3.0 => 2.3.0 
    gatsby-transformer-csv: ^2.3.0 => 2.3.0 
    gatsby-transformer-documentationjs: ^4.3.0 => 4.3.0 
    gatsby-transformer-gitinfo: ^1.1.0 => 1.1.0 
    gatsby-transformer-remark: ^2.8.5 => 2.8.5 
    gatsby-transformer-screenshot: ^2.3.1 => 2.3.1 
    gatsby-transformer-sharp: ^2.5.0 => 2.5.0 
    gatsby-transformer-yaml: ^2.4.0 => 2.4.0

**Comment by coreyward** [comment]
Gatsby uses yarn, not npm. This is noted in the README of the “www” submodule.

**Comment by ilyaryabchinski** [comment]
tried to remove `node_modules` and install dependencies again using yarn, the issue persists

**Comment by wardpeet** [comment]
Could you try the following:
1. remove node_modules
2. remove yarn.lock
3. remove package-lock.json

**Comment by ilyaryabchinski** [comment]
Still get the exception thrown from yoga-layout-prebuilt package

**Comment by LekoArts** [comment]
It works for me pulling down the latest version of the `www` repo so please try again and follow the steps from wardpeet if necessary.

Closing this as solved.
