### ISSUE TITLE
[docs] Add documentation of how to creating prefixed 404 pages by createPages

### ISSUE THREAD

**Issue by thundermiracle** [gatsbyjs/gatsby#23776]
## Summary

I'm using `gatsby-plugin-i18n` to generate all pages dynamically with `createPages` API. When 404 error occurs, I'd like to redirect to the prefixed 404 pages for different languages. 
But after I ran into the [documentation](https://www.gatsbyjs.org/docs/creating-prefixed-404-pages-for-different-languages/), I found that there's only a sample of how to by using `onCreatePage` API.

### Motivation

Adding a sample of how to achieve the same goal by using `createPages` API is very kind for beginners implementing i18n by `gatsby-plugin-i18n`.

### Draft the doc

- [x] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [x] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [x] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by gillkyle** [comment]
I think the difference between Node API's isn't a huge focus of these pages but more samples of code certainly can't hurt. If there's a way we can describe solutions that are plugin agnostic that would be ideal, though in some cases using a plugin is ideal since it can simplify setup.

What exactly were your issues that didn't make this doc useful to you @thundermiracle? Was it being able to have the customized 404 pages for each language?

(note: I'm continuing this discussion from the PR in #23777)

**Comment by thundermiracle** [comment]
@gillkyle 
Thanks for all your time & comments.

>What exactly were your issues that didn't make this doc useful to you 

Creating pages for each language by `template`  which needs to use `createPages` API.
I don't want to create `404` by `onCreatePage` only but other pages by `creataPages` API. For me consistency is important and it's easier to understand.

And then, again, after running into the documentation, there's only a description that `how to do it by onCreatePage` which seems that if you want to make prefixed 404, you have to use onCreatePage.
But it's not true.

What I tried to add is just tell the readers, hey, you can create prefixed 404 pages by both `onCreatePage` and `createPages`. If you're got used to `createPages`, ok, you don't need `onCreatePage`.

Perhaps my English isn't good enough to explain this requirement well, and of course I think this is really a niche problem that is not important.
So I'm going to close this ticket. And thanks for all your time again.
