### ISSUE TITLE
[gatsby-image 1.0.7] Bug: Images doesn't show on Safari (but chrome OK)

### ISSUE THREAD

**Issue by roberpoldo** [gatsbyjs/gatsby#2378]
Just have updated to `gatsby-image 1.0.7`. it's working well in Chrome but in Safari the images aren't showing up. I'm using the sizes option:
```
              childImageSharp {
                sizes(maxWidth: 1200) {
                  ...GatsbyImageSharpSizes_noBase64
                }
              }
```
Am I the only one with this bug?

**Comment by EmilTholin** [comment]
Could you try `gatsby-image@1.0.9`? I just tried your example query, and it works for me in Safari.

<img width="1226" alt="gatsby_image_safari" src="https://user-images.githubusercontent.com/11573167/31318883-5fc1059a-ac59-11e7-8b41-c63d2f7de967.png">

**Comment by roberpoldo** [comment]
@EmilTholin Thanks for your reply. Is the lazy-load working for you in Safari?

I just have updated to 1.0.9. Now Images are showing up in Safari but the lazyload still doesn't work. It's loading all the images at once. Probably because of the non-supportive intersection-observer in -webkit browsers.
Now If I add a Int-Obs polyfill like [this package](https://www.npmjs.com/package/intersection-observer) , the images aren't showing up in Safari…  here is the html result:
```
<div class=" gatsby-image-wrapper" style="position: relative; overflow: hidden; z-index: 1;">
<div style="width: 100%; padding-bottom: 72.3%;"></div>
</div>
```

**Comment by EmilTholin** [comment]
Interesting. It does not lazy load in Safari, as you say. I don't know enough about Intersection Observer to say what it could be, sadly. It looks like [it is being worked on](https://bugs.webkit.org/show_bug.cgi?id=159475).

![gatsby_io_safari](https://user-images.githubusercontent.com/11573167/31319056-b85a29f4-ac5c-11e7-84c0-5ce079ce2105.gif)

**Comment by Haroenv** [comment]
IntersectionObserver is indeed not available without polyfill in stable Safari currently

**Comment by KyleAMathews** [comment]
gatsby-image checks for `window.IntersectionObserver` to be set in order to enable lazy loading so make sure the polyfill is set there.
