### ISSUE TITLE
Gatsby Cloud - GCS Deployment Issues

### ISSUE THREAD

**Issue by dolphub** [gatsbyjs/gatsby#23794]
## Description
We are triggered automated deployments from the Contentful integration publishes on the production branch.

We are seeing random issues in the code being deployed to GCS.
Last night we were seeing random `/html>` tags being inserted as strings at the bottom of the page.
After publishing a few times of simple data to re-trigger a build / deploy the issue alternated between `/html>`, `>ml>` and `ml>`.

**Note** Local dev, and the production build URL's produced by gatsby cloud do not have any of these issues, only the GCS artifacts.

This morning's build did not produce any random string artifacts, but it did randomly misspell some class names... 

```<img class="CustomerLogosSectios--logo" src="..." >```
```<img class="CustomerLogosSections--logo" src="..." >```
There is a random `n` missing from the class names... which very heavily breaks the page being rendered correctly.

The code that renders these logos is very simple, which renders 15+ logos on the screen the same way, yet it misspells one random class name when deployed to GCS.
```
      <div className="CustomerLogosSection--logos">
        {data.assets
          ? data.assets.map((p, i: number) => (
              <ContentfulAsset
                key={i}
                asset={p}
                className="CustomerLogosSection--logo"
              />
            ))
          : null}
      </div>
```

### Steps to reproduce
I'm not 100% sure, the issues seems to be indeterminate.

### Expected result
I expect the deploy target to receive the same code as the build pipeline and it render exactly the same.

### Actual result

Random strings are being injected / left out in the build artifacts breaking our site.
**Update** We're now seeing some images not rendering because there is a random `o` prepended to the src of an image tag 

```
<img class="CustomerLogosSection--logo" src="o/static/07be092964dd567a77aa856e">
```

### Environment

Gatsby Cloud's internal integrations with Contentful CMS integration and GCS deployment target.

**Comment by LekoArts** [comment]
Please contact Cloud's support via the „Help“ button in the top bar. Thanks!

**Comment by benrobertsonio** [comment]
@dolphub - thanks for filing this, we are working to resolve on the cloud side. I'll be in touch via email!
