### ISSUE TITLE
gatsby-plugin-react-next + gatsby-plugin-typography error

### ISSUE THREAD

**Issue by ssteinerx** [gatsbyjs/gatsby#2379]
Runs fine without react-next, and runs fine again after react-next is removed.

With react-next plugin:

```
 ERROR  Failed to compile with 1 errors                                                                       1:10:07 PM

 error  in ./~/gatsby-plugin-typography/.cache/typography.js

Module build failed: Error: ENOENT: no such file or directory, open '.../node_modules/gatsby-plugin-typography/.cache/typography.js'
    at Error (native)

 @ ./~/gatsby-plugin-typography/gatsby-browser.js 3:18-74
```

**Comment by KyleAMathews** [comment]
We use these two modules together in gatsbyjs.org so it doesn't seem this is always causing trouble. I'm guessing that modules in `node_modules` are getting moved around perhaps?

Could you look at where `gatsby-plugin-typography` is in `node_modules` both with the react-next plugin installed and without?

**Comment by ssteinerx** [comment]
Sorry, gave up on Gatsby when I saw how much code had to be written to render simple markdown files.  Not at all what I had in mind.  I won't be updating this.
