### ISSUE TITLE
What API should I use to access Redux store through graphql query and update the store back

### ISSUE THREAD

**Issue by maxkoretskyi** [gatsbyjs/gatsby#23791]
I'm querying Google Analytics and creating a node with data from it like this:

```
exports.sourceNodes = ({ actions, createNodeId, createContentDigest }) => {
    const data = analytics().then((data) => {
        const node = {
            hits: data,
            internal: {
                type: "AnalyticsNode",
            }
            ...
        };
        createNode(node);
    });
};
```

then I need to transform this data using information from other nodes, say posts, so I can query these nodes and transform the data inside `createPages`:

```
exports.createPages = async ({ graphql, actions }) => {
    const { createPage } = actions;

    const result = await graphql(`
        {
            allPost() { ... }
	    analyticsNode() { ... }	
         }
    `);

    const resultingData = mixData();
```

and **now I need to send this `resultingData` back to the store to make it queryable inside pages.** How do I do that?

If the page is static, I could send it through `context` inside create pages:

```
    createPage({
        path: 'analytics',
        component: path.resolve(`./src/templates/analytics.js`),
        context: {
            resultingData
        }
    });

```

but this wouldn't work for for dynamic pages, i.e. `/app` pages rendered using a Router.

**Comment by maxkoretskyi** [comment]
It seems that I can access all nodes inside `onPreExtractQueries` and update the node before query extraction process happens:

```
exports.onPreExtractQueries = async ({ actions, getNodesByType }) => {
    const nodes1 = getNodesByType("Post");
    const nodes2 = getNodesByType("AnalyticsNode");

    actions.createNodeField({
        node: nodes2[0],
        name: `somename`,
        value: "somevalue",
    });
};
```

the problem is that I don't know how to access this field inside a graphql page query. This fails:

```
query MyQuery {
    analyticsNode {
        fields {
            updated
        }
    }
}
```

**Comment by ascorbic** [comment]
Hi @maxkoretskyi 
It sounds liek what you need is similar to a [transformer plugin](https://www.gatsbyjs.org/docs/creating-a-transformer-plugin/). These take nodes of one type and add new nodes based on them. You can hook into onCreateNode and listen for the creation of e.g `Post`s, and add the "mixed nodes" then, querying for the analytics nodes too. Creating new nodes is generally a better approach than adding fields, and you can always make them a child of the other node if that helps. A lot of these could be easier to handle if you put them into a local plugin rather than all inside your gatsby-node file, as you can then control the order of execution in your gatsby-config.

**Comment by maxkoretskyi** [comment]
Hey @ascorbic, thanks for your feedback, I thought about this approach

> It sounds liek what you need is similar to a transformer plugin.

but my problem is that I need to wait until all Post and Analytics nodes have been created, can you expand a little bit on the order of execution, where and when is the best place to start transforming and adding new nodes?

**Comment by ascorbic** [comment]
Plugins are run in the order that they're listed in the gatsby-config, and then finally the ones in your own gatsby-node are run. If you put the analytics stuff into a local plugin, sourceNodes for that will be run, and then you can have another sourceNodes in your local gatsby-node that will be run after everything else. You can then do your stuff there.

**Comment by maxkoretskyi** [comment]
@ascorbic , got it, thanks, so what if `sourceNodes` in a plugin is async, does the same order remain? I mean, does Gatsby wait until async action from `sourceNodes` is finished in an external plugin before it moves to the next one? 

With this approach I can't use `graphql` to run a query, correct? Wouldn't it be better to use some API if it exists like `onPreExtractQueries` that runs after all nodes have been sourced and also where I can have access to `graphql` to run a query and create a new node?

**Comment by maxkoretskyi** [comment]
@ascorbic , so since there's no `getNodesByType` inside `actions` that are passed to `onCreateNode`, I managed to implement my solution like this:

```
const postNodes = [];

exports.onCreateNode = async ({ node, actions }) => {
    const { createNode } = actions;

    if (node.internal.type === "Post") { postNodes.push(node) }

    if (node.internal.type === "Analytics") {
        const data = mixData(postNodes, node);
        
        const processed = {
            id: `Analytics__Node__5e001c79d724c36e46с254865`,
            parent: null,
            data: data,
            children: [],
            internal: {
                type: "ProcessedHits",
                contentDigest: "57e14fe254d2510eb9e2ab61763d21745",
            },
        };
        createNode(processed);
    }
}
```

can you please confirm this is how you expected it to me implemented?

**Comment by ascorbic** [comment]
@maxkoretskyi  OK, now I understand a bit better what you're after. A custom resolver is what you need. Attach as a new field on `Analytics`, and inside the resolver you can access `Post` and handle `mixData`. See https://www.gatsbyjs.org/docs/schema-customization/#createresolvers-api

**Comment by maxkoretskyi** [comment]
@ascorbic , got it working, awesome, appreciate your help! Last quick question, is there any way to access nodes storage (context.nodeModel in resolvers) in a runtime, from component through redux maybe?

**Comment by ascorbic** [comment]
Hi @maxkoretskyi. No, there's not currently a way to access that data at runtime. It's something people have requested, but couldn't be implemented without running a live GraphQL server for each site.

I'm going to close this now. If you have any more questions, let me know.
