### ISSUE TITLE
Adding Markdown Pages - Error: data is missing in props validation

### ISSUE THREAD

**Issue by saschaseniuk** [gatsbyjs/gatsby#23806]
Hi,

i´m trying to follow along the tutorial https://www.gatsbyjs.org/docs/adding-markdown-pages/

after saving the "blogTemplate.js" the following error occurs:

5:36  error  'data' is missing in props validation                                   react/prop-types
6:21  error  'data.markdownRemark' is missing in props validation                    react/prop-types
10:19  error  'data.markdownRemark.frontmatter' is missing in props validation        react/prop-types
10:31  error  'data.markdownRemark.frontmatter.title' is missing in props validation  react/prop-types
11:54  error  'data.markdownRemark.html' is missing in props validation               react/prop-types

**Comment by saschaseniuk** [comment]
import React from "react"
import { graphql } from "gatsby"
import Layout from "../components/layout"

export default function BlogPost({ data }) {
  const post = data.markdownRemark
  return (
    <Layout>
      <div>
        <h1>{post.frontmatter.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: post.html }} />
      </div>
    </Layout>
  )
}

export const pageQuery = graphql`
  query($path: String!) {
    markdownRemark(frontmatter: { path: { eq: $path } }) {
      html
      frontmatter {
        date(formatString: "MMMM DD, YYYY")
        path
        title
      }
    }
  }
`

**Comment by saschaseniuk** [comment]
`import React from "react"
import { graphql } from "gatsby"
import Layout from "../components/layout"

export default function BlogPost({ data }) {
  const post = data.markdownRemark
  return (
    <Layout>
      <div>
        <h1>{post.frontmatter.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: post.html }} />
      </div>
    </Layout>
  )
}

export const pageQuery = graphql`
  query($path: String!) {
    markdownRemark(frontmatter: { path: { eq: $path } }) {
      html
      frontmatter {
        date(formatString: "MMMM DD, YYYY")
        path
        title
      }
    }
  }
``

**Comment by thrixton** [comment]
Reopen.
Any ideas on this?
Still an issue following current docs.

**Comment by Tapha** [comment]
I'm experiencing the same issue. The following is my code:

import React from 'react';
import { graphql } from 'gatsby';

const PostPage = ({
  data: {
    gcms: { post },
  },
}) => (
  <React.Fragment>
    <h1>{post.title}</h1>
    <p>{post.slug}</p>
  </React.Fragment>
);

```
export const pageQuery = graphql`
  query PostPageQuery($id: ID!) {
    gcms {
      post(where: { id: $id }) {
        title
        slug
      }
    }
  }
`;

export default PostPage;
```
