### ISSUE TITLE
MDXRenderer with object property fails on "gatsby build"

### ISSUE THREAD

**Issue by pofallon** [gatsbyjs/gatsby#23815]
## Description

When including an object property in `<MDXRenderer>` like this:
```jsx
const testing = { name: 'Paul' }
//...
<MDXRenderer testing={testing}>{post.body}</MDXRenderer>
```
and referencing it in a *.mdx file like this:  `<pre>{props.testing.name}</pre>`

`gatsby develop` renders this correctly (the string `Paul` is displayed on the page) but running `gatsby build` results in an error:

```
gatsby-plugin-mdx
TypeError: Cannot read property 'name' of undefined
    at MDXContent (eval at _construct (evalmachine.<anonymous>:1624:584), <anonymous>:31:38)
```
### Steps to reproduce

This site demonstrates the problem: https://github.com/pofallon/gatsby-mdx-issue

* See the `<MDXRenderer>` property in `src/templates/blog-post.js`
* Run `gatsby develop` and view the "Hello World" blog post to see `Paul` displayed.
* Run `gatsby build` and you should see the above error.

(this site is based on [this MDX blog starter](https://www.gatsbyjs.org/starters/hagnerd/gatsby-starter-blog-mdx/))

### Expected result

`gatsby build` should render the same property value as `gatsby develop`

### Actual result

Running `gatsby build` produces an error

### Environment

```
  System:
    OS: macOS 10.15.4
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/opt/node@12/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.14.4 => 2.21.13
    gatsby-image: ^2.0.22 => 2.4.1
    gatsby-plugin-feed: ^2.0.8 => 2.5.1
    gatsby-plugin-google-analytics: ^2.0.5 => 2.3.1
    gatsby-plugin-manifest: ^2.0.5 => 2.4.2
    gatsby-plugin-mdx: ^1.0.33 => 1.2.6
    gatsby-plugin-offline: ^2.0.5 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.0 => 3.3.1
    gatsby-plugin-sharp: ^2.0.6 => 2.6.1
    gatsby-plugin-typography: ^2.2.0 => 2.5.1
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.3.2
    gatsby-remark-images: ^3.1.19 => 3.3.1
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.4.2
    gatsby-remark-smartypants: ^2.0.5 => 2.3.1
    gatsby-source-filesystem: ^2.0.2 => 2.3.1
    gatsby-transformer-remark: ^2.1.6 => 2.8.6
    gatsby-transformer-sharp: ^2.1.3 => 2.5.1
  npmGlobalPackages:
    gatsby-cli: 2.12.7
```

**Comment by johno** [comment]
Thanks for opening up an issue! Turns out that this is a problem with compatibility between `gatsby-plugin-mdx` and `gatsby-plugin-feed`. If you remove `gatsby-plugin-feed` your build _should_ succeed.

I'm curious what you're looking to achieve by passing props into an MDX document. This isn't a usecase we've considered (though it is technically supported). Perhaps you can try using frontmatter or an import?

The way `gatsby-plugin-feed` works, it doesn't use the `MDXRenderer` codepath so it has no access to props.

Considering props passing into MDX in combination with `gatsby-plugin-feed` is sort of an edgecase we don't have plans to support in the near future, but we would accept a PR from a community member.

**Comment by pofallon** [comment]
Thanks for the reply @johno!  The short version of what I'm trying to achieve is to make part of the template's `pageQuery` results accessible in the *.mdx file.  If there's a better way to do that in Gatsby, I'd be interested to learn that too!

Here's the longer, more specific version of what I'm trying to do:
- In my [blog project](https://github.com/pofallon/blog) I want to include YouTube playlist information (including video titles, links, etc.) within my blog posts.
- These playlists will be identified in YAML front matter in the *.mdx file and then later passed to a custom React component in the page body, like this:
```
---
playlists:
- { name: london, id: PLCU2qJekvcN2f9rgS50xy7-4QBpgwid4G }
---

View all the sessions from Gatsby Days 2019 London!

<Playlist content={props.playlists.london} />
```
- This is done with a [transformer plugin](https://github.com/pofallon/gatsby-transformer-playlists) which parses the front matter, calls the YouTube API and adds the playlist/video information as child elements to the mdx nodes.
- The default template for these blog posts then queries [this playlist data](https://github.com/pofallon/blog/blob/f56a81f15e51c422532f0af0f6a4723f4c12c579/src/templates/blog-post.js#L113-L129) as part of the `pageQuery`, [reformats it](https://github.com/pofallon/blog/blob/f56a81f15e51c422532f0af0f6a4723f4c12c579/src/templates/blog-post.js#L19-L26) and [defines it as a property](https://github.com/pofallon/blog/blob/f56a81f15e51c422532f0af0f6a4723f4c12c579/src/templates/blog-post.js#L54) on `<MDXRenderer>`.
- This then makes the information available on `props` in the *.mdx page where it can be passed into the `<Playlist>` component as described above.

**Comment by i-bsd** [comment]
I have the same problem.

Disabling `gatsby-plugin-feed` stopped the error for me, but this is not ideal since I require a feed.

I'm passing frontmatter to MDXRenderer as prop and it's vital. Is there a way around this issue?

**Comment by matthewhoth** [comment]
@i-bsd , @pofallon 

Did y'all ever find a solution? I don't have the gatsby-plugin-feed and these errors are so nondescript I'm going crazy.

Spent literal days just trying to render a prop passed string.

**Comment by ahmedfaaid** [comment]
Has anyone found a solution to this? I need a feed for my website.
