### ISSUE TITLE
I'm trying to import a Header.js from components into index page, Not working. Any help ?

### ISSUE THREAD

**Issue by theboyonline** [gatsbyjs/gatsby#23827]
## Summary
I'm trying to import a header.js from components, but whenever I put up Header on index page, it's my browser get no response issue but on console it shows no error, Whenever i remove them it works smoothly without any issue. Am i doing something wrong ? 
I use with React-bootstrap 

Here is the Repo https://github.com/theboyonline/helloblank

## Relevant information

https://github.com/theboyonline/helloblank

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by Olanetsoft** [comment]
@theboyonline I have checked your repo and I realize your reference isn't done correctly, I have made some changes kindly check to merge my PR and confirm the fix.
