### ISSUE TITLE
Invalid left-hand side expression in prefix operation mdx-renderer.js:24

### ISSUE THREAD

**Issue by isabellachen** [gatsbyjs/gatsby#23831]
I was converting my md files to mdx in [my blog](https://github.com/isabellachen/isachen). I followed the steps in [how to convert an existing Gatsby blog to us MDX ](https://www.gatsbyjs.org/blog/2019-11-21-how-to-convert-an-existing-gatsby-blog-to-use-mdx/) Everything was working fine until I tried to use the `<MDXRenderer>` component.

I have a gatsby-node.js file which creates pages from my mdx files. I have a blog archive page which links all the blog titles to the blog page itself. When I try to access the blog page from the archives page, I get the error `TypeError: Cannot read property 'innerText' of null` coming from `/.cache/navigation.js:177`. When I refresh the page however, I get a different error `SyntaxError: Invalid left-hand side expression in prefix operation`.

![gatsby-err-1](https://user-images.githubusercontent.com/9280665/81178367-62051780-8fa8-11ea-99e0-2fdf2e7bf98b.gif)

I have removed my `node_modules`, ran `gatsby clean` and `yarn install` to reinstall the dependencies and still this error persists.

### Minimal Repro
I created a [minimum viable example](https://github.com/isabellachen/my-mdx-starter) with the gatsby mdx starter by @ChristopherBiscardi , updated the package.json for more recent versions of gatsby and gatsby-plugin-mdx and created a similar structure. 

When I comment out the `<MDXRenderer>{body}</MDXRenderer>` in the blogPostSingle (which gatsby-node uses to generate the pages), I don't have any problems. I am able to access the page via the `<Link>` from the archives and on a refresh. It only shows the frontmatter data of course, not the `rawBody`.  

Using <MDXRenderer>, I get the same issues. `TypeError: Cannot read property 'innerText' of null` and `Uncaught SyntaxError: Invalid left-hand side expression in prefix operation` 

As a side note, before I updated to the latest gatsby version, I was getting `navigation.js:173 Uncaught TypeError`. Another user commented on the MDXRenderer causing the problem [issue #21263](https://github.com/gatsbyjs/gatsby/issues/21263#issuecomment-602205360)

I tried wrapping the MDXRenderer with an MDXProvider, but this did not resolve the issue...

### Environment
Am using gatsby-cli 2.11.16
#### System Info
  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
    Safari: 13.1

#### Packages
    gatsby: ^2.20.25 => 2.21.15
    gatsby-image: ^2.2.8 => 2.2.8
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-mdx: ^1.2.6 => 1.2.6
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-source-filesystem: ^2.2.5 => 2.3.1
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5

#### Packages in the minimum

**Comment by vladar** [comment]
As for the error `TypeError: Cannot read property 'innerText' of null (in /.cache/navigation.js:177)` - I've seen a similar error here #23583

**Comment by johno** [comment]
Thank you very much for the thorough issue and reproduction @isabellachen! Your template needs to be changed so that it references `body` rather than `rawBody` because MDXRenderer expects the transpiled version rather than the raw MDX.

Updating your template to reflect the diff below should fix this issue for you!

```diff
@@ -4,7 +4,7 @@ import { MDXRenderer } from 'gatsby-plugin-mdx';
 
 export default ({ data }) => {
   const title = data.mdx.frontmatter.title;
-  const body = data.mdx.rawBody;
+  const body = data.mdx.body;
 
   return (
     <div className="mb-4">
@@ -17,7 +17,7 @@ export default ({ data }) => {
 export const query = graphql`
   query($slug: String!) {
     mdx(frontmatter: { path: { eq: $slug } }) {
-      rawBody
+      body
       frontmatter {
         title
       }
```
