### ISSUE TITLE
Why does GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES  always build all pages?

### ISSUE THREAD

**Issue by starrett67** [gatsbyjs/gatsby#23841]
## Summary

I am trying to set up incremental builds for my site. We are currently building ~68k pages for each build so build times are very long. Unfortunately, we have to do this in house because of some build requirements that cannot be satisfied by gatsby cloud. However, every time I run a build, even if code has not changed, I rebuild all pages and my newPages.txt has 68k lines in it.

## Relevant information

I have this set up in Jenkins. We use ec2 plugin to run our builds on so all the build machines are ephemeral and builds do not consistently use the same machine. I am saving my .cache directory and public directory to S3 inside a folder that corresponds to the git commit SHA. So basically a build goes like this:

1. Check if .cache and public directory exists in s3 depending on the git commit SHA
2. If it does download the .cache and public directories into the workspace
3. GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES = "true" is always set
4. Do a gatsby build and write built pages to file
5. Always save cache and public folders into git commit SHA folder in s3

I am looking for some help on what I should be looking at or debugging tips to figure out why all pages are being built.

### Bonus Questions
1. Does a change to match-path.json cause all pages to be rebuilt?
2. Is it possible to detect if all pages will be rebuilt before starting a build? I would like to optimized build machine cost and it will also affect how we deploy to s3 because we usually deploy to a new location every time and then swap the CDN origin to point towards it. 

Unfortunately, I cannot share everything publicly but I can email detail privately. I will continue to update as I find out more

**Comment by herecydev** [comment]
Is it possible any of your page-data is changing that could be causing it to rebuild?

**Comment by starrett67** [comment]
This is my thought as well. I set up a way to build from a static contentful export and static product data export. Going to see if it makes any difference. I Will update in a few moments.

**Comment by pieh** [comment]
> 1. Does a change to match-path.json cause all pages to be rebuilt?

Yes! Change like that will change the webpack generated hash. And this cause every .html page to be rewritten because .js file hashes will change. 

Also currently any data change that is queried by static queries will cause all pages to be rebuilt as well - there is work being done to prevent that - https://github.com/gatsbyjs/gatsby/pull/23837 - but this will take some time.

Similarly - adding or removing page templates, or in-browser redirects will also cause full html rebuilds

> 2\. Is it possible to detect if all pages will be rebuilt before starting a build? I would like to optimized build machine cost and it will also affect how we deploy to s3 because we usually deploy to a new location every time and then swap the CDN origin to point towards it.

We can detect it at some point of a build (after webpack compilation). Maybe you could do pre-step to try to infer if build would change webpack hash (using notes I mentioned in answer to point 1) ) - but that's not something that Gatsby can know ahead of time on its own and would require you writing custom logic for that

**Comment by starrett67** [comment]
Thanks @pieh this information helps me out greatly! Unfortunately for us, we have product listing pages that get created all the time on the fly and each page adds an entry in match-path.json. I also found that we are adding algolia search result data into some of our pages at build time. I believe this is the reason my page data keeps changing. It looks like we have to make some major changes in order to be more compatible with incremental builds.

**Comment by wardpeet** [comment]
Enabling `GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES` is not the same as "incremental builds". `"GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES"` is an experimental feature (not for production use) and it is designed to speed-up page creation. It's not made to make gatsby build truly incremental on data-changes, ... When anything in webpack changes, we have to rebuild all pages, as @pieh mentioned. I feel you have to re-architect a bit of your site.

> Is it possible to detect if all pages will be rebuilt before starting a build? I would like to optimized build machine cost and it will also affect how we deploy to s3 because we usually deploy to a new location every time and then swap the CDN origin to point towards it.

Sadly, we do not provide an API to do this. You could build your own ruleset where you check what has changed from last build (data/code) that give you a conclusion. 

I don't think we can help you any further on this issue, but feel free to send me a message at ward@gatsbyjs.com with some extra information and the reason why gatsby cloud isn't a possibility.

**Comment by devuxer** [comment]
@wardpeet , What is the relationship between GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES  and netlify-plugin-gatsby-cache? [This blog post](https://www.netlify.com/blog/2020/04/23/enable-gatsby-incremental-builds-on-netlify/) suggests the environment variable is required to turn on incremental builds. Is that not correct?

**Comment by wardpeet** [comment]
Incremental builds isn't really the right term. We call it [Conditional Page Builds](https://www.gatsbyjs.org/docs/conditional-page-builds/). It only builds pages that are necessary but it's not the same as Incremental Builds on gatsby cloud.

> What is the relationship between GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES and netlify-plugin-gatsby-cache

That's something you'll have to ask Netlify, I don't really know what `netlify-plugin-gatsby-cache` does.

**Comment by devuxer** [comment]
@wardpeet , Aha! I was wondering how Gatsby was saying incremental builds are only available on Gatsby Cloud, then suddenly Netlify was claiming they had them too. Based on my ~20-page test site, "conditional page builds" saved only a little bit of time.

One thing in particular that seems to really slow down builds for me is how long it takes for mini-css-extract-plugin to run when using Ant Design. With conditional page builds, it seemed that this plugin was still running on pages that shouldn't have needed to rebuild. (Sometimes, I just triggered a rebuild without changing anything, and mini-css-extract-plugin still threw a bunch of warnings about imports being out of order.) Perhaps this is due conditional page builds still being experimental.

**Comment by LekoArts** [comment]
Since the original question was answered I'll close this one.

As laid out the "Conditional page builds" are not "Incremental builds" (only on Gatsby Cloud) and they are experimental and only for for HTML re-generation.
