### ISSUE TITLE
I cant reach Graphql playground

### ISSUE THREAD

**Issue by Angelhpascual** [gatsbyjs/gatsby#23846]
## Summary

I try to get GRAPHQL as a global variable adding ".env.development" file with the code "GATSBY_GRAPHQL_IDE=playground", I downloaded the env-cmd dependencies with yarn just typing "yarn add env-cmd" and now I have some problems that I can not resolve myself and that's why Im looking for help. 
I change the package.json develop line to "env-cmd .env.development gatsby develop"
When I try to make a yarn run I have this error:

`yarn run v1.22.4
warning ../package.json: No license field
$ npm run develop
npm WARN lifecycle The node binary used for scripts is /var/folders/g8/8j6lzrfn2cvfwzy7jyp7yfy80000gn/T/yarn--1588793366403-0.01248939580439079/node but npm is using /Users/angelpfm/.nvm/versions/node/v13.11.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> gatsby-starter-hello-world@0.1.0 develop /Users/angelpfm/blogGatby2/gatsby-bootcamp
> env-cmd .env.development gatsby develop

Error: Failed to find .env file at default paths: [./.env,./.env.js,./.env.json]
    at getEnvFile (/Users/angelpfm/blogGatby2/gatsby-bootcamp/node_modules/env-cmd/dist/get-env-vars.js:58:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-hello-world@0.1.0 develop: `env-cmd .env.development gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-hello-world@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/angelpfm/.npm/_logs/2020-05-06T19_29_28_024Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

And when I try to type "gatsby develop" everything works fine but It doesn't show the GraphQL playground and I dn't know why. 

Is something wrong with my dependencies or my package manager? 
Thank you so much if you can help me 
and sorry for my newbie English
Keep Gatsby strong!

**Comment by ascorbic** [comment]
Hi. [env-cmd](https://www.npmjs.com/package/env-cmd) needs a `-f` flag if you're using a custom `.env` file. e.g. in your case it would be `env-cmd -f .env.development gatsby develop`. However that shouldn't be needed if you only need this one var. You can pass in env vars inline, without needing `env-cmd`: 

`GATSBY_GRAPHQL_IDE=playground gatsby develop`

For more information see [the docs here](https://www.gatsbyjs.org/docs/using-graphql-playground/)

I'm going to close this, but if you have any more questions please do re-open.
