### ISSUE TITLE
Content Missing on browser-apis docs page

### ISSUE THREAD

**Issue by mickeyreiss** [gatsbyjs/gatsby#23857]
I'm seeing a relatively blank screen at https://www.gatsbyjs.org/docs/browser-apis. I was expecting to see some content underneath **`APIs`** and **`Reference`**.

![image](https://user-images.githubusercontent.com/47405/81237612-eeb5d280-8fb4-11ea-9605-f55fff058219.png)

Am I missing something on my end?

Thanks, team Gatsby!

**Comment by shrthnd** [comment]
I see the same issue on the node-apis docs page:

![image](https://user-images.githubusercontent.com/25191/81242811-18362480-8fdc-11ea-9867-0075c341ba40.png)

**Comment by mathieudutour** [comment]
I think the issue is this PR: https://github.com/gatsbyjs/gatsby/pull/20763

**Comment by ascorbic** [comment]
Thanks for the report. It seems this is an issue with our TypeScript conversion, which gatsby-transformer-js is having trouble with.
