### ISSUE TITLE
createNodeField documentation falsely(?) claims that field values must be strings

### ISSUE THREAD

**Issue by colinmorris** [gatsbyjs/gatsby#23852]
The [API documentation for `createNodeField`](https://www.gatsbyjs.org/docs/actions/#createNodeField) says that the "value" argument must be of type string. 

I am doubtful as to whether this is an intended limitation, because
- I've tested adding numbers, lists, and objects using the API, and it seems to work as you would hope
- In practice, the function seems to be widely used with non-string arguments. For example, [here](https://github.com/eggheadio/gatsby-starter-egghead-blog/blob/0dd9184a8b99fda56727fe65146474b1197601de/gatsby-node.js#L184) in a starter project with ~500 stars.

If I'm wrong, and this really isn't intended to be officially supported, please close this. (But if that's the case, I may file a separate feature request for this to be supported, because it seems highly desirable to me to be able to attach structured data to nodes without having to encode it as a string.)

**Comment by marcysutton** [comment]
This PR would benefit from a core team review, as it could be answered quickly by someone more familiar with Schema Customization. As a result, I've relabeled it with the triage needed label for the @gatsbyjs/core to review: please comment and we can make changes to the docs accordingly.

**Comment by freiksenet** [comment]
Hello!

That's indeed the case. I've made a patch to fix it [in this PR](https://github.com/gatsbyjs/gatsby/pull/24740).

Thank you!
