### ISSUE TITLE
Graphql Error for image

### ISSUE THREAD

**Issue by emmadigital** [gatsbyjs/gatsby#23869]
###Summary: 
I am using Netlify CMS for content management and Gatsby. When I am updating any blog or creating a page on Netlify CMS I get build error of image field but not mention the page and line number, however Its working locally. Please advise.

## Repo: 
https://github.com/emmadigital/ardalis-newsite

### Environment (if relevant)

  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: ^2.20.35 => 2.21.9
    gatsby-image: ^2.3.5 => 2.4.0
    gatsby-plugin-netlify: ^2.2.4 => 2.3.0
    gatsby-plugin-netlify-cms: ^4.2.5 => 4.3.0
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^3.2.5 => 3.3.0
    gatsby-plugin-sass: ^2.2.4 => 2.3.0
    gatsby-plugin-sharp: ^2.5.7 => 2.6.0
    gatsby-plugin-twitter: ^2.3.1 => 2.3.1
    gatsby-remark-copy-linked-files: ^2.2.4 => 2.3.1
    gatsby-remark-images: ^3.2.6 => 3.3.0
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-source-filesystem: ^2.2.5 => 2.3.0
    gatsby-transformer-remark: ^2.7.5 => 2.8.4
    gatsby-transformer-sharp: ^2.4.7 => 2.5.0

## Netlify Build Error: 

4:55:15 PM: Build ready to start
4:55:21 PM: build-image version: 2dbd444fcdce00cf06325060a8238d5ae3e86774
4:55:21 PM: build-image tag: v3.3.7
4:55:21 PM: buildbot version: d305548225ac57bb00eb5a596b0b8674e76a4681
4:55:21 PM: Fetching cached dependencies
4:55:21 PM: Starting to download cache of 274.5MB
4:55:24 PM: Finished downloading cache in 3.114633215s
4:55:24 PM: Starting to extract cache
4:55:39 PM: Finished extracting cache in 14.645103875s
4:55:39 PM: Finished fetching cache in 17.84241352s
4:55:39 PM: Starting to prepare the repo for build
4:55:39 PM: Preparing Git Reference pull/23/head
4:55:41 PM: Found Netlify configuration file netlify.toml in site root
4:55:41 PM: Found Netlify configuration file(s). Overriding site configuration
4:55:41 PM: Different functions path detected, going to use the one specified in the Netlify configuration file: 'lambda' versus '' in the Netlify UI
4:55:41 PM: Creating functions prep folder
4:55:41 PM: Starting build script
4:55:41 PM: Installing dependencies
4:55:41 PM: Started restoring cached node version
4:55:45 PM: Finished restoring cached node version
4:55:46 PM: v12.16.3 is already installed.
4:55:46 PM: Now using node v12.16.3 (npm v6.14.4)
4:55:47 PM: Attempting ruby version 2.6.2, read from environment
4:55:48 PM: Using ruby version 2.6.2
4:55:48 PM: Using PHP version 5.6
4:55:48 PM: Started restoring cached node modules
4:55:48 PM: Finished restoring cached node modules
4:55:49 PM: Started restoring cached go cache
4:55:49 PM: Finished restoring cached go cache
4:55:49 PM: unset GOOS;
4:55:49 PM: unset GOARCH;
4:55:49 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
4:55:49 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
4:55:49 PM: go version >&2;
4:55:49 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
4:55:49 PM: go version go1.12 linux/amd64
4:55:49 PM: Installing missing commands
4:55:49 PM: Verify run directory
4:55:49 PM: Executing user command: npm run build
4:55:49 PM: > gatsby-starter-netlify-cms@1.1.3 build /opt/build/repo
4:55:49 PM: > npm run clean && gatsby build
4:55:49 PM: > gatsby-starter-netlify-cms@1.1.3 clean /opt/build/repo
4:55:49 PM: > gatsby clean
4:55:50 PM: info Deleting .cache, public
4:55:50 PM: info Successfully deleted directories
4:55:52 PM: success open and validate gatsby-configs - 0.045s
4:55:54 PM: success load plugins - 1.564s
4:55:54 PM: success onPreInit - 0.012s
4:55:54 PM: success delete html and css files from previous builds - 0.014s
4:55:54 PM: success initialize cache - 0.008s
4:55:54 PM: success copy gatsby files - 0.049s
4:55:54 PM: success onPreBootstrap - 0.015s
4:55:54 PM: success createSchemaCustomization - 0.021s
4:55:54 PM: success source and transform nodes - 0.433s
4:55:55 PM: success building schema - 0.508s
4:55:55 PM: success createPages - 0.108s
4:55:55 PM: success createPagesStatefully - 0.106s
4:55:55 PM: success onPreExtractQueries - 0.000s
4:55:55 PM: success update schema - 0.048s
4:55:56 PM: error There was an error in your GraphQL query:
**4:55:56 PM: Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?
4:55:56 PM: error There was an error in your GraphQL query:
4:55:56 PM: Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?
4:55:56 PM: error There was an error in your GraphQL query:
4:55:56 PM: Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?
4:55:56 PM: error There was an error in your GraphQL query:
4:55:56 PM: Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?
4:55:56 PM: error There was an error in your GraphQL query:
4:55:56 PM: Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?
4:55:56 PM: error There was an error in your GraphQL query:
4:55:56 PM: Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?
4:55:56 PM: error There was an error in your GraphQL query:
4:55:56 PM: Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?
4:55:56 PM: error There was an error in your GraphQL query:
4:55:56 PM: Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?
4:55:56 PM: error There was an error in your GraphQL query:
4:55:56 PM: Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?
4:55:56 PM: error There was an error in your GraphQL query:
4:55:56 PM: Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?
4:55:56 PM: error There was an error in your GraphQL query:
4:55:56 PM: Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?**
4:55:56 PM: failed extract queries from components - 0.592s
4:55:56 PM: npm
4:55:56 PM:  ERR! code ELIFECYCLE
4:55:56 PM: npm
4:55:56 PM: ERR!
4:55:56 PM: errno
4:55:56 PM:  1
4:55:56 PM: npm
4:55:56 PM: ERR! gatsby-starter-netlify-cms@1.1.3 build: `npm run clean && gatsby build`
4:55:56 PM: npm ERR! Exit status 1
4:55:56 PM: npm ERR!
4:55:56 PM: npm
4:55:56 PM:  ERR! Failed at the gatsby-starter-netlify-cms@1.1.3 build script.
4:55:56 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
4:55:56 PM: npm
4:55:56 PM: ERR!
4:55:56 PM:  A complete log of this run can be found in:
4:55:56 PM: npm
4:55:56 PM: ERR!
4:55:56 PM:      /opt/buildhome/.npm/_logs/2020-05-07T13_55_56_098Z-debug.log
4:55:56 PM: Function Dir: /opt/build/repo/lambda
4:55:56 PM: TempDir: /tmp/zisi-5eb4134348ad120007c4e123
4:55:56 PM: Prepping functions with zip-it-and-ship-it 0.3.1
4:55:57 PM: [ { path: '/tmp/zisi-5eb4134348ad120007c4e123/hello.zip',
4:55:57 PM:     runtime: 'js' } ]
4:55:57 PM: Prepping functions complete
4:55:57 PM: Caching artifacts
4:55:57 PM: Started saving node modules
4:55:57 PM: Finished saving node modules
4:55:57 PM: Started saving pip cache
4:55:57 PM: Finished saving pip cache
4:55:57 PM: Started saving emacs cask dependencies
4:55:57 PM: Finished saving emacs cask dependencies
4:55:57 PM: Started saving maven dependencies
4:55:57 PM: Finished saving maven dependencies
4:55:57 PM: Started saving boot dependencies
4:55:57 PM: Finished saving boot dependencies
4:55:57 PM: Started saving go dependencies
4:55:57 PM: Finished saving go dependencies
4:55:57 PM: Error running command: Build script returned non-zero exit code: 1
4:55:57 PM: Failing build: Failed to build site
4:55:57 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
4:55:57 PM: Finished processing build request in 36.253886277s

**Comment by ascorbic** [comment]
Hi. Is the repo publicly available? Can you at the very least share the GraphQL queries that are refererring to the `image` fields?

**Comment by ascorbic** [comment]
OK, the issue is with the page queries. You're querying the image in the frontmatter like this:

```js
export const interviewsPageQuery = graphql`
  query InterviewsPage($id: String!) {
    markdownRemark(id: { eq: $id }) {
      html
      frontmatter {
        title
        image
      }
    }
  }
`
```

...but the `image` field is actually a File object, so needs to be queried more like this:

```graphql

             image {
              childImageSharp {
                fluid(maxWidth: 526, quality: 92) {
                  ...GatsbyImageSharpFluid
                }
              }
            }
```

This should fix the issue. If it doesn't please feel free to reopen this or open a new issue.

**Comment by emmadigital** [comment]
I had this code before but I was getting error due to which I removed this code https://prnt.sc/sc059l

**Comment by ascorbic** [comment]
Hi,
Then issue there is that the image isn't being found. If it finds the image then it turns it into a File node. When I cloned your repo and ran it locally I got the same error as you got on build.

**Comment by emmadigital** [comment]
> Hi,
> Then issue there is that the image isn't being found. If it finds the image then it turns it into a File node. When I cloned your repo and ran it locally I got the same error as you got on build.

The images are inside the directory but the file path in md files is not updated properly i dont understand why netlify cms not updating md files properly when its uploading files to right directory.
