### ISSUE TITLE
Gatsby routing between pages is extremely slow on production. Sometimes takes upto 4 seconds to navigate between pages. Please let me know if there is any fix for this. Thanks

### ISSUE THREAD

**Issue by rhaegar453** [gatsbyjs/gatsby#23862]
## Description

I have created a gatsby site https://www.getservicegrid.com, one can see that clicking on the navlinks takes about 3-4 seconds to actually navigate to the page.

### Steps to reproduce

- Visit https://www.getservicegrid.com.
- Click on any of the navlinks

**Comment by ascorbic** [comment]
Hi,
This doesn't seem to be a Gatsby issue specifically. It seems to be that you have some very large JS chunks loading. e.g. this one seems to be full of some sort of address data, and is ~400kB gzipped: https://www.getservicegrid.com/component---src-pages-blog-js-2240971088975dc66f79.js
Try using webpack-bundle-analyzer to see where the size is coming from.

**Comment by rhaegar453** [comment]
Couldn't thank you enough sir. The site was using the faker library because of which content took longer to load. I forgot to include that as a part of development dependency and rolled it in production. Thanks again
