### ISSUE TITLE
onCreateNode question

### ISSUE THREAD

**Issue by apmsooner** [gatsbyjs/gatsby#23885]
I have a situation where a field (address) sourced from Drupal comes back with just 2 digit state code and I want to modify the field to include the full state name so i created a function that does a lookup for the code and returns the name. Ideally i want the additional property to display with the address object vs. using createNodeField where it would show up separately in a fields object. This works great... but is there anything wrong about this approach concerning node immutability?

```js
exports.onCreateNode = ({ node, actions }) => {
  const { createNode, createNodeField } = actions;
  // Transform the new node here and create a new node or
  // create a new node field.
  if (node.internal.type === 'hotel') {
    if (node.address !== null) {
      node.address = {
        ...node.address,
        administrative_area_name: getAddressStateName(node.address.country_code, node.address.administrative_area)
      }
    }
  }
};
```

**Comment by capndave** [comment]
I think your modifications only mutate the node.address within the scope of the function, which shouldn't matter as long as it works for you.

**Comment by apmsooner** [comment]
@capndave  - yeah that was my thought too and yes it does work. Thanks for the reply

**Comment by pvdz** [comment]
Seems asked and answered. Closing the issue :)
