### ISSUE TITLE
How to add pagination feature

### ISSUE THREAD

**Issue by emmadigital** [gatsbyjs/gatsby#23886]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A 

#Summary

I am using this starter template: https://github.com/netlify-templates/gatsby-starter-netlify-cms and the blog listing page doesn't have pagination feature.

Kindly suggest how can I implement pagination for blog listing page for this starter template as I have more than 1000 blogs which will cause lot of scrolling. Is there any easy and quick solution for pagination or load on click button, that you can suggest.

**Comment by herecydev** [comment]
Hey 👋 , there's a chapter [here](https://www.gatsbyjs.org/docs/adding-pagination/) that covers exactly your scenario. The end result is you will have `/blogs`, `/blogs/1`, `/blogs/2`, etc.

**Comment by LekoArts** [comment]
Thank you for opening this!

As Dan said please follow the official guide in our docs and you should be all set up!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by emmadigital** [comment]
> Hey 👋 , there's a chapter [here](https://www.gatsbyjs.org/docs/adding-pagination/) that covers exactly your scenario. The end result is you will have `/blogs`, `/blogs/1`, `/blogs/2`, etc.

@herecydev thanks for sharing the chapter it was very helpful can you also share how to create pagination for blog categories or tags https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/master/src/templates/tags.js

**Comment by herecydev** [comment]
Same principal, just query the tags instead of blogs...

**Comment by emmadigital** [comment]
> Same principal, just query the tags instead of blogs... I tried but its not creating this structure but for tags I want `tags/tag-one/page/2`  `tags/tag-one/page/3` like this

```
 const posts = result.data.allMarkdownRemark.edges
    // Tag pages:
    let tags = []
    const postsPerPage = 2;
    // Iterate through each post, putting all found tags into `tags`
    posts.forEach((edge) => {
      if (_.get(edge, `node.frontmatter.tags`)) {
        tags = tags.concat(edge.node.frontmatter.tags)
      }
    })
    // Eliminate duplicate tags
    tags = _.uniq(tags)

    // Make tag pages
    tags.forEach((tag) => {
      const tagPath = `/tags/${_.kebabCase(tag)}/`

      const numPages = Math.ceil(tags.length / postsPerPage);

      Array.from({ length: numPages }).forEach((_, i) => {
       createPage({
         path: i === 0 ? `/tags` : `/tags/page/${i + 1}`,
         component: path.resolve("./src/templates/tag-list.js"),
         context: {
           limit: postsPerPage,
           skip: i * postsPerPage,
           numPages,  
           currentPage: i + 1,
           tag,
         },
       });
      });

                //createPage({
                //  path: tagPath,
                //  component: path.resolve(`src/templates/tags.js`),
                //  context: {
                //    tag,
                //  },
               // })
    })
  })
}
```

**Comment by emmadigital** [comment]
Below is tags.js file

```
import React from 'react'
import { Helmet } from 'react-helmet'
import { Link, graphql } from 'gatsby'
import Layout from '../components/Layout'

class TagRoute extends React.Component {
  render() {


    const posts = this.props.data.allMarkdownRemark.edges

    const { currentPage, numPages } = this.props.pageContext
    const isFirst = currentPage === 1 
    const isLast = currentPage === numPages
    const prevPage = currentPage - 1 === 1 ? "/" : (currentPage - 1).toString()
    const nextPage = (currentPage + 1).toString()

    
    const postLinks = posts.map((post) => (
      <li key={post.node.fields.slug}>
        <Link to={post.node.fields.slug}>
          <h2 className="is-size-2">{post.node.frontmatter.title}</h2>
        </Link>
      </li>
    ))
    const tag = this.props.pageContext.tag
    const title = this.props.data.site.siteMetadata.title
    const totalCount = this.props.data.allMarkdownRemark.totalCount
    const tagHeader = `${totalCount} post${
      totalCount === 1 ? '' : 's'
    } tagged with “${tag}”`

    return (
      <Layout>
        <section className="section">
          <Helmet title={`${tag} | ${title}`} />
          <div className="container content">
            <div className="columns">
              <div
                className="column is-10 is-offset-1"
                style={{ marginBottom: '6rem' }}
              >
                <h3 className="title is-size-4 is-bold-light">{tagHeader}</h3>
                <ul className="taglist">{postLinks}</ul>
                <p>
                  <Link to="/tags/">Browse all tags</Link>
                </p>
              </div>
              <ul
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            marginBottom: '2rem',
            marginTop: '2rem',
            alignItems: 'center',
            listStyle: 'none',
            padding: 0,
            marginLeft:'0%',
          }}
        >
       
         {currentPage === 2 ? (
            <Link to={`/tags/${tag}`} rel="prev">
              ← Previous Page
            </Link> )
        : !isFirst && (
            <Link to={`/tags/${tag}/page/${prevPage}`} rel="prev">
              ← Previous Page
            </Link>
          )}
          {Array.from({ length: numPages }, (_, i) => (
            <li
              key={`pagination-number${i + 1}`}
              style={{
                margin: 0,
              }}
            >
              <Link
                to={`/${i === 0 ? `/tags/${tag}` : `/tags/${tag}/page/${i + 1}`}`}
                style={{
                  padding: '0.42rem',
                  textDecoration: 'none',
                  color: i + 1 === currentPage ? '#ffffff' : '',
                  background: i + 1 === currentPage ? '#007acc' : '',
                }}
              >
                {i + 1}
              </Link>
            </li>
          ))}
          {!isLast && (
            <Link to={`/tags/${tag}/page/${nextPage}`} rel="next">
              Next Page →
            </Link>
          )} 
        </ul>  
            </div>
          </div>
        </section>
      </Layout>
    )
  }
}

export default TagRoute

export const tagPageQuery = graphql`
  query TagPage($tag: String, $skip: Int!, $limit: Int!) {
    site {
      siteMetadata {
        title
      }
    }
    allMarkdownRemark(
      limit: $limit
      skip: $skip 
      sort: { fields: [frontmatter___date], order: DESC }
      filter: { frontmatter: { tags: { in: [$tag] } } }
    ) {
      totalCount
      edges {
        node {
          fields {
            slug
          }
          frontmatter {
            title
          }
        }
      }
    }
  }
`

```

**Comment by emmadigital** [comment]
Hi @herecydev any suggestions how to make it work.

**Comment by herecydev** [comment]
@emmadigital I'm happy to help but you can't give 3 pages of code and say it doesn't work. So can you provide some further information? Are you saying that the `createPages` isn't working?

**Comment by emmadigital** [comment]
> @emmadigital I'm happy to help but you can't give 3 pages of code and say it doesn't work. So can you provide some further information? Are you saying that the `createPages` isn't working?

thank you @herecydev for your response. Yes its not creating pages that are assoicated with tags. /i have created a repo https://github.com/emmadigital/tagspagination.git that you can check.

**Comment by herecydev** [comment]
Can you list out all the pages that are created and all the pages you want to be created so we can see the issue

**Comment by emmadigital** [comment]
> Can you list out all the pages that are created and all the pages you want to be created so we can see the issue

hi @herecydev its not creating any pages, the page its showing is not related to any tag and it displays tag as undefined here is the screenshot https://prnt.sc/sm27op and when i click on next page it says page not found https://prnt.sc/sm28sn
