### ISSUE TITLE
post-build.js should be moved into gatsby-node.js

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#239]
Keep things simple. All node APIs in gatsby-node and all browser APIs in gatsby-browser.

**Comment by LukeSheard** [comment]
This seems simple enough, I'd be happy to give this a go. Would you want to keep the existing `lib/utils/post-build.js` or move it in to `lib/isomorphic/gatsby-node.js`?

**Comment by KyleAMathews** [comment]
Sorry this issue wasn't super clear. Right now if you add a `post-build.js` file into the root of your site, Gatsby will try to require that and call its function after all building is finished. See https://github.com/gatsbyjs/gatsby/blob/45ed32d7e5d6e90271fe4334e29829c7642c682e/lib/utils/build.js#L13

So the work to be done here is to move this API to `gatsby-node.js` so if you want to do some work after the site is built, you'd export a function in `gatsby-node.js` like `export.postBuild = (pages, cb) => // do some work`.

Make sense?

Thanks!
