### ISSUE TITLE
code highlighting seems to be broken with gatsby-transformer-asciidoc

### ISSUE THREAD

**Issue by maiksensi** [gatsbyjs/gatsby#23903]
# Description

When using gatsby (2.21.13) with gatsby-transformer-asciidoc (1.3.1) code highlighting seems to be broken. 

### Steps to reproduce

* Clone: `git clone https://github.com/maiksensi/gatsby-asciidoc-issue-reproducer`
* Install dependencies: `npm install`
* Run project: `npm start`

### Expected result

When accessing `localhost:8000/about/` the source code block should be highlighted because I added `:source-highlighter: highlightjs` as an attribute.

### Actual result

The source code block is not highlighted. 

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 3.8.1 - /Users/maiksensi/.pyenv/shims/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.21.13 => 2.21.13
    gatsby-source-filesystem: ^2.3.1 => 2.3.1
    gatsby-transformer-asciidoc: ^1.3.1 => 1.3.1
```

# Comment

I also tried adding highlight.js (https://highlightjs.org/usage/) via helmet to the head and I tried to just add it as a es6 module and load the syntax highlighting via `useEffect` which didn't work. 

When exporting this file to html via `asciidoctor about.adoc` highlighting is successfully applied. 

Please let me know if I can help in any way to track this down further.

**Comment by maiksensi** [comment]
I digged a bit more into this, and it seems that this is a problem of asciidoctor.js. If I convert a file with a little script `convert.js`: 

```
const fs = require("fs")
const asciidoctor = require("asciidoctor")()
const content = `= This is a hello
:source-highlighter: highlightjs


Some text

== Second title
[source,javascript]
----
export fun = () => {
  console.log("This is fun");
}
----

more fun.`
console.log(asciidoctor.convert(content))
```

run this via: `node convert.js`

then the output is different from the one I get when using `asciidoctor` directly. Especially, the highlightjs cdn stuff is not added. 

I am not so sure anymore this is a bug of the plugin :(. Still I tried to add the styles via helmet and other methods that didn't work out well. 

Feel free to close this if you feel this is not related to the plugin and should be taken care of in the asciidoctor.js issue tracker.

**Comment by maiksensi** [comment]
Got it working with: 

`about.adoc`
```
= This is a hello

Some text

== Second title

[source,javascript]
----
export fun = () => {
  console.log("This is fun");
}
----

more fun.
```

`about.js`
```
import { graphql } from "gatsby"
import React, { useEffect } from "react"
import hljs from "highlight.js"
import "highlight.js/styles/github.css"

export default function About({ data }) {
  useEffect(() => {
    document.querySelectorAll("pre code").forEach(block => {
      hljs.highlightBlock(block)
    })
  })

  const about = data.asciidoc

  return (
    <>
      <h1>{about.document.title}</h1>
      <div dangerouslySetInnerHTML={{ __html: about.html }} />
    </>
  )
}

export const query = graphql`
  query($slug: String!) {
    asciidoc(fields: { slug: { eq: $slug } }) {
      html
      document {
        title
      }
    }
  }
`
```

Please let me know if I should update the docs (and if so where is the appropriate place) to point out that: 

* syntax highlighting is not directly supported via the plugin because asciidoctor.js is not respecting the attribute
* adding a use effect hook does the trick 

Are there cleaner solutions?

**Comment by pieh** [comment]
I think this tracks to upstream issue https://github.com/asciidoctor/asciidoctor.js/issues/427 . This seems to be solved in later versions ( requiring major version bump for our dependency and actually package rename - from `asciidoctor` to `@asciidoctor/core` ). Then support for highlighting could be added with https://github.com/jirutka/asciidoctor-highlight.js (probably also would need to happen in plugin).

I'm not sure how to approach documentation part. The code highlighters currently are not supported and it would require upgrades in the plugin to fix it. The workaround I don't feel comfortable suggesting because `highlight.js` is quite heavy - https://bundlephobia.com/result?p=highlight.js@10.2.1 (252kB min gzipped currently) and that's a lot for users to download when visiting sites.

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v4 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

[reproduction]: https://gatsby.dev/reproduction
