### ISSUE TITLE
Question: How do you query WordPress posts?

### ISSUE THREAD

**Issue by akmur** [gatsbyjs/gatsby#2390]
Hi, I've been searching for hours, and I'm pretty new to Gatsby and GraphQL. I just can't understand how to filter the AllWordpressPost query by specific wordpress_id.
Is it at all possible?

I have gone as far as this (which doesn't work):

```
allWordpressPost(filter: {wordpress_id: {eq: 1297}}) {
  edges {
    node {
      id
      wordpress_id
    }
  }
} 
```

In this case I get no error message, but the result is 

```
{
  "data": {
    "allWordpressPost": null
  }
}
```

While I am sure that a post with the ID of 1297 does exist, because if I query without filter, the first result is:

```
  "data": {
    "allWordpressPost": {
      "edges": [
        {
          "node": {
            "id": "36f4f805-f47a-54b4-8aeb-fdd32530e8c2",
            "wordpress_id": 1296
          }
         ...
```

Any help would be greatly appreciated.
Thanks!

**Comment by akmur** [comment]
I was using the wrong ID :)

**Comment by interactiveRob** [comment]
For anyone else who comes upon this, you can also query the wordpressPage or wordpressPost object like so.
```
query staticFrontPage($frontpage_id: Int = 5){
 	wordpressPage (wordpress_id: {eq: $frontpage_id}){
		id
		title
		acf {
			hero_headline
		}    
   }
	site {
		id
		siteMetadata {
		  title
		}
	}
}
```
