### ISSUE TITLE
Markdown pages not styled correctly

### ISSUE THREAD

**Issue by cjdunteman** [gatsbyjs/gatsby#23908]
I am having trouble getting my markdown pages to render correctly. The text is appearing, but is not formatted like Markdown. It is plain html. 

I tried removing all my styles to see if that was an issue and it did not work.

My repo is [here](https://github.com/cjdunteman/cliff-codes)

**Comment by DSchau** [comment]
@cjdunteman thanks for letting us know!

I think you'll want to use `gatsby-remark-prismjs` to get that syntax highlighting. You can see how that works [here](https://using-remark.gatsbyjs.org/code-and-syntax-highlighting/).

Thanks for using Gatsby 💜
