### ISSUE TITLE
How to use Restful API when createPages

### ISSUE THREAD

**Issue by richardhsueh** [gatsbyjs/gatsby#23902]
I was trying to static site generate a FAQ list, but my source of data are 3 RESTful API.

`/{language}/{system}/categories` // this will get the full list of categories
`/{language}/{system}/faq?categoryId={categoryId}` // this will get eh full list of FAQ under the given category id
`/{language}/{system}/faq/{id}` // this will get the FAQ of the given FAQ id

And I am not sure how to do it.

## Summary
1. Can I just use `axios` to call the api and use the api respond data to create page inside `export.createPages` ?
2. Do I need to use `createNode` or anything else ?
3. If not, then what is the purpose of `createNode`, under what circumstances it is required ?

Thank you.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by herecydev** [comment]
Sounds like you are on the right lines. I would do something similar to:

```js
exports.createPages = async ({ actions }) => {
  const { createPage } = actions
  const result = await getAxiosData()
  createPage({
      path: "pathname",
      component: path.resolve(`./src/templates/your-page.js`),
      context: {
        //data you might need in your page
      },
  })
}
```

`CreateNode` is used for creating graphql nodes. It's worth exploring (and it's really powerful) but it's not a requirement for gatsby.

[This page](https://www.gatsbyjs.org/docs/why-gatsby-uses-graphql/) explains some of the steps nicely.

**Comment by richardhsueh** [comment]
@herecydev Firstly, thank you for your answer. I think I know what to do next.
But can you explain a little bit more on when do we need to create graphql nodes ? I am still very confused. 🤔

**Comment by herecydev** [comment]
Yer that's fine. As I said there's no requirement to use graphql.

In a way you can think of it as 2 different ways to achieve the same thing, you could:

1. Use the restful api call and pass that into the pageContext to create a page. This is a really simple approach but has some drawbacks; there might be too much data that isn't all needed (overfetching) and if other pages need to share the data it can complicate things.

2. Use the restful api call and create graphql nodes using `createNode`, then create pages that query the graphql system. Slightly more work up-front, but it doesn't suffer the drawbacks of the other approach. You can also do some [limited filtering/sorting/etc](https://www.gatsbyjs.org/docs/graphql-reference/) of data

It might be helpful to read through [this page](https://www.gatsbyjs.org/docs/creating-a-generic-plugin/)

**Comment by richardhsueh** [comment]
I see, thanks a lot. 👍
