### ISSUE TITLE
Consuming graphqlRunner in onCreatePage

### ISSUE THREAD

**Issue by herecydev** [gatsbyjs/gatsby#23900]
## Summary

It would be beneficial to consume grapqhl in the `onCreatePage` hook. #21611 has answered part of why this isn't available. @pieh had said:

> it has some scaling problems associated with it - the onCreatePage doesn't run concurrently - it will always run one by one now. So we will be limited to executing single query at a time (as opposed to things like page queries where we execute many of them concurrently). It can quickly become bottleneck.

I want to present the following use case of where consuming graphql would be advantageous

## i18n example

Using [the gatsby i18n example](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-i18n) as a reference, it uses the `onCreatePage` hook to recreate the page with the locale prefixed, for example `/apples` would become `/en-us/apples`. If the user wants the path to also be localized, such that `/apples` could become `/fr-fr/pommes` then querying graphql would be helpful.

## Discussion

@pieh does the following still hold true:

> the onCreatePage doesn't run concurrently - it will always run one by one now.

From a quick test of using `onCreatePage` and adding an async timeout, I can see that `onCreatePage` is called for all my pages simultaneously and a timeout of 5s doesn't "stack up".

**Comment by arjunvegda** [comment]
Any update on this? I want to leverage from Gatsby's default mechanism of creating pages and just update the slugs (for different languages) from CMS. Having access to graphQL on onCreatePage would make this super easy.

**Comment by LekoArts** [comment]
Thank you for opening this!

This still holds true and we probably also won't change it for the reasons my colleague mentioned.

As for your i18n example: You should change this in the `exports.createPages` step. It's the best place there in my opinion and doable.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by herecydev** [comment]
@LekoArts Can you elaborate further on how you would see that happen?

It currently works:
1. User creates pages
2. Plugin will interecept using onCreatePage (and recreate them with localized url)
 
At this point we want to present the user an opportunity to localize the url from graphql. I just don't see how to "move it to exports.createPages" step without pushing responsibility back to step 1, which negates the whole point of having a plugin

**Comment by LekoArts** [comment]
There is no need to have access to GraphQL at this stage.

If you want `/apples` to become `/fr-fr/pommes` then you could let the user pass in some sort of dictionary or better let them handle it themselves. Because they already have access to that information in their `createPages` step. 

If you would want to access GraphQL in `onCreatePage` what would you request? 
A list of translations? (Doable with pluginOptions)
The list of all pages?

You can't make your plugin agnostic to any way of creating pages so pushing that responsibility to the individual page is the only sensible way at the moment.

**Comment by herecydev** [comment]
Ideally I want to provide a hook to allow the user to receive something like `{ locale: "fr-FR", path: "/apples" }` and they can return the appropriate transaltion by querying the graphql.

I've considered using pluginOptions but as I understand that has to be known statically, i.e. before the graphql is built

**Comment by herecydev** [comment]
Similar to how `gatsby-plugin-sitemap` allows a callback that can be used to query stuff

**Comment by LekoArts** [comment]
I see.

Yeah, this isn't possible as overall gatsby-config is sync and you can't make requests there, too.

**Comment by herecydev** [comment]
@LekoArts Would you be willing to discuss an additional api in the build step? https://www.gatsbyjs.org/docs/overview-of-the-gatsby-build-process/#steps-of-the-bootstrap-phase

If there was a step between 12 - building schema and 13 - creating pages, something like `onPreCreatePages` that fires as a 1 time event. If that was given the graphql runner, it would allow plugins to gather schema related information.

**Comment by LekoArts** [comment]
You can use `createResolvers` as it's run last in the schema generations step: https://www.gatsbyjs.org/docs/node-apis/#createResolvers

**Comment by herecydev** [comment]
That's an interesting idea, it might be a bit "raw" though. I don't think you would be able to perform graphql queries in that method because there is no runner, and you can't instantiate a `GraphQLRunner` because the schema isn't fully built yet. At least there's the raw nodes.

Can you think of anyway a query can be run there?

**Comment by LekoArts** [comment]
The intermediate schema is available so you can use runQuery :)
https://www.gatsbyjs.org/docs/schema-customization/#accessing-gatsbys-data-store-from-field-resolvers

**Comment by herecydev** [comment]
Hmm, how would you see that working? I see how you can access the schema but that's only called when a query is running and it uses your custom resolver.

So even if you hacked in a new field to query some data, you still need something to call that query 🤔

**Comment by agrohs** [comment]
What caused this to get closed?
