### ISSUE TITLE
[gatsby-plugin-sharp] Wrong (max-width) values

### ISSUE THREAD

**Issue by LeKoArts** [gatsbyjs/gatsby#2391]
Hi!
While using gatsby-image and therefore using gatsby-plugin-sharp I noticed that I don't get my desired (max-width) set on the image. My use case:

- I have high resolution images on my harddrive (artworks etc.) which I resize before
- The images have a width of 1200px
- I set the maxWidth in the query to 1200 like so:
`sizes(maxWidth: 1200)`
- The output gives me something like this:
`sizes="(max-width: 288px) 100vw, 288px"`

**Why doesn't it get set to 1200px?**

I also tried it with other images which had a width of ~ 3000px. Even there the max-width gets set to 1191px.

Do I miss something obvious or should these lines get altered?

https://github.com/gatsbyjs/gatsby/blob/104ad1ef71025afd19b8b76cf8db73b3719ce612/packages/gatsby-plugin-sharp/src/index.js#L361-L375

**Comment by KyleAMathews** [comment]
We're discussing this at https://github.com/gatsbyjs/gatsby/issues/2292

Would love to hear your thoughts there on how to resolve the issue.
