### ISSUE TITLE
refactor (www): Make gatsby-transformer-gatsby-api-calls a standalone plugin.

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#23928]
## Description

Make `www/plugins/gatsby-transformer-gatsby-api-calls` its own plugin.

## Motivation

Precursor of #23926 

Currently `gatsby-transformer-gatsby-api-calls` is a local plugin that defines an `apiCall` endpoint in the content mesh. This endpoint is called in our API reference pages.

We are factoring out gatsbyjs.org into a theme to facilitate translations. Themes cannot have their own local plugins, which means that for local plugins, our choices are:

1. keep the plugin in the skeleton `www` implementation
2. make the plugin standalone

For something like `gatsby-perf-metrics`, another local plugin in www, option 1 is feasible because excluding the plugin from the translated repos won't cause the site to fail. For `api-calls` however, this won't work: because the plugin defines an endpoint on the site, the site will fail if the plugin is not included. Therefore, our only option to keep our current functionality is 2, making the plugin standalone.

**Comment by copperwall** [comment]
I'm up to work on this if that's cool
