### ISSUE TITLE
CLI: `gatsby new` without arguments produce errors

### ISSUE THREAD

**Issue by melanieseltzer** [gatsbyjs/gatsby#23927]
## Description

When running `gatsby new` without arguments I get errors. From what I read in the [docs](https://www.gatsbyjs.org/docs/gatsby-cli/#examples), it's supposed to run an interactive shell asking for inputs?

It also never asked for my preferred shell like documented [here](https://www.gatsbyjs.org/docs/gatsby-cli/#how-to-change-your-default-package-manager-for-your-next-project) (it's the first time I ran `gatsby new` after installing the cli). So I've been unable to choose my package manager.

```bash
~/Sites 51s
❯ gatsby new
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-default.git
fatal: destination path '/Users/melleh/Sites' already exists and is not an empty directory.
error Command failed: git clone https://github.com/gatsbyjs/gatsby-starter-default.git /Users/melleh/Sites --single-branch


  Error: Command failed: git clone https://github.com/gatsbyjs/gatsby-starter-default.git /Users/melleh/Sites --single-branch
  
  - index.js:236 
    [lib]/[gatsby-cli]/[execa]/index.js:236:11
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18
  
  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18
  
  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19
  
  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14
  
  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18
  
  - async.js:138 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12
  
  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9
  
  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5
  
  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
```

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

Launch the interactive shell asking to name the project and choose a starter.

### Actual result

Errors out, no interactive shell.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```bash
System:
    OS: macOS 10.14.6
    CPU: x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v12.7.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 72.0.2
    Safari: 13.1
  npmGlobalPackages:
    gatsby-cli: 2.12.15
```

**Comment by LekoArts** [comment]
Hi!

Can you ugprade the CLI to the latest version (re-run `npm install -g gatsby-cli`)? I tried it in my playground folder and it works.

However, your error indicates that you didn't run `gatsby new` but something in the realms of `gatsby new <some-code>`. Because when I run `gatsby new .` it throws a similar error:

![image](https://user-images.githubusercontent.com/16143594/81813537-e0713480-9527-11ea-8931-08c03572d26f.png)

So could you make sure that you don't have a <kbd>Space</kbd> behind the `new` or try it in another folder?

**Comment by melanieseltzer** [comment]
@LekoArts Upgrading the cli seems to have worked, although I did install it fresh 5 days ago 🤔 Weird, but yes it's working! I can run `gatsby new` anywhere.

**Comment by LekoArts** [comment]
Awesome!
