### ISSUE TITLE
maintenance(docs): remark-preset-lint-gatsby-style-guide

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#23929]
## Summary

Move the rules defined in our [remarkrc](https://github.com/gatsbyjs/gatsby/blob/master/.remarkrc.js) to a package `remark-preset-lint-gatsby-style-guide`

### Motivation

As we add more rules (#23692) to the remark linter and even make our own rules (#20732), we end up cluttering up the top-level workspace with dependencies to remark plugins. Moving these dependencies to one place would clean up our `package.json`.

**Comment by muescha** [comment]
we should wait until #24372 `mainenance(docs): Add retext-spell to check spelling` is merged

**Comment by muescha** [comment]
make it sense to move it now or wait until: #25290  `enhancement (docs): Improvements to retext-spell`?
