### ISSUE TITLE
Disqus Plugin Configuration

### ISSUE THREAD

**Issue by emmadigital** [gatsbyjs/gatsby#23933]
## Summary
I have installed disqus plugin https://github.com/tterb/gatsby-plugin-disqus to my theme, it shows the disqus widget in the blog posts but its not properly linking to the disqus account. I have used correct shortname. The comments are zero on all posts. Whereas there are comments on most of my posts.

## Relevant information

Here is my disqus plugin configuration code https://github.com/emmadigital/ardalis-newsite/blob/master/src/templates/blog-post.js

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by ascorbic** [comment]
Hey. Could you file this issue on [the plugin repo](gatsby-plugin-disqus)? It's a community plugin that isn't maintained by Gatsby.
