### ISSUE TITLE
maintenance(docs): Switch docs formatter from Prettier to customized remark-stringify

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#23931]
## Description

Switch the [docs formatter](https://github.com/gatsbyjs/gatsby/blob/master/package.json#L114) from prettier to [remark-stringify](https://github.com/remarkjs/remark/tree/master/packages/remark-stringify), customized with additional rules.

## Motivation

remark-stringify is extensible and allows users and plugins to [extend the compiler](https://github.com/remarkjs/remark/tree/master/packages/remark-stringify#extending-the-compiler) with changes. We need this flexibility to do things such as auto-generating heading IDs to docs (#20732).

## Issues

The default remark-stringify won't work for a variety of issues (even with configurations). These can be seen in this diff: https://github.com/gatsbyjs/gatsby/compare/remark-stringify?expand=1

* Doesn't understand codeblock titles generated with [`gatsby-remark-code-titles`](https://www.gatsbyjs.org/packages/gatsby-remark-code-titles/): it escapes the underscores in the title and parses the title as part of the language block.
* Adds `<>` to URLs (e.g. `https://youtube.com` becomes `<https://youtube.com>`). (I think) This interferes with [`gatsby-remark-embedder`](https://www.gatsbyjs.org/packages/gatsby-remark-embedder), which requires the raw URLs to embed Youtube and Giphy links.
* Doesn't support code formatting in links (it escapes tildes)

Minor difference from Prettier:

* Doesn't escape dollar signs (`$`) unless the latex plugin is installed.
* Adds line breaks between link definitions
* Some weird table formatting?

**Comment by capndave** [comment]
I'll start fooling around with this as an exploratory exercise. For anyone else not familiar with [remark-stringify](https://github.com/remarkjs/remark/tree/master/packages/remark-stringify), the [unified](https://unifiedjs.com/learn/guide/introduction-to-unified/) docs seem like a good place to start.

**Comment by capndave** [comment]
@tesseralis a couple questions re: linting/formatting pipeline that occurs now. I do see that `husky` and `lint-staged` currently call `prettier --write` to lint staged markdown files, and assume that circleCI or something calls the `lint` script . I guess my questions are:

1. You want to run remark-stringify just on changes to markdown files in the docs dir, correct?
2. Any idea what's going with line 134 of `package.json`? 
```
"lint:docs": "remark --quiet --frail \"./docs/\""
```
3. Do you think formatting will need to be kicked off as part of both `lint-staged` and `lint`, or just one of them?

Thanks!

**Comment by tesseralis** [comment]
@capndave 

1. Correct, we only want to run remark-stringify on markdown files in the docs dir
2. We're using remark to lint the docs but prettier to format them
3. Remark-stringify should be used in in the `lint-staged` command. A new `format:docs` command should be added that runs remark-stringify on the docs, and it should be added to the `format` script.

**Comment by muescha** [comment]
the escape of dollar sign can stay disabled, because on gatsbyjs.org its not "reescaped" on website

**Comment by capndave** [comment]
@tesseralis I think it will be trivial to make an extension or plugin to remove angular brackets from urls at the end of whatever other unified/remark pipeline, but not to keep them from getting introduced in the first place. See [here](https://github.com/remarkjs/remark-lint/issues/47) and [here](https://github.com/remarkjs/remark/issues/208). Is there case where we wouldn't want to remove angular brackets after they've been added?

**Comment by muescha** [comment]
since `prettier` is based on `unified` and `remark` - maybe the `prettier` engine is customizable with plugins, so we get our styling done without switching complete to an own solution?

**Comment by muescha** [comment]
not stale
