### ISSUE TITLE
How can I copy any files into public from .md .mdx?

### ISSUE THREAD

**Issue by muukii** [gatsbyjs/gatsby#23935]
## Summary

Hello,
First of all, thank you for beautiful tool.

I have a question about generate file path while creating a page from MDX.
Image or any file link are supported by gatsby-remark-copy-linked-files
However, I'd like to pass some file url to my local React Component.
Technically, that component create video tag inside and provides some controls.
So I'd like to write like following:

my-post.mdx
```mdx
<MyVideo src={"./video.mp4"} />
```

Component
```tsx
import React from "react"

type Props = {
  src: string
}

export const Video = (props: Props) => {
  return <video src={props.src} />
}
```

however, the file url won't be converted valid url such as a link that gatsby-remark-copy-linked-files creates.
I know this plugin does not support this syntax.

So Does anyone know some plugin to convert url to valid url with any syntax?

Thanks

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

What you're asking for isn't possible at the moment. You could import the video in the MDX file with `import Video from "./video.mp4"` and pass that `Video` to the component.
Alternatively you'll need to place this file in the `static` folder and reference it this way.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
