### ISSUE TITLE
Use Sharp Fragment in Sitemap plugin

### ISSUE THREAD

**Issue by D0m3-** [gatsbyjs/gatsby#23940]
## Summary

I want to reuse Sharp Fragment to index the images that I show on my pages. I have declared the plugins in correct order and the query works fine in my pages but not in the sitemap plugin config.

I get Error: Unknown fragment "GatsbyImageSharpFluid".

How can I solve that?

## Relevant information

```
{
    resolve: `gatsby-plugin-sitemap`,
    options: {
      exclude: [`/success`],
      query: `
        {
          site {
            siteMetadata {
              siteUrl
            }
          }

          allSitePage {
            nodes {
              path
            }
          }
          allStripeProduct {
            nodes {
              localImages {
                childImageSharp {
                  fluid(maxWidth: 800) {
                    ...GatsbyImageSharpFluid
                  }
                }
              }
            }
          }
      }`,
      serialize: ({ site, allSitePage, allStripeProduct }) =>
        allSitePage.nodes
          .map(node => {
            return {
              url: `${site.siteMetadata.siteUrl}${node.path}`,
             // TODO img
            }
          })

    }
  }
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by ascorbic** [comment]
Hi. Unfortunately we don't support fragments inside gatsby-node (which is where these queries are executed). This is a known issue. #12155 

In the meantime, you could copy the contents of the fragments from https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/fragments.js

**Comment by D0m3-** [comment]
Thanks for the info
