### ISSUE TITLE
Gatsby requires Node.js v8 or higher (you have v15.0.0-pre)

### ISSUE THREAD

**Issue by jrgleason** [gatsbyjs/gatsby#23945]
When I try to build NPM from source using a locally compiled version of Node I get...

>Gatsby requires Node.js v8 or higher (you have v15.0.0-pre)

I can delete the reference in `.//docs/node_modules/gatsby/node_modules/gatsby-cli/lib/index.js` and manually remove the check it works.

**Comment by capndave** [comment]
It's weird that the error message suggests you're using Node v15 (which isn't supposed to be released til October)! Can you tell me the results of `node --version`?

**Comment by ascorbic** [comment]
Gatsby is behaving as expected. The required version in the latest CLI is set as ">=10.13.0", which is not satisfied by "15.0.0-pre". See [the checker](https://jubianchi.github.io/semver-check/#/%3E%3D10.13.0/15.0.0-pre). Whether this _should_ be the behaviour is another question. Perhaps we should specifically allow prerelease versions. In any case, as you probably expect, we're not going to support v15 until it's released, so I'm going to close this ticket.
