### ISSUE TITLE
There is no flag --log-pages in my gatsby build command

### ISSUE THREAD

**Issue by laurenskling** [gatsbyjs/gatsby#23941]
## Summary

at https://www.gatsbyjs.org/docs/page-build-optimizations-for-incremental-data-changes/#reporting-what-has-been-built it is writting I can use a `--log-pages` flag. But my cli says that flag does not exist. I tried different recent versions of gatsby.

**Comment by albertlincoln** [comment]
I ran into the same issue - the code is in gatsby but not gatsby-cli. I've fixed it here:

https://github.com/gatsbyjs/gatsby/pull/23951

**Comment by adriandmitroca** [comment]
I'm pretty sure this flag existed in the past.

Is there any new equivalent? I couldn't find anything related to this change in the changelog.

**Comment by clementhk** [comment]
> I'm pretty sure this flag existed in the past.
> 
> Is there any new equivalent? I couldn't find anything related to this change in the changelog.

Same here, my daily build just failed.

**Comment by clementhk** [comment]
Broke by gatsby@2.21.21 2 days ago.

**Comment by clementhk** [comment]
The build logic is changed and converted to ts, that's probably why? Hopefully nothing else broke.

**Comment by pieh** [comment]
Hey folks. We just released `gatsby-cli@2.12.16` / `gatsby@2.21.22` (thanks to PR by @albertlincoln  ). Updating should fix this problem
