### ISSUE TITLE
Unnecessary CSS included in html files when using SCSS modules leading to bloated HTML files

### ISSUE THREAD

**Issue by kokokenada** [gatsbyjs/gatsby#23942]
###  Description
* The app uses CSS Modules.  As normal there is a <file>.module.scss associated with the .tsx file and a related import styles from './styles.module.scss';  
* The app runs fine and all the styles are present
* However, the generated files are very big (e.g. 250KB) of which most is CSS in a style element (e.g. after running prettier on the output in public/ there are 11500 lines and the first 11300 lines are in the style element
* As an example, there is a stepper component with stepper styles.  The stepper styles appears in every html file in the public directory, even though it is defined only in style.module.scss in the stepper component directory and imported only there.

Describe the issue that you're seeing.

### Steps to reproduce

This is the portion of gatsby.config.js for (not that it should matter)
````
    {
      resolve: 'gatsby-plugin-sass',
      options: {
        useResolveUrlLoader: {
          options: {
            debug: true,
            sourceMap: true,
          },
        },
      },
    },
````

### Expected result

The generated html files should only include CSS from scss files that were explicitly imported instead of every scss file in the tree.

### Actual result

Each generated html file included CSS from everywhere in the project

### Environment

  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.0.4
  npmGlobalPackages:
    gatsby: 2.20.2

**Comment by herecydev** [comment]
[It's an oversight that the team is aware of](https://github.com/gatsbyjs/gatsby/issues/21253)

Maybe you can add the potential fix and see if it works for you. Let us know here!

**Comment by kokokenada** [comment]
@herecydev - thanks for the reply!  The fix worked for me! The public directory is significantly smaller. It also got rid of some annoying build warnings that I couldn't figure out. The following errors use to show up in the build and now they're gone:
````
Conflicting order. Following module has been added:
 * css ./node_modules/css-loader??ref--14-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/resolve-url-loader??ref--14-oneOf-0-3!./node_modules/sass-loader/dist/cjs.js??ref--14-oneOf-0-4!./src/components/Forms/for
m-container/styles.module.scss
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader??ref--14-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/resolve-url-loader??ref--14-oneOf-0-3!./node_modules/sass-loader/dist/cjs.js??ref--14-oneOf-0-4!./src/layouts/Footer/style
s.module.scss
   - couldn't fulfill desired order of chunk group(s) component---src-pages-admin-tsx, component---src-pages-contact-us-tsx, component---src-pages-edit-payment-tsx
   - while fulfilling desired order of chunk group(s) component---src-pages-change-password-tsx, component---src-pages-my-account-tsx, component---src-pages-sign-up-tsx, component---src-pages-subscribe-tsx
````

**Comment by herecydev** [comment]
Glad it helped! 

@wardpeet hope this information if of some use. Would it be helpful to put a disclaimer in some of the documentation about this. For a lot of people, I think the assumption would be that using css modules would provide the correct isolation and this is kind of issue is fairly frequently raised.

**Comment by ascorbic** [comment]
Thanks for handling this, @herecydev. I'm goign to close this as a duplicate, but also flag this as a potential documentation and/or webpack issue.
