### ISSUE TITLE
[gatsby-source-shopify] — Limit products in ShopifyCollection

### ISSUE THREAD

**Issue by tizzle** [gatsbyjs/gatsby#23958]
## Summary

Wouldn't it be great to limit the number of products pulled in when querying a collection in the gatsby-source-shopify plugin? This would reduce the size of the generated page-data.json files, making page load and prefetching even faster.

### Basic example

```
myCollection: shopifyCollection(handle: { eq: "kitchen" }) {
  handle
  products(limit: 18) {
    edges {
      node {
        id
      }
    }
  }
}
```

### Motivation

Speed. And thrift.

Right now the plugin pulls in all the products in a collection. Say you only want to tease a collection by showing two or three products on a shop overview page and give the user the option to drill deeper. Right now i get rather largish page-data.json files that include all the queried data, although i will never use it.

We could do the same for images as well. Sometimes i don't need more than one image of a product or category.

**Comment by ascorbic** [comment]
Interesting idea. It would require changing `products` to be a custom resolver. You could add that field yourself with a [createResolvers](https://www.gatsbyjs.org/docs/schema-customization/#createresolvers-api) function inside your gatsby-node. A simpler, if less elegant way is to query the get the products list in `createPages`, and then pass the list of ids through to the template in context. You could then grab that list of products in the page query, alongside the collection. e.g (not tested):

```js
exports.createPages = async function createPages({ actions, graphql }) {
  const result = await graphql(`
    {
  allShopifyCollection {
    nodes {
      products {
        id
      }
      handle
      id
    }
  }
}
  `)

  const collectionTemplate = path.resolve(`src/templates/product.js`)

  result.data.allShopifyCollection.nodes.forEach(({handle, id, products}) => {
    actions.createPage({
      component: productTemplate,
      path: `collections/${handle}`,
      context: {
        id,
        products: products.map(product => product.id)
      },
    })
  })
}

```


...and then in the page template:

```js
export const collectionQuery = graphql`
  query CollectionQuery($id: String!, $products: [String!]!) {
    products: allShopifyProduct(filter: {id: {in: $products}}, limit: 10) {
nodes {
      //etc
    }

    }
   myCollection: shopifyCollection(id: { eq: $id }) {
  handle
  //etc
  }
}

  }
`

```
Or you could slice the id list before passing it in context. Give that a go

**Comment by tizzle** [comment]
Hey @ascorbic,

thanks for the detailed feedback. I think i will try to go the way of the custom resolver, as i would like to keep my context as slim as possible.

Do you think this functionality could sooner or later find its way into the plugin? I assume it should be discussed in more breadth, as this would be a breaking change.

I would build this in gatsby-node first and then – if there's interest – create a PR for the plugin as well.

Best regards and thanks again for the quick reply!

**Comment by ascorbic** [comment]
@smthomas what do you think? Would this be worth adding to the plugin?

**Comment by angeloashmore** [comment]
As an aside, it would be nice to have generic resolvers that allowed limit, sort, skip, etc. on array values. Something like a `@listOperators` directive:

```graphql
type ShopifyCollection {
  products: [ShopifyProduct] @listOperators
}
```

Something like that could benefit other source plugins.

**Comment by Haven3** [comment]
Hey @tizzle,

Have you had any luck with your custom resolver? I am trying to limit the number of product images I pull in on collection pages but I have not had any luck yet.

**Comment by tizzle** [comment]
Hey @Haven3,

I only started looking into this yesterday, but found the documentation on doing this was a bit incomplete. The place i struggled most was creating ConnectionTypes. The documentation on this is unfortunately outdated and i was not really able to dive into the Gatsby source to figure out how this is handled.

Sorry for such little information, maybe someone — who is more experienced and reading along — can enlighten me a bit :)

Maybe you could share your approach?

**Comment by Haven3** [comment]
I wish I had something to offer! This is new territory for me. I’ve been going through the documentation trying out different scenarios but nothing has worked yet unfortunately. 

I have collection pages that show the first image of each product. Unfortunately, having to pull in all images means, 150-200 products Per collection with 5-15 images for each item! Page-data.json files are getting pretty large…

I may just try to narrow down the data I need in my Gatsby-node file and then pass it through context. Not ideal but maybe it will work. :)

**Comment by jasonbiondo** [comment]
Does anyone actually have any idea on how to create resolvers?  The documentation on this is incomplete.

**Comment by brvnonascimento** [comment]
> Does anyone actually have any idea on how to create resolvers? The documentation on this is incomplete.

I'm struggling with the same problem as jasonbiondo and tizzle.

**Comment by wphowto** [comment]
Any update no this? I am struggling to get this to work.

**Comment by connordowson** [comment]
I got this to work [using this](https://github.com/gatsbyjs/gatsby/discussions/28126#discussioncomment-162057)

```js
exports.createResolvers = ({ createResolvers }) => {
  createResolvers({
    ShopifyCollection: {
      // Add products from the selected section(s)
      products: {
        args: {
          limit: `Int`,
        },
        resolve: async (root, args, context, info) => {
          const allProductsInCollection =
            (await info.originalResolver(root, args, context, info)) || []

          return args.limit
            ? allProductsInCollection.slice(0, args.limit)
            : allProductsInCollection
        },
      },
    },
  })
}
```
