### ISSUE TITLE
gatsby-plugin-typography doesn't handle pathToConfigModule in theme 

### ISSUE THREAD

**Issue by anindha** [gatsbyjs/gatsby#23950]
## Description

I am trying to use `gatsby-plugin-typography` with a theme but the `pathToConfigModule` seems to searching in the site directory rather than the theme directory.

### Steps to reproduce

1. `git clone https://github.com/lamnohq/gatsby-theme-typographyjs-bug.git`
2. `yarn workspace example develop`

### Expected result

The plugin should read the typography.js file in the theme directory.

### Actual result

The plugin seems to be looking in the site directory. 

Error:
```
 ERROR #98124  WEBPACK

Generating SSR bundle failed

Can't resolve '/Users/anindha/Code/gatsby/gatsby-theme-typographyjs-bug/example/src/utils/typography' in '/Users/anindha/Code/gatsby/gatsby-theme-typographyjs-bug/example/.cache/caches/gatsby-plugin-typography'

Perhaps you need to install the package '/Users/anindha/Code/gatsby/gatsby-theme-typographyjs-bug/example/src/utils/typography'?

File: .cache/caches/gatsby-plugin-typography/typography.js
```

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.8.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 72.0.2
    Safari: 13.1
  npmGlobalPackages:
    gatsby-cli: 2.11.22
```

**Comment by ascorbic** [comment]
This issue seems to be that shadowing isn't working properly with the plugin's system of writing the module file out to .cache

**Comment by johno** [comment]
Thanks for opening up an issue @anindha!

The error you're seeing is a result of resolution from your gatsby-config. With themes, the resolution happens from a different directory/context. In order to fix this you can explicitly create a full path from the current directory using `path.join`.

```js
const path = require("path");

module.exports = {
  plugins: [
    {
      resolve: "gatsby-plugin-typography",
      options: {
        pathToConfigModule: path.join(__dirname, `src/utils/typography`),
      },
    },
  ],
};
```
