### ISSUE TITLE
gatsby-plugin-emotion adds styles inside body during build, but on rehidratation styles are moved to the header

### ISSUE THREAD

**Issue by stevemarksd** [gatsbyjs/gatsby#23973]
## Description

gatsby-plugin-emotion adds styles inside body during build, but on rehidratation styles are moved to the header

### Steps to reproduce

Simply use this plugin `gatsby-plugin-emotion` and run build.

### Expected result

im not sure, but should not jump to <head/>

### Actual result

styles are added to <head/>

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.21.9 => 2.21.9 
    gatsby-common: link:../../packages/gatsby-common => 1.0.0 
    gatsby-image: ^2.4.0 => 2.4.0 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-catch-links: ^2.0.9 => 2.3.0 
    gatsby-plugin-emotion: ^3.0.1 => 3.0.1 
    gatsby-plugin-layout: ^1.3.0 => 1.3.0 
    gatsby-plugin-manifest: ^2.0.12 => 2.4.1 
    gatsby-plugin-material-ui: ^2.1.8 => 2.1.8 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.3.0 
    gatsby-plugin-sharp: ^2.0.15 => 2.6.0 
    gatsby-plugin-sitemap: ^2.0.3 => 2.4.1 
    gatsby-plugin-typescript: ^2.0.3 => 2.4.0 
    gatsby-remark-component: ^1.1.3 => 1.1.3 
    gatsby-remark-images: ^3.0.1 => 3.3.0 
    gatsby-source-filesystem: ^2.0.12 => 2.3.0 
    gatsby-transformer-remark: ^2.1.15 => 2.8.4 
    gatsby-transformer-sharp: ^2.1.9 => 2.5.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.7

**Comment by ascorbic** [comment]
Hey. Could you [provide a minimal reproduction][reproduction] so we can look into this further? Rehydration issues like this usually indicate an issue with the SSR HTML.

**Comment by stevemarksd** [comment]
Look on gatsby https://www.gatsbyjs.org/ for the class in source code and the class once is rendererd: `.css-c14scv`

first render is set inside the body, then is moved to the <head> tag

**Comment by wardpeet** [comment]
It can be reproduced with https://github.com/gatsbyjs/gatsby/tree/master/examples/using-emotion

Thank you!

**Comment by riccardogiorato** [comment]
Any news on this issue with emotion @wardpeet ?

**Comment by nagiek** [comment]
+1

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
