### ISSUE TITLE
How to use routing parameter?

### ISSUE THREAD

**Issue by linxianxi** [gatsbyjs/gatsby#23998]
![image](https://user-images.githubusercontent.com/47104575/81646836-87899980-945e-11ea-9a51-09175e87a359.png)

Is this the wrong way to use it？

![image](https://user-images.githubusercontent.com/47104575/81646898-a4be6800-945e-11ea-8e70-84c2e5a0073e.png)

**Comment by herecydev** [comment]
Can you elobarate on what you're trying to achieve?

If you're trying to create different men pages you can try something like:

```
  posts.forEach((post) => {
    createPage({
      path: `men/${post.id}`,
      component: path.resolve(`./src/templates/product.js`),
      context: {
        postData: post
      },
    })
```

But I'm kinda guessing on what you're trying to achieve.

**Comment by linxianxi** [comment]
> Can you elobarate on what you're trying to achieve?
> 
> If you're trying to create different men pages you can try something like:
> 
> ```
>   posts.forEach((post) => {
>     createPage({
>       path: `men/${post.id}`,
>       component: path.resolve(`./src/templates/product.js`),
>       context: {
>         postData: post
>       },
>     })
> ```
> 
> But I need to know a bit more

If I have 10,000 products, this is going to create 10,000 pages, is that good？

**Comment by herecydev** [comment]
> If I have 10,000 products, this is going to create 10,000 pages, is that good？

Depends on your view of good. If you're statically creating 10k pages then the user experience will be blazingly fast. That's the core of what makes gatsby so fast. Of course, you have to make the tradeoffs in your achitecture, i.e. what happens when a product's price changes.

What are you trying to achieve, do you want the product pages to be statically built?

**Comment by LekoArts** [comment]
Thank you for opening this!

If you don't want to statically create them (although we highly recommend it), you should look at: https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
