### ISSUE TITLE
Detect if in Gatsby directory and exit if not

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#24]
It'd be interesting though if not in a Gatsby directory to auto-scan above and below the current working directory for Gatsby sites (glob for a gatsby.config.* file?) This is potentially problematic as could lead to opening 1000s of files. Not sure if node-glob can limit how many directories you look into.

There's also finding modules like https://www.npmjs.com/package/find which might be a better choice. Have to investigate cross-platform compatibility.

**Comment by gesposito** [comment]
Thinking about something like
https://github.com/nodejitsu/require-analyzer

**Comment by KyleAMathews** [comment]
Superseded by #204
