### ISSUE TITLE
How to cache a React library

### ISSUE THREAD

**Issue by sumanthyedoti** [gatsbyjs/gatsby#24003]
I am using [React-fullpage](https://github.com/alvarotrigo/react-fullpage) library. Currently, the library is getting into action with some delay of few seconds depending on bandwidth.

I need to **fetch this library on high priority and cache** it locally so the library comes into action quickly as page loads and consecutive page hits don't download the library again

Please help with a possible ways to do this. 

[Custom Webpack Config](https://www.gatsbyjs.org/docs/add-custom-webpack-config/), caching the library using service-workers without making the website PWA, [Code Splitting and Prefetching](https://www.gatsbyjs.org/docs/how-code-splitting-works/#prefetching-chunks)? Whatever the possible solution to achieve this.

Thanks.

**Comment by herecydev** [comment]
Out the box, I would expect your library to be bundled up and requested as a dependency of your pages. This will result in it being immediately requested and if you've set the `Cache-Control` headers correctly it will be cached forever.

Are you not seeing that behavior?

**Comment by sumanthyedoti** [comment]
I am using `gatsby-plugin-htaccess` plugin with custom rules
```
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE]
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType image/gif "access plus 1 month"
  ExpiresByType image/png "access plus 1 month"
  ExpiresByType image/svg+xml "access plus 1 month"
  ExpiresByType video/mp4 "access plus 1 month"
  ExpiresByType text/css "access plus 1 month"
  ExpiresByType text/javascript "access plus 1 month"
  ExpiresByType application/javascript "access plus 1 month"
</IfModule>
```

Does this do the job?

**Comment by wardpeet** [comment]
Hey @sumanthyedoti,

Have you looked at https://www.gatsbyjs.org/docs/caching/? You'll have to setup something along these lines, I haven't tested it.

It should be already setup that way if you use `gatsby-plugin-htaccess`. Maybe drop the custom rules? If you can share a URL that would be helpful.

```
<FilesMatch "\.html$">
  Header set Cache-Control "public, max-age=0, must-revalidate"
</FilesMatch>
<FilesMatch "^/page-data/">
  Header set Cache-Control "public, max-age=0, must-revalidate"
</FilesMatch>
<IfModule mod_headers.c>
<FilesMatch "\.(js|css)$">
  Header set Cache-Control "public, max-age=31536000, immutable"
</FilesMatch>
<Files sw.js>
  Header set Cache-Control "public, max-age=0, must-revalidate"
</Files>
```

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
