### ISSUE TITLE
Gatsby Build + Gastby Serve + Anchor tag href change not working.

### ISSUE THREAD

**Issue by vstojkovski** [gatsbyjs/gatsby#24006]
## Description

The href tag of the anchor tag was changed based on a state change in dev mode (gatsby develop). When I switched to the production environment using gatsby build + gatsby server the href is no long affected i.e it stays the same no matter the change.

### Steps to reproduce

Create a <a href={stateHere}>stateHere</a> link and make the href change based on a state. When using gatsby develop href changes, when using production env the href does not change.

### Expected result

The href should change based on a state element. For example on first load stateHere is equal to '/test' after a change in the state it will be equal to /test-2, but the href attribute is not reflected with that change. However the text inside the anchor tag changes.

### Actual result

On the change of the state, the link remained the same and the href was not changed. Both places should reflect the state change

### Environment
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.19.49 => 2.19.49
    gatsby-cli: ^2.11.3 => 2.11.3
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-create-client-paths: ^2.1.23 => 2.1.23
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39
    gatsby-plugin-offline: ^3.0.32 => 3.0.32
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1
    gatsby-plugin-resolve-src: ^2.0.0 => 2.0.0
    gatsby-plugin-sass: ^2.1.29 => 2.1.29
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-source-graphql: ^2.1.33 => 2.1.33
    gatsby-source-greenhouse: ^2.0.2 => 2.0.2
    gatsby-source-marketo: ^1.0.2 => 1.0.2
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13
  npmGlobalPackages:
    gatsby: 2.19.28

Has anyone encountered this issue?

**Comment by madalynrose** [comment]
Hi @vstojkovski!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by julienfouilhe** [comment]
Encountered the same issue.

Here is a small example:

```
const PageComponent = ({location}: {location: Location}) =>  {
   console.log("Render page component");
   return <a href={`https://google.com${location.search ?? ""}`}>Link to site</a>
}
```

If you go to `http://localhost:5000?searchParam`, you'll see that the search is actually not forwarded to Google. The PageComponent is rerendered normally though (the console.log is displayed properly), but the href tag is not updated.

**Comment by julienfouilhe** [comment]
I don't think this is stale

**Comment by msquinn** [comment]
Any updates on this? Currently running into the same issue. @vstojkovski did you ever find a solution?

**Comment by vstojkovski** [comment]
@msquinn I was not able to find an actual fix with state change... Since I had separate page templates for UK/US languages I moved to a non-state solution and basically hardcoded the lang in the props of the main layout: <MainLayout lang="uk"> and <MainLayout lang="us">. This way when the pages were built it actually had the right lang from the start and it was not dependent on state change. (previously it was not like this and this lang was handled dynamically with state change but since I was not able to find a solution I had to do it differently).
