### ISSUE TITLE
How to connect one Foreign Field to another (I use gatsby-source-mongodb) 

### ISSUE THREAD

**Issue by phanatuan** [gatsbyjs/gatsby#24000]
Hi, 

I use `gatsby-source-mongodb` to query the following collection in my Mongo DB: 

`posts`: [featureImage, authorId] 
`authors`: [id (mongoID), authorName] 

Gatsby generates the GraphQL as expected. I could query the following: 

```graphql 
query MyQuery {
  allMongodbNicheappAuthors {
    nodes {
      featureImage
      name
      mongodb_id
    }
  }
allMongodbNicheappPosts {
    nodes {
      authorId
      featureImage
    }
  }
}
```
But I'm having problem connecting the "authorId" from `posts` to the `authors`.  I read the guide on [foreign field mapping](https://www.gatsbyjs.org/docs/schema-gql-type/#foreign-key-reference-___node), but it's quite short and not into details how to implement it. 

This guide on [mapping node types ](https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types)seems not to be relevant either. 

One more question is my `featureImage` field is an image s3 URL => How could I have Gatsby process the image so I could use Gatsby Transform Image when I query the image? 

Thank you so much. 

Tuan.

**Comment by freiksenet** [comment]
You can use schema customization for this. See this [guide for adding foreign key fields](https://www.gatsbyjs.org/docs/schema-customization/#foreign-key-fields) with it.
