### ISSUE TITLE
Relay support for client-only data fetching

### ISSUE THREAD

**Issue by rayronvictor** [gatsbyjs/gatsby#24007]
Gatsby have support for client-only data fetching using Relay?

I'm trying to create a funcional example but at build Gatsby conflicts with Relay Graphql template literal tag.

**Comment by rayronvictor** [comment]
I created an example that should fetch the name of the repository "facebook / relay" on Github using the [Github GraphQL API](https://api.github.com/graphql). You will need to generate a personal token and add `REACT_APP_GITHUB_AUTH_TOKEN=YOUR_TOKEN` to your `.env`

https://github.com/rayronvictor/gatsby-relay-example

I'm using [`gatsby-plugin-create-client-paths`](https://www.gatsbyjs.org/packages/gatsby-plugin-create-client-paths) for the client-only routes.

**Comment by LekoArts** [comment]
And what is the error you're facing? Please fill out the issue template for a bug:

````
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.org/docs/
  - How to File an Issue: https://www.gatsbyjs.org/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

````

**Comment by danabrit** [comment]
@rayronvictor Closing this issue due to no response in 8 days. If you would like to reopen it with the information requested in the issue template above, we'd be happy to take a look. Thank you!

**Comment by rayronvictor** [comment]
## Description

When using `babel-plugin-relay` to use relay for client-only data fetching GatsbyJs throw the error 

````console
ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve './__generated__/PagesQuery.graphql' in '/Users/rayron/Documents/workspace/gatsby-relay-example/.cache'

If you're trying to use a package make sure that './__generated__/PagesQuery.graphql' is installed. If you're trying to use a local file make sure that the path is correct.

File: .cache/dev-404-page.js

failed Re-building development bundle - 0.549s
````
### Steps to reproduce

I created an example that should fetch the name of the repository "facebook/relay" on Github using the Github GraphQL API. You will need to generate a personal token and add REACT_APP_GITHUB_AUTH_TOKEN=YOUR_TOKEN to your .env

https://github.com/rayronvictor/gatsby-relay-example

I'm using gatsby-plugin-create-client-paths for the client-only routes.

### Expected result

The `babel-plugin-relay` should not conflict with `gatsby develop` command

### Environment

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47 
    gatsby-image: ^2.4.16 => 2.4.16 
    gatsby-plugin-create-client-paths: ^2.3.10 => 2.3.10 
    gatsby-plugin-manifest: ^2.4.23 => 2.4.23 
    gatsby-plugin-offline: ^3.2.23 => 3.2.23 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.27 => 2.6.27 
    gatsby-source-filesystem: ^2.3.24 => 2.3.24 
    gatsby-transformer-sharp: ^2.5.13 => 2.5.13
