### ISSUE TITLE
Gatsby-image + Safari + CSS Columns: Not all images are displayed

### ISSUE THREAD

**Issue by jjato** [gatsbyjs/gatsby#24004]
## Description

For some reason, since a recent update of Gatsby or Safari, Gatsby-image doesn't work as expected on Safari when using the CSS property column-count.
From my understanding, it's like the images on the second column never get revealed. They have a forced property `transition: none` and even by forcing it in the stylesheet, they keep a 0 opacity.

Everything works fine in Firefox and Chrome.

I tried displaying using flex elements but it doesn't work as I want. My fallback option would be to use a library to reproduce the masonry style I was after.

The image isn't even loaded in the div element when it's on Safari AND using the columns, but it works as normal if I use a display flex.

At the moment, my portfolio is still broken so the issue can be visible here: https://www.jonathanjato.com/Love/

Here is a video of my localhost with the forced css style, you can see the image is poping.

[Gatsby-image-css-col-bug.zip](https://github.com/gatsbyjs/gatsby/files/4615300/Gatsby-image-css-col-bug.zip)

### Steps to reproduce

I used graphQL and ImageSharp to lazyload my images. I tried using the publicURL of my images and it works fine.
Link to the concerned page and line: https://github.com/jjato/portfolio/blob/0321c0c6f87c6bf876243e96ab73bc77d03b4ff0/src/templates/project.js#L123

### Expected result

<img width="1440" alt="Capture d’écran 2020-05-12 à 21 58 23" src="https://user-images.githubusercontent.com/15047094/81686109-b5410380-949b-11ea-81f0-7dede131b4fa.png">

<img width="1440" alt="Capture d’écran 2020-05-12 à 21 56 09" src="https://user-images.githubusercontent.com/15047094/81685456-66936980-949b-11ea-881a-9373af1614d7.png">

### Actual result

<img width="1440" alt="Capture d’écran 2020-05-12 à 21 54 55" src="https://user-images.githubusercontent.com/15047094/81685184-39df5200-949b-11ea-8279-84e63c3aa014.png">
<img width="1440" alt="Capture d’écran 2020-05-12 à 21 55 40" src="https://user-images.githubusercontent.com/15047094/81685332-554a5d00-949b-11ea-8781-e61cb346faf1.png">

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/local/Cellar/python/2.7.13/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    gatsby: 2.20.13 => 2.20.13 
    gatsby-cli: ^2.12.16 => 2.12.16 
    gatsby-image: 2.4.3 => 2.4.3 
    gatsby-plugin-less: ^3.2.1 => 3.2.1 
    gatsby-plugin-manifest: ^2.4.2 => 2.4.2 
    gatsby-plugin-offline: ^3.2.1 => 3.2.1 
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-sharp: ^2.6.2 => 2.6.2 
    gatsby-source-filesystem: ^2.3.1 => 2.3.1 
    gatsby-transformer-remark: ^2.8.7 => 2.8.7 
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2 
  npmGlobalPackages:
    gatsby-cli: 2.12.16
```

**Comment by jjato** [comment]
Forcing the overflow to be visible with an `!important` at the line bellow seems to fix that issue...

https://github.com/jjato/portfolio/blob/0321c0c6f87c6bf876243e96ab73bc77d03b4ff0/src/assets/styles/Screen.less#L19

**Comment by wardpeet** [comment]
I didn't see your overflow fix yet in the inspector. I do see this:
![safari](https://user-images.githubusercontent.com/1120926/81784657-7a6fb780-94fd-11ea-8906-432e01877cdc.png)

I think this is slightly tangential to Gatsby, and it seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪

**Comment by jjato** [comment]
Hey @wardpeet , thanks for having taken a look at the issue.
Which version of Safari are you using? I'm on Catalina, and I still have the issue, same by using an iPad and on another laptop using Catalina as well.

I haven't published the overflow fix but I'll do it today. It's a bit of a hack but it seems to fix it...

**Comment by wardpeet** [comment]
I'm using browserstack as I'm not on a mac which should be the same as a real device. I'm testing on safari 13 (Catalina). Also tested on iPad 7th generation on safari and also worked 😬

**Comment by jjato** [comment]
Yeah it seems to work for some people and not for others... I forced the overflow in the CSS, I'll check in a few updates to see what has changed :-)
Thanks for your time!
