### ISSUE TITLE
Feature Request: add test for trailing slashes in yaml files with links

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#24014]
## Summary

add a test for trailing slashes to yaml/json files with links to have sidebar links selected

### Basic example

- `/docs/guides/` <- trailing slash
- `/tutorial/part-zero/#install-git` <- trailing slash before hash #

but should ignore comments like:
```yaml
fromPath: /community/ # Moved "Community" page from /community to /contributing/community
```

### Affected files

- key `links:`
  - [www/src/data/sidebars/contributing-links.yaml](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/contributing-links.yaml)
  - [www/src/data/sidebars/doc-links.yaml](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml)
  - [www/src/data/sidebars/features-links.yaml](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/features-links.yaml)
  - [www/src/data/sidebars/tutorial-links.yaml](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/tutorial-links.yaml)

- key `fromPath` and key `toPath`:
  - [www/redirects.yaml](https://github.com/gatsbyjs/gatsby/blob/master/www/redirects.yaml)

- key `url`:
  - [www/src/data/diagram/static-hosts.yml](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/diagram/static-hosts.yml)

- but also some json in js:
  - [www/src/data/tags-docs.js](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/tags-docs.js)

### Motivation

> Could we write a test to validate this instead of checking manually every time?

_Originally posted by @tesseralis in https://github.com/gatsbyjs/gatsby/pull/23921#issuecomment-626048414_

### Related Issues:

- Issue Links not selected in sidebar when not with slash
  - #21318 `fix(www): Add slashes to links in features overview` 
  - #21604 `docs: redirect not select TOC`

**Comment by LekoArts** [comment]
Since `www` is private now I'll close this one.
