### ISSUE TITLE
Issues with installing Axios

### ISSUE THREAD

**Issue by mattcotter** [gatsbyjs/gatsby#2402]
Hi there,

Seem to be having an issue with install Axios alongside Gatsby.js. I'm trying to use Axios to pull a remote json file into my project and keep getting this issue after I try to run "gatsby develop"

> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module 'amdefine'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\mcotter\Desktop\gatsby\fresh\node_modules\webpack\node_modules\webpack-core\node_modules\source-map\lib\source-map\source-map-generator.js:8:37)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\mcotter\Desktop\gatsby\fresh\node_modules\webpack\node_modules\webpack-core\node_modules\source-map\lib\source-map.js:6:30)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
> 

I tried installing axios and react-axios (https://www.npmjs.com/package/react-axios) on two different installs. Same error on both.

**Comment by KyleAMathews** [comment]
This doesn't appear to be a Gatsby error. Perhaps something didn't get installed correctly? I'd google for this error message + axios + webpack to see if others have run into the same problem.

**Comment by Haroenv** [comment]
seems to be same as https://github.com/zeit/next.js/issues/2303

workaround seems to be to reinstall your node_modules

**Comment by sundarsan** [comment]
I was able to call an API using axios along with Gatsby js

**Comment by mattcotter** [comment]
I was able to get it working. Thanks everyone!
