### ISSUE TITLE
Disable right click on images?

### ISSUE THREAD

**Issue by musicbyjing** [gatsbyjs/gatsby#24030]
I saw that you can set `linkImagesToOriginal` as false in order to not link to the image, but I'm wondering if there's a way to go a step further and disable right click on images completely. 

I tried adding [this script](https://stackoverflow.com/questions/47076947/disable-rightclick-on-on-images/47076988) within a copied version of `html.js`, as mentioned [here](https://www.gatsbyjs.org/docs/custom-html/#adding-custom-javascript), but I'm guessing images don't use the `<img>` tag once Gatsby fully compiles everything, because it doesn't seem to work.

Anyone know of a workaround? Thank you.

**Comment by wardpeet** [comment]
Hey,

i'm not 100% sure why you would like to do this but you can add this snippet to your website. Just note that people will still be able to download your pictures. It's also not user friendly.

```js
document.addEventListener('contextmenu', (e) => {
  if (e.target.tagName === 'IMG') {
    e.preventDefault()
    e.stopPropagation()
  }
})
```

I would recommend disabling hotlinking instead.
https://www.google.com/search?q=hotlinking+protection
https://www.google.com/search?q=disable+hotlinking

Thank you for opening this, @musicbyjing

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
