### ISSUE TITLE
a11y (www): "View all posts" in homepage doesn’t get tab focus outline

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#24035]
##  Description

The "View all posts" link in the Gatsby site homepage doesn't get focus when tabbed into.

### Steps to reproduce

1. Go to https://www.gatsbyjs.org
2. navigate using the TAB key until "View all posts" is selected 

### Expected result

A visible outline should appear showing the element was selected.

### Actual result

No outline is visible.

<img width="1280" alt="Screenshot of gatsbyjs.org homepage showing the 'View All Posts' button" src="https://user-images.githubusercontent.com/1278991/81753781-67aba300-9469-11ea-8b41-f0e767aca4d5.png">

**Comment by carlesnunez** [comment]
I'd like to help in this one, can I?

**Comment by tesseralis** [comment]
@carlesnunez sure!

**Comment by carlesnunez** [comment]
Thank you so much! It's done, let me know if I have something else to do!
