### ISSUE TITLE
If a proposed change runs and *isn't* implemented for some reason, tell the user

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#24037]
## Problem

It's important for users to know if something was successfully installed and *also* if it wasn't installed.

## Solution
We should communicate these statuses:

- success
- error
- nothing happened because it was already installed in the past

**Comment by wardpeet** [comment]
@shannonbux, this sounds a little bit vague. Where do you want these messages to pop up? Maybe a screenshot with some pointers could help here?

**Comment by shannonbux** [comment]
@wardpeet apologies for not getting to this earlier! It's for recipes design in particular. I don't have a design yet yet need to track that this needs to get done. What do you advise?
