### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by abdokouta** [gatsbyjs/gatsby#24043]
hello, i would like to create a subdomain like my.example.com for customer account pages in my app and i would like upon login or upon click on my account button it should navigate to my.example.com and serve all account pages like 10 to 15 pages under this subdomain, i have read the path prefix but path prefix not dealing with subdomain it's dealing with subdirectories, any references or help on this, please?

**Comment by wardpeet** [comment]
You'll have to create 2 gatsby sites. 1 that works on `example.com` and another one that works on `my.example.com`. You don't need any special `pathPrefix` settings.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by jleni** [comment]
I would like to understand is there is any solution with respect to searching. 
If we split the site in two domains, is there any way that the search box still works for both?
