### ISSUE TITLE
Can't update the config.yml for gatsby-plugin-netlify-cms

### ISSUE THREAD

**Issue by minhtanpham** [gatsbyjs/gatsby#24046]
## Description

I am using the `gatsby-plugin-netlify-cms` plugin to work with Local NetlifyCMS on my computer.
1 month ago, I completed basic setup and running NetlifyCMS. However, today my Gatsby project changed the structure as well as updated the new collection, so I updated my `config.yml` file.
However, after the update is finished, I run `gatsby-develop` and all my updated content is reverted to the previous version before updating. Even when I updated and pushed the `config.yml` file to github, it still reverted to the old version.

I don't know what was missing or what to do in the process of updating this file.

### Steps to reproduce

- Checkout branch where `config.yml` of NetlifyCMS is being configured.
- Update new config.
- Restart gatsby with `gatsby develop`.
- The `config.yml` is reverted to the old version when gatsby was re-built.
- Update the updated content.
- Push to the git repository.
- Clone to repository.
- Run `gatsby develop`.
- The `config.yml` is reverted to the old version when gatsby was re-built.

### Expected result

The `config.yml` file is not changed when gatsby is restarted.

### Actual result

The `config.yml` file is not changed everywhen gatsby is restarted.

### Environment

- OS: MacOS Catalina ver 10.15.4
- NodeJs: v12.16.3
- Gatsby CLI version: 2.12.17

**Comment by wardpeet** [comment]
Hey @minhtanpham, I think you forgot to add the repository :)

**Comment by minhtanpham** [comment]
> Hey @minhtanpham, I think you forgot to add the repository :)

Hi @wardpeet, thanks for your reply. Here is my configuration for the repository in the top of my `config.yml`

```
backend:
  name: "github"
  repo: "abc/xxxxxx"
  branch: "develop"
```

Is that the part you think I am missing?

**Comment by wardpeet** [comment]
Hi,

No I mean a link to the github repository so we can checkout what the issue could be. It's hard to actually see where the bug lies without a repository.

**Comment by minhtanpham** [comment]
Thanks for your goodwill @wardpeet . I understand it is difficult to know where the cause is, but this is a private project and I cannot share it publicly. There is an information I hope will be useful.

Currently integrating NetlifyCMS into Gatsby I have only done on the develop branch, so the file `cofig.yml` does not exist on the master branch yet.

Anyway, thank you very much for the reply. I will try it on other computers and leave information for people who see this issue later

**Comment by erezrokah** [comment]
Thanks for assigning me @wardpeet.
@minhtanpham, I'm sure what "revert to old version" means? Does the file changes locally to a previous version or that the file remains the same but the changes are not reflected in the CMS?
If changes are not reflected in the CMS, how are you accessing it? Via localhost or the published site? Can you share the site URL?
If accessing the site locally can you provide the full path to the `config.yml` you're editing?
For example `static/admin/config.yml`.

Also, I'm not sure how it is reverted to a previous version in a completely new repo.
Can you share your `cms.js` file if exists and `gatsby-config.js`?
Also even if you can't share the repo, can you set up an example public repo with the issue?

**Comment by minhtanpham** [comment]
Hi @erezrokah, I mean all my changes on the `admin / config.yml` file have been changed and reverted back to its previous version. I cannot setup an example repo right now for you. However, I will send you my `cms.js` and `gatsby-config.js` files. Accompanied by a short clip describing the error that I am experiencing.

`cms.js` and `gatsby-config.js` file
[Archive.zip](https://github.com/gatsbyjs/gatsby/files/4627288/Archive.zip)

The clip describes the error I'm having
https://share.getcloudapp.com/GGukdKxP

My update for collection integrations is gone and my update for collection press released has been changed from `src/content/pr` to`/content/pr` as its previous version.

Hope this helps you spot the problem. I will re-produce and update the example repository as soon as possible. Regards.

**Comment by erezrokah** [comment]
Hi @mingaldrichgan, looks like you're editing `public/admin/config.yml` where you should be updating `static/admin/config.yml`

**Comment by minhtanpham** [comment]
yeah, you're right. Sorry my stupid mistake. Thanks @erezrokah for you help. Close this issue
