### ISSUE TITLE
Can I cache app-data.json?

### ISSUE THREAD

**Issue by starrett67** [gatsbyjs/gatsby#24041]
## Summary
app-data.json is hitting s3 rate limits during peak hours. I wonder what would happen if I applied some caching
## Relevant information
So basically we are seeing some 503 (slow down) origin responses during times of heavy traffic. We have strictly followed the caching guidelines here: https://www.gatsbyjs.org/docs/caching/ but we want to start caching this file for a bit to avoid hitting s3 rate limits. As of right now, it seems like this file is accessed every time a user hovers a link on the site and on page load. The idea is to put a small cache of 10 seconds on all the files that are recommended to not be cached. I'm worried that in the middle of deployments users may experience some issues. Right now we are seeing that an error response on this file causes a 404 page to be displayed. Can I expect the same behavior if we deploy changes to the site and a 10-second old webpack hash is displayed in the app-data.json file? 

### Environment (if relevant)
Site stored in s3 and served through cloudfront

**Comment by wardpeet** [comment]
We recommend that you do not cache app-data. It might bring your site into a weird state. 10 seconds sounds reasonable and probably won't cause much harm.

The question is why does it get requested so many times? You might want to move to cloudfront as a cdn. You can than let cloudfront cache app-data until a new version is uploaded.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
