### ISSUE TITLE
How to add inline script to html head before React rendering?

### ISSUE THREAD

**Issue by zheeeng** [gatsbyjs/gatsby#24049]
I want to execute some inline script to add the operation system info as the classname to HTML element. It is used to hide/display some download buttons under different OS.
I used offline-plugin, enabled prerendering and the service worker.

Can I have a chance to execute the script as soon as possible before React rendering? The `ComponentDidMount` lifecycle happens too later for adding OS classname to HTML, which leads   a flashing at first glance.

**Comment by wardpeet** [comment]
There are a few things you can do:
1) you can modify `html.js` to include your snippet. https://www.gatsbyjs.org/docs/custom-html/
1) You can use https://www.gatsbyjs.org/docs/ssr-apis/#onPreRenderHTML to add your script tag to the dom
1) Use https://www.gatsbyjs.org/docs/browser-apis/#onClientEntry, it's executed right before we do the client render.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
