### ISSUE TITLE
Output warning the graphql inference process drops fields due to type mis-matches

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#2405]
Users are surprised sometimes due to fields in their data being dropped due to mis-matched types. Instead of silently dropping data, we should output a warning about the data source (file(s), external API, etc) and any transformers involved and examples of the mis-matched data.

#2404 is an example of an issue coming from the lack of this warning and there's been more in the past.

/cc @danoc @jquense

**Comment by pieh** [comment]
Closed via #3905
