### ISSUE TITLE
Create Framework for consumers to write assertions against their filesystem GraphQl

### ISSUE THREAD

**Issue by alex-bezek** [gatsbyjs/gatsby#2406]
As a consumer of the filesystem repos to pull data from markdown (and possibly other file formats) I want to be able to write assertions to validate my data integrity. This framework or methodology should allow for
* a directory of test files that can be ran
* test files should allow for their own custom queries as opposed to just getting data from the extracted queries to write targeted specific tests
* Common test cases might be 
** Verify all tags are found within this defined array of tags (to avoid misspelling or typos and generating slightly different tags/categories)
** Verify all required fields have values, while others might be optional
** validate that value types are parsed correctly (a string to "./my-image.png" is processed by your sharp transformer and is of type File not type String)

@KyleAMathews noted that the [onPostBootstrap Node API](https://www.gatsbyjs.org/docs/node-apis/#onPostBootstrap) should be looked into.

##### Options
* Create a plugin that hooks into the onPostBoostrap lifecyle call. This would result in tests on every build
* Integrate into the gatsby-cli to be called independently. This aligns closer with create-react-app where your build is not dependent on your tests passing

**Comment by fabien0102** [comment]
Good idea! Until now I'm using some generators to avoid basic misspelling/typos (https://github.com/fabien0102/gatsby-starter/blob/master/generators/blog-post-generator.js) but integrity tests can be very cool! 

I think it can be done easily with the combo jest / fs / gray-matter (without any gatsby-cli integration)

**Comment by alex-bezek** [comment]
@fabien0102 thanks for taking interest. I'm interested in contributing this, but I'm very new to Gatsby. I agree integrating it directly into a jest test (or other framework), without involving the gatsby-cli, would be best and not interupt a developers typical scritps/dev_process so you could just run `npm test`. 

I'm very new to Gatsby, so first I have to figure out how gatsby magically provides the results of `pageQuery` to the components `this.props.data` . I searched the repo for `pageQuery` for specific code around it but only came up with results in www and examples
https://github.com/gatsbyjs/gatsby/search?l=JavaScript&p=1&q=pageQuery&type=&utf8=%E2%9C%93

A nudge in the right direction would be apprectiated so I can understand if using graphQl from a test will work out of the box (so we would just want to create a new example in the gatsby repo) or if some configuration needs to be done (so we could make a plugin making it easly accessible to everyone).

Thanks

**Comment by fabien0102** [comment]
@alex-bezek `pageQuery` it's just a convention, you can spell this variable as you want, the real keyword is `graphql`.

The magic part is [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/babel-plugin-extract-graphql.js), we have a babel parser to extract and compile the query.

After it used by the [query-runner](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby/src/internal-plugins/query-runner) (but I don't have all the process in mind ^^ but with these info, you can "easily" follow how a query become a props.data).

Last tips for understand this magic behind gatsby, you can install the [redux devtools](https://www.gatsbyjs.org/docs/how-to-contribute/#development-tools) to see all the data and process behind gatsby.

![image](https://user-images.githubusercontent.com/1761469/31428624-b8d7c948-ae6b-11e7-98fc-470ca3736752.png)

**Comment by KyleAMathews** [comment]
Hey, closing out old issues. Please re-open if you have additional questions, thanks!

(BTW, this does seem like a cool idea! Would love to discuss further in a new issue in interested)
