### ISSUE TITLE
Favicon not showing up on mobile

### ISSUE THREAD

**Issue by 8shaks** [gatsbyjs/gatsby#24063]
## Description

I notice once I change the favicon files in the static folder, the icons no longer work on mobile but still works on desktop. Instead in mobile I just get a letter.

### Steps to reproduce

Cloned the gatsby ghost starter repo.
Replaced the favicon files in the static folder within client with my own favicon files.
Added a node server to serve the static pages.

[https://github.com/8shaks/gatsby-ghost-test-site](https://github.com/8shaks/gatsby-ghost-test-site)

### Expected result

The icon should appear correctly on Mobile for the website when looking at browser history on mobile.
### Actual result

Instead when looking at browser history on mobile, it just shows the a letter instead of the favicon even though the favicon correctly shows on desktop.

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.2 - C:\Users\shaks\AppData\Local\Programs\Python\Python38-32\python.EXE
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.22 => 2.21.24 
    gatsby-awesome-pagination: 0.3.5 => 0.3.5 
    gatsby-background-image: ^0.8.9 => 0.8.19 
    gatsby-image: ^2.2.10 => 2.4.3 
    gatsby-plugin-advanced-sitemap: 1.5.1 => 1.5.1 
    gatsby-plugin-catch-links: 2.1.25 => 2.1.25 
    gatsby-plugin-exclude: ^1.0.2 => 1.0.2 
    gatsby-plugin-force-trailing-slashes: 1.0.4 => 1.0.4 
    gatsby-plugin-google-analytics: ^2.2.2 => 2.3.1 
    gatsby-plugin-manifest: ^2.3.3 => 2.4.2 
    gatsby-plugin-offline: ^2.2.7 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.4 => 3.3.1 
    gatsby-plugin-sharp: ^2.5.3 => 2.6.2 
    gatsby-source-filesystem: ^2.1.11 => 2.3.1 
    gatsby-source-ghost: ^4.0.3 => 4.0.4 
    gatsby-transformer-sharp: ^2.4.3 => 2.5.2

**Comment by pieh** [comment]
Can you provide reproduction? There are multiple ways to add favicons and it's not clear which one you are using.

I tried it on few sites and they working fine on mobile for me (showing actual favicon), so this might be something specific about your setup.

**Comment by 8shaks** [comment]
Hey, I edited the reproduction section a bit and also added a link to the code repo. I notice that when I add the website to my home screen(on mobile), the favicon appears correctly for my website. However if I look at the browser history the icon for the website is just a letter.
