### ISSUE TITLE
Routes on Netlify not working quite right... capital letters?

### ISSUE THREAD

**Issue by kershnerd** [gatsbyjs/gatsby#24072]
I have a very simple app running correctly locally but a few routes don't work when deployed to Netlify.

These routes work:
```
https://radiusai.netlify.app/
https://radiusai.netlify.app/blog
https://radiusai.netlify.app/health
```

These routes do not work... they show an empty page with no errors in the console:
```
https://radiusai.netlify.app/retail
https://radiusai.netlify.app/about
https://radiusai.netlify.app/contact
```

I don't have any redirects and all routes are just automatically created from:
```
/src/pages/index.js
/src/pages/about/index.js
/src/pages/contact/index.js
/src/pages/health/index.js
```
... etc

One interesting thing I noticed is that for some reason putting on a trailing '/' on the about route:
```
https://radiusai.netlify.app/about/
```

Does a redirect to:
```
https://radiusai.netlify.app/About/
```
... and that works.

All my directories are lowercase in the code.

Any idea what might be going on?

**Comment by jeffkershner** [comment]
So apparently routes nested in folders doesn't work?  

When moving the `/src/pages/about/index.js` to `/src/pages/about.js`, all routing issues are fixed.
