### ISSUE TITLE
How do I use nested component directories?

### ISSUE THREAD

**Issue by agamm** [gatsbyjs/gatsby#24074]
## Summary
I'd like so separate the components that are related to different pages (with different layouts for example).
For example, let's say I have a landing page with vastly different layout strucutrte than a conrol panel. So I'd like to move the control components to a different directory like so:
![bla2](https://user-images.githubusercontent.com/1269911/81872661-d92b4480-9582-11ea-8376-80843c5d476b.PNG)
after (I would like to have this):
![bla3](https://user-images.githubusercontent.com/1269911/81872716-f5c77c80-9582-11ea-8263-523568d7b7b0.PNG)

## Relevant information
I even tried to change the export names so there won't be collisions.

### Environment (if relevant)
Using the Windows 10 WSL.
```
System:
    OS: Linux 4.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
  npmPackages:
    gatsby: 2.21.26 => 2.21.26
    gatsby-plugin-eslint: 2.0.8 => 2.0.8
    gatsby-plugin-manifest: 2.4.2 => 2.4.2
    gatsby-plugin-offline: 3.2.2 => 3.2.2
    gatsby-plugin-postcss: 2.3.1 => 2.3.1
    gatsby-plugin-react-helmet: 3.3.1 => 3.3.1
    gatsby-plugin-sharp: 2.6.3 => 2.6.3
  npmGlobalPackages:
    gatsby-cli: 2.12.16
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

I'm not sure how this is specific to Gatsby, it will surely work with it. I suggest asking your general React questions in places like SO or Reactiflux. Thanks!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
