### ISSUE TITLE
How to make a production build in a project with jQuery?

### ISSUE THREAD

**Issue by niba** [gatsbyjs/gatsby#2408]
In one of my gatsby projects, I'm forced to use jquery in some of its parts. Unfortunately, I cannot make a production build for this project. I'm getting the following error:

`error Building static HTML for pages failed: WebpackError: jQuery requires a window with a document`

I import and use jQuery only in componentDidMount handlers and everything works in the develop mode. Do you have any ideas how could I fix this error in a production build?

**Comment by niba** [comment]
Ok, the problem was that apart from the jQuery itself I had one library that was dependent on jQuery and I was importing that library in the standard way at top of the file where window object wasn't ready

**Comment by goodok21** [comment]
layout.js:
```
if (typeof document !== 'undefined') {
  ...
  document.body.appendChild(script);
}
```

componentDidMount() in your component
```
setInterval(()=>{
      if (typeof window !== 'undefined' && stop != true) {
        console.log('retry');
        stop = true;
        ... do something with jQuery
      }
}
```
