### ISSUE TITLE
Dynamic Navigation Menu

### ISSUE THREAD

**Issue by abdokouta** [gatsbyjs/gatsby#24086]
Hello, i want to create Dynamic Navigation Menu which i'm using source plugin and having query prams based on locale so what i have done i have created a menu template and make the graphql query and called navigation component and passing data to it but when i call it in header component it's not getting data, i will attach files to a better understanding 
[index.txt](https://github.com/gatsbyjs/gatsby/files/4628285/index.txt)
[menu.txt](https://github.com/gatsbyjs/gatsby/files/4628286/menu.txt)

**Comment by LekoArts** [comment]
Thank you for opening this!

Please head to our communities listed below as this React question isn’t related to Gatsby specifically. You'll find help there. Thanks!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by abdokouta** [comment]
@LekoArts no it's not related to react it's related to gatsbyjs cuz gatsbyjs graphql avalible only while build and fetching data source so i need gatsbyjs help here
