### ISSUE TITLE
Tutorial step titles show a bullet point over number in dark mode

### ISSUE THREAD

**Issue by gillkyle** [gatsbyjs/gatsby#24093]
## Description

While in dark mode while viewing the docs. A noticeable circular bullet point covers up the number of the tutorial step. (Note: this also occurs on light mode, though the bullet is much fainter and doesn't seem to cause any issue seeing the number).

![image](https://user-images.githubusercontent.com/21114044/81952101-48288d80-95c3-11ea-9f3a-f1d236cc6cf7.png)

This is only an issue in the tutorial section, docs, features, contributing, are all unaffected.

## Related changes

This was introduced somewhere in #23248 which cleaned up a lot of code in the docs sidebar.

## How to fix

- [ ] identify what styles were adjusted that caused this (maybe as simple as a `list-style: none` thing, or maybe a custom `::before` element) and fix those styles (you can run the website following [instructions in the contributing section](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/))
- [ ] open a pull request stating the changes made that references this issue like `Fixes #24093`

**Comment by Pyrax** [comment]
Hey, I'd like to take a look at it.

**Comment by gillkyle** [comment]
That'd be great @Pyrax 🙂 feel free to give it a shot!

**Comment by Pyrax** [comment]
I would love to get some opinions which solution is preferred/which behavior is expected. @gillkyle @tesseralis 

Solution 1 - remove bullets on the accordion:
![solution_without_indent](https://user-images.githubusercontent.com/4885581/82044610-f0b31c00-96ad-11ea-8479-272821017edc.png)
Solution 2 - pass the `ui: steps` property down to children (still needs adjustments to position):
![solution_with_indent](https://user-images.githubusercontent.com/4885581/82044616-f27cdf80-96ad-11ea-8831-30039abd8d7d.png)

Before refactoring it looked like this:
![old_tutorial_links](https://user-images.githubusercontent.com/4885581/82043889-a3827a80-96ac-11ea-8c1f-c6155dc69bcc.png)

**Comment by gillkyle** [comment]
Hey @Pyrax! Thanks for a quick turnaround on this! Solution 2 looks like it's on the right track 🙂 

I pulled up an old build of the site before the changes that tweaked this (you can refer to it yourself here if you want: https://build-d65cadf7-eeda-4ea1-816a-354c4ab514f3.gtsb.io/tutorial/)

That makes it look like we'd like to keep the subheadings indented like your solution 2 shows, and the bullet would turn purple on hover and have the line cover it when selected. If we can get close to that behavior that we had that'd probably be the ideal. It looks like just repositioning the purple dot when an item is hovered in your screenshots might be enough.
