### ISSUE TITLE
[.cache] Deleted file still shown in gatsby posts

### ISSUE THREAD

**Issue by nodox** [gatsbyjs/gatsby#2410]
I deleted a folder full of markdown in my `src/pages` directory but when I went to view my site (in dev) the folder was still being referenced. When I did a build the pages were still being referenced. 

I did a grep search but nothing was found. I started wondering if some data was being save locally and I was correct. The `.cache` folder still had `.json` referencing the missing files as well as some file that I had updated to fix a typo (and the typo was still showing in development mode). 

The fix was to delete the `.cache` folder. The real problem however is that the updates to the filesystem are not shown in gatsby in realtime which can cause discrepancies. What exactly can you tell us about this interesting bug?

**Comment by KyleAMathews** [comment]
Could you test if deleting a file works?

Perhaps this code here doesn't work when a folder is deleted not a file? https://github.com/gatsbyjs/gatsby/blob/74e3bd6179324e30fa7d0091ccd12146c3710e7d/packages/gatsby-source-filesystem/src/gatsby-node.js#L52

**Comment by nodox** [comment]
Still looking into this. Not stale!

**Comment by KyleAMathews** [comment]
Did this PR fix things for you? https://github.com/gatsbyjs/gatsby/pull/2546

**Comment by misscs** [comment]
Also having a similar issue. I modified my `json` file in project but everytime I build it is referencing stale data. I even tried to delete the `.cache/json` folder to no avail. Is there a way to clear the cache?

**Comment by misscs** [comment]
Updated to latest version 👍

**Comment by johnrlive** [comment]
To delete your .cache folder just, cd into your project folder and run this in shell:

` rm -r ./.cache/*`
 
To rebuild cache just run 
`gatsby develop` or `gatsby build`

**Comment by ryantuck** [comment]
seems like it would help to have this as an arg to pass in, kind of like how docker does it:

```
gatsby develop --no-cache
```

**Comment by explicitcall** [comment]
It could also be helpful to have a `gatsby clean` command that cleans up the cache and whatever other cleanup is needed. Having this as a separate command would make it more discoverable through `gatsby help`

**Comment by KyleAMathews** [comment]
Creating then deleting caches makes the cache (more than) useless — instead — we need everyone to pitch in helping identify when and where our cache can get invalid. Our cache is already very good and can be perfect. We've merged ~10 PRs over the past 4-5 months fixing up edge cases in handling data in the cache e.g. this recent one https://github.com/gatsbyjs/gatsby/pull/4209

This particular issue was fixed a while ago actually so closing it now.

A general plea — if you *ever* run across a situation where you think the cache is at fault — please spend a bit of time verifying this it is a cache problem by verifying the problem and then create an issue with how to reproduce the problem, preferably with a sample site I or others could look at.

Caches are amazing and provide incredible speedups and improvements to the DX. Totally understand how annoying a cache is though that you can trust and I've spent 100s of hours already on the cache and am perfectly willing to spend that much more to make it perfect. But need people's help to identify bugs so they can get fixed.

**Comment by explicitcall** [comment]
not having an official way to clean the cache until it's working well doesn't help the issue

**Comment by KyleAMathews** [comment]
An official way to clear the cache is a strong indication that the project doesn't care about making the cache good which is absolutely not the case. You should *never* clear the cache. Again, if you ever feel the need to clear the cache, please file an issue.

**Comment by timojaask** [comment]
I'd love a way to reset the cache right now because I just switched one JPEG file for another with the same name, but for whatever reason, Gatsby doesn't see that the file has changed, and keeps showing the old file. It's driving me nuts because I can't figure out how to make it re-read the updated image file.

**Comment by KyleAMathews** [comment]
@timojaask where is the jpeg image being used? Is it referenced from a markdown file or are you querying it with graphql and ImageSharp?

**Comment by timojaask** [comment]
@KyleAMathews I've got graphqul query with a lot of images, below is a snippet. So I changed the `helsinki-basbas5.jpeg` image from one to another with the same name.
```
export const query = graphql`
  query ArticleImages {
    basbas4: imageSharp(id: {regex: "/helsinki-basbas4/" }) {
      sizes(maxWidth: 700, maxHeight: 525, cropFocus: CENTER) {
        ...GatsbyImageSharpSizes
      }
    },
    basbas5: imageSharp(id: {regex: "/helsinki-basbas5/" }) {
      sizes(maxWidth: 700, maxHeight: 525, cropFocus: CENTER) {
        ...GatsbyImageSharpSizes
      }
    },
  }
`;
```
I noticed that if I change anything in the basbas5 query, it will show the updated image. For example, if I change cropFocus to NORTH, it works. If I change it back to CENTER, it will show the old image again.

**Comment by KyleAMathews** [comment]
Huh, that's odd. Lemme look into that real quick.

**Comment by KyleAMathews** [comment]
I didn't make it far with my investigation but this is definitely a bug — we shouldn't be caching any query results if the underlying data changes in some ways. We normally don't I believe so not entirely sure what's happening. I'd appreciate more people investigating.

**Comment by KeevanDance** [comment]
Yes, I am storing markdown files, then deleting them, however the blog post rendered from the markdown file still persists on the webpage. Deleting .cache fixes this.

**Comment by filipetedim** [comment]
@KyleAMathews I too found the same issue with the images as @timojaask . In my case (fetching from Wordpress API), if I change an image on there, it seems the GraphQL isn't picking that up and still uses the old one, in both development and production (I suspect cache) as I build and deploy with `aws cli`. I have to manually go *inside* the GraphQL query, change something as to force it to re-do the query, and then it works.

Am I doing something wrong or is that just plan weird? The same happens with local images.

**Comment by KyleAMathews** [comment]
@filipetedim are you restarting `gatsby develop`? Gatsby doesn't know when you change data in WordPress so you need to trigger refetching data from there (which currently means restarting the develop server).

**Comment by filipetedim** [comment]
@KyleAMathews yep. Restarting `develop` and `build` too. It just doesn't pick it up unless I manually change something in the query. What I've done is every time this happens, I change the "quality" in the query to 99, then back to 100, then it successfully pulled it.

**Comment by alexandresgf** [comment]
Same issue here. Trying to do another query using gatsby-source-strapi plugin, and neither the new fields that I created on Strapi, appeared. I already erased the .cache folder, browser cache, and whatever related to it, and nothing happens. The fields that I created aren't appearing.

Error:

```TypeError: Cannot read property 'id' of null```

Query:
```
{
  strapiLandingpage(Landing_Owner: {eq: "RemeCoin"}) {
    id
  }
}
```

The new field is **Landing_Owner**, and the return:

```
{
  "data": {
    "strapiLandingpage": null
  }
}
```

And, the data was previously created in Strapi database.

Someone could help?

Thanks!

**Comment by timojaask** [comment]
@alexandresgf One simple way to make sure the cache is fresh is to rm -rf the entire project and re-clone it from git 😉 Make sure to push all changes before deleting! Works every time!

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by penumbra1** [comment]
Faced this issue today: swapped one png for another with the same name. SVG traces the new image, but the old one shows up, clipped to the size of the new one. Removing the cache didn't help.
![chaika](https://user-images.githubusercontent.com/11068840/46282833-01bc2180-c58c-11e8-8a6f-4707762b7adc.png)

**Comment by eivindflobak** [comment]
I had the same problem as @timojaask. I am using the latest version of GatsbyJS. Resolved the issue by adding a suffix to my jpeg filename.

**Comment by ChristianTucker** [comment]
Having the same problem using source plugins, I have to delete the .cache folder after adding or removing any nodes for them to show up correctly.

**Comment by mukul-rathi** [comment]
Have a similar problem with svg files - I get the "info changed file at ...../file.svg but the actual webpage doesn't refresh - I have to stop `gatsby develop` and manually clear the `.cache` folder.

**Comment by DanielRuf** [comment]
> It’s been 30 days since
> commented 11 days ago

Wait what?

**Comment by m-allanson** [comment]
Well... that's not right.

**Comment by DanielRuf** [comment]
Sounds like some cachebusting might be the solution / workaround in general (hashes in generated file names and references).

**Comment by leworking** [comment]
Hello, I'm experiencing the same issue (or I believe), I am retrieving a markdown file from Github, but when I change the content of that file, gatsby somehow is using the old version.

- If I run the query from graphiql, I receive the updated text
- If I delete the .cache folder (windows 10) after having stopped gatsby develop, it DOES NOT fix the issue, so that with gatsby develop I continue seeing the old content

**Comment by wardpeet** [comment]
I'm closing this issue, we fixed the problem described in this issue. When removing a md file, the listing gets removed but the html will still be accessible, which is described by https://github.com/gatsbyjs/gatsby/issues/10844.

If it's still an issue please open up a new issue.

**Comment by remi2j** [comment]
I replaced an image with another that had the same name. Gatbsy kept showing the old one, even after removing the cache. I had to rename my image to make the change happen.

**Comment by bobgravity1** [comment]
this happens to me all the time with gatsby. really annoying. takes like an hour of just messing around and RANDOMLY it works again.. to all the people saying to never delete caches. good luck using gatsby without having to do that 8-9 times each project. i love gatsby but this kind of random unexplained error stuff happens way too often

**Comment by bobgravity1** [comment]
solution this time: delete the whole markdown file. copy and paste the text. delete it. delete cache. delete node modules. run npm. run build. THEN make a new markdown file and paste it all in


yes... this is why gatsby is ridiculous
