### ISSUE TITLE
How to persit folders and files between builds on Gatsby Cloud

### ISSUE THREAD

**Issue by cedricdelpoux** [gatsbyjs/gatsby#24109]
## Summary 

Sometimes, we need to keep specific files or folders between builds and Gatsby cache is irrelevant because it can be invalidated and clear data.

It is possible using `Netlify` builds and [gatsby-plugin-netlify-cache](https://github.com/axe312ger/gatsby-plugin-netlify-cache)

```
{
      resolve: "gatsby-plugin-netlify-cache",
      options: {
        extraDirsToCache: [".my-specific-cache"],
      },
},
```

I can't find any documentation about this and it prevent me to use Gatsby Cloud instead of Netlify builds

## Usecase
One of my use case is to store a token wich need to be refreshed after expiration.
I can't use env variables because my token need to change dynamically and I can't store it in Gatsby cache because if the cache is invalidated, my token disappears.

**Comment by TylerBarnes** [comment]
@nicholascapo do you know if this is possible?

**Comment by LekoArts** [comment]
Please reach out to the Gatsby Cloud support via the "Help" button at the top. Thanks!
