### ISSUE TITLE
How to use this Graphql in gatsby-node.js？I want to use this to create pages,please help me,

### ISSUE THREAD

**Issue by linxianxi** [gatsbyjs/gatsby#24107]
Api like this in graphql-playground,
 How to use this api to create pages in gatsby-node.js?
![image](https://user-images.githubusercontent.com/47104575/82008472-6663bb80-969f-11ea-84b5-7896e6412fda.png)

--------------------------------------------------------------------------------------------------------------

Not down here，I can use this
![image](https://user-images.githubusercontent.com/47104575/82008494-78455e80-969f-11ea-807d-f883077c575c.png)

**Comment by herecydev** [comment]
Well if you want articles you can start with:

```
{
  allShopifyArticle {
    edges {
      ... more stuff here
    }
  }
}
```

You will see that the allShopifyArticle will be selected and give you additional options

**Comment by linxianxi** [comment]
> Well if you want articles you can start with:
> 
> ```
> {
>   allShopifyArticle {
>     edges {
>       ... more stuff here
>     }
>   }
> }
> ```
> 
> You will see that the allShopifyArticle will be selected and give you additional options

If not shopify,like this, it's my project.How to use it?
![image](https://user-images.githubusercontent.com/47104575/82022139-b900a000-96be-11ea-97e2-b9e3e82dad89.png)

**Comment by linxianxi** [comment]
> > Well if you want articles you can start with:
> > ```
> > {
> >   allShopifyArticle {
> >     edges {
> >       ... more stuff here
> >     }
> >   }
> > }
> > ```
> > 
> > 
> > You will see that the allShopifyArticle will be selected and give you additional options
> 
> If not shopify,like this, it's my project.How to use it?
> ![image](https://user-images.githubusercontent.com/47104575/82022139-b900a000-96be-11ea-97e2-b9e3e82dad89.png)

**Comment by herecydev** [comment]
Can you put together a reproduction? https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

If you haven't read [this](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) then I would suggest that's a good start to learning.

**Comment by linxianxi** [comment]
> Can you put together a reproduction? https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/
> 
> If you haven't read [this](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) then I would suggest that's a good start to learning.

It don't need an example for this, just want to know how to use the other graphql API in createPages。I used react-Apollo。

**Comment by herecydev** [comment]
Take a read of this and see if it helps: https://www.gatsbyjs.org/tutorial/part-seven/#creating-pages

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
