### ISSUE TITLE
createSchemaCustomization is failing to find tracer in 2.21.31 vs 2.21.19

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#24100]
## Description

`createSchemaCustomization` is not working as intended in `2.21.31` vs `2.21.19`

Is https://github.com/gatsbyjs/gatsby/pull/23589 potentially related?

### Steps to reproduce

1. https://github.com/duanecilliers/gatsby-mdx-frontmatter-starter uses the same setup as mine, but happy to pair over Zoom
1. Use Gatsby `2.21.19` to start develop server
  1. Should work fine
1. Upgrade to `2.21.31`
  1. Errors out in console with `Cannot read property 'tracer' of undefined` on fields that use custom schema resolver.

### Expected result

Schema customizations should work as they do in previous versions. 

If there is updated documentation I may have missed, please let me know.

<img width="935" alt="Screen Shot 2020-05-14 at 6 42 14 PM" src="https://user-images.githubusercontent.com/1018402/81992941-a597fb00-9612-11ea-964b-da1a92330432.png">

**Comment by pieh** [comment]
It seems very likely that PR you linked is responsible.

Last working version I found is `2.21.22`, and next one (`2.21.23`) breaks with error you describe (that was also release that introduced changes from that PR)

**Comment by freiksenet** [comment]
Thank you for you report! This is fixed in `2.21.32`. Resolver now checks if context is passed at all before using tracer.

I recommend always passing `context` and `info` to resolvers - they are compulsory parameters and they would break without them in a similarly confusing manner. I've added warning now so that people can fix it.

**Comment by zslabs** [comment]
Thank you very much @freiksenet!
