### ISSUE TITLE
Custom fonts in Gatsby node build cycle

### ISSUE THREAD

**Issue by danspratling** [gatsbyjs/gatsby#24113]
I've been creating a custom social image using NodeJS and [Canvas](https://github.com/Automattic/node-canvas) but I'm running into troubles using custom fonts.

Following canvas' recommendations, I'm registering the font for use
```js
const { registerFont, createCanvas } = require('canvas')
registerFont('static/fonts/ubuntu/4iCv6KVjbNBYlgoCjC3jsGyL.woff', {
  family: 'Ubuntu',
})
```
[socialImage.js](https://github.com/danspratling/portfolio/blob/7756b032236d2d71e3f6486d692725b9cb541e1c/functions/socialImage.js)

This function is then used in gatsby-node.js to generate social images. My blog uses Contentful as a CMS, so sometimes this build is triggered externally, and new social media images are generated directly in Gatsby Cloud (deployed to Netlify).

The problem I'm running into is that during local builds, everything works perfectly fine - the images are generated with the correct font, but when builds are run on the server, the font isn't loaded and I get something like this.

<img width="590" alt="Screenshot 2020-05-15 at 09 56 22" src="https://user-images.githubusercontent.com/11349104/82036648-1124ab80-9699-11ea-84bd-713321295b8f.png">

Is there anything I can do (or try) to allow the font to be used in all build environments?

**Comment by blainekasten** [comment]
@danspratling Do you know if you're using incremental builds feature in Gatsby Cloud?

**Comment by danspratling** [comment]
- @blainekasten I’m not. I’m just using normal builds.

**Comment by danabrit** [comment]
@danspratling Would you please send this to Cloud support - support@gatsbyjs.com - so they can help you get fixed up? Thanks!

**Comment by danspratling** [comment]
Had no response from support@gatsbyjs.com so going to re-open this to track the issue.

**Comment by LekoArts** [comment]
Please wait for an answer there, this is not the right place.
