### ISSUE TITLE
Any reason this is forced to be HTTP?

### ISSUE THREAD

**Issue by zoubarevm** [gatsbyjs/gatsby#24130]
https://github.com/gatsbyjs/gatsby/blob/f4939b5c545f238aaf2f4a82a05a55d7d5766a8d/packages/gatsby-source-contentful/src/download-contentful-assets.js#L59

**Comment by DanielRuf** [comment]
This was probably overseen in reviews.

https://github.com/gatsbyjs/gatsby/pull/10682

**Comment by vladar** [comment]
@axe312ger Should this be `https` instead? Sorry if I am tagging you inappropriately but I was told you will keep an eye on contentful source plugin.

**Comment by zoubarevm** [comment]
@vladar and @axe312ger - I've changed it to `https` and it all works locally. Our environment doesn't permit `http` connections and caused this error. I'm not entirely sure if there's a value in doing this is a flag or whether to just default it to `https` as that is the preferred method of communication with contentful by default.

**Comment by vladar** [comment]
It makes perfect sense to me to have `https` there. But I am not sure if we _should_ still support `http` as an option (I doubt so but I am not an expert here). Anyways, a PR is welcome for this simple change!
