### ISSUE TITLE
Scroll-sync of sidebar sets wrong items active

### ISSUE THREAD

**Issue by Pyrax** [gatsbyjs/gatsby#24132]
## Summary

For most items in the documentation the sidebar components sets wrong items as active. 

Best way to reproduce is clicking on this link: https://www.gatsbyjs.org/tutorial/part-zero/#install-git
Although, I linked "Install Git" it immediately highlights "Create a Gatsby site" which is the second next section. I have tested it on a viewport of 1905x948 where "Create a Gatsby site" feels to be at least one screen height away.

**Comment by Pyrax** [comment]
Did some short investigation on this today.

The problem is that code blocks on the page are not rendered server-side. As the offsets of all anchors are calculated once when the sidebar component is mounted, they are calculated before any code blocks have been rendered ([scroll-sync-sidebar.js#L20](https://github.com/gatsbyjs/gatsby/blob/6cf45884f8b53752d70accd0b96cae4548cf5f8c/www/src/components/sidebar/scroll-sync-sidebar.js#L20)).

**Comment by LekoArts** [comment]
When we merged gatsbyjs.org and gatsbyjs.com I rewrote this part of the codebase to use the `useActiveHash` hook. It works as expected now as it adds the IntersectionObserver after the code blocks have mounted :)
