### ISSUE TITLE
Mention that the navigate helper is not available during SSR

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#24135]
### Motivation

When using the [`navigate` helper](https://www.gatsbyjs.org/docs/gatsby-link/#how-to-use-the-navigate-helper-function), it was easy to forget/not realize that it's not available during SSR. The documentation page should mention how to handle that.

**Comment by blainekasten** [comment]
@dandv if you want to submit a PR feel free. However I personally feel like it's not that beneficial to document for a few reasons.

1. Devs rarely should be invoking functions like this during the render phase
1. The API is deprecated and will be removed in the next version of Gatsby.

I'm going to close the issue, but i'll cc @AishaBlake who leads our documentation to weigh in if she feels differently. Thanks for raising concern though!

**Comment by dandv** [comment]
> Devs rarely should be invoking functions like this during the render phase

Then maybe *that* should be mentioned in the docs? I have a landing page that my auth provider redirects users to after they verify their email. That landing page shows a toast and `navigate`s to `/app`, in order to keep `/app` clean of signup logic state.

In my experience missing documentation has hurt more than one extra line of documentation. Here's a [recent example](https://github.com/apollographql/apollo-client/pull/6303): *one* paragraph that would've prevented lengthy discussions involving tens of people (plus [hundreds](https://en.wikipedia.org/wiki/1%25_rule_(Internet_culture))+ lurkers) and wasting who knows how many days of dev time.

**Comment by antoinerousseau** [comment]
> > Devs rarely should be invoking functions like this during the render phase
> 
> Then maybe _that_ should be mentioned in the docs? I have a landing page that my auth provider redirects users to after they verify their email. That landing page shows a toast and `navigate`s to `/app`, in order to keep `/app` clean of signup logic state.

It's explained at https://www.gatsbyjs.org/docs/debugging-html-builds/

As @blainekasten stated, you shouldn't call `navigate` in your render phase, but rather in a side-effect, e.g. with `useEffect`.

**Comment by dandv** [comment]
Good point, thanks!

**Comment by casewalker** [comment]
> 2. The API is deprecated and will be removed in the next version of Gatsby.

The version is now Gatsby 5 and `navigate` is still alive and well!
