### ISSUE TITLE
Proposal: gatsby-source-workable example?

### ISSUE THREAD

**Issue by richardwestenra** [gatsbyjs/gatsby#2413]
Would you be interested in a demo of [gatsby-source-workable](https://github.com/tumblbug/gatsby-source-workable/) for the examples directory? I was thinking of making one, but wanted to check it would be useful before beginning work.

**Note:** I have an unreviewed [open PR](https://github.com/tumblbug/gatsby-source-workable/pull/3) on that plugin, and I believe that the plugin won't work properly until that's merged. As a temporary workaround, I could link to my forked branch in the package.json for the demo, and change it over when that fix gets merged? (CC @bjrnt)

**Comment by KyleAMathews** [comment]
So far we haven't had any example sites built with plugins not hosted here since community plugins aren't as easy to fix if they break.

That being said, the more example sites the better. If @bjrnt doesn't mind helping review the example app and being available if the plugin breaks, I think it'd be great to add an example site.

**Comment by richardwestenra** [comment]
@KyleAMathews Ok cool, thanks!

One small issue: I don't have a Workable API key that I'm allowed to publicly share in an example repo. I asked Workable's support team and they were reluctant to share an example key. So I might just use environment variables for the API keys with [dotenv](https://github.com/motdotla/dotenv) instead?

**Comment by KyleAMathews** [comment]
Yeah, making the example a "some assembly required" example site seems reasonable given it's a commercial product.

**Comment by KyleAMathews** [comment]
Hey, closing out old issues. Please re-open if you have additional questions, thanks!
