### ISSUE TITLE
Can Gatsby infer the structure and create GraphQL types automatically from data returned by a resolver

### ISSUE THREAD

**Issue by maxkoretskyi** [gatsbyjs/gatsby#24136]
I've written a custom resolver that returns a data which is a nested mix of arrays and objects. It seems that I need to explicitly define a type for each nested object, something like this for just one `CustomAuthor` object:
```
exports.createSchemaCustomization = ({ actions }) => {
    const { createTypes } = actions;
    const typeDefs = `
        type ProcessedHits implements Node {
          name: String,
        }
        
        type CustomAuthor { 
            author: String,
            hits: Int
        }
      `;
    createTypes(typeDefs);
};

exports.createResolvers = ({ createResolvers }) => {
    const resolvers = {
        ProcessedHits: {
            custom: {
                type: "CustomAuthor",
                resolve(source, args, context, info) {
                    const posts = context.nodeModel.getAllNodes({ type: "Post" });
                    ...
                    return { author: 'John', hits: 3};
                },
            },
        },
    };
    createResolvers(resolvers);
};
```

**Is there any way, like helper or something, for Gatsby to infer types from the returned data?** 

As you can imagine, if an object is deeply nested it's going to be a lot of type definitions simply for the purpose of making graphql work.

**Comment by herecydev** [comment]
I've been doing this a lot lately and not found such thing unfortunately. Definitely would be helpful if something existed

**Comment by blainekasten** [comment]
Thanks for reporting ya'll! I've assigned to @vladar who leads development on our graphql code. He'll be able to discuss and find out solutions here. 💜

**Comment by maxkoretskyi** [comment]
@blainekasten, thanks! It seems that it's even more complicated than simply setting up types, it seems Gatsby requires me to set up a resolver for each nested object like this:

```
exports.createSchemaCustomization = ({ actions }) => {
    const { createTypes } = actions;
    const typeDefs = `
        type CustomAuthor {
            hits: CustomHits
        }

        type CustomHits {
            session: String,
            title: String,
            week: String
        }
      `;
    createTypes(typeDefs);
};

exports.createResolvers = ({ createResolvers }) => {
    const resolvers = {
        CustomAuthor: {
            hits: {
                type: "CustomHits",
                resolve(source, args, context, info) {
                    return { session: "2222", title: "KOval Vlad", week: "2020-01" };
                },
            },
        },
    };
    createResolvers(resolvers);
};

```

@vladar can you please confirm that this is indeed the right approach at the moment?

**Comment by vladar** [comment]
Hi @maxkoretskyi !

As long as the data returned from your resolvers matches nested type structure it should just work without additional resolvers. Can you please make a [repro][reproduction] of your problem with steps to reproduce (i.e. provide the query you are running that doesn't work as expected)

Then I can take a look.

[reproduction]: https://gatsby.dev/reproduction

**Comment by maxkoretskyi** [comment]
@vladar , thanks, indeed, this approach seems to be working without custom resolvers, thanks!

```
    const typeDefs = `
        type ProcessedHits implements Node {
            hits: [CustomHits]
        }
        type CustomHits {
            author: String,
            sessions: Int,
            title: String,
            path: String,
            oneWeekSession : [SessionWeek]
        }
        type SessionWeek {
            week: String,
            sessions: Int
        }
      `;
```

Any comments about inferring the structure and creating GraphQL types automatically from data returned by a resolver?

**Comment by vladar** [comment]
> Any comments about inferring the structure and creating GraphQL types automatically from data returned by a resolver?

Type definitions and schema building occur **before** resolvers are executed. You need a full schema before you start resolving anything. You can't modify the schema as you run queries.

You can still leverage inference but on the node level. For example, by using [`createNodeField`](https://www.gatsbyjs.org/docs/actions/#createNodeField) in the [`onCreateNode`](https://www.gatsbyjs.org/docs/node-apis/#onCreateNode)

Or by creating [child nodes](https://www.gatsbyjs.org/docs/creating-a-transformer-plugin/#create-new-nodes-from-the-derived-data)

Alternatively, for dynamic data, you can use a special `JSON` type, but keep in mind that you can't query nested fields of this type, so the whole `JSON` structure will be passed to your components (and added to page-data.json)

**Comment by maxkoretskyi** [comment]
@vladar appreciate your input, could you please elaborate a bit on these:

> Alternatively, for dynamic data, you can use a special JSON type,

like this?

```
exports.createResolvers = ({ createResolvers }) => {
    const resolvers = {
        CustomAuthor: {
            hits: {
                type: "JSON",
                resolve(source, args, context, info) {
                    const someAribtraryJSONLikeData = [...];
                    return someAribtraryJSONLikeData;
                },
            },
        },
```

> You can still leverage inference but on the node level. For example, by using createNodeField in the onCreateNode .... Or by creating child nodes

That's probably not suitable for my case as I need to have access to `context.nodeModel` as described [in this issue](https://github.com/gatsbyjs/gatsby/issues/23791#issuecomment-626547034) and it's not available in `onCreateNode`. Or am I missing something?

> Type definitions and schema building occur before resolvers are executed. You need a full schema before you start resolving anything.

Can I create a dummy node with some mock data for Gatsby to infer the schema? [Something like this plugin does](https://github.com/TryGhost/gatsby-source-ghost/blob/master/gatsby-node.js#L128):

```
const createTemporaryFakeNodes = ({emitter, actions}) => {
    // Setup our temporary fake nodes
    fakeNodes.forEach((node) => {
        // createTemporaryFakeNodes is called twice. The second time, the node already has an owner
        // This triggers an error, so we clean the node before trying again
        delete node.internal.owner;
        actions.createNode(node);
    });
```

**Comment by vladar** [comment]
> like this?

For `JSON` type - yes, that's correct.

> Can I create a dummy node with some mock data for Gatsby to infer the schema? Something like this plugin does:

This is a bad approach (at least the way this plugin does it - I even filled an issue for them - https://github.com/TryGhost/gatsby-source-ghost/issues/44). Schema customization is a better way.

If you have a fake node - you can simply transform it to type definition manually. We discussed once the possibility of adding a utility that would do it for you (transform arbitrary object to type definition) but that didn't move further yet.

I mean the idea is that you could do something like this:

```js
exports.createSchemaCustomization = ({ actions }) => {
  createTypes([
    // ...some manual definitions,
    inferType(fakeObject),
  ])
}
```

The PR for such a utility is very welcome! 😉

**Comment by vladar** [comment]
We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

If you decide to open a PR with `inferType` utility, please just mention me in the PR description!
