### ISSUE TITLE
How to achieve SEO for dynamic content received from API ?

### ISSUE THREAD

**Issue by ImSolitude** [gatsbyjs/gatsby#24146]
I am not sure If Gatsby works best for this use case, But I have an API to provide me content for static websites for list of companies (Text and Images).
Let's just say If user hit `company1.mygatsby.com` then `company1` content will be received and displayed. I've done the website and content shown perfectly

 My problem now how to achieve SEO for those websites? How to make whatever SEO checker to wait for the data before indexing or checking. Excuse my ignorance, I am new to this.

**Comment by herecydev** [comment]
Are you sourcing the content dynamically or statically (at build time when gatsby build runs). It sounds like the content is static and you would be best off building all your page content ahead of time rather then dynamically.

Once you have all that being built into your pages, the seo story becomes much easier to work with.

**Comment by ImSolitude** [comment]
@herecydev, The # of companies is big and the content is huge so I guess it must be dynamic, I don't think something like [this](https://www.gatsbyjs.org/docs/recipes/sourcing-data/#pulling-data-from-an-external-source-and-creating-pages-without-graphql) works best for my use case? because I cannot loop over the companies and get all the data, It's just too much.

Just to demonstrate, User goes to `company1.mygatsby` the API then hits `company1` and retrieve it from API. I am not sure If it's possible. If you can give me a brief example I'd appreciate it. Thank you.

**Comment by herecydev** [comment]
Well give me an idea of how many companies and how big the data is. I've worked with 10k pages and that works fast, I'm confident gatsby can easily push much further (into the 100k page territory as well)

**Comment by LekoArts** [comment]
Thank you for opening this!

As Dan mentioned: If you're creating these pages on the client-side it's just a normal React SPA and hence it has the typical SEO situation (worse than what Gatsby creates at build time). On this front Gatsby can't help you as client-side is just client-side.

However, I would encourage you to try to build your site! https://github.com/gatsbyjs/gatsby/issues/19512 has shown that it's possible -- if it doesn't work _just_ yet you can comment on the issue.
You can also try Gatsby Cloud at https://www.gatsbyjs.com/ which is purpose-built for Gatsby sites and should increase the build time even more.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by rafcontreras** [comment]
@ImSolitude maybe you could try [PERENDER.io](https://prerender.io) SAAS, or host it [yourself](https://github.com/prerender)

**Comment by stevepepple** [comment]
I realize this issue is closed, but doesn't this approach work for this situation? 

https://www.gatsbyjs.com/docs/how-to/rendering-options/using-server-side-rendering/
