### ISSUE TITLE
How to stop Gatsby from converting SVG favicon to PNG during build

### ISSUE THREAD

**Issue by LethalPants** [gatsbyjs/gatsby#24149]
## Summary

Hi! I have a SVG file which I want to use for the favicon of my website, because of the flexibility to change color depending on the theme. On building the site, the SVG is converted into PNG format. How do I stop that from happening?

### Environment (if relevant)

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.3 - /c/Users/Hatim/AppData/Local/Programs/Python/Python38-32/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12 
    gatsby-image: ^2.3.1 => 2.3.1 
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3 
    gatsby-plugin-offline: ^3.1.2 => 3.1.2 
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1 
    gatsby-plugin-sass: ^2.2.1 => 2.2.1 
    gatsby-plugin-scroll-reveal: 0.0.6 => 0.0.6 
    gatsby-plugin-sharp: ^2.5.3 => 2.5.3 
    gatsby-plugin-smoothscroll: ^1.1.0 => 1.1.0 
    gatsby-source-filesystem: ^2.2.2 => 2.2.2 
    gatsby-transformer-sharp: ^2.4.3 => 2.4.3 
  npmGlobalPackages:
    gatsby-cli: 2.12.21

### File contents (if changed)

`gatsby-config.js`: 
```
plugins: [
    `gatsby-plugin-sass`,
    `gatsby-plugin-react-helmet`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-smoothscroll`,
    `gatsby-plugin-scroll-reveal`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Hatim Murtuza`,
        short_name: `Hatim Murtuza`,
        start_url: `/`,
        background_color: `#fbfbfb`,
        theme_color: `#0075f2`,
        display: `standalone`,
        icon: `src/images/icon.svg`, // This path is relative to the root of the site.
        icon_options: {
          purpose: `maskable`,
        },
        cache_busting_mode: `none`,
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    {
      resolve: `gatsby-plugin-offline`,
      options: {
        precachePages: [`/`, `/404`],
        workboxConfig: {
          globPatterns: ["**/*"],
        },
      },
    },
  ],
```
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by blainekasten** [comment]
Hey @LethalPants, thanks for the report. I've assigned this to @wardpeet to help you out.

**Comment by LekoArts** [comment]
Thank you for opening this!

You should use the `manual` option to define your icons and the paths to it yourself: https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/#manual-mode-configuration

This way you skip the image conversion part.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
