### ISSUE TITLE
Gatsby Documentation: Change sidebar expand arrows to point downward rather than upward

### ISSUE THREAD

**Issue by capndave** [gatsbyjs/gatsby#24150]
## Description

The dropdown arrows on the gatsby docs point upwards to expand rather than downwards. Am I crazy or should they point downward?

![image](https://user-images.githubusercontent.com/15132517/82131211-6b586600-9798-11ea-87a1-88188473bfea.png)

### Steps to reproduce

Go to the [gatsby docs](https://www.gatsbyjs.org/docs/). Click on any arrow on the left-hand side. Note direction.

**Comment by djD-REK** [comment]
This is actually a really interesting design choice.  I think the current arrows are unintuitive too, so I tried doing some research.  

The buttons should point down before they are opened, indicating that clicking on them drops the menu down, and then right or preferably up (indicating that clicking brings the menu up) when you click on them.

At least, that's according to StackOverflow: https://ux.stackexchange.com/questions/87350/which-way-should-arrows-point-for-a-dropdown-button

Thoughts @capndave ?

**Comment by capndave** [comment]
I can get behind the arrows representing "what will be" rather than "what
is". A dropdown menu normally uses a down arrow to show that clicking on it
will make something appear in a downward direction. What seems off to me is
that, using the logic above, the arrow should point down when collapsed and
up when expanded. Instead I read the sideways arrow as (currently)
collapsed. Its corollary would be currently expanded = down.

All that being said, this probably isn't a big deal. If other users dont
have the same reaction then we should probably close the issue.
