### ISSUE TITLE
Navigation links to top level route on subpages (created with createPage) not working

### ISSUE THREAD

**Issue by distor-sil3nt** [gatsbyjs/gatsby#24157]
This might be a rookie question however I couldn't really find a solution to this while searching the forum:

I have a page 'careers' created through the pages folder (file name careers.js with corresponding slug /careers) and several subpages of careers created with the createPages API in the file gatsby-node.js like so:

```
    result.data.allMarkdownRemark.edges.forEach(({ node }) => {
        const department = node.frontmatter.department
        const slug = node.frontmatter.slug
        const path = '/careers/${department}/${slug}'

         createPage({
             path,
             component: careerPositionTemplate,
              context: {
                  slug,
              },
         })
    })
```

My problem now is that once I am on a slug of a subpage (i.e. /careers/engineering/position-engineer) the navigation links in my header and footer to /careers/ don't work. Once I'm on any route that contains the top level route /careers/ the link to /careers/ in the navigation gets rendered without a href:

In the Navigation.js file the Link is defined as:

```
    <Link activeClassName="active" to="/careers" onClick={handleCloseOnTimeout}>
         <Button color="dark" size="md">Career</Button>
    </Link> 

```
On route /careers/engineering/position-engineer the back link to /careers/ doesn't work. The Output in the header and footer is:
```
   <a class="d-flex align-items-center ml-2">
       <button class="btn btn-dark btn-sm">Career</button>
    </a>
```

On route /about/ without the top level route /careers/ the link is rendered with a href as I want it:

```
  <a class="d-flex align-items-center ml-2" href="/careers">
     <button class="btn btn-dark btn-sm">Career</button>
   </a>
```

I already tried a plugin [gatsby-plugin-exact-client-paths](https://www.gatsbyjs.org/packages/gatsby-plugin-exact-client-paths), however that plugin throws errors after installing. So I couldn't really test whether it would solve my problem. After trying multiple other things with client side routes and manually setting up routing with reach router in vain I'm now desperate enought to post this question here. Don't know if it has been answered somewhere else here already - I'm just would be grateful for any help.

### Environment (if relevant)

```
  System:
    OS: Windows 10
    Shell: Command Prompt, Powershell
  Binaries:
    Node: 12.16.2
    npm: 6.14.4
  Browsers:
    Chrome: 81.0.4044.138 (Offizieller Build) (64-Bit)
npmPackages:
    "gatsby": "2.21.33",
    "gatsby-image": "2.4.3",
    "gatsby-plugin-alias-imports": "^1.0.5",
    "gatsby-plugin-anchor-links": "1.1.1",
    "gatsby-plugin-compile-es6-packages": "^2.1.0",
    "gatsby-plugin-manifest": "2.4.3",
    "gatsby-plugin-offline": "3.2.2",
    "gatsby-plugin-postcss": "2.3.1",
    "gatsby-plugin-react-helmet": "3.3.1",
    "gatsby-plugin-react-svg": "^3.0.0",
    "gatsby-plugin-sass": "2.3.1",
    "gatsby-plugin-sharp": "2.6.3",
    "gatsby-plugin-transition-link": "^1.18.0",
    "gatsby-source-filesystem": "2.3.3",
    "gatsby-transformer-remark": "2.8.8",
    "gatsby-transformer-sharp": "2.5.2",
    "node-sass": "4.14.1",
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Also: You're mixing up `career` and `careers` up multiple times in your text, are you sure it's not a typo on your end?

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by distor-sil3nt** [comment]
My bad, I had some typos in the description of the issue. I corrected them now. The slug is in any case called /careers/

I will try to provide a code example asap to demonstrate my problem.

**Comment by distor-sil3nt** [comment]
I solved the problem after reconstructing the problem in a minimal reproduction app. The Link component has been rewritten by a custom Link component and the route matching of the custom Link component was not done properly / was buggy. That's why Links were not working properly on subpages / subroutes.

Thanks for your help!
