### ISSUE TITLE
PWA Not working on Netlify

### ISSUE THREAD

**Issue by JesterOrNot** [gatsbyjs/gatsby#24162]
## Description

I followed the steps on https://www.gatsbyjs.org/docs/progressive-web-app/ to create a Gatsby PWA, and it worked in development using `gatsby build && gatsby serve` but in the Netlify deploy preview the service worker fails to register, this is the error `The installing service worker became redundant.`

### Steps to reproduce

Unsure how to reproduce in another project but to see the issue

1. [open](https://gitpod.io/#https://github.com/gitpod-io/website/pull/639) the repo in Gitpod
2. Open in browser
3. See PWA installable
4. Open the [deploy preview]
5. See the logs say that it failed 

Alternatively, here are the screenshots

Development

![image](https://user-images.githubusercontent.com/50386709/82153192-a061c880-982b-11ea-9f2d-5a9d6dc16cc3.png)

Deploy Preview

![image](https://user-images.githubusercontent.com/50386709/82153214-c38c7800-982b-11ea-923e-2dbdce2e5dbb.png)

### Expected result

PWA should be insatllable on Netlify just like it was previously in a production build.

### Actual result

Weird error that is not consistent with the production gatsby build

### Environment

```
  System:
    OS: Linux 4.14 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Languages:
    Python: 2.7.17 - /home/gitpod/.pyenv/shims/python
  npmPackages:
    gatsby: 2.19.7 => 2.19.7
    gatsby-image: 2.2.39 => 2.2.39
    gatsby-plugin-algolia-docsearch: ^1.0.5 => 1.0.5
    gatsby-plugin-canonical-urls: 2.1.19 => 2.1.19
    gatsby-plugin-catch-links: 2.1.24 => 2.1.24
    gatsby-plugin-emotion: 4.1.21 => 4.1.21
    gatsby-plugin-exclude: ^1.0.2 => 1.0.2
    gatsby-plugin-feed: ^2.3.26 => 2.3.26
    gatsby-plugin-google-analytics: 2.1.34 => 2.1.34
    gatsby-plugin-manifest: ^2.4.3 => 2.4.3
    gatsby-plugin-offline: ^3.2.2 => 3.2.2
    gatsby-plugin-react-helmet: 3.1.21 => 3.1.21
    gatsby-plugin-sharp: 2.4.3 => 2.4.3
    gatsby-plugin-sitemap: 2.2.26 => 2.2.26
    gatsby-plugin-typescript: 2.1.26 => 2.1.26
    gatsby-remark-autolink-headers: 2.1.23 => 2.1.23
    gatsby-remark-copy-linked-files: 2.1.36 => 2.1.36
    gatsby-remark-embed-video: ^2..1 => 2.0.1
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-images: 3.1.42 => 3.1.42
    gatsby-remark-prismjs: 3.3.30 => 3.3.30
    gatsby-remark-responsive-iframe: 2.2.31 => 2.2.31
    gatsby-remark-smartypants: 2.1.20 => 2.1.20
    gatsby-source-filesystem: 2.1.46 => 2.1.46
    gatsby-transformer-json: 2.2.25 => 2.2.25
    gatsby-transformer-remark: 2.6.48 => 2.6.48
    gatsby-transformer-sharp: 2.3.13 => 2.3.13
  npmGlobalPackages:
    gatsby-cli: 2.12.21
```

**Comment by blainekasten** [comment]
Thanks for the report! I've assigned our Learning team to review this and get back to you. Thanks!

**Comment by XabierL** [comment]
Yes, netlify deploy
![image](https://user-images.githubusercontent.com/44481156/82736072-13d17180-9d27-11ea-8ce6-885b92b8d5d4.png)

In local, gatsby build works correctly, PWA too
Regards

**Comment by JesterOrNot** [comment]
Any news on this issue?

**Comment by LekoArts** [comment]
I don't think this is an issue with GitHub but rather with Netlify and/or your deployment. See https://community.netlify.com/t/workbox-error-precachecontroller-mjs-194-uncaught-in-promise-bad-precaching-response-redirects-wb-revision-404/8865/9 and https://github.com/GoogleChrome/workbox/issues/2179#issuecomment-519664678.

You can adjust the workboxConfig if needed.

**Comment by sauravseth** [comment]
If anyone else experiences the same problem with gatsby: ^5.12.0 and netlify then do the following
1. Create a `_redirects` file (no extension) under the `static` folder. This file is used by netlify to handle routing
2. Add the following line to the file `/offline-plugin-app-shell-fallback/index.html /offline-plugin-app-shell-fallback 200`
3. Re-deploy your site

The reason why the problem exists is that netlify is not serving pages with /index.html (I turned off pretty URLs yet it didn't work). This redirect ensures that the actual page is served
