### ISSUE TITLE
Question: How Search Engines crawl Internal Links for SEO and will it affect my SEO?

### ISSUE THREAD

**Issue by nikolayval** [gatsbyjs/gatsby#24168]
Hello!

I'm working with personal SEO-sites. And I have one question about react router. Sorry for bad English, I'm from Russia and learn English.

For SEO Internal Links very important. Internal Links help to Google better site crawling. In Internal Links anchor I write the main keywords, and it improve SEO for my other pages too.

Anchor-words (link-word) on links will help to Google, what about our other page, that we linking. This is a popular technique for optimizing sites for SEO. Internal links with anchors help search robots better explore the entire site.

Please tell me. Can search engines crawl through internal links on my Gatsby Site? In React.js, pages work without refresh page on Browser. This is how works React Router, right? And will search robots then be able to understand that the page has changed? Or all the pages for the search robot are the same, because the page in the browser did not refreshed?

Sorry for poor english. Sorry, I feel ashamed for my English.

**Comment by LekoArts** [comment]
Thank you for opening this!

Gatsby uses `@reach/router` and those links are just `<a>` tags. This doc https://www.gatsbyjs.org/docs/seo/ also touches on the fact that all the HTML is generated when using Gatsby so your site (and thus also Google) will work without JavaScript. You get distinct pages with working links.
So yeah, everything will work! :) 

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
