### ISSUE TITLE
How to change doctype in gatsby?

### ISSUE THREAD

**Issue by Lenetta** [gatsbyjs/gatsby#24169]
Hi people.
I choose between React and Gatsby to create custom emails with reusable components.
React has index.html, which is created manually, but static files out of the box are not generated there.
In Gatsby, I cannot find where to change the DOCTYPE.
Someone can say, is it possible to change DOCTYPE in Gatsby?

**Comment by blainekasten** [comment]
At this point I don't see that we support changing the DOCTYPE based on a quick search through our codebase. Using Gatsby for generating emails is a new use case we haven't really considered and we don't see this very often. 

I'm curious why you chose Gatsby for this?

**Comment by Lenetta** [comment]
Because I liked the component approach as in reaction with the generation of static files.
The letter template is individual and requires fine styling and layout, various tools for letters are either heavily overloaded or have defects when working on the desired platforms. And it’s more convenient for me to write a set of my components for their reuse. And you also need to store all the files, and not generate them one at a time, here the same files will be routes and it will be easy to find and change them.

**Comment by LekoArts** [comment]
Hey, thanks for the issue!

I don't think we'll expose this as an option however you can change this yourself via the `onPostBuild` lifecycle.

I created a plugin for this, you could give this a try: https://github.com/LekoArts/gatsby-plugin-doctype

It changes the DOCTYPE for every HTML file inside the `public` folder.

As this can be achieved in userland and we won't expose this for everyone I'll close this issue.

**Comment by Lenetta** [comment]
Hi, thank you very much!
This works, but I constantly see an error in the console.
Everything is clean and installed from scratch. I do not understand why this is happening.

[2020-05-20T22_21_59_218Z-debug.log](https://github.com/gatsbyjs/gatsby/files/4659572/2020-05-20T22_21_59_218Z-debug.log)

![image](https://user-images.githubusercontent.com/33329240/82503338-be684b00-9b01-11ea-9af0-df4c90557e9f.png)
