### ISSUE TITLE
Should I be able to use a path such as /v1.0.0

### ISSUE THREAD

**Issue by freaksauce** [gatsbyjs/gatsby#24171]
I'm building a release notes app and want each page to be the release number ie. /v1.0.0. When I refresh the pages or try to direct link they 404 or redirect to the index page. If you use the Gatsby Link to navigate to the pages it works as expected?

### Environment
```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v11.15.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.21.31 => 2.21.31
    gatsby-cli: ^2.12.21 => 2.12.21
    gatsby-plugin-json-output: ^1.1.3 => 1.1.3
    gatsby-remark-copy-linked-files: ^2.3.2 => 2.3.2
    gatsby-remark-prismjs: ^3.5.1 => 3.5.1
    gatsby-source-filesystem: ^2.3.3 => 2.3.3
    gatsby-transformer-remark: ^2.8.8 => 2.8.8
  npmGlobalPackages:
    gatsby-cli: 2.11.4
```

**Comment by blainekasten** [comment]
Hey @freaksauce !

Thanks for the report. I can't think of a reason off the top of my head why this would be problematic. Can you share more code on how this is setup?

**Comment by freaksauce** [comment]
I have pagination setup for the releases archive page I wonder if that is causing issues?
`
const path = require('path')
const { createFilePath } = require('gatsby-source-filesystem')

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions
  const result = await graphql(`
    query {
      site {
        siteMetadata {
          title
        }
      }
      allMarkdownRemark {
        edges {
          node {
            frontmatter {
              path
            }
          }
        }
      }
    }
  `)

  // Create releases pages
  const posts = result.data.allMarkdownRemark.edges
  const postsPerPage = 8
  const numPages = Math.ceil(posts.length / postsPerPage)
  Array.from({ length: numPages }).forEach((_, i) => {
    createPage({
      path: i === 0 ? '/archive' : `/archive/${i + 1}`,
      component: path.resolve('./src/templates/index.js'),
      context: {
        limit: postsPerPage,
        skip: i * postsPerPage,
        numPages,
        currentPage: i + 1
      }
    })
  })

  const singleReleaseTemplate = path.resolve('src/templates/singleRelease.js')
  const { title } = result.data.site.siteMetadata
  posts.forEach(({ node }) => {
    const { path: pathSlug } = node.frontmatter
    createPage({
      path: pathSlug,
      component: singleReleaseTemplate,
      context: {
        pathSlug,
        siteTitle: title
      }
    })
  })
}

exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions
  if (node.internal.type === 'MarkdownRemark') {
    const value = createFilePath({ node, getNode })
    const { title } = node.frontmatter.title
    createNodeField({
      name: 'slug',
      node,
      value,
      title
    })
  }
}
`

**Comment by LekoArts** [comment]
Can you [provide a minimal reproduction][reproduction]?

[reproduction]: https://gatsby.dev/reproduction

**Comment by danabrit** [comment]
Closed due to lack of minimal reproduction. Please re-open once that reproduction is attached to this issue.

**Comment by freaksauce** [comment]
I did make a minimal reproduction site and deployed to Netlify and it worked fine so it must be something to do with my AWS setup.
