### ISSUE TITLE
[gatsby-source-wordpress] ACF not working when there actually is ACF data

### ISSUE THREAD

**Issue by garytokyo** [gatsbyjs/gatsby#2417]
I am having an issue whereby if there are no ACF fields attached to Posts or Pages then the `acf` field is available to use in graphiql. See screenshot:

![screen shot 2017-10-11 at 12 09 14](https://user-images.githubusercontent.com/26624466/31437589-af286cec-ae7d-11e7-870a-e82c0624cef6.png)

When I attach a test field group to Posts the acf field is no longer available and will error saying you cannot use that field on the type wordpress__POST (same for posts or pages):

![screen shot 2017-10-11 at 11 48 31](https://user-images.githubusercontent.com/26624466/31437543-8b7d07d0-ae7d-11e7-8013-f60081b0adaa.png)

I am using ACF Pro (latest) and I have latest acf to rest plugin and latest versions of gatsby and gatsby-source-wordpress. ACF pro was working fine in older version of gatsby and wordpress source plugin when you had to do:

```
childWordpressAcfField {
    internal {
      content
   }
}
```

that query no longer seems to do anything though even though the docs still say this is how to do it.

**Comment by KyleAMathews** [comment]
Does the using-wordpress example site work for you? Can you grep through `.cache/redux-state.json` to see if your acf data is there?

**Comment by garytokyo** [comment]
@KyleAMathews the acf data IS in `redux-state.json` and it shows the correct fields for pages that doe have ACF attached.

**Comment by KyleAMathews** [comment]
Hmmm but the schema isn't being generated correctly then? Just to double-check, you're refreshing graphiql when you restart `gatsby develop` to get the latest schema?

**Comment by garytokyo** [comment]
Correct the schema is not being generated correctly. Yes and just to be sure I deleted .cache and ran develop again to rebuild .cache. The acf field is correct again in `redux-state.json` but if I try and run a GraphQL query on the page with the acf field on I get the error.

```
query aboutPageQuery {
  wordpressPage(wordpress_id: {eq: 7}) {
    title
    content
    slug
    acf
  }
}
```

results in

```
{
  "errors": [
    {
      "message": "Cannot query field \"acf\" on type \"wordpress__PAGE\".",
      "locations": [
        {
          "line": 73,
          "column": 5
        }
      ]
    }
  ]
}
```

And that is the page that has the correct acf data in `redux-state.json`.

**Comment by garytokyo** [comment]
@KyleAMathews is there anything else I can try on this?

**Comment by KyleAMathews** [comment]
Are you on gatsby-source-wordpress v2?

Did you verify that the using-wordpress site works?

**Comment by akmur** [comment]
I have the same issue,, and for me using-wordpress works, while using my own wp install it does not.
I also get the acf fields in redux-state.json

**Comment by KyleAMathews** [comment]
This should be fixed by @chrisgeary92 in #2471!

The issue turned out to be that if you had a post without acf, the API returns `acf:false` which causes all the acf fields to be removed as Gatsby ignores fields with conflicting types. The fix was to just remove the `acf: false` data.

Try out gatsby-source-wordpress@2.0.21 and see if things are working for ya!

**Comment by garytokyo** [comment]
@KyleAMathews Can confirm this fixed my issue thank you very much. Sorry never got back to you from your last reply been away from work.

**Comment by KyleAMathews** [comment]
@garytokyo great! Glad it's working. Credit goes to @chrisgeary92 though as he debugged the issue and wrote the PR :-)
