### ISSUE TITLE
Hitting direct link redirects to main page

### ISSUE THREAD

**Issue by Defite** [gatsbyjs/gatsby#24187]
## Description

I have gatsby project with pages created programmatically with `createPage` inside `createPages`. Both dev and prod modes work good locally, but on the server, while typing direct link manually in the browser (like https://example.com/some-link) I've got redirect to the main page. Nginx doesn't show any redirects, so I'm sure it's Gatsby doing something :) I see no errors in the console of the browser and in my terminal while building this project.

**Comment by blainekasten** [comment]
Hey! Thanks for the report.

If the gatsby app is working as expected with `gatsby develop` and `gatsby serve` it is most likely not related to gatsby, but more specific with your hosting setup. I don't know that we'll be able to give the best advice for Nginx but we can try.

First, can we confirm that the app works as expected in develop and serve?
Second, can you share more of your nginx setup?

**Comment by Defite** [comment]
Hey!

> First, can we confirm that the app works as expected in develop and serve?

Yes, it's working as expected when I build it via `gatsby develop` and `gatsby build`. On remote server it begin working correctly when I disable JS in Chrome, so I suppose it's not Nginx related problem...

**Comment by Defite** [comment]
I've disabled client routing with `gatsby-plugin-static-site` but it shows me the main page when I hit links different from the main page. Any thoughts of what's broken in my project?

**Comment by Defite** [comment]
Sorry, closing this because it is our nginx configuration, Gatsby is ok)

**Comment by LpmRaven** [comment]
How did you fix this? I've got a similar issue with #24601
