### ISSUE TITLE
The Surge CNAME instructions in the tutorial don't work

### ISSUE THREAD

**Issue by j127** [gatsbyjs/gatsby#24206]
## Summary

[This page](https://www.gatsbyjs.org/docs/deploying-to-surge/#step-4-bonus---remembering-a-domain) in the docs says to put a `CNAME` file in the root of the project, but it doesn't seem to work unless the `CNAME` file is in `public` (so it should probably go in `static`).

The surge.sh docs are also unclear about that in their wording.

### Motivation

Anyone who uses the Gatsby tutorial will benefit.

## Steps to resolve this issue

Put the `CNAME` file in `static` instead of at the root of the Gatsby project.

### Draft the doc

I clicked the edit button on Github and it created a fork with my proposed changes [here](https://github.com/j127/gatsby/commit/a95f5d2d17cac766b055f99e7b3ee0a51befb14d). If you want to use those changes I can make a pull request.

**Comment by viveksharmaui** [comment]
I want to work on this issue please assign this issue to me .

**Comment by viveksharmaui** [comment]
I also wants to work on this issue.

**Comment by LekoArts** [comment]
Seems correct, go ahead with the PR @j127 :)

@viveksharmaui The creator of this issue will handle it, feel free to look at other "Help wanted" or "good first issue" issues.
