### ISSUE TITLE
How do I host a static file at a specific url?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#24204]
adding apple pay to stripe and I need to host a text file at a specific URL, as per the instructions:

<img width="476" alt="Screen Shot 2020-05-18 at 4 55 24 PM" src="https://user-images.githubusercontent.com/7884263/82270104-8659e000-9928-11ea-97e5-c3651d20844c.png">

How can I do that with Gatsby?

**Comment by LekoArts** [comment]
Thank you for opening this!

You can use the static folder for this:
https://www.gatsbyjs.org/docs/static-folder/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
