### ISSUE TITLE
Remove image downloading out of query-running for contentful

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#24220]
## Summary

Currently contentful does base64 generating during query-running. It reduces the amount of data being downloaded and process by contentful but we only run 4 queries at a time so this slowdown query-running. 

https://github.com/gatsbyjs/gatsby/blob/2c38a9dfb90b2684d97a092098e849f41d9a47d0/packages/gatsby-source-contentful/src/extend-node-type.js#L51-L77

### Motivation

Make query-running faster

**Comment by axe312ger** [comment]
This will be fixed in the next major version as it requires potentially breaking refactoring to reduce the network requests.

See #25249

**Comment by axe312ger** [comment]
This ticket is directly related https://github.com/gatsbyjs/gatsby/issues/24679#issuecomment-641885490

**Comment by axe312ger** [comment]
@wardpeet 

Hey there,

I wonder how you'd achieve that. Creating these previews is based on the actual query result, we do not need to download 20px variants for all images stored in Contentful, we "just" have to do it for these who are actually rendered with gatsb(-plugin)-image.


Alternatively we might have some king of separate cache for these, that way we could download previews beforehand, store them in the folder and only delete/replace when the actual file changes. Might add some more network requests to the initial load, but should save a lot later on.

What have been your thoughts when opening this?

Benedikt
