### ISSUE TITLE
Wrong return types for some gatsby-ssr hooks

### ISSUE THREAD

**Issue by antoinerousseau** [gatsbyjs/gatsby#24229]
## Description

Some hooks like `onRenderBody` expect to return `any`, when the documentation shows an example returning `void` (no return statement).

### Steps to reproduce

- Create a TS file with 
```ts
import type { GatsbySSR } from "gatsby"

import React from "react"

export const onRenderBody: GatsbySSR["onRenderBody"] = ({ setHeadComponents }) => {
  setHeadComponents([<link key="test" />])
}
```

- Import it in `gatsby-ssr.js` like:
```ts
exports.onRenderBody = require("./src/gatsby/onRenderBody").onRenderBody
```

You might need to add `require("ts-node").register()` to `gatsby-config.js` to make TS work.
Or you can just start from https://github.com/antoinerousseau/gatsby-starter-antoine

### Expected result

No error. Like in the doc: https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody

### Actual result

TS error: `Type 'void' is not assignable to type 'Promise<any>'` (or `to type 'any'`)

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 75.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.20.23 => 2.21.39
    gatsby-image: ^2.3.3 => 2.4.4
    gatsby-plugin-google-analytics: ^2.2.3 => 2.3.1
    gatsby-plugin-manifest: ^2.3.4 => 2.4.5
    gatsby-plugin-netlify: ^2.2.2 => 2.3.2
    gatsby-plugin-react-helmet: ^3.2.3 => 3.3.1
    gatsby-plugin-sharp: ^2.5.5 => 2.6.5
    gatsby-plugin-styled-components: ^3.2.2 => 3.3.1
    gatsby-plugin-typescript: ^2.3.2 => 2.4.2
    gatsby-source-filesystem: ^2.2.3 => 2.3.4
    gatsby-transformer-sharp: ^2.4.5 => 2.5.2
```

**Comment by LekoArts** [comment]
The types are currently hand-written so there might be some errors. We'd be happy to receive an update from you on https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/index.d.ts#L561-L723 though! :)

**Comment by antoinerousseau** [comment]
@LekoArts actually I was about to make a PR on that file, but I decided to open an issue first, to make sure I wasn't mistaken. Can I just replace those `any` with `void`? Do we agree that these hooks shouldn't return anything special?

**Comment by antoinerousseau** [comment]
@LekoArts #24262 :)

**Comment by antoinerousseau** [comment]
Followup at #27149
