### ISSUE TITLE
Provide host and port details to `onCreateDevServer`

### ISSUE THREAD

**Issue by offirgolan** [gatsbyjs/gatsby#24236]
## Summary

Currently the only way to get access to the dev server's host and port is via the `developMiddleware` config option. Unfortunately that isn't very scalable when trying to create plugins to be shared across multiple teams. 

### Basic example

```js
exports.onCreateDevServer = ({ app, host, port }, pluginOptions = {}) => {
  // Setup a proxy to target the current host and port
};
```

### Motivation

The core motivation around this is to be able to attach a proxy server to the host and port that the development server is running on instead of needing to pass it via the plugin options or depending on environment variables.

**Comment by LekoArts** [comment]
Sounds reasonable! We'd be happy to receive a PR implementing this :) Please reach out if you need assistance in getting started with contributing. Thanks!

**Comment by offirgolan** [comment]
I was able to get the host and port via:

```js
const { program } = store.getState();
```
