### ISSUE TITLE
pre-caching images across site or sub-section of site

### ISSUE THREAD

**Issue by migs540** [gatsbyjs/gatsby#2425]
What if we could pre-load images across a site (sub-pages) just as we do for sub-pages? 

At the moment gatsby is (awesomely):

1. loading html
2. then js (including subpage data)
3. Only loading images when you navigate to that page
 
but we kind of lose that customer experience of speed with images. We can do things like progressive reveals as noted in this:

https://github.com/gatsbyjs/gatsby/issues/431

but that seems to be a bit of a workaround because if I have a small site I can make the assumption (perhaps incorrectly!) that people will want to navigate throughout the site, not just the main page. If so it would make sense to:

load html
then js (including subpage data)
then images on sub pages (perhaps defining a sequence order)

Yes, it increases the overall data size downloaded to devices but if it's a small site or you are enabled to specify how much of (how deep in) the sitemap you wanted to go (or determine form factor and download images for that form-factor size only, sitewide) ... well it seems like we can skip some of the progressive reveal (blurred, skeleton, placeholder photos) and extend the benefits of gatsby's speed to photos themselves. Same could go for animations (lottie) or any content. 

precache=yes. 

Or have i missed something basic? webpagespeedtest and chrome developer tools (network, img) seem to show the behaviour I mention above for a webpage i built using gatsby build (and copying the public directory contents to my web server).

**Comment by KyleAMathews** [comment]
This is probably possible but... generally I think what gatsby-image does is better? I.e. use the blur-up technique.

What do you think?

https://using-gatsby-image.gatsbyjs.org

**Comment by migs540** [comment]
@KyleAMathews I'll give gatsby-image a go. Overall I think it's a step towards what is needed but falls short. Blur-up (or skeleton) just isn't the same as revealing a legible image immediately on page display. When images have legibility we grasp their meaning very quickly, in ms.

**Comment by KyleAMathews** [comment]
No definitely agree that having the images already loaded on subsequent pages would be better. The trick is that downloading all images on a site would be a lot of data and saturate the network making other things slower.

So a heuristic for saying 1) only download images on pages highly likely to be visited soon and 2) only download the images that'll be in the initial viewport.

**Comment by migs540** [comment]
and possibly a third heuristic...

So a heuristic for saying 1) only download images on pages highly likely to be visited soon and 2) only download the images that'll be in the initial viewport. or 3) to [maxsitesize] (i.e. if the total site is xxxKB (or some configurable figure), go pre/eager load it all. 

Using [maxsitesize] then supports lightweight web pages by default. For more bulky (more images/data) then heuristics 1  & 2. 

I have a feeling this would be contentious. 

For developers it might seem a bit like apple pushing U2 onto your phone without asking... in this case using people's data without being asked. My hypothesis: heuristic 3 would be likely to increase optimisation thus reducing bloat / data usage.

Another example: youtube preloads/buffers the video before you click play. So it's a heuristic people are familiar with.

**Comment by KyleAMathews** [comment]
Oooo... yes, buffering it's probably the right metaphor. Very nice.

**Comment by KyleAMathews** [comment]
"streaming" and "buffering"

**Comment by KyleAMathews** [comment]
Hey, closing out old issues. Please re-open if you have additional questions, thanks!

**Comment by frederikhors** [comment]
@KyleAMathews any news on this in Gatsby 2?

**Comment by KyleAMathews** [comment]
React suspense will let us do this as you can block rendering on loading critical images. Also we'd love to let plugins add assets to pages to be prefetched. No immediate plans on either.
