### ISSUE TITLE
Gatsby develop with Basic Auth 

### ISSUE THREAD

**Issue by TorrinLynn** [gatsbyjs/gatsby#24266]
## Summary
I have a gatsby site using TinaCMS for content creation and editing. I'm wondering if it's possible to protect the site with basic auth so I can run gatsby develop on a 3rd party provider like Heroku and use an rpm package like basic-auth to protect the site so only content editors can access it. When I deploy to production, I don't want any auth. Thanks for a great product.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by ascorbic** [comment]
Hi,
We don't support basic auth for develop as we're just using webpack-dev-middleware. Your best bet is probably to add a reverse proxy in front of it in Heroku, or perhaps create a plugin that implements onCreateDevServer to add basic auth middleware. If you go for the plugin approach let me know how you get on!

**Comment by TorrinLynn** [comment]
Perfect. I was able to quickly update onCreateDevServer to add basic auth using express-basic-auth. Thanks for your help.

**Comment by bryangruneberg** [comment]
Thanks for the idea to use `onCreateDevServer` @ascorbic!

Our infrastructure (Lagoon from amazee.io) sets two environment variables which we read and respond to. Works well for our development use case! 

Here's the code we use in gatsby-node.js:

```
const basicAuth = require('express-basic-auth')
exports.onCreateDevServer = ({ app }) => {
  if(process.env.BASIC_AUTH_USERNAME && process.env.BASIC_AUTH_PASSWORD) {
    app.use(basicAuth({
      authorizer: (username, password) => {
        const userMatches = basicAuth.safeCompare(username, process.env.BASIC_AUTH_USERNAME)
        const passwordMatches = basicAuth.safeCompare(password, process.env.BASIC_AUTH_PASSWORD)
        return userMatches & passwordMatches
      },
      challenge: true,
      realm: 'insanity',
    }))
  }
}
```
