### ISSUE TITLE
gatsby-source-wordpress: Get menus

### ISSUE THREAD

**Issue by Unforgiven-wanda** [gatsbyjs/gatsby#2426]
Hello again,
There was this [issue](https://github.com/gatsbyjs/gatsby/issues/1612) discussing the manner of getting menus and their locations, with @sebastienfi suggesting to use allWordpressWpApiMenusMenusExtended, but the plugin seems to have been updated since (the docs a bit later, which was confusing) because that node no longer exists.
So my question is: Is there, at the moment, any way to fetch the menus of Worpdress? Possibly according to their location? And if not is there an ETA on this feature?

Thank you.

Edit: I have just now noticed that the docs changed. However, with `WP Api Menus` installed on Wordpress, and the latest Gatsby version running, I can't run the basic example of `AllWordpressWpApiMenusMenuLocations`. Getting the error `Cannot query field \"allWordpressWpApiMenusMenusLocation\" on type \"RootQueryType\". Did you mean \"allWordpressWpApiMenusMenus\", \"wordpressWpApiMenusMenus\", or \"allWordpressWpStatuses\"?`

**Comment by sebastienfi** [comment]
Here you go

```gql

allWordpressWpApiMenusMenusItems {
    edges {
      node {
        name
        count
        items {
          order
          title
          url
          wordpress_children {
            wordpress_id
            title
            url
          }
        }
      }
    }
  }

```

Then, in `render()` : 
`const siteMenus = this.props.data.allWordpressWpApiMenusMenusItems.edges`

Does this gives the data you expected ?

**Comment by sebastienfi** [comment]
Closing this issue, please reopen if you feel that more information is needed :)

**Comment by dmackerman** [comment]
It looks like the routes for the Wordpress plugin have changed?

This seems like the route for me:
`/wp-json/wp-api-menus/v2/menus`

**Comment by braco** [comment]
Also getting an error from the query above
```
{
  "errors": [
    {
      "message": "Cannot query field \"allWordpressWpApiMenusMenusItems\" on type \"Query\". Did you mean \"allWordpressWpStatuses\", \"allWordpressWpTaxonomies\", \"allWordpressGutenbergSearch\", \"allWordpressWpTypes\", or \"wordpressWpStatuses\"?",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
```

**Comment by loganfromlogan** [comment]
I'm using `Version 1.3.1` of the WP API Menus plugin. It's activated, but I go into GraphiQL and there are no options for menus. I've searched but don't see anything. The other queries mentioned in this issue don't work. @braco What version where you using when you go this to work? I first installed the V2 Menus plugin, but then removed it and installed the WP API Menus. Doesn't seemed to have helped.

**Comment by joshuaiz** [comment]
Having this issue as well: Gatsby 2.4.6/WP API Menus 1.3.1/WP 4.9.8

@braco's fix did not work. Also tried completely deleting the .cache directory and no change.

Here is the error:

     43:9  error  Cannot query field "allWordpressWpApiMenusMenusItems" on type "Query". Did you mean "allWordpressWpTaxonomies", "allWordpressWpUsers", "allWordpressSiteMetadata", "allWordpressWpMedia", or "wordpressWpTaxonomies"?  graphql/template-strings

It doesn't even list a suggested query param for the menu. What is the proper query parameter?

**Comment by geocine** [comment]
Thanks @braco  and @joshuaiz , your combined solutions worked for me. However, we should probably move to the `WP-REST-API v2 Menus` , since it is the most recently update Wordpress plugin. The `WP API Menus` was updated 2 years ago. Also, https://github.com/postlight/headless-wp-starter uses `WP-REST-API v2 Menus`

**Comment by eemeeli** [comment]
This seems to be still an issue, I don't get `allWordpressWpApiMenusMenusItems{}` endpoint. 

Just getting `allWordpressWpApiMenusMenuLocations and` `allWordpressWpApiMenusMenus`.

Got the right version of WP-API-MENUS and the current gatsby version is 2.5.4

**Comment by paulmasek** [comment]
Same here @eemeeli. Perhaps this should be reopened?

**Comment by eemeeli** [comment]
@paulmasek I noticed that the "problem" for me was, on the WordPress install. I didn't have default main menu on WordPress and had two custom menus. One for main language and for the secondary language.  Tested with other WordPress site that had only one menu / default main menu the `allWordpressWpApiMenusMenusItems ` appeared

**Comment by paulmasek** [comment]
@eemeeli thanks for that - much appreciated. I do have two custom menus on my wordpress instance and no default one, so perhaps the same issue is occurring for me. Surely a bug though, and a bizarre one at that :/

**Comment by freemh** [comment]
Including `/*/*menus` in `includedRoutes` solve the problem, because before the content of `includedRoutes` was like that:

```
includedRoutes: [
  "**/categories",
  "**/posts",
  "**/pages",
  "**/events",
  "**/menu-locations/**",
  "**/media",
],
```

**Comment by jarrodmedrano** [comment]
Nothing has worked for me.
I tried including /*/*/menus in my includedRoutes

**Comment by jonniebigodes** [comment]
@jarrodmedrano see if [this](https://github.com/gatsbyjs/gatsby/issues/15612#issuecomment-510670862) helps

**Comment by jarrodmedrano** [comment]
@jonniebigodes Yeah I didn't see anything different in your installation the baseUrl. I don't get this /wp-json/wp-api-menus/v2/menus url 404's.

**Comment by jarrodmedrano** [comment]
Thanks. @jonniebigodes I eventually got it to work using your post. But I'm not really sure what the problem was.
