### ISSUE TITLE
Can anyone show me how to write a webhook in gatsby

### ISSUE THREAD

**Issue by iraguhalionel** [gatsbyjs/gatsby#24261]

**Comment by blainekasten** [comment]
@iraguhalionel can you share more about what you are trying to accomplish?

**Comment by iraguhalionel** [comment]
So I deployed gatsby on digital ocean, and I used the strapi cms, so I want anytime API changes to trigger the changes automatically

**Comment by LekoArts** [comment]
Please ask in communities of Strapi or Digitalocean as this isn't something you can configure in Gatsby and hence is not related to this repo. Thanks!
