### ISSUE TITLE
gatsby develop 

### ISSUE THREAD

**Issue by giovannibenussi** [gatsbyjs/gatsby#24260]
## Description

I follow the steps documented in [Website Contributions](https://www.gatsbyjs.org/contributing/website-contributions/) but after running `yarn develop` I get the following error:

![image](https://user-images.githubusercontent.com/1259399/82454915-59b8dc00-9a80-11ea-88a7-3c49213cb00c.png)

### Steps to reproduce

* Clone [gatsby](https://github.com/gatsbyjs/gatsby/)
* run `yarn` to install dependencies
* run `yarn develop`

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Environment

  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
    Yarn: 1.21.0 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v11.10.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0.1
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.21.37 => 2.22.0 
    gatsby-alias-imports: ^1.0.4 => 1.0.4 
    gatsby-core-utils: ^1.2.3 => 1.3.0 
    gatsby-design-tokens: ^2.0.5 => 2.0.5 
    gatsby-image: ^2.4.4 => 2.4.4 
    gatsby-plugin-canonical-urls: ^2.3.1 => 2.3.1 
    gatsby-plugin-catch-links: ^2.3.1 => 2.3.1 
    gatsby-plugin-emotion: ^4.3.1 => 4.3.1 
    gatsby-plugin-feed: ^2.5.1 => 2.5.1 
    gatsby-plugin-google-analytics: ^2.3.1 => 2.3.1 
    gatsby-plugin-google-tagmanager: ^2.3.1 => 2.3.1 
    gatsby-plugin-guess-js: ^1.3.2 => 1.3.2 
    gatsby-plugin-layout: ^1.3.1 => 1.3.1 
    gatsby-plugin-mailchimp: ^2.2.3 => 2.2.3 
    gatsby-plugin-manifest: ^2.4.5 => 2.4.6 
    gatsby-plugin-mdx: 1.2.8 => 1.2.8 
    gatsby-plugin-netlify: ^2.3.2 => 2.3.2 
    gatsby-plugin-netlify-cache: ^0.1.0 => 0.1.0 
    gatsby-plugin-nprogress: ^2.3.1 => 2.3.1 
    gatsby-plugin-offline: ^3.2.3 => 3.2.4 
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1 
    gatsby-plugin-sharp: ^2.6.4 => 2.6.6 
    gatsby-plugin-sitemap: ^2.4.2 => 2.4.2 
    gatsby-plugin-theme-ui: ^0.3.0 => 0.3.0 
    gatsby-plugin-twitter: ^2.3.1 => 2.3.1 
    gatsby-plugin-typography: ^2.5.1 => 2.5.1 
    gatsby-remark-autolink-headers: ^2.3.2 => 2.3.2 
    gatsby-remark-code-titles: ^1.1.0 => 1.1.0 
    gatsby-remark-copy-linked-files: ^2.3.2 => 2.3.2 
    gatsby-remark-embedder: ^1.16.0 => 1.16.0 
    gatsby-remark-graphviz: ^1.3.1 => 1.3.1 
    gatsby-remark-http-to-https: ^1.0.2 => 1.0.2 
    gatsby-remark-images: ^3.3.4 => 3.3.5 
    gatsby-remark-normalize-paths: ^1.0.0 => 1.0.0 
    gatsby-remark-prismjs: ^3.5.1 => 3.5.1 
    gatsby-remark-responsive-iframe: ^2.4.2 => 2.4.2 
    gatsby-remark-smartypants: ^2.3.1 => 2.3.1 
    gatsby-source-airtable: ^2.1.1 => 2.1.1 
    gatsby-source-filesystem: ^2.3.4 => 2.3.5 
    gatsby-source-git: ^1.0.2 => 1.0.2 
    gatsby-source-npm-package-search: ^2.3.3 => 2.3.3 
    gatsby-transformer-csv: ^2.3.1 => 2.3.1 
    gatsby-transformer-documentationjs: ^4.3.1 => 4.3.1 
    gatsby-transformer-gitinfo: ^1.1.0 => 1.1.0 
    gatsby-transformer-remark: ^2.8.9 => 2.8.10 
    gatsby-transformer-screenshot: ^2.3.5 => 2.3.6 
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2 
    gatsby-transformer-yaml: ^2.4.1 => 2.4.1

**Comment by blainekasten** [comment]
Hey @giovannibenussi.

The error listed there (`spawn EAGAIN`) has this as it's explanation:

![image](https://user-images.githubusercontent.com/2916023/82457807-7ef71b80-9a7b-11ea-8352-18836b6f91f3.png)

I'm not sure how to advise on this as it's likely dependent on your machine and configuration. I would encourage looking into how to address this general process error on your machine.

I'm going to close this issue as I don't see any way we can fix this within our codebase right now. If you have any ideas or further questions feel free to keep discussing in this issue. 💜
