### ISSUE TITLE
Webpack Error, static-entry: transpile

### ISSUE THREAD

**Issue by yasserzubair** [gatsbyjs/gatsby#2427]
Hi there,
Whenever I try to build, I am getting this error. Can anyone please tell me whats it related to and how can I get rid of it.

`
> 1 | import React from "react"
    | ^
  2 | import { renderToString, renderToStaticMarkup } from "react-dom/server"
  3 | import { StaticRouter, Route, withRouter } from "react-router-dom"
  4 | import { kebabCase, get, merge, isArray, isString } from "lodash"

  WebpackError:

  - static-entry.js:1 transpile
    .cache/static-entry.js:1:1

  - static-entry.js:7
    .cache/static-entry.js:7:1

  - React.js:82 FSReqWrap.readFileAfterOpen [as oncomplete]
    ~/react/lib/React.js:82:1`

**Comment by KyleAMathews** [comment]
Does this happen in the default starter?

**Comment by halloween603** [comment]
Hi there,
I am also getting the same error.
Yeah it is happening in the default starter.

**Comment by halloween603** [comment]
Hi,
I am also getting the same error while building. can anyone help me out to get rid of it.
Yeah it is happening in default starter only.

**Comment by hirviid** [comment]
@yasserzubair @halloween603 Did you find the cause / solution for this?

**Comment by DarrylD** [comment]
I'm getting the same error out of nowhere. Any idea what It would be?

**Comment by arnondora** [comment]
I also got this error. Is there any solution?

**Comment by Metturan** [comment]
Hi,

have this same error, can't build or deploy. Any solution for this?

**Comment by arnondora** [comment]
I have no `.babelrc` in any directory in my project. For me, it might from something else?

**Comment by apnerve** [comment]
@arnondora Are you also getting "Webpack Error"?

**Comment by arnondora** [comment]
Yes, I also got webpack error. Now, the problem is gone but I don’t know why. I just re-build project again and again.

**Comment by alexmacarthur** [comment]
Having this same issue as well. Anyone have any ideas?

**Comment by Redmega** [comment]
Facing this same issue, no `.babelrc` here.

**Comment by Redmega** [comment]
Mine looks a bit different, probably because of the newer gatsby version:

```
1 | import React from "react"
    | ^
  2 | import { renderToStaticMarkup } from "react-dom/server"
  3 | import { merge } from "lodash"
  4 | import apiRunner from "./api-runner-ssr"


  WebpackError:

  - develop-static-entry.js:1 transpile
    .cache/develop-static-entry.js:1:1

  - develop-static-entry.js:7
    .cache/develop-static-entry.js:7:1
```

**Comment by arnondora** [comment]
Sometime I just remove some of graphql query in the `gatsby-node.js` And build, it worked.  Then I just add the part that has removed and build again, it also work. I still don’t know why this problem happened.

**Comment by Redmega** [comment]
In my case it ended up being a syntax error that eslint wasn't alerting me to for some reason. I had a missing ] in my `typography.js`. Run your code through eslint and make sure there are no errors

**Comment by yasserzubair** [comment]
Mine also ended up being a syntax error.

**Comment by grundmanise** [comment]
same for me.. it was a syntax error.

**Comment by alexmacarthur** [comment]
Same here -- syntax error. Specifically, I had some JSON-LD structured data I was outputting inside of `<Helmet></Helmet> tags. Just missing a comma, but wasn't notified clear of that in my terminal.

**Comment by elrumordelaluz** [comment]
In case could be useful for someone having this issue, in my case was using `yeld` inside a function not declared as _generator_ so without `*`, adding it solved this issue.

**Comment by hogyun3709** [comment]
Hi I have got a simple solution for this error which is replacing "gatsby-config.js" file name to "gatsby.config.js". Try this :)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by JustFly1984** [comment]
I got this error then updating gatsby from 2.5.3 to 2.10.0
