### ISSUE TITLE
enhancement (docs, www, gatsby): Generate API docs from type definitions

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#24283]
## Overview

Generate API documentation from [gatsby/index.d.ts](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/index.d.ts) instead of a variety of files.

## Motivation

* Ensures that our API docs are always up-to-date with our types.
* Makes it easier for us to translate APIs, since the documentation is separated from implementation.

## Intermediate steps

* Create typedefs for node helper API #24280 
* Create typedefs for the Node Model
* Add the documentation for the rest of the docs

## Considerations

* Some APIs have multiple definitions, for example [`sourceNodes`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/index.d.ts#L418). We either need to consolidate all the typings or show each typing separately (which may be beneficial?)
* Some APIs are typed with very specific interfaces: for example, `createPages` and `CreatePagesArgs`. We need to figure out how to destructure these interfaces or override them.

**Comment by imrishabh18** [comment]
@tesseralis I am a beginner Can I take up this issue ?

**Comment by tesseralis** [comment]
Hi @imrishabh18, this is a pretty involved issue so it's probably not a good idea. Please see the issues labeled ["Good first issue"](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+) for good issues for you to tackle!
