### ISSUE TITLE
Gatsby mdx render error: Error: Element type is invalid: expected a string (for built-in components) or a class/function

### ISSUE THREAD

**Issue by javialon26** [gatsbyjs/gatsby#24284]
## Description

When I use shortcodes for my components in MDX and the component is in the form of ```<Nav.Item as="li">Hello</Nav.Item>``` a render error occurs.

If I import the component directly in the MDX file everything works but with shortcodes no.

### Steps to reproduce

See the index.mdx file and the layout component in /components. Another test is made with create page API in gatsby-node and src/templates/blog-post.js.

Reproduction link: https://codesandbox.io/s/admiring-bhaskara-gc4v1?file=/src/pages/index.mdx:293-327 

### Expected result

Render the mdx file.

### Actual result

Render error.
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of `MDXContent`.
```

### Environment

```
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.4 => 2.22.4
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-plugin-emotion: ^4.3.2 => 4.3.2
    gatsby-plugin-manifest: ^2.4.8 => 2.4.8
    gatsby-plugin-mdx: ^1.2.11 => 1.2.11
    gatsby-plugin-netlify: ^2.3.3 => 2.3.3
    gatsby-plugin-netlify-cms: ^4.3.3 => 4.3.3
    gatsby-plugin-offline: ^3.2.6 => 3.2.6
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2
    gatsby-plugin-sharp: ^2.6.8 => 2.6.8
    gatsby-remark-copy-linked-files: ^2.3.3 => 2.3.3
    gatsby-remark-images: ^3.3.7 => 3.3.7
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-source-filesystem: ^2.3.7 => 2.3.7
    gatsby-transformer-remark: ^2.8.12 => 2.8.12
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3
  npmGlobalPackages:
    gatsby-cli: 2.8.3
```

**Comment by laurieontech** [comment]
Hey @javialon26, thanks for the issue! 

This is a known problem in MDX itself. There is currently a [PR to address it](https://github.com/mdx-js/mdx/pull/953). I'm going to close this issue as its not something the Gatsby repo can address, but as soon as that PR is merged you should be good to go.

**Comment by ciacicode** [comment]
When will the PR be merged? I am still affected by the issue...

**Comment by laurieontech** [comment]
Hi @ciacicode, MDX is a separate project, so I can't be sure. However, it appears that this will be fixed in MDX v2 rather than in that PR.
