### ISSUE TITLE
How to store form data in mysql table in gatsby?

### ISSUE THREAD

**Issue by Anbarasan321** [gatsbyjs/gatsby#24295]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by ascorbic** [comment]
Hello,
Please can you complete the issue description. We need the information if we are to understand your question. Thanks.

**Comment by Anbarasan321** [comment]
I have connected the database and fetch the data correctly using the below codes (gatsby-config.js).
```
resolve: `gatsby-source-mysql`,
      options: {
        connectionDetails: {
          host: 'localhost',
          user: 'root',
          password: '',
          database: 'test'
        },
        queries: [
          {
            statement: 'SELECT * FROM contact',
            idFieldName: 'contactID',
            name: 'name'
          }
        ]
      }
```
I have a form on contact page like below(contact.js)
```
<form onSubmit={this.handleSubmit}>
        <label>
          Name
          <input
            type="text"
            name="name"
            value={this.state.name}
            onChange={this.handleInputChange}
          />
        </label>
        <button type="submit">Submit</button>
      </form>
```

Now I want to store this form value on the MySQL test table. kindly check and share the solution for this.

Thanks.
