### ISSUE TITLE
How to view single data based on the selection on the other page in gatsby with mysql?

### ISSUE THREAD

**Issue by Anbarasan321** [gatsbyjs/gatsby#24298]
I have connected the database and fetch the data correctly using the below codes (gatsby-config.js).

```
resolve: `gatsby-source-mysql`,
      options: {
        connectionDetails: {
          host: 'localhost',
          user: 'root',
          password: '',
          database: 'test'
        },
        queries: [
          {
            statement: 'SELECT * FROM contact',
            idFieldName: 'contactID',
            name: 'name'
          }
        ]
      }
```
and displayed above datas on the main file (index.js)
```
{data.allMysqlName.edges.map(({ node }) => (
              <a href="/contact/{node.id}" className="grey-text">
                {node.name}
              </a>
          ))}
```

I got a list of contacts on the index page now, I want to view any particular contact details like their email, phone data on the contact page("/contact/{node.id}").

kindly share the solution for this.

Thanks.

**Comment by freiksenet** [comment]
Hi @Anbarasan321!

You can query a single item by using single query field, rather than an `all` field. It your case it would probably look as follows:

```graphql
query {
  mysqlName(id: "your-id") { # or you can use graphql variables
    id
    email
    phone
  }
}
```

Thank you for using Gatsby! :purple_heart:
