### ISSUE TITLE
How to store form data in mysql table in gatsby?

### ISSUE THREAD

**Issue by Anbarasan321** [gatsbyjs/gatsby#24297]
I have connected the database and fetch the data correctly using the below codes (gatsby-config.js).

```
resolve: `gatsby-source-mysql`,
      options: {
        connectionDetails: {
          host: 'localhost',
          user: 'root',
          password: '',
          database: 'test'
        },
        queries: [
          {
            statement: 'SELECT * FROM contact',
            idFieldName: 'contactID',
            name: 'name'
          }
        ]
      }
```
I have a form on contact page like below(contact.js)

```
<form onSubmit={this.handleSubmit}>
        <label>
          Name
          <input
            type="text"
            name="name"
            value={this.state.name}
            onChange={this.handleInputChange}
          />
        </label>
        <button type="submit">Submit</button>
      </form>
```
Now I want to store this form value on the MySQL test table. kindly check and share the solution for this.

Thanks.

**Comment by jonniebigodes** [comment]
@Anbarasan321 you can't, that plugin like most of the plugins for Gatsby they work on a "one way street approach", meaning that they can only pull in data into the site, To add data you'll have to change the way you approach this. You'll need to make some chages and create some type of middleware to make those changes.

Feel free to provide feedback

**Comment by freiksenet** [comment]
Hello @Anbarasan321!

Gatsby source plugins, as a rule, only retrieve data and don't ever write data back. If you want to do writes to the database, you would need an API that would receive request from your Gatsby site and write them to your database. You would also like need to setup a trigger on a change that would rebuild your Gatsby website.

Currently we don't have plans to change the behavior of source plugins, as that would require a big number of architectural changes to Gatsby.

Hope that helps! Thank you for using Gatsby! :purple_heart:
