### ISSUE TITLE
How to view single data based on the selection on the other page in gatsby with mysql?

### ISSUE THREAD

**Issue by Anbarasan321** [gatsbyjs/gatsby#24296]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by ascorbic** [comment]
Hi,
I'm goign to close this as you have not included a description, nor any details to help us understand the issue. You are welcome to open a new ticket with the full information requested in the template.
Thanks
