### ISSUE TITLE
[gatsby-config] TypeScript project failed after 2.22.x version

### ISSUE THREAD

**Issue by rroslaniec** [gatsbyjs/gatsby#24293]
## Description

In our company we got gatsby files migrated to TypeScript (e.g. gatsby-config.ts). After https://github.com/gatsbyjs/gatsby/issues/22759 we are not able to start project.

### Steps to reproduce

create `gatsby-config.ts`
create npm scripts:
    "gatsby:ts": "ts-node -r tsconfig-paths/register -T ./node_modules/.bin/gatsby",
    "start": "npm run gatsby:ts -- develop",

### Expected result

Project should just run.

### Actual result

 ERROR #10124  CONFIG

It looks like you were trying to add the config file? Please rename "gatsby-config.ts" to "gatsby-config.js"

  Error: Cannot find module '/path/to/project/gatsby-config'

**Comment by ascorbic** [comment]
Hi,
While this may have worked before, we don't (yet) officially support writing your config files in TypeScript so unfortunately it's not something that we can help with right now. However some members of the community do this, so you may like to look at @Js-Brecht 's plugin [gatsby-plugin-ts-config](https://github.com/Js-Brecht/gatsby-plugin-ts-config) and see if that helps. We will be adding support for writing them in TypeScript soon as part of a our migraiton project.

**Comment by Js-Brecht** [comment]
@rroslaniec as you probably noticed already, that PR makes Gatsby run in a child process, which means the `ts-node` instance you started your project with won't have any effect.  With `gatsby-plugin-ts-config`, Typescript support will be set up during Gatsby's lifecycle, which will happen inside of the child process, so it should work for what you're doing.

If you wind up having any problems with it, please feel free to file an issue [in the repo](https://github.com/Js-Brecht/gatsby-plugin-ts-config/issues)

**Comment by tombohub** [comment]
Then why does your template creates config file in Typescript?

**Comment by tmkasun** [comment]
Hi Team,
I'm getting the same error

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/3313885/170820246-c6f4f186-56fa-4e83-b5fd-5090ec2ec074.png">


when i started 
```
npm start
```
for the second time , just after initializing the project using

```
npm init gatsby
```

I have followed this [official doc](https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/)

**Comment by alexanderbluhm** [comment]
I resolved the error by using `gatsby clean`.
(If this command does not work for you, you can just add `"clean": "gatsby clean"` to the `scripts` section of your package.json and call `npm run clean`)
