### ISSUE TITLE
How to a script tag with code that has backslashes via setHeadComponents?

### ISSUE THREAD

**Issue by szimek** [gatsbyjs/gatsby#24304]
## Summary
I'm trying to add a script provided by NewRelic to `<head>` element in `gatsby-ssr.js` using `setHeadComponents`:
```jsx
exports.onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <script dangerouslySetInnerHTML={{__html: `window.NREUM||(NREUM={})...`}} />
  ]);
});
```

The problem is that this NewRelic code has a few regexes in it that include backslashes, e.g.
```js
var a=/Version\/(\S+)\s+Safari/;
```

When I add this snippet as a string, all backslashes (`\`) are treated as escape characters and it becomes:
```js
var a=/Version/(S+)s+Safari/;
```
which of course throws "invalid syntax" error. 

I'm probably missing something obvious here, but is there a way to add this code in a script tag without manually escaping all backslashes? Also, is there a way to ensure that it's added as the first script tag in `<head>`?

**Comment by LekoArts** [comment]
Thank you for opening this!

> I'm probably missing something obvious here, but is there a way to add this code in a script tag without manually escaping all backslashes?

This is something that React does and not Gatsby. My shallow look into this issue says that you'll probably have to escape your backslashes. Or put the content into it's own file, place it inside `static` and require it like usual.

> Also, is there a way to ensure that it's added as the first script tag in <head>?

You can manually re-order the elements in those SSR hooks, like shown in this issue: https://github.com/gatsbyjs/gatsby/issues/23473#issuecomment-619902689

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
