### ISSUE TITLE
"ENOENT: no such file or directory, with yarn

### ISSUE THREAD

**Issue by Tanvesh-11** [gatsbyjs/gatsby#24302]
## Description

Got an unexpected error while using yarn
Error-
An unexpected error occurred: "ENOENT: no such file or directory, lstat '/home/pi/node_modules/mozjpeg/\u0001�\u0017@@�\u000f\f@8\b@\u001eu0006\u0005@@@@@�\u0001�\u0001\b\u0003\u0004\u0002\u0002@\u0002@\u001c\u001c\u0001\u0001\u0005@@\u001c�'".

I m currently using raspbian OS
yarn version: 1.22.4
node version: 10.20.1

I tried cleaning the npm and yarn cache and also tried downgrading the node version

**Comment by freiksenet** [comment]
Unfortunately I'm not sure what could cause this error, however it's weird that the path to `node_modules` is directly from your home folder. Can you confirm that you are running `yarn` from your Gatsby site directory?

**Comment by Tanvesh-11** [comment]
Yes!
Although I guess it's problem with R-pi processor - 32-bit Arm Cortex-A72

**Comment by AkimaLunar** [comment]
I just had the same issue 😬 I have `build-essential` and `libpng-dev`. Anything else I am missing?

- Ubuntu 20.04.2 LTS
- Node 14.16.1
- Yarn 1.22.10

```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/home/riacarmin/Code/ReactVancouver/website/node_modules/mozjpeg/\u0001�\u0017@@�\u000f\f@8\b@\u001eu0006\u0005@@@@@�\u0001�\u0001\b\u0003\u0004\u0002\u0002@\u0002@\u001c\u001c\u0001\u0001\u0005@
```
