### ISSUE TITLE
enhancement(gatsby-source-contentful) publishedAt and firstPublishedAt fields

### ISSUE THREAD

**Issue by thijs-van-der-velden** [gatsbyjs/gatsby#24303]
## Summary

Currently content nodes only pick up the `updatedAt` and `createdAt` fields from the contentful API response. I would like to suggest a change to also include the `publishedAt` and `firstPublishedAt` fields.

### Motivation

I am working on a project that requires us to sort a list of entries by their publish date.

**Comment by freiksenet** [comment]
Hello @thijs-van-der-velden!

That would indeed be a nice feature. Would you be interested in creating a PR that would add that functionality? You would likely need to modify [this file](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/normalize.js#L430) in contentful source.

Also pinging @axe312ger.

**Comment by axe312ger** [comment]
The gatsby source plugin uses the sync api. The delivery/sync api does not have access to this attribute:

https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/common-resource-attributes


But the new Contentful graphql api does support this attribute:

https://www.contentful.com/developers/docs/references/graphql/#/reference/schema-generation/sys-field

As soon the gatsby source plugin supports the contentful graphql api, this tickets should be solved automatically. (See disclaimer: https://www.contentful.com/developers/docs/references/graphql/#/introduction/basic-api-information)


I'll readd it to the GitHub project so we can keep track of this :)

**Comment by chawes13** [comment]
Is this information available now? Having trouble locating it (7.6.1)

**Comment by axe312ger** [comment]
@chawes13 no, you only have available what you see in GraphQL

The new version will contain the (first) publish date. see #31385
