### ISSUE TITLE
Console warnings with Theme-UI Styled component in latest Gatsby versions

### ISSUE THREAD

**Issue by ehowey** [gatsbyjs/gatsby#24327]
**Describe the bug**
Since updating to the latest version of Gatsby I am seeing a bunch of console warnings that look like this:

```shell
warn ESLintError: 
/Users/erichowey/Coding/erichoweydev/src/components/work-card.js
  44:9  warning  Imported JSX component h4 must be in PascalCase or SCREAMING_SNAKE_CASE  react/jsx-pascal-case
  45:9  warning  Imported JSX component p must be in PascalCase or SCREAMING_SNAKE_CASE   react/jsx-pascal-case
  48:9  warning  Imported JSX component p must be in PascalCase or SCREAMING_SNAKE_CASE   react/jsx-pascal-case
```
Basically what is happening is that it doesn't like the `<Styled.p>` syntax and is complaining. Not a big deal - but maybe worrying for newer users of Theme-UI.  Not sure if this would be resolved here or on the Gatsby end so I will cross post it.

Related to: https://github.com/system-ui/theme-ui/issues/947

**Comment by maiertech** [comment]
This is back in 2.31.0.
