### ISSUE TITLE
useStaticQuery not working in coffeescript

### ISSUE THREAD

**Issue by ivands** [gatsbyjs/gatsby#24320]
## Description
I'm getting the following error after using the useStaticQuery hook in a coffeescript file:
```
Error: The result of this StaticQuery could not be fetched.
This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
```

## Code
```coffeescript

import React from 'react'
import PropTypes from 'prop-types'
import { Helmet } from 'react-helmet'
import { useStaticQuery, graphql } from 'gatsby'

export default SEO = ({ title, description = '', lang = 'en', meta = [] }) ->
	{ site } = useStaticQuery graphql"
		query {
			site {
				siteMetadata {
					title
				}
			}
		}
	"

	metaDescription = description or site.siteMetadata.description

	<Helmet
		htmlAttributes={{ lang }}
		title={ title }
		titleTemplate={ "%s | #{ site.siteMetadata.title }" }
		meta={ [
			{ name: 'description',			content: metaDescription }
			{ property: 'og:title',			content: title }
			{ property: 'og:description',	content: metaDescription }
			{ property: 'og:type',			content: 'website' }
			{ name: 'twitter:card',			content: 'summary' }
			{ name: 'twitter:creator',		content: site.siteMetadata.author }
			{ name: 'twitter:title',		content: title }
			{ name: 'twitter:description',	content: metaDescription }
		].concat meta }
		/>

```

## Steps to reproduce
I'm simply using the gatsby-plugin-coffeescript plugin and trying to use the useStaticQuery hook.

## Environment
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.0 - ~/.nvm/versions/node/v12.13.1/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0.1
    Safari: 13.1
  npmGlobalPackages:
    gatsby-cli: 2.12.24

**Comment by wardpeet** [comment]
Hey @ivands,

I'm going to close this issue as you'll likely have more issues along the way than just this one. We're happy to accept a pr to fix staticQueries in Gatsby with coffeescript.


Thanks for understanding and using Gatsby 💪
