### ISSUE TITLE
gatsby-transformer-remark does not populate fileAbsolutePath property on MarkdownRemark nodes when parents are not of type "File"

### ISSUE THREAD

**Issue by mirabilio** [gatsbyjs/gatsby#24322]
## Description
In order to provide data consistency for consumers of `MarkdownRemark` nodes and provide for a wider range of use cases, I would like to propose that this plugin populate its `fileAbsolutePath` property regardless of the parent's type. [At this line](https://github.com/gatsbyjs/gatsby/blob/c4c7563d8dc167561962c4ab7c6ef8f2e2d3eec9/packages/gatsby-transformer-remark/src/on-node-create.js#L57), the plugin does not populate `fileAbsolutePath` unless the parent is a `File` type.

An example scenario where this is a problem:
[My plugin `gatsby-plugin-json-remark`](https://github.com/mirabilio/gatsby-plugin-json-remark) creates MarkdownRemark nodes from markdown snippets contained in JSON files and in this use case, the `MarkdownRemark` parent's type is `JsonRemark`, not `File`.

Further down the lifecycle, `TinaCMS` consumes `MarkdownRemark` nodes produced by `gatsby-plugin-json-remark` and expects the `fileAbsolutePath` property to be present. [It fails](https://github.com/tinacms/tinacms/blob/c70c023233020cd8cb77e1fe9ee46139dd53722d/packages/gatsby-tinacms-remark/gatsby-node.js#L37) because the value is not present.

I think it would be ideal if this field is always populated as long as `absolutePath` property is present in the parent node. This would bring consistency for plugins that create `MarkdownRemark` nodes outside the usual use case of source .md files.

For reference, the issue opened by a user: [5](https://github.com/mirabilio/gatsby-plugin-json-remark/issues/5)

**Comment by pieh** [comment]
I think we should actually do complete opposite :P and not set `fileAbsolutePath` at all on remark nodes - this is bad practice because remark node itself doesn't care where the data came from (it only is concerned with content). It would be still accessible if someone actually needed it (get parent node - if it's a File get path from that). 

We actually don't know what to set it to if it's not coming from File - so it should be empty string - it might work for `.replace` case - but would break if someone actually tries to read a file etc, so it's not exactly fixing issue - it's masking it.

But this is breaking change of course, so we likely won't do anything like that soon.

**Comment by mirabilio** [comment]
Agreed 100% that `fileAbsolutePath` should not be set at all. Users should go to parent to get source information (e.g. path and file info for files). The `MarkdownRemark` nodes should be completely ignorant of where/how the content was sourced.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
