### ISSUE TITLE
gatsby develop doesn't work " SyntaxError: expected expression, got '<' "  and other issues.

### ISSUE THREAD

**Issue by AbdallahAbis** [gatsbyjs/gatsby#24328]
#24058  Description

gatsby develop doesn't seem to work on `Localhost` I experienced this just today, I've created a new gatsby project by doing

`npx gatsby new Productly`

and then 

`cd Productly`

then

`gatsby develop`

the website loads just fine, but once I **### refresh it** the error shows up.

### Expected result

to reload just fine and keep hot reloading.

#### _===> Firefox_
I get these errors
`The connection to http://localhost:8000/__webpack_hmr was interrupted while the page was loading.`
`SyntaxError: expected expression, got '<'`

![img](https://i.imgur.com/usRNvi6.png)

#### _===> Chrome_
the browser keeps reloading non-stop, and it shows some errors on the console but I couldn't read all of them. here are some errors that I could get by stopping the refresh.

`Uncaught (in promise) Error: Manifest request to /9e7b27f5efbfea19e53d.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (bootstrap:41)`

![img](https://i.imgur.com/dwT7lws.png)

`global-shortcut.js:10 Uncaught TypeError: Cannot read property 'hasAttribute' of null
    at global-shortcut.js:10
    at global-shortcut.js:10`

![img](https://i.imgur.com/YWIDoCG.png)

### Environment

 System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.21.37 => 2.21.37
    gatsby-image: ^2.4.4 => 2.4.4
    gatsby-plugin-manifest: ^2.4.5 => 2.4.5
    gatsby-plugin-offline: ^3.2.3 => 3.2.3
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-sharp: ^2.6.4 => 2.6.4
    gatsby-source-filesystem: ^2.3.4 => 2.3.4
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2

**Comment by freiksenet** [comment]
Hi!

Do you seen any errors from console where you are running your develop server?

**Comment by AbdallahAbis** [comment]
@freiksenet the errors I can see when I run gatsby develop are mentioned above. In the terminal I don't see any.

**Comment by AbdallahAbis** [comment]
###  fixed by clearing the cache of the whole browser. Thank You, Guys!
