### ISSUE TITLE
[gatsby-plugin-mdx] Cannot set property 'dirty' of undefined with gatsby-remark-vscode

### ISSUE THREAD

**Issue by cristiano-belloni** [gatsbyjs/gatsby#24339]
## Description

When I try to use the `gatsby-remark-vscode` in the `gatsbyRemarkPlugins` field of the `gatsby-plugin-mdx` options, I get:

``` 
TypeError: Cannot set property 'dirty' of undefined

  - inference-metadata.js:187 incrementalReducer
    [myproj]/[gatsby]/dist/redux/reducers/inference-metadata.js:187:27

  - inference-metadata.js:55 module.exports
    [myproj]/[gatsby]/dist/redux/reducers/inference-metadata.js:55:25
```

This happens only if I have a code fence in my pages

### Steps to reproduce

Run this configuration and put a 3-backtick code fence in one of your mdx pages:

```
module.exports = {
  siteMetadata: {
    title: `MyProj`,
    description: `My Project`,
    author: `Me`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`,
      },
    },
    {
      resolve: "gatsby-plugin-web-font-loader",
      options: {
        google: {
          families: ["Noto Sans", "Inconsolata", "Roboto"],
        },
      },
    },
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        defaultLayouts: { default: path.resolve("./src/components/layout.js") },
        gatsbyRemarkPlugins: [
          {
            resolve: `gatsby-remark-vscode`,
          },
        ],
      },
    },
  ],
}
```

### Expected result

I should see the highlighting plugin working

### Actual result

The plugin breaks in gatsby-plugin-mdx's `inference-metadata.js` with the message `TypeError: Cannot set property 'dirty' of undefined`

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 74.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.21.37 => 2.21.37
    gatsby-image: ^2.4.4 => 2.4.4
    gatsby-plugin-manifest: ^2.4.5 => 2.4.5
    gatsby-plugin-mdx: ^1.2.11 => 1.2.11
    gatsby-plugin-offline: ^3.2.3 => 3.2.3
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-sharp: ^2.6.4 => 2.6.4
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-vscode: ^2.1.1 => 2.1.1
    gatsby-source-filesystem: ^2.3.4 => 2.3.4
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2
```

**Comment by laurieontech** [comment]
Thanks for opening an issue! I ran a separate project with the plugin and code fences and didn't see this issue. I noted your config file above, would you be able to point to a repo with a full reproduction of what you have running?

**Comment by cristiano-belloni** [comment]
>  would you be able to point to a repo with a full reproduction of what you have running?

Thanks! Here it is: https://github.com/cristiano-belloni/gatsby-bug

**Comment by laurieontech** [comment]
Thanks so much! So the issue here is that `gatsby-plugin-mdx` isn't creating any nodes, so that plugin is trying to operate on something that's undefined.

While you have an mdx file in `/src/pages` the plugin is not operating on it because the `gatsby-source-fileystem` plugin is not configured to do so. 

To fix the issue you can add the following to your gatsby-config.js file:

```
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages`,
      },
    },
```

The long answer is in [this issue](https://github.com/gatsbyjs/gatsby/issues/15594).

**Comment by cristiano-belloni** [comment]
That makes sense, thanks!
