### ISSUE TITLE
Support "traced placeholder" generation in gatsby-plugin-sharp

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#2435]
Ran across on Twitter this really cool demo of a generating outlines of images and using them as placeholders while loading the image:

https://twitter.com/mikaelainalem/status/918213244954861569

![s5o6zbl1icr_eftt](https://user-images.githubusercontent.com/71047/31520549-0ad1d064-af5b-11e7-97cf-b3f70baa1f34.gif)

It'd be fun if we could build this into our image processing pipeline

[Following this thread](https://twitter.com/Martin_Adams/status/918481838347292678) which suggested using a unix tool named [potrace](http://potrace.sourceforge.net/). There's also a [little-used JS port of potrace](https://www.npmjs.com/package/potrace).

If anyone wants to experiment with this, it'd be a really cool addition to Gatsby!

**Comment by benjaminhoffman** [comment]
I think this has been merged yeah?  Can close issue?

**Comment by KyleAMathews** [comment]
Indeed!

**Comment by hackhat** [comment]
This should be added to gatsby-remark-images to be consistent, otherwise some images will be blurred, others will have svg.

**Comment by m-ttriley** [comment]
why did u guys add this

**Comment by abheist** [comment]
It's breaking for large images!
