### ISSUE TITLE
Will Gatsby switch to React Router now?

### ISSUE THREAD

**Issue by rememberlenny** [gatsbyjs/gatsby#24375]
## Summary

Considering React Router is deciding to double down on RR instead of Reach, will Gatsby be integrating now?

## Relevant information

https://reacttraining.com/blog/reach-react-router-future/

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

Our plan is to move back to react-router however we'll first need to make sure that it's as accessible as the current `@reach/router` we use. Furthermore, there might be some breaking changes so we're tracking this really here: https://github.com/gatsbyjs/gatsby/issues/15277 (This is not an umbrella issue)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
