### ISSUE TITLE
Using custom GraphQL queries in Private routes

### ISSUE THREAD

**Issue by lukebyrne73** [gatsbyjs/gatsby#24371]
## Summary
I'm building a gatsby app where users can log in and search for different products. They need to be logged in to see the table of products. Given this, the table is a component that is called in a private route. I want to let the user filter products, but because my private routes must be called as components, I need to use Static Query and can't pass variables to GraphQL. 

Ideally, I'd like to figure out how to let private pages live in the /pages directory without them being called as a component, but still having them behind an auth wall, so that I can use GraphQL with user inputted variables.

**Comment by herecydev** [comment]
The graphql is designed for building the static pages out. When you add client-only paths, it's supported but there's no mechanism to query the graphql at runtime because there's no server involved.

If you want user querying/filtering I think you will have to design the architecture yourself. Hope that helps.

**Comment by LekoArts** [comment]
Thank you for opening this!

As commented the GraphQL data layer that Gatsby provides is only available at build time and not on the client-side. When you create private routes/client-only pages only a HTML shell is rendered. You'll need to use something like Apollo Client or urql to query your data.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
