### ISSUE TITLE
How to filter products being pulled in by gatsby-source-shopify plugin?

### ISSUE THREAD

**Issue by alvisanovari** [gatsbyjs/gatsby#24376]
How do we filter out some products from the initial GraphQL query? I see there is an includeCollections argument in the plugin that defaults to includeCollections: ["shop", "content"]. However changing this to any of my collections only breaks the query. Is there a different id we need to use rather than the collection name to filter to products in only that collection?

**Comment by LekoArts** [comment]
Thank you for opening this!

You can use the `filter` options provided in the GraphQL query to filter for your specific products. Our reference page will give you an idea how that works and a complete list of all available operators: https://www.gatsbyjs.org/docs/graphql-reference/#filter

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by alvisanovari** [comment]
Thank you. Would filtering in the product GraphQL query reduce the total number of static files since the initial query will still load everything? My worry is the overall site size gets bloated even though we are filtering on specific pages.
