### ISSUE TITLE
Improving TypoCI usage

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#24387]
## Summary

So I do agree that TypoCI is good for finding typos in docs PRs, but it really gets spammy in other types of situations.

For instance, in the site showcase submissions where there are proper nouns or URLs, it picks those up as misspellings which is incorrect frequently

Is there specific files that it could be filtered down to only run on or ways to enhance it so it doesn't clutter the PRs as much as it does now?

**Comment by LekoArts** [comment]
You can define the `excluded_files` (https://typoci.com/documentation). If it's necessary would be up for discussion.
