### ISSUE TITLE
Deploy to Netlify failing

### ISSUE THREAD

**Issue by seanngpack** [gatsbyjs/gatsby#24389]
# Description

Was wondering if anyone has this issue? Cannot deploy Gatsby blog on netlify as of recently. Gatsby build and develop works perfectly fine on local. 

### Steps to reproduce

Build and deploy on netlify.
Repo: https://github.com/seanngpack/Seans-Portfolio

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

Netlify error seems to be related to Gatsby-cli. Here is a snippet of the build log from Netlify. This is the only error logged and it starts when Netlify calls `gatsby build`
```

Executing user command: gatsby build
11:52:38 AM: /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/init-starter.js:117
11:52:38 AM:   } catch {
11:52:38 AM:           ^
11:52:38 AM: SyntaxError: Unexpected token {
11:52:38 AM:     at createScript (vm.js:80:10)
11:52:38 AM:     at Object.runInThisContext (vm.js:139:10)
11:52:38 AM:     at Module._compile (module.js:617:28)
11:52:38 AM:     at Object.Module._extensions..js (module.js:664:10)
11:52:38 AM:     at Module.load (module.js:566:32)
11:52:38 AM:     at tryModuleLoad (module.js:506:12)
11:52:38 AM:     at Function.Module._load (module.js:498:3)
11:52:38 AM:     at Module.require (module.js:597:17)
11:52:38 AM:     at require (internal/module.js:11:18)
11:52:38 AM:     at Object.<anonymous> (/opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli/lib/create-cli.js:28:20)
11:52:38 AM: Skipping functions preparation step: no functions directory set
```

### Environment

<details>
<summary>click to expand</summary>

System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 3.7.7 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.9 => 2.22.9
    gatsby-image: ^2.2.33 => 2.4.5
    gatsby-plugin-feed: ^2.3.21 => 2.5.3
    gatsby-plugin-google-analytics: ^2.1.28 => 2.3.2
    gatsby-plugin-manifest: ^2.2.29 => 2.4.9
    gatsby-plugin-react-helmet: ^3.1.15 => 3.3.2
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-sharp: ^2.3.2 => 2.6.9
    gatsby-plugin-typography: ^2.3.17 => 2.5.2
    gatsby-remark-copy-linked-files: ^2.1.30 => 2.3.3
    gatsby-remark-embed-video: ^2.0.1 => 2.0.1
    gatsby-remark-images: ^3.1.33 => 3.3.8
    gatsby-remark-prismjs: ^3.3.24 => 3.5.2
    gatsby-remark-responsive-iframe: ^2.2.27 => 2.4.3
    gatsby-remark-smartypants: ^2.1.16 => 2.3.2
    gatsby-source-filesystem: ^2.1.38 => 2.3.8
    gatsby-transformer-remark: ^2.6.37 => 2.8.13
    gatsby-transformer-sharp: ^2.3.5 => 2.5.3
  npmGlobalPackages:
    gatsby-cli: 2.12.34

</details>

**Comment by shreyansh-zazz** [comment]
Did you try building locally first?

**Comment by seanngpack** [comment]
Yes, works 100% locally, and it was working last time I deployed a couple months ago, I think it may have to do with the updated gatsby-cli package

**Comment by Meninas** [comment]
The same problema, local 100% . Netlify PWA broke

**Comment by shreyansh-zazz** [comment]
Any chance you guys are using Netlify Plugins?

**Comment by hronchetti** [comment]
I think this is the same issue I was experiencing (https://github.com/gatsbyjs/gatsby/issues/24343) to solve I think it was updating Gatsby to the latest version in package.json that fixed it (https://github.com/gatsbyjs/gatsby/issues/23214)

**Comment by annas-abuhassan** [comment]
Same exact issue here, I haven't deployed for a few months.

- Updated all dependencies
- I am not using Netlify Plugins
- I tried to re-deploy my last working build however this is failing with the same error message

**Comment by Meninas** [comment]
Netlify deploy

`7:16:44 PM: Build ready to start
7:16:45 PM: build-image version: 30f629161c0736b1a3ecd8b418e5eeffab5c0faf
7:16:45 PM: build-image tag: v3.3.14
7:16:45 PM: buildbot version: 80440c4491d323247b9d55f7bea2ea6bc96ce8d2
7:16:45 PM: Fetching cached dependencies
7:16:46 PM: Starting to download cache of 254.9KB
7:16:46 PM: Finished downloading cache in 104.255038ms
7:16:46 PM: Starting to extract cache
7:16:46 PM: Failed to fetch cache, continuing with build
7:16:46 PM: Starting to prepare the repo for build
7:16:46 PM: No cached dependencies found. Cloning fresh repo
7:16:47 PM: Preparing Git Reference refs/heads/master
7:16:47 PM: Starting build script
7:16:47 PM: Installing dependencies
7:16:48 PM: Attempting node version '12.16.3' from .nvmrc
7:16:49 PM: Downloading and installing node v12.16.3...
7:16:49 PM: Downloading https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.xz...
7:16:49 PM: Computing checksum with sha256sum
7:16:49 PM: Checksums matched!
7:16:52 PM: Now using node v12.16.3 (npm v6.14.4)
7:16:52 PM: Started restoring cached build plugins
7:16:52 PM: Finished restoring cached build plugins
7:16:52 PM: Attempting ruby version 2.6.2, read from environment
7:16:53 PM: Using ruby version 2.6.2
7:16:54 PM: Using PHP version 5.6
7:16:54 PM: 5.2 is already installed.
7:16:54 PM: Using Swift version 5.2
7:16:54 PM: Started restoring cached node modules
7:16:54 PM: Finished restoring cached node modules
7:16:54 PM: Started restoring cached yarn cache
7:16:54 PM: Finished restoring cached yarn cache
7:16:54 PM: Installing yarn at version 1.17.0
7:16:54 PM: Installing Yarn!
7:16:54 PM: > Downloading tarball...
7:16:54 PM: [1/2]: htt
7:16:54 PM: ps://yarnpkg.com/downloads/1.17.0/yarn-v1.17.0.tar.gz --> /tmp/yarn.tar.gz.i8k1BTfLWX
7:16:54 PM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
7:16:54 PM:                                  Dload  Upload   Total   Spent    Left  Speed
7:16:54 PM: 
  0     0
7:16:54 PM:   0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
7:16:54 PM: 
100    80  100    80    0     0    234      0 --:--
7:16:54 PM: :-- --:--:-- --:--:--   234
7:16:54 PM: 
  0     0    0     0    0     0      0      0 -
7:16:54 PM: -:--:-- --:--:-- --:--:--     0
7:16:54 PM: 
100    93  100    93    0     0    14
7:16:54 PM: 4      0 --:--:-- --:--:-- --:--:--  3444
7:16:55 PM: 
100   630  100   630    0     0    683      0 --:-
7:16:55 PM: -:-- --:--:-- --:--:--   683
7:16:55 PM: 
100 1213k  100 1213
7:16:55 PM: k    0     0   898k      0  0:00:01  0:00:01 --:--:--  898k
7:16:55 PM: [
7:16:55 PM: 2
7:16:55 PM: /
7:16:55 PM: 2
7:16:55 PM: ]
7:16:55 PM: :
7:16:55 PM: h
7:16:55 PM: t
7:16:55 PM: t
7:16:55 PM: p
7:16:55 PM: s
7:16:55 PM: :
7:16:55 PM: /
7:16:55 PM: /
7:16:55 PM: y
7:16:55 PM: a
7:16:55 PM: r
7:16:55 PM: n
7:16:55 PM: p
7:16:55 PM: k
7:16:55 PM: g
7:16:55 PM: .
7:16:55 PM: c
7:16:55 PM: o
7:16:55 PM: m
7:16:55 PM: /
7:16:55 PM: d
7:16:55 PM: o
7:16:55 PM: w
7:16:55 PM: n
7:16:55 PM: l
7:16:55 PM: o
7:16:55 PM: a
7:16:55 PM: d
7:16:55 PM: s
7:16:55 PM: /
7:16:55 PM: 1
7:16:55 PM: .
7:16:55 PM: 1
7:16:55 PM: 7
7:16:55 PM: .
7:16:55 PM: 0
7:16:55 PM: /
7:16:55 PM: y
7:16:55 PM: a
7:16:55 PM: r
7:16:55 PM: n
7:16:55 PM: -
7:16:55 PM: v
7:16:55 PM: 1
7:16:55 PM: .
7:16:55 PM: 1
7:16:55 PM: 7
7:16:55 PM: .
7:16:55 PM: 0
7:16:55 PM: .
7:16:55 PM: t
7:16:55 PM: a
7:16:55 PM: r
7:16:55 PM: .
7:16:55 PM: g
7:16:55 PM: z
7:16:55 PM: .
7:16:55 PM: a
7:16:55 PM: s
7:16:55 PM: c
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: >
7:16:55 PM: /
7:16:55 PM: t
7:16:55 PM: m
7:16:55 PM: p
7:16:55 PM: /
7:16:55 PM: y
7:16:55 PM: a
7:16:55 PM: r
7:16:55 PM: n
7:16:55 PM: .
7:16:55 PM: t
7:16:55 PM: a
7:16:55 PM: r
7:16:55 PM: .
7:16:55 PM: g
7:16:55 PM: z
7:16:55 PM: .
7:16:55 PM: i
7:16:55 PM: 8
7:16:55 PM: k
7:16:55 PM: 1
7:16:55 PM: B
7:16:55 PM: T
7:16:55 PM: f
7:16:55 PM: L
7:16:55 PM: W
7:16:55 PM: X
7:16:55 PM: .
7:16:55 PM: a
7:16:55 PM: s
7:16:55 PM: c
7:16:55 PM: 1
7:16:55 PM: 0
7:16:55 PM: 0
7:16:55 PM: 8
7:16:55 PM: 4
7:16:55 PM: 1
7:16:55 PM: 0
7:16:55 PM: 0
7:16:55 PM: 8
7:16:55 PM: 4
7:16:55 PM: 0
7:16:55 PM: 0
7:16:55 PM: 3
7:16:55 PM: 1
7:16:55 PM: 0
7:16:55 PM: 0
7:16:55 PM: 0
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: 3
7:16:55 PM: 1
7:16:55 PM: 0
7:16:55 PM: 0
7:16:55 PM: 
100    97  100    97    0     0
7:16:55 PM:   1692      0 --:--:-- --:--:-- --:--:--  1692
7:16:55 PM: 1
7:16:55 PM: 0
7:16:55 PM: 0
7:16:55 PM: 6
7:16:55 PM: 3
7:16:55 PM: 4
7:16:55 PM: 1
7:16:55 PM: 0
7:16:55 PM: 0
7:16:55 PM: 6
7:16:55 PM: 3
7:16:55 PM: 4
7:16:55 PM: 0
7:16:55 PM: 0
7:16:55 PM: 7
7:16:55 PM: 0
7:16:55 PM: 7
7:16:55 PM: 5
7:16:55 PM: 0
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: :
7:16:55 PM: -
7:16:55 PM: -
7:16:55 PM: 7
7:16:55 PM: 0
7:16:55 PM: 7
7:16:55 PM: 5
7:16:55 PM: 
100   832  100   832    0     0   5915      0 --:--:-- --:--:-- --:--:--  5915
7:16:55 PM: > Verifying integrity...
7:16:55 PM: gpg: Signature made Fri 14 Jun 2019 06:55:58 PM UTC using RSA key ID 69475BAA
7:16:55 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
7:16:55 PM: gpg: WARNING: This key is not certified with a trusted signature!
7:16:55 PM: gpg:          There is no indication that the signature belongs to the owner.
7:16:55 PM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
7:16:55 PM:      Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
7:16:55 PM: > GPG signature looks good
7:16:55 PM: > Extracting to ~/.yarn...
7:16:55 PM: > Adding to $PATH...
7:16:56 PM: > Successfully installed Yarn 1.17.0! Please open another terminal where the `yarn` command will now be available.
7:16:56 PM: Installing NPM modules using Yarn version 1.17.0
7:16:57 PM: yarn install v1.17.0
7:16:57 PM: [1/4] Resolving packages...
7:16:57 PM: [2/4] Fetching packages...
7:17:21 PM: info fsevents@2.1.3: The platform "linux" is incompatible with this module.
7:17:21 PM: info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
7:17:21 PM: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
7:17:21 PM: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
7:17:21 PM: [3/4] Linking dependencies...
7:17:21 PM: warning "gatsby > @pmmmwh/react-refresh-webpack-plugin@0.3.2" has incorrect peer dependency "react-refresh@^0.8.2".
7:17:21 PM: warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
7:17:21 PM: warning "gatsby-plugin-preact > @prefresh/webpack@0.6.0" has unmet peer dependency "webpack@^4.0.0".
7:17:21 PM: warning "gatsby-plugin-preact > @prefresh/webpack > @prefresh/core@0.6.0" has unmet peer dependency "webpack@^4.0.0".
7:17:36 PM: [4/4] Building fresh packages...
7:17:40 PM: Done in 43.81s.
7:17:40 PM: NPM modules installed using Yarn
7:17:41 PM: Started restoring cached go cache
7:17:41 PM: Finished restoring cached go cache
7:17:41 PM: go version go1.12 linux/amd64
7:17:41 PM: go version go1.12 linux/amd64
7:17:41 PM: Installing missing commands
7:17:41 PM: Verify run directory
7:17:41 PM: Executing user command: gatsby build
7:17:43 PM: success open and validate gatsby-configs - 0.039s
7:17:44 PM: success load plugins - 0.904s
7:17:44 PM: success onPreInit - 0.016s
7:17:44 PM: success delete html and css files from previous builds - 0.014s
7:17:44 PM: success initialize cache - 0.008s
7:17:44 PM: success copy gatsby files - 0.035s
7:17:44 PM: success onPreBootstrap - 0.015s
7:17:44 PM: success createSchemaCustomization - 0.004s
7:17:44 PM: Starting to fetch data from Contentful
7:17:44 PM: info Fetching default locale
7:17:44 PM: info default locale is: es
7:17:45 PM: info contentTypes fetched 2
7:17:45 PM: info Updated entries 92
7:17:45 PM: info Deleted entries 0
7:17:45 PM: info Updated assets 227
7:17:45 PM: info Deleted assets 0
7:17:45 PM: Fetch Contentful data: 512.340ms
7:17:45 PM: success source and transform nodes - 0.831s
7:17:46 PM: success building schema - 0.493s
7:17:46 PM: success createPages - 0.013s
7:17:46 PM: success createPagesStatefully - 0.080s
7:17:46 PM: success onPreExtractQueries - 0.001s
7:17:46 PM: success update schema - 0.042s
7:17:46 PM: success extract queries from components - 0.517s
7:17:46 PM: success write out requires - 0.004s
7:17:46 PM: success write out redirect data - 0.001s
7:17:46 PM: success Build manifest and related icons - 0.279s
7:17:46 PM: success onPostBootstrap - 0.281s
7:17:46 PM: ⠀
7:17:46 PM: info bootstrap finished - 5.752s
7:17:46 PM: ⠀
7:17:55 PM: success Building production JavaScript and CSS bundles - 8.816s
7:17:55 PM: success Rewriting compilation hashes - 0.002s
7:17:55 PM: success run queries - 8.960s - 4/4 0.45/s
7:17:57 PM: success Building static HTML for pages - 1.084s - 4/4 3.69/s
7:17:57 PM: warning One of the glob patterns doesn't match any files. Please remove or fix the following: {
7:17:57 PM:   "globDirectory": "public",
7:17:57 PM:   "globPattern": "snipcart.js",
7:17:57 PM:   "globIgnores": [
7:17:57 PM:     "**/workbox-v4.3.1/*.+(js|mjs)*",
7:17:57 PM:     "**/node_modules/**/*",
7:17:57 PM:     "**/sw.js"
7:17:57 PM:   ]
7:17:57 PM: }
7:17:57 PM: info Generated public/sw.js, which will precache 0 files, totaling 0 bytes.
7:17:57 PM: The following pages will be precached:
7:17:57 PM: /offline-plugin-app-shell-fallback/index.html
7:17:57 PM: success onPostBuild - 0.078s
7:17:57 PM: info Done building in 15.935967343 sec
7:17:57 PM: Skipping functions preparation step: no functions directory set
7:17:57 PM: Caching artifacts
7:17:57 PM: Started saving node modules
7:17:57 PM: Finished saving node modules
7:17:57 PM: Started saving build plugins
7:17:57 PM: internal/modules/cjs/loader.js:960
7:17:57 PM:   throw err;
7:17:57 PM:   ^
7:17:57 PM: Error: Cannot find module '../../utils/page-html'
7:17:57 PM: Require stack:
7:17:57 PM: - /opt/build/repo/node_modules/gatsby/dist/utils/worker/render-html.js
7:17:57 PM: - /opt/build/repo/node_modules/gatsby/dist/utils/worker/child.js
7:17:57 PM: - /opt/build/repo/node_modules/jest-worker/build/workers/processChild.js
7:17:57 PM:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
7:17:57 PM:     at Function.Module._load (internal/modules/cjs/loader.js:840:27)
7:17:57 PM:     at Module.require (internal/modules/cjs/loader.js:1019:19)
7:17:57 PM:     at require (internal/modules/cjs/helpers.js:77:18)
7:17:57 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/gatsby/dist/utils/worker/render-html.js:14:17)
7:17:57 PM:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
7:17:57 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
7:17:57 PM:     at Module.load (internal/modules/cjs/loader.js:977:32)
7:17:57 PM:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
7:17:57 PM:     at Module.require (internal/modules/cjs/loader.js:1019:19)
7:17:57 PM:     at require (internal/modules/cjs/helpers.js:77:18)
7:17:57 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/gatsby/dist/utils/worker/child.js:10:19)
7:17:57 PM:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
7:17:57 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
7:17:57 PM:     at Module.load (internal/modules/cjs/loader.js:977:32)
7:17:57 PM:     at Function.Module._load (internal/modules/cjs/loader.js:877:14) {
7:17:57 PM:   code: 'MODULE_NOT_FOUND',
7:17:57 PM:   requireStack: [
7:17:57 PM:     '/opt/build/repo/node_modules/gatsby/dist/utils/worker/render-html.js',
7:17:57 PM:     '/opt/build/repo/node_modules/gatsby/dist/utils/worker/child.js',
7:17:57 PM:     '/opt/build/repo/node_modules/jest-worker/build/workers/processChild.js'
7:17:57 PM:   ]
7:17:57 PM: }
7:17:57 PM: internal/modules/cjs/loader.js:960
7:17:57 PM:   throw err;
7:17:57 PM:   ^
7:17:57 PM: Error: Cannot find module '../../utils/page-html'
7:17:57 PM: Require stack:
7:17:57 PM: - /opt/build/repo/node_modules/gatsby/dist/utils/worker/render-html.js
7:17:57 PM: - /opt/build/repo/node_modules/gatsby/dist/utils/worker/child.js
7:17:57 PM: - /opt/build/repo/node_modules/jest-worker/build/workers/processChild.js
7:17:57 PM:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
7:17:57 PM:     at Function.Module._load (internal/modules/cjs/loader.js:840:27)
7:17:57 PM:     at Module.require (internal/modules/cjs/loader.js:1019:19)
7:17:57 PM:     at require (internal/modules/cjs/helpers.js:77:18)
7:17:57 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/gatsby/dist/utils/worker/render-html.js:14:17)
7:17:57 PM:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
7:17:57 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
7:17:57 PM:     at Module.load (internal/modules/cjs/loader.js:977:32)
7:17:57 PM:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
7:17:57 PM:     at Module.require (internal/modules/cjs/loader.js:1019:19)
7:17:57 PM:     at require (internal/modules/cjs/helpers.js:77:18)
7:17:57 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/gatsby/dist/utils/worker/child.js:10:19)
7:17:57 PM:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
7:17:57 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
7:17:57 PM:     at Module.load (internal/modules/cjs/loader.js:977:32)
7:17:57 PM:     at Function.Module._load (internal/modules/cjs/loader.js:877:14) {
7:17:57 PM:   code: 'MODULE_NOT_FOUND',
7:17:57 PM:   requireStack: [
7:17:57 PM:     '/opt/build/repo/node_modules/gatsby/dist/utils/worker/render-html.js',
7:17:57 PM:     '/opt/build/repo/node_modules/gatsby/dist/utils/worker/child.js',
7:17:57 PM:     '/opt/build/repo/node_modules/jest-worker/build/workers/processChild.js'
7:17:57 PM:   ]
7:17:57 PM: }
7:17:57 PM: Finished saving build plugins
7:17:57 PM: Started saving yarn cache
7:17:57 PM: Finished saving yarn cache
7:17:57 PM: Started saving pip cache
7:18:04 PM: Finished saving pip cache
7:18:04 PM: Started saving emacs cask dependencies
7:18:04 PM: Finished saving emacs cask dependencies
7:18:04 PM: Started saving maven dependencies
7:18:04 PM: Finished saving maven dependencies
7:18:04 PM: Started saving boot dependencies
7:18:04 PM: Finished saving boot dependencies
7:18:04 PM: Started saving go dependencies
7:18:04 PM: Finished saving go dependencies
7:18:07 PM: Build script success
7:18:07 PM: Starting to deploy site from 'public/'
7:18:07 PM: Creating deploy tree 
7:18:07 PM: Creating deploy upload records
7:18:07 PM: 0 new files to upload
7:18:07 PM: 0 new functions to upload
7:18:08 PM: Starting post processing
7:18:08 PM: Post processing done
7:18:08 PM: Site is live
7:19:02 PM: Finished processing build request in 2m17.104559086s`

**Comment by lpatino10** [comment]
Hey @seanngpack, I was running into the exact same issue and I ended up fixing it by setting a higher Node.js version in Netlify. My Netlify build was defaulting to v8.17.0 when Gatsby needs v10.13.0 or higher.

I committed a `.nvmrc` file with the version matching what I was using locally and everything built and deployed fine. Hope this helps!

**Comment by andelh** [comment]
> Hey @seanngpack, I was running into the exact same issue and I ended up fixing it by setting a higher Node.js version in Netlify. My Netlify build was defaulting to v8.17.0 when Gatsby needs v10.13.0 or higher.
> 
> I committed a `.nvmrc` file with the version matching what I was using locally and everything built and deployed fine. There are some other ways to set the Node version documented [here](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript).
> 
> Hope this helps!

Thank you this worked for me!
For me it was as simple as setting an environment variable in Netlify like so:

NODE_VERSION          10

<img width="720" alt="Screen Shot 2020-05-24 at 2 27 26 PM" src="https://user-images.githubusercontent.com/9642862/82761739-b3940b80-9dca-11ea-9ede-4b2119016c25.png">

**Comment by ElijahLynn** [comment]
> I committed a `.nvmrc` file with the version matching what I was using locally and everything built and deployed fine. There are some other ways to set the Node version documented [here](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript).

Thanks, this is working for me now too with that same error:

I opted for a `.node-version` file with my local of `10.5.3` as the filename is a bit more descriptive. But it failed with that and I had to use just `10` and now it installed `10.20.1` and is running fine. I guess I'll update my local to match that.

**Comment by LekoArts** [comment]
Thank you for opening this!

You can remove `gatsby-cli` from your dependencies as it's not needed to build the site. It can potentially create errors for the build (it might work for you locally because you have different versions installed). Also, as other people have mentioned Gatsby requires at least `10.13.0` so make sure that you run it with this version.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by mouten57** [comment]
> Hey @seanngpack, I was running into the exact same issue and I ended up fixing it by setting a higher Node.js version in Netlify. My Netlify build was defaulting to v8.17.0 when Gatsby needs v10.13.0 or higher.
> 
> I committed a `.nvmrc` file with the version matching what I was using locally and everything built and deployed fine. There are some other ways to set the Node version documented [here](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript).
> 
> Hope this helps!

This worked! Thanks @lpatino10
