### ISSUE TITLE
issue with Typescript file in gatsby-starter-default

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#24388]
## Summary

In Gatsby-starter-default, one of the pages is a TSX file: [src/pages/page-2.tsx](https://github.com/gatsbyjs/gatsby/blob/master/starters/default/src/pages/page-2.tsx)

This feels like a dark pattern. Although yes I believe it is good to tell people you can now use Typescript in Gatsby natively, the default starter may not be a good place for this to exist. if you type in 

```
gatsby new
```

and spin up a new Gatsby site, now there is Typescript files in there by default which could cause some confusion, as the file states `// Gatsby supports TypeScript natively!` at the top of it, but doesn't link anywhere or discuss the ramifications of what that means.

Instead, maybe have a possibility of an official gatsby-starter-default-typescript that core maintains. or link to a page in the gatsby docs to see what "Native Typescript in Gatsby" means.

cc: @blainekasten

**Comment by resir014** [comment]
+1. While I welcome TypeScript support in Gatsby, mixing them together with the default starter will cause uneeded confusion.

Another suggestion I could add to that is to have an extra onboarding steps whenever you start running `datsby develop` sort of like [what Next.js does](https://nextjs.org/docs/basic-features/typescript) with their TS support, where they'll automatically add the required `tsconfig.json` file and walk you through what packages to install should you decide to opt into TS (by renaming the `.js` files to `.tsx`).

**Comment by paulrenshaw** [comment]
+1 I just started using gatsby this week and this was the first thing I noticed and pulled a face at. (I've just been on the discord and mentioned this before coming here). At the very least, the content of page-2 should explain why it is a `.tsx`, maybe even rename it to typescript. But I also think a separate typescript version is a good idea.
