### ISSUE TITLE
Gatsby Node Create Pages - actions.createPages is not a function

### ISSUE THREAD

**Issue by lukebyrne73** [gatsbyjs/gatsby#24397]
I'm trying to create dynamic pages inn Gatsby based on a list of products in a faunadb database. I've connected faunadb, but when trying to create the dynamic pages, I'm getting the error "actions.createPages is not a function".

**What should Happen**
The Gatsby site should build

**What Happens**
I get the error mentioned above

**Code**
```
exports.createPages = async function({graphql, actions}){
    const {data} = await graphql(`
    query {
        fauna {
            allCompanies {
                data {
                    slug
                }
            }
        }
    }
    `)

    data.fauna.allCompanies.data.forEach(edge => {
        const slug = edge.slug
        actions.createPages ({
            path: slug,
            component: require.resolve("./src/components/products.js"),
            context:{
                slug
            },
        })
    })
}
```

**Comment by zingbretsen** [comment]
@lukebyrne73 I believe it's `actions.createPage` not `actions.createPages`.

**Comment by herecydev** [comment]
@zingbretsen is correct: `exports.createPages` is the function and `createPage` is an action that you can use to create a single page
