### ISSUE TITLE
Localisation 

### ISSUE THREAD

**Issue by sundarsan** [gatsbyjs/gatsby#2439]
Does Gatsby has any specific procedure to implement multilingual ? 

Or does it has some feature to do it ?

**Comment by KyleAMathews** [comment]
There's no specific helpers atm. There's someone who'll be writing a blog post on how they build a multi-lingual site with Gatsby.

This is something that should be straightforward out of the box so looking forward to more community investment and documentation around patterns.

**Comment by angeloocana** [comment]
Hello @sundarsan 

I've created a plugin to do that: [gatsby-plugin-i18n](https://github.com/angeloocana/gatsby-plugin-i18n)

I'd love to help you using the plugin,
please let me know if you have any problem or need any new feature.

Sites using the plugin:
[angeloocana.com](https://angeloocana.com)
[tic-tac-toe-ai.surge.sh](https://tic-tac-toe-ai.surge.sh)

**Comment by sundarsan** [comment]
Do you have any step by step approach once i add the plugin

**Comment by angeloocana** [comment]
Not yet @sundarsan ;/
I'll be working on it soon.

Did you see the new starter? It's simple.
https://github.com/angeloocana/gatsby-starter-default-i18n

If you have any question, let me know,
I would love to help

**Comment by m-allanson** [comment]
There's a good discussion around i18n at #3853.
