### ISSUE TITLE
events.js:287       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by saurabhprasadsah** [gatsbyjs/gatsby#24405]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by herecydev** [comment]
Hi Saurabh 👋, you need to fill in the info above otherwise it's very difficult to help.

**Comment by LekoArts** [comment]
Hi, please follow our issue template! Please open a new issue when you do so. Thanks!
