### ISSUE TITLE
website has no menu nav item to starters

### ISSUE THREAD

**Issue by Countryen** [gatsbyjs/gatsby#24401]
## Summary
There is no menu item to the starters (gatsbysjs.org/starters) in the header menu (navigation). Is this on purpose, seems missing?

### Motivation
Would be nice to navigate to the starters easier.
Helps in finding the starters.

## Steps to resolve this issue
Go to any page on https://gatsbyjs.org and look at the menu (navigation) at the top.

**Comment by LekoArts** [comment]
Hi, thanks for the issue! But this is currently on purpose like that :)
