### ISSUE TITLE
Issues porting existing website with Gatsby

### ISSUE THREAD

**Issue by AlQaholic007** [gatsbyjs/gatsby#24406]
## Summary

Basically I have a set up where I have my own `index.html` page and I use Gatsby to create blog. Since the `index.html` page is really complicated, rather than try to migrate it's code to react, I would prefer to have a set up where the '/' routes by default to my `index.html` page while the Gatsby `page/index.js` is mapped to '/blog'. How can I accomplish this? Is it possible to have Gatby's index.js map to some other html page like `blog.html` or something like that? 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by herecydev** [comment]
Hey Soham, you can accomplish this by using a pathPrefix. There's some [guidance here](https://www.gatsbyjs.org/docs/path-prefix/) that literally has your example use case.

**Comment by AlQaholic007** [comment]
Hi @herecydev, I tried that approach. Basically Gatsby still compiles the code into an index.html file. Is it possible for me to configure Gatsby in such a way that it compiles to a file other than `index.html` ?

**Comment by AlQaholic007** [comment]
So I could try to give more info if that helps. I've thrown in an `index.html` file in the `static` folder of my project's root. Even while using `pathPrefix` option, Gatsby code compiles into an `index.html` file which gets overriden by the one in my `static` folder

**Comment by herecydev** [comment]
Not that I know of, every page is compiled to an index.html and placed into the correct folder. This is how many file providers will work as well, e.g. /blog => /blog/index.html.

What are you using to host the Gatsby application? It sounds like that needs to be configured to route the request correctly.

**Comment by AlQaholic007** [comment]
I am using netlify @herecydev

**Comment by AlQaholic007** [comment]
My problem arises from the fact that Gatsby doesnt compile the whole code into `/blog/index.html` despite me trying to use `pathPrefix`. To prove that, I tried renaming the `index.html` file in my `static` folder to `main.html` and found the `public` folder to not only have a `main.html` but also the `index.html` compiled by Gatsby

**Comment by herecydev** [comment]
I see what you're trying to do, when you use the pathPrefix gatsby will build all the content into the public folder **without the blog prefix** but will make the links work correctly, e.g. `<Link to="/my-first-blog" />` => `<Link to="/blog/my-first-blog" />`

I think an easy way forward is to:

1. Build the gatsby blog stuff first
2. Move all the files to /blog
3. Add your static index.html to the root
4. Deploy all that to netlify

Hope that makes sense

**Comment by AlQaholic007** [comment]
Ohhhh I see there has been a feature request on it but was held back on the pretext that the maintenance for something this trivial would not be worth it! Thank you so much @herecydev, I think your suggestion is the best way out 😁. I'll close this issue now!
