### ISSUE TITLE
Advice needed: Image links in custom transformer plugin to work with gatsby-remark-images

### ISSUE THREAD

**Issue by niklas-may** [gatsbyjs/gatsby#24416]
## Summary
I am working on a transformer plugin for `gatsby-transformer-remark` that resolves relative image links in markdown files that where sourced by `gatsby-source-dropbox`. In this case, `gatsby-remark-relative-images` doesn't do the job since markdown and image files are stored in gatsbys `.cache` folder in separate folders each.

### My Approach
I wanted to make a plugin that only prepares the links so that `gatsby-remark-images` can do it's magic.

```javaScript
// gatsby-config.js

module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-dropbox`,
      options: {
        accessToken: `<Token>`,
        createFolderNodes: true,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          `gatsby-remark-dropbox-images`, // My plugin to prepare the URLs for the next plugin
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 590,
            },
          },
        ],
      },
    },
  ],
}
```

It was no problem to work my way up from the `markdownAST` node to the corresponding `localFile` node of the image.

```javaScript
// plugins/gatsby-remark-dropbox-images/index.js

const path = require(`path`)
const visit = require("unist-util-visit")

module.exports = ({markdownAST, markdownNode, getNodes, getNode}, pluginOptions) => {

  visit(markdownAST, "image",  node => {
    const { url } = node
    const baseName = path.basename(url) 

    // Find the original node implemented by gatsby-source-dropbox
    const rootNode = getNodes().filter(node => node.internal.type === 'dropboxMarkdown' && node.localFile___NODE === markdownNode.parent)[0]
    
    if(rootNode) {
      const { directory } = rootNode

      // Find the image node that matches the basename and that was stored in the same directory on the dropbox
      const dropboxImageNode = getNodes().filter(node => node.internal.type === 'dropboxImage' && node.directory === directory && node.name === baseName)[0]
      const { localFile___NODE } = dropboxImageNode
    
      const localFile = getNode(localFile___NODE)
      const { absolutePath } = localFile
      // absolutePath: /Users/niklasmay/Code/gatsby-source-dropbox/.cache/caches/gatsby-source-dropbox/56a0f8940f762303afe1c9743b654ef0/01-Folder-Structure.png

      node.url = absolutePath
      // This will not work...
    }

  })
  return markdownAST
}
```

### My Problem
Setting `node.url` to `localFile.absolutePath` will not work for `gatsby-remark-images`. As far as I understand it, it can only work with images stored in the `public` directory. Unfortunately there is no `childImageSharp` field with a path at this point in the lifecycle.

### My Question
What would be a good approach to solve this?
a) Use `gatsby-plugin-sharp`,  invoke `fixed()` to create images in the public directory? 
b) Use some node function to copy the file into the public folder? If so, are there any guidelines regarding folder names and such?
c) ...

I Would be greatly happy for thoughts and / or guidance.

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Can you give some more details about the usage? I'm not sure how you want to use the source plugin to get images inside your markdown files. Because I want to understand why https://www.gatsbyjs.org/packages/gatsby-remark-images-anywhere/ is not an option. Have you also looked at https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images-contentful ?

**Comment by niklas-may** [comment]
Tanks for your answer!

I basically want to get image and markdown files stored on a dropbox account, and also resolve image links within the markdown. 

Getting all the data with `gatsby-source-dropbox` works fine, but the image links within the markdown (that do work in the filesystem) don't work in graphql.

**Example**

The dropbox folder (stored outside of the gatsby repo):
```markdown
. DropboxFolder
+-- text.md
+-- image.jpg
```

The `text.md` contains an image link:
```text
# Markdown body

Here is an image in the markdown body:
![Alt description](./image.jpg)
```

After sourcing with `gatsby-source-filesystem`, I can query the individual files with no problem. And `gatsby-transformer-remark` does pickup the image tag:

```javaScript
{
  type": "element",
  "tagName": "img",
  "properties": {
    "src": "./image.jpg",
    "alt": "Alt description"
  },
  "children": []
}
```

But `gatsby-remark-relative-image` or `gatsby-remark-images-anywhere` are not able to fix the path. As far as I understand it, both plugins are made to work with files that were sourced with `gatsby-source-filesystem`. I guess this plugin does create some kind of reference to the original folder the file was stored in. So that the remark plugin can resolve the path.

Files sourced with `gatsby-source-dropbox` are just stored in the cache without a proper reference to the original folder they were stored in. 

As I mentioned in my previous post in the `gatsby-remark-dropbox-images/index.js` example, I am able to identify the correct image nodes, but i don't know how to pass this information to `gatsby-remark-images`. Just adding the absolutePath does not do the trick...

Is there more information or documentation for `gatsby-remark-images` than [this](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images)? Otherwise I guess i need to dig deeper into the code.

**Comment by niklas-may** [comment]
I just went deeper into the `gatsby-remark-images`. Unfortunately I found out that that it will not be compatible with the way that `gatsby-source-dropbox` works.

```javaScript
//gatsby-remark-images/src/index.js

const generateImagesAndUpdateNode = async function (
  node,
  resolve,
  inLink,
  overWrites = {}
) {
  
  // This is still ok, markdown nodes sourced from dropbox do also have parent
  const parentNode = getNode(markdownNode.parent)

  let imagePath
  // Here is where the problem starts.
  // Since files sourced form dropbox, each individual file has a seperate folder in the .cache
  // Checking for the path of the markdown file, will not lead to to folder where the image is stored
  if (parentNode && parentNode.dir) {
    imagePath = slash(path.join(parentNode.dir, getImageInfo(node.url).url))
  } else {
    return null
  }

  const imageNode = _.find(files, file => {
    if (file && file.absolutePath) {
      return file.absolutePath === imagePath
    }
    return null
  })

  if (!imageNode || !imageNode.absolutePath) {
    return resolve()
  }

  let fluidResult = await fluid({
    file: imageNode,
    args: options,
    reporter,
    cache,
  })

  if (!fluidResult) {
    return resolve()
  }

  // ...
}
```

**I guess there are 3 choices now:**

A. Create a new transformer plugin that does exactly what `gatsby-remark-images` does, but just for markdown sourced from dropbox.
B. Change the way how `gatsby-source-dropbox` caches files to make the plugin compatible
C. Kill the whole idea

Option A feels not ideal because it is just a lot of duplicate code. For option B, i am not sure if this is even possible. Option C would just be sad.

Anyways, if you have any ideas, i am happy for input! If this is all out of scope, feel free to close this issue.

**Comment by niklas-may** [comment]
Hi, I was finally able to make this work and released this as a plugin.
[gatsby-remark-dropbox-images](https://www.npmjs.com/package/gatsby-remark-dropbox-images)

Thanks for your help and feel free to close this issue.
