### ISSUE TITLE
Color code issue on MSYS for Win

### ISSUE THREAD

**Issue by MatteoGauthier** [gatsbyjs/gatsby#24420]
## Description

Buggy color character

### Steps to reproduce

Use msys
execute `gatsby new`

### Expected result

Colors

### Actual result

Raw chars
![image](https://user-images.githubusercontent.com/32040951/82764368-73ef1300-9e0e-11ea-935c-7ab0ef768e02.png)

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - ~\.yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.18 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.21.37 => 2.21.37 
  npmGlobalPackages:
    gatsby-cli: 2.12.34

**Comment by LekoArts** [comment]
We'd appreciate any more input from other people to be able to pin point the issue.

**Comment by GYETROH** [comment]
Does someone have the answer to this? 
Same problem here, I don't know hot to fix it. 😢
