### ISSUE TITLE
How do we access siteMetadata from createSchemaCustomization in gatsby-node.js

### ISSUE THREAD

**Issue by JohJonker** [gatsbyjs/gatsby#24427]
## Summary
I'm creating schema customisations using `createSchemaCustomization` in `gatsby-node.js` and need to access an array of content types that I've stored in `siteMetadata` in `gatsby-config.js`. What is the best way to query/access that in this context?

## Relevant information
In Gatsby Themes, `createSchemaCustomization` receives a `siteOptions` param, containing the config; that would've been ideal. In normal sites, however, `createSchemaCustomization` only receives `{ actions }`.

### Environment (if relevant)
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 72.0.2
    Safari: 13.1
  npmPackages:
    gatsby: ^2.21.39 => 2.21.39 
    gatsby-background-image: ^1.1.1 => 1.1.1 
    gatsby-image: ^2.4.4 => 2.4.4 
    gatsby-plugin-emotion: ^4.3.1 => 4.3.1 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-transformer-csv: ^2.3.1 => 2.3.1 
  npmGlobalPackages:
    gatsby-cli: 2.12.15

### File contents (if changed)

`gatsby-node.js`:
This was what I thought I could do conceptually, but I'm guessing it's not safe to query graphql in this point of the lifecycle, when we're still customising the schema?
```js
exports.createSchemaCustomization = async ({ actions }) => {
  const { createTypes } = actions;

  const query = `
    {
        site {
            siteMetadata {
                contentTypes {
                    frontmatterFields {
                        name
                        type
                    }
                }
            }
        }
    }
    `;
  const result = await graphql(query);
  const { contentTypes } = result.site.siteMetadata;

  const contentTypeDefinitions = {};
  for (let i = 0; i < contentTypes.length; i += 1) {
    for (let j = 0; j < contentTypes[i].frontmatterFields.length; j += 1) {
      if (
        contentTypeDefinitions[contentTypes[i].frontmatterFields[j].name] ===
        undefined
      ) {
        // Checks for duplicate field declarations; only the first will be declared
        contentTypeDefinitions[contentTypes[i].frontmatterFields[j].name] =
          contentTypes[i].frontmatterFields[j].type;
      }
    }
  }
  const finalDefinitions = `
    type MarkdownRemark implements Node {
      fields: Fields
      frontmatter: Frontmatter    
    }
    type Fields {
      slug: String
      collection: String
    }
    type Frontmatter {
        ${Object.keys(contentTypeDefinitions)
          .map((key) => `${key}: ${contentTypeDefinitions[key]}`)
          .join('\n')}
    }
  `;
  createTypes(finalDefinitions);
};
```

**Comment by JohJonker** [comment]
FYI: You may have noted my related question #24428. That describes how, ideally, I'd like to customise schema in my Gatsby Theme. Because that doesn't currently seem possible, I'm trying to customise the schema in the site itself, as described in this issue.

**Comment by LekoArts** [comment]
Thank you for opening this!

You can't access that data (in `createSchemaCustomization` step) and doing any hacky workarounds wouldn't be safe at all. You should pass those things in via the `pluginOptions` and for that you'll need to create a (local) theme.

However, you can access Gatsby's data layer in a safe way in the `createResolvers` step. So you could run a `runQuery` for your frontmatter field and get the data this way: https://www.gatsbyjs.org/docs/schema-customization/#accessing-gatsbys-data-store-from-field-resolvers

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by JohJonker** [comment]
Thanks for the response @LekoArts!

The `createResolvers` pointer is useful, thanks! I see I can override the schema type and default values there, as well as specify foreign key relations, albeit with a bit more effort than in `createSchemaCustomization`.

Can I override schema with `createResolvers` from my theme?

One further concern I have: My understanding is that `createResolvers` runs after all the schema is generated. If I want to override the schema types there, doesn't that mean all the initial time spent inferring the types is wasted? Would I then need to explicitly opt out of type inference with `createSchemaCustomization` and rather explicitly define it in `createResolvers`?

**Comment by vladar** [comment]
> One further concern I have: My understanding is that createResolvers runs after all the schema is generated. If I want to override the schema types there, doesn't that mean all the initial time spent inferring the types is wasted? Would I then need to explicitly opt-out of type inference with createSchemaCustomization and rather explicitly define it in createResolvers?

Inference runs regardless of the choice of redux action (`createTypes` or `createResolvers`) unless you opt-out of it explicitly. So if you are going to generate full types, then you should opt-out of inference.

But keep in mind that `createResolvers` can't create new types, only modify existing types.

**Comment by JohJonker** [comment]
Thanks @vladar! Good to know.
