### ISSUE TITLE
Gatsby Cloud: Unknown argument "publicName" on field "createSite" of type "Mutation"

### ISSUE THREAD

**Issue by JohJonker** [gatsbyjs/gatsby#24431]
## Description

Not sure if this is the right place to post about Gatsby Cloud. When trying to create a new site in Gatsby Cloud from an existing GitHub repo, I get this error message: `Unknown argument "publicName" on field "createSite" of type "Mutation".`

<img width="641" alt="Screenshot 2020-05-25 at 11 03 01" src="https://user-images.githubusercontent.com/4933686/82797896-0972bd00-9e78-11ea-85ff-373da2b914eb.png">

### Steps to reproduce

1. https://www.gatsbyjs.com/dashboard/sites
2. Click "Create new site"
3. Select "I already have a Gatsby site", click Next
4. Select the GitHub repo, click Next
5. Error message

### Expected result

Gatsby Cloud should create the new site.

### Actual result

Error message described above.

**Comment by LekoArts** [comment]
Please use the "Help" button in the navigation. Thanks!
