### ISSUE TITLE
Comments on Gatsby feature comparison to Wordpress, Jekyll & Squarespace

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#2444]
With https://github.com/gatsbyjs/gatsby/pull/2443 we're adding a features comparison page to help potential Gatsby adopters compare Gatsby to alternative frameworks and tools such as Wordpress, Jekyll & Squarespace. 

Because framework capabilities are always changing we're opening this issue as a general banner  to ensure the information contained remains complete, accurate and up to date. Please comment with suggestions if you feel it is not,  _especially_ if you are a member of the Wordpress, Jekyll or Squarespace communities.

**Comment by bep** [comment]
The "traditional static site generators such as Jekyll" and "comparison with a representative from each category" is misleading. 

GatsbyJS should be proud of its features and uniqueness, but to put all the others (like Hugo, where I come from) into one basket doesn't make much sense. 

Compare it to Jekyll, that's fine and dandy -- but please remove the "STATIC SITE GENS" category.

**Comment by KyleAMathews** [comment]
How would you categorize things?

**Comment by bep** [comment]
>How would you categorize things?

I wouldn't. There are 100s of static generators. There are plenty of diversity. GatsbyJS is excellent for certain use cases, Hugo is excellent for certain use cases ... Etc. You cannot truly put this into a matrix table with "GatsbyJS vs the rest of the static generators".

I would put the focus on GatsbyJS' features.

 But this isn't my project. Up to you, but right now it doesn't look right.

**Comment by zionis137** [comment]
"CSS Extensions (eg Sass)" is fully supported in Jekyll
https://jekyllrb.com/docs/assets/#sassscss

**Comment by lvpreet** [comment]
how we can study the architecture of this project ?
Thankyou

**Comment by samfrost** [comment]
There's a minor typo in the expanded detail for 'No extraneous code fetching'. Last sentence 'fine' is spelt with two I's (fiine).

**Comment by mittalyashu** [comment]
Can you add Nuxt as a competitor?

**Comment by chrisarusso** [comment]
The comparison paragraph `prefetched linked pages` reads:

> You can put this together in considerably more tricky for Wordpress & requires maintaining dual PHP and JS templates.

That sentence needs some work - it doesn't currently make sense. Perhaps you meant

> This in considerably more tricky for Wordpress & requires maintaining dual PHP and JS templates.

**Comment by SteveALee** [comment]
At the top of the page you list 3 types of sites. I'm keen to know how Gatsby compares with an SPA, perhaps made with create-react-app. Obviously Gatsby makes more decisions, but would some types of SPA be better made with Gatsby?

I am really assuming the line between an `app` and a `site` is very blurred :)

**Comment by spookylukey** [comment]
For me a critical feature to have on this list is what I would call "HTTP basics" (sometimes called "server side rendering") which is a bunch of things:

* a URL for some specific HTML resource should return the actual HTML content for that resource (not some Javascript that, when executed, will fetch and build that HTML).
* URLs should return appropriate HTTP response codes at the server level (e.g. 200/404 etc).
* the site content is accessible, at least to a basic level, with Javascript disabled (a fairly key HTTP principle IMO) 

It looks like Gatsby does this properly, as do most of the others (in theory), it is some JS frameworks that are offenders.

I know this is similar to the "static content" and "No extraneous code fetching Info" items, but it is also distinct, and none of those bullet points answered this question for me.

**Comment by spookylukey** [comment]
For me a critical feature to have on this list is what I would call "HTTP basics" (sometimes called "server side rendering") which is a bunch of things:

1. a URL for some specific HTML resource should return the actual HTML content for that resource (not some Javascript that, when executed, will fetch and build that HTML).
2. URLs should return appropriate HTTP response codes at the server level (e.g. 200/404 etc).
3. the site content is accessible, at least to a basic level, with Javascript disabled (a fairly key HTTP principle IMO) 

Looking at some of the sites in the gallery, some seem to do all these fine (e.g. https://reactjs.org/ ) , others don't e.g.:

    curl https://impossiblefoods.com/food/ | html2rst.py

I get nothing - there is no HTML content in the actual HTML document returned.

I know this is similar to the "static content" and "No extraneous code fetching Info" items, but it is also distinct, and none of those bullet points answered this question for me.

**Comment by rbmedia** [comment]
Wordpress has all features out of the box in your comparison chart, is this right?
I use gatsby because I am  unhappy with the output of CMS like Drupal and wordpress.

**Comment by hyperparsa** [comment]
Pretty sure the wordpress features list is wrong. It shoes all the features as "Out of the box".

**Comment by pieh** [comment]
Ah, sorry - will fix soon https://github.com/gatsbyjs/gatsby/pull/9883

**Comment by primerano** [comment]
under "Asset pipelines" I think Jekyll should be listed as plugins available.  I've been using this one for a few years now -> https://github.com/envygeeks/jekyll-assets
