### ISSUE TITLE
Create reference guides collection for Remark

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#24450]
## Summary

Currently Gatsby has some docs on using `gatsby-transformer-remark` to render markdown pages.

- [Adding Markdown Pages](https://www.gatsbyjs.org/docs/adding-markdown-pages/)
- [Adding a List of Markdown Blog Posts](https://www.gatsbyjs.org/docs/adding-a-list-of-markdown-blog-posts/)
- [Creating Tags Pages for Blog Posts](https://www.gatsbyjs.org/docs/adding-tags-and-categories-to-blog-posts/#add-tags-to-your-markdown-files)

These should all be centralized in a collection similar to how the [MDX Collection](https://www.gatsbyjs.org/docs/mdx/) exists.

As well on top of these pages, I believe there should be a page on what Gatsby Remark plugins are, how to use them, and maybe link over to the [Creating a Remark Transformer Plugin](https://www.gatsbyjs.org/tutorial/remark-plugin-tutorial/)

### Motivation

The docs have a reference guide collection on MDX but the content about Remark is more dispersed across the docs.

## Steps to resolve this issue

This is likely a discussion that has to be made with the core team on what pages should exist in a collection like this and then start moving the various files either in the sidebar / adding pages that should exist but don't yet.

**Comment by marcysutton** [comment]
Given Gatsby's focus on MDX (we have a team dedicated to it now), we don't really want to put the same emphasis on Remark. I'm going to close this as we don't want to move forward with it, but we really thank you for opening the issue!
