### ISSUE TITLE
Gatsby-Image with svg file styling question

### ISSUE THREAD

**Issue by nickrazes** [gatsbyjs/gatsby#24464]
Hello everyone:

How should I apply css styles to an svg image using the gatsby-image setup from the following issue: #12499 ?

I can't apply the styles directly to the <img> tag within ImgWithSVGSupport component because then it gets applied to every svg file instead of just the one I want.

Trying to use imgStyle and style as an inline style does nothing because the svg image is getting its styles from the <img> tag.

I tried passing in a class to the <MySVG /> component call within the page that is making use of the ImgWithSVGSupport component as well but it does nothing.

How should I handle this?

**Comment by LekoArts** [comment]
Thank you for opening this!

You can add a `className` to the `<img />` tag and then style your wrapper (via the `...rest` props. But please be aware that you can't modify svg files inside a `<img />` tag.
As this question isn't specific to Gatsby I'll close this. I'd recommend reaching out to one of the React communities if you have general React questions!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
