### ISSUE TITLE
Gatsby-cli@2.12.35 breaks the Gatsby

### ISSUE THREAD

**Issue by jayjayzheng** [gatsbyjs/gatsby#24461]
## Description

After installed latest gatsby-cli@2.12.35, then gatsby not working any more. here is the error - 

```
/usr/local/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: No valid exports main found for '/usr/local/lib/node_modules/gatsby-cli/node_modules/@urql/core'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/node_modules/urql/dist/urql.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}
```

### Steps to reproduce

npm i -g gatsby-cli

gatsby develop

### Actual result

gatsby command not working 

### Environment

gatsby-cli@2.12.35
npm: 6.14.5
node: 13.6

**Comment by jayjayzheng** [comment]
I had to rollback to 2.12.29 to have it work. here is the gatsby info - 

 System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.113
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.1 => 2.22.1
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.4.4 => 2.4.4
    gatsby-plugin-google-analytics: ^2.3.1 => 2.3.1
    gatsby-plugin-guess-js: ^1.3.2 => 1.3.2
    gatsby-plugin-intl: ^0.3.3 => 0.3.3
    gatsby-plugin-layout: ^1.3.1 => 1.3.1
    gatsby-plugin-manifest: ^2.4.6 => 2.4.6
    gatsby-plugin-material-ui: ^2.1.8 => 2.1.8
    gatsby-plugin-netlify: ^2.3.3 => 2.3.3
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sass: ^2.3.1 => 2.3.1
    gatsby-plugin-sharp: ^2.6.6 => 2.6.6
    gatsby-plugin-sitemap: ^2.4.2 => 2.4.2
    gatsby-source-filesystem: ^2.3.5 => 2.3.5
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2
  npmGlobalPackages:
    gatsby-cli: 2.12.29

**Comment by t2ca** [comment]
Works fine here.
`Gatsby CLI version: 2.12.35`

**Comment by LekoArts** [comment]
As per other issues https://github.com/gatsbyjs/gatsby/issues/22558, https://github.com/gatsbyjs/gatsby/issues/23214, https://github.com/gatsbyjs/gatsby/issues/23763, https://github.com/gatsbyjs/gatsby/issues/23378 - please update your packages to the latest versions, maybe delete the package-lock/yarn.lock files and node_modules folder beforehand.

The CLI is working fine for me on the mentioned version.

**Comment by ergunpp** [comment]
How to best update gatsby and gatsby cli for a site?

**Comment by TomPeak** [comment]
I did it by the book … got same error!

Everything uptodate!
latest nvm npm gatsby-cli

**Comment by zlydenko** [comment]
same error here
