### ISSUE TITLE
README.dev.md incorrectly rendered on gatsby plugin page instead of README.md

### ISSUE THREAD

**Issue by baerrach** [gatsbyjs/gatsby#24468]
## Description

When I browse to this gatsby community plugin https://www.gatsbyjs.org/packages/gatsby-remark-plantuml/?=gatsby-remark-plantuml instead of rendering the project's **README.md** it is instead rendering **README.dev.md**

**Comment by LekoArts** [comment]
Thank you for opening this!

We're using https://www.npmjs.com/package/gatsby-source-npm-package-search to pull up the README and it probably uses the first README file it can find. I don't think that we need to change something on our end as I would recommend you to use `CONTRIBUTING.md` instead. That's the convention we and a lot of other people use!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
