### ISSUE TITLE
gatsby-plugin-react-helmet doesn't set or pass through htmlAttributes or bodyAttributes

### ISSUE THREAD

**Issue by ptolemybarnes** [gatsbyjs/gatsby#2447]
The [current implementation](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-react-helmet/src/gatsby-ssr.js) of `gatsby-plugin-react-helmet` doesn't set or pass through these properties.

It could use `setBodyProps` to pass these through.

**Comment by KyleAMathews** [comment]
Added PR #2448 to fix this 👍  Some other people have been mentioning the same shortcoming.
