### ISSUE TITLE
gatsby-plugin-dark-mode README in plugins list appears outdated/not to match the one in the repo

### ISSUE THREAD

**Issue by pranjaljately** [gatsbyjs/gatsby#24499]
As per my conversation with @laurieontech

> If the README files don't appear to be the same I'd recommend filing an issue in this repo and showing screenshots or links of the difference.
_Originally posted by @laurieontech in https://github.com/gatsbyjs/gatsby/pull/24350#issuecomment-634151728_

**The new docs help fix an issue that I was facing when using the docs from GatsbyJS for the plugin.**

[**Example on GatsbyJS:**](https://www.gatsbyjs.org/packages/gatsby-plugin-dark-mode/)

![image](https://user-images.githubusercontent.com/30666375/82932361-3ad6b000-9f80-11ea-80ec-fa3f7a3aa33a.png)

[**Updated example in plugin repo:**](https://github.com/insin/gatsby-plugin-dark-mode#readme)

![image](https://user-images.githubusercontent.com/30666375/82932537-7e311e80-9f80-11ea-9cd2-1b0c0093c915.png)

**Comment by laurieontech** [comment]
From what I can tell the latest README isn't being pulled into the plugin showcase for some reason. So wanted the user to open a bug.

**Comment by LekoArts** [comment]
I updated the title/description on this issue: https://github.com/gatsbyjs/gatsby/issues/24137

Let's consolidate it there, it's basically the same issue :)
