### ISSUE TITLE
Resolve Page URLs With ".html" Suffix

### ISSUE THREAD

**Issue by DannyHinshaw** [gatsbyjs/gatsby#24494]
## Summary
I'm in a bit of an unfortunate position where the design choices of someone years ago are now affecting my rebuild of a website. Basically, way back when the site was originally created the designer pushed to have all URLs be fully explicit with the `.html` extensions (eg `website.com/index.html`). I am currently in the process of rebuilding the site with Gatsby and it has come to my attention that we need to continue resolving those old URLs as they are still scattered around the internet in the form of links. But the owner would like to move away from those URLs going forward, so basically I just need to support resolving them for backwards compat.

I have been working with the `onCreatePage` function and can get it to resolve the `.html` links like so:

```javascript
exports.onCreatePage = async ({ page, actions }) => {
	const { createPage } = actions;
	console.log(actions);

	// Create resolvers for all pages with .html in URLs
	if (!page.path.endsWith(".html")) {
		const isIndex = page.path === "/";
		page.matchPath = isIndex
			? page.path + "/index.html"
			: page.path.replace(/\/$/, ".html");

		createPage(page);
	}
};
```

But unfortunately that _only_ resolves the `.html` URLs, not plain urls with no `.html` suffix.

Is there a way I can achieve this? Should I be looking at a different API than `onCreatePage`?

**Comment by blainekasten** [comment]
Hey there!

I think what you want to use is [`createRedirect`](https://www.gatsbyjs.org/docs/actions/#createRedirect). My guess is that your code should look something like this:

```js
exports.onCreatePage = ({ page, actions }) => {
  actions.createRedirect({
    from: page.path + '.html',
    to: page.path
  });
};
```

There are other options to help you configure your redirects, so check out the docs.

I'm going to close this issue as it seems like this should work. But feel free to respond here for further support or open a new issue!

**Comment by DannyHinshaw** [comment]
@blainekasten thanks! I had actually just found that and was in the middle of attempting:

```javascript
exports.onCreatePage = async ({ page, actions }) => {
	const { createRedirect } = actions;

	// Create resolvers for all pages with .html in URLs
	if (!page.path.endsWith(".html")) {
		const isIndex = page.path === "/";
		const legacyUrl = isIndex
			? page.path + "/index.html"
			: page.path.replace(/\/$/, ".html");

		console.log("legacyUrl::", legacyUrl);
		createRedirect({ fromPath: legacyUrl, toPath: page.path, isPermanent: true });
	}
};
```

The console is outputting the correct old URLs but it is not redirecting... not sure what I'm doing wrong. Guess I look more at the docs and hope there's a solution in there
