### ISSUE TITLE
is there a way to build components out of .md files?

### ISSUE THREAD

**Issue by kevohagan** [gatsbyjs/gatsby#245]
Is that possible? I don't really grasp how i could do that. Basically instead of building a whole static page (from a markdown file for e.g.), i could build just a component and then include it in a parent template. I don't know if what i'm saying makes sense.. hehe

Thanks!

**Comment by KyleAMathews** [comment]
Yup! Just import a markdown file actually :-) This is actually Gatsby is doing under the hood.

In a JS component you can do something like

```js
// File should be underscored so Gatsby doesn't convert it into a page.
import Text from './_my_special_markdown_file.md'
```

There's also several React components on NPM that let you write Markdown directly in your React component e.g. https://www.npmjs.com/package/react-markdown-it which also uses markdown-it like Gatsby.

Did that answer your question?

**Comment by rowellx68** [comment]
@KyleAMathews I have been looking for this! However, I'm having to do this:

```jsx
<Container className="default-container" style={styles.defaultContainer} >
    <Grid columns={12}>
        <div dangerouslySetInnerHTML={{__html: Schema.body}}></div>
    </Grid>
</Container>
```

Is there a better way of doing it?

**Comment by KyleAMathews** [comment]
@rowellx68 what are you trying to do here? What is `Schema`?

**Comment by rowellx68** [comment]
It's a markdown file that I've imported as suggested above

**Comment by kylegach** [comment]
You have to use dangerouslySetInnerHTML when you need the contents to be converted into HTML (as opposed to simply injected as a string).

It's easier to just see the difference than to explain it. So try this and note how the output is different from the snippet above:
```
<Container className="default-container" style={styles.defaultContainer} >
    <Grid columns={12}>
        { Schema.body }
    </Grid>
</Container>
```

**Comment by rowellx68** [comment]
@kylegach The goal was to imbed a `.md` file inside a React component and treat it as HTML. Looking at `/wrappers/md.js`, it uses `dangerouslySetInnerHTML `. 

Apologies if it was a bit unclear

**Comment by kylegach** [comment]
Yeah, I think I misunderstood, sorry. I conflated your comment with OP’s issue and didn't realize you already understood dangerouslySetInnerHTML and were explicitly looking for an alternative.

It looks like the package Kyle linked to would meet your goal.

**Comment by KyleAMathews** [comment]
Looks like we're good here now :-) Reopen if you have further questions.
