### ISSUE TITLE
Docs: Add title to <abbr> in docs

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#24505]
## Summary

when a abbreviation is marked with `<abbr>` then it is underlined and i can hoover over it and it becomes a `?` but no more info is there :(

### Motivation

the underline and the change of the icon feels useless if there is no more information, because i expect that is clickable when i see a `?`

## Steps to resolve this issue

should we add a `title` parameter to the `<abbr>` tag?

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by AishaBlake** [comment]
Given that every instance of the `<abbr>` tag I see is accompanied by an explanation of the abbreviation, I think it's probably better to remove them rather than add repetitive titles.

**Comment by muescha** [comment]
you mean removing the `<abbr>` tags around?

**Comment by AishaBlake** [comment]
> you mean removing the `<abbr>` tags around?

Yes! Since their purpose is already being served by the surrounding text, I don't think they're necessary.

**Comment by muescha** [comment]
ah ok - has the removement of all `<abbr>` any impact for screenreaders? maybe they read it better with this marker?

**Comment by marcysutton** [comment]
Screen reader users will get the surrounding context, and adding `<abbr>` with titles to inline copy will indeed be redundant. I've opened a PR to remove them since I agree they aren't necessary. https://github.com/gatsbyjs/gatsby/pull/24964
