### ISSUE TITLE
discussion: move gatsby recipes out of glossary for IaC

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#24509]
## Summary

in PR #23431 `Glossary, encyclopedia: Add Infrastructure As Code article.` there is and Glossary about [IaC](https://www.gatsbyjs.org/docs/glossary/infrastructure-as-code/) and there is a half of the text in style of a guide about Gatsby Recipes.

i suggest:
- to extract this Recipes part into a Recipes Guide 
- only an overview why recipes are IaC
- add an glossary about Gatsby Recipes

### Motivation

i expect a glossary just an information about a technology and not a guide

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by marcysutton** [comment]
Closed with #23431.

**Comment by muescha** [comment]
mhhh @marcysutton 

mhh this issue is NOT closed with #23431 

because i am referencing exactly to the #23431, that in this PR is too much guide

🤔
