### ISSUE TITLE
pathPrefix in gatsby-config is not prepending the prefix to assets.

### ISSUE THREAD

**Issue by RebootGG** [gatsbyjs/gatsby#24513]
Hello everyone. I'm trying to deploy my gatsby project on a sub-directory like: https://www.example.com/blog 

Following the [docs](https://www.gatsbyjs.org/docs/path-prefix/), I added a `/blog` path prefix into my `gatsby-config.js` file. Then, I build the project using the command `gatsby build --prefix-paths`

When i check my generated `index.html` in my `public` folder, i'm seeing that the prefix is not prepended to the statics assets' path.  

I've started from a fresh project and yet I am still having the issue. Maybe I've been looking at it for too long and missing something stupid. I've also tried double quotes, simple quotes, removing the leading slash, but nothing seems to work. Any help would be appreciated.

### Steps to reproduce
1. Start a new project : `gatsby new gatsby-site`
2. Add a pathPrefix into `gatsby-config.js` : 
````module.exports = {
  siteMetadata: {
    pathPrefix: `/blog`,
  },
````
3. Build the project using the flag : `gatsby build --prefix-paths`
4. Check the presence of the prefix you chose in the assets linked in the `index.html` file

### Expected result
Linked static assets prepended with the path prefix should be like :
`src="/blog/static/6d91c86c0fde632ba4cd01062fd9ccfa/630fb/gatsby-astronaut.png"`

### Actual result
`src="/static/6d91c86c0fde632ba4cd01062fd9ccfa/630fb/gatsby-astronaut.png"
`
### Environment

  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  Binaries:
    Node: 12.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.21.37 => 2.21.37 
    gatsby-image: ^2.4.4 => 2.4.4 
    gatsby-plugin-manifest: ^2.4.5 => 2.4.5 
    gatsby-plugin-offline: ^3.2.3 => 3.2.3 
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1 
    gatsby-plugin-sharp: ^2.6.4 => 2.6.4 
    gatsby-source-filesystem: ^2.3.4 => 2.3.4 
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2 
  npmGlobalPackages:
    gatsby-cli: 2.11.8

### gatsby-config.js

```
module.exports = {
  siteMetadata: {
    pathPrefix: `/blog`,
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `.`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}

```

**Comment by thomascorthouts** [comment]
Hi @RebootGG 

Could you try moving your `pathPrefix: '/blog',` from the `siteMetadata` to 1 level up and see if that works, the docs say it needs to be in the root level of the object put in `module.exports` for it to work

**Comment by thomascorthouts** [comment]
It would be 
```
module.exports = {
  pathPrefix: `/blog`,
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `.`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
```
(I moved the path prefix from L3 to L2)

**Comment by LekoArts** [comment]
Thank you for opening this!

As Thomas said correctly you placed the key in the wrong location. Fixing this should make it work :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by RebootGG** [comment]
@thomascorthouts Thank you for you answer. 

The point you are referrring to was unfortunately just a copy/paste mistake from my side when I shared my code here. 

I used a different prefix in my code, and I replaced it at the wrong location when pasting it on Github,(I kept 'blog' prefix for clarity reasons.. that is a fail) sorry about that. 

I found that the problem was actually coming from the `siteUrl` in my siteMetadata object : I omitted the prefix there, so my URL was : 

`siteURL : https://www.mydomain.com `

when it should have been : 

`siteURL : https://www.mydomain.com/blog`

I thought that gatsby would automatically add the prefix to the base URL, but you have to write down too, which seems kinda logical for me now.

It is working fine now. Thanks again

**Comment by airtonix** [comment]
@LekoArts This needs to be documented here: 
- https://www.gatsbyjs.com/docs/path-prefix/#add-to-gatsby-configjs
