### ISSUE TITLE
discussion: add a part for glossary to contribution / style guide 

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#24510]
## Summary

there are some pages about [Gatsby Styleguide: What kinds of docs can I write?](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#what-kinds-of-docs-can-i-write) and [Docs Contributions - Docs Writing Process: Tutorials vs. recipes vs. guides](https://www.gatsbyjs.org/contributing/docs-writing-process/#tutorials-vs-recipes-vs-guides).

But i miss there how a glossary should include, how should the wording include etc.

### Motivation

i miss a help about how glossary should be styled/written etc.

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by meganesu** [comment]
Hi there @muescha! Thanks for bringing this up. The Documentation team is starting to think about adding a resource like this, but we'll have to prioritize it alongside our existing work. It might be some time before you see this addition.

Thanks for your contribution! 💜

**Comment by muescha** [comment]
not stale
