### ISSUE TITLE
Error "missing script: build:cli" when running "npm run watch"

### ISSUE THREAD

**Issue by szimek** [gatsbyjs/gatsby#2451]
`watch` task is defined in `packages/gatsby/package.json` as 
```
rimraf dist && mkdir dist && npm run build:cli && npm run build:internal-plugins && npm run build:rawfiles && npm run build:src -- --watch
```
When running `npm run watch` in `gatsby` repo, I'm getting errors for `gatsby` package saying `missing script: build:cli`. I can't find it defined anywhere in the repo. 

The only place where's it's defined is: `./node_modules/rollup/package.json:20:    "build:cli": "rollup -c rollup.config.cli.js",`, but I don't think that's the one that `watch` task is  trying to run.

**Comment by markmichon** [comment]
Try removing node modules, and possibly the lock file. Then run yarn bootstrap again. That generally fixes any weird issues.

**Comment by szimek** [comment]
The problem is that this `build:cli` task is not defined anywhere in the repo, so reinstalling packages won't help. Just run `git grep 'build:cli'` or `grep -rnw '.' -e 'build:cli'` to see yourself. There's a `build` task defined for `gatsby` package and it's almost exactly the same as the `watch` task, except it doesn't call `build:cli`.

`watch` task:
```
rimraf dist && mkdir dist && npm run build:cli && npm run build:internal-plugins && npm run build:rawfiles && npm run build:src -- --watch
```

`build` task:
```
rimraf dist && npm run build:src && npm run build:internal-plugins && npm run build:rawfiles
```

**Comment by markmichon** [comment]
Ah. Looks like it might have happened in #1969. https://github.com/gatsbyjs/gatsby/commit/af5c9c86a604d2f6d441a793d1df3cd7b2cba793#diff-d42476695f98af8f85d595ac39bc0653L156

Perhaps @jquense knows whats up?

**Comment by KyleAMathews** [comment]
Thanks for the report @szimek! It should be fixed now.
