### ISSUE TITLE
Gatsby develop fails - yoga-layout and urql

### ISSUE THREAD

**Issue by whoisryosuke** [gatsbyjs/gatsby#24514]
## Description

Gatsby develop command fails immediately and displays error for yoga-layout and urql.

Not sure what caused this issue. I recently updated my Gatsby site to the latest version using `yarn add gatsby@latest` to enable conditional page builds. It worked great, the dev and build processes worked fine. I reopened the project, added a new MDX post, spun up the dev server, and immediately started seeing this issue. 

I tried updating the rest of my dependencies but saw no improvement. I also tried clearing the `.cache` and `node_modules` and reinstalling dependencies multiple times -- I still see the same error.

I think this might be related to https://github.com/gatsbyjs/gatsby/issues/22991 and https://github.com/gatsbyjs/gatsby/issues/23202. I'm using Node 13, which is a known issue?

### Steps to reproduce

1. Clone [my repo at this point](https://github.com/whoisryosuke/ryosuke-gatsby-blog/tree/broken-dev-server)
2. Install dependencies `yarn`
3. Run develop `yarn develop`

### Expected result

Gatsby develop process works as intended.

### Actual result

Development server crashes immediately (before anything really happens, like GraphQL or page generation). The following error is displayed:

```
/Users/ryo/Development/Projects/ryosuke-gatsby-blog/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: No valid exports main found for '/Users/ryo/Development/Projects/ryosuke-gatsby-blog/node_modules/@urql/core'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/ryo/Development/Projects/ryosuke-gatsby-blog/node_modules/urql/dist/urql.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND'
}
```

### Environment

```
 System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 74.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.11 => 2.22.11
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-link: ^2.4.3 => 2.4.3
    gatsby-paginate: ^1.1.1 => 1.1.1
    gatsby-plugin-feed: ^2.5.3 => 2.5.3
    gatsby-plugin-google-analytics: ^2.3.2 => 2.3.2
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9
    gatsby-plugin-mdx: ^1.2.12 => 1.2.12
    gatsby-plugin-offline: ^3.2.7 => 3.2.7
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9
    gatsby-plugin-sitemap: ^2.4.3 => 2.4.3
    gatsby-plugin-styled-components: ^3.3.2 => 3.3.2
    gatsby-plugin-twitter: ^2.3.2 => 2.3.2
    gatsby-plugin-typescript: ^2.4.3 => 2.4.3
    gatsby-remark-copy-linked-files: ^2.3.3 => 2.3.3
    gatsby-remark-images: ^3.3.8 => 3.3.8
    gatsby-remark-prismjs: ^3.5.2 => 3.5.2
    gatsby-remark-smartypants: ^2.3.2 => 2.3.2
    gatsby-source-filesystem: ^2.3.8 => 2.3.8
    gatsby-transformer-json: ^2.4.3 => 2.4.3
    gatsby-transformer-remark: ^2.8.13 => 2.8.13
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3
  npmGlobalPackages:
    gatsby-cli: 2.11.18
```

**Comment by KyleAMathews** [comment]
Older versions of Node 13 error in @urql/core — see https://github.com/FormidableLabs/urql/issues/788 for details. If you upgrade to node 13.14.0 or above things will work.

Note that odd major versions of Node are unstable so keeping to even releases like 12 & 14 are generally better bets.
