### ISSUE TITLE
Normalising Node Data

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#24539]
I'm working on a Gatsby site which shares components with other SPAs. One thing that causes friction is the format of the data supplied by GraphQL queries in Gatsby. Data is located in various different places on a GraphQL node. I've adopted a pattern of normalising the data I need by mapping it over to the `fields` attribute of a node (See a plugin I wrote for this [here](https://github.com/Undistraction/gatsby-plugin-node-fields)), however even adopting this approach, the data object you have to work with is effectively:
```javascript
{ 
   fields: {
     alpha: 1,
     bravo: 2,
   }
}
```
This means that data is not at the root of the object, but one level deep. Ideally I would like to be able to pass around objects without worrying about this extra level of nesting which would also mean components shared with other SPAs can expect data in a normalised shape.

Obviously it would be simple to create a generic transformer function that took a node and returned a new object with the attributes of `field` at the root, however this does't scale very well, and becomes problematic with nested relations, requiring either deep introspection / transformation, or later transformation at the point of consumption (probably within components).

I'm wondering if I'm missing something obvious here. Is there a clean way of transforming nodes at the point of query in such a way that associated nodes would also be transformed? Is there another approach to flattening node data to a more standard format?

**Comment by freiksenet** [comment]
Hello @Undistraction!

We are not there yet - but our idea about unifying data types from different sources is built around GraphQL interfaces and GraphQL adapter types. Eg if you'd make a generic article type using Interfaces (and using special directive `@nodeInterface` or inherit Node in newer graphql versions).

```graphql
type Article @nodeInterface {
  id: ID!
  title: String!
  body: String
}
```

To implement it for, for example, remark types, you'd need to proxy the it's into that type. For that we'll implement the type and write an adapter.

```js
schema.buildObjectType({
  fields: {
    title(parent) {
      return parent.frontmatter.title,
    },
    body(parent) {
      return parent.html
    }
  },
  interfaces: ['Article', 'Node'],
  extensions: {
    childOf: {
      type: 'MarkdownRemark',
    },
  },
})
```

Then you'll create a type for every MarkdownRemark using `onCreateType`.

Currently it's hard to do and kinda crude and non-perfomant, we want to make it more first-class in future. I hope this gives you a good overview of how we hope to solve this problem.

**Comment by Undistraction** [comment]
@freiksenet Thanks for taking the time to document this. I'd been toying with the idea of wrapping chunks of data in decorators that would proxy access to the underlying data, but this would be a great solution.
