### ISSUE TITLE
Deployment issue  error Building static HTML failed for path "/about/"

### ISSUE THREAD

**Issue by williamkwon97** [gatsbyjs/gatsby#24546]
## Description
I have a similar problem with this issue
https://github.com/gatsbyjs/gatsby/issues/12706
I didn't used the lazy or suspension code and I search for it too, but I didn't find anything.
https://github.com/williamkwon97/GatsbyJS
![Screen Shot 2020-05-27 at 1 33 04 PM](https://user-images.githubusercontent.com/34716439/83060552-3d3d1680-a021-11ea-90b4-770e812e823e.png)
my about.js
![Screen Shot 2020-05-27 at 1 31 14 PM](https://user-images.githubusercontent.com/34716439/83060580-4af29c00-a021-11ea-956e-bf9f3ff58135.png)

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by mnurik** [comment]
@williamkwon97 I don't think it is gatsby issue. While in build step you are trying to get `store` from empty context and then from `store` you are looking for value `isDark`. So if you give an initial value to context in `context.js` file, like: `createContext({ state: {/* your initial store */} })`, you will see the error gone. You still have an issue using `emotion-theming`, but it is different topic :)

**Comment by williamkwon97** [comment]
> @williamkwon97 I don't think it is gatsby issue. While in build step you are trying to get `store` from empty context and then from `store` you are looking for value `isDark`. So if you give an initial value to context in `context.js` file, like: `createContext({ state: {/* your initial store */} })`, you will see the error gone. You still have an issue using `emotion-theming`, but it is different topic :)

Hello thank you for responding. I learn gatsbyJS 2 days ago and never learn javascript properly before so could you fork what you mean? I basically finished tutorial from gatsbyjs and watched https://www.youtube.com/watch?v=g2GeQlvdqdo&t=2001s this videos to implement dark mode so not sure what to put as /* your initial store */. Also how is emotion-theming going to trouble after this?

**Comment by wardpeet** [comment]
Thanks so much for opening this issue! As stated, this is slightly tangential to Gatsby. Please go to [Discord](https://gatsby.dev/discord), they can probably help you with these issues.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪
