### ISSUE TITLE
gatsby-image wrapper className

### ISSUE THREAD

**Issue by dardub** [gatsbyjs/gatsby#2454]
In gatsby-image the className prop is applied to the second div and not the outer.

I'm using css grid to layout the images on the page, but this wrapper is affecting the positioning. I think this could also be tricky if using this in conjunction with flexbox.

I just wanted to see if it should be moved to the parent div, or add another prop for the parent div.

**Comment by KyleAMathews** [comment]
Yeah want to add a PR adding a class `gatsby-image-outer-wrapper` and prop `outerWrapperClassName`?

**Comment by dardub** [comment]
Sure!

**Comment by dardub** [comment]
I'm not sure how you could use a css prop with glamor in this. I think you would have to use the css helper.

```
<Image outerWrapperClassName={css(styles)} />
```

Any ideas on a cleaner way?

**Comment by KyleAMathews** [comment]
That looks about right! You can just use the css prop for the normal className as the css prop converts the styles into a className for you.
