### ISSUE TITLE
gatsby develop throwing Error: Cannot find module 'gatsby/dist/utils/develop'

### ISSUE THREAD

**Issue by jaanhio** [gatsbyjs/gatsby#2455]
Running "gatsby develop" with latest build is throwing the following error.
```
module.js:491
    throw err;
    ^

Error: Cannot find module 'gatsby/dist/utils/develop'
    at Function.Module._resolveFilename (module.js:489:15)
```
however it works fine with "npm run develop"

**Comment by dardub** [comment]
Just a check, but did you update gatsby-cli as well?

**Comment by jaanhio** [comment]
i see that mine is v1.0.12, while latest is v1.1.10.

sorry for the noob question but, how do i update it?

**Comment by jquense** [comment]
`npm install --global gatsby-cli@latest`

**Comment by jaanhio** [comment]
its working now. thanks!
