### ISSUE TITLE
One or more of your plugins have changed / GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES

### ISSUE THREAD

**Issue by aheissenberger** [gatsbyjs/gatsby#24568]
## Description

The build will always give this info when the `.cache` and `public` folder have been restored from a tar file.

```
gatsby build --write-to-file --log-pages
success open and validate gatsby-configs - 0.041s
success load plugins - 0.509s
success onPreInit - 0.019s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's no stale data.
```

### Steps to reproduce

I created a sample project with the Gatsby starter package

```
npx gatsby new gatsby-cache-problem
cd gatsby-cache-problem
yarn upgrade --latest
GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true yarn build --write-to-file --log-pages
tar czf gatsby-artifacts.tgz .cache/ public/
rm -fr .cache/ public/
tar -xf gatsby-artifacts.tgz
GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true yarn build --write-to-file --log-pages
```

### Expected result

```
$ gatsby build --write-to-file --log-pages
success open and validate gatsby-configs - 0.029s
success load plugins - 0.851s
success onPreInit - 0.030s
success initialize cache - 0.014s
success copy gatsby files - 0.121s
success onPreBootstrap - 0.007s
success createSchemaCustomization - 0.008s
success source and transform nodes - 0.048s
success building schema - 0.411s
success createPages - 0.002s
success createPagesStatefully - 0.073s
success onPreExtractQueries - 0.007s
success update schema - 0.035s
success extract queries from components - 0.318s
success write out requires - 0.007s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.166s
success onPostBootstrap - 0.178s
⠀
info bootstrap finished - 6.770s
⠀
success Building production JavaScript and CSS bundles - 4.896s
success run queries - 4.998s - 4/4 0.80/s
success Building static HTML for pages - 0.799s - 0/0 0.00/s
success Delete previous page data - 0.007s
success onPostBuild - 0.005s
info Done building in 12.696924662 sec
```

### Actual result

```
$ gatsby build --write-to-file --log-pages
success open and validate gatsby-configs - 0.042s
success load plugins - 0.572s
success onPreInit - 0.020s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's no stale data.
success initialize cache - 0.064s
success copy gatsby files - 0.072s
success onPreBootstrap - 0.030s
success createSchemaCustomization - 0.014s
success source and transform nodes - 0.175s
success building schema - 0.437s
success createPages - 0.004s
success createPagesStatefully - 0.102s
success onPreExtractQueries - 0.002s
success update schema - 0.039s
success extract queries from components - 0.443s
success write out requires - 0.015s
success write out redirect data - 0.009s
success Build manifest and related icons - 0.256s
success onPostBootstrap - 0.268s
⠀
info bootstrap finished - 5.504s
⠀
success Building production JavaScript and CSS bundles - 6.189s
success run queries - 6.402s - 7/7 1.09/s
success Building static HTML for pages - 0.678s - 0/0 0.00/s
success Delete previous page data - 0.002s
success onPostBuild - 0.005s
info Done building in 12.691495854 sec
```

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.3.0 - /var/folders/c3/xp8j5jx90s37thp58v2_76t80000gr/T/yarn--1590669969769-0.11111835422606897/node
    Yarn: 1.22.4 - /var/folders/c3/xp8j5jx90s37thp58v2_76t80000gr/T/yarn--1590669969769-0.11111835422606897/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.11 => 2.22.11 
    gatsby-image: ^2.4.5 => 2.4.5 
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9 
    gatsby-plugin-offline: ^3.2.7 => 3.2.7 
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2 
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9 
    gatsby-source-filesystem: ^2.3.8 => 2.3.8 
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3

**Comment by aheissenberger** [comment]
I debugged the problem and found 2 things:
1) the version of the `default-site-plugin` is a [file hash with this glob](https://github.com/gatsbyjs/gatsby/blob/2691f0947ef6040a2bbe7d0b3f4205eb5dc97436/packages/gatsby/src/bootstrap/load-plugins/load.ts#L238) `gatsby-*`
2) I created a tar named `gatsby-artifacts.tgz` in the project root which did not exist when the file hash was created and saved in the `.cache`

I solved the problem by changing the name of the created tar to not start with `gatsby-`

**Comment by sven5** [comment]
Is there any other solution?
I'm running an Azure Pipeline and like to cache Gatsby static files.

**Comment by haysclark** [comment]
@sven5 I just ran into this issue trying to take advantage of caching on a CI build setup. It looks like one can not touch 'package.json' or else it [invalidates the cache](https://github.com/gatsbyjs/gatsby/blob/f2d4830ef22666786e0020108d97379a853282b3/packages/gatsby/src/services/initialize.ts#L324) as well. We use Semantic Release for PR's and Release builds, all of which modify the package.json's version # via:

```bash
npm version $VERSION
```

**Comment by Mrchow86** [comment]
Mate I am telling you I have no idea what it is.. I uploaded 1 pic of my
face and that's it.. unless the site got all my permissions from apps but
I'm sorry I don't know
