### ISSUE TITLE
Any plan to support Snowpack?

### ISSUE THREAD

**Issue by kaushalyap** [gatsbyjs/gatsby#24566]
## Summary
Is there any plans to support [Snowpack](https://github.com/pikapkg/snowpack)? instead of Webpack

FYI:

- https://www.pika.dev/blog/pika-web-a-future-without-webpack
- https://blog.logrocket.com/snowpack-vs-webpack/
- https://www.snowpack.dev/posts/2020-05-26-snowpack-2-0-release/

**Comment by wardpeet** [comment]
Hey there!

We don't have any intention to support snowpack anytime soon. Snowpack is great for modern browsers but it hasn't got a good story for legacy ones. Also, snowpack doesn't support many assets besides javascript, typescript, JSON & CSS. We have plenty of users that use svg loaders, file loaders, ... Those are not yet available in snowpack.

Even if I'm not the biggest fan of webpack, they do have the most extensive ecosystem and have a big API surface we can use to improve our bundling.

I'm particularly curious why you triggered this question? :) What the reason you want snowpack as a replacement?

**Comment by kaushalyap** [comment]
> Snowpack is great for modern browsers but it hasn't got a good story for legacy ones. 

Yeah due to usage of ES modules, [no support for IE 11 and some others](https://caniuse.com/#feat=es6-module), but this will be solved with the time.

> I'm particularly curious why you triggered this question? :) What the reason you want snowpack as a replacement?

May be wondering possibility more build time improvement. I know now there are things like

- Gatsbyjs incremental builds 
- [Gatsby cache](https://github.com/jlengstorf/netlify-plugin-gatsby-cache) build plugins  
- [Parallel image processing
](https://www.netlify.com/blog/2020/02/25/gatsby-build-speed-improvements-with-parallel-image-processing/)

And also improvement of site performance due to [better caching](https://blog.logrocket.com/snowpack-vs-webpack/) 

At the end of the day if you need something really fast you one can go with [Pax.js](https://pax.js.org/) with [SWC](https://github.com/swc-project/swc)

**Comment by thefrontendwizard** [comment]
As far as my understanding goes, feel free to correct me if I'm wrong, but we could use snowpack for its developer experience features, but bundle the app at the when building for production.

I feel it could be worth exploring.

That said, as a big disclaimer here, I  haven't really used snowpack yet and have no idea how much effort it'd be to support it.

**Comment by Ciantic** [comment]
SVG is supported already, it's even used in the snowpack example:

`npx create-snowpack-app new-dir --template @snowpack/app-template-react-typescript`

Also, adding plugins to it seems rather straight forward. E.g. 

```
{
  "extends": "@snowpack/app-scripts-react",
  "scripts": {
    "build:scss": "sass $FILE"
  },
  "plugins": []
}
```

Adds SCSS import support, and it seems to work with SCSS/CSS modules also.

**Comment by LekoArts** [comment]
As my colleague said we don't have any plans to support anytime soon and thus the initial question was answered - so I'll close this issue.

Feel free to discuss further here though :)

**Comment by atomkirk** [comment]
I would like to see something faster for development than webpack. Takes 5-10s to reload and I'm using a slightly modified version of the contentful gatsby starter project. Webpack is excruciatingly slow.

**Comment by tony** [comment]
This snowpack stuff is continuing to get better btw. It's been nearly 1 year since the last comment.

- July 30th, 2020: [Snowpack v2.7.0](https://www.snowpack.dev/posts/2020-07-30-snowpack-2-7-release)
- January 13th, 2021: [Snowpack v3.0](https://www.snowpack.dev/posts/2021-01-13-snowpack-3-0)

Supported files: https://www.snowpack.dev/reference/supported-files include css modules, svg, jpg, png, wasm, typescript.
Javascript API: https://www.snowpack.dev/reference/javascript-interface

**Comment by joer-tt** [comment]
Adding to @frontendwizard 's comment...

Here's an example of a framework using Snowpack for local dev, and a bundler for production: https://svelte.dev/blog/whats-the-deal-with-sveltekit#How_is_this_new_thing_different

What's the benefit of keeping webpack for local dev?
