### ISSUE TITLE
cli: yoga-layout-prebuilt error on gatsby build

### ISSUE THREAD

**Issue by alexandresgf** [gatsbyjs/gatsby#24577]
## Description

After an update did using the command `npm update` and the Gatsby updated from 2.21.17 to 2.22.12 no command did using `gatsby-cli` works anymore.

### Steps to reproduce

1. Start a new gatsby project or just run `npm update`; and,
2. Try to execute `gatsby develop` or `build` or `serve`.

### Expected result

Expected to run the development server.

### Actual result

```
/home/alexandre/projects/bestcanais/frontend/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EACCES
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:677:19)
    at /home/alexandre/projects/bestcanais/frontend/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/loggers/ipc/index.js:58:13
    at dispatch (/home/alexandre/projects/bestcanais/frontend/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:54:5)
    at /home/alexandre/projects/bestcanais/frontend/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/internal-actions.js:42:7
    at dispatch (/home/alexandre/projects/bestcanais/frontend/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:33:5)
    at /home/alexandre/projects/bestcanais/frontend/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:30:28
    at Array.forEach (<anonymous>)
    at dispatch (/home/alexandre/projects/bestcanais/frontend/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:30:12)
    at Reporter.pendingActivity (/home/alexandre/projects/bestcanais/frontend/node_modules/redux/lib/redux.js:483:12)
    at module.exports (/home/alexandre/projects/bestcanais/frontend/node_modules/gatsby/dist/commands/develop-process.js:413:21)
    at Object.<anonymous> (/home/alexandre/projects/bestcanais/frontend/.cache/tmp-27267-PDO5cWsb1RYS:4:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/home/alexandre/projects/bestcanais/frontend/node_modules/signal-exit/index.js:161:32)
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'write'
}
```

### Environment

```
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
    Shell: 4.4.20 - /bin/bash
  Languages:
    Python: 2.7.17 - /home/alexandre/.pyenv/shims/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
  npmPackages:
    gatsby: ^2.21.17 => 2.22.12 
    gatsby-image: ^2.4.5 => 2.4.5 
    gatsby-plugin-google-analytics: ^2.3.2 => 2.3.2 
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9 
    gatsby-plugin-material-ui: ^2.1.9 => 2.1.9 
    gatsby-plugin-offline: ^3.2.7 => 3.2.7 
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2 
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9 
    gatsby-source-filesystem: ^2.3.8 => 2.3.8 
    gatsby-source-graphql: ^2.5.2 => 2.5.2 
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3 
```

**Comment by moreguppy** [comment]
Having a similar error when running `netlify dev` on a gatsby project. Running locally with `gatsby develop` is OK.

```
/Users/mikeguppy/Code/xxxx/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^
```

I'm on gatsby version 2.22.9, and gatsby cli version 2.12.21

**Comment by pieh** [comment]
What are node version you are using? We also do need some kind of reproduction for it.

**Comment by MrUltimate** [comment]
Same issue here #24589

**Comment by moreguppy** [comment]
@pieh I'm on node `v14.2.0`

Also if it helps: `macOS Catalina 10.15.4`

**Comment by moreguppy** [comment]
@pieh I just created a new gatsby project and updated to:
```
Gatsby CLI version: 2.12.21
Gatsby version: 2.22.12
Node version `14.2.0`
```
and `gatsby develop` runs fine. 

My issue was with running `netlify dev`, which threw an exception on that `yoga-layout-prebuilt` package same as @alexandresgf original post

**Comment by alexandresgf** [comment]
> What are node version you are using? We also do need some kind of reproduction for it.

`node 12.17.0 LTS`

I just downgrade the Gatsby version to `2.21.17`, and for now, it is working fine.

**Comment by vladar** [comment]
Could be related: #22558, #23214, #24411. Can be also related: https://github.com/gatsbyjs/gatsby/issues/22991#issuecomment-630381390

**Comment by pieh** [comment]
I wonder if this is case of some error being eaten by `ink` and hiding real problem that is not actually related to `ink` - could you try running `CI=1 gatsby develop` (or `CI=1 netlify dev` in case of @moreguppy)?

This should force using "legacy" logger (which is not using `yoga-layout-prebuilt`) - if there are errors - we can inspect them. If there are no errors we can at least be more sure that it is somewhat related to `ink` logger

**Comment by gustavpursche** [comment]
I'm also running into this problem. Ran the `CI=1 gatsby develop` which prints:

```
> lm@1.0.0 develop /home/gustav/Development/lm
> CI=1 gatsby develop

/home/gustav/Development/lm/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EACCES
    at process.target._send (internal/child_process.js:811:20)
    at process.target.send (internal/child_process.js:682:19)
    at /home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/loggers/ipc/index.js:58:13
    at dispatch (/home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:54:5)
    at /home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/internal-actions.js:42:7
    at dispatch (/home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:33:5)
    at /home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:30:28
    at Array.forEach (<anonymous>)
    at dispatch (/home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:30:12)
    at Reporter.pendingActivity (/home/gustav/Development/lm/node_modules/redux/lib/redux.js:483:12)
    at module.exports (/home/gustav/Development/lm/node_modules/gatsby/dist/commands/develop-process.js:410:21)
    at Object.<anonymous> (/home/gustav/Development/lm/.cache/tmp-43477-3sp50vYLAonc:4:5)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/home/gustav/Development/lm/node_modules/signal-exit/index.js:155:32)
    at internal/child_process.js:815:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -13,
  code: 'EACCES',
  syscall: 'write'
}
```

Gatsby version: `2.23.3`

**Comment by blainekasten** [comment]
You could probably work around this by installing `ink` and running with the ink logger. 

`GATSBY_LOGGER=ink gatsby develop`

It's strange that gatsby is picking the `ipc` logger. The reason it's failing is because the ipc logger sends it's data to the parent process. But i don't understand why there is a parent process here when just running gatsby develop.

**Comment by gustavpursche** [comment]
@blainekasten Unfortunately not:

```
kolle-on-xps :: Development/lm » GATSBY_LOGGER=ink npx gatsby develop
/home/gustav/Development/lm/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EACCES
    at process.target._send (internal/child_process.js:811:20)
    at process.target.send (internal/child_process.js:682:19)
    at /home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/loggers/ipc/index.js:58:13
    at dispatch (/home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:54:5)
    at /home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/internal-actions.js:42:7
    at dispatch (/home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:33:5)
    at /home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:30:28
    at Array.forEach (<anonymous>)
    at dispatch (/home/gustav/Development/lm/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/redux/index.js:30:12)
    at Reporter.pendingActivity (/home/gustav/Development/lm/node_modules/redux/lib/redux.js:483:12)
    at module.exports (/home/gustav/Development/lm/node_modules/gatsby/dist/commands/develop-process.js:410:21)
    at Object.<anonymous> (/home/gustav/Development/lm/.cache/tmp-46528-C7kBELRkUd53:4:5)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/home/gustav/Development/lm/node_modules/signal-exit/index.js:155:32)
    at internal/child_process.js:815:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -13,
  code: 'EACCES',
  syscall: 'write'
}
```

even after installing `ink`:

```
kolle-on-xps :: Development/louise-michel » npm ls -g | grep ink
├─┬ ink@2.7.1
│ ├─┬ bin-links@1.1.7
│ │ ├── bin-links@1.1.7 deduped
│ │ ├── bin-links@1.1.7 deduped
```

**Comment by blainekasten** [comment]
Oh, I just realized you are using `npx`, I'm betting that's the problem. Can you try installing gatsby globally?

```
yarn global add gatsby-cli
gatsby develop
```

**Comment by gustavpursche** [comment]
@blainekasten 

```
kolle-on-xps :: Development/lm » npm ls -g | grep gatsby-cli
├─┬ gatsby-cli@2.12.47
```

Unfortunately this dosn't change anything. Stacktrace looks exactly the same.

**Comment by wardpeet** [comment]
@gustavpursche yes that narrows it down. We can check what changed between those versions. Thank you!

**Comment by blainekasten** [comment]
This is the publish commit for [2.21.40](https://github.com/gatsbyjs/gatsby/commit/0c0880999c0294748f6815ba63c5e06f14d1c0f7).
This is the publish commit for [2.22.0](https://github.com/gatsbyjs/gatsby/commit/e393c89cf82db382a1f080c7a497536b06aef1da)

The only commit [between](https://github.com/gatsbyjs/gatsby/commits/e393c89cf82db382a1f080c7a497536b06aef1da) those two is [d4ec5e5e081f46ae33578861bcfb29d9554e099a](https://github.com/gatsbyjs/gatsby/commit/d4ec5e5e081f46ae33578861bcfb29d9554e099a)

**Comment by blainekasten** [comment]
Looks like this is when @mxstbr added the `develop-process` code.

**Comment by blainekasten** [comment]
@gustavpursche I'm curious, does `npx` work for you with other uses non gatsby related?

**Comment by gustavpursche** [comment]
@blainekasten The only regular npx command I'm (willingly) using is `npx serve` - which works.

I'm also using other globally installed node cli tools and they all work, so I guess it is not a permission issue.

🤷

**Comment by gustavpursche** [comment]
@blainekasten Had a look today, but I couldn't find anything useful here. :sob: The only thin I discoverd, which is different from the issue description is, that `gatsby build` and `gatsby serve` are working. The problem only occurs when running `gatsby develop`.

I've also tried it with `gatsby-cli` installed and without - same result. I'd be super happy if you or @mxstbr do have an idea. Happy to support you with anything you need.

**Comment by gustavpursche** [comment]
@alexandresgf @moreguppy @MrUltimate 

In case you are also still struggeling with this: I've created/ forked a docker project, which helps me now running gatsby with a recent version: https://github.com/gustavpursche/gatsby-docker

**Comment by ibraheemdev** [comment]
I am having the same issue on netlify with gatsby build

**Comment by ibraheemdev** [comment]
Oh, nvm. The issue is gone after I cleared netlify's cache and rebuilt the site 👍

**Comment by g1eny0ung** [comment]
We had the same problem on CircleCI. After troubleshooting, this article helps us to solve this problem.

https://support.circleci.com/hc/en-us/articles/360038192673-NodeJS-Builds-or-Test-Suites-Fail-With-ENOMEM-or-a-Timeout

The container we used is 2CPU/4GB, so we limit gatsby to use only 1 CPU: `GATSBY_CPU_COUNT=1 yarn build`.

**Comment by mxstbr** [comment]
The stack trace shows the the develop child process trying to `process.send` an IPC message to the develop parent process (a `reporter.pendingActivity` call).

The actual `process.send` call all the way at the top of the stack trace is failing with `Error: write EACCES`, which is [the error code](https://nodejs.org/api/errors.html#errors_common_system_errors) for "An attempt was made to access a file in a way forbidden by its file access permissions."

That's about as far as I have gotten, as I have absolutely no clue why `process.send` would trigger a file access error 🤔 Maybe @sidharthachatterjee has run into this before?

**Comment by geekiam** [comment]
I have faced the same issue on builds on Netlify.

![image](https://user-images.githubusercontent.com/6225592/90749626-5bdb4280-e2dc-11ea-8af5-517edfdecba1.png)

**Comment by Levino** [comment]
I have this issue with local builds. See #26439 for details. None of the above "fixes" works for me...

**Comment by mcqj** [comment]
I've encountered a similar issue with local builds.
A workaround that has worked form me is to use "yarn Install" on my project instead on "npm install" (after deleting node_modules). So far, I have not been able to determine why that makes a difference but it does and consistently. I've verified with both MacOS and Linux and with node v12.18.3 v12.13.0 and v14.8.0

**Comment by gustavpursche** [comment]
@mcqj You are my hero. I can confirm that doing the same in yarn works. :sparkles:

**Comment by mfuery** [comment]
I was getting this error when netlify tried to build. Clear Netlify Cache and Rebuild worked for me 🎉
p.s. I was not getting an error locally, neither via `gatsby develop` nor `gatsby build`.

**Comment by geekiam** [comment]
@mfuery yeah, that's exactly my case. But I don't want to manually restart builds every time when someone from my team open PR and preview fails with this error 😫

**Comment by Levino** [comment]
As I said in #26439 I have an example [commit](https://github.com/hardforkio/homepage/tree/4701c3430d3aa604022db36ff8f25ebf960943ef) to reproduce the issue. Just check it out. Also you can see the failing build here: https://app.circleci.com/pipelines/github/hardforkio/homepage/1229/workflows/1477ff4a-8837-48f6-a824-be816c58ed37/jobs/6321

**Comment by Levino** [comment]
So when I install the deps with `npm` I can build. Even run `yarn build` not `npm run build`. So that's the inverse of what @mcqj said. WTF?

**Comment by azhang** [comment]
```
rm -rf node_modules
yarn install
yarn build
```

worked for me. Thanks @mcqj 

I haven't used npm install in years but somehow this yarn reinstall fixed things.

**Comment by Levino** [comment]
This is still an issue.

**Comment by ibraheemdev** [comment]
It is an issue, but clearing the cache almost always fixes it. Any thoughts on a potential solution?

**Comment by 5minpause** [comment]
I had the same issue.
```
rm -rf node_modules
yarn install
GATSBY_CPU_COUNT=1 yarn build
```
worked for me. That was the only solution that worked for me. I used yarn before.

**Comment by ibraheemdev** [comment]
not stale

**Comment by wardpeet** [comment]
the yoga prebuild is the catch all, the stack trace should tell you more where the real error is. GLib error means it's a sharp issue. Upgrading to the latest plugin-sharp might help here

**Comment by niecnasowa** [comment]
I just had the same issue, somewhat it was connected with imports to blog components in post preview in netlify cms. For me removing package-lock.json was the solution.

**Comment by UtkarshKr007** [comment]
> I just had the same issue, somewhat it was connected with imports to blog components in post preview in netlify cms. For me **removing package-lock.json** && `rm -rf node_modules` && `npm install` was the solution.

Thanks. That fixed it for me.

**Comment by rfink** [comment]
Still having this issue

**Comment by ashwinkjoseph** [comment]
This issue is still present.
I've tried clearing the cache, removing node_modules, tried with yarn and npm, after removing the lock files, tried on node v10, v12, v14, v15. I also tried upgrading all the packages to their latest versions.
downgrading only introduced new issues related to reducers.

**Comment by marharyta** [comment]
still having an issue, more details here: https://github.com/gatsbyjs/gatsby/issues/27891

**Comment by djcritch** [comment]
also getting this issue very frustrating nothing anyone has suggested has solved it for me ..


`12:15:53 AM: /opt/build/repo/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
12:15:53 AM:         throw ex;
12:15:53 AM:         ^
12:15:53 AM: Error: Callback was already called.
12:15:53 AM:     at throwError (/opt/build/repo/node_modules/neo-async/async.js:16:11)
12:15:53 AM:     at /opt/build/repo/node_modules/neo-async/async.js:2818:7
12:15:53 AM:     at processTicksAndRejections (internal/process/task_queues.js:79:11)
12:15:53 AM: npm ERR! code ELIFECYCLE
12:15:53 AM: npm ERR! errno 7
12:15:53 AM: npm ERR! gatsby-starter-netlify-cms@1.1.3 build: `npm run clean && gatsby build`
12:15:53 AM: npm ERR! Exit status 7
12:15:53 AM: npm ERR!
12:15:53 AM: npm ERR! Failed at the gatsby-starter-netlify-cms@1.1.3 build script.
12:15:53 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
12:15:53 AM: npm ERR! A complete log of this run can be found in:
12:15:53 AM: npm ERR!     /opt/buildhome/.npm/_logs/2021-02-09T00_15_53_466Z-debug.log`

**Comment by wardpeet** [comment]
Are you all using netlify-cms?

**Comment by djcritch** [comment]
i am using netlify-cms-app

I just removed the options section from gatsby-config.js as suggested here: https://github.com/gatsbyjs/gatsby/issues/27891 and the build seems to be working now....

I replaced:

    {
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
        modulePath: `${__dirname}/src/cms/cms.js`,
      },
    },

with:

    {
      resolve: 'gatsby-plugin-netlify-cms',
    },

**Comment by ma-bourassa** [comment]
@djcritch Did the same but I did not find a way to use my preview components yet.

**Comment by hoangbn** [comment]
It only happens when `cms.js` has `registerPreviewTemplate`

**Comment by gcutrini** [comment]
It is actually happening at the import level.

This builds:
```javascript
import CMS from 'netlify-cms-app'

// But these mere imports triggers the build error
/*
import BlogPostPreview from './preview-templates/BlogPostPreview'
import IndexPagePreview from './preview-templates/IndexPagePreview'
*/

import { Widget as FileRelationWidget } from '@ncwidgets/file-relation'
import { Widget as IdWidget } from '@ncwidgets/id'

CMS.registerWidget(IdWidget)
CMS.registerWidget(FileRelationWidget)

CMS.registerPreviewStyle('style/styles.scss');

function FooPreview({ entry, widgetFor }) {
  return null
}

CMS.registerPreviewTemplate('foo', FooPreview)
```
Downgrading ```gatsby-plugin-netlify-cms``` did not work for me.

**Comment by gianlucacandiotti** [comment]
Still seeing this issue, was playing with versions but couldn't figure it out .

**Comment by MKrupauskas** [comment]
This started happening when my preview component was rendering content. Downgrading, upgrading gatsby, netlify-cms packages didn't resolve the issue

**Comment by unimprobable** [comment]
I am having this issue on a Windows 10 machine, not using netlify-cms. The project builds fine on netlify, but breaks in local development.

**Comment by MKrupauskas** [comment]
I've managed to solve this issue in my project. It had to do with importing sass in my Layout component. I switched to just linking to the compiled CSS. I now also link the CSS directly in the netlify CMS script though this might not be needed. This is just one quick and dirty way of solving this issue for now but there may be ways of resolving this by changing the sass compilation implementation. This issue refers to something like this and it gave me the idea to check the sass imports https://github.com/gatsbyjs/gatsby/issues/27891.

**Comment by erezrokah** [comment]
Hi all 👋  Erez from Netlify here. Going to start looking into this issue.
I somehow think this is related to having custom preview templates + a dirty cache, but not sure what the actual cause of the error yet.

**Comment by gcutrini** [comment]
Hi Erez, this happens too when clearing cache (on Netlify). Also happens on
local env with gatsby build.
It is related to custom preview _imports_ . Just importing the templates
triggers the error.
Thanks for looking into it!

**Comment by Artofaj** [comment]
I can confirm deleting my custom preview templates and their corresponding imports solves the issue.

**Comment by miguelt1** [comment]
same issue here, it happens when I import my css and import my custom preview templates, if i delete them it works.
But I would love to have that feature in my project, can you guys solve that problem quickly? :)

**Comment by dlangsam** [comment]
I've been getting this error when trying to deploy to netlify. 
npm run build
gatsby develop
gatsby build 
netlify dev
all work on my machine. I tried to clear cache and deploy but it still failed on the same error.

**Comment by pawelbrzezinski** [comment]
@erezrokah any update on this one? Does anyone know which versions are stable so we can get a build "green" while waiting for the fix?

**Comment by erezrokah** [comment]
Hi @pawelbrzezinski, not yet - but I do have a reproduction for this locally. Will update once I make some progress.

**Comment by erezrokah** [comment]
A possible workaround if you're using `yarn` is to add the following to `package.json`:
```
"resolutions": {
    "mini-css-extract-plugin": "0.11.2"
  },
```

The underlying cause seems to be that both Gatsby and the CMS plugin have `mini-css-extract-plugin` as a dependency but with mismatching versions.

Looks like a [PR to solve it was already merged](https://github.com/gatsbyjs/gatsby/pull/29642), but not released yet .
I'll verify everything works with the latest changes from Gatsby's `master` branch.

**Comment by logemann** [comment]
After doing a rollback of my v3 migration today because of this very ugly gatsby-plugin-netlify-cms package, i suddently getting this error too in my v2 distro. Dont know if this is related to my previous v3 migration but seems unlikely because i reverted and cleaned everything.

I could fix it with what was proposed already:
```
/*            
     options: {
                modulePath: `${__dirname}/src/cms/cms.js`
     }
*/
```

But one need the modulePath right? So this seems not a viable workaround. I must say that i am little bit disappointed that Netlify-CMS gives me such a hard time currently. Not getting v3 is one thing but now even my previous stable distro is kind of defunct.

**Comment by erezrokah** [comment]
@logemann can you share the issues you've had with Gatsby v3 and the CMS?

We're in the process of updating it on the [CMS repo](https://github.com/netlify/netlify-cms/pull/5057). The only issue I had so far is that I had to keep `gatsby-plugin-emotion` at `v4` to avoid using `emotion@11` (the CMS uses `emotion@v10`).

**Comment by logemann** [comment]
@erezrokah see #29951

**Comment by technoken35** [comment]
> `'gatsby-plugin-sass', `

This worked for me minus the changes to the SASS config. I had to leave it as 'gatsby-plugin-sass'. Otherwise, it would throw an error when trying to compile my SASS files.

**Comment by michaelcorley** [comment]
@erezrokah Could you list out the steps needed to solve this issue? I tried adding the code you said to `package.json` and running a fresh `npm i` after deleting node_modules and the package-lock.json file but I'm still getting this error.

**Comment by erezrokah** [comment]
Hi @michaelcorley the `"resolutions"` field in `package.json` only works if you're using `yarn`.

[This tool](https://github.com/rogeriochaves/npm-force-resolutions) might work for `npm` but I haven't tested it.

**Comment by jf-home** [comment]
I had to comment out the import and register entries in cms.js to get around the problem.  Would love to see a fix for this (I use npm rather than yarn)

**Comment by logemann** [comment]
Until recently i thought its a v3 thing but now i also have it in a v2 project. Removind modulePath from cms plugin fixes it, but this is not a viable workaround. Are there some news? This error is just plain ugly.

**Comment by logemann** [comment]
"Looks like a PR to solve it was already merged, but not released yet."

@erezrokah Any news on this? I thought for a second that there will be a gatsby-plugin-netlify-cms v4.11.0 which solved this issue by using a mini-css-extract-plugin version aligned to gatsby npm module.

**Comment by erezrokah** [comment]
Hi @logemann, I think updating to the latest versions of Gatsby (v3) and the plugin (v5) should fix this. We are using both of them for `www.netlifycms.org` without issues:
https://github.com/netlify/netlify-cms/blob/85550eba9e55c65c2f9fa9493c3b114546eab1ea/website/package.json#L22

So this is not fixed in `v4` but in `v5` + Gatsby v3.

We can consider back porting a fix (pending approval of the maintainers of this repo) if there's a good reason to do it.

**Comment by logemann** [comment]
given the fact that not every project will be ported to v3, it would be a good idea to backport it.

**Comment by erezrokah** [comment]
> given the fact that not every project will be ported to v3, it would be a good idea to backport it.

Good point. See PR https://github.com/gatsbyjs/gatsby/pull/31093

**Comment by erezrokah** [comment]
Hi @logemann, can you try with `gatsby-plugin-netlify-cms@4.10.1` per https://github.com/gatsbyjs/gatsby/pull/31093#issuecomment-829113521?

**Comment by LekoArts** [comment]
This was fixed with https://github.com/gatsbyjs/gatsby/pull/31093

**Comment by logemann** [comment]
@erezrokah removed "resolutions" workaround in packages.json, got the error, used 4.10.1 dependency --> worked! Thanks for your efforts !! #31093 is the man.

**Comment by jf-home** [comment]
As requested by @erezrokah ...I'm having issues with the build as outlined below: 

```
gatsby-plugin-purgecss: Only processing  C:\home\hello-i8n\src\components\all.sass
⠋ Building development bundle
C:\home\hello-i8n\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: Callback was already called.
    at throwError (C:\home\hello-i8n\node_modules\neo-async\async.js:16:11)
    at C:\home\hello-i8n\node_modules\neo-async\async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

My repo can be found here: [https://github.com/jf-home/hello-i8n](https://github.com/jf-home/hello-i8n)

The only way that I have found to get around the error is to comment out lines 5 to 16 in `\src\cms\cms.js` but this then prevents a meaningful preview inside netlify cms.

Thanks in advance for any assistance provided.

**Comment by erezrokah** [comment]
Hi @jf-home, for some reason you also have mismatching dependencies, see:
![image](https://user-images.githubusercontent.com/26760571/118398909-4fb1c500-b663-11eb-8f20-a16d1cf37b2d.png)

I was able to fix this by running:
```
npm install gatsby@2
```

See PR https://github.com/jf-home/hello-i8n/pull/1

**Comment by doublejosh** [comment]
Dang, I get this error but I'm using `gatsby-source-sanity` as my data source.

**Comment by AbdallahAbis** [comment]
same error using `gatsby-source-sanity`

**Comment by SachaG** [comment]
I'm not using any of these plugins but still got this same error. Any idea how to fix it?

**Comment by robwilkerson** [comment]
I seem to be bumping into this as well. 

```
# node --version
v16.18.0
```

```
# gatsby -v
Gatsby CLI version: 4.24.0
Gatsby version: 4.24.6
```

I can't find anything that helps me get past this error in the build process. Any information that might get me a step along the way would be much appreciated.

**Comment by Bhanahnah** [comment]
Still getting this error, 2 years later, with `yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53`
