### ISSUE TITLE
Ways to reduce graphql bloat in components, wrapper component or best practice?

### ISSUE THREAD

**Issue by conspireagency** [gatsbyjs/gatsby#24584]
## Summary

Have you ever seen a Gatsby Image wrapper (think that's what you'd call it) used to dynamically make the graph ql queries? Gatsby Image is great and all, but when you're using it for multiple images in a component the graphql really can get messy bloating the component.

Would be nice if there was some way to internalize the graphql query by using a wrapper component, something that might look like:

`<ImageWrapper fluid='filename.jpg' /> or <ImageWrapper fixed='filename.jpg' />`

With all the graphql static queries internalized in the wrapper component.

It's something that we run into all the time and give a quick stab at, but as you can see in the example below it requires iterating through all images and isn't at all ideal / optimized.  Would be cool to know if anyone else has run into this and come up with a solution.

```
import React from 'react';
import { StaticQuery, graphql } from 'gatsby';
import Img from 'gatsby-image';
// Note: You can change "images" to whatever you'd like.
const Image = props => (
  <StaticQuery
    query={graphql`
      query {
        images: allFile {
          edges {
            node {
              relativePath
              name
              childImageSharp {
                fluid(quality: 50) {
                  ...GatsbyImageSharpFluid
                }
              }
            }
          }
        }
      }
    `}
    render={data => {
      const image = data.images.edges.find(n => {
        return n.node.relativePath.includes(props.filename);
      });
      if (!image) {
        return null;
      }
      //const imageSizes = image.node.childImageSharp.sizes; sizes={imageSizes}
      return <Img alt={props.alt} fluid={image.node.childImageSharp.fluid} />;
    }}
  />
);
export default Image;
```

### Motivation

People using multiple image + gatsby image in a component

**Comment by LekoArts** [comment]
Thank you for opening this!

This is the umbrella issue you'll want to read: https://github.com/gatsbyjs/gatsby/issues/10482

We are aware of this limitation and want to solve it eventually :) There are some workarounds like yours however they can degrade the performance when e.g. you use a lot of images. For a couple of images this shouldn't be a problem though.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
