### ISSUE TITLE
bug(gatsby-transformer-documentationjs): plugin causes error when no documentationJS nodes are found

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#24592]
##  Description

`gatsby-transformer-documentationjs` fails when no documentation nodes are defined.

### Steps to reproduce

1. create a project that uses the `gatsby-transformer-documentationjs` plugin
2. do not source any JS files
3. have a page/static query that calls `documentationJS`, eg:

```
allDocumenationJS {
  nodes {
    description {
      id
    }
  }
}
```

### Expected result

The `allDocumentationJS` query returns an empty array

### Actual result

Build fails with `Type with name "DocumentationJSComponentDescription" does not exists`

### Proposed solution

Add a `type DocumentationJSComponentDescription` with the appropriate fields to the gatsby-node of the plugin: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-documentationjs/src/gatsby-node.js#L47

### Environment

N/A

**Comment by luisFilipePT** [comment]
@tesseralis I think you have a typo `allDocumenationJS` instead of `allDocumentationJs` just to avoid people copy pasting and having a different bug ;)

**Comment by mikeattara** [comment]
Is anyone working on this?

**Comment by mikeattara** [comment]
@tesseralis can I work on it?

**Comment by tesseralis** [comment]
@mikeattara are you still interested in working on this?

**Comment by mikeattara** [comment]
@tesseralis yes
