### ISSUE TITLE
"gatsby-source-graphql" threw an error while running the sourceNodes lifecycle

### ISSUE THREAD

**Issue by dongtanhuy** [gatsbyjs/gatsby#24603]
## Description

`"gatsby-source-graphql"` threw an error while running the sourceNodes lifecycle

### Steps to reproduce

I faced this issue when deploying my Gatsby app to production.
I tried to upgrade `gatsby-source-graphql` plugin version to 2.5.2 (the latest) but it still didn't work

### Actual result

The log show that: `Response not successful: Received status code 400`

### Environment
```
success open and validate gatsby-configs - 0.092s
 
/bin/sh: lscpu: not found
 
/bin/sh: lscpu: not found
 
success load plugins - 0.917s
 
success onPreInit - 0.004s
 
success delete html and css files from previous builds - 0.014s
 
success initialize cache - 0.007s
 
success copy gatsby files - 0.033s
 
success onPreBootstrap - 0.014s
 
success createSchemaCustomization - 0.006s
 

 
 ERROR #11321  PLUGIN
 

 
"gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:
 

 
Response not successful: Received status code 400
 

 

 

 
  ServerError: Response not successful: Received status code 400
 
  
 
  - index.js:23 Object.exports.throwServerError
 
    [app]/[gatsby-source-graphql]/[apollo-link-http-common]/lib/index.js:23:17
 
  
 
  - index.js:48 
 
    [app]/[gatsby-source-graphql]/[apollo-link-http-common]/lib/index.js:48:21
 
  
 
  - next_tick.js:68 process._tickCallback
 
    internal/process/next_tick.js:68:7
 
  
 

 
not finished source and transform nodes - 0.347s
 
The command '/bin/sh -c gatsby build' returned a non-zero code: 1
 
 
Exited with code exit status 1 
CircleCI received exit code 1 
```

**Comment by vladar** [comment]
As the message suggests you are having an HTTP error. It is not a graphql error, it is probably something with your plugin or server configuration (missing auth headers, wrong endpoint, incompatible GraphQL server, etc).

Did you try running the same queries manually against your remote endpoint with the same configuration as the plugin has?

**Comment by hoantran3108** [comment]
We have 2 environments staging and production. Our static site is deployed on K8s cluster and sit behind a LB which basically have the same configuration. When we run `gatsby develop` on local machine with production environment it throws the same error but it does not crash the app so I'm able to go to localhost:8000 and all the requests to production GraphQL server success with status 200.

**Comment by vladar** [comment]
Network and server issues like this are nearly impossible to debug without an example/reproduction.

You can try debugging it yourself by providing a [`fetch` option](https://www.gatsbyjs.org/packages/gatsby-source-graphql/#how-to-use) to the plugin config and checking the actual request/response. Maybe it has a more specific error message.

```js
    // Advanced config, using a custom fetch function
    {
      resolve: "gatsby-source-graphql",
      options: {
        typeName: "GitHub",
        fieldName: "github",
        url: "https://api.github.com/graphql",
        // A `fetch`-compatible API to use when making requests.
        fetch: (uri, options = {}) =>
          fetch(uri, { ...options, headers: sign(options.headers) }),
      },
    },
```

Alternatively, you can debug this on the server as the request obviously reaches your GraphQL server so it should have some details on why it fails with HTTP 400 status code.

**Comment by hoantran3108** [comment]
Hello everyone, for anyone stumbling across the same issue. Our problem is that in the backend Graphql server when you specify the NODE_ENV=production the introspection schema is disabled intentionally which is why Gatsby won't be able to request to the server to build a schema.
We fixed it by generating introspection.json schema and add it to Gatsby repository and add the following into `gatsby-source-graphql`
```
  createSchema: async () => {
          const json = JSON.parse(
            fs.readFileSync(`${__dirname}/introspection.json`)
          )
          return buildClientSchema(json)
   },
```
I think the error should be more meaningful, direct to easily detect the problem

**Comment by vladar** [comment]
Closing this. And thanks for reporting back!
