### ISSUE TITLE
embed react stuff in remark'd html

### ISSUE THREAD

**Issue by brandonmp** [gatsbyjs/gatsby#2460]
I'm pulling markdown from Contentful via the contentful/remark plugins. 

For simple stuff like `<figure>`, I can just insert raw `html` into the markdown. For super complex stuff, I can host static `html` files & `iframe` them.

I'm wondering, though, how best to do React components that interact with the rendered HTML?

Simple example would be tooltips. for example, on this news site, any references to certain figures render as a link with an on-hover/click tooltip:

![image](https://user-images.githubusercontent.com/14139991/31580218-1f35f220-b117-11e7-91b2-a6758a5d1f4c.png)
 (sorry for the nsfw pic :) )
Since I'm taking the markdown html and setting it as the inner HTML, it's not clear to me how I'd inject React stuff into it first.

Is there a straightforward way to do this?

**Comment by KyleAMathews** [comment]
Not yet! But just wrote up a proposal on how to do this over on a long-running thread on this topic https://github.com/gatsbyjs/gatsby/issues/312#issuecomment-336681894
