### ISSUE TITLE
404 document error for generated pages

### ISSUE THREAD

**Issue by LpmRaven** [gatsbyjs/gatsby#24601]
I now generate all of my product and category pages using gatsby-node.js. Only my index page (waterproofjack.com) is being found on google webmasters, I've also checked the pages using deadlinkchecker, all pages return 404. They work when using the browser, but there seems to be some issue for bots. The site is hosted on AWS using S3 and Cloudfront, although the issue started when I switched to page generation in gatsby-node.js. Has anyone seen this issue or got any ideas? 

My site can be found here: https://waterproofjack.com/en-gb

<img width="900" alt="Screen Shot 2020-05-29 at 5 07 21 pm" src="https://user-images.githubusercontent.com/6523593/83231476-e2e1b880-a1ce-11ea-842b-697ae0c74be7.png">

As you can see below, it is looking for the document with the page name. 

<img width="1199" alt="Screen Shot 2020-05-29 at 5 06 20 pm" src="https://user-images.githubusercontent.com/6523593/83231390-c34a9000-a1ce-11ea-950a-bdc600034a11.png">

**Comment by LpmRaven** [comment]
Sorted it, I had incorrectly redeployed my cloudfront with the wrong 404 settings. The fix is under SPA on this page: https://gist.github.com/bradwestfall/b5b0e450015dbc9b4e56e5f398df48ff

**Comment by LpmRaven** [comment]
Sorry, I have to reopen this issue. Continuing my debugging of why my pages are not being indexed. As I previously mentioned, all of my product and category pages are generated using the API createPages. Since correcting my cloudfront configuration to respond 404s to index.html, I noticed that all the product and category pages are still being treated as 404s. 

Example product page: https://waterproofjack.com/en-gb/boys/snow-jackets-and-snow-coats/trespass-wato-navy

If you try to hit this page directly, it redirects to the home page (root). 

Does the API createPages require me to handle these pages as client-only routes?

**Comment by LpmRaven** [comment]
After further investigation, this is definitely an AWS S3 and CloudFront issue. 

This returns 404 (unless you have already hit the page): https://waterproofjack.com/en-gb/boys/snow-jackets-and-snow-coats/trespass-wato-navy
This works: https://waterproofjack.com/en-gb/boys/snow-jackets-and-snow-coats/trespass-wato-navy/index.html

Still have not worked out the CloudFront or S3 configuration to fix this, but I'm going to close the issue as it is not a gatsby issue.

**Comment by malisbad** [comment]
> After further investigation, this is definitely an AWS S3 and CloudFront issue.
> 
> This returns 404 (unless you have already hit the page): https://waterproofjack.com/en-gb/boys/snow-jackets-and-snow-coats/trespass-wato-navy This works: https://waterproofjack.com/en-gb/boys/snow-jackets-and-snow-coats/trespass-wato-navy/index.html
> 
> Still have not worked out the CloudFront or S3 configuration to fix this, but I'm going to close the issue as it is not a gatsby issue.

Did you figure out a solution for this? Sorry for dredging up problems, but I'm having the exact same problem, except even with the root loaded, it will always load the root page.

I can access the pages if I use the `/index.html` at the end of the path as well.

**Comment by LpmRaven** [comment]
> Did you figure out a solution for this? Sorry for dredging up problems, but I'm having the exact same problem, except even with the root loaded, it will always load the root page.
> 
> I can access the pages if I use the `/index.html` at the end of the path as well.

It was a while ago, I took a look at my commit history for you.

On the 3rd of June (1 day after my last message) I changed OriginProtocolPolicy from `https-only` to `http-only`.
```
  CustomOriginConfig:
    OriginProtocolPolicy: http-only #NOTE: -- 03/06/2020 Liam Raven -- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesOriginProtocolPolicy
```

The link says: "HTTP Only is the default setting when the origin is an Amazon S3 static website hosting endpoint, because Amazon S3 doesn’t support HTTPS connections for static website hosting endpoints. The CloudFront console does not support changing this setting for Amazon S3 static website hosting endpoints."

Try that? Let me know if it works.

**Comment by malisbad** [comment]
> > Did you figure out a solution for this? Sorry for dredging up problems, but I'm having the exact same problem, except even with the root loaded, it will always load the root page.
> > I can access the pages if I use the `/index.html` at the end of the path as well.
> 
> It was a while ago, I took a look at my commit history for you.
> 
> On the 3rd of June (1 day after my last message) I changed my AWS Cloudfront distribution OriginProtocolPolicy from `https-only` to `http-only`.
> 
> ```
>   CustomOriginConfig:
>     OriginProtocolPolicy: http-only #NOTE: -- 03/06/2020 Liam Raven -- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesOriginProtocolPolicy
> ```
> 
> The link says: "HTTP Only is the default setting when the origin is an Amazon S3 static website hosting endpoint, because Amazon S3 doesn’t support HTTPS connections for static website hosting endpoints. The CloudFront console does not support changing this setting for Amazon S3 static website hosting endpoints."
> 
> Try that? Let me know if it works.

Thanks for your help on this one, but it wasn't the solution I needed. I did end up fixing it using a cloudfront function to rewrite the URL. For anyone experiencing similar problems, I based my solution off of [this](https://blog.elantha.com/cloudfront-function-index-handling/) blog post that describes a fairly strong solution for it.
