### ISSUE TITLE
gatsby-image noscript img doesn't honor imgStyle

### ISSUE THREAD

**Issue by etabard** [gatsbyjs/gatsby#24617]
## Description

The imgStyle gatsby-image attribute is not reflected in noscript img.
Here is the code, we can see the static styling : https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js#L259

Thank you for your help !

### Steps to reproduce

Add an image with imgStyle={{ objectFit: contain }} and disable javascript before loading the page or look at the static html in the public dir after build

### Expected result

We should see <noscript><picture><img ... style="object-fit:contain" /></picture></noscript>

### Actual result

The actual output is : <noscript><picture><img ... style="object-fit:cover" /></picture></noscript>

### Environment
  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.3 => 2.22.3 
    gatsby-cli: ^2.12.29 => 2.12.29 
    gatsby-image: ^2.4.5 => 2.4.5 
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.2 
    gatsby-plugin-flow: ^1.1.21 => 1.3.2 
    gatsby-plugin-google-analytics: ^2.1.35 => 2.3.1 
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9 
    gatsby-plugin-netlify: ^2.1.32 => 2.3.2 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-offline: ^3.2.7 => 3.2.7 
    gatsby-plugin-preconnect: ^1.1.23 => 1.1.30 
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2 
    gatsby-plugin-remove-console: ^0.0.2 => 0.0.2 
    gatsby-plugin-remove-generator: ^1.0.4 => 1.0.4 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sharp: ^2.6.0 => 2.6.2 
    gatsby-plugin-sitemap: ^2.3.0 => 2.4.2 
    gatsby-plugin-styled-components: ^3.3.2 => 3.3.2 
    gatsby-plugin-svg-sprite-loader: ^0.1.4 => 0.1.4 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.9 => 1.1.9 
    gatsby-source-filesystem: ^2.1.48 => 2.3.1 
    gatsby-source-google-spreadsheet: ^2.0.0 => 2.0.0 
    gatsby-source-prismic: BreakingWeb/gatsby-source-prismic#download-raw-dist => 3.0.2 
    gatsby-transformer-json: ^2.2.28 => 2.4.1 
    gatsby-transformer-sharp: ^2.5.0 => 2.5.2

**Comment by stackrole-dev** [comment]
Hi @etabard ,
In this line it is added as `object-fit:cover;`

https://github.com/gatsbyjs/gatsby/blob/3429474b3bf34a0db4748c9ce3d8e4447bf9a153/packages/gatsby-image/src/index.js#L259

**Comment by etabard** [comment]
Hi @stackrole-dev, thanks for your reply !

Yes, my point is that it should honor the imgStyle attribute provided and not be "hardcoded". 
That way it will work when I add objectFit: contain.

**Comment by etabard** [comment]
Related to https://github.com/gatsbyjs/gatsby/pull/22607 and https://github.com/gatsbyjs/gatsby/issues/21799

I'm closing my issue and will follow the PR progress !
