### ISSUE TITLE
New Starters added to starter.yml not showing up in first page.

### ISSUE THREAD

**Issue by stackrole-dev** [gatsbyjs/gatsby#24616]
## Summary
Hi Gatsby Team,
I recently added a starter https://www.gatsbyjs.org/starters/stackrole/gatsby-starter-foundation/, but this does not show up in first page.

I spent close to a month on the starter and made open source to give back to community and gain exposure doing so. This is the case for many developers who contribute to GatsbyJS.

What are your thought on this? I think the new starter should be shown first, so that starter could build up some traction.

If new starters are going to be in bottom, no one would see them ruining the purpose they were built for.

Thank you.

## Relevant information

I followed the contribution guide and added my starter at the bottom of starter.yml. Also checked starter templates to see if there is any sorting added. But only thing i found out is. the starter are sorted based on the order they were kept in that file.

Shouldn't be new starter be added to top of list.

**Comment by stackrole-dev** [comment]
Hi @LekoArts,

Should i be moving my starter to top in starters.yml

**Comment by LekoArts** [comment]
Hi!
They are not sorted via their insertion order but by the stars they have. For now we'll keep it this way.

**Comment by stackrole-dev** [comment]
Hi @LekoArts,
I understand your point, Gatsby wants to offer the best starter to people. 

![image](https://user-images.githubusercontent.com/64824192/83345819-dd05e780-a334-11ea-926e-7efffdf56aa7.png)

But as you can see the screenshot above, the sorting order is not based on stars. if that is the case,  following should be order right.
1. gatsby-starter-blog (stars 2525)
2. gatsby-starter-netlify-cms (stars 1500)
3. 
.
.
. and so on

---

**Problem**: Bringing exposure to new starter, while having popular starters view.
**Solution**: Have a toggle button to switch between popular and new starters
![Frame 1](https://user-images.githubusercontent.com/64824192/83346065-0de71c00-a337-11ea-97fc-b81010e4ebac.png)

Is this something you guys are looking in future or accept a PR on that.

**Comment by LekoArts** [comment]
Thanks for the suggestion but we want to leave things as-is for now. I also fixed the bug that didn't sort the starters.

**Comment by stackrole-dev** [comment]
Thank you @LekoArts for fixing the bug
