### ISSUE TITLE
@babel/polyfill has been deprecated

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#24629]
## Summary

Installing `gatsby` produces a number of npm warnings about deprecated packages. While hunting down one of them, I noticed that gatsby [depends](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json#L16) on `@babel/polyfill`, which has been [deprecated](https://github.com/babel/babel/tree/master/packages/babel-polyfill).

In turn, @babel/polyfill depends on core-js@2, which has been deprecated and generates this warning when installing any Gatsby project:

```
$ npm install
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

### Motivation

Many users are confused by NPM warnings about deprecated packages:

* [NPM warn message about deprecated package](https://stackoverflow.com/questions/35236735/npm-warn-message-about-deprecated-package)
* [npm deprecated warnings – do I need to update something?](https://stackoverflow.com/questions/34840153/npm-deprecated-warnings-do-i-need-to-update-something)
* [How to deal with deprecation warnings from npm](https://stackoverflow.com/questions/38889519/how-to-deal-with-deprecation-warnings-from-npm)
* [npm install and deprecated warnings](https://stackoverflow.com/questions/40132400/npm-install-and-deprecated-warnings)
* [Getting npm WARN deprecated](https://stackoverflow.com/questions/58989617/getting-npm-warn-deprecated)

**Comment by LekoArts** [comment]
Thank you for opening this!

The core-js topic is known to us and tracked here: https://github.com/gatsbyjs/gatsby/issues/15601

In turn of this we'll also get rid of e.g. `@babel/polyfill`, possibly sooner than in a next major version. We're working on this.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
