### ISSUE TITLE
blog: Impossible food: Images should be inlined in repo and not hosted on googleusercontent.com

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#24626]
## Description

5 images linked external and hosted on googleusercontent.com

### Steps to reproduce

open https://www.gatsbyjs.org/blog/2020-05-07-gatsby-delivers-impossible-burgers-map/

inspect images or right click on and image and select open in new tab 

or look here: https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2020-05-07-gatsby-delivers-impossible-burgers-map/index.md

### Expected result

- images should placed in the blog directory
- images can be optimized by sharp / GatsbyImage
- independent from external image hosting

### Actual result

- hosted on googleusercontent.com
- not optimized by sharp / Gatsby Image

## Related Issues

- #23873 `add Impossible Burgers case study`

**Comment by muescha** [comment]
same here:

- #24244 `add Little and Big agency case study`

**Comment by LekoArts** [comment]
See https://github.com/gatsbyjs/gatsby/issues/24646#issuecomment-637314853

From the perspective of future contributors who clone the repository this would be hurtful if we enforce having every possible image in our repository.
