### ISSUE TITLE
How to use gatsbyjs + redux + redux-saga ?

### ISSUE THREAD

**Issue by imagine10255** [gatsbyjs/gatsby#24635]
Hi, How to use gatsbyjs + redux + redux-saga ?
can there be examples ?

**Comment by herecydev** [comment]
There's an example here that should help: https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redux

**Comment by LekoArts** [comment]
Thank you for opening this!

Please refer to the example, our [documentation](https://www.gatsbyjs.org/docs/adding-redux-store/), or any guides you'll find via Google.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
