### ISSUE TITLE
[gatsby-source-wordpress] fetch more than 100 posts

### ISSUE THREAD

**Issue by AlexHff** [gatsbyjs/gatsby#24639]
## Description

The goal is to fetch 2,000+ WordPress posts using the gatsby-source-wordpress plugin from this website: [https://wordpress-385135-1210443.cloudwaysapps.com/wp-json/](https://wordpress-385135-1210443.cloudwaysapps.com/wp-json/).

Unfortunately, only (at most) 100 posts are fetched. This issue is applicable for every resource from the WP API (media, comments, etc.). One interesting fact is that once in a while (~1/30), everything works perfectly fine without me changing a single line of code.

I already tried to increase the `per_page` value but the limit is 100 posts per page otherwise the API throws a `404`. When I set the `perPage` value in the `gatsby-config.js` to a value between 0 and 100, the plugin will fetch that exact number of resources.

I know that the plugin is supposed to loop over every page in order to fetch all of the posts.

### Steps to reproduce

I created a minimal reproducible test case [here](https://github.com/AlexHff/gatsby-bug-repro).

Just pull and `npm start`. In my case, it only fetches 100 posts.

### Expected result

```
 -> wordpress__wp_v2 fetched : 1
 -> wordpress__POST fetched : 2409
 -> wordpress__PAGE fetched : 3
 -> wordpress__wp_media fetched : 7741
 -> wordpress__wp_blocks fetched : 0
 -> wordpress__wp_types fetched : 1
 -> wordpress__wp_statuses fetched : 1
 -> wordpress__wp_taxonomies fetched : 1
 -> wordpress__CATEGORY fetched : 48
 -> wordpress__TAG fetched : 0
 -> wordpress__wp_users fetched : 3
```

### Actual result

```
 -> wordpress__wp_v2 fetched : 1
 -> wordpress__POST fetched : 100
 -> wordpress__PAGE fetched : 3
 -> wordpress__wp_media fetched : 100
 -> wordpress__wp_blocks fetched : 0
 -> wordpress__wp_types fetched : 1
 -> wordpress__wp_statuses fetched : 1
 -> wordpress__wp_taxonomies fetched : 1
 -> wordpress__CATEGORY fetched : 48
 -> wordpress__TAG fetched : 0
 -> wordpress__wp_users fetched : 3
```

### Environment

```
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 13.14.0 - ~/.nvm/versions/node/v13.14.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.14.0/bin/npm
  Languages:
    Python: 3.6.9 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
  npmPackages:
    gatsby: ^2.13.31 => 2.22.12
    gatsby-image: ^2.0.23 => 2.4.5
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-netlify: ^2.0.6 => 2.3.3
    gatsby-plugin-netlify-cms: ^4.1.6 => 4.3.3
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.1
    gatsby-plugin-react-helmet: ^3.0.4 => 3.3.2
    gatsby-plugin-sass: ^2.0.7 => 2.3.2
    gatsby-plugin-sharp: ^2.2.9 => 2.6.9
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.3.3
    gatsby-remark-images: ^3.1.6 => 3.3.8
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-source-filesystem: ^2.0.26 => 2.3.8
    gatsby-source-wordpress: ^3.3.8 => 3.3.8
    gatsby-transformer-remark: ^2.6.9 => 2.8.13
    gatsby-transformer-sharp: ^2.1.9 => 2.5.3
```

**Comment by TylerBarnes** [comment]
Hi @AlexHff , I finally had a chance to have a look at this and it appears to be working normally for me.

<img width="1017" alt="Screen Shot 2020-06-16 at 10 49 47 AM" src="https://user-images.githubusercontent.com/14190743/84809752-3d488a80-afbf-11ea-8efa-637e9eae9e74.png">

One thing you should definitely be aware of is `gatsby-source-wordpress@v3` (the version you're using here) will be soon deprecated for v4 which will work completely differently and use WPGraphQL internally instead of the REST API.

See this MD file for more info https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/feat/docs/docs/why-use-this-plugin.md#why-use-this-plugin-instead-of-x-source-plugin

**Comment by TylerBarnes** [comment]
I definitely recommend switching to `gatsby-source-wordpress-experimental` (which will become v4 soon) sooner than later. https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/feat/docs/README.md

**Comment by AlexHff** [comment]
Hi,

Thank you for your response.
From your screenshot, it doesn't appear to me that the fetch worked correctly. Observe that the number of `wp_media` fetched is limited to 100.

I found a temporary workaround which is to manually update any article on Wordpress. After that, the plugin fetches every resource normally. Nevertheless, I will upgrade the plugin to `gatsby-source-wordpress-experimental` which should fix the issue.

Thank you.
Alex
