### ISSUE TITLE
[docs][workflow] Implementing search with algolia.

### ISSUE THREAD

**Issue by mujeex** [gatsbyjs/gatsby#24641]
Part of the **Top 25 Learning Workflows initiative**. See #13708 for the meta issue that this issue falls under.

# User story
As a new Gatsby user, I would like to learn how to integrate Algolia into my Gatsby site. 

# Evaluation

| Search | Discover | Complete | Linked | Tone | Style | Overall |
| --- | --- | --- | --- | --- | --- | --- |
| 😄 |😄| 😄 | 😐 | 😐 | 😄 | 😄 |

# Steps taken to implement
1. Searchability
     i. Searched `gatsby algolia` on Google; clicked first [result](https://www.gatsbyjs.org/docs/adding-search-with-algolia/).
2. Discoverability
    i. Brought me right to the content i'm looking for at docs /adding-search-with-algolia/, thereby having no need to click on anything on .org.
3. Completeness
   i. Followed steps to install the `gatsby-plugin-algolia` and `react-instantsearch-dom`. **[rec]** Having the installation steps documented in the plugins page would go a long way as I could get easily intimidated reading up the installation process on the readme of the plugin on github.
  ii. Followed steps to configure algolia-plugin in gatsby-config.js file. **[rec]** Making explicit on where to create *.env* in project would save some research time. **[rec]** As well as a guide on how to setup env variables on the Netlify dashboard will be significant.
  iii. Followed steps to [adding search interface to site](https://www.gatsbyjs.org/docs/adding-search-with-algolia/#adding-a-search-interface-to-your-site).**[rec]** Though a new gatsby project works on the assumption that `gatsby-transformer-remark` plugin has be installed and that the appropriate fields in frontmatter of the markdown files are in place. So an explicit mention of this would go a long way.
  iv. Success!!
4. Linkedness
   i. Links to the [dotenv](https://www.npmjs.com/package/dotenv) docs on setup process would be very helpful.
 ii. Links to [styled components](https://www.gatsbyjs.org/docs/styled-components/) docs would be useful as well.
5. Tone
   i. Sometimes heavy on technical terminology; perhaps not completely understandable to a web development beginner.
6. Style
   i. **[rec]** A header for the section of setting up queries at `src/utils/algolia.js` would reduce the cognitive load.

# Recommendations

- [x] Completeness: Having the `gatsby-plugin-algolia` and `react-instantsearch-dom` installation steps documented in the plugins page would go a long way as I could get easily intimidated reading up the installation process on the readme of the plugin on Github.
- [x] Completeness: Making explicit on where to create *.env* in project would save some research time.
- [ ] Completeness: A guide on how to setup env variables on the Netlify dashboard will be significant.
- [ ] Completeness: An explicit mention to install `gatsby-transformer-plugin` and having the appropriate fields in the frontmatter of the markdown files would go a long way.
- [x] Style: A header for the section of setting up queries at `src/utils/algolia.js` would reduce the cognitive load.

**Comment by marcysutton** [comment]
Hi there, thanks for the issue! I've filed it internally to track, but if anyone wants to help with validating and implementing these recommendations we would welcome your contribution.

**Comment by ehrencrona** [comment]
I tried to follow the Algolia tutorial based on a new project created using `gatsby new`. That fails because the tutorial assumes that `gatsby-transformer-remark` is installed and that there are markdown files containing certain fields in the frontmatter. 

It would be good to clarify what the preconditions are on the project code. Ideally, it should be possible to run the tutorial directly on a site created using `gatsby new`

**Comment by mujeex** [comment]
> I tried to follow the Algolia tutorial based on a new project created using `gatsby new`. That fails because the tutorial assumes that `gatsby-transformer-remark` is installed and that there are markdown files containing certain fields in the frontmatter.
> 
> It would be good to clarify what the preconditions are on the project code. Ideally, it should be possible to run the tutorial directly on a site created using `gatsby new`

Thank you for voicing that out Andreas, let me add that to the completeness. I hope it worked for you after you installed the right plugin and added the appropriate fields in the frontmatter of your files.

**Comment by ehrencrona** [comment]
The reason I followed the tutorial was I wanted to improve the documentation to address the issues mentioned in this ticket. Since so many different technologies come together in the tutorial it's quite challenging to present it in a clear way, but I hope to be able to suggest a few improvements. I hope make a PR today or tomorrow.

**Comment by mujeex** [comment]
> The reason I followed the tutorial was I wanted to improve the documentation to address the issues mentioned in this ticket. Since so many different technologies come together in the tutorial it's quite challenging to present it in a clear way, but I hope to be able to suggest a few improvements. I hope make a PR today or tomorrow.

I totally understand your pain Andreas, and thank you so very much for taking the time to improve our beloved gatsby. Can't wait to see you PR. :)

**Comment by w3bdesign** [comment]
Not entirely relevant, but seeing as I have recently worked with Algolia and implemented it in a React project, I recommend that you take a look at a project where I have implemented this with NextJS: 

https://github.com/w3bdesign/nextjs-woocommerce

**Comment by han-so1omon** [comment]
Should this be closed following the PR submitted by @ehrencrona ?

**Comment by ehrencrona** [comment]
In my opinon: yes.

**Comment by han-so1omon** [comment]
@ehrencrona could you please detail which of the recommendations from @mujeex you have covered?

**Comment by ehrencrona** [comment]
I reviewed them again. As far as I can tell all the points under "recommendations" are covered by the changes.

**Comment by marcysutton** [comment]
I think we can close this one, thanks @ehrencrona for your PR!! It was a great addition.
