### ISSUE TITLE
blog:strapi instant content preview: Images should be inlined in repo and not hosted on githubusercontent.com

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#24646]
## Description

4 images linked external and hosted on githubusercontent.com

### Steps to reproduce

open https://www.gatsbyjs.org/blog/2020-05-12-strapi-instant-content-preview-plugin/

inspect images or right click on and image and select open in new tab 

or look https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2020-05-12-strapi-instant-content-preview-plugin/index.md#L59

### Expected result

- images should placed in the blog directory
- images can be optimized by sharp / GatsbyImage
- independent from external image hosting

### Actual result

- hosted on githubusercontent.com
- not optimized by sharp / Gatsby Image

## Related Issues

- #23986 `add strapi case study and author avatar and bio`

**Comment by LekoArts** [comment]
Thanks for the issue but we don't see this as a problem that needs to be solved.
