### ISSUE TITLE
My plugin is not being opened correctly

### ISSUE THREAD

**Issue by nishantwrp** [gatsbyjs/gatsby#24647]
## Description

I have made a plugin for gatsby name `gatsby-source-hashnode-devblog` and it is listed in the plugins page but clicking on it gives a error. (https://www.gatsbyjs.org/packages/gatsby-source-hashnode-devblog/)

**Comment by LekoArts** [comment]
Hi!
The site needs to rebuild first. Give it a bit of time and your plugin will show :)
