### ISSUE TITLE
Gatsby develop on https

### ISSUE THREAD

**Issue by brsanthu** [gatsbyjs/gatsby#2464]
We are testing stripe integration on a site generated by gatsby. Because `gatsby develop` starts on http site, we cannot test stripe integration.

How can we configure gatsby develop to run on https mode? I see that webpack devserver has `--https` options but when I specified that in `gatsby develop` it errors out.

**Comment by szimek** [comment]
While it's just a workaround, you could use something like [ngrok](https://ngrok.com/docs) to access gatsby server via https.

**Comment by brsanthu** [comment]
Thank you @szimek. I think it will be a nice workaround. However, I think still gatsby should support passing `--https` option to Wepback Dev server.

**Comment by KyleAMathews** [comment]
Happy to add support for using https w/ the develop server. FYI, we don't serve things directly from webpack-dev-server.

**Comment by brsanthu** [comment]
Thank you @KyleAMathews for going to add this and also clarifying webpack-dev-server is not used internally.

**Comment by KyleAMathews** [comment]
Oh, I should have proofed my comment better — I meant I'm happy to support *someone else* adding a PR to add support for this :-)

I don't have any current need for this so won't be doing it.

**Comment by brsanthu** [comment]
Can you please give some hints on how to approach adding https support?

**Comment by KyleAMathews** [comment]
All the develop server code is in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/develop.js

I'm not really sure what the best way to get https running automatically locally so you'll need to research that.

BTW, I also googled "stripe localhost" and it seems you don't need https when testing locally FWIW.

**Comment by KyleAMathews** [comment]
gatsby develop has https now!
