### ISSUE TITLE
Gatsby 2.22.13 pulls in incompatible dependencies

### ISSUE THREAD

**Issue by andrewaylett** [gatsbyjs/gatsby#24653]
#  Description

Describe the issue that you're seeing.

A minimal `package.json` containing just a dependency on `gatsby@2.22.13` has a broken dependency tree:

```
andrewaylett@ANDRAYLE01M:~/tmp/gatsby$ npm ls gatsby
gtest@1.0.0 /Users/andrewaylett/tmp/gatsby
└─┬ UNMET PEER DEPENDENCY gatsby@2.22.13
  └─┬ gatsby-admin@0.1.54
    └── UNMET PEER DEPENDENCY gatsby@2.22.13  deduped

npm ERR! peer dep missing: gatsby@2.6.0, required by gatsby-interface@0.0.163
```

### Steps to reproduce

Example repo here: https://github.com/andrewaylett/gatsby-bug-report

* `npm ci`
* `npm ls gatsby`

### Expected:

A consistent dependency tree

### Actual:

gatsby@2.22.13 -> gatsby-admin@^0.1.54 -> gatsby-interface@0.0.163 -> gatsby@2.6.0

Note the gatsby-admin dependency is a caret dependency, while the others are specific version dependencies.

This appears to be a result of #23734 (and #24451).

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Languages:
    Python: 3.7.3 - /Users/andrewaylett/.pyenv/shims/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 77.0
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.22.13 => 2.22.13

**Comment by mxstbr** [comment]
Thank you for the report!

PR to unpin the gatsby peer dependency over in gatsby-interface is open: https://github.com/gatsby-inc/gatsby-interface/pull/337
