### ISSUE TITLE
Why does Gatsby start a second server at localhost:4000? 

### ISSUE THREAD

**Issue by bytheway875** [gatsbyjs/gatsby#24656]
When I create a new gatsby app and run `gatsby develop,` it starts a server at localhost:8000 and then a second one on localhost:4000, where I'm able to query things like "allGatsbyPlugin":

![Screen Shot 2020-05-30 at 2 40 45 PM](https://user-images.githubusercontent.com/4494389/83339533-bc318980-a283-11ea-9a00-411fb6423522.png)

I can't find documentation on gatsby starting things on ports other than localhost:8000. What is this, why is it here (I discovered it because it's interfering with something else I run on port 4000), and can I change the port it runs on?

**Comment by varughese** [comment]
How are creating your new gatsby app? According to this tutorial - https://github.com/gatsbyjs/gatsby/blob/master/docs/tutorial/source-plugin-tutorial.md - it seems like running gatsby develop starts a server up on localhost:4000. Was your gatsby project started from a plugin example by accident? Hope that is helpful!

**Comment by bytheway875** [comment]
@varughese Thanks! So, It's was just the regular gatsby new, so not created from a plugin example. It does seem like gatsby-recipes starts a server at localhost:4000:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-recipes/src/graphql-server/server.js

https://github.com/gatsbyjs/gatsby/blob/abedd3c3ac32515f98bc59993a93af95d0d5cc26/packages/gatsby-cli/src/recipes.ts

Then, checking out the code for `gatsby develop` command in the CLI, looks like its importing startGraphQLServer from gatsby-recipes and starting up the recipe server at 4000...

https://github.com/gatsbyjs/gatsby/blob/abedd3c3ac32515f98bc59993a93af95d0d5cc26/packages/gatsby-cli/src/create-cli.ts


I guess I get it, but it's kind of a bummer because I'm dealing with trying to fix this error:
https://github.com/gatsbyjs/gatsby/issues/23214, which requires upgrading our gatsby version. But upgrading starts this server at localhost:4000 and I'm running another graphql server on localhost 4000. Even though it looks like the code to start up the recipes server takes an argument to start that server on a different port, I can't tell how to pass that in as an option to the CLI. I'd really prefer not to have to change the infrastructure of where my GraphQL server is served from just to accomodate this recipes server that I have no interest in using...

But anyways, if you see how I can change the recipes server location that will help me work around it at least. 

Thanks!

**Comment by Pyrax** [comment]
This was only recently introduced. Afaik there's no option to change the port or disable that extra server, yet.

However, maybe one of these workarounds help you for the time being:
1. Search for the process ending on "graphql-server/server.js" and terminate it.
2. Or: If your service which uses port 4000 starts before `gatsby develop` and keeps the port blocked, the recipe server uses the next free port instead of 4000.

**Comment by KyleAMathews** [comment]
Yeah — 4000 wasn't a good choice for the default recipes port as it's used a lot for apps. Opened https://github.com/gatsbyjs/gatsby/pull/24665 to move it to 50400 which is a cool number as it's a highly composite number! https://en.wikipedia.org/wiki/50,000

**Comment by bytheway875** [comment]
@KyleAMathews Thank you!
