### ISSUE TITLE
How do I know if a sitemap is created?

### ISSUE THREAD

**Issue by arhoy** [gatsbyjs/gatsby#24676]
Hello I am using the gatsby plugin sitemap, But I have a few questions

1) How to check if my site map is properly created?

I follow the steps in the instructions.

2) Is the site map always updating if I add more pages?

Thanks you very much

**Comment by hendra-go** [comment]
Have you ever try to build your project ?

From the [gatsby-plugin-sitemap documentation](https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/?=gatsby-plugin-sitemap):

> NOTE: This plugin only generates output when run in production mode! To test your sitemap, run: gatsby build && gatsby serve

The sitemap should be in public folder, usually sitemap.xml (if you not change the output file name in gatsby-config)

**Comment by herecydev** [comment]
> Is the site map always updating if I add more pages?

Yes all pages that are added either statically or programmatically are added to the sitemap, again by default. This can be changed if you wish

**Comment by arhoy** [comment]
Yes I have.  Do you have example XML?

**Comment by arhoy** [comment]
Ok thankyou. Some of pages are not showing up in google search console
though. Once that are nested like /website/project

Does it take Google longer to crawl?

**Comment by herecydev** [comment]
> Some of pages are not showing up in google search console
though. Once that are nested like /website/project

Are those pages appearing in your sitemap?

**Comment by arhoy** [comment]
@herecydev I don't understand I thought the sitemap is auto generated?

**Comment by arhoy** [comment]
I have  `gatsby-plugin-sitemap` installed and in my config file
That is all I did

**Comment by herecydev** [comment]
The sitemap is auto generated, as Hendra pointed out:

>The sitemap should be in public folder, usually sitemap.xml

**Comment by arhoy** [comment]
I dont see it there. If I push to production willl it generate?
For example I don't see a sitemap on Google Console But if I type in site:myurl some of my pages show.

Further I was not able to run gatsby build as it threw an error

"gatsby-source-buttercms" threw an error while running the sourceNodes lifecycle:

**Comment by arhoy** [comment]
I almost never run gatsby build or gatsby serve and it is throwing lots of errors and issues.
I simply deploy to netlify and there is no issue at all. I am not sure how I can get my sitemap.

**Comment by LekoArts** [comment]
Thank you for opening this!

> How to check if my site map is properly created?

After running a `gatsby build` you'll find the sitemap inside your `public` folder.

> Is the site map always updating if I add more pages?

If you left the GraphQL query on the standard setting your sitemap will udpate after you re-build your site.

The rest of your questions were already correctly answered by Dan and Hendra :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by arhoy** [comment]
I just want to say that if you are using Netlify, running gatsby build is not necessary. You can checkout the sitemap by going to 
yourURL.com/sitemap.xml

Take that and plug into the Google Search Console.
- QED
