### ISSUE TITLE
isUseStaticQuery Fails to Detect Static Query Usage on CommonJS Module

### ISSUE THREAD

**Issue by gchallen** [gatsbyjs/gatsby#24677]
## Description

I'm developing a Gatsby theme in TypeScript, which I'm transpiling to a CommonJS module before publishing. One of its components uses the `useStaticQuery` hook. However, this usage is not detected properly when the theme is added to another Gatsby site, leading to "Error: The result of this StaticQuery could not be fetched."

I've traced this down to this bit of `file-parser.js`:

```js
function isUseStaticQuery(path, file) {
  return path.node.callee.type === `MemberExpression` && path.node.callee.property.name === `useStaticQuery` && path.get(`callee`).get(`object`).referencesImport(`gatsby`) || path.node.callee.name === `useStaticQuery` && path.get(`callee`).referencesImport(`gatsby`);
}
```

Breaking the conditional as follows causes the check to work properly, so it's a problem with the second bit:

```js
function isUseStaticQuery(path, file) {
  // My file ends with Single.js, so this was a quick hack to isolate my code
  if (file.endsWith("Single.js") && path.node.callee.type === "MemberExpression" && path.node.callee.property.name === "useStaticQuery") {
    return true;
  }
  return path.node.callee.type === `MemberExpression` && path.node.callee.property.name === `useStaticQuery` && path.get(`callee`).get(`object`).referencesImport(`gatsby`) || path.node.callee.name === `useStaticQuery` && path.get(`callee`).referencesImport(`gatsby`);
}
```

Here is the bit of my transpiled code that should trigger this check:

```js
exports.Single = ({ children }) => {
    const data = gatsby_1.useStaticQuery(gatsby_2.graphql `
    query Single {
      site {
        siteMetadata {
          title
        }
      }
      file(relativePath: { eq: "logo.png" }, sourceInstanceName: { eq: "images" }) {
        childImageSharp {
          fixed(width: 48, height: 48) {
            base64
            width
            height
            src
            srcSet
          }
        }
      }
    }
  `);
```

Note that if I manually trigger the static component context wrapper by adding a dummy static query in the main repository, everything works as expected. So the problem here is the static query usage detection. (Note that my package does have `gatsby` in the name, as required.)

As an aside, I'm not sure exactly what this search process is trying to accomplish. Are the actual static queries being extracted and run for some reason, or is this just to determine that a static query is being used so that the correct context provider can be added? If it's the latter—maybe not, but the fact that a dummy query then causes my theme to work is suspicious—wouldn't it be simpler to just let packages mark that they use static queries somehow, maybe under a `gatsby` key in `package.json` and avoid this search which seems at least somewhat brittle? Just a thought.

Alternatively, is there a way to add the appropriate static query context provider manually?

### Steps to reproduce

Clone [this repository](https://github.com/cs125-illinois/gatsby-isstaticquery-bug-report) and `npm start`.

### Expected result

Gatsby should detect that my theme uses a static query and the site should compile and run.

### Actual result

"Error: The result of this StaticQuery could not be fetched."

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 5.0.17 - /opt/local/bin/bash
  Binaries:
    Node: 12.16.1 - ~/.asdf/installs/nodejs/12.16.1/bin/node
    npm: 6.13.4 - ~/.asdf/installs/nodejs/12.16.1/bin/npm
  Languages:
    Python: 3.8.2 - /Users/challen/.asdf/shims/python
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15
  npmGlobalPackages:
    gatsby-cli: 2.12.21

**Comment by madalynrose** [comment]
Hi there @gchallen! I tried to reproduce with the steps you listed and ended up with an error saying `const react_google_login_1 = require("@cs125/react-google-login");` was undefined. Is there a step I'm missing in running your project?

**Comment by gchallen** [comment]
Ah, sorry. I forgot to check in a `.env.development` file that defines some constants that we check for at runtime. Fixed and pushed.

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v4 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

Moreover, you don't need to compile a Gatsby Theme. Gatsby already compiles relevant packages in `node_modules` under the hood itself so it'll understand the theme in TypeScript.

[reproduction]: https://gatsby.dev/reproduction
