### ISSUE TITLE
gatsby set host option (-H) not working since release 2.22.0

### ISSUE THREAD

**Issue by vipinagg** [gatsbyjs/gatsby#24678]
$ gatsby develop -H <your_ip>

returns no data

This is a regression since 2.22.0. It works fine until 2.21.40.
To reproduce, just take any gatsby starter and run it.

**Comment by LekoArts** [comment]
A `gatsby develop -H 0.0.0.0` works but now specifying an internal IP.

**Comment by sidharthachatterjee** [comment]
This was since fixed in https://github.com/gatsbyjs/gatsby/pull/24761

Upgrade `gatsby` and it should work again. Thanks for reporting! 🙌
