### ISSUE TITLE
useStaticQuery for non-page components not working with typescript plugin

### ISSUE THREAD

**Issue by dragGH102** [gatsbyjs/gatsby#24673]
## Description

When using 

```
 export const query = graphql`
  query LayoutQuery {
    site {
      siteMetadata {
        title
      }
    }
  }
```
**gabtsy-config.js**
```

module.exports = {
  siteMetadata: {
    title: 'my-site'
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
     // Add typescript stack into webpack
    `gatsby-plugin-typescript`
  ],
}
```
in page-component it works as expected.
However when using `useStaticQuery` in a non-page component (e.g. higher order component for layout) as

```
export const query = useStaticQuery(
  graphql`
      query LayoutQuery {
        site {
          siteMetadata {
            title
          }
        }
      }
    `
)
```

it throws 

> This dependency was not found:
> * gatsby in ./src/components/layout.tsx
> To install it, you can run: npm install --save gatsby

Obviously, `gatsby` is installed

Note: my IDE shows suggests to install the typings `@types/gatsby` but these do not exist apparently ( **404 from npm** ) 

```
export const query = useStaticQuery(
  graphql`
      query LayoutQuery {
        site {
          siteMetadata {
            title
          }
        }
      }
    `
)
```

I am also not sure why `export` is needed for the query since the query itself is used within the component file (that's how the documentation shows it)

## Reproduction

This is the project I am working on and it's pretty much as simple as it can be except couple of extra pages

https://github.com/dragGH102/webcv/commit/786eb88f44d2f980a1e4cddfc91e9c5f0105dc1e

(please use that commit as I will keep working on the same repo with more commits on top)

Possibly related: also when using 'gatsby-plugin-mdx' there seem to an issue with resolving dependencies:

```
See https://www.gatsbyjs.org/docs/browser-apis/ for the list of Gatsby Browser APIs
 — The plugin "gatsby-plugin-mdx@1.2.13" is exporting a variable named "wrapRootElement" which isn't an API. Perhaps you meant to export "wrapRootComponent"?

Your plugins must export known APIs from their gatsby-ssr.js.
The following exports aren't APIs. Perhaps you made a typo or
your plugin is outdated?

See https://www.gatsbyjs.org/docs/ssr-apis/ for the list of Gatsby SSR APIs
 — The plugin "gatsby-plugin-mdx@1.2.13" is exporting a variable named "wrapRootElement" which isn't an API.
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success copy gatsby files — 0.093 s
⠂ onPreBootstrap/usr/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'gatsby/graphql'
```

Commit: https://github.com/dragGH102/webcv/commit/3e1d610bb7b6a561ba83bd9e8052f1fbb0e7d3da

### Environment

  System:
    OS: Linux 4.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.20.1 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^1.9.279 => 1.9.279
    gatsby-link: ^1.6.28 => 1.6.46
    gatsby-plugin-react-helmet: ^1.0.8 => 1.0.8
    gatsby-plugin-typescript: ^1.4.10 => 1.4.20
  npmGlobalPackages:
    gatsby-cli: 2.12.36

**Comment by LekoArts** [comment]
Thank you for opening this!

I cloned your repository and found the culprits. TS and useStaticQuery work fine together.

You were using severely outdated dependencies that are incompatible with current versions. `useStaticQuery` isn't accessible in Gatsby v1, you'll need to update to the latest version. Also with the latest version the typescript plugin is added by default, so no need to install and use it.

![image](https://user-images.githubusercontent.com/16143594/83490561-87564a00-a4b0-11ea-9c39-38f2e5c63d8f.png)

So please update all your versions and it'll work!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
