### ISSUE TITLE
How to create a POST API endpoint in a gatsby site.

### ISSUE THREAD

**Issue by AparnaJoshi007** [gatsbyjs/gatsby#24671]
## Summary
Adding a POST API endpoint with gatsby site
## Relevant information
I have a contact form that takes in user input. This input must be posted to an endpoint belonging to a different domain. Due to the cors issue, I cannot make a direct API call to the endpoint from the browser. I need to reroute it through a server. I checked many source plugins, but they have only given documentation on `GET` calls. 
I needed some help with the following:
1. Is it possible to add a custom POST endpoint in gatsby site? The frontend would make a POST call providing data such as `email` address to this endpoint.
2. If there is any plugin/readme to do the same, can I get a link to them?

Thanks in advance

**Comment by herecydev** [comment]
Gatsby generates files and that's it, it's designed with the lowest common denominator (which is no server at all, i.e. CDNs etc). You'll have to create some backend that you control and proxy the requests that way.

https://www.gatsbyjs.org/blog/2018-12-17-turning-the-static-dynamic/ is a good blog about using netlify functions that might help

**Comment by universse** [comment]
What hosting solution are you using?

**Comment by LekoArts** [comment]
Thank you for opening this!

As Dan said Gatsby is not a tool with which you could create a "POST API endpoint". You can make API calls as usual in any React application but for the endpoint itself you'll need to create that outside of Gatsby. Please refer to the communities below to ask for non-Gatsby questions.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
