### ISSUE TITLE
Adding meta elements to user generated pages i.e for dynamic urls. Please help, it's very urgent.

### ISSUE THREAD

**Issue by ankit-gupta1307** [gatsbyjs/gatsby#24680]
I have a website https://www.loved.com and there pages https://www.loved.com/hh . "hh"  is varaible and it can be anything, I want to add meta data for thes pages depending ton the api call. I am researching about this from the past 2 days but I am unable to get he the answer. Is there any way from gatsby-node.js or gatsby-ssr.js file to add meta data in these pages like we could normally do with server side rendering.

**Comment by herecydev** [comment]
There's a whole page dedicated to this: https://www.gatsbyjs.org/docs/add-page-metadata/

**Comment by ankit-gupta1307** [comment]
@herecydev Did you even read properly what's the issue I am facing, I have already gone through those pages but that doesn't solve my purpose.

I want to do the server side rendering of dynamic urls(i.e urls will be user generated). I want to add meta elements to those pages. So that when I share that url, I will get the data.

**Comment by LekoArts** [comment]
Thank you for opening this!

Gatsby only renders the HTML/CSS/JS at build time. If you're creating client-only pages you won't have the benefit of that static pre-rendering. Gatsby doesn't support the "server side rendering of dynamic urls" unless you build them at build time. So I guess what you're asking for is not possible.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by ankit-gupta1307** [comment]
@LekoArts Gatsby didn't mention it anywhere in their website that it's not possible. Thanks for getting back, appreciate it.

Please refer to this link: 

[https://www.gatsbyjs.org/features/jamstack/gatsby-vs-nextjs]

Atleast when doing comparision be fair to the users, gatsby could have mentioned their that Server side rendering is possible for NextJs but not gatsby. This is undone.
