### ISSUE TITLE
Replace Typefaces with Fontsource

### ISSUE THREAD

**Issue by DecliningLotus** [gatsbyjs/gatsby#24692]
## Summary

In reference to #24385 which contains all the details regarding this issue, what additional discussion should precede for this documentation update?

What are everyone's thoughts towards the change and what concerns would anyone hold to the PR?

### Motivation

I personally loved the idea of using [Typefaces](https://github.com/KyleAMathews/typefaces) for my projects, however, it lacks many of newer Google Fonts and existing ones have been outdated. That is evident from the number of issues and PRs. I would've loved to contribute, but it's been clear that the project isn't maintained anymore so I decided to rebuild the whole project.

[Fontsource](https://github.com/DecliningLotus/fontsource) aims to replace the project by setting up an automatic update schedule to keep Google Fonts up to date, adds the much-needed options to choose subsets, weights and styles for greater performance capability/language support and embrace newer alternative Open Source fonts. With far clearer documentation to boot, I would say this is a very viable improvement to the Gatsby ecosystem from a performance and QOL perspective for typography.

### Documentation 

The section considered to be adjusted can be found here: https://www.gatsbyjs.org/docs/recipes/styling-css/#using-google-fonts

**Comment by herecydev** [comment]
My biggest concern with a change like this is the very problem of maintenance that you've pointed out isn't addressed. If you stop supporting Fontsource in a few months, what happens then?

I do think it's problematic if Typefaces is going a bit stale, but I think that needs to be addressed with better automation and potentially opening up the core mainteners if the burden of managing it is becoming a problem. I just don't see endless rewrites as a better methodology

**Comment by Neilblaze** [comment]
@DecliningLotus  please review PR #24726

**Comment by DecliningLotus** [comment]
@herecydev, I actually agree with the opening up to more core maintainers part for Typefaces. 

We may actually see that being addressed soon in one form or the other since it isn’t ideal to migrate an entire community over to another repo which follows the same project vision, however, I’m not too concrete on the details regarding that since not much has been discussed. 

I’m not going to be pushing this issue too much until I get clarity on that other venture.

@Neilblaze I would recommend closing that since it is a duplicate PR of #24385.

**Comment by marcysutton** [comment]
Hey there, thanks for the issue and discussion. I agree that it would be good to recommend something for working with Google fonts that's been kept up to date more. We're going to chat about our options internally, and we'll update you when we know more.

**Comment by DecliningLotus** [comment]
Just leaving a note that I’m open to integrate Fontsource into the Typefaces project as an active maintainer. It would be great to go through all those issues and clean up the maintenance backlog.

I’ve got tons planned including preload support, a search directory and more - I’ve left that on hiatus for the time being until we sort this out.

**Comment by jsejcksn** [comment]
Maintainers: Are you open to reconsidering the remote resource strategy entirely? I don't know that the current implementation of maintaining proxied caches are sustainable strategies.

Fonts are a specific type of resource that I'll focus on here, with Google Fonts as the example, but this idea can be extrapolated to other font sources and other types of resources.

I'll share two strategy ideas:

---

Let's say you want to load a few variants of Roboto:

```
https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400;1,700&display=swap
```

[The workbox documentation explains:](https://developers.google.com/web/tools/workbox/guides/common-recipes#google_fonts)

> The Google Fonts service consists of two parts:
>
>   - The stylesheet with the @font-face definitions, which link to the font files.
>   - The static, revisioned font files.

## Strategy 1: Using service workers with original sources

When using a service worker (e.g. [`gatsby-plugin-offline`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-offline)), a technique like SWR works great: cache the resources from their actual locations, serve cached, and re-fetch if necessary.

Unless the user's connection to your site's CDN is faster than Google Fonts, caching from Google Fonts will be advantageous. Plus, if the user has visited another website which uses any of the same fonts, they will already be in cache and _instantly_ available on first load.

The fonts have a cache-control policy of a year (`cache-control: public, max-age=31536000`) and the stylesheets have a policy of 24 hours (`cache-control: private, max-age=86400, stale-while-revalidate=604800`).

## Strategy 2: Fetch the remote resources at build time (e.g. via a plugin)

Essentially, this is the `Typefaces`/`Fontsource` package as a plugin: Create a plugin for web fonts, allowing the user to provide a link to one or more stylesheets.

1. Download the stylesheet
2. Parse the font resource addresses from the stylesheet
3. Download the font resources
4. Re-write the addresses in the stylesheet to point to the local font resources
5. Bundle with app during build

I think this strategy is more sustainable than the npm cache strategies, but it loses all the shared cache benefits provided in strategy 1.

---

These are initial thoughts. Apologies if I overlooked something. Please provide feedback!

**Comment by DecliningLotus** [comment]
I apologise if I get anything incorrect with what I say below. Feel free to correct me if I'm wrong.

---

> ## **Strategy 1: Using service workers with original sources**
I feel that this solution excludes those who do not wish to use `gatsby-plugin-offline` or service workers in their project.

> Plus, if the user has visited another website which uses any of the same fonts, they will already be in cache and instantly available on first load.

At least to my understanding, that benefit does not exist due to double-keyed caching implemented in most modern browsers such as Chromium and Safari. More on this [here](https://www.chromestatus.com/feature/5280299309072384).

In which case, a locally hosted font pretty much achieves the same benefits of browser caching in the end compared to a service worker?

---

> ##  **Strategy 2: Fetch the remote resources at build time (e.g. via a plugin)**

> I think this strategy is more sustainable than the npm cache strategies

@jsejcksn, I'm a little unsure of what you mean by "sustainable" in this context.

As a separate repository, [Fontsource](https://github.com/fontsource/fontsource) is framework agnostic, meaning it works with most React frameworks - Gatsby, CRA and Next.js being key tested figures. The libraries also works with Vue and I haven't necessarily checked with Angular, but it probably may work there too. I don't think it's a good move to lock and restrict this project onto Gatsby solely by developing it into a plugin.

Not to mention for both strategies you do lose one of the key benefits of Fontsource - version control. Google pushes updates to their fonts without notice and some changes can cause mass outrage such as [google/fonts#1307](https://github.com/google/fonts/issues/1307). Treat your fonts like any other NPM dependency and update them at your own pace.

**Comment by jsejcksn** [comment]
> I'm a little unsure of what you mean by "sustainable" in this context.

@DecliningLotus _Sustainable_ as in "requiring ongoing human maintenance and infrastructure"

I'm not trying to step on your toes. If you want to maintain a versioned font repository for general use, I think that's great for the community.

As I mentioned at the top of my message:

> Fonts are a specific type of resource that I'll focus on here, with Google Fonts as the example, but **this idea can be extrapolated** to other font sources and other types of resources.

I was just using fonts as an example. The suggestion was about allowing users to download and bundle all kinds of remote resources (including resources not related to fonts) at build time. Think of it as a suggestion for a "remote resource caching plugin" (or plugins, depending on implementation).

**Comment by DecliningLotus** [comment]
@jsejcksn, my bad. Appreciate the response. 

It's an interesting direction to take things, at least in the general scope. You should definitely make a separate issue to get dedicated feedback from the general perspective.

**Comment by meganesu** [comment]
Hi @DecliningLotus, thanks for your patience while we talked about this internally. At this time, our hope is to get Typefaces back up to date by opening it up to community contributors. We're still nailing down the details for how to do that.

In the meantime, I'm going to close this issue, since we aren't planning on moving the docs away from Typefaces. Thanks for bringing this to our attention! 💜

**Comment by jarodtaylor** [comment]
@meganesu does the Gatsby team plan to update the Typefaces repo/Readme? It currently still says deprecated and points users to use Fontsource.

**Comment by KyleAMathews** [comment]
Yes there's another PR up https://github.com/gatsbyjs/gatsby/pull/27313
