### ISSUE TITLE
Continue to show re-build failures in browser after a browser refresh

### ISSUE THREAD

**Issue by bilogic** [gatsbyjs/gatsby#24695]
## Summary
Rebuild failures only show up in the terminal, show them in HTTP as well.
 
### Motivation
Rebuild failures do not show up in HTTP, furthermore, the HTTP still loads the previous version, i.e. a working version or one that has JavaScript errors, leading to unexplained levels of confusion.

The terminal is also often hidden to maximize screen real estate. It gets frustrating when despite multiple trial and error, the page still does not change or JavaScript errors still do not go away.

HTTP does not have to show the full errors, it could be as simple as "There was a re-build failure at *timestamp*", this timestamp is an important indicator keep the programmer more aware about whether the browser page he is staring at is fresh or stale.

Thank you.

**Comment by bilogic** [comment]
Sorry, after I wrote this, my browser started to show ```Failed to compile errors```, it seems my browser does not refresh to show it at times. I will monitor and file a report if I can reproduce it reliably. Thank you.

**Comment by bilogic** [comment]
Hi,

I managed to reproduce the issue.

1. When I save and there is a re-build error, browser auto refreshes and shows the error
2. If I go to the browser and hit refresh, the last successful re-build page shows up, this can either be a proper page or a page with Javascript errors, basically the page from the last successful re-build

Can gatsby continue to show the re-build error instead of the last successful re-build page?

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by bilogic** [comment]
> I managed to reproduce the issue.
> 
> 1. When I save and there is a re-build error, browser auto refreshes and shows the error
> 2. If I go to the browser and hit refresh, the last successful re-build page shows up, this can either be the HTML page I'm developing or a page with Javascript errors, basically the page from the last successful re-build
> 
> Can gatsby continue to show the re-build error instead of the last successful re-build page?

I believe the above was already minimal enough, well.. in even more minute detail, here goes:

Minimal reproduction steps:

1. Create a new gatsby hello-world ```gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world```
2. Run ```gatsby develop```
3. Load ```http://localhost:8000``` in a browser, a ```Hello world!``` should show
4. Edit ```./src/pages/index.js``` and overwrite it with the following and save, this will cause the re-build to fail
```
import React from "react"

export default function Home() {
 asdf=1
 return <div>Hello world!</div>
}
```
5. Go back to the browser and press refresh, why does ```Hello world!``` still show?
