### ISSUE TITLE
gatsby image: custom rootMargin

### ISSUE THREAD

**Issue by pindjur** [gatsbyjs/gatsby#24712]
Currently Intersection observer's root margin is hard coded to 200px. [gatsby-image/src/index.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js)
It means that image will start loading when the distance from viewport to image  is  200px, however  in some cases we want to load image much before 200px gap (for example if we know from statistics that most users will scroll to that image). Also I don't think  pixels are right solution for this, according to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) margin can be percentage.

> **rootMargin**
Margin around the root. Can have values similar to the CSS margin property, e.g. "10px 20px 30px 40px" (top, right, bottom, left). The values can be percentages. This set of values serves to grow or shrink each side of the root element's bounding box before computing intersections. Defaults to all zeros.

Unlike in css where the size of the margin(horizontal and vertical also) as a percentage is  relative to the **width** of the containing block, in observer vertical margin is relative to root intersection rectangle height (in our case viewport height),see  [W3C spec](https://w3c.github.io/IntersectionObserver/). You can test this by logging entry.rootBounds. 

Browsers default scrolling is from **left** to **right** and from **top** to **bottom**  so I think that default rootMargin can be something like this "0px 30% 30% 0px" (top | right | bottom | left) but for people who implements horizontal scrolling with both sides  "0px 30% 30% 30%" or for backwards compatability best is around "30%" all.
Anyway, can someone add rootMargin prop ? im new to github.

**Comment by LekoArts** [comment]
Thank you for opening this!

In the past we've closed requests for this, see my colleagues comment:
https://github.com/gatsbyjs/gatsby/pull/16004#issuecomment-514181464

We haven't changed our mind on this but if you can provide some research that a value other than 200px would be feasible as a default, please let us know!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
