### ISSUE TITLE
[gatsby-source-wordpress] ACF data cannot be queried if first post has no fields

### ISSUE THREAD

**Issue by chrisgeary92** [gatsbyjs/gatsby#2471]
If the first post Gatsby queries (for a given post type) does not have ACF data assigned to it (if you have conditional fields, or you install ACF on an existing site), then GraphQL treats every post of that post type as if it has no ACF data (even though they can do). Presumably because it returns `false` instead of `{}`

This is what the WP API gives you back when you have no data:
```json
{
    "acf": false,
}
```

This is what the WP API gives you when you do have data:
```json
{
    "acf": {
        "project_url": "https://..."
    }
}
```

I spoke to Kyle and his thoughts were:

> ok, this fix is easy then, `gatsby-source-wordpress` should just strip away the `acf: false` since that's useless to us

But I cannot figure out what I have to change to make this happen unfortunately.

* * *

Using:
 - `gatsby`: `^1.9.36`
 - `gatsby-source-wordpress`: `^2.0.12`

Probably related to: #2417 and #2394

**Comment by KyleAMathews** [comment]
Add a new function here: https://github.com/gatsbyjs/gatsby/blob/eb4d12705600acc42007d0b8c53b7b37c9205852/packages/gatsby-source-wordpress/src/gatsby-node.js#L52

As you can see, there's already a long list of things we do to normalize the data coming from WordPress.
