### ISSUE TITLE
5 usability tests for a Gatsby recipe in the browser

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#24724]
## Goal

We want to make sure the following is true:
- users can input information into the recipe
- users can install the recipe
- users can know if the recipe installed successfully or not
- users can view the resources installed

## How to reach that goal

I'll setup at least 5 usability tests with Gatsby users so we can see if the statements above are true or not!

## Blocked by
Not sure the most effective way to test this; @kyleamathews and @johno at some point soon will people be able to clone your PR and run it in their own browser?

**Comment by KyleAMathews** [comment]
We should have a tagged release we can use for testing.

So we could create a special starter for testing with it + the user would run our new version of recipes like `npx gatsby@recipes-input`
