### ISSUE TITLE
gatsby-remark-autolink-headers doesn't properly slugify headings with html nodes

### ISSUE THREAD

**Issue by vihanb** [gatsbyjs/gatsby#24738]
## Description
The slugs produced by gatsby-remark-autolink-headers don't ignore HTML tags. The URL in the `tableOfContents` field does, however, handle them correctly. This mismatch causes issues as those URLs

### Steps to reproduce

My MDX has a heading that's something like:

```markdown
## `Symbol.iterator`
```

The generated HTML from this markdown (initially) is something like:

```html
<h2><code class="language-text">Symbol.iterator</code></h2>
```

### Expected result

The heading should appear somewhat like:

```html
<h2 id="symboliterator">
    <a href="#symboliterator">
        ...
    </a>
<h2>
```

### Actual result
The `<code>` tags in the heading confuse the slugify function and it interprets those as part of the heading text

```html
<h2 id="code-classlanguage-textsymboliteratorcode">
    <a href="#code-classlanguage-textsymboliteratorcode">
        ...
    </a>
<h2>
```

The url on the object returned by `tableOfContents` is the correct `#symboliterator`

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.0.0 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    gatsby: ^2.19.45 => 2.22.12
    gatsby-image: ^2.2.44 => 2.4.5
    gatsby-plugin-google-analytics: ^2.1.38 => 2.3.2
    gatsby-plugin-lodash: ^3.3.3 => 3.3.3
    gatsby-plugin-manifest: ^2.2.48 => 2.4.9
    gatsby-plugin-mdx: ^1.2.13 => 1.2.13
    gatsby-plugin-netlify: ^2.3.3 => 2.3.3
    gatsby-plugin-offline: ^3.0.41 => 3.2.7
    gatsby-plugin-react-helmet: ^3.1.24 => 3.3.2
    gatsby-plugin-sass: ^2.1.31 => 2.3.2
    gatsby-plugin-sharp: ^2.4.13 => 2.6.9
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2
    gatsby-plugin-transition-link: ^1.18.0 => 1.18.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-autolink-headers: ^2.3.3 => 2.3.3
    gatsby-remark-copy-linked-files: ^2.3.3 => 2.3.3
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: ^3.3.8 => 3.3.8
    gatsby-remark-katex: ^3.3.2 => 3.3.2
    gatsby-remark-prismjs: ^3.5.2 => 3.5.2
    gatsby-remark-responsive-iframe: ^2.4.3 => 2.4.3
    gatsby-remark-smartypants: ^2.3.2 => 2.3.2
    gatsby-source-filesystem: ^2.1.56 => 2.3.8
    gatsby-source-graphql: ^2.2.0 => 2.5.2
    gatsby-source-youtube-v2: ^1.0.1 => 1.0.1
    gatsby-transformer-sharp: ^2.3.19 => 2.5.3
    gatsby-transformer-yaml: ^2.3.0 => 2.4.2
  npmGlobalPackages:
    gatsby-cli: 2.12.37
    gatsby: 2.13.72
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by vihanb** [comment]
Looks like this is a duplicate of #5764.
