### ISSUE TITLE
Emotion Theme prop rendering incorrect styles

### ISSUE THREAD

**Issue by amykapernick** [gatsbyjs/gatsby#24737]
## Description

Based on the props in a theme, styles are rendered. Eg. the header logo svg changes colours based on a prop in the theme
```
.name {
    fill: #000;
    fill: ${(props) => (props.theme.colours.themes.header.lightLogo === true && `#fff`)};
}
```
If it has the `lightLogo` prop, it should fill with white, otherwise black.

But on the homepage of the site, it currently renders the logo with a white fill, despite the fact that the `lightLogo` prop is false

This only happens during a production build (`gatsby build`), not in dev mode (`gatsby develop`)

In React dev tools, can see the theme prop on the logo, and the `lightLogo` prop is set to false on the homepage, however the white fill style is still being rendered
![image](https://user-images.githubusercontent.com/15953185/83599081-e3e36300-a59d-11ea-841d-5edfc575ea0e.png)
![image](https://user-images.githubusercontent.com/15953185/83599113-f3fb4280-a59d-11ea-98d4-f5a59b352b45.png)

### Steps to reproduce

- Github Repo <https://github.com/amykapernick/emotion-theming-issue>
- Netlify Build of repo <https://serene-bardeen-30de22.netlify.app>

### Expected result

If the theme has the prop for `lightLogo: false`, the logo in the header should have the fill of `#000`

### Actual result

Even though the theme prop has `lightLogo: false`, the logo in the header on the homepage as the fill of `#fff`

### Environment

```
  System:
    OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
    Yarn: 1.22.4 - /home/linuxbrew/.linuxbrew/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.9.0/bin/npm
  npmPackages:
    gatsby: ^2.21.21 => 2.21.21
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-plugin-emotion: ^4.3.1 => 4.3.1
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-netlify-cms: ^4.3.1 => 4.3.1
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^2.3.1 => 2.3.1
    gatsby-plugin-sharp: ^2.6.2 => 2.6.2
    gatsby-source-filesystem: ^2.3.1 => 2.3.1
    gatsby-transformer-json: ^2.4.3 => 2.4.3
    gatsby-transformer-remark: ^2.8.12 => 2.8.12
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2
```

**Comment by LekoArts** [comment]
Thank you for opening this!

I cloned your repository, ran a `gatsby build` and `gatsby serve` and didn't see the behavior you're describing. I don't think this is an issue with Gatsby itself but rather your code and/or how browsers order duplicate CSS styles.

![image](https://user-images.githubusercontent.com/16143594/83609520-b63af180-a57e-11ea-87ea-29361d9ab7b9.png)

I would recommend not having duplicate definitions but rather do a ternary check on the fill property:

```js
.name {
  fill: ${(props) => (props.theme.colours.themes.header.lightLogo ? `#fff` : `#000`)};
}
```

I pushed that version to Netlify and it also works: https://angry-goodall-9f0fdb.netlify.app/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by amykapernick** [comment]
@LekoArts I understand how browsers order duplicate styles, but if it was rendering properly, the `fill: #fff` should not have existed if the `lightLogo` prop wasn't true. I had previously had it as a ternary check and that was broken as well.

Can you confirm if you've made any other changes to the code, as I've changed mine back to ternary check using the exact code you did and it still doesn't work (my repo has been updated with that)

The code is working perfectly fine in dev mode, but not in the production build, and the code is still rendering incorrectly for me, which to me suggests a bug in how it's being built, this issue has not yet been resolved.

**Comment by LekoArts** [comment]
> Can you confirm if you've made any other changes to the code, as I've changed mine back to ternary check using the exact code you did and it still doesn't work (my repo has been updated with that)

I only changed the line I mentioned and installed the project fresh. Maybe try removing your `.cache`, `public` and `node_modules` folder + `yarn.lock` and a fresh install.

I tried this via `gatsby build` and `gatsby serve` on my Windows (WSL) machine in multiple browsers, also cloned your project on my Mac and it also works:

**Comment by amykapernick** [comment]
I have burnt all cache and module folders several times over, as well as updating modules to ensure that they're up to date

You can see on this page - <https://serene-bardeen-30de22.netlify.app> - which is built from my code, that flicking through the pages changes the background colour as per the different themes. But for the homepage, the values for the theme (printed below on the page) do not match the CSS being defined
![image](https://user-images.githubusercontent.com/15953185/83623910-89a9c880-a5c4-11ea-8b40-33d5d7d31381.png)
Every other page however has the correct CSS for that theme
![image](https://user-images.githubusercontent.com/15953185/83624128-ce356400-a5c4-11ea-816c-ecafbf6b124a.png)

**Comment by LekoArts** [comment]
When visiting the Homepage I see the correct color:

![image](https://user-images.githubusercontent.com/16143594/83737632-91647e00-a653-11ea-8628-79ac0dca4b39.png)

I think overall your theming setup is a bit convoluted so I went ahead and created a simple example of how I would do it. The gist is that I place the ThemeProvider in the wrapPageElement API and only access the pageContext, not passing around props in the Layout component and reassigning variables.

https://github.com/LekoArts/emotion-theming-multiple

The theme variants are defined in the wrapPageElement.js file. Maybe this simple example will help you in restructuring your page
