### ISSUE TITLE
cli: Status bar doesn't show in `develop`

### ISSUE THREAD

**Issue by LekoArts** [gatsbyjs/gatsby#24736]
## Description

The develop status bar doesn't always show in develop mode even though it should:

https://github.com/gatsbyjs/gatsby/blob/342d835b6e02e766fd3a2abd9cb7c4fc7daf28cc/packages/gatsby-cli/src/reporter/loggers/ink/index.tsx#L8-L12

This isn't expected behavior and we need to see why `showStatusBar` is false.

### Steps to reproduce

In my tests this behavior already shows when spinning up a hello-world starter.

### Expected result

The develop status bar shows when bootstrap is finished with the status, pageName and number of pages.

### Actual result

Doesn't show.

### Environment

```

  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9
    gatsby-remark-prismjs: ^3.5.2 => 3.5.2
    gatsby-source-filesystem: ^2.3.8 => 2.3.8
    gatsby-transformer-json: ^2.4.3 => 2.4.3
    gatsby-transformer-remark: ^2.8.13 => 2.8.13
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3
  npmGlobalPackages:
    gatsby-cli: 2.12.36
    gatsby-dev-cli: 2.7.0

```

**Comment by blainekasten** [comment]
@LekoArts is it inconsistent? Or does it never show up for you?

**Comment by LekoArts** [comment]
@blainekasten It's inconsistent. Sometimes it shows, sometimes not. Didn't have yet to dig into why though.
