### ISSUE TITLE
Types for `CreateRemoteFileNodeArgs['cache']` are inconsistent with Gatsby types

### ISSUE THREAD

**Issue by ricokahler** [gatsbyjs/gatsby#24735]
### Description

It seems like the types for `CreateRmoteFileNodeArgs['cache']` are no longer consistent with the types from Gatsby. This causes a type error when directly passing the `cache` from the `CreateResolversArgs` to `createRemoteFileNode`.

### Steps to reproduce

clone [this](https://github.com/ricokahler/bug-repro-gatsby-source-filesystem-types.git) `https://github.com/ricokahler/bug-repro-gatsby-source-filesystem-types.git`

See this line:

https://github.com/ricokahler/bug-repro-gatsby-source-filesystem-types/blob/6370676bb8dd959f8b815f0a5d490e61956aeaf7/create-resolvers.ts#L34-L40

![image](https://user-images.githubusercontent.com/10551026/83601288-49076c00-a53e-11ea-9494-3eb4b47a5798.png)

### Expected result

No type error

### Actual result

Seems like the types of the cache in the gatsby-source-filesystem changed and no longer matches the types from gatsby itself.

### Environment

```
  System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15 
    gatsby-source-filesystem: ^2.3.10 => 2.3.10 
  npmGlobalPackages:
    gatsby-cli: 2.11.15
    gatsby: 2.20.6
```

**Comment by vladar** [comment]
You are correct - typings for `createRemoteFileNode` are stale. Should be fixed via #24750

Thanks for reporting this! 💜
