### ISSUE TITLE
Broken navigation on Docs & Blog Components contributing page

### ISSUE THREAD

**Issue by ascorbic** [gatsbyjs/gatsby#24746]
## Description
The "Next" link on the [Docs & Blog Components](https://www.gatsbyjs.org/contributing/docs-and-blog-components/) is broken, with the `to` prop null. This was causing build failures (since fixed). I'm not aware of the details of how the navigation is handled with these, othewrwise I would've fixed it myself

### Steps to reproduce
Visit [Docs & Blog Components](https://www.gatsbyjs.org/contributing/docs-and-blog-components/). Click on "Gatsby Brand Guidelines", and note that the link is incorrect.

**Comment by LekoArts** [comment]
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/19685
