### ISSUE TITLE
surge.sh website not indexed in google

### ISSUE THREAD

**Issue by NourddineMaghmouli** [gatsbyjs/gatsby#24742]
Hi,

I have hosted a webpage under surge.sh but now it seems that it will not be indexed by google because robot.txt blocks it, is there a solution for this?
the page url is: [https://guelma-stories.surge.sh]
also I was wondering if I can redirect the page to my own domain such as: guelma-stories.com for example?
please note that I am new at coding, I just started learning some very basic staff on html and css 

Thanks

Noureddine

**Comment by LekoArts** [comment]
Thank you for opening this!

Please reach out to Surge's support as this is meant to be Gatsby-only. Thanks!

P.S.: It seems this is expected behavior: https://github.com/sintaxi/surge/issues/288
