### ISSUE TITLE
Kyle's image on https://gatsbygram.gatsbyjs.org/ is a deadlink

### ISSUE THREAD

**Issue by davidkartuzinski** [gatsbyjs/gatsby#24759]
## Description

On the example website, https://gatsbygram.gatsbyjs.org/, linked from https://www.gatsbyjs.com/guides/building-beautiful-sites/, Kyle's avatar picture is a deadlink. The URL is not getting the image of Kyle's avatar in this example.

![Missing Kyle Avatar](https://user-images.githubusercontent.com/29503118/83668723-b7950a00-a5d0-11ea-8042-4bb28c9f32af.png)
### Steps to reproduce

You just need to go to: https://gatsbygram.gatsbyjs.org/ to see the missing avatar. 

It looks like a change in the Instagram API or Kyle changed his instagram picture...

### Expected result

Kyle's avatar picture should be there.

### Actual result

Kyle's picture is missing.

### Environment

I am just browsing on the latest Chrome browser.

**Comment by sidharthachatterjee** [comment]
Thanks for the report @davidkartuzinski 

Looks like the URL is now broken. Data seems to be pretty out of date. @KyleAMathews Want to do a new export from your Instagram and give us your data? 😅
