### ISSUE TITLE
Is there any simple way to include content from a Markdown / MD file in a component?

### ISSUE THREAD

**Issue by ratacat** [gatsbyjs/gatsby#24760]
I've been trying to figure this out for a while. There's plenty of solutions around using MDX and expressing your components within MD.  But what about the reverse?  I just want to pull some MD content in from a file and render the html within a component on our website. This lets us start to hook up the MD content to the Netlify CMS and it becomes easier for non developers to change basic wording etc.  Seems like it would be a straight forward thing to do...

Does anyone have any suggestions?  I've tried using remark-rehype, but there's no way to just import a MD file into a component. And using remark-transformer-gatsby seems untenable for this use case, as there is no way to know which content pieces belong to which components.

Thankyou!

**Comment by LekoArts** [comment]
Thank you for opening this!

With MDX and `gatsby-plugin-mdx` you can simply import the file like `import MyFile from "./index.mdx"` to your component and use it like `<MyFile />`. Here would be an example of this: https://github.com/LekoArts/gatsby-themes/blob/f25dfb6105669f62468abc63ceb73c2fbbb73065/themes/gatsby-theme-cara/src/components/about.tsx#L9

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
