### ISSUE TITLE
gatsby-plugin-manifest troubleshooting addendum suggestion

### ISSUE THREAD

**Issue by cbdp** [gatsbyjs/gatsby#24764]
Documentation: https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/

## Summary
I received an error in my browser during a lighthouse audit, wherein an icon listed in the manifest returned a 404 not found. I'm by no means an expert, but I finally discovered this issue was due to a conflict between the apache websever and gatsby-plugin-manifest.

### Motivation
Apache is still widely used and I imagine a lot of people will run into the same problem, if they are attempting to use gatsby as a PWA.

## Steps to resolve this issue
This issue could be resolved directly in the software by writing to /favicons instead of /icons, but my suggestion is only to amend the documentation, because it might be an edge case. Below is a draft of my suggestion.

### APACHE: Error while trying to use the following icon from the Manifest
If you are using an Apache webserver and utilising the automatic solution, you may receive an error when attempting to access an icon listed in the Manifest as residing in the /icons folder. This is because Apache restricts access to all /icons folders by default. You can fix this by switching to the hybrid solution and changing the foldername from 'icons' to something like 'favicons'. 

Example:
```js
{
    "src": "favicons/icon-144x144.png",
    "sizes": "144x144",
    "type": "image/png"
}
```

Edit: this can also be fixed with
`cp /etc/apache2/mods-available/alias.conf /etc/apache2/mods-available/alias.conf.back`
`cat /etc/apache2/mods-available/alias.conf | grep "Alias /icons/"`
if you have access to do so.

**Comment by marcysutton** [comment]
Hey there, thanks for the issue. That seems like a fine docs addendum to me, as I see here that `/icons` is indeed restricted: https://electrictoolbox.com/apache-icons-directory/

Two suggestions I'd make:

- Add a filename for the example code to provide more context: https://www.gatsbyjs.org/contributing/docs-and-blog-components/#code-blocks
- Explain more about the command line code so people know what it does and why they'd run it

**Comment by cbdp** [comment]
@marcysutton, thank you for the suggestions, I've incorporated them to the best of my ability below: 
## Second draft of addendum to gatsby-plugin-manifest docs
### APACHE: Error while trying to use the following icon from the Manifest
If you are using an Apache webserver and utilising the automatic solution, you may receive an error when attempting to access an icon listed in the Manifest as residing in the /icons folder. This is because Apache restricts access to all /icons folders by default. You can fix this by switching to the hybrid solution and changing the foldername from 'icons' to something like 'favicons'. 

Example:
```js
// In the gatsby-plugin-manifest section of your gatsby-config.js
  icon: `src/images/icon.png`, // This path is relative to the root of the site.
  icons: [
    {
        "src": "favicons/icon-144x144.png",
        "sizes": "144x144",
        "type": "image/png"
    },  // Add or remove icon sizes as desired
  ]
```

Alternatively, if you have access to modify apache, you can resolve this issue by removing the restriction on /icons folders.

Create a backup of /etc/httpd/conf.d/autoindex.conf:
`# cp /etc/httpd/conf.d/autoindex.conf /etc/httpd/conf.d/autoindex.conf.back`

Comment out "Alias /icons/" in /etc/httpd/conf.d/autoindex.conf:
`# cat /etc/httpd/conf.d/autoindex.conf | grep "Alias /icons/"`

Reload Apache/or restart server:
`# service httpd reload`

**Comment by marcysutton** [comment]
That looks good to me, my only remaining question is about whether the leading `#` needs to be removed from each line to run the commands. 

I've labeled this issue as help wanted in case anyone wants to create a PR, thanks again for opening an issue!

**Comment by cbdp** [comment]
Thanks again marcy. I deleted the '#'s and created a pull request to commit this text to the docs for gatsby-plugin-manifest.
