### ISSUE TITLE
Please provide a production grade complete example of gatsby for apps

### ISSUE THREAD

**Issue by kaushalyap** [gatsbyjs/gatsby#24768]
## Summary

Please provide the community with a production grade open source, hosted example of Gatsby for app with following

- User Authentication
- Dynamic routes
- Dynamic content
- Security best practices.

### Basic example

Clone of social network would be good!. If you guys want to be great you guys can implement a community forum powered by Gatsby, since Gatsby does not have its own community forum like [Netlify Community](http://community.netlify.com/), nothing fancy is necessary.

### Motivation

Currently Gatsby is mostly used for static sites, but not much for dynamic apps (JAM stack). Have not seen any relatively big JAM stack app (using Gatsby) in production. Currently there is [Gatsby Mail example](https://gatsby-mail.netlify.app/) but it comes with following disclaimer

>  Don't use this for anything real!

which gives the impression that Gatsby is for static sites.

While reading things on the web it seems Gatsby is mostly recommended for static websites and Nextjs for dynamic web apps. With Nextjs recent [SSG support](https://nextjs.org/blog/next-9-3#next-gen-static-site-generation-ssg-support) one can use both SSG and SSR  on a single website  (hybrid) which offers more flexibility than Gatsby.

Giving a production grade example would  encourage Gatsby users to try it for dynamic apps.

**Side Note:**

I am not trying offend Gatsby here, I like Gatsby. But Gatsby's current push towards app is not convincing IMHO.

**Comment by kaushalyap** [comment]
Gatsby have great docs covering required topic for implementing dynamic apps, but just having great docs is not enough in order to adopt Gatsby for dynamic apps IMHO.

**Comment by sidharthachatterjee** [comment]
Hey! Great question. Check out https://github.com/DSchau/gatsby-mail built by @DSchau from our team. 

It should check all the boxes you described above. Cheers!

**Comment by kaushalyap** [comment]
Any plans to build something bit more complex as I suggested initially?

**Comment by sidharthachatterjee** [comment]
@kaushalyap Probably unlikely for now. Complexity that serves the purpose of illustrating new use cases would be welcome but as far as I understand, all the four points you mentioned are covered in the Gatsby Mail example. 

In case one of the above is _not_, we're happy to discuss a request to fulfil it or add documentation for it! Thanks for opening this. Let's close for now since there isn't a clearly actionable next step here. 

Cheers.
