### ISSUE TITLE
Serving Ads On A Gatsby Blog

### ISSUE THREAD

**Issue by 3200creative** [gatsbyjs/gatsby#24781]
I work with a fair amount of bloggers who generate 100% of income serving ads distributed by ad networks.

One has requested a move to GatsbyJS. I'm comfortable with the build process and certain the final site will be awesome on Gatsby however, I haven't worked on a site that is ad-based. I reached out to the Ad Networks and showed them a few examples of GatsbyJS blogs to confirm they would work. Their response was:

_"We took a peek and these sites won't work with our ads because the DOM, is in fact, not reloading when you navigate to a new page. Ads would only work on the initial page view, but not on any other pages since the DOM doesn't reload._ 

If you were to make a change for any clients that are currently using our ads, we wouldn't be able to continue running ads with the gatsby setup and there would, of course, be significant drops in revenue."

Is there a solution while still using GatsbyJS?

Thanks in advance!

**Comment by herecydev** [comment]
I don't think any SPA would work if you can't "reload the DOM", I don't understand why that couldn't work though, I've seen plenty of ads work with React

**Comment by 3200creative** [comment]
I've see ads in React. I looked through the entire showcase at GatsbyJS and couldn't locate a single site example that uses ads. I'd prefer to use GatsbyJS over anything else if possible. I'll leave this open in the event someone else has insight. Thanks for the prompt response.

**Comment by herecydev** [comment]
But GatsbyJs is built on react, there's nothing stopping it working. I'm going to close this issue because there doesn't seem to be an issue.

If you experience an issue integrating an ad network into your Gatsby site please open another ticket and I'm happy to help with that.

**Comment by 3200creative** [comment]
Thanks for the update. While GatsbyJS is built on React, it is an SPA. I reached out to the ad netowrk and a non-SPA is required.

NextJS was their recommendation. You were initially correct. 'SPA's don't work' for this scenario.
