### ISSUE TITLE
Creating client-only sub-routes for static pages, /item/:id/edit

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#24792]
Gatsby [prides itself](https://www.gatsbyjs.org/docs/adding-app-and-website-functionality/) in being not just a static site generator:

> [Gatsby] allows you to make a site as feature-less or feature-rich as you want, you aren’t restricted to just static sites.

For web apps, one very common REST URL pattern is `/item/:id/edit`. This should be clearly documented at [Hybrid app pages](https://www.gatsbyjs.org/docs/adding-app-and-website-functionality/#hybrid-app-pages).

I found a similar issue #16250, but with no scalable or official solution.

**Comment by herecydev** [comment]
It's literally documented directly underneath where you linked: https://www.gatsbyjs.org/docs/adding-app-and-website-functionality/#client-only-routes

This links of to a dedicated page about client only routes as well.

**Comment by freiksenet** [comment]
There is a link to [client-only routes](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/) in that document. You should be able to use client-only routes to do that.
