### ISSUE TITLE
Docs: link to findpath.js is broken

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#24796]
At https://www.gatsbyjs.org/docs/gatsby-internals-terminology/#matchpath, the link under `find-path.js` is missing in the source.

> But on the frontend, when resolving the page from the path (find-path.js), it is used (via reach router) to find the matching page.

The link to "pages are sorted" in the next paragraph is broken too.

> Note that the [pages are sorted](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/query-runner/pages-writer.js#L38) so that those with matchPaths are at the end, so that explicit paths are matched first.

**Comment by muescha** [comment]
there is a warning at the top of this doc, that this is outdated...

see also #14228

**Comment by LekoArts** [comment]
I'll close this in favor of https://github.com/gatsbyjs/gatsby/issues/14228 - with Incremental builds in OSS now in Gatsby v3 some more things have changed
