### ISSUE TITLE
How to use Tailwind CSS in Gatsby?

### ISSUE THREAD

**Issue by zwl1619** [gatsbyjs/gatsby#24819]
How to use [Tailwind CSS](https://tailwindcss.com/docs/installation) in Gatsby?
I tried [gatsby-plugin-tailwindcss](https://github.com/muhajirdev/gatsby-plugin-tailwindcss) but it doesn't work.

**Comment by abhishekjakhar** [comment]
Hi @zwl1619
Did you followed the steps mentioned in the following documentation https://www.gatsbyjs.org/docs/tailwind-css/

**Comment by zwl1619** [comment]
@abhishekjakhar   I didn't find this part, I read it and it works now, thank you!

**Comment by abhishekjakhar** [comment]
> @abhishekjakhar I didn't find this part, I read it and it works now, thank you!

@zwl1619 That's great, you're welcome 👍 ⚡
