### ISSUE TITLE
Is it a good idea to use `onCreatePage` with "stateful" updates?

### ISSUE THREAD

**Issue by lffg** [gatsbyjs/gatsby#24827]
I am quite new to the Gatsby ecosystem, so I don't actually know if what I am planning to do is a "good" or "bad" idea.

Basically, I am using the `onCreatePage` API to delete the default pages that Gatsby creates based in the `src/pages` directory to re-create them for each locale my website must support, passing the respective internationalization data through page context.

<details>
  <summary>Minimal example of my current <code>gatsby-node.js</code>'s <code>onCreatePage</code>.</summary>

```js
// Example of the `locales` array:
const locales = ['en', 'pt'];

exports.onCreateNode = ({ actions, page }) => {
  const { createPage, deletePage } = actions;

  deletePage(page);

  locales.forEach((locale) => {
    const translations = allTranslations[locale];

    createPage({
      ...page,

      path: createLocalizedPath({
        locale,
        base: page.path
      }),

      context: {
        ...page.context,
        translations,
        locale
      }
    });
  });
};
```
</details>

The problem is when I need to change a locale from the source (`resources/locales/<locale>`), the only way to make the changes reflect in the Gatsby pages is by restarting the entire development server, which although is currently quite fast, may become slower as my site grows.

To solve this problem, I wonder if adding a file watcher inside the `onCreatePage` API is a good idea, which will watch for changes in a specific locale file and re-create the dependent pages. Something like:

<details>
  <summary>Example code (new <code>gatsby-node.js</code>).</summary>

```diff
  // Example of the `locales` array:
  const locales = ['en', 'pt'];

+ // This will be something like:
+ // { en: null, pt: null }
+ const localeFileListeners = locales.reduce(
+   (acc, current) => ({ ...acc, [current]: null }),
+   {}
+ );

  exports.onCreateNode = ({ actions, page }) => {
    const { createPage, deletePage } = actions;

    deletePage(page);

    locales.forEach((locale) => {
      const translations = allTranslations[locale];

+     // This will ensure only one listener is added per locale.
+     if (!localeFileListeners[locale]) {
+       addListenerHere(locale);
+
+      localeFileListeners[locale] = true;
+     }

      createPage({
        ...page,

        path: createLocalizedPath({
          locale,
          base: page.path
        }),

        context: {
          ...page.context,
          translations,
          locale
        }
      });
    });
  };
```
</details>

I know it would be OK if I did that in `createPagesStatefully` (although that API is not suitable for this particular case, as I need to delete pages and re-create them). So, my question is: **Is it OK to do so in `onCreatePage`?**

**Comment by herecydev** [comment]
Should be fine, that's what the API is designed for. You can see the gatsby-plugin-page-creator does this here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-page-creator/src/gatsby-node.js#L60-L82

So you've got some priort art to look at 👌

What I would say, having written a plugin for i18n, and doing exactly what you've done is.... is it worth it? How frequently are your locales changing?

**Comment by lffg** [comment]
Hey, @herecydev, thanks for your response.

I've looked at `gatsby-plugin-page-creator` before, and it watches the directory inside the `createPagesStatefully` API. My question regards the `onCreatePage`. Is it OK to, for example, watch a file change within `onCreatePage`?

> What I would say, having written a plugin for i18n, and doing exactly what you've done is.... is it worth it? How frequently are your locales changing?

I don't actually know if it's really worth it. I'm just experimenting to learn more about Gatsby while I build my website. :P

**Comment by herecydev** [comment]
I don't see why not
