### ISSUE TITLE
 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by abdokouta** [gatsbyjs/gatsby#24829]
since yesterday I'm getting this message upon building or run development the project, can anyone help me with this! this message shows on local, Netlify, Gatsby Cloud and  have tried build environment variables and no hope, is this issue related to a package in my package.json or my code ??

`NODE_OPTIONS  --max-old-space-size=4096`

`
17:42:52 PM: success building schema - 3.858s
17:42:52 PM: Using environment config: 'production'
19:06:27 PM:  <--- Last few GCs ---> [3079:0x2e872d0] 6586247 ms: Mark-sweep 2004.1 (2070.2) -> 1988.9 (2070.7) MB, 4923.3 / 0.2 ms (average mu = 0.128, current mu = 0.079) allocation failure scavenge might not succeed [3079:0x2e872d0] 6591858 ms: Mark-sweep 2004.4 (2070.7) -> 1989.2 (2071.2) MB, 5283.1 / 0.2 ms (average mu = 0.094, current mu = 0.058) allocation failure scavenge might not succeed
19:06:27 PM:  <--- JS stacktrace ---> ==== JS stack trace ========================================= 0: ExitFrame [pc: 0x13cb519] Security context: 0x0d001e4808d1 <JSObject> 1: join [0xd001e48eb19](this=0x34a1d6bf01d9 <JSArray[10]>) 2: toString [0xd001e48d381](this=0x34a1d6bf01d9 <JSArray[10]>) 3: _objectSort [0x81be8328409] [/usr/src/app/www/node_modules/node-object-hash/dist/stringifiers.js:~336] [pc=0x22c7008a1efb](this=0x081be832ca91 <Object map = 0x36c018869299>,0x34a1d6bf00b1 <Object map = 0x1d1502376809>) 4: /*...
19:06:27 PM: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
19:06:27 PM:  1: 0xa07f90 node::Abort() [node]
19:06:27 PM:  2: 0xa0839c node::OnFatalError(char const*, char const*) [node]
19:06:27 PM:  3: 0xb80d9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
19:06:27 PM:  4: 0xb81119 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
19:06:27 PM:  5: 0xd2d875 [node]
19:06:27 PM:  6: 0xd2df06 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
19:06:27 PM:  7: 0xd3a785 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
19:06:27 PM:  9: 0xd3e0ec v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
19:06:27 PM:  8: 0xd3b635 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
19:06:27 PM: 10: 0xd04cbb v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
19:06:27 PM: 11: 0x10464be v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node] 12: 0x13cb519 [node]
19:28:50 PM:  <--- Last few GCs ---> [5976:0x44c22d0] 6599069 ms: Mark-sweep 2002.5 (2068.7) -> 1987.2 (2069.2) MB, 4689.7 / 0.2 ms (average mu = 0.128, current mu = 0.055) allocation failure scavenge might not succeed [5976:0x44c22d0] 6604305 ms: Mark-sweep 2002.7 (2069.2) -> 1987.5 (2069.7) MB, 5190.1 / 0.2 ms (average mu = 0.069, current mu = 0.009) allocation failure scavenge might not succeed <--- JS stacktrace ---> ==== JS stack trace ========================================= 0: ExitFrame [pc: 0x13cb519] Security context: 0x05b41a6808d1 <JSObject> 1: sort [0x5b41a6978d1](this=0x0db53e3b4951 <JSArray[2]>) 2: _array [0x14149b3e2a29] [/usr/src/app/www/node_modules/node-object-hash/dist/stringifiers.js:~260] [pc=0x345ef9e52627](this=0x14149b3e7259 <Object map = 0x34782e1a9299>,0x027c5a92b739 <JSArray[17]>) 3: _objectSort [0x14149b3e2ba9] [/usr/src/app/www/node_modules/node-object-hash/dist/stringif...
19:28:50 PM: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory 1: 0xa07f90 node::Abort() [node]
19:28:50 PM:  3: 0xb80d9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
19:28:50 PM:  2: 0xa0839c node::OnFatalError(char const*, char const*) [node]
19:28:50 PM:  4: 0xb81119 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
19:28:50 PM:  5: 0xd2d875 [node] 6: 0xd2df06 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node] 7: 0xd3a785 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node] 8: 0xd3b635 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node] 9: 0xd3e0ec v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node] 10: 0xd04cbb v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node] 11: 0x10464be v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
19:28:50 PM: 12: 0x13cb519 [node]
19:29:04 PM: /app/services/cloud-runner/runner-command: line 25: 5976 Aborted (core dumped) ${GATSBY} build --no-color
19:29:04 PM: ERROR Failed to compile: Error: Exited with code 134
`

**Comment by tim-line** [comment]
I also started getting a similar error after upgrading from 2.21.40 to <2.22.0. For me it seems to get thrown during the create nodes cycle and only when creating a large number of nodes (< 10000). I've tried increasing --max-old-space-size=8192 and still get the error. I've downgraded back 2.21.40 and my build is running without issue.

**Comment by abdokouta** [comment]
for me, it was issue n layout that infinity loops while creating pages i have fixed it and everything going fine. 
P.S: i using latest gatsby version now, so please double-check that there is nothing causing this issue in ur code

**Comment by tim-line** [comment]
I'll double check the code but I think that the only thing changing to produce the error is updating the Gatsby version. The code remains the same but errors when updated to 2.22.0.
