### ISSUE TITLE
OnClick Event not Responding

### ISSUE THREAD

**Issue by imthatalex** [gatsbyjs/gatsby#24823]
## Summary

I am currently attempting to have a pop up appear when I press a button using an onclick event. 

## Relevant information

- I am using the template provided by Gatsby Tutorial-Part-Three
- here is the function the onclick event points too. 

`
function windowAlert() {
    window.alert("Hello World")
};
`

- here is the jsx where the onclick event can be found.

`
export default () => (
    <button onclick={windowAlert} id={TestStyles.tester}>
        Hello World
    </button>
);
`

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.19.45 => 2.19.45
    gatsby-plugin-typography: ^2.4.1 => 2.4.1
  npmGlobalPackages:
    gatsby-cli: 2.12.21

**Comment by herecydev** [comment]
You misspelled `onclick` => `onlcick` if that's the problem. Otherwise this will be a react issue!

**Comment by imthatalex** [comment]
> You misspelled `onclick` => `onlcick` if that's the problem. Otherwise this will be a react issue!

Fixed, if only that was the issue lol.
