### ISSUE TITLE
Gatsby Request for Blogposts (RFB #1)

### ISSUE THREAD

**Issue by calcsam** [gatsbyjs/gatsby#2483]
Gatsby is an incredibly powerful framework with a huge number of applications; it's also an opinionated framework with implementations of some of the most-talked-about ideas in the development world.

@KyleAMathews and I got to talking about how to help more people see how Gatsby can help make the web better. 

We figured one way to do that was to issue Gatsby's first Request For Blog posts (RFB), from community members to highlight some of Gatsby's features and how it fits into larger trends.

Ideally these blog posts would be in the form of first-hand experiences that illuminate broader development trends, although we're open to other formats as well. 

Some examples are recent posts by [Kostas Bariotis](https://www.gatsbyjs.org/blog/2017-09-18-gatsby-modern-static-generation/), [Tim Arney](https://www.gatsbyjs.org/blog/2017-09-26-embracing-graphql/) and [David James](https://www.gatsbyjs.org/blog/2017-10-05-portfolio-site-gatsby-wordpress/). 

We'd love to publish your piece on the official blog at [GatsbyJS.org](http://gatsbyjs.org); if you have a personal blog, you can make that the canonical post and we'll cross-post at [GatsbyJS.org](http://gatsbyjs.org). Either way, you'll get to:

-   talk about building cool stuff!
-   build up material for a future meet up or conference talk
-   share your experience with the Gatsby community :)

And of course, we're happy to help edit.

## Overview

Some themes we've heard chatter about include:

-   Designing websites with components

-   Progressive Web Apps & The Next Billion Web Users

-   CSS-in-JS

-   Using Gatsby with a CMS (e.g. Wordpress, Contentful, Drupal, etc).

-   To Gatsby From Wordpress

-   Automated builds & deployments

-   The changing Javascript ecosystem

### Designing websites with components

-   Could discuss plugging existing components used in web app or web site into Gatsby, or vice versa

-   How does building websites feel different when using components vs. traditional templates?

-   What was the effect of that on your iteration speed? Consistency of look and feel?

### Progressive Web Apps & The Next Billion Web Users

-   Should be a site that was built with the assumption that a large fraction of users would be on mobile devices, or from developing countries where mobile devices are the predominant way people access the web

-   Discuss the benefits of progressive web apps & the decision to use Gatsby

-   What was the effect on load speeds? User engagement with the site?

### CSS-in-JS

-   Used Gatsby with a library like Typography.js or styled-components + Hedron with design primitives in JS

-   This could be a pretty visual post, images & animations like[  this one](https://camo.githubusercontent.com/0506699aaaae2f9772cc381b92f2aa5e14eba296/687474703a2f2f7a697070792e6766796361742e636f6d2f556c74696d6174655765656b6c7942617265626972646261742e676966) would be really catchy

-   What was your motivation for doing this?

-   What was the effect on design iteration speed?

### Using Gatsby with a CMS

-   Eg a site that's frontend by Gatsby and backed by a CMS like Wordpress, Drupal, etc

-   What was behind the decision to use the two together? What business needs & use-cases did you have to support?

-   How did you find the experience of using the Gatsby plugin system?

-   What does your workflow for publishing look like?

### To Gatsby From Wordpress

-   The experience of someone who's used to building Wordpress sites who decided to build a Gatsby site instead

-   What made you decide to transition technologies? Was this experimental? Or do you see your trajectory moving toward the JS ecosystem?

-   What was your experience like in the Gatsby world vs the Wordpress ecosystem?

-   What sort of features would you need to make it possible for you to build more sites in Gatsby?

### Automated builds & deployments

-   Your experience with Gatsby in the context of developer trends towards automated build and deploy systems (DevOps, Heroku, etc, etc).

-   What's your experience with automated build & deployment systems?

-   How does it compare to your experiences with manual deployment processes?

-   When you used Gatsby, where did you feel it fell on the spectrum? Did you like that? How did it compare to previous tools you used to build websites?

-   Have you used specialized build tools specifically for websites or static sites before (e.g. Netlify). What was your experience with them?

### The changing Javascript ecosystem

-   Your experience with Gatsby in the context of the changing Javascript ecosystem

-   How Gatsby interacts with your experience using things like

    -   Build tools like webpack, grunt, gulp, etc

    -   ES5, ES6, ES7, Coffeescript

    -   The shift towards more functional & declarative JS from imperative.

    -   React, GraphQL

    -   Server-side rendering

These are all just ideas, not a checklist! Maybe you have a super visceral reaction to one or two of these. That's great --- we'd love to see a post :)

## Process

If you're interested in writing a post, create a new Github Issue with [Proposed Post] header and comment here linking to it.

We'll respond on that issue with questions & comments, and can take the conversation from there.

**Comment by KyleAMathews** [comment]
Was just thinking — how about we add this as well to the "How to Contribute" section of the docs? Issues can get lost pretty easily. The docs get a lot more eyeballs on them.

**Comment by calcsam** [comment]
Definitely agree. I'll open a PR soon adding this as a separate page w/ a link here, under a How To Contribute sub-part of our Community section.

**Comment by KyleAMathews** [comment]
Closing this out as it should probably live somewhere else e.g. in the contributing guide.
