### ISSUE TITLE
npm install -g gatsby-cli, core-js, error

### ISSUE THREAD

**Issue by 4096void** [gatsbyjs/gatsby#24841]
When I run `npm install -g gatsby-cli`,

Results below:
```javascript
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/my_name/.npm/_logs/2020-06-06T14_32_49_601Z-debug.log
```

Or can I just update core-js@latest to fix this?
Thanks in advance.

**Comment by herecydev** [comment]
An update to core-js is being tracked here: https://github.com/gatsbyjs/gatsby/issues/15601

Are you able to use the gatsby-cli, this shouldn't be an error but just a warning

**Comment by 4096void** [comment]
After few times, it works fine now, seems not related to core-js@<3
