### ISSUE TITLE
How to conditionally query for data in Gatsby from Contentful

### ISSUE THREAD

**Issue by zaidakhterr** [gatsbyjs/gatsby#24840]
## Summary

I am trying to query for Sections inside of pages. But before I query I need to check if that section is available in contentful otherwise the code breaks.

## Relevant information

To do that I am doing something like this in `gatsby-node.js`

```javascript
exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions

  const pages = await graphql(`
    query GetPages {
      allContentfulPage {
        totalCount
        edges {
          node {
            sections {
              __typename
            }
            slug
            title
            node_locale
            id
          }
        }
      }
    }
  `)

  pages.data.allContentfulPage.edges.forEach(async (edge) => {
    const pageTemplate = path.resolve(`src/templates/page.js`)

    // check if file exists
    const localeSlug = edge.node.node_locale
      ? `${edge.node.node_locale}/${edge.node.slug}`
      : edge.node.slug

    const sectionExists = (sec) =>
      edge.node.sections.some((s) => s.__typename === sec)

    const sections =
      edge.node.sections.length > 0
        ? await graphql(`
    {
      contentfulPage(id: { eq: ${JSON.stringify(edge.node.id)} }, node_locale: { eq: ${JSON.stringify(edge.node.node_locale)} }){
        sections{
          ${
            sectionExists("ContentfulSectionBody")
              ? `
          ... on ContentfulSectionBody {
            __typename
            id
            tItle
            childContentfulSectionBodyBodyRichTextNode {
              content {
                content {
                  value
                }
              }
            }
          }
          `
              : ``
          }
        }
      }
    }
    `)
        : ""

    createPage({
      path: localeSlug,
      component: pageTemplate,
      context: {
        page_id: edge.node.id,
        node_locale: edge.node.node_locale,
        slug: edge.node.slug,
        sections: sections !== "" ? sections.data.contentfulPage.sections : [],
      },
    })
  }
}
```

But by doing so I recieve the following warning in the console.

```cmd
warn Action createPage was called outside of its expected asynchronous lifecycle createPages in default-site-plugin.
Ensure that you return a Promise from createPages and are awaiting any asynchronous method
invocations (like graphql or http requests).
For more info and debugging tips: see https://gatsby.dev/sync-actions

File E:\...\gatsby-node.js:351:5
  349 |         : ""
  350 |
> 351 |     createPage({
      |     ^
  352 |       path: localeSlug,
```

Is there a better way for me to query data from contentful conditionally and avoid this warning?

### Environment (if relevant)

System:
OS: Windows 10 10.0.18362
CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Binaries:
Node: 10.16.2 - C:\Program Files\nodejs\node.EXE
npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
Languages:
Python: 3.7.3
Browsers:
Edge: 44.18362.449.0
npmPackages:
gatsby: ^2.23.0 => 2.23.0
gatsby-image: ^2.4.6 => 2.4.6
gatsby-plugin-antd: ^2.2.0 => 2.2.0
gatsby-plugin-less: ^3.2.3 => 3.2.3
gatsby-plugin-manifest: ^2.4.10 => 2.4.10
gatsby-plugin-offline: ^3.2.8 => 3.2.8
gatsby-plugin-react-helmet: ^3.3.3 => 3.3.3
gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
gatsby-plugin-sharp: ^2.6.10 => 2.6.10
gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1
gatsby-source-contentful: ^2.3.14 => 2.3.14
gatsby-source-filesystem: ^2.3.10 => 2.3.10
gatsby-source-instagram: ^0.7.2 => 0.7.2
gatsby-transformer-sharp: ^2.5.4 => 2.5.4
npmGlobalPackages:
gatsby-cli: 2.12.36

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by herecydev** [comment]
`forEach` is not async. Try using `for...of` and it should work just fine!

**Comment by zaidakhterr** [comment]
@herecydev Thank You. using `for...of` removes the warning.
