### ISSUE TITLE
Are Environment Variables secure for storing private keys or passwords?

### ISSUE THREAD

**Issue by Erythros** [gatsbyjs/gatsby#24846]
## Summary
Documentation about Environment Variables is confusing. Are these secure for storing private api-key / passwords? 
## Relevant information

I need a secure way of storing private api-keys and/or some passwords both for local development as well as after the app is deployed (in my case with Netlify, but it shouldn't matter).

From the [documentation](https://www.gatsbyjs.org/docs/environment-variables/#client-side-javascript) I get that both Project Env Vars and OS Env Vars (those prefixed with GATSBY_*) are client-side. Therefore, these would be exposed  publicly and thus insecure for storing confidential information.

What is the best way of dealing with this?

**Comment by LekoArts** [comment]
Thank you for opening this!

Environment variables are secure for storing your keys and access tokens. But you will never ever want to commit them to source control/GitHub and only set those in your CI/CD solution then or locally in an `.env` file. That's also what the documentation is explaining.

With Gatsby you're requesting everything at build time so your secrets are safe as the build artifacts won't contain this information. Set your keys in Netlify and you're fine.

But if you're prefixing them with `GATSBY_` and use them on the client-side, they are not safe. That's a problem unrelated to Gatsby and most of the times it's solved with middlewares/proxies between the requests, e.g. https://gomakethings.com/keeping-credentials-secure-when-making-api-calls-with-javascript/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
