### ISSUE TITLE
Always fetching data from 127.0.0.1:1337

### ISSUE THREAD

**Issue by sasidharank** [gatsbyjs/gatsby#24853]
Gatsby always fetching data from the localhost also I changed my API URL to the Heroku path.
- the plugin used `gatsby-source-strapi`
- done `gatsby-clean`
- updated API URL in gatsby plugin config

![image](https://user-images.githubusercontent.com/29498872/83969806-a8bf9780-a8ef-11ea-9ed8-b0817ad77666.png)

**Comment by sidharthachatterjee** [comment]
Hey @sasidharank 

Thank you for opening this! gatsby-source-strapi is maintained by the strapi folks over at https://github.com/strapi/gatsby-source-strapi though. Maybe open an issue there? 

Closing this one for now. Thanks and cheers!
