### ISSUE TITLE
Adding an ErrorBoundary to gatsby-image

### ISSUE THREAD

**Issue by schwartzmj** [gatsbyjs/gatsby#24855]
## Summary

Does it make sense to add an ErrorBoundary to gatsby-image by default?

### Motivation

If there's any sort of javascript error inside of gatsby-image, it will crash the entire app. Does it make any sense to have `Img` automatically wrapped in an ErrorBoundary so that the app doesn't crash and the only thing that gets affected is the `<Img />` component?

One example of it crashing is something simple like passing a null value into `fluid` or `fixed`.

For a normal HTML `<img />` element, the `img` element just wouldn't display anything because it has an empty src attribute.

**Comment by LekoArts** [comment]
Can you please explain the use case/motivation further here?

> One example of it crashing is something simple like passing a null value into fluid or fixed.

Your Gatsby build wouldn't let that pass as at the GraphQL stage Gatsby would complain about missing data. So when would `fluid`/`fixed` be `null`?

**Comment by schwartzmj** [comment]
My Shopify product didn’t have an image. It compiled and crashed the app in production.

**Comment by LekoArts** [comment]
I tried it locally and when I piped in a `null` to the `fluid`/`fixed` prop the development server showed an error overlay, the built app showed something in the console but kept working.

You should add a conditional to your component then when the data is sometimes there and sometimes missing.

I think https://github.com/gatsbyjs/gatsby/pull/25371 will also fix your issue.
