### ISSUE TITLE
Ability to set a timeout for gatsby-source-shopify plugin

### ISSUE THREAD

**Issue by TotomInc** [gatsbyjs/gatsby#24856]
## Description

On slow networks it is impossible to download all assets when there are a large amount of them due to slow network and the default timeout set to 30s.

### Steps to reproduce

There is no minimal reproduction link as it needs a Shopify store setup and a slow network.

I also don't want to make public my Shopify access-token for security reasons.

### Expected result

I should be able to define a maximum timeout myself on the configuration in order to develop my site.

### Actual result

I am not able to develop because of my slow network, which makes the gatsby server throwing an error and crashing.

```
ERROR #11321 PLUGIN

"gatsby-source-shopify" threw an error while running the sourceNodes lifecycle:

failed to process https://cdn.shopify.com/s/files/1/0403/0159/2737/products/<my-asset-name>.png

TimeoutError: Timeout awaiting 'request' for 30000ms

[...]

error Command failed with exit code 1.
```

### What I tried to do

- I tried to reduce the `paginationSize` option property of the `gatsby-source-shopify` plugin but it doesn't work, as this issue is related to images/videos assets and not Shopify JSON API.

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15 
    gatsby-image: ^2.4.5 => 2.4.5 
    gatsby-plugin-codegen: ^1.1.0 => 1.1.0 
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9 
    gatsby-plugin-offline: ^3.2.7 => 3.2.7 
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2 
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9 
    gatsby-plugin-styled-components: ^3.3.3 => 3.3.3 
    gatsby-source-filesystem: ^2.3.8 => 2.3.8 
    gatsby-source-shopify: ^3.2.10 => 3.2.10 
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3

**Comment by teleaziz** [comment]
Adding this to my env fixed it for me:
```
GATSBY_STALL_RETRY_LIMIT=6
GATSBY_STALL_TIMEOUT=60000
GATSBY_CONNECTION_RETRY_LIMIT=10
GATSBY_CONNECTION_TIMEOUT=60000
```
