### ISSUE TITLE
Warnings on installing Gatsby: 4 x Deprecated issues

### ISSUE THREAD

**Issue by clukeh** [gatsbyjs/gatsby#24859]
Hello,

Please be gentle - I am a Bash, Node, NPM and Gatsby newbie. However, Gatsby is so good that I am trying to learn new skills.

Set Up:
Mac OS 10.13.6
Node: 14.4.0
NPM: 6.14.5

I have loaded Node (& NPM). When I run the Gatsby global install I get four warnings (three near the start of the message and one near the end). Please does anyone have an idea of how to solve any one or, even better, all of these warnings? 

Many thanks in advance,

Luke (using Jill's computer!)

> Jill-Arrowsmiths-iMac:~ Jill$ npm install -g gatsby-cli
> **npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated**
> /Users/Jill/.nvm/versions/node/v14.4.0/bin/gatsby -> /Users/Jill/.nvm/versions/node/v14.4.0/lib/node_modules/gatsby-cli/lib/index.js
> 
> > websocket@1.0.31 install /Users/Jill/.nvm/versions/node/v14.4.0/lib/node_modules/gatsby-cli/node_modules/websocket
> > (node-gyp rebuild 2> builderror.log) || (exit 0)
> 
>   CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
>   SOLINK_MODULE(target) Release/bufferutil.node
>   CXX(target) Release/obj.target/validation/src/validation.o
>   SOLINK_MODULE(target) Release/validation.node
> 
> > core-js@2.6.11 postinstall /Users/Jill/.nvm/versions/node/v14.4.0/lib/node_modules/gatsby-cli/node_modules/core-js
> > node -e "try{require('./postinstall')}catch(e){}"
> 
> Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
> 
> The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> > https://opencollective.com/core-js 
> > https://www.patreon.com/zloirock 
> 
> Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
> 
> 
> > gatsby-telemetry@1.3.10 postinstall /Users/Jill/.nvm/versions/node/v14.4.0/lib/node_modules/gatsby-cli/node_modules/gatsby-telemetry
> > node src/postinstall.js || true
> 
> 
> > gatsby-cli@2.12.44 postinstall /Users/Jill/.nvm/versions/node/v14.4.0/lib/node_modules/gatsby-cli
> > node scripts/postinstall.js
> 
> Success!
> 
> Welcome to the Gatsby CLI! Please visit https://www.gatsbyjs.org/docs/gatsby-cli/ for more information.
> 
> **npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.**
> 
> + gatsby-cli@2.12.44
> added 990 packages from 691 contributors in 119.019s
> Jill-Arrowsmiths-iMac:~ Jill$

**Comment by clukeh** [comment]
Thanks Dana :)

**Comment by LekoArts** [comment]
Thank you for opening this!

The PR https://github.com/gatsbyjs/gatsby/pull/25158 will solve some of those warnings, updates we want to do to your dependencies in the near future will solve the others. For now you don't need to do anything as they are just warnings. The CLI and Gatsby will work as usual :)
With having packages that have dependencies and those dependencies have dependencies etc. these kind of things sometimes occur. We have an eye on this, so fear not!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by clukeh** [comment]
Thank you for that. I'll give it a go :-)
