### ISSUE TITLE
View docs locally

### ISSUE THREAD

**Issue by joshuacox** [gatsbyjs/gatsby#24857]
View docs locally.

## Summary

Regarding the warning on:
https://github.com/gatsbyjs/gatsby/tree/master/docs

```
We intend the docs to be read on gatsbyjs.org — You can read them here of course :-) Just be warned that links won't often work and other things will be missing or less than optimal.
```

And I'm left wondering why the docs directory isn't a valid gatsby site?

### Basic example

`cd docs; gatsby develop` peruse gatsby docs locally while offline.

### Motivation

Promote developers to get out of the house and into the sunshine and help their body develop vitamin D naturally.

In many cases, I find myself with my laptop, a clone of the gatsby repo, and some spare time out under a tree, but with no wifi etc.  I can read the markdown files directly, but it sure would be nice to be able to run `gatsby develop` inside of the [docs directory](https://github.com/gatsbyjs/gatsby/tree/master/docs) and render the wholes docs site locally.

**Comment by LekoArts** [comment]
Thank you for opening this!

After cloning our repository you can go to the [`www`](https://github.com/gatsbyjs/gatsby/tree/master/www) directory and run `npm install` & `npm run develop` to see the website locally. I'd highly recommend setting the [screenshot placeholder](https://github.com/gatsbyjs/gatsby/tree/master/www#running-slow-build-screenshots-placeholder) to have quicker build times. The initial build will take a while.

Moreover, our .org site is a PWA with offline functionalities so you can install it (Chrome will show a "+" sign in the URL bar) and the pages you browsed while being online then will be stored for offline usage.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
