### ISSUE TITLE
Passing id prop to component with useStaticQuery

### ISSUE THREAD

**Issue by dkjess** [gatsbyjs/gatsby#24861]
In an effort to write some nice looking code, I am trying to run simple graphql queries that only return the ids and then pass those ids to a component with its own graphql query for getting the data the component needs. But for some reason, the id is never passed to the query and I end up with an `TypeError: Cannot read property 'company' of undefined` error.

```import React from 'react'
import styled from 'styled-components'
import {Link, useStaticQuery, graphql} from 'gatsby'

const Wrapper = styled(Link)`
    display: block;
    border-bottom: 1px solid ${props => props.theme.colors.lightGrey};
    padding: 16px 0;
`
const Title = styled.span`
    display: block;
    font-size: ${props => props.theme.fontSizes.three};
`

interface Props {
    id?: string
}

function JobSnippet ({id}:Props) { 
    const data = useStaticQuery(graphql`
        query JobSnippetQuery($id: ID) {
            gcms {
                job(where: { id: $id }) {
                    slug
                    title
                    description
                    category
                    jobType
                    location
                    publishedAt
                    company {
                        name
                        slug
                    }
                }
            }
        }
    `)
    
    const LinkPath = `/${data.job.company.slug}/${data.job.slug}`

    return (
        <Wrapper to={LinkPath}>
            <Title>{data.job.title}</Title>
            <p>{data.job.publishedAt}</p>
        </Wrapper>
    )
}

export default JobSnippet```

**Comment by LekoArts** [comment]
Thank you for opening this!

Static Queries have a known limitation in that they don't support variables:
https://www.gatsbyjs.org/docs/use-static-query/#known-limitations

You can follow this issue to see when it's resolved: https://github.com/gatsbyjs/gatsby/issues/10482

For your particular instance I'd suggest querying your data at the page level and then pass the data into the components itself.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by dkjess** [comment]
Thanks. Will follow the main issue on the topic.
