### ISSUE TITLE
gatsby-plugin-less alias without tilde

### ISSUE THREAD

**Issue by minimit** [gatsbyjs/gatsby#24867]
I need less alias without tilde, it's supported in [less-loader version 6](https://github.com/webpack-contrib/less-loader/releases/tag/v6.0.0)

Is it possible to update gatbsy-plugin-less less-loader to version 6.1.0? thanks

**Comment by LekoArts** [comment]
Since the breaking changes are among other things:

> minimum supported Node.js version is 10.13,
> minimum support webpack version is 4

It's fine to upgrade it. We'd be happy to accept a PR from you!

**Comment by minimit** [comment]
I can do it, should i commit a fix or a feat?
