### ISSUE TITLE
Feature Request to integrate YoastSEO plugin

### ISSUE THREAD

**Issue by tomakali** [gatsbyjs/gatsby#24870]
Integrating a popular plugin to this CMS will help webmaster to leverage a lot of features.

  Useful Links:
  - [https://yoast.com/yoast-seo-platforms/your-platform/](url)

**Comment by LekoArts** [comment]
Thank you for opening this!

You can use https://github.com/ashhitch/wp-graphql-yoast-seo to access Yoast information in WPGraphQL. WPGraphQL is needed for https://www.gatsbyjs.org/packages/gatsby-source-wordpress-experimental/ which soon will be the default for v4. You can find some documentation here: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/feat/docs/README.md

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
