### ISSUE TITLE
[gatsby-transformer-remark] How to customize the class asociated to <table><th> elements when parsking markdown tables

### ISSUE THREAD

**Issue by cangulo** [gatsbyjs/gatsby#24881]
Let's say I have the next code in MD

```markdown
| command | description |
| ------- | ----------- |
| item 1  | item 1      |
| item 2  | item 2      |
```

Which will be parsed into the next HTML using the gatsby-transformer-remark plugin:

```html
<table>
	<thead>
		<tr>
		<th>command</th>
		<th>description</th>
		</tr>
	</thead>
	<tbody>
		<tr>
		<td>item 1</td>
		<td>item 1</td>
		</tr>
		<tr>
		<td>item 2</td>
		<td>item 2</td>
		</tr>
	</tbody>
</table>
```

How can I customize the gatsby-transformer-remark plugin to add a class in all the table HTML elements as <table>,<thead>,etc (e.g. <table class="custom-class">) ?

I would like to customize the table style of the output HTML to be the same as the GitHub:

![image](https://user-images.githubusercontent.com/23151731/84088005-bf4b1900-a9eb-11ea-8517-4fd9e5868a17.png)

What I have now is:

![image](https://user-images.githubusercontent.com/23151731/84088100-0afdc280-a9ec-11ea-9927-4af155b54358.png)

Thanks in advance! :)

**Comment by capndave** [comment]
Have you checked out [gatsby-remark-classes](https://www.gatsbyjs.org/packages/gatsby-remark-classes/)? I think that will do it for you.

**Comment by cangulo** [comment]
I will check it. Thanks :)
