### ISSUE TITLE
New version of gatsby throws when context is null

### ISSUE THREAD

**Issue by Austaras** [gatsbyjs/gatsby#24884]
https://github.com/gatsbyjs/gatsby/blob/64858b12b34a3fab45b1bb06a6b65803231569e2/packages/gatsby/src/redux/actions/public.js#L195

this line will throw when context is null, revert back to `_.isObject` will fix it

**Comment by Austaras** [comment]
I'm a bit occupied lately so @ascorbic  is there any specific reason to change this and if not could you open a pr and revert it?

**Comment by ascorbic** [comment]
Thanks for spotting this
