### ISSUE TITLE
gatsby-plugin-google-gtag: optimize_id shouldn't be submitted to GOOGLE_AD_WORDS config in 

### ISSUE THREAD

**Issue by Odelya** [gatsbyjs/gatsby#24885]
## Description

gatsby-plugin-google-gtag - optimize_id should only be sent to analytics.js and not to other platforms like google ad words

### Steps to reproduce

Add the following code:

```
{
      resolve: 'gatsby-plugin-google-gtag',
      options: {
        trackingIds: [
          'AW-GOOGLE_AD_WORDS',
          'UA-GOOGLE_ANALYTICS',
        ],
        gtagConfig: {
          anonymize_ip: false,
          optimize_id: 'GTM-CONTAINER',
        },
        pluginConfig: {
          head: true,
          respectDNT: false,
        },
      },
    },
```
### Expected result

` gtag('config', 'AW-GOOGLE_AD_WORDS', {"anonymize_ip":false,"send_page_view":false});gtag('config', 'UA-GOOGLE_ANALYTICS', {"anonymize_ip":false,"optimize_id":"GTM-CONTAINER","send_page_view":false});`

What should happen?

`optimize_id` shouldn't be sent to AW-GOOGLE_AD_WORDS

### Actual result

`gtag('config', 'AW-GOOGLE_AD_WORDS', {"anonymize_ip":false,"optimize_id":"GTM-CONTAINER","send_page_view":false});gtag('config', 'UA-GOOGLE_ANALYTICS', {"anonymize_ip":false,"optimize_id":"GTM-CONTAINER","send_page_view":false});`

### Environment

```
  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.8.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 3.7.3 
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 74.0.1
    Safari: 12.0.2
  npmGlobalPackages:
    gatsby-cli: 2.6.2
```

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
