### ISSUE TITLE
Unable to run command "npm i -g powerbi-visuals-tools"

### ISSUE THREAD

**Issue by surendrasai** [gatsbyjs/gatsby#24919]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by surendrasai** [comment]
I am trying to install pbiviz package, but I am getting attached error.

My Node Version is 13.7, what steps I need to perform to run PBIVIZ.

**Comment by connorlindsey** [comment]
This seems to be completely unrelated to Gatsby, so I'm going to close this issue. I would recommend reaching out to the relevant community for the `powerbi-visuals-tools` npm package.
