### ISSUE TITLE
tinysearch in Gatsby

### ISSUE THREAD

**Issue by dioptre** [gatsbyjs/gatsby#24911]
I'd love to see support for https://endler.dev/2019/tinysearch/ in Gatsby.

**Comment by LekoArts** [comment]
Thank you for opening this!

This isn't something we'll tackle so feel free to implement this on your own following our instructions on how to build a Gatsby plugin: https://www.gatsbyjs.org/docs/creating-plugins/

Or see if you can find people in our communities that would be interested in building this :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
