### ISSUE TITLE
[gatsby-image] prefer webp when browser support is given

### ISSUE THREAD

**Issue by Fetten** [gatsbyjs/gatsby#2491]
I played around with the new gatsby-image for a while now and the implementation and performance is (as Gatsby itself) absolutely great!

Anyhow, I'm thinking of an enhancement where the image component would prefer webp files over jpg and png when browser support is given, to increase loading-performance even further. A quick outline of the feature implementation could be:

1. Provide **additional** sizes/resolutions to the Image component (e.g.`preferredSizes` or `webpSizes` prop)
2. Image checks if [webp is supported by the browser](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/img/webp.js)
3. Image loads webp files or falls back to default sizes/resolutions.

I know this is a very specific case, so I'm not quite sure if this is a good way to go.

Let me know what you think please. Would love to contribute.

**Comment by TomiTakussaari** [comment]
I have been using something like this to use webp images when supported, no need for JS.

```graphql
image {
    childImageSharp {
        webPImage: responsiveSizes(maxWidth: 1425, maxHeight: 500, toFormat: WEBP) {
            srcSet
        }
        normalImage: responsiveSizes(maxWidth: 1425, maxHeight: 500) {
            base64
            src
            srcSet
        }
    }
}


```

```jsx
<picture>
    <source media="all" srcSet={this.props.webPImageSrcSet} type="image/webp"/>
    <img src={this.props.imageSrc} srcSet={this.props.imageSrcSet}
         alt={this.props.alt + " logo"} style={imageStyle}/>
</picture>
```

So browsers that understand WebP use that, and others use plain old image tag.

**Comment by Fetten** [comment]
Thank you Tomi for your solution!

I was thinking of using the picture element in the first place, but see some disadvantages:
1. The additional `picture`and `source` tags increase the html output (I know, this is pretty micro, but I'm trying to safe bytes where possible :) )
2. We cannot use the gatsby-image component here, because it wraps a div around the `img` tag and have to give up on features like lazy-loading.

If you are not using gatsby-image at all, your solution is absolutely the way to go. But my goal is to extend the gatsby-image component itself.

Other opinions?

**Comment by KyleAMathews** [comment]
Hey @Fetten! Glad you're enjoying gatsby-image!

Agree that adding support for webp would be awesome! And yeah, a client-side check with gatsby-image would be pretty straightforward to do.

Would love it if you want to work on a PR for this!

The steps to get this in would be roughly:

1. Add support for webp to gatsby-plugin-sharp and gatsby-transformer-sharp
2. Add a new fragment for adding webp support (this is my initial thought as I assume adding webp would increase time on building images as you'd double the count of image thumbnails you're creating + if I recall correctly, webp is much slower to create vs. jpeg/png).
3. Add support to gatsby-image. Basically a) check if webp in data, b) check if browser supports webp, and c) use webp srcSet instead of jpeg/png version

**Comment by KyleAMathews** [comment]
This would be really cool though — webp saves quite a bit of bandwidth and is ideal to support for image-heavy Gatsby sites.

**Comment by Fetten** [comment]
Thanks for liking the idea @KyleAMathews!

I created a working version with the following changes:
* add new fragments in gatsby-transformer-sharp with additional `srcWebp` and `srcSetWebp` fields
* create additional webp files in gatsby-plugin-sharp
* use `srcWebp` and `srcSetWebp` in gatsby-image if browser supports webp

The only thing that bothers me is that webp images are always created now, wether you need them or not, due to how gatsby-plugin-sharp works. This increases image build time as expected.

I'm also unsure if the new fragment names (`GatsbyImageSharpSizes_withWebp` ...) could be better :)

**Comment by KyleAMathews** [comment]
PR merged so closing this.
