### ISSUE TITLE
gatsby-config.js is called twice

### ISSUE THREAD

**Issue by muuvmuuv** [gatsbyjs/gatsby#24928]
## Description

Running `develop` calls `gatsby-config.js` twice. I am showing some "Welcome" message in my gatsby config with some information, having them printed twice doesn't look pretty nice and I think it is not necessary to get it twice anyway.

### Steps to reproduce

1. Install any starter
2. Add a console log
3. Run `gatsby develop`

### Expected result

Run once

### Actual result

Run twice

### Environment

<details>
<summary>Details</summary>

```
  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.97
    Edge: 83.0.478.45
    Firefox: 76.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.23.3 => 2.23.3
    gatsby-plugin-bundle-stats: ^2.2.0 => 2.2.0
    gatsby-plugin-canonical-urls: ^2.3.4 => 2.3.4
    gatsby-plugin-catch-links: ^2.3.5 => 2.3.5
    gatsby-plugin-layout: ^1.3.4 => 1.3.4
    gatsby-plugin-manifest: ^2.4.11 => 2.4.11
    gatsby-plugin-mdx: ^1.2.15 => 1.2.15
    gatsby-plugin-offline: ^3.2.9 => 3.2.9
    gatsby-plugin-pnpm: ^1.2.5 => 1.2.5
    gatsby-plugin-preact: ^4.0.3 => 4.0.3
    gatsby-plugin-react-helmet-async: ^1.0.17-0 => 1.0.17-0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-generator: ^1.0.5 => 1.0.5
    gatsby-plugin-remove-trailing-slashes: ^2.3.5 => 2.3.5
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1
    gatsby-plugin-sass: ^2.3.4 => 2.3.4
    gatsby-plugin-sharp: ^2.6.11 => 2.6.11
    gatsby-plugin-simple-analytics: ^1.0.3 => 1.0.3
    gatsby-plugin-sitemap: ^2.4.5 => 2.4.5
    gatsby-remark-autolink-headers: ^2.3.5 => 2.3.5
    gatsby-remark-check-links: ^2.1.0 => 2.1.0
    gatsby-remark-copy-linked-files: ^2.3.5 => 2.3.5
    gatsby-remark-embedder: ^2.1.1 => 2.1.1
    gatsby-remark-images: ^3.3.10 => 3.3.10
    gatsby-source-filesystem: ^2.3.11 => 2.3.11
    gatsby-transformer-json: ^2.4.5 => 2.4.5
    gatsby-transformer-sharp: ^2.5.5 => 2.5.5
  npmGlobalPackages:
    gatsby-cli: 2.12.29
```
</details>

**Comment by LekoArts** [comment]
Thank you for opening this!

I think you're using the wrong lifecycle to post your message then as we won't change our internal behavior (during `gatsby develop`) to mitigate such issue. I think you should use the `onPreBootstrap` lifecycle as it's called once before the loading of the config: https://www.gatsbyjs.org/docs/node-apis/#onPreBootstrap

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by ar7casper** [comment]
@muuvmuuv Did you manage to find out why / how?
I have a similar issue and it overrides data on the second time

**Comment by junhan-z** [comment]
+1 that I loaded an external script and it got called twice. Note it is not a problem for local with `gatsby develop` but once I deployed, the script will be called twice somehow.

**Comment by TildeWill** [comment]
Also having this issue when deploying. `gatsby-config.js` is getting required twice which causes a date-sensitive constant to change, which makes my assetPrefix incorrect.
