### ISSUE TITLE
Reverse proxy a single gatsby page 

### ISSUE THREAD

**Issue by vai0** [gatsbyjs/gatsby#24939]
# Summary

We have an nginx server one layer above another server that hosts the Gatsby assets. We want to have `mydomain.org` reverse proxy the assets from `mydomain.com/org`, with the end result being that users visiting mydomain.org will see the page hosted at our other domain `mydomain.com/org`

This is what we have so far:

```nginx
#  ngnix/vhost-mydomain.org.conf
server {
  server_name mydomain.org www.mydomain.org;
  
  # for mydomain.org, reverse proxy the html page at mydomain.com/org
  location = / {
    proxy_pass http://server-with-gatsby-assets:9000/org;
  }
  
  # for all other things (gatsby .json and .js assets for that /org page) 
  location / {
    proxy_pass http://server-with-gatsby-assets:9000;
  }
}
```
which gets us 90% there.

However, whats happening is if we visit `mydomain.org`, its actually going to `mydomain.org/org`.

What seems to be happening is Gatsby's router is modifying the url path, i'm guessing doing a `window.history.replaceState()` or `pushState` call and tacking a `/org`. This behavior can be verified by disabling Javascript which ensures this no longer happens.

What I can initially think of as a hacky solution is to call a `window.history.replaceState("/")` on `componentDidMount` to remove the `/org`.

The question is - is there a suggested method for reverse proxy'ing a single Gatsby page?

**Comment by wardpeet** [comment]
@vai0 are you using path-prefix by any chance?

**Comment by vai0** [comment]
@wardpeet I am not

**Comment by jamo** [comment]
You might want to add `proxy_redirect off;` to the proxy_pass. a `curl -v` or from browser devtools `copy as curl` might help better understand the issue at hand. (or a full example but that might be tedious to set up)

**Comment by jamo** [comment]
Something in the example and original message still confuses me, you can btw also do location blocks based on the extension:
```
location ~* .(js|json)$ {

}```

**Comment by LekoArts** [comment]
Please create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

[reproduction]: https://gatsby.dev/reproduction

**Comment by TylerBarnes** [comment]
Hi @vai0,

I'm closing issue this issue due to no reproduction being posted within 7 days.
Once you have a minimal reproduction feel free to re-open this issue and we'll be happy to take another look. 💜 

Thank you!
