### ISSUE TITLE
<html><head></head></html> appeared when html presents in markdown

### ISSUE THREAD

**Issue by 3axap4eHko** [gatsbyjs/gatsby#2493]
I'm using `html` tags in page markdown file, and html generated incorrect
```
<a href="https://ru.wikipedia.org/wiki/%D0%A7%D0%B0%D1%81%D1%82%D0%BE%D1%82%D1%8B_%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8_%D1%84%D0%BE%D1%80%D1%82%D0%B5%D0%BF%D0%B8%D0%B0%D0%BD%D0%BE" target="_wiki">частоты настройки фортепиано</a>
```
replaced to
```
<html><head></head><body><a href="https://ru.wikipedia.org/wiki/%D0%A7%D0%B0%D1%81%D1%82%D0%BE%D1%82%D1%8B_%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8_%D1%84%D0%BE%D1%80%D1%82%D0%B5%D0%BF%D0%B8%D0%B0%D0%BD%D0%BE" target="_wiki"></a></body></html>
```
this happens with every html tag inside markdown

**Comment by KyleAMathews** [comment]
You can't add html/head/body to markdown in Gatsby as those are handled by Gatsby and everything in the markdown is put within the body.

**Comment by 3axap4eHko** [comment]
I DID NOT ADD! This tags added by remark when any html tag presents in markdown. Se the example!

**Comment by KyleAMathews** [comment]
Not really sure what the problem is… could you build a small site reproducing the problem and push it to GitHub?

**Comment by 3axap4eHko** [comment]
Could you take a look at sources of this page view-source:https://potofcode.com/2017/09/diy-pianoduino
there are a few tags html inside

**Comment by 3axap4eHko** [comment]
this is a part of markdown:
```
Если вы хотите настроить другие ноты, то можете воспользоваться таблицей 
<a href="https://ru.wikipedia.org/wiki/%D0%A7%D0%B0%D1%81%D1%82%D0%BE%D1%82%D1%8B_%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8_%D1%84%D0%BE%D1%80%D1%82%D0%B5%D0%BF%D0%B8%D0%B0%D0%BD%D0%BE" target="_wiki">частоты настройки фортепиано</a>
```
so you can try to find this string in the page sources `частоты настройки фортепиано` it should be inside of `a` tag, but it does not

**Comment by 3axap4eHko** [comment]
@KyleAMathews did you have a chance to see that?

**Comment by 3axap4eHko** [comment]
Also I found issue with `gastby-blog-starter` that some `html` pages was not rendered. If you clone `gastby-blog-starter` locally and open file `/public/hi-folks/index.html` you will not see any content from the markdown file
