### ISSUE TITLE
Graph QL : Gatsby Strapi Media library integration issue

### ISSUE THREAD

**Issue by shivaping** [gatsbyjs/gatsby#24949]
I have a Strapi article defined with Media asset which has Alt text and Caption to the Media library. 

Now, when i pull the Strapi articles into gatsby i don't see the gatsby image sharp is pulling the File Name, alt text and caption for images. Please see the below screenshot for more details

![image](https://user-images.githubusercontent.com/13598222/84492501-dfb4f500-acc3-11ea-8939-2e0ea7e50b24.png)

**Comment by LekoArts** [comment]
Hey, thanks for the issue! We don't maintain the plugin so please open this on https://github.com/strapi/gatsby-source-strapi. Thanks!
