### ISSUE TITLE
Where is gatsby-starter-blog without TypeScript?

### ISSUE THREAD

**Issue by hugo-a-garcia** [gatsbyjs/gatsby#24950]
Hi

Where can I find a gatsby-starter-blog without TypeScript please?
Is there a separete official gatsby-starter-blog that can be cloned?

thanks in advance

-H

**Comment by LekoArts** [comment]
Thank you for opening this!

You can delete the `using-typescript` page and be fine with it. Gatsby ships with TS support by default now so there is no version without TS. But you don't have to use it! :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by hugo-a-garcia** [comment]
hi

Thank you for the reply.

I am trying to find an old index.js in the repository history so I can replace index.tsx and have a starter blog without TypeScript. 

Currently 

gatsby new gatsby_blog https://github.com/gatsbyjs/gatsby-starter-blog.git

creates a starter with typescript. Unfortunately, some of us are not ready to evolve to using TypeScript.
