### ISSUE TITLE
Is it possible to use pedantic conditional depend of folder?

### ISSUE THREAD

**Issue by pacocom** [gatsbyjs/gatsby#24951]
```
folder
  old
    file1.md
    file2.md
  new
    file3.md
    file4.md
```

I want to use pendantic: true to "old" folder and pedantic: false to "new" folder:

Current `gatsby-config.js`:
```
resolve: 'gatsby-transformer-remark',
      options: {
        gfm: true,
        commonmark: true,
        footnotes: true,
        pedantic: true,
    }
```

Thanks!

**Comment by LekoArts** [comment]
Thank you for opening this!

You can't have multiple instances of this transformer in the same gatsby-config.js and therefore you can't use it depending on the folder itself. Sidenote: The documentation says that `pedantic` will be removed in the future: https://github.com/remarkjs/remark/tree/master/packages/remark-parse#optionspedantic

So sorry, this isn't possible.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
