### ISSUE TITLE
MDX defaultLayout is not applied

### ISSUE THREAD

**Issue by zeekrey** [gatsbyjs/gatsby#24955]
# Summary
I tried to follow the guide at [gatsbyjs.org](https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/#default-layouts) and implement a defaultLayout. I don't know why, but the referenced defaultLayout isn't applied.

## Relevant information

Here is a codesandbox: https://codesandbox.io/s/mdx-provider-test-2-y02hm

### File contents

gatsby-config.js
```
module.exports = {
  plugins: [
    {
      resolve: "gatsby-plugin-mdx",
      options: {
        defaultLayouts: {
          default: require.resolve("./src/components/Layout.jsx")
        }
      }
    },
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "blog",
        path: `${__dirname}/src/blog/`
      }
    }
  ]
};
```

From the page template:
```
export default function Post({ data }) {
  const {
    mdx: { body }
  } = data;

  return <MDXRenderer>{body}</MDXRenderer>;
}
```

From the MDX defaultLayout:
```
import React from "react";
import { MDXProvider } from "@mdx-js/react";
import { ExternalLink } from "../components/ExternalLink";

const shortcodes = {
  ExternalLink: function({ children, href, ...props }) {
    return (
      <ExternalLink href={href} {...props}>
        {children}
      </ExternalLink>
    );
  }
};

export default props => (
  <>
    <div>Hello from my default layout</div>
    <MDXProvider components={shortcodes}>
      <main {...props} />
    </MDXProvider>
  </>
);
```

**Comment by jzabala** [comment]
Hi @zeekrey, I had the same problem and turns out that the `defaultLayout` is applied only if the extension of the page `component` is `.mdx`. In your case it is `.jsx`:

```js
const blogPostTemplate = require.resolve(`./src/components/Post.jsx`);
```

Check this [issue](https://github.com/gatsbyjs/gatsby/issues/23227#issuecomment-615570758) to learn more.

**Comment by zeekrey** [comment]
> Hi @zeekrey, I had the same problem and turns out that the `defaultLayout` is applied only if the extension of the page `component` is `.mdx`. In your case it is `.jsx`:
> 
> ```js
> const blogPostTemplate = require.resolve(`./src/components/Post.jsx`);
> ```
> 
> Check this [issue](https://github.com/gatsbyjs/gatsby/issues/23227#issuecomment-615570758) to learn more.

Thank you @jzabala for referencing the issue links. Just changing the extansion is unfortunately not enough. 😢  As described in [#23227](https://github.com/gatsbyjs/gatsby/issues/23227#issuecomment-615570758) we also need to provide it to the createPage function. In this case I won't use the mdx layout and shortcode function at all and stay with importing the components manually.
