### ISSUE TITLE
Dynamic GraphQL Queries

### ISSUE THREAD

**Issue by gvargash** [gatsbyjs/gatsby#24969]
Hello, I have the following lines to consult my images, is it possible to pass a variable to make the most dynamic queries?
In this case I am passing `name `as property, however this is not working.

```jsx
import React from "react"
import { useStaticQuery, graphql } from "gatsby"
import Img from "gatsby-image"

const Logo = ({name}) => {
  const data = useStaticQuery(graphql`
    query {
      placeholderImage: file(relativePath: { eq: ${name} }) {
        childImageSharp {
          fluid(maxWidth: 300) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
  `)
  return <Img fluid={data.placeholderImage.childImageSharp.fluid} />
}

export default Logo
```

**Comment by lannonbr** [comment]
This is not currently possible as StaticQuery cannot take any kind of variable (interpolated strings or GraphQL variables). There's already discussion on this in #10482. Closing this issue.
