### ISSUE TITLE
Build Succeeds but deployed site has error

### ISSUE THREAD

**Issue by btbjosh** [gatsbyjs/gatsby#2496]
Hello,

Just as the title says, my site is running fine in dev mode and builds (locally) to completion, however once deployed (currently deployed manually at netlify) I see the following error.

I am using the `gatsby-starter-default` starter created with `gatsby new`.

```
Uncaught Error: Cannot find module "gatsby-module-loader?name=component---src-templates-article-js!/Users/joshweaver/Documents/BtB Current/Documentation/Static/rollcall-docs/src/templates/article.js"
    at async-requires.js:5
    at Object.166 (async-requires.js:5)
    at t (bootstrap ff971473c0c889c97952:52)
    at Object.0 (production-app.js:16)
    at t (bootstrap ff971473c0c889c97952:52)
    at window.webpackJsonp (bootstrap ff971473c0c889c97952:23)
    at app-43a42bdd9167f8645c1f.js:1
```

Any ideas?

**Comment by KyleAMathews** [comment]
Looks like you hard-coded the absolute path to your template file.

Use `path.resolve` instead.

**Comment by btbjosh** [comment]
Thanks for the quick response!

I actually am using that pattern (which I used in my last site that was creating pages the same way, yet the only difference was that my previous site was `.jsx` files instead of this one being a `js`).

`const articlePage = path.resolve("src/templates/article.js");`

**Comment by KyleAMathews** [comment]
Grep your code for `/Users/joshweaver/Documents/`.

Somehow or another a path from your local computer is showing up on Netlify which means it has to be in your code somewhere.

**Comment by btbjosh** [comment]
Well it's odd because I just cloned my repo and ran `npm install` to check if it was something to do with any of my dependencies (before your last response). 

The netlify build still showed the error in the console.

So I ran `npm install gatsby-module-loader` just for kicks, and built it again. Manual deploy to netlify shows a 100% functional site now. 🤔 

https://rollcalldocs.netlify.com/

Also, I just ran a search on my dev folder and the only references to `/Users/joshweaver/Documents/...` are in internal gatsby api files.

**Comment by KyleAMathews** [comment]
Perhaps you checked in `.cache`

**Comment by 3CordGuy** [comment]
(Back to my personal account -- Still at the office)

Double-checked that just now.
```
# Project dependencies
# https://www.npmjs.org/doc/misc/npm-faq.html#should-i-check-my-node_modules-folder-into-git
node_modules
.cache/
# Build directory
public/
.DS_Store
yarn-error.log
```

Not sure if these issues are related but I just saw someone else reported `gatsby-module-loader` reference issue here: [#2358 ](https://github.com/gatsbyjs/gatsby/issues/2358)

**Comment by 3CordGuy** [comment]
Knowing `gatsby-module-loader` is a direct dependency of `gatsby`... I just uninstalled and reinstalled `gatsby` .... again... And it resolved this.

**Comment by jblok** [comment]
`npm uninstall gatsby` and then `npm install gatsby` worked for me
