### ISSUE TITLE
Is there a way to change siteMetadata programmatically at onPreInit lifecycle?

### ISSUE THREAD

**Issue by theowenyoung** [gatsbyjs/gatsby#24967]
## Summary

Hi everyone, Like the title, I want to know is there a way to change siteMetadata programmatically 
at `onPreInit` lifecycle?

I need to fetch a siteMetadata config from a remote url,  I want to use gatsby plugin to change the siteMetadata info.

I know there is another way to change it, I can write a script to get the remote config before gatsby build, but I just want to know if there is a way to change siteMetadata programmatically.

Thanks.

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Thank you for opening this!

As you already mentioned there is the possibility to call the API and create a local file in a step before `gatsby develop/build` and that is still the only working solution as the gatsby-config.js file is run synchronously so you can't call your API there. Or you use environment variables to populate the entries.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by ZeldOcarina** [comment]
I think this is very important and there's no reason to not support something this simple. Is there any workaround two years later?
