### ISSUE TITLE
Any way to see running queries?

### ISSUE THREAD

**Issue by fatihky** [gatsbyjs/gatsby#24974]
## Summary
Hi, I had created a resolver for dynamically fetching data for a field from external source (video durations from youtube). When I run `gatsby develop` command, it was stucking at `run queries` step. I could not find the hanging query.

So I cloned your repo and did something like this:
```
mv node_modules/gatsby node_modules/gatsby.backup
ln -s ../../my-works/gatsby/packages/gatsby node_modules/gatsby
```
I wanted to use my local copy to find hanging query. Somehow, I got something like:
```
Warning: Query is taking too long time

...fields
duration
^
...other fields
```
So I got the problem: My resolver was failing.

My request is, if possible, to be able to see started and finished queries with hooks (`gatsby-[node|browser ...].js`) or logs (`DEBUG` environment variable).

**Comment by LekoArts** [comment]
Thank you for opening this!

We have the section "Performance Tracing" on our docs: https://www.gatsbyjs.org/docs/performance-tracing/

In a paragraph it mentions:

> In addition, Gatsby has additional tracing for GraphQL resolvers. This traces every resolver and might have performance impact, so it’s disabled by default. You can enable it with --graphql-tracing argument for the build command.

This refers to the flag on the `build` command:
https://www.gatsbyjs.org/docs/gatsby-cli/#build

This should give you the information you need! :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
