### ISSUE TITLE
setWebpackConfig({ externals }) Not Working

### ISSUE THREAD

**Issue by gchallen** [gatsbyjs/gatsby#24977]
## Description

Attempting to configure webpack externals fails.

```jsx
actions.setWebpackConfig({ externals: {} })
```
Results in the following error:

```sh
ERROR

There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html SyntaxError: Unexpected token '.'

  WebpackError: SyntaxError: Unexpected token '.'
  - build-html.ts:127 doBuildPages
    [gatsby-theme-cs125]/[gatsby]/src/commands/build-html.ts:127:24
  - build-html.ts:147 buildHTML
    [gatsby-theme-cs125]/[gatsby]/src/commands/build-html.ts:147:3
  - develop-process.ts:121 createIndexHtml
    [gatsby-theme-cs125]/[gatsby]/src/commands/develop-process.ts:121:7
  - develop-process.ts:144 startServer
    [gatsby-theme-cs125]/[gatsby]/src/commands/develop-process.ts:144:3
  - develop-process.ts:448 module.exports
    [gatsby-theme-cs125]/[gatsby]/src/commands/develop-process.ts:448:39
```

(Obviously this is a silly example, since there is no need to override externals with an empty object. But trying to pass in a valid configuration object also fails.)

### Steps to reproduce

I encountered this when working in an existing project and trying to configure webpack to exclude certain libraries from the client bundle that are only used during SSR. I attempted to produce a MWE but couldn't get it to fail.

However, I suspect the problem here is how attempts to override externals are interacting with Gatsby's default webpack configuration. Based on [these lines](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L610), Gastby configures its own externals to avoid certain packages during certain build stages. I suspect that my full example is using one of those packages, and, that failing to correctly exclude it causes webpack to try to import a file from a package that it doesn't understand how to parse, leading to the (fairly cryptic error) shown above. My MWE must not have included the problematic package.

I don't know if this a problem with `webpack-merge` or with Gatsby, but it seems that the configuration provided by the project is not being merged properly with Gatsby's default. I'm not sure why.

The following workaround works, essentially performing a manual merge, with the additional complication that the default externals is not set during certain build stages:

```ts
const config = getConfig()
// We only use jsdom, cheerio, and ace-builds during SSR, so we don't want to include them in the
// client bundle. (Plus, jsdom will crash if run in the browser.)
const ourExternals = [/jsdom/, /cheerio/, /ace-builds/]
const externals = config.externals ? [...ourExternals, ...config.externals] : ourExternals
actions.setWebpackConfig({ externals })
```
### Expected result

The build should not fail.

### Actual result

The build fails.

### Environment

```
  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 5.0.17 - /opt/local/bin/bash
  Binaries:
    Node: 12.16.1 - ~/.asdf/installs/nodejs/12.16.1/bin/node
    npm: 6.13.4 - ~/.asdf/installs/nodejs/12.16.1/bin/npm
  Languages:
    Python: 3.8.2 - /Users/challen/.asdf/shims/python
  npmPackages:
    gatsby: 2.23.3 => 2.23.3
    gatsby-alias-imports: ^1.0.4 => 1.0.4
    gatsby-image: ^2.4.7 => 2.4.7
    gatsby-plugin-env-variables: ^1.0.2 => 1.0.2
    gatsby-plugin-graphql-codegen: ^2.7.1 => 2.7.1
    gatsby-plugin-manifest: ^2.4.11 => 2.4.11
    gatsby-plugin-material-ui: ^2.1.9 => 2.1.9
    gatsby-plugin-mdx: ^1.2.15 => 1.2.15
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.4
    gatsby-plugin-sass: ^2.3.4 => 2.3.4
    gatsby-plugin-sharp: ^2.6.11 => 2.6.11
    gatsby-plugin-typescript: ^2.4.6 => 2.4.6
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.10 => 1.1.10
    gatsby-source-filesystem: ^2.3.11 => 2.3.11
    gatsby-transformer-sharp: ^2.5.5 => 2.5.5
  npmGlobalPackages:
    gatsby-cli: 2.12.44
```

**Comment by wardpeet** [comment]
@gchallen Could you do a `JSON.stringify(actions.getConfig(), null, 2)` of your config. `setWebpackConfig` merges exclude, not replace it.

You also have `stage` where you can only apply your config on build-javascript or build-html.

Note that externals isn't the way to not include something in a bundle, it still needs to be available. You're probably looking to use null-loader or alias the package to a noop file.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
