### ISSUE TITLE
@wardpeet thanks for your reply. It is useful. Perhaps the best output from this issue would be some documentation outlining how to optimise for each of the metrics in the new Lighthouse. I am confident that our site feels fast to users and that Gatsby itself is doing a great job of optimising the site for real users. However if Google's web vitals are going to start informing page rank, getting a good lighthouse score is going to become mission-critical for most sites.

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#24970]
@wardpeet thanks for your reply. It is useful. Perhaps the best output from this issue would be some documentation outlining how to optimise for each of the metrics in the new Lighthouse (in the context of Gatsby). I am confident that our site feels fast to users and that Gatsby itself is doing a great job of optimising the site for real users. However if Google's web vitals are going to start informing page rank, getting a good lighthouse score is going to become mission-critical for most sites.

@Jimmydalecleveland we had a similar problem where we were needed to load in all the items of a resource so we could use data from within markdown to configure a filtwr (i.e. we couldn't filter using GraphQL) and optimised by using different fragments when loading a full resource  Vs when loading all resources for filtering. This greatly reduced our by Jason and therefore our bundle size.

@treyles you need to be careful delaying the load of Analytics as it can mean your stats are incomplete. For example it can mean your reported bounce-rate is not accurate. There are some scripts that marketing would not allow us to delay (pixel, analytics, hotjar and therefore tag manager), but others, e.g. Intercom are fine and are a worthwhile optimisation. In terms of how to delay these scripts, the scripts supplied by third-parties usually load async, but this alone is not enough. What you will probably need to do is replace these scripts with your own. Listen for window.load, then trigger the download. You need to be careful though as some scripts rely on window.load to initialise, and if you've used it to load the script, it will not fire again, so you need to initialise them manually. For example with Intercom we:
- removed the degault `<script>...</script>` supplied by Intercom.
- added a listener for `window.load`
- added a brief delay within this listener
- triggered a modified version Intercom's default script that loaded their lib async.
- polled to see when the script was loaded (Intercom doesn't provide a reliable event)
- manually initialised their script (which was done on page.load by their default script).

_Originally posted by @Undistraction in https://github.com/gatsbyjs/gatsby/issues/24332#issuecomment-643580233_

**Comment by wardpeet** [comment]
Seems like someone clicked the wrong button
