### ISSUE TITLE
Remove :warning: or replace with something better

### ISSUE THREAD

**Issue by Ildarik** [gatsbyjs/gatsby#24979]
Recently I added a warning block [here](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/#deploying-to-a-github-pages-subdomain-at-githubio). But I thought it renders some sort of exclamation visual mark. So we need to decide that to do:
1) remove `:warning:`
2) replace it with something that appeals more elegant visually. Didn't find in docs proper use cases

![Screenshot from 2020-06-13 21-57-10](https://user-images.githubusercontent.com/10713674/84576926-f1c88d80-adc0-11ea-8986-fc74033c69b5.png)

**Comment by LekoArts** [comment]
You can remove the `:warning:` :) On GitHub or Slack it would render to a ⚠️ but we don't have that on our website.
