### ISSUE TITLE
Gatsby Deployment on AWS Amplify

### ISSUE THREAD

**Issue by shotesmagotes** [gatsbyjs/gatsby#24980]
## Summary
I am encountering an issue deploying my site to AWS Amplify using custom domains. I have image assets, that are not rendering (not even requested) on the custom domain that I have added to my Amplify app. However, the images do show on the automatically generated amplifyapp url. I have opened an issue on the amplify-console github repo (https://github.com/aws-amplify/amplify-console/issues/754#issue-638102323) as well. 

I am using the following plugins to help with querying and transforming the image for my site:

    "gatsby-background-image": "^1.1.1",
    "gatsby-image": "^2.4.3",
    "gatsby-source-filesystem": "^2.3.10",
    "gatsby-plugin-sharp": "^2.6.2",
    "gatsby-transformer-sharp": "^2.5.2",

My gatsby-config.js includes among its plugins:

    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-transformer-remark`,
    `gatsby-plugin-layout`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-material-ui`,
    {
      resolve: `gatsby-source-filesystem`,
      options: { path: `./src/images/` }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages/`,
      },
    }

### Environment (if relevant)
  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 72.0.2
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.21.22 => 2.21.22 
    gatsby-background-image: ^1.1.1 => 1.1.1 
    gatsby-image: ^2.4.3 => 2.4.3 
    gatsby-plugin-layout: ^1.3.4 => 1.3.4 
    gatsby-plugin-mailchimp: ^5.1.2 => 5.1.2 
    gatsby-plugin-material-ui: ^2.1.9 => 2.1.9 
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.4 
    gatsby-plugin-sharp: ^2.6.2 => 2.6.2 
    gatsby-plugin-typography: ^2.5.1 => 2.5.1 
    gatsby-source-filesystem: ^2.3.10 => 2.3.10 
    gatsby-source-s3: 0.0.0 => 0.0.0 
    gatsby-transformer-remark: ^2.8.14 => 2.8.14 
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2 
  npmGlobalPackages:
    gatsby-cli: 2.12.45

### File contents (if changed)
`gatsby-config.js`:

```
module.exports = {
  siteMetadata: {
    title: ``,
    subTitle: ``,
    description: ``,
  },
  plugins: [
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-transformer-remark`,
    `gatsby-plugin-layout`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-material-ui`,
    {
      resolve: `gatsby-source-filesystem`,
      options: { path: `./src/images/` }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages/`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `mds`,
        path: `${__dirname}/data/`,
      },
    },
    {
      resolve: 'gatsby-plugin-mailchimp',
      options: {
        endpoint: ''
      },
    }
  ]
}

```

`package.json`: 
```
{
  "name": "gatsby-starter-hello-world",
  "private": true,
  "description": "A simplified bare-bones starter for Gatsby",
  "version": "0.1.0",
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1",
  },
  "dependencies": {
    "@material-ui/core": "^4.10.1",
    "bootstrap": "^4.5.0",
    "fontsource-source-sans-pro": "^2.1.3",
    "gatsby": "^2.21.22",
    "gatsby-background-image": "^1.1.1",
    "gatsby-image": "^2.4.3",
    "gatsby-plugin-layout": "^1.3.4",
    "gatsby-plugin-mailchimp": "^5.1.2",
    "gatsby-plugin-material-ui": "^2.1.9",
    "gatsby-plugin-react-helmet": "^3.3.4",
    "gatsby-plugin-sharp": "^2.6.2",
    "gatsby-plugin-typography": "^2.5.1",
    "gatsby-source-filesystem": "^2.3.10",
    "gatsby-source-s3": "0.0.0",
    "gatsby-transformer-remark": "^2.8.14",
    "gatsby-transformer-sharp": "^2.5.2",
    "react": "^16.12.0",
    "react-bootstrap": "^1.0.1",
    "react-dom": "^16.12.0",
    "react-helmet": "^6.1.0",
    "react-icons": "^3.10.0",
    "react-typography": "^0.16.19",
    "typeface-source-sans-pro": "^1.1.5",
    "typography": "^0.16.19",
    "typography-theme-fairy-gates": "^0.16.19",
    "typography-theme-github": "^0.16.19",
    "typography-theme-moraga": "^0.16.19"
  },
  "devDependencies": {
    "prettier": "^2.0.5"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-hello-world"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
```
`gatsby-browser.js`: 
```
import 'bootstrap/dist/css/bootstrap.min.css';
import "./src/styles/global.css"
import "typeface-source-sans-pro"
```

**Comment by LekoArts** [comment]
Thank you for opening this!

This doesn't seem to be related to an Gatsby issue but your deployment with AWS. Since you already created an issue on their end (https://github.com/aws-amplify/amplify-console/issues/754) I'll close this.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
