### ISSUE TITLE
Document scroll listeners work in dev, but not deployed on GH Pages?

### ISSUE THREAD

**Issue by tangert** [gatsbyjs/gatsby#2498]
Not sure why, but in my development environment my page scroll indicators and animations work flawlessly, but the moment I deployed to github pages it all went to shit. Any ideas?

**Comment by dardub** [comment]
Does a local build work? Can you elaborate on 

> all went to shit

**Comment by dardub** [comment]
Did you place the event listeners in componentDidMount?

**Comment by KyleAMathews** [comment]
Hey, closing out old issues. Please re-open if you have additional questions, thanks!
