### ISSUE TITLE
Custom Javascript not working 

### ISSUE THREAD

**Issue by zohaib055** [gatsbyjs/gatsby#24989]
I have a javascript function that I want to add into the custom html component 

but can't add  tried the below code but it's not working

  ```
<script
      dangerouslySetInnerHTML={{
        __html: `
                var name = 'world';
                console.log('Hello ' + name);
            `,
      }}
    />
```

**Comment by herecydev** [comment]
I don't think that's possible, you can read more about it here: https://stackoverflow.com/questions/37803559/react-js-how-to-get-script-inside-dangerouslysetinnerhtml-executed

Also this isn't really a Gatsby issue, that's something that react-dom will be handling. So it might be worth checking react for similar issues
