### ISSUE TITLE
Continue reading - Wordpress theme

### ISSUE THREAD

**Issue by Rakete2510** [gatsbyjs/gatsby#24994]
Hi,
I have downloaded the Wordpress theme for me. So far it workes fine. If i put a longer article on i can set up the number of words for the teaser. the theme shows a "continue reading" link which has to point to the article. Unfortunately it points the the same site. (e.g. if the site is names hamradio and the article is named radio1, it points to the hamradio site.)
if i klick on the Link to the article itself it points to the right target (the article)

can you give me a hint where i can fix that or even change the target of the "continue reading" link?

cheers
Lars

**Comment by LekoArts** [comment]
To what "Wordpress theme" are you referring to? Do you have a link?

**Comment by freiksenet** [comment]
Hi! 

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. 

Thanks!
