### ISSUE TITLE
yarn.lock in .gitignore

### ISSUE THREAD

**Issue by maciejmyslinski** [gatsbyjs/gatsby#2499]
Howdy! First of all, huge thanks for developing gatsby. I absolutely love it!

I find it strange that in gatsby project generated with `gatsby new`, `yarn.lock` file is listed in `.gitignore`. When we ignore this file, we do not reap benefits from it. It's not a good practice imo. What do you think? And is the current state an architectural decision or a mistake?

**Comment by KyleAMathews** [comment]
Yeah, that was a mistake :-)

Someone else pointed that out recently and I removed it https://github.com/gatsbyjs/gatsby-starter-default/commit/1c97a22de02b783aeca76dcd63a88dbf5abee716

Thanks! And glad to hear you're enjoying Gatsby!
