### ISSUE TITLE
Add nodemon to gatsby-admin dependencies

### ISSUE THREAD

**Issue by ehrencrona** [gatsbyjs/gatsby#25007]
## Summary

Add installation steps for `nodemon` in the "Install Node and Yarn" section

## Motivation

To set up the development environment, `nodemon` needs to be installed. Otherwise, you run into the following when running `yarn run watch`:

```$ yarn run watch
yarn run v1.21.0
$ lerna run watch --no-sort --stream --concurrency 999
lerna notice cli v3.22.0
...
gatsby-admin: $ nodemon --watch src --ext js,ts,tsx,json --exec "yarn run build"
...
gatsby-admin: /bin/sh: nodemon: command not found
...
gatsby-admin: error Command failed with exit code 127.
gatsby-admin: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is easily fixed by running `yarn global add nodemon` which I believe ought to be mentioned under [Install Node and Yarn](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/#install-node-and-yarn) in "Setting Up Your Local Dev Environment"

It's also possible this is a bug and nodemon is not supposed to be required. In that case, feel free to close or rewrite this ticket.

### Draft the doc

- [x] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [x] Open a [pull request](https://github.com/gatsbyjs/gatsby/pull/25008)

**Comment by LekoArts** [comment]
Thanks for the issue! This is indeed a bug and either nodemon shouldn't be used or added to the devDependencies. I'll let @mxstbr know.
