### ISSUE TITLE
[gatsby-transformer-remark] Get the number of line of front-matter

### ISSUE THREAD

**Issue by wdavidw** [gatsbyjs/gatsby#25010]
## Summary

I need to report errors and warnings with their associated line number from a markdown file. For example, "Targeted link at line 5 return 301". The problem is that the line number does not take into consideration the number of lines of the front-matter. It is quite easy to extract the markdown content line number from the AST but I haven't find any solution to obtain and the number of front-matter lines.

My target environment is a gatsby website using gatsby-transformer-remark which itself uses gray-matter [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/on-node-create.js#L28).

### Basic example

Here's an example:

```md
---
title: a title
---

go [here]('https://domain.com/does-no-exists')
```

The above should throw a message like "Targeted link at line 5 return 301" while instead it print "Targeted link at line 2 return 301". I know the line number in the content but I can't add the number of lines of the front-matter.

### Suggestion

The gray-matter module return a property called `matter` which is the raw content of the front-matter. From there, by splitting its value by lines, we could obtain the number of lines of the front-matter.

I propose to expose the `matter` property with a new property named `rawMarkdownFrontMatter`, the same way as we expose the gray-matter `content` property in `rawMarkdownBody`.

Note, I could provide a pull request if the proposal is relevant and accepted.

**Comment by LekoArts** [comment]
Yeah, feel free to send in a PR :)
