### ISSUE TITLE
bug(gatsby-source-npm-package-search): Add explicit GraphQL schema typings

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#25011]
##  Description

Add explicit typings to NpmPackage and NpmPackageReadme so that sites that use the plugin still work even if no sites match the search parameters:

```graphql
type NpmPackage implements Node {
  # add fields
}
```

### Steps to reproduce

1. Create a gatsby project using the `gatsby-source-npm-package-search` plugin
2. Configure it for a keyword that returns no search results
3. Create a page/static query that uses npm results
4. Build the site

Alternatively, run the source for gatsbyjs.org changing this line in `gatsby-config`: https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-config.js#L87

```
    {
      resolve: `gatsby-source-npm-package-search`,
      options: {
        keywords: [`blablablablabla`],
      },
    },
```

### Expected result

The site builds, but the query returns `null`.

### Actual result

Site fails to build:

```
There was an error in your GraphQL query:

Cannot query field "npmPackage" on type "Query".

If you don't expect "npmPackage" to exist on the type "Query" it is most likely a typo.
However, if you expect "npmPackage" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "npmPackage" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")
```

### Environment

N/A

**Comment by jzabala** [comment]
I would like to help with this one!
