### ISSUE TITLE
Allow multiple 404 pages

### ISSUE THREAD

**Issue by emanueleperuffo** [gatsbyjs/gatsby#25017]
## Summary

Accordingly to the documentation on [_redirects](https://docs.netlify.com/routing/redirects/redirect-options/#http-status-codes) of Netlify, I can have multiple 404 pages.

Netlify correctly handles the additional 404 pages and as expected

> the page content will change, but the URL in the browser address bar will not

Gatsby handles the classic `/404` page correctly like Netlify does.
If, instead, the browser receives a different 404 page, Gatsby redirects automatically to the real path of this 404 page.

### Basic example

This is my _redirects file:
```
[some other redirect rules]

/it/* /it/404 404
/en/* /en/404 404
```
If, for example, I type the path `www.example.com/en/asdasdasd` and I receive the content for the `/en/404` page, Gatsby automatically changes the browser path to `/en/404` instead of keeping `/en/asdasdasd`.

### The issue

I found the issue in `.cache/production-app.js`. Would it be a problem to change the below `pagePath.match(/^\/404\/?$/)` to `pagePath.match(/\/404\/?$/)`?

```javascript
  const { pagePath, location: browserLoc } = window

  // Explicitly call navigate if the canonical path (window.pagePath)
  // is different to the browser path (window.location.pathname). But
  // only if NONE of the following conditions hold:
  //
  // - The url matches a client side route (page.matchPath)
  // - it's a 404 page
  // - it's the offline plugin shell (/offline-plugin-app-shell-fallback/)
  if (
    pagePath &&
    __BASE_PATH__ + pagePath !== browserLoc.pathname &&
    !(
      loader.findMatchPath(stripPrefix(browserLoc.pathname, __BASE_PATH__)) ||
      pagePath === `/404.html` ||
      pagePath.match(/^\/404\/?$/) ||
      pagePath.match(/^\/offline-plugin-app-shell-fallback\/?$/)
    )
  ) {
    navigate(__BASE_PATH__ + pagePath + browserLoc.search + browserLoc.hash, {
      replace: true,
    })
  }
```

**Comment by ascorbic** [comment]
Hi. This isn't something we could add by default, as it would be a breaking change. It could in theory be a configurable feature.

**Comment by jzabala** [comment]
@emanueleperuffo I think you can solve your issue but setting a `matchPath` for the `/es/404` page.

In your `gatsby-node.js` you can do something like this:

```js
exports.onCreatePage = ({ page, actions }) => {
  if (page.path.match(/^\/es\/404\//)) {
    page.matchPath = "/es/*"
    actions.createPage(page)
  }
}
```

This way the loader will find a matching path and won't navigate.

**Comment by emanueleperuffo** [comment]
Yeah I considered that solution already but I'm not sure if there are any
other implications with matchPath for the other pages matching the pattern.
Is it safe?

**Comment by jzabala** [comment]
> Yeah I considered that solution already but I'm not sure if there are any other implications with matchPath for the other pages matching the pattern. Is it safe?

Docs:

> Note that the pages are sorted so that those with matchPaths are at the end, so that explicit paths are matched first.

https://www.gatsbyjs.org/docs/gatsby-internals-terminology/#matchpath

It will only match that path if no other, more specific, path is found.

**Comment by emanueleperuffo** [comment]
@jzabala Thank you for your help.

I'm closing this issue as [this solution based on matchPath](https://github.com/gatsbyjs/gatsby/issues/25017#issuecomment-645541217) works.

**Comment by alexbchr** [comment]
@emanueleperuffo I have the same issue (also using Gatsby on Netlify). According to my tests, the `matchPath` solution will return 200 status codes for 404 paths. Can you confirm you experience this as well?

If not, what did you do to get 404 status codes using `matchPath`?

**Comment by emanueleperuffo** [comment]
@alexbchr I get 404 status codes correctly. 

You need to add redirects in `gatsby-node.js` and you also need to enable the [gatsby-plugin-netlify](https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify/) plugin. This plugin will query Gatsby for redirects and create the appropriate `_redirects` file for you. I see that I have also the option `generateMatchPathRewrites` set to `true`, but I'm not sure if this is needed.

I use the onCreateNode API to add redirects, but I guess that it depends on your project in which Gatsby API you will call`actions.createRedirect`.

Adapt the following code to your needs:

```javascript
// gatsby-node.js

exports.onCreateNode = ({actions}) => {
  // Redirects are evaluated last, 
  // so don't be afraid because 
  // the wildcard /en/* here will not 
  // hide your pages below /en/.

  actions.createRedirect({
    fromPath: '/en/*', // your matchPath here
    toPath: '/en/404', // the path to your 404 page here
    statusCode: '404',
  });
};
```

Some useful links for you:

- https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling
- https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify/#redirects

Good luck!

**Comment by alexbchr** [comment]
@emanueleperuffo Thanks for your feedback, it helped a lot!

For others looking for a solution, I'll just leave what I experimented with here:

## Attempt 1
I did exactly as @emanueleperuffo solution: 404 redirects in `gatsby-node.js`, `generateMatchPathRewrites: true` in Netlify plugin config and `matchPath` set on created 404 pages.

**Result:** Does not work locally when using Netlify Dev CLI (404 pages are answered correctly on invalid paths of different languages but are returned with a `200` status code). However, once deployed to Netlify, it works flawlessly.

**Investigation:** The `_redirects` file generated by Netlify plugin creates 200 rewrites for 404 pages when `generateMatchPathRewrites` option is set to true. This results in 2 rewrite rules for 404 paths, one returning a `200` status code and another returning a `404` status code.

## Attempt 2
Exact same solution as 1, except this time I set `generateMatchPathRewrites` to false, so 200 rewrites aren't present in `_redirects` file.

**Result:** Same as 1, works when hosted on Netlify but not using Netlify Dev CLI. However, I sleep better at night with the 200 rewrites not being written in the `_redirects` file.

**Comment by lenzls** [comment]
My setup is a little different, but I'm having the same problem. Sadly, the proposed solution does not fully cover the problem, I think.

So the user requests URLs like
1. `example.com/en/nonsense`
2. `example.com/it/nonsense`
3. `example.com/nonsense`

Nginx rewrites them to 
1. `/en/404`
2. `/it/404`
3. `/en/404` (based on heuristics)

I've now added rules as suggested e.g.
```
  if (page.path.match(/^\/en\/404\//)) {
    page.matchPath = "/en/*"
    actions.createPage(page)
  }

  if (page.path.match(/^\/il\/404\//)) {
    page.matchPath = "/il/*"
    actions.createPage(page)
  }
[…]
```

In the first two cases, this works as expected. But for case (3) I can't specify such a rule, since I do not know which 404 page to show.

Because the problematic code `loader.findMatchPath(stripPrefix(browserLoc.pathname, __BASE_PATH__)) || …` tries to match the pathname (`/nonsense`) and not the pagePath (`/en/404`) against `matchPath`.

Do you have a suggestion how to solve this?

Thanks in advance.
