### ISSUE TITLE
How can I implement https://idiotwu.github.io/smooth-scrollbar/ in gatsby?

### ISSUE THREAD

**Issue by piyush97** [gatsbyjs/gatsby#25023]
How can I implement https://idiotwu.github.io/smooth-scrollbar/ in gatsby?

Is there anyway you guys figured it out?
Leave your suggestions in the comments 

Thanks

**Comment by LekoArts** [comment]
Thank you for opening this!

Please ask this at their repository our use something like https://www.npmjs.com/package/react-smooth-scrollbar

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
