### ISSUE TITLE
Slow TTI and noticeable lag with poor performance

### ISSUE THREAD

**Issue by pmarik** [gatsbyjs/gatsby#25027]
## Summary
Attempting to move over my portfolio to a Gatsby site and experiencing slow TTI and poor lighthouse results for my pages. The site responds well and has fast perceived load when viewed on mobile but has noticeable lag when viewed on desktop in chrome, firefox, and some images aren't even showing up on safari even when testing on multiple devices. I've moved my images to the static folder and using gatsby-plugin-netlify to serve over http2. 

It appears that my images may not be getting lazy-loaded, if there is some way to fix that? I'm also considering using loadable components but shouldn't Gatsby be doing most of the code splitting for my routes? 

As this isn't a huge site I'm not sure where I'm going wrong. I'm aware there are differences in the new lighthouse version impacting performance scores but my problem is that there is actual lag and slow TTI on desktop when there shouldn't be.

Test site: https://priceless-colden-91fb3a.netlify.app/
Git repo: https://github.com/pmarik/gatsby-firebase-test

I'm also using firebase with dynamic routes but it shouldn't be loaded with the public routes and none of the public routes link to any components that use firebase. Mostly focusing on the public facing TTI and performance.
## Relevant information
Lighthouse score:
![chromeRegLighthouse](https://user-images.githubusercontent.com/26751437/84802984-f6f72980-afc6-11ea-86cc-4b00878db0b4.JPG)

Webpack Analyser:
![webpackAnalyser](https://user-images.githubusercontent.com/26751437/84803035-0b3b2680-afc7-11ea-8ce7-317e665ffb90.JPG)

### Environment (if relevant)
Plugins:
`gatsby-plugin-react-helmet`,
`gatsby-plugin-lodash`,
`gatsby-plugin-react-svg`,
`gatsby-source-filesystem`,
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sass`,
    `gatsby-plugin-styled-components`,
    `gatsby-plugin-purgecss`, 
   `gatsby-plugin-webpack-bundle-analyser-v2`,
    `gatsby-plugin-netlify-cache`,
    `gatsby-plugin-preact`,
    `gatsby-plugin-netlify`

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by herecydev** [comment]
I don't see anywhere near those scores: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpriceless-colden-91fb3a.netlify.app%2F

Why is the react-error-overlay being bundled? It's huge!

**Comment by polarathene** [comment]
No lag for me on Chrome (Linux), worked fine. Ran pagespeed on it as well and got 86 score for mobile, 98 for desktop.

Seems like your issue is related to macOS or local to your machine/network. I only noticed <500KB for initial page load was transferred. 3 images loaded, with the last one being about 2 viewports down, on Chrome this uses native lazy load support, which means it's up to Chrome how to handle it, with other browsers that support Observer API, they should have a threshold beyond the viewport boundary for when to trigger(200px by default iirc), and if neither methods are supported by the browser, then you'd see no lazy load support.

What JS files are loading that you're certain should not be?(on Discord you said it was unused) Nothing looks concerning. When you hover over a nav link, assets/js will preload for those routes in advanced to clicking.

**Comment by vladar** [comment]
Also having good numbers in lighthouse (93-94 for performance). No lags or delays here. Sounds like some issue with your local/network setup?

Can you provide a performance profile from Chrome Dev Tools? `Performance -> Start profiling and reload page`, then `Save profile...`. This may help us shed some light on what's going on.

**Comment by pmarik** [comment]
@polarathene 
> What JS files are loading that you're certain should not be?(on Discord you said it was unused) Nothing looks concerning. When you hover over a nav link, assets/js will preload for those routes in advanced to clicking.

Thanks for taking a look. I didn't think there was any considerable bloat to the page but the 'remove unused js' metric is showing up for me every time on lighthouse. Makes me feel a little better there is no lag on your end but still really confused that for some reason there is still lag showing up for me (testing multiple browsers on mac and windows).

@vladar 
>No lags or delays here. Sounds like some issue with your local/network setup?

I have another gatsby project that is showing no lag on the same devices and browsers so that's why I don't think its specific to this. It just seems to be this site that is causing lag especially when I hover over other routes and gatsby preloads them that the current route shows lag again. 

Still kinda new to gatsby though, but here is the saved profile: 
[Profile.zip](https://github.com/gatsbyjs/gatsby/files/4793898/Profile.zip)

**Comment by vladar** [comment]
Do you have any browser extensions installed? I see some icon showing up during loading (at the top-right corner) which doesn't show up for me.

Also there is a plenty of blocking tasks in the profile with a stack trace like this (which suggests an extension interfering with your site):
 
```
chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/content.bundle.js:1 |  
30.7 ms5.5 % | 66.2 ms11.9 % | nchrome-extension://mlomiejdfkolichcflejclcbmpeaniij/dist/content_script_bundle.js:1 |  
23.0 ms4.1 % | 63.9 ms11.5 % | nchrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/injectGlobalHook.js:1 |  
14.0 ms2.5 % | 14.0 ms2.5 % | n.dchrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/injectGlobalHook.js:1 |  
7.7 ms1.4 % | 9.2 ms1.7 % | (anonymous)
```

**Comment by pmarik** [comment]
Going to close this for now as I think it's probably an extension. Just not sure why since I have other gatsby sites that play nice with no lag or slow TTI with extensions enables.
