### ISSUE TITLE
Back button not working with sitemap plugin

### ISSUE THREAD

**Issue by swkeever** [gatsbyjs/gatsby#25024]
## Description

I'm using [gatsby-plugin-sitemap](https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/) to generate a `/sitemap.xml` route. I'm putting a `Link` to this route. [Here](https://github.com/swkeever/swkeever.github.io/blob/develop/gatsby-config.js) is my `gatsby-config.js`.

When I click the Sitemap link in my footer, I'm taken to the XML document as expected. But when I press the back button, I don't go back.

I didn't find any issues about this from Googling so hopefully this is just user error. Any ideas what could be going on?

### Steps to reproduce

~~1. Visit [this webpage](https://swkeever.github.io)
2. Scroll down to the footer, and click Sitemap
3. Click the back button on your browser~~

EDIT: see comment below

### Expected result

It should take me back to the page I was on before I clicked the Sitemap link.

### Actual result

The URL seems to update correctly, but I stay on the sitemap page.

### Environment

Production i.e. `gatsby build && gatsby serve`

**Comment by swkeever** [comment]
I'm able to resolve this issue by doing what the [Gatsby website](https://gatsbyjs.org) does and move the sitemap to the `<head>`. This is fine for my purposes. But I'll keep the issue open in case its an issue for someone else.

**Comment by LekoArts** [comment]
I don't see a sitemap link in the footer? Also not sure what you meant with:

> I'm able to resolve this issue by doing what the Gatsby website does and move the sitemap to the <head>. This is fine for my purposes.

**Comment by swkeever** [comment]
@LekoArts I removed the Sitemap link in the footer since it was giving the issue with the back button.

What I mean is I did something like this to work around this issue.
```
<head>
      <link rel="sitemap" type="application/xml" href="/sitemap.xml" />
</head>
```

**Comment by LekoArts** [comment]
That's how I always added the sitemap to my site and have seen it done everywhere. Also your plugin (https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/#options) has the option `createLinkInHead`. So I'm not sure what you did before?

**Comment by swkeever** [comment]
I didn't realize that! Thanks for the tip. I was manually putting it in as a child of `<Helmet>` before, but I like your solution better.

**Comment by LekoArts** [comment]
So can we close this as resolved then? :)

**Comment by swkeever** [comment]
Sure! It's not an issue for me anymore.

I just left it open in case it wasn't expected behavior for the back button to not work when putting the sitemap link in the body of the site. If you want I could make a separate branch with the sitemap in the footer like before. I just didn't want the issue to exist in production :sweat_smile: 

Otherwise, good to close :+1:
