### ISSUE TITLE
Output stack traces for Webpack errors during build

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#25037]
## Summary

During `gatsby build`, errors encountered while rendering React components are shown as `WebpackError: ...`, without a useful stack trace. Would it be possible to add a stack trace through the React component tree, or at least the line number of where the error occurred?

### Basic example

Open the [code sandbox](https://codesandbox.io/s/gatsby-2020-webpack-stack-trace-fr-5v4zz?file=/gatsby-node.js) and wait for the build to run into the error. The output will look like the following:

![image](https://user-images.githubusercontent.com/33569/84850264-21b7a100-b00c-11ea-8152-52b271c10b33.png)

### Motivation

This would enable tracking errors that occur in React components during SSR.

An alternative would be documentation about how to step through React components during SSR, added to https://gatsby.dev/html-builds or perhaps to https://www.gatsbyjs.org/docs/debugging-the-build-process/.

**Comment by abraaoz** [comment]
up

**Comment by LekoArts** [comment]
https://github.com/gatsbyjs/gatsby/pull/25385 should have fixed this. If you're still seeing this behavior please post a reproduction in this issue: https://github.com/gatsbyjs/gatsby/issues/25507

**Comment by dandv** [comment]
Confirming the fix in v2.24.3. Thanks!
