### ISSUE TITLE
Does Gatsby have something like getServerSideProps in nextjs?

### ISSUE THREAD

**Issue by ImSolitude** [gatsbyjs/gatsby#25033]
If you're not familiar on how [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) works, basically get the data on the server before rendering the component.

In my use case I **really** need this, I have a dynamic components that needs SEO and I cannot do it on build time.

Any help?

**Comment by LekoArts** [comment]
Thank you for opening this!

With Gatsby the paradigm is that you create everything at build time and if you have e.g. authenticated routes you render it only on the client. Typically you can/should prerender everything except when you - as mentioned - have things like authenticated routes.

So you should still render your components at build time. If that's not possible you have to render it on the client.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
