### ISSUE TITLE
$regex filter with escapes broken

### ISSUE THREAD

**Issue by pvdz** [gatsbyjs/gatsby#25047]
This is how the regex is preprocessed (`gatsby/src/utils/prepare-regex.ts`):

```
import _ from "lodash"

export const prepareRegex = (str: string): RegExp => {
  const exploded = str.split(`/`)
  const regex = new RegExp(
    exploded
      .slice(1, -1)
      .join(`/`)
      // Double escaping is needed to get past the GraphQL parser,
      // but single escaping is needed for the RegExp constructor,
      // i.e. `"\\\\w+"` for `/\w+/`.
      .replace(/\\\\/, `\\`),
    _.last(exploded)
  )
  return regex
}
```

The replace is missing a `g` flag, so it will only replace the first occurrence, which I don't think is what we want.

The `_.last` call is a liiitle redundant, too :/

**Comment by ehrencrona** [comment]
I took a brief look at this. Per se I agree that `/g` should be added in the replace, but on the other hand I'm kind of wondering about why the double escaping replacement is happening at all. If I remove it completely all unit tests still pass.

(the `_.last`, on the other hand, is required for the flags to be passed)
