### ISSUE TITLE
Updating to latest graphql-playground-html introduces StaticQuery(Loading) Error

### ISSUE THREAD

**Issue by infomofo** [gatsbyjs/gatsby#25054]
## Description

I got a critical security vulnerability alert to update [graphql-playground-html](https://github.com/graphcool/graphql-playground) from 1.6.19 to 1.6.25.

After upgrading, whenever I run `gatsby develop` locally, any components with a `<StaticQuery>` render with the words "Loading {StaticQuery}" inline instead of the contents of the component.

It's similar the same behavior described in some old issues #7959 #24890 

I've tried the resolution on that old issue, clearing my cache and node modules folder and that does not resolve the issue. Downgrading the plugin works, but isn't a great solution since it is a critical security vulnerability. Note, this only affects my `gatsby develop`, my `gatsby build` works fine.

I haven't yet made a reproduction case, but if other people are experiencing the same issue with this plugin I can, I just wanted to document what I was seeing for now.

### Environment

```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.0.17 - /usr/local/bin/bash
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 3.7.7 - /Users/will/.pyenv/shims/python
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: 2.23.3 => 2.23.3
    gatsby-cli: 2.12.45 => 2.12.45
    gatsby-image: 2.4.7 => 2.4.7
    gatsby-plugin-algolia: 0.11.1 => 0.11.1
    gatsby-plugin-canonical-urls: 2.3.4 => 2.3.4
    gatsby-plugin-catch-links: 2.3.5 => 2.3.5
    gatsby-plugin-feed: 2.5.5 => 2.5.5
    gatsby-plugin-google-analytics: 2.3.4 => 2.3.4
    gatsby-plugin-manifest: 2.4.11 => 2.4.11
    gatsby-plugin-offline: 3.2.9 => 3.2.9
    gatsby-plugin-react-helmet: 3.3.4 => 3.3.4
    gatsby-plugin-sharp: 2.6.11 => 2.6.11
    gatsby-plugin-styled-components: 3.3.4 => 3.3.4
    gatsby-plugin-typography: 2.5.4 => 2.5.4
    gatsby-remark-copy-linked-files: 2.3.5 => 2.3.5
    gatsby-remark-images: 3.3.10 => 3.3.10
    gatsby-remark-prismjs: 3.5.4 => 3.5.4
    gatsby-remark-responsive-iframe: 2.4.5 => 2.4.5
    gatsby-remark-smartypants: 2.3.4 => 2.3.4
    gatsby-source-filesystem: 2.3.11 => 2.3.11
    gatsby-transformer-remark: 2.8.15 => 2.8.15
    gatsby-transformer-sharp: 2.5.5 => 2.5.5
```

**Comment by vladar** [comment]
Hi @infomofo 

We'd really want to get a [reproduction][reproduction] for this as we couldn't reproduce it. That would be very helpful! Then we can take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by JeffWeim** [comment]
FWIW, I'm currently using version `2.23.1`. [This change](https://github.com/gatsbyjs/gatsby/commit/7c9711b) was introduced in `2.23.2`. After I upgraded to any version after `2.23.2` this same issue appeared for me when using `StaticQuery` in pages.

**Comment by wardpeet** [comment]
Is it possible to create a small reproduction? I can't seem to reproduce on the latest gatsby package.

**Comment by LekoArts** [comment]
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!
