### ISSUE TITLE
Fix "Adding Search with Algolia" tutorial

### ISSUE THREAD

**Issue by samajammin** [gatsbyjs/gatsby#25070]
## Summary

First off, thank you! I've been loving Gatsby & overall your docs are excellent.

I just walked through [the Algolia tutorial](https://www.gatsbyjs.org/docs/adding-search-with-algolia/#usage) & (perhaps this is just a user error but) I hit an issue with the code you provided.

In the Search component ([index.js](https://www.gatsbyjs.org/docs/adding-search-with-algolia/#indexjs)), I believe the `ref` is not set correctly. When I set up the component & try to `gatsby develop`, I hit this error if I click anywhere:

```
index.js:26 Uncaught TypeError: Cannot read property 'contains' of null at HTMLDocument.detectClickOutside (index.js:26)
```

The offending code:
```
const detectClickOutside = (event) => !ref.current.contains(event.target) && handler()
```

`ref.current` appears to always be `null`.

### Motivation

The current documentation is broken (at least for me).

## Steps to resolve this issue

I was able to get around this by editing this code:

```
    <InstantSearch
      searchClient={searchClient}
      indexName={indices[0].name}
      onSearchStateChange={({ query }) => setQuery(query)}
      root={{ Root, props: { ref } }}
    >
```

To follow [this code](https://github.com/janosh/blog/blob/03c61cd35b89caea8ab9984551a5da7105fdb84a/src/components/Search/index.js) (from the blog you link to in the bottom video).
Here, the Root component wraps all components & [the ref is set on the Root component](https://github.com/janosh/blog/blob/03c61cd35b89caea8ab9984551a5da7105fdb84a/src/components/Search/index.js#L32).

### Draft the doc

I would just update the index.js file to match [this](https://github.com/janosh/blog/blob/03c61cd35b89caea8ab9984551a5da7105fdb84a/src/components/Search/index.js).

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by samajammin** [comment]
Hey @yg - I see you assigned this to me. Is there any action needed on my end? I've opened up https://github.com/gatsbyjs/gatsby/pull/25073

Thanks!

**Comment by yg** [comment]
@samajammin I assigned to you because you are working on this issue, If I'm wrong correct me. Thanks
