### ISSUE TITLE
docs: Document caveat of `@link` directive (by parameter)

### ISSUE THREAD

**Issue by LekoArts** [gatsbyjs/gatsby#25089]
## Summary

In solving the issue https://github.com/gatsbyjs/gatsby/issues/25077 it was made clear that the `by` argument of the `@link` directive doesn't support arrays. This should be documented in the https://www.gatsbyjs.org/docs/schema-customization/#foreign-key-fields section of our documentation.

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by jzabala** [comment]
Hi @LekoArts I added a draft for updating the docs to include the `by` behavior with arrays.
