### ISSUE TITLE
onCreateBabelConfig needs update post 2.0

### ISSUE THREAD

**Issue by dandv** [gatsbyjs/gatsby#25083]
[onCreateBabelConfig](https://www.gatsbyjs.org/docs/node-apis/#onCreateBabelConfig) reads

> This API will change before 2.0 as it needs still to be converted to use Redux actions.

**Comment by marcysutton** [comment]
This could use a comment by someone on @gatsbyjs/core, since it has to do with core APIs.

**Comment by wardpeet** [comment]
Good call, this is indeed fully functional and we should update the docs accordingly.

You can edit the description here:
https://github.com/gatsbyjs/gatsby/blob/788856010308eaff9ee0bd3ff29bb1dc9cf14ba6/packages/gatsby/src/utils/api-node-docs.ts#L334-L339

An example of this api can be found here:
https://github.com/gatsbyjs/gatsby/blob/561d33e2e491d3971cb2a404eec9705a5a493602/packages/gatsby-plugin-styled-components/src/gatsby-node.js

We would love a PR that fixes this documentation 😄
