### ISSUE TITLE
Router issue - change url but without rerender the content

### ISSUE THREAD

**Issue by stanleyyuenyiu** [gatsbyjs/gatsby#25087]
As gatsby is restrict to use reach/router, however, it seem to lost the flexibility on change url but without re-render a page

use case (react router)
 i have a hoc, which map a state call locale, when locale update, this HOC, will use componentWillReceiveProps to update the history, e.g:

```
componentWillReceiveProps(nextProps) 
{
            if (this.props.locale !== nextProps.locale) {
                this.updateCurrentLocation(nextProps);
            }
        }

updateCurrentLocation(nextProps) {
            const pathname = nextProps.location.pathname;
            let pathnames = pathname.split('/');
            pathnames[1] = nextProps.locale;
            nextProps.history.replace(pathnames.join('/'));
        }
```
in this case, the Component that using this HOC will not re-render, as we only change the url at browser, but not doing any redirect, therefore, if the Component is a input form, the input that user fill in will not clear if he change the locale, unlike reach/router, it force to re render

how can i do the same things with reach/router, or you never have a chance to do it?

**Comment by LekoArts** [comment]
Thank you for opening this!

Our usage of reach/router didn't change the functionality you're describing, the general way in how Gatsby works makes the difference.

You can use the [`wrapPageElement`](https://www.gatsbyjs.org/docs/browser-apis/#wrapPageElement) API to persist data on route changes. The [`gatsby-plugin-layout`](https://www.gatsbyjs.org/packages/gatsby-plugin-layout/) implements this API for you. So you'll need to place the component into the wrapPageElement call or into the file that you use with the layout plugin.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by stanleyyuenyiu** [comment]
may i know wrapPageElement only blocking the re-render on route change, or block any re-render (like using redux, and i assume it will rerender if the redux state is mapped)?

cause in some case,

 i have 2 pages, 

page a and page b, 

when i switch the page from a to b or b to a, i wanna reload the destination page data, 

but except url locale update, can i do this with wrapPageElement?

**Comment by stanleyyuenyiu** [comment]
> communities

may i know wrapPageElement only blocking the re-render on route change, or block any re-render (like using redux, and i assume it will rerender if the redux state is mapped)?

cause in some case,

i have 2 pages,

page a and page b,

when i switch the page from a to b or b to a, i wanna reload the destination page data,

but except url locale update, can i do this with wrapPageElement?

**Comment by LekoArts** [comment]
If I understood your question correctly:

> This is useful for setting wrapper components around pages that won’t get unmounted on page changes

So your component doesn't get unmounted on route changes but if you decide to update e.g. the Redux state it'll re-render.

**Comment by stanleyyuenyiu** [comment]
component doesn't get unmounted on route changes -> only apply for locale change, such as /en/login to /cz/login, but not apply to /en/login to /en/home

**Comment by kevinNgws** [comment]
Im facing the same issue as well. 
Is there a listener to capture a before route change? So that I can check if only language is modified then i shall not reload the page.
