### ISSUE TITLE
Query for siteMetadata from inside plugin

### ISSUE THREAD

**Issue by anicolaides** [gatsbyjs/gatsby#25082]
## Summary

First off, thank you! Gatsby is a wonderful technology.

I have created a gatsby-theme that requires **siteMetadata.siteUrl**; for instance, take a look at the **gatsby-plugin-canonical-urls** section of the theme's gatsby-config.js below:

```js
// gatsby-config.js of the theme
module.exports = themeOptions => {
  return {
    plugins: [
      ...
      {
        resolve: `gatsby-plugin-canonical-urls`,
        options: {
          siteUrl: themeOptions.siteUrl,
        },
      },
      ...
    ],
  }
}
```
How it's used at the moment:

```js
// gatsby-config.js of plugin user
module.exports = {
  plugins: [
    {
      resolve: `gatsby-theme-test`,
      options: {
        siteUrl: "https://example.com",
      },
    },
  ],
}
```

How I would like to have it used:

```js
// gatsby-config.js of plugin user
module.exports = {
  plugins: [
    ...
    `gatsby-theme-test`,
    ...
  ],
}
```

It seems redundant to pass siteUrl for each plugin individually in gatsby-config.js. I would like to have my gatsby-theme fetch the siteUrl internally, and supply it to it's gatsby-config.js for use as necessary.

I have found the API specified below that allows for gatsby-node.js queries to be run, yet I cannot seem to think of a way to pass data **from gatsby-node.js to gatsby-config.js**.

[Node Model - runQuery | GatsbyJS](https://www.gatsbyjs.org/docs/node-model/#runQuery)

### Motivation

Don't repeat yourself principle

**Comment by ascorbic** [comment]
You can query for siteMetadata inside a plugin's source. See gatsby-plugin-sitemap for an example. However you can't do any queries in gatsby-config, nor can you pass query results to it. The plugins and configs are loaded right at the beginning of the build process, a long time before the GraphQL nodes have been created. This makes sense if you think about it, as the siteMetadata is defined in the config, so it can't be available until after all the configs are loaded.

I'm goign to clsoe this, but if I've misunderstood your question then please do re-open it.
