### ISSUE TITLE
Issues with displaying <code> and <blockquote> when using markdown to generate pages in Gatsby

### ISSUE THREAD

**Issue by mukul-raina** [gatsbyjs/gatsby#25081]
## Description

When I try to use `<code>` and `<blockquote>` tags, gatsby seems to generate the right html tags but the styling isn't there

<img width="1280" alt="Screen Shot 2020-06-17 at 10 44 44 PM" src="https://user-images.githubusercontent.com/4411238/84972109-2b183a80-b0ec-11ea-86bd-ed01523ad433.png">

However things are getting displayed as expected in VS code markdown preview, so I guess there not issues with the markdown file itself 

<img width="1280" alt="Screen Shot 2020-06-17 at 10 46 07 PM" src="https://user-images.githubusercontent.com/4411238/84972188-5a2eac00-b0ec-11ea-9e57-31be5e59a905.png">

### Steps to reproduce

I followed the exact step to step here: https://www.gatsbyjs.org/docs/adding-markdown-pages/ no additional changes to `<code>` and `<blockquote` styling 

### Expected result

I'm hoping the outcome is same as the VS code previewer 

### Actual result

No styling applied as evident in the screenshot above

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.106
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9
    gatsby-plugin-offline: ^3.2.7 => 3.2.7
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2
    gatsby-plugin-sass: ^2.3.4 => 2.3.4
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9
    gatsby-source-filesystem: ^2.3.11 => 2.3.11
    gatsby-transformer-remark: ^2.8.15 => 2.8.15
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3
  npmGlobalPackages:
    gatsby: 2.23.3

**Comment by LekoArts** [comment]
Thank you for opening this!

The markdown preview you see in VS Code is enhanced by VS Code itself. If you open the Developer Tools you'll see that they add CSS styling to the elements:

![image](https://user-images.githubusercontent.com/16143594/84987918-5e38e900-b141-11ea-9506-7593bfb15e05.png)

Thus you'll also need to add CSS styles to style your `blockquote` or code blocks. For the latter you can use this plugin: https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/
We also have a section on how to add styling to your page here: https://www.gatsbyjs.org/docs/styling/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
