### ISSUE TITLE
Gatsby-source-contentful fails with an obtuse error if no content of a certain type

### ISSUE THREAD

**Issue by daniel-simpson** [gatsbyjs/gatsby#2508]
Gatsby version: "^1.9.70"
Plugin: "gatsby-source-contentful": "^1.3.17",

Scratched my head over this one for a few hours before I dug into the code: was getting a very obtuse error message:
```
error Plugin gatsby-source-contentful returned an error
TypeError: Cannot read property 'sys' of undefined
```

After opening up my node modules to track down what was going on and figured out that a line of code in normalize.js makes an assumption that there is at least one content item.  Because I have only done my data modelling in Contentful so far (I hadn't added test content for each type), this was breaking with my error above.

Fix incoming, just as soon as I can clone the gatsby core repo.

**Comment by flaviolivolsi** [comment]
This still happens to me. Wasn't the fix merged?
