### ISSUE TITLE
Relicense starters under 0BSD?

### ISSUE THREAD

**Issue by balibebas** [gatsbyjs/gatsby#25091]
## Summary

MIT license in Gatsby starters may lead individuals to use unlicensed code.

## Relevant information

The starter templates everyone's using are licensed under MIT which requires the original license text, disclaimer and copyright notice are kept for the life of the project. Wouldn't it be preferable to relicense those under [0BSD](https://choosealicense.com/licenses/0bsd/) so those getting started with Gatsby don't have to worry about carrying around that MIT license?

The presense of the MIT license from the get-go also raises concerns about lawful use of Gatsby starter's which've been extended without the addition of a second copyright notice or a relicensing effort: https://github.com/AlexanderProd/gatsby-shopify-starter/issues/45

**Comment by ascorbic** [comment]
Thanks. We need to discuss this internally and will update you when we have an answer.

**Comment by balibebas** [comment]
Thanks @LekoArts et al. This is a much appreciated change. :comet:
