### ISSUE TITLE
How to auth protect one list page and all its children?

### ISSUE THREAD

**Issue by lionzan** [gatsbyjs/gatsby#25097]
## Summary
I successfully followed the [authentication tutorial](https://www.gatsbyjs.org/tutorial/authentication-tutorial/). Now I would like to protect an entire list of pages sitting in one single folder. Imagine a blog which is password protected.

1. How can I do it? 
2. Where would I put the pages content (which wouldn't be actual pages as much as component rendered on the client)

## Details
Q. 1. I guess I should include each page in `app.js` as a `<PrivateRoute>` but how would I do it? I guess I need a way to include an entire directory as `<PrivateRoute>`. 

Or there is another strategy?

## Syatem

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.106
    Safari: 13.1
  npmPackages:
    gatsby: ^2.23.3 => 2.23.3
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-source-filesystem: ^2.3.11 => 2.3.11
    gatsby-transformer-remark: ^2.8.16 => 2.8.16
  npmGlobalPackages:
    gatsby-cli: 2.12.21

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wardpeet** [comment]
This might not be 100% what you're looking for but something like this is more or less what I think you're looking for.

```
const CustomRoute = ({ component: Component, location, ...rest }) => {
  if (location.pathname.startsWith('/app/secure')) {
    return <PrivateRoute component={Component} location={location} {...rest} />
  }

  return <Component location={location} {...rest} />
}
```

Thank you for raising this question. If you think we should add extra notes to the tutorial, please let us know.
For more guidance and help I suggest you go to [Discord](https://gatsby.dev/discord). 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

Cheers!
Ward

**Comment by lionzan** [comment]
Thank you @wardpeet I will try to make it work and if in trouble will reopen the issue.
