### ISSUE TITLE
Netlify and Vercel fail to build gatsby

### ISSUE THREAD

**Issue by crperez5** [gatsbyjs/gatsby#25090]
## Summary
Deployment to Vercel and Netlify fails due to invalid CSS in the output artifact. 

The exact error is:

![image](https://user-images.githubusercontent.com/17414656/85006385-bcc28f00-b162-11ea-9d8c-c52105bc8e5e.png)

On the other hand, `gatsby build` works just fine when run locally even after a fresh `git clone` and full `npm install`.

## Relevant information
These are the specs from the remote server that is building the gatsby project:

![image](https://user-images.githubusercontent.com/17414656/85006653-1034dd00-b163-11ea-92b9-df98de74fde8.png)

These are the specs from my computer:

![image](https://user-images.githubusercontent.com/17414656/85006713-26db3400-b163-11ea-846f-4a2bb35d69cf.png)

Interestingly, the CSS file that Vercel / Netlify are complaining about contains 16 lines while the one generated in my computer contains a single line.

Do you see any remarkable differences that would cause a different behaviour when running the build on a remote machine vs local? 

I have no access to the build artifacts in the remote machine, so I cannot tell wether the CSS is invalid or not. The CSS file that gets generated in my computer appears to be ok. 

Repo URL: 
https://github.com/crperez5/portfolio

Any hints would be much appreciated.

**Comment by ascorbic** [comment]
Hi. My guess is that this is Windows vs Linux issue. I can't test using your repo, because I don't have your API keys. If you try deploying it to Gatbsy Cloud it'll probably have the same issue if it's a Linux problem, and I can debug the issue directly on the build machine then. Would you be iwlling to give that a try?

**Comment by crperez5** [comment]
> Hi. My guess is that this is Windows vs Linux issue. I can't test using your repo, because I don't have your API keys. If you try deploying it to Gatbsy Cloud it'll probably have the same issue if it's a Linux problem, and I can debug the issue directly on the build machine then. Would you be iwlling to give that a try?

Sure, that would be great. 

I don't feel confortable posting keys in here, how can I send them over to you?   

Thanks.

**Comment by crperez5** [comment]
@

> Hi. My guess is that this is Windows vs Linux issue. I can't test using your repo, because I don't have your API keys. If you try deploying it to Gatbsy Cloud it'll probably have the same issue if it's a Linux problem, and I can debug the issue directly on the build machine then. Would you be iwlling to give that a try?

Thanks once more. I managed to reproduce the error in a Linux machine. 

Unfortunately, when the build fails gatsby will not output the CSS file into the public folder or maybe it deletes it afterwards so I cannot inspect it. 

Any workarounds?

**Comment by crperez5** [comment]
Okay, I'm replying to myself but anyway it may be useful for other people. It turns out that the problem was the path to a SVG:

`background-image: url(images/header-background.svg);`

I provided a base64 encoded version of the SVG instead and that made the trick. 

Of course, figuring out why this happened only in Linux will take me some more time.

Cheers!

**Comment by ascorbic** [comment]
Oh great, glad you solved it. Incidentally, rather than base64-encoding it, you can [embed svg directly as a data uri](https://css-tricks.com/probably-dont-base64-svg/) and it'll probably a lot smaller.
