### ISSUE TITLE
Failing after 5s — Gatsby Build Service

### ISSUE THREAD

**Issue by abhishekjakhar** [gatsbyjs/gatsby#25101]
When raising the PR, the **Gatsby Build Service - gatsby-master** check is failing for every PR, this particular check was not there before in the pipeline.

For example https://github.com/gatsbyjs/gatsby/pull/25078 in this PR also this check has failed, I am not able to identify the reason, can anyone help?

**Comment by LekoArts** [comment]
We're aware of this, you can ignore this for now / we'll comment if it's of importance.
