### ISSUE TITLE
Any way to include file from static folder without actually using the file?

### ISSUE THREAD

**Issue by learis** [gatsbyjs/gatsby#25108]
I'm finishing a website and am putting in some SEO optimizations. One of those is structured data. Structured data has the property 'logo' which I'd like to use, and it requires an absolute path for the logo image. No problem, I'll just use the static folder for that since that's Gatsby's answer to absolute paths.

However, unless I actually use the logo image in that static folder, it never gets included. The problem is I only use the logo image from graphql queries to other locations for the image, not the static folder location. I literally only want the static folder so that I can reference the logo image via direct path from within the structured data like:

    <script type="application/ld+json">
    {
      //... other structured data,
      "logo": "http://www.example.com/logo.png"
    }

But I've tested on a simple hello world app. The image is only ever included directly if it's truly used in the app (which is not the case for me since I'm never truly using the image in the static folder). Is there any way around this? Like some way to force the builder to include that image even though it's not technically used in the app? I'm a beginner at this low-level building stuff, so bear with me.

**Comment by LekoArts** [comment]
Hi, thanks for the issue! Can you please provide a [minimal reproduction][reproduction] of what you're seeing?

The `static` portion of e.g. themes.lekoarts.de works just fine, I also only include the images in my absolute paths for the SEO component and don't import them anywhere: https://github.com/LekoArts/gatsby-themes/blob/master/www/src/components/seo.tsx

[reproduction]: https://gatsby.dev/reproduction

**Comment by apmsooner** [comment]
I put my images like that in an "images" folder under source and just import them into the component like:
`import Logo from "./images/logo.png"`

and then you could just do like this:

```
<script type="application/ld+json">
{
  //... other structured data,
  "logo": Logo
}
```

I don't know if there is an advantage otherwise to referencing them in a static folder... perhaps someone else could comment on that but this approach works for me if you wanna try that.

**Comment by learis** [comment]
Hello, it turns out that everything actually works just like LekoArts said. The confusing thing is that unused static files don't show up when debugging from local host, but when I published via surge and checked again, everything was fine. So there's no issue.
