### ISSUE TITLE
[bug] gatsby.2.23.3/2.23.4 failing in Github Actions ubuntu 18 LTS

### ISSUE THREAD

**Issue by JustFly1984** [gatsbyjs/gatsby#25103]
@pieh  I have got this error 3 times today in github actions build pipeline

```sh
$ yarn develop
$ gatsby develop -S
info setting up automatic SSL certificate (may require elevated permissions/sudo)

rm: cannot remove '/usr/local/share/ca-certificates/devcert.crt': No such file or directory
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/n/nss/libnss3-tools_3.35-2ubuntu2.7_amd64.deb  404  Not Found [IP: 52.165.132.12 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error Failed to generate dev SSL certificate


  Error: Command failed: sudo apt install libnss3-tools
  WARNING: apt does not have a stable CLI interface. Use with caution in scripts  .
  E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/n/nss/libns  s3-tools_3.35-2ubuntu2.7_amd64.deb  404  Not Found [IP: 52.165.132.12 80]
  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-m  issing?
  
  - utils.js:22 Object.run
    [poolotto-gatsby]/[devcert]/dist/utils.js:22:28
```

After restarting failed task, deploy succeed.
Updating to 2.23.4 to check if it fixed.

Update: 2.23.4 also has same issue as 2.23.3
Update: reverting to 2.23.2 did not help,
pinning devcert to 1.1.0 helped only on local macos environment

**Comment by JustFly1984** [comment]
reverting back to 2.23.2 does not help, same error at runtime:

<img width="1226" alt="Screenshot 2020-06-19 16 49 57" src="https://user-images.githubusercontent.com/2255993/85120116-fc65a580-b24c-11ea-92b8-88cf53b0cdef.png">

**Comment by JustFly1984** [comment]
Guess it is the same issue as of https://github.com/gatsbyjs/gatsby/issues/25064

**Comment by LekoArts** [comment]
Thanks for the issue! But as per https://github.com/gatsbyjs/gatsby/issues/25064#issuecomment-646708020 this isn’t an issue with Gatsby but your GitHub actions setup.

**Comment by JustFly1984** [comment]
@LekoArts  it is not issue of github actions setup, it is the issue of gatsby, due it having dependency devcert unpinned version, and reliance of devcert on environment to have certain modules installed by default, which happens is not reliable. We had this github actions setup for last 4 months at least and everything worked perfectly with ubuntu-latest as test/deploy target. Something has changed, and it bubbled up to gatsby. We had switched github actions target to macos-latest, and pined devcert to 1.1.0, and fixed ci pipelines.
