### ISSUE TITLE
Add support for handling redirects

### ISSUE THREAD

**Issue by hellais** [gatsbyjs/gatsby#2511]
I see that in https://github.com/gatsbyjs/gatsby/pull/2191 it was added support for handling redirects via the `createRedirects` API call in the netlify plugin.

I would like to know what would be needed to:

* [ ] Add support for handling these redirects when in development mode (`gatsby develop`)
* [ ] Add support for handling redirects when using something like nginx

I see a comment in https://github.com/gatsbyjs/gatsby/issues/1660#issuecomment-326136327 stating that the best path for the second would be to create a plugin called `gatsby-plugin-nginx`, but some pointers as to how once would go about doing that is unclear.

**Comment by KyleAMathews** [comment]
Redirects already are handled in development.

Adding support for other hosting environments would mean writing out some sort of file specifying the redirects that e.g. nginx could read in.

See what the Netlify plugin does https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify/src/create-redirects.js

**Comment by KyleAMathews** [comment]
Closing this issue as it's fairly old and we have far too many open issues! Would love if someone builds a gatsby-plugin-nginx!

**Comment by b0gd4n** [comment]
any update on this?

**Comment by wardpeet** [comment]
@b0gd4n we support redirects. Feel free to re-open an issue if you have problems.
