### ISSUE TITLE
Can not develop after switching branch and which is few commit behind the head

### ISSUE THREAD

**Issue by jjbully** [gatsbyjs/gatsby#25118]
## Description

I create a branch few commit behind the head and then switch branch and do sthg. and then it fail to develop and it give me this error

### Steps to reproduce

1. create a branch which is few commit behind the head
2. switch to that branch
3. make some change
4. `gatsby develop`, fail
5. switch back to master branch (which worked before)
6 `gatsby develop` fail too
7 `gatsby clean `      `gatsby develop` fail too

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

able to develop

### Actual result

localhost:8000 show this error

`Error: It appears like Gatsby is misconfigured. JSONStore is Gatsby internal development-only component and should never be used in production.

Unless your site has a complex or custom webpack/Gatsby configuration this is likely a bug in Gatsby. Please report this at https://github.com/gatsbyjs/gatsby/issues with steps to reproduce this error.
Module../.cache/query-result-store.js
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/.cache/query-result-store.js:13
  10 | import normalizePagePath from "./normalize-page-path"
  11 | 
  12 | if (process.env.NODE_ENV === `production`) {
> 13 |   throw new Error(
  14 |     `It appears like Gatsby is misconfigured. JSONStore is Gatsby internal ` +
  15 |       `development-only component and should never be used in production.\n\n` +
  16 |       `Unless your site has a complex or custom webpack/Gatsby ` +
View compiled
__webpack_require__
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
fn
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
Module../.cache/public-page-renderer-dev.js
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/.cache/public-page-renderer-dev.js:1
> 1 | import React from "react"
  2 | import PropTypes from "prop-types"
  3 | 
  4 | import loader from "./loader"
View compiled
__webpack_require__
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
fn
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
./.cache/public-page-renderer.js
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/.cache/public-page-renderer.js:4
  1 | const preferDefault = m => (m && m.default) || m
  2 | 
  3 | if (process.env.BUILD_STAGE === `develop`) {
> 4 |   module.exports = preferDefault(require(`./public-page-renderer-dev`))
  5 | } else if (process.env.BUILD_STAGE === `build-javascript`) {
  6 |   module.exports = preferDefault(require(`./public-page-renderer-prod`))
  7 | } else {
View compiled
__webpack_require__
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
fn
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
Module../.cache/gatsby-browser-entry.js
http://localhost:8000/commons.js:1653:79
__webpack_require__
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
fn
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
Module../src/components/layout.js
http://localhost:8000/commons.js:33895:64
__webpack_require__
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
fn
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
Module../src/pages/about.js
http://localhost:8000/commons.js:33962:76
__webpack_require__
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
fn
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
./.cache/sync-requires.js
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/.cache/sync-requires.js:8
   5 | 
   6 | 
   7 | exports.components = {
>  8 |   "component---src-pages-about-js": hot(preferDefault(require("/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/src/pages/about.js"))),
   9 |   "component---src-pages-index-js": hot(preferDefault(require("/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/src/pages/index.js"))),
  10 |   "component---src-pages-my-files-js": hot(preferDefault(require("/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/src/pages/my-files.js"))),
  11 |   "component---src-templates-blog-post-js": hot(preferDefault(require("/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/src/templates/blog-post.js")))
View compiled
__webpack_require__
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
fn
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
Module../.cache/app.js
http://localhost:8000/commons.js:996:73
__webpack_require__
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
fn
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
0
http://localhost:8000/commons.js:34351:18
__webpack_require__
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
(anonymous function)
/Volumes/Storage/Code/JS/gatsby/offical-tutorial/gatsby-04-07-data/webpack/bootstrap:856
  853 | 
  854 | 
  855 | // Load entry module and return exports
> 856 | return hotCreateRequire(0)(__webpack_require__.s = 0);
  857 | 
View compiled
(anonymous function)
http://localhost:8000/commons.js:860:10
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
`

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 76.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.23.3 => 2.23.3 
    gatsby-plugin-emotion: ^4.3.4 => 4.3.4 
    gatsby-plugin-typography: ^2.5.4 => 2.5.4 
    gatsby-source-filesystem: ^2.3.11 => 2.3.11 
    gatsby-transformer-remark: ^2.8.16 => 2.8.16 
  npmGlobalPackages:
    gatsby-cli: 2.12.45

**Comment by smthomas** [comment]
Thank you for the information and for submitting an issue. Can you try to update to the latest version of Gatsby. Then delete the .node_modules folder and re-run `npm install` to get the updated packages?

If you are still running into the same problem after these steps, please let us know.

**Comment by freiksenet** [comment]
Hi! 

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. 

Thanks!
