### ISSUE TITLE
Pull the Linklist object to GraphQL

### ISSUE THREAD

**Issue by josub** [gatsbyjs/gatsby#25127]
## Summary

The [Linklist object](https://shopify.dev/docs/themes/liquid/reference/objects/linklist) which is available via Shopify API is currently not being pulled in by the [Shopify source plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-shopify) . Can the source plugin pull in the Linklist object so we can access it in GraphQL?

### Motivation
The Linklist object is primarily used for parsing Navigation and Menus but also often used by Shopify theme developers to give the customer a way to dynamically set a product for a specific feature. See e.g. [Gift wrap option](https://shopify.dev/tutorials/customize-theme-add-gift-wrap-option) as one of many examples of how the Linklist can be used not only for Menus.

**Comment by smthomas** [comment]
Thanks for submitting an issue. The gatsby-source-shopify plugin uses the Shopify Storefront API to pull in the data from the Shopify store. I did a quick look and couldn't find Menus or Linklist items listed in the Storefront API documentation:

https://shopify.dev/docs/storefront-api/reference/object

The GraphQL queries are included in the queries.js file in gatsby-source-shopify for reference. I could see this information being useful, though. However, it is going to take some research to determine how this information can be queried and it may require some significant changes to how data is pulled into the gatsby-source-shopify plugin.

If you can do some research or find some API documentation for how to access this data, it may help us move this feature request along.

**Comment by josub** [comment]
Thank you for the reply. I am closing this issue since it is not in the Storefront API and therefore not viable to add. I will update here if I find some easy workaround.
