### ISSUE TITLE
Change `navigate` typings to not return a promise

### ISSUE THREAD

**Issue by sindreij** [gatsbyjs/gatsby#25123]
## Summary

Can `navigate` be changed to return a promise that is resolved when the next page has loaded? This is how the similar-named function works for @reach/router, and since gatsby is re-exporting the types from this, the gatsby-types says that it returns a promise.

### Basic example

```js
navigate("/form-submitted/").then(() => {
    // Do something
}
```

### Motivation

The typescript-types claims that this is returned, and it is how the API works for reach. I need this to be able to smooth-scroll to a part of the next page.

**Comment by wardpeet** [comment]
We should update the typings so it doesn't return a promise. At this moment we can't coordinate when a page is really done.

https://github.com/gatsbyjs/gatsby/issues/22151#issuecomment-598103802

**Comment by ehrencrona** [comment]
For what it's worth, it seems to return a promise when I try it. The following code works for me and prints out `resolved undefined` (using the current Gatsby built from source).

```
import React from "react"
import { PageProps } from "gatsby"

export default ({ navigate }: PageProps) => {
  return (
    <button
      onClick={() =>
        navigate("/page-2/").then(result => {
          console.log("resolved", result)
        })
      }
    >
      Navigate
    </button>
  )
}
```

**Comment by sindreij** [comment]
@ehrencrona: I think one is using `navigate` from `@reach/router` instead of the one from `gatsby`. The latter is a wrapper around the former, which also does a few more things.

My initial use-case no longer applies, but I at least think the typing should be updated. Now you get an error from `eslint` saying that you need to handle the Promise.
