### ISSUE TITLE
IMG/CSS only in "link"

### ISSUE THREAD

**Issue by wybitnygracz** [gatsbyjs/gatsby#25130]
I'm having problems indexing my sites after migrating to Gatsby.
My sites have 10k+ pages. Before migrating to gatsby there was 10k+ sites in index. 
Now i have only about ~4k.  
I'm want to test if reduce HTML files size  will affect indexing. 

Therefore, I want  remove all <style>CSS...</style> from my site. Then add CSS only this way <style href="static/style.css" />  
How can i do this? 

I also want to prevent my images from being placed this way: (<img src="data:..." ) i want my images to be accesible standard way like (<img src="statci/image.jpg"); 
How can i do this?

**Comment by herecydev** [comment]
You can customize your html: https://www.gatsbyjs.org/docs/custom-html/

And include your css in your static folders. That should work

**Comment by smthomas** [comment]
I think @herecydev's comment will help with your CSS question. In regards to your image question, I think you are likely using Gatsby Image (https://www.gatsbyjs.org/packages/gatsby-image/#image-processing-arguments). It's highly recommended to use Gatsby image for the performance benefits, however, it is possible to use your own img tags in your HTML if you would like and not use Gatsby Image.

**Comment by wybitnygracz** [comment]
@smakosh 
no i'm not using gatsby image, just <img tag. 
Now i see that gatsby make base64_ for some images only. Probably only for small images.

**Comment by wybitnygracz** [comment]
i just discovered `gatsby-plugin-tidy` this make css loading like i want.

**Comment by smakosh** [comment]
> @smakosh
> no i'm not using gatsby image, just <img tag.
> Now i see that gatsby make base64_ for some images only. Probably only for small images.

@smthomas*

**Comment by LekoArts** [comment]
Thank you for opening this!

> Therefore, I want remove all <style>CSS...</style> from my site. Then add CSS only this way <style href="static/style.css" />
How can i do this?

As the others have said you could place your CSS into the `static` folder and require it manually. However, we encourage to let the CSS be inlined for performance reasons.

> I also want to prevent my images from being placed this way: (<img src="data:..." ) i want my images to be accesible standard way like (<img src="statci/image.jpg");
How can i do this?

You are describing this behavior (on https://www.gatsbyjs.org/docs/importing-assets-into-files/#importing-assets-with-webpack):

> To reduce the number of requests to the server, importing images that are less than 10,000 bytes returns a data URI instead of a path. This applies to the following file extensions: svg, jpg, jpeg, png, gif, mp4, webm, wav, mp3, m4a, aac, and oga.

Again, this is a performance optimization we encourage and again you can mitigate this by using the `static` folder (https://www.gatsbyjs.org/docs/static-folder/).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
