### ISSUE TITLE
The result of this StaticQuery could not be fetched.

### ISSUE THREAD

**Issue by muhamed91** [gatsbyjs/gatsby#25131]
I dont know how to fix it!

**Comment by herecydev** [comment]
If you fill in the issue template it would help massively: https://github.com/gatsbyjs/gatsby/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by freiksenet** [comment]
Hi! 

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. 

Thanks!
