### ISSUE TITLE
gatsbyjs.org won't load in Microsoft Edge

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#25140]
## Description

The Gatsby website isn't loading at all in Microsoft Edge on Windows. It doesn't render and goes to a browser page that says "This page is having a problem loading." No markup or JavaScript errors, and it happens on all sections as far as I can tell. I can reproduce it on a virtual machine and a Surface both running Windows 10.

Changes are coming to the website, so this may be irrelevant over time. But I didn't see anyone report it yet and thought it should be tracked/fixed.

### Steps to reproduce

- Open gatsbyjs.org in Microsoft Edge
- See pages fail to load

### Expected result

The site should load

### Actual result

The site gets stuck on a browser error page. Maybe it's an issue with the service worker?

![Browser screenshot of Edge with the message This page is having a problem loading](https://user-images.githubusercontent.com/1045233/85189920-0779ff00-b268-11ea-9258-90ad9af1a683.png)

### Environment

Microsoft Edge 41.16299.1480.0
Microsoft EdgeHTML 16.16299

**Comment by doc-han** [comment]
Hi @marcysutton hope it works now because I'm on edge and the site loads perfectly
