### ISSUE TITLE
How to trigger build when new Shopify product is created?

### ISSUE THREAD

**Issue by josub** [gatsbyjs/gatsby#25141]
## Summary
What is the suggested method for triggering a new build for a gatsby site hosted on Netlify that's using the [Gatsby Source Shopify plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-shopify)  when a new product is created in Shopify? 

Is it a configuration in gatsby or is this done between Shopify and the host (Netlify)?

**Comment by AkashRajpurohit** [comment]
Hello @josub 
To ensure that you gatsby site is build everytime you make change in your shopify backend, what you need to do is setup a webhook.

Head to netlify dashboard and go to Settings -> Build & Deploy and look for `Build Hooks`
<img width="688" alt="Build Hooks" src="https://user-images.githubusercontent.com/30044630/85223518-7169e400-b3e1-11ea-91e7-8cbf839f0d7a.PNG">

And create a build hook, you will get a URL. 

Now head over to shopify backend, sorry I haven't used shopify admin but I think you have to find [events](https://shopify.dev/docs/admin-api/rest/reference/events/event?api[version]=2020-04) when you want to trigger a build and add this webhook URL provided by netlify.

**Comment by LekoArts** [comment]
Thank you for opening this!

> Is it a configuration in gatsby or is this done between Shopify and the host (Netlify)?

This is something you'll need to set up between Shopify and Netlify. As Akash already showed you can get a webhook URL to trigger a build on Netlify. Head to Shopify's community/documentation to find out how to hit that URL. I found [this article](https://medium.com/@emeruchecole9/building-an-e-commerce-store-with-gatsby-and-shopify-6af8558a301f) which suggets:

> Copy that and head over back to the Shopify store. Move to Settings > Notifications > Webhooks > Create webhook. For the event, choose Product creation, leave format as JSON and paste the URL from the Netlify build hook and hit Save webhook. Do this again two more times for Product deletion and Product update and any other event you feel may be necessary for a rebuild, while using the same URL from Netlify.
And that is it, as you add/update/delete products, Netlify rebuilds the site in a few minutes to reflect changes.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
