### ISSUE TITLE
[gatsby-transformer-remark] Add a way to get AST of Table of contents

### ISSUE THREAD

**Issue by iray-tno** [gatsbyjs/gatsby#25152]
## Summary

Adding a way to get AST of Table of contents just like the htmlAst property.

### Basic example

```graphql
{
  allMarkdownRemark {
    edges {
      node {
        html
        htmlAst
        tableOfContents
        tableOfContentsAst // <- add this
      }
    }
  }
}
```

### Motivation

When a user using htmlAst to customize the output DOM, they may want to access the AST of the table of contents too.
In my case, I'm using the htmlAst with `rehype-react`. When I want to add functionality to the table of contents, like emphasizing the header which a user is reading. It's very convenient if I can get the AST of the table of contents.

**Comment by PetroPavlenko** [comment]
Hi @freiksenet .
I'm using htmlAst with rehype and can all headers

```
import rehypeReact from "rehype-react";
const config = {
  createElement: React.createElement,
  Fragment: React.Fragment,
  components: {
    p: P,
    sup: Sup,
    a: StyledLink, 
    ol: Ol,
    ul: Ul,
    li: Li,
    h1: Heading1,
    h2: Heading2,
    h3: Heading3,
    h4: Heading4,
    h5: H5,
    b: Strong,
    i: Em,
    em: Em,
  },
};
const renderAst = new rehypeReact(astConfig).Compiler;

export const AstContent = ({ content, className }: AstContentProps) => (
  <div className={className}>
    {renderAst(content)}
  </div>
);
```
most tags are custom. And I can add styles how I want.
Not sure that's is answer to your question. But should be helpful )

**Comment by iray-tno** [comment]
Hi @PetroPavlenko . Maybe wrong mention? XD

Thanks for your comment.

Yeah, I'm doing the same thing with that for article content.
What I meant is I wanted to do that for the table of contents also.

By filtering elements except for headers, I can actually use the `htmlAst` for rendering the table of contents also.
But I think it's more convenient if I'm able to access AST of the table of contents.

**Comment by iray-tno** [comment]
This looks like the proper use-case of headings. #23546
I'll look into it a bit more tomorrow.

**Comment by iray-tno** [comment]
> I'll look into it a bit more tomorrow.

"tomorrow"... haha

Sorry for the late reply.

I actually could do everything I wanted to do with the `headings`.
And now it looks enough simple for me. Maybe some functionalities are difficult to implement with my idea (`htmlAst`).
`headings` were better than it.

This issue can be closed.
But since it's already assigned @pieh, I let this open,
