### ISSUE TITLE
Gatsby static site generator built with Deno

### ISSUE THREAD

**Issue by muhammad-mejanul-haque** [gatsbyjs/gatsby#25153]
### Will Gatsby change Nodejs to Deno? Is there any upcoming features related with [Deno ](https://deno.land/)in Gatsby?

If I want to create a long term web application with Gatsby, Should I worry about this Deno world?

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

We're currently not looking into Deno and don't plan on supporting it in the medium-term future. So for now you won't have to look into it when you want to use Gatsby.
