### ISSUE TITLE
Load custom html file at root path and gatsby files at all other paths.

### ISSUE THREAD

**Issue by und3fined-v01d** [gatsbyjs/gatsby#25168]
## Summary

I am currently migrating my blog from a custom blog engine to gatsby. I however want to keep my index.html of the original website as is. The index.html page runs its own code which is way different from the one for gatsby.

The gatsby code has following routes:

`/blog`
`/about`
`/contact`
`/notes`

Trying prefixPath adds a path prefix to all the above routes which is not what I want. I just want gatsby to load my index.html at root and its own files at the above mentioned routes. Can someone help me accomplish this?

**Comment by und3fined-v01d** [comment]
I am not sure how to title this appropriately...It would be lovely if someone helped with that as well. Let me know if you need more info.

**Comment by herecydev** [comment]
Why don't you just let gatbsy build your `/blog`, `/about`, etc. And then just add the index.html file into the `public` folder before deploying it?

**Comment by und3fined-v01d** [comment]
@herecydev I have one quick question. If there is no `index.js` file in my `pages` folder, will gatsby build a `index.html` in my public folder?

**Comment by herecydev** [comment]
I haven't tested it but I doubt it would. I think it creates only the pages which you've specified

**Comment by und3fined-v01d** [comment]
Let me try this one out...I'll update you on it.

**Comment by LekoArts** [comment]
Thank you for opening this!

As herecydev correctly said you don't have to have a `pages/index.js` file. Gatsby only creates pages for files inside that folder, not automatically any other files.
You can place your `index.html` file into the `static` folder (https://www.gatsbyjs.org/docs/static-folder/) as Gatsby then will copy this file over to your `public` folder.

![image](https://user-images.githubusercontent.com/16143594/85252090-402dfa00-b45b-11ea-83f1-46321f501618.png)

You might need to run a `gatsby build` to copy the things over first.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by und3fined-v01d** [comment]
@LekoArts and @herecydev, the solution pointed me to the right direction. Thank you so much.
