### ISSUE TITLE
LocalizedLink adds "currentslug" to LocalizedLink

### ISSUE THREAD

**Issue by DaTurboD** [gatsbyjs/gatsby#25170]
The LocalizedLink Component from the [example provided by Gatsby](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-i18n) is somehow working in an unexpected way for me.

In "...config/i18n" i have defined two languages:
- german (default), path "" and
- english, path "en"

and with Styled Components i am creating these links like
```js
export const LogoLink = styled(LocalizedLink)`
  display: inline-block;
  margin-right: auto;
  width: 170px;
`;
```
For the default language everything is working as expected but for english language there are slugs created which i can't explain.

```js
import React from 'react';
import { Link } from 'gatsby';
import { LocaleContext } from '../Layout';
import locales from '../../../config/i18n';

// Use the globally available context to choose the right path
const LocalizedLink = ({ to, ...props }) => {
  const { locale } = React.useContext(LocaleContext);

  const isIndex = to === `/`;

  // If it's the default language, don't do anything
  // If it's another language, add the "path"
  // However, if the homepage/index page is linked don't add the "to"
  // Because otherwise this would add a trailing slash
  const path = locales[locale].default
    ? to
    : `${locales[locale].path}${isIndex ? `` : `${to}`}`;

  return <Link {...props} to={path} />;
};

export default LocalizedLink;
```

This function is getting the path for english language ("en") and concatenates them with the input link. But somehow the LocalizedLink functions always adds the slug of the current page and then adds the path and the destination link.
For example i want to go to "/en/gis/" from "/en" and it points to "/en/en/gis/".

Now the weird thing for me is that if i change the LocalizedLink function to for example
```js
const path = locales[locale].default
    ? to
    : `what${to}`;
``` 
the created link is "en/what/gis". So now it suddenly adds the "en/" automatically. But if i change it like
```js
const path = locales[locale].default
    ? to
    : `${to}`;
``` 
the link points to "/gis".

Any help is highly appreciated.

[Repository](https://github.com/DaTurboD/GIS-Netzwerk)

I cloned the example Repo and it has the same issue
![grafik](https://user-images.githubusercontent.com/40794289/85223818-0363f380-b3c6-11ea-8572-d0acc187a6a1.png)

It worked fine before i updated Gatsby but unfortunately i cannot tell which version it was.

**Comment by herecydev** [comment]
That's an expected outcome I think. I believe you're supposed to use `LocalizedLink to="/gis"` and that would automatically prefix the locale if **it's not the default**. i.e:

- german (default) => /gis
- en => /en/gis
- french => fr/gis

**Comment by DaTurboD** [comment]
> That's an expected outcome I think. I believe you're supposed to use `LocalizedLink to="/gis"` and that would automatically prefix the locale if **it's not the default**. i.e:
> 
>     * german (default) => /gis
> 
>     * en => /en/gis
> 
>     * french => fr/gis

Thats what i am doing but the result looks like "en/en/gis" when i am currently at "en".
When i want to navigate to "/en/gis" from "/en/page123/ it will put out "/en/page123/en/gis".

**Comment by herecydev** [comment]
I'm not totally sure, for what it's worth I wrote a plugin to solve this which you can find here: https://github.com/herecydev/gatsby-plugin-internationalization

It might be that the localizedLink from the examples hasn't been updated since they supported proper relative paths.

**Comment by LekoArts** [comment]
This will be fixed by https://github.com/gatsbyjs/gatsby/pull/25180 - without the slash the links are relative.
Thanks for the report!
