### ISSUE TITLE
[gatsby-transformer-remark] Cannot write custom "local" plugins without publishing them as packages

### ISSUE THREAD

**Issue by dantman** [gatsbyjs/gatsby#25179]
## Summary

It is not possible to write "local" plugins for gatsby-transformer-remark. A plugin only works if you turn it into a full NPM package.

All of the following potential methods for using a local module as a plugin just throw a `Error: Unable to find plugin "[...]". Perhaps you need to install its package?` error.

```js
{
  resolve: "./src/plugins/my-custom-plugin",
  options: {},
},
{
  resolve: require.resolve("./src/plugins/my-custom-plugin"),
  options: {},
},
{
  resolve: require("./src/plugins/my-custom-plugin"),
  options: {},
},
```

### Motivation

Not every use case for a remark transformer plugin warrants a full npm plugin. Some use cases can be project specific. e.g. I wanted to add a CC-0 footer to my code blocks after the Prism plugin handled them but none of the existing plugins could do that and this use case is too specific to publish a plugin to npm for.

**Comment by LekoArts** [comment]
As per https://www.gatsbyjs.org/docs/loading-plugins-from-your-local-plugins-folder/ you should put your `plugins` folder at the root level. I have a project working with a local remark plugin:

![image](https://user-images.githubusercontent.com/16143594/85250925-39ea4e80-b458-11ea-8297-d83298fd9362.png)

So please provide a [minimal reproduction][reproduction] of your project. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by dfireBird** [comment]
So I got similar error in `gatsby-plugin-mdx` where I can't use a local plugin in `gatsbyRemarkPlugins` property. It shows lot of error that it can't find the specified plugin but when I install it as npm package it doesn't show up any error

**Comment by wardpeet** [comment]
@dfireBird does your plugin has a package.json? A plugin needs a package.json to work.

If it's still not working then I feel it will be resolved by https://github.com/gatsbyjs/gatsby/issues/21592

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
