### ISSUE TITLE
404 on docs/node-apis/ for source code

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#25206]
## Description

404 Error on docs/node-apis/ for source code

### Steps to reproduce

- open https://www.gatsbyjs.org/docs/node-apis/#onCreateWebpackConfig
- click on any source link 

### Expected result

- show source code on github

### Actual result

- 404 for all Source links:

### Related Code

www/src/components/api-reference/doc-block.js

### Related Issues

**Comment by LekoArts** [comment]
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/24914

**Comment by muescha** [comment]
oh yes - i searched for this in issues and pr and did not found them :(
