### ISSUE TITLE
302 instead of 404?

### ISSUE THREAD

**Issue by wybitnygracz** [gatsbyjs/gatsby#25210]
Hi, 
sometimes after changing product status to "sold out " product come back after some time. 
Probably in case of products 302 header will be better instead of 404

How can config gatsby 302 header for non existing urls but only with certain urls (for example if in url there is "product").

**Comment by LekoArts** [comment]
Thank you for opening this!

This isn't something you configure in Gatsby but with your hosting provider/setup. So please reach out to the communities of the solution you use for hosting your site.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
