### ISSUE TITLE
bug(gatsby-source-shopify):  "Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: `products___NODE`. There is no corresponding node with the `id` field matching"

### ISSUE THREAD

**Issue by iKeeko** [gatsbyjs/gatsby#25217]
Hi, I'm attempting to build an ecommerce with gatsby using gatsby-source-shopify

I'm seeing console error
- Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: `products___NODE`. There is no corresponding node with the `id` field matching:

I'm seeing the error on both command "gatsby develop" and "gatsby build"
I found the previous issue#14193 but couldn't understand how it solved.

From gatsby-source-shopify docs. there's no clear instructions on how to expose metafield to the Shopify Storefront API from gatsby side or config.

I opened as a bug issue because sometimes the gatsby develop and build works with no issue.
almost like 50% of the time works with no error and 50% failing to run develop/build with the above error.

package version:
"gatsby": "^2.21.0"
 "gatsby-source-shopify": "^3.2.3"

Thank you

**Comment by madalynrose** [comment]
Hi @iKeeko !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and also include information from running `gatsby info --clipboard` and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by iKeeko** [comment]
Hi @madalynrose sorry, a little late.

here is the minimal repo with the exact packages and configs I used where this error happening with gatsby-source-shopify

gatsby clipboard is in it too as a txt file.

[https://github.com/iKeeko/gatsby-repro](url)

Thank you

**Comment by willTastyMakers** [comment]
I too have been getting the bug. Sometimes running` gatsby clean` works, but other times it does not. When it does not ,I  run ` gatsby develop ` 3 or 4 times in a row without running  ` gatsby clean ` or else I have to have also remove node_modules, run clean,  run install, and finally `gatsby develop`.

**Comment by willTastyMakers** [comment]
i@ascorbic Has there been any updates on the issue. I too have been experience the same problems as @iKeeko and I wondering we can begin to figure out why this is happening. Could it have something to do with this issue that was posted in the gastsbyjs repo https://github.com/gatsbyjs/gatsby/issues/14193 ?

**Comment by iKeeko** [comment]
> i@ascorbic Has there been any updates on the issue. I too have been experience the same problems as @iKeeko and I wondering we can begin to figure out why this is happening. Could it have something to do with this issue that was posted in the [gastsbyjs](https://github.com/gatsbyjs/gatsby/issues) repo [Invariant Violation: Encountered an error trying to infer a GraphQL type #14193](https://github.com/gatsbyjs/gatsby/issues/14193) ?

Nope, I'm afraid they haven't got back to us. I wonder how people using this in production with random errors u have no idea where it's coming from or maybe just lack of documentation for not so genius developer like me.

This is the only thing stopping me to migrate woocommerce site to gatsby ecommerce

**Comment by amandasaffer** [comment]
+1. Also having this issue. I simply followed the basic [Shopify E-Commerce](https://www.gatsbyjs.com/docs/building-an-ecommerce-site-with-shopify/) tutorial on the gatsby site and ran into this issue immediately. I've tried modifying the query to a more basic version and can't seem to replicate the issue consistently with any one query.

**Comment by Sean-93** [comment]
I'm also getting this issue immediately after trying the same Gatsby Shopify tutorial.

**Comment by leofrozenyogurt** [comment]
this is still an issue

**Comment by iamkratos** [comment]
I'm also having this issue, but it seems to be related to the products I'm sourcing. I tried the same setup with a different store of products, and it runs without a problem.....

**Comment by Jamal1337** [comment]
I had the exact same issue and were trying back and forth the last hours until I tried different versions of the "gatsby-source-shopify" plugin.

Finally version 3.1.2 worked for me. What versions are you guys using? Maybe the older one will work for you as well.

`"gatsby-source-shopify": "3.1.2",`

**Comment by iamkratos** [comment]
@Jamal1337 Thanks for the tip. I tried downgrading to 3.12, but it's still broken for me. Was that the only change that fixed the error?

**Comment by a5okol** [comment]
@Jamal1337 This is not helped me.

I add variable GATSBY_STALL_TIMEOUT=120000 and It worked.

**Comment by Cerom** [comment]
I'm having the same issue with a Shopify shop containing thousands of items.
The build/develop processes keep crashing at some point while fetching the Collections nodes.

I tried lowering the paginationSize in the plugin options but it didn't help and thought maybe the latest Gatsby & plugin update would solve that but it didn't.
I could just use the Shopify Buy SDK but I can't create page dynamically if I don't load it through GraphQL so I'm stuck.

```
"gatsby": "^3.0.0",
"gatsby-source-shopify": "^4.0.0",
```

**Comment by blancomaberino** [comment]
> I'm having the same issue with a Shopify shop containing thousands of items.
> The build/develop processes keep crashing at some point while fetching the Collections nodes.
> 
> I tried lowering the paginationSize in the plugin options but it didn't help and thought maybe the latest Gatsby & plugin update would solve that but it didn't.
> I could just use the Shopify Buy SDK but I can't create page dynamically if I don't load it through GraphQL so I'm stuck.
> 
> ```
> "gatsby": "^3.0.0",
> "gatsby-source-shopify": "^4.0.0",
> ```

Same here but without having thousands of products on the site, just a couple of 10s.

**Comment by leofrozenyogurt** [comment]
note sure why it was removed but setting GATSBY_STALL_TIMEOUT = 120000 worked for me

**Comment by dungle-scrubs** [comment]
I'm experiencing the same, or at least a [very similar issue](https://github.com/gatsbyjs/gatsby/discussions/31089), but from a plugin I created rather than from `gatsby-source-shopify`.

**Comment by LekoArts** [comment]
We released a new major version (v5) that fundamentally works different. Please upgrade and you shouldn't see this issue anymore.
