### ISSUE TITLE
Need help with creating two different posts types on gatsby-node.js 

### ISSUE THREAD

**Issue by judepark** [gatsbyjs/gatsby#25214]
I'm trying to create a second blog post type on gatsby-node.js.

I need to identify the different markdown files I have so I can create a unique url structure for them. I can already identify "notes" files, and want to create a second type called "projects".

My gatsby-node.js file looks like this right now
```
const path = require('path');
const { createFilePath } = require('gatsby-source-filesystem');

// Look at every node when it is created
exports.onCreateNode = ({node, getNode, actions}) => {
	// Check for markdown nodes
	const { createNodeField } = actions;
	if(node.internal.type === 'MarkdownRemark') {
		// Create a slug out of the markdown filepath name
		const slug = createFilePath({
			node,
			getNode,
			basePath: 'notes'
		});
		// Add the newly created slug to the node itself
		createNodeField({
			node,
			name: 'slug',
			value: `/note${slug}`
		});
	}
};

exports.createPages = ({ graphql, actions }) => {
	const { createPage } = actions
	return new Promise((resolve, reject) => {
	  graphql(`
		{
		  allMarkdownRemark {
			edges {
			  node {
				fields {
				  slug
				}
			  }
			}
		  }
		}
	  `).then(result => {
		result.data.allMarkdownRemark.edges.forEach(({ node }) => {
		  createPage({
			path: node.fields.slug,
			component: path.resolve(`./src/templates/note.js`),
			context: {
			  // Data passed to context is available in page queries as GraphQL variables.
			  slug: node.fields.slug,
			},
		  })
		})
		resolve()
	  })
	})
  };
```

I don't know if I have to have 2 different graphql queries or if i have to separate the markdown files on CreatePages.. I learn better through example so if you can show me how you might accomplish the task I might be able to understand this!

**Comment by mcropper** [comment]
This may be of use to you:
 [Using multiple queries or entries on gatsbyjs createPages Node API](https://swas.io/blog/using-multiple-queries-on-gatsbyjs-createpages-node-api/)

**Comment by judepark** [comment]
I guess I get confused at the 

```
const path = require('path');
const { createFilePath } = require('gatsby-source-filesystem');
```

If I rewrite the function to have two separate pathways, it throws the error message "Cannot query field "fields" on type "MarkdownRemark" ". This isn't my original code so I'm trying to understand how to change this to produce a second file type without rewriting the entire gatsby-node.js file.

**Comment by LekoArts** [comment]
Thank you for opening this!

As per https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#how-to-query the `name` you define for `gatsby-source-filesystem` is automatically the `sourceInstanceName`. You can access this information not only in your GraphQL queries but also in the Node API lifecycle methods.

## Example

`gatsby-config.js`

```js
module.exports = {
  return {
    siteMetadata: {},
    plugins: [
      {
        resolve: `gatsby-source-filesystem`,
        options: {
          name: "notes",
          path: "path-to-notes-dir",
        },
      },
      {
        resolve: `gatsby-source-filesystem`,
        options: {
          name: "projects",
          path: "path-to-projects-dir",
        },
      },
    ],
  }
}
```

`gatsby-node.js`

```js
const pathMap = {
  notes: "/notes",
  projects: "/projects",
}

exports.onCreateNode = ({ node, actions, getNode, createNodeId, createContentDigest }, themeOptions) => {
  const { createNode } = actions

  // Make sure that it's an Markdown node
  if (node.internal.type !== `MarkdownRemark`) {
    return
  }

  // Create a source field
  // And grab the sourceInstanceName to differentiate the different sources
  const fileNode = getNode(node.parent)
  const source = fileNode.sourceInstanceName

  if (node.internal.type === `MarkdownRemark`) {
	// Do something only for markdown files
	// e.g. use pathMap[source] to get the correct path-prefix
  }
}
```

**Comment by judepark** [comment]
I am having the hardest time trying to get it to work...  🤕 Do I need to rewrite my entire gatsby-node.js file? I keep getting the error message **Cannot query field "fields" on type "MarkdownRemark"** everytime I try to rewrite it in whichever way.

**Comment by LekoArts** [comment]
Please provide a [minimal reproduction][reproduction] or alternatively link your complete project as we can't help otherwise. Thanks! :)

[reproduction]: https://gatsby.dev/reproduction

**Comment by judepark** [comment]
Thank you, does this help? https://codesandbox.io/s/broken-hooks-rx98x?file=/gatsby-config.js

**Comment by LekoArts** [comment]
Yeah, that helped!

I forked your codesandbox and added the behavior you were after:

![image](https://user-images.githubusercontent.com/16143594/85674103-d87ae780-b6c4-11ea-8df9-b567416b6105.png)

You can find it here: https://codesandbox.io/s/issue-25214-xrnpz (live preview at https://xrnpz-8000.sse.codesandbox.io)

For archival reasons, here's the important snippet from `gatsby-node.js` and `gatsby-config.js`:

```js
const path = require("path")
const { createFilePath } = require("gatsby-source-filesystem")

const pathMap = {
  note: "notes",
  project: "projects"
}

exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions

  if (node.internal.type !== "MarkdownRemark") {
    return
  }

  const fileNode = getNode(node.parent)
  const source = fileNode.sourceInstanceName

  const slug = createFilePath({
    node,
    getNode,
    basePath: pathMap[source]
  })
  createNodeField({
    node,
    name: "slug",
    value: `/${source}${slug}`
  })
  createNodeField({
    node,
    name: "template",
    value: source
  })
}

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions

  const result = await graphql(`
    {
      allMarkdownRemark {
        edges {
          node {
            fields {
              slug
              template
            }
          }
        }
      }
    }
  `)

  result.data.allMarkdownRemark.edges.forEach(({ node }) => {
    createPage({
      path: node.fields.slug,
      component: path.resolve(`./src/templates/${node.fields.template}.js`),
      context: {
        // Data passed to context is available in page queries as GraphQL variables.
        slug: node.fields.slug,
        template: node.fields.template
      }
    })
  })
}
```

and

```js
module.exports = {
  plugins: [
    {
      resolve: "gatsby-source-filesystem",
      options: {
        path: `${__dirname}/src/notes`,
        name: "note"
      }
    },
    {
      resolve: "gatsby-source-filesystem",
      options: {
        path: `${__dirname}/src/projects`,
        name: "project"
      }
    },
  ]
}

```

---

While this is working now I'd highly advise you to follow our tutorial (https://www.gatsbyjs.org/tutorial/) as I have seen that you removed necessary dependencies (like react, react-dom), installed gatsby plugins that you didn't use and with missing dependencies, used React components in e.g. src/pages/index.js that aren't existent anymore.
So you gonna need to cover some basics so that you can dive further into Gatsby :) But you'll champion that, have fun! :)

**Comment by judepark** [comment]
Thank you !

**Comment by wilmerterrero** [comment]
> Yeah, that helped!
> 
> I forked your codesandbox and added the behavior you were after:
> 
> ![image](https://user-images.githubusercontent.com/16143594/85674103-d87ae780-b6c4-11ea-8df9-b567416b6105.png)
> 
> You can find it here: https://codesandbox.io/s/issue-25214-xrnpz (live preview at https://xrnpz-8000.sse.codesandbox.io)
> 
> For archival reasons, here's the important snippet from `gatsby-node.js` and `gatsby-config.js`:
> 
> ```js
> const path = require("path")
> const { createFilePath } = require("gatsby-source-filesystem")
> 
> const pathMap = {
>   note: "notes",
>   project: "projects"
> }
> 
> exports.onCreateNode = ({ node, getNode, actions }) => {
>   const { createNodeField } = actions
> 
>   if (node.internal.type !== "MarkdownRemark") {
>     return
>   }
> 
>   const fileNode = getNode(node.parent)
>   const source = fileNode.sourceInstanceName
> 
>   const slug = createFilePath({
>     node,
>     getNode,
>     basePath: pathMap[source]
>   })
>   createNodeField({
>     node,
>     name: "slug",
>     value: `/${source}${slug}`
>   })
>   createNodeField({
>     node,
>     name: "template",
>     value: source
>   })
> }
> 
> exports.createPages = async ({ graphql, actions }) => {
>   const { createPage } = actions
> 
>   const result = await graphql(`
>     {
>       allMarkdownRemark {
>         edges {
>           node {
>             fields {
>               slug
>               template
>             }
>           }
>         }
>       }
>     }
>   `)
> 
>   result.data.allMarkdownRemark.edges.forEach(({ node }) => {
>     createPage({
>       path: node.fields.slug,
>       component: path.resolve(`./src/templates/${node.fields.template}.js`),
>       context: {
>         // Data passed to context is available in page queries as GraphQL variables.
>         slug: node.fields.slug,
>         template: node.fields.template
>       }
>     })
>   })
> }
> ```
> 
> and
> 
> ```js
> module.exports = {
>   plugins: [
>     {
>       resolve: "gatsby-source-filesystem",
>       options: {
>         path: `${__dirname}/src/notes`,
>         name: "note"
>       }
>     },
>     {
>       resolve: "gatsby-source-filesystem",
>       options: {
>         path: `${__dirname}/src/projects`,
>         name: "project"
>       }
>     },
>   ]
> }
> ```
> 
> While this is working now I'd highly advise you to follow our tutorial (https://www.gatsbyjs.org/tutorial/) as I have seen that you removed necessary dependencies (like react, react-dom), installed gatsby plugins that you didn't use and with missing dependencies, used React components in e.g. src/pages/index.js that aren't existent anymore.
> So you gonna need to cover some basics so that you can dive further into Gatsby :) But you'll champion that, have fun! :)

MAN YOU ARE THE BEST IN THE WORLD
