### ISSUE TITLE
Gatsby-plugin-react-helmet doesn't work if there is replaceRenderer function in gatsby-ssr.js file

### ISSUE THREAD

**Issue by Ilham-Pratama** [gatsbyjs/gatsby#25224]
## Description

As we know that Gatsby-plugin-react-helmet makes your react-helmet tags ready in sever-side. But unfortunately, that feature will not work if you have replaceRenderer function in your gatsby-ssr file. I'd like to know why, and What can I do in order to make it work.

### Steps to reproduce

- Create new gatsby project by running`gatsby new my-hello-world-starter https://github.com/gatsbyjs/gatsby-starter-hello-world`
- Install gatsby-plugin-react-helmet and react-helmet
- create gatsby-ssr.js file in root folder and add this simple piece of code into that file
```
export const replaceRenderer = ({ replaceBodyHTMLString }) => {
  replaceBodyHTMLString('<div id="___gatsby"></div>');
};
```
- Add simple Helmet component to `src/pages/index.js`, like: 
```
import React from "react"
import { Helmet } from "react-helmet"

export default function Home() {
  return <>
    <Helmet title="My Site">
      <meta property="og:url" content='example.com' />
      <meta property="og:type" content="website" />
      <meta property="og:site_name" content='sample site' />
    </Helmet>
    <div>Hello world!</div>
  </>
}
```
- run `gatsby build` and check the static index.html, you won't see your Helmet tags you just added until you check the web console

### Expected result

Helmet tags should be ready in server side

### Actual result

It's not ready in server side, you have to check the console in order to see those tags

### Environment

My Project's environtment
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.23.3 => 2.23.3
    gatsby-image: ^2.4.7 => 2.4.7
    gatsby-plugin-chakra-ui: ^1.0.0-next.1 => 1.0.0-next.1
    gatsby-plugin-google-tagmanager: ^2.3.5 => 2.3.5
    gatsby-plugin-manifest: ^2.4.12 => 2.4.12
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.4
    gatsby-plugin-sharp: ^2.6.12 => 2.6.12
    gatsby-plugin-sitemap: ^2.4.5 => 2.4.5
    gatsby-source-filesystem: ^2.3.12 => 2.3.12
    gatsby-source-graphql: ^2.5.5 => 2.5.5
    gatsby-transformer-json: ^2.4.5 => 2.4.5
    gatsby-transformer-sharp: ^2.5.5 => 2.5.5
  npmGlobalPackages:
    gatsby-cli: 2.12.29
```

**Comment by LekoArts** [comment]
Thank you for opening this!

What you're describing is expected behavior. On https://www.gatsbyjs.org/docs/ssr-apis/#replaceRenderer it says:
> Replace the default server renderer.

And on https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody it says:
> Using this API over replaceRenderer is preferable as multiple plugins can implement this API where only one plugin can take over server rendering. However, if your plugin requires taking over server rendering then that’s the one to use

By using `replaceRenderer` you're overwriting the contents of https://github.com/gatsbyjs/gatsby/blob/a72caa67f85907ddf394d21c4b645e5a58bf32c4/packages/gatsby-plugin-react-helmet/src/gatsby-ssr.js

So you should use the `onRenderBody` API instead.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by Ilham-Pratama** [comment]
Thank you @LekoArts for your fast respond, I really appreciate that.
Weirdly, when I remove the replaceRenderer function, I ran into this error.
```
 ERROR #95313
Building static HTML failed for path "/404/"
See our docs page for more info on this error: https://gatsby.dev/debug-html

  WebpackError: TypeError: Object is not iterable (cannot read property Symbol(Symbol.iterator))

  - build-html.js:107 doBuildPages
    [rim-site-react]/[gatsby]/dist/commands/build-html.js:107:24

  - build-html.js:121 async buildHTML
    [rim-site-react]/[gatsby]/dist/commands/build-html.js:121:3

  - build.js:206 async build
    [rim-site-react]/[gatsby]/dist/commands/build.js:206:5
```

**Comment by doublejosh** [comment]
I'm getting the same failure with a `onPreRenderHTML` in `gatsby-ssr.js`

I'm using `replaceHeadComponents` and `getHeadComponents` to inject a script at the top of <head>
