### ISSUE TITLE
 How to prevent components unmount when the route changes but the template does not change

### ISSUE THREAD

**Issue by AboyL** [gatsbyjs/gatsby#25220]
## Summary
On the current page, I have a scrolling content. At this time, I scrolled to the middle. When I clicked a link to switch to another route, the scrolling position returned to the original position because the component was unmounted, but for this For both routes, I use the same template. What should I do to keep the scroll position consistent after switching routes?

I hope to achieve an effect similar to [antd](https://ant.design/components/checkbox-cn/#components-checkbox-demo-group) although they are not achieved using GATSBY

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by madalynrose** [comment]
Hi there @AboyL! You should be able to override this behavior using Gatsby's [shouldUpdateScroll Browser API](https://www.gatsbyjs.org/docs/browser-apis/#shouldUpdateScroll).
