### ISSUE TITLE
How to manage secrets with Gatsby?

### ISSUE THREAD

**Issue by ptrhck** [gatsbyjs/gatsby#25222]
After reading [this](https://www.gatsbyjs.org/blog/2018-11-07-gatsby-for-apps/) blog post about Gatsby, I am considering to use it for a Mapbox app, which is outlined [here](https://medium.com/@brendan_ward/migrating-from-create-react-app-and-leaflet-to-gatsbyjs-and-mapbox-gl-98b49c2e75c4). I would like to pick this up to ask the following questions: How do you manage secrets within a Gatsby app?

I know that there are client only routes which will be rendered, e.g. after a user is logged in. However, how do I manage secrets of third party services such as Mapbox as my site is completely static? With the provided Mapbox article, is any user capable of seeing my Mapbox secret key? What is the best way to manage such things with gatsby?

**Comment by NotMoni** [comment]
@ptrhck  you can use [.env](https://www.npmjs.com/package/dotenv) files to define your api code

**Comment by madalynrose** [comment]
Yes, @NotMoni is correct! You can see more about using .env variables in Gatsby in this [doc](https://www.gatsbyjs.org/docs/environment-variables/) that goes through a couple different use cases.

**Comment by wardpeet** [comment]
Thank you for opening this, @ptrhck

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by ptrhck** [comment]
I do understand how to use API keys for example at build time. However, as far as I understand, mapbox needs the access token at runtime. In that case, someone could grab the key from the client side js and use it somewhere else. Am I missing something here how to handle this use case with gatsby?

**Comment by NotMoni** [comment]
Hey, @ptrhck Check this out.

**Comment by LekoArts** [comment]
> In that case, someone could grab the key from the client side js and use it somewhere else. Am I missing something here how to handle this use case with gatsby?

This isn't a specific problem to Gatsby or even React. You'll always have this problem when needing to make request with a key you don't want to expose.
You'll need to create a little Node/Express backend where you can send the requests to and which then will make the actual API call with the token and send the data back. Using Google will give you plenty of results, e.g. https://github.com/react-boilerplate/react-boilerplate/issues/1744#issuecomment-303112505

**Comment by ptrhck** [comment]
@NotMoni 
I absolutely understand, thanks for your detailed answer! In this case, however, there is some backend server involved, e.g. gatsby develop server.

@LekoArts 
That is excatcly what I was looking for, many thanks! Do you know of any example Gatsby/Node repo that has an example implementation?

**Comment by NotMoni** [comment]
Try this: https://www.gatsbyjs.org/packages/gatsby-source-apiserver/
