### ISSUE TITLE
Broken URL on packages/gatsby-transformer-remark/README.md

### ISSUE THREAD

**Issue by dididy** [gatsbyjs/gatsby#25244]
## Summary

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/README.md

- Above links url's REAMDE.md has problem of containing broken url
- Below sentence is 39 lline on `/packages/gatsby-transformer-remark/README.md`
> The details of the Remark options above could be found in [`remark-parse`'s documentation](https://github.com/remarkjs/remark/tree/master/packages/remark-parse#processoruseparse-options)
- You can check `remark-parse's documentation is return 404 page of github

### Motivation

- I want to check `options.commonmark`, `options.footnotes`, `options.pedantic`, `options.gfm` options but it cannot possible now.

## Steps to resolve this issue

- I found `remark`'s default branch changed `master` to `main` so that link need to revise like below.

> Current
https://github.com/remarkjs/remark/tree/master/packages/remark-parse#processoruseparse-options

> Need to modify
https://github.com/remarkjs/remark/tree/main/packages/remark-parse#processoruseparse-options

### Draft the doc

- None

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by wardpeet** [comment]
This might not be 100% what you're looking for but something like this is more or less what I think you're looking for.

```
const CustomRoute = ({ component: Component, location, ...rest }) => {
  if (location.pathname.startsWith('/app/secure')) {
    return <PrivateRoute component={Component} location={location} {...rest} />
  }

  return <Component location={location} {...rest} />
}
```

Thank you for raising this question. If you think we should add extra notes to the tutorial, please let us know.
For more guidance and help I suggest you go to [Discord](https://gatsby.dev/discord). 

Cheers!
Ward

**Comment by wardpeet** [comment]
Sorry closed the wrong issue. Thank you for opening this issue! We're happy to receive a pull request.

More info how to get started can be found at https://www.gatsbyjs.org/contributing/

**Comment by Ranjith10** [comment]
I would like to take this issue @wardpeet
