### ISSUE TITLE
[www/blog] Allow Markdown in `<Pullquote citation>`

### ISSUE THREAD

**Issue by mgienow** [gatsbyjs/gatsby#25240]
Hello!  I would like to request a feature to go with the <Pullquote> component. 

The `<Pullquote>` component, which is allowed in MDX, supports setting an optional `citation` like so:  `<Pullquote citation="Dennis Brotzky, Founding Partner, Narative">`.

The feature I'm requesting is the ability to add links to the citation, e. g. if we want to link to the website of the person we attributed the quote to. In MDX this would be `Dennis Brotzky, Founding Partner, [Narative](https://www.narative.co/)` but putting in the markdown link does not work in the `<Pullquote citation="">` context.

Thanks!

**Comment by fk** [comment]
Hey @mgienow! 🤗 🎉 
Welcome, and thanks for opening this!

To add to your great issue description, [here's that `<Pullquote>` component](https://github.com/gatsbyjs/gatsby/blob/a40fd01c9e4998eea00f856bba63dc6a0b956d76/www/src/components/shared/pullquote.js).

---

I can see a couple of ways enabling this, but given my very shallow understanding of MDX, I can't help but think that the easiest probably would be to use [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml). 🤭 

I also wouldn't be surprised if I don't see the forest for the trees! 😅 

Pinging the @gatsbyjs/website superfriends for help! Is there an (easy) way to apply Markdown/MDX magic to the `citation` field, or … hmm, maybe nesting a `<Citation>` in `<Pullquote>`, with both rendering MDX?

/cc @gillkyle

**Comment by fk** [comment]
So turns out I didn't see that forest for those trees. 😅 🤦 🤷 

@sidharthachatterjee to the rescue ❤️ — we can pass [JSX](https://reactjs.org/docs/introducing-jsx.html) to `citation` like so:

```jsx
<Pullquote
  citation={
    <span>
      Dennis Brotzky, Founding Partner,{" "}
      <a href="https://www.narative.co/">Narative</a>
    </span>
  }
>
  “Partnering with Gatsby has been a strong driver for growth. Our clients love
  the performance benefits and our developers are happy to use tools they
  already love.”
</Pullquote>
```

Thank you Sid! 🤗 
Follow-up PR to #25239 incoming!

**Comment by fk** [comment]
https://github.com/gatsbyjs/gatsby/pull/25251

**Comment by muescha** [comment]
it can done the way like in:
- #25414 `fix(blog): Gatsby Partner program - add links back to Pullquote` 

but the JSX code should be in **one line** until `remark-mdx` is implemented in:
- #25290 `enhancement (docs): Improvements to retext-spell`  *(part: implement `remark-mdx`)*

**Comment by muescha** [comment]
```html
<Pullquote>
  “Partnering with Gatsby has been a strong driver for growth. Our clients love
  the performance benefits and our developers are happy to use tools they
  already love.”
  <PullquoteCitation>
    Dennis Brotzky, Founding Partner, [Narative](https://www.narative.co/)
  <PullquoteCitation>
</Pullquote>
```

maybe is this syntax possible? then inside the `PullquoteCitation` the text is converted as markdown?

**Comment by muescha** [comment]
related: 
- https://github.com/mdx-js/mdx/issues/628 `RFC: Interleaving Markdown in JSX`

**Comment by fk** [comment]
Oh yes, thank you @muescha! 🙏 🤗
Was searching for something like this when we ran into this problem, but didn't find anything. Great to see it added to the v2 milestone!

**Comment by muescha** [comment]
As workaround befoee 2.0 maybe we can run the markdown convent in the component itself with the unified remark?

**Comment by muescha** [comment]
not stale

**Comment by LekoArts** [comment]
Since the blogposts were moved to Wordpress (including the individual components like Pullquote) we can close this issue.
