### ISSUE TITLE
retext-spell failing CI on warnings

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#25268]
## Description

With https://github.com/gatsbyjs/gatsby/pull/24372 merged, there are some lint failures on the master branch that can be inspected with Circle CI: https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/44142/workflows/1136923a-d2a9-4a57-98f1-631d0ee3ccc8/jobs/447601/steps

Looks like retext-spell is having a tough time with proper nouns, and the `--frail` flag fails them by default: `remark --quiet --frail "./docs/"`. Is it possible to disable this somehow, so we don't have to add every proper noun to the dictionary? Until we make a change to the lint configuration, every docs PR will fail the linter.

### Steps to reproduce

Look at any recent docs PR compared against master (as of a couple hours ago): https://github.com/gatsbyjs/gatsby/pull/25267

### Expected result

Warnings should not fail the linter, or at the very least it should be more tolerant of proper nouns.

### Actual result

The current lint configuration is failing the build for every docs PR.

**Comment by tesseralis** [comment]
There's a script `scripts/update-dictionary.js` that automatically adds all new words (mostly proper nouns) to `dictionary.txt`. I ran it when creating #25270. I forgot to add documentation for it with the initial PR. I'll make a follow-up to do it and add more words!
