### ISSUE TITLE
Locally hosting fonts w/ typography

### ISSUE THREAD

**Issue by foggy1** [gatsbyjs/gatsby#2526]
If I use gatsby-plugin-typography, under the hood, it does the following, courtesy of react-typography:

```
exports.onRenderBody = ({ setHeadComponents }, pluginOptions) => {
  setHeadComponents([
    <TypographyStyle key={`TypographyStyle`} typography={typography} />,
    <GoogleFont key={`GoogleFont`} typography={typography} />,
  ])
}
```
With Typefaces, however, it's really easy for me to host, say, Merriweather and Merriweather Sans myself, making the GoogleFont the one extra stylesheet I have to pull in.

If I manually configure typography (which really isn't all that much work) with typefaces, I can configure around this stuff, linking the styles but not the font. Unless I'm missing something, it would be nice to have a plugin option that allowed a user to omit the GoogleFont link. I can PR something if this sounds like it's worth it.

Seems like if the plugin takes options, this might be a good one.

**Comment by KyleAMathews** [comment]
I think it'd be easier perhaps to just delete the `googleFonts` key off the theme you're using?

**Comment by foggy1** [comment]
I agree that would be easier, and honestly what the plugin does is so lightweight that I'm just using typography and typeface myself, but it just seems like if the plugin is going to be a plugin and take options this might be a useful one, rather than doing config elsewhere.

**Comment by KyleAMathews** [comment]
Ah so to `gatsby-plugin-typography`. Yeah that makes sense actually. `disableGoogleFonts` which would then just delete `googleFonts` off the typography config object for you. Sure! Would take a PR for that.
