### ISSUE TITLE
Integrating React Js Template

### ISSUE THREAD

**Issue by sundarsan** [gatsbyjs/gatsby#2527]
Hi Team , 

This is not an issue but i am just looking for best way or approaches for the below problem.I have ReactJs based UI template what are best possible approaches for me to integrate that into Gatsby Project.

Could you please help me with the best and easy approach for the above.

Regards
Sundar

**Comment by KyleAMathews** [comment]
Not really sure what your question is? Gatsby uses React components for everything so use your UI library as normal.

Try going through the tutorial at gatsbyjs.org/tutorial/ if you haven't.
