### ISSUE TITLE
static query fails on gatsby build

### ISSUE THREAD

**Issue by gabdorf** [gatsbyjs/gatsby#25289]
## Description

I'm trying to build a page based on a theme locally with yarn workspaces. Everything works fine when running `gatsby develop`, but as soon as I run `gatsby build` I get the following error:

```
ERROR #98124  WEBPACK

Generating JavaScript bundles failed

Can't resolve '../../../pagename/public/static/d/103120742.json' in '/Users/username/.../.../gatsby-theme-name/src/components'

If you're trying to use a package make sure that '../../../pagename/public/static/d/103120742.json' is installed. If you're trying to use a local file make sure that the path is correct.
```

The query that is failing:

```
query NavLinkQuery {
  site {
    siteMetadata {
      navLinks {
        name
        link
      }
    }
  }
}
```

When I remove that query, everything works fine.
Seems to be related to this: https://github.com/gatsbyjs/gatsby/issues/24890#issuecomment-642140380

I already tried `gatsby clean` in both the theme and the page folder. I removed all `node_modules` and reinstalled the packages.

Contents of `gatsby info --clipboard`:

```
System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Edge: 83.0.478.56
    Firefox: 76.0.1
    Safari: 13.1.1
  npmGlobalPackages:
    gatsby-cli: 2.12.51
    gatsby: 2.22.0`
```

**Comment by pieh** [comment]
Hey @gabdorf, are you able to provide reproduction? Or at least actual logs - the edited parts of the message just hide any potential clues (tho they might not be helfpful, but with paths being edited very little context is lost)

**Comment by gabdorf** [comment]
Hi @pieh.
Can I share the files with you privately somehow?

Here is the log again with edited things in caps:

```
 ERROR #98124  WEBPACK

Generating JavaScript bundles failed

Can't resolve '../../../FOLDER-1/public/static/d/103120742.json' in '/Users/USERNAME/Desktop/Projekte/Git/GATSBY-THEME-NAME/src/components'

If you're trying to use a package make sure that '../../../FOLDER-1/public/static/d/103120742.json' is installed. If you're trying to use a local file make sure that the path is correct.

File: ../GATSBY-THEME-NAME/src/components/nav.js
```

**Comment by pieh** [comment]
@gabdorf feel free to DM me at https://twitter.com/mipiechowiak to share source files if you can't share it publicly

But this seems like your theme is completely outside of your project directory - that might yarn workspaces or some sort of symlinks - we generally _should_ support this, but it seems not in this case

**Comment by gabdorf** [comment]
Thank you. Sent you a DM on twitter.

**Comment by gabdorf** [comment]
Thanks to @pieh for helping out. This was not a bug but me relying on an old hack cleaning out the public folder on build (see link above)
