### ISSUE TITLE
How to disable a specific Babel plugin?

### ISSUE THREAD

**Issue by Mrtenz** [gatsbyjs/gatsby#25297]
## Summary

I need to disable a specific Babel plugin (`@babel/plugin-transform-exponentiation-operator`), since it isn't compatible with `bigint`. Somehow, Gatsby seems to always include this plugin, even when using a custom Babel config, or adding it to `@babel/preset-env`'s `exclude`.

## Relevant information

When running Gatsby, Babel (I'm assuming) changes `a ** b` to `Math.pow(a, b)`. If a and b were regular numbers, that's fine, but I'm using `bigint`, and `Math.pow` doesn't work with those. For that reason I need to disable `@babel/plugin-transform-exponentiation-operator` which seems to be part of `babel-preset-gatsby`.

I tried the following (minimal) Babel config:
```json
{
  "presets": [
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}
```

Somehow `a ** b` is still changed to use `Math.pow`. I also tried the following in `gatsby-node`:

```ts
export const onCreateBabelConfig: GatsbyNode['onCreateBabelConfig'] = ({ actions }) => {
  const { setBabelPreset, setBabelPlugin } = actions;

  setBabelPreset({
    name: `@babel/preset-env`,
    options: {
      exclude: [
        '@babel/plugin-transform-exponentiation-operator'
      ]
    },
  });
};
```

But again, this did not work.

### Environment (if relevant)

```
  System:
    OS: Linux 5.7 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.16.1 - /tmp/yarn--1593094049939-0.20936901508456507/node
    Yarn: 1.22.4 - /tmp/yarn--1593094049939-0.20936901508456507/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 3.8.3 - /usr/bin/python
  Browsers:
    Firefox: 77.0.1
  npmPackages:
    gatsby: ^2.23.4 => 2.23.4
    gatsby-plugin-canonical-urls: ^2.3.4 => 2.3.4
    gatsby-plugin-catch-links: ^2.1.25 => 2.3.5
    gatsby-plugin-favicons: ^1.0.4 => 1.0.4
    gatsby-plugin-matomo: ^0.8.0 => 0.8.3
    gatsby-plugin-mdx: ^1.0.73 => 1.2.15
    gatsby-plugin-react-helmet-async: ^1.0.15 => 1.0.16
    gatsby-plugin-s3: ^0.3.3 => 0.3.3
    gatsby-plugin-sharp: ^2.4.5 => 2.6.11
    gatsby-plugin-sitemap: ^2.2.27 => 2.4.5
    gatsby-plugin-styled-components: ^3.1.19 => 3.3.4
    gatsby-plugin-ts-config: ^0.2.3 => 0.2.3
    gatsby-plugin-typescript: ^2.4.6 => 2.4.6
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-images: ^3.1.44 => 3.3.10
    gatsby-remark-static-images: ^1.0.1 => 1.2.0
    gatsby-source-filesystem: ^2.3.0 => 2.3.11
    gatsby-transformer-yaml: ^2.2.25 => 2.4.4
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by wardpeet** [comment]
@Mrtenz Thanks for opening this issue. Just to clarify, is this bigint problem occurring in node_modules or your src code? The reason I ask is that we currently do not allow to edit node_modules babel-preset but I can give you a workaround for that.

If it's user code, creating your own .babelrc file should work instead of calling `onCreateBabelConfig`

**Comment by Mrtenz** [comment]
@wardpeet It initially happend in a node_modules dependency, but I am able to reproduce it in my own code as well. I will likely only use it in the dependency though. The compiled code in the dependency looks like
```
const maxValue = 2n ** bits - 1n;
```
so that shouldn't be the issue. I'd like to hear about the workaround.

**Comment by wardpeet** [comment]
This should remove transforming node_modules entirely.

```js
exports.onCreateWebpackConfig = ({ getConfig, actions, stage }) => {
  const webpackConfig = getConfig()

  if (stage === "build-javascript") {
    const dependencyRulesIndex = webpackConfig.module.rules.findIndex(
      (rule) => {
        return (
          rule.test &&
          rule.test.toString() === "/\\.(js|mjs)$/" &&
          typeof rule.exclude === "function"
        )
      }
    )

    webpackConfig.module.rules.splice(dependencyRulesIndex, 1)
  }

  actions.replaceWebpackConfig(webpackConfig)
}
```

**Comment by wardpeet** [comment]
@mrtenz you can use `gatsby-plugin-remove-dependency-transpilation` to remove the dependency step and create your own or use https://www.gatsbyjs.com/plugins/gatsby-plugin-compile-es6-packages/

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
