### ISSUE TITLE
Does the Link API support adding custom styles for the currently active fragment?

### ISSUE THREAD

**Issue by rahul-sundaresan** [gatsbyjs/gatsby#25309]
## Summary
I'm trying to create a navbar for my single page website. The navbar will highlight the current section the user is on. I saw the gatsby docs for styling links. While it works for linking to different pages (and highlighting the approriate item on the navbar), the styling part doesn't work when I'm using HTML fragments

## Relevant information
My nav bar is like this:
![image](https://user-images.githubusercontent.com/22392208/85773940-39a9b780-b6d3-11ea-9b05-1194118fbaaa.png)

```jsx
<nav id="nav-wrap" style={{backgroundColor: "black"}}>
            <ul id="nav" className="nav">
                <li><Link to="/"  activeStyle={{color: "orange"}} >Home</Link></li>
                <li><Link to="/#about" activeStyle={{color: "orange"}}>About</Link></li>
                <li><Link to="/#resume" activeStyle={{color: "orange"}}>Resume</Link></li>
                <li><Link to="/#contact" activeStyle={{color: "orange"}}>Contact</Link></li>
            </ul>
</nav>
```
Only the Home link is always orange no matter what ever link I click (but its scrolling correctly)

Can I use the Link API to style fragments?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by pieh** [comment]
I don't think this API is suitable, because Link primarly uses just `pathname` and I think in this case you do want to "hook" into scrolling events or intersection observer to know which section is in view (and not necesairly just rely on `hash` part of location).

My solution would be to hook various sections of your page to `IntersectionObserver`, have some react context to keeps track which section is "active" and wrap your menu navigation links with something like this:

```js
const activeStyle = {
  color: `orange`,
}

const defaultStyle = {}

function NavLink(props) {
  const activeSection = useContext(ActiveSectionContext)

  return <Link {...props} style={props.to === activeSection ? activeStyle : defaultStyle } />
}
```

**Comment by LekoArts** [comment]
As this is a general React question I'll close this and refer you to [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) where you can get support.
