### ISSUE TITLE
Smaller core size

### ISSUE THREAD

**Issue by probablyup** [gatsbyjs/gatsby#25310]
## Summary

At the moment, gatsby relies on gatsby-cli, which relies on gatsby-recipes. This pulls in a metric f*ton of dependencies that most people will never use. Can this be refactored away?

**Comment by pieh** [comment]
Let's start with saying that there are always opportunities to reduce number of deps (no argue there). 

We can't easily detach `gatsby` from `gatsby-cli` tho - every gatsby run use `gatsby-cli`. Not without massive refactor. Is this doable? Sure. Is it worth to prioritize this over other efforts (performance, features, bug fixes)? If you stack rank "effort * impact" and here impact would be "less node_modules" and other efforts results in "faster builds" or "user can now do X" or "user is no longer blocked by a bug", then I don't really see refactor like that being more important than other work that can be done in that time.

For `gatsby-recipes` - today, maybe this could be optional dependency or even separate CLI - it's early and it pulls quite a bit of deps, true, but there are trade offs. This is currently the way we envision provisioning/scaffolding sites and running various tasks that user either have to do manually or rely on starters that do it for them. For this to be successful there should be no extra barriers for users (and recipe creators) - for that reason we absolutely do want this to be usable via `gatsby recipes [...args]`. Could this, for example, download needed deps lazily when user first uses `gatsby recipes` command? I bet it could, but again - is doing that more impactful than other efforts? Is added complexity and "maintenance cost" worth it?

If those deps would be ending up in produced browser bundles - that would be different story - in this case it would probably skyrocket when it comes to prioritization, but they are not and only things left are size of `node_modules` and time spend on deps install/update.

**Comment by probablyup** [comment]
Not stale

**Comment by LekoArts** [comment]
In what way? My colleague gave a lengthy answer to your question and on that higher level it was answered. Do you have any further suggestions or answers/questions?

**Comment by probablyup** [comment]
> maybe this could be optional dependency or even separate CLI

Sounds like an action item.

**Comment by LekoArts** [comment]
Gatsby Recipes is still in early development and it would be a premature optimization to try to pull it out right now. So there isn't really any actionable thing here and thus I'll close this. Thanks for the issue!
