### ISSUE TITLE
Inconsistency between build and develop for target="_blank" attribute

### ISSUE THREAD

**Issue by peonmodel** [gatsbyjs/gatsby#2532]
```html
<a href={`https://www.google.com`} target="_blank">Google</a>
```
i am getting inconsistent result from ```gatsby build``` and ```gatsby develop``` with regards to target="_blank" attributes

in develop, the link opens in a new window as expected but the "target="_blank"" attribute is missing from the html file in build

**Comment by LeKoArts** [comment]
To just try a shot in the dark here:
What happens if you add the "rel" attribute?
``rel="noopener noreferrer"``

**Comment by KyleAMathews** [comment]
Your explanation sounds like a red herring perhaps. Gatsby is a normal React build so perhaps you have some logic or whatever that's going awry during the build.

**Comment by peonmodel** [comment]
ok, problem gone, i think it was some weird caching issue with my browser that resolve itself after i close all windows, thanks
