### ISSUE TITLE
@link graphql field extension regression in gatsby@2.23

### ISSUE THREAD

**Issue by stefanprobst** [gatsbyjs/gatsby#25336]
## Description

Queries on fields with the `link` field extension broke with gatsby@2.23.

### Steps to reproduce

```bash
git clone https://github.com/stefanprobst/gatsby-issue-link-extension-regression
cd gatsby-issue-link-extension-regression
yarn && yarn start
# this runs with gatsby@2.22.22 -- the query results are correctly displayed at [http://localhost:8000]
# now update gatsby to latest
yarn add gatsby@2.23
yarn start
# query fails
```

### Expected result

Working query

### Actual result

Query failure: "Cannot return null for non-nullable field Tag.posts."

### Environment

```
  System:
    OS: Linux 5.4 KDE neon 5.19
    CPU: (4) x64 Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.18.1 - /tmp/yarn--1593200298393-0.5385115370476083/node
    Yarn: 1.22.4 - /tmp/yarn--1593200298393-0.5385115370476083/yarn
    npm: 6.14.5 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: dev
    Firefox: 77.0.1
  npmPackages:
    gatsby: 2.23 => 2.23.11 
    gatsby-source-filesystem: ^2.3.13 => 2.3.14 
    gatsby-transformer-json: ^2.4.7 => 2.4.7 
```

**Comment by stefanprobst** [comment]
also: in #25109 a section was added to the schema customization docs, explaining that the `by` arg to `@link` does not support array values. i think this is not correct, as in the above repro case the following worked with gatsby@2.22, which is pretty much the same example as the one in the docs:
```graphql
type Author implements Node @dontInfer {
  id: ID!
  name: String!
  email: String!
  posts: [Post!]! @link(from: "email", by: "authors.email")
}

type Post implements Node @dontInfer {
  id: ID!
  title: String!
  body: String!
  authors: [Author!]! @link(by: "email")
  tags: [Tag!]! @link
}

type Tag implements Node @dontInfer {
  id: ID!
  label: String!
  description: String!
  posts: [Post!]! @link(from: "id", by: "tags.id")
}
```

**Comment by stefanprobst** [comment]
i have added the [`pr-25109`](https://github.com/stefanprobst/gatsby-issue-link-extension-regression/tree/pr-25109) branch in the above repo that shows the example from #25109 working with gatsby@2.22

**Comment by vladar** [comment]
Probably caused by #24743 as it's the only change in 2.23. @pvdz any idea which change could have caused this?

**Comment by stefanprobst** [comment]
looks like the following works in v2.23:

```diff
type Author implements Node @dontInfer {
  id: ID!
  name: String!
  email: String!
- posts: [Post!]! @link(from: "email", by: "authors.email")
+ posts: [Post!]! @link(from: "email", by: "authors.elemMatch.email")
}

type Post implements Node @dontInfer {
  id: ID!
  title: String!
  body: String!
  authors: [Author!]! @link(by: "email")
  tags: [Tag!]! @link
}

type Tag implements Node @dontInfer {
  id: ID!
  label: String!
  description: String!
- posts: [Post!]! @link(from: "id", by: "tags.id")
+ posts: [Post!]! @link(from: "id", by: "tags.elemMatch.id")
}
```

it's a bit confusing though because `link.by` should be a path to a field

**Comment by pvdz** [comment]
I'll have a look at this in the next few days. It seems something is underlying broken/incompatible when running the filters with `@link`.

**Comment by pvdz** [comment]
Turns out the `@link` resolver was generating a filter with `$eq` as operator. In Sift, `$eq` would work on arrays but after we replaced Sift that was no longer the case (that's what `elemMatch` and `$in` are for, after all). The `@link` feature is not very commonly used and it seems arrays are even an edge case in that so this problem flew under the radar, apart from this issue.

I've put up a PR that fixes the issue but will need to add some tests before I can merge it. If you are blocked by it you can try the same patch in your `node_modules` although that's not going to be sustainable long term.
