### ISSUE TITLE
gatsby-cli impossible to install via Yarn without --ignore-engines flag

### ISSUE THREAD

**Issue by inferusvv** [gatsbyjs/gatsby#2534]
I am trying to install `gatsby-cli` via Yarn. I run `yarn global add gatsby-cli`. But I am gettin an error: 

`error ghost-cli@1.1.3: The engine "node" is incompatible with this module. Expected version "^4.5.0 || ^6.9.0".`

It works with `yarn global add gatsby-cli --ignore-engines` but very fun that on your website [here](https://www.gatsbyjs.org/tutorial/part-one/) on screenshot you have node version 8, not 6 😄

**Comment by jquense** [comment]
where is `ghost-cli` coming from that isn't a gatsby dependency

**Comment by KyleAMathews** [comment]
Yeah, you might have typoed gatsby-cli. as you can see, we don't specify engine in the gatsby-cli package.json https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/package.json
