### ISSUE TITLE
maintenance(www): Switch layer-icon to pure SVGs

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#25346]
## Description

Since #25282, we can now import SVGs directly as React components. We have a file [`layer-icon.js`](https://github.com/gatsbyjs/gatsby/blob/master/www/src/assets/icons/layer-icon.js) that inlines icons that we use in the `LayerModel` component. Convert these into raw SVG files that can be imported normally.

## Motivation

Raw SVGs can be optimized with SVGO.

**Comment by abhishekjakhar** [comment]
I have started working on the remaining components

**Comment by morgan-sam** [comment]
Hi @abhishekjakhar are you still working on this?

**Comment by abhishekjakhar** [comment]
@morgan-sam hey you can pick this up if you want to, I got occupied with another PR.
