### ISSUE TITLE
Support for App + Web property Google Analytics Measurement ID in gatsby-plugin-google-tagmanager

### ISSUE THREAD

**Issue by danielmgzzg** [gatsbyjs/gatsby#25359]
## Summary

I'm not sure if I'm setting this up correctly but I know my gatsby-plugin-google-tagmanager has a problem when I load the measurement id as in the picture below as a tag, it's not returning data from the production build even with the same gatsby-route-change trigger in the tag configuration.

I'm not sure if there is support yet, since this is still a beta (see links below for reference). But we wanted to explore this option as it would be great to make use of the extended features it offers now. Any help would be greatly appreciated to understand this better, or we could just switch back to tracking id from google analytics, which worked with the plugin.

[Upgrade to an App + Web property   |   Google Support](https://support.google.com/analytics/answer/9744165?hl=en&ref_topic=9143232)

[What happened to my Tracking ID?   |   Google Support](https://support.google.com/analytics/answer/9539598)

## Relevant information

Google Analytics Web Streams

![image](https://user-images.githubusercontent.com/34385962/85933335-8213d180-b89b-11ea-87b4-8cc162a75d5a.png)

![image](https://user-images.githubusercontent.com/34385962/85933419-61984700-b89c-11ea-9395-6a874583e224.png)

Google Tag Manager Config

![image](https://user-images.githubusercontent.com/34385962/85933318-46790780-b89b-11ea-88a3-1ac14e5a24d2.png)

### File contents

`gatsby-config.js`: 
```
{
      resolve: `gatsby-plugin-google-tagmanager`,
      options: {
        id: process.env.GOOGLE_TAGMANAGER_ID,
        includeInDevelopment: false,
        defaultDataLayer: { platform: "gatsby" },
      },
    },
```

**Comment by ViktorMeduneckij** [comment]
Any progress on this?

**Comment by LekoArts** [comment]
Since this is in Beta the current plugins and their script tags they add to the HTML don't support that. Feel free to send in a PR or copy the plugin code into your project and update the script tag itself.

**Comment by markojak** [comment]
Google Analytics 4 is now out of public beta. Anyone got any ideas if this is fixed?

**Comment by vincentntang** [comment]
doesn't seem to work for me, I have gatsby site that works fine using the old google "UA" IDs

with google analytics 4 I can't seem to get my analytics integrated

**Comment by BoolHandLuke** [comment]
For anyone arriving here from Google and facing challenges integrating a new Google analytics account with a Measurement ID (starting "G-") instead of a tracking ID (starting "UA-"), it's still possible to create an old version Universal Analytics account when setting up your property in the Analytics dashboard. Under advanced settings use the option to create a Universal Analytics property as well as the default Google Analytics 4 property to ensure that you will also get a "UA-" tracking ID. This will let you use this plugin until it's updated for the new version of Google Analytics.

**Comment by pepjo** [comment]
Are there any plans to upgrade to google analytics 4? If so, is there an issue to track the progress?

**Comment by pterofractal** [comment]
At a minimum can the documentation at least be updated to include the workaround that @BoolHandLuke mentioned? I think that help a lot of new people building sites out a lot. I was also confused why nothing was working haha.

**Comment by sulunemre** [comment]
An alternative plugin: https://www.gatsbyjs.com/plugins/gatsby-plugin-gdpr-cookies/
