### ISSUE TITLE
Console logging doesn't seem to work for me.

### ISSUE THREAD

**Issue by FormidablePencil** [gatsbyjs/gatsby#25366]
The gatsby environment runs and displays in the browser what it should display but console logging from anywhere in the code doesn't print in the running terminal. Idk if it's how gatsby is created internally that doesn't allow console logging or if there's something I'm missing. Before anyone jumps to conclusion and thinks I've some nooby programmer (which I am) that can't console.log('hello world") I have to say console logging works in all other environments I work in: React, Express and plain js. And yes, I'm sure Gatsby is running. but Gatsby is the only one I'm having trouble with. Gatsby on both windows and mac doesn't allow me to print console log to the terminal. I've also tried creating a new gatsby started default template and no luck. 
I feel stupid for asking but could someone help me console.log('hello world')?

**Comment by herecydev** [comment]
Would be helpful if you could make a minimal reproduction so it's obvious what you're trying: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

**Comment by FormidablePencil** [comment]
yeah sure. Here's a repo of a blog I was building in gatsby https://github.com/FormidablePencil/blog-site

**Comment by FormidablePencil** [comment]
The problem as previously mentioned is not specific to any repo but Gatsby itself in general

**Comment by KyleAMathews** [comment]
Where are you putting the `console.log`?

**Comment by FormidablePencil** [comment]
within the functional components like so 
const SomePage = () => {
console.log("hello world")
return (
  <div><div>
)}

Also tried putting it into a function and triggering it with an onClick event but still no printing "hello world" in the terminal:
const SomePage = () => {
 const onClickHandler = () => {
  console.log('hello world')
}
return (
<div className='clickableElement' onClick={onClickHandler} />
)}

**Comment by wardpeet** [comment]
Hi @FormidablePencil!

For me console.log works fine in the browser. I'm not entirely sure how to reproduce this.

To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by FormidablePencil** [comment]
Thx @wardpeet I've checked the console in the browser and there was my "hello world" I console logged. I'm used to seeing console logging in the terminal where my app is running so I forgot browser's console also outputs console logs

**Comment by mehov** [comment]
Hi everyone, 

This shows up on Google, so I'll have to bump this hoping it helps someone else.

I was putting `console.log` into a GatsbyJS page template. I expected to see the output during the initial build in my terminal (where I initiated it). However, it actually showed up only when I visited that page in my browser.
