### ISSUE TITLE
gatsby-source-shopify uses different types as shopify-buy-sdk 

### ISSUE THREAD

**Issue by AlexanderProd** [gatsbyjs/gatsby#25365]
## Summary 

I'm trying to use `gatsby-source-shopify` in a project with TypeScript. But I've noticed that `gatsby-source-shopify` uses different types than the type declarations for the official `shopify-buy` packages. This makes using both packages (which you need to) in a TypeScript project impossible to do right. 

## Relevant information

This is how the Product type which gets queried, looks on gatsby-source-shopify:
_I didn't include all the fields._
```
{
  title
  availableForSale
  createdAt
  description
  descriptionHtml
  id
  handle
  onlineStoreUrl
  productType
  priceRange {
    maxVariantPrice {
      amount
      currencyCode
    }
    minVariantPrice {
      amount
      currencyCode
    }
  }
  shopifyId
  tags
  updatedAt
  variants {
    availableForSale
    compareAtPrice
    id
    price
    sku
    shopifyId
    title
  }
}
```

And this is how the Product Type in the `shopify-buy` package looks like. You have to install `@types/shopify-buy`.

```
export interface Product extends GraphModel {
    description: string;
    id: string | number;
    images: Array<Image>;
    variants: Array<ProductVariant>;
    options: Array<Option>;
    selectedVariant: ProductVariant;
    selectedVariantImage: Image;
    selections: Array<string>;
    title: string;
    vendor: string;
}

export interface ProductVariant extends GraphModel {
    available: boolean;
    compareAtPrice: string;
    formattedPrice: string;
    grams: number;
    id: string | number;
    image: Image;
    imageVariant: Array<ImageVariant>;
    optionValues: Array<OptionValue>;
    price: string;
    productId: string | number;
    productTitle: string;
    title: string;
    checkoutUrl(quantitiy: number): string;
}
```

As you can see the Product type for `gatsby-source-shopify ` has many fields which don't exist in the other package, or the fields just have a different name, for example `available` vs. `availableForSale`. 

This makes using both packages in a Typescript in a proper manner (not using `any` or `@ts-lint ignore` all the time) practically impossible. 

I'm wondering what could be done about this. Maybe I can start a discussion about the topic

**Comment by smthomas** [comment]
This is an interesting question. The first problem I see is that `gatsby-source-shopify` by default is using the Shopify Storefront API version `2019-07` while `shopify-buy` version 2.10 uses `2020-04`. On top of that I also noticed https://github.com/Shopify/js-buy-sdk#expanding-the-sdk which says that the sdk does not support all of the fields available from the Storefront API. I don't think `gatsby-source-shopify` uses all of the fields available either, but it does seem to make significantly more fields available.

I don't know if this will help but we should soon be adding a feature that allows for you to customize the GraphQL queries sent to the Shopify Storefront API (see #23922). I wonder if this along with using GraphQL aliases in the custom queries to rename the fields would get you closer?

**Comment by AlexanderProd** [comment]
Yeah I think using a custom Query with aliases would help, especially for cases like `available` vs`availableForSale`. Also I think it would make sense to upgrade `gatsby-source-shopify` to the `2020-04` api.

**Comment by smthomas** [comment]
I am closing this as we have plans to update the gatsby-source-shopify plugin in the near future (the next few months) which will use a more recent version of the API.
