### ISSUE TITLE
Location undefined issue on gatsby-browser

### ISSUE THREAD

**Issue by bhargav-kahar-everestek** [gatsbyjs/gatsby#25375]
Hi,

Can you please look into issue of gatsby browser
![image](https://user-images.githubusercontent.com/53463085/85971451-c1046d00-b9ea-11ea-9691-c4a49f65529c.png)

**Comment by blainekasten** [comment]
Can you share your `gatsby-browser` file with us?

**Comment by bhargav-kahar-everestek** [comment]
The contents are as below for `gatsby-browser` file.
```
exports.shouldUpdateScroll = ({
  getSavedScrollPosition,
  prevRouterProps: { location: prevLocation },
  routerProps: { location },
}) => {
  const stripPath = (path) => path.replace(/[^a-z0-9]/gi, '');

  // if the path changes, we let the browser do its thing
  if (stripPath(location.pathname) !== stripPath(prevLocation.pathname)) {
    return true;
  }

  // if a query param changes, we want to maintain our previous scroll position
  if (location.search !== prevLocation.search) {
    const position = getSavedScrollPosition(prevLocation);
    if (position) return position;
  }

  // if nothing changed, nothing needs to be done
  return false;
};
```

**Comment by graysonhicks** [comment]
I attempted to recreate in this sandbox (https://codesandbox.io/s/fervent-lehmann-3hvlb?file=/gatsby-browser.js), but the script completes as expected.

@bhargav-kahar-everestek Could you post the output of your `gatsby info --clipboard` command?

**Comment by bhargav-kahar-everestek** [comment]
Hi, 
Still happening after some 20-30 min. later; then reload the page.  (Must, to reproduce the issue)
![GatsbyInfo](https://user-images.githubusercontent.com/53463085/86202411-c646f080-bb7f-11ea-9726-1c80dd210fbf.PNG)

**Comment by bhargav-kahar-everestek** [comment]
I've changed to this & fix the problem.

```
exports.shouldUpdateScroll = ({
  getSavedScrollPosition,
  prevRouterProps: prevLocationObj = {},
  routerProps: locationObj = {},
}) => {
  const { prevLocation } = prevLocationObj;
  const { location } = locationObj;

  if (!(prevLocation && location)) return false;
...
...
}
```
