### ISSUE TITLE
gatsby-plugin-create-client-paths wildcart prefix will go to 404 if there is a 404.js

### ISSUE THREAD

**Issue by stanleyyuenyiu** [gatsbyjs/gatsby#25376]
- install plugin gatsby-plugin-create-client-paths 
- add below code  to the gatsby-config.js -> plugins section
{
      resolve: \`gatsby-plugin-create-client-paths\`,
      options: { prefixes: [\`/*\`] },
} 
- create page index.js in pages folder
pages
   - index.js
   - 404.js

- include a router and define the path in index.js

 <Layout>
      <Router>
        <Hi path="/:locale/hi" default />
      </Router>
    </Layout>

- visit the page  ->  /en-us/hi

expect:
Page display

Actual:
go to 404

The 404 result will only happen when you naming any pages with start with 4, such as 404.js, 401.js...

if you dont have such page, it will be fine

--update--
Here is the sandbox url
https://codesandbox.io/s/spring-sea-yjy5c

type url in the test browser ->

https://yjy5c.sse.codesandbox.io/en/test

**Comment by FranciscoImanolSuarez** [comment]
Never implement this, but try changing the path to **index.js** and create your **index.js** page folder. When reading the documentation it says "In this example, all paths prefixed with **/app/** will show the path described in **src/pages/app.js**." So I understand that if your app.js is not in your page folder, it would not work and would return 404 (page not found)

https://www.gatsbyjs.org/packages/gatsby-plugin-create-client-paths/

**Comment by stanleyyuenyiu** [comment]
sorry i didnt mention clearly 

i create a page named index.js in page folder

beside, above case will make the useParam not work any more, always return null

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by stanleyyuenyiu** [comment]
Here is the sandbox url
https://codesandbox.io/s/spring-sea-yjy5c

type url in the test browser ->

https://yjy5c.sse.codesandbox.io/en/test

**Comment by FranciscoImanolSuarez** [comment]
Please let us know if what I provide @stanleyyuenyiu  has worked for you.

**Comment by stanleyyuenyiu** [comment]
@FranciscoImanolSuarez what have you provided? i dont see any change on the sandbox

**Comment by FranciscoImanolSuarez** [comment]
Sorry, it was a misunderstanding of mine, I didn't see that you provided the sandbox and that you also started this problem (# 25376). Now I look at the sandbox

**Comment by stanleyyuenyiu** [comment]
@FranciscoImanolSuarez 

just remind that i have this request becoz

my url will be

/:locale/page/:dynamic_id_that_depend_on_user_data

e.g

/en/inbox/mymessage123
/en/inbox/mymessage124
/zh-tw/inbox/mymessage123
/en/address/myaddress1
/en/address/myaddress2

**Comment by stanleyyuenyiu** [comment]
also remind that i have 30000+user , and 20+ languages, therefore i can not use create the path in static way (createPage), it may no sense on this case, as my application is not a static website, but a user portal, the application content mostly depend on user

**Comment by stanleyyuenyiu** [comment]
@LekoArts any update???
