### ISSUE TITLE
[gatsby-plugin-offline] TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by eneim** [gatsbyjs/gatsby#25374]
## Description

My build fails with the following error:

```
  TypeError: Cannot read property 'startsWith' of undefined
  
  - get-resources-from-html.js:40 Node.<anonymous>
    [blog]/[gatsby-plugin-offline]/get-resources-from-html.js:40:42
```

I think that this line:

https://github.com/gatsbyjs/gatsby/blob/c9c3d68b589a1feba64d232c6b496968083e8e88/packages/gatsby-plugin-offline/src/get-resources-from-html.js#L46

doesn't check the url for nullability.

### Steps to reproduce

It occurs in my private blog. Sadly I have no idea how I could reproduce it with a simple repo.

### Expected result

It should successfully build the repo.

### Actual result

It fails to build.

### Environment

```

  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.0.76 => 2.23.11 
    gatsby-awesome-pagination: ^0.3.3 => 0.3.6 
    gatsby-image: ^2.0.20 => 2.4.9 
    gatsby-plugin-draft: ^0.0.4 => 0.0.4 
    gatsby-plugin-feed: ^2.3.20 => 2.5.7 
    gatsby-plugin-google-analytics: ^2.0.17 => 2.3.6 
    gatsby-plugin-manifest: ^2.0.9 => 2.4.14 
    gatsby-plugin-netlify: ^2.0.12 => 2.3.7 
    gatsby-plugin-offline: ^3.2.13 => 3.2.13 
    gatsby-plugin-postcss: ^2.0.2 => 2.3.6 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.3.6 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.1 
    gatsby-plugin-sharp: ^2.0.17 => 2.6.14 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5 
    gatsby-remark-code-titles: ^1.1.0-rc.0 => 1.1.0 
    gatsby-remark-copy-linked-files: ^2.0.9 => 2.3.7 
    gatsby-remark-embed-gist: ^1.1.6 => 1.2.0 
    gatsby-remark-embed-video: ^1.7.0 => 1.7.1 
    gatsby-remark-external-links: ^0.0.4 => 0.0.4 
    gatsby-remark-footnotes: ^0.0.7 => 0.0.7 
    gatsby-remark-images: ^3.0.1 => 3.3.13 
    gatsby-remark-numbered-footnotes: ^1.0.1 => 1.0.1 
    gatsby-remark-prismjs: ^3.2.0 => 3.5.6 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.4.7 
    gatsby-source-filesystem: ^2.0.8 => 2.3.14 
    gatsby-transformer-remark: ^2.1.19 => 2.8.19 
    gatsby-transformer-sharp: ^2.1.8 => 2.5.7 
```

**Comment by blainekasten** [comment]
Feels related to #25380

**Comment by jrusso1020** [comment]
Just a little more info @blainekasten @wardpeet 

I have the same issue using `gatsby-plugin-offline` version 3.2.13, I started my website from https://github.com/gatsbyjs/gatsby-starter-blog so I think that would probably be a minimal repo to reproduce this.

I also get the issue with 3.2.12, 3.2.11, etc (that I tried). Looking at the linked issue https://github.com/gatsbyjs/gatsby/issues/25380

It appears to be a problem with Gatsby it self not the `gatsby-plugin-offline`

Gatsby version 2.23.12 and `gatsby-core-utils` 1.3.8

**Comment by zeropaper** [comment]
I'm facing the same issue.

I could determined that the root cause is the generated html file 

which contains something like:
```
<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible"
content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1,
shrink-to-fit=no"/><meta name="generator" content="Gatsby 2.24.2"/><title
data-react-helmet="true"></title><link rel="stylesheet"/><style type="text/css">
    .anchor.before {
      position: absolute;
      top: 0;
      left: 0;
      transform: translateX(-100%);
      padding-right: 4px;
    }
    .anchor.after {
      display: inline-block;
      padding-left: 4px;
    }
    h1 .anchor svg,
```
the problem lies here: `<link rel="stylesheet"/>`, the tag will be found by the code

https://github.com/gatsbyjs/gatsby/blob/c9c3d68b589a1feba64d232c6b496968083e8e88/packages/gatsby-plugin-offline/src/get-resources-from-html.js#L29-L49

but it has no "src" attribute...

So... IMVHO... a valid fix would be to change:

https://github.com/gatsbyjs/gatsby/blob/c9c3d68b589a1feba64d232c6b496968083e8e88/packages/gatsby-plugin-offline/src/get-resources-from-html.js#L46

to 

```js
if (url && !blackListRegex.test(url) && url.startsWith(`${pathPrefix}/`)) { 
```
