### ISSUE TITLE
Missing endsWith polyfill for Gatsby's internal absolutify utility in IE11

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#25380]
## Description

I'm seeing errors in Sentry for our Gatsby site being caused by one of Gatsby's internal utilities using `string.endsWith` which is not being correctly polyfilled with [core-js](https://github.com/zloirock/core-js/blob/v3.6.5/packages/core-js/modules/es.string.ends-with.js): `/es.string.ends-with.js`

The error originates [here](https://github.com/gatsbyjs/gatsby/blob/e2c6cf2a66419827abbc5c831e10e21012441d8a/packages/gatsby/cache-dir/find-path.js#L33):
```
function absolutify(path) {
  // If it's already absolute, return as-is
  if (
    path.startsWith(`/`) ||
    path.startsWith(`https://`) ||
    path.startsWith(`http://`)
  ) {
    return path
  }
  // Calculate path relative to current location, adding a trailing slash to
  // match behavior of @reach/router
  return new URL(
    path,
    window.location.href + (window.location.href.endsWith(`/`) ? `` : `/`)
  ).pathname
}

Looks like the same is true for `startsWith` and possibly others.
```

I'm using Gatsby's default browserlist which should include polyfills for IE11. 

### Steps to reproduce

- Build Gatsby site
- Inspect bundle

### Expected result

- appropriate polyfill is included.

### Actual result

- polyfill is missing.

<img width="1905" alt="Screenshot 2020-06-29 at 13 43 03" src="https://user-images.githubusercontent.com/161489/86006858-844a6d00-ba0e-11ea-95d8-e76d70272487.png">

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: 2.23.11 => 2.23.1 
    gatsby-cli: ^2.12.44 => 2.12.44 
    gatsby-image: ^2.4.7 => 2.4.7 
    gatsby-link: ^2.4.6 => 2.4.6 
    gatsby-plugin-catch-links: ^2.3.5 => 2.3.5 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-google-tagmanager: ^2.3.5 => 2.3.5 
    gatsby-plugin-manifest: ^2.4.11 => 2.4.11 
    gatsby-plugin-netlify-cms: ^4.3.5 => 4.3.5 
    gatsby-plugin-node-fields: 3.1.0 => 3.1.0 
    gatsby-plugin-page-creator: ^2.3.9 => 2.3.9 
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.4 
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0 
    gatsby-plugin-scroll-reveal: ^0.0.7 => 0.0.7 
    gatsby-plugin-sharp: ^2.6.11 => 2.6.11 
    gatsby-plugin-sitemap: ^2.4.5 => 2.4.5 
    gatsby-plugin-styled-components: ^3.3.4 => 3.3.4 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-react-router-scroll: 3.0.3 => 3.0.3 
    gatsby-remark-autolink-headers: ^2.3.5 => 2.3.5 
    gatsby-remark-component-parent2div: ^1.2.3 => 1.2.3 
    gatsby-remark-copy-linked-files: ^2.3.5 => 2.3.5 
    gatsby-remark-footnotes: ^0.0.7 => 0.0.7 
    gatsby-remark-images: ^3.3.10 => 3.3.10 
    gatsby-remark-numbered-footnotes: ^1.0.1 => 1.0.1 
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0 
    gatsby-remark-responsive-iframe: ^2.4.5 => 2.4.5 
    gatsby-remark-smartypants: ^2.3.4 => 2.3.4 
    gatsby-remark-unwrap-images: ^1.0.2 => 1.0.2 
    gatsby-source-filesystem: ^2.3.11 => 2.3.11 
    gatsby-transformer-json: ^2.4.5 => 2.4.5 
    gatsby-transformer-remark: ^2.8.15 => 2.8.15 
    gatsby-transformer-sharp: ^2.5.5 => 2.5.5

**Comment by blainekasten** [comment]
@Undistraction Uh oh! That's problematic!

I just tested this locally and found the endsWith polyfill. Wondering if you could test this and it might help us pinpoint something. Do the following:

1. `gatsby build`
1. `gatsby serve`
1. In your browser at localhost:9000, look at the resource for `app-[hash].js` and search for `endsWith`, you should find a polyfill that looks roughly like this:

![image](https://user-images.githubusercontent.com/2916023/86016959-117acb00-b9e9-11ea-9309-07b718f97136.png)


Let me know if you find that or not.

**Comment by Undistraction** [comment]
@blainekasten I made a repro using the hello-world starter, and I am seeing both `starts-with` and `ends-with` polyfills being added to the bundle, however they are missing for my project. Looks like things are working out of the box, so error is somewhere in my project. I'll close this out and reopen if the problem isn't my own stupidity.

**Comment by Undistraction** [comment]
@blainekasten sorry. One question. Should Gatsby be polyfilling IntersectionObserver automatically?

**Comment by wardpeet** [comment]
@Undistraction no but it shouldn't break your site. Gatsby should use progressive enhancement

**Comment by Undistraction** [comment]
@wardpeet Thank you.
