### ISSUE TITLE
How do I stop the preview in localhost:9000 from gatsby serve?

### ISSUE THREAD

**Issue by learis** [gatsbyjs/gatsby#25396]
Hello, I previously used gatsby serve to preview a build at localhost:9000. Days later I am realizing that the preview is still appearing on localhost:9000. I'm just being nitpicky, but I don't want it to appear anymore. I would normally use ctrl + c to cancel the preview in gatsby develop, but how do I do it for the preview that comes from gatsby serve?

**Comment by LekoArts** [comment]
Thank you for opening this!

Using <kbd>Ctrl</kbd> + <kbd>C</kbd> is cancelling `gatsby serve` that is serving your site. It's the same as with `gatsby develop`. Make sure that you actually cancelled the server in your terminal/IDE etc. - also see if you have `gatsby-plugin-offline` installed as this will install a service worker also for your localhost:9000 and one of it's purposes is to serve the site even when it's offline.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by learis** [comment]
@LekoArts Yes I think it's because of the offline plugin. But now there's another problem. I just built and served another website. However the page stays white with errors because it's trying to load stuff from the previous website still. Something to do with cache I think. I have to hold shift + r to reload it properly. How do I remove all of the info from the previously built website so I can get my new one to load normally on the build server?

**Comment by know-mad** [comment]
I'm having the same issue. Why was this closed. Simply telling to hit ctrl + c and close the server on localhost doesn't actually resolve anything.
Ive killed everything running on port 9000 width ```lsof -i :9000``` to get the PID and then ```kill PID```

still does nothing and the previous site continues to build on that port. This is so annoying
