### ISSUE TITLE
project crashes when starting

### ISSUE THREAD

**Issue by nelsonwenner** [gatsbyjs/gatsby#25393]
## Description
Following the documentation tutorial for a quick start from gatsby, the application breaks when running.
* quick-start: https://www.gatsbyjs.org/docs/quick-start/

### Expected result
execute the project to start studies.

### Actual result
![Screenshot from 2020-06-29 16-21-39](https://user-images.githubusercontent.com/40550247/86048379-d0a1a700-ba26-11ea-93be-0b3038e22066.png)

### Environment
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-3330S CPU @ 2.70GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 77.0.1
  npmPackages:
    gatsby: ^2.23.10 => 2.23.10
    gatsby-image: ^2.4.8 => 2.4.8
    gatsby-plugin-manifest: ^2.4.13 => 2.4.13
    gatsby-plugin-offline: ^3.2.12 => 3.2.12
    gatsby-plugin-react-helmet: ^3.3.5 => 3.3.5
    gatsby-plugin-sharp: ^2.6.13 => 2.6.13
    gatsby-source-filesystem: ^2.3.13 => 2.3.13
    gatsby-transformer-sharp: ^2.5.6 => 2.5.6
  npmGlobalPackages:
    gatsby-cli: 2.12.51

**Comment by alveshelio** [comment]
Hi,

Have you tried to do what the message says, install the missing package? Try `npm i engine.io-client`? And run `gatsby develop` again

**Comment by nelsonwenner** [comment]
@alveshelio  It worked, but it is strange that this dependency is not in the package by default.
