### ISSUE TITLE
Proper way to do an external redirect programmatically

### ISSUE THREAD

**Issue by dav92lee** [gatsbyjs/gatsby#25398]
## Summary

I am trying to programmatically perform a redirect but to an external website.  Exactly as what `window.location.href = ...` does.  I was wondering if there's a preferred gatsby way to do this.

## Relevant information

For example.  My website makes an api call to our shopping cart service which returns some `uuid`.  When that api call returns, i want to redirect the person to `cart.com/<uuid>` where cart.com is not the domain my site is hosted on.

**Comment by FranciscoImanolSuarez** [comment]
I think this can help you!  [#19294](https://github.com/gatsbyjs/gatsby/issues/19294) , Another alternative I think would be to implement [gatsby-plugin-client-side-redirect](https://www.gatsbyjs.org/packages/gatsby-plugin-client-side-redirect/)

**Comment by pvdz** [comment]
@dav92lee if that answers your question please feel free to close this issue. Thank you :)
