### ISSUE TITLE
Make require("gatsby").graphql work

### ISSUE THREAD

**Issue by jfrolich** [gatsbyjs/gatsby#25406]
This is necessary for properly supporting tagged template literals in BuckleScript/ReasonML. It's probably a small change in the babel-plugin to make it work.

Example

```js
let query = require("gatsby").graphql`
   ...
`
```

I can PR this. Mostly a reminder and happy to get feedback.

**Comment by pvdz** [comment]
I don't think this is a babel/TS change but the symbol just has to be exported in order to be imported :) Looking forward to the PR.

**Comment by i-am-the-slime** [comment]
This is also a problem in PureScript.
