### ISSUE TITLE
[gatsby-plugin-feed] can this plugin be run onPreBuild instead of onPostBuild?

### ISSUE THREAD

**Issue by ehowey** [gatsbyjs/gatsby#25407]
## Summary

So I have a pretty complex themes setup with nested themes. I recently found a pretty sneaky error happening with `gatsby-plugin-feed` when generating images for the RSS Feed in some edge cases when it was being initialized father down the theme chain. In brief these errors seem to be solved by changing the plugin to run its main function `onPreBuild` instead of `onPostBuild` - but my testing is limited and I do not understand enough about everything that is happening in the plugin to know whether this would cause a whole cascade of other problems for people.

cc: @laurieontech as I think this may relate to some of the work you will do when implementing RSS Feed with featured images and social images with `gatsby-theme-blog` v2.0

The two errors I am seeing are as follows:

**Error 1: When building the page using a sharp transformation in the feed query**

If you query for a `childImageSharp` fragment in the feed query e.g:

```js
featuredImage {
    childImageSharp {
        fixed {
            src
            }
          }
       }
```

The page will usually build successfully but in your build logs you will see something like this at the very end of the build process which sometimes causes builds to fail for reasons I can't totally understand.

`11:27:57 PM: (sharp:1645): GLib-CRITICAL **: 05:27:57.061: g_hash_table_lookup: assertion 'hash_table != NULL' failed`

The best I can tell is that this is caused by `gatsby-plugin-feed` trying to run image transformation processes after the build is actually complete and timing out sometimes. I did try other solutions related to this error but none of theme worked/seemed relevant.

**Error 2: When using publicURL in your feed query**

One way around this is to not use a sharp transformation in your query and instead do something like this:

```js
featuredImage {
    publicURL
       }
```

This seems to work if the theme is at the top level - however breaks when the theme implementing `gatsby-plugin-feed` is nested down multiple levels in the theme hierarchy.  The other problem with publicURL is that you get the full sized image when for RSS Feeds you really just need a smaller social media sized image, so being able to use `resize` from `gatsby-transformer-sharp` would be great.

For example this seems to cause problems:

Site -> Presentation Theme -> Blog Theme, Core Theme, Header Theme, Footer Theme 

This seems to work:

Site -> Blog theme, Core Theme, Header Theme, Footer Theme

## Proposed Solution

Both of these problems were solved, for me, by changing the following line in`gatsby-node.js` in `gatsby-plugin-feed`:

`exports.onPostBuild = async ({ graphql }, pluginOptions) => {`

to:

`exports.onPreBuild = async ({ graphql }, pluginOptions) => {`

## Relevant information

The issue is cropping up for me in my work on `gatsby-theme-catalyst`. 

You can view it on GH here: https://github.com/ehowey/gatsby-theme-catalyst

I was running differential tests against my personal site which uses the Catalyst themes and was how I discovered some of these odd behaviours as I have the themes implemented slightly differently on my personal site.

### File contents (if changed)

Full `gatsby-plugin-feed` config for my version of a core blog theme. Note that this shows the `childImageSharp` query but currently in my repo on GH it is the `publicURL` query.

```js
{
        resolve: `gatsby-plugin-feed`,
        options: {
          query: `
            {
              site {
                siteMetadata {
                  title
                  description
                  siteUrl
                  site_url: siteUrl
                }
              }
            }
          `,
          feeds: [
            {
              output: `/rss.xml`,
              title: themeOptions.rssTitle || `RSS Feed`,
              query: `
                {
                  allCatalystPost(
                    sort: { fields: [date, title], order: DESC }
                    limit: 1000
                    filter: { draft: { eq: false } }
                  ) {
                    nodes {
                      id
                      slug
                      title
                      author
                      excerpt
                      date(formatString: "ddd, DD MMM YYYY HH:mm:ss ZZ")
                      socialImage {
                        childImageSharp {
                          fixed {
                            src
                          }
                        }
                      }
                      featuredImage {
                        childImageSharp {
                          fixed {
                            src
                          }
                        }
                      }
                    }
                  }
                }
              `,
              serialize: ({
                query: {
                  site: {
                    siteMetadata: { siteUrl },
                  },
                  allCatalystPost,
                },
              }) => {
                const rssFeed = allCatalystPost.nodes.map((node) => {
                  const hasSocial = node.socialImage !== null
                  const hasFeatured = node.featuredImage !== null
                  const rssImage = hasSocial
                    ? `${siteUrl}${node.socialImage.childImageSharp.fixed.src}`
                    : hasFeatured
                    ? `${siteUrl}${node.featuredImage.childImageSharp.fixed.src}`
                    : null
                  const serialized = {
                    guid: `${siteUrl}${node.slug}`,
                    url: `${siteUrl}${node.slug}`,
                    title: node.title,
                    author: node.author,
                    description: node.excerpt,
                    pubDate: node.date,
                    enclosure: { url: rssImage },
                  }
                  return serialized
                })
                return rssFeed
              },
            },
          ],
        },
      },
```

`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by laurieontech** [comment]
Thanks for opening this issue Eric! There are a number of challenges with `gatsby-plugin-feed` compatibility at the moment. @johno opened #25069 as an umbrella issue for some of them.

We'd certainly be open to a PR with this change so we can explore the impacts. My suspicion is that it may have some unexpected edge cases, but that's a challenge of the current implementation as well.

**Comment by ehowey** [comment]
Thanks Laurie - sounds like people smarter than me are already looking at this.  I will leave this open for now.  I made a PR too - but I do think this one is a bit beyond me as there are lots of edge cases to test for.  Just wanted to draw attention to some odd behaviours I have run into with it in use.

**Comment by laurieontech** [comment]
Absolutely, if it's alright with you I'm going to close this issue but reference in the umbrella one. It cuts down on the noise of the repo a bit but gives us access to all this great research.
