### ISSUE TITLE
How do you update your Gatsby site that's hosted on Heroku when a new Wordpress blog is published

### ISSUE THREAD

**Issue by mumbii** [gatsbyjs/gatsby#25417]
## Summary
 Hello! So I'm a newby in Gatsby but have a fair understanding on programming (HTML, CSS etc). But I've managed to integrate a Wordpress blog to a Gatsby site using all the tutorials online. The part I'm stuck at is how to update the site when a new post is published whilst using Heroku. I've seen that most people seem to be using Netlify to host their site and I'm not sure how to apply the same principles on Heroku.  

Any advice or help would be greatly appreciated. Thank you :) 

## Relevant information

The Wordpress site is hosted on Wordpress.com, not locally. I don't know if that changes anything. 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by graysonhicks** [comment]
I haven't used Heroku in a bit, but it looks like they have a webhooks API [here](https://devcenter.heroku.com/articles/app-webhooks).  Wordpress also has webhook functionality [here](https://wordpress.com/support/webhooks/#:~:text=You%20can%20add%20a%20webhook,when%20the%20selected%20action%20fires.). 

You will need to configure your Wordpress to trigger your Heroku webhook when content is published.

**Comment by jasonbahl** [comment]
If I'm not mistaken, the Heroku webhooks API @graysonhicks linked to is for configuring webhooks to be sent _out_ of Heroku when things happen in the Heroku environment. 

I believe what would be needed is to make use of the Heroku  Platform API to make a build request: https://devcenter.heroku.com/articles/platform-api-reference

You could use the WordPress webhook functionality to send a webhook from WordPress to Heroku when content in WordPress changes, but I believe the destination the WordPress webhook needs to post to would need to be to a Heroku Platform API endpoint.

I'm not familiar enough with the Heroku APIs to give expert advice here, but this article looks promising: https://devcenter.heroku.com/articles/build-and-release-using-the-api

**Comment by graysonhicks** [comment]
@mumbii Have you had any luck with the approach described by @jasonbahl ?

**Comment by richhiggins** [comment]
I have a Gatsby app on Heroku with webhook triggered builds. We are using Contentful but the integration should be more or less the same. On a publish event you'll want to hit Heroku's build endpoint with a POST request.

We also trigger the nightly build using the following config with axios, here you can see the endpoint, headers and data payload you need to send from your webhook.

```
const axiosOptions = {
  url: 'https://api.heroku.com/apps/<HEROKU_APP_NAME>/builds',
  method: 'POST',
  headers: {
    Accept: 'application/vnd.heroku+json; version=3',
    Authorization: `Bearer <HEROKU_AUTH_TOKEN>`,
    'Content-Type': 'application/json',
  },
  data: {
    source_blob: {
      url: `https://<GITHUB_AUTH_USERNAME>:<GITHUB_AUTH_API_KEY>@github.com/<GITHUB_USERNAME>/<GITHUB_REPOSITORY_NAME>/archive/master.tar.gz`,
    },
  },
}
```
