### ISSUE TITLE
Move webpackManifest to below body

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#2541]
It can get quite large on big sites so blocks the initial render.

We'd need to revisit how to ensure webpack doesn't start working until this is read in.

Requested in https://github.com/reactjs/reactjs.org/issues/179

**Comment by Daniel15** [comment]
>  how to ensure webpack doesn't start working until this is read in.

I'm not very experienced with Webpack, but won't everything "just work" if all the JS is at the bottom of the body? Since Gatsby sites work without JS (I assume), it would make sense to defer as much of it as possible.

**Comment by KyleAMathews** [comment]
eh probably :-) I haven't thought about this stuff for 6 months so I'd need to research to remember why I moved it back to the top.

But yeah, I don't think this is a very hard fix.

**Comment by szimek** [comment]
@KyleAMathews What exactly is this `webpackManifest` used for? Does it list *all* pages? We're planning to use Gatsby and Contentful to run a blog with ~5000 pages, so it will probably get quite huge - assuming a single entry is ~60 bytes, it will be additional ~300kB on each page?

**Comment by szimek** [comment]
@KyleAMathews This issue can be closed now thanks to https://github.com/gatsbyjs/gatsby/pull/3519.

**Comment by KyleAMathews** [comment]
@szimek thanks again for the PR!
