### ISSUE TITLE
Integrate static pages generated by Gatsby into Gatsby

### ISSUE THREAD

**Issue by Chaosbohne** [gatsbyjs/gatsby#25416]
How to integrate generated Gatsby files into another Framework or in another Gatsby Project?

Status Quo:
I got an app A based on Gatsby. This application is running fine and provides a path for '/blog/'. For example '/blog/1' gives the blog entry with id 1, '/blog/2' gives the blog entry with id 2 and so on. This app is not hosted as standalone.

I got another app B (the main app) running on Angular. This application is running fine and provides a navigation bar containing different sections. For example path for '/shop/', '/getting-started' and '/about'.

I got another app C running on Gatsby. This application is running fine and provides other paths.

Goal:
App A must be integrated into App B and App C but must be kept as separate project. Note that App B is a Angular App whereas App C is another Gatsby project. See the mockup to have a better understanding.

![image](https://user-images.githubusercontent.com/2006115/86132201-e24a8380-bae6-11ea-8543-e0b00520b188.png)

I started integrating a A to C. A Gatsby Project into a Gatsby Project so to say. I did this using an iframe and found a solution to this here: https://github.com/gatsbyjs/gatsby/issues/17761 Unfortunately this does not seem to work when the local sources are Gatsby source code. The iframe renders recursively. (find a reproducible example here: https://github.com/Chaosbohne/gatsby_iframe_example).

I also tried to render the html as innerHtml but this somehow overwrites the existing page. Unfortunately I didn't found a way to change the '___gatsby' identifier. Adding innerHtml results in a duplication of the '___gatsby' identifier.

My question is not necessarily about the solution of the embed as an iframe but rather best practices in general about the mentioned problem. Should I tweak the generation of webpack in some way? 

Edit: I was able to render the gatsby static files as iframe. The key was to change the page-path of the web page. This could work out, still I would be interested in best practices.

**Comment by vladar** [comment]
User experience with iframes is rather poor. I would suggest replicating common parts of the UI (top menu?) in all projects and just navigate as usual (so when moving across different app boundaries the page would reload but when you are within the same app it will transition smoothly)

Make sure to set [path prefix](https://www.gatsbyjs.org/docs/path-prefix) in `gatsby-config.js` to make gatsby sites work correctly with non-root routes.

**Comment by LekoArts** [comment]
Thanks for the issue, will close this as answered.
