### ISSUE TITLE
Dev server crashes when files are deleted/renamed

### ISSUE THREAD

**Issue by mickeyreiss-visor** [gatsbyjs/gatsby#2542]
Steps to reproduce:

```sh
gatsby develop
rm src/pages/mypage.js
```

Console output:
```
./node_modules/.bin/gatsby --version
1.1.10
yarn start v1.0.2
$ gatsby develop --port 4567
success delete html files from previous builds — 0.027 s
success open and validate gatsby-config.js — 0.008 s
success copy gatsby files — 0.022 s
success onPreBootstrap — 0.009 s
success source and transform nodes — 0.033 s
success building schema — 0.224 s
success createLayouts — 0.032 s
success createPages — 0.012 s
success createPagesStatefully — 0.036 s
success onPreExtractQueries — 0.002 s
success extract queries from components — 0.133 s
success run graphql queries — 0.021 s
success write out page data — 0.003 s
success write out redirect data — 0.001 s
success update schema — 0.091 s
success onPostBootstrap — 0.003 s

info bootstrap finished - 2.319 s

error UNHANDLED REJECTION


  Error: ENOENT: no such file or directory, open '/[redacted]/code/github.com/[redacted]/src/pages/[redacted].js'

  - Error

  - file-parser.js:239 FileParser._callee3$
    [...]/[gatsby]/dist/internal-plugins/query-runner/file-parser.js:239:25

  - file-parser.js:287 FileParser.parseFile
    [...]/[gatsby]/dist/internal-plugins/query-runner/file-parser.js:287:20

  - file-parser.js:304
    [...]/[gatsby]/dist/internal-plugins/query-runner/file-parser.js:304:30

  - Array.map

  - file-parser.js:303 FileParser._callee4$
    [...]/[gatsby]/dist/internal-plugins/query-runner/file-parser.js:303:67
```

Impact: Gatsby develop crashes during development.

If this issue is confirmed, I'd be happy to try to fix it. I think the fix will involve catching the ENOENT error, or preventing it in the first place by rechecking for file existence in file-parser.js.

Thanks!

**Comment by KyleAMathews** [comment]
I do recall seeing something similar to this so yes, would love a fix!

**Comment by mickeyreiss** [comment]
OK. Here's what I've learned:

* A reference to the deleted file remains in the components state in redux;
* This causes the file to be included in the glob in parseEverything;[1]
* Which this leads to the file name being passed into `parseFiles`,[2]
* Whereupon, we fail to read the non-existent file.[3]

The easy solution would be to check for file existence before reading in `parseFiles` (or just swallow the exception.)
  
However, this would leave what is now a known subtle caching bug. So, a better solution is to fix the caching bug in redux and remove the defunct reference when pages are deleted.

***

[1]:

https://github.com/gatsbyjs/gatsby/blob/38149a23a87cb91e0c6047cba2e20eb533da97b5/packages/gatsby/src/internal-plugins/query-runner/query-compiler.js#L78-L84

[2]:

https://github.com/gatsbyjs/gatsby/blob/38149a23a87cb91e0c6047cba2e20eb533da97b5/packages/gatsby/src/internal-plugins/query-runner/query-compiler.js#L99

[3]:

https://github.com/gatsbyjs/gatsby/blob/38149a23a87cb91e0c6047cba2e20eb533da97b5/packages/gatsby/src/internal-plugins/query-runner/file-parser.js#L121

**Comment by liligga** [comment]
@KyleAMathews  Still have a problem with this when components in `pages` directory are renamed. Here for instance I renamed `myProfileSitter.js` to something else:
```
 ｢wdm｣: Compiling...
 ERROR  Failed to compile with 1 errors   

 error  in ./src/pages/myProfileSitter.js

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: ENOENT: no such file or directory, open 'pathToApp/src/pages/myProfileSitter.js'

 @ ./.cache/sync-requires.js 16:62-123
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app

✖ ｢wdm｣:
ERROR in ./src/pages/myProfileSitter.js
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: ENOENT: no such file or directory, open 'pathToApp/src/pages/myProfileSitter.js'
 @ ./.cache/sync-requires.js 16:62-123
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.
```
and my dependencies are:
```
  "dependencies": {
    "bulma": "^0.7.1",
    "gatsby": "^2.0.0",
    "gatsby-plugin-manifest": "^2.0.2",
    "gatsby-plugin-offline": "^2.0.5",
    "gatsby-plugin-react-helmet": "^3.0.0",
    "gatsby-plugin-sass": "^2.0.1",
    "gatsby-source-contentful": "^2.0.1",
    "node-sass": "^4.9.3",
    "react": "^16.5.1",
    "react-dom": "^16.5.1",
    "react-helmet": "^5.2.0"
  },
```
So for everything to work I have to restart `gatsby develop`.
