### ISSUE TITLE
Add information about css-loader version and point to its actual documentation 

### ISSUE THREAD

**Issue by SilencerWeb** [gatsbyjs/gatsby#25420]
## Summary
Currently, Gatsby uses `css-loader@1.0.1` and when it comes to configuration of this loader, Gatsby's documentation always points on `css-loader`'s documentation which is good except the fact that current `css-loader`'s version is 3.6.0 and it has a lot of breaking changes in their API, including adding and removing some options.

So, basically, Gatsby's documentation says that you can configure this loader like it is documented here but actually, you can't. For example, such options as `localsConvention`, `onlyLocals` and `esModule` are introduced in new `css-loader`'s versions and not available in `css-loader@1.0.1`. Such options as `localIdentName` and `camelCase` were removed and there is no documentation for them.

Today I spent a lot of time figuring out how to set up `css-loader` so it would convert my dashed classes into camel-cased but also leave original ones. Apparently, I had to set `camelCase: true` (in versions of the loader, `localsConvention: 'camelCase'` is an equivalent for this).

So my proposal is to point in the documentation that Gatsby is using `css-loader@1.0.1` and also replace the link that leads to `css-loader` documentation on this one — https://github.com/webpack-contrib/css-loader/tree/version-1. I'm sure it would save me a lot of time and what is more important — it can save a lot of time for others.

Not sure about places where this needs to be done, but here is one of them — https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sass.

**Comment by vladar** [comment]
Sorry to hear you've wasted some time because of this. The note in docs makes perfect sense to me. Mind opening a PR with suggested changes? 

Thanks for caring about the community 💜

**Comment by SilencerWeb** [comment]
I'll try to open it this weekend. Any suggestions and tips? 🙂

**Comment by meandillar** [comment]
I have been attempting to configure css-loader use v3 docs for the last couple of hours. Glad I came across this issue.

**Comment by graysonhicks** [comment]
PR addressing the link in the primary Gatsby docs. https://github.com/gatsbyjs/gatsby/pull/25575

Will be creating PRs in the appropriate plugins doing the same.
