### ISSUE TITLE
gatsby-source-contentful: cannot get image uri after updating content in contentful

### ISSUE THREAD

**Issue by jjbully** [gatsbyjs/gatsby#25433]
## Description

cannot get image's uri after updating content in contentful

can go back to normal if i use `gatsby clean` after updating things in contentful and then `gatsby develop` again

### Steps to reproduce
- create a blog post content type contentful, 
 sthg like:
\- blog post
\-- image
\-- title
\-- subtitle

-  `gatsby develop`   source the data from contentful

- change sthg in contentful

- `gatsby develop` source the data from contentful again

### Expected result
the data sourced will be like this, has the imag's file uri (embedded-asset-block)

```json
{
  "data": {
    "contentfulPost": {
      "id": "3875ab8b-3e1b-5f31-9f17-5f758065f109",
      "content": {
        "json": {
          "nodeType": "document",
          "data": {},
          "content": [
            {
              "nodeType": "paragraph",
              "content": [
                {
                  "nodeType": "text",
                  "value": "one piece",
                  "marks": [],
                  "data": {}
                }
              ],
              "data": {}
            },
            {
              "nodeType": "embedded-asset-block",
              "content": [],
              "data": {
                "target": {
                  "sys": {
                    "space": {
                      "sys": {
                        "type": "Link",
                        "linkType": "Space",
                        "id": "orvemwqyam9t",
                        "contentful_id": "orvemwqyam9t"
                      }
                    },
                    "id": "c1EXk6yQUmeD5ubIzqxc0V5",
                    "type": "Asset",
                    "createdAt": "2020-07-01T08:17:09.579Z",
                    "updatedAt": "2020-07-01T08:17:09.579Z",
                    "environment": {
                      "sys": {
                        "id": "master",
                        "type": "Link",
                        "linkType": "Environment",
                        "contentful_id": "master"
                      }
                    },
                    "revision": 1,
                    "contentful_id": "1EXk6yQUmeD5ubIzqxc0V5"
                  },
                  "fields": {
                    "title": {
                      "en-US": "Android-Lollipop-Wallpaper-Widescreen-D34"
                    },
                    "description": {
                      "en-US": "android wallpaper"
                    },
                    "file": {
                      "en-US": {
                        "url": "//images.ctfassets.net/orvemwqyam9t/1EXk6yQUmeD5ubIzqxc0V5/e8b033760f60e762411faf49af603469/Android-Lollipop-Wallpaper-Widescreen-D34.jpg",
                        "details": {
                          "size": 45828,
                          "image": {
                            "width": 676,
                            "height": 846
                          }
                        },
                        "fileName": "Android-Lollipop-Wallpaper-Widescreen-D34.jpg",
                        "contentType": "image/jpeg"
                      }
                    }
                  }
                }
              }
            },
            {
              "nodeType": "paragraph",
              "content": [
                {
                  "nodeType": "text",
                  "value": "",
                  "marks": [],
                  "data": {}
                }
              ],
              "data": {}
            }
          ]
        }
      }
    }
  }
}
```

### Actual result
i got sthg below after updating things in contentful and then develop again
(embedded-asset-block)

```json
{
  "data": {
    "contentfulPost": {
      "id": "3875ab8b-3e1b-5f31-9f17-5f758065f109",
      "content": {
        "json": {
          "nodeType": "document",
          "data": {},
          "content": [
            {
              "nodeType": "paragraph",
              "content": [
                {
                  "nodeType": "text",
                  "value": "one piece",
                  "marks": [],
                  "data": {}
                }
              ],
              "data": {}
            },
            {
              "nodeType": "paragraph",
              "content": [
                {
                  "nodeType": "text",
                  "value": "afafsasfdasdfasdf",
                  "marks": [],
                  "data": {}
                }
              ],
              "data": {}
            },
            {
              "nodeType": "paragraph",
              "content": [
                {
                  "nodeType": "text",
                  "value": "",
                  "marks": [],
                  "data": {}
                },
                {
                  "nodeType": "hyperlink",
                  "content": [
                    {
                      "nodeType": "text",
                      "value": "one piece ",
                      "marks": [],
                      "data": {}
                    }
                  ],
                  "data": {
                    "uri": "https://google.com"
                  }
                },
                {
                  "nodeType": "text",
                  "value": "",
                  "marks": [],
                  "data": {}
                }
              ],
              "data": {}
            },
            {
              "nodeType": "embedded-asset-block",
              "content": [],
              "data": {
                "target": {
                  "sys": {
                    "id": "c1EXk6yQUmeD5ubIzqxc0V5",
                    "type": "Link",
                    "linkType": "Asset",
                    "contentful_id": "1EXk6yQUmeD5ubIzqxc0V5"
                  }
                }
              }
            },
            {
              "nodeType": "paragraph",
              "content": [
                {
                  "nodeType": "text",
                  "value": "",
                  "marks": [],
                  "data": {}
                }
              ],
              "data": {}
            }
          ]
        }
      }
    }
  }
}
```

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12 
    gatsby-image: ^2.4.9 => 2.4.9 
    gatsby-plugin-feed: ^2.5.7 => 2.5.7 
    gatsby-plugin-google-analytics: ^2.3.6 => 2.3.6 
    gatsby-plugin-manifest: ^2.4.14 => 2.4.14 
    gatsby-plugin-offline: ^3.2.13 => 3.2.13 
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.6 
    gatsby-plugin-sharp: ^2.6.14 => 2.6.14 
    gatsby-plugin-typography: ^2.5.6 => 2.5.6 
    gatsby-remark-copy-linked-files: ^2.3.7 => 2.3.7 
    gatsby-remark-images: ^3.3.14 => 3.3.14 
    gatsby-remark-prismjs: ^3.5.6 => 3.5.6 
    gatsby-remark-responsive-iframe: ^2.4.7 => 2.4.7 
    gatsby-remark-smartypants: ^2.3.6 => 2.3.6 
    gatsby-source-contentful: ^2.3.18 => 2.3.18 
    gatsby-source-filesystem: ^2.3.14 => 2.3.14 
    gatsby-transformer-remark: ^2.8.20 => 2.8.20 
    gatsby-transformer-sharp: ^2.5.7 => 2.5.7 
  npmGlobalPackages:
    gatsby-cli: 2.12.52

**Comment by vladar** [comment]
@axe312ger Does it relate to the rich text work you do now? Is it a known issue?

**Comment by nicolauscg** [comment]
I found that inside rich text, an embedded jpg asset's graphql result is missing `data.target.fields` unlike png assets so file url is not present. Current workaround is to only use png assets. `gatsby-source-contentful` version 2.3.26

```
{
  // embedded jpg asset in rich text
  "nodeType": "embedded-asset-block",
  "content": [],
  "data": {
    "target": {
      "sys": {
        "id": "c3jo..",
        "type": "Link",
        "linkType": "Asset",
        "contentful_id": "3jo.."
      }
    }
  }
},
{
  //  embedded png asset in rich text
  "nodeType": "embedded-asset-block",
  "content": [],
  "data": {
    "target": {
      "sys": {
        "space": {
          "sys": {
            "type": "Link",
            "linkType": "Space",
            "id": "c5w8..",
            "contentful_id": "c5w8.."
          }
        },
        "id": "c2Mn..",
        "type": "Asset",
        "createdAt": "2020-07-11T09:31:58.302Z",
        "updatedAt": "2020-07-11T09:31:58.302Z",
        "environment": {
          "sys": {
            "id": "master",
            "type": "Link",
            "linkType": "Environment",
            "contentful_id": "master"
          }
        },
        "revision": 1,
        "contentful_id": "2MnP.."
      },
      "fields": {
        "title": { ... },
        "description": { ... },
        "file": { ... }
      }
    }
  }
},
```

**Comment by axe312ger** [comment]
Hey there, 

sorry we had some delays, but there is now a version for you to test. The whole change is breaking, thats why we are releasing a canary version before merging everything to master.


The new Contentful source plugin can be installed via `npm i gatsby-source-contentful@next`.

Migration instructions can be found here:  https://github.com/gatsbyjs/gatsby/pull/25249

Would be amazing if you could confirm that the new version fixes your issue.

Thanks,
Benedikt

**Comment by axe312ger** [comment]
This will be fixed in https://github.com/gatsbyjs/gatsby/pull/27244 which will be released soon :)

**Comment by HJordan35** [comment]
@axe312ger - I am still experiencing this same issue in my environment, and it changed over-night without any change to Contentful content, or React code. We did a build yesterday and everything deployed without issue - then this morning, one of our pages broke because an `embedded-asset-block` object does not contain node.data.target.fields....it only contains data.target.sys 

Similar to the response above, this issue only seems to impact `.jpg` files - `png` files work as expected.

I attempted updating a few packages, namely Gatsby (currently using 2.30) and Gatsby-Source-Contentful (migrated to 4.4.0) but this does not seem to have resolved the issue

**Comment by axe312ger** [comment]
@HJordan35 I can only offer you this:

Add the `--verbose` flag to your build commands to get the full, extended logs.

Wait till the issue happens again

Send your full log to https://www.contentful.com/support/, mention Gatsby and this issue, and your log will be redirected to me. That way we can reconstruct what happened on API and Gatsby side, as currently I never did run into that issue and have trouble replicating.

Thanks
