### ISSUE TITLE
gatsby-plugin-sass  didn't work!

### ISSUE THREAD

**Issue by Stoneleee** [gatsbyjs/gatsby#2543]
I installed this package, and config as the picture blow, but it didn't work,
was there anything wrong for my usage?

**by the way, the default starter I used**
![default](https://user-images.githubusercontent.com/28681019/31802543-6f687498-b581-11e7-9308-1d8a72608120.png)

**Comment by KyleAMathews** [comment]
Try running the sass example site https://github.com/gatsbyjs/gatsby/tree/master/examples/using-sass

**Comment by Stoneleee** [comment]
cool !
but why,
the tutorial of gatsby's website makes me confused,

**Comment by Stoneleee** [comment]
Oh, I resolved that after watching [this video](https://www.youtube.com/watch?v=Jm7AMhKLeIU&t=312s)
just rerun ```gatsby develop```, 
😂  😂  😂
