### ISSUE TITLE
Compilation error after switching to Dart implementation

### ISSUE THREAD

**Issue by robertjk** [gatsbyjs/gatsby#25430]
## Description

Development compilation of my styles is failing after changing from `node-sass` to `sass` (Dart implementation). The error message doesn't tell me anything about what's going on - it seems it's a syntax error on a perfectly legal Sass syntax.

When I try compiling that same file that's throwing an error manually using the same `sass` executable: `npx sass <name-of-the-file>` the complication is successful - doesn't produce any errors and outputs proper CSS. So the problem seems to be somewhere within the chain of loaders that are applied in the Webpack compilation process.

### Steps to reproduce

1. The styles are compiling perfectly fine when running `gatsby develop`.
2. Change the line in `gatsby-config.js` from:
    ```
    "gatsby-plugin-sass",
    ```
    to:
    ```
    {
      resolve: `gatsby-plugin-sass`,
      options: {
        // Use Dart implementation of Sass instead of Node one
        implementation: require("sass"),
      },
    },
    ```
3. Install `sass` by `npm install sass`.
4. Re-run Gatsby development environment by killing the initial environment and executing `gatsby develop` again.

### Expected result

The styles should compile successfully as before.

### Actual result

The styles compilation is now throwing an error:

```
  ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


// Main style base file. Import all style base blocks in proper order.
^
      Invalid CSS after "": expected 1 selector or at-rule, was "var content = requi"
      in /home/robert/programming/credijusto/landing-website/src/styles/index.scss (line 1, column 1)

File: src/styles/index.scss

failed Re-building development bundle - 0.058s
```

The contents of _index.scss_ file that's throwing an error:

```
// Main style base file. Import all style base blocks in proper order.
//
// NOTE: This is the only file from styles/ that should be imported in other
// files.

// Our base styles
@import "./typography";
@import "./layout";

```

And I import this file in a React component:

```
import { useStaticQuery, graphql } from "gatsby";
import React from "react";
import PropTypes from "prop-types";

import Header from "~components/Header";
import Footer from "~components/Footer";

// Base styles (global - for all components)
import "~styles/index.scss";

function Layout({ children }) {
  const data = useStaticQuery(graphql`
    query SiteTitleQuery {
      site {
        siteMetadata {
          title
        }
      }
    }
  `);

  return (
    <div>
      <Header siteTitle={data.site.siteMetadata.title} />
      <main>{children}</main>
      <Footer />
    </div>
  );
}

Layout.propTypes = {
  children: PropTypes.node.isRequired,
};

export default Layout;
```

### Environment

  System:
    OS: Linux 5.7 Arch Linux
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.4.0 - /sbin/node
    Yarn: 1.22.4 - /sbin/yarn
    npm: 6.14.5 - /sbin/npm
  Languages:
    Python: 3.8.3 - /sbin/python
  Browsers:
    Firefox: 77.0.1
  npmPackages:
    gatsby: ^2.23.3 => 2.23.3
    gatsby-image: ^2.4.7 => 2.4.7
    gatsby-plugin-manifest: ^2.4.11 => 2.4.11
    gatsby-plugin-offline: ^3.2.9 => 3.2.9
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.4
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^2.3.5 => 2.3.5
    gatsby-plugin-sharp: ^2.6.11 => 2.6.11
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.3.11 => 2.3.11
    gatsby-transformer-sharp: ^2.5.5 => 2.5.5

**Comment by vladar** [comment]
Hi @robertjk !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by robertjk** [comment]
While reproducing the case, I found the bug. It was in my configuration:

```
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-sass`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-sass`,
      options: {
        // Use Dart implementation of Sass instead of Node one
        implementation: require("sass"),
      },
    },
    {
      resolve: "gatsby-plugin-react-svg",
      options: {
        rule: {
          include: /\.svg$/,
        },
      },
    },
    {
      resolve: "gatsby-plugin-web-font-loader",
      options: {
        google: {
          families: ["Inter:regular,bold"],
        },
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
```

I listed `gatsby-plugin-sass` two times. My mistake. Closing the issue. And thanks for the response :).
