### ISSUE TITLE
Gatsby useStaticQuery fails with NPM package

### ISSUE THREAD

**Issue by jarodpeachey** [gatsbyjs/gatsby#25446]
## Description

I'm creating two NPM packages for Gatsby. One of these is a source plugin, and the other includes a JSX component that grabs data from GraphQL to be imported as a component by the end user.

However, the static query for the latter component fails with an error.

```
Error: It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away. Unfortunately, something went wrong and the query was left in the compiled code.
```

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

1. Go to https://github.com/jarodpeachey/netlify-comments and clone the repo
2. Run yarn install
3. Run lerna link and lerna bootstrap
4. `cd packages/netlify-comments`
5. `npm run compile`
6. cd ../gatsby-demo
7. `npm start`

### Expected result
The component located at packages/netlify-comments/src/Comments.js should build properly.

### Actual result
The static query fails and the component does not build.

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.4 - /c/Users/Able Family Life/AppData/Local/Programs/Python/Python37-32/python
  Browsers:
    Edge: 44.19041.1.0

**Comment by vladar** [comment]
Hi @jarodpeachey 

I've followed your steps but I don't see this error. What I get is this:

```
warn Using the global `graphql` tag is deprecated, and will not be supported in v3.
Import it instead like:  import { graphql } from 'gatsby' in file:
./netlify-comments/packages/gatsby-demo/src/pages/index.js
```

But that's because you don't import `graphql` in your [index.js page](https://github.com/jarodpeachey/netlify-comments/blob/master/packages/gatsby-demo/src/pages/index.js) (as the error says).

As for [`packages/netlify-comments/src/Comments.js`](https://github.com/jarodpeachey/netlify-comments/blob/master/packages/netlify-comments/src/Comments.js) - `useStaticQuery` is never called there (even though it is imported). Did you already change something there?

It's hard to debug the issue this way. It is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by jarodpeachey** [comment]
Ah, my bad. I forgot to push the latest code. I just did that now.

**Comment by freiksenet** [comment]
@jarodpeachey I can't run the reproduction without netlify code, but I think the problem is that you don't use `babel-preset-gatsby` in netlify comments, so graphql tags aren't stripped. I'm not sure if it will work correctly with it, but it's something you can try. If you could email me your netlify api token to freiksenet@gatsbyjs.com, I could try debugging it more.

**Comment by jarodpeachey** [comment]
Yeah, I just tried that. It throws an error about needing to run `gatsby build`.

```
Error: [BABEL] D:\Netlify Comments\packages\netlify-comments\src\apollo\client.js: `babel-preset-gatsby` has been loaded, which consumes config generated by the Gatsby CLI. 
Set `NODE_ENV=test` to bypass, or run `gatsby build` first. (While processing: "D:\\Netlify Comments\\packages\\netlify-comments\\node_modules\\babel-preset-gatsby\\index.js")
```

**Comment by freiksenet** [comment]
@jarodpeachey Got your token. It seems to work for me now. Could you try upgrading gatsby version and see if this helps?

**Comment by jarodpeachey** [comment]
@freiksenet Should I update gatsby in the netlify-comments directory, or the gatsby-demo directory?

**Comment by freiksenet** [comment]
I think in both - the versions should also match.

**Comment by jarodpeachey** [comment]
@freiksenet When you say it worked, did the site show up in localhost:8000?

Because it compiles properly but doesn't work in the browser.

**Comment by freiksenet** [comment]
Yep, both gatsby develop and build/serve.

![2020-07-03-15:49:20](https://user-images.githubusercontent.com/172936/86470787-d22fdf80-bd44-11ea-8761-8456583b5b91.png)
![2020-07-03-15:49:04](https://user-images.githubusercontent.com/172936/86470789-d2c87600-bd44-11ea-9269-7b17570beddc.png)

**Comment by jarodpeachey** [comment]
Hm... what are the exact steps you ran? It still gives me the error:

```
Error: [BABEL] D:\Netlify Comments\packages\netlify-comments\src\apollo\client.js: `babel-preset-gatsby` has been loaded, which consumes config generated by the Gatsby CLI. Set `NODE_ENV=test` to bypass, or run `gatsby build` first.
```

**Comment by jarodpeachey** [comment]
@freiksenet Can you give an example?

**Comment by jarodpeachey** [comment]
@freiksenet Do you still have the working example?

**Comment by jarodpeachey** [comment]
@TylerBarnes @freiksenet Have you looked into this yet?

**Comment by sidharthachatterjee** [comment]
@jarodpeachey Queries are only supported in packages that include `gatsby` in their name. We do this because scanning through _all_ installed packages is _very_ expensive. I think this might be undocumented unfortunately. (Cc @AishaBlake)

**Comment by jarodpeachey** [comment]
Hey @sidharthachatterjee I've renamed the package to gatsby-plugin-netlify-comments, and it still gives the error.

This is my .babelrc file:

{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "babel-plugin-styled-components",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-transform-runtime",
    "babel-plugin-macros",
    "babel-plugin-transform-react-remove-prop-types",
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-optional-chaining",
    "babel-plugin-optimize-hook-destructuring"
  ]
}

**Comment by jarodpeachey** [comment]
Hey @sidharthachatterjee I've renamed the package to gatsby-plugin-netlify-comments, and it still gives the error.

This is my .babelrc file:

{
"presets": [
"@babel/preset-env",
"@babel/preset-react"
],
"plugins": [
"babel-plugin-styled-components",
"@babel/plugin-proposal-class-properties",
"@babel/plugin-syntax-dynamic-import",
"@babel/plugin-transform-runtime",
"babel-plugin-macros",
"babel-plugin-transform-react-remove-prop-types",
"@babel/plugin-proposal-nullish-coalescing-operator",
"@babel/plugin-proposal-optional-chaining",
"babel-plugin-optimize-hook-destructuring"
]
}
