### ISSUE TITLE
Using ESLint https://www.gatsbyjs.org/docs/eslint/ ... missing step?

### ISSUE THREAD

**Issue by stevenkkim** [gatsbyjs/gatsby#25449]
I tried following the steps outlined here https://www.gatsbyjs.org/docs/eslint/ and it did not work.

After trying various things out, I finally got it to work after installing https://www.gatsbyjs.org/packages/gatsby-plugin-eslint/

If installing gatsby-plugin-eslint is a required step, then it should be added to the instructions here: https://www.gatsbyjs.org/docs/eslint

See also my response here: https://github.com/gatsbyjs/gatsby/issues/22285

**Comment by herecydev** [comment]
It is in there:

> When you include a custom .eslintrc file, Gatsby gives you full control over the ESLint configuration. This means that it will override the built-in eslint-loader and you need to enable any and all rules yourself. One way to do this is to use the Community plugin gatsby-eslint-plugin.

**Comment by stevenkkim** [comment]
Ok, that note wasn't clear to me at all.  I thought that note referred to a **different** method of managing ESLint configuration because the instructions on https://www.gatsbyjs.org/docs/eslint refer to using `.eslintrc.js` while the note refers to using a custom `.eslintrc` file. I thought they were two different files and therefore two different methods.

In other words, I interpret the docs as saying there are two ways to manage ESLint:

Method #1 explained on https://www.gatsbyjs.org/docs/eslint
Step 1: npm install --save-dev eslint-config-react-app
Step 2: create `.eslintrc.js` file using module.exports for configuration

OR

Method #2 explained on https://www.gatsbyjs.org/packages/gatsby-plugin-eslint/
Step 1: npm install --save-dev gatsby-plugin-eslint
Step 2: npm install --save-dev eslint eslint-loader
Step 3: create `.eslintrc` file using json for configuration

Do you see why I interpreted it that way?

I think on https://www.gatsbyjs.org/docs/eslint/ if you explicitly include the step of adding `gatsby-plugin-eslint` in the "How to use ESLint", that would be clear.

Thanks!

**Comment by ascorbic** [comment]
Tagging docs team to see if this needs clarifying.

**Comment by gitjeff05** [comment]
I was also a little confused here:

> When you include a custom .eslintrc file, Gatsby gives you full control over the ESLint configuration. This means that it will override the built-in eslint-loader and you need to enable any and all rules yourself. One way to do this is to use the Community plugin gatsby-eslint-plugin. This also means that the default ESLint config Gatsby ships with will be entirely overwritten. If you would still like to take advantage of those rules, you’ll need to copy them to your local file.

#### A clearer distinction between the `eslint-loader` options and `eslint` rules may help.

I *believe* the interpretation is that when including your own `.eslintrc` file, **both** the `eslint-loader` configuration *and* the `eslint` rules that come with Gatsby are overridden. Getting them back involves two steps:

  1. To get the `eslint-loader` options back, [install the `gatsby-plugin-eslint` plugin and add it to the `gatsby-config.js` file](https://www.gatsbyjs.org/packages/gatsby-plugin-eslint/). 
  2. To get the `eslint` rules back, copy [gatsby's default eslint rules](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/eslint-config.ts) into your `.eslintrc` file. 

Is this correct?

_Aside: is it `gatsby-plugin-eslint` or `gatsby-eslint-plugin`? Both ways are referenced._

**Comment by stevengrimaldo** [comment]
> @herecydev Thanks for the reply.
> 
> That note wasn't clear to me at all. I thought that note referred to a **different** method of managing ESLint configuration because the instructions on https://www.gatsbyjs.org/docs/eslint refer to using `.eslintrc.js` while the note refers to using a custom `.eslintrc` file. I thought they were two different files and therefore two different methods. Furthermore, saying "One way to do this..." makes it sound like an alternative method, not a required step.
> 
> In other words, I interpret the docs as saying there are two ways to manage ESLint:
> 
> Method 1 explained on https://www.gatsbyjs.org/docs/eslint Step 1: npm install --save-dev eslint-config-react-app Step 2: create `.eslintrc.js` file using module.exports for configuration
> 
> OR
> 
> Method 2 explained on https://www.gatsbyjs.org/packages/gatsby-plugin-eslint/ Step 1: npm install --save-dev gatsby-plugin-eslint Step 2: npm install --save-dev eslint eslint-loader Step 3: create `.eslintrc` file using json for configuration
> 
> Do you see why I interpreted it that way? And I don't think it is just me, issue #22285 happened for the same reason – this user followed the steps the same way I interpreted them in Method 1 without adding gatsby-plugin-eslint.
> 
> I think on https://www.gatsbyjs.org/docs/eslint/ if you explicitly include the step of adding `gatsby-plugin-eslint` in the "How to use ESLint", that would be clear.
> 
> Thanks!

+1

**Comment by maxenko** [comment]
This has worked for me:

1. Create .eslintrc.js
2. basic config: 
```js module.exports = {
    globals: {
        __PATH_PREFIX__: true,
    },
    extends: ["react-app", "eslint:recommended"],
    "env": {
        "browser": true,
        "node": true
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "no-unused-vars": "warn"
    }
}
```
3. npm i gatsby-plugin-eslint
4. Add it to gatsby config: 
```js module.exports = {
    plugins: [
		"gatsby-plugin-eslint"
	],
    }

Then configure to preference, as above is pretty strict.
