### ISSUE TITLE
If this is an 'official' plugin you need to document it better

### ISSUE THREAD

**Issue by juanjoseluisgarcia** [gatsbyjs/gatsby#25451]
- Do not include minified code in the examples. If you think it's better that way include the functionality in the plugin itself

- provide a full working example. Not pseudo-code or place holders like '...'

- make sure anyone that has not coded the plugin themselves with knowledge of React can actually use it.

**Comment by marcysutton** [comment]
Hi @juanjoseluisgarcia, we need more information from you to properly take action on this issue. Can you provide more details, such as:

- Which plugin you're talking about
- Links to any documentation pages

Thanks!

**Comment by juanjoseluisgarcia** [comment]
Apologies for commenting on the general repo. The plugin I refer to is `gatsby-plugin-gdpr-cookies` It seems really that it needs work both in the plugin itself and the docs.

**Comment by LekoArts** [comment]
Please open an issue on https://github.com/andrezimpel/gatsby-plugin-gdpr-cookies as we don't maintain this plugin. Thanks!
