### ISSUE TITLE
[feat]: run babel macros before extracting graphql queries 

### ISSUE THREAD

**Issue by bennetthardwick** [gatsbyjs/gatsby#25459]
## Summary

Babel macros are [supported](https://www.gatsbyjs.org/docs/babel-plugin-macros/) by Gatsby, however, despite being run at compile time they're not able to generate static queries. Attempting to do so results in:

```
Error: It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away. Unfortunately, something went wrong and the query was left in the compiled code.
```

It would be incredibly useful to allow plugin authors and users to leverage babel macros to generate static queries.

### Motivation

Currently, the ergonomics around static queries can be quite bad and full of boilerplate. Since not all static queries are unique, it would make sense to have some method to reduce the code duplication caused by similar queries with a different parameter or something. I suppose this spirit of this feature request is similar to #10482.

**Comment by ascorbic** [comment]
Hi @bennetthardwick. Thanks for the suggestion. I'm a bit wary to do this. While I get your motivation, the use of Babel for extracting queries is really an implementation detail. If we were to enable macros we'd be tying ourselves down to that handling of them, when this is an area of active development for us. We have a big improvement to how static queries are handled coming down the line very soon. If we keep the query extraction "magic" a black box we can make improvements without it being a breaking change.
