### ISSUE TITLE
No matching version found for babel-plugin-remove-graphql-queries

### ISSUE THREAD

**Issue by lewismorris** [gatsbyjs/gatsby#25475]
## Description

When trying to run `npm install` with `gatsby: 2.23.16` the following error is outputted.

`No matching version found for babel-plugin-remove-graphql-queries@^2.9.10.`

### Steps to reproduce

`npm install --save gatsby@2.23.16`

### Expected result

NPM install should finish running.

### Actual result

NPM install errors.

### Environment

  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.0.5
  npmGlobalPackages:
    gatsby-cli: 2.12.45

**Comment by ssshooter** [comment]
![image](https://user-images.githubusercontent.com/13051472/86367386-73b82200-bcae-11ea-8a8f-ca303e73fe03.png)
Same situation

**Comment by pieh** [comment]
Thanks, on this right now - should be fixed soon. Sorry for the problem

**Comment by pieh** [comment]
I just republished https://github.com/gatsbyjs/gatsby/commit/fa41d8a5bce683cddb3d271a09baed9ee25fe6b5 :

```
Successfully published:
 - babel-plugin-remove-graphql-queries@2.9.10
 - gatsby-admin@0.1.80
 - gatsby-plugin-typescript@2.4.11
 - gatsby-source-drupal@3.5.18
 - gatsby-theme-blog-core@1.5.54
 - gatsby-theme-blog@1.6.54
 - gatsby-theme-notes@1.3.80
 - gatsby-theme-ui-preset@0.0.69
 - gatsby@2.23.15
lerna success published 9 packages
```

Something must have gone wrong in original publish, so I will leave this issue open even tho I republished

**Comment by pieh** [comment]
@lewismorris Can you try again and let me know if issue was fixed?

**Comment by stephencweiss** [comment]
@pieh, it worked for me! (solves #25476).

Thanks!

**Comment by lewismorris** [comment]
@pieh yup working great now. Thanks for the quick fix, really appreciate it.

**Comment by rajanmagar** [comment]
@pieh Yeah it's working now. Thanks.
