### ISSUE TITLE
childImageSharp: Combine resize and duotone

### ISSUE THREAD

**Issue by pichichi91** [gatsbyjs/gatsby#2547]
Hi All, so I'd like to crop the featured image and apply the duo tone filter.  Currently I have a working query, which applies the duo tone filter:
```
...
childImageSharp {
    sizes(
        duotone: {highlight: "#FFFFFF", shadow: "#3D9970"}
        toFormat: PNG
        maxWidth: 800
    ) {
            ...GatsbyImageSharpSizes
    }
}
...
```

Is there any way I can combine this with "resize(width: 800, height:300)"?

**Comment by KyleAMathews** [comment]
Just add it in :-)

```graphql
{
  childImageSharp {
    sizes { ...GatsbyImageSharpSizes }
    resize(width: 800, height: 300) { src }
  }
}
```

**Comment by pichichi91** [comment]
this generates two different images, right? I was looking to make both manipulations on same image :)

Thanks anyway!

**Comment by KyleAMathews** [comment]
Not sure what you mean? `sizes` alone produces 3-5 thumbnails. So yes it creates multiple "output" images but they're all created from the image you select.

I suggest trying the query I wrote above :-)

**Comment by pichichi91** [comment]
So basically I was looking for a way to cut the image to 800x300 AND add a duotone filter. I ended up cutting the images by myself now :)

**Comment by KyleAMathews** [comment]
Duotone is an argument you pass to resize (and sizes/resolutions). Playing in GraphiQL is your friend for discovering how arguments, etc. work. Also https://image-processing.gatsbyjs.org/ has examples for most options.
