### ISSUE TITLE
Warning: Empty string transition configs (e.g., `{ on: { '': ... }}`) for transient transitions are deprecated.

### ISSUE THREAD

**Issue by GhaithZamrik** [gatsbyjs/gatsby#25484]
When running `gatsby build` command I am getting the following warning:
```
warning Warning: Empty string transition configs (e.g., `{ on: { '': ... }}`) for transient transitions are deprecated.
Specify the transition in the `{ always: ... }` property instead. Please check the `on` configuration for "#pageComponents.inactive".
```
Having in mind that everything **works fine when running the project in development mode.** `gatsby develop`
And since it's happened the site styling and performance has been broken in some instances 
can someone elaborate please what this is exactly, and why I might be getting it? 

```
Gatsby v2.23.17
Gatsby-CLI v2.12.54
```

would appreciate any feedback, been banging my head because of this all day long.

**Comment by g-mayer** [comment]
@GhaithZamrik I was just getting this bug. I think because I recently updated the gatsby-cli to the latest version. I was able to get past that error by updating my gatsby dependencies. If you also just updated gatsby I would try updating "gatsby-plugin-offline" to the latest version.

**Comment by alchi126** [comment]
fyi I was getting this error as well as ERROR #11321 PLUGIN. Error while running the createPages lifecycle: Reducers may not dispatch actions. The fix for that was found [here ](https://github.com/gatsbyjs/gatsby/issues/25478#issuecomment-653207216) (bump gatsby to 2.23.18) which resolved this warning for me as well.

**Comment by ryparker** [comment]
@alchi126 That worked. Thanks!
