### ISSUE TITLE
[Docs] GraphQL Reference - 502 Bad Gateway

### ISSUE THREAD

**Issue by polarathene** [gatsbyjs/gatsby#25517]
https://www.gatsbyjs.org/docs/graphql-reference/

All the embeds on this page are black boxes with the error message:
```
502:Bad Gateway
We had trouble connecting to the server, try restarting it or check the logs to see what happened.
```

Scrolling down, some are just blank(big white gap between, presumably embed belongs there), one embed was is stuck on "Initializing Sandbox Container", and the last one on the page was initializing, but then after sorting out all it's modules, presented the 502 error message as well, so perhaps the error is unrelated to this page specifically.

**Comment by LekoArts** [comment]
Hi, thanks for the note! We're aware of this problem but nothing we can do on our side. I'm in contact with the codesandbox team to get it resolved :)
