### ISSUE TITLE
gatsby-cloud-staging should point to Gatsbyjs org stage?

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#25510]
## Description

Since some days there is an "gatsby-cloud-staging" bot running. but i expect the gatsby www site should be in the stage and not the GatsbyGram

### Steps to reproduce

- open pull requests
- look for gatsby-cloud-staging bot comments:

> Your pull request can be previewed in Gatsby Cloud: [build-7fc27aa0-17af-4d22-a96b-444e8261e2ba.staging-previews.gtsb.io](https://build-7fc27aa0-17af-4d22-a96b-444e8261e2ba.staging-previews.gtsb.io)

https://github.com/gatsbyjs/gatsby/pull/25490#issuecomment-653309532

### Expected result

to see the staging of www.gatsbyjs.org

### Actual result

GatsbyGram

https://build-76c0f1ce-06a5-4f79-87ae-666029736d8a.staging-previews.gtsb.io/

**Comment by LekoArts** [comment]
You can ignore this for now, it's just a temporary stage/test.

**Comment by muescha** [comment]
it still running?
