### ISSUE TITLE
Some pages redirect to HOME but only in production build

### ISSUE THREAD

**Issue by acidjunk** [gatsbyjs/gatsby#25515]
## Description

In the local dev server I can navigate to all pages and reload them : the app stays on the same page

When deploying the production build: some page load fine: other pages will redirect to home when you reload them or try to load them from the URL. I'm quite new to gatsby but as the production build doesn't have errors, and the console.log on production is completely blanco I find it very hard to debug what actually could be wrong here.

### Steps to reproduce

With the local dev server it all works fine.

After deploy:

https://blog.improviser.education/blogs/improvising-over-major-blues => redirects to https://blog.improviser.education

but

https://blog.improviser.education/team/rene-dohmen => loads ok

### Expected result

If a page loads ok in dev mode : the routes should also be ok on prod, or some build warnings/errors would be visible.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
  Languages:
    Python: 3.7.6 - /Users/acidjunk/opt/anaconda3/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 73.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: 2.22.20 => 2.22.20
    gatsby-plugin-manifest: ^2.4.12 => 2.4.17
    gatsby-plugin-mdx: ^1.2.18 => 1.2.22
    gatsby-plugin-offline: ^3.2.11 => 3.2.16
    gatsby-plugin-react-helmet: 3.3.3 => 3.3.3
    gatsby-plugin-remove-serviceworker: 1.0.0 => 1.0.0
    gatsby-plugin-sharp: ^2.6.12 => 2.6.17
    gatsby-plugin-stylus: 2.3.3 => 2.3.3
    gatsby-remark-images: ^3.3.11 => 3.3.17
    gatsby-source-apiserver: ^2.1.6 => 2.1.6
    gatsby-source-filesystem: 2.3.10 => 2.3.10
    gatsby-transformer-remark: 2.8.14 => 2.8.14
    gatsby-transformer-sharp: ^2.5.5 => 2.5.10
  npmGlobalPackages:
    gatsby: 2.23.4
```

A public repo can be found here:

https://github.com/acidjunk/improviser-blog-test

**Comment by pieh** [comment]
Did you by any chance configure CloudFront as SPA (meaning that all "html" requests would serve `./index.html`)? It feels like it, and this is wrong configuration for Gatsby

It seems to me that it's service worker (`gatsby-plugin-offline`) will sometimes allow to refresh and get cached resources (this is where you can navigate to a page). I'm saying that because when I visited the second link I also landed on home page. I could get this to work eventually when resources started being cached).

**Comment by acidjunk** [comment]
Yes I think it's configured as a SPA. And indeed with a fresh, private tab the https://blog.improviser.education/team/rene-dohmen redirected me to home page; which I didn't notice before (probably due to the offline functionality/side effect from service worker).

Thanks for the pointer into the right direction. Also did some reading on https://gist.github.com/bradwestfall/b5b0e450015dbc9b4e56e5f398df48ff#file-s3-static-sites-md and the docs on https://www.gatsbyjs.org/docs/deploying-to-s3-cloudfront/ contained helpful stuff.
(with fresh browser, and after changes in S3 bucket + Cloudfront config: it works now.

Thanks again !
