### ISSUE TITLE
Gatsby build: 'WebpackError: TypeError: Cannot read property 'length' of undefined'

### ISSUE THREAD

**Issue by TatianaKat** [gatsbyjs/gatsby#25511]
## Description

When trying to use `gatsby build` to prepare my site for deployment, I receive an error:

`WebpackError: TypeError: Cannot read property 'length' of undefined`

### Steps to reproduce

You can check the code for the offending page right here:
[https://pastebin.com/Mh0mde1S](https://pastebin.com/Mh0mde1S)

### Expected result

I assume it should finish building! The cookies seem to be working just fine in the actual app when testing locally. I'm still somewhat new to React/Gatsby in general, so it's possible I did something wrong here, but I couldn't find an obvious solution through Google.

### Actual result

```
failed Building static HTML for pages - 1.041s

 ERROR #95313 

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  44 | }
  45 | 
> 46 | if (cookies.get('userName').length !== 0) {
     |                             ^
  47 |   return (
  48 |     <Layout>
  49 |     <div className="mainContainer">


  WebpackError: TypeError: Cannot read property 'length' of undefined

  - index.js:46 
    src/pages/index.js:46:29
```
### Environment

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor         
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12 
    gatsby-image: ^2.4.9 => 2.4.9 
    gatsby-plugin-manifest: ^2.4.14 => 2.4.14 
    gatsby-plugin-offline: ^3.2.13 => 3.2.13 
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.6 
    gatsby-plugin-sharp: ^2.6.14 => 2.6.14 
    gatsby-source-filesystem: ^2.3.14 => 2.3.14 
    gatsby-transformer-sharp: ^2.5.7 => 2.5.7 
  npmGlobalPackages:
    gatsby-cli: 2.12.58
```

**Comment by TatianaKat** [comment]
I fixed it. It was me being a dummy. I learned how to use useEffect instead and it sorted the problem out.

**Comment by WhySoBad** [comment]
Hello @TatianaKat 
I have a very similar error.
Can you may tell a bit more detailed how you fixed it?

Thanks!
