### ISSUE TITLE
--prefix-paths flag is always enabled

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#2551]
Setting a `pathPrefix` in `gatsby-config.js` will cause `gatsby build` to use that path prefix in all production builds - i.e.`gatsby build` and `gatsby build --prefix-paths` produce the same output.

This means that sites built with `gatsby build` will have broken navigation and trigger errors in the browser console.

![screen shot 2017-10-20 at 12 15 08](https://user-images.githubusercontent.com/381801/31818506-5ead19ba-b590-11e7-87d4-ce4316fa3981.png)

It looks like this is caused by [an unexpected value in the equality check in `loader.js`](https://github.com/gatsbyjs/gatsby/blob/38149a23a87cb91e0c6047cba2e20eb533da97b5/packages/gatsby/cache-dir/loader.js#L113). `__PREFIX_PATHS__` is a `ReferenceError` instead of `undefined`.  This causes the `pathPrefix` to be used, resulting in Gatsby being unable to match window paths with its own list of paths. 

I'm a bit hazy on the precise differences between a ReferenceError and undefined, but hopefully this is enough info for someone to track down the problem.

![screen shot 2017-10-20 at 12 06 20](https://user-images.githubusercontent.com/381801/31818537-75f6ae7e-b590-11e7-8926-5d3201acf061.png)

I've created an example repo (based on gatsby's default starter) that demonstrates the problem at https://github.com/m-allanson/gatsby-path-prefix-test

**Comment by vieckys** [comment]
I am also getting this same issue. Anyone has a fix ?

**Comment by m-allanson** [comment]
@vieckys this should have been fixed a while ago. Are you using a recent version of Gatsby?

**Comment by vieckys** [comment]
hmm it may be 2 - 3 months old.

**Comment by m-allanson** [comment]
Ok I’d try updating to a newer version
