### ISSUE TITLE
Gatsby Build Failed : The System can not find the path specified

### ISSUE THREAD

**Issue by siddhpurakaran** [gatsbyjs/gatsby#25536]
## Description

When i am building gatsby app it is failing with following error.
The system can not find the path specified.

### Steps to reproduce

This is a project which i forked.
Repo link : https://github.com/bchiang7/v4

I also opened same issue on that repo.
https://github.com/bchiang7/v4/issues/79

### Expected result

Build should success. 

### Actual result

Build failed with this error.
WorkerError: Processing D:/Project/Site/personal-web-master/personal-web-master/content/about/image/me.jpg failed
  Original error:
  The system cannot find the path specified.
### Environment

  System:
    OS: Windows 10 10.0.17134
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  Binaries:
    Node: 10.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.18.7 => 2.23.20 
    gatsby-image: ^2.4.12 => 2.4.12 
    gatsby-plugin-google-analytics: ^2.1.29 => 2.3.10 
    gatsby-plugin-manifest: ^2.2.31 => 2.4.17 
    gatsby-plugin-netlify: ^2.1.27 => 2.3.10 
    gatsby-plugin-offline: ^3.0.27 => 3.2.16 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.3.9 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.1 
    gatsby-plugin-sharp: ^2.6.17 => 2.6.17 
    gatsby-plugin-sitemap: ^2.2.22 => 2.4.10 
    gatsby-plugin-styled-components: ^3.1.14 => 3.3.9 
    gatsby-remark-code-titles: ^1.1.0 => 1.1.0 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-images: ^3.3.17 => 3.3.17 
    gatsby-remark-prismjs: ^3.3.25 => 3.5.9 
    gatsby-source-filesystem: ^2.3.18 => 2.3.18 
    gatsby-transformer-remark: ^2.8.23 => 2.8.23 
    gatsby-transformer-sharp: ^2.5.10 => 2.5.10 
  npmGlobalPackages:
    gatsby-cli: 2.12.58

**Comment by LekoArts** [comment]
Thank you for opening this!

We're not maintaining this starter so please refer to their issue board. On a first glance the image is simply not at the destination the project is looking for, e.g. the image is at the path `content/about/me.jpg` when I look into the repo.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
