### ISSUE TITLE
[gatsby-plugin-mdx] timeToRead is wrong for Chinese/Japanese texts

### ISSUE THREAD

**Issue by maekawataiki** [gatsbyjs/gatsby#25532]
## Summary

There is a great PR handling `timeToRead` for Chinese/Japanese input in PR #21312 on `gatsby-transformer-remark`.
However, this PR does not support mdx.
It would be great `gatsby-plugin-mdx` handle Chines/Japanese similarly.

### Basic Example

An example similar to #21311, but using starter with mdx.

### Motivation

This feature provides more accurate `timeToRead` field for Chinese/Japanese body for project using mdx.

**Comment by maekawataiki** [comment]
Waiting for review. Not stale.

**Comment by KyleAMathews** [comment]
A PR adding support to transformer-mdx would be great!

**Comment by maekawataiki** [comment]
This issue is not stale.
There is PR #25533 making a change to `gatsby-plugin-mdx` which solves the issue.
Waiting for review by the maintainer.

**Comment by minimalsm** [comment]
@KyleAMathews @LekoArts can we reopen or will I create a new issue?
