### ISSUE TITLE
Wrong links in gatsby-transformer-orga

### ISSUE THREAD

**Issue by kepi** [gatsbyjs/gatsby#25541]
## Summary

Links on https://www.gatsbyjs.org/packages/gatsby-transformer-orga/ targets 404 as package moved to organization repository.

It looks like that README is already fixed and showing OK on https://www.npmjs.com/package/gatsby-transformer-orga

### Motivation

Because people can't find documentation right now.

## Steps to resolve this issue

Update documentation for package from its README?

**Comment by Escavalier** [comment]
i am not able to find the place where the code needs to be fixed

**Comment by LekoArts** [comment]
Thank you for opening this!

The READMEs are sourced from Algolia:

https://github.com/gatsbyjs/gatsby/blob/b5926cc5fc73336af0a3ef499859ced22ebf56da/www/gatsby-config.js#L94-L104

Therefore the results (cache) from Algolia needs to update itself and the website needs to be rebuilt. The latter happens often, the former is a matter of time. It should get updated eventually, in the meantime there is nothing to speed up that process.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
