### ISSUE TITLE
build fail while using createBrowserHistory from History (package come with react-router-dom)

### ISSUE THREAD

**Issue by stanleyyuenyiu** [gatsbyjs/gatsby#25544]
Any component include  package"history" (from react-router-dom)  + {Link, Router, useParams} from "@reach/router" together ,  will output "ERROR #95313 , WebpackError: Invariant failed..."  when run build, but it will be fine when run develop

the error is throw by :
WebpackError: Invariant failed
    - tiny-invariant.esm.js:8 
    node_modules/tiny-invariant/dist/tiny-invariant.esm.js:8:1
  
  - history.js:251 
    node_modules/history/esm/history.js:251:115
  
  - app.js:10 
    src/pages/app.js:10:38
  
  - history.js:13 
    node_modules/history/esm/history.js:13:1

it look like history is not go right with reach/router

plz do not ask me why i need to use react-router-dom ^5.2.0 while there is a reach/router, because i need to use the history API to replace the url path silently, without any render/redirect, which reach-router not support 

Here is the code that trigger error when build: 

import React from "react"
import { createBrowserHistory } from 'history';  
import {Link, Router, useParams} from "@reach/router"

const Layout = ({ children }) => {
  const history = createBrowserHistory();
  return (
    <>
        <div className="container">
        {children}
      </div>
    </>
  )
}

**Comment by stanleyyuenyiu** [comment]
it look like createBrowserHistory need window object, as the advice from https://www.gatsbyjs.org/docs/debugging-html-builds/, better to move it into did mount process

however it doesnt explain why it work without reach/router

**Comment by pieh** [comment]
> however it doesnt explain why it work without reach/router

Did you try this in any server-side rendering? It feels like this is just SSR problem and it's not related to `reach/router`?

**Comment by pieh** [comment]
> i need to use the history API to replace the url path silently

You can replace current url using `navigate(`somelink`, { replace: true })`, but it might cause re-renders.

Can you expand on what you are trying to do exactly and why you don't want to use `navigate` function - I feat that using `history` outside of navigation might have weird interactions that can break in future etc, and I would really try not to use it unless you absolutely must

**Comment by stanleyyuenyiu** [comment]
@pieh let say you are generating the page with multi-language (if it is not pre-generating, it has no issue) , 
/cz/abc-page/index.html, /en/abc-page/index.html, 

when you switch the language, you will force to re-render the page
 (which will also re-call some function, event put it into did mount cycle), 

therefore, i just wanna to switch the url silently 

and in case the user refresh the browser , 
he can stay to where ever he up to

**Comment by freiksenet** [comment]
You can try recording what page you are moving to and handling this with component state instead of navigation. I don't think this is achievable without a reload otherwise. I don't think using browser history will make it work properly too - I feel there would be too many complex side effects involved. You could also try detecting what kind of change it is inside cDM cycle and not trigger if it's not a full reload (eg by passing state to navigate).

Unfortunately we don't feel it's a common use case and we won't be implementing it inside Gatsby. I hope the advice above helps. I'll be closing this issue in the meantime.
