### ISSUE TITLE
Filesystem with Remark plugin not hot reloading.

### ISSUE THREAD

**Issue by fusepilot** [gatsbyjs/gatsby#2555]
Repro: https://github.com/fusepilot/gatsby-filesystem-remark-repro

Expected: When editing the contents of `contents/docA.md`, I expected to see the page at `http://localhost:8000/docA` hot update to reflect the new content.

Observed: The page at `http://localhost:8000/docA` does not update unless manually refreshed.

**Comment by KyleAMathews** [comment]
Thanks for reporting this! I saw this last night as well so good to have a second confirmation of the problem.

Will look into what broke soon.

**Comment by KyleAMathews** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/2563 Upgrade and things should be fixed.

**Comment by daaain** [comment]
I have a same issue with a website derived from starter-blog and I can't for my life figure out why is it happening 😿

I made sure to merge in the latest changes, purged `node_modules` and `.cache`, but no dice. It seems the JSON files in `.cache` don't get updated on changes, despite Webpack successfully picking up the filesystem change and triggering HMR in the browser. It just doesn't show any files changed in the console and doesn't update the content...

I'm at my wit's end, please have a look! Or please point me to a more appropriate place to ask this sort of question.

The repo is over here: https://github.com/movementkitchen/website

Thanks a lot!

**Comment by KyleAMathews** [comment]
Could you try upgrading your sites packages?

**Comment by daaain** [comment]
@KyleAMathews sorry I'm a bit slow today, do you mean the NPM packages?

**Comment by KyleAMathews** [comment]
Yes

**Comment by daaain** [comment]
Thanks!

Same issue 😿

It was only a few inconsequential packages though:

```
$ npm outdated
Package                     Current   Wanted  Latest  Location
gatsby-plugin-react-helmet    1.0.8    1.0.8   2.0.3  movement-kitchen
typeface-amatic-sc           0.0.43   0.0.43  0.0.45  movement-kitchen
typeface-work-sans           0.0.43   0.0.43  0.0.44  movement-kitchen
typography                  0.15.12  0.15.12  0.16.6  movement-kitchen
```
