### ISSUE TITLE
gatsby develop freezes on Windows 10

### ISSUE THREAD

**Issue by gateixeira** [gatsbyjs/gatsby#25552]
## Description

Development mode is not started on a gatsby-based documentation, built with `gatsby-theme-carbon`:
https://github.com/IBM/transparent-supply-documentation

`gatsby develop` freezes on Windows 10 on "Build manifest and related icons". A Chrome debug apparently shows what seems an infinite loop in the `gatsby-plugin-manifest`:

![image](https://user-images.githubusercontent.com/4645845/86615229-753a6080-bfb4-11ea-827c-3a6525a0a3f5.png)

![image](https://user-images.githubusercontent.com/4645845/86614047-b5004880-bfb2-11ea-8c2e-53b1c592c5e6.png)

### Steps to reproduce

- clone repo
- run `npm install`
- run `npm start`

### Expected result

Dev mode should start

### Actual result

CLI hangs on "Build manifest and related icons"

What happened.

### Environment

Windows 10
npm version: 6.14.5
node version: 14.5.0 (tried on 12 as well)
gatsby version: 2.21.36

**Comment by vladar** [comment]
I couldn't reproduce this on my Windows 10 machine. Probably something environment-specific. Have you tried downgrading to older versions of gatsby? We need to bisect this somehow to figure out what could have caused this.

Also weird that you have some output after terminating - looks like two gatsby versions were started somehow.

**Comment by gateixeira** [comment]
@vladar thanks for looking into it.

I will try to downgrade. Any specific version I should look for?

**Comment by vladar** [comment]
I think it makes sense to bisect minor versions the way you would do with binary search.

Start with `2.10.x` then `2.16.x` (if `2.10.x` works), etc. until you narrow the range where it breaks. I could have done this myself but as I said I couldn't reproduce this locally (sadly).

**Comment by gateixeira** [comment]
Just getting back to you to say that I managed to make it work with version 2.15.x. Sorry for the delay, the windows laptop is not my own. Closing the issue.

**Comment by derykmarl** [comment]
Still getting that issue here.   I very frequently have to ctrl-c and start the build process again, and then it goes through
