### ISSUE TITLE
in website’s local 'plugins' folder, onCreateNode is not called everytime a new node is created

### ISSUE THREAD

**Issue by anisg** [gatsbyjs/gatsby#25553]
## Description

I was following the source plugin tutorial ([here](https://www.gatsbyjs.org/tutorial/source-plugin-tutorial/)).

I noticed that when my plugin is in this 'plugins' folder, onCreateNode wasn't called everytime a new node was created. if I move my plugin to another place and use 'require.resolve', it works as it's suppose to.

### Steps to reproduce

1. download the example folder from the tutorial: https://github.com/gatsbyjs/gatsby/tree/master/examples/creating-source-plugins
2. in `./source-plugin/gatsby-node.js`, in the OnCreateNode function: add the code `console.log('onCreateNode!', node.internal.type)` to see if this function is called and for which type of nodes.
3. `mv ./source-plugin ./example-site/plugins`
4. `gatsby develop`

### Expected result

onCreateNode should be called 10+ times, and especially for some nodes of type `Post` and `Author`.

### Actual result

onCreateNode is called 5 times, with all nodes of type `SitePage`

### Environment
```
  System:
    OS: Linux 4.19 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /c/Program Files (x86)/Yarn/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12
    gatsby-image: ^2.4.9 => 2.4.9
    gatsby-plugin-manifest: ^2.4.14 => 2.4.14
    gatsby-plugin-offline: ^3.2.13 => 3.2.13
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.6
    gatsby-plugin-sharp: ^2.6.18 => 2.6.18
    gatsby-source-filesystem: ^2.3.14 => 2.3.14
    gatsby-transformer-sharp: ^2.5.10 => 2.5.10
```

**Comment by pieh** [comment]
`onCreateNode ` won't be called if the `node` was created in previous run and it didn't change. Can you try running `gatsby clean` and restarting (without `require.resolve` approach - just local plugin, and referenced by `source-plugin` in gatsby-config)?

Changing gatsby-config to use `require.resolve` forces gatsby to clean cache under the hood, moving plugin around doesn't (it's still same config)

**Comment by pieh** [comment]
Also - you should not rely on `onCreateNode` to be called on each run - there is no guarantee that it will - it will only run if new node is created or cached node is updated with some change (`contentDigest` for given node id changes)

**Comment by anisg** [comment]
Yes I didn't understood that onCreateNode wasn't always called on each run. Thanks for the help!
