### ISSUE TITLE
gatsby-transformer-sharp isn't working with MDX

### ISSUE THREAD

**Issue by DaTurboD** [gatsbyjs/gatsby#25559]
## Description

I am trying to query images through the frontmatter of mdx-files like 
```
frontmatter {
            layout
            title
            description
            category
            image {
              publicURL
              childImageSharp {
                sizes(
                  maxWidth: 2000
                  traceSVG: { color: "#639" }
                ) {
                  ...GatsbyImageSharpSizes_tracedSVG
                }
              }
            }
```

But i get following error:
```
There was an error in your GraphQL query:

Field "image" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" make sure that your input source and/or plugin is correct.
```
### Steps to reproduce

This is how my gatsby-config.js looks like:
```js
... 
module.exports = {
  siteMetadata: {
    title: config.siteTitle,
    description: config.siteDescription,
    author: config.userName,
    siteUrl: urljoin(config.siteUrl, config.pathPrefix),
    rssMetadata: {
      site_url: urljoin(config.siteUrl, config.pathPrefix),
      feed_url: urljoin(config.siteUrl, config.pathPrefix, config.siteRss),
      title: config.siteTitle,
      description: config.siteDescription,
      image_url: `${urljoin(
        config.siteUrl,
        config.pathPrefix
      )}/logos/logo-square-512.png`,
      copyright: config.copyright
    }
  },
  plugins: [
    `gatsby-transformer-yaml`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-lodash`,
    `gatsby-plugin-netlify-cms`,
    `gatsby-plugin-styled-components`,
    `gatsby-transformer-json`,
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        extensions: [`.mdx`, `.md`],
        gatsbyRemarkPlugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 590,
            },
          },
          {
            resolve: `gatsby-remark-prismjs`,
            options: {
              classPrefix: "language-",
              inlineCodeMarker: null,
              aliases: {},
              showLineNumbers: false,
              noInlineHighlight: false,
            }
          },
        ],
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 590,
            },
          },
        ],
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/static/assets/img`,
...
```

Frontmatter looks like this
```md
...
image: "/assets/img/was-ist-ein-geoinformationssystem.jpg"
...
```
### Expected result

Images should be able to be queried with childImageSharp

### Actual result

```
There was an error in your GraphQL query:

Field "image" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" make sure that your input source and/or plugin is correct.
```

### Environment

System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz
  Binaries:
    Node: 10.16.0 - ~\AppData\Local\Temp\yarn--1594067792534-0.6077076286175209\node.CMD
    Yarn: 1.21.1 - ~\AppData\Local\Temp\yarn--1594067792534-0.6077076286175209\yarn.CMD
    npm: 6.14.5 - V:\Websites\GIS-Netzwerk\node_modules\.bin\npm.CMD
  Languages:
    Python: 3.7.4
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.12 => 2.23.20
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.4.12 => 2.4.12
    gatsby-plugin-catch-links: ^2.1.25 => 2.3.10
    gatsby-plugin-feed-mdx: ^1.0.1 => 1.0.1
    gatsby-plugin-gdpr-cookies: ^1.0.6 => 1.0.7
    gatsby-plugin-guess-js: ^1.1.30 => 1.3.10
    gatsby-plugin-lodash: ^3.1.20 => 3.3.9
    gatsby-plugin-mailchimp: ^5.1.2 => 5.2.2
    gatsby-plugin-manifest: ^2.2.20 => 2.4.17
    gatsby-plugin-matomo: ^0.8.3 => 0.8.3
    gatsby-plugin-mdx: ^1.2.16 => 1.2.22
    gatsby-plugin-netlify-cms: ^4.1.25 => 4.3.10
    gatsby-plugin-nprogress: ^2.1.19 => 2.3.9
    gatsby-plugin-offline: ^3.0.11 => 3.2.16
    gatsby-plugin-react-helmet: ^3.1.10 => 3.3.9
    gatsby-plugin-react-leaflet: ^2.0.13 => 2.0.13
    gatsby-plugin-sass: ^2.1.29 => 2.3.10
    gatsby-plugin-sharp: ^2.6.18 => 2.6.18
    gatsby-plugin-sitemap: ^2.2.27 => 2.4.10
    gatsby-plugin-styled-components: ^3.1.8 => 3.3.9
    gatsby-remark-autolink-headers: ^2.1.24 => 2.3.10
    gatsby-remark-images: ^3.3.17 => 3.3.17
    gatsby-remark-lazy-load: ^1.0.2 => 1.0.2
    gatsby-remark-prismjs: ^3.5.4 => 3.5.9
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-source-filesystem: ^2.0.28 => 2.3.18
    gatsby-source-instagram-all: ^2.0.5 => 2.0.5
    gatsby-transformer-json: ^2.1.11 => 2.4.10
    gatsby-transformer-remark: ^2.6.27 => 2.8.23
    gatsby-transformer-sharp: ^2.5.10 => 2.5.10
    gatsby-transformer-yaml: ^2.2.25 => 2.4.9
  npmGlobalPackages:
    gatsby-cli: 2.12.45

**Comment by DaTurboD** [comment]
Figured it out. Problem were the relative paths to the images.

**Comment by muhammedMoussa** [comment]
the same issue was here related to relative paths, and fixed by clear cash ` rm -rf .cache`
