### ISSUE TITLE
New projects created with gatsby-cli have 655 security vulnerabilities (low severity) 

### ISSUE THREAD

**Issue by jarodtaylor** [gatsbyjs/gatsby#25589]
## Description

Just installed gatsby-cli (v2.12.58) on a new MBP and when I run `gatsby new` I get 655 low severity security vulnerabilities from npm. They're all due to `lodash` and prototype pollution in various gatsby plugin files. 

I'm obviously not going to paste all 655 but here are the last few:

![image](https://user-images.githubusercontent.com/362248/86865123-0af8ed00-c094-11ea-949b-d40c8304761b.png)

### Steps to reproduce

Run `gatsby new project_name`

### Environment

  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12
    gatsby-image: ^2.4.9 => 2.4.9
    gatsby-plugin-manifest: ^2.4.14 => 2.4.14
    gatsby-plugin-offline: ^3.2.13 => 3.2.13
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.6
    gatsby-plugin-sharp: ^2.6.14 => 2.6.14
    gatsby-source-filesystem: ^2.3.14 => 2.3.14
    gatsby-transformer-sharp: ^2.5.7 => 2.5.7
  npmGlobalPackages:
    gatsby-cli: 2.12.58

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll need to have to wait for lodash to release a patch release. Once that's out you'll automatically get that new release (we don't pin versions). Nothing much we can do on our end, it's expected that when a wide-used library like lodash has an advisory you'll see a lot of warnings. Shouldn't take too long though as they know that themselves.
