### ISSUE TITLE
bug(docs, www): GraphQL embeds are broken

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#25590]
## Description

The GraphQL embeds in doc pages like the [GraphQL Refrence](https://www.gatsbyjs.org/docs/graphql-reference/) do not load.

### Repro steps

1. Go to a page with GraphQL embeds in the docs (e.g. https://www.gatsbyjs.org/docs/graphql-reference/)

### Expected result

The graphql embed displays a GraphiQL link.

### Actual result

Nothing is shown:

<img width="654" alt="A screenshot of the page url above showing an empty spot where an embed should be" src="https://user-images.githubusercontent.com/1278991/86868928-7b9b0c00-c08a-11ea-80ee-d1e46a8baea2.png">

## Notes

* Going to some of the actual codesandbox seems to be fine? https://q4xpb.sse.codesandbox.io/___graphql

**Comment by LekoArts** [comment]
This is an intermittent issue with codesandbox and sometimes occurs. For example yesterday it worked fine and tomorrow it'll be fine again. There is nothing on our end what we could do to solve this.
