### ISSUE TITLE
How to get all the ipynb files inside a git repo?

### ISSUE THREAD

**Issue by jugshaurya** [gatsbyjs/gatsby#25599]
## Summary
Use case: I want to use gatsby to pull all the jupyter notebooks in my GitHub repo and read all the content of it and show as a blog. Can someone help How to get that? I was trying to use gatsby-source-git and @gatsby-contrib/gatsby-transformer-ipynb, but not able to get every file inside subdirectories and it's content. only getting the top level 3 .ipynb files.

## Relevant information
- Plugins:
![help1](https://user-images.githubusercontent.com/39825643/86606930-4200cd00-bfc6-11ea-86ed-3d7c051caa6e.png)

Just getting these 3 files although MY repo contained more that 50 jupyter notebooks.
My repo: https://github.com/jugshaurya/Machine-Learning
![help2](https://user-images.githubusercontent.com/39825643/86607027-665ca980-bfc6-11ea-8e17-d8b1eeece994.png)

**Comment by jugshaurya** [comment]
@pieh please help

**Comment by LekoArts** [comment]
Thank you for opening this!

Please don't ping people, especially if you just created your issue a minute before that. That's rude.

As we don't maintain said plugins please open an issue on their repository, you probably want to open one here:
https://github.com/stevetweeddale/gatsby-source-git

Only getting the top 3 level will be a limitation or setting in this plugin.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by jugshaurya** [comment]
ok. Thank you.
> Please don't ping people, especially if you just created your issue a minute before that. That's rude. 

sorry for that.

By the way, got it resolved after writing my own custom transformer-plugin to convert Jupyter notebook to Html. Thanks to notebooks
