### ISSUE TITLE
gatsby build deletes all html files

### ISSUE THREAD

**Issue by singuerinc** [gatsbyjs/gatsby#2559]
I have a bunch of examples in my blog, small index.html files with a bit of js.
I put them in a folder inside the `static` folder.

If I run `gatsby develop` everything works well, but I soon as I run `gatsby build` every html file is deleted because https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/index.js#L64

And that's seems to be the correct behavior, so my question is: How you handle this situation?

I tried to use the `onPostBuild` function and that works ok with `gatsby build`, but not with `gatsby develop`, so I'm not entirely sure how to solve that.

Any idea?

**Comment by KyleAMathews** [comment]
Oh, hmmm does this happen? The solution would be then to copy stuff from the static folder *after* we delete the HTML files in `public`. Could you create a PR doing this?

**Comment by singuerinc** [comment]
What about excluding `public/static/**/*.html` from https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/index.js#L64 ?

**Comment by KyleAMathews** [comment]
👍  that'd work too

**Comment by singuerinc** [comment]
I don't have time right now but I will create a PR asap. Thanks!

**Comment by singuerinc** [comment]
Done: https://github.com/gatsbyjs/gatsby/pull/2569

**Comment by singuerinc** [comment]
Unfortunately the fix didn't work as expected, it is still removing the files.

Looking into the readme of "del" I saw:
https://www.npmjs.com/package/del#beware

So, that was the cause why it didn't work before.

I created a new PR that should fix it properly:
https://github.com/gatsbyjs/gatsby/pull/2600

Thanks!

**Comment by singuerinc** [comment]
I works now!
