### ISSUE TITLE
gatsby new in current directory

### ISSUE THREAD

**Issue by adjohnson916** [gatsbyjs/gatsby#256]
It's be great to support `gatsby new` in current directory. I don't like to install npm modules globally (instead I have `./node_modules/.bin` in my path). So I tend to create project directory, then install gatsby locally, then finally want to start a new site in that directory.

**Comment by KyleAMathews** [comment]
It'd probably be simplest then to just git clone the starter then.

**Comment by MoOx** [comment]
Phenomic use this approach and only work in a local way. Our "one line" install/setup is pretty long, but works copy pasted https://github.com/MoOx/phenomic/issues/416

**Comment by dmitriyaa** [comment]
Hey guys, here is what I'm doing: 
```
cd project dir
gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
mv ./hello-world/*(DN) ./
rm -d hello-world
```
what do you think? 🤔 
p.s.
I'm using zsh for mv command

**Comment by bashleigh** [comment]
rm -rf .git && gatsby-cli new . https://github.com/gatsbyjs/gatsby-starter-hello-world
