### ISSUE TITLE
 is not possible to consume React context (useContext) within /pages ?

### ISSUE THREAD

**Issue by exocode** [gatsbyjs/gatsby#25616]
I've a question regarding Context API:

I have a page which consists of Layout, which is splitted in Sidebar, Navigation, Footer... .
I've set up a Context to show and hide some stuff (in my case a share area). 

I have a file within `/pages` folder and wanna consume that context which was clicked in the layout area, but it is not changing in the `pages`. 

Here is my example: It simply toggles true false if somewhere in Layout/Footer/Navigation
´/context/ShareContext.js´

```jsx
import React, { createContext } from "react"
const defaultState = {
  collapsedShare: false,
  toggleShare: () => {},
}
const ShareContext = createContext(defaultState)
const ShareContextProvider = props => {
  const [collapsedShare, setCollapsedShare] = useState(false)
  const toggleShare = () => setCollapsedShare(!collapsedShare)

  return (
    <ShareContext.Provider value={{ collapsedShare, toggleShare: toggleShare }}>
      {props.children}
    </ShareContext.Provider>
  )
}

export { ShareContextProvider, ShareContext }
```

`/src/layout`

```jsx
import React from "react"

import { ShareContextProvider } from "../context/ShareContext"
const Layout = props => {
  const [collapsed, setCollapsed] = useState(true)
  const toggleNav = () => setCollapsed(!collapsed)
  return <ShareContextProvider>
                 <Sidebar/>
                 <Button onClick={toggleShare} > Button Text </Button>
                 <Footer/>
              </ShareContextProvider>
```

`/pages/home.js` (where I wanna consume)

```jsx
import React, { useContext } from "react"
import Layout from "../components/layout"
import { ShareContext } from "../context/ShareContext"

const IndexPage = props => {
  const { collapsedShare, toggleShare } = useContext(ShareContext)
  console.log(collapsedShare)
  return (
    <Layout>
      <div id="wrapper">
        Some content and my context to consume
         {String(collapsedShare)} <<<<<<----------- is always "false" (never changes)
      </div>
    </Layout>
  )
}
```

Do I have a wrong understanding how Gatsby works or is this not possible to do with Gatsby

**Comment by herecydev** [comment]
I've made this work so it's definitely possible. Can you put together a repo so I can better see what you're attempting?

**Comment by exocode** [comment]
@herecydev 

> I've made this work so it's definitely possible. Can you put together a repo so I can better see what you're attempting?

I made here a repo to point out this problem. Very simplified, but shows the issue: 

https://github.com/exocode/gatsby-context-problem

**Comment by herecydev** [comment]
Hey your example isn't very simple to follow, but a quick glance shows the component tree looks like:

![image](https://user-images.githubusercontent.com/11328618/87064227-51228d80-c207-11ea-8337-c6b6eb30fc5d.png)

**Comment by graysonhicks** [comment]
Yea, I think there is a lot happening under the hood that makes this difficult to explain/visualize, but here is your sandbox forked with it fixed by moving the Context consumer to a _child_ of the Index page instead of in the Index page itself:

https://codesandbox.io/s/admiring-hooks-lzxb4?file=/src/pages/index.js

The relevant part:
```javascript
import React, { useContext } from "react"
import Layout from "../components/layout"
import { ShareContext } from "../context/ShareContext"

// Move this to it's own component consuming context.
const IndexContent = () => {
  const { collapsedShare, toggleShare } = useContext(ShareContext)
  return (
    <>
      <p>collapsedShare in index page is {String(collapsedShare)} </p>
      <button onClick={toggleShare}>
        I am in the page: Click me to change
      </button>
    </>
  )
}

const IndexPage = () => {
  // Consuming the context here lifts it above the Layout, and therefore above
  // the context provider.
  return (
    <Layout>
      <h3>
        I am the page where a context should update, when it's set outside
      </h3>
      <IndexContent />
    </Layout>
  )
}

export default IndexPage

```

**Comment by herecydev** [comment]
Yer because previously you were using the context that was declared at the "index page level", where layout is now responsible for rendering the `IndexContent` component. This will then have a context that's "somewhere beneath the layout".

It's really hard to articulate, but hope that helps?

**Comment by pieh** [comment]
Dan summarised it pretty well (I also have no way of articulating it better :) ).

To fix the problem the Provider should be above consumers and you can do this by using https://www.gatsbyjs.org/packages/gatsby-plugin-layout/ and putting Provider there, then you could use it in your page components directly. Alternatively you could use [`wrapRootElement`](https://www.gatsbyjs.org/docs/browser-apis/#wrapRootElement) yourself to do this (just keep in mind you need same thing for `gatsby-ssr` and `gatsby-browser` file as mentioned in the note of the doc I linked to). (but the plugin I linked to just abstract similar API and generally is nicer to use if you don't need additional control there)

**Comment by exocode** [comment]
Interesting! For my point of view is this "magic" of Gatsby (I'm Gatsby noob).
Very nice thank you, have to read through. I will close this now. Thanks again.

**Comment by bobgravity1** [comment]
honestly ridiculous. while people claim gatsby is SO QUICK and easy to set up a website i frankly find these things to be extremely overlooked by their dev team. passing state is like the STAPLE of react and having to set up a plug in use something as essential as context/global state is ridiculous... nuff said. not even up for debate imho


THIS is why front end dev gets so exhausting. learning 80000 ways to do one simple thing

**Comment by graysonhicks** [comment]
@bobgravity1 You can do it without the plugin by wrapping the app with your Provider in gatsby-browser and gatsby-ssr just as you would in any React app, but the plugin just does it for you in less code.

**Comment by bobgravity1** [comment]
i appreciate that. will look into it.

**Comment by jfschaff** [comment]
I may have a similar issue. Here it is. It makes no sense to me, as the code works in React but not in Gatsby.

Here is the code:
https://stackoverflow.com/questions/77262847/using-contexts-in-react-with-gatsby

And a sandbox, which shows how that this exact same code works in React without Gatsby:
https://codesandbox.io/s/hungry-gianmarco-sry9v9?file=/src/Page.tsx

Am I missing something?

**Comment by bobgravity1** [comment]
Use the Gatsby-browser to wrap the context! Hope this helps
