### ISSUE TITLE
Docs are not being shown for gatsby-plugin-sass

### ISSUE THREAD

**Issue by SilencerWeb** [gatsbyjs/gatsby#25628]
## Summary
Is it supposed to be like that? [Link](https://www.gatsbyjs.org/packages/gatsby-plugin-sass/?=sass)

![image](https://user-images.githubusercontent.com/20713191/86987795-4f79ab00-c1b0-11ea-9b27-ea193ce6f14a.png)

**Comment by LekoArts** [comment]
Hi! You can follow this issue here: https://github.com/gatsbyjs/gatsby/issues/24137
