### ISSUE TITLE
Gatsby does not work on IE11

### ISSUE THREAD

**Issue by F5CnS** [gatsbyjs/gatsby#25630]
## Description

I understand that Gatsby supports IE11 by default. However, React totally did not work in one of the pages in my Gatsby app.
The page name is product and when I navigate to that page, the following error can be seen in the console:

```Unhandled promise rejection error, page resources not found for /product. Not rendering React```

So the page was loaded, but javascript did not work at all on that page (onClick event was not triggered,...etc)

### Steps to reproduce

product.js was created under src/pages folder and it included a React component.

1. Build the app with `gatsby build`
2. Run the app with `gatsby serve`
3. Nagivate to http://localhost:8080/product
On Chrome, Safari, it works well. 

### Expected result

Javascript should work on IE 11.

### Actual result

However, on IE 11, when button is clicked, event is not triggered, so no state is updated. The following error was seen in the console:

```Unhandled promise rejection error, page resources not found for /product. Not rendering React```

### Environment

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Edge: 80.0.361.62
    Firefox: 51.0
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.21.37 => 2.21.37
    gatsby-image: ^2.4.4 => 2.4.4
    gatsby-plugin-manifest: ^2.4.5 => 2.4.5
    gatsby-plugin-offline: ^3.2.3 => 3.2.3
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.3.10 => 2.3.10
    gatsby-plugin-sass: ^2.3.3 => 2.3.3
    gatsby-plugin-sharp: ^2.6.4 => 2.6.4
    gatsby-source-filesystem: ^2.3.8 => 2.3.8
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2
  npmGlobalPackages:
    gatsby-cli: 2.12.34

**Comment by cometkim** [comment]
Yes... I've got 38K events from Sentry last 24 hours, after updated gatsby-image to the latest version :\

![image](https://user-images.githubusercontent.com/9696352/87027910-cba7d900-c218-11ea-9784-f2381c151b98.png)

**Comment by wardpeet** [comment]
Is it possible to create a small reproduction? Also please make sure to test IE11 when running `gatsby serve` and not `gatsby develop`

**Comment by cometkim** [comment]
Sure, but I'm not sure the problem I have is the same issue with the original. @F5CnS Do you use gatsby-image? how's your stacktrace?

**Comment by cometkim** [comment]
(FYI, I already resolved the problem by just reverting a dependabot PR and tested in BrowserStack)

**Comment by F5CnS** [comment]
> Sure, but I'm not sure the problem I have is the same issue with the original. @F5CnS Do you use gatsby-image? how's your stacktrace?

I used `gatsby-image`

**Comment by F5CnS** [comment]
> (FYI, I already resolved the problem by just reverting a dependabot PR and tested in BrowserStack)



> Is it possible to create a small reproduction? Also please make sure to test IE11 when running `gatsby serve` and not `gatsby develop`

yes, I tested with production build

**Comment by F5CnS** [comment]
@wardpeet @cometkim 

So I have updated gatsby and fixed the problem IE. The following installations work for me:

System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Edge: 80.0.361.62
    Firefox: 51.0
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.23.12 => 2.24.1
    gatsby-image: ^2.4.9 => 2.4.13
    gatsby-plugin-manifest: ^2.4.14 => 2.4.18
    gatsby-plugin-offline: ^3.2.13 => 3.2.17
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.10
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.3.10 => 2.3.10
    gatsby-plugin-sass: ^2.3.3 => 2.3.3
    gatsby-plugin-sharp: ^2.6.14 => 2.6.19
    gatsby-source-filesystem: ^2.3.14 => 2.3.19
    gatsby-transformer-sharp: ^2.5.7 => 2.5.11

**Comment by pedrofsantoscom** [comment]
In my case I fixed the issue loading polyfill.io lib into the page
```js
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1"></script>
```
