### ISSUE TITLE
Duplicate Viewport When Using gatsby-plugin-react-helmet

### ISSUE THREAD

**Issue by adonig** [gatsbyjs/gatsby#25636]
## Description

Gatsby's html.js already contains a viewport specification:

`<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />`

Thus when you set the viewport with gatsby-plugin-react-helmet, there are two viewport specification.

You can fix this by overriding html.js and adding `data-react-helmet="true"`.

Would it make sense to add this by default so one does not have to override html.js?

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

What we have in `html.js` is considered to be best practice, if you need an escape hatch for edge-cases you can override that file as you already have discovered. Adding the attribute you mentioned wouldn't be the silver bullet as the users then have to use `react-helmet`. There are other packages out there to add that information and also our own API: https://www.gatsbyjs.org/docs/ssr-apis/#onPreRenderHTML (replaceHeadComponents).

**Comment by adonig** [comment]
Hi @LekoArts!

Adding the attribute does not force users to use react-helmet. The data attribute has no meaning as long as they don't use it. It's just like 24 bytes more in the default html template.

Sadly it's not possible to replace the viewport by replacing the head components, because the viewport isn't one of them. The default html template handles those meta-tags separately.

<img width="847" alt="Screen Shot 2020-07-09 at 11 43 07" src="https://user-images.githubusercontent.com/900404/87024514-82846480-c1d9-11ea-81ff-abc7b45994dc.png">

That's why it is necessary to override html.js to remove the duplicate viewport element. While that is certainly not a big thing, wouldn't it still be better to make it work out of the box? :)

Maybe there is a way to detect that users have the helmet plugin and conditionally add the attribute [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/default-html.js)?

**Comment by LekoArts** [comment]
I guess most of our users use `react-helmet`, so yeah, feel free to open a PR changing that.

**Comment by adonig** [comment]
Do you know whether there is a reason for those three head elements being hardcoded in the HTML template instead of being set dynamically using `headComponents`?

```
        <meta charSet="utf-8" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
```

I'm asking because if they were part of `headComponents`, then `gatsby-plugin-react-helmet` could simply use `onPreRenderHTML`'s `replaceHeadComponents` to replace the viewport element with a copy having `data-react-helmet="true"`.
