### ISSUE TITLE
Gatsby develop error: 'pngquant.exe is not recognized as an internal or external command, operable program or batch file.'

### ISSUE THREAD

**Issue by Louisrobertson20** [gatsbyjs/gatsby#25638]
## Description

When running gatsby develop, I get the error: ' 'node_modules\pngquant-  bin\vendor\pndor\pngquant.exe' is not recognized as an internal or external command,  operable program or batch file.'

### Steps to reproduce

Download 'Gatsby Personal Starter Blog' from the Gatsby CMS tutorial. I've tried to configure my Windows 10 environment as that seemed to cause initial issues (but may not have ironed out everything). Type 'gatsby develop' in command line.

### Expected result

I should be able to see my Gatsby website in local host 8000.

### Actual result

Error as above.

### Environment

System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
  Binaries:
    Node: 14.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/louis/.windows-build-tools/python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.23.11 => 2.23.22
    gatsby-image: ^2.0.39 => 2.4.12
    gatsby-plugin-feed-mdx: ^1.0.0 => 1.0.1
    gatsby-plugin-google-analytics: ^2.0.18 => 2.3.10
    gatsby-plugin-manifest: ^2.0.29 => 2.4.17
    gatsby-plugin-mdx: ^1.2.14 => 1.2.22
    gatsby-plugin-netlify-cms: ^4.3.7 => 4.3.10
    gatsby-plugin-offline: ^2.0.25 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.12 => 3.3.9
    gatsby-plugin-sharp: ^2.0.35 => 2.6.18
    gatsby-plugin-styled-components: ^3.0.7 => 3.3.9
    gatsby-plugin-typography: ^2.2.13 => 2.5.9
    gatsby-remark-copy-linked-files: ^2.0.11 => 2.3.10
    gatsby-remark-images: ^3.3.9 => 3.3.17
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.4.10
    gatsby-remark-smartypants: ^2.0.9 => 2.3.9
    gatsby-remark-vscode: ^2.1.2 => 2.1.2
    gatsby-source-filesystem: ^2.0.29 => 2.3.18
    gatsby-transformer-sharp: ^2.1.18 => 2.5.10
  npmGlobalPackages:
    gatsby-cli: 2.12.59

**Comment by pieh** [comment]
Can you run `npm rebuild` and paste the output? I suspect that during installation of dependencies some binaries fail to build. Given that you are on Windows https://www.gatsbyjs.org/docs/gatsby-on-windows/ this might be relevant (especially when running `npm rebuild` or deleting `node_modules` and reinstalling you will see error messages mentioned there in "if npm install" fails)

**Comment by Louisrobertson20** [comment]
That did the trick! The npm rebuild command ironed out all issues and I can now view the site on local host. Thank you!

**Comment by ascorbic** [comment]
Glad to hear that fixed it. I'll close the issue now.

**Comment by Hiteshkumawat** [comment]
Thanks for your help @pieh
