### ISSUE TITLE
Build failing with Wordpress when wordpress__wp_media is empty

### ISSUE THREAD

**Issue by bshyong** [gatsbyjs/gatsby#2564]
I am having problems with Gatsby building properly; I've traced it down to the `normalize.js` file in the `gatsby-source-wordpress` package.

In the following line, `me` is undefined, causing the build to fail. Adding a guard lets the build complete successfully.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/normalize.js#L303

Is this simply an issue with a missing guard, e.g. if the `media` array is empty?
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/normalize.js#L238

**Comment by KyleAMathews** [comment]
So you can link to media in WordPress that doesn't exist?

Your site has no media but there's still links to media?

**Comment by KyleAMathews** [comment]
(And thanks for digging in and helping with this! The wordpress/gatsby plugin is newish so not fully fleshed out).

**Comment by bshyong** [comment]
@KyleAMathews My site has no media, so trying to build causes an error `undefined has no attribute id`. Looking at the code maybe we are still trying to do something with media even when there is no media (empty array); a guard would fix it

**Comment by bshyong** [comment]
@KyleAMathews any update here? I did some more digging and it seems that the problem is the following:

Note that I have ACF turned on.

1. Media is empty is populated with entities in wordpress__wp_media
` const media = entities.filter(e => e.__type === `wordpress__wp_media`)`
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/normalize.js#L238
2.  during the iteration, we fall into this block because `e.acf == true`.

The failure is in this line `const me = media.find(m => m.source_url === value)`; `me` is undefined because media with those params cannot be found. so the following line fail:
`e.acf[`${key}___NODE`] = me.id` (`me` is `undefined` here)


```
    if (e.acf) {
      _.each(e.acf, (value, key) => {
        if (_.isString(value) && isPhotoUrl(value)) {
          const me = media.find(m => m.source_url === value)
          e.acf[`${key}___NODE`] = me.id
          delete e.acf[key]
        }

        if (_.isArray(value) && value[0] && value[0].acf_fc_layout) {
          e.acf[key] = e.acf[key].map(f => {
            replaceFieldsInObject(f)
            return f
          })
        }
      })
    }
```

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/normalize.js#L305

**Comment by bshyong** [comment]
error from trace for more context:

```
  TypeError: Cannot read property 'id' of undefined
  
  - normalize.js:359 
    [website-frontend]/[gatsby-source-wordpress]/normalize.js:359:38

```

**Comment by KyleAMathews** [comment]
Oh hmmm — yeah, could you add a PR that wraps all the media linking code after the find in `if (me) {}` so we just skip trying to link to media if there is no media?

**Comment by bshyong** [comment]
here you go! https://github.com/gatsbyjs/gatsby/pull/2619
