### ISSUE TITLE
Error EPERM for mkdir .cache after reruning `gatsby develop`

### ISSUE THREAD

**Issue by hayk94** [gatsbyjs/gatsby#25658]
## Description

Getting error EPERM , every time I make a change to `gatsby-node.js` file and re-run `gatsby-develop`

Tried clearing the cache, but the only workaround for this at the moment is to restart whole windows.

```
C:\Users\Hayk_Safaryan\projects\egghead\my-blog>gatsby develop
success open and validate gatsby-configs - 0.038s
success load plugins - 0.550s
success onPreInit - 0.008s

 ERROR

Missing onError handler for invocation 'initialize', error was 'Error: EPERM: operation not permitted, mkdir 'C:\Users\Hayk_Safaryan\projects\egghead\my-blog\.cache''. Stacktrace was 'Error: EPERM: operation not permitted, mkdir 'C:\Users\Hayk_Safaryan\projects\egghead\my-blog\.cache''

⠇ initialize cache
```

### Steps to reproduce

https://github.com/hayk94/my-blog

`gatsby develop`

make change to `gatsby-node.js` file

rerun `gatsby develop`

### Expected result

local dev server should start

### Actual result
getting the error described above.

### Environment

$ gatsby info --clipboard

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.23.12 => 2.23.21
    gatsby-source-filesystem: ^2.3.18 => 2.3.18
    gatsby-transformer-remark: ^2.8.23 => 2.8.23

**Comment by shinaBR2** [comment]
I have exactly the same problem on Windows 10 after I run `yarn clean`, `gatsby clean`.

I did the following:
- Right click on project folder, select "Properties" => "Security".
- Click "Edit" button on the right hand of "To change permissions, click Edit".
- Allow "Full control" for all Users and Groups.

It works for me, not sure if it effects something or not. But at least, I can run `gatsby develop` now. Hope this help @hayk94

**Comment by hayk94** [comment]
Yeah, unfortunately it won’t work on corporate laptops.

**Comment by shinaBR2** [comment]
Yeah so bad. I copy everything in my project folder into another one, remove and create new folder, and it works like a charm.

**Comment by shinesanthosh** [comment]
I'm also having the same issue after I did the update🤦‍♂️.  I tried giving access to every user 😅. It works for a single time. And then I have to restart the ide to run it again

**Comment by grabtheskills** [comment]
Hi guys any solution?

**Comment by CeoFred** [comment]
how tf does this remain unattended to??

**Comment by shinesanthosh** [comment]
Nobody notices this. Since gatsby-node.js need to be configured only once (in most cases), I just ignored the issue as there's no fix for it😅

**Comment by shinesanthosh** [comment]
An ide restart fixes the issue for me. 

> Is the `.cache` folder created normally otherwise? Or does creating folders always fail?

It creates the cache without any issue

**Comment by CeoFred** [comment]
Restarting always works.. that's a stupid fix though

**Comment by beatyt** [comment]
Just adding my laments.

**Comment by Aloinn** [comment]
Manually creating the .cache folder fixed the problem for me

**Comment by alpinstang** [comment]
This is still a persisting problem. Bump..

**Comment by alpinstang** [comment]
I fixed it by giving the `Users` group `Full control` in the project folder properties.

right click project folder > Properties >  Security (Tab) > Select Users. Check Allow Full control in permissions list.

**Comment by AleC77** [comment]
i have the same issue. There's a more consistent way to fix this issue?

**Comment by suleymanbariseser** [comment]
I was getting this error when I tried to use [gatsby-source-contentful](https://www.gatsbyjs.com/plugins/gatsby-source-contentful/) with downloadLocal: true. The problem is caused because of the gatsby-source-fileystem's number of concurrent download limit and timeout. The solution is to reduce number of concurrent download. Add following line to gatsby-config.js and this may solve your issue in this case.
`process.env.GATSBY_CONCURRENT_DOWNLOAD = 1;`

**Comment by FIFOFridge** [comment]
In my case restarting VS Code and launching gatsby via cmd or powershell then launching vscode do the job

**Comment by Sameedahmad** [comment]
@suleymanbariseser It would work this way, however it takes so long for the build, I don't know why this is happening on windows only, As my other colleagues on mac don't run into this issue at all.

**Comment by lennyxc** [comment]
If you're getting this on VS code terminal on windows, run VS code as administrator.
