### ISSUE TITLE
Gatsby navigate throws a window undefined error

### ISSUE THREAD

**Issue by CaptainChemist** [gatsbyjs/gatsby#25650]
## Description

After switching to use `navigate` from the gatsby package rather than @reach/router, I'm getting a window not defined error when I run gatsby build. Is this expected? I feel like I must be doing something silly.

### Steps to reproduce

Here is the offending code, I am getting an error on the first line that calls `navigate`.

```
import { navigate } from 'gatsby'
import * as React from 'react'

import Layout from '../layout/SiteLayout'
import { RouteProps } from '../../types'
import { isAdmin, isLoggedIn } from '../../utils/auth'

const RouteAdmin = ({
  component: Component,
  location,
  ...rest
}: RouteProps) => {
  const { path, title, description } = rest

  if (!isLoggedIn()) {
    navigate(`/user/login`)
    return null
  }
  if (!isAdmin()) {
    navigate(`/`)
    return null
  }
  return (
    <Layout
      path={path}
      title={title}
      description={description}
      darktheme={false}
    >
      <Component {...rest} />
    </Layout>
  )
}

export default RouteAdmin
```

### Expected result

I'd expect it to build without throwing a window undefined error. I can actually get this result if I use `navigate` from reach-router rather than gatsby.

### Actual result

Here is the error I get in my console, it luckily points directly to the problem in the gatsby navigate code:

```
  277 | 
  278 | var navigate = function navigate(to, options) {
> 279 |   window.___navigate(rewriteLinkPath(to, window.location.pathname), options);
      | ^
  280 | };
  281 | 
  282 | exports.navigate = navigate;


  WebpackError: ReferenceError: window is not defined
  
  - index.js:279 
    node_modules/gatsby-link/index.js:279:1
  
  - RouteAdmin.tsx:16 
    src/components/routes/RouteAdmin.tsx:16:15
```

### Environment

  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 72.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.23.7 => 2.24.1
    gatsby-image: ^2.2.7 => 2.2.34
    gatsby-plugin-google-tagmanager: ^2.1.9 => 2.1.18
    gatsby-plugin-less: ^3.0.4 => 3.0.15
    gatsby-plugin-mailchimp: ^5.1.2 => 5.1.2
    gatsby-plugin-manifest: ^2.2.4 => 2.2.30
    gatsby-plugin-mdx: ^1.2.15 => 1.2.15
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.16
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.2.9 => 2.3.4
    gatsby-plugin-sitemap: ^2.2.26 => 2.2.26
    gatsby-plugin-styled-components: ^3.1.3 => 3.1.14
    gatsby-plugin-typescript: ^2.1.5 => 2.1.20
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.1.7 => 2.1.39
    gatsby-source-graphql: ^2.1.3 => 2.1.25
    gatsby-transformer-sharp: ^2.2.5 => 2.3.6

**Comment by mhmdAljefri** [comment]
@pieh & @blainekasten of you don't mind I would like to help In this?

**Comment by CaptainChemist** [comment]
Thanks everyone! I realized after more research that this has been reported here: https://github.com/gatsbyjs/gatsby/issues/10421

Over there they say that it can be fixed by moving this into a `componentDidMount` and that might be so, I guess the thing that is a little confusing is why the reach-router works without an error and why gatsby is apparently using that router under the hood but throwing this error regardless. Are there any disadvantages that I need to be aware of with using reach-router here and also not using it in `componentDidMount` like they suggest? 

More broadly, why not just update the `navigate` gatsby method to have a window undefined check just like the gatsby documentation recommends that other people do for their own code? I'm just trying to understand why this doesn't get addressed either by officially recommending using reach-router or by adding the check in the `navigate` gatsby function itself- is there some sort of anti-pattern you are trying to ward against? 

This particular bug took me a few days to track down because initially, it was not outputting the specific error during the build and I was seeing only a more generic one about window being undefined _somewhere_ in the project. I'm just afraid others will run into this too since trying to redirect when a component loads is a common use-case for protecting routes or other components from loading.

**Comment by blainekasten** [comment]
@CaptainChemist The reason for the crash is that `window` doesn't exist in SSR. Gatsby does some special stuff that requires window access that @reach/router doesn't do.

The main problem here is that `navigate` shouldn't actually ever be used in the render function. Even @reach/router's navigate _shouldn't_ be used that way. If you need to re-route a user you should use the `Redirect` component. This has more browser-accurate behavior to redirecting a user. 

You should change your code to use a `<Redirect>` I'm going to close this as it's not totally a problem with `navigate` but more in the usage. Hope that helps! feel free to respond with questions or thoughts 💜

**Comment by 14gasher** [comment]
@blainekasten Would it be possible to update the docs? They do call a navigate in the render function here:

https://www.gatsbyjs.com/tutorial/authentication-tutorial/#controlling-private-routes

```js
import React from "react"
import { navigate } from "gatsby"
import { isLoggedIn } from "../services/auth"
const PrivateRoute = ({ component: Component, location, ...rest }) => {
  if (!isLoggedIn() && location.pathname !== `/app/login`) {
    navigate("/app/login")
    return null
  }
  return <Component {...rest} />
}
export default PrivateRoute
```

**Comment by wajeshubham** [comment]
The same error still exists while building, any solution for this?

**Comment by Quentin-Danjou** [comment]
Hello @LekoArts! Not sure Blaine is still working for Gatsby/Netlify so I hope you don't mind the tag here!

It is 2023 and the official doc of Gatsby https://www.gatsbyjs.com/tutorial/authentication-tutorial/#controlling-private-routes still mentions to do `navigate()` in a render, and I cannot see how to do it with Redirect. Do you mind sharing an example for me and those who sometimes lend here?

**Comment by victorlin** [comment]
I'm using Gatsby v2.32.13 so this might not apply to newer versions, but conditioning on `browser` being defined [like this](https://github.com/gatsbyjs/gatsby/issues/5329#issuecomment-484741119) works well:

```js
const browser = typeof window !== "undefined" && window;

if (browser) {
  navigate("/some-page");
  return null;
}
```
