### ISSUE TITLE
gatsby starter failed Building development bundle

### ISSUE THREAD

**Issue by def-not-ys** [gatsbyjs/gatsby#25657]
## Description

I am using this [gatsby-ghost-starter](https://www.gatsbyjs.org/starters/TryGhost/gatsby-starter-ghost/). I successfully installed the app, and ran `yarn` to installed all dependencies. But when I ran `gatsby develop` I kept getting this error:

```bash
 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.flat' in <file path>

If you're trying to use a package make sure that 'core-js/modules/es.array.flat' is installed. If you're trying to use a local file make sure that the path is correct.

File: .cache\error-overlay-handler.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'core-js/modules/es.array.unscopables.flat' in <file path>

If you're trying to use a package make sure that 'core-js/modules/es.array.unscopables.flat' is installed. If you're trying to use a local file make sure that the path is correct.

File: .cache\error-overlay-handler.js

failed Building development bundle - 3.868s
```
I tried adding the react tool tip mentioned in this post [#25453](https://github.com/gatsbyjs/gatsby/issues/25453) and still getting the same error. 

### Steps to reproduce

```bash 
npm install -g gatsby-cli
```

```bash 
gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost
```
```bash
yarn
```
```bash
gatsby develop
```
```bash
ERROR #98124  WEBPACK (error message above)
```

### Expected result

Should develop successfully 

### Actual result

not able to complete building development bundle

```bash 
failed Building development bundle
```

### Environment

```bash
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz  
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.2
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: 2.23.20 => 2.23.20
    gatsby-awesome-pagination: 0.3.6 => 0.3.6
    gatsby-image: 2.4.12 => 2.4.12
    gatsby-plugin-advanced-sitemap: 1.5.5 => 1.5.5
    gatsby-plugin-catch-links: 2.3.10 => 2.3.10
    gatsby-plugin-feed: 2.5.10 => 2.5.10
    gatsby-plugin-force-trailing-slashes: 1.0.4 => 1.0.4   
    gatsby-plugin-manifest: 2.4.17 => 2.4.17
    gatsby-plugin-offline: 3.2.16 => 3.2.16
    gatsby-plugin-react-helmet: 3.3.9 => 3.3.9
    gatsby-plugin-sharp: 2.6.17 => 2.6.17
    gatsby-source-filesystem: 2.3.18 => 2.3.18
    gatsby-source-ghost: 4.0.5 => 4.0.5
    gatsby-transformer-sharp: 2.5.10 => 2.5.10
  npmGlobalPackages:
    gatsby-cli: 2.12.60
```

**Comment by mattfelten** [comment]
I'm getting this too with my project. I'm not seeing it locally though which is weird. But my Netlify build is giving me the same error.

**Comment by AndrejGajdos** [comment]
I have the same issue from today.

**Comment by danielmacuare** [comment]
+1 Here. I'm having the same issue while doing the following:

````
gatsby new damt-blog https://github.com/TryGhost/gatsby-starter-ghost
gatsby develop
```

**Comment by andyhmltn** [comment]
Also seeing this locally on an existing gatsby installation

**Comment by andyhmltn** [comment]
I upgraded gatsby to `2.24.18` and this appears to be fixed

**Comment by AndrejGajdos** [comment]
Thanks @andyhmltn. I don't see an error with that version.

**Comment by def-not-ys** [comment]
@andyhmltn would you mind explaining how to upgrade gatsby? (I am new to web development). thanks

**Comment by andyhmltn** [comment]
@def-not-ys If you're using yarn:`yarn upgrade gatsby@2.24.18` or if you're using npm: `npm install myPackage@2.0.0 --save`

Let me know if that doesn't work

**Comment by def-not-ys** [comment]
@andyhmltn  Thanks! Yes upgrading gatsby fixed the error on building development. 
I did not see the option of `gatsby@2.24.18` so I upgraded it up `gatsby@2.24.2`.
however now I am getting a bunch of errors on GraphQL. but it successfully built the development bundle.
Upgrading seems to the fix to this issue. Thank you so much!
will close this issue now.

**Comment by andyhmltn** [comment]
@def-not-ys Great news 👍

**Comment by sunshine940326** [comment]
I have the same issue from today.
