### ISSUE TITLE
Gatsby Link is appending the target path to the current page URL.... sometimes

### ISSUE THREAD

**Issue by raquelmsmith** [gatsbyjs/gatsby#25661]
## Description

The <Link> component is placing the target path after the current page URL. For example, the `blog/blog/` in this URL:

![image](https://user-images.githubusercontent.com/18598166/87095626-ea48a880-c1f5-11ea-8ee3-f712f7cc12ac.png)

I'm seeing that when using the Link component on [this page](https://5f0791653b549a0007a8e4f5--wizardly-spence-993265.netlify.app/blog/): 
![image](https://user-images.githubusercontent.com/18598166/87095734-22e88200-c1f6-11ea-8786-8a66c6c94e50.png)

My link looks like this:

```js
<Link
       to={`blog/${node.slug}`}
       aria-label={`Continue reading ${node.title}`}
>
``` 

What's _really_ weird is that I get a different result on different builds. When it was building in Netlify as part of the PR checks it worked fine. But when I actually deployed it from Master I got this behavior (you can see it [here](https://5f0791653b549a0007a8e4f5--wizardly-spence-993265.netlify.app/blog/) - I manually deployed the PR check deploy preview to my live site since that one worked for whatever reason).

Important to note, though, is that I **AM** seeing this bug in my local development environment.

### Steps to reproduce

Not super sure here since it only happens sometimes. But you can see the page in question on my repo here: https://github.com/raquelmsmith/rms-portfolio/blob/master/src/pages/blog.js

### Expected result

The link component wouldn't add the target path to the current page path. It would use the root domain and add the described path after that.

### Actual result

The target page path was appended to the existing page path.

### Environment
```
  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.24.1 => 2.24.1 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-emotion: ^4.1.18 => 4.1.18 
    gatsby-plugin-feed: ^2.5.11 => 2.5.11 
    gatsby-plugin-gtag: ^1.0.13 => 1.0.13 
    gatsby-plugin-manifest: ^2.3.6 => 2.3.6 
    gatsby-plugin-offline: ^3.2.17 => 3.2.17 
    gatsby-plugin-polished: ^1.0.3 => 1.0.4 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-remote-images: ^1.0.1 => 1.0.7 
    gatsby-plugin-robots-txt: ^1.4.0 => 1.5.0 
    gatsby-plugin-sharp: ^2.6.19 => 2.6.19 
    gatsby-plugin-sitemap: ^2.0.11 => 2.2.19 
    gatsby-plugin-typography: ^2.4.3 => 2.4.3 
    gatsby-source-filesystem: ^2.2.4 => 2.2.4 
    gatsby-source-wordpress: ^3.3.21 => 3.3.21 
    gatsby-transformer-sharp: ^2.5.11 => 2.5.11 
  npmGlobalPackages:
    gatsby-cli: 2.11.13
```

**Comment by wardpeet** [comment]
Hey,

You should use 
```
<Link
       to={`/blog/${node.slug}`}
       aria-label={`Continue reading ${node.title}`}
>
```

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by raquelmsmith** [comment]
Ahhhhh a forward slash at the beginning. Thank you!!
