### ISSUE TITLE
'gatsby' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Adityac1** [gatsbyjs/gatsby#25678]
I am trying to create a new project in CMD using gatsby new projects. I am getting the error as 'gatsby' is not recognized as an internal or external command,
operable program or batch file.

Even I had installed using the cmd npm i -g gatsby-cli. I am getting a successful message but I am unable to create a new project

Please, anyone, help me in  fixing the issue

**Comment by rametta** [comment]
Duplicate issue: https://github.com/gatsbyjs/gatsby/issues/2509#issuecomment-384779247

**Comment by TylerBarnes** [comment]
Hi @Adityac1 , thanks for opening an issue. As @rametta mentioned this is a duplicate so please follow the steps in that linked comment and follow up in that issue if needed. 
Thanks again!
