### ISSUE TITLE
Gatsby or NextJS for ecommence complex site

### ISSUE THREAD

**Issue by stanleyyuenyiu** [gatsbyjs/gatsby#25674]
I have below applications:

a magento2 e-commence site with Restful API in docker

some nodejs micro service Restful API in docker

i wanna to develop a ecommence frontend (use magento 2 api)  + user portal site (use some micro service that code by nodejs)

given that:

i have over 30000 user
i have 50 pages on user portal, some path will depends on user, which mean not able to pre-gen, e.g /myinbox/letter-from-tom-to-me 
i have over 10 store represent 10 countries , each of them has more than 20 products, and may increasing
Both need to serve more than 10 locales, and may keep increasing
Both need to have different localisation setting, such as different UI by country

GATSBY is a good solution on that kind of unknown growth and complex projects or better use NEXTJS

**Comment by TylerBarnes** [comment]
Hi @stanleyyuenyiu thanks for opening this issue and asking such a great question!
Given your requirements Gatsby is a great choice! Your 30k users should make no difference in build times as you'll need to dynamically create anything related to their profile or account client-side.
Gatsby will offer you better site speed and maintainability and make scaling for high traffic a non-issue. I would recommend it for this type of project every time.

There is a Magento 2 source plugin here https://www.gatsbyjs.org/packages/gatsby-source-magento2/?=magento and you'll be able to do anything dynamic you want to do in-browser using the Magento2 api.
