### ISSUE TITLE
I can't see any meta tag in the build directory after running gatsby build

### ISSUE THREAD

**Issue by diegomadeit** [gatsbyjs/gatsby#25676]
## Description

I noticed the problem because Facebook Share is not picking up OpenGraph meta tags on my project. If I inspect the code the meta tags are there but If I check index.html file in the build directory I see no meta tags.

- My project is a Gatsby theme.

- I use createContext() and I use gatsby-ssr and gatsby-browser to wrap all the elements with a Provider.

### Steps to reproduce
To make it more simple I removed the content of gatsby-ssr and gatsby-browser and simplified the code this way, but the problem keeps the same: 

Note: I'm passing data to Layout through createPage() context.

```
const Layout: React.FC<LayoutProps> = ({
}) => {
  const data = useStaticQuery(graphql`
    query LayoutQuery {
      datoCmsSite {
        faviconMetaTags {
          tags
        }
      }
    }
  `);

  return (
    <div>
      <HelmetDatoCms>
        <html lang="en" />
        <title>test</title>
        <meta name="description" content="test" />
        <meta property="og:title" content="test"></meta>
      </HelmetDatoCms>
    </div>
  );
};
export default Layout;
```

I'm using HelmetDatoCms(gatsby-source-datocms@^2.1.22). Also tried directly with react-helmet(react-helmet@^5.2.1) with same result.

These are the plugings I'm using:
"gatsby-plugin-google-tagmanager"
"gatsby-plugin-typescript"
"gatsby-source-datocms"
"gatsby-plugin-theme-ui"
"gatsby-plugin-sitemap"
"gatsby-plugin-feed"

### Expected result

I can see meta tag on build directory so I can use social share like Facebook Share.

### Actual result

No meta tag on build directory content.

### Environment

System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 78.0.1
    Safari: 13.0.4
  npmGlobalPackages:
    gatsby-cli: 2.6.7

**Comment by TylerBarnes** [comment]
Hi @diegomadeit  !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by diegomadeit** [comment]
Hi @TylerBarnes, thanks for your reaction. This is my firts Gatsby professional project and I really enjoyed doing it, I really like Gatsby. I work for the marketing deparment so social sharing is vital. I'm going to share with you a repo I created for this, hopefuly we can find together an easy a solution.
