### ISSUE TITLE
Getting an error looping through menu items fetched from WordPress

### ISSUE THREAD

**Issue by sjoerdvermeijden** [gatsbyjs/gatsby#25702]
Can someone help me with this, i'm getting an error saying "Expected an assignment or function call and instead saw an expression" while looping through the WordPress navigation items. Thanks!

<img width="578" alt="Schermafbeelding 2020-07-12 om 14 45 08" src="https://user-images.githubusercontent.com/13441035/87246596-b5835e00-c44e-11ea-9605-4ee842a3150a.png">
<img width="329" alt="Schermafbeelding 2020-07-12 om 14 45 22" src="https://user-images.githubusercontent.com/13441035/87246597-b6b48b00-c44e-11ea-9485-3c4a7703ec0e.png">

**Comment by doc-han** [comment]
Hi @sjoerdvermeijden the problem here is with your jsx.
the anonymous function with parameter **item** has to return a value and this value isn't supposed to be in curly braces. So your code will look like below
```js
<ul>
	{ data.allWordpressWpApiMenusMenusItems.edhes[0].node.items.map(item => {
		return item.title;
	})}
</ul>
```

**Comment by sjoerdvermeijden** [comment]
Thanks! Now how would i wrap this in div tags, because <div>return item.title; </div> Doesn't work and i didn't get it to work wrapping in in template tags either.

**Comment by doc-han** [comment]
`return <div> item.title </div>` should work

**Comment by sjoerdvermeijden** [comment]
@doc-han Thanks! `return <div> {item.title} </div>` worked for me!

**Comment by doc-han** [comment]
Great!
