### ISSUE TITLE
ERROR #98123 Generating SRR budle failed

### ISSUE THREAD

**Issue by jack0wsky** [gatsbyjs/gatsby#25701]
## Description

While running `gatsby develop` it is #98123 error. I'm using Mapbox API and its maps. I tried to unmount component which uses maps as well as reinstalling npm, deleting node_modules and package-lock.json but it didn't solve problem. It looks like it is something wrong with mapbox files but yesterday everything worked without issues. I have also commented `wrapRootElement` with Redux but it generated other error.

Describe the issue that you're seeing.

### Steps to reproduce

Not sure right now

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

No errors during development

What should happen?

### Actual result

error #98123 generating SSR bundle failed

What happened.

### Environment

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 78.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.24.2 => 2.24.2
    gatsby-cli: ^2.12.60 => 2.12.60
    gatsby-image: ^2.4.5 => 2.4.13
    gatsby-plugin-manifest: ^2.4.9 => 2.4.18
    gatsby-plugin-offline: ^3.2.7 => 3.2.17
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.10
    gatsby-plugin-sharp: ^2.6.9 => 2.6.19
    gatsby-plugin-styled-components: ^3.3.4 => 3.3.10
    gatsby-plugin-transition-link: ^1.20.2 => 1.20.2
    gatsby-source-filesystem: ^2.3.8 => 2.3.19
    gatsby-transformer-sharp: ^2.5.3 => 2.5.11
  npmGlobalPackages:
    gatsby-cli: 2.12.1

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by herecydev** [comment]
You need to provide the minimal reproduction otherwise it's really difficult to help.

**Comment by blainekasten** [comment]
@jack0wsky agreed, we need more info. Typically SSR issues happen because some runtime code is trying to access `window` (which doesn't exist in SSR).

Mind sharing the code from your component? and maybe the exact output error you get from SSR?

related: #25729

**Comment by verlekar-viraj** [comment]
> @jack0wsky agreed, we need more info. Typically SSR issues happen because some runtime code is trying to access `window` (which doesn't exist in SSR).
> 
> Mind sharing the code from your component? and maybe the exact output error you get from SSR?
> 
> related: #25729

@blainekasten Not sure if this is the same issue but i got a similar issue when using `gatsby-plugin-react-native-web`.

ERROR #98123  WEBPACK
Generating SSR bundle failed
Missing external configuration for type:commonjs2

This error is not thrown if i exclude the plugin from gatsby-config.js.

I got this issue when using expo with gatsby. https://github.com/expo/examples/tree/master/with-gatsby

**Comment by jack0wsky** [comment]
Ok, I have tested some solutions and I'm sure that there is no `window` declared, however, what's interesting I removed `wrapRootElement` from `gatsby-srr.js` and `gatsby-browser.js` which is responsible for Redux. Then developer server still didn't work but in chrome dev tools was error `Uncaught SyntaxError: Unexpected token '<' in common.js`

**Comment by freiksenet** [comment]
Mapbox requires a browser environment, so you need to make sure it's not trying to load when you are doing SSR generation.

In your `gatsby-node.js` config you should shim it:

```js
exports.onCreateWebpackConfig = ({ actions, stage }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /mapbox-gl/,
            use: ["null-loader"],
          },
        ],
      },
    });
  }
};
```

In your Map component you should check if Mapbox is defined. For example you can make Map only load when the component Mounted.

```js
const MyMap = () => {
  const [hasMounted, setHasMounted] = useState(false);
  useEffect(() => {
    setHasMounted(true);
  }, []);
  if (!hasMounted) {
    return null;
  }

  const Map = ReactMapboxGl({
    accessToken: process.env.GATSBY_MAPBOX_TOKEN,
    minZoom: 6,
    maxZoom: 12,
  });

  return (
    <Map />
  );
};
```

You can also use library like [loadable-components](https://github.com/smooth-code/loadable-components) to lazily load your Map component instead.

**Comment by jack0wsky** [comment]
> Mapbox requires a browser environment, so you need to make sure it's not trying to load when you are doing SSR generation.
> 
> In your `gatsby-node.js` config you should shim it:
> 
> ```js
> exports.onCreateWebpackConfig = ({ actions, stage }) => {
>   if (stage === "build-html") {
>     actions.setWebpackConfig({
>       module: {
>         rules: [
>           {
>             test: /mapbox-gl/,
>             use: ["null-loader"],
>           },
>         ],
>       },
>     });
>   }
> };
> ```
> 
> In your Map component you should check if Mapbox is defined. For example you can make Map only load when the component Mounted.
> 
> ```js
> const MyMap = () => {
>   const [hasMounted, setHasMounted] = useState(false);
>   useEffect(() => {
>     setHasMounted(true);
>   }, []);
>   if (!hasMounted) {
>     return null;
>   }
> 
>   const Map = ReactMapboxGl({
>     accessToken: process.env.GATSBY_MAPBOX_TOKEN,
>     minZoom: 6,
>     maxZoom: 12,
>   });
> 
>   return (
>     <Map />
>   );
> };
> ```
> 
> You can also use library like [loadable-components](https://github.com/smooth-code/loadable-components) to lazily load your Map component instead.

Ok, thank you. I'll try this solution.
