### ISSUE TITLE
Blog starter throwing error 

### ISSUE THREAD

**Issue by vpsk** [gatsbyjs/gatsby#25700]
## Description

Describe the issue that you're seeing.
gatsby starter blog creator giving error : 

gatsby new personal-blog https://github.com/thomaswangio/gatsby-personal-starter-blog
info Creating new site from git: https://github.com/thomaswangio/gatsby-personal-starter-blog.git
Cloning into 'personal-blog'...
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 50 (delta 1), reused 37 (delta 0), pack-reused 0
Unpacking objects: 100% (50/50), done.
success Created starter directory layout
info Installing packages...
yarn install v1.17.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby > @pmmmwh/react-refresh-webpack-plugin@0.3.3" has incorrect peer dependency "react-refresh@^0.8.2".
warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "netlify-cms-app > netlify-cms-widget-code@1.2.0" has unmet peer dependency "codemirror@^5.46.0".
warning "netlify-cms-app > netlify-cms-widget-list@2.6.0" has unmet peer dependency "netlify-cms-lib-widgets@^1.0.0".
warning "netlify-cms-app > netlify-cms-widget-relation@2.8.0" has unmet peer dependency "netlify-cms-lib-widgets@^1.0.0".
warning "netlify-cms-app > netlify-cms-widget-code > react-codemirror2@6.0.1" has unmet peer dependency "codemirror@5.x".
warning "netlify-cms-app > netlify-cms-core > redux-notifications > react-redux@4.4.10" has incorrect peer dependency "redux@^2.0.0 || ^3.0.0".
[4/4] 🔨  Building fresh packages...
[-/19] ⡀ waiting...
[-/19] ⡀ waiting...
[-/19] ⡀ waiting...
[13/19] ⡀ oniguruma
error /Users/virendra.singh/Desktop/project/personal-blog/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/virendra.singh/Desktop/project/personal-blog/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.2.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node/14.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/virendra.singh/Desktop/project/personal-blog/node_modules/oniguruma/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/14.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/virendra.singh/Library/Caches/node-gyp/14.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/virendra.singh/Library/Caches/node-gyp/14.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/14.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/virendra.singh/Library/Caches/node-gyp/14.2.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/virendra.singh/Desktop/project/personal-blog/node_modules/oniguruma',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node/14.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/Cellar/node/14.2.0/bin/node" "/usr/local/Cellar/node/14.2.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/virendra.singh/Desktop/project/personal-blog/node_modules/oniguruma

 ERROR 

Command failed with exit code 1: yarnpkg

  Error: Command failed with exit code 1: yarnpkg
  
  - error.js:56 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:56:11
  
  - index.js:114 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:114:26
  
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
  
  - init-starter.js:136 async install
    [lib]/[gatsby-cli]/lib/init-starter.js:136:7
  
  - init-starter.js:206 async clone
    [lib]/[gatsby-cli]/lib/init-starter.js:206:3
  
  - init-starter.js:345 async initStarter
    [lib]/[gatsby-cli]/lib/init-starter.js:345:19
  
  - create-cli.js:400 
    [lib]/[gatsby-cli]/lib/create-cli.js:400:7

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
    Safari: 13.1.1
  npmGlobalPackages:
    gatsby-cli: 2.12.60

**Comment by blainekasten** [comment]
I just ran `gatsby new personal-blog https://github.com/thomaswangio/gatsby-personal-starter-blog` and it worked for me. It looks like this is an issue with your local setup. This line seems peculiar `gyp: No Xcode or CLT version detected!`

**Comment by blainekasten** [comment]
Thanks so much for opening this issue! As stated, this is slightly tangential to Gatsby, and it seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby :muscle:
