### ISSUE TITLE
"gatsby build" not including CSS when the project package json marks the CSS as a side effect

### ISSUE THREAD

**Issue by mohsinulhaq** [gatsbyjs/gatsby#25707]
## Bug Report

**Describe the bug**

I am using gatsby via docz. When I run `docz build`, which in turn runs `gatsby build`, the build is not including a CSS file that I import in one of the components.
When I remove that CSS file from the `sideEffects` array in the project package.json, it works fine.

**To Reproduce**

- In the project, import CSS in one of the documentation components.
- Mark that CSS as a `sideEffect` in `package.json`
- Run `gatsby build`.
- The final build will not include that CSS.
- [react-popper-tooltip](https://github.com/mohsinulhaq/react-popper-tooltip) this repo can be used to check it out.

**Expected behavior**

The CSS to be in the final bundle.

**Environment**

```
  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
    Safari: 13.1.1
```

**Comment by mohsinulhaq** [comment]
@wardpeet anything on this?

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
