### ISSUE TITLE
Failed to create project

### ISSUE THREAD

**Issue by KevinBurton** [gatsbyjs/gatsby#25710]
### Description

gatsby new gatsby-starter-business https://github.com/v4iv/gatsby-starter-business causes a host of node-gyp error messages

### Steps to reproduce

gatsby new gatsby-starter-business https://github.com/v4iv/gatsby-starter-business

### Expected result

New project should be created without errors

### Actual result

Here is a sample of the output:

Building: C:\Program Files\nodejs\node.exe C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\RKevi\\source\\repos\\gatsby-starter-business\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:175:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:175:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import sys; print "2.7.17
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.4.0
gyp verb command install [ '14.4.0' ]
gyp verb install input version string "14.4.0"
gyp verb install installing version: 14.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.4.0
gyp verb build dir attempting to create "build" dir: C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.Windows10SDK.18362
gyp verb find vs2017   - Using this installation with Windows 10 SDK
gyp verb find vs2017 using installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'C:\\Users\\RKevi\\source\\repos\\gatsby-starter-business\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\RKevi\\source\\repos\\gatsby-starter-business\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\RKevi\\source\\repos\\gatsby-starter-business\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\RKevi\\.node-gyp\\14.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\RKevi\\.node-gyp\\14.4.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\RKevi\\source\\repos\\gatsby-starter-business\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\RKevi\\.node-gyp\\14.4.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\RKevi\\source\\repos\\gatsby-starter-business\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\RKevi\\source\\repos\\gatsby-starter-business\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\RKevi\.node-gyp\14.4.0
gyp verb found first Solution file build/binding.sln
gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\RKevi\\source\\repos\\gatsby-starter-business\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\RKevi\source\repos\gatsby-starter-business\node_modules\node-sass
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz
  Binaries:
    Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.19041.1.0
  npmGlobalPackages:
    gatsby-cli: 2.12.60

**Comment by blainekasten** [comment]
This doesn't seem like a gatsby issue but instead an issue with your local setup with node. Try using node 12? I just closed #25700 and the only correlation I see is Node 14.

**Comment by lukeAnderson2015** [comment]
I'm seeing this error as well on a fresh install via gatsby new my-gatsby-project https://github.com/PrototypeInteractive/gatsby-react-boilerplate

**Comment by zxlvera** [comment]
I am also encountering a similar issue with this starter template:
`gatsby new gatsby-starter-strata https://github.com/codebushi/gatsby-starter-strata`
