### ISSUE TITLE
Problem rendering MDX & layout via multiple templates.

### ISSUE THREAD

**Issue by EximiousKnights** [gatsbyjs/gatsby#25718]
## Description

I am having trouble rendering multiple types of content, which I have defined in two separate templates - 'singlePost' and 'page'. Both templates uses MDXRenderer to render the .mdx content for the templates. 
Entering "http://localhost:8000/2020/post-x/" uses 'singlePost' template correctly. However, entering "http://localhost:8000/projects" which should use 'page' template does not render the layout. Can you please help me?

### Steps to reproduce
https://github.com/EximiousKnights/gatsby-test

### Expected result
MDX should render with correct layout and with corresponding template. 

### Actual result
MDX renders correctly on one template (singlePost template) but does not render correctly on the other template (page template). All styled-components and layouts disappear. For example, mdx files using 'singlePost' template works as expected, as shown below:

![n2](https://user-images.githubusercontent.com/68223567/87381298-10829580-c5b4-11ea-8133-8bcda2bd6af9.png)

But, mdx files using 'page', template does not render correctly as shown below: Layout, styles, and background disappear.

![n](https://user-images.githubusercontent.com/68223567/87381294-0f516880-c5b4-11ea-9ccf-828c46cae666.png)

### Directory Structure:

![folder](https://user-images.githubusercontent.com/68223567/87381641-e1205880-c5b4-11ea-844a-27856103855f.png)

### Environment

  System:

    OS: Linux 5.7 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 5.0.17 - /bin/bash

  Binaries:

    Node: 14.3.0 - /usr/bin/node
    npm: 6.14.6 - /usr/bin/npm
  Languages:
    Python: 3.8.3 - /usr/bin/python

  npmPackages:

    gatsby: ^2.23.10 => 2.24.2 
    gatsby-background-image: ^1.1.1 => 1.1.1 
    gatsby-cli: ^2.12.58 => 2.12.60 
    gatsby-image: ^2.4.12 => 2.4.13 
    gatsby-plugin-feed-mdx: ^1.0.1 => 1.0.1 
    gatsby-plugin-google-analytics: ^2.3.8 => 2.3.11 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.4.16 => 2.4.18 
    gatsby-plugin-mdx: ^1.2.19 => 1.2.25 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-offline: ^3.2.17 => 3.2.17 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-helmet: ^3.3.8 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.14 => 2.6.19 
    gatsby-plugin-sitemap: ^2.4.9 => 2.4.11 
    gatsby-plugin-styled-components: ^3.3.8 => 3.3.10 
    gatsby-remark-images: ^3.3.13 => 3.3.18 
    gatsby-remark-slug: ^0.1.0 => 0.1.0 
    gatsby-source-filesystem: ^2.3.14 => 2.3.19 
    gatsby-transformer-remark: ^2.8.22 => 2.8.25 
    gatsby-transformer-sharp: ^2.5.7 => 2.5.11 

  npmGlobalPackages:

    gatsby-cli: 2.12.60

**Comment by greenlightjohnny** [comment]
Hi, 
In Gatsby the `src/pages` folder is a bit special, and any mdx is inside it is automatically converted to a page. 
Your pages folder contains two mdx files, projects and about, both of which are not rendering as you want because they are inside the `src/pages` folder.
Your mdx files for your posts are in `src/posts` and are working great.
The solution is to move your mdx files that are not working properly out of the `src/pages` folder and into a new one (say `src/mdxpages` for example). Obviously update the gatsby-node.js, and the gatsby-config.js to search/point at the new file location/name as well. 
Let me know if this works for you, cheers!

**Comment by EximiousKnights** [comment]
@greenlightjohnny Thank you so much, Fred. You saved me, brother. God bless you :)
