### ISSUE TITLE
Gatsby build repaints whole application after/during hydration

### ISSUE THREAD

**Issue by teclone** [gatsbyjs/gatsby#25717]
## Description
I noticed while working on a gatsby project, that the whole page gets repainted after some time, likely after hydration happened. You will see images disappear and later on, reappear after some time lag due to some scripting.

### Steps to reproduce
I created a repo for this, to help reproduce the issue. [https://github.com/teclone/gatsby-image-hydrate-error-demo](https://github.com/teclone/gatsby-image-hydrate-error-demo)

1. Clone the project and yarn install.

2. build the project and run a performance tooling locally

   ```bash
   yarn serve; // builds and the starts the application at `http://localhost:9000`
   ```

3. on chrome, open dev tools, switch to the Performance tab and run a profile.

4. observe the frames, you will see that the images disappeared and reappeared at some point.

   To prove that the images disappeared only after/during hydration, I had to render two images, one renders at the server, another renders after mount.

   By inspecting the frame screenshots, you will observe that the second image also rendered, then disappeared, and then loaded again. The same as the first image.

### Expected result

I expect the images to never get destroyed and recreated after or during hydration. I also assigned the images keys and also added the `suppressHydrationWarning` in case of mismatches, but to no avail. I am even guessing this is not related to hydration, seems something is just calling react render again within gatsby.

### Actual result
the whole application gets recreated/destroyed.

### Environment
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 78.0.1
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12 
    gatsby-image: ^2.4.9 => 2.4.9 
    gatsby-plugin-manifest: ^2.4.14 => 2.4.14 
    gatsby-plugin-offline: ^3.2.13 => 3.2.13 
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.6 
    gatsby-plugin-sharp: ^2.6.14 => 2.6.14 
    gatsby-plugin-typescript: 2.4.14 => 2.4.14 
    gatsby-source-filesystem: ^2.3.14 => 2.3.14 
    gatsby-transformer-sharp: ^2.5.7 => 2.5.7 
  npmGlobalPackages:
    gatsby-cli: 2.12.60

**Comment by blainekasten** [comment]
@teclone I confirmed this is a bug. Thanks for reporting. I'm not certain what's going on here.. We are going to enable SSR for develop soon and that should help in the future to solve these issues. I'm going to link this to #25729 and close as duplicate.

**Comment by teclone** [comment]
> @teclone I confirmed this is a bug. Thanks for reporting. I'm not certain what's going on here.. We are going to enable SSR for develop soon and that should help in the future to solve these issues. I'm going to link this to #25729 and close as duplicate.

@blainekasten, is there any way I can help in facilitating the SSR on development feature

**Comment by blainekasten** [comment]
@teclone I appreciate the willingness! It's a quite involved and complicated. If you want to take a stab and submit a PR we'd be happy to take a look and see if it'll work!

**Comment by teclone** [comment]
ok @blainekasten, I am willing to give it a shot.
