### ISSUE TITLE
[Umbrella] Run SSR in Develop ☔ 

### ISSUE THREAD

**Issue by blainekasten** [gatsbyjs/gatsby#25729]
## Summary

Gatsby currently does not run SSR in develop mode. This has caused some users headaches when they deploy gatsby apps to find that there are production-only issues due to SSR.

The solution is to convert gatsby develop into running true SSR. 

### Motivation

To make Gatsby easier to use, prevent hard to debug errors, and have a more consistent developer experience.

**Comment by teclone** [comment]
@blainekasten , I am ready to start looking into this from tomorrow. I will need to sync with you to get all the necessary understanding of what needs to be done, are you ready and willing to discuss this with me?

**Comment by blainekasten** [comment]
@teclone Yes! Send me an email at blaine@gatsbyjs.com and we'll set up a time to hop on a video call to discuss!

**Comment by teclone** [comment]
> @teclone Yes! Send me an email at [blaine@gatsbyjs.com](mailto:blaine@gatsbyjs.com) and we'll set up a time to hop on a video call to discuss!

ok, done, thanks

**Comment by eyalroth** [comment]
Related: https://github.com/gatsbyjs/gatsby/issues/10706

**Comment by vladar** [comment]
What would be the outcome of this umbrella issue? We have a PR: https://github.com/gatsbyjs/gatsby/pull/24872 that does something similar (runs `renderToString` in develop).

But it fixes only a subclass of hydration issues (won't handle things like `typeof windows` checks, etc.

**Comment by blainekasten** [comment]
@teclone thanks for reaching out! This feature is actually now a priority of the core team for the next few sprints so we'll be able to complete it!

**Comment by blainekasten** [comment]
@vladar I believe it is to create a proper SSR implementation and not the partial solution

**Comment by teclone** [comment]
> @teclone thanks for reaching out! This feature is actually now a priority of the core team for the next few sprints so we'll be able to complete it!

@blainekasten , Thanks a lot, I am following up with the progress. Kudos to you all

**Comment by lucashfreitas** [comment]
This would be neat! I am constantly running into small issues due SSR and have to run gatsby build/serve every time. Would be really useful to use that feature. 

Would love to help as well 👍

**Comment by jakezien** [comment]
+1 on this — my styled components break in production but look fine in dev.

**Comment by KyleAMathews** [comment]
Hey everyone! We've shipped an initial version of SSR in develop in 2.27.0 — upgrade & try it out!

`GATSBY_EXPERIMENTAL_FAST_DEV=true gatsby develop`

Read more about it + some other initiatives we're working on to speedup/improve the dev server https://github.com/gatsbyjs/gatsby/blob/master/docs/reference/release-notes/v2.27/index.md

**Comment by KyleAMathews** [comment]
Also if you find bugs or oddities w/ dev ssr (or if you just want to comment on how awesome it is ;-)) — let us know over at https://github.com/gatsbyjs/gatsby/discussions/28138

**Comment by LekoArts** [comment]
I'll close this in favor of the same discussions, no point in having two duplicate things open: https://github.com/gatsbyjs/gatsby/discussions/28138

Please head on over there and give it a try!
