### ISSUE TITLE
Does Lighthouse 6.1 drastically reduce performance score for Gatsby websites?

### ISSUE THREAD

**Issue by IanLunn** [gatsbyjs/gatsby#25722]
## Summary

Hi. I have a reasonably new Gatsby website that was achieving a performance score in the high 90s. Today, upon doing some tweaks I noticed my performance score now in the 60-70s. I reverted changes (that were actually for the purpose of increase performance further) and still see a bad performance score.

## Relevant information

[Lighthouse 6.1 got released](https://github.com/GoogleChrome/lighthouse/blob/master/changelog.md#610-2020-06-25) a couple of days ago and it now has diagnostics for main-thread-blocking tasks. I believe this is why my site (and unfortunately all Gatsby sites) has dropped around 30 points for performance in Lighthouse.

Can anyone confirm they have found similar?

I don't know what [https://www.gatsbyjs.org](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.gatsbyjs.org%2F) was scoring previously but it is now getting a [performance score of 62 in my test](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.gatsbyjs.org%2F) and the largest issue in minimize main-thread-work.

**Comment by wesbos** [comment]
Mine (wesbos.com) was ~97, I did see mine drop to ~60s a few weeks ago, but now it's showing 84. Same codebase. 

No sure if this is a gatsby issue or not and I still think my site is super fast, just thought I'd drop my numbers in as well. 

<img width="619" alt="image" src="https://user-images.githubusercontent.com/176013/87314414-2b400600-c4f1-11ea-83fd-2384ee8b030f.png">

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Please follow along here: https://github.com/gatsbyjs/gatsby/issues/24332
