### ISSUE TITLE
Gatsby Cloud Uploading Files Not Working This Morning

### ISSUE THREAD

**Issue by dav92lee** [gatsbyjs/gatsby#25730]
## Description

Gatsby Cloud Uploading to s3 isn't taking this morning.  I launched my website this morning and wanted to push a hotfix.  The deploy step where i upload assets to s3 usually takes 3-6 seconds tops, but today my first upload took 13 minutes, and the second one is 30 minutes and counting.  The change has only been a few text/copy changes, so no new assets, packages uploaded or large files from my previous deploys.  Is there any way for me to get clarity on why this is the case?  Can i cancel a deploy that is currently uploading?  The AWS status board doesn't list any downtimes.  Is it because i have traffic now on the site, and I can only upload when those static files aren't currently being accessed?

### Steps to reproduce

Pushing code to a branch that gatsby cloud is wired to deploy.

### Expected result

Gatsby cloud typically takes 3-6 seconds to upload my built gatsby site to the cloud.  

### Actual result

Today it's taking 30 minutes and counting -- i don't know when this is going to end?

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 78.0.1
    Safari: 13.1
  npmPackages:
    gatsby: 2.23.11 => 2.23.11 
    gatsby-image: ^2.4.4 => 2.4.13 
    gatsby-plugin-anchor-links: ^1.1.1 => 1.1.1 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-google-analytics: ^2.3.6 => 2.3.11 
    gatsby-plugin-manifest: ^2.4.5 => 2.4.18 
    gatsby-plugin-offline: ^3.2.3 => 3.2.17 
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.10 
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1 
    gatsby-plugin-s3: ^0.3.3 => 0.3.3 
    gatsby-plugin-sharp: ^2.6.10 => 2.6.19 
    gatsby-plugin-sitemap: ^2.4.11 => 2.4.11 
    gatsby-plugin-smoothscroll: ^1.1.0 => 1.1.0 
    gatsby-plugin-styled-components: ^3.3.2 => 3.3.10 
    gatsby-source-filesystem: ^2.3.4 => 2.3.19 
    gatsby-source-shopify: ^3.2.14 => 3.2.20 
    gatsby-source-strapi: 0.0.12 => 0.0.12 
    gatsby-transformer-sharp: ^2.5.4 => 2.5.11 
  npmGlobalPackages:
    gatsby-cli: 2.12.37

**Comment by dav92lee** [comment]
I upgraded to the pricey paid tier and it just worked.  Is there throttling on uploads on the free plan?

**Comment by blainekasten** [comment]
Hey @dav92lee, The OSS team does not work on the Cloud product. All Gatsby Cloud related questions should be sent to support@gatsbyjs.com.
