### ISSUE TITLE
Can static query using filter?

### ISSUE THREAD

**Issue by stanleyyuenyiu** [gatsbyjs/gatsby#25739]
Can static query using filter?

im using strapi as my config server

i will gather the config data on build time

And i have a component which need to query the config data by user data (e.g user group)

however it seem gatsby not allow me to pass any var to the query or even hard code the query with the param

e.g

```
graphql 
    query MyQuery {
        allStrapiAvailableLanguageByMarkets(filter: {country: {code: {eq: "CA"}}}) {
            nodes {
              country {
                code
              }
              languages {
                code
                name
              }
            }
          }
    }
```

**Comment by stanleyyuenyiu** [comment]
i receive the message of 


Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues

**Comment by herecydev** [comment]
Should be fine. The graphql should be like notice the backticks ` : 

```
graphql`
    query MyQuery {
        allStrapiAvailableLanguageByMarkets(filter: {country: {code: {eq: "CA"}}}) {
            nodes {
              country {
                code
              }
              languages {
                code
                name
              }
            }
          }
    }`
```

**Comment by sidharthachatterjee** [comment]
@stanleyyuenyiu useStaticQuery does _not_ support variables. The static param should work. Like Dan suggested, do include the back ticks and let us know if it doesn't work! Thanks!

**Comment by sidharthachatterjee** [comment]
Marking this as answered and closing. Thank you!
