### ISSUE TITLE
How to setup siteUrl properly for a website with multiple languages 

### ISSUE THREAD

**Issue by dn-l** [gatsbyjs/gatsby#25743]
## Summary

I want my blog website to be `www.mywebsite.com/{lang}/blog` where _lang_ - language (en or es or different)
What should be the siteUrl in this scenario?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by herecydev** [comment]
Gatsby doesn't currently support i18n out of the box, so you'll need to include a plugin (like I've made here: https://www.gatsbyjs.org/packages/gatsby-plugin-internationalization/) or write something yourself that works for you

**Comment by sidharthachatterjee** [comment]
Hey @dn-l 

That's a great question. As Dan pointed out, Gatsby doesn't support i18n out of the box (yet). @LekoArts (from the Gatsby team) has been working on a theme that should simplify this. Lennart, do you want to link to an alpha version of this when it's ready? In the mean time, check out his blog post at https://www.gatsbyjs.org/blog/2020-07-13-i18n-pain-points/

The package that Dan links to always seems helpful. Do try it out!

**Comment by LekoArts** [comment]
And do answer your question in the title. The `siteUrl` should be `www.mywebsite.com` and you'll need to set the current `lang` into the paths yourself or use such i18n plugins.
