### ISSUE TITLE
Build stuck on page queries despite not having any page queries

### ISSUE THREAD

**Issue by oskareke** [gatsbyjs/gatsby#25741]
I'm building a large Gatsby site and for performance reasons I'm passing all data through page context and not using any page queries. Despite this, as the number of pages increase, the build process get stuck at around 8% of the "Run page queries"-step. It goes very fast up to that point but then it just gets stuck. 
It's hard to know what's going on here, but since we don't have any page queries, is it be possible to disable this step?

**Comment by herecydev** [comment]
It would be best if you could provide a reproduction of the problem. https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

> and for performance reasons I'm passing all data through page context

That's not really a recommended approach as you will likely overfetch a lot of data if you're not careful and therefore have _worse_ performance
