### ISSUE TITLE
Pass React component as context within `createPages`

### ISSUE THREAD

**Issue by danoc** [gatsbyjs/gatsby#2574]
Hello, I'm building documentation for a React UI component library that can render live examples. Each component has its own page and all of those pages are built with the same template.

I'm able to render the examples if I `import` all of the components into the template file. This isn't ideal, however, because only only UI component is documented within a given page. (I believe tree-shaking in Gatsby 2/Webpack 3 will fix this? 🎉)

I explored passing in the appropriate React UI component through the `context` object in `createPage`, but that does not seem to accept components.

Is this correct? Would it make sense to be able to pass in React components through `context`?

(Would be happy to help improve the documentation if I'm missing something here! 😃)

**Comment by danoc** [comment]
I'm planning to work around this by wrapping `createPage` in a function that, given a component and template, would create a template for each component that includes the correct import.

**Comment by KyleAMathews** [comment]
@danoc yeah, that seems very reasonable. webpack unfortunately only understands code written to disk so there's several places in core we do similar stuff, writing out code to .cache.

**Comment by danoc** [comment]
Thanks, @KyleAMathews! Big fan of Gatsby. Thanks for all of the work!

**Comment by DekiGk** [comment]
@danoc Can you share your solution? Or maybe @KyleAMathews can link me to how it is done in core. I am having the same issue.

**Comment by danoc** [comment]
Hey @DekiGk, I think I used [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports) to only load the components that were needed on the page.

It's been a while since I worked on this, so I don't remember entirely.
