### ISSUE TITLE
Gatsby not showing 404 page when using Netlify _redirects /* /index.html 200

### ISSUE THREAD

**Issue by simerlec** [gatsbyjs/gatsby#25756]
## Description

Hello 👋  

I'm not 100% sure if this issue is strictly with Gatsby or not but maybe someone can give me some insight as to what is happening here.

We have a Gatsby site in production that's using a custom 404 page (like the one in the `gatsby-starter-default`). Now if we use it in combination with Netlify's recommended `_redirects` file (which consists of a single line `/* /index.html 200`, mentioned [here](https://www.netlify.com/blog/2020/04/07/creating-better-more-predictable-redirect-rules-for-spas/) and [here](https://www.netlify.com/blog/2019/01/16/redirect-rules-for-all-how-to-configure-redirects-for-your-static-site/)) and you navigate to a page that does not exists, the 404 page is not shown anymore but simply gets redirected to the root page.

### Steps to reproduce

I have provided a repo using the `gatsby-starter-default` and modified the build scripts to include the `_redirects` file in the build folder. So after you run `npm run build` simply navigate to the build folder `public` and start `netlify dev` (using the netlify cli) from there.

https://github.com/simerlec/gatsby-starter-default-with-netlify-redirects

### Expected result

Once you navigate to a page that does not exist the 404 page should be shown.

### Actual result

Once you navigate to a page that does not exist you get redirected to the root page.

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.3.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.24.2 => 2.24.2 
    gatsby-image: ^2.4.13 => 2.4.13 
    gatsby-plugin-manifest: ^2.4.18 => 2.4.18 
    gatsby-plugin-offline: ^3.2.17 => 3.2.17 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.19 => 2.6.19 
    gatsby-source-filesystem: ^2.3.19 => 2.3.19 
    gatsby-transformer-sharp: ^2.5.11 => 2.5.11 
  npmGlobalPackages:
    gatsby-cli: 2.12.60

Thank you for your time 🙏

**Comment by freiksenet** [comment]
You shouldn't need a manual redirect rule like this when using Gatsby with Netlify. Instead, you should use [`gatsby-plugin-netlify`](https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/) that will configure redirects for you. If you have a [client-side only route](https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/), then Gatsby will write a needed redirect for that, but you don't need a catch-all route like this with Gatsby.

**Comment by simerlec** [comment]
Thanks for the fast response @freiksenet - could you explain why the `catch-all route` does not work as I thought it would?
