### ISSUE TITLE
gatsby-image sources not prefixing properly

### ISSUE THREAD

**Issue by nicktouchette** [gatsbyjs/gatsby#25755]
## Description

When stopping the development server, and running a production build with pathPrefixes, the cache from the development build somehow prevents gatsby-images from being prefixed and vice versa.

Running `gatsby clean` before the build will result in properly prefixed gatsby-images.  However, returning to the development server will now have prefixed gatsby-images from the production build.  To fix this I have to run `gatsby clean` and then run `gatsby develop`.

Having to run `gatsby clean` every time I want to build/develop is time consuming when having to rebuild the entire cache.

### Steps to reproduce

https://github.com/nicktouchette/gatsby-bug-repro

After cloning and installing the repo.

Reproduction for broken gatsby-image in production build
1. `gatsby develop` to ensure both images load without a prefix.
2. `gatsby build --prefix-paths` or `yarn build`
3. `gatsby serve --prefix-paths` or `yarn serve` and browse to localhost:9000/prefix

Fixing the gatsby-image prefix in the production build
1. `gatsby clean`
2. `gatsby build --prefix-paths` or `yarn build`
3. `gatsby serve --prefix-paths` or `yarn serve` and browse to localhost:9000/prefix

Reproduction of broken gatsby-images in development
1. `gatsby develop` gatsby-image should still be prefixed, resulting in a broken image.

Fixing the gatsby-image prefix in development
1. `gatsby clean`
2. `gatsby develop` gatsby-image will not be prefixed

### Expected result

Both of the images should be prefixed with `/prefix` when serving with prefixPath, and when in development server, both images should not be prefixed.

### Actual result

The imported image has the correct prefix in both development and production, and the gatsby-image does not update until a cache is wiped.

### Environment

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.15.0/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12 
    gatsby-image: ^2.4.13 => 2.4.13 
    gatsby-plugin-sharp: ^2.6.19 => 2.6.19 
    gatsby-source-filesystem: ^2.3.19 => 2.3.19 
    gatsby-transformer-sharp: ^2.5.11 => 2.5.11

**Comment by im-adithya** [comment]
@LekoArts I am interested. Can you help me with this?

**Comment by henrikwirth** [comment]
I have the same issue. Every time I switch from develop to build (with prefix), I have to rebuild the cache with `gatsby clean` first. This is pretty time consuming.
