### ISSUE TITLE
Netlify Build Fails However locally builds successfully

### ISSUE THREAD

**Issue by amresha** [gatsbyjs/gatsby#25758]
## Summary
I am unable to deploy the site on Netlify as it gives build fail error however it builds successfully on the local machine.

## Relevant information
I am using gatsby with Netlify CMS,  the build error points to all components.
**My repository:** https://github.com/amresha/amresha-official.git

**Build Error:**

1:50:48 PM: error Generating development JavaScript bundle failed
1:50:48 PM: Can't resolve '../components/Gallery' in '/opt/build/repo/src/pages'
1:50:48 PM: If you're trying to use a package make sure that '../components/Gallery' is installed. If you're trying to use a local file make sure that the path is correct.
1:50:48 PM: error Generating development JavaScript bundle failed
1:50:48 PM: Can't resolve '../components/Mailchimp' in '/opt/build/repo/src/pages'
1:50:48 PM: If you're trying to use a package make sure that '../components/Mailchimp' is installed. If you're trying to use a local file make sure that the path is correct.
1:50:48 PM: error Generating development JavaScript bundle failed
1:50:48 PM: Can't resolve '../components/Mailchimp' in '/opt/build/repo/src/pages'
1:50:48 PM: If you're trying to use a package make sure that '../components/Mailchimp' is installed. If you're trying to use a local file make sure that the path is correct.
1:50:48 PM: error Generating development JavaScript bundle failed
1:50:48 PM: Can't resolve '../components/testinomials' in '/opt/build/repo/src/pages'
1:50:48 PM: If you're trying to use a package make sure that '../components/testinomials' is installed. If you're trying to use a local file make sure that the path is correct.
1:50:48 PM: error Generating development JavaScript bundle failed
1:50:48 PM: Can't resolve '../components/testinomials' in '/opt/build/repo/src/pages'
1:50:48 PM: If you're trying to use a package make sure that '../components/testinomials' is installed. If you're trying to use a local file make sure that the path is correct.
1:50:48 PM: failed Building development bundle - 15.639s

### Environment (if relevant)

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.3.25 => 2.23.3
    gatsby-image: ^2.0.39 => 2.4.7
    gatsby-plugin-feed-mdx: ^1.0.0 => 1.0.1
    gatsby-plugin-fontawesome-css: ^1.0.0 => 1.0.0
    gatsby-plugin-google-analytics: ^2.0.18 => 2.3.4
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2
    gatsby-plugin-manifest: ^2.0.29 => 2.4.11
    gatsby-plugin-material-ui: ^2.1.9 => 2.1.9
    gatsby-plugin-mdx: ^1.2.14 => 1.2.15
    gatsby-plugin-netlify-cms: ^4.0.0 => 4.3.5
    gatsby-plugin-offline: ^2.0.25 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.12 => 3.3.4
    gatsby-plugin-scss-typescript: ^4.0.12 => 4.0.12
    gatsby-plugin-sharp: ^2.0.35 => 2.6.11
    gatsby-plugin-styled-components: ^3.3.6 => 3.3.6
    gatsby-plugin-typography: ^2.2.13 => 2.5.4
    gatsby-remark-copy-linked-files: ^2.0.11 => 2.3.5
    gatsby-remark-images: ^3.3.9 => 3.3.10
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.4.5
    gatsby-remark-smartypants: ^2.0.9 => 2.3.4
    gatsby-remark-vscode: ^1.0.4 => 1.4.0
    gatsby-source-filesystem: ^2.0.29 => 2.3.11
    gatsby-transformer-sharp: ^2.1.18 => 2.5.5

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by freiksenet** [comment]
Hello @amresha!

I get the same error when I'm building your website locally. The problem is that you are using Mac OS as a development machine, and that has case insensitive filesystem, while Netlify uses Linux that has case sensitive filesystem. You should update your file names and imports so that they are consistent in casing.

**Comment by amresha** [comment]
> Hello @amresha!
> 
> I get the same error when I'm building your website locally. The problem is that you are using Mac OS as a development machine, and that has case insensitive filesystem, while Netlify uses Linux that has case sensitive filesystem. You should update your file names and imports so that they are consistent in casing.

Thanks a lot, @freiksenet for highlighting my mistake. I fixed those case sensitive issue and it successfully deployed now.
