### ISSUE TITLE
connecting nodes from different sources

### ISSUE THREAD

**Issue by brandonmp** [gatsbyjs/gatsby#2575]
I'm sure I'm missing this in the docs/google/issues search, but is there a way to connect nodes coming from different sources?

eg something like
```
type Note = {
  id: ID!,
  user: User
}
type User = {
  id: ID!,
  notes: [Note]
}
```
where `User` and `Note` come from separate JSONs via `plugin-source-filesystem` and `plugin-transformer-json`

I see [`createParentChildLink`](https://www.gatsbyjs.org/docs/bound-action-creators/#createParentChildLink), but I'm not sure that's it nor where to use it if it is.

**Comment by KyleAMathews** [comment]
Use [onCreateNode](https://www.gatsbyjs.org/docs/node-apis/#onCreateNode) and [createNodeField](https://www.gatsbyjs.org/docs/bound-action-creators/#createNodeField) to create the links.

Links are made by adding fields to nodes like `link___NODE: ID_OF_ANOTHER_NODE`. Or in your case do `notes___NODE: [ID1, ID2, ID3]`. After adding the link delete the old `notes` key as when Gatsby creates the GraphQL schema, it'll turn `notes___NODE` into just `notes`.

**Comment by Necmttn** [comment]
@KyleAMathews you should add this one in docs. :)

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by nextlevelshit** [comment]
> Use [onCreateNode](https://www.gatsbyjs.org/docs/node-apis/#onCreateNode) and [createNodeField](https://www.gatsbyjs.org/docs/bound-action-creators/#createNodeField) to create the links.
> 
> Links are made by adding fields to nodes like `link___NODE: ID_OF_ANOTHER_NODE`. Or in your case do `notes___NODE: [ID1, ID2, ID3]`. After adding the link delete the old `notes` key as when Gatsby creates the GraphQL schema, it'll turn `notes___NODE` into just `notes`.

To be honest, this is not super clear for me. Could someone provide an example, please?

**Comment by harrysolovay** [comment]
@KyleAMathews –– I'm digging into Gatsby & really loving it.

Running into an interesting roadblock relating to this issue. Was hoping you could weigh in.

My `sourceNodes` builds the connection between `post` and `author` MarkdownRemark nodes.

```js
createNodeField({
  node,
  name: "authors",
  value: authorNodes,
})
```

However, the `avatar` frontmatter field in the author node is reverted back to string form when referenced from within a post.

The following query...

```graphql
{
  allMarkdownRemark(filter: {fields: {category: {eq: "posts"}}}) {
    edges {
      node {
        fields {
          authors
        }
      }
    }
  }
}
```

Yields this data:

```json
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "fields": {
              "authors": [
                "0dc758f4-4641-5adc-87b9-0d20225e19e3"
              ]
            }
          }
        },
        {
          "node": {
            "fields": {
              "authors": [
                "0dc758f4-4641-5adc-87b9-0d20225e19e3"
              ]
            }
          }
        }
      ]
    }
  }
}
```

 (the relative file path... not the transformed `gatsby-remark-copy-linked-file`/`gatsby-remark-images` node)

Do you know of a way that I could preserve the transformations made by the plugins?

Any help would be greatly appreciated. THANK YOU!

**Comment by Brettm12345** [comment]
@KyleAMathews No idea you could link an array of IDs this is a game changer. Thank you so much
