### ISSUE TITLE
Generating SSR bundle failed Missing external configuration for type:commonjs2

### ISSUE THREAD

**Issue by verlekar-viraj** [gatsbyjs/gatsby#25760]
## Description
Getting the following error while using `gatsby-plugin-react-native-web` plugin & `gatsby` with `expo`

ERROR #98123  WEBPACK
Generating SSR bundle failed
Missing external configuration for type:commonjs2
error Command failed with exit code 1.

### Steps to reproduce

->clone https://github.com/expo/examples.git
->go to the root & then run the following commands
cd with-gatsby/
yarn install
yarn gatsby develop

Reference: https://github.com/expo/examples/tree/master/with-gatsby

### Expected result

Expected server start

### Actual result

Generating SSR bundle failed error thrown

### Environment

  System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 14.2.0 - /tmp/yarn--1594813578561-0.30698502797906935/node
    Yarn: 1.21.1 - /tmp/yarn--1594813578561-0.30698502797906935/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 72.0.2
  npmPackages:
    gatsby: ^2.17.6 => 2.24.2
    gatsby-image: ^2.2.30 => 2.4.13
    gatsby-plugin-manifest: ^2.2.25 => 2.4.18
    gatsby-plugin-offline: ^3.0.17 => 3.2.17
    gatsby-plugin-react-helmet: ^3.1.13 => 3.3.10
    gatsby-plugin-react-native-web: ^3.0.0-beta.1 => 3.1.0
    gatsby-plugin-sharp: ^2.2.34 => 2.6.19
    gatsby-plugin-typescript: ^2.1.15 => 2.4.14
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-source-filesystem: ^2.1.35 => 2.3.19
    gatsby-transformer-sharp: ^2.3.1 => 2.5.11

**Comment by wardpeet** [comment]
Hey,

This seems like an issue with [gatsby-plugin-react-native-web](https://github.com/slorber/gatsby-plugin-react-native-web) please create your issue on that repository.

If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby 💪
