### ISSUE TITLE
Missing documentation for gatsby-plugin-sass

### ISSUE THREAD

**Issue by mubaraqwahab** [gatsbyjs/gatsby#25775]
## Summary

The documentation for `gatsby-plugin-sass` is missing in the [website](https://www.gatsbyjs.org/packages/gatsby-plugin-sass/?=). See the screenshot:

![image](https://user-images.githubusercontent.com/48601635/87576949-06eb5180-c6ca-11ea-88c0-edc16a8fbeb9.png)

However, the README exists [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sass).

Can I take this issue up :blush:? I don't know where to fix it though.

Thanks!

**Comment by LekoArts** [comment]
Thanks for the issue! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/24137
