### ISSUE TITLE
[build] error collection  

### ISSUE THREAD

**Issue by arthurlogilab** [gatsbyjs/gatsby#25789]
## Summary

What is the recommended way of collecting build errors when using gatsby ? We're using continuous build and delivery with `gatsby build` and we've tried looking into gatsby + sentry but the plugins seems to be for front-end error collection only. 

Right now we're using `sentry-cli` to send the build logs like : 

```
if gatsby build --no-colors | tee /tmp/build.log ; then
  echo "Build finished."
else
  echo "Build failed."
  sentry-cli send-event -m "Build failed" --logfile /tmp/build.log
fi
```
This is not ideal as it doesn't extract the relevant bits and we have to scroll through the log as a plain text information.

**Comment by ascorbic** [comment]
Hi. If you set the env var `GATSBY_LOGGER` to "json" then you will get the logs in JSON format, which should be easier to parse.
