### ISSUE TITLE
Better document default props for gatsby-image

### ISSUE THREAD

**Issue by Floriferous** [gatsbyjs/gatsby#25786]
Several props from Gatbsy-image are missing default props. Sometimes it's mentioned at the end of the description, sometimes it isn't, and you're left to find that out by yourself.

It'd be really helpful if the props table simply had an additional column that mentions the default prop value!

**Comment by polarathene** [comment]
Perhaps a good idea to list those props here and their defaults too :)

I have added documentation for some base64 features that previously weren't in the docs so I doubt anyone else knew they even existed, but that PR is waiting on being merged.
