### ISSUE TITLE
gatsby-emotion-plugin and Redux don't work together on production builds

### ISSUE THREAD

**Issue by eladams** [gatsbyjs/gatsby#2578]
Getting the following error when the build is on the HTML build stage:
`WebpackError: Could not find "store" in either the context or props of "Connect(DefaultLayout)"`

**Comment by fk** [comment]
Hi @eladams! I didn't play around with neither emotion nor Redux (and Gatsby), but https://gatsbythemes.com/blog/how-to-use-redux-and-emotion-in-gatsby might help.

**Comment by m-allanson** [comment]
Gatsby should now warn you when you run into issues like this - see #2005 and #3889.
