### ISSUE TITLE
Add slug for all models

### ISSUE THREAD

**Issue by laurieontech** [gatsbyjs/gatsby#25799]
PR #25726 introduced slug directly in `gatsby-plugin-mdx`. Ideally, we'd be able to abstract this code to cover remark and other use cases. This will allow us to remove the MDX specific code and unlock this default field for all File based pages.

**Comment by KyleAMathews** [comment]
On avoiding conflicting with `slug` already being defined in say a node type created by `gatsby-transformer-json` (the json file might already have a slug field) — we could name the auto-generated slug `filepathSlug` — this makes it clear too where it comes from so would be less confusing in case it's not needed by someone.

**Comment by KyleAMathews** [comment]
@connorlindsey @LinnJS interested in picking this up?

**Comment by connorlindsey** [comment]
@KyleAMathews I'd be happy to pick it up!

**Comment by KyleAMathews** [comment]
Awesome thanks! This is a perfectly complement to the work on the new
routing APIs so it'll be great to get it in.

--
Kyle Mathews

Blog: *http://bricolage.io <http://bricolage.io>*
Twitter: http://twitter.com/kylemathews

**Comment by connorlindsey** [comment]
@laurieontech Hi, I had a few questions

Where should the `filepathSlug` be implemented/added? It seems like adding `filepathSlug` to `gatsby-plugin-filesystem/create-file-node.js` would work. Not sure if there is another plugin it should be implemented in or if it should be added as a util somewhere. 

What file types should be supported or should it be added to all File types? I assume the path would only be useful on html, md, and mdx (might be missing some uses cases), but I also don't think there's any harm in just adding it to all File types. 

Thanks!

**Comment by laurieontech** [comment]
Thanks for the interest in picking this up @connorlindsey! That's part of why this issue is vague. There isn't a clear direction for where we'd want to do this and what the behavior should be. I'll let @KyleAMathews chime in since I know he had some ideas.

**Comment by KyleAMathews** [comment]
The best way to do this would be to build it into core — automatically add the field to Nodes which are created from File like MarkdownRemark, MDX, JSON/YAML nodes etc. — that'll be trickier to figure out and land though — so what I'd do is take what @laurieontech did and turn it into a utility library (perhaps in `gatsby-core-utils`) which we add directly to different transformers — then later, assuming the pattern is working well, we move it to core.

How's that sound @laurieontech / @pieh?

**Comment by laurieontech** [comment]
Seems reasonable to me.
