### ISSUE TITLE
Use  404 status code for 404 pages in development

### ISSUE THREAD

**Issue by mixtur** [gatsbyjs/gatsby#25794]
## Description

Currently 404 page is served on a dev server with the status code 200.

### Expected result

I would expect it to be 404.

**Comment by mixtur** [comment]
It may be a problem when using a reverse proxy upstreaming to the gatsby dev server and falling back to some other server.
In that case the fallback is never triggered.

**Comment by KyleAMathews** [comment]
BTW, this has been fixed with DEV_SSR https://github.com/gatsbyjs/gatsby/discussions/28138
