### ISSUE TITLE
Sometimes some fields are missing when querying data.

### ISSUE THREAD

**Issue by ronihcohen** [gatsbyjs/gatsby#25807]
I'm not sure if It's a bug or am I missing something?
![image](https://user-images.githubusercontent.com/3350618/87771691-657b1180-c829-11ea-8e9e-ebf3e7b3873b.png)
Some fields are missing
But I'm sure the query is fine:
![image](https://user-images.githubusercontent.com/3350618/87771721-6e6be300-c829-11ea-88db-073f5f5a869b.png)

I'm pretty sure I'm using the right slug,
here is my gatsby-node.js:

```

exports.onCreateNode = ({ node, getNode, actions }) => {
    const { createNodeField } = actions
    if (node.internal.type === `CoffeeJson`) {
        const slug = `beans/${node.kebabName}`
        createNodeField({
            node,
            name: `slug`,
            value: slug,
        })
    }
}

exports.createPages = async function ({ actions, graphql }) {
    const { data } = await graphql(`
      query {
        allCoffeeJson {
            edges {
                node {
                    fields {
                        slug
                    }
                }
            }
        }
      }
    `)
    data.allCoffeeJson.edges.forEach(edge => {
        const slug = edge.node.fields.slug
        actions.createPage({
            path: slug,
            component: require.resolve(`./src/templates/beans.js`),
            context: { slug: slug },
        })
    })
}
```

Thanks!

**Comment by pieh** [comment]
This sure looks like a bug, but I can't reproduce it (there likely is specific setup that cause issues like that). Does the chrome dev tools screenshot come from `gatsby develop` runtime? Do you know what curse of action triggers this? Also - can you share your project if this happen regularly there?

Additionally - there are some known problematic plugins that cause problems for hot data updates (like `gatsby-plugin-transition-link` in https://github.com/gatsbyjs/gatsby/issues/23622 / https://github.com/TylerBarnes/gatsby-plugin-transition-link/issues/131), so this might be similar case here.

**Comment by ronihcohen** [comment]
Yes, the screenshot is from `gatsby develop`, my repo is public and here is my config file: https://github.com/ronihcohen/coffee-crawler/blob/master/gatsby-config.js.

I'll check if it happens on prod.

**Comment by ronihcohen** [comment]
Looks like it happens only on develop.

**Comment by vladar** [comment]
@ronihcohen The link is 404 for me. Is it a public project? We still need a way to reproduce it to move forward with this.

**Comment by ronihcohen** [comment]
Closing the issue for now
