### ISSUE TITLE
Upgrade eslint to prevent auto-fix from autofilling deps

### ISSUE THREAD

**Issue by theskillwithin** [gatsbyjs/gatsby#25804]
In the version of eslint gatsby currently uses, it auto-fixes react hooks exhaustive deps.

This causes problems when someone unfamiliar attempts to edit component with a hook and it auto-fills deps, then causes infinite loop.

of course you can put `// eslint-disable-next-line react-hooks/exhaustive-deps`  but this is impractical if you have multiple gatsby projects to do this manually on after upgrading.

the most recent version of eslint fix does not auto fix this anymore due to this problem

**Comment by pieh** [comment]
Are you sure that it's Gatsby that does it? Eslint that comes with `gatsby` is used for `eslint-loader` and it doesn't have autofix enabled. I need more details here, because I can't reproduce auto-fixing in my sample project - can you share your setup?

**Comment by theskillwithin** [comment]
Sorry! never mind

it's because I have VSCode set to `"eslint.autoFixOnSave": true,`

and also VSCode is using the eslint from the node_modules so thats why I didn't notice on other projects
