### ISSUE TITLE
Wrap apps in StrictMode in develop

### ISSUE THREAD

**Issue by blainekasten** [gatsbyjs/gatsby#25813]
## Summary

Opening this for discussion. From a recent conversation with @gaearon, he requested that we turn on StrictMode for gatsby users. React has a lot of major changes in the next 1-2 years and StrictMode is the pressure to get the community to update from legacy patterns that will be breaking in future React updates.

**Proposal:** Gatsby wraps apps in develop mode with `StrictMode` and have a configuration that can disable it. But it would be opt-out.  

### Motivation

Gatsby is an important member of the React ecosystem and we have the opportunity to do "right" by supporting the maintainers and the community to encourage that pressure to transition away from legacy APIs and patterns.

### Discussion

I'd like to discuss a few things in this issue:

1. Are we happy to make this change? It might be contentious and disrupt some users _marginally._
1. Can we ship this now or should it be part of the next major?
1. What would be the costs/risks/negative consequences?

**Comment by danabrit** [comment]
I would add to the list of questions to discuss:

3. What would be the costs/risks/negative consequences?

**Comment by herecydev** [comment]
✔ Develop mode only, doesn't impact production
✔ Only issues logs (AFAIK), so minimally disruptive
✔ Leads users to better practices (less tickets for the long term)
✔ Easier migration to future React versions, providing users follow the advice
❌ Will generate some initial influx of "I've started getting this warning"

I think it's an easy go ahead from me! The only negative of incoming bug tickets offsets the same amount when a new React version is released that "breaks things" for the same users. This can also be mitigated with some pinned issues, guidance, etc.

I would however disagree with the opt-out switch, out of fear that it's a tempting choice to hide the warnings. If it's released as a minor `2.25.X` then there's at least a choice and a path back
