### ISSUE TITLE
Gatsby Query Not Removed During Compile

### ISSUE THREAD

**Issue by jarodpeachey** [gatsbyjs/gatsby#25817]
m creating two NPM packages for Gatsby. One of these is a source plugin, and the other includes a JSX component that grabs data from GraphQL to be imported as a component by the end user.

However, the static query for the latter component fails with an error.

Error: It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away. Unfortunately, something went wrong and the query was left in the compiled code.
Steps to reproduce
Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue much easier to diagnose (seriously).

Go to https://github.com/jarodpeachey/netlify-comments and clone the repo
Run yarn install
Run lerna link and lerna bootstrap
cd packages/netlify-comments
npm run compile
cd ../gatsby-demo
npm start
Expected result
The component located at packages/netlify-comments/src/Comments.js should build properly.

Actual result
The static query fails and the component does not build.

Environment
System:
OS: Windows 10 10.0.19041
CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Binaries:
Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
Languages:
Python: 3.7.4 - /c/Users/Able Family Life/AppData/Local/Programs/Python/Python37-32/python
Browsers:
Edge: 44.19041.1.0

**Comment by sidharthachatterjee** [comment]
This is known behaviour (that is unfortunately undocumented at the moment Cc @AishaBlake) 

We only extract gatsby GraphQL queries from packages that include the `gatsby` in their name. Renaming `netlify-comments` to `gatsby-netlify-comments` should fix this. Thanks!

**Comment by jarodpeachey** [comment]
Hey @sidharthachatterjee I've renamed the package to `gatsby-plugin-netlify-comments`, and it still gives the error.

This is my .babelrc file:

```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "babel-plugin-styled-components",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-transform-runtime",
    "babel-plugin-macros",
    "babel-plugin-transform-react-remove-prop-types",
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-optional-chaining",
    "babel-plugin-optimize-hook-destructuring"
  ]
}
```

**Comment by stevemarksd** [comment]
IM also having this issue

**Comment by iDVB** [comment]
@sidharthachatterjee Is there any way to force this for specifically named packages? We have this same issue but our package is an internal UI library that we do not want prefixed with `gatbsy-`.
