### ISSUE TITLE
Incorrect scroll top position when navigating between pages (part 2)

### ISSUE THREAD

**Issue by josephmarkus** [gatsbyjs/gatsby#25814]
## Description

After upgrading from `gatsby@2.20.26` to `gatsby@2.24.3` I noticed an issue where navigating within the app sets incorrect scroll top position.

_NOTE:_
- this has been recently addressed by @blainekasten here - https://github.com/gatsbyjs/gatsby/pull/25749
- related issue - https://github.com/gatsbyjs/gatsby/issues/25745

### Steps to reproduce

For the following to work, we'll assume a pretty standard website structure:
- homepage and another page
- header with a link to the homepage on the logo
- footer with a link

_This is for illustration purposes only. Other reproduction scenarios are possible_

1. Make sure you have latest version of gatsby installed - `gatsby@2.24.3`
2. Run `gatsby develop`
3. From your homepage, click on a link that isn't at the very top of the page (e.g. your site's footer). You can check this in your DevTools console by logging out `window.scrollY`. As long as it's more than `0` then you're good.
4. Once you navigate to a new page, click on a link back to the homepage in your header.
5. Observe scroll position of the homepage. The scrollTop position is not at `0` (you can verify as detailed in step 3)

### Expected result

After navigating `homepage -> another page -> homepage` scrollTop value should be 0

### Actual result

Application remembers page scroll position of a previously visited page. This could come in handy if user clicks 'Back' in the browser, but this would be unexpected if user clicks to navigate to a page via direct link.

### Environment

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Safari: 13.1.2
  npmPackages:
    gatsby: 2.24.3 => 2.24.3
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ~2.4.12 => 2.4.12
    gatsby-plugin-catch-links: ~2.3.10 => 2.3.10
    gatsby-plugin-emotion: ~2.0.5 => 2.0.7
    gatsby-plugin-favicon: ~3.1.5 => 3.1.6
    gatsby-plugin-google-gtag: ~2.1.9 => 2.1.9
    gatsby-plugin-manifest: ~2.4.17 => 2.4.17
    gatsby-plugin-mdx: ^1.2.22 => 1.2.22
    gatsby-plugin-postcss: ~2.3.9 => 2.3.9
    gatsby-plugin-react-helmet: ~3.3.9 => 3.3.9
    gatsby-plugin-remove-generator: ^1.0.5 => 1.0.5
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ~1.5.1 => 1.5.1
    gatsby-plugin-root-import: ~2.0.5 => 2.0.5
    gatsby-plugin-sharp: ~2.6.18 => 2.6.18
    gatsby-plugin-sitemap: ~2.4.10 => 2.4.10
    gatsby-remark-autolink-headers: ^2.3.10 => 2.3.10
    gatsby-remark-copy-linked-files: ^2.3.10 => 2.3.10
    gatsby-remark-external-links: ~0.0.4 => 0.0.4
    gatsby-remark-images: ~3.3.17 => 3.3.17
    gatsby-remark-relative-images: ^0.2.2 => 0.2.3
    gatsby-remark-responsive-iframe: ~2.4.10 => 2.4.10
    gatsby-source-filesystem: ~2.3.18 => 2.3.18
    gatsby-source-youtube-v2: ^1.0.1 => 1.0.1
    gatsby-transformer-remark: ^2.8.23 => 2.8.23
    gatsby-transformer-sharp: ~2.5.10 => 2.5.10
  npmGlobalPackages:
    gatsby-cli: 2.12.59
```

**Comment by blainekasten** [comment]
@josephmarkus I just tested this and couldn't get it to reproduce. Could you create a minimal reproduction and send me the repo to test with?

**Comment by josephmarkus** [comment]
Sure thing, let me put something together

**Comment by josephmarkus** [comment]
I converted a MOV to GIF and it's super slow, but here's the outline:
- first time navigating from home to another page and back is ok as I click on a particular link
- second time navigating from home to another page and back isn't okay as I use back navigation

![ezgif com-resize](https://user-images.githubusercontent.com/9258365/88082513-c718e400-cb79-11ea-98a0-655657686e6c.gif)

I created a repo through `gatsby new` and then bumped all packages to latest: https://github.com/josephmarkus/scroll-position-bug/blob/master/package.json

**Comment by micha149** [comment]
@josephmarkus your repository doesn't exist anymore?!

**Comment by josephmarkus** [comment]
@micha149 there was no response, so I assumed that this wasn't of interest to the requester

**Comment by micha149** [comment]
Is there is still a problem with the latest release? I have other issues with scroll position when using the `useScrollRestoration` hook in a Layout component, but the basic functionality looks fine I think.
