### ISSUE TITLE
Reorder Images, Files, & Video sidebar items

### ISSUE THREAD

**Issue by AishaBlake** [gatsbyjs/gatsby#25829]
## Summary

This suggestion came out of an internal docs office hours session. The fact that using Gatsby Image isn't listed first under the "[working with images](https://www.gatsbyjs.org/docs/images-and-files/)" section in the docs may be confusing to some users. We want people to use Gatsby Image whenever possible, so that should be listed first.

### Motivation

More generally, when there is a preferred (or "more Gatsby") way to do things, that should be clear in the documentation. There's more to be done to make Gatsby Image easier to use, especially for new Gatsby devs. This issue is meant to be a  "quick win" and to provide a low-pressure opportunity for a new contributor to tackle.

### Make the change

- [ ] Change the order of the pages in `doc-links.yaml`
  - "Working with Images in Gatsby" should be first, then "Using gatsby-image"

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #25829" in the pull request description

**Comment by Neilblaze** [comment]
Assign me this task please @AishaBlake

**Comment by Neilblaze** [comment]
@AishaBlake please review the PR
