### ISSUE TITLE
Change highlight colour to something other than red

### ISSUE THREAD

**Issue by maraisr** [gatsbyjs/gatsby#25836]
## Summary

Western culture tends to associate red with negative intent (eg, GIT diff's), so reading the code blocks I'm unsure if the highlighted code is something I should remove, or add.

### Motivation

I believe that if the highlighted code in the code blocks was something more of a green to indicate add—or quite simply a blue, white or even the brand purple that it'll be more clear what I'm needing to do.

For example take a look at this screenshot.

![image](https://user-images.githubusercontent.com/599459/87848085-3abfb480-c920-11ea-99fd-e6f1c0647ac1.png)

As a developer I tend to quickly scan code blocks, and upon first glance it looks like I need to remove the plugin from my config... Then my intuition tells me "but if I want to add the plugin, surely I need to add it"... So I then read the surrounding context only to then read the "add it to the config" line above. Making it a lot slower to read the docs. It truly trips me up sometimes 👀 

Granted this is a very subjective opinion. Just opening this in hopes someone might share this view.

## Steps to resolve this issue

As denoted above; would be awesome for the highlight colour to be more of a neutral colour.

### Draft the doc

Perhaps this section is mute?

### Open a pull request

I would gladly open a PR for this; just wanting to get some opinions from the maintainers first!

**Comment by fk** [comment]
Hey @maraisr! Welcome, and thanks for raising this issue! 🤗 🙏 

I think you def. have a point — the highlight color shouldn't ever raise these questions or implicitly communicate whether the highlighted parts should be added, or removed — they should highlight.

The latter — us using these to (also) just highlight things — not only additions to the code in regards to a previous step/code snippet — IMO green is out.

Maybe an easy way to mock up a few color combinations (maybe orange-ish?) is using the developer console? Also super happy to look at a PR!

**Comment by AishaBlake** [comment]
We should definitely try to reduce confusion where we can! The highlight already looks more orange to me than red and I'm assuming that's expected but I'd love to see if we can come up with a solution that works for even more people.

@maraisr, for the sake of clarity, everything under "Steps to resolve this issue" in the issue template are meant for you to fill in for the benefit for whoever takes the issue up. You don't have to submit the PR if you'd prefer not to or don't have the time. (I may need to revisit that text!) If you're willing, you're welcome to work on it as far as I'm concerned.
