### ISSUE TITLE
Bootstrap boilerplate for existing project

### ISSUE THREAD

**Issue by sanketpath** [gatsbyjs/gatsby#25835]
Hola! 👋 

I'm learning GatsbyJS and developing my portfolio + blog website from the scratch (used gatsby starter pack from tutorials). I want to use Bootstrap CSS framework going forward. Is it possible to use it? If yes, how do install it in my [existing project](https://github.com/sanketpath/gatsby-learn)?

**Comment by koji** [comment]
This repo might be useful for you.
https://github.com/jaxx2104/gatsby-starter-bootstrap

**Comment by sanketpath** [comment]
@koji Thank you! That was really helpful. I do have a follow-up question. I've installed [react-bootstrap](https://react-bootstrap.github.io/) in my project and it's overriding all the existing styling done via custom css and typography.js. Is there any way to fix this? Anything I need to mention in config file under bootstrap settings to use certain fonts and colors?

**Comment by koji** [comment]
Did you apply to your custom css via class/id to your components?

**Comment by sanketpath** [comment]
Yes, via Class and defined under global.css file.

**Comment by koji** [comment]
So you do something like below?

```js
import Button from 'react-bootstrap/Button';
import './custom.css';

or importing 

const Test = () => {
  return(
    <Button
      variant="primary"
      className="myBtn"
	>
      Click Me
    </Button>
  )
}
```

**Comment by LekoArts** [comment]
Thank you for opening this!

You can have a look at the starters to see how to implement Bootstrap: https://www.gatsbyjs.org/starters/?c=Styling%3ABootstrap&v=2

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
