### ISSUE TITLE
Gatsby Develop not working on IE11

### ISSUE THREAD

**Issue by BenRauzi** [gatsbyjs/gatsby#25848]
Site works fine when built in production. When in development get this error:

![image](https://user-images.githubusercontent.com/46276310/87863426-f5969380-c9ae-11ea-866b-d21b7c9f591b.png)

Which points to this:

```
const { hot } = __webpack_require__(/*! react-hot-loader/root */ "./node_modules/react-hot-loader/root.js")
```

Any ideas? Have looked over previous similar issues but cannot seem to resolve it.

What should happen?

Page should load

What happened.

White screen

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.2
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.22.22 => 2.24.3
    gatsby-image: ^2.4.0 => 2.4.0
    gatsby-plugin-google-analytics: ^2.2.4 => 2.2.4
    gatsby-plugin-manifest: ^2.4.0 => 2.4.0
    gatsby-plugin-netlify-cms: ^4.3.0 => 4.3.0
    gatsby-plugin-offline: ^3.1.4 => 3.1.4
    gatsby-plugin-react-helmet: ^3.2.4 => 3.2.4
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^2.2.3 => 2.2.3
    gatsby-plugin-sharp: ^2.6.0 => 2.6.0
    gatsby-source-filesystem: ^2.3.0 => 2.3.0
    gatsby-transformer-json: ^2.3.1 => 2.3.1
    gatsby-transformer-sharp: ^2.4.4 => 2.4.4
  npmGlobalPackages:
    gatsby-cli: 2.12.5
```

**Comment by TimFletcher** [comment]
Yeah, same issue here. :(

**Comment by ar5had** [comment]
same here..

**Comment by gustaflindqvist** [comment]
I getting type error with regex within `common.js`. Could be connected to this issue. 

Going to look into the code more that being generated.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
