### ISSUE TITLE
Array.from()  WebpackError: TypeError

### ISSUE THREAD

**Issue by Vsplorer** [gatsbyjs/gatsby#25856]
**Hello everyone, I am a beginner of Gatsby and learning framer motion recent. When I try to deploy a gatsby site to Github page, an error was occurring:**

`success Rewriting compilation hashes - 0.004s
failed Building static HTML for pages - 0.822s

 ERROR #95313 

Building static HTML failed for path "/index/hero/"

See our docs page for more info on this error: https://gatsby.dev/debug-html

  12 |     const { text, adjust } = this.props
  13 | 
> 14 |     const string = Array.from(text)
     |                          ^
  15 |     const containerVariants = {
  16 |       before: {},
  17 |       after: { transition: { staggerChildren: 0.04, delayChildren: 0 } },

  WebpackError: TypeError: Cannot convert undefined or null to object`

`the origin code is below:`

`import React from "react"
import { motion } from "framer-motion"

import "./hero.css"

function Hero(props) {
  const { text, adjust } = props
  const string = Array.from(text)
  const containerVariants = {
    before: {},
    after: { transition: { staggerChildren: 0.04, delayChildren: 0 } },
  }
  const letterVariants = {
    before: {
      opacity: 0,
      y: 200,
      transition: {
        ease: [0.77, 0, 0.175, 1],
        duration: 0.6,
      },
    },
    after: {
      opacity: 1,
      y: 0,
      transition: {
        ease: [0.77, 0, 0.175, 1],
        duration: adjust,
      },
    },
  }

  return (
    <div>
      <motion.div
        className="title-field"
        variants={containerVariants}
        initial={"before"}
        animate={"after"}
      >
        {string.map((l, i) => (
          <motion.div className="title-body" key={i} variants={letterVariants}>
            {l === " " ? "\u00A0" : l}
          </motion.div>
        ))}
      </motion.div>
    </div>
  )
}

export default Hero
`

I have not found any solution yet. So anyone can help me?

**Comment by herecydev** [comment]
> Cannot convert undefined or null to object

The error is pointing out that something is either null or undefined. Probably your `text` prop

**Comment by sidharthachatterjee** [comment]
@Vsplorer Marking this as answered and closing this since it's user error! Feel free to comment or reopen if there is more we can help with 🙂
