### ISSUE TITLE
Search engines crawl duplicate pages

### ISSUE THREAD

**Issue by ergunpp** [gatsbyjs/gatsby#25871]
Hi,
My published site has been crawled twice for each page on my website. Once for the path; and again for the path+index.html.

How can I avoid this?
I am using Gatsby-plugin-robots and Gatsby-plugin-sitemap.

Thanks for the help!

**Comment by flikteoh** [comment]
Did you add canonical tag for your pages?

**Comment by ergunpp** [comment]
No I did not. Do I have to add it to the helmet for each page?

**Comment by flikteoh** [comment]
It's a good practice to setup canonical url to prevent content duplication.

Especially if you have contents that are reachable from multiple URLs.

I suggested you to read up about it here: [Canonical URL](https://support.google.com/webmasters/answer/139066?hl=en)

Gatsby do comes with features that allows you to programmatically setup [canonical URL](https://www.gatsbyjs.org/tutorial/seo-and-social-sharing-cards-tutorial/#link-relcanonical) in your pages.

Additionally, it depends also on the hosting platform you're working on, you may want to have a proper redirection or learn how it works.

For example: the URLs you've mentioned with /folder/index.html should usually end up as /folder/ without the file name. If it didn't end up that way, you may want find out how that should be done as well.

**Comment by ediblecode** [comment]
To follow up on @flikteoh's excellent answer, we used the 301 redirect technique in a [_.htaccess_ file](https://httpd.apache.org/docs/2.4/howto/htaccess.html), which you might be able to use depending on where/how you're hosting the app. For example:

https://github.com/nice-digital/cks-gatsby/blob/d40489b41c727d07c57a20862b861a7daf513be9/gatsby/static/.htaccess#L5-L6
