### ISSUE TITLE
Creating node links on custom union type fields

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#2587]
I'm using Gatsby to create a site from an API. I've written a source plugin to map the API responses into Gatsby. This is working excellently! Now I'd like to download all remote images that are referenced in the API responses, so I can hook into Gatsby's neat image optimisation flow.

I've got the images being downloaded and file nodes being created, but I'm having some trouble linking the local File nodes to the API nodes that I'm creating.

A little background on the setup - the data is structured similarly to https://github.com/gatsbyjs/gatsby/issues/2307 - I have `articles` which each contain a `blocks` field, and `blocks` is an array of various different types of content.

So far, so good. I've used the `setFieldsOnGraphQLNodeType` hook to create a union GraphQL type.
<details>
  <summary>Expand to see example code:</summary>

```js
const customBlockType = (name, description, contentFields) => {
  return new GraphQLObjectType({
    name,
    description,
    fields: () => {
      return {
        type: { type: GraphQLString, description: `The type of block` },
        content: {
          type: new GraphQLObjectType({
            name: `${name}Content`,
            description: `The content specific to this type of block`,
            fields: () => contentFields
          })
        }
      };
    }
  });
};

const ImageBlockType = customBlockType(
  `ImageBlock`,
  `A block with a single image`,
  {
    image: { type: GraphQLString }
  }
);

// More block types, then...

const BlockType = new GraphQLUnionType({
  name: "BlockType",
  types: [
    ChartBlockType,
    QuoteBlockType,
    ImageBlockType
    // more block types...
  ],

  resolveType: resolveType
});

exports.default = ({ type }) => {
  if (type.name === `ArticleNode`) {
    return { blocks: { type: new GraphQLList(BlockType) } };
  }
  return {};
};
``` 
</details>

The data for an image block will look like this:

```js
{
  type: "image",
  content: {
    image: "http://example.com/example-image.jpg"
  }
}
```

What I'd like to do is download these remote images so they can be processed by Gatsby. I've tried following [the example of the wordpress source plugin](https://github.com/gatsbyjs/gatsby/blob/ddbf5887a73e73112ae6b5728fdc6ef33a63b133/packages/gatsby-source-wordpress/src/normalize.js#L323). 

<details>
<summary>Expand for more example code:</summary>

```js
article.blocks = await Promise.all(
  blocks.map(async block => {
    if (block.type === "image") {
      let fileNode;
      try {
        fileNode = await createRemoteFileNode({
          // url: block.content.image,
          url: "http://via.placeholder.com/350x150.jpg",
          store,
          cache,
          createNode
        });
      } catch (e) {
        // Ignore
      }
      if (fileNode) {
        block.content.image___NODE = fileNode.id;
        delete block.content.image;
      }
    }
    return block;
  })
);

return article
```

</details>

With the changes above running as part of my `sourceNodes` hook, I can see that the image files get downloaded to `.cache/gatsby-source-filesystem`, but when I query the data `block[n]content.image` is `null`.

Example query: 

```graphql
fragment ArticleFieldsFragment on ArticleNode {
    id
    title
    # more fields..
    blocks {
      ... on ImageBlock {
        type
        content {
          image # this will be null
        }
      }
      # more block types
    }
  }
```

I'm guessing that each `block.content.image___NODE` is not being linked because that field is not described in my GraphQL Union type. And because I've manually specified the types for ImageBlock, Gatsby's normal type inference isn't happening?

That's just a guess though, maybe something else is preventing the node from being linked. Note that the file nodes _do_ show up in `allFile {}` queries, they're just not attached to the `article.blocks[x].content.image` field.

After all that (thanks for reading) I have a few questions:

- Can I link the file node to a nested field when using custom union types as described above? 
- Is this even the right approach for doing this? Maybe the linking should be done as a transform plugin? Or some other way?

**Comment by KyleAMathews** [comment]
Two questions:

* Are blocks separate nodes?
* If you link to a file node at a top-level field does that make a difference?

**Comment by m-allanson** [comment]
> Are blocks separate nodes?

Blocks are not separate nodes, they're just fields on the article node

> If you link to a file node at a top-level field does that make a difference?

Yep, linking to a file node at the top level of the article node works as expected. 

If I link the file nodes to both `article.localImage` and `article.blocks.[x].content.localImage` in my `sourceNodes` hook like this:

```js
if (fileNode) {
  article.localImage___NODE = fileNode.id;
  block.content.localImage___NODE = fileNode.id; 
}
```

Then a query like this:
```graphql
{
  allArticleNode {
    edges {
      node {
        id
        title
        excerpt
        localImage {
          sourceInstanceName
          relativePath
          birthTime
          internal{
            type
            owner
            mediaType
          }
        }
        blocks {
          ... on ImageBlock {
            type
            content {
              image
              localImage
            }
          }
        }
      }
    }
  }
}
```

Will output results like this:

```js

{
  "data": {
    "allArticleNode": {
      "edges": [
        {
          "node": {
            "id": "59cb9ad7-a101-518c-b028-158a1e9f7b35",
            "title": "Foo",
            "excerpt": "bar",
            "localImage": {
              "sourceInstanceName": "__PROGRAMATTIC__",
              "relativePath": ".cache/gatsby-source-filesystem/c4f9489ce0d146c3b47e5fcdc4fa16b3.jpg",
              "birthTime": "2017-10-23T09:02:10.000Z",
              "internal": {
                "type": "File",
                "owner": "gatsby-source-filesystem",
                "mediaType": "image/jpeg"
              }
            },
            "blocks": [
              {},
              {
                "type": "image",
                "content": {
                  "image": "/media/original_images/baz.png",
                  "localImage": null
                }
              },
              {},
              {},
              {}
            ]
          }
        }
        # other results.. 
      ]
    }
  }
}
```

**Comment by KyleAMathews** [comment]
Ah ok, so the problem is then yeah, just that we're not trying to infer links at deeper levels. This bit of code needs to recursively dive into objects https://github.com/gatsbyjs/gatsby/blob/fd55277e712e16f1ac75e31e742472e8c05c4fa6/packages/gatsby/src/schema/infer-graphql-type.js#L558

**Comment by KyleAMathews** [comment]
Could you put together a PR making that change w/ a new test for deeper links?

**Comment by m-allanson** [comment]
Aha perfect! Yep, will do.

**Comment by m-allanson** [comment]
Unfortunately I couldn't figure out how to make this work, and have run out of time to investigate further.

In the end I created a script that downloads the remote images, processes them outside of Gatsby, then saves them into the `/static/` directory.

**Comment by jeremylynch** [comment]
I am looking to achieve this exactly. Does anyone have a solution?
