### ISSUE TITLE
White screen of death when browsing around after gatsby build.

### ISSUE THREAD

**Issue by shanejones** [gatsbyjs/gatsby#25878]
## Description

I'm using Gatsby's built-in Link component for all internal links around the site but for some links it keeps pushing the user to a completely white screen.

### Steps to reproduce

If you take a look here https://5f0ce4c9e45bb4001142106c--novos-beta.netlify.app/

Then click on the top nav links you can see that it takes you to a white screen, clicking back then brings you back to another white screen.

When you hit the white screen pages a number of console errors appear. These are not visible in development mode which is making it tricky to work out what the issue is.

### Expected result

The site should browse around like normal and not hit this white screens.

### Actual result

White screen of death 👻

### Environment

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 72.0.2
  npmPackages:
    gatsby: ^2.21.0 => 2.24.1 
    gatsby-background-image: ^1.1.1 => 1.1.1 
    gatsby-image: ^2.4.0 => 2.4.7 
    gatsby-plugin-canonical-urls: ^2.3.0 => 2.3.4 
    gatsby-plugin-force-trailing-slashes: ^1.0.4 => 1.0.4 
    gatsby-plugin-google-tagmanager: ^2.3.0 => 2.3.5 
    gatsby-plugin-manifest: ^2.4.1 => 2.4.11 
    gatsby-plugin-netlify: ^2.3.1 => 2.3.5 
    gatsby-plugin-next-seo: ^1.5.0 => 1.5.1 
    gatsby-plugin-offline: ^3.2.0 => 3.2.9 
    gatsby-plugin-postcss: ^2.3.0 => 2.3.4 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-helmet: ^3.3.0 => 3.3.4 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.3.4 => 2.3.4 
    gatsby-plugin-sharp: ^2.6.0 => 2.6.11 
    gatsby-source-filesystem: ^2.3.1 => 2.3.19 
    gatsby-source-wordpress: ^3.3.1 => 3.3.11 
    gatsby-source-wordpress-menus: ^1.1.3 => 1.1.3 
    gatsby-transformer-inline-svg: ^0.0.7 => 0.0.7 
    gatsby-transformer-sharp: ^2.5.0 => 2.5.5 
  npmGlobalPackages:
    gatsby-cli: 2.10.2

**Comment by herecydev** [comment]
Looks like your "eCommerce Strategy" image doesn't have a fluid or fixed prop coming through. It's pretty hard to help any further though unless you can show the query? Hope that helps.

**Comment by gabrielste1n** [comment]
I'm having this same issue. My site has been running fine and made one small update this afternoon, now I am also getting this "White screen of death".

**Comment by freiksenet** [comment]
Hi! 

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. 

Thanks!
