### ISSUE TITLE
Page refresh loses hashes after service worker update

### ISSUE THREAD

**Issue by ediblecode** [gatsbyjs/gatsby#25889]
## Description

I'm linking between pages using a hash to link to a specific section. After a site re-deploy, which I think in turn triggers a service worker update, the page reloads after navigation and loses the hash. Which in turns mean a user isn't taken to the section related to the link they clicked.

From digging around, I _think_ it's caused by this:

https://github.com/gatsbyjs/gatsby/blob/2a72ec15bb0a5f5d763ad53b413c01c9f66cdbaf/packages/gatsby/cache-dir/navigation.js#L68-L73

Where the `___swUpdated` comes from:

https://github.com/gatsbyjs/gatsby/blob/2e6825af08911877f90d172f8f6bb7f89643c946/packages/gatsby/cache-dir/register-service-worker.js#L27-L30.

I think I _might_ be able to work round it by using `onServiceWorkerUpdateReady` to reload the window myself (keeping the hash), or by setting `window.___swUpdated = false` [like this blog post](https://www.ziebikiewicz.com/adding-update-button-to-gatsby-app#how-to-prevent-auto-reload-on-page-navigation). But this seems wrong to have to do this, when the default behaviour is to refresh after an update - it feels like navigation.js should reload the page, and keep the hash. Maybe by using `window.reload(true)` rather than setting `window.location`?

```diff
-window.location = pathname
+window.reload(true)
```

### Steps to reproduce

1. Add gatsby-plugin-offline to a new gatsby site
1. Create a site with 2 pages, page1.html and page 2.html
2. Add link (using gatsby Link) from page1.html to page 2 with a hash e.g. page2.html#a-section
3. Build the site
4. Navigate to page1, click the link to page 2
5. Make a small code change and build the site again
4. Navigate to page1, click the link to page 2

### Expected result

The page reloads, because of a service worker update, with the same URL, including the hash.

### Actual result

The page reloads, but excludes the hash and just uses the pathname.

### Environment

n/a

**Comment by ediblecode** [comment]
This is kind of related to #25778 in a way as they're both dealing with hashes in links. Just in case anyone else has issues using hash links...

**Comment by madalynrose** [comment]
I'm sorry you're running into this issue @ediblecode! Thanks for lettings us know! It would be really helpful if you could provide a minimal reproduction. I'm tagging in @moonmeister who might have more context on `gatsby-plugin-offline` and service workers but it'd be easiest for us to help debug if we could see a live reproduction of the issue in something like codesandbox.

**Comment by ediblecode** [comment]
Thanks for the reply. I did think about a minimal repro but it's pretty
tricky as it requires a build, after you've visited the site so you can
revisit, with a different build hash so the service worker updates, which
is when you'd see the refresh. So not that straightforward I'm afraid
unless there's another way? Although I could set up a minimal repro repo if
that's easier?

**Comment by ediblecode** [comment]
Ok, I've create a minimal repro repo, see https://github.com/ediblecode/gatsby-hash-repro.

1. Git clone
2. `npm run build`
3. `npm run serve`
4. Open localhost:9000
5. Click the link to page 2 - the url should still contain #test
6. Stop the serve command, and make a simple content change to any file
7.  Repeat steps 2-5 only this time page2.html will reload and lose the hash

There must be a build hash used somewhere for the service worker as you need to make a content change to see trigger a service worker update.

I hope that helps @madalynrose and @moonmeister but more than happy to add more details/screenshare to demo if needs be.

**Comment by wpj** [comment]
There may be other aspects to this that I haven't considered, but I think setting `window.location` to the original value of `to` passed to the navigate function instead of the parsed pathname would fix this: https://github.com/gatsbyjs/gatsby/blob/83926c8ff1df55898ffdeb49183163b5f0bc4270/packages/gatsby/cache-dir/navigation.js#L49

**Comment by ediblecode** [comment]
I think you're right @wpj. I initially thought `window.reload(true)` would do the trick but that would reload the current page rather than the destination page, so you're right that this makes more sense:

```diff
-window.location = pathname
+window.location = to
```

I did wonder if this wouldn't work if there was a prefixed path (sub folder) but looks like the prefixing is done in gatby-link itself:

https://github.com/gatsbyjs/gatsby/blob/693d4aa089f86653d9bbceca7c8736a38bee1323/packages/gatsby-link/src/index.js#L196

so by the time it get's to `navigate` then it's already prefixed, so just using `to` seems sensible to me.

**Comment by ediblecode** [comment]
Definitely not stale

**Comment by Auspicus** [comment]
@ediblecode Don't know if this is still an issue for you but https://github.com/gatsbyjs/gatsby/pull/32323 should address the issue. It also handles query parameters getting dropped which was the bug we had that caused us to look into this.
