### ISSUE TITLE
Asset Prefix does not works on SVG

### ISSUE THREAD

**Issue by kaknut** [gatsbyjs/gatsby#25918]
https://www.gatsbyjs.org/docs/asset-prefix/

## Description
The build command for asset prefix does not work with .svg files. 
If you use `img/demo.svg` in markdown then it get's converted to `https://www.your-domain.com/https:/cdn.your-domain.com/{generated-hash-values}/demo.svg`

### Steps to reproduce

Just add path prefix build on a page which load .svg type images.

### Expected result

If you use `img/demo.svg` in markdown then it should get converted to `https:/cdn.your-domain.com/{generated-hash-values}/demo.svg`

### Actual result

If you use `img/demo.svg` in markdown then it get's converted to `https://www.your-domain.com/https:/cdn.your-domain.com/{generated-hash-values}/demo.svg`. This leads to image returning `4xx`

### Environment

`gatsby build --prefix-paths`

**Comment by kaknut** [comment]
Is this a known issue?

**Comment by wardpeet** [comment]
That seems to be a bug indeed with our remark parser. Thank you for raising it

**Comment by pieh** [comment]
Pending fix for this problem: https://github.com/gatsbyjs/gatsby/pull/26976
