### ISSUE TITLE
Conditional page builds not working with static queries

### ISSUE THREAD

**Issue by herecydev** [gatsbyjs/gatsby#25928]
#25723 has moved static queries outside of the js bundles. Previously a change to these would trigger a full rebuild which wasn't ideal. The changes made have fixed this, however now nothing is triggering so it is not possible to detect and deploy a static query change.

This effectively makes them unreliable for use with conditional page builds

**Comment by SpicyPete** [comment]
I am also having this issue, where any `template` with a static query being exported fails to build... which are most of my pages in some projects.

**Comment by StuartRayson** [comment]
This is good change having the static queries outside of the JS bundles. 🙇  

Just thinking how to we could go about fixing `conditional page builds` 🤔 , 

The full rebuild on the static data change wasn't ideal, in the first attempt we struggled linking page paths to static data. 

I haven't started investigating myself yet, so just a few questions

I see in the PR there is now a `[staticQueryResults](https://github.com/gatsbyjs/gatsby/pull/25723/files#diff-2c6a8681039e2f6dce2b3ca1444dfce2R16)` with a `path`, is the staticQueryResults saved in a redux.state cache?

Do the `staticQueryHashes` change if query data returned is different?

**Comment by herecydev** [comment]
Struggling to recreate in isolation, so appreciate that's not a great start. However I did dig into some of the dirty checking that Gatsby is doing and **would really appreciate** if you can look over my findings:

I added some additional logging into [this block in redux/reducers/html.ts](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/reducers/html.ts#L114-L116) so that I could check if it detects that my static query data has changed. This works as intended:

![Untitled](https://user-images.githubusercontent.com/11328618/131213179-6a242889-ffec-44ac-b4ab-1fda595c0260.png)

Gatsby detects the change, flags the query as dirty and subsequently rebuilds the necessary pages. The problem, I think, is that it's not correctly reupdating this entry in the `trackedStaticQueryResults`, so of course the old cache remains in the html. When the state is saved in `saveState`, the following can be observed:

![Untitled2](https://user-images.githubusercontent.com/11328618/131213263-3fc68297-11a1-4a78-bf36-0ca357e9f8d1.png)

So the old hash is persisted, and the following problem is introduced: 

1. data was "foo" in cache
2. data changes to "bar"
3. dirty detected and rebuilds pages
4. data changes back to "foo"
5. dirty is not detected because cached version is still "foo"
6. No rebuild happens
