### ISSUE TITLE
Gatsby transformer CSV - truncates the data in graphiql.

### ISSUE THREAD

**Issue by peter3bweb** [gatsbyjs/gatsby#25923]
## Description

Describe the issue that you're seeing.

I have a csv with 406 rows and 4 columns. When using Graphiql it returns only rows. - 269 - using the following query

```const stationCsvData = useStaticQuery(
    graphql`
      query allStationsQuery {
        allStationsGridviewCsv {
          totalCount
          nodes {
            line
            lon
            lat
            name
            id
          }
        }
      }
    `
  )
```

looking at /__graphiql only returns the 269 results too so my query isn't causing the issues.
### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/ - 
https://test-ltm-3--ltm-map-project.netlify.app/ - it appears when selecting hammersmith & city. Missing tube lines

I am retrieving location from a CSV and it is truncating the results. - 

### Expected result

What should happen?
Get all 406 rows of data from the CSV file.
### Actual result

What happened.
Only 269 results are returned - 
### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 78.0.2
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.22.15 => 2.24.7
    gatsby-image: ^2.4.5 => 2.4.13
    gatsby-plugin-manifest: ^2.4.9 => 2.4.19
    gatsby-plugin-offline: ^3.2.7 => 3.2.19
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.10
    gatsby-plugin-sharp: ^2.6.9 => 2.6.20
    gatsby-source-airtable: ^2.1.1 => 2.1.1
    gatsby-source-filesystem: ^2.3.8 => 2.3.20
    gatsby-source-googlemaps-geocoding: ^1.0.0 => 1.0.0
    gatsby-source-googlemaps-static: ^1.1.12 => 1.1.12
    gatsby-transformer-csv: ^2.3.10 => 2.3.10
    gatsby-transformer-sharp: ^2.5.3 => 2.5.11
  npmGlobalPackages:
    gatsby-cli: 2.8.12

**Comment by peter3bweb** [comment]
Any update on this issue?

**Comment by peter3bweb** [comment]
Any updates?

**Comment by pvdz** [comment]
I'd like to take this on but honestly don't know when I'll have time for it.

Any chance you could take an attempt at debugging the plugin, see where it derails? The file itself (gatsby-node.js) is less than 100loc.

**Comment by acao** [comment]
i wonder if it’s related to delimeter charachters? in your CSV file @peter3bweb, are there any unescaped special characters in that row? for example, a string with an unescaped comma or double quote in it?

**Comment by peter3bweb** [comment]
Thanks both. I am happy to take a look at it

@acao  - there are some double quotes. I think I had removed these but was still getting the error

**Comment by acao** [comment]
have you looked into using any of [these parameters](https://www.npmjs.com/package/csvtojson#parameters) from the underling parsing library? the nature of your bug, where there is partial parsing, seems to indicate `csvtojson` is having trouble parsing the file. for example, you might try `quote: “off”` in the plugin config

**Comment by pvdz** [comment]
@peter3bweb any chance I could take a look at this csv? I'm hoping maybe it's open public transport data.

Either way, CSV has a very straightforward encoding scheme:
- replace all double quotes with two double quotes
- wrap fields with unpredictable input in double quotes

The algo will start from a double quote and keep consuming until the first double quote that is not escaped by another double quote. This includes newlines, commas, and any other awkward characters.

CSV doesn't really support any other escaping mechanism (but that all depends on whether the actual parser does, of course). In particular: backslashes are not special.

I created a benchmark csv site last week and went through this as well.

Can you confirm whether or not your input data is properly escaped this way? Otherwise can you close this issue? :) Thanks! :purple_heart:

**Comment by pvdz** [comment]
@peter3bweb if there's no further response I'll assume the matter was resolved?
