### ISSUE TITLE
Fixed image with media queries renders slowest image available on first render

### ISSUE THREAD

**Issue by MarcoScabbiolo** [gatsbyjs/gatsby#25938]
## Description

When using multiple sources for a  fixed image, each with a media query set, the first source is rendered ignoring the media queries and the issue is fixed only after resizing the window, something end user will of course wont do.

### Steps to reproduce

meros created a [repro repo](https://github.com/meros/gatsby-bug-repro-image-media-queries), and provided it in [this comment](https://github.com/gatsbyjs/gatsby/issues/16763)

### Expected result

The image matching the media query should be rendered

### Actual result

The first image is rendered

### Environment

It only happens on production environments

This was first reported in #16763 but since that issue was closed and is being ignored, I'm opening a new one refering to the same bug.

**Comment by polarathene** [comment]
This issue has been resolved with the following PR https://github.com/gatsbyjs/gatsby/pull/24811

Please subscribe to that and await it being reviewed and merged.
