### ISSUE TITLE
How do you update a deployed Gatsby site?

### ISSUE THREAD

**Issue by learis** [gatsbyjs/gatsby#25935]
I deployed a Gatsby site to Godaddy. I see a minor styling error that I need to fix in code for a js file. Is there a way to just upload that single file and replace it on the live site? Or do I have to build the entire website again and upload the entire website to GoDaddy?

There's tons of tutorials on deploying a website, but I couldn't really find one on updating a website that's already deployed.

**Comment by polarathene** [comment]
Your JS is bundled via webpack, it also has a unique hash for the file in it's filename to prevent misconfigured cache issues causing problems. Thus it's advisable to do a full redeploy of any files that have been changed from a new build. There is a variety of tools out there that can compare two directories for differences, including git itself. If you use SFTP, your client software may also offer the option to only copy over files that are different, but this would not remove old files that are no longer in use, over time that may add up and be undesirable.

Additionally if you're only doing static hosting, you may prefer to host via Netlify or Vercel, which offer generous free tier plans, they can integrate with your Github or Gitlab account, where you can upload your Gatsby project, and these services will create a new build and deploy the update for you as soon as you update your project on Github / Gitlab. 

The services are quick and easy to sign-up for, you can link your Github or Gitlab account, then choose the project, and click deploy, it's a very simple process. Once setup, you'll be provided a URL to visit and see the website hosted by the service, you can then go into settings and assign your own custom web domain that you're using with GoDaddy if you like. 

If you are not comfortable with using Github or Gitlab, you'll find Netlify offers a drag and drop feature for files instead.
