### ISSUE TITLE
The result of this StaticQuery could not be fetched. (after deploying public folder of gatsby build)

### ISSUE THREAD

**Issue by arslqureshi** [gatsbyjs/gatsby#25949]
## Description

So I deployed a website created in gatsby . After using the command gatsby build. I uploaded it and it shows this error The result of this StaticQuery could not be fetched.
### Steps to reproduce

follow this [link](https://www.youtube.com/watch?v=TXAkP4WQVXY). after deploying check console of the browser

### Expected result

It should display my website at https://suspicious-curran-c4b2b0.netlify.app/

### Actual result

just showing black screen

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.20.36 => 2.24.9
    gatsby-plugin-google-analytics: ^2.1.8 => 2.3.13
    gatsby-plugin-manifest: ^2.2.6 => 2.4.20
    gatsby-plugin-netlify: ^2.1.6 => 2.3.11
    gatsby-plugin-offline: ^2.2.7 => 2.2.10
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.10 => 1.1.10
  npmGlobalPackages:
    gatsby-cli: 2.12.62

**Comment by sidharthachatterjee** [comment]
@arslqureshi Do you have a reproduction? Can you please push your project to a repository and link to it here?

**Comment by arslqureshi** [comment]
@sidharthachatterjee https://gitlab.com/arslq7/portfolio/-/tree/master/

**Comment by wardpeet** [comment]
This is a windows error, I'm currently fixing it :) Thanks for reporting it

**Comment by sidharthachatterjee** [comment]
@wardpeet Excellent catch! Thank you! ❤️

**Comment by wardpeet** [comment]
Fixed in `gatsby@2.24.11`
