### ISSUE TITLE
Unable to perform gatsby build over CMS running under Windows 10 Docker

### ISSUE THREAD

**Issue by jf-home** [gatsbyjs/gatsby#25957]
Trying to run up a gatsby develop session and get the following message:

"gatsby-source-directus" threw an error while running the sourceNodes lifecycle
Environment information

    @directus/gatsby-source-directus version v0.0.44
    Directus version: v8.8.0
    Gatsby version: v2.24.7

To Reproduce on Windows 10 (using Docker Desktop)

    Install Docker Desktop application on Windows 10

    Install and run the Directus Docker installation per the following instructions:

    https://docs.directus.io/installation/docker.html

    Install gatsby-source-directus plug-in in your Gatsby project

    Reference the plug-in in your gatsby-config.js file (note: the user token can be obtained from the directus_users table in the MySQL database):

    {
    resolve: gatsby-source-directus,
    options: {
    url: localhost:8080,
    protocol: 'http',
    project: '_',
    auth: {
    token: <YOUR_USER_TOKEN_IN_HERE>,
    },
    targetStatuses: ['published', 'NONE'],
    nameExceptions: {
    posts: "Article",
    },

    Run gatsby develop from a terminal

Expected behavior

Gatsby develop session should run without errors. When complete content in Directus should be available through GraphQL (localhost:8000/___graphql).
Output from the gatsby develop session:

success open and validate gatsby-configs - 0.055s
success load plugins - 4.865s
success onPreInit - 0.033s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's no stale data.
success initialize cache - 0.117s
success copy gatsby files - 0.235s
success onPreBootstrap - 0.026s
success createSchemaCustomization - 0.016s
gatsby-source-directus Fetching Directus tables data...

ERROR #11321 PLUGIN

"gatsby-source-directus" threw an error while running the sourceNodes lifecycle:

warn The gatsby-source-directus plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 0.340s
success building schema - 0.418s
success createPages - 0.003s
success createPagesStatefully - 0.141s
success updating schema - 0.044s
success write out redirect data - 0.010s
success Build manifest and related icons - 0.146s
success onPostBootstrap - 0.165s
info bootstrap finished - 13.738s
success onPreExtractQueries - 0.003s
success extract queries from components - 0.465s
success write out requires - 0.063s
success run static queries - 0.102s - 3/3 29.50/s
success run page queries - 0.031s - 6/6 195.75/s
success write out requires - 0.002s
⠀
You can now view gatsby-starter-default in the browser.
gatsby info:

System:
OS: Windows 10 10.0.18363
CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Binaries:
Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
Languages:
Python: 2.7.17
Browsers:
Edge: 44.18362.449.0
npmPackages:
gatsby: ^2.24.7 => 2.24.7
gatsby-image: ^2.4.13 => 2.4.13
gatsby-plugin-manifest: ^2.4.19 => 2.4.19
gatsby-plugin-offline: ^3.2.19 => 3.2.19
gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
gatsby-plugin-sharp: ^2.6.20 => 2.6.20
gatsby-source-directus: 0.0.44 => 0.0.44
gatsby-source-filesystem: ^2.3.20 => 2.3.20
gatsby-transformer-sharp: ^2.5.11 => 2.5.11
npmGlobalPackages:
gatsby-cli: 2.12.24

I believe this is more of a Gatsby - Docker issue rather than a CMS-specific problem as I have also run into the same issue when running Cockpit as a Docker on my Windows 10 system as well.

Thanks in advance!

**Comment by vladar** [comment]
Hey @jf-home !

This sounds like an issue with `gatsby-source-directus`. I guess we can try to look into it but need an [example project](https://gatsby.dev/reproduction). This will help anyone who is interested to start debugging it!

An example project:

- can be run locally or credentials have been provided
- can be used to reproduce the issue

**Comment by jf-home** [comment]
Hi @vladar  - thanks for the prompt reply - much appreciated.  

I'm not sure that it is a `gatsby-source-directus` issue specifically as I have run into the exact same issue with `gatsby-source-cockpit`.  I believe that there is some specific configuration required as a result of running the CMSs under Docker, unfortunately, I've not been able to fathom it out though.  

I can certainly share my basic repo.  I'll get onto that tomorrow and will provide a futher update when available.

Many thanks.

**Comment by jf-home** [comment]
Hi @vladar, 

I have a shared repo for you to use: https://github.com/jf-home/gatsby-directus.  

Please note that this whilst the site will run, there is an error during `gatsby develop` which suggests that connection to Directus has failed.  To confirm this, no Directus nodes are available though GraphQL (http://localhost:8000/___graphql).

i appreciate you taking the time to look into this!

Many thanks

**Comment by jf-home** [comment]
... I should also mention that the following entires were added to my Windows hosts file (C:\Windows\System32\drivers\etc\hosts):

# Added by Docker Desktop
192.168.1.133 host.docker.internal
192.168.1.133 gateway.docker.internal

...and I also added the following to the hosts file based on some suggestions that I found: 
127.0.0.1 host.docker.internal:8080

Many thanks!

**Comment by jf-home** [comment]
Please keep open as I'd like to know how to successfully host via a docker.  TY

**Comment by vladar** [comment]
Did you try SSH into Docker machine and try to fetch data from Directus manually (i.e. using `curl`, `wget` or a similar tool)? This sounds like a docker network setup issue for me. But if fetching data via shell works, then it's odd indeed.

**Comment by jf-home** [comment]
Thanks for looking into this for me.  Unfortunately, I'm going to have to cut my losses on this one.  Closing as a result.
