### ISSUE TITLE
Error Copying Files To public Directory

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#25959]
## Description

I'm seeing the following error during build.

```
error copying file from /Users/me/Sites/example/static/uploads/example.svg to /Users/me/Sites/example/public/static/1dfbd614d33d3d25f117f78696579658/example.svg [Error: ENOENT: no such file or directory, unlink '/Users/me/Sites/example/public/static/1dfbd614d33d3d25f117f78696579658/example.svg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/Users/me/Sites/example/public/static/1dfbd614d33d3d25f117f78696579658/example.svg'
}
```

This doesn't happen on every build. Probably two in every three builds. It happens regardless of whether `gatsby clean` has been run before the build, and errors appear to be emitted for some or all of the same set of images. The only consistency between all images is that they are:
- referenced from frontmatter of a markdown document
- either svgs or pdfs. (We use a large number of pngs and jpegs, so I think this is significant). 

Possibly related to #20602, #1693

Note that it doesn't appear to have any negative consequences. The images are still present in the `/public/` directory and load successfully on the site. 

The same thing happens on our CI server (Linux), with the same unpredictable pattern. 

### Steps to reproduce

I can't reliably reproduce.

### Expected result

No error should be emitted.

### Actual result

An obscure error message is emitted

### Environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 78.0.2
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.23.1 => 2.23.1
    gatsby-cli: ^2.12.44 => 2.12.44
    gatsby-image: ^2.4.7 => 2.4.7
    gatsby-link: ^2.4.6 => 2.4.6
    gatsby-plugin-catch-links: ^2.3.5 => 2.3.5
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6
    gatsby-plugin-google-tagmanager: ^2.3.5 => 2.3.5
    gatsby-plugin-manifest: ^2.4.11 => 2.4.11
    gatsby-plugin-netlify-cms: ^4.3.7 => 4.3.7
    gatsby-plugin-node-fields: 3.1.0 => 3.1.0
    gatsby-plugin-page-creator: ^2.3.9 => 2.3.9
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.4
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0
    gatsby-plugin-scroll-reveal: ^0.0.7 => 0.0.7
    gatsby-plugin-sharp: ^2.6.11 => 2.6.11
    gatsby-plugin-sitemap: ^2.4.5 => 2.4.5
    gatsby-plugin-styled-components: ^3.3.4 => 3.3.4
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2
    gatsby-react-router-scroll: 3.0.3 => 3.0.3
    gatsby-remark-autolink-headers: ^2.3.5 => 2.3.5
    gatsby-remark-component-parent2div: ^1.2.3 => 1.2.3
    gatsby-remark-copy-linked-files: ^2.3.5 => 2.3.5
    gatsby-remark-footnotes: ^0.0.7 => 0.0.7
    gatsby-remark-images: ^3.3.10 => 3.3.10
    gatsby-remark-numbered-footnotes: ^1.0.1 => 1.0.1
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-remark-responsive-iframe: ^2.4.5 => 2.4.5
    gatsby-remark-smartypants: ^2.3.4 => 2.3.4
    gatsby-remark-unwrap-images: ^1.0.2 => 1.0.2
    gatsby-source-filesystem: ^2.3.11 => 2.3.11
    gatsby-transformer-json: ^2.4.5 => 2.4.5
    gatsby-transformer-remark: ^2.8.15 => 2.8.15
    gatsby-transformer-sharp: ^2.5.5 => 2.5.5
```

**Comment by vladar** [comment]
Hi @Undistraction !

Do you see any stack trace with those errors?

I realize that it's hard to reproduce but it is also hard to help without reproduction (or at least access to an example project where this can be reproduced).

So I am still asking for a [minimal reproduction][reproduction] (or an example project). And hope that maybe someone else who also sees this issue can provide a repro or at least a bit more information about the issue.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Undistraction** [comment]
@vladar yeah I appreciate that. I've tried putting together a reproduction with a basic template but it doesn't exhibit the same behaviour. I'll try again when I get some more time.

**Comment by freiksenet** [comment]
Hi! 

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. 

Thanks!
