### ISSUE TITLE
Loading (StaticQuery) screen on every route even if I am not using StaticQuery component at all

### ISSUE THREAD

**Issue by marcelo-umg** [gatsbyjs/gatsby#25955]
I am getting the error reported on this issue: https://github.com/gatsbyjs/gatsby/issues/25920

I know you guys will ask for a reproducible demo, but how do I do that if there is no reason for my to throw that error I am not even using `StaticQuery` component anywhere on my app?

To be clear, the issue is only happening on the live site, not locally. 
Even if I run the commands: `gatsby build` and `gatsby develop`, the project keeps running properly on my local. It's on the live site that the application shows that `Loading (StaticQuery)` screen.

I noticed some other devs before having it: https://github.com/gatsbyjs/gatsby/issues/6350

I saw that some devs recommend removing the `export` from the `query` variable, so this:
```js
const query = graphql`...`
```
Instead of this:
```js
export const query = graphql`...`
```
But this is not my case. Everything was working good until some hours ago.

I have all of my pages with queries like this:

```js
// this is my component
const CollectionProduct = ({ data }) => {...}

// and outside the component is the query
export const query = graphql`
  query($handle: String!) {
    shopifyCollection(handle: { eq: $handle }) {
      products {
        id
        title
        handle
        createdAt
        }
      }
    }
  }
`
```

In that component I am using `export` on `const query`, all of my pages are defined the same way and before there were no problems. I already upgrade and downgrade the version of Gatsby and yet the same issue.

My issues comes exactly after I added a `.eslintrc.js` config file to the project; is this an option that my project build fails on the live site due to ESLint?

Locally it works, I can build the project and see it on my `localhost` with no problems. But when I see the live site, it throws that `Loading(StaticQuery)` white screen. And I am not even using `StaticQuery` component anywhere. Only the `useStaticQuery` hook on non page nor templates components.

This is my ESLint config:
```js
module.exports = {
  globals: {
    __PATH_PREFIX__: true,
  },
  'parser': 'babel-eslint',
  parserOptions: {
    extraFileExtensions: ['.js'],    
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
    useJSXTextNode: true,
    include: ['**/*js'],
  },
  env: {
    es6: true,
    node: true,
    jest: true,
    browser: true,
    commonjs: true,
    serviceworker: true,
  },
  extends: ['eslint:recommended', 'plugin:react/recommended', 'semistandard', 'plugin:import/react'],
  plugins: ['react'],
  rules: {
    semi: 'off',
    'strict': 0,
    curly: [1, 'all'],
    'no-console': 'error',
    "react/prop-types": 0,
    camelcase: ['off', {}],
    'react/jsx-uses-vars': 1,
    'react/jsx-uses-react': 1,
    'react/jsx-boolean-value': 2,
    "react/display-name": 'warn',
    'react/react-in-jsx-scope': 1,
    'brace-style': ['error', '1tbs'],
    'comma-dangle': ['error', 'never'],
    'linebreak-style': ['error', 'unix'],
    'react-hooks/exhaustive-deps': 'off',
    'standard/no-callback-literal': [0, []],
    'padding-line-between-statements': [
      'error',
      { blankLine: 'always', prev: '*', next: 'return' },
      { blankLine: 'always', prev: '*', next: 'multiline-const' },
      { blankLine: 'always', prev: 'multiline-const', next: '*' },
      { blankLine: 'always', prev: '*', next: 'block-like' },
      { blankLine: 'always', prev: 'block-like', next: '*' },
    ],
    'react/jsx-curly-brace-presence': [
      'error',
      { props: 'never', children: 'never' },
    ],
  },
};
```

Any ideas?

```
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Edge: 84.0.522.40
    Safari: 13.1
  npmPackages:
    gatsby: ^2.24.8 => 2.24.8
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-cli: ^2.12.54 => 2.12.54
    gatsby-image: ^2.3.2 => 2.4.13
    gatsby-plugin-emotion: ^4.2.1 => 4.3.10
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-google-tagmanager: ^2.3.11 => 2.3.11
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-layout: ^1.3.2 => 1.3.10
    gatsby-plugin-manifest: ^2.4.1 => 2.4.20
    gatsby-plugin-nprogress: ^2.3.9 => 2.3.10
    gatsby-plugin-offline: 3.2.0 => 3.2.0
    gatsby-plugin-postcss: ^2.3.1 => 2.3.11
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.10
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-sass: ^2.3.2 => 2.3.12
    gatsby-plugin-sharp: ^2.5.4 => 2.6.21
    gatsby-plugin-sitemap: ^2.4.5 => 2.4.11
    gatsby-remark-responsive-iframe: ^2.3.1 => 2.4.11
    gatsby-source-drupal: ^3.5.12 => 3.5.24
    gatsby-source-filesystem: ^2.2.2 => 2.3.21
    gatsby-source-shopify: ^3.2.8 => 3.2.23
    gatsby-transformer-sharp: ^2.5.3 => 2.5.11
  npmGlobalPackages:
    gatsby-cli: 2.12.60
```

**Comment by sidharthachatterjee** [comment]
@marcelo-umg In this case, the error points to usage of both the `StaticQuery` component or the `useStaticQuery` hook. Does removing the `.eslintrc` fix this for you?

**Comment by marcelo-umg** [comment]
Hi @sidharthachatterjee, I am not using `StaticQuery` at all in my code, so why this error suggests I am using both?

And no, I didn't remove the `.eslintrc` file. I am going to try by removing it.

**Comment by sidharthachatterjee** [comment]
@marcelo-umg The error is relevant for both `StaticQuery` and `useStaticQuery`

Is your repo public? If yes, can you link to it? Or invite me to it in case it's private and I'll help fix this as soon as possible! 🙂

**Comment by marcelo-umg** [comment]
@sidharthachatterjee I am going to close this issue. I pushed my code without `package-lock.json`. And now the live site is working. It is strange but this is the way it works.
