### ISSUE TITLE
gatsby info throws error UNHANDLED REJECTION e.filter is not a function

### ISSUE THREAD

**Issue by jsejcksn** [gatsbyjs/gatsby#25966]
## Description

`gatsby info` throws error `UNHANDLED REJECTION e.filter is not a function`

### Steps to reproduce

Install `gatsby-cli`, then

```shell
% gatsby --version
Gatsby CLI version: 2.12.65

% gatsby info     

 ERROR 

UNHANDLED REJECTION e.filter is not a function



  TypeError: e.filter is not a function
  
  - envinfo.js:1 
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:73205
  
  - async Promise.all
```

### Expected result

According to the manual:

> Get environment information for debugging and issue reporting

### Actual result

See terminal output above.

### Environment

> Run `gatsby info --clipboard` in your project directory and paste the output here.

_womp womp_

```shell
% gatsby info --clipboard

 ERROR 

UNHANDLED REJECTION e.filter is not a function



  TypeError: e.filter is not a function
  
  - envinfo.js:1 
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:73205
  
  - async Promise.all
```

**Comment by vladar** [comment]
Interesting. I couldn't reproduce this locally. I think it might be a problem with `envinfo` package - https://github.com/tabrindle/envinfo/issues/182 

Try re-installing `gatsby-cli` as they have fixed it and published a fix several hours ago?

**Comment by jsejcksn** [comment]
@vladar I think you're right. `gatsby-cli` should bump `envinfo` to `^7.7.2`
