### ISSUE TITLE
Uninstall, or reset Gatsby CLI

### ISSUE THREAD

**Issue by dwyn** [gatsbyjs/gatsby#25979]
## Description

When I run `npm uninstall -g gatsby-cli`, the gatsby-cli still seems to be installed. 
Right afterwards I can run `gatsby -v`
--> `Gatsby CLI version: 2.12.65`

### Environment
2019 Macbook Pro
macOS Catalina 10.15.6

Is there another way to completely remove the gatsby-cli from my system, so that I may reinstall it? Thanks in advance!

**Comment by 3scava1i3r** [comment]
Please globally remove gatsby 
`yarn global remove gatsby-cli`
or use this as well
`sudo npm uninstall -g gatsby-cli`

I hope i was able to help

**Comment by dwyn** [comment]
Thanks, everyone!
