### ISSUE TITLE
Error while fetching data from gatsby-source-shopify2

### ISSUE THREAD

**Issue by jack0wsky** [gatsbyjs/gatsby#25973]
## Description

I'm using `gatsby-source-shopify2`. My problem is that when I run `gatsby develop` I see this error:

`gatsby-source-shopify/undefined starting to fetch data from Shopify

 ERROR 

error an error occured while sourcing data

 ERROR 

query: 
  """

      query GetProductTypes($first: Int!) {
        shop {
          productTypes(first: $first) {
            edges {
              node
            }
          }
        }
      }

  """
variables: 
  first: 250`

here is my `gatsby-config.js` file: 

`
{
      resolve: `gatsby-source-shopify2`,
      options: {
        shopName: process.env.GATSBY_SHOP_NAME,
        accessToken: process.env.GATSBY_STOREFRONT_ACCESS_TOKEN,
        apiVersion: '2020-07',
        verbose: true,
      },
    },
`

### Steps to reproduce

have no idea

### Expected result

gatsby should fetch all data from Shopify without errors

### Actual result

`gatsby-source-shopify2` cannot fetch data

### Environment

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 78.0.1
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.17.4 => 2.24.4
    gatsby-cli: ^2.12.62 => 2.12.62
    gatsby-image: ^2.2.29 => 2.4.13
    gatsby-plugin-google-analytics: ^2.0.13 => 2.3.11
    gatsby-plugin-layout: ^1.0.11 => 1.3.10
    gatsby-plugin-manifest: ^2.2.23 => 2.4.18
    gatsby-plugin-offline: ^3.0.16 => 3.2.18
    gatsby-plugin-react-helmet: ^3.1.13 => 3.3.10
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-sharp: ^2.2.32 => 2.6.19
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10
    gatsby-plugin-transition-link: ^1.20.2 => 1.20.2
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.1.33 => 2.3.20
    gatsby-source-shopify: ^3.2.24 => 3.2.24
    gatsby-source-shopify2: ^2.0.7 => 2.0.7
    gatsby-transformer-sharp: ^2.3.0 => 2.5.11
  npmGlobalPackages:
    gatsby-cli: 2.12.60

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by vladar** [comment]
Hm, `gatsby-source-shopify2` has it's own repo: https://github.com/witbybit/gatsby-source-shopify

And they say the plugin is deprecated and that you should use `gatsby-source-shopify@^2.0.5`.

Have you tried this? If not, or if you want to stick with `gatsby-source-shopify2` I suggest you open an issue in their repository instead.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
