### ISSUE TITLE
Error: result of static query could not be fetched

### ISSUE THREAD

**Issue by Chanakya888** [gatsbyjs/gatsby#25985]
##Error
Uncaught Error: The result of this StaticQuery could not be fetched.
This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue.

default index.js:14
-->

## Description
This error is appearing only when I build and serve the site, not in develop mode. There are already several of these issues which have been solved, I've tried all those solutions, couldn't get it to work. I understand this isn't a bug, I am assuming that the way I am using useStaticQuery has something to do with it.

### Steps to reproduce

Demolink: [https://github.com/Chanakya888/csp-deploy](https://github.com/Chanakya888/csp-deploy)

1. npm i 
2. gatsby build
3. gatsby serve

### Expected result

The pages should load the data when I move to pages like About and investments without the need of a refresh.

### Actual result

I have just mentioned index.js:14 error above, but the error occurs whenever I open a new page, the error disappears when I refresh the page.

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 78.0.2
    Safari: 13.1
  npmPackages:
    gatsby: 2.24.10 => 2.24.10
    gatsby-image: ^2.4.7 => 2.4.13
    gatsby-plugin-postcss: ^2.3.4 => 2.3.11
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-react-leaflet: ^2.0.13 => 2.0.13
    gatsby-plugin-sharp: ^2.6.12 => 2.6.21
    gatsby-plugin-transition-link: ^1.20.2 => 1.20.2
    gatsby-source-contentful: ^2.3.16 => 2.3.30
    gatsby-source-filesystem: ^2.3.12 => 2.3.22
    gatsby-source-googlemaps-static: ^1.1.12 => 1.1.12
    gatsby-transformer-sharp: ^2.5.5 => 2.5.11
  npmGlobalPackages:
    gatsby-cli: 2.12.48```

**Comment by sidharthachatterjee** [comment]
Can you please try upgrading to gatsby@2.24.11? That contains a fix for a bug that was breaking static queries on Windows machines.

**Comment by dbelovol** [comment]
I found cause of my trouble (useStaticQuery problem #25987). As I mentioned in issue, I've used official integration example of material-ui library for Gatsby. I've tried to query SEO info from siteMetadata instead of hardcoded value in example in local plugin code from this example. 
When I explored files from gatsby-ssr.js and gatsby-browser.js from local plugin directory, I've found they are **identical**
```
export const wrapRootElement = ({ element }) => {
  return <TopLayout>{element}</TopLayout>;
};
```
In fact, my query was succesful **at build time**, but I've got error message from browser-side query attempt. When I comment out code in plugin's gatsby-browser.js, the bug disappeared.
I'm sorry - it was my fault. In fact, I don't know gatsby internals yet.

**Comment by Chanakya888** [comment]
I still couldn't find the issue, I have updated to gatsby@2.24.11, I have no errors in build time or in development . I am sure it's the error from browser-side query attempt for me too. I've hosted the website here, [https://csp-testing-websie.netlify.app/](https://csp-testing-websie.netlify.app/). 

I can also see this weird behaviour of the page name changing, if I click on the about us page, it goes to /About and then changes to /about, same for all the pages, it is unusual. Can you explain me what is happening here?

**Comment by dbelovol** [comment]
Couldn't say anything about locations. 
As for query itself being Static and, like so, performed at build time, you should avoid using it browser side.

**Comment by dbelovol** [comment]
Gatsby has lot more difficult internals compared to my imagination. So I can't explain it's strange behavior. 
I've read that all Static queries are removed from final bundle and substituted by json import, containing data, fetched at build time. 
So it seems to be bug, because we get Static query message from browser runtime js  so question is - why this query has not been removed from bundle? 
By the way - I got this message, surfing Gatsby.org. I've tried to load PRPL pattern entry from conceptual guide, but page not loaded. When I look into console and see that message from static query hook.

**Comment by yanbutan** [comment]
Hi guys any follow up for this? I believe i'm having the same issue. useStaticQuery works during development but not during production when gatsby build && gatsby serve is run.

static query in seo.js file :
`function SEO({ description, lang, meta, title }) {
  const { site } = useStaticQuery(
    graphql`
      query {
        site {
          siteMetadata {
            title
            description
            author
          }
        }
      }
    `
  )`


Gatsby dependencies: 
`"gatsby": "^2.23.12",
    "gatsby-image": "^2.4.9",
    "gatsby-plugin-manifest": "^2.4.14",
    "gatsby-plugin-postcss": "^2.3.4",
    "gatsby-plugin-react-helmet": "^3.3.6",
    "gatsby-plugin-robots-txt": "^1.5.1",
    "gatsby-plugin-sharp": "^2.6.14",
    "gatsby-plugin-sitemap": "^2.4.11",
    "gatsby-source-filesystem": "^2.3.14",
    "gatsby-transformer-sharp": "^2.5.7",`

**Comment by natedonato** [comment]
@yanbutan  I had a similar production only issue with StaticQuery components, may have fixed by upgrading my gatsby dependency to 2.24.11 
```
   "gatsby": "2.24.11",
```

**Comment by Brend0n** [comment]
Same issue for me, 
The error is coming when I build/serve Gatsby, if I try to switch page (browser-side navigation) I have the `Uncaught Error: The result of this StaticQuery could not be fetched.` error on page change (need to refresh to load the page).

The weird thing is the error is raised from the current page file not the page I am navigating to.

I have tried different gatsby version (including 2.24.11) but nothing seems solving the issue.

**Comment by yanbutan** [comment]
> Hi guys any follow up for this? I believe i'm having the same issue. useStaticQuery works during development but not during production when gatsby build && gatsby serve is run.
> 
> static query in seo.js file :
> `function SEO({ description, lang, meta, title }) { const { site } = useStaticQuery( graphql`
> query {
> site {
> siteMetadata {
> title
> description
> author
> }
> }
> }
> ` )`
> 
> Gatsby dependencies:
> `"gatsby": "^2.23.12", "gatsby-image": "^2.4.9", "gatsby-plugin-manifest": "^2.4.14", "gatsby-plugin-postcss": "^2.3.4", "gatsby-plugin-react-helmet": "^3.3.6", "gatsby-plugin-robots-txt": "^1.5.1", "gatsby-plugin-sharp": "^2.6.14", "gatsby-plugin-sitemap": "^2.4.11", "gatsby-source-filesystem": "^2.3.14", "gatsby-transformer-sharp": "^2.5.7",`

Updates regarding this on my side. I deleted .cache, node modules, package.lock, npm installed, gatsby build && gatsby serve and this worked for me. But this is not a very reassuring fix because I will have to keep updating the versions if this happen again.

**Comment by Chanakya888** [comment]
I set everything up from scratch, updated everything, copy pasted code from previous the above repo, it works now. I'm closing this issue, I'll leave the repo public and the site live, if anyone at Gatsby wants to review it. Thank you everyone!
