### ISSUE TITLE
Defining schema types for a YAML sequence

### ISSUE THREAD

**Issue by brettdewoody** [gatsbyjs/gatsby#25986]
## Summary

Is it possible to add a schema customization for a sequence of `id`s from a Yaml file? 

Example YAML:
```
- product1
- product2
- product3
```

Each `id` in this sequence corresponds to another type, specifically a Stripe product id, but it could be any other type. 

In other instances, where I have an array within a Node, we're able to this:

```
products:
  - product1
  - product2
  - product3

type BoxYaml implements Node {
  products: [StripeProduct] @link(by: "id")
}
```

But I'd like to define the items in the sequence as a `StripeProduct`. Is this possible?

### Environment 

```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.0 - ~/.nvm/versions/node/v8.11.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v8.11.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 76.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.24.2 => 2.24.2
    gatsby-image: ^2.4.13 => 2.4.13
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-gtag: ^1.0.13 => 1.0.13
    gatsby-plugin-manifest: ^2.4.18 => 2.4.18
    gatsby-plugin-offline: ^3.2.17 => 3.2.17
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.6.19 => 2.6.19
    gatsby-plugin-sitemap: ^2.4.11 => 2.4.11
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10
    gatsby-source-filesystem: ^2.3.19 => 2.3.19
    gatsby-source-stripe: ^3.1.1 => 3.1.1
    gatsby-transformer-remark: ^2.8.25 => 2.8.25
    gatsby-transformer-sharp: ^2.5.11 => 2.5.11
    gatsby-transformer-yaml: ^2.4.10 => 2.4.10
  npmGlobalPackages:
    gatsby-cli: 2.7.47
```

**Comment by TylerBarnes** [comment]
Hi @brettdewoody , if all of the items in the sequence will be of the `StripeProduct` type, you can do what's in your code example. If they can be of any node type, you'll need to create a new node interface type using the `@nodeInterface` extension https://www.gatsbyjs.org/docs/schema-customization/#queryable-interfaces-with-the-nodeinterface-extension.

The only problem is I believe any type you want to show up in this list will need to implement your new node interface type and I'm not totally sure how to filter or modify types to have existing types do this. @vladar do you have an idea?

**Comment by brettdewoody** [comment]
@TylerBarnes What's in my code example works. But what if I merely have a sequence of IDs which I want to map to `StripeProduct` types. Like:

```
- product1
- product2
- product3
```

Something like this (it doesn't work)?

```
type BoxYaml implements Node {
  [StripeProduct] @link(by: "id")
}
```

**Comment by vladar** [comment]
@brettdewoody Interesting question. Can you show how `BoxYaml` type looks like without schema customization when you use a simple array of scalars:

```yaml
- product1
- product2
- product3
```

For me it looks like this (when using `gatsby-transformer-yaml`):

```json
{
  "data": {
    "allBoxYaml": {
      "nodes": [
        {
          "__typename": "BoxYaml",
          "_0": "p",
          "_1": "r",
          "_2": "o",
          "_3": "d",
          "_4": "u",
          "_5": "c",
          "_6": "t",
          "_7": "1"
        },
        {
          "__typename": "BoxYaml",
          "_0": "p",
          "_1": "r",
          "_2": "o",
          "_3": "d",
          "_4": "u",
          "_5": "c",
          "_6": "t",
          "_7": "2"
        },
        {
          "__typename": "BoxYaml",
          "_0": "p",
          "_1": "r",
          "_2": "o",
          "_3": "d",
          "_4": "u",
          "_5": "c",
          "_6": "t",
          "_7": "3"
        }
      ]
    }
  }
}
```

I doubt that schema customization can help here.

But if I change YAML contents to:

```yaml
- product: 1
- product: 2
- product: 3
```

Then I get this:
```json
{
  "data": {
    "allBoxYaml": {
      "nodes": [
        {
          "__typename": "BoxYaml",
          "product": 1
        },
        {
          "__typename": "BoxYaml",
          "product": 2
        },
        {
          "__typename": "BoxYaml",
          "product": 3
        }
      ]
    }
  }
}
```

And in this case, you can customize the type like this:

```graphql
type BoxYaml implements Node {
  product: StripeProduct @link
}
```
But keep in mind that the type describes a single element of the array in this case, not the whole array.

**Comment by brettdewoody** [comment]
@vladar Nice, that did the trick. I was seeing exactly what you described. Adding a `product` key to each node allowed me to use the `schemaCustomization`. 

Closing this as resolved.

**Comment by arsinclair** [comment]
@vladar's comment was actually very helpful in resolving an issue I have spent hours debugging.

Gatsby was reading a JSON file with localization strings for a website, and GraphQL schema format should have been like this:
```
allStrings {
  nodes {
    string_name_1 {
      string_name_1
      language
    }
  }
}
```
but I was receiving:

```
allStrings {
  nodes {
    _0 {
      string_name_1 {
        string_name_1
        language
      }
    }
  }
}
```

Turns out, my JSON wasn't formatted well, the string collection was an array, instead of an object.

So in my _en.json_, _fr.json_, and other language files. instead of 
```json
[{
    "string_name_1": "some text",
    "string_name_2": "some other text"
}]
```

it should have been

```json
{
    "string_name_1": "some text",
    "string_name_2": "some other text"
}
```
