### ISSUE TITLE
Cloud Deploy fail on svg import but works locally with gatsby deploy

### ISSUE THREAD

**Issue by AdamQuadmon** [gatsbyjs/gatsby#25992]
## Description

Deploying to Gatsby Cloud or Netlify Cloud fail with this error:

```
1:58:21 AM: error Generating JavaScript bundles failed
1:58:21 AM: Can't resolve '../icons/coffee.svg' in '/opt/build/repo/src/components'
1:58:21 AM: If you're trying to use a package make sure that '../icons/coffee.svg' is installed. If you're trying to use a local file make sure that the path is correct.
```

I'm using gatsby-plugin-react-svg

```
    {
      resolve: `gatsby-plugin-react-svg`,
      options: {
        rule: {
          include: /icons/,
          omitKeys: ['xmlnsDc', 'xmlnsCc', 'xmlnsRdf', 'xmlnsSvg', 'xmlnsSodipodi', 'xmlnsInkscape']
        }
      }
    },
```

in src/components/MyComponent.js
```
import Coffee from "../icons/coffee.svg";
//...
<Coffee />
```

This renders correctly on local builds but builds fail on the cloud.

### Steps to reproduce

The problem happens on cloud deploy, can't reproduce locally

### Environment

  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 3.8.2 - /Users/lucianoamodio/.pyenv/shims/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 74.0
    Safari: 13.1.1
  npmPackages:
    gatsby: 2.24.10 => 2.24.10 
    gatsby-background-image: ^1.1.1 => 1.1.1 
    gatsby-background-image-es5: ^1.1.1 => 1.1.1 
    gatsby-image: ^2.2.3 => 2.4.13 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-gtag: ^1.0.13 => 1.0.13 
    gatsby-plugin-manifest: 2.4.20 => 2.4.20 
    gatsby-plugin-offline: ^3.2.1 => 3.2.20 
    gatsby-plugin-postcss: ^2.0.7 => 2.3.11 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: 3.3.10 => 3.3.10 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.3.10 => 2.3.12 
    gatsby-plugin-sharp: ^2.2.1 => 2.6.21 
    gatsby-source-filesystem: ^2.1.1 => 2.3.22 
    gatsby-transformer-remark: ^2.5.0 => 2.8.26 
    gatsby-transformer-sharp: ^2.2.0 => 2.5.11

**Comment by AdamQuadmon** [comment]
I did a successful deploy removing the svg icon include from my component.
How can I fix the svg import?

**Comment by TylerBarnes** [comment]
Hi @AdamQuadmon !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by AdamQuadmon** [comment]
Solved! Was not a gatsby issue but a .gitignore one.

My local .gitignore was preventing /icon folder to be added to git.
I had another similar issue related to git not updating a filename case change (footer.js renamed to Footer.js), so I double-checked on my GitHub repo and I found the missing icon folder.
