### ISSUE TITLE
Styled components does not hot reload

### ISSUE THREAD

**Issue by bobissict** [gatsbyjs/gatsby#2599]
I'm using the Gatsby starter blog with styled components and the hot reloading does not work. It works for everything else, changing JSX etc but it just won't pick up changes from styled components forcing me to have to manually reload the page.

I've tried a bunch of things but nothing seems to work.

I'd appreciate any help as it's driving me crazy.

**Comment by danoc** [comment]
@bobissict – Are you seeing this warning in your console?
![image](https://user-images.githubusercontent.com/916038/31968031-ab105c72-b8c4-11e7-9e39-9194f457f8e1.png)

I haven't dug into this at all but see this warning often.

**Comment by bobissict** [comment]
super weird, i have another gatsby site that I setup with the `gatsby-blog-starter` which the hot reloading works. I just ended up cloning that site and using it.

Gonna just mark this as closed unless I can recreate the issue again

**Comment by KyleAMathews** [comment]
There was a recent PR that fixed hot reloading for some stuff so perhaps the older site just needed upgraded.

**Comment by pgegenfurtner** [comment]
I've got the same problem here. I created a new gatsby project based of the default starter, then added the gatsby-plugin-styled-components, imported styled-components and created the first one in pages/index.js

When I create a new styled component and use it, hot reloading works fine, but as soon as I change a property of a already loaded styled-component, the hot reload doesn't work and I have to manually refresh.

I can see the classes of the component hot reloading, but the css itself stays old.

I'm on the newest gatsby version (1.9.80)

**Comment by monsieurnebo** [comment]
Same problem here ✋ 

I can see the concerned class beeing updated, but the new properties don't show up.

**Versions:**
```
gatsby@1.9.97
├── gatsby-plugin-styled-components@1.0.5
```

**Comment by KyleAMathews** [comment]
Sounds like this is the problem https://github.com/styled-components/styled-components/issues/1225

More discussion here: https://spectrum.chat/gatsby-js?thread=b7270640-d077-411f-bda8-0b06a4f67bd3

**Comment by KyleAMathews** [comment]
If you downgrade styled components to v2.2.0 it works apparently.

**Comment by monsieurnebo** [comment]
@KyleAMathews I just tested with **v2.2.0**, it's working fine.

**Comment by greglobinski** [comment]
@KyleAMathews Thank you

**Comment by Nick-vr** [comment]
Downgrading to v2.0.0 did not fix the problem for me.

**Comment by nathanjdunn** [comment]
Similarly to @Nick-vr, I'm also having this issue

**Comment by ziyafenn** [comment]
@nathanjdunn @Nick-vr uninstall the styled-components package and run this again:
`npm install --save gatsby-plugin-styled-components styled-components@2.2.0`

**Comment by Nick-vr** [comment]
@ziyafenn Thank you!

**Comment by monsieurnebo** [comment]
Seems fixed by https://github.com/styled-components/styled-components/releases/tag/v2.2.4

**Comment by KyleAMathews** [comment]
Great! Closing this now.
