### ISSUE TITLE
404s for GraphQL Query Options Reference  examples

### ISSUE THREAD

**Issue by tjcrowder** [gatsbyjs/gatsby#26017]
## Description

I'm getting 404s for the examples in the [GraphQL Query Options Reference page](https://www.gatsbyjs.org/docs/graphql-reference/). I'm fairly sure this is a new issue, I _think_ I've been on that page in the last few days before and had the examples be there. It's not browser-specific (I tried Brave, Chrome, and Firefox).

(I initially clicked "Documentation" to report this, but that was oriented on creating/improving documentation rather than reporting a bug delivering the documentation.)

### Steps to reproduce

1. Go to https://www.gatsbyjs.org/docs/graphql-reference/
2. Wait a moment
3. Note that 404s appear for the examples as in the following screenshot. It's every example except the one-liner JavaScript example about filtering on multiple fields.

![gatsby-404](https://user-images.githubusercontent.com/27634/88454601-b19d0600-ce68-11ea-8cba-ee5214bf39d3.png)

**Comment by iamdarshshah** [comment]
@tjcrowder It seems to be a duplicate issue. You can check this discussion #25852 as it's similar to what you have described.

Also, It works for me. Check the screenshot. Need to check what's something we are missing out with this. You can follow along with the discussion #25852. Closing this issue for now. 

Thanks 👍 

> Screenshot
![Screenshot (67)](https://user-images.githubusercontent.com/25670841/88535751-25d1d800-d028-11ea-8035-f49d2960ce65.png)
