### ISSUE TITLE
Keeping a local copy of theme with updated dependencies

### ISSUE THREAD

**Issue by Hrishikesh-K** [gatsbyjs/gatsby#26013]
## Summary

Hello.

I am trying to use a Gatsby theme-based starter and it works great and all. It uses Theme-UI, but, the current Theme-UI in its `package.json` is way older than then latest version, thus not letting me use a specific property. But, it's not just Theme-UI, rather, most dependencies used by the theme are outdated. Now, I can't expect the developer to keep updating the node package every time a dependency is updated. So, I was willing to know if and how exactly can I keep the dependencies of the theme updated, as manually changing its `package.json`, is not something I think I should be doing. Since it's not just that theme specific question, and rather an overall question about themes (as I guess all themes would have this problem), I decided to ask it here. I'm sorry if I was wrong and this issue can be closed.

I tried reading the official documentation on themes, but, it talks about creating one from scratch in most cases. Even then, I tried placing the theme folder in the same folder as my `gatsby-config.js`, or even in `plugins` folder (and defined it as a plugin in my config), but, that's didn't work.

**Comment by LekoArts** [comment]
Thank you for opening this!

You have two simpler options:

1) Fork the theme and publish it as your own on npm
2) Use [`yarn resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to set the specific versions

Normally you won't need to update the theme itself every day as when the developer uses version carets like `^2.1.1` all versions on `v2` will be automatically used when installing the theme. In case of Theme UI this doesn't work (as it's on the v0 spectrum).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
