### ISSUE TITLE
styled-components + use-dark-mode: Theme styles inconsistent between deep page reloads

### ISSUE THREAD

**Issue by WillTheVideoMan** [gatsbyjs/gatsby#26024]
## Description

When using `use-dark-mode`, `gatsby-plugin-use-dark-mode` alongside `styled-components` and `gatsby-plugin-styled-components`, theme style rules are not consistently applied to components when a deep reload (`CTRL + F5`, cleared cache) is performed. In the example below, the background (set in a `styled-components` global style) is styled as per the dark theme, but the title text of the heading and the first child component reverts to the default light theme. Oddly enough, all the other child components render just fine in the dark theme... except not really because their SVG background dotted lines are all missing. Dumbfounded!

![personal-gatsby-not-working](https://user-images.githubusercontent.com/29780384/88467896-075ac800-ced4-11ea-84b5-ad45322d7b0b.gif)

Try it out: https://willhall-uk-phw179v7m.vercel.app/

This issue arises only when the site is built with `gatsby build`, and is not seen when using the development server. I am also using the `gatsby-plugin-offline`, but when removing this plugin in my testing and clearing all application data from the browser (plus the Gatsby `.cache` between builds), the issue still persists.

If the default theme is set to dark, the same issue persists; but inverted, such that the background is in light theme and the text is in dark theme (i.e. a light font colour).

To preface this, I apologise if this does not fall into the bounds of a Gatsby issue, as it could also easily be something completely outside the scope of the repository, or also just some shoddy work on my part. I have a feeling it is something to do with SSR and hydration, and so might be in the scope of Gatsby. Nevertheless, the glance of experienced eyes would be greatly appreciated.

I appreciate your time. Cheers! ✌️

### Steps to reproduce

I have created a minimal reproduction to hopefully ease the solving of this mystery.

Repo: https://github.com/WillTheVideoMan/gatsby-repro-dark-mode
Try it out: https://gatsby-repro-dark-mode.vercel.app/

The steps are as follows:

1. Have a couple of themes in a object with keys of some styling value. Here they are `light` and `dark`. `dark` spreads over `light`, which would be useful if `light` were to contain some shared keys:
```javascript
const light = {
  colours: {
    primary: "black",
    accent: "#eee",
    background: "white",
  },
}

const dark = {
  ...light,
  colours: {
    primary: "white",
    accent: "#333",
    background: "#111",
  },
}
```
2. Have a constant which holds the `useDarkMode` hook context (from `use-dark-mode`):
```javascript
const darkMode = useDarkMode(false);
```
3. Use that constant to inform the `<ThemeProvider />` (from `styled-components`) of which theme to use, like so: 
```javascript
<ThemeProvider theme={darkMode.value ? themes.dark : themes.light}>
   {children}
</ThemeProvider>
```
4. Have two children. One is a global style, created with `createGlobalStyle` from styled-components. The other is any old component, but it might be helpful to have some theme toggling functionality here. Both children consume `props.theme` somewhere in their styling to gain their looks.
5. Clear the browser site data. Run a fresh clean build.
6. Visit the site, and toggle dark mode.
7. Smash `CTRL + F5` on the keyboard.
8. Watch as the dark background remains, but the light theme text colour also shows.

### Expected result

![gatsby-develop-working](https://user-images.githubusercontent.com/29780384/88467762-733c3100-ced2-11ea-8c24-d3aa862ae5d4.gif)

The theme is properly applied after a full refresh. The background and text both match the same theme.

> The example above shows the desired behaviour using the development server.

### Actual result

![gatsby-build-not-working](https://user-images.githubusercontent.com/29780384/88467680-6c60ee80-ced1-11ea-981f-8f5ac72c1931.gif)

The theme application is somewhat sporadic and does not properly persist. In some places, the theme is matched, in others, not. 

### Environment

```
  System:
    OS: Linux 5.3 elementary OS 5.1.6 Hera
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 79.0b7
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12
    gatsby-image: ^2.4.9 => 2.4.9
    gatsby-plugin-manifest: ^2.4.14 => 2.4.14
    gatsby-plugin-offline: ^3.2.21 => 3.2.21
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.6
    gatsby-plugin-sharp: ^2.6.14 => 2.6.14
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10
    gatsby-plugin-use-dark-mode: ^1.1.2 => 1.1.2
    gatsby-source-filesystem: ^2.3.14 => 2.3.14
    gatsby-transformer-sharp: ^2.5.7 => 2.5.7
  npmGlobalPackages:
    gatsby-cli: 2.12.51
```

**Comment by LekoArts** [comment]
Closing as stale. If you still see this behavior in the latest Gatsby v3 please open a new issue.
