### ISSUE TITLE
How can I use gatsby-plugin-offline to create a completely offline version of my site? Automatically download all the pages, images, etc?

### ISSUE THREAD

**Issue by raymestalez** [gatsbyjs/gatsby#26033]
Hi! I'm looking for some help. I want people to be able to go to my Gatsby website, click "Add to Home Screen", and then be able to browse the site completely offline.

I want to download the whole website (images, javascript, all the pages, everything) automatically, without users having to open each page for it to get cached.

I know that Gatsby has `gatsby-plugin-offline`, and it sounds like it should make this sort of thing possible, but I can't figure out how to configure it correctly. Just uncommenting the plugin didn't do the trick.

Can you help me find the correct config for accomplishing that?

**Comment by flikteoh** [comment]
```
{
    resolve: 'gatsby-plugin-offline',
    options: {
      workboxConfig: {
      globPatterns: ['**/*'],
      },
    },
},
```

This would do that. However, do note that hell will break loose if you're having a large website.

Your users will download a large amount of data they have yet needed or don't need at all.

Also it is a bad idea to cache pages as you may update them in future and possibly causes stale content.

Not sure if it is even good idea to cache the whole site offline, so use with caution!

**Comment by raymestalez** [comment]
Thank you!
