### ISSUE TITLE
Connect gatsby-source-graphql with GraphQL endpoint in Drupal : Runtime error

### ISSUE THREAD

**Issue by iomack** [gatsbyjs/gatsby#26040]
Hello
## Summary
Me and my team are creating a decoupled Drupal website. 
We decided to use the Drupal module GraphQL that gives a GraphQL endpoint and to use on Gatsby's side the plugin gatsby-source-graphql.
The plugin gatsby-source-drupal was not really better for our needs.
The problem starts with the fact that gatsby-source-graphql asks in its configuration for a fieldName, lets call it "drupal".
For the typeName, asked again by the plugin, we use also the name "drupal".
So, every query has this form: 
`
   query {  
      drupal{  
        blockContentById(id: "5") {  
          ... on drupal_BlockReference {  
            entityId  
            fieldTitle  
            fieldContentLink {  
              url {  
                path  
              }  
            }  
          }  
        }  
     }  
}
`
So, will on build time everything works great and the plugin can get data from the Drupal endpoint, on runtime it fails.
On Drupal side, I get errors like: "LogicException : Missing type drupal_BlockReference ..." because it expects just "BlockReference" there. 
My question is why on build time the prefix "drupal_" is ignored and we are able to fetch data from Drupal and on runtime the prefix exists and breaks the queries?

Thank you for all your help in advance.

### Environment (if relevant)

  System:
    OS: Linux 4.18 CentOS Linux 8 (Core)
    CPU: (16) x64 Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.21.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  npmPackages:
    gatsby: ^2.23.3 => 2.24.7
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.4.7 => 2.4.13
    gatsby-plugin-antd: ^2.2.0 => 2.2.0
    gatsby-plugin-apollo: ^3.0.1 => 3.0.1
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.4.11 => 2.4.19
    gatsby-plugin-offline: ^3.2.9 => 3.2.19
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.10
    gatsby-plugin-remote-images: ^2.1.0 => 2.2.0
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0
    gatsby-plugin-sass: ^2.3.6 => 2.3.12
    gatsby-plugin-scroll-reveal: ^0.0.7 => 0.0.7
    gatsby-plugin-sharp: ^2.6.11 => 2.6.20
    gatsby-source-filesystem: ^2.3.11 => 2.3.20
    gatsby-source-graphql: ^2.5.7 => 2.6.2
    gatsby-transformer-sharp: ^2.5.5 => 2.5.11

### File contents (if changed)
Using apollo-client. Configuration:

import ApolloClient from 'apollo-boost';  
import fetch from 'isomorphic-fetch';  
  
export const client = new ApolloClient({  
  uri: "https://drupalsiteexample.com/graphql/",  
  fetch,  
});  

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by blainekasten** [comment]
cc'ing @smthomas - our Drupal expert

**Comment by smthomas** [comment]
@iomack When you say your "Runtime" queries do not work, I'm assuming this means you are making queries from within your Gatsby site directly to the live Drupal GraphQL server. Is this correct?

The gatsby-source-graphql module requires the prefix because you may need to connect multiple GraphQL endpoints to a single Gatsby site and the prefix provides a way to identify them.

If you need a way to run the same queries at build time and at runtime, others have written some type of middleware function to remove the prefixes before executing the "runtime" queries.

I should also note that we are at the early stages of writing a gatsby-source-drupal-graphql source plugin that will improve a lot of the challenges you will likely run into with gatsby-source-graphql. It's likely still a month or two from being ready.

**Comment by iomack** [comment]
@smthomas  Thank you for your answer.
I am sorry for not being more clear. I mean exactly what you supposed. We run the same queries on build time  and directly to the live Drupal GraphQL server.
I will examine the "middleware function" solution.
I am also really glad to hear for this new source plugin you are developing!

Thank you once again. 
For me the issue is solved.
