### ISSUE TITLE
withPrefix not working as expected: __BASE_PATH__ is undefined error 

### ISSUE THREAD

**Issue by doubledherin** [gatsbyjs/gatsby#26048]
## Description

I've been trying to troubleshoot why my use of the `withPrefix` function doesn't seem to be working in production on my GH Pages site. Here is a snippet of the code where I use `withPrefix` with `createPage`, in my `gatsby-node.js` file (link to the code is [here](https://github.com/doubledherin/again/blob/master/gatsby-node.js#L53)):

Note that if don't set the second argument to `withPrefix`, I get `__BASE_PATH__ is undefined` when I run `npm run deploy`. 

```
exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions
  const result = await graphql(`
    query {
      allImageSharp {
        nodes {
          fields {
            slug
          }
        }
      }
    }
  `)
  result.data.allImageSharp.nodes.forEach(node => {
    if (node && node.fields) {
        createPage({
        path: withPrefix(node.fields.slug, ''),
        component: path.resolve(`./src/templates/galleryItemPage.js`),
        context: {
          // Data passed to context is available
          // in page queries as GraphQL variables.
          slug: node.fields.slug,
        },
      })
    }
  })
}
```
I am defining my `pathPrefix` in a `config.js` file (link [here](https://github.com/doubledherin/again/blob/master/config.js)), which gets read in by my `gatsby-config.js` file. 

From my `config.js` file:

```
module.exports = {
  siteAuthor: '',
  siteTitle: '',
  siteShortTitle: '',
  siteDescription: '',
  siteShortDescription: '',
  siteKeywords: 'comma, separated, list', // Replace this with your SEO keywords
  siteUrl: 'https://doubledherin.github.io',
  pathPrefix: '/again',
  siteLanguage: 'en',
  get copyright() {
    return `Copyright \u00A9 ${new Date().getFullYear()} ${this.siteAuthor}`;
  }, // Returns copyright string with year of last build
}
```

My `gatsby-config.js` file:

```
const config = require('./config')

const pathPrefix = config.pathPrefix === '/' ? '' : config.pathPrefix

console.log("GATSBY PATH PREFIX: ", pathPrefix) // <-- CONFIRMED: this logs '/again'

module.exports = {
  siteMetadata: {
    author: config.siteAuthor,
    title: config.siteTitle,
    description: config.siteDescription,
    siteUrl: config.siteUrl + pathPrefix,
    settings: { ...config },
  },
  plugins: [
    `gatsby-plugin-sass`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src`,
      },
    },
  ],
  pathPrefix,
}
```

I've confirmed that `pathPrefix` really is set to `/again` here.

However, since it wasn't working (that is, the `/again` prefix wasn't showing up in the URL path), I looked at the implementation of `withPrefix` in the [gatsby code](https://github.com/gatsbyjs/gatsby/blob/83926c8ff1df55898ffdeb49183163b5f0bc4270/packages/gatsby-link/src/index.js#L12-L40) and it seems like it depends on `__PATH_PREFIX__` and/or `__BASE_PREFIX__` variables. Mine both seem to be set to the empty string. 

[This is from some logging in on my gallery page ](https://github.com/doubledherin/again/blob/master/src/pages/gallery.jsx#L9-L11)-- I gathered based on this issue that these variables are not on the window object (and I checked, it wasn't there) nor set as environment variables.

```
  console.log("PATH PREFIX ON process.env: ", process.env.__PATH_PREFIX__) // Yields undefined
  console.log("PATH PREFIX IS EMPTY STRING: ", __PATH_PREFIX__ === '') // Yields true
  console.log("BASE PATH IS EMPTY STRING: ", __BASE_PATH__ === '') // Yields true
```

It looks like `__PATH_PREFIX__` and `__BASE_PATH__` are set [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L199-L200), based on whether `program.prefixPaths` is truthy. I'm not sure, but I'm assuming that `program.prefixPaths` is `true` if the `--prefix-paths` tag is used. 

For my deployment, it is used. Here is a snippet from my `package.json`.

```
  "scripts": {
    "clean": "gatsby clean",
    "reset": "rm -rf .cache/ public/ node_modules/ package-lock.json",
    "prep": "rm -rf .cache/ public/ node_modules/ && npm ci",
    "develop": "DEBUG=gatsby* gatsby develop --verbose",
    "build": "DEBUG=gatsby* gatsby build --verbose",
    "serve": "DEBUG=gatsby* gatsby serve --verbose",
    "test": "echo \"Error: no test specified -- https://gatsby.app/unit-testing/\" && exit 1",
    "deploy": "gatsby build --prefix-paths && gh-pages -d public"
  },
```

So, since my build *should* be setting `program.prefixPaths` to `true`, and since `pathPrefix` is set in my config, I don't understand why __PATH_PREFIX__ is the empty string when I deploy.

[Here](https://github.com/doubledherin/again) is a link to my repo. The `master` branch is up to date with what I've deployed, and if you want to see what was built, you can look at the `gh-pages` branch.

### Steps to reproduce

Go to my deployed site's "gallery" page (here https://doubledherin.github.io/again/gallery/) and click on a gallery item. 

### Expected result

You should be redirected to "/again/p5/<image filename>".

### Actual result

You are redirected to "/p5/<image filename>" without the /again prefix, resulting in a 404.

### Environment
```
Run `gatsby info --clipboard` in your project directory and paste the output here.
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.14.7 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 72.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.24.11 => 2.24.11
    gatsby-image: ^2.4.0 => 2.4.0
    gatsby-plugin-sass: ^2.3.1 => 2.3.1
    gatsby-plugin-sharp: ^2.6.0 => 2.6.0
    gatsby-plugin-typography: ^2.5.0 => 2.5.0
    gatsby-source-filesystem: ^2.3.0 => 2.3.0
    gatsby-transformer-sharp: ^2.5.0 => 2.5.0
  npmGlobalPackages:
    gatsby-cli: 2.8.29
```

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
