### ISSUE TITLE
gatsby-plugin-offline service worker registration timing

### ISSUE THREAD

**Issue by tavelli** [gatsbyjs/gatsby#26059]
## Summary
service worker seems to be registered early in render, may be hurting initial performance in some cases

## Relevant information
when reviewing a recent trace of one of my gatsby sites i noticed the service worker js and related libs like workbox were loading ahead of critical path resources like api calls. im not suggesting they were blocking necessarily but it still seemed odd to have them loaded so early in the render. 

looking into the generated output from a build it seems like service worker registration happens `onClientEntry` which as i understand is pretty early in page rendering lifecycle

````
Object(r.apiRunnerAsync)("onClientEntry").then(function() {
          Object(r.apiRunner)("registerServiceWorker").length > 0 && n("NSX3")
````

this article suggests moving service worker registration to the load event to avoid perf issues with primary content: https://www.thecodeship.com/web-development/guide-service-worker-pitfalls-best-practices/

````
window.addEventListener('load', () => {
      navigator.serviceWorker.register('sw.js');
    });
````

anyway was wondering if this is something that has been thought through already and there is a reason for loading early? maybe there is a possibility of configuring when in page lifecycle service worker is registered in `gatsby-plugin-offline` config might be an option?

**Comment by pvdz** [comment]
If your assumption holds then I like this idea. There might be a reason the SW is registered that early, though, so we'd have to make sure such a change doesn't break anything.
