### ISSUE TITLE
gatsby-plugin-feed: how to apply path prefix to urls?

### ISSUE THREAD

**Issue by jorrit** [gatsbyjs/gatsby#26066]
I am using gatsby-plugin-feed to build a feed for a website. The site uses the pathPrefix functionality in production. Normally, one can use `withPrefix` function to add the prefix to a url when in production and add no prefix while developing.

The RSS serializes function however, is defined in gatsby-config.js and when loading the `withPrefix` function it displays this error:

```
__BASE_PATH__ is not defined
```

How can I add a prefix to a url in gatsby-config without repeating all the logic in gatsby-cli to combine `process.argv` and `env.PREFIX_PATHS`.

**Comment by pvdz** [comment]
You could try `global.__BASE_PATH__`.

**Comment by jorrit** [comment]
That variable is undefined at that point. I think `__BASE_PATH__` is only available for code run 'inside' webpack and the configuration is read outside webpack.

**Comment by pvdz** [comment]
Right. I'm not sure who can help with this at the moment. The rss plugin does not really have a clear owner right now. I guess we're open to a PR to handle this? :)
