### ISSUE TITLE
[gatsby-remark-prismJs] line highlighting does not work properly with 'triple-quoted-string'

### ISSUE THREAD

**Issue by Skurrr** [gatsbyjs/gatsby#26079]
## Description

Line hightlighting does not work for language python when line is inside span 'triple-quoted-string'.

### Steps to reproduce
project: https://github.com/Skurrr/prismJsBug
run gatsby serve
go to: http://localhost:8000/test/
inspect html dom:
![obraz](https://user-images.githubusercontent.com/32570288/88693040-1a9dab80-d0ff-11ea-9b78-b6a381faf4af.png)
### Expected result
markdown structure shouldn't be altered. 
lines 2 and 3 should be highlighted

### Actual result
Span 'triple-quoted-string' seems to be messy, as result first string line is moved to the same line as """. Whole triple-quoted-string span is marked for highlighting, i would expect that below lines are highligted(see /src/markdow-pages/test.md)

-  opening docString: `"""`

- first text line:     This is a one line description of the bbue CDA Module.

### Environment

 System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.18.1 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Firefox: 72.0.2
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12
    gatsby-remark-prismjs: ^3.5.10 => 3.5.10
    gatsby-source-filesystem: ^2.3.23 => 2.3.23
    gatsby-transformer-remark: ^2.8.27 => 2.8.27
  npmGlobalPackages:
    gatsby-cli: 2.12.67

**Comment by Skurrr** [comment]
Update:
Issue has been narrowed down to specific scenario:
-for 'triple-quoted-string' line highlighting is broken when user try to highlight line that contains opening """ regex.

**Comment by pieh** [comment]
Hey @Skurrr https://github.com/Skurrr/prismJsBug.git is `hello-world` starter without markdown/prismjs - could you update repro?

**Comment by Skurrr** [comment]
Hey @pieh 
Repo has been updated.

**Comment by pieh** [comment]
Thanks. Opened https://github.com/gatsbyjs/gatsby/pull/26161 with the fix

**Comment by Skurrr** [comment]
@pieh Thanks for support!
