### ISSUE TITLE
[www] gatsby-remark-prismjs only working partially

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#2607]
`<div class="gatsby-highlight" />` is not wrapping code blocks on [gatsbyjs.org](https://www.gatsbyjs.org/), see e.g. https://www.gatsbyjs.org/tutorial/part-one/#linking-between-pages: 

![image](https://user-images.githubusercontent.com/21834/31961144-2931c994-b8fa-11e7-9044-281de0c5d9fb.png)

`.gatsby-highlight-code-line` on the other hand is applied correctly as well as the `language-*` class for `<pre>`.

FWIW this works fine in examples/using-remark:

![image](https://user-images.githubusercontent.com/21834/31961290-9c1fcd70-b8fa-11e7-8246-93cbf3932b60.png)

**Comment by KyleAMathews** [comment]
Hmmm that's odd. Perhaps that line highlighting breaks tag nesting is what's biting us here?

**Comment by fk** [comment]
So … this is working again!

**Comment by KyleAMathews** [comment]
Wait really? What changed?

**Comment by fk** [comment]
Dunno :( … just noted https://www.gatsbyjs.org/tutorial/part-one/#linking-between-pages looks good again – `.gatsby-highlight` is back: 
![image](https://user-images.githubusercontent.com/21834/32738484-65c6ec42-c89d-11e7-86f7-401ead3f0249.png)

**Comment by KyleAMathews** [comment]
Well haha I guess we'll close this issue then :-D
