### ISSUE TITLE
[gatsby-plugin-netlify] Documenting redirects

### ISSUE THREAD

**Issue by avigoldman** [gatsbyjs/gatsby#2608]
It looks like the ability to add redirects was added in #2191. It doesn't look like there are any docs around actually adding them though. What I'm missing?

(Once I understand this, I'll make a PR on the docs 😅)

**Comment by rdela** [comment]
@avigoldman good news! I have a PR more or less ready for this. Let me open it again, take a look and update to current, then I will update this issue

**Comment by rdela** [comment]
@avigoldman if you get a chance to look at the example let me know if anything needs clarification please! https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redirects

**Comment by avigoldman** [comment]
That definitely helps @rdela! I'm not seeing any mention of Netlify there, though. Does it tie into the `createRedirect` function?

**Comment by rdela** [comment]
Yes, @KyleAMathews posted link to how the Netlify plugin uses `createRedirect` at bottom of #2511 https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify/src/create-redirects.js

Searching the repo for “redirect” turns that and a few other things up “createRedirect” search in example does not https://github.com/gatsbyjs/gatsby/search?q=redirect

**Comment by rdela** [comment]
@avigoldman I mention several other issues and merged PRs in #2633 it may help to sift through. We should document or add another example for anything that you think still needs it. Maybe in…
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify/README.md
and/or we add a Netlify section to 
https://www.gatsbyjs.org/docs/deploy-gatsby/ /
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/deploy-gatsby.md

I signed up for Netlify but have not tried the example there yet, anything in particular you are looking to understand better or extend about redirection on Netlify side?

**Comment by avigoldman** [comment]
At this point, I think I have a pretty decent understanding so I'll open a PR on the `gatsby-plugin-netlify` README.md and share it here.

**Comment by avigoldman** [comment]
Took a while, but I've got that PR ready 😅 @rdela mind giving it a look?
