### ISSUE TITLE
GraphQL query differs between GraphiQL and develop/build

### ISSUE THREAD

**Issue by yoannfleurydev** [gatsbyjs/gatsby#26084]
## Description

Some queries are working in GraphiQL as expected, but when copy/pasting in source code and then running develop or build it doesn't work as expected, the nodes are empty.

### Steps to reproduce

1. `git clone https://github.com/CodeursEnSeine/codeursenseine-new`
2. `cd codeursenseine-new`
3. `git checkout gatsby-issue-debug`
4. `yarn install`
5. `yarn start`
6. Go to [localhost:8000/meetups](http://localhost:8000/meetups)

Everything is in the file [`src/pages/meetups/index.js`](https://github.com/CodeursEnSeine/codeursenseine-new/blob/gatsby-issue-debug/src/pages/meetups/index.js) if you are looking for the source of this page 🙂 

### Expected result

The page should have content (cards with a title, a location and a date), and an `Array` with object values should be printed in the developer tools console. The GraphQL query for `meetups` is working in GraphiQL, but not while developing or building the site.

### Actual result

Check the developer tools console, it's printing an empty `Array`, and the content under "Tous les meetups" (i18n: "All the meetups") is empty.
The `console.log()` is [this one](https://github.com/CodeursEnSeine/codeursenseine-new/blob/gatsby-issue-debug/src/pages/meetups/index.js#L11)

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/3920615/88713985-6f035400-d11c-11ea-8364-e068fa0a8696.png">

### Environment

`gatsby info` is returning an error:

```
 ERROR

UNHANDLED REJECTION (e || []).filter is not a function



  TypeError: (e || []).filter is not a function

  - envinfo.js:1
    [ces-test]/[envinfo]/dist/envinfo.js:1:73314

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5

  - async Promise.all
```

I'm using **Node.js** `v12.18.1`, **yarn** `1.22.4`, and all the other information are in the repository https://github.com/CodeursEnSeine/codeursenseine-new, on branch `gatsby-issue-debug`.

For mote context and information you can also check [a post I did on spectrum.chat](https://spectrum.chat/gatsby-js/general/correct-graphiql-results-are-sometimes-not-working-in-develop-and-build~d72c8a7f-fd61-42e9-90a5-b7e2c8aa8075).

Hope I have been clear enough, and I will be available to answer your questions if you have any. 😃 

You are doing an awesome job, thanks a lot for Gatsby 👍

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v4 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

[reproduction]: https://gatsby.dev/reproduction
