### ISSUE TITLE
Share GraphQL queries between Gatsby and graphql-request

### ISSUE THREAD

**Issue by tlgimenes** [gatsbyjs/gatsby#26105]
Hello People. First of all, I'm really enjoying Gatsby

## Summary
I'm trying to create an e-commerce web app with about 3 million pages. Building all of these pages at once can be a little bit troublesome and slow. 

For solving this problem, me and my team are trying to explore the huge "pareto" e-commerce websites have. The strategy is to generate only the most visited 1k pages, and let the rest be all client-side rendered.

## Relevant information
This hybrid rendering approach is basically achieved with two templates:
```
├── templates
│   ├── product
│   │   ├── client.tsx
│   │   └── server.tsx
```

`server.tsx` queries the Gatsby's GraphQL API for product data, thus server side rendering the whole page, whereas `client.tsx` only contains code for fetching and rendering on client side

So far, we've managed to solve all problems with routing and fetching. However, we still have one last problem to solve. Since we have an external GraphQL API, we would like to reuse the GraphQL query from `server.tsx` in `client.tsx`, however I couldn't find an straight forward way in doing this. 

My research lead me to this issue (#21935) with similar content about reusing graphql queries on the client-side, however it's closed now and not receiving too much attention.

##  Possible solutions
1. This [plugin](https://github.com/birkir/gatsby-source-graphql-universal) tries to solve this problem. However it seems to use some obscure internals of Gatsby and I'm afraid it will stop working after some release of Gatsby.
2. I know all queries are stored into the redux storage. However, there is no node API hook for accessing it. If we had a onPostExtractQueries we could somehow send these queries to the browser and create a plugin to sort this out for us. Actually, #23679 suggested having this API for another reason
3. Receive the page query via the pageContext API by a feature in gatsby itself

Please let me know if you have some ideas or if I am missing something in here.

Thanks !

**Comment by tlgimenes** [comment]
Just adding another possible solution:

The code below adds a prop called `pageQuery` to the `pageContext`.  The downside of this solution is having to stay in sync with gatsby's internal redux cycles.

```
export const onPreExtractQueries = ({ store }: ParentSpanPluginArgs) => {
  store.subscribe(async () => {
    const {
      lastAction: { type, payload },
      components,
      pages: allPages,
    } = store.getState()

    if (type !== 'QUERY_EXTRACTED') {
      return
    }

    const { componentPath } = payload
    const { query, pages } = components.get(componentPath)

    if (!query) {
      return
    }

    pages.forEach((pagePath: string) => {
      const page = allPages.get(pagePath)

      page.context = { ...page.context, pageQuery: query }
    })
  })
}
```

**Comment by vladar** [comment]
@tlgimenes Thanks for opening this! Your project sounds very exciting 👍 

As for the feature you want - it is not supported out-of-the-box yet. We have a PR: #23423 that will do what you want here. I think you can use the `gatsby-source-graphql-universal` plugin for now (they will likely switch to the new approach when it lands).

Still, you should be aware that `gatsby-source-graphql` plugin has several major drawbacks. They are well-explained here: https://github.com/gatsbyjs/gatsby/pull/23423#issuecomment-623976993

We will probably deprecate it eventually or at least add a warning about those drawbacks. The alternative is to write a [custom solution](https://www.gatsbyjs.org/tutorial/source-plugin-tutorial/) for sourcing data from your GraphQL API into Gatsby.

We are also working on tools that should help you with this: https://github.com/vladar/gatsby-graphql-toolkit (early stage)

I would strongly encourage you to try the `graphql-toolkit`. It may be harder at the beginning but will pay off later, especially if your API supports [delta sourcing](https://github.com/vladar/gatsby-graphql-toolkit#sourcing-changes-delta). I am always willing to help with it on [#gatsby-graphql-toolkit](https://discord.gg/RT2Wqr8) discord channel.

Thanks for using Gatsby 💜

**Comment by tlgimenes** [comment]
Thanks for the quick answer @vladar  !

I didn't know about this graphql-toolkit. Sounds amazing. I will definitely use it.
I will also wait for  #23423 to be merged

Thanks !
