### ISSUE TITLE
[gatsby-source-contentful] - Contentful Reference fields only allow to query for fragments/types that are in use instead of all possible.

### ISSUE THREAD

**Issue by oneextra** [gatsbyjs/gatsby#26112]
## Description

A contentful reference field that can take a number of content-types will only allow me to query for the content types that are actually linked in the content. So if the content only links to 1 or 2 contentypes out of the 6 available, I can only query these 2. And worse I can only compile for querying these two. Any query addressing the possible links to other content types in the future cannot be queried. Making the reference field fairly problematic. 

My workaround so far is to create "dummy contents", each one linking to a different content type so I can include all of these types in my queries. But this is obviously very fragile and not really elegant. 

Is there a way to pass some schema to gatsby-source-contentful, so that it knows beforehand that what I expect link to be is a union of the different content types as specified? Or can it pull the schema directly from contentful?

### Steps to reproduce

- I have a Reference field in Contentful, that allows to take any of the ContentTypes I defined:
![c1](https://user-images.githubusercontent.com/1944911/88845000-5fc1ec00-d198-11ea-9d56-66479c93090a.jpg)
(The restriction doesn't really matter, it is just to show, that these are all contentypes that work with the link, since they have a slug-property defined in our model).

- I have 2 Contents that use this reference field one links to a **Product** another one to a **ProductCategory**. I can query those and ONLY those 2, not all of the above
![image](https://user-images.githubusercontent.com/1944911/88845491-1625d100-d199-11ea-89eb-b40e6c1e3c41.jpeg)

- If I try to query any other content type I get a GraphQL Error on build/develop
![image](https://user-images.githubusercontent.com/1944911/88845687-5edd8a00-d199-11ea-846c-d8d80aba108d.jpeg)
Here I try to query on the ContentType **HomePage**.

```
We've encountered an error: Objects are not valid as a React child (found: GraphQLDocumentError: GraphQLDocumentError: Fragment cannot be spread here as objects of type "ContentfulProductContentfulProductCategoryUnion" can never be of type
"ContentfulHomePage".). If you meant to render a collection of children, use an array instead.

```
### Expected result

I should be able to query for all possible content types. 

After all Contentful does provide the types the Link-Field can have in the JSON-output for the Contenttype:

![image](https://user-images.githubusercontent.com/1944911/88846282-45890d80-d19a-11ea-8745-785faa80e171.jpeg)
(not all types selected here, but the list is visible under "validations")

### Actual result

The graphQL error above. 

### Environment

```  System:

    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 73.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.24.2 => 2.24.2
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-env-variables: ^2.0.0 => 2.0.0
    gatsby-image: ^2.4.9 => 2.4.13
    gatsby-plugin-graphql-codegen: ^2.7.1 => 2.7.1
    gatsby-plugin-manifest: ^2.4.14 => 2.4.18
    gatsby-plugin-offline: ^3.2.18 => 3.2.18
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.10
    gatsby-plugin-sass: ^2.3.12 => 2.3.12
    gatsby-plugin-sharp: ^2.6.21 => 2.6.22
    gatsby-source-contentful: ^2.3.33 => 2.3.33
    gatsby-source-filesystem: ^2.3.14 => 2.3.19
    gatsby-transformer-remark: ^2.8.25 => 2.8.25
    gatsby-transformer-sharp: ^2.5.7 => 2.5.11
  npmGlobalPackages:
    gatsby-cli: 2.12.60

```

**Comment by vladar** [comment]
Hi @oneextra !

Thanks for opening this. By default, Gatsby relies on actual data to produce GraphQL schema (type inference), so the behavior you describe is expected here. But Gatsby also exposes an API for [schema customization](https://www.gatsbyjs.org/docs/schema-customization/). If a plugin or site knows the schema upfront they can explicitly define GraphQL types in Gatsby using this API and thus stop relying on inference.

Ideally, this should be handled in Contentful plugin but you can also define types in your project. We have a tracking PR for the new major version of the Contentful plugin - #25249 (which may help here). But in the meantime, you can define the reference types yourself using schema customization.

This will look something like this:

```js
// gatsby-node.js
exports.createSchemaCustomization = ({ actions }) => {
  actions.createTypes(`
    union MyContentfulLinkType = ContentfulBlogPost | ContentfulHomePage | ContentfulProduct | ContentfulProductCategory | ContentfulProductsPage

    # Replace MyContentfulEntryType below with your actual type name having a `link` field
    type MyContentfulEntryType {
      link: MyContentfulLinkType
    }
  `)
}

```

I didn't test it, so please let me know if it doesn't work for you.

**Comment by oneextra** [comment]
Yes this is it @vladar - Thank you so much! It worked. 
(The only thing that needed to be changed in your code is to add "implements Node" in the type). 

I don't entirely understand why this happens this way - since contentful probably provides the schema in some way?

**Comment by oneextra** [comment]
Actually I gave it some more tests and there is another issue resulting out of this. 

For example I have a Type HeroSlide which has a Link reference to ContentfulProduct | ContentfulProductCategory | ContentfulLoginPage. 

The latter, the login page is not linked, but theoretically can be there. If I dont add the schema customization. I can only get product and product category. So I add it like so: 
```
union HeroSlideLink = ContentfulProduct | ContentfulProductCategory | ContentfulLoginPage
type ContentfulHeroSlide implements Node{
    link: HeroSlideLink
}
```
Result is that I can see the 3 types it in __graphiql and run queries on them.

However what happens now is that all data returned for the link field link is "null". That is really strange: 

This is my query:
```
allContentfulHeroSlide {
    nodes {
      link {
        ... on ContentfulProduct {
          contentful_id          
        }
        ... on ContentfulProductCategory {
          contentful_id
        }
          
    	}  
    }
  }
```

But WITH the customization in gatsby-node all I get is: 
```
"nodes": [
        {
          "link": null
        },
        {
          "link": null
        },
...
```

while the expected result is (which is what I get if I don't customise in gatsby-node
```
  "nodes": [
        {
          "link": {
            "contentful_id": "6beJ9R8VkwQQum5EoBpmiD"
          }
        },
        {
          "link": {
            "contentful_id": "lubwGKp0itZs6epbqYacr"
          }
        },
...
```


Any leads why this happens ?

**Comment by vladar** [comment]
@oneextra I forgot another part, you probably need to set it like this:

```graphql
type ContentfulHeroSlide implements Node {
    link: HeroSlideLink @link(from: "link___NODE")
}
```

See https://github.com/gatsbyjs/gatsby/issues/24290#issuecomment-632257170 for more context

**Comment by oneextra** [comment]
Yes this finally totally resolved my issue Thank you so much. 

I had to add the array, since for some types I had multiple references.

link: [HeroSlideLink] @link(from: "link___NODE")

Thanks a lot!

**Comment by tmatek** [comment]
This approach seems to fail for "JSON Object" Contentful types. We have an optional `image` field in Contentful, that is linked to Cloudinary and is of type "JSON Object". We have this customization:

```Javascript
// gatsby-node.js
exports.createSchemaCustomization = ({ actions }) => {
  actions.createTypes(`
    type CloudinaryImage implements Node {
      secure_url: String
      width: Int
      height: Int
    }

    type ContentfulImage implements Node {
      image: [CloudinaryImage] @link(from: "image___NODE")
    }
 `)
}
```

The data for the `image` field is still `null` though. Any way to make it work for JSON fields too?

**Comment by tmatek** [comment]
Update:

we've managed to partially solve this by "predicting" the typename of JSON fields ahead of time. In Contentful development environment we had some data for the `image` field, so we were able to get the typename generated by the Contentful plugin. We then used this typename to link it to the existing components, so that if in master Contentful environment the data is not there it still works ok.

```javascript
// gatsby-node.js
exports.createSchemaCustomization = ({ actions }) => {
  actions.createTypes(`
    # typename obtained from GraphQL playground
    type contentfulImageImageJsonNode implements Node {
      secure_url: String
      width: Int
      height: Int
    }

    type ContentfulImage implements Node {
      image: [contentfulImageImageJsonNode] @link(from: "image___NODE")
    }
 `)
}
```

This also works for rich text fields:

```graphql
type contentfulImageCaptionTextNode implements Node {
  childMarkdownRemark: MarkdownRemark
}
```

**Comment by EdPike365** [comment]
Since this is still open, here is a link to the version of this problem in gatsby-source-contentful v 4.6 ish. Hope this helps anyone coming along this problem in more recent times. https://edpike365.medium.com/gatsby-contentful-rich-text-migrate-to-gatsby-source-contentful-version-4-in-early-2021-321904587470
