### ISSUE TITLE
Static query not invalidating hash

### ISSUE THREAD

**Issue by herecydev** [gatsbyjs/gatsby#26135]
Looking at the guidance on caching (https://www.gatsbyjs.org/docs/caching/#static-files) I think the recent changes to static queries isn't correct with this. @sidharthachatterjee I don't know if this is something you can answer?

The guidance is:

> All files in static/ should be cached forever

However the .json files that are output to the `static/d` folder look like a hash of the query (schema?) and not of the query result. Images are requested like `/icons/icon-512x512.png?v=6097298229b47b2e2010b1492c6fee40`, where the v seems to be a hash of something that rotates when an image has changed.

Is this `?v=` supposed to be applied to the static/d/<hash>.json files as well?

## Steps to recreate

1. Create gatsby-starter-default
2. `gatsby build`
3. Observe `static/d/` folder
4. Change siteMetadata title, for example
5. `gatsby build`
6. Observe `static/d/` folder, it hasn't changed

**Comment by sidharthachatterjee** [comment]
Excellent issue @herecydev 

We were just discussing this internally last night and I was about to update the documentation and create an issue. You beat me to it, haha. I'll update the documentation. I think this needs a two part solution:

- Short term: We add `public/static/d` as an exception to the caching rules 
- Long-ish term: We switch the location for static queries into `public/page-data/static/d`

**Comment by herecydev** [comment]
> Short term: We add public/static/d as an exception to the caching rules

I think this needs to be broadcast well; I would expect a lot of people have that cache rule in place. It's the sort of thing you wouldn't bother checking periodically as well.

> Long-ish term: We switch the location for static queries into public/page-data/static/d

Seems sensible, and would "just work" for everyone who's setup blanket rules

**Comment by disintegrator** [comment]
Just got bitten by this :). We enabled a new locale in Contentful but since the static queries didn't change the resulting json files remained in the browser disk cache and were used instead of fetching updated ones. We're seeing a few issues and caching anomalies because of this such as menu items popping in and out.

**Comment by sidharthachatterjee** [comment]
We switch the location for static queries into public/page-data/sq/d

Fix published in `gatsby@2.24.33`

**Comment by ibraheemdev** [comment]
When did this. become an issue? Was it a result of a recent update? Because I had no issue with the static hashes until just recently

**Comment by herecydev** [comment]
@ibraheemdev 17 days ago, from this pull request: https://github.com/gatsbyjs/gatsby/pull/25723

**Comment by danielmgzzg** [comment]
Guys, I thank you so much for fixing this issue. I just wish we had found it earlier in the docs or something we have been clueless for months and tried all sort of things until we looked closely at the .json from the static queries and searched for this
