### ISSUE TITLE
"source and transform nodes" is Too Opaque

### ISSUE THREAD

**Issue by machineghost** [gatsbyjs/gatsby#26149]
## Description

I'm hung on the "source and transform nodes" step, and from the numerous related threads it seems this is a fairly common occurrence in Gatsby ... which is why this bug is _not_ yet another "please help me fix variant #972B of this bug" ;)

Instead, this bug is a plea to make it so users *don't need help*.  Surely it's possible to somehow surface greater information about this step, so that users can solve their own problems?

### Steps to reproduce

See the numerous previous issues about "source and transform nodes"

### Expected result

If a particular piece of _any_ program breaks frequently, I ... well first, look, I don't expect programs (especially OSS ones) to work perfectly!  Stuff happens.

All I'm asking is that when you see a part of your app breaking in different (and often inconsistent ways), that part of the app needs to give more info than just "source and transform nodes".  Having however many different issue threads out there (several with many different sub-issues/solutions) as the only documentation is not an optimal solution.

### Actual result

All anyone ever sees is "source and transform nodes" ... forever.

### Environment

Irrelevant, because again it just doesn't feel sustainable to have to waste maintainer time debugging my personal variation of this issue.

**Comment by machineghost** [comment]
Just as a simple example, in the process of trying to debug my own issue I added this console.log line to `utils/api-runner-node`:

    const pluginName = plugin.name === `default-site-plugin` ? `gatsby-node.js` : plugin.name;
    console.log('pluginName', pluginName)
    return new Promise(resolve => {

Now obviously if this was a PR I'd submit something like:

    (if env.VERBOSE) console.log('pluginName', pluginName)

but the point is that this doesn't have to be anything crazy: simply having a debug/verbose flag so that you can see what plugin is the last to run before the program freezes can be very helpful.

**Comment by machineghost** [comment]
P.S. I was able to trace the issue to this line (logs added before it run, logs added after don't):

    const graphqlSchema = await createPostGraphileSchema(pool, schemas, {

I'll have to debug further to see why PostGraphile is having difficulty, but again, I don't blame Gatsby for any of this!  An app this complex is going to have issues like this, and in this case it was a completely different library (PostGraphile) hanging which "made Gatsby look bad"!

All I'm asking for in this ticket is just a way for Gatsby users (eg. a `--debug` or `--verbose` flag) to see **_why_** Gatsby is hanging.

**Comment by KyleAMathews** [comment]
A really simple way we could help here is to log after 30 seconds (and incrementing every 30 seconds after that) source plugins which haven't finished yet.

**Comment by machineghost** [comment]
Sounds great to me.  If you want to point me towards where/how you'd want that done I'd be happy to submit a PR, but this may well be the sort of thing it takes longer to explain than to just do :)

**Comment by KyleAMathews** [comment]
Heh — if you want to play with this, we call APIs in this file & create for each plugin invocation a record — https://github.com/gatsbyjs/gatsby/blob/e001e1177f9a0e3c4fb4141e747ecd026a371e1c/packages/gatsby/src/utils/api-runner-node.js#L368

You could use a `setInterval` to check how old different instances are every few seconds & then log out any longer-running instances. You could start with simple `console.log` but for the final version, we use redux under the hood to store data so you'd want to pass to that updates for when an API call has been going for longer (and remove it when the API call does finish).

I think this would be super helpful for debugging stalled plugins!

**Comment by machineghost** [comment]
Quick question: before I start working on someone else's repo I always like to see a green test build, but I ran into some issues running `npm test` on a clean checkout (with `npm i` run of course).

First, it seemed like I needed to run `npm run format` to trigger prettier before I could run tests.  Compared to most repos I've worked on, that felt backwards: tests don't normally care about formatting.  Orgs often do, but if they do, they normally check in formatted code: they don't check in bad code, and make everyone else format it on their machines.  So me having to format the checked-out code just to run tests made me feel like I was doing something wrong.

Second, even once I formatted the code, I couldn't run tests until I installed a bunch of packages:

+    "@reach/router": "^1.3.4",
+    "babel-preset-gatsby-package": "^0.5.2",
+    "gatsby-cli": "^2.12.68",
+    "gatsby-core-utils": "^1.3.14",
+    "gatsby-legacy-polyfills": "0.0.2",
+    "graphql": "^15.3.0",
+    "graphql-compose": "^7.18.1",
+    "mitt": "^2.1.0",
+    "react": "^16.13.1",
+    "react-error-overlay": "^6.0.7",
+    "redux": "^4.0.5",
+    "shallow-compare": "^1.2.2",
+    "xhr-mock": "^2.5.1"

... but even after installing all that I still had 76 failures, because of dependencies like `redux-thunk`.

This is baffling to me: none of those were listed in `package.json` (as either a dependency or devDependency), but I can see the use of Redux in the code itself, so it clearly *does* depend on Redux (and all those other libraries).  Does Gatsby have some sort of secret `package.json` with it's real dependencies or something? 

BTW I did read https://www.gatsbyjs.org/contributing/code-contributions/, but it didn't mention any of this.

**Comment by KyleAMathews** [comment]
Did you see these instructions? You need to use `yarn` as we use yarn workspaces so dependencies won't be installed otherwise https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/#fork-clone-and-branch-the-repository

**Comment by machineghost** [comment]
Ah.  I don't think I want to switch package managers just to work on this, but hopefully it will be easy to implement without my PR.

**Comment by KyleAMathews** [comment]
It's a very temporary switch :-) you could even I think run `npx yarn` to avoid installing it.

**Comment by machineghost** [comment]
It's just a fun thing: I don't contribute to OSS because I'm being paid, I do it because it's fun.

Helping out a great OSS library like Gatsby? Definitely fun.  Having to learn a whole other build system, which I have no desire to ever use outside of Gatsby? Not fun.

**Comment by machineghost** [comment]
P.S. Just wanted to mention that I found my own personal cause of the hanging behavior (an out-dated `pg` dependency in the relevant plug-in).  But being able to know which plug-in was responsible would have saved me from some painful `node_modules` debugging, so I still think this ticket could have value to others if there's a reasonable chance of any plug-in doing the same thing in the future.
