### ISSUE TITLE
Improve SSR-API onRenderBody example.

### ISSUE THREAD

**Issue by freethebit** [gatsbyjs/gatsby#26144]
## Summary

Where: https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody

What: Improve the example for `onRenderBody` or add another example, simple, that is not tied to a plugin.

### Suggestion

```
// Object of props
const HtmlAttributes = {
  "data-whatever": "content"
}

// Magic
exports.onRenderBody = (
  { setHtmlAttributes }
) => {
   setHtmlAttributes(HtmlAttributes)
}

// Output
<html data-whatever="content">
```
In my opinion looks much easier to understand the description:

> Takes an object of props which will spread into the `<html>` component.

### Motivation

It may help anyone starting with this API.

The process on how to contribute to Gatsbyjs docs is too complicated.

**Comment by asaki444** [comment]
Is anyone taking this? I'll take it!

**Comment by Mvrs** [comment]
is this still open?

**Comment by thehanimo** [comment]
@Mvrs I've made a pull request (#26362)... a review on it is pending.
