### ISSUE TITLE
 How not to use SSR

### ISSUE THREAD

**Issue by AboyL** [gatsbyjs/gatsby#26157]
I don’t want to use SSR when executing build. Is there a solution?

**Comment by sidharthachatterjee** [comment]
@AboyL We don't support this _not_ running SSR for builds at the moment (and are unlikely to do so). Any reason _why_ you wouldn't want to run SSR?

You can use client side only pages to achieve this but seems like an antipattern.

**Comment by AboyL** [comment]
> @AboyL We don't support this _not_ running SSR for builds at the moment (and are unlikely to do so). Any reason _why_ you wouldn't want to run SSR?
> 
> You can use client side only pages to achieve this but seems like an antipattern.

Thank you very much,I want to do this because my website has some problems, I suspect it is caused by SSR, so I want to temporarily close it, thank you very much for your answer
