### ISSUE TITLE
Subdirectory pages are not loading css (icons and loose some css)

### ISSUE THREAD

**Issue by Berchant** [gatsbyjs/gatsby#26158]
## Description

In the index page everything is working perfectly and other pages but when i created a folder and add more pages in the folder when going in to those pages some css and js are lost and all the icons when i refresh some css are back but not the icons 

### Expected result
not loosing the css and js functionalities and to work as they work on other pages that aren't in a different folder
What should happen?

### Environment

Gatsby V2
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-plugin-firebase: ^0.2.0-beta.4 => 0.2.0-beta.4
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9
    gatsby-plugin-modal-routing: ^1.1.0 => 1.1.0
    gatsby-plugin-offline: ^3.2.7 => 3.2.7
    gatsby-plugin-postcss: ^2.3.3 => 2.3.3
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9
    gatsby-plugin-styled-components: ^3.3.3 => 3.3.3
    gatsby-source-apiserver: ^2.0.0 => 2.0.0
    gatsby-source-filesystem: ^2.3.12 => 2.3.12
    gatsby-transformer-remark: ^2.8.17 => 2.8.17
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3
  npmGlobalPackages:
    gatsby-cli: 2.12.58

**Comment by sidharthachatterjee** [comment]
This shouldn't occur. Do you have a minimal reproduction?

**Comment by Berchant** [comment]
> Do you have a minimal reproduction?

no unfortunately i do not it a work for a company project can not share the project

**Comment by freiksenet** [comment]
Hi! 

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. 

Thanks!
