### ISSUE TITLE
gatsby-source-contentful static files are not output with an md5 hash so cannot be cached long term

### ISSUE THREAD

**Issue by taskbox-joe** [gatsbyjs/gatsby#26153]
## Description

All other content that is output to public/static uses an md5 hash of the content in some way so that the content can be cached long term but some of the static files output by gatsby-source-contentful do not. This was causing some of our built files to not be visible after an update because for all the content in public/static we were using an immutable cache header. I'm not certain that all files within public/static should use some kind of file hash to ensure that if the content changes the file name also changes but all other content appears to follow some rule along these lines. Also not certain that it is gatsby-source-contentful that is the problem but it is only page data related to contentful sourced data.

### Steps to reproduce

`npm run build` and check output

### Expected result

That all files output to public/static will use some kind of hash so that if their content changes so does the filename

### Actual result

there is content output to public/static/d/<filename>.json where filename is just a 10 digit id and if a change is made in contentful that results in a change to the content of these files, the name of the file remains the same and breaks the caching I have in place.

(Have a workaround in place for files in public/static/d for now that just applies a max-age=0 rule for these files for the time being)

### Environment

As well as the below this is also run on windows and a CI server on circle ci and all have the same thing

  System:
    OS: Linux 4.14 Amazon Linux AMI 2018.03
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.21.0/bin/npm
  Languages:
    Python: 3.6.11 - /usr/bin/python
  npmPackages:
    gatsby: ^2.24.14 => 2.24.14
    gatsby-image: ^2.4.14 => 2.4.14
    gatsby-link: ^2.2.20 => 2.4.13
    gatsby-plugin-catch-links: ^2.1.13 => 2.3.11
    gatsby-plugin-google-analytics: ^2.1.21 => 2.3.13
    gatsby-plugin-react-helmet: ^3.1.11 => 3.3.10
    gatsby-plugin-sass: ^2.1.18 => 2.3.12
    gatsby-plugin-sharp: ^2.6.23 => 2.6.23
    gatsby-plugin-sitemap: ^2.2.17 => 2.4.11
    gatsby-remark-images: ^3.3.22 => 3.3.22
    gatsby-remark-images-contentful: ^2.3.12 => 2.3.12
    gatsby-source-contentful: ^2.3.33 => 2.3.33
    gatsby-source-filesystem: ^2.3.23 => 2.3.23
    gatsby-transformer-remark: ^2.8.27 => 2.8.27
    gatsby-transformer-sharp: ^2.2.21 => 2.5.11

**Comment by sidharthachatterjee** [comment]
This is a known issue at the moment and is being tracked in https://github.com/gatsbyjs/gatsby/issues/26135

The immediate recommendation is to add `public/static/d` as an exclusion to your caching rules.

**Comment by sidharthachatterjee** [comment]
A fix for this was just published in Gatsby 2.24.33
