### ISSUE TITLE
Add UI to the site itself that highlights the existence of Admin

### ISSUE THREAD

**Issue by mxstbr** [gatsbyjs/gatsby#26168]
Maybe something similar to the WordPress top bar or some kind of floating action button or something that reminds people that Admin exists and makes it only be a click away!

Needs to be configurable (through gatsby-config.js and thus Admin in the UI :wink:) so people can turn it off!

**Comment by sampittko** [comment]
@mxstbr Can I take this issue?

**Comment by sampittko** [comment]
I am a member of Gatsby Admin Early Access group so it would be a pleasure for me to help

**Comment by mxstbr** [comment]
@sampittko I really appreciate the offer! This requires significant design exploration and user testing before we can really tackle it, which we don't currently have, so this is likely not the right moment to jump in just yet :blush:

**Comment by sampittko** [comment]
> @sampittko I really appreciate the offer! This requires significant design exploration and user testing before we can really tackle it, which we don't currently have, so this is likely not the right moment to jump in just yet 😊

Thanks for your response. Is there anything I can do in order to help with the Admin UI?

**Comment by mxstbr** [comment]
I unfortunately don't think so at the moment! I'll definitely ping you once there's some clearly scoped tasks though 👍
