### ISSUE TITLE
GraphQL Pagination

### ISSUE THREAD

**Issue by Unforgiven-wanda** [gatsbyjs/gatsby#2616]
Hello,
I'm trying to create a simple archives page that lists all my posts (instead of having it clutter the front page) However I am having trouble creating a pagination with a GraphQL for a number of reasons:

1. The GraphQL query in my component/page cannot receive js data (I cannot declare a `var page=2` and pass it to the query) and thus I can't get the appropriate data when needed

2. The GraphQL query receives its data from the `context` object in the `createPage` part of `gatsby-node`, however, since this is done at page generation, I couldn't get the number of the page in this manner:

```javascript
context: {
                id: edge.node.id,
                url: window.location.href
              },
```
And so I'm completely stumped as to how I can create a pagination in Gatsby. Is there some method I am not aware of? If so, please inform me.

Thank you, and good day.

**Comment by tinrab** [comment]
You can use context values as GraphQL query arguments.

I've done it like this. The context, for `createPage`, contains:

```
context: {
  skip: i,
  limit: articlesPerPage,
  total: total
}
```

And the GraphQL query inside the template:

```
query Query($skip: Int!, $limit: Int!) {
  allMarkdownRemark(skip: $skip, limit: $limit, ...) {
    ...
```

**Comment by KyleAMathews** [comment]
@pixelstew is working on a Gatsby pagination library. I'm sure he'd love feedback on you using it!

https://www.npmjs.com/package/gatsby-paginate
