### ISSUE TITLE
High risk vulnerability for Gatsby and Gatsby-cli

### ISSUE THREAD

**Issue by w3bdesign** [gatsbyjs/gatsby#26177]
Talked to Kyle Matthews about this and he told me to file an issue.

## Description

I am seeing this in my console:

```
 
  High            Prototype Pollution                                           
                                                                                
  Package         dot-prop                                                      
                                                                                
  Patched in      >=5.1.1                                                       
                                                                                
  Dependency of   gatsby                                                        
                                                                                
  Path            gatsby > devcert > configstore > dot-prop                     
                                                                                
  More info       https://npmjs.com/advisories/1213                             
                                                                                
                                                                                
  High            Prototype Pollution                                           
                                                                                
  Package         dot-prop                                                      
                                                                                
  Patched in      >=5.1.1                                                       
                                                                                
  Dependency of   gatsby                                                        
                                                                                
  Path            gatsby > gatsby-cli > update-notifier > configstore >         
                     dot-prop                                                      
                                                                                
  More info       https://npmjs.com/advisories/1213
```     

### Steps to reproduce

Upgrade all npm packages and do a npm install

### Expected result

I expect no vulnerabilities

### Environment

  System:
    OS: Windows 7 6.1.7601
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn x\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.4
  Browsers:
    Chrome: 84.0.4147.105
  npmPackages:
    gatsby: ^2.24.23 => 2.24.23 
    gatsby-cypress: ^0.4.10 => 0.4.10 
    gatsby-plugin-fontawesome-css: ^1.0.0 => 1.0.0 
    gatsby-plugin-manifest: ^2.4.21 => 2.4.21 
    gatsby-plugin-netlify: ^2.3.11 => 2.3.11 
    gatsby-plugin-percy: ^0.1.4 => 0.1.4 
    gatsby-plugin-postcss: ^2.3.11 => 2.3.11 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1 
    gatsby-plugin-sitemap: ^2.4.11 => 2.4.11 
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10 
    gatsby-source-graphql: ^2.6.2 => 2.6.2 
  npmGlobalPackages:
    gatsby-cli: 2.12.68

**Comment by herecydev** [comment]
This is a duplicate of #26128
