### ISSUE TITLE
Forking a theme, Error 85901 (Duplicate definitions)

### ISSUE THREAD

**Issue by thedatabusdotio** [gatsbyjs/gatsby#26188]
## Description

I'm using the theme [gatsby-theme-nehalem](https://github.com/nehalist/gatsby-theme-nehalem) to build [my site](https://thedatabus.io). Since I needed to make a lot of changes to the original theme I decided to fork it instead and make changes to the theme itself. Here is what I did:

1. Forked the theme
2. Made some changes (only one change, I added the `gatsby-remark-katex` plugin to the blog post template, added it the list of dependencies in `package.json`, made relevant namespacing changes (changed '@nehalist' to '@blacksparrow' etc)).
3. published the theme under a different name [@blacksparrow/gatsby-theme-blacksparrow](https://www.npmjs.com/package/@blacksparrow/gatsby-theme-blacksparrow) to npm. 
4. Made changes in my starter (/demo) folders to use @blacksparrow/gatsby-theme-blacksparrow instead of @nehalist/gatsby-theme-nehalem (basically just modified the `gatsby-config.js` and the component shadowing path)
5. did `npm install @blacksparrow/gatsby-theme-blacksparrow`
6. ran `gatsby develop`

You can look at [this diff](https://github.com/nehalist/gatsby-theme-nehalem/compare/master...thedatabusdotio:master) between the original theme repo and my fork for a list of all the changes I made.

### Steps to reproduce
1. Clone [this repo](https://github.com/thedatabusdotio/gatsby-theme-nehalem) to your system
2. `cd` into `demo/`
3. run `gatsby develop`

### Expected result

The site should be live with added katex support at localhost:8000

### Actual result
The build goes through but I get the following error: 

```
 ERROR #85901  GRAPHQL
There was an error in your GraphQL query:
Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
- MetadataQuery
- Tags                                                                                                                  
- PrimaryTag
```
### Environment
```
System:
  OS: Windows 10 10.0.18362
  CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
Binaries:
   Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
   npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
Languages:
   Python: 3.8.3
Browsers:
   Edge: 44.18362.449.0
npmPackages:
   gatsby: ^2.13.1 => 2.13.1
npmGlobalPackages: 
  gatsby-cli: 2.12.51
```

**Comment by LekoArts** [comment]
When forking the theme you'll need to remove the old theme from the package.json:
https://github.com/thedatabusdotio/gatsby-theme-nehalem/blob/master/demo/package.json#L16
