### ISSUE TITLE
Creating Components from MDX/JSON/Data

### ISSUE THREAD

**Issue by JoshWilkins2013** [gatsbyjs/gatsby#26185]
## File Structure 

The file structure I have looks something like this

data
-UserN
-- BlockN
--- SubBlockN
---- ImageN

With N representing any number of users, blocks, subblocks, and images.
Every user folder, block folder, and subblock folder has a json file with some relavant info.

## Thoughts / Questions

What I've been thinking is creating components from the json files so I can reuse them across the site.
For example, I just want to query once for all the images in each SubBlock and represent them the same way as a component.

The CreatePages function in gatsby-node.js basically does this but its used for creating pages.
I don't need a page for every SubBlock. Is there something similar that I can use for creating components?

Maybe I just create a component and pass in the id of the SubBlock I want?
But wouldn't this query for the images every time?

Maybe its easier to create my own graphql schema for this?

I guess I'm really just looking for how others would you go about handling this?

## Comments

This is not a question about how to use gatsby-transformer-json or how to query for data.
More of a question about how to structure my code.
Any help would be greatly appreciated.

**Comment by freiksenet** [comment]
At this moment doing this is pretty tricky unfortunately. There is no way to control what code you'd need in a particular page without importing it. We are working on a feature that will make this much easier - it will allow creating components in resolvers that will then get loaded on the page and returned from GraphQL. At this stage you could take a look how MDXRenderer does this, but it would be pretty complicated. 

We expect components from graphql to ship within next 1-2 months.

**Comment by JoshWilkins2013** [comment]
Thanks @freiksenet, that sounds like what I'm looking for. I'm surprised I haven't come across anyone else looking to do something similar. 

Any way to track the progress of this feature?

**Comment by ascorbic** [comment]
Hi. I'm going to close this for now. Components from GraphQL is a feature planned for the future, but we don't have a specific date for it.
