### ISSUE TITLE
Viewing starter on Safari page has horizontal overflow

### ISSUE THREAD

**Issue by zburk** [gatsbyjs/gatsby#26184]
## Description

Horizontal overflow when screen width < 750px only viewable when selecting a starter from Starter Library

Being caused by
```
<Copy
    fileName="Install command"
    content={content}
    sx={{ borderRadius: 1 }}
/>
```

### Steps to reproduce

View https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-blog/ on Safari with a screen width < 750px

### Expected result

There should be no horizontal overflow since it's just empty space

### Actual result

<img width="565" alt="Screen Shot 2020-08-01 at 1 22 54 PM" src="https://user-images.githubusercontent.com/5782327/89106710-212b6c00-d3fa-11ea-885a-5cf5f0c707bd.png">

### Environment

```
  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.21.0 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.7.0/bin/npm
  Languages:
    Python: 3.7.8 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Safari: 13.1.1
```

**Comment by LekoArts** [comment]
Thanks for the issue! This was fixed on the current site with the .org and .com merge. Thanks for creating this issue and sending in the PR though!
