### ISSUE TITLE
Gatsby-plugin-sitemap generates NaN-NaN-NaN on <lastmod>

### ISSUE THREAD

**Issue by flikteoh** [gatsbyjs/gatsby#26194]
## Description

When using `gatsby-plugin-sitemap` to generate sitemap.xml, `<lastmod>` was not available by default.

Manually adding this would output `<lastmod>` tags in the final sitemap.xml, but the date were written as `NaN-NaN-NaN`

**Note:** Even if we manually uses `lastmod: '2020-08-03T01:54:49.000Z'` during the serialize below still outputs as NaN

### Steps to reproduce
```
{
      resolve: `gatsby-plugin-sitemap`,
      options: {
        createLinkInHead: true,
        query: `{
          site {
            siteMetadata {
              siteUrl
            }
          }

          allSitePage {
            nodes {
              path
              context {
                updated
              }
            }
          }
        }`,
        resolveSiteUrl: ({ site }) => {
          return site.siteMetadata.siteUrl;
        },
        serialize: ({ site, allSitePage }) =>
          allSitePage.nodes.map((node) => {
            return {
              url: `${site.siteMetadata.siteUrl}${node.path}`,
              changefreq: `daily`,
              priority: 0.7,
              lastmod: `${node.context.updated}`,
            };
          }),
      },
    },
```
### Expected result

Expecting the sitemap to output entries with correct last-modified tags, ie:`<lastmod>2020-08-03T01:54:49.000Z</lastmod>`

### Actual result

`<lastmod>NaN-NaN-NaN</lastmod>`

### Environment

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    npm: 6.14.7 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.4 => 2.24.4 
    gatsby-image: ^2.4.13 => 2.4.13 
    gatsby-plugin-catch-links: ^2.3.11 => 2.3.11 
    gatsby-plugin-feed-mdx: ^1.0.1 => 1.0.1 
    gatsby-plugin-google-analytics: ^2.3.11 => 2.3.11 
    gatsby-plugin-manifest: ^2.4.18 => 2.4.21 
    gatsby-plugin-mdx: ^1.2.27 => 1.2.27 
    gatsby-plugin-offline: ^3.2.18 => 3.2.18 
    gatsby-plugin-preact: ^4.0.9 => 4.0.9 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1 
    gatsby-plugin-s3: ^0.3.3 => 0.3.4 
    gatsby-plugin-sharp: ^2.6.19 => 2.6.22 
    gatsby-plugin-sitemap: ^2.4.11 => 2.4.11 
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10 
    gatsby-remark-attr: ^0.1.0 => 0.1.0 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-images: ^3.3.19 => 3.3.19 
    gatsby-remark-unwrap-images: ^1.0.2 => 1.0.2 
    gatsby-source-filesystem: ^2.3.20 => 2.3.23 
    gatsby-transformer-sharp: ^2.5.11 => 2.5.11 
  npmGlobalPackages:
    gatsby-cli: 2.12.66

**Comment by fgambarino** [comment]
Hi @flikteoh,
since the format of the date you are using is ISO one, could you try to use - instead of lastmod - the lastmodISO property?

**Comment by vladar** [comment]
Hi @flikteoh 

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by vladar** [comment]
CC @moonmeister

**Comment by Joe-Edwards** [comment]
I just ran into this as well - the fix appears to be using `lastmodISO` as suggested above.

It's a little tricky to debug as the plugin is using an old version of the sitemap package, and more recent versions of the package don't have this distinction (see https://github.com/ekalinin/sitemap.js/blob/master/CHANGELOG.md#breaking-changes).

**Comment by moonmeister** [comment]
Sounds like https://github.com/gatsbyjs/gatsby/pull/25670 will take care of this since it updates to the latest version.

**Comment by flikteoh** [comment]
@fgambarino Thank you so much. That fixes my problem.

Was wondering why isn't there any documentation regarding to this on the plugin page itself.
Whether is it `lastmod` or `lastmodISO`, I felt that it's somewhat important for users.

Also, 
> https://support.google.com/webmasters/answer/183668?hl=en
> Google ignores <priority> and <changefreq> values, so don't bother adding them.
> Google reads the <lastmod> value, but if you misrepresent this value, we will stop reading it.

and sorry @vladar I'm unable to create a minimal reproduction for this issue.

In case anyone that came across similar problem, this solved my problem:

**via the lastmodISO**

```
    {
      resolve: `gatsby-plugin-sitemap`,
      options: {
        query: `{
          site {
            siteMetadata {
              siteUrl
            }
          }

          allSitePage {
            nodes {
              path
              context {
                updated
              }
            }
          }
        }`,
        resolveSiteUrl: ({ site }) => site.siteMetadata.siteUrl,
        serialize: ({ site, allSitePage }) =>
          allSitePage.nodes.map((node) => {
            const { siteUrl } = site.siteMetadata;
            return {
              url: `${siteUrl}${node.path}`,
              lastmodISO: node.context.updated,
            };
          }),
        createLinkInHead: true,
      },
    },
```
