### ISSUE TITLE
How to handle an external service GraphQL dependency network failure?

### ISSUE THREAD

**Issue by tshelburne** [gatsbyjs/gatsby#26212]
##  Summary

When a service has an issue and returns 503s (currently Workable), is there a good way to handle that failure so that builds can continue? I understand the data won't be available, but it would be good to be able to create fallbacks in situations where the missing data is acceptable.

## Relevant information

Workable is currently having sporadic degraded service where 503s are being returned, and our website build is failing as a result. I would like to be able to at least handle PR review of work done by creating an acceptable fallback.

### Environment (if relevant)

```
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.14.0 - ~/.nvm/versions/node/v13.14.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v13.14.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9
    gatsby-plugin-netlify-cms: ^4.3.9 => 4.3.9
    gatsby-plugin-offline: ^3.2.7 => 3.2.7
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2
    gatsby-plugin-sass: ^2.3.4 => 2.3.4
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9
    gatsby-source-filesystem: ^2.3.8 => 2.3.8
    gatsby-source-workable: ^1.1.1 => 1.1.1
    gatsby-transformer-remark: ^2.8.23 => 2.8.23
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

Your description is a bit vague:

> and our website build is failing as a result.

Where does it fail, with what error? What is your expected outcome?

**Comment by tshelburne** [comment]
Fair - my bad, kid woke up and couldn't focus. Error from Netlify logs below:

```
9:05:45 PM: error "gatsby-source-workable" threw an error while running the sourceNodes lifecycle:
9:05:45 PM: Request failed with status code 503
9:05:45 PM: 
9:05:45 PM: 
9:05:45 PM:   Error: Request failed with status code 503
9:05:45 PM:   
9:05:45 PM:   - createError.js:16 createError
9:05:45 PM:     [repo]/[axios]/lib/core/createError.js:16:15
9:05:45 PM:   
9:05:45 PM:   - settle.js:18 settle
9:05:45 PM:     [repo]/[axios]/lib/core/settle.js:18:12
9:05:45 PM:   
9:05:45 PM:   - http.js:191 IncomingMessage.handleStreamEnd
9:05:45 PM:     [repo]/[axios]/lib/adapters/http.js:191:11
9:05:45 PM:   
9:05:45 PM:   - task_queues.js:84 processTicksAndRejections
9:05:45 PM:     internal/process/task_queues.js:84:21
9:05:45 PM:   
9:05:45 PM: 
9:05:45 PM: not finished source and transform nodes - 0.782s
9:05:45 PM: ​
9:05:45 PM: ┌─────────────────────────────┐
9:05:45 PM: │   "build.command" failed    │
9:05:45 PM: └─────────────────────────────┘
9:05:45 PM: ​
9:05:45 PM:   Error message
9:05:45 PM:   Command failed with exit code 1: gatsby build
9:05:45 PM: ​
9:05:45 PM:   Error location
9:05:45 PM:   In Build command from Netlify app:
9:05:45 PM:   gatsby build
9:05:45 PM: ​
9:05:45 PM:   Resolved config
9:05:45 PM:   build:
9:05:45 PM:     command: gatsby build
9:05:45 PM:     commandOrigin: ui
9:05:45 PM:     environment:
9:05:45 PM:       - HUBSPOT_API_KEY
9:05:45 PM:       - HUBSPOT_TRACKING_CODE
9:05:45 PM:       - REVIEW_ID
9:05:45 PM:       - WORKABLE_API_KEY
9:05:45 PM:     publish: /opt/build/repo/public
```

**Comment by LekoArts** [comment]
Ok, thanks for that.
It's something that needs to be fixed inside `gatsby-source-workable`. This is the source plugin itself: https://github.com/tumblbug/gatsby-source-workable/blob/master/src/gatsby-node.js

It doesn't have proper error handling and it also doesn't add custom types via Gatsby's schema customization API. Though, when it was created the latter didn't exist yet.

You could send in a PR to the plugin to handle those errors or copy it to a local plugin: https://www.gatsbyjs.org/docs/creating-a-local-plugin/

The tutorial here explains what you need to know to update the code to current APIs: https://www.gatsbyjs.org/docs/creating-a-source-plugin/

When you additionally also create types (via https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions) the types from the source plugin will always be defined even when no data comes back so that your builds don't break on missing data.

**Comment by tshelburne** [comment]
Excellent - thanks so much for the detailed response. The missing data has been *so frustrating* in the Contentful plugin, really cool to see that this can be handled.
