### ISSUE TITLE
Improve SSR-API onRenderBody example about keys

### ISSUE THREAD

**Issue by freethebit** [gatsbyjs/gatsby#26211]
### Summary

**Where**: https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody for:

- `setPreBodyComponents`
- `setPostBodyComponents`

**What**: The example does not make clear thar it need a 'key' for the array element and a warning is raised:

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
```

The docs says:

> Takes an array of components as its first argument which are added to the `preBodyComponents` array which is passed to the `html.js` component.

### Suggestion

Improve the warning msg. The warning will mention `MyComponent` and not the function that is mess up `setPreBodyComponents`.

Make clear in the API about the need to use key:

:+1: :+1: :+1: 
```
setPreBodyComponents(<MyComponent key={0}/>, <MyComponent key={1}/>)
```
:-1: :-1: :-1: 
```
setPreBodyComponents(<MyComponent />, <MyComponent />)
```

https://stackoverflow.com/questions/28329382/understanding-unique-keys-for-array-children-in-react-js
https://reactjs.org/docs/reconciliation.html#keys

### Motivation

Well, no body likes to debug by generic warning messages.

**Comment by meganesu** [comment]
Hi there @freethebit! Totally understand that it's confusing to get generic warning messages.

> Warning: Each child in a list should have a unique "key" prop.
>
> Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.

The above warning message comes from React, not Gatsby. If there are particular examples in the docs that show incorrect usage (like missing the key attribute), then we'd be open to changes to correct those mistakes. But at this time, we are not planning to add a reminder to use a key for each method that takes an array of components.

Were there any particular examples in the docs with incorrect usage?

Thanks for your contribution! 💜

**Comment by meganesu** [comment]
I'm going to close this issue for now. Feel free to reopen it if you find any examples in the docs that are incorrectly using the key attribute.

Thanks again for your contribution! 💜
