### ISSUE TITLE
404 page appears when using createRedirect too

### ISSUE THREAD

**Issue by pacocom** [gatsbyjs/gatsby#26218]
## Description

If I use **404 page** and **createRedirect** in gatsby-node.js (createPages) so first appears 404 page and little time later redirect to the redirect page.
![image](https://user-images.githubusercontent.com/7735329/89287720-c17ccd00-d654-11ea-9f72-5536f605ad84.png)
![image](https://user-images.githubusercontent.com/7735329/89287740-c93c7180-d654-11ea-82bc-3888f36fff96.png)

### Steps to reproduce
Goto: https://h9xml.sse.codesandbox.io/latest/. As you will see first appears 404 page and little time later appears the redirect page.

**(Code in https://codesandbox.io/s/quizzical-framework-h9xml)**

### Expected result
Redirect or navigate to redirect page without appears 404 page.

### Actual result
If I use **404 page** and **createRedirect** in gatsby-node.js (createPages) so first appears 404 page and little time later redirect to the redirect page.

### Environment
Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: 2.23.3 => 2.23.3 
    gatsby-image: 2.4.7 => 2.4.7 
    gatsby-plugin-catch-links: 2.3.5 => 2.3.5 
    gatsby-plugin-manifest: 2.4.11 => 2.4.11 
    gatsby-plugin-meta-redirect: 1.1.1 => 1.1.1 
    gatsby-plugin-react-helmet: 3.3.4 => 3.3.4 
    gatsby-plugin-remove-serviceworker: 1.0.0 => 1.0.0 
    gatsby-plugin-sass: 2.3.4 => 2.3.4 
    gatsby-plugin-sharp: 2.6.11 => 2.6.11 
    gatsby-plugin-typescript: 2.4.6 => 2.4.6 
    gatsby-remark-autolink-headers: 2.3.5 => 2.3.5 
    gatsby-remark-copy-linked-files: 2.3.5 => 2.3.5 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-images: 3.3.10 => 3.3.10 
    gatsby-remark-link-rewrite: 0.2.1 => 0.2.1 
    gatsby-remark-prismjs: 3.5.4 => 3.5.4 
    gatsby-remark-relative-images: 0.3.0 => 0.3.0 
    gatsby-remark-responsive-iframe: 2.4.5 => 2.4.5 
    gatsby-remark-smartypants: 2.3.4 => 2.3.4 
    gatsby-source-filesystem: 2.3.11 => 2.3.11 
    gatsby-transformer-json: 2.4.5 => 2.4.5 
    gatsby-transformer-remark: 2.8.15 => 2.8.15 
    gatsby-transformer-sharp: 2.5.5 => 2.5.5

**Comment by freiksenet** [comment]
Hi!

In Gatsby Develop this is an expected behavior, because redirects happen on client-side. When deploying a built app, your corresponding CDN will handle redirects properly (eg on netlify when using gatsby-plugin-netlify).

**Comment by pacocom** [comment]
Ok, thanks.

**Comment by kristfal** [comment]
@freiksenet just a heads up, this should be much clearer stated in the documentation at 

[https://www.gatsbyjs.com/docs/how-to/cloud/working-with-redirects-and-rewrites/](https://www.gatsbyjs.com/docs/how-to/cloud/working-with-redirects-and-rewrites/
)

Googling Gatsby Redirect leads to that page, and there is no info about redirects not working in dev mode.
