### ISSUE TITLE
gatsby-source-mysql plugin doesn't return all records from database

### ISSUE THREAD

**Issue by shubhambhatta** [gatsbyjs/gatsby#26226]
##  Description
gatsby built plugin gatsby-source-mysql doesn't behave as it is supposed to. when sourcing from mysql database and upon querying it from graphql in gatsby only the data of last column is shown.

### Steps to reproduce

1. install gatsby-source-mysql
2. configure gatsby-config.js as described in gatsby docs  
```
{
      resolve: `gatsby-source-mysql`,
      options: {
        connectionDetails: {
          host: 'localhost',
          user: 'root',
          password: '',
          database: 'mysql'
        },
        queries: [
          {
            statement: 'SELECT * FROM job_posts',
            idFieldName: 'jobs',
            name: 'posts'
          },
        ]
      }
    }
```
3. query from graphql in localhost:8000/___graphql  
```
query MyQuery {
  allMysqlPosts {
    edges {
      node {
        slug
      }
    }
  }
}
```

### Expected result

All the list of results which are saved in job_posts table is expected.

### Actual result  
```
{
  "data": {
    "allMysqlPosts": {
      "edges": [
        {
          "node": {
            "slug": "vacancy-javaScript-developer"
          }
        }
      ]
    }
  }
}
```
Only last item from job_post table is returned. There are multiple records saved in database but we get only last one. It happens even if we apply filter to our query, only the last item which matches filter is returned.

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12 
    gatsby-image: ^2.4.9 => 2.4.9 
    gatsby-plugin-manifest: ^2.4.14 => 2.4.14 
    gatsby-plugin-offline: ^3.2.13 => 3.2.13 
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.6 
    gatsby-plugin-sass: ^2.3.12 => 2.3.12 
    gatsby-plugin-sharp: ^2.6.14 => 2.6.14 
    gatsby-remark-classes: ^1.0.0 => 1.0.0 
    gatsby-remark-images: ^3.3.23 => 3.3.23 
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0 
    gatsby-source-filesystem: ^2.3.14 => 2.3.14 
    gatsby-source-mysql: ^2.2.3 => 2.2.3 
    gatsby-transformer-remark: ^2.8.27 => 2.8.27 
    gatsby-transformer-sharp: ^2.5.7 => 2.5.7 
  npmGlobalPackages:
    gatsby-cli: 2.12.49

**Comment by wardpeet** [comment]
Thank you for opening an issue, [gatsby-source-mysql](https://github.com/malcolm-kee/gatsby-source-mysql) is not a plugin we maintain. Please open up an issue on their repository instead.

Thank you for using Gatsby!

**Comment by i-bsd** [comment]
Just now encountered this issue myself.

@shubhambhatta did you resolve this? If so, please share.

**Comment by Justinkarso** [comment]
I had the same problem, fixed it by adding a custom id to idFieldName as well as adding one to the MySQL database table. I called it "alias". Seems gatsby-source-mysql needs a custom id for it to query all results. By simply using the primary key as id it only detects the last result like in our cases.

So basically this is my query from the gatsby-config.js
```
{
    statement: 'SELECT * FROM work',
    idFieldName: 'alias',
    name: 'work'
}
```
Where the name stands for the query name,
and the idFieldName stands for the custom id that the plugin uses to detect all your results.

The same goes for my database table.
So here I have added the same custom id I am specifying in the gatsby-config.js.

![image](https://user-images.githubusercontent.com/19993572/111655787-37abf980-880a-11eb-9d61-add90346330f.png)

my query returns the following.

![image](https://user-images.githubusercontent.com/19993572/111656144-8bb6de00-880a-11eb-9bd6-6a71210c256f.png)

So now you can see it returns all 5 rows within the table.
