### ISSUE TITLE
Cannot create images in a query with gatsby-plugin-feed and gatsby-plugin-sharp

### ISSUE THREAD

**Issue by johnridesabike** [gatsbyjs/gatsby#26227]
## Description

If you include `childImageSharp` in your `gatsby-plugin-feed` query, then it will usually\* crash on build. It seems to be that `gatsby-plugin-sharp` cannot generate new images when `gatsby-plugin-feed` runs. 

(\*If the `childImageSharp` query is able to use cached images, then the build succeeds. If it has to generate new images, then the build fails.)

An example of when this would be an issue: You have images in your markdown frontmatter to be used as “hero images” or “post thumbnails.” Even though they aren’t part of your markdown body, they’re relevant to the content and you want to include them in your RSS feed.

### Steps to reproduce

[I’ve created a demo repository here.](https://github.com/johnridesabike/gatsby-rss-demo) It’s based on `gastby-starter-blog`, and [this is the git diff between them](https://github.com/johnridesabike/gatsby-rss-demo/commit/6d7428f380dfe386b2223cea7522a5baa3b4330b).

```sh
git clone https://github.com/johnridesabike/gatsby-rss-demo.git
cd gatsby-rss-demo
npm install
gatsby build
```

### Expected result

The build should succeed with no issue.

### Actual result

The build crashes after the `onPostBuild` phase:

```
> gatsby build

success open and validate gatsby-configs - 0.039s
success load plugins - 1.016s
warn The Google Analytics plugin requires a tracking ID. Did you mean to add it?
success onPreInit - 0.017s
success delete html and css files from previous builds - 0.011s
success initialize cache - 0.008s
success copy gatsby files - 0.051s
warn gatsby-plugin-feed was initialized in gatsby-config.js without a feeds option.
This means that the plugin will use the internal RSS feed creation, which may not match
your use case.
This behavior will be removed in the next major release of gatsby-plugin-feed.
success onPreBootstrap - 0.016s
success createSchemaCustomization - 0.144s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.085s
success building schema - 0.260s
success createPages - 0.028s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.049s
success update schema - 0.025s
success onPreExtractQueries - 0.003s
success extract queries from components - 0.267s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.098s
success onPostBootstrap - 0.102s
info bootstrap finished - 6.147s
success run static queries - 0.056s - 2/2 35.43/s
success run page queries - 0.179s - 7/7 39.09/s
success write out requires - 0.006s
success Building production JavaScript and CSS bundles - 6.423s
success Rewriting compilation hashes - 0.007s
success Building static HTML for pages - 1.548s - 7/7 4.52/s
success Generating image thumbnails - 8.330s - 9/9 1.08/s
success onPostBuild - 0.021s
info Done building in 14.522525164 sec
not finished Generating image thumbnails - 0.044s

(sharp:63870): GLib-CRITICAL **: 13:23:13.517: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:63870): GLib-CRITICAL **: 13:23:13.543: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:63870): GLib-CRITICAL **: 13:23:13.557: g_hash_table_lookup: assertion 'hash_table != NULL’ failed
```

### Workarounds

Because the build succeeds if it can use cached images, then you can make it work by putting an identical `childImageSharp` query somewhere else in the site (which will generate the images to the cache).

However, there are cases where this isn’t ideal, such as if you want to use different image resolutions.

### Environment

```
  System:
    OS: macOS 10.15.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.26 => 2.24.26
    gatsby-image: ^2.4.14 => 2.4.14
    gatsby-plugin-feed: ^2.5.11 => 2.5.11
    gatsby-plugin-google-analytics: ^2.3.13 => 2.3.13
    gatsby-plugin-manifest: ^2.4.21 => 2.4.21
    gatsby-plugin-offline: ^3.2.21 => 3.2.21
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-sharp: ^2.6.24 => 2.6.24
    gatsby-plugin-typography: ^2.5.10 => 2.5.10
    gatsby-remark-copy-linked-files: ^2.3.12 => 2.3.12
    gatsby-remark-images: ^3.3.24 => 3.3.24
    gatsby-remark-prismjs: ^3.5.10 => 3.5.10
    gatsby-remark-responsive-iframe: ^2.4.12 => 2.4.12
    gatsby-remark-smartypants: ^2.3.10 => 2.3.10
    gatsby-source-filesystem: ^2.3.23 => 2.3.23
    gatsby-transformer-remark: ^2.8.27 => 2.8.27
    gatsby-transformer-sharp: ^2.5.12 => 2.5.12
  npmGlobalPackages:
    gatsby-cli: 2.12.66
```

**Comment by wardpeet** [comment]
Thanks for reporting, this is indeed a bug. Thank you

**Comment by benb1983** [comment]
Fixing your version to: "gatsby-plugin-sharp": "2.6.24" resolves the problem until sharp issue is resolved

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
