### ISSUE TITLE
Javascript exports in MDX files are not working according to the documentation

### ISSUE THREAD

**Issue by laurofialho** [gatsbyjs/gatsby#26230]
## Description

Following the guidelines of [exporting javascript objects](https://www.gatsbyjs.org/docs/mdx/writing-pages/#using-javascript-exports) from MDX files is not possible due to the fact that the graphql type for the `exports` is an array of strings. When I look at the graphql types for the `allMdx` and `mdx` queries, the type of exports is marked to be an array of strings, while in the examples it is treated as an object.

<img width="338" alt="Screen Shot 2020-08-04 at 8 37 25 PM" src="https://user-images.githubusercontent.com/56821651/89331581-505c0a80-d692-11ea-8dda-e11e21ab22f3.png">

### Expected result

Should be able to build the query as in the example:
```
exports {
  constOne {
    valueOne
  }
}
```
### Actual result

Not possible to query any specific exported constants nor their nested fields. I also tried to explicitly set the `exports` in `gatsby-node.js`, but as expected this was unsuccessful (example below):
```
type ExportMetadata {
  author: String
}
    
type ExportType {
  metadata: ExportMetadata
}

type Mdx {
  exports: ExportType
}
```
### Environment
```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 78.0.2
    Safari: 13.1.2
  npmPackages:
    gatsby: 2.24.11 => 2.24.11
    gatsby-plugin-mdx: 1.2.29 => 1.2.29
    gatsby-plugin-react-svg: 3.0.0 => 3.0.0
    gatsby-plugin-sass: 2.3.12 => 2.3.12
    gatsby-plugin-sharp: 2.6.22 => 2.6.22
    gatsby-plugin-styled-components: 3.3.10 => 3.3.10
    gatsby-plugin-typescript: 2.4.16 => 2.4.16
    gatsby-remark-dropcap: 0.1.2 => 0.1.2
    gatsby-remark-images: 3.3.21 => 3.3.21
    gatsby-remark-katex: 3.3.10 => 3.3.10
    gatsby-source-filesystem: 2.3.23 => 2.3.23
    gatsby-transformer-remark: 2.8.27 => 2.8.27
```

**Comment by wardpeet** [comment]
Hi @laurofialho!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by pvdz** [comment]
>     gatsby-plugin-mdx: 1.2.29 => 1.2.29

There was a known problem with exports in .29, so if you could please bump to gatsby-plugin-mdx@1.2.34 then I'm pretty sure this issue will be resolved. Sorry about the inconvenience.
