### ISSUE TITLE
Markdown Remark Bug after using Double Space Break [Line Break]

### ISSUE THREAD

**Issue by hendhyhutomo** [gatsbyjs/gatsby#26246]
## Description

I am currently working on a project with Gatsby and NetlifyCMS, the site is live and working well at [herbamojo.id](https://herbamojo.id). However recently my user started experiencing build failing issue due to "childImageSharp not defined". After further investigation, the issue was caused by the sure using "double-space linebreak" inside an "Ordered List". 

I have created a repo from Gatsby NetlifyCMS Starter [LINK](https://github.com/hendhyhutomo/gatsby-netlfycms-ImageIssue).

I modified one blog post that originally looks like:
![Screenshot 2020-08-05 at 21 05 33](https://user-images.githubusercontent.com/11151079/89422409-80bdaa80-d75f-11ea-915f-50042320a659.png)
To this (Notice the red mark to indicate double space)
![Screenshot 2020-08-05 at 21 06 00](https://user-images.githubusercontent.com/11151079/89422418-83200480-d75f-11ea-8b0a-3148101d6012.png)

This Original Blog has a Featured Image on the Blog Page, but after adding that double space the feature image disappear (a console log shows that childImageSharp is not defined).
<img width="1217" alt="Screenshot 2020-08-05 at 22 08 20" src="https://user-images.githubusercontent.com/11151079/89429866-49073080-d768-11ea-9dd7-9fffd29946a2.png">
<img width="1222" alt="Screenshot 2020-08-05 at 22 10 15" src="https://user-images.githubusercontent.com/11151079/89430024-7d7aec80-d768-11ea-87e8-78f264a283ec.png">

<img width="669" alt="Screenshot 2020-08-05 at 22 32 14" src="https://user-images.githubusercontent.com/11151079/89432632-8d480000-d76b-11ea-8f60-93fd39e63e85.png">

The issue doesn't show up initially during 'gatsby Develop'. The first tie I encounter it was during local 'gatsby build'. After further testing and reset, the error occurs on the second 'gatsby develop' and it is cached as well so that even if the double space is removed, only after using 'gatsby clean' we can reset the development back to normal.

Clearing the cache with gatsby clean and then running gatsby build manages to avoid the issue. I am still not sure why the error occurs on my netlify builds.

Replacing the double space line break with <br/> solves the issue. However, I am trying to avoid telling my user to use <br/> to smoothen the editorial experience. And the double space line break seems like [a default Markdown Syntax](https://www.markdownguide.org/basic-syntax/#line-breaks).

### Steps to reproduce

A Demo repo has been created with this link [LINK](https://github.com/hendhyhutomo/gatsby-netlfycms-ImageIssue).
I hosted it on Netlify with this [LINK](https://practical-lovelace-1cbbd5.netlify.app)

Without the Gatsby Clean command, the second build fails.
<img width="888" alt="Screenshot 2020-08-05 at 22 59 49" src="https://user-images.githubusercontent.com/11151079/89435703-6f7c9a00-d76f-11ea-8060-22e79d3c0d69.png">

I have created a new blog post called Image Breaking that I used to experiment and test the issue.

* Run the repo with Gatsby Develop. 
* Change the Markdown by adding the double space on a list (Error only occurs if there are multiple list item that contains double space). 
* You should immediately see that the image on /blog is missing or the page is broken because it is trying to find the childImageSharp. 

Sometimes it only occurs on the second gatsby develop (Terminate the first develop and then repeat the step).

Clearing the cache with gatsby clean, resets the issue. I assume there maybe a problem of how it is handled in cache?

### Expected result

Gatsby should still be able to access the Image ChildImageSharp normally. The error occurs randomly, so it questions the reliability of the build.

### Actual result

After a consecutive develop (or build after failed development), the post that contains double space has its Frontmatter Image not recognized my Transformer Sharp.

### Environment

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 78.0.2
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.20.35 => 2.24.23 
    gatsby-image: ^2.3.5 => 2.4.14 
    gatsby-plugin-netlify: ^2.2.4 => 2.3.11 
    gatsby-plugin-netlify-cms: ^4.2.5 => 4.3.11 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^3.2.5 => 3.3.10 
    gatsby-plugin-sass: ^2.2.4 => 2.3.12 
    gatsby-plugin-sharp: ^2.5.7 => 2.6.24 
    gatsby-remark-copy-linked-files: ^2.2.4 => 2.3.12 
    gatsby-remark-images: ^3.2.6 => 3.3.23 
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0 
    gatsby-source-filesystem: ^2.2.5 => 2.3.23 
    gatsby-transformer-remark: ^2.7.5 => 2.8.27 
    gatsby-transformer-sharp: ^2.4.7 => 2.5.12 
  npmGlobalPackages:
    gatsby-cli: 2.12.60

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v4 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

[reproduction]: https://gatsby.dev/reproduction
