### ISSUE TITLE
How to avoid using pageContext in Gatsby-Node to pass big changes of data to pages?

### ISSUE THREAD

**Issue by oneextra** [gatsbyjs/gatsby#26250]
##  Summary

We are currently developing a multi language website using Contentful + Gatsby. 
Our current build does a lot of automated slug generation. For example products in contentful have a slug and a category. 
When Gatsby-node runs to createPages we construct the slug by using **language slug**/**product page slug**/**category-slug**/**product-slug**.

Then there are pages in contentful that contain a reference that directly point to a product. 
In the page-query I can query the **product-slug** but in order to display a link I also need the **language slug**, and the **category slug** and the **product page slug**. While it is possible to query all these things to, it becomes incredibly error prone and cumbersome to create links in the templates, because the link structure also varies from content type and I end up using complicated mechanisms and longer than necessary queries to assemble links.

I resolved this problems, by creating a "link-dictionary" in gatsby-node that maps contentful_id to the correct slug. It is generated once at the beginning and then passed on to createPage context. Thus becoming available in the templates, that load that into a react-context-provider (or a global variable), making it available to all subcomponents. Now I only need to query contentful_id on any reference field and use the dictionary to get the long complicated links. The link structure also becomes conveniently defined in gatsby-node alone.  

This works well, but Gatsby complains that the pageContext is too large (exceeds 500kb) and I notice a slow down here, because the link-dictionary is quite expansive and unnecessary in the pageQueries.  

_What are the options to pass a big chunk of data, the link dictionary (just a big JSON/JS Object) to the page. 
Writing out a JSON file and reading it in? Are there any ways to define global variables in gatsby-node that might be available to the templates?_

**Comment by wardpeet** [comment]
At this moment, we suggest creating a JSON file and storing it inside the public directory.

Using gatsby-ssr you could load the json synchronously through a require call and git it to your provider and in gatsby-browser you could use a fetch call to obtain it from the server.

Would that solve your issue?

**Comment by KyleAMathews** [comment]
>While it is possible to query all these things to, it becomes incredibly error prone and cumbersome to create links in the templates, because the link structure also varies from content type and I end up using complicated mechanisms and longer than necessary queries to assemble links.

Would it be possible to put the logic into a function with lots of unit tests? Then use that to create the links for pages in gatsby-node as well as in the browser?

**Comment by oneextra** [comment]
Thank you for the great answers! I figured it out! 
I went for the JSON solution, which seems like a convenient way to pass global data. 

If someone stumbles upon it, this is how I did that:

in Gatsby-node.js I have

```
var fs = require('fs');

var globalData = ... 

fs.writeFile('public/globalPageData.json', JSON.stringify(globalData), function (err) {
        if (err) throw err;
        console.log('success'.green + ' Writing out public/globalPageData.json');
    });
```
in gatsby-ssr.js I added 
```
var fs = require('fs');
export const onRenderBody = ({ setHeadComponents }) => {

    var pageData = fs.readFileSync('./public/globalPageData.json');
    
    if(!pageData){
        throw new Error('Failed reading linkable Content Dictionary from JSON in gatsby-ssr.js');
    }
    setHeadComponents([
        <script dangerouslySetInnerHTML={{__html:`var globalPageData = ${pageData};`}} charSet={'utf8'} key={'linkdictionary'}/>
    ]);
}
```

now there is variable globalPageData accessible anywhere in the code. 
Use 
`declare const globalPageData;`
or @ts-ignore 
to prevent Typescript from complaining.

**Comment by drake-smith** [comment]
@oneextra @wardpeet How does this JSON global approach work for SEO purposes/Server side rendered HTML? The docs here https://www.gatsbyjs.org/docs/static-folder/ recommend importing the JSON inside componentDidMount / useEffect to avoid file size bloat.

So, the workflow would be like this?

1. Publish Contentful page entry with slug:  `a-page`
2. Link to that entry within a component using the Contentful entry slug.
3. Server-rendered HTML for that link would be:  <Link to=`/a-page` />
4. React hydration kicks in and on componentDidMount, update with actual path using the JSON dictionary file: <Link to=`/category/sub-category/a-page` />
 
Does that mean that the SSR HTML / search crawlers won't have the correct path?
