### ISSUE TITLE
Add messenger plugi in gatsby project

### ISSUE THREAD

**Issue by arslanbisharat** [gatsbyjs/gatsby#26262]
I am trying to add messenger on a project. Wherever I searched It is said to add "XYZ" code in body tag of HTML. But in gatsby, HTML is generated my npm install command so how should I do it?

**Comment by pieh** [comment]
Can you link to one of those guides so we talk about same service (is it facebook messenger?)? I can help with Gatsby-ifying those, but I need bit more info.

**Comment by arslanbisharat** [comment]
yes from facebook developers instruction

**Comment by arslanbisharat** [comment]
@pieh can you help me here
