### ISSUE TITLE
Unable to deploy site to gh-pages

### ISSUE THREAD

**Issue by vicradon** [gatsbyjs/gatsby#26263]
## Description
The deploy script fails and gives a message about node_modules being ignored

### Steps to reproduce

1. Clone this repo https://github.com/vicradon/vicradon.github.io
0. Install dependencies
0. run the deploy script

I can't share my github credentials, so reproduction won't be possible per se

### Expected result
No output on the console

### Actual result
```bash
$ yarn deploy
yarn run v1.22.4
$ gh-pages -d public -b master
The following paths are ignored by one of your .gitignore files:
node_modules
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```

### Environment
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.5 - /c/Users/vicradon/AppData/Local/Programs/Python/Python38/python
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.20.12 => 2.24.23
    gatsby-plugin-manifest: ^2.3.3 => 2.4.21
    gatsby-plugin-offline: ^3.1.2 => 3.2.21
    gatsby-plugin-react-helmet: ^3.2.1 => 3.3.10
    gatsby-plugin-sass: ^2.2.1 => 2.3.12

**Comment by pieh** [comment]
I tried forking in effort to reproduce, but I couldn't:

```
➜  i26263 git:(source) ✗ yarn build && yarn deploy
yarn run v1.16.0
warning ../package.json: No license field
$ gatsby build
success open and validate gatsby-configs - 0.020s
success load plugins - 0.434s
success onPreInit - 0.014s
success delete html and css files from previous builds - 0.011s
success initialize cache - 0.008s
success copy gatsby files - 0.073s
success onPreBootstrap - 0.009s
success createSchemaCustomization - 0.006s
success Checking for changed pages - 0.003s
success source and transform nodes - 0.036s
success building schema - 0.181s
success createPages - 0.014s
success Checking for changed pages - 0.002s
success createPagesStatefully - 0.047s
success update schema - 0.029s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.071s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.338s
success onPostBootstrap - 0.344s
info bootstrap finished - 5.113s
success run static queries - 0.024s - 2/2 84.07/s
success run page queries - 0.014s - 4/4 275.96/s
success write out requires - 0.006s
success Building production JavaScript and CSS bundles - 7.427s
success Rewriting compilation hashes - 0.007s
success Building static HTML for pages - 1.375s - 4/4 2.91/s
info Generated public/sw.js, which will precache 7 files, totaling 270561 bytes.
The following pages will be precached:
/offline-plugin-app-shell-fallback/index.html
success onPostBuild - 0.066s
info Done building in 14.145977722 sec
✨  Done in 14.32s.
yarn run v1.16.0
warning ../package.json: No license field
$ gh-pages -d public -b master
Published
✨  Done in 15.22s.
➜  i26263 git:(source) ✗
```

And this landed in https://github.com/pieh/vicradon.github.io/tree/master correctly. 

I don't really know much about github pages, but this seem like question/issue should be reported in github pages related repositories as you will probably get better support about this issue there (tho I do recognize your setup is following https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/#deploying-to-a-github-pages-subdomain-at-githubio ).
