### ISSUE TITLE
npm i gatsby-cli -g error

### ISSUE THREAD

**Issue by 3crazyspecial** [gatsbyjs/gatsby#26267]
## Description
when i use `npm i gatsby-cli -g`, it happen error
![image](https://user-images.githubusercontent.com/26181170/89514674-bd91ac00-d808-11ea-8920-9508452cede9.png)

node v10.21.0
npm v6.14.4

### Steps to reproduce

`npm i gatsby-cli`

### Expected result

install success

### Actual result

install error

### Environment

node v10.21.0
npm v6.14.4
Mac pro 16-inch

**Comment by Onixaz** [comment]
same problem here

**Comment by ahmetcanaydemir** [comment]
Duplicate of #26266

**Comment by pieh** [comment]
Closing as duplicate - please see https://github.com/gatsbyjs/gatsby/issues/26266#issuecomment-669819344 about likely cause of it
