### ISSUE TITLE
Remove Spectrum from issue templates

### ISSUE THREAD

**Issue by AishaBlake** [gatsbyjs/gatsby#26276]
## Summary

The documentation issue template includes a link to Spectrum, which we no longer use. This link should be removed from all issue templates.

### Motivation

Why should we document this and who will benefit from it?

### Draft the doc

- [ ] search for "Spectrum" in the issue template files and remove any links!

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #26276" in the pull request description

**Comment by taylorcjohnson** [comment]
Mind if I help with this one?

**Comment by muescha** [comment]
a follow up issue could be replace all spectrum links also in the docs

**Comment by taylorcjohnson** [comment]
Hi @muescha! I opened #26351 yesterday to remove the links from other markdown files in the repo, but I wasn't sure if we should also remove them from blog posts that have already been published (#100DaysOfGatsby, for example).

**Comment by muescha** [comment]
Great 👍
