### ISSUE TITLE
[gatsby-transformer-sharp] causing unknown error in gatsby-node.js graphql 

### ISSUE THREAD

**Issue by adamwiggall** [gatsbyjs/gatsby#2628]
gatsby: 1.9.79
gatsby-transformer-sharp: 1.6.13
gatsby-image: 1.0.15

Running the following  query
```
    {
      allMarkdownRemark(
        sort: { order: DESC, fields: [frontmatter___date] }
        limit: 1000
      ) {
        edges {
          node {
            html
            id
            frontmatter {
              path
              title
              category
              coverImage {
                childImageSharp {
                  sizes(maxWidth: 900) {
                    ...GatsbyImageSharpSizes_withWebp
                  }
                }
              }
            }
          }
        }
      }
    }
```
in `gatsby-node.js` is throwing
```
error Plugin default-site-plugin returned an error


  Error:

```
between the output of `createLayouts` and `createPages` when running `gatsby develop`, and breaking any `createPage` functionality.

If I modify the query removing the `sizes()` call, no error is thrown and all is well with the site (minus the images I'm trying to create). So, the following will work and output `sizes` for each post.
```
{
      allMarkdownRemark(
        sort: { order: DESC, fields: [frontmatter___date] }
        limit: 1000
      ) {
        edges {
          node {
            html
            id
            frontmatter {
              path
              title
              category
              coverImage {
                childImageSharp {
                  sizes {
                    sizes
                  }
                }
              }
            }
          }
        }
      }
    }
```

I am using the desired GraphQL query in `pages/index.js` as follows,
```
query IndexQuery {
    allMarkdownRemark(sort: { order: DESC, fields: [frontmatter___date] }) {
      edges {
        node {
          id
          frontmatter {
            title
            path
            category
            coverImage {
              childImageSharp {
                sizes(maxWidth: 900) {
                  ...GatsbyImageSharpSizes_withWebp
                }
              }
            }
          }
        }
      }
    }
  }
```
This doesn't throw any error and allows me to use `gatsby-image` for the `coverImage`.

Any help on this would be appreciated.

**Comment by KyleAMathews** [comment]
I'm guessing another query is causing the trouble? What happens if you remove other queries?

**Comment by adamwiggall** [comment]
I removed the two other graphql queries I have in the build and I still get the same error.

Interestingly if I edit one of the other queries while running `gatsby develop` I get this error 

```
error UNHANDLED REJECTION


Error: Invariant Violation: /Users/adam/Sites/site.example.com/src/templates/post.js not found in the store components: {
  "/Users/adam/Sites/site.example.com/src/layouts/index.js": {
    "componentPath": "/Users/adam/Sites/site.example.com/src/layouts/index.js"
    },
    "/Users/adam/Sites/site.example.com/.cache/dev-404-page.js": {
    "componentPath": "/Users/adam/Sites/site.example.com/.cache/dev-404-page.js",
    "query": "query Dev404Page {\n  allSitePage(filter: {path: {ne: \"/dev-404-page/\"}}) {\n totalCount\n edges {\n node {\n path\n }\n }\n  }\n}\n"
    },
    "/Users/adam/Sites/site.example.com/src/pages/404.js": {
    "componentPath": "/Users/adam/Sites/site.example.com/src/pages/404.js"
    },
    "/Users/adam/Sites/site.example.com/src/pages/about.js": {
    "componentPath": "/Users/adam/Sites/site.example.com/src/pages/about.js"
    },
    "/Users/adam/Sites/site.example.com/src/pages/index.js": {
    "componentPath": "/Users/adam/Sites/site.example.com/src/pages/index.js",
    "query": "query IndexQuery {\n  allMarkdownRemark(sort: {order: DESC, fields: [frontmatter___date]}) {\n edges {\n node {\n id\n frontmatter {\n title\n path\n category\n coverImage {\n childImageSharp {\n sizes(maxWidth: 900) {\n ...GatsbyImageSharpSizes_withWebp\n }\n }\n }\n }\n }\n }\n  }\n}\n\nfragment GatsbyImageSharpSizes_withWebp on ImageSharpSizes {\n  base64\n  aspectRatio\n  src\n  srcSet\n  srcWebp\n  srcSetWebp\n  sizes\n}\n"
  }
}

- invariant.js: 42 invariant
  [site.example.com]/[invariant]/invariant.js:42:15

- query - watcher.js: 98
  [site.example.com]/[gatsby]/dist/internal-plugins/query-runner/query-watcher.js:98:9

- Map.forEach

- query - watcher.js: 95
  [site.example.com]/[gatsby]/dist/internal-plugins/query-runner/query-watcher.js:95:15

- next_tick.js: 131 _combinedTickCallback
  internal/process/next_tick.js:131:7

- next_tick.js: 180 process._tickCallback
  internal/process/next_tick.js:180:9
```

Not sure what `not found in the store components` is referring to? Related?

**Comment by KyleAMathews** [comment]
Hmm is your site public so I could look at it? Or if not, could you build a reproduction for the problem that I could look at?

**Comment by adamwiggall** [comment]
The site is not public at present. 

Working on a reproduction now.

I'll come back to you, and thanks!

**Comment by adamwiggall** [comment]
Kyle.

I've moved all of the transformations out of `gatsby-node.js` and refactored the image processing.

All of the issues above are gone. No doubt a rookie mistake on my part.

I guess this one can be closed.

**Comment by pie6k** [comment]
@adamwiggall could you describe a bit more about how you've solved it. Any idea what it was? I've got exactly the same issue and not sure what my 'rookie mistake' might be.

**Comment by madox2** [comment]
I had the same problem. I have fixed it by moving image sharp query from `createPages` to template component query (in `blog.js`) and it worked for me.

However this is just workaround, it would be nice to resize images directly in `createPages`

**Comment by KyleAMathews** [comment]
Why would you want to resize images when creating pages?

**Comment by madox2** [comment]
In my case it is a matter of integration `gatsby-paginate` library. I need to display thumbnails in paginated posts list. I don't think the library uses best approach but I couldn't find any alternatives.

**Comment by v4iv** [comment]
> I had the same problem. I have fixed it by moving image sharp query from `createPages` to template component query (in `blog.js`) and it worked for me.
> 
> However this is just workaround, it would be nice to resize images directly in `createPages`

Hi, I'm facing the same problem, can you link the file that shows this work around?
