### ISSUE TITLE
Standardize reporter output

### ISSUE THREAD

**Issue by jacobshu** [gatsbyjs/gatsby#26285]
## Summary

This is super simple, but it's not a bug and didn't seem like a documentation issue. I think it would be good to standardize the reporter output to the console. Right now there's inconsistent capitalization, acronyms, and (grammatical) mood.

### Basic example

Specifically, I'd prefer the `activityTimer()`, `phantomActivity()`, and `createProgress()` methods to prefer console outputs that follow normal capitalization, normal acronym capitalization, and the imperative mood. 

current: `success delete html and css files from previous builds`
proposed: `success Delete HTML and CSS files from previous builds`

current: `success Rewriting compilation hashes`
proposed: `success Rewrite compilation hashes`

Function names would stay the same: `success createPagesStatefully`

### Motivation

Generally, I think consistency is a good thing. Visually, sentence capitalization creates a nice demarcation between the result (`success`) and what produced the result (`Rewrite compilation hashes`). If we adopt sentence capitalization, not correctly capitalizing acronyms would seem weird to me(`Delete html and css files from previous builds`). Lastly, I think the imperative mood makes for more concise logging and I'm personally used to it from [git commit messages](https://chris.beams.io/posts/git-commit/#imperative). 

The fixes should be simple but spread over several files: the files where the reporter methods are called, test files that check the console log, and documentation files that show expected outputs (for consistency's sake).

Incidentally, though this might be a separate code quality issue, the `reporter` module is often imported as `report` rather than its export and filename `reporter`.

**Comment by KyleAMathews** [comment]
Hey are you no longer interested in doing this? I think this is a great idea whoever wants to pick it up.

**Comment by jacobshu** [comment]
I'd be glad to.

**Comment by KyleAMathews** [comment]
Terrific! Want to do a few copy tweaks in a PR to start with? The code quality issue is a well-known problem and a bigger lift to do. If you'd like to tackle that as well, some of the core team has dug in on it and can discuss more what would need done.

**Comment by jacobshu** [comment]
Sure, would it be easier for y'all to break that into a separate issue or subsume it into this one?
