### ISSUE TITLE
Asciidoc transformer not working?

### ISSUE THREAD

**Issue by snide** [gatsbyjs/gatsby#26296]
## Description

The asciidoc transformer seems to not return any data.

### Steps to reproduce

This is a simple codesandbox with `gatsby-transformer-asciidoc` plugin and dependency added with a `pages/doc.adoc` file. No other changes from the default template

https://codesandbox.io/s/awesome-silence-gx6de?file=/gatsby-config.js

### Expected result

The `__graphql` browser should show `allAsciidoc` as available. The page should render at `/doc/`

### Actual result

It doesn't seem to return

### Environment

I see the same issue locally.

```
  System:
    OS: Linux 5.6 Manjaro Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Shell: 3.1.2 - /usr/bin/fish
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.21.0/bin/npm
  Languages:
    Python: 3.8.3 - /bin/python
  Browsers:
    Chrome: 83.0.4103.116
```

**Comment by pvdz** [comment]
I don't think we currently have anybody that knows much about this transformer.

It sounds like a bug and I'd be happy to see a PR that resolves it. If it's really about returning it then perhaps the fix is not that hard? :)

**Comment by snide** [comment]
Hello bot. This is still broken as far as I'm aware.

**Comment by KyleAMathews** [comment]
@snide could you compare your code to the asciidoc example site — https://github.com/gatsbyjs/gatsby/tree/master/examples/using-asciidoc — just tested that and it's working as expected. I'm guessing the problem is that you're expecting the transformer to create a new page automatically? Transformers just "transform" data into GraphQL types — which you can then use to create pages.

**Comment by LekoArts** [comment]
As Kyle pointed out your issue is that you don't actually create the page. Placing the doc file inside `src/pages` folder won't do anything. That only works for js/jsx/tsx files (with valid React component as default export). Using the linked example should solve your issue.
