### ISSUE TITLE
Add API to allow plugins to add/modify CLI commands

### ISSUE THREAD

**Issue by vitalybe** [gatsbyjs/gatsby#263]
The process for creating a new post (e.g in blog-starter) in gatsby is a bit cumbersome - Creating a folder with unique name, creating a markup file with specific format, etc.

Writing a post generator would be trivial, but I wonder, is there something in gatsby that already does it?

**Comment by KyleAMathews** [comment]
There's not. I'm currently designing a revamp of Gatsby's APIs + a plugin system that'd let you add additional commands to Gatsby's CLI tool e.g. `gatsby create post` or something like that to setup a default new post. You could then distribute that tool as a plugin on NPM.

In the meantime, I don't know of any open sourced post generator tool that you can install. If you're looking for some sample code, @pamo built one for her blog at https://github.com/pamo/pamo.github.io/blob/development/new_post.js

**Comment by KyleAMathews** [comment]
Just saw this on Twitter https://www.npmjs.com/package/microgen
