### ISSUE TITLE
[gatsby-plugin-offline] What use is the offline app shell?

### ISSUE THREAD

**Issue by kije** [gatsbyjs/gatsby#26303]
Hi

I have a gastby site which uses gatsby-plugin-offline to provide offline support.
As far as I understood it, the purpose of the app-shell is to display something to the user when he's offline but tries to navigate to a page that isn't yet cached by the service worker.

However, the app-shell provided by gatsby-plugin-offline just renders a blank page, and as far as I could tell from the documentation/inspecting the source code of the plugin, there is no way to customize the apps shell, e.g. by providing a custom component or similar.

So my question is, of what use this app shell really is?

**Comment by pvdz** [comment]
Hi. I'm not super familiar with the plugin myself but [reading the docs](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-offline/README.md) it states

> - `precachePages` lets you specify pages whose resources should be precached by the service worker, using an array of globs.

Is this different from what you're asking?
