### ISSUE TITLE
Suggestion: Option to set initial dev route logged to terminal

### ISSUE THREAD

**Issue by mrseanbaines** [gatsbyjs/gatsby#26312]
## Summary

It would be great if there was an option to set the initial route that gets logged when running `gatsby develop` (e.g. `/en/` instead of `/`):

<img width="331" alt="image" src="https://user-images.githubusercontent.com/24367010/89736356-b369ea80-da60-11ea-98e1-9cb4e48aeab6.png">

So this ☝️ would then log http://localhost:8000/en/

One example use case would be for localised sites where there _is_ no page at `/`. Currently if you have a site like this and click on the suggested URL (http://localhost:8000/) where you're told you can view your site, you end up getting a 404.

### Basic example

I would imagine this would simply require an additional option in `gatsby-config` to set the initial route, e.g.:

```js
module.exports = {
  initialRoute: `/en/`
  ...
}
```

Not sure if `initialRoute`, `defaultPath` or something else would be the best name for this.

### Motivation

It's a small thing, but in my opinion would be a really nice addition and I assume very little effort involved in achieving this.

I'm happy to look into this and try to open a PR if the suggestion is accepted.

**Comment by blainekasten** [comment]
Thanks for the suggestion! Does your site need a redirect from `/` to `/en` when it's deployed or anything? Most users solve this problem with creating a redirect.


```js
// gatsby-node.js
exports.createPages = ({actions}) => actions.createRedirect({fromPath: "/", toPath: "/en"})
```

**Comment by mrseanbaines** [comment]
Hi @blainekasten. It does indeed need a `/` to `/en` redirect in production. By my understanding, `createRedirect` will only have an effect when running `gatsby develop`, right?

I had thought of this as possible solution - I just thought it would be a bit nicer for the URL showing in the terminal to be the one you actually end up on if you follow the link. Could also be clearer for other devs coming into the project, otherwise they may not know where the redirect is coming from. 🤷‍♂️
