### ISSUE TITLE
Failure to run when project in /node_modules/ folder

### ISSUE THREAD

**Issue by TijlB99** [gatsbyjs/gatsby#26311]
## Summary
I'm trying to put my gatsby project in an npm package and when I place the project inside a node_modules folder, it throws an error while otherwise it runs fine (this is also the case if I just rename a parent directory to node_modules). 
When building I get the following error:
```
failed Building production JavaScript and CSS bundles - 2.134s

 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

/home/username/Documents/folders/node_modules/l-td/.cache/production-app.js: Support for the experimental syntax 'jsx' isn't currently enabled (55:5):

  53 |   // Remove this in v3
  54 |   const RouteHandler = props => (
> 55 |     <BaseContext.Provider
     |     ^
  56 |       value={{
  57 |         baseuri: `/`,
  58 |         basepath: `/`,

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.

File: .cache/production-app.js:55:4
```
Adding those babel packages to my `.babelrc` didn't change anything and I'm fairly sure it's just webpack ignoring things inside /node_modules/ folders.

## Relevant information
Basically the same problem as this: https://github.com/gatsbyjs/gatsby/issues/2792, but that syntax doesn't work anymore.
I think I just need this
```
exports.modifyWebpackConfig = ({ config }) => {
  config._loaders.js.config.exclude = new RegExp(process.cwd() + '/(node_modules|bower_components)');
};
```
but modifyWebpackConfig doesn't exist anymore and is replaced with 
```
exports.onCreateWebpackConfig = ({ actions }) => { 
  actions.setWebpackConfig({
    config._loaders.js.config.exclude = new RegExp(process.cwd() + '/(node_modules|bower_components)'); // <- this line doesn't work
  })
  
}
```
Even from the examples from the [onCreateWebpackConfig](https://www.gatsbyjs.org/docs/add-custom-webpack-config/) page I can't figure out what fields I should be modifying.

### Environment (if relevant)

 System:
    OS: Linux 5.6 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.7 - /usr/bin/npm
  Languages:
    Python: 3.8.3 - /usr/bin/python
  Browsers:
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.24.35 => 2.24.35
    gatsby-plugin-local-search: ^1.1.1 => 1.1.1
    gatsby-plugin-manifest: ^2.4.22 => 2.4.22
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-sharp: ^2.6.25 => 2.6.25
    gatsby-plugin-smoothscroll: ^1.2.0 => 1.2.0
    gatsby-source-filesystem: ^2.3.24 => 2.3.24
    gatsby-transformer-json: ^2.4.11 => 2.4.11
  npmGlobalPackages:
    gatsby-cli: 2.12.80

### File contents
`.babelrc`:
```
{
  "presets": ["babel-preset-gatsby"],
  "plugins": [
    "@babel/plugin-syntax-jsx",
    ["prismjs", {
      "languages": ["javascript", "json", "css"],
      "plugins": ["line-numbers", "show-language"],
      "theme": "tomorrow",
      "css": true
    }]
  ]
}
```

**Comment by blainekasten** [comment]
This is happening because webpack (and maybe babel?) ignores node_modules. So the files that are in node_modules that are written in ES6 and JSX aren't getting compiled to valid javascript. 

You'll likely need to tweak some settings around webpack and babel. I would probably need to get access to the source to really advise on how to achieve that since your setup is atypical. 

However, this is not really a way we've developed gatsby in mind, so there is a possibility of rough edges that I can't guarantee we would prioritize. 

What is the use case for putting your gatsby app in node_modules?

**Comment by TijlB99** [comment]
This is the source: https://github.com/luciad/typescript-documentation

Basically what I'm trying to do is use gatsby to generate a site from a json input. I wrote a bash script where I can specify the input in command line and do some other things that don't really matter for this problem. 
This way, I can call the script, specify the JSON, wait for gatsby to do its thing and get the wanted output (the script then moves the output to the desired location).
This works as expected in a normal folder. 
The use case is then to make this an npm package so you can do this from anywhere where it is installed, use it in combination with other npm packages etc.

**Comment by TijlB99** [comment]
This has solved the issue:

`gatsby-node.js`
```
/**
 * https://www.gatsbyjs.com/docs/add-custom-webpack-config/
 */
exports.onCreateWebpackConfig = ({ actions, loaders, getConfig }) => {
  const config = getConfig()
  config.module.rules = [
    // Omit the default rule where test === '\.jsx?$'
    ...config.module.rules.filter(
      rule => String(rule.test) !== String(/\.jsx?$/)
    ),
    // Recreate it with custom exclude filter
    {
      ...loaders.js(),
      test: /\.jsx?$/,
      // Exclude all node_modules from transpilation, except for 'project_name'
      exclude: modulePath =>
        /node_modules/.test(modulePath) &&
        !/node_modules\/(project_name)/.test(modulePath),
    },
  ]
  // This will completely replace the webpack config with the modified object.
  actions.replaceWebpackConfig(config)
}
```

where project_name is the name of the npm project.

**Comment by servrox** [comment]
@TijlB99 thanks for your input here! 🙏

I'm using a nx monorepo with gatsby. when i added plugins containing jsx i got errors above.

your solution worked for me too! ..i was already going crazy :J

```
// Exclude all node_modules from transpilation, except for 'gatsby-plugin-use-query-params' + 'gatsby-theme-style-guide'
exclude: (modulePath) =>
    /node_modules/.test(modulePath) &&
    !/node_modules\/(gatsby-plugin-use-query-params|gatsby-theme-style-guide)/.test(
         modulePath,
    ),
```

> if someone also has problems with the nx workspace: the [nrwl/gatsby-example](https://github.com/nrwl/gatsby-example) + above script solved all my problems (no babel plugins or ts tweaks)
