### ISSUE TITLE
Is there a document about unit testing?

### ISSUE THREAD

**Issue by liuchong** [gatsbyjs/gatsby#2632]
I've checked the documents, but did not found a description about unit test, is there anything that I'd missed?
Also, I would like to know that how could I filter the test case beside the source file in the pages folder.
I could do approach it by add a "_" on the start of the filename, such as "_somepage.test.tsx", but is there a filter exists?
Or maybe I should not do this, as the pages are all "pages" :joy_cat:

**Comment by KyleAMathews** [comment]
Not really… but look for directories named `__tests__` and you'll find lots of examples of tests.

Or do you mean unit testing Gatsby sites?

**Comment by liuchong** [comment]
Thanks, I mean that when I use gatsby build a site, I would write some codes like "components/xxx.tsx", "pages/my-page.tsx", and then add some unit tests, like "components/xxx.test.tsx" and "pages/my-page.test.tsx", but the my-page.test.tsx will be recognized as a page.
So it seems there are no config options such as { "filter": ".*.test.tsx" } to let it avoid the test files.
Anyway, this is not very ... important, there are other ways :joy_cat:

**Comment by liuchong** [comment]
But is I add a graphql`something` in my pages and layouts, it should query through gatsby, seems I should import something in gatsby?
