### ISSUE TITLE
Fix CI validation for starters yaml

### ISSUE THREAD

**Issue by Knochenmark** [gatsbyjs/gatsby#26326]
You might want to fix your validation for the starters yaml.

It seems like the validation includes the npm audit check, which probably makes no sense when validating a simple yaml file.

Therefore I suggest you exclude the audit check from that starter validation check.

**Comment by blainekasten** [comment]
Thanks for the recommendation @Knochenmark, we're aware of the issue and always looking for ways to stabilize and improve our process. 

I'm going to close this issue as we're tracking this internally. Thanks!
