### ISSUE TITLE
Small improvement for RSS feed - W3C validation fix atom

### ISSUE THREAD

**Issue by Fasani** [gatsbyjs/gatsby#26325]
## Description

In the official RSS plugin:
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-feed

A small improvement could be made for better W3C validation. I recently used W3C to check my RSS feed was configured correctly and I noticed this issue.

### Steps to reproduce

My feed result:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.michaelfasani.com%2Frss.xml

### Expected result

W3C validation should be perfect but it suggests the following change:

```
Recommendations
This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

line 1, column 3376: Missing atom:link with rel="self" [help]

... 5 May 2020 14:23:23 GMT</pubDate></item></channel></rss>
```

How to fix:

Insert the following node into the `<channel>` node with the correct URL specified.

`<atom:link href="http://dallas.example.com/rss.xml" rel="self" type="application/rss+xml" />`

**Comment by blainekasten** [comment]
@Fasani Thanks for the report! I don't know much about RSS honestly, is this something you would be interested in submitting a PR for?

**Comment by Fasani** [comment]
Sure!

**Comment by Fasani** [comment]
I was able to fix it for myself by doing the following in `gatsby-config.js`
```
setup: (options) => ({
        ...options,
        custom_elements: [
                {
                        'atom:link href="https://www.michaelfasani.com/rss.xml" rel="self" type="application/rss+xml"': null,
                },
        ],
}),
```

Now just contemplating how to best to do it in the plugin without breaking this existing functionality of passing `custom_elements` from the `gatsby-config.js`.

**Comment by Fasani** [comment]
TBH I think there is not a clean way to do this in the Gatsby Plugin and my assumption is that the work should be done in the RSS generator repo: https://github.com/dylang/node-rss/tags but that repo was not touched since 2017 so I think it is perhaps unlikely.

It would have to be here (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-feed/src/internals.js) in the `defaultOptions` but as you can see from my fix above you have all the data + injected site url in the `key` and a `null` for the value. It's already a bit odd in terms of set up, but that is the nature of injecting a node in the RSS module according to what  W3C wants it to be.

I think for now I would just close this ticket and for anyone who cares enough they can figure out what I did above, it was also just a recommendation from W3C so it is not exactly broken more just can be improved.

But I can confirm my site feed is now perfect with the above fix in the `gatsby-config.js` js file.

<img width="1082" alt="Screenshot 2020-08-11 at 00 23 52" src="https://user-images.githubusercontent.com/448410/89837291-f57e5380-db68-11ea-97ed-233a7b907bd8.png">
