### ISSUE TITLE
[gatsby-source-shopify] - "quantityAvailable" and "totalInventory" still not queryable after custom queries PR was merged.

### ISSUE THREAD

**Issue by abohannon** [gatsbyjs/gatsby#26321]
## Description

In [this PR](https://github.com/gatsbyjs/gatsby/pull/23922) there was a solution proposed to add custom queries for things like "quantityAvailable" and "totalInventory". However, neither of those fields seem to have been implemented in said PR.

When adding the key `shopifyQueries` and providing the default product query provided in the repo to the config in `gatsby-config.js`, everything works fine. When I add `availableQuantity` to the variants object (nested in the product query), I get:

`Field 'quantityAvailable' doesn't exist on type 'ProductVariant'`
or 
`Field 'totalInventory' doesn't exist on type 'Product'`

despite both being provided by the native Shopify API.

### Steps to reproduce

1. In `gatsby-config.js` under `gatsby-source-shopify`, add:
```
shopifyQueries: {
  product: <<DEFAULT_PRODUCT_QUERY>>
}
```
2. Build w/ this config to ensure all queries work properly.
3. If build succeeds, edit the default query by adding `availableQuantity` on the variants object
```
variants(first: 250) {
          edges {
              node {
              availableQuantity
              ...
```
4. The build should fail during shopify queries.

### Expected result

It should query all fields provided by the native shopify api correctly

### Actual result

Query fails for a known field, such as `availableQuantity`.

### Environment

```
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.7.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.21.21 => 2.24.11
    gatsby-image: ^2.2.29 => 2.4.13
    gatsby-plugin-google-analytics: ^2.0.13 => 2.3.13
    gatsby-plugin-layout: ^1.0.11 => 1.3.10
    gatsby-plugin-manifest: ^2.2.23 => 2.4.21
    gatsby-plugin-offline: ^3.0.16 => 3.2.21
    gatsby-plugin-react-helmet: ^3.1.13 => 3.3.10
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-sass: ^2.3.1 => 2.3.12
    gatsby-plugin-sharp: ^2.2.32 => 2.6.22
    gatsby-source-filesystem: ^2.1.33 => 2.3.23
    gatsby-source-shopify: ^3.2.26 => 3.2.26
    gatsby-transformer-sharp: ^2.3.0 => 2.5.11
  npmGlobalPackages:
    gatsby-cli: 2.12.37
```

**Comment by RistoBIn** [comment]
The `quantityAvailable` still not available.
Is there anyone solve this issue?

**Comment by LekoArts** [comment]
Hi! We've released a new major verison (v5) which fundamentally works different. Please try the upgrade and if you still hit this please open a new issue with a reproduction. Thanks!
