### ISSUE TITLE
Docs Plugins Overview Missing Links (GuideList)

### ISSUE THREAD

**Issue by Nick-Mazuk** [gatsbyjs/gatsby#26335]
## Description

https://www.gatsbyjs.org/docs/plugins/

This documentation page should list the guides in the plugins section. However, it appears that the output from the `GuideList` isn't producing the list in the published GatsbyJS site

:

`<GuideList slug={props.slug} />`

Here's the corresponding MD file: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/plugins.md

**Comment by AdamSiekierski** [comment]
Yea, it looks like this component doesn't show at all - `docs/conceptual-guide.md` also doesn't show it. Maybe it's not imported in the MDX provider? I'll take a look at it.

**Comment by AdamSiekierski** [comment]
Well, it seems that it has been fixed by now. Closing the issue

**Comment by Nick-Mazuk** [comment]
Looks fixed on my end with the new site update.
