### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by nnhhiilliisstt** [gatsbyjs/gatsby#26336]
## Description

Failed to compile

### Steps to reproduce

gatsby new project-name https://github.com/LekoArts/gatsby-starter-portfolio-jodie
gatsby develop

### Expected result

success in building

### Actual result
 ERROR #85923  GRAPHQL

### Environment

There was an error in your GraphQL query:

Cannot query field "allInstaNode" on type "Query".

If you don't expect "allInstaNode" to exist on the type "Query" it is most likely a typo.
However, if you expect "allInstaNode" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allInstaNode" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: C:/Users/user/Documents/gatsby-insta-feed/project-name/src/pages/instagram.tsx

**Comment by blainekasten** [comment]
According to the documentation for the starter there is a bit of a process to get the configuration working. I'm going to close this as it's not a problem with Gatsby itself.

I recommend following the configuration docs [here](https://github.com/LekoArts/gatsby-starter-portfolio-jodie#configuring-the-instagram-source-plugin). Good luck!
