### ISSUE TITLE
[gatsby-image] Same TracedSVG with same filenames

### ISSUE THREAD

**Issue by LeKoArts** [gatsbyjs/gatsby#2634]
Hi.

I'm currently using gatsby-image and its recently released TracedSVG functionality. While building a grid layout I encountered the problem that the TracedSVG of all images is the same. After a while I figured out that the problem is the same file names I used. To make things clearer:

I'm querying for all markdown files and the image defined as a cover there. The frontmatter of every markdown file has a cover:
```
------------
cover: "./cubeRound.jpg"
...
------------
```

![17_10_0s716cad](https://user-images.githubusercontent.com/16143594/32046565-bb362ab6-ba43-11e7-8117-4ecb3db80110.png)

Before that every image had the filename ``cover.jpg``. Hence this was the frontmatter:
```
------------
cover: "./cover.jpg"
...
------------
```

But with that all images had the same TracedSVG even though every image was different.

**Comment by fk** [comment]
Thanks for reporting @LeKoArts! Can confirm this.

I don't have much time today but if anyone wants to take a stab here's a reproduction with `examples/using-remark`: https://github.com/fk/gatsby/tree/topics/reproduce-2634

"Hello World…", "Copying Linked Files…", "Code and Syntax Highlighting…" articles all have different images (sharing an identical filename) but show the same placeholder SVG.

**Comment by LeKoArts** [comment]
Thanks for the quick fix!
