### ISSUE TITLE
Support HTTPS for the develop status server

### ISSUE THREAD

**Issue by mxstbr** [gatsbyjs/gatsby#26359]
This is split out from #24862, see that issue for more context. The develop status server (created in `gatsby/src/commands/develop.ts`) should support HTTPS, right now it always uses http:

https://github.com/gatsbyjs/gatsby/blob/76cddc7ff2e4d7d2db6d5bc2d1e2dc765af62c1d/packages/gatsby/src/commands/develop.ts#L299-L300

**Comment by vhiairrassary** [comment]
@mxstbr I spent some time working on that and would love to get your feedbacks: https://github.com/gatsbyjs/gatsby/pull/27955. Thank you in advance for your the time spent on this.
