### ISSUE TITLE
CircleCI starters_validate failing

### ISSUE THREAD

**Issue by aaaakshat** [gatsbyjs/gatsby#26363]
## Description

Nearly every pending [add-starter PR](https://github.com/gatsbyjs/gatsby/pulls?q=is%3Apr+is%3Aopen+label%3A%22topic%3A+starters%22) is failing due to the `starters_validate` test on CircleCI failing. Even the [past few merged PRs](https://github.com/gatsbyjs/gatsby/issues?q=label%3A%22topic%3A+starters%22+is%3Aclosed) were merged despite failing `starters_validate` which suggests that it is failing on valid submissions.

![Failed starter_validate tests](https://user-images.githubusercontent.com/33050725/89902002-7d6f6680-dc18-11ea-9235-d44c4f801668.png)

### Steps to reproduce

1. Visit the [`topic: starters` opened PRs](https://github.com/gatsbyjs/gatsby/pulls?q=is%3Apr+label%3A%22topic%3A+starters%22+is%3Aopen)
1. Look at any PR on the list, all except 2 are suffering from `starters_validate` failing

### Expected result

Observing the [merged PRs](https://github.com/gatsbyjs/gatsby/pulls?q=is%3Apr+label%3A%22topic%3A+starters%22+is%3Aclosed) they appeared to be suffering from the same issue and the fact that they were merged suggests that the expected result would be `starters_validate` returning a successful `exit code status 0`

### Actual result

Tests are returning

```shell
found 44 vulnerabilities (42 low, 2 high) in 2472 scanned packages
  run `npm audit fix` to fix 42 of them.
  2 vulnerabilities require manual review. See the full report for details.

Exited with code exit status 1
```

### Environment

This is a test run through CircleCI so I'm not sure of the environment. However, here is one of the [CircleCI logs](https://circleci.com/gh/gatsbyjs/gatsby/486479?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) for a failed `starters_validate` test.

**Comment by aaaakshat** [comment]
Just to give some examples of current PRs that are failing due to this error:
1. #26388 
1. #26374
1. #25338
1. #26338
1. #26331

**Comment by LekoArts** [comment]
Since we paused the submissions to the showcases and this will only fail due to some alerts we can mostly ignore, I'll close this. Thanks for the issue though!
