### ISSUE TITLE
Redirect on GitHub page is not work

### ISSUE THREAD

**Issue by kpman** [gatsbyjs/gatsby#2636]
## Demo repo

I have created a demo repo for this issue.

repo: https://github.com/kpman/gatsby-redirect-with-path-prefix
gh-pages: https://kpman.github.io/gatsby-redirect-with-path-prefix/

## Problem

The problem is when I am using the `createRedirect` on develop, it works fine.
But when I deploy it to GitHub page, the redirect will not work.

## Custom

The repo is under my GitHub account called `gatsby-redirect-with-path-prefix`.

### gatsby-config.js

I added `pathPrefix` which its value is: `/gatsby-redirect-with-path-prefix` on **gatsby-config.js**

### gatsby-node.js

And I also added the **gatsby-node.js** file on root for the redirection.
```
exports.createPages = ({ boundActionCreators }) => {
  const { createRedirect } = boundActionCreators;

  createRedirect({
    fromPath: `/redirect-page`,
    isPermanent: true,
    redirectInBrowser: true,
    toPath: `/page-2/`,
  });

  createRedirect({
    fromPath: `/redirect-page/`,
    isPermanent: true,
    redirectInBrowser: true,
    toPath: `/page-2/`,
  });
};
```

### npm script

My deploy script is `gatsby build --prefix-paths && gh-pages -d public -m 'Auto-generated commit'`
I leverage the package called [gh-pages](https://github.com/tschaub/gh-pages)

Hope someone can help me to solve this problem.
Thanks.

**Comment by KyleAMathews** [comment]
Thanks for raising this issue. Prefix support hasn't been added to redirects. Could you create a PR for this? It should be added to the createRedirects action in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/actions.js

You can pull the path prefix and if it's enabled off the program object. Search around the code base for other examples.

**Comment by kpman** [comment]
@KyleAMathews Thanks for giving the hint.
I've created a PR #2651.
