### ISSUE TITLE
`--inspect-brk=0.0.0.0` does not set host successfully

### ISSUE THREAD

**Issue by narthur** [gatsbyjs/gatsby#26379]
## Description

Using `--inspect-brk=0.0.0.0` with `gatsby develop` does not set debugger to listen on 0.0.0.0 [as Node's docs indicate it does when used on node directly](https://nodejs.org/en/docs/guides/debugging-getting-started/).

### Steps to reproduce

1. `node --no-lazy node_modules/.bin/gatsby develop --inspect-brk=0.0.0.0`
2. See in logs: `Debugger listening on ws://127.0.0.1:9229/43d0600c-22dc-40e9-98f6-f27004b6d353`

### Expected result

Debugger should listen on 0.0.0.0, not 127.0.0.1

### Actual result

Debugger listens on 127.0.0.1 instead of 0.0.0.0

### Environment

```
  System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (6) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: ^2.23.12 => 2.24.24
    gatsby-image: ^2.4.9 => 2.4.14
    gatsby-plugin-manifest: ^2.4.18 => 2.4.21
    gatsby-plugin-offline: ^3.2.13 => 3.2.21
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.10
    gatsby-plugin-sass: ^2.3.12 => 2.3.12
    gatsby-plugin-sharp: ^2.6.14 => 2.6.24
    gatsby-source-filesystem: ^2.3.14 => 2.3.23
    gatsby-source-graphql: ^2.6.1 => 2.6.2
    gatsby-transformer-sharp: ^2.5.7 => 2.5.12
  npmGlobalPackages:
    gatsby-cli: 2.12.59
```

**Comment by pieh** [comment]
Hi @narthur. Right now the `gatsby develop`s `--inspect(-brk)` switches only handle ports and not the host part:

https://github.com/gatsbyjs/gatsby/blob/75add7b06dd740ea2577b357bc0056a6c754ac8c/packages/gatsby/src/commands/develop-process.ts#L61-L69

(per nodejs docs https://nodejs.org/api/inspector.html#inspector_inspector_open_port_host_wait - `inspector.open` 2nd param is the host, which we just don't set right now.

For reference those are the changes that introduced those cli switches - https://github.com/gatsbyjs/gatsby/pull/24693 - to support host part we would need to adjust cli flags (yargs configuration) to be strings and then do some handling to split passed strings into host + port, so syntaxes like:
 - `--inspect-brk=0.0.0.0` - result in setting host and using default port
 - `--inspect-brk=0.0.0.0:9230` - result in setting host and port
 - `--inspect-brk=9230` - result in setting port and using default host

**Comment by narthur** [comment]
@pieh Thanks for the info! Are you open to a PR on this?

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
