### ISSUE TITLE
Installing new theme broke my app, after uninstalling the theme I'm getting GraphQL query errors

### ISSUE THREAD

**Issue by Nicknyr** [gatsbyjs/gatsby#26377]
## Description

I'm new to Gatsby and built a basic blog app. I installed a new theme and attempted to apply it and it completely broke my app. I'm getting a bunch of "cannot query field x on type Query" errors.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

My app should function

### Actual result

The following error: 

> There was an error in your GraphQL query:

Cannot query field "themeUiConfig" on type "Query".

If you don't expect "themeUiConfig" to exist on the type "Query" it is most likely a typo.
However, if you expect "themeUiConfig" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "themeUiConfig" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/nick/Desktop/learn-gatsby/node_modules/gatsby-plugin-theme-ui/src/hooks/configOptions.js

There was an error in your GraphQL query:

Cannot query field "social" on type "SiteSiteMetadata".

If you don't expect "social" to exist on the type "SiteSiteMetadata" it is most likely a typo.
However, if you expect "social" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "social" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "SiteSiteMetadata":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/nick/Desktop/learn-gatsby/node_modules/gatsby-theme-blog-core/src/templates/post-query.js

There was an error in your GraphQL query:

Cannot query field "blogPost" on type "Query".

If you don't expect "blogPost" to exist on the type "Query" it is most likely a typo.
However, if you expect "blogPost" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "blogPost" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/nick/Desktop/learn-gatsby/node_modules/gatsby-theme-blog-core/src/templates/post-query.js

There was an error in your GraphQL query:

Cannot query field "blogPost" on type "Query".

If you don't expect "blogPost" to exist on the type "Query" it is most likely a typo.
However, if you expect "blogPost" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "blogPost" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/nick/Desktop/learn-gatsby/node_modules/gatsby-theme-blog-core/src/templates/post-query.js

There was an error in your GraphQL query:

Cannot query field "blogPost" on type "Query".

If you don't expect "blogPost" to exist on the type "Query" it is most likely a typo.
However, if you expect "blogPost" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "blogPost" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/nick/Desktop/learn-gatsby/node_modules/gatsby-theme-blog-core/src/templates/post-query.js

There was an error in your GraphQL query:

Cannot query field "social" on type "SiteSiteMetadata".

If you don't expect "social" to exist on the type "SiteSiteMetadata" it is most likely a typo.
However, if you expect "social" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "social" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "SiteSiteMetadata":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/nick/Desktop/learn-gatsby/node_modules/gatsby-theme-blog-core/src/templates/posts-query.js

There was an error in your GraphQL query:

Cannot query field "allBlogPost" on type "Query".

If you don't expect "allBlogPost" to exist on the type "Query" it is most likely a typo.
However, if you expect "allBlogPost" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allBlogPost" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/nick/Desktop/learn-gatsby/node_modules/gatsby-theme-blog-core/src/templates/posts-query.js

There was an error in your GraphQL query:

Cannot query field "siteUrl" on type "SiteSiteMetadata".

If you don't expect "siteUrl" to exist on the type "SiteSiteMetadata" it is most likely a typo.
However, if you expect "siteUrl" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "siteUrl" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "SiteSiteMetadata":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/nick/Desktop/learn-gatsby/node_modules/gatsby-theme-blog/src/components/seo.js

There was an error in your GraphQL query:

Cannot query field "blogThemeConfig" on type "Query".

If you don't expect "blogThemeConfig" to exist on the type "Query" it is most likely a typo.
However, if you expect "blogThemeConfig" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "blogThemeConfig" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/nick/Desktop/learn-gatsby/node_modules/gatsby-theme-blog/src/hooks/configOptions.js

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by laurieontech** [comment]
Thanks for opening the issue! It looks like you're missing some of the required metadata for this theme as well as markdown files for it to reference. I'd recommend walking through the [tutorial](https://www.gatsbyjs.org/tutorial/using-a-theme/) as it notes the minimal required information to set up.

I'm going to close this issue for now. But please feel free to reopen it if this does not solve the issue.

**Comment by killoblanco** [comment]
Hi @Nicknyr, hope this ain't too late. I had the same problem after installing `gatsby-theme-blog`. So my solution was to run `$ npm uninstall gatsby-theme-blog && npm cache verify` restart the Gatsby dev server and done. :D

**Comment by juliendf** [comment]
> Hi @Nicknyr, hope this ain't too late. I had the same problem after installing `gatsby-theme-blog`. So my solution was to run `$ npm uninstall gatsby-theme-blog && npm cache verify` restart the Gatsby dev server and done. 😄

Same issue, same solution ! Thanks @killoblanco

**Comment by Adam-Al-Rahman** [comment]
> Hi @Nicknyr, hope this ain't too late. I had the same problem after installing `gatsby-theme-blog`. So my solution was to run `$ npm uninstall gatsby-theme-blog && npm cache verify` restart the Gatsby dev server and done. 😄

Similar issue but the solution for me was to only run `npm cache verify`.
Thanks @killoblanco
