### ISSUE TITLE
Stop page component reload every time location.hash changes

### ISSUE THREAD

**Issue by lougroshek** [gatsbyjs/gatsby#26383]
# Summary

I've got a React component that modifies the location hash during usage. Test users notice that an echarts component flickers when used within the Gatsby site. It does not happen when the app is served locally in the development environment or when the app is [published independently on github pages](https://hyperobjekt.github.io/cpal-components/demo/dist/). Only when loaded in Gatsby, and in Gatsby, I can replicate when served locally and when published via Netlify. I've backtracked to discover that the entire Gatsby page component reloads every time window.location.hash changes, and I've confirmed that other pages in the repo also reload if I manually update the hash from the console (for example, `window.location.hash = '#/4/7/'`). Which seems to be backed up by some of what I [read here](https://www.gatsbyjs.org/docs/gatsby-link/). Why is this necessary for changes to the hash, as opposed to changes to location.pathname? On static sites, developers typically use hash routing within an app explicitly to avoid affecting the routing in the parent site. At any rate, **I** used hash routing explicitly to stay out of the way of Gatsby's routing. How can I stop this? 

## Relevant information

You can observe the flicker here by hovering over the bars: http://localhost:8000/explorer/#/feeder/cri_weight/1,1,1,1,1///1,0/32.76/-96.792/10/

It does not happen when the app is published in other contexts: https://hyperobjekt.github.io/cpal-components/demo/dist/#/feeder/cri_weight/1,1,1,1,1///1,0/32.76/-96.792/10/

App repo: https://github.com/Hyperobjekt/cpal-components

Gatsby site repo: https://github.com/Hyperobjekt/cpal-site

```
lougro@Lous-MacBook-Pro cpal-site % gatsby -v
Gatsby CLI version: 2.12.80
Gatsby version: 2.23.14
```

**Comment by freiksenet** [comment]
Do you experience same flicker if you change hash with `window.history.pushState`?

**Comment by amygroshek** [comment]
@freiksenet I can't use window.history.pushState. I am modifying the hash so that if a user copies and shares the browser path it will restore the app to its current state.

**Comment by amygroshek** [comment]
@freiksenet Thanks for the followup. If I change the hash using `window.history.pushState` the page component does not reload and the flickering issue does not occur.

**Comment by icazevedo** [comment]
I have the exact same problem as @amygroshek. I have the same behavior using Netlify or when I use a local Python HTTP server to serve the build.

**Comment by gemryan** [comment]
> @freiksenet Thanks for the followup. If I change the hash using `window.history.pushState` the page component does not reload and the flickering issue does not occur. I can implement that as a workaround, but it is not what I want, as the application state is now tied in to the browser history. Also, IMO it is not standard browser behavior to reload the page when the hash changes, and Gatsby shouldn't be doing it either. If I want to listen **within** a page or an app for the `hashChange` event and do something, that is a different matter, but it runs counter to expected behavior to automatically reload the page in that case.

Hey bro, Is there any progress on this issue?

**Comment by wangxiaohong418-spec** [comment]
scratch猫块
