### ISSUE TITLE
GraphQL "in" filter on array fields returns duplicates 

### ISSUE THREAD

**Issue by alisd23** [gatsbyjs/gatsby#26382]
## Description

I'm trying to filter records (blog articles in my case) by the `tags` field, which is an **array of strings**. I am looking to search for all articles which **contain** any tags from some array. Example query is below:

```gql
query MyQuery {
  allContentfulArticle(filter: {tags: {in: ["environment","food"]}}) {
    nodes {
      id
      title
      tags
    }
  }
}
```

This should return any articles with *either* the `environment` tag or `food` tag. This does work, but for some reason this is returning duplicates for me, but only for cases when the article contains **both the tags** in the search array, with the exact same ID (the actual response I get back is below):

```json
{
  "data": {
    "allContentfulArticle": {
      "nodes": [
        {
          "id": "89fd7eba-ccaf-5e43-aa4f-9455692f6940",
          "title": "Hello world",
          "tags": [
            "environment",
            "science"
          ]
        },
        {
          "id": "7985f52d-048e-5f5d-8b18-52cf02624bb9",
          "title": "Static sites are great",
          "tags": [
            "environment",
            "food"
          ]
        },
        {
          "id": "7985f52d-048e-5f5d-8b18-52cf02624bb9",
          "title": "Static sites are great",
          "tags": [
            "environment",
            "food"
          ]
        }
      ]
    }
  }
}
```

It's also worth noting that this is also the case for the `glob` operator (e.g. `environment|food`) or the regex operator.

### Steps to reproduce

This should be reproducible in the default [Contentful Starter](https://github.com/contentful-userland/gatsby-contentful-starter) example as I am still using mostly the same model and data from this example.

Then just try the query I listed above and make sure one of the blog posts has both of the tags in the tag search array.

### Expected result

No duplicate records should be returned

### Actual result

Duplicates are returned.

**Comment by pvdz** [comment]
Considering #26705, this is a generic `in` problem. I'll try to find time for it. I don't know how deep this rabbit hole goes.

**Comment by pvdz** [comment]
(committed a fix)
