### ISSUE TITLE
Error: Cannot find module 'gatsby-cli/lib/reporter' 

### ISSUE THREAD

**Issue by ErickRV19** [gatsbyjs/gatsby#26381]
## Summary
Hello, I just started and try to follow the tutorial on the page to use Gatsby’s default starter 

But I get a bug when I start with gatsby develop

## Relevant information
This is what I see in the terminal
`gatsby develop
Debugger listening on ws://127.0.0.1:9229/ab9cd164-7de3-4833-99aa-4d03dd32bf56
For help, see: https://nodejs.org/en/docs/inspector
success open and validate gatsby-configs - 0.077s

 ERROR 

Error in "/home/erick/w/my-default-starter/node_modules/gatsby-plugin-page-creator/gatsby-node.js": Cannot find module 'gatsby-cli/lib/reporter'
Require stack:
- /home/erick/w/my-default-starter/node_modules/gatsby-plugin-page-creator/is-valid-collection-path-implementation.js
- /home/erick/w/my-default-starter/node_modules/gatsby-plugin-page-creator/create-pages-from-collection-builder.js
- /home/erick/w/my-default-starter/node_modules/gatsby-plugin-page-creator/create-page-wrapper.js
- /home/erick/w/my-default-starter/node_modules/gatsby-plugin-page-creator/gatsby-node.js
- /home/erick/w/my-default-starter/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
- /home/erick/w/my-default-starter/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
- /home/erick/w/my-default-starter/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
- /home/erick/w/my-default-starter/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
- /home/erick/w/my-default-starter/node_modules/gatsby/dist/services/initialize.js
- /home/erick/w/my-default-starter/node_modules/gatsby/dist/services/index.js
- /home/erick/w/my-default-starter/node_modules/gatsby/dist/state-machines/develop/services.js
- /home/erick/w/my-default-starter/node_modules/gatsby/dist/state-machines/develop/index.js
- /home/erick/w/my-default-starter/node_modules/gatsby/dist/commands/develop-process.js
- /home/erick/w/my-default-starter/.cache/tmp-78667-QJU6K3EAkwW7

  Error: Cannot find module 'gatsby-cli/lib/reporter'
  Require stack:
  - /home/erick/w/my-default-starter/node_modules/gatsby-plugin-page-creator/is-valid-collection-path-implementation.js
  - /home/erick/w/my-default-starter/node_modules/gatsby-plugin-page-creator/create-pages-from-collection-builder.js
  - /home/erick/w/my-default-starter/node_modules/gatsby-plugin-page-creator/create-page-wrapper.js
  - /home/erick/w/my-default-starter/node_modules/gatsby-plugin-page-creator/gatsby-node.js
  - /home/erick/w/my-default-starter/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
  - /home/erick/w/my-default-starter/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
  - /home/erick/w/my-default-starter/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
  - /home/erick/w/my-default-starter/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
  - /home/erick/w/my-default-starter/node_modules/gatsby/dist/services/initialize.js
  - /home/erick/w/my-default-starter/node_modules/gatsby/dist/services/index.js
  - /home/erick/w/my-default-starter/node_modules/gatsby/dist/state-machines/develop/services.js
  - /home/erick/w/my-default-starter/node_modules/gatsby/dist/state-machines/develop/index.js
  - /home/erick/w/my-default-starter/node_modules/gatsby/dist/commands/develop-process.js
  - /home/erick/w/my-default-starter/.cache/tmp-78667-QJU6K3EAkwW7
  
  - loader.js:957 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:957:15
  - loader.js:840 Function.Module._load
    internal/modules/cjs/loader.js:840:27
  - loader.js:1019 Module.require
    internal/modules/cjs/loader.js:1019:19
  - v8-compile-cache.js:159 require
    [my-default-starter]/[v8-compile-cache]/v8-compile-cache.js:159:20
  - is-valid-collection-path-implementation.js:10 Object.<anonymous>
    [my-default-starter]/[gatsby-plugin-page-creator]/is-valid-collection-path-implementation.js:10:40
  - v8-compile-cache.js:178 Module._compile
    [my-default-starter]/[v8-compile-cache]/v8-compile-cache.js:178:30
  - loader.js:1153 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1153:10
  - loader.js:977 Module.load
    internal/modules/cjs/loader.js:977:32
  - loader.js:877 Function.Module._load
    internal/modules/cjs/loader.js:877:14
  - loader.js:1019 Module.require
    internal/modules/cjs/loader.js:1019:19
  - v8-compile-cache.js:159 require
    [my-default-starter]/[v8-compile-cache]/v8-compile-cache.js:159:20
  - create-pages-from-collection-builder.js:28 Object.<anonymous>
    [my-default-starter]/[gatsby-plugin-page-creator]/create-pages-from-collection-builder.js:28:44
  - v8-compile-cache.js:178 Module._compile
    [my-default-starter]/[v8-compile-cache]/v8-compile-cache.js:178:30
  - loader.js:1153 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1153:10
  - loader.js:977 Module.load
    internal/modules/cjs/loader.js:977:32
  - loader.js:877 Function.Module._load
    internal/modules/cjs/loader.js:877:14

    not finished load plugins - 1.535s

### Environment (if relevant)

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.24.41 => 2.24.41 
    gatsby-image: ^2.4.15 => 2.4.15 
    gatsby-plugin-manifest: ^2.4.22 => 2.4.22 
    gatsby-plugin-offline: ^3.2.23 => 3.2.23 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.26 => 2.6.26 
    gatsby-source-filesystem: ^2.3.24 => 2.3.24 
    gatsby-transformer-sharp: ^2.5.12 => 2.5.12 
  npmGlobalPackages:
    gatsby-cli: 2.12.83

**It was an incorrect installation or how can I fix it ?**

**Comment by KyleAMathews** [comment]
Hi can you upgrade to the latest versions of Gatsby? This bug was published yesterday and fixed early this morning so you should get things working again by upgrading https://github.com/gatsbyjs/gatsby/issues/26345#issuecomment-671885869

**Comment by ErickRV19** [comment]
Thanks, I'll check it.
