### ISSUE TITLE
YAML files are not seen in onCreateNode

### ISSUE THREAD

**Issue by varya** [gatsbyjs/gatsby#26391]
## Summary

I am trying to write my own transformer to get menu data from a YAML file. I follow this documentation https://www.gatsbyjs.org/docs/creating-a-transformer-plugin/

Using `gatsby-source-filesystem` I get the file as a node, and it can be seen with `allFile` graphQL query. However, this file does not show in `onCreateNode`. If I print what I have in `onCreateNode`, there will be only `.md` page files.

The documentation supposes that `onCreateNode` also runs on creating the node for YAML files.

I tried to make `gatsby clean` but it does not seem helping.

Is the documentation accurate?

### File contents (if changed)

My file contents are as in the linked documentaion example.

**Comment by freiksenet** [comment]
Could you include content of your `gatsby-config.js` file? It `source-filesystem` pointed to the directory where you have .yaml files?

**Comment by varya** [comment]
I don't exactly know what was the problem but when I started to prepare a repo with example, I could not reproduce it. Everything is working correctly. Sorry for the noise.
