### ISSUE TITLE
How CSS Files are bundled in GatsbyJS

### ISSUE THREAD

**Issue by Imran109** [gatsbyjs/gatsby#26398]
I wanted to play with all different types of styling methods in GatsbyJS. In my project, I have three types of implementing stylings,` global CSS, CSS Modules and CSS-in-JS(styled-components)`. Everything works as expected. But, when I build the project with gatsby build and open one of the index.html where I did `CSS-in-js` I see that there is a CSS file in `data-href` tag inside. When I open it, It contains all the CSS stylings of my project. But `I didn't even import` it to the component where I did CSS-in-js. Why would something like this happen? Why stylings from module.css are being referred inside this file? It's fine if its a global CSS. But whatever I did within `module.css` also comes along.
![image](https://user-images.githubusercontent.com/42968710/90003838-4b124780-dcb2-11ea-961a-eac23b1294b8.png)

**Comment by wardpeet** [comment]
Hi @Imran109 !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

I think I know where this bug is settled in our code but I'm not sure so a reproduction would be really helpful.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by Imran109** [comment]
sure!
Steps to reproduce, please follow the file tree structure I added here
![image](https://user-images.githubusercontent.com/42968710/90017474-37261000-dcc9-11ea-9143-d03ded77284b.png)


```
gatsby new tutorial-part-two https://github.com/gatsbyjs/gatsby-starter-hello-world
cd tutorial-part-two
```
**container.js**
```
import React from "react"
import styled from "styled-components"


const Section = styled.section`
  margin: 3rem auto;
  max-width: 600px;
`

export default function Container({ children }) {
  return <Section className={`Container`}>
      {children}
      </Section>
}
```

**about-css-module.js**

```
import React from "react"
import styles from "./about-css-modules.module.css"
import Container from "../components/container"

import { Link } from "gatsby"

const User = props => (
    <div className={styles.user}>
      <img src={props.avatar} className={styles.avatar} alt="" />
      <div className={styles.description}>
        <h2 className={styles.username}>{props.username}</h2>
        <p className={styles.excerpt}>{props.excerpt}</p>
      </div>
    </div>
  )
  // highlight-end
  
  export default function About() {
    return (
      <Container>
        <h1>About CSS Modules</h1>
        <p>CSS Modules are cool</p>
        {/* highlight-start */}
        <User
          username="Jane Doe"
          avatar="https://s3.amazonaws.com/uifaces/faces/twitter/adellecharles/128.jpg"
          excerpt="I'm Jane Doe. Lorem ipsum dolor sit amet, consectetur adipisicing elit."
        />
        <User
          username="Bob Smith"
          avatar="https://s3.amazonaws.com/uifaces/faces/twitter/vladarbatov/128.jpg"
          excerpt="I'm Bob Smith, a vertically aligned type of guy. Lorem ipsum dolor sit amet, consectetur adipisicing elit."
        />
        {/* highlight-end */}

    <Link to="/">Go to Home Page</Link> <br /><br></br>

      </Container>
    )
  }

```
**about-css-modules.module.css**

```
.user {
    display: flex;
    align-items: center;
    margin: 0 auto 12px auto;
  }
  
  .user:last-child {
    margin-bottom: 0;
  }
  
  .avatar {
    flex: 0 0 96px;
    width: 96px;
    height: 96px;
    margin: 0;
  }
  
  .description {
    flex: 1;
    margin-left: 18px;
    padding: 12px;
  }
  
  .username {
    margin: 0 0 12px 0;
    padding: 0;
  }
  
  .excerpt {
    margin: 0;
  }
```

**css-in-js**

i```
mport React from "react"
import styled from "styled-components"
import { Link } from "gatsby"

const Container = styled.div`
  margin: 12rem  auto;
  max-width: 600px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`

const UserWrapper = styled.div`
  display: flex;
  align-items: center;
  margin: 12px 12px auto;
  &:last-child {
    margin-bottom: 0;
  }
`

const Avatar = styled.img`
  flex: 0 0 96px;
  width: 96px;
  height: 96px;
  margin: 0;
`

const Description = styled.div`
  flex: 1;
  margin-left: 18px;
  padding: 12px;
`

const Username = styled.h2`
  margin: 0 0 12px 0;
  padding: 0;
`

const Excerpt = styled.p`
  margin: 0;
`

const User = props => (
  <UserWrapper>
    <Avatar src={props.avatar} alt="" />
    <Description>
      <Username>{props.username}</Username>
      <Excerpt>{props.excerpt}</Excerpt>
    </Description>
  </UserWrapper>
)

export default function UsersList() {
  return (
    <Container>
      <h1>About Styled Components</h1>
      <p>Styled Components is cool</p>
      <User
        username="Jane Doe"
        avatar="https://s3.amazonaws.com/uifaces/faces/twitter/adellecharles/128.jpg"
        excerpt="I'm Jane Doe. Lorem ipsum dolor sit amet, consectetur adipisicing elit."
      />
      <User
        username="Bob Smith"
        avatar="https://s3.amazonaws.com/uifaces/faces/twitter/vladarbatov/128.jpg"
        excerpt="I'm Bob smith, a vertically aligned type of guy. Lorem ipsum dolor sit amet, consectetur adipisicing elit."
      />
    <Link to="/">Go to Home Page</Link> <br /><br></br>
    </Container>
  )
}
```

**index.js**

```
import React from "react"
import { Link } from "gatsby"

export default function Home() {
  return <div>
    <h1>Welcome to the Global CSS Home Page</h1>
    <Link to="/second-page">Go to page 2</Link><br /><br></br>
    <Link to="/about-css-module">Go to CSS Module</Link> <br /><br></br>
    <Link to="/css-in-js">Go to CSS-in-JS using Styled components</Link> <br /><br></br>
    <Link to="/css-in-js-ii">Go to CSS-in-JS II</Link> <br /><br></br>
  </div>
}
```

**global.css**

```
html {
    background-color: blueviolet;
  }

  .container{
    background : yellow;
  }
```
`gatsby develop`
`gatsby build`
