### ISSUE TITLE
GATSBY develop not working 

### ISSUE THREAD

**Issue by na-win-27** [gatsbyjs/gatsby#26401]
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\navin\gatsby> npm install -g gatsby-cli
npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
C:\Users\navin\AppData\Roaming\npm\gatsby -> C:\Users\navin\AppData\Roaming\npm\node_modules\gatsby-cli\cli.js

> core-js@2.6.11 postinstall C:\Users\navin\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> gatsby-telemetry@1.3.27 postinstall C:\Users\navin\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\gatsby-telemetry 
> node src/postinstall.js || true

> gatsby-cli@2.12.84 postinstall C:\Users\navin\AppData\Roaming\npm\node_modules\gatsby-cli
> node scripts/postinstall.js

╔════════════════════════════════════════════════════════════════════════╗
║                                                                        ║
║   Gatsby collects anonymous usage analytics                            ║
║   to help improve Gatsby for all users.                                ║
║                                                                        ║
║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
║   To learn more, checkout https://gatsby.dev/telemetry                 ║
║                                                                        ║
╚════════════════════════════════════════════════════════════════════════╝
Success!

Welcome to the Gatsby CLI! Please visit https://www.gatsbyjs.org/docs/gatsby-cli/ for more information.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\gatsby-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN gatsby-interface@0.0.166 requires a peer of gatsby@2.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react-dom@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/popover@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/tooltip@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/combobox@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies 
yourself.
npm WARN @reach/tabs@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/alert@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/dialog@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN theme-ui@0.2.52 requires a peer of @mdx-js/react@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/menu-button@0.10.3 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/visually-hidden@0.10.4 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/utils@0.10.5 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/descendants@0.10.5 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencinpm WARN @reach/auto-id@0.10.5 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/portal@0.10.5 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/rect@0.10.5 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.

+ gatsby-cli@2.12.84
added 862 packages from 621 contributors in 593.561s
PS C:\Users\navin\gatsby> gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-starter-hello-world
info Creating new site from git: https://github.com/gatsbyjs/gatsby-starter-hello-world.git
Cloning into 'gatsby-site'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 16 (delta 0), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), 384.47 KiB | 162.00 KiB/s, done.
success Created starter directory layout
info Installing packages...

> core-js@2.6.11 postinstall C:\Users\navin\gatsby\gatsby-site\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@3.6.5 postinstall C:\Users\navin\gatsby\gatsby-site\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js-pure@3.6.5 postinstall C:\Users\navin\gatsby\gatsby-site\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

> gatsby-telemetry@1.3.26 postinstall C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby-telemetry
> node src/postinstall.js || true

> gatsby-cli@2.12.82 postinstall C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\node_modules\gatsby-cli
> node scripts/postinstall.js

> gatsby@2.24.41 postinstall C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby
> node scripts/postinstall.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1968 packages from 1026 contributors in 85.622s

  run `npm fund` for details

info
Your new Gatsby site has been successfully bootstrapped. Start developing it by running:

  cd gatsby-site
  gatsby develop

PS C:\Users\navin\gatsby> cd gatsby-site
>>   gatsby develop
Debugger listening on ws://127.0.0.1:9229/71723700-08ae-4773-9921-a9d64523c927
For help, see: https://nodejs.org/en/docs/inspector
success open and validate gatsby-configs - 0.018s

 ERROR 

Error in "C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby-plugin-page-creator\gatsby-node.js": Cannot find module 'gatsby-cli/lib/reporter'
Require stack:
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby-plugin-page-creator\is-valid-collection-path-implementation.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby-plugin-page-creator\create-pages-from-collection-builder.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby-plugin-page-creator\create-page-wrapper.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby-plugin-page-creator\gatsby-node.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\bootstrap\resolve-module-exports.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\services\initialize.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\services\index.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\state-machines\develop\services.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\state-machines\develop\index.js
- C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\commands\develop-process.js
- C:\Users\navin\gatsby\gatsby-site\.cache\tmp-7032-2v22fCYTnlAo

  Error: Cannot find module 'gatsby-cli/lib/reporter'
  Require stack:
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby-plugin-page-creator\is-valid-collection-path-implementation.js       
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby-plugin-page-creator\create-pages-from-collection-builder.js
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby-plugin-page-creator\create-page-wrapper.js
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby-plugin-page-creator\gatsby-node.js
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\bootstrap\resolve-module-exports.js
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\services\initialize.js
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\services\index.js
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\state-machines\develop\services.js
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\state-machines\develop\index.js
  - C:\Users\navin\gatsby\gatsby-site\node_modules\gatsby\dist\commands\develop-process.js
  - C:\Users\navin\gatsby\gatsby-site\.cache\tmp-7032-2v22fCYTnlAo

  - loader.js:1085 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:1085:15

  - loader.js:928 Function.Module._load
    internal/modules/cjs/loader.js:928:27

  - loader.js:1145 Module.require
    internal/modules/cjs/loader.js:1145:19

  - v8-compile-cache.js:159 require
    [gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - is-valid-collection-path-implementation.js:10 Object.<anonymous>
    [gatsby-site]/[gatsby-plugin-page-creator]/is-valid-collection-path-implementation.js:10:40

  - v8-compile-cache.js:178 Module._compile
    [gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader.js:1277 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1277:10

  - loader.js:1105 Module.load
    internal/modules/cjs/loader.js:1105:32

  - loader.js:967 Function.Module._load
    internal/modules/cjs/loader.js:967:14

  - loader.js:1145 Module.require
    internal/modules/cjs/loader.js:1145:19

  - v8-compile-cache.js:159 require
    [gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - create-pages-from-collection-builder.js:28 Object.<anonymous>
    [gatsby-site]/[gatsby-plugin-page-creator]/create-pages-from-collection-builder.js:28:44

  - v8-compile-cache.js:178 Module._compile
    [gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader.js:1277 Object.Module._extensions..js

  - loader.js:1105 Module.load
    internal/modules/cjs/loader.js:1105:32

  - loader.js:967 Function.Module._load
    internal/modules/cjs/loader.js:967:14

not finished load plugins - 0.238s
PS C:\Users\navin\gatsby\gatsby-site> gatsby devlop

 ERROR

**Comment by nakamura0907** [comment]
```
npm i -S gatsby@2.24.42
```
  The error no longer occurs.

**Comment by freiksenet** [comment]
Sorry about that! Issue should be resolvef if you upgrade Gatsby.
