### ISSUE TITLE
Add `deprecation` notice to Spectrum Chat 

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#26407]
## Summary

add a small note about discontinuing official support at https://spectrum.chat/gatsby-js

### Basic example

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation

guide user where to find answers

## Related Issues

- #26276 `Remove Spectrum from issue templates`   
- #26351 `Remove Spectrum Community Reference From Documentation`

**Comment by LekoArts** [comment]
The message was added :)
