### ISSUE TITLE
404 on gatsbyjs.com - add redirect from /packages/* to /plugins/* 

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#26417]
## Description

with the transition from gatsbyjs.org to gatsbyjs.com the path for the plugins is changed from `/packages/*` to `/plugins/*`, but this redirect is missing on gatsbyjs.com

### Steps to reproduce

- open: https://www.gatsbyjs.com/tutorial/ecommerce-tutorial/
- click on: "Stripe source plugin" https://www.gatsbyjs.com/packages/gatsby-source-stripe/

### Expected result

- page should be visible

### Actual result

- 404

### Environment

- online at: gatsbyjs.com 

### 

Note: from the org the redirect is working: https://www.gatsbyjs.org/packages/gatsby-source-stripe/

**Comment by LekoArts** [comment]
This was fixed :)
