### ISSUE TITLE
New Site Text Content: Explore the Gatsby Ecosystem

### ISSUE THREAD

**Issue by calebsylvest** [gatsbyjs/gatsby#26414]
## Description

Incorrect description text rendering on new Gatsby homepage.

### Steps to reproduce

1. Visit https://www.gatsbyjs.com/ homepage
1. Scroll down to the **Explore the Gatsby Ecosystem** section
1. Toggle the **Plugins**, **Themes**, and **Recipes** tabs
1. Read the text

### Expected result

Each  **Plugins**, **Themes**, and **Recipes** tab should have unique description text describing each Ecosystem feature.

I don't know exactly where the text content data is coming from, but you can see the [homepage-ecosystem.js component here](https://github.com/gatsbyjs/gatsby/blob/3c194389ada8373ad014e9ba922098f9b6040866/www/src/components/homepage/homepage-ecosystem.js#L161)

### Actual result

All three  **Plugins**, **Themes**, and **Recipes** tabs repeat the same descriptive text.

![Gatsby_Cloud](https://user-images.githubusercontent.com/4457883/90049234-24481700-dc9a-11ea-83b9-f0b805a68f55.png)

### Environment

Production website

**Comment by vladar** [comment]
Are you still seeing it? I opened the website and the text is different for me. Probably was already fixed?

**Comment by calebsylvest** [comment]
This is corrected. Looks like new updates went out for the site. Closing.
