### ISSUE TITLE
siteData in layout

### ISSUE THREAD

**Issue by konsumer** [gatsbyjs/gatsby#2642]
I'd like to get the prop `site` in my layout (so I can pull the `siteMetadata.title` into the main header), but it doesn't seem to come in on the props.

I read [here](https://www.gatsbyjs.org/docs/bound-action-creators/#createPage) I can do that by adding it to `context` of `createPage`, so this is what I did:

`gatsy-node.js`
```js
const _ = require('lodash')
const Promise = require('bluebird')
const path = require('path')
const select = require(`unist-util-select`)
const fs = require(`fs-extra`)

exports.createPages = ({ graphql, boundActionCreators }) => {
  const { createPage } = boundActionCreators

  return new Promise((resolve, reject) => {
    const templateLocation = path.resolve('./src/templates/gallery.js')
    resolve(
      graphql(
        `
      {
        site {
          siteMetadata {
            title
            author
          }
        }
        allMarkdownRemark(limit: 1000) {
          edges {
            node {
              frontmatter {
                path
              }
            }
          }
        }
      }
    `
      ).then(result => {
        if (result.errors) {
          console.log(result.errors)
          reject(result.errors)
        }

        // Create posts pages.
        _.each(result.data.allMarkdownRemark.edges, edge => {
          createPage({
            path: edge.node.frontmatter.path,
            component: templateLocation,
            context: {
              path: edge.node.frontmatter.path,
              site: result.data.site
            }
          })
        })
      })
    )
  })
}
```

But looking at the props of the component in `layouts/index.js` I don't see `site`. I am thinking maybe I am just modifying the inner template's props. Is there a way to get `site` in the layout?

**Comment by emmafallancy** [comment]
Hi @konsumer, you would get the `context.site` value through the props within the `pathContext` property in the component props of `gallery` template that you specified (e.g. `this.props.pathContext.site`). You can get the `siteMetada` in your layout when you make a query by exporting the query in `layouts/index.js`.

```js
// E.g. Make query to access the siteMetadata in layouts/index.js
export const pageQuery = graphql`
  query LayoutIndexQuery {
    site {
      siteMetadata {
        author
        title
      }
    }
  }
`
```

I hope this would be able to answer your question :)

**Comment by konsumer** [comment]
Thanks @emmafallancy! I should have realized I can put a `pageQuery` on the layout, too. Awesome!
