### ISSUE TITLE
Remove "How to Label an Issue" doc since community contributors cannot add labels to issues

### ISSUE THREAD

**Issue by taylorcjohnson** [gatsbyjs/gatsby#26428]
## Summary

What problem(s) did you run into that caused you to request additional documentation? What questions do you think we should answer? What, if any, existing documentation relates to this proposal?

As of August 12, 2020 Gatsby community contributors no longer belong to the Gatsby organization. The [_How to Label an Issue_](https://www.gatsbyjs.com/contributing/how-to-label-an-issue/) doc describes how contributors can label issues - this is not longer needed since community contributors do not have that capability. 

A new doc could replace it that describes the possible issues a community contributor might encounter while reviewing issues, but this already exists in the [repo](https://github.com/gatsbyjs/gatsby/issues/labels).

### Motivation

Why should we document this and who will benefit from it?

Community contributors (who I believe are the target audience for the contributing section of Gatsby docs) might be confused reading a section in the docs that describes how to do something that they can no longer do (add labels to issues).

## Steps to resolve this issue

_If_ I am interpreting these recent changes to the status community contributors correctly, and we can no longer label issues, I can remove the _How to Label an Issue_ doc.

### Draft the doc

Not applicable - this is an update to an existing doc.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by raythurman2386** [comment]
@taylorcjohnson Could I tackle this issue or have you already completed this?

**Comment by taylorcjohnson** [comment]
@raythurman2386 I have not done this work - I was waiting clarification from a documentation team member. However, feel free to work on it - a pull request would probably result in more eyes on the issue!
