### ISSUE TITLE
Duplicate scrollbars on docs page

### ISSUE THREAD

**Issue by SimonSiefke** [gatsbyjs/gatsby#26435]
## Description

There are two scrollbars on https://www.gatsbyjs.com/docs/visual-testing-with-storybook/

![Screenshot from 2020-08-13 09-28-05](https://user-images.githubusercontent.com/23744935/90106644-0638f000-dd48-11ea-80c1-6312981bd51f.png)

### Steps to reproduce

Go to https://www.gatsbyjs.com/docs/visual-testing-with-storybook/

### Expected result

Only one scrollbar

### Actual result

Two scrollbars

**Comment by capndave** [comment]
It looks like this is the case for everything in [the docs](https://www.gatsbyjs.com/docs/). It's possible to hide/disappear the outer bar but am not sure if that would cause other issues. I'm happy to fool with it but could use some input @ whether Gatsby team would/wouldn't want that.

**Comment by awardnasc** [comment]
Taking a look at this really quick it seems to be stemming from the notification at the top. If you change the `dispaly: flex` on it to `display: none` it removes the second scroll bar. I would guess that when adding that notification, the height of the full window wasn't reconsidered for the other elements.

**Comment by capndave** [comment]
Just pulled this from gatsby master and the right inner scroll bar is gone. Maybe someone fixed but the source code hasn't been deployed yet? Not sure why it's this way on my local and still has two scrollbars on the web.

**Comment by LekoArts** [comment]
Thanks for the issue! Since the code for the website is currently not open source the `www` part of the monorepo is outdated and doesn't get deployed to gatsbyjs.com. I fixed the underlying bug and the scrollbars should be removed with the next deploy :)

**Comment by capndave** [comment]
Great! Regarding `www` and it not being open-source: what's the future plan
for that?

**Comment by LekoArts** [comment]
Eventually we'd like to make it open-source again (here in this repository) but can't give an ETA on this for now.
