### ISSUE TITLE
Fix dead links on docs on reference guides

### ISSUE THREAD

**Issue by heytulsiprasad** [gatsbyjs/gatsby#26447]
# Issue

The reference guide on, [Programmatically create pages from Data](https://www.gatsbyjs.com/docs/programmatically-create-pages-from-data) contains a dead (404) link in its markdown.

# Details

On page  [Programmatically create pages from Data](https://www.gatsbyjs.com/docs/programmatically-create-pages-from-data) and section  [Not just Markdown](https://www.gatsbyjs.com/docs/programmatically-create-pages-from-data/#not-just-markdown) as shown in the screenshot below.

![https://i.imgur.com/wFVu30A.png](https://i.imgur.com/wFVu30A.png)

On clicking the highlighted link it forwards to a 404 page, as shown below.

![https://i.imgur.com/mSWXiJm.png](https://i.imgur.com/mSWXiJm.png)

# Fix

As the above link redirects to *https://www.gatsbyjs.com/packages/gatsby-transformer-remark/* which doesn't exists, it should be redirecting to *https://www.gatsbyjs.com/plugins/gatsby-transformer-remark/* instead, which hopefully is the referred page here. 

I would be glad to fix this one by opening a PR. Thanks! 👍

**Comment by LekoArts** [comment]
Thanks for the issue! The redirects issue was solved in the meantime and the link works again.
