### ISSUE TITLE
Console errors should have a background color

### ISSUE THREAD

**Issue by benjaminhoffman** [gatsbyjs/gatsby#2645]
The error `window is not defined` renders white text.  If this error is read in a browser or terminal with a white brackground, the text is essentially hidden.  See attached.  May want to include a darker bg color so this text stands out.  [
![screen shot 2017-10-26 at 12 11 56 pm](https://user-images.githubusercontent.com/6520022/32074223-95645826-ba4d-11e7-8f3b-1172b334bd76.png)
](url)

**Comment by benjaminhoffman** [comment]
another example.  

![screen shot 2017-11-02 at 1 14 14 pm](https://user-images.githubusercontent.com/6520022/32348015-c3f4219e-bfcf-11e7-98ac-8a84d7f6f884.png)

**Comment by r1b** [comment]
Perhaps the entire background should be red like the background of the error prototype. I would be happy to fix this.

**Comment by imjared** [comment]
@r1b did you take a pass at this?

**Comment by r1b** [comment]
@imjared no i'm sorry :( - life has gotten in the way

**Comment by alexparish** [comment]
Mind if I have a look at this?

**Comment by faburu** [comment]
I have grey copy on a red background which is difficult to read. Could you tell if and where I could change this?

![image](https://user-images.githubusercontent.com/29293242/41503997-bc53a210-71af-11e8-8c2d-ac212a22a93c.png)
