### ISSUE TITLE
Gatsby Build fails on CI (Bitbucket Pipelines)

### ISSUE THREAD

**Issue by artemtam** [gatsbyjs/gatsby#26454]
## Description

We try to use Bitbucket Pipelines to build Gatsby.js websites. Time to time (not always) the build fails. The most often error is a segmentation fault:
```
success open and validate gatsby-configs - 0.040s
/bin/sh: lscpu: not found
success load plugins - 1.755s
success onPreInit - 0.061s
success delete html and css files from previous builds - 0.004s
success initialize cache - 0.009s
success copy gatsby files - 0.060s
success onPreBootstrap - 0.022s
/bin/sh: lscpu: not found
success createSchemaCustomization - 0.016s
success Checking for changed pages - 0.000s
success source and transform nodes - 0.494s
success building schema - 0.439s
success createPages - 0.004s
success Checking for changed pages - 0.000s
success createPagesStatefully - 0.156s
success update schema - 0.241s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.700s
success write out redirect data - 0.005s
success onPostBootstrap - 0.000s
info bootstrap finished - 8.668s
Segmentation fault (core dumped)
```

Sometimes we get a different error:
```
success Rewriting compilation hashes - 0.002s
error Generating SSR bundle failed
Can't resolve '../../../../../public/page-data/sq/d/440663142.json' in '/opt/atlassian/pipelines/agent/build/src/components/Features/FeaturesHeader/ParallaxContainer'
If you're trying to use a package make sure that '../../../../../public/page-data/sq/d/440663142.json' is installed. If you're trying to use a local file make sure that the path is correct.
error Generating SSR bundle failed
...
not finished Building static HTML for pages - 3.411s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website@0.1.0 build: `gatsby build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the website@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-12T07_39_38_453Z-debug.log
```
Here is the pipeline script we use:
```yaml
definitions:
  steps:
    - step: &build
        name: Build
        image: node:14-alpine
        script:
          - npm ci --no-audit --progress=false --unsafe-perm
          - npm run build
        artifacts:
          - public/**

pipelines:
  default:
    - step: *build
```

Increasing build machine capacity with `size: 2x` helps a bit – failed builds appear less often. 

### Steps to reproduce

To reproduce take a middle-size Gatsby.js project and try to build it inside Bitbucket with the pipeline script described above. It is pretty hard to prepare the exact example for you, though I believe every Gatsby.js website will experience the same problems with pipelines.

### Expected result

Build should always be successful.

### Actual result

Build sometimes fails.

### Environment

The environment is `node14-alpine` docker container inside a Bitbucket pipeline.

**Comment by pieh** [comment]
Can you try setting `GATSBY_CPU_COUNT` environment variable to match the logical core count? (So something like `GATSBY_CPU_COUNT=4`). I can't really find any reference to actual resources being provided for 1x and 2x (other than that memory limit goes from 4GB to 8GB), so I don't even know what those values should be. We saw some of those issues when running builds in CircleCI where automatic core count detection is not working properly (because we get information about physical cores and not just about logical cores made available to container), so it very often tries to spawn to many subprocesses which are then terminated by CircleCI (probably as measure trying to shield it from excessive resource usage that might be malicious?)

**Comment by artemtam** [comment]
I tried this as I found it in similar issues. Doesn't help, still happening from time to time. 

I also noticed that cache probably affects the build. If I do `rm -rf ./.cache` it seems it happens less often, though I am not sure. 

Is it possible to get the full trace where the segmentation fault is happening?

**Comment by pieh** [comment]
For seg faults - not sure if that would work but you can try adding [`segfault-handler`](https://github.com/ddopson/node-segfault-handler) package to your (dev)deps, create new file (let's call it `segfault-debug.js`) in project directory with following content:

```
var SegfaultHandler = require('segfault-handler');

SegfaultHandler.registerHandler("crash.log");
```

and adjust build script (in package.json) to be `NODE_OPTIONS=--require=./segfault-debug.js gatsby build` (which should auto-apply that custom script to every node process that gatsby creates).

**Comment by pojntfx** [comment]
Just tried this, fails with the following:

```bash
# NODE_OPTIONS=--require=./segfault-debug.js gatsby develop

Something is already running at port 8000
✔ Would you like to run the app at another port instead? … yes
success open and validate gatsby-configs - 0.055s
success load plugins - 0.520s
success onPreInit - 0.037s
success initialize cache - 0.013s
success copy gatsby files - 0.018s
success onPreBootstrap - 0.009s
success createSchemaCustomization - 0.009s
success Checking for changed pages - 0.003s
success source and transform nodes - 0.084s
success building schema - 0.353s
success createPages - 0.002s
success Checking for changed pages - 0.002s
success createPagesStatefully - 0.074s
success update schema - 0.032s
success write out redirect data - 0.002s
⠋ onPostBootstrap
⠋ Build manifest and related icons
PID 31641 received SIGSEGV for address: 0x0
PID 31620 received SIGSEGV for address: 0x7b84
Segmentation fault
```

**Comment by artemtam** [comment]
I have similar issues with `segfault-handler`. Can't run it inside the alpine container.

**Comment by Niemi** [comment]
@artemtam  we tried both node:14-alpine and node:15-alpine :)
But work with "lscpu" utility
` # apk search lscpu
util-linux-2.34-r1
/ # apk add util-linux
`

**Comment by 088haizi** [comment]
> I have similar issues with `segfault-handler`. Can't run it inside the alpine container.

@artemtam Did you work this out in the end? I just got the same issue in my project, thanks for any further clue.
