### ISSUE TITLE
Unified gatsby: sidebar content is not updated, redirects are not applied, old content still cached

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#26460]
## Description

Sidebar updates from the PR #25503 are not synced

There is a missing sync between .org/docs and .com/docs
- sidebar is not updated (`www/src/data/sidebars/doc-links.yaml`)
- redirects are not updated (`www/redirects.yaml`)

#### Page Schema Root Fields

- open https://www.gatsbyjs.com/docs/schema-root-fields/
- see screenshot:
<img width="1001" alt="Bildschirmfoto 2020-08-14 um 16 37 23" src="https://user-images.githubusercontent.com/184316/90261351-1d153a80-de4d-11ea-93ef-7cc219afee82.png">

checked also via: `curl https://www.gatsbyjs.com/docs/schema-root-fields/ > test.html`
and searched for `gql`

#### deleted Page Schema Connections

- open deleted page: https://www.gatsbyjs.com/docs/schema-connections
- missing here the redirect
- you see short a 404:
  - but then after rehydration the old site
  - even force refresh not update the cache and show old content

### Expected result

Sidebar schould be updated
Redirects should be updated

### Actual result

Sidebar is not updated
Redirects are not updated

### Environment

on gatsbyjs.com

## Related Issues

- #25503 `feat(docs): Better docs for big chunk of schema stuff`

**Comment by gillkyle** [comment]
Thanks for raising this @muescha! Just updated the sidebar and redirects to address this.

**Comment by muescha** [comment]
### Related PR

looking at PR: 
- #26106 `Add refresh content docs` 

### Problem

again - `doc-links.yaml` is not updated:

<img width="1109" alt="Bildschirmfoto 2020-08-18 um 21 35 55" src="https://user-images.githubusercontent.com/184316/90557528-e9167e00-e19a-11ea-94a2-523c31e5930f.png">

missing:

- right breadcrump on top
- missing link in sidebar

**Comment by muescha** [comment]
how i can reopen an issue? 🤔

**Comment by muescha** [comment]
i created a new Issue:

- #26538 `Unified gatsby: sidebar content is not updated, breadcrumbs are not updated`
