### ISSUE TITLE
Images generated by 'gatsby-remark-images' with 'withWebp' option fail to show when 'pathPrefix' is set

### ISSUE THREAD

**Issue by frncesc** [gatsbyjs/gatsby#26471]
## Description

In a Gatsby site with the `pathPrefix` option set, fluid images generated by `gatsby-remark-images` with WebP don't show (or show only the blur layer) in Chrome and Firefox.

For a live example of this issue, see this [test page](https://gatsby-template.saltamarges.org/web/en/mendeleev/).

If you take a look at the generated HTML code you will see that `picture` elements have two `source` children: one for images in WebP format and the other one for images in the original format (PNG or JPG). Note that __the paths in webP images do not include the pathPrefix__, which is not the case of images on the original format.

### Steps to reproduce

- Create a Gatsby site with [pathPrefix](https://www.gatsbyjs.com/docs/path-prefix/)
- Use [gatsby-remark-images](https://www.gatsbyjs.com/plugins/gatsby-remark-images/) enabling `withWebp`
- Place some JPG and/or PNG images on the markdown pages
- The development site (where `pathPrefix` is [not used](https://github.com/gatsbyjs/gatsby/issues/16040)) will work as expected: the browser quickly downloads and displays the WebP images over the blur layer.  
- Build the site
- When serving the production built site (now with `pathPrefix`), the image does not show. 

#### Demo project:
https://github.com/frncesc/gatsby-webp-bug (see eggs picture in 'Hello world')
It's just a fork of [Gatsby starter blog](https://www.gatsbyjs.com/starters/gatsbyjs/gatsby-starter-blog) with `pathPrefix` set to `/blog` and `withWebp` set to `true` in `gatsby-remark-images`.

#### Another demo project already deployed in Netlify:
https://github.com/frncesc/gatsby-multilang-material-blog (see [this page](https://gatsby-template.saltamarges.org/web/en/mendeleev/))
Deployed in: https://gatsby-template.saltamarges.org/web/

### Expected result

WebP images should be displayed, also when using `pathPrefix`.

### Actual result

Images not showing because `pathPrefix` is ignored in WebP pictures   

I will post a PR to `gatsby-remark-images` with an easy solution to this issue

### Environment

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.8.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.7 - ~/.npm-global/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47
    gatsby-image: ^2.4.16 => 2.4.16
    gatsby-plugin-feed: ^2.5.11 => 2.5.11
    gatsby-plugin-google-analytics: ^2.3.13 => 2.3.13
    gatsby-plugin-manifest: ^2.4.23 => 2.4.23
    gatsby-plugin-offline: ^3.2.23 => 3.2.23
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-sharp: ^2.6.27 => 2.6.27
    gatsby-plugin-typography: ^2.5.10 => 2.5.10
    gatsby-remark-copy-linked-files: ^2.3.12 => 2.3.12
    gatsby-remark-images: ^3.3.25 => 3.3.25
    gatsby-remark-prismjs: ^3.5.10 => 3.5.10
    gatsby-remark-responsive-iframe: ^2.4.12 => 2.4.12
    gatsby-remark-smartypants: ^2.3.10 => 2.3.10
    gatsby-source-filesystem: ^2.3.24 => 2.3.24
    gatsby-transformer-remark: ^2.8.28 => 2.8.28
    gatsby-transformer-sharp: ^2.5.13 => 2.5.13
  npmGlobalPackages:
    gatsby-cli: 2.12.87
```

**Comment by wardpeet** [comment]
Thank you for opening the issue and fixing it at the same time! 💪
