### ISSUE TITLE
Typography breaks when used in a workspace theme

### ISSUE THREAD

**Issue by joshuacox** [gatsbyjs/gatsby#26473]
## Description

Typography does not work inside of theme npm package.

### Steps to reproduce

gist:
https://gist.github.com/joshuacox/05559ca673a9b8841594f0936195850d

Also, I have a katacoda scenario for duplicating this issue:
https://www.katacoda.com/thoth/scenarios/tryoutgatsbyjs-typography

### Expected result

Typography should work just like it does in the example site.

### Actual result

```
 ERROR #98124  WEBPACK

Generating SSR bundle failed

Can't resolve '/tmp/my-theme/example/src/utils/typography' in '/tmp/my-theme/example/.cache/caches/gatsby-plugin-typography'

If you're trying to use a package make sure that '/tmp/my-theme/example/src/utils/typography' is installed. If you're trying to use a local file make sure that the path is correct.
```

### Environment

```
  System:
    OS: Linux 5.8 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.16.3/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 3.8.5 - /usr/bin/python
  Browsers:
    Firefox: 79.0
  npmGlobalPackages:
    gatsby-cli: 2.12.87
```

**Comment by joshuacox** [comment]
I can fix the 'example' site by adding that typography file, but I want it to 'inherit' this file by default.

```shell
mkdir -p example/src/utils     
cp gatsby-theme-minimal/src/utils/typography.js example/src/utils 
```

**Comment by vladar** [comment]
Hey @joshuacox 

Sorry for the delay with a response. `gatsby-plugin-typography` is not theme-aware. It doesn't support shadowing out of the box.

But it accepts an absolute path in `pathToConfigModule`:

https://github.com/gatsbyjs/gatsby/blob/ac72bfb7d1ff2c06ef6652f12c1e861fd7cc21f3/packages/gatsby-plugin-typography/src/gatsby-node.js#L13-L15

So you should be able to control which file should be actually loaded in your theme config. For example, you could do something like this in `gatsby-config.js`:

```js
const path = require(`path`);

module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: path.resolve(
          path.join(__dirname, `src/utils/typography`)
        ),
      },
    },
  ],
};
```

**Comment by LekoArts** [comment]
Closing this one as stale.
