### ISSUE TITLE
Code Sandbox examples aren't loading for GraphQL examples

### ISSUE THREAD

**Issue by webdevpchoi** [gatsbyjs/gatsby#26478]
This page: https://www.gatsbyjs.com/docs/graphql-reference/#basic-query isn't loading the code examples on any browser. Windows 10 operating system.

**Comment by LekoArts** [comment]
Thanks for the issue! There are sometimes intermittent issues with codesandbox and they normally resolve themselves. When you visit the site now you'll see it working :)
