### ISSUE TITLE
Feature Request: github bot should handle adding a label "not stale"

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#26489]
## Summary

Since the member permissions to add/remove labels are restricted the GatsbyBot now mark Issues as stale, but as a user i can not add now "not stale" 

### Changes:

- ~add a action, when new comments incoming, removing the "stale" label~ *it is done with a delay*
- if a user writes "not stale", add the label "not stale"
- update the GatsbyBot info text and remove "You can also add the label "not stale" to keep this issue open!"

### Motivation

he member permissions to add/remove labels are restricted now

**Comment by muescha** [comment]
updated tile: Gatsby-Bot removes the stale label with a delay

**Comment by pieh** [comment]
> updated tile: Gatsby-Bot removes the stale label with a delay

Just to add more context to this - Stale bot runs twice a day ( https://github.com/gatsbyjs/gatsby/blob/318a8a2abb1518b7b011158a25939f9dc9990ba3/.github/workflows/schedule-stale.yml#L1-L3 ) and not in reaction to each individual comment. So delay with removing label at most should be 12h
