### ISSUE TITLE
gatsby recipes storybook-ts not working

### ISSUE THREAD

**Issue by mrseanbaines** [gatsbyjs/gatsby#26480]
## Description
The `storybook-ts` Gatsby recipe doesn't seem to be working. I am getting an error and a neverending installation phase.

It also seems to be messing up when writing to `package.json` (see image)

<img width="1440" alt="Screenshot 2020-08-15 at 17 58 04" src="https://user-images.githubusercontent.com/24367010/90317927-9af84500-df24-11ea-9587-a768b1007497.png">

<img width="1440" alt="Screenshot 2020-08-15 at 17 58 00" src="https://user-images.githubusercontent.com/24367010/90317924-96339100-df24-11ea-93ff-62d71fb5d38f.png">

<img width="198" alt="image" src="https://user-images.githubusercontent.com/24367010/90318017-5325ed80-df25-11ea-948b-8252008d925b.png">

### Steps to reproduce

```sh
npx gatsby new gatsby-storybook-test
cd gatsby-storybook-test
npx gatsby recipes storybook-ts --install
```

### Expected result

No error. The recipe installs and configures correctly

### Actual result

Error and neverending installation

### Environment

```sh

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.41 => 2.24.41 
    gatsby-image: ^2.4.15 => 2.4.15 
    gatsby-plugin-manifest: ^2.4.22 => 2.4.22 
    gatsby-plugin-offline: ^3.2.23 => 3.2.23 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.26 => 2.6.26 
    gatsby-source-filesystem: ^2.3.24 => 2.3.24 
    gatsby-transformer-sharp: ^2.5.12 => 2.5.12 
```

**Comment by Lutherwaves** [comment]
I'm also getting a neverending installation when I run
```
gatsby recipes storybook-ts --install
```
I'm experiencing 0 errors when installing packages manually tho.

**Comment by laurieontech** [comment]
Thanks for the issue! I don't have the fix yet but wanted to let you know that I was able to reproduce it.

My suspicion at the moment is that it has to do with the mix of dev dependencies and regular dependencies. Trying to switch between the two makes it hang. But that's unconfirmed just yet.

**Comment by KyleAMathews** [comment]
@laurieontech that looks like it's it!

This recipe doesn't ever finish in the same way:

```mdx
yo

---

<NPMPackage name="foo" />
<NPMPackage name="bar" dependencyType="development" />
```
