### ISSUE TITLE
gatsby-react-router-scroll changes resulting in fail of gbi in Chrome

### ISSUE THREAD

**Issue by timhagn** [gatsbyjs/gatsby#26481]
## Description

Two weeks ago I got a new bug-report in `gatsby-background-image`, [#125](https://github.com/timhagn/gatsby-background-image/issues/125). With the changes from PR #24306 `gbi` gets called again after its own `IntersectionObserver` kicks in when scrolling down, which results in its given image getting loaded again for normal & adaptive images, stacked images seem to work.
Only setting `critical` "rectifies" the repeated image loading, but that isn't a functional workaround in the long run.
And I guess in some cases this might happen for `gatsby-image` as well, but I didn't look into it.

The "offending line" in the compiled output is the initialization (number 34 in `scroll-handler.js`):

```js
_this = _React$Component.call.apply(_React$Component, [this].concat(args)) || this;
```

I couldn't disable the behavior with a `shouldUpdateScroll` in a `gatsby-browser.js`, or should this even be possible like this?
The workarounds from other issues like setting `"resolutions"` to `"gatsby-react-router-scroll": "3.0.0"` didn't work either.

Or is there any other way to prevent the `ScrollHandler` from interrupting `gbi`s flow (or a thing I might be able to change)?
Any help would be highly appreciated!

### Steps to reproduce

Adding a placeholder `div` in front of a `BackgroundImage` component, putting it below the fold and kicking off the `IntersectionObserver` (like the OP in [#125](https://github.com/timhagn/gatsby-background-image/issues/125) did):

```jsx
    <div style={{ height: 4000, display: 'block' }}></div>
```

Without setting `critical` on the `BackgroundImage` the image loads twice / trice.

I created a reproduction branch in `gbitest`, the demo repo of `gbi`, called [scroll-handler-bug](https://github.com/timhagn/gbitest/tree/scroll-handler-bug). The div was added [here](https://github.com/timhagn/gbitest/blob/6da4b153f2c2a85e76ed5ffa235e5744147bd95b/src/pages/index.js#L16) and the relevant component is [`BackgroundSection`](https://github.com/timhagn/gbitest/blob/scroll-handler-bug/src/components/BackgroundSection.js).

### Expected result

Image gets loaded only once.

### Actual result

The `scroll` event handler kicks in and forces `BackgroundImage` to rerender, which results in multiple image load events:
![image](https://user-images.githubusercontent.com/22683980/89183695-e7906780-d597-11ea-817d-810c32eb75e0.png)

### Environment

```
  System:
    OS: Linux 5.4 Linux Mint 20 (Ulyana)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47
    gatsby-background-image: ^1.1.2 => 1.1.2
    gatsby-image: ^2.4.16 => 2.4.16
    gatsby-plugin-manifest: ^2.4.23 => 2.4.23
    gatsby-plugin-offline: ^3.2.23 => 3.2.23
    gatsby-plugin-react-helmet: 3.3.10 => 3.3.10
    gatsby-plugin-sharp: ^2.6.27 => 2.6.27
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10
    gatsby-source-filesystem: ^2.3.24 => 2.3.24
    gatsby-transformer-sharp: ^2.5.13 => 2.5.13
```

I also tested it with node v12.18.0 with sadly the same result.
And I of course know `gbi` is no core component of gatsby, but any help would be greatly appreciated!

**Comment by timhagn** [comment]
Hi there,

any news on this one?

Best,

Tim.

**Comment by timhagn** [comment]
Still nothing : /?

**Comment by not-authorized** [comment]
Hi there, any plans/updates on this issue?
