### ISSUE TITLE
Calling `createNodeField` with an incomplete node object will delete fields

### ISSUE THREAD

**Issue by multimeric** [gatsbyjs/gatsby#26487]
## Description
Calling `createNodeField` with an incomplete node object will delete any fields on the node that are not attached to the `node` object you pass in.

### Steps to reproduce
This is fully documented in this repo: https://github.com/TMiguelT/GatsbyCreateNodeFieldBug

1. `git clone git@github.com:TMiguelT/GatsbyCreateNodeFieldBug.git`
2. `gatsby develop`

### Expected result

No assertion should fail, or more generally, calling `createNodeField` with an incomplete node object should not touch the fields that are not provided at the time.

### Actual result
The assertion `assert("firstField" in fullNode)` will fail, indicating that a field has been deleted

### Environment
```
  System:
    OS: Linux 4.19 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 AMD FX(tm)-8320 Eight-Core Processor
    Shell: 3.1.2 - /usr/bin/fish
  Binaries:
    Node: 14.8.0 - /usr/bin/node
    npm: 6.14.7 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.24.41 => 2.24.47 
    gatsby-image: ^2.4.15 => 2.4.16 
    gatsby-plugin-manifest: ^2.4.22 => 2.4.23 
    gatsby-plugin-offline: ^3.2.23 => 3.2.23 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.26 => 2.6.27 
    gatsby-source-filesystem: ^2.3.24 => 2.3.24 
    gatsby-transformer-sharp: ^2.5.12 => 2.5.13 
  npmGlobalPackages:
    gatsby-cli: 2.12.87
```

**Comment by TMiguelT** [comment]
Sidenote: if this is considered desirable behaviour (I don't think it is, but someone might), then I think a note in the documentation is at least important here to prevent other people having this issue.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
