### ISSUE TITLE
[www]: Issue on compare JAMstack technologies page

### ISSUE THREAD

**Issue by nephlin7** [gatsbyjs/gatsby#26502]
## Description
Sometimes this [issue](https://streamable.com/bb7ais) happens on the compare JAMstack technologies page https://www.gatsbyjs.com/features/jamstack/gatsby-vs-nextjs/

**Comment by LekoArts** [comment]
Thanks for the issue! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/26475
