### ISSUE TITLE
Router from "@reach/router" shows page not found

### ISSUE THREAD

**Issue by Imran109** [gatsbyjs/gatsby#26505]
I am trying to make custom Routes. Whenever enter `localhost:8000/login` in **Browser** it gives me `404` page instead of the **login page** itself. 

**index.js**
```
import React from "react"
import { Router} from "@reach/router"
import LoginComponent from "../components/LoginComponent";
import ProfileComponent from "../components/ProfileComponent";
import AuthRoute from "./authRoute";
import PublicRoute from "./PublicRoute"

export default function Home() {
  const token = localStorage.getItem("Authorization");
  return (
  <Router>
          <PublicRoute  path = "/login" component = {LoginComponent} token = {token}/>
          <AuthRoute  path = "/profile" component = {ProfileComponent} token = {token}/>
  </Router>
  )
}
```

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/42968710/90368191-59cc7600-e087-11ea-8af7-85aba19a2bef.png">

![image](https://user-images.githubusercontent.com/42968710/90368227-681a9200-e087-11ea-8e2d-ed9a1ccf99a8.png)

![image](https://user-images.githubusercontent.com/42968710/90368314-75378100-e087-11ea-9a24-1209247d9a00.png)

**Comment by blainekasten** [comment]
@Imran109 That is not the correct way to create client side routes. Gatsby takes care of routing for you, so you need to just create components under `src/pages` and each file will create a new route.

So for you, you should make:

```
src/pages/login.js      => url.com/login
src/pages/profile.js    => url.com/profile
```
