### ISSUE TITLE
[question] Upgrading to webpack 5.x

### ISSUE THREAD

**Issue by onichandame** [gatsbyjs/gatsby#26507]
## Summary

Is there any plan to upgrade the webpack to 5.x used in Gatsby?

## Relevant information

Recently I tried to adopt [ipfs](https://ipfs.io/) into a Gatsby project. However, [A bug in webpack](https://github.com/webpack/webpack/issues/1599) blocked the building process.

As stated in the issue, the bug is fixed in webpack@5.

**Comment by polarathene** [comment]
Webpack 5 will be used for an upcoming Gatsby v3 release from what I know. They'll likely be quite a bit of other changes to go with that major version change(of Gatsby), so it may take some time until we see it materialize.

**Comment by onichandame** [comment]
@polarathene thx for providing the info. Is there already an issue tracking this feature? I have searched in the milestone "Next Major" but nothing related is found.

**Comment by polarathene** [comment]
I am not aware of any progress, I am just a contributor sorry.

**Comment by wardpeet** [comment]
Hey, thanks for the question. There are no plans yet to support webpack 5, it's still early days. Webpack 5 is still in beta, the ecosystem (plugins, loaders, ...) still have to be adjusted so it's going to take a couple of months for us to upgrade. As @polarathene we'll do it in a major release, probably v4 in about 6 months.


We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by tujoworker** [comment]
There is an open Issue on Webpack 5 here: #26146
