### ISSUE TITLE
Starter Hello World needs gatsby version bump + deploy

### ISSUE THREAD

**Issue by shaun3141** [gatsbyjs/gatsby#26503]
## Description

There was the issue around [Cannot find module 'gatsby-cli/lib/reporter'](https://github.com/gatsbyjs/gatsby/issues/26463) - some of the starter repos have it updated now, but not the [starter repo](https://github.com/gatsbyjs/gatsby-starter-hello-world) referenced in the tutorial.

### Steps to reproduce

Look at `package.json` :)

### Expected result

I had tried to make the change here to fix this: https://github.com/gatsbyjs/gatsby-starter-hello-world/pull/62/files

### Actual result

N/A

### Environment

N/A

**Comment by shaun3141** [comment]
Less of an issue, but I noticed the readme still has a broken image link though it seems to be fixed in the monorepo so I think it just needs to be pushed again?

**Comment by polarathene** [comment]
Related: https://github.com/gatsbyjs/gatsby/issues/26499

**Comment by samfearn** [comment]
I came to make the same issue - building a new project from the hello-world starter on MacOS gave me the error regarding not being able to find gatsby-cli/lib/reporter. Updating the version of gatsby listed in package.json to `^2.24.42` and then running `npm install` fixed the problem.

**Comment by wardpeet** [comment]
Thanks, I'll get it updated today 👍

**Comment by wardpeet** [comment]
Fixed
