### ISSUE TITLE
Sometimes when I stop Gatsby server, it isn't actually being stopped

### ISSUE THREAD

**Issue by SilencerWeb** [gatsbyjs/gatsby#26501]
## Description
Sometimes when I stop Gatsby server, it isn't actually being stopped. I run the command `gatsby develop -H 0.0.0.0` in VS Code terminal, then stop the command with `control + c` and it is stopped in the terminal but then I run the command `gatsby develop -H 0.0.0.0` again and it says "Something is already running at port 8000" and asks "Would you like to run the app at another port instead?", I press `y` and it throws an error "Looks like develop for this site is already running. Try visiting http://localhost:8001 maybe?" but nothing has even been run on port 8001.

I'm not sure yet what could be the reason for such bug, I'm experiencing it all the time but can't understand the pattern yet to tell you how to reproduce it. Maybe it has to do something with the changes it `gatsby-node.js` during the development and then me canceling to restart the server when Gatsby asks for it. Anyway, I'll post an update if I understand the pattern so you guys could reproduce this bug.

### Environment
```
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.42 => 2.24.42
    gatsby-alias-imports: ^1.0.4 => 1.0.4
    gatsby-image: ^2.4.15 => 2.4.15
    gatsby-plugin-google-tagmanager: ^2.3.11 => 2.3.11
    gatsby-plugin-manifest: ^2.4.22 => 2.4.22
    gatsby-plugin-offline: ^3.2.23 => 3.2.23
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-sass: ^2.3.12 => 2.3.12
    gatsby-plugin-sharp: ^2.6.26 => 2.6.26
    gatsby-plugin-svgr-svgo: ^1.0.12 => 1.0.12
    gatsby-source-filesystem: ^2.3.24 => 2.3.24
    gatsby-source-wordpress-experimental: ^1.3.3 => 1.3.3
    gatsby-transformer-sharp: ^2.5.12 => 2.5.12
```

**Comment by blainekasten** [comment]
Next time this happens could you run `ps -c | grep node` and see if there is still a node process running? Also you can then run `lsof -i :8000` and `lsof -i :8001` to see what process is exposing a server on a specific port.

I haven't seen this issue before so I'll wait to see what comes back for these. Also, what version of gatsby cli are you running? `gatsby -v`

**Comment by SilencerWeb** [comment]
Sure, I'll provide this information next time it happens.

About version of gatsby CLI, `gatsby -v` doesn't do anything since `gatsby` is not installed globally, only locally in the project.

Meanwhile, could you please try to run `gatsby develop -H 0.0.0.0` in one tab of the terminal and then run the same command in another terminal tab without stopping the first process? It should ask if you want to run gatsby on another port and on confirmation it should throw an error.

![image](https://user-images.githubusercontent.com/20713191/91398778-31e2cc80-e856-11ea-9210-dd5f1e18362c.png)

By the way, look at the link gatsby suggests to visit — `http://://localhost:8001`, it seems to be weird, isn't it?

**Comment by SilencerWeb** [comment]
I've had such issue again and here are the results of the commands you asked to run:

`ps -c | grep node`:
```
 1887 ttys001    0:02.03 node
 1896 ttys001    0:56.55 node
 1917 ttys001    0:00.00 (node)
 1918 ttys001    0:00.00 (node)
 1919 ttys001    0:00.00 (node)
 1920 ttys001    0:00.00 (node)
 1921 ttys001    0:00.00 (node)
 1922 ttys001    0:00.00 (node)
```

`lsof -i :8000`:
```
COMMAND  PID        USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    1887 silencerweb   27u  IPv4 0xa6d34c47efec98cb      0t0  TCP *:irdmi (LISTEN)
```

`lsof -i :8001` prints nothing

`gatsby -v` still prints nothing because as I said earlier, gatsby is not installed globally for me, but I ran `npx gatsby -v` and here is the result I got:
```
Gatsby CLI version: 2.12.88
Gatsby version: 2.24.50
  Note: this is the Gatsby version for the site at: /Users/silencerweb/Documents/work/project
```

This time I've got this issue while the server was getting ready to start, there was an error in one query which I fixed during these processes and then I used shortcut `control + c` to stop the process:
![image](https://user-images.githubusercontent.com/20713191/91552021-88c6cf80-e944-11ea-8f64-13681e52a82a.png)

**Comment by SilencerWeb** [comment]
Thanks a lot @wardpeet!

**Comment by SilencerWeb** [comment]
By the way, @wardpeet, does it fix the issue when you run the server in one terminal tab and try to run the server in the second tab?

![image](https://user-images.githubusercontent.com/20713191/91720008-c5e2ca00-ebaf-11ea-893b-82d5925afec4.png)
