### ISSUE TITLE
Starter Error - doesn't exist file empty

### ISSUE THREAD

**Issue by akanoodles** [gatsbyjs/gatsby#26522]
Description

I get the following error when trying to pull the starter folder down from Github
<img width="851" alt="Screenshot 2020-08-17 at 21 15 00" src="https://user-images.githubusercontent.com/1613697/90440826-c9feea00-e0cf-11ea-8b27-e59cf7ae2bfb.png">

Steps to reproduce
In Terminal I type the command "gatsby new hello-world https://github.com/gatsbyjs/gatsby/tree/master/starters/hello-world"

Expected result
Complete file

Actual result
<img width="851" alt="Screenshot 2020-08-17 at 21 15 00" src="https://user-images.githubusercontent.com/1613697/90440826-c9feea00-e0cf-11ea-8b27-e59cf7ae2bfb.png">

### Environment
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
    Safari: 13.1.2
  npmGlobalPackages:
    gatsby-cli: 2.12.87

**Comment by wardpeet** [comment]
Hey @akanoodles ,

You'll have to pull it down like this:
`gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world`

Just checking where did you get that URL from?


We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by racingicemen** [comment]
That URL is from the tutorial on gatsbyjs.com
https://www.gatsbyjs.com/tutorial/part-zero/#create-a-gatsby-site
