### ISSUE TITLE
Missing onError handler for invocation 'rebuildSchemaWithSitePage'

### ISSUE THREAD

**Issue by SimonSiefke** [gatsbyjs/gatsby#26531]
## Description

```
Missing onError handler for invocation 'rebuildSchemaWithSitePage', error was 'TypeError: Cannot read property 'contents' of null'. Stacktrace was 'TypeError: Cannot read property 'contents' of null
    at get (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:10:20)
    at map (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:20:59)
    at Array.map (<anonymous>)
    at getArray (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:19:6)
    at get (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:12:36)
    at get (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:13:50)
    at get (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:13:50)
    at get (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:13:50)
    at getValueAt (/home/simon/tmp/bug-repro/node_modules/gatsby/src/utils/get-value-at.ts:4:10)
    at getFirstValueAt (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/is-file.ts:14:15)
    at find (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/is-file.ts:84:13)
    at Array.find (<anonymous>)
    at getFilePath (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/is-file.ts:83:41)
    at isFile (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/is-file.ts:91:20)
    at getSimpleFieldConfig (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:315:11)
    at getFieldConfig (/home/simon/tmp/bug-repro/node_modules/gatsby/src/schema/infer/add-inferred-fields.js:174:19)'
```

### Steps to reproduce

Minimal reproduction: https://github.com/SimonSiefke/gatsby-bug

1. Run `gatsby develop`
2. Error occurs

### Expected result

No Error

### Actual result

Error

### Environment

```

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.3.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47 
  npmGlobalPackages:
    gatsby-cli: 2.12.87

```

**Comment by pieh** [comment]
We just published `gatsby@2.24.49` which fixes the root problem. I locally checked the provided reproduction and it no longer result in this error after upgrading `gatsby`.

**Comment by pickleat** [comment]
Just encountered the same issue on `gatsby@2.24.54` but upgrading to `gatsby@2.24.86` fixed it. Just in case someone else comes across this again.

**Comment by pickleat** [comment]
Its happening again on `gatsby@2.24.86`

**Comment by Tony-Ndichu** [comment]
Also happening on `@gatsby@^2.24.91`

**Comment by tingiris** [comment]
Also happening on `gatsby@2.25.0`

**Comment by kiril-daskalov** [comment]
Does `gatsby clean` help for you. I think it is working for me.

**Comment by tingiris** [comment]
> Does `gatsby clean` work for you? I think it is working for me.

Yes, that seems to have worked for me too. I also noticed that if I use `npm` to update modules I get the issue but not if I use `yarn`.

**Comment by ledtest** [comment]
Also happening on `gatsby@2.30.1`，`gatsby-cli@2.15.0`

**Comment by iamkratos** [comment]
This is also happening in Gatsby V3

**Comment by Faiiya** [comment]
Im also having this error in Gatsby V3

**Comment by dillon** [comment]
Same problem in Gatsby V3

**Comment by acapro** [comment]
I was able to solve this in V3 but updating graphql to version "^15.4.0"

**Comment by Hahlh** [comment]
Similar error ```error handler for infocation 'building-schema', error was "TypeError: cannot read property 'name' of undefined."```` was solved by bumping gatsby-source-sanity to 6.0.5.

**Comment by i001962** [comment]
managed to get unstuck by moving from npm to yarn after running "rm -rf node_modules && rm -rf package-lock.json"

**Comment by Faiiya** [comment]
> managed to get unstuck by moving from npm to yarn after running "rm -rf node_modules && rm -rf package-lock.json"

moving from npm to yarn worked out for me too

**Comment by AnderUstarroz** [comment]
I am facing a similar issue:
- https://stackoverflow.com/questions/67768308/how-to-fix-invariant-violation-errors-when-running-gatsby-build-develop/67768487?noredirect=1#comment119784364_67768487

but `rm -rf node_modules && rm -rf package-lock.json` doesn't really seems to work.

**Comment by peterschwarzdev** [comment]
Neither for me :(

**Comment by triwats** [comment]
This is still impacting me too, but not sure how to catch this to get more verbosity:


```
 ERROR

Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value:
  JSON.'. Stacktrace was 'Error: Cannot create as TypeComposer the following value:
  JSON.
    at SchemaComposer.createTempTC (/Users/tristan.watson/src/make/node_modules/gatsby/node_modules/graphql-compose/lib/SchemaComposer.js:463:11)
    at SchemaComposer.createTC (/Users/tristan.watson/src/make/node_modules/gatsby/node_modules/graphql-compose/lib/SchemaComposer.js:426:84)
    at SchemaComposer.add (/Users/tristan.watson/src/make/node_modules/gatsby/node_modules/graphql-compose/lib/SchemaComposer.js:715:21)
    at createSchemaComposer (/Users/tristan.watson/src/make/node_modules/gatsby/src/schema/schema-composer.js:17:18)
    at build (/Users/tristan.watson/src/make/node_modules/gatsby/src/schema/index.js:104:26)
    at buildSchema (/Users/tristan.watson/src/make/node_modules/gatsby/src/services/build-schema.ts:19:3)'

⠙ building schema
```

```
❯ gatsby --version
Gatsby CLI version: 3.4.0
Gatsby version: 3.6.1
  Note: this is the Gatsby version for the site at: /Users/tristan.watson/src/make
```

**Comment by MiKatre** [comment]
Happening to me since updating to Gatsby v3

**Comment by Rocketpilot** [comment]
Still happening on:

Gatsby CLI version: 3.10.0
Gatsby version: 3.9.1

after adding the gatsby-source-rest-api plugin.

Should this not be re-opened?

**Comment by Dickson-Mwendia** [comment]
I'm experiencing the same issue on Gatsby Version 3.10.0

**Comment by hudadamar21** [comment]
its happening to me too, when i edit the markdown content, its error always showing and server stuck.
after restart the server then no error, and i edit the markdown content again, error showing again :|

**Comment by trinidades** [comment]
https://github.com/gatsbyjs/gatsby-starter-landing-page

> ERROR 
> 
> Missing onError handler for invocation 'building-schema', error was 'Error: Type with name "contentfulLandingPageContentPrimaryTextTextNode" does not exists'. Stacktrace was 'Error: Type with name
> "contentfulLandingPageContentPrimaryTextTextNode" does not exists
>     at SchemaComposer.get (C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\graphql-compose\lib\TypeStorage.js:44:13)
>     at ThunkComposer._thunk (C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\graphql-compose\lib\TypeMapper.js:585:34)
>     at ThunkComposer.get ofType [as ofType] (C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\graphql-compose\lib\ThunkComposer.js:20:34)
>     at getTypeNode (C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\graphql-compose\lib\utils\definitionNode.js:265:28)
>     at C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\graphql-compose\lib\utils\definitionNode.js:317:18
>     at Array.map (<anonymous>)
>     at getFieldDefinitionNodes (C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\graphql-compose\lib\utils\definitionNode.js:315:21)
>     at getObjectTypeDefinitionNode (C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\graphql-compose\lib\utils\definitionNode.js:40:13)
>     at ObjectTypeComposer.getType (C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\graphql-compose\lib\ObjectTypeComposer.js:700:76)
>     at ThunkComposer.getType (C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\graphql-compose\lib\ThunkComposer.js:46:24)
>     at ListComposer.getType (C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\graphql-compose\lib\ListComposer.js:22:49)
>     at ObjectTypeComposer.getFieldConfig (C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\graphql-compose\lib\ObjectTypeComposer.js:348:18)
>     at forEach (C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\gatsby\src\schema\extensions\index.js:220:48)
>     at Array.forEach (<anonymous>)
>     at C:\Users\User\Documents\Gatsby\my-landing-page-site\node_modules\gatsby\src\schema\extensions\index.js:215:8
>     at Array.forEach (<anonymous>)'
> 
> ⠴ building schema

Getting stuck here, both on my bare metal and Gatsby coud build.
Any ideas for debugging this?

**Comment by vinodchauhan99** [comment]
ERROR 

Missing onError handler for invocation 'building-schema', error was 'Error: Type with name "GatsbyImageLayout" does not exists'. Stacktrace was 'Error:    
Type with name "GatsbyImageLayout" does not exists
    at SchemaComposer.get (D:\A3\HouseManager\house-manager-master\node_modules\graphql-compose\src\TypeStorage.ts:39:13)
    at ThunkComposer._thunk (D:\A3\HouseManager\house-manager-master\node_modules\graphql-compose\src\TypeMapper.ts:737:34)
    at ThunkComposer.get ofType [as ofType] (D:\A3\HouseManager\house-manager-master\node_modules\graphql-compose\src\ThunkComposer.ts:21:34)
    at getTypeNode (D:\A3\HouseManager\house-manager-master\node_modules\graphql-compose\src\utils\definitionNode.ts:253:28)
    at D:\A3\HouseManager\house-manager-master\node_modules\graphql-compose\src\utils\definitionNode.ts:286:20
    at Array.map (<anonymous>)
    at getArgumentsDefinitionNodes (D:\A3\HouseManager\house-manager-master\node_modules\graphql-compose\src\utils\definitionNode.ts:284:6)
    at D:\A3\HouseManager\house-manager-master\node_modules\graphql-compose\src\utils\definitionNode.ts:320:20
    at Array.map (<anonymous>)
    at getFieldDefinitionNodes (D:\A3\HouseManager\house-manager-master\node_modules\graphql-compose\src\utils\definitionNode.ts:312:6)
    at getObjectTypeDefinitionNode (D:\A3\HouseManager\house-manager-master\node_modules\graphql-compose\src\utils\definitionNode.ts:61:13)
    at ObjectTypeComposer.getType (D:\A3\HouseManager\house-manager-master\node_modules\graphql-compose\src\ObjectTypeComposer.ts:986:57)
    at ObjectTypeComposer.getFieldConfig (D:\A3\HouseManager\house-manager-master\node_modules\graphql-compose\src\ObjectTypeComposer.ts:595:18)
    at forEach (D:\A3\HouseManager\house-manager-master\node_modules\gatsby\src\schema\extensions\index.js:220:48)
    at Array.forEach (<anonymous>)
    at D:\A3\HouseManager\house-manager-master\node_modules\gatsby\src\schema\extensions\index.js:215:8'

⠇ building schema

**Comment by spond-canoo** [comment]
Same for me. 

Missing onError handler for invocation 'building-schema', error was 'Invariant Violation: Encountered an error
trying to infer a GraphQL type for: `component: video___NODE`. There is no corresponding node with the `id` field
matching: "7c7b7o0fmMBybG2ZP6rXCH".'. Stacktrace was 'Invariant Violation: Encountered an error trying to infer a
GraphQL type for: `component: video___NODE`. There is no corresponding node with the `id` field matching:
"7c7b7o0fmMBybG2ZP6rXCH".

**Comment by MeiYu-AAXIS** [comment]
> Same for me.
> 
> Missing onError handler for invocation 'building-schema', error was 'Invariant Violation: Encountered an error trying to infer a GraphQL type for: `component: video___NODE`. There is no corresponding node with the `id` field matching: "7c7b7o0fmMBybG2ZP6rXCH".'. Stacktrace was 'Invariant Violation: Encountered an error trying to infer a GraphQL type for: `component: video___NODE`. There is no corresponding node with the `id` field matching: "7c7b7o0fmMBybG2ZP6rXCH".

excuse me, have you solved it?

**Comment by spond-canoo** [comment]
> > Same for me.
> > Missing onError handler for invocation 'building-schema', error was 'Invariant Violation: Encountered an error trying to infer a GraphQL type for: `component: video___NODE`. There is no corresponding node with the `id` field matching: "7c7b7o0fmMBybG2ZP6rXCH".'. Stacktrace was 'Invariant Violation: Encountered an error trying to infer a GraphQL type for: `component: video___NODE`. There is no corresponding node with the `id` field matching: "7c7b7o0fmMBybG2ZP6rXCH".
> 
> excuse me, have you solved it?

I believe the issue I had boiled down to a restriction listed for the gatsby-source-contentful plugin:

At the moment, fields that do not have at least one populated instance will not be created in the GraphQL schema. This can break your site when field values get removed. You may workaround with an extra content entry with all fields filled out.


To workaround, I filled out a completed Model, with all descendent references also being completely filled out... with dummy data.

This is inconvenient, but it seems to keep the schema inference from crashing when content is being removed and swapped, especially in a live-preview development environment.

**Comment by Krus-Leung** [comment]
It happens again on Gatsby version 4.10.0

**Comment by AbdallahAbis** [comment]
Facing the same issue on `gatsby@^4.9.3` and `gatsby-cli@3.11.0`


![Screen Shot 2022-03-21 at 19 21 19](https://user-images.githubusercontent.com/59185227/159338820-aae3bc4a-9892-45ac-9a3c-536c2e4d1b02.png)

**Comment by sripriyesha** [comment]
Running `gatsby clean` solved it for me

**Comment by davido242** [comment]
Honestly there seems to be no solution to this error; I keep wondering why it will require a downgrade of packages to older ones! Seek!

**Comment by hotWater-me** [comment]
Also happening on  "gatsby": "^4.14.0",  This problem has been around for so long, is there a good solution ?

`Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value:`

**Comment by davido242** [comment]
> Also happening on "gatsby": "^4.14.0", This problem has been around for so long, is there a good solution ?
> 
> `Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value:`

Try to downgrade gatsby version and its peer dependencies...............I downgraded to ^3 for my app and it works

**Comment by rub1e** [comment]
Should this issue be closed? It's just happened to me and clearly plenty of people are still affected by it.

I have an old site that's still on Gatsby v2 and this started when I upgraded gatsby-transformer-sharp from `2.5.21` to `2.12.1`

**Comment by yachaoxiong** [comment]
same here   "gatsby-source-graphql": "^4.13.0",

**Comment by kapy9612** [comment]
I've also got this problem in gatsby: 3.14.6, with gatsby-source-strapi: 1.0.3, but I solved it by deleting a many-to-one connection in the collection type which affected the error.

**Comment by CSzLong** [comment]
I met this issue today, but it was resolved after I installed the source inside the project folder.

**Comment by raulvictorrosa** [comment]
> I met this issue today, but it was resolved after I installed the source inside the project folder.

Which source did you installed?

**Comment by barbalex** [comment]
Just ran into this when updating gatsbyjs from 4.24.1 to 4.24.6.

I was hoping to have one of the rare cases of updating dependencies in a gatsby project that would not fail. Well, so much for hoping...

**Comment by laurent-le-graverend** [comment]
Same here; I can't find a solution so far...

**Comment by ZeldOcarina** [comment]
Same here, it started occuring when I tried to upgrade to v5. It's stunning this issue has zero comments from the Gatsby team..

**Comment by barbalex** [comment]
I ran into this again, updating a different project from 4 to 5

**Comment by websupergirl** [comment]
Thank you @barbalex for your comments - that was a lifesaver when upgrading 4->5.

I'm leaving my notes in case someone else like me find this.

In my case, it was also competing graphql, but it was the gatsby images/sharp/transfomer plugins asking for 16 and gatsby 5 asking for 15. Running `npm ls graphql` gave me this (truncated):

```
├─┬ gatsby-plugin-image@3.0.0
│ └─┬ gatsby-plugin-utils@4.0.0
│   └── graphql@16.6.0
├─┬ gatsby-plugin-manifest@5.0.0
│ └─┬ gatsby-plugin-utils@4.0.0
│   └── graphql@16.6.0
├─┬ gatsby-plugin-sharp@5.0.0
│ └─┬ gatsby-plugin-utils@4.0.0
│   └── graphql@16.6.0
├─┬ gatsby-transformer-sharp@5.0.0
│ └─┬ gatsby-plugin-utils@4.0.0
│   └── graphql@16.6.0
└─┬ gatsby@5.0.1
  ├─┬ @graphql-codegen/add@3.2.1
  │ └── graphql@15.8.0
```

I fixed this by deleting `node_modules` and `package-lock.json`, and then running:

```
npm install --legacy-peer-deps
gatsby clean && gatsby develop
```

**Comment by laurent-le-graverend** [comment]
I could solve this issue by removing graphql from my project.
It's not needed, gatsby has its own via `import { graphql } from 'gatsby';`

<img width="373" alt="image" src="https://user-images.githubusercontent.com/332246/202456567-58b080f2-e23a-4255-a942-8c9a625ae8fc.png">

**Comment by Jazy08** [comment]
Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the
following value:
  GraphQLScalarType({ name: "Date", description: "A date string, such as 2007-12-03, compliant with the ISO 8601
standard for representation of dates and times using the Gregorian calendar.", specifiedByURL: undefined,
serialize: [function String], parseValue: [function String], parseLiteral: [function parseLiteral], extensions: {
 }, astNode: undefined, extensionASTNodes: [] }).'. Stacktrace was 'Error: Cannot create as TypeComposer the
following value:
  GraphQLScalarType({ name: "Date", description: "A date string, such as 2007-12-03, compliant with the ISO 8601
standard for representation of dates and times using the Gregorian calendar.", specifiedByURL: undefined,
serialize: [function String], parseValue: [function String], parseLiteral: [function parseLiteral], extensions: {
 }, astNode: undefined, extensionASTNodes: [] }).


Experiencing the same error in gatsby while updating from version 3 to version 5.

**Comment by wjdwl002** [comment]
Got the same problem on `gatsby@5.4.0` while just simply starting a [starter project](https://github.com/gatsbyjs/gatsby-starter-datocms-homepage-ts). Tried all suggestions above all and nothing seems to work

**Comment by tomasIndicius** [comment]
@wjdwl002 all of the sudden it's happening to me as well. Did you manage to get it to work?

**Comment by joaosilva-lp** [comment]
The only way that worked for me was update nodejs

**Comment by kapilsinha** [comment]
This needs resolution from the team. The basic starter landing page templates is broken, and has been problematic for many many people clearly

**Comment by ZeldOcarina** [comment]
Gatsby has been clearly completely killed by Netlify. It's time for everyone to migrate to Astro, if anyone is still here.. I've migrated a huge project to Astro, it's missing some of the nice features Gatsby had (components shadowing mostly) but it's doable and the end result is so much more performant..

**Comment by kapilsinha** [comment]
> Gatsby has been clearly completely killed by Netlify. It's time for everyone to migrate to Astro, if anyone is still here.. I've migrated a huge project to Astro, it's missing some of the nice features Gatsby had (components shadowing mostly) but it's doable and the end result is so much more performant..

@ZeldOcarina Understood, it's sunk cost for me at this point. Appreciate, I'll check out Astro. Essentially I want to spin up a free landing page with minimal fuss (I hate that I had to even set up a Contentful account here) and own the code. Is that easy with Astro?

**Comment by ZeldOcarina** [comment]
> > Gatsby has been clearly completely killed by Netlify. It's time for everyone to migrate to Astro, if anyone is still here.. I've migrated a huge project to Astro, it's missing some of the nice features Gatsby had (components shadowing mostly) but it's doable and the end result is so much more performant..
> 
> @ZeldOcarina Understood, it's sunk cost for me at this point. Appreciate, I'll check out Astro. Essentially I want to spin up a free landing page with minimal fuss (I hate that I had to even set up a Contentful account here) and own the code. Is that easy with Astro?

Oh yeah if it's just for a landing page it's actually waay easier than with Gatsby!
