### ISSUE TITLE
Problems with "simple-auth" example: default path flickering (404)

### ISSUE THREAD

**Issue by iksent** [gatsbyjs/gatsby#26546]
### Steps to reproduce

1. Clone ["simple-auth" example](https://github.com/gatsbyjs/gatsby/tree/master/examples/simple-auth) or follow the official guide [client-only-routes-and-user-authentication](https://www.gatsbyjs.com/docs/client-only-routes-and-user-authentication/)

My clone: https://github.com/iksent/gatsby-simple-auth

2. Create default "404" route at app.js:
```
    <Router>
      <PrivateRoute path="/app/details" component={Details} />
      <PrivateRoute path="/app/profile" component={Profile} />
      <Login path="/app/login" />
      <NotFound text="Not found at APP" path="/app/*" /> --------- HERE IT IS
    </Router>
```

3. Publish to netlify: https://modest-liskov-1349ce.netlify.app/

4. Go to client-side route: https://modest-liskov-1349ce.netlify.app/app/login
And press F5 to reload the page.

### Expected result

We will see the Login's page content.

### Actual result

We see "NotFound.js" component's content firstly, then JS loads Login content.
With JS disabled we will see NotFound.js content only.

**Comment by blainekasten** [comment]
We are shipping new features to improve client side pages. See #26375. We will update our documentation once we stabilize this feature!

But in short, instead of creating a 404 route, you would create the following files:

```
src/pages/app/details.js
src/pages/app/profile.js
src/pages/app/login.js
src/pages/app/[...].js (this is your 404 route aka, /app/*)
```
