### ISSUE TITLE
`navigate` doesn't return Promise

### ISSUE THREAD

**Issue by devfive** [gatsbyjs/gatsby#26543]
## Description

According to the `gatsby-link` TypeScript declaration file, `navigation` function returns a Promise which resolves when React renders next screen.

https://github.com/gatsbyjs/gatsby/blob/b86d3ffefa003ee6d0095283c92d4581167e0770/packages/gatsby-link/index.d.ts#L35

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/410945551d356ddda19d268df0ad85ad6e8959f6/types/reach__router/index.d.ts#L106

Unfortunately, it's not a case, because `gatsby-link` exports `navigate` function which uses global `window.___navigate`:
https://github.com/gatsbyjs/gatsby/blob/b86d3ffefa003ee6d0095283c92d4581167e0770/packages/gatsby-link/src/index.js#L269

`window.__navigate` uses `reach/router`'s `navigate` function under the hood:
https://github.com/gatsbyjs/gatsby/blob/b86d3ffefa003ee6d0095283c92d4581167e0770/packages/gatsby/cache-dir/navigation.js#L49

### Steps to reproduce

Pseudocode:
```
import { navigate } from 'gatsby-link'

describe('gatsby-link', () => {
  it('navigate should return a promise', () => {
    expect(navigate('/')).toBeInstanceOf(Promise)
  })
})
```

### Expected result

To be honest not sure what is expected, but we have two options:
1. Fix TypeScript declaration to return proper type for `navigation` function.
2. Fix the code and match `reach/router`'s API (shouldn't be very difficult as this is just to add `return` here and there)

I would be happy to prepare a PR once it will be decided.

### Actual result

`navigate` doesn't return a Promise

### Environment

```
  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - ~/.pyenv/shims/python
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.24.11 => 2.24.11 
    gatsby-background-image: ^1.1.1 => 1.1.1 
    gatsby-image: ^2.4.13 => 2.4.13 
    gatsby-plugin-google-tagmanager: ^2.3.1 => 2.3.1 
    gatsby-plugin-manifest: ^2.4.21 => 2.4.21 
    gatsby-plugin-mdx: ^1.2.18 => 1.2.18 
    gatsby-plugin-nprogress: ^2.3.6 => 2.3.6 
    gatsby-plugin-offline: ^3.2.21 => 3.2.21 
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sass: ^2.3.12 => 2.3.12 
    gatsby-plugin-sharp: ^2.6.22 => 2.6.22 
    gatsby-plugin-sitemap: ^2.3.6 => 2.3.6 
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10 
    gatsby-plugin-typescript: ^2.1.27 => 2.1.27 
    gatsby-source-filesystem: ^2.3.23 => 2.3.23 
    gatsby-source-sylius-rest: 0.3.0-dev.0 => 0.4.0-dev.1 
    gatsby-transformer-json: ^2.4.11 => 2.4.11 
    gatsby-transformer-sharp: ^2.5.11 => 2.5.11 
```

**Comment by herecydev** [comment]
Duplicate of #22151

**Comment by devfive** [comment]
Oh, forgive me!
