### ISSUE TITLE
"Unknown fragment \"GatsbyContentfulFixed_withWebp_noBase64\"."

### ISSUE THREAD

**Issue by raulrr88** [gatsbyjs/gatsby#26559]
## Description

I can't use SQIP because of this "Unknown fragment \"GatsbyContentfulFixed_withWebp_noBase64\"." error.

### Steps to reproduce

Docs instructions to use SQIP with Contentful isn't working.

`With gatsby-source-contentful:

image {
  sqip(numberOfPrimitives: 30, blur: 0) {
    dataURI
  },
  fixed {
    ...GatsbyContentfulFixed_withWebp_noBase64
  }
}`

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

use `...GatsbyContentfulFixed_withWebp_noBase64 normally`

### Actual result

"Unknown fragment \"GatsbyContentfulFixed_withWebp_noBase64\"."

### Environment

```
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.23.12 => 2.24.47 
    gatsby-image: ^2.4.16 => 2.4.16 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.3.10 => 2.3.12 
    gatsby-plugin-sharp: ^2.6.27 => 2.6.27 
    gatsby-source-contentful: ^2.3.26 => 2.3.37 
    gatsby-source-filesystem: ^2.3.24 => 2.3.24 
    gatsby-transformer-sharp: ^2.5.13 => 2.5.13 
    gatsby-transformer-sqip: ^2.3.27 => 2.3.27 
  npmGlobalPackages:
    gatsby-cli: 2.12.45
`

**Comment by blainekasten** [comment]
Strange! Do you have `gatsby-source-contentful` setup in your gatsby-config.js?

**Comment by raulrr88** [comment]
Hey @blainekasten! Yes, I do.
