### ISSUE TITLE
GitHub Issues: missing option to reopen my issues - GatsbyjsBot closing Issues without chance to reopen

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#26552]
## Description

I am not able to reopen issues, GatsbyBot closing issues, but there is no chance to reopen them.

### Steps to reproduce

https://github.com/gatsbyjs/gatsby/issues/22503

> Please keep in mind that I’m only a robot, so if I’ve closed this issue in error, I’m HUMAN_EMOTION_SORRY. Please feel free to reopen this issue or create a new one if you need anything else.

### Expected result

no reopen possible

### Actual result

missing reopen button:
<img width="955" alt="Bildschirmfoto 2020-08-19 um 16 56 45" src="https://user-images.githubusercontent.com/184316/90651175-01d77000-e23d-11ea-9fe9-4781712a024b.png">

### Environment

- on GitHub Issues

**Comment by pieh** [comment]
Hey @muescha!

First of all thanks for pointing this out!

In the short term, we will be increasing number of days before "stale bot" actually auto-closes the issue: https://github.com/gatsbyjs/gatsby/pull/26571 looks to bump it from current 30 days (10 days after the "stale?" label application) to 60 days. This will give us more time to have proper solution for this.

**Comment by muescha** [comment]
Not stale

**Comment by muescha** [comment]
Not stale

**Comment by muescha** [comment]
Not stale
