### ISSUE TITLE
Incompatible typescript type for Node interface (parent isn't nullable)

### ISSUE THREAD

**Issue by ervasive** [gatsbyjs/gatsby#26553]
## Description

The typescript typings state that `parent` property of Node interface can be of type `string` only, when in fact it also can be `Null` in runtime when a node does not have a `parent`

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/index.d.ts#L1520

```
export interface Node extends NodeInput {
  parent: string
  children: string[]
  internal: NodeInput["internal"] & {
    owner: string
  }
  [key: string]: unknown
}
```

### Expected result

The Typescript typings should reflect the possibility of `parent` property of Node interface to be nullable

**Comment by AdamSiekierski** [comment]
https://github.com/gatsbyjs/gatsby/blob/f59fb3703e92910477a8f437d6448757cb6ce408/packages/gatsby/src/redux/types.ts#L66 . I think it should be replaced with `Identifier | null`

**Comment by pieh** [comment]
You are absolutely right. Would you be willing to open pull request to adjust the type, so `parent` is nullable?

**Comment by ervasive** [comment]
Not stale

**Comment by ervasive** [comment]
not stale?
