### ISSUE TITLE
StaticQuery error running a Gatsby Preview server on Heroku

### ISSUE THREAD

**Issue by woodwoerk** [gatsbyjs/gatsby#26564]
> Please note, this has already been reported here: #21392 - however that issue was closed due to the lack of a reproduction. This includes similar information but also the reproduction requested by maintainers.

## Description

I'm trying to run `gatsby develop` on Heroku to set up a custom Gatsby Preview server. This approach is recommended in the [Gatsby docs here](https://www.gatsbyjs.com/docs/running-a-gatsby-preview-server/#rolling-your-own-preview)

However, the page fails with `Error: The result of this StaticQuery could not be fetched.`. When not using a static query the page renders fine.

#### Prerequisites

- [Heroku CLI](https://devcenter.heroku.com/articles/heroku-cli)

#### Steps:

1. Clone [this reproduction](https://github.com/woodwoerk/heroku-gatsby-dev-bug-repro) and jump in:

```
  git clone https://github.com/woodwoerk/heroku-gatsby-dev-bug-repro.git
  cd heroku-gatsby-dev-bug-repro
```

2. Create a new Heroku site via the heroku cli:

```
  heroku create
```

3. Set Heroku env variables:

```
  heroku config:set NODE_ENV=development
  heroku config:set NPM_CONFIG_PRODUCTION=false
  heroku config:set ENABLE_GATSBY_REFRESH_ENDPOINT=true
```

4. Deploy to Heroku:

```
  git push heroku master
```

5. After deployment, open the app url which is now running `gatsby develop` at \<heroku-app-name>.herokuapp.com

### Expected result

The page at `<heroku-app-name>.herokuapp.com` should show "Hello world!" as defined and queried for in the `siteMetadata`, which works successfully when running locally. 

### Actual result

The page fails to render with the error:

```
Error: The result of this StaticQuery could not be fetched.
```

Link to live environment: https://limitless-sands-63823.herokuapp.com/

![Capture](https://user-images.githubusercontent.com/15343658/90789324-767adf00-e30f-11ea-8635-fc66f34f691a.PNG)

### Environment

Running in a Free Dyno on Heroku

```
  npmPackages:
    gatsby: ^2.24.42 => 2.24.47 
```

**Comment by LekoArts** [comment]
Closing this as stale since in the meantime Gatsby v4 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction][reproduction]).

[reproduction]: https://gatsby.dev/reproduction

**Comment by woodwoerk** [comment]
> Closing this as stale since in the meantime Gatsby v4 and updated related packages were released. Please try with the latest versions and if you still see this problem open a new bug report (it must include a [minimal reproduction](https://gatsby.dev/reproduction)).

@LekoArts Is it counter productive to close this and open a new issue rather than reopening this one? Just migrated to v4 and the bug persists, I'll create a new issue but please reopen this if you prefer.
