### ISSUE TITLE
bug: 404 link on https://www.gatsbyjs.com/cloud/docs/sanity/getting-started/

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#26569]
## Description

- 404 on link

### Steps to reproduce

- open: https://www.gatsbyjs.com/cloud/docs/sanity/getting-started/
- click on: `Follow the steps in this doc`
- 404: `https://www.gatsbyjs.com/cloud/docs/adding-gatsby-cloud-extension-to-sanity/`
- expected: `https://www.gatsbyjs.com/cloud/docs/sanity/adding-extension/`

**Comment by LekoArts** [comment]
Thanks, I fixed that wrong link!
