### ISSUE TITLE
bug: 404 link on gatsbyjs.com/cloud/docs/integrations/

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#26568]
## Description

- 404 on link

### Steps to reproduce

- open: https://www.gatsbyjs.com/cloud/docs/integrations/
- click on: `data source`
- 404: `https://www.gatsbyjs.com/cloud/docs/integrations/(/cloud/docs/#data-source-CMS-integrations)`
- expected: `https://www.gatsbyjs.com/cloud/docs/#data-source-CMS-integrations`

**Comment by LekoArts** [comment]
Thanks, I fixed the link on that cloud doc.
