### ISSUE TITLE
Unable to change default icon and splash screen in ionic 5. 

### ISSUE THREAD

**Issue by so1995** [gatsbyjs/gatsby#26575]
Hi guys ,hope you guys are fine. I have really really big problem. I am trying to change the default icon and splash screen in my ionic 5 application and it keeps giving lots of errors and i don't know what to do. I have tried all sorts of thing but nothing seems to work. Please i really really need some help. please

### Expected result

IT should change my icon and splash screen automatically

### Actual result

Cannot find module '../build/Release/sharp.node'

**Comment by LekoArts** [comment]
I think you're in the wrong repository here :) I'd suggest asking on the Ionic platforms/forums.
