### ISSUE TITLE
How do I obtain a node by ID when in onCreateNode?

### ISSUE THREAD

**Issue by atrauzzi** [gatsbyjs/gatsby#26585]
## Summary

When gatsby is calling `onCreateNode` for each node made, do I have a way of querying for a specific parent node by its ID?

## Relevant information

I'm using `gatsby-transformer-remark` with `gatsby-source-filesystem`.  Unfortunately, I also have `gatsby-source-blogger` and all the nodes from `gatsby-source-blogger` are being visited by `gatsby-transformer-remark`.

My hope was that I could follow the parent of the nodes created by `gatsby-transformer-remark` to see if they are markdown files so that I'm only processing what I need.

Apologies if this is fairly basic, I haven't been able to search anything out in the documentation or in existing issues.  Likely due to the level of ambiguity in all the terminology I'm after here. :laughing:

**Comment by blainekasten** [comment]
```
// gatsby-node.js
exports.onCreateNode = function({node, getNode}) {
  const parentNode = getNode(node.parent);
  console.log(parentNode)
}

**Comment by atrauzzi** [comment]
Thanks!
