### ISSUE TITLE
Please add npx installation part

### ISSUE THREAD

**Issue by karan-tewari** [gatsbyjs/gatsby#26591]
Hi , the gatsby cli was giving me the error to get started. Once I tried the same with npx , it worked in first go ( got the npx idea from react and it did work )

Please mention the same on docs as well, as its more preferred way to config any project.

**Comment by LekoArts** [comment]
Thanks for the issue! We don't plan on adding `npx` information as the docs expect you to have the CLI globally installed (so we can't change that first initial installation step). It might be a localized issue on your machine as in general the CLI installation works. If you found a bug, please report that via the appropriate issue template. Thanks!
