### ISSUE TITLE
gatsby-plugin-react-css-modules does not work in presence of gatsby-plugin-resolve-src

### ISSUE THREAD

**Issue by deadalnix** [gatsbyjs/gatsby#26595]
## Description

When using a CSS included via a path provided by gatsby-plugin-resolve-src , this module throws with the following error:

```
file.js: Cannot find module 'path/to/style.css'
```

### Steps to reproduce

Create a gatsby project with both gatsby-plugin-resolve-src and gatsby-plugin-react-css-modules enabled.

Create a page and try to import a css file using its path from src.

### Expected result

The path of the CSS module is resolved as per speficied by gatsby-plugin-resolve-src (or more generally, using the webpack config set with gatsby-node.js 's onCreateWebpackConfig )

### Actual result

The set of path used for resolution using gatsby-plugin-react-css-modules differs from the one set by gatsby-plugin-resolve-src . As a result, trying to import CSS using these path lead to a "Cannot find module" error and gatsby does not start.

### Environment
I'm not sure this is very relevant to this specific issue, but here we go.

```
  System:
    OS: Linux 5.7 Debian GNU/Linux bullseye/sid
    CPU: (12) x64 Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz
    Shell: 5.0.18 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/bin/node
    npm: 6.14.7 - /usr/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47
    gatsby-image: ^2.4.16 => 2.4.16
    gatsby-plugin-asset-path: ^3.0.2 => 3.0.2
    gatsby-plugin-manifest: ^2.4.23 => 2.4.23
    gatsby-plugin-offline: ^3.2.23 => 3.2.23
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0
    gatsby-plugin-sass: ^2.3.12 => 2.3.12
    gatsby-plugin-scroll-reveal: 0.0.7 => 0.0.7
    gatsby-plugin-sharp: ^2.6.27 => 2.6.27
    gatsby-source-filesystem: ^2.3.24 => 2.3.24
    gatsby-transformer-sharp: ^2.5.13 => 2.5.13
  npmGlobalPackages:
    gatsby-cli: 2.12.87
```

**Comment by blainekasten** [comment]
Thanks for the report! Would you be willing to submit a PR to fix this?

**Comment by deadalnix** [comment]
@blainekasten Hi,

Sorry, for some reason, I messed the notification and was unaware that you answered. I'm willing to work on a fix, but you need to know that I'm pretty new to this whole ecosystem and so I'd probably need some hand-holding. If you are willing to give me some pointer, I'd be happy to have a look.

Maybe you guys have a telegram/irc/discord/whatever I could join?
