### ISSUE TITLE
How to use GatsbySSR['wrapPageElement']?

### ISSUE THREAD

**Issue by mrseanbaines** [gatsbyjs/gatsby#26594]
## Summary
I'm using Gatsby with TypeScript, and I've configured it to be able to write my `gatsby-*` files using TS as well. Typing the browser API of `wrapPageElement` was smooth and simple:

```tsx
import React from 'react'
import { GatsbyBrowser } from 'gatsby'

import { WrapPageElement } from 'components/wrap-page-element'

export const wrapPageElement: GatsbyBrowser['wrapPageElement'] = ({ element }) => (
  <WrapPageElement>{element}</WrapPageElement>
)
```

...but trying to do the same with the SSR API has been a little trickier:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/24367010/90959346-693a2d80-e492-11ea-8c9d-43f92c4e2194.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/24367010/90959358-7e16c100-e492-11ea-802d-6c7ae5f6547f.png">

I've kind of gotten around it (with some help from the TS community), but it feels a little hacky:

<img width="603" alt="image" src="https://user-images.githubusercontent.com/24367010/90959387-ae5e5f80-e492-11ea-8458-7253344201a4.png">

My question is: Is there a better way to do this? Is the typing for this `wrapPageElement` in the SSR API wrong, or is this expected behaviour?

## Relevant information
Using the latest version of Gatsby (`2.24.47`)

### Environment (if relevant)

```sh
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - /var/folders/c6/zn3s5lkd09xf78n8tcylhyg00000gn/T/yarn--1598108880795-0.29181622183273914/node
    Yarn: 1.22.4 - /var/folders/c6/zn3s5lkd09xf78n8tcylhyg00000gn/T/yarn--1598108880795-0.29181622183273914/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47 
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10 
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by blainekasten** [comment]
Our internal types here are probably not great. We're in the middle of a large refactor internally to use typescript which will allow us to improve our external types.

For now, I would recommend either submitting a PR to fix our types, or not using it and making your own types for your codebase

**Comment by doylemark** [comment]
Any update on this? 😬

**Comment by ZeeEssDoubleU** [comment]
Bump
