### ISSUE TITLE
metadata() for js pages

### ISSUE THREAD

**Issue by 1st1** [gatsbyjs/gatsby#266]
What's the recommended way of adding metadata to JS pages?  I'm trying to use the `metadata()` hook, but when it's present in the file, the `ReactComponent` doesn't render. If I comment out the `metadata()` block, `<h1>blog post</h1>` gets rendered just fine.

```javascript
export default class ReactComponent extends React.Component {
  render () {
    return (
        <h1>
          blog post
        </h1>
    )
  }
}

export function metadata() {
  return {
    title: 'Blog Post',
  }
}
```

**Comment by KyleAMathews** [comment]
`metadata` needs to be a static function of the class itself not exported from the module. See http://stackoverflow.com/questions/29433130/react-statics-with-es6-classes

Here's where in the code the function is called: https://github.com/gatsbyjs/gatsby/blob/master/lib/isomorphic/create-routes.js#L114
