### ISSUE TITLE
Easier access to make calls to window before the page renders

### ISSUE THREAD

**Issue by jonohewitt** [gatsbyjs/gatsby#26604]
## Summary

I'm still very new to gatsby so I'm sorry if I'm missing something that already exists here!

I've found that occasionally I need to make a check to window.localStorage or window.matchMedia which determins how I want my page to look before it loads - e.g dark mode or loading with an app tab bar instead of a top nav bar if launched as a PWA. Just including these checks in a useEffect hook works, but there is a flicker of the default state (I assume from the pre-rendering at build time?) before they take effect. This is a jarring experience. 

Through following a [dark mode article](https://joshwcomeau.com/gatsby/dark-mode/) by @joshwcomeau I've seen there is a way to inject a blocking script before render which works really well - but the developer experience is quite convoluted, writing an IIFE as a string and converting it to html within the script. I was wondering if it would be possible to make this more intuitive?

Maybe there could be a priority hook that we could use inside the component alongside useEffect which would block rendering until it is evaluated, or a gatsby-browser / srr api which lets us list the components that need to evaluate their useEffect hooks before rendering to screen, or a priority context provider we could use within useEffect which provides a state that gets assigned before anything is rendered to the screen.

I don't know if any of this would be possible and I understand that adding more steps before the initial render is bad for performance, but it seems that sometimes this could be really valuable to avoid the flicker. If this already exists, please could you point me in the right direction?

### Motivation

Avoiding flickering on conditionally rendered components while calls to window are made.

**Comment by blainekasten** [comment]
This isn't a problem unique to Gatsby but instead unique to SSR. Which is a wider concept and applies to many other frameworks and setups. 

This is not something that is actively on our roadmap, but if you can think of a good API and solution, I would recommend you submit an [RFC](https://github.com/gatsbyjs/gatsby/blob/master/rfcs/README.md) for us to discuss and weigh in on. Then it can be on our roadmap!
