### ISSUE TITLE
regex not working in Graphql query: Invalid flags supplied to RegExp constructor

### ISSUE THREAD

**Issue by nisarhassan12** [gatsbyjs/gatsby#26600]
## Description

Describe the issue that you're seeing.

I'm trying to use this `^(?!content\/blog).*` in my query 

```graphql
 query {
      allMdx(
        filter: { fileAbsolutePath: { regex: "^(?!content\/blog).*" } }
      ) {
        edges {
          node {
            id
            frontmatter {
              slug
            }
          }
        }
      }
}
```

but it gives me this error 
```
Invalid flags supplied to RegExp constructor 'blog).*'
```

I have tested the regex on https://regex101.com and it seems to work well there:

![image](https://user-images.githubusercontent.com/46004116/90969744-a1cf1b00-e515-11ea-8691-a1be38e31cfe.png)

I don't know Regex not sure how the regex that I have can be made valid.

Thanks.

**Comment by karland** [comment]
I am also using a filter and have put slashes around the regex, which is working fine. So try:

```JS
filter: { fileAbsolutePath: { regex: "/^(?!content\/blog).*/" } }
```

I am not sure, but maybe this helps.

**Comment by blainekasten** [comment]
@nisarhassan12 yes, you need to wrap it in slashes, almost like a fully formed javascript regex. 

Thanks @karland!
