### ISSUE TITLE
Add Sourcemaps for Sass  [gatsby-plugin-postcss-sass]

### ISSUE THREAD

**Issue by 12finger** [gatsbyjs/gatsby#2660]
Currently in develop-mode all styles(css) get put into the head into a style tag.
Which is perfectly fine for a basic use case.

Though if you have multiple Sass-partials and do some `@include`s and whatnot .. in order to be able to debug we need sourcemaps support for sass source files.

I tried to modify the webpack config via `exports.modifyWebpackConfig = ({ config, stage }) => { …`
but did not succeed. I simply could not get it working that way ..

While diving into the plugin gatsby-plugin-postcss-sass i found the spot which needed modification: 

https://github.com/gatsbyjs/gatsby/blob/475cae7e72af9fe0b209c4afd329d7eab5342b37/packages/gatsby-plugin-postcss-sass/src/gatsby-node.js#L23

For dev-mode this line can be
[**_proposed-fix:_**]
`loaders: [ 'style', 'css?sourceMap', 'postcss', 'sass?sourceMap' ]` 
 
and many users would instantly benefit from it. 
Works for me™.
Could somebody with more background/deeper understanding check/confirm this ?
Does it work for all ?

Btw: I found out that 
https://github.com/gatsbyjs/gatsby/blob/475cae7e72af9fe0b209c4afd329d7eab5342b37/packages/gatsby-plugin-postcss-sass/src/gatsby-node.js#L16

`sassLoader` is outputting some strange stuff (when logged to console):
 *  `sass?{"plugins":[],"postCssPlugins":[null,null ],"precision":8}`

In my case i am using two postCssPlugins (autoprefixer, lost-grid) and they only appear with a `null` each in the sassloader postCssPlugins and obviously they are not needed here, as everything seems to work properly when using my proposed fix from above

**Comment by ptrikutam** [comment]
I'm currently having the same issue, and I'm trying to enable source maps for the development environment only. Doing something like the following in my `gatsby-node.js` isn't working:

```javascript
exports.modifyWebpackConfig = ({ config, stage }) => {
  switch (stage) {
    case 'develop': {
      config.loader('sass', {
        loaders: ['style', 'css', 'sass', 'sass?sourceMap'],
      });
      return config;
    }
    default: {
      return config;
    }
  }
};
```

Looking at https://github.com/gatsbyjs/gatsby/issues/692, I also tried using `sass-loader` instead of `sass`, and it still didn't work. I'm sure I'm screwing up something simple in the config. Anyone have any ideas?

**Comment by azamatsmith** [comment]
Update to above - For now @ptrikutam and I are using this solution for sourcemaps with `gatsby-plugin-sass`:

```
exports.modifyWebpackConfig = ({ config }) => {
  const newConfig = { ...config };
  const loadersArr = ['style', 'css?sourceMap', 'sass', 'sass?sourceMap'];
  if (config._loaders.sass.config.loaders) {
    newConfig._loaders.sass.config.loaders = loadersArr;
  }
  return newConfig;
}
```

We know there is probably a better way to update the loaders object below (this is from the gatsby docs), but we are not sure how.

```
config.loader('sass', {
  include: /flexboxgrid/,
});
```

**Comment by emanueleperuffo** [comment]
I think this is the correct way:

`exports.modifyWebpackConfig = ({config, stage}, options) => {
  options.sourceMap = true;

  const sassFiles = /\.s[ac]ss$/;
  const sassModulesFiles = /\.module\.s[ac]ss$/;
  const sassLoader = `sass?${JSON.stringify(options)}`;

  switch (stage) {
    case 'develop': {
      config.removeLoader('sass');
      config.removeLoader('sassModules');

      config.loader('sass', {
        test: sassFiles,
        exclude: sassModulesFiles,
        loaders: ['style', 'css?sourceMap', sassLoader],
      });

      config.loader('sassModules', {
        test: sassModulesFiles,
        loaders: ['style', `${cssModulesConfig(stage)}&sourceMap=true`, sassLoader],
      });

      return config;
    }
    default: {
      return config;
    }
  }
};`

**Comment by KyleAMathews** [comment]
Would love a PR fixing this for gatsby-plugin-sass!

**Comment by emanueleperuffo** [comment]
I don't really remember why I put it there. 
I think that was the original CSS webpack loader from either gatsby or its sass plugin.

Anyways... My mistake, I should have specified that you need to require() that function:

```javascript
const {cssModulesConfig} = require('gatsby-1-config-css-modules');
```

**Comment by benwis** [comment]
Hey @emanueleperuffo you wouldn't happen to have this ported for gatsby v2 have you? I'd love to get sourcemaps, but it seems like cssModulesConfig has moved and modifyWebpackConfig has become onCreateWebpackConfig. I'm trying to modify it, but my webpack is rusty. Thanks!

**Comment by emanueleperuffo** [comment]
Hey @benwis!
I'll look at it when I get back from holidays 😊

**Comment by kakadiadarpan** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub issues, we have to clean some of the old issues as many of them have already been resolved with the latest updates.

Please make sure to update to the latest Gatsby version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by kakadiadarpan** [comment]
This issue is being closed because there hasn't been any activity for at least 30 days. Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem 👍
