### ISSUE TITLE
Actions 'undefined' in 'createPages'

### ISSUE THREAD

**Issue by jthawme** [gatsbyjs/gatsby#26612]
## Description

The actions object is listed as undefined in `gatsby-node.js` in my `createPages` export. This is without any changes, just using https://www.gatsbyjs.com/starters/haysclark/gatsby-starter-typescript (although i have installed gatsby-source-google-sheets)

### Steps to reproduce

Heres the repo, should be able to just install and try run `yarn gatsby develop` to see the problem.
https://github.com/jthawme/lifeline/tree/actions-undefined

### Expected result

`actions` shouldn't be undefined

### Actual result

`actions` is undefined

### Environment

  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash

  Binaries:
    Node: 12.16.3 - /var/folders/y3/qx7d738x02vdw1w0t57ljb5w0000gn/T/yarn--1598265666178-0.6475163283741687/node
    Yarn: 1.22.4 - /var/folders/y3/qx7d738x02vdw1w0t57ljb5w0000gn/T/yarn--1598265666178-0.6475163283741687/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm

  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 79.0
    Safari: 13.1.1

  npmPackages:
    gatsby: ^1.9.119 => 1.9.279 
    gatsby-link: ^1.6.28 => 1.6.46 
    gatsby-plugin-react-helmet: ^1.0.8 => 1.0.8 
    gatsby-plugin-typescript: ^1.4.10 => 1.4.20 
    gatsby-source-google-sheets: ^1.1.1 => 1.1.1

**Comment by blainekasten** [comment]
This is using gatsby v1, we are no longer actively supporting gatsby v1. Please upgrade to gatsby v2, in which `actions` will be present in `createPages`

**Comment by jthawme** [comment]
Apologies, @blainekasten didn't see that as the problem. Is there an official typescript starter for gatsby?
