### ISSUE TITLE
Rendering iframe in a div -Gatsby

### ISSUE THREAD

**Issue by skyphyy** [gatsbyjs/gatsby#26623]
[ask.txt](https://github.com/gatsbyjs/gatsby/files/5121477/ask.txt)
[ask.txt](https://github.com/gatsbyjs/gatsby/files/5121478/ask.txt)

Hi I'm new to Gatsby and I'm trying to render iframe using these scripts in a div
Please let me know how to do it in gatsby.
Thanks in advance.

`<​div​​ id​=​"container"​></​div​>
<​script​>​
var​ Container ​=​​document​.​querySelector​(​"#container"​);​
var​ store ​=​​new ​​obj.details​({
    Token​:​​"TOKEN"​,
    Id​:​​"ID"​
 });  
store.​renderStore(Container);
</​script​>`

**Comment by LekoArts** [comment]
Thank you for opening this!

As Gatsby is only a thin layer over React it works like in any other React application:
https://stackoverflow.com/questions/33913737/inserting-the-iframe-into-react-component
https://stackoverflow.com/questions/50454134/rendering-iframe-into-react

You'll need to convert the logic for selecting the container and appending a script to React.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
