### ISSUE TITLE
jwt not working ,  Route discovered : /jwt-auth/v1 Excluded route: blacklisted

### ISSUE THREAD

**Issue by bstrokevin** [gatsbyjs/gatsby#26639]
## Description

Try to use JWT auth with  gatsby-source-wordpress and  https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
But it's not working

See the out put below, (removed email and password). I'm not sure why  does is say:
Route discovered : /jwt-auth/v1
Excluded route: blacklisted

Site hosted on Wordpress.com: false
Using ACF: true
Auth:
  JWT Auth: email:password
Verbose output: true

Mama Route URL: https://domain.com/wp-json

Detected ACF to REST namespace: acf/v2.
Route discovered : /
Excluded route: blacklisted
Route discovered : /oembed/1.0
Excluded route: blacklisted
Route discovered : /oembed/1.0/embed
Excluded route: blacklisted
Route discovered : /oembed/1.0/proxy
Excluded route: blacklisted
Route discovered : /jwt-auth/v1
Excluded route: blacklisted
Route discovered : /jwt-auth/v1/token
Excluded route: blacklisted
Route discovered : /jwt-auth/v1/token/validate

### Steps to reproduce

updated gatsby config 
auth: {
          jwt_user: "email address",
          jwt_pass: "password",
        },

### Expected result

Should be authdicated and be able to draft posts. Not just published posts.

### Actual result

Route blacklisted. And can only get published posts 

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 47.81s. - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 77.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.22.0 => 2.22.0
    gatsby-awesome-pagination: ^0.3.6 => 0.3.6
    gatsby-image: ^2.4.7 => 2.4.7
    gatsby-plugin-asset-path: ^3.0.2 => 3.0.2
    gatsby-plugin-google-tagmanager: ^2.3.11 => 2.3.11
    gatsby-plugin-lodash: ^3.3.1 => 3.3.1
    gatsby-plugin-netlify: ^2.3.2 => 2.3.2
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-remote-images: ^2.1.0 => 2.1.0
    gatsby-plugin-sass: ^2.3.1 => 2.3.1
    gatsby-plugin-sharp: ^2.6.6 => 2.6.6
    gatsby-remark-images: ^3.3.5 => 3.3.5
    gatsby-source-filesystem: ^2.3.18 => 2.3.18
    gatsby-source-wordpress: ^3.3.5 => 3.3.5
    gatsby-transformer-remark: ^2.8.10 => 2.8.10
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2
    gatsby-wordpress-reading-time: ^1.0.4 => 1.0.4
  npmGlobalPackages:
    gatsby-cli: 2.8.29

**Comment by TylerBarnes** [comment]
Hi @bstrokevin !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Also, I would definitely recommend starting to think about upgrading to the beta of `gatsby-source-wordpress@v4`. We're currently publishing it as a [separate package](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental) to help folks migrate, so that the old and new version can be installed side by side. In the near future we will be deprecating our usage of the WP REST API when v4 becomes stable.

[reproduction]: https://gatsby.dev/reproduction

**Comment by jacksellwood** [comment]
With the introduction of v4 of gatsby-source-wordpress, we'll only be applying critical vulnerability patches to v3.
Checkout docs for upgrading from v3 to v4: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/migrating-from-other-wp-source-plugins.md
It's faster too!
