### ISSUE TITLE
is it possible / advisable to mount a client-only route on the root of the gatsby site?

### ISSUE THREAD

**Issue by cristiano-belloni** [gatsbyjs/gatsby#26638]
I know that it's possible to mount [client-only routes](https://www.gatsbyjs.com/docs/client-only-routes-and-user-authentication/) in Gatsby. Is there any controindication on doing it so on the root of the site, e.g. having the client-only route returned from the `index.jsx` page and having all the static pages in a subfolder, like `/docs`?

**Comment by sidharthachatterjee** [comment]
Nope, no limitation from that. You can do that!

**Comment by cristiano-belloni** [comment]
@sidharthachatterjee thanks!
