### ISSUE TITLE
Change `target-container`

### ISSUE THREAD

**Issue by MythreyaK** [gatsbyjs/gatsby#26635]
Is it possible to change the [target container](https://www.gatsbyjs.com/docs/custom-html/#target-container)?

There's a project I'm converting to Gatsby, and changing this would make a lot of pain go away...

**Comment by blainekasten** [comment]
Yes. The document you referenced is showing you how you can create a custom `html.js` file and put the gatsby target container anywhere in the root structure. The only requirement is that there must be an element that has `id="___gatsby"` so gatsby can find it and attach the react tree.

**Comment by MythreyaK** [comment]
Hmm in hindsight, perhaps I didn't express my question well. I meant to ask if I could change the `id` itself, to something else.

**Comment by LekoArts** [comment]
No, that's not possible.
