### ISSUE TITLE
Connecting Gatsby with redux rematch

### ISSUE THREAD

**Issue by mossen** [gatsbyjs/gatsby#26649]
Is there any way to connect Gatsby with [rematch](https://github.com/rematch/rematch) in a way without having a wrapper in every single file. Something like a react app that has a provider around the whole app.

Also from the docs:

> Once in wrapRootElement which runs during Gatsby's server rendering process, and once in wrapRootElement which is part of Gatsby's browser APIs.

Isn't that supposed to handle this issue? or a provider for every single file is mandatory?

**Comment by arthurjdam** [comment]
That would indeed solve the issue. If you're using the wrapRootElement pattern, adding the Provider again per page would be redundant. 
I've submitted a PR to fix the rematch example in their repo here: https://github.com/rematch/rematch/pull/809

**Comment by mossen** [comment]
That wrapper.tsx is the magic, thanks for the help
