### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined on blog-post.js

### ISSUE THREAD

**Issue by nodox** [gatsbyjs/gatsby#2665]
I have a theme system abstraction in my application to create a prototype version of simple install themes for gatsbyjs. You can see how its used in the [gatsby layout](https://github.com/nodox/gatsby-blog-starter-kit/blob/master/src/layouts/index.js) and the implementation can be found in the [theme](https://github.com/nodox/gatsby-blog-starter-kit/blob/master/src/themes/massively/Massively.js).

Everything worked perfectly in development mode but once I build, some of my props are not rendered thus cause my buttons to be unclickable. I can only assume that my abstraction is somehow messing with react router. I'm not sure why this should be a problem since the only thing I'm doing is cloning props onto my own components. How can I debug this issue?

**Comment by nodox** [comment]
`package.json`
```
{
  "name": "gatsby-blog-starter-kit",
  "description": "Gatsby blog starter example",
  "version": "1.1.0",
  "author": "Dustin Schau <dustinschau@gmail.com>",
  "dependencies": {
    "classnames": "^2.2.5",
    "gatsby": "~1.9.45",
    "gatsby-link": "~1.6.17",
    "gatsby-plugin-catch-links": "~1.0.1",
    "gatsby-plugin-google-analytics": "^1.0.8",
    "gatsby-plugin-react-helmet": "~1.0.1",
    "gatsby-plugin-react-next": "~1.0.4",
    "gatsby-plugin-sharp": "~1.6.8",
    "gatsby-remark-images": "~1.5.13",
    "gatsby-source-filesystem": "~1.5.1",
    "gatsby-transformer-remark": "~1.7.12",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-icons": "~2.2.5",
    "react-router-dom": "^4.2.2"
  },
  "devDependencies": {
    "babel-jest": "^21.2.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "enzyme": "^3.1.0",
    "enzyme-adapter-react-16": "^1.0.2",
    "enzyme-to-json": "^3.1.4",
    "gh-pages": "~1.0.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^21.2.1",
    "prettier": "~1.7.2",
    "react-test-renderer": "^16.0.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "deploy": "gatsby build --prefix-paths",
    "postdeploy": "gh-pages -d public",
    "develop": "gatsby develop",
    "preserve": "npm run build",
    "serve": "gatsby serve",
    "start": "npm run develop",
    "format": "prettier --trailing-comma es5 --single-quote --write \"src/**/*.js\"",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:coverage": "jest --coverage"
  }
}

```

**Comment by nodox** [comment]
The error also seems to propagate upwards from `    'gatsby-plugin-catch-links'` would I lose some speed if I tried to take this off?

**Comment by nodox** [comment]
Seems to be a server side issue on build pipeline. Not sure why everything is parsed but then when updated to the frontend nothing is present.

**Comment by emmafallancy** [comment]
Hi @nodox , may I know what does the error say? Maybe I could help you out on this. Also, are you able to build and host it? 😃 Was wondering if when you click on any link element before, would it throw you any error?

**Comment by nodox** [comment]
@emmafallancy I have solved the problem. I'm not sure how. Thank you!

**Comment by mtzfactory** [comment]
@nodox I'm very insterested in the solution, I have the same issue...
