### ISSUE TITLE
Data imported in a mdx file appear in the main js bundle for all pages?

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#26655]
I've seen, when exploring the js files that appear in a gatsby site, that any component that you import in a `mdx` file (processed by `gatsby-plugin-mdx`) appears in the mail js bundle (in all pages)

The same, but in a regular page instead of a `mdx` page, doesn't put that component in the bundle

- clone the repo https://github.com/kuworking/test_gatsby_mdx
- yarn
- gatsby build
- gatsby serve
- localhost:9000 and visit the main page

`page-5.mdx` imports `<More />`
`test.js` imports `<Test />` and `<Alarm />`

None of them are linked to the main page

When you explore the `app-6261...js` file, you find the contents of `<More />` there, but not the contents of `<Test />` and `<Alarm />`

- Is that a bug or a feature?
- Is there any way to prevent this? Or one should refrain of using `mdx` if there are plans for importing heavy components?

**Comment by kuworking** [comment]
I've made a repo https://github.com/kuworking/test_gatsby_mdx

There I've just the `mdx starter`, added a `js` file with a bunch of data and a component that is `imported` in the second page

- clone the repo
- yarn
- gatsby build
- gatsby serve
- localhost:9000 and visit the main page
- explore the 3 `js` files, in my case the `app-0cb94...js`

There in that file (a big 80.1 kB file) you can find the data of that component (which is responsible for that size)

```
        return r.a.createElement("div", null, i.map(function(t) {
            return r.a.createElement("span", null, t)
        }))
    }
      , i = ["test", "test", "test", "test", "test", "test", "test", "test", "test", "test", "test", 
```

So the data is necessary (not in this example), but I only want to accept the costs for such data in the relevant page, not in all pages of the website

How can I prevent this from happening?

**Comment by laurieontech** [comment]
Thanks for asking this question. This is, in fact, expected behavior. However it’s not ideal and something we’ve been noodling on how to fix. We have a way forward and if you’d like to track that work you can follow [this issue](https://github.com/gatsbyjs/gatsby/issues/25069).
