### ISSUE TITLE
Guard against common "Unterminated JSX contents" errors 

### ISSUE THREAD

**Issue by macdonst** [gatsbyjs/gatsby#26667]
## Summary

I'd like to see `gatsby-plugin-mdx` guard against common unterminated HTML elements that show up in .md or .mdx files. 

Tags like:

```html
<br>
<hr>
<img src="image.png">
```

### Basic example

In on-create-node.js line [#47](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/gatsby/on-create-node.js#L47) the content of the .md/.mdx file is loaded before it is passed to `createMDXNode`. Input like:

```markdown
# Test

This is a test.<br>Of the emergency broadcast system.

<hr>

This is only a test.
```

could be converted to:

```markdown
# Test

This is a test.<br/>Of the emergency broadcast system.

<hr/>

This is only a test.
```

Just by doing some string manipulation.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

We are hoping to make this change as we have a lot of historical documentation in markdown but would like to use MDX when creating our site. Since we pull down the docs using `gatsby-source-git` we often don't have the offending markdown in the same codebase as being used to create the site. We are hoping to avoid having to send PR's to many, many repos in order to fix these issues.

**Comment by laurieontech** [comment]
Thanks for opening this issue. While I understand the use case presented, I don't think it makes sense to implement in `gatsby-plugin-mdx`. The main reason is for consistency with the MDX spec which does not manipulate the tags as written. 

As a potential alternative to changing all the source code you could query your mdx nodes in `gatsby-node` and transform/parse the body content before creating the pages.
