### ISSUE TITLE
MDX v2 breaks Markdown images with gatsby-remark-images

### ISSUE THREAD

**Issue by patrickarlt** [gatsbyjs/gatsby#26662]
## Description

Attempting to upgrade to the latest version of MDX (2.0.0-next.7) breaks `gatsby-remark-images`.

### Steps to reproduce

Minimal reproduction: https://github.com/patrickarlt/gatsby-mdx-v2-image-issue-reproduction

1. Clone Repo
2.  `npm install`
3. `gatsby develop` - note the missing image
4. `npm install @mdx-js/mdx@1.6.16 @mdx-js/react@1.6.16` - install previous mdx
5. `gatsby clean`
6. `gatsby develop` - image appears

### Expected result

These pages should render the same in both MDX 2.0.0-next.7 and 1.16.6. This isn't rendering the image in MDX 2.0.0-next.7

```
import { Link } from "gatsby";

# Image issues

![Test](../images/gatsby-astronaut.png)

<Link to="/page/">Second Page</Link>

```

![2020-08-27_11-01-42](https://user-images.githubusercontent.com/378557/91478631-0dd2bb80-e855-11ea-9c96-8779912cf389.png)

### Actual result

Image does not render.

![2020-08-27_10-58-12](https://user-images.githubusercontent.com/378557/91478577-f8f62800-e854-11ea-928a-d3ceb5da42a2.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 81.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.12 => 2.24.12
    gatsby-image: ^2.4.16 => 2.4.16
    gatsby-plugin-manifest: ^2.2.4 => 2.2.4
    gatsby-plugin-mdx: ^1.0.0 => 1.0.22
    gatsby-plugin-offline: ^2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sharp: ^2.6.29 => 2.6.29
    gatsby-remark-images: ^3.3.27 => 3.3.27
    gatsby-source-filesystem: ^2.3.25 => 2.3.25
    gatsby-transformer-sharp: ^2.5.13 => 2.5.13
  npmGlobalPackages:
    gatsby-cli: 2.12.29
```

**Comment by patrickarlt** [comment]
I'm again unsure if this is a Gatsby or MDX issue so it if filed in both repos. https://github.com/mdx-js/mdx/issues/1240

**Comment by patrickarlt** [comment]
Upon furthur inspection it looks like `gatsby-remark-images` creates `html` nodes for the new images https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/index.js#L463. Since MDX v2 doesn't support the `html` node type anymore I think this has to be rewritten.

**Comment by patrickarlt** [comment]
Looks like this will also affect these packages which also use either the `html` or `jsx` node type.

* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-code-repls/src/index.js#L37
* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-copy-linked-files/src/index.js#L223
* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-graphviz/src/index.js#L51
* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images-contentful/src/index.js#L280
* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-katex/src/index.js#L15
* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/index.js#L72
* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-responsive-iframe/src/index.js#L81

**Comment by vladar** [comment]
Could be potentially fixed in #26660 (will be merged/published somewhere in the beginning of the next week)

**Comment by isaobushi** [comment]
Any update on the matter ?

**Comment by jerelmiller** [comment]
Our team also just encountered the same issue. We are migrating a pretty big website over to Gatsby + MDX and noticed our images are no longer showing up. Are there contributions currently being made to support MDX v2? Or alpha/next versions of Gatsby available to try out? 
=

**Comment by LekoArts** [comment]
To keep things organized I'll close this in favor of an umbrella issue. Please repost your findings here: https://github.com/gatsbyjs/gatsby/issues/25068

Thanks!

**Comment by yougotashovel** [comment]
> Our team also just encountered the same issue. We are migrating a pretty big website over to Gatsby + MDX and noticed our images are no longer showing up. Are there contributions currently being made to support MDX v2? Or alpha/next versions of Gatsby available to try out?

Did you ever find a fix for this issue? Current experiencing it.

**Comment by jerelmiller** [comment]
@yougotashovel Yes and no. We ended up creating our own custom plugin to polyfill the behavior. If you're curious, you can check it out here: https://github.com/newrelic/docs-website/blob/develop/plugins/gatsby-remark-mdx-v2-images/index.js

Config is here: https://github.com/newrelic/docs-website/blob/fb9ab7e4c73191d6c4587d08453ddeefa631858f/gatsby-config.js#L294-L296
