### ISSUE TITLE
Cannot retrieve defined global variables with plugins.define({...})

### ISSUE THREAD

**Issue by jonathanlinat** [gatsbyjs/gatsby#26676]
## Description

I defined global variables into `global-config.js` file but when I try to retrieve them in a specific component, IDE's console tells me that the specified variables don't exist.

### Steps to reproduce

**global-node.js**

```javascript
exports.onCreateWebpackConfig = ({ stage, actions, plugins }) => {
  actions.setWebpackConfig({
    plugins: [
      plugins.define({
        VERSION: JSON.stringify(require("./package.json").version),
        BUILD_DATE: JSON.stringify(new Date()),
      }),
    ],
  })
}
```

**my-component.jsx**

```javascript
console.log(`v${VERSION} (${BUILD_DATE})`)
```

### Expected result

Browser's console

`v0.1.0 (2020-08-28T05:54:04.592Z)`

### Actual result

IDE's console

```bash
6:17  error  'VERSION' is not defined     no-undef
6:29  error  'BUILD_DATE' is not defined  no-undef

✖ 2 problems (2 errors, 0 warnings)
```

### Environment

```bash
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    npm: 6.14.7 - ~/.nvm/versions/node/v12.16.3/bin/npm
  npmPackages:
    gatsby: 2.24.49 => 2.24.49 
    gatsby-cli: 2.12.88 => 2.12.88 
    gatsby-plugin-alias-imports: 1.0.5 => 1.0.5 
    gatsby-plugin-mdx: 1.2.35 => 1.2.35 
    gatsby-plugin-page-creator: 2.3.23 => 2.3.23 
    gatsby-plugin-styled-components: 3.3.10 => 3.3.10 
    gatsby-source-filesystem: 2.3.25 => 2.3.25 
```

**Comment by jonathanlinat** [comment]
Okay, I figured out that I can retrieve those variables adding `// eslint-disable-next-line` before using `console.log()` method.

```javascript
// eslint-disable-next-line
console.log(`v${VERSION} (${BUILD_DATE})`)
```

Nevertheless, isn't that a little bit weird? Isn't there any other viable alternative to this workaround?

Ref. https://github.com/gatsbyjs/gatsby/issues/10637#issuecomment-449737060

**Comment by jonathanlinat** [comment]
Well, that workaround might be a viable alternative:

**gatsby-config.js**

```javascript
  actions.setWebpackConfig({
    plugins: [
      plugins.define({
        global: {
          VERSION: JSON.stringify(require("./package.json").version),
          BUILD_DATE: JSON.stringify(new Date()),
        }
      }),
    ],
  })
```

**my-component.jsx**

```javascript
console.log(`v${global.VERSION} (${global.BUILD_DATE})`)
```

**Comment by vladar** [comment]
Glad that you've figured this out! Eslint is not aware of your webpack config. So for eslint those variables are just undefined javascript variables.

As stated, this is slightly tangential to Gatsby, and it seems like you have sorted this out already so I am closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. 

Thanks for using Gatsby :muscle:
