### ISSUE TITLE
Gatsby plugin not working

### ISSUE THREAD

**Issue by tajchana1** [gatsbyjs/gatsby#26683]
npm install --save gatsby-plugin-typography
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.3.3 requires a peer of react-refresh@^0.8.2 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of gatsby@2.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react-dom@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN theme-ui@0.2.52 requires a peer of @mdx-js/react@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

+ gatsby-plugin-typography@2.5.10
updated 1 package and audited 1992 packages in 7.988s

150 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by vladar** [comment]
I'd be happy to help but it is not clear what your issue actually is. The log you copied doesn't say much about your actual problem, unfortunately. So I am closing this but if you still need help, please open a new issue and follow the steps described in our docs here: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

Thanks for using Gatsby 💜
