### ISSUE TITLE
Themed Plugin not working

### ISSUE THREAD

**Issue by tajchana1** [gatsbyjs/gatsby#26695]
Dear Team,

Please advise.

I have my dev site running ok. I am having issues with installing themed plugins on my site.  When I type in the below for an example:- 

```
>> npm i theme-ui gatsby-plugin-theme-ui
```

i get the error message

```
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.3.3 requires a peer of react-refresh@^0.8.2 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of gatsby@2.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-interface@0.0.166 requires a peer of react-dom@16.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN theme-ui@0.2.52 requires a peer of @mdx-js/react@^1.0.0 but none is installed. You must install peer dependencies yourself.

+ theme-ui@0.2.52
+ gatsby-plugin-theme-ui@0.3.0
added 1 package from 1 contributor, updated 1 package and audited 2095 packages in 12.069s

151 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by LekoArts** [comment]
Thank you for opening this!

The log you showed here said that it successfully installed both plugins that you wished to install. You only see peerDependency warnings which you can ignore as they typically don't cause any harm. However, you should make sure to install `theme-ui@0.3.1` as that's the latest version (https://www.npmjs.com/package/theme-ui). You installed `+ theme-ui@0.2.52` so give it a retry with `npm install theme-ui@latest`.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
