### ISSUE TITLE
Future of the Site Showcase Validator

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#26690]
## Summary

With the move of everything over to Gatsbyjs.com and related projects, the site showcase & starter showcase submission process has closed while things are being updated. As well, as the source files for the showcases are now inside WordPress, the yaml files are stale, and the Site Showcase validator I created is now going to be stagnant.

As well, as no one really used it to clean up & track entries other than me, so for the time being I'm suggesting getting rid of it as I am not going to maintain it and it's just going to waste CPU cycles as it is not pulling from up to date data.

**Comment by sidharthachatterjee** [comment]
Hey Ben! Long time, no see...

Firstly, thank you for both building the Site Showcase validator and running it. I think it's served a lot of value in keeping the showcases clean over the years. 

I think we might be able to find a way to repurpose this but I'll defer to @gillkyle who owns the new website. 

In the mean time, I do agree that disabling it for now might be a good next step.

**Comment by gillkyle** [comment]
These are good points, thanks @lannonbr! I think the short term is remove the action (which I did in #26724), and medium/long term is re-implementing something similar ourselves or running it manually in the future to prune old sites from the showcase.

**Comment by gillkyle** [comment]
I'll close this with the short term fix implemented. Medium/long term will come further down the road.
