### ISSUE TITLE
[using-page-transitions] build fails

### ISSUE THREAD

**Issue by dustinhorton** [gatsbyjs/gatsby#2669]
```console
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  4 | 
  5 | const Cat = ({ transition }) => (
> 6 |   <div style={transition.style}>
    |                          ^
  7 |     <h1>meow</h1>
  8 |     <div>
  9 |       <Link to="/">Go to home</Link>


  WebpackError: Cannot read property 'style' of undefined
  
  - cat.js:6 Cat
    src/pages/cat.js:6:26
  
  - ReactCompositeComponent.js:306 ReactCompositeComponentWrapper._constructComponentWithoutOwner
    ~/react-dom/lib/ReactCompositeComponent.js:306:1
  
  - ReactCompositeComponent.js:282 ReactCompositeComponentWrapper._constructComponent
    ~/react-dom/lib/ReactCompositeComponent.js:282:1
  
  - ReactCompositeComponent.js:185 ReactCompositeComponentWrapper.mountComponent
    ~/react-dom/lib/ReactCompositeComponent.js:185:1
  
  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1
  
  - ReactMultiChild.js:234 ReactDOMComponent.mountChildren
    ~/react-dom/lib/ReactMultiChild.js:234:1
  
  - ReactDOMComponent.js:657 ReactDOMComponent._createContentMarkup
    ~/react-dom/lib/ReactDOMComponent.js:657:1
  
  - ReactDOMComponent.js:524 ReactDOMComponent.mountComponent
    ~/react-dom/lib/ReactDOMComponent.js:524:1
  
  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1
  
  - ReactMultiChild.js:234 ReactDOMComponent.mountChildren
    ~/react-dom/lib/ReactMultiChild.js:234:1
```

[Looks like the preview may have failed in the PR too](https://github.com/gatsbyjs/gatsby/pull/2557#issuecomment-339480744)? Not exactly sure that's what's happening there.

A quick workaround was to swap:

```jsx
style={transition.style}
```

for:

```jsx
style={(typeof transition != 'undefined') ? transition.style : null}
```

but this check should happen just once elsewhere…haven't quite figured out where.

### Edit

That 'workaround' makes the build pass, but the resulting site isn't functional. When clicking 'local' links:

```console
gatsby-browser.js:21 Uncaught TypeError: Cannot read property 'component' of undefined
    at gatsby-browser.js:21
    at t.render (Transition.js:372)
    at p._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at p._renderValidatedComponent (ReactCompositeComponent.js:819)
    at performInitialMount (ReactCompositeComponent.js:359)
    at p.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at Object.updateChildren (ReactChildReconciler.js:119)
    at v._reconcilerUpdateChildren (ReactMultiChild.js:209)
    at v._updateChildren (ReactMultiChild.js:308)
```

**Comment by andykenward** [comment]
Having the same issue. To me it looks like the example is using props that are only available in development. 

In [gatsby-browser.js#L21](https://github.com/gatsbyjs/gatsby/blob/1adad2d24d661117ea80d51ece67169464269022/examples/using-page-transitions/gatsby-browser.js#L21) `props.pageResources` is needed. But when you do a production build this isn't available.

From what I can tell from the source code in [`packages/gatsby/cache-dir/root.js`](https://github.com/gatsbyjs/gatsby/blob/1adad2d24d661117ea80d51ece67169464269022/packages/gatsby/cache-dir/root.js#L141) passes `pageResources` as a prop to ComponentRenderer. But on a production build it uses [`packages/gatsby/cache-dir/production-app.js`](https://github.com/gatsbyjs/gatsby/blob/1adad2d24d661117ea80d51ece67169464269022/packages/gatsby/cache-dir/production-app.js#L162) which does not. [`loader.getResourcesForPathname`](https://github.com/gatsbyjs/gatsby/blob/1adad2d24d661117ea80d51ece67169464269022/packages/gatsby/cache-dir/loader.js#L283) does return `pageResources` but if you pass that in `production-app.js` same as `root.js` it then doesn't show the correct page data on a url change.

Could we not just move the transition logic to [`layouts/index.js#L55`](https://github.com/gatsbyjs/gatsby/blob/1adad2d24d661117ea80d51ece67169464269022/examples/using-page-transitions/src/layouts/index.js#L55) ?

**Comment by dustinhorton** [comment]
cc @stevensurgnier : ]

**Comment by SamHellawell** [comment]
@KyleAMathews these seems to be an issue again as of V2
