### ISSUE TITLE
[gatsby-image] Cannot use object-fit: contain; on an <Img>

### ISSUE THREAD

**Issue by dantman** [gatsbyjs/gatsby#26702]
## Description

It doesn't seem to be possible to use `object-fit: contain;` with a gatsby-image `<Img>`.

### Steps to reproduce

Try using `objectFit="contain"` on an `<Img>`.

### Expected result

The image should use `object-fit: contain;` or otherwise be available to have that css applied to it.

### Actual result

Every `<img>` element outputted by gatsby-image has `object-fit: cover;` applied to it in the inline `style=""` that cannot be easily overridden.

**Comment by polarathene** [comment]
Use the [`gatsby-image` prop](https://www.gatsbyjs.com/plugins/gatsby-image/#gatsby-image-props) `imgStyle`, both the main image and placeholder image spread that over their internal style prop defaults.

```jsx
<GatsbyImage <other-props> imageStyle={{objectFit: `cover`}} />
```

**Comment by sidharthachatterjee** [comment]
Couldn't have answered this better than Brennan. Thank you @polarathene!

**Comment by SabbeRubbish** [comment]
> Use the [`gatsby-image` prop](https://www.gatsbyjs.com/plugins/gatsby-image/#gatsby-image-props) `imgStyle`, both the main image and placeholder image spread that over their internal style prop defaults.
> 
> ```js
> <GatsbyImage <other-props> imageStyle={{objectFit: `contain`}} />
> ```

Make sure to use `imgStyle` and not `imageStyle` like in your code snippet. **Works like a charm!**

Just too bad it doesn't use the GraphQL options like so:
```
 childImageSharp {
    gatsbyImageData(transformOptions: {fit: CONTAIN}, layout: FULL_WIDTH)
}
```
