### ISSUE TITLE
VS Code debugger broken (Exception: Inspector is already activated)

### ISSUE THREAD

**Issue by aaronadamsCA** [gatsbyjs/gatsby#26708]
Gatsby has recently stopped working with defined debugger launch configurations in Visual Studio Code.

I don't know if this was due to a change in Gatsby or in VS Code and/or its extensions; I just know it worked at some point in the last couple of months, and now it doesn't.

### Steps to reproduce

**Update:** I can reproduce this issue in a starter repo using the exact launch configuration [from the docs](https://www.gatsbyjs.com/docs/debugging-the-build-process/#vs-code-debugger-manual-config):

`launch.json`

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Gatsby develop",
      "type": "node",
      "request": "launch",
      "protocol": "inspector",
      "program": "${workspaceRoot}/node_modules/.bin/gatsby",
      "autoAttachChildProcesses": true,
      "args": ["develop", "--inspect-brk"],
      "stopOnEntry": false,
      "runtimeArgs": ["--nolazy"],
      "sourceMaps": false
    },
    {
      "name": "Gatsby build",
      "type": "node",
      "request": "launch",
      "protocol": "inspector",
      "program": "${workspaceRoot}/node_modules/.bin/gatsby",
      "args": ["build"],
      "stopOnEntry": false,
      "runtimeArgs": ["--nolazy"],
      "sourceMaps": false
    }
  ]
}
```

This is the line throwing an unhandled exception:

https://github.com/gatsbyjs/gatsby/blob/7e83aced6b5c9fc421fd8f3b67b77269a6b59f09/packages/gatsby/src/commands/develop-process.ts#L67

This is the exception:

```text
Exception has occurred: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
  at Object.open (inspector.js:137:11)
 ```

Some things I've tried adjusting without success:

- Changing `"type": "node"` to `"type": "pwa-node"` and/or setting `debug.node.useV3` to `true`; either one should cause VS Code to use [the new Node.js debugger](https://github.com/microsoft/vscode-js-debug)
- Moving `"--inspect-brk"` to `runtimeArgs` or removing it entirely

### Workaround

Auto-attach is not affected. If I set VS Code setting `debug.node.autoAttach` to `true` and then run `node --nolazy node_modules/.bin/gatsby develop --inspect-brk` in the terminal, the debugger attaches and Gatsby runs without exception.

### Environment

```text
  System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: ^2.24.52 => 2.24.52
    gatsby-source-sanity: ^6.0.3 => 6.0.3
```

**Comment by aaronadamsCA** [comment]
@wardpeet I've updated to `gatsby@2.24.53` and I'm still experiencing the same issue.

**Comment by aaronadamsCA** [comment]
@LekoArts / @wardpeet Can you please reopen this ticket? #26669 did not resolve the issue.

It's still broken with both the current Node.js debugger:

![image](https://user-images.githubusercontent.com/1505561/92091837-97dcd000-edd1-11ea-9e5a-5efbb8376efb.png)

And the new upcoming Node.js debugger:

![image](https://user-images.githubusercontent.com/1505561/92091922-b17e1780-edd1-11ea-8776-e587afbc5b21.png)

`gatsby info --clipboard`:

```text
  System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: ^2.24.53 => 2.24.53
    gatsby-source-sanity: ^6.0.4 => 6.0.4
```

I've put a reproduction here on branch `issue-26708` here: https://github.com/shopnishe/gatsby-issues/tree/issue-26708

**Comment by wardpeet** [comment]
Re-opened, i'll have a look

**Comment by connor4312** [comment]
Hi, I build the JS debugger.

Two things:

- @aaronadamsCA passing `--inspect-brk` to Gatsby is probably unnecessary. We --require a 'bootloader' script via NODE_OPTIONS which sets up debugging before the process (i.e. Gatsby) gets activated.
- Throwing the error is new behavior as of https://github.com/nodejs/node/commit/dd5f209213a2b75bb386b44c296a059fc10dfb02. You can detect that the inspector is already open by seeing if `inspector.url() !== undefined` ([eg](https://github.com/microsoft/vscode-js-debug/blob/c6cea4175b54a6c54ae29720a29b940cb2c02257/src/targets/node/bootloader.ts#L79-L89))

**Comment by aaronadamsCA** [comment]
Amazing, thank you @connor4312, removing `--inspect-brk` does indeed bypass the error.

@wardpeet, at this point this might just be a documentation thing? Compared to [the current docs](https://github.com/gatsbyjs/gatsby/blame/b1745891a0c33eca2a4ae874129d0976d243b38e/docs/docs/debugging-the-build-process.md#L86-L115) it seems this is now the better recommendation for `launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Gatsby develop",
      "type": "pwa-node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/.bin/gatsby",
      "args": ["develop"],
      "runtimeArgs": ["--nolazy"],
      "console": "integratedTerminal"
    },
    {
      "name": "Gatsby build",
      "type": "pwa-node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/.bin/gatsby",
      "args": ["build"],
      "runtimeArgs": ["--nolazy"],
      "console": "integratedTerminal"
    }
  ]
}
```

In addition to removing `--inspect-brk`, other changes include:

- Updated `"type": "pwa-node"` to opt into the new Node.js debugger; it ships with VS Code stable, works well, and will soon be the only option, so IMO it's already the right choice
- Removed `"protocol"` because it does nothing with `"request": "launch"`
- Removed `"autoAttachChildProcesses"` and `"stopOnEntry"` because there's no need to restate defaults
- Removed `"sourceMaps": false`, I don't see any documented/ticketed reason to recommend this
- Added `"console": "integratedTerminal"` to be able to see Gatsby console output

**Comment by aaronadamsCA** [comment]
Should maybe still make the core change to check if the inspector is already running, but PR submitted to update the docs.

**Comment by connor4312** [comment]
Those suggested changes look good. Technically you don't need `type: "pwa-node"` to opt in since the June release, but having that allows the user to specify more/new options without VS Code complaining they're invalid 🙂

**Comment by connor4312** [comment]
Also, setting `showAsyncStacks: false` in `Gatsby: build` will speed up build times in the range of 20-40% -- less bookkeeping for V8, if you don't expect people to be debugging Gatsby: build very much. Alternately, it can be a [build task](https://code.visualstudio.com/docs/editor/tasks).

**Comment by AnalogMemory** [comment]
If anyone is still getting the error even with the updated launch.json config. 

Opening VSCode via the terminal with force it to have context on the path for node.

Or if you don't want to have to remember to do that add this to each config
`"runtimeExecutable": "/usr/local/bin/node",`

**Comment by wardpeet** [comment]
What do we need to do to fix the issue and close it? Anything on gatsby's end?

**Comment by connor4312** [comment]
@wardpeet removing any manual --inspect or --inspect-brk flag that you pass should be sufficient https://github.com/gatsbyjs/gatsby/issues/26708#issuecomment-686604631

**Comment by connor4312** [comment]
@wardpeet the one change would probably be to not try to reactive debugging if the process is already being debugged, preventing a crash https://github.com/gatsbyjs/gatsby/issues/26708#issuecomment-686604631

**Comment by connor4312** [comment]
I think this is still valid

**Comment by LekoArts** [comment]
If anyone wants to pick this up, as per @connor4312 it would make sense to leverage `inspector.url`:

> Throwing the error is new behavior as of https://github.com/nodejs/node/commit/dd5f209213a2b75bb386b44c296a059fc10dfb02. You can detect that the inspector is already open by seeing if `inspector.url() !== undefined` ([eg](https://github.com/microsoft/vscode-js-debug/blob/c6cea4175b54a6c54ae29720a29b940cb2c02257/src/targets/node/bootloader.ts#L79-L89))

To fix the issue:

> the one change would probably be to not try to reactive debugging if the process is already being debugged, preventing a crash

**Comment by connor4312** [comment]
Not stale :)

**Comment by connor4312** [comment]
Not stale

**Comment by connor4312** [comment]
Not stale

**Comment by aaronadamsCA** [comment]
@wardpeet, could we please get a **not-stale** on this?

I haven't been pushing the issue, since I haven't needed to debug any Gatsby code for several weeks; but it is still worth fixing when someone gets a chance. It's especially useful for heavy Node API work.

**Comment by connor4312** [comment]
It was a simple fix, so I put in a PR.
