### ISSUE TITLE
Gatsby storybook tutorial does not support CSS modules

### ISSUE THREAD

**Issue by EliotSlevin** [gatsbyjs/gatsby#26714]
## Description

Following the [visual testing tutorial ](https://www.gatsbyjs.com/docs/visual-testing-with-storybook/) from gatsbyjs.com ends with a storybook setup that does not support CSS modules. 

Here is a button component rendering via `gatsby develop`
<img width="323" alt="Screen Shot 2020-08-31 at 4 36 08 PM" src="https://user-images.githubusercontent.com/4987326/91683417-ba3fd500-eba8-11ea-80dd-6b79f800d83f.png">

And here is the button rendering in storybook - the styles from the css modules are missing
<img width="488" alt="Screen Shot 2020-08-31 at 4 36 13 PM" src="https://user-images.githubusercontent.com/4987326/91683434-c3c93d00-eba8-11ea-92dd-b19129ada660.png">

### Steps to reproduce

[Here is a minimal repo ](https://github.com/EliotSlevin/Storybook-gatsby-no-css-modules) to reproduce, just run gatsby, and storybook to see the differences.

### Expected result

The button is styled green in storybook, with the css module's styles applied. 

### Actual result

The component in storybook has no styles - the dom structure looks like this, with no class applied. 
`<div>I should be a green button</div>`

Where as the dom structure looks like this when `gatsby develop`
`<div class="button-module--button--2z6oN">I should be a green button</div>`

### Environment

```
 System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 79.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.24.50 => 2.24.50
```

I'd love to help to fix this issue, storybook or any visual testing tool would be so handy to help share a UI library I'm working on with the wider design team. Webpack config and babel is just a topic I know very little on, so not really sure where to start :( 

Cheers

**Comment by EliotSlevin** [comment]
I think I got something working! 

Adding this line to `main.js` seems to have worked. 
```
    config.module.rules[3].use[1].options = { 
      modules: true,
      importLoaders: 1 
    }
```

I'M SO HAPPY

**Comment by EliotSlevin** [comment]
I would raise a PR to add this to the tutorial, but it feels very fragile? If there are more rules added by storybook, or the order of the rules change it'll all break?

**Comment by EliotSlevin** [comment]
Yeah very fragile - I just replicated this approach onto my existing project, and a storybook update has changed their webpack config to add a bunch more rules, making the css-loader move order. Managed to get it working with this snippet.

```
    config.module.rules[7].use[1].options = { 
      modules: true,
      importLoaders: 1 
    }
```

When Storybook uses it's css loader, it looks like this in the config.
```
//config.module.rules[7]

  {
    loader: '/Users/eliotslevin/Desktop/marketing-website/node_modules/@storybook/core/node_modules/css-loader/dist/cjs.js',
    options: { importLoaders: 1 }
  },
```

All you need to do to get it to work is change that config to look like this
```
  {
    loader: '/Users/eliotslevin/Desktop/marketing-website/node_modules/@storybook/core/node_modules/css-loader/dist/cjs.js',
    options: { modules: true, importLoaders: 1 }
  },
```


Would be good if the code explicitly only updated the css-loader rule, no matter where it was in the order....

**Comment by EliotSlevin** [comment]
Also had an issue rendering components which used gatsby-link - _in the built storybook_. For some reason didn't happen in the live storybook. Would throw `__BASE_PATH__ not defined`. 

Added these lines to preview.js and seems to have fixed it. Not sure why though, I threw them in on a hunch based off another issue. 

```
global.__PATH_PREFIX__ = ``
global.__BASE_PATH__= ``
```

**Comment by vicnicius** [comment]
I did manage to only update the css-loader rule by doing this:

```js
const ruleCssIndex = config.module.rules.findIndex(rule => rule.test.toString() === '/\\.css$/');
config.module.rules[ruleCssIndex].use.map(item => {
  If (item.loader && item.loader.includes('/css-loader/')) {
    item.options.modules = true;
    item.options.importLoaders = 1;
  }
  return item;
})
```
I don't think that's a proper solution, though.

After that, I had to add all global CSS modules imported by components manually to preview.js. In a sense, this last bit was due to a user error, as we were using `.module.css` and `.css` indistinctively, but I'd expect either to work inside storybook just like they do outside.

**Comment by EliotSlevin** [comment]
> all global CSS modules

What do you mean by this? I thought all css modules had to be scoped by their nature. Or do you mean a css module which you re-use among many different components? (like something to define typography?).

I have some global css (setting up the fonts and reset border box) but I have that as a normal `.css` file, imported in a wrapper component which I had to add to preview.js as well.

**Comment by vicnicius** [comment]
Yeah, I mean a reusable CSS module. Before, it wasn't necessary to import them if the component in the story was already doing it. After the tweak I did to make CSS modules work, you have to import them manually.

So if you had:

```jsx
// Component.js
// ...
import './component.css'
export default function({children}) {
  return (<div className='some-class-in-component.css'>{children}</div>);
}
```
This would work without the need to import `component.css` if I had `Component.js` in my story and it only had CSS classes defined in `component.css`.

After the change, you have to add it manually to preview.js, even if you do import the component that is importing the global CSS.

**Comment by EliotSlevin** [comment]
While I'm not sure of the best way to fix this, and what we should suggest - I don't want to just let this issue go stale. 

I've created a PR adding a line to the gatsby storybook documentation page, just saying that Supporting CSS modules require a few more changes to your webpack config - and linking to this issue. 

https://github.com/gatsbyjs/gatsby/pull/27461
