### ISSUE TITLE
Gatsby Cloud menu overlap 

### ISSUE THREAD

**Issue by tdelgio** [gatsbyjs/gatsby#26739]
## Description
On Gatsby Cloud the user menu is overlapping with the contributors image.

### Steps to reproduce
Log in to Gatsby cloud and display de user menu to see the problem. The image attached shows the issue.

Chrome
<img width="304" alt="Screen Shot 2020-09-01 at 11 56 53" src="https://user-images.githubusercontent.com/50454716/91867631-3ccca100-ec4a-11ea-94ee-8105ddf5bb76.png">

Firefox
<img width="299" alt="Screen Shot 2020-09-01 at 11 52 19" src="https://user-images.githubusercontent.com/50454716/91867121-a5674e00-ec49-11ea-8ffe-63e7637a9346.png">

### Expected result

The Menu should have a higher z-index.

### Actual result

Overlapping menu.

### Environment

System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.135
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.11 => 2.24.11
    gatsby-image: ^2.4.6 => 2.4.6
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6
    gatsby-plugin-google-tagmanager: ^2.3.11 => 2.3.11
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5
    gatsby-plugin-manifest: ^2.4.21 => 2.4.21
    gatsby-plugin-modal-routing: ^1.2.0 => 1.2.0
    gatsby-plugin-offline: ^3.2.8 => 3.2.8
    gatsby-plugin-react-css-modules: ^2.3.4 => 2.3.4
    gatsby-plugin-react-helmet: ^3.3.3 => 3.3.3
    gatsby-plugin-sharp: ^2.6.10 => 2.6.10
    gatsby-plugin-styled-components: ^3.3.3 => 3.3.3
    gatsby-remark-images-contentful: ^2.3.4 => 2.3.4
    gatsby-source-contentful: ^2.3.14 => 2.3.14
    gatsby-source-filesystem: ^2.3.10 => 2.3.10
    gatsby-transformer-sharp: ^2.5.4 => 2.5.4
    gatsby-transformer-sqip: ^2.3.10 => 2.3.10
  npmGlobalPackages:
    gatsby-cli: 2.12.65

**Comment by fk** [comment]
cc @Elanhant

**Comment by fk** [comment]
Thank you @tdelgio! 🙏 🤗

**Comment by Elanhant** [comment]
This should be fixed now.
