### ISSUE TITLE
Tutorial Part 4 - Unknown field `siteMetadata` on type `Site`

### ISSUE THREAD

**Issue by kildareflare** [gatsbyjs/gatsby#2674]
Followed the tutorial step by step. And I get the following error related to the graph query.

```
  GraphQL Error Unknown field `siteMetadata` on type `Site`
  file: C:/Code/Projects/bss3/prt4-data/src/layouts/index.js

  1 |
  2 |   query LayoutQuery {
  3 |     site {
> 4 |       siteMetadata {
    |       ^
  5 |         title
  6 |       }
  7 |     }
  8 |   }
```

As per tutorial, this is defined in  `gatsby-config.js` which is in the root.
![image](https://user-images.githubusercontent.com/5456669/32149287-a79eb4fc-bd66-11e7-9fe0-b6f6924244c9.png)

Repeated more than once, starting from scratch.
npm: 5.4.2
node: 6.11.3

**Comment by kildareflare** [comment]
I resolved this by including this line in `layouts\index.js`
`import graphql from 'graphql'`

But, weirdly, if I then remove that line, it still works....

**Comment by KyleAMathews** [comment]
Perhaps you didn't restart `gatsby develop` after adding `gatsby-config.js`? The schema doesn't get rebuilt until then so any queries to siteMetadata would fail.

**Comment by sebastienfi** [comment]
`import graphql from 'graphql'` doesn't seems either required nor a good idea as it will include a 400Kb file to your build. Kyle's suggestion is the way to go!

**Comment by tcjcodes** [comment]
I had the same issue- my project was fine but had to upgrade my version of npm to the latest 5.5.1, delete and re-install node_modules. I already had node v6.11.4 installed. Works now!

**Comment by martinpsz** [comment]
Followed part 4 instructions exactly...in fact, I copied and pasted them and restarted gatsby develop. Received the following error:

×
TypeError: Cannot read property 'site' of undefined
new _default
src/layouts/index.js:20
  17 | >
  18 |   <Link to={`/`}>
  19 |     <g.H3 marginBottom={rhythm(2)} display={`inline-block`}>
> 20 |       {data.site.siteMetadata.title}
  21 |     </g.H3>
  22 |   </Link>
  23 |   <Link className={linkStyle} to={`/about/`}>


 Any ideas on how to fix. Have latest version 8.9.1 of node and 5.5.1 of npm.

**Comment by KyleAMathews** [comment]
If you log the data what do you get? What happens when you try the same query in graphiql?

**Comment by martinpsz** [comment]
This is the error that shows up when  enter "gatsby develop": 

GraphQL Error There was an error while compiling your site's GraphQL queries.
 Invariant Violation: GraphQLParser: Unknown field `siteMetadata` on type `Site`. Source: document `AboutQuery` file: `GraphQL request`.

Haven't explored graphiql.

**Comment by KyleAMathews** [comment]
What is the path to your gatsby-config.js? Could you paste it here?

**Comment by martinpsz** [comment]
gatsby-config.js is located on the same level as my 'src' file. The files are .cache, .vscode, node_modules, public, src, .gitignore, gatsby.config.js and so on. This is the path: 
~/Desktop/tutorial-part-four/gatsby.config.js

**Comment by martinpsz** [comment]
Hi Kyle,

Any thoughts on how I can address the issue I raised?

Thanks for your work on Gatsby JS. I am new to static site generators and am looking forward to working with Gatsby.

**Comment by kildareflare** [comment]
Hi @martinpsz , this is probably not your problem, since you are following the tutorial. However for future reference...  

When I see that error, 9 times out of 10 it is because another graphQL query in my app is broken and does not compile. E.g. my app pulls data from prismic. If I have not formatted it correctly, I will see the error you are seeing. What I do then, is start graphiql and format the query until it works. And then update the query in my source to match.

you could start by checking that your metadata query works.
You can find graphiql here:  localhost:8000/___graphql

CTRL + SPACE will show a list of possible fields 
CTRL + ENTER will run the query

**Comment by kildareflare** [comment]
@martinpsz have you got any further with this?

**Comment by Jaikant** [comment]
@martinpsz I hit this precise issue, when a different query failed. 
The query failed because the JSON was malformed. JSON does not support trailing commas.

**Comment by jeff-jk** [comment]
@kildareflare @martinpsz Maybe try a `yarn install` before `gatsby develop`?

**Comment by snak1t** [comment]
@martinpsz I think its too late, but I still want to reply. Maybe someone else find it useful. The point is that you name your file `gatsby.config.js` and not `gatsby-config.js`. Have the same issue, and after renaming everything works as expected.

**Comment by mccrodp** [comment]
I was getting this just now also, I had ran:
````
node -v
v8.4.0
````
````
npm -v
5.3.0
````
So I ran: `npm install npm@latest -g` to get npm v `5.6.0`, deleted `node_modules`, re-ran `npm install` and then `gatsby develop` and....just stopped. Still getting the error :(

**Comment by mccrodp** [comment]
🤕 🌴 In my case it was path to my `gatsby-config.js` that was wrong, make sure it is in the root and not `/src/` dir as it was in my case. You see this error when it's in the wrong dir, thanks Kyle!

>What is the path to your gatsby-config.js? Could you paste it here?

**Comment by KyleAMathews** [comment]
I added this PR https://github.com/gatsbyjs/gatsby/pull/4101 that checks if your gatsby-config.js is in the src directory and politely tells you to move it to the correct place :-) hopefully that helps people in the future who make this very understandable mistake!

**Comment by fahrradflucht** [comment]
@KyleAMathews This addresses one issue but for me and a couple of other people the solution was to rename `gatsby-config.js` to `gatsby.config.js` an idea why that is? This seems to be against everything that is noted anywhere...

**Comment by amitrathik** [comment]
> 🤕 🌴 In my case it was path to my `gatsby-config.js` that was wrong, make sure it is in the root and not `/src/` dir as it was in my case. You see this error when it's in the wrong dir, thanks Kyle!
> 
> > What is the path to your gatsby-config.js? Could you paste it here?

I stumbled into this issue today. Turned out i had the file set to "gatsby.config.js". Once I switched it to gatsby-config.js the error was resolved...

**Comment by rfox12** [comment]
Does the polite warning occur before any other checks?  I didn't notice it and I ran a brand new Gatsby 2.0 and ran into this where I had the config inside src
