### ISSUE TITLE
ERROR #85901  GRAPHQL : Unexpected error value: "failed to process

### ISSUE THREAD

**Issue by KamranMaqbool** [gatsbyjs/gatsby#26765]
"gatsby develop"
not download .png image file

give me error
![TaskImgError](https://user-images.githubusercontent.com/53546053/92027528-1c9cff00-ed7c-11ea-8bf5-b8e93db9b183.png)

tihis same error on some other pages

**My GraphQL Query like this**
`query GET_PAGE($id: ID!) {
		wpgraphql {
			page(id: $id) {
				id
				pageId
				uri
				title
				content
				featuredImage {
					sourceUrl
					altText
					imageFile {
						childImageSharp {
							fluid(maxWidth: 1200, maxHeight:600, quality: 80, cropFocus: CENTER) {
								...GatsbyImageSharpFluid_withWebp_noBase64
							}
						}
					}
				}
}
}`

**Wordpress GraphQL Query**
![wpQuery](https://user-images.githubusercontent.com/53546053/92028268-325ef400-ed7d-11ea-9b52-b976b7ee57ab.png)

**Gatsby GraphQL Query**
![wpqueryone](https://user-images.githubusercontent.com/53546053/92028351-53bfe000-ed7d-11ea-8a03-00403a072fc5.png)

before above query work file but now it's give me error when click on imageFile node like below

![Screenshot from 2020-09-03 00-15-28](https://user-images.githubusercontent.com/53546053/92028432-79e58000-ed7d-11ea-9dd8-70240979fa9d.png)

imageFile {} object only show in gatsbyjs wpgraphQL but why not show in WPGraphQL Query.i don't understand what this happen
some days ago this working perfect

### Environment
Ubuntu OS
    "gatsby": "^2.24.50",
    "gatsby-image": "^2.4.16",
    "gatsby-plugin-sharp": "^2.6.28",
    "gatsby-source-graphql": "^2.7.2",
    "gatsby-transformer-sharp": "^2.5.13",

**Comment by MKlblangenois** [comment]
I've the same issue, process return error when he's trying to download PNG file

``` ERROR 

Processing /Users/loganblangenois/Documents/Sites/Gatsby/Clients/gatsby-studyfr-v5/.cache/caches/gatsby-source-wordpress-experimental/a1aa62e5163bc8656a334d10837722b0/Warmadewa University Logo.png failed

Original error:

  WorkerError: Processing /Users/loganblangenois/Documents/Sites/Gatsby/Clients/gatsby-studyfr-v5/.cache/caches/gatsby-source-wordpress-experimental/a1aa62e5163bc8656a334d10837722b0/  Warmadewa University Logo.png failed
  Original error:
  
  - jobs-manager.ts:318 enqueueJob
    [gatsby-studyfr-v5]/[gatsby]/src/utils/jobs-manager.ts:318:21
  
  - runMicrotasks
  
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
```

- "gatsby": "^2.24.50",
- "gatsby-image": "^2.4.16",
- "gatsby-plugin-sharp": "^2.6.28",
- "gatsby-source-wordpress-experimental": "^1.3.8",
- "gatsby-transformer-sharp": "^2.5.13",

**Comment by pieh** [comment]
@KamranMaqbool The 409 (Conflict) error comes from wordpress server in this is root problem here. It might be combination of the way file is being downloaded. Some brief info on 409 - https://httpstatuses.com/409

Does the error happen consistently? If so - try clearing gatsby cache (`gatsby clean` command) and try build/develop again - this might be some weirdness with our downloader trying to use ETAG which maybe is not supported by your server in weird way? 

> imageFile {} object only show in gatsbyjs wpgraphQL but why not show in WPGraphQL Query.i don't understand what this happen

I see you are using `wpgraphql` with `gatsby-source-graphql` combination, which means that you probably also use something like https://gist.github.com/henrikwirth/4ba900b7f89b9e28ec81497466b12710 to add this custom field in Gatsby GraphQL layer (which is why this is only available in gatsby and not on WPGraphQL)

**Comment by pieh** [comment]
@MKlblangenois your issue doesn't seem related. This is about image processing, so I would suggest either finding similar issue or opening new one if there were no reports for it yet.

**Comment by theskillwithin** [comment]
I am getting same issues as @MKlblangenois on a random single png file.  I upgrade about every week so I think recent.

**Comment by KamranMaqbool** [comment]
@pieh 
I'm also try to remove node_modules & `(gatsby clean command)`  
but same error occurs

**Comment by KamranMaqbool** [comment]
@pieh 
this error produce in local environment 
when deploy in production(on Netlify) no error occur.it's working fine

**Comment by linoxyn** [comment]
I'm getting a similar error in development. Errors out even when I remove or replace the image it fails on.

```
Processing C:/Projects/lochwebsite/.cache/caches/gatsby-source-google-docs/40ddb3df04d7c5a8a0473e6bf801d4b2/google-docs-image-4d7218b8-316a-5853-aab9-4663599dcda2.png failed

Original error:

  WorkerError: Processing C:/Projects/lochwebsite/.cache/caches/gatsby-source-google-docs/40ddb3df04d7c5a8a0473e6bf801d4b  2/google-docs-image-4d7218b8-316a-5853-aab9-4663599dcda2.png failed
  Original error:

  - jobs-manager.ts:318 enqueueJob
    [lochwebsite]/[gatsby]/src/utils/jobs-manager.ts:318:21

  - runMicrotasks

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5

not finished Generating image thumbnails - 140.317s
```
Initially I thought this might have been an issue with `gatsby-source-google-docs` as this is the CMS I'm using to download images from Google Docs. I have been trying to find a working development setup where I can get all the images generated without error and I found if I set an older `gatsby-plugin-sharp@2.6.29` version it works. 

Partial list of packages:

-     "gatsby": "^2.24.54",
-     "gatsby-cli": "^2.12.92",
-     "gatsby-image": "^2.4.17",
-     "gatsby-plugin-catch-links": "^2.3.11",
-     "gatsby-plugin-manifest": "^2.4.28",
-     "gatsby-plugin-offline": "^3.2.27",
-     "gatsby-plugin-prefetch-google-fonts": "^1.4.3",
-     "gatsby-plugin-react-helmet": "^3.3.10",
-     "gatsby-plugin-sharp": "^2.6.29",
-     "gatsby-plugin-styled-components": "^3.3.10",
-     "gatsby-plugin-typography": "^2.5.10",
-     "gatsby-remark-embed-video": "^3.0.10",
-     "gatsby-remark-images": "^3.3.29",
-     "gatsby-remark-responsive-iframe": "^2.4.13",
-     "gatsby-source-filesystem": "^2.3.28",
-     "gatsby-source-google-docs": "^2.0.0-beta.18",
-     "gatsby-transformer-remark": "^2.8.33",
-     "gatsby-transformer-sharp": "^2.5.14",

**Comment by MKlblangenois** [comment]
imagemin-pngquant just merge PR's #71 (https://github.com/imagemin/imagemin-pngquant/pull/71) that solve the issue. Just update or install imagemin-pngquant@9.0.1 fix error on local and Netlify
