### ISSUE TITLE
Code not working on server

### ISSUE THREAD

**Issue by ujwaldreamztech** [gatsbyjs/gatsby#26774]
Hello,

I am using the gatsby theme admin template and have written the code below to make different types of layouts. However the code is working in netlify and on my localhost, but when I upload a build to the apache server, the below the code is not working.
Could you please tell us how to resolve this issue?

 if (pageContext.layout == undefined && location && location.href && !location.href.match(/admin/)) {
    pageContext.layout = 'frontend';
  } else if (pageContext.layout == undefined && location && location.href && location.href.match(/admin/)) {
    pageContext.layout = 'auth-inner';
  }

**Comment by LekoArts** [comment]
Thank you for opening this!

We're not maintaining https://github.com/paljs/gatsby-admin-template here so if you have specific questions about the template, please ask them there. You'll need to configure your Apache server to handle client-only routes (it seems), so maybe look into [these docs](https://www.gatsbyjs.com/docs/client-only-routes-and-user-authentication/#configuring-and-handling-client-only-routes-on-a-server).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
