### ISSUE TITLE
Telemetry write directory permission issues

### ISSUE THREAD

**Issue by 273403986** [gatsbyjs/gatsby#26783]
.config/gatsby/sites
GATSBY_TELEMETRY_DISABLED=1
gatsby telemetry --disable 
Can I turn this feature off completely or allow me to modify the write directory because it has permissions issues.

**Comment by LekoArts** [comment]
Thank you for opening this!

So we tested this a bit, there shouldn't be any problems with running Gatsby even when you have broken permissions for your `$home/.config` directory. With `GATSBY_TELEMETRY_DISABLED=1` you disabled it anyways. You won't be able to persist settings though or use future features like implemented in Gatsby Desktop but the general usage works.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by LekoArts** [comment]
Can you please explain your problem in more detail? What error are you seeing?

**Comment by 273403986** [comment]
I can set this XDG_CONFIG_HOME variable to solve this problem

**Comment by LekoArts** [comment]
Ok, good to hear. Closing this then!
