### ISSUE TITLE
Dropdown menu item gets the wrong position when changing the viewport

### ISSUE THREAD

**Issue by duyphanz** [gatsbyjs/gatsby#26797]
## Description

Dropdown menu item gets the wrong position when changing the viewport

### Steps to reproduce

- Enter: https://www.gatsbyjs.com/
- Try to grow and shrink from mobile view to desktop view

[Demo video](https://vimeo.com/455150584)

### Expected result

The Dropdown menu item should have the right position

### Actual result

The Dropdown menu item gets the wrong position

**Comment by LekoArts** [comment]
Thanks for the issue, this has been fixed!
