### ISSUE TITLE
[Feature Request][netlify] Autogenerate virtual redirects for development from static/_redirects

### ISSUE THREAD

**Issue by probablyup** [gatsbyjs/gatsby#26790]
## Summary

The netlify plugin automatically creates a redirects file based on a combination of any supplied redirects via `static/_redirects`. It'd be great if during development it also created virtual redirects inside gatsby (materialized from `static/_redirects`) so the site appears to work as it would when you build and host it.

**Comment by LekoArts** [comment]
Googling for a bit and finding this issue (https://github.com/netlify/cli/issues/583) I think you can use Netlify's CLI (`netlify dev`) to have these redirects working.

**Comment by probablyup** [comment]
Bump

**Comment by LekoArts** [comment]
Bump for what? 😅 I answered and asked a question 😬

**Comment by probablyup** [comment]
@LekoArts https://github.com/netlify/cli/issues/1300 it's not usable

**Comment by LekoArts** [comment]
Ok! Thinking a bit more about this I don't think this is something we want to do anyways, the Netlify CLI is the correct approach to those Netlify specific things.

**Comment by probablyup** [comment]
Honestly shit like this is why I don't enjoy using the gatsby ecosystem. I am forced into it because of work but I would never choose this ecosystem otherwise; every time I've raised a legitimate concern the people involved have opted-out of a good dev experience. It's very disappointing.
