### ISSUE TITLE
gatsby-plugin-feed: enable function values for `title`, `output`, and `link`?

### ISSUE THREAD

**Issue by johnridesabike** [gatsbyjs/gatsby#26803]
## Summary

I propose that `gatsby-plugin-feed` be able to accept functions for `title`, `output`, and `link`. Each of these functions would accept the result of the `query` value and return a string.

### Basic example

Compared to the current example configuration:

```diff
// In your gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-feed`,
      options: {
        query: `
          {
            site {
              siteMetadata {
                title
                description
                siteUrl
+                feedTitle
+                feedOutput
+                feedLink
              }
            }
          }
        `,
        feeds: [
          {
            serialize:  serializeCallback,
            query: queryString,
-            output: "/rss.xml",
+            output: ({ query: { site: { feedOutput } } }) => feedOutput,
-            title: "Your Site's RSS Feed",
+            title: ({ query: { site: { feedTitle } } }) => feedTitle,
            match: "^/blog/",
-            link: "https://feeds.feedburner.com/gatsby/blog",
+            link: ({ query: { site: { feedLink } } }) => feedLink,
          },
        ],
      },
    },
  ],
}
```

### Motivation

This allows these values to be configured through the same GraphQL API that the rest of the data is in. You can store these values in JSON, YAML, or some other queryable source instead of editing `gatsby-config.js`. This will also make it easier to use with CMSes.

**Comment by LekoArts** [comment]
Sounds like a good idea! I also was in the need to customise the feed title in the past programmatically. Since we currently won't have time to implement this would you be interested in sending in a PR for this? Let us know if you need guidance or pointers for the start.
