### ISSUE TITLE
Scroll handler crashes when there is an invalid hash

### ISSUE THREAD

**Issue by alexantom** [gatsbyjs/gatsby#26828]
## Description

Access this  url from chrome browser breaks the page
https://www.gatsbyjs.com/blog/2019-11-13-getting-set-up-to-manually-test-web-accessibility/?search=sdfsk#%

Don't have reproducible code yet, will update this thread soon

### Steps to reproduce

Access Above Url 

Or 

1. add `?search=sdfsk#%` part of the url 
2. hit enter key on browser addressbar

![image](https://user-images.githubusercontent.com/54152098/92523740-b67a0700-f1d5-11ea-937e-e5e9f3257441.png)

### Expected result

Page should not Break

### Actual result

Throwing Error , refer screenshot or access url

looks like issue is with this module
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-react-router-scroll/src/scroll-handler.tsx#L48

### Environment

`Chrome Version 85.0.4183.83 (Official Build) (64-bit)`

**Comment by alexantom** [comment]
@ umusicanumothu

**Comment by umusicanumothu** [comment]
@alexantom  ya. Happening the issue for me too.

**Comment by alexantom** [comment]
Thanks @umusicanumothu  to identify this issue.
