### ISSUE TITLE
Accessing in gatsby-node through graphQL to the exports in page files, as you can do it with mdx files

### ISSUE THREAD

**Issue by kuworking** [gatsbyjs/gatsby#26820]
In `gatsby-node`, is there a way to access through `graphQL` to the `exports` present in page files (when programatically creating them)?

I am currently doing this with `mdx` files, but in my case it has more sense to use plain `js` files rather than `mdx`

However I cannot access to the page exports with standard graphQL `allFile` query (while exploring it in graphiQL)

Is there a way to access them out of the box? 

Or should I create the node in `onCreateNode` (I don't know what should I do, so maybe this is a good reason to keep using `mdx`)

```
allMdx
      {
        edges {
          node {
            body
            tableOfContents
            timeToRead
            wordCount {
              words
            }
            exports {
              image
              type
              date(formatString: "MMMM DD, YYYY")
```

**Comment by LekoArts** [comment]
Can you please rephrase your question or give a full reproduction/example of your problem? That would really help me (or others) to understand your question. Thanks!

**Comment by kuworking** [comment]
> Can you please rephrase your question or give a full reproduction/example of your problem? That would really help me (or others) to understand your question. Thanks!

In one website I've seen that I was using `mdx` pages not really to have markdown content, but to have access to the exported components through graphQL

```js
# this is my mdx file

export const hello = 'I can see this const hello through graphQL`

```

I am using this graphQL access to be able to use this data in `gatsby-node`, so I need this functionality

But it feels weird to use `mdx` only because of this feature, so I've switched to `js` pages only to see that without `gatsby-plugin-mdx` these `export const` are not exposed to graphQL

Hence the question

At the end, thought, I've switched to `yaml` files, for which the plugin also exposes the data through graphQL and fits very well to what I need, so this issue is solved for me

But still, I'd like to know if there is a reasoning for this situation, maybe to encourage that content in Gatsby should not be typed in `js` files but in other formats (?)

**Comment by LekoArts** [comment]
Ok, now I understand.

Would https://www.gatsbyjs.com/plugins/gatsby-transformer-javascript-frontmatter/ work for you usecase?

**Comment by kuworking** [comment]
Yes, this is exactly what I meant, didn't know this existed (!)

Thanks :)
