### ISSUE TITLE
How to catch or handle error in: Building static HTML for pages step?

### ISSUE THREAD

**Issue by PrzemyslawZajac88** [gatsbyjs/gatsby#26835]
Hi, 

In our project we are using database with - "page" which represents state of the gatsby publishing (with states unpublished, pending, published, error).
Our gatsby process is executed by cron job every minute (without overlapping).  

We defined Gatsby steps (**gatsby-node.js**) : 
- createPages (fetch page records with state pending and run createPage() )
- onPostBuild (update page records with success or error)

**The problem** is that "Building static HTML for pages" step is failing whole build and even if we catch Error we are not sure how to inform graphql which page failed.
 
**The Question is** : How we can update error state if we encounter issue in : Building static HTML for pages step ?

Note: We cannot validate context data (page records) before, because this data is noSql/dynamic structure created by multiple services. So not all pages has same data, and one "page" should not block others from building.  

Note2: We use s3 plugin to deploy only newly generated pages to Aws s3. (Not sure if this detail is needed)

Regards, 
Przemek

**Comment by ascorbic** [comment]
Hi Przemek,
There isn't a way to prevent a page build error from failing the whole build. This is expected behaviour. You could find which page failed though, by setting `GATSBY_LOGGER=json`. This will give you the build status, as well as the actual error details, including the path. 

I'm goign to close this, but if you have more questions please do re-open.

**Comment by iampava** [comment]
I couldn't find any reference to this in the docs. Is this still the case?

My situation is that I'd like to know which page fails. Currently in the console all I get is a stack trace but nothing to get back to the page.
