### ISSUE TITLE
[nprogress] loading spinner/bar don't show every time

### ISSUE THREAD

**Issue by theiliad** [gatsbyjs/gatsby#2683]
I'm seeing this with a bunch of Gatsby sites using the nprogress plugin, where only for routes where the load takes really long it would show the spinner and the progress bar.

**Any way to show the spinner on any route change as soon as the route change process has started?**

I know I can add nprogress manually and add bound it to
```js
browserHistory.listen()
```

but I was wondering if you can configure the plugin in any way

**Comment by KyleAMathews** [comment]
Why show it all the time?

**Comment by theiliad** [comment]
Sometimes the route change takes a while and you would think that nothing is happening without the progress bar, but I guess the time is lower than the minimum amount of seconds after which the loading will show.

Take a look here:
https://www.gopher.it

**Comment by KyleAMathews** [comment]
Yeah, it shows after a second as 1 second is around when a user starts to think "oh, maybe something is wrong". Before then, showing any feedback is just distracting and makes the site feel like a carnival :-)

https://www.nngroup.com/articles/response-times-3-important-limits/

Anyways, super sexy site! I'd hire y'all! You should add the site to the showcase once you launch!

**Comment by theiliad** [comment]
I see, cool, if research shows otherwise then who am I to argue.

Thanks yeah will do, right now still trying to finish it up 😄
