### ISSUE TITLE
"Command failed with exit code 255" error after "gatsby new project https://github.com/gatsbyjs/gatsby-starter-hello-world"

### ISSUE THREAD

**Issue by romanthecoder** [gatsbyjs/gatsby#26843]
## Description

I have been having this problem with every new project I start using gatsby-cli. I upgraded brew, node, npm, gatsby-cli... I tried using yarn. Still, I get a problem with the "gatsby new" command because of something with "install.js". 

### Steps to reproduce

1. cd into your projects directory and pick a name for a project that is not used

2. gatsby new [project name] https://github.com/gatsbyjs/gatsby-starter-hello-world

3. that's it. 

### Expected result

I get no errors installing packages

### Actual result

```
gatsby new project https://github.com/gatsbyjs/gatsby-starter-hello-world
info Creating new site from git:
Cloning into 'project'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 16 (delta 0), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), 372.57 KiB | 849.00 KiB/s, done.
success Created starter directory layout
info Installing packages...

> fsevents@1.2.13 install /Users/romanmirov/Desktop/project/node_modules/fsevents
> node install.js



 ERROR 

Command failed with exit code 255: npm install



  Error: Command failed with exit code 255: npm install
  
  - error.js:56 makeError
    [global]/[execa]/lib/error.js:56:11
  
  - index.js:114 handlePromise
    [global]/[execa]/index.js:114:26
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - init-starter.js:143 install
    [global]/[gatsby-cli]/lib/init-starter.js:143:7
  
  - init-starter.js:210 clone
    [global]/[gatsby-cli]/lib/init-starter.js:210:3
  
  - init-starter.js:351 initStarter
    [global]/[gatsby-cli]/lib/init-starter.js:351:5
  
  - create-cli.js:428 
    [global]/[gatsby-cli]/lib/create-cli.js:428:7
```

### Environment

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2467M CPU @ 1.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 78.0.2
    Safari: 13.1.2
```

**Comment by ascorbic** [comment]
Hi,
From the error message it seems to be a specific issue with installing fsevents. I have just tried to reproduce it here and it seems to work fine. Could you try cloning https://github.com/gatsbyjs/gatsby-starter-hello-world and running npm install and see if you get the same error?

Thanks

**Comment by romanthecoder** [comment]
@ascorbic I cloned it and ran install, this was the output: 
```
> fsevents@1.2.13 install /Users/romanmirov/Desktop/gatsby-starter-hello-world/node_modules/fsevents
> node install.js
```
No error this time with the exit code. It looks like some of the dependencies require a 1.x.x version of fsevents when the newest version is 2.x.x, but `gatsby develop` works using the git clone method. Thanks!
