### ISSUE TITLE
'UNHANDLED REJECTION' at 'Building production JavaScript and CSS bundles' - during build process

### ISSUE THREAD

**Issue by RaphaelKomander** [gatsbyjs/gatsby#26846]
### Description

Getting 'Building production JavaScript and CSS bundles' - ERROR - during build process. 

![200908 Gatsby Retro_UNHANDLED_REJECTION](https://user-images.githubusercontent.com/7094655/92699698-34f9b480-f34e-11ea-83ca-b416f88e7c74.PNG)

### Steps to reproduce

clone remote repo
cmd: sudo gatsby build - within app folder

### Expected result

Succeful built of the cloned repo

### Actual result

'Build prduction JavaScript and CSS bundles' process  'ERROR' - 'UNHANDLED REJECTION'

### Environment

System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) CPU D-1527 @ 2.20GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/bin/node
    npm: 6.14.8 - /usr/bin/npm
  npmPackages:
    gatsby: ^2.24.43 => 2.24.43
    gatsby-image: 2.2.37 => 2.2.37
    gatsby-link: 2.2.27 => 2.2.27
    gatsby-plugin-feed: 2.3.25 => 2.3.25
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-netlify: 2.1.30 => 2.1.30
    gatsby-plugin-nprogress: 2.1.17 => 2.1.17
    gatsby-plugin-offline: 3.0.30 => 3.0.30
    gatsby-plugin-preact: 3.1.24 => 3.1.24
    gatsby-plugin-react-helmet: 3.1.18 => 3.1.18
    gatsby-plugin-sass: ^2.3.12 => 2.3.12
    gatsby-plugin-sharp: 2.3.10 => 2.3.10
    gatsby-plugin-sitemap: 2.2.24 => 2.2.24
    gatsby-remark-copy-linked-files: 2.1.33 => 2.1.33
    gatsby-remark-images: 3.1.39 => 3.1.39
    gatsby-remark-prismjs: 3.3.28 => 3.3.28
    gatsby-remark-responsive-iframe: 2.2.30 => 2.2.30
    gatsby-remark-smartypants: 2.1.19 => 2.1.19
    gatsby-source-filesystem: 2.1.43 => 2.1.43
    gatsby-transformer-remark: 2.6.45 => 2.6.45
    gatsby-transformer-sharp: 2.3.9 => 2.3.9
  npmGlobalPackages:
    gatsby-cli: 2.12.94
    gatsby: 2.24.55

**Comment by ascorbic** [comment]
Hi,
Can you upgrade to the latest version of `gatsby-plugin-sharp` and try again? You're running a very old version. While you're at it I'd upgrade the other plugins too if possible. If you're using yarn, you can do `yarn upgrade-interactive --latest`.

**Comment by RaphaelKomander** [comment]
Oh thanks!

This error resolved with the help of following cmds - from project directory:
```
sudo npm uninstall -g gatsby-cli
sudo npm clean -force
sudo npm install -g gatsby-cli
sudo npm install --save gatsby-plugin-sharp@latest --unsafe-perm
sudo npm audit fix
```
PS: I've taken the npm path due to this [quick start](https://www.gatsbyjs.com/docs/quick-start/) guide. ^^
