### ISSUE TITLE
GraphiQL IDE and gatsby-source-filesystem query question

### ISSUE THREAD

**Issue by waylonrobert** [gatsbyjs/gatsby#26845]
Hi - new to Gatsby and learning as I go. I have a strange problem that I can't figure out. 

I'm attempting to follow the guide here: https://www.gatsbyjs.com/docs/sourcing-from-the-filesystem/

Some particulars:
- MacBook Pro running macOS Catalina 10.15.4.
- I have a single JSON data file in `src/data`. 
- When I try to run the query on GraphiQL to get the bare minimum information (ID as noted in the guide), I get nothing. See output below:

**Query:**
```
query MyQuery {
  allFile {
    edges {
      node {
        id
      }
    }
  }
}
```
**Result:**
```
{
  "data": {
    "allFile": {
      "edges": []
    }
  },
  "extensions": {}
}
```

My gatsby-config.js includes this:

```
{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `${__dirname}/src/data/`,
      },
    },
```
Versions according to package.json:

```
gatsbv 2.24.56
gatsby-source-filesystem 2.3.29
```
What could be the problem? As far as I understand it, I should see a result from the query, but I bet I'm missing something. Appreciate any help!

**Comment by LekoArts** [comment]
Hi, thanks for the issue! Can you link to an example or give a reproduction where this doesn't work? I've spun up a [codesandbox](https://codesandbox.io/s/issue-26845-xxmnu) and the [GraphQL query](https://xxmnu-8000.sse.codesandbox.io/___graphql?query=query%20MyQuery%20%7B%0A%20%20allFile%20%7B%0A%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=MyQuery) works as expected.

Have you restarted your development server after adding the plugin and adding the entry to `gatsby-config.js`?

**Comment by waylonrobert** [comment]
Hi @LekoArts - thanks for spinning that up! I spun one up last night as well, and I could not replicate it outside of my machine. But that's why I posted here; trying to figure out what could be causing this.

**Comment by waylonrobert** [comment]
Found the issue. There was a syntax issue in my gatsby-config.js file. Oddly, it didn't warn me about it (and my site loaded fine this entire time). Thanks for the help!
