### ISSUE TITLE
Gatsbyjs build, better control for interval rebuild

### ISSUE THREAD

**Issue by snics** [gatsbyjs/gatsby#26851]
## Summary

Hello everyone,

I want to know if it makes sense to build a service with Gatsbyjs to build the frontend (most likely a big project). Because I want to rebuild this as soon as there are changes in the database. I would like to adapt the build output, so not all files are always rebuilt. So content and the other files split, in order to have the best out of the webpack contenthash procedure. Anybody is working on that already? Help wanted label ✌️

## Relevant information

None

**Comment by herecydev** [comment]
This actually already exists, you can check it out here: https://www.gatsbyjs.com/docs/conditional-page-builds

It's not perfect as there's a few bugs that need fixing but it does do what you want.

**Comment by snics** [comment]
@herecydev thanks for the article!

Have you ever used it before?
If so, do you know where the problems are?

**Comment by herecydev** [comment]
Yep; I added the following disclaimer:

> Conditional page builds do not currently account for static queries. Any query result differences will not trigger pages to rebuild.

So effectively that makes static queries useless at the moment. It might take some time to fix that as it's not really anything the Gatsby core team will focus on. Other than that they work really well; any data changes (page props) will not update if they are equal to the previous run.

You'll need to also keep the cache/public folder around, that's usually not an issue with build servers but it's worth noting.

**Comment by snics** [comment]
@vladar danke dir! Werde mir das mal in Projekt angucken.

**Comment by snics** [comment]
@vladar thank you! I'll check it out in Project.
