### ISSUE TITLE
Page does not display images on first load

### ISSUE THREAD

**Issue by Rahavee** [gatsbyjs/gatsby#26855]
## Description

The page does not display images on first load. The components are not styled correctly, but when I am routed to another page the problem seems to fix itself

### Steps to reproduce
 https://silly-goldwasser-8fa9a6.netlify.app/
https://silly-goldwasser-8fa9a6.netlify.app/Code-Etch

### Expected result
The images be displayed on the first load of the home page

### Actual result

There are no images and components are not styled correctly

### Environment

 System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 80.0
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47
    gatsby-image: ^2.4.17 => 2.4.17
    gatsby-plugin-netlify-cms: ^4.3.13 => 4.3.13
    gatsby-plugin-sharp: ^2.6.34 => 2.6.34
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10
    gatsby-remark-images: ^3.3.29 => 3.3.29
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-filesystem: ^2.3.27 => 2.3.27
    gatsby-transformer-remark: ^2.8.32 => 2.8.32
    gatsby-transformer-sharp: ^2.5.14 => 2.5.14

### Repository

https://github.com/Rahavee/gatsby-site

**Comment by pindjur** [comment]
@Rahavee You need server side support for material ui. Here is the [plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-material-ui/)
