### ISSUE TITLE
Absolute-positioned div scrolls inside absolute-positioned parent + Keyboard Scroll not working

### ISSUE THREAD

**Issue by bradkim06** [gatsbyjs/gatsby#26862]
## Description
title is same my problem. I have an absolute-positioned div with two children -- an absolute-positioned div and a static div which will scroll inside the parent. It looks like this: https://build-32315e85-3ae0-4cc1-a1e1-e01577c4f6b0.gtsb.io/
Mouse scrolling works fine, but keyboard scrolling doesn't work. 

I wondered if the Absolute property was the problem, so I tried the similar example without the Absolute property, but it also can't scroll with keyboard. Demo Code2(https://codepen.io/pawelsas/pen/vdwjpj) it is not possible to scroll child elements with a keyboard in Gatsby Ver2.x. I have found that this problem occurs in only Gatsby Version 2.x and above, but not in Gatsby Version 1.x.

I don't want to downgrade Gatsby to Version1. How can i scroll child div with keyboard in Gatsby Version 2.x?

## Steps to reproduce
To simplify the problem, I create and describe a new project.

```bash
gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-starter-hello-world
```
fix src/pages/index.js
```jsx
import React from "react"
import styled from "styled-components"

const Hello = () => {
  return (
    <Test>
      <div class="frame">
        <div class="fix-me"></div>
        <div class="scroll-me">
          <div class="long-content"></div>
        </div>
      </div>
    </Test>
  )
}

const Test = styled.div`
  .frame {
    background-color: blue;
    position: absolute;
    top: 40px;
    right: 40px;
    left: 40px;
    bottom: 40px;
    overflow-y: hidden;
  }

  .scroll-me {
    background-color: orange;
    position: absolute;
    top: 40px;
    right: 40px;
    left: 40px;
    bottom: 40px;
    overflow-y: scroll;
  }

  .fix-me {
    position: absolute;
    z-index: 999;
    top: 40px;
    left: 40px;
    right: 40px;
    height: 56px;
    background-color: purple;
  }

  .long-content {
    width: 480px;
    background-color: yellow;
    height: 4000px;
    margin: 20px auto;
  }
`
export default Hello
```

```bash
gatsby develop
```

## Notes on troubleshooting
Simplified example
github: https://github.com/bradkim06/keyboard_scroll_not_work
demo page: https://build-32315e85-3ae0-4cc1-a1e1-e01577c4f6b0.gtsb.io/

My Gatsby blog is a real problem
github: https://github.com/bradkim06/clone_greg_blog
demo page: https://personal_blog.gtsb.io/

## Environment
```
  System:
    OS: Windows 10 Pro Ver 2004
    CPU: (4) intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 CPUs), ~2.0GHz
    Shell: wsl2 - zsh
  Binaries:
    Node: v10.19.0
    Yarn: 1.22.5
    npm: 6.14.7

  Test Browsers:
    Chrome: 85.0.4183.83
    Microsoft Edge: 85.0.564.44

  npmPackages:
    "gatsby": "^2.24.54",
    "gh-pages": "^3.1.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "styled-components": "^5.2.0"

  npmGlobalPackages:
    Gatsby CLI version: 2.12.91
    Gatsby version: 2.24.54
```

**Comment by LekoArts** [comment]
Thank you for opening this!

This is not an issue with Gatsby but your CSS or rather how CSS works & behaves. You can only use the keyboard if the overflow is on the `body` itself (like on "Demo Code 2") or if your focus is on the specific `div`. You can try this by adding `tabindex="0"` to the `div` and you'll be able to <kbd>Tab</kbd> into it and scroll then.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by bradkim06** [comment]
@LekoArts Thank you for kindly answering even silly questions

tabIndex is exactly what I want.
```jsx
<div class="scroll-me" tabIndex="0">
```

however, there is one question. 

why gatsby Ver1 & CodePen can keyboard scroll without tabIndex="0". why Ver2 need tabIndex? 

Could you please tell me what makes this difference?

**Comment by LekoArts** [comment]
I don't know the answer to that, maybe the updated React version changes something. There's also a V2 version of your starter available: https://github.com/greglobinski/gatsby-starter-personal-blog/tree/version-2

**Comment by bradkim06** [comment]
Okay. Thank you so much for your kind response.
