### ISSUE TITLE
Proposals are not polyfilled by babel-preset-gatsby

### ISSUE THREAD

**Issue by probablyup** [gatsbyjs/gatsby#26867]
## Description

We recently started using `Promise.allSettled` in our application code. This is correctly pulled into the polyfill bundle because some browsers don't support it yet.

The gatsby babel preset currently uses `core-js@3` to polyfill syntax that is not supported by whatever browserslist config your project uses. However, if a particular syntax is a _proposal_ (e.g. `Promise.allSettled`: https://github.com/zloirock/core-js/blob/master/packages/core-js/proposals/promise-all-settled.js) this is currently **not** polyfilled automatically.

This is confusing for developers and solvable by simple configuration change to Gatsby's usage of babel preset env: https://babeljs.io/docs/en/babel-preset-env#corejs

### Steps to reproduce

Make a Gatsby project that uses `Promise.allSettled` somewhere in the code.

### Expected result

`Promise.allSettled` polyfill is added to polyfills.js, as well as the application code, and Safari 12 loads the inlined `Promise.allSettled` polyfill since it doesn't have that native method.

### Actual result

`Promise.allSettled` polyfill is added to polyfills.js, _not added to the application code_, and Safari 12 _does not_ load the polyfill.js backup file due to `nomodule` directive on the script tag, which Safari 12 understands.

**Comment by probablyup** [comment]
One possible fix would be to emit the polyfills as separate files and only add `nomodule` if it's 100% known that "modern" browsers support it.

**Comment by probablyup** [comment]
If anyone else is dealing with this, I was able to work around the issue by using:

```tsx
<Helmet>
  <script
    dangerouslySetInnerHTML={{
      __html: `document.querySelector('script[src*=polyfill]').removeAttribute('nomodule')`,
    }}
  />
</Helmet>
```

**Comment by herecydev** [comment]
I think the `nomodule` polyfill bundle might be misleading you here. It's sort of "statically built" and is irrelevant to whether you've included something that needs polyfilling. For example if you didn't included `Promise.allSettled` it still exists in the bundle and is primarily there to easily support IE11.

Because you're using safari 13 it should already support `Promise.allSettled` so I disagree with your expected result. Is it not working in safari for you?

**Comment by herecydev** [comment]
And I would definitely not recommend doing what you're suggesting (removing the nomodule) unless you understand the consequences. This will unnecessarily load in a lot of js polyfills.

**Comment by probablyup** [comment]
What would you have me do then? Promise.allSettled is not supported by Safari 12.x which is still over 1% https://www.w3counter.com/globalstats.php

**Comment by herecydev** [comment]
In your comments you were talking about Safari 13 which does support it. Those stats from w3counter are not the same stats that are used to identify what browsers you are supporting in your Gatsby app. For that you need to refer to https://gs.statcounter.com. Have you tried changing what browsers you want to support: https://www.gatsbyjs.com/docs/browser-support/#specify-what-browsers-your-project-supports-using-browserslist

**Comment by pindjur** [comment]
browserslist does not work with gatsby. try yourself and you will see that the same code is in production with last 2 Chrome versions and defaults or any other query.

**Comment by pindjur** [comment]
>  @probablyup  Solution for your problem is to use browserslist but it does not currently work with gatsby. its an issue a from  about year ago, i will try to find it

**Comment by herecydev** [comment]
@pindjur When you say doesn't work what do you mean?

> the same code is in production

The consuming code is unlikely to change, what we want to see is that the correct polyfills are added

**Comment by pindjur** [comment]
@herecydev  Yes. Same polyfils are added no metter what you put in .browserslistrc or package.json

**Comment by probablyup** [comment]
Alright I ended up making #26895 to hopefully solve this in core. In the meantime I went ahead and added this to the relevant files in my project:

```js
import 'core-js/proposals/promise-all-settled' // remove with https://github.com/gatsbyjs/gatsby/pull/26895
```

**Comment by wardpeet** [comment]
I'm not really in favor of adding more polyfills to Gatsby. Why aren't you adding that polyfill yourself to gatsby-browser.js instead? In gatsby v4 we will deprecate core-js as it adds to much bloat to bundles. We will provide tools to tell you about which polyfills you need so you're cautious of what's happening.

I'm happy to hear why enabling proposals is better than adding it manually. Also removing no-module from the polyfills bundle will make your site slower as it contains all necessary polyfills for IE11

**Comment by probablyup** [comment]
@wardpeet Are you not in favor of seamless developer experience? That's the only reason I can think of _not_ doing this. It's surprising and a waste of peoples' time to chase down a polyfill not being applied like I have done in this thread.

**Comment by probablyup** [comment]
@wardpeet I went ahead and updated the OP to reflect the new information.

> I'm not really in favor of adding more polyfills to Gatsby.

The way the [`corejs` flag](https://babeljs.io/docs/en/babel-preset-env#corejs) in preset env works is only to inline polyfills for syntax that you're actually using (detected via the "usage" `useBuiltIns` value which Gatsby already sets.) This is all still based on the browserslist config given to the project. So it's not really adding more polyfills, unless you yourself decide to use a syntax that would trigger the polyfill to be added.

> In gatsby v4 we will deprecate core-js as it adds to much bloat to bundles.

That's highly subjective and, in my opinion as someone that maintains quite a few open source projects and production applications, not a good idea. If you choose to use a syntax, the platform should do what it can to ensure your code works (within reason.)

--

Part of the appeal to using a framework like Gatsby is it abstracts away decisions the developer doesn't want/need to make and allows you to focus on _building product_. Taking steps away from a good developer experience meaningfully degrades the value of the framework.

**Comment by wardpeet** [comment]
I think you misunderstood me. I'm all in favor of developer experience but the user always comes first! Why should your user pay the price of Promise.allSettled when his browser supports it? Core-js allSettled promise polyfill weighs about 10kB. This can be written in 300B.

What I'm trying to say is that Gatsby needs to be smarter about polyfills. Most developers are not aware of what impact new features can have on their users. Thats why giving better info on what's happening with your bundle is ideal. We should only load the allSettled polyfill when used and when the browser needs it. @babel/preset-env only gives us the first piece.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
