### ISSUE TITLE
z-index issue of Dropdown Menu on Gatsby website

### ISSUE THREAD

**Issue by notsonoobie** [gatsbyjs/gatsby#26872]
## Description

There is a z-indexing issue on page https://www.gatsbyjs.com/showcase/2017.stateofeuropeantech.com where the z-index of the dropdown menu is expected to be higher then the z-index of the template shown.

When we hover over Nav-Links for the dropdown menu, the z-index of the dropdown menu is lower then the z-index of the template shown, so due to this few Nav-links are not visible.

### Steps to reproduce

1. Increase the z-index property of the dropdown menu.

### Expected result

If the z-index property of the dropdown menu is set higher than the z-index property of the template, then the Dropdown Menu will be properly visible for navigation.

### Visual Issue
![Screenshot (1)](https://user-images.githubusercontent.com/54475009/93000201-5b814080-f544-11ea-9bb9-3f26a19b8750.png)

**Comment by SergiLorDD** [comment]
this problem is related to these styles
https://ibb.co/TrTq1Dq

possible solution
https://ibb.co/xDF9vWb

**Comment by LekoArts** [comment]
Thanks for the report, I noted this internally and it'll get fixed :)
