### ISSUE TITLE
Frontmatter list items not treated as `File`s

### ISSUE THREAD

**Issue by dustinhorton** [gatsbyjs/gatsby#2687]
(Originally raised @ https://github.com/gatsbyjs/gatsby/issues/780#issuecomment-339790722, but think it _may_ have been missed, so wanted to make a fresh issue).

Using `1.9.83`:

Markdown frontmatter list:

```markdown
images:
  - ./images/01.jpg
  - ./images/02.jpg
  - ./images/03.jpg
```

Query:

```graphql
{
  markdownRemark {
    frontmatter {
      images
    }
  }
}
```

Result:

```json
{
  "data": {
    "markdownRemark": {
      "frontmatter": {
        "images": [
          "./images/01.jpg",
          "./images/02.jpg",
          "./images/03.jpg"
        ]
      }
    }
  }
}
```

And if trying to treat as `File`s:

```graphql
{
  markdownRemark {
    frontmatter {
      images {
        childImageSharp {
          responsiveSizes {
            src
          }
        }
      }
    }
  }
}
```

Result:

```json
{
  "errors": [
    {
      "message": "Field \"images\" must not have a selection since type \"[String]\" has no subfields.",
      "locations": [
        {
          "line": 4,
          "column": 14
        }
      ]
    }
  ]
}
```

**Comment by KyleAMathews** [comment]
Can you build a reproduction site? There's been several PRs addressing this recently so not sure what's wrong.

**Comment by dustinhorton** [comment]
@KyleAMathews Give this a shot: https://github.com/dustinhorton/gatsby-issue

It's the blog starter, and I've modified the 'New Beginnings'/'/hi-folks/' post. Not sure that was an optimal repro…let me know if I can provide something better.

**Comment by KyleAMathews** [comment]
The images have to exist for the link to be created.

**Comment by dustinhorton** [comment]
@KyleAMathews Apologies, I'd forgotten to `git add .` after adding them to the repro site. I've added them: https://github.com/dustinhorton/gatsby-issue/commit/fddf025b84c1889f2afdfa92c51ff9419e3c77f3

**Comment by KyleAMathews** [comment]
Ok, found the source of the bug. For our GraphQL inference, we have a general type inference and then we do special mappings for manual mappings, the `___NODE` syntax, and file mappings. We're not looking inside arrays right now for file mappings. I'll put together a quick PR for that.

Thanks @dustinhorton for the repo site! Always super helpful to have those when debugging.

**Comment by KyleAMathews** [comment]
@owenhoskins try not repeating your keys (you have two `images`) and see if it starts working?

**Comment by owenhoskins** [comment]
@KyleAMathews Thanks for the reply. It turns out the repeating keys were not the issue! Rather I had a onCreateNode API function that was throwing off the file system.

**Comment by justinlevi** [comment]
I recently had an odd issue with the Type inference not working with what seemed like some reserved keys. I had a `header` key with an image path that the auto-inference didn't seem to like.
