### ISSUE TITLE
Netlify blog tutorial broken link

### ISSUE THREAD

**Issue by jwa5426** [gatsbyjs/gatsby#26880]
## Summary

What problem(s) did you run into that caused you to request additional documentation? What questions do you think we should answer? What, if any, existing documentation relates to this proposal?

In [this tutorial](https://www.gatsbyjs.com/tutorial/blog-netlify-cms-tutorial/) the link to [gatsby-personal-starter-blog](https://www.gatsbyjs.com/starters/thomaswang/gatsby-personal-starter-blog/) in the first paragraph is broken

**Comment by LekoArts** [comment]
Thanks for the report! Would you be up for changing the link to `https://github.com/thomaswang/gatsby-personal-starter-blog` ?

**Comment by jwa5426** [comment]
Thanks for fixing it. I was too slow on the draw. 😅
