### ISSUE TITLE
Error during build - Failed to retrieve metadata from image ... Input file is missing

### ISSUE THREAD

**Issue by robert-adchitects** [gatsbyjs/gatsby#26888]
## Description

I have Gatsby project connected with WordPress. It's hosted on Vercel. 
When triggering `build` from WP (via webhook) I'm getting following error:

`error Failed to retrieve metadata from image /vercel/7c48990a/.cache/caches/gatsby-source-filesystem/4bea188c5eff0f6506668c8acc73697b/img_1-1_sistable.jpg Input file is missing`

It's weird that error occurs in about 50% of builds triggered. So when build ends with error - I'm able to trigger another build from WP (not changing anything) and it build successfully.

### Steps to reproduce

I can't share entire code as it's business project for a client, but let me know if anything more would be helpful for you.

The scenario for reproduce a bug is:

- make any changes within WordPress (plugin _JAMstack Deployments_ is set up to create POST request to Vercel Build Hook URL)
- login to Vercel and see _Deployments_ tab (sometimes there's error, sometimes not)

### Expected result

Successful build

### Actual result

Following error:

`error Failed to retrieve metadata from image /vercel/7c48990a/.cache/caches/gatsby-source-filesystem/4bea188c5eff0f6506668c8acc73697b/img_1-1_sistable.jpg Input file is missing`

### Environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.102
    Edge: 85.0.564.51
    Firefox: 77.0.1
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.23.10 => 2.23.10
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.4.8 => 2.4.8
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6
    gatsby-plugin-load-script: ^1.1.0 => 1.1.0
    gatsby-plugin-manifest: ^2.4.13 => 2.4.13
    gatsby-plugin-offline: ^3.2.12 => 3.2.12
    gatsby-plugin-react-helmet: ^3.3.5 => 3.3.5
    gatsby-plugin-sass: ^2.3.6 => 2.3.6
    gatsby-plugin-sharp: ^2.6.13 => 2.6.13
    gatsby-plugin-sitemap: ^2.4.7 => 2.4.7
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.3.13 => 2.3.13
    gatsby-source-wordpress: ^3.3.15 => 3.3.15
    gatsby-transformer-sharp: ^2.5.6 => 2.5.6
  npmGlobalPackages:
    gatsby-cli: 2.12.95
```

**Comment by sidharthachatterjee** [comment]
So it appears that the cache ought to exist but for some reason it is not? Does this happen on any other build service or just Vercel? 

If it's possible (I'm not familiar with Vercel), can you SSH into the build container and check if the file indeed exists or not?

**Comment by robert-adchitects** [comment]
@sidharthachatterjee I didn't try any other build service, but on my local machine everything worked fine.

When build ends with error - no output (build container) is being generated. When I checked one of successful build's output - there was no _.cache_ folder at all (or it was hidden).

Do you think it may be Vercel related issue? 
I wonder if _.cache_ folder is generated by Gatsby itself or it's a Vercel feature?

**Comment by robert-adchitects** [comment]
I managed to fix it. Adjusting build command ​to the following solves the issue:

`gatsby clean && gatsby build`

**Comment by leevi978** [comment]
Hello! I am getting this same error when building on Gatsby Cloud, but the console does not allow me to change the build command. Can this issue please be re-opened so that the developers may work on a fix?

**Comment by runemadsen** [comment]
I'm running into the same issue in a GitHub action. It was the first time it ran on the machine, so there shouldn't be any caching issues.
