### ISSUE TITLE
How to reduce size polyfill.js (78.59 KB)?

### ISSUE THREAD

**Issue by kouliavtsev** [gatsbyjs/gatsby#26894]
# Summary
In order to get better performance issues, I have installed **gatsby-plugin-webpack-bundle-analyser-v2**. I have learned that there is a polyfill-beba213d6201e708199c.js being generated with a whooping (78.59 KB).

I thought that this was generated by .bablerc, yet it seems that I am wrong. What is the best way to reduce the size of this file?

**Comment by herecydev** [comment]
This is a `nomodule` bundle needed only for browsers that don't support modules (basically IE). It contains a bunch of polyfills necessary for older browsers. So although it might seem chunky, it shouldn't be loaded by many browsers nowadays and therefore not of too much concern.

**Comment by LekoArts** [comment]
As herecydev correctly said this chunk has a `nomodule` attribute and thus will not be loaded automatically or the majority of the users (speaking in general terms). So luckily there's no further action required for you :)

**Comment by kouliavtsev** [comment]
Thanks for the explanation! I assume that this is being loaded continually (based on the browser)?
