### ISSUE TITLE
How to preserve the UTM queries with GatsbyLink?

### ISSUE THREAD

**Issue by lipis** [gatsbyjs/gatsby#26910]
I'm trying to preserve the UTM queries (from Google Analytics: `utm_source`, `utm_medium`, `utm_channel`, etc) while navigating through the website, so I updated the `gatsby-browser.js` with the relevant code that updates all the links with these queries from the landing page.

The problem is that when using the GatsbyLink it ignores and strips it, even though it appears that is being added via JS.

How could we preserve those queries.

### File contents (if changed)

`gatsby-browser.js`: https://gist.github.com/lipis/ac2d10ae44fc453b44797de51c335766

If the information is not enough, I could possibly create the simplest project with just that.

P.S. This works for links that are not GatsbyLinks :)

**Comment by icy-meteor** [comment]
I would say, just store the UTM in your local storage whenever someone lands on your website. You can capture in a Root level component. And then, just make use of that data wherever required.

**Comment by wardpeet** [comment]
@lipis I would go with what @icy-meteor suggested, you want to store it in session-storage. My question would be, why do you want to keep the utm data around?

You can also wrap gatsby-link in your own component that appends that query string to each gatsby link tag.

this is some pseudo code, don't expect it to work without modification :)
```
function MyOwnGatbyLink({to, ..props) {
  return <Link to={to + document;location.search} {...props} />
} 
```

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by lipis** [comment]
Thanks for the quick reply and I'll try a few options tomorrow! ❤️
