### ISSUE TITLE
[gatsby-offline-plugin] Blank Page sometimes appears and disappears after reload on pages with query.

### ISSUE THREAD

**Issue by Neychok** [gatsbyjs/gatsby#26912]
### Description

After installing gatsby-offline-plugin I get blank screen on some pages and errors like this in the console:
`TypeError: Cannot read property 'uid' of undefined
at t.default (single-product.ks:164)
...`
and after I reload the page the error disappears and everything looks normal.

I think it has something to do with the Service Worker since installing `gatsby-plugin-remove-serviceworker` fixes the problem. But I don't want to disable the service worker.

Also 100% of the times I had a blank screen it was on a page with a query.

Not sure if it's important but I am using `gatsby-plugin-transition-link` so the menu doesn't reload between pages

### Steps to reproduce

It's hard to reproduce since it doesn't happen always. It usually happens the first time I open the site after deploying it.

1. Make changes to site.
2. Deploy on Netlify
3. Open a page that has a query in it.

This is one of the pages I had blank screen on: [Link to gist](https://gist.github.com/Neychok/62a4f9f5fc67b8e5c6330831a13c6498)

### Expected result

Not show a blank screen

### Actual result

Shows a blank screen

### Environment

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.18.3 - D:\Programs\NodeJS\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - D:\Programs\NodeJS\npm.CMD
  Browsers:
    Chrome: 84.0.4147.89
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.51)
  npmPackages:
    gatsby: ^2.24.47 => 2.24.60 
    gatsby-image: ^2.4.16 => 2.4.18 
    gatsby-plugin-advanced-sitemap: ^1.5.5 => 1.5.6 
    gatsby-plugin-manifest: ^2.4.23 => 2.4.29 
    gatsby-plugin-offline: ^3.2.23 => 3.2.28 
    gatsby-plugin-postcss: ^2.3.11 => 2.3.12 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.11 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0  //Fixes the problem but it's currently disabled
    gatsby-plugin-sharp: ^2.6.27 => 2.6.36 
    gatsby-plugin-transition-link: ^1.20.2 => 1.20.2
    gatsby-plugin-typography: ^2.5.10 => 2.5.1
    gatsby-source-filesystem: ^2.3.24 => 2.3.30 
    gatsby-source-prismic: ^3.2.1 => 3.2.1 
    gatsby-transformer-sharp: ^2.5.13 => 2.5.15 
  npmGlobalPackages:
    gatsby-cli: 2.12.97

**Comment by LekoArts** [comment]
Can you maybe set up a new site and try to reproduce it there and link it? Without a possibility to see a reproduction (also live) it's hard to pin point the issue.

**Comment by Neychok** [comment]
Well, I updated some of the dependencies, including gatsby, and the problem seems to have disappeared.

**Comment by LekoArts** [comment]
Glad to hear that! :) Then I'll close this one.
