### ISSUE TITLE
Guide to deploying to Netlify

### ISSUE THREAD

**Issue by ItsPugle** [gatsbyjs/gatsby#2691]
Would this be possible to be made?

**Comment by Unforgiven-wanda** [comment]
In my experience, deploying to Netlify is pretty straightforward: 

1. Create your repo, in either Github, Bitbucket, or Gitlab
2. Go to Netlify, create an account, create an app
3. Give it access to your Git account, choose the repo you want to deploy
4. Netlify automatically detects that it's a Gatsby project, what with the build command and the publish directory
5. Tap "deploy site", wait for the install and build to finish and voilà

**Comment by wiesson** [comment]
An example for a `netlify.toml` for gatsby would be nice to see!

**Comment by MarcCoet** [comment]
I am actually looking into that in more details myself. Have you seen [this article](https://www.netlify.com/docs/continuous-deployment/#deploy-contexts) @wiesson ?

**Comment by ItsPugle** [comment]
Thanks for your replies - I got it successfully deployed shortly afterwards 😄

**Comment by sebastienfi** [comment]
Also, this plugin https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-netlify

**Comment by nodox** [comment]
Have you seen this [article](https://www.netlify.com/blog/2016/02/24/a-step-by-step-guide-gatsby-on-netlify/)?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
