### ISSUE TITLE
Using GraphQL to definine initial state for global context

### ISSUE THREAD

**Issue by dav92lee** [gatsbyjs/gatsby#26926]
## Summary
I've instantiated a global context to manage a the global state of my gatsby app.  There is a `defaultSelection` variable that I want to initialize with some data i pull from graphql (shopify-source plugin) -- I want the `defaultSelection` variable to be updateable.  As of right now, I am calling that graphql query to basically generate the defaultSelection as a fallback for every component that needs to know about `defaultSelection`.  It's messy and I was wondering if anyone knew of best practice or a better way to solve this problem?  Like some way of injecting my initial state variable with the defaultSelection during build time? 

*this is called everywhere i need access to `defaultSelection`
```
    const { allProductType } = useStaticQuery(graphql`
        query {
            allProductType {
                edges {
                    node {
                        ...productFields
                    }
                }
            }
        }
    `)

    const defaultSelection = state.defaultSelection || initDefaultSelection(allProductType)
```

**Comment by LekoArts** [comment]
Thank you for opening this!

You should put your Global Context into the [`wrapRootElement`](https://www.gatsbyjs.com/docs/browser-apis/#wrapRootElement) where you can also use `useStaticQuery` to access data. Then set this data as the default for the React context.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
