### ISSUE TITLE
How to uninstall Gatsby?

### ISSUE THREAD

**Issue by ItsPugle** [gatsbyjs/gatsby#2692]
How do you uninstall gatsby?

**Comment by KyleAMathews** [comment]
If you uninstall Gatsby, you'll never be able to deploy it to Netlify :-)

**Comment by ItsPugle** [comment]
@KyleAMathews If I don't have Gatsby installed, I won't have to deploy it to Netlify ;)
I figured it out anyways - `$ npm uninstall gatsby-cli` along with some scouring of `/usr` for any remaining files/directories

**Comment by jodumont** [comment]
Hi;
I have the same question
now I did `npm uninstall gatsby-cli` and `sudo npm uninstall gatsby-cli`
but `npm ls -g|grep gatsby`
still showing me 
```
├─┬ gatsby-cli@2.4.3
│   │ ├─┬ rx-lite-aggregates@4.0.8
  │ │ ├── delegates@1.0.0
```

**Comment by ItsPugle** [comment]
Hey @jodumont. Have you tried giving `npm uninstall -g gatsby-cli` a shot?
