### ISSUE TITLE
Upgrade gatsby-plugin-postcss to PostCSS 8

### ISSUE THREAD

**Issue by ai** [gatsbyjs/gatsby#26939]
## Summary

PostCSS 8 was released. It added a new plugin API. Right now Gatsby does not support PostCSS 8 plugins.

Updating `postcss-loader` and adding `postcss` to dependencies for `gatsby-plugin-postcss` will fix the problem.

[PostCSS 8 changelog](https://github.com/postcss/postcss/releases/tag/8.0.0) does not have breaking changes related to Gatsby only removing Node.js 6 and 8 support).

**Comment by LekoArts** [comment]
We'd be happy to receive a PR updating this, if you need help feel free to reach out here.

**Comment by chlorophyllkid** [comment]
Currently the build in the PR fails but I'm not sure if it's due to the changes in package.json and in yarn.lock 🤔

**Comment by LekoArts** [comment]
We published this on `gatsby-plugin-postcss@3.0.0` :)
