### ISSUE TITLE
Markdown Node excerpt does not have text within <code> tags

### ISSUE THREAD

**Issue by nwshane** [gatsbyjs/gatsby#2694]
## Observed Behavior

The `node.excerpt` data provided by gatsby-transformer-remark has had all text within `<code>` tags removed.

## Expected Behavior

Either:
1) the `<code>` tags can be removed but the text within them should stay. If `node.excerpt` is supposed to contain text with no html tags, then this is the desired fix.
2) the `<code>` tags can stay. I personally would prefer this, since then any code at the beginning of my blog post will be styled as code in the excerpt as well.

gatsby-transformer-remark@1.7.18
gatsby@1.8.11

**Comment by KyleAMathews** [comment]
The excerpt in code just [extracts "text" nodes from markdown](https://github.com/gatsbyjs/gatsby/blob/62637291567669219b776f4ab461e7945d1bda94/packages/gatsby-transformer-remark/src/extend-node-type.js#L258).

So 1 is the case.

For 2 — perhaps the solution is you could add an `htmlExcerpt` field as well?

**Comment by nwshane** [comment]
@KyleAMathews Thanks for the response! I went with 1) and added the value of `inlineCode` nodes into the excerpt. I probably don't really need `htmlExcerpt` but it's an interesting idea. Let me know what you think about the pull request - I haven't contributed much to open source yet so this is a new thing for me :)
