### ISSUE TITLE
"Internal server error" - is there any way at all to see the actual error message?

### ISSUE THREAD

**Issue by MitchEff** [gatsbyjs/gatsby#26945]
Every time I've seen someone else ask this, everyone just goes "it's an error on your server" which, like, obviously. 

If the request was being made by Axios or Postman or jQuery or your browser you'd still get the error it was returning. When Gatsby compiles, we just get 'Internal server error' and then just have to stab around in the dark until we can guess our way out of it. 

Is there something I'm missing? It's the biggest time-waster in our agency at the moment...

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

You'll need to explain this a bit more as your description is very vague.

- When does this error happen? How does the error look like in the CLI?
- What is your project like? Which source plugins do you use?
- What APIs do you request that could cause an "internal server error"?

**Comment by MitchEff** [comment]
Haha, totally understood @LekoArts, sorry about that.

It's frankly more likely an Apollo issue, as we get the same issue with Gatsby as we do Node etc. 

FWIW, if it helps anyone, we ended up getting some more valuable insights from logging $request in Request.php in wp-graphql's source. 

Probably shoulda put this issue in another repo - perhaps disregard.

**Comment by LekoArts** [comment]
Yeah, seems like not Gatsby is swallowing the error there but the initial logging already has this shape. So I'd recommend opening the issue on the other repository :)
