### ISSUE TITLE
AppSumo Callback Tracker

### ISSUE THREAD

**Issue by emmadigital** [gatsbyjs/gatsby#26944]
## Summary
I want to integrate App Sumo Callback tracker to gatsby website. 

## Relevant information

I have got below script from https://appsumo.com/callback-tracker/ for integrating callback tracker to my website:

`<noindex><script src="//widget.callbacktracker.com/tracker/xxxxxxxxxxxxxxxxxxxxxxxxx1234566" charset="UTF-8"  async="async" type="text/javascript"></script></noindex>
`
I added the code to gatsby-ssr.js as shown below:

```
setPostBodyComponents([
<noindex><script src="//widget.callbacktracker.com/tracker/xxxxxxxxxxxxxxxxxxxxxxxxx1234566" charset="UTF-8"  async="async" type="text/javascript"></script></noindex>
])
```

But the chat widget didn't appear. Please advise how to integrate this code so the chat widget appears on the website.

**Comment by LekoArts** [comment]
Thank you for opening this!

You'll need to add a `key` prop to the `noindex` and also change `charset` to `charSet`.
This is working in a codesandbox: https://codesandbox.io/s/add-script-to-body-u7lrn

```js
const React = require("react")

const PostBodyComponents = [
  <noindex key="app-sumo-callback-tracker">
    <script
      src="//widget.callbacktracker.com/tracker/xxxxxxxxxxxxxxxxxxxxxxxxx1234566"
      charSet="UTF-8"
      async="async"
      type="text/javascript"
    />
  </noindex>
]

exports.onRenderBody = ({ setPostBodyComponents }) => {
  setPostBodyComponents(PostBodyComponents)
}
```

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
