### ISSUE TITLE
[gatsby-transformer-remark] Content of inline HTML tags from markdown source is outside of tags in HTML output.

### ISSUE THREAD

**Issue by pzatrick** [gatsbyjs/gatsby#2696]
Gatsby version 1.9.83, CLI version 1.1.13
Node version 8.6.0
macOS 10.12.6

gatsby-config.js
```javascript
module.exports = {
    siteMetadata: {
        title: `Gatsby Default Starter`,
    },
    plugins: [
        `gatsby-plugin-react-helmet`,
        {
            resolve: `gatsby-plugin-typography`,
            options: {
                pathToConfigModule: `src/utils/typography.js`,
            },
        },
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                path: `${__dirname}/src/blog`,
                name: 'pages',
            },
        },
        {
            resolve: 'gatsby-transformer-remark',
            options: {
                plugins: [
                    `gatsby-remark-smartypants`,
                    {
                        resolve: `gatsby-remark-images`,
                        options: {
                            // It's important to specify the maxWidth (in pixels) of
                            // the content container as this plugin uses this as the
                            // base for generating different widths of each image.
                            maxWidth: 590,
                            // Remove the default behavior of adding a link to each
                            // image.
                            // linkImagesToOriginal: false,
                        },
                    },
                    {
                        resolve: 'gatsby-remark-copy-linked-files',
                        options: {
                            // `ignoreFileExtensions` defaults to [`png`, `jpg`, `jpeg`, `bmp`, `tiff`]
                            // as we assume you'll use gatsby-remark-images to handle
                            // images in markdown as it automatically creates responsive
                            // versions of images.
                            //
                            // If you'd like to not use gatsby-remark-images and just copy your
                            // original images to the public directory, set
                            // `ignoreFileExtensions` to an empty array.
                            ignoreFileExtensions: [],
                        },
                    }
                ]
            }
        },
    ],
};
```

package.json
```javascript
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.73",
    "gatsby-link": "^1.6.22",
    "gatsby-plugin-react-helmet": "^1.0.8",
    "gatsby-remark-copy-linked-files": "^1.5.15",
    "gatsby-remark-images": "^1.5.24",
    "gatsby-source-filesystem": "^1.5.5",
    "gatsby-transformer-remark": "^1.7.18",
    "typography-theme-lawton": "^0.15.10"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write 'src/**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.7.4"
  }
}
```

I'm trying to use inline HTML tags in my markdown e.g `<small>footnotes</small>` but in the rendered HTML I get `<small></small>footnotes`.

**Comment by dustinhorton** [comment]
I've experienced the same with `a` tags.

**Comment by ptrikutam** [comment]
I'm having the same issue. Anyone figure this one out?

**Comment by pzatrick** [comment]
I found that HTML tags work if you write it in "block" format as opposed to inline e.g.

```
<small>
small text
</small>
```

But of course its not a great workaround since then the `small` element gets rendered inside its own `p` element. HTH

**Comment by KyleAMathews** [comment]
Could someone put together a PR with a failing test? That'd be a good place to start collaborating on a solution.

**Comment by pzatrick** [comment]
I looked at the code to see if that's something I could do quickly, looks like that's not the case 😞 I'll put a PR together when I have a few hours of free time but not sure when that will be. In the meantime, my code that has the issue is [here](https://github.com/pzatrick/patrickcanfield.com/tree/master/gatsby).

**Comment by pzatrick** [comment]
I suspect the bug is hiding in `extend-node-type` but I don't see any tests for that file, which would be helpful.

**Comment by prurph** [comment]
I've also experienced this when creating my own plugin trying to make footnotes into side notes. I noticed I could create a simple HTML node in MDAST where the `value` string was the correct HTML, and when it was compiled by Gatsby something like `<span><div>Some stuff</div></span>` became `<span></span><div>Some stuff</div>`. (Re: div in span--best not to ask 😁 .)

Also my observation is similar to @pzatrick's: if the node in the AST is `type: html` the problem occurs, but if it's another type--like the `paragraph` his example will give you--it seems to work, even if that node has children that are themselves html types.

**Comment by bvaughn** [comment]
I _think_ I experienced this same thing just now, plugging the new `gatsby-remark-code-repls` plugin into the reactjs.org website. I wasn't seeing this issue while developing on a slightly outdated version of Gatsby (and plugins) and then I saw it after updating and installing the newly-released transform.

**Comment by dustinhorton** [comment]
Reduced test case: https://github.com/dustinhorton/gatsby-issue

Just run and visit [`http://localhost:8000/hi-folks`](http://localhost:8000/hi-folks). The first two paragraph should have a few links (authored in HTML), but the text is rendered outside the `a` tags.

**Comment by fk** [comment]
Haven't looked into it more, but [removing _gatsby-remark-copy-linked-files_](https://github.com/fk/gatsby-issue/tree/fix-issue) from `gatsby-config.js` seems to fix things:

![image](https://user-images.githubusercontent.com/21834/32636539-9009f52a-c5b5-11e7-81c6-39ede761be54.png)

**Comment by ptrikutam** [comment]
@fk's solution works great for me, however then `.gif` images no longer get copied over.

**Comment by prurph** [comment]
@fk interesting--I wonder if it has to do with the interplay of plugins that are editing the `markdownAST` after it is generated. I had this issue without gatsby-remark-copy-linked-files in my project but I was building a custom plugin that also `visit`ed all the nodes in the markdownAST and made some changes to them before returning the AST.

**Comment by fk** [comment]
Would have loved to fix this tonight, but got distracted and now gotta sleep. FWIW all HTML node tags (`<a>`, `<small>`…) seem to be always closed with gatsby-remark-copy-linked-files active via cheerio's `.html()` in https://github.com/gatsbyjs/gatsby/blob/ad0b4e8e5c504a1b1a2b3f86a60ff3b9a43189c0/packages/gatsby-remark-copy-linked-files/src/index.js#L254

e.g. an initial `node.value` of `<a href="https://www.gatsbyjs.org">` gets replaced by `<a href="https://www.gatsbyjs.org"></a>`.
