### ISSUE TITLE
gatsby-plugin-countly: We are trying to include Countly in our Gatsby site and it looks like this plugin is gone.

### ISSUE THREAD

**Issue by lipis** [gatsbyjs/gatsby#26969]
https://www.gatsbyjs.com/plugins/gatsby-plugin-countly/

What would be the best way to include it? What happened to the plugin?

P.S. It seems that it's removed from the repo, but still available on plugin search..

**Comment by LekoArts** [comment]
Thank you for opening this!

We're not the authors of the plugin and thus can't change the status on npm (e.g. deprecating it) or changing the tags that Algolia uses to index plugins. As long as they have certain tags and are not deprecated it'll be indexed and thus be available on the plugin search.

It seems like the source code is here: https://github.com/squarecat/gatsby-plugin-countly

You'll need to reference their documentation (https://support.count.ly/hc/en-us/articles/360037441932-Web-analytics-JavaScript-) and can also have a look at other tracking plugins how they integrate things.

On our repository we have examples like:

- https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-analytics
- https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-gtag
- https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-tagmanager
- https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-fullstory

You won't need to publish your own plugin (if you don't want to) as you can place it in a local plugins folder: https://www.gatsbyjs.com/docs/loading-plugins-from-your-local-plugins-folder/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
