### ISSUE TITLE
Error: The result of this StaticQuery could not be fetched

### ISSUE THREAD

**Issue by deoxyshub** [gatsbyjs/gatsby#26967]
## Description

Error: The result of this StaticQuery could not be fetched.
This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in (https://github.com/gatsbyjs/gatsby/issues)

- Production environment
- White page in some clients
- Mobile client for the most part

### Steps to reproduce

Impossible to reproduce, because it never happens in development with `gatsby develop`,  `gatsby build` and `gatsby serve`, neither in an NGINX instance in a Docker container and neither in browser with incognito mode (production).

### Expected result

Load the content of the pages 

### Actual result

White screen on some route pages

### Environment

```
Amazon CloudFront - Serverless website
NPM Packages
    "gatsby": "2.24.62",
    "gatsby-image": "2.4.19",
    "gatsby-plugin-alias-imports": "1.0.5",
    "gatsby-plugin-facebook-pixel": "1.0.3",
    "gatsby-plugin-load-script": "1.1.0",
    "gatsby-plugin-manifest": "2.4.30",
    "gatsby-plugin-offline": "3.2.28",
    "gatsby-plugin-preconnect": "1.1.54",
    "gatsby-plugin-react-helmet": "3.3.11",
    "gatsby-plugin-react-svg": "3.0.0",
    "gatsby-plugin-robots-txt": "1.5.2",
    "gatsby-plugin-sass": "2.3.13",
    "gatsby-plugin-sharp": "2.6.36",
    "gatsby-plugin-sitemap": "2.4.13",
    "gatsby-plugin-webfonts": "1.1.3",
    "gatsby-source-filesystem": "2.3.30",
    "gatsby-transformer-inline-svg": "0.0.7",
    "gatsby-transformer-sharp": "2.5.15",
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue! Sadly we can't do much without a reproduction and thus this issue is not actionable. You can follow https://github.com/gatsbyjs/gatsby/issues/26563 or comment there when you have a reproduction. Thanks!
