### ISSUE TITLE
No Indenting

### ISSUE THREAD

**Issue by ardalis** [gatsbyjs/gatsby#26960]
## Description

Code sections lose all indentation. Mainly using C#.

### Steps to reproduce

Full source: https://github.com/ardalis/ardalis-com-gatsby
Example Page: https://ardalis.com/group-your-constants-and-enums/
Source File: https://github.com/ardalis/ardalis-com-gatsby/blob/master/src/pages/blog/group-your-constants-and-enums.md

Sample code:
```csharp
public static class Constants {
    public static class EditorThemes
    {
        public const int LIGHT = 0;
        public const int DARK = 1;
        public const int PLAID = 2;
    }
// more stuff here
}
```

Result:
![image](https://user-images.githubusercontent.com/782127/93669491-a3cbc180-fa62-11ea-886c-505ee04d43df.png)

### Expected result

Code should retain its indentation.

### Actual result

All indentation lost.

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.3
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.20.35 => 2.21.9 
    gatsby-dynamic-image: ^0.2.0 => 0.2.0 
    gatsby-image: ^2.3.5 => 2.4.0 
    gatsby-plugin-feed: ^2.5.11 => 2.5.11 
    gatsby-plugin-google-tagmanager: ^2.3.4 => 2.3.4 
    gatsby-plugin-mailchimp: ^5.1.2 => 5.1.2 
    gatsby-plugin-material-ui: ^2.1.8 => 2.1.8 
    gatsby-plugin-netlify: ^2.2.4 => 2.3.0 
    gatsby-plugin-netlify-cms: ^4.2.5 => 4.3.0 
    gatsby-plugin-paginate: ^1.12.0 => 1.12.0 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^3.2.5 => 3.3.0 
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1 
    gatsby-plugin-sass: ^2.2.4 => 2.3.0 
    gatsby-plugin-sharp: ^2.5.7 => 2.6.0 
    gatsby-plugin-sitemap: ^2.4.5 => 2.4.5 
    gatsby-plugin-twitter: ^2.3.1 => 2.3.1 
    gatsby-remark-copy-linked-files: ^2.2.4 => 2.3.1 
    gatsby-remark-images: ^3.2.6 => 3.3.0 
    gatsby-remark-prismjs: ^3.5.13 => 3.5.2 
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0 
    gatsby-source-filesystem: ^2.2.5 => 2.3.0 
    gatsby-transformer-remark: ^2.8.13 => 2.8.13 
    gatsby-transformer-sharp: ^2.4.7 => 2.5.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.49

**Comment by LekoArts** [comment]
Thank you for opening this!

I created an example project at https://codesandbox.io/s/remark-prismjs-csharp-copwm and it's working as expected. Looking a bit at your CSS with the DevTools (on the live site) I saw that you overwrote the `white-space` attribute: https://github.com/ardalis/ardalis-com-gatsby/blob/master/src/components/style.css#L368

If you remove this line and keep the `white-space: pre-wrap;` it'll work as expected. So not an issue with Gatsby but your CSS :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by ardalis** [comment]
Ah, that could certainly do it. However, the reason that was added is that without it every code block started with a leading indentation. So, maybe that has magically disappeared but if not I may be sending another issue this way soon. :) 

Thanks!

**Comment by LekoArts** [comment]
As the codesandbox is not showing that behavior I guess this is also a (CSS) issue on your end then :)
