### ISSUE TITLE
Error while installing gatsby cli

### ISSUE THREAD

**Issue by pavan-elisetty** [gatsbyjs/gatsby#26975]
![image](https://user-images.githubusercontent.com/57026704/93763702-87c94b00-fc2f-11ea-985c-7e5205c2a4d3.png)

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi!

The error message says that it can't access npm. Please make sure that you have not blocked npm and have internet access and try again.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

[reproduction]: https://gatsby.dev/reproduction
