### ISSUE TITLE
Gatsby doesn't work with React 17 RC

### ISSUE THREAD

**Issue by gaearon** [gatsbyjs/gatsby#26979]
1. Update `react` and `react-dom` to `17.0.0-rc.1`
2. Update `gatsby` to latest
3. Run `yarn dev`

This is the result:

<img width="706" alt="Screenshot 2020-09-21 at 17 45 55" src="https://user-images.githubusercontent.com/810438/93796148-50a86900-fc32-11ea-917b-164cfbe98812.png">

While there's ongoing work to make Fast Refresh the default for compatible setups, in the meantime, can we figure out how to fix this error?

I'm guessing that what needs to happen is for https://github.com/hot-loader/react-dom/issues/41 to be solved by publishing a patched package. This is likely little work, but requires access to that package (cc @theKashey). I could do this myself if I had the instructions.

**Comment by theKashey** [comment]
Reason: `RHL` "hot-patch" was not applied to `createFiberFromTypeAndProps` and `AppContainer` was left _unpatched_ ("as is")
Tracked at: https://github.com/gaearon/react-hot-loader/pull/1557

**Comment by theKashey** [comment]
`hot-loader/react-dom`(17.0.0-rc.2) and `react-hot-loader`(4.13.0) were updated and should not cause the issue anymore.

**Comment by gaearon** [comment]
Thank you so much!

**Comment by gaearon** [comment]
Concretely, if you're running this error, the fix is to run `npm update`.

If this didn't help, delete your lockfile (`yarn.lock` or `package-lock.json`) and re-run your package manager.

**Comment by lnikell** [comment]
Still getting error that React is not defined after 'npm update', removing 'package-lock.json' and cache clean.

```
"gatsby": "^2.24.88",
"react": "^17.0.1",
"react-dom": "^17.0.1",
```

**Comment by gaearon** [comment]
>Still getting error that React is not defined 

This does not sound like the error described in this issue. File a new one?

**Comment by mikaelkristiansson** [comment]
> Still getting error that React is not defined after 'npm update', removing 'package-lock.json' and cache clean.
> 
> ```
> "gatsby": "^2.24.88",
> "react": "^17.0.1",
> "react-dom": "^17.0.1",
> ```

This is another error, and I created a issue for it:
https://github.com/gatsbyjs/gatsby/issues/27694

**Comment by sapkra** [comment]
I still have the same error but `react`, `react-hot-loader` and `@hot-loader/react-dom` already are at the latest version. Could there another reason?

**Comment by tony** [comment]
@sapkra I tried the solution thing and it didn't work for me. Would that `npm:@hot-loader/react-dom` part be compatible with yarn? (I'm yarn v1.22.5, node v12.20.0)

I still get this error with the latest gatsby

```
  "dependencies": {
    "@chakra-ui/core": "^1.0.0-rc.7",
    "@chakra-ui/theme": "1.1.0",
    "@chakra-ui/theme-tools": "^1.0.1",
    "@deckdeckgo/highlight-code": "^2.2.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@fortawesome/react-fontawesome": "^0.1.13",
    "@mdx-js/mdx": "<1.6.17",
    "@mdx-js/react": "<1.6.17",
    "@mdx-js/runtime": "<1.6.17",
    "@tippyjs/react": "^4.2.0",
    "base64id": "^2.0.0",
    "framer-motion": "^2.9.4",
    "gatsby": "2.27.2",
    "gatsby-image": "^2.6.0",
    "gatsby-plugin-advanced-sitemap": "^1.5.6",
    "gatsby-plugin-catch-links": "^2.5.0",
    "gatsby-plugin-chakra-ui": "^1.0.0-rc.7",
    "gatsby-plugin-exclude": "^1.0.2",
    "gatsby-plugin-google-gtag": "^2.3.0",
    "gatsby-plugin-manifest": "^2.7.0",
    "gatsby-plugin-mdx": "<1.2.40",
    "gatsby-plugin-meta-redirect": "^1.1.1",
    "gatsby-plugin-offline": "^3.5.0",
    "gatsby-plugin-react-helmet": "^3.5.0",
    "gatsby-plugin-s3": "^0.3.8",
    "gatsby-plugin-sass": "^2.6.0",
    "gatsby-plugin-sharp": "^2.9.0",
    "gatsby-plugin-typegen": "^2.2.1",
    "gatsby-plugin-typescript": "^2.7.0",
    "gatsby-plugin-web-vitals": "^1.0.3",
    "gatsby-plugin-webfonts": "^1.1.3",
    "gatsby-remark-autolink-headers": "^2.6.0",
    "gatsby-remark-highlight-code": "^2.1.0",
    "gatsby-remark-prismjs": "^3.8.0",
    "gatsby-source-filesystem": "^2.6.1",
    "gatsby-transformer-json": "^2.6.0",
    "gatsby-transformer-sharp": "^2.7.0",
    "gatsby-transformer-yaml": "^2.6.0",
    "moment": "^2.28.0",
    "moment-duration-format": "^2.3.2",
    "prismjs": "^1.22.0",
    "prop-types": "^15.7.2",
    "query-string": "^6.13.7",
    "react": "^17.0.1",
    "react-device-detect": "^1.14.0",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "react-swipeable": "^6.0.0",
    "url-join": "^4.0.1",
    "xss": "^1.0.8"
  },
  "devDependencies": {
    "@types/moment-duration-format": "^2.2.2",
    "@types/node": "^14.14.10",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@typescript-eslint/eslint-plugin": "^4.8.2",
    "@typescript-eslint/parser": "^4.8.2",
    "eslint": "^7.14.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-react": "^7.21.5",
    "gatsby-plugin-eslint": "^2.0.8",
    "prettier": "^2.2.0",
    "ts-node": "^9.0.0",
    "typescript": "^4.1.2"
  },
```

**Comment by sapkra** [comment]
@tony Have you really added it as an `resolution`? It not a dependency, it overrides dependencies of other packages. btw. I'm using yarn too.

**Comment by theKashey** [comment]
try finding `@hot-loader/react-dom` in `yarn.lock` and removing the record to get it updated to the latest version.
You can do the same by adding it as an explicit dependency to your project.

**Comment by emt-mocha** [comment]
I use NPM to install all my package.

I follow the steps at below: 

`npm install -g npm-check-updates
 ncu - u             // to update all the package to latest version
 npm install      // install the package

//during the npm package installations u will notice many warnings. Just ignore it.
// once the package update done, you need to delete the node_module folder again from your root directory. DO NOT DELETE "package-lock.json" !!!!
// final steps

npm ci  // once package updates complete follow the normal gatsby commands to start your development server.
 
// HOPE THIS HELPS :)
// in future if you use **ncu -u** again then you need to follow the entire steps.

`
