### ISSUE TITLE
Support Overrides in gatsby-plugin-canonical-urls

### ISSUE THREAD

**Issue by hs737** [gatsbyjs/gatsby#26978]
## Summary
I would like to introduce an `overrides` option in `gatsby-plugin-canonical-urls`. This plugin is really useful for adding the canonical tag across all the pages created in Gatsby. But it has an all-or-nothing approach about it. If I want just one page to reference another page, then I need to remove this plugin and manually add a canonical URL to every page. 

My proposal for an `overrides` tag will make this easier. I am not attached to the label `overrides`, if there is a better term for this (perhaps `originalReferences`?). Also, I am happy to enter a PR myself, although I have not contributed to this repo before, so I could use a little guidance. 

### Basic example

Currently the plugin, `gatsby-plugin-canonical-urls`, supports two options: `siteUrl` and `stripQueryString`
```js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-canonical-urls`,
      options: {
        siteUrl: `https://www.example.com`,
        stripQueryString: true,
      },
    },
  ],
}
```

I would like to see a third option that is `overrides`. This would then look like the following:
```js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-canonical-urls`,
      options: {
        siteUrl: `https://www.example.com`,
        stripQueryString: true,
        overrides: {
            "someSpecificUrl": "/",
            "someOtherPath/withSpecificUrl": "/page-2"
        }
      },
    },
  ],
}
```

All URLs not specified in this `overrides` object will operate using the existing logic.

### Motivation

The hope is to make this plugin more flexible and therefore more sticky. I am currently using this plugin, and now that I have one page with some duplicate content, I need to remove this plugin and add react-helmet to every one of my pages. 

I did a bit of research and I couldn't find anything, but let me know if there is already an existing, better alternative. I'm happy to hear feedback.

**Comment by herecydev** [comment]
Could you use `react-helmet` to override the canonical url for those pages? Or does it duplicate it? What's the use case for needing overrides?
