### ISSUE TITLE
Error when redirect route '/' to '/lang/'

### ISSUE THREAD

**Issue by orblazer** [gatsbyjs/gatsby#26988]
## Description

When i make localized paths like routes `/en/`, `/fr/`, etc, and for that i have delete the page `/` for recreate with localized path. But i have error when access to `/`.

### Steps to reproduce

1. Clone my repo https://github.com/orblazer/gatsby-i18n-issues/tree/page-errors (branch `page-errors`)
2. Run `gatsby develop`
3. Go to `http://localhost:8000/`
4. Open console and see errors

### Expected result

Redirect to `/{defaultLanguage}/` (like `/en/`) without error.

### Actual result

Two error is throwed when access to '/'
1. `The route "/" matches both a page and a redirect; this is probably not intentional.`
    This is come from https://github.com/gatsbyjs/gatsby/blob/1a7a446bf67e5d79cf62dbb67fc4610d7a1f198a/packages/gatsby/cache-dir/navigation.js#L25
2. 
    ```
    Uncaught Error: EnsureResources was not able to find resources for path: "/"
    This typically means that an issue occurred building components for that path.
    Run `gatsby clean` to remove any cached elements.
    ```
    This is come from https://github.com/gatsbyjs/gatsby/blob/030d927cddbdc64f8d93d409a5ada7442d5e62bf/packages/gatsby/cache-dir/ensure-resources.js#L79

### Environment

```
$ gatsby info --clipboard

  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.10.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.7 - /usr/bin/npm
  Languages:
    Python: 3.8.5 - /usr/bin/python
  Browsers:
    Firefox: 80.0.1
  npmPackages:
    gatsby: ^2.24.63 => 2.24.63
```

### Other

*I think i just no understand something.*
**Additional question :** how i can create an redirect the page like `/test` to `/en/test` (or `/en/404`) for localized error page ?

**Comment by ascorbic** [comment]
Hi. I think I've worked out what's wrong here, and I have opened a PR with a fix. However I should point out that as it stands it will not work even when the fix is in. The "Language" is a custom addition that only works for Netlify, and isn't supported for client redirects.
