### ISSUE TITLE
gatsby-plugin-manifest: incorrect SVG resizing

### ISSUE THREAD

**Issue by mvasilkov** [gatsbyjs/gatsby#26989]
## Description

[gatsby-plugin-manifest](https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/) resizes SVG incorrectly.

### Steps to reproduce

Add the following line to the plugin options:
```
  icon: `src/images/icon.svg`, // This path is relative to the root of the site.
```

Using the following SVG file as `icon.svg`:
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">
<defs><radialGradient id="a" cx="64" cy="-48" r="64" fx="64" fy="144" fr="64" gradientUnits="userSpaceOnUse"><stop offset=".3" stop-color="#e31587"/><stop offset=".47" stop-color="#ff3647"/><stop offset=".63" stop-color="#ff980e"/><stop offset=".95" stop-color="#fff44f"/></radialGradient></defs>
<path fill="url(#a)" d="M124.25 64l-4.59 23.06-13.06 19.54-19.54 13.06L64 124.25l-23.06-4.59L21.4 106.6 8.34 87.06 3.75 64l4.59-23.06L15.65 30l11.56-9.64 1.63 14.35 14.51-10.92.35 14.69L64 51.95 36.69 69.07l1.1 5.54 6.06 9.22 9.12 6.2L64 91.72l10.61-2.11 8.56-6.44 4.81-9.49.68-9.91-2.53-9.19-6.14-6.9-3.91-2.61 6.47.05 8.17 3.57-4.76-6.97L77.83 30l-1.84-15.43L82.68.23l4.38 7.5 18.55 22.81 8.11 13.86-2.62-9.89-3.29-8.12 5.06 4.39 6.79 10.16z"/>
</svg>
```

I put the SVG here for reference: https://codepen.io/mvasilkov/pen/LYNgXYy

### Expected result

Should generate apple-touch-icons properly from the SVG.

### Actual result

The generated icons (PNG) are bad:

![icon-512x512](https://user-images.githubusercontent.com/140257/93869325-53f43100-fcd4-11ea-9879-71bd1923a242.png)

### Environment

```
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 80.0.1
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.63 => 2.24.63 
```

**Comment by mvasilkov** [comment]
Update: it seems to work fine if I pin the latest `sharp` in `package.json`:
```
  "resolutions": {
    "sharp": "0.26.1"
  }
```

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
