### ISSUE TITLE
lots of paga-data.json errors logged (nginx), with paths using backslashes

### ISSUE THREAD

**Issue by derykmarl** [gatsbyjs/gatsby#26990]
I noticed when checking the nginx error logs I'm seeing a lot of lines like this:

`2020/09/22 11:35:59 [error] 42962#0: *17590 open() "/var/www/example.com/public/page-data\news\2018\07\page-data.json" failed (2: No such file or directory), client: IP.REDACTED, server: www.example.com, request: "GET /page-data\news\2018\07\page-data.json HTTP/1.1", host: "www.example.com"`

Not seeing any errors in the console in Chrome when visiting these pages though.  But I do note it uses backslashes after the path to page-data.

Any idea what's going on?

**Comment by wardpeet** [comment]
Seems like our paths are wrong when built on windows. I'll take care of it.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
