### ISSUE TITLE
'Duplicate "graphql" modules' error when developing a theme

### ISSUE THREAD

**Issue by stanislawosinski** [gatsbyjs/gatsby#27002]
## Description

I'm trying to convert a Gatsby plugin/starter I've been developing into a proper theme. I started with the [theme starter workspace](https://github.com/gatsbyjs/gatsby-starter-theme-workspace) and added the relevant code and plugin dependencies. All the code is available at https://github.com/carrotsearch/gatsby-theme-apidocs.

The theme appears to be working when published to the NPM and applied to an external Gatsby project, but I'm having problems applying the theme to the example project that is part of the theme starter workspace -- I'm getting the 'Duplicate "graphql" modules' error as shown below.

Is there anything obvious that I'm missing here?

### Steps to reproduce

The reproduction code is available at https://github.com/carrotsearch/gatsby-theme-apidocs.

```shell
git clone git@github.com:carrotsearch/gatsby-theme-apidocs.git
cd gatsby-theme-apidocs
yarn install
yarn develop
```

### Expected result

The development server should start without errors.

### Actual result

I'm getting the following error:

```
yarn run v1.22.5
$ yarn workspace example develop
$ gatsby develop
success open and validate gatsby-configs - 0.049s
success load plugins - 1.478s
success onPreInit - 0.029s
success initialize cache - 0.009s
success copy gatsby files - 0.150s
success onPreBootstrap - 0.021s
success createSchemaCustomization - 0.007s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.160s

 ERROR

Missing onError handler for invocation 'building-schema', error was 'Error: Cannot use GraphQLScalarType "JSON" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.'. Stacktrace was 'Error: Cannot use GraphQLScalarType "JSON" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (F:\tmp\gatsby-theme-apidocs\node_modules\graphql\jsutils\instanceOf.js:28:13)
    at isScalarType (F:\tmp\gatsby-theme-apidocs\node_modules\graphql\type\definition.js:103:34)
    at isOutputType (F:\tmp\gatsby-theme-apidocs\node_modules\graphql\type\definition.js:226:10)
    at isComposeOutputType (F:\tmp\gatsby-theme-apidocs\node_modules\graphql-compose\lib\ObjectTypeComposer.js:46:36)
    at ObjectTypeComposer.getField (F:\tmp\gatsby-theme-apidocs\node_modules\graphql-compose\lib\ObjectTypeComposer.js:232:38)
    at ObjectTypeComposer.getFieldExtensions (F:\tmp\gatsby-theme-apidocs\node_modules\graphql-compose\lib\ObjectTypeComposer.js:839:24)
    at ObjectTypeComposer.extendFieldExtensions (F:\tmp\gatsby-theme-apidocs\node_modules\graphql-compose\lib\ObjectTypeComposer.js:852:26)
    at ObjectTypeComposer.setFieldExtension (F:\tmp\gatsby-theme-apidocs\node_modules\graphql-compose\lib\ObjectTypeComposer.js:873:10)
    at forEach (F:\tmp\gatsby-theme-apidocs\node_modules\gatsby\src\schema\schema.js:478:20)
    at Array.forEach (<anonymous>)
    at addExtensions (F:\tmp\gatsby-theme-apidocs\node_modules\gatsby\src\schema\schema.js:477:34)
    at processAddedType (F:\tmp\gatsby-theme-apidocs\node_modules\gatsby\src\schema\schema.js:417:3)
    at forEach (F:\tmp\gatsby-theme-apidocs\node_modules\gatsby\src\schema\schema.js:298:11)
    at Array.forEach (<anonymous>)
    at addTypes (F:\tmp\gatsby-theme-apidocs\node_modules\gatsby\src\schema\schema.js:248:9)
    at updateSchemaComposer (F:\tmp\gatsby-theme-apidocs\node_modules\gatsby\src\schema\schema.js:135:9)
    at buildSchema (F:\tmp\gatsby-theme-apidocs\node_modules\gatsby\src\schema\schema.js:62:9)
    at build (F:\tmp\gatsby-theme-apidocs\node_modules\gatsby\src\schema\index.js:105:24)
    at buildSchema (F:\tmp\gatsby-theme-apidocs\node_modules\gatsby\src\services\build-schema.ts:19:3)'

⠇ building schema
```

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (32) x64 Intel(R) Core(TM) i9-7960X CPU @ 2.80GHz
  Binaries:
    Node: 12.14.1 - ~\AppData\Local\Temp\yarn--1600861424734-0.8943478381582799\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1600861424734-0.8943478381582799\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.102
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.51)

**Comment by vladar** [comment]
Hi @stanislawosinski !

Usually, this error means that you have multiple versions of the `graphql` package in your project. But I've just followed your steps to reproduce and it worked fine for me. So this is likely some issue with dependency installation.

Maybe you've run `npm install` previously which messed up your `node_modules`? I have the same `yarn.lock` so it should be the same for me.

What you can try is:

1. Run `yarn why graphql` to see all packages that require graphql (and post the output here)
2. Remove `node_modules` and run `yarn install` again in the project root

Let me know if it helps. Thanks for using Gatsby 💜

**Comment by stanislawosinski** [comment]
Hi @vladar !

The problem is that this is happening on the fresh checkout, so this is probably not a case of stale `node_modules`. Just to make sure I removed `yarn.lock` and `node_modules` from the checkout, ran `yarn install` and `yarn develop` still gives me the same error.

I include output of `yarn why graphql` below. Maybe there's some problem in the dependencies of the theme or the plugins the theme uses, I just don't know how to diagnose it.

```
yarn why v1.22.5
[1/4] Why do we have the module "graphql"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "graphql@14.7.0"
info Reasons this module exists
   - "_project_#example#gatsby" depends on it
   - Hoisted from "_project_#example#gatsby#graphql"
   - Hoisted from "_project_#example#gatsby#gatsby-plugin-page-creator#graphql"
   - Hoisted from "_project_#example#gatsby#gatsby-cli#gatsby-recipes#graphql"
info Disk size without dependencies: "3.06MB"
info Disk size with unique dependencies: "3.16MB"
info Disk size with transitive dependencies: "3.16MB"
info Number of shared dependencies: 1
Done in 1.10s.
```

**Comment by vladar** [comment]
I am puzzled as I can't reproduce it on a fresh setup. Maybe try creating a project on https://codesandbox.io to make sure we're on the same page?

**Comment by stanislawosinski** [comment]
Oh, thanks for the confirmation that it works for you. This must be something local then (same thing on two machines though :-)), let me dig into this. Is it possible that a global gatsby-cli install might be the cause?

**Comment by stanislawosinski** [comment]
> Is it possible that a global gatsby-cli install might be the cause?

Probably not, I don't have a global gatsby-cli on one of the failing machines. Weird.

**Comment by stanislawosinski** [comment]
This is reproducible only on my two Windows desktops, other machines work fine, weird indeed. Closing but still curious what the reason is.

**Comment by vladar** [comment]
I am on windows too and couldn't reproduce this. Maybe `gatsby-cli` uses some globally installed GraphQL package (not the project-specific one)? Check if you have graphql installed globally maybe and which version it has?

Still pretty weird 🤷‍♀️

**Comment by stanislawosinski** [comment]
I removed all the globals and still no luck.

To make things even weirder, if I do `yarn install` in Git Bash (on my Windows workstation), then `yarn develop` works fine both in Bash and cmd. If I do `yarn install` in cmd, then `yarn develop` throws the exception in both Bash and cmd.

I checked that both Bash and cmd use the same yarn binaries:

```shell
$ which yarn
/c/Program Files (x86)/Yarn/bin/yarn

where yarn
C:\Program Files (x86)\Yarn\bin\yarn
C:\Program Files (x86)\Yarn\bin\yarn.cmd
C:\Program Files (x86)\Yarn\bin\yarn.js
```

Super weird, but at least I have a workaround now. If you can think of any debug output I could use to satisfy my curiosity regarding the problem, let me know :-)
