### ISSUE TITLE
Code Split in Gatsby

### ISSUE THREAD

**Issue by developer0116** [gatsbyjs/gatsby#27000]
Currently I am building up a website using Gatsby and I need to optimize the performance in mobile devices.

I want to minimize the main thread work, but code split is not supported in Gatsby.

Look forward to your support.

Thanks

**Comment by usamahbass** [comment]
Hay @developer0116 try you back to this issue [https://github.com/gatsbyjs/gatsby/issues/11960](url) or this link [https://www.gatsbyjs.com/docs/how-code-splitting-works](url) or [https://github.com/gatsbyjs/gatsby/issues/18689](url) , hope it can help :)

**Comment by LekoArts** [comment]
Thank you for opening this!

As https://www.gatsbyjs.com/docs/how-code-splitting-works/ explains Gatsby supports and does code-splitting by default. If you further want to remove expensive parts from the initial bundle you can lazy-load those pieces. For example with `loadable-components` or React.lazy().

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
