### ISSUE TITLE
improve docs explaining about how retrieve the state from route

### ISSUE THREAD

**Issue by daniloab** [gatsbyjs/gatsby#27025]
## Summary
Improve navigate docs to understand more easily how to retrieve state set on the route by `navigate` help.

### Motivation
Trying to implement the navigate helper to set a `state` on my router I've found some difficulty retrieving this state after being redirected.

I had a function after success redirects the user to another page. But on this page, I need to know the email from this user. To solve this I use the navigate helper:

`navigate('/next/route/, { state: { email } })`

My difficulty is on `next/route` component. There I can't find on docs how to retrieve this state. Looking on docs, issues, and core code from gatsby link API I found these solutions below:

- use window native history `window.history.state` https://github.com/gatsbyjs/gatsby/issues/9091
- importing `useLocation from @reach/router`

```
import { useLocation } from '@reach/router'

const App = () => {
  const location = useLocation();

  console.log('location.state', location.state);

  return (
   ...
  )
}
```

## Steps to resolve this issue
I would like to know what is the best way to handle this case

**Comment by vitordino** [comment]
@daniloab i think this state is passed to the page component (or whatever template you used to render) can you check all props that the page/template is recieving?

**Comment by daniloab** [comment]
@vitordino I checked but I was receiving only an empty object `{}`

**Comment by pindjur** [comment]
see  [pass state as props to linked page](https://www.gatsbyjs.com/docs/gatsby-link/#pass-state-as-props-to-the-linked-page)
