### ISSUE TITLE
how to add image in gatsby

### ISSUE THREAD

**Issue by daniyal8** [gatsbyjs/gatsby#27026]
### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by dawood6** [comment]
you can add image in gatsby as you can add in reat like:

import logo from './logo.svg

and in return (
<img src={logo} />
)

**Comment by daniyal8** [comment]
> you can add image in gatsby as you can add in reat like:
> 
> import logo from './logo.svg
> 
> <img src={logo} => like this />

thank you so much
