### ISSUE TITLE
Update analytics doc to include google-plugin-gtag

### ISSUE THREAD

**Issue by meganesu** [gatsbyjs/gatsby#27065]
## Summary

The existing [docs about adding Google analytics](https://www.gatsbyjs.com/docs/adding-analytics/) recommend using the `gatsby-plugin-google-analytics`. Under the hood, this plugin uses Google's `analytics.js` file.

However, Google has a [guide recommending users upgrade to `gtag.js` instead](https://developers.google.com/analytics/devguides/collection/upgrade/analyticsjs). There is another plugin ([`gatsby-plugin-gtag`](https://www.gatsbyjs.com/plugins/gatsby-plugin-gtag/)) which uses `gtag.js`.

### Motivation

The `gtag.js` file works with all Google services. Here are a few resources with more information about the difference between `gtag.js` and `analytics.js`:

- [Google FAQ about `gtag.js`](https://support.google.com/analytics/answer/7509746)
- [What’s the Difference Between analytics.js, gtag.js & ga.js? (Daan van den Bergh)](https://daan.dev/wordpress/difference-analyics-gtag-ga-js/)

## Steps to resolve this issue

- [ ] Update the [Google analytics docs](https://www.gatsbyjs.com/docs/adding-analytics/) to add a section about "Using `gatsby-plugin-gtag`".

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #27065" in the pull request description

**Comment by meganesu** [comment]
There's still an open question around what to do with the existing section for how to use `gatsby-plugin-google-analytics`.

* Option 1: Keep the section, and add some guidance on how users should decide whether to use `gatsby-plugin-google-analytics` or `gatsby-plugin-gtag`.
* Option 2: Always recommend using `gatsby-plugin-gtag`. Remove the section on `gatsby-plugin-google-analytics` and instead list it under the "Other Gatsby analytics plugins" section.

**Comment by 98lenvi** [comment]
Hi @meganesu, I can help with this! Can you assign the issue to me?

I think going with option 1 will be a better choice.

**Comment by wardpeet** [comment]
@meganesu I would try to promote gtag as much as we can (option 2). If you follow Google's developer docs and/or copy-paste from analytics itself you get a gtag code and not an analytics code anymore.

I don't think our docs need to be talking about the difference between gtag or analytics. It would only confuse people. We don't want to give users to many options :joy:, users who are invested in analytics probably already know the difference or google about it. We could add a note to the readme files of the plugins so it's documented somewhere.

**Comment by meganesu** [comment]
@wardpeet sounds good, thanks for the recommendation!

@98lenvi thanks for tackling this issue. Could you please update your PR to match @wardpeet's recommendation? Feel free to reach out if you have any questions about the changes.

**Comment by 98lenvi** [comment]
@meganesu, Hi! can you check the PR now? I have made the changes.

**Comment by akgupta0777** [comment]
Is this necessary that the issue assigned to somebody only He/She can do?
I am new to Github and Open Source Development.

@LekoArts

**Comment by LekoArts** [comment]
@akgupta0777 When an issue can only be fixed by one PR (which is the case here) it's common etiquette that a person offers their help and then picks up the work. This should be communicated clearly in the issue so that other people who want to help see that it's already being addressed and not duplicate PRs are opened. To make things clearer we ("Gatsby") assign issues to people then.

You can still help out by leaving review comments on the PR (although most of the time the core maintainers do that).

If the person who initially signed up for sending in a PR didn't do that after quite some time (OSS is most of the times in the free time of people so don't expect anyone to instantly create things) you could ask in the issue if you instead could pick it up (or any other person).

**Comment by akgupta0777** [comment]
Thanks I understood now.

**Comment by muescha** [comment]
i think we should also update the readme in [gatsby-plugin-google-analytics](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-analytics#readme)

**Comment by akgupta0777** [comment]
Can I do this thing updating in readme task ?

**Comment by muescha** [comment]
@akgupta0777 sorry i did read your help to late :(

i have done a PR 
- #28918 `chore(docs): google plugin analytics - upgrade to gtag, fix code`

**Comment by akgupta0777** [comment]
@muescha It's ok, not a problem.
