### ISSUE TITLE
gatsby createSchemaCustomization API in typescript

### ISSUE THREAD

**Issue by yudyananda** [gatsbyjs/gatsby#27096]
My motivation is to convert `gatsby-node.js` to typescript then split up into separate module #21209 it's working as i expected (onCreateNode and createPages) but typescript start to complain when i try to create `createSchemaCustomization`

![schema](https://user-images.githubusercontent.com/29258979/94342554-fa756480-003b-11eb-8938-4e6c8117aed2.jpg)

try to run develop but no luck

```bash
// console error
Error in "E:\user\web_project\dev\gatsby-node.ts": ⨯ Unable to compile TypeScript:
gatsby-node.ts:17:14 - error TS2322: Type '({ actions, schema }: { actions: any; schema: any; }) => void' is not assignable to type '{ (args: CreateSchemaCustomizationArgs, options: PluginOptions): any; (args: CreateSchemaCustomizationArgs, options: PluginOptions): Promise<...>; (args: CreateSchemaCustomizationArgs, options: PluginOptions, callback: PluginCallback): void; }'.
  Type 'void' is not assignable to type 'Promise<any>'.
```

```typescript
// gatsby-node.ts
import { GatsbyNode } from 'gatsby'
const generatePages = require('./src/gatsby_api/createPages')
const generatePosts = require('./src/gatsby_api/createPosts')
const generateNodes = require('./src/gatsby_api/createNodes')

const sections = [generatePages, generatePosts]
const sectionNodes = [generateNodes]

export const onCreateNode: GatsbyNode['onCreateNode'] = helpers => {
    sectionNodes.forEach(sectionNode => sectionNode.onCreateNode(helpers))
}

export const createPages: GatsbyNode['createPages'] = async helpers => {
    await Promise.all(sections.map(section => section.createPages(helpers)))
}

export const createSchemaCustomization: GatsbyNode['createSchemaCustomization'] = ({actions, schema}) => {
    ...
}
```

Any idea?

**Comment by herecydev** [comment]
I'm certain you can't use TypeScript in any gatsby-X files yet. Currently it's only your "userland" files, i.e. pages. Hope that helps

**Comment by sidharthachatterjee** [comment]
Yup, like @herecydev correctly mentioned, TypeScript doesn't work in `gatsby-*` files yet...

**Comment by yudyananda** [comment]
ok then looks like I have to wait, thank you for the clarification

**Comment by ko1imai** [comment]
I'm not sure if you have resolved this. Anyway, I would like to let you know what I did successfully.
if you use `: GatsbyNode['createSchemaCustomization’]` the function is expected to return Promise as you see. if you use only `createTypes`, it is not necessary to handle this as an async function. I made it as follows and I was able to build it successfully.

```
export const createSchemaCustomization: ({ actions }: { actions: Actions }) => void = ({
  actions,
}: {
  actions: Actions;
}): void => {
  const { createTypes } = actions; // eslint-disable-line @typescript-eslint/unbound-method

  createTypes(`
    type SiteSiteMetadata {
      author: Author
      siteUrl: String
      social: Social
    }
    ...
```

Hope you resolve this case.
