### ISSUE TITLE
CSS caching issue

### ISSUE THREAD

**Issue by SubstanceP** [gatsbyjs/gatsby#27102]
=
## Description

CSS not updating on live site called scientifikz.io (using foreign domain via nameservers).  The old CSS is still apparent regardless of changes made to global.css
To attempt to update I use:
gatsby develop

**gatsby build**
success open and validate gatsby-configs - 0.016s
success load plugins - 0.057s
success onPreInit - 0.024s
success delete html and css files from previous builds - 0.004s
success initialize cache - 0.008s
success copy gatsby files - 0.016s
success onPreBootstrap - 0.006s
success createSchemaCustomization - 0.005s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.028s
success building schema - 0.153s
success createPages - 0.003s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.042s
success update schema - 0.023s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.014s
success write out redirect data - 0.002s
success onPostBootstrap - 0.002s
info bootstrap finished - 2.634s
success run page queries - 0.016s - 1/1 63.07/s
success write out requires - 0.003s
success Building production JavaScript and CSS bundles - 4.675s
success Rewriting compilation hashes - 0.003s
success Building static HTML for pages - 0.745s - 1/1 1.34/s
success onPostBuild - 0.002s
info Done building in 8.178 sec

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

The CSS should be updated to the correct text colors.

### Actual result

checked scientifikz.io and the CSS has not changed.  The text color should be white for paragraphs and lightgreen for headers. 

### Environment

System:
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 80.0.1
  npmPackages:
    gatsby: ^2.24.54 => 2.24.54
    gatsby-plugin-typography: ^2.5.11 => 2.5.11
  npmGlobalPackages:
    gatsby-cli: 2.12.100

**Comment by AdamSiekierski** [comment]
Maybe clean your browser cache? The colors you described are visible on the page.

![image](https://user-images.githubusercontent.com/24841038/94360084-4f9c8f00-00ab-11eb-963d-96059f27154a.png)

**Comment by LekoArts** [comment]
Thank you for opening this!

As Adam said I'm also seeing the white paragraph text and green headings. You'll need to check your deployment, cache headers or local cache/browser cache in cases like these. So this is not an issue with Gatsby itself.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
