### ISSUE TITLE
How to remove comments on production build

### ISSUE THREAD

**Issue by arualana** [gatsbyjs/gatsby#27123]
This is my gatsby-node.js file

exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === 'build-javascript') {
    actions.setWebpackConfig({
      devtool: false
    })
  }
  actions.setWebpackConfig({
    optimization: {
      minimize: false
    }
  })
.....

How would I have the comments removed on the production build?

I am looking at this https://github.com/webpack/webpack/issues/6879 for webpack, but don't know how to add it.

Thank you

**Comment by herecydev** [comment]
It should be done already for you if you run `gatsby build`. Are you not seeing this?

**Comment by arualana** [comment]
@herecydev It doesn't, may it have anything to with it this in the node js?

```
optimization: {
  minimize: false
}
```

**Comment by herecydev** [comment]
Well yes that would turn all minification off so comments will remain

**Comment by arualana** [comment]
Yes @herecydev , sorry for the dumb question, will close now
