### ISSUE TITLE
gatsby-source-contentful images

### ISSUE THREAD

**Issue by attfarhan** [gatsbyjs/gatsby#2712]
I notice in the example GraphQL query in gatsby-source-contentful, you can simply query the image field in `allContentfulProducts` and choose resolution and so on:
```
allContentfulProduct {
    edges {
      node {
        id
        productName
        image {
          responsiveResolution(width: 100) {
            width
            height
            src
            srcSet
          }
        }
      }
    }
  }
}
```

I have a media field in my schema, that I’d expect to work the same way, however I get a bunch of null values despite having values in the posts in Contentful, and I can’t query for responsiveResolution, for example. 

So the question here is twofold:
1) Should I expect the gatsby-source-contentful plugin to handle fetching media fields like this?
2) What type should an image field be in Contentful for the gatsby-source-contentful plugin to be able to query the image like in the example above?

**Comment by attfarhan** [comment]
Figured out the problem: seems like even though the image in my content type is not a required field, all instances of this content type must have some value in the image field defined, otherwise it won't work.  Will leave this open since it seems like this has yet to be reported.

**Comment by KyleAMathews** [comment]
>all instances of this content type must have some value in the image field defined, otherwise it won't work

I don't see how this could be true. Please double-check that this is true? E.g. create a new content item without an image and see if all the other content types stop working.

**Comment by attfarhan** [comment]
Tried reproducing and couldn't, and couldn't figure out what the actual issue was. Closing, sorry for the late reply!

**Comment by MarcCoet** [comment]
@attfarhan could you delete your cache and public folders and try again pretty please?

It seems to me that it is the same old issue (like #2392 and a few others before this one). I would really like to know if this is fixed but since I had to hack the contentful plugin to work for my usecase it is not an easy task to just test the last version.
