### ISSUE TITLE
Hosting a gatsby site on cPanel (Shared Hosting)

### ISSUE THREAD

**Issue by AjayDhimanELS** [gatsbyjs/gatsby#27138]
I have a gatsby site (with node.js and express for little backend)

**What I have done so far :**
The project is copied on the cPanel. and the `gatsby-config.js` was changed with the appropriate changes(mysql connections and other plugins). 
My simple/noob question is that `gatsby run develop` on cPanel teminal runs the site on `http://localhost:8000/`. 

How can I change this? I want to run this on my domain. 

How can I make this right? Also, what is the best way to host gatsby+node.js+express on a shared hosting? Couldn't find any good doc/article on this. Thanks a ton.

**Comment by LekoArts** [comment]
Thank you for opening this!

As outlined in https://www.gatsbyjs.com/docs/preparing-for-deployment/ you'll want to run `gatsby build` and copy the `public` folder to your folder that holds the contents of your website (e.g. `www`). Gatsby's output isn't special in any way, it's just HTML, CSS and JS so any guide that explains how to host these files will work with Gatsby, albeit you'll need to run `gatsby build` first and copy the contents from A => B somewhere.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by AjayDhimanELS** [comment]
@LekoArts I can't run `gatsby develop` with the hosted db config. When I change the `gatsby-config.js` with the hosted db config, It says  `Error establishing db connection ER_BAD_DB_ERROR: Unknown database '<Hosted_DB_Name>'`. How can I resolve this then? 
I'm confused. Please help.
Thanks.
