### ISSUE TITLE
react-helmet className doesn't work

### ISSUE THREAD

**Issue by cpboyd** [gatsbyjs/gatsby#27142]
## Description

I'm trying to easily use different styles for the home page.

### Steps to reproduce

Add `react-helmet` and:

```jsx
    <Helmet htmlAttributes={{ className: 'home' }} bodyAttributes={{ className: 'root' }} />
```

Repro: https://github.com/cpboyd/gatsby-helmet-bug

### Expected result

The `className` should be properly reflected to `class` on the `html` or `body` tag (depending on `htmlAttributes` or `bodyAttributes` respectively).

### Actual result

Unfortunately, while `gatsby build`/SSR renders it properly, the browser component writes it to the `classname` attribute rather than `class`. This means that it matches whatever the first loaded page is.

Changing `className` to `class` works, but doesn't match `react-helmet`'s documentation:
https://github.com/nfl/react-helmet/blob/2aecac5d0df4bc208fb11394e867b1b1ddcd5a5f/src/Helmet.js#L18

### Environment

Run `gatsby info --clipboard` in your project directory:
```
  System:
    OS: macOS 11.0
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.121
    Edge: 85.0.564.63
    Firefox: 80.0.1
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.24.63 => 2.24.63
  npmGlobalPackages:
    gatsby-cli: 2.12.100
```

**Comment by sidharthachatterjee** [comment]
Seems to me like this is a bug in `react-helmet` and not `gatsby`?

**Comment by cpboyd** [comment]
@sidharthachatterjee `react-helmet` does have an open issue about how `toString()` and `toComponent()` behave differently: https://github.com/nfl/react-helmet/issues/300

`gatsby-plugin-react-helmet` uses `toComponent()` in SSR :https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-react-helmet/src/gatsby-ssr.js

Shouldn't the plugin have a similar setup for `gatsby-browser.js` to eliminate the SSR and browser discrepancies?

**Comment by cpboyd** [comment]
Closing in place of https://github.com/nfl/react-helmet/issues/618
