### ISSUE TITLE
Change url/path of page 

### ISSUE THREAD

**Issue by adiusz** [gatsbyjs/gatsby#27168]
Hello there.
I decided to post this question here, since I found this issue very popular.
So I'm using gatsby-plugin-intl for internationalization my website but since plugin's author stopped answering on Github issues I'm gonna ask here. So the thing is it didnt allow you to translate pages' url/path. I'm wondering if it is possible to use onCreatePages to translate url/path of pages? For example: I have 2 paths of /about.js page - /en/about and /es/about and I want to convert es/about to es/sobre. Any idea how to achieve this?

**Comment by herecydev** [comment]
Something like:

```
exports.onCreatePage = ({ page, actions }, pluginOptions) => {
  if (page.context.locales) {
    return;
  }

  const { createPage, deletePage } = actions;
  deletePage(page);

  if(page.path === "es/about") {
    createPage({
      ...page,
      path: "es/sobre",
    });
  }
};
```

**Comment by adiusz** [comment]
Thanks @herecydev, it works fine like this:

```
module.exports.onCreatePage = ({ page, actions }) => {
  const { createPage, deletePage } = actions;

  if(page.path === "/en/about/") {
    deletePage(page);
    createPage({
      ...page,
      path: "es/sobre/",
    });
  }
};
```

but unfortunetly it doesn't solve problem entirely. Link from gatsby-plugin-intl doen't know how to map the urls when switching  currentLocale... 
Perfect solution would be arrays of paths, but I find it hard to implement.

**Comment by herecydev** [comment]
Yer it's difficult when the plugin has to manage page creation and linking. I'm fairly knowledgable on this because I've created a package that provides a similar outcome: https://github.com/herecydev/gatsby-plugin-internationalization

Solving translation of routes is non-trivial, but it is possible. Some configuration would have to be provided to alter route names. There's also rumblings of file system routing that might help/hinder the design of that: https://github.com/gatsbyjs/gatsby/pull/24463

**Comment by LekoArts** [comment]
Thank you for opening this!

While it might feel tempting to open issues here, we don't maintain said plugin and thus can't help with specific issue on it. You'll also need to recognize that most open-source packages are maintained by people in their free-time so there shouldn't be any expectations that you get answers immediately. The initial question of yours was answered and as Dan said your request is non-trivial -- which might be the reason why the plugin in question hasn't implemented it yet.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
