### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by Kolkies** [gatsbyjs/gatsby#27178]
Does Gatsby do something special this year like last year with hacktoberfest?
[https://www.gatsbyjs.com/blog/2019-10-08-hacktoberfest-2019/](https://www.gatsbyjs.com/blog/2019-10-08-hacktoberfest-2019/)

**Comment by LekoArts** [comment]
Hi, thanks for asking! We'll have something planned for this year and will announce it on [Twitter](https://twitter.com/gatsbyjs?lang=de) and on the [blog](https://www.gatsbyjs.com/blog/) so keep a look at that :)

**Comment by Kolkies** [comment]
Nice! I'll keep an eye out!
