### ISSUE TITLE
Gatsby-CLI Peer Dependencies issue?

### ISSUE THREAD

**Issue by blangsmgi** [gatsbyjs/gatsby#27172]
## Description

My terminal window shows a long list of missing peer dependencies on a fresh install of Gatsby-CLI:

![image](https://user-images.githubusercontent.com/48220374/94586943-bd28f680-0236-11eb-9f21-4d02e499836f.png)

As far as I know it's not best practice to install some of these packages globally. I think this may be a bug?

### Steps to reproduce
I have just installed Gatsby-CLI as per the documentation
`npm install -g gatsby-cli`

I wanted to see what else I had globally installed, so I ran
`npm list -g --depth 0`

Terminal window displays the long list of missing peer dependencies as shown above.

### Expected result

No errors for missing peer dependencies

### Actual result

Long list of missing peer dependencies

### Environment

  System:
    OS: Linux 4.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
    npm: 6.14.8 - /usr/bin/npm
  npmGlobalPackages:
    gatsby-cli: 2.12.101

**Comment by blangsmgi** [comment]
### Another Attempt
Tried again on my home iMac just now.

I again used the command to install Gatsby CLI globally. Here is the result of the installation:

![image](https://user-images.githubusercontent.com/48220374/94623249-9c799480-0268-11eb-984a-b1d89d93ec49.png)
![image](https://user-images.githubusercontent.com/48220374/94623273-ab604700-0268-11eb-9f6e-9c0a4e44d364.png)

Installation was successful, but followed by a ton of warnings. And again, checking what was installed globally shows a long list of missing peer dependences:

![image](https://user-images.githubusercontent.com/48220374/94623342-cfbc2380-0268-11eb-81cd-55686c3a0d79.png)

### Environment
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 81.0
    Safari: 14.0
  npmGlobalPackages:
    gatsby-cli: 2.12.101

**Comment by wardpeet** [comment]
Thank you, we're aware and currently fixing the situation :)

Both PRs should fix the issue:
https://github.com/gatsbyjs/gatsby/pull/27058
https://github.com/gatsbyjs/gatsby/pull/27057

**Comment by blangsmgi** [comment]
Good to hear. Thank you!

**Comment by suato** [comment]
i have the same issue just like the mac user but I use a windows system and mine just occurred now
