### ISSUE TITLE
Gatsby Theme Shadowing Not Pulling In SCSS File

### ISSUE THREAD

**Issue by DannyHinshaw** [gatsbyjs/gatsby#27185]
## Description

I have a mono-repo where I plan to have a few different layout themes as well as a few different color themes, the main idea being that I will be able to combine different layouts and color themes to create unique themes. However, I am running into a seemingly fundamental issue with how Gatsby themes work, that is, I cannot get shadowed SCSS (or CSS) files to be substituted out where they should be.

### Steps to reproduce

I've created a repo to reproduce my issues, [`test-gatsby-themes`](https://github.com/DannyHinshaw/test-gatsby-themes). The instructions for reproduction are in the README there and should be straightforward and simple enough (if not let me know).

The basic gist of the problem (as defined in the repro repo) is that `gatsby-layout-default` should be importing `gatsby-theme-light`, which does appear to be happening as I have a log statement in `gatsby-theme-light/gatsby-config.js` that does indeed log successfully. However, the SCSS file at `gatsby-theme-light/src/theme/styles.scss` is NOT overwriting/shadowing the SCSS file at the same location at `gatsby-layout-default/src/theme/styles.scss`.

I'm stumped as to what I'm missing, according to everything I've read this should work.

### Expected result

The SCSS file at `gatsby-theme-light/src/theme/styles.scss` should overwrite the file at `gatsby-layout-default/src/theme/styles.scss` as `gatsby-layout-default` imports `gatsby-theme-light`.

### Actual result

The import appears to happen as the log statement in `gatsby-theme-light/gatsby-config.js` does log successfully, however, the SCSS file never overwrites the base file at the shadowed path.

### Environment

```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 80.0.1
    Safari: 13.1.2
```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

I think I understand what you're trying to do and looked at your repository -- the behavior you're looking for can't work this way because you're shadowing incorrectly.

For brevity sake I'll stick to `default` and `light`.

So you want your `light` theme to override the `default` theme. But you're importing `light` into `default`. It needs to be the other way around.

Once you use `default` in the `light` theme, you can create a scss file at `src/default/theme/styles.scss` in the `light` theme. This way you shadow the `default` style file.

Some real-world examples for this:

https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-minimal-blog/src/%40lekoarts/gatsby-theme-minimal-blog-core/components

`gatsby-theme-minimal-blog` shadows components from the `-core` theme and then in the starter people could shadow files for both themes.

---

I guess what you really want to do is to simply import the scss file from the `light` theme into the scss file of the `default` one.

**Comment by DannyHinshaw** [comment]
@LekoArts hello, thank you for your reply. I'm still a bit puzzled by this, I feel like the documentation could be a little clearer about how to order the imports, nevertheless I've tried a few different things and none have worked.

Firstly, I need to make a correction, I didn't describe the original import order correctly in my initial report (which you may have seen looking at the repo but I will go ahead and explain), I had originally said that `site` imports `layout` which imports `theme`, but what was actually happening was `site` was importing (in order) `layout` and then `theme`. So assuming the order is the problem like you described [I have tried the reorder here](https://github.com/DannyHinshaw/test-gatsby-themes/blob/reorder-site-imports/gatsby-site/gatsby-config.js) but the result is the same with no shadowing/overriding of the theme SCSS file.

Now I know the previous attempt isn't exactly how you described to go about but I thought it may work considering the order issue. Nonetheless, I have also attempted to do literally what you said to do (or at least how I interpreted it) which is have `site` import `theme` which then imports `layout` [in this branch here](https://github.com/DannyHinshaw/test-gatsby-themes/tree/site-theme-layout), and again, the result is the same.

Finally for completeness I am completely flipping the original design on its head and reordered the imports to `theme` imports `layout` which imports `site` [on this branch here](https://github.com/DannyHinshaw/test-gatsby-themes/tree/complete-flip), where I am now using the `theme` package as the base package where I run the `develop` command but the result is (again) the same.

What am I missing here? How do I get this to work?

> I guess what you really want to do is to simply import the scss file from the light theme into the scss file of the default one.

Yes, that hard coded solution would work but completely misses the point of why I am attempting to do this with themes, that is, the combination of "themes" won't be known until build time so it needs to be handled dynamically at build time.

**Comment by DannyHinshaw** [comment]
@LekoArts I just saw what I was missing in your post, specifically that I need I needed to add another directory level to the light theme package: `src/gatsby-layout-default/theme/styles.scss` not just `src/theme/styles.scss`.

Once I added that extra layer `gatsby-layout-default` it does indeed work on the `site-theme-layout` branch. While re-reading the documentation for 100th time I see it does mention this as well, I'm not sure how my brain skipped that step completely for so long, but here we are.

I'll leave the last post as is in case other confused individuals run into this.

Thanks!

**Comment by DannyHinshaw** [comment]
I will just not one more thing, my original design does indeed also work by just adding that extra shadow directory layer, so the problem doesn't appear to have been the order of imports at all, just that missing directory level.

You can see it [here on master branch](https://github.com/DannyHinshaw/test-gatsby-themes).

**Comment by LekoArts** [comment]
Glad to hear that you sorted out your problem! I didn't account for the `site` in my answer but yeah, if you have the correct path the shadowing will work :)
