### ISSUE TITLE
Using Link from @reach/router is broken in Dev-Mode since 2.24.65

### ISSUE THREAD

**Issue by jablonski** [gatsbyjs/gatsby#27196]
## Description

Up to Gatsby 2.24.64 is was possible to use Link from @reach/router to link between pages. Starting from 2.24.65 you get 404-errors. We need to use Link from @reach/router in our project because we have to rebundle our components without a Gatsby dependency. With Link from "gatsby" it works fine.

I suspect that this issue is related to this fix, but I'm not totally sure:

[https://github.com/gatsbyjs/gatsby/pull/27003](https://github.com/gatsbyjs/gatsby/pull/27003)

### Steps to reproduce

Create a new starter project:

`gatsby new gatsby-test https://github.com/gatsbyjs/gatsby-starter-hello-world`

As src/pages/index.js use:

```
import { Link } from "@reach/router"
import React from "react"

export default function Home() {
  return <Link to="/page2">Page2</Link>
}
```

As src/pages/page2.js use:

```
import { Link } from "@reach/router"
import React from "react"

export default function Page2() {
  return <Link to="/">Home</Link>
}
```

### Expected result

Now run it in develop mode. Clicking on the link works fine with Gatsby version up to 2.24.64, but results in the error page with 2.24.65 and above.

### Actual result

With Gatsby 2.24.65 and above you'll get 404-error page.

**Comment by MakowskiHubert** [comment]
Happening the issue for me too.

**Comment by xu3u4** [comment]
Same for me.

**Comment by daiky00** [comment]
same for me

**Comment by tracy-liucui** [comment]
We had the same issue, solved it by using gatsby link. 

Gatsby link handles some gatsby-specified logic, if you want to make the reach-router link work the same, you should handle them by yourself. Mainly the hover event I guess
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-link/src/index.js#L223

**Comment by sarahannnicholson** [comment]
As a workaround in development my process has been:
1. Click on a link that goes to the page I want
2. Get the 404 page
3. Refresh the page
and then I get my page appearing. Which just reinforces that this is an issue with the linking. 

Alternatively, going straight to the route you want works for me as well. 

Can confirm this only happens on development, `gatsby build` is fine. 
Gatsby `v2.30.2`

**Comment by abohannon** [comment]
Currently our entire team is using the same workaround as @sarahannnicholson. Only dev is affected, build is fine. We're using Gatsy Link and `v2.32.3`.

**Comment by cameronbraid** [comment]
from https://github.com/gatsbyjs/gatsby/issues/7643#issuecomment-736063788

> Someone looking for a quick solution without changing their approach can try import { navigate } from "gatsby" instead of from @reach/router.

**Comment by wardpeet** [comment]
Is this fixed? Does this still occur in v3 or in v4?

**Comment by jablonski** [comment]
For us the problem was solved by using another bundling strategy by exposing "@gatsbyjs/reach-router". As Gatsby switched from "@reach/router" to a dedicated fork ("@gatsbyjs/reach-router"), the original idea of using "@reach/router" to keep our bundle Gatsby-agnostic isn't valid anymore.

**Comment by byronlanehill** [comment]
@wardpeet This is still a problem in the current version of Gatsby. It doesn't affect production at all but does affect development. 

My use case is to update the query params of the URL using @reach/router's navigate function as per [](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/#recommendations-for-programmatic-in-app-navigation). Currently doing exactly what is defined in the docs will cause a 404 in development, but will work fine in production.

This will also affect any site this is using gatsby-plugin-use-query-params because they use @reach/routers navigate function under the hood to handle updating query params without a full reload.
