### ISSUE TITLE
Use Danger JS http://danger.systems/js/

### ISSUE THREAD

**Issue by andykenward** [gatsbyjs/gatsby#2720]
I've noticed that the [`CHANGELOG.md`](https://github.com/gatsbyjs/gatsby/blob/5fafae157dd9ad0d45f48bc850283f89392fc401/CHANGELOG.md) isn't being kept up to date with the releases.

It might be worth adding in [Danger JS](http://danger.systems/js/) to help with this or an alternative.

**Comment by KyleAMathews** [comment]
We've been thinking also about using semantic-release https://github.com/gatsbyjs/gatsby/pull/2198

Any preference?

Adding Danger could have other uses though.

**Comment by m-allanson** [comment]
Danger JS was added in https://github.com/gatsbyjs/gatsby/pull/4970

**Comment by KyleAMathews** [comment]
Kinda doing this now.
