### ISSUE TITLE
Flow Type in gatsby-node.js "Invalid or unexpected token"

### ISSUE THREAD

**Issue by semireg** [gatsbyjs/gatsby#27212]
## Description

When I import a flow type in gatsby-node.js I get an invalid or unexpected token error. I have gatsby-plugin-flow installed and configured. This same file works OK when imported from a component.

### Steps to reproduce

It seems like flow types don't work when imported from gatsby-node.js.

Importing a file that starts with:
```
// @flow

import {
  Record,
  Map,
  type RecordFactory,
  type RecordOf,
  List,
  OrderedMap,
} from 'immutable';
```

Results in:
![2020-10-01 at 9 33 AM](https://user-images.githubusercontent.com/1819762/94823290-4f610400-03c9-11eb-98d8-dd71f3a5d5a4.png)

### Expected result

It should work from Gatsby-node.js. This file works if imported elsewhere or other Flow projects.

### Actual result

  SyntaxError: Invalid or unexpected token

### Environment

```
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.121
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.67 => 2.24.67
    gatsby-image: ^2.4.20 => 2.4.20
    gatsby-plugin-canonical-urls: ^2.3.12 => 2.3.12
    gatsby-plugin-flow: ^1.3.13 => 1.3.13
    gatsby-plugin-google-analytics: ^2.3.15 => 2.3.15
    gatsby-plugin-google-tagmanager: ^2.3.14 => 2.3.14
    gatsby-plugin-less: ^2.1.2 => 2.1.2
    gatsby-plugin-manifest: ^2.4.33 => 2.4.33
    gatsby-plugin-netlify: ^2.3.16 => 2.3.16
    gatsby-plugin-react-helmet: ^3.3.12 => 3.3.12
    gatsby-plugin-robots-txt: ^1.5.3 => 1.5.3
    gatsby-plugin-sharp: ^2.6.38 => 2.6.38
    gatsby-plugin-sitemap: ^2.4.14 => 2.4.14
    gatsby-remark-copy-linked-files: ^2.3.18 => 2.3.18
    gatsby-remark-embed-video: ^1.7.1 => 1.7.1
    gatsby-remark-images: ^3.3.32 => 3.3.32
    gatsby-remark-images-zoom: ^1.1.0 => 1.1.0
    gatsby-remark-prismjs: ^3.5.15 => 3.5.15
    gatsby-remark-responsive-iframe: ^2.4.16 => 2.4.16
    gatsby-remark-smartypants: ^2.3.12 => 2.3.12
    gatsby-remark-unwrap-images: ^1.0.2 => 1.0.2
    gatsby-source-filesystem: ^2.3.32 => 2.3.32
    gatsby-transformer-remark: ^2.8.37 => 2.8.37
    gatsby-transformer-sharp: ^2.5.16 => 2.5.16
    gatsby-transformer-sqip: ^2.3.38 => 2.3.38
  npmGlobalPackages:
    gatsby-cli: 2.8.27
```

File .flowconfig exists.

Running via: `NODE_OPTIONS='-r esm' gatsby develop`

My gatsby-config.js contains:

```
module.exports = {
  siteMetadata: {
   ...
  },
  plugins: [
    `gatsby-plugin-flow`,
    ...
```

What am I doing wrong?

**Comment by pieh** [comment]
`gatsby-node.js` (as well as `gatsby-config.js`) doesn't support either flow or typescript (that would be variant with .ts extension) even with their respective plugins. If you wish to use flow (or typescript) today for those you would need to have your own transpilation step that runs before `gatsby build/develop` or maybe try to use something like https://www.npmjs.com/package/flow-node#use-the-require-hook as first thing in those files?

**Comment by semireg** [comment]
Thanks, installing and adding `require('flow-remove-types/register')` above the require worked great. 

What this looks like in practice:

```
require('flow-remove-types/register');
const { default: Barcodes } = require('./src/utils/Barcode');
```
