### ISSUE TITLE
GraphQL error: Cannot read property dir of null.

### ISSUE THREAD

**Issue by zlobizlobi** [gatsbyjs/gatsby#27215]
## Description

Hi there! I am using Gatsby together with `gatsby-plugin-mdx` and `netlify-cms` for blog content creation - meaning I am sourcing mdx files from a `netlify-cms` content folder into my Gatsby project. At some point during the development GraphQL started to throw the following internal error for the images coming from my mdx frontmatter: 

```
There was an error in your GraphQL query:

Cannot read property 'dir' of null

  19 |       }
  20 |       authorName
  21 |       metaTitle
  22 |       metaDescription
  23 |       metaLinks {
  24 |         rel
  25 |         href
  26 |         hreflang
  27 |       }
  28 |       categories
> 29 |       mainImage {
     |       ^
  30 |         childImageSharp {
  31 |           fluid(quality: 100) {
  32 |             ...GatsbyImageSharpFluid
  33 |           }
  34 |         }
  35 |       }
  36 |       mainImageAltText
  37 |     }
  38 |   }
  39 | }
```

Nevertheless,

- The images from my query, the ones that the error points at, are rendered correctly on the static. It's not blocking anything.

### Steps to reproduce

- Clone [this repository](https://github.com/zlobizlobi/netlify-cms-inline-images-issue).
- Follow the steps in the `README.md`.

### Expected result

There should not be a GraphQL error at all as everything is working properly. 

### Environment
```
  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.11.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.121
    Safari: 13.1.1
  npmPackages:
    gatsby: 2.24.57 => 2.24.57
    gatsby-image: 2.4.14 => 2.4.14
    gatsby-plugin-graphql-codegen: 2.7.1 => 2.7.1
    gatsby-plugin-mdx: 1.2.30 => 1.2.30
    gatsby-plugin-netlify-cms: 4.1.28 => 4.1.28
    gatsby-plugin-react-helmet: 3.1.15 => 3.1.15
    gatsby-plugin-root-import: 2.0.5 => 2.0.5
    gatsby-plugin-sharp: 2.6.25 => 2.6.25
    gatsby-plugin-styled-components: 3.1.20 => 3.1.20
    gatsby-plugin-typescript: 2.1.19 => 2.1.19
    gatsby-remark-images: 3.3.25 => 3.3.25
    gatsby-remark-unwrap-images: 1.0.2 => 1.0.2
    gatsby-source-filesystem: 2.1.46 => 2.1.46
    gatsby-transformer-sharp: 2.5.13 => 2.5.13
```

**Comment by pieh** [comment]
Did you confirm it happens in provided reproduction? I can't reproduce reported errors locally with your reproduction. I did try to play with netlify cms admin messing with content a little bit as well as adding some new posts, but I couldn't hit that error.

Not great solution - but can you try stop `gatsby develop`, temporarily rename `.cache` directory to something like `.cache.bak` and restart `npm run dev`? If that works it shouldn't be considered a fix - just test/confirmation that persisted internal state of gatsby went "bad" and couldn't recover from it. Reason I asked for rename and not removal is that we could potentially investigate it (not easiest task if we don't know how to trigger it, but better to have something around than not).

**Comment by zlobizlobi** [comment]
Hi @pieh,  Thanks for replying 😃 !

I see that there are indeed no errors right now.  I think something in combination with `gatsby-plugin-graphql-codegen` is giving this error. I removed this dependency in the reproduction because I thought it would not serve a purpose and therefore the error is gone now for some reason. See the [updated repo](https://github.com/zlobizlobi/netlify-cms-inline-images-issue) for the error. My first thought is that the types are not being generated until the images are being sourced from `static/media` ...so I moved around the all `gatsby-source-filesystem` instances to be first in `gatsby-config.js` but to no avail...

**Comment by zlobizlobi** [comment]
Hi there @pieh!

Thanks to your comment I was able to understand partly where the error was coming from. In the reproduction scenario I left out the `gatsby-plugin-graphql-codegen` as I did not see any purpose for it in this case. When I included the dependency - the error re-appeared. Then I took a closer look at my `gatsby-config.js` and saw a possibility that you may need to source from `../static/media` first before sourcing the posts - tada - error gone and codegen dependency still in place. 🙌 

Thanks for your help!
