### ISSUE TITLE
gatsby-plugin-sharp | Support withoutEnlargement

### ISSUE THREAD

**Issue by schwiet** [gatsbyjs/gatsby#27219]
## Summary

The Sharp [resize()](https://sharp.pixelplumbing.com/api-resize#resize) function has a useful option: [withoutEnlargement](https://sharp.pixelplumbing.com/api-resize#parameters) that can be used to prevent source images from being enlarged beyond their original size, which helps prevent undesirable degradation in image quality. It would be nice if Gatsby Plugin Sharp exposed this option as a [Shared Option](https://www.gatsbyjs.com/plugins/gatsby-plugin-sharp/#shared-options).

### Basic example

```
childImageSharp{
    fixed(
        width: 1000
        height: 600
        withoutEnlargement: true
    ){
        ...GatsbyImageSharpFixed
    }
}
```

```
childImageSharp{
    fluid(
        maxWidth: 1000
        maxHeight: 600
        withoutEnlargement: true
    ){
        ...GatsbyImageSharpFluid
    }
}
```

```
childImageSharp{
    resize(
        width: 1000
        height: 600
        withoutEnlargement: true
    ){
        ...GatsbyImageSharpResize
    }
}
```

### Motivation

There are use cases where it is desirable to limit the resizing of an image to sizes that are <= its original size, in order to prevent loss in image quality. The [withoutEnlargement](https://sharp.pixelplumbing.com/api-resize#parameters) option allows you to enforce this restriction. It would be great if Gatsby's Sharp plugin exposed this functionality.

**Comment by marcotisi** [comment]
Our team also need that feature, any ETA? Thanks!

**Comment by ascorbic** [comment]
This is the default behaviour in the new `gatsbyImageData` resolver from gatsby-plugin-image, so we're unlikely to add it to this to the legacy one.

**Comment by marcotisi** [comment]
Thank you, I'll take a look at the new resolver

**Comment by ascorbic** [comment]
It's still in beta, but should be stable next month
