### ISSUE TITLE
[gatsby-transformer-remark] Empty title when containing double-colon

### ISSUE THREAD

**Issue by mkrcah** [gatsbyjs/gatsby#2721]
Given a markdown file:
```
---
title: Question: To be or Not to be?
date: 2017-11-01
---

some content
```

the GraphQL outputs empty string for the `title` field.

When changed to the following (notice the removal of the doublecolon in the title)
```
---
title: Question - To be or Not to be?
date: 2017-11-01
---

some content
```

the GraphQL outputs the correct string `Question - To be or Not to be?`

It seems there is an error in parsing a title which contains a double-colon.

**Comment by KyleAMathews** [comment]
Frontmatter is yaml. So when you add the second colon, yaml treats question as a new key in a sub-object. Do `title: "Question: To be or Not to be?"` instead to treat the title as a string.

**Comment by mkrcah** [comment]
Thanks!
