### ISSUE TITLE
🍁🎃 Gatsby Hacktoberfest 2020 🎃👻!

### ISSUE THREAD

**Issue by mgienow** [gatsbyjs/gatsby#27222]
<h1 align="center"> Welcome to Gatsby Hacktoberfest 2020!</h1>
<p align="center">
  <a href="https://www.gatsbyjs.com/">What is Gatsby?</a>  |  <a href="https://www.gatsbyjs.com/docs/">Gatsby Docs</a>
</p>
<p align="center">
<img alt="Linus from Peanuts in pumpkin patch" src="https://lh3.googleusercontent.com/uHB83llNLu9S4Ysjog7gvPS9oVqZKNhLSMD1IUJ0rI536JI0VetJm8tP0NBs92oQxLpZzCSe1pRWDwXyARAXqPEdQBDJvQVgaqvFZko0lZv5wxN_Neq8_LKCX2OSuWoczD9oZODg"/>
</p>
Welcome to Hacktoberfest 2020 with Gatsby!  This is the place to get started, check out open issues you can contribute to, and ask questions.

Hacktoberfest is a [month long initiative](https://hacktoberfest.digitalocean.com/), led by Digital Ocean, to encourage the growth of the global open source community through helping new contributors make their first project contributions. Everyone, from all backgrounds and skill levels, is invited to join in. 

__Please note: Issues tagged "Hacktoberfest" are specifically designed and written to be more accessible for first-time contributors.__ Any issue PR's during the month of October counts as Hacktoberfest participation, we are simply asking more experienced contributors to choose from any of our many other issues available. Thanks!

### So, how _do_ you get started?

1.  Register for Hacktoberfest at <https://hacktoberfest.digitalocean.com/>.

2.  Come back to the [main Issues repository](https://github.com/gatsbyjs/gatsby/issues) for Gatsby open source, and start shopping for an open issue that interests you! [Search with the Hacktoberfest tag](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest) to uncover all the "official" issues we have identified and scoped as especially good for new or first time contributors.

3.  After you've done the work, submit a pull request. We will work with you to get it merged.

4.  Once the PR is approved, make sure you fill in the [Gatsby Hacktoberfest form](https://docs.google.com/forms/d/e/1FAIpQLSccR2qesIHmOVvNPwa8COEvF33wG0Ibkf0ZFJykKvl7ayn72A/viewform) to claim your special edition glow in the dark Gatsby sticker, exclusively for Hacktoberfest contributors! (No need to register with us beforehand, this is just how we make sure everyone gets their bonus sticker for participating).

For more information, check out the [Hacktoberfest blog post](https://www.gatsbyjs.com/blog/hacktoberfest-2020) on the Gatsby website. 

We are glad you are here, and Happy Hack(tober)ing!

**Comment by nickmccurdy** [comment]
It looks like you'll need an admin to add the `hacktoberfest` topic to the repository or all pull requests will be ignored https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by wardpeet** [comment]
I followed the instructions and we should be good to go. If not let me know in this thread 😄

**Comment by TheSench** [comment]
I got here via the topic, so you should be good. 👍

**Comment by LekoArts** [comment]
Thanks for participating in this year's Hacktoberfest!
