### ISSUE TITLE
Documentation on .env files is hidden

### ISSUE THREAD

**Issue by WillMayger** [gatsbyjs/gatsby#27237]
## Summary

When searching for how to make use of `.env` files with Gatsby, the current documentation is not clear enough and causes confusion.

Documentation link: https://www.gatsbyjs.com/docs/environment-variables

When understanding how to use project-wide environment variables with `.env` files, the documentation frequently references using `.env.*`, `.env.development`, or `.env.production` and only references that it is not supported by default later on in the documentation which is currently hidden in the server-side node.js section and difficult to find.`

 - Current documentation un-intentionally suggests `.env` is supported by default in early paragraphs by talking about using `.env` files.
 - The message that is is not supported is hidden away in the documentation and needs to be clearer. 

### Motivation

Due to how create-react-app works many people will expect `.env` files to work out of the box with gatsby, and the current documentation un-intentionally suggests that it is supported. Only if you really dig down into the documentation, into the server-side node.js section, will you find a small message saying that it is not supported by default.

Everyone who is coming from CRA to Gatsby will benefit from a more explicit message about the `.env` not being supported by default.

## Steps to resolve this issue

Add in a simple warning/note at the top explaining this and pointing to the relevant section

For example, here is an issue that could have been prevented: [#22880](https://github.com/gatsbyjs/gatsby/issues/22880)

## PR:

Pull request opened: https://github.com/gatsbyjs/gatsby/pull/27239

**Comment by tom-raley** [comment]
I'd be happy to take this on if you're still looking for someone!

**Comment by WillMayger** [comment]
Hi @tom-raley, thanks however I already have a PR for this one here:  https://github.com/gatsbyjs/gatsby/pull/27239

**Comment by w3bdesign** [comment]
Not stale.

**Comment by WillMayger** [comment]
Not stale

**Comment by WillMayger** [comment]
Not stale

**Comment by WillMayger** [comment]
@pvdz @tom-raley Please can someone review the PR on this?
