### ISSUE TITLE
URL Validation on non-ascii characters

### ISSUE THREAD

**Issue by alpeer** [gatsbyjs/gatsby#27258]
## Description

Ggatsby can't validate my domain(https://kürşat.com) in config to start development environment.

### Steps to reproduce

1-) edit gatsby-config.js
```javascript
module.exports = {
  siteMetadata: {
    siteUrl: "http://kürşat.com",
    ...
```

2-) start project in terminal
```bash
  npm start
```
### Expected result

Should successfully start development environment

### Actual result

```bash
npm start

> gatsby-starter-default@0.1.0 start /hidden/project/path
> npm run develop


> gatsby-starter-default@0.1.0 develop /hidden/project/path
> gatsby develop


 ERROR #10122  CONFIG

The site's gatsby-config.js failed validation:

child "siteMetadata" fails because [child "siteUrl" fails because ["siteUrl" must be a valid uri]]

not finished open and validate gatsby-configs - 0.471s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-default@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!   /hidden/path**-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@0.1.0 start: `npm run develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-default@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 63.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.24.26 => 2.24.57 
    gatsby-image: ^2.4.14 => 2.4.17 
    gatsby-plugin-google-analytics: ^2.3.14 => 2.3.14 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.4.21 => 2.4.28 
    gatsby-plugin-offline: ^3.2.21 => 3.2.27 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.24 => 2.6.35 
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10 
    gatsby-remark-images: ^3.3.24 => 3.3.29 
    gatsby-remark-prismjs: ^3.5.10 => 3.5.11 
    gatsby-remark-reading-time: ^1.1.0 => 1.1.0 
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0 
    gatsby-source-filesystem: ^2.3.23 => 2.3.29 
    gatsby-transformer-remark: ^2.8.28 => 2.8.34 
    gatsby-transformer-sharp: ^2.5.12 => 2.5.14 
  npmGlobalPackages:
    gatsby: 2.24.67
```

**Comment by arnsteinsm** [comment]
Hi!

Issues with Internationalized domain names (IDN) in siteUrl has been brought up before. #23468.

The validation method used by Gatsby to verify the siteUrl ([joi](https://joi.dev/api/?v=17.2.1#stringurioptions)), has no support for [IRI](https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier) at this time, and it [might not come at all](https://github.com/sideway/joi/issues/1164).

If you set your siteUrl in gatsby-config.js already punyencoded (in your case http://xn--krat-0ra90d.com), it will work as expected. You could use a tool like https://www.punycode.io/ to encode your adress.

**Comment by LekoArts** [comment]
Thank you for opening this!

@arnsteinsm hit the nail on the head - thanks for that! As explained in #23468 it would a bigger undertaking to support this and the demand for it is really low (that's why joi is also not consider doing it). I'd also advise to use punycode to fix your issue.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
