### ISSUE TITLE
Gatsby localhost different to Netlify deploy

### ISSUE THREAD

**Issue by Marius-Adam** [gatsbyjs/gatsby#27269]
Hi,

I'm fairly new to Gatsby. I actually came across it when was looking for templates for my portfolio.

I found a great example and I started customizing it following the guide on Gatsby's website. 
I managed to customize the Hero/Intro section and that worked well, however when I moved on to the About section and Footer the changes would not take place when deploying to Netlify.

I removed all the MDX files and I'm confused because I can't understand where they coming from when deploying

I've attached a short video to hopefully make things clearer
[Video](https://vimeo.com/464684170)

**Comment by Marius-Adam** [comment]
All sorted, cloned a fresh copy of the project and followed the guide on how to edit content. Pretty straightforward if you read the documentation.

**Comment by LekoArts** [comment]
Great! Just wanted to write you an answer 😛 For possible future Googlers:
When using a Gatsby theme you'll need to [Shadow files](https://www.gatsbyjs.com/docs/themes/shadowing/) to make changes.
