### ISSUE TITLE
Deploy on Netlify Blank

### ISSUE THREAD

**Issue by Aboumicho** [gatsbyjs/gatsby#27266]
## Description

The gatsby project builds locally but on deploy, displays blank page.

### Steps to reproduce
Go on this link: 
https://5f7593ca12c348e273bbf67d--vigorous-snyder-c8c0c4.netlify.app/

### Expected result

Website should appear.

### Actual result

Blank Page.

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.2
  Browsers:
    Chrome: 85.0.4183.121
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.24.66 => 2.24.66 
    gatsby-image: ^2.4.20 => 2.4.20 
    gatsby-plugin-manifest: ^2.4.32 => 2.4.32 
    gatsby-plugin-netlify-cms: ^4.3.15 => 4.3.15 
    gatsby-plugin-netlify-cms-paths: ^1.3.0 => 1.3.0 
    gatsby-plugin-react-helmet: ^3.3.12 => 3.3.12 
    gatsby-plugin-sharp: ^2.6.37 => 2.6.37 
    gatsby-plugin-sitemap: ^2.4.14 => 2.4.14 
    gatsby-source-filesystem: ^2.3.31 => 2.3.31 
    gatsby-transformer-remark: ^2.8.36 => 2.8.36 
    gatsby-transformer-sharp: ^2.5.16 => 2.5.16 
  npmGlobalPackages:
    gatsby-cli: 2.12.101

It says published, but everything is blank.
Also, on the netlify log:

4:32:57 AM: Starting to deploy site from 'public'
4:32:58 AM: Creating deploy tree 
4:32:58 AM: Creating deploy upload records
**4:32:58 AM: 0 new files to upload
4:32:58 AM: 0 new functions to upload**
4:32:58 AM: Starting post processing

**Comment by LekoArts** [comment]
Please reach out to Netlify's support about this. Thanks!
