### ISSUE TITLE
Tree-shaking not working correctly (react-icons)

### ISSUE THREAD

**Issue by abdullahe** [gatsbyjs/gatsby#27276]
## Description

When [react-icons ](https://github.com/react-icons/react-icons) is used, all of the icons in the set are included in the bundle. 

### Steps to reproduce

Clone and develop/build [gatsby-starter-default](https://github.com/abdullahe/gatsby-starter-default) which I added react-icons and gatsby-webpack-bundle-analyse:

`gatsby new treeshake-test https://github.com/abdullahe/gatsby-starter-default
`
```
cd treeshake-test
gatsby develop
```

### Expected result

The bundle should not include 1.37 mb of react-icons index.js.

### Actual result

![image](https://user-images.githubusercontent.com/699010/95017570-c8c75380-0662-11eb-8ce1-b36ef9a6bdaf.png)

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU         661  @ 3.33GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Chrome: 85.0.4183.121
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.68)
  npmPackages:
    gatsby: ^2.24.66 => 2.24.66 
    gatsby-image: ^2.4.20 => 2.4.20 
    gatsby-plugin-manifest: ^2.4.32 => 2.4.32 
    gatsby-plugin-offline: ^3.2.29 => 3.2.29 
    gatsby-plugin-react-helmet: ^3.3.12 => 3.3.12 
    gatsby-plugin-sharp: ^2.6.37 => 2.6.37 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.13 => 1.1.13 
    gatsby-source-filesystem: ^2.3.31 => 2.3.31 
    gatsby-transformer-sharp: ^2.5.16 => 2.5.16 
  npmGlobalPackages:
    gatsby-cli: 2.12.100

**Comment by herecydev** [comment]
Have you seen this issue: https://github.com/react-icons/react-icons/issues/154

Lots of helpful suggestions there

**Comment by abdullahe** [comment]
Thanks @herecydev. Yes, I've seen it. I am new, so could not try everything because I did not understand. 

I tried these:

* importing from `import { FaChevronDown } from "react-icons/fa/index"` and from `import { FaChevronDown } from "react-icons/fa"`  instead of `"react-icons"`.

* adding `  "sideEffects": false,` to `packages.json`.

None of them helped.

**Comment by herecydev** [comment]
Okay, might be worth asking in that issue. I'm not sure this is really a Gatsby thing (webpack handles the treeshaking), and it works well normally. I think `react-icons` library has some issues

**Comment by abdullahe** [comment]
Possible. Someone had the [same issue,](https://github.com/react-icons/react-icons/issues/154#issuecomment-658222949) but got no response.

**Comment by LekoArts** [comment]
Thanks for the issue! Please report that on the repository of react-icons as this isn't an issue with Gatsby. The package needs to enable tree-shaking.
