### ISSUE TITLE
[gatsby-plugin-mdx] + [gatsby-transformer-react-docgen]: JS files appear in allMdx queries

### ISSUE THREAD

**Issue by oschade** [gatsbyjs/gatsby#27270]
## Description

If I'm using "gatsby-plugin-mdx" along with "gatsby-transformer-react-docgen", js-files (my component-files) appear in GraphlQL allMdx query.

### Steps to reproduce

I created a repo, so you can easily reproduce it:

`git clone https://github.com/oschade/gatsby-mdx-docgen-test.git`
`yarn && yarn develop`

Then open [http://localhost:8000/__graphql?query=query%20MyQuery%20%7B%0A%20%20allMdx%20%7B%0A%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20frontmatter%20%7B%0A%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20%20%20slug%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=MyQuery](http://localhost:8000/__graphql?query=query%20MyQuery%20%7B%0A%20%20allMdx%20%7B%0A%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20frontmatter%20%7B%0A%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20%20%20slug%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=MyQuery)

### Expected result

There should be one entry for `src/blog/first.mdx`.

### Actual result

There are two entries, for src/blog/first.mdx and for `src/components/Test.jsx`.

### Environment

````

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.3
  Browsers:
    Chrome: 85.0.4183.121
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.68)
  npmPackages:
    gatsby: ^2.24.66 => 2.24.66 
    gatsby-plugin-mdx: ^1.2.43 => 1.2.43 
    gatsby-source-filesystem: ^2.3.32 => 2.3.32 
    gatsby-transformer-react-docgen: ^5.2.13 => 5.2.13 
  npmGlobalPackages:
    gatsby-cli: 2.12.102
    gatsby-plugin-marvelle: 0.0.1
    gatsby: 2.1.18
````

**Comment by LekoArts** [comment]
@pieh mentioned that due to [descriptions being created as markdown types](https://github.com/gatsbyjs/gatsby/blob/7bf2bdbf0de545db7c8a1b540cfffb0641a7137a/packages/gatsby-transformer-react-docgen/src/on-node-create.js#L19-L48) MDX will pick those things up.

In that sense it's expected and correct behavior. https://github.com/gatsbyjs/gatsby/issues/19953 explores the ideas of e.g. treating only parts as `Mdx` so that not everything ends up in `allMdx`.

So for now you'll need to filter for your blog posts. You can do it by adding another field to your `Mdx` nodes:

```js
// gatsby-node.js

exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions

  if (node.internal.type === `Mdx`) {
    const sourceInstanceName = getNode(node.parent).sourceInstanceName

    createNodeField({
      node,
      name: `sourceInstanceName`,
      value: sourceInstanceName,
    })
  }
}
```

Then you can filter by it:

```graphql
query MyQuery {
  allMdx(filter: {fields: {sourceInstanceName: {eq: "blog"}}}) {
    nodes {
      frontmatter {
        title
      }
      fields {
        slug
      }
    }
  }
}
```
