### ISSUE TITLE
Profile picture won't show up in Gatsby Starter Blog (fresh setup)

### ISSUE THREAD

**Issue by einarpersson** [gatsbyjs/gatsby#27286]
## Summary
I'm trying out [Gatsby Starter Blog](https://www.gatsbyjs.com/starters/gatsbyjs/gatsby-starter-blog) from scratch. I've just swapped out the default `profile-pic.jpg` to one of my own. But now the profile picture won't display at all. 

I don't even know where to begin to troubleshoot this. I don't see any error messages, no nothing. Where should I even look?

### Environment (if relevant)

````
  System:
    OS: Linux 4.19 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
  npmPackages:
    gatsby: ^2.24.66 => 2.24.66 
    gatsby-image: ^2.4.20 => 2.4.20 
    gatsby-plugin-feed: ^2.5.13 => 2.5.13 
    gatsby-plugin-google-analytics: ^2.3.15 => 2.3.15 
    gatsby-plugin-manifest: ^2.4.32 => 2.4.32 
    gatsby-plugin-offline: ^3.2.29 => 3.2.29 
    gatsby-plugin-react-helmet: ^3.3.12 => 3.3.12 
    gatsby-plugin-sharp: ^2.6.37 => 2.6.37 
    gatsby-remark-copy-linked-files: ^2.3.17 => 2.3.17 
    gatsby-remark-images: ^3.3.31 => 3.3.31 
    gatsby-remark-prismjs: ^3.5.14 => 3.5.14 
    gatsby-remark-responsive-iframe: ^2.4.15 => 2.4.15 
    gatsby-remark-smartypants: ^2.3.12 => 2.3.12 
    gatsby-source-filesystem: ^2.3.31 => 2.3.31 
    gatsby-transformer-remark: ^2.8.36 => 2.8.36 
    gatsby-transformer-sharp: ^2.5.16 => 2.5.16 
  npmGlobalPackages:
    gatsby-cli: 2.12.102
```` 

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by acagastya** [comment]
@einarpersson if you have just started and made no changes except swapping the profile picture -- is the new name of the file same as the old one?  And if so, could you remove `.cache` and `public` folders and re-run to confirm the problem exists?

**Comment by einarpersson** [comment]
It started to work now. Did not change anything. Weird.

Well I'm happy now, closing...

**Comment by acagastya** [comment]
@einarpersson probably it was due to caching.  I have set up my start script as `rm -rf .cache public && yarn develop`.  Glad it works for you now!
