### ISSUE TITLE
docs: Add DatoCMS fragments to gatsby-image 

### ISSUE THREAD

**Issue by dragenet** [gatsbyjs/gatsby#27288]
DatoCMS nowadays support GatsbyDatoCmsFluid_tracedSVG and GatsbyDatoCmsFixed_tracedSVG fragments so it will be nice to add it to gatsby-image documentation

**Comment by LekoArts** [comment]
Thanks for the issue! As you correctly pointed out as per https://github.com/datocms/gatsby-source-datocms#integration-with-gatsby-image it supports `GatsbyDatoCmsFluid_tracedSVG` and `GatsbyDatoCmsFixed_tracedSVG` which is missing here: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-image#gatsby-source-datocms

Feel free to send in a PR adding those two entries :)

**Comment by Ankit810** [comment]
Hi!
So we just have to add those two formats under the gatsby-source-datocms section in here :https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-image#gatsby-source-datocms?

**Comment by LekoArts** [comment]
Correct!

**Comment by Ankit810** [comment]
Can I help contributing? @LekoArts

**Comment by LekoArts** [comment]
Sure! You can directly change the file via GitHub's UI: https://www.gatsbyjs.com/contributing/docs-contributions/#modifying-markdown-files

**Comment by Ankit810** [comment]
Thank you so much!
On it...
