### ISSUE TITLE
Weird big chunk `/public/static/d`

### ISSUE THREAD

**Issue by cesarvarela** [gatsbyjs/gatsby#27297]
## Summary
Hi, I'm trying to improve the pagespeed score of our landing page, and I'm confused about what's causing this big webpack chunks:

![image](https://user-images.githubusercontent.com/1172479/95134365-27f79780-0739-11eb-923b-83ed2f07cb61.png)

Both are around 400kb (200kb gziped).

Is this normal? What's causing this? Importing images using webpack? Should I move them to the `/static` folder? 

Lighthouse does not like them at all:
They
![image](https://user-images.githubusercontent.com/1172479/95134544-71e07d80-0739-11eb-8ecd-72e9dbf5d12c.png)

Thanks

**Comment by KyleAMathews** [comment]
Those are the results or static queries. You can look at what's in the json files to see what the query is and then audit the query to see if you need all the data there

**Comment by cesarvarela** [comment]
Thanks!
