### ISSUE TITLE
Simple gatsby-plugin-canonical-urls Protocol Bug

### ISSUE THREAD

**Issue by mikleing** [gatsbyjs/gatsby#27298]
## Description

The [gatsby-plugin-canonical-urls](https://www.gatsbyjs.com/plugins/gatsby-plugin-canonical-urls/) plugin adds a rel=canonical <link> tag to the head of each HTML page. 

Here is an example of code added to the head of the html document:

`<link rel="canonical" href="https://www.abc.com" data-baseprotocol="https:" data-basehost="www.abc.com">`

The potential problem is with the protocol.  It states the protocol is "https:".  But shouldn't it be "https" without the colon?

## How to Reproduce

1. Start with the [Gatsby Starter Default](https://www.gatsbyjs.com/starters/gatsbyjs/gatsby-starter-default/).
2. Install the [gatsby-plugin-canonical-urls](https://www.gatsbyjs.com/plugins/gatsby-plugin-canonical-urls/) plugin.
3. Run "gatsby develop"
4. Open "localhost:8000" in Google Chrome.
5. Open the developer tools (click F12).
6. Select "Elements"
7. Expand the "head" section.
8. Look for the rel=canonical <link> tag.
9. Find the property data-baseprotocol.  It should be equal to "https" not "https:"

## Solution

Open the [gatsby-srr.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-canonical-urls/src/gatsby-ssr.js) file.  And modify line 29 to remove the colon.  Here is what line 29 should look like:

`data-baseprotocol={parsed.protocol.slice(0, -1)}`

**Comment by rutujak24** [comment]
Please assign me this issue

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by rutujak24** [comment]
@LekoArts Sir, Can I work on this issue and solve it?

**Comment by LekoArts** [comment]
@rutujak24 This issue lacks a clear issue/error description so there isn't anything actionable here. Please have a look at the issues tagged with [hacktoberfest](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AHacktoberfest).

**Comment by mikleing** [comment]
@rutujak24 I have updated my original message to include information on how to reproduce the error.  I didn't create a reproduction since the error is found by simply using a starter project and installing the plugin.  There is no special code needed to reproduce the error.  I do also include the steps to fix the error.  It's a very simple error.

**Comment by pvdz** [comment]
Can you cite a reference stating the protocol should be without a colon? I can't find a reference and everything I find on the canonical tag also has a colon.

**Comment by pvdz** [comment]
Honestly I'm of half a mind to just drop `data-basehost` and `data-baseprotocol`. I cannot find any reference that refers to these attributes or how they ought to be filled. These attributes were added two years ago but the PR (#4116) does not explain why. I don't think the original issue (#4110) does either. Perhaps @danhounshell can chime in here?

**Comment by mikleing** [comment]
Before posting the issue, I spend a fair amount of time looking for any specification for `data-basehost` and `data-baseprotocol`.  I couldn't find any standard or even a reference of anyone who uses those values.  [Google's documentation](https://support.google.com/webmasters/answer/139066?hl=en) does not comment on  `data-basehost` or `data-baseprotocol`.  I also began to wonder if they were really needed.

So I don't have a reference that says the protocol should not have the colon.  But I've never seen a reference to the protocol that includes the colon.  Plus, I could see how this could have been an oversight by the original programmer.  The field `parsed.protocol` seems to give you exactly what you want.  But I've seen people add the `.slice(0, -1)` function when referencing the protocol from the url package.

**Comment by rutujak24** [comment]
Yes I do agree with @mikleing 
I had a similar approach to this issue.

**Comment by pvdz** [comment]
Considering it's been like this for two years, I would suggest to either keep it as is or drop it entirely. If nothing is actually using this, they're just dead bytes. And arguably, the protocol of the canonical url should be leading anyways so it feels like a redundant field regardless.

**Comment by pvdz** [comment]
Ok, @pieh pointed me towards https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-canonical-urls/src/gatsby-browser.js#L6-L21 and that this is probably the reason for these attributes existing in the first place. Nothing else. So removing the colon would break that so we're not going to do that.

So I'd propose to drop these attributes and get this information straight from the canonical url in browser.js instead.

**Comment by tmttn** [comment]
> So I'd propose to drop these attributes and get this information straight from the canonical url in browser.js instead.

My PR is pretty much exactly this. :-)
