### ISSUE TITLE
Hot reload not working on projects under macOS synthetic firmlinks 

### ISSUE THREAD

**Issue by azzazzel** [gatsbyjs/gatsby#27290]
## Description

Since macOS Catalina, the root volume of the OS is read-only. [To create a folder in the root one has to use synthetic firmlinks](https://derflounder.wordpress.com/2020/01/18/creating-root-level-directories-and-symbolic-links-on-macos-catalina/). I happened to have a gatsby project in a path under one such folder.  It looks like `gatsby develop` is unable to hot reload if a project is located in such place. The same project moved to path outside the synthetic firmlink (for example user's home folder) results in hot reload working properly. 

### Steps to reproduce

1. If you don't have one, create a synthetic firmlink on recent macOS  ([this post](https://derflounder.wordpress.com/2020/01/18/creating-root-level-directories-and-symbolic-links-on-macos-catalina/) explains how to do it)
2. create new Gatsby project anywhere under the synthetic firmlink
3. run `gatsby develop` and open the site it in a browser
4. modify `index.js` (or any other page) and save it

### Expected result

Browser reloads the page and the changes are rendered

### Actual result

Page is not realoded

### Environment
```
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 80.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.66 => 2.24.66
    gatsby-image: ^2.4.20 => 2.4.20
    gatsby-plugin-manifest: ^2.4.32 => 2.4.32
    gatsby-plugin-offline: ^3.2.29 => 3.2.29
    gatsby-plugin-react-helmet: ^3.3.12 => 3.3.12
    gatsby-plugin-sharp: ^2.6.37 => 2.6.37
    gatsby-source-filesystem: ^2.3.31 => 2.3.31
    gatsby-transformer-sharp: ^2.5.16 => 2.5.16
  npmGlobalPackages:
    gatsby-cli: 2.12.102
```

**Comment by ascorbic** [comment]
Hi. I'm afraid I can't repro this. Here's what I did:

- Created a `synthetic.conf` file with a firmlink from `/foo` to a folder in my home directory.
- Rebooted and confirmed that `/foo` had been created and was writeable
- Ran `gatsby new` in `/foo` and created a site from the default starter.
- Ran `gatsby develop` in the site folder
- Edited `pages/index.js`

It hot-reloaded as expected.

Could you run `gatsby develop --verbose` and share the logs for when you edit a page?

Thanks

**Comment by azzazzel** [comment]
Hmm, that's odd. 
I did run with `-verbose` but nothing appears in the logs when I edit a page. It just shows the initial log:
```
...

Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 2.851s
verbose Transition to "waiting"
```

In may case the firmlink points to a folder in `/System/Volumes/Data/` rather than the user's home directory. Perhaps that's  the issue.

**Comment by ascorbic** [comment]
Perhaps. As it doesn't seem to know about the file change at all guessing this is an issue with webpack (or specifically watchpack), as it doesn't look like it's getting an event for the file changing. You'd expect something saying "Webpack file changed: .." and then the filename. Can you check whether you can repro it with a link to a folder in your home directory?

**Comment by ascorbic** [comment]
My guess is that this is related to webpack-dev-server, which uses chokidar@2, which in turn uses fsevents@1, which is pretty old. They are promising an imminent update (like, in the next week), so we may be able to upgrade it.

**Comment by azzazzel** [comment]
Thank you for the explanation. 

I'm not a JS developer (I just need to make some small changes in existing Gatsby project). The JS "dependency hell" is somewhat a mystery to me and I desperately try to stay away from it as the Java one that I normally deal with is already more than enough of a headache. 

If you think an issue should be reported to one of those project Gatsby depends on, I hope someone from your team can do it. I'm afraid I'll not be able to provide a reproducible case with those technologies.

I will try with a link to home directory and let you know the result. But that would be earliest the end of next week.

**Comment by azzazzel** [comment]
OK, I was forced to restart my machine so I used the occasion to test it.
It indeed works OK if the firmlink points to user's home folder. It does not, if it points to a folder in `/System/Volumes/Data/`

**Comment by ascorbic** [comment]
Ok, thanks. I will do some tests today and see if it's a fsevents thing

**Comment by azzazzel** [comment]
Hi @ascorbic 

today I encountered (kind of) the same issue with Docker. Mounted folders fail to update content between the container and the host if the host folder is a firmlink pointing to a path starting with `/System/Volumes/...` 

As this is outside not only Gatsby but the whole JS ecosystem AFAIK, I just wanted to let you know that perhaps the issue is with MacOS file system and not Gatsby and/or dependent JS libraries.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
