### ISSUE TITLE
[docs] Deploy to XDN

### ISSUE THREAD

**Issue by ianand** [gatsbyjs/gatsby#27291]
I filed this as a pull request originally (https://github.com/gatsbyjs/gatsby/pull/27247) but was told I need to file a ticket first.

There aren't any instructions for how to deploy Gatsby to the Moovweb XDN which has Gatsby as a supported framework. Would you accept a PR for instructions on how to deploy to the Moovweb XDN? 

And no (since it was asked) I'm not doing this as part of hacktoberfest. I work at Moovweb and we recently added Gatsby support. If there's any chance, would be great to get this in before JamstackConf tomorrow (like Gatsby, we're sponsoring the conference; see you there tomorrow!).

cc @meganesu

**Comment by meganesu** [comment]
Hi there @ianand! Thanks for your patience. Sorry for making you jump through hoops - I'm new to Gatsby and still getting up to speed on processes.

After talking with the team internally, we've decided to add in your deploy guide! I'll reopen the PR and add more detailed review notes there.

Thanks for your contribution! 💜
