### ISSUE TITLE
Is it possible to remove the scroll position (@@scroll/initial etc) in session storage?

### ISSUE THREAD

**Issue by isshesure** [gatsbyjs/gatsby#27308]
Currently, the user's scroll position is stored within session storage, and this is violating a GDPR compliance check (yes, I know). Is there a way to disable this storage?

**Comment by herecydev** [comment]
Is storing a position in a page anywhere close to "uniquely identifying a user"? I'm no expert but this seems fine?

**Comment by devbhansingh** [comment]
I would like to contribute in this project.

**Comment by isshesure** [comment]
Yes, it's more that it fails some online compliance checks, and given that I'm using `shouldUpdateScroll` to ignore the scroll position, it's also redundant. Perhaps this should be a feature request to update `shouldUpdateScroll` to be a more generic scrolling override option.

**Comment by herecydev** [comment]
So this file is the relevant one: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-react-router-scroll/src/scroll-handler.tsx

As it's just a React context you should be able to override the default by providing your own `Provider`. Does that work?

**Comment by ascorbic** [comment]
I am not a lawyer, but I have worked quite a bit with the GDPR. There is no scenario where scroll position could be considered to be PII! That said, it is a reasonable feature request so if someone wants to contribute then please go ahead. Are you planning to do this, @devbhansingh ?

**Comment by Shock451** [comment]
Hi, I'd like to take up this issue.

**Comment by lnfnunes** [comment]
A ref doc about this subject: https://www.termsfeed.com/blog/gdpr-scrolling-not-consent/
As @ascorbic mentioned, I'm not a lawyer too and my understanding is the scrolling act on a webpage **_cannot_** be considered consent. This is a reasonable feature but not because of GDPR compliance.

**Comment by RobvH** [comment]
It might be worth clarifying for all the non-Europeans, like myself, who were still confused after reading to this point. The implied issue here is that scroll position is kept in session storage _and the implementation of that session storage is using **cookies**_. So this is running afoul of a requirement that the user consent to the use of HTTP cookies.

**Comment by RobvH** [comment]
Are there tests around this?

**Comment by AjitsinghKamal** [comment]
@ascorbic can I pick this up?

**Comment by ascorbic** [comment]
@AjitsinghKamal Please do!

**Comment by AjitsinghKamal** [comment]
@ascorbic how would you recommend proceeding with this ?
Currently we set up SessionStorage as the first thing after initializing scroll. To prevent the addressed issue, we would need to introduce a prop say `disableScrollTracking` to signal that we need to turn off setting up sessionStorage entirely.

**Comment by Schweinepriester** [comment]
I think this issue shouldn't be closed just because of inactivity.

I'd like to be able to disable scroll restoration/tracking because of performance (for a feature we don't use):
- https://css-tricks.com/a-primer-on-the-different-types-of-browser-storage/
- https://web.dev/storage-for-the-web/

> [SessionStorage] … should be used with caution because it is synchronous and will block the main thread.

**Comment by ascorbic** [comment]
@Schweinepriester I'm afraid I don't work at Gatsby anymore so your best bet is to open a new issue, linking to this.

**Comment by Schweinepriester** [comment]
Since GitHub doesn't seem to link back from discussions:
Created a feature request since I couldn't really open a new issue: https://github.com/gatsbyjs/gatsby/discussions/34432

**Comment by jayjayjpg** [comment]
I'd like to see this ticket reopened (in my project's case also due to both GDPR and performance concerns). I'd also be up for working on it if this ticket was reopened

**Comment by jdahdah** [comment]
[Cookiebot](https://www.cookiebot.com/en/) is flagging `@@scroll#` as non-compliant for GDPR. Is there a pragmatic solution for this in the short-term? Unfortunately this is legally complicated for businesses and can potentially open them up to litigation in the EU.

**Comment by pgeimer** [comment]
@jdahdah I am having the same issue with Cookiebot. When the user rejects this cookie the website is not working properly anymore. Setting the cookie category to "required" in Cookiebot is not solving the issue.

**Comment by aiorga-ld** [comment]
@pgeimer are you using the Gatsby Script API? this seemed to break our site while using Cookiebot

**Comment by pgeimer** [comment]
@aiorga-ld With the Gatsby Script API Cookiebot wasn't blocking anything. at least in auto blocking mode. We ended up using Cookiebot in ``/src/html.js`` with manual blocking mode and then add attributes like ``data-cookieconsent="statistics"`` to the other scripts.

**Comment by pgeimer** [comment]
@aiorga-ld My site is working fine now. Even if a user rejects. I am having Cookiebot and all my other scripts placed in ``html.js`` below ``{props.headComponents}``.
