### ISSUE TITLE
Can't download directly HTML file from public

### ISSUE THREAD

**Issue by pacocom** [gatsbyjs/gatsby#27320]
## Description
Can't download directly HTML file from public. I want to download tutorial.html from public folder directly using markdown link.

```md
[Tutorial txt](/downloads/tutorial.txt 'Tutorial.txt')
[Tutorial html](/downloads/tutorial.html 'Tutorial.html')
```
```
```md
[Tutorial txt](/downloads/tutorial.txt 'Tutorial.txt')
```
![image](https://user-images.githubusercontent.com/7735329/95332367-9a888480-08ab-11eb-9169-1cec69423f95.png)
If I use txt file:
![image](https://user-images.githubusercontent.com/7735329/95332406-ac6a2780-08ab-11eb-9ddb-dc6006b0c6a2.png)
If I use html file:
Page 404 error appears.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by pvdz** [comment]
Double posted #27321
