### ISSUE TITLE
Build webhook returns empty 204 response.

### ISSUE THREAD

**Issue by ndaelemans** [gatsbyjs/gatsby#27323]
## Description

When I trigger a new build by submitting an empty POST to  the build webhook, I get an empty 204 (No content) response. However, it would be more logical to return a 200 code, as this is the general HTTP code for successful requests.

### Steps to reproduce

1. Post an empty body to the build webhook of your Gatsby project
2. Get a 204 response

### Expected result

200 OK

### Actual result

204 No Content

**Comment by ascorbic** [comment]
Hi. Any 2xx code means success, and in this case the 204 code is correct as there is no body. I'm going to clsoe this as it is working as expected.
