### ISSUE TITLE
[gatsb-theme-blog] i got an error adding to default hello world starter site

### ISSUE THREAD

**Issue by johng2t** [gatsbyjs/gatsby#27333]
## Description

I am new to gatsby. I created a new site with gatsby-starter-hello-world, follwoing https://github.com/gatsbyjs/gatsby-starter-hello-world this link. The hello world program works perfectly. 
I try to add the `gatsb-theme-blog` to this existing hello world site, I followed as given in the documentation
https://www.gatsbyjs.com/tutorial/using-a-theme/#installing-the-blog-theme
I run `gatsby develop` after completing the above instructions I got error and can't fix.

Kindly guide me on how to use themes in existing sites.  

### Error
![image](https://user-images.githubusercontent.com/46560005/95423482-c87ad100-095e-11eb-9c94-2a750e67cc26.png)

### Environment

  System:
    OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Shell: 5.1.1 - /usr/bin/zsh
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v12.14.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 80.0.1
  npmPackages:
    gatsby: ^2.24.67 => 2.24.67 
    gatsby-theme-blog: ^2.0.2 => 2.0.2 
  npmGlobalPackages:
    gatsby-cli: 2.12.102

**Comment by laurieontech** [comment]
Thanks for filing the issue! The problem right now is that the site is using the "wrong" version of theme-ui when you install with npm (which is what you have set up with gatsby new). There are a couple of options to fix this.

1. You can override the version by adding `"theme-ui": "0.4.0-alpha.3"` to the dependencies in your package.json file.
2. Alternatively you can use yarn which is able to pick the right dependency. If you use yarn and you'd like to use it for all gatsby new commands going forward, you can set that preference with your CLI using the command `gatsby options pm set yarn`.

The wrong theme-ui version is coming from another package in the monorepo, so I'll look into solving that for everyone.

**Comment by johng2t** [comment]
@laurieontech  Thank you its working.
