### ISSUE TITLE
images are not working in doc

### ISSUE THREAD

**Issue by kokum007** [gatsbyjs/gatsby#27341]
i found images are not working correctly in following path
[docs/tutorial/e-commerce-with-datocms-and-snipcart](url)

image links are broken or misleading in index.md on above path

**Comment by LekoArts** [comment]
Thank you for opening this!

The docs are supposed to be read on https://www.gatsbyjs.com/tutorial/e-commerce-with-datocms-and-snipcart/ and there all images are working :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by kokum007** [comment]
[https://www.gatsbyjs.com/tutorial/e-commerce-with-datocms-and-snipcart/](url)

yeah above link everything works. 
But i found inside the repo [https://github.com/gatsbyjs/gatsby/blob/master/docs/tutorial/e-commerce-with-datocms-and-snipcart/index.md](url)

the images are not showing in index.md file so i fixed it.  @LekoArts  anyway thanks. ill continue to contribute if I found something else.
