### ISSUE TITLE
not getting audio from markdown frontmatter

### ISSUE THREAD

**Issue by ashishch-98** [gatsbyjs/gatsby#27344]
I have a blog in which each blogpost has its audio file. So, this audio file is added in the frontmatter of the respective markdown. To play this audio I'm using [react h5 audio player](https://github.com/lhz516/react-h5-audio-player). But on the webpage, the audio file from the markdown does not load. 

Here is the frontmatter of the blog.

```
---
title: test
audio: 
      -"../music/test-audio.mp3"
---
```

Then this is how I query it in the blog-template.

```
query MyQuery {
  markdownRemark {
    frontmatter {
      title
      audio {
        sourceInstanceName
      }
    }
  }
}
```

_I changed to all the options, available in the graphql interface, under the audio section, but nothing seems to work._

This is the code of react h5 audio player
```
 <AudioPlayer
                autoPlay
                src={post.frontmatter.audio.sourceInstanceName}
                onPlay={e => console.log("onPlay")}
      />
```

This is the output I get

<img width="243" alt="audio" src="https://user-images.githubusercontent.com/71139972/95491556-61d5d180-09b7-11eb-9784-4934a03c6e2e.PNG">

If I import an audio file directly on the template page and pass it to the source, the audio plays perfectly on the page. But, I cant use that because I need the specific audio related to the respective blog.  

Can someone please help me out with what I'm doing wrong here? I am struggling for days to get it right but nothing seems to work.

**Comment by vladar** [comment]
Thank you for opening this, @ashishch-98 !

You should be using `publicURL` in your query like this:

```graphql
query MyQuery {
  markdownRemark {
    frontmatter {
      title
      audio {
        publicURL
      }
    }
  }
}
```

See [related docs section](https://www.gatsbyjs.com/docs/importing-assets-into-files/#querying-for-a-file-in-graphql-using-gatsby-source-filesystem).

Also, I've created a [simple example](https://github.com/vladar/audio-gh-27344) while trying to reproduce this, here are the changes made from the default starter blog: https://github.com/vladar/audio-gh-27344/commit/ade4f73237100078d1f4948cf38ff8e112267dc6

We're marking this issue as answered and closing it for now but please feel free to tag me and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by ashishch-98** [comment]
Thanks, man it worked. I think I was missing the "gatsby-remark-copy-linked-files" plugin.  Earlier I tried using _publicURL_ it didn't work but on adding this plugin the audio works fine.
