### ISSUE TITLE
VSCode Debug on windows SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by talohana** [gatsbyjs/gatsby#27355]
## Description

I've tried to debug the build process following the docs - [VS Code Debugger (Manual Config)](https://www.gatsbyjs.com/docs/debugging-the-build-process/#vs-code-debugger-manual-config), after saving and running `Gatsby develop` config I got the following error:

```text
C:\devl\workspace\my-project\node_modules\.bin\gatsby:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1053:16)←[39m       
←[90m    at Module._compile (internal/modules/cjs/loader.js:1101:27)←[39m
←[90m    at Object..js (internal/modules/cjs/loader.js:1157:10)←[39m     
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m
```

I workaround this by changing the config to:

```diff
{
    "name": "Gatsby develop",
    "type": "pwa-node",
    "request": "launch",
    "program": "${workspaceRoot}/node_modules/.bin/gatsby",
+    "windows": {
+    "program": "${workspaceRoot}/node_modules/gatsby/dist/bin/gatsby"
+    },
    "args": ["develop"],
    "runtimeArgs": ["--nolazy"],
    "console": "integratedTerminal"
},
```

It worked but logged `Debugger attached.` 4 times, which I'm not sure is the correct behavior.

### Steps to reproduce

1. `gatsby new bug-repro https://github.com/gatsbyjs/gatsby-starter-hello-world`

2. add to `.vscode/launch.json` file:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Gatsby develop",
      "type": "pwa-node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/.bin/gatsby",
      "args": ["develop"],
      "runtimeArgs": ["--nolazy"],
      "console": "integratedTerminal"
    }
  ]
}
```

### Environment
  IDE: VSCode 1.49.3 x64 - using git-bash version 2.23.0.windows.1 as default terminal
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.18.3 - ~\AppData\Local\Temp\yarn--1602241778964-0.05746843170514704\node.CMD
    Yarn: 1.22.4 - ~\AppData\Local\Temp\yarn--1602241778964-0.05746843170514704\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.70)
  npmPackages:
    gatsby: ^2.24.66 => 2.24.66 
    gatsby-image: ^2.4.20 => 2.4.20 
    gatsby-plugin-google-analytics: ^2.3.15 => 2.3.15 
    gatsby-plugin-manifest: ^2.4.32 => 2.4.32 
    gatsby-plugin-mdx: ^1.2.46 => 1.2.46 
    gatsby-plugin-offline: ^3.2.29 => 3.2.29 
    gatsby-plugin-react-helmet: ^3.3.12 => 3.3.12 
    gatsby-plugin-sharp: ^2.6.37 => 2.6.37 
    gatsby-plugin-styled-components: ^3.3.12 => 3.3.12 
    gatsby-plugin-typography: ^2.5.12 => 2.5.12 
    gatsby-remark-images: ^3.3.33 => 3.3.33 
    gatsby-remark-prismjs: ^3.5.16 => 3.5.16 
    gatsby-source-filesystem: ^2.3.31 => 2.3.31 
    gatsby-source-medium: ^2.3.12 => 2.3.12 
    gatsby-transformer-sharp: ^2.5.16 => 2.5.16 

Would like to submit a PR is possible

**Comment by zteric** [comment]
Any updates on this? having the same issue here

**Comment by Piepongwong** [comment]
This command worked for me: 
`node --inspect node_modules/gatsby/dist/bin/gatsby develop`

I'm running windows 10. Verified on Node 14.5.3 + 15.0 and gatsby 2.24.91 + 2.30.1.

**Comment by Piepongwong** [comment]
I see "debugger attached" only twice. There's just 1 node process running so I guess it's alright?

**Comment by arsinclair** [comment]
Why is this closed? What's the solution to the problem?

**Comment by arsinclair** [comment]
Whilst this config works like a charm on Linux, on Windows 10 there's an exception. I've modified the config to use the direct path to gatsby distribution on Windows in the following way.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Gatsby develop",
      "type": "pwa-node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/.bin/gatsby",
      "windows": {
        "program": "${workspaceRoot}/node_modules/gatsby/dist/bin/gatsby"
      },
      "args": ["develop"],
      "runtimeArgs": ["--nolazy"],
      "console": "integratedTerminal"
    },
    {
      "name": "Gatsby build",
      "type": "pwa-node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/.bin/gatsby",
      "args": ["build"],
      "runtimeArgs": ["--nolazy"],
      "console": "integratedTerminal"
    }
  ]
}
```

**Comment by yonatanLehman** [comment]
Same problem here. And the proposed solution works for me. 
I have added it to the documentation at https://www.gatsbyjs.com/docs/debugging-the-build-process/ and issued a PR.

**Comment by arsinclair** [comment]
I think this can be added as a temporary measure. I think it is good to try to maintain the same configuration for all platforms. Really curious, why `dirname` crashes...

Thank you for your PR.

**Comment by zipzit** [comment]
I discovered this issue when searching for troubles in debugging in vscode.  I started with 

` "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "develop"
            ],
            "port": 9229,
            "skipFiles": [
                "<node_internals>/**"
            ]
        },`

Total fail.  No errors, the whole thing just hangs.  Now I'm using the configurations from the website  https://www.gatsbyjs.com/docs/debugging-the-build-process/ and that totally works.  Many thanks!  

One comment. When I'm looking at the launch.json file in VSCode, there are a whole lot of warnings...  Each of the configurations I copied from the link above generate four warnings:

> Property windows is not allowed
> missing property "name"
> Missing property "type"
> Missing property "request"

Is that correct?
