### ISSUE TITLE
Add Expires headers

### ISSUE THREAD

**Issue by developer0116** [gatsbyjs/gatsby#27366]
I have built up website using Gatsby deployed on AWS Amplify.
I measured the performance score on GTMetrix. The speed score is 96 and yslow is 84 because of the `Add Expires headers` issue.
How can I add the expires headers in Gatsby.

Thanks

**Comment by vladar** [comment]
Thank you for opening this, @developer0116 

Ideally, the "Expires" header should be set in your web server configuration. So maybe look for it in Amplify docs/support. As a fallback try adding a meta tag (using [react-helmet](https://www.gatsbyjs.com/docs/add-page-metadata/#using-react-helmet-and-gatsby-plugin-react-helmet)):

```
<meta http-equiv="Expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
```
(make sure to change the value to something that makes sense in your case)

We're marking this issue as answered and closing it for now but please feel free to ping me and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
