### ISSUE TITLE
Form not working

### ISSUE THREAD

**Issue by ianseberg** [gatsbyjs/gatsby#27378]
## Description

I'm expecting the button to show correctly but when load the page, only on Safari, I see just a button.
Strate starter.
https://github.com/ianseberg/comprooro-lascari

### Steps to reproduce

Just build and try local

### Expected result

Rectangular yellow button with text

### Actual result

When I load the page in mobile Safari I don't see the button correctly formatted

### Environment

Run `gatsby build

**Comment by LekoArts** [comment]
Thank you for opening this!

This isn't a bug with Gatsby and also not a project we maintain. Please open an issue on the starter's repository or ask about general React questions in the communities mentioned below.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
