### ISSUE TITLE
onCreatePage is not fired when creating pages with gatsby-source-wordpress

### ISSUE THREAD

**Issue by samfenwick** [gatsbyjs/gatsby#27375]
## Summary

- I am using gatsby-source-wordpress to make a gatsby site with a headless wordpress backend

- In my gatsby-node.js createPages function I programatically create pages with page slugs I get from wordpress

- If i log out each page created in the onCreatePage func then I am not seeing any of the pages created as part of that step, only the /404/ page generated by gatsby.

- From reading other issues i'm thinking this is due to onCreatePage not being triggered (https://github.com/gatsbyjs/gatsby/issues/17498#issuecomment-529442071)

Is there any way around this? I want to create client routes within my site (https://www.gatsbyjs.com/docs/client-only-routes-and-user-authentication/) but I can't if i'm unable to access onCreatePage.

Ideally what I want that for is to be able to do is this:

In my site there are pages I have programatically made via the wordpress backend e.g. lets say a page with path: **/vacation/**

Within that page there are photo thumbnails, when you click on them you get a modal that displays the photo (similar to facebook). I want the path to change to something along the lines of **/vacation/some-photo-name** which I was hoping to be able to handle with client only routes. Such that I could link someone **www.mysite.com/vaction/some-photo-name** and it navigate them to the www.mysite.com/vaction with the correct photo modal opened.

Any ideas?

Thanks!

### File contents

`gatsby-node.js`: 
```
exports.createPages = ({ graphql, actions, page }) => {
  const { createPage } = actions;
  return new Promise((resolve) => {
    graphql(
      `
        {
          allWordpressPage {
            edges {
              node {
                slug
              }
            }
          }
        }
      `,
    )
      .then((result) => {
        const pageTemplate = path.resolve('./src/templates/page.jsx');
        _.each(result.data.allWordpressPage.edges, (edge) => {
          createPage({
            path: `/${edge.node.slug}/`,
            component: slash(pageTemplate)
          });
          resolve();
        });
      });
  });
}; 

exports.onCreatePage = ({page}) => {
    console.log(page)
};

```

**Comment by vladar** [comment]
Hi @samfenwick !

Just to clarify - when you source data from any other source - can you reproduce this? 

It is hard to help without having some code to look at. So it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by samfenwick** [comment]
> Hi @samfenwick !
> 
> Just to clarify - when you source data from any other source - can you reproduce this?
> 
> It is hard to help without having some code to look at. So it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

Hi there 👋 

This is the only data source I’ve used with Gatsby so I’m not sure if it’s an issue with the actual plugin or some internal code to Gatsby itself preventing onCreatePage from firing (https://github.com/gatsbyjs/gatsby/issues/17498#issuecomment-529442071)

I will try and recreate the issue as you’ve mentioned.

**Comment by TylerBarnes** [comment]
Hi @samfenwick , this is actually by design and isn't a bug. Check the onCreatePage docs here https://www.gatsbyjs.com/docs/node-apis/#onCreatePage

```
There is a mechanism in Gatsby to prevent calling onCreatePage for pages created by the same gatsby-node.js to avoid infinite loops/callback.
```

Maybe this should be converted to a documentation issue because https://www.gatsbyjs.com/docs/page-creation/#oncreatepage-api doesn't mention this behaviour.

**Comment by samfenwick** [comment]
> Hi @samfenwick , this is actually by design and isn't a bug. Check the onCreatePage docs here https://www.gatsbyjs.com/docs/node-apis/#onCreatePage
> 
> ```
> There is a mechanism in Gatsby to prevent calling onCreatePage for pages created by the same gatsby-node.js to avoid infinite loops/callback.
> ```
> 
> Maybe this should be converted to a documentation issue because https://www.gatsbyjs.com/docs/page-creation/#oncreatepage-api doesn't mention this behaviour.

Ahh I did think it could be.

Do you have any idea if it’s possible for me to get around this? It’d be great if I could create client only routes for the pages I’m generating, even if I had to hard code the page paths somewhere.

**Comment by TylerBarnes** [comment]
I'm actually not too sure. You could try making a local Gatsby plugin in your project to see if that works
https://www.gatsbyjs.com/docs/creating-a-local-plugin/

**Comment by TylerBarnes** [comment]
Also @samfenwick what's your use case? That will help me or other folks know wether there's a better API to recommend.

**Comment by samfenwick** [comment]
> Also @samfenwick what's your use case? That will help me or other folks know wether there's a better API to recommend.

@TylerBarnes I have a simple photo website that has a number of pages that all have the same layout (each of these pages is created programmatically as outlined above). 

The layout is just a grid of thumbnails & when you click a thumbnail it brings up a modal showing the full sized image with a description at the side and a space for comments.

I want to be able to link someone a direct link to a page with the modal open for a given image e.g. www.example.com/vacation/photo1
would link to the /vacation page and I would have some logic in the code to parse /photo1 out of the pathname and make it so that the photo1 modal was open. This way I can have a unique URL for each photo on the page without needing a separate page for each photo.

**Comment by KyleAMathews** [comment]
A little late to the conversation but it looks like you want to build something similar to https://gatsbygram.gatsbyjs.org? If so, check out its src.
