### ISSUE TITLE
gatsby-cli not working anymore after updating to 2.12.107

### ISSUE THREAD

**Issue by catalina-cimpanu** [gatsbyjs/gatsby#27377]
## Description

Hi! I am writing this because I didn't find any recent help for this issue. This morning I started working on 2 gatsby projects (basically the same site in 2 versions). When I opened the first one in VS code and started the development with "gatsby develop", I had no issue. Then, I opened the second one and I saw that I can update gatsby-cli, so  I thought to myself , I'd better do that before starting developing the second project. Except, after I updated, the commands wouldn't work anymore :( 
I got an error "permission denied", which I, unfortunately, didn't copy right away, but it was something similar to this: [https://stackoverflow.com/questions/63378957/when-attempting-to-run-any-commands-to-do-with-gatsby-i-get-an-error-saying-perm](https://stackoverflow.com/questions/63378957/when-attempting-to-run-any-commands-to-do-with-gatsby-i-get-an-error-saying-perm)  - with no answer
or this: [https://github.com/gatsbyjs/gatsby/issues/26405](https://github.com/gatsbyjs/gatsby/issues/26405)  -closed without a solution
or this [https://github.com/gatsbyjs/gatsby/issues/22558](https://github.com/gatsbyjs/gatsby/issues/22558)  -also closed without a solution.

I hope I didn't break anything with the "npm config set prefix " command :(

Any help would be very much appreciated :)

### Steps to reproduce

First, I updated gatsby-cli with npm (this is where all started)
Then gatsby commands didn't work anymore, I was getting a permission error 
I found this: [https://github.com/gatsbyjs/gatsby/issues/4967](https://github.com/gatsbyjs/gatsby/issues/4967), so I tried to use
npm config set prefix /usr/local 
which didn't work, then I did
npm config set prefix C:\Users\catal\AppData\Roaming\npm
which is the folder where npm installed packages so far, which still didn't work.

Then i found this : [https://github.com/gatsbyjs/gatsby/issues/19088](https://github.com/gatsbyjs/gatsby/issues/19088), so uninstalled and reinstalled globally both gatsby and gatsby-cli
Still didn't work
Then I downgraded gatsby-cli to 2.12.106, still doesn't work

Everytime i try to run a gatsby command i get "bash: gatsby: command not found", like for example:
$ gatsby develop
bash: gatsby: command not found

### Expected result

gastbi-cli is working and i can develop as before

### Actual result

got the following error:

Latest error:
bash: gatsby: command not found

### Environment

$ gatsby info --clipboard
bash: gatsby: command not found

$ node -v
v12.18.3

$ npm -v
6.14.6

$ npm ls --depth=0 -global
C:\Users\catal\UserscatalAppDataRoamingnpm
`-- gatsby-cli@2.12.107

npm ERR! peer dep missing: gatsby@^2.6.0, required by gatsby-interface@0.0.193
npm ERR! peer dep missing: react-dom@^16.8.1, required by gatsby-interface@0.0.193
npm ERR! peer dep missing: acorn@^6.0.0, required by acorn-dynamic-import@4.0.0
npm ERR! peer dep missing: @mdx-js/react@^1.0.0, required by theme-ui@0.2.52
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/alert@0.10.3
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/combobox@0.10.3
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/dialog@0.10.3
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/menu-button@0.10.3
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/popover@0.10.3
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/tabs@0.10.3
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/tooltip@0.10.3
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/utils@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/visually-hidden@0.10.4
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/auto-id@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/descendants@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/popover@0.10.3
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/portal@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/utils@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/utils@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/utils@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/utils@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/portal@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/utils@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/auto-id@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/descendants@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/popover@0.10.3
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/utils@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/portal@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/rect@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/utils@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/utils@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/auto-id@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/descendants@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/utils@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/auto-id@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/portal@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/rect@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/utils@0.10.5
npm ERR! peer dep missing: react-dom@^16.8.0, required by @reach/visually-hidden@0.10.4

**Comment by catalina-cimpanu** [comment]
so, just a bit of an update: meanwhile because of me using 
`npm config set prefix /usr/local`
I couldn't even start my strapi server (i use strapi as a source).
But I found this: [https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows](https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows) so I changed the config file as recommended in one of the answers, and I also added permissions for authenticated users, as recommended in another answer. 
While reconfiguring npm, I noticed that I had a folder in my `C:\Users\catal`  (catal being the username)
named UserscatalAppDataRoamingnpm , which contained the node-module and the files for gatsby-cli, so I just copied these files in the `C:\Users\catal\AppData\Roaming\npm` directory. Then I reopened my VSCode and both my strapi and my gatsby were working.

I thought this might helpful for others, although to be honest, I am not sure what happened nor exactly how it was solved (other than copying the files in the right place). 

So, practically, what might help if someone has the same issue: 
- check if gatsby-cli was installed somwhere else and copy the files in the right folder
-make sure that the npm folder has permissions for the users

**Comment by LekoArts** [comment]
Hi, thanks for the issue and your answer to it. Permission issues are out of our hands but glad you were able to solve it :)

**Comment by catalina-cimpanu** [comment]
Hi, Thanks for your answer, I really appreciate you taking the time. Yeah, first I had that permission issue and then I wasn’t able to install gatsby-cli correctly and continue my project. I didn’t find an answer, and I got a bit too lost.. that’s why I wrote the issue. But then, somehow, I solved it. So probably all I needed was to keep on trying Have a great day!
