### ISSUE TITLE
Feature: Query siteMetaData

### ISSUE THREAD

**Issue by syzer** [gatsbyjs/gatsby#2738]
is it possible to query site metadata?
ex:
let's say site.siteMetaData.products is collection:
```[{id:1000}, {id:42}]```

Whould be awesome to query like: [markdownRemark](https://www.gatsbyjs.org/tutorial/part-four/#programmatically-creating-pages-from-data)

```graphql
 query ProductsQuery {
    site {
      siteMetadata {
        products(id: "1000") {
          id
        }
      }
    }
  }
```

**Comment by KyleAMathews** [comment]
You're asking if there's a way to filter arrays.

There is not but that would be a super cool thing to add!

**Comment by syzer** [comment]
Ok let's say we need that to work in similar way that
 ```
query BlogPostQuery($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      html
      frontmatter {
        title
      }
    }
  }
```
from tutorial
what files you would recommend me to dig deep to create PR ?

**Comment by syzer** [comment]
Also need to create global for `window` because gatsby build ` WebpackError: window is not defined`
So if you could give me a hint where to start , I would be much obliged

**Comment by KyleAMathews** [comment]
It's fairly complex. Basically we're ever we use `GraphQLList` we'd need to generate query operators specific to that list.

**Comment by KyleAMathews** [comment]
re) window — you need to make sure you're not importing libraries that rely on window unless you're in browser land. There's a docs page on this.

**Comment by KyleAMathews** [comment]
Use GraphQLList in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-type.js

**Comment by syzer** [comment]
In react statefull component there is ```e.slug === window.location.pathname```
so i just need to tell webpack that window is ok :).. dont transpile it...
AKA globals

**Comment by KyleAMathews** [comment]
use props.location.pathname and that'll work. Adding window to webpack still wouldn't work as you'd still not have a location object.

**Comment by syzer** [comment]
is `props` avaible in Pure component ?
similar to `data`?
of would that be a feature request?

**Comment by syzer** [comment]
Also: does ```<img src={`${__PATH_PREFIX__}/products/${product.icon}.svg`} alt="Product image"/>```
work with Statefull Component?

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
