### ISSUE TITLE
gatsby-background-image flickering and reshaping on scroll

### ISSUE THREAD

**Issue by Guiguerreiro39** [gatsbyjs/gatsby#27407]
## Summary

I am using the gatsby-background-image plugin on my background images but, on mobile, when scrolling up and down in a section with a background image is seems that the image is reshaping and flickering making it annoying and sometimes slow. My background images are set to fixed and this can cause that issue perhaps.

## Relevant information

You can check out this issue on this link [https://guilherme-guerreiro.netlify.app/](url)
To reproduce it, just be on a mobile phone and try scrolling up and down a bit faster than usual on the background image sections.

This issue does not occur when I'm testing the responsiveness on my laptop browser but everytime I tried it on a phone it happens.

I was hoping someone could help me out to solve this issue? I've tryed looking online but nothing solved it yet..

**Comment by vladar** [comment]
Thank you for opening this @Guiguerreiro39 

`gatsby-background-image` is a community plugin. I suggest you ask this question in their repo: https://github.com/timhagn/gatsby-background-image

Hopefully, they will be able to help! If not, please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby :muscle:
