### ISSUE TITLE
Your plugins must export known APIs from their gatsby-node.js.

### ISSUE THREAD

**Issue by saadaouad** [gatsbyjs/gatsby#27403]
## Description

I'm getting the error below after upgrading `gatsby-plugin-react-helmet` package from `3.3.13` to `3.3.14`:

```log
11:26:00 AM: Your plugins must export known APIs from their gatsby-node.js.
11:26:00 AM: The following exports aren't APIs. Perhaps you made a typo or your plugin is outdated?
11:26:00 AM: See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby Node APIs
11:26:00 AM: - The plugin "gatsby-plugin-react-helmet@3.3.14" is exporting a variable named "pluginOptionsSchema" which isn't an API.
```

/cc @mxstbr

**Comment by ascorbic** [comment]
Hi. Please upgrade to the latest version of gatsby to fix this. See #27370

**Comment by jorgechiapello** [comment]
I run with the same issue. Can the package.json from `gatsby-plugin-react-helmet` be updated to indicate that it needs at least gatsby 2.25?
