### ISSUE TITLE
Using different YAML files but just one template page

### ISSUE THREAD

**Issue by ItzaMi** [gatsbyjs/gatsby#27401]
## Summary
Currently I'm creating multiple pages from a single `yaml` file using a template page but over the time this is becoming too cumbersome and I figured that I'm doing this the hard way.
I would like to know if there's a way to address this issue on `gatsby-node` to allow for all the `yaml` files inside a certain folder to use the same template

## Relevant information
While looking at my `gatsby-node`, here's what you can find

```
const path = require('path');

const { createFilePath } = require('gatsby-source-filesystem');

const fs = require('fs');
const yaml = require('js-yaml');

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions;

  const ymlDoc = yaml.safeLoad(
    fs.readFileSync('./src/content/servicePages/servicePages.yaml', 'utf-8')
  );

  return graphql(`
    {
      allMarkdownRemark(sort: { order: DESC, fields: [frontmatter___date] }) {
        edges {
          node {
            frontmatter {
              categories
              tags
            }
            fields {
              slug
            }
          }
        }
      }
    }
  `).then((result) => {
    ymlDoc.forEach((element) => {
      createPage({
        path: element.path,
        component: require.resolve('./src/templates/services-pages.js'),
        context: {
          metadata: element.metadata,
          hero: element.hero,
        },
      });
    });
  });
};
```

As you can see, I'm currently creating all my `service pages` from a single yaml file named `servicePages.yaml` but I would like to be able to tell Gatsby to find all the `yaml` files and create pages for them lets say inside the `content/servicePages/` path

I figured that there should be a way for me to doing this but I'm not sure how to search for it. Any help would be appreciated

### File contents (if changed)

`gatsby-config.js`: N/A
`package.json`: N/A
`gatsby-node.js`: _Posted above_
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by vladar** [comment]
Thank you for opening this, @ItzaMi 

We have a similar example in our docs (but for Markdown): https://www.gatsbyjs.com/docs/adding-markdown-pages/

I assume you were trying to adapt it to YAML. I've built a quick example where the same approach is used for YAML: https://github.com/vladar/yaml-example

It requires you to install `gatsby-transformer-yaml` (and not parse YAML manually). Then you can query for YAML data the same way as markdown.

We're marking this issue as answered and closing it for now but please feel free to mention me this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by ItzaMi** [comment]
Hi, @vladar , and thank you for your quick reply 👋  I ended up facing some problems with your suggestion.

When I insert in my `gatsby-node` the portion of the code that you have in your example, like so
```
const path = require('path');

const { createFilePath } = require('gatsby-source-filesystem');
const { getBlogCategoryPath } = require('./src/utils');

const fs = require('fs');
const yaml = require('js-yaml');

exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions;
  if (node.internal.type === 'MarkdownRemark') {
    const slug = createFilePath({ node, getNode, basePath: 'pages' });
    createNodeField({
      node,
      name: 'slug',
      value: slug,
    });
  }
};

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions;

  const projectDoc = yaml.safeLoad(
    fs.readFileSync('./src/content/projectPages/projectPages.yaml', 'utf-8')
  );

  const ymlDoc = yaml.safeLoad(
    fs.readFileSync('./src/content/servicePages/servicePages.yaml', 'utf-8')
  );

  return graphql(`
    {
      allMarkdownRemark(sort: { order: DESC, fields: [frontmatter___date] }) {
        edges {
          node {
            frontmatter {
              categories
              tags
            }
            fields {
              slug
            }
          }
        }
      }
      allYamlPage {
        nodes {
          id
          path
        }
      }
    }
  `).then((result) => {
    ymlDoc.forEach((element) => {
      createPage({
        path: element.path,
        component: require.resolve('./src/templates/services-pages.js'),
        context: {
          metadata: element.metadata,
          hero: element.hero,
          # more data here
        },
      });
    });

    projectDoc.forEach((element) => {
      createPage({
        path: element.path,
        component: require.resolve('./src/templates/project-page.js'),
        context: {
          metadata: element.metadata,
          hero: element.hero,
          # more data here
        },
      });
    });
  });
};
```

`projectDoc` and `ymlDoc` were the ways I could find to get a template page to work using `yaml` but, of course, it's sourcing from a single file

I get an error telling me `Cannot query field "allYamlPage" on type "Query".` and also `Cannot read property 'allMarkdownRemark' of undefined`.
For this project I also need to maintain the `allMarkdownRemark` since we have a blog portion of the website (I can leave here the complete `gatsby-node` including the parts of the blog, if you think that that might help.

We're also querying `yaml` to our other files since that's how we're providing the content to our `about.js` and `index.js`, for example ( I don't know if that creates a conflict with the example you provide since it seems it fetches all the `yaml` files, correct?)
We do have `'gatsby-transformer-yaml'` and we're also using `'gatsby-source-filesystem'` like so
```
{
resolve: 'gatsby-source-filesystem',
  options: {
    name: 'content',
    path: `${__dirname}/src/content`
  }
},
```
