### ISSUE TITLE
Error 11328: No name but `undefined`

### ISSUE THREAD

**Issue by darcelvictor** [gatsbyjs/gatsby#27410]
## Description
I'm getting an error 11328 with unhelpful debugging information when I run gatsby build. Running gatsby develop works very fine.

### Steps to reproduce
Updated all my dependencies to latest, tried to build the project, it failed.
My repo : https://github.com/darcelvictor/Gatsby-Builder
clone it
and run `yarn install`
and `gatsby build`

### Expected result
The project should build like in `gatsby develop`

### Actual result
 ERROR #11328

A page component must export a React component for it to be valid. Please make sure this file exports a React component:

undefined

not finished createPagesStatefully - 0.068s

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.13.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 3.7.6 - /opt/anaconda3/bin/python
  Browsers:
    Chrome: 86.0.4240.75
    Safari: 14.0
  npmPackages:
    gatsby: ^2.24.73 => 2.24.74 
    gatsby-image: ^2.4.21 => 2.4.21 
    gatsby-plugin-fontawesome-css: ^1.0.0 => 1.0.0 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.4.34 => 2.4.34 
    gatsby-plugin-offline: ^3.2.31 => 3.2.31 
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.6.40 => 2.6.41 
    gatsby-plugin-styled-components: ^3.3.14 => 3.3.14 
    gatsby-source-filesystem: ^2.3.34 => 2.3.34 
    gatsby-transformer-sharp: ^2.5.17 => 2.5.17 
  npmGlobalPackages:
    gatsby-cli: 2.12.107

Thanks for your help

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

I found the reason for the `undefined` and sent in a PR. In this screenshot you can see the culprit now:

![image](https://user-images.githubusercontent.com/16143594/95829143-27ad5c80-0d36-11eb-9204-5e3a66404d33.png)

You need to move your `DATA` folder out of the `src/pages` directory as every js/jsx/tsx file there gets turned into page and needs to be a valid React component with a default export.

**Comment by darcelvictor** [comment]
Perfect, it works perfectly !
Thank you very much for your help !
