### ISSUE TITLE
Can't create dynamic routes for compare version

### ISSUE THREAD

**Issue by pacocom** [gatsbyjs/gatsby#27423]
I can't create dynamic pages with custom regular expression matchPath.
Example: Need dynamic routes similar to https://github.com/microsoft/TypeScript/compare/v4.0.2...v4.0.3 where v4.0.2 is **BaseVersion** after ... and afeter v4.0.3 is **CompareVersion**

```js
async function createDatasetComparePages({ graphql, actions }) {
  const { createPage } = actions;

  const result = await graphql(`
    {
      datasets {
        edges {
          node {
            fields {
              slug
            }
          }
        }
      }
    }
  `);
  result.data &&
    result.data.datasets.edges.forEach(({ node }) => {
      const {
        fields: { slug },
      } = node;

      createPage({
        path: `${slug}compare/:versions/`,
        matchPath: `${slug.replace(
          /\//,
          '\\/'
        )}compare/v\\d\\.\\d\\.\\d\\.{3}v\\d\\.\\d\\.\\d/`,
        component: path.resolve('src/templates/dataset-compare.tsx'),
        context: { slug },
      });
    });
}
```

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by wardpeet** [comment]
Hey,

Thanks for creating an issue, to get more info about matchPath you can follow https://www.gatsbyjs.com/docs/client-only-routes-and-user-authentication/ or look at https://reach.tech/router/example/url-params.

For your example something like this should work:
```
      createPage({
        path: `${slug}compare/`,
        matchPath: `${slug.replace(
          /\//,
          '\\/'
        )}compare/:versions`,
        component: path.resolve('src/templates/dataset-compare.tsx'),
        context: { slug },
      });
```

Regex type path matching is not supported

**Comment by wardpeet** [comment]
Thank you for opening this, @pacocom

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by pacocom** [comment]
Thank @wardpeet!
