### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR when using `gatsby develop --https`

### ISSUE THREAD

**Issue by Mrtenz** [gatsbyjs/gatsby#27427]
## Description

When using `gatsby develop --https`, I see a lot of `ERR_SSL_PROTOCOL_ERROR` errors in the console, for what seems to be `socket.io` related requests. I am using the (currently) latest version of Gatsby.

![image](https://user-images.githubusercontent.com/7503723/95875727-a1fbd200-0d72-11eb-92c8-169215bc7c9b.png)

It happens about every 5 seconds, which makes it annoying to use the console to debug other things. The page seems to work fine, and HMR works without issues too, regardless of the errors.

### Steps to reproduce

Go to this repo and follow the instructions: https://github.com/Mrtenz/gatsby-https-issue

Alternatively, run this in an existing Gatsby project:

1. Run `gatsby develop --https`
2. Open the page and check the console

### Expected result

There shouldn't be any SSL errors.

### Actual result

There are SSL errors.

### Environment

```
  System:
    OS: Linux 5.8 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.18.3 - /tmp/yarn--1602600057219-0.43846647488335666/node
    Yarn: 1.22.10 - /tmp/yarn--1602600057219-0.43846647488335666/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Languages:
    Python: 3.8.6 - /usr/bin/python
  Browsers:
    Firefox: 81.0.1
  npmPackages:
    gatsby: ^2.24.76 => 2.24.76
    gatsby-plugin-canonical-urls: ^2.3.13 => 2.3.13
    gatsby-plugin-create-client-paths: ^2.3.13 => 2.3.13
    gatsby-plugin-layout: ^1.3.13 => 1.3.13
    gatsby-plugin-manifest: ^2.4.34 => 2.4.34
    gatsby-plugin-offline: ^3.2.31 => 3.2.31
    gatsby-plugin-react-helmet-async: ^1.1.0 => 1.1.0
    gatsby-plugin-react-redux: ^1.1.0 => 1.1.0
    gatsby-plugin-robots-txt: ^1.5.3 => 1.5.3
    gatsby-plugin-s3: ^0.3.5 => 0.3.5
    gatsby-plugin-sitemap: ^2.4.16 => 2.4.16
    gatsby-plugin-styled-components: ^3.3.14 => 3.3.14
    gatsby-plugin-ts-config: ^1.1.0 => 1.1.0
    gatsby-plugin-typescript: ^2.4.21 => 2.4.21
    gatsby-plugin-typescript-checker: ^1.1.1 => 1.1.1
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.13 => 1.1.13
```

**Comment by wardpeet** [comment]
I don't have that issue on windows. I see that it's arch Linux. Are there other platforms that have this issue, like ubuntu?

**Comment by Mrtenz** [comment]
I made a minimal reproduction repo where I can reproduce this issue. Would be great if someone with Ubuntu could test this, as I do not have (easy) access to an Ubuntu machine.

https://github.com/Mrtenz/gatsby-https-issue

**Comment by Mrtenz** [comment]
I just tested it on Firefox, and I get a different error, CORS related:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:36443/socket.io/?EIO=3&transport=polling&t=NKhqkE-. (Reason: CORS request did not succeed).
```

![image](https://user-images.githubusercontent.com/7503723/96112382-cf678d80-0ee2-11eb-84e6-aef491eef669.png)

**Comment by iDiegoNL** [comment]
I can confirm that this issue also appears when using Ubuntu.
![image](https://user-images.githubusercontent.com/10339564/96114143-849b4500-0ee5-11eb-89bc-5ebcac5f8e1b.png)

**Comment by vrabe** [comment]
I access those URLs with curl, and curl returns
```
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by valeeum** [comment]
Same issue here.  Something to note is that on 2.24.78, the site is served on port 8000 but socket.io connection using another port. On 2.24.55, both site and socket.io connection is served over the same port and works as expected.

**Comment by tmttn** [comment]
This was broken in #27302. Looking at the related issue (#27294), the PR was trying to fix some mixed content errors. Looking at:
> bug introduced from: #24335 (particularly a7f92af)
I think that the fix in #27302 was too short-sighted. Namely because there were a lot of changes in #24335 to ensure that the socket.io connection would go through the proxy instead of directly to the socket.io server.

We are now bumping into CORS issues because the server does not allow localhost:8000 as an origin.

**Comment by scottalan** [comment]
Holy cow! ++ to tracking all that down.

I'm rolling back to gatsby@2.24.55 to confirm that what @valeeum stated earlier applies in our situation as well.

**Comment by tmttn** [comment]
> Holy cow! ++ to tracking all that down.
> 
> 
> 
> I'm rolling back to gatsby@2.24.55 to confirm that what @valeeum stated earlier applies in our situation as well.

With pleasure I investigated this in order to find a fix, but since I have no hands-on experience with the codebase yet, I wasn't sure how to tackle it. So I decided to document my findings instead. 😅

**Comment by wardpeet** [comment]
Thanks a lot for the information. I'll keep you posted and sorry for the inconviences

**Comment by tmttn** [comment]
In the end... it did prove to be that easy. I spent way too much time on this.

**Comment by tmttn** [comment]
Not stale, my PR just needs a review ;(

**Comment by valeeum** [comment]
I'm experiencing these issues again but this time on the develop server so the localhost dev server never loads to begin with.  The problem doesn't exist when I reference "gatsby": "4.14.1" in package.json but does when I specify "gatsby": "^4.14.1".  Depending on the version of gatsby I install i get one of the following errors: 

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/1195356/180049159-0865e250-b6ac-4036-b46d-f8b01a17cc47.png">

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/1195356/180049202-88d8bee4-d071-4563-bccd-2a593f81ef29.png">

**Comment by raulvictorrosa** [comment]
> I'm experiencing these issues again but this time on the develop server so the localhost dev server never loads to begin with. The problem doesn't exist when I reference "gatsby": "4.14.1" in package.json but does when I specify "gatsby": "^4.14.1". Depending on the version of gatsby I install i get one of the following errors:
> 
> <img alt="image" width="1097" src="https://user-images.githubusercontent.com/1195356/180049159-0865e250-b6ac-4036-b46d-f8b01a17cc47.png">
> 
> <img alt="image" width="1176" src="https://user-images.githubusercontent.com/1195356/180049202-88d8bee4-d071-4563-bccd-2a593f81ef29.png">

I'm acing the same with `"gatsby": "^4.19.2"`.

**Comment by darylthornhill** [comment]
I am also getting this with "gatsby": "^4.19.2" Any help anyone?
