### ISSUE TITLE
Search console - google is not indexing site

### ISSUE THREAD

**Issue by marketingsolution** [gatsbyjs/gatsby#27426]
Hi
do you have the same issue with indexing you sites created in gatsby?
Page detected - currently not indexed

I add sitemap, but it's not resolveing anything.
Page: https://moto-trips.com
sitemap: https://moto-trips.com/sitemap-pages.xml

**Comment by LekoArts** [comment]
Thank you for opening this!

I don't think we can help with this, please reach out to Google or some other platform as I don't think this is specific to Gatsby or a problem with Gatsby.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
