### ISSUE TITLE
"Too many open files" error w/ high-volume template

### ISSUE THREAD

**Issue by brandonmp** [gatsbyjs/gatsby#2743]
I have one template that's used to create ~700 nodes,  and the gql queries are pretty lengthy.

Today when I tried to add a new query for blog posts, the build (a) took much, much longer than normal, and (b) broke with an error about "Too many open files," referencing some JSONs in the `.cache`.  Removing the query brought things back to normal.

Here's the complete query from the offending template:

```
export const pageQuery = graphql`
    query ConsultantQuery($id: String!) {
        consultantsJson(id: { eq: $id }) {
            name
            id
            agencyId
            linkedInUrl
            officialBio
        }
        allConsultantJobsJson(
            sort: { fields: [endYear], order: DESC }
            filter: { consultantId: { eq: $id } }
        ) {
            edges {
                node {
                    companyName
                    startYear
                    endYear
                    durationInMonths
                    jobTitle
                }
            }
        }
        allGoogleSheetAppDataConsultantEducationRow(
            sort: { fields: [degreeName], order: DESC }
            filter: { consultantId: { eq: $id } }
        ) {
            edges {
                node {
                    schoolName
                    degreeName
                    startYear
                    endYear
                }
            }
        }
        allReviewsJson(filter: { consultantId: { eq: $id } }) {
            edges {
                node {
                    rating
                    date
                }
            }
        }
    }
allContentfulBlogPost(
            sort: { fields: [publishDate], order: DESC }
            limit: 4
        ) {
            edges {
                node {
                    title
                    slug
                    publishDate
                    mainPicture {
                        responsiveSizes(maxWidth: 500) {
                            base64
                            aspectRatio
                            src
                            srcSet
                            sizes
                        }
                    }
                }
            }
        }`;
```

The very last query, `allContentfulBlogPost`, is the one that broke the camels back.

I'm using Gatsby `1.9.9`--I know that's a bit out of date, but upgrading to latest breaks some things & I haven't had the time to debug.

**Comment by brandonmp** [comment]
btw: the workaround was to just add the `allContentfulBlogPost` query to `gatsby-node` and pass it down via `pathContext`. This avoided the error & resulted in a much quicker build to-boot.

**Comment by KyleAMathews** [comment]
This isn't something straightforward to fix in Gatsby (or really fixable — we can perhaps alleviate the issue but that's about it). The root problem is your OS restricts how many files a program can open. Once you hit that, it tries to stop you. To fix this on larger Gatsby sites, you'll want to google for instructions for your OS for upping the files open limit.

**Comment by brandonmp** [comment]
what's the difference in execution b/t putting it in the template & putting it in `gatsby-node`, then? Is there some implementation detail in `pageQuery` that's making it do far, far more work for a query than must be done in `gatsby-node`?

**Comment by KyleAMathews** [comment]
Not really… in both cases it writes out a file / page in `.cache/json`. Sounds like we're doing something inefficient though…

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
