### ISSUE TITLE
gatsby-source-shopify - Cache the data to speed up dev builds 

### ISSUE THREAD

**Issue by jasonbiondo** [gatsbyjs/gatsby#27459]
For the Shopify plugin, I have thousands of products and the build time is super slow.  Is there anyway to do a better job of cacheing this data?  I don't see a cache flag in the plugin and every time I run it the plugin fetches the data and rebuilds all the nodes.

**Comment by LekoArts** [comment]
Let's keep it contained to one issue :)
https://github.com/gatsbyjs/gatsby/issues/26726
