### ISSUE TITLE
Use a gatsby project as a node dependency on multiple repos

### ISSUE THREAD

**Issue by hk86** [gatsbyjs/gatsby#27455]
I've build a gatsby website and I would like deploy this website for three languages on three different domains. The codebase of each domain is the same, only the env vars are different (i.e. one env var is for the locale of the website). Is it possible to use the the gatsby website as a node module and install it as a dependency?

The idea is to end up with four repos:

- 1 general repo, this were all the components are defined
- 1 repo for the language en, the general repo is a dependency
- 1 repo for the language es, the general repo is a dependency
- 1 repo for the language kr, the general repo is a dependency

Sure I could copy the genral repo manually three times into the specific repos, but I would end up with redundant code and would need to copy the code each time I change the general repo. What is the right approach here?

**Comment by LekoArts** [comment]
Thank you for opening this!

What you're looking for are [Gatsby Themes](https://www.gatsbyjs.com/docs/themes/). You can pack the whole site into an npm package and make the `gatsby-config.js` configurable. Then in each of those sites you'd use the theme and only configure the options via `gatsby-config.js`.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by hk86** [comment]
Exactly what I was looking for! Thanks!
