### ISSUE TITLE
Filters in gatsby-source-drupal aren't added to the first page of results

### ISSUE THREAD

**Issue by blazeyo** [gatsbyjs/gatsby#27453]
## Description

`gatsby-source-drupal` has the `filters` option which has an issue. The filters are only applied starting from the second page of the results. The first one doesn't get them. Example:
first call: `/jsonapi/node/page`
second call: `/jsonapi/node/page?page[offset]=50&page[limit]=50?filter=value`

### Steps to reproduce

- Add the gatsby-source-drupal plugin with the filters option (example: `filters: { 'node--page': 'filter=value'  }`).
- Run the build and check the urls that are hit.

### Expected result

- The filters should be added to the first page
- They shouldn't be added to the next pages (the link in `next.href` returned by jsonapi already has them)

### Actual result

See description.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.19.0 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.75
    Firefox: 81.0
```

**Comment by kszot-ref** [comment]
This is still a valid issue, the `getNext` function always receives a string variable, so the codepath for adding filters never runs (as it's inside an if clause that checks wether the `url` variable is of type `object`)
