### ISSUE TITLE
gatsby plugin sitemap breaks build

### ISSUE THREAD

**Issue by arminyahya** [gatsbyjs/gatsby#27463]
## Description

I installed [gatsby-plugin-sitemap](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap#readme) and next added to plugins inside gatsby-config.js file.

after running gatsby build. build gives me errors

### Steps to reproduce

run:

`npm i gatsby-plugin-sitemap`

next:

add valid siteUrl to siteMetadata inside gatsby-config.js file.

next:

add `gatsby-plugin-sitemap`  to begining of plugins.

### Expected result

build finish successfully

### Actual result

 ```
ERROR #10123  CONFIG

We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.

  TypeError: "gatsby-plugin-sitemap" is not a function

  - gatsby-config.js:22 Object.<anonymous>
    F:/holdyourlight/gatsby-site/gatsby-config.js:22:5

  - v8-compile-cache.js:178 Module._compile
    [gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - loader.js:947 Object.Module._extensions..js
    internal/modules/cjs/loader.js:947:10

  - loader.js:790 Module.load
    internal/modules/cjs/loader.js:790:32

  - loader.js:703 Function.Module._load
    internal/modules/cjs/loader.js:703:12

  - loader.js:830 Module.require
    internal/modules/cjs/loader.js:830:19

  - v8-compile-cache.js:159 require
    [gatsby-site]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - get-config-file.js:33 getConfigFile
    [gatsby-site]/[gatsby]/dist/bootstrap/get-config-file.js:33:20

  - index.js:128 module.exports
    [gatsby-site]/[gatsby]/dist/bootstrap/index.js:128:46

  - build.js:90 build
    [gatsby-site]/[gatsby]/dist/commands/build.js:90:36

  - create-cli.js:174
    [gatsby-site]/[gatsby]/[gatsby-cli]/lib/create-cli.js:174:14

  - create-cli.js:101
    [gatsby-site]/[gatsby]/[gatsby-cli]/lib/create-cli.js:101:24

  - create-cli.js:35 Object.handler
    [gatsby-site]/[gatsby]/[gatsby-cli]/lib/create-cli.js:35:19

  - command.js:238 Object.runCommand
    [gatsby-site]/[gatsby]/[yargs]/lib/command.js:238:44

  - yargs.js:1063 Object.parseArgs [as _parseArgs]
    [gatsby-site]/[gatsby]/[yargs]/yargs.js:1063:30

  - yargs.js:566 Object.parse
    [gatsby-site]/[gatsby]/[yargs]/yargs.js:566:2 5


not finished open and validate gatsby-configs -
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@0.1.0 build: `gatsby clean && gatsby build`
npm ERR! Exit status 1
```

### Environment

  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD  Languages:
    Python: 3.8.5
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.21.13 => 2.21.13
    gatsby-image: ^2.4.1 => 2.4.1
    gatsby-plugin-manifest: ^2.4.2 => 2.4.2
    gatsby-plugin-offline: ^3.2.1 => 3.2.1
    gatsby-plugin-preact: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-remote-images: ^2.2.0 => 2.2.0
    gatsby-plugin-sharp: ^2.6.1 => 2.6.1
    gatsby-plugin-sitemap: ^2.4.16 => 2.4.16
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.9 => 1.1.9
    gatsby-source-custom-api: ^2.1.4 => 2.1.4
    gatsby-source-filesystem: ^2.3.1 => 2.3.1
    gatsby-source-multi-api: ^1.0.3 => 1.0.3
    gatsby-source-rest-api: ^0.2.3 => 0.2.3
    gatsby-transformer-sharp: ^2.5.1 => 2.5.1
  npmGlobalPackages:
    gatsby-cli: 2.12.13

@Pearce-Ropion

**Comment by arminyahya** [comment]
I realized if I move plugin name to end of plugins, the error disappears, and build finish successfully

**Comment by pieh** [comment]
Hey @arminyahya 

Can you provide sample `gatsby-config` content that caused this error?

**Comment by pieh** [comment]
I managed to reproduce this exact error when I had missing comma in gatsby-config plugins:

```
plugins: [
  `gatsby-plugin-sitemap`
  `gatsby-plugin-sharp`
]
```

It goes away as soon as I add missing comma between items. This is unfortunate error message, but it also comes directly from JS interpreter

**Comment by arminyahya** [comment]
Thank you @pieh.
That's missing comma causing the error.
