### ISSUE TITLE
Can't install gatsby-cli

### ISSUE THREAD

**Issue by Alxandr** [gatsbyjs/gatsby#2746]
The cli won't install because of missing `gatsby.js` file (which it's trying to link to from the `.bin` folder).

**Comment by KyleAMathews** [comment]
https://github.com/gatsbyjs/gatsby/commit/40db8d9a7dcd2e39e5ab32ea82bc3bf8b3caac2b was needed too I think. Just published that so we'll see

**Comment by KyleAMathews** [comment]
Ok, yeah, just reinstalled gatsby-cli@1.1.17 successfully.

**Comment by KyleAMathews** [comment]
Thanks for the bug report!
