### ISSUE TITLE
I can no longer run "gatsby develop"  

### ISSUE THREAD

**Issue by Abdelfatahh** [gatsbyjs/gatsby#27484]
I am using contentful and gatsby and yesterday i tried to add some adjustment to my project and i figured out it doesn't work as it is suppose to work. it gives me the following error: 

success open and validate gatsby-configs - 0.046s
success load plugins - 2.138s
success onPreInit - 0.040s
success initialize cache - 0.016s
success copy gatsby files - 0.147s
success onPreBootstrap - 0.028s
success createSchemaCustomization - 0.068s

` ERROR `

Accessing your Contentful space failed.
Try setting GATSBY_CONTENTFUL_OFFLINE=true to see if we can serve from cache.

Used options:
spaceId: "*********1o5"
accessToken: "***************************************6xaI"
host: "preview.contentful.com"
environment (default value): "master"
downloadLocal (default value): false
localeFilter (default value): [Function]
forceFullSync (default value): false
pageLimit (default value): 100
useNameForId (default value): true

`not finished` source and transform nodes - 1.275s
`not finished` Contentful: Fetch data (gldthkygs1o5-master) - 1.083s

## What I tried to do :
1. I tried to update the whole `package.json` 
2. I tried to delete the cache and re-build. 
3. I tried to use another environmet on contentful and I made sure that the maste checkbox is checked.
4. I deleted the usual API key from contentful and created a new one. 

# none of the above worked for me 😢

**Comment by wardpeet** [comment]
could you share the gatsby-source-contentful version?

Could you also try running gatsby with `GATSBY_EXPERIMENTAL_PLUGIN_OPTION_VALIDATION=1`

**Comment by Abdelfatahh** [comment]
Hello @wardpeet !

"@contentful/rich-text-react-renderer": "^14.1.1",
    "gatsby-source-contentful": "^2.3.53",

I ran the command you mentioned above 
`npx cross-env GATSBY_EXPERIMENTAL_PLUGIN_OPTION_VALIDATION=1 gatsby develop` 
and it worked successfully! Can you tell me what is this about? and Thanks alot! ❤️

**Comment by wardpeet** [comment]
Unsure to be honest, GATSBY_EXPERIMENTAL_PLUGIN_OPTION_VALIDATION is a new feature we're launching soon and I was just checking if it was a mistake we made along the way. I can't seem to reproduce this on contentful.

Does the following values look correct?
```
spaceId: "*********1o5"
accessToken: "***************************************6xaI"
host: "preview.contentful.com"
environment (default value): "master"
downloadLocal (default value): false
localeFilter (default value): [Function]
forceFullSync (default value): false
pageLimit (default value): 100
useNameForId (default value): true
```

**Comment by tgallacher** [comment]
I am experiencing something similar. 

Have a setup with Gatsby + Contentful.

Running `gatsby build` runs and seems to complete as expected. However, running `gatsby develop` fails to complete; it gets stuck on `createPages`... It doesn't output any errors, warnings, etc. Just presents a never-ending spinner.

Running with the `GATSBY_EXPERIMENTAL_PLUGIN_OPTION_VALIDATION=1` var doesn't provide any additional insight or resolve the issue. 

I have similarly tried updating the dependencies, cleaning the Gatsby cache (`gatsby clean`) etc. But so far nothing seems to have worked 😢 . 

Any thoughts? 

For ref, my gatsby info

```

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /var/folders/t8/gcrtnx0d4b30wll3rf30r0r40000gn/T/yarn--1603113913670-0.03923147032622776/node
    Yarn: 1.22.4 - /var/folders/t8/gcrtnx0d4b30wll3rf30r0r40000gn/T/yarn--1603113913670-0.03923147032622776/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Languages:
    Python: 3.7.7 - /Users/<my_username>/.pyenv/shims/python
  Browsers:
    Chrome: 86.0.4240.80
    Safari: 13.1.2
  npmPackages:
    gatsby: 2.24.80 => 2.24.80 
    gatsby-background-image: ^0.10.2 => 0.10.2 
    gatsby-cli: 2.12.109 => 2.12.109 
    gatsby-image: ^2.2.40 => 2.4.21 
    gatsby-plugin-client-side-redirect: 0.0.2 => 0.0.2 
    gatsby-plugin-intercom: ^0.1.4 => 0.1.4 
    gatsby-plugin-manifest: ^2.2.41 => 2.4.35 
    gatsby-plugin-offline: ^3.1.2 => 3.2.34 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.3.14 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-remove-trailing-slashes: ^2.1.21 => 2.3.13 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.3 
    gatsby-plugin-sass: ^2.1.28 => 2.3.18 
    gatsby-plugin-segment-js: 3.1.0 => 3.1.0 
    gatsby-plugin-sharp: ^2.4.5 => 2.6.43 
    gatsby-plugin-sitemap: ^2.2.27 => 2.4.17 
    gatsby-plugin-typescript: ^2.1.27 => 2.4.22 
    gatsby-remark-embed-video: ^1.7.1 => 1.7.1 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-highlights: ^1.3.4 => 1.3.4 
    gatsby-remark-images-contentful: ^2.3.19 => 2.3.19 
    gatsby-remark-prismjs: ^3.3.31 => 3.5.16 
    gatsby-source-contentful: 2.3.55 => 2.3.55 
    gatsby-source-filesystem: ^2.1.48 => 2.3.35 
    gatsby-source-marketo-forms: ^0.0.3 => 0.0.3 
    gatsby-transformer-remark: ^2.6.50 => 2.8.43 
    gatsby-transformer-sharp: ^2.3.14 => 2.5.18 
    gatsby-transformer-sqip: ^2.1.64 => 2.3.44 
```

**Comment by wardpeet** [comment]
@tgallacher mind sharing your repo and steps on how to run it to ward@gatsbyjs.com. I can't help you much with the provided info..

**Comment by tgallacher** [comment]
> @tgallacher mind sharing your repo and steps on how to run it to [ward@gatsbyjs.com](mailto:ward@gatsbyjs.com). I can't help you much with the provided info..

Thanks for reaching out @wardpeet. Unfortunately the repo is private (my employer's). 

I appreciate there isn't much detail in my above comment to go on, wanted to just register that I have a similar (possibly the same) problem. Mostly trying to increase the signal here that something might be off, in case anyone else stumbles here. 

I'll noodle a little bit more on this and see if I can come up with anything. 

thanks again!
