### ISSUE TITLE
gatsby onCreatePage only for static pages

### ISSUE THREAD

**Issue by pacocom** [gatsbyjs/gatsby#27486]
I need onCreatePage for dynamic pages with template
Example: 

```js
async function createComparePages({ graphql, actions }) {
  const { createPage } = actions;

  const result = await graphql(`
...
`);

result.data.forEach (...) {
      const page = {
        path: `${slug}compare/`,
        component: path.resolve('src/templates/dataset-compare.tsx'),
        context: { slug },
        matchPath: `${slug}compare/*`,
      };

      createPage(page);
}

async function onCreatePage({ page, actions }) {
  console.log('onCreatePage', page.path);
  const { createPage } = actions;

  if (page.path.match(/\/compare\//)) {
    page.matchPath = `${page.path}:urlCompareString/`;
    createPage(page); // page with param
  }
}

```

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment]
Thank you for opening this!

That's not possible. You'll need to have your logic in your React frontend of the client-only page. Please also fill out all the requested information in the issue template in the future as your description is quite sparse.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
