### ISSUE TITLE
<gatsby-plugin-typescript> transpileOnly should be configurable

### ISSUE THREAD

**Issue by PepperTeasdale** [gatsbyjs/gatsby#2749]
The typescript integration is super easy to set up, which I love, but it sets `transpileOnly` to `true`, which seems to be a bit beside the point for most use cases. Used in conjunction with [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin), this is still useful, but it would be helpful to document this or to make this option configurable. If you are open to a PR, I would be happy to add support for this.

Thanks!

**Comment by KyleAMathews** [comment]
So make transpileOnly optional?

I don't know the Typescript ecosystem well but making non required options overridable is always great!

**Comment by syzer** [comment]
:ittle bit off topic but is `gatsby-flow` planned?
