### ISSUE TITLE
disableCorePrefetching disables preload in development but not with production build

### ISSUE THREAD

**Issue by everly-blake** [gatsbyjs/gatsby#27508]
## Description

When using `exports.disableCorePrefetching = () => true` and running the app locally with `gatsby develop`, links to js and json files correctly do not have a `preload` tag.

However, when doing a production build with `gatsby build`, the `preload` tags are not removed.

### Steps to reproduce

1. Add `exports.disableCorePrefetching = () => true` to `gatsby-browser.js`
2. Run app in dev mode
3. inspect html, cmd + f,  and observe `preload` tags are missing
4. build build production app locally with `gatsby build` and `gatsby serve`
5. inspect html, cmd + f,  and observe `preload` tags are back

### Expected result

Preload tags should not be present in production build.

### Actual result

Preload tags are present in production build.

### Environment

 ```
 System:
    OS: macOS Mojave 10.14.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.80
    Firefox: 81.0.1
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.22.12 => 2.23.9 
    gatsby-cli: ^2.10.9 => 2.12.49 
    gatsby-image: ^2.2.23 => 2.4.8 
    gatsby-plugin-emotion: ^2.0.5 => 2.0.7 
    gatsby-plugin-force-trailing-slashes: ^1.0.4 => 1.0.4 
    gatsby-plugin-google-tagmanager: ^2.1.15 => 2.3.6 
    gatsby-plugin-manifest: ^2.2.21 => 2.4.13 
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3 
    gatsby-plugin-offline: ^2.0.5 => 2.2.10 
    gatsby-plugin-preload-link-crossorigin: ^1.0.2 => 1.0.2 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.3.5 
    gatsby-plugin-sharp: ^2.0.5 => 2.6.13 
    gatsby-plugin-sitemap: ^2.2.17 => 2.4.6 
    gatsby-plugin-styled-components: ^3.3.9 => 3.3.10 
    gatsby-plugin-typescript: ^2.0.0 => 2.4.7 
    gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.13 => 1.1.13 
    gatsby-source-contentful: ^2.0.1 => 2.3.17 
    gatsby-transformer-remark: ^2.1.5 => 2.8.18 
    gatsby-transformer-sharp: ^2.2.19 => 2.5.6 
```

**Comment by wardpeet** [comment]
@everly-blake We always add preload tags for page-data and necessary files for that page. This simply disables prefetching of links on the page
