### ISSUE TITLE
Gatsby build has blurry images

### ISSUE THREAD

**Issue by Lylio** [gatsbyjs/gatsby#27517]
## Description

I'm fairly new to React/Gatsby and have just tweaked a template to create the site [www.flakyrecords.com](url).

I packaged the site using the Gatsby command `gatsby build` which creates the website in the public folder. I then copied all of the files and folders from this public directory to my hosting provider.

For the most part, it worked - however, as you can see, the images are extremely blurry. Is there something obvious I need to do here in order to publish the images as sharp/in focus?

Many thanks.

### Steps to reproduce

1. gatsby build
2. Copy everything from local 'public' folder to my hosting provider
3. Observer blurry images: [www.flakyrecords.com](url)

### Expected result

Images should be clear/sharp

### Actual result

Images are very blurry

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

   System:
     OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
     CPU: (4) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
     Shell: 5.8 - /usr/bin/zsh
   Binaries:
     Node: 10.19.0 - /usr/bin/node
     Yarn: 1.22.5 - /usr/bin/yarn
     npm: 6.14.5 - /usr/local/bin/npm
   Languages:
     Python: 3.8.5 - /usr/bin/python
   Browsers:
     Chrome: 86.0.4240.75
     Firefox: 81.0
   npmPackages:
     gatsby: ^2.23.7 => 2.23.11
     gatsby-image: ^2.4.7 => 2.4.9
     gatsby-plugin-manifest: ^2.4.12 => 2.4.14
     gatsby-plugin-offline: ^3.2.11 => 3.2.13
     gatsby-plugin-react-helmet: ^3.3.4 => 3.3.6
     gatsby-plugin-sass: ^2.3.4 => 2.3.6
     gatsby-plugin-sharp: ^2.6.12 => 2.6.14
     gatsby-source-filesystem: ^2.3.12 => 2.3.14
     gatsby-transformer-sharp: ^2.5.5 => 2.5.7
   npmGlobalPackages:
     gatsby-cli: 2.12.108

**Comment by validity-check** [comment]
Hi, I would like to see if I can do anything here. Are the images blurry in development?

**Comment by xaverfleer** [comment]
[Stackoverflow response](https://stackoverflow.com/questions/64405255/gatsby-js-has-blurry-images/64414502#64414502)

Your image paths are wrong.

**Comment by Lylio** [comment]
Thanks for the advice. I don't understand where the long string in the url comes from, after the/static/. However, if I create the folder and subfolder (a4acc2fd3768aba6c88aea6e0ca345b2/26a97/) within my hosting provider instance, and upload the lyle-03.png, then the website www.flakyrecords.com returns a sharp, in focus image. But do you know why this extra long String is being created in the filename? I had hope to simply upload my images straight into the static folder on my hosting provider (i.e. static/lyle-03.png) as that's how it is locally and works fine.

**Comment by xaverfleer** [comment]
I agree, it's sometimes confusing how resources are loaded/ where you need to upload your assets.

Are you working in a public repository? I can take a look at its configuration.

**Comment by dominikkurbiel** [comment]
Hey, I have the same issue but it looks like images are not working only in `/` (home) path which is index.html in public directory. So on `/contact` or other everything works perfect. 

Moreover, I'm getting strange error on home path: `Uncaught (in promise) Error: page resources for / not found. Not rendering React`.

Maybe this is connected somehow or do you have any idea how to fix it?

**Comment by xaverfleer** [comment]
@dominikkurbiel your issue sounds like the import path to the image is incorrect.

Hard to tell without looking at your code.

Are you working in a public repository? I can take a look.

**Comment by dominikkurbiel** [comment]
@xaverfleer that would be perfect.

This is my repo: https://github.com/dominikkurbiel/mali_streamerzy

I just put my /public folder content to the FTP server, and its live here: https://www.malistreamerzy.pl/

Like I said it's not working only on home directory. (logo in the footer) When you enter any other page like https://www.malistreamerzy.pl/kontakt its working perfectly. Also mobile menu is not working on home path probably because this React error. On other pages its working smooth.

**Comment by Lylio** [comment]
My repo is https://github.com/Lylio/flaky-records-webapp if you wouldn't mind having a look.

I've managed to fix the blurred images on desktop browser anyway, on my mobile, one of the images is stubborn and remains blurred. But the directory hierarchy/file-path on my hosting isn't pretty:

flakyrecords.com
|
|___ static
       |
       |___ 25d4a183ea655f7d2f80fc31f51c9cdf
              |
              |___ 73c85
                     |
                     |___ lyle-03.png


There are a couple of dozen folders in the public > static folder that have enormous Strings like '25d4a183ea655f7d2f80fc31f51c9cdf' as their file-names.
