### ISSUE TITLE
Errors even when no code present: Call stack size / cannot read property 

### ISSUE THREAD

**Issue by inblock-io** [gatsbyjs/gatsby#27515]
## Description
I have an issue I need help with that seems to have popped up a few times over the years. I have burned 8 hours, one full work day, and this is too much.

**Backstory:** Have a working page that needed updates. Unfortunately for some reason,  after 2.5 months of no updates and no changes, it has stopped building, on both netlify and local development, throwing either
a)   `RangeError: Maximum call stack size exceeded`
b)   `TypeError: Cannot read property 'internal' of null`

### Steps to reproduce

- Clone https://github.com/inblock-io/inblock
- npm install
- you will need the following add these access tokens to (these are Ok to post> spaceid: lil8n4syivvk , content api access token: rJ6yJJXuukb5K7ghg761Aj0w0rvcOKTwSeKHxcztYLI) to the `.contentful.json.sample` file in the project root and REMOVE the `.sample` extension

### Expected result

npm run dev -> content pulled from contentful, everybody happy, page is served

### Actual result

a)   `RangeError: Maximum call stack size exceeded`
b)   `TypeError: Cannot read property 'internal' of null`

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.75
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.38)
  npmPackages:
    gatsby: ^1.9.279 => 1.9.279 
    gatsby-image: ^1.0.55 => 1.0.55 
    gatsby-link: ^1.6.46 => 1.6.46 
    gatsby-plugin-react-helmet: ^1.0.8 => 1.0.8 
    gatsby-plugin-sharp: ^1.6.46 => 1.6.48 
    gatsby-source-contentful: ^1.3.54 => 1.3.54 
    gatsby-transformer-remark: ^1.7.44 => 1.7.44 
  npmGlobalPackages:
    gatsby: 2.24.53

### Commentary

1st I thought it might be this behind it: 
https://github.com/gatsbyjs/gatsby/blob/639a0ca2cffc8009602b808cc165c74ff4ce5dc5/packages/gatsby-plugin-react-helmet/README.md#compatibility-with-react-168-useeffect-hook
- But the project uses React 15.x
2nd I thought it might be this: https://github.com/gatsbyjs/gatsby/issues/6949#issuecomment-477463165
- No content has been removed on contentful ... it is a mystery. 

How can I find out what the hell is going on? If this is an offending, failing graphQL query, how do i troubleshoot if I cannot even get graphiql locally?

**Comment by inblock-io** [comment]
Update:

I have found the generic graphiQL endpoint and instance for our contentful project. [Feel free to peruse, access tokens included (click) ](https://graphql.contentful.com/content/v1/spaces/lil8n4syivvk/explore?access_token=rJ6yJJXuukb5K7ghg761Aj0w0rvcOKTwSeKHxcztYLI)

### Insight

I realized that the "old", orignally working queries don't work any longer [gatsby-node.js]:
```
resolve(
    graphql(
          {
            allContentfulBlogPost {
              edges {
                node {
                  title
                  slug
                }
              }
            }
```
But using the project's graphiQl I realized those do not work any more and discovered these that work:

```
resolve(
      graphql(
        `
          {
            blogPostCollection {
              items {
                title
                slug
              }
            }
```

**But they do not solve the issue - in fact, when building the project both query types work.. ?!**

**Comment by axe312ger** [comment]
Closed because of no more feedback by the creator

**Comment by le-dawg** [comment]
This is still active, I have been troubleshooting withusers in the jamstack and contentful slack servers.

**Comment by le-dawg** [comment]
cc @axe312ger

**Comment by axe312ger** [comment]
@le-dawg thank you! reopening!

**Comment by le-dawg** [comment]
> Hey @inblock-io ,
> 
> the generic GraphQL endpoint is unrelated to what you do in Gatsby when using gatsby-source-contentful.
> 
> The code of your project is very old, it is still running Gatsby v1.
> 
> Please consider upgrading your project, you miss a huge load of features and bugfixes in Gatsby and the contentful plugin as well.
> 
> Best,
> Benedikt

OK, that is theortetically good feedback. I am not the developer of this project, I have inherited it and am faced with these issues. 
From what I understood upgrading to gatsby v2 is not a simple config update but a full refactoring of the code.Is this correct?

I would like some more clarity on this as well:
> the generic GraphQL endpoint is unrelated to what you do in Gatsby when using gatsby-source-contentful.

When gatbsy source contentful fails for some reason (which is probably somehow contentful related) then how can this be separate from directlz querying contentful?

**Comment by axe312ger** [comment]
> > Hey @inblock-io ,
> > the generic GraphQL endpoint is unrelated to what you do in Gatsby when using gatsby-source-contentful.
> > The code of your project is very old, it is still running Gatsby v1.
> > Please consider upgrading your project, you miss a huge load of features and bugfixes in Gatsby and the contentful plugin as well.
> > Best,
> > Benedikt
> 
> OK, that is theortetically good feedback. I am not the developer of this project, I have inherited it and am faced with these issues.
> From what I understood upgrading to gatsby v2 is not a simple config update but a full refactoring of the code.Is this correct?

As Gatsby v1 is pretty long ago, the deployed page on inblock.io is partly broken and the a quick look on your code tells me its not really complex, I'd recommend to redo it, at least partly.

You could try the following, could be done in a few hours:

* start a new gatsby v2 project with a bootstrap starter: https://www.gatsbyjs.com/starters/jaxx2104/gatsby-starter-bootstrap
* you should be able to keep your `src/components` and `src/pages` files. You might have to change some imports due to API changes in some dependencies (react helmet for example).
* refactor the old `src/templates`, `src/layouts` and `src/html.js` into the new structure. 


> 
> I would like some more clarity on this as well:
> 
> > the generic GraphQL endpoint is unrelated to what you do in Gatsby when using gatsby-source-contentful.
> 
> When gatbsy source contentful fails for some reason (which is probably somehow contentful related) then how can this be separate from directlz querying contentful?

When the plugin does not when actually getting data from Contentful in the very beginning, the error is related to something within Gatsby.

Gatsby stores are copy of your Contentful data and enhances it with a lot of useful things.

The GraphQL endpoint from Contentful is pretty new and the Gatsby plugin predates it several years.

That means the GraphQL you use in Gatsby is not exactly the same you would use on the official, new GraphQL endpoint. (We are planning to align this)
