### ISSUE TITLE
Broken Link - https://www.gatsbyjs.com/docs/typography-js/

### ISSUE THREAD

**Issue by tathagatbanerjee** [gatsbyjs/gatsby#27529]
## Summary

The link in the Gatsby docs to the typography page is broken.

![image](https://user-images.githubusercontent.com/11780602/96390378-0f3eb580-1200-11eb-8110-7de0a94e227e.png)

Currently it points to below - 

![image](https://user-images.githubusercontent.com/11780602/96390401-2b425700-1200-11eb-9e98-6abd78af6223.png)

Am pretty sure it should point to 

![image](https://user-images.githubusercontent.com/11780602/96390418-490fbc00-1200-11eb-94b0-0da5bc526b82.png)

No big deal, but unsure so posted as issue instead of fix and pull request. Thanks so much for looking at it.

**Comment by LekoArts** [comment]
Thanks! This was due to an outdated sidebar which I fixed now :)

**Comment by tathagatbanerjee** [comment]
Thank you!
