### ISSUE TITLE
Plugin should download the assets to the static folder but don't work

### ISSUE THREAD

**Issue by rcapdepaula** [gatsbyjs/gatsby#27524]
I'm using this plugin https://www.gatsbyjs.com/plugins/@draftbox-co/gatsby-wordpress-inline-images/ following all instructions, but does not work.

The plugin should download the assets to the Gatsby static folder but don't work.

My Gatsby Blog Post:
![nmAQkUp](https://user-images.githubusercontent.com/59542732/96377390-d6e59b80-115b-11eb-8577-ff2d076deb70.png)

Does anyone know what could be going wrong?

**Comment by LekoArts** [comment]
We're not maintaining `@draftbox-co/gatsby-wordpress-inline-images` so please open an issue on their repository. Thanks!
