### ISSUE TITLE
Updates in Contentful are not reflected in Gatsby

### ISSUE THREAD

**Issue by MarcMagdi** [gatsbyjs/gatsby#27543]
## Description

My current stack is Contentful as CMS, Gatsby which is hosted on Netlify. 
The current issue is that in some time (not always), when creating new pages in Contentful it's not reflected in Gatsby. 
In gatsby-node we are iterating over the pages we have in Contentful and use createPage API to create a new web page for it. 
When creating new web pages, we can't see that this page got created in Gatsby until we do a **delete of the cache** and trigger a new build

### Steps to reproduce

Unfortunately, we don't have a clear way to reproduce the issue, it disappears for a few days and then comes back, no clear repro or scenario we faced. 

### Environment
We currently have the [netlify-plugin-gatsby-cache](https://github.com/jlengstorf/netlify-plugin-gatsby-cache) installed in our Netlify env. 
We also enabled the incremental build in Netlify using this command
``GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build ``

 ```
 System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.75
    Firefox: 81.0.2
  npmPackages:
    gatsby: ^2.21.37 => 2.21.37
    gatsby-background-image: ^1.1.2 => 1.1.2
    gatsby-image: ^2.4.16 => 2.4.16
    gatsby-plugin-google-analytics: ^2.3.14 => 2.3.14
    gatsby-plugin-manifest: ^2.4.5 => 2.4.5
    gatsby-plugin-netlify: ^2.3.10 => 2.3.10
    gatsby-plugin-nprogress: ^2.3.11 => 2.3.11
    gatsby-plugin-offline: ^3.2.3 => 3.2.3
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-sass: ^2.3.2 => 2.3.3
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1
    gatsby-plugin-sharp: ^2.6.27 => 2.6.27
    gatsby-source-contentful: ^2.3.55 => 2.3.55
    gatsby-source-filesystem: ^2.3.4 => 2.3.4
    gatsby-source-graphql: ^2.7.6 => 2.7.6
    gatsby-transformer-remark: ^2.8.28 => 2.8.28
    gatsby-transformer-sharp: ^2.5.13 => 2.5.13
```

**Comment by wardpeet** [comment]
Hey @MarcMagdi

Sorry to hear you're running into an issue. netlify-plugin-gatsby-cache isn't owned by us so it's best to create an issue in https://github.com/jlengstorf/netlify-plugin-gatsby-cache. Can you try without netlify-plugin-gatsby-cache? If the issue still persists please re-open this issue or create a new one.

If you're looking for faster builds & incremental ones you should checkout https://www.gatsbyjs.com/cloud/.

Thank you for using Gatsby!
