### ISSUE TITLE
Does every library need to implement the SSR API in Gatsby?

### ISSUE THREAD

**Issue by mhyrr** [gatsbyjs/gatsby#2755]
I'm using https://github.com/jxnblk/grid-styled along with Styled Components to setup and layout a Gatsby site, and I'm getting an initial page load of some of the global styles/fonts, followed by the overall layout later.  

Does any additional library used also need to implement the Gatsby SSR API to get a nice smooth page load?  What am I missing?  Example: http://justadream.co/

**Comment by KyleAMathews** [comment]
Are you using gatsby-plugin-styled-components?

**Comment by mhyrr** [comment]
Yep!

**Comment by KyleAMathews** [comment]
Look at the HTML that's being outputted for your site and see what css is there. The grid library uses styled components so is fine. Perhaps there's a configuration problem with gatsby-plugin-styled-components

**Comment by mhyrr** [comment]
I removed everything except base styled components as a test, and it's still happening, so I'm assuming you're correct.  But I thought the plugin simply had to be referenced in the gatsby-config?

Layout and index templates are linked in head with a rel=preload attribute.  The global and component CSS are in head also, but down near the bottom, underneath all the js refs.

**Comment by mhyrr** [comment]
Figured it out!  Completely unrelated.. had some extraneous fonts being loaded but not used from the starter project.  Once I removed them, it loaded properly.  Thanks for looking!

**Comment by mhyrr** [comment]
If I have a components directory that I'm referencing in layouts or index.js, is there anything special needed?  I assume that their imports are enough for webpack.

**Comment by mhyrr** [comment]
Fixed this, fonts weren’t being loaded initially, which seemed to cause the rerender.  Handled them all in the injectGlobal and issues went away.
