### ISSUE TITLE
Docs about adding search with Typesense (an open source alternative to Algolia)

### ISSUE THREAD

**Issue by jasonbosco** [gatsbyjs/gatsby#27560]
## Summary

The docs currently provide two options for adding search [here](https://www.gatsbyjs.com/docs/adding-search/): 

1. ElasticLunr / Lunr 
2. Algolia

The first option is browser-based search which (like the docs point out) could result in large bundle sizes for even moderately heavy-content sites, since the index is pulled into the browser. The only other alternative is Algolia.

While Algolia provides a generous DocSearch option, it is only free for open source documentation sites. For other use cases, it is still a proprietary offering that can get expensive for Gatsby sites with a lot of content, traffic or both. Also, the [Algolia Gatsby plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-algolia/) is currently in beta and not supported.

I think it would benefit the Gatsby community to have the option of integrating with an open source, server-based search engine alternative to Algolia - Typesense: http://github.com/typesense/typesense. 

I recently created a Gatsby plugin to index site content to Typesense here: https://github.com/typesense/gatsby-plugin-typesense. 

Would you be open to adding Typesense as an additional open source search option to this docs page: https://www.gatsbyjs.com/docs/adding-search, along with a new sub-page with a detailed walk-through of how to add a search bar with Typesense?

### Motivation

Typesense is an open source alternative to Algolia and a lighter-weight and easier-to-use alternative to ElasticSearch. The current search solutions mentioned in the Gatsby docs are:

- Browser-based (and so only useful for smaller Gatsby sites)
- Proprietary and expensive at moderate scale (like Algolia)
- Open source and complex to administer and run (like ElasticSearch / Solr)

[Typesense](https://github.com/typesense/typesense) on the other hand is open source and is simple to use and scale. So having Typesense as an option for a search server would benefit Gatsby users looking for an easy-to-use search alternative to existing solutions.

## Steps to resolve this issue

I'm happy to contribute a PR to the docs, once this issue is reviewed by the Gatsby team.

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by jasonbosco** [comment]
@pvdz any updates on this? Just need a yay or nay.

**Comment by meganesu** [comment]
Hi there! Thanks for your patience and for taking the time to open this issue.

We recently announced a new project to [reorganize our existing documentation](https://github.com/gatsbyjs/gatsby/discussions/27856). To limit the number of moving pieces, we're not accepting contributions for new docs at this time.

For now, I'm going to close this issue. After we finish the docs reorganization, we can revisit whether this issue should be reopened.

Thanks again for your contribution! 💜

**Comment by jasonbosco** [comment]
Sounds good. Looking forward to the new docs!
