### ISSUE TITLE
(gatsby new ; gatsby develop) Error: The result of this StaticQuery could not be fetched.

### ISSUE THREAD

**Issue by Mehuge** [gatsbyjs/gatsby#27577]
## Description

Newly created gatsby website errors with:

![image](https://user-images.githubusercontent.com/99895/96622554-01715900-1302-11eb-9275-fd607c0a3488.png)

### Steps to reproduce

```
npm i -g gatsby-cli
gatsby new mywebsite
cd mywebsite
gatsby develop
```
Then browse to http://localhost:8000/

### Expected result

gatsby-starter-default website should be displayed.

### Actual result

Error: The result of this StaticQuery could not be fetched.

### Environment

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
  Binaries:
    Node: 12.17.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - ~\AppData\Roaming\npm\npm.CMD
  Languages:
    Python: 3.7.0 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.75
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.24.79 => 2.24.79 
    gatsby-image: ^2.4.21 => 2.4.21 
    gatsby-plugin-manifest: ^2.4.34 => 2.4.34 
    gatsby-plugin-offline: ^3.2.33 => 3.2.33 
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14 
    gatsby-plugin-sharp: ^2.6.42 => 2.6.42 
    gatsby-source-filesystem: ^2.3.34 => 2.3.34 
    gatsby-transformer-sharp: ^2.5.17 => 2.5.17 
  npmGlobalPackages:
    gatsby-cli: 2.12.111

**Comment by ascorbic** [comment]
This seems to be the same issue as #26563. I'm going to close this, but you might want to add some details there. If it is a different issue please re-open with more details as to why

**Comment by Mehuge** [comment]
> This seems to be the same issue as #26563. I'm going to close this, but you might want to add some details there. If it is a different issue please re-open with more details as to why

I am not sure why that would be considered the same issue. #26563 is an 'only in production' problem. The problem I have logged here is with develop.

**Comment by adamfaryna** [comment]
I stumble upon exactly the same issue. It's happening in dev env not production.
