### ISSUE TITLE
Icons from Material UI Icons or React-Icons not showing up in production

### ISSUE THREAD

**Issue by richardgohcr** [gatsbyjs/gatsby#27570]
I am currently hosting my Gatsby site on Netlify, and I have tried installing and using React-Icons and tried again separately with Material UI Icons, and while they show up perfectly when I run gatsby develop, they don't show up in my production site. 

I cannot reproduce this behaviour, but just wanted to ask if anyone knows if I am missing something?

**Comment by pvdz** [comment]
Can you post some more information? Like your gatsby-config and gatsby-node? It's a little hard to figure out what's wrong without more information :)

**Comment by richardgohcr** [comment]
Hello @pvdz , thank you for your reply! I really appreciate it! Here is my gatsby-config. I am not using gatsby-node. I have tried a several work arounds like installing the gatsby-plugin-material-ui and/or gatsby-plugin-google-fonts, but to no avail. The same issue happened when I tried using React-icons. I have also attached two images, one showing the icons showing up perfectly in my dev environment, and the other of my live website. 

module.exports = {
  siteMetadata: {
    title: `JolynMoh.com`,
    description: `Jolyn Moh's Personal Website`,
    author: `Jolyn Moh`,
  },
  plugins: [
    "gatsby-plugin-sass",
    `gatsby-plugin-material-ui`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: "gatsby-plugin-react-svg",
      options: {
        rule: {
          include: /images/, // See below to configure properly
        },
      },
    },
    {
      resolve: "gatsby-plugin-google-fonts",
      options: {
        fonts: ["material icons", "roboto:300,400,500,700"],
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}

![image](https://user-images.githubusercontent.com/29534052/96597930-ef52e300-1320-11eb-9962-44f558713eec.png)

![image](https://user-images.githubusercontent.com/29534052/96597983-faa60e80-1320-11eb-87a8-6e8f2220d447.png)

**Comment by pvdz** [comment]
(I have taken the liberty of editing your post. I've only added the code block backticks to it for formatting.)

**Comment by pvdz** [comment]
What is the output of your build? 

Side note: Please wrap it in a markdown "code block"

``````
```js
stuff on next line
end on own line
```
``````

**Comment by richardgohcr** [comment]
Here you go. Please ignore the warn "export 'IconExternal' was not found in './index'. That is me trying to add icons manually as a workaround. 

```js
PS C:\Users\Richard\Code\projects\jolynmoh.com> gatsby build
success open and validate gatsby-configs - 0.043s
success load plugins - 1.595s
success onPreInit - 0.021s
success delete html and css files from previous builds - 0.024s
success initialize cache - 0.007s
success copy gatsby files - 0.193s
success onPreBootstrap - 0.014s
success createSchemaCustomization - 0.008s
success source and transform nodes - 0.104s
success building schema - 0.366s
success createPages - 0.002s
success createPagesStatefully - 0.128s
success onPreExtractQueries - 0.002s
success update schema - 0.032s   
warn Using the global `graphql` tag is deprecated, and will not be supported in v3.
Import it instead like:  import { graphql } from 'gatsby' in file:
C:/Users/Richard/Code/projects/jolynmoh.com/src/components/Carousel/index.js       
warn Using the global `graphql` tag is deprecated, and will not be supported in v3.
Import it instead like:  import { graphql } from 'gatsby' in file:
C:/Users/Richard/Code/projects/jolynmoh.com/src/components/ResumeCVBar/index.js
warn Using the global `graphql` tag is deprecated, and will not be supported in v3.
Import it instead like:  import { graphql } from 'gatsby' in file:
C:/Users/Richard/Code/projects/jolynmoh.com/src/components/VerticalTimeline/index.js
success extract queries from components - 0.467s
success write out requires - 0.010s
success write out redirect data - 0.009s
success Build manifest and related icons - 0.148s
success onPostBootstrap - 0.156s
⠀
info bootstrap finished - 8.717s
⠀
warn "export 'IconExternal' was not found in './index'       
success Building production JavaScript and CSS bundles - 43.716s
success Rewriting compilation hashes - 0.007s
success run queries - 43.999s - 12/12 0.27/s
success Building static HTML for pages - 13.358s - 10/10 0.75/s
success onPostBuild - 0.003s
info Done building in 66.514 sec
```

**Comment by richardgohcr** [comment]
The icons do not appear in the compiled html files as well.
I have provided a link to my repo in case you need it: https://github.com/jolyntato/jolynmoh.com

**Comment by pvdz** [comment]
I'll try to have a look tomorrow

**Comment by richardgohcr** [comment]
@pvdz I found the problem, it turns out to be a bug in my CSS that set the opacity of the icons to be 1%. Silly mistake on my part, but thank you for helping me! Will be closing the issue since it's absolutely my fault.

**Comment by pvdz** [comment]
Happy to hear you resolved it :)
