### ISSUE TITLE
Cache Gatsby GraphQL Schema To Reduce Build Time?

### ISSUE THREAD

**Issue by jasonbiondo** [gatsbyjs/gatsby#27596]
Is it possible to just cache the entire schema of all of the data to reduce the time it takes for the future builds on development?  It takes a lot of time to do the node creations and having to restart dev for minutes on end is unproductive for my team.  I'm looking for a solution on this. Does anyone know how this can be done?

**Comment by KyleAMathews** [comment]
Yup! https://www.gatsbyjs.com/plugins/gatsby-plugin-schema-snapshot/

**Comment by jasonbiondo** [comment]
This does indeed grab the schema but it doesn't cache the data.  I don't want to rerun the same plugins over and over.  Is there a way to cache all the data and then load it in?
