### ISSUE TITLE
Client-only routes do not work properly after browser refresh (F5)

### ISSUE THREAD

**Issue by jordan-arteaga** [gatsbyjs/gatsby#27605]
## Description

In production: Client only routes works fine until I refresh a page different from the base one (/), for example if I have two pages, / and /profile, when I try to reload /user seems to be loading / instead, or a mix of both pages

In development: Client only routes works fine even with a page refresh.

The problem is also happening if I use Private routes (following this guide https://www.gatsbyjs.com/docs/client-only-routes-and-user-authentication/)

I saw in a previous bug report the same issue, and the workaround was to disable SSR, but I think is not the ideal solution

`exports.replaceRenderer = ({ replaceBodyHTMLString }) => {
  replaceBodyHTMLString('<div id="___gatsby"></div>');
};`

(added to gatsby-ssr.js).

**Related report:** https://github.com/gatsbyjs/gatsby/issues/15159

### Steps to reproduce

I have client only routes defined in my pages/app.js, you can go to /profile and refresh (F5), the pages seems to be mixed, at first seems to be loading the base page, and after that the result is a mix of both pages. 

Repo: https://github.com/jordan-arteaga/gatsby-client-routes

### Expected result

 When I refresh the browser the profile page loads correctly

### Actual result

The result after refresh the browser is a mix of the base page and the profile page

### Environment

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 81.0.2
  npmPackages:
    gatsby: ^2.24.79 => 2.24.79 
  npmGlobalPackages:
    gatsby-cli: 2.12.111

**Comment by ascorbic** [comment]
Hi @jordan-arteaga . How have you got the routes set-up on the server? Refreshing doesn't work unless your server is setup to rewrite the URLs to the base path.

**Comment by jordan-arteaga** [comment]
@ascorbic Following the client only routes guide, I did this step https://www.gatsbyjs.com/docs/client-only-routes-and-user-authentication/#configuring-pages-with-matchpath

And according to the guide it's an alternative to configure the routes on the server, or I'm wrong whit that?

> If you are hosting on your own server, you can opt to configure the server to handle client-only routes instead of using the matchPath method explained above.

https://www.gatsbyjs.com/docs/client-only-routes-and-user-authentication/#configuring-and-handling-client-only-routes-on-a-server
