### ISSUE TITLE
Update analytics doc to use official Gatsby gtag plugin

### ISSUE THREAD

**Issue by meganesu** [gatsbyjs/gatsby#27623]
## Summary

The existing [doc about adding Google analytics](https://www.gatsbyjs.com/docs/adding-analytics/) recommends using the `gatsby-plugin-gtag` plugin. As was pointed out after #27081 was merged, Gatsby actually maintains an official plugin with the same functionality, [`gatsby-plugin-google-gtag`](https://www.gatsbyjs.com/plugins/gatsby-plugin-google-gtag/).
 
The Adding Analytics doc should be updated to use this official plugin instead.

## Steps to resolve this issue

- [ ] Update the [Google analytics docs](https://www.gatsbyjs.com/docs/adding-analytics/) to use `gatsby-plugin-google-gtag` instead of `gatsby-plugin-gtag`.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #27623" in the pull request description

**Comment by im-adithya** [comment]
I am interested @meganesu. Can you assign this to me? 😄

**Comment by uniyalabhishek** [comment]
@meganesu Updated the analytics doc to use official Gatsby gtag plugin. Please check PR #27747
