### ISSUE TITLE
bug: Upgrading @emotion/core to v10.0.35 from v10.0.28 fails static build

### ISSUE THREAD

**Issue by und3fined-v01d** [gatsbyjs/gatsby#27635]
## Description

I was testing out upgrading the npm packages in the package.json to the latest versions for the now deprecated `gatsby/www` and found the static build to fail. I traced the error to occur only when `@emotion/core` is upgraded to v10.0.35

The build seems to run fine when I use `gatsby develop` but fails only when running `gatsby build`

### Steps to reproduce

1. Run `yarn upgrade @emotion/code@10.0.35`
2. Run `gatsby develop` and see the code run fine
3. Now run `gatsby build` and this is the error thrown:

```

Building static HTML failed for path "/offline-plugin-app-shell-fallback/"

See our docs page for more info on this error: https://gatsby.dev/debug-html





  WebpackError: TypeError: Cannot read property 'code' of undefined
  
  - build-html.js:107 doBuildPages
    [www]/[gatsby]/dist/commands/build-html.js:107:24
  
  - build-html.js:121 async buildHTML
    [www]/[gatsby]/dist/commands/build-html.js:121:3
  
  - build.js:206 async build
    [www]/[gatsby]/dist/commands/build.js:206:5

```

**Comment by LekoArts** [comment]
Hi, we're no longer using `www` so there's no need to update packages there :)
