### ISSUE TITLE
Cannot query field "altText" on type "ContentfulImageContentfulImageSetUnion".

### ISSUE THREAD

**Issue by hema1592** [gatsbyjs/gatsby#27660]
We are getting the below error while running local dev command after updating the gatsby and gatsby-contentful to the latest version.
Gatsby (2.23.0)
gatsby-source-contentfu(2.3.15). We were facing high vulnerabilities(~1k) and therefore thought with npm audit fix will reduce the vulnerabilities.However, it reduced the vulnerabilities(~5) but the site is not running in local.

"Cannot   query field "altText" on type   "ContentfulImageContentfulImageSetUnion".

Snippet of package.json:
   "dependencies": {
            "autoprefixer": "^9.1.1",
            "axios": "^0.19.0",
            "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
            "circular-json": "0.5.5",
            "classnames": "^2.2.6",
            "develop": "^1.0.0",
            "email-validator": "^2.0.4",
            "file-saver": "1.3.8",
            "fs": "0.0.1-security",
            "fs-extra": "7.0.0",
            "gatsby": "^2.12.0",
            "gatsby-link": "^2.0.1",
            "gatsby-plugin-canonical-urls": "^2.0.10",
            "gatsby-plugin-google-analytics": "^2.0.15",
            "gatsby-plugin-google-tagmanager": "^2.0.9",
            "gatsby-plugin-manifest": "^2.1.1",
            "gatsby-plugin-offline": "^2.2.9",
            "gatsby-plugin-react-helmet": "^3.0.11",
            "gatsby-plugin-remove-serviceworker": "^1.0.0",
            "gatsby-plugin-robots-txt": "^1.4.0",
            "gatsby-plugin-sharp": "^2.0.37",
            "gatsby-plugin-sitemap": "^2.0.11",
            "gatsby-plugin-webpack-size": "0.0.3",
            "gatsby-remark-responsive-iframe": "^2.1.1",
            "gatsby-remark-responsive-image": "^1.0.0-alpha13-alpha.435e0178",
            "gatsby-source-contentful": "^2.0.56",
            "gatsby-transformer-remark": "2.5.0",
            "gatsby-transformer-sharp": "^2.2.0",
            "handlebars": "^4.1.2",
            "intl": "1.2.5",
            "json-query": "2.2.2",
            "jsonwebtoken": "8.3.0",
            "lodash": "^4.17.11",
            "lodash.debounce": "4.0.8",
            "mobx": "4.3.0",
            "mobx-react": "5.1.2",
            "picturefill": "3.0.2",
            "postcss-import": "^12.0.0",
            "prop-types": "^15.7.2",
            "qs-stringify": "1.1.0",
            "query-string": "6.1.0",
            "react": "^16.4.2",
            "react-autosuggest": "9.3.4",
            "react-cookie-consent": "^2.2.2",
            "react-dom": "^16.4.2",
            "react-helmet": "5.2.0",
            "react-idle-timer": "4.0.8",
            "react-image-magnify": "2.7.0",
            "react-in-viewport": "0.0.35",
            "react-intl": "2.4.0",
            "react-lazyload": "^2.6.1",
            "react-recaptcha-google": "^1.1.1",
            "react-slick": "^0.23.1",
            "react-youtube": "^7.9.0",
            "slick-carousel": "^1.8.1",
            "smoothscroll-polyfill": "^0.4.4",
            "swiftype": "^0.4.0",
            "tailwindcss-object-fit": "^1.0.1",
            "uglifyjs-webpack-plugin": "^2.1.3",
            "validatorjs": "3.14.2"
      },
      "devDependencies": {
            "@babel/plugin-proposal-decorators": "^7.3.0",
            "babel-eslint": "^8.2.6",
            "babel-jest": "^24.8.0",
            "babel-preset-gatsby": "^0.1.11",
            "babel-preset-react-app": "3.1.2",
            "enzyme": "^3.9.0",
            "enzyme-adapter-react-15": "1.0.6",
            "enzyme-to-json": "3.3.4",
            "eslint": "^5.15.1",
            "eslint-config-airbnb": "^17.1.0",
            "eslint-config-prettier": "3.0.1",
            "eslint-config-standard": "^12.0.0",
            "eslint-loader": "^2.1.0",
            "eslint-plugin-import": "^2.16.0",
            "eslint-plugin-jsx-a11y": "^6.1.1",
            "eslint-plugin-node": "^8.0.1",
            "eslint-plugin-prettier": "2.6.2",
            "eslint-plugin-promise": "^4.0.1",
            "eslint-plugin-react": "^7.11.1",
            "eslint-plugin-standard": "^4.0.0",
            "gatsby-plugin-eslint": "^2.0.4",
            "gatsby-plugin-purgecss": "^3.1.0",
            "gatsby-plugin-remove-trailing-slashes": "^2.0.9",
            "jest": "^24.8.0",
            "postcss": "^7.0.2",
            "postcss-cli": "^6.1.3",
            "prettier": "1.14.2",
            "purgecss": "1.0.1",
            "react-test-renderer": "16.4.2",
            "stylelint": "^10.1.0",
            "stylelint-config-recommended": "^2.2.0",
            "stylelint-config-styled-components": "^0.1.1",
            "stylelint-processor-styled-components": "^1.8.0",
            "tailwindcss": "^0.6.5",
            "terser-webpack-plugin": "^1.2.3",
            "xml2js": "^0.4.19"

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ascorbic** [comment]
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!
