### ISSUE TITLE
[MDX2] "gatsby-plugin-mdx" threw an error when URLs are declared with "<http://www.example.com>"

### ISSUE THREAD

**Issue by jonathanlinat** [gatsbyjs/gatsby#27687]
### Your environment

- **OS**: Ubuntu 20.04 LTS
- **Packages**: 
  - "gatsby": "2.24.88"
  - "gatsby-plugin-mdx": "1.2.51"
  - "@mdx-js/mdx": "2.0.0-next.8"
  - "@mdx-js/react": "2.0.0-next.8"
- **Env**: Node v12.19.0 / NPM v6.14.8

### Actual behaviour

When I declare URLs as `<http://www.example.com>`, then `gatsby-plugin-mdx` throws an error while running the `onCreateNode` lifecycle.

```
error "gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:

Unexpected character `/` (U+002F) before local name, expected a character that can start a name, such as a letter, `$`, or `_`
```

![image](https://user-images.githubusercontent.com/14064112/97341803-46e2d880-1864-11eb-92c4-c2b443d95fff.png)

![image](https://user-images.githubusercontent.com/14064112/97341676-2581ec80-1864-11eb-941c-83459fa760f6.png)

**Comment by LekoArts** [comment]
To keep things organized I'll close this in favor of an umbrella issue. Please repost your findings here: https://github.com/gatsbyjs/gatsby/issues/25068

Thanks!

**Comment by jonathanlinat** [comment]
> To keep things organized I'll close this in favor of an umbrella issue. Please repost your findings here: #25068
> 
> Thanks!

Hey @LekoArts . I'm not sure how to repost my findings. Do I have to comment #25068 with my findings?
