### ISSUE TITLE
React is not defined with React v17

### ISSUE THREAD

**Issue by lnikell** [gatsbyjs/gatsby#27689]
## Description

Based on the React v17 documentation page Gatsby has support of the new JSX transform. New JSX transform however does not require to have `import React` at the top of each file. [How to upgrade to new jsx transform.](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#how-to-upgrade-to-the-new-jsx-transform)
After the upgrade to React v17 and removing React import from a file, I'm getting the error "React is not defined".

### Steps to reproduce

1. Run Gatsby project with the latest gatsby version and React v17
2. Delete import `import React from 'react';` from the file where you use JSX

### Expected result

Everything should work fine, based on the [documentation](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#gatsby). 

### Actual result
![image](https://user-images.githubusercontent.com/2697570/97354922-70b4f300-1896-11eb-8174-70a95ed20a97.png)

### Environment

```
  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 76.0.1
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.24.89 => 2.24.89
    gatsby-alias-imports: ^1.0.6 => 1.0.6
    gatsby-image: ^2.4.21 => 2.4.21
    gatsby-plugin-manifest: ^2.4.36 => 2.4.36
    gatsby-plugin-offline: ^3.2.37 => 3.2.37
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14
    gatsby-plugin-sass: ^2.3.21 => 2.3.21
    gatsby-plugin-sharp: ^2.6.43 => 2.6.43
    gatsby-plugin-svgr-svgo: ^1.0.12 => 1.0.12
    gatsby-source-filesystem: ^2.3.37 => 2.3.37
    gatsby-transformer-sharp: ^2.5.20 => 2.5.20
  npmGlobalPackages:
    gatsby-cli: 2.8.23
```

**Comment by KyleAMathews** [comment]
We disabled this a few days ago as there's tools in the ecosystem that haven't adjusted yet https://github.com/gatsbyjs/gatsby/pull/27615
