### ISSUE TITLE
Page refresh when scrolling

### ISSUE THREAD

**Issue by arm021** [gatsbyjs/gatsby#27712]
### Description

Every time I scroll on any page when I hit about 50%-70% of the page it refreshes. Please help I am just new to gatsby. Thank you.

### Steps to reproduce

1. gatsby new gatsby-project https://github.com/GatsbyStorefront/gatsby-starter-storefront-shopify
2. cd gatsby-project
3. configure shopName and accessToken in gatsby-config.js file
4. gatsby-develop
5. access localhost:8000

### Expected result

Will be able to scroll the page til bottom without refreshing.

### Actual result

Page refresh when scrolling about 50%-70% of the page

### Environment

System:
    OS: Windows 10 10.0.19041
    CPU: (2) x64 Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.3
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Spartan (44.19041.423.0)
  npmPackages:
    gatsby: ^2.13.38 => 2.24.91
  npmGlobalPackages:
    gatsby-cli: 2.12.113

**Comment by LekoArts** [comment]
Thank you for opening this!

I'm not seeing this behavior in a default starter of ours so please open an issue with the repository of the starter!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
