### ISSUE TITLE
CSS additionalProperties issue

### ISSUE THREAD

**Issue by VitaliiZhukov** [gatsbyjs/gatsby#2772]
Hi there!
Recently I started to get error running gatsby develop.
```
info bootstrap finished - 4.564 s

[ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: '_PARENT' },
    message: 'should NOT have additional properties' } ]
error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  Error: Module build failed: Error: /Users/vitaliizhukov/work/sh-site/website/.cache/develop-stati  c-entry.js: Invalid configuration
  
  - index.js:204 PluginPass.Program
    [website]/[babel-plugin-react-css-modules]/dist/index.js:204:17 
```
Running 'gatsby build' leads to next error:
```
info bootstrap finished - 4.339 s

⡀ Building CSS[ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: '_PARENT' },
    message: 'should NOT have additional properties' } ]
success Building CSS — 1.661 s
⠄ Building production JavaScript bundles[ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: '_PARENT' },
    message: 'should NOT have additional properties' } ]
success Building production JavaScript bundles — 0.344 s
⠁ [ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: '_PARENT' },
    message: 'should NOT have additional properties' } ]

error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND


  Error: Module build failed: Error: /Users/vitaliizhukov/work/sh-site/website/.cache/static-entry.  js: Invalid configuration
  
  - index.js:204 PluginPass.Program
    [website]/[babel-plugin-react-css-modules]/dist/index.js:204:17
```

I found out that last gatsby version that builds website successfully is 1.9.81. (But for that version I had another issue with multiple graphql entries)
What do I miss here?
Thanks.

**Comment by KyleAMathews** [comment]
No idea what's going on.

We did recently make a change to add `_PARENT` to nodes but that's not anything that should show up in your site's code.

Easiest way to move forward on this is perhaps if you can isolate exactly what's causing the trouble. So copy your site and start deleting things until you're left with just what's causing the trouble.

**Comment by pieh** [comment]
Ok, so problem is that `babel-plugin-react-css-modules` (used by `gatsby-plugin-react-css-modules`) validates passed config and errors out on fields it does not expect (`_PARENT`) and gatsby mutates plugin configuration when adding `_PARENT` for graphql ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js#L66 here gatsby does shallow copy of plugin data, so plugin configuration that is mutated is same object that is passed later).

My solution is like that https://github.com/pieh/gatsby/commit/f4e52bda36ca054858407fb2eecdb2736931168e but I don't have properly setup gatsby to build it from source and test it (just did same "fix" in built gatsby in my local node_modules which fixed it for me locally - but obviously can't use it on netlify :/)

**Comment by VitaliiZhukov** [comment]
worked, thanks!
