### ISSUE TITLE
Error in gatsby-source-drupal when using fastbuilds 'Plugins creating nodes can not set data on the reserved field "fields"'

### ISSUE THREAD

**Issue by kitti-radovics** [gatsbyjs/gatsby#27733]
## Description

I'm using gatsby-source-drupal with fastbuilds and the following error is given when the refresh is triggered:
```
  Error: Plugins creating nodes can not set data on the reserved field "fields"
        as this is reserved for plugins which wish to extend your nodes.
        If your plugin didn't add "fields" you're probably seeing this
        error because you're reusing an old node object.
        Node:
        {
      "id": "89a071af-301b-5a2d-b713-cf648cf9d67a",
      "drupal_id": "62481b86-833f-4d81-93ff-861f5e37a964",
      "parent": null,
      "children": [],
      "display_name": "admin",
      "drupal_internal__uid": 1,
      "langcode": "en",
      "name": "admin",
      "created": "2020-06-28T11:49:43+00:00",
      "changed": "2020-10-26T09:55:22+00:00",

      ...

      "fields": {
          "slug": "/user/1"
      },
      "__gatsby_resolved": {
          "path": {}
      }
  }
```

This only happens when I select Redirect under "Entity types to send to Gatsby Preview and Build Server" on Gatsby Integration Settings form in Drupal.

I'm also using `createRedirect()` in Gatsby to have client side redirect from Drupal Redirect entities, but the error still happens when I comment out `createRedirect` calls in `createPages`.

### Steps to reproduce

- Select "Redirect" and "Content" under "Entity types to send to Gatsby Preview and Build Server" on Gatsby Integration Settings form in Drupal
- Run `gatsby develop`
- Update a node in Drupal changing its title (pathauto configured for node type) to trigger creation of Redirect entity

### Expected result
- Refresh endpoint is called by Drupal
- `gatsby develop` continues to run and successfully fetches changes
- Node title changes on UI

### Actual result

Refresh endpoint gets called and Gatsby starts to fetch changed data from Drupal, but the process fails with an error message (see description).

If I add the following lines to `handleWebhookUpdate` in `utils.js` (line 171) then the error goes away. 
```js
for (const node of nodesToUpdate) {
    if (node.internal.owner) {
      delete node.internal.owner;
    }

    /// These 3 lines eliminate the error.
    if (node.fields) {
      delete node.fields;
    }

    node.internal.contentDigest = createContentDigest(node);
    createNode(node);
    reporter.log(`Updated node: ${node.id}`);
  }
```
I assume that the problem is that nodes for referenced entities are not created from scratch with `nodeFromData` but they are created based on the old node data and that's why `fields` is explicitly set on the node (the `slug` field in the error was created in my `gatsby-node.js`).

### Environment
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 10.22.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/<someuser>/.windows-build-tools/python27/python
  Browsers:
    Chrome: 86.0.4240.111
  npmPackages:
    gatsby: ^2.24.29 => 2.24.91
    gatsby-background-image: ^1.1.2 => 1.1.2
    gatsby-cli: ^2.12.74 => 2.12.113
    gatsby-image: ^2.0.25 => 2.4.21
    gatsby-plugin-client-side-redirect: ^1.1.0 => 1.1.0
    gatsby-plugin-feed: ^2.5.12 => 2.5.20
    gatsby-plugin-gdpr-tracking: ^1.1.2 => 1.2.2
    gatsby-plugin-manifest: ^2.4.1 => 2.4.37
    gatsby-plugin-material-ui: ^2.1.9 => 2.1.10
    gatsby-plugin-react-helmet: ^3.2.1 => 3.3.14
    gatsby-plugin-sass: ^2.3.12 => 2.3.22
    gatsby-plugin-schema-snapshot: ^1.0.0 => 1.0.0
    gatsby-plugin-sharp: ^2.6.0 => 2.6.43
    gatsby-source-drupal: ^3.5.15 => 3.5.40
    gatsby-source-filesystem: ^2.3.27 => 2.3.37
    gatsby-transformer-json: ^2.1.7 => 2.4.15
    gatsby-transformer-remark: ^2.1.20 => 2.8.47
    gatsby-transformer-remote-filesystem: ^1.0.0 => 1.0.0
    gatsby-transformer-sharp: ^2.5.0 => 2.5.20
    gatsby-transformer-yaml: ^2.1.7 => 2.4.15
  npmGlobalPackages:
    gatsby-cli: 2.12.113
```

**Comment by Auspicus** [comment]
@kitti-radovics @smthomas I have a PR to address this.

**Comment by KyleAMathews** [comment]
PR merged 👍
