### ISSUE TITLE
Gatsby Plugin Manifest lacking clarity -> causing error

### ISSUE THREAD

**Issue by qumberhussain** [gatsbyjs/gatsby#27751]
## Summary

The [gatsby-manifest-plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest) documentation for generating icons is unclear. 

```
        icon: `src/images/favion.svg`, // This path is relative to the root of the site.
        icons: [
          {
            src: `src/images/favicon--short.svg`,
            sizes: `192x192`,
            type: `image/png`,
          },
        ],
```

I have added the above code to the `gatsby-config.js`. However when running `gatsby develop` or `gatsby build` the terminal throws the following error.

```
error "gatsby-plugin-manifest" threw an error while running the onPostBootstrap lifecycle:

ENOENT: no such file or directory, mkdir 'public/src/images'

  303 | 
  304 |                 if (!exists) {
> 305 |                   fs.mkdirSync(iconPath);
      |                      ^
  306 |                 }
  307 | 
  308 |                 paths[iconPath] = true;


  Error: ENOENT: no such file or directory, mkdir 'public/src/images'
``` 

The documentation has the favicons in a folder called favicons. The error implies these icon files should be inside the public folder. But this seems incorrect.

Any advice would be helpful, thankyou.

**Comment by LekoArts** [comment]
The `icon` option should point to a file relative to the root of your site inside the `src` folder.

The icons defined in the `icons` option however reference icons that will eventually be in the `public` folder. One puts these files there by placing them inside the [static](https://www.gatsbyjs.com/docs/static-folder/) folder.

Example:
1) https://github.com/LekoArts/gatsby-starter-minimal-blog/blob/master/gatsby-config.js#L55-L66
2) https://github.com/LekoArts/gatsby-starter-minimal-blog/tree/master/static

The documentation/README at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-manifest/README.md should include a note that `icons` is referring to the final URL and thus images need to be added to `static`.

**Comment by franjorub** [comment]
I was thinking in include a note below the config but it is already described at Manual mode config

> you are responsible for defining the entire web app manifest and providing the defined icons in the static folder. 

so I just put some comments next to the src path like with the icon path

https://github.com/gatsbyjs/gatsby/pull/27892

**Comment by Anmol368** [comment]
icons: [
          {
            src: `/android-chrome-192x192.png`,
            sizes: `192x192`,
            type: `image/png`,
          },
          {
            src: `/android-chrome-512x512.png`,
            sizes: `512x512`,
            type: `image/png`,
          },
        ],
      },
    },

**Comment by moonmeister** [comment]
@Anmol368 did yo I have a question/issue?

**Comment by sijin-raj** [comment]
icons: [
          {
            src: `src/images/favion.svg`,
            sizes: `192x192`,
            type: `image/png`,
          },
          
        ],

**Comment by sijin-raj** [comment]
Hi,
  This is Sijin can i get few stickers from gatsby . please reply for this
mail

**Comment by sijin-raj** [comment]
Done.

**Comment by LekoArts** [comment]
See https://github.com/gatsbyjs/gatsby/pull/27892#issuecomment-736697786
