### ISSUE TITLE
Feature: Query multiple node types simultaneously

### ISSUE THREAD

**Issue by uttrasey** [gatsbyjs/gatsby#2775]
I'm using the `gatsby-source-contentful` and would like, in a single query, to be able to `order` and `paginate` several content types simultaneously. 

The use case for this is a "latest content feed" which co-mingles 3 different content types chronologically based on a `publishDate` field which I've added to each of the CMS content models.

I've been reading about GraphQL Unions and Interfaces as a means to dealing with different content types collectively.

I'm keen to know if this is achievable and what the best approach is.

**Comment by KyleAMathews** [comment]
This seems like a really valuable area to explore. There's definitely lots of times you want to query multiple types at once like your "content feed" use case.

A few ways we could handle this:
 
* A source plugin creates union/interface types as it makes sense for their data
* A site builder can manually group types into a new union type
* We expose a new hook to do this programatically
* Automatically infer interfaces based on common fields — e.g. all Contentful node types could share a number of fields e.g. your `publishDate` — it'd be fairly straightforward to infer this and generate a new interface type based on the common fields.

People have any other ideas?

**Comment by uttrasey** [comment]
I think automatically inferring might be tricky where as allowing programatic union definition would allow for more control / use cases. For example not everything with a publishDate should appear in my "content feed". 

Being relatively new to gatsby I don't have a strong feeling on how to expose this functionality `hook` vs `plugin`. Thoughts?

**Comment by KyleAMathews** [comment]
>I think automatically inferring might be tricky where as allowing programatic union definition would allow for more control / use cases. For example not everything with a publishDate should appear in my "content feed"

👍  also someone could easily write a plugin to do the automatic inference. Always better to start low-level and manual in core and then experiment with higher-level primitives in userland.

Plugins use hooks so both :-) Probably the best way to land this is to add a PR with the new API hook along with an example site demoing its use and then if there's a really solid plugin that can automate some of this, add that as well.

This would be really exciting functionality to add!

**Comment by uttrasey** [comment]
Sounds good. I'm going to try and get something raised early next week 👌

**Comment by uttrasey** [comment]
Raised something super rough to get feedback https://github.com/gatsbyjs/gatsby/pull/2990

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
