### ISSUE TITLE
gatsby-source-shopify variant image not linked to product variant

### ISSUE THREAD

**Issue by axelra82** [gatsbyjs/gatsby#27788]
## Description

[gatsby-source-shopify](https://www.gatsbyjs.com/packages/gatsby-source-shopify/). The variant images, while they are being sourced, have no way of linking with variant product in GraphQL query.

### Steps to reproduce

Latest GatsbyJS and gatsby-source-shopify, in http://localhost:8000/___graphql

```query MyQuery {
  allShopifyProduct {
    edges {
      node {
        variants {
          image {
            originalSrc
          }
        }
      }
    }
  }
}
```

### Expected result

Expected above query to return the variant specific image.

### Actual result

Gives image of main product, not variant. I can't see any way of getting variant specific image linked to variant of a product. **Maybe I've just completely missed something here**? 🤷‍♂️ 

The variant images are in local cache and they can be found in GraphQL

```query MyQuery {
  allShopifyProduct {
    edges {
      node {
        images {
          originalSrc
        }
      }
    }
  }
}
```

This gives us an array of images. There is however, **from what I can tell**, no way of linking these images with their corresponding variants. That should happen in the sourcing process, where the variant image should be linked with the variant.

### Environment

System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 82.0.2
    Safari: 14.0
  npmPackages:
    gatsby: ^2.25.0 => 2.25.0 
    gatsby-image: ^2.4.21 => 2.4.21 
    gatsby-plugin-sharp: ^2.7.0 => 2.7.0 
    gatsby-source-filesystem: ^2.4.0 => 2.4.0 
    gatsby-source-shopify: ^3.3.0 => 3.3.0 
    gatsby-transformer-remark: ^2.9.0 => 2.9.0 
    gatsby-transformer-sharp: ^2.5.21 => 2.5.21 
  npmGlobalPackages:
    gatsby-cli: 2.12.113

**Comment by axelra82** [comment]
# ISSUE RESOLVED
Something bugged without us noticing while saving in shopify, images were just not properly linked to variants in shopify.
No bug. Everything works as expected.

**Sorry for the inconvenience!**

**Comment by Luca8991** [comment]
I can't find any field inside `shopifyProduct` GraphQL query that links an image to its variant. Where is the problem?

**Comment by jacksellwood** [comment]
Hi there, we're currently testing the next major version of gatsby-source-shopify. Learn more about upgrading: https://www.notion.so/gatsbyjs/Instructions-for-upgrading-to-Shopify-7-e5cb1068b35b4de7ba7e9ffb160aad26
