### ISSUE TITLE
Feature: Tag Plugin

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#2778]
I know there is a fair amount of discussion in the issues about tagging, but there doesn't seem to be a firm resolution. Would you be interested in a PR for a plugin adding tagging support? Something simple that would pull tags (and/or) keywords from markdown and yaml front matter, and generate a series of pages containing links to the pages that originated the tags. The config could offer:
- declaration of tags
- supported filetypes (markdown, yaml)
- regex for files to pull tags from
- path to template for tags page.
- path to template component for tag pages.

**Comment by KyleAMathews** [comment]
Yeah! Sounds awesome! Something straightforward to use and well documented/tested would be a huge boon to the community.

**Comment by Undistraction** [comment]
OK. I'll put something together.

**Comment by Undistraction** [comment]
@KyleAMathews Any thoughts on the naming of the plugin?

- gatsby-plugin-tags

 Is this OK or do you want something more specific in case of different tag approaches?

- gatsby-plugin-front-matter-tags

**Comment by KyleAMathews** [comment]
Either could work depending on focused you want the library to be.

You could model it after [gatsby-paginate](https://github.com/pixelstew/gatsby-paginate) where it's not a plugin but instead a pure function that you pass data into and which creates the pages for you.

**Comment by Undistraction** [comment]
I like that idea a lot. Do you want it within this repo or as a separate project?

**Comment by KyleAMathews** [comment]
Happy to have it here or elsewhere. Here you get more help maintaining it but no one will know you wrote it.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
