### ISSUE TITLE
bug(gatsby-plugin-sass): plugin option issues

### ISSUE THREAD

**Issue by cpboyd** [gatsbyjs/gatsby#27796]
## Description

Per https://sass-lang.com/documentation/js-api#outputstyle:
While `nested` is the default for Node Sass, it isn't supported by Dart Sass.

Similarly, `webpackImporter` is no longer allowed. This is necessary for any Sass files using `@forward` syntax (e.g. Google's Material design): https://github.com/webpack-contrib/sass-loader/issues/804

This breaking change was introduced in #27437.

### Steps to reproduce

Setup with Dart Sass as described on https://www.gatsbyjs.com/plugins/gatsby-plugin-sass/

### Expected result

This should work, as it used to.

### Actual result

```
Invalid argument(s): Unsupported output style "nested".
```

### Environment

```
  System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    npm: 7.0.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.111
    Edge: 86.0.622.58
    Firefox: 80.0.1
    Safari: 14.0.1
  npmPackages:
    gatsby-theme-youtube: ^1.0.0 => 1.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.104
```

**Comment by pravinthan** [comment]
The `cssLoader` option validation is missing too, causing some Gatsby projects to break.
