### ISSUE TITLE
Upgrading Gatsby gives Unexpected end of JSON input while parsing near '...-tape":"^1.0.0","cont'

### ISSUE THREAD

**Issue by w3bdesign** [gatsbyjs/gatsby#27802]
## Description

When trying to upgrade Gatsby to 2.25.0 or 2.25.1 I get a 

`npm ERR! Unexpected end of JSON input while parsing near '...-tape":"^1.0.0","cont'` 

error message in the terminal.`

### Steps to reproduce

See https://github.com/w3bdesign/dfweb

1. Upgrade package in package.json
2. Run `npm install`

### Expected result

I should be able to upgrade without any issues.

### Actual result

I see the error.

### Environment

System:
    OS: Windows 7 6.1.7601
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 12.18.4 - F:\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn x\bin\yarn.CMD
    npm: 6.14.8 - F:\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.111
  npmPackages:
    gatsby: ^2.24.89 => 2.24.89
    gatsby-cypress: ^0.4.12 => 0.4.12
    gatsby-plugin-manifest: ^2.5.1 => 2.5.1
    gatsby-plugin-netlify: ^2.4.0 => 2.4.0
    gatsby-plugin-percy: ^0.1.4 => 0.1.4
    gatsby-plugin-postcss: ^3.0.4 => 3.0.4
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-robots-txt: ^1.5.3 => 1.5.3
    gatsby-plugin-sitemap: ^2.5.0 => 2.5.0
    gatsby-plugin-styled-components: ^3.3.14 => 3.3.14
    gatsby-source-graphql: ^2.7.6 => 2.7.6
  npmGlobalPackages:
    gatsby-cli: 2.12.113

**Comment by pvdz** [comment]
I cloned your repo and installed, worked fine.

Then I bumped to `gatsby@2.25.1` and ran `yarn`. Worked fine.

I removed `node_modules` and ran `npm install`. Worked fine.

I can't repro it here. Can you try to remove the `node_modules` folder and try again?

**Comment by w3bdesign** [comment]
@pvdz 

After some trial and error I managed to update and install without errors.

Here are the steps I took:

1. Deleted the repository from my local PC
2. Ran `npm cache clean --force`
3. Cloned the repository back to my PC
4. Deleted package-lock.json
5. Updated package.json with the latest Gatsby version
6. Ran npm install
