### ISSUE TITLE
Error in your GraphQL query, unsupported image format -> tracedSVG

### ISSUE THREAD

**Issue by Ben1980** [gatsbyjs/gatsby#27806]
## Description

Deploying gatsby with contentful on netlify/render.com is causing an error
```
error There was an error in your GraphQL query:
10:41:00 AM: Input file contains unsupported image format
10:41:00 AM:    1 | fragment GatsbyContentfulFluid_tracedSVG on ContentfulFluid {
10:41:00 AM: >  2 |   tracedSVG
10:41:00 AM:      |   ^
```
This is happening after updating packages with npm update.
Also happens after manualy upgrading to gatsby-plugin-sharp 2.7

Allready mentioned at [8301](https://github.com/gatsbyjs/gatsby/issues/8301) but still a problem
My project which has this issue can be found at [thoughts-on-coding](https://github.com/Ben1980/thoughts-on-coding)

### Steps to reproduce
1. Create a gatsby contentful project via gatsbycloud
2. deploy it on netlify or render.com -> works fine
3. call npm update on the project -> netlify/render.com can't deploy it anymore because of error mentioned above
4. With gatsby-plugin-sharp 2.7 it can be also reproduced via npm run dev

**Comment by wardpeet** [comment]
Do you get it locally? Or only CI?

**Comment by Ben1980** [comment]
only in production on netlify

**Comment by Ben1980** [comment]
Any news? Can I somehow help?

**Comment by Ben1980** [comment]
This is still a several issue, travesvg can't be Süd this was, how can i help?
