### ISSUE TITLE
gatsby-plugin-offline breaks external download links for large files in Firefox

### ISSUE THREAD

**Issue by slawo-ch** [gatsbyjs/gatsby#27827]
## Description

This issue appears when you have links in your content like this: `<a href="https://someexternal.com/some_big_file.zip">download</a>`

If you left-click the download link, and the file does not finish downloading within ~30 secs, Firefox will close the connection and abort all current downloads as failed. Every time. I've not been able to reproduce this in Chrome. Firefox only. But realiably cross-platform: happens on macOs, Linux, and Windows.

No errors show in the firefox console.

If you right-click 'Save as...' the same download links, the service worker is not involved, and the downloads finish reliably. Every time.

### Steps to reproduce

To reproduce, it's useful to have multiple such links to various big files > 500MB-ish, and left-click download 3-5 of them. It ensures the connection is saturated and the timeout triggers reliably while some downloads are still in progress. They all fail as a group at once every time the timeout triggers.

Somehow the service worker is tasked with downloading the files? I have no experience with the how and why's, I've come across this bug report that deals with a similar issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1288915 it helped me isolate the cause of failing downloads on my site. I had to remove gatsby-plugin-offline in order to offer reliable download links on my website.

### Expected result

Downloads should not abort and finish reliably.

### Actual result

Downloads abort after a timeout.

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 3.8.1 - /Users/slawo/.pyenv/shims/python
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 82.0.2
    Safari: 14.0
  npmPackages:
    gatsby: ^2.25.1 => 2.25.1 
    gatsby-alias-imports: ^1.0.6 => 1.0.6 
    gatsby-plugin-google-analytics: 2.4.0 => 2.4.0 
    gatsby-plugin-manifest: ^2.5.1 => 2.5.1 
    gatsby-plugin-mdx: ^1.3.0 => 1.3.0 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-postcss: ^3.0.4 => 3.0.4 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sharp: ^2.7.0 => 2.7.0 
    gatsby-plugin-tailwindcss: ^1.0.3 => 1.0.3 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.4.0 => 2.4.0 
    gatsby-transformer-remark: ^2.9.1 => 2.9.1 
  npmGlobalPackages:
    gatsby-cli: 2.12.115

**Comment by ascorbic** [comment]
Hi. That's an odd one. I'd recommend using [custom Workbox options](https://www.gatsbyjs.com/plugins/gatsby-plugin-offline/#overriding-workbox-configuration), and add the downloads to the denyList. You might have to play around a bit with the options, as I can't try them out without a reproduction. Let me know if that works, and if it doesn't please share a minimal reproduction. Thanks.

**Comment by slawo-ch** [comment]
I tried to produce a minimal reproduction and got nowhere on a clean slate. 

The error seems related to what Firefox does specifically when other requests are in play, such as loading assets from other domains like, css, js, iframes, etc. for chat widgets, mailing list providers and the like. In my scenario there are CORS requests and websockets connections to external domains involved.

I suppose since reproduction is difficult and it's not clear who's 'fault' it is, this issue should be closed, but hopefully remain searchable for posterity in case someone else runs into a similar issue.

**Comment by ascorbic** [comment]
Thanks for the update. I'll close it and it will remain searchable. You could also open a discussion if you need more help, as maybe somebody else will have an idea.
