### ISSUE TITLE
gatsby-plugin-google-analytics: "cookieFlags" is not allowed  - Invalid plugin options

### ISSUE THREAD

**Issue by mohsenkhanpour** [gatsbyjs/gatsby#27833]
## Description

After recent update which enabled plugin option validation, `gatsby-plugin-google-analytics` throws with the following:
```
error Invalid plugin options for "gatsby-plugin-google-analytics":

- "cookieFlags" is not allowed
not finished load plugins - 9.797s
```

Although [gatsby-plugin-google-analytics](https://www.npmjs.com/package/gatsby-plugin-google-analytics) list `cookieFlags` as an option, it is not allowed after the latest update.

### Steps to reproduce

1. Update `gatsby` and `gatsby-plugin-google-analytics`
2. Add `cookieFlags` option:
```
		{
			resolve: `gatsby-plugin-google-analytics`,
			options: {
				// replace "UA-XXXXXXXXX-X" with your own Tracking ID
				trackingId: 'UA-XXXXXXXXX-X',
				cookieFlags: 'Secure;SameSite=None',
			},
		},
```

### Expected result

It should be accepted as a valid plugin option.

### Actual result

It is not allowed and throws build process.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```
npmPackages:
    gatsby: 2.25.2 => 2.25.2 
    gatsby-plugin-google-analytics: ^2.4.0 => 2.4.0 
```

**Comment by mohsenkhanpour** [comment]
@mxstbr Thanks for updating the schema, I just saw that some optional options were added.
However I took a look at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-analytics/src/gatsby-node.js and `cookieFlags` was not added to schema, please inspect.

**Comment by mxstbr** [comment]
Oops I forgot the one key you were talking about, super sorry about that! 🤦

**Comment by mohsenkhanpour** [comment]
@mxstbr Many thanks.
