### ISSUE TITLE
gatsby-* files and Babel

### ISSUE THREAD

**Issue by pindjur** [gatsbyjs/gatsby#27834]
From [creating a local plugin](https://www.gatsbyjs.com/docs/creating-a-local-plugin/) documentation page: 

> Like all gatsby-* files, the code is not processed by Babel. If you want to use JavaScript syntax which isn’t supported by your version of Node.js, you can place the files in a src subfolder and build them to the plugin folder root.

But gatsby-browser is processed. This is likely outdated documentation.  It shoud be easy to reproduce, view bundled script file that starts with app. Here is reactjs.org [script file](https://reactjs.org/app-bd5759781bb3f2833d32.js). Exported handlers from gatsby-browser.js are bundled in app.js and code inside handlers are processed.

**Comment by vladar** [comment]
Thanks for opening this @pindjur 

`gatsby-browser` is not directly pre-processed by babel (same as any other gatsby-* file) but it is included by webpack and so is processed as a part of the webpack bundling step.

But this note is indeed a bit confusing. A PR with a clarification is welcome!

**Comment by StefanSelfTaught** [comment]
I've open a PR #28072
