### ISSUE TITLE
dev-404-page not compatible with Internet Explorer

### ISSUE THREAD

**Issue by emanueleperuffo** [gatsbyjs/gatsby#27845]
## Description

dev-404-page has a dependency on query-string > 6.0 which is not compatible with Internet Explorer because it makes use of arrow functions. https://github.com/sindresorhus/query-string/releases?after=v6.6.0

Gatsby, accordingly to the documentation, should support "the same browsers as the current stable version of React.js which is currently IE9+ as well as the most recent versions of other popular browsers". https://www.gatsbyjs.com/docs/browser-support/

When on development, webpack includes the code of query-string in the bundle because it is imported by dev-404-page.js.

This way it becomes impossible to work on IE productively because the browser throws a syntax error. One hack I have found to work on development, and that I actually use, is this:

```javascript
/** @type {import('gatsby').GatsbyNode['onCreatePage']} */
exports.onCreatePage = (args) => {
  const {page, actions} = args;

  if (page.component.endsWith('/dev-404-page.js')) {
    // This page depends on query-string, which is not compatible with Internet Explorer
    actions.deletePage(page);
  }
};
```

### Steps to reproduce

1. start gatsby develop
2. open IE. commons.js now throws a syntax error

### Expected result

The website should show up.

### Actual result

We see a blank page, and a syntax error in the developer tools.

### Environment

```
  System:
    OS: Linux 5.8 NixOS 20.09 (Nightingale) 20.09.1599.d105075a1fd (Nightingale)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Shell: 4.4.23 - /nix/store/xadrr3l5jvkkm3g3lb2g81j5wz51zqdv-bash-interactive-4.4-p23/bin/bash
  Binaries:
    Node: 14.9.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Firefox: 82.0.2
  npmPackages:
    gatsby: ^2.24.53 => 2.24.66 
    gatsby-core-utils: ^1.3.21 => 1.3.21 
    gatsby-image: ^2.4.4 => 2.4.20 
    gatsby-plugin-emotion: ^4.3.2 => 4.3.12 
    gatsby-plugin-google-analytics: ^2.3.3 => 2.3.15 
    gatsby-plugin-layout: ^1.3.4 => 1.3.12 
    gatsby-plugin-manifest: ^2.4.5 => 2.4.32 
    gatsby-plugin-mdx: ^1.2.13 => 1.2.42 
    gatsby-plugin-netlify: ^2.3.5 => 2.3.16 
    gatsby-plugin-netlify-cms: ^4.3.5 => 4.3.15 
    gatsby-plugin-nprogress: ^2.3.4 => 2.3.12 
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.12 
    gatsby-plugin-sharp: ^2.6.4 => 2.6.37 
    gatsby-plugin-typography: ^2.5.2 => 2.5.12 
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2 
    gatsby-source-filesystem: ^2.3.4 => 2.3.31 
    gatsby-transformer-sharp: ^2.5.2 => 2.5.16 
    gatsby-transformer-yaml: ^2.4.2 => 2.4.13 
  npmGlobalPackages:
    gatsby-cli: 2.12.38
```

**Comment by wardpeet** [comment]
Hey, we're happy to accept a PR to fix this. It looks like not all code is transpiled correctly in develop.
