### ISSUE TITLE
Cannot install gatsby-cli

### ISSUE THREAD

**Issue by woodpaul** [gatsbyjs/gatsby#27840]
Hi!

I am trying to install globally gatsby-cli with npm (also have tried with yarn):

```
npm install -g gatsby-cli
```

The process stops after a while with the following error:

```
2146 verbose stack envinfo: No matching version found for envinfo@^7.7.3.
2146 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:207:23)
2146 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:96:26
2146 verbose stack     at async Promise.all (index 9)
2146 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:785:5)
2146 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:202:7)
2146 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:121:5)
2146 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:40:5)
2147 verbose cwd /Users/Ferenc
2148 verbose Darwin 19.6.0
2149 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "gatsby-cli"
2150 verbose node v15.0.1
2151 verbose npm  v7.0.3
2152 error code ETARGET
2153 error notarget No matching version found for envinfo@^7.7.3.
2154 error notarget In most cases you or one of your dependencies are requesting
2154 error notarget a package version that doesn't exist.
2155 verbose exit 1
```

I've tried to update envinfo manually, but on the npm only version 7.7.2 is available.
Please change the version so installation of gatsby-cli would be possible.

Thank you,
Ferenc

**Comment by ascorbic** [comment]
Hi @woodpaul. I can't reproduce this, and [envinfo@7.7.3](https://www.npmjs.com/package/envinfo) does seem to be the latest version available. I know the npm regustry has been a but unreliable recently, so could you try again and let me know if it's still failing. If that doesn't help, can you give me more info such as your node and npm versions, and your OS and version. Thanks

**Comment by woodpaul** [comment]
Hi Matt,

Thanks for getting back to me.
I've just checked and it is still not working for me. :(

At the moment I am on
node v15.0.1 (i've been using v14.6, updated due to my issues with
gatsby-cli)
npm v7.0.3
MacOS Catalina 10.15.7
iTerm2 with ZSH

Hope it helps.
I've already spent long hours trying to find a solution before contacting
you.

In the beginning of October I was able to install gatsby-cli without a
problem.
Then I tried to start a new project that failed. Then I decided to
reinstall the cli, and I am stuck here since.

Thank you for your help in advance.

Kind regards,
Ferenc

**Comment by ascorbic** [comment]
Hi. Could you try `npm install -g envinfo@^7.7.3` and see what happens?

**Comment by woodpaul** [comment]
I've already tried.

Npm says "no matches found".
It is strange, like it is not accepting ^ as valid argument at all, even
with envinfo^7.7.0 it didn't work.

If i go with npm install -g envinfo@7.7.3 (without higher or equal), then i
am getting this error:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for envinfo@7.7.3.
npm ERR! notarget In most cases you or one of your dependencies are
requesting
npm ERR! notarget a package version that doesn't exist.

With version 7.7.2 it works though.

**Comment by woodpaul** [comment]
The problem was with my local configuration. Apologies.
