### ISSUE TITLE
Invalid CSS but it's sass

### ISSUE THREAD

**Issue by silverscat-3** [gatsbyjs/gatsby#27842]
## Description

I can't build when I load sass using gatsby-plugin-sass.

```
error Generating development JavaScript bundle failed


html, body, #___gatsby, div[role="group"][tabindex], #gatsby-focus-wrapper
^
      Invalid CSS after "h": expected 1 selector or at-rule, was "html, body, #___gat"
      in /home/****/Documents/sass-bug/src/stylesheets/gatsby_reset.sass (line 1, column 1)
failed Building development bundle - 2.771s
```

I used the npx command to confirm that there is no issue with node-sass itself.

### Steps to reproduce

1. Create a project
2. Install gatsby-plugin-sass
3. Put random sass file
4. It happened

Demo: https://github.com/silverscat-3/gasby-sass-issue

### Expected result

Complete build

### Actual result

Output error and can't build

```
error Generating development JavaScript bundle failed


html, body, #___gatsby, div[role="group"][tabindex], #gatsby-focus-wrapper
^
      Invalid CSS after "h": expected 1 selector or at-rule, was "html, body, #___gat"
      in /home/****/Documents/sass-bug/src/stylesheets/gatsby_reset.sass (line 1, column 1)
failed Building development bundle - 2.771s
```

### Environment

  System:
    OS: Linux 5.4 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.0.1 - /bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 6.14.8 - /bin/npm
  Languages:
    Python: 3.8.6 - /bin/python
  npmPackages:
    gatsby: ^2.25.1 => 2.25.2 
    gatsby-plugin-sass: ^2.4.2 => 2.4.2

**Comment by vladar** [comment]
Thank you for opening this, @silverscat-3 

This syntax is not enabled by default in [node-sass](https://github.com/sass/node-sass#indentedsyntax). To make it work you must enable it in the plugin config like this:

```js
module.exports = {
  /* Your site config here */
  plugins: [
    { resolve: `gatsby-plugin-sass`, options: { indentedSyntax: true } },
  ],
}

```

We're marking this issue as answered and closing it for now but please feel free to comment and mention me if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
