### ISSUE TITLE
Consider deprecating Moment.js due to it being legacy tech

### ISSUE THREAD

**Issue by mor10** [gatsbyjs/gatsby#27859]
## Description
Moment.js is considered a legacy project by its maintainers:
> "We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done."

Source: [https://momentjs.com/docs/](https://momentjs.com/docs/)

Apart from the various issues with Moment.js itself, JS itself now encapsulates much if not all its features.

## Recommendations
- Deprecate Moment.js and replace with standard JS features.
- Update documentation to provide adequate transition instructions for devs using Moment.js features.

**Comment by vladar** [comment]
Thank you for opening this, @mor10 

This is under discussion / planned for v3. I encourage you to read and post a comment in this thread: https://github.com/gatsbyjs/gatsby/issues/15277
