### ISSUE TITLE
gatsby-transformer-sharp plugin not exporting onPreExtractQueries

### ISSUE THREAD

**Issue by EricSSartorius** [gatsbyjs/gatsby#2785]
When trying to run `gatsby develop` (v1.1.7)  with `gatsby-transformer-sharp` installed I am getting the following message:
```Your plugins must export known APIs from their gatsby-node.js.
The following exports aren't APIs. Perhaps you made a typo or
your plugin is outdated?

See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby Node APIs

 — The plugin "gatsby-transformer-sharp@1.6.13" is exporting a variable named "onPreExtractQueries" which isn't an API.
```

The plugin version is recent and in my `gatsby-config.js` file it is under my plugins as `'gatsby-transformer-sharp'`, so no typo there. And I double checked that `onPreExtractQueries` is in the list of Gatsby Node APIs...

Is this a problem with the plugin or am I missing something?

**Comment by KyleAMathews** [comment]
You're running an old version of Gatsby. `gatsby-transformer-sharp` is expecting a new API from `gatsby` to be available. Try upgrading all your packages.

**Comment by EricSSartorius** [comment]
Thank you, it works now! Sorry, I thought I checked that I was up to date.
