### ISSUE TITLE
🗣 Documentation Reorganization Project

### ISSUE THREAD

**Issue by meganesu** [gatsbyjs/gatsby#27857]
Hi all! For those of you that I haven't met yet, I'm Megan. I'm a developer at Gatsby who focuses on our documentation.

I created this issue as a Public Service Announcement about our current documentation reorganization project! For more information, please refer to this GitHub Discussion: #27856

## How to help

If you're interested in sharing your feedback on our current documentation, we'd love to hear your thoughts in the linked Discussion above.

You can also [fill out this contact form](https://forms.gle/WNDEnDEAwBkZprNh6) to give feedback on the new docs site once we have a prototype!

Thank you in advance for your feedback and for being part of our community! 💜

**Comment by meganesu** [comment]
## Project Update 🗣

We have our first prototype of the new docs site! Check out the [GitHub discussion](https://github.com/gatsbyjs/gatsby/discussions/27856#discussioncomment-136915) for the full update, and let us know what you think so far!

**Comment by KarenEfereyan** [comment]
@meganesu I'm Karen. I'm a new user of Gatsbyjs and I've found it amazing so far. I'd like to start contributing to it. I'll take a look at the github discussions

**Comment by meganesu** [comment]
Hi @KarenEfereyan, welcome to Gatsby! We're excited to have you :)

We'd love to have you contribute! If you take a look at [our open issues](https://github.com/gatsbyjs/gatsby/issues), you can look around and see if there's anything that you're interested in working on. (The "good first issue" and "help wanted" labels are a good place to start.)

As far as the docs reorg goes, we'd love your feedback on our prototype for the new docs site! Feel free to check out the [GitHub discussion](https://github.com/gatsbyjs/gatsby/discussions/27856#discussioncomment-136915) for more details. Your experience as a new Gatsby user would be extremely helpful, since our goal is to make the new site easier for Gatsby newcomers to navigate!

You can fill out the [contact form](https://forms.gle/WNDEnDEAwBkZprNh6) or leave your thoughts in the GitHub discussion. Looking forward to your contribution! 💜

**Comment by LekoArts** [comment]
This since has been finished. Yey 🎉
