### ISSUE TITLE
Error: The result of this StaticQuery could not be fetched.

### ISSUE THREAD

**Issue by AndriesVDW** [gatsbyjs/gatsby#27878]
## Description

I am getting the following error:

> Error: The result of this StaticQuery could not be fetched.
> 
> This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in > https://github.com/gatsbyjs/gatsby/issues

### Steps to reproduce
The error is being thrown because of the following code:
```tsx
import React from "react";

import { Helmet } from "react-helmet";

import { PropsWithChildren } from "react";

import { graphql } from "gatsby";
import { useStaticQuery } from "gatsby";

import "@css/component/Layout.module.scss";

/**
 * @type LayoutProps
 */
export type LayoutProps = Readonly<PropsWithChildren<{}>>;

/**
 * @const Layout
 */
const Layout = (props: LayoutProps) => {
    const {
        children
    } = props;

    const result = useStaticQuery(graphql`
        query {
            wordpress {
                generalSettings {
                    title
                }
            }
        }
    `);

    console.log(result);

    return (
        <>
            <Helmet>
                <title>Title</title>
            </Helmet>
            <header>Header</header>
            { children }
            <footer>Footer</footer>
        </>
    );
};

export default Layout;
```

My `package.json` looks like this:

```
{
  "dependencies": {
    "dotenv": "^8.2.0",
    "gatsby": "^2.25.3",
    "gatsby-plugin-react-helmet": "^3.3.14",
    "gatsby-plugin-sass": "^2.4.2",
    "gatsby-plugin-sharp": "^2.7.1",
    "gatsby-source-wordpress-experimental": "^1.7.9",
    "gatsby-transformer-sharp": "^2.5.21",
    "node-sass": "^4.14.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0"
  },
  "devDependencies": {
    "@types/react-helmet": "^6.1.0"
  }
}
```

### Expected result

It should get the title from my Wordpress website and log it in the console.

### Actual result

It throws an error:

> Error: The result of this StaticQuery could not be fetched.
> 
> This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in > https://github.com/gatsbyjs/gatsby/issues

### Environment

> System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 15.1.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 7.0.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 82.0
  npmPackages:
    gatsby: ^2.25.3 => 2.25.3 
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14 
    gatsby-plugin-sass: ^2.4.2 => 2.4.2 
    gatsby-plugin-sharp: ^2.7.1 => 2.7.1 
    gatsby-source-wordpress-experimental: ^1.7.9 => 1.7.9 
    gatsby-transformer-sharp: ^2.5.21 => 2.5.21 
  npmGlobalPackages:
    gatsby-cli: 2.12.117

**Comment by AndriesVDW** [comment]
Okay, so I found the issue.
I had put my code in a folder with another name then "src". When I renamed the folder to "src" it all worked.

**Comment by sidharthachatterjee** [comment]
Glad to hear you figured it out! Cheers. Closing this!
