### ISSUE TITLE
Clarification on trailing slashes, urls in sitemaps and canonical urls?

### ISSUE THREAD

**Issue by alexpchin** [gatsbyjs/gatsby#27889]
I am currently working on a gatsby website and I've been struggling to find the "best practise" and implementation for all things related to trailing slashes: 

- "to use or not use" trailing slashes
- trailing slashes in URLs in sitemaps
- trailing slashes in canonical URLs
- confusion over `gatsby-plugin-remove-trailing-slashes` and `gatsby-plugin-force-trailing-slashes`

After researching, it seems other people are confused as well and I don't feel that the documentation is clear as to what the best practices are and how to go about achieving them. It seems there is an unnecessary amount of out-of-the box learning when it comes to best setup. Also, which bits require server configuration and which bits do not.

- https://github.com/gatsbyjs/gatsby/issues/6365
- https://github.com/gatsbyjs/gatsby/issues/15317
- https://github.com/gatsbyjs/gatsby/issues/9207

Here are my questions:

**1. If gatsby pages are generated with a directory structure `about/index.html`, so should the URLs have a trailing slash?**

According to: 

- [https://searchfacts.com/url-trailing-slash/]()
- [https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html]()

If the resource you are linking to is a directory then it should have a trailing slash. As Gatsby, by default creates directories for URLs, then they should include the trailiing slash?

**2. Should users setup 301 redirects from no trailing slash to trailing slash?**

Accordinig to the previous links, the non-trailing slash URL should have a 301 redirect to the trailinig slash URL.

- https://www.website.com/about -> 301 redirect -> https://www.website.com/about/

When setting up, it seemed like the plugin `gatsby-plugin-force-trailing-slashes` would do this for you however it doesn't do the 301 redirect which is a server setup problem.

In this project, I am using Cloudfront, so used this function to redirect from no trailing slash to trailiing slash. This is not a trivial thing for someone starting out to work out? 

```js
// https://gist.github.com/karolmajta/6aad229b415be43f5e0ec519b144c26e

'use strict';

const pointsToFile = uri => /\/[^/]+\.[^/]+$/.test(uri);

exports.handler = (event, context, callback) => {
    
    // Extract the request from the CloudFront event that is sent to Lambda@Edge 
    var request = event.Records[0].cf.request;

    // Extract the URI from the request
    var oldUri = request.uri;
    var newUri;
    
    if (!pointsToFile(oldUri) && !oldUri.endsWith('/')) {
      const newUri = request.querystring ? `${oldUri}/?${request.querystring}` : `${oldUri}/`;
      return callback(null, {
        body: '',
        status: '301',
        statusDescription: 'Moved Permanently',
        headers: {
          location: [{
            key: 'Location',
            value: newUri,
          }],
        }
      });
    } else {
      newUri = oldUri;
    }

    // Match any '/' that occurs at the end of a URI. Replace it with a default index
    newUri = newUri.replace(/\/$/, '\/index.html');
    
    // Log the URI as received by CloudFront and the new URI to be used to fetch from origin
    console.log("Old URI: " + oldUri);
    console.log("New URI: " + newUri);
    
    // Replace the received URI with the URI that includes the index page
    request.uri = newUri;
    
    // Return to CloudFront
    return callback(null, request);

};
```

I know on Netlify there are other options to do tthis.

Note: Alternatively `gatsby-plugin-create-page-html` is a plugin that creates an `about.html` file from an `about/index.html` file. However, this just means you have two resources for the same content, which I believe isn't good.

**3. Your pages should include a canoncial URL that includes the trailing space**

I tried both `gatsby-plugin-canonical-urls` and `gatsby-plugin-react-helmet-canonical-urls` to add canonic URLs to my pages. In the documentation for [`gatsby-plugin-canonical-urls`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-canonical-urls) it says:

> With the above configuration, the plugin will add to the head of every HTML page a rel=canonical e.g.
> 
> ```
> <link rel="canonical" href="https://www.example.com/about-us/" />
> ```

This show that the URL should have a trailing slash.

FYI: I added patch for `gatsby-plugin-react-hemet-canonical-urls` to force an option to force a trailing slash:

```
diff --git a/node_modules/gatsby-plugin-react-helmet-canonical-urls/wrap-page.js b/node_modules/gatsby-plugin-react-helmet-canonical-urls/wrap-page.js
index ea5cc53..37ee5a0 100644
--- a/node_modules/gatsby-plugin-react-helmet-canonical-urls/wrap-page.js
+++ b/node_modules/gatsby-plugin-react-helmet-canonical-urls/wrap-page.js
@@ -7,6 +7,7 @@ var _require = require('react-helmet'),
 
 var defaultPluginOptions = {
   noTrailingSlash: false,
+  trailingSlash: false,
   nopQueryString: false,
   nopHash: false
 };
@@ -33,6 +34,7 @@ module.exports = function (_ref, pluginOptions) {
   if (options.siteUrl && !isExcluded(options.exclude, location.pathname)) {
     var pathname = location.pathname || '/';
     if (options.noTrailingSlash && pathname.endsWith('/')) pathname = pathname.substring(0, pathname.length - 1);
+    if (options.trailingSlash && !pathname.endsWith('/')) pathname = pathname.replace(/\/?$/, '/');
     var myUrl = "" + options.siteUrl + pathname;
     if (!options.noQueryString) myUrl += location.search;
     if (!options.noHash) myUrl += location.hash;
```

I know these are more of a collection of thoughts but I feel like there are lots of people asking questions related to these issues so the documentation could perhaps be more direct at addressing the solutions?

**Comment by LekoArts** [comment]
What documentation did you find confusing? Can you directly link to it and highlight the portions of it?

Gatsby by default creates paths with a trailing slash, everything after that is your personal preference and I don't think we make any recommendations or comments about this. Moreover the documentation should be specific to Gatsby so I don't see the need for explanations about server redirects or SEO implications if there are enough articles on the internet already.

The example you cited from the canonical URL plugin just happens to have the trailing slash as that's what Gatsby is creating by default. It doesn't imply that canonical URLs have to have a trailing slash.

I'd recommend sticking to one of the two options (non-trailing/trailing) and keeping it consistent everywhere.
