### ISSUE TITLE
My netlify.toml isn't fully processed while deploying via Gatsby Cloud (w/ netlify webhooks)

### ISSUE THREAD

**Issue by mikeyfe6** [gatsbyjs/gatsby#27895]
## Description

I have a feelin that my `netlify.toml` **isn't** processed while deploying via **Gatsby Cloud** (w/ netlify webhooks).. I can't fully confirm it. But I noticed it because i cannot find my **custom CSP**.. only the **default setting**s are read and used. 

**However** if i do a manual 'netlify-rebuild' my CSP rules do come through but that's obviously not the workflow I want. How do I fix this?

### Steps to reproduce

link to **github**: [https://github.com/mikeyfe6/Gimmix](https://github.com/mikeyfe6/Gimmix)
link to **live project**: [https://gimmix.nl](https://gimmix.nl) 

**Is there something I should add/edit to the plugin options?**

<pre>
{
      <b>resolve:</b> `gatsby-plugin-netlify`,
      <b>options:</b> {
        mergeSecurityHeaders: <b>true</b>, // boolean to turn off the default security headers
        mergeLinkHeaders: <b>true</b>, // boolean to turn off the default gatsby js headers
        mergeCachingHeaders: <b>true</b>, // boolean to turn off the default caching headers
        generateMatchPathRewrites: <b>true</b>, // boolean to turn off automatic creation of redirect rules for client only paths
      },
 },
</pre>

### Expected result

The workflow between **Gatsby Cloud -> Netlify** should be flawless; my custom CSP and custom headers should been processed.

### Actual result

Custom CSP and custom headers rules in my`netlify.toml` **aren't** processed.

### Environment

<pre>
<b>System:</b>
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  <b>Binaries:</b>
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
<b>Languages:</b>
    Python: 2.7.16 - /usr/bin/python
  <b>Browsers:</b>
    Chrome: 86.0.4240.183
    Safari: 14.0
 <b>npmPackages:</b>
    gatsby: ^2.25.3 => 2.25.3
    gatsby-image: ^2.4.21 => 2.4.21
    gatsby-plugin-canonical-urls: ^2.3.13 => 2.3.13
    gatsby-plugin-catch-links: ^2.3.15 => 2.3.15
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-feed: ^2.6.0 => 2.6.0
    gatsby-plugin-google-tagmanager: ^2.4.0 => 2.4.0
    gatsby-plugin-manifest: ^2.5.2 => 2.5.2
    gatsby-plugin-netlify: ^2.4.0 => 2.4.0
    gatsby-plugin-nprogress: ^2.3.13 => 2.3.13
    gatsby-plugin-offline: ^3.3.2 => 3.3.2
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14
    gatsby-plugin-robots-txt: ^1.5.3 => 1.5.3
    gatsby-plugin-sass: ^2.4.2 => 2.4.2
    gatsby-plugin-sharp: ^2.7.1 => 2.7.1
    gatsby-plugin-sitemap: ^2.5.1 => 2.5.1
    gatsby-plugin-smoothscroll: ^1.2.0 => 1.2.0
    gatsby-remark-images: ^3.4.1 => 3.4.1
    gatsby-remark-images-contentful: ^2.3.20 => 2.3.20
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-contentful: ^3.1.3 => 3.1.3
    gatsby-source-filesystem: ^2.4.2 => 2.4.2
    gatsby-transformer-remark: ^2.9.2 => 2.9.2
    gatsby-transformer-sharp: ^2.5.21 => 2.5.21
 <b> npmGlobalPackages:</b>
    gatsby-cli: 2.12.113
</pre>

**Comment by abhiaiyer91** [comment]
I think if you moved your netlify.toml into the `public` directoy on `onPostBuild`, Gatsby Cloud will upload it to Netlify

**Comment by LekoArts** [comment]
Please see https://www.gatsbyjs.com/support/ for Gatsby Cloud related issues, this repository is only for  the open source project.
