### ISSUE TITLE
Empty query when feeding images into gatsby-image using gatsby-source-graphql  and gatsby-source-filesystem

### ISSUE THREAD

**Issue by cristian-rita** [gatsbyjs/gatsby#27915]
## Description

Hi! I'm trying to follow [this](https://www.gatsbyjs.com/docs/schema-customization/#feeding-remote-images-into-gatsby-image) guide to feed images from a Strapi CMS to gatsby-image. When querying from gatsby Graphiql I receive a 400 error from Strapi. 

```javascript
{
  strapi {
    header {
     logo {
      imageFile {
        childImageSharp{
          fixed(width:400){
            src
          }
        }
      }
    }
    }
  }
}
```
Analyzing the request sent by gatsby, it looks like the query is empty. Now if I add some fields before imageFile everything works as expected.

```javascript
{
  strapi {
    header {
     logo {
   		id
      url
      imageFile {
        childImageSharp{
          fixed(width:400){
            src
          }
        }
      }
    }
    }
  }
}
```

### Steps to reproduce

To reproduce this just use this: https://github.com/gatsbyjs/gatsby/tree/master/examples/using-gatsby-source-graphql
and any CMS.

### Expected result

The query should work fine.

### Actual result

Gatsby is sending an empty query that the CMS fails to parse. 

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.183
    Firefox: 82.0.2
    Safari: 14.0
  npmPackages:
    gatsby: ^2.25.3 => 2.25.3 
    gatsby-image: ^2.4.21 => 2.4.21 
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14 
    gatsby-plugin-sharp: ^2.7.1 => 2.7.1 
    gatsby-plugin-styled-components: ^3.3.14 => 3.3.14 
    gatsby-source-filesystem: ^2.4.2 => 2.4.2 
    gatsby-source-graphql: ^2.7.7 => 2.7.7 
    gatsby-transformer-sharp: ^2.5.21 => 2.5.21 
  npmGlobalPackages:
    gatsby-cli: 2.12.100

**Comment by vladar** [comment]
Thank you for opening this, @cristian-rita 

There is the following comment in the guide you linked:

```graphql
      image {
        # It is important to include all fields in the query which you want to
        # access in the resolver. In this example make sure to include
        # the `url` field. In the future, Gatsby might provide a `@projection`
        # extension to automatically include those fields.
        url
        imageFile {
```

So this behavior is a known limitation at the moment.

We're marking this issue as answered and closing it for now but please feel free to comment and mention me if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜
