### ISSUE TITLE
`gatsby-transfomer-sharp` adds `childImageSharp` to wrong types.

### ISSUE THREAD

**Issue by andris-sevcenko** [gatsbyjs/gatsby#27924]
## Description

[During `onCreateNode` ](https://github.com/gatsbyjs/gatsby/blob/df914d94a7c47c6082b6f165eb44dc6e15e12c7d/packages/gatsby-transformer-sharp/src/on-node-create.js) the plugin only checks whether the `extension` field exists and is populated with a supported extension, before adding the `childImageSharp` field to the node, and this behavior is not configurable.

In Craft CMS, Assets are content elements that describe a file, so it's perfectly normal for them to have a populated `extension` field, however, they are not files themselves. This leads to `childImageSharp` fields being created on them that always results in an error.

### Steps to reproduce

Have an external data source and have at least one type that has the `extension` field populated with a valid image extension.

Run `gatsby develop`, open `http://localhost:800/__graphql` and query for the corresponding Gatsby node. Observe that a `childImageSharp` field is present.

You can use the following project to reproduce it: https://github.com/craftcms/starter-blog/blob/master/headless-front-end/gatsby/README.md, but it'll be a little bit involved.

### Expected result

The `childImageSharp` field should not appear based on one field existing or not.

### Actual result

It does appear.

**Comment by pieh** [comment]
Thanks for report - I opened https://github.com/gatsbyjs/gatsby/pull/27992 that should remove `childImageSharp` from non-`File` types

**Comment by andris-sevcenko** [comment]
Appreciate the speedy resolution!
