### ISSUE TITLE
Failed to parse develop-static-entry.js

### ISSUE THREAD

**Issue by Alxandr** [gatsbyjs/gatsby#2792]
My build is failing with the following error:

```
  Error: Module parse failed: /Users/alxandr/hub/alxandr.me/packages/node_modules/alxandr.me/.cache/develop-static-entry.js Unexpected token (63:4)
  You may need an appropriate loader to handle this file type.
  SyntaxError: Unexpected token (63:4)
  
  - acorn.js:2221 Parser.pp$4.raise
    [gatsby]/[webpack]/[acorn]/dist/acorn.js:2221:15
```

The file is auto-generated, and the token it's crashing on is `...` (object rest spread). I tried to add the object rest spread to the babel config (both by creating a babelrc, and by adding a modifyBabelrc). Neither helped.

**Comment by KyleAMathews** [comment]
Does this happen on any gatsby site? I've never seen or heard of this error before. The default Babel setup handles object spread so not sure why that's not working.

**Comment by Alxandr** [comment]
I don't know. It happens on my site, and I don't know why. Nor do I know how to go about debugging it. It handles object rest spread in my own files just fine, but not in the auto-generated one `.cache/develop-static-entry.js`.

**Comment by Alxandr** [comment]
![image](https://user-images.githubusercontent.com/112334/32457746-6b1b14de-c32a-11e7-8f9e-83769c8c7a82.png)

Taken from https://github.com/babel/babel/blob/master/experimental/babel-preset-env/README.md

Might be related...

**Comment by jquense** [comment]
Do you have a local `.babelrc`? The default config definitely has all the necessary plugins via preset-env and stage-0

**Comment by Alxandr** [comment]
No I don't. But given that a babel readme has a warning about some version incompatibilities with object rest spread, I figured it'd be likely that is the cause of my issues.

**Comment by mathieudutour** [comment]
I stumbled upon the same error.

In my case, it's because my gatsby folder was inside a `node_modules` folder.

The following webpack loader
```js
{
    test: /\.jsx?$/,
    exclude: /(node_modules|bower_components)/,
    loader: 'babel',
    query: { plugins: [Array], presets: [Array], cacheDirectory: true }
}
```
is ignoring any file which has a name matching `/(node_modules|bower_components)/`. This is maybe a bit exessive. Could we perhaps exclude only if the name is `new Regex(process.cwd() + '/(node_modules|bower_components)'` or something?

**Comment by bodia-uz** [comment]
Similar error with the acorn.
I don't modify webpack config, but gatsby site is inside a `node_modules`.

Something like this:
`/PATH_TO_MY_APP/node_modules/PATH_TO_LIB/site/node_modules/gatsby`

Config generated by gatsby after `compilerConfig.resolve()` `(https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/develop-html.js#L23) looks like this (using JSON.stringify):
https://gist.github.com/bodia-uz/5faaa47e0e604e2f2055bfd26d590d30

**Comment by Morlem** [comment]
I was having this same issue trying to use a 3rd party React component library with Gatsby.

The first example on the page @bodia-uz linked to worked for me.
https://www.gatsbyjs.org/docs/add-custom-webpack-config/#modifying-the-babel-loader

In my case, trying out the Salesforce design system, I needed to change the exclude line to:
```
exclude: modulePath =>
        /node_modules/.test(modulePath) && !/node_modules\/(@salesforce)/.test(modulePath)
```

This was a little confusing initially since you're adding an exclusion to the exclusion with the `&& !`

**Comment by magnusarinell** [comment]
Worked for me using @bodia-uz fix but without using an indexer:
```
exports.modifyWebpackConfig = ({ config }) => {
  config._loaders.js.config.exclude = new RegExp(process.cwd() + '/(node_modules|bower_components)');
};
```

**Comment by bodia-uz** [comment]
As variant, If all your code to transpile is inside `src`:
```
exports.modifyWebpackConfig = ({ config }) => {
  config._loaders.js.config.include = [
    new RegExp(process.cwd() + '/src'),
    new RegExp(process.cwd() + '/.cache'),
  ];
  config._loaders.js.config.exclude = undefined;
};
```

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by johnatspreadstreet** [comment]
> Do you have a local `.babelrc`? The default config definitely has all the necessary plugins via preset-env and stage-0

Nice, this was definitely the issue I was having.
