### ISSUE TITLE
gatsby-transformer-remark use gray-matter excerpt

### ISSUE THREAD

**Issue by reccanti** [gatsbyjs/gatsby#2794]
I’m trying to grab excerpts from my markdown files up to a specified separator, similar to how they’re handled by graymatter and jekyll [link](https://github.com/jonschlinkert/gray-matter#optionsexcerpt_separator). Seeing as how this plugin uses graymatter under-the-hood, is there any way to access this functionality?

gatsby-transformer-remark version - 1.7.19
gatsby version - 1.9.73

**Comment by KyleAMathews** [comment]
This is the relevant code https://github.com/gatsbyjs/gatsby/blob/2439ef79b4e667efd4c548dffef0a8fcca17248c/packages/gatsby-transformer-remark/src/on-node-create.js#L22

**Comment by reccanti** [comment]
Okay! It looks like graymatter accepts an object as a second parameter after `content` where you can specify whether to get an excerpt and what the excerpt should be. Any idea what the best way to add this functionality would be? Would it be better as a custom plugin, or would it be useful to add this functionality to the main remark plugin? 

Sorry if I'm asking a lot. I'm new to working with Gatsby

**Comment by reccanti** [comment]
Just noticed this. gatsby-transformer-remark relies version 2.1 of graymatter, but the excerpt options were added in version 3.0

**Comment by KyleAMathews** [comment]
Oh sweet! Would you like to put together a PR that upgrades gray-matter and documents how to add excerpt support?

You'd also need to modify the existing excerpt functionality to check if there's an excerpt already set and use that instead of generating a new one https://github.com/gatsbyjs/gatsby/blob/6ff3bc38b97ed4185bd97b7f90e10d580abcbb2d/packages/gatsby-transformer-remark/src/extend-node-type.js#L262

**Comment by reccanti** [comment]
Sure, I can take a look at that!

**Comment by reccanti** [comment]
We should close this since it was taken care of in this PR https://github.com/gatsbyjs/gatsby/pull/2883. 

@fxfactorial You can updated the pruneLength in your graphql https://using-remark.gatsbyjs.org/excerpts/

**Comment by fxfactorial** [comment]
appreciate it!

**Comment by pieh** [comment]
Closing this issue, as this was already resolved as mentioned by @reccanti
