### ISSUE TITLE
runQuery in custom resolvers do not track collections for queries

### ISSUE THREAD

**Issue by aaronadamsCA** [gatsbyjs/gatsby#27940]
I'm having continued problems with Gatsby failing to clear the right parts of the Gatsby build cache. I am using schema customizations.

### Steps to reproduce

Here's what I've reproduced locally; I'm not sure yet how to create a reproduction for anyone else. I do wonder if anyone could offer advice on how to troubleshoot or work around this issue, short of forcing a `gatsby clean` on every site update (which I'm pretty sure could only be done manually in Gatsby Cloud).

I have the following (partial) page template:

```graphql
query NeighbourhoodTemplate($id: String!) {
  neighbourhood: sanityNeighbourhood(id: { eq: $id }) {
    title
    stores {
      nodes {
        ...StoreListFields
      }
    }
  }
}
```

`neighbourhood.stores` is provided by the following custom resolver (and then forwarded to `neighbourhood.stores.nodes`):

```js
const resolveNeighbourhoodStores = async ({ id }, _, { nodeModel }) =>
  (await nodeModel.runQuery({
    type: "SanityStore",
    query: {
      filter: {
        neighbourhoods: { elemMatch: { id: { eq: id } } },
        flags: { visible: { eq: true } },
      },
    },
  })) || [];
```

### Expected result

When a new store is created (or an existing store has `flags.visible` changed to `true`), the store should appear on matching neighbourhood pages.

### Actual result

When a new store is created, it does not always appear on matching neighbourhood pages. `gatsby clean` followed by a new build is required.

Note that when an existing store is deleted (or has `flags.visible` changed to `false`) the same problem does not happen; the store is correctly modified or removed. This would seem to suggest the build cache can handle node changes/removals in a query result, and is only failing to notice new nodes.

### Environment

Node 12, React 16.14, with the following Gatsby packages:

```
    gatsby: ^2.25.3 => 2.25.3 
    gatsby-image: ^2.4.21 => 2.4.21 
    gatsby-plugin-algolia: ^0.14.1 => 0.14.1 
    gatsby-plugin-google-gtag: ^2.1.13 => 2.1.13 
    gatsby-plugin-manifest: ^2.5.2 => 2.5.2 
    gatsby-plugin-netlify: ^2.4.0 => 2.4.0 
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sharp: ^2.7.1 => 2.7.1 
    gatsby-plugin-theme-ui: ^0.3.3 => 0.3.3 
    gatsby-source-sanity: ^6.0.4 => 6.0.4 
    gatsby-theme-style-guide: ^0.3.3 => 0.3.3 
    gatsby-transformer-sharp: ^2.5.21 => 2.5.21 
```

**Comment by vladar** [comment]
We need to figure out if we actually re-run queries for all pages with `SanityStore` lists. Or in other words - is it resolver results that are stale or full query results?

Also - what happens if you run the same query manually in GraphiQL - do you see the new data?

**Comment by aaronadamsCA** [comment]
GraphiQL queries do see the new data, yes. It looks to be strictly a build cache issue. The queries with `SanityStore` lists do re-run correctly on node changes and removals.

Here's what I see when I set store visibility to `false`. 10 affected pages is about right, I think:

```
success run page queries - 0.886s - 10/10 11.29/s
```

When I set it back to `true`, it only reappears in some of the places it disappeared from:

```
success run page queries - 0.398s - 4/4 10.05/s
```

So my guess here is that the cache knows how to monitor an existing relationship, but doesn't understand how to detect a new one that should now exist.

I discussed this on the side with @sidharthachatterjee and I believe there are some coming improvements that may address this scenario. Which is great! So for now I can just keep clearing the cache each time I rebuild.

**Comment by sidharthachatterjee** [comment]
The issue here is that `runQuery` doesn't track collections by itself. The quick fix for now is to add a call to 

```
nodeModel.createPageDependency({
  path,
  connection: collectionName,
});
```

This will opt in dependency tracking for the collection. We should fix this in core to enable auto tracking though. Let's track that in this issue. I'll open a fix, later this week.
