### ISSUE TITLE
Typography.js and gatsby-image issues

### ISSUE THREAD

**Issue by ghost** [gatsbyjs/gatsby#2795]
![screen shot 2017-11-05 at 05 12 30](https://user-images.githubusercontent.com/241553/32410971-01a2b8ce-c1e8-11e7-9e4b-ed5e857c62ca.png)

### Typography.js

Typography.js themes stopped working for me about a week ago. I've tried reverting to older versions of `gatsby`, `gatsby-link`, and `gatsby-plugin-typography` without success.

The above screenshot shows the Twin Peaks theme. As you can see, there is no error in the console, but the fonts rendered are the default ones instead of the theme-specified ones. The links have unwanted white borders around them. They also don't respect `textDecoration: 'none'`. 

Alton, Judah, and the custom theme from Tutorial Part Two all have no effect.

### gatsby-image

Gatsby Image has an issue, too. When using resolutions, setting `margin` on a `<Img />` unexpectedly displaces the image (see screenshot).

Please see [this repo](https://github.com/leonfeng/gatsby-playground/tree/feature/typography-gatsby-link) for the relevant files.

### Environment:

- gatsby-cli v1.1.19
- node v8.9.0
- macOS v10.12.6

**Comment by KyleAMathews** [comment]
Nothing has changed about Typography.js themes lately. Perhaps investigate changes you made to your site recently? Many example sites + gatsbyjs.org use these tools together and are still working as expected.

**Comment by KyleAMathews** [comment]
It does seem like there could be some bugs though — could you isolate further what is causing trouble?

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
