### ISSUE TITLE
CSS loads properly with gatsby develop, but not gatsby build

### ISSUE THREAD

**Issue by zefwang** [gatsbyjs/gatsby#27978]
## Description
The styling for a page is applied as expected when running gatsby develop, but no styling is applied when using gatsby build + gatsby serve. The styling for this page is written in a SCSS file that is then imported into the main.scss. There are a ton of other pages that are structured the same way, but we see CSS as expected in those pages.

### Steps to reproduce
https://github.com/HackBeanpot/website-2021/blob/develop/src/pages/packet/packet.scss
Run gatsby build and gatsby serve.
Navigate to localhost:9000/packet.

### Expected result
Styling appears as expected.
![Screen Shot 2020-11-11 at 4 23 51 PM](https://user-images.githubusercontent.com/45447059/98866099-6a984800-243a-11eb-9a12-6d69676d3e38.png)

### Actual result
No CSS is applied at all. 
![Screen Shot 2020-11-11 at 4 24 16 PM](https://user-images.githubusercontent.com/45447059/98866314-bcd96900-243a-11eb-858a-bdb69693f215.png)

### Environment
  ```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.193
    Firefox: 82.0.2
    Safari: 14.0
  npmPackages:
    gatsby: ^2.24.86 => 2.24.86 
    gatsby-plugin-google-analytics: ^2.3.19 => 2.3.19 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14 
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0 
    gatsby-plugin-sass: ^2.3.21 => 2.3.21 
    gatsby-plugin-sitemap: ^2.4.17 => 2.4.17 
  npmGlobalPackages:
    gatsby-cli: 2.12.117
```

**Comment by visualjeff** [comment]
What fixed it?

**Comment by zefwang** [comment]
Forgot to import our main.scss file into the page's index.js, adding that fixed it.

**Comment by visualjeff** [comment]
Thanks!
