### ISSUE TITLE
[gatsby-remark-images] Captions affecting styles of blog posts when using mdx

### ISSUE THREAD

**Issue by pavsidhu** [gatsbyjs/gatsby#27977]
## Description

When using `gatsby-plugin-mdx` with `gatsby-remark-images`, some components in the mdx are not styled as expected while others are. This only occurs when `showCaptions` is set to `true` and the page with the MDX is accessed directly rather than through Gatsby's `Link` component.

### Steps to reproduce

Example repo: https://github.com/pavsidhu/gatsby-remark-bug

```
npm install
npm run build
gatsby serve
```

Go to `localhost:9000`, click the `Go to post` link to go to the blog post. You should see all the paragraphs are red. If you reload the page, some of the paragraphs are no longer styled as per the components prop in `MDXProvider`. If you remove `showCaptions: true` in `gatsby.config.js`, all paragraphs are styled properly.

### Environment

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/local/bin/python
  Browsers:
    Edge: 83.0.478.50
    Firefox: 81.0.2
    Safari: 14.0
  npmPackages:
    gatsby: ^2.24.86 => 2.24.86
    gatsby-plugin-mdx: ^1.2.51 => 1.2.51
    gatsby-plugin-sharp: ^2.6.43 => 2.6.43
    gatsby-remark-images: ^3.3.39 => 3.3.39
    gatsby-source-filesystem: ^2.3.36 => 2.4.2
    gatsby-transformer-sharp: ^2.5.20 => 2.5.20
  npmGlobalPackages:
    gatsby-cli: 2.12.51
    gatsby: 2.23.7

**Comment by pieh** [comment]
The thing is that (I think) with `showCaptions` we render `<figure>` (which is a block element) inside `<p>` tag which is not valid

This is quite tricky, and I didn't yet figure out how to fix it, but this can be (somewhat) replicate in just react with something like:

```
<p style={{color: `blue`}}>test<figure>hmm?</figure></p>
```

Depending wether JS is enabled in browser you get one of two resulting DOM structures:
![Screenshot 2020-11-12 at 15 17 45](https://user-images.githubusercontent.com/419821/98951359-73505300-24fa-11eb-97be-55e9f2f240c5.png)

And I think addition of that extra empty `<p>` tag trips up react hydration and cause some paragraphs just to not contain `style` attribute (as react hydration doesn't compare attributes, only "content"):

> React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them. In development mode, React warns about mismatches during hydration. There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.

(from https://reactjs.org/docs/react-dom.html#hydrate )

**Comment by pieh** [comment]
I am not sure how to tackle this problem - I'm not sure if we can make `<figure>` to not end up inside `<p>` tag. Maybe making that `<figure>` not block element could be somehow a workaround but this becomes tricky problem to solve

**Comment by Slapbox** [comment]
Not stale.

**Comment by Slapbox** [comment]
Not stale. Can anybody call off the bot?

**Comment by Slapbox** [comment]
Not stale.

**Comment by tondi** [comment]
Not stale

**Comment by Slapbox** [comment]
Untested, but unlikely to be stale.
