### ISSUE TITLE
Looks like develop for this site is already running, can you visit http://localhost:8000 ? If it is not, try again in five seconds!

### ISSUE THREAD

**Issue by kalkson** [gatsbyjs/gatsby#27976]
## Description

Hey, I get this error when `gatsby develop` every time on my gatsby project which I'm warking since last week:
`error Looks like develop for this site is already running, can you visit http://localhost:8000 ? If it is not, try again in five seconds!`

There is no any runned project or application on 8000 port and no other as well. I tried everything I could think of: clearing cache, reseting npm, updating node, gatsby, npm, getting rid of vulnerabilities, deleteting whole directory and pulling from remote, also on previous commits. And nothing helps. I created a new gatsby project and there is no problem.

Additional, it make no difference if I try to run dev on another port. The problem is the same but for this port.

Gatsby CLI version: 2.12.117
Gatsby version: 2.25.3

node: v14.15.0
npm: 6.14.8

Using Windows 10 64bit

### Steps to reproduce

https://github.com/kalkson/reactywny.pl

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

Should run development server

### Actual result

error Looks like develop for this site is already running, can you visit http://localhost:8000 ? If it is not, try again in five seconds!

### Environment

System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.0
  Browsers:
    Chrome: 86.0.4240.193
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.24.91 => 2.25.3
    gatsby-background-image: ^1.1.2 => 1.1.2
    gatsby-image: ^2.4.21 => 2.4.21
    gatsby-plugin-disqus: ^1.2.2 => 1.2.2
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-layout: ^1.3.13 => 1.3.13
    gatsby-plugin-manifest: ^2.4.37 => 2.5.2
    gatsby-plugin-mdx: ^1.3.1 => 1.3.1
    gatsby-plugin-offline: ^3.2.38 => 3.3.3
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-prettier-eslint: ^1.0.4 => 1.0.4
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-sharp: ^2.7.1 => 2.7.1
    gatsby-plugin-styled-components: ^3.3.14 => 3.3.14
    gatsby-source-datocms: ^2.5.7 => 2.5.7
    gatsby-source-filesystem: ^2.3.37 => 2.4.2
    gatsby-transformer-sharp: ^2.5.20 => 2.5.21
  npmGlobalPackages:
    gatsby-cli: 2.12.117

**Comment by mxstbr** [comment]
This sounds like an issue with our service locking mechanism. Can you try running this command in Powershell and then trying again? :pray:

```
npx rimraf ~\.config\gatsby\sites
```

(I don't use windows myself so I'm not sure if that path is 100% correct)

Sorry for the troubles!

**Comment by kalkson** [comment]
> This sounds like an issue with our service locking mechanism. Can you try running this command in Powershell and then trying again? 🙏
> 
> ```
> npx rimraf ~\.config\gatsby\sites
> ```
> 
> (I don't use windows myself so I'm not sure if that path is 100% correct)
> 
> Sorry for the troubles!

Me and my friend realized that fix but thanks for your answer. This should be usefull for potential guys in future. 
I add that the properly path is: `C:\Users\[your name]\.config\gatsby\sites`

Fixed, thanks!

**Comment by tsdexter** [comment]
I am also having this issue. I cannot run `gatsby develop` on a site after trying all the 'fixes' above.

**Comment by tsdexter** [comment]
@patrickbenjamin1 I fixed it in windows by deleting the entire `gatsby` folder rather than `gatsby/sites`:

1. using vscode bash terminal
2. `cd /c/Users/username/.config`
3. `rm -rf gatsby`

**Comment by T-Fletcher** [comment]
From reading up and solutions not working, I've found this error can arise from a few situations including if a gatsby-related process fails to close when a terminal is shut or if you have multiple Gatsby sites running in multiple terminals.

Here's all the fixes I read of rolled into one for MacOS:

1. Close any OS terminals you have open
2. Close any terminals open in your code editor (VScode for me)
3. Re-open your code editor and terminal
4. Run `rm -rf ~/.config/gatsby/sites`
5. Run `gatsby clean`
6. Run `ps aux | grep gatsby` to see if any processes are still using Gatsby. Kill each of them with `kill <PID>`
7. Try `gatsby develop` again.
