### ISSUE TITLE
gatsby-plugin-manifest: Some issue (?)

### ISSUE THREAD

**Issue by Isabellarossi** [gatsbyjs/gatsby#27971]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment]
Hello!

Please fill out the issue template :)

**Comment by moonmeister** [comment]
Probably solved by #27951

**Comment by LekoArts** [comment]
I'll close this one as there's no information. Please file a new issue and fill out the issue template if you continue to have issues. Thanks!
