### ISSUE TITLE
[gatsby-plugin-netlify]: Wrong shape for headers

### ISSUE THREAD

**Issue by iiroj** [gatsbyjs/gatsby#2797]
>Error: The "headers" option to gatsby-plugin-netlify is in the wrong shape. Yo u should pass in a object with string keys (representing the paths) and an array of strings as the value (representing the headers). Check your gatsby-config.js.

For whatever reason, lately my generation of Netlify headers has stopped working, while it was working before. This started after updating Node and packages; related commit here:
https://github.com/iiroj/iiro.fi/commit/213268affad60b8fc426e89b1b14060e199012c5

Removing `headers: {...}` from the config works, and there's no problem with `allheaders: [...]`.

For reference, my headers were as follows:
https://github.com/iiroj/iiro.fi/commit/021cdfb17828270af7dd8001ec0a76adabb95655

EDIT: Building my current release on Node 8.6.0 also produces this error, so it's not related directly to Node 8.9.0

**Comment by KyleAMathews** [comment]
Not super familiar with how gatsby-plugin-netlify works. Could you dive into the code a bit to see why things are breaking?

**Comment by ungarida** [comment]
I did an update of my package and I get as well:

> error Plugin gatsby-plugin-netlify returned an error
> Error: The "headers" option to gatsby-plugin-netlify is in the wrong shape. You should pass in a object with string keys (representing the paths) and an array of strings as the value (representing the headers). Check your gatsby-config.  js.

**Comment by iiroj** [comment]
Well, it seems `gatsby-plugin-netlify` doens't receive the headers object correctly:
```
{ '/': 
   [ 'Link: </d.svg>; rel=preload; as=image',
     'Link: </e.svg>; rel=preload; as=image',
     'Link: </gh.svg>; rel=preload; as=image',
     'Link: </gl.svg>; rel=preload; as=image',
     'Link: </l.svg>; rel=preload; as=image',
     'Link: </t.svg>; rel=preload; as=image',
     _PARENT: 'SOURCE' ],
  _PARENT: 'SOURCE' }
```
It fails to this `_PARENT: 'SOURCE'` key val on the last line. I haven't seen anything like this before but I'll keep digging. The plugin uses lodash heavily, so maybe it comes from there.

**Comment by KyleAMathews** [comment]
Ugh that again. There's a PR fixing this at https://github.com/gatsbyjs/gatsby/pull/2812

**Comment by KyleAMathews** [comment]
I'll be merging and releasing it soon

**Comment by KyleAMathews** [comment]
This should be fixed now in the most recent release — would love to hear a report back.

**Comment by iiroj** [comment]
It is again working as expected! Thanks!
