### ISSUE TITLE
gatsby-remark-images: `showCaptions` option does not accept an array of attributes

### ISSUE THREAD

**Issue by marktron** [gatsbyjs/gatsby#27983]
## Description

According to the [documentation](https://www.gatsbyjs.com/plugins/gatsby-remark-images/#options), the `showCaptions` option can accept an array such as `["title", "alt"]` or `["title"]` to determine which attributes to use for an image's caption. Instead, passing an array causes the build to fail.

### Steps to reproduce
Demo repo here: https://github.com/marktron/gatsby-remark-images-bug

In gastby-config.js:
```
…

{
  resolve: `gatsby-remark-images`,
  options: {
    maxWidth: 590,
    showCaptions: ["title", "alt"]
  },
},

…
```

### Expected result

A caption should display beneath the image, like this:
<img width="1552" alt="Screen Shot 2020-11-11 at 9 51 06 PM" src="https://user-images.githubusercontent.com/867615/98889729-78fd5880-2468-11eb-956a-859e87a8cc9c.png">

### Actual result

During the build, it fails with the following error:

```
error Invalid plugin options for "gatsby-remark-images":

- "showCaptions" must be a boolean
```
### Environment
```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.193
    Firefox: 81.0.1
    Safari: 14.0
  npmPackages:
    gatsby: ^2.25.3 => 2.25.3
    gatsby-plugin-sharp: ^2.7.1 => 2.7.1
    gatsby-remark-images: ^3.4.2 => 3.4.2
    gatsby-source-filesystem: ^2.4.2 => 2.4.2
    gatsby-transformer-remark: ^2.9.2 => 2.9.2
  npmGlobalPackages:
    gatsby-cli: 2.12.117
```

**Comment by pieh** [comment]
Thanks for report - I opened https://github.com/gatsbyjs/gatsby/pull/27998 with the fix
