### ISSUE TITLE
When accessing 404 page, there is additional 404 response for page-data.json

### ISSUE THREAD

**Issue by aha-oretama** [gatsbyjs/gatsby#27985]
## Description

When I serve 404 page by adding `/src/pages/404.js` and access non-existing path, the request returns 404 page with 404 http status. This is expected behavior. But there is an additional 404 response for page-data.json.

The practical use is not affected by this, but I hope that there are no additional 404 responses.

### Steps to reproduce

I create sample project to reproduce above.
https://github.com/aha-oretama/gatsby-404

After cloning it, please run the following commands.
```
$ npm i
$ npm run clean
$ npm run build
$ npm run serve
```

Then, please access non-existing path by browser.
For example, acccess http://localhost:9000/hogehoge
Then, you can see the 404 response

1. http://localhost:9000/hogehoge → 404: expected
1. http://localhost:9000/hogehoge/page-data.json → 404: not expected

### Expected result

It's better that `hogehoge/page-data.json` won't return 404 http status.

### Actual result

`hogehoge/page-data.json` returns 404 http status.

### Environment

```

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 12.16.1 - ~/.anyenv/envs/nodenv/versions/12.16.1/bin/node
    npm: 6.13.4 - ~/.anyenv/envs/nodenv/versions/12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.193
    Firefox: 78.0.1
    Safari: 14.0
  npmPackages:
    gatsby: ^2.25.3 => 2.25.3 
  npmGlobalPackages:
    gatsby-cli: 2.12.117

```

**Comment by pieh** [comment]
> But there is an additional 404 response for page-data.json.
> 
> The practical use is not affected by this, but I hope that there are no additional 404 responses.

Just to be clear: do you mean response status or making that request at all?

Both of those have their problems:
- Not making request at all: there will be times when 404 html file is served, but `page-data` exists indicating that the page should be there but for whatever reason (deploy problems, deploy in progress) is not there. So if `page-data` file would exist we would be able to render the page (with delay) even if .html file is not there
- Response status: while we can change `gatsby serve`, this is more in line with what various hostings will do, so it doesn't seem correct to change anything here

**Comment by aha-oretama** [comment]
Both is fine for me. But it might be better to choose `Not making request at all` as far as I read above problems.

Is it possible not to make the request to `paga-data` at all **only in 404 page**?
Because as you wrote, the app will be slower if `page-data` file is not found and this problem is occurred in 404 page in my investigation.
This is maybe because of rooting problems. The built structure is like this.
```
- public
  - 404/index.html
  - page-data
    - 404/page-data.json
    - 404.html/page-data.json
```
If you access `http://localhost:9000/404`, then `http://localhost:9000/404/index.html` and `http://localhost:9000/page-data/404/page-data.json` will be found and return 200 http status. But, when you access `http://localhost:9000/hogehoge`, then `http://localhost:9000/page-data/hogehoge/page-data.json` is not found and return 404 status.
