### ISSUE TITLE
Proxy should not follow redirections

### ISSUE THREAD

**Issue by vhiairrassary** [gatsbyjs/gatsby#28003]
## Description

[Proxy](https://www.gatsbyjs.com/docs/api-proxy/#proxying-api-requests-in-development) used during development should not follow redirections.

#### Details

As Gatsby [uses the "got" package for the proxy](https://github.com/gatsbyjs/gatsby/blob/4ef4bf5fa85e5fc1bacea2a9da58ce0ab6ed56d2/packages/gatsby/src/utils/start-server.ts#L398) without specifying `followRedirect: false`. It means "got" will follow redirects (it is its default behavior, search for `followRedirect` in https://github.com/sindresorhus/got#readme).

### Steps to reproduce

Start a fake HTTP server that is always returning a 301 code (it can be tested with `curl localhost:1501/api/test -v` & `curl localhost:1501/api/test -v -L`):
```bash
trap 'exit 0' INT

while true; do
  echo -e "HTTP/1.1 301 OK\nContent-Length: 0\nLocation: https://httpbin.org/ip\n" | nc -l 127.0.0.1 1501;
done
```

Starting from a fresh Gatsby installation, add the following to `gatsby-config.js`.
```js
proxy: {
    prefix: '/api',
    url: 'http://127.0.0.1:1501'
},
```

Send a request to Gastby development server using `curl localhost:8000/api/test -v`

### Expected result

```
curl localhost:8000/api/test -v
[...]
< HTTP/1.1 301 Moved Permanently
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< content-length: 0
< location: https://httpbin.org/ip
< Date: Thu, 12 Nov 2020 14:26:36 GMT
< Connection: close
```

### Actual result

```
curl localhost:8000/api/test -v
[...]
< HTTP/1.1 200 OK
< X-Powered-By: Express
< access-control-allow-origin: *
< date: Thu, 12 Nov 2020 14:25:17 GMT
< content-type: application/json
< content-length: 31
< connection: close
< server: gunicorn/19.9.0
< access-control-allow-credentials: true
<
{
  "origin": "xx.xx.xxx.xx"
}
```

### Possible fixes
- Workaround: [use a low-level proxy](https://www.gatsbyjs.com/docs/api-proxy/#advanced-proxying) with `developMiddleware` in `gatsby-config.js` by replacing

```js
module.exports = {
  proxy: {
    prefix: '/api',
    url: 'http://localhost:3000'
  }
}
```

by
```js
const proxy = require('http-proxy-middleware'); // version 0.19.1

module.exports = {
  developMiddleware: (app) => {
    app.use(
      '/api/*',
      proxy({
        target: 'http://localhost:3000',
        followRedirects: false
      })
    );
  }
}
```

- Add `followRedirect` to [the "got" options](https://github.com/gatsbyjs/gatsby/blob/4ef4bf5fa85e5fc1bacea2a9da58ce0ab6ed56d2/packages/gatsby/src/utils/start-server.ts#L399) but it is a breaking change ⚠️ (PR: https://github.com/gatsbyjs/gatsby/pull/28005)
- Expose the `followRedirect` options as part of [the proxy configuration block](https://www.gatsbyjs.com/docs/gatsby-config/#proxy) (PR: https://github.com/gatsbyjs/gatsby/pull/28006)

**Comment by wardpeet** [comment]
Could you explain why we shouldn't follow redirects?

**Comment by vhiairrassary** [comment]
@wardpeet we wanted to setup an OAuth2 flow with Google: when the user requests `/server/oauth2` she is redirected to Google. As this request is served by our backend, which is proxified by Gatsby, then instead of receiving the 3xx redirection she receives the OAuth2 content from Google, served by the application's domain.

We don't redirect to Google directly from the JS application for security reasons: when calling `/server/oauth2` the server (Rails) will set the `state` parameter to the redirect URL & store it in the session 🍪 to prevent CSRF attacks during the callback phase.

As a workaround we removed the proxy & SSL configurations from Gatsby and instead we use a local nginx to handle SSL termination & proxy (which is more similar to our production setup).

If someone else wants to achieve a similar setup (you need Gatsby 2.27+ for https://github.com/gatsbyjs/gatsby/pull/27955 fix) then you have to apply to following patch (using something like [patch-package](https://www.npmjs.com/package/patch-package)) to have a different listening port than the one rendered by Gatsby in the assets (more details about the why available at https://github.com/gatsbyjs/gatsby/pull/27955):

```diff
diff --git a/node_modules/gatsby/dist/utils/detect-port-in-use-and-prompt.js b/node_modules/gatsby/dist/utils/detect-port-in-use-and-prompt.js
index 6fc3828..6b481c7 100644
--- a/node_modules/gatsby/dist/utils/detect-port-in-use-and-prompt.js
+++ b/node_modules/gatsby/dist/utils/detect-port-in-use-and-prompt.js
@@ -14,6 +14,11 @@ var _prompts = _interopRequireDefault(require("prompts"));
 const detectPortInUseAndPrompt = async (port) => {
   const detectedPort = await (0, _detectPort.default)(port).catch(err => _reporter.default.panic(err));
 
+  // We know it will work with 0.0.0.0
+  if (port === 443) {
+      return port;
+  }
+
   if (port !== detectedPort) {
     _reporter.default.log(`\nSomething is already running at port ${port}`);
 
diff --git a/node_modules/gatsby/dist/utils/develop-proxy.js b/node_modules/gatsby/dist/utils/develop-proxy.js
index d44eca1..605ca01 100644
--- a/node_modules/gatsby/dist/utils/develop-proxy.js
+++ b/node_modules/gatsby/dist/utils/develop-proxy.js
@@ -82,7 +82,9 @@ const startDevelopProxy = input => {
   server.on(`upgrade`, function (req, socket, head) {
     proxy.ws(req, socket, head);
   });
-  server.listen(input.proxyPort, input.program.host);
+
+  // Bind Gatsby at 127.0.0.1:8000, which is proxied by our nginx in development
+  server.listen(8000, "127.0.0.1");
   return {
     server,
     serveRestartingScreen: () => {
```
