### ISSUE TITLE
Support Directory Components For Pages

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#2800]
It is very common to organise React components into their own directories, separating Container (for data fetch), View (for mapping data to props) and Subcomponents, with an index at the root -
 See [here](https://medium.com/styled-components/component-folder-pattern-ee42df37ec68) and [here](https://github.com/davezuko/react-redux-starter-kit/wiki/Fractal-Project-Structure). A more complex Component like a page particularly benefits from this approach. However there is currently no way to use this approach with Gatsby's pages because the graphQL query will not be executed unless it is in a component directly within the `pages/` dir.

## Attempted Workaround

Assuming a structure like this:

```
- src
  - pages 
      - index.js 
      - HomePage
          - index.js
          - Container.js
          - View.js
          - etc
```

I thought it would be  possible to work around this by forwarding references:

src/pages/index.js
```
import HomePage,{query} from './HomePage

export default HomePage;
export {query};
```

src/pages/HomePage/index.js
```
import Container,{query} from './Container

export default HomePage;
export {query};
```

However although this appears to work at first, even after restarting the server, it breaks if the `.cache` dir is deleted. I now realise you are preprocessing the files for queries. This is why the query has to be inside a file in the `pages/` dir.  However, this isn't consistent - it is possible to extract the view and just leave a query for files in `pages` and `templates`, however trying to extract the view from files in `templates` doesn't work.

So for anyone stumbling across this issue:

- Pages: You must have your graphql queries within files situated in the root of `pages` or they will not be run and your components will receive an undefined data object.
- Templates: You must have your graphql queries within files situated in the root of `templates` or they will not be run and your components will receive an undefined data object.
- Layouts: You must have both your graphql queries and your components situated with a single file in the root of the `layouts` dir.

I think this kind of organisation should be supported straight out of the box or there should at least be an escape hatch or workaround. Could a regex be passed to Gatsby to specify which are page components, which are templates and which are layouts,  rather than hardcoding all the paths? 

See also related #2779.

**Comment by KyleAMathews** [comment]
Gatsby parses all files in the `src` directory (+ our fragments directory) https://github.com/gatsbyjs/gatsby/blob/2dbf4dd299d5507307c3d0c77e93b6ba06d5e4b9/packages/gatsby/src/internal-plugins/query-runner/query-compiler.js#L185

So I'm not sure why you're running into the troubles you are. Page components don't have to be in the pages directory nor do templates/layouts need to be in those directories as well.

Probably what's breaking is each of your other components are being turned into pages automatically. Any JS file in pages will get turned into pages. To get around this, [you can name these sub-components starting with an underscore](https://github.com/gatsbyjs/gatsby/blob/2dbf4dd299d5507307c3d0c77e93b6ba06d5e4b9/packages/gatsby/src/internal-plugins/component-page-creator/validate-path.js) (e.g. `_View.js`).

**Comment by Undistraction** [comment]
I've just pushed a couple of commits for a Gatsby boilerplate I'm working on which clearly show the problem. As soon as the queries are moved away from the files in `pages`, the data object was is no longer passed in to the component. 

[This](https://github.com/Undistraction/gatsby-skeleton/commit/96e865ec97175263b3c2541dce3d5199bd4bc40a) commit moves the components used for the pages into a separate directory (works so far). 

[This](https://github.com/Undistraction/gatsby-skeleton/commit/713415b32e89ee3a509c71a2225ecd7d47bee2fc) commit moves the queries out from the page into separate files (results in errors because no data object is no longer passed in to the page component).

I feel like I've maybe misunderstood something about how Gatsby is handling things. My understanding is that Gatsby preprocesses the files in `templates`, `pages` and `layouts` looking for an exported graphql query. If it finds one it runs the query and passes the results of the query into the component as a `data` prop.

**Comment by KyleAMathews** [comment]
Gatsby processes all files in src for queries.

Queries in page & layout components are run and the data is automatically inserted as a prop.

Regular non-page/layout component queries *aren't* run. For those, you should [export a query fragment](https://github.com/gatsbyjs/gatsby/search?utf8=%E2%9C%93&q=fragment&type=) and then spread the fragment into a page/layout component.

**Comment by Undistraction** [comment]
Thanks for clarifying.

> Queries in page & layout components are run and the data is automatically inserted as a prop.

So in the following file, would you expect `AboutPage` to receive a `data` property, assuming aboutPageQuery is a graphql query?

```
import AboutPage from '../components/AboutPage';
import aboutPageQuery from '../data/queries/aboutPageQuery';

export default AboutPage;

export { aboutPageQuery };
```

If I delete the`.cache` dir and load the about page, I can see `.cache/json/about.json` contains the correct results of the query, but the data object isn't being passed into the `AboutPage` component.

**Comment by KyleAMathews** [comment]
Not entirely sure what's happening. You should dive into https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/query-runner/pages-writer.js and see what's being written out.

Also https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/loader.js to see what's being loaded into the browser

**Comment by Undistraction** [comment]
There seem to be two issues with how Gatsby parses files:

1. `packages/gatsby/src/internal-plugins/query-runner/file-parser.js` only checks the AST for named exports [see here](https://github.com/gatsbyjs/gatsby/blob/d855150dadb91e80b836d2bd5e160cb0b84f5e2a/packages/gatsby/src/internal-plugins/query-runner/file-parser.js#L93), so if the query is in its own file and uses a default export it doesn't find them.

2. If the component in `src/layouts` or `src/pages` doesn't actually contain the graphql query (in other words if instead it imports, then exports a query, as in my example above), Gatsby doesn't associate the query with the component. In the case of Layouts and Pages, this means the query result isn't passed to the component as a data property.

**Comment by KyleAMathews** [comment]
Yes — neither of those come for free — we're parsing files with Babel. Babel only parse a file at a time so any sort of inter-file stitching has to have code for it.

It'd be really useful to have though. I haven't researched how to do this but if this is something you'd be interesting in tackling, supporting these two features would be 💯

**Comment by Undistraction** [comment]
It would definitely be really useful - I don't think this limitation is mentioned anywhere so I think it would be useful to add a section to the docs.  To  be perfectly honest, I think adding support for this is beyond my capabilities. Checking for queries defined in default exports would be easy enough, but I wouldn't know how to start when it comes to parsing out imported files looking for queries. And the first is no use without the second.

Shall I close this and add this as a feature request? I can be explicit about the improvement now.

**Comment by Undistraction** [comment]
Opened as a specific feature request #2827
