### ISSUE TITLE
Build errors when trying to incorporate Popper.js

### ISSUE THREAD

**Issue by nechmads** [gatsbyjs/gatsby#2801]
I'm trying to use Bootstrap that requires JQuery and it requires Popper.js to be on the page.
When I run build I get the following error:

"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `PopperComponent`"

In my /html.js I have the following code:
render() {
    const jquery = (
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" />
    )
    const popper = (
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" />
    )
    const bootstrap = (
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" />
    )
...

return {
...
{jquery}
{popper}
{bootstrap}
...
}

This is the full stack for the error:

- reactProdInvariant.js:29 reactProdInvariant
    ~/react-dom/lib/reactProdInvariant.js:29:1
  
  - instantiateReactComponent.js:72 ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactCompo    nent]
    ~/react-dom/lib/instantiateReactComponent.js:72:1
  
  - ReactCompositeComponent.js:364 ReactCompositeComponentWrapper.performInitialMount
    ~/react-dom/lib/ReactCompositeComponent.js:364:1
  
  - ReactCompositeComponent.js:255 ReactCompositeComponentWrapper.mountComponent
    ~/react-dom/lib/ReactCompositeComponent.js:255:1
  
  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1
  
  - ReactCompositeComponent.js:368 ReactCompositeComponentWrapper.performInitialMount
    ~/react-dom/lib/ReactCompositeComponent.js:368:1
  
  - ReactCompositeComponent.js:255 ReactCompositeComponentWrapper.mountComponent
    ~/react-dom/lib/ReactCompositeComponent.js:255:1
  
  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1
  
  - ReactMultiChild.js:234 ReactDOMComponent.mountChildren
    ~/react-dom/lib/ReactMultiChild.js:234:1
  
  - ReactDOMComponent.js:657 ReactDOMComponent._createContentMarkup
    ~/react-dom/lib/ReactDOMComponent.js:657:1

any help will be super appreciated!

**Comment by KyleAMathews** [comment]
Generally you should rely on webpack imports for adding extra libraries. So install these libraries with npm and then import them into pages where they're needed.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
