### ISSUE TITLE
Since gatsby-plugin-sass@2.4.x it's not possible to use SASS and SCSS together

### ISSUE THREAD

**Issue by nikoladev** [gatsbyjs/gatsby#28042]
## Description

Since `gatsby-plugin-sass@2.4.x` I can't mix SCSS and SASS. I use SCSS in my code, but also depend on [Bulma](https://github.com/jgthms/bulma) (which is written in SASS).

If I only use SCSS it works, and if I only use SASS (Bulma) I need to apply [this solution](https://github.com/gatsbyjs/gatsby/issues/28007#issuecomment-726268375) and then it works. However I can't get them both to work together, while it did work before with `gatsby-plugin-sass@2.3.x` and before.

I have a [minimal reproducible example here](https://github.com/nikoladev/gatsby-plugin-sass-bulma).

### Steps to reproduce

To get the error:

- Clone [this repo](https://github.com/nikoladev/gatsby-plugin-sass-bulma)
- Run `yarn`
- Run `yarn develop`
- It crashes

To prevent the error:

- In `package.json` revert to the previous minor version: `"gatsby-plugin-sass": "2.3.x",`
- Run `yarn`
- Run `yarn develop`
- It works

### Expected result

It should build without errors.

### Actual result

You get this error:

```
error Generating development JavaScript bundle failed


@import "sass/layout/_all"
                         ^
      Expected "{".
   ╷
10 │ @import "sass/layout/_all"
   │                           ^
   ╵
  stdin 10:27  root stylesheet
      in /[...]/node_modules/bulma/bulma.sass (line 10, column 27)
```

**Comment by LekoArts** [comment]
The only thing that changed between `2.3.x` and `2.4.x` is the addition of the plugins validation API which didn't change the behavior of the plugin, see: https://diff.intrinsic.com/gatsby-plugin-sass/2.3.22/2.5.1

So not sure why you'd see that.

**Comment by LekoArts** [comment]
I also don't think that you use Bulma correctly. As we show in the docs (https://www.gatsbyjs.com/docs/bulma/) you'll need to import the file into its own `.scss` file and then import that into the React component (they also do that in their official example: https://github.com/jgthms/bulma-start/blob/master/_sass/main.scss).

Your `import bulma` is incorrect. I did the change above locally and it all works, hence I'll close this as resolved.

**Comment by nikoladev** [comment]
You're right, as soon as I imported Bulma [exactly as described in the Gatsby Bulma docs](https://www.gatsbyjs.com/docs/bulma/) everything worked. Don't know how I overlooked that page.

I guess I was just lucky that my incorrect way of importing worked for a while 🤷‍♀️

Thanks for looking into it and helping out :)
