### ISSUE TITLE
npm watch + gatsby-dev produce errors after updating to latest master

### ISSUE THREAD

**Issue by Swizec** [gatsbyjs/gatsby#2805]
I was trying to implement a bugfix/feature that I started looking into a month ago and ran into some issues after updating my clone of Gatsby to the latest master.

When I run `yarn test` on my clone, it succeeds.

Running `npm run watch`, works without error.

Running `gatsby-dev` in my test site, also works.

But when I run `gatsby develop` to run my test site, it returns missing packages errors from Gatsby. 👇

```
success delete html files from previous builds — 0.015 s
success open and validate gatsby-config.js — 0.004 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success copy gatsby files — 0.017 s
error UNHANDLED EXCEPTION


  Error: Cannot find module 'valid-url'
  
  - module.js:11 require
    internal/module.js:11:18
  
  - create-remote-file-node.js:7 Object.<anonymous>
    [intro-to-react-workshop]/[gatsby-source-filesystem]/create-remote-file-node.js:7:22
  
  - module.js:11 require
    internal/module.js:11:18
  
  - index.js:10 Object.<anonymous>
    [intro-to-react-workshop]/[gatsby-source-filesystem]/index.js:10:32
  
  - module.js:11 require
    internal/module.js:11:18
  
  - gatsby-node.js:2 Object.<anonymous>
    /Users/Swizec/Documents/random-coding/intro-to-react-workshop/gatsby-node.js:2:28
```

I tried nuking my `node_modules` and running `gatsby develop` with and without `yarn install` after nuking, and it didn't help, just changed which particular package it complains about.

What am I doing wrong?

**Comment by KyleAMathews** [comment]
Old yarn.lock? gatsby-dev-cli doesn't install missing dependencies

**Comment by Swizec** [comment]
Tried removing `yarn.lock` and running `yarn install` in my test site.

And that indeed fixed it. Thanks!
Closing.
