### ISSUE TITLE
GraphiQL Explorer doesn't work as described in the docs

### ISSUE THREAD

**Issue by igorradovanov** [gatsbyjs/gatsby#28056]
## Description

The GraphiQL Explorer doesn't seem to work as described in the [docs](https://www.gatsbyjs.com/tutorial/part-five/) (including the tutorial).

Under the **site** segment, I am unable to select the **siteMetadata** fields such as title or description (the checkbox is missing).

### Steps to reproduce

Open http://localhost:8000/___graphql toggle Explorer, go to Site -> siteMetadata->Title (or Description)

### Expected result

The checkbox should appear as in docs (so the field can be seen in the code editor)

### Actual result

The field checkbox is missing, it displays the numerous other checkboxes below the field name. Not sure if this is the bug with the GraphiQL or the docs are outdated due to a new GraphiQL version.

Screenshot:

![explorer](https://user-images.githubusercontent.com/20539903/99156766-ed800380-26c3-11eb-95d2-44a30a68dc62.png)

### Environment

  System:
    OS: Linux 5.4 Linux Mint 20 (Ulyana)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 80.0
  npmPackages:
    gatsby: ^2.25.3 => 2.25.3 
    gatsby-plugin-postcss: ^3.0.4 => 3.0.4 
    gatsby-plugin-typography: ^2.5.13 => 2.5.13 
  npmGlobalPackages:
    gatsby-cli: 2.12.91

**Comment by LekoArts** [comment]
Thank you for opening this!

You are currently filtering for something. The purple items are always the filter for the query. If you look further down you’ll see the entry as a blue text.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
