### ISSUE TITLE
HTML class attribute is inconsistent: present on `/present`, missing on `/`

### ISSUE THREAD

**Issue by xaverfleer** [gatsbyjs/gatsby#28071]
## Description

Gatsby `<Link class="present"></Link>` adds class `present` on `/present`. Gatsby `<Link class="missing"></Link>` adds no class "missing" at `/`.

Classes should be added with `className` in React. The issue only occurs when I use the attribute `class` instead of `className`.

For some reasons the class `present` is added on the path `/present`.

### Steps to reproduce

Add component with <Link class="present"></Link> to a non-index page (for example `src/pages/some-path.js`

Minimal reproduction: https://github.com/xaverfleer/minimal-gatsby-example

### Expected result

No class should exist on the anchor element.

### Actual result

The class `present` is exists on the anchor element.

### Environment

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.198
    Edge: 86.0.622.63
    Firefox: 81.0.1
    Safari: 14.0
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1 
  npmGlobalPackages:
    gatsby-cli: 2.13.1

**Comment by LekoArts** [comment]
Thanks for the report but that’s not something we need to fix as one needs to use className for valid syntax. As long as it doesn’t completely brake stuff it’s fine as linters will catch this.

**Comment by xaverfleer** [comment]
Thank you for responding quickly.

Further thoughts:
 - It is ok for me not to consider this "a bug we need to fix", except
 - Linters, as configured in gatsby-starter-default not catch it.
 - And I would have preferred to close the issue myself, as suggested in the [Triaging documentation](url) "Give issue authors time to close their own issues."
