### ISSUE TITLE
Documentation on how to create a resolver with query filtering

### ISSUE THREAD

**Issue by jasonbiondo** [gatsbyjs/gatsby#28126]
Can someone explain how to create a resolver for something like limiting the amount of images returned in query.  Lets assume you have

node -> images -> src

and I want to do 

node -> images(limit: 2) -> src 

so only 2 images would be queryied via graphql.  How can we create these subfilters? I. assume it's with a resolver but I see no example of this in the docs.

**Comment by pvdz** [comment]
Hi @jasonbiondo . I'm going to convert your issue to a discussion :)
