### ISSUE TITLE
☂ [Umbrella] SSR in Develop

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#28138]
This is an issue for discussing the upcoming SSR in development feature. The coming feature enables SSR in development so certain bugs that previously only show up in builds (like trying to access the `window` object) will now be seen during development which will help speed up fixing them.

Original PR: https://github.com/gatsbyjs/gatsby/pull/27432

## How to test
Run your develop server with the feature enabled and let us know how it goes!

```
GATSBY_EXPERIMENT_DEVJS_LAZY=true gatsby develop
```

**Comment by wardpeet** [comment]
I've tested it on kent c dodds site and I see
https://www.loom.com/share/eaeab772ac554d0f9cb428024dec318f

It didn't show without the flag
