### ISSUE TITLE
gatsby-transform-remark messes up with plain HTML (especially self-closing tags) inside markdown file

### ISSUE THREAD

**Issue by shahbits22** [gatsbyjs/gatsby#28133]
## Description

We are in process of moving  our company's documentation on gatsby platform. We are having difficulties with the existing md files. Some of our markdown files contain plain HTML. I noticed an issue with the self closing anchor tag. It seems gatsby / react creates multiple anchor tags from one.

### Steps to reproduce

Code - https://raw.githubusercontent.com/shahbits22/gatsby-starter-markdown/master/contents/docs/get-started/introduction.md

site - https://musing-mclean-ec664f.netlify.app/docs/get-started/introduction

### Expected result

It should have created only one anchor tag

### Actual result
It creates 3 anchor tags

<img width="1049" alt="Screen Shot 2020-11-16 at 7 33 06 PM" src="https://user-images.githubusercontent.com/8637564/99421404-56d26300-28cc-11eb-8336-515b282550eb.png">

### Environment

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.198
    Edge: 86.0.622.69
    Firefox: 82.0.2
    Safari: 14.0
  npmPackages:
    gatsby: ^2.15.15 => 2.15.15
    gatsby-cli: ^2.7.47 => 2.7.47
    gatsby-image: ^2.2.19 => 2.2.19
    gatsby-plugin-catch-links: ^2.3.15 => 2.3.15
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7
    gatsby-plugin-remove-trailing-slashes: ^2.1.6 => 2.1.6
    gatsby-plugin-sharp: ^2.2.22 => 2.2.22
    gatsby-remark-autolink-headers: ^2.1.10 => 2.1.10
    gatsby-remark-images: ^3.1.22 => 3.1.22
    gatsby-remark-katex: ^3.1.8 => 3.1.8
    gatsby-source-filesystem: ^2.1.22 => 2.1.22
    gatsby-transformer-json: ^2.2.8 => 2.2.8
    gatsby-transformer-remark: ^2.6.22 => 2.6.22
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14
  npmGlobalPackages:
    gatsby-cli: 2.12.99

**Comment by LekoArts** [comment]
Thank you for opening this!

According to the spec: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element
Omitting the end tag (and using a self-closing element) is invalid -- so you'll need to fix your HTML and this isn't a bug on Gatsby's end.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
