### ISSUE TITLE
☂ [Umbrella] Lazy Development JS bundling

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#28137]
This is an umbrella issue for discussing the new feature for lazy JS bundling in development. The [initial PR](https://github.com/gatsbyjs/gatsby/pull/27884) dropped times for bundling by up to 80% on some sites (with possible future improvements that can be made as well). Sites with less JS won't see as dramatic of improvement but all sites will benefit.

## How to test & help out

Try out the feature on your site by running `gatsby develop` with the feature enabled `GATSBY_EXPERIMENTAL_LAZY_DEVJS=true gatsby develop`

Report any errors or other problems you might see.

We'd love also for you to report on how much this improves times for your site.

To make the comparison, run develop on your site with and without this feature running `gatsby clean` before each run.

```
# run 1
gatsby clean
gatsby develop // Make note of the "Building development bundle" time

# run 2
gatsby clean
GATSBY_EXPERIMENTAL_LAZY_DEVJS=true gatsby develop // Again note the time.
```

**Comment by Anmol368** [comment]
This is an umbrella issue for discussing the new feature for lazy JS bundling in development. The initial PR dropped times for bundling by up to 80% on some sites (with possible future improvements that can be made as well).

**Comment by KyleAMathews** [comment]
@Anmol368 did you mean to post this?
