### ISSUE TITLE
[gatsby-source-contentful]: Can't render Rich Text

### ISSUE THREAD

**Issue by gregoralbrecht** [gatsbyjs/gatsby#28164]
## Description

I'm trying to upgrade to v4 of `gatsby-source-contentful` but can't get it to work. I'm querying the rich text like this (unchanged except for the `raw` instead of `json`):

```graphql
blocks {
  ... on ContentfulBlockRichText {
    body {
      raw
    }
  }
}
```

Which worked fine before the upgrade. If I pass `raw` down to the new `renderRichText(raw, {})`, I get an error:

```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at renderRichText (rich-text.js:13)
    at RichText (index.jsx:101)
    at renderWithHooks (react-dom.development.js:14804)
```

Running `JSON.parse(raw)` seems to work perfectly fine, so I've run out of ideas...

### Environment

```
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Shell: 5.7 - /usr/local/bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    gatsby-cli: 2.12.60 => 2.12.60
```

**Comment by raelBernardino** [comment]
I currently have the same issue

**Comment by LekoArts** [comment]
Please comment in the umbrella discussion for this, thanks!
https://github.com/gatsbyjs/gatsby/discussions/28098
