### ISSUE TITLE
Unable to use Gatsby after fresh install with starter project

### ISSUE THREAD

**Issue by mattbesedick** [gatsbyjs/gatsby#28168]
## Description

Error: The result of this StaticQuery could not be fetched.

### Steps to reproduce

Fresh install of gatsby onto WSL2, started a fresh new project using the commands on Gatsby documentation. When I run gatsby develop for the first time, and navigate to localhost:8000, this is the error I have been getting every time. Refreshing the page doesn't fix the issue

### Expected result

Gatsby starter should load with no problems.

### Actual result

Error: The result of this StaticQuery could not be fetched.

### Environment

System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1 
    gatsby-image: ^2.5.0 => 2.5.0 
    gatsby-plugin-manifest: ^2.6.1 => 2.6.1 
    gatsby-plugin-offline: ^3.4.0 => 3.4.0 
    gatsby-plugin-react-helmet: ^3.4.0 => 3.4.0 
    gatsby-plugin-sharp: ^2.8.0 => 2.8.0 
    gatsby-source-filesystem: ^2.5.0 => 2.5.0 
    gatsby-transformer-sharp: ^2.6.0 => 2.6.0 
  npmGlobalPackages:
    gatsby-cli: 2.13.1

**Comment by ascorbic** [comment]
Hi @mattbesedick,
Sorry to hear you're having this issue. Can you confirm that this is with the default starter?

Thanks

**Comment by mattbesedick** [comment]
Yes! Sorry for the late response. It is in fact producing this error with the default starter.

**Comment by mattbesedick** [comment]
Is there any idea why this is currently happening?

**Comment by Xairoo** [comment]
Started with Gatsby a few days ago. Changed the Windows PC, installed Gatsby, cloned the project.
Failed with 2.26.1 & 2.27.1.

Figured out that it was related to a single case sensitive filename.

I could reproduce it with `gatsby-starter-default`

Added `gatsby-plugin-layout`, `i18next`, `i18next-browser-languagedetector` and `react-i18next`.

Demo: https://github.com/Xairoo/my-gatsby-project

Just change `src\components\Layout.js` to `src\components\layout.js` and vice versa.

**Comment by LekoArts** [comment]
Hey, thanks for the issue! I'm consolidating issues that mention the same error into https://github.com/gatsbyjs/gatsby/issues/26563 -- please post your reproduction there. Thanks!
