### ISSUE TITLE
`Incremental Builds` link leads to 404

### ISSUE THREAD

**Issue by Leksat** [gatsbyjs/gatsby#28175]
## Description

https://www.gatsbyjs.com/docs/conditional-page-builds/ links to https://www.gatsbyjs.com/docs/incremental-builds/ (`Incremental Builds` link). If you click the link, there will be 404. Yet if you reload the page, it works.

![Nov-19-2020 13-16-49](https://user-images.githubusercontent.com/989015/99653403-0264ea00-2a6a-11eb-9c50-c2da3e212ffa.gif)

### Steps to reproduce

- go to https://www.gatsbyjs.com/docs/conditional-page-builds/
- click `Incremental Builds` link

### Expected result

I am redirected to https://support.gatsbyjs.com/hc/en-us/articles/360056151214-Incremental-Builds (I guess)

### Actual result

I see 404

### Environment

Internet :)

I ensured I can reproduce the issue in the Guest profile of latest Chrome.

**Comment by KKVANONYMOUS** [comment]
@LekoArts I would like to work on this issue
