### ISSUE TITLE
Object.entries(...).flatMap is not a function - trouble when trying to use postcss + tailwind + purgecss

### ISSUE THREAD

**Issue by waylonrobert** [gatsbyjs/gatsby#28173]
## Description

I'm trying to use Tailwind CSS, following the Gatsby docs. I'm unable to get the site to run. 

### Steps to reproduce

1. Clone https://github.com/waylonrobert/gatsby-tailwind-bug
2. Run `gatsby develop`

### Expected result

The site should build and be able to use Tailwind CSS.

### Actual result

I get an error message during build:

```
Generating development JavaScript bundle failed

Object.entries(...).flatMap is not a function

File: src/styles/styles.css
```

### Environment

  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.22.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/opt/node@10/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 71.0
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1 
    gatsby-plugin-postcss: ^3.1.0 => 3.1.0 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.95

**Comment by LekoArts** [comment]
Thank you for opening this!

Please see https://github.com/tailwindlabs/tailwindcss/issues/2804

TailwindCSS 2 requires Node 12, you're using Node 10

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
