### ISSUE TITLE
using `@reach/router` links with query on demand breaks navigation

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#28183]
If someone uses Reach router Link component directly (vs. our Link from gatsby-link) - they won't load the page on demand. The reason is that in this case they bypass our page loading mechanism.

Using `@reach/router` links result in navigating to 404 page even when page actually does exist. Refreshing the browser shows the correct page, but this is awful interaction.

For now the workaround is swapping from

```
import { Link } from "@reach/router"
```

to

```
import { Link } from "gatsby"
```

But this might not be feasible for everyone ( there might be reason user chose to use `@reach/router` Link over `gatsby-link`, so this needs to be fixed.

**Comment by jablonski** [comment]
This seems to be related:

https://github.com/gatsbyjs/gatsby/issues/27196

**Comment by pieh** [comment]
Ah, that's good find, I wasn't aware that this issue was actually present in non-query on demand mode to same extent. I will close this issue in favour of #27196 which was original issue.

**Comment by daiky00** [comment]
any news on this @pieh
