### ISSUE TITLE
Remote debugging with android device - CORS error

### ISSUE THREAD

**Issue by t2ca** [gatsbyjs/gatsby#28189]
Im getting the following error on a clients website only while connected via usb to my mobile phone.

Im using the chrome dev debugging tool as shown here https://developers.google.com/web/tools/chrome-devtools/remote-debugging

However, I do not see this error while browsing the same website on my computer. The website seems to load fine without any noticeable issues so i'm not sure if this error is a problem.

`Access to fetch at 'https://www.CLIENTSWEBSITE.com/page-data/app-data.json' (redirected from 'https://CLIENTSWEBSITE.netlify.app/page-data/app-data.json') from origin 'https://CLIENTSWEBSITE.netlify.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by vladar** [comment]
Hey @t2ca 👋 

Looks like it is a redirect issue. You open a website deployed to Netlify (`https://CLIENTSWEBSITE.netlify.app`) but it attempts to load page data from a different domain: `https://www.CLIENTSWEBSITE.com`. This can happen if you have redirects set up in your Netlify deployment. In this case - you should also make the main URL: `https://CLIENTSWEBSITE.netlify.app` to redirect to `https://www.CLIENTSWEBSITE.com` for consistency.

Or maybe it is already set and it's just a browser cache issue - try clearing all caches and reloading `https://CLIENTSWEBSITE.netlify.app` in your browser.

As stated, this is slightly tangential to Gatsby, and it seems like we’ve provided enough information to make an informed decision.

If this is not the case, or if we can help further -- please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby :muscle:
