### ISSUE TITLE
Gatsby-Image Returns Original Size in Srcset even when breakpoints are added

### ISSUE THREAD

**Issue by jasonbiondo** [gatsbyjs/gatsby#28196]
I have the following query and I would thing srcsetbreakpoints means that only the 250px and 500px image would load in the srcset but that's not the case.  The original image size is also returned which is causing me to serve images that are too large.  Is there a way to prevent that from happening?

```
localFile {
                    childImageSharp {
                      fluid(maxWidth: 500, srcSetBreakpoints: [250, 500]) {
                        aspectRatio
                        tracedSVG
                        sizes
                        src
                        srcSet
                        srcWebp
                        srcSetWebp
                      }
                    }
                  }
```

This is the graphql output

![image](https://user-images.githubusercontent.com/1186147/99749429-8c35a700-2aac-11eb-92c9-a1ad8b166e92.png)

Is seems like this has been a bug for a very long time which leads to heavy load on all sites that use gatsby-image: https://github.com/gatsbyjs/gatsby/issues/5516

**Comment by wardpeet** [comment]
@jasonbiondo Currently, we always add the original size to the fluid query. This was added while back, there is no way to negate this except removing it form the string manually...

I suggest moving to https://github.com/gatsbyjs/gatsby/discussions/27950 which will negate this problem

**Comment by vladar** [comment]
Thank you for opening this, @jasonbiondo 

We're marking this issue as answered and closing it for now but please feel free to comment if you would like to continue this discussion.

The suggested solution is to switch to the new `gatsby-plugin-image`. Thanks! 💜
