### ISSUE TITLE
gatsby-plugin-manifest - Build sometimes doesn't complete

### ISSUE THREAD

**Issue by markledwich2** [gatsbyjs/gatsby#28194]
## Description

When I use gatsby-plugin-manifest on my site, the build will usually fail on my Windows laptop. A few relevant things
- It will often work the next build
- It always works when building on netlify

It gets stuck at this point and never completes:
![gatsby-plugin-manifest-bug](https://user-images.githubusercontent.com/17095341/99734693-fa12ba80-2b0e-11eb-9a0c-bc2a762e6515.gif)

### Steps to reproduce
Build the following site (purely npm dependencies) https://github.com/markledwich2/TransparencyTube

You will probably need to run windows to reproduce.
```  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Chrome: 87.0.4280.66
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.69)
  npmPackages:
    gatsby: ^2.27.0 => 2.27.0
    gatsby-image: ^2.6.0 => 2.6.0
    gatsby-plugin-google-gtag: ^2.3.0 => 2.3.0
    gatsby-plugin-manifest: ^2.7.0 => 2.7.0
    gatsby-plugin-offline: ^3.5.0 => 3.5.0
    gatsby-plugin-react-helmet: ^3.5.0 => 3.5.0
    gatsby-plugin-sharp: ^2.9.0 => 2.9.0
    gatsby-plugin-styled-components: ^3.5.0 => 3.5.0
    gatsby-plugin-ts: ^2.7.1 => 2.7.1
    gatsby-source-filesystem: ^2.6.0 => 2.6.0
    gatsby-transformer-sharp: ^2.7.0 => 2.7.0
  npmGlobalPackages:
    gatsby-cli: 2.12.111
```

**Comment by vladar** [comment]
Thanks for opening this @markledwich2 

I definitely can reproduce this with your site on Windows. Is it a new thing? Or the same occurs with older versions of the plugin as well?

**Comment by markledwich2** [comment]
From memory, the problem has existed since I added the plugin about a month
or so ago with the latest version at the time. I wasn't using it before
that.

**Comment by vladar** [comment]
Also, pretty hard to reproduce - I could reproduce it twice but now it works almost every time.

**Comment by ediblecode** [comment]
Is this the same as, or at least related to #25216?

**Comment by vladar** [comment]
@ediblecode You are right! This is the same issue. Let's track it there. 

@markledwich2 Closing this one as a duplicate. Thanks for reporting and for the repro! 💜
