### ISSUE TITLE
Cryptic Gatsby CLI update message

### ISSUE THREAD

**Issue by nina-py** [gatsbyjs/gatsby#28201]
## Description

Every now and then Gatsby CLI notifies me that a more recent version is available. The update message that I get lacks the necessary information to upgrade the tool.

### Steps to reproduce

I am not sure how to reproduce this. Install a previous version of Gatsby CLI perhaps (any of the minor updates released in the last couple of months) and wait until it prompts the user to update?

### Expected result

Gatsby CLI tells me which command to run to update it. Showing the current locally installed and latest available versions would also be helpful - at the moment I see a template rather than the actual data. 

### Actual result

Seeing this:

```bash
   ╭──────────────────────────────────────────────────────────╮
   │                                                          │
   │   Update available {currentVersion} → {latestVersion}    │
   │              Run {updateCommand} to update               │
   │                                                          │
   ╰──────────────────────────────────────────────────────────╯
```

### Environment

  System:
    OS: Linux 5.9 Debian GNU/Linux bullseye/sid
    CPU: (12) x64 AMD Ryzen 5 PRO 4650U with Radeon Graphics
    Shell: 5.1.0 - /bin/bash
  Binaries:
    Node: 14.15.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
  Browsers:
    Chrome: 87.0.4280.66
    Firefox: 78.3.0esr
  npmGlobalPackages:
    gatsby-cli: 2.12.111

**Comment by vladar** [comment]
This is probably some upstream bug in [`update-notifier`](https://github.com/yeoman/update-notifier) package. We simply call it here:

https://github.com/gatsbyjs/gatsby/blob/fe18a18812276c19c2bef654f08039f1037113f7/packages/gatsby-cli/src/index.ts#L23-L24

And then it outputs the actual message somewhere after these lines:
https://github.com/yeoman/update-notifier/blob/da7c4647014a66c719ee41e9e253ea6fb9959707/index.js#L139-L143

So nothing fancy on `gatsby` side. I think it makes sense to report in `update-notifier` repo?

**Comment by nina-py** [comment]
Hi @vladar, thank you for the clarification. I've been able to reproduce it outside of Gatsby and did as you suggested - opened an issue in the `update-notifier` repo.

**Comment by nina-py** [comment]
@vladar, the upstream bug has apparently been fixed already in version 5: https://github.com/yeoman/update-notifier/releases/tag/v5.0.1, the latest Gatsby I've just updated to is using 4.1.3, so it looks like all that is needed is to update the dependency?

**Comment by vladar** [comment]
Yeah, I've read through the changelog and the only breaking thing is bumping the minimum node version to 10. Gatsby already requires 10+ so bump should be safe enough. A pull request is welcome! And thanks for the report 💜

**Comment by nina-py** [comment]
Thank you for making me feel welcome @vladar! PR done :).
