### ISSUE TITLE
Ignored custom PostCSS config when building site

### ISSUE THREAD

**Issue by fpoumian** [gatsbyjs/gatsby#2823]
I am trying to integrate a custom configuration for PostCSS in Webpack that includes both customProperties and customMedia, like so:

```js
// gatsby-node.js
exports.modifyWebpackConfig = ({ config, stage }) => {

  const features = {
    customProperties: {
      variables: {
        mainColor: 'blue',
        maxWidth: '43.5rem',
        accentColor: '#102b40',
        accentColorHover: '#009998',
        darkestGray: '#222326',
        darkGray: '#62646c',
        neutralGray: '#b2b2b2',
        lightGray: '#f6f6f6',
        lightestGray: '#f9f9f9',
        colorPrimary: '#373737',
        colorPrimaryDark: '#373737',
        colorSecondaryDark: '#080808',
        colorSecondary: '#080808',
        colorNeutralDark: '#111',
        colorNeutral: '#8C8D91',
        colorNeutralLight: '#FBFCFC',
        colorText: '#555',
        mainFontFamily: '"Varela Round", Arial, Sans-Serif',
        altFontFamily: '"Montserrat", Arial, Sans-Serif',
        contentFontFamily: '"Noto Serif","Times New Roman",Serif',
        contentFontSize: '1rem',
        contentLineHeight: '2rem',
        titleBaseFontSize: '2rem',
        titleBaseLineHeight: 'normal',
        excerptBaseFontSize: '1.1rem',
      },
    },
    customMedia: {
      extensions: {
        '--mobile-s': '(min-width: 320px)',
        '--mobile-m': '(min-width: 480px)',
        '--tablet': '(min-width: 768px)',
        '--laptop': '(min-width: 992px)',
        '--laptop-l': '(min-width: 1200px)',
        '--4K': '(min-width: 2560px)',
      },
    },
  }

  config.merge({
    postcss: [
      require(`postcss-cssnext`)({
        browsers: 'last 2 versions',
        features: features,
      }),
    ],
  })

  return config
}
```

For some reason this works perfectly in development mode, but when I try to build the site the resulting styles in the site get very messed up. Some of the CSS Modules seem to work, but many don't, especially the ones that depend on the customMedia queries, so I'm guessing something must be wrong with my webpack config.

 Also, when I previewed the site I noticed that the CSS rules are still being inlined like in Development mode, instead of using a separate stylesheet. However, the public folder does seem to contain the stylesheets...which is kind of confusing. 

Any idea of why this might be happening? I've been trying to fix this for a couple of hours now without any success :(

Thanks in advance

**Comment by ooloth** [comment]
@fpoumian Did you get this working in the end? I need to customize the postcss configuration as well (adding Tailwind.css, in my case) and I’d love to know what method worked for you.

**Comment by chris-pearce** [comment]
I am also experiencing this 🙁. I.e., my PostCSS config works fine for `gatsby dev` but for `gatsby build` certain things simply don't work.

The main culprit for me is the `postcss-cssnext` → `features` config. For reference here's where this is defined in Gatsby's [`webpack.config.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js):

* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L438
* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L464-L466

**My config:**

```js
// gatsby-node.js
exports.modifyWebpackConfig = require('./config/webpack.config');
```

```js
// webpack.config.js
const webpack = require('webpack');
const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');

const paths = require('./paths');
const postCSSConfig = require('./postcss.config');
const svgConfig = require('./svg.config');

module.exports = ({ config }) => {
  config.merge({
    resolve: {
      modulesDirectories: [paths.root, 'node_modules'],
      extensions: ['', '.js', '.jsx', '.json'],
    },
    postcss(wp) {
      return postCSSConfig(wp);
    },
    plugins: [
      new webpack.ProvidePlugin({
        React: 'react',
      }),
    ],
  });

  config.loader('svg', {
    test: /\.svg$/,
    loader: `svgo-loader?${svgConfig}`,
  });

  return config;
};
```

```js
// postcss.config.js
const postcssImport = require('postcss-import');
const postcssNext = require('postcss-cssnext');
const postcssBrowserReporter = require('postcss-browser-reporter');
const postcssReporter = require('postcss-reporter');

const tokens = require('./../src/constants/tokens.json');

module.exports = wp => [
  postcssImport({
    addDependencyTo: wp,
  }),
  postcssNext({
    browsers: ['> 1%', 'not IE 11'],
    features: {
      customProperties: {
        variables: tokens,
        warnings: true,
      },
      filter: false,
    },
  }),
  postcssBrowserReporter,
  postcssReporter,
];
```

This part of my `postcss.config.js` config seems to be ignored, or just doesn't work `¯\_(ツ)_/¯`, when running `gatsby build`:

```js
features: {
  customProperties: {
    variables: tokens,
    warnings: true,
  },
  filter: false,
}
```

**Some examples of the issues:**

My CSS custom properties don't get compiled when looking in: `public/styles.css`, e.g.:

```css
font-size: calc((var(--root-unit) / 16 * 1rem) + 2px);
```

And my `filter: false` rule (removing inline SVG via `filter: url()`) isn't applied, e.g.:

```css
.c-logo:focus img,
.c-logo:hover img {
    filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feComponentTransfer color-interpolation-filters="sRGB"><feFuncA type="table" tableValues="0 0.8" /></feComponentTransfer></filter></svg>#filter');
    -webkit-filter: opacity(80%);
    filter: opacity(80%)
}
```

When inspecting the CSS via Chrome's dev tools when running my site locally (via `gatsby dev`) everything works fine, e.g.:

<img width="221" alt="screen shot 2018-04-28 at 6 06 08 pm" src="https://user-images.githubusercontent.com/1342772/39393964-e1f22dec-4b0e-11e8-8595-768ef1fe0f75.png">

<img width="356" alt="screen shot 2018-04-28 at 6 12 48 pm" src="https://user-images.githubusercontent.com/1342772/39394040-20b8ff5a-4b10-11e8-80bf-3f23dacce552.png">

I've been messing around with these issues for ages but everything I try doesn't work. Feels like configuring PostCSS is a tad buggy.
