### ISSUE TITLE
styled-components theme causing errors in build but not in development

### ISSUE THREAD

**Issue by meaagan** [gatsbyjs/gatsby#28250]
## Description

When I use my gatsby site in development it loads everything perfectly, but when I do gatsby build it gives me this error:

`WebpackError: TypeError: Cannot read property 'xs' of undefined`

which refers to:

```
  @media (min-width: ${props => props.theme.screen.xs}) {
                                                          ^
     max-width: 540px;
  }
```

...and if I replace that one instance of using the theme, it finds the next time I use prop => props.theme and gives me the same error. 

### Steps to reproduce

Here is the project in question: https://github.com/meaagan/avocado
Minimum repro: https://github.com/meaagan/bug-repro

Clone, run gatsby build to see error, gatsby develop to see it locally.

### Expected result

Build version should be the same as the development version

### Actual result

Development version works fine, the theme and styled-components work perfectly, but when I build version doesn't work.

### Environment

  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 10.22.1 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.6 - /usr/bin/npm
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1 
    gatsby-background-image: ^1.2.0 => 1.2.0 
    gatsby-image: ^2.5.0 => 2.5.0 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.6.0 => 2.6.0 
    gatsby-plugin-offline: ^3.4.0 => 3.4.0 
    gatsby-plugin-react-helmet: ^3.4.0 => 3.4.0 
    gatsby-plugin-react-i18next: 0.0.27 => 0.0.27 
    gatsby-plugin-sharp: ^2.8.0 => 2.8.0 
    gatsby-plugin-styled-components: ^3.3.2 => 3.3.2 
    gatsby-source-filesystem: ^2.5.0 => 2.5.0 
    gatsby-source-fontawesome: 0.0.1 => 0.0.1 
    gatsby-source-instagram: ^0.9.0 => 0.9.0 
    gatsby-transformer-sharp: ^2.6.0 => 2.6.0

gatsby-config:
    {
      resolve: `gatsby-plugin-react-i18next`,
      options: {
        path: `${__dirname}/locales`,
        languages: [`en`, `fr`],
        defaultLanguage: `en`,
        i18nextOptions: {
          interpolation: {
            escapeValue: false // not needed for react as it escapes by default
          },
          keySeparator: false,
          nsSeparator: false
        },
      }
    },
    {
      resolve: `gatsby-plugin-google-fonts`,
      options: {
        fonts: [`Poppins\:300,500,700`],
      },
    },
    {
      resolve: `gatsby-source-instagram`,
      options: {
        username: `**********`,
      },
    },
    {
      resolve: `gatsby-plugin-alias-imports`,
      options: {
        alias: {
          "@src": "src",
          "@components": "src/components",
          "@pages": "src/pages",
          "@images": "src/images",
          "@styles": "src/styles",
        },
        extensions: [
          "js",
        ],
      }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages/`,
      },
    },
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-source-fontawesome`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Avocado Sushi du Village`,
        short_name: `Avocado`,
        start_url: `/`,
        background_color: `#222222`,
        theme_color: `#a1a1a1`,
        display: `minimal-ui`,
        icon: `src/static/wavelogo.png`,
      },
    },
    `gatsby-plugin-styled-components`,
    `gatsby-plugin-offline`

**Comment by sidharthachatterjee** [comment]
Hi @meaagan 

We don't run SSR in development (when you run `gatsby develop`). `gatsby build` however _does_ run SSR and this might be why you don't see the error in development but see it during build. This typically means that some code depends on a browser runtime environment. I haven't dived deep into you repository to be able to point out just where that is but please do ensure that all code is SSR friendly. 

Let me know if that helps or if you have any other questions! Cheers
