### ISSUE TITLE
SASS plugin config "importLoaders: 2" breaks my build

### ISSUE THREAD

**Issue by sapkra** [gatsbyjs/gatsby#28278]
## Description

I'm using the `gatsby-plugin-sass` together with a postcss plugin which appends my css classes with a global one. The problem is that I have already built another package in my monorepo that already has these classes applied. Because  I can not configure `importLoaders` I cannot stop the plugin for applying a the class a second time because it resolves the `@my/package/dist/style.css` import.

### Expected result

`importLoaders` should be configurable

**Comment by LekoArts** [comment]
Can you please provide more information on what the expected result should be, how you'd propose to achieve it and what the risks are?

**Comment by ascorbic** [comment]
Hi. I'm going to close this now, as we can't do much to help without more information. If you can provide more details then please do open a new issue.

**Comment by sapkra** [comment]
@ascorbic @LekoArts Sorry, I had not time to provide more information.

https://github.com/gatsbyjs/gatsby/blob/ac3759932c582663999aa4384e8e38f9935d7f29/packages/gatsby-plugin-sass/src/gatsby-node.js#L32

This line should be changed to:

```typescript
loaders.css({ importLoaders: 2, ...cssLoaderOptions }),
```

Temporarily I had to set `importLoaders: 2` for all my packages. But it's not the right way in my opinion.

**Comment by hendis85** [comment]
> ## Description
> I'm using the `gatsby-plugin-sass` together with a postcss plugin which appends my css classes with a global one. The problem is that I have already built another package in my monorepo that already has these classes applied. Because I can not configure `importLoaders` I cannot stop the plugin for applying a the class a second time because it resolves the `@my/package/dist/style.css` import.
> 
> ### Expected result
> `importLoaders` should be configurable

#28683

**Comment by LekoArts** [comment]
Please give `gatsby-plugin-sass@3.0.0-next.2` at try :)
