### ISSUE TITLE
Upgrade workbox to v5 in gatsby-plugin-offline

### ISSUE THREAD

**Issue by kije** [gatsbyjs/gatsby#28287]
## Description

gatsby-plugin-offline currently uses workbox v4, which is outdated and should be updated to the latest v5 version

**Comment by LekoArts** [comment]
Feel free to send in a PR upgrading it and laying out if/how breaking changes would affect the plugin :)

**Comment by nategiraudeau** [comment]
@LekoArts an I work on this issue?

**Comment by kije** [comment]
@LekoArts sorry for the inactivity here. I finally found some time to investigate this, and I prepared a PR that upgrades the workbox version to the latest version (v6). 
The upgrade required some changes to the "architecture" of the plugin. I outlined them in the PR.

**Comment by RectoVersoDev** [comment]
Hi everyone, any update on this ? The bot closed the issue but workbox version is still 4.3.1 (published 4 years ago!).

It would be really cool to use the latest version of workbox in the plugin.
