### ISSUE TITLE
Gatsby Develop command generates an Error

### ISSUE THREAD

**Issue by rahmed7331** [gatsbyjs/gatsby#28293]
I have just started to learn Gatsby and created a new project with only the gatsby default files using git bash command line. When I run 'gatsby develop' to see the current UI of my project, I keep getting an error that I can't fix. Please help:

Error: ENOENT: no such file or directory, open 'C:\users\[my_username]\Documents\chrono\my_first_gatsby\.cache\json\_using-typescript_.json'

### Steps to reproduce

Open Git Bash
run 'cd [my gatsby project name]'
run 'gatsby develop'

### Expected result
It provides a link: http://localhost:8000/ >> I should be able to view gatsby-starter-default in the browser using this link. But due to the error, that doesn't work.

### Actual result
Error: ENOENT: no such file or directory, open 'C:\users\[my_username]\Documents\chrono\my_first_gatsby\.cache\json\_using-typescript_.json'

### Environment

 System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  Binaries:
    Node: 13.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/ahmed/.windows-build-tools/python27/python
  Browsers:
    Chrome: 86.0.4240.198
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.27.3 => 2.27.3
    gatsby-image: ^2.6.0 => 2.6.0
    gatsby-plugin-manifest: ^2.7.0 => 2.7.0
    gatsby-plugin-offline: ^3.5.0 => 3.5.0
    gatsby-plugin-react-helmet: ^3.5.0 => 3.5.0
    gatsby-plugin-sharp: ^2.9.0 => 2.9.0
    gatsby-source-filesystem: ^2.6.1 => 2.6.1
    gatsby-transformer-sharp: ^2.7.0 => 2.7.0
  npmGlobalPackages:
    gatsby-cli: 2.14.1

**Comment by LekoArts** [comment]
Hi! Can you please give more information on your local setup? Is this only occurring with Gatsby or also other npm packages? Can you give clearer reproduction steps please?

Also, do you use WSL (similar issue: https://github.com/gatsbyjs/gatsby/issues/21879#issuecomment-595154309)?

**Comment by rahmed7331** [comment]
Hi, apologies for the missing info as I am a brand new gatsby dev. 

**Can you please give more information on your local setup?**
I provided a screenshot of my systems info below: please let me know what other info you may require for my local setup
![image](https://user-images.githubusercontent.com/24552861/100681970-f408af00-3342-11eb-8289-3316913997ea.png)

**Is this only occurring with Gatsby or also other npm packages?**
Only happening with gatsby

**Can you give clearer reproduction steps please?**
Yes. I was simply following this tutorial (Link: https://www.michaeluloth.com/starting-a-new-gatsby-project)
Then got stuck in the final step. Here is a written list of the steps. 

**Steps I followed:**
1. Open Git bash
2. Run '$ npm install --global gatsby-cli'
3. Run '$ gatsby --version' (this verified that I have the latest gatsby version)
4. Run '$ cd [directory name]'
5. Run '$ gatsby new my_first_gatsby' (created a brand new gatsby default starter-project)
6. Run '$ cd my_first_gatsby'
7. Run '$ gatsby develop (expecting a link to gatsby's live local development server but it produces the above error.)

**Also, do you use WSL**
No I don't.

**Comment by rahmed7331** [comment]
Click [HERE](https://docs.google.com/document/d/1P0u3bAGAiUM2DAFoX-tRkieMUtP5ACqdZkRlsgwF8O8/edit?usp=sharing) to see the complete Response after running the 'gatsby develop' command:

**Comment by ascorbic** [comment]
This issue seems to be related to conflicts in casing. See the different between `C:\users` and `C:\Users` Can you share a link to the repo and/or your gatsby-config. Thanks.

**Comment by rahmed7331** [comment]
Hi ascorbic, You are awesome. It looks like all I had to do was change my initial setting directory command from C:\users to C:\Users. And it worked. Thanks, again. bud.

**Comment by rahmed7331** [comment]
The issue was casing.
