### ISSUE TITLE
Gatsby build is giving unexpected error comparing with development mode

### ISSUE THREAD

**Issue by wangsongiam** [gatsbyjs/gatsby#2830]
Hi guys, I was executing `gatsby build` and got undefined from a graphql queried data, which I have never encountered in development mode. I double checked the graphql page in development mode only seeing normal behaviors. I also logged out the `undefined` variable and it's not undefined actually. Any idea?

Gatsby version:   "gatsby": "^1.9.22"
Node: 6.11.5

##### error log
```
   8 |   render() {
   9 |     console.log(this.props)
> 10 |     const posts = this.props.data.allMarkdownRemark.edges
     |                                   ^
  11 |     const title = this.props.data.site.siteMetadata.title
  12 |     const postLinks = posts.map(post => {
  13 |       return (


  WebpackError: Cannot read property 'allMarkdownRemark' of undefined

  - tag-page.js:10 TagRoute.render
    src/templates/tag-page.js:10:35

  - preact-compat.js:484 callMethod
    ~/preact-compat/dist/preact-compat.js:484:1

  - preact-compat.js:495 TagRoute.render
    ~/preact-compat/dist/preact-compat.js:495:1

  - index.js:153 renderToString

```

<img width="257" alt="screen shot 2017-11-07 at 10 45 50 am" src="https://user-images.githubusercontent.com/19645990/32502536-0094f8f8-c3a9-11e7-89f8-e0c6156dbd09.png">

by the way, this issue only happened in the `./src/templates/tag-page.js`, not getting other querying issue from other files

**Comment by KyleAMathews** [comment]
Hard to say :-( perhaps try upgrading Gatsby to the latest version and trying again?

**Comment by MaralS** [comment]
@wangsongiam I have the same issue but it markdownRemark of undefined. I tried to do yarn upgrade gatsby@latest, delete `./cache` and `/public` folder but it didn't work

Similar issue [#3751](https://github.com/gatsbyjs/gatsby/issues/3751)

**Comment by Zuul86** [comment]
I am getting this error as well when running in dev.  I edit the markdown, the hot reload kicks in and the data prop is undefined.

gatsby 1.9.204,
gatsby-transformer-remark 1.7.25
gatsby-source-filesystem 1.5.21

**Comment by KyleAMathews** [comment]
@Zuul86 can you try upgrading to the latest versions of packages?

**Comment by Zuul86** [comment]
That seems to have resolved my issue.  Thanks.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
