### ISSUE TITLE
Gatsby CLI dependency (yargs ^15.4.1) has a high severity vulnerability

### ISSUE THREAD

**Issue by arielperez82** [gatsbyjs/gatsby#28315]
Gatsby CLI is currently pulling in yargs ^15.4.1 which depends on a version of y18n that has a [Prototype Pollution](https://app.snyk.io/vuln/SNYK-JS-Y18N-1021887) vulnerability.

This is resulting in Gatsby CLI being blocked by my company's automatic vulnerability scanners.

yargs has remediated the issue in 16.1.1.

**Comment by LekoArts** [comment]
Hi! Thanks for the issue!

We'd be happy to receive a PR upgrading it when the breaking changes made in the release don't affect us. If they do, we sadly can't just upgrade. As a workaround you can use yarn's `resolutions` feature to force a higher version.

**Comment by nategiraudeau** [comment]
Can I work on this issue?

**Comment by arielperez82** [comment]
It seems the PR @nategiraudeau submitted was closed as tests were failing thus, this is still an issue.
