### ISSUE TITLE
Gatsby Plugin Manifest - Auto Generate Icons with Maskable and Non-Maskable Icon 

### ISSUE THREAD

**Issue by jasonbiondo** [gatsbyjs/gatsby#28350]
In the Gatsby plugin manifest only one icon can be set.  I either have to set my maskable icon or my apple touch icon and then it generates the other icons based on that one predefined.  I should be able to apply both to the plugin and have it generate all of the maskable and apple touch icons that are non maskable.  This is an issue because if you supply a maskable icon as the resource it makes your favicon small and will make your icons smaller on IOs devices.  

Also the plugin advises that we use purpose "any maskable" but in the documentation you can clearly see why this is not optimal: https://web.dev/maskable-icon/

**Comment by LekoArts** [comment]
Thank you for opening this!

You should use the [manual configuration](https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/#manual-mode-configuration) if you need more control over the individual entries in the "icons" array. The README isn't advising something there, it's just an example.

I've opened https://github.com/gatsbyjs/gatsby/pull/28363 to add the resource to the README.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by jasonbiondo** [comment]
The manual config doesn’t work. When I reference paths it throws errors. 

Jason Biondo

**Comment by KesleyDavid** [comment]
> The manual config doesn’t work. When I reference paths it throws errors. Jason Biondo
> […](#)
> On Nov 30, 2020, at 4:52 AM, Lennart ***@***.***> wrote: ﻿ Thank you for opening this! You should use the manual configuration if you need more control over the individual entries in the "icons" array. The README isn't advising something there, it's just an example. I've opened #28363 to add the resource to the README. We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our communities if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I added it to my gatsby-config and it worked perfectly:

```js
icon_options: {
    // For all the options available,
    // please see the section "Additional Resources" below.
    purpose: `any maskable`,
  },
```

**Comment by jomarcardoso** [comment]
I can't put 2 icons with the same size but with different purposes. Please read again the purpose of the issue. If possible the component make the padding for us. https://maskable.app/
