### ISSUE TITLE
pathprefix with dot always adds slash before

### ISSUE THREAD

**Issue by themre** [gatsbyjs/gatsby#28353]
## Description

I want to have relative path prefix for all my resources, but path-prefix config adds always slash before everything

### Steps to reproduce

add `pathPrefix: '.'` into gatsby-config.js

### Expected result

index.html should have resources started as `script src="./component---src-pages-index...`

### Actual result

index.html has `script src="/./component---src-pages-index`

### Environment

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.423.0
  npmPackages:
    gatsby: 2.27.0 => 2.27.0 
    gatsby-image: 2.6.0 => 2.6.0 
    gatsby-plugin-eslint: 2.0.8 => 2.0.8 
    gatsby-plugin-manifest: 2.7.0 => 2.7.0 
    gatsby-plugin-offline: 3.5.0 => 3.5.0 
    gatsby-plugin-postcss: 3.2.0 => 3.2.0 
    gatsby-plugin-purgecss: 5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: 3.5.0 => 3.5.0 
    gatsby-plugin-sharp: 2.9.0 => 2.9.0 
    gatsby-plugin-typescript: 2.7.0 => 2.7.0 
    gatsby-source-filesystem: 2.6.1 => 2.6.1 
    gatsby-transformer-sharp: 2.7.0 => 2.7.0

**Comment by DSchau** [comment]
@themre can you clarify this use case?

> *I want to have relative path prefix for all my resources*, but path-prefix config adds always slash before everything

Why? What are you trying to achieve?

**Comment by themre** [comment]
Hey @DSchau. I want to share in same repo code with electron app. And when creating bundle , electron reads from file system and all links are broken. I'm searching for similar thing here as crate react app has with `homepage:"."`. <base href="." /> in electron html also didn't help. Does gatsby has such solution?

**Comment by LekoArts** [comment]
Thank you for opening this!

For the feature request of relative URLs you can follow: https://github.com/gatsbyjs/gatsby/discussions/14161
Such feature wasn't added to Gatsby yet.

My colleague (and other people also have used Gatsby with electron) created "desktop": https://github.com/gatsbyjs/desktop -- it should give you an idea on how to use the in combination.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by themre** [comment]
Thank you very much for this answer! Will take a look.
