### ISSUE TITLE
使用antd 4.x 版本时，热更新会卡死 extract queries from components，

### ISSUE THREAD

**Issue by ZhiGang-Fang** [gatsbyjs/gatsby#28361]
## Description

在使用过程时发现，使用antd 3.X 版本没有问题，在一个新项目使用antd 4.x 时，每次更新时都是卡在 extract queries from components，获取此处么有卡住，编译也通过了， 而浏览器就卡住了，刷新浏览器会崩溃， 从新运行就没有问题了

### Steps to reproduce

升级antd 4.x 版本，编辑代码，保存之后就会出现

### Expected result

不被 卡在 extract queries from components 。。。。 或者不出现浏览器刷新崩溃

### Actual result

希望能正常使用，不出现 无限等待 extract queries from components 。。

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

![image](https://user-images.githubusercontent.com/24228407/100579569-66679800-331f-11eb-89e6-53e57b5ed93a.png)

**Comment by LekoArts** [comment]
Hello, thank you for opening this issue!

We would really like to help you with your problem/question but we don't understand your language and therefore kindly ask you to write in the English language. Google Translate can only help a bit and in the end it would be a frustrating guessing game for both parties.

Please feel free to open a new issue (in English) and we'd be happy to help you then 💜

Thank you for using Gatsby!
