### ISSUE TITLE
Gatsby Jest+Babel not working  --   SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by uh-oh-404** [gatsbyjs/gatsby#28362]
## Description

Implementing Unit Tests and getting Error:
```
 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from "react";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

Add tests according to https://www.gatsbyjs.com/docs/unit-testing/
If using Import you'll see the error

### Expected result

What should happen?
No error

### Actual result
Babel/jest like error

### Environment

  System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.67
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.25.0 => 2.26.1 
    gatsby-image: ^2.4.21 => 2.5.0 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-apollo: ^3.0.2 => 3.0.2 
    gatsby-plugin-breadcrumb: ^10.0.0 => 10.0.0 
    gatsby-plugin-prettier-eslint: ^1.0.4 => 1.0.4 
    gatsby-plugin-sass: ^2.4.0 => 2.5.1 
    gatsby-plugin-sharp: ^2.7.0 => 2.8.0 
    gatsby-plugin-styled-components: ^3.3.14 => 3.4.0 
    gatsby-plugin-transition-link: ^1.20.5 => 1.20.5 
    gatsby-source-filesystem: ^2.4.0 => 2.5.0 
    gatsby-transformer-json: ^2.4.15 => 2.5.0 
    gatsby-transformer-sharp: ^2.5.21 => 2.6.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.113

**Comment by uh-oh-404** [comment]
Here's my jest.config

```
module.exports = {
  transform: {
    "^.+\\.jsx?$": `<rootDir>/jest-preprocess.js`,
  },
  moduleNameMapper: {
    ".+\\.(css|styl|less|sass|scss)$": `identity-obj-proxy`,
    ".+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": `<rootDir>/__mocks__/file-mock.js`,
    "@components(.*)$": "<rootDir>/src/components$1",
  },
  testPathIgnorePatterns: [`node_modules`, `.cache`],
  transformIgnorePatterns: [`node_modules/(?!(gatsby)/)`],
  globals: {
    __PATH_PREFIX__: ``,
  },
  testURL: `http://localhost`,
  setupFilesAfterEnv: [`<rootDir>/jest.setup.js`],
  setupFiles: [`<rootDir>/loadershim.js`],
};

```

**Comment by uh-oh-404** [comment]
Nevermind. Just realized there are more steps for Typescript.
Delete

**Comment by visualjeff** [comment]
Hey guys, I've just ran into the same issue.  Everything was working fine up until this last week then I started to see this message with one of my tests:  
```
Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/jgilber/Documents/ecomm/home/node_modules/@babel/runtime/helpers/esm/slicedToArray.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import arrayWithHoles from "@babel/runtime/helpers/esm/arrayWithHoles";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/forge-components/dist/stories/links/linkWithTooltip/component.js:10:46)
```
