### ISSUE TITLE
[gatsby-image] add width and height attribute to improve CLS

### ISSUE THREAD

**Issue by PetroPavlenko** [gatsbyjs/gatsby#28368]
## Description

New Lighthouse version needs width and height attributes. 
https://web.dev/optimize-cls/?utm_source=lighthouse&utm_medium=devtools#images-without-dimensions

### Steps to reproduce

use any fluid image

### Expected result

Add property to include width and height attribute in img tag

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /var/folders/gb/6zmvh1p14lgb_ckkttst8vxm0000gn/T/yarn--1606738359951-0.447755690193848/node
    Yarn: 1.22.5 - /var/folders/gb/6zmvh1p14lgb_ckkttst8vxm0000gn/T/yarn--1606738359951-0.447755690193848/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.198
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.24.86 => 2.24.88 
    gatsby-image: ^2.4.21 => 2.4.21 
    gatsby-plugin-catch-links: ^2.3.15 => 2.3.15 
    gatsby-plugin-layout: ^1.3.13 => 1.3.13 
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0 
    gatsby-plugin-netlify: ^2.3.24 => 2.3.24 
    gatsby-plugin-netlify-cms: ^4.5.0 => 4.5.0 
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.3 
    gatsby-plugin-sharp: ^2.6.43 => 2.6.43 
    gatsby-plugin-sitemap: ^2.4.0 => 2.4.17 
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.14 
    gatsby-plugin-tsconfig-paths: ^1.0.2 => 1.0.2 
    gatsby-plugin-typescript: ^2.4.24 => 2.4.24 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.13 => 1.1.13 
    gatsby-remark-copy-linked-files: ^2.3.19 => 2.3.19 
    gatsby-remark-images: ^3.3.39 => 3.3.39 
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2 
    gatsby-remark-sub-sup: ^1.0.0 => 1.0.0 
    gatsby-source-filesystem: ^2.3.36 => 2.3.37 
    gatsby-transformer-remark: ^2.8.46 => 2.8.46 
    gatsby-transformer-sharp: ^2.5.20 => 2.5.20

**Comment by LekoArts** [comment]
Hi! Please give the new plugin a try, it most likely solves all your issues: https://github.com/gatsbyjs/gatsby/discussions/27950
