### ISSUE TITLE
View Gatsby dev site on multiple devices?

### ISSUE THREAD

**Issue by ooloth** [gatsbyjs/gatsby#2837]
I'm hoping to test my Gatsby site on multiple devices during development.

Following the advice of @webOS101 in [#864](https://github.com/gatsbyjs/gatsby/issues/864), I ran `gatsby develop --host <my-machine>.local` (substituting `<my-machine>` for my actual computer name). Gatsby then said my site is running at http://localhost:8000/ (which it is not).

If this is the correct method, what URL do I open each device's browser to in order to view my dev site?

If this is the wrong method, what is the right way to view my Gatsby dev site on multiple devices?

**Comment by KyleAMathews** [comment]
Looks like localhost got hardcoded:

https://github.com/gatsbyjs/gatsby/blob/5cf7d187a5f56bc52f588a41588f3c269d268c35/packages/gatsby/src/utils/webpack.config.js#L183

Interested in putting together a PR to use the actual host value?

**Comment by ooloth** [comment]
I'd love to! But, I'm not sure how that line needs to change... 🤔

**Comment by JLongley** [comment]
To be clear, that line you reference is just a log statement. The actual code DOES use the host value:

https://github.com/gatsbyjs/gatsby/blob/5cf7d187a5f56bc52f588a41588f3c269d268c35/packages/gatsby/src/utils/webpack.config.js#L134

You can achieve what you are trying to do with:

```
gatsby develop -H 0.0.0.0
```

**Comment by KyleAMathews** [comment]
`--host` works too — so what @ooloth was doing worked it just was confusing due to the logging bug.

Thanks for the fix @JLongley!
