### ISSUE TITLE
How to place pages in a location other than the src/pages/ directory 

### ISSUE THREAD

**Issue by nodox** [gatsbyjs/gatsby#2839]
I see that this path plus src/layouts or src/templates are hard coded directories in my project stack. The name src is conflicting with another src folder I have in my project. Therefore I wish there was a way I could designate a custom path for the folder I want gatsby to use for autogenerated pages. 

`component-page-creator.js` is the file I supposed is responsible for this default behavior but when I introduced my change, the app broke. Other files of interest are 
```
load-plugins.js
src/bootstrap/index.js 
```

The way I thought about introducing the custom path was through the `gatsby-config.js` because its loaded on bootstrap however it broke the `query-watcher.js` when I save the file with a change.

What is the best way to introduce this custom path?

**Comment by dustinhorton** [comment]
@nodox You might want to weigh in on this pre-existing open issue: https://github.com/gatsbyjs/gatsby/issues/2424
