### ISSUE TITLE
Allow passing children to a page

### ISSUE THREAD

**Issue by nagiek** [gatsbyjs/gatsby#28397]
Hi,

Presently, PageProps explicitly forbids that a Page receive children as an argument. While this is correct 99% of the time, I think there are small edge cases which makes me want to revisit the idea.

https://github.com/gatsbyjs/gatsby/blob/91b0433a8155efe526ab93028fdec25c86d5124c/packages/gatsby/index.d.ts#L79

I have a page (TabManager) which shows tabbed content. I want to pass each Tab as a child to TabManager. However, I cannot do this as it is explicitly forbidden. 

Normally I wrap my individual pages with WithLayout. However, because there are two tabs being managed, it doesn't seem possible to wrap them both. Therefore I want TabManager to be a page, and the tabs it loads to be children.

I understand this could be solved simply by changing the argument name passed to TabManager to "tabs", but I thought I should address it here. I prefer seeing the Tab content as children.

Thanks.

**Comment by LekoArts** [comment]
Thank you for opening this!

This won’t be possible as it’s a reserved key in Gatsby. It’s used for child/parent relationships between nodes: https://www.gatsbyjs.com/docs/node-creation/#parentchildrefs

Hence the typings are correctly enforcing that.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
