### ISSUE TITLE
Don't show "local install of Gatsby was not found" error when not running a site-specific command

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#284]
e.g. `gatsby` or `gatsby --help` or `gatsby new`

**Comment by i8ramin** [comment]
I was still getting this error b/c I had an older version of `gatsby-cli` installed in `/usr/local/lib/node_modules` ... To solve the problem, I manually removed that version and also ran `npm cache clean --force` and then also ran `npm uninstall -g gatsby-cli` and reinstalled from scratch. Afterwards, running `which gatsby` shows me:

```/Users/ramin/.nvm/versions/node/v8.1.4/bin/gatsby```
