### ISSUE TITLE
Gatsby site freezes after swiping to go back in iOS Safari

### ISSUE THREAD

**Issue by huntercaron** [gatsbyjs/gatsby#2842]
Currently on every Gatsby site, when swiping to go back in mobile safari, the screen freezes up and sometimes goes blank for ~2-6 seconds. This really breaks the flow of the site. 

Reproducible on sites such as https://www.gatsbyjs.org/, https://reactjs.org/, etc. I haven't found any that is doesn't apply to. 

Reproducible on multiple iOS 11.0.1 & 11.1 devices (iPhone 8, iPad Mini).

I hooked up remote debugging and didn't see any logs/errors.

![gatsbyfreeze](https://user-images.githubusercontent.com/4625978/32555762-a114e3ca-c46b-11e7-8461-5c33c26046e1.gif)

As soon as the page go backs I try to scroll, but its completely frozen (until that highlighted state on the button goes  away).

**Comment by KyleAMathews** [comment]
Tested this on my iphone 6 and was able to reproduce this.

Would love it if you could profile what's happening https://stackoverflow.com/questions/25970466/javascript-profiling-ios-8-safari

**Comment by huntercaron** [comment]
I can't seem to figure out how to export the profile from safari, trying to figure it out right now.

Here is a screenshot of the Javascript events that happen when the screen unfreezes after transition. Hopefully it's useful in some way.

![gatsbyfreeze](https://user-images.githubusercontent.com/4625978/32861001-6d92add2-ca21-11e7-8c51-9a3026c70cfe.png)

**Comment by ryanditjia** [comment]
I’m able to reproduce this issue on all Gatsby sites, on both iPhone and iPad.

The problem doesn’t occur when using the back button. So I recorded timelines to check the differences between the 2. Please help me make sense of this finding.

#### Notes
- Timestamps indicate time in "Timelines Inspector", _not_ timestamp in video
- Site used to test: http://past-stream.surge.sh (based off tutorial 4)
- Devices used: iPhone 6 on iOS 11.2.1 hooked up to MBA on High Sierra 10.13.2

#### Test procedure:
1. Hook up iPhone (Web Inspector turned on) to MBA
2. Load up site
3. Navigate to post #1 (Pandas and Bananas)
4. Click record on Timelines inspector
5. Wait for ~1s
6. Navigate to previous screen, using back button (recording 1), and using edge swipe gesture (recording 2)
7. Start scrolling furiously
8. Stop recording soon after site is scrollable

## Timeline recording 1 — using back button
[View recording in YouTube](https://youtu.be/8C66czbJDjM)
### Observations
- First scroll is on 1.55s (roughly 0.55s after back button is triggered)
- There’s only 1× Script Evaluated event

## Timeline recording 2 — using edge swipe gesture
[View recording in YouTube](https://youtu.be/hzGIHZqUHuM)
### Observations
- First scroll is on 4.42s (roughly 3.42s after edge swipe), screen is empty (white all around) before then
- There are 3× Script Evaluated events

## End of sample

It isn’t obvious to me what’s causing the delay in render. I’m not much of a programmer yet, but I’d love to be able to help. Let me know if you need more data / test samples.

**Comment by ryanditjia** [comment]
As much as I want to see this fixed, this problem appears to be bigger than just Gatsby’s. It’s been bugging me, so I checked out other sites built with other tools (Next, React-Static). Some face similar issue.

### Next ###
- vinylbase.now.sh [repo](https://github.com/GraphCMS/example_01_nextjs_apollo) (has issue)
- https://next-episode.now.sh/ [repo](https://github.com/timneutkens/next-episode) (no issue)

### React-Static ###
- nozzle.io (no issue)
- blacksandsolutions.co (no issue)
- manticoregames.com (has issue)

### Misc. ###
- instagram.com (has issue) 

Hope this helps.

**Comment by KyleAMathews** [comment]
Oh forgot to mention it here but someone on Twitter said this is a known safari issue so not much we can do about it. Thanks for your research! This is super obnoxious :-(

**Comment by thomas-darling** [comment]
Yeah, we just discovered this freezing problem too, in a site based on the framework Aurelia.
It does not appear to be specific to any package or framework, but is as you say triggered by setting `window.history.scrollRestoration` to `manual`, and apparently also by just attaching an event handler to the `scroll` event of the page, regardless of what that handler does.

It’s clearly a bug in Safari, and a really annoying one too.

**Comment by KyleAMathews** [comment]
@rutzfutz just fixed this in our upstream scroll-behavior https://github.com/taion/scroll-behavior/pull/129! Thanks!

**Comment by rutzfutz** [comment]
Most welcome! :-)

**Comment by joeshub** [comment]
@rutzfutz nice find and thanks for the fix! this was driving me crazy. 💯
