### ISSUE TITLE
not working in github desktop

### ISSUE THREAD

**Issue by charanhu** [gatsbyjs/gatsby#28434]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by ascorbic** [comment]
Hi @charanhu ,
Please can you complete the issue template and describe in detail what the problem is.

**Comment by ascorbic** [comment]
Hi. I'm going to close this now, as there is not enough information to understand what the problem is. If you're still having trouble, please open a new issue, making sure to complete the full issue template.  Thanks.
