### ISSUE TITLE
Gatsby Image doesn't seem to work when editing Collection images sourced from Shopify.

### ISSUE THREAD

**Issue by cordial** [gatsbyjs/gatsby#28445]
## Description

When I edit a collection image in Shopify and rebuild (either locally or deployed to Netlify), the gatsby image version of the collection image doesn't change. The non Gatsby image does however change - is gatsby image not supported for Collection images?

### Steps to reproduce

1. Create Collection in Shopify including a Collection Image. 
2. Edit Image of that collection. 
3. Build either locally or on production (I was using Netlify)
4. The src inside Gatsby image does not change to the new image (but the non gatsby image src does). 
How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

New image should be shown on the collection page. 

### Actual result

Old Image remains on the collection page. 
### Environment

  System:
    OS: macOS 11.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nodenv/versions/12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nodenv/versions/12.16.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 80.0.1
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.25.4 => 2.25.4
    gatsby-background-image-es5: ^1.1.1 => 1.1.1
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-plugin-google-analytics: ^2.3.2 => 2.3.2
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-layout: ^1.3.2 => 1.3.2
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9
    gatsby-plugin-netlify-cms: ^4.3.17 => 4.3.17
    gatsby-plugin-offline: ^3.2.7 => 3.2.7
    gatsby-plugin-portal: ^1.0.7 => 1.0.7
    gatsby-plugin-postcss: ^2.3.2 => 2.3.2
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9
    gatsby-remark-images: ^3.5.1 => 3.5.1
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-filesystem: ^2.3.8 => 2.3.8
    gatsby-source-instagram: ^0.8.0 => 0.8.0
    gatsby-source-shopify: ^3.2.8 => 3.2.8
    gatsby-transformer-remark: ^2.9.2 => 2.9.2
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3
  npmGlobalPackages:
    gatsby: 2.21.30

**Comment by calebsylvest** [comment]
Did you check your query to be sure it is correct?

```
{
  allShopifyCollection {
    edges {
      node {
        id
        descriptionHtml
        handle
        image {
          src
          alt
        }
        products {
          id
          handle
          title
        }
        title
      }
    }
  }
}
```

Pulling that from the plugin repo: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-shopify#query-product-collections

**Comment by cordial** [comment]
hey

My query in my template file is 

  query($handle: String!) {
    shopifyCollection(handle: { eq: $handle }) {
      id
      title
      handle
      descriptionHtml
      shopifyId

      image {
        localFile {
          childImageSharp {
            fluid(maxWidth: 3000) {
              ...GatsbyImageSharpFluid_withWebp_noBase64
            }
          }
        }
      }....

I checked the contents of the gatsby image and it had the old file. I then checked the contents of 'src' for the non gatsby image version (using __graphql and also iGraphQL on the shopify side) and it has the edited new image as expected.

**Comment by ascorbic** [comment]
This is a cache invalidation problem. The workaround is not ideal, but running `gatsby clean` should fix it.

**Comment by cordial** [comment]
hey, thanks, but i have tried that and the issue still remains i.e. im stuck with the old image.
