### ISSUE TITLE
[Gatsby-source-contentful] How to retrieve the list of space locales from GraphQL?

### ISSUE THREAD

**Issue by dganoff** [gatsbyjs/gatsby#2844]
Hi, it doesn't seem like the GQL schema generated by the contentful space provides a query to retrieve the Contentful Space information like list of locales. Am I missing something?

Thank you!

**Comment by dganoff** [comment]
I've heard that `allContentfulLocales` is a query that should be included in the GQL schema, but mine doesn't have it. Is there something I need to enable on the Contentful side in order for this to be added to my GQL schema?

**Comment by anjawaldbauer** [comment]
I would also like to query available locales and, if possible, determine which is the default locale. It this possible, yet?

**Comment by rjobin** [comment]
+1, does someone know if there are any updates on this?

**Comment by pieh** [comment]
I don't have concrete answer for you but something you might try if there is no dedicated locales query. You can query one of your post type and use `distinct` resolver to get list of unique values of some field - in this case locale
```gql
allMarkdownRemark{
  distinct(field:frontmatter___title) 
}
```
`allMarkdownRemark` should be one of your contentful query and `frontmatter___title` should be path to locale - best to test this in graphiql

And other option would be update contentful source plugin to support this

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
