### ISSUE TITLE
Gatsbyjs with Wordpress errors when switching data source to locally hosted

### ISSUE THREAD

**Issue by Kimpo79** [gatsbyjs/gatsby#2845]
I just started exploring gatsbyjs and tried to get a site running with WP as data source. The example which is using dev-gatbsyjswp.pantheonsite.io works out of the box but changing to a locally hosted WP gives me an error i cannot figure out.

I'm getting:
<img width="1048" alt="screen shot 2017-11-08 at 4 36 58 pm" src="https://user-images.githubusercontent.com/4668225/32560988-5a90159c-c4ab-11e7-827b-8f64ad4b79fc.png">

I can run a query with Graphiql and i do get results. I have limited knowledge when it comes to gatsbyjs and graphql so i might of course be missing something obvious 😁

![screen shot 2017-11-08 at 4 46 49 pm](https://user-images.githubusercontent.com/4668225/32560993-5fc289a0-c4ab-11e7-92ee-1d136e6705d2.png)

Is the demo WP site using some special set up?
Is the gatsby-source-wordpress expecting something specific(i see a lot of hard coded ACF stuff 😁 ) to be provided through the WP-API that is not in a standard installation?

**Comment by KyleAMathews** [comment]
In general you cant just switch sources and expect things to work. Gatsby's graphql schemas are built based on the data in your sources so queries used for one site won't necessarily work for another site.

Try deleting the different pages from the example site and starting over from scratch. Also look in the console for errors.

**Comment by Kimpo79** [comment]
You are completely correct @KyleAMathews , that was a bad assumption from my side that it would just work. I had forgotten a file from the source that should not have been there.

Just a question, is there an easy way to get better debugging info when graphql errors during compile? i tried setting plugin config to `verbose:true` but did not seem to make any difference.

All i got was `GraphQL Error There was an error while compiling your site's GraphQL queries.` which does not tell me a lot besides that something is wrong :)

**Comment by KyleAMathews** [comment]
Hmmm it should tell you what component file has the error?

**Comment by KyleAMathews** [comment]
If you want to play around with this to see if you can improve the errors — the code for them is here: https://github.com/gatsbyjs/gatsby/blob/af5c9c86a604d2f6d441a793d1df3cd7b2cba793/packages/gatsby/src/internal-plugins/query-runner/graphql-errors.js

**Comment by Kimpo79** [comment]
>Hmmm it should tell you what component file has the error?

I thought it should do it too, in this case it was the PostIcon i had mistakenly forgotten in my filesystem which gatsby was picking up during build time. 

I would gladly try to help out contributing to gatsbyjs since i think it is really exciting and will very likely be building websites/webapps with it.
