### ISSUE TITLE
Add Support For Remark React Plugin

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#2846]
The [Remark React Plugin](https://github.com/mapbox/remark-react) allows you to set up mappings between markdown-rendered elements and React Components. Supporting this would greatly improve consistency across the application because React components can be shared between content rendered from markdown and other components defined in the rest of the view. This is particularly useful when using Styled Components.

It uses config like this:
```
remarkReactComponents: {
  a: MyLink,
  p: MyParagraph
}
```

**Comment by KyleAMathews** [comment]
We don't want to use that plugin since it does the markdown parsing in the browser which means loading a lot of JS + incurring compilation costs on the client.

Hop on this thread to see what we've been talking about doing — I rather like my suggestion towards the end! Still need someone to jump on it and implement it! ;-)

https://github.com/gatsbyjs/gatsby/issues/312

**Comment by Undistraction** [comment]
I think my request is different form #312. There you are discussing being able to actually write React within markdown. I can absolutely see the benefit of this, but I actually want something much simpler. The ability to map the standard elements generated by markdown - `ul`, `p`, `a` etc to React components so that rather than the parser rendering a `### Example` as `<h3>Example</h3>`, it would be rendered as a react component: `<Title level="3">Example</Title>`. If you feel this is different enough I'll open a separate issue that is not specific to Remark React.

**Comment by KyleAMathews** [comment]
`<Title>` is React too :-) We use `dangerouslySetInnerHTML` to insert the HTML from markdown so it doesn't matter if we replace html tags with React components because it's still just inserted in.

Auto swapping HTML tags w/ React is something I'd *love* to support once #312 is solved.

**Comment by Undistraction** [comment]
Ah. Ok that makes sense. I had imagined there was more complexity to parsing out the React comps from the Markdown, but I see what you mean.

**Comment by chibicode** [comment]
@Undistraction @KyleAMathews I believe this is now possible as #312 is resolved.

https://using-remark.gatsbyjs.org/custom-components/

If you want to use your custom `<Paragraph>` component to replace `<p>` tags, do this:

```js
// Define Paragraph component...
// const Paragraph = ({ children }) => ...
// or use styled components...
// const Paragraph = styled.p`...`

const renderAst = new rehypeReact({
 createElement: React.createElement,
 components: { "p": Paragraph },
}).Compiler;
```

I can add this use case to [the documentation](https://using-remark.gatsbyjs.org/custom-components/) if @KyleAMathews thinks this would be helpful.

**Comment by KyleAMathews** [comment]
@chibicode thanks for the offer! Yeah, that page doesn't really talk about overriding default dom components so this would be a nice addition.
