### ISSUE TITLE
default typescript plugin conflicts with ts-loader

### ISSUE THREAD

**Issue by Merciful12** [gatsbyjs/gatsby#28498]
## Description
 i use ts loader and after i updated gatsby i start getting errors like this https://github.com/gatsbyjs/gatsby/issues/26027
I Didn't catch how to disable default babel ts compilation https://github.com/gatsbyjs/gatsby/pull/26452

### Steps to reproduce

start a new gatsby project and add ts-loader plugin

### Expected result

should build without error

### Actual result

didn't build because errors like 
```
TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
TS7006: Parameter '_ref3' implicitly has an 'any' type.
```

**Comment by Js-Brecht** [comment]
There is (supposed to) be discussion about modifying the default typescript loader here: https://github.com/gatsbyjs/gatsby/discussions/26984.  It hasn't seen any action since that PR, however.

For right now, in `onCreateWebpackConfig`, you would need to strip out `gatsby-plugin-typescript` in order for you to be able to use `ts-loader`.

**Comment by Merciful12** [comment]
@Js-Brecht For temporary solution i just resolve both plugins in order : `gatsby-plugin-typescript`, `gatsby-plugin-ts-loader`. And it works fine. How to strip out in `onCreateWebpackConfig`? Just webpack ignore `@babel/preset-typescript`?

**Comment by Js-Brecht** [comment]
You would need to find the rule in the webpack config that matches against `*.ts` files and that uses `babel-loader`, and remove it.  That should leave the rule that uses `ts-loader`

**Comment by LekoArts** [comment]
I'll close this in favor of https://github.com/gatsbyjs/gatsby/discussions/26984

Thanks Js-Brecht for always helping out!
