### ISSUE TITLE
The result of this StaticQuery could not be fetched

### ISSUE THREAD

**Issue by leekallman** [gatsbyjs/gatsby#28502]
## Description

I get an error message when I try to load the localhost page. See attached image.

### Expected result

I want to render featuredImage from a markup post into a component.

### Actual result

First I got an error saying the childImageSharp can't read the featuredImage of null. This error occurred when I was adding multiple markup-files in my file-system. It worked from the beginning. (I'm also fetching other data from the same markup-file, which works fine.) Now I receive this error saying it might be a bug.

### Environment

 System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 81.0.1
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1 
    gatsby-image: ^2.7.0 => 2.7.0 
    gatsby-plugin-fontawesome-css: ^1.0.0 => 1.0.0 
    gatsby-plugin-sharp: ^2.10.0 => 2.10.0 
    gatsby-remark-images: ^3.7.0 => 3.7.0 
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2 
    gatsby-source-filesystem: ^2.6.1 => 2.6.1 
    gatsby-transformer-remark: ^2.12.0 => 2.12.0 
    gatsby-transformer-sharp: ^2.8.0 => 2.8.0 
  npmGlobalPackages:
    gatsby-cli: 2.13.1

<img width="737" alt="Screenshot 2020-12-06 at 15 09 31" src="https://user-images.githubusercontent.com/59650403/101282366-154f1c80-37d5-11eb-97a1-524987a7b585.png">

repo: https://github.com/leekallman/TM/tree/onePager/src

should also add that i'm a beginner in gatsby..

**Comment by jharrilim** [comment]
I have the same issue, tossed it into this branch:
https://github.com/jharrilim/jharrilim.github.io/blob/gatsby-bug/src/layouts/post.tsx

It seems to occur for me when I write a query without the [OperationName](https://graphql.org/learn/queries/#operation-name) which seems to be the same case as OP.

This is an error:

```js
const data = useStaticQuery(graphql`
  query {
    site {
      siteMetadata {
        title
      }
    }
  } 
`);
```

This is not an error:

```js
const data = useStaticQuery(graphql`
  query ATitleQuery {
    site {
      siteMetadata {
        title
      }
    }
  } 
`);
```

**Comment by LekoArts** [comment]
Thanks for the issue! I'm consolidating the issues around it into this one here: https://github.com/gatsbyjs/gatsby/issues/26563 -- please comment with your reproduction there. Thanks!
