### ISSUE TITLE
[gatsby-source-contentful] Stuck at load plugins when using proxy

### ISSUE THREAD

**Issue by donaldkg** [gatsbyjs/gatsby#28526]
## Description

When using gatsby-source-contentful with proxy, I cannot get passed load plugins. It runs for a while and returns a timeout error. 

### Steps to reproduce

1. Run npm run build behind proxy

### Expected result

It should be able to build.

### Actual result

The build process is stuck in load plugins

### Environment

  System:
    OS: Linux 3.10 Red Hat Enterprise Linux Server 7.6 (Maipo)
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-26xx v4
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 12.18.3 - /bin/node
    npm: 6.14.6 - /bin/npm
  Languages:
    Python: 2.7.5 - /bin/python
  npmPackages:
    gatsby: ^2.26.1 => 2.28.1
    gatsby-image: ^2.7.0 => 2.7.0
    gatsby-plugin-canonical-urls: ^2.6.0 => 2.6.0
    gatsby-plugin-google-analytics: ^2.7.0 => 2.7.0
    gatsby-plugin-google-tagmanager: ^2.8.0 => 2.8.0
    gatsby-plugin-intl: ^0.3.3 => 0.3.3
    gatsby-plugin-manifest: ^2.8.0 => 2.8.0
    gatsby-plugin-react-helmet: ^3.6.0 => 3.6.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.10.0 => 2.10.1
    gatsby-plugin-sitemap: ^2.8.0 => 2.8.0
    gatsby-plugin-styled-components: ^3.6.0 => 3.6.0
    gatsby-source-contentful: ^2.3.52 => 2.3.56
    gatsby-source-filesystem: ^2.7.0 => 2.7.0
    gatsby-transformer-remark: ^2.12.0 => 2.12.0
    gatsby-transformer-sharp: ^2.8.0 => 2.8.0

**Comment by donaldkg** [comment]
I suspect that `validateContentfulAccess` function misses to pass proxy options in `fetch` in `gatsby-node.js` file.

**Comment by DSchau** [comment]
@donaldkg can you share your particular set up or how the plugin is configured? (https://gatsby.dev/reproduction)

My suspicion is you're probably correct, but it's hard to _know_ that until there's something for us to review!

**Comment by donaldkg** [comment]
@DSchau Thanks for your reply. I have provided the environment above. To reproduce, just run `gatsby build` with downloadLocal set to true.

**Comment by donaldkg** [comment]
I finally use `global-agent` to solve the problem. I put `require('global-agent/bootstrap');` in `gatsby-config.js` and setting the environment variable `GLOBAL_AGENT_HTTP_PROXY`. It seems that all the api call from Contentful can use the proxy defined in the variable.
