### ISSUE TITLE
Automatically add `__typename` and `contentful_id` to Contentful Rich Text references

### ISSUE THREAD

**Issue by axe312ger** [gatsbyjs/gatsby#28528]
Not sure if this is a bug or just a miss in the documentation but when setting a reference to an `Asset` it will not include it unless you add the key `__typename` in the graphQL query.
so like this:
```
body {
      raw
      references {
        ... on ContentfulAsset {
          contentful_id
          __typename
          file {
            url
          }
        }
      }
    }
```

this is because if you use `richTextRender` function it will divide the types by that key.
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/rich-text.js#L30

It might have to do something with this comment? https://github.com/gatsbyjs/gatsby/pull/25249#issuecomment-665043279
I havent tried out the `useNameForId: false` yet though.

_Originally posted by @mikaelkristiansson in https://github.com/gatsbyjs/gatsby/discussions/28098#discussioncomment-130585_

**Comment by axe312ger** [comment]
We may fix it like we did here: https://github.com/gatsbyjs/gatsby/pull/20849

**Comment by TjenWellens** [comment]
This took me too long to find, so I'm going to add my error messages here.
In the hopes that the next person having the same problem, will end up here, and see the workaround.

When you have something like
(for instance when you're following the migration guide from [gatsby-source-contentful](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/CHANGELOG.md#400-next0-2020-11-09)
```
export const pageQuery = graphql`
  query pageQuery($id: String!) {
    contentfulPage(id: { eq: $id }) {
      title
      slug
      description {
        raw
        references {
          ... on ContentfulAsset {
            # contentful_id is required to resolve the references
            contentful_id
            fluid(maxWidth: 600) {
              ...GatsbyContentfulFluid_withWebp
            }
          }
        }
      }
    }
  }
`
```

You get an error like
```
TypeError: Cannot read property '0' of undefined
getCurrentSrcData
node_modules/gatsby-image/index.js:134
|    return currentData[0];

getImageSrcKey
node_modules/gatsby-image/index.js:102

inImageCache
node_modules/gatsby-image/index.js:144
```

And you can resolve the error by adding `__typename` and `contentful_id`
```
 ... on ContentfulAsset {
# contentful_id is required to resolve the references
contentful_id
fluid(maxWidth: 600) {
  ...GatsbyContentfulFluid_withWebp
}
# __typename is ALSO required to resolve the references
__typename
}
```

**Comment by axe312ger** [comment]
Please just add __typename to the references when using rich text.
