### ISSUE TITLE
`contentful_id` is sometimes of type `String` and sometimes of type `String!` Is this a bug? If not, what can I do to prevent this from happening?

### ISSUE THREAD

**Issue by axe312ger** [gatsbyjs/gatsby#28527]
`contentful_id` is sometimes of type `String` and sometimes of type `String!` Is this a bug? If not, what can I do to prevent this from happening?

This is a problem when required to use `contentful_id` on creating references

```
body {
        raw
        references {
          __typename
          ... on ContentfulArticle {
            contentful_id
            slug
          }
          ... on ContentfulVideo {
            contentful_id
            slug
          }
          ...
```

Error:
```
Fields "contentful_id" conflict because they return conflicting types String and String!. Use different aliases on the fields to fetch both if this was intentional.

GraphQL request:56:13
55 |           ... on ContentfulArticle {
56 |             contentful_id
   |             ^
57 |             id

GraphQL request:125:13
124 |           ... on ContentfulVideo {
125 |             contentful_id
    |             ^
126 |             url
```

I worked around it by creating an alias for one of the fields. 

I'm using gatsby 2.28.0 and gatsby-source-contentful@4.2.0, also tried 4.3.0-next.1

_Originally posted by @hoenderdaal in https://github.com/gatsbyjs/gatsby/discussions/28098#discussioncomment-145231_

**Comment by zcei** [comment]
Is the the antichrist of the "field missing" bug? 😱 

I intend something where now the core checks smth like 

> So, should this filed be requireed? Pretty much when every value is set, 
> - Hopefully no contributor 

That's the reason btw why the official  Contentful GraphQL API has nearly every user field as nullable. We can't always prevent customers from handing us no data somewhere. Only fields that use a resolver that' guarantees to always yield results are marked with the exclamation mark. (Some don't like this decision of course. There'rs no silverbullet, just a 2c)

**Comment by axe312ger** [comment]
Nah I think this is just a type mixup

**Comment by axe312ger** [comment]
@hoenderdaal

Sorry, but I can't replicate your issue, for me:

* I can't locate any content type in my examples that has `String`, all have `String!`
* So far I understand, this code ensures `contentful_id` of all content type nodes are `String!`: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/gatsby-node.js#L322-L334 (@ gatsby core: Is this assumption correct? )
* Assets `contentful_id` is set to `String!` as well a few lines above

Does the issue persist for you?

Did you maybe created your own type for that one fields content type? And define `contentful_id` over there as nullable?

**Comment by hoenderdaal** [comment]
@axe312ger Thanks for looking into it.

I still have the issue. I've been trying to debug it, but can't find the code that is setting the type to String. I also don't have set any custom schema types. My workaround didn't work as expected either. So, right now, what works for me is creating custom schema types for the objects generated with type String.

```
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions
  const typeDefs = `
    type ContentfulArticle implements Node {
      contentful_id: String!
    }
    type ContentfulExternalLink implements Node {
      contentful_id: String!
    }
    type ContentfulDeskCategory implements Node {
      contentful_id: String!
    }
    type ContentfulTable implements Node {
      contentful_id: String!
    }
  `
  createTypes(typeDefs)
}
```
It's strange it happens with 4 of the 10 objects. I've been trying to find if there is a relation between does objects, but without success. I'll let you know if I found the problem or have more information.

**Comment by axe312ger** [comment]
@hoenderdaal Thank you. Any information would be helpful. Super strange only a few are affected.

Stupid question: You did clear the cache, right? 😅 


If you/your organization is willing to give me access to your Contentful space, I could use your data to debug the issue on my end.

You would need to start a new support ticket (https://www.contentful.com/support/) and that you are willing to give us access to your data. Our support team will guide you to through the process. Just be sure to mention this issue/GatsbyJS, so it will end up on my desk :)

**Comment by LekoArts** [comment]
Is there a reproduction for this issue? We normally close issues after a while if they have no reproduction.

**Comment by axe312ger** [comment]
Closing due to no reply from issue creator. In case you run into this and have steps to reproduce, fee free to open a new issue or post here.
