### ISSUE TITLE
useStaticQuery & StaticQuery: The result of this StaticQuery could not be fetched

### ISSUE THREAD

**Issue by timurc** [gatsbyjs/gatsby#28537]
## Description

I am trying to use static queries in a project, but they are not working. Neither `useStaticQuery()` nor `<StaticQuery />`. `useStaticQuery` reproduces the following error: 

```
Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
```

When using `<StaticQuery />` the error is instead: `Loading(Static Query)` on a blank page.

I have used this query before in other projects without problems. I tried to triangulate for some time now, but really did not get to it. I also found issues that have the same symptoms (https://github.com/gatsbyjs/gatsby/issues/25920, https://github.com/gatsbyjs/gatsby/issues/24902, https://github.com/gatsbyjs/gatsby/issues/24526) but did not help me resolve this, so I assume it's some different issue. Things I tried:

* update all dependencies to the latest version
* delete `node_modules`, `.cache`
* check for casing errors
* fresh checkout in a different folder, just to be sure...

### Steps to reproduce

I made a branch that at least _at my machine_ reproduces the error: https://github.com/voellig-ohne/timobecker/tree/reproduce-issue

Clone into repo, checkout out `reproduce-issue`, `npm i`,  `npm start`, open in browser

### Expected result

Query should not fail. Or display a helpful error message that does not ask me to open an issue here 😅

### Actual result

Query fails.

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.88
    Edge: 87.0.664.57
    Firefox: 83.0
    Safari: 14.0
  npmPackages:
    gatsby: ^2.28.1 => 2.28.1 
    gatsby-image: ^2.7.0 => 2.7.0 
    gatsby-plugin-less: ^4.3.0 => 4.3.0 
    gatsby-plugin-matomo: ^0.8.3 => 0.8.3 
    gatsby-plugin-react-helmet: ^3.6.0 => 3.6.0 
    gatsby-plugin-sharp: ^2.10.1 => 2.10.1 
    gatsby-remark-copy-linked-files: ^2.6.0 => 2.6.0 
    gatsby-source-contentful: ^4.2.1 => 4.2.1 
    gatsby-source-filesystem: ^2.7.0 => 2.7.0 
    gatsby-transformer-remark: ^2.12.0 => 2.12.0 
    gatsby-transformer-sharp: ^2.8.0 => 2.8.0 
```

Thanks for any help with this!

**Comment by LekoArts** [comment]
Thanks for the issue and the reproduction! Could you please copy this over to https://github.com/gatsbyjs/gatsby/issues/26563 ? I'll consolidate all issues into this one. Thanks!

**Comment by timurc** [comment]
@LekoArts thanks! Sure, copied it there. Don't know why I didn't stumble over that one...
