### ISSUE TITLE
Katex rendering not working with MDX

### ISSUE THREAD

**Issue by sonapraneeth-a** [gatsbyjs/gatsby#28546]
## Description

Describe the issue that you're seeing.

Math blocks not rendering properly when using KaTeX with MDX

### Steps to reproduce

[Repo link](https://github.com/sonapraneeth-a/using-mdx)

1. Clone the repository
2. `npm install`
3. `npm run develop`
4. Open `http://localhost:8000/`
4. Verify the equation rendering

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

![image](https://user-images.githubusercontent.com/13482560/101592645-a4964300-3a14-11eb-9c30-06c3a81272c6.png)

![image](https://user-images.githubusercontent.com/13482560/101592669-ae1fab00-3a14-11eb-9aa9-c1686cc34114.png)

### Actual result

What happened.

![image](https://user-images.githubusercontent.com/13482560/101592750-cb547980-3a14-11eb-9fa3-f084f9d32db1.png)

![image](https://user-images.githubusercontent.com/13482560/101592770-d0b1c400-3a14-11eb-89b5-daf1ae34e42b.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
 System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\Softwares\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Softwares\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\Softwares\nodejs\npm.CMD
  Languages:
    Python: 3.7.4
  Browsers:
    Edge: 44.19041.423.0
  npmPackages:
    gatsby: 2.28.1 => 2.28.1
    gatsby-plugin-mdx: 1.3.0 => 1.3.0
    gatsby-remark-autolink-headers: ^2.8.0 => 2.8.0
    gatsby-remark-katex: 3.3.0 => 3.3.0
    gatsby-source-filesystem: 2.7.0 => 2.7.0
```

**Comment by sonapraneeth-a** [comment]
This appears to be a problem from `gatsby-plugin-mdx`

**Comment by sonapraneeth-a** [comment]
Closing this for now as I've got a workaround

**Comment by trevorblades** [comment]
@sonapraneeth-a what was the workaround?

**Comment by sonapraneeth-a** [comment]
@trevorblades , Instead of `gatsby-remark-katex`, I'm using `remark-html-katex` and `remark-math` plugins.
