### ISSUE TITLE
"Sorting on fields that need arguments to resolve is deprecated" warning

### ISSUE THREAD

**Issue by cedricdelpoux** [gatsbyjs/gatsby#28565]
## Description

If I create a node field using `createNodeField` from a node value:
```
exports.onCreateNode = async ({node, actions: {createNodeField}}) => {
  if (node.internal.type === "MarkdownRemark") {
    createNodeField({
      node,
      name: "template",
      value:  node.frontmatter.template,
    })
  }
}
```

Then I want to use this field to group my nodes 
```
query MyQuery {
  allMarkdownRemark {
    group(field: fields___template) {
      fieldValue
      totalCount
    }
  }
}
```

There is the following warning
<img width="751" alt="Screenshot 2020-12-09 at 17 19 30" src="https://user-images.githubusercontent.com/2683300/101658181-0bcbeb80-3a45-11eb-9f70-bf4f89061dbc.png">

If I use the original data (which is the same), everything is fine
```
query MyQuery {
  allMarkdownRemark {
    group(field: frontmatter___template) {
      fieldValue
      totalCount
    }
  }
}
```

### Steps to reproduce

1. Create a node field
2. Try to group nodes by this field

### Expected result

No warning, it should works

### Actual result
              
`Sorting on fields that need arguments to resolve is deprecated`

### Environment

System:
OS: macOS 11.0.1
CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
Shell: 5.8 - /bin/zsh
Binaries:
Node: 15.2.1 - /usr/local/bin/node
Yarn: 1.22.10 - /usr/local/bin/yarn
npm: 7.0.10 - /usr/local/bin/npm
Languages:
Python: 2.7.16 - /usr/bin/python
Browsers:
Chrome: 87.0.4280.88
Firefox: 72.0.2
Safari: 14.0.1
npmPackages:
gatsby: ^2.28.0 => 2.28.0

**Comment by vladar** [comment]
Hey @cedricdelpoux 

Do you use schema customization by chance? If so, double check that you don't have arguments defined for this field (e.g. by checking the field `MarkdownRemarkFields.template` in GraphiQL docs).

If you are absolutely positive that this field has no arguments - please provide a [minimal reproduction][reproduction] and we'll be able to take another look.

[reproduction]: https://gatsby.dev/reproduction

**Comment by cedricdelpoux** [comment]
<img width="958" alt="Screenshot 2020-12-10 at 14 42 12" src="https://user-images.githubusercontent.com/2683300/101779705-ea770800-3af5-11eb-966d-08c648c765b8.png">

Like you can see, it's a simple string

**Comment by vladar** [comment]
Interesting. Can you provide a [minimal reproduction](https://gatsby.dev/reproduction). I'll take a look.

**Comment by sonapraneeth-a** [comment]
I've seen a similar warning when using `sort`. I've been using sort based on example provided in the [docs](https://www.gatsbyjs.com/docs/graphql-reference/#sort)

By the way, the fields I'm using are from schema customization. Is there any way to use fields created by schema customization in `sort`?

![image](https://user-images.githubusercontent.com/13482560/101912009-33f35000-3be7-11eb-8103-4463bf9902de.png)

![image](https://user-images.githubusercontent.com/13482560/101911913-0dcdb000-3be7-11eb-8d9e-02a97ee50be4.png)

**Comment by amantiwari1** [comment]
I've seen a similar warning, is any way to `fix it`?
![image](https://user-images.githubusercontent.com/53963065/106372899-6ecd6500-639a-11eb-95e9-fadb8bc219b6.png)

**Comment by vladar** [comment]
This is possible if there are custom arguments on those fields. But it doesn't look this way from your screenshots. I checked it on our starters and I don't see this problem. So we do need a [minimal reproduction](https://gatsby.dev/reproduction) to actually start investigating this.

**Comment by sonapraneeth-a** [comment]
@vladar , What does custom argument mean? Could you please show an example?

**Comment by ascorbic** [comment]
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Comment by emmenko** [comment]
The "minimal blog theme" from @LekoArts uses those deprecated sorting fields:

https://github.com/LekoArts/gatsby-themes/blob/ea3eb0b4f6d49c99b2f209d0a9a504f3e3f1ce10/themes/gatsby-theme-minimal-blog-core/gatsby-node.js#L295-L299

I'm curious to hear from @LekoArts what's the best way to migrate to v3 and avoid those deprecation warnings, while keeping the same functionality.

Thanks 🙏

**Comment by rejas** [comment]
I get this warning too when building my personal homepage (https://github.com/rejas/veeck.de)

Will try to get a minimal reproduction done....

**Comment by rejas** [comment]
hi @ascorbic I created a repo with hopefully minimal code around it. You can find it in https://github.com/rejas/deprecate_repo

or should I open a new issue with this sicne I am not the OP ? Thx in advance

**Comment by ascorbic** [comment]
Hi @rejas,
I don't work at Gatsby anymore, but I'd say open a new issue as this one has been closed.

**Comment by rejas** [comment]
Will do, thanks anyway!
