### ISSUE TITLE
Website has loads of slow loading of "page-data.json" files in the network

### ISSUE THREAD

**Issue by Oyyou** [gatsbyjs/gatsby#28578]
I've been working on a Gatsby site for a while now, and it just appears to be getting slower and slower as I go on. After looking in at the network when the page loads, I can see plenty of "page-data.json" files in use:
![image](https://user-images.githubusercontent.com/2433994/101833814-66427600-3b31-11eb-8caa-6d70a75deba1.png)

In the above example, those time values are quite generous. We're usually looking at closer to 6s per one. I don't know if this is just how gatsby works, but I also see duplicated "page-data.json" files

Any idea what the issue is, and how I resolve it?

(also, if I need to post anything else, let me know)

**Comment by KyleAMathews** [comment]
It's possible that the requests are queuing up — the browser will only make so many requests at a time so it's possible that the later requested files are waiting on the earlier. Is there any requests that are loading much quicker?

**Comment by Oyyou** [comment]
It appears to only happen on my "products" page, which loads about 50 products from shopify via graphql. I did think this was the problem, but that was working fine at an earlier stage

I've been looking for a way to load the query in bit-by-bit but had no luck (load the first 10, then next 10 after scrolling to the bottom. Infinite scrolling)

**Comment by Oyyou** [comment]
Here is a video I just recorded of going from the home page to the products page. It took about 11 seconds to navigate:
https://www.youtube.com/watch?v=8McE5vZoN6w

Along with that is the .har file: https://we.tl/t-OdLxDmWCnO

Sorry I'm not much use. I'm relatively new to web dev!

**Comment by Oyyou** [comment]
After some looking, and thinking, I remembered that my allShopifyProducts was using "variants". With each of my products having quite a few variants, I was loading in about 2k things anytime I went to the "products page"

As we're only using "variants" to show the price at that stage, I've removed the variants completely and instead used the priceRange. That has improved the performance drastically (as expected!)

**Comment by smthomas** [comment]
This appears like it was fixed. Let us know if you are still having issues with this.
