### ISSUE TITLE
For a Rich-Content-text  data fetch using json is not available

### ISSUE THREAD

**Issue by anto-pv** [gatsbyjs/gatsby#28588]
## Description
For fetching data from a rich text data , in contentful, only raw is available json is not available 

### Steps to reproduce

make a gatsby site
npm install gatsby-source-contentful
give query in graphql which recieves a rich-content-data from contentful by json 

### Expected result

It should generate a json formatted content

### Actual result

graphql gives:
"errors": [
    {
      "message": "Cannot query field \"json\" on type \"ContentfulBlogPostBody\".",
"stack": [
        "GraphQLError: Cannot query field \"json\" on type \"ContentfulBlogPostBody\".",
        "    at Object.Field

**Comment by DevanB** [comment]
I'm having a similar issue, but I can't see `json` or `raw` on a rich text node at all.

![image](https://user-images.githubusercontent.com/354652/101996265-d7ec0280-3c9e-11eb-9500-3a666a21ded3.png)

**Comment by anto-pv** [comment]
> I'm having a similar issue, but I can't see `json` or `raw` on a rich text node at all.
> 
> ![image](https://user-images.githubusercontent.com/354652/101996265-d7ec0280-3c9e-11eb-9500-3a666a21ded3.png)

![Screenshot (102)](https://user-images.githubusercontent.com/67824435/102002330-76b94300-3d21-11eb-8441-d4c5f95955ed.png)

**Comment by anto-pv** [comment]
> I'm having a similar issue, but I can't see `json` or `raw` on a rich text node at all.
> 
> ![image](https://user-images.githubusercontent.com/354652/101996265-d7ec0280-3c9e-11eb-9500-3a666a21ded3.png)

Yes...Finally I got what happened. The things raw, json depend on version of plugin gatsby-source-contentful. json is supported @^2.3.56 in @4 raw is supported. So change the version , I think it may work.

**Comment by nmastroianni** [comment]
Hey, late to the party as usual. I was experiencing this issue and [I found this](https://www.contentful.com/developers/docs/tutorials/general/rich-text-and-gatsby/) (see note at the bottom of the page)
