### ISSUE TITLE
Popped up command window

### ISSUE THREAD

**Issue by moahmadeng** [gatsbyjs/gatsby#28593]
A window pops up randomly and you loose the focus on the window you were for 1 second then you get the focus back again. Sometimes there are 3 windows simultaneously popping up for 1 sec then it closed instantaneously.

**Comment by LekoArts** [comment]
Hi, please fill out the issue template for bug reports and provide a reproduction for your problem. I'll close this one here as it’s not actionable. Thanks for understanding!
