### ISSUE TITLE
Line breaks in md data

### ISSUE THREAD

**Issue by MichaelCereda** [gatsbyjs/gatsby#286]
I'm tying to have a line break (<br/>) within two lines.

```markdown
---
title: I'm a markdown file!
subtitle: >
          I'm going to keep it
          short, I promise
icon: ghost
---
Markdown is pretty cool if you ask me.

## You can have lists

### Numbered
1. me first!
2. I'm second!
3. third :(

```

i tryed everything, >, |.
nothings seems to render that

i also followed this blog post but really nothing happens... any idea?
http://push.cwcon.org/learn/yaml-and-markdown.html

**Comment by MichaelCereda** [comment]
i resolved editing the loader
```markdown
---
title: I'm a markdown file!
subtitle: >
  I'm going to keep it
  
  short, I promise
icon: ghost
---
```
editing to

https://github.com/gatsbyjs/gatsby/blob/master/lib/loaders/markdown-loader/index.js#L31

```javascript
for (var key in meta.attributes){
    if(meta.attributes[key].indexOf('\n')!=-1){
      meta.attributes[key] = meta.attributes[key].replace('\n', '<br />');
    }
  }
```

**Comment by KyleAMathews** [comment]
Hmmm yeah the front matter in Gatsby isn't run through the markdown renderer like in that blog post. It looks like your solution works. But instead of forking Gatsby, just override the loader like here https://github.com/gatsbyjs/gatsby-starter-default/blob/master/loaders/markdown-loader/index.js

**Comment by MichaelCereda** [comment]
Yes absolutely... I linked that line so if somebody needs it they won't
have to look around.
