### ISSUE TITLE
Issues with 404 and page-data.json not loading

### ISSUE THREAD

**Issue by peetaaah** [gatsbyjs/gatsby#28603]
## Description

Hey guys, I'm unsure whether this is the place to ask, but I've been slaving over this issue for a week or so now, and I figured since I can't get any answers coming through the Gatsby Github, or stackoverflow, I'd just ask here (and hopefully it'll help others too)

When i run `gatsby develop` the app i built runs fine - but when i navigate to another page, it briefly displays that page, then reverts to my homepage.

Even my 404 page doesn't display, it just goes back to my homepage.

Strangely enough, it worked before, until one day when i re-ran my develop and build.

### Steps to reproduce

1. Open the application @ localhost:8000
2. Page will automatically redirect to the auth0 authentication page
3. Once authenticated, will redirect back to the localhost:8000 (home page of the SaaS)
4. The affected pages are in the speeddial - in the gif below you'll see it redirects back to localhost upon clicking them.

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

 - Page navigation should occur normally.

### Actual result

- Page navigation redirects back to my localhost:8000, with the only console log being 
"GET http://localhost:8000/page-data/%20/page-data.json net::ERR_ABORTED 404 (Not Found)"

- I use auth0 as my means of authentication. When I click the affected page, the console log i set on the if statement returns normally, and the page briefly shows then returns to the localhost:8000 page.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 6.14.9 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.67
    Safari: 14.0
  npmPackages:
    gatsby: ^2.28.2 => 2.28.2 
    gatsby-cli: ^2.15.1 => 2.15.1 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.10 
  npmGlobalPackages:
    gatsby-cli: 2.15.1

Thank you for any assistance - I've been trying to solve this for about 1.5 weeks now!

![gatsby-help](https://user-images.githubusercontent.com/42408307/102047523-5b7d2f00-3e18-11eb-96b5-9681cea50cca.gif)

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by peetaaah** [comment]
Hi @LekoArts, let me try my best for it!

Thanks also for replying to me :)

**Comment by peetaaah** [comment]
Found out the issue - and thankfully, the bug wasn't with the page-data.json.

(issue was with gatsby x material UI: i placed some code that wasn't compatible with material UI and so the site broke, my fault)

The 404 on the page-data.json still exists, but it doesn't fully interfere with the function of the app platform. 

So... I guess i can close it. thanks once again!
