### ISSUE TITLE
Fast reload stops working on Gatsby pages that use Redux connect

### ISSUE THREAD

**Issue by raRaRa** [gatsbyjs/gatsby#28608]
## Description

When I wrap a page under /pages with Redux `connect`, then the page won't refresh when changes are made on it. It'll start working as soon as I remove `export default connect(mapStateToProps)(Home)` and change it to `export default Home`

### Steps to reproduce

Setup Redux and try using react-redux `connect` on a page under /pages.

### Expected result

It should refresh the page when changes are made

### Actual result

It doesn't refresh.

### Environment

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.60)
  npmPackages:
    gatsby: ^2.28.2 => 2.28.2 
    gatsby-plugin-react-helmet: ^3.6.0 => 3.6.0 
    gatsby-plugin-sass: ^2.7.0 => 2.7.0 
  npmGlobalPackages:
    gatsby-cli: 2.15.1

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by raRaRa** [comment]
Thanks for the quick response.

Try editing the app component:`/components/app/index.js` here: https://codesandbox.io/s/hardcore-voice-vpob3

I couldn't properly re-produce it when wrapping a page with connect, but refresh doesn't work for the app component.

Visit the `/app` route on the codesandbox to see it render the app component. Then try editing the component and it doesn't refresh.

**Comment by raRaRa** [comment]
P.s. are there any known issues with Redux and fast refresh when using `createPage`? E.g. to create signed in pages for `/app/*`

**Comment by Bartmr** [comment]
@raRaRa Redux `connect` wraps the component in a ES6 Class, which are not supported in React Fast Refresh (it only works with function components and hooks)

**Comment by Bartmr** [comment]
It's also important to note that Gatsby does not hot reload `wrapRootElement` (where you normally inject the Redux Store), so changes to this file or anything that it imports will cause a full reload.

There are ways to go around this issue by using module.hot.accepts and module.hot.data to keep the store instance between hot reloads in the `wrapRootElement`

**Comment by LekoArts** [comment]
Thanks @Bartmr for that information!

Also, I'm a bit confused. Currently we don't activate React Fast Refresh by default (even for React 17) so the Error Overlay/Hot-Loader you get is still react-hot-loader:

![image](https://user-images.githubusercontent.com/16143594/102327627-4aeac700-3f86-11eb-92f5-4da6a61394d2.png)

**Comment by Bartmr** [comment]
Sorry, I'm a bit on auto-pilot. Neither hot reload modes reload the wrapRootElement.

If you want to enable hot reload on `wrapRootElement` and your redux store just setup your `gatsby-browser.js` like this:
```javascript
/**
 * Implement Gatsby's Browser APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/browser-apis/
 */

import React, { useEffect, useState } from 'react';

const RootWrapper = (props) => {
  const [RootFrame, replaceRootFrame] = useState(
    () => require('./src/components/root-frame/root-frame').RootFrame,
  );

  useEffect(() => {
    if (module.hot) {
      module.hot.accept(
        ['./src/components/root-frame/root-frame'],
        function () {
          replaceRootFrame(
            () => require('./src/components/root-frame/root-frame').RootFrame,
          );
        },
      );
    }
  }, []);

  // RootFrame being the stuff that you want to render around the page
  return <RootFrame>{props.children}</RootFrame>;
};

export const wrapRootElement = ({ element }) => (
  <RootWrapper>{element}</RootWrapper>
);

```

...and `RootFrame` being:

```typescript
type ModuleHotData = {
  store?: ReturnType<typeof createStore>;
};

export const RootFrame = (props: { children: ReactNode }) => {
  const [store] = useState(() => {
    const storeFromPreviousRuntime = (module.hot?.data as
      | ModuleHotData
      | undefined)?.store;

    const store = storeFromPreviousRuntime || createStore();

    if (module.hot) {
      module.hot.dispose((data: ModuleHotData) => {
        data.store = store;
      });
    }

    return store;
  });

 // Not wrapping props.children in Fragments (<>) sometimes breaks the app
 return <>props.children</>
}
```

@KyleAMathews I think Gatsby should explain in the docs that Gatsbt Browser is not Hot Reloaded, as consequence Redux stores aren't persisted between Hot Reloads. This hack up here is what I do to have Hot Reload and Redux and not loose my state.

**Comment by wardpeet** [comment]
@Bartmr does it work out of the box when using react-refresh?

**Comment by Bartmr** [comment]
@wardpeet it should. It's what I've been using for 2 years to keep the store hot reloaded in Gatsby.
