### ISSUE TITLE
gatsby develop gets stuck on 'Source and transform nodes'

### ISSUE THREAD

**Issue by baloghrebecca** [gatsbyjs/gatsby#28632]
## Description

When I run "gatsby develop" it gets stuck on "source and transform nodes" for minutes (at least 10)/hours. So whenever the build IS finally running, I can't access the site, because the website keeps loading forever, even though I got a "success Building development bundle" in my logs. 

What I've tried:
- Clearing my cache (gatsby clean)
- Deleting my node modules + reinstalling them
- Resizing my terminal window (? weirdly something that seemed to work for some)

### Steps to reproduce

I'd love to but I'm not sure at all what could be causing it. But here is my link to the [github repo](https://github.com/baloghrebecca/reproduction).

1. Just run gatsby develop
2. It will get stuck on "source and transform nodes"

### Expected result

1. The development server should start in a timely manner. 
2. The page should work when I open localhost:8000

### Actual result

1. The development server takes FOREVER to start because it gets stuck on tuck on "source and transform nodes".
2. The page won't stop loading (stays blank) when I open up localhost:8000

### Environment

System:
OS: macOS 10.15.7
CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
Shell: 5.7.1 - /bin/zsh
Binaries:
Node: 14.5.0 - /usr/local/bin/node
Yarn: 1.22.4 - /usr/local/bin/yarn
npm: 6.14.9 - /usr/local/bin/npm
Languages:
Python: 2.7.16 - /usr/bin/python
Browsers:
Chrome: 87.0.4280.88
Edge: 87.0.664.60
Firefox: 82.0.3
Safari: 14.0
npmPackages:
gatsby: ^2.28.2 => 2.28.2
gatsby-image: ^2.4.12 => 2.4.12
gatsby-plugin-anchor-links: ^1.1.1 => 1.1.1
gatsby-plugin-favicon: ^3.1.6 => 3.1.6
gatsby-plugin-offline: ^3.2.9 => 3.2.9
gatsby-plugin-react-helmet: ^3.3.4 => 3.3.4
gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
gatsby-plugin-sass: ^2.3.4 => 2.3.4
gatsby-plugin-sharp: ^2.6.18 => 2.6.18
gatsby-plugin-smoothscroll: ^1.1.0 => 1.1.0
gatsby-plugin-snipcart: ^1.1.2 => 1.1.2
gatsby-plugin-snipcart-advanced: ^1.0.0 => 1.0.0
gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
gatsby-remark-images: ^3.3.10 => 3.3.10
gatsby-source-filesystem: ^2.0.28 => 2.0.28
gatsby-source-strapi: 0.0.12 => 0.0.12
gatsby-source-stripe: ^3.1.1 => 3.1.1
gatsby-transformer-remark: ^2.8.17 => 2.8.17
gatsby-transformer-sharp: ^2.5.10 => 2.5.10
npmGlobalPackages:
gatsby-cli: 2.15.1

**Comment by pvdz** [comment]
Is this the same problem as https://github.com/gatsbyjs/gatsby/issues/28625 ? Or is it a new problem? In that case, did you fix the other one?

**Comment by baloghrebecca** [comment]
> Is this the same problem as #28625 ? Or is it a new problem? In that case, did you fix the other one?
2 separate ones, unfortunately!

**Comment by pvdz** [comment]
I'll have a closer look at it tomorrow.

At quick glance the only thing I notice is that `makeRequest` is not catching the `reject` callback for the graphql call (it checks the .errors but not the call itself). That could hide something, even if it's not supposed to. Probably not the problem here but the site has too many deps for me to just see it right now.

**Comment by baloghrebecca** [comment]
> I'll have a closer look at it tomorrow.
> 
> At quick glance the only thing I notice is that `makeRequest` is not catching the `reject` callback for the graphql call (it checks the .errors but not the call itself). That could hide something, even if it's not supposed to. Probably not the problem here but the site has too many deps for me to just see it right now.

Thank you! If it's of any help, it worked fine just 2 weeks ago, and I didn't change anything in my code.

**Comment by pvdz** [comment]
I cloned and built your site. Site appears to build fine. The waiting time for sourcing without CLI update seems long, but it's on the plugin to print this. While debugging I noticed that some Shopify requests took a really long time to complete. And it's silent while doing stuff. We don't control that plugin so I'd suggest to file a request at https://github.com/njosefbeck/gatsby-source-stripe to make use of the progress bar, or to at least print some sign of life while doing stuff.

Beyond that, on my machine, a super cold build built your site in ~6 minutes on my machine, of which 5 minutes was spent sourcing. I can repro the other issue (nodes appear to be changed) so I'll dig a bit into that.

**Comment by vladar** [comment]
See also https://github.com/gatsbyjs/gatsby/issues/28625#issuecomment-748069954

FYI, do you even need `gatsby-source-stripe`? I don't see any usage of data sourced by this plugin in your website code. If I remove completely it the build doesn't fail. And sourcing step drops to 1.5 minutes.

**Comment by baloghrebecca** [comment]
Sorry for my late reply! YES! This was the solution. Thank you. I deleted `gatsby-source-stripe` and it's not stuck on `source and transform nodes` any longer. Thank you so much for looking into this issue.
