### ISSUE TITLE
Wrap sharp calls in try/catch to avoid crashing on bad images

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#28640]
A follow up to https://github.com/gatsbyjs/gatsby/pull/28614

Here are a few other places where sharp reads/writes images that don't seem to have try/catch setup around them.

https://github.com/gatsbyjs/gatsby/blob/b81e6bdb70fbda4f02739728f79b12c166b1a188/packages/gatsby-plugin-sharp/src/image-data.ts#L61

https://github.com/gatsbyjs/gatsby/blob/b81e6bdb70fbda4f02739728f79b12c166b1a188/packages/gatsby-plugin-sharp/src/duotone.js#L103-L123

https://github.com/gatsbyjs/gatsby/blob/b81e6bdb70fbda4f02739728f79b12c166b1a188/packages/gatsby-plugin-sharp/src/duotone.js#L18-L36

**Comment by nategiraudeau** [comment]
@KyleAMathews can I work on this?

**Comment by KyleAMathews** [comment]
Please do!

**Comment by lesagi** [comment]
Hi please let me know if you didn't work on that, I'm looking for the first issue for myself :)

**Comment by nategiraudeau** [comment]
I did. I'm just waiting for the PR to get merged: #28645
