### ISSUE TITLE
There was an error while compiling your site's GraphQL queries" error message

### ISSUE THREAD

**Issue by siwel** [gatsbyjs/gatsby#2867]
> There was an error while compiling your site's GraphQL queries" error message.

Whats the best way to get more information about GraphQL compiling errors? For example with the one above Is there an option to let you know what query?

Thanks, Lewis

**Comment by mattbag** [comment]
There is a verbose setting, but I could see it working only for wordpress-source-plugin.

It's likely that you have missing/deleted files/data and you're still pointing the query on those.
This answer is more for following the topic, but it might help as well.

**Comment by m-allanson** [comment]
@siwel I think this will be fixed by #2873

**Comment by siwel** [comment]
Thanks 👍
