### ISSUE TITLE
All Canonical URLs use offline-plugin-app-shell-fallback/ when deployed in Netlify

### ISSUE THREAD

**Issue by garlen-javier** [gatsbyjs/gatsby#28691]
I tried to use this plugin but seems all canonical url in the link tag are the same with offline-plugin-app-shell fallback as a slug in Netlify and not getting the right slug when checking at localhost, anyone knows why it is happening?

My website: https://www.meekcode.com/

**Issue from Netlify via view source:**
`<link rel="canonical" href="https://www.meekcode.com/offline-plugin-app-shell-fallback/" data-baseprotocol="https:" data-basehost="www.meekcode.com"/>`

**Issue from localhost view view source:**
`<link rel="canonical" href="https://www.meekcode.com/" data-baseprotocol="https:" data-basehost="www.meekcode.com"/>`

**Expected Result:**
`<link rel="canonical" href="https://www.meekcode.com/<MY SLUG SHOULD BE HERE NOT THE OFFLINE PLUGIN>/" data-baseprotocol="https:" data-basehost="www.meekcode.com"/>`

Snippet from gatsby-config.js
```
     {
      resolve: `gatsby-plugin-canonical-urls`,
      options: {
        siteUrl: settings.meta.siteUrl,
        stripQueryString: true,
      },
    },
    {
      resolve: `gatsby-plugin-gtag`,
      options: {
        // your google analytics tracking id
        trackingId: settings.meta.google_analytics,
        // Puts tracking script in the head instead of the body
        head: false,
        // enable ip anonymization
        anonymize: true,
      },
    },
    // {
    //   resolve: `gatsby-plugin-google-adsense`,
    //   options: {
    //     publisherId: settings.meta.google_adsense
    //   },
    // },
    {
      resolve: `gatsby-plugin-advanced-sitemap`,
      options: {
        exclude: [
          `/404`,
          `/login`,
          `/login-failed`,
          `/thanks`,
          `/search-result`,
          `/apps/app-temp-dont-deletemodifypublish`,
          `/blog/temp-post-dont-deletemodifypublish`,
          `/offline-plugin-app-shell-fallback`,
      ],
      }
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Meek Code`,
        short_name: `Meek Code`,
        start_url: `/`,
        background_color: `#f7f0eb`,
        theme_color: `#2c292a`,
        display: `standalone`,
        icon: `static/assets/meekcode.png`,
      },
    },
    {
      resolve: `gatsby-plugin-netlify`,
      options: {
        mergeSecurityHeaders: true,
      },
    },
    'gatsby-plugin-offline',
  ],
}
```

**Comment by vladar** [comment]
Check this out: https://www.gatsbyjs.com/plugins/gatsby-plugin-offline/#app-shell-and-server-logs (and the whole `Notes` section)
