### ISSUE TITLE
Breadcrumbs using click tracking is unpredictable

### ISSUE THREAD

**Issue by developdeez** [gatsbyjs/gatsby#28698]
## Description

My app uses gatsby with a Layout component I put on all of my pages.
I have the useBreadcrumbs in the Layout taking the location and a sent in title.
I noticed my page rerenders multiple times sending both the last and current titles to useBreadcrumb.
I also noticed this doesn't happen without this plugin.

There appears to be no working examples online.

How do you make this actually work on pages?

 
### Steps to reproduce

Add breadcrumbs as the example: https://www.gatsbyjs.com/plugins/gatsby-plugin-breadcrumb/

### Expected result

Breadcrumbs as expected

### Actual result

Unexpected breadcrumbs

### Environment

  System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.88
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.29.1 => 2.26.1 
    gatsby-image: ^2.8.0 => 2.5.0 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-apollo: ^3.0.2 => 3.0.2 
    gatsby-plugin-breadcrumb: ^10.0.0 => 10.0.0 
    gatsby-plugin-prettier-eslint: ^1.0.4 => 1.0.4 
    gatsby-plugin-sass: ^2.8.0 => 2.5.1 
    gatsby-plugin-sharp: ^2.11.1 => 2.8.0 
    gatsby-plugin-styled-components: ^3.7.0 => 3.4.0 
    gatsby-plugin-transition-link: ^1.20.5 => 1.20.5 
    gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1 
    gatsby-source-filesystem: ^2.8.0 => 2.5.0 
    gatsby-transformer-json: ^2.8.0 => 2.5.0 
    gatsby-transformer-sharp: ^2.9.0 => 2.6.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.113

**Comment by developdeez** [comment]
Seems to be related to Gatsby not handling context well.
My context
```
import { createContext, useState, useMemo } from "react";
const BreadcrumbsContext = () => {
  const [breadcrumbs, setBreadcrumbs] = useState([]);
  const value = useMemo(() => ({ breadcrumbs, setBreadcrumbs }), [
    breadcrumbs,
    setBreadcrumbs,
  ]);
  return createContext(value);
};

export default BreadcrumbsContext;
```

My usage:
`  const { breadcrumbs, setBreadcrumbs } = useContext(breadcrumbsContext());
  useEffect(() => {
    const crumbIdx = breadcrumbs.findIndex((crumb) => crumb.text === title);
    if (crumbIdx < 0) {
      setBreadcrumbs([
        ...breadcrumbs,
        { text: title, href: location.pathname },
      ]);
    }
  }, []);`

**Comment by vladar** [comment]
Hey, @developdeez 

I recommend you to open a new issue in the plugin repository: https://github.com/sbardian/gatsby-plugin-breadcrumb

As stated, this is slightly tangential to Gatsby. If this is not the case, or if we can help further--please don’t hesitate to reach out or comment on this issue, and we’d love to take another look.

Thanks for using Gatsby :muscle:

**Comment by developdeez** [comment]
@vladar i noticed this with any component needing context. I even tried setting a session value on load and when I went to the next page gatsby erased it sure to this rerender bug
