### ISSUE TITLE
gatsby-plugin-netlify: mergeLinkHeaders: true resulting in huge _headers files that fail builds

### ISSUE THREAD

**Issue by kaganjd** [gatsbyjs/gatsby#28693]
## Summary

Netlify support here 👋🏻 We've seen several customers in our helpdesk with large builds that time out and fail for the same reason: a very big (> 15MB) _headers file that was generated by `gatsby-plugin-netlify`. When they toggle `mergeLinkHeaders` to `false`, this resolves their issue. It seems like there be a documentation gap here about what that option does.

Here are the current docs on the plugin: https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify/

### Motivation

Less frustration for Gatsby developers who are deploying large sites on Netlify

Let me know if we can provide any other info to help!

**Comment by wardpeet** [comment]
@kaganjd is it possible to share a headers file through email? ward@gatsbyjs.com

**Comment by kaganjd** [comment]
We can't due to data privacy stuff, but we've let the most recent customer who hit this know they can share their _headers file with you directly if they want.

**Comment by isabelleingato** [comment]
Hey @wardpeet and @kaganjd,

I'm new here, and I'd like to grab this one. Would that be okay?

**Comment by kaganjd** [comment]
Hey @isabelleingato- thanks so much for opening a PR for this! I don't know what the process is on the Gatsby side but it looks like your PR didn't pass CI tests so it never got automatically merged. Would you be up for digging into whatever's wrong?

**Comment by isabelleingato** [comment]
> Hey @isabelleingato- thanks so much for opening a PR for this! I don't know what the process is on the Gatsby side but it looks like your PR didn't pass CI tests so it never got automatically merged. Would you be up for digging into whatever's wrong?

@kaganjd Thanks for the heads up, I just needed to merge master! The update to the README is now merged.

**Comment by kaganjd** [comment]
Amazing! Many thanks from the Netlify Support team- this will be a big help for us.
