### ISSUE TITLE
Gatsby + reach router Links 404 in development

### ISSUE THREAD

**Issue by beatyt** [gatsbyjs/gatsby#28702]
## Description

While running `gatsby develop` valid URLs will return 404s. However, once `gatsby build` and `gatsby serve` are run, the links work fine. These URLs are using Reach Router for navigation.

### Steps to reproduce

1. `git clone git@github.com:beatyt/gatsby-reach-router-404s-repro.git` 
2. `npm run start`
3. Click the link to `Blog` that shows on the page at `http://localhost:8000`
4. It should 404

![image](https://user-images.githubusercontent.com/1040103/102692567-2ab74400-41e2-11eb-8386-22eb2feff931.png)

Link to my repository reproducing the issue:  https://github.com/beatyt/gatsby-reach-router-404s-repro

### Expected result

Navigating to the link should show the page.

### Actual result

The 404 page is shown instead.

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.9 - ~\AppData\Roaming\npm\npm.CMD
  Languages:
    Python: 3.5.1 - /c/Python35/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.26.1 => 2.29.1
    gatsby-image: ^2.8.0 => 2.8.0
    gatsby-plugin-manifest: ^2.9.0 => 2.9.0
    gatsby-plugin-mdx: ^1.7.0 => 1.7.0
    gatsby-plugin-offline: ^3.7.0 => 3.7.0
    gatsby-plugin-react-helmet: ^3.7.0 => 3.7.0
    gatsby-plugin-sass: ^2.8.0 => 2.8.0
    gatsby-plugin-sharp: ^2.11.1 => 2.11.1
    gatsby-plugin-sitemap: ^2.9.0 => 2.9.0
    gatsby-remark-copy-linked-files: ^2.7.0 => 2.7.0
    gatsby-remark-images: ^3.8.0 => 3.8.0
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-filesystem: ^2.8.0 => 2.8.0
    gatsby-transformer-remark: ^2.13.0 => 2.13.0
    gatsby-transformer-sharp: ^2.9.0 => 2.9.0
  npmGlobalPackages:
    gatsby-cli: 2.12.31

**Comment by pieh** [comment]
Thanks for opening issue @beatyt!

This issue is already tracked in https://github.com/gatsbyjs/gatsby/issues/27196 , so I'll close this as duplicate
