### ISSUE TITLE
"Panicking" (Infinite Recompile) Error Message Provides No Diagnostic Info

### ISSUE THREAD

**Issue by machineghost** [gatsbyjs/gatsby#28704]
## Description

When you use Gatsby, even with a consistent/automated API (eg. Postgraphile), you can sometimes run into:

>error Panicking because nodes appear to be being changed every time we run queries. This would cause the site to recompile infinitely. 
>Check custom resolvers to see if they are unconditionally creating or mutating nodes on every query. 
>This may happen if they create nodes with a field that is different every time, such as a timestamp or unique id.

### Steps to reproduce

If I knew how to do this, I wouldn't be filing the bug :)

The problem is, when this error occurs it's completely opaque to the user: you just suddenly get the error out of the blue, and you don't get any indication as to what caused it.

### Expected result

When any library throws any opaque error, it should do its best to inform the user of as many helpful details about the error as possible.  In this case, that would mean surfacing as much info as possible about the actions which caused the infinite loop.

### Actual result

Currently the message barely tells you anything (basically just "one of your many endpoints isn't doing what we want").  What would be _much_ more helpful is if the message told you what fields caused the error ... and it appears to have that info available already.

The error is thrown from this action: `panicBecauseOfInfiniteLoop` (in https://github.com/gatsbyjs/gatsby/blob/903439bcb4c909c1881cb3139b7545b161ea580b/packages/gatsby/src/state-machines/develop/actions.ts).

According to the type that action gets (but currently ignores) an `IBuildContext` argument.  That type (https://github.com/gatsbyjs/gatsby/blob/903439bcb4c909c1881cb3139b7545b161ea580b/packages/gatsby/src/services/types.ts) has a `nodeMutationBatch` property, which is an `Array<IMutationAction>`.

An `IMutationAction` in turn has a `payload` property, which contains the arguments passed to it when it was enqueued, as well as a `type`.  Since Gatsby already has all this information available to it, it would be handy if it surfaced that info (action type + payload, for every mutation in the batch) when this error was thrown.

If desired I would be willing to submit a PR for this.

### Environment

  System:
    OS: Linux 5.4 Linux Mint 20 (Ulyana)
    CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/bin/node
    npm: 6.14.8 - /usr/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 83.0
  npmPackages:
    gatsby: ^2.24.91 => 2.25.3
    gatsby-cli: ^2.12.113 => 2.12.113
    gatsby-image: ^2.4.21 => 2.4.21
    gatsby-plugin-google-analytics: ^2.3.19 => 2.3.19
    gatsby-plugin-import: ^2.1.6 => 2.1.6
    gatsby-plugin-manifest: ^2.4.37 => 2.4.37
    gatsby-plugin-modal-routing: /home/jeremy/temp/gatsby-plugin-modal-routing => 1.2.0
    gatsby-plugin-offline: ^3.2.38 => 3.2.38
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-s3: ^0.3.8 => 0.3.8
    gatsby-plugin-sharp: ^2.6.43 => 2.6.43
    gatsby-plugin-sitemap: ^2.4.17 => 2.4.17
    gatsby-plugin-styled-components: ^3.6.0 => 3.6.0
    gatsby-source-filesystem: ^2.3.37 => 2.3.37
    gatsby-source-pg: ^0.2.1 => 0.2.1
    gatsby-transformer-sharp: ^2.5.20 => 2.5.20
  npmGlobalPackages:
    gatsby: 2.24.73

**Comment by KyleAMathews** [comment]
This is with gatsby-source-graphql I assume?

**Comment by machineghost** [comment]
Correct

**Comment by machineghost** [comment]
Just to reiterate, I'm happy to submit a PR ... but I just don't want to go through the effort if it's not wanted.

I'd really like to get this fixed though: having my devsite crash mysteriously/constantly is **really** annoying.

**Comment by KyleAMathews** [comment]
Please file the PR! Yeah anytime an error doesn't have enough info to solve it that needs fixed.

**Comment by machineghost** [comment]
Hmmm ... are there build instructions anywhere?  You seem to have some sort of monorepo, but I can't find any instructions on how to get it up and running (not even on https://www.gatsbyjs.com/contributing/how-to-open-a-pull-request/).

**Comment by KyleAMathews** [comment]
Yeah here's the doc page
https://www.gatsbyjs.com/contributing/setting-up-your-local-dev-environment/
--
Kyle Mathews

Blog: *http://bricolage.io <http://bricolage.io>*
Twitter: http://twitter.com/kylemathews

**Comment by benedyktdryl** [comment]
@machineghost have you had a chance to work on this PR? I can help you with that as I am struggling with the same issue.

**Comment by machineghost** [comment]
No, sorry ... I wound up abandoning Gatsby (after running into a large number of errors; I didn't give up just because of this one).

**Comment by benedyktdryl** [comment]
Well, that is sad but kinda true. My error about panicking is coming randomly from Gatsby used with Docz and I have no idea what is causing that. It's just failing randomly when I increase the number of components (operating on a kinda big codebase).

@KyleAMathews do you have any idea how I can debug this error? I know I should provide repro but that is the point - base configuration works fine, running it on my codebase is just "panicking" randomly.

**Comment by raphaelcunha** [comment]
> Well, that is sad but kinda true. My error about panicking is coming randomly from Gatsby used with Docz and I have no idea what is causing that. It's just failing randomly when I increase the number of components (operating on a kinda big codebase).
> 
> @KyleAMathews do you have any idea how I can debug this error? I know I should provide repro but that is the point - base configuration works fine, running it on my codebase is just "panicking" randomly.

You have any solution for this "Panicking"? I have the same problem?
