### ISSUE TITLE
No matching version found for bash-glob@1.0.2

### ISSUE THREAD

**Issue by posebear1990** [gatsbyjs/gatsby#2872]
I have a problem when I exec `gatsby new modern_front_end_development` command in the latest version of gatsby.
This is npm error log:
```bash
npm ERR! code ETARGET
npm ERR! notarget No matching version found for bash-glob@1.0.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'gatsby-starter-default'
npm ERR! notarget 
```

**Comment by KyleAMathews** [comment]
Try again? There is a bash-glob@1.0.2 so perhaps NPM just had a network glitch or something.

**Comment by KyleAMathews** [comment]
Also just ran `gatsby new test-gatsby-site` and it installed fine.

Good luck getting going on modern front end development :-)

**Comment by posebear1990** [comment]
THX, it works at latest version of gatsby.😃
