### ISSUE TITLE
Avoid loading polyfill (gatsby-legacy-polyfills)

### ISSUE THREAD

**Issue by devquestionz** [gatsbyjs/gatsby#28736]
## Description

I used [this tool](https://www.gatsbyjs.com/plugins/gatsby-plugin-webpack-bundle-analyser-v2/) to see the js loaded in the project and I see polyfills - I am trying to not load `node_modules/gatsby-legacy-polyfills/dist` at all - I tried to set browserlists to just latest chrome but still polyfills loads. How can I make sure polyfills is not loaded at all?

### Steps to reproduce

Set browserlist to 
```
"browserslist": [
    "last 2 Chrome versions"
  ],
```

- run gatsby clean
- run gatsby build
- polyfill is still loaded

### Expected result

polyfill should not be loaded

### Actual result

using [this tool ](https://www.gatsbyjs.com/plugins/gatsby-plugin-webpack-bundle-analyser-v2/)I can see that polyfill.js is loaded

### Environment

```
  Binaries:
    Node: 12.19.0
    Yarn: 1.21.1 
    npm: 6.14.8
  Languages:
    Python: 2.7.16
  npmPackages:
    gatsby: ^2.27.0 => 2.27.0 
    gatsby-cli: 2.13.1
```

**Comment by KyleAMathews** [comment]
Hi that bundle is generated on every build but only loads on older browsers. Try it yourself and load a site in chrome. The polyfill is in the html but won't load (as seen in the network tab). This way Gatsby can support older browsers but not load polyfills when they're not needed.

The bundle analyzer just shows all created bundles and isn't going to be an accurate representation in this case of what the browser loads.
