### ISSUE TITLE
Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by DCStudioProjects** [gatsbyjs/gatsby#28733]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

I will be able to install and run a Gatsby site locally

### Actual result
There was an error while installing:
Error: Something went wrong installing the "sharp" module
  Cannot find module '../build/Release/sharp.node'
  Require stack:
  - C:\Users\4idan\Desktop\react-developer\node_modules\sharp\lib\constructor.js
  - C:\Users\4idan\Desktop\react-developer\node_modules\sharp\lib\index.js
  - C:\Users\4idan\Desktop\react-developer\node_modules\gatsby-plugin-manifest\safe-sharp.js
  - C:\Users\4idan\Desktop\react-developer\node_modules\gatsby-plugin-manifest\gatsby-node.js
  - C:\Users\4idan\Desktop\react-developer\node_modules\gatsby\dist\bootstrap\resolve-module-exports.js
  - C:\Users\4idan\Desktop\react-developer\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
  - C:\Users\4idan\Desktop\react-developer\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
  - C:\Users\4idan\Desktop\react-developer\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
  - C:\Users\4idan\Desktop\react-developer\node_modules\gatsby\dist\bootstrap\index.js
  - C:\Users\4idan\Desktop\react-developer\node_modules\gatsby\dist\commands\develop.js
  - C:\Users\4idan\AppData\Roaming\npm\node_modules\gatsby-cli\lib\create-cli.js
  - C:\Users\4idan\AppData\Roaming\npm\node_modules\gatsby-cli\lib\index.js
  - C:\Users\4idan\AppData\Roaming\npm\node_modules\gatsby-cli\cli.js
  - Run "npm rebuild --verbose sharp" and look for errors
  - Consult the installation documentation at https://sharp.pixelplumbing.com/install
  - Search for this error at https://github.com/lovell/sharp/issues
### Environment

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 15.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.0.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.0 - /c/Python39/python
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.66)
  npmPackages:
    gatsby: ^2.21.0 => 2.21.0 
    gatsby-plugin-dark-mode: ^1.1.1 => 1.1.1 
    gatsby-plugin-google-analytics: ^2.1.36 => 2.1.36 
    gatsby-plugin-manifest: ^2.4.1 => 2.4.1 
    gatsby-plugin-netlify-cms: ^4.1.38 => 4.1.38 
    gatsby-plugin-offline: ^3.2.0 => 3.2.0 
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22 
    gatsby-plugin-sass: ^2.1.28 => 2.1.28 
    gatsby-plugin-sitemap: ^2.4.0 => 2.4.0 
    gatsby-remark-emojis: ^0.4.2 => 0.4.2 
    gatsby-remark-prismjs: ^3.3.31 => 3.3.31 
    gatsby-source-filesystem: ^2.1.48 => 2.1.48 
    gatsby-transformer-remark: ^2.6.53 => 2.6.53 
  npmGlobalPackages:
    gatsby-cli: 2.16.1

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by Slapbox** [comment]
Just started upgrading a 16 month old site and immediately hit this. I'm not sure what I'm using that is invoking Sharp?

**Comment by KyleAMathews** [comment]
Try running "npm rebuild sharp". That often fixes things

**Comment by DCStudioProjects** [comment]
Thnx a lot, but I gave up :), it was a very old repo, there were a lot of other errors, but I think that this issue could help other coders to find a solutions.

**Comment by ajj-siraj** [comment]
It's most likely your node version, I think. I started noticing this error in many of my projects ever since upgrading to v15.3. I had v12.3 before encountering this error on nearly every project, gatsby or otherwise. But then again I also updated my Windows 10 simultaneously (major feature update) so it could be a combination of both.

I forgot how I got rid of this error but I did everything you can think of:
- reinstall or repair nodejs (and the additional Visual C++ redistributables).
- remove node_modules and package-lock.json and run npm install.
- npm cache clean --force, and then do the previous step again.
- npm rebuild --verbose sharp (I ran this after almost every try).

I spent days on this so I probably did other things as well but I can't remember. The only thing I didn't try was to downgrade node back to 12.3.

**Comment by DCStudioProjects** [comment]
> It's most likely your node version, I think. I started noticing this error in many of my projects ever since upgrading to v15.3. I had v12.3 before encountering this error on nearly every project, gatsby or otherwise. But then again I also updated my Windows 10 simultaneously (major feature update) so it could be a combination of both.
> 
> I forgot how I got rid of this error but I did everything you can think of:
> 
> * reinstall or repair nodejs (and the additional Visual C++ redistributables).
> * remove node_modules and package-lock.json and run npm install.
> * npm cache clean --force, and then do the previous step again.
> * npm rebuild --verbose sharp (I ran this after almost every try).
> 
> I spent days on this so I probably did other things as well but I can't remember. The only thing I didn't try was to downgrade node back to 12.3.

It only happens on Netlify or Vercel, they download packages and installing dependencies again and again with every deployment. Everything is ok on my localhost. But unfortunately, problem occurs when I try to deploy via Vercel & Netlify, etc.

**Comment by DCStudioProjects** [comment]
> It's most likely your node version, I think. I started noticing this error in many of my projects ever since upgrading to v15.3. I had v12.3 before encountering this error on nearly every project, gatsby or otherwise. But then again I also updated my Windows 10 simultaneously (major feature update) so it could be a combination of both.
> 
> I forgot how I got rid of this error but I did everything you can think of:
> 
> * reinstall or repair nodejs (and the additional Visual C++ redistributables).
> * remove node_modules and package-lock.json and run npm install.
> * npm cache clean --force, and then do the previous step again.
> * npm rebuild --verbose sharp (I ran this after almost every try).
> 
> I spent days on this so I probably did other things as well but I can't remember. The only thing I didn't try was to downgrade node back to 12.3.

This helped me with #28748 issue, thanks again. Merry Christmas and good luck!
