### ISSUE TITLE
error "gatsby-plugin-manifest" threw an error while running the onPostBootstrap lifecycle

### ISSUE THREAD

**Issue by DCStudioProjects** [gatsbyjs/gatsby#28748]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

gatsby build succesfully compilation

### Actual result

error "gatsby-plugin-manifest" threw an error while running the onPostBootstrap lifecycle:
--
20:49:08.045 | Input file contains unsupported image format
20:49:08.053 |  
20:49:08.053 | Error: Input file contains unsupported image format
20:49:08.053 |  
20:49:08.054 | not finished onPostBootstrap - 0.013s
20:49:09.612 | npm ERR! code ELIFECYCLE
20:49:09.612 | npm ERR! errno 1
20:49:09.617 | npm ERR! gatsby-starter-default@0.1.0 build: `gatsby build`
20:49:09.617 | npm ERR! Exit status 1
20:49:09.617 | npm ERR!
20:49:09.617 | npm ERR! Failed at the gatsby-starter-default@0.1.0 build script.
20:49:09.617 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
20:49:09.631 | npm ERR! A complete log of this run can be found in:
20:49:09.631 | npm ERR!     /vercel/.npm/_logs/2020-12-23T17_49_09_617Z-debug.log
20:49:09.636 | Error: Command "npm run build" exited with 1
20:49:11.990 | Done with "package.json"

### Environment

Vercel or Netlify
When I run via localhost everything is working good
Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by DCStudioProjects** [comment]
> ## Description
> error "gatsby-plugin-manifest" threw an error while running the onPostBootstrap lifecycle
> 
> ### Steps to reproduce
> Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).
> 
> How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/
> 
> ### Expected result
> gatsby build succesfully compilation
> 
> ### Actual result
> ## error "gatsby-plugin-manifest" threw an error while running the onPostBootstrap lifecycle:
> 20:49:08.045 | Input file contains unsupported image format
> 20:49:08.053 |  
> 20:49:08.053 | Error: Input file contains unsupported image format
> 20:49:08.053 |  
> 20:49:08.054 | not finished onPostBootstrap - 0.013s
> 20:49:09.612 | npm ERR! code ELIFECYCLE
> 20:49:09.612 | npm ERR! errno 1
> 20:49:09.617 | npm ERR! gatsby-starter-default@0.1.0 build: `gatsby build`
> 20:49:09.617 | npm ERR! Exit status 1
> 20:49:09.617 | npm ERR!
> 20:49:09.617 | npm ERR! Failed at the gatsby-starter-default@0.1.0 build script.
> 20:49:09.617 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 20:49:09.631 | npm ERR! A complete log of this run can be found in:
> 20:49:09.631 | npm ERR! /vercel/.npm/_logs/2020-12-23T17_49_09_617Z-debug.log
> 20:49:09.636 | Error: Command "npm run build" exited with 1
> 20:49:11.990 | Done with "package.json"
> 
> ### Environment
> Vercel or Netlify
> When I run via localhost everything is working good
> Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by rolwin100** [comment]
I'm facing the same issue on netlify and local its working fine any help anyone.

**Comment by DCStudioProjects** [comment]
> I'm facing the same issue on netlify and local its working fine any help anyone.

#28733

**Comment by rolwin100** [comment]
@DCStudioProjects this issue is casued on netlify and I tried running the command npm rebuild sharp its still not workiing

**Comment by DCStudioProjects** [comment]
> @DCStudioProjects this issue is casued on netlify and I tried running the command npm rebuild sharp its still not workiing

Did u make them step by step?

**Comment by billschnoebelen** [comment]
> > @DCStudioProjects this issue is casued on netlify and I tried running the command npm rebuild sharp its still not workiing
> 
> Make these step by step:
> 
> 1. Remove node_modules
> 2. npm cache clean --force
> 3. npm rebuild --verbose sharp
> 
> It solved my problem

This seemed to work for me, but with additional steps. I deleted netlify, github, and package-lock.json and started over. I also deleted some of my test blogs which may have caused the issue?

**Comment by DCStudioProjects** [comment]
> > > @DCStudioProjects this issue is casued on netlify and I tried running the command npm rebuild sharp its still not workiing
> > 
> > Make these step by step:
> > 
> > 1. Remove node_modules
> > 2. npm cache clean --force
> > 3. npm rebuild --verbose sharp
> > 
> > It solved my problem
> 
> This seemed to work for me, but with additional steps. I deleted netlify, github, and package-lock.json and started over. I also deleted some of my test blogs which may have caused the issue?
> 
> 

Yea, sure, I forgot to add a package-lock.json removing to list, I'm sorry!

**Comment by billschnoebelen** [comment]
> > > > @DCStudioProjects 

Thanks for the help!

**Comment by romulobastos** [comment]
> > @DCStudioProjects this issue is casued on netlify and I tried running the command npm rebuild sharp its still not workiing
> 
> Make these step by step:
> 
> 1. Remove node_modules
> 2. npm cache clean --force
> 3. npm rebuild --verbose sharp
> 4. Remove package-lock.json
> 5. Run `npm install`.
> 
> It solved my problem.

In my case, I need to remove yarn.lock too. It works fine. Thank you! ;)

**Comment by connorocampo** [comment]
> > @DCStudioProjects this issue is casued on netlify and I tried running the command npm rebuild sharp its still not workiing
> 
> Make these step by step:
> 
> 1. Remove node_modules
> 2. npm cache clean --force
> 3. npm rebuild --verbose sharp
> 4. Remove package-lock.json
> 5. Run `npm install`.
> 
> It solved my problem.

I just had this issue. Been trying to solve it for a while and this worked for me. Right now you are my hero.

**Comment by mbernardes19** [comment]
> > @DCStudioProjects this issue is casued on netlify and I tried running the command npm rebuild sharp its still not workiing
> 
> Make these step by step:
> 
> 1. Remove node_modules
> 2. npm cache clean --force
> 3. npm rebuild --verbose sharp
> 4. Remove package-lock.json
> 5. Run `npm install`.
> 
> It solved my problem.

Just had to remove package-lock.json and it worked for me. Thanks a lot!

**Comment by rishFilet** [comment]
Never mind, this was sovled because of my gatsby-config setup:
`
{
      resolve: 'gatsby-plugin-manifest',
      options: {
        icon: 'src/images/icon.png',
      },
    },
`

This path does not exist
