### ISSUE TITLE
"gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:

### ISSUE THREAD

**Issue by mohomedanees** [gatsbyjs/gatsby#28766]
Hi tried running my project which is the hello world template from Gatsby when I ran npm run develop it gives the below errors.

![Screenshot 2020-12-27 at 23 51 46](https://user-images.githubusercontent.com/12741808/103177267-040ea280-489f-11eb-9e95-fb4a92ebdf3f.png)

I'm trying to get the data from graphql plugins which I have installed in my wordpress site. The plugins are 
WP GraphiQL, WP GraphQL and WPGraphQL for Advanced Custom Fields.

How can I fix this issue.

**Comment by mohomedanees** [comment]
What can be done for this to fix ?

**Comment by KyleAMathews** [comment]
Try to verify that `gatsby-source-graphql` is setup correctly? `Unexpected token <` generally means that its HTML (or some other XML-based document) and not JSON which means that you're not correctly running GraphQL queries.

The error should be improved to show what the string looks like that couldn't be parsed.

**Comment by LekoArts** [comment]
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
