### ISSUE TITLE
Sometimes `gatsby build` doesn't minify the commons-*.js file

### ISSUE THREAD

**Issue by resir014** [gatsbyjs/gatsby#2877]
* **Gatsby version:** `gatsby 1.9.106`, `gatsby-cli 1.1.20`
* **Node version:** 8.9.0
* **OS:** Windows 10 (x64)

I've brought up this issue on the Reactiflux chat the other day, but I'm going to put it as an issue here since it's potentially an issue on both Gatsby and Netlify.

On some occasions,`gatsby build` doesn't generate a minified `commons-*.js` file:

![image](https://user-images.githubusercontent.com/5663877/32667280-db42044e-c66c-11e7-8498-5c3fd200adcd.png)

This could sometimes result in the React Devtools saying that I'm *not* running a minified build of React whenever I deploy to Netlify with Continuous Deployment:

![image](https://user-images.githubusercontent.com/5663877/32667613-b88407a8-c66d-11e7-8af7-633331f71456.png)

Running `gatsby build` and manually deploying everything to Netlify will cause React Devtools to behave, however the resulting `commons-*.js` file remains unminified.

**Comment by sebastienfi** [comment]
See my post here, maybe it helps https://github.com/gatsbyjs/gatsby/issues/2771

**Comment by resir014** [comment]
@sebastienfi ah, thanks a lot! I can close this as a duplicate then.

**Comment by resir014** [comment]
Reopening this to post my solution.

`gatsby-node.js`

```js
exports.modifyWebpackConfig = ({ config, stage }) => {
  if (stage === 'build-javascript') {
    // Here we override the Webpack plugin during building the JS bundles
    // to make everything compile down to es5 - turns out Webpack v1 doesn't
    // like that we have some ES6 stuff littered in our final bundle...
    config.loader('typescript', {
      test: /\.tsx?$/,
      loaders: ['ts-loader']
    })
  }
}
```

`tsconfig.json`

```json
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es5",
    "jsx": "react",
    "lib": ["dom", "esnext"]
  },
  "include": [
    "./src/**/*"
  ]
}
```

**Comment by Cammisuli** [comment]
I tried to follow the advice from @resir014's post, but I kept getting `Cannot read property 'initial' of undefined`.

So, I found the proper solution for me, and maybe this could help  others in the future. In the plugin section of `gatsby-config.js`, specify the typescript target in compilerOptions to `'es5'`
```
{
  resolve: "gatsby-plugin-typescript",
  options: {
    compilerOptions: {
      target: 'es5'
    }
  }
}
```

**Comment by resir014** [comment]
@Cammisuli Please update `gatsby-plugin-typescript`. This whole issue is fixed on https://github.com/gatsbyjs/gatsby/pull/3369, so the workaround is no longer needed.
