### ISSUE TITLE
Security vulnerability reported in highlight.js

### ISSUE THREAD

**Issue by wkilday** [gatsbyjs/gatsby#28781]
Github's Dependabot is flagging Gatsby with a [vulnerability](https://github.com/highlightjs/highlight.js/security/advisories/GHSA-7wwv-vh3v-89cq) in `highlight.js@^8.1.0` via a dependency on `hicat@0.7.0`.

The vulnerability is fixed in `highlight.js@10.4.1`, which [`hicat@0.8.0`](https://github.com/rstacruz/hicat/pull/9/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R19) uses.

Updating the hicat dependency in gatsby-recipes should resolve this vulnerability.  Pull Request #28545 is already doing that, so getting it reviewed and merged should be enough.

**Comment by JackHowa** [comment]
@LekoArts @wkilday have a more specific pr that might avoid any other ci issues of #28545. Let me know if there's anything else there with #28860

**Comment by JackHowa** [comment]
seems like https://github.com/gatsbyjs/gatsby/pull/28545 is ready to go... saw the axios warning in gatsby as well
