### ISSUE TITLE
default behaviour - gatsby plugin canonical urls

### ISSUE THREAD

**Issue by jmau111** [gatsbyjs/gatsby#28790]
## Description

Hi, thanks for great tool. I've been testing some codes with https://www.gatsbyjs.com/plugins/gatsby-plugin-canonical-urls/

I think `stripQueryString` should be `true` by default.

It says that URL search parameters are included in the canonical URL by default, but here that means any URL gets that configuration with any get parameter, which is kinda risky IMHO.

Another default behaviour that looks strange to me is the canonical on 404 pages : 

```
<link rel="canonical" href="https://www.example.com/dsdsds" data-baseprotocol="https:" data-basehost="www.example.com">
```

### Expected result

- `stripQueryString` set to true by default
- another parameter to whitelist in `gatsby-config.js` the GET param used if we need  `stripQueryString` to be set to false
- no canonical on 404 pages

### Actual result

- no strip of get params
- any GET parameter is in the canonical URL
- there's a canonical on 404 pages

### Environment

A fresh install of Gatsby (after a `gatsby new`) with the plugin gatsby-plugin-canonical-urls.

**Comment by ashiishme** [comment]
@lekoArts & @jmau111  Can I pick this issue?
