### ISSUE TITLE
Async onCreateNode does not update GraphQL on hot-reload

### ISSUE THREAD

**Issue by stldo** [gatsbyjs/gatsby#28795]
## Description

I'm calling `createNode` after resolving some async functions in a transformer. If these functions take a little longer to return a value, like 100ms, the field is not accessible by GraphQL queries during hot-reload, returning an error like the following:

```
There was an error in your GraphQL query:

Cannot query field "Field" on type "Query".
```

The fields are created normally during the first boot, but triggering hot-reload returns this error. It could be related to https://github.com/gatsbyjs/gatsby/issues/26580.

### Steps to reproduce

I've made a reproduction, available at https://github.com/stldo/timeout-example. Start the development server using `gatsby develop` and everything should work fine. After editing the file `src/data.json`, Gatsby will throw the error `Cannot query field "timeoutB" on type "Query".` on hot-reload — `timeoutB` returns its value after a timeout, while `timeoutA` returns its value immediately.

### Expected result

`timeoutB` value should be accessible by GraphQL after a hot-reload even after the timeout.

### Actual result

An error is returned.

### Environment

```
  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (2) x64 Intel(R) Xeon(R) CPU @ 2.30GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.15.3 - ~/.local/bin/node
    Yarn: 1.22.10 - /usr/local/nvm/versions/node/v10.14.2/bin/yarn
    npm: 6.14.10 - ~/.local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    gatsby: ^2.29.3 => 2.29.3
    gatsby-source-filesystem: ^2.8.1 => 2.8.1
  npmGlobalPackages:
    gatsby: 2.29.2
```

**Comment by KyleAMathews** [comment]
What happens if you remove the Promise.resolve?

**Comment by stldo** [comment]
Both will fail if I remove Promise.resolve, as createNode will receive a Promise instead of a node object. The promises are just to simulate the condition on which this error happens. Therefore, removing them entirely will make everything work just as expected.

**Comment by stldo** [comment]
Adding a timeout just before the following line, greater than the time `timeoutB` takes to resolve — like `await new Promise(resolve => setTimeout(resolve, 2000))`:

https://github.com/gatsbyjs/gatsby/blob/10dfe011c368e28e8de19f0f5569748ebb9a6bc3/packages/gatsby/src/schema/index.js#L105

makes everything work as expected. Adding a timeout before the following line has the same effect:

https://github.com/gatsbyjs/gatsby/blob/10dfe011c368e28e8de19f0f5569748ebb9a6bc3/packages/gatsby/src/schema/infer/index.js#L19

`hasNodes` is not returning true for these nodes because `typeMetadata.total` value is `0` until they are resolved — that's why the timeout trick works. It seems that type information is taken from Redux, through `inferenceMetadata`:

https://github.com/gatsbyjs/gatsby/blob/10dfe011c368e28e8de19f0f5569748ebb9a6bc3/packages/gatsby/src/schema/index.js#L99

I don't have much time to help furthermore right now, but I hope that this information helps.
