### ISSUE TITLE
gatsby-remark-images prevents box-shadow styling of images (workaround included)

### ISSUE THREAD

**Issue by joostdecock** [gatsbyjs/gatsby#28798]
## Description

The `gatsby-remark-images plugin [sets the box-shadow CSS property inline on the img element](https://github.com/gatsbyjs/gatsby/blob/2059ead7ff0bcfa0897b1606cbfa559835b97f84/packages/gatsby-remark-images/src/gatsby-browser.js#L33).

This prevents setting that property in CSS because in-lines style takes precedence. Which is unfortunate, because a shadow effect on images is a rather common style:

![Screenshot_2020-12-30 Images](https://user-images.githubusercontent.com/1708494/103342744-a048cd00-4a8a-11eb-8997-6a7b51cb76de.png)

Because the code copies in the `backgroundColor` option:

```js
imageElement.style.boxShadow = `inset 0px 0px 0px 400px ${options.backgroundColor}`
```

I was able to work around this with this configuration:

```js
backgroundColor: `, 0 1px 3px 0 rgba(0, 0, 0, 0.2), 0 1px 1px 0 rgba(0, 0, 0, 0.14), 0 2px 1px -1px rgba(0, 0, 0, 0.12)`
```

Which results in the screenshot I included above, which has the shadow I want.

However, that seems rather hackish to say the least, so I think it would be worthwhile to add an option to prevent the `box-shadow` CSS property to be set so it can be styled in CSS.

I'm too busy to submit a PR for this at this point, so I'm creating this issue as a reminder. I might be able to get around it at a later time. If somebody else wants to tackle this, obviously that's great too :slightly_smiling_face: 

### Steps to reproduce

Set up a site with markdown processing, try to apply a box-shadow to images added with gatsby-remark-images, it won't work.

I will try to re-visit this issue later to add a reproduction site.

### Expected result

When I add CSS like this:

```css
img.gatsby-resp-image-image {
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.2), 0 1px 1px 0 rgba(0, 0, 0, 0.14), 0 2px 1px -1px rgba(0, 0, 0, 0.12);
}
```

I expect it to look like this:

![Screenshot_2020-12-30 Images](https://user-images.githubusercontent.com/1708494/103342744-a048cd00-4a8a-11eb-8997-6a7b51cb76de.png)

### Actual result

No shadow:

![Screenshot_2020-12-30 Images(2)](https://user-images.githubusercontent.com/1708494/103343308-1699ff00-4a8c-11eb-90a0-9c60677b61bd.png)

What happened.

### Environment

```

  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Browsers:
    Chrome: 54.0.2840.90
    Firefox: 84.0
  npmPackages:
    gatsby: ^2.25.4 => 2.29.2 
    gatsby-image: 2.8.0 => 2.8.0 
    gatsby-link: 2.8.0 => 2.8.0 
    gatsby-plugin-algolia: 0.16.2 => 0.16.2 
    gatsby-plugin-catch-links: 2.7.0 => 2.7.0 
    gatsby-plugin-manifest: ^2.4.18 => 2.9.1 
    gatsby-plugin-mdx: 1.7.1 => 1.7.1 
    gatsby-plugin-netlify: 2.8.0 => 2.8.0 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-nprogress: 2.7.0 => 2.7.0 
    gatsby-plugin-offline: ^3.2.18 => 3.7.1 
    gatsby-plugin-react-helmet: 3.7.0 => 3.7.0 
    gatsby-plugin-sass: ^2.3.12 => 2.8.0 
    gatsby-plugin-sharp: 2.11.2 => 2.11.2 
    gatsby-plugin-styled-components: 3.7.0 => 3.7.0 
    gatsby-remark-autolink-headers: 2.8.0 => 2.8.0 
    gatsby-remark-copy-linked-files: 2.7.0 => 2.7.0 
    gatsby-remark-images: 3.8.1 => 3.8.1 
    gatsby-remark-jargon: 2.10.8-rc.1 => 2.10.8-rc.1 
    gatsby-remark-prismjs: 3.10.0 => 3.10.0 
    gatsby-remark-smartypants: 2.7.0 => 2.7.0 
    gatsby-source-filesystem: 2.8.1 => 2.8.1 
    gatsby-transformer-remark: 2.13.1 => 2.13.1 
    gatsby-transformer-sharp: 2.9.0 => 2.9.0 
  npmGlobalPackages:
    gatsby-cli: 2.16.2
```

**Comment by LekoArts** [comment]
Thank you for opening this!

You should add your styling to `.gatsby-resp-image-wrapper` to add a shadow. Alternatively you can also use the `wrapperStyle` option of the plugin.

An example:

live: https://minimal-blog.lekoarts.de/introduction-to-defence-against-the-dark-arts
code: https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-minimal-blog/src/components/post.tsx#L64

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
