### ISSUE TITLE
How to remove Service Worker created by gatsby-plugin-offline?

### ISSUE THREAD

**Issue by pedromartinez11** [gatsbyjs/gatsby#2880]
I would like to remove the service worker on my site.
I removed gatsby-plugin-offline from my gatsby-config and tried doing this in my index page:
```
console.log('removing service worker')
if (typeof window !== 'undefined') {
  if ('serviceWorker' in window.navigator) {
    window.navigator.serviceWorker.ready.then(registration => {
      registration.unregister();
    });
  }
}
```

But I don't even see `removing service worker` in my console logs. I think it's because the old JS is still being served?

**Comment by KyleAMathews** [comment]
Possibly — try opening the site in an incognito window.

**Comment by KyleAMathews** [comment]
But you'll probably need to keep shipping the SW while also removing it with the above code as SW don't update unless you ship a new one.

Google around for patterns around removing a SW — not an area I'm expert in.

**Comment by ahmedelgabri** [comment]
@pedromartinez11 you found a solution for this? I'm having the same problem

**Comment by pedromartinez11** [comment]
@ahmedelgabri , no, I ended up just re-adding the SW.

**Comment by ahmedelgabri** [comment]
This might work

```js
if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
  window.navigator.serviceWorker.getRegistrations().then(registrations => {
    registrations.forEach(r => r.unregister())
  })
}
```

**Comment by pedromartinez11** [comment]
When I tried something similar, my "new" JS was never delivered to the browser because the SW cached all previous files. So, the new code that removed the SW was never executed.

**Comment by ahmedelgabri** [comment]
Maybe you need to add this code while you still have the plugin so the SW tries to fetch the new changes & then it will be removed.

**Comment by ahmedelgabri** [comment]
@pedromartinez11 I found a way to do this, don't put the script inside your gatsby files, put the script in `static` this way it will not be part of the bundle that Webpack creates & it won't be part of the SW. This way the script will run for sure.

Just put this in your layout or something

```jsx
{/* assuming you have the script directly inside static/ */}
<script src="/script.js" />
```

**Comment by benedfit** [comment]
Check out https://github.com/NekR/self-destroying-sw/tree/master/packages/gatsby-plugin-remove-serviceworker

**Comment by Lidofernandez** [comment]
Hi I've added this plugin to my gatsby project but still I need to reload a couple of time to make sure that the sw is gone: maybe I'm doing something wrong?

```
{
    'gatsby-plugin-catch-links',
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-styled-components',
    'gatsby-plugin-remove-serviceworker',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'img',
        path: 'src/img/',
      },
    },
}
```

**Comment by pungggi** [comment]
@Lidofernandez if i understood it right the plugin helps you naming the service worker you still to add a script to remove it?

**Comment by Lidofernandez** [comment]
Hi @pungggi yeah in order to remove it completely I added the script as well.

**Comment by deadcoder0904** [comment]
Probably a noob mistake but I had a console error `The installing service worker became redundant.` because I was applying `gatsby-plugin-remove-serviceworker` after `gatsby-plugin-offline` like:

```js
[
`gatsby-plugin-manifest`,
`gatsby-plugin-offline`,
`gatsby-plugin-remove-serviceworker`
]
```

So it was installing new Service Worker first with `gatsby-plugin-offline` & then removing it with `gatsby-plugin-remove-serviceworker`. That's why the error.

To remove it just put `gatsby-plugin-remove-serviceworker` first like so:

```js
[
`gatsby-plugin-remove-serviceworker`,
`gatsby-plugin-manifest`,
`gatsby-plugin-offline`
]
```

**Comment by neonguru** [comment]
@deadcoder0904 I tried to put gatsby-plugin-remove-serviceworker before the others and the sw.js file was unchanged after the build. I then put it after the others and sw.js was replaced with the gatsby-plugin-remove-serviceworker's sw.js file as expected.

In the end, I removed the others and left just gatsby-plugin-remove-serviceworker.

The console error confirms the service worker is redundant as desired.

**Comment by nathansebhastian** [comment]
@Lidofernandez hello, May I know where did you put the script file?

**Comment by valayd** [comment]
I tried everything mentioned here but site still loads older version. In Chrome Incognito it works fine. Any workaround available ? As The site is still in development and each time I need to check updates in Incognito mode.

**Comment by davidbailey00** [comment]
To remove the service worker created by `gatsby-plugin-offline`, you should remove this line entirely from your `gatsby-config.js` and replace it with `gatsby-plugin-remove-serviceworker` (after installing this with Yarn/NPM).

When testing your site before deployment, this is unnecessary; you can use the Chrome console to quickly clear the service worker from your site:

![image](https://user-images.githubusercontent.com/4248177/52217831-2e14e100-2891-11e9-8af8-fd92027a4b94.png)

(console -> Application -> Clear storage -> Clear site data)

**Comment by ajayns** [comment]
What if not using Gatsby for my updated site. In that case how do I remove the service worker? @davidbailey00 @NekR

**Comment by tkhquang** [comment]
> What if not using Gatsby for my updated site. In that case how do I remove the service worker? @davidbailey00 @NekR

@ajayns Have you found the solution for this? My app keeps using the old gatsby version instead of my new Vue based version.

**Comment by davidbailey00** [comment]
@ajayns @tkhquang I no longer work at Gatsby but you can take a look at this: https://github.com/NekR/self-destroying-sw (put it in `/sw.js` since that's where Gatsby has its service worker)

**Comment by tkhquang** [comment]
> @ajayns @tkhquang I no longer work at Gatsby but you can take a look at this: https://github.com/NekR/self-destroying-sw (put it in `/sw.js` since that's where Gatsby has its service worker)

Thank you, it seems to work!

**Comment by ajayns** [comment]
Thanks @davidbailey00 that worked. The issue was that the code needs to be in the exact path and filename that Gatsby previously used

**Comment by eleijonmarck** [comment]
@ajayns where would that have been ? 🤔 trying to remove mine from my old site

**Comment by eleijonmarck** [comment]
it worked for me! i put it in `public/sw.js`

**Comment by tslater** [comment]
@ajayns I have the same issue. Any luck toasting it without gatsby?
