### ISSUE TITLE
[docs] many plugin links in doc are broken

### ISSUE THREAD

**Issue by takapiro99** [gatsbyjs/gatsby#28814]
## Summary

In documentation ([gatsbyjs.com/docs](gatsbyjs.com/docs)), a variety of plug-ins have been introduced, but many of the links to them, which like `/packages/gatsby-foo-bar` are broken. Links to  `/plugin/gatsby-foo-bar` works, so should it be fixed?

I searched over the repo and found 311 links starts with `/pakages/gatsby-` and probably (and strangely) all of them are broken as of now.

Example:
  - `gatsby-plugin-typescript` link at [here](https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript#other-resources)

---

Another thing I've found is that request to "gatsbyjs **.org**" redirects to "gatsbyjs **.com**", 
and links like "gatsbyjs.org/**packages**/foo" automaticaly redirects to "gatsbyjs.com/**plugins**/foo."

I don't know the historical background of this site, but if anyone knows, please help.

### Motivation

Broken links should be fixed.

## Steps to resolve this issue

- change all `/packages/***` links to `/plugins/***` (probably)

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.com/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.com/contributing/docs-templates/)
  - [Example of a similar article]()

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by eiselems** [comment]
:D Funny that I encountered it yesterday. Tried to partially fix it and now found your Issue/pull request :)
