### ISSUE TITLE
[gatsby-plugin-mdx]  ERROR #11321 using reserved word in plain text 

### ISSUE THREAD

**Issue by Stvad** [gatsbyjs/gatsby#28815]
## Description

When I have the Markdown formatted just so the build breaks

seems similar to https://github.com/gatsbyjs/gatsby/issues/24923 and https://github.com/gatsbyjs/gatsby/issues/17315

### Steps to reproduce

Try to render the Markdown file which has exactly the following content: (I know this one is weird but a version of it ended up being generated from my source files 😛 )

```
    # ```
    import static
    ```
```

### Expected result

Things are rendered somehow

### Actual result

```
ERROR #11321  PLUGIN

"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:

unknown: Unexpected reserved word 'static' (1:7)

> 1 | import static
    |        ^
  2 | ```
  3 | /Users/sitalov/coding/knowledge/garden/content/garden/hello.mdx: unknown: Unexpected reserved word 'static'
(1:7)

> 1 | import static
    |        ^
  2 | ```
  3 |

  SyntaxError: unknown: Unexpected reserved word 'static' (1:7)
  > 1 | import static
      |        ^
    2 | ```
    3 | /Users/sitalov/coding/knowledge/garden/content/garden/hello.mdx: unknown: Unexpected reserve  d word 'static'
(1:7)
  > 1 | import static
      |        ^
    2 | ```
    3 |

  - error.js:60 Object._raise
    [garden]/[@babel]/parser/src/parser/error.js:60:45

  - error.js:55 Object.raiseWithData
    [garden]/[@babel]/parser/src/parser/error.js:55:17

  - error.js:39 Object.raise
    [garden]/[@babel]/parser/src/parser/error.js:39:17
```

### Interesting variations

```
    # ```
    import magic
    ```
```
also breaks things

```
    # ```import static
    ```
```
does not break things

```
    # ```
        import static
    ```
```
does not break things

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.5.0 - ~/.nvm/versions/node/v15.5.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - ~/.nvm/versions/node/v15.5.0/bin/npm
  Languages:
    Python: 3.8.5 - /Users/sitalov/.pyenv/shims/python
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 84.0
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.21.37 => 2.29.3
  npmGlobalPackages:
    gatsby-cli: 2.16.2
    gatsby-source-roamresearch: 0.4.1
    gatsby: 2.29.3
```

**Comment by 9rstpn** [comment]
It looks like you are using old version of Gatsby and it's dependencies. please try to update the dependencies and check.
Will fix #28815

**Comment by Stvad** [comment]
@9rstpn um, upon seeing discussion in #24923 I double checked that, run npm update/etc. As my environment description says - I use `2.29.3` version of Gatsby, which seems the most recent one available in npm?

**Comment by ascorbic** [comment]
Hi @Stvad 
If the indentation in your example is deliberate, then I can't reproduce this. I pasted [that exact code](https://gist.github.com/ascorbic/8ba6a040e39bcc5659eeffad939f8651) into a file and it works fine. If the indentation _isn't_ meant to be included, then this seems like expected behaviour. The triple-backticks after the `#` does not create a code fence, so the import on the next line should be expected to be treated as code, which is why it fails. Could you upload the actual mdx file as a gist, or confirm the expected behaviour.

Thanks

**Comment by Stvad** [comment]
Space added so Github renders it as code (so original has no spaces). Actual file: https://gist.githubusercontent.com/Stvad/1d9ca7868e627c300d333430f9fa941f/raw/b3a4c63c11c46bc8fff7ee7d3218684fe4d8f476/example_breaking1.mdx  

>The triple-backticks after the # does not create a code fence, so the import on the next line should be expected to be treated as code, which is why it fails. 

I see 😞. Will close this then, though would appreciate any pointers for working around this! (right now I do text replace & inject newline before any ```)

**Comment by ascorbic** [comment]
> right now I do text replace & inject newline before any ```
I think something like that is the only way
