### ISSUE TITLE
Menu didn't highlight when selected in gatsby-plugin-netlify-cms

### ISSUE THREAD

**Issue by tranlehaiquan** [gatsbyjs/gatsby#28839]
## Description

As the title: Menu didn't highlight when selected in gatsby-plugin-netlify-cms (netlify-cms).

### Steps to reproduce

- Enter admin route
- Create new content
- Text something: Eg: "dummy text" and select h1
- The h1 doesn't highlight when it selected

![Screen Shot 2021-01-03 at 14 25 48](https://user-images.githubusercontent.com/17347993/103548977-36d91c00-4ed9-11eb-8768-82f4323e3d0a.png)

![Screen Shot 2021-01-03 at 14 26 15](https://user-images.githubusercontent.com/17347993/103549060-5cfebc00-4ed9-11eb-8e71-b21045e3cf57.png)

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?
The h1 should get css highlight

### Actual result

H1 doesn't highlight

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment]
Thank you for opening this!

Please open an issue at https://github.com/netlify/netlify-cms as this doesn't seem related to the Gatsby plugin.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by tranlehaiquan** [comment]
Dear @LekoArts,
This just only happens when used with `gatsby-plugin-netlify-cms`. When I use netlify-cms with another platform it still okay.
