### ISSUE TITLE
Passing props from layout to page

### ISSUE THREAD

**Issue by sungwoncho** [gatsbyjs/gatsby#2884]
I would like to pass props from layout to pages. But I could not find any documentation. Does Gatsby support this, and if not, would you consider a PR?

I think this is reasonable if a user wants a state to be fetched and shared in all pages (such as `loggedIn`). Wrapping each page with HOC is a solution but we can't use the state in something outside a page but inside the layout (e.g. `<Header>`).

**Comment by pieh** [comment]
Closing issue, it was answered in previous comment.
