### ISSUE TITLE
GraphQLError when filtering for date

### ISSUE THREAD

**Issue by dplate** [gatsbyjs/gatsby#2886]
Hi, 
I just updated from 1.8.11 to 1.9.108, but one of my GraphQL filters fails now:

```
{
  reportJson(date: {eq: "20171101"}) {
    date
  }
}
```

`GraphQLError: Cannot read property 'fromNow' of undefined`

`resolve` is called without a second parameter in:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/run-sift.js#L12

But `resolve` of a date type needs a second parameter:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-type.js#L137

I couldn't find any good workaround for this and I believe it is a bug.

**Comment by benedfit** [comment]
On a related note, this line https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/infer-graphql-type.js#L62, can result in false positives when trying to filter. I had some IDs of objects saved as strings, one of them was identified as a date, and then that broke filtering against that field because the others weren't valid dates

**Comment by simonrepp** [comment]
I've hit this same problem with gatsby `1.9.149`. In my case I have a `year` field containing values like `2012`, `2013`, `2014`, and so on, and on a query like `allDocument(year: {eq:"2012"})` I am getting exactly the same error message as @dplate. I'd second the view that this is clearly a bug in gatsby.

I'll gladly provide a demo project reproducing the issue in a minimal setup, if requested.

**Comment by benedfit** [comment]
The way I got around this was to prefix the values with a string, and then strip that string when I needed to use that field, not ideal, but it works for now

**Comment by simonrepp** [comment]
hey thanks for the hint @benedfit! :beers: I did work around it in a similar fashion already, still this should be adressed at some point, as you say, not ideal, i second that. ;)
