### ISSUE TITLE
Heroku Deployment Problem

### ISSUE THREAD

**Issue by Faizan777** [gatsbyjs/gatsby#28865]
## Summary

The major issue is that when a person wants to deploy the Gatsby application on Heroku. They probably end up getting the error. Application works well in Local Development machine but when it's come to deployment , then have to face certain Issues.
**Adding below buildpack on Heroku , during deployment it throws an error for compatibility. 
heroku buildpacks:add https://github.com/heroku/heroku-buildpack-static.git**

Heroku Deployment Procedure must be updated on documentation.

**Comment by LekoArts** [comment]
Please provide more information as to what is wrong, failing and what needs to be corrected. The current description lacks that information. Thanks!

**Comment by Faizan777** [comment]
![image](https://user-images.githubusercontent.com/39923225/103978483-8f423f00-51a1-11eb-9d72-d1e119bd951e.png)
Above build pack is mentioned by [gatsby documentation](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/deploying-to-heroku/) 
Now when we move to deployment part, then below things happened.
![image](https://user-images.githubusercontent.com/39923225/103978670-f65ff380-51a1-11eb-853b-5b54b2312201.png)

And you know what it's just a simple application , below is the preview of application 
![API Call with Some Styling](https://user-images.githubusercontent.com/39923225/103978708-14c5ef00-51a2-11eb-88ce-b11c89b43343.PNG)

**Comment by ascorbic** [comment]
Hi,
From the error message, this seems to be an issue with heroku-buildpack-static, rather than your site or gatsby. COuld you try opening an issue on that repo. If I'm misunderstanding, please do open a new issue with more explanation.

**Comment by edmorley** [comment]
The reason for this error is that `heroku-buildpack-static` requires that there be a `static.json` in the root of the repo:
> The static.json file is required to use this buildpack. 
(From https://github.com/heroku/heroku-buildpack-static#deploying)

The docs at https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/deploying-to-heroku/ do say to create one:

> Finally, add a static.json file in the root of your project to define the directory where your static assets will be. You can check all the options for this file in the heroku-buildpack-static configuration.

...but I presume not everyone reads to the end of the docs.

**Comment by Faizan777** [comment]
Ok will try above fix.

**Comment by johnpaulmarino** [comment]
I'm also looking for a fix. https://github.com/heroku/heroku-buildpack-static is deprecated.
