### ISSUE TITLE
code blocks not visible on /doc

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#28872]
## Description

Code blocks are missing in docs

### Steps to reproduce

open any page with code blocks:
https://www.gatsbyjs.com/docs/how-to/routing/mdx-plugins/

### Expected result

this code blocks should be visible:
<img width="544" alt="Bildschirmfoto 2021-01-05 um 17 59 12" src="https://user-images.githubusercontent.com/184316/103675094-d05b0900-4f7f-11eb-82a3-3835a8f59a0d.png">

### Actual result

<img width="693" alt="Bildschirmfoto 2021-01-05 um 17 58 55" src="https://user-images.githubusercontent.com/184316/103675121-da7d0780-4f7f-11eb-850d-fc28a6bdcf1b.png">

the code blocks not visible in html, they are missing complete

( source https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/how-to/routing/mdx-plugins.md )

### Environment

https://www.gatsbyjs.com

**Comment by LekoArts** [comment]
Working all fine for me:

![image](https://user-images.githubusercontent.com/16143594/103747814-83207b00-5003-11eb-8398-0a4f82a0fba8.png)

**Comment by muescha** [comment]
🤷‍♂️ now its working again
