### ISSUE TITLE
Gatsby Develop - new Socket.IO CORS breaking change

### ISSUE THREAD

**Issue by zahirally** [gatsbyjs/gatsby#28899]
## Description

GatsbyJS has a dependency on Socket.IO^2.3.  A recent release of Socket.IO (https://github.com/socketio/socket.io/releases/tag/2.4.0) introduced a breaking change that is impacting running GatsbyJS in development mode.   

### Steps to reproduce

Simply install Gatsby from scratch and run `gatsby develop`, browse to http://localhost:8000, then view the browser console log for socket.io errors. 

### Expected result

No socket.io errors in the console.

### Actual result

Socket.io errors in the console.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by KyleAMathews** [comment]
This should be fixed in 2.30.1. Could you try upgrading?
