### ISSUE TITLE
Add AVIF support to gatsby-remark-images

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#28894]
## Description

Sharp (and gatsby-plugin-sharp)) recently got support for a very exciting new image format AVIF which has large size savings over older formats like jpeg and webp.

[We added it to gatsby-plugin-image](https://github.com/gatsbyjs/gatsby/pull/28742) and we should add support for it to gatsby-remark-images.

Perhaps just another option for now `withAvif`. We're still doing benchmarking to see how fast AVIF generation is but potentially we could enable this by default in the future.

**Comment by LekoArts** [comment]
Added in https://github.com/gatsbyjs/gatsby/pull/28927
