### ISSUE TITLE
gatsby-wordpress-experimental runs out of memory when trying to pull in wordpress data, is there any way to limmit what it pulls in?

### ISSUE THREAD

**Issue by meekmachine** [gatsbyjs/gatsby#28902]
I am attempting to use gatsby-wordpress-experimental  connected to a wordpress site with several years content. I was able to get it to work using the older plugins for gatsby and wordpress respectively, but after updating I now see this message:

```
>        This is either your first build or the cache was cleared.
> 	  Please wait while your WordPress data is synced to your Gatsby cache.
> 
> 	  Maybe now's a good time to get up and stretch? :D

```
Then the wordpress endpoint eventually runs out of memory even when I set the timeout and concurrency as suggested:

```
>    ERROR #gatsby-source-wordpress-experimental_111007 

> 
>  gatsby-source-wordpress  Your wordpress server at http://panthernow.com/graphql appears to be overloaded.
> 
> Try reducing the requestConcurrency for content updates or the previewRequestConcurrency for previews:
> 
> {
>   resolve: 'gatsby-source-wordpress-experimental',
>   options: {
>     schema: {
>       requestConcurrency: 5, // currently set to 1
>       previewRequestConcurrency: 2, // currently set to 2
>     }
>   },
> }
> 
> The GATSBY_CONCURRENT_REQUEST environment variable is no longer used to control concurrency.
> If you were previously using that, you'll need to use the settings above instead.

```
Since I am not able to allocate more memory to the Wordpress server, is there any way I could get around this issue either by populating the cache manually or somehow setting the initial cache populating  query to filter date to limit the data so it will not run out of memory?

**Comment by LekoArts** [comment]
Hi!

Please open an issue here: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental

Thanks!
