### ISSUE TITLE
gatsby-source-contentful rate limit preview endpoint

### ISSUE THREAD

**Issue by alana314** [gatsbyjs/gatsby#28901]
## Description

When running gatsby build pointed to contentful preview, we get many (1000+) API errors about rate limits.

### Steps to reproduce
We have a large website. When we run gatsby build we see thousands of these lines:
```
[GraphQL error]: Message: An unexpected error happened on our side., Location: [object Object], Path: preview
[GraphQL error]: Message: An unexpected error happened on our side., Location: [object Object], Path: preview
[GraphQL error]: Message: An unexpected error happened on our side., Location: [object Object], Path: preview
[GraphQL error]: Message: An unexpected error happened on our side., Location: [object Object], Path: preview
[GraphQL error]: Message: An unexpected error happened on our side., Location: [object Object], Path: preview
[GraphQL error]: Message: You have exceeded the rate limit of the Organization this Space belongs to by making too many API requests within a short timespan. Please wait a moment before trying the request again., Location: undefined, Path: undefined
[Network error]: ServerError: Response not successful: Received status code 429
[GraphQL error]: Message: You have exceeded the rate limit of the Organization this Space belongs to by making too many API requests within a short timespan. Please wait a moment before trying the request again., Location: undefined, Path: undefined
[Network error]: ServerError: Response not successful: Received status code 429
[GraphQL error]: Message: You have exceeded the rate limit of the Organization this Space belongs to by making too many API requests within a short timespan. Please wait a moment before trying the request again., Location: undefined, Path: undefined
[Network error]: ServerError: Response not successful: Received status code 429
```

Occasionally, when we run builds pointed at either cdn.contentful.com or preview.contentful.com, we also get this error:

```
success createSchemaCustomization - 0.057s
error [object Object] Cannot read property 'content-length' of undefined
  TypeError: Cannot read property 'content-length' of undefined
  
  - fetch.js:31 responseLogger
    [gatsby-project]/[gatsby-source-contentful]/fetch.js:31:46
  
  - index.es-modules.js:217 
    [gatsby-project]/[contentful]/[contentful-sdk-core]/dist/index.es-modules.js:217:1
  
  - runMicrotasks
  
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
  
  - fetch.js:119 contentfulFetch
    [gatsby-project]/[gatsby-source-contentful]/fetch.js:119:23
  
  - gatsby-node.js:200 Object.exports.sourceNodes
    [gatsby-project]/[gatsby-source-contentful]/gatsby-node.js:200:9
  
  - api-runner-node.js:460 runAPI
    [gatsby-project]/[gatsby]/src/utils/api-runner-node.js:460:16
  
not finished source and transform nodes - 8.287s
not finished Contentful: Fetch data ([project id]) - 8.216s
error Command failed with exit code 1.
```
We believe this is related to hitting the organizational API limit via preview above.

### Expected result
Gatsby should build

### Actual result
Gatsby fails building. Sometimes preview succeeds after 1000s of the 429 errors and sometimes it fails. If we see the content-length error from fetch.js in gatsby-source-contentful it always fails.

### Environment

  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 84.0.1
    Safari: 14.0.2
  npmPackages:
    gatsby-core-utils: ^1.7.0-next.0 => 1.7.0-next.0
    gatsby-plugin-utils: ^0.6.0-next.0 => 0.6.0-next.0
    gatsby-source-filesystem: ^2.8.0-next.0 => 2.8.0-next.0
  npmGlobalPackages:
    gatsby-cli: 2.7.30

**Comment by wardpeet** [comment]
There is not much we can do to fix this from our side, could you contact Contentful support?

Here are some tips to play with that might solve it. (https://gatsbyjs.com/plugins/gatsby-source-contentful/?=content#configuration-options)
* Change pageLimit to a lower value
* assetDownloadWorkers [number][optional] [default: 50]
* Filter your locales by localeFilter

**Comment by jordan314** [comment]
I will reach out to contentful but in my opinion gatsby-source-contentful should limit its retries if contentful sends an X-Contentful-RateLimit-Reset header.
The second "Cannot read property 'content-length' of undefined" actually wasn't our API limit but page size, I logged the response and got "Response size too big. Maximum allowed response size: 7340032B". So thank you for the pageLimit suggestion, 50 worked when 100 didn't. We are still seeing the 429 errors though.

**Comment by axe312ger** [comment]
We are working on resolving these issues. Stay tuned :)

**Comment by petergray-maker** [comment]
> We are working on resolving these issues. Stay tuned :)

Thanks, I got the same issue with 429 errors from contentful, would be great to handle these

**Comment by axe312ger** [comment]
@petergray-maker where do you get them? Latest versions of the plugin should retry 429 when fetching content data from Contentful.

**Comment by petergray-maker** [comment]
Hey @axe312ger 
Thanks for getting back to us.

We get the issue through our github action, we perform a build and checks when we create a PR, it's possible that more then one build process could be running at a single time and increase the likelihood of reaching the contentful rate limit.

The error we get in the github action build process is:

---
  Error:Source GraphQL API: HTTP error 429 Too Many Requests
  
  - fetch.js:11 exports.fetchWrapper
    [client-website]/[gatsby-source-graphql]/fetch.js:11:11
  
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
  
  - dataloader-link.js:101 request
    [client-website]/[gatsby-source-graphql]/batching/dataloader-link.js:101:    20
  
  - dataloader-link.js:25 DataLoader.load [as _batchLoadFn]
    [client-website]/[gatsby-source-graphql]/batching/dataloader-link.js:25:2    0
  

not finished Generating image thumbnails - 1.590s
not finished run page queries - 1.279s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

---
And our yarn.lock file is using:

> gatsby-source-graphql@^2.7.7:
>   version "2.14.0"
>   resolved "https://registry.yarnpkg.com/gatsby-source-graphql/-/gatsby-source-graphql-2.14.0.tgz#9b2217da7c9ccf215f166cca18e304d59ff8de09"
>   integrity sha512-sl23ngwJRbw6ZdFJk9dBF3vONvpfw4DIhp4FZcQ0o8qWsGbkHhBxd9osNIFhIT+SwIDsqzEhsDg+acy31pGKbw==
>   dependencies:
>     "@babel/runtime" "^7.12.5"
>     "@graphql-tools/links" "^7.0.3"
>     "@graphql-tools/utils" "^7.0.2"
>     "@graphql-tools/wrap" "^7.0.1"
>     apollo-link "1.2.14"
>     apollo-link-http "^1.5.17"
>     dataloader "^2.0.0"
>     invariant "^2.2.4"
>     node-fetch "^2.6.1"
>     uuid "3.4.0"

And if it helps the github action environment is:

> Current runner version: '2.277.1'
> Operating System
>   Ubuntu
>   18.04.5
>   LTS
> Virtual Environment
>   Environment: ubuntu-18.04

Many thanks

**Comment by axe312ger** [comment]
Please create a new issue and ask for retry on these errors when using `gatsby-source-graphql`
