### ISSUE TITLE
gatsby-plugin-twitter is not injecting the twitter script (possible conflict with React Context Api? )

### ISSUE THREAD

**Issue by anonimoconiglio** [gatsbyjs/gatsby#28909]
## Description

The plugin `gatsby-plugin-twitter` is not working. There's no twitter `<script>` injected on the `<head>` tag of the html page. 

I'm using it along with `gatsby-remark-embedder` plugin (as suggested on the documentation) but this last plugin work as expected (it normally returns the `<blockquote>` part of the tweet).

Looking at the source code of the plugin-twitter I presume this could be a conflict with my `gatsby-browser.js` code (where I'm [using ThemeProvider from ThemeContext file](https://www.gatsbyjs.com/blog/2019-01-31-using-react-context-api-with-gatsby/)). This is just a intuition, probably not right.

### Steps to reproduce

Content of my `gatsby-config.js` file: 
```js
   ...
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sharp',
    'gatsby-transformer-sharp',
    'gatsby-plugin-twitter',
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 800,
            },
          },
	`gatsby-remark-embedder`	
        ]
      }
    },
   ...
```

Content of my `gatsby-browser.js` file: 

```js
import React from "react"
import { ThemeProvider } from "./src/context/ThemeContext"

// IMPORTING GLOBAL CSS FOR MY CSS GRID
import "./src/utils/global.css"

export const wrapRootElement = ({ element }) => (
	<ThemeProvider>{element}</ThemeProvider>
)
```

### Expected result

According to source code I should see the twitter script with a `window.twttr` prop injected after the loading of the page (at the end of the `<head>` element)

### Actual result

There's no `<script>` injected on the `<head>` tag of the html page. 
And so `window.twttr` returns undefined.

### Environment

```
  System:
    OS: Linux 5.9 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 15.5.1 - /usr/bin/node
    npm: 6.14.10 - /usr/bin/npm
  Languages:
    Python: 3.9.1 - /usr/bin/python
  npmPackages:
    gatsby: ^2.30.1 => 2.30.1 
    gatsby-image: ^2.9.0 => 2.9.0 
    gatsby-plugin-disqus: ^1.2.2 => 1.2.2 
    gatsby-plugin-emotion: ^5.2.0 => 5.2.0 
    gatsby-plugin-feed: ^2.11.0 => 2.11.0 
    gatsby-plugin-google-gtag: ^2.6.0 => 2.6.0 
    gatsby-plugin-layout: ^1.8.0 => 1.8.0 
    gatsby-plugin-manifest: ^2.10.0 => 2.10.0 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-offline: ^3.8.0 => 3.8.0 
    gatsby-plugin-react-helmet: ^3.8.0 => 3.8.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5 
    gatsby-plugin-sharp: ^2.12.0 => 2.12.0 
    gatsby-plugin-sitemap: ^2.10.0 => 2.10.0 
    gatsby-plugin-twitter: ^2.8.0 => 2.8.0 
    gatsby-plugin-typography: ^2.10.0 => 2.10.0 
    gatsby-remark-embedder: ^4.1.0 => 4.1.0 
    gatsby-remark-images: ^3.9.0 => 3.9.0 
    gatsby-remark-responsive-iframe: ^2.9.0 => 2.9.0 
    gatsby-source-filesystem: ^2.9.0 => 2.9.0 
    gatsby-transformer-remark: ^2.14.0 => 2.14.0 
    gatsby-transformer-sharp: ^2.10.0 => 2.10.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.60
```

**Comment by pieh** [comment]
Do you have any tweet embedes on your page?

Just checking https://github.com/gatsbyjs/gatsby/blob/78e5e4762e7a7704bf9d22baa5ef551a5fdd91db/packages/gatsby-plugin-twitter/src/gatsby-browser.js#L30-L35 and https://github.com/gatsbyjs/gatsby/blob/78e5e4762e7a7704bf9d22baa5ef551a5fdd91db/packages/gatsby-plugin-twitter/src/gatsby-browser.js#L38-L40

it only wants to inject twitter runtime if there are any elements that have those "embedClasses"

**Comment by anonimoconiglio** [comment]
> Do you have any tweet embedes on your page?

Yes they have `twitter-tweet` class:

**Comment by joshatoutthink** [comment]
Can you share a repo that demonstrates the problem?  Im having some trouble replicating the issue.
