### ISSUE TITLE
Gatsby build: page refresh disrupts all the layout?

### ISSUE THREAD

**Issue by undavide** [gatsbyjs/gatsby#28919]
## Description

I'm developing a Gatsby website using [Adobe React Spectrum Components](https://react-spectrum.adobe.com/react-spectrum/getting-started.html). I'm already pulling my hair because of some inconsistencies between `develop` vs. `build` rendering, but this one is literally driving me nuts.

The `develop` site is totally fine. In the `build` instead, when I first navigate to a page everything looks more or less fine. If I refresh the page (Cmd+R) the layout goes _nuts_, and when I inspect the code via Chrome DevTools I can see that the divs, classes, styles etc. are in fact quite different, as in the following screenshot.

![image](https://user-images.githubusercontent.com/5939127/103928479-2fee1b80-511c-11eb-90d5-2782238098e3.png)

As a side note, that card is a React component (based on a [Spectrum View](https://react-spectrum.adobe.com/react-spectrum/View.html)), so there's no actual reason why it should not be rendered the same within the page.

### Steps to reproduce

Hard to provide a CodeSandbox, I'm sorry. I've read some past issues, that pointed out to a potentially conflicting `normalize.css` (I've got rid of it, no luck). I understand that I'm providing very little context, but the issue is so striking that might ring a bell to more experienced Gatsby developers.

To be sure, I've run `gatsby clean && gatsby build && gatsby serve -H 0.0.0.0` and checked on a different machine connected to the same LAN. Also the browser doesn't matter.

I could try to reverse-engineer an issue that is apparent as soon as the page displays, but... this isn't fair ;-)

### Expected result

A page refresh shouldn't change the page layout

### Actual result

A page refresh dramatically changes the page code.

### Environment

```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.141
    Safari: 14.0
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1
    gatsby-background-image: ^1.3.1 => 1.3.1
    gatsby-image: ^2.5.0 => 2.5.0
    gatsby-plugin-breakpoints: ^1.3.1 => 1.3.1
    gatsby-plugin-iubenda-cookie-footer: ^1.2.0 => 1.2.0
    gatsby-plugin-manifest: ^2.6.1 => 2.6.1
    gatsby-plugin-offline: ^3.4.0 => 3.4.0
    gatsby-plugin-prettier-eslint: ^1.0.4 => 1.0.4
    gatsby-plugin-react-helmet: ^3.4.0 => 3.4.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.8.0 => 2.8.0
    gatsby-plugin-styled-components: ^3.7.0 => 3.7.0
    gatsby-source-filesystem: ^2.5.0 => 2.5.0
    gatsby-transformer-sharp: ^2.6.0 => 2.6.0
  npmGlobalPackages:
    gatsby-cli: 2.16.2
```

**Comment by undavide** [comment]
Some hours and much reading later, it seems that the problem was a missing Spectrum [`<SSRProvider>`](https://react-spectrum.adobe.com/react-spectrum/ssr.html) component. Wrapping everything with that makes the _hydration_ possible. Not entirely sure why `gatsby develop` doesn't need to be hydrated while `gatsby build` does, but it's already been a long evening.

**Comment by KyleAMathews** [comment]
Sorry for the trouble. This change came a bit too late to help https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/reference/release-notes/v2.30/index.md#server-side-rendering-ssr-in-development

Hydration problems didn't happen in dev in the past as we didn't SSR. Now we do so you'd detect it in dev.
