### ISSUE TITLE
gatsby command not found in user/local/bin after install

### ISSUE THREAD

**Issue by yaronlevi** [gatsbyjs/gatsby#2892]
I've installed gatsby via yarn:
yarn global add gatsby-cli

it went ok without errors, and I can see the "gatsby" and "gatsby-cli" folders in the global folder.
But the "gatsby" command is not available globally.
I looked in **user/local/bin** where my other commands are, and indeed there was no gatsby file there.

I saw that user/local/bin contains aliases. So I tried to create an alias manually for index.js (in gatsby-cli) but it didn't work.

Can you help me understand why the file wasn't created at the first place in user/local/bin or how should I create it manually?

**Comment by markmichon** [comment]
I occasionally run into this with yarn. Give `yarn global remove gatsby-cli` a try, then try installing again with `yarn global add gatsby-cli`. Also upgrade yarn if available.

**Comment by yaronlevi** [comment]
@markmichon thanks I'll try it

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
