### ISSUE TITLE
Add TinaCMS

### ISSUE THREAD

**Issue by SimonKlausLudwig** [gatsbyjs/gatsby#28932]
Tina is a great CMS with Gatsby support. https://tina.io/

Would be worth mention it in the docs ?

**Comment by LekoArts** [comment]
Thanks for the request. To anyone interested, the [doc](https://tina.io/docs/integrations/gatsby/) and [guide](https://tina.io/guides/#gatsby) can be added to this file: https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/how-to/sourcing-data/headless-cms.md

**Comment by Vishal19111999** [comment]
I would like to take this as my first issue
