### ISSUE TITLE
gatsby-plugin-google-analytics sets tracking code in the body

### ISSUE THREAD

**Issue by sungwoncho** [gatsbyjs/gatsby#2894]
The google analytics plugin sets the tracking code in the `<body />` [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-analytics/src/gatsby-ssr.js#L5).

Any reasons for this? I'd like to move it to `<head />` because Google Webmasters tools requires that "tracking code should be in the `<head />` section of your page," when verifying the property.

**Comment by LeKoArts** [comment]
I think you're mixing things up here. Generally speaking you put non-critical code at the end of body to not  prevent the loading of the website. I guess what you mean is the Google Analytics verification itself.
You can put that meta tag in your <head  /> or put a html file at the root of your project (with Gatsby you'd put it in the ``static`` folder.

**Comment by KyleAMathews** [comment]
Yeah — could you screenshot the warning google webmasters is giving? Everything I've ever seen says put the script after body

**Comment by jodyboucher** [comment]
Google's recommendations depend on the analytics script you are using.  They recommended the older synchronous ga.js be placed at the end of BODY. They recommend the newer analytics.js and the even newer gtag.js be placed at the top of HEAD. I don't know that it really makes much difference, but [this is from the the analytics docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/) for the method being used in the plugin.

![google-analytics-docs](https://user-images.githubusercontent.com/11773139/34219458-40ee5578-e57f-11e7-8913-48d76ee3510d.png)

**Comment by crgeary** [comment]
This has recently been raised as an issue within our company too. I found this explanation as to why it's recommended for the `<head>` - https://stackoverflow.com/questions/3173571/should-i-put-the-google-analytics-js-in-the-head-or-at-the-end-of-body

Perhaps the plugin options can allow the developer to choose support for adding it to the `<head>`. If nothing is set, it would fallback to the `<body>` as it does now?

**Comment by KyleAMathews** [comment]
@crgeary yeah this sounds great! Would love a PR adding this.

**Comment by crgeary** [comment]
Sweet.. Just been speaking to @endymion1818 and he wants to take a shot at implementing this :)

**Comment by endymion1818** [comment]
Hah, thanks @crgeary ;-)

Having trouble setting this up, I've got the tooling right (I think!) but can't see the GA tracking code on my local build, either using `gatsby develop` or `npm run develop --NODE_ENV=production`

Chris, if you have any more ideas about this please let me know ...

**Comment by cmwall** [comment]
Even with the merged PR (https://github.com/gatsbyjs/gatsby/pull/3995), the script is still being added to the end of the body for me.

The head component never gets the script. 

```js
{
  resolve: `gatsby-plugin-google-analytics`,
  options: {
    trackingId: "id",
    head: true,
  },
}
```

Any ideas on what I'm doing wrong here?

**Comment by pieh** [comment]
@cmwall can You confirm your `gatsby-plugin-google-analytics` version is at least `1.0.19` ?

**Comment by cmwall** [comment]
That was the problem. Thanks! @pieh
