### ISSUE TITLE
upgrading from gatsby v2.24.64 to v2.24.65 breaks navigation

### ISSUE THREAD

**Issue by barbalex** [gatsbyjs/gatsby#28954]
## Description

I have a navbar with elements like this:
```jsx
<Navbar.Brand onClick={onClickEvents}>Events</Navbar.Brand>
```

with callbacks like this:
```js
const onClickEvents = useCallback(() => {
  // load the data
  store.page.getPage('pages_events')
  // navigate
  navigate('/events')
}, [store.page])
```

navigate is imported from @reach/router:
```js
import { navigate } from '@reach/router'
```

(I can import it from gatsby as well, the same happens)

So when you click one of the menus in the navbar the app navigates.
For a few years now this has worked fine. I haven't touched this part of the code in ages.

But when I update gatsby from version 2.24.64 to any version higher (I have tried about 20 of them because I had first updated to v2.30.1, then worked my way down), the navigation breaks. There is no error in the console but the page shows this in dev:

<img width="867" alt="2021-01-09_23h15_28" src="https://user-images.githubusercontent.com/669783/104109782-8cdf0280-52d1-11eb-8157-b7d537db6097.png">

As is visible in the image, the route navigated to _does_ exist. The error happens even when the following slash is added, for instance: `navigate('/events'/)`. Also: When I reload the page, it is loaded. So this only happens when using `navigate`.

I do not know what happens in production - will not risk trying it out.

I can repeatedly upgrade to 2.24.65 and downgrade back to 2.24.64. The issue always exists in 2.24.65 or higher and not at 2.24.65 (or 2.24.63 which was installed before).

### Steps to reproduce

I have none. Sorry. Can not tell you to clone my app (https://github.com/barbalex/bb2), even though it is open source as it needs a database to run.

### Expected result

The app should know that the page it should navigate to exists and load it.

### Actual result

A page is shown that claims that there is no page at the url.

### Environment

```
$ yarn gatsby info --clipboard
yarn run v1.22.5
$ C:\Users\alexa\bb2\node_modules\.bin\gatsby info --clipboard

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 15.0.1 - ~\AppData\Local\Temp\yarn--1610231484784-0.2362000124454624\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1610231484784-0.2362000124454624\yarn.CMD
    npm: 7.0.3 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.75)
  npmPackages:
    gatsby: 2.24.65 => 2.24.65
    gatsby-plugin-create-client-paths: 2.8.0 => 2.8.0
    gatsby-plugin-eslint: 2.0.8 => 2.0.8
    gatsby-plugin-google-analytics: 2.9.0 => 2.9.0
    gatsby-plugin-manifest: 2.10.0 => 2.10.0
    gatsby-plugin-offline: 3.8.0 => 3.8.0
    gatsby-plugin-react-helmet: 3.8.0 => 3.8.0
    gatsby-plugin-sharp: 2.8.0 => 2.8.0
    gatsby-plugin-sitemap: 2.10.0 => 2.10.0
    gatsby-plugin-styled-components: 3.8.0 => 3.8.0
    gatsby-source-filesystem: 2.9.0 => 2.9.0
    gatsby-transformer-sharp: 2.10.0 => 2.10.0
```

**Comment by KyleAMathews** [comment]
What happens if you import navigation from "gatsby" instead?

**Comment by barbalex** [comment]
The exact same happens. I know because as this code is old I went into the docs and found out that they say to import from gatsby. So I tried.

**Comment by barbalex** [comment]
This commit sounds close to the problem: https://github.com/gatsbyjs/gatsby/commit/18944cec9d87af4744b5583736cc9ed7adf0df0b

**Comment by barbalex** [comment]
Maybe this line is causing this? https://github.com/gatsbyjs/gatsby/commit/18944cec9d87af4744b5583736cc9ed7adf0df0b#diff-e4535fc084e00493cdf64059b0257b3ba2ee3fe54ec9396daf87158b0679905cR205

I am just guessing though, I do not understand the code.

**Comment by barbalex** [comment]
The reason I found this code was comparing the versions: https://github.com/gatsbyjs/gatsby/compare/gatsby@2.24.64...gatsby@2.24.65

**Comment by KyleAMathews** [comment]
Ah you're navigating to /events and the actual page is /events/

I guess we were more forgiving of that before 🤔

**Comment by barbalex** [comment]
I did try changing it to /events/. Did not help either

**Comment by barbalex** [comment]
There are five pages linked in the header. If the site is loaded on one of them, then navigating to it (later) always works. No mather which one. But all the others have the issue

**Comment by KyleAMathews** [comment]
Can you share the site or a reproduction? That'd make it easier to see
what's happening.
--
Kyle Mathews

Blog: *http://bricolage.io <http://bricolage.io>*
Twitter: http://twitter.com/kylemathews

**Comment by barbalex** [comment]
Here are:
- The github project: https://github.com/barbalex/bb2
- The component with the nav-links: https://github.com/barbalex/bb2/blob/master/src/components/Layout/Navbar.js
- The live version of the app: https://mediterranean-migration.com

**Comment by barbalex** [comment]
I tried to build reproductions but ran into problems and gave up. It does not seem to be my great day today 😢 

1. local project (https://github.com/barbalex/bb-bug-repro) does not start due to what seem to be two different issues:
```
$ gatsby develop
success open and validate gatsby-configs - 0.018s

 ERROR #11329

Your plugins must export known APIs from their gatsby-node.js.

See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby node APIs.

- The plugin gatsby-plugin-typescript@2.10.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.

Some of the following may help fix the error(s):

- npm install gatsby@^2.25.0

success load plugins - 0.485s
success onPreInit - 0.017s
success initialize cache - 0.004s
success copy gatsby files - 0.413s
success onPreBootstrap - 0.040s
success createSchemaCustomization - 0.003s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.026s
success building schema - 0.154s
info Total nodes: 18, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.003s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.049s
success update schema - 0.017s
success write out redirect data - 0.003s
success onPostBootstrap - 0.002s
info bootstrap finished - 9.511s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.063s
success write out requires - 0.007s
success run page queries - 0.051s - 6/6 117.93/s
⠀
You can now view bb-bug-repro in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
warn ESLintError:
C:\Users\alexa\bb-bug-repro\src\pages\index.js
  37:11  warning  Visible, non-interactive elements with click handlers must have at least one keyboard listener  jsx-a11y/click-events-have-key-events
  37:11  warning  Static HTML elements with event handlers require a role                                         jsx-a11y/no-static-element-interactions

✖ 2 problems (0 errors, 2 warnings)

success Building development bundle - 8.309s

 ERROR

undefined is not iterable (cannot read property Symbol(Symbol.iterator))



  TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

  - Function.from

  - page-data.ts:128 flush
    [bb-bug-repro]/[gatsby]/src/utils/page-data.ts:128:30

  - webpack-status.ts:16 markWebpackStatusAsDone
    [bb-bug-repro]/[gatsby]/src/utils/webpack-status.ts:16:5

  - start-webpack-server.ts:163
    [bb-bug-repro]/[gatsby]/src/services/start-webpack-server.ts:163:7


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [bb-bug-repro]/[tapable]/lib/Hook.js:154:20

  - Watching.js:98 Watching._done
    [bb-bug-repro]/[webpack]/lib/Watching.js:98:28

  - Watching.js:73
    [bb-bug-repro]/[webpack]/lib/Watching.js:73:19

  - Compiler.js:499 Compiler.emitRecords
    [bb-bug-repro]/[webpack]/lib/Compiler.js:499:39

  - Watching.js:54
    [bb-bug-repro]/[webpack]/lib/Watching.js:54:20

  - Compiler.js:485
    [bb-bug-repro]/[webpack]/lib/Compiler.js:485:14


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [bb-bug-repro]/[tapable]/lib/Hook.js:154:20

  - Compiler.js:482
    [bb-bug-repro]/[webpack]/lib/Compiler.js:482:27

  - async.js:2818
    [bb-bug-repro]/[neo-async]/async.js:2818:7

  - async.js:3522 done
    [bb-bug-repro]/[neo-async]/async.js:3522:9



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

2. codesandbox

This does not seem to run correctly either: https://codesandbox.io/s/loving-panini-yqjwh

**Comment by KyleAMathews** [comment]
Ugh sorry :-(

Can you try upgrading all your plugins and gatsby to the latest versions?

**Comment by barbalex** [comment]
That results in the same issue. As mentioned: I tried about 20 Versions between 2.24.64 and 2.30.1. The error occurs with the change from 2.24.64 to 2.24.65 which is why I thought the issue might be related to this change: https://github.com/gatsbyjs/gatsby/commit/18944cec9d87af4744b5583736cc9ed7adf0df0b#diff-e4535fc084e00493cdf64059b0257b3ba2ee3fe54ec9396daf87158b0679905cR205

Just to be sure I now tried again. Yep, same issue.

**Comment by KyleAMathews** [comment]
I was referring to the typescript plugin error for your reproduction.

**Comment by barbalex** [comment]
I finally got it to run with only minor error messages: https://github.com/barbalex/bb-bug-repro-2
But it fails to reproduce the issue 🙄

**Comment by barbalex** [comment]
The issue remains

**Comment by LekoArts** [comment]
Is it right that a [minimal reproduction][reproduction] doesn't exist though? Without one we can't help much further sadly.

[reproduction]: https://gatsby.dev/reproduction

**Comment by ascorbic** [comment]
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!
