### ISSUE TITLE
[Question: WordPress + ACF/GraphQL] Documentation for querying custom fields

### ISSUE THREAD

**Issue by ryancoughlin** [gatsbyjs/gatsby#2895]
Been working from the Gatsby Wordpress Starter, but I have been unable to successfully query and display custom image fields from ACF.

I found a handful of ACF related issues/questions, but _was unable to find any documentation that points to variables, types, and various queries using ACF and GraphQL._  I'd be happy to open a PR to update the README on the Wordpress starter to help folks in the future. 

Been trying a few things below: 

I have been playing with a handful of variations of this query below. I recently found this issue regarding no `localFile` on ACF (https://github.com/gatsbyjs/gatsby/issues/2492).

I also tried this query type earlier: https://github.com/gatsbyjs/gatsby/blob/master/examples/using-wordpress/src/templates/post.js#L74

```
query homePageQuery {
  allWordpressPost(sort: {fields: [date]}) {
    edges {
      node {
        title
        excerpt
        slug
        acf {
          flies
          location
          hero_image {    
            localFile {
              childImageSharp {
                sizes {
                  base64
                  tracedSVG
                  aspectRatio
                  src
                  srcSet
                  srcWebp
                  srcSetWebp
                  sizes
                  originalImg
                  originalName
                }
              }
            }      
            media_details {
              width
              height
              file
            }
          }
        }
      }
    }
  }
}
```

Thanks in advance.

**Comment by KyleAMathews** [comment]
You probably need to add gatsby-transformer-sharp and gatsby-plugin-sharp.

Transformers extend your schema so e.g. childImageSharp won't exist without the sharp transformer

**Comment by pieh** [comment]
I was planning to prepare PR to update docs on wordpress plugin to add some stuff for image processing but work took all my energy this week

I can outline few things you will need:
- plugins: `gatsby-plugin-sharp` and `gatsby-transformer-sharp`
- acf image fields need to return either image url or image object and not image ID ( return value row https://www.advancedcustomfields.com/wp-content/uploads/2013/02/acf-image-field-edit.jpg ), gallery field should work out of the box (return value is fixed and you can't change that)

does featured image work for you? it should be under `featured_media` field on root level

**Comment by sebastienfi** [comment]
@pieh You can also name your image field `featured_media` and return Object ID.
