### ISSUE TITLE
gatbsy-plugin-manifest - "value" must contain at least one of [icon, icons]

### ISSUE THREAD

**Issue by ndom91** [gatsbyjs/gatsby#28963]
## Description

Issue is based on the 'gatsby-plugin-manifest'. When trying to run a dev server, I receive the error message: 

```
Invalid plugin options for "gatsby-plugin-manifest":

- "value" must contain at least one of [icon, icons]
```

I see there was a similar problem mentioned in issue #28312, however the user just seemed to have his `icon` value commented out - easy fix. 

### Steps to reproduce

So prior to this error appearing, I upgraded my dependencies which included an upgrade of the following:

- gatsby 2.20.10 -> 2.30.1
- gatsby-plugin-manifest 2.2.44 -> 2.10.0

Here is the project's [`package.json`](https://github.com/ndom91/home2020/blob/main/package.json)

And my config looks like so:

<details>
<summary>
<code>gatsby-config.js</code>

</summary>

```js
require('source-map-support').install()
require('ts-node').register({
  compilerOptions: {
    module: 'commonjs',
    target: 'es2017',
  },
})

const config = require('./config/SiteConfig').default
const pathPrefix = config.pathPrefix === '/' ? '' : config.pathPrefix

module.exports = {
  pathPrefix: config.pathPrefix,
  siteMetadata: {
    siteUrl: config.siteUrl + pathPrefix,
    github: config.userGithub,
    twitter: config.userTwitter,
    mail: config.userMail,
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-styled-components',
    'gatsby-plugin-typescript',
    'gatsby-plugin-manifest',
    'gatsby-plugin-catch-links',
    'gatsby-plugin-sitemap',
    'gatsby-plugin-lodash',
    {
      resolve: 'gatsby-plugin-manifest',
      options: {
        name: config.siteTitle,
        short_name: config.siteTitleAlt,
        description: config.siteDescription,
        start_url: config.pathPrefix,
                                lang: 'en_US',
                                icon: 'src/favicon.png',
                                icons: [
                                  {
                                          // src: config.favicon,
                                          src: 'src/favicon.png',
                                                sizes: '128x128',
                                                type: 'image/png',
                                        }
                                ],
        background_color: config.backgroundColor,
        theme_color: config.themeColor,
        display: 'standalone',
      },
    },
    'gatsby-plugin-offline',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'post',
        path: `${__dirname}/blog`,
      },
    },
    'gatsby-transformer-json',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'projects',
        path: `${__dirname}/src/data`,
      },
    },
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          'gatsby-remark-copy-linked-files',
          {
            resolve: `gatsby-remark-images-medium-zoom`, // point!
            options: {
              zIndex: 9999,
              background: 'rgba(0,0,0,0.4)',
              margin: 100,
            },
          },
          {
            resolve: 'gatsby-remark-external-links',
            options: {
              target: '_blank',
              rel: 'nofollow noopener noreferrer',
            },
          },
          {
            resolve: 'gatsby-remark-images',
            options: {
              linkImagesToOriginal: false,
            },
          },
          'gatsby-remark-prismjs',
          'gatsby-remark-autolink-headers',
        ],
      },
    },
    {
      resolve: 'gatsby-plugin-typography',
      options: {
        pathToConfigModule: 'src/utils/typography.ts',
      },
    },
    {
      resolve: 'gatsby-plugin-react-svg',
      options: {
        rule: {
          include: '/static/assets/tech/',
        },
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/images/`,
      },
    },
  ],
}

```
</details>

As you can see, the `gatsby-plugin-manifest` options include `icon` and `icons` key values. I initially just had the `icon` path, but added the `icons` array while troubleshooting this error.

### Expected result

Dev server should start.

### Actual result

`gatsby develop` crashes.

Full `gatsby develop` output:

<details>
<summary>
<code>output</code>
</summary>

```bash
> ndom91-home-2020@1.0.2 dev /opt/ndomino/home2020
> gatsby develop


 ERROR

Unexpected key "componentDataDependencies" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "nodes", "logs",
 "pages", "redirects", "schema", "definitions", "staticQueryComponents", "status", "webpack", "pageData", "themes", "webpackCompilationHash", "config", "lastAction",
"jobsV2", "pageDataStats", "components", "babelrc", "jobs", "nodesByType", "program", "resolvedNodesCache", "nodesTouched", "flattenedPlugins", "pendingPageDataWrites",
"schemaCustomization", "inferenceMetadata", "staticQueriesByTemplate", "queries", "visitedPages". Unexpected keys will be ignored.

success open and validate gatsby-configs - 1.158s

 ERROR #11331  PLUGIN

Invalid plugin options for "gatsby-plugin-manifest":

- "value" must contain at least one of [icon, icons]

not finished load plugins - 0.370s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ndom91-home-2020@1.0.2 dev: `gatsby develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ndom91-home-2020@1.0.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ndo/.npm/_logs/2021-01-10T19_41_13_457Z-debug.log

```
</details>

### Environment

>  System:
>    OS: Linux 5.10 EndeavourOS
>    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
>    Shell: 5.1.4 - /bin/bash
>  Binaries:
>    Node: 15.5.1 - /usr/bin/node
>    npm: 6.14.8 - ~/npm-global/bin/npm
>  Languages:
>    Python: 3.9.1 - /usr/bin/python
>  Browsers:
>    Firefox: 84.0.1
>  npmPackages:
>    gatsby: ^2.30.1 => 2.30.1 
>    gatsby-image: ^2.9.0 => 2.9.0 
>    gatsby-plugin-catch-links: ^2.8.0 => 2.8.0 
>    gatsby-plugin-lodash: ^3.8.0 => 3.8.0 
>    gatsby-plugin-manifest: ^2.10.0 => 2.10.0 
>    gatsby-plugin-offline: ^3.8.0 => 3.8.0 
>    gatsby-plugin-react-helmet: ^3.8.0 => 3.8.0 
>    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
>    gatsby-plugin-sharp: ^2.12.0 => 2.12.0 
>    gatsby-plugin-sitemap: ^2.10.0 => 2.10.0 
>    gatsby-plugin-styled-components: ^3.8.0 => 3.8.0 
>    gatsby-plugin-typescript: ^2.10.0 => 2.10.0 
>    gatsby-plugin-typography: ^2.10.0 => 2.10.0 
>    gatsby-remark-autolink-headers: ^2.9.0 => 2.9.0 
>    gatsby-remark-copy-linked-files: ^2.8.0 => 2.8.0 
>    gatsby-remark-external-links: 0.0.4 => 0.0.4 
>    gatsby-remark-images: ^3.9.0 => 3.9.0 
>    gatsby-remark-images-medium-zoom: ^1.7.0 => 1.7.0 
>    gatsby-remark-images-zoom: ^1.1.0 => 1.1.0 
>    gatsby-remark-prismjs: ^3.11.0 => 3.11.0 
>    gatsby-source-filesystem: ^2.9.0 => 2.9.0 
>    gatsby-transformer-json: ^2.9.0 => 2.9.0 
>    gatsby-transformer-remark: ^2.14.0 => 2.14.0 
>    gatsby-transformer-sharp: ^2.10.0 => 2.10.0

**Comment by LekoArts** [comment]
Thank you for opening this!

You have two duplicate entries of `gatsby-plugin-manifest` in your config:

https://github.com/ndom91/home2020/blob/48811d51b244ac1664a80cd1d7927a649dc49d0d/gatsby-config.js#L24

The plugin validation fails on this entry as the necessary options are missing from this. If you remove that line it'll work.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by ndom91** [comment]
Eieiei can't believe I didnt see that haha. Thanks!
