### ISSUE TITLE
S3 images missing from Styling tutorial

### ISSUE THREAD

**Issue by chonghorizons** [gatsbyjs/gatsby#28974]
#### What problem(s) did you run into that caused you to request additional documentation? What questions do you think we should answer? What, if any, existing documentation relates to this proposal?

In the tutorial on styling (https://www.gatsbyjs.com/docs/tutorial/part-two/), the s3 images don't load anymore.

* https://s3.amazonaws.com/uifaces/faces/twitter/adellecharles/128.jpg
* https://s3.amazonaws.com/uifaces/faces/twitter/vladarbatov/128.jpg

If you open the link, the resource is no longer valid.

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>DB62790FA8EF4F3A</RequestId>
<HostId>7zULMRSfcr4lyAiMHHt/A81FO5JkRDesGOoU0nwFYj3ajArupbMeN6CZ6Y7otDEn6+2u/Nb/ctk=</HostId>
</Error>`

## Steps to resolve this issue

Pick new avatar images OR take the old avatar images and stick it in a new cloud service.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by Vishal19111999** [comment]
I will like to work on this

Can I can use these images @chonghorizons 

https://pbs.twimg.com/profile_images/1108790938640531456/Bl2JvdG__400x400.png
https://pbs.twimg.com/profile_images/1222317768273485824/jTjYAVwU_400x400.jpg

**Comment by meganesu** [comment]
Oh shoot @Vishal19111999 I missed your comment. Sorry about that!! 💜

Feel free to look through our [open issues](https://github.com/gatsbyjs/gatsby/issues) for another thing to work on!
