### ISSUE TITLE
return 404 instead of 200 for 404.html page 

### ISSUE THREAD

**Issue by ahmadkhalaf1** [gatsbyjs/gatsby#28977]
Hello , 
i am hosting Gatsby with cloudfront and s3 bucket , and my custom 404 page is returning 200 Ok when i hit the url 
mysite.de/404.html like this , i noticed its the same thing with Gatsby site 
https://www.gatsbyjs.com/404.html

is it possible to return 404 instead of 200 ?

thanks

**Comment by Vishal19111999** [comment]
I would like to take up this bug as a beginner!

**Comment by mattsbanner** [comment]
Also experiencing this, I agree that a 404 should be returned. Whilst it is true that the 'not found' page has been found, it's not a valid page that would be included in sitemaps or ever shown to user purposely and so it seems strange to return a successful response on it.

**Comment by aryanwebmob** [comment]
I am having the same issues as well ... if in my site i go to https://mysite.com/random_shit, gatsby return a 200 code on that document fetch and show a 404 page content ... why is it giving back a 200 code on a 404 page

**Comment by Kofeinich** [comment]
So, may be anyone can to do with this something?

**Comment by alexhollenbeck** [comment]
Also experiencing this issue - would love if there was support for the 404 page itself returning a 404 instead of 200, as this is flagged by Google Search Console and hurts SEO.

**Comment by ahmadkhalaf1** [comment]
so the only way i could do to prevent seo issues with a help of a seo guy , i set the 404.html to no index inside header via metadata, i hope this could be a help for you guys .

<meta property="robots" content="noindex" data-react-helmet="true" />

**Comment by lopandpe** [comment]
This is not closed, is it?

It would be ideal to have a way to force the statusCode of the 404 page to not be 200, as it is a problem for SEO.
