### ISSUE TITLE
Update GitHub Pages Hosting Documentation

### ISSUE THREAD

**Issue by actuallyatiger** [gatsbyjs/gatsby#28989]
## Summary

What problem(s) did you run into that caused you to request additional documentation? What questions do you think we should answer? What, if any, existing documentation relates to this proposal?

Some recommended topics to cover:

- List the topics you think should be here.
- This list does not need to be exhaustive!

GitHub Pages now allows you to choose any branch as your deployment branch.

Gatsby documentation page for [GitHub Pages](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages/#deploying-to-a-github-pages-subdomain-at-githubio)

GitHub Pages documentation showing the feature [here](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source)

### Motivation

Why should we document this and who will benefit from it?

Makes setting up a deployment easier because you do not have to rename branches and change the repository default.

### Draft the doc

- [x] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.com/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.com/contributing/docs-templates/)
  - [Example of a similar article]()

### Open a pull request

- [x] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by LekoArts** [comment]
Thanks for the issue! Do you want to open that PR for the commit that you created? :)

**Comment by actuallyatiger** [comment]
Waiting for the pull request to be approved
