### ISSUE TITLE
Integrating template languages (handlebars, liquid, etc)

### ISSUE THREAD

**Issue by talbet** [gatsbyjs/gatsby#290]
Gatsby has been a great tool to work with, and I am really enjoying what is possible. I was wondering if its possible to create static pages using template languages such as handlebars.

So far I have
- merged webpack config using `gatsby-node.js` to add support for '.hbs' templates.
- setup webpack loaders to handle the templates
- created a `hbs.js` wrapper to add transforms to the template

However, I can't find a way to get gatsby to recogize the .hbs files as a static route. Is there a way to merge new configuration into `create-routes.js` and `gatsby-helpers.js`?

Amazing work on gatsby.

**Comment by KyleAMathews** [comment]
So... unfortunately the list of file extensions that can become pages is hard coded atm https://github.com/gatsbyjs/gatsby/blob/cb9d686a5f27ee165607b96dcf0886d1d3a635fa/lib/utils/glob-pages.js#L8-L20 and https://github.com/gatsbyjs/gatsby/blob/43c26d22976aabed5c583ee40e8e89fc4cc3bf94/lib/isomorphic/create-routes.js#L84

So right now the easiest thing to do (unfortunately) is to fork Gatsby and add `hbs` to those two places.

There's plans afoot to add a plugin system which will move all configuration for "page types" into plugins so you'd install `gatsby-plugin-json` for json pages or `gatsby-plugin-handlebars` for handlebars and things would just work.

I am curious though, what's the advantage to creating pages with handlebars? How would you get data into the handlebar templates? Or what would the data source be?

**Comment by talbet** [comment]
No worries, that's what I thought.

I'm currently working on a doc site for an existing project that uses handlebars. The idea was that we could implement handlebar templates so that it would be easy to use existing snippets. Then we can prototype new ideas in gatsby and export changes back out with minimum translation between template languages.

The data would be be a static .json file that is full of sample data from the project. It's a bit of an edge case, and html is still going to work for us. Gatsby is so versatile in so many respects, thanks for the hard work on it.

**Comment by KyleAMathews** [comment]
It really wouldn't be too bad to maintain a temp fork adding support for handlebar pages. You'd just need to make the two changes above, run `npm run build`, remove `dist` from `.gitignore`, `git add dist/` and commit and push to your repo, then `npm install` straight from your fork instead of npm.

Gatsby will hopefully have native support for new content types in the next month or so.

**Comment by talbet** [comment]
What I've ended up doing is adding a 'language' attribute to the front matter. Then I can process the markup as 'handlebars' in the html wrapper based on what the language is set too. It means that the compilation is in react, rather than webpack, which has advantages and disadvantages. It is a testament to Gatsby (and React) that it is flexible enough to do this. This seems to be working for us, at least until, more options open up.

Closing this for now, as we've solved our way around the issue.

**Comment by JamesJosephFinn** [comment]
@KyleAMathews Gatsby is clearly an amazing project (the [features page](https://www.gatsbyjs.org/features/) says it all!), but I'm not willing / able (at this stage) to take on the cognitive overhead of learning React. However, I am very comfortable using something like Nunjucks. Are there any plans to make Gatsby usable by someone like me, or should I just be content to use the preexisting (albeit not as awesome) alternatives? Thanks!

**Comment by KyleAMathews** [comment]
I have no plans to support nunjucks. Some one could probably build a plugin for it however.
