### ISSUE TITLE
TypeError only in production build with runtime-loaded @google/model-viewer

### ISSUE THREAD

**Issue by MichaelBelousov** [gatsbyjs/gatsby#29005]
## Description

When building a production build on my personal website, I get a type error that `undefined` has no property `prototype` in the runtime code of the @google/model-viewer library.
See [this informative commit](https://github.com/MichaelBelousov/MichaelBelousov.github.io/commit/6f705d48a63c3eb0cf33e24d4218fac719468bfb) which works around the issue.
I thought Gatsby was an appropriate place to put the issue since it looks like whatever minification or uglification occurred (the source maps point to `model-viewer.min.js` but I build with --no-uglify) is responsible for shadowing an existing name `n` in the outer closure. It's also very possible a dependency of Gatsby is responsible.

### Steps to reproduce

1. clone my personal website `git clone https://github.com/MichaelBelousov.github.io`. I might remove the reference in the future but I'm ok with sharing an already obviously publicly stored website.
2. run the `./clean.sh` script to remove the current production build content
3. run `cd src && ./publish.sh` to regenerate the production build with gatsby. `publish.sh` takes extra arguments for `gatsby build` so you can run `./publish.sh --no-uglify`.
4. voila, you should now be able to `grep -B2 -A2 'var n = this\[bp\]\.model' '*.js'` and see a reference to `n.prototype` before `var n`. The commit referenced in the description is a simple workaround by manually renaming `n`.
5. To see the TypeError in the console, serve the website (`npx serve -l 8000` or `python -m simpleHTTPServer` or `python3 -m http.server` and navigate to https://localhost:8000/SentinelBeam 

### Expected result

No type error is thrown when the affected page is opened in a browser. You can run `npx serve -l 8000` in the current state of my repository to see what *should* happen because the workaround works around it (lol).

### Actual result

A type error is thrown. If you ran the reproduction steps you should see this. You can also see it by just serving the base directory of the reproduction repo.

### Environment

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.18.1 - ~/.nvm/versions/node/v10.18.1/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v10.18.1/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v10.18.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: beta
    Firefox: 84.0.2
  npmGlobalPackages:
    gatsby: 2.21.13
```

**Comment by ascorbic** [comment]
Hi,
It seems this is a known issue with model-viewer and SSR. See [this issue](https://github.com/google/model-viewer/issues/690) for workarounds. I got it to work by changing the import like this:

```jsx
await import('@google/model-viewer/dist/model-viewer-legacy')
```

...which gives me this:

![image](https://user-images.githubusercontent.com/213306/104576956-d2dcf300-5650-11eb-8ca3-8cb91cc615f4.png)

I'm going to close this, but feel free to reply or open a new issue if this doesn't work for you.

**Comment by MichaelBelousov** [comment]
Thank you for figuring that out, sorry that I missed that detail while using model-viewer, I thought I was avoiding SSR with the runtime import anyhow but that was an incorrect assumption.
