### ISSUE TITLE
gatsby build error : WebpackError: ReferenceError: fetch

### ISSUE THREAD

**Issue by ininahazwe** [gatsbyjs/gatsby#29012]
I'm trying to deploy my application, without success. I get this error message : " WebpackError: ReferenceError: fetch is not defined" whereas in dev mode, everything works. The application is linked to firebase. 

here is the full status after build attempt :

success open and validate gatsby-configs - 0.079s
success load plugins - 1.028s
success onPreInit - 0.064s
success delete html and css files from previous builds - 0.007s
info We've detected that the Gatsby cache is incomplete (the .cache directory exists
but the public directory does not). As a precaution, we're deleting your site's
cache to ensure there's no stale data.
success initialize cache - 0.148s
success copy gatsby files - 0.137s
success onPreBootstrap - 0.032s
success createSchemaCustomization - 0.113s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.279s
success building schema - 0.417s
info Total nodes: 127, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.008s
success Checking for changed pages - 0.000s
success createPagesStatefully - 0.134s
success update schema - 0.032s
success onPreExtractQueries - 0.000s
success extract queries from components - 0.539s
success write out redirect data - 0.001s
warning The icon(src/images/logo.png) you provided to 'gatsby-plugin-manifest' is not square.
The icons we generate will be square and for the best results we recommend you provide a square icon.

success Build manifest and related icons - 0.171s
success onPostBootstrap - 0.176s
info bootstrap finished - 9.174s
success run static queries - 1.406s - 7/7 4.98/s
success run page queries - 0.012s - 3/3 252.67/s
success write out requires - 0.006s
success Building production JavaScript and CSS bundles - 90.757s
success Rewriting compilation hashes - 0.010s
success Building HTML renderer - 7.966s
failed Building static HTML for pages - 0.607s
error Building static HTML failed

  662 |  * limitations under the License.
  663 |  */
> 664 | registerFunctions(firebase, fetch.bind(self));
      |                           ^
  665 | firebase.registerVersion(name, version);
  666 | //# sourceMappingURL=index.esm.js.map
  667 | 

  WebpackError: ReferenceError: fetch is not defined
  
  - index.esm.js:664 
    node_modules/@firebase/functions/dist/index.esm.js:664:27
  
  - index.esm.js:1 
    node_modules/firebase/dist/index.esm.js:1:1
  
  - config.js:1 
    src/firebase/config.js:1:1
  
  - useFirestore.js:1 
    src/hooks/useFirestore.js:1:1
  
  - imageGrid.js:1 
    src/components/imageGrid.js:1:1
  
  - accueil.js:1 
    src/components/accueil.js:1:1
  
  - about.js:1 
    src/pages/about.js:1:1

An idea of what to do?

**Comment by LekoArts** [comment]
Thank you for opening this!

`fetch` is not available in Node.js (which is the environment that `gatsby build` runs in). It's the same error as undefined `window` for example. You'll need to check for existence of the fetch/window object before calling your firebase functions: https://www.gatsbyjs.com/docs/debugging-html-builds/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by MadsMadsDk** [comment]
I'm somehow also experiencing this in the new version of Gatsby (not sure that's related, though), but I'm pretty sure I'm doing a window is defined check. I'll see if I can reproduce, but it's also related to firebase.

**Comment by mkimbo** [comment]
> I'm somehow also experiencing this in the new version of Gatsby (not sure that's related, though), but I'm pretty sure I'm doing a window is defined check. I'll see if I can reproduce, but it's also related to firebase.
Hello did you manage to solve the issue..Im also getting the same error despite checking for the window object

**Comment by Archdoog** [comment]
Started having the issue again even though I'm checking for window as well. 

Ended up trying this with my module name: https://www.gatsbyjs.com/docs/debugging-html-builds/#fixing-third-party-modules and it worked great.

Example: 

```
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html" || stage === "develop-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /firebase/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
}
```

**Comment by thecodingwizard** [comment]
Dynamically importing Firebase no longer works with the Firebase v9 SDK. However, Archdoog's fix above works great :)
