### ISSUE TITLE
[gatsby-plugin-layout]: Page refresh undesired behavior

### ISSUE THREAD

**Issue by fcisio** [gatsbyjs/gatsby#29024]
## Description

I'm having issues figuring out a weird behavior from gatsby-plugin-layout.
Without the plugin, on page refresh the page doesn't change much, that's good.
With the plugin, the pages component seems to be fully re-rendered (which can be expected I guess). My issue comes when I serve the site.

**On hard reload:** ✅  Same behavior as without the plugin (not much change)
**On normal reload:** 🚫  Rendering issue

### Steps to reproduce

1. Clone a Gatsby starter
2. Install "gatsby-plugin-layout"
3. Build & Serve
4. Refresh the page normally and observe
5. Hard refresh the page normally and observe

### Expected result

The page should not flicker and only the images should rerender

### Actual result

The page component fully rerenders

Here's a short video to showcase this. Look for the copyright line that flashes at the top.

4 first reload === hard reload
4 last reload === normal reload

https://user-images.githubusercontent.com/46095852/104535921-0c781480-55e5-11eb-9971-698dd697e1c4.mov

### Environment

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.22.15 => 2.23.3 
    gatsby-image: ^2.4.5 => 2.4.7 
    gatsby-plugin-emotion: ^4.3.4 => 4.3.4 
    gatsby-plugin-layout: ^1.3.4 => 1.3.4 
    gatsby-plugin-manifest: ^2.4.9 => 2.4.11 
    gatsby-plugin-offline: ^3.2.9 => 3.2.9 
    gatsby-plugin-preact: ^4.0.3 => 4.0.3 
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.4 
    gatsby-plugin-sharp: ^2.6.9 => 2.6.11 
    gatsby-plugin-styled-components: ^3.3.4 => 3.3.4 
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2 
    gatsby-source-filesystem: ^2.3.8 => 2.3.11 
    gatsby-transformer-sharp: ^2.5.3 => 2.5.5

**Comment by ascorbic** [comment]
Hi,
Could you confirm that this still happens when you're upgraded gatsby and all the plugins? You're using some very old versions. Thanks.

**Comment by fcisio** [comment]
Hi @ascorbic 
I worked on a repro for this and I was able to identify `gatsby-plugin-offline` as the source of the issue.
> Also tested with `gatsby-plugin-offline@3.9.0-next.1`, but the problem persists

upgrade-dependencies: The issue persists when all dependencies are up to date
[See repro](https://github.com/fcisio/repro-gatsby-layout/tree/upgrade-dependencies)

---
I have tried to upgrade the dependencies, but it seems to break the `HMR` (see #27609)
For me, `Gatbsy@2.24.0`, is the last HMR stable version

**Comment by crock** [comment]
@fcisio To be honest, try just throwing this in your `gatsby-browser.js`. It's basically what `gatsby-plugin-layout` does, so there's no need for another plugin dependency.

```js
import { Layout}  from './src/layouts/' // change the import statement to reflect where your layout component is obviously

export const wrapPageElement = ({element}) => <Layout>{element}</Layout>
```

Then you can remove the Layout from each of your standard page components as it's wrapped in gatsby-browser instead.
