### ISSUE TITLE
Responsive Images (remote)

### ISSUE THREAD

**Issue by kildareflare** [gatsbyjs/gatsby#2902]
Hi, first up great work. I've just completed my first site using Gatsby and it's awesome!
My first time using React and GraphQL and I've enjoyed it (normally use Angular1/Angular2).

My site is backed by the prismic headless CMS and uses this [source plugin](https://github.com/angeloashmore/gatsby-source-prismic) to get the data.

I'd now like to make the images responsive.

I'm aware that Gatsby has a responsive image plugin but it appears to work only with local images and mine are hosted remotely in the prismic CMS. In theory it would be possible to add multiple images in prismic and infer what to display where based on the data returned. But I'd rather this was all handled automagically and only one image needed to be added to prismic.

**Question.** Is there a way to handle remote images with the existing plugin - have I missed something?

I'm assuming not, in which case would the best thing be to:

* extend the plugin with a new option, that when set, fetches remote images, saves them locally and then processed them as normal?
* create a new plugin to do this?

**Comment by garnerp** [comment]
I don't know much about the Prismic plugin, but take a look at the Contentful one.  I believe that it uses Gatsby's responsive image solution to generate the srcset, but the resulting URLs are served from Contentful's image delivery using its image manipulation query string parameters.

https://using-contentful.netlify.com/

**Comment by KyleAMathews** [comment]
Contentful is a bit unique in that they have an Image API. So what the gatsby-source-contentful plugin does is create a GraphQL type for images with the same API as gatsby-transformer-sharp so you can write queries the same way but not have to do the image processing locally like with sharp.

Assuming Prismic doesn't have an image API like contentful, you'll want to do your first option, add a PR to gatsby-source-prismic to download images locally.

This is pretty easy to do — gatsby-source-filesystem exposes a helper function which does all the hard work. See for example how gatsby-source-wordpress does things https://github.com/gatsbyjs/gatsby/blob/4969db87cbbad7c66f714fd62b593f5f815399de/packages/gatsby-source-wordpress/src/normalize.js#L349

**Comment by KyleAMathews** [comment]
Yup! You can use the same createRemoteFileNode function in gatsby-node.js and onCreateNode to download URLs and create links to them with createNodeField.

This is pretty easy to debug with console.log/breakpoints in your API implementations.

**Comment by elliotschultz** [comment]
This is great! I didn't realise there was already support for pulling remote images in `gatsby-source-wordpress`.

I've just tried @KyleAMathews suggestion above (with `gatsby-source-contentful` instead of Prismic) and I'm getting close but would really appreciate some pointers.

This is my `gatsby-node.js` file:

```es6
const { createRemoteFileNode } = require(`gatsby-source-filesystem`)

exports.onCreateNode = ({ node, boundActionCreators, store, cache }) => {
  const { createNodeField, createNode } = boundActionCreators

  if (node.internal.type === `ContentfulAsset`) {
    createRemoteFileNode({
      url: 'http:' + node.file.url,
      store,
      cache,
      createNode
    }).then((result) => {
      console.log(result)
    })

  }
}
```

This is working as I can see the newly generated File nodes in GraphQL and the remote images are being pulled down to my machine, but I'm not quite understanding how to "create links to them with createNodeField". How do I make these File nodes as a subset of the `ContentfulAsset`nodes?

**Comment by KyleAMathews** [comment]
You'll want to add a link to the new file node using [`createNodeField`](https://www.gatsbyjs.org/docs/bound-action-creators/#createNodeField) e.g.

```js
createNodeField({
  node,
  name: `linkToFile___NODE`,
  value: remoteFile.id,
})

// The field value is now accessible at node.fields.happiness
```

The important part is the name of the new field has the `___NODE` at the end which is how you programmatically create links between nodes.

**Comment by elliotschultz** [comment]
Thanks for the quick reply

This is my `gatsby-node.js` now:

```es6
exports.onCreateNode = ({ node, boundActionCreators, store, cache }) => {
  const { createNodeField, createNode } = boundActionCreators

  if (node.internal.type === `ContentfulAsset`) {
    return new Promise((resolve, reject) => {
      createRemoteFileNode({
        url: 'http:' + node.file.url,
        store,
        cache,
        createNode
      }).then(result => {

        console.log(result.id)

        createNodeField({
          node,
          name: `linkToFile___NODE`,
          value: result.id
        })
        resolve()
      }).catch(reject)
    })
  }
}
```

but am getting this error:

```
Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: "internal.fieldOwners.linkToFile___NODE". There is no corresponding node with the id field matching: "default-site-plugin"
```

The `console.log(result.id)` returns:
```
/[MY DIRECTORY]/gatsby-contentful/.cache/gatsby-source-filesystem/a2c788e43a91530c5a610bb3072eb449.jpg absPath of file
```
which appears to be right.

Am I using `createNodeField` appropriately?

**Comment by KyleAMathews** [comment]
Check what the value of node is when you create the node field.

**Comment by elliotschultz** [comment]
Running `console.log(node)` right before `createNodeField` in the code above spits out:

```graphql
{ id: 'c3yW5oX7VLWOQw0kUoeawKY',
  parent: null,
  children: [],
  file: 
   { url: '//images.contentful.com/hmylqvbzvbxb/3yW5oX7VLWOQw0kUoeawKY/e722bd7caeb2ced91760497f9ee08466/20170715-DSCF2224-Edit-cropped.jpg',
     details: { size: 1944471, image: [Object] },
     fileName: '20170715-DSCF2224-Edit-cropped.jpg',
     contentType: 'image/jpeg' },
  title: 'Portrait',
  description: '',
  node_locale: 'en-AU',
  internal: 
   { type: 'ContentfulAsset',
     contentDigest: '007eea3e43ba39629d71d11f0379548d',
     owner: 'gatsby-source-contentful' }
}
```

**Comment by KyleAMathews** [comment]
The error suggests you're somehow adding the field to a random other node.

**Comment by kildareflare** [comment]
This where I've got to, but I'm stuggling a bit now.
This solution is hacked together from the links above and the source from remark-images.
https://gist.github.com/kildareflare/3b1371c6f68066310fc68dece2409a71

What I have attempted to do:
1) look out for prismic data that contains images (they are always in a field called slideshow and only on certain node types)
2) download all images to local file system using the remote url
3) link them (don't really understand this)
4) use the code from remark-images to create raw srcset html
5) add this to the original prismic node
6) I will then use this to create appropriate html in my app.

There is likely quite a few things wrong with the current code, but I am working through it bit by bit.
What I am seeing right now though...
I have two pages which are created from data (graphsql results)
Without my image code in place, each page gets created.
But with the code in place, sometimes each page gets created multiple times...

e.g. in this scenario, 3 times.
```
create page for flat-top-hill-walks
create page for bendigo-goldfields
start sizes View from property
create page for flat-top-hill-walks
create page for bendigo-goldfields
start sizes Among The Rocks
start sizes Views Towards Alexandra
start sizes View from property
start sizes Wild Thyme
start sizes 1860s Miners Hut
start sizes Gold Mining Relic
start sizes Butchers Reservoir
create page for flat-top-hill-walks
create page for bendigo-goldfields
start sizes Some of our flock
create page for flat-top-hill-walks
create page for bendigo-goldfields
```

**Comment by toxsick** [comment]
@elliotschultz did you fix this one? I'm also getting

```
Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: "internal.fieldOwners.<fieldname>___NODE". There is no corresponding node with the id field matching: "default-site-plugin"
```

when trying to create a link between nodes.

**Comment by moltar** [comment]
Also getting the same error:

> Invariant Violation: Encountered an error trying to infer a GraphQL type for: "internal.fieldOwners.linkToFile___NODE". The  re is no corresponding node with the id field matching: "default-site-plugin"

**Comment by MarcCoet** [comment]
Did someone succeeded implementing `createRemoteFileNode` with `createNodeField`??
If someone is interested I managed to get around it by creating a node like transformer plugins do. I used [this example](https://github.com/gatsbyjs/gatsby/blob/a5c08719ebe1a3004ac8f97b888a73a65fa4fa32/packages/gatsby-transformer-screenshot/src/gatsby-node.js#L75) to help me think about it the right way.
```js
const crypto = require('crypto')
const { createRemoteFileNode } = require(`gatsby-source-filesystem`)

const createContentDigest = obj =>
  crypto
    .createHash(`md5`)
    .update(JSON.stringify(obj))
    .digest(`hex`)

exports.onCreateNode = async ({ node, boundActionCreators, store, cache }) => {
  const {
    createNode,
    createNodeField,
    createParentChildLink,
  } = boundActionCreators

  if (node.internal.type !== `Asset`) {
    return
  }

  const localImageNode = await createLocalImageNode({
    url: 'https://static.pexels.com/photos/248797/pexels-photo-248797.jpeg',
    parent: node.id,
    store,
    cache,
    createNode,
  })
  createParentChildLink({
    parent: node,
    child: localImageNode,
  })
}

const createLocalImageNode = async ({
  url,
  parent,
  store,
  cache,
  createNode,
}) => {

  const fileNode = await createRemoteFileNode({
    url,
    store,
    cache,
    createNode,
  })

  const localImageNode = {
    id: `${parent} >>> LocalImage`,
    url,
    // expires: screenshotResponse.data.expires,
    parent,
    children: [],
    internal: {
      type: `LocalImage`,
    },
    localImageFile___NODE: fileNode.id,
  }

  localImageNode.internal.contentDigest = createContentDigest(localImageNode)
  
  createNode(localImageNode)
  
  return localImageNode
}
```

The pain is it make kilometric queries
```js
query{
  asset {
    childLocalImage {
      localImageFile {
        childImageSharp {
          sizes {
            src
          }
        }
      }
    }
  }
}
```

**Comment by graysonhicks** [comment]
@MarcCoet Awesome, worked for me.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
