### ISSUE TITLE
Manifest.json syntax error with AWS Amplify

### ISSUE THREAD

**Issue by krichey15** [gatsbyjs/gatsby#29025]
## Description

When I run my site from localhost there is not manifest.json syntax error. But when I deploy the site using AWS Amplify there is. I assume this is because AWS Amplify is not building the site properly.

### Steps to reproduce

I mean really the only steps I can think of are
1. Clone some gatsby starter code
2. Deploy site using AWS Amplify

Feel free to view the source code of my site and you will see the console error I am getting. 
www.kyle-richey.com

**Comment by LekoArts** [comment]
Thank you for opening this!

This doesn't seem to be a bug with Gatsby but related to your deployment with Amplify. Please see our documentation on this: https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/deploying-to-aws-amplify/

You can use our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
