### ISSUE TITLE
gatsby-plugin-sass sassOptions docs is incorrect

### ISSUE THREAD

**Issue by joebobmiles** [gatsbyjs/gatsby#29045]
## Summary

In [the official docs for `gatsby-plugin-sass`](https://www.gatsbyjs.com/plugins/gatsby-plugin-sass/?=sass#other-options), the following configuration is listed for providing the `includePaths` parameter to the Sass compiler:

```js
plugins: [
  {
    resolve: `gatsby-plugin-sass`,
    options: {
      sassOptions: {
        includePaths: ["absolute/path/a", "absolute/path/b"],
        ...
      }
    },
  },
]
```

Per this code snippet, I added the following to my `gatsby-config.js`:

```js
plugins: [
  {
    resolve: `gatsby-plugin-sass`,
    options: {
      sassOptions: {
        includePaths: [ './src/styles' ],
        ...
      }
    },
  },
]
```

However, using this configuration, the Sass compiler reports it cannot locate the modules. I've struggled for a while now trying to understand why. I finally reviewed the `gatsby-node.js` provided by `gatsby-plugin-sass` and found this:

```js
exports.onCreateWebpackConfig = ({
  actions,
  stage,
  rules,
  plugins,
  loaders
}, {
  cssLoaderOptions = {},
  postCssPlugins,
  useResolveUrlLoader,
  sassRuleTest,
  sassRuleModulesTest,
  ...sassOptions
}) => {
  ...
});
```

The last parameter, `sassOptions`, ***is a rest argument, not a configuration object.*** Therefore, the correct usage is:

```js
plugins: [
  {
    resolve: `gatsby-plugin-sass`,
    options: {
       includePaths: [ './src/styles' ],
       ...
    },
  },
]
```

### Motivation

The documentation of this plugin should be accurate to the code. Correcting this bit of documentation will avoid unnecessary confusion about the usage of the plugin, and prevent users from erroneously reporting bugs due to inaccurate documentation. (I almost reported this as a but before I went to the code to verify that it was, in fact, a bug.)

## Steps to resolve this issue

I suggest updating the snippet under ["Other Options" in `gatsby-plugin-sass`'s documentation](https://www.gatsbyjs.com/plugins/gatsby-plugin-sass/?=sass#other-options) to read:

```js
plugins: [
  {
    resolve: `gatsby-plugin-sass`,
    options: {
       includePaths: ["absolute/path/a", "absolute/path/b"],
       ...
    },
  },
]
```

At the moment, I am pressed for time, and will be unable to author a draft and open a PR until Saturday (1/15/2021).

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.com/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.com/contributing/docs-templates/)
  - [Example of a similar article]()

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by joebobmiles** [comment]
So I figured I'd edit my issue to provide a GitHub link to the `gatsby-node.js` in `gatsby-plugin-sass`, but see some completely different code:

```js
exports.onCreateWebpackConfig = (
  { actions, stage, rules, plugins, loaders },
  {
    cssLoaderOptions = {},
    postCssPlugins,
    useResolveUrlLoader,
    sassRuleTest,
    sassRuleModulesTest,
    sassOptions = {},
    ...sassLoaderOptions
  }
) => {
 ...
});
```

A little investigation reveals that this code is from `gatsby-plugin-sass@v3.1.0-next.1`, but my local version is `gatsby-plugin-sass@v2.3.3`. Tried to upgrade to the latest stable version on NPM (`gatsby-plugin-sass@v3.0.0`), but node-sass build failed. I'll be working to figure that out instead.

**Comment by LekoArts** [comment]
Hi Joseph!

With v3 one of the breaking changes was to move the options into a `sassOptions` object: https://www.gatsbyjs.com/plugins/gatsby-plugin-sass/?=sass#v300

The documentation is referencing the latest version thus you'll see errors with a v2 version.

**Comment by joebobmiles** [comment]
Thank you for the response. I'll work on upgrading to v3 then.
