### ISSUE TITLE
8 high severity vulnerabilities found

### ISSUE THREAD

**Issue by jordan-miguel** [gatsbyjs/gatsby#29042]
**Description**

**NPM install found 5 high severity vulnerabilities**

**Steps to reproduce**
cd into my-blog-starter
npm install gatsby-source-contentful

**npm audit security report**
See screenshot
<img width="545" alt="Screenshot 2021-01-15 at 12 14 12" src="https://user-images.githubusercontent.com/14114089/104726257-3b989e00-572b-11eb-84ea-439b65328b4a.png">

**Environment**
New prokect (for testing purposes)

**Additional Notes:**
I'm assuming this is a low priority bug based on comments in [this](https://github.com/gatsbyjs/gatsby/issues/24679) report. If so please feel free to close the issue.

**Comment by ascorbic** [comment]
This is fixed in #29034
