### ISSUE TITLE
react-query doesn't work

### ISSUE THREAD

**Issue by notaduck** [gatsbyjs/gatsby#29054]
## Description

I am trying to implement the [react-query v3](https://github.com/tannerlinsley/react-query) package into a gatsbyjs project, however I get the following error: `Error: No QueryClient set, use QueryClientProvider to set one` even though I have wrapped everything with the `QueryClientProvicer` and given it a `client` in `gatsby-browser.js`

```js
import { QueryClient, QueryClientProvider } from 'react-query'
import React from 'react'

export const wrapPageElement = ({ element, props }) => {

    const queryClient = new QueryClient();

    return (
        <QueryClientProvider clien={queryClient}>
            {element}
        </QueryClientProvider>
    )
}
```

### Steps to reproduce

https://codesandbox.io/s/7uh7q

### Expected result

react-query should fetch the data from the star wars api.

### Actual result

The `QueryClientProvicer` doesn't get the `client`.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by probablyup** [comment]
@notaduck there's a typo in your code example. `clien` vs `client`

**Comment by LekoArts** [comment]
Hi!

Your reproduction on codesandbox doesn't work for me, it always fails to start. As probablyup also said you've got a typo in there. Lastly, I'd recommend sharing the code between gatsby-browser.js and gatsby-ssr.js so that you don't create the client twice and do not repeat code as well.

**Comment by notaduck** [comment]
> @notaduck there's a typo in your code example. `clien` vs `client`

And thatvisbwy it is better to go to sleep instead of opening a issue...... Sry! It is working now

**Comment by LekoArts** [comment]
@notaduck Why did you reopen?

**Comment by notaduck** [comment]
That was a mistake, sry!

**Comment by notaduck** [comment]
I just tried to implement it again.... However it still looks like there is problems. It works just fine in `development` but as soon as I `build` the project will it fail:
```
failed Building static HTML for pages - 0.144s

 ERROR #95313

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  23 |
  24 |   if (!queryClient) {
> 25 |     throw new Error('No QueryClient set, use QueryClientProvider to set one');
     | ^
  26 |   }
  27 |
  28 |   return queryClient;


  WebpackError: No QueryClient set, use QueryClientProvider to set one

  - QueryClientProvider.js:25
    node_modules/react-query/es/react/QueryClientProvider.js:25:1

  - useBaseQuery.js:6
    node_modules/react-query/es/react/useBaseQuery.js:6:35

  - useQuery.js:7
    node_modules/react-query/es/react/useQuery.js:7:22

  - index.js:11
    src/pages/index.js:11:38
```

Prove -> https://github.com/notaduck/use-react-gatsby-demo
