### ISSUE TITLE
gatsby-plugin-mdx, custom plugin access to properties like `timeToRead`, `tableOfContents`

### ISSUE THREAD

**Issue by alexanderwe** [gatsbyjs/gatsby#29058]
## Description

I am currently in the process of integrating a custom local Gatsby plugin into my personal site. The purpose of the plugin is to create social card images on the fly. The overall setup of my site is done with yarn workspaces. The site imports a custom Gatsby theme. The theme then imports the custom plugin for the social cards. All blog posts are written in `.mdx` and therefore I am using the `gatsby-plugin-mdx`. 

Now I want that my custom plugin is run when the `gatsby-plugin-mdx` is creating the pages.  The plugin needs access to some of the properties that are added by the `gatsby-plugin-mdx` during build, like `timeToRead`. What I see is that when the `index.js` of my custom plugin is run, these properties are not available. 

I added my plugin inside the `gatsbyRemarkPlugins` option of the `gatsby-plugin-mdx` plugin.

```javascript
{
resolve: `gatsby-plugin-mdx`,
options: {
  extensions: [`.mdx`, `.md`],
  defaultLayouts: {
    posts: `${__dirname}/src/templates/blog-post.js`,
    default: `${__dirname}/src/templates/page.js`,
  },
  gatsbyRemarkPlugins: [
    {
      resolve: `gatsby-remark-images`,
      options: {
        maxWidth: 800,
        linkImagesToOriginal: false,
      },
    },
    {
      resolve: `gatsby-remark-prismjs`,
      options: {
        classPrefix: `language-`,
        inlineCodeMarker: null,
        showLineNumbers: false,
      },
    },
    {
      resolve: `gatsby-remark-slug`,
      options: {},
    },
    {
      resolve: `gatsby-remark-social-cards-teabyte`, // <-- this is the custom plugin
      options: {},
    },
  ],
},
```

==== Custom Plugin ====

```json
{
    "name": "gatsby-remark-social-cards-teabyte",
    "version": "1.0.0",
    "description": "Custom plugin for teaybte blog to generate social cards",
    "main": "index.js",
    "license": "MIT",
    "dependencies": {
        "jimp": "0.16.1"
    }
}
```

```javascript
//index.js
module.exports = ({ markdownNode }, options) => {
  console.log(`${markdownNode.timeToRead}` //undefined
  console.log(`${markdownNode.excerpt}` //undefined
...
};
```

```javascript
//gatsby-node of the custom plugin

exports.onPreInit = () => {
  console.log(
    "logging to the console from a plugin in another project with require.resolve"
  );
};
```

Here is an example GraphQL query where I access the `timeToRead` property. I would have thought that this property must be part of  the `markdownNode` my plugin has access to. 

```
query blogListQuery($skip: Int!, $limit: Int!) {
    allMdx(
      sort: { fields: [frontmatter___date], order: DESC }
      filter: { frontmatter: { published: { eq: true } } }
      limit: $limit
      skip: $skip
    ) {
      edges {
        node {
          id
          excerpt(pruneLength: 250)
          timeToRead
          frontmatter {
            type
            title
            slug
            date
          }
          slug
        }
      }
    }
  }
```

### Steps to reproduce

---- 

### Expected result

Properties like `timeToRead` or `excerpt` are available when running the plugin. 

### Actual result

Properties like `timeToRead` or `excerpt` are not available when running the plugin. 

### Environment

```
  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 12.20.1 - /var/folders/gf/y7blnj6j32d6pjftwj6xqptw0000gp/T/yarn--1610900258329-0.18529287546618867/node
    Yarn: 1.22.10 - /var/folders/gf/y7blnj6j32d6pjftwj6xqptw0000gp/T/yarn--1610900258329-0.18529287546618867/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 84.0.2
    Safari: 14.0.2
```

**Comment by LekoArts** [comment]
Thank you for opening this!

That you can't access both properties on the markdownNode is expected as they are only added in the GraphQL schema phase: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/gatsby/source-nodes.js

So they are not created while the markdownNode is created but attached on top of it.

If you want to access those fields and also add additional fields to the `Mdx` node you'll need to use the `createResolvers` API:
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#extending-third-party-types

Here are two examples for this:
https://spectrum.chat/gatsby-js/general/rendering-content-to-page-with-frontmatter-data~4bda35b1-c923-4e96-ad89-5eb8bdd8dfec
https://github.com/gatsbyjs/gatsby/issues/26301#issuecomment-698457377

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by alexanderwe** [comment]
Thanks a lot for the clarification. This makes sense. I was not aware of that, so I am sorry for creating noise in the issues here. 

I will change my plugin code according to your suggestions. Thanks !
