### ISSUE TITLE
gatsby-link determine when loading is complete

### ISSUE THREAD

**Issue by baseten** [gatsbyjs/gatsby#2906]
Does `gatsby-link` provide any sort of event or callback that I can use to determine when the load for the code chunks for the incoming page has completed? Gatsby seems to use a global `___loader` instance to manage this, but this doesn't seem to have any documentation. Can I use `onPostLoadPageResources` somehow?

**Comment by KyleAMathews** [comment]
Not right now.

What is your use case for wanting to know when loading is complete?

**Comment by baseten** [comment]
I've updated to the latest gatsby-link version where data is preloaded if the link is in the viewport so this is less of an issue now. Before after clicking a link there was a significant wait before displaying the page and I wanted to show a loader. This would still be a useful thing to do and I have implemented at the moment as follows in my `onInitialClientRender` in `gatsby-browser`:
```
window.___emitter.on( 'onPostLoadPageResources', e => {
    // dispatch redux action with e.page
} );
```

**Comment by KyleAMathews** [comment]
Ah interesting — yeah exposing the emitter could be interesting too at some point.

I like to be cautious though about making APIs public as they're fairly set in stone at that point.

You might want to look at the source of https://www.gatsbyjs.org/packages/gatsby-plugin-nprogress/ as well.

Good to hear that avoiding preloading links if not in the viewport made a noticeable improvement!

**Comment by baseten** [comment]
Ah, good to know I was on the right track! I'll use the `onDelayedLoadPageResources` event too.

Makes sense regarding exposing APIs as well.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
