### ISSUE TITLE
Build / Develop cli logs are not visible if one the new fast_dev flags are set.

### ISSUE THREAD

**Issue by jonnyeom** [gatsbyjs/gatsby#29070]
## Description

When one of the new dev flags are set,
During Gatsby develop / build, the console output is hidden / not shown.
![image](https://user-images.githubusercontent.com/19575068/104930281-f1a1f900-5972-11eb-8e65-2917c29d1a44.png)

### Steps to reproduce

On the latest cli code, in `gatsby-config.js`, set one of the new fast_dev flags.
```
  flags: { PRESERVE_WEBPACK_CACHE: true },
  plugins: [
    {...
```

### Expected result

Notice about flags are shown,
An then regular build logs are displayed.

### Actual result
Notice about flags are shown,
Regular build logs are displayed but the text is empty / not visible.

What happened.

### Environment

  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.4.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.9 - /usr/bin/npm
  Languages:
    Python: 3.9.1 - /usr/bin/python
  Browsers:
    Firefox: 84.0.2
  npmPackages:
    gatsby: ^2.26.1 => 2.30.3 
    gatsby-background-image: ^1.2.0 => 1.4.0 
    gatsby-image: ^2.5.0 => 2.9.0 
    gatsby-link: ^2.5.0 => 2.9.0 
    gatsby-plugin-catch-links: ^2.4.0 => 2.8.0 
    gatsby-plugin-feed: ^2.7.0 => 2.11.0 
    gatsby-plugin-google-analytics: ^2.5.0 => 2.9.0 
    gatsby-plugin-manifest: ^2.6.1 => 2.10.0 
    gatsby-plugin-nprogress: ^2.4.0 => 2.8.0 
    gatsby-plugin-offline: ^3.4.0 => 3.8.0 
    gatsby-plugin-preact: ^3.3.2 => 3.3.2 
    gatsby-plugin-react-helmet: ^3.4.0 => 3.8.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sass: ^2.5.1 => 2.8.0 
    gatsby-plugin-sharp: ^2.8.0 => 2.12.2 
    gatsby-plugin-sitemap: ^2.6.0 => 2.10.0 
    gatsby-plugin-twitter: ^2.4.0 => 2.8.0 
    gatsby-source-drupal: ^3.7.0 => 3.11.1 
    gatsby-source-filesystem: ^2.5.0 => 2.9.1 
    gatsby-transformer-sharp: ^2.6.0 => 2.10.1 
  npmGlobalPackages:
    gatsby-cli: 2.17.1

**Comment by LekoArts** [comment]
Hi! Please report this in the umbrella issue: https://github.com/gatsbyjs/gatsby/discussions/28331
Thanks!
