### ISSUE TITLE
[gatsby-source-contentful] tracedSVG error on windows

### ISSUE THREAD

**Issue by ariadne-github** [gatsbyjs/gatsby#29071]
## Description

Running gatsby build, and using an image from Contentful (by **gatsby-source-contentful**), requesting **tracedSVG** results in:

```
There was an error in your graphql query:
... AppData\Local\Temp/2021-01-04T08:30:47.877Z-news-default-small.jpg-98303ac8334d2e4086aa2c59c013fde8..jpg : unable to open file for write 
windows error
```

### Steps to reproduce

Just request the tracedSVG field on a contentful image and run gatsby build.

### Expected result

The build should complete without errors.

### Actual result

The build breaks with this errors:

```
There was an error in your graphql query:
... AppData\Local\Temp/2021-01-04T08:30:47.877Z-news-default-small.jpg-98303ac8334d2e4086aa2c59c013fde8..jpg : unable to open file for write 
windows error
```

### Environment

System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.8
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.29.3 => 2.29.3
    gatsby-image: ^2.8.0 => 2.8.0
    gatsby-plugin-google-tagmanager: ^2.8.0 => 2.8.0
    gatsby-plugin-gtag: ^1.0.13 => 1.0.13
    gatsby-plugin-image: ^0.4.1 => 0.4.1
    gatsby-plugin-manifest: ^2.9.1 => 2.9.1
    gatsby-plugin-postcss: ^2.3.13 => 2.3.13
    gatsby-plugin-preact: ^4.4.0 => 4.4.0
    gatsby-plugin-react-helmet: ^3.7.0 => 3.7.0
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sass: ^2.8.0 => 2.8.0
    gatsby-plugin-schema-snapshot: ^1.4.0 => 1.4.0
    gatsby-plugin-sharp: ^2.11.2 => 2.11.2
    gatsby-plugin-sitemap: ^2.9.0 => 2.9.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.18 => 1.1.18
    gatsby-source-contentful: ^4.5.0-next.1 => 4.5.0-next.1
    gatsby-source-filesystem: ^2.8.1 => 2.8.1
    gatsby-transformer-json: ^2.8.0 => 2.8.0
    gatsby-transformer-remark: ^2.13.1 => 2.13.1
    gatsby-transformer-sharp: ^2.9.0 => 2.9.0
    gatsby-transformer-yaml: ^2.8.0 => 2.8.0
  npmGlobalPackages:
    gatsby-cli: 2.12.115

### Notes on troubleshooting

I've investigated the source of the error, and I'm pretty sure I've found it.
This line creates an invalid path on Windows:

https://github.com/gatsbyjs/gatsby/blob/3163ca67d44b79c727dd3e331fb56b21707877a5/packages/gatsby-plugin-sharp/src/trace-svg.js#L112

Because of #28609.
The contentDigest is an ISO timestamp, which contains colon characters that are invalid for paths on Windows.

I don't want to mess with the optimization of the digest (in gatsby-source-contentful), so I think the bug could simply be solved in gatsby-plugion-sharp, by cleaning the generated path or the digest from invalid characters, but I'm not sure what's the best way to do it, to avoid the same error next time someone throws something else in the digest.

Maybe something like (also adding path.join to fix the separator):
```
const cleanDigest = slugify(file.internal.contentDigest, { remove: /[<>:"\/\\\|\?\*]/g });
const tmpFilePath = path.join(tmpDir, `${cleanDigest}-${file.name}-${optionsHash}.${file.extension}`);
```

What do you think? I'm willing to open a pull request if necessary.
This fixes the bug on my machine.

**Comment by LekoArts** [comment]
Can you give us a reproduction on this or go into your `node_modules`, change the path to leave out the `contentDigest` and see if it works?

**Comment by ariadne-github** [comment]
A reproduction is a little complicated, and I think it's not needed, since the error is evident. I've already tried to correct the path inside the node_modules, and it works. I've also tried to leave it out as you suggested, and it works.
