### ISSUE TITLE
Results of useStaticQuery are Undefined with `gatsby build`

### ISSUE THREAD

**Issue by codingwithchris** [gatsbyjs/gatsby#29080]
## Description
I'm using Gatsby in a monorepo with Sanity:
https://github.com/the-nerve/nerve.web/tree/feature/migrate-to-monorepo-and-sanity-cms/packages/web

When working in development mode with `gatsby start`, everything builds as expected, the site works with no errors whatsoever, and all contexts reliant on static queries are fully populated with data. All static queries are run and yield the expected data results.

However, when attempting to deploy the site to Netlify OR building locally with `gatsby build`, the process fails at the `Building static HTML for page` step.

The errors all revolve around my context components; Specifically, the ones that contain a `useStaticQuery` call.

Before we get to the steps to reproduce, here's a full implementation of such a component that is causing issues:

**EnvironmentContext.tsx**
```
export const EnvironmentContext = createContext({} as Environment);

export const EnvironmentProvider: React.FC = ({ children }) => {
    const data = useStaticQuery(graphql`
        query EnvironmentConfigQuery {
            site {
                siteMetadata {
                    appVersion
                    prodURL
                    deployURL
                    environment
                    deployContext
                    deployID
                    commitRef
                    prevCommitRef
                    isDev
                    isProd
                }
            }
        }
    `);

    const queryData = data?.site?.siteMetadata;

    const config = {
        app: {
            version: queryData.appVersion,
            deployURL: queryData.deployURL,
            prodURL: queryData.prodURL,
        },
        environment: {
            context: queryData.environment,
            isDev: queryData.isDev,
            isProd: queryData.isProd,
        },
        release: {
            id: queryData.commitRef,
            prevID: queryData.prevCommitRef,
        },
        deploy: {
            context: queryData.deployContext,
            id: queryData.deployID,
        },
    };

    return (
        <EnvironmentContext.Provider value={config}>
            {children}
        </EnvironmentContext.Provider>
    );
};

export const useEnvironmentContext = (): Environment =>
    useContext(EnvironmentContext);
```

**gatsby-browser** (other contexts removed for simplicity in this example)
```
export const wrapRootElement: GatsbyBrowser['wrapRootElement'] = ({
    element,
}) => (
    <EnvironmentProvider>
          {element} 
    </EnvironmentProvider>
);
```

### Steps to reproduce
1. Clone [the repository](https://github.com/the-nerve/nerve.web/tree/feature/migrate-to-monorepo-and-sanity-cms/packages/web) or inspect it manually. The most up-to-date code is on this feature branch currently.
2. `npm install`
3. Unfortunately you need private npm tokens for environment variables to run the setup :/
4. `npm run start` works without a hitch
5. `npm run build` 👎 

### Expected result

What should happen?

The build should complete as expected, and as it does in the development environment.

### Actual result
`npm run build` fails with:

```
failed Building static HTML for pages - 0.247s
ERROR #95313 
Building static HTML failed for path "/s/2016-2017"

> 22 |     const liveURL = app.prodURL ?? company.website;
     |                         ^
  23 | 
  24 |     const currentURL =
  25 |         liveURL && path ? `${liveURL}${path}` : getCurrentRootURL();

WebpackError: TypeError: Cannot read property 'prodURL' of undefined
```
(I should note here that I've tested other routes, not just the one listed above and had the same result)

This failure above is the result of an undefined `useStaticQuery` call in the `useCurrentURL` component:

```
export const useCurrentURL = (path?: string): string => {
    const { company } = useConfigContext();
    const { app } = useEnvironmentContext(); // should use the result of the query defined in the previous section.

    const liveURL = app.prodURL ?? company.website;

    const currentURL =
        liveURL && path ? `${liveURL}${path}` : getCurrentRootURL();

    return currentURL;
};
```

**Notes**
1. Trying to debug the issue myself, I tried to remove completely `app.ProdURL` and use `company.website` as the value instead, and got a similar failure with `company` being undefined (which also uses a static query to populate data).
2. In an effort to make sure the issue wasn't with `gatsby-source-sanity` somehow, I removed all other contexts/static queries except for my `EnvironmentContext` (showed in a previous section). That component queries `siteMetadata` from `gatsby-config` and has no external dependency. The result was similar. The data is undefined with `gatsby build` but exists as expected with `gatsby develop`.
3. I obviously tired deleting `.cache` and `public` + rerunning etc.

Is anyone else experiencing or have you experienced anything similar?

### Environment
Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.141
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.30.3 => 2.30.3 
    gatsby-background-image: ^1.4.0 => 1.4.0 
    gatsby-image: ^2.9.0 => 2.9.0 
    gatsby-plugin-gtag: ^1.0.13 => 1.0.13 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-manifest: ^2.10.0 => 2.10.0 
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3 
    gatsby-plugin-netlify: ^2.9.0 => 2.9.0 
    gatsby-plugin-react-helmet: ^3.8.0 => 3.8.0 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5 
    gatsby-plugin-sharp: ^2.12.2 => 2.12.2 
    gatsby-plugin-sitemap: ^2.10.0 => 2.10.0 
    gatsby-plugin-styled-components: ^3.8.0 => 3.8.0 
    gatsby-plugin-typescript: ^2.10.0 => 2.10.0 
    gatsby-source-filesystem: ^2.9.1 => 2.9.1 
    gatsby-source-sanity: ^6.0.5 => 6.0.5 
    gatsby-transformer-sharp: ^2.10.1 => 2.10.1 
```

**A little bit more about my setup:**
I'm using Typescript everywhere, including the gatsby-* files. You can see how I am accomplishing this by [taking a look at `gatsby-*.js`](https://github.com/the-nerve/nerve.web/blob/feature/migrate-to-monorepo-and-sanity-cms/packages/web/gatsby-config.js) files [as well as `@gatsby/api/*.ts` files](https://github.com/the-nerve/nerve.web/tree/feature/migrate-to-monorepo-and-sanity-cms/packages/web/%40gatsby/api).

I'm not sure if that is having an impact on anything.

**Comment by codingwithchris** [comment]
Expanding upon the above: after some thought, it seems like the issue doesn't have to do with `useStaticQuery`, but with context itself somehow.

If context was working, `app` would be defined in the above example because it was manually defined with:
```
 const config = {
        app: {
```

The issue is that `app` is undefined which makes me think that somehow context isn't working as it should. If context were working properly, but not `useStaticQuery` then `app.prodURL` would resolve as `undefined` instead of throwing an error about app being undefined.

**Comment by codingwithchris** [comment]
I finally had some time to dig into this today. Ultimately I moved my gatsby-* out of typescript files and back to vanilla js files. This fixed the problem. So it seems that compiling with Typescript works fine in development mode, but breaks when trying to build HTML on the server.

**Comment by ascorbic** [comment]
Hi. Glad you've found a fix for this. You're correct that we don't currently support using TypeScript for gatsby-* files, though the handling should clealry be more consistent between develop and build. I'm going to close this now, but will note that we should align the behaviour.
