### ISSUE TITLE
Hash URLs scroll to the wrong position on first load with a fixed header

### ISSUE THREAD

**Issue by alowdon** [gatsbyjs/gatsby#29084]
## Description

If a website has a fixed header, when a URL with a hash is first loaded, the page is scrolled to the wrong location; so that the target element is hidden underneath the header. However clicking other hash links within the now-loaded page will scroll the content to the correct location as expected.

### Steps to reproduce

I did spend some time trying to produce a minimal reproduction to isolate which plugin/configuration might be causing this, but unfortunately wasn't able to, but this problem can be seen on the Gatsby documentation website so the team should have a scenario they can use, e.g.:

- Open https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#replaceHydrateFunction in a fresh tab/window
- You can also refresh the page once loaded to see this effect

### Expected result

The header for replaceHydrateFunction should be the first item visible underneath the header.

### Actual result

The header for replaceHydrateFunction appears behind the header (as it appears the element is actually aligned to the top of the window, rather than the top of the visible area).

Clicking on items in the right-hand menu will scroll the page as expected, showing the headings underneath the header correctly, but then refreshing the page again will show the same problem.

### Environment

Tested on Chrome 87.0.4280.141

In case it's useful, in Safari 14.0.2 (16610.3.7.1.9), all headings are shown in the wrong location when items in the right-hand menu are clicked (i.e. the heading is always hidden by the header).

For reference, here is the environment I am running for our site which has the same issue:

  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.141
    Edge: 87.0.664.75
    Firefox: 84.0.2
    Safari: 14.0.2

And with the following package versions:

    "gatsby": "2.30.2",
    "gatsby-plugin-algolia": "0.16.2",
    "gatsby-plugin-catch-links": "2.8.0",
    "gatsby-plugin-compile-es6-packages": "2.1.0",
    "gatsby-plugin-google-tagmanager": "2.9.0",
    "gatsby-plugin-layout": "1.8.0",
    "gatsby-plugin-minify-classnames": "0.2.0",
    "gatsby-plugin-react-helmet": "3.8.0",
    "gatsby-plugin-sass": "3.0.0",
    "gatsby-plugin-sharp": "2.12.1",
    "gatsby-plugin-sitemap": "2.10.0",
    "gatsby-plugin-use-query-params": "1.0.1",
    "gatsby-remark-attr": "0.1.0",
    "gatsby-remark-autolink-headers": "2.9.0",
    "gatsby-remark-component-parent2div": "1.2.3",
    "gatsby-remark-copy-linked-files": "2.8.0",
    "gatsby-remark-custom-blocks": "2.8.0",
    "gatsby-remark-embed-snippet": "4.8.0",
    "gatsby-remark-images": "3.9.0",
    "gatsby-remark-prismjs": "3.11.0",
    "gatsby-source-filesystem": "2.9.0",
    "gatsby-transformer-rehype": "1.9.8",
    "gatsby-transformer-remark": "2.14.0",
    "gatsby-transformer-sharp": "2.10.1",

**Comment by ascorbic** [comment]
Hi. Have you tried setting the `scroll-margin-top`? https://twitter.com/joshwcomeau/status/1332015868725891076

**Comment by devdomsos** [comment]
Can confirm the same behaviour on AnchorLink component.

**Comment by alowdon** [comment]
@ascorbic We did try setting `scroll-margin-top` but that did not fix the issue.

After some more digging I believe this is related to the gatsby-remark-autolink-headers plugin. This inserts a script into the page via [gatsby-ssr.js](https://github.com/gatsbyjs/gatsby/blob/55a8b695118691380fa508e323143b0471443974/packages/gatsby-remark-autolink-headers/src/gatsby-ssr.js#L56) and also adds a hook in `onInitialClientRender` in [gatsby-browser.js], both of which look to change the scroll position for hash URLs. After removing both these bits of code, our site works as expected. Maybe there is a reason that they exist, but it seems like a lot of things are competing to set the scroll position.

**Comment by alowdon** [comment]
Can confirm that this is still an issue e.g. on the Gatsby documentation website.

**Comment by cayeborreo** [comment]
Can confirm this behavior across our Gatsby projects as well, and even in gatsbyjs.org - e.g. [gatsbyjs.com/docs/conceptual/building-with-components/#why-react-components](https://www.gatsbyjs.com/docs/conceptual/building-with-components/#why-react-components)

**Comment by Szulerinio** [comment]
this is still an issue

**Comment by MuhammadHaseeb12** [comment]
For React and Next js you can use very light package called [reach-hash-control](https://github.com/haseeb5555/react-hash-control) related to the url hash to read url hash params and to scroll between hashes with in the page and more check out https://github.com/haseeb5555/react-hash-control (give star if you find helpfull)
