### ISSUE TITLE
[gatsby-plugin-image] responsive images not working

### ISSUE THREAD

**Issue by Grsmto** [gatsbyjs/gatsby#29093]
## Description

When using the new `gatsby-plugin-image`, the highest source image is always chosen by the browser, no matter what viewport you're in. Responsive is not respected. This is because the `sizes` prop is not passed down to the `<source>` element.

Bug fix in #29092.

### Steps to reproduce
1. Set viewport size to mobile size
2. Inspect any image
3. Notice `sizes` is missing from `<source>`
4. Check "Network" tab and notice what version of the image is loaded

(tried to create a reproduction example but seems like Codesandbox is buggy atm [https://codesandbox.io/s/interesting-gould-xnv6b](https://codesandbox.io/s/interesting-gould-xnv6b))

### Expected result

Browser should download the right image based on viewport width/DPR.

### Actual result

Browser downloads biggest image.

### Environment

"gatsby": "2.31.0",
"gatsby-image": "2.11.0-next.0",
"gatsby-plugin-image": "0.7.0-next.0",

**Comment by LekoArts** [comment]
Hi! Please use the Discussion to report bugs: https://github.com/gatsbyjs/gatsby/discussions/27950

Thanks!
