### ISSUE TITLE
After refresh query string either dissapears or shows up after '/'

### ISSUE THREAD

**Issue by PetrShchukin** [gatsbyjs/gatsby#29115]
## Description

After navigation to another page using `navigate(`/search?q=${searchQuery}`);` everything works. The url is "***/search?q=123" once I refresh the page it becomes "search/?q=123". You can test it even using this link  https://www.gatsbyjs.com/docs?=123

P.S.
after deploying on SURGE, after refreshing query string disappears completely

### Steps to reproduce
paste this link into browser https://www.gatsbyjs.com/docs?=123

### Expected result

The url should be"https://www.gatsbyjs.com/docs?=123"

### Actual result

The url is "https://www.gatsbyjs.com/docs/?=123"

### Environment

  System:
    OS: Linux 5.10 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 15.6.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.11 - /usr/bin/npm
  Languages:
    Python: 3.9.1 - /usr/bin/python
  Browsers:
    Firefox: 84.0.2
  npmPackages:
    gatsby: ^2.26.1 => 2.30.3 
    gatsby-plugin-manifest: ^2.5.2 => 2.10.0 
  npmGlobalPackages:
    gatsby-cli: 2.13.1

**Comment by LekoArts** [comment]
Thank you for opening this!

This is something you'll need to configure for your webserver. On `gatsby.com` we enforce trailing slashes but it will work the same. For example [https://www.gatsbyjs.com/starters/?c=Airtable&v=2](https://www.gatsbyjs.com/starters/?c=Airtable&v=2) also has the trailing slash, the filtering still works.

So if you don't want those on your own site you'll need to configure your webserver to do so.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
