### ISSUE TITLE
  ERROR #85901  GRAPHQL  There was an error in your GraphQL query:  Unexpected error value: "failed to process https://api.flotiq.com/image/0x0/_media-5b0c7d0c-6973-480b-b885-59d3fd74cedf.jpg\nError: EPERM: operation not permitted

### ISSUE THREAD

**Issue by StudioMontreal** [gatsbyjs/gatsby#29116]
## Description

Running the "gatsby build" command keeps giving me the following errors:
![error1](https://user-images.githubusercontent.com/51174369/105248359-421c8080-5b44-11eb-8b93-400c71b91744.PNG)
![error2](https://user-images.githubusercontent.com/51174369/105248366-46e13480-5b44-11eb-95e0-741dfd5d5e67.PNG)

I've tried deleting the cache, with npm run clean and gatsby clean, I deleted and reinstall the modules folder. I tried deleting the image files that failed to process and restart, but every time I restart there's a new image file that fails to process. I deleted the sharp folder inside the modules folder and reinstall both the "gatsby-transformer-sharp" and the "gatsby-plugin-sharp" but nothing works. 

The "gatsby develop" command is working fine, however, I get a warning saying "query takes too long". 

I'm using Flotiq.

### Steps to reproduce

Run the "gatsby build" command

### Expected result

The site gets compiled successfully

### Actual result

The build process is not finished

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.31.0 => 2.31.0
    gatsby-background-image: ^1.3.1 => 1.3.1
    gatsby-image: ^2.7.0 => 2.7.0
    gatsby-plugin-react-helmet: ^3.6.0 => 3.6.0
    gatsby-plugin-sharp: ^2.13.1 => 2.13.1
    gatsby-plugin-styled-components: ^3.6.0 => 3.6.0
    gatsby-source-filesystem: ^2.7.0 => 2.7.0
    gatsby-source-flotiq: ^2.2.1 => 2.2.1
    gatsby-transformer-sharp: ^2.11.0 => 2.11.0
  npmGlobalPackages:
    gatsby-cli: 2.18.0

Thanks in advance.

**Comment by LekoArts** [comment]
Hi!

Please open an issue on their repository about this: https://github.com/flotiq/gatsby-source-flotiq

Thanks!
