### ISSUE TITLE
Invalid plugin options "related_applications" gatsby-plugin-manifest

### ISSUE THREAD

**Issue by samponeill** [gatsbyjs/gatsby#29112]
Adding a webapp as a related application gives me the following:

- "related_applications[0].platform" must be one of [narrow, wide, chromeos,
ios, kaios, macos, windows, windows10x, xbox, chrome_web_store, play, itunes,
microsoft]
- "related_applications[0].id" is required

whereas w3c options include:
"chrome_web_store": Google Chrome Web Store.
"play": Google Play Store.
"itunes": iTunes App Store.
"webapp": Web apps.
"windows": Windows App Store.

https://github.com/w3c/manifest/wiki/Platforms

Is it possible to add the above options and disable the requirement for id for webapps?

**Comment by LekoArts** [comment]
Thank you for opening this!

As per the W3 spec you need to have an `id` or `url`: https://www.w3.org/TR/appmanifest/#externalapplicationresource-and-its-members

So our error logging is working as expected here.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by samponeill** [comment]
@LekoArts thanks for taking the time to respond

I have a URL but it is requiring me to have an id as well. 

From the spec:
"A valid ExternalApplicationResource dictionary MUST have platform and **either** an url **or** an id (or both)."

Being required to have an id despite having a URL is not to spec. Also please can you address the platforms issue? Webapp is a known possible value according to the wiki but is not being allowed here

**Comment by samponeill** [comment]
@LekoArts thanks for adding that in!

As for id – you say I need an id or url and I have a url but I'm still encountering an error message saying I need an id. Should it be url or id rather than requiring id no matter what?

"A valid ExternalApplicationResource dictionary MUST have platform and **either** an url **or** an id (or both)."
from W3 spec you referenced (emphasis mine)
