### ISSUE TITLE
Please include the paramter list for the Gatsby Node API function sourceNodes

### ISSUE THREAD

**Issue by K20shores** [gatsbyjs/gatsby#29121]
## Summary

Gatsby docs do not include a detailed description of the parameters for the [`sourceNodes`](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#sourceNodes) function for the Gatsby Node API.

### Motivation

They should be included.

## Steps to resolve this issue

Add the parameters

**Comment by LekoArts** [comment]
Thank you for opening this!

The documentation page begins with the introduction: https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#introduction where it has this section:

> Every Gatsby Node API passes a set of Node API helpers. These let you access several methods like reporting, or perform actions like creating new pages.

So to not repeat ourselves for every API we have there's this separate page for all parameters: https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
