### ISSUE TITLE
Gatsby Link (location.state) is not working on Netlify

### ISSUE THREAD

**Issue by DusanSmutny** [gatsbyjs/gatsby#29123]
## Description

As per documentation Link allows passing state prop ... https://gatsbyjs-org-prefetched.netlify.app/docs/gatsby-link/
After deployment on Netlify, state prop is undefined

### Steps to reproduce

<Link to="/gallery" className="button" state={{ myid: true }}>Gallery</Link>
on target added simple console.log to see result on Netllify deploy console

![image](https://user-images.githubusercontent.com/47855406/105291594-f48e2b00-5bb8-11eb-9721-aeb9904a3198.png)

### Expected result

props.location.state should be available on Link target component however is undefined

What should happen?

It's trivial use case

### Actual result

Does not work as expected

What happened.

State is undefined

### Environment

Deploeyd under Netlify Free account (used netlify.toml more less default for Functions setup)
Locally all works as expected.

**Comment by DusanSmutny** [comment]
Sorry, source code was cleared by picture. It's almost the same as in your doc.

<Link to="/gallery" className="button" state={{ myid: true }}>Galéria</Link>

and on target
const Gallery = ( {location}) => {
   console.log("Gallery location=",location)    
   console.log("Gallery location.state",location.state)
....

**Comment by LekoArts** [comment]
Thank you for opening this!

This is working as expected. The `state` is only available on the client, not during rendering in Node on the server.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!
