### ISSUE TITLE
Page queries taking longer to run without field extension

### ISSUE THREAD

**Issue by jabrks** [gatsbyjs/gatsby#29139]
## Description

I originally raised this [in a discussion](https://github.com/gatsbyjs/gatsby/discussions/28518) but I _think_ it's an issue so I thought it would be worth filing a report here.

I have a site where some of the source data contains image paths that Gatsby can't resolve to file nodes by default. In order to mitigate that, we use a field extension to resolve them at build time.

The original requirement for the image paths to be written this way no longer exists, so I set out to fix the paths and remove the field extension. I was mostly expecting the build time to stay the same, however after making the change the site now takes around 4 times longer on average to build, with most of this extra time being spent running the page queries.

### Steps to reproduce

https://github.com/jabrks/gatsby-field-extension
https://github.com/jabrks/gatsby-no-field-extension

### Expected result

Both sites should take the same amount of time to build

### Actual result

The site with the field extension took 93 seconds to build, where as the site without the field extension took 398 seconds to build

### Environment

```
System:
  OS: macOS 11.0.1
  CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
  Yarn: 1.22.10 - /usr/local/bin/yarn
  npm: 6.14.11 - ~/.nvm/versions/node/v12.18.4/bin/npm
Languages:
  Python: 2.7.16 - /usr/bin/python
Browsers:
  Chrome: 88.0.4324.96
  Edge: 88.0.705.50
  Firefox: 84.0.1
  Safari: 14.0.1
npmPackages:
  gatsby: ^2.29.1 => 2.29.1
  gatsby-source-filesystem: ^2.8.0 => 2.8.0
  gatsby-transformer-yaml: ^2.8.0 => 2.8.0
npmGlobalPackages:
  gatsby-cli: 2.18.0
  gatsby-dev-cli: 2.7.21
```

**Comment by vladar** [comment]
Does the `gatsby-field-extension` example actually work for you? For me it always returns `null` for `Meta.Image` field in query results. 

When I fix the resolver to actually return the proper `File` - I get pretty similar build times.

**Comment by jabrks** [comment]
The `gatsby-field-extension` example definitely seems to be working for me...

<img width="931" alt="image" src="https://user-images.githubusercontent.com/52410024/106207348-86012c80-61b9-11eb-88f9-9cc72125877c.png">

What changes did you have to make to fix the resolver on your side out of interest?

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
