### ISSUE TITLE
Gatsby build adds <!-- --> between string when build (SSR)

### ISSUE THREAD

**Issue by shi-rudo** [gatsbyjs/gatsby#29155]
## Description

When I generate a compound string like this: 

```javascript
...
<td>{someTitle} {somethingElse}</td>
...
```

Gatsby turns this into:
```javascript
<td>This is a title<!-- --> <!-- -->300</td>
```

### Steps to reproduce

The issue **does not** appear when I use the **current** `gatsby new bug-repro https://github.com/gatsbyjs/gatsby-starter-hello-world`.  However, **updating this repro to the latest version** causes this **error to appear** when using `build` or `GATSBY_EXPERIMENTAL_FAST_DEV=true gatsby develop`. It does not happen when using `gatsby develop`.

Gatsby gatsby-starter-hello-world uses:

```
├── gatsby@2.26.1
├── prettier@2.2.1
├── react@16.13.1
└── react-dom@16.13.1
```

✅-> String does **not** contain `<!-- -->`
Minimal repro: https://github.com/shi-rudo/bug-repro-older-no-string-error

Gatsby updated gatsby-starter-hello-world uses:

```
├── gatsby@2.31.1
├── prettier@2.2.1
├── react@16.14.0
└── react-dom@16.14.0
```

❌ -> String **does** now contain `<!-- -->`
Minimal repro: https://github.com/shi-rudo/bug-repro-string-bug

### Expected result

```javascript
<td>This is a title 300</td>
```

### Actual result

```javascript
<td>This is a title<!-- --> <!-- -->300</td>
```

### Environment

```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.5.0/bin/npm
  Languages:
    Python: 3.7.6 - /Users/trex/opt/anaconda3/bin/python
  Browsers:
    Chrome: 87.0.4280.141
    Edge: 88.0.705.50
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.31.1 => 2.31.1
  npmGlobalPackages:
    gatsby-cli: 2.18.0
```

**Comment by shi-rudo** [comment]
with more complex layout it leads to strong malformations
![chrome screenshot](http://www.dlds.de/pub/gatsby/string/error.jpg)

**Comment by nathanchu** [comment]
The `<!-- -->` issue seems to be coming from `react-dom`, not from gatsby.
```js
const React = require('react')
const ReactDOMServer = require('react-dom/server')
ReactDOMServer.renderToString(<span><b>{'title'}</b> {'weight'} g</span>)
// "<span data-reactroot=\"\"><b>title</b> <!-- -->weight<!-- --> g</span>"
// https://runkit.com/nathanchu/600cc9ad5ea79d00192e6a1e
```
That could be easily removed by using an html minifier used by gatsby though, or even a regex (maybe).


I'm not sure what the malformations are caused by, I'll have to look into those.

**Comment by ascorbic** [comment]
Hi. Are you able to confirm whether the change was introduced in the gatsby upgrade, or the react-dom upgrade?
