### ISSUE TITLE
Bump version of contentful in gatsby-source-contentful to fix vulnerability 

### ISSUE THREAD

**Issue by devuxer** [gatsbyjs/gatsby#29152]
## Description

**gatsby-source-contentful** depends on **contentful ^7.14.12**, which depends on **axios 0.20.0**, which has a high severity vulnerability. Recommend bumping the **contentful** dependency to the latest version.

### Steps to reproduce

1. Begin with a fresh gatsby site
2. `npm install gatsby-source-contentful`
3. `npm audit`

### Expected result

No security vulnerabilities

### Actual result

1 security vulnerability.

### Environment

(not relevant)

**Comment by LekoArts** [comment]
Thank you for opening this!

First and foremost: The **possible** vulnerability in the package won't affect your live site.
We can't bump the contentful package at the moment as the version that has the fixed axios version relies on Node 12 and we currently still support Node 10. When we'll change the minimum Node version to 12 (which will be soon) we'll update the package.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by willm** [comment]
We would like to run `npm audit` as part of CI to ensure we don't accidentaly include insecure dependencies. This is the only package reporting high severity errors, it would be nice to fix it.

**Comment by lorvsso** [comment]
Hi, Node 10 has reached End-of-Life https://github.com/nodejs/Release#nodejs-release-working-group

As per Gatsby docs it looks like Gatsby no longer needs to support Node 10 and is unblocked from fixing this issue https://www.gatsbyjs.com/docs/upgrading-node-js/

Can we open this issue back up please?

**Comment by LekoArts** [comment]
This has been already fixed:

https://github.com/gatsbyjs/gatsby/blob/c94fadd3806776ce8f445c63d4fcaae87db78a54/packages/gatsby-source-contentful/package.json#L18
