### ISSUE TITLE
There was a problem reading the file: ***

### ISSUE THREAD

**Issue by davidlindercodes** [gatsbyjs/gatsby#29153]
## Description

I just started using gatsby today and just installed it on my machine. I was working my way through the tutorial when I accidentally mistyped the name of the file 'cantact.js' rather than 'contact.js' 

I noticed my error and immediately fixed the typo, however, when I go to save the file, I get the error: 
```
"There was a problem reading the file: C:/Users/Drakom/hello-world/src/pages/cantact.js"
(referring to the original misspelling).
```

This (now closed) issue suggested that if I delete the cache files that would help. But now I just get the error: 
```
There was a problem reading the file: C:/Users/Drakom/hello-world/.cache/dev-404-page.js

File: C:/Users/Drakom/hello-world/.cache/dev-404-page.js

There was a problem reading the file: C:/Users/Drakom/hello-world/src/pages/cantact.js

File: C:/Users/Drakom/hello-world/src/pages/cantact.js

```

Also in that issue, now closed, it suggested that the V2 gatsby solved this issue, but I am using Gatsby CLI version: 2.18.

 

### Steps to reproduce

1.  Run Gatsby CLI version: 2.18. 
2. Work your way through this https://gatsbyjs.com/docs/tutorial/part-one/
3. Change the name of one of the files 

### Expected result

It should use the new name

### Actual result

It was still looking for the old filename and gave me error because that file name did not exist, even though I was not referring to that file name anywhere

### Environment

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.1
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.75)
  npmGlobalPackages:
    gatsby-cli: 2.18.0

**Comment by davidlindercodes** [comment]
code here: 
https://github.com/davidlindercodes/portfolio

**Comment by ascorbic** [comment]
Hi. When you say you deleted the cache files, do you mean you ran `gatsby clean`? If not, try that. Your repo runs fine for me locally.

**Comment by davidlindercodes** [comment]
gatsby clean did the job, thank you!!! I was just about to start learning Next.js too! hah
