### ISSUE TITLE
Unable to pass second argument to "require.resolve"

### ISSUE THREAD

**Issue by tsvetomir** [gatsbyjs/gatsby#29224]
## Description

The global [`require.resolve`](https://nodejs.org/docs/latest-v10.x/api/modules.html#modules_require_resolve_request_options) method is overloaded in [v8-compile-cache](https://github.com/zertosh/v8-compile-cache/blob/v1.1.2/v8-compile-cache.js#L161). The referenced version (v1.1.2) does not support passing `options` as a second argument.

I suggest upgrading to v2.2.0 or dropping the dependency entirely, provided it does not negatively affect benchmarks.

Notes: There are some hints([issue 6](https://github.com/zertosh/v8-compile-cache/issues/6#issuecomment-700858100), [issue 33](https://github.com/zertosh/v8-compile-cache/issues/33)) that this approach may be outdated. I find it's use questionable as Gatsby is all about extensibility and altering fundamental globals is a big no-no in that context.

### Steps to reproduce

Add the following snippet in `gatsby-node.js`:
```js
console.log(require.resolve.toString());
```

You should see a function with two arguments ([source](https://github.com/zertosh/v8-compile-cache/blob/v2.2.0/v8-compile-cache.js#L163)), but it only has one ([source](https://github.com/zertosh/v8-compile-cache/blob/v1.1.2/v8-compile-cache.js#L161)):
```js
function(request) {
  return Module._resolveFilename(request, mod);
}
```

### Expected result

I should be able to invoke `require.resolve` with `options`.

### Actual result

The `options` argument is ignored.

### Environment

```
  System:
    OS: Linux 5.10 Arch Linux
    CPU: (4) x64 Intel(R) Xeon(R) CPU E3-1245 v3 @ 3.40GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 10.23.1 - /usr/bin/node
    Yarn: 1.22.10 - ~/.npm/bin/yarn
    npm: 6.14.11 - ~/.npm/bin/npm
  Languages:
    Python: 3.9.1 - /usr/bin/python
```

**Comment by ascorbic** [comment]
Thanks! It looks like this is safe to upgrade, and at some point in the future we can benchmark whether it's still needed.

**Comment by tsvetomir** [comment]
That's great news, thanks!

I did a quick "benchmark" by toggling the [`DISABLE_V8_COMPILE_CACHE`](https://github.com/zertosh/v8-compile-cache/blob/v1.1.2/v8-compile-cache.js#L326) flag and building a fairly large site. That's completely unscientific as it does not remove the effects of networking and file caching. But the numbers are fairly close.

| Operation | With cache | Without cache |
| :-- | :-- | :-- |
| run page queries | 1328.540s - 4122/4122 3.10/s | 1313.771s - 4122/4122 3.14/s |
| write out requires | 0.029s | 0.028s |
| Building production JavaScript and CSS bundles | 23.441s | 22.675s |
| Rewriting compilation hashes | 0.005s | 0.003s |
| Building HTML renderer | 11.497s | 12.470s |
| Building static HTML for pages | 15.724s - 4122/4122 262.15/s | 15.418s - 4122/4122 267.35/s |
| Generating image thumbnails | 1386.499s - 54/54 0.04/s | 1371.062s - 54/54 0.04/s |
| onPostBuild | 0.004s | 0.005s |
| Overall | 1438.973508358 sec | 1422.011720118 sec |
