### ISSUE TITLE
WebpackError: TypeError: Cannot read property 'childImageSharp' of null  | Only happenning on build

### ISSUE THREAD

**Issue by MartinSchere** [gatsbyjs/gatsby#29239]
My gatsby app is able to find the static images in development, and they work perfectly. But the build process terminates with the message in the title of this issue:

` WebpackError: TypeError: Cannot read property 'childImageSharp' of null`

This is most likely caused by this error in the graphql query (correct me if I'm wrong):

`Field "xxx" must not have a selection since type "String" has no subfields`

I double-checked the images referenced in the markdown files (can also be seen in the repo below) and it doesn't seem to be the problem. I also have the `gatsby-remark-relative-images` package installed and set-up _before_ `gatsby-plugin-netlify-cms`. 

To reproduce this, simply clone my public repo:

https://github.com/MartinSchere/gatsby-test-ts

When trying to build, it'll fail with the above error

Environment:
```
System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 AMD Ryzen 5 1400 Quad-Core Processor
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.23.0 - /usr/bin/node
    npm: 6.14.11 - /usr/bin/npm
  npmPackages:
    gatsby: ^2.26.1 => 2.26.1
    gatsby-image: ^2.10.0 => 2.10.0
    gatsby-plugin-graphql-codegen: ^2.7.1 => 2.7.1
    gatsby-plugin-netlify-cms: ^4.9.0 => 4.9.0
    gatsby-plugin-netlify-cms-paths: ^1.3.0 => 1.3.0
    gatsby-plugin-sass: ^3.1.0 => 3.1.0
    gatsby-plugin-sharp: ^2.13.1 => 2.13.1
    gatsby-plugin-typescript: ^2.11.0 => 2.11.0
    gatsby-remark-images: ^3.10.0 => 3.10.0
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-filesystem: ^2.10.0 => 2.10.0
    gatsby-transformer-remark: ^2.15.0 => 2.15.0
    gatsby-transformer-sharp: ^2.11.0 => 2.11.0
  npmGlobalPackages:
    gatsby-cli: 2.17.1
```

**Comment by ascorbic** [comment]
Hi. The error is happening because you have an empty markdown file `alert.md`. When it tries to build that page, the frontmatter fields are all null, and you have no null checking:
```json
  language: {
    whatis: null,
    bottomImage: null,
    commonUseCases: null,
    companies: null,
    featuredImg: null,
    features: null,
    languageImg: null,
    name: null,
    technologies: null,
    title: '',
    topics: null
  }
```
You should either remove the empty file, or add null checks to the template so that it will build the empty page. A good pattern in all cases is to add null checks when using images. e.g. change the main template to:

```tsx
        {language.featuredImg && (
          <Img
            fluid={language.featuredImg?.childImageSharp?.fluid}
            className="featured-img"
          />
        )}
```

**Comment by MartinSchere** [comment]
Awesome! Thanks a lot
