### ISSUE TITLE
Documentation header text blurry in Chrome, Safari on low-DPI monitors (like 1080p)

### ISSUE THREAD

**Issue by adamjcooper** [gatsbyjs/gatsby#29259]
The documentation header applies a CSS style rule of `backdrop-filter: blur(8px)`. Unfortunately, this can cause the text within the header to appear blurry in Chrome and Safari on a low-DPI display:

![image](https://user-images.githubusercontent.com/443020/106199473-82eb4980-6183-11eb-8529-0dd67eb6f2a7.png)

As I resize the width of the browser window, I notice the header text changes from blurry to crisp and back with each pixel width change (resize window 1 pixel width smaller, text becomes crisp, resize window 1 pixel width smaller, text becomes blurry, etc.). On a 1920x1080 external monitor, when the browser window is maximized the header text is unfortunately blurry. 

I've observed this behavior in both Chrome and Safari (Firefox's renderer does not have this problem). I've only observed this effect on low-DPI displays; the header text remains crisp at all window widths on my "retina" MacBook display.

The cause seems to be the use of `backdrop-filter: blur(8px);` (and the way that Chrome and Safari handle text rendering when this backdrop filter is applied). When I disable this rule in dev tools the header text remains crisp on my 1920x1080 external monitor at all window widths.

It looks like you're using this CSS rule to create a sort of "frosted glass" effect for your header. Unfortunately, text legibility will suffer for some readers. Consider removing both transparency and the backdrop-filter rule for your site styling.

Hope this helps, and thanks for Gatsby.

**Comment by Dhruvpatel32** [comment]
hii adamjcooper ,
this is because you have use backdrop-filter: blur(8px); this affects the whole content you want to style.
you should use the   filter: blur(8px); this only affects the background of your content, not the word written in it
