### ISSUE TITLE
.env variable exposed to browser

### ISSUE THREAD

**Issue by matteofrana** [gatsbyjs/gatsby#29256]
## Description

If I create a `.env.development` file with a var **without the `GATSBY_` prefix** I see it is accessible in the browser.

### Steps to reproduce

https://github.com/ReactBricks/test-env-gatsby

### Expected result

I expected not to be able to render and `console.log` the `SECRET_KEY` variable.

### Actual result

I can render and console.log the `SECRET_KEY` variable.

### Environment

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 57.0.4
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.26.1 => 2.31.1
```

**Comment by KyleAMathews** [comment]
Ok, confirmed the reproduction. It happens in both dev & production. It's not a security hole per se as the env variables are swapped out when webpack compiles the code. They're not accessible at `process.env.X` in the browser. So a `SUPER_SECRET_KEY` wouldn't be accessible. Tests were added for this by @pieh here https://github.com/gatsbyjs/gatsby/pull/10030

So the question here is why is our docs (https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/#client-side-javascript) at odds with the implementation. Or why is our implementation inconsistent. We read all env variables from the `.env.X` files indiscriminately but we _do_ filter by `GATSBY_` from the actual environment (e.g. `GATSBY_API_KEY=xyz gatsby develop` works but `API_KEY=xyz gatsby develop` doesn't. 

You can see the implementation here: https://github.com/gatsbyjs/gatsby/blob/1da331a5352e3f7cb18f69050b7199481d85fbcb/packages/gatsby/src/utils/webpack.config.js#L51-L110

This does make sense to me IMO as `.env.X` files are more locked down — they only have in them what you put in them — whereas the terminal env is more open-ended but... you're unlikely still to be referencing random env variables all the same.

This was the original PR adding it and we were I guess copying CRA's pattern https://github.com/gatsbyjs/gatsby/pull/2057

**Comment by tjjjwxzq** [comment]
Bump, was there ever any resolution to this issue? I'm on gatsby `3.12.1`, and I'm encountering behaviour where environment variables, even without the `GATSBY` prefix, seem to be available in the local dev server as well as a locally served and built site (ie. `gatsby build` followed by `gatsby serve`), but they are correctly missing in the production site hosted on Gatsby Cloud.

This was initially very confusing as I couldn't seem to reproduce the error at all locally. Is the `gatsby build` process somehow different run on Gatsby Cloud vs your local machine? When I check the bundled code, the literal values for those env vars are visible in the locally built app, but they are missing on the production site in Gatsby Cloud. Was this issue ever fixed?

**Comment by nboliver** [comment]
bump @KyleAMathews we are noticing the same thing as @tjjjwxzq on gatsby@3.14.6. Any explanation as to why the build command works differently locally vs netlify / gatsby cloud would be super appreciated, as it's easy to think you could be exposing secrets since they can be console logged. Thanks!

**Comment by nboliver** [comment]
@tjjjwxzq I was confused about this too. If you read @KyleAMathews comment above, he mentions that there is a difference between `.env.x` (what you'd use locally) files and and an actual environment variable (what gatsby cloud uses). hope this helps someone else that's confused!
