### ISSUE TITLE
Delete html files from previous builds is not deep enough

### ISSUE THREAD

**Issue by vibertthio** [gatsbyjs/gatsby#2926]
https://github.com/gatsbyjs/gatsby/blob/940563bc9519e74424a0905126cef0f768067fc7/packages/gatsby/src/bootstrap/index.js#L66

If you have structure deeper than 2 like mine (as shown below)

.
├── ...
├── public                    
│   ├── projects
│   ├── blogs
│  │   ├── 2017-10-01
│  │  │    ├──  index.html
│  │   ├── 2017-10-02
└── ...

"That" index.html would not be deleted.
It really is a pain in my ass until I found this problem.

**Comment by KyleAMathews** [comment]
This doesn't seem right — the _globstar_ `**` matches all subdirectories.

**Comment by KyleAMathews** [comment]
https://github.com/isaacs/node-glob#glob-primer

We don't limit the depth of deletion.

Perhaps something else is causing the file not to be deleted?

**Comment by vibertthio** [comment]
Oh yes, I think I found the real problem. Its in the cache.
I found that if I use prefix setting in build and no-prefix in local dev,
the cache wouldn't be replaced, and make the prefix settings not working right.

I solved this problem with an extra script that delete the ./.cache every time I run the dev server or build.

```
echo "#### Cleaning cache"
rm -rf ./.cache/
```

here is the repo and how I use.
https://github.com/vibertthio/portfolio

-------------
I know the description above is not quite clear enough to address the issue, but I will find other day to deliberate it! Thank you.

**Comment by KyleAMathews** [comment]
How is the cache causing trouble when switching between prefixed and non-prefixed builds? There shouldn't be any differences in what's cached in the two styles of builds and if there is, let's try to narrow that down and fix it.

**Comment by vibertthio** [comment]
It's the url of the remark-image isn't modify properly with prefix when cache is presented. I will give you a procedure to reproduce the problem.
Do you have any clue of that where the problem of image link in markdown is?

**Comment by vibertthio** [comment]
I reproduce the bug in this [repo](https://github.com/vibertthio/gatsby-remark-image-prefix-bug)

Try deploy to gh-pages w/ and w/o cleaning cache first. You can see that the remark-image url produced by gatsby is wrong w/o cleaning cache.
Moreover, I searched the exact url in my project directory, and found that the cache contained some info about the exact url. These are two reason why I think the bug of remark image url prefix comes from cache folder.

**Comment by arggh** [comment]
I think I bumped into this one too. I have to clear `.cache` (also I clean public just in case) between starting `gatsby develop` and building. Otherwise some of the prefixed paths break:

The development version might be using the prefixed paths or the built&deployed version might be missing them, causing at least broken images.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
