### ISSUE TITLE
"Found X changed pages" on every build even if files not changing, triggering query rebuild. Getting all the time `verbose Found ${totalPages} changed pages` when using `gatsby-transformer-remark` plugin

### ISSUE THREAD

**Issue by stevemarksd** [gatsbyjs/gatsby#29273]
## Description

I see this all the time I run `gatsby build`.

![image](https://user-images.githubusercontent.com/58653359/106374496-e3b29600-63be-11eb-8d28-de37c4cdbfda.png)

### Steps to reproduce

 - Install a brand new gatsby with no extra features
 - Install `gatsby-transformer-remark` 

gatsby-config.js

```
module.exports = {
  plugins: [
    {
      resolve: `gatsby-transformer-remark`,
      options: {},
    },
  ],
}
```

gatsby-node.js
```
exports.createPages = async ({actions, graphql}) => {
  const {createPage} = actions
  createPage({
    path: `/404/`,
    component: require.resolve(`./ErrorPage.tsx`),
    context: {},
  })
}
```

ErrorPage.tsx
```
import * as React from 'react'

const NotFound = () => {
  return <span>ssssssss</span>
}

export default NotFound
```

**Note**: 

if we remove 

```
    {
      resolve: `gatsby-transformer-remark`,
      options: {},
    },
```

changed pages is 0.

### Expected result

`verbose Found 2 changed pages` should be `verbose Found 0 changed pages`

### Actual result

`verbose Found 2 changed pages`

### Environment

```
"./node_modules/.bin/gatsby" info --clipboard

  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 14.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.5
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.56)
  npmPackages:
    gatsby: ^2.26.1 => 2.31.1
    gatsby-transformer-remark: ^2.15.0 => 2.15.0
```

**Comment by LekoArts** [comment]
I don't understand, what's the actual issue here?

**Comment by stevemarksd** [comment]
> I don't understand, what's the actual issue here?

@LekoArts  Found X changed pages on every build, even if you don't change any page. This doesn't seem correct, right?

**Comment by stevemarksd** [comment]
Upgraded to gatsby v3... anyway I could debug this myself?

**Comment by stevemarksd** [comment]
nobody else is getting this issue?

**Comment by stevemarksd** [comment]
@vladar sorry to bother you, but do you think the gatsby-transformer-remark has a bug? I'm not sure how nobody noticed this yet

I tried v3 and v4 same issue, even with latest gatsby

**Comment by rinorzek** [comment]
I also have this issue
