### ISSUE TITLE
Gatsby Link's all of a sudden not working on build (when visit page link it shows nothing until refresh)

### ISSUE THREAD

**Issue by anderskitson** [gatsbyjs/gatsby#29305]
## Description

Gatsby Links send me to the right page, but they load just a white screen, nothing loads in the dom, until I hit refresh.
This started happening all of a sudden

### Steps to reproduce

If you click on the curations link in the navigation it just takes you to a blank page. where it should load the page, it doesnt work until I hit refresh

Here is my repo https://github.com/wispyco/fix-me

the website is at https://studioconscious.com

and there is a password but we are trying to go live so I am fine sharing it it is 

pass: conscious63901

### Expected result

the link should navigate to the page and load the html content

### Actual result

loads a blank page with nothing in the dom besides the body

### Environment

Also fails on netlify

System:
    OS: Linux 5.8 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Shell: 3.1.2 - /usr/bin/fish
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 85.0
  npmPackages:
    gatsby: ^2.32.0 => 2.32.0
    gatsby-image: ^2.11.0 => 2.11.0
    gatsby-omni-font-loader: ^1.3.0 => 1.3.0
    gatsby-plugin-manifest: ^2.12.0 => 2.12.0
    gatsby-plugin-offline: ^3.10.0 => 3.10.0
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0
    gatsby-plugin-sharp: ^2.14.0 => 2.14.0
    gatsby-plugin-styled-components: ^3.10.0 => 3.10.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.11.0 => 2.11.0
    gatsby-source-instagram: ^0.9.0 => 0.9.0
    gatsby-source-sanity: ^6.0.5 => 6.0.5
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0
  npmGlobalPackages:
    gatsby-cli: 2.12.87

**Comment by ascorbic** [comment]
Hi,
When I click through, it's giving me an hCaptcha error. Could this be causing the problem?

**Comment by anderskitson** [comment]
The thing I don't understand is there is no captcha on that page, and it works fine in development, but as soon as it's built I get that error. Why would it be looking for hcaptcha on that page I wonder, on any of them curations, goods, concepts, or blog.

**Comment by anderskitson** [comment]
> Hi,
> When I click through, it's giving me an hCaptcha error. Could this be causing the problem?

If this is the issue I have no idea why, there are no captcha's on any of these pages that just load a blank white screen. They work after hitting refresh so I dont understand why that would be. This started happening out of nowhere as far as I can tell, but no ruling out a mistake by me.

**Comment by anderskitson** [comment]
I had to remove the captcha for now and still nto sure what is going on. I changed the pass on the site so it will no longer be accesible but the repo will be. So I think this is still a bug but I have a temporary fix for myself.

**Comment by anderskitson** [comment]
Im closing this for I think it's a incompatibility with recaptcha after a npm update (possibly) but no need to keep this open now.
