### ISSUE TITLE
dev-404-page in allSitePage query in production

### ISSUE THREAD

**Issue by spikyjt** [gatsbyjs/gatsby#29318]
## Description

In production mode, a static query to `allSitePage` includes a node with the path `/dev-404-page/`, in addition to the expected `/404/` and `/404.html`.

Additionally, in develop mode (where this page is expected to be present) the property `isCreatedByStatefulCreatePages` is `true` for this page, but in production mode it is `false`, which makes it more difficult to filter out.

### Steps to reproduce

- Create a gatsby site using the standard generator.
- Add a static query that lists all pages in a component e.g.:
  ```graphql
  {
    allSitePage {
      nodes {
        path
        isCreatedByStatefulCreatePages
      }
    }
  }
  ```
- Log the results and examine output in both develop and production modes.

_N.B. I would create a sample site, but all the docs about contributing to this project are 404 at the moment_

### Expected result

Dev 404 page should not be present in production.
(Or at least the property `isCreatedByStatefulCreatePages` should be consistent regardless of mode)

### Actual result

Dev 404 page is present in production and `isCreatedByStatefulCreatePages` is unexpectedly `false`.

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 81.0
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.26.1 => 2.32.0 
    gatsby-plugin-sass: ^3.2.0 => 3.2.0 
    gatsby-plugin-sitemap: ^2.12.0 => 2.12.0 
```

**Comment by pieh** [comment]
As a workaround for this - I suggest using `allSitePage(filter: { path: { ne: "/dev-404-page/" } })` filter.

`isCreatedByStatefulCreatePages` is some internal that actually shouldn't even be exposed to graphql and also is not tied to dev-404-page - it being true or false can vary in regular pages too depending how those pages were created  (it will be `true` for pages created from automatic page creation in `/src/pages` and `false` for pages created in `gatsby-node` -> `createPages`), so it's not good filter for `dev-404-page`

**Comment by spikyjt** [comment]
@pieh I've figured out a filter that suits my needs. Was using `isCreatedByStatefulCreatePages` precisely so that it didn't bring in any 404 pages and other stuff in `src/pages`, as mine come in from markdown. Noted that it should be avoided though.

I was just surprised that a page that is clearly intended only for development is still present in production. That doesn't make any sense. Is there a good reason for it, or is it a bug?

**Comment by pieh** [comment]
> @pieh I've figured out a filter that suits my needs. Was using `isCreatedByStatefulCreatePages` precisely so that it didn't bring in any 404 pages and other stuff in `src/pages`, as mine come in from markdown. Noted that it should be avoided though.

I mean, you can use it if it suits your needs, in that case I would combine two filters: `allSitePage(filter: { isCreatedByStatefulCreatePages: { ne: true }, path: { ne: "/dev-404-page/" } })` (or something like that)

> I was just surprised that a page that is clearly intended only for development is still present in production. That doesn't make any sense. Is there a good reason for it, or is it a bug?

It is a bug I would say, but also one that was there for a loooong time, so changing it now (at least for v2) is potentially dangerous. For next major I would want to remove `dev-404-page` `SitePage` node completely (in both dev and prod), because `dev-404-page` isn't like "real" page and it flopping between dev and prod is not good (list of "real" pages shouldn't change between dev and prod)

**Comment by spikyjt** [comment]
> It is a bug I would say, but also one that was there for a loooong time, so changing it now (at least for v2) is potentially dangerous. For next major I would want to remove `dev-404-page` `SitePage` node completely (in both dev and prod), because `dev-404-page` isn't like "real" page and it flopping between dev and prod is not good (list of "real" pages shouldn't change between dev and prod)

@pieh that makes sense. So is the bug or the issue to do what you suggest already recorded for the next major release (i.e. we should close this) or should we keep this open to record it?

**Comment by dougwithseismic** [comment]
Slightly related; isCreatedByStatefulCreatePages is no longer accessible as part of allSitePage - Is there an alternative for when I want to grab all pages that have been created statefully? (When generating a sitemap for example).
