### ISSUE TITLE
Needs documentation for how to use new JSX transform

### ISSUE THREAD

**Issue by kylegoetz** [gatsbyjs/gatsby#29334]
## Summary

React says that Gatsby 2.24.+ supports the new JSX transform (and there's a merged PR here claiming it is supported) so we don't need to `import * as React from 'react'` anymore for React 17. So I started a new Gatsby project (2.26.x). It installed React 16.x, which doesn't support the new transform. I updated `react` and `react-dom` to 17.0.1 and removed the `import * as React from 'react'` line from `src/pages/index.js` and now I get a bunch of

```
101:5   error  'React' must be in scope when using JSX react/react-in-jsx-scope
```

for that file.

### Motivation

It should be documented because React and Gatsby both claim to support this for React 17, but there do not seem to be instructions for how to make this work.

## Steps to resolve this issue

Hell if I know. I've been trying to get this to work for a couple days now. Once it's working, I'm going to try to get it working with TypeScript, which I also failed to get working the past day.

**Comment by wardpeet** [comment]
@kylegoetz Thanks for opening the issue. We're working on supporting the new jsx transforms. Currently they are not supported unless you create a custom babelrc and mimic what `babel-preset-gatsby` does.

**Comment by MrReasonable** [comment]
This error is actually generated due to the eslint configuration and configuring babelrc doesn't fix it.  The issue appears to be due to https://github.com/gatsbyjs/gatsby/blob/5c3faff51494f5212c1db98b36bcef9de48c8b17/packages/gatsby/src/utils/webpack-utils.ts#L184 always evaluating to false.  This was introduced #27615

**Comment by Austaras** [comment]
> @kylegoetz Thanks for opening the issue. We're working on supporting the new jsx transforms. Currently they are not supported unless you create a custom babelrc and mimic what `babel-preset-gatsby` does.

@wardpeet any progress or roadmap yet?

**Comment by LekoArts** [comment]
@Austaras https://www.gatsbyjs.com/docs/reference/config-files/gatsby-config/#jsxruntime
