### ISSUE TITLE
webpack-configurator unmaintained

### ISSUE THREAD

**Issue by realseanp** [gatsbyjs/gatsby#2933]
The [webpack configurator module](https://github.com/lewie9021/webpack-configurator) hasn't been updated in 2 years and is really out of date. I'd like to request that you take your recommendation to use this this out of your documentation, since webpack has been updated several times over. I'm going to have to update the config without using webpack configurator.

**Comment by KyleAMathews** [comment]
We're going to drop it when we move to webpack 3. It still works fine for our current version of webpack (v1).
