### ISSUE TITLE
Where is the documentation for gatsby-source-wordpress v3?

### ISSUE THREAD

**Issue by 8ctopotamus** [gatsbyjs/gatsby#29358]
V3 docs have been replaced by V4 on the gatsby site, but some of us need to use v3 for a little bit longer. Where can we find the documentation for this version?

**Comment by LekoArts** [comment]
Hi! You can find it here: https://github.com/gatsbyjs/gatsby/blob/1da331a5352e3f7cb18f69050b7199481d85fbcb/packages/gatsby-source-wordpress/README.md

**Comment by 8ctopotamus** [comment]
@LekoArts Awesome, thanks for your help!
