### ISSUE TITLE
WP Preview doesn't work with the filesystem route api

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/gatsby#29361]
For me neither published posts or drafts ever load when selecting preview from WP.  Drafts throw this message:
![image](https://user-images.githubusercontent.com/2730871/102906133-d1495200-4439-11eb-90c1-4e77528d4835.png)

Published posts basically time out. Tyler I believe you have access to my site to check things out, let me know if you have questions. 

If you browse to the preview site directly published posts work fine. Drafts do appear on archive pages but the preview URL is broken: https://preview-moonmeisternet.gtsb.io/generated-preview-path/post/7176/

The only thing somewhat unique about my site that I can think of is the fact that I use the newish file-system routing API for posts. 

```

  System:
    OS: Linux 4.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.3 - /tmp/yarn--1608653875235-0.10626545320667291/node
    Yarn: 1.22.10 - /tmp/yarn--1608653875235-0.10626545320667291/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
  npmPackages:
    gatsby: ^2.29.1 => 2.29.1
    gatsby-image: ^2.8.0 => 2.8.0
    gatsby-plugin-feed: ^2.10.0 => 2.10.0
    gatsby-plugin-goatcounter: ^0.4.0 => 0.4.0
    gatsby-plugin-linaria: ^2.2.0 => 2.2.0
    gatsby-plugin-manifest: ^2.9.0 => 2.9.0
    gatsby-plugin-netlify: ^2.8.0 => 2.8.0
    gatsby-plugin-offline: ^3.7.0 => 3.7.0
    gatsby-plugin-postcss: ^3.4.0 => 3.4.0
    gatsby-plugin-preact: ^4.4.0 => 4.4.0
    gatsby-plugin-react-helmet: ^3.7.0 => 3.7.0
    gatsby-plugin-readingtime: ^1.0.1 => 1.0.1
    gatsby-plugin-robots-txt: ^1.5.3 => 1.5.5
    gatsby-plugin-sharp: ^2.11.1 => 2.11.1
    gatsby-plugin-sitemap: ^2.9.0 => 2.9.0
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-plugin-webpack-size: ^1.0.0 => 1.0.0
    gatsby-source-filesystem: ^2.8.0 => 2.8.0
    gatsby-source-wordpress-experimental: * => 6.0.0
    gatsby-transformer-sharp: ^2.9.0 => 2.9.0
```

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
