### ISSUE TITLE
Hard to read errors on Mac OS.

### ISSUE THREAD

**Issue by hbowden** [gatsbyjs/gatsby#2936]
It's hard to read error messages from gatsby with the default terminal on Mac OS.

![screen shot 2017-11-15 at 9 10 38 pm](https://user-images.githubusercontent.com/12447474/32872008-efc70730-ca49-11e7-8648-45641408f59a.png)

gatsby version: 1.9.112
node version: v8.9.1
Mac OS version: 10.12.6

**Comment by dustinhorton** [comment]
https://github.com/gatsbyjs/gatsby/issues/2645

**Comment by hbowden** [comment]
Ohh sorry didn't see that issue open.
