### ISSUE TITLE
Clarify the distinction between browser console and terminal console in part 7 of the tutorial

### ISSUE THREAD

**Issue by alanwsmith** [gatsbyjs/gatsby#29376]
## Summary

I ran into a problem in [part 7](https://www.gatsbyjs.com/docs/tutorial/part-seven/) of the tutorial.

The confusion started in part 6 where there's a `console.log(data)` line that outputs to the browser's devtools console. This is the behavior I expect given my experience outside of Gatsby. 

The first snippet of code in part 7 contains another `console.log()`. line:

    exports.onCreateNode = ({ node }) => {
      console.log(`Node created of type "${node.internal.type}"`)
    }

Below that, it says "Stop and restart the development server. As you do, you’ll see quite a few newly created nodes get logged to the terminal console."

The problem is that as someone new to Gatsby, I didn't realize it meant the command line console. Especially since the prior instance of `console.log()`went to the browser. I spent ten minutes trying to figure out what I was doing wrong before someone in chat told me to look at the command line. 

Clarifying that `console.log()` can go to multiple places would counteract the issue. 

### Motivation

Updating the documentation will help prevent confusion about the different output locations for `console.log()`. This will benefit anyone not already familiar with the functionality. 

## Steps to resolve this issue

In the [Creating slugs for pages](https://www.gatsbyjs.com/docs/tutorial/part-seven/#creating-slugs-for-pages) section, possible solutions include one or a combination of the following:

1. Update this:

    Stop and restart the development server. As you do, you’ll see quite a few newly created nodes get logged to the terminal console.

    To:

    Stop and restart the development server. As you do, you’ll see quite a few newly created nodes get logged to the terminal console. (Note, this is not the browser devtools console, but the command line terminal where the server is running.)

2. Or, add an image showing the terminal like the one further down the page under the snippet with:

        exports.onCreateNode = ({ node, getNode }) => {
          if (node.internal.type === `MarkdownRemark`) {
            const fileNode = getNode(node.parent)
            console.log(`\n`, fileNode.relativePath)
          }
        }

3. Or, add a note like:

    NOTE: `console.log()` outputs to different locations depending on where it's located. When used on pages (e.g. `./src/pages/index.js`, it outputs to the browser's devtools console. When used in ???? files (like the `gatsby-node.js` file shown here), the output goes to the command line terminal where the server is running.

    (I'm still new to Gatsby, so I don't know what type of files go in the ???? location)

Ideally, items 2 and 3 would go together. The last one would be the best if only one use used since it lays out the difference explicitly and would be more accessible than the alt description of an image that could have the same problem as the original text.

**Comment by kelvindecosta** [comment]
Hello there!

Usually, `console.log` calls in a configuration file, i.e., `gatsby-config.js`, `gatsby-node.js`, etc. will always output to the terminal.

You mentioned that `console.log` calls in an `src/pages` file output to the browser's console.
When `React` handles the `Component` defined in such files, these `log` calls are also run.
It really depends on when these components are rendered.

<details>
<summary>Example</summary>

```jsx
import React, {useState, useEffect} from "react"

 const MyComponent = () => {
    // Let us keep track of a value
    const [value, setValue] = useState(false)
    
    // Set the value to true when the component is mounted or updated on the browser
    useEffect(() => {
        setValue(true)
    }, [setValue])

    // Log the value
    console.log(value)

    return <>{value}</>
}

export default MyComponent
```

For the above Component:

- Terminal:
   ```bash
   false # server side rendering
   ```

- Browser:
   ```bash
   false # initially
   true #  once the component is mounted
   ```

</details>

The way I see it, **configuration code is somewhat static** when compared with `React` components.
The terminal console usually **logs information at build time that will probably not change**.
It makes sense for the calls in configuration files to ouput to the terminal.

> Below that, it says "Stop and restart the development server. As you do, you’ll see quite a few newly created nodes get logged to the **terminal** console."

The documentation  mentions that the output will be logged to the terminal..

I hope this helped you.

Happy coding!

**Comment by LekoArts** [comment]
Closing as stale/resolved as we haven't seen this issue arise in other instances.
