### ISSUE TITLE
Package documentation not linked from docs

### ISSUE THREAD

**Issue by sedubois** [gatsbyjs/gatsby#2938]
Sorry if this is a silly question and I'm missing something, but while trying to learn about Gatsby-image, I couldn't find any trace of it by going to gatsbyjs.org/docs (did a keyboard search on `gatsby-image` and `packages`).

However there _is_ a documentation page for it: https://www.gatsbyjs.org/packages/gatsby-image/

Should the packages documentation be linked from the main docs navigation?

**Comment by KyleAMathews** [comment]
It's linked to from here: https://www.gatsbyjs.org/docs/plugins/#official-components

We want to upgrade that plugins page to be a generic package search for all Gatsby related packages on NPM.

Perhaps we should rename the page from "plugins" to "packages"?

**Comment by sedubois** [comment]
If plugins and packages are interchangeable names, I would definitely discard one term in favor of the other.

The other issue is that on the gatsby-image [doc page](https://www.gatsbyjs.org/packages/gatsby-image/), there is nothing highlighted in the navigation sidebar, so it feels like it is a "rogue" page for someone who discovered it through another entry point (such as google in my case, or someone who would come from this GitHub issue).

Maybe the plugins/packages section should be highlighted, and for even more clarity there could be some breadcrumbs (or however that is called) at the top.

**Comment by KyleAMathews** [comment]
Yeah it's a bit awkward now — we're going to move to a design something like https://js.coach/ that'll make it a lot more clear you're looking at plugin/package documentation.

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
