### ISSUE TITLE
Gutenberg + ACF breaks preview in wordpress

### ISSUE THREAD

**Issue by lnikell** [gatsbyjs/gatsby#29390]
## Description

Since gatsby-wordpress-experimental move undo this repo, I will create this issue here. 
[Original discsussion](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/140)
Is there any ETA when Gutenberg and ACF will work properly, I understand that there is an issue either on WP or Gutenber side, however maybe there could be some options to make it work(hack). Gutenberg is the default text editor in WP and ACF is also a must-have option for all WP sites. So at this moment, I can't recommend Gatsby Cloud for non of our clients, since it just does not work for us, or speed up the deployment process.

### Steps to reproduce

- Install ACF
- Create Post with attached ACF fields and fill some data in the editor
- Use Preview

### Expected result

The page should be rendered

### Actual result

Nothing happens

### Environment

Since it's a known issue, so basically all version of the plugin  gatsby-wordpress-experimental/gatsby and wp-graphql/wp-gatsby affected by this

**Comment by TylerBarnes** [comment]
Hi @lnikell , thanks for opening this issue. I agree that this would be awesome but there isn't anything we can do about this. This is a problem with Gutenberg and isn't specific to Gatsby or Gatsby Cloud. The same issue exists in PHP WP themes. Once it's fixed upstream in Gutenberg it will work in Gatsby. If there's a workaround that could be added it would be in WPGraphQL - but I don't think Jason will be interested in adding it there. WP andWPGraphQL are very hookable so I would recommend:

1. Add your vote to the Gutenberg issue and express how much you need this https://github.com/WordPress/gutenberg/issues/16006
2. If you have the know-how - try making a WP plugin that works around this somehow. If you can find a good way to make it work there's a chance WPGraphQL or WPGatsby could implement your solution, as of now Jason and I don't have any ideas on making this work.

**Comment by Khoded-Andy** [comment]
I have managed to fix this by installing and activating the [Disable Gutenberg plugin](https://wordpress.org/plugins/disable-gutenberg/) and defining WP_POST_REVISIONS to 3:

`define( 'WP_POST_REVISIONS', 3 );`

Seems to have done the trick for published posts/pages.

Unbelievable that an issue like this has been known for so long and Gutenberg is even considered a MVP. Crazy. But here we are. Hopefully this fix works for others as well.
