### ISSUE TITLE
Gatsby Deploy messing with Font.js Import?

### ISSUE THREAD

**Issue by grafmark59** [gatsbyjs/gatsby#2939]
Hey,

so I've run into an issue with importing fonts from fonts.com. Instead of a link tag, they give you a script tag to insert into your code, and I think this has to be the issue, as I'm pulling a link tag with no problems from Google Fonts.

It's working on localhost (pre-compilation) but once I deploy it to GitHub pages and it becomes static, the download no longer works, and it returns the error:

`scrollLeft.js:19 GET https://fast.fonts.net/dv2/14/8dd355f9-1a9a-4d91-8aa1-7dcc9deeb439.woff2?d44f19a684109620e4841578a490e8187cac2bf7466ecccd35f843ec9e8410dc73fea4cea7acbbbaf9d830e48fc615a792f4b24a1c10853efb77f66879fc39a15a09593f079cf7a38cb48dd4836fa2ebba1b54d33b577d893508a6f4d0526453533728dec4671fee2d130ac32d5b8a97d5&projectId=0a390850-37c6-420c-8ead-c15e81202559 net::ERR_ABORTED`

Does something happen to script tags when they are built?

Thanks so much

**Comment by KyleAMathews** [comment]
Guessing you need to tell fonts.com about your production domain?

**Comment by grafmark59** [comment]
Hey yeah, I did this. I've used the domain both with and without the leading "www" and also the github.io page itself, all to no avail. Unfortunately, that's all they have as suggestions on how to deal with 403 on their side:
"Make sure that the website is correct"
But I've done that. So I was wondering if it could possibly be caused by the build function/webpack somehow messing with the script tags that are in the <Helmet>

**Comment by KyleAMathews** [comment]
It's possible depending on how the script tag is created. You can find out really quick by comparing the URLs for the font files in development and production.

**Comment by grafmark59** [comment]
So they urls seem to be the same. I've been digging through the network calls, and they're calling to the same location, but what's interesting is that it isn't the js file that's 403-ing, but the actual font file itself.

**Comment by grafmark59** [comment]
Alright so I solved this.
While the project was being hosted on a project domain (www.mywebsite.com/project), I saw deep in the network calls that the request itself was coming from the regular domain (www.mywebsite.com). So I had to adjust that in the listed domains.

Thanks for your help @KyleAMathews
