### ISSUE TITLE
gatsby-plugin-image beta + gatsby-source-contentful: cannot use "breakpoints" argument in gatsbyImageData resolver

### ISSUE THREAD

**Issue by nonAlgebraic** [gatsbyjs/gatsby#29404]
## Description

When using `gatsby-source-contentful` together with the new `gatsby-plugin-image` beta, if attempting to use the "`breakpoints`" argument in the `gatsbyImageData` GraphQL field resolver, an "`unkown argument "breakpoints"`" GraphQL error is thrown.

### Steps to reproduce

1. Clone this minimal reproduction: https://github.com/nonAlgebraic/gatsby-plugin-image-contentful-breakpoints-repro
2. Run `yarn install`
3. Set the Contentful `accessToken` and `spaceId` properties in the `gatsby-source-contentful` plugin config object in `gatsby-config.js` (ensure the Contentful space you're connecting to has at least one image asset)
4. Run `yarn build` or `yarn develop`

### Expected result

A build/serve or develop spin-up is successful, and the resulting root page on the site displays a Contentful image.

### Actual result

There is a GraphQL error thrown:
```bash
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown argument "breakpoints" on field "gatsbyImageData" of type "ContentfulAsset".
```

Removing the "`breakpoints`" argument from the field resolver makes the query succeed and the image is visible. Further, the default set of breakpoints ([as documented in the `gatsby-plugin-image` docs](https://gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image)) does seem to take effect, as can be observed in the `srcset` of the generated responsive image on the built page.

### Environment

```
  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.0 - /var/folders/s4/vdtxk6m16bq6yymsmcxpp8k94ldqbp/T/yarn--1612831828138-0.8047906766494342/node
    Yarn: 1.22.4 - /var/folders/s4/vdtxk6m16bq6yymsmcxpp8k94ldqbp/T/yarn--1612831828138-0.8047906766494342/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Languages:
    Python: 3.7.7 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 88.0.4324.146
    Edge: 88.0.705.63
    Firefox: 84.0.1
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.32.3 => 2.32.3 
    gatsby-plugin-image: ^0.7.1 => 0.7.1 
    gatsby-plugin-sharp: ^2.14.1 => 2.14.1 
    gatsby-source-contentful: ^4.6.1 => 4.6.1 
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0 
```

**Comment by LekoArts** [comment]
Hi!
Please use the discussion for feedback/bug reports. Thanks!

https://github.com/gatsbyjs/gatsby/discussions/27950

**Comment by nonAlgebraic** [comment]
@LekoArts  my apologies, will do!
