### ISSUE TITLE
mobx in gatsby

### ISSUE THREAD

**Issue by wedelgaard** [gatsbyjs/gatsby#2940]
Is it possible to use mobx with gatsby without using client side routing? I've taken a look at [https://github.com/Shaid/gatsby-example-mobx](url) but it uses react-router client side routing. I assume those routes won't be picked up by gatsby and created as static html files?

At the moment ive tried to wrap my layouts/index.js in `<Provider>` from mobx-react, and use `@inject` in pages/index.js but it won't work.

**Comment by TomiTakussaari** [comment]
This works for me:

```javascript
#gatsby-ssr.js

import { Provider, useStaticRendering } from "mobx-react";
import { renderToString } from "react-dom/server";

exports.replaceRenderer = ({ bodyComponent, replaceBodyHTMLString }) => {
    useStaticRendering(true);

    const ProviderBody = () => (
        <Provider Store={Store}>
                {bodyComponent}
        </Provider>
    );

    replaceBodyHTMLString(renderToString(<ProviderBody />));
};

```

```javascript
# gatsby-browser.js

import { Router } from "react-router-dom";
import { Provider } from "mobx-react";


exports.replaceRouterComponent = ({ history }) => {
    return ({ children }) => (
        <Provider Store={MyStore}>
            <StyleRoot>
                <Router history={history}>{children}</Router>
            </StyleRoot>
        </Provider>
    );
};
```

```javascript
#component.js

@inject("Store")
@observer
@Radium
export default class MyComponent extends Component {
...
}


```

**Comment by wedelgaard** [comment]
@TomiTakussaari thanks. Interesting approach. I'll have a look at it 👍

**Comment by ApprenticeGC** [comment]
@TomiTakussaari  Following your approach, it is working for development build. However, whenever I use `gatsby build` to generate production build. I always get error like

```
WebpackError: MobX injector: Store 'store' is not available! Make sure it is provided by some Provider
```

How do you solve this issue?

**Comment by Cacivy** [comment]
@TomiTakussaari when i run build, throw error " MobX injector: Store 'store' is not available! Make sure it is provided by some Provider"

**Comment by TomiTakussaari** [comment]
Do you have example code ?

I migrated my mobx-using-gatsby project to Next.js, because I needed dynamic pages, but I think this approach should still work with Gatsby..

Perhaps there should be "using-mobx" example in Gatsby, let's see if i'll find time and motivation for it

**Comment by Cacivy** [comment]
I think the code of gatsby-ssr is Useless,because `gatsby develop` is ok,and `gatsby build` is not work.
at last, I move `Provider ` to `layouts/index.js`

**Comment by rongierlach** [comment]
@TomiTakussaari prop variable `MyStore` is note in scope in your `gatsby-browser.js`.

Mind correcting the snippet for reference? 😁

**Comment by TomiTakussaari** [comment]
@rongierlach Yeah, I left defining Store out previously for some reason. Added it there now.
Did not test it though, so there might be typos etc.

I'll try to find time to create PR with mobx example later.

**Comment by TomiTakussaari** [comment]
@Cacivy I created my Mobx implementation by following [Gatsby's Redux example](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redux).

You need both gatsby-ssr & gatsby-browser.js for it work in build, develop & actual browser.

Atleast that's what I found out when creating it originally, have'nt tested if Gatsbys ways have changed since that.

**Comment by timmyers** [comment]
I am having the same issue.  Works fine for development, but the build fails, saying my store is not passed provided despite the `replaceRouterComponent` implementation.

**Comment by timmyers** [comment]
I think (for me at least), this is occurring due to also using `gatsby-plugin-styled-components`, which uses the `replaceRouterComponent` API as well.  According to https://www.gatsbyjs.org/docs/ssr-apis/, only one plugin can use this API.

I worked around this by removing the styled components plugin, and rolling its implementation into my own custom `gatsby-ssr.js`

```javascript
import * as React from 'react';
import { Provider, useStaticRendering } from 'mobx-react';
import { renderToString } from 'react-dom/server';
import { ServerStyleSheet, StyleSheetManager } from 'styled-components';
import { BreweryStore } from 'Stores/BreweryStore';

exports.replaceRenderer = ({
  bodyComponent,
  replaceBodyHTMLString,
  setHeadComponents,
}) => {
  useStaticRendering(true);

  const sheet = new ServerStyleSheet()

  const app = (
    <StyleSheetManager sheet={sheet.instance}>
      <Provider BreweryStore={BreweryStore}>
        {bodyComponent}
      </Provider>
    </StyleSheetManager>
  )

  const body = renderToString(app)

  replaceBodyHTMLString(body)
  setHeadComponents([sheet.getStyleElement()])
};
```

**Comment by ksaitor** [comment]
Ok. Fixed it by moving `useStaticRendering(true)` outside of `replaceRenderer` function, in `gatsby-ssr.js`

```jsx
import React from 'react'
import { Provider, useStaticRendering } from 'mobx-react'
import { renderToString } from 'react-dom/server'
import stores from './src/stores'

useStaticRendering(true)

exports.replaceRenderer = ({ bodyComponent, replaceBodyHTMLString }) => {
  const ProviderBody = () => (
    <Provider {...stores}>{bodyComponent}</Provider>
  )
  replaceBodyHTMLString(renderToString(<ProviderBody/>))
}

```

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by jonniebigodes** [comment]
@KyleAMathews and to whom it may concern. i saw this issue being bounced around a bit so i took a crack at it. Grabbed the example from redux and implemented it using mobx i have a working example in [here](https://github.com/jonniebigodes/gatsby-example-mobx) . If you guys want it add that to the examples. Thanks in advance
