### ISSUE TITLE
NPM 7 sharp compile issue

### ISSUE THREAD

**Issue by theskillwithin** [gatsbyjs/gatsby#29419]
After upgrading to npm 7 (nvm install-latest-npm),  I do an `npm i` (to update lock version) and then upon doing `npm ci` I get problem with image sharp compile.

node v14.15.4. npm 7.5.3

https://gist.github.com/theskillwithin/8811fc0085c13cb4b62ceb3354820f2d#file-foo-log-L4766

I noticed very similar issue here but deleting ~/.npm folder does not fix
https://github.com/gatsbyjs/gatsby/issues/21929 

i also tried `npm rebuild sharp` hoping that would be a lucky guess to fix but does not

**Comment by KyleAMathews** [comment]
Did you try deleting both the lock file and node_modules and then
reinstalling?

The sharp bit also suggests you might have multiple versions of Sharp
installed which it doesn't like.

**Comment by theskillwithin** [comment]
thank you @KyleAMathews I think the package-lock may have been the issue.
after deleting that tho I get a new error now.  I think maybe npm 7 stricter on peer dependencies so it doesn't like that im using react 17 now.  i tried npm i --force but still got error

```
➜  ps git:(master) ✗ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ps@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.4.2" from gatsby@2.30.2
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"2.30.2" from the root project
npm ERR!   peer gatsby@"*" from @sentry/gatsby@6.1.0
npm ERR!   node_modules/@sentry/gatsby
npm ERR!     @sentry/gatsby@"^6.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/austinpeterson/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/austinpeterson/.npm/_logs/2021-02-10T00_39_07_406Z-debug.log
```

**Comment by KyleAMathews** [comment]
what does running `npm i --legacy-peer-deps` get you?
--
Kyle Mathews

Blog: *http://bricolage.io <http://bricolage.io>*
Twitter: http://twitter.com/kylemathews

**Comment by theskillwithin** [comment]
Yes that works.  I believe this might be the problem: https://github.com/staylor/react-helmet-async/pull/107
