### ISSUE TITLE
[gatsby-transformer-react-docgen] Does not support `text/jsx` files

### ISSUE THREAD

**Issue by danoc** [gatsbyjs/gatsby#2941]
The react-docgen transformer doesn't appear to work on `.jsx` files.

I believe the issue is with this this line:
https://github.com/gatsbyjs/gatsby/blob/e6e8d565c6376f63683a1c97b3dada15a78c589d/packages/gatsby-transformer-react-docgen/src/on-node-create.js#L72

It should be changed to:
```js
node.internal.mediaType !== `application/javascript` && node.internal.mediaType !== `text/jsx`
```

I can make the change and update tests if you'd like!

**Comment by danoc** [comment]
Hey @KyleAMathews, I'd love to take a stab at this and submit a PR if the proposal sounds good to you.

**Comment by jquense** [comment]
Go  for it 👍

**Comment by KyleAMathews** [comment]
👍 sounds great!
