### ISSUE TITLE
Links to homepage still point to WP host after node processing

### ISSUE THREAD

**Issue by karen-sarkisyan** [gatsbyjs/gatsby#29417]
Hi 👋

I’ve found that urls in links to homepage are not replaced by relative paths on GraphQL node creation. They are still pointing to WP host and not the Gatsby frontend host.

Here's an example of how links are transformed (I'll provide endpoint and details at the bottom): 
![gql-gatsby-links](https://user-images.githubusercontent.com/18420141/105825752-00228d00-5fd1-11eb-9c9c-c832a9429d8b.jpg)

On the image: link to `https://wordpress-for-fun.000webhostapp.com/about` becomes `/about`, but `https://wordpress-for-fun.000webhostapp.com` stays the same.

## Possible fix

As I can see, `replaceNodeHtmlLinks()` [here in process-node.js](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/2ef17722a5eab474d7fe127888589e3d7b844bb2/plugin/src/steps/source-nodes/create-nodes/process-node.js#L797-L802) is responsible for checking and replacing links with relative paths in node strings. This RegExp looks for a match:

`["']${wpUrl}(?!/wp-content|/wp-admin|/wp-includes)(/[^'"]+)["']`

It assumes that the URL should have a path with **1 or more characters** after `/`, which is what `+` stands for. So homepage path does not match.

I changed `+` to `*` to indicate that there can be **0 or more characters**, like this:

`["']${wpUrl}(?!/wp-content|/wp-admin|/wp-includes)(/[^'"]*)["']`

and ran `gatsby develop` after clearing cache. It seems to have fixed the issue on my website (on a much bigger website, not this example) without any negative side effects. I've also ran tests for the plugin in the repo and they pass.

I wanted to make a PR, but still I might have missed some downstream effects that I'm not aware of. Please let me know if my fix is OK. 🙂

## Steps to reproduce reduced case
Run `gatsby develop` with this endpoint as source: https://wordpress-for-fun.000webhostapp.com/graphql

Dependencies:
```json
"gatsby": "^2.30.3",
"gatsby-source-wordpress-experimental": "^7.0.3",
"react": "^16.14.0",
"react-dom": "^16.14.0"
```

Go to GraphiQL playground on Gatsby’s side and query all page nodes with contents.
```graphql
query {
  allWpPage {
    nodes {
      content
      title
    }
  }
}
```
### Desired result
All links in page content are replaced with relative paths. 

### Actual result
All links _except for links to homepage_ are replaced with relative paths.

### Proposed fix
In `steps/source-nodes/create-nodes/process-node.js` change line 798:
```diff
- `["']${wpUrl}(?!/wp-content|/wp-admin|/wp-includes)(/[^'"]+)["']`
+ `["']${wpUrl}(?!/wp-content|/wp-admin|/wp-includes)(/[^'"]*)["']`
```

**Comment by karen-sarkisyan** [comment]
Hey Tyler @TylerBarnes !
Mind if I make a PR for the issue? If not, please let me know if there's something I should know besides the contributing guidelines in the docs. 🙂

**Comment by TylerBarnes** [comment]
@karen-sarkisyan please do :) that'd be much appreciated! The contributing docs should be enough to get going but let me know if anything doesn't work.

**Comment by karen-sarkisyan** [comment]
Dear bot, please don't close it just yet!

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
