### ISSUE TITLE
gatsby-plugin-netlify-cms Build times

### ISSUE THREAD

**Issue by zslabs** [gatsbyjs/gatsby#29421]
## Description

👋 Following up on a few other issues I read through:

* https://github.com/gatsbyjs/gatsby/issues/18245
* https://github.com/gatsbyjs/gatsby/issues/21900
* https://github.com/gatsbyjs/gatsby/issues/27891

Builds for our site have been pretty long and after debugging, have a few build logs to share:

**gatsby-plugin-netlify-cms NO CACHE**

```
[1] success open and validate gatsby-configs - 0.280s
success load plugins - 1.031s
success onPreInit - 0.049s
success initialize cache - 0.005s
success copy gatsby files - 0.045s
success onPreBootstrap - 0.020s
success createSchemaCustomization - 0.014s
success Checking for changed pages - 0.000s
success source and transform nodes - 3.204s
success building schema - 0.698s
info Total nodes: 2275, SitePage nodes: 437 (use --verbose for breakdown)
success createPages - 62.558s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.290s
success update schema - 0.209s
success onPreExtractQueries - 0.000s
success extract queries from components - 1.163s
success write out redirect data - 0.001s
success Build manifest and related icons - 0.053s
success onPostBootstrap - 0.056s
info bootstrap finished - 72.025s
success run static queries - 0.266s - 18/18 67.67/s
success run page queries - 21.275s - 485/485 22.80/s
success write out requires - 0.009s
success Building production JavaScript and CSS bundles - 126.409s
success Rewriting compilation hashes - 0.003s
success Building HTML renderer - 54.976s
success Building static HTML for pages - 4.940s - 485/485 98.17/s
success Delete previous page data - 0.000s
😢 Algolia search builds are enabled only for production builds
success onPostBuild - 17.007s
info Done building in 298.613864993 sec
```

**Removed plugin NO CACHE**

```
[1] success open and validate gatsby-configs - 0.326s
success load plugins - 1.511s
success onPreInit - 0.051s
success initialize cache - 0.004s
success copy gatsby files - 0.089s
success onPreBootstrap - 0.020s
success createSchemaCustomization - 0.006s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.921s
success building schema - 0.846s
info Total nodes: 2275, SitePage nodes: 437 (use --verbose for breakdown)
success createPages - 6.435s
success Checking for changed pages - 0.000s
success createPagesStatefully - 0.344s
success Cleaning up stale page-data - 0.010s
success update schema - 0.195s
success onPreExtractQueries - 0.002s
success extract queries from components - 1.397s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.064s
success onPostBootstrap - 0.069s
info bootstrap finished - 15.926s
success write out requires - 0.006s
success Building production JavaScript and CSS bundles - 67.019s
success Building HTML renderer - 28.442s
success Building static HTML for pages - 0.001s - 0/0 0.00/s
success Delete previous page data - 0.001s
😢 Algolia search builds are enabled only for production builds
success onPostBuild - 5.165s
info Done building in 117.507162094 sec
```

That's a pretty dramatic difference, with cached results showing the same trend. My config for the plugin looks like the following:

```
{
  resolve: 'gatsby-plugin-netlify-cms',
  options: {
    modulePath: `${__dirname}/src/cms/cms.js`,
    manualInit: true,
  },
},
```

I've opened up the repo to a team member previously, but didn't get any feedback on the build times, so I'm happy to do so again if nothing stands out.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

Build times should be impacted THIS much.

### Actual result

Build times (and saving CMS files during development) are extremely slow.

### Environment

```

  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 3.0.0 - /usr/local/bin/fish
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.npm-packages/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.146
    Edge: 88.0.705.63
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    gatsby: 2.32.2 => 2.32.2 
    gatsby-plugin-compile-es6-packages: 2.1.0 => 2.1.0 
    gatsby-plugin-emotion: 5.4.0 => 5.4.0 
    gatsby-plugin-feed: 2.13.0 => 2.13.0 
    gatsby-plugin-google-tagmanager: 2.11.0 => 2.11.0 
    gatsby-plugin-launchdarkly: 0.3.2 => 0.3.2 
    gatsby-plugin-lodash: 3.10.0 => 3.10.0 
    gatsby-plugin-manifest: 2.12.0 => 2.12.0 
    gatsby-plugin-mdx: 1.10.0 => 1.10.0 
    gatsby-plugin-mdx-embed: 0.0.17 => 0.0.17 
    gatsby-plugin-mdx-frontmatter: 0.0.2 => 0.0.2 
    gatsby-plugin-netlify: 2.11.0 => 2.11.0 
    gatsby-plugin-netlify-cms: 4.10.0 => 4.10.0 
    gatsby-plugin-react-helmet: 3.10.0 => 3.10.0 
    gatsby-plugin-react-helmet-canonical-urls: 1.4.0 => 1.4.0 
    gatsby-plugin-segment-js: 3.6.0 => 3.6.0 
    gatsby-plugin-sitemap: 2.12.0 => 2.12.0 
    gatsby-plugin-svgr: 2.1.0 => 2.1.0 
    gatsby-plugin-webpack-bundle-analyser-v2: 1.1.20 => 1.1.20 
    gatsby-source-filesystem: 2.11.0 => 2.11.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.117
```

**Comment by zslabs** [comment]
Tagging @pvdz per https://github.com/gatsbyjs/gatsby/issues/3406#issuecomment-583878527

**Comment by pvdz** [comment]
@zslabs I'm sorry, I don't work there anymore. And while I'd love to help you, they burned the bridge pretty hard, so I'm not. Best of luck.

**Comment by zslabs** [comment]
@pvdz Understood. Really appreciate all the hard work you've done for this project.

@KyleAMathews @wardpeet Any suggestions on how who would be a good point of contact for performance-related questions moving forward? Ward, I noticed you had some contributions to the `gatsby-plugin-netlify-cms` configuration in the past in dealing with the built time issues.

**Comment by KyleAMathews** [comment]
I haven't worked on this plugin myself so can't speak to it too deeply.

But the comparison build is a good first step. Looking at the two, the plugin adds the extra time in `createPages` and the webpack steps. I'm not sure what it's doing to 10x the time to create pages. That seems extreme so probably that could be optimized. For webpack, my understanding is the plugin does its own webpack run to build the admin sections of the site so it's doubling at least the time spent handling js.

One suggestion (not sure how practical it is) is to only build the admin section of the site occasionally on a local machine and then check the compiled site into your repo. I suspect that for most builds the admin site isn't affected so you'd save a lot of time by not building it at all.

**Comment by zslabs** [comment]
Thanks for the reply. I do think that could be an option, but as an added item that I wanted to note -> when using `netlify-cms-proxy-server` and in development mode, `success Re-building development bundle - 57.404s` that's how long it takes for a save within any files imported into CMS takes to rebundle 😬

**Comment by KyleAMathews** [comment]
yikes — it sounds like it's not even using the dev server then but is doing full rebuilds each time 🤦

**Comment by zslabs** [comment]
FWIW, moving the CMS folder outside of `src/` dramatically helped the rebuild times. Not sure if this should be considered solved since most tutorials I've seen mention putting the initializer in `src/cms.js`, but definitely interesting. 

I did the same with Netlify functions -> `src/functions` to `functions` and saw the develop rebuild not triggered at all, since `netlify-cms-proxy-server` took over. Are there some Gatsby file-watchers we can tweak to avoid double/triple compilation?

**Comment by KyleAMathews** [comment]
This might be a Gatsby watcher thing or it could just be that the plugin just stops doing work when it can't find the initializer?

**Comment by erezrokah** [comment]
Hi all 👋 Erez from Netlify here. I can shed some light on what the plugin does and why it does it.
One of the main purposes of the plugin is to allow users to use the same components from their site inside the CMS preview pane.
The preview pane is the right pane of the CMS editor window. See example [here](https://cms-demo.netlify.com/#/collections/faq/entries/what-is-jam-stack):
![image](https://user-images.githubusercontent.com/26760571/108351669-7ee4a180-71ee-11eb-80dc-0ba166736d15.png)


This is done by:
1. Creating a `cms.js` file where you register your templates (see example [here](https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/cc946ea2e93473f43b57e0f8d5c95135cceb8984/src/cms/cms.js#L13)).
2. Telling the plugin about that file via `modulePath`

In turn what the plugin does is builds that file with the referenced preview template components and the CMS as a standalone React app.
This is done here https://github.com/gatsbyjs/gatsby/blob/3b4d32f0b2d6aef3193213252c3eb813cc2cbea9/packages/gatsby-plugin-netlify-cms/src/gatsby-node.js#L346 as a part of `onCreateWebpackConfig` since we need to use the user's Gatsby build configuration to know how to build those components. 

As for the matter at hand - to debug the performance issues I recommend:
1. Opening a public repo reproducing it (this is the fastest way to get the issue resolved). 
2. Trying to comment out specific preview templates to see which one is adding a lot of build time (if any).

Another completely different way to go about it is being able to import the CMS as a standard React component that lives under the Gatsby app (but that's another topic).

**Comment by mcdowellalex** [comment]
@SapneshNaik, in response to the equk blog post and removing netlify-cms-app, gatsby-plugin-netlify, and gatsby-plugin-netlify-cms. Of course this would improve the build times, but am I wrong in thinking this is just the same as removing the cms? So I guess if you don't want a cms, then sure, you should remove it. But if you need the cms, then that doesn't make much sense to me.
