### ISSUE TITLE
createRedirect issues with static files

### ISSUE THREAD

**Issue by mcdanielisaac** [gatsbyjs/gatsby#2942]
Gatsby version 1.9.110
node.js version 6.10.0
macOS version 10.13.1 (17B48)

I've created a [repository](https://github.com/mcdanielisaac/gatsby-redirects-static-files) showing my setup.

Essentially I am setting up a redirect from a static file's old location to its new location using createRedirect however this results in two different 404 errors, depending on how the [redirect is setup](https://github.com/mcdanielisaac/gatsby-redirects-static-files/blob/94f7ae17cd3893ccc15ff5c21f7941bb7867cd84/gatsby-node.js)

**Comment by KyleAMathews** [comment]
FYI, redirects don't work out of the box — you need to build integration between them and however you're hosting the files as redirects need to be handled by the host of the site e.g. gatsby-plugin-netlify has integration built in.
