### ISSUE TITLE
Better document trailing slash behaviour

### ISSUE THREAD

**Issue by decimoseptimo** [gatsbyjs/gatsby#29445]
We start off with the premise that default the behaviour in gatsby is for trailing slashes to be on.
Good read: https://zenofreact.com/why-the-trailing-slash-gatsby/ 

In an old proyect I just discovered that my canonical URLs were lacking the trailing slashes, because I didn't add them in the first place. Probably due to the official tutorials or sample code, doing the same.

Extrated from: https://github.com/gatsbyjs/gatsby/blob/master/examples/recipe-createPage/gatsby-node.js#L16
```js
    createPage({
      path: `/${dog.name}`
```
In this example that causes that, upon first load of that route, gatsby will actually remove the trailing slash (through the router), because that's how canonical URLs were set up. See: https://github.com/gatsbyjs/gatsby/issues/15317#issuecomment-519289284

The correct code would have been
```js
    createPage({
      path: `/${dog.name}/`
```

Many examples just grab the slug and use it as the path in createPage, not adding a trailing slash to it.
Either better document this in places like https://www.gatsbyjs.com/docs/tutorial/part-seven/ or actually check for it within createPage.

**Comment by wardpeet** [comment]
Thank you for the issue, we'll be adding an extra config flag soon so gatsby knows what you prefer.
