### ISSUE TITLE
AWS Amplify Deployment issues. Error: The result of this StaticQuery could not be fetched

### ISSUE THREAD

**Issue by HeskethGD** [gatsbyjs/gatsby#29441]
## Description

When I run gatsby develop or gatsby serve locally the site works fine but when deploying to AWS Amplify the images do not load if I use graphQL. All I get is _"Error: The result of this StaticQuery could not be fetched. This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue"_. The images queried with GraphQL look blurry.  I have read a few answers but achieved nothing. Deleted node_modules and .cache, upgraded all packages and also tried changing cache_control headers in AWS as described [here](https://www.gatsbyjs.com/docs/caching/#page-data)

### Steps to reproduce

Here is a link to the faulty [site]( https://fixgraphql.d1s9huzadov3vh.amplifyapp.com)

### Expected result

The images should load as they do locally

### Actual result

Images don't load

### Environment

System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
  npmPackages:
    gatsby: ^2.32.3 => 2.32.3 
    gatsby-image: ^2.11.0 => 2.11.0 
    gatsby-plugin-gdpr-cookies: ^1.0.12 => 1.0.12 
    gatsby-plugin-manifest: ^2.12.0 => 2.12.0 
    gatsby-plugin-offline: ^3.10.0 => 3.10.0 
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5 
    gatsby-plugin-sharp: ^2.14.1 => 2.14.1 
    gatsby-plugin-sitemap: ^2.12.0 => 2.12.0 
    gatsby-remark-images: ^3.11.0 => 3.11.0 
    gatsby-source-filesystem: ^2.11.0 => 2.11.0 
    gatsby-transformer-remark: ^2.16.0 => 2.16.0 
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.113

**Comment by ascorbic** [comment]
Hi
Sorry to hear you're running into an issue. I've looked at the site, and it does look like the component is there in the generated HTML, but it disappears in hydration. To help more I'm goign to need a way of reproducing the issue. It would be really helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by HeskethGD** [comment]
Thanks @ascorbic I think this is resolved now. I stripped back the landing page so it just loaded a single image with GraphQL and that seemed to work when deployed. Then when I started to add the other content back in it seemed to be OK. Not sure exactly why this helped but it seems OK. Thanks for looking at it.

**Comment by ascorbic** [comment]
Great! Thanks for the update
