### ISSUE TITLE
Layout not working for pages created from data

### ISSUE THREAD

**Issue by kildareflare** [gatsbyjs/gatsby#2946]
In `gatsby-node`  I create pages from some data returned from prismic.
I am assigning these pages a different layout - `article-layout` which exists at `src/layouts/article-layout.js`.
But when I navigate to that page, the layout is not used. In fact, **no** layout is used.
I've also tried both setting layout to  `index`, and removing the the layout property to see if the default layout would be used, but it is not.

If I look in `.cache/layouts` I can see two files:
* index
* article-layout

And in `.cache\json` I can see
* layout-index
* layout-article-layout

And these both have the data I would expect.

Here is my gatsby-node
```
exports.createPages = ({ graphql, boundActionCreators }) => {
    const { createPage } = boundActionCreators

    return new Promise((resolve, reject) => {
      const articleTemplate = path.resolve(`src/templates/article.js`)

      resolve(
        graphql(
          `
        {
          articles: allPrismicDocument(filter: {type: {eq: "article"}}) {
            edges {
                node {
                  fields {
                       slug
                  }
                  type
                }
              }
          }
        }
      `
        ).then(result => {
          if (result.errors) {
            reject(result.errors)
          }

          // Create pages for each article.
          result.data.articles.edges.forEach(({ node }) => {

            if(node.type === 'article') {
            console.log(`create page for ${node.fields.slug}`);
            createPage({
              path: node.fields.slug,
              component: articleTemplate,
              layout: `article-layout`,
              context: {
                slug: node.fields.slug
              }
            })
        }
          })
          resolve()
        })
      )
    })
  }
```

**onCreatePage**
As a workaround I also tried setting the layout using  `onCreatePage` but this is never called for pages created from data, it is only called for `index` and `dev-404`.

**What** am i doing wrong?

**Comment by kildareflare** [comment]
Any pointers for this @KyleAMathews? It's the last thing I need to sort before I can go live.
After that I can start work on the responsive remote images and start contributing :0)

**Comment by KyleAMathews** [comment]
I'm not sure, could you build a very small site reproducing this?

**Comment by rudasn** [comment]
Having the same issue here..

Not sure if this may be the cause, but in `build/sync-requires.js` the `exports.layouts` object may contain the same key multiple times.. In my case:

```
exports.layouts = {
  "component---src-layouts-index-js": preferDefault(require("<path here>/website/.cache/layouts/index.js")),
  "component---src-layouts-index-js": preferDefault(require("<path here>/website/.cache/layouts/i18nLayout-en.js")),
  "component---src-layouts-index-js": preferDefault(require("<path here>/website/.cache/layouts/i18nLayout-el.js"))
}
```

**Comment by kildareflare** [comment]
Trying to create a new gatsby site so I can reproduce this in a small site.

```gatsby new layout-test```

installation hangs after this message
>info Creating new site from git: git://github.com/gatsbyjs/gatsby-starter-default.git

I've tried updating gatsby to latest (1.1.20) it was (1.1.11) and same error.

No directory or any files created.

**Comment by kildareflare** [comment]
OK, created a small repo from scratch and layouts worked.
Was in process of porting existing repo over to working one, when I realised that I layouts were working all along. I was just being a massive numpty. In short my shared code was still on the index, not on the layout. Cringe, blush.

Apologies for the time wasting.

**Comment by KyleAMathews** [comment]
Oh good 🤗 glad you got it working!

Weird about `gatsby new`… what version of gatsby-cli do you have installed?

@rudasn you might have a separate issue — could you try building a small reproduction site too that I could look at?

**Comment by rudasn** [comment]
@KyleAMathews I opened a new issue for this https://github.com/gatsbyjs/gatsby/issues/2957

Check the repo here: https://github.com/gatsbyjs/gatsby/issues/2957

**Comment by kildareflare** [comment]
@KyleAMathews I was on 1.1.11 and updated to 1.1.20, but it made no difference. Just tried `gatsby new layout-test` again in case it was gremlins on my windows - but still no dice. I'll try again on next update.

**Comment by kildareflare** [comment]
Open a new issue for gatsby new issue.
Closing as original issue resolved.
