### ISSUE TITLE
[FYI] Resource interpreted as Stylesheet but transferred with MIME type text/html

### ISSUE THREAD

**Issue by kildareflare** [gatsbyjs/gatsby#2947]
Putting this here in case anybody else comes across this.

I was getting this warning on my development server 
> Resource interpreted as Stylesheet but transferred with MIME type text/html

and this error on my production site
> Failed to load resource: the server responded with a status of 404 () / [object%20Object]

The solution was to remove ` rel="stylesheet"` from my stylesheet link

i.e. from this

```
  ///'layouts/index.js'
  import global from  '../assets/css/global.css';
 <link rel="stylesheet" type="text/css" href={global}/>
```
to this
```
   ///'layouts/index.js'
   import global from  '../assets/css/global.css';
   <link type="text/css" href={global}/>
```

**Comment by KyleAMathews** [comment]
Curious what the link is for? Gatsby automatically includes your css for you e.g. the default starter https://github.com/gatsbyjs/gatsby-starter-default/blob/master/src/layouts/index.js

Are you trying to do something special?

**Comment by kildareflare** [comment]
It's just a global stylesheet, but I did not realise that would work.
Updated and now it's simply this, as you suggested. :0)

``
import '../assets/css/global.css';
```

**Comment by kildareflare** [comment]
Issue resolved.
