### ISSUE TITLE
No type attribute in source element of gatsby-image created

### ISSUE THREAD

**Issue by MaVo289** [gatsbyjs/gatsby#29487]
## Description

Gatsby image does not generate the type attribute two the second source tag while using GatsbyImageSharpFluid_withWebp fragment. **At the bottom of this issue you find a suggestion to fix this problem**. This would then also fix #25740, which is still unresolved. 

### Steps to reproduce

Steps to reproduce
Go to the default starter demo. Check the code of generated image on main page:

```
<picture>
<source srcset="/static/6d91c86c0fde632ba4cd01062fd9ccfa/5db04/gatsby-astronaut.png 75w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/6d161/gatsby-astronaut.png 150w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/630fb/gatsby-astronaut.png 300w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/62b1f/gatsby-astronaut.png 450w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/2a4de/gatsby-astronaut.png 600w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/ee604/gatsby-astronaut.png 800w" sizes="(max-width: 300px) 100vw, 300px">
<img sizes="(max-width: 300px) 100vw, 300px" srcset="/static/6d91c86c0fde632ba4cd01062fd9ccfa/5db04/gatsby-astronaut.png 75w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/6d161/gatsby-astronaut.png 150w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/630fb/gatsby-astronaut.png 300w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/62b1f/gatsby-astronaut.png 450w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/2a4de/gatsby-astronaut.png 600w,
/static/6d91c86c0fde632ba4cd01062fd9ccfa/ee604/gatsby-astronaut.png 800w" src="/static/6d91c86c0fde632ba4cd01062fd9ccfa/630fb/gatsby-astronaut.png" alt="" loading="lazy" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; object-fit: cover; object-position: center center; opacity: 1; transition: opacity 500ms ease 0s;">
</picture>
```
Source tag does not have media or type attributes
### Expected result

According to specification:

When a source element has a following sibling source element or img element with a srcset attribute specified, it must have at least one of the following:

A media attribute specified with a value that, after stripping leading and trailing ASCII whitespace, is not the empty string and is not an ASCII case-insensitive match for the string "all".
A type attribute specified.

### Actual result

Html validator marks this behavior as an error:

A source element that has a following sibling source element or img element with a srcset attribute must have a media attribute and/or type attribute.

The reason for this behaviour is in the gatsby-image index.js file: 
The following check only sets the type attribute if isWebp is true, otherwise an empty string is set. In case an empty string is set, the html validator complains about the missing type attribute: 

`var typeAttr = isWebp ? "type='image/webp' " : "";`

**A simple fix could be to set the typeAttr to the correct image format instead of an empty string (e.g. 'image/png', 'image/jpg' etc.)**

### Environment

Any environment

**Comment by ascorbic** [comment]
Hi. This is fixed in [the new image plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-image/), so the best solution is to upgrade. I'm going to close this, as we're not going to be making these sort of fixes to this plugin now.

**Comment by MaVo289** [comment]
Hi, hmm ok. However, I figured out how to fix at least the HTML-Errors that are generated due to gatsby-image: 
A simple fix is to set explicitly the media attribute, which in turn fixes the HTML-Errors. Here is a small example: 

`<Img style={imageStyle} fluid={{...image.childImageSharp.fluid,media:"(max-width: 240px)"}} alt={alt} />`

Could of use for some users I guess :-)

**Comment by Viktor19931** [comment]
I faced this issue in gatsby-plugin-image
<img width="1568" alt="Screenshot 2024-03-10 at 23 05 56" src="https://github.com/gatsbyjs/gatsby/assets/29923015/493b9ad6-4ccf-4ce3-a44b-47ec8cfd9827">
