### ISSUE TITLE
Create Gitter.im / Slack community

### ISSUE THREAD

**Issue by barraq** [gatsbyjs/gatsby#2949]
It would be really great to create a dedicated `GatsbyJS` community e.g. on https://slack.com or https://discordapp.com to allow better Q/A between the community. What do you think @KyleAMathews @rgbkrk?

The current setup, with Discord, restricts Gatsby to be in one thread which makes it difficult to address several topics or regroup community around shared topics in dedicated channels. As mentioned below it would be preferable to keep only one source (meaning one platform).

If Discord is preferred over Slack, would it be possible to create a dedicated Gatsby organisation?

**Note**: this post is being updated based on discussions below.
**Update**: I removed Gitter as it forces also to have a single channel.
**Update**: Seems that there is such community here https://spectrum.chat/gatsby-js/general

**Comment by pungggi** [comment]
or Slack.. but something more popular than Reactiflux Chat..

**Comment by barraq** [comment]
Slack would be great indeed, as one can create different channels which is simpler to use that the mono channel in Gitter.

**Comment by jquense** [comment]
For a general support and discussion platform for a OSS, Slack is functionally the same as discord but harder to handle anon signups and missing some nice features like code syntax. More generally tho the folks contributing to gatsby already hang out on the discord channel, so having another place would more than like just result in worse attention and support since we'd have to split focus

**Comment by barraq** [comment]
@jquense yup I agree that having various sources of discussions would make things impossible to manage. Yet, I looked at Discord and it seems that `gatsby` is just one channel in a more generic organisation (namely reactiflux) which makes it super hard to discuss different topics (e.g. `#getting-started`, `#gatsbyjs-engine`, etc.) Maybe I am using it wrong... maybe then the solution would be to have Discord with a dedicated Gatsby organisation allowing specialised channels ;)

**Comment by fabe** [comment]
There's an official channel on Spectrum → https://spectrum.chat/gatsby-js

**Comment by barraq** [comment]
Ok thanks @fabe, good to know
