### ISSUE TITLE
ERROR 11321 PLUGIN

### ISSUE THREAD

**Issue by tkim** [gatsbyjs/gatsby#29501]
Hello, 
I started to get yarn build error after setting up the netlify backend to host. I searched for similar error and noticed the following reference:-
 
This sounds like is a duplicate of #20698 

Likely happening because Netlify has global `libvips` installed that is incompatible with a local sharp version. The suggested solution is to re-install dependencies from scratch using `SHARP_IGNORE_GLOBAL_LIBVIPS=true`:

```
rm -rf node_modules &&
SHARP_IGNORE_GLOBAL_LIBVIPS=true yarn
```

I am currently running on windows and I saw that globally-installed libvips is unsupported in Windows.

https://sharp.pixelplumbing.com/install#custom-libvips

what is the proper work around this issue when using windows?

System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.6.6
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.68)
  npmPackages:
    gatsby: ^2.13.41 => 2.32.3
    gatsby-plugin-google-analytics: ^2.1.6 => 2.11.0
    gatsby-plugin-manifest: ^2.12.0 => 2.12.0
  npmGlobalPackages:
    gatsby-cli: 2.19.1

Error: 

Creating authors page

info Total nodes: 82, SitePage nodes: 5 (use --verbose for breakdown)
success createPages - 5.941s
success Checking for changed pages - 0.014s
success createPagesStatefully - 0.588s
success Cleaning up stale page-data - 0.059s
success update schema - 0.409s
success onPreExtractQueries - 0.005s
success extract queries from components - 2.103s
success write out redirect data - 0.032s
success Build manifest and related icons - 0.007s

 ERROR #11321  PLUGIN

"gatsby-plugin-manifest" threw an error while running the onPostBootstrap lifecycle:

Input file contains unsupported image format

  Error: Input file contains unsupported image format

not finished Generating image thumbnails - 9.470s
not finished onPostBootstrap - 0.369s

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by tkim** [comment]
Hello, thank you for the quick turn around. For some reason, when I deleted all the example pages on the theme and restarted the server all the issues and conflicts went away. All resolved. Please feel free to close this issue.

**Comment by tkim** [comment]
Hello,

Actually this is good to close. I basically removed the example pages from
the theme and restarted the gatsby server and all the errors went away.
Thank you for the quick response!

Terrence
