### ISSUE TITLE
Gatsby Cloud requires CSP script-src unsafe-eval to render preview

### ISSUE THREAD

**Issue by marcustisater** [gatsbyjs/gatsby#29516]
When running Gatsby 2.32.3 on Gatsby Cloud Preview the website will not render. In the console it says that it requires CSP script-src ['unsafe-eval'](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#sources).

```
<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline' ...." />
```

I am not sure if this is a bug, but I think it's worth looking into.

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' etc...

 at Object../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js 
```

Let me know if you need more details ✌️

**Comment by LekoArts** [comment]
Hi! For Gatsby Cloud questions please reach out here: https://www.gatsbyjs.com/support/
Thanks!

**Comment by marcustisater-kivra** [comment]
@LekoArts I did, and Kyle asked me to open an issue here when I asked on Discord.

**Comment by marcustisater** [comment]
@LekoArts I did, and Kyle asked me to open an issue here when I asked on Discord.

**Comment by LekoArts** [comment]
It's still a Gatsby Cloud issue, please use the form at the bottom of the page.

**Comment by marcustisater** [comment]
@LekoArts Thanks. I did, but there is no follow up more than to add `unsafe-eval` if I want to use it.
