### ISSUE TITLE
(Official?) gatsby-starter-default codesandbox.io fails on 'no space left on device'

### ISSUE THREAD

**Issue by therealgilles** [gatsbyjs/gatsby#29527]
## Description
The codesandbox at https://codesandbox.io/s/github/gatsbyjs/gatsby-starter-default fails with:

``` JS
error An unexpected error occurred: "ENOSPC: no space left on device, copyfile '/home/sandbox/.cache/yarn/v6/npm-@babel-helper-validator-option-7.12.11-d66cb8b7a3e7fe4c6962b32020a131ecf0847f4f-integrity/node_modules/@babel/helper-validator-option/package.json' -> '/sandbox/node_modules/@babel/helper-validator-option/package.json'".
```

### Steps to reproduce
Open the codesandbox.io link and wait for it to run (and fail).

### Expected result
Hoping it would work.

### Actual result
No space left on device error, plus other errors after that.

### Environment
https://codesandbox.io/s/github/gatsbyjs/gatsby-starter-default

**Comment by LekoArts** [comment]
Hi! Please reach out to codesandbox's support about this. Thanks!
