### ISSUE TITLE
"Loading the component for ${page.path} failed" after new build deployed

### ISSUE THREAD

**Issue by lsirivong** [gatsbyjs/gatsby#2954]
I've noticed the following scenario can happen:

1. Build & deploy gatsby site to S3 via sync (missing files get deleted from bucket)
2. Load site in browser
3. Edit some /page/name.js
4. Repeat step (1)
5. With same browser session from (2), navigating to the edited page via a link can fail, with the error in the console: `Loading the component for /page-3/ failed` from loader.js

Intuitively, I understand why this is happening - the new build has changed the resource for the edited page so the previous one is removed from the server upon sync.

Is it be possible for the loader to handle this scenario? Possibly by attempting a regular ol' http request of the path, causing the app to reload and refresh the pre-cached references?

**Comment by KyleAMathews** [comment]
>Is it be possible for the loader to handle this scenario? Possibly by attempting a regular ol' http request of the path, causing the app to reload and refresh the pre-cached references?

Yeah this. I've thought about this problem and that this could be a potential solution. One tricky problem though is the failed loading *could* result just a client going offline in which case if you reload the page then they'll go from reading something already in their browser to… nothing.

I think we should still auto-reload but we should ask browsers also if we're online (to browser that support this).

Oh hey, I found the issue where I discussed this https://github.com/gatsbyjs/gatsby/issues/1807

Are you interested in working on a PR for this? Would be a huge help!

**Comment by lsirivong** [comment]
Ah, definitely not used to thinking about the offline use case, that makes a lot of sense.

I think this is definitely something we're interested in addressing, so happy to contribute.

Your original issue looks like a helpful outline; the only part I'm not clear on is how you go about inspecting "the last 5/10 resource downloads." Is that part of gatsby internals or a browser API I'm unaware of?

**Comment by KyleAMathews** [comment]
Sweet!

I just meant that within loader track failures. If some downloads *are* succeeding while some are not, this means the user is definitely online just that they're fetching older versions of the site some which no longer exist so you should refresh.

**Comment by KyleAMathews** [comment]
On the other hand if *everything* fails then the user is probably offline and you should just gracefully quit.

**Comment by KyleAMathews** [comment]
*fail

**Comment by Chuloo** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues as many of them have already been resolved with the latest updates or explained in a previous issue.

Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) if you still experience this problem or a similar one! 👍
