### ISSUE TITLE
Add reporter.panic to empty catch in load-themes

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#29545]
In my case I did use a wrong version of Gatsby and I ve got an incorrect error about it

to replicate just change version to a wrong one in package.json of Gatsby and 
semver will throw out an error than the catch on 
https://github.com/gatsbyjs/gatsby/blob/a6be92eb80bb98c308310a0fb3c340dab8e104aa/packages/gatsby/src/bootstrap/load-themes/index.js#L40

do not output and do not stop the code.

as a result themeDir in 
https://github.com/gatsbyjs/gatsby/blob/a6be92eb80bb98c308310a0fb3c340dab8e104aa/packages/gatsby/src/bootstrap/load-themes/index.js#L44
is null

and send to the user an error not related

I think output the catch and stop the execution will be more relevant

**Comment by LekoArts** [comment]
Thanks for the report!

To fix this a `reporter.panic` should be used in this catch block (like in the block below) to throw an error about it.

**Comment by nategiraudeau** [comment]
@LekoArts can I work on this issue?
