### ISSUE TITLE
Links not working in IE11 production build

### ISSUE THREAD

**Issue by jim-moody** [gatsbyjs/gatsby#2955]
I see the following error in the console:

`Unable to get property 'push' of undefined or null reference`
`production-app.js (87,7)`

That line corresponds with the following line of code:
`window.___history.push(pathname)`

**Comment by KyleAMathews** [comment]
Just checking — you're on the latest Gatsby?

Does your problem look similar to previous IE11 discussions? https://github.com/gatsbyjs/gatsby/search?q=ie11&type=Issues&utf8=%E2%9C%93

**Comment by jim-moody** [comment]
Yes - v1.9.110
No - it seems like a different issue

It appears to be related to the `gatsby-plugin-catch-links` plugin because when I take that out, I don't get the error.

**Comment by jim-moody** [comment]
I'm closing this issue because I think another issue was actually causing this random error to show in the console.

I was using Array.find and String.includes without polyfill in IE and I guess it could have just happend to propagate itself on this particular line of code even though it wasn't the root cause.

I kind of assumed those would be available because of Babel, what am I missing about the babel config?

**Comment by KyleAMathews** [comment]
No we don't automatically polyfill old APIs. Perhaps we should? /cc @jquense thoughts?

**Comment by jim-moody** [comment]
I don't think it automatically needs polyfill as long as it is clear how to customize the build process to have babel do that.

Another example - I am trying to use `async` and `await` in a `gatsby-node.js` file but `gatsby develop` blows up.

If it was a standard vanilla project I would just throw in a .babelrc with the correct settings and configure webpack and be good to go. With gatsby, I am not sure how to actually set it up.

**Comment by KyleAMathews** [comment]
async/await only works in node 8 which I'm guessing is your problem.

**Comment by jim-moody** [comment]
Ah good call, sorry I forgot I had switched to an older version for another project
