### ISSUE TITLE
Creating multiple layouts from the same component does not work as expected

### ISSUE THREAD

**Issue by rudasn** [gatsbyjs/gatsby#2957]
```
Gatsby version: 1.1.20
Node version: v8.7.0
```

**Steps to reproduce** 

Clone the repo https://github.com/rudasn/gatsby-layout-test and run `npm run develop`. Open the development site on your browser (http://localhost:8000/) and observe the list of pages and their properties.

**Expected behaviour**

- The index page and all other pages not created via `gatsby-node.js` should be using the default `index` layout, but are instead using our custom layout (created from `gatsby-node.js`).

- Page One (http://localhost:8000/one) should be using the `layout-one` layout, but is instead using `layout-two`

- Page Two (http://localhost:8000/one) is using the correct `layout-two` layout, but even broken clocks are correct twice a day.

**Problem**

When layouts are created they are assigned a `componentChunkName` property which is derived from the layout's filesystem path. This property is used by pages to determine which layout a page should be using. When more than one layouts are created from the same layout component (eg. `src/layouts/index.js`) they all end up having the same  `componentChunkName` property.

This ends up breaking the module import system in a way that no errors are thrown:

**async-requires.js**

```js

exports.layouts = {
  "component---src-layouts-index-js": require("gatsby-module-loader?name=component---src-layouts-index-js!/Users/rudasn/Sites/gatsby-layout-test/.cache/layouts/index.js"),
  "component---src-layouts-index-js": require("gatsby-module-loader?name=component---src-layouts-index-js!/Users/rudasn/Sites/gatsby-layout-test/.cache/layouts/layout-one.js"),
  "component---src-layouts-index-js": require("gatsby-module-loader?name=component---src-layouts-index-js!/Users/rudasn/Sites/gatsby-layout-test/.cache/layouts/layout-two.js")
}
```
**sync-requires.js**

```js
exports.layouts = {
  "component---src-layouts-index-js": preferDefault(require("/Users/rudasn/Sites/gatsby-layout-test/.cache/layouts/index.js")),
  "component---src-layouts-index-js": preferDefault(require("/Users/rudasn/Sites/gatsby-layout-test/.cache/layouts/layout-one.js")),
  "component---src-layouts-index-js": preferDefault(require("/Users/rudasn/Sites/gatsby-layout-test/.cache/layouts/layout-two.js"))
}
```
`layouts` contains keys of the same name and so the last one wins: `layout-two`.

**Solution**

To be able to create multiple layouts from the same component we need to make sure that no more than one layout is created with the same `componentChunkName` property.

To do that we just need to update the redux action `createLayout` and make sure that the `componentChunkName` also considers the layouts `id` property, not just the `path`:

```js
exports.layouts = {
  "component---src-layouts-index-js": preferDefault(require("/Users/rudasn/Sites/gatsby-layout-test/.cache/layouts/index.js")),
  "component---src-layouts-layout-one-js": preferDefault(require("/Users/rudasn/Sites/gatsby-layout-test/.cache/layouts/layout-one.js")),
  "component---src-layouts-layout-two-js": preferDefault(require("/Users/rudasn/Sites/gatsby-layout-test/.cache/layouts/layout-two.js"))
}
```

---

**package.json** (from default gatsby starter)

```json
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^1.9.117",
    "gatsby-link": "^1.6.28",
    "gatsby-plugin-react-helmet": "^1.0.8"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"src/**/*.js\"",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.8.2"
  }
}
```

**gatsby-node.js**

```js
const path = require('path')

exports.createLayouts = ({ boundActionCreators }) => {
    const { createLayout } = boundActionCreators

    const component = path.resolve('src/layouts/index.js')
    const layouts = [ 'one', 'two' ].map(name => ({
        id: `layout-${ name }`,
        component,
        context: {
            name: `layout ${ name }`,
        }
    }))

    layouts.map(l => createLayout(l))
}

exports.createPages = ({ boundActionCreators }) => {
    const { createPage } = boundActionCreators

    const component = path.resolve('src/pages/index.js')
    const pages = [ 'one', 'two' ].map(name => ({
        id: `page-${ name }`,
        path: `/${ name }`,
        component,
        layout: `layout-${ name }`,
        context: {
            name: `page ${ name }`,
        }
    }))

    pages.map(p => createPage(p))

}
```

**Comment by yachaka** [comment]
#3039 fixes this!

**Comment by KyleAMathews** [comment]
It does!
