### ISSUE TITLE
[gatsby-source-wordpress] Preview for ACF flexible content not updating

### ISSUE THREAD

**Issue by MobyDigg** [gatsbyjs/gatsby#29570]
**Problem:**

This issue regards the gatsby-source-wordpress@^4.0.1 plugin.

The preview isn't updating for flexible content elements. 

My preview works for regular ACF fields or all other WordPress fields. The issue is, when I update a **flexible content layout**. Although the preview is produced and displays normally, it doesn't show the updated fields of the flexible content layout – just the old, published content.

**Testing**

- Testing was done locally with ngrok and verbose output, as suggested in the documentation. The raw remote node data shows the flexible content nodes but, as mentioned above, the old version. The node also shows a correct, updated date of modification. Besides the flexible content node, the preview works as wished. 
- Other fields are shown updated in the node (eg. page title or other simple ACF fields). Also the revisions show up in the WordPress backend. 
- After saving the page, then hitting the preview button, the preview shows the update. But not, when I only press "Preview Changes".

**Errors**

The following error is displayed in the terminal output:

```
error Error loading a result for the page query in "92-autosave-v1" / "92-autosave-v1". Query was not run and no cached result was found. ENOENT: no such file or directory, open '/Users/myname/dev/gatsby/website-name/public/page-data/92-autosave-v1/page-data.json'


  Error: ENOENT: no such file or directory, open '/Users/myname/dev/gatsby/website-name/public/page-data/92-autosave-v1/page-  data.json'
```

**What I tried**

- Conditional chaining in all respective files

- wp-config.php has no line such as ``define( 'WP_POST_REVISIONS', FALSE );``

- gatsby-node.js query for ``allWpContentNode`` has no filters and no sorting going on:

```
exports.createPages = async ({ actions, graphql, reporter }) => {
  const {
    data: {
      allWpContentNode: { nodes: contentNodes },
    },
  } = await graphql(/* GraphQL */ `
    query ALL_CONTENT_NODES {
      allWpContentNode {
        nodes {
          nodeType
          id
          status
          slug
          ... on WpCompetence {
            language {
              slug
            }
            contentType {
              node {
                name
              }
            }
          }
          ... on WpPage {
            language {
              slug
            }
            contentType {
              node {
                name
              }
            }
          }
          ... on WpPost {
            language {
              slug
            }
            contentType {
              node {
                name
              }
            }
          }
          ... on WpProject {
            language {
              slug
            }
            contentType {
              node {
                name
              }
            }
          }
          ... on WpJob {
            language {
              slug
            }
            contentType {
              node {
                name
              }
            }
          }
        }
      }
    }
  `);

  const templates = getTemplates();
  const contentTypeTemplateDirectory = `./src/templates/`;
  const contentTypeTemplates = templates.filter((path) =>
    path.includes(contentTypeTemplateDirectory)
  );

  const contentNodesFiltered = contentNodes.filter(item => item.nodeType !== "Employee" && item.nodeType !== "MediaItem")

  await Promise.all(
    contentNodesFiltered.map(async (node, i) => {
      const {
        id,
        slug,
        language,
        nodeType,
        contentType: {
          node: { name },
        },
      } = node;

      const templatePath = `${contentTypeTemplateDirectory}${nodeType}.jsx`;

      const contentTypeTemplate = contentTypeTemplates.find(
        (path) => path === templatePath
      );

      if (!contentTypeTemplate) {
        reporter.panic(
          `[using-gatsby-source-wordpress] No template found at ${templatePath}\nfor single ${nodeType} ${
            node.id
          } with path ${
            node.uri
          }\n\nAvailable templates:\n${contentTypeTemplates.join(`\n`)}`
        );
        reporter.log(``);
        dd(node);
        reporter.log(``);
      }

      let edgePath = "";

      if (slug === "home") {
        edgePath = localPath.createPath(localeDirectories, language.slug, []);
      } else if (name === "page") {
        edgePath = localPath.createPath(
          localeDirectories,
          language.slug,
          [],
          slug
        );
      } else {
        edgePath = localPath.createPath(
          localeDirectories,
          language.slug,
          [`${name}`],
          slug
        );
      }

      await actions.createPage({
        component: resolve(templatePath),
        path: edgePath,
        context: {
          id,
          slug,
          lang: language.slug,
          next: (contentNodes[i + 1] || {}).id,
          prev: (contentNodes[i - 1] || {}).id,
        },
      });
    })
  );
};
```

Page query reads as follows:

```
export const pageQuery = graphql`
  query pagePageQuery($id: String!, $lang: String!) {
    page: wpPage(id: { eq: $id }) {
      title
      databaseId
      flex {
        content {
          __typename
          ...PageHeroSectionFragment
          ...PageHeroSectionSliderFragment
          ...PageServicesTeaserSectionFragment
          ...PageBasicSliderSectionFragment
          ...PageTeaserSectionFragment
          ...PageProgressSliderSectionFragement
          ...PageRelatedProjectsSectionFragment
          ...PageRelatedStorySectionFragment
          ...PageTextItemsColumnsSectionFragment
          ...PageJobOverviewSectionFragment
          ...PageContactPersonsSectionFragment
          ...PageLocationSectionFragment
          ...PageInquirySectionFragment
          ...PageHeadlineSectionFragment
          ...PageTextSectionFragment
          ...PageTextAndImagesColumnSectionFragment
          ...PageProjectOverviewSectionFragment
          ...PageCompetenceSectionFragment
          ...PageTeamOverviewSectionFragment
          ...PageTimelineSliderSectionFragement
          ...PageNewsOverviewSectionFragment
          ...PageCurrentNewsTeaserSectionFragment
          ...PageFeaturedContentSectionFragment
          ...PageDynamicContentSectionFragment
          ...PageJobApplicationSectionFragment
        }
      }
    }
    relatedProjects: allWpProject(
      filter: {
        id: {ne: $id},
        language: {slug: {eq: $lang}},
        title: { ne: "DO NOT DELETE" },
      }
      ) {
      edges {
        ...
      }
    }
    relatedStories: allWpPost(
      filter: {
        id: {ne: $id},
        language: {slug: {eq: $lang}},
        title: { ne: "DO NOT DELETE" },
      }) {
      nodes {
        ...
      }
    }
    employeesDE: allWpEmployee (
      filter: {title: {nin: ["DO NOT DELETE", "Karriere"]}, language: {slug: {eq: "de"}}},
      sort: {order: DESC, fields: date}
    ) {
      edges {
        ...
      }
    }
    employeesEN: allWpEmployee (
      filter: {title: {nin: ["DO NOT DELETE", "Career"]}, language: {slug: {eq: "en"}}},
      sort: {order: DESC, fields: date}
    ) {
      edges {
        node {
          ...
        }
      }
    }
  }
`
```

**Setup**

- gatsby-source-wordpress 4.0.1,
- gatsby 2.25.3,
- WP Gatsby 1.0.1,
- WP GraphQL 1.1.3 and
- WordPress 5.6.1.

**Question**

Is there anything I should setup to make changes in flexible content types available in the preview? @TylerBarnes you are an expert on this, maybe you can help?

**Note**

Note

I did not know where to post this, so there is the same issue here: https://github.com/wp-graphql/wp-graphql-acf/issues/217

**Comment by TylerBarnes** [comment]
Hi @MobyDigg , thanks for the thorough explanation 👍 are you using Gutenberg? Gutenberg broke meta previews for all plugins (including ACF) for both decoupled WP and regular PHP WP.

**Comment by MobyDigg** [comment]
Hi @TylerBarnes, thanks for your reply. No I actually deactivated Gutenberg with the "Disable Gutenberg" plugin… Does this error I mentioned above give any clues what it might be?

**Comment by MobyDigg** [comment]
@TylerBarnes any other ideas, what this might be? How could I debug this further?

**Comment by jacksellwood** [comment]
Hi there @MobyDigg, we're working through a backlog of customer feedback and GitHub issues. We're currently hiring more folks for our squad to help triage these, but in the meantime @TylerBarnes is the only engineer maintaining this project. Please be a little patient with us while we work through these requests.
PS: if you're interested in applying to join our squad, we're hiring for a staff software engineer: https://grnh.se/0137fbc23us

**Comment by MobyDigg** [comment]
Hi @jacksellwood, thanks for the heads up.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
