### ISSUE TITLE
gatsby-plugin-offline appendScript not working

### ISSUE THREAD

**Issue by mbcod3** [gatsbyjs/gatsby#29598]
I have custom-sw-code.js file in src and in my gatsby-config.js 

  {
      resolve: `gatsby-plugin-offline`,
      options: {
        appendScript: require.resolve('src/custom-sw-code.js'),
      },
    },

Its just like in docs for extending service worker

https://www.gatsbyjs.com/plugins/gatsby-plugin-offline/

This throws  Cannot find module error on develop and build. 

I tried having file in root and static folder with require.resolve('custom-sw-code.js') but I get the same error.

If I do require.resolve('/custom-sw-code.js') having file in root folder or in src folder with require.resolve(`./src/custom-sw-code.js`), it doesnt throw error but the code is also not working. I tested it by adding this in the custom-sw-code.js file

setTimeout(() => {
  self.registration.showNotification("Hello, world!")
}, 7000)

But the notification doesnt show up which means the code in that file is not running.

I wanted to implement web share target for receiving image from other apps via mobile native share. I implemented share_target in manifest which works as my pwa app shows up as share target but the code in custom sw which has to add event listener for post request doesnt work. Nothing in custom sw script runs.

How do I add event listener to service worker i.e. extend it?

**Comment by Yixuan-Wang** [comment]
I suppose there are issues with our gatsby-plugin-offline [document](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-offline/README.md). The appended script **shouldn't be** a Node module, but some **plain code** directly appended after sw.js.

https://github.com/gatsbyjs/gatsby/blob/39f25b75661c13b9df8924b421b5e2dea3cf9070/packages/gatsby-plugin-offline/src/gatsby-node.js#L196-L204

But the document uses `require.resolve` to ensure the appended script being a node module.
```
plugins: [
  {
    resolve: `gatsby-plugin-offline`,
    options: {
      appendScript: require.resolve(`src/custom-sw-code.js`),
    },
  },
]
```
