### ISSUE TITLE
add link to netlify guide to gatsby

### ISSUE THREAD

**Issue by phlogisticfugu** [gatsbyjs/gatsby#296]
Netlify provides a nice hosting and continuous build/deploy solution for those who want to "just" make the website part of their site, and they made a nice guide to using gatsby with their service:

https://www.netlify.com/blog/2016/02/24/a-step-by-step-guide-gatsby-on-netlify

it is admittedly a paid service, but may be a nice alternative to include in options for deploying gatsby beyond github pages.

**Comment by KyleAMathews** [comment]
Thanks for the suggestion! Netlify is an awesome service. That blog post actually though already is in the Videos & Blogs section https://github.com/gatsbyjs/gatsby#videos-and-blogs
