### ISSUE TITLE
How the react component receives the data found by the graphql?

### ISSUE THREAD

**Issue by FourEyebrowXiake** [gatsbyjs/gatsby#2961]
for example :
```javascript
class BlogIndex extends React.Component {
...
}
export default BlogIndex;

export const pageQuery = graphql`...`
```
How data is sent to the 'BLogIndex'?

**Comment by rdela** [comment]
Hi did you check out https://www.gatsbyjs.org/docs/create-source-plugin/ already?

**Comment by KyleAMathews** [comment]
Gatsby has a runtime that loads in the data from queries and automatically passes it as props to the page components. You can see the code for this in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/component-renderer.js

**Comment by gnuletik** [comment]
Thanks @KyleAMathews !
Should this be added to the tutorial ?

**Comment by KyleAMathews** [comment]
Perhaps. This is somewhat advanced concept to explain so not probably helpful for the tutorial. But eventually we plan to write a page explaining how Gatsby works in general under the hood where this would be great.
