### ISSUE TITLE
Incorrect query example in part four of tutorial

### ISSUE THREAD

**Issue by anthlubic** [gatsbyjs/gatsby#29635]
## Summary

While looking into issue #29416, others mentioned that you can reproduce part of the issue by doing step four of the tutorial.  I did it and noticed an error, and it's because the query doesn't have a name.

## Steps to resolve this issue

The queries should have a name, like SiteTitleQuery.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by LekoArts** [comment]
Thanks for the issue and PR! But the name is not necessary :)

**Comment by anthlubic** [comment]
@LekoArts You're right, the query doesn't seem to need a name if you omit the query keyword.  If you specify query then it seems to be required.

This can be reproduced by following the Gatsby Tutorial and copying each code example: https://www.gatsbyjs.com/docs/tutorial/part-four/

**Comment by LekoArts** [comment]
No, it'll also work if you have the `query` keyword. Can you please provide a reproduction (like a repository) where you see this behavior?
