### ISSUE TITLE
[gatsby-admin] Remove Formik

### ISSUE THREAD

**Issue by coreyward** [gatsbyjs/gatsby#29632]
The developers of Formik launched a commercial form-submission handling service by the same name, later rebranded to Formium. They've reneged on promises, introduced breaking changes to the service without notifying customers, and have me emailing them desperately for weeks on end without response because a client is pissed that their form doesn't work due to a breaking change that I don't understand (and that Formik/Formium has not explained or documented). 

If Gatsby Admin is going to use it, I **strongly oppose** the default inclusion of the gatsby-admin as a required dependency of Gatsby.

Bonus point: the creator of Formik “[doesn’t] see a any value for the added complexity or indirection of Gatsby”: https://jaredpalmer.com/gatsby-vs-nextjs

**Comment by wardpeet** [comment]
Could you explain a little more on why formik as a devDependency messes with the production site? I'm not 100% following the issue.

**Comment by coreyward** [comment]
It's being installed with Gatsby v2.23.1 (i.e. not just a devDependency):

```
% yarn why formik                                                               master 
yarn why v1.22.5
[1/4] 🤔  Why do we have the module "formik"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "formik@2.2.6"
info Reasons this module exists
   - "gatsby#gatsby-admin" depends on it
   - Hoisted from "gatsby#gatsby-admin#formik"
✨  Done in 3.12s.
```

Generally speaking, the Gatsby dependency tree is a bit out of control. We're talking about a form library with a half dozen dependencies that is a peer dependency of a sub dependency, none of which are in use. It's hard to keep defending not evaluating Gatsby's dependencies for security when they're so numerous and seemingly without justification. Accidentally declaring a devDependency as a dependency in a time when Node packages (which run code when installed) are becoming the sources of vulnerabilities in critical infrastructure like build systems is also not confidence inspiring.

What I'd really like is to not have gatsby-admin or gatsby-interface dependencies at all.

**Comment by wardpeet** [comment]
It seems like you're using an old version of Gatsby. I couldn't reproduce your issue with the latest version Gatsby 2.32.4. What's the reason for sticking to < 2.25? A possible solution for your issue could be to use resolutions and force gatsby-admin to the latest version which does not have the dependency listed anymore.

To clarify a little bit, you're not installing storybook or any devDependency. We use gatsby-interface as a UI library that we can use in the commercial projects but also OSS interfaces like gatsby-admin, gatsby-desktop, ...

**Comment by coreyward** [comment]
This particular project was using the latest version of Gatsby available at the time. I avoid updating Gatsby on existing/older projects unless there's a need for it because bugs are introduced into Gatsby rather often and if I'm not actively developing a website it's unlikely I'll catch it, particularly if it is complex and not obvious. I would expect something like this fix to be backported and released as a patch for all recent-ish versions, as happens with other projects (e.g. Ruby on Rails), but the monorepo pattern tends to make this sort of maintenance release hygiene harder.
