### ISSUE TITLE
External JSON endpoint

### ISSUE THREAD

**Issue by squall-cuckoo** [gatsbyjs/gatsby#2966]
Great framework, exporting to static is brilliant.
However, I have an use case here which I'm not sure is it covered by the documentation.

My JSON file is hosted in AWS S3,
having that said, I'm not able to host put my files in src/data/ 

I tried to define an absolute path at gatsby-config.js:

    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `tnc`,
        path: `<absolutepath/>.json`
      }
    },

Note: <absoultepath/> is just a reference placeholder.

this doesn't work as it will prompt me this error.
"The path passed to gatsby-source-filesystem does not exist on your file system:"

Is there any reference to my use case?

**Comment by KyleAMathews** [comment]
gatsby-source-filesystem only works with the local filesystem. 

Easiest thing to use the filesystem plugin with gatsby-transformer-json and download the json file to your site.

A fancier and more automated way of doing this is with `createRemoteFileNode`.

It's not documented and I don't have time to explain it right now but perhaps you can understand how to use it from jts usages in the repo https://github.com/gatsbyjs/gatsby/search?utf8=✓&q=createRemoteFileNode&type=

**Comment by squall-cuckoo** [comment]
It seems like this require to download the json file instead of reading directly from the external JSON directly?

**Comment by KyleAMathews** [comment]
Yeah — I'd suggest doing that.

**Comment by pungggi** [comment]
Hi, I may have use case where this error is a bit annoying:  I am using netlify-cms to create my data store I then use this data for the build. 
When I delete all the data of a folder i configured with g-s-fs then of course after pull new data that folder is delete. 

Would you consider, instead of throwing an error, to allow a graceful info message of missing folders?

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
