### ISSUE TITLE
gatsby-source-wordpress / allWpMediaItem | audio/mpeg

### ISSUE THREAD

**Issue by PaulieScanlon** [gatsbyjs/gatsby#29666]
## Description

Hi, i'm able to query using `allWpMediaItem` which returns an `.mp3` that i have uploaded to "media" in Wordpress. However the below query only returns the mp3 if it's the last media item i uploaded.

### Steps to reproduce

Upload an `.mp3` to Wordpress and query using the following query

```
{
  allWpMediaItem(filter: {mimeType: {eq: "audio/mpeg"}}) {
    edges {
      node {
        mimeType
        mediaItemUrl
      }
    }
  }
}

```

Which (for me) returns the following:

```
{
  "data": {
    "allWpMediaItem": {
      "edges": [
        {
          "node": {
            "mimeType": "audio/mpeg",
            "mediaItemUrl": "https://pauliepro.blog/wp-content/uploads/2021/02/215416__unfa__short-ping_01.mp3"
          }
        }
      ]
    }
  },
  "extensions": {}
}
```

If i then upload an image to "media" and re-run the query the query returns nothing.

Also in **both** cases the query always returns nothing when run in production locally and when deployed to Gatsby Cloud

As a test i've run a similar query in WP Admin

```
{
  mediaItems(where: {mimeType: AUDIO_MPEG}) {
    edges {
      node {
        mediaItemUrl
        mimeType
      }
    }
  }
}

```

which correctly returns the `.mp3` but the filter doesn't work, i've mentioned this in issue [1309](https://github.com/wp-graphql/wp-graphql/issues/1309)

### Expected result

There's a small repro repo [here](https://github.com/PaulieScanlon/repro-gatsby-source-wordpress) but i'm currently developing using the same Wordpress `graphql` url so results may vary depending on what i'm currently doing with it.

I'd expect the query to always return correctly when run in development and production locally and in production when deployed to Gatsby Cloud

### Actual result

empty result returned by `...  allWpMediaItem(filter: {mimeType: {eq: "audio/mpeg"}}) { ...`

### Environment

```

  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.182
    Firefox: 85.0.2
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.29.3 => 2.29.3 
    gatsby-plugin-image: ^0.7.0 => 0.7.0 
    gatsby-plugin-sharp: ^2.14.1 => 2.14.1 
    gatsby-plugin-theme-ui: ^0.3.5 => 0.3.5 
    gatsby-source-filesystem: ^2.11.0 => 2.11.0 
    gatsby-source-wordpress: ^4.0.1 => 4.0.1 
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0 
  npmGlobalPackages:
    gatsby-cli: 2.15.1

```

**Comment by PaulieScanlon** [comment]
For anyone experiencing a similar issue the problem is related to media items that are not referenced or used in a page: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/features/media-item-processing.md#only-referenced-media-items-are-sourced

**Comment by IvanFlavorio** [comment]
Hi, I really need to be able to turn of this 'only-referenced-media-items-are-sourced' feature.

**Comment by PaulieScanlon** [comment]
Hey @ivan-aksamentov yeah i know what you mean. 

It's a tricky one because WordPress won't allow Gatsby to query data that's not in use. It kind of makes sense. You wouldn't want the plugin to query everything that's been uploaded to the media library. On a large site this could be thousands of images and lots might not actually be used. 

I guess another way round it would be to upload the pdf's to the media library and add a link to that file in a WordPress page somewhere. It's still a manual work around but it means you don't need a "dummy page" or to query any data.
