### ISSUE TITLE
[gatsby-plugin-manifest] hybrid mode is acting like manual mode

### ISSUE THREAD

**Issue by acarnwath** [gatsbyjs/gatsby#29679]
I'm attempting to provide different versions of the favicon based on the size, but lean back on the automatic production of icons for sizes that I did not supply. However, it appears when I add the key `icons`, the `icon` key is ignored, acting like the "manual" option described in the documentation rather than the way I understand that "hybrid" is supposed to.
When I remove `icons`, the generated files are included in my manifest.json, and when I include the array, ONLY those icons in the array are included in my manifest.json.
If this is _not_ the way the "hybrid" mode is supposed to work, the documentation is unclear and should be explained more clearly...

My config (`gatsby-config.js`):
```javascript
{
  resolve: `gatsby-plugin-manifest`,
  options: {
    name: `The site's name`,
    short_name: `short`,
    start_url: `/`,
    background_color: `#009ec2`,
    theme_color: `#009ec2`,
    display: `minimal-ui`,
    icon: `src/images/favicon-maskable.png`, // This path is relative to the root of the pre-rendered site
    icons: [ // Paths relative to the static folder
      {
        src: `favicon/favicon-72.png`,
        sizes: `72x72`,
        type: `image/png`,
      },{
        src: `favicon/favicon-48.png`,
        sizes: `48x48`,
        type: `image/png`,
      },{
        src: `favicon/favicon-32.png`,
        sizes: `32x32`,
        type: `image/png`,
      },
    ],
    cache_busting_mode: 'none',
  },
},
```

The referenced files:
```
/src/images/favicon-maskable.png
/static/favicon/favicon-32.png
/static/favicon/favicon-48.png
/static/favicon/favicon-72.png
```

Versions:
gatsby-plugin-manifest@2.12.0
gatsby@2.32.4

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by acarnwath** [comment]
Minimal Reproduction here: https://github.com/acarnwath/manifest-hybrid-bug-repro

Results in this manifest.webmanifest:
```
{
  "name": "The site's name",
  "short_name": "short",
  "start_url": "/",
  "background_color": "#ff0000",
  "theme_color": "#ff0000",
  "display": "minimal-ui",
  "icons": [
    {
      "src": "favicon/favicon-72.png",
      "sizes": "72x72",
      "type": "image/png"
    },
    {
      "src": "favicon/favicon-32.png",
      "sizes": "32x32",
      "type": "image/png"
    },
    {
      "src": "favicon/favicon-maskable.png",
      "sizes": "310x310",
      "type": "image/png",
      "purpose": "maskable"
    }
  ],
  "cacheDigest": null
}
```
Note that there are ONLY the icons that I included in the `icons` array, nothing additional was generated.

It could just be that the [documentation](https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/#hybrid-mode-configuration) is confusing, but based on this sentence: "The hybrid option allows the most flexibility while still not requiring you to create all icon sizes manually." 

I was expecting the same results as automatic, with my `icons` array overriding / merging with whatever it generates from `icon`, i.e. there would also be `"sizes": "96x96"`, `"sizes": "256x256"`, `"sizes": "512x512"`, etc. entries.

**Comment by acarnwath** [comment]
This is not stale (I provided a minimal reproduction and haven't heard anything since).

**Comment by acarnwath** [comment]
This is not stale (I provided a minimal reproduction and haven't heard anything since).
