### ISSUE TITLE
`gatsby-plugin-offline` + `gatsby-plugin-create-client-paths` = blank page :(

### ISSUE THREAD

**Issue by wan54** [gatsbyjs/gatsby#29701]
## Description

No pages are rendered when using `gatsby-plugin-offline` and `gatsby-plugin-create-client-paths` in the app

### Steps to reproduce

The repo with the minimal code to reproduce the issue: https://gitlab.com/pub-test/test-pwa-gatsby

### Expected result

Pages of each route should rendered

### Actual result

Blank page.

### Environment

```
System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.16.2/bin/npm
  Languages:
    Python: 3.7.7 - /Users/wanchiu/.pyenv/shims/python
  Browsers:
    Chrome: 88.0.4324.182
    Edge: 88.0.705.74
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    gatsby: ^2.32.3 => 2.32.4
    gatsby-plugin-create-client-paths: 2.10.0 => 2.10.0
    gatsby-plugin-manifest: 2.12.0 => 2.12.0
    gatsby-plugin-offline: 3.10.1 => 3.10.1
    gatsby-plugin-react-helmet: 3.10.0 => 3.10.0
  npmGlobalPackages:
    gatsby-cli: 2.19.0
```

I'm building a PWA that is also a protected SPA by utilising `gatsby-plugin-create-client-paths`. Some sections of the pages in the SPA may have contents that are pulled from Drupal.

**Comment by ascorbic** [comment]
I've tried it locally and the issue seems to be in matching of paths during hydration: the page is there in the generated HTML, and the router components are visible in devtools. It's just that nothing is being rendered. I'm not sure of the cause at the moment.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
