### ISSUE TITLE
[gatsby-source-wordpress] Cannot sort regular posts by menuOrder, but CPTs work fine

### ISSUE THREAD

**Issue by ardiewen** [gatsbyjs/gatsby#29721]
## Description

With `post-attributes` enabled for the built-in `post` post type in Wordpress, users are able to sort by MENU_ORDER in `wp-graphql`, however they do not have this argument available in `gatsby-source-wordpress`. Furthermore, this isn't an issue with CPTs.

### Steps to reproduce

1. Enable page attributes for default posts in `functions.php`:

   ```
   add_action( 'admin_init', 'posts_menu_order' );

   function posts_menu_order() {
     add_post_type_support( 'post', 'page-attributes' );
   }
   ```

2. Query posts with an `orderby` argument in wp-graphql (works fine):

   ```
   query GET_SORTED_POSTS {
     posts(where: {orderby: {field: MENU_ORDER, order: ASC}}) {
       edges {
         node {
           id
           title
         }
       }
     }
   }
   ```

3. Query posts with the `sort` argument in `gatsby graphiql` e.g. localhost:8000/___graphiql (no field option available):

   ```
   query GET_SORTED_POSTS {
     allWpPost(sort: {fields: _______, order: DESC}) {
       edges {
         node {
           id
           title
         }
       }
     }
   }
   ```

### Expected result

Contrast this to a CPT with page attributes enabled:

1. Query CPT (productPages) in `wp-graphql`:

   ```
   query GET_SORTED_PRODUCT_PAGES {
     productPages(where: {orderby: {field: MENU_ORDER, order: ASC}}) {
       edges {
         node {
           id
           title
         }
       }
     }
   }
   ```

2. Query CPT (wpProductPage) in `gatsby graphiql`:

   ```
   query GET_ALL_PRODUCT_PAGES {
     allWpProductPage(sort: {fields: menuOrder, order: ASC}) {
       edges {
         node {
           id
           title
         }
       }
     }
   }
   ```

### Actual result

The source plugin doesn't seem to surface the `menuOrder` sort argument on native posts, even though it is available on Wordpress's side.

Minimal repro available if required.

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - ~/Projects/vieren-website/node_modules/.bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    gatsby: ^2.31.1 => 2.31.1
    gatsby-image: ^2.4.19 => 2.4.21
    gatsby-omni-font-loader: ^1.3.0 => 1.3.0
    gatsby-plugin-image: ^0.7.1 => 0.7.1
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2
    gatsby-plugin-manifest: ^2.6.1 => 2.6.1
    gatsby-plugin-netlify: ^2.5.0 => 2.5.0
    gatsby-plugin-no-sourcemaps: ^2.2.0 => 2.2.1
    gatsby-plugin-react-helmet: ^3.3.11 => 3.3.14
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-segment-js: ^3.6.0 => 3.6.0
    gatsby-plugin-sharp: ^2.14.1 => 2.14.1
    gatsby-plugin-sitemap: ^2.6.0 => 2.6.0
    gatsby-plugin-styled-components: ^3.4.0 => 3.4.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.16 => 1.1.16
    gatsby-source-filesystem: ^2.3.30 => 2.3.35
    gatsby-source-wordpress: ^4.0.1 => 4.0.1
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0

**Comment by ardiewen** [comment]
not stale

**Comment by ardiewen** [comment]
not stale

> Hiya!
> 
> This issue has gone quiet. Spooky quiet. 👻
> 
> We get a lot of issues, so we currently close issues after 60 days of inactivity. It’s been at least 20 days since the last update here.
> If we missed this issue or if you want to keep it open, please reply here.
> As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [gatsby.dev/contribute](https://www.gatsbyjs.org/contributing/how-to-contribute/) for more information about opening PRs, triaging issues, and contributing!
> 
> Thanks for being a part of the Gatsby community! 💪💜

**Comment by ardiewen** [comment]
not stale

**Comment by ardiewen** [comment]
not stale

**Comment by rforster-dev** [comment]
Not stale - very keen to utilise out of the box functionality in WP before I have to develop my own....

**Comment by rforster-dev** [comment]
Not stale

**Comment by rforster-dev** [comment]
Not stale - is there any view on when and if this would be considered?

**Comment by rforster-dev** [comment]
Not stale - i've had to create some custom GraphQL to expose the ordering of a separate plugin that handles reOrdering of posts and taxonomies, but this should be still considered as menu order in WP is core functionality.
