### ISSUE TITLE
Error during production build when using Preact plugin

### ISSUE THREAD

**Issue by codejet** [gatsbyjs/gatsby#2972]
When I add the Preact plugin development works fine, but when I run `gatsby build` I get this:

```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  60 |     }
  61 |
> 62 |     if (location.pathname === rootPath) {
     |                  ^
  63 |       header = (
  64 |         <h1>
  65 |           <Linker to={'/'}>Gatsby Starter Blog</Linker>


  WebpackError: Cannot read property 'pathname' of undefined

  - index.js:62 Template.render
    src/layouts/index.js:62:18

  - preact-compat.js:496 callMethod
    ~/preact-compat/dist/preact-compat.js:496:1

  - preact-compat.js:507 Template.render
    ~/preact-compat/dist/preact-compat.js:507:1

  - index.js:155 renderToString
    ~/preact-render-to-string/dist/index.js:155:1

  - index.js:162 renderToString
    ~/preact-render-to-string/dist/index.js:162:1

  - index.js:162 renderToString
    ~/preact-render-to-string/dist/index.js:162:1

  - index.js:162 renderToString
    ~/preact-render-to-string/dist/index.js:162:1

  - index.js:162 renderToString
    ~/preact-render-to-string/dist/index.js:162:1

  - index.js:162 renderToString
    ~/preact-render-to-string/dist/index.js:162:1

  - gatsby-ssr.js:25 Object.exports.replaceRenderer
    ~/gatsby-plugin-styletron/gatsby-ssr.js:25:1

```

When I remove the plugin the production build is successful.

**Comment by codejet** [comment]
@KyleAMathews could you maybe point me to the place where the props for layouts/index.js are being (pre)filled or how this works, respectively?

When console logging during build, I saw that at first the props contain a location object with a pathname member, but in the next iteration they look like this: `{ layoutContext: {}, children: [Function: children] }`.

Prefilling the location object (`const { location = {}, children } = this.props;`) results in the wrong markup being rendered server-side (once the client-side kicks in it gets replaced, resulting in a "flash of server-side markup", so to say), but makes the build run through.

**Comment by DanielRuf** [comment]
I also get this error so this is not yet resolved.

**Comment by KyleAMathews** [comment]
This is where pages are rendered https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/page-renderer.js

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by DanielRuf** [comment]
> Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

=/

So no preact support?

cc @developit

**Comment by codejet** [comment]
I debugged a bit the other day but unfortunately didn't get to the bottom of the issue. Will try again as soon as I find some time.

**Comment by kakadiadarpan** [comment]
@codejet could you provide relevant environment information by running `gatsby info --clipboard`?

**Comment by codejet** [comment]
After upgrading to Gatsby 2 there is a different issue which is described here https://github.com/gatsbyjs/gatsby/issues/8545

**Comment by kakadiadarpan** [comment]
@codejet Preact support for Gatsby 2 is broken currently.

Since you have upgraded to Gatsby v2, we'll be closing this in favor of #8545
