### ISSUE TITLE
Media download issues

### ISSUE THREAD

**Issue by adrianhewitt** [gatsbyjs/gatsby#29744]
Been wrestling with this for a few weeks, but I can't seem to get this budging. Whenever i try to build / develop from my cleaned project, i always get hit by this error for many (not all) of the image files:

```
gatsby-source-wordpress  Fetching https://cms.me.com/wp-content/uploads/20
19/09/image.png is taking a long time time (longer
than 15 seconds). This file is 6.85 MB
```

```
RequestError: Timeout awaiting 'request' for 30000ms
    at ClientRequest.<anonymous>
(/Users/me/Repositories/me.com/node_modules/gatsby-source-wordpre
ss-experimental/node_modules/got/dist/source/core/index.js:953:65)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/me/Repositories/me.com/n
ode_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at Timeout.timeoutHandler [as _onTimeout]
(/Users/me/Repositories/me.com/node_modules/gatsby-source-wordpre
ss-experimental/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1612140972803,
    socket: 1612140972803,
    lookup: 1612140972804,
    connect: 1612140972886,
    secureConnect: 1612140973028,
    upload: 1612140973028,
    response: 1612140973105,
    end: undefined,
    error: 1612141002803,
    abort: 1612141002803,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 82,
      tls: 142,
      request: 0,
      firstByte: 77,
      download: undefined,
      total: 30000
    }
  },
  event: 'request'
}
```

i've tried killing the request concurrency using:

```
    {
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: `https://cms.me.com/graphql`,
        schema: {
          requestConcurrency: 1
        },
      }
    },
```

but i'm not even sure the plugin is even listening to that config as it's flying through trying to download the images. that said, the wordpress instance is running on a super fast VPS and shouldn't have any issues with the transfer. Additionally, this wordpress instance was working perfectly with a previous gatsbyjs build... so i'm out of ideas. libraries are all updated etc.

**Comment by adrianhewitt** [comment]
updated all libraries, tried the usual `gatsby build` and `gatsby develop` as a baseline and they were still failing, but if i run `GATSBY_CONCURRENT_DOWNLOAD=5 gatsby build` and `GATSBY_CONCURRENT_DOWNLOAD=5 gatsby develop` the file download errors go away. Yay!

I was sure somewhere in my troubleshooting in the past i tried that approach, but maybe that was some other variable or there was a change somewhere.

**Comment by TylerBarnes** [comment]
Woo, that's really great to hear! The media item request concurrency will be fixed soon but I'm glad there's a workaround for now :)

**Comment by Piligrimas** [comment]
I can confirm that adding `GATSBY_CONCURRENT_DOWNLOAD=5` variable solves the issue. Thank you!

**Comment by ali1059** [comment]
I am have media fetch issue RequestError: Timeout awaiting 'request' for 30000ms. I have also increased the timeout time in schema option and have also used "GATSBY_CONCURRENT_DOWNLOAD=5 gatsby develop" but nothing is working.

**Comment by iamkratos** [comment]
I'm also still experiencing this issue after updating my scripts

**Comment by adrianhewitt** [comment]
All I can suggest on top of the command line `GATSBY_CONCURRENT_DOWNLOAD=5 gatsby develop` are these which fixed my problems:


 ```
   {
      resolve: `gatsby-source-wordpress`,
      options: {
        url: `https://domain.com/graphql`,
        schema: {
          requestConcurrency: 1, // i cant remember if this was a fix or not, but i just killed all concurrency which the command line probably overrode
          timeout: 90000, // i cant remember if this was a fix or not, or just an attempt at killing the bug in this thread
        },
        type: {
          MediaItem: {
            localFile: {
              requestConcurrency: 1, // i cant remember if this was a fix or not, but i just killed all concurrency which the command line probably overrode
              maxFileSizeBytes: 100000000, // large images would die if they were larger than.. like, 5mb by default? undocumented and threw no warnings, just died.
            },
          },
        },
      }
    },
```

**Comment by tungto** [comment]
> I am have media fetch issue RequestError: Timeout awaiting 'request' for 30000ms. I have also increased the timeout time in schema option and have also used "GATSBY_CONCURRENT_DOWNLOAD=5 gatsby develop" but nothing is working.

same here :(

**Comment by sam-davidoff** [comment]
@SergiOca87 You run it in the terminal like the normal commands. I updated the scripts section of my package.json to use yarn develop as a shortcut

```
"scripts": {
    "develop": "GATSBY_CONCURRENT_DOWNLOAD=5 gatsby develop",
  },
```

**Comment by SergiOca87** [comment]
> @SergiOca87 You run it in the terminal like the normal commands. I updated the scripts section of my package.json to use yarn develop as a shortcut
> 
> ```
> "scripts": {
>     "develop": "GATSBY_CONCURRENT_DOWNLOAD=5 gatsby develop",
>   },
> ```

That doesn't work on Windows, it says it's an unrecognized command.
