### ISSUE TITLE
Not allowed to use cyrillic symbols in path

### ISSUE THREAD

**Issue by Ssupreme** [gatsbyjs/gatsby#29759]
## Description

I use template for blog to creare pages from md files. When my title is written with cyrillic symbols, path or slug is equal to empty. If I have atleast one latin symbol, path is created with this only symbol. I didn't test with file name, but I thing problem will be the same.

### Steps to reproduce

https://github.com/Ssupreme/theunicodebug
In file theunicodebug/src/data/blog/blog-1.md replace all symbols with non-latin or number.

### Expected result

Other services have transliteration of cyrillic symbols or today it is widely accepted to use cyrillic symbols as domain names and pathes for url.

### Actual result

 ERROR #11323

Your site's "gatsby-node.js" must set the page path when creating a page.

The page object passed to createPage:
{
    "path": "",
    "component": "C:\\Users\\....\\src\\templates\\blog-template\\blog-template.js",
    "context": {
        "slug": ""
    }
}

### Environment

 System:
    OS: Windows 10 10.0.18363
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.1
  Browsers:
    Chrome: 88.0.4324.182
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.31.1 => 2.31.1
    gatsby-background-image: ^0.9.12 => 0.9.14
    gatsby-image: ^2.2.34 => 2.2.40
    gatsby-plugin-google-analytics: ^2.1.35 => 2.1.35
    gatsby-plugin-manifest: ^2.2.40 => 2.2.41
    gatsby-plugin-offline: ^3.0.25 => 3.0.34
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.22
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sharp: ^2.12.1 => 2.12.1
    gatsby-plugin-sitemap: ^2.2.26 => 2.2.27
    gatsby-plugin-styled-components: ^3.1.13 => 3.1.19
    gatsby-remark-images: ^3.1.42 => 3.1.44
    gatsby-source-filesystem: ^2.1.39 => 2.1.48
    gatsby-transformer-json: ^2.2.20 => 2.2.26
    gatsby-transformer-remark: ^2.6.48 => 2.6.50
    gatsby-transformer-sharp: ^2.3.6 => 2.3.14
  npmGlobalPackages:
    gatsby-cli: 2.19.2

**Comment by LekoArts** [comment]
This seems like a duplicate of https://github.com/gatsbyjs/gatsby/issues/16765 -- it stayed closed because there was no clear [minimal reproduction][reproduction] (which we also need here) and different answers about possible solutions. It'd be really helpful if you can answer the questions here: https://github.com/gatsbyjs/gatsby/issues/16765#issuecomment-757874458

[reproduction]: https://gatsby.dev/reproduction

**Comment by Ssupreme** [comment]
https://github.com/Ssupreme/theunicodebug

I created this sample, ignore fuctionality. 
Problem appers when in file theunicodebug/src/data/blog/blog-1.md title doesn't contain latin symbol.

**Comment by Ssupreme** [comment]
> This seems like a duplicate of #16765 -- it stayed closed because there was no clear [minimal reproduction](https://gatsby.dev/reproduction) (which we also need here) and different answers about possible solutions. It'd be really helpful if you can answer the questions here: [#16765 (comment)](https://github.com/gatsbyjs/gatsby/issues/16765#issuecomment-757874458)

Did I answer the question?
