### ISSUE TITLE
createRedirect broke gatsby-plugin-netlify redirects on 2.32.7

### ISSUE THREAD

**Issue by jaska120** [gatsbyjs/gatsby#29779]
Hi,

newly merged PR and published as version 2.32.7 broke gatsby-plugin-netlify redirects implementation. The release (https://github.com/gatsbyjs/gatsby/pull/29742) introduced a new prop `ignoreCase` which is passed to the build output of `_redirects` file on gatsby-plugin-netlify https://github.com/gatsbyjs/gatsby/blob/e79fc6b8b0da2bb5aaec8e0ff06073af9c466401/packages/gatsby-plugin-netlify/src/create-redirects.js#L46

I am not sure which way is right: introducing a new prop which with default value of false instead of undefined or the way gatsby-plugin-netlify including all the props to the output.

The result now:
- `_redirects` file outputs ignoreCase=false by default, which in turn is not recognized on Netlify and therefore the redirects are not working.

**Comment by sidharthachatterjee** [comment]
I’ll push a fix to the netlify plugin to resolve this today. Thanks for reporting!

**Comment by mlenser** [comment]
We can confirm the same problem. Thanks for looking into it!

**Comment by ohsnapitscolin** [comment]
Following up here, did this fix go out? We're still running into the same issue.

**Comment by oskareke** [comment]
This is causing a lot of trouble for us SEO-wise... any updates?

**Comment by jackhair** [comment]
> > Following up here, did this fix go out? We're running into the same issue and had to revert to restore our redirects functionality. Upgraded to the latest version of `gatsby-plugin-netlify` but still seeing the issue.
> 
> @ohsnapitscolin What version did you revert back to when you restored your redirects functionality?

I'm on the same team as @ohsnapitscolin, our issue came when we upgraded from `2.32.0` to `2.32.8`, so we reverted straight back to `2.32.0` once we found the issue was breaking a lot of our redirects.

**Comment by vladar** [comment]
Published in `gatsby-plugin-netlify@3.0.1`

**Comment by fivetwelve** [comment]
> Published in `gatsby-plugin-netlify@3.0.1`

Any resolution for builds that are not using Gatsby 3.x? There may be a lot and my project is one of them.

After adding 3.0.1 of the plugin...
`warn Plugin gatsby-plugin-netlify is not compatible with your gatsby version 2.32.9 - It requires gatsby@^3.0.0-next.0`

**Comment by vladar** [comment]
@fivetwelve This is also published in `gatsby-plugin-netlify@2.11.1`

**Comment by fivetwelve** [comment]
Much appreciated @vladar 🙏
