### ISSUE TITLE
[gatsby-source-contentful] Missing support for transforming image assets with `cornerRadius`

### ISSUE THREAD

**Issue by bobeagan** [gatsbyjs/gatsby#29784]
## Description

Attempting to run a GraphQL query for an Asset from Contentful does not allow specifying a [cornerRadius](https://www.contentful.com/developers/docs/references/graphql/#image-transformations) option. All other options appear to be present except that one.

### Steps to reproduce

Attempt to build a query that tries to transform the image using cornerRadius and see that it is not supported or inspect the schema for the type (see below)
![image](https://user-images.githubusercontent.com/100226/109230432-211dff80-7782-11eb-8e5d-9b2a4f24fd0a.png)

### Expected result

It should support all of the options according to the Contentful spec

### Actual result

Receive error in GraphiQL explorer: `Unknown argument "cornerRadius" on field "fixed" of type "ContentfulAsset".

### Environment

Can see that it is not present in the current master branch: https://github.com/gatsbyjs/gatsby/blob/3b4d32f0b2d6aef3193213252c3eb813cc2cbea9/packages/gatsby-source-contentful/src/extend-node-type.js#L474

**Comment by vladar** [comment]
CC @axe312ger

**Comment by bobeagan** [comment]
Not stale

**Comment by axe312ger** [comment]
@bobeagan Any reason why you don't do this with CSS?

**Comment by bobeagan** [comment]
I'm already transforming the image and its available via their API so seems nice to be able to have it handled and cached on their end. As a workaround we are doing with CSS for now though. I just felt it would be nice to have full coverage of their image API capabilities available.

**Comment by axe312ger** [comment]
Will leave this open as feature request. Feel free to create a PR, I am happy to review an merge.

**Comment by axe312ger** [comment]
This is not forgotten, and as other issues with higher priority getting done, I might find time to add this in the follow weeks :)
