### ISSUE TITLE
[gatsby] validate plugin options does not run against a locally resolved plugin

### ISSUE THREAD

**Issue by kamranayub** [gatsbyjs/gatsby#29785]
## Description

I am attempting to use plugin options schema validation for a demo/sample using a local plugin. Right now, the plugin is resolved at a custom path using `require.resolve`. When the plugin loads, it doesn't seem to respect or validate my options schema. Resolving the plugin outside the `plugins` directory could be the root cause, I didn't try it with putting the plugin there. Regardless, I would expect it to work the same however the plugin itself is resolved whether local or from a package.

Related PR: https://github.com/gatsbyjs/gatsby/pull/27242#issuecomment-786363729

### Steps to reproduce

Create a local plugin with the following options schema:

**gatsby-node.js**

```js
exports.pluginOptionsSchema = ({ Joi }) => Joi.object({
  required: Joi.boolean().required(),
  optionalString: Joi.string()
});
```

Add to `gatsby-config.js` using `require.resolve`:

```js
{
        plugins: [
          {
            resolve: require.resolve('./__fixtures__/local-plugin'),
            options: {
              optionalString: 1234
            },
          },
        ],
      }
```

I have a test case to reproduce this as well in my fork.

![image](https://user-images.githubusercontent.com/563819/109245817-c64acf00-77a6-11eb-8f10-e125238b093a.png)

**packages\gatsby\src\bootstrap\load-plugins\__tests__\load-plugins.ts**

```js
it(`validates local plugin schemas`, async () => {
      await loadPlugins({
        plugins: [
          {
            resolve: require.resolve('./__fixtures__/local-plugin'),
            options: {
              optionalString: 1234
            },
          },
        ],
      })

      expect(reporter.error as jest.Mock).toHaveBeenCalledTimes(1)
      expect(mockProcessExit).toHaveBeenCalledWith(1)
    })
```

### Expected result

I expect that `pluginOptionsSchema` is respected for both local and "normal" plugins as the documentation doesn't specify that there would be a difference.

### Actual result

When Gatsby loads the plugin in `develop` or `build`, it does not throw an error with schema validation.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.11
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.74)

```

**Comment by kamranayub** [comment]
I am actively looking at providing a fix for this, I will push a PR with the failing test case at least.

**Comment by sidyes** [comment]
@kamranayub +1

I got this same problem within a lerna monorepo.

**Comment by kamranayub** [comment]
It's fixed but just awaiting review
