### ISSUE TITLE
how to get https:// on relative paths?

### ISSUE THREAD

**Issue by Maxhodges** [gatsbyjs/gatsby#2979]
```
<Image src=“/static/assets/images/home/category-kanji.png” />
```
emits an image path preceded by `http://`, which makes my site appear as not secure. any idea how to get it to emit `https://`

**Comment by calcsam** [comment]
Can you post more info please? Doesn't look like Gatsby -- it doesn't look like you're using the default gatsby-image component, example of how that works here:

https://github.com/gatsbyjs/gatsby/blob/master/examples/using-gatsby-image/src/pages/blur-up.js
https://using-gatsby-image.gatsbyjs.org/blur-up/

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
