### ISSUE TITLE
Gatsby is rendering the same blog post for every post URl

### ISSUE THREAD

**Issue by thomasabishop** [gatsbyjs/gatsby#29804]
## Description

I have followed the standard Gatsby documentation for creating blog pages progammatically. Although each blog post has its own URL - demonstrated by the 404 page - when I click through the same blog post is rendered for every URL. 

### Steps to reproduce

`gatsby-node.js` 
```
const path = require("path")
const _ = require("lodash")
//Access blog post in file directory and generate slug from filename
const { createFilePath } = require(`gatsby-source-filesystem`)
exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions
  if (node.internal.type === `MarkdownRemark`) {
    const slug = createFilePath({ node, getNode, basePath: `content/posts` })
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }
}

exports.createPages = async ({ actions, graphql, reporter }) => {
  const { createPage } = actions
  const blogPostTemplate = path.resolve("./src/templates/post.jsx")
  const tagTemplate = path.resolve("./src/templates/tags.jsx")
  const result = await graphql(`
    {
      postsRemark: allMarkdownRemark(
        sort: { order: DESC, fields: [frontmatter___date] }
        limit: 2000
      ) {
        edges {
          node {
            fields {
              slug
            }
            frontmatter {
              template
              tags
            }
          }
        }
      }
      tagsGroup: allMarkdownRemark(limit: 2000) {
        group(field: frontmatter___tags) {
          fieldValue
        }
      }
    }
  `)
  // handle errors
  if (result.errors) {
    reporter.panicOnBuild(`Error while running GraphQL query.`)
    return
  }
  const posts = result.data.postsRemark.edges
  // Create post detail pages
  posts.forEach(({ node }) => {
    createPage({
      path: `/posts${node.fields.slug}`,
      component: blogPostTemplate,
    })
  })
  // Extract tag data from query
  const tags = result.data.tagsGroup.group
  // Make tag pages
  tags.forEach(tag => {
    createPage({
      path: `/tags/${_.kebabCase(tag.fieldValue)}/`,
      component: tagTemplate,
      context: {
        tag: tag.fieldValue,
      },
    })
  })
}
```

`gatsby-config.js`
```
module.exports = {
  siteMetadata: {
    title: `Thomas Bishop Web Developer`,
  },
  plugins: [
    `gatsby-plugin-material-ui`,
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `posts`,
        path: `${__dirname}/content/posts`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/img`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-prismjs`,
            options: {
              prompt: {
                user: "root",
                host: "localhost",
                global: false,
              },
            },
          },
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 800,
            },
          },
        ],
      },
    },
  ],
}
```
* Demonstration that the pages exist *
<img width="1058" alt="Screenshot 2021-02-26 at 15 33 06" src="https://user-images.githubusercontent.com/44098506/109320531-02823c00-7848-11eb-8940-ff889596d10d.png">

*Demonstration of the wrong page being shown for the url (same for every blog url)*
<img width="1131" alt="Screenshot 2021-02-26 at 15 35 17" src="https://user-images.githubusercontent.com/44098506/109320778-50973f80-7848-11eb-9b35-62f6365d04d6.png">

### Expected result
Each blog url should link to its corresponding page and render that page when navigated to

### Actual result

Every blog url links to one single page that does not correspond to the URL. No matter which blog page URL I click, I always receive the same (wrong) page. 

### Environment

  System:
    OS: macOS 11.1
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    npm: 7.0.14 - /usr/local/bin/npm
  Languages:
    Python: 3.9.0 - /Users/thomasbishop/.pyenv/shims/python
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 86.0
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.32.8 => 2.32.8 
    gatsby-image: ^2.10.0 => 2.10.0 
    gatsby-plugin-material-ui: ^2.1.10 => 2.1.10 
    gatsby-plugin-remove-trailing-slashes: ^2.10.0 => 2.10.0 
    gatsby-plugin-sass: ^2.8.0 => 2.8.0 
    gatsby-plugin-sharp: ^2.13.1 => 2.14.3 
    gatsby-remark-images: ^3.10.0 => 3.11.1 
    gatsby-remark-prismjs: ^3.12.0 => 3.12.0 
    gatsby-source-filesystem: ^2.11.1 => 2.11.1 
    gatsby-transformer-remark: ^2.14.0 => 2.16.1 
    gatsby-transformer-sharp: ^2.11.0 => 2.11.0 
  npmGlobalPackages:
    gatsby-cli: 2.19.1

**Comment by vladar** [comment]
Hi @thomasabishop!

You didn't provide contents of your `src/templates/post.jsx`. Are you sure you wire up query variables correctly there? I don't see any context in your createPage call:

```js
posts.forEach(({ node }) => {
  createPage({
    path: `/posts${node.fields.slug}`,
    component: blogPostTemplate,
    // context: {}?
  })
})
```

That's the first thing to check. 

If you still see the same result - please provide a [provide a minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

[reproduction]: https://gatsby.dev/reproduction

**Comment by vladar** [comment]
Also check out related docs: https://www.gatsbyjs.com/docs/how-to/querying-data/page-query/#how-to-add-query-variables-to-a-page-query

**Comment by thomasabishop** [comment]
Thank you @vladar . I think you're right and it's the lack of context that is the issue here. I've just read the docs properly and will amend.
