### ISSUE TITLE
[gatsby-plugin-sitemap] Documentation and DX improvements

### ISSUE THREAD

**Issue by jevenson** [gatsbyjs/gatsby#29810]
## Summary

I implemented gatsby-plugin-sitemap onto my site just now, and I ran into a few problems that I think could've been prevented by improving documentation and adding some error handling with logging in the plugin.

First, I was unclear that it is required to query `allSitePage` with a `path` property. The docs _do_ state this, however as devs do, we typically skim documentation. Would be good to add error handling/logging when the `allSitePage` option is missing.

Second, I forgot to return from the `serialize` function, which led to this error. I think this could be improved with some error handling. If urls is undefined, throw an error with a message "gatsby-plugin-sitemap did not recieve sitemap entries. Did you forget to return from your serialize function". Or something of that nature.

```shell
 ERROR #11321  PLUGIN

"gatsby-plugin-sitemap" threw an error while running the onPostBuild lifecycle:

Cannot read property 'forEach' of undefined

  79 | 
  80 |             map = _sitemap.default.createSitemap(rest);
> 81 |             urls.forEach(function (u) {
     |                  ^
  82 |               return map.add(u);
  83 |             });
  84 |             return _context.abrupt("return", (0, _internals.writeFile)(saved,
map.toString()));

File: node_modules\gatsby-plugin-sitemap\gatsby-node.js:81:18
```

### Motivation

To improve DX when implementing the sitemap plugin

## Steps to resolve this issue

I will be cooking up a pull request for your consideration to resolve these issues 👍

**Comment by vladar** [comment]
Sounds great 👍 Thanks for tackling this and a PR is welcome!

But you should also know that we have a pending PR for this plugin rewrite: https://github.com/gatsbyjs/gatsby/pull/25670
We will likely publish a new major version of the plugin somewhere in the next month.

**Comment by jevenson** [comment]
Ahhh, thanks for letting me know. I'll watch out for the release and check it out. Thanks!

**Comment by jevenson** [comment]
I've still got my eye on this, waiting for the next version to be published

**Comment by arun-is** [comment]
looks like that PR you were waiting on is stale? https://github.com/gatsbyjs/gatsby/pull/25670

**Comment by LekoArts** [comment]
https://github.com/gatsbyjs/gatsby/pull/25670 was merged and currently published under the `@next` tag. If you have any additional improvements to the docs please open a PR. Thanks!
