### ISSUE TITLE
Dead Link in gatsby-image-plugin npm description

### ISSUE THREAD

**Issue by Hahlh** [gatsbyjs/gatsby#29825]
Found at:
[https://www.npmjs.com/package/gatsby-plugin-image#static-images](https://www.npmjs.com/package/gatsby-plugin-image#static-images)

![image](https://user-images.githubusercontent.com/45669613/109398138-15c20400-793b-11eb-8e7f-37a35678a2f2.png)

Excited for v3! :partying_face:

**Comment by LekoArts** [comment]
Hi! Please direct this feedback to here: https://github.com/gatsbyjs/gatsby/discussions/27950
Thanks!
