### ISSUE TITLE
gatsby-source-wordpress ACF field type "File" is null when video is selected

### ISSUE THREAD

**Issue by Dsmitheo** [gatsbyjs/gatsby#29820]
This is a non issue for the WordPress GraphQL IDE,  I'm only seeing this within the Gatsby GraphQL IDE.

Steps to reproduce:
**ACF Field settings**
<img width="900" alt="Screenshot 2021-02-27 at 11 22 30" src="https://user-images.githubusercontent.com/6852328/109385944-41b79800-78ef-11eb-9d6a-82542d01406e.png">

**Attach a video or image from the media library and check the following results:**
![Screenshot_2021-02-27_at_11_10_04](https://user-images.githubusercontent.com/6852328/109385970-6dd31900-78ef-11eb-80c0-67bd436e18a0.png)

It's worth mentioning that the Gatsby Graph QL IDE is displaying url is http://wordpress/graphql due to this being run within docker compose,  I can confirm its connecting to the same WordPress instance,  as seen in the "With image" part of the test

**Environment:**
Gatsby:
    "gatsby": "2.32.4",
    "gatsby-image": "^2.11.0",
    "gatsby-plugin-react-helmet": "3.10.0",
    "gatsby-plugin-sass": "3.2.0",
    "gatsby-plugin-sharp": "2.14.1",
    "gatsby-source-wordpress": "4.0.1",
    "gatsby-transformer-sharp": "2.12.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-helmet": "6.1.0",

Wordpress:
    Advanced Custom Fields PRO : 5.9.5
    WP Gatsby : 1.0.1
    WP GraphQL : 1.1.8 
    WPGraphQL for Advanced Custom Fields : 0.4.1

Hopefully this can be reproduced,  are there any recommended alternatives?

**Comment by daniel7912** [comment]
I had this too but with Flexible Content fields. Fixed it by stopping my Gatsby server and running

`yarn clean && yarn develop`

Hope it helps!

**Comment by jooola** [comment]
@Dsmitheo Maybe duplicate of https://github.com/gatsbyjs/gatsby/issues/30755

**Comment by TylerBarnes** [comment]
Please try `gatsby-source-wordpress@5.10.0-alpha-wordpress.19+3d743f8f07` as I believe it solves this issue.
