### ISSUE TITLE
DEV_SSR returns 404 for encoded pathnames and then returns the content

### ISSUE THREAD

**Issue by herecydev** [gatsbyjs/gatsby#29858]
## Description

**For this ticket let's use the arabic number `١` which is `1` in English.**

Gatsby build + serve works correctly with encoded characters in page names, i.e. `/pages/١.js`. However the dev server (when DEV_SSR = true) returns a 404. Interestingly the gatsby 404 page is shown but it is able to recover and show the page.

This is especially problematic for testing in cypress, as the 404 throws exceptions.

![image](https://user-images.githubusercontent.com/11328618/109487192-cc2d0280-7a7b-11eb-9148-156237b44dab.png)

### Steps to reproduce

1. Clone `https://github.com/herecydev/gatsby-arabic-bug`
2. `npm develop`
3. Navigate to http://localhost:8000/١

### Expected result

Page is correctly returned with an HTTP 200 status code

### Actual result

Page is returned with a 404, however it subsequently does load.

### Environment

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 9 5950X 16-Core Processor            
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.81)
  npmPackages:
    gatsby: ^2.32.8 => 2.32.8 
    gatsby-image: ^2.11.0 => 2.11.0 
    gatsby-plugin-gatsby-cloud: ^1.0.2 => 1.0.2 
    gatsby-plugin-manifest: ^2.12.1 => 2.12.1 
    gatsby-plugin-offline: ^3.10.2 => 3.10.2 
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0 
    gatsby-plugin-sharp: ^2.14.3 => 2.14.3 
    gatsby-source-filesystem: ^2.11.1 => 2.11.1 
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0 
  npmGlobalPackages:
    gatsby-cli: 2.19.2

```

**Comment by LekoArts** [comment]
Hi, thanks for the issue!
For currently active experiments or betas we like to keep things inside a Discussion. Please copy your text there: https://github.com/gatsbyjs/gatsby/discussions/28138

Thanks!
