### ISSUE TITLE
DEV_SSR: true mode reevaluates node_module packages during SSR

### ISSUE THREAD

**Issue by jayphelps** [gatsbyjs/gatsby#29887]
## Description

`DEV_SSR: true` mode reevaluates node_module packages during SSR, even though they didn't change. This causes packages that have global state (`globalThis.something = true`) to potentially behave in unexpected ways, as well as causes `instanceof` checks to fail if you are keeping a reference to a class instance from one of these libraries.

### Steps to reproduce

https://github.com/jayphelps/gatsby-dev-ssr-issue

### Expected result

Imported node_modules are only evaluated once during DEV_SSR on the dev server, within the same JS isolate.

Because it can be helpful to know what others in the community are doing, I also included a similar demo in Next.js [in the same repo](https://github.com/jayphelps/gatsby-dev-ssr-issue/tree/master/nextjs-app), where it appears they do not reevaluate the node_module package more than once, mitigating the issue.

### Actual result

Imported node_modules are reevaluated each time you make a change during DEV_SSR on the dev server, within the same JS isolate, causing potential issues with libraries that expect to only be imported once, along with other strange behaviors such as `instanceof` checks failing due to the same classes being created more than once.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.0.1 - ~/.nvm/versions/node/v15.0.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.0.1/bin/yarn
    npm: 7.5.4 - ~/.nvm/versions/node/v15.0.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Edge: 88.0.705.81
    Firefox: 84.0.2
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.32.8 => 2.32.8 
```

**Comment by LekoArts** [comment]
Hi! Please post this in the respective umbrella discussion: https://github.com/gatsbyjs/gatsby/discussions/28138
Thanks!

**Comment by jayphelps** [comment]
@LekoArts can you link me to the specific thread around this? There's a fair amount of unrelated discussion and I can't seem to find the one applicable to this issue.

**Comment by LekoArts** [comment]
Feel free to post it as a new answer to the discussion :)

**Comment by jayphelps** [comment]
@LekoArts I'm sorry, I'm not following? I'm reporting a bug here 😄  That's a discussion thread on a new feature, not a bug report.

**Comment by LekoArts** [comment]
As this is an experimental feature behind a flag, we track those inside umbrella discussions: https://github.com/gatsbyjs/gatsby/discussions/categories/umbrella-discussions

That's also why the CLI is pointing you to this discussion

**Comment by jayphelps** [comment]
@LekoArts 

> That's also why the CLI is pointing you to this discussion

Come on..

**Comment by LekoArts** [comment]
I don't follow?

**Comment by LekoArts** [comment]
@jayphelps In case you missed the above 🤗
