### ISSUE TITLE
Circular dependency when using StaticQuery in gatsby-browser

### ISSUE THREAD

**Issue by coreyward** [gatsbyjs/gatsby#29903]
## Description

When consuming a hook that uses `useStaticQuery` in a component that is rendered in `gatsby-browser.js`, the [circular-dependency-plugin](https://www.npmjs.com/package/circular-dependency-plugin) detects an unexpected circular dependency that hops through various internal Gatsby files in `.cache`. 

### Steps to reproduce

Here's a reproduction on CodeSandbox using the default Gatsby starter:
https://codesandbox.io/s/gatsby-circular-dependency-repro-9lns5

Relevant files:
- `gatsby-node.js` - sets up the circular dependency plugin (pretty straightforward)
- `gatsby-browser.js` - uses the `Example` component in the `wrapRootElement` component
- `src/components/Example.js` - uses the hook that pulls data using a StaticQuery
- `src/hooks/useInternalPaths.js` - contains the StaticQuery that I suspect is causing this all

When the app boots you should see two warning messages in the console from the circular dependency plugin:

> warning Circular dependency detected:
src/components/Example.jsx -> src/hooks/useInternalPaths.js -> .cache/gatsby-browser-entry.js -> .cache/public-page-renderer.js -> .cache/public-page-renderer-dev.js -> .cache/query-result-store.js -> .cache/page-renderer.js -> .cache/api-runner-browser.js -> .cache/api-runner-browser-plugins.js -> gatsby-browser.js -> src/components/Example.jsx
> warning Circular dependency detected:
src/hooks/useInternalPaths.js -> .cache/gatsby-browser-entry.js -> .cache/public-page-renderer.js -> .cache/public-page-renderer-dev.js -> .cache/query-result-store.js -> .cache/page-renderer.js -> .cache/api-runner-browser.js -> .cache/api-runner-browser-plugins.js -> gatsby-browser.js -> src/components/Example.jsx -> src/hooks/useInternalPaths.js

### Expected result

No errors or warnings.

### Actual result

Circular dependency is created.

### Environment

Exists across multiple versions and environments, including…

```
System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.23.0 -
/tmp/yarn--1614650128566-0.23669315139729963/node
    Yarn: 1.22.10 -
/tmp/yarn--1614650128566-0.23669315139729963/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^2.32.8 => 2.32.8
    gatsby-image: ^2.11.0 => 2.11.0
    gatsby-plugin-gatsby-cloud: ^1.0.2 => 1.0.2
    gatsby-plugin-manifest: ^2.12.1 => 2.12.1
    gatsby-plugin-offline: ^3.10.2 => 3.10.2
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0
    gatsby-plugin-sharp: ^2.14.3 => 2.14.3
    gatsby-source-filesystem: ^2.11.1 => 2.11.1
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0
```

cc: @vladar @calcsam

**Comment by wardpeet** [comment]
@coreyward Thanks for the bug report, is this causing any issues?

**Comment by coreyward** [comment]
I'm not sure. I don't have a ton of experience dealing with side effects from circular dependencies in JS aside from them causing obscure build failures. Mostly this creates a lot of noisy log messages, and I don't know whether or not it's safe to ignore them.

**Comment by coreyward** [comment]
Yes, it has gone quiet. @wardpeet Do you think this is something that the Gatsby team will have a chance to look into?

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
