### ISSUE TITLE
gatsby-plugin-image placeholder opacity transition is blinking

### ISSUE THREAD

**Issue by laurenskling** [gatsbyjs/gatsby#29911]
## Description

as discussed in https://github.com/gatsbyjs/gatsby/pull/28868. The image is blinking when blurring from the placeholder to the real image. Looks like because of the placeholder being removed from the DOM, so the opacity transition isnt working.

### Expected result

The blur up effect should blur from the placeholder to the image, without blinking to the background color.

### Actual result

You see placeholder -> background -> real image transition

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /var/folders/gh/yg99pwqj2rngz5wysjcgl8ph0000gn/T/yarn--1614689061406-0.29251695091521035/node
    Yarn: 1.22.4 - /var/folders/gh/yg99pwqj2rngz5wysjcgl8ph0000gn/T/yarn--1614689061406-0.29251695091521035/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Safari: 14.0.2

**Comment by ascorbic** [comment]
Hi. Thanks for the report. I know exactly what's causing it, and it's something I did to fix another bug! I'll take a look today.

**Comment by huangsam** [comment]
@ascorbic thanks for taking a look into it!

Just as a FYI, I encountered a similar issue on my personal website, where my `placeholder` attribute for the GraphQL query function is set to `BLURRED`.

Here's my GraphQL query for reference:

https://github.com/huangsam/huangsam.github.io/blob/main/src/pages/index.jsx#L65-L69

I notice the background color blinking (as mentioned by @laurenskling) in between the transition when clicking on the Gatsby `Link` component from the [About Me](https://sambyte.net/about/) page back to the home page.

Here's my `Link` declaration for reference:

https://github.com/huangsam/huangsam.github.io/blob/main/src/components/layout.jsx#L20

I hope the added context helps with your diagnosis / resolution.

**Comment by clariceabreu** [comment]
@ascorbic do you have any updates about this issue?
I'm facing the same problem.

**Comment by ascorbic** [comment]
@clariceabreu If you're using gatsby-image-background-slider, then you're using the old image component

**Comment by clariceabreu** [comment]
@ascorbic it is necessary to update the package on the `gatsby-image-background-slider' to fix the issue, right?

**Comment by stefanweck** [comment]
Here is a little (slowed down) screen recording, in which you can see that the blurred image totally disappears before the real image is faded in, resulting in a white flash.

https://user-images.githubusercontent.com/1083626/111142530-15557a00-8585-11eb-9b2d-b3274abad1b2.mov

**Comment by FlxAlbroscheit** [comment]
This problem remains even after pushing gatsby to v3.1.1.

**Comment by ascorbic** [comment]
@FlxAlbroscheit Which version of gatsby-plugin-image?

**Comment by FlxAlbroscheit** [comment]
Hi @ascorbic I'm fully upstream: gatsby@3.1.2; gatsby-plugin-image@1.1.2

**Comment by LekoArts** [comment]
The PR wasn't released in a stable release yet, you'll need to install `gatsby-plugin-image@next`

**Comment by FlxAlbroscheit** [comment]
Updating to gatsby-plugin-image@next resolves the problem indeed. Thanks a lot!
