### ISSUE TITLE
Is there a way to access the fields created by the gatsby-remark-transformer plugin?

### ISSUE THREAD

**Issue by jim-moody** [gatsbyjs/gatsby#2991]
I want to access the `headings` field on a Markdown node for a plugin but the field is not accessible in the `onCreateNode` function.

I can see that the field is created by the `gatsby-remark-transformer` plugin so how can I have my plugin access the node after the field has been created?

Sample gatsby-node  code:

```js
exports.onCreateNode = ({ node, boundActionCreators }) => {
  if (node.internal.type !== 'MarkdownRemark') {
    return;
  }
  const { createNodeField } = boundActionCreators;

  const headingSlugs = node.headings.map((heading) => { // this returns headings undefined
    return slugger.slug(heading.value);
  });
  createNodeField({
    node,
    name: `headingSlugs`,
    value: headingSlugs,
  });
};
```

**Comment by rudasn** [comment]
`remark-transfomer` parses headings, toc, and html from markdown when a node is first queried for (not on creation).

I haven't tried it, and I'm not sure if it's the right approach, but you could query for the created node (in onCreateNode) and then process the result.
