### ISSUE TITLE
[gatsby-plugin-google-gtag] – inaccurate page title reporting

### ISSUE THREAD

**Issue by bryndyment** [gatsbyjs/gatsby#29913]
## Description

A significant number of reported page titles in Google Analytics are out of sync with the actual route.

### Steps to reproduce

- create a basic multi-page Gatsby site
- set up gatsby-plugin-google-gtag with default settings
- watch Google Analytics → Realtime → Content → Active Users
- change routes on the Gatsby site (production build) and watch out-of-sync `Page` and `Page Title` columns

### Expected result

`Page` and `Page Title` columns should be consistently in sync.

### Actual result

`Page` and `Page Title` columns are not consistently in sync.

### Environment

  System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 84.0.2
    Safari: 14.0.3
  npmPackages:
    gatsby: 2.32.9 => 2.32.9 
    gatsby-image: 2.11.0 => 2.11.0 
    gatsby-plugin-better-jss: 1.0.3 => 1.0.3 
    gatsby-plugin-google-gtag: 2.8.0 => 2.8.0 
    gatsby-plugin-layout: 1.10.0 => 1.10.0 
    gatsby-plugin-netlify: 2.11.0 => 2.11.0 
    gatsby-plugin-react-helmet: 3.10.0 => 3.10.0 
    gatsby-plugin-sharp: 2.14.3 => 2.14.3 
    gatsby-source-filesystem: 2.11.1 => 2.11.1 
    gatsby-transformer-sharp: 2.12.0 => 2.12.0

**Comment by DevelopingUK** [comment]
@bryndyment 

I have a similar problem, where it's not even showing the page titles, I have all other data except what pages users are on.

Any idea on a fix or is it better to uninstall this and use a better option?

Thanks.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!
