### ISSUE TITLE
Remove any instance of Pair Programming from docs

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#29927]
# Description

In the feature comparison section of the site comparing Gatsby to other web solutions, in the Community section, a thing that Gatsby "offers" is Pair Programming sessions, but that is not the case anymore with https://github.com/gatsbyjs/gatsby/pull/29454, so that field should be removed.

![Screen Shot 2021-03-02 at 12 23 20 PM](https://user-images.githubusercontent.com/3685876/109688279-1aacd080-7b52-11eb-8735-737f91dea8b1.png)

**Comment by LekoArts** [comment]
Thanks for the notice! Forgot we had that there, too.
