### ISSUE TITLE
[3.0.next] peer deps broken in examples/creating-source-plugins

### ISSUE THREAD

**Issue by drkstr101** [gatsbyjs/gatsby#29929]
➜  creating-source-plugins yarn list graphql
```shell
yarn list v1.22.10
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ graphql-yoga@1.18.3
│  └─ graphql@14.7.0
└─ graphql@15.5.0
```

➜  creating-source-plugins yarn why graphql
```
yarn why v1.22.10
[1/4] Why do we have the module "graphql"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "graphql@15.5.0"
info Has been hoisted to "graphql"
info Reasons this module exists
   - "workspace-aggregator-512db251-85d6-40cf-8140-cb4c74b83fcc" depends on it
   - Hoisted from "_project_#source-plugin#graphql"
   - Hoisted from "_project_#example-site#gatsby#graphql"
   - Hoisted from "_project_#api#graphql-yoga#@types#graphql#graphql"
   - Hoisted from "_project_#example-site#gatsby#gatsby-cli#gatsby-recipes#graphql"
info Disk size without dependencies: "3.47MB"
info Disk size with unique dependencies: "3.47MB"
info Disk size with transitive dependencies: "3.47MB"
info Number of shared dependencies: 0
=> Found "graphql-yoga#graphql@14.7.0"
info This module exists because "_project_#api#graphql-yoga" depends on it.
info Disk size without dependencies: "3.11MB"
info Disk size with unique dependencies: "3.21MB"
info Disk size with transitive dependencies: "3.21MB"
info Number of shared dependencies: 1
Done in 0.98s.
```

Should I force resolution to `graphql@14.7.0` or `15.5.0`?

Cheers, and thank you for all the new goodies!!

**Comment by vladar** [comment]
Yes, this is a known problem. You will have to update `graphql-yoga` too. Or stick with `yarn resolutions` as suggested in the migration guide: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#handling-dependencies-for-plugins-that-are-not-yet-updated

Gatsby needs `"graphql": "^15.4.0"`, so try that first (also GraphQL 14 is mostly compatible with it)

**Comment by drkstr101** [comment]
My mistake! I did try looking for a migration gudie, but only found v1->v2.

Thanks for the link!

**Comment by vladar** [comment]
Just curious, where did you look? We may want to put v2->v3 migration guide there as well 😅

**Comment by drkstr101** [comment]
Google was a total bust. I think its just to new. And I just came back here to grab the link again when I couldn't find it poking around a few clicks in docs/. I looked in docs/contributing/ first, but that was probably a poor choice. Refernce/ makes more sense.

Cheers!

PS: I would just frontpage that awesome announcement with a call to action on the migration guide! :D

**Comment by drkstr101** [comment]
@vladar Would you mind if I, or someone affiliated with Gatsby, post a link to the announcement on Hacker News? If migration guide link is in ther it will get boosted quite a bit if the story gets picked up.

**Comment by vladar** [comment]
@drkstr101 Sounds good, feel free to post it 👍 

- [Announcement blog post](https://www.gatsbyjs.com/blog/gatsby-v3)
- [v3.0 release notes](https://www.gatsbyjs.com/docs/reference/release-notes/v3.0/)

Any of those has a link to the migration guide.
