### ISSUE TITLE
Gatsby v3 - CSS modules import fails

### ISSUE THREAD

**Issue by anantoghosh** [gatsbyjs/gatsby#29931]
## Description
Importing CSS Modules in gatsby v3 is failing with `warn Attempted import error: './index.module.css' does not contain a default export (imported as 'styles')`. It works with v2.

### Steps to reproduce

1. Create new gatsby project: `npm init gatsby`
2. Create a module css file `index.module.css`
3. Import and use this file

```js
import styles from './index.module.css`
```

Minimal Repo:
https://github.com/anantoghosh/gatsby-v3-modules

### Expected result

Modules work as in v2.

### Actual result

```sh
warn Attempted import error: './index.module.css' does not contain a default export (imported as 'styles').
success Building HTML renderer - 0.898s
failed Building static HTML for pages - 0.189s

 ERROR #95313

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


   5 | const IndexPage = () => {
   6 |   return (
>  7 |     <main className={styles.hello}>
     |                      ^
   8 |     </main>
   9 |   )
  10 | }


  WebpackError: TypeError: Cannot read property 'hello' of undefined

  - index.js:7
    test_build_3/src/pages/index.js:7:22

  - extends.js:8
    [test_build_3]/[@babel]/runtime/helpers/extends.js:8:1

  - extends.js:14
    [test_build_3]/[@babel]/runtime/helpers/extends.js:14:1

  - extends.js:13
    [test_build_3]/[@babel]/runtime/helpers/extends.js:13:1

  - static-entry.js:263
    test_build_3/.cache/static-entry.js:263:20

  - history.js:26
    [test_build_3]/[@gatsbyjs]/reach-router/es/lib/history.js:26:1



error Command failed with exit code 1.
```

```css
/* index.module.css */
.hello {
  background-color: black;
}

```
### Environment
Using yarn 1.

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  Binaries:
    Node: 14.15.1 - C:\Users\A\AppData\Local\Temp\yarn--1614712526746-0.07679433515396306\node.CMD
    Yarn: 1.22.5 - C:\Users\A\AppData\Local\Temp\yarn--1614712526746-0.07679433515396306\yarn.CMD
    npm: 6.14.8 - ~\nvm\nodejs\bin\npm.CMD
  Languages:
    Python: 3.8.2
  Browsers:
    Chrome: 88.0.4324.190
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.74)
  npmPackages:
    gatsby: ^3.0.0 => 3.0.0

**Comment by martinhj** [comment]
Experience the same (w/ gatsby-plugin-sass 4.0.0)

**Comment by vladar** [comment]
Hey 👋 Glad you're trying Gatsby v3. Please, check out the migration guide about this: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#css-modules-are-imported-as-es-modules

**Comment by anantoghosh** [comment]
@vladar ah ok, thank you.
I did look at the docs first to verify if I was doing something wrong. https://www.gatsbyjs.com/docs/recipes/styling-css#using-css-modules but those are not up to date.
Closing.

**Comment by LekoArts** [comment]
Yeah, thanks for flagging that!
