### ISSUE TITLE
Gatsby v3 Migration 📌

### ISSUE THREAD

**Issue by vladar** [gatsbyjs/gatsby#29932]
## Summary

Gatsby v3 is here 🎉 Some useful links below:

- [Announcement blog post](https://www.gatsbyjs.com/blog/gatsby-v3)
- [v3.0 release notes](https://www.gatsbyjs.com/docs/reference/release-notes/v3.0/)
- **[v2 to v3 migration guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/)**

If you have any issues with migration - please let us know and create a new issue.

**Comment by TylerBarnes** [comment]
Oops, accidentally unpinned this!
