### ISSUE TITLE
access to img with her URI

### ISSUE THREAD

**Issue by pinaudnico** [gatsbyjs/gatsby#2993]
Gatsby generate a link to my img which looks like that : http://localhost:8000/static/photo2.38a4b984.jpg
I want to know the part 38a4b984 of my img to rebuild it, how can I do that ?
Thanks for help

**Comment by benjaminhoffman** [comment]
@pinaudnico that part -- `38a4b984` -- is called the image "hash".  if you change the file, that string will change too.  if you dont change the file, the string stays the same.  you can link to the image as normal in your html/css/js, gatsby will make sure to update your links with the image hash.

may i ask why you need this value?

**Comment by pinaudnico** [comment]
Thanks for the info. Yes you can ask. I'm coding an app I want to change picture on the screen with geoloc points. It is built in react with gatsby. Gatsby uses webpack to data uri pictures. So it is coded with the adress just up there. Ad I want it to be dynamical, I must find the hash code to build this adress. Now I know it is hash, I can find on npm something which make hash code for me I think.

**Comment by benjaminhoffman** [comment]
okay cool.  if you are happy with the result, please don't forget to close this issue!  thank you. :)
