### ISSUE TITLE
Pages are not generated when building Gatsby V2

### ISSUE THREAD

**Issue by marcus13371337** [gatsbyjs/gatsby#29948]
## Description
Sometimes when running `gatsby build` it seems as not all of our pages are generated but the build command does not report any errors. We have about ~20k pages, and there are approx 2/3 random pages that are missing sometimes

### Steps to reproduce
Run `gatsby build` with new input data every hour for about a day, then suddenly some pages are not generated without any error code.

### Expected result
All pages should be generated or gatsby should throw an error

### Actual result
Some pages are missing in the final build

### Environment
mhart/alpine-node:12.9

Sidenote, it seems as we have some memory issues as we occasionally run into the following error:
```
error Building static HTML failed for path \"/XXXX/yyyy/
```
However, running the build locally with the same input does not cause the same error at those times. It seems as that is the start of the problem, any builds after that but with the same `.cache` or `public` folder may risk of missing pages when building

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. The way I understand your issue this only happens on your build server, not locally, right? To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

As for now your setup is a blackbox to us and we don't have a good way to look into it yet :)

[reproduction]: https://gatsby.dev/reproduction

**Comment by marcus13371337** [comment]
Yep, agree it's hard to debug for both for us and even harder for you. I will try to get a minimal reproduction.

Not sure if it only happens on our build-server as I haven't been rerunning the build-process over and over

**Comment by LekoArts** [comment]
Would be interesting to know if you can also see this behavior locally then if you run it multiple times

**Comment by marcus13371337** [comment]
I've added a fix to our build server which is that if it ever fails for some reason it will clear the `.cache` and the `public` directory. I will see if that fixes the issue :)

**Comment by marcus13371337** [comment]
Update: added a validation step before we deploy our website, which is to validate the expected number of pages (based on our input data) and compare that to the number of pages that are generated in the public-directory:
```
 success open and validate gatsby-configs - 0.631s
 success load plugins - 0.132s
success onPreInit - 0.036s
success delete html and css files from previous builds - 3.865s
success initialize cache - 0.005s
success copy gatsby files - 0.039s
success onPreBootstrap - 0.010s
success createSchemaCustomization - 0.004s
verbose 153.326997487 Checking for deleted pages
verbose 153.329443902 Deleted 0 pages
verbose 153.329630888 Found 0 changed pages
success Checking for changed pages - 0.001s
success source and transform nodes - 142.509s
success building schema - 58.715s
info Total nodes: 109015, SitePage nodes: 23472
verbose 220.859184319 Number of node types: 18. Nodes per type: SitePage: 23472, SitePlugin: 43, Site: 1, SiteBuildMetadata: 1, Directory: 1656, File: 36254, ProductPage: 22139, BasePageSlug: 23784, BrandStartPage: 595, RootPage: 7, ContentPage: 667, CampaignPage: 74, CategoryPage: 300, Footer: 1, Header: 1, StartPage: 1, Configuration: 18, CampaignStartPage: 1
success createPages - 8.810s
verbose 220.859610674 Checking for deleted pages
verbose 220.862449008 Deleted 0 pages
verbose 220.866731255 Found 23471 changed pages
success Checking for changed pages - 0.004s
success createPagesStatefully - 0.080s
success Cleaning up stale page-data - 1.180s
success update schema - 0.160s
success onPreExtractQueries - 0.000s
success extract queries from components - 0.626s
success write out redirect data - 0.005s
success onPostBootstrap - 0.000s
info bootstrap finished - 222.934s
success run static queries - 0.125s - 1/1 8.00/s
success run page queries - 28.069s - 14588/14588 519.72/s
success write out requires - 0.320s
success Building production JavaScript and CSS bundles - 14.300s
success Building HTML renderer - 7.560s
success Building static HTML for pages - 167.638s - 23473/23473 140.02/s
success onPostBuild - 0.132s
info Done building in 463.134675326 sec
```

My validation step:
gatsbyPages: 23473
gatsbyPageDatas: 23473
pagesThatShouldHaveBeenGenerated: 23484

we have 4 pages that gatsby generates without any input data, so 23484 + 4 = 23488 should be equal to the number of pages that gatsby generates which is only 23473, so we are missing 15 pages

In the previous build, with the same `.cache` and `public` directory, we had 23488 pages generated which is the correct number. So it seems as there is a problem with the `gatsby-source-filesystem` which we use to load a lot of yaml-files
