### ISSUE TITLE
Attempted import error when importing a css module

### ISSUE THREAD

**Issue by carljustineoyales** [gatsbyjs/gatsby#29940]
## Description

I'm getting an import error when using a css module and importing it to a component using
```
import styles from '../styles/home.module.css
```

home.module.css
```
.header {
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-gap: 40px;
  align-items: center;
}
```

and applying it to a component
```
...
<section className={styles.header}>
...
```

### Steps to reproduce

- Create a new Gatsby site with a starter(hello-world repo)
- Create a style directory with a css module (<filename>.module.css)
- import that module in a component (import styles from "../styles/filename.module.css")
- run development

### Expected result

it should style the component using `className={style.<class>}`

### Actual result

I'm getting an Import error
```
warn Attempted import error: '../styles/<filename>.module.css' does not contain a default
export (imported as 'styles').
success Re-building development bundle - 0.402s
```

### Environment

System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 AMD Ryzen 3 3200G with Radeon Vega Graphics
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.81)
  npmPackages:
    gatsby: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby-cli: 3.0.0

**Comment by LekoArts** [comment]
Hi, thanks for the issue and upgrading to v3! As with https://github.com/gatsbyjs/gatsby/issues/29940 it's a breaking change between v2 and v3.

You can learn more here: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#css-modules-are-imported-as-es-modules
