### ISSUE TITLE
Hot reloading not working with PageQueries with Safari on Gatsby v3

### ISSUE THREAD

**Issue by Oliweer** [gatsbyjs/gatsby#29952]
## Description

Since the new updates Safari seems to have issues with hot reloading, i made a mininal reproduction, it may be related to a similar issue [on Vue](https://github.com/vuejs/vue-cli/issues/1132) and they say it's due to how safari handles cache

### Steps to reproduce

gatsby new gatsby-starter-blog https://github.com/gatsbyjs/gatsby-starter-blog
gatsby develop
While its running, change the pageQuery in src/pages/index.js from
`allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC }) {`
to
`allMarkdownRemark(sort: { fields: [frontmatter___date], order: ASC }) {`

### Expected result

It should display the blog posts in a different order

### Actual result

You get an Unhandled Runtime Error, but if you refresh the page it works.

<img width="711" alt="Screenshot 2021-03-03 at 10 53 44" src="https://user-images.githubusercontent.com/5395484/109789969-290df180-7c11-11eb-86fd-ba975285e3d9.png">

However if you now change back to `allMarkdownRemark(sort: { fields: [frontmatter___date], order: DESC }) {` you'll get this and refreshing doesn't help anymore

<img width="701" alt="Screenshot 2021-03-03 at 11 02 01" src="https://user-images.githubusercontent.com/5395484/109789919-1dbac600-7c11-11eb-9c4b-0ceff7b98d42.png">

If you use Empty Caches (shift-command-E) and reload it works again.

### Environment

  System:
    OS: macOS 11.2.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.4.0 - ~/.nvm/versions/node/v15.4.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.4 - ~/.nvm/versions/node/v15.4.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 85.0.1
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.0 => 3.0.0 
    gatsby-plugin-feed: ^3.0.0 => 3.0.0 
    gatsby-plugin-gatsby-cloud: ^2.0.0 => 2.0.0 
    gatsby-plugin-google-analytics: ^3.0.0 => 3.0.0 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-remark-copy-linked-files: ^3.0.0 => 3.0.0 
    gatsby-remark-images: ^4.0.0 => 4.0.0 
    gatsby-remark-prismjs: ^4.0.0 => 4.0.0 
    gatsby-remark-responsive-iframe: ^3.0.0 => 3.0.0 
    gatsby-remark-smartypants: ^3.0.0 => 3.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-remark: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0

**Comment by Oliweer** [comment]
This also happens when you edit gatsby-browser.js, except it doesn't throw an error until you refresh the page

**Comment by LekoArts** [comment]
Ok, so the linked PR fixes showing the overlay for now. But hot reloading doesn't quite work everywhere yet, so will have to investigate a bit more.

**Comment by Isidoria** [comment]
I've had the same issue trying to reproduce the few lines of code from the Gatsby tutorial https://www.gatsbyjs.com/docs/tutorial/part-one/#linking-between-pages using Safari & trying to access http://localhost:8000/contact/

Thanks a lot for opening this issue ! I've switched to Chrome & it works like a charm <3 : )

**Comment by beamercola** [comment]
Does anybody have a fix for this?  I'm having to `yarn clean` and remove cache every ~5 minutes.

I don't have any lowercase components.  Though I am organizing components by `src/components/Box/index.js` and importing them as `import Box from "components/Box"`, is that a problem?  I thought this was standard (I have a companion `index.stories.js`)

**Comment by pragmaticpat** [comment]
Our recommendation at this time is to use an alternative available browser, such as Chrome ( or other Chromium-based browser ) or Firefox. We won't be pursuing this issue further at this time.
