### ISSUE TITLE
Cannot find @reach/router in gatsby-link

### ISSUE THREAD

**Issue by shtelzerartem** [gatsbyjs/gatsby#29964]
## Description

Migrated to gatsby 3, now getting this issue 

```
Error in "C:\projects\onlixe\blog-insiders\insiders-template-react\gatsby-node.js": Cannot find module '@reach/router'
Require stack:
- C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby-link\index.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\cache-dir\commonjs\gatsby-browser-entry.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\gatsby-node.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\bootstrap\resolve-module-exports.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\services\initialize.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\services\index.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\state-machines\develop\services.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\state-machines\develop\index.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\commands\develop-process.js
- C:\projects\onlixe\blog-insiders\insiders-template-react\.cache\tmp-23300-an3qIDriMlhr



  Error: Cannot find module '@reach/router'
  Require stack:
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby-link\index.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\cache-dir\commonjs\gatsby-browser-entry.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\gatsby-node.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\bootstrap\resolve-module-exports.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\services\initialize.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\services\index.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\state-machines\develop\services.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\state-machines\develop\index.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\dist\commands\develop-process.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\.cache\tmp-23300-an3qIDriMlhr

  - loader.js:794 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:794:15

  - loader.js:687 Function.Module._load
    internal/modules/cjs/loader.js:687:27

  - loader.js:849 Module.require
    internal/modules/cjs/loader.js:849:19

  - v8-compile-cache.js:159 require
    [insiders-template-react]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - index.js:22 Object.<anonymous>
    [insiders-template-react]/[gatsby-link]/index.js:22:15

  - v8-compile-cache.js:192 Module._compile
    [insiders-template-react]/[v8-compile-cache]/v8-compile-cache.js:192:30

  - loader.js:973 Object.Module._extensions..js
    internal/modules/cjs/loader.js:973:10

  - loader.js:812 Module.load
    internal/modules/cjs/loader.js:812:32

  - loader.js:724 Function.Module._load
    internal/modules/cjs/loader.js:724:14

  - loader.js:849 Module.require
    internal/modules/cjs/loader.js:849:19

  - v8-compile-cache.js:159 require
    [insiders-template-react]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - gatsby-browser-entry.js:15 Object.<anonymous>
    [insiders-template-react]/[gatsby]/cache-dir/commonjs/gatsby-browser-entry.js:15:43

  - v8-compile-cache.js:192 Module._compile
    [insiders-template-react]/[v8-compile-cache]/v8-compile-cache.js:192:30

  - loader.js:973 Object.Module._extensions..js
    internal/modules/cjs/loader.js:973:10

  - loader.js:812 Module.load
    internal/modules/cjs/loader.js:812:32

  - loader.js:724 Function.Module._load
    internal/modules/cjs/loader.js:724:14


not finished load plugins - 0.999s

error Command failed with exit code 1.
```

### Environment

```
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.1 - /c/Users/Artem Shteltser/AppData/Local/Programs/Python/Python39/python
  Browsers:
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^3.0.0 => 3.0.0
    gatsby-image: ^3.0.0 => 3.0.0
    gatsby-link: ^3.0.0 => 3.0.0
    gatsby-plugin-emotion: ^6.0.0 => 6.0.0
    gatsby-plugin-env-variables: ^2.0.0 => 2.0.0
    gatsby-plugin-eslint: ^3.0.0 => 3.0.0
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-portal: ^1.0.7 => 1.0.7
    gatsby-plugin-postcss: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-source-graphql: ^3.0.0 => 3.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
```

**Comment by pieh** [comment]
Do you have `gatsby-link` declared separately in your `package.json`? If so please remove it and adjust imports to use `Link` component from `gatsby` (this was changed when migrating from gatsby v1 to v2 - https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v1-to-v2/#import-link-from-gatsby - it might have worked but it had opportunity for issues when using `gatsby-link` separately).

If above is not the case - can you paste output of:
 - (if using npm): `npm list gatsby-link`
 - (if using yarn) - `yarn why gatsby-link`
?

**Comment by shtelzerartem** [comment]
@pieh yes, I had gatsby-link in package.json added it specifically to test, if it will fix my problem. Unfortunately, not, not the case.

Here is ```yarn why gatsby-link``` output:
```
yarn why v1.22.5
[1/4] Why do we have the module "gatsby-link"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "gatsby-link@3.0.0"
info Reasons this module exists
   - "gatsby" depends on it
   - Hoisted from "gatsby#gatsby-link"
info Disk size without dependencies: "68KB"
info Disk size with unique dependencies: "936KB"
info Disk size with transitive dependencies: "2.39MB"
info Number of shared dependencies: 9
Done in 0.83s.
```

**Comment by pieh** [comment]
After looking a bit more closely to stack trace - this caught my attention:

```
  - C:\projects\onlixe\blog-insiders\insiders-template-react\node_modules\gatsby\cache-dir\commonjs\gatsby-browser-entry.js
  - C:\projects\onlixe\blog-insiders\insiders-template-react\gatsby-node.js
```

Do you import/require anything from `gatsby-browser-entry.js` in your gatsby-node file? This seems to be direct cause as this code generally is not meant to be accessed in node environment without going through webpack. We had to actually vendor `@reach/router` ( https://github.com/gatsbyjs/gatsby/pull/29772 ) but we added webpack's alias for imports to `@react/router` to keep working in frontend code, but that alias won't work when things are imported in Node.js environment. If you do import anything - what do you import? Maybe we could provide better way to get access to that functionality without having to resort to importing frontend code in Node.js.

**Comment by pieh** [comment]
In referenced PR I noticed that we kept imports to `@react/router` for our frontend code that do work bacause of the alias, but seems like is the reason for the error, so I will go ahead and adjust all of those to use vendored package (probably tomorrow).

But I still want to stress that importing `gatsby-browser-entry` in Node.js code is likely not good idea and might cause troubles in the future if we ever add code that specifically depend on `window` or any browser specific APIs.

**Comment by shtelzerartem** [comment]
@pieh Doesn't look like I'm importing smth. That's all I have. 

```
require("dotenv").config(`./.env`);

const { graphql } = require("gatsby");

exports.createPages = async ({ actions }) => {
  const { createPage } = actions;
  const { PROJECT_ID } = process.env;

  const pages = await graphql(
    `
      query GET_PAGES_FOR_PROJECT($id: ID!) {
        swapi {
          insidersTemplates(publicationState: LIVE, where: { Project: { id: $id } }) {
            id
            Link
          }
          project(id: $id) {
            ProjectName
          }
        }
      }
    `,
    { id: PROJECT_ID }
  );

  console.log(pages);
  createPage({
    path: "/",
    component: path.resolve(`./src/IndexPage.js`),
  });
};
```

**Comment by shtelzerartem** [comment]
@pieh Sry, I must be mistaken, here is the only import from ```gatsby-browser-entry.js``` - ```graphql```. Maybe it's the problem?

**Comment by pieh** [comment]
Ah, sorry - you are right - I thought it was direct import to that, but apparently we got wrong `main`/`module` entrypoints in gatsby's package.json - https://github.com/gatsbyjs/gatsby/blob/ba8a498c268694999bfa7961d41018b09b523779/packages/gatsby/package.json#L222-L223

In any case - did above code actually worked before? For `createPages` you should get `graphql` from arguments passed to it:

```diff
require("dotenv").config(`./.env`);

-const { graphql } = require("gatsby");
-
-exports.createPages = async ({ actions }) => {
+exports.createPages = async ({ actions, graphql }) => {
  const { createPage } = actions;
  const { PROJECT_ID } = process.env;

  const pages = await graphql(
    `
      query GET_PAGES_FOR_PROJECT($id: ID!) {
        swapi {
          insidersTemplates(publicationState: LIVE, where: { Project: { id: $id } }) {
            id
            Link
          }
          project(id: $id) {
            ProjectName
          }
        }
      }
    `,
    { id: PROJECT_ID }
  );

  console.log(pages);
  createPage({
    path: "/",
    component: path.resolve(`./src/IndexPage.js`),
  });
};
```

https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#createPages for reference

**Comment by shtelzerartem** [comment]
@pieh Hey, it works! Thank you a lot! Can I close this issue?

**Comment by talohana** [comment]
I also running into this problem, for me tests failing for components that have
- `import { Link } from 'gatsby';`
- `import { graphql, useStaticQuery } from 'gatsby';`

**Comment by codepunkt** [comment]
The problem I see is that `gatsby-link` imports from `@reach/router` here:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-link/src/index.js#L3

But it doesn't have a dependency on `@reach/router` at all:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-link/package.json

Is there some kind of webpack alias shenanigans or is this just missing?

**Comment by LekoArts** [comment]
> @pieh Hey, it works! Thank you a lot! Can I close this issue?

Not yet, we'll need to fix our aliasing or rewrite the imports to our vendored package

**Comment by pieh** [comment]
> Is there some kind of webpack alias shenanigans or is this just missing?

It is webpack alias shenanigans - https://github.com/gatsbyjs/gatsby/blob/ec57fb2e8b92c99db991e226383cfd7642eb511f/packages/gatsby/src/utils/webpack.config.js#L429

For cases other than one originally reported (importing `gatsby` in `gatsby-node`) we also mentioned need for alias for scenarios when same code is ran outside of gatsby (like test setups) in https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/reference/release-notes/migrating-from-v2-to-v3.md#reach-router

I can't really explain https://github.com/gatsbyjs/gatsby/issues/30029 issue - as that is using Gatsby's webpack and still alias doesn't seem to have effect, but I just opened https://github.com/gatsbyjs/gatsby/pull/30033 that adjust gatsby runtime imports to not have to rely on the alias

**Comment by codepunkt** [comment]
Sounds good. How can I test this, is there a (prerelease) version for it?

**Comment by fshowalter** [comment]
Confirmed this fixes my local install, HOWEVER, if you `import { useLocation } from "@reach/router";` in a component (say in an SEO component to set the `og:url` property) it will still complain `Can't resolve '@reach/router' in '/path/to/your/component'`. Changing your reference to `import { useLocation } from "@gatsbyjs/reach-router";` will fix it, but typescript will complain about no type definitions for `@gatsbyjs/reach-router` can we fix that?

**Comment by fshowalter** [comment]
Dug deeper. Looks like `gatsby-plugin-linaria` is removing the alias https://github.com/cometkim/gatsby-plugin-linaria/blob/e011a14eda9c7da99ab553aada921dffc2fdf5a6/src/gatsby-node.ts#L53. I've opened an issue here: https://github.com/cometkim/gatsby-plugin-linaria/issues/19#issuecomment-791614220

Other plugins may be doing similar shenanigans.

**Comment by codepunkt** [comment]
This whole aliasing of @reach/router sounds totally fishy and is a recipe to disaster and follow-up costs and problems imo.

**Comment by fshowalter** [comment]
Confirmed re-adding the alias in my own `onCreateWebpackConfig` in `gatsby-node.js` fixes everything, without needing the changes in #30033. That said, agree with codepunkt that it seems brittle and prone to breakage.

**Comment by talohana** [comment]
I am using TypeScript paths ([with code from this gist](https://gist.github.com/nerdyman/2f97b24ab826623bff9202750013f99e)) and merging webpack's alias rather than overriding it fixed the issue

```diff
+ exports.onCreateWebpackConfig = ({ actions, getConfig }) => {
+  const config = getConfig();

  actions.setWebpackConfig({
    resolve: {
      alias: {
+        ...config.resolve.alias,
        ...resolveTsconfigPathsToAlias(),
      },
    },
  });
};
```

**Comment by codepunkt** [comment]
I removed the code that removed the alias in my `node_modules/gatsby-plugin-linaria` to test out if this is the culprit - and it seems to be. However, now that my development build on gatsby v3 with `linaria` and `gatsby-plugin-linaria` runs, there is some other hidden error using linaria that leads to the site not rendering at all, leaving the `#__gatsby` HTML element empty (see #30045)

**Comment by fshowalter** [comment]
@talohana which issue were you referring to? If a plugin removes the `@reach/router` alias, it won't be present on the config you get in `onCreateWebpackConfig`, so you'll need to re-add it.

**Comment by vladar** [comment]
Published in `gatsby-link@3.0.1`, `gatsby-react-router-scroll@4.0.1`, ` gatsby@3.0.3`

**Comment by ichsanindraw** [comment]
hey I'm still facing this issue, can someone help me?

<img width="1145" alt="Screen Shot 2022-04-21 at 22 06 12" src="https://user-images.githubusercontent.com/98682801/164488276-ca0a4f1a-0e76-4df7-a974-46e494ed9067.png">

**Comment by arpitdalal** [comment]
I'm facing the above issue as well, updating gatsby and gatsby-* plugins
